Unreal Engine 5.6 C++ API: UE::Math::TTransform< T > Struct Template Reference
UE::Math::TTransform< T > Struct Template Reference
#include "TransformNonVectorized.h"
Public Types
using FReal = T
using TransformVectorRegister = TVectorRegisterType<T>
Public Member Functions
FORCEINLINE TTransform ()
Default constructor.
FORCEINLINE TTransform (const TMatrix< T > &InMatrix)
Constructor for converting a Matrix (including scale) into a TTransform<T>.
FORCEINLINE TTransform (const TQuat< T > &InRotation)
Constructor with an initial rotation.
FORCEINLINE TTransform (const TQuat< T > &InRotation, const TVector< T > &InTranslation, const TVector< T > &InScale3D=TVector< T >::OneVector)
Constructor with all components initialized.
FORCEINLINE TTransform (const TRotator< T > &InRotation)
Constructor with an initial rotation.
FORCEINLINE TTransform (const TRotator< T > &InRotation, const TVector< T > &InTranslation, const TVector< T > &InScale3D=TVector< T >::OneVector)
Constructor with all components initialized, taking a TRotator<T> as the rotation component.
template<typename FArg UE_REQUIRES>
TTransform (const TTransform< FArg > &From)
FORCEINLINE TTransform (const TVector< T > &InTranslation)
Constructor with an initial translation.
FORCEINLINE TTransform (const TVector< T > &InX, const TVector< T > &InY, const TVector< T > &InZ, const TVector< T > &InTranslation)
Constructor that takes basis axes and translation.
FORCEINLINE TTransform (ENoInit)
Constructor with leaving uninitialized memory.
FORCEINLINE void Accumulate (const TTransform< T > &Atom, FReal BlendWeight)
Accumulates another transform with this one, with a blending weight.
FORCEINLINE void Accumulate (const TTransform< T > &SourceAtom)
Accumulates another transform with this one.
FORCEINLINE void AccumulateWithAdditiveScale (const TTransform< T > &Atom, T BlendWeight)
Accumulates another transform with this one, with a blending weight.
FORCEINLINE void AccumulateWithShortestRotation (const TTransform< T > &DeltaAtom, FReal BlendWeight)
Accumulates another transform with this one, with an optional blending weight.
FORCEINLINE void AddToTranslation (const TVector< T > &DeltaTranslation)
Adjusts the translation component of this transformation.
FORCEINLINE void Blend (const TTransform< T > &Atom1, const TTransform< T > &Atom2, float Alpha)
Set this transform to the weighted blend of the supplied two transforms.
FORCEINLINE void BlendWith (const TTransform< T > &OtherAtom, float Alpha)
Set this Transform to the weighted blend of it and the supplied Transform.
FORCEINLINE void ConcatenateRotation (const TQuat< T > &DeltaRotation)
Concatenates another rotation to this transformation.
bool ContainsNaN () const
Checks the components for non-finite values (NaN or Inf).
FORCEINLINE void CopyRotation (const TTransform< T > &Other)
Copy rotation from another TTransform<T>.
FORCEINLINE void CopyRotationPart (const TTransform< T > &SrcBA)
Sets the Rotation and Scale3D of this transformation from another transform.
FORCEINLINE void CopyScale3D (const TTransform< T > &Other)
Copy scale from another TTransform<T>.
FORCEINLINE void CopyTranslation (const TTransform< T > &Other)
Copy translation from another TTransform<T>.
FORCEINLINE void CopyTranslationAndScale3D (const TTransform< T > &SrcBA)
Sets the Translation and Scale3D of this transformation from another transform.
bool DebugEqualMatrix (const TMatrix< T > &Matrix) const
Debug purpose only.
void DebugPrint () const
Does a debugf of the contents of this Transform.
FORCEINLINE void DiagnosticCheck_IsValid () const
FORCEINLINE void DiagnosticCheckNaN_All () const
FORCEINLINE void DiagnosticCheckNaN_Rotate () const
FORCEINLINE void DiagnosticCheckNaN_Scale3D () const
FORCEINLINE void DiagnosticCheckNaN_Translate () const
FORCEINLINE bool Equals (const TTransform< T > &Other, FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE bool EqualsNoScale (const TTransform< T > &Other, FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE FReal GetDeterminant () const
Calculate the determinant of this transformation.
FORCEINLINE TVector< T > GetLocation () const
FORCEINLINE T GetMaximumAxisScale () const
same version of TMatrix<T>::GetMaximumAxisScale function
FORCEINLINE T GetMinimumAxisScale () const
TTransform< T > GetRelativeTransform (const TTransform< T > &Other) const
TTransform< T > GetRelativeTransformReverse (const TTransform< T > &Other) const
FORCEINLINE TQuat< T > GetRotation () const
Returns the rotation component.
TransformVectorRegister GetRotationRegister () const
FORCEINLINE TVector< T > GetScale3D () const
Returns the Scale3D component.
FORCEINLINE TTransform< T > GetScaled (T Scale) const
Apply Scale to this transform.
FORCEINLINE TTransform< T > GetScaled (TVector< T > Scale) const
Apply Scale to this transform.
FORCEINLINE TVector< T > GetScaledAxis (EAxis::Type InAxis) const
FORCEINLINE TVector< T > GetTranslation () const
Returns the translation component.
TransformVectorRegister GetTranslationRegister () const
FORCEINLINE TVector< T > GetUnitAxis (EAxis::Type InAxis) const
FORCEINLINE bool Identical (const TTransform< T > *Other, uint32 PortFlags) const
bool InitFromString (const FString &InSourceString)
Acceptable form: "%f,%f,%f|%f,%f,%f|%f,%f,%f".
FORCEINLINE TTransform< T > Inverse () const
Convert this Transform to inverse.
FORCEINLINE TVector< T > InverseTransformPosition (const TVector< T > &V) const
Inverts the transform and then transforms V - correctly handles scaling in this transform.
FORCEINLINE TVector< T > InverseTransformPositionNoScale (const TVector< T > &V) const
FORCEINLINE TQuat< T > InverseTransformRotation (const TQuat< T > &Q) const
Inverse transform a rotation.
FORCEINLINE TVector< T > InverseTransformVector (const TVector< T > &V) const
Transform a direction vector by the inverse of this transform - will not take into account translation part.
FORCEINLINE TVector< T > InverseTransformVectorNoScale (const TVector< T > &V) const
FORCEINLINE bool IsRotationNormalized () const
Checks whether the rotation component is normalized or not.
bool IsValid () const
FORCEINLINE void LerpTranslationScale3D (const TTransform< T > &SourceAtom1, const TTransform< T > &SourceAtom2, ScalarRegister Alpha)
Set the translation and Scale3D components of this transform to a linearly interpolated combination of two other transforms.
FORCEINLINE void Mirror (EAxis::Type MirrorAxis, EAxis::Type FlipAxis)
FORCEINLINE void MultiplyScale3D (const TVector< T > &Scale3DMultiplier)
Scales the Scale3D component by a new factor.
FORCEINLINE void NormalizeRotation ()
Normalize the rotation component of this transformation.
FORCEINLINE TTransform< T > operator* (const TQuat< T > &Other) const
Return a transform that is the result of this multiplied by another transform (made only from a rotation).
FORCEINLINE TTransform< T > operator* (const TTransform< T > &Other) const
Return a transform that is the result of this multiplied by another transform.
FORCEINLINE TTransform< T > operator* (T Mult) const
FORCEINLINE void operator*= (const TQuat< T > &Other)
Sets this transform to the result of this multiplied by another transform (made only from a rotation).
FORCEINLINE void operator*= (const TTransform< T > &Other)
Sets this transform to the result of this multiplied by another transform.
FORCEINLINE TTransform< T > & operator*= (T Mult)
FORCEINLINE TTransform< T > operator+ (const TTransform< T > &Atom) const
Quaternion addition is wrong here.
FORCEINLINE TTransform< T > & operator+= (const TTransform< T > &Atom)
FORCEINLINE void RemoveScaling (FReal Tolerance=UE_SMALL_NUMBER)
FORCEINLINE bool RotationEquals (const TTransform< T > &Other, FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE TRotator< T > Rotator () const
FORCEINLINE bool Scale3DEquals (const TTransform< T > &Other, FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE void ScaleTranslation (const FReal &Scale)
FORCEINLINE void ScaleTranslation (const TVector< T > &InScale3D)
Scale the translation part of the Transform by the supplied vector.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
FORCEINLINE void SetComponents (const TQuat< T > &InRotation, const TVector< T > &InTranslation, const TVector< T > &InScale3D)
Sets the components.
void SetFromMatrix (const TMatrix< T > &InMatrix)
FORCEINLINE void SetIdentity ()
Sets the components to the identity transform: Rotation = (0,0,0,1) Translation = (0,0,0) Scale3D = (1,1,1)
FORCEINLINE void SetIdentityZeroScale ()
Sets the components to the 'additive' identity transform: Rotation = (0,0,0,1) Translation = (0,0,0) Scale3D = (0,0,0)
FORCEINLINE void SetLocation (const TVector< T > &Origin)
Set the translation of this transformation.
FORCEINLINE void SetRotation (const TQuat< T > &NewRotation)
Sets the rotation component.
void SetRotationRegister (TransformVectorRegister InRotation)
FORCEINLINE void SetScale3D (const TVector< T > &NewScale3D)
Sets the Scale3D component.
void SetToRelativeTransform (const TTransform< T > &ParentTransform)
Set current transform and the relative to ParentTransform.
FORCEINLINE void SetTranslation (const TVector< T > &NewTranslation)
Sets the translation component.
FORCEINLINE void SetTranslationAndScale3D (const TVector< T > &NewTranslation, const TVector< T > &NewScale3D)
Sets both the translation and Scale3D components at the same time.
void SetTranslationRegister (TransformVectorRegister InTranslation)
FString ToHumanReadableString () const
Convert TTransform<T> contents to a string.
FORCEINLINE TMatrix< T > ToInverseMatrixWithScale () const
Convert this Transform to matrix with scaling and compute the inverse of that.
FORCEINLINE TMatrix< T > ToMatrixNoScale () const
Convert this Transform to a transformation matrix, ignoring its scaling.
FORCEINLINE TMatrix< T > ToMatrixWithScale () const
Convert this Transform to a transformation matrix with scaling.
FString ToString () const
FORCEINLINE TVector4< T > TransformFVector4 (const TVector4< T > &V) const
Transform TVector4<T>
FORCEINLINE TVector4< T > TransformFVector4NoScale (const TVector4< T > &V) const
Transform homogenous TVector4<T>, ignoring the scaling part of this transform.
FORCEINLINE TVector< T > TransformPosition (const TVector< T > &V) const
FORCEINLINE TVector< T > TransformPositionNoScale (const TVector< T > &V) const
FORCEINLINE TQuat< T > TransformRotation (const TQuat< T > &Q) const
Transform a rotation.
FORCEINLINE TVector< T > TransformVector (const TVector< T > &V) const
FORCEINLINE TVector< T > TransformVectorNoScale (const TVector< T > &V) const
FORCEINLINE bool TranslationEquals (const TTransform< T > &Other, FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
Static Public Member Functions
static FORCEINLINE TVector< T > AddTranslations (const TTransform< T > &A, const TTransform< T > &B)
Add the translations from two TTransform<T>s and return the result.
static FORCEINLINE bool AnyHasNegativeScale (const TVector< T > &InScale3D, const TVector< T > &InOtherScale3D)
static FORCEINLINE bool AreRotationsEqual (const TTransform< T > &A, const TTransform< T > &B, FReal Tolerance=UE_KINDA_SMALL_NUMBER)
static FORCEINLINE bool AreScale3DsEqual (const TTransform< T > &A, const TTransform< T > &B, FReal Tolerance=UE_KINDA_SMALL_NUMBER)
static FORCEINLINE bool AreTranslationsEqual (const TTransform< T > &A, const TTransform< T > &B, FReal Tolerance=UE_KINDA_SMALL_NUMBER)
static FORCEINLINE void BlendFromIdentityAndAccumulate (TTransform< T > &FinalAtom, const TTransform< T > &SourceAtom, float BlendWeight)
Blends the Identity transform with a weighted source transform and accumulates that into a destination transform.
static FORCEINLINE TVector< T > GetSafeScaleReciprocal (const TVector< T > &InScale, FReal Tolerance=UE_SMALL_NUMBER)
static FORCEINLINE void Multiply (TTransform< T > *OutTransform, const TTransform< T > *A, const TTransform< T > *B)
Create a new transform: OutTransform = A * B.
static FORCEINLINE TVector< T > SubtractTranslations (const TTransform< T > &A, const TTransform< T > &B)
Subtract translations from two TTransform<T>s and return the difference.
Data Fields
friend Z_Construct_UScriptStruct_FTransform3d_Statics
friend Z_Construct_UScriptStruct_FTransform3f_Statics
friend Z_Construct_UScriptStruct_FTransform_Statics
Static Public Attributes
static const TTransform< T > Identity
The identity transformation (Rotation = TQuat<T>::Identity, Translation = TVector<T>::ZeroVector, Scale3D = (1,1,1)).
Protected Attributes
TQuat< T > Rotation
Rotation of this transformation, as a quaternion.
TVector< T > Scale3D
3D scale (always applied in local space) as a vector.
TVector< T > Translation
Translation of this transformation, as a vector.
Private Member Functions
FORCEINLINE bool Private_RotationEquals (const TQuat< T > &InRotation, const FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE bool Private_Scale3DEquals (const TVector< T > &InScale3D, const FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE bool Private_TranslationEquals (const TVector< T > &InTranslation, const FReal Tolerance=UE_KINDA_SMALL_NUMBER) const
Static Private Member Functions
static FORCEINLINE void ConstructTransformFromMatrixWithDesiredScale (const TMatrix< T > &AMatrix, const TMatrix< T > &BMatrix, const TVector< T > &DesiredScale, TTransform< T > &OutTransform)
Create a new transform from multiplications of given to matrices (AMatrix*BMatrix) using desired scale This is used by MultiplyUsingMatrixWithScale and GetRelativeTransformUsingMatrixWithScale This is only used to handle negative scale.
static void GetRelativeTransformUsingMatrixWithScale (TTransform< T > *OutTransform, const TTransform< T > *Base, const TTransform< T > *Relative)
Create a new transform: OutTransform = Base * Relative(-1) using the matrix while keeping the scale that's given by Base and Relative Please note that this operation is a lot more expensive than normal GetRelativeTrnasform.
static FORCEINLINE void MultiplyUsingMatrixWithScale (TTransform< T > *OutTransform, const TTransform< T > *A, const TTransform< T > *B)
Create a new transform: OutTransform = A * B using the matrix while keeping the scale that's given by A and B Please note that this operation is a lot more expensive than normal Multiply.
Friends
FArchive & operator<< (FArchive &Ar, TTransform< T > &M)
Detailed Description
template<typename T>
struct UE::Math::TTransform< T >
Definition at line 38 of file TransformNonVectorized.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TTransform< T >::FReal = T
Definition at line 44 of file TransformNonVectorized.h.
TransformVectorRegister
template<typename T> using UE::Math::TTransform< T >::TransformVectorRegister = TVectorRegisterType<T>
Definition at line 45 of file TransformNonVectorized.h.
Constructor & Destructor Documentation
TTransform() [1/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform () inline nodiscard
Default constructor.
Definition at line 113 of file TransformNonVectorized.h.
Referenced by ConstructTransformFromMatrixWithDesiredScale(), GetScaled(), GetScaled(), UE::Math::TTransform< double >::Inverse(), Multiply(), MultiplyUsingMatrixWithScale(), operator*(), operator*(), UE::Math::TTransform< double >::operator*(), operator*=(), operator*=(), and UE::Math::TTransform< double >::operator+().
TTransform() [2/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (const TVector< T > & InTranslation) inline explicit nodiscard
Constructor with an initial translation.
Parameters
InTranslation The value to use for the translation component
Definition at line 125 of file TransformNonVectorized.h.
TTransform() [3/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (ENoInit) inline explicit nodiscard
Constructor with leaving uninitialized memory.
Definition at line 136 of file TransformNonVectorized.h.
TTransform() [4/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (const TQuat< T > & InRotation) inline explicit nodiscard
Constructor with an initial rotation.
Parameters
InRotation The value to use for rotation component
Definition at line 155 of file TransformNonVectorized.h.
TTransform() [5/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (const TRotator< T > & InRotation) inline explicit nodiscard
Constructor with an initial rotation.
Parameters
InRotation The value to use for rotation component (after being converted to a quaternion)
Definition at line 168 of file TransformNonVectorized.h.
TTransform() [6/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (const TQuat< T > & InRotation, const TVector< T > & InTranslation, const TVector< T > & InScale3D = TVector<T>::OneVector) inline nodiscard
Constructor with all components initialized.
Parameters
InRotation The value to use for rotation component
InTranslation The value to use for the translation component
InScale3D The value to use for the scale component
Definition at line 183 of file TransformNonVectorized.h.
TTransform() [7/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (const TRotator< T > & InRotation, const TVector< T > & InTranslation, const TVector< T > & InScale3D = TVector<T>::OneVector) inline nodiscard
Constructor with all components initialized, taking a TRotator<T> as the rotation component.
Parameters
InRotation The value to use for rotation component (after being converted to a quaternion)
InTranslation The value to use for the translation component
InScale3D The value to use for the scale component
Definition at line 198 of file TransformNonVectorized.h.
TTransform() [8/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (const TMatrix< T > & InMatrix) inline explicit nodiscard
Constructor for converting a Matrix (including scale) into a TTransform<T>.
Definition at line 209 of file TransformNonVectorized.h.
TTransform() [9/10]
template<typename T> FORCEINLINE UE::Math::TTransform< T >::TTransform (const TVector< T > & InX, const TVector< T > & InY, const TVector< T > & InZ, const TVector< T > & InTranslation) inline nodiscard
Constructor that takes basis axes and translation.
Definition at line 216 of file TransformNonVectorized.h.
TTransform() [10/10]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TTransform< T >::TTransform (const TTransform< FArg > & From) inline explicit
Definition at line 1224 of file TransformNonVectorized.h.
Member Function Documentation
Accumulate() [1/2]
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::Accumulate (const TTransform< T > & Atom, FReal BlendWeight) inline
Accumulates another transform with this one, with a blending weight.
Let SourceAtom = Atom * BlendWeight Rotation is accumulated multiplicatively (Rotation = SourceAtom.Rotation * Rotation). Translation is accumulated additively (Translation += SourceAtom.Translation) Scale3D is accumulated multiplicatively (Scale3D *= SourceAtom.Scale3D)
Note: Rotation will not be normalized! Will have to be done manually.
Parameters
Atom The other transform to accumulate into this one
BlendWeight The weight to multiply Atom by before it is accumulated.
Definition at line 958 of file TransformNonVectorized.h.
Accumulate() [2/2]
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::Accumulate (const TTransform< T > & SourceAtom) inline
Accumulates another transform with this one.
Note
: Added template type function for Accumulate The template type isn't much useful yet, but it is with the plan to move forward to unify blending features with just type of additive or full pose Eventually it would be nice to just call blend and it all works depending on full pose or additive, but right now that is a lot more refactoring For now this types only defines the different functionality of accumulate
Rotation is accumulated multiplicatively (Rotation = SourceAtom.Rotation * Rotation) Translation is accumulated additively (Translation += SourceAtom.Translation) Scale3D is accumulated multiplicatively (Scale3D *= SourceAtom.Scale3D)
Parameters
SourceAtom The other transform to accumulate into this one
Definition at line 935 of file TransformNonVectorized.h.
AccumulateWithAdditiveScale()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::AccumulateWithAdditiveScale (const TTransform< T > & Atom, T BlendWeight) inline
Accumulates another transform with this one, with a blending weight.
Let SourceAtom = Atom * BlendWeight Rotation is accumulated multiplicatively (Rotation = SourceAtom.Rotation * Rotation). Translation is accumulated additively (Translation += SourceAtom.Translation) Scale3D is accumulated assuming incoming scale is additive scale (Scale3D *= (1 + SourceAtom.Scale3D))
When we create additive, we create additive scale based on [TargetScale/SourceScale -1] because that way when you apply weight of 0.3, you don't shrink. We only saves the % of grow/shrink when we apply that back to it, we add back the 1, so that it goes back to it. This solves issue where you blend two additives with 0.3, you don't come back to 0.6 scale, but 1 scale at the end because [1 + [1-1]*0.3 + [1-1]*0.3] becomes 1, so you don't shrink by applying additive scale
Note: Rotation will not be normalized! Will have to be done manually.
Parameters
Atom The other transform to accumulate into this one
BlendWeight The weight to multiply Atom by before it is accumulated.
Definition at line 1023 of file TransformNonVectorized.h.
AccumulateWithShortestRotation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::AccumulateWithShortestRotation (const TTransform< T > & DeltaAtom, FReal BlendWeight) inline
Accumulates another transform with this one, with an optional blending weight.
Rotation is accumulated additively, in the shortest direction (Rotation = Rotation +/- DeltaAtom.Rotation * Weight) Translation is accumulated additively (Translation += DeltaAtom.Translation * Weight) Scale3D is accumulated additively (Scale3D += DeltaAtom.Scale3D * Weight)
Parameters
DeltaAtom The other transform to accumulate into this one
Weight The weight to multiply DeltaAtom by before it is accumulated.
Definition at line 979 of file TransformNonVectorized.h.
Referenced by BlendTransform< ETransformBlendMode::Accumulate >().
AddToTranslation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::AddToTranslation (const TVector< T > & DeltaTranslation) inline
Adjusts the translation component of this transformation.
Parameters
DeltaTranslation The translation to add in the following fashion: Translation += DeltaTranslation
Definition at line 830 of file TransformNonVectorized.h.
Referenced by UE::Geometry::GetFKElement(), and UE::Geometry::GetShape().
AddTranslations()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::AddTranslations (const TTransform< T > & A, const TTransform< T > & B) inline static nodiscard
Add the translations from two TTransform<T>s and return the result.
Returns
A.Translation + B.Translation
Definition at line 840 of file TransformNonVectorized.h.
AnyHasNegativeScale()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::AnyHasNegativeScale (const TVector< T > & InScale3D, const TVector< T > & InOtherScale3D) static nodiscard
Definition at line 1235 of file TransformNonVectorized.h.
References FORCEINLINE, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by Multiply().
AreRotationsEqual()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::AreRotationsEqual (const TTransform< T > & A, const TTransform< T > & B, FReal Tolerance = UE_KINDA_SMALL_NUMBER) inline static nodiscard
Definition at line 683 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::RotationEquals().
AreScale3DsEqual()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::AreScale3DsEqual (const TTransform< T > & A, const TTransform< T > & B, FReal Tolerance = UE_KINDA_SMALL_NUMBER) inline static nodiscard
Definition at line 695 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Scale3DEquals().
AreTranslationsEqual()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::AreTranslationsEqual (const TTransform< T > & A, const TTransform< T > & B, FReal Tolerance = UE_KINDA_SMALL_NUMBER) inline static nodiscard
Definition at line 689 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::TranslationEquals().
Blend()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::Blend (const TTransform< T > & Atom1, const TTransform< T > & Atom2, float Alpha) inline
Set this transform to the weighted blend of the supplied two transforms.
Definition at line 375 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate().
BlendFromIdentityAndAccumulate()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::BlendFromIdentityAndAccumulate (TTransform< T > & FinalAtom, const TTransform< T > & SourceAtom, float BlendWeight) inline static
Blends the Identity transform with a weighted source transform and accumulates that into a destination transform.
DeltaAtom = Blend(Identity, SourceAtom, BlendWeight) FinalAtom.Rotation = DeltaAtom.Rotation * FinalAtom.Rotation FinalAtom.Translation += DeltaAtom.Translation FinalAtom.Scale3D *= DeltaAtom.Scale3D
Parameters
FinalAtom [in/out] The atom to accumulate the blended source atom into
SourceAtom The target transformation (used when BlendWeight = 1); this is modified during the process
BlendWeight The blend weight between Identity and SourceAtom
Definition at line 1085 of file TransformNonVectorized.h.
BlendWith()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::BlendWith (const TTransform< T > & OtherAtom, float Alpha) inline
Set this Transform to the weighted blend of it and the supplied Transform.
Definition at line 405 of file TransformNonVectorized.h.
ConcatenateRotation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::ConcatenateRotation (const TQuat< T > & DeltaRotation) inline
Concatenates another rotation to this transformation.
Parameters
DeltaRotation The rotation to concatenate in the following fashion: Rotation = Rotation * DeltaRotation
Definition at line 820 of file TransformNonVectorized.h.
ConstructTransformFromMatrixWithDesiredScale()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale (const TMatrix< T > & AMatrix, const TMatrix< T > & BMatrix, const TVector< T > & DesiredScale, TTransform< T > & OutTransform) static private
Create a new transform from multiplications of given to matrices (AMatrix*BMatrix) using desired scale This is used by MultiplyUsingMatrixWithScale and GetRelativeTransformUsingMatrixWithScale This is only used to handle negative scale.
Parameters
AMatrix first Matrix of operation
BMatrix second Matrix of operation
DesiredScale - there is no check on if the magnitude is correct here. It assumes that is correct.
OutTransform the constructed transform
Definition at line 1280 of file TransformNonVectorized.h.
References TTransform(), FORCEINLINE, UE::Math::TMatrix< T >::GetOrigin(), UE::Math::TMatrix< T >::GetScaledAxis(), UE::Math::TVector< T >::GetSignVector(), UE::Math::TMatrix< T >::RemoveScaling(), Rotation, Scale3D, UE::Math::TMatrix< T >::SetAxis(), Translation, EAxis::X, UE::Math::TVector< T >::X, EAxis::Y, UE::Math::TVector< T >::Y, EAxis::Z, and UE::Math::TVector< T >::Z.
Referenced by MultiplyUsingMatrixWithScale().
ContainsNaN()
template<typename T> bool UE::Math::TTransform< T >::ContainsNaN () const inline nodiscard
Checks the components for non-finite values (NaN or Inf).
Returns
Returns true if any component (rotation, translation, or scale) is not finite.
Definition at line 598 of file TransformNonVectorized.h.
Referenced by FCSPose< PoseType >::CalculateComponentSpaceTransform(), and UE::Math::TTransform< double >::IsValid().
CopyRotation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::CopyRotation (const TTransform< T > & Other) inline
Copy rotation from another TTransform<T>.
Definition at line 865 of file TransformNonVectorized.h.
CopyRotationPart()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::CopyRotationPart (const TTransform< T > & SrcBA) inline
Sets the Rotation and Scale3D of this transformation from another transform.
Parameters
SrcBA The transform to copy rotation and Scale3D from
Definition at line 1142 of file TransformNonVectorized.h.
CopyScale3D()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::CopyScale3D (const TTransform< T > & Other) inline
Copy scale from another TTransform<T>.
Definition at line 881 of file TransformNonVectorized.h.
CopyTranslation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::CopyTranslation (const TTransform< T > & Other) inline
Copy translation from another TTransform<T>.
Definition at line 811 of file TransformNonVectorized.h.
CopyTranslationAndScale3D()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::CopyTranslationAndScale3D (const TTransform< T > & SrcBA) inline
Sets the Translation and Scale3D of this transformation from another transform.
Parameters
SrcBA The transform to copy translation and Scale3D from
Definition at line 1156 of file TransformNonVectorized.h.
DebugEqualMatrix()
template<typename T> bool UE::Math::TTransform< T >::DebugEqualMatrix (const TMatrix< T > & Matrix) const nodiscard
Debug purpose only.
DebugPrint()
template<typename T> void UE::Math::TTransform< T >::DebugPrint () const
Does a debugf of the contents of this Transform.
DiagnosticCheck_IsValid()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::DiagnosticCheck_IsValid () const inline
Definition at line 109 of file TransformNonVectorized.h.
DiagnosticCheckNaN_All()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::DiagnosticCheckNaN_All () const inline
Definition at line 108 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::AccumulateWithAdditiveScale(), UE::Math::TTransform< double >::AccumulateWithShortestRotation(), InverseTransformPosition(), InverseTransformPositionNoScale(), InverseTransformVector(), InverseTransformVectorNoScale(), UE::Math::TTransform< double >::SetComponents(), UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy(), TransformFVector4(), TransformFVector4NoScale(), TransformPosition(), TransformPositionNoScale(), TransformVector(), and TransformVectorNoScale().
DiagnosticCheckNaN_Rotate()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::DiagnosticCheckNaN_Rotate () const inline
Definition at line 106 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::ConcatenateRotation(), UE::Math::TTransform< double >::CopyRotationPart(), UE::Math::TTransform< double >::GetRotation(), UE::Math::TTransform< double >::NormalizeRotation(), RemoveScaling(), and UE::Math::TTransform< double >::SetRotation().
DiagnosticCheckNaN_Scale3D()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::DiagnosticCheckNaN_Scale3D () const inline
Definition at line 107 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::CopyRotationPart(), UE::Math::TTransform< double >::CopyTranslationAndScale3D(), GetMaximumAxisScale(), GetMinimumAxisScale(), UE::Math::TTransform< double >::GetScale3D(), UE::Math::TTransform< double >::LerpTranslationScale3D(), UE::Math::TTransform< double >::MultiplyScale3D(), RemoveScaling(), UE::Math::TTransform< double >::SetScale3D(), and UE::Math::TTransform< double >::SetTranslationAndScale3D().
DiagnosticCheckNaN_Translate()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::DiagnosticCheckNaN_Translate () const inline
Definition at line 105 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::AddToTranslation(), UE::Math::TTransform< double >::CopyTranslationAndScale3D(), UE::Math::TTransform< double >::GetTranslation(), UE::Math::TTransform< double >::LerpTranslationScale3D(), ScaleTranslation(), ScaleTranslation(), UE::Math::TTransform< double >::SetLocation(), UE::Math::TTransform< double >::SetTranslation(), and UE::Math::TTransform< double >::SetTranslationAndScale3D().
Equals()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::Equals (const TTransform< T > & Other, FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Definition at line 721 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Identical().
EqualsNoScale()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::EqualsNoScale (const TTransform< T > & Other, FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Definition at line 733 of file TransformNonVectorized.h.
Referenced by FNetworkPredictionPhysicsState::StateIsConsistent().
GetDeterminant()
template<typename T> FORCEINLINE FReal UE::Math::TTransform< T >::GetDeterminant () const inline nodiscard
Calculate the determinant of this transformation.
Definition at line 582 of file TransformNonVectorized.h.
GetLocation()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::GetLocation () const inline nodiscard
Definition at line 571 of file TransformNonVectorized.h.
Referenced by FNetworkPredictionPhysicsState::MarshalPhysicsToComponent(), USceneComponent::SetRelativeTransform_Direct(), and DisplayClusterTypesConverter::ToHexString().
GetMaximumAxisScale()
template<typename T> T UE::Math::TTransform< T >::GetMaximumAxisScale () const inline nodiscard
same version of TMatrix<T>::GetMaximumAxisScale function
Returns
the maximum magnitude of all components of the 3D scale.
Definition at line 1581 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_Scale3D(), and Scale3D.
Referenced by FSphericalSector::TransformBy(), and UE::Math::TSphere< T >::TransformBy().
GetMinimumAxisScale()
template<typename T> T UE::Math::TTransform< T >::GetMinimumAxisScale () const inline nodiscard
Returns
the minimum magnitude of all components of the 3D scale.
Definition at line 1590 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_Scale3D(), and Scale3D.
GetRelativeTransform()
template<typename T> TTransform< T > UE::Math::TTransform< T >::GetRelativeTransform (const TTransform< T > & Other) const nodiscard
Referenced by FCSPose< PoseType >::GetLocalSpaceTransform().
GetRelativeTransformReverse()
template<typename T> TTransform< T > UE::Math::TTransform< T >::GetRelativeTransformReverse (const TTransform< T > & Other) const nodiscard
GetRelativeTransformUsingMatrixWithScale()
template<typename T> void UE::Math::TTransform< T >::GetRelativeTransformUsingMatrixWithScale (TTransform< T > * OutTransform, const TTransform< T > * Base, const TTransform< T > * Relative) static private
Create a new transform: OutTransform = Base * Relative(-1) using the matrix while keeping the scale that's given by Base and Relative Please note that this operation is a lot more expensive than normal GetRelativeTrnasform.
Parameters
OutTransform pointer to transform that will store the result of Base * Relative(-1).
BAse Transform Base.
Relative Transform Relative.
GetRotation()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TTransform< T >::GetRotation () const inline nodiscard
Returns the rotation component.
Returns
The rotation component
Definition at line 1109 of file TransformNonVectorized.h.
Referenced by InverseTransformRotation(), FNetworkPredictionPhysicsState::MarshalPhysicsToComponent(), UE::MovieScene::MultiChannelFromData(), FSkeletonRemapping::RetargetAdditiveTransformToTargetSkeleton(), FSkeletonRemapping::RetargetBoneTransformToTargetSkeleton(), DisplayClusterTypesConverter::ToHexString(), UE::Geometry::TFrame3< float >::Transform(), and TransformRotation().
GetRotationRegister()
template<typename T> TransformVectorRegister UE::Math::TTransform< T >::GetRotationRegister () const inline nodiscard
Definition at line 905 of file TransformNonVectorized.h.
GetSafeScaleReciprocal()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::GetSafeScaleReciprocal (const TVector< T > & InScale, FReal Tolerance = UE_SMALL_NUMBER) static nodiscard
Definition at line 1603 of file TransformNonVectorized.h.
References FORCEINLINE, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Math::TTransform< double >::Inverse(), InverseTransformPosition(), and InverseTransformVector().
GetScale3D()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::GetScale3D () const inline nodiscard
Returns the Scale3D component.
Returns
The Scale3D component
Definition at line 1131 of file TransformNonVectorized.h.
Referenced by FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms(), UDecalComponent::GetTransformIncludingDecalSize(), UE::MovieScene::MultiChannelFromData(), FRootMotionReset::ResetRootBoneForRootMotion(), FSkeletonRemapping::RetargetAdditiveTransformToTargetSkeleton(), FSkeletonRemapping::RetargetBoneTransformToTargetSkeleton(), USceneComponent::SetRelativeTransform_Direct(), UE::Geometry::FNegativeSpaceSampleSettings::SetResultTransform(), and DisplayClusterTypesConverter::ToHexString().
GetScaled() [1/2]
template<typename T> FORCEINLINE TTransform< T > UE::Math::TTransform< T >::GetScaled (T Scale) const nodiscard
Apply Scale to this transform.
Definition at line 1353 of file TransformNonVectorized.h.
References TTransform(), A, and FORCEINLINE.
GetScaled() [2/2]
template<typename T> FORCEINLINE TTransform< T > UE::Math::TTransform< T >::GetScaled (TVector< T > Scale) const nodiscard
Apply Scale to this transform.
Definition at line 1368 of file TransformNonVectorized.h.
References TTransform(), A, and FORCEINLINE.
GetScaledAxis()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::GetScaledAxis (EAxis::Type InAxis) const nodiscard
Definition at line 1536 of file TransformNonVectorized.h.
References FORCEINLINE, TransformVector(), EAxis::X, and EAxis::Y.
GetTranslation()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::GetTranslation () const inline nodiscard
Returns the translation component.
Returns
The translation component
Definition at line 1120 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::GetLocation(), UE::MovieScene::MultiChannelFromData(), FSkeletonRemapping::RetargetAdditiveTransformToTargetSkeleton(), FSkeletonRemapping::RetargetBoneTransformToTargetSkeleton(), and FAtmosphereSetup::UpdateTransform().
GetTranslationRegister()
template<typename T> TransformVectorRegister UE::Math::TTransform< T >::GetTranslationRegister () const inline nodiscard
Definition at line 901 of file TransformNonVectorized.h.
GetUnitAxis()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::GetUnitAxis (EAxis::Type InAxis) const nodiscard
Definition at line 1553 of file TransformNonVectorized.h.
References FORCEINLINE, TransformVectorNoScale(), EAxis::X, and EAxis::Y.
Referenced by FBuoyancyComponentSim::UpdatePhysicsState().
Identical()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::Identical (const TTransform< T > * Other, uint32 PortFlags) const inline nodiscard
Definition at line 727 of file TransformNonVectorized.h.
InitFromString()
template<typename T> bool UE::Math::TTransform< T >::InitFromString (const FString & InSourceString)
Acceptable form: "%f,%f,%f|%f,%f,%f|%f,%f,%f".
Inverse()
template<typename T> FORCEINLINE TTransform< T > UE::Math::TTransform< T >::Inverse () const inline nodiscard
Convert this Transform to inverse.
Definition at line 307 of file TransformNonVectorized.h.
Referenced by UE::Geometry::IsInside().
InverseTransformPosition()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::InverseTransformPosition (const TVector< T > & V) const nodiscard
Inverts the transform and then transforms V - correctly handles scaling in this transform.
Definition at line 1456 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, GetSafeScaleReciprocal(), Rotation, Scale3D, and Translation.
Referenced by UE::Geometry::TPlane3< FVector::FReal >::InverseTransform(), UE::Math::TBox< T >::InverseTransformBy(), UE::Geometry::IsInside(), UE::Geometry::IsInside(), UE::Geometry::IsInside(), and FDisplayClusterShaderParameters_ICVFX::FCameraSettings::SetViewProjection().
InverseTransformPositionNoScale()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::InverseTransformPositionNoScale (const TVector< T > & V) const nodiscard
Definition at line 1465 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, Rotation, and Translation.
InverseTransformRotation()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TTransform< T >::InverseTransformRotation (const TQuat< T > & Q) const nodiscard
Inverse transform a rotation.
For example if this is a LocalToWorld transform, InverseTransformRotation(Q) would transform Q from world to local space.
Definition at line 1496 of file TransformNonVectorized.h.
References FORCEINLINE, and GetRotation().
Referenced by FDisplayClusterShaderParameters_ICVFX::FCameraSettings::SetViewProjection().
InverseTransformVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::InverseTransformVector (const TVector< T > & V) const nodiscard
Transform a direction vector by the inverse of this transform - will not take into account translation part.
If you want to transform a surface normal (or plane) and correctly account for non-uniform scaling you should use TransformByUsingAdjointT with adjoint of matrix inverse.
Definition at line 1474 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, GetSafeScaleReciprocal(), Rotation, and Scale3D.
InverseTransformVectorNoScale()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::InverseTransformVectorNoScale (const TVector< T > & V) const nodiscard
Definition at line 1483 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, and Rotation.
IsRotationNormalized()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::IsRotationNormalized () const inline nodiscard
Checks whether the rotation component is normalized or not.
Returns
true if the rotation component is normalized, and false otherwise.
Definition at line 1068 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::Blend(), UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate(), UE::Math::TTransform< double >::BlendWith(), UE::Math::TTransform< double >::ToMatrixNoScale(), and UE::Math::TTransform< double >::ToMatrixWithScale().
IsValid()
template<typename T> bool UE::Math::TTransform< T >::IsValid () const inline nodiscard
Definition at line 603 of file TransformNonVectorized.h.
LerpTranslationScale3D()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::LerpTranslationScale3D (const TTransform< T > & SourceAtom1, const TTransform< T > & SourceAtom2, ScalarRegister Alpha) inline
Set the translation and Scale3D components of this transform to a linearly interpolated combination of two other transforms.
Translation = FMath::Lerp(SourceAtom1.Translation, SourceAtom2.Translation, Alpha) Scale3D = FMath::Lerp(SourceAtom1.Scale3D, SourceAtom2.Scale3D, Alpha)
Parameters
SourceAtom1 The starting point source atom (used 100% if Alpha is 0)
SourceAtom2 The ending point source atom (used 100% if Alpha is 1)
Alpha The blending weight between SourceAtom1 and SourceAtom2
Definition at line 1045 of file TransformNonVectorized.h.
Mirror()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::Mirror (EAxis::Type MirrorAxis, EAxis::Type FlipAxis) nodiscard
Definition at line 1569 of file TransformNonVectorized.h.
References FORCEINLINE, UE::Math::TMatrix< T >::Mirror(), SetFromMatrix(), and ToMatrixWithScale().
Multiply()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::Multiply (TTransform< T > * OutTransform, const TTransform< T > * A, const TTransform< T > * B) static
Create a new transform: OutTransform = A * B.
Returns Multiplied Transform of 2 TTransform<T>s.
Order matters when composing transforms : A * B will yield a transform that logically first applies A then B to any subsequent transformation.
Parameters
OutTransform pointer to transform that will store the result of A * B.
A Transform A.
B Transform B.
Definition at line 1311 of file TransformNonVectorized.h.
References TTransform(), A, AnyHasNegativeScale(), B, checkSlow, FORCEINLINE, MultiplyUsingMatrixWithScale(), Rotation, Scale3D, and Translation.
Referenced by operator*(), operator*(), operator*=(), and operator*=().
MultiplyScale3D()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::MultiplyScale3D (const TVector< T > & Scale3DMultiplier) inline
Scales the Scale3D component by a new factor.
Parameters
Scale3DMultiplier The value to multiply Scale3D with
Definition at line 794 of file TransformNonVectorized.h.
MultiplyUsingMatrixWithScale()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::MultiplyUsingMatrixWithScale (TTransform< T > * OutTransform, const TTransform< T > * A, const TTransform< T > * B) static private
Create a new transform: OutTransform = A * B using the matrix while keeping the scale that's given by A and B Please note that this operation is a lot more expensive than normal Multiply.
Order matters when composing transforms : A * B will yield a transform that logically first applies A then B to any subsequent transformation.
Parameters
OutTransform pointer to transform that will store the result of A * B.
A Transform A.
B Transform B.
Definition at line 1272 of file TransformNonVectorized.h.
References TTransform(), A, B, ConstructTransformFromMatrixWithDesiredScale(), and FORCEINLINE.
Referenced by Multiply().
NormalizeRotation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::NormalizeRotation () inline
Normalize the rotation component of this transformation.
Definition at line 1057 of file TransformNonVectorized.h.
Referenced by FCSPose< PoseType >::CalculateComponentSpaceTransform().
operator*() [1/3]
template<typename T> FORCEINLINE TTransform< T > UE::Math::TTransform< T >::operator* (const TQuat< T > & Other) const nodiscard
Return a transform that is the result of this multiplied by another transform (made only from a rotation).
Order matters when composing transforms : C = A * B will yield a transform C that logically first applies A then B to any subsequent transformation.
Parameters
Other other quaternion rotation by which to multiply.
Returns
new transform: this * TTransform(Other)
Definition at line 1518 of file TransformNonVectorized.h.
References TTransform(), FORCEINLINE, Multiply(), UE::Math::TVector< T >::OneVector, Other, and UE::Math::TVector< T >::ZeroVector.
operator*() [2/3]
template<typename T> FORCEINLINE TTransform< T > UE::Math::TTransform< T >::operator* (const TTransform< T > & Other) const nodiscard
Return a transform that is the result of this multiplied by another transform.
Order matters when composing transforms : C = A * B will yield a transform C that logically first applies A then B to any subsequent transformation.
Parameters
Other other transform by which to multiply.
Returns
new transform: this * Other
Definition at line 1502 of file TransformNonVectorized.h.
References TTransform(), FORCEINLINE, Multiply(), and Other.
operator*() [3/3]
template<typename T> FORCEINLINE TTransform< T > UE::Math::TTransform< T >::operator* (T Mult) const inline nodiscard
Definition at line 457 of file TransformNonVectorized.h.
operator*=() [1/3]
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::operator*= (const TQuat< T > & Other)
Sets this transform to the result of this multiplied by another transform (made only from a rotation).
Order matters when composing transforms : C = A * B will yield a transform C that logically first applies A then B to any subsequent transformation.
Parameters
Other other quaternion rotation by which to multiply.
Definition at line 1527 of file TransformNonVectorized.h.
References TTransform(), FORCEINLINE, Multiply(), UE::Math::TVector< T >::OneVector, Other, and UE::Math::TVector< T >::ZeroVector.
operator*=() [2/3]
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::operator*= (const TTransform< T > & Other)
Sets this transform to the result of this multiplied by another transform.
Order matters when composing transforms : C = A * B will yield a transform C that logically first applies A then B to any subsequent transformation.
Parameters
Other other transform by which to multiply.
Definition at line 1511 of file TransformNonVectorized.h.
References TTransform(), FORCEINLINE, Multiply(), and Other.
operator*=() [3/3]
template<typename T> FORCEINLINE TTransform< T > & UE::Math::TTransform< T >::operator*= (T Mult) inline
Definition at line 462 of file TransformNonVectorized.h.
operator+()
template<typename T> FORCEINLINE TTransform< T > UE::Math::TTransform< T >::operator+ (const TTransform< T > & Atom) const inline nodiscard
Quaternion addition is wrong here.
This is just a special case for linear interpolation. Use only within blends!! Rotation part is NOT normalized!!
Definition at line 438 of file TransformNonVectorized.h.
operator+=()
template<typename T> FORCEINLINE TTransform< T > & UE::Math::TTransform< T >::operator+= (const TTransform< T > & Atom) inline
Definition at line 443 of file TransformNonVectorized.h.
Private_RotationEquals()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::Private_RotationEquals (const TQuat< T > & InRotation, const FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline private
Definition at line 665 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Equals(), and UE::Math::TTransform< double >::EqualsNoScale().
Private_Scale3DEquals()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::Private_Scale3DEquals (const TVector< T > & InScale3D, const FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline private
Definition at line 675 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Equals().
Private_TranslationEquals()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::Private_TranslationEquals (const TVector< T > & InTranslation, const FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline private
Definition at line 670 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Equals(), and UE::Math::TTransform< double >::EqualsNoScale().
RemoveScaling()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::RemoveScaling (FReal Tolerance = UE_SMALL_NUMBER)
Definition at line 1262 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_Rotate(), DiagnosticCheckNaN_Scale3D(), FORCEINLINE, Rotation, and Scale3D.
RotationEquals()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::RotationEquals (const TTransform< T > & Other, FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Definition at line 703 of file TransformNonVectorized.h.
Rotator()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TTransform< T >::Rotator () const inline nodiscard
Definition at line 576 of file TransformNonVectorized.h.
Referenced by USceneComponent::SetRelativeTransform_Direct().
Scale3DEquals()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::Scale3DEquals (const TTransform< T > & Other, FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Definition at line 715 of file TransformNonVectorized.h.
ScaleTranslation() [1/2]
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::ScaleTranslation (const FReal & Scale)
Definition at line 1252 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_Translate(), FORCEINLINE, Scale, and Translation.
ScaleTranslation() [2/2]
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::ScaleTranslation (const TVector< T > & InScale3D)
Scale the translation part of the Transform by the supplied vector.
Definition at line 1243 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_Translate(), FORCEINLINE, and Translation.
Serialize()
template<typename T> bool UE::Math::TTransform< T >::Serialize (FArchive & Ar) inline
Definition at line 627 of file TransformNonVectorized.h.
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TTransform< T >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 633 of file TransformNonVectorized.h.
SetComponents()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetComponents (const TQuat< T > & InRotation, const TVector< T > & InTranslation, const TVector< T > & InScale3D) inline
Sets the components.
Parameters
InRotation The new value for the Rotation component
InTranslation The new value for the Translation component
InScale3D The new value for the Scale3D component
Definition at line 755 of file TransformNonVectorized.h.
SetFromMatrix()
template<typename T> void UE::Math::TTransform< T >::SetFromMatrix (const TMatrix< T > & InMatrix) inline
Definition at line 1165 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), and Mirror().
SetIdentity()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetIdentity () inline
Sets the components to the identity transform: Rotation = (0,0,0,1) Translation = (0,0,0) Scale3D = (1,1,1)
Definition at line 770 of file TransformNonVectorized.h.
SetIdentityZeroScale()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetIdentityZeroScale () inline
Sets the components to the 'additive' identity transform: Rotation = (0,0,0,1) Translation = (0,0,0) Scale3D = (0,0,0)
Definition at line 783 of file TransformNonVectorized.h.
SetLocation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetLocation (const TVector< T > & Origin) inline
Set the translation of this transformation.
Definition at line 588 of file TransformNonVectorized.h.
SetRotation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetRotation (const TQuat< T > & NewRotation) inline
Sets the rotation component.
Parameters
NewRotation The new value for the rotation component
Definition at line 858 of file TransformNonVectorized.h.
Referenced by AEFConstantKeyLerp< FORMAT >::GetBoneAtomRotation(), and AEFVariableKeyLerp< FORMAT >::GetBoneAtomRotation().
SetRotationRegister()
template<typename T> void UE::Math::TTransform< T >::SetRotationRegister (TransformVectorRegister InRotation) inline
Definition at line 913 of file TransformNonVectorized.h.
SetScale3D()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetScale3D (const TVector< T > & NewScale3D) inline
Sets the Scale3D component.
Parameters
NewScale3D The new value for the Scale3D component
Definition at line 874 of file TransformNonVectorized.h.
Referenced by AEFConstantKeyLerp< FORMAT >::GetBoneAtomScale(), AEFVariableKeyLerp< FORMAT >::GetBoneAtomScale(), UE::Geometry::FCubeGrid::GetFTransform(), UDecalComponent::GetTransformIncludingDecalSize(), and FRootMotionReset::ResetRootBoneForRootMotion().
SetToRelativeTransform()
template<typename T> void UE::Math::TTransform< T >::SetToRelativeTransform (const TTransform< T > & ParentTransform)
Set current transform and the relative to ParentTransform.
Equates to This = This->GetRelativeTransform(Parent), but saves the intermediate TTransform<T> storage and copy.
SetTranslation()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetTranslation (const TVector< T > & NewTranslation) inline
Sets the translation component.
Parameters
NewTranslation The new value for the translation component
Definition at line 804 of file TransformNonVectorized.h.
Referenced by AEFConstantKeyLerp< FORMAT >::GetBoneAtomTranslation(), and AEFVariableKeyLerp< FORMAT >::GetBoneAtomTranslation().
SetTranslationAndScale3D()
template<typename T> FORCEINLINE void UE::Math::TTransform< T >::SetTranslationAndScale3D (const TVector< T > & NewTranslation, const TVector< T > & NewScale3D) inline
Sets both the translation and Scale3D components at the same time.
Parameters
NewTranslation The new value for the translation component
NewScale3D The new value for the Scale3D component
Definition at line 891 of file TransformNonVectorized.h.
SetTranslationRegister()
template<typename T> void UE::Math::TTransform< T >::SetTranslationRegister (TransformVectorRegister InTranslation) inline
Definition at line 909 of file TransformNonVectorized.h.
SubtractTranslations()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::SubtractTranslations (const TTransform< T > & A, const TTransform< T > & B) inline static nodiscard
Subtract translations from two TTransform<T>s and return the difference.
Returns
A.Translation - B.Translation.
Definition at line 849 of file TransformNonVectorized.h.
ToHumanReadableString()
template<typename T> FString UE::Math::TTransform< T >::ToHumanReadableString () const nodiscard
Convert TTransform<T> contents to a string.
ToInverseMatrixWithScale()
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TTransform< T >::ToInverseMatrixWithScale () const inline nodiscard
Convert this Transform to matrix with scaling and compute the inverse of that.
Definition at line 298 of file TransformNonVectorized.h.
ToMatrixNoScale()
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TTransform< T >::ToMatrixNoScale () const inline nodiscard
Convert this Transform to a transformation matrix, ignoring its scaling.
Definition at line 320 of file TransformNonVectorized.h.
Referenced by FAnimPhysPose::Matrix().
ToMatrixWithScale()
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TTransform< T >::ToMatrixWithScale () const inline nodiscard
Convert this Transform to a transformation matrix with scaling.
Definition at line 241 of file TransformNonVectorized.h.
Referenced by FInstancedSkinnedMeshComponentHelper::CalcBounds(), Mirror(), UE::Math::TTransform< double >::ToInverseMatrixWithScale(), UE::Math::TBox< T >::TransformBy(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
ToString()
template<typename T> FString UE::Math::TTransform< T >::ToString () const nodiscard
Referenced by FCSPose< PoseType >::CalculateComponentSpaceTransform().
TransformFVector4()
template<typename T> FORCEINLINE TVector4< T > UE::Math::TTransform< T >::TransformFVector4 (const TVector4< T > & V) const nodiscard
Transform TVector4<T>
Definition at line 1402 of file TransformNonVectorized.h.
References checkSlow, DiagnosticCheckNaN_All(), FORCEINLINE, Rotation, Scale3D, Transform, Translation, and UE::Math::TVector4< T >::W.
TransformFVector4NoScale()
template<typename T> FORCEINLINE TVector4< T > UE::Math::TTransform< T >::TransformFVector4NoScale (const TVector4< T > & V) const nodiscard
Transform homogenous TVector4<T>, ignoring the scaling part of this transform.
Definition at line 1381 of file TransformNonVectorized.h.
References checkSlow, DiagnosticCheckNaN_All(), FORCEINLINE, Rotation, Transform, Translation, and UE::Math::TVector4< T >::W.
TransformPosition()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::TransformPosition (const TVector< T > & V) const nodiscard
Definition at line 1423 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, Rotation, Scale3D, and Translation.
Referenced by UE::Geometry::TFrame3< float >::Transform(), UE::Geometry::TPlane3< FVector::FReal >::Transform(), FSphericalSector::TransformBy(), and UE::Math::TSphere< T >::TransformBy().
TransformPositionNoScale()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::TransformPositionNoScale (const TVector< T > & V) const nodiscard
Definition at line 1431 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, Rotation, and Translation.
TransformRotation()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TTransform< T >::TransformRotation (const TQuat< T > & Q) const nodiscard
Transform a rotation.
For example if this is a LocalToWorld transform, TransformRotation(Q) would transform Q from local to world space.
Definition at line 1490 of file TransformNonVectorized.h.
References FORCEINLINE, and GetRotation().
TransformVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::TransformVector (const TVector< T > & V) const nodiscard
Definition at line 1439 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, Rotation, and Scale3D.
Referenced by FSphericalSector::TransformBy().
TransformVectorNoScale()
template<typename T> FORCEINLINE TVector< T > UE::Math::TTransform< T >::TransformVectorNoScale (const TVector< T > & V) const nodiscard
Definition at line 1447 of file TransformNonVectorized.h.
References DiagnosticCheckNaN_All(), FORCEINLINE, and Rotation.
Referenced by FBuoyancyComponentSim::ApplyTorqueForDownstreamAngularRotation(), and GetUnitAxis().
TranslationEquals()
template<typename T> FORCEINLINE bool UE::Math::TTransform< T >::TranslationEquals (const TTransform< T > & Other, FReal Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Definition at line 709 of file TransformNonVectorized.h.
Friends And Related Symbol Documentation
operator<<
template<typename T> FArchive & operator<< (FArchive & Ar, TTransform< T > & M) friend
Definition at line 619 of file TransformNonVectorized.h.
Field Documentation
Identity
template<typename T> const TTransform<T> UE::Math::TTransform< T >::Identity static
The identity transformation (Rotation = TQuat<T>::Identity, Translation = TVector<T>::ZeroVector, Scale3D = (1,1,1)).
Definition at line 58 of file TransformNonVectorized.h.
Rotation
template<typename T> TQuat<T> UE::Math::TTransform< T >::Rotation protected
Rotation of this transformation, as a quaternion.
Definition at line 49 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::AccumulateWithAdditiveScale(), UE::Math::TTransform< double >::AccumulateWithShortestRotation(), UE::Math::TTransform< double >::Blend(), UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate(), UE::Math::TTransform< double >::BlendWith(), ConstructTransformFromMatrixWithDesiredScale(), UE::Math::TTransform< double >::CopyRotationPart(), InverseTransformPosition(), InverseTransformPositionNoScale(), InverseTransformVector(), InverseTransformVectorNoScale(), Multiply(), UE::Math::TTransform< double >::operator+(), UE::Math::TTransform< double >::operator+=(), UE::Math::TTransform< double >::operator<<, RemoveScaling(), TransformFVector4(), TransformFVector4NoScale(), TransformPosition(), TransformPositionNoScale(), TransformVector(), and TransformVectorNoScale().
Scale3D
template<typename T> TVector<T> UE::Math::TTransform< T >::Scale3D protected
3D scale (always applied in local space) as a vector.
Definition at line 53 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::AccumulateWithAdditiveScale(), UE::Math::TTransform< double >::AccumulateWithShortestRotation(), UE::Math::TTransform< double >::Blend(), UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate(), UE::Math::TTransform< double >::BlendWith(), ConstructTransformFromMatrixWithDesiredScale(), UE::Math::TTransform< double >::CopyRotationPart(), UE::Math::TTransform< double >::CopyTranslationAndScale3D(), GetMaximumAxisScale(), GetMinimumAxisScale(), InverseTransformPosition(), InverseTransformVector(), UE::Math::TTransform< double >::LerpTranslationScale3D(), Multiply(), UE::Math::TTransform< double >::operator+(), UE::Math::TTransform< double >::operator+=(), UE::Math::TTransform< double >::operator<<, RemoveScaling(), TransformFVector4(), TransformPosition(), and TransformVector().
Translation
template<typename T> TVector<T> UE::Math::TTransform< T >::Translation protected
Translation of this transformation, as a vector.
Definition at line 51 of file TransformNonVectorized.h.
Referenced by UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::Accumulate(), UE::Math::TTransform< double >::AccumulateWithAdditiveScale(), UE::Math::TTransform< double >::AccumulateWithShortestRotation(), UE::Math::TTransform< double >::Blend(), UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate(), UE::Math::TTransform< double >::BlendWith(), ConstructTransformFromMatrixWithDesiredScale(), UE::Math::TTransform< double >::CopyTranslationAndScale3D(), InverseTransformPosition(), InverseTransformPositionNoScale(), UE::Math::TTransform< double >::LerpTranslationScale3D(), Multiply(), UE::Math::TTransform< double >::operator+(), UE::Math::TTransform< double >::operator+=(), UE::Math::TTransform< double >::operator<<, ScaleTranslation(), ScaleTranslation(), TransformFVector4(), TransformFVector4NoScale(), TransformPosition(), and TransformPositionNoScale().
Z_Construct_UScriptStruct_FTransform3d_Statics
template<typename T> friend UE::Math::TTransform< T >::Z_Construct_UScriptStruct_FTransform3d_Statics
Definition at line 41 of file TransformNonVectorized.h.
Z_Construct_UScriptStruct_FTransform3f_Statics
template<typename T> friend UE::Math::TTransform< T >::Z_Construct_UScriptStruct_FTransform3f_Statics
Definition at line 40 of file TransformNonVectorized.h.
Z_Construct_UScriptStruct_FTransform_Statics
template<typename T> friend UE::Math::TTransform< T >::Z_Construct_UScriptStruct_FTransform_Statics
Definition at line 42 of file TransformNonVectorized.h.
The documentation for this struct was generated from the following files:
Runtime/Core/Public/Math/MathFwd.h
Runtime/Core/Public/Math/TransformNonVectorized.h