Unreal Engine 5.6 C++ API: TLocklessStaticStorage< T, N > Struct Template Reference
TLocklessStaticStorage< T, N > Struct Template Reference
#include "SimpleStreamableAssetManager.h"
Public Member Functions
TArrayView< T > GetData ()
void Release (uint32 ToRelease)
uint32 Reserve ()
void Store (T &&In, uint32 ItemReservedIndex)
void WaitForWrites () const
Static Public Attributes
static constexpr uint32 MaxElements = N
Private Attributes
std::atomic_uint32_t ReleasedIndex = 0
std::atomic_uint32_t ReservedIndex = 0
T Storage [MaxElements] {}
Detailed Description
template<typename T, uint32 N>
struct TLocklessStaticStorage< T, N >
Definition at line 22 of file SimpleStreamableAssetManager.h.
Member Function Documentation
GetData()
template<typename T, uint32 N> TArrayView< T > TLocklessStaticStorage< T, N >::GetData () inline
Definition at line 48 of file SimpleStreamableAssetManager.h.
Release()
template<typename T, uint32 N> void TLocklessStaticStorage< T, N >::Release (uint32 ToRelease) inline
Definition at line 34 of file SimpleStreamableAssetManager.h.
Referenced by TLocklessGrowingStorage< T >::Push().
Reserve()
template<typename T, uint32 N> uint32 TLocklessStaticStorage< T, N >::Reserve () inline
Definition at line 26 of file SimpleStreamableAssetManager.h.
Referenced by TLocklessGrowingStorage< T >::Push().
Store()
template<typename T, uint32 N> void TLocklessStaticStorage< T, N >::Store (T && In, uint32 ItemReservedIndex) inline
Definition at line 28 of file SimpleStreamableAssetManager.h.
Referenced by TLocklessGrowingStorage< T >::Push().
WaitForWrites()
template<typename T, uint32 N> void TLocklessStaticStorage< T, N >::WaitForWrites () const inline
Definition at line 43 of file SimpleStreamableAssetManager.h.
Referenced by TLocklessGrowingStorage< T >::ExtractShards().
Field Documentation
MaxElements
template<typename T, uint32 N> uint32 TLocklessStaticStorage< T, N >::MaxElements = N static constexpr
Definition at line 25 of file SimpleStreamableAssetManager.h.
ReleasedIndex
template<typename T, uint32 N> std::atomic_uint32_t TLocklessStaticStorage< T, N >::ReleasedIndex = 0 private
Definition at line 52 of file SimpleStreamableAssetManager.h.
ReservedIndex
template<typename T, uint32 N> std::atomic_uint32_t TLocklessStaticStorage< T, N >::ReservedIndex = 0 private
Definition at line 51 of file SimpleStreamableAssetManager.h.
Storage
template<typename T, uint32 N> T TLocklessStaticStorage< T, N >::Storage[MaxElements] {} private
Definition at line 53 of file SimpleStreamableAssetManager.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Streaming/SimpleStreamableAssetManager.h