Unreal Engine 5.6 C++ API: FScopedStackAllocatorBookmark Struct Reference
FScopedStackAllocatorBookmark Struct Reference
#include "VirtualStackAllocator.h"
Public Member Functions
~FScopedStackAllocatorBookmark ()
Private Member Functions
FScopedStackAllocatorBookmark ()=delete
FScopedStackAllocatorBookmark (const FScopedStackAllocatorBookmark &Other)=delete
FScopedStackAllocatorBookmark (FScopedStackAllocatorBookmark &&Other)=delete
FScopedStackAllocatorBookmark (void *InRestorePointer, FVirtualStackAllocator *Owner)
void operator= (const FScopedStackAllocatorBookmark &Other)=delete
void operator= (FScopedStackAllocatorBookmark &&Other)=delete
Private Attributes
friend FVirtualStackAllocator
FVirtualStackAllocator * Owner
void * RestorePointer
Detailed Description
Definition at line 46 of file VirtualStackAllocator.h.
Constructor & Destructor Documentation
~FScopedStackAllocatorBookmark()
FScopedStackAllocatorBookmark::~FScopedStackAllocatorBookmark ()
FScopedStackAllocatorBookmark() [1/4]
FScopedStackAllocatorBookmark::FScopedStackAllocatorBookmark (void * InRestorePointer, FVirtualStackAllocator * Owner) inline private
Definition at line 55 of file VirtualStackAllocator.h.
References FVirtualStackAllocator, Owner, and RestorePointer.
Referenced by FScopedStackAllocatorBookmark(), FScopedStackAllocatorBookmark(), operator=(), and operator=().
FScopedStackAllocatorBookmark() [2/4]
FScopedStackAllocatorBookmark::FScopedStackAllocatorBookmark () private delete
FScopedStackAllocatorBookmark() [3/4]
FScopedStackAllocatorBookmark::FScopedStackAllocatorBookmark (const FScopedStackAllocatorBookmark & Other) private delete
References FScopedStackAllocatorBookmark(), and Other.
FScopedStackAllocatorBookmark() [4/4]
FScopedStackAllocatorBookmark::FScopedStackAllocatorBookmark (FScopedStackAllocatorBookmark && Other) private delete
References FScopedStackAllocatorBookmark(), and Other.
Member Function Documentation
operator=() [1/2]
void FScopedStackAllocatorBookmark::operator= (const FScopedStackAllocatorBookmark & Other) private delete
References FScopedStackAllocatorBookmark(), and Other.
operator=() [2/2]
void FScopedStackAllocatorBookmark::operator= (FScopedStackAllocatorBookmark && Other) private delete
References FScopedStackAllocatorBookmark(), and Other.
Field Documentation
FVirtualStackAllocator
friend FScopedStackAllocatorBookmark::FVirtualStackAllocator private
Definition at line 53 of file VirtualStackAllocator.h.
Referenced by FScopedStackAllocatorBookmark().
Owner
FVirtualStackAllocator* FScopedStackAllocatorBookmark::Owner private
Definition at line 68 of file VirtualStackAllocator.h.
Referenced by FScopedStackAllocatorBookmark().
RestorePointer
void* FScopedStackAllocatorBookmark::RestorePointer private
Definition at line 67 of file VirtualStackAllocator.h.
Referenced by FScopedStackAllocatorBookmark().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Memory/VirtualStackAllocator.h