Unreal Engine 5.6 C++ API: UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType > Struct Template Reference
UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType > Struct Template Reference
#include "MovieSceneEntityFactoryTemplates.h"
Public Member Functions
TConditionalDuplicateChildEntityInitializer (TComponentTypeID< ComponentType > InComponent, FComponentMask InParentComponentMask)
virtual bool IsRelevant (const FComponentMask &InParentType, const FComponentMask &InChildType) const override
Public Member Functions inherited from UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType >
TDuplicateChildEntityInitializer (TComponentTypeID< ComponentType > InComponent)
TComponentTypeID< ComponentType > GetComponent () const
virtual void Run (const FEntityRange &ChildRange, const FEntityAllocation *ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets)
Public Member Functions inherited from UE::MovieScene::FChildEntityInitializer
virtual ~FChildEntityInitializer ()
FComponentTypeID GetChildComponent () const
FComponentTypeID GetParentComponent () const
Data Fields
FComponentMask ParentComponentMask
Additional Inherited Members
Protected Member Functions inherited from UE::MovieScene::FChildEntityInitializer
FChildEntityInitializer (FComponentTypeID InParentComponent, FComponentTypeID InChildComponent)
Protected Attributes inherited from UE::MovieScene::FChildEntityInitializer
FComponentTypeID ChildComponent
FComponentTypeID ParentComponent
Detailed Description
template<typename ComponentType>
struct UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType >
Definition at line 112 of file MovieSceneEntityFactoryTemplates.h.
Constructor & Destructor Documentation
TConditionalDuplicateChildEntityInitializer()
template<typename ComponentType> UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType >::TConditionalDuplicateChildEntityInitializer (TComponentTypeID< ComponentType > InComponent, FComponentMask InParentComponentMask) inline explicit
Definition at line 114 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType >::TDuplicateChildEntityInitializer(), and ParentComponentMask.
Member Function Documentation
IsRelevant()
template<typename ComponentType> virtual bool UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType >::IsRelevant (const FComponentMask & InParentType, const FComponentMask & InChildType) const inline override virtual
Reimplemented from UE::MovieScene::FChildEntityInitializer.
Definition at line 119 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FComponentMask::ContainsAll(), UE::MovieScene::FChildEntityInitializer::IsRelevant(), and ParentComponentMask.
Field Documentation
ParentComponentMask
template<typename ComponentType> FComponentMask UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType >::ParentComponentMask
Definition at line 124 of file MovieSceneEntityFactoryTemplates.h.
Referenced by TConditionalDuplicateChildEntityInitializer(), and IsRelevant().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityFactoryTemplates.h