Unreal Engine 5.6 C++ API: UE::Core::Private::TAdderReserverVTable< T, SizeType > Struct Template Reference
UE::Core::Private::TAdderReserverVTable< T, SizeType > Struct Template Reference
#include "AdderRef.h"
Public Member Functions
constexpr TAdderReserverVTable (void(*InAddConstRef)(void *ContainerPtr, const T &Val), void(*InAddRValueRef)(void *ContainerPtr, T &&Val), SizeType(*InNum)(const void *ContainerPtr), void(*InReserve)(void *ContainerPtr, SizeType Size))
Public Member Functions inherited from UE::Core::Private::TAdderVTable< T >
constexpr TAdderVTable (void(*InAddConstRef)(void *ContainerPtr, const T &Val), void(*InAddRValueRef)(void *ContainerPtr, T &&Val))
Data Fields
SizeType(* Num)(const void *ContainerPtr)
void(* Reserve)(void *ContainerPtr, SizeType Size)
Data Fields inherited from UE::Core::Private::TAdderVTable< T >
void(* AddConstRef)(void *ContainerPtr, const T &Val)
void(* AddRValueRef)(void *ContainerPtr, T &&Val)
Detailed Description
template<typename T, typename SizeType>
struct UE::Core::Private::TAdderReserverVTable< T, SizeType >
Definition at line 55 of file AdderRef.h.
Constructor & Destructor Documentation
TAdderReserverVTable()
template<typename T, typename SizeType> UE::Core::Private::TAdderReserverVTable< T, SizeType >::TAdderReserverVTable (void(* InAddConstRef)(void *ContainerPtr, const T &Val), void(* InAddRValueRef)(void *ContainerPtr, T &&Val), SizeType(* InNum)(const void *ContainerPtr), void(* InReserve)(void *ContainerPtr, SizeType Size)) inline constexpr
Definition at line 57 of file AdderRef.h.
References UE::Core::Private::TAdderVTable< T >::TAdderVTable(), Num, Reserve, and TSequenceHistory< HistorySize >::Size.
Field Documentation
Num
template<typename T, typename SizeType> SizeType(* UE::Core::Private::TAdderReserverVTable< T, SizeType >::Num) (const void *ContainerPtr)
Definition at line 64 of file AdderRef.h.
Referenced by TAdderReserverVTable().
Reserve
template<typename T, typename SizeType> void(* UE::Core::Private::TAdderReserverVTable< T, SizeType >::Reserve) (void *ContainerPtr, SizeType Size)
Definition at line 65 of file AdderRef.h.
Referenced by TAdderReserverVTable().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/AdderRef.h