Unreal Engine 5.6 C++ API: FDFMatrix Struct Reference
FDFMatrix Struct Reference
#include "DoubleFloat.h"
Public Member Functions
FDFMatrix ()=default
FDFMatrix (FMatrix44f M, FVector3f PostTranslation)
Static Public Member Functions
static FDFMatrix MakeClampedToRelativeWorldMatrix (const FVector3f Origin, const FMatrix &ToWorld)
static FMatrix MakeClampedToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix &ToWorld)
static FDFMatrix MakeToRelativeWorldMatrix (const FVector3f Origin, const FMatrix &ToWorld)
static FMatrix MakeToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix &ToWorld)
static FMatrix44f SafeCastMatrix (const FMatrix &Matrix)
Data Fields
FMatrix44f M {}
FVector3f PostTranslation {}
Detailed Description
Definition at line 176 of file DoubleFloat.h.
Constructor & Destructor Documentation
FDFMatrix() [1/2]
FDFMatrix::FDFMatrix (FMatrix44f M, FVector3f PostTranslation) inline
Definition at line 178 of file DoubleFloat.h.
References M, and PostTranslation.
Referenced by MakeClampedToRelativeWorldMatrix(), and MakeToRelativeWorldMatrix().
FDFMatrix() [2/2]
FDFMatrix::FDFMatrix () default
Member Function Documentation
MakeClampedToRelativeWorldMatrix()
FDFMatrix FDFMatrix::MakeClampedToRelativeWorldMatrix (const FVector3f Origin, const FMatrix & ToWorld) static nodiscard
References FDFMatrix(), and Origin.
MakeClampedToRelativeWorldMatrixDouble()
FMatrix FDFMatrix::MakeClampedToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix & ToWorld) static nodiscard
References FVector, and Origin.
Referenced by FPrimitiveUniformShaderParametersBuilder::Build().
MakeToRelativeWorldMatrix()
FDFMatrix FDFMatrix::MakeToRelativeWorldMatrix (const FVector3f Origin, const FMatrix & ToWorld) static nodiscard
References FDFMatrix(), and Origin.
MakeToRelativeWorldMatrixDouble()
FMatrix FDFMatrix::MakeToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix & ToWorld) static nodiscard
References FVector, and Origin.
Referenced by FPrimitiveUniformShaderParametersBuilder::Build().
SafeCastMatrix()
FMatrix44f FDFMatrix::SafeCastMatrix (const FMatrix & Matrix) static nodiscard
References Matrix.
Field Documentation
M
FMatrix44f FDFMatrix::M {}
Definition at line 184 of file DoubleFloat.h.
Referenced by FDFMatrix().
PostTranslation
FVector3f FDFMatrix::PostTranslation {}
Definition at line 185 of file DoubleFloat.h.
Referenced by FDFMatrix().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/DoubleFloat.h