Unreal Engine 5.6 C++ API: FAtmosphereSetup Struct Reference
FAtmosphereSetup Struct Reference
#include "SkyAtmosphereCommonData.h"
Public Member Functions
FAtmosphereSetup (const FSkyAtmosphereDynamicState &Ds)
FAtmosphereSetup (const USkyAtmosphereComponent &SkyAtmosphereComponent)
void ApplyWorldOffset (const FVector &InOffset)
void ComputeViewData (const FVector &WorldCameraOrigin, const FVector &PreViewTranslation, const FVector3f &ViewForward, const FVector3f &ViewRight, FVector3f &SkyCameraTranslatedWorldOrigin, FVector4f &SkyPlanetTranslatedWorldCenterAndViewHeight, FMatrix44f &SkyViewLutReferential) const
FLinearColor GetTransmittanceAtGroundLevel (const FVector &SunDirection) const
template<typename T>
void InternalInit (const T &SkyAtmosphereComponent)
void UpdateTransform (const FTransform &ComponentTransform, uint8 TranformMode)
Data Fields
float AbsorptionDensity0ConstantTerm
float AbsorptionDensity0LayerWidth
float AbsorptionDensity0LinearTerm
float AbsorptionDensity1ConstantTerm
float AbsorptionDensity1LinearTerm
FLinearColor AbsorptionExtinction
float BottomRadiusKm
FLinearColor GroundAlbedo
FLinearColor MieAbsorption
float MieDensityExpScale
FLinearColor MieExtinction
float MiePhaseG
FLinearColor MieScattering
float MultiScatteringFactor
FVector PlanetCenterKm
float RayleighDensityExpScale
FLinearColor RayleighScattering
float TopRadiusKm
float TransmittanceMinLightElevationAngle
Static Public Attributes
static const float CmToSkyUnit = 0.00001f
static const float SkyUnitToCm = 1.0f / 0.00001f
Detailed Description
Definition at line 17 of file SkyAtmosphereCommonData.h.
Constructor & Destructor Documentation
FAtmosphereSetup() [1/2]
FAtmosphereSetup::FAtmosphereSetup (const USkyAtmosphereComponent & SkyAtmosphereComponent)
Definition at line 123 of file SkyAtmosphereCommonData.cpp.
References InternalInit().
FAtmosphereSetup() [2/2]
FAtmosphereSetup::FAtmosphereSetup (const FSkyAtmosphereDynamicState & Ds)
Definition at line 128 of file SkyAtmosphereCommonData.cpp.
References InternalInit().
Member Function Documentation
ApplyWorldOffset()
void FAtmosphereSetup::ApplyWorldOffset (const FVector & InOffset)
Definition at line 133 of file SkyAtmosphereCommonData.cpp.
References CmToSkyUnit, FVector, and PlanetCenterKm.
ComputeViewData()
void FAtmosphereSetup::ComputeViewData (const FVector & WorldCameraOrigin, const FVector & PreViewTranslation, const FVector3f & ViewForward, const FVector3f & ViewRight, FVector3f & SkyCameraTranslatedWorldOrigin, FVector4f & SkyPlanetTranslatedWorldCenterAndViewHeight, FMatrix44f & SkyViewLutReferential) const
Definition at line 245 of file SkyAtmosphereCommonData.cpp.
References BottomRadiusKm, CmToSkyUnit, UE::Math::TVector< float >::CrossProduct(), UE::Math::TVector< float >::DotProduct(), Forward(), FVector, UE::Math::TMatrix< T >::GetTransposed(), Left, PlanetCenterKm, UE::Math::TMatrix< T >::SetColumn(), UE::Math::TVector< T >::Size(), SkyUnitToCm, and TSequenceHistory< HistorySize >::Size.
GetTransmittanceAtGroundLevel()
FLinearColor FAtmosphereSetup::GetTransmittanceAtGroundLevel (const FVector & SunDirection) const
Definition at line 156 of file SkyAtmosphereCommonData.cpp.
References AbsorptionDensity0ConstantTerm, AbsorptionDensity0LayerWidth, AbsorptionDensity0LinearTerm, AbsorptionDensity1ConstantTerm, AbsorptionDensity1LinearTerm, AbsorptionExtinction, FLinearColor::B, BottomRadiusKm, FMath::Clamp(), FMath::DegreesToRadians(), UE::Math::TVector< float >::Distance(), UE::Math::TVector< float >::DotProduct(), ForceInitToZero, UE::Math::TVector< double >::ForwardVector, FVector, FLinearColor::G, FMath::GetAzimuthAndElevation(), UE::Math::TVector< double >::LeftVector, FMath::Max, MieDensityExpScale, MieExtinction, FMath::Min, FLinearColor::R, RayleighDensityExpScale, RayleighScattering, TopRadiusKm, TransmittanceMinLightElevationAngle, UE::Math::TVector< double >::UpVector, UE::Math::TVector2< T >::X, UE::Math::TVector< T >::X, UE::Math::TVector2< T >::Y, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
InternalInit()
template<typename T> void FAtmosphereSetup::InternalInit (const T & SkyAtmosphereComponent)
Definition at line 28 of file SkyAtmosphereCommonData.cpp.
References AbsorptionDensity0ConstantTerm, AbsorptionDensity0LayerWidth, AbsorptionDensity0LinearTerm, AbsorptionDensity1ConstantTerm, AbsorptionDensity1LinearTerm, AbsorptionExtinction, FLinearColor::B, BottomRadiusKm, FMath::Clamp(), FLinearColor::G, UE::Color::FColorSpaceTransform::GetSRGBToWorkingColorSpace(), GetTentDistribution(), UE::Color::FColorSpace::GetWorking(), GroundAlbedo, UE::Color::FColorSpace::IsSRGB(), FMath::Max, MieAbsorption, MieDensityExpScale, MieExtinction, MiePhaseG, MieScattering, MultiScatteringFactor, FLinearColor::R, RayleighDensityExpScale, RayleighScattering, TopRadiusKm, TransmittanceMinLightElevationAngle, and UpdateTransform().
Referenced by FAtmosphereSetup(), and FAtmosphereSetup().
UpdateTransform()
void FAtmosphereSetup::UpdateTransform (const FTransform & ComponentTransform, uint8 TranformMode)
Definition at line 138 of file SkyAtmosphereCommonData.cpp.
References BottomRadiusKm, check, CmToSkyUnit, FVector, UE::Math::TTransform< T >::GetTranslation(), and PlanetCenterKm.
Referenced by InternalInit().
Field Documentation
AbsorptionDensity0ConstantTerm
float FAtmosphereSetup::AbsorptionDensity0ConstantTerm
Definition at line 39 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
AbsorptionDensity0LayerWidth
float FAtmosphereSetup::AbsorptionDensity0LayerWidth
Definition at line 38 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
AbsorptionDensity0LinearTerm
float FAtmosphereSetup::AbsorptionDensity0LinearTerm
Definition at line 40 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
AbsorptionDensity1ConstantTerm
float FAtmosphereSetup::AbsorptionDensity1ConstantTerm
Definition at line 41 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
AbsorptionDensity1LinearTerm
float FAtmosphereSetup::AbsorptionDensity1LinearTerm
Definition at line 42 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
AbsorptionExtinction
FLinearColor FAtmosphereSetup::AbsorptionExtinction
Definition at line 37 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
BottomRadiusKm
float FAtmosphereSetup::BottomRadiusKm
Definition at line 23 of file SkyAtmosphereCommonData.h.
Referenced by ComputeViewData(), GetTransmittanceAtGroundLevel(), InternalInit(), and UpdateTransform().
CmToSkyUnit
const float FAtmosphereSetup::CmToSkyUnit = 0.00001f static
Definition at line 19 of file SkyAtmosphereCommonData.h.
Referenced by ApplyWorldOffset(), ComputeViewData(), and UpdateTransform().
GroundAlbedo
FLinearColor FAtmosphereSetup::GroundAlbedo
Definition at line 44 of file SkyAtmosphereCommonData.h.
Referenced by InternalInit().
MieAbsorption
FLinearColor FAtmosphereSetup::MieAbsorption
Definition at line 33 of file SkyAtmosphereCommonData.h.
Referenced by InternalInit().
MieDensityExpScale
float FAtmosphereSetup::MieDensityExpScale
Definition at line 34 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
MieExtinction
FLinearColor FAtmosphereSetup::MieExtinction
Definition at line 32 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
MiePhaseG
float FAtmosphereSetup::MiePhaseG
Definition at line 35 of file SkyAtmosphereCommonData.h.
Referenced by InternalInit().
MieScattering
FLinearColor FAtmosphereSetup::MieScattering
Definition at line 31 of file SkyAtmosphereCommonData.h.
Referenced by InternalInit().
MultiScatteringFactor
float FAtmosphereSetup::MultiScatteringFactor
Definition at line 26 of file SkyAtmosphereCommonData.h.
Referenced by InternalInit().
PlanetCenterKm
FVector FAtmosphereSetup::PlanetCenterKm
Definition at line 22 of file SkyAtmosphereCommonData.h.
Referenced by ApplyWorldOffset(), ComputeViewData(), and UpdateTransform().
RayleighDensityExpScale
float FAtmosphereSetup::RayleighDensityExpScale
Definition at line 29 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
RayleighScattering
FLinearColor FAtmosphereSetup::RayleighScattering
Definition at line 28 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
SkyUnitToCm
const float FAtmosphereSetup::SkyUnitToCm = 1.0f / 0.00001f static
Definition at line 20 of file SkyAtmosphereCommonData.h.
Referenced by ComputeViewData().
TopRadiusKm
float FAtmosphereSetup::TopRadiusKm
Definition at line 24 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
TransmittanceMinLightElevationAngle
float FAtmosphereSetup::TransmittanceMinLightElevationAngle
Definition at line 46 of file SkyAtmosphereCommonData.h.
Referenced by GetTransmittanceAtGroundLevel(), and InternalInit().
The documentation for this struct was generated from the following files:
Runtime/Engine/Public/Rendering/SkyAtmosphereCommonData.h
Runtime/Engine/Public/Rendering/SkyAtmosphereCommonData.cpp