Unreal Engine 5.6 C++ API: FIoHash Struct Reference
FIoHash Struct Reference
Stores a BLAKE3-160 hash, taken from the first 20 bytes of a BLAKE3-256 hash.
#include "IoHash.h"
Public Types
using ByteArray = uint8[20]
Public Member Functions
FIoHash ()=default
Construct a zero hash.
FIoHash (const ByteArray &Hash)
Construct a hash from an array of 20 bytes.
FIoHash (const FBlake3Hash &Hash)
Construct a hash from a BLAKE3-256 hash.
FIoHash (FAnsiStringView HexHash)
Construct a hash from a 40-character hex string.
FIoHash (FUtf8StringView HexHash)
FIoHash (FWideStringView HexHash)
ByteArray & GetBytes ()
Returns a reference to the raw byte array for the hash.
const ByteArray & GetBytes () const
bool IsZero () const
Returns whether this is a zero hash.
void Reset ()
Reset this to a zero hash.
Static Public Member Functions
static FIoHash FromView (FMemoryView Hash)
Construct a hash from a view of 20 bytes.
static FIoHash HashBuffer (const FCompositeBuffer &Buffer)
static FIoHash HashBuffer (const void *Data, uint64 Size)
static FIoHash HashBuffer (FMemoryView View)
Calculate the hash of the buffer.
Static Public Attributes
static const FIoHash Zero
A zero hash.
Private Attributes
ByteArray Hash {}
Friends
uint32 GetTypeHash (const FIoHash &Value)
bool operator!= (const FIoHash &A, const FIoHash &B)
bool operator< (const FIoHash &A, const FIoHash &B)
FArchive & operator<< (FArchive &Ar, FIoHash &InHash)
bool operator== (const FIoHash &A, const FIoHash &B)
Detailed Description
Stores a BLAKE3-160 hash, taken from the first 20 bytes of a BLAKE3-256 hash.
The BLAKE3 hash function was selected for its high performance and its ability to parallelize. Only the leading 160 bits of the 256-bit hash are used, to provide strong collision resistance while minimizing the size of the hash.
When the data to hash is not in a contiguous region of memory, use FIoHashBuilder to hash data in blocks with FIoHashBuilder::Update(Block) followed by FIoHashBuilder::Finalize().
Definition at line 32 of file IoHash.h.
Member Typedef Documentation
ByteArray
using FIoHash::ByteArray = uint8[20]
Definition at line 35 of file IoHash.h.
Constructor & Destructor Documentation
FIoHash() [1/6]
FIoHash::FIoHash () default
Construct a zero hash.
References FIoHash(), and Hash.
Referenced by FIoHash(), FromView(), GetTypeHash, HashBuffer(), HashBuffer(), HashBuffer(), operator!=, operator<, operator<<, operator==, and Reset().
FIoHash() [2/6]
FIoHash::FIoHash (const ByteArray & Hash) inline explicit
Construct a hash from an array of 20 bytes.
Definition at line 104 of file IoHash.h.
References Hash, and FMemory::Memcpy().
FIoHash() [3/6]
FIoHash::FIoHash (const FBlake3Hash & Hash) inline
Construct a hash from a BLAKE3-256 hash.
Definition at line 109 of file IoHash.h.
References FBlake3Hash::GetBytes(), Hash, and FMemory::Memcpy().
FIoHash() [4/6]
FIoHash::FIoHash (FAnsiStringView HexHash) inline explicit
Construct a hash from a 40-character hex string.
Definition at line 115 of file IoHash.h.
References check, Hash, UE::String::HexToBytes(), and TStringView< CharType >::Len().
FIoHash() [5/6]
FIoHash::FIoHash (FWideStringView HexHash) inline explicit
Definition at line 121 of file IoHash.h.
References check, Hash, UE::String::HexToBytes(), and TStringView< CharType >::Len().
FIoHash() [6/6]
FIoHash::FIoHash (FUtf8StringView HexHash) inline explicit
Definition at line 127 of file IoHash.h.
References check, Hash, UE::String::HexToBytes(), and TStringView< CharType >::Len().
Member Function Documentation
FromView()
FIoHash FIoHash::FromView (FMemoryView Hash) inline static
Construct a hash from a view of 20 bytes.
Definition at line 133 of file IoHash.h.
References FIoHash(), checkf, TMemoryView< DataType >::GetData(), TMemoryView< DataType >::GetSize(), Hash, FMemory::Memcpy(), TEXT, and UINT64_FMT.
GetBytes() [1/2]
ByteArray & FIoHash::GetBytes () inline
Returns a reference to the raw byte array for the hash.
Definition at line 61 of file IoHash.h.
References Hash.
Referenced by operator<<.
GetBytes() [2/2]
const ByteArray & FIoHash::GetBytes () const inline
Definition at line 62 of file IoHash.h.
References Hash.
HashBuffer() [1/3]
FIoHash FIoHash::HashBuffer (const FCompositeBuffer & Buffer) inline static nodiscard
Definition at line 166 of file IoHash.h.
References FIoHash(), Buffer, and FBlake3::HashBuffer().
HashBuffer() [2/3]
FIoHash FIoHash::HashBuffer (const void * Data, uint64 Size) inline static nodiscard
Definition at line 161 of file IoHash.h.
References FIoHash(), FBlake3::HashBuffer(), and TSequenceHistory< HistorySize >::Size.
HashBuffer() [3/3]
FIoHash FIoHash::HashBuffer (FMemoryView View) inline static nodiscard
Calculate the hash of the buffer.
Definition at line 156 of file IoHash.h.
References FIoHash(), and FBlake3::HashBuffer().
Referenced by FCbAttachment::FBinaryValue::FBinaryValue().
IsZero()
bool FIoHash::IsZero () const inline
Returns whether this is a zero hash.
Definition at line 142 of file IoHash.h.
References Hash, and Value.
Reset()
void FIoHash::Reset () inline
Reset this to a zero hash.
Definition at line 55 of file IoHash.h.
References FIoHash().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FIoHash & Value) friend
Definition at line 90 of file IoHash.h.
References FIoHash(), and Value.
operator!=
bool operator!= (const FIoHash & A, const FIoHash & B) friend
Definition at line 80 of file IoHash.h.
References FIoHash(), A, B, and FMemory::Memcmp().
operator<
bool operator< (const FIoHash & A, const FIoHash & B) friend
Definition at line 85 of file IoHash.h.
References FIoHash(), A, B, and FMemory::Memcmp().
operator<<
FArchive & operator<< (FArchive & Ar, FIoHash & InHash) friend
Definition at line 95 of file IoHash.h.
References FIoHash(), Ar, and GetBytes().
operator==
bool operator== (const FIoHash & A, const FIoHash & B) friend
Definition at line 75 of file IoHash.h.
References FIoHash(), A, B, and FMemory::Memcmp().
Field Documentation
Hash
ByteArray FIoHash::Hash {} private
Definition at line 73 of file IoHash.h.
Referenced by FIoHash(), FIoHash(), FIoHash(), FIoHash(), FIoHash(), FIoHash(), FromView(), GetBytes(), GetBytes(), and IsZero().
Zero
const FIoHash FIoHash::Zero inline static
A zero hash.
Definition at line 70 of file IoHash.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/IO/IoHash.h