Unreal Engine 5.6 C++ API: TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > > Struct Template Reference
TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > > Struct Template Reference
Pointer-related functionality (e.g.
#include "TableViewTypeTraits.h"
Data Structures
class SerializerType
Public Types
using MapKeyFuncs = TDefaultMapHashableKeyFuncs<TSharedPtr<T, ESPMode::NotThreadSafe>, TSharedRef<ITableRow>, false>
using MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TSharedPtr<T, ESPMode::NotThreadSafe>, FSparseItemInfo, false>
typedef TSharedPtr< T > NullableType
using SetKeyFuncs = DefaultKeyFuncs<TSharedPtr<T, ESPMode::NotThreadSafe>>
Static Public Member Functions
template<typename U>
static void AddReferencedObjects (FReferenceCollector &, TArray< TSharedPtr< T > > &, TSet< TSharedPtr< T > > &, TMap< const U *, TSharedPtr< T > > &)
static FString DebugDump (TSharedPtr< T > InPtr)
static bool IsPtrValid (const TSharedPtr< T > &InPtr)
static TSharedPtr< T > MakeNullPtr ()
static TSharedPtr< T > NullableItemTypeConvertToItemType (const TSharedPtr< T > &InPtr)
static void ResetPtr (TSharedPtr< T > &InPtr)
Detailed Description
template<typename T>
struct TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >
Pointer-related functionality (e.g.
setting to nullptr, testing for nullptr) specialized for SharedPointers.
Definition at line 129 of file TableViewTypeTraits.h.
Member Typedef Documentation
MapKeyFuncs
template<typename T> using TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::MapKeyFuncs = TDefaultMapHashableKeyFuncs<TSharedPtr<T, ESPMode::NotThreadSafe>, TSharedRef<ITableRow>, false>
Definition at line 134 of file TableViewTypeTraits.h.
MapKeyFuncsSparse
template<typename T> using TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TSharedPtr<T, ESPMode::NotThreadSafe>, FSparseItemInfo, false>
Definition at line 135 of file TableViewTypeTraits.h.
NullableType
template<typename T> typedef TSharedPtr<T> TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::NullableType
Definition at line 132 of file TableViewTypeTraits.h.
SetKeyFuncs
template<typename T> using TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::SetKeyFuncs = DefaultKeyFuncs<TSharedPtr<T, ESPMode::NotThreadSafe>>
Definition at line 136 of file TableViewTypeTraits.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> template<typename U> void TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::AddReferencedObjects (FReferenceCollector & , TArray< TSharedPtr< T > > & , TSet< TSharedPtr< T > > & , TMap< const U *, TSharedPtr< T > > &) inline static
Definition at line 139 of file TableViewTypeTraits.h.
DebugDump()
template<typename T> FString TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::DebugDump (TSharedPtr< T > InPtr) inline static
Definition at line 166 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::Get(), TSharedPtr< ObjectType, InMode >::IsValid(), TEXT, and UPTRINT_x_FMT.
IsPtrValid()
template<typename T> bool TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::IsPtrValid (const TSharedPtr< T > & InPtr) inline static
Definition at line 146 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::IsValid().
MakeNullPtr()
template<typename T> TSharedPtr< T > TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::MakeNullPtr () inline static
Definition at line 156 of file TableViewTypeTraits.h.
NullableItemTypeConvertToItemType()
template<typename T> TSharedPtr< T > TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::NullableItemTypeConvertToItemType (const TSharedPtr< T > & InPtr) inline static
Definition at line 161 of file TableViewTypeTraits.h.
ResetPtr()
template<typename T> void TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::ResetPtr (TSharedPtr< T > & InPtr) inline static
Definition at line 151 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::Reset().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Framework/Views/TableViewTypeTraits.h