Unreal Engine 5.6 C++ API: FMemoryImageMaterialParameterInfo Struct Reference
FMemoryImageMaterialParameterInfo Struct Reference
#include "MaterialTypes.h"
Public Member Functions
FMemoryImageMaterialParameterInfo (const FMaterialParameterInfo &Rhs)
FMemoryImageMaterialParameterInfo (const FName &InName, EMaterialParameterAssociation InAssociation=EMaterialParameterAssociation::GlobalParameter, int32 InIndex=INDEX_NONE)
FMemoryImageMaterialParameterInfo (const FScriptName &InName=FScriptName(), EMaterialParameterAssociation InAssociation=EMaterialParameterAssociation::GlobalParameter, int32 InIndex=INDEX_NONE)
FMemoryImageMaterialParameterInfo (const TCHAR *InName, EMaterialParameterAssociation InAssociation=EMaterialParameterAssociation::GlobalParameter, int32 InIndex=INDEX_NONE)
DECLARE_TYPE_LAYOUT (FMemoryImageMaterialParameterInfo, NonVirtual)
FORCEINLINE FName GetName () const
LAYOUT_FIELD (FScriptName, Name)
LAYOUT_FIELD (int32, Index)
LAYOUT_FIELD (TEnumAsByte< EMaterialParameterAssociation >, Association)
bool RemapLayerIndex (TArrayView< const int32 > IndexRemap, FMemoryImageMaterialParameterInfo &OutResult) const
Friends
FORCEINLINE uint32 GetTypeHash (const FMemoryImageMaterialParameterInfo &Value)
FORCEINLINE bool operator!= (const FMaterialParameterInfo &Lhs, const FMemoryImageMaterialParameterInfo &Rhs)
FORCEINLINE bool operator!= (const FMemoryImageMaterialParameterInfo &Lhs, const FMaterialParameterInfo &Rhs)
FORCEINLINE bool operator!= (const FMemoryImageMaterialParameterInfo &Lhs, const FMemoryImageMaterialParameterInfo &Rhs)
FArchive & operator<< (FArchive &Ar, FMemoryImageMaterialParameterInfo &Ref)
FORCEINLINE bool operator== (const FMaterialParameterInfo &Lhs, const FMemoryImageMaterialParameterInfo &Rhs)
FORCEINLINE bool operator== (const FMemoryImageMaterialParameterInfo &Lhs, const FMaterialParameterInfo &Rhs)
FORCEINLINE bool operator== (const FMemoryImageMaterialParameterInfo &Lhs, const FMemoryImageMaterialParameterInfo &Rhs)
Detailed Description
Definition at line 94 of file MaterialTypes.h.
Constructor & Destructor Documentation
FMemoryImageMaterialParameterInfo() [1/4]
FMemoryImageMaterialParameterInfo::FMemoryImageMaterialParameterInfo (const TCHAR * InName, EMaterialParameterAssociation InAssociation = EMaterialParameterAssociation::GlobalParameter, int32 InIndex = INDEX_NONE) inline
Definition at line 98 of file MaterialTypes.h.
References INDEX_NONE, InName, Name, and NameToScriptName().
Referenced by DECLARE_TYPE_LAYOUT(), GetTypeHash, operator!=, operator!=, operator!=, operator<<, operator==, operator==, operator==, and RemapLayerIndex().
FMemoryImageMaterialParameterInfo() [2/4]
FMemoryImageMaterialParameterInfo::FMemoryImageMaterialParameterInfo (const FName & InName, EMaterialParameterAssociation InAssociation = EMaterialParameterAssociation::GlobalParameter, int32 InIndex = INDEX_NONE) inline
Definition at line 104 of file MaterialTypes.h.
References INDEX_NONE, InName, Name, and NameToScriptName().
FMemoryImageMaterialParameterInfo() [3/4]
FMemoryImageMaterialParameterInfo::FMemoryImageMaterialParameterInfo (const FScriptName & InName = FScriptName(), EMaterialParameterAssociation InAssociation = EMaterialParameterAssociation::GlobalParameter, int32 InIndex = INDEX_NONE) inline
Definition at line 110 of file MaterialTypes.h.
References INDEX_NONE, InName, and Name.
FMemoryImageMaterialParameterInfo() [4/4]
FMemoryImageMaterialParameterInfo::FMemoryImageMaterialParameterInfo (const FMaterialParameterInfo & Rhs) inline
Definition at line 116 of file MaterialTypes.h.
References Name, and NameToScriptName().
Member Function Documentation
DECLARE_TYPE_LAYOUT()
FMemoryImageMaterialParameterInfo::DECLARE_TYPE_LAYOUT (FMemoryImageMaterialParameterInfo , NonVirtual)
References FMemoryImageMaterialParameterInfo().
GetName()
FORCEINLINE FName FMemoryImageMaterialParameterInfo::GetName () const inline
Definition at line 122 of file MaterialTypes.h.
References FORCEINLINE, Name, and ScriptNameToName().
LAYOUT_FIELD() [1/3]
FMemoryImageMaterialParameterInfo::LAYOUT_FIELD (FScriptName , Name)
References Name.
LAYOUT_FIELD() [2/3]
FMemoryImageMaterialParameterInfo::LAYOUT_FIELD (int32 , Index)
LAYOUT_FIELD() [3/3]
FMemoryImageMaterialParameterInfo::LAYOUT_FIELD (TEnumAsByte< EMaterialParameterAssociation > , Association)
RemapLayerIndex()
bool FMemoryImageMaterialParameterInfo::RemapLayerIndex (TArrayView< const int32 > IndexRemap, FMemoryImageMaterialParameterInfo & OutResult) const
References FMemoryImageMaterialParameterInfo().
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FMemoryImageMaterialParameterInfo & Value) friend
Definition at line 168 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), FORCEINLINE, GetTypeHash, HashCombine(), and Value.
Referenced by GetTypeHash.
operator!= [1/3]
FORCEINLINE bool operator!= (const FMaterialParameterInfo & Lhs, const FMemoryImageMaterialParameterInfo & Rhs) friend
Definition at line 153 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), FORCEINLINE, and operator==.
operator!= [2/3]
FORCEINLINE bool operator!= (const FMemoryImageMaterialParameterInfo & Lhs, const FMaterialParameterInfo & Rhs) friend
Definition at line 163 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), FORCEINLINE, and operator==.
operator!= [3/3]
FORCEINLINE bool operator!= (const FMemoryImageMaterialParameterInfo & Lhs, const FMemoryImageMaterialParameterInfo & Rhs) friend
Definition at line 143 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), FORCEINLINE, and operator==.
operator<<
FArchive & operator<< (FArchive & Ar, FMemoryImageMaterialParameterInfo & Ref) friend
Definition at line 124 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), Ar, NameToScriptName(), and ScriptNameToName().
operator== [1/3]
FORCEINLINE bool operator== (const FMaterialParameterInfo & Lhs, const FMemoryImageMaterialParameterInfo & Rhs) friend
Definition at line 148 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), and FORCEINLINE.
operator== [2/3]
FORCEINLINE bool operator== (const FMemoryImageMaterialParameterInfo & Lhs, const FMaterialParameterInfo & Rhs) friend
Definition at line 158 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), and FORCEINLINE.
operator== [3/3]
FORCEINLINE bool operator== (const FMemoryImageMaterialParameterInfo & Lhs, const FMemoryImageMaterialParameterInfo & Rhs) friend
Definition at line 138 of file MaterialTypes.h.
References FMemoryImageMaterialParameterInfo(), and FORCEINLINE.
Referenced by operator!=, operator!=, and operator!=.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/MaterialTypes.h