Unreal Engine 5.6 C++ API: FCurveAttributes Struct Reference
FCurveAttributes Struct Reference
Method of interpolation between this key and the next.
#include "RealCurve.h"
Public Member Functions
FCurveAttributes ()
ERichCurveExtrapolation GetPostExtrapolation () const
ERichCurveExtrapolation GetPreExtrapolation () const
Access the extended properties of this curve.
bool HasPostExtrapolation () const
bool HasPreExtrapolation () const
Check whether this curve has the specified properties.
FCurveAttributes & SetPostExtrapolation (ERichCurveExtrapolation InPostExtrapolation)
FCurveAttributes & SetPreExtrapolation (ERichCurveExtrapolation InPreExtrapolation)
Set the extended properties of this curve.
void UnsetPostExtrapolation ()
void UnsetPreExtrapolation ()
Reset the extended properties of this curve, implying it does not support such properties.
Static Public Member Functions
static FCurveAttributes MaskCommon (const FCurveAttributes &A, const FCurveAttributes &B)
Generate a new set of attributes that contains only those attributes common to both A and B.
Private Attributes
uint8 bHasPostExtrapolation: 1
true if the curve can express post-extrapolation modes
uint8 bHasPreExtrapolation: 1
true if the curve can express pre-extrapolation modes
ERichCurveExtrapolation PostExtrapolation
This curve's post-extrapolation mode.
ERichCurveExtrapolation PreExtrapolation
This curve's pre-extrapolation mode.
Detailed Description
Method of interpolation between this key and the next.
Enumerates extrapolation options. Structure allowing external curve data to express extended attributes
Definition at line 46 of file RealCurve.h.
Constructor & Destructor Documentation
FCurveAttributes()
FCurveAttributes::FCurveAttributes () inline
Definition at line 48 of file RealCurve.h.
References bHasPostExtrapolation, bHasPreExtrapolation, PostExtrapolation, and PreExtrapolation.
Referenced by MaskCommon(), SetPostExtrapolation(), and SetPreExtrapolation().
Member Function Documentation
GetPostExtrapolation()
ERichCurveExtrapolation FCurveAttributes::GetPostExtrapolation () const inline
Definition at line 66 of file RealCurve.h.
References bHasPostExtrapolation, check, and PostExtrapolation.
GetPreExtrapolation()
ERichCurveExtrapolation FCurveAttributes::GetPreExtrapolation () const inline
Access the extended properties of this curve.
Must check whether the curve has such properties first
Definition at line 65 of file RealCurve.h.
References bHasPreExtrapolation, check, and PreExtrapolation.
HasPostExtrapolation()
bool FCurveAttributes::HasPostExtrapolation () const inline
Definition at line 60 of file RealCurve.h.
References bHasPostExtrapolation.
HasPreExtrapolation()
bool FCurveAttributes::HasPreExtrapolation () const inline
Check whether this curve has the specified properties.
Definition at line 59 of file RealCurve.h.
References bHasPreExtrapolation.
MaskCommon()
FCurveAttributes FCurveAttributes::MaskCommon (const FCurveAttributes & A, const FCurveAttributes & B) inline static
Generate a new set of attributes that contains only those attributes common to both A and B.
Definition at line 82 of file RealCurve.h.
References FCurveAttributes(), A, B, SetPostExtrapolation(), and SetPreExtrapolation().
SetPostExtrapolation()
FCurveAttributes & FCurveAttributes::SetPostExtrapolation (ERichCurveExtrapolation InPostExtrapolation) inline
Definition at line 72 of file RealCurve.h.
References FCurveAttributes(), bHasPostExtrapolation, and PostExtrapolation.
Referenced by MaskCommon().
SetPreExtrapolation()
FCurveAttributes & FCurveAttributes::SetPreExtrapolation (ERichCurveExtrapolation InPreExtrapolation) inline
Set the extended properties of this curve.
Definition at line 71 of file RealCurve.h.
References FCurveAttributes(), bHasPreExtrapolation, and PreExtrapolation.
Referenced by MaskCommon().
UnsetPostExtrapolation()
void FCurveAttributes::UnsetPostExtrapolation () inline
Definition at line 77 of file RealCurve.h.
References bHasPostExtrapolation.
UnsetPreExtrapolation()
void FCurveAttributes::UnsetPreExtrapolation () inline
Reset the extended properties of this curve, implying it does not support such properties.
Definition at line 76 of file RealCurve.h.
References bHasPreExtrapolation.
Field Documentation
bHasPostExtrapolation
uint8 FCurveAttributes::bHasPostExtrapolation private
true if the curve can express post-extrapolation modes
Definition at line 104 of file RealCurve.h.
Referenced by FCurveAttributes(), GetPostExtrapolation(), HasPostExtrapolation(), SetPostExtrapolation(), and UnsetPostExtrapolation().
bHasPreExtrapolation
uint8 FCurveAttributes::bHasPreExtrapolation private
true if the curve can express pre-extrapolation modes
Definition at line 102 of file RealCurve.h.
Referenced by FCurveAttributes(), GetPreExtrapolation(), HasPreExtrapolation(), SetPreExtrapolation(), and UnsetPreExtrapolation().
PostExtrapolation
ERichCurveExtrapolation FCurveAttributes::PostExtrapolation private
This curve's post-extrapolation mode.
Only valid to read if bHasPostExtrapolation is true
Definition at line 109 of file RealCurve.h.
Referenced by FCurveAttributes(), GetPostExtrapolation(), and SetPostExtrapolation().
PreExtrapolation
ERichCurveExtrapolation FCurveAttributes::PreExtrapolation private
This curve's pre-extrapolation mode.
Only valid to read if bHasPreExtrapolation is true
Definition at line 107 of file RealCurve.h.
Referenced by FCurveAttributes(), GetPreExtrapolation(), and SetPreExtrapolation().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Curves/RealCurve.h