Unreal Engine 5.6 C++ API: UE::FMonotonicTimePoint Struct Reference
UE::FMonotonicTimePoint Struct Reference
A point in time measured in seconds since an arbitrary epoch.
#include "MonotonicTime.h"
Public Member Functions
constexpr FMonotonicTimePoint ()=default
constexpr bool IsInfinity () const
bool IsNaN () const
constexpr bool operator!= (const FMonotonicTimePoint Other) const
constexpr FMonotonicTimePoint operator+ (const FMonotonicTimeSpan Span) const
constexpr FMonotonicTimeSpan operator- (const FMonotonicTimePoint Point) const
constexpr FMonotonicTimePoint operator- (const FMonotonicTimeSpan Span) const
constexpr bool operator< (const FMonotonicTimePoint Other) const
constexpr bool operator<= (const FMonotonicTimePoint Other) const
constexpr bool operator== (const FMonotonicTimePoint Other) const
constexpr bool operator> (const FMonotonicTimePoint Other) const
constexpr bool operator>= (const FMonotonicTimePoint Other) const
constexpr double ToSeconds () const
Seconds since the epoch.
Static Public Member Functions
static constexpr FMonotonicTimePoint FromSeconds (const double Seconds)
Construct from seconds since the epoch.
static constexpr FMonotonicTimePoint Infinity ()
static FMonotonicTimePoint Now ()
Private Attributes
double Time = 0
Detailed Description
A point in time measured in seconds since an arbitrary epoch.
This is a monotonic clock which means the current time will never decrease. This time is meant primarily for measuring intervals. The interval between ticks of this clock is constant except for the time that the system is suspended on certain platforms. The tick frequency will differ between platforms, and must not be used as a means of communicating time without communicating the tick frequency together with the time.
Definition at line 73 of file MonotonicTime.h.
Constructor & Destructor Documentation
FMonotonicTimePoint()
UE::FMonotonicTimePoint::FMonotonicTimePoint () constexpr default
Referenced by FromSeconds(), Infinity(), Now(), operator!=(), operator+(), operator-(), operator-(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
Member Function Documentation
FromSeconds()
constexpr FMonotonicTimePoint UE::FMonotonicTimePoint::FromSeconds (const double Seconds) inline static constexpr
Construct from seconds since the epoch.
Definition at line 83 of file MonotonicTime.h.
References FMonotonicTimePoint(), Seconds, and Time.
Referenced by Infinity(), operator+(), and operator-().
Infinity()
constexpr FMonotonicTimePoint UE::FMonotonicTimePoint::Infinity () inline static constexpr
Definition at line 80 of file MonotonicTime.h.
References FMonotonicTimePoint(), and FromSeconds().
Referenced by IsInfinity(), and UE::FManualResetEvent::Wait().
IsInfinity()
bool UE::FMonotonicTimePoint::IsInfinity () const inline constexpr
Definition at line 93 of file MonotonicTime.h.
References Infinity().
Referenced by UE::FManualResetEvent::WaitUntil().
IsNaN()
bool UE::FMonotonicTimePoint::IsNaN () const inline
Definition at line 94 of file MonotonicTime.h.
References Time.
Now()
FMonotonicTimePoint UE::FMonotonicTimePoint::Now () static
References FMonotonicTimePoint(), and UE_API.
Referenced by UE::FManualResetEvent::WaitFor(), and UE::FManualResetEvent::WaitUntil().
operator!=()
bool UE::FMonotonicTimePoint::operator!= (const FMonotonicTimePoint Other) const inline constexpr
Definition at line 97 of file MonotonicTime.h.
References FMonotonicTimePoint(), Other, and Time.
operator+()
FMonotonicTimePoint UE::FMonotonicTimePoint::operator+ (const FMonotonicTimeSpan Span) const inline constexpr
Definition at line 103 of file MonotonicTime.h.
References FMonotonicTimePoint(), FromSeconds(), Time, and UE::FMonotonicTimeSpan::ToSeconds().
operator-() [1/2]
FMonotonicTimeSpan UE::FMonotonicTimePoint::operator- (const FMonotonicTimePoint Point) const inline constexpr
Definition at line 106 of file MonotonicTime.h.
References FMonotonicTimePoint(), UE::FMonotonicTimeSpan::FromSeconds(), Point, and Time.
operator-() [2/2]
FMonotonicTimePoint UE::FMonotonicTimePoint::operator- (const FMonotonicTimeSpan Span) const inline constexpr
Definition at line 104 of file MonotonicTime.h.
References FMonotonicTimePoint(), FromSeconds(), Time, and UE::FMonotonicTimeSpan::ToSeconds().
operator<()
bool UE::FMonotonicTimePoint::operator< (const FMonotonicTimePoint Other) const inline constexpr
Definition at line 99 of file MonotonicTime.h.
References FMonotonicTimePoint(), Other, and Time.
operator<=()
bool UE::FMonotonicTimePoint::operator<= (const FMonotonicTimePoint Other) const inline constexpr
Definition at line 98 of file MonotonicTime.h.
References FMonotonicTimePoint(), Other, and Time.
operator==()
bool UE::FMonotonicTimePoint::operator== (const FMonotonicTimePoint Other) const inline constexpr
Definition at line 96 of file MonotonicTime.h.
References FMonotonicTimePoint(), Other, and Time.
operator>()
bool UE::FMonotonicTimePoint::operator> (const FMonotonicTimePoint Other) const inline constexpr
Definition at line 101 of file MonotonicTime.h.
References FMonotonicTimePoint(), Other, and Time.
operator>=()
bool UE::FMonotonicTimePoint::operator>= (const FMonotonicTimePoint Other) const inline constexpr
Definition at line 100 of file MonotonicTime.h.
References FMonotonicTimePoint(), Other, and Time.
ToSeconds()
double UE::FMonotonicTimePoint::ToSeconds () const inline constexpr
Seconds since the epoch.
Definition at line 91 of file MonotonicTime.h.
References Time.
Field Documentation
Time
double UE::FMonotonicTimePoint::Time = 0 private
Definition at line 112 of file MonotonicTime.h.
Referenced by FromSeconds(), IsNaN(), operator!=(), operator+(), operator-(), operator-(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and ToSeconds().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/MonotonicTime.h