Unreal Engine 5.6 C++ API: TTypeContainer< Mode >::TFunctionInstanceProvider< T > Struct Template Reference
TTypeContainer< Mode >::TFunctionInstanceProvider< T > Struct Template Reference
Implements an instance provider that forwards instance requests to a factory function.
Public Member Functions
TFunctionInstanceProvider (TFunction< TSharedPtr< void, Mode >()> &&InCreateFunc)
virtual ~TFunctionInstanceProvider () override
virtual TSharedPtr< void, Mode > GetInstance () override
Gets an instance of a class.
Public Member Functions inherited from TTypeContainer< Mode >::IInstanceProvider
virtual ~IInstanceProvider ()
Virtual destructor.
Data Fields
TFunction< TSharedPtr< void, Mode >()> CreateFunc
Detailed Description
template<ESPMode Mode = ESPMode::ThreadSafe>
template<class T>
struct TTypeContainer< Mode >::TFunctionInstanceProvider< T >
Implements an instance provider that forwards instance requests to a factory function.
Definition at line 86 of file TypeContainer.h.
Constructor & Destructor Documentation
TFunctionInstanceProvider()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> TTypeContainer< Mode >::TFunctionInstanceProvider< T >::TFunctionInstanceProvider (TFunction< TSharedPtr< void, Mode >()> && InCreateFunc) inline
Definition at line 89 of file TypeContainer.h.
References CreateFunc, and MoveTemp().
~TFunctionInstanceProvider()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> virtual TTypeContainer< Mode >::TFunctionInstanceProvider< T >::~TFunctionInstanceProvider () inline override virtual
Definition at line 93 of file TypeContainer.h.
Member Function Documentation
GetInstance()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> virtual TSharedPtr< void, Mode > TTypeContainer< Mode >::TFunctionInstanceProvider< T >::GetInstance () inline override virtual
Gets an instance of a class.
Returns
Shared pointer to the instance (must be cast to TSharedPtr<R, Mode>).
Implements TTypeContainer< Mode >::IInstanceProvider.
Definition at line 95 of file TypeContainer.h.
References CreateFunc.
Field Documentation
CreateFunc
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> TFunction<TSharedPtr<void, Mode>()> TTypeContainer< Mode >::TFunctionInstanceProvider< T >::CreateFunc
Definition at line 100 of file TypeContainer.h.
Referenced by TFunctionInstanceProvider(), and GetInstance().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/TypeContainer.h