Unreal Engine 5.6 C++ API: TChar< CharType > Struct Template Reference
TChar< CharType > Struct Template Reference
TChar Set of utility functions operating on a single character.
#include "Char.h"
Static Public Member Functions
static int32 ConvertCharDigitToInt (CharType Char)
static bool IsAlnum (CharType Char)
static bool IsAlpha (CharType Char)
static bool IsControl (CharType Char)
static bool IsDigit (CharType Char)
static bool IsGraph (CharType Char)
static bool IsHexDigit (CharType Char)
static bool IsIdentifier (CharType Char)
static bool IsLower (CharType Char)
static bool IsOctDigit (CharType Char)
static bool IsPrint (CharType Char)
static bool IsPunct (CharType Char)
static bool IsUnderscore (CharType Char)
static bool IsUpper (CharType Char)
static bool IsWhitespace (CharType Char)
static CharType ToLower (CharType Char)
Only converts ASCII characters, same as CRT to[w]upper() with standard C locale.
static constexpr FORCEINLINE uint32 ToUnsigned (CharType Char)
Avoid sign extension problems with signed characters smaller than int.
static CharType ToUpper (CharType Char)
Only converts ASCII characters, same as CRT to[w]upper() with standard C locale.
Static Public Member Functions inherited from TCharBase< CharType, sizeof(CharType)>
static bool IsLinebreak (CharType Char)
Additional Inherited Members
Static Public Attributes inherited from TCharBase< CharType, sizeof(CharType)>
static constexpr CharType CarriageReturn
static constexpr CharType FormFeed
static constexpr CharType LineFeed
static constexpr CharType LineSeparator
static constexpr CharType NextLine
static constexpr CharType ParagraphSeparator
static constexpr CharType VerticalTab
Detailed Description
template<typename CharType>
struct TChar< CharType >
TChar Set of utility functions operating on a single character.
The functions are specialized for ANSICHAR and TCHAR character types. You can use the typedefs FChar and FCharAnsi for convenience.
Definition at line 75 of file Char.h.
Member Function Documentation
ConvertCharDigitToInt()
template<typename CharType> int32 TChar< CharType >::ConvertCharDigitToInt (CharType Char) inline static
Definition at line 329 of file Char.h.
IsAlnum()
template<typename CharType> bool TChar< CharType >::IsAlnum (CharType Char) inline static
Definition at line 219 of file Char.h.
Referenced by TChar< TCHAR >::IsIdentifier().
IsAlpha()
template<typename CharType> bool TChar< CharType >::IsAlpha (CharType Char) inline static
Definition at line 135 of file Char.h.
IsControl()
template<typename CharType> bool TChar< CharType >::IsControl (CharType Char) inline static
Definition at line 303 of file Char.h.
IsDigit()
template<typename CharType> bool TChar< CharType >::IsDigit (CharType Char) inline static
Definition at line 240 of file Char.h.
IsGraph()
template<typename CharType> bool TChar< CharType >::IsGraph (CharType Char) inline static
Definition at line 156 of file Char.h.
IsHexDigit()
template<typename CharType> bool TChar< CharType >::IsHexDigit (CharType Char) inline static
Definition at line 261 of file Char.h.
IsIdentifier()
template<typename CharType> bool TChar< CharType >::IsIdentifier (CharType Char) inline static
Definition at line 334 of file Char.h.
IsLower()
template<typename CharType> bool TChar< CharType >::IsLower (CharType Char) inline static
Definition at line 114 of file Char.h.
IsOctDigit()
template<typename CharType> bool TChar< CharType >::IsOctDigit (CharType Char) inline static
Definition at line 324 of file Char.h.
IsPrint()
template<typename CharType> bool TChar< CharType >::IsPrint (CharType Char) inline static
Definition at line 177 of file Char.h.
IsPunct()
template<typename CharType> bool TChar< CharType >::IsPunct (CharType Char) inline static
Definition at line 198 of file Char.h.
IsUnderscore()
template<typename CharType> bool TChar< CharType >::IsUnderscore (CharType Char) inline static
Definition at line 339 of file Char.h.
Referenced by TChar< TCHAR >::IsIdentifier().
IsUpper()
template<typename CharType> bool TChar< CharType >::IsUpper (CharType Char) inline static
Definition at line 93 of file Char.h.
IsWhitespace()
template<typename CharType> bool TChar< CharType >::IsWhitespace (CharType Char) inline static
Definition at line 282 of file Char.h.
Referenced by LexTryParseString(), TStringView< CharType >::TrimEnd(), and TStringView< CharType >::TrimStart().
ToLower()
template<typename CharType> CharType TChar< CharType >::ToLower (CharType Char) inline static
Only converts ASCII characters, same as CRT to[w]upper() with standard C locale.
Definition at line 88 of file Char.h.
ToUnsigned()
template<typename CharType> constexpr FORCEINLINE uint32 TChar< CharType >::ToUnsigned (CharType Char) inline static constexpr
Avoid sign extension problems with signed characters smaller than int.
E.g. 'Ö' - 'A' is negative since the char 'Ö' (0xD6) is negative and gets sign-extended to the 32-bit int 0xFFFFFFD6 before subtraction happens.
Mainly needed for subtraction and addition.
Definition at line 352 of file Char.h.
Referenced by FAsciiSet::Contains(), FAsciiSet::operator+(), FAsciiSet::StringToBitset(), FAsciiSet::Test(), TChar< TCHAR >::ToLower(), and TChar< TCHAR >::ToUpper().
ToUpper()
template<typename CharType> CharType TChar< CharType >::ToUpper (CharType Char) inline static
Only converts ASCII characters, same as CRT to[w]upper() with standard C locale.
Definition at line 80 of file Char.h.
Referenced by FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), TCString< T >::Stristr(), TCString< T >::Strnistr(), FAndroidPlatformString::Strupr(), and FMicrosoftPlatformString::Strupr().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Char.h