Unreal Engine 5.6 C++ API: UE::Geometry::FIndex4i Struct Reference
UE::Geometry::FIndex4i Struct Reference
4-index tuple.
#include "IndexTypes.h"
Public Member Functions
FIndex4i ()
FIndex4i (int ValA, int ValB, int ValC, int ValD)
bool Contains (int Idx) const
int IndexOf (int Value) const
bool operator!= (const FIndex4i &Other) const
bool operator== (const FIndex4i &Other) const
int & operator[] (int Idx)
const int & operator[] (int Idx) const
void Serialize (FArchive &Ar)
Serialize FIndex3i to an archive.
Static Public Member Functions
static FIndex4i Invalid ()
static FIndex4i Max ()
static FIndex4i Zero ()
Data Fields
union {
struct {
int A
int B
int C
int D
}
};
Friends
FArchive & operator<< (FArchive &Ar, FIndex4i &I)
Serialization operator for FIndex4i.
Detailed Description
4-index tuple.
Ported from g3Sharp library, with the intention of maintaining compatibility with existing g3Sharp code. Has an API similar to WildMagic, GTEngine, Eigen, etc.
Definition at line 295 of file IndexTypes.h.
Constructor & Destructor Documentation
FIndex4i() [1/2]
UE::Geometry::FIndex4i::FIndex4i () inline
Definition at line 308 of file IndexTypes.h.
References FIndex4i().
Referenced by FIndex4i(), Invalid(), Max(), operator!=(), operator<<, operator==(), and Zero().
FIndex4i() [2/2]
UE::Geometry::FIndex4i::FIndex4i (int ValA, int ValB, int ValC, int ValD) inline
Definition at line 311 of file IndexTypes.h.
References A, B, C, and D.
Member Function Documentation
Contains()
bool UE::Geometry::FIndex4i::Contains (int Idx) const inline
Definition at line 360 of file IndexTypes.h.
References A, B, C, and D.
IndexOf()
int UE::Geometry::FIndex4i::IndexOf (int Value) const inline
Definition at line 355 of file IndexTypes.h.
References A, B, C, D, and Value.
Invalid()
FIndex4i UE::Geometry::FIndex4i::Invalid () inline static
Definition at line 327 of file IndexTypes.h.
References FIndex4i(), and IndexConstants::InvalidID.
Max()
FIndex4i UE::Geometry::FIndex4i::Max () inline static
Definition at line 323 of file IndexTypes.h.
References FIndex4i().
operator!=()
bool UE::Geometry::FIndex4i::operator!= (const FIndex4i & Other) const inline
Definition at line 350 of file IndexTypes.h.
References FIndex4i(), A, B, C, D, and Other.
operator==()
bool UE::Geometry::FIndex4i::operator== (const FIndex4i & Other) const inline
Definition at line 345 of file IndexTypes.h.
References FIndex4i(), A, B, C, D, and Other.
operator[]() [1/2]
int & UE::Geometry::FIndex4i::operator[] (int Idx) inline
Definition at line 332 of file IndexTypes.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator[]() [2/2]
const int & UE::Geometry::FIndex4i::operator[] (int Idx) const inline
Definition at line 338 of file IndexTypes.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Serialize()
void UE::Geometry::FIndex4i::Serialize (FArchive & Ar) inline
Serialize FIndex3i to an archive.
Definition at line 379 of file IndexTypes.h.
References A, Ar, B, C, and D.
Referenced by operator<<.
Zero()
FIndex4i UE::Geometry::FIndex4i::Zero () inline static
Definition at line 319 of file IndexTypes.h.
References FIndex4i().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FIndex4i & I) friend
Serialization operator for FIndex4i.
Parameters
Ar Archive to serialize with.
I Index to serialize.
Returns
Passing down serializing archive.
Definition at line 372 of file IndexTypes.h.
References FIndex4i(), Ar, and Serialize().
Field Documentation
[union]
union { ... } UE::Geometry::FIndex4i
A
int UE::Geometry::FIndex4i::A
Definition at line 301 of file IndexTypes.h.
Referenced by FIndex4i(), Contains(), IndexOf(), operator!=(), operator==(), and Serialize().
B
int UE::Geometry::FIndex4i::B
Definition at line 301 of file IndexTypes.h.
Referenced by FIndex4i(), Contains(), IndexOf(), operator!=(), operator==(), and Serialize().
C
int UE::Geometry::FIndex4i::C
Definition at line 301 of file IndexTypes.h.
Referenced by FIndex4i(), Contains(), IndexOf(), operator!=(), operator==(), and Serialize().
D
int UE::Geometry::FIndex4i::D
Definition at line 301 of file IndexTypes.h.
Referenced by FIndex4i(), Contains(), IndexOf(), operator!=(), operator==(), and Serialize().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/IndexTypes.h