Unreal Engine 5.6 C++ API: TPimplPtr< T, EPimplPtrMode::DeepCopy > Struct Template Reference
TPimplPtr< T, EPimplPtrMode::DeepCopy > Struct Template Reference
#include "PimplPtr.h"
Public Member Functions
TPimplPtr ()=default
TPimplPtr (const TPimplPtr &A)
TPimplPtr (TPimplPtr &&)=default
TPimplPtr (TYPE_OF_NULLPTR)
~TPimplPtr ()=default
TPimplPtr & operator= (const TPimplPtr &A)
TPimplPtr & operator= (TPimplPtr &&)=default
FORCEINLINE TPimplPtr & operator= (TYPE_OF_NULLPTR A)
Private Types
using Super = TPimplPtr<T, EPimplPtrMode::NoCopy>
Friends
template<typename U, EPimplPtrMode M, typename... ArgTypes>
TPimplPtr< U, M > MakePimpl (ArgTypes &&... Args)
Heap-allocates an instance of T with the given arguments and returns it as a TPimplPtr.
Detailed Description
template<typename T>
struct TPimplPtr< T, EPimplPtrMode::DeepCopy >
Definition at line 244 of file PimplPtr.h.
Member Typedef Documentation
Super
template<typename T> using TPimplPtr< T, EPimplPtrMode::DeepCopy >::Super = TPimplPtr<T, EPimplPtrMode::NoCopy> private
Definition at line 247 of file PimplPtr.h.
Constructor & Destructor Documentation
TPimplPtr() [1/4]
template<typename T> TPimplPtr< T, EPimplPtrMode::DeepCopy >::TPimplPtr () default
Referenced by TPimplPtr(), TPimplPtr(), MakePimpl, operator=(), operator=(), and operator=().
~TPimplPtr()
template<typename T> TPimplPtr< T, EPimplPtrMode::DeepCopy >::~TPimplPtr () default
TPimplPtr() [2/4]
template<typename T> TPimplPtr< T, EPimplPtrMode::DeepCopy >::TPimplPtr (const TPimplPtr< T, EPimplPtrMode::DeepCopy > & A) inline
Definition at line 259 of file PimplPtr.h.
References TPimplPtr(), A, and UE::Core::Private::PimplPtr::CallCopier().
TPimplPtr() [3/4]
template<typename T> TPimplPtr< T, EPimplPtrMode::DeepCopy >::TPimplPtr (TPimplPtr< T, EPimplPtrMode::DeepCopy > &&) default
References TPimplPtr().
TPimplPtr() [4/4]
template<typename T> TPimplPtr< T, EPimplPtrMode::DeepCopy >::TPimplPtr (TYPE_OF_NULLPTR) inline
Definition at line 288 of file PimplPtr.h.
Member Function Documentation
operator=() [1/3]
template<typename T> TPimplPtr & TPimplPtr< T, EPimplPtrMode::DeepCopy >::operator= (const TPimplPtr< T, EPimplPtrMode::DeepCopy > & A) inline
Definition at line 267 of file PimplPtr.h.
References TPimplPtr(), A, UE::Core::Private::PimplPtr::CallCopier(), IsValid(), and Reset.
operator=() [2/3]
template<typename T> TPimplPtr & TPimplPtr< T, EPimplPtrMode::DeepCopy >::operator= (TPimplPtr< T, EPimplPtrMode::DeepCopy > &&) default
References TPimplPtr().
operator=() [3/3]
template<typename T> FORCEINLINE TPimplPtr & TPimplPtr< T, EPimplPtrMode::DeepCopy >::operator= (TYPE_OF_NULLPTR A) inline
Definition at line 292 of file PimplPtr.h.
References TPimplPtr(), A, and FORCEINLINE.
Friends And Related Symbol Documentation
MakePimpl
template<typename T> template<typename U, EPimplPtrMode M, typename... ArgTypes> TPimplPtr< U, M > MakePimpl (ArgTypes &&... Args) friend
Heap-allocates an instance of T with the given arguments and returns it as a TPimplPtr.
Usage: TPimplPtr<FMyType> MyPtr = MakePimpl<FMyType>(...arguments...);
DeepCopy Usage: TPimplPtr<FMyType, EPimplPtrMode::DeepCopy> MyPtr = MakePimpl<FMyType, EPimplPtrMode::DeepCopy>(...arguments...);
Definition at line 319 of file PimplPtr.h.
References TPimplPtr(), DeepCopy, FORCEINLINE, Forward(), NoCopy, and UE::Core::Private::PimplPtr::RequiredAlignment.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/PimplPtr.h