Unreal Engine 5.6 C++ API: UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes > Struct Template Reference
UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes > Struct Template Reference
Templated utility class that assists in tracking the state of many -> one data relationships in an FEntityManager.
#include "MovieSceneOverlappingEntityTracker.h"
Data Structures
struct FOutput
Public Types
using KeyType = TOverlappingEntityInput<InputKeyTypes...>
using ParamType = typename TCallTraits<KeyType>::ParamType
Public Member Functions
template<typename HandlerType>
void Destroy (HandlerType &&InHandler)
Destroy all the outputs currently being tracked.
void FindEntityIDs (ParamType Key, TArray< FMovieSceneEntityID > &OutEntityIDs) const
const OutputType * FindOutput (FMovieSceneEntityID EntityID) const
const OutputType * FindOutput (ParamType Key) const
bool IsEmpty () const
bool IsInitialized () const
bool NeedsRestoration (ParamType Key, bool bEnsureOutput=false) const
template<typename HandlerType>
void ProcessInvalidatedOutputs (UMovieSceneEntitySystemLinker *Linker, HandlerType &&InHandler)
Process any outputs that were invalidated as a result of Update being called using a custom handler.
void SetNeedsRestoration (ParamType Key, bool bNeedsRestoration, bool bEnsureOutput=false)
void Update (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< InputKeyTypes >... InKeyComponents, const FEntityComponentFilter &InFilter)
Update this tracker by iterating any entity that contains InKeyComponent, and matches the additional optional filter Only entities tagged as NeedsLink or NeedsUnlink are iterated, invalidating their outputs.
template<typename ... ComponentTypes>
void UpdateFromComponents (UMovieSceneEntitySystemLinker *Linker, const FEntityComponentFilter &InFilter, TComponentTypeID< ComponentTypes >... InKeyComponents)
Update this tracker by iterating any entity that contains InKeyComponent, and matches the additional optional filter Only entities tagged as NeedsLink or NeedsUnlink are iterated, invalidating their outputs.
template<typename ... ComponentTypes>
void UpdateUnlinkedOnly (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< ComponentTypes >... InKeyComponent, const FEntityComponentFilter &InFilter)
Update this tracker by iterating any entity that contains InKeyComponent, and matches the additional optional filter Only entities tagged as NeedsUnlink are iterated, invalidating their outputs.
template<typename ... ComponentTypes>
void VisitActiveAllocation (const FEntityAllocation *Allocation, TComponentPtr< const ComponentTypes >... ReadKeys)
Update this tracker by (re)linking the specified allocation.
template<typename ... ComponentTypes>
void VisitLinkedAllocation (const FEntityAllocation *Allocation, TComponentPtr< const ComponentTypes >... ReadKeys)
Update this tracker by (re)linking the specified allocation.
void VisitUnlinkedAllocation (const FEntityAllocation *Allocation)
Update this tracker by unlinking the specified allocation.
Protected Member Functions
void ClearOutputByEntity (FMovieSceneEntityID EntityID)
uint16 CreateOutputByKey (ParamType Key)
uint16 FindOutputByEntity (FMovieSceneEntityID EntityID) const
uint16 FindOutputByKey (ParamType Key) const
bool IsOutputValid (uint16 OutputIndex)
uint16 MakeOutput (FMovieSceneEntityID EntityID, ParamType InKey, bool bAlwaysInvalidate)
template<typename ... ComponentTypes>
void VisitActiveAllocationImpl (const FEntityAllocation *Allocation, TComponentPtr< const ComponentTypes >... Keys)
void VisitUnlinkedAllocationImpl (const FEntityAllocation *Allocation)
Protected Attributes
bool bIsInitialized = false
TMap< FMovieSceneEntityID, uint16 > EntityToOutput
TBitArray InvalidatedOutputs
TMap< KeyType, uint16 > KeyToOutput
TBitArray NewOutputs
TSparseArray< FOutput > Outputs
TMultiMap< uint16, FMovieSceneEntityID > OutputToEntity
Static Protected Attributes
static constexpr uint16 NO_OUTPUT = MAX_uint16
Detailed Description
template<typename OutputType, typename... InputKeyTypes>
struct UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >
Templated utility class that assists in tracking the state of many -> one data relationships in an FEntityManager.
InputKeyTypes defines the component type(s) which defines the key that determines whether an entity animates the same output. OutputType defines the user-specfied data to be associated with the multiple inputs (ie, its output)
Definition at line 130 of file MovieSceneOverlappingEntityTracker.h.
Member Typedef Documentation
KeyType
template<typename OutputType, typename... InputKeyTypes> using UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::KeyType = TOverlappingEntityInput<InputKeyTypes...>
Definition at line 132 of file MovieSceneOverlappingEntityTracker.h.
ParamType
template<typename OutputType, typename... InputKeyTypes> using UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::ParamType = typename TCallTraits<KeyType>::ParamType
Definition at line 133 of file MovieSceneOverlappingEntityTracker.h.
Member Function Documentation
ClearOutputByEntity()
template<typename OutputType, typename... InputKeyTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::ClearOutputByEntity (FMovieSceneEntityID EntityID) inline protected
Definition at line 493 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::VisitUnlinkedAllocationImpl().
CreateOutputByKey()
template<typename OutputType, typename... InputKeyTypes> uint16 UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::CreateOutputByKey (ParamType Key) inline protected
Definition at line 461 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::MakeOutput().
Destroy()
template<typename OutputType, typename... InputKeyTypes> template<typename HandlerType> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::Destroy (HandlerType && InHandler) inline
Destroy all the outputs currently being tracked.
Definition at line 307 of file MovieSceneOverlappingEntityTracker.h.
FindEntityIDs()
template<typename OutputType, typename... InputKeyTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::FindEntityIDs (ParamType Key, TArray< FMovieSceneEntityID > & OutEntityIDs) const inline
Definition at line 326 of file MovieSceneOverlappingEntityTracker.h.
FindOutput() [1/2]
template<typename OutputType, typename... InputKeyTypes> const OutputType * UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::FindOutput (FMovieSceneEntityID EntityID) const inline
Definition at line 334 of file MovieSceneOverlappingEntityTracker.h.
FindOutput() [2/2]
template<typename OutputType, typename... InputKeyTypes> const OutputType * UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::FindOutput (ParamType Key) const inline
Definition at line 346 of file MovieSceneOverlappingEntityTracker.h.
FindOutputByEntity()
template<typename OutputType, typename... InputKeyTypes> uint16 UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::FindOutputByEntity (FMovieSceneEntityID EntityID) const inline protected
Definition at line 487 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ClearOutputByEntity(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::MakeOutput().
FindOutputByKey()
template<typename OutputType, typename... InputKeyTypes> uint16 UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::FindOutputByKey (ParamType Key) const inline protected
Definition at line 481 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::CreateOutputByKey(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::NeedsRestoration(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::SetNeedsRestoration().
IsEmpty()
template<typename OutputType, typename... InputKeyTypes> bool UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::IsEmpty () const inline
Definition at line 298 of file MovieSceneOverlappingEntityTracker.h.
IsInitialized()
template<typename OutputType, typename... InputKeyTypes> bool UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::IsInitialized () const inline
Definition at line 135 of file MovieSceneOverlappingEntityTracker.h.
IsOutputValid()
template<typename OutputType, typename... InputKeyTypes> bool UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::IsOutputValid (uint16 OutputIndex) inline protected
Definition at line 506 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::NeedsRestoration(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::SetNeedsRestoration().
MakeOutput()
template<typename OutputType, typename... InputKeyTypes> uint16 UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::MakeOutput (FMovieSceneEntityID EntityID, ParamType InKey, bool bAlwaysInvalidate) inline protected
Definition at line 423 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::VisitActiveAllocationImpl().
NeedsRestoration()
template<typename OutputType, typename... InputKeyTypes> bool UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::NeedsRestoration (ParamType Key, bool bEnsureOutput = false) const inline
Definition at line 358 of file MovieSceneOverlappingEntityTracker.h.
ProcessInvalidatedOutputs()
template<typename OutputType, typename... InputKeyTypes> template<typename HandlerType> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::ProcessInvalidatedOutputs (UMovieSceneEntitySystemLinker * Linker, HandlerType && InHandler) inline
Process any outputs that were invalidated as a result of Update being called using a custom handler.
InHandler Any user-defined handler type that contains the following named functions: // Called when an output is first created void InitializeOutput(InputKeyTypes... Inputs, TArrayView<const FMovieSceneEntityID> Inputs, OutputType* Output, FEntityOutputAggregate Aggregate);
// Called when an output has been updated with new inputs void UpdateOutput(InputKeyTypes... Inputs, TArrayView<const FMovieSceneEntityID> Inputs, OutputType* Output, FEntityOutputAggregate Aggregate);
// Called when all an output's inputs are no longer relevant, and as such the output should be destroyed (or restored) void DestroyOutput(InputKeyTypes... Inputs, OutputType* Output, FEntityOutputAggregate Aggregate);
Definition at line 231 of file MovieSceneOverlappingEntityTracker.h.
SetNeedsRestoration()
template<typename OutputType, typename... InputKeyTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::SetNeedsRestoration (ParamType Key, bool bNeedsRestoration, bool bEnsureOutput = false) inline
Definition at line 370 of file MovieSceneOverlappingEntityTracker.h.
Update()
template<typename OutputType, typename... InputKeyTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::Update (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< InputKeyTypes >... InKeyComponents, const FEntityComponentFilter & InFilter) inline
Update this tracker by iterating any entity that contains InKeyComponent, and matches the additional optional filter Only entities tagged as NeedsLink or NeedsUnlink are iterated, invalidating their outputs.
Definition at line 144 of file MovieSceneOverlappingEntityTracker.h.
UpdateFromComponents()
template<typename OutputType, typename... InputKeyTypes> template<typename ... ComponentTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::UpdateFromComponents (UMovieSceneEntitySystemLinker * Linker, const FEntityComponentFilter & InFilter, TComponentTypeID< ComponentTypes >... InKeyComponents) inline
Update this tracker by iterating any entity that contains InKeyComponent, and matches the additional optional filter Only entities tagged as NeedsLink or NeedsUnlink are iterated, invalidating their outputs.
Definition at line 154 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::Update().
UpdateUnlinkedOnly()
template<typename OutputType, typename... InputKeyTypes> template<typename ... ComponentTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::UpdateUnlinkedOnly (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< ComponentTypes >... InKeyComponent, const FEntityComponentFilter & InFilter) inline
Update this tracker by iterating any entity that contains InKeyComponent, and matches the additional optional filter Only entities tagged as NeedsUnlink are iterated, invalidating their outputs.
Definition at line 179 of file MovieSceneOverlappingEntityTracker.h.
VisitActiveAllocation()
template<typename OutputType, typename... InputKeyTypes> template<typename ... ComponentTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::VisitActiveAllocation (const FEntityAllocation * Allocation, TComponentPtr< const ComponentTypes >... ReadKeys) inline
Update this tracker by (re)linking the specified allocation.
Definition at line 196 of file MovieSceneOverlappingEntityTracker.h.
VisitActiveAllocationImpl()
template<typename OutputType, typename... InputKeyTypes> template<typename ... ComponentTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::VisitActiveAllocationImpl (const FEntityAllocation * Allocation, TComponentPtr< const ComponentTypes >... Keys) inline protected
Definition at line 384 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::VisitActiveAllocation(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::VisitLinkedAllocation().
VisitLinkedAllocation()
template<typename OutputType, typename... InputKeyTypes> template<typename ... ComponentTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::VisitLinkedAllocation (const FEntityAllocation * Allocation, TComponentPtr< const ComponentTypes >... ReadKeys) inline
Update this tracker by (re)linking the specified allocation.
Definition at line 204 of file MovieSceneOverlappingEntityTracker.h.
VisitUnlinkedAllocation()
template<typename OutputType, typename... InputKeyTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::VisitUnlinkedAllocation (const FEntityAllocation * Allocation) inline
Update this tracker by unlinking the specified allocation.
Definition at line 212 of file MovieSceneOverlappingEntityTracker.h.
VisitUnlinkedAllocationImpl()
template<typename OutputType, typename... InputKeyTypes> void UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::VisitUnlinkedAllocationImpl (const FEntityAllocation * Allocation) inline protected
Definition at line 410 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::VisitUnlinkedAllocation().
Field Documentation
bIsInitialized
template<typename OutputType, typename... InputKeyTypes> bool UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::bIsInitialized = false protected
Definition at line 528 of file MovieSceneOverlappingEntityTracker.h.
EntityToOutput
template<typename OutputType, typename... InputKeyTypes> TMap<FMovieSceneEntityID, uint16> UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::EntityToOutput protected
Definition at line 520 of file MovieSceneOverlappingEntityTracker.h.
InvalidatedOutputs
template<typename OutputType, typename... InputKeyTypes> TBitArray UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::InvalidatedOutputs protected
Definition at line 526 of file MovieSceneOverlappingEntityTracker.h.
KeyToOutput
template<typename OutputType, typename... InputKeyTypes> TMap<KeyType, uint16> UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::KeyToOutput protected
Definition at line 523 of file MovieSceneOverlappingEntityTracker.h.
NewOutputs
template<typename OutputType, typename... InputKeyTypes> TBitArray UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::NewOutputs protected
Definition at line 526 of file MovieSceneOverlappingEntityTracker.h.
NO_OUTPUT
template<typename OutputType, typename... InputKeyTypes> uint16 UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::NO_OUTPUT = MAX_uint16 static constexpr protected
Definition at line 530 of file MovieSceneOverlappingEntityTracker.h.
Outputs
template<typename OutputType, typename... InputKeyTypes> TSparseArray< FOutput > UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::Outputs protected
Definition at line 524 of file MovieSceneOverlappingEntityTracker.h.
OutputToEntity
template<typename OutputType, typename... InputKeyTypes> TMultiMap<uint16, FMovieSceneEntityID> UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputKeyTypes >::OutputToEntity protected
Definition at line 521 of file MovieSceneOverlappingEntityTracker.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneOverlappingEntityTracker.h