Unreal Engine 5.6 C++ API: UE::MovieScene::FComponentTypeID Struct Reference
UE::MovieScene::FComponentTypeID Struct Reference
#include "MovieSceneEntityIDs.h"
Public Member Functions
FComponentTypeID ()
int32 BitIndex () const
operator bool () const
template<typename T>
TComponentTypeID< T > ReinterpretCast () const
Static Public Member Functions
static FComponentTypeID FromBitIndex (int32 BitIndex)
static FComponentTypeID Invalid ()
Protected Member Functions
FComponentTypeID (uint16 InValue)
Protected Attributes
uint16 Value
Static Protected Attributes
static const uint16 INVALID = uint16(-1)
Friends
uint32 GetTypeHash (FComponentTypeID In)
bool operator!= (FComponentTypeID A, FComponentTypeID B)
bool operator< (FComponentTypeID A, FComponentTypeID B)
bool operator== (FComponentTypeID A, FComponentTypeID B)
FComponentMask & operator| (FComponentMask &A, FComponentTypeID B)
FComponentMask operator| (FComponentTypeID A, FComponentTypeID B)
Detailed Description
Definition at line 173 of file MovieSceneEntityIDs.h.
Constructor & Destructor Documentation
FComponentTypeID() [1/2]
UE::MovieScene::FComponentTypeID::FComponentTypeID () inline
Definition at line 175 of file MovieSceneEntityIDs.h.
References INVALID, and Value.
Referenced by UE::MovieScene::TComponentTypeID< T >::TComponentTypeID(), FromBitIndex(), GetTypeHash, Invalid(), operator!=, operator<, operator==, operator|, and operator|.
FComponentTypeID() [2/2]
UE::MovieScene::FComponentTypeID::FComponentTypeID (uint16 InValue) inline explicit protected
Definition at line 242 of file MovieSceneEntityIDs.h.
References Value.
Member Function Documentation
BitIndex()
int32 UE::MovieScene::FComponentTypeID::BitIndex () const inline
Definition at line 218 of file MovieSceneEntityIDs.h.
References Value.
Referenced by UE::MovieScene::FComponentMask::Contains(), FromBitIndex(), UE::MovieScene::TComponentTypeID< T >::FromBitIndex(), UE::MovieScene::FComponentMask::operator[](), UE::MovieScene::FComponentMask::operator[](), ReinterpretCast(), UE::MovieScene::FComponentMask::Remove(), and UE::MovieScene::FComponentMask::Set().
FromBitIndex()
FComponentTypeID UE::MovieScene::FComponentTypeID::FromBitIndex (int32 BitIndex) inline static
Definition at line 184 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), BitIndex(), and check.
Referenced by UE::MovieScene::FComponentMask::First(), and UE::MovieScene::FComponentTypeIDFilter::GetComponentType().
Invalid()
FComponentTypeID UE::MovieScene::FComponentTypeID::Invalid () inline static
Definition at line 179 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), and INVALID.
Referenced by UE::MovieScene::FSystemTaskPrerequisites::FSystemTaskPrerequisites(), UE::MovieScene::FSystemTaskPrerequisites::AddRootTask(), UE::MovieScene::FEntityManager::ContainsAnyComponent(), UE::MovieScene::FEntityFactories::DefineChildComponent(), UE::MovieScene::FComponentMask::First(), UE::MovieScene::IsAccessorValid(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulatePrerequisites().
operator bool()
UE::MovieScene::FComponentTypeID::operator bool () const inline explicit
Definition at line 193 of file MovieSceneEntityIDs.h.
References INVALID, and Value.
ReinterpretCast()
template<typename T> TComponentTypeID< T > UE::MovieScene::FComponentTypeID::ReinterpretCast () const inline
Definition at line 501 of file MovieSceneEntityIDs.h.
References BitIndex(), and UE::MovieScene::TComponentTypeID< T >::FromBitIndex().
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::MakeInitialValueProcessor(), UE::MovieScene::FComponentRegistry::NewComponentType(), UE::MovieScene::FComponentRegistry::NewComponentTypeNoAddReferencedObjects(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendChannel(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendImpl().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FComponentTypeID In) friend
Definition at line 213 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), and Value.
operator!=
bool operator!= (FComponentTypeID A, FComponentTypeID B) friend
Definition at line 208 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), A, and B.
operator<
bool operator< (FComponentTypeID A, FComponentTypeID B) friend
Definition at line 198 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), A, and B.
operator==
bool operator== (FComponentTypeID A, FComponentTypeID B) friend
Definition at line 203 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), A, and B.
operator| [1/2]
FComponentMask & operator| (FComponentMask & A, FComponentTypeID B) friend
Definition at line 233 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), A, B, check, and INVALID.
operator| [2/2]
FComponentMask operator| (FComponentTypeID A, FComponentTypeID B) friend
Definition at line 223 of file MovieSceneEntityIDs.h.
References FComponentTypeID(), A, B, check, INVALID, and Mask.
Field Documentation
INVALID
const uint16 UE::MovieScene::FComponentTypeID::INVALID = uint16(-1) static protected
Definition at line 246 of file MovieSceneEntityIDs.h.
Referenced by FComponentTypeID(), Invalid(), operator bool(), operator|, and operator|.
Value
uint16 UE::MovieScene::FComponentTypeID::Value protected
Definition at line 247 of file MovieSceneEntityIDs.h.
Referenced by FComponentTypeID(), FComponentTypeID(), BitIndex(), GetTypeHash, and operator bool().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityIDs.h