Unreal Engine 5.6 C++ API: FViewMatrices Struct Reference
FViewMatrices Struct Reference
#include "SceneView.h"
Data Structures
struct FMinimalInitializer
Public Member Functions
FViewMatrices ()
FViewMatrices (const FMinimalInitializer &Initializer)
FViewMatrices (const FSceneViewInitOptions &InitOptions)
void ApplyWorldOffset (const FVector &InOffset)
const FVector2D ComputeHalfFieldOfViewPerAxis () const
const FMatrix ComputeInvProjectionNoAAMatrix () const
FMatrix::FReal ComputeNearPlane () const
FMatrix::FReal ComputeOrthoFarPlane () const
const FMatrix ComputeProjectionNoAAMatrix () const
const FMatrix ComputeViewRotationProjectionMatrix () const
const FVector & GetCameraToViewTarget () const
FVector2f GetFirstPersonHalfFieldOfViewPerAxis () const
float GetFirstPersonScale () const
FVector4f GetFirstPersonTanAndInvTanHalfFOV () const
const FMatrix & GetFirstPersonTransform () const
const FMatrix & GetHMDViewMatrixNoRoll () const
const FMatrix & GetInvProjectionMatrix () const
FVector2f GetInvTanHalfFov () const
const FMatrix & GetInvTranslatedViewMatrix () const
const FMatrix & GetInvTranslatedViewProjectionMatrix () const
const FMatrix & GetInvViewMatrix () const
const FMatrix & GetInvViewProjectionMatrix () const
FVector2f GetOrthoDimensions () const
const FMatrix & GetOverriddenInvTranslatedViewMatrix () const
const FMatrix & GetOverriddenTranslatedViewMatrix () const
float GetPerProjectionDepthThicknessScale () const
const FVector & GetPreViewTranslation () const
const FMatrix & GetProjectionMatrix () const
const FMatrix & GetProjectionNoAAMatrix () const
const FVector2D & GetProjectionScale () const
float GetScreenScale () const
const FMatrix & GetScreenToClipMatrix () const
FVector4f GetTanAndInvTanHalfFOV () const
FVector2f GetTanHalfFov () const
const FVector2D GetTemporalAAJitter () const
const FMatrix & GetTranslatedViewMatrix () const
const FMatrix & GetTranslatedViewProjectionMatrix () const
const FMatrix & GetViewMatrix () const
const FVector & GetViewOrigin () const
const FMatrix & GetViewProjectionMatrix () const
void HackAddTemporalAAProjectionJitter (const FVector2D &InTemporalAAProjectionJitter)
void HackOverrideViewMatrixForShadows (const FMatrix &InViewMatrix)
void HackRemoveTemporalAAProjectionJitter ()
bool IsPerspectiveProjection () const
void SaveProjectionNoAAMatrix ()
FMatrix ScreenToClipProjectionMatrix () const
void UpdatePlanarReflectionViewMatrix (const FSceneView &SourceView, const FMirrorMatrix &MirrorMatrix)
void UpdateViewMatrix (const FVector &ViewLocation, const FRotator &ViewRotation)
Private Member Functions
void Init (const FMinimalInitializer &Initializer)
void RecomputeDerivedMatrices ()
Static Private Member Functions
static const FMatrix InvertProjectionMatrix (const FMatrix &M)
Private Attributes
FVector CameraToViewTarget
The current view target's location proportional to the camera location.
FFirstPersonParameters FirstPersonParams
Parameters controlling the rendering (FOV and scale) of first person primitives.
FMatrix FirstPersonTransform
Scale and shear to avoid first person primitives to clip with the scene and to achieve a first person specific FOV.
FMatrix HMDViewMatrixNoRoll
FMatrix InvProjectionMatrix
ClipToView : UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
FMatrix InvTranslatedViewMatrix
ViewToWorld with PreViewTranslation.
FMatrix InvTranslatedViewProjectionMatrix
The inverse view-projection transform, ending with world-space points translated by -ViewOrigin.
FMatrix InvViewMatrix
FMatrix InvViewProjectionMatrix
FMatrix OverriddenInvTranslatedViewMatrix
ViewToWorld with PreViewTranslation.
FMatrix OverriddenTranslatedViewMatrix
WorldToView with PreViewTranslation.
float PerProjectionDepthThicknessScale
Depth test scaling; differs between perspective and orthographic.
FVector PreViewTranslation
The translation to apply to the world before TranslatedViewProjectionMatrix.
FMatrix ProjectionMatrix
ViewToClip : UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
FMatrix ProjectionNoAAMatrix
ViewToClipNoAA : UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
FVector2D ProjectionScale
Scale applied by the projection matrix in X and Y.
float ScreenScale
Scale factor to use when computing the size of a sphere in pixels.
FMatrix ScreenToClipMatrix
The screen to clip matrix (defined depending on whether this is a perspective or ortho projection view)
FVector2D TemporalAAProjectionJitter
TemporalAA jitter offset currently stored in the projection matrix.
FMatrix TranslatedViewMatrix
WorldToView with PreViewTranslation.
FMatrix TranslatedViewProjectionMatrix
The view-projection transform, starting from world-space points translated by -ViewOrigin.
FMatrix ViewMatrix
FVector ViewOrigin
The camera/viewport location in world space.
FMatrix ViewProjectionMatrix
Detailed Description
Definition at line 311 of file SceneView.h.
Constructor & Destructor Documentation
FViewMatrices() [1/3]
FViewMatrices::FViewMatrices () inline
Definition at line 324 of file SceneView.h.
References CameraToViewTarget, FirstPersonTransform, HMDViewMatrixNoRoll, InvProjectionMatrix, InvTranslatedViewMatrix, InvTranslatedViewProjectionMatrix, InvViewMatrix, InvViewProjectionMatrix, OverriddenInvTranslatedViewMatrix, OverriddenTranslatedViewMatrix, PreViewTranslation, ProjectionMatrix, ProjectionNoAAMatrix, ProjectionScale, ScreenScale, ScreenToClipMatrix, TemporalAAProjectionJitter, TranslatedViewMatrix, TranslatedViewProjectionMatrix, ViewMatrix, ViewOrigin, ViewProjectionMatrix, UE::Math::TVector2< double >::ZeroVector, and UE::Math::TVector< double >::ZeroVector.
FViewMatrices() [2/3]
FViewMatrices::FViewMatrices (const FMinimalInitializer & Initializer)
FViewMatrices() [3/3]
FViewMatrices::FViewMatrices (const FSceneViewInitOptions & InitOptions)
Member Function Documentation
ApplyWorldOffset()
void FViewMatrices::ApplyWorldOffset (const FVector & InOffset) inline
Definition at line 699 of file SceneView.h.
References FVector, InvViewMatrix, PreViewTranslation, RecomputeDerivedMatrices(), ViewMatrix, and ViewOrigin.
ComputeHalfFieldOfViewPerAxis()
const FVector2D FViewMatrices::ComputeHalfFieldOfViewPerAxis () const inline
Definition at line 665 of file SceneView.h.
References ComputeInvProjectionNoAAMatrix(), FVector, IsPerspectiveProjection(), UE::Math::TVector< T >::Normalize(), UE::Math::TMatrix< T >::TransformPosition(), UE::Math::TVector2< double >::X, and UE::Math::TVector2< double >::Zero().
ComputeInvProjectionNoAAMatrix()
const FMatrix FViewMatrices::ComputeInvProjectionNoAAMatrix () const inline
Definition at line 659 of file SceneView.h.
References ComputeProjectionNoAAMatrix(), and InvertProjectionMatrix().
Referenced by ComputeHalfFieldOfViewPerAxis().
ComputeNearPlane()
FMatrix::FReal FViewMatrices::ComputeNearPlane () const inline
Definition at line 685 of file SceneView.h.
References ProjectionMatrix.
Referenced by ComputeOrthoFarPlane().
ComputeOrthoFarPlane()
FMatrix::FReal FViewMatrices::ComputeOrthoFarPlane () const inline
Definition at line 690 of file SceneView.h.
References ComputeNearPlane(), InvProjectionMatrix, and IsPerspectiveProjection().
ComputeProjectionNoAAMatrix()
const FMatrix FViewMatrices::ComputeProjectionNoAAMatrix () const inline
Definition at line 631 of file SceneView.h.
References IsPerspectiveProjection(), UE::Math::TMatrix< T >::M, ProjectionMatrix, and TemporalAAProjectionJitter.
Referenced by ComputeInvProjectionNoAAMatrix().
ComputeViewRotationProjectionMatrix()
const FMatrix FViewMatrices::ComputeViewRotationProjectionMatrix () const inline
Definition at line 654 of file SceneView.h.
References ProjectionMatrix, and ViewMatrix.
GetCameraToViewTarget()
const FVector & FViewMatrices::GetCameraToViewTarget () const inline
Definition at line 523 of file SceneView.h.
References CameraToViewTarget, and FVector.
GetFirstPersonHalfFieldOfViewPerAxis()
FVector2f FViewMatrices::GetFirstPersonHalfFieldOfViewPerAxis () const inline
Definition at line 719 of file SceneView.h.
References GetFirstPersonTanAndInvTanHalfFOV(), IsPerspectiveProjection(), UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector2< float >::Zero().
GetFirstPersonScale()
float FViewMatrices::GetFirstPersonScale () const inline
Definition at line 508 of file SceneView.h.
References FirstPersonParams.
GetFirstPersonTanAndInvTanHalfFOV()
FVector4f FViewMatrices::GetFirstPersonTanAndInvTanHalfFOV () const inline
Definition at line 730 of file SceneView.h.
References FirstPersonParams, GetTanAndInvTanHalfFOV(), IsPerspectiveProjection(), UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Referenced by GetFirstPersonHalfFieldOfViewPerAxis().
GetFirstPersonTransform()
const FMatrix & FViewMatrices::GetFirstPersonTransform () const inline
Definition at line 503 of file SceneView.h.
References FirstPersonTransform.
GetHMDViewMatrixNoRoll()
const FMatrix & FViewMatrices::GetHMDViewMatrixNoRoll () const inline
Definition at line 463 of file SceneView.h.
References HMDViewMatrixNoRoll.
GetInvProjectionMatrix()
const FMatrix & FViewMatrices::GetInvProjectionMatrix () const inline
Definition at line 438 of file SceneView.h.
References InvProjectionMatrix.
Referenced by RecomputeDerivedMatrices().
GetInvTanHalfFov()
FVector2f FViewMatrices::GetInvTanHalfFov () const inline
Definition at line 544 of file SceneView.h.
References IsPerspectiveProjection(), and ProjectionMatrix.
GetInvTranslatedViewMatrix()
const FMatrix & FViewMatrices::GetInvTranslatedViewMatrix () const inline
Definition at line 473 of file SceneView.h.
References InvTranslatedViewMatrix.
Referenced by RecomputeDerivedMatrices().
GetInvTranslatedViewProjectionMatrix()
const FMatrix & FViewMatrices::GetInvTranslatedViewProjectionMatrix () const inline
Definition at line 493 of file SceneView.h.
References InvTranslatedViewProjectionMatrix.
GetInvViewMatrix()
const FMatrix & FViewMatrices::GetInvViewMatrix () const inline
Definition at line 448 of file SceneView.h.
References InvViewMatrix.
Referenced by RecomputeDerivedMatrices().
GetInvViewProjectionMatrix()
const FMatrix & FViewMatrices::GetInvViewProjectionMatrix () const inline
Definition at line 458 of file SceneView.h.
References InvViewProjectionMatrix.
GetOrthoDimensions()
FVector2f FViewMatrices::GetOrthoDimensions () const inline
Definition at line 709 of file SceneView.h.
References InvProjectionMatrix, IsPerspectiveProjection(), and UE::Math::TVector2< float >::ZeroVector.
GetOverriddenInvTranslatedViewMatrix()
const FMatrix & FViewMatrices::GetOverriddenInvTranslatedViewMatrix () const inline
Definition at line 483 of file SceneView.h.
References OverriddenInvTranslatedViewMatrix.
GetOverriddenTranslatedViewMatrix()
const FMatrix & FViewMatrices::GetOverriddenTranslatedViewMatrix () const inline
Definition at line 478 of file SceneView.h.
References OverriddenTranslatedViewMatrix.
GetPerProjectionDepthThicknessScale()
float FViewMatrices::GetPerProjectionDepthThicknessScale () const inline
Definition at line 578 of file SceneView.h.
References PerProjectionDepthThicknessScale.
GetPreViewTranslation()
const FVector & FViewMatrices::GetPreViewTranslation () const inline
Definition at line 513 of file SceneView.h.
References FVector, and PreViewTranslation.
GetProjectionMatrix()
const FMatrix & FViewMatrices::GetProjectionMatrix () const inline
Definition at line 428 of file SceneView.h.
References ProjectionMatrix.
Referenced by RecomputeDerivedMatrices().
GetProjectionNoAAMatrix()
const FMatrix & FViewMatrices::GetProjectionNoAAMatrix () const inline
Definition at line 433 of file SceneView.h.
References ProjectionNoAAMatrix.
GetProjectionScale()
const FVector2D & FViewMatrices::GetProjectionScale () const inline
Definition at line 533 of file SceneView.h.
References ProjectionScale.
GetScreenScale()
float FViewMatrices::GetScreenScale () const inline
Definition at line 528 of file SceneView.h.
References ScreenScale.
GetScreenToClipMatrix()
const FMatrix & FViewMatrices::GetScreenToClipMatrix () const inline
Definition at line 498 of file SceneView.h.
References ScreenToClipMatrix.
GetTanAndInvTanHalfFOV()
FVector4f FViewMatrices::GetTanAndInvTanHalfFOV () const inline
Definition at line 565 of file SceneView.h.
References InvProjectionMatrix, IsPerspectiveProjection(), and ProjectionMatrix.
Referenced by GetFirstPersonTanAndInvTanHalfFOV().
GetTanHalfFov()
FVector2f FViewMatrices::GetTanHalfFov () const inline
Definition at line 554 of file SceneView.h.
References InvProjectionMatrix, and IsPerspectiveProjection().
GetTemporalAAJitter()
const FVector2D FViewMatrices::GetTemporalAAJitter () const inline
Definition at line 649 of file SceneView.h.
References TemporalAAProjectionJitter.
GetTranslatedViewMatrix()
const FMatrix & FViewMatrices::GetTranslatedViewMatrix () const inline
Definition at line 468 of file SceneView.h.
References TranslatedViewMatrix.
Referenced by RecomputeDerivedMatrices().
GetTranslatedViewProjectionMatrix()
const FMatrix & FViewMatrices::GetTranslatedViewProjectionMatrix () const inline
Definition at line 488 of file SceneView.h.
References TranslatedViewProjectionMatrix.
GetViewMatrix()
const FMatrix & FViewMatrices::GetViewMatrix () const inline
Definition at line 443 of file SceneView.h.
References ViewMatrix.
Referenced by RecomputeDerivedMatrices().
GetViewOrigin()
const FVector & FViewMatrices::GetViewOrigin () const inline
Definition at line 518 of file SceneView.h.
References FVector, and ViewOrigin.
Referenced by FDebugRenderSceneProxy::PointInRange().
GetViewProjectionMatrix()
const FMatrix & FViewMatrices::GetViewProjectionMatrix () const inline
Definition at line 453 of file SceneView.h.
References ViewProjectionMatrix.
HackAddTemporalAAProjectionJitter()
void FViewMatrices::HackAddTemporalAAProjectionJitter (const FVector2D & InTemporalAAProjectionJitter) inline
Definition at line 592 of file SceneView.h.
References ensure, InvertProjectionMatrix(), InvProjectionMatrix, IsPerspectiveProjection(), ProjectionMatrix, RecomputeDerivedMatrices(), and TemporalAAProjectionJitter.
HackOverrideViewMatrixForShadows()
void FViewMatrices::HackOverrideViewMatrixForShadows (const FMatrix & InViewMatrix)
HackRemoveTemporalAAProjectionJitter()
void FViewMatrices::HackRemoveTemporalAAProjectionJitter () inline
Definition at line 613 of file SceneView.h.
References InvertProjectionMatrix(), InvProjectionMatrix, IsPerspectiveProjection(), ProjectionMatrix, RecomputeDerivedMatrices(), TemporalAAProjectionJitter, and UE::Math::TVector2< double >::ZeroVector.
Init()
void FViewMatrices::Init (const FMinimalInitializer & Initializer) private
InvertProjectionMatrix()
const FMatrix FViewMatrices::InvertProjectionMatrix (const FMatrix & M) inline static private
Definition at line 760 of file SceneView.h.
References UE::Math::TMatrix< T >::Inverse(), and UE::Math::TMatrix< T >::M.
Referenced by ComputeInvProjectionNoAAMatrix(), HackAddTemporalAAProjectionJitter(), and HackRemoveTemporalAAProjectionJitter().
IsPerspectiveProjection()
bool FViewMatrices::IsPerspectiveProjection () const inline
Returns
true:perspective, false:orthographic
Definition at line 539 of file SceneView.h.
References ProjectionMatrix.
Referenced by ComputeHalfFieldOfViewPerAxis(), ComputeOrthoFarPlane(), ComputeProjectionNoAAMatrix(), GetFirstPersonHalfFieldOfViewPerAxis(), GetFirstPersonTanAndInvTanHalfFOV(), GetInvTanHalfFov(), GetOrthoDimensions(), GetTanAndInvTanHalfFOV(), GetTanHalfFov(), HackAddTemporalAAProjectionJitter(), and HackRemoveTemporalAAProjectionJitter().
RecomputeDerivedMatrices()
void FViewMatrices::RecomputeDerivedMatrices () inline private
Definition at line 749 of file SceneView.h.
References GetInvProjectionMatrix(), GetInvTranslatedViewMatrix(), GetInvViewMatrix(), GetProjectionMatrix(), GetTranslatedViewMatrix(), GetViewMatrix(), InvTranslatedViewProjectionMatrix, InvViewProjectionMatrix, TranslatedViewProjectionMatrix, and ViewProjectionMatrix.
Referenced by ApplyWorldOffset(), HackAddTemporalAAProjectionJitter(), and HackRemoveTemporalAAProjectionJitter().
SaveProjectionNoAAMatrix()
void FViewMatrices::SaveProjectionNoAAMatrix () inline
Definition at line 587 of file SceneView.h.
References ProjectionMatrix, and ProjectionNoAAMatrix.
ScreenToClipProjectionMatrix()
FMatrix FViewMatrices::ScreenToClipProjectionMatrix () const
UpdatePlanarReflectionViewMatrix()
void FViewMatrices::UpdatePlanarReflectionViewMatrix (const FSceneView & SourceView, const FMirrorMatrix & MirrorMatrix)
UpdateViewMatrix()
void FViewMatrices::UpdateViewMatrix (const FVector & ViewLocation, const FRotator & ViewRotation)
References FVector.
Field Documentation
CameraToViewTarget
FVector FViewMatrices::CameraToViewTarget private
The current view target's location proportional to the camera location.
Definition at line 394 of file SceneView.h.
Referenced by FViewMatrices(), and GetCameraToViewTarget().
FirstPersonParams
FFirstPersonParameters FViewMatrices::FirstPersonParams private
Parameters controlling the rendering (FOV and scale) of first person primitives.
Definition at line 414 of file SceneView.h.
Referenced by GetFirstPersonScale(), and GetFirstPersonTanAndInvTanHalfFOV().
FirstPersonTransform
FMatrix FViewMatrices::FirstPersonTransform private
Scale and shear to avoid first person primitives to clip with the scene and to achieve a first person specific FOV.
Definition at line 388 of file SceneView.h.
Referenced by FViewMatrices(), and GetFirstPersonTransform().
HMDViewMatrixNoRoll
FMatrix FViewMatrices::HMDViewMatrixNoRoll private
Definition at line 372 of file SceneView.h.
Referenced by FViewMatrices(), and GetHMDViewMatrixNoRoll().
InvProjectionMatrix
FMatrix FViewMatrices::InvProjectionMatrix private
ClipToView : UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
Definition at line 362 of file SceneView.h.
Referenced by FViewMatrices(), ComputeOrthoFarPlane(), GetInvProjectionMatrix(), GetOrthoDimensions(), GetTanAndInvTanHalfFOV(), GetTanHalfFov(), HackAddTemporalAAProjectionJitter(), and HackRemoveTemporalAAProjectionJitter().
InvTranslatedViewMatrix
FMatrix FViewMatrices::InvTranslatedViewMatrix private
ViewToWorld with PreViewTranslation.
Definition at line 376 of file SceneView.h.
Referenced by FViewMatrices(), and GetInvTranslatedViewMatrix().
InvTranslatedViewProjectionMatrix
FMatrix FViewMatrices::InvTranslatedViewProjectionMatrix private
The inverse view-projection transform, ending with world-space points translated by -ViewOrigin.
Definition at line 384 of file SceneView.h.
Referenced by FViewMatrices(), GetInvTranslatedViewProjectionMatrix(), and RecomputeDerivedMatrices().
InvViewMatrix
FMatrix FViewMatrices::InvViewMatrix private
Definition at line 366 of file SceneView.h.
Referenced by FViewMatrices(), ApplyWorldOffset(), and GetInvViewMatrix().
InvViewProjectionMatrix
FMatrix FViewMatrices::InvViewProjectionMatrix private
Definition at line 370 of file SceneView.h.
Referenced by FViewMatrices(), GetInvViewProjectionMatrix(), and RecomputeDerivedMatrices().
OverriddenInvTranslatedViewMatrix
FMatrix FViewMatrices::OverriddenInvTranslatedViewMatrix private
ViewToWorld with PreViewTranslation.
Definition at line 380 of file SceneView.h.
Referenced by FViewMatrices(), and GetOverriddenInvTranslatedViewMatrix().
OverriddenTranslatedViewMatrix
FMatrix FViewMatrices::OverriddenTranslatedViewMatrix private
WorldToView with PreViewTranslation.
Definition at line 378 of file SceneView.h.
Referenced by FViewMatrices(), and GetOverriddenTranslatedViewMatrix().
PerProjectionDepthThicknessScale
float FViewMatrices::PerProjectionDepthThicknessScale private
Depth test scaling; differs between perspective and orthographic.
Definition at line 411 of file SceneView.h.
Referenced by GetPerProjectionDepthThicknessScale().
PreViewTranslation
FVector FViewMatrices::PreViewTranslation private
The translation to apply to the world before TranslatedViewProjectionMatrix.
Usually it is -ViewOrigin but with rereflections this can differ
Definition at line 390 of file SceneView.h.
Referenced by FViewMatrices(), ApplyWorldOffset(), and GetPreViewTranslation().
ProjectionMatrix
FMatrix FViewMatrices::ProjectionMatrix private
ViewToClip : UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
Definition at line 358 of file SceneView.h.
Referenced by FViewMatrices(), ComputeNearPlane(), ComputeProjectionNoAAMatrix(), ComputeViewRotationProjectionMatrix(), GetInvTanHalfFov(), GetProjectionMatrix(), GetTanAndInvTanHalfFOV(), HackAddTemporalAAProjectionJitter(), HackRemoveTemporalAAProjectionJitter(), IsPerspectiveProjection(), and SaveProjectionNoAAMatrix().
ProjectionNoAAMatrix
FMatrix FViewMatrices::ProjectionNoAAMatrix private
ViewToClipNoAA : UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
Don't apply any AA jitter
Definition at line 360 of file SceneView.h.
Referenced by FViewMatrices(), GetProjectionNoAAMatrix(), and SaveProjectionNoAAMatrix().
ProjectionScale
FVector2D FViewMatrices::ProjectionScale private
Scale applied by the projection matrix in X and Y.
Definition at line 396 of file SceneView.h.
Referenced by FViewMatrices(), and GetProjectionScale().
ScreenScale
float FViewMatrices::ScreenScale private
Scale factor to use when computing the size of a sphere in pixels.
A common calculation is to determine the size of a sphere in pixels when projected on the screen: ScreenRadius = max(0.5 * ViewSizeX * ProjMatrix[0][0], 0.5 * ViewSizeY * ProjMatrix[1][1]) * SphereRadius / ProjectedSpherePosition.W Instead you can now simply use: ScreenRadius = ScreenScale * SphereRadius / ProjectedSpherePosition.W
Definition at line 408 of file SceneView.h.
Referenced by FViewMatrices(), and GetScreenScale().
ScreenToClipMatrix
FMatrix FViewMatrices::ScreenToClipMatrix private
The screen to clip matrix (defined depending on whether this is a perspective or ortho projection view)
Definition at line 386 of file SceneView.h.
Referenced by FViewMatrices(), and GetScreenToClipMatrix().
TemporalAAProjectionJitter
FVector2D FViewMatrices::TemporalAAProjectionJitter private
TemporalAA jitter offset currently stored in the projection matrix.
Definition at line 398 of file SceneView.h.
Referenced by FViewMatrices(), ComputeProjectionNoAAMatrix(), GetTemporalAAJitter(), HackAddTemporalAAProjectionJitter(), and HackRemoveTemporalAAProjectionJitter().
TranslatedViewMatrix
FMatrix FViewMatrices::TranslatedViewMatrix private
WorldToView with PreViewTranslation.
Definition at line 374 of file SceneView.h.
Referenced by FViewMatrices(), and GetTranslatedViewMatrix().
TranslatedViewProjectionMatrix
FMatrix FViewMatrices::TranslatedViewProjectionMatrix private
The view-projection transform, starting from world-space points translated by -ViewOrigin.
Definition at line 382 of file SceneView.h.
Referenced by FViewMatrices(), GetTranslatedViewProjectionMatrix(), and RecomputeDerivedMatrices().
ViewMatrix
FMatrix FViewMatrices::ViewMatrix private
Definition at line 364 of file SceneView.h.
Referenced by FViewMatrices(), ApplyWorldOffset(), ComputeViewRotationProjectionMatrix(), and GetViewMatrix().
ViewOrigin
FVector FViewMatrices::ViewOrigin private
The camera/viewport location in world space.
Definition at line 392 of file SceneView.h.
Referenced by FViewMatrices(), ApplyWorldOffset(), and GetViewOrigin().
ViewProjectionMatrix
FMatrix FViewMatrices::ViewProjectionMatrix private
Definition at line 368 of file SceneView.h.
Referenced by FViewMatrices(), GetViewProjectionMatrix(), and RecomputeDerivedMatrices().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/SceneView.h