Unreal Engine 5.6 C++ API: FDocumentTabFactoryForObjects< BaseClass > Struct Template Reference
FDocumentTabFactoryForObjects< BaseClass > Struct Template Reference abstract
#include "WorkflowUObjectDocuments.h"
Public Member Functions
virtual TSharedRef< SWidget > CreateTabBody (const FWorkflowTabSpawnInfo &Info) const override
virtual const FSlateBrush * GetTabIcon (const FWorkflowTabSpawnInfo &Info) const override
virtual bool IsPayloadSupported (TSharedRef< FTabPayload > Payload) const override
virtual bool IsPayloadValid (TSharedRef< FTabPayload > Payload) const override
Returns TRUE if the payload is valid.
virtual bool SupportsObjectType (UObject *DocumentID) const
Public Member Functions inherited from FDocumentTabFactory
virtual UNREALED_API TSharedRef< struct FGenericTabHistory > CreateTabHistoryNode (TSharedPtr< FTabPayload > Payload)
Creates a tab history node from the passed in payload.
virtual void OnTabActivated (TSharedPtr< SDockTab > Tab) const
virtual void OnTabBackgrounded (TSharedPtr< SDockTab > Tab) const
virtual void OnTabForegrounded (TSharedPtr< SDockTab > Tab) const
virtual void OnTabRefreshed (TSharedPtr< SDockTab > Tab) const
virtual void SaveState (TSharedPtr< SDockTab > Tab, TSharedPtr< FTabPayload > Payload) const
Public Member Functions inherited from FWorkflowTabFactory
UNREALED_API FWorkflowTabFactory (FName InIdentifier, TSharedPtr< class FAssetEditorToolkit > InHostingApp)
virtual ~FWorkflowTabFactory ()
virtual UNREALED_API TAttribute< FText > ConstructTabLabelSuffix (const FWorkflowTabSpawnInfo &Info) const
virtual UNREALED_API TSharedPtr< SToolTip > CreateTabToolTipWidget (const FWorkflowTabSpawnInfo &Info) const
virtual UNREALED_API void CreateViewMenuEntry (FMenuBuilder &MenuBuilder, const FUIAction &Action) const
FName GetIdentifier () const
virtual UNREALED_API const FSlateIcon & GetTabSpawnerIcon (const FWorkflowTabSpawnInfo &Info) const
virtual FText GetTabToolTipText (const FWorkflowTabSpawnInfo &Info) const
bool IsSingleton () const
virtual UNREALED_API FTabSpawnerEntry & RegisterTabSpawner (TSharedRef< FTabManager > TabManager, const FApplicationMode *CurrentApplicationMode) const
Register a tab spawner for this factory.
virtual UNREALED_API TSharedRef< SDockTab > SpawnBlankTab () const
virtual UNREALED_API TSharedRef< SDockTab > SpawnTab (const FWorkflowTabSpawnInfo &Info) const
virtual UNREALED_API void UpdateTab (TSharedPtr< SDockTab > InDockTab, const FWorkflowTabSpawnInfo &Info, TSharedPtr< SWidget > InContent) const
Updates a given tab with new content.
Public Member Functions inherited from TSharedFromThis< FWorkflowTabFactory >
TSharedRef< FWorkflowTabFactory, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FWorkflowTabFactory, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
FDocumentTabFactoryForObjects (FName InIdentifier, TSharedPtr< class FAssetEditorToolkit > InHostingApp)
virtual TAttribute< FText > ConstructTabName (const FWorkflowTabSpawnInfo &Info) const override
virtual TAttribute< FText > ConstructTabNameForObject (BaseClass *DocumentID) const =0
virtual TSharedRef< SWidget > CreateTabBodyForObject (const FWorkflowTabSpawnInfo &Info, BaseClass *DocumentID) const =0
virtual const FSlateBrush * GetTabIconForObject (const FWorkflowTabSpawnInfo &Info, BaseClass *DocumentID) const =0
Protected Member Functions inherited from FDocumentTabFactory
UNREALED_API FDocumentTabFactory (FName InIdentifier, TSharedPtr< class FAssetEditorToolkit > InHostingApp)
Protected Member Functions inherited from FWorkflowTabFactory
virtual UNREALED_API bool CanSpawnTab (const FSpawnTabArgs &SpawnArgs, TWeakPtr< FTabManager > WeakTabManager) const
Callback function for checking to see if a tab can/should be spawned.
UNREALED_API void EnableTabPadding ()
virtual UNREALED_API TSharedRef< SDockTab > OnSpawnTab (const FSpawnTabArgs &SpawnArgs, TWeakPtr< FTabManager > WeakTabManager) const
Callback function for spawning the tab.
Protected Member Functions inherited from TSharedFromThis< FWorkflowTabFactory >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FWorkflowTabFactory >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FWorkflowTabFactory
bool bIsSingleton
bool bShouldAutosize
TWeakPtr< class FAssetEditorToolkit > HostingApp
float InsideTabPadding
FSlateIcon TabIcon
FName TabIdentifier
FText TabLabel
ETabRole TabRole
FText ViewMenuDescription
FText ViewMenuTooltip
Detailed Description
template<typename BaseClass>
struct FDocumentTabFactoryForObjects< BaseClass >
Definition at line 73 of file WorkflowUObjectDocuments.h.
Constructor & Destructor Documentation
FDocumentTabFactoryForObjects()
template<typename BaseClass> FDocumentTabFactoryForObjects< BaseClass >::FDocumentTabFactoryForObjects (FName InIdentifier, TSharedPtr< class FAssetEditorToolkit > InHostingApp) inline protected
Definition at line 118 of file WorkflowUObjectDocuments.h.
References FDocumentTabFactory::FDocumentTabFactory().
Member Function Documentation
ConstructTabName()
template<typename BaseClass> virtual TAttribute< FText > FDocumentTabFactoryForObjects< BaseClass >::ConstructTabName (const FWorkflowTabSpawnInfo & Info) const inline override protected virtual
Reimplemented from FWorkflowTabFactory.
Definition at line 124 of file WorkflowUObjectDocuments.h.
References FTabPayload_UObject::CastChecked(), check, ConstructTabNameForObject(), and Info.
ConstructTabNameForObject()
template<typename BaseClass> virtual TAttribute< FText > FDocumentTabFactoryForObjects< BaseClass >::ConstructTabNameForObject (BaseClass * DocumentID) const protected pure virtual
Implemented in FRigVMGraphEditorSummoner.
Referenced by ConstructTabName().
CreateTabBody()
template<typename BaseClass> virtual TSharedRef< SWidget > FDocumentTabFactoryForObjects< BaseClass >::CreateTabBody (const FWorkflowTabSpawnInfo & Info) const inline override virtual
Reimplemented from FWorkflowTabFactory.
Definition at line 84 of file WorkflowUObjectDocuments.h.
References FTabPayload_UObject::CastChecked(), CreateTabBodyForObject(), and Info.
CreateTabBodyForObject()
template<typename BaseClass> virtual TSharedRef< SWidget > FDocumentTabFactoryForObjects< BaseClass >::CreateTabBodyForObject (const FWorkflowTabSpawnInfo & Info, BaseClass * DocumentID) const protected pure virtual
Implemented in FRigVMGraphEditorSummoner.
References Info.
Referenced by CreateTabBody().
GetTabIcon()
template<typename BaseClass> virtual const FSlateBrush * FDocumentTabFactoryForObjects< BaseClass >::GetTabIcon (const FWorkflowTabSpawnInfo & Info) const inline override virtual
Reimplemented from FWorkflowTabFactory.
Definition at line 90 of file WorkflowUObjectDocuments.h.
References FTabPayload_UObject::CastChecked(), GetTabIconForObject(), and Info.
GetTabIconForObject()
template<typename BaseClass> virtual const FSlateBrush * FDocumentTabFactoryForObjects< BaseClass >::GetTabIconForObject (const FWorkflowTabSpawnInfo & Info, BaseClass * DocumentID) const protected pure virtual
Implemented in FRigVMGraphEditorSummoner.
References Info.
Referenced by GetTabIcon().
IsPayloadSupported()
template<typename BaseClass> virtual bool FDocumentTabFactoryForObjects< BaseClass >::IsPayloadSupported (TSharedRef< FTabPayload > Payload) const inline override virtual
Reimplemented from FDocumentTabFactory.
Definition at line 96 of file WorkflowUObjectDocuments.h.
References FTabPayload_UObject::CastChecked(), TSharedRef< ObjectType, InMode >::IsValid(), and SupportsObjectType().
IsPayloadValid()
template<typename BaseClass> virtual bool FDocumentTabFactoryForObjects< BaseClass >::IsPayloadValid (TSharedRef< FTabPayload > Payload) const inline override virtual
Returns TRUE if the payload is valid.
Reimplemented from FWorkflowTabFactory.
Definition at line 106 of file WorkflowUObjectDocuments.h.
References TSharedRef< ObjectType, InMode >::IsValid().
SupportsObjectType()
template<typename BaseClass> virtual bool FDocumentTabFactoryForObjects< BaseClass >::SupportsObjectType (UObject * DocumentID) const inline virtual
Definition at line 77 of file WorkflowUObjectDocuments.h.
References UObjectBaseUtility::IsA().
Referenced by IsPayloadSupported().
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/WorkflowOrientedApp/WorkflowUObjectDocuments.h