Unreal Engine 5.6 C++ API: FPrimaryAssetId Struct Reference
FPrimaryAssetId Struct Reference
This identifies an object as a "primary" asset that can be searched for by the AssetManager and used in various tools.
#include "PrimaryAssetId.h"
Public Member Functions
FPrimaryAssetId ()=default
FPrimaryAssetId (const FPrimaryAssetId &)=default
FPrimaryAssetId (const FString &TypeAndName)
FPrimaryAssetId (FPrimaryAssetId &&)=default
FPrimaryAssetId (FPrimaryAssetType InAssetType, FName InAssetName)
void AppendString (FStringBuilderBase &Builder) const
Appends to the given builder the string version of this identifier in Type:Name format.
bool ExportTextItem (FString &ValueStr, FPrimaryAssetId const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
UStruct Overrides.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText)
bool IsValid () const
Returns true if this is a valid identifier.
bool operator!= (const FPrimaryAssetId &Other) const
FPrimaryAssetId & operator= (const FPrimaryAssetId &)=default
FPrimaryAssetId & operator= (FPrimaryAssetId &&)=default
bool operator== (const FPrimaryAssetId &Other) const
bool SerializeFromMismatchedTag (struct FPropertyTag const &Tag, FStructuredArchive::FSlot Slot)
FString ToString () const
Returns string version of this identifier in Type:Name format.
Static Public Member Functions
static FPrimaryAssetId FromString (const FString &String)
Converts from Type:Name format.
static FPrimaryAssetId ParseTypeAndName (const FString &TypeAndName)
static FPrimaryAssetId ParseTypeAndName (const TCHAR *TypeAndName, uint32 Len)
static FPrimaryAssetId ParseTypeAndName (FName TypeAndName)
Data Fields
FName PrimaryAssetName
An FName describing this asset.
FPrimaryAssetType PrimaryAssetType
An FName describing the logical type of this object, usually the name of a base UClass.
Static Public Attributes
static const FName PrimaryAssetDisplayNameTag
AssetRegistry tag used to store primary asset display name (optional)
static const FName PrimaryAssetNameTag
static const FName PrimaryAssetTypeTag
Static names to represent the AssetRegistry tags for the above data.
Private Member Functions
void SerializeForLog (FCbWriter &Writer, const FPrimaryAssetId &Value)
Friends
uint32 GetTypeHash (const FPrimaryAssetId &Key)
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, FPrimaryAssetId &Other)
struct Z_Construct_UScriptStruct_FPrimaryAssetId_Statics
Detailed Description
This identifies an object as a "primary" asset that can be searched for by the AssetManager and used in various tools.
Definition at line 105 of file PrimaryAssetId.h.
Constructor & Destructor Documentation
FPrimaryAssetId() [1/5]
FPrimaryAssetId::FPrimaryAssetId () default
Referenced by FPrimaryAssetId(), FPrimaryAssetId(), FPrimaryAssetId(), ExportTextItem(), FromString(), GetTypeHash, operator!=(), operator<<, operator=(), operator=(), operator==(), ParseTypeAndName(), ParseTypeAndName(), ParseTypeAndName(), and SerializeForLog().
FPrimaryAssetId() [2/5]
FPrimaryAssetId::FPrimaryAssetId (FPrimaryAssetType InAssetType, FName InAssetName) inline
Definition at line 121 of file PrimaryAssetId.h.
References PrimaryAssetName, and PrimaryAssetType.
FPrimaryAssetId() [3/5]
FPrimaryAssetId::FPrimaryAssetId (const FString & TypeAndName) inline explicit
Definition at line 132 of file PrimaryAssetId.h.
References FPrimaryAssetId(), and ParseTypeAndName().
FPrimaryAssetId() [4/5]
FPrimaryAssetId::FPrimaryAssetId (const FPrimaryAssetId &) default
References FPrimaryAssetId().
FPrimaryAssetId() [5/5]
FPrimaryAssetId::FPrimaryAssetId (FPrimaryAssetId &&) default
References FPrimaryAssetId().
Member Function Documentation
AppendString()
void FPrimaryAssetId::AppendString (FStringBuilderBase & Builder) const inline
Appends to the given builder the string version of this identifier in Type:Name format.
Definition at line 156 of file PrimaryAssetId.h.
References IsValid(), PrimaryAssetName, PrimaryAssetType, and TEXT.
Referenced by FAssetIdentifier::AppendString(), and ToString().
ExportTextItem()
bool FPrimaryAssetId::ExportTextItem (FString & ValueStr, FPrimaryAssetId const & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
UStruct Overrides.
References FPrimaryAssetId(), and Parent.
FromString()
FPrimaryAssetId FPrimaryAssetId::FromString (const FString & String) inline static
Converts from Type:Name format.
Definition at line 167 of file PrimaryAssetId.h.
References FPrimaryAssetId(), and String.
Referenced by FAssetIdentifier::FromString().
ImportTextItem()
bool FPrimaryAssetId::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText)
References Buffer, and Parent.
IsValid()
bool FPrimaryAssetId::IsValid () const inline
Returns true if this is a valid identifier.
Definition at line 142 of file PrimaryAssetId.h.
References PrimaryAssetName, and PrimaryAssetType.
Referenced by AppendString(), FAssetIdentifier::FromString(), and FAssetIdentifier::IsValid().
operator!=()
bool FPrimaryAssetId::operator!= (const FPrimaryAssetId & Other) const inline
Definition at line 177 of file PrimaryAssetId.h.
References FPrimaryAssetId(), Other, PrimaryAssetName, and PrimaryAssetType.
operator=() [1/2]
FPrimaryAssetId & FPrimaryAssetId::operator= (const FPrimaryAssetId &) default
References FPrimaryAssetId().
operator=() [2/2]
FPrimaryAssetId & FPrimaryAssetId::operator= (FPrimaryAssetId &&) default
References FPrimaryAssetId().
operator==()
bool FPrimaryAssetId::operator== (const FPrimaryAssetId & Other) const inline
Definition at line 172 of file PrimaryAssetId.h.
References FPrimaryAssetId(), Other, PrimaryAssetName, and PrimaryAssetType.
ParseTypeAndName() [1/3]
FPrimaryAssetId FPrimaryAssetId::ParseTypeAndName (const FString & TypeAndName) inline static
Definition at line 127 of file PrimaryAssetId.h.
References FPrimaryAssetId(), and ParseTypeAndName().
ParseTypeAndName() [2/3]
FPrimaryAssetId FPrimaryAssetId::ParseTypeAndName (const TCHAR * TypeAndName, uint32 Len) static
References FPrimaryAssetId().
Referenced by FPrimaryAssetId(), and ParseTypeAndName().
ParseTypeAndName() [3/3]
FPrimaryAssetId FPrimaryAssetId::ParseTypeAndName (FName TypeAndName) static
References FPrimaryAssetId().
SerializeForLog()
void FPrimaryAssetId::SerializeForLog (FCbWriter & Writer, const FPrimaryAssetId & Value) private
References FPrimaryAssetId(), and Value.
SerializeFromMismatchedTag()
bool FPrimaryAssetId::SerializeFromMismatchedTag (struct FPropertyTag const & Tag, FStructuredArchive::FSlot Slot)
ToString()
FString FPrimaryAssetId::ToString () const inline
Returns string version of this identifier in Type:Name format.
Definition at line 148 of file PrimaryAssetId.h.
References AppendString(), TStringBuilderBase< CharType >::GetData(), and TStringBuilderBase< CharType >::Len().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPrimaryAssetId & Key) friend
Definition at line 194 of file PrimaryAssetId.h.
References FPrimaryAssetId(), GetTypeHash, Hash, HashCombine(), and Key.
Referenced by GetTypeHash.
operator<<
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, FPrimaryAssetId & Other) friend
Definition at line 182 of file PrimaryAssetId.h.
References FPrimaryAssetId(), Ar, FORCEINLINE, and Other.
Z_Construct_UScriptStruct_FPrimaryAssetId_Statics
friend struct Z_Construct_UScriptStruct_FPrimaryAssetId_Statics friend
Definition at line 203 of file PrimaryAssetId.h.
References Z_Construct_UScriptStruct_FPrimaryAssetId_Statics.
Referenced by Z_Construct_UScriptStruct_FPrimaryAssetId_Statics.
Field Documentation
PrimaryAssetDisplayNameTag
const FName FPrimaryAssetId::PrimaryAssetDisplayNameTag static
AssetRegistry tag used to store primary asset display name (optional)
Definition at line 118 of file PrimaryAssetId.h.
PrimaryAssetName
FName FPrimaryAssetId::PrimaryAssetName
An FName describing this asset.
This is usually the short name of the object, but could be a full asset path for things like maps, or objects with GetPrimaryId() overridden. "PrimaryAssetType:PrimaryAssetName" should form a unique name across your project.
Definition at line 112 of file PrimaryAssetId.h.
Referenced by FPrimaryAssetId(), AppendString(), IsValid(), operator!=(), and operator==().
PrimaryAssetNameTag
const FName FPrimaryAssetId::PrimaryAssetNameTag static
Definition at line 116 of file PrimaryAssetId.h.
PrimaryAssetType
FPrimaryAssetType FPrimaryAssetId::PrimaryAssetType
An FName describing the logical type of this object, usually the name of a base UClass.
For example, any Blueprint derived from APawn will have a Primary Asset Type of "Pawn". "PrimaryAssetType:PrimaryAssetName" should form a unique name across your project.
Definition at line 109 of file PrimaryAssetId.h.
Referenced by FPrimaryAssetId(), AppendString(), IsValid(), operator!=(), and operator==().
PrimaryAssetTypeTag
const FName FPrimaryAssetId::PrimaryAssetTypeTag static
Static names to represent the AssetRegistry tags for the above data.
Definition at line 115 of file PrimaryAssetId.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PrimaryAssetId.h