Unreal Engine 5.6 C++ API: UE::MovieScene::FPreAnimatedStorageID Struct Reference
UE::MovieScene::FPreAnimatedStorageID Struct Reference
#include "MovieScenePreAnimatedStorageID.h"
Public Member Functions
FPreAnimatedStorageID ()=default
operator bool () const
Private Member Functions
FPreAnimatedStorageID (uint32 InTypeID)
Private Attributes
uint32 TypeID = ~0u
Friends
struct FPreAnimatedStateExtension
uint32 GetTypeHash (FPreAnimatedStorageID In)
bool operator< (FPreAnimatedStorageID A, FPreAnimatedStorageID B)
bool operator== (FPreAnimatedStorageID A, FPreAnimatedStorageID B)
Detailed Description
Definition at line 13 of file MovieScenePreAnimatedStorageID.h.
Constructor & Destructor Documentation
FPreAnimatedStorageID() [1/2]
UE::MovieScene::FPreAnimatedStorageID::FPreAnimatedStorageID () default
Referenced by GetTypeHash, operator<, and operator==.
FPreAnimatedStorageID() [2/2]
UE::MovieScene::FPreAnimatedStorageID::FPreAnimatedStorageID (uint32 InTypeID) inline explicit private
Definition at line 42 of file MovieScenePreAnimatedStorageID.h.
References TypeID.
Member Function Documentation
operator bool()
UE::MovieScene::FPreAnimatedStorageID::operator bool () const inline explicit
Definition at line 19 of file MovieScenePreAnimatedStorageID.h.
References TypeID.
Friends And Related Symbol Documentation
FPreAnimatedStateExtension
friend struct FPreAnimatedStateExtension friend
Definition at line 40 of file MovieScenePreAnimatedStorageID.h.
References FPreAnimatedStateExtension.
Referenced by FPreAnimatedStateExtension.
GetTypeHash
uint32 GetTypeHash (FPreAnimatedStorageID In) friend
Definition at line 24 of file MovieScenePreAnimatedStorageID.h.
References FPreAnimatedStorageID(), and TypeID.
operator<
bool operator< (FPreAnimatedStorageID A, FPreAnimatedStorageID B) friend
Definition at line 29 of file MovieScenePreAnimatedStorageID.h.
References FPreAnimatedStorageID(), A, and B.
operator==
bool operator== (FPreAnimatedStorageID A, FPreAnimatedStorageID B) friend
Definition at line 34 of file MovieScenePreAnimatedStorageID.h.
References FPreAnimatedStorageID(), A, and B.
Field Documentation
TypeID
uint32 UE::MovieScene::FPreAnimatedStorageID::TypeID = ~0u private
Definition at line 46 of file MovieScenePreAnimatedStorageID.h.
Referenced by FPreAnimatedStorageID(), GetTypeHash, and operator bool().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/PreAnimatedState/MovieScenePreAnimatedStorageID.h