Unreal Engine 5.6 C++ API: FMovieSceneBlendTypeFieldIterator Struct Reference
FMovieSceneBlendTypeFieldIterator Struct Reference
#include "MovieSceneBlendType.h"
Public Member Functions
FORCEINLINE operator bool () const
FORCEINLINE bool operator! () const
FORCEINLINE bool operator!= (const FMovieSceneBlendTypeFieldIterator &RHS) const
MOVIESCENE_API EMovieSceneBlendType operator* ()
FORCEINLINE void operator++ ()
FORCEINLINE bool operator== (const FMovieSceneBlendTypeFieldIterator &RHS) const
Static Public Member Functions
static FMovieSceneBlendTypeFieldIterator Begin (FMovieSceneBlendTypeField InField)
static FMovieSceneBlendTypeFieldIterator End (FMovieSceneBlendTypeField InField)
Private Member Functions
MOVIESCENE_API void IterateToNext ()
Static Private Member Functions
static FORCEINLINE int8 MaxValidOffset ()
Private Attributes
FMovieSceneBlendTypeField Field
int8 Offset
Friends
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator begin (const FMovieSceneBlendTypeField &Field)
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator end (const FMovieSceneBlendTypeField &Field)
Detailed Description
Definition at line 160 of file MovieSceneBlendType.h.
Member Function Documentation
Begin()
FMovieSceneBlendTypeFieldIterator FMovieSceneBlendTypeFieldIterator::Begin (FMovieSceneBlendTypeField InField) static
End()
FMovieSceneBlendTypeFieldIterator FMovieSceneBlendTypeFieldIterator::End (FMovieSceneBlendTypeField InField) static
IterateToNext()
MOVIESCENE_API void FMovieSceneBlendTypeFieldIterator::IterateToNext () private
Referenced by operator++().
MaxValidOffset()
FORCEINLINE int8 FMovieSceneBlendTypeFieldIterator::MaxValidOffset () inline static private
Definition at line 180 of file MovieSceneBlendType.h.
References FORCEINLINE, and StaticEnum().
Referenced by operator bool(), and operator!().
operator bool()
FORCEINLINE FMovieSceneBlendTypeFieldIterator::operator bool () const inline explicit
Definition at line 166 of file MovieSceneBlendType.h.
References FORCEINLINE, MaxValidOffset(), and Offset.
operator!()
FORCEINLINE bool FMovieSceneBlendTypeFieldIterator::operator! () const inline
Definition at line 167 of file MovieSceneBlendType.h.
References FORCEINLINE, MaxValidOffset(), and Offset.
operator!=()
FORCEINLINE bool FMovieSceneBlendTypeFieldIterator::operator!= (const FMovieSceneBlendTypeFieldIterator & RHS) const inline
Definition at line 170 of file MovieSceneBlendType.h.
References Field, FORCEINLINE, and Offset.
operator*()
MOVIESCENE_API EMovieSceneBlendType FMovieSceneBlendTypeFieldIterator::operator* ()
operator++()
FORCEINLINE void FMovieSceneBlendTypeFieldIterator::operator++ () inline
Definition at line 168 of file MovieSceneBlendType.h.
References FORCEINLINE, and IterateToNext().
operator==()
FORCEINLINE bool FMovieSceneBlendTypeFieldIterator::operator== (const FMovieSceneBlendTypeFieldIterator & RHS) const inline
Definition at line 169 of file MovieSceneBlendType.h.
References Field, FORCEINLINE, and Offset.
Friends And Related Symbol Documentation
begin
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator begin (const FMovieSceneBlendTypeField & Field) friend
Referenced by USTRUCT(), USTRUCT(), and USTRUCT().
end
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator end (const FMovieSceneBlendTypeField & Field) friend
Referenced by USTRUCT(), USTRUCT(), and USTRUCT().
Field Documentation
Field
FMovieSceneBlendTypeField FMovieSceneBlendTypeFieldIterator::Field private
Definition at line 182 of file MovieSceneBlendType.h.
Referenced by operator!=(), and operator==().
Offset
int8 FMovieSceneBlendTypeFieldIterator::Offset private
Definition at line 183 of file MovieSceneBlendType.h.
Referenced by operator bool(), operator!(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/Blending/MovieSceneBlendType.h