Unreal Engine 5.6 C++ API: TDirectoryTree< ValueType >::FTreeNode Struct Reference
TDirectoryTree< ValueType >::FTreeNode Struct Reference
A tree structure; each node has a sorted array of child paths and a matching array of child nodes.
Public Member Functions
FTreeNode ()=default
FTreeNode (const FTreeNode &Other)
FTreeNode (FTreeNode &&Other)
bool ContainsChildPaths (FStringView InRelPath) const
Recursively search this node's subtree for the given relative path, then return whether that path has any children.
ValueType * Find (FStringView InRelPath)
Return pointer to the Value stored in RelPath, if RelPath exists in the tree.
ValueType & FindOrAdd (FStringView InRelPath, bool &bOutExisted)
Recursively search the node's subtree to find the given relative directory name, adding nodes for the path and its parents if required.
void FixupDirectChildrenPathSeparator (TCHAR OldSeparator, TCHAR NewSeparator)
SIZE_T GetAllocatedSize () const
How much memory is used by *this, not counting sizeof(*this).
int32 GetNumChildNodes () const
ValueType & GetValue ()
Get a reference to the node's Value.
const ValueType & GetValue () const
Get a reference to the node's Value.
bool HasValue () const
Report whether the node has a value, which is equivalent to the node's path existing in the DirectoryTree.
bool IsEmpty () const
Are no paths contained within the node.
FTreeNode & operator= (const FTreeNode &Other)
FTreeNode & operator= (FTreeNode &&Other)
void Remove (FStringView InRelPath, bool &bOutExisted)
Remove the Value if it exists in the tree.
void RemoveValue ()
Set HasValue=false, and destruct any existing old value.
void Reset ()
Remove Value and ChildNodes, return state to default-constructed state.
void SetDefaultValue ()
Set HasValue=true, and default-construct the node's value, after destructing any existing old value.
void SetValue (ValueType &&InValue)
Set HasValue=true, and move InValue into the node's value, after destructing any existing old value.
void Shrink ()
Reduce memory used in buffers.
ValueType * TryFindClosestPath (FStringView RelPath, FStringBuilderBase *OutPath, TCHAR SeparatorChar)
Recursively search the node's subtree to find the given RelPath.
bool TryGetChildren (FStringBuilderBase &ReportedPathPrefix, TCHAR InPathSeparator, FStringView InRelPath, TArray< FString > &OutRelativeChildNames, EDirectoryTreeGetFlags Flags) const
Private Member Functions
int32 FindInsertionIndex (FStringView FirstPathComponent, bool &bOutExists) const
Search the sorted ChildNode RelPaths for the given FirstPathComponent, which must be only a single path component, and return the index either of the existing path or where the path should be inserted if new.
FTreeNode & InsertChildNode (int32 InsertionIndex, FString &&RelPath, FTreeNode &&ChildNode)
Insert the given RelPath and ChildNode at the given index; must be the index from FindInsertionIndex.
void Realloc (int32 NewCapacity)
Reallocate the NumChildNodes arrays to match the given new capacity.
void RemoveChildNodeAt (int32 RemoveIndex)
Remove the RelPath and ChildNode from the given index.
void SetNumChildNodes (int32 InNumChildNodes)
Static Private Member Functions
static void ConditionalCompactNode (FString &RelPath, FTreeNode &ChildNode)
Merge the node with its direct child if possible, and if so adjust the input RelPath to match.
Private Attributes
int32 CapacityChildNodes = 0
TUniquePtr< FTreeNode[]> ChildNodes
uint32 NumChildNodesAndFlags = 0
TUniquePtr< FString[]> RelPaths
TTypeCompatibleBytes< ValueType > Value
Static Private Attributes
static constexpr uint32 FlagsMask = 0x1u << FlagsShift
static constexpr uint32 FlagsShift = (8u * sizeof(uint32) - NumFlagBits)
static constexpr uint32 NumFlagBits = 1u
Friends
struct FIteratorInternal
Detailed Description
template<typename ValueType>
struct TDirectoryTree< ValueType >::FTreeNode
A tree structure; each node has a sorted array of child paths and a matching array of child nodes.
Child paths are relative paths and are organized by the FirstComponent of their relative path. If there is only a single child path with a given FirstComponent, the entire relative path to that child is listed as the relative path. If there are two or more paths with the same first component, a new child node is created for the first component, and the paths are then children of that component. Example: Root / (FullPath: /) A (FullPath: /A X (FullPath: /A/X Y/M (FullPath: /A/Y/M) B/Z (FullPath: /B/Z) N (FullPath: /B/Z/N) O (FullPath: /B/Z/O) C/W/P (FullPath: /C/W/P)
Definition at line 274 of file DirectoryTree.h.
Constructor & Destructor Documentation
FTreeNode() [1/3]
template<typename ValueType> TDirectoryTree< ValueType >::FTreeNode::FTreeNode () default
References FTreeNode(), and Other.
Referenced by FTreeNode(), FTreeNode(), FTreeNode(), ConditionalCompactNode(), ContainsChildPaths(), Find(), FindOrAdd(), GetAllocatedSize(), InsertChildNode(), operator=(), operator=(), Realloc(), Remove(), Shrink(), TryFindClosestPath(), and TryGetChildren().
FTreeNode() [2/3]
template<typename ValueType> TDirectoryTree< ValueType >::FTreeNode::FTreeNode (FTreeNode && Other)
Definition at line 799 of file DirectoryTree.h.
References FTreeNode(), MoveTemp(), and Other.
FTreeNode() [3/3]
template<typename ValueType> TDirectoryTree< ValueType >::FTreeNode::FTreeNode (const FTreeNode & Other)
Definition at line 768 of file DirectoryTree.h.
References FTreeNode(), and Other.
Member Function Documentation
ConditionalCompactNode()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::ConditionalCompactNode (FString & RelPath, FTreeNode & ChildNode) static private
Merge the node with its direct child if possible, and if so adjust the input RelPath to match.
Definition at line 1577 of file DirectoryTree.h.
References FTreeNode(), FPathViews::AppendPath(), checkf, ChildNodes, GetNumChildNodes(), HasValue(), MoveTemp(), RelPaths, and TEXT.
Referenced by Remove().
ContainsChildPaths()
template<typename ValueType> bool TDirectoryTree< ValueType >::FTreeNode::ContainsChildPaths (FStringView InRelPath) const
Recursively search this node's subtree for the given relative path, then return whether that path has any children.
Returns false if the given relative path doesn't exist in the tree or if it is an explicit path with no children. Returns true if the given path is implicit (there is a node representing a sub-path of it) or if it is an explicit path with direct or indirect children.
Definition at line 1118 of file DirectoryTree.h.
References FTreeNode(), check, checkf, ChildNodes, ContainsChildPaths(), FPathViews::Equals(), FindInsertionIndex(), TStringView< CharType >::GetData(), GetNumChildNodes(), TStringView< CharType >::IsEmpty(), TStringView< CharType >::Len(), RelPaths, FPathViews::SplitFirstComponent(), and TEXT.
Referenced by ContainsChildPaths().
Find()
template<typename ValueType> ValueType * TDirectoryTree< ValueType >::FTreeNode::Find (FStringView InRelPath)
Return pointer to the Value stored in RelPath, if RelPath exists in the tree.
Definition at line 1083 of file DirectoryTree.h.
References FTreeNode(), check, ChildNodes, Find(), FindInsertionIndex(), GetValue(), HasValue(), TStringView< CharType >::IsEmpty(), RelPaths, FPathViews::SplitFirstComponent(), and FPathViews::TryMakeChildPathRelativeTo().
Referenced by Find().
FindInsertionIndex()
template<typename ValueType> int32 TDirectoryTree< ValueType >::FTreeNode::FindInsertionIndex (FStringView FirstPathComponent, bool & bOutExists) const inline private
Search the sorted ChildNode RelPaths for the given FirstPathComponent, which must be only a single path component, and return the index either of the existing path or where the path should be inserted if new.
Also report whether it exists.
Definition at line 1517 of file DirectoryTree.h.
References UE::DirectoryTree::FindInsertionIndex(), GetNumChildNodes(), and RelPaths.
Referenced by ContainsChildPaths(), Find(), FindOrAdd(), Remove(), TryFindClosestPath(), and TryGetChildren().
FindOrAdd()
template<typename ValueType> ValueType & TDirectoryTree< ValueType >::FTreeNode::FindOrAdd (FStringView InRelPath, bool & bOutExisted)
Recursively search the node's subtree to find the given relative directory name, adding nodes for the path and its parents if required.
Return reference to the added or existing node's value.
Definition at line 910 of file DirectoryTree.h.
References FTreeNode(), FPathViews::Append(), check, checkf, ChildNodes, TStringView< CharType >::Equals(), FindInsertionIndex(), FindOrAdd(), TStringView< CharType >::GetData(), GetValue(), HasValue(), ESearchCase::IgnoreCase, InsertChildNode(), TStringView< CharType >::IsEmpty(), TStringView< CharType >::Len(), MoveTemp(), RelPaths, Reset(), SetDefaultValue(), FPathViews::SplitFirstComponent(), and TEXT.
Referenced by FindOrAdd().
FixupDirectChildrenPathSeparator()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::FixupDirectChildrenPathSeparator (TCHAR OldSeparator, TCHAR NewSeparator) inline
Definition at line 1630 of file DirectoryTree.h.
References GetNumChildNodes(), TDirectoryTree< ValueType >::Num(), and RelPaths.
GetAllocatedSize()
template<typename ValueType> SIZE_T TDirectoryTree< ValueType >::FTreeNode::GetAllocatedSize () const inline
How much memory is used by *this, not counting sizeof(*this).
Definition at line 1484 of file DirectoryTree.h.
References FTreeNode(), CapacityChildNodes, ChildNodes, GetNumChildNodes(), RelPaths, and TSequenceHistory< HistorySize >::Size.
GetNumChildNodes()
template<typename ValueType> int32 TDirectoryTree< ValueType >::FTreeNode::GetNumChildNodes () const inline
Definition at line 837 of file DirectoryTree.h.
References FlagsMask, and NumChildNodesAndFlags.
Referenced by ConditionalCompactNode(), ContainsChildPaths(), FindInsertionIndex(), FixupDirectChildrenPathSeparator(), GetAllocatedSize(), InsertChildNode(), IsEmpty(), TDirectoryTree< ValueType >::FIteratorInternal::operator++(), Realloc(), Remove(), RemoveChildNodeAt(), Shrink(), TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid(), and TryGetChildren().
GetValue() [1/2]
template<typename ValueType> ValueType & TDirectoryTree< ValueType >::FTreeNode::GetValue () inline
Get a reference to the node's Value.
Invalid to call if !HasValue.
Definition at line 858 of file DirectoryTree.h.
References Value.
Referenced by Find(), FindOrAdd(), and TryFindClosestPath().
GetValue() [2/2]
template<typename ValueType> const ValueType & TDirectoryTree< ValueType >::FTreeNode::GetValue () const inline
Get a reference to the node's Value.
Invalid to call if !HasValue.
Definition at line 864 of file DirectoryTree.h.
References Value.
HasValue()
template<typename ValueType> bool TDirectoryTree< ValueType >::FTreeNode::HasValue () const inline
Report whether the node has a value, which is equivalent to the node's path existing in the DirectoryTree.
Nodes might exist in the tree without their path existing, if they are parent paths that have not been added.
Definition at line 852 of file DirectoryTree.h.
References FlagsMask, and NumChildNodesAndFlags.
Referenced by TDirectoryTree< ValueType >::FIteratorInternal::FIteratorInternal(), ConditionalCompactNode(), Find(), FindOrAdd(), IsEmpty(), Remove(), RemoveValue(), TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid(), TryFindClosestPath(), and TryGetChildren().
InsertChildNode()
template<typename ValueType> TDirectoryTree< ValueType >::FTreeNode & TDirectoryTree< ValueType >::FTreeNode::InsertChildNode (int32 InsertionIndex, FString && RelPath, FTreeNode && ChildNode) private
Insert the given RelPath and ChildNode at the given index; must be the index from FindInsertionIndex.
Definition at line 1523 of file DirectoryTree.h.
References FTreeNode(), CapacityChildNodes, check, checkf, ChildNodes, FlagsMask, GetNumChildNodes(), MoveTemp(), Realloc(), RelPaths, SetNumChildNodes(), and TEXT.
Referenced by FindOrAdd().
IsEmpty()
template<typename ValueType> bool TDirectoryTree< ValueType >::FTreeNode::IsEmpty () const inline
Are no paths contained within the node.
Definition at line 1478 of file DirectoryTree.h.
References GetNumChildNodes(), and HasValue().
operator=() [1/2]
template<typename ValueType> TDirectoryTree< ValueType >::FTreeNode & TDirectoryTree< ValueType >::FTreeNode::operator= (const FTreeNode & Other)
Definition at line 774 of file DirectoryTree.h.
References FTreeNode(), ChildNodes, CopyTemp(), Other, Realloc(), RelPaths, Reset, SetNumChildNodes(), and SetValue().
operator=() [2/2]
template<typename ValueType> TDirectoryTree< ValueType >::FTreeNode & TDirectoryTree< ValueType >::FTreeNode::operator= (FTreeNode && Other)
Definition at line 805 of file DirectoryTree.h.
References FTreeNode(), CapacityChildNodes, ChildNodes, MoveTemp(), Other, RelPaths, RemoveValue(), SetNumChildNodes(), and SetValue().
Realloc()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::Realloc (int32 NewCapacity) private
Reallocate the NumChildNodes arrays to match the given new capacity.
Definition at line 1599 of file DirectoryTree.h.
References FTreeNode(), CA_ASSUME, CapacityChildNodes, check, ChildNodes, GetNumChildNodes(), MoveTemp(), and RelPaths.
Referenced by InsertChildNode(), operator=(), and Shrink().
Remove()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::Remove (FStringView InRelPath, bool & bOutExisted)
Remove the Value if it exists in the tree.
Definition at line 1027 of file DirectoryTree.h.
References FTreeNode(), check, ChildNodes, ConditionalCompactNode(), FindInsertionIndex(), GetNumChildNodes(), HasValue(), TStringView< CharType >::IsEmpty(), RelPaths, Remove(), RemoveChildNodeAt(), RemoveValue(), FPathViews::SplitFirstComponent(), and FPathViews::TryMakeChildPathRelativeTo().
Referenced by Remove().
RemoveChildNodeAt()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::RemoveChildNodeAt (int32 RemoveIndex) private
Remove the RelPath and ChildNode from the given index.
Definition at line 1562 of file DirectoryTree.h.
References check, ChildNodes, GetNumChildNodes(), MoveTemp(), RelPaths, and SetNumChildNodes().
Referenced by Remove().
RemoveValue()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::RemoveValue () inline
Set HasValue=false, and destruct any existing old value.
Definition at line 894 of file DirectoryTree.h.
References FlagsMask, FlagsShift, HasValue(), NumChildNodesAndFlags, and Value.
Referenced by operator=(), Remove(), Reset(), SetDefaultValue(), and SetValue().
Reset()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::Reset ()
Remove Value and ChildNodes, return state to default-constructed state.
Definition at line 827 of file DirectoryTree.h.
References CapacityChildNodes, ChildNodes, NumChildNodesAndFlags, RelPaths, and RemoveValue().
Referenced by FindOrAdd().
SetDefaultValue()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::SetDefaultValue () inline
Set HasValue=true, and default-construct the node's value, after destructing any existing old value.
Definition at line 882 of file DirectoryTree.h.
References FlagsMask, FlagsShift, NumChildNodesAndFlags, RemoveValue(), and Value.
Referenced by FindOrAdd().
SetNumChildNodes()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::SetNumChildNodes (int32 InNumChildNodes) inline private
Definition at line 843 of file DirectoryTree.h.
References check, FlagsMask, and NumChildNodesAndFlags.
Referenced by InsertChildNode(), operator=(), operator=(), and RemoveChildNodeAt().
SetValue()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::SetValue (ValueType && InValue) inline
Set HasValue=true, and move InValue into the node's value, after destructing any existing old value.
Definition at line 870 of file DirectoryTree.h.
References FlagsMask, FlagsShift, MoveTemp(), NumChildNodesAndFlags, RemoveValue(), and Value.
Referenced by operator=(), and operator=().
Shrink()
template<typename ValueType> void TDirectoryTree< ValueType >::FTreeNode::Shrink () inline
Reduce memory used in buffers.
Definition at line 1501 of file DirectoryTree.h.
References FTreeNode(), ChildNodes, GetNumChildNodes(), Realloc(), and RelPaths.
TryFindClosestPath()
template<typename ValueType> ValueType * TDirectoryTree< ValueType >::FTreeNode::TryFindClosestPath (FStringView RelPath, FStringBuilderBase * OutPath, TCHAR SeparatorChar)
Recursively search the node's subtree to find the given RelPath.
Return whether the path or any parent is found, and if any is found and Outpath is present, append relative path of the discovered path into OutPath.
Definition at line 1411 of file DirectoryTree.h.
References FTreeNode(), FPathViews::Append(), check, ChildNodes, FindInsertionIndex(), UE::DirectoryTree::FixupPathSeparator(), GetValue(), HasValue(), INDEX_NONE, TStringView< CharType >::IsEmpty(), TStringBuilderBase< CharType >::Len(), RelPaths, TStringBuilderBase< CharType >::RemoveSuffix(), FPathViews::SplitFirstComponent(), TryFindClosestPath(), and FPathViews::TryMakeChildPathRelativeTo().
Referenced by TryFindClosestPath().
TryGetChildren()
template<typename ValueType> bool TDirectoryTree< ValueType >::FTreeNode::TryGetChildren (FStringBuilderBase & ReportedPathPrefix, TCHAR InPathSeparator, FStringView InRelPath, TArray< FString > & OutRelativeChildNames, EDirectoryTreeGetFlags Flags) const
Definition at line 1197 of file DirectoryTree.h.
References FTreeNode(), TArray< InElementType, InAllocatorType >::Add(), FPathViews::Append(), check, checkf, ChildNodes, EnumHasAnyFlags(), FPathViews::Equals(), FindInsertionIndex(), UE::DirectoryTree::FixupPathSeparator(), Flags, TStringView< CharType >::GetData(), GetNumChildNodes(), HasValue(), ImpliedChildren, ImpliedParent, TStringView< CharType >::IsEmpty(), TStringBuilderBase< CharType >::Len(), TStringView< CharType >::Len(), Recursive, RelPaths, TStringBuilderBase< CharType >::RemoveSuffix(), FPathViews::SplitFirstComponent(), TEXT, and TryGetChildren().
Referenced by TryGetChildren().
Friends And Related Symbol Documentation
FIteratorInternal
template<typename ValueType> friend struct FIteratorInternal friend
Definition at line 365 of file DirectoryTree.h.
References FIteratorInternal.
Referenced by FIteratorInternal.
Field Documentation
CapacityChildNodes
template<typename ValueType> int32 TDirectoryTree< ValueType >::FTreeNode::CapacityChildNodes = 0 private
Definition at line 371 of file DirectoryTree.h.
Referenced by GetAllocatedSize(), InsertChildNode(), operator=(), Realloc(), and Reset().
ChildNodes
template<typename ValueType> TUniquePtr<FTreeNode[]> TDirectoryTree< ValueType >::FTreeNode::ChildNodes private
Definition at line 369 of file DirectoryTree.h.
Referenced by ConditionalCompactNode(), ContainsChildPaths(), Find(), FindOrAdd(), GetAllocatedSize(), InsertChildNode(), operator=(), operator=(), Realloc(), Remove(), RemoveChildNodeAt(), Reset(), Shrink(), TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid(), TryFindClosestPath(), and TryGetChildren().
FlagsMask
template<typename ValueType> uint32 TDirectoryTree< ValueType >::FTreeNode::FlagsMask = 0x1u << FlagsShift static constexpr private
Definition at line 345 of file DirectoryTree.h.
Referenced by GetNumChildNodes(), HasValue(), InsertChildNode(), RemoveValue(), SetDefaultValue(), SetNumChildNodes(), and SetValue().
FlagsShift
template<typename ValueType> uint32 TDirectoryTree< ValueType >::FTreeNode::FlagsShift = (8u * sizeof(uint32) - NumFlagBits) static constexpr private
Definition at line 344 of file DirectoryTree.h.
Referenced by RemoveValue(), SetDefaultValue(), and SetValue().
NumChildNodesAndFlags
template<typename ValueType> uint32 TDirectoryTree< ValueType >::FTreeNode::NumChildNodesAndFlags = 0 private
Definition at line 370 of file DirectoryTree.h.
Referenced by GetNumChildNodes(), HasValue(), RemoveValue(), Reset(), SetDefaultValue(), SetNumChildNodes(), and SetValue().
NumFlagBits
template<typename ValueType> uint32 TDirectoryTree< ValueType >::FTreeNode::NumFlagBits = 1u static constexpr private
Definition at line 343 of file DirectoryTree.h.
RelPaths
template<typename ValueType> TUniquePtr<FString[]> TDirectoryTree< ValueType >::FTreeNode::RelPaths private
Definition at line 368 of file DirectoryTree.h.
Referenced by ConditionalCompactNode(), ContainsChildPaths(), Find(), FindInsertionIndex(), FindOrAdd(), FixupDirectChildrenPathSeparator(), GetAllocatedSize(), InsertChildNode(), operator=(), operator=(), Realloc(), Remove(), RemoveChildNodeAt(), Reset(), Shrink(), TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid(), TryFindClosestPath(), and TryGetChildren().
Value
template<typename ValueType> TTypeCompatibleBytes<ValueType> TDirectoryTree< ValueType >::FTreeNode::Value private
Definition at line 367 of file DirectoryTree.h.
Referenced by GetValue(), GetValue(), RemoveValue(), SetDefaultValue(), and SetValue().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/DirectoryTree.h