Unreal Engine 5.6 C++ API: UE::Core::Private::Function::TFunctionStorage< bUnique > Struct Template Reference
UE::Core::Private::Function::TFunctionStorage< bUnique > Struct Template Reference
#include "Function.h"
Public Member Functions
TFunctionStorage ()=default
TFunctionStorage (FFunctionStorage &&Other)
template<typename FunctorType>
std::decay_t< FunctorType > * Bind (FunctorType &&InFunc)
Public Member Functions inherited from UE::Core::Private::Function::FFunctionStorage
FFunctionStorage ()
FFunctionStorage (const FFunctionStorage &Other)=delete
FFunctionStorage (FFunctionStorage &&Other)
void * BindCopy (const FFunctionStorage &Other)
IFunction_OwnedObject * GetBoundObject () const
void * GetPtr () const
Returns a pointer to the callable object - needed by TFunctionRefBase.
FFunctionStorage & operator= (const FFunctionStorage &Other)=delete
FFunctionStorage & operator= (FFunctionStorage &&Other)=delete
void Unbind ()
Destroy any owned bindings - called by TFunctionRefBase only if Bind() or BindCopy() was called.
Additional Inherited Members
Data Fields inherited from UE::Core::Private::Function::FFunctionStorage
void * HeapAllocation
Static Public Attributes inherited from UE::Core::Private::Function::FFunctionStorage
static constexpr bool bCanBeNull = true
Detailed Description
template<bool bUnique>
struct UE::Core::Private::Function::TFunctionStorage< bUnique >
Definition at line 207 of file Function.h.
Constructor & Destructor Documentation
TFunctionStorage() [1/2]
template<bool bUnique> UE::Core::Private::Function::TFunctionStorage< bUnique >::TFunctionStorage () default
TFunctionStorage() [2/2]
template<bool bUnique> UE::Core::Private::Function::TFunctionStorage< bUnique >::TFunctionStorage (FFunctionStorage && Other) inline
Definition at line 211 of file Function.h.
References UE::Core::Private::Function::FFunctionStorage::FFunctionStorage(), MoveTemp(), and Other.
Member Function Documentation
Bind()
template<bool bUnique> template<typename FunctorType> std::decay_t< FunctorType > * UE::Core::Private::Function::TFunctionStorage< bUnique >::Bind (FunctorType && InFunc) inline
Definition at line 217 of file Function.h.
References CA_ASSUME, Forward(), UE::Core::Private::Function::FFunctionStorage::HeapAllocation, and UE::Core::Private::Function::IsBound().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/Function.h