Unreal Engine 5.6 C++ API: FViewportCameraTransform Struct Reference
FViewportCameraTransform Struct Reference
Stores the transformation data for the viewport camera.
#include "EditorViewportClient.h"
Public Member Functions
UNREALED_API FViewportCameraTransform ()
UNREALED_API FMatrix ComputeOrbitMatrix () const
Computes a matrix to use for viewport location and rotation when orbiting.
FORCEINLINE const FVector & GetLocation () const
FORCEINLINE const FVector & GetLookAt () const
FORCEINLINE float GetOrthoZoom () const
FORCEINLINE const FRotator & GetRotation () const
UNREALED_API bool IsPlaying ()
Check if transition curve is playing.
UNREALED_API void SetLocation (const FVector &Position)
Sets the transform's location.
void SetLookAt (const FVector &InLookAt)
Sets the location to look at during orbit.
void SetMaxLocation (double InMaxLocation)
void SetOrthoZoom (float InOrthoZoom)
Set the ortho zoom amount.
void SetRotation (const FRotator &Rotation)
Sets the transform's rotation.
UNREALED_API void TransitionToLocation (const FVector &InDesiredLocation, TWeakPtr< SWidget > EditorViewportWidget, bool bInstant)
Animates from the current location to the desired location.
UNREALED_API bool UpdateTransition ()
Updates any current location transitions.
Private Attributes
FVector DesiredLocation
Desired viewport location when animating between two locations.
FVector LookAt
When orbiting, the point we are looking at.
double MaxLocation
Location is clamped to a box around the origin with this radius.
float OrthoZoom
Ortho zoom amount.
FVector StartLocation
Viewport start location when animating to another location.
TSharedPtr< struct FCurveSequence > TransitionCurve
The time when a transition to the desired location began.
FVector ViewLocation
Current viewport Position.
FRotator ViewRotation
Current Viewport orientation; valid only for perspective projections.
Detailed Description
Stores the transformation data for the viewport camera.
Definition at line 221 of file EditorViewportClient.h.
Constructor & Destructor Documentation
FViewportCameraTransform()
UNREALED_API FViewportCameraTransform::FViewportCameraTransform ()
Member Function Documentation
ComputeOrbitMatrix()
UNREALED_API FMatrix FViewportCameraTransform::ComputeOrbitMatrix () const
Computes a matrix to use for viewport location and rotation when orbiting.
Referenced by FEditorViewportClient::SetLookAtLocation().
GetLocation()
FORCEINLINE const FVector & FViewportCameraTransform::GetLocation () const inline
Returns
The transform's location
Definition at line 257 of file EditorViewportClient.h.
References FORCEINLINE, FVector, and ViewLocation.
Referenced by FEditorViewportClient::GetViewLocation().
GetLookAt()
FORCEINLINE const FVector & FViewportCameraTransform::GetLookAt () const inline
Returns
The look at point for orbiting
Definition at line 263 of file EditorViewportClient.h.
References FORCEINLINE, FVector, and LookAt.
Referenced by FEditorViewportClient::GetLookAtLocation().
GetOrthoZoom()
FORCEINLINE float FViewportCameraTransform::GetOrthoZoom () const inline
Returns
The ortho zoom amount
Definition at line 266 of file EditorViewportClient.h.
References FORCEINLINE, and OrthoZoom.
Referenced by FEditorViewportClient::GetOrthoZoom().
GetRotation()
FORCEINLINE const FRotator & FViewportCameraTransform::GetRotation () const inline
Returns
The transform's rotation
Definition at line 260 of file EditorViewportClient.h.
References FORCEINLINE, and ViewRotation.
Referenced by FEditorViewportClient::GetViewRotation().
IsPlaying()
UNREALED_API bool FViewportCameraTransform::IsPlaying ()
Check if transition curve is playing.
SetLocation()
UNREALED_API void FViewportCameraTransform::SetLocation (const FVector & Position)
Sets the transform's location.
References FVector, and Position.
Referenced by FEditorViewportClient::SetLookAtLocation(), and FEditorViewportClient::SetViewLocation().
SetLookAt()
void FViewportCameraTransform::SetLookAt (const FVector & InLookAt) inline
Sets the location to look at during orbit.
Definition at line 236 of file EditorViewportClient.h.
References FVector, and LookAt.
Referenced by FEditorViewportClient::SetLookAtLocation().
SetMaxLocation()
void FViewportCameraTransform::SetMaxLocation (double InMaxLocation) inline
Definition at line 248 of file EditorViewportClient.h.
References MaxLocation.
SetOrthoZoom()
void FViewportCameraTransform::SetOrthoZoom (float InOrthoZoom) inline
Set the ortho zoom amount.
Definition at line 242 of file EditorViewportClient.h.
References ensure, MAX_ORTHOZOOM, MIN_ORTHOZOOM, and OrthoZoom.
Referenced by FEditorViewportClient::SetOrthoZoom().
SetRotation()
void FViewportCameraTransform::SetRotation (const FRotator & Rotation) inline
Sets the transform's rotation.
Definition at line 230 of file EditorViewportClient.h.
References Rotation, and ViewRotation.
Referenced by FEditorViewportClient::SetLookAtLocation(), and FEditorViewportClient::SetViewRotation().
TransitionToLocation()
UNREALED_API void FViewportCameraTransform::TransitionToLocation (const FVector & InDesiredLocation, TWeakPtr< SWidget > EditorViewportWidget, bool bInstant)
Animates from the current location to the desired location.
Parameters
InDesiredLocation The location to transition to
bInstant If the desired location should be set instantly rather than transitioned to over time
References FVector.
UpdateTransition()
UNREALED_API bool FViewportCameraTransform::UpdateTransition ()
Updates any current location transitions.
Returns
true if there is currently a transition
Field Documentation
DesiredLocation
FVector FViewportCameraTransform::DesiredLocation private
Desired viewport location when animating between two locations.
Definition at line 299 of file EditorViewportClient.h.
LookAt
FVector FViewportCameraTransform::LookAt private
When orbiting, the point we are looking at.
Definition at line 301 of file EditorViewportClient.h.
Referenced by GetLookAt(), and SetLookAt().
MaxLocation
double FViewportCameraTransform::MaxLocation private
Location is clamped to a box around the origin with this radius.
Definition at line 307 of file EditorViewportClient.h.
Referenced by SetMaxLocation().
OrthoZoom
float FViewportCameraTransform::OrthoZoom private
Ortho zoom amount.
Definition at line 305 of file EditorViewportClient.h.
Referenced by GetOrthoZoom(), and SetOrthoZoom().
StartLocation
FVector FViewportCameraTransform::StartLocation private
Viewport start location when animating to another location.
Definition at line 303 of file EditorViewportClient.h.
TransitionCurve
TSharedPtr<struct FCurveSequence> FViewportCameraTransform::TransitionCurve private
The time when a transition to the desired location began.
Curve for animating between locations
Definition at line 293 of file EditorViewportClient.h.
ViewLocation
FVector FViewportCameraTransform::ViewLocation private
Current viewport Position.
Definition at line 295 of file EditorViewportClient.h.
Referenced by GetLocation().
ViewRotation
FRotator FViewportCameraTransform::ViewRotation private
Current Viewport orientation; valid only for perspective projections.
Definition at line 297 of file EditorViewportClient.h.
Referenced by GetRotation(), and SetRotation().
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/EditorViewportClient.h