Unreal Engine 5.6 C++ API: FNDIGeometryCollectionArrays Struct Reference
FNDIGeometryCollectionArrays Struct Reference
Arrays in which the cpu datas will be str.
#include "NiagaraDataInterfaceGeometryCollection.h"
Public Member Functions
FNDIGeometryCollectionArrays ()
FNDIGeometryCollectionArrays (uint32 Num)
void CopyFrom (const FNDIGeometryCollectionArrays *Other)
void Resize (uint32 Num)
Data Fields
TArray< FVector4f > BoundsBuffer
TArray< FTransform > ComponentRestTransformBuffer
TArray< uint32 > ElementIndexToTransformBufferMapping
uint32 NumPieces = 100
TArray< FVector4f > PrevWorldInverseTransformBuffer
TArray< FVector4f > PrevWorldTransformBuffer
TArray< FVector4f > WorldInverseTransformBuffer
TArray< FVector4f > WorldTransformBuffer
Detailed Description
Arrays in which the cpu datas will be str.
Definition at line 16 of file NiagaraDataInterfaceGeometryCollection.h.
Constructor & Destructor Documentation
FNDIGeometryCollectionArrays() [1/2]
FNDIGeometryCollectionArrays::FNDIGeometryCollectionArrays () inline
Definition at line 26 of file NiagaraDataInterfaceGeometryCollection.h.
References Resize().
Referenced by CopyFrom().
FNDIGeometryCollectionArrays() [2/2]
FNDIGeometryCollectionArrays::FNDIGeometryCollectionArrays (uint32 Num) inline
Definition at line 31 of file NiagaraDataInterfaceGeometryCollection.h.
References Num, and Resize().
Member Function Documentation
CopyFrom()
void FNDIGeometryCollectionArrays::CopyFrom (const FNDIGeometryCollectionArrays * Other) inline
Definition at line 36 of file NiagaraDataInterfaceGeometryCollection.h.
References FNDIGeometryCollectionArrays(), BoundsBuffer, ComponentRestTransformBuffer, ElementIndexToTransformBufferMapping, Other, PrevWorldInverseTransformBuffer, PrevWorldTransformBuffer, Resize(), WorldInverseTransformBuffer, and WorldTransformBuffer.
Resize()
void FNDIGeometryCollectionArrays::Resize (uint32 Num) inline
Definition at line 49 of file NiagaraDataInterfaceGeometryCollection.h.
References BoundsBuffer, ComponentRestTransformBuffer, ElementIndexToTransformBufferMapping, Num, NumPieces, PrevWorldInverseTransformBuffer, PrevWorldTransformBuffer, WorldInverseTransformBuffer, and WorldTransformBuffer.
Referenced by FNDIGeometryCollectionArrays(), FNDIGeometryCollectionArrays(), and CopyFrom().
Field Documentation
BoundsBuffer
TArray<FVector4f> FNDIGeometryCollectionArrays::BoundsBuffer
Definition at line 22 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by CopyFrom(), and Resize().
ComponentRestTransformBuffer
TArray<FTransform> FNDIGeometryCollectionArrays::ComponentRestTransformBuffer
Definition at line 23 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by CopyFrom(), and Resize().
ElementIndexToTransformBufferMapping
TArray<uint32> FNDIGeometryCollectionArrays::ElementIndexToTransformBufferMapping
Definition at line 24 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by CopyFrom(), and Resize().
NumPieces
uint32 FNDIGeometryCollectionArrays::NumPieces = 100
Definition at line 62 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by Resize().
PrevWorldInverseTransformBuffer
TArray<FVector4f> FNDIGeometryCollectionArrays::PrevWorldInverseTransformBuffer
Definition at line 21 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by CopyFrom(), and Resize().
PrevWorldTransformBuffer
TArray<FVector4f> FNDIGeometryCollectionArrays::PrevWorldTransformBuffer
Definition at line 19 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by CopyFrom(), and Resize().
WorldInverseTransformBuffer
TArray<FVector4f> FNDIGeometryCollectionArrays::WorldInverseTransformBuffer
Definition at line 20 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by CopyFrom(), and Resize().
WorldTransformBuffer
TArray<FVector4f> FNDIGeometryCollectionArrays::WorldTransformBuffer
Definition at line 18 of file NiagaraDataInterfaceGeometryCollection.h.
Referenced by CopyFrom(), and Resize().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosNiagara/Source/ChaosNiagara/Public/NiagaraDataInterfaceGeometryCollection.h