Unreal Engine 5.6 C++ API: UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > Struct Template Reference
UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > Struct Template Reference
#include "Tuple.h"
Public Member Functions
TTupleBase ()=default
TTupleBase (const TTupleBase &Other)=default
template<typename... ArgTypes, decltype(ConceptCheckingHelper(TTupleBaseElement< Types, Indices, sizeof...(Types)>(ForwardingConstructor, DeclVal< ArgTypes && >())...)) * = nullptr>
TTupleBase (EForwardingConstructor, ArgTypes &&... Args)
template<typename TupleType, decltype(ConceptCheckingHelper(TTupleBaseElement< Types, Indices, sizeof...(Types)>(ForwardingConstructor, DeclVal< TupleType && >().template Get< Indices >())...)) * = nullptr>
TTupleBase (EOtherTupleConstructor, TupleType &&Other)
TTupleBase (TTupleBase &&Other)=default
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) &&
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) const &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) const &&
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) const volatile &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) const volatile &&
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) volatile &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyAfter (FuncType &&Func, ArgTypes &&... Args) volatile &&
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) &&
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) const &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) const &&
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) const volatile &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) const volatile &&
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) volatile &
template<typename FuncType, typename... ArgTypes>
decltype(auto) ApplyBefore (FuncType &&Func, ArgTypes &&... Args) volatile &&
template<uint32 Index>
FORCEINLINE decltype(auto) Get () &
template<typename T>
FORCEINLINE decltype(auto) Get () &
template<uint32 Index>
FORCEINLINE decltype(auto) Get () &&
template<typename T>
FORCEINLINE decltype(auto) Get () &&
template<uint32 Index>
FORCEINLINE decltype(auto) Get () const &
template<typename T>
FORCEINLINE decltype(auto) Get () const &
template<uint32 Index>
FORCEINLINE decltype(auto) Get () const &&
template<typename T>
FORCEINLINE decltype(auto) Get () const &&
template<uint32 Index>
FORCEINLINE decltype(auto) Get () const volatile &
template<typename T>
FORCEINLINE decltype(auto) Get () const volatile &
template<uint32 Index>
FORCEINLINE decltype(auto) Get () const volatile &&
template<typename T>
FORCEINLINE decltype(auto) Get () const volatile &&
template<uint32 Index>
FORCEINLINE decltype(auto) Get () volatile &
template<typename T>
FORCEINLINE decltype(auto) Get () volatile &
template<uint32 Index>
FORCEINLINE decltype(auto) Get () volatile &&
template<typename T>
FORCEINLINE decltype(auto) Get () volatile &&
FORCEINLINE bool operator!= (const TTupleBase &Rhs) const
FORCEINLINE bool operator< (const TTupleBase &Rhs) const
FORCEINLINE bool operator<= (const TTupleBase &Rhs) const
TTupleBase & operator= (const TTupleBase &Other)=default
TTupleBase & operator= (TTupleBase &&Other)=default
FORCEINLINE bool operator== (const TTupleBase &Rhs) const
FORCEINLINE bool operator> (const TTupleBase &Rhs) const
FORCEINLINE bool operator>= (const TTupleBase &Rhs) const
Public Member Functions inherited from UE::Core::Private::Tuple::TTupleBaseElement< Types, Indices, sizeof...(Types)>
TTupleBaseElement (EForwardingConstructor, ArgType &&Arg)
TTupleBaseElement & operator= (TTupleBaseElement &&)=default
Static Public Member Functions
static FORCEINLINE void Serialize (FArchive &Ar, TTupleBase &Tuple)
static FORCEINLINE void SerializeStructured (FStructuredArchive::FSlot Slot, TTupleBase &Tuple)
Additional Inherited Members
Data Fields inherited from UE::Core::Private::Tuple::TTupleBaseElement< Types, Indices, sizeof...(Types)>
Types Value
Detailed Description
template<uint32... Indices, typename... Types>
struct UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >
Definition at line 275 of file Tuple.h.
Constructor & Destructor Documentation
TTupleBase() [1/5]
template<uint32... Indices, typename... Types> template<typename... ArgTypes, decltype(ConceptCheckingHelper(TTupleBaseElement< Types, Indices, sizeof...(Types)>(ForwardingConstructor, DeclVal< ArgTypes && >())...)) * = nullptr> UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::TTupleBase (EForwardingConstructor , ArgTypes &&... Args) inline explicit
Definition at line 281 of file Tuple.h.
References UE::Core::Private::Tuple::TTupleBaseElement< Types, Indices, sizeof...(Types)>::TTupleBaseElement(), Forward(), and UE::Core::Private::Tuple::ForwardingConstructor.
Referenced by TTupleBase(), TTupleBase(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), Get(), Get(), Get(), Get(), Get(), Get(), Get(), Get(), operator!=(), operator<(), operator<=(), operator=(), operator=(), operator==(), operator>(), operator>=(), Serialize(), and SerializeStructured().
TTupleBase() [2/5]
template<uint32... Indices, typename... Types> template<typename TupleType, decltype(ConceptCheckingHelper(TTupleBaseElement< Types, Indices, sizeof...(Types)>(ForwardingConstructor, DeclVal< TupleType && >().template Get< Indices >())...)) * = nullptr> UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::TTupleBase (EOtherTupleConstructor , TupleType && Other) inline explicit
Definition at line 290 of file Tuple.h.
References UE::Core::Private::Tuple::TTupleBaseElement< Types, Indices, sizeof...(Types)>::TTupleBaseElement(), Forward(), UE::Core::Private::Tuple::ForwardingConstructor, Get(), and Other.
TTupleBase() [3/5]
template<uint32... Indices, typename... Types> UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::TTupleBase () default
TTupleBase() [4/5]
template<uint32... Indices, typename... Types> UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::TTupleBase (TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > && Other) default
References TTupleBase(), and Other.
TTupleBase() [5/5]
template<uint32... Indices, typename... Types> UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::TTupleBase (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Other) default
References TTupleBase(), and Other.
Member Function Documentation
ApplyAfter() [1/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) & inline
Definition at line 319 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyAfter() [2/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) && inline
Definition at line 323 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyAfter() [3/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) const & inline
Definition at line 320 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyAfter() [4/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) const && inline
Definition at line 324 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyAfter() [5/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) const volatile & inline
Definition at line 322 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyAfter() [6/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) const volatile && inline
Definition at line 326 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyAfter() [7/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) volatile & inline
Definition at line 321 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyAfter() [8/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter (FuncType && Func, ArgTypes &&... Args) volatile && inline
Definition at line 325 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [1/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) & inline
Definition at line 328 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [2/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) && inline
Definition at line 332 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [3/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) const & inline
Definition at line 329 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [4/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) const && inline
Definition at line 333 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [5/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) const volatile & inline
Definition at line 331 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [6/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) const volatile && inline
Definition at line 335 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [7/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) volatile & inline
Definition at line 330 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
ApplyBefore() [8/8]
template<uint32... Indices, typename... Types> template<typename FuncType, typename... ArgTypes> decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore (FuncType && Func, ArgTypes &&... Args) volatile && inline
Definition at line 334 of file Tuple.h.
References TTupleBase(), Forward(), and Get().
Get() [1/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () & inline
Definition at line 301 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Referenced by TTupleBase(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyAfter(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), ApplyBefore(), Get(), Get(), Get(), Get(), Get(), Get(), Get(), Get(), Serialize(), and SerializeStructured().
Get() [2/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () & inline
Definition at line 310 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
Get() [3/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () && inline
Definition at line 305 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Get() [4/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () && inline
Definition at line 314 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
Get() [5/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const & inline
Definition at line 302 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Get() [6/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const & inline
Definition at line 311 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
Get() [7/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const && inline
Definition at line 306 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Get() [8/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const && inline
Definition at line 315 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
Get() [9/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const volatile & inline
Definition at line 304 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Get() [10/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const volatile & inline
Definition at line 313 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
Get() [11/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const volatile && inline
Definition at line 308 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Get() [12/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () const volatile && inline
Definition at line 317 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
Get() [13/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () volatile & inline
Definition at line 303 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Get() [14/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () volatile & inline
Definition at line 312 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
Get() [15/16]
template<uint32... Indices, typename... Types> template<uint32 Index> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () volatile && inline
Definition at line 307 of file Tuple.h.
References TTupleBase(), FORCEINLINE, and Get().
Get() [16/16]
template<uint32... Indices, typename... Types> template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get () volatile && inline
Definition at line 316 of file Tuple.h.
References TTupleBase(), FORCEINLINE, Get(), and UE::Core::Private::Tuple::TTypeCountInParameterPack_V.
operator!=()
template<uint32... Indices, typename... Types> FORCEINLINE bool UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator!= (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Rhs) const inline
Definition at line 358 of file Tuple.h.
References TTupleBase(), and FORCEINLINE.
operator<()
template<uint32... Indices, typename... Types> FORCEINLINE bool UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator< (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Rhs) const inline
Definition at line 363 of file Tuple.h.
References TTupleBase(), and FORCEINLINE.
operator<=()
template<uint32... Indices, typename... Types> FORCEINLINE bool UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator<= (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Rhs) const inline
Definition at line 368 of file Tuple.h.
References TTupleBase(), and FORCEINLINE.
operator=() [1/2]
template<uint32... Indices, typename... Types> TTupleBase & UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator= (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Other) default
References TTupleBase(), and Other.
operator=() [2/2]
template<uint32... Indices, typename... Types> TTupleBase & UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator= (TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > && Other) default
References TTupleBase(), and Other.
operator==()
template<uint32... Indices, typename... Types> FORCEINLINE bool UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator== (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Rhs) const inline
Definition at line 352 of file Tuple.h.
References TTupleBase(), and FORCEINLINE.
operator>()
template<uint32... Indices, typename... Types> FORCEINLINE bool UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator> (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Rhs) const inline
Definition at line 373 of file Tuple.h.
References TTupleBase(), and FORCEINLINE.
operator>=()
template<uint32... Indices, typename... Types> FORCEINLINE bool UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::operator>= (const TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Rhs) const inline
Definition at line 378 of file Tuple.h.
References TTupleBase(), and FORCEINLINE.
Serialize()
template<uint32... Indices, typename... Types> FORCEINLINE void UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Serialize (FArchive & Ar, TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Tuple) inline static
Definition at line 337 of file Tuple.h.
References TTupleBase(), Ar, FORCEINLINE, and Get().
SerializeStructured()
template<uint32... Indices, typename... Types> FORCEINLINE void UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::SerializeStructured (FStructuredArchive::FSlot Slot, TTupleBase< TIntegerSequence< uint32, Indices... >, Types... > & Tuple) inline static
Definition at line 344 of file Tuple.h.
References TTupleBase(), FStructuredArchiveSlot::EnterStream(), FORCEINLINE, Get(), and Stream.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/Tuple.h