Unreal Engine 5.6 C++ API: FWidgetReference Struct Reference
FWidgetReference Struct Reference
The Widget reference is a useful way to hold onto the selection in a way that allows for up to date access to the current preview object.
#include "WidgetReference.h"
Public Member Functions
FWidgetReference ()
UWidget * GetPreview () const
TSharedPtr< SWidget > GetPreviewSlate () const
UWidget * GetTemplate () const
TSharedPtr< FWidgetBlueprintEditor > GetWidgetEditor () const
bool IsValid () const
bool operator!= (const FWidgetReference &Other) const
Checks if widget reference is the different from another widget reference, based on the template pointers.
bool operator== (const FWidgetReference &Other) const
Checks if widget reference is the same as another widget reference, based on the template pointers.
Data Fields
friend FWidgetBlueprintEditor
Private Member Functions
FWidgetReference (TSharedPtr< FWidgetBlueprintEditor > WidgetEditor, TSharedPtr< FWidgetHandle > TemplateHandle)
void OnObjectsReplaced (const TMap< UObject *, UObject * > &ReplacementMap)
Private Attributes
TSharedPtr< FWidgetHandle > TemplateHandle
TWeakPtr< FWidgetBlueprintEditor > WidgetEditor
Detailed Description
The Widget reference is a useful way to hold onto the selection in a way that allows for up to date access to the current preview object.
Because the designer could end up rebuilding the preview, it's best to hold onto an FWidgetReference.
Definition at line 26 of file WidgetReference.h.
Constructor & Destructor Documentation
FWidgetReference() [1/2]
FWidgetReference::FWidgetReference ()
Referenced by operator!=(), and operator==().
FWidgetReference() [2/2]
FWidgetReference::FWidgetReference (TSharedPtr< FWidgetBlueprintEditor > WidgetEditor, TSharedPtr< FWidgetHandle > TemplateHandle) private
References TemplateHandle, and WidgetEditor.
Member Function Documentation
GetPreview()
UWidget * FWidgetReference::GetPreview () const
Returns
the preview widget. This is the transient representation of the template. Constantly being destroyed and recreated. Do not cache this pointer.
Referenced by GetPreviewSlate().
GetPreviewSlate()
TSharedPtr< SWidget > FWidgetReference::GetPreviewSlate () const inline
Returns
the preview slate widget. This is the transient representation of the template. Constantly being destroyed and recreated. Do not cache this pointer.
Definition at line 43 of file WidgetReference.h.
References GetPreview(), and IsValid().
GetTemplate()
UWidget * FWidgetReference::GetTemplate () const
Returns
The template widget. This is the widget that is serialized to disk
Referenced by GetTypeHash().
GetWidgetEditor()
TSharedPtr< FWidgetBlueprintEditor > FWidgetReference::GetWidgetEditor () const inline
Definition at line 53 of file WidgetReference.h.
References WidgetEditor.
IsValid()
bool FWidgetReference::IsValid () const
Returns
true if both the template and the preview pointers are valid.
OnObjectsReplaced()
void FWidgetReference::OnObjectsReplaced (const TMap< UObject *, UObject * > & ReplacementMap) private
operator!=()
bool FWidgetReference::operator!= (const FWidgetReference & Other) const inline
Checks if widget reference is the different from another widget reference, based on the template pointers.
Definition at line 67 of file WidgetReference.h.
References FWidgetReference(), operator==(), and Other.
operator==()
bool FWidgetReference::operator== (const FWidgetReference & Other) const inline
Checks if widget reference is the same as another widget reference, based on the template pointers.
Definition at line 56 of file WidgetReference.h.
References FWidgetReference(), Other, and TemplateHandle.
Field Documentation
FWidgetBlueprintEditor
friend FWidgetReference::FWidgetBlueprintEditor
Definition at line 28 of file WidgetReference.h.
TemplateHandle
TSharedPtr< FWidgetHandle > FWidgetReference::TemplateHandle private
Definition at line 80 of file WidgetReference.h.
Referenced by FWidgetReference(), and operator==().
WidgetEditor
TWeakPtr<FWidgetBlueprintEditor> FWidgetReference::WidgetEditor private
Definition at line 78 of file WidgetReference.h.
Referenced by FWidgetReference(), and GetWidgetEditor().
The documentation for this struct was generated from the following file:
Editor/UMGEditor/Public/WidgetReference.h