Unreal Engine 5.6 C++ API: TCustomLerp< UE::Math::TQuat< T > > Struct Template Reference
TCustomLerp< UE::Math::TQuat< T > > Struct Template Reference
#include "Quat.h"
Public Types
using QuatType = UE::Math::TQuat<T>
Static Public Member Functions
template<class U>
static FORCEINLINE_DEBUGGABLE QuatType BiLerp (const QuatType &P00, const QuatType &P10, const QuatType &P01, const QuatType &P11, const U &FracX, const U &FracY)
template<class U>
static FORCEINLINE_DEBUGGABLE QuatType CubicInterp (const QuatType &P0, const QuatType &T0, const QuatType &P1, const QuatType &T1, const U &A)
template<class U>
static FORCEINLINE_DEBUGGABLE QuatType Lerp (const QuatType &A, const QuatType &B, const U &Alpha)
Static Public Attributes
static constexpr bool Value = true
Detailed Description
template<typename T>
struct TCustomLerp< UE::Math::TQuat< T > >
Definition at line 1476 of file Quat.h.
Member Typedef Documentation
QuatType
template<typename T> using TCustomLerp< UE::Math::TQuat< T > >::QuatType = UE::Math::TQuat<T>
Definition at line 1479 of file Quat.h.
Member Function Documentation
BiLerp()
template<typename T> template<class U> FORCEINLINE_DEBUGGABLE QuatType TCustomLerp< UE::Math::TQuat< T > >::BiLerp (const QuatType & P00, const QuatType & P10, const QuatType & P01, const QuatType & P11, const U & FracX, const U & FracY) inline static
Definition at line 1488 of file Quat.h.
References FORCEINLINE_DEBUGGABLE, Lerp, and UE::Math::TQuat< T >::Slerp_NotNormalized().
CubicInterp()
template<typename T> template<class U> FORCEINLINE_DEBUGGABLE QuatType TCustomLerp< UE::Math::TQuat< T > >::CubicInterp (const QuatType & P0, const QuatType & T0, const QuatType & P1, const QuatType & T1, const U & A) inline static
Definition at line 1502 of file Quat.h.
References A, FORCEINLINE_DEBUGGABLE, and UE::Math::TQuat< T >::Squad().
Lerp()
template<typename T> template<class U> FORCEINLINE_DEBUGGABLE QuatType TCustomLerp< UE::Math::TQuat< T > >::Lerp (const QuatType & A, const QuatType & B, const U & Alpha) inline static
Definition at line 1482 of file Quat.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, and UE::Math::TQuat< T >::Slerp().
Field Documentation
Value
template<typename T> bool TCustomLerp< UE::Math::TQuat< T > >::Value = true static constexpr
Definition at line 1478 of file Quat.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/Quat.h