Unreal Engine 5.6 C++ API: TNetSimCueWrapper< TCue > Struct Template Reference
TNetSimCueWrapper< TCue > Struct Template Reference
#include "NetworkPredictionCues.h"
Public Member Functions
TNetSimCueWrapper ()=default
template<typename... ArgsType>
TNetSimCueWrapper (ArgsType &&... Args)
void * CueData () const override final
ENetSimCueReplicationTarget GetReplicationTarget () const override final
bool NetIdentical (const void *OtherCueData) const override final
void NetSerialize (FArchive &Ar) override final
Public Member Functions inherited from FNetSimCueWrapperBase
virtual ~FNetSimCueWrapperBase ()
Data Fields
TCue Instance
Detailed Description
template<typename TCue>
struct TNetSimCueWrapper< TCue >
Definition at line 63 of file NetworkPredictionCues.h.
Constructor & Destructor Documentation
TNetSimCueWrapper() [1/2]
template<typename TCue> TNetSimCueWrapper< TCue >::TNetSimCueWrapper () default
TNetSimCueWrapper() [2/2]
template<typename TCue> template<typename... ArgsType> TNetSimCueWrapper< TCue >::TNetSimCueWrapper (ArgsType &&... Args) inline
Definition at line 68 of file NetworkPredictionCues.h.
References Forward(), Instance, and MoveTempIfPossible().
Member Function Documentation
CueData()
template<typename TCue> void * TNetSimCueWrapper< TCue >::CueData () const inline final override virtual
Implements FNetSimCueWrapperBase.
Definition at line 81 of file NetworkPredictionCues.h.
References Instance.
GetReplicationTarget()
template<typename TCue> ENetSimCueReplicationTarget TNetSimCueWrapper< TCue >::GetReplicationTarget () const inline final override virtual
Implements FNetSimCueWrapperBase.
Definition at line 86 of file NetworkPredictionCues.h.
References TNetSimCueTraits< TCue >::ReplicationTarget.
NetIdentical()
template<typename TCue> bool TNetSimCueWrapper< TCue >::NetIdentical (const void * OtherCueData) const inline final override virtual
Implements FNetSimCueWrapperBase.
Definition at line 76 of file NetworkPredictionCues.h.
References TNetCueNetIdenticalHelper< TCue, Enabled >::CallNetIdenticalOrNot(), and Instance.
NetSerialize()
template<typename TCue> void TNetSimCueWrapper< TCue >::NetSerialize (FArchive & Ar) inline final override virtual
Implements FNetSimCueWrapperBase.
Definition at line 71 of file NetworkPredictionCues.h.
References Ar, TNetCueNetSerializeHelper< TCue, Enabled >::CallNetSerializeOrNot(), and Instance.
Field Documentation
Instance
template<typename TCue> TCue TNetSimCueWrapper< TCue >::Instance
Definition at line 91 of file NetworkPredictionCues.h.
Referenced by TNetSimCueWrapper(), CueData(), NetIdentical(), and NetSerialize().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionCues.h