Unreal Engine 5.6 C++ API: UE::AnimNext::ISmoothBlend Struct Reference
UE::AnimNext::ISmoothBlend Struct Reference
ISmoothBlend.
#include "ISmoothBlend.h"
Public Member Functions
DECLARE_ANIM_TRAIT_INTERFACE (ISmoothBlend) ANIMNEXTANIMGRAPH_API virtual float GetBlendTime(FExecutionContext &Context
virtual ANIMNEXTANIMGRAPH_API EAlphaBlendOption GetBlendType (FExecutionContext &Context, const TTraitBinding< ISmoothBlend > &Binding, int32 ChildIndex) const
virtual ANIMNEXTANIMGRAPH_API UCurveFloat * GetCustomBlendCurve (FExecutionContext &Context, const TTraitBinding< ISmoothBlend > &Binding, int32 ChildIndex) const
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayName () const override
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayShortName () const override
Public Member Functions inherited from UE::AnimNext::ITraitInterface
virtual ~ITraitInterface ()
virtual FTraitInterfaceUID GetInterfaceUID () const
virtual bool IsInternal () const
Data Fields
const TTraitBinding< ISmoothBlend > & Binding
const TTraitBinding< ISmoothBlend > int32 ChildIndex const
Additional Inherited Members
Static Public Attributes inherited from UE::AnimNext::ITraitInterface
static constexpr FTraitInterfaceUID InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface"))
Detailed Description
ISmoothBlend.
This interface exposes blend smoothing related information.
Blend smoothing is a process that may be needed for discrete blends to make their pose transition appear continuous (IE: smooth).
Definition at line 23 of file ISmoothBlend.h.
Member Function Documentation
DECLARE_ANIM_TRAIT_INTERFACE()
UE::AnimNext::ISmoothBlend::DECLARE_ANIM_TRAIT_INTERFACE (ISmoothBlend) &
GetBlendType()
virtual ANIMNEXTANIMGRAPH_API EAlphaBlendOption UE::AnimNext::ISmoothBlend::GetBlendType (FExecutionContext & Context, const TTraitBinding< ISmoothBlend > & Binding, int32 ChildIndex) const virtual
Reimplemented in UE::AnimNext::FBlendSmootherTrait, and UE::AnimNext::FBlendStackCoreTrait.
References Binding, const, GetBlendType(), and UE_API.
Referenced by GetBlendType().
GetCustomBlendCurve()
virtual ANIMNEXTANIMGRAPH_API UCurveFloat * UE::AnimNext::ISmoothBlend::GetCustomBlendCurve (FExecutionContext & Context, const TTraitBinding< ISmoothBlend > & Binding, int32 ChildIndex) const virtual
Reimplemented in UE::AnimNext::FBlendSmootherTrait, and UE::AnimNext::FBlendStackCoreTrait.
References Binding, const, GetCustomBlendCurve(), and UE_API.
Referenced by GetCustomBlendCurve().
GetDisplayName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::ISmoothBlend::GetDisplayName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetDisplayShortName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::ISmoothBlend::GetDisplayShortName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
Field Documentation
Binding
const TTraitBinding<ISmoothBlend>& UE::AnimNext::ISmoothBlend::Binding
Definition at line 28 of file ISmoothBlend.h.
Referenced by UE::AnimNext::FBlendSmootherTrait::GetBlendTime(), UE::AnimNext::FBlendSmootherTrait::GetBlendType(), GetBlendType(), UE::AnimNext::FBlendSmootherTrait::GetCustomBlendCurve(), and GetCustomBlendCurve().
const
const TTraitBinding<ISmoothBlend> int32 ChildIndex UE::AnimNext::ISmoothBlend::const
Definition at line 28 of file ISmoothBlend.h.
Referenced by GetBlendType(), and GetCustomBlendCurve().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitInterfaces/ISmoothBlend.h