Unreal Engine 5.6 C++ API: FPropertyTag Struct Reference
FPropertyTag Struct Reference
A tag describing a class property, to aid in serialization.
#include "PropertyTag.h"
Public Member Functions
FPropertyTag ()
FPropertyTag (const FPropertyTag &)=default
UE_INTERNAL FPropertyTag (FProperty *Property, int32 InIndex, uint8 *Value)
PRAGMA_DISABLE_DEPRECATION_WARNINGS FPropertyTag (FPropertyTag &&)=default
PRAGMA_ENABLE_DEPRECATION_WARNINGS FProperty * GetProperty () const
UE::FPropertyTypeName GetType () const
FPropertyTag & operator= (const FPropertyTag &)=default
FPropertyTag & operator= (FPropertyTag &&)=default
void SerializeTaggedProperty (FArchive &Ar, FProperty *Property, uint8 *Value, const uint8 *Defaults) const
UE_INTERNAL void SerializeTaggedProperty (FStructuredArchive::FSlot Slot, FProperty *Property, uint8 *Value, const uint8 *Defaults) const
void SetProperty (FProperty *Property)
void SetPropertyGuid (const FGuid &InPropertyGuid)
void SetType (UE::FPropertyTypeName TypeName)
UE_DEPRECATED (5.4, "EnumName has been deprecated and replaced by GetType(). Use GetType().IsEnum(EnumName) to test, otherwise if Type is EnumProperty or ByteProperty then EnumName is GetType().GetParameterName(0).") FName EnumName
UE_DEPRECATED (5.4, "InnerName has been deprecated and replaced by GetType(). If Type is ArrayProperty/SetProperty/MapProperty/OptionalProperty then InnerType is GetType().GetParameterName(0).") FName InnerType
UE_DEPRECATED (5.4, "Prop has been deprecated. Use GetProperty()/SetProperty().") FProperty *Prop
UE_DEPRECATED (5.4, "StructGuid has been deprecated and replaced by GetType(). If Type is StructProperty then StructGuid is GetType().GetParameterName(1).") FGuid StructGuid
UE_DEPRECATED (5.4, "StructName has been deprecated and replaced by GetType(). Use GetType().IsStruct(StructName) to test, otherwise if Type is StructProperty then StructName is GetType().GetParameterName(0).") FName StructName
UE_DEPRECATED (5.4, "ValueName has been deprecated and replaced by GetType(). If Type is MapProperty then ValueType is GetType().GetParameterName(1).") FName ValueType
Data Fields
int32 ArrayIndex = INDEX_NONE
bool bExperimentalOverridableLogic = false
uint8 BoolVal = 0
uint8 HasPropertyGuid = 0
FName Name
EOverriddenPropertyOperation OverrideOperation
FGuid PropertyGuid
EPropertyTagSerializeType SerializeType = EPropertyTagSerializeType::Unknown
int32 Size = 0
int64 SizeOffset = INDEX_NONE
FName Type
Private Attributes
UE::FPropertyTypeName TypeName
Friends
void LoadPropertyTagNoFullType (FStructuredArchive::FSlot Slot, FPropertyTag &Tag)
FArchive & operator<< (FArchive &Ar, FPropertyTag &Tag)
void operator<< (FStructuredArchive::FSlot Slot, FPropertyTag &Tag)
void SerializePropertyTagAsText (FStructuredArchive::FSlot Slot, FPropertyTag &Tag)
Detailed Description
A tag describing a class property, to aid in serialization.
Definition at line 37 of file PropertyTag.h.
Constructor & Destructor Documentation
FPropertyTag() [1/4]
FPropertyTag::FPropertyTag ()
References FPropertyTag().
Referenced by FPropertyTag(), FPropertyTag(), FPropertyTag(), FPropertyTag(), LoadPropertyTagNoFullType, operator<<, operator<<, operator=(), operator=(), and SerializePropertyTagAsText.
FPropertyTag() [2/4]
UE_INTERNAL FPropertyTag::FPropertyTag (FProperty * Property, int32 InIndex, uint8 * Value)
References FPropertyTag(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, Property, UE_INTERNAL, and Value.
FPropertyTag() [3/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FPropertyTag::FPropertyTag (FPropertyTag &&) default
References FPropertyTag().
FPropertyTag() [4/4]
FPropertyTag::FPropertyTag (const FPropertyTag &) default
References FPropertyTag().
Member Function Documentation
GetProperty()
PRAGMA_ENABLE_DEPRECATION_WARNINGS FProperty * FPropertyTag::GetProperty () const inline
Definition at line 81 of file PropertyTag.h.
References GetProperty(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by GetProperty().
GetType()
UE::FPropertyTypeName FPropertyTag::GetType () const inline
Definition at line 91 of file PropertyTag.h.
References TypeName.
Referenced by TProperty_Numeric< InTCppType >::ConvertFromType(), UScriptStruct::TCppStructOps< CPPSTRUCT >::SerializeFromMismatchedTag(), and UScriptStruct::TCppStructOps< CPPSTRUCT >::StructuredSerializeFromMismatchedTag().
operator=() [1/2]
FPropertyTag & FPropertyTag::operator= (const FPropertyTag &) default
References FPropertyTag(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FPropertyTag & FPropertyTag::operator= (FPropertyTag &&) default
References FPropertyTag().
SerializeTaggedProperty() [1/2]
void FPropertyTag::SerializeTaggedProperty (FArchive & Ar, FProperty * Property, uint8 * Value, const uint8 * Defaults) const
References Ar, Property, and Value.
SerializeTaggedProperty() [2/2]
UE_INTERNAL void FPropertyTag::SerializeTaggedProperty (FStructuredArchive::FSlot Slot, FProperty * Property, uint8 * Value, const uint8 * Defaults) const
References Property, UE_INTERNAL, and Value.
SetProperty()
void FPropertyTag::SetProperty (FProperty * Property)
References Property.
SetPropertyGuid()
void FPropertyTag::SetPropertyGuid (const FGuid & InPropertyGuid)
SetType()
void FPropertyTag::SetType (UE::FPropertyTypeName TypeName)
References TypeName.
UE_DEPRECATED() [1/6]
FPropertyTag::UE_DEPRECATED (5. 4, "EnumName has been deprecated and replaced by GetType(). Use GetType().IsEnum(EnumName) to test, otherwise if Type is EnumProperty or ByteProperty then EnumName is GetType().GetParameterName(0).")
References UE_DEPRECATED().
UE_DEPRECATED() [2/6]
FPropertyTag::UE_DEPRECATED (5. 4, "InnerName has been deprecated and replaced by GetType(). If Type is ArrayProperty/SetProperty/MapProperty/OptionalProperty then InnerType is GetType().GetParameterName(0).")
References UE_DEPRECATED().
UE_DEPRECATED() [3/6]
FPropertyTag::UE_DEPRECATED (5. 4, "Prop has been deprecated. Use GetProperty()/SetProperty().")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [4/6]
FPropertyTag::UE_DEPRECATED (5. 4, "StructGuid has been deprecated and replaced by GetType(). If Type is StructProperty then StructGuid is GetType().GetParameterName(1).")
References UE_DEPRECATED().
UE_DEPRECATED() [5/6]
FPropertyTag::UE_DEPRECATED (5. 4, "StructName has been deprecated and replaced by GetType(). Use GetType().IsStruct(StructName) to test, otherwise if Type is StructProperty then StructName is GetType().GetParameterName(0).")
References UE_DEPRECATED().
UE_DEPRECATED() [6/6]
FPropertyTag::UE_DEPRECATED (5. 4, "ValueName has been deprecated and replaced by GetType(). If Type is MapProperty then ValueType is GetType().GetParameterName(1).")
References UE_DEPRECATED().
Friends And Related Symbol Documentation
LoadPropertyTagNoFullType
void LoadPropertyTagNoFullType (FStructuredArchive::FSlot Slot, FPropertyTag & Tag) friend
References FPropertyTag().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPropertyTag & Tag) friend
References FPropertyTag(), and Ar.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FPropertyTag & Tag) friend
References FPropertyTag().
SerializePropertyTagAsText
void SerializePropertyTagAsText (FStructuredArchive::FSlot Slot, FPropertyTag & Tag) friend
References FPropertyTag().
Field Documentation
ArrayIndex
int32 FPropertyTag::ArrayIndex = INDEX_NONE
Definition at line 59 of file PropertyTag.h.
Referenced by TProperty_Numeric< InTCppType >::TConvertAndSet< FromType, ToType >::TConvertAndSet(), TProperty_Numeric< InTCppType >::TConvertAndSet< SameType, SameType >::TConvertAndSet(), and TProperty_Numeric< InTCppType >::ConvertFromType().
bExperimentalOverridableLogic
bool FPropertyTag::bExperimentalOverridableLogic = false
Definition at line 68 of file PropertyTag.h.
BoolVal
uint8 FPropertyTag::BoolVal = 0
Definition at line 65 of file PropertyTag.h.
Referenced by TProperty_Numeric< InTCppType >::ConvertFromType().
HasPropertyGuid
uint8 FPropertyTag::HasPropertyGuid = 0
Definition at line 64 of file PropertyTag.h.
Name
FName FPropertyTag::Name
Definition at line 49 of file PropertyTag.h.
OverrideOperation
EOverriddenPropertyOperation FPropertyTag::OverrideOperation
Definition at line 67 of file PropertyTag.h.
PropertyGuid
FGuid FPropertyTag::PropertyGuid
Definition at line 63 of file PropertyTag.h.
SerializeType
EPropertyTagSerializeType FPropertyTag::SerializeType = EPropertyTagSerializeType::Unknown
Definition at line 66 of file PropertyTag.h.
Size
int32 FPropertyTag::Size = 0
Definition at line 58 of file PropertyTag.h.
SizeOffset
int64 FPropertyTag::SizeOffset = INDEX_NONE
Definition at line 60 of file PropertyTag.h.
Type
FName FPropertyTag::Type
Definition at line 48 of file PropertyTag.h.
Referenced by TProperty_Numeric< InTCppType >::ConvertFromType(), FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::SerializeFromMismatchedTag(), and TPerPlatformProperty< _StructType, _ValueType, _BasePropertyName >::SerializeFromMismatchedTag().
TypeName
UE::FPropertyTypeName FPropertyTag::TypeName private
Definition at line 45 of file PropertyTag.h.
Referenced by GetType(), and SetType().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PropertyTag.h