Unreal Engine 5.6 C++ API: FGameTime Struct Reference
FGameTime Struct Reference
Contains all the timings of a gaming frame, to handle pause and time dilation (for instance bullet time) of the world.
#include "GameTime.h"
Public Member Functions
FORCEINLINE_DEBUGGABLE FGameTime ()
FGameTime (const FGameTime &)=default
FORCEINLINE_DEBUGGABLE float GetDeltaRealTimeSeconds () const
Returns frame delta time in seconds with no adjustment for time dilation and pause.
FORCEINLINE_DEBUGGABLE float GetDeltaWorldTimeSeconds () const
Returns frame delta time in seconds adjusted by e.g.
FORCEINLINE_DEBUGGABLE double GetRealTimeSeconds () const
Returns time in seconds since level began play, but IS NOT paused when the game is paused, and IS NOT dilated/clamped.
FORCEINLINE_DEBUGGABLE float GetTimeDilation () const
Returns how much world time is slowed compared to real time.
FORCEINLINE_DEBUGGABLE double GetWorldTimeSeconds () const
Returns time in seconds since level began play, but IS paused when the game is paused, and IS dilated/clamped.
FORCEINLINE_DEBUGGABLE bool IsPaused () const
Returns whether the world time is paused.
FGameTime & operator= (const FGameTime &)=default
Static Public Member Functions
static FORCEINLINE_DEBUGGABLE FGameTime CreateDilated (double InRealTimeSeconds, float InDeltaRealTimeSeconds, double InWorldTimeSeconds, float InDeltaWorldTimeSeconds)
static FORCEINLINE_DEBUGGABLE FGameTime CreateUndilated (double InRealTimeSeconds, float InDeltaRealTimeSeconds)
static FGameTime GetTimeSinceAppStart ()
Private Member Functions
FORCEINLINE_DEBUGGABLE FGameTime (double InRealTimeSeconds, float InDeltaRealTimeSeconds, double InWorldTimeSeconds, float InDeltaWorldTimeSeconds)
Private Attributes
float DeltaRealTimeSeconds
float DeltaWorldTimeSeconds
double RealTimeSeconds
double WorldTimeSeconds
Detailed Description
Contains all the timings of a gaming frame, to handle pause and time dilation (for instance bullet time) of the world.
Definition at line 9 of file GameTime.h.
Constructor & Destructor Documentation
FGameTime() [1/3]
FORCEINLINE_DEBUGGABLE FGameTime::FGameTime () inline
Definition at line 11 of file GameTime.h.
References DeltaRealTimeSeconds, DeltaWorldTimeSeconds, FORCEINLINE_DEBUGGABLE, RealTimeSeconds, and WorldTimeSeconds.
Referenced by FGameTime(), CreateDilated(), CreateUndilated(), GetTimeSinceAppStart(), and operator=().
FGameTime() [2/3]
FGameTime::FGameTime (const FGameTime &) default
References FGameTime().
FGameTime() [3/3]
FORCEINLINE_DEBUGGABLE FGameTime::FGameTime (double InRealTimeSeconds, float InDeltaRealTimeSeconds, double InWorldTimeSeconds, float InDeltaWorldTimeSeconds) inline private
Definition at line 78 of file GameTime.h.
References DeltaRealTimeSeconds, DeltaWorldTimeSeconds, FORCEINLINE_DEBUGGABLE, RealTimeSeconds, and WorldTimeSeconds.
Member Function Documentation
CreateDilated()
FORCEINLINE_DEBUGGABLE FGameTime FGameTime::CreateDilated (double InRealTimeSeconds, float InDeltaRealTimeSeconds, double InWorldTimeSeconds, float InDeltaWorldTimeSeconds) inline static
Definition at line 29 of file GameTime.h.
References FGameTime(), and FORCEINLINE_DEBUGGABLE.
Referenced by CreateUndilated().
CreateUndilated()
FORCEINLINE_DEBUGGABLE FGameTime FGameTime::CreateUndilated (double InRealTimeSeconds, float InDeltaRealTimeSeconds) inline static
Definition at line 24 of file GameTime.h.
References FGameTime(), CreateDilated(), and FORCEINLINE_DEBUGGABLE.
GetDeltaRealTimeSeconds()
FORCEINLINE_DEBUGGABLE float FGameTime::GetDeltaRealTimeSeconds () const inline
Returns frame delta time in seconds with no adjustment for time dilation and pause.
Definition at line 41 of file GameTime.h.
References DeltaRealTimeSeconds, and FORCEINLINE_DEBUGGABLE.
GetDeltaWorldTimeSeconds()
FORCEINLINE_DEBUGGABLE float FGameTime::GetDeltaWorldTimeSeconds () const inline
Returns frame delta time in seconds adjusted by e.g.
time dilation.
Definition at line 53 of file GameTime.h.
References DeltaWorldTimeSeconds, and FORCEINLINE_DEBUGGABLE.
Referenced by FCanvas::UE_DEPRECATED().
GetRealTimeSeconds()
FORCEINLINE_DEBUGGABLE double FGameTime::GetRealTimeSeconds () const inline
Returns time in seconds since level began play, but IS NOT paused when the game is paused, and IS NOT dilated/clamped.
Definition at line 35 of file GameTime.h.
References FORCEINLINE_DEBUGGABLE, and RealTimeSeconds.
GetTimeDilation()
FORCEINLINE_DEBUGGABLE float FGameTime::GetTimeDilation () const inline
Returns how much world time is slowed compared to real time.
Definition at line 59 of file GameTime.h.
References DeltaRealTimeSeconds, DeltaWorldTimeSeconds, ensure, and FORCEINLINE_DEBUGGABLE.
GetTimeSinceAppStart()
FGameTime FGameTime::GetTimeSinceAppStart () static
References FGameTime().
GetWorldTimeSeconds()
FORCEINLINE_DEBUGGABLE double FGameTime::GetWorldTimeSeconds () const inline
Returns time in seconds since level began play, but IS paused when the game is paused, and IS dilated/clamped.
Definition at line 47 of file GameTime.h.
References FORCEINLINE_DEBUGGABLE, and WorldTimeSeconds.
IsPaused()
FORCEINLINE_DEBUGGABLE bool FGameTime::IsPaused () const inline
Returns whether the world time is paused.
Definition at line 66 of file GameTime.h.
References DeltaWorldTimeSeconds, and FORCEINLINE_DEBUGGABLE.
operator=()
FGameTime & FGameTime::operator= (const FGameTime &) default
References FGameTime().
Field Documentation
DeltaRealTimeSeconds
float FGameTime::DeltaRealTimeSeconds private
Definition at line 75 of file GameTime.h.
Referenced by FGameTime(), FGameTime(), GetDeltaRealTimeSeconds(), and GetTimeDilation().
DeltaWorldTimeSeconds
float FGameTime::DeltaWorldTimeSeconds private
Definition at line 76 of file GameTime.h.
Referenced by FGameTime(), FGameTime(), GetDeltaWorldTimeSeconds(), GetTimeDilation(), and IsPaused().
RealTimeSeconds
double FGameTime::RealTimeSeconds private
Definition at line 72 of file GameTime.h.
Referenced by FGameTime(), FGameTime(), and GetRealTimeSeconds().
WorldTimeSeconds
double FGameTime::WorldTimeSeconds private
Definition at line 73 of file GameTime.h.
Referenced by FGameTime(), FGameTime(), and GetWorldTimeSeconds().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/GameTime.h