Unreal Engine 5.6 C++ API: Nanite::FPackedCluster Struct Reference
Nanite::FPackedCluster Struct Reference
#include "NaniteResources.h"
Public Member Functions
uint32 GetAttributeOffset () const
uint32 GetBitsPerAttribute () const
uint32 GetBitsPerIndex () const
uint32 GetFlags () const
uint32 GetIndexOffset () const
uint32 GetNormalPrecision () const
uint32 GetNumClusterBoneInfluences () const
uint32 GetNumTris () const
uint32 GetNumVerts () const
uint32 GetPosBitsX () const
uint32 GetPosBitsY () const
uint32 GetPosBitsZ () const
uint32 GetPositionOffset () const
int32 GetPosPrecision () const
uint32 GetTangentPrecision () const
void SetAttributeOffset (uint32 Offset)
void SetBitsPerAttribute (uint32 Bits)
void SetBitsPerIndex (uint32 BitsPerIndex)
void SetBrickDataNum (uint32 Num)
void SetBrickDataOffset (uint32 Offset)
void SetColorBitsA (uint32 NumBits)
void SetColorBitsB (uint32 NumBits)
void SetColorBitsG (uint32 NumBits)
void SetColorBitsR (uint32 NumBits)
void SetColorMode (uint32 Mode)
void SetDecodeInfoOffset (uint32 Offset)
void SetExtendedDataNum (uint32 Num)
void SetExtendedDataOffset (uint32 Offset)
void SetFlags (uint32 Flags)
void SetGroupIndex (uint32 GroupIndex)
void SetHasSkinning (bool bSkinning)
void SetHasTangents (bool bHasTangents)
void SetIndexOffset (uint32 Offset)
void SetNormalPrecision (uint32 NumBits)
void SetNumClusterBoneInfluences (uint32 N)
void SetNumTris (uint32 NumTris)
void SetNumUVs (uint32 Num)
void SetNumVerts (uint32 NumVerts)
void SetPosBitsX (uint32 NumBits)
void SetPosBitsY (uint32 NumBits)
void SetPosBitsZ (uint32 NumBits)
void SetPositionOffset (uint32 Offset)
void SetPosPrecision (int32 Precision)
void SetTangentPrecision (uint32 NumBits)
void SetVertResourceBatchInfo (TArray< uint32 > &BatchInfo, uint32 GpuPageOffset, uint32 NumMaterialRanges)
Data Fields
uint32 AttributeOffset_BitsPerAttribute
uint32 BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision
FVector3f BoxBoundsCenter
FVector3f BoxBoundsExtent
uint32 BrickDataOffset_Num
uint32 ColorBits_GroupIndex
uint32 ColorMin
uint32 DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode
uint32 Dummy0
uint32 Dummy1
uint32 ExtendedDataOffset_Num
uint32 Flags_NumClusterBoneInfluences
FSphere3f LODBounds
uint32 LODErrorAndEdgeLength
uint32 NumTris_IndexOffset
uint32 NumVerts_PositionOffset
uint32 PackedMaterialInfo
FIntVector PosStart
uint32 UVBitOffsets
uint32 VertReuseBatchInfo [4]
Detailed Description
Definition at line 94 of file NaniteResources.h.
Member Function Documentation
GetAttributeOffset()
uint32 Nanite::FPackedCluster::GetAttributeOffset () const inline
Definition at line 148 of file NaniteResources.h.
References AttributeOffset_BitsPerAttribute, and Nanite::GetBits().
GetBitsPerAttribute()
uint32 Nanite::FPackedCluster::GetBitsPerAttribute () const inline
Definition at line 149 of file NaniteResources.h.
References AttributeOffset_BitsPerAttribute, and Nanite::GetBits().
GetBitsPerIndex()
uint32 Nanite::FPackedCluster::GetBitsPerIndex () const inline
Definition at line 136 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::GetBits().
GetFlags()
uint32 Nanite::FPackedCluster::GetFlags () const inline
Definition at line 144 of file NaniteResources.h.
References Flags_NumClusterBoneInfluences, and Nanite::GetBits().
GetIndexOffset()
uint32 Nanite::FPackedCluster::GetIndexOffset () const inline
Definition at line 134 of file NaniteResources.h.
References Nanite::GetBits(), and NumTris_IndexOffset.
GetNormalPrecision()
uint32 Nanite::FPackedCluster::GetNormalPrecision () const inline
Definition at line 141 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::GetBits().
GetNumClusterBoneInfluences()
uint32 Nanite::FPackedCluster::GetNumClusterBoneInfluences () const inline
Definition at line 145 of file NaniteResources.h.
References Flags_NumClusterBoneInfluences, and Nanite::GetBits().
GetNumTris()
uint32 Nanite::FPackedCluster::GetNumTris () const inline
Definition at line 133 of file NaniteResources.h.
References Nanite::GetBits(), and NumTris_IndexOffset.
GetNumVerts()
uint32 Nanite::FPackedCluster::GetNumVerts () const inline
Definition at line 130 of file NaniteResources.h.
References Nanite::GetBits(), and NumVerts_PositionOffset.
GetPosBitsX()
uint32 Nanite::FPackedCluster::GetPosBitsX () const inline
Definition at line 138 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::GetBits().
GetPosBitsY()
uint32 Nanite::FPackedCluster::GetPosBitsY () const inline
Definition at line 139 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::GetBits().
GetPosBitsZ()
uint32 Nanite::FPackedCluster::GetPosBitsZ () const inline
Definition at line 140 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::GetBits().
GetPositionOffset()
uint32 Nanite::FPackedCluster::GetPositionOffset () const inline
Definition at line 131 of file NaniteResources.h.
References Nanite::GetBits(), and NumVerts_PositionOffset.
GetPosPrecision()
int32 Nanite::FPackedCluster::GetPosPrecision () const inline
Definition at line 137 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::GetBits().
GetTangentPrecision()
uint32 Nanite::FPackedCluster::GetTangentPrecision () const inline
Definition at line 142 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::GetBits().
SetAttributeOffset()
void Nanite::FPackedCluster::SetAttributeOffset (uint32 Offset) inline
Definition at line 168 of file NaniteResources.h.
References AttributeOffset_BitsPerAttribute, and Nanite::SetBits().
SetBitsPerAttribute()
void Nanite::FPackedCluster::SetBitsPerAttribute (uint32 Bits) inline
Definition at line 169 of file NaniteResources.h.
References AttributeOffset_BitsPerAttribute, and Nanite::SetBits().
SetBitsPerIndex()
void Nanite::FPackedCluster::SetBitsPerIndex (uint32 BitsPerIndex) inline
Definition at line 157 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::SetBits().
SetBrickDataNum()
void Nanite::FPackedCluster::SetBrickDataNum (uint32 Num) inline
Definition at line 188 of file NaniteResources.h.
References BrickDataOffset_Num, Num, and Nanite::SetBits().
SetBrickDataOffset()
void Nanite::FPackedCluster::SetBrickDataOffset (uint32 Offset) inline
Definition at line 187 of file NaniteResources.h.
References BrickDataOffset_Num, and Nanite::SetBits().
SetColorBitsA()
void Nanite::FPackedCluster::SetColorBitsA (uint32 NumBits) inline
Definition at line 180 of file NaniteResources.h.
References ColorBits_GroupIndex, and Nanite::SetBits().
SetColorBitsB()
void Nanite::FPackedCluster::SetColorBitsB (uint32 NumBits) inline
Definition at line 179 of file NaniteResources.h.
References ColorBits_GroupIndex, and Nanite::SetBits().
SetColorBitsG()
void Nanite::FPackedCluster::SetColorBitsG (uint32 NumBits) inline
Definition at line 178 of file NaniteResources.h.
References ColorBits_GroupIndex, and Nanite::SetBits().
SetColorBitsR()
void Nanite::FPackedCluster::SetColorBitsR (uint32 NumBits) inline
Definition at line 177 of file NaniteResources.h.
References ColorBits_GroupIndex, and Nanite::SetBits().
SetColorMode()
void Nanite::FPackedCluster::SetColorMode (uint32 Mode) inline
Definition at line 175 of file NaniteResources.h.
References DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode, and Nanite::SetBits().
SetDecodeInfoOffset()
void Nanite::FPackedCluster::SetDecodeInfoOffset (uint32 Offset) inline
Definition at line 171 of file NaniteResources.h.
References DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode, and Nanite::SetBits().
SetExtendedDataNum()
void Nanite::FPackedCluster::SetExtendedDataNum (uint32 Num) inline
Definition at line 185 of file NaniteResources.h.
References ExtendedDataOffset_Num, Num, and Nanite::SetBits().
SetExtendedDataOffset()
void Nanite::FPackedCluster::SetExtendedDataOffset (uint32 Offset) inline
Definition at line 184 of file NaniteResources.h.
References ExtendedDataOffset_Num, and Nanite::SetBits().
SetFlags()
void Nanite::FPackedCluster::SetFlags (uint32 Flags) inline
Definition at line 165 of file NaniteResources.h.
References Flags, Flags_NumClusterBoneInfluences, and Nanite::SetBits().
SetGroupIndex()
void Nanite::FPackedCluster::SetGroupIndex (uint32 GroupIndex) inline
Definition at line 182 of file NaniteResources.h.
References ColorBits_GroupIndex, and Nanite::SetBits().
SetHasSkinning()
void Nanite::FPackedCluster::SetHasSkinning (bool bSkinning) inline
Definition at line 173 of file NaniteResources.h.
References DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode, and Nanite::SetBits().
SetHasTangents()
void Nanite::FPackedCluster::SetHasTangents (bool bHasTangents) inline
Definition at line 172 of file NaniteResources.h.
References DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode, and Nanite::SetBits().
SetIndexOffset()
void Nanite::FPackedCluster::SetIndexOffset (uint32 Offset) inline
Definition at line 155 of file NaniteResources.h.
References NumTris_IndexOffset, and Nanite::SetBits().
SetNormalPrecision()
void Nanite::FPackedCluster::SetNormalPrecision (uint32 NumBits) inline
Definition at line 162 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::SetBits().
SetNumClusterBoneInfluences()
void Nanite::FPackedCluster::SetNumClusterBoneInfluences (uint32 N) inline
Definition at line 166 of file NaniteResources.h.
References Flags_NumClusterBoneInfluences, and Nanite::SetBits().
SetNumTris()
void Nanite::FPackedCluster::SetNumTris (uint32 NumTris) inline
Definition at line 154 of file NaniteResources.h.
References NumTris_IndexOffset, and Nanite::SetBits().
SetNumUVs()
void Nanite::FPackedCluster::SetNumUVs (uint32 Num) inline
Definition at line 174 of file NaniteResources.h.
References DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode, Num, and Nanite::SetBits().
SetNumVerts()
void Nanite::FPackedCluster::SetNumVerts (uint32 NumVerts) inline
Definition at line 151 of file NaniteResources.h.
References NumVerts_PositionOffset, and Nanite::SetBits().
SetPosBitsX()
void Nanite::FPackedCluster::SetPosBitsX (uint32 NumBits) inline
Definition at line 159 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::SetBits().
SetPosBitsY()
void Nanite::FPackedCluster::SetPosBitsY (uint32 NumBits) inline
Definition at line 160 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::SetBits().
SetPosBitsZ()
void Nanite::FPackedCluster::SetPosBitsZ (uint32 NumBits) inline
Definition at line 161 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::SetBits().
SetPositionOffset()
void Nanite::FPackedCluster::SetPositionOffset (uint32 Offset) inline
Definition at line 152 of file NaniteResources.h.
References NumVerts_PositionOffset, and Nanite::SetBits().
SetPosPrecision()
void Nanite::FPackedCluster::SetPosPrecision (int32 Precision) inline
Definition at line 158 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::SetBits().
SetTangentPrecision()
void Nanite::FPackedCluster::SetTangentPrecision (uint32 NumBits) inline
Definition at line 163 of file NaniteResources.h.
References BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision, and Nanite::SetBits().
SetVertResourceBatchInfo()
void Nanite::FPackedCluster::SetVertResourceBatchInfo (TArray< uint32 > & BatchInfo, uint32 GpuPageOffset, uint32 NumMaterialRanges) inline
Definition at line 190 of file NaniteResources.h.
References check, TArray< InElementType, InAllocatorType >::GetData(), FMemory::Memcpy(), FMemory::Memzero(), TArray< InElementType, InAllocatorType >::Num(), and VertReuseBatchInfo.
Field Documentation
AttributeOffset_BitsPerAttribute
uint32 Nanite::FPackedCluster::AttributeOffset_BitsPerAttribute
Definition at line 117 of file NaniteResources.h.
Referenced by GetAttributeOffset(), GetBitsPerAttribute(), SetAttributeOffset(), and SetBitsPerAttribute().
BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision
uint32 Nanite::FPackedCluster::BitsPerIndex_PosPrecision_PosBits_NormalPrecision_TangentPrecision
Definition at line 105 of file NaniteResources.h.
Referenced by GetBitsPerIndex(), GetNormalPrecision(), GetPosBitsX(), GetPosBitsY(), GetPosBitsZ(), GetPosPrecision(), GetTangentPrecision(), SetBitsPerIndex(), SetNormalPrecision(), SetPosBitsX(), SetPosBitsY(), SetPosBitsZ(), SetPosPrecision(), and SetTangentPrecision().
BoxBoundsCenter
FVector3f Nanite::FPackedCluster::BoxBoundsCenter
Definition at line 110 of file NaniteResources.h.
BoxBoundsExtent
FVector3f Nanite::FPackedCluster::BoxBoundsExtent
Definition at line 113 of file NaniteResources.h.
BrickDataOffset_Num
uint32 Nanite::FPackedCluster::BrickDataOffset_Num
Definition at line 124 of file NaniteResources.h.
Referenced by SetBrickDataNum(), and SetBrickDataOffset().
ColorBits_GroupIndex
uint32 Nanite::FPackedCluster::ColorBits_GroupIndex
Definition at line 102 of file NaniteResources.h.
Referenced by SetColorBitsA(), SetColorBitsB(), SetColorBitsG(), SetColorBitsR(), and SetGroupIndex().
ColorMin
uint32 Nanite::FPackedCluster::ColorMin
Definition at line 101 of file NaniteResources.h.
DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode
uint32 Nanite::FPackedCluster::DecodeInfoOffset_HasTangents_Skinning_NumUVs_ColorMode
Definition at line 118 of file NaniteResources.h.
Referenced by SetColorMode(), SetDecodeInfoOffset(), SetHasSkinning(), SetHasTangents(), and SetNumUVs().
Dummy0
uint32 Nanite::FPackedCluster::Dummy0
Definition at line 125 of file NaniteResources.h.
Dummy1
uint32 Nanite::FPackedCluster::Dummy1
Definition at line 126 of file NaniteResources.h.
ExtendedDataOffset_Num
uint32 Nanite::FPackedCluster::ExtendedDataOffset_Num
Definition at line 123 of file NaniteResources.h.
Referenced by SetExtendedDataNum(), and SetExtendedDataOffset().
Flags_NumClusterBoneInfluences
uint32 Nanite::FPackedCluster::Flags_NumClusterBoneInfluences
Definition at line 114 of file NaniteResources.h.
Referenced by GetFlags(), GetNumClusterBoneInfluences(), SetFlags(), and SetNumClusterBoneInfluences().
LODBounds
FSphere3f Nanite::FPackedCluster::LODBounds
Definition at line 108 of file NaniteResources.h.
LODErrorAndEdgeLength
uint32 Nanite::FPackedCluster::LODErrorAndEdgeLength
Definition at line 111 of file NaniteResources.h.
NumTris_IndexOffset
uint32 Nanite::FPackedCluster::NumTris_IndexOffset
Definition at line 100 of file NaniteResources.h.
Referenced by GetIndexOffset(), GetNumTris(), SetIndexOffset(), and SetNumTris().
NumVerts_PositionOffset
uint32 Nanite::FPackedCluster::NumVerts_PositionOffset
Definition at line 99 of file NaniteResources.h.
Referenced by GetNumVerts(), GetPositionOffset(), SetNumVerts(), and SetPositionOffset().
PackedMaterialInfo
uint32 Nanite::FPackedCluster::PackedMaterialInfo
Definition at line 121 of file NaniteResources.h.
PosStart
FIntVector Nanite::FPackedCluster::PosStart
Definition at line 104 of file NaniteResources.h.
UVBitOffsets
uint32 Nanite::FPackedCluster::UVBitOffsets
Definition at line 119 of file NaniteResources.h.
VertReuseBatchInfo
uint32 Nanite::FPackedCluster::VertReuseBatchInfo[4]
Definition at line 128 of file NaniteResources.h.
Referenced by SetVertResourceBatchInfo().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Rendering/NaniteResources.h