Unreal Engine 5.6 C++ API: FRigVMTemplateArgument Struct Reference
FRigVMTemplateArgument Struct Reference
The template argument represents a single parameter in a function call and all of its possible types.
#include "RigVMTemplate.h"
Data Structures
struct CategoryViews
Public Types
enum EArrayType {
EArrayType_SingleValue , EArrayType_ArrayValue , EArrayType_ArrayArrayValue , EArrayType_Mixed ,
EArrayType_Invalid
}
enum ETypeCategory : uint8 {
ETypeCategory_Execute , ETypeCategory_SingleAnyValue , ETypeCategory_ArrayAnyValue , ETypeCategory_ArrayArrayAnyValue ,
ETypeCategory_SingleSimpleValue , ETypeCategory_ArraySimpleValue , ETypeCategory_ArrayArraySimpleValue , ETypeCategory_SingleMathStructValue ,
ETypeCategory_ArrayMathStructValue , ETypeCategory_ArrayArrayMathStructValue , ETypeCategory_SingleScriptStructValue , ETypeCategory_ArrayScriptStructValue ,
ETypeCategory_ArrayArrayScriptStructValue , ETypeCategory_SingleEnumValue , ETypeCategory_ArrayEnumValue , ETypeCategory_ArrayArrayEnumValue ,
ETypeCategory_SingleObjectValue , ETypeCategory_ArrayObjectValue , ETypeCategory_ArrayArrayObjectValue , ETypeCategory_Invalid
}
Public Member Functions
RIGVM_API FRigVMTemplateArgument ()
RIGVM_API FRigVMTemplateArgument (const FName &InName, ERigVMPinDirection InDirection)
RIGVM_API FRigVMTemplateArgument (const FName &InName, ERigVMPinDirection InDirection, const TArray< ETypeCategory > &InTypeCategories, TFunction< bool(const TRigVMTypeIndex &)> InFilterType=nullptr)
RIGVM_API FRigVMTemplateArgument (const FName &InName, ERigVMPinDirection InDirection, const TArray< TRigVMTypeIndex > &InTypeIndices)
RIGVM_API FRigVMTemplateArgument (const FName &InName, ERigVMPinDirection InDirection, TRigVMTypeIndex InType)
RIGVM_API void AddTypeIndex (const TRigVMTypeIndex InTypeIndex)
DECLARE_DELEGATE_RetVal_OneParam (bool, FTypeFilter, const TRigVMTypeIndex &)
RIGVM_API int32 FindTypeIndex (const TRigVMTypeIndex InTypeIndex) const
RIGVM_API void ForEachType (TFunction< bool(const TRigVMTypeIndex InType)> &&InCallback) const
RIGVM_API void GetAllTypes (TArray< TRigVMTypeIndex > &OutTypes, const bool bLockRegistry=true) const
RIGVM_API void GetAllTypes_NoLock (TArray< TRigVMTypeIndex > &OutTypes) const
RIGVM_API EArrayType GetArrayType (const bool bLockRegistry=true) const
RIGVM_API EArrayType GetArrayType_NoLock () const
ERigVMPinDirection GetDirection () const
const FName & GetName () const
RIGVM_API int32 GetNumTypes () const
RIGVM_API int32 GetNumTypes_NoLock () const
RIGVM_API const TArray< int32 > & GetPermutations (const TRigVMTypeIndex InType, bool bLockRegistry=true) const
RIGVM_API const TArray< int32 > & GetPermutations_NoLock (const TRigVMTypeIndex InType) const
RIGVM_API TArray< TRigVMTypeIndex > GetSupportedTypeIndices (const TArray< int32 > &InPermutationIndices=TArray< int32 >()) const
RIGVM_API TArray< FString > GetSupportedTypeStrings (const TArray< int32 > &InPermutationIndices=TArray< int32 >()) const
RIGVM_API TRigVMTypeIndex GetTypeIndex (const int32 InIndex, const bool bLockRegistry=true) const
RIGVM_API TRigVMTypeIndex GetTypeIndex_NoLock (const int32 InIndex) const
template<typename Predicate>
int32 IndexOfByPredicate (Predicate Pred) const
RIGVM_API void InvalidatePermutations (const TRigVMTypeIndex InType)
RIGVM_API bool IsExecute () const
RIGVM_API bool IsExecute_NoLock (const FRigVMRegistry_NoLock &InRegistry) const
RIGVM_API bool IsSingleton (const TArray< int32 > &InPermutationIndices=TArray< int32 >(), const bool bLockRegistry=true) const
RIGVM_API bool IsSingleton_NoLock (const TArray< int32 > &InPermutationIndices=TArray< int32 >()) const
RIGVM_API void RemoveType (const int32 InIndex)
RIGVM_API bool SupportsTypeIndex (TRigVMTypeIndex InTypeIndex, TRigVMTypeIndex *OutTypeIndex=nullptr, const bool bLockRegistry=true) const
RIGVM_API bool SupportsTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex, TRigVMTypeIndex *OutTypeIndex=nullptr) const
RIGVM_API TOptional< TRigVMTypeIndex > TryToGetTypeIndex (const int32 InIndex, const bool bLockRegistry=true) const
RIGVM_API TOptional< TRigVMTypeIndex > TryToGetTypeIndex_NoLock (const int32 InIndex) const
Protected Member Functions
RIGVM_API FRigVMTemplateArgument (FProperty *InProperty, FRigVMRegistry_NoLock &InRegistry)
RIGVM_API void EnsureValidExecuteType_NoLock (FRigVMRegistry_NoLock &InRegistry)
RIGVM_API void UpdateTypeToPermutationsSlow ()
Static Protected Member Functions
static RIGVM_API FRigVMTemplateArgument Make (FProperty *InProperty)
static RIGVM_API FRigVMTemplateArgument Make_NoLock (FProperty *InProperty)
static RIGVM_API FRigVMTemplateArgument Make_NoLock (FProperty *InProperty, FRigVMRegistry_NoLock &InRegistry)
Protected Attributes
bool bUseCategories = false
TOptional< EArrayType > CachedArrayType
ERigVMPinDirection Direction = ERigVMPinDirection::IO
TFunction< bool(const TRigVMTypeIndex &)> FilterType
int32 Index = INDEX_NONE
FName Name = NAME_None
TArray< ETypeCategory > TypeCategories
TArray< TRigVMTypeIndex > TypeIndices
TMap< TRigVMTypeIndex, TArray< int32 > > TypeToPermutations
Friends
struct FRigVMDispatchFactory
struct FRigVMRegistry_NoLock
struct FRigVMStructUpgradeInfo
struct FRigVMTemplate
class FRigVMTypeCacheScope_NoLock
RIGVM_API friend uint32 GetTypeHash_NoLock (const FRigVMTemplateArgument &InArgument)
class URigVMCompiler
class URigVMController
Detailed Description
The template argument represents a single parameter in a function call and all of its possible types.
Definition at line 157 of file RigVMTemplate.h.
Member Enumeration Documentation
EArrayType
enum FRigVMTemplateArgument::EArrayType
Enumerator
EArrayType_SingleValue
EArrayType_ArrayValue
EArrayType_ArrayArrayValue
EArrayType_Mixed
EArrayType_Invalid
Definition at line 161 of file RigVMTemplate.h.
ETypeCategory
enum FRigVMTemplateArgument::ETypeCategory : uint8
Enumerator
ETypeCategory_Execute
ETypeCategory_SingleAnyValue
ETypeCategory_ArrayAnyValue
ETypeCategory_ArrayArrayAnyValue
ETypeCategory_SingleSimpleValue
ETypeCategory_ArraySimpleValue
ETypeCategory_ArrayArraySimpleValue
ETypeCategory_SingleMathStructValue
ETypeCategory_ArrayMathStructValue
ETypeCategory_ArrayArrayMathStructValue
ETypeCategory_SingleScriptStructValue
ETypeCategory_ArrayScriptStructValue
ETypeCategory_ArrayArrayScriptStructValue
ETypeCategory_SingleEnumValue
ETypeCategory_ArrayEnumValue
ETypeCategory_ArrayArrayEnumValue
ETypeCategory_SingleObjectValue
ETypeCategory_ArrayObjectValue
ETypeCategory_ArrayArrayObjectValue
ETypeCategory_Invalid
Definition at line 170 of file RigVMTemplate.h.
Constructor & Destructor Documentation
FRigVMTemplateArgument() [1/6]
RIGVM_API FRigVMTemplateArgument::FRigVMTemplateArgument ()
Referenced by GetTypeHash_NoLock, Make(), Make_NoLock(), and Make_NoLock().
FRigVMTemplateArgument() [2/6]
RIGVM_API FRigVMTemplateArgument::FRigVMTemplateArgument (const FName & InName, ERigVMPinDirection InDirection)
References InName.
FRigVMTemplateArgument() [3/6]
RIGVM_API FRigVMTemplateArgument::FRigVMTemplateArgument (const FName & InName, ERigVMPinDirection InDirection, TRigVMTypeIndex InType)
References InName.
FRigVMTemplateArgument() [4/6]
RIGVM_API FRigVMTemplateArgument::FRigVMTemplateArgument (const FName & InName, ERigVMPinDirection InDirection, const TArray< TRigVMTypeIndex > & InTypeIndices)
References InName.
FRigVMTemplateArgument() [5/6]
RIGVM_API FRigVMTemplateArgument::FRigVMTemplateArgument (const FName & InName, ERigVMPinDirection InDirection, const TArray< ETypeCategory > & InTypeCategories, TFunction< bool(const TRigVMTypeIndex &)> InFilterType = nullptr)
References InName.
FRigVMTemplateArgument() [6/6]
RIGVM_API FRigVMTemplateArgument::FRigVMTemplateArgument (FProperty * InProperty, FRigVMRegistry_NoLock & InRegistry) protected
References FRigVMRegistry_NoLock.
Member Function Documentation
AddTypeIndex()
RIGVM_API void FRigVMTemplateArgument::AddTypeIndex (const TRigVMTypeIndex InTypeIndex)
DECLARE_DELEGATE_RetVal_OneParam()
FRigVMTemplateArgument::DECLARE_DELEGATE_RetVal_OneParam (bool , FTypeFilter , const TRigVMTypeIndex &)
EnsureValidExecuteType_NoLock()
RIGVM_API void FRigVMTemplateArgument::EnsureValidExecuteType_NoLock (FRigVMRegistry_NoLock & InRegistry) protected
References FRigVMRegistry_NoLock.
FindTypeIndex()
RIGVM_API int32 FRigVMTemplateArgument::FindTypeIndex (const TRigVMTypeIndex InTypeIndex) const
ForEachType()
RIGVM_API void FRigVMTemplateArgument::ForEachType (TFunction< bool(const TRigVMTypeIndex InType)> && InCallback) const
GetAllTypes()
RIGVM_API void FRigVMTemplateArgument::GetAllTypes (TArray< TRigVMTypeIndex > & OutTypes, const bool bLockRegistry = true) const
GetAllTypes_NoLock()
RIGVM_API void FRigVMTemplateArgument::GetAllTypes_NoLock (TArray< TRigVMTypeIndex > & OutTypes) const
GetArrayType()
RIGVM_API EArrayType FRigVMTemplateArgument::GetArrayType (const bool bLockRegistry = true) const
GetArrayType_NoLock()
RIGVM_API EArrayType FRigVMTemplateArgument::GetArrayType_NoLock () const
GetDirection()
ERigVMPinDirection FRigVMTemplateArgument::GetDirection () const inline
Definition at line 206 of file RigVMTemplate.h.
References Direction.
GetName()
const FName & FRigVMTemplateArgument::GetName () const inline
Definition at line 203 of file RigVMTemplate.h.
References Name.
GetNumTypes()
RIGVM_API int32 FRigVMTemplateArgument::GetNumTypes () const
GetNumTypes_NoLock()
RIGVM_API int32 FRigVMTemplateArgument::GetNumTypes_NoLock () const
GetPermutations()
RIGVM_API const TArray< int32 > & FRigVMTemplateArgument::GetPermutations (const TRigVMTypeIndex InType, bool bLockRegistry = true) const
GetPermutations_NoLock()
RIGVM_API const TArray< int32 > & FRigVMTemplateArgument::GetPermutations_NoLock (const TRigVMTypeIndex InType) const
GetSupportedTypeIndices()
RIGVM_API TArray< TRigVMTypeIndex > FRigVMTemplateArgument::GetSupportedTypeIndices (const TArray< int32 > & InPermutationIndices = TArray< int32 >()) const
GetSupportedTypeStrings()
RIGVM_API TArray< FString > FRigVMTemplateArgument::GetSupportedTypeStrings (const TArray< int32 > & InPermutationIndices = TArray< int32 >()) const
GetTypeIndex()
RIGVM_API TRigVMTypeIndex FRigVMTemplateArgument::GetTypeIndex (const int32 InIndex, const bool bLockRegistry = true) const
GetTypeIndex_NoLock()
RIGVM_API TRigVMTypeIndex FRigVMTemplateArgument::GetTypeIndex_NoLock (const int32 InIndex) const
IndexOfByPredicate()
template<typename Predicate> int32 FRigVMTemplateArgument::IndexOfByPredicate (Predicate Pred) const inline
Definition at line 230 of file RigVMTemplate.h.
References bUseCategories, FilterType, FRigVMTemplateArgument::CategoryViews::ForEachType(), INDEX_NONE, FRigVMTemplateArgument::CategoryViews::IndexOfByPredicate(), Predicate, TypeCategories, and TypeIndices.
InvalidatePermutations()
RIGVM_API void FRigVMTemplateArgument::InvalidatePermutations (const TRigVMTypeIndex InType)
IsExecute()
RIGVM_API bool FRigVMTemplateArgument::IsExecute () const
IsExecute_NoLock()
RIGVM_API bool FRigVMTemplateArgument::IsExecute_NoLock (const FRigVMRegistry_NoLock & InRegistry) const
References FRigVMRegistry_NoLock.
IsSingleton()
RIGVM_API bool FRigVMTemplateArgument::IsSingleton (const TArray< int32 > & InPermutationIndices = TArray< int32 >(), const bool bLockRegistry = true) const
IsSingleton_NoLock()
RIGVM_API bool FRigVMTemplateArgument::IsSingleton_NoLock (const TArray< int32 > & InPermutationIndices = TArray< int32 >()) const
Make()
RIGVM_API FRigVMTemplateArgument FRigVMTemplateArgument::Make (FProperty * InProperty) static protected
References FRigVMTemplateArgument().
Make_NoLock() [1/2]
RIGVM_API FRigVMTemplateArgument FRigVMTemplateArgument::Make_NoLock (FProperty * InProperty) static protected
References FRigVMTemplateArgument().
Make_NoLock() [2/2]
RIGVM_API FRigVMTemplateArgument FRigVMTemplateArgument::Make_NoLock (FProperty * InProperty, FRigVMRegistry_NoLock & InRegistry) static protected
References FRigVMTemplateArgument(), and FRigVMRegistry_NoLock.
RemoveType()
RIGVM_API void FRigVMTemplateArgument::RemoveType (const int32 InIndex)
SupportsTypeIndex()
RIGVM_API bool FRigVMTemplateArgument::SupportsTypeIndex (TRigVMTypeIndex InTypeIndex, TRigVMTypeIndex * OutTypeIndex = nullptr, const bool bLockRegistry = true) const
SupportsTypeIndex_NoLock()
RIGVM_API bool FRigVMTemplateArgument::SupportsTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex, TRigVMTypeIndex * OutTypeIndex = nullptr) const
TryToGetTypeIndex()
RIGVM_API TOptional< TRigVMTypeIndex > FRigVMTemplateArgument::TryToGetTypeIndex (const int32 InIndex, const bool bLockRegistry = true) const
TryToGetTypeIndex_NoLock()
RIGVM_API TOptional< TRigVMTypeIndex > FRigVMTemplateArgument::TryToGetTypeIndex_NoLock (const int32 InIndex) const
UpdateTypeToPermutationsSlow()
RIGVM_API void FRigVMTemplateArgument::UpdateTypeToPermutationsSlow () protected
Friends And Related Symbol Documentation
FRigVMDispatchFactory
friend struct FRigVMDispatchFactory friend
Definition at line 322 of file RigVMTemplate.h.
References FRigVMDispatchFactory.
Referenced by FRigVMDispatchFactory.
FRigVMRegistry_NoLock
friend struct FRigVMRegistry_NoLock friend
Definition at line 324 of file RigVMTemplate.h.
References FRigVMRegistry_NoLock.
Referenced by FRigVMTemplateArgument(), EnsureValidExecuteType_NoLock(), FRigVMRegistry_NoLock, IsExecute_NoLock(), and Make_NoLock().
FRigVMStructUpgradeInfo
friend struct FRigVMStructUpgradeInfo friend
Definition at line 325 of file RigVMTemplate.h.
References FRigVMStructUpgradeInfo.
Referenced by FRigVMStructUpgradeInfo.
FRigVMTemplate
friend struct FRigVMTemplate friend
Definition at line 321 of file RigVMTemplate.h.
References FRigVMTemplate.
Referenced by FRigVMTemplate.
FRigVMTypeCacheScope_NoLock
friend class FRigVMTypeCacheScope_NoLock friend
Definition at line 327 of file RigVMTemplate.h.
References FRigVMTypeCacheScope_NoLock.
Referenced by FRigVMTypeCacheScope_NoLock.
GetTypeHash_NoLock
RIGVM_API friend uint32 GetTypeHash_NoLock (const FRigVMTemplateArgument & InArgument) friend
References FRigVMTemplateArgument().
URigVMCompiler
friend class URigVMCompiler friend
Definition at line 326 of file RigVMTemplate.h.
References URigVMCompiler.
Referenced by URigVMCompiler.
URigVMController
friend class URigVMController friend
Definition at line 323 of file RigVMTemplate.h.
References URigVMController.
Referenced by URigVMController.
Field Documentation
bUseCategories
bool FRigVMTemplateArgument::bUseCategories = false protected
Definition at line 300 of file RigVMTemplate.h.
Referenced by IndexOfByPredicate().
CachedArrayType
TOptional<EArrayType> FRigVMTemplateArgument::CachedArrayType mutable protected
Definition at line 303 of file RigVMTemplate.h.
Direction
ERigVMPinDirection FRigVMTemplateArgument::Direction = ERigVMPinDirection::IO protected
Definition at line 293 of file RigVMTemplate.h.
Referenced by GetDirection().
FilterType
TFunction<bool(const TRigVMTypeIndex&)> FRigVMTemplateArgument::FilterType protected
Definition at line 302 of file RigVMTemplate.h.
Referenced by IndexOfByPredicate().
Index
int32 FRigVMTemplateArgument::Index = INDEX_NONE protected
Definition at line 291 of file RigVMTemplate.h.
Name
FName FRigVMTemplateArgument::Name = NAME_None protected
Definition at line 292 of file RigVMTemplate.h.
Referenced by GetName().
TypeCategories
TArray<ETypeCategory> FRigVMTemplateArgument::TypeCategories protected
Definition at line 301 of file RigVMTemplate.h.
Referenced by IndexOfByPredicate().
TypeIndices
TArray<TRigVMTypeIndex> FRigVMTemplateArgument::TypeIndices protected
Definition at line 295 of file RigVMTemplate.h.
Referenced by IndexOfByPredicate().
TypeToPermutations
TMap<TRigVMTypeIndex, TArray<int32> > FRigVMTemplateArgument::TypeToPermutations mutable protected
Definition at line 297 of file RigVMTemplate.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMTemplate.h