Unreal Engine 5.6 C++ API: FAudioBufferConfig Struct Reference
FAudioBufferConfig Struct Reference
#include "AudioBufferConfig.h"
Public Member Functions
HARMONIXDSP_API FAudioBufferConfig ()
HARMONIXDSP_API FAudioBufferConfig (EAudioBufferChannelLayout InChannelLayout, int32 InNumChannels, int32 InNumFrames, float InSampleRate=0.0f, bool InInterleaved=false)
HARMONIXDSP_API FAudioBufferConfig (EAudioBufferChannelLayout InChannelLayout, int32 InNumFrames, float InSampleRate=0.0f, bool InInterleaved=false)
HARMONIXDSP_API FAudioBufferConfig (int32 InNumChannels, int32 InNumFrames, float InSampleRate=0.0f, bool InInterleaved=false)
FORCEINLINE EAudioBufferChannelLayout GetChannelLayout () const
FORCEINLINE uint32 GetChannelMask () const
HARMONIXDSP_API FAudioBufferConfig GetDeinterleavedConfig () const
HARMONIXDSP_API FAudioBufferConfig GetInterleavedConfig () const
FORCEINLINE bool GetIsInterleaved () const
FORCEINLINE int32 GetNumChannels () const
FORCEINLINE int32 GetNumFrames () const
HARMONIXDSP_API int32 GetNumTotalSamples () const
HARMONIXDSP_API float GetSampleRate () const
HARMONIXDSP_API bool operator== (const FAudioBufferConfig &) const
HARMONIXDSP_API void SetChannelLayout (EAudioBufferChannelLayout InChannelLayout)
HARMONIXDSP_API void SetChannelMask (uint32 InChannelMask)
HARMONIXDSP_API void SetNumChannels (int32 InNumChannels)
HARMONIXDSP_API void SetNumFrames (int32 InNumFrames)
HARMONIXDSP_API void SetSampleRate (float InSamplesPerSecond)
Static Public Attributes
static const uint32 kMaxAudioBufferChannels = 8
Private Attributes
EAudioBufferChannelLayout ChannelLayout
uint32 ChannelMask
bool Interleaved
int32 NumChannels
int32 NumFrames
float SampleRate
Detailed Description
Definition at line 17 of file AudioBufferConfig.h.
Constructor & Destructor Documentation
FAudioBufferConfig() [1/4]
HARMONIXDSP_API FAudioBufferConfig::FAudioBufferConfig ()
References UE_API.
Referenced by GetDeinterleavedConfig(), GetInterleavedConfig(), and operator==().
FAudioBufferConfig() [2/4]
HARMONIXDSP_API FAudioBufferConfig::FAudioBufferConfig (int32 InNumChannels, int32 InNumFrames, float InSampleRate = 0.0f, bool InInterleaved = false)
References UE_API.
FAudioBufferConfig() [3/4]
HARMONIXDSP_API FAudioBufferConfig::FAudioBufferConfig (EAudioBufferChannelLayout InChannelLayout, int32 InNumFrames, float InSampleRate = 0.0f, bool InInterleaved = false)
References UE_API.
FAudioBufferConfig() [4/4]
HARMONIXDSP_API FAudioBufferConfig::FAudioBufferConfig (EAudioBufferChannelLayout InChannelLayout, int32 InNumChannels, int32 InNumFrames, float InSampleRate = 0.0f, bool InInterleaved = false)
References UE_API.
Member Function Documentation
GetChannelLayout()
FORCEINLINE EAudioBufferChannelLayout FAudioBufferConfig::GetChannelLayout () const inline
Definition at line 43 of file AudioBufferConfig.h.
References ChannelLayout, and FORCEINLINE.
Referenced by TAudioBuffer< DataType >::Configure().
GetChannelMask()
FORCEINLINE uint32 FAudioBufferConfig::GetChannelMask () const inline
Definition at line 46 of file AudioBufferConfig.h.
References ChannelMask, and FORCEINLINE.
GetDeinterleavedConfig()
HARMONIXDSP_API FAudioBufferConfig FAudioBufferConfig::GetDeinterleavedConfig () const
References FAudioBufferConfig(), and UE_API.
GetInterleavedConfig()
HARMONIXDSP_API FAudioBufferConfig FAudioBufferConfig::GetInterleavedConfig () const
References FAudioBufferConfig(), and UE_API.
GetIsInterleaved()
FORCEINLINE bool FAudioBufferConfig::GetIsInterleaved () const inline
Definition at line 41 of file AudioBufferConfig.h.
References FORCEINLINE, and Interleaved.
GetNumChannels()
FORCEINLINE int32 FAudioBufferConfig::GetNumChannels () const inline
Definition at line 31 of file AudioBufferConfig.h.
References FORCEINLINE, and NumChannels.
Referenced by TAudioBuffer< DataType >::AliasChannelDataPointers(), and TAudioBuffer< DataType >::Configure().
GetNumFrames()
FORCEINLINE int32 FAudioBufferConfig::GetNumFrames () const inline
Definition at line 34 of file AudioBufferConfig.h.
References FORCEINLINE, and NumFrames.
Referenced by TAudioBuffer< DataType >::AliasChannelDataPointers(), and TAudioBuffer< DataType >::Configure().
GetNumTotalSamples()
HARMONIXDSP_API int32 FAudioBufferConfig::GetNumTotalSamples () const
References UE_API.
GetSampleRate()
HARMONIXDSP_API float FAudioBufferConfig::GetSampleRate () const
References UE_API.
operator==()
HARMONIXDSP_API bool FAudioBufferConfig::operator== (const FAudioBufferConfig &) const
References FAudioBufferConfig(), and UE_API.
SetChannelLayout()
HARMONIXDSP_API void FAudioBufferConfig::SetChannelLayout (EAudioBufferChannelLayout InChannelLayout)
References UE_API.
SetChannelMask()
HARMONIXDSP_API void FAudioBufferConfig::SetChannelMask (uint32 InChannelMask)
References UE_API.
SetNumChannels()
HARMONIXDSP_API void FAudioBufferConfig::SetNumChannels (int32 InNumChannels)
References UE_API.
SetNumFrames()
HARMONIXDSP_API void FAudioBufferConfig::SetNumFrames (int32 InNumFrames)
References UE_API.
SetSampleRate()
HARMONIXDSP_API void FAudioBufferConfig::SetSampleRate (float InSamplesPerSecond)
References UE_API.
Field Documentation
ChannelLayout
EAudioBufferChannelLayout FAudioBufferConfig::ChannelLayout private
Definition at line 57 of file AudioBufferConfig.h.
Referenced by GetChannelLayout().
ChannelMask
uint32 FAudioBufferConfig::ChannelMask private
Definition at line 55 of file AudioBufferConfig.h.
Referenced by GetChannelMask().
Interleaved
bool FAudioBufferConfig::Interleaved private
Definition at line 56 of file AudioBufferConfig.h.
Referenced by GetIsInterleaved().
kMaxAudioBufferChannels
const uint32 FAudioBufferConfig::kMaxAudioBufferChannels = 8 static
Definition at line 20 of file AudioBufferConfig.h.
Referenced by TAudioBuffer< DataType >::Configure(), TAudioBuffer< DataType >::Initialize(), and TAudioBuffer< DataType >::SetNumValidChannels().
NumChannels
int32 FAudioBufferConfig::NumChannels private
Definition at line 53 of file AudioBufferConfig.h.
Referenced by GetNumChannels().
NumFrames
int32 FAudioBufferConfig::NumFrames private
Definition at line 54 of file AudioBufferConfig.h.
Referenced by GetNumFrames().
SampleRate
float FAudioBufferConfig::SampleRate private
Definition at line 52 of file AudioBufferConfig.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixDsp/Public/HarmonixDsp/AudioBufferConfig.h