Unreal Engine 5.6 C++ API: FFieldRemapInfo Struct Reference
FFieldRemapInfo Struct Reference
Helper struct to allow us to redirect properties and functions through renames and additionally between classes if necessary.
#include "MemberReference.h"
Public Member Functions
FFieldRemapInfo ()
bool operator== (const FFieldRemapInfo &Other) const
Data Fields
FName FieldClass
The new name of the field's outer class if different from its original location, or NAME_None if it hasn't moved.
FName FieldName
The new name of the field after being renamed.
Friends
uint32 GetTypeHash (const FFieldRemapInfo &RemapInfo)
Detailed Description
Helper struct to allow us to redirect properties and functions through renames and additionally between classes if necessary.
Definition at line 18 of file MemberReference.h.
Constructor & Destructor Documentation
FFieldRemapInfo()
FFieldRemapInfo::FFieldRemapInfo () inline
Definition at line 36 of file MemberReference.h.
References FieldClass, and FieldName.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
operator==()
bool FFieldRemapInfo::operator== (const FFieldRemapInfo & Other) const inline
Definition at line 26 of file MemberReference.h.
References FFieldRemapInfo(), FieldClass, FieldName, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FFieldRemapInfo & RemapInfo) friend
Definition at line 31 of file MemberReference.h.
References FFieldRemapInfo(), FieldClass, FieldName, and GetTypeHash.
Referenced by GetTypeHash.
Field Documentation
FieldClass
FName FFieldRemapInfo::FieldClass
The new name of the field's outer class if different from its original location, or NAME_None if it hasn't moved.
Definition at line 24 of file MemberReference.h.
Referenced by FFieldRemapInfo(), GetTypeHash, and operator==().
FieldName
FName FFieldRemapInfo::FieldName
The new name of the field after being renamed.
Definition at line 21 of file MemberReference.h.
Referenced by FFieldRemapInfo(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Engine/MemberReference.h