Unreal Engine 5.6 C++ API: FArchiveState Struct Reference
FArchiveState Struct Reference abstract
#include "Archive.h"
Data Structures
struct FFastPathLoadBuffer
Public Member Functions
virtual bool AtEnd ()
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax)
Called to get the computed size from a size-detecting archive after it has finished serializing.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
virtual uint32 EngineNetVer () const
Returns the engine-global network protocol version for this archive.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual uint32 GameNetVer () const
Returns the game-specific network protocol version for this archive.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj)
Called to retrieve the archetype from the event driven loader.
virtual FString GetArchiveName () const
Returns the name of the Archive.
FORCEINLINE FArchiveCookContext * GetCookContext ()
virtual const FCustomVersionContainer & GetCustomVersions () const
Gets the custom version numbers for this archive.
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
virtual FArchiveState & GetInnermostState ()
Returns lowest level archive state, proxy archives will override this.
virtual FLinker * GetLinker ()
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FObjectSavePackageSerializeContext * GetSavePackageSerializeContext ()
Return the API object used to record extra data for SavePackage calls (e.g.
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void Reset ()
Resets all of the base archive members.
virtual void ResetCustomVersions ()
Resets the custom version numbers for this archive.
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetCustomVersions (const FCustomVersionContainer &CustomVersionContainer)
Sets the custom version numbers for this archive.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags)
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
virtual void SetEngineNetVer (const uint32 InEngineNetVer)
Sets the archive engine network version.
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetFilterEditorOnly (bool InFilterEditorOnly)
Sets a flag indicating that this archive needs to filter editor-only content.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetGameNetVer (const uint32 InGameNetVer)
Sets the archive game network version.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
virtual void SetSerializedProperty (FProperty *InProperty)
Overrides the property that is currently being serialized.
virtual void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr)
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned)
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
virtual bool ShouldSkipProperty (const FProperty *InProperty) const
Checks whether the archive wants to skip the property independent of the other flags.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
virtual int64 Tell ()
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
virtual int64 TotalSize ()
Returns total size of the backing data storage.
UE_DEPRECATED (5.5, "GetSerializeContext is not supported. Use FUObjectThreadContext::Get().GetSerializeContext().") virtual FUObjectSerializeContext *GetSerializeContext()
Gets the current UObject serialization context for this archive.
UE_DEPRECATED (5.5, "SetSerializeContext is not supported. Remove calls to it.") virtual void SetSerializeContext(FUObjectSerializeContext *InLoadContext)
Sets the current UObject serialization context for this archive.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData.") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
virtual bool UseToResolveEnumerators () const
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Data Fields
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Protected Member Functions
void CopyTrivialFArchiveStatusMembers (const FArchiveState &ArchiveStatusToCopy)
Copies all of the members except CustomVersionContainer.
Static Protected Member Functions
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Protected Attributes
FEngineVersionBase ArEngineVer
Holds the engine version.
uint8 ArForceUnicode: 1
Whether this archive wants to always save strings in UTF16 format even if they are ANSI characters.
uint8 ArIsLoading: 1
Whether this archive is for loading data.
uint8 ArIsLoadingFromCookedPackage: 1
Whether this archive is loading from a cooked package.
uint8 ArIsPersistent: 1
Whether this archive saves to persistent storage.
uint8 ArIsSaving: 1
Whether this archive is for saving data.
uint8 ArIsTextFormat: 1
Whether this archive serializes to a text format.
uint8 ArIsTransacting: 1
Whether archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
int32 ArLicenseeUEVer
Holds the archive version for licensees.
FPackageFileVersion ArUEVer
Holds the archive version.
uint8 ArUseUnversionedPropertySerialization: 1
Whether tagged property serialization is replaced by faster unversioned serialization.
uint8 ArWantBinaryPropertySerialization: 1
Whether this archive wants properties to be serialized in binary form instead of tagged.
bool bCustomVersionsAreReset
Indicates if the custom versions container is in a 'reset' state.
FCustomVersionContainer * CustomVersionContainer = nullptr
All the custom versions stored in the archive.
FArchiveSavePackageData * SavePackageData = nullptr
Provider of data and API specific to UPackage::Save2.
FProperty * SerializedProperty
Holds the pointer to the property that is currently being serialized.
FArchiveSerializedPropertyChain * SerializedPropertyChain
Holds the chain of properties that are currently being serialized.
Private Member Functions
FArchiveState ()
FArchiveState (const FArchiveState &)
Copy constructor.
virtual ~FArchiveState ()=0
template<typename T>
void ForEachState (T Func)
FArchiveState & operator= (const FArchiveState &ArchiveToCopy)
Copy assignment operator.
Private Attributes
uint8 ArIsCriticalError: 1
Whether this archive contains critical errors that cannot be recovered from.
uint8 ArIsError: 1
Whether this archive contains errors, which means that further serialization is generally not safe.
uint8 ArShouldSkipCompilingAssets: 1
Whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
uint8 ArShouldSkipUpdateCustomVersion: 1
If true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
FArchiveState * NextProxy = nullptr
Linked list to all proxies.
Friends
class FArchive
Detailed Description
Definition at line 69 of file Archive.h.
Constructor & Destructor Documentation
FArchiveState() [1/2]
FArchiveState::FArchiveState () private
Referenced by FArchiveState(), CopyTrivialFArchiveStatusMembers(), FArchive::GetArchiveState(), FArchive::GetArchiveState(), GetInnermostState(), LinkProxy(), operator=(), SetArchiveState(), and UnlinkProxy().
FArchiveState() [2/2]
FArchiveState::FArchiveState (const FArchiveState &) private
Copy constructor.
References FArchiveState().
~FArchiveState()
virtual FArchiveState::~FArchiveState () private pure virtual
Member Function Documentation
AtEnd()
virtual bool FArchiveState::AtEnd () inline virtual
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
Reimplemented in FArchive, FArchiveProxy, FBitReader, FBufferReaderBase, FBufferWriter, and FBulkDataWriter.
Definition at line 161 of file Archive.h.
References INDEX_NONE, Tell(), and TotalSize().
ClearError()
void FArchiveState::ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
ContainsCode()
FORCEINLINE bool FArchiveState::ContainsCode () const inline
Returns true if this archive contains native or generated code.
Definition at line 379 of file Archive.h.
References ArContainsCode, and FORCEINLINE.
ContainsMap()
FORCEINLINE bool FArchiveState::ContainsMap () const inline
Returns true if this archive contains a ULevel or UWorld object.
Definition at line 385 of file Archive.h.
References ArContainsMap, and FORCEINLINE.
CookingTarget()
FORCEINLINE const ITargetPlatform * FArchiveState::CookingTarget () const inline
Returns the cooking target platform.
Returns null if not being serialized from Savepackage, or if it is an editor save rather than a cook save.
Returns
Target platform.
Definition at line 675 of file Archive.h.
References FORCEINLINE, and SavePackageData.
CopyTrivialFArchiveStatusMembers()
void FArchiveState::CopyTrivialFArchiveStatusMembers (const FArchiveState & ArchiveStatusToCopy) protected
Copies all of the members except CustomVersionContainer.
References FArchiveState().
CountBytes()
virtual void FArchiveState::CountBytes (SIZE_T InNum, SIZE_T InMax) inline virtual
Called to get the computed size from a size-detecting archive after it has finished serializing.
Reimplemented in FArchive, FArchiveCountMem, and FArchiveProxy.
Definition at line 125 of file Archive.h.
CustomVer()
int32 FArchiveState::CustomVer (const struct FGuid & Key) const
Queries a custom version from the archive.
If the archive is being used to write, the custom version must have already been registered.
Parameters
Key The guid of the custom version to query.
Returns
The version number, or -1 if the custom tag isn't stored in the archive.
References Key.
Referenced by FArchive::UsingCustomVersion().
DoDelta()
FORCEINLINE bool FArchiveState::DoDelta () const inline
Returns true if this archive should handle delta serialization for properties.
Definition at line 417 of file Archive.h.
References ArNoDelta, and FORCEINLINE.
DoIntraPropertyDelta()
FORCEINLINE bool FArchiveState::DoIntraPropertyDelta () const inline
Returns true if this archive should perform delta serialization within properties (e.g.
TMaps and TSets).
Definition at line 423 of file Archive.h.
References ArNoIntraPropertyDelta, and FORCEINLINE.
EngineNetVer()
virtual uint32 FArchiveState::EngineNetVer () const virtual
Returns the engine-global network protocol version for this archive.
Reimplemented in FArchive, and FInBunch.
EngineVer()
FORCEINLINE FEngineVersionBase FArchiveState::EngineVer () const inline
Returns the compiled engine version used for this archive.
Definition at line 216 of file Archive.h.
References ArEngineVer, and FORCEINLINE.
ForceByteSwapping()
FORCEINLINE bool FArchiveState::ForceByteSwapping () const inline
Returns true if this archive should always swap bytes, ignoring endian rules.
Definition at line 399 of file Archive.h.
References ArForceByteSwapping, and FORCEINLINE.
ForEachState()
template<typename T> void FArchiveState::ForEachState (T Func) private
GameNetVer()
virtual uint32 FArchiveState::GameNetVer () const virtual
Returns the game-specific network protocol version for this archive.
Reimplemented in FArchive, and FInBunch.
GetArchetypeFromLoader()
virtual UObject * FArchiveState::GetArchetypeFromLoader (const UObject * Obj) inline virtual
Called to retrieve the archetype from the event driven loader.
If this returns null, then call GetArchetype yourself.
Reimplemented in FArchive, FArchiveProxy, and FLinkerLoad.
Definition at line 198 of file Archive.h.
GetArchiveName()
virtual FString FArchiveState::GetArchiveName () const virtual
Returns the name of the Archive.
Useful for getting the name of the package a struct or object is in when a loading error occurs.
This is overridden for the specific Archive Types
Reimplemented in FArchive, FArchiveCountMem, FArchiveCrc32, FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveFindCulprit, FArchiveMD5, FArchiveObjectCrc32, FArchiveProxy, FArchiveReplaceObjectRefBase, FArchiveShowReferences, FArrayReader, FBufferReader, FBufferReaderBase, FBufferReaderWithSHA, FBufferWriter, FBulkDataReader, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FFindReferencersArchive, FLargeMemoryReader, FLargeMemoryWriter, FLinkerLoad, FLinkerSave, FMaterialResourceMemoryWriter, FMaterialResourceProxyReader, FMemoryArchive, FMemoryReader, FMemoryReaderView, FObjectReader, FObjectWriter, FPreloadableArchive, FPreloadableArchiveProxy, FStaticMemoryReader, FTransactionallySafeArchiveWriter, TBufferArchive< IndexSize >, TBufferArchive< 32 >, TBufferArchive< 64 >, TMemoryHasher< HashBuilder, HashDigest >, TMemoryHasher< FBlake3, FBlake3Hash >, TMemoryHasher< FSHA1, FSHAHash >, TMemoryWriterBase< ArrayAllocatorType >, and TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >.
GetCookContext()
FORCEINLINE FArchiveCookContext * FArchiveState::GetCookContext () inline
Definition at line 664 of file Archive.h.
References FORCEINLINE, and SavePackageData.
GetCustomVersions()
virtual const FCustomVersionContainer & FArchiveState::GetCustomVersions () const virtual
Gets the custom version numbers for this archive.
These are used to check for system or game-specific version numbers.
Returns
The container of custom versions in the archive.
Reimplemented in FArchive, FArchiveProxy, and FMaterialResourceMemoryWriter.
GetDebugSerializationFlags()
FORCEINLINE uint32 FArchiveState::GetDebugSerializationFlags () const inline
Returns the editor-only debug serialization flags.
Definition at line 492 of file Archive.h.
References ArDebugSerializationFlags, and FORCEINLINE.
GetError()
FORCEINLINE bool FArchiveState::GetError () const inline
Definition at line 367 of file Archive.h.
References ArIsError, and FORCEINLINE.
GetInnermostState()
virtual FArchiveState & FArchiveState::GetInnermostState () inline virtual
Returns lowest level archive state, proxy archives will override this.
Reimplemented in FArchive, and FArchiveProxy.
Definition at line 97 of file Archive.h.
References FArchiveState().
GetLinker()
virtual FLinker * FArchiveState::GetLinker () inline virtual
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
Returns
The linker, or nullptr if the archive is not a linker.
Reimplemented in FArchive, FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 140 of file Archive.h.
GetMaxSerializeSize()
FORCEINLINE int64 FArchiveState::GetMaxSerializeSize () const inline
Returns the maximum size of data that this archive is allowed to serialize.
Definition at line 508 of file Archive.h.
References ArMaxSerializeSize, and FORCEINLINE.
GetMigrationContext()
virtual const FUObjectMigrationContext * FArchiveState::GetMigrationContext () const inline virtual
When migrating objects, we may need some context as to the intent of the migration during serialization.
Reimplemented in FArchive.
Definition at line 343 of file Archive.h.
GetPortFlags()
FORCEINLINE uint32 FArchiveState::GetPortFlags () const inline
Returns this archive's property serialization modifier flags.
Definition at line 474 of file Archive.h.
References ArPortFlags, and FORCEINLINE.
GetSavePackageData()
FArchiveSavePackageData * FArchiveState::GetSavePackageData () inline
Definition at line 640 of file Archive.h.
References SavePackageData.
GetSavePackageSerializeContext()
FObjectSavePackageSerializeContext * FArchiveState::GetSavePackageSerializeContext () inline
Return the API object used to record extra data for SavePackage calls (e.g.
cook build dependencies). Returns null if not being serialized from SavePackage.
Definition at line 684 of file Archive.h.
References SavePackageData.
GetSerializedProperty()
FORCEINLINE class FProperty * FArchiveState::GetSerializedProperty () const inline
Gets the property that is currently being serialized.
Returns
Pointer to the property that is currently being serialized
Definition at line 724 of file Archive.h.
References FORCEINLINE, and SerializedProperty.
GetSerializedPropertyChain() [1/2]
FORCEINLINE const FArchiveSerializedPropertyChain * FArchiveState::GetSerializedPropertyChain () const inline
Get the raw serialized property chain for this archive.
Note
Accessing this directly can avoid an array allocation depending on your use-case
Definition at line 739 of file Archive.h.
References FORCEINLINE, and SerializedPropertyChain.
GetSerializedPropertyChain() [2/2]
void FArchiveState::GetSerializedPropertyChain (TArray< class FProperty * > & OutProperties) const
Gets the chain of properties that are currently being serialized.
Note
This populates the array in stack order, so the 0th entry in the array is the top of the stack of properties
HasAllPortFlags()
FORCEINLINE bool FArchiveState::HasAllPortFlags (uint32 Flags) const inline
Checks to see if all of the passed in property serialization modifier flags are set.
Definition at line 486 of file Archive.h.
References ArPortFlags, Flags, and FORCEINLINE.
HasAnyPortFlags()
FORCEINLINE bool FArchiveState::HasAnyPortFlags (uint32 Flags) const inline
Checks to see if any of the passed in property serialization modifier flags are set.
Definition at line 480 of file Archive.h.
References ArPortFlags, Flags, and FORCEINLINE.
IsAllowingLazyLoading()
FORCEINLINE bool FArchiveState::IsAllowingLazyLoading () const inline
Returns true if this archive sould allow lazy loading of bulk / secondary data.
Definition at line 447 of file Archive.h.
References ArAllowLazyLoading, and FORCEINLINE.
IsByteSwapping()
FORCEINLINE bool FArchiveState::IsByteSwapping () inline
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
Definition at line 169 of file Archive.h.
References ArForceByteSwapping, FORCEINLINE, and IsPersistent().
Referenced by FArchive::SerializeCompressedNew().
IsCooking()
FORCEINLINE bool FArchiveState::IsCooking () const inline
Checks whether the archive is used for cooking.
Returns
true if the archive is used for cooking, false otherwise.
Definition at line 617 of file Archive.h.
References FORCEINLINE, and SavePackageData.
IsCountingMemory()
FORCEINLINE bool FArchiveState::IsCountingMemory () const inline
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
Definition at line 468 of file Archive.h.
References ArIsCountingMemory, and FORCEINLINE.
IsCriticalError()
FORCEINLINE bool FArchiveState::IsCriticalError () const inline
Returns true if this archive contains critical errors that cannot be recovered from.
Definition at line 373 of file Archive.h.
References ArIsCriticalError, and FORCEINLINE.
IsError()
FORCEINLINE bool FArchiveState::IsError () const inline
Returns true if this archive contains errors, which means that further serialization is generally not safe.
Definition at line 362 of file Archive.h.
References ArIsError, and FORCEINLINE.
IsFilterEditorOnly()
bool FArchiveState::IsFilterEditorOnly () const inline
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
Returns
true if the archive filters editor-only content, false otherwise.
Definition at line 578 of file Archive.h.
References ArIsFilterEditorOnly.
IsForcingUnicode()
FORCEINLINE bool FArchiveState::IsForcingUnicode () const inline
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
Definition at line 291 of file Archive.h.
References ArForceUnicode, and FORCEINLINE.
IsIgnoringArchetypeRef()
FORCEINLINE bool FArchiveState::IsIgnoringArchetypeRef () const inline
Returns true if this archive should ignore archetype references for structs and classes.
Definition at line 411 of file Archive.h.
References ArIgnoreArchetypeRef, and FORCEINLINE.
IsIgnoringClassGeneratedByRef()
FORCEINLINE bool FArchiveState::IsIgnoringClassGeneratedByRef () const inline
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
Definition at line 435 of file Archive.h.
References ArIgnoreClassGeneratedByRef, and FORCEINLINE.
IsIgnoringClassRef()
FORCEINLINE bool FArchiveState::IsIgnoringClassRef () const inline
Returns true if this archive should ignore the Class reference in UObject.
Definition at line 441 of file Archive.h.
References ArIgnoreClassRef, and FORCEINLINE.
IsIgnoringOuterRef()
FORCEINLINE bool FArchiveState::IsIgnoringOuterRef () const inline
Returns true if this archive should ignore the Outer reference in UObject.
Definition at line 429 of file Archive.h.
References ArIgnoreOuterRef, and FORCEINLINE.
IsLoading()
FORCEINLINE bool FArchiveState::IsLoading () const inline
Returns true if this archive is for loading data.
Definition at line 236 of file Archive.h.
References ArIsLoading, and FORCEINLINE.
Referenced by operator<<(), and SetSavePackageData().
IsLoadingFromCookedPackage()
FORCEINLINE bool FArchiveState::IsLoadingFromCookedPackage () const inline
Returns true if this archive is loading from a cooked package.
Definition at line 242 of file Archive.h.
References ArIsLoadingFromCookedPackage, and FORCEINLINE.
IsMigratingRemoteObjects()
FORCEINLINE constexpr bool FArchiveState::IsMigratingRemoteObjects () const inline constexpr
Returns true if this Archive is migrating remote object.
Definition at line 355 of file Archive.h.
References FORCEINLINE.
IsModifyingWeakAndStrongReferences()
FORCEINLINE bool FArchiveState::IsModifyingWeakAndStrongReferences () const inline
Returns true if this archive should modify/search weak object references as well as strong ones.
Definition at line 462 of file Archive.h.
References ArIsModifyingWeakAndStrongReferences, and FORCEINLINE.
IsNetArchive()
FORCEINLINE bool FArchiveState::IsNetArchive () const inline
Whether or not this archive is serializing data being sent/received by the netcode.
Definition at line 607 of file Archive.h.
References ArIsNetArchive, and FORCEINLINE.
IsObjectReferenceCollector()
FORCEINLINE bool FArchiveState::IsObjectReferenceCollector () const inline
Returns true if this archive is only looking for UObject references.
This can be false for reference collectors looking for more general references.
Definition at line 456 of file Archive.h.
References ArIsObjectReferenceCollector, and FORCEINLINE.
IsPersistent()
FORCEINLINE bool FArchiveState::IsPersistent () const inline
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
This is also true for some intermediate archives for tasks like duplication that are eventually destined for persistent storage.
Definition at line 300 of file Archive.h.
References ArIsPersistent, and FORCEINLINE.
Referenced by IsByteSwapping().
IsSaveGame()
bool FArchiveState::IsSaveGame () const inline
Indicates whether this archive is saving or loading game state.
Note
This is intended for game-specific archives and is not true for any of the build in save methods
Returns
true if the archive is dealing with save games, false otherwise.
Definition at line 599 of file Archive.h.
References ArIsSaveGame.
IsSaving()
FORCEINLINE bool FArchiveState::IsSaving () const inline
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
Definition at line 248 of file Archive.h.
References ArIsSaving, and FORCEINLINE.
Referenced by SetSavePackageData().
IsSerializingDefaults()
FORCEINLINE bool FArchiveState::IsSerializingDefaults () const inline
Returns true if this archive is currently serializing class/struct default values.
Definition at line 405 of file Archive.h.
References ArSerializingDefaults, and FORCEINLINE.
IsTextFormat()
FORCEINLINE bool FArchiveState::IsTextFormat () const inline
Returns true if this archive serializes to a structured text format.
Text format archives should use high level constructs from FStructuredArchive for delimiting data rather than manually seeking through the file.
Definition at line 270 of file Archive.h.
References ArIsTextFormat, FORCEINLINE, and WITH_TEXT_ARCHIVE_SUPPORT.
IsTransacting()
FORCEINLINE bool FArchiveState::IsTransacting () const inline
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
Definition at line 254 of file Archive.h.
References ArIsTransacting, and FORCEINLINE.
Referenced by SetSavePackageData().
LicenseeUEVer()
FORCEINLINE int32 FArchiveState::LicenseeUEVer () const inline
Returns the licensee-specific version used for this archive, will be 0 by default.
Definition at line 210 of file Archive.h.
References ArLicenseeUEVer, and FORCEINLINE.
LinkProxy()
void FArchiveState::LinkProxy (FArchiveState & Inner, FArchiveState & Proxy) static protected
References FArchiveState().
Referenced by FArchive::~FArchive().
operator=()
FArchiveState & FArchiveState::operator= (const FArchiveState & ArchiveToCopy) private
Copy assignment operator.
Parameters
ArchiveToCopy The archive to copy from.
References FArchiveState().
RequiresLocalizationGather()
FORCEINLINE bool FArchiveState::RequiresLocalizationGather () const inline
Returns true if this archive contains data required to be gathered for localization.
Definition at line 391 of file Archive.h.
References FORCEINLINE, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Reset()
virtual void FArchiveState::Reset () virtual
Resets all of the base archive members.
Reimplemented in FArchive, FArchiveMD5, FBitWriter, and FOutBunch.
ResetCustomVersions()
virtual void FArchiveState::ResetCustomVersions () virtual
Resets the custom version numbers for this archive.
Reimplemented in FArchive, and FArchiveProxy.
SetArchiveState()
void FArchiveState::SetArchiveState (const FArchiveState & InState)
Modifies current archive state, can be used to override flags.
References FArchiveState().
SetByteSwapping()
void FArchiveState::SetByteSwapping (bool Enabled) inline
Toggle byte order swapping.
This is needed in rare cases when we already know that the data swapping has already occurred or if we know that it will be handled later.
Parameters
Enabled set to true to enable byte order swapping
Definition at line 546 of file Archive.h.
References ArForceByteSwapping, and Enabled.
SetCriticalError()
void FArchiveState::SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
Also sets CriticalError in the proxy archiver if one is wrapping this.
SetCustomVersion()
void FArchiveState::SetCustomVersion (const struct FGuid & Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
Parameters
Key - The guid of the custom version to query.
Version - The version number to set key to
FriendlyName - Friendly name corresponding to the key
References Key.
SetCustomVersions()
virtual void FArchiveState::SetCustomVersions (const FCustomVersionContainer & CustomVersionContainer) virtual
Sets the custom version numbers for this archive.
Parameters
CustomVersionContainer - The container of custom versions to copy into the archive.
Reimplemented in FArchive, and FArchiveProxy.
References CustomVersionContainer.
SetDebugSerializationFlags()
virtual void FArchiveState::SetDebugSerializationFlags (uint32 InCustomFlags) inline virtual
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
Parameters
InCustomFlags the new flags to use for custom serialization
Reimplemented in FArchive, FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 566 of file Archive.h.
References ArDebugSerializationFlags.
Referenced by FLinkerLoad::SetDebugSerializationFlags().
SetEngineNetVer()
virtual void FArchiveState::SetEngineNetVer (const uint32 InEngineNetVer) virtual
Sets the archive engine network version.
Reimplemented in FArchive, and FInBunch.
References SetEngineNetVer().
Referenced by SetEngineNetVer().
SetEngineVer()
virtual void FArchiveState::SetEngineVer (const FEngineVersionBase & InVer) virtual
Sets the archive engine version.
Used by the code that makes sure that FLinkerLoad's internal archive versions match the file reader it creates.
Parameters
InVer new version number
Reimplemented in FArchive.
References SetEngineVer().
Referenced by SetEngineVer().
SetError()
void FArchiveState::SetError ()
Sets ArIsError to true.
Also sets error in the proxy archiver if one is wrapping this.
SetFilterEditorOnly()
virtual void FArchiveState::SetFilterEditorOnly (bool InFilterEditorOnly) inline virtual
Sets a flag indicating that this archive needs to filter editor-only content.
Parameters
InFilterEditorOnly Whether to filter editor-only content.
Reimplemented in FArchive, FArchiveProxy, and FLinkerSave.
Definition at line 588 of file Archive.h.
References ArIsFilterEditorOnly.
SetForceUnicode()
virtual void FArchiveState::SetForceUnicode (bool bInForceUnicode) virtual
Sets whether this archive wants to force saving as Unicode.
This is needed when we need to make sure ANSI strings are saved as Unicode.
Parameters
bInForceUnicode true if this archive wants to force saving as Unicode, false otherwise.
Reimplemented in FArchive.
References SetForceUnicode().
Referenced by SetForceUnicode().
SetGameNetVer()
virtual void FArchiveState::SetGameNetVer (const uint32 InGameNetVer) virtual
Sets the archive game network version.
Reimplemented in FArchive, and FInBunch.
References SetGameNetVer().
Referenced by SetGameNetVer().
SetIsLoading()
virtual void FArchiveState::SetIsLoading (bool bInIsLoading) virtual
Sets whether this archive is for loading data.
Parameters
bInIsLoading true if this archive is for loading, false otherwise.
Reimplemented in FArchive.
References SetIsLoading().
Referenced by SetIsLoading().
SetIsLoadingFromCookedPackage()
virtual void FArchiveState::SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage) virtual
Sets whether the archive is loading from a cooked package.
Parameters
bInIsLoadingFromCookedPackage true if this archive is loading from a cooked package, false otherwise
Reimplemented in FArchive.
References SetIsLoadingFromCookedPackage().
Referenced by SetIsLoadingFromCookedPackage().
SetIsPersistent()
virtual void FArchiveState::SetIsPersistent (bool bInIsPersistent) virtual
Sets whether this archive is to persistent storage.
Parameters
bInIsPersistent true if this archive is to persistent storage, false otherwise.
Reimplemented in FArchive.
References SetIsPersistent().
Referenced by SetIsPersistent().
SetIsSaving()
virtual void FArchiveState::SetIsSaving (bool bInIsSaving) virtual
Sets whether this archive is for saving data.
Parameters
bInIsSaving true if this archive is for saving, false otherwise.
Reimplemented in FArchive.
References SetIsSaving().
Referenced by SetIsSaving().
SetIsTextFormat()
virtual void FArchiveState::SetIsTextFormat (bool bInIsTextFormat) virtual
Sets whether this archive is in text format.
Parameters
bInIsTextFormat true if this archive is in text format, false otherwise.
Reimplemented in FArchive.
References SetIsTextFormat().
Referenced by SetIsTextFormat().
SetIsTransacting()
virtual void FArchiveState::SetIsTransacting (bool bInIsTransacting) virtual
Sets whether this archive is for transacting.
Parameters
bInIsTransacting true if this archive is for transacting, false otherwise.
Reimplemented in FArchive.
References SetIsTransacting().
Referenced by SetIsTransacting().
SetLicenseeUEVer()
virtual void FArchiveState::SetLicenseeUEVer (int32 InVer) virtual
Sets the archive licensee version number.
Used by the code that makes sure that FLinkerLoad's internal archive versions match the file reader it creates.
Parameters
Ver new version number
Reimplemented in FArchive.
References SetLicenseeUEVer().
Referenced by SetLicenseeUEVer().
SetMigratingRemoteObjects()
void FArchiveState::SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
Parameters
bMigrating Whether this archive is migrating remote objects
SetPortFlags()
void FArchiveState::SetPortFlags (uint32 InPortFlags) inline
Sets the archive's property serialization modifier flags.
Parameters
InPortFlags the new flags to use for property serialization
Definition at line 556 of file Archive.h.
References ArPortFlags.
SetSavePackageData()
void FArchiveState::SetSavePackageData (FArchiveSavePackageData * InSavePackageData) inline
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
Must be set only after setting the loading/saving/transacting flags.
Definition at line 628 of file Archive.h.
References check, checkf, IsLoading(), IsSaving(), IsTransacting(), SavePackageData, and TEXT.
SetSerializedProperty()
virtual void FArchiveState::SetSerializedProperty (FProperty * InProperty) inline virtual
Overrides the property that is currently being serialized.
Note
: You likely want to call PushSerializedProperty/PopSerializedProperty instead
Parameters
InProperty Pointer to the property that is currently being serialized
Reimplemented in FArchive, FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 714 of file Archive.h.
References SerializedProperty.
Referenced by FLinkerLoad::SetSerializedProperty().
SetSerializedPropertyChain()
virtual void FArchiveState::SetSerializedPropertyChain (const FArchiveSerializedPropertyChain * InSerializedPropertyChain, class FProperty * InSerializedPropertyOverride = nullptr) virtual
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
Reimplemented in FArchive, FArchiveProxy, FLinkerLoad, and FLinkerSave.
Referenced by FLinkerLoad::SetSerializedPropertyChain().
SetShouldSkipCompilingAssets()
void FArchiveState::SetShouldSkipCompilingAssets (bool Enabled) inline
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Parameters
Enabled Set to true to enable skip serialization on compiling assets.
Definition at line 310 of file Archive.h.
References ArShouldSkipCompilingAssets, and Enabled.
SetShouldSkipUpdateCustomVersion()
void FArchiveState::SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
Querying the version registry is not cheap, and the look up time increases as more custom versions are registered, therefore if you don't change the registered custom version data once is set in the archive Setting this to true should improve serialization performance by skipping the step entirely.
Parameters
bShouldSkip Whether we should skip the checking the version registry for new version data if the version key is already set
SetUEVer()
virtual void FArchiveState::SetUEVer (FPackageFileVersion InVer) virtual
Sets the archive version number.
Used by the code that makes sure that FLinkerLoad's internal archive versions match the file reader it creates.
Parameters
UEVer new version number
Reimplemented in FArchive.
References SetUEVer().
Referenced by SetUEVer().
SetUseUnversionedPropertySerialization()
virtual void FArchiveState::SetUseUnversionedPropertySerialization (bool bInUseUnversioned) virtual
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
This assumes writer and reader share the same property definitions.
Reimplemented in FArchive, and FLinkerSave.
References SetUseUnversionedPropertySerialization().
Referenced by SetUseUnversionedPropertySerialization().
SetWantBinaryPropertySerialization()
virtual void FArchiveState::SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization) virtual
Sets whether this archive wants binary property serialization.
Parameters
bInWantBinaryPropertySerialization true if this archive wants binary serialization, false otherwise.
Reimplemented in FArchive.
References SetWantBinaryPropertySerialization().
Referenced by SetWantBinaryPropertySerialization().
ShouldSkipBulkData()
FORCEINLINE bool FArchiveState::ShouldSkipBulkData () const inline
Returns true if this archive should ignore bulk data.
Definition at line 502 of file Archive.h.
References ArShouldSkipBulkData, and FORCEINLINE.
ShouldSkipCompilingAssets()
FORCEINLINE bool FArchiveState::ShouldSkipCompilingAssets () const inline
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Definition at line 318 of file Archive.h.
References ArShouldSkipCompilingAssets, and FORCEINLINE.
ShouldSkipProperty()
virtual bool FArchiveState::ShouldSkipProperty (const FProperty * InProperty) const inline virtual
Checks whether the archive wants to skip the property independent of the other flags.
Reimplemented in FArchive, FArchiveProxy, FLinkerSave, and UE::Transaction::FDiffableObjectDataWriter.
Definition at line 703 of file Archive.h.
ShouldSkipUpdateCustomVersion()
FORCEINLINE bool FArchiveState::ShouldSkipUpdateCustomVersion () const inline
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
Definition at line 331 of file Archive.h.
References ArShouldSkipUpdateCustomVersion, and FORCEINLINE.
Tell()
virtual int64 FArchiveState::Tell () inline virtual
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
If this returns -1, there is no backing data storage and Seek will not function.
Reimplemented in FArchive, FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveLoadCompressedProxy, FArchiveProxy, FArchiveSaveCompressedProxy, FBufferReaderBase, FBufferWriter, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FLinkerLoad, FLinkerSave, FMaterialResourceProxyReader, FMemoryArchive, FPreloadableArchive, FPreloadableArchiveProxy, FRigVMObjectArchiveWriter, FTransactionallySafeArchiveWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::Internal::FSerializedObjectDataWriterCommon.
Definition at line 149 of file Archive.h.
References INDEX_NONE.
Referenced by AtEnd().
ThisContainsCode()
void FArchiveState::ThisContainsCode () inline
Sets a flag indicating that this archive contains native or generated code.
Definition at line 180 of file Archive.h.
References ArContainsCode.
ThisContainsMap()
void FArchiveState::ThisContainsMap () inline
Sets a flag indicating that this archive contains a ULevel or UWorld object.
Definition at line 186 of file Archive.h.
References ArContainsMap.
ThisRequiresLocalizationGather()
void FArchiveState::ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
TotalSize()
virtual int64 FArchiveState::TotalSize () inline virtual
Returns total size of the backing data storage.
Reimplemented in FArchive, FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveProxy, FArrayReader, FBufferReaderBase, FBufferWriter, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FLargeMemoryReader, FLargeMemoryWriter, FLinkerLoad, FMemoryReader, FMemoryReaderView, FObjectReader, FPreloadableArchive, FPreloadableArchiveProxy, FRigVMObjectArchiveWriter, FStaticMemoryReader, TMemoryHasher< HashBuilder, HashDigest >, TMemoryHasher< FBlake3, FBlake3Hash >, TMemoryHasher< FSHA1, FSHAHash >, TMemoryWriterBase< ArrayAllocatorType >, TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::Internal::FSerializedObjectDataWriterCommon.
Definition at line 155 of file Archive.h.
References INDEX_NONE.
Referenced by AtEnd().
UE_DEPRECATED() [1/4]
FArchiveState::UE_DEPRECATED (5. 5, "GetSerializeContext is not supported. Use FUObjectThreadContext::Get().GetSerializeContext().") inline
Gets the current UObject serialization context for this archive.
Definition at line 759 of file Archive.h.
UE_DEPRECATED() [2/4]
FArchiveState::UE_DEPRECATED (5. 5, "SetSerializeContext is not supported. Remove calls to it.") inline
Sets the current UObject serialization context for this archive.
Definition at line 755 of file Archive.h.
UE_DEPRECATED() [3/4]
FArchiveState::UE_DEPRECATED (5. 5, "Use GetCookContext or CookingTarget or GetSavePackageData.") inline
Definition at line 654 of file Archive.h.
References check.
UE_DEPRECATED() [4/4]
FArchiveState::UE_DEPRECATED (5. 5, "Use SetSavePackageData.") inline
Definition at line 645 of file Archive.h.
References check.
UEVer()
FORCEINLINE FPackageFileVersion FArchiveState::UEVer () const inline
Returns the global engine serialization version used for this archive.
Definition at line 204 of file Archive.h.
References ArUEVer, and FORCEINLINE.
UnlinkProxy()
void FArchiveState::UnlinkProxy (FArchiveState & Inner, FArchiveState & Proxy) static protected
References FArchiveState().
Referenced by FArchive::~FArchive().
UseToResolveEnumerators()
virtual bool FArchiveState::UseToResolveEnumerators () const inline virtual
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
Returns
true if the archive is used to resolve out-of-date enum indexes
Reimplemented in FArchive, and FArchiveProxy.
Definition at line 695 of file Archive.h.
UseUnversionedPropertySerialization()
FORCEINLINE bool FArchiveState::UseUnversionedPropertySerialization () const inline
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
This assumes writer and reader share the same property definitions.
Definition at line 285 of file Archive.h.
References ArUseUnversionedPropertySerialization, and FORCEINLINE.
WantBinaryPropertySerialization()
FORCEINLINE bool FArchiveState::WantBinaryPropertySerialization () const inline
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Definition at line 276 of file Archive.h.
References ArWantBinaryPropertySerialization, and FORCEINLINE.
Friends And Related Symbol Documentation
FArchive
friend class FArchive friend
Definition at line 73 of file Archive.h.
References FArchive.
Referenced by FArchive.
Field Documentation
ActiveFPLB
FFastPathLoadBuffer* FArchiveState::ActiveFPLB
Definition at line 799 of file Archive.h.
ArAllowLazyLoading
uint8 FArchiveState::ArAllowLazyLoading
Whether to allow lazy loading of bulk/secondary data.
Definition at line 888 of file Archive.h.
Referenced by IsAllowingLazyLoading().
ArContainsCode
uint8 FArchiveState::ArContainsCode
Quickly tell if an archive contains script code.
Definition at line 857 of file Archive.h.
Referenced by ContainsCode(), and ThisContainsCode().
ArContainsMap
uint8 FArchiveState::ArContainsMap
Used to determine whether FArchive contains a level or world.
Definition at line 860 of file Archive.h.
Referenced by ContainsMap(), and ThisContainsMap().
ArCustomPropertyList
const struct FCustomPropertyListNode* FArchiveState::ArCustomPropertyList
Custom property list attribute.
If the flag below is set, only these properties will be iterated during serialization. If NULL, then no properties will be iterated.
Definition at line 1042 of file Archive.h.
ArDebugSerializationFlags
uint32 FArchiveState::ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
Definition at line 1046 of file Archive.h.
Referenced by GetDebugSerializationFlags(), and SetDebugSerializationFlags().
ArEngineVer
FEngineVersionBase FArchiveState::ArEngineVer protected
Holds the engine version.
Definition at line 1031 of file Archive.h.
Referenced by EngineVer().
ArForceByteSwapping
UE_DEPRECATED (5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 FArchiveState::ArForceByteSwapping
Used to determine whether FArchive contains data required to be gathered for localization.
Whether we should forcefully swap bytes.
Definition at line 867 of file Archive.h.
Referenced by ForceByteSwapping(), IsByteSwapping(), and SetByteSwapping().
ArForceUnicode
uint8 FArchiveState::ArForceUnicode protected
Whether this archive wants to always save strings in UTF16 format even if they are ANSI characters.
Definition at line 830 of file Archive.h.
Referenced by IsForcingUnicode().
ArIgnoreArchetypeRef
uint8 FArchiveState::ArIgnoreArchetypeRef
If true, we will not serialize archetype references for structs and classes.
Definition at line 870 of file Archive.h.
Referenced by IsIgnoringArchetypeRef().
ArIgnoreClassGeneratedByRef
uint8 FArchiveState::ArIgnoreClassGeneratedByRef
If true, we will not serialize ClassGeneratedBy reference in UClass.
Definition at line 882 of file Archive.h.
Referenced by IsIgnoringClassGeneratedByRef().
ArIgnoreClassRef
uint8 FArchiveState::ArIgnoreClassRef
If true, UObject::Serialize will skip serialization of the Class property.
Definition at line 885 of file Archive.h.
Referenced by IsIgnoringClassRef().
ArIgnoreOuterRef
uint8 FArchiveState::ArIgnoreOuterRef
If true, we will not serialize the Outer reference in UObject.
Definition at line 879 of file Archive.h.
Referenced by IsIgnoringOuterRef().
ArIsCountingMemory
uint8 FArchiveState::ArIsCountingMemory
Whether this archive is counting memory.
Definition at line 897 of file Archive.h.
Referenced by IsCountingMemory().
ArIsCriticalError
uint8 FArchiveState::ArIsCriticalError private
Whether this archive contains critical errors that cannot be recovered from.
Definition at line 840 of file Archive.h.
Referenced by IsCriticalError().
ArIsError
uint8 FArchiveState::ArIsError private
Whether this archive contains errors, which means that further serialization is generally not safe.
Definition at line 837 of file Archive.h.
Referenced by GetError(), and IsError().
ArIsFilterEditorOnly
uint8 FArchiveState::ArIsFilterEditorOnly
Whether editor only properties are being filtered from the archive (or has been filtered).
Definition at line 903 of file Archive.h.
Referenced by IsFilterEditorOnly(), and SetFilterEditorOnly().
ArIsLoading
uint8 FArchiveState::ArIsLoading protected
Whether this archive is for loading data.
Definition at line 809 of file Archive.h.
Referenced by IsLoading().
ArIsLoadingFromCookedPackage
uint8 FArchiveState::ArIsLoadingFromCookedPackage protected
Whether this archive is loading from a cooked package.
Definition at line 812 of file Archive.h.
Referenced by IsLoadingFromCookedPackage().
ArIsModifyingWeakAndStrongReferences
uint8 FArchiveState::ArIsModifyingWeakAndStrongReferences
Whether a reference collector is modifying the references and wants both weak and strong ones.
Definition at line 894 of file Archive.h.
Referenced by IsModifyingWeakAndStrongReferences().
ArIsNetArchive
uint8 FArchiveState::ArIsNetArchive
Whether or not this archive is sending/receiving network data.
Definition at line 909 of file Archive.h.
Referenced by IsNetArchive().
ArIsObjectReferenceCollector
uint8 FArchiveState::ArIsObjectReferenceCollector
Whether this archive only cares about serializing object references.
Definition at line 891 of file Archive.h.
Referenced by IsObjectReferenceCollector().
ArIsPersistent
uint8 FArchiveState::ArIsPersistent protected
Whether this archive saves to persistent storage.
This is also true for some intermediate archives like DuplicateObject that are expected to go to persistent storage but may be discarded
Definition at line 833 of file Archive.h.
Referenced by IsPersistent().
ArIsSaveGame
uint8 FArchiveState::ArIsSaveGame
Whether this archive is saving/loading game state.
Definition at line 906 of file Archive.h.
Referenced by IsSaveGame().
ArIsSaving
uint8 FArchiveState::ArIsSaving protected
Whether this archive is for saving data.
Definition at line 815 of file Archive.h.
Referenced by IsSaving().
ArIsTextFormat
uint8 FArchiveState::ArIsTextFormat protected
Whether this archive serializes to a text format.
Text format archives should use high level constructs from FStructuredArchive for delimiting data rather than manually seeking through the file.
Definition at line 821 of file Archive.h.
Referenced by IsTextFormat().
ArIsTransacting
uint8 FArchiveState::ArIsTransacting protected
Whether archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
Definition at line 818 of file Archive.h.
Referenced by IsTransacting().
ArLicenseeUEVer
int32 FArchiveState::ArLicenseeUEVer protected
Holds the archive version for licensees.
Definition at line 1028 of file Archive.h.
Referenced by LicenseeUEVer().
ArMaxSerializeSize
int64 FArchiveState::ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
Definition at line 927 of file Archive.h.
Referenced by GetMaxSerializeSize().
ArMergeOverrides
uint8 FArchiveState::ArMergeOverrides
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
Definition at line 915 of file Archive.h.
ArNoDelta
uint8 FArchiveState::ArNoDelta
If true, do not perform delta serialization of properties.
Definition at line 873 of file Archive.h.
Referenced by DoDelta().
ArNoIntraPropertyDelta
uint8 FArchiveState::ArNoIntraPropertyDelta
If true, do not perform delta serialization within properties (e.g.
TMaps and TSets).
Definition at line 876 of file Archive.h.
Referenced by DoIntraPropertyDelta().
ArPortFlags
uint32 FArchiveState::ArPortFlags
Modifier flags that be used when serializing UProperties.
Definition at line 924 of file Archive.h.
Referenced by GetPortFlags(), HasAllPortFlags(), HasAnyPortFlags(), and SetPortFlags().
ArPreserveArrayElements
uint8 FArchiveState::ArPreserveArrayElements
Set TRUE to stop arrays from being cleared before they're loaded.
Instead, array data will be merged
Definition at line 918 of file Archive.h.
ArSerializingDefaults
int32 FArchiveState::ArSerializingDefaults
Whether we are currently serializing defaults.
> 0 means yes, <= 0 means no.
Definition at line 921 of file Archive.h.
Referenced by IsSerializingDefaults().
ArShouldSkipBulkData
uint8 FArchiveState::ArShouldSkipBulkData
Whether bulk data serialization should be skipped or not.
Definition at line 900 of file Archive.h.
Referenced by ShouldSkipBulkData().
ArShouldSkipCompilingAssets
uint8 FArchiveState::ArShouldSkipCompilingAssets private
Whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Definition at line 843 of file Archive.h.
Referenced by SetShouldSkipCompilingAssets(), and ShouldSkipCompilingAssets().
ArShouldSkipUpdateCustomVersion
uint8 FArchiveState::ArShouldSkipUpdateCustomVersion private
If true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
Querying the version registry is not cheap, and the look up time increases as more custom versions are registered, therefore if you don't change the registered custom version data once is set in the archive Setting this to true should improve serialization performance by skipping the step entirely
Definition at line 848 of file Archive.h.
Referenced by ShouldSkipUpdateCustomVersion().
ArUEVer
FPackageFileVersion FArchiveState::ArUEVer protected
Holds the archive version.
Definition at line 1025 of file Archive.h.
Referenced by UEVer().
ArUseCustomPropertyList
uint8 FArchiveState::ArUseCustomPropertyList
Set TRUE to use the custom property list attribute for serialization.
Definition at line 912 of file Archive.h.
ArUseUnversionedPropertySerialization
uint8 FArchiveState::ArUseUnversionedPropertySerialization protected
Whether tagged property serialization is replaced by faster unversioned serialization.
This assumes writer and reader share the same property definitions.
Definition at line 827 of file Archive.h.
Referenced by UseUnversionedPropertySerialization().
ArWantBinaryPropertySerialization
uint8 FArchiveState::ArWantBinaryPropertySerialization protected
Whether this archive wants properties to be serialized in binary form instead of tagged.
Definition at line 824 of file Archive.h.
Referenced by WantBinaryPropertySerialization().
bCustomVersionsAreReset
bool FArchiveState::bCustomVersionsAreReset mutable protected
Indicates if the custom versions container is in a 'reset' state.
This will be used to defer the choice about how to populate the container until it is needed, where the read/write state will be known.
Definition at line 1082 of file Archive.h.
CustomVersionContainer
FCustomVersionContainer* FArchiveState::CustomVersionContainer = nullptr mutable protected
All the custom versions stored in the archive.
Stored as a pointer to a heap-allocated object because of a 3-way dependency between TArray, FCustomVersionContainer and FArchive, which is too much work to change right now. Keeping it as a heap-allocated object also helps with performance in some cases as we don't need to construct it for archives that don't care about custom versions.
Definition at line 1038 of file Archive.h.
Referenced by SetCustomVersions().
InlineFPLB
FFastPathLoadBuffer FArchiveState::InlineFPLB
Definition at line 800 of file Archive.h.
NextProxy
FArchiveState* FArchiveState::NextProxy = nullptr private
Linked list to all proxies.
Definition at line 1086 of file Archive.h.
SavePackageData
FArchiveSavePackageData* FArchiveState::SavePackageData = nullptr protected
Provider of data and API specific to UPackage::Save2.
Required by archives used from UPackage::Save2, and required for cook saves of packages. nullptr means the archive is not one from UPackage::Save2 and is not being called from a cook save.
Definition at line 1055 of file Archive.h.
Referenced by CookingTarget(), GetCookContext(), GetSavePackageData(), GetSavePackageSerializeContext(), IsCooking(), and SetSavePackageData().
SerializedProperty
FProperty* FArchiveState::SerializedProperty protected
Holds the pointer to the property that is currently being serialized.
Definition at line 1058 of file Archive.h.
Referenced by GetSerializedProperty(), and SetSerializedProperty().
SerializedPropertyChain
FArchiveSerializedPropertyChain* FArchiveState::SerializedPropertyChain protected
Holds the chain of properties that are currently being serialized.
Definition at line 1061 of file Archive.h.
Referenced by GetSerializedPropertyChain().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Serialization/Archive.h