Unreal Engine 5.6 C++ API: FLandscapeRenderSystem Struct Reference
FLandscapeRenderSystem Struct Reference
#include "LandscapeRender.h"
Data Structures
struct LODSettingsComponent
Public Types
typedef uint32 FViewKey
using SectionKeyToLODValueMap = TMap<FIntPoint, float>
Public Member Functions
FLandscapeRenderSystem (uint32 InLandscapeKey, FSceneInterface *InScene)
~FLandscapeRenderSystem ()
bool AnySectionsInRangeInclusive (FIntPoint RangeMin, FIntPoint RangeMax)
void CompactMap ()
const TResourceArray< float > & ComputeSectionsLODForView (const FSceneView &InView, UE::Renderer::Private::IShadowInvalidatingInstances *InShadowInvalidatingInstances)
void FetchHeightmapLODBiases ()
const TResourceArray< float > & GetCachedSectionLODValues (const FSceneView &InView) const
FLandscapeSectionInfo * GetSectionInfo (FIntPoint InRenderCoord)
int32 GetSectionLinearIndex (FIntPoint InRenderCoord) const
float GetSectionLODBias (FIntPoint InRenderCoord) const
float GetSectionLODValue (const FSceneView &InView, FIntPoint InRenderCoord) const
bool IsValidCoord (FIntPoint InRenderCoord) const
void PerformShadowInvalidations (UE::Renderer::Private::IShadowInvalidatingInstances &InShadowInvalidatingInstances)
void ResizeAndMoveTo (FIntPoint NewMin, FIntPoint NewMax)
void ResizeToInclude (const FIntPoint &NewCoord)
void SetSectionInfo (FIntPoint InRenderCoord, FLandscapeSectionInfo *InSectionInfo)
void UpdateBuffers (FRHICommandListBase &RHICmdList)
Static Public Member Functions
static float ComputeLODFromScreenSize (const LODSettingsComponent &InLODSettings, float InScreenSizeSquared)
static void CreateResources (FRHICommandListBase &RHICmdList, FLandscapeSectionInfo *SectionInfo)
static void DestroyResources (FLandscapeSectionInfo *SectionInfo)
static void RegisterSection (FLandscapeSectionInfo *SectionInfo)
static void UnregisterSection (FLandscapeSectionInfo *SectionInfo)
Data Fields
FVector ComponentOrigin = FVector::ZeroVector
int32 ComponentResolution = -1
FVector ComponentXVector = FVector::ZeroVector
FVector ComponentYVector = FVector::ZeroVector
int8 ForcedLODOverride
Forced LOD level which overrides the ForcedLOD level of all the sections under this LandscapeRenderSystem.
int32 LandscapeIndex
uint32 LandscapeKey = 0
FIntPoint Min
TMap< const FSceneView *, TResourceArray< float > > PerViewCachedSectionLODValues
TMap< uint32, TResourceArray< float > > PerViewStateCachedSectionLODValues
TMap< uint32, SectionKeyToLODValueMap > PerViewStateLastShadowInvalidationSectionLODValues
int32 ReferenceCount
int32 RegisteredCount
FSceneInterface * Scene = nullptr
TArray< FLandscapeSectionInfo * > SectionInfos
FBufferRHIRef SectionLODBiasBuffer
TResourceArray< float > SectionLODBiases
FShaderResourceViewRHIRef SectionLODBiasSRV
FUniformBufferRHIRef SectionLODUniformBuffer
int32 SectionsRemovedSinceLastCompact
TMap< UE::Renderer::Private::IShadowInvalidatingInstances *, TArray< const FPrimitiveSceneInfo * > > ShadowInvalidationRequests
FIntPoint Size
Static Public Attributes
static TBitArray LandscapeIndexAllocator
Private Member Functions
void CreateResources_Internal (FRHICommandListBase &RHICmdList, FLandscapeSectionInfo *InSectionInfo)
void DestroyResources_Internal (FLandscapeSectionInfo *InSectionInfo)
Detailed Description
Definition at line 468 of file LandscapeRender.h.
Member Typedef Documentation
FViewKey
typedef uint32 FLandscapeRenderSystem::FViewKey
Definition at line 470 of file LandscapeRender.h.
SectionKeyToLODValueMap
using FLandscapeRenderSystem::SectionKeyToLODValueMap = TMap<FIntPoint, float>
Definition at line 515 of file LandscapeRender.h.
Constructor & Destructor Documentation
FLandscapeRenderSystem()
FLandscapeRenderSystem::FLandscapeRenderSystem (uint32 InLandscapeKey, FSceneInterface * InScene)
~FLandscapeRenderSystem()
FLandscapeRenderSystem::~FLandscapeRenderSystem ()
Member Function Documentation
AnySectionsInRangeInclusive()
bool FLandscapeRenderSystem::AnySectionsInRangeInclusive (FIntPoint RangeMin, FIntPoint RangeMax)
CompactMap()
void FLandscapeRenderSystem::CompactMap ()
ComputeLODFromScreenSize()
float FLandscapeRenderSystem::ComputeLODFromScreenSize (const LODSettingsComponent & InLODSettings, float InScreenSizeSquared) static
ComputeSectionsLODForView()
const TResourceArray< float > & FLandscapeRenderSystem::ComputeSectionsLODForView (const FSceneView & InView, UE::Renderer::Private::IShadowInvalidatingInstances * InShadowInvalidatingInstances)
CreateResources()
void FLandscapeRenderSystem::CreateResources (FRHICommandListBase & RHICmdList, FLandscapeSectionInfo * SectionInfo) static
CreateResources_Internal()
void FLandscapeRenderSystem::CreateResources_Internal (FRHICommandListBase & RHICmdList, FLandscapeSectionInfo * InSectionInfo) private
DestroyResources()
void FLandscapeRenderSystem::DestroyResources (FLandscapeSectionInfo * SectionInfo) static
DestroyResources_Internal()
void FLandscapeRenderSystem::DestroyResources_Internal (FLandscapeSectionInfo * InSectionInfo) private
FetchHeightmapLODBiases()
void FLandscapeRenderSystem::FetchHeightmapLODBiases ()
GetCachedSectionLODValues()
const TResourceArray< float > & FLandscapeRenderSystem::GetCachedSectionLODValues (const FSceneView & InView) const
GetSectionInfo()
FLandscapeSectionInfo * FLandscapeRenderSystem::GetSectionInfo (FIntPoint InRenderCoord) inline
Definition at line 571 of file LandscapeRender.h.
References GetSectionLinearIndex(), IsValidCoord(), and SectionInfos.
GetSectionLinearIndex()
int32 FLandscapeRenderSystem::GetSectionLinearIndex (FIntPoint InRenderCoord) const inline
Definition at line 551 of file LandscapeRender.h.
References check, IsValidCoord(), Min, Size, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
Referenced by GetSectionInfo(), and SetSectionInfo().
GetSectionLODBias()
float FLandscapeRenderSystem::GetSectionLODBias (FIntPoint InRenderCoord) const
GetSectionLODValue()
float FLandscapeRenderSystem::GetSectionLODValue (const FSceneView & InView, FIntPoint InRenderCoord) const
IsValidCoord()
bool FLandscapeRenderSystem::IsValidCoord (FIntPoint InRenderCoord) const inline
Definition at line 545 of file LandscapeRender.h.
References Min, Size, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
Referenced by GetSectionInfo(), GetSectionLinearIndex(), and SetSectionInfo().
PerformShadowInvalidations()
void FLandscapeRenderSystem::PerformShadowInvalidations (UE::Renderer::Private::IShadowInvalidatingInstances & InShadowInvalidatingInstances)
RegisterSection()
void FLandscapeRenderSystem::RegisterSection (FLandscapeSectionInfo * SectionInfo) static
ResizeAndMoveTo()
void FLandscapeRenderSystem::ResizeAndMoveTo (FIntPoint NewMin, FIntPoint NewMax)
ResizeToInclude()
void FLandscapeRenderSystem::ResizeToInclude (const FIntPoint & NewCoord)
SetSectionInfo()
void FLandscapeRenderSystem::SetSectionInfo (FIntPoint InRenderCoord, FLandscapeSectionInfo * InSectionInfo) inline
Definition at line 563 of file LandscapeRender.h.
References GetSectionLinearIndex(), IsValidCoord(), and SectionInfos.
UnregisterSection()
void FLandscapeRenderSystem::UnregisterSection (FLandscapeSectionInfo * SectionInfo) static
UpdateBuffers()
void FLandscapeRenderSystem::UpdateBuffers (FRHICommandListBase & RHICmdList)
Field Documentation
ComponentOrigin
FVector FLandscapeRenderSystem::ComponentOrigin = FVector::ZeroVector
Definition at line 526 of file LandscapeRender.h.
ComponentResolution
int32 FLandscapeRenderSystem::ComponentResolution = -1
Definition at line 525 of file LandscapeRender.h.
ComponentXVector
FVector FLandscapeRenderSystem::ComponentXVector = FVector::ZeroVector
Definition at line 527 of file LandscapeRender.h.
ComponentYVector
FVector FLandscapeRenderSystem::ComponentYVector = FVector::ZeroVector
Definition at line 528 of file LandscapeRender.h.
ForcedLODOverride
int8 FLandscapeRenderSystem::ForcedLODOverride
Forced LOD level which overrides the ForcedLOD level of all the sections under this LandscapeRenderSystem.
Definition at line 522 of file LandscapeRender.h.
LandscapeIndex
int32 FLandscapeRenderSystem::LandscapeIndex
Definition at line 489 of file LandscapeRender.h.
LandscapeIndexAllocator
TBitArray FLandscapeRenderSystem::LandscapeIndexAllocator static
Definition at line 487 of file LandscapeRender.h.
LandscapeKey
uint32 FLandscapeRenderSystem::LandscapeKey = 0
Definition at line 533 of file LandscapeRender.h.
Min
FIntPoint FLandscapeRenderSystem::Min
Definition at line 491 of file LandscapeRender.h.
Referenced by GetSectionLinearIndex(), and IsValidCoord().
PerViewCachedSectionLODValues
TMap<const FSceneView*, TResourceArray<float> > FLandscapeRenderSystem::PerViewCachedSectionLODValues
Definition at line 509 of file LandscapeRender.h.
PerViewStateCachedSectionLODValues
TMap<uint32, TResourceArray<float> > FLandscapeRenderSystem::PerViewStateCachedSectionLODValues
Definition at line 510 of file LandscapeRender.h.
PerViewStateLastShadowInvalidationSectionLODValues
TMap<uint32, SectionKeyToLODValueMap> FLandscapeRenderSystem::PerViewStateLastShadowInvalidationSectionLODValues
Definition at line 516 of file LandscapeRender.h.
ReferenceCount
int32 FLandscapeRenderSystem::ReferenceCount
Definition at line 497 of file LandscapeRender.h.
RegisteredCount
int32 FLandscapeRenderSystem::RegisteredCount
Definition at line 499 of file LandscapeRender.h.
Scene
FSceneInterface* FLandscapeRenderSystem::Scene = nullptr
Definition at line 534 of file LandscapeRender.h.
SectionInfos
TArray<FLandscapeSectionInfo*> FLandscapeRenderSystem::SectionInfos
Definition at line 495 of file LandscapeRender.h.
Referenced by GetSectionInfo(), and SetSectionInfo().
SectionLODBiasBuffer
FBufferRHIRef FLandscapeRenderSystem::SectionLODBiasBuffer
Definition at line 501 of file LandscapeRender.h.
SectionLODBiases
TResourceArray<float> FLandscapeRenderSystem::SectionLODBiases
Definition at line 494 of file LandscapeRender.h.
SectionLODBiasSRV
FShaderResourceViewRHIRef FLandscapeRenderSystem::SectionLODBiasSRV
Definition at line 502 of file LandscapeRender.h.
SectionLODUniformBuffer
FUniformBufferRHIRef FLandscapeRenderSystem::SectionLODUniformBuffer
Definition at line 504 of file LandscapeRender.h.
SectionsRemovedSinceLastCompact
int32 FLandscapeRenderSystem::SectionsRemovedSinceLastCompact
Definition at line 531 of file LandscapeRender.h.
ShadowInvalidationRequests
TMap<UE::Renderer::Private::IShadowInvalidatingInstances*, TArray<const FPrimitiveSceneInfo*> > FLandscapeRenderSystem::ShadowInvalidationRequests
Definition at line 519 of file LandscapeRender.h.
Size
FIntPoint FLandscapeRenderSystem::Size
Definition at line 492 of file LandscapeRender.h.
Referenced by GetSectionLinearIndex(), and IsValidCoord().
The documentation for this struct was generated from the following file:
Runtime/Landscape/Public/LandscapeRender.h