Unreal Engine 5.6 C++ API: FPlatformUserId Struct Reference
FPlatformUserId Struct Reference
Handle that defines a local user on this platform.
#include "CoreMiscDefines.h"
Public Member Functions
FORCEINLINE int32 GetInternalId () const
Returns the internal id for debugging/etc.
FORCEINLINE bool IsValid () const
Sees if this is a valid user.
FORCEINLINE constexpr operator int32 () const
FORCEINLINE bool operator!= (const FPlatformUserId &Other) const
FORCEINLINE bool operator== (const FPlatformUserId &Other) const
Static Public Member Functions
static FORCEINLINE FPlatformUserId CreateFromInternalId (int32 InInternalId)
Explicit function to create from an internal id.
Private Attributes
int32 InternalId = INDEX_NONE
Raw id, will be allocated by application layer.
Friends
FORCEINLINE friend uint32 GetTypeHash (const FPlatformUserId &UserId)
Detailed Description
Handle that defines a local user on this platform.
This used to be just a typedef int32 that was used interchangeably as ControllerId and LocalUserIndex. Moving forward these will be allocated by the platform application layer.
Definition at line 442 of file CoreMiscDefines.h.
Member Function Documentation
CreateFromInternalId()
FORCEINLINE FPlatformUserId FPlatformUserId::CreateFromInternalId (int32 InInternalId) inline static
Explicit function to create from an internal id.
Definition at line 457 of file CoreMiscDefines.h.
References FORCEINLINE, and InternalId.
GetInternalId()
FORCEINLINE int32 FPlatformUserId::GetInternalId () const inline
Returns the internal id for debugging/etc.
Definition at line 451 of file CoreMiscDefines.h.
References FORCEINLINE, and InternalId.
Referenced by ISlateInputManager::GetUserIndexForPlatformUser(), FGenericApplicationMessageHandler::OnMotionDetected(), FGenericApplicationMessageHandler::OnTouchEnded(), FGenericApplicationMessageHandler::OnTouchFirstMove(), FGenericApplicationMessageHandler::OnTouchForceChanged(), FGenericApplicationMessageHandler::OnTouchMoved(), and FGenericApplicationMessageHandler::OnTouchStarted().
IsValid()
FORCEINLINE bool FPlatformUserId::IsValid () const inline
Sees if this is a valid user.
Definition at line 445 of file CoreMiscDefines.h.
References FORCEINLINE, INDEX_NONE, and InternalId.
operator int32()
FORCEINLINE constexpr FPlatformUserId::operator int32 () const inline constexpr
Definition at line 481 of file CoreMiscDefines.h.
References FORCEINLINE, and InternalId.
operator!=()
FORCEINLINE bool FPlatformUserId::operator!= (const FPlatformUserId & Other) const inline
Definition at line 469 of file CoreMiscDefines.h.
References FORCEINLINE, InternalId, and Other.
operator==()
FORCEINLINE bool FPlatformUserId::operator== (const FPlatformUserId & Other) const inline
Definition at line 464 of file CoreMiscDefines.h.
References FORCEINLINE, InternalId, and Other.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE friend uint32 GetTypeHash (const FPlatformUserId & UserId) friend
Definition at line 474 of file CoreMiscDefines.h.
References FORCEINLINE, and InternalId.
Field Documentation
InternalId
int32 FPlatformUserId::InternalId = INDEX_NONE private
Raw id, will be allocated by application layer.
Definition at line 485 of file CoreMiscDefines.h.
Referenced by CreateFromInternalId(), GetInternalId(), GetTypeHash, IsValid(), operator int32(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/CoreMiscDefines.h