Unreal Engine 5.6 C++ API: FMenuEntryStyleParams Struct Reference
FMenuEntryStyleParams Struct Reference
Contains various Style parameters and overrides.
#include "MultiBoxDefs.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FMenuEntryStyleParams ()=default
FMenuEntryStyleParams (const FMenuEntryStyleParams &)=default
FMenuEntryStyleParams (FMenuEntryStyleParams &&)=default
FMenuEntryStyleParams & operator= (const FMenuEntryStyleParams &)=default
FMenuEntryStyleParams & operator= (FMenuEntryStyleParams &&)=default
UE_DEPRECATED (5.6, "Use DesiredHeightOverride instead") TOptional< float > DesiredHeight
(Optionally) set the desired height override
UE_DEPRECATED (5.6, "Use DesiredWidthOverride instead") TOptional< float > DesiredWidth
(Optionally) set the desired width override
UE_DEPRECATED (5.6, "Use MaximumSize instead") TOptional< float > MaxSize
(Optionally) override the maximum size.
UE_DEPRECATED (5.6, "Use MinimumSize instead") TOptional< float > MinSize
(Optionally) override the minimum size.
Data Fields
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool bNoIndent = false
If true, removes the padding from the left of the widget that lines it up with other menu items.
TAttribute< FOptionalSize > DesiredHeightOverride
(Optionally) set the desired height override
TAttribute< FOptionalSize > DesiredWidthOverride
(Optionally) set the desired width override
TOptional< float > FillSize
(Optionally) override the fill proportion when the SizeRule is Stretch or StretchContent, defaults to 1.0f
TOptional< float > FillSizeMin
(Optionally) override the minimum fill proportion when the SizeRule is StretchContent, defaults to FillSize/1.0f
EHorizontalAlignment HorizontalAlignment = HAlign_Fill
Horizontal alignment for this widget in its parent container.
TAttribute< float > MaximumSize
(Optionally) override the maximum size.
TAttribute< float > MinimumSize
(Optionally) override the minimum size.
TOptional< FSizeParam::ESizeRule > SizeRule
(Optionally) override the size rule, where the default is generally Auto
TOptional< EVerticalAlignment > VerticalAlignment
(Optional) Vertical alignment for this widget in its parent container
Detailed Description
Contains various Style parameters and overrides.
Not all are applicable to a given entry
Definition at line 208 of file MultiBoxDefs.h.
Constructor & Destructor Documentation
FMenuEntryStyleParams() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FMenuEntryStyleParams::FMenuEntryStyleParams () default
Referenced by FMenuEntryStyleParams(), FMenuEntryStyleParams(), operator=(), and operator=().
FMenuEntryStyleParams() [2/3]
FMenuEntryStyleParams::FMenuEntryStyleParams (FMenuEntryStyleParams &&) default
References FMenuEntryStyleParams().
FMenuEntryStyleParams() [3/3]
FMenuEntryStyleParams::FMenuEntryStyleParams (const FMenuEntryStyleParams &) default
References FMenuEntryStyleParams().
Member Function Documentation
operator=() [1/2]
FMenuEntryStyleParams & FMenuEntryStyleParams::operator= (const FMenuEntryStyleParams &) default
References FMenuEntryStyleParams(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FMenuEntryStyleParams & FMenuEntryStyleParams::operator= (FMenuEntryStyleParams &&) default
References FMenuEntryStyleParams().
UE_DEPRECATED() [1/4]
FMenuEntryStyleParams::UE_DEPRECATED (5. 6, "Use DesiredHeightOverride instead")
(Optionally) set the desired height override
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FMenuEntryStyleParams::UE_DEPRECATED (5. 6, "Use DesiredWidthOverride instead")
(Optionally) set the desired width override
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FMenuEntryStyleParams::UE_DEPRECATED (5. 6, "Use MaximumSize instead")
(Optionally) override the maximum size.
This will apply to the width or height, depending on the menu orientation
References MaxSize, and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
FMenuEntryStyleParams::UE_DEPRECATED (5. 6, "Use MinimumSize instead")
(Optionally) override the minimum size.
This will apply to the width or height, depending on the menu orientation
References MinSize.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
bNoIndent
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool FMenuEntryStyleParams::bNoIndent = false
If true, removes the padding from the left of the widget that lines it up with other menu items.
Definition at line 220 of file MultiBoxDefs.h.
DesiredHeightOverride
TAttribute<FOptionalSize> FMenuEntryStyleParams::DesiredHeightOverride
(Optionally) set the desired height override
Definition at line 263 of file MultiBoxDefs.h.
DesiredWidthOverride
TAttribute<FOptionalSize> FMenuEntryStyleParams::DesiredWidthOverride
(Optionally) set the desired width override
Definition at line 260 of file MultiBoxDefs.h.
FillSize
TOptional<float> FMenuEntryStyleParams::FillSize
(Optionally) override the fill proportion when the SizeRule is Stretch or StretchContent, defaults to 1.0f
Definition at line 248 of file MultiBoxDefs.h.
FillSizeMin
TOptional<float> FMenuEntryStyleParams::FillSizeMin
(Optionally) override the minimum fill proportion when the SizeRule is StretchContent, defaults to FillSize/1.0f
Definition at line 251 of file MultiBoxDefs.h.
HorizontalAlignment
EHorizontalAlignment FMenuEntryStyleParams::HorizontalAlignment = HAlign_Fill
Horizontal alignment for this widget in its parent container.
Note: only applies to toolbars
Definition at line 223 of file MultiBoxDefs.h.
MaximumSize
TAttribute<float> FMenuEntryStyleParams::MaximumSize
(Optionally) override the maximum size.
This will apply to the width or height, depending on the menu orientation
Definition at line 257 of file MultiBoxDefs.h.
MinimumSize
TAttribute<float> FMenuEntryStyleParams::MinimumSize
(Optionally) override the minimum size.
This will apply to the width or height, depending on the menu orientation
Definition at line 254 of file MultiBoxDefs.h.
SizeRule
TOptional<FSizeParam::ESizeRule> FMenuEntryStyleParams::SizeRule
(Optionally) override the size rule, where the default is generally Auto
Definition at line 229 of file MultiBoxDefs.h.
VerticalAlignment
TOptional<EVerticalAlignment> FMenuEntryStyleParams::VerticalAlignment
(Optional) Vertical alignment for this widget in its parent container
Definition at line 226 of file MultiBoxDefs.h.
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Framework/MultiBox/MultiBoxDefs.h