Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitUpdateState Struct Reference
UE::AnimNext::FTraitUpdateState Struct Reference final
FTraitUpdateState.
#include "IUpdate.h"
Public Member Functions
FTraitUpdateState ()=default
FTraitUpdateState (float InDeltaTime)
FTraitUpdateState AsBlendingOut (bool InIsBlendingOut=true) const
FTraitUpdateState AsNewlyRelevant (bool InIsNewlyRelevant=true) const
float GetDeltaTime () const
float GetTotalTrajectoryWeight () const
float GetTotalWeight () const
bool IsBlendingOut () const
bool IsNewlyRelevant () const
FTraitUpdateState WithDeltaTime (float InDeltaTime) const
FTraitUpdateState WithTimeScale (float TimeScale) const
FTraitUpdateState WithTrajectoryWeight (float Weight) const
FTraitUpdateState WithWeight (float Weight) const
Private Attributes
int8 bIsBlendingOut = false
int8 bIsNewlyRelevant = false
float DeltaTime = 0.0f
float TotalTrajectoryWeight = 1.0f
float TotalWeight = 1.0f
Detailed Description
FTraitUpdateState.
State that propagates down the graph during the update traversal.
We align this to 16 bytes and maintain that same size to ensure efficient copying.
Definition at line 83 of file IUpdate.h.
Constructor & Destructor Documentation
FTraitUpdateState() [1/2]
UE::AnimNext::FTraitUpdateState::FTraitUpdateState () default
Referenced by AsBlendingOut(), AsNewlyRelevant(), WithDeltaTime(), WithTimeScale(), WithTrajectoryWeight(), and WithWeight().
FTraitUpdateState() [2/2]
UE::AnimNext::FTraitUpdateState::FTraitUpdateState (float InDeltaTime) inline explicit
Definition at line 87 of file IUpdate.h.
References DeltaTime.
Member Function Documentation
AsBlendingOut()
FTraitUpdateState UE::AnimNext::FTraitUpdateState::AsBlendingOut (bool InIsBlendingOut = true) const inline nodiscard
Definition at line 139 of file IUpdate.h.
References FTraitUpdateState().
AsNewlyRelevant()
FTraitUpdateState UE::AnimNext::FTraitUpdateState::AsNewlyRelevant (bool InIsNewlyRelevant = true) const inline nodiscard
Definition at line 147 of file IUpdate.h.
References FTraitUpdateState().
GetDeltaTime()
float UE::AnimNext::FTraitUpdateState::GetDeltaTime () const inline
Definition at line 92 of file IUpdate.h.
References DeltaTime.
GetTotalTrajectoryWeight()
float UE::AnimNext::FTraitUpdateState::GetTotalTrajectoryWeight () const inline
Definition at line 98 of file IUpdate.h.
References TotalTrajectoryWeight.
GetTotalWeight()
float UE::AnimNext::FTraitUpdateState::GetTotalWeight () const inline
Definition at line 95 of file IUpdate.h.
References TotalWeight.
IsBlendingOut()
bool UE::AnimNext::FTraitUpdateState::IsBlendingOut () const inline
Definition at line 101 of file IUpdate.h.
References bIsBlendingOut.
IsNewlyRelevant()
bool UE::AnimNext::FTraitUpdateState::IsNewlyRelevant () const inline
Definition at line 104 of file IUpdate.h.
References bIsNewlyRelevant.
WithDeltaTime()
FTraitUpdateState UE::AnimNext::FTraitUpdateState::WithDeltaTime (float InDeltaTime) const inline nodiscard
Definition at line 131 of file IUpdate.h.
References FTraitUpdateState().
WithTimeScale()
FTraitUpdateState UE::AnimNext::FTraitUpdateState::WithTimeScale (float TimeScale) const inline nodiscard
Definition at line 123 of file IUpdate.h.
References FTraitUpdateState().
WithTrajectoryWeight()
FTraitUpdateState UE::AnimNext::FTraitUpdateState::WithTrajectoryWeight (float Weight) const inline nodiscard
Definition at line 115 of file IUpdate.h.
References FTraitUpdateState(), and Weight.
WithWeight()
FTraitUpdateState UE::AnimNext::FTraitUpdateState::WithWeight (float Weight) const inline nodiscard
Definition at line 107 of file IUpdate.h.
References FTraitUpdateState(), and Weight.
Field Documentation
bIsBlendingOut
int8 UE::AnimNext::FTraitUpdateState::bIsBlendingOut = false private
Definition at line 165 of file IUpdate.h.
Referenced by IsBlendingOut().
bIsNewlyRelevant
int8 UE::AnimNext::FTraitUpdateState::bIsNewlyRelevant = false private
Definition at line 168 of file IUpdate.h.
Referenced by IsNewlyRelevant().
DeltaTime
float UE::AnimNext::FTraitUpdateState::DeltaTime = 0.0f private
Definition at line 156 of file IUpdate.h.
Referenced by FTraitUpdateState(), and GetDeltaTime().
TotalTrajectoryWeight
float UE::AnimNext::FTraitUpdateState::TotalTrajectoryWeight = 1.0f private
Definition at line 162 of file IUpdate.h.
Referenced by GetTotalTrajectoryWeight().
TotalWeight
float UE::AnimNext::FTraitUpdateState::TotalWeight = 1.0f private
Definition at line 159 of file IUpdate.h.
Referenced by GetTotalWeight().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitInterfaces/IUpdate.h