Unreal Engine 5.6 C++ API: TBlendableTokenStack< DataType > Struct Template Reference
TBlendableTokenStack< DataType > Struct Template Reference
Implementation of a blendable token stack for any given data type.
#include "BlendableTokenStack.h"
Public Member Functions
TBlendableTokenStack ()
void AddToken (const TBlendableToken< DataType > *TokenToAdd)
Conditionally add a token to this stack if it has a >= hierarchical bias, removing anything of a lower bias.
virtual void ComputeAndActuate (UObject *InObject, FMovieSceneBlendingAccumulator &Accumulator, FMovieSceneBlendingActuatorID InActuatorType, const FMovieSceneContext &Context, FPersistentEvaluationData &PersistentData, IMovieScenePlayer &Player) override final
Implemented by typed stacks to compute the final blended value for its data, and apply that result to the specified object.
virtual void Interrogate (UObject *AnimatedObject, FMovieSceneInterrogationData &InterrogationData, FMovieSceneBlendingAccumulator &Accumulator, FMovieSceneBlendingActuatorID ActuatorTypeID, const FMovieSceneContext &Context) override final
Implemented by typed stacks to interrogate the final blended value for its data.
template<typename... T>
void SavePreAnimatedState (IMovieScenePlayer &Player, T &&... Args) const
Helper function for saving pre-animated state for all entites that want RestoreState and relate to the current token stack.
template<typename... T>
void SavePreAnimatedStateForAllEntities (IMovieScenePlayer &Player, T &&... Args) const
Helper function for saving pre-animated state for all entites that contributed to this stack, regardless of whether they want restore state or not.
Public Member Functions inherited from IBlendableTokenStack
virtual ~IBlendableTokenStack ()
Virtual destructor.
Data Fields
int32 CurrentBias
The highest encountered hierarchical bias.
TArray< const TBlendableToken< DataType > * > Tokens
This stack's typed blendable tokens.
Data Fields inherited from IBlendableTokenStack
FMovieSceneAnimTypeID DataTypeID
The type of data that this stack contains.
Private Member Functions
template<typename... T>
void SavePreAnimatedStateImpl (IMovieScenePlayer &Player, TOptional< EMovieSceneCompletionMode > CompletionModeOverride, T &&... Args) const
Additional Inherited Members
Protected Member Functions inherited from IBlendableTokenStack
IBlendableTokenStack (FMovieSceneAnimTypeID InDataTypeID)
Constructor.
Detailed Description
template<typename DataType>
struct TBlendableTokenStack< DataType >
Implementation of a blendable token stack for any given data type.
Definition at line 82 of file BlendableTokenStack.h.
Constructor & Destructor Documentation
TBlendableTokenStack()
template<typename DataType> TBlendableTokenStack< DataType >::TBlendableTokenStack () inline
Definition at line 90 of file BlendableTokenStack.h.
References IBlendableTokenStack::IBlendableTokenStack(), CurrentBias, GetBlendingDataType(), and Lowest.
Member Function Documentation
AddToken()
template<typename DataType> void TBlendableTokenStack< DataType >::AddToken (const TBlendableToken< DataType > * TokenToAdd) inline
Conditionally add a token to this stack if it has a >= hierarchical bias, removing anything of a lower bias.
Parameters
TokenToAdd The token to add
Definition at line 97 of file BlendableTokenStack.h.
References check, CurrentBias, TBlendableToken< DataType >::HierarchicalBias, and Tokens.
Referenced by FMovieSceneAccumulatedBlendState::TTokenEntry< DataType >::Consolidate().
ComputeAndActuate()
template<typename DataType> virtual void TBlendableTokenStack< DataType >::ComputeAndActuate (UObject * InObject, FMovieSceneBlendingAccumulator & Accumulator, FMovieSceneBlendingActuatorID InActuatorType, const FMovieSceneContext & Context, FPersistentEvaluationData & PersistentData, IMovieScenePlayer & Player) final override virtual
Implemented by typed stacks to compute the final blended value for its data, and apply that result to the specified object.
Parameters
InObject The object to apply the result to. Nullptr for root track data.
Accumulator The accumulator that was used to gather and consolidate the blendable tokens
ActuatorTypeID A unique identifier to the actuator that should be used to apply the result to the object
Context Root-level movie scene evaluation context for the current frame
PersistentData Persistent data store for the evaluation
Player The player that is responsible for playing back the sequence
Implements IBlendableTokenStack.
Interrogate()
template<typename DataType> virtual void TBlendableTokenStack< DataType >::Interrogate (UObject * AnimatedObject, FMovieSceneInterrogationData & InterrogationData, FMovieSceneBlendingAccumulator & Accumulator, FMovieSceneBlendingActuatorID ActuatorTypeID, const FMovieSceneContext & Context) final override virtual
Implemented by typed stacks to interrogate the final blended value for its data.
Parameters
AnimatedObject The object that the value should be interrogated for
InterrogationData The interrogation data to populate
Accumulator The accumulator that was used to gather and consolidate the blendable tokens
ActuatorTypeID A unique identifier to the actuator that should be used to apply the result to the object
Context Root-level movie scene evaluation context for the current frame
Implements IBlendableTokenStack.
SavePreAnimatedState()
template<typename DataType> template<typename... T> void TBlendableTokenStack< DataType >::SavePreAnimatedState (IMovieScenePlayer & Player, T &&... Args) const inline
Helper function for saving pre-animated state for all entites that want RestoreState and relate to the current token stack.
Parameters
Player The movie scene player that's playing back the sequence
Args Variable arguments that are forwarded to IMovieScenePlayer::SavePreAnimatedState
Definition at line 158 of file BlendableTokenStack.h.
References SavePreAnimatedStateImpl().
Referenced by TPropertyActuator< PropertyType >::Actuate().
SavePreAnimatedStateForAllEntities()
template<typename DataType> template<typename... T> void TBlendableTokenStack< DataType >::SavePreAnimatedStateForAllEntities (IMovieScenePlayer & Player, T &&... Args) const inline
Helper function for saving pre-animated state for all entites that contributed to this stack, regardless of whether they want restore state or not.
Parameters
Player The movie scene player that's playing back the sequence
Args Variable arguments that are forwarded to IMovieScenePlayer::SavePreAnimatedState
Definition at line 146 of file BlendableTokenStack.h.
References SavePreAnimatedStateImpl().
SavePreAnimatedStateImpl()
template<typename DataType> template<typename... T> void TBlendableTokenStack< DataType >::SavePreAnimatedStateImpl (IMovieScenePlayer & Player, TOptional< EMovieSceneCompletionMode > CompletionModeOverride, T &&... Args) const inline private
Definition at line 166 of file BlendableTokenStack.h.
References Forward(), TOptional< OptionalType >::Get(), IMovieScenePlayer::PreAnimatedState, IMovieScenePlayer::SavePreAnimatedState(), and Tokens.
Referenced by SavePreAnimatedState(), and SavePreAnimatedStateForAllEntities().
Field Documentation
CurrentBias
template<typename DataType> int32 TBlendableTokenStack< DataType >::CurrentBias
The highest encountered hierarchical bias.
Definition at line 88 of file BlendableTokenStack.h.
Referenced by TBlendableTokenStack(), and AddToken().
Tokens
template<typename DataType> TArray<const TBlendableToken<DataType>*> TBlendableTokenStack< DataType >::Tokens
This stack's typed blendable tokens.
Definition at line 85 of file BlendableTokenStack.h.
Referenced by AddToken(), and SavePreAnimatedStateImpl().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/Blending/BlendableTokenStack.h