Unreal Engine 5.6 C++ API: UE::StateTree::FActiveFrameID Struct Reference
UE::StateTree::FActiveFrameID Struct Reference
A unique ID for FStateTreeExecutionFrame.
#include "StateTreeStatePath.h"
Public Member Functions
FActiveFrameID ()=default
FActiveFrameID (uint32 NewID)
bool IsValid () const
bool operator!= (const FActiveFrameID &) const =default
bool operator== (const FActiveFrameID &) const =default
Static Public Attributes
static STATETREEMODULE_API const FActiveFrameID Invalid
Private Attributes
uint32 Value = InvalidValue
Static Private Attributes
static constexpr uint32 InvalidValue = 0
Detailed Description
A unique ID for FStateTreeExecutionFrame.
Definition at line 17 of file StateTreeStatePath.h.
Constructor & Destructor Documentation
FActiveFrameID() [1/2]
UE::StateTree::FActiveFrameID::FActiveFrameID () explicit default
Referenced by operator!=(), and operator==().
FActiveFrameID() [2/2]
UE::StateTree::FActiveFrameID::FActiveFrameID (uint32 NewID) inline explicit
Definition at line 26 of file StateTreeStatePath.h.
References check, InvalidValue, and Value.
Member Function Documentation
IsValid()
bool UE::StateTree::FActiveFrameID::IsValid () const inline nodiscard
Definition at line 35 of file StateTreeStatePath.h.
References InvalidValue, and Value.
operator!=()
bool UE::StateTree::FActiveFrameID::operator!= (const FActiveFrameID &) const nodiscard default
References FActiveFrameID().
operator==()
bool UE::StateTree::FActiveFrameID::operator== (const FActiveFrameID &) const nodiscard default
References FActiveFrameID().
Field Documentation
Invalid
STATETREEMODULE_API const FActiveFrameID UE::StateTree::FActiveFrameID::Invalid static
Definition at line 23 of file StateTreeStatePath.h.
InvalidValue
uint32 UE::StateTree::FActiveFrameID::InvalidValue = 0 static constexpr private
Definition at line 20 of file StateTreeStatePath.h.
Referenced by FActiveFrameID(), and IsValid().
Value
uint32 UE::StateTree::FActiveFrameID::Value = InvalidValue private
Definition at line 41 of file StateTreeStatePath.h.
Referenced by FActiveFrameID(), and IsValid().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreeStatePath.h