Unreal Engine 5.6 C++ API: FComponentQueryParams Struct Reference
FComponentQueryParams Struct Reference
Structure when performing a collision query using a component's geometry.
#include "CollisionQueryParams.h"
Public Member Functions
FComponentQueryParams ()
FComponentQueryParams (FName InTraceTag, const AActor *InIgnoreActor=NULL, const FCollisionEnabledMask InShapeCollisionMask=0)
FComponentQueryParams (FName InTraceTag, const TStatId &InStatId, const AActor *InIgnoreActor=NULL, const FCollisionEnabledMask InShapeCollisionMask=0)
Public Member Functions inherited from FCollisionQueryParams
FCollisionQueryParams ()
FCollisionQueryParams (FName InTraceTag, bool bInTraceComplex=false, const AActor *InIgnoreActor=NULL)
FCollisionQueryParams (FName InTraceTag, const TStatId &InStatId, bool bInTraceComplex=false, const AActor *InIgnoreActor=NULL)
void AddIgnoredActor (const AActor *InIgnoreActor)
Add an actor for this trace to ignore.
void AddIgnoredActor (const uint32 InIgnoreActorID)
Add an actor by ID for this trace to ignore.
void AddIgnoredActors (const TArray< AActor * > &InIgnoreActors)
Add a collection of actors for this trace to ignore.
void AddIgnoredActors (const TArray< const AActor * > &InIgnoreActors)
void AddIgnoredActors (const TArray< TWeakObjectPtr< const AActor > > &InIgnoreActors)
void AddIgnoredComponent (const FRemoteObjectReference &InComponentRef)
void AddIgnoredComponent (const TWeakObjectPtr< UPrimitiveComponent > &InIgnoreComponent)
void AddIgnoredComponent (const UPrimitiveComponent *InIgnoreComponent)
Add a component for this trace to ignore.
void AddIgnoredComponent_LikelyDuplicatedRoot (const UPrimitiveComponent *InIgnoreComponent)
Special variant that hints that we are likely adding a duplicate of the root component or first ignored component.
void AddIgnoredComponents (const TArray< TWeakObjectPtr< UPrimitiveComponent > > &InIgnoreComponents)
Variant that uses an array of TWeakObjectPtrs.
void AddIgnoredComponents (const TArray< UPrimitiveComponent * > &InIgnoreComponents)
Add a collection of components for this trace to ignore.
void AddIgnoredSourceObject (const FRemoteObjectReference &ObjectRef)
void AddIgnoredSourceObject (const TWeakObjectPtr< const UObject > &InIgnoreObject)
void AddIgnoredSourceObject (const uint32 InIgnoreActorID)
Add a source object for this trace to ignore.
void AddIgnoredSourceObject (const UObject *InIgnoreActor)
Add a source object for this trace to ignore.
void AddIgnoredSourceObjects (const TArray< const UObject * > &InIgnoreObjects)
void AddIgnoredSourceObjects (const TArray< TWeakObjectPtr< const UObject > > &InIgnoreObjects)
void AddIgnoredSourceObjects (const TArray< UObject * > &InIgnoreObjects)
Add a collection of source objects for this trace to ignore.
void ClearIgnoredComponents ()
Clears the set of components to ignore during the trace.
void ClearIgnoredSourceObjects ()
Clears the set of source objects (such as actors) to ignore during the trace.
const IgnoreComponentsArrayType & GetIgnoredComponents () const
Returns set of unique components to ignore during the trace.
const IgnoreActorsArrayType & GetIgnoredSourceObjects () const
Returns the set of source objects (such as actors) to ignore during the trace.
UE_INTERNAL void Internal_AddIgnoredComponent (const uint32 ComponentID)
Add a component (by id) for this trace to ignore.
void SetNumIgnoredComponents (int32 NewNum)
Set the number of ignored components in the list.
FString ToString () const
UE_DEPRECATED (5.5, "Use ClearIgnoredSourceObjects instead.") void ClearIgnoredActors()
Clears the set of actors to ignore during the trace.
UE_DEPRECATED (5.5, "Use GetIgnoredSourceObjects instead.") const IgnoreActorsArrayType &GetIgnoredActors() const
Returns set of source objects (including actors) to ignore during the trace.
Data Fields
FCollisionEnabledMask ShapeCollisionMask
Only use query shapes which remain unmasked by this collision mask (if mask is nonzero)
Data Fields inherited from FCollisionQueryParams
bool bDebugQuery
bool bFindInitialOverlaps
Whether we want to find out initial overlap or not.
bool bIgnoreBlocks
Whether to ignore blocking results.
bool bIgnoreTouches
Whether to ignore touch/overlap results.
bool bReplaceHitWithSubComponents
If bTraceIntoSubComponents is true, whether to replace the hit of the cluster union with its children instead.
bool bReturnFaceIndex
Whether we want to return the triangle face index for complex static mesh traces.
bool bReturnPhysicalMaterial
Whether we want to include the physical material in the results.
bool bSkipNarrowPhase
Whether to skip narrow phase checks (only for overlaps).
bool bTraceComplex
Whether we should trace against complex collision.
bool bTraceIntoSubComponents
Whether to ignore traces to the cluster union and trace against its children instead.
FMaskFilter IgnoreMask
Extra filtering done on the query.
EQueryMobilityType MobilityType
Filters query by mobility types (static vs stationary/movable)
FName OwnerTag
Tag used to indicate an owner for this trace.
TStatId StatId
StatId used for profiling individual expensive scene queries.
FName TraceTag
Tag used to provide extra information or filtering for debugging of the trace (e.g.
Static Public Attributes
static FComponentQueryParams DefaultComponentQueryParams
static variable for default data to be used without reconstructing everytime
Static Public Attributes inherited from FCollisionQueryParams
static FCollisionQueryParams DefaultQueryParam
static variable for default data to be used without reconstructing everytime
Additional Inherited Members
Public Types inherited from FCollisionQueryParams
typedef IgnoreSourceObjectsArrayType IgnoreActorsArrayType
typedef TArray< uint32, TInlineAllocator< 8 > > IgnoreComponentsArrayType
TArray typedef of components to ignore.
typedef TArray< uint32, TInlineAllocator< 4 > > IgnoreSourceObjectsArrayType
TArray typedef of actors to ignore.
Static Public Member Functions inherited from FCollisionQueryParams
static FORCEINLINE TStatId GetUnknownStatId ()
Detailed Description
Structure when performing a collision query using a component's geometry.
Definition at line 296 of file CollisionQueryParams.h.
Constructor & Destructor Documentation
FComponentQueryParams() [1/3]
FComponentQueryParams::FComponentQueryParams () inline
Definition at line 299 of file CollisionQueryParams.h.
References FCollisionQueryParams::FCollisionQueryParams(), and FCollisionQueryParams::GetUnknownStatId().
Referenced by FComponentQueryParams().
FComponentQueryParams() [2/3]
FComponentQueryParams::FComponentQueryParams (FName InTraceTag, const AActor * InIgnoreActor = NULL, const FCollisionEnabledMask InShapeCollisionMask = 0) inline
Definition at line 304 of file CollisionQueryParams.h.
References FComponentQueryParams(), and FCollisionQueryParams::GetUnknownStatId().
FComponentQueryParams() [3/3]
FComponentQueryParams::FComponentQueryParams (FName InTraceTag, const TStatId & InStatId, const AActor * InIgnoreActor = NULL, const FCollisionEnabledMask InShapeCollisionMask = 0) inline
Definition at line 310 of file CollisionQueryParams.h.
References FCollisionQueryParams::FCollisionQueryParams(), and ShapeCollisionMask.
Field Documentation
DefaultComponentQueryParams
FComponentQueryParams FComponentQueryParams::DefaultComponentQueryParams static
static variable for default data to be used without reconstructing everytime
Definition at line 319 of file CollisionQueryParams.h.
ShapeCollisionMask
FCollisionEnabledMask FComponentQueryParams::ShapeCollisionMask
Only use query shapes which remain unmasked by this collision mask (if mask is nonzero)
Definition at line 316 of file CollisionQueryParams.h.
Referenced by FComponentQueryParams().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/CollisionQueryParams.h