Unreal Engine 5.6 C++ API: FManifestContext Struct Reference
FManifestContext Struct Reference
#include "InternationalizationManifest.h"
Public Member Functions
FManifestContext ()
FManifestContext (const FLocKey &InKey)
FManifestContext (const FManifestContext &Other)
Copy ctor.
bool operator!= (const FManifestContext &Other) const
bool operator< (const FManifestContext &Other) const
FManifestContext & operator= (const FManifestContext &Other)
bool operator== (const FManifestContext &Other) const
Data Fields
bool bIsOptional
TSharedPtr< FLocMetadataObject > InfoMetadataObj
FLocKey Key
TSharedPtr< FLocMetadataObject > KeyMetadataObj
FName PlatformName
FString SourceLocation
Detailed Description
Definition at line 18 of file InternationalizationManifest.h.
Constructor & Destructor Documentation
FManifestContext() [1/3]
FManifestContext::FManifestContext () inline
Definition at line 21 of file InternationalizationManifest.h.
References bIsOptional, Key, PlatformName, and SourceLocation.
Referenced by FManifestContext(), operator!=(), operator<(), operator=(), and operator==().
FManifestContext() [2/3]
FManifestContext::FManifestContext (const FLocKey & InKey) inline explicit
Definition at line 29 of file InternationalizationManifest.h.
References bIsOptional, Key, PlatformName, and SourceLocation.
FManifestContext() [3/3]
FManifestContext::FManifestContext (const FManifestContext & Other)
Copy ctor.
References FManifestContext(), and Other.
Member Function Documentation
operator!=()
bool FManifestContext::operator!= (const FManifestContext & Other) const inline
Definition at line 42 of file InternationalizationManifest.h.
References FManifestContext(), and Other.
operator<()
bool FManifestContext::operator< (const FManifestContext & Other) const
References FManifestContext(), and Other.
operator=()
FManifestContext & FManifestContext::operator= (const FManifestContext & Other)
References FManifestContext(), and Other.
operator==()
bool FManifestContext::operator== (const FManifestContext & Other) const
References FManifestContext(), and Other.
Field Documentation
bIsOptional
bool FManifestContext::bIsOptional
Definition at line 49 of file InternationalizationManifest.h.
Referenced by FManifestContext(), and FManifestContext().
InfoMetadataObj
TSharedPtr<FLocMetadataObject> FManifestContext::InfoMetadataObj
Definition at line 51 of file InternationalizationManifest.h.
Key
FLocKey FManifestContext::Key
Definition at line 46 of file InternationalizationManifest.h.
Referenced by FManifestContext(), and FManifestContext().
KeyMetadataObj
TSharedPtr<FLocMetadataObject> FManifestContext::KeyMetadataObj
Definition at line 52 of file InternationalizationManifest.h.
PlatformName
FName FManifestContext::PlatformName
Definition at line 48 of file InternationalizationManifest.h.
Referenced by FManifestContext(), and FManifestContext().
SourceLocation
FString FManifestContext::SourceLocation
Definition at line 47 of file InternationalizationManifest.h.
Referenced by FManifestContext(), and FManifestContext().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Internationalization/InternationalizationManifest.h