Unreal Engine 5.6 C++ API: FMovieSceneBlenderSystemID Struct Reference
FMovieSceneBlenderSystemID Struct Reference
Identifier for a type of blender system (e.g.
#include "MovieSceneBlenderSystemTypes.h"
Public Member Functions
FMovieSceneBlenderSystemID ()
FMovieSceneBlenderSystemID (uint8 InValue)
bool IsValid () const
Static Public Attributes
static FMovieSceneBlenderSystemID Invalid
Private Attributes
uint8 Value
Friends
uint32 GetTypeHash (FMovieSceneBlenderSystemID SystemID)
bool operator< (FMovieSceneBlenderSystemID A, FMovieSceneBlenderSystemID B)
bool operator== (FMovieSceneBlenderSystemID A, FMovieSceneBlenderSystemID B)
Detailed Description
Identifier for a type of blender system (e.g.
float blender, integer blender, etc.)
Definition at line 19 of file MovieSceneBlenderSystemTypes.h.
Constructor & Destructor Documentation
FMovieSceneBlenderSystemID() [1/2]
FMovieSceneBlenderSystemID::FMovieSceneBlenderSystemID () inline
Definition at line 23 of file MovieSceneBlenderSystemTypes.h.
References Max, and Value.
Referenced by GetTypeHash, operator<, and operator==.
FMovieSceneBlenderSystemID() [2/2]
FMovieSceneBlenderSystemID::FMovieSceneBlenderSystemID (uint8 InValue) inline explicit
Definition at line 24 of file MovieSceneBlenderSystemTypes.h.
References Value.
Member Function Documentation
IsValid()
bool FMovieSceneBlenderSystemID::IsValid () const inline
Definition at line 26 of file MovieSceneBlenderSystemTypes.h.
References Invalid, and Value.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FMovieSceneBlenderSystemID SystemID) friend
Definition at line 28 of file MovieSceneBlenderSystemTypes.h.
References FMovieSceneBlenderSystemID(), GetTypeHash, and Value.
Referenced by GetTypeHash.
operator<
bool operator< (FMovieSceneBlenderSystemID A, FMovieSceneBlenderSystemID B) friend
Definition at line 38 of file MovieSceneBlenderSystemTypes.h.
References FMovieSceneBlenderSystemID(), A, and B.
operator==
bool operator== (FMovieSceneBlenderSystemID A, FMovieSceneBlenderSystemID B) friend
Definition at line 33 of file MovieSceneBlenderSystemTypes.h.
References FMovieSceneBlenderSystemID(), A, and B.
Field Documentation
Invalid
FMovieSceneBlenderSystemID FMovieSceneBlenderSystemID::Invalid static
Definition at line 21 of file MovieSceneBlenderSystemTypes.h.
Referenced by IsValid().
Value
uint8 FMovieSceneBlenderSystemID::Value private
Definition at line 44 of file MovieSceneBlenderSystemTypes.h.
Referenced by FMovieSceneBlenderSystemID(), FMovieSceneBlenderSystemID(), GetTypeHash, and IsValid().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneBlenderSystemTypes.h