Unreal Engine 5.6 C++ API: FDelinquencyAnalytics Struct Reference
FDelinquencyAnalytics Struct Reference
Convenience type that can be used to tracks information about things that can result in prolonged periods of apparent network inactivity, despite actually receiving traffic.
#include "NetAnalyticsTypes.h"
Public Member Functions
FDelinquencyAnalytics (const FDelinquencyAnalytics &)=delete
FDelinquencyAnalytics (const uint32 InNumberOfTopOffendersToTrack)
FDelinquencyAnalytics (FDelinquencyAnalytics &&Other)
void Add (FDelinquencyNameTimePair &&ToTrack)
Adds the event to the delinquency tracking, by accumulating its time into total time, and updating any existing events to choose the one with the highest time.
void CountBytes (class FArchive &Ar) const
void Emplace (FName Name, float TimeSeconds)
const TSet< FDelinquencyNameTimePair, FDelinquencyKeyFuncs > & GetAllDelinquents () const
const uint32 GetNumberOfTopOffendersToTrack () const
const TArray< FDelinquencyNameTimePair > & GetTopOffenders () const
const float GetTotalTime () const
const FDelinquencyAnalytics & operator= (const FDelinquencyAnalytics &)=delete
FDelinquencyAnalytics & operator= (FDelinquencyAnalytics &&)=default
void Reset ()
Private Attributes
TSet< FDelinquencyNameTimePair, FDelinquencyKeyFuncs > AllDelinquents
uint32 NumberOfTopOffendersToTrack
TArray< FDelinquencyNameTimePair > TopOffenders
float TotalTime
Detailed Description
Convenience type that can be used to tracks information about things that can result in prolonged periods of apparent network inactivity, despite actually receiving traffic.
The overall number of entries is expected to be small, but ultimately is left up to callers.
Definition at line 59 of file NetAnalyticsTypes.h.
Constructor & Destructor Documentation
FDelinquencyAnalytics() [1/3]
FDelinquencyAnalytics::FDelinquencyAnalytics (const uint32 InNumberOfTopOffendersToTrack) explicit
Referenced by FDelinquencyAnalytics(), FDelinquencyAnalytics(), operator=(), and operator=().
FDelinquencyAnalytics() [2/3]
FDelinquencyAnalytics::FDelinquencyAnalytics (FDelinquencyAnalytics && Other)
References FDelinquencyAnalytics(), and Other.
FDelinquencyAnalytics() [3/3]
FDelinquencyAnalytics::FDelinquencyAnalytics (const FDelinquencyAnalytics &) delete
References FDelinquencyAnalytics().
Member Function Documentation
Add()
void FDelinquencyAnalytics::Add (FDelinquencyNameTimePair && ToTrack)
Adds the event to the delinquency tracking, by accumulating its time into total time, and updating any existing events to choose the one with the highest time.
When NumberOfTopOffendersToTrack == 0, we will just track the set of all events as well as the total time.
When NumberOfTopOffendersToTrack > 0, we will track the set, total time, and also maintain sorted list (highest to lowest) of events that occurred.
By setting NumberOfTopOffendersToTrack to 0, users can manage their own lists of "TopOffenders", or otherwise avoid the per add overhead of this tracking.
CountBytes()
void FDelinquencyAnalytics::CountBytes (class FArchive & Ar) const
References Ar.
Emplace()
void FDelinquencyAnalytics::Emplace (FName Name, float TimeSeconds) inline
Definition at line 71 of file NetAnalyticsTypes.h.
References Add, and Name.
GetAllDelinquents()
const TSet< FDelinquencyNameTimePair, FDelinquencyKeyFuncs > & FDelinquencyAnalytics::GetAllDelinquents () const inline
Definition at line 95 of file NetAnalyticsTypes.h.
References AllDelinquents.
GetNumberOfTopOffendersToTrack()
const uint32 FDelinquencyAnalytics::GetNumberOfTopOffendersToTrack () const inline
Definition at line 105 of file NetAnalyticsTypes.h.
References NumberOfTopOffendersToTrack.
GetTopOffenders()
const TArray< FDelinquencyNameTimePair > & FDelinquencyAnalytics::GetTopOffenders () const inline
Definition at line 90 of file NetAnalyticsTypes.h.
References TopOffenders.
GetTotalTime()
const float FDelinquencyAnalytics::GetTotalTime () const inline
Definition at line 100 of file NetAnalyticsTypes.h.
References TotalTime.
operator=() [1/2]
const FDelinquencyAnalytics & FDelinquencyAnalytics::operator= (const FDelinquencyAnalytics &) delete
References FDelinquencyAnalytics().
operator=() [2/2]
FDelinquencyAnalytics & FDelinquencyAnalytics::operator= (FDelinquencyAnalytics &&) default
References FDelinquencyAnalytics().
Reset()
void FDelinquencyAnalytics::Reset ()
Field Documentation
AllDelinquents
TSet<FDelinquencyNameTimePair, FDelinquencyKeyFuncs> FDelinquencyAnalytics::AllDelinquents private
Definition at line 117 of file NetAnalyticsTypes.h.
Referenced by GetAllDelinquents().
NumberOfTopOffendersToTrack
uint32 FDelinquencyAnalytics::NumberOfTopOffendersToTrack private
Definition at line 121 of file NetAnalyticsTypes.h.
Referenced by GetNumberOfTopOffendersToTrack().
TopOffenders
TArray<FDelinquencyNameTimePair> FDelinquencyAnalytics::TopOffenders private
Definition at line 116 of file NetAnalyticsTypes.h.
Referenced by GetTopOffenders().
TotalTime
float FDelinquencyAnalytics::TotalTime private
Definition at line 118 of file NetAnalyticsTypes.h.
Referenced by GetTotalTime().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Net/NetAnalyticsTypes.h