Unreal Engine 5.6 C++ API: FCollisionEnabledMask Struct Reference
FCollisionEnabledMask Struct Reference
#include "EngineTypes.h"
Public Member Functions
FCollisionEnabledMask (ECollisionEnabled::Type CollisionEnabled)
FCollisionEnabledMask (int8 InBits=0)
operator bool () const
operator int8 () const
FCollisionEnabledMask operator& (const ECollisionEnabled::Type Other) const
FCollisionEnabledMask operator& (const FCollisionEnabledMask Other) const
FCollisionEnabledMask operator| (const ECollisionEnabled::Type Other) const
FCollisionEnabledMask operator| (const FCollisionEnabledMask Other) const
Data Fields
int8 Bits
Detailed Description
Definition at line 1554 of file EngineTypes.h.
Constructor & Destructor Documentation
FCollisionEnabledMask() [1/2]
FCollisionEnabledMask::FCollisionEnabledMask (int8 InBits = 0)
Referenced by operator&(), operator&(), operator|(), and operator|().
FCollisionEnabledMask() [2/2]
FCollisionEnabledMask::FCollisionEnabledMask (ECollisionEnabled::Type CollisionEnabled)
Member Function Documentation
operator bool()
FCollisionEnabledMask::operator bool () const
operator int8()
FCollisionEnabledMask::operator int8 () const
operator&() [1/2]
FCollisionEnabledMask FCollisionEnabledMask::operator& (const ECollisionEnabled::Type Other) const
References FCollisionEnabledMask(), and Other.
operator&() [2/2]
FCollisionEnabledMask FCollisionEnabledMask::operator& (const FCollisionEnabledMask Other) const
References FCollisionEnabledMask(), and Other.
operator|() [1/2]
FCollisionEnabledMask FCollisionEnabledMask::operator| (const ECollisionEnabled::Type Other) const
References FCollisionEnabledMask(), and Other.
operator|() [2/2]
FCollisionEnabledMask FCollisionEnabledMask::operator| (const FCollisionEnabledMask Other) const
References FCollisionEnabledMask(), and Other.
Field Documentation
Bits
int8 FCollisionEnabledMask::Bits
Definition at line 1556 of file EngineTypes.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Engine/EngineTypes.h