Unreal Engine 5.6 C++ API: FText3DRange Struct Reference
FText3DRange Struct Reference
#include "Text3DEffectExtensionBase.h"
Public Member Functions
FText3DRange ()=default
FText3DRange (uint16 InStartIndex, uint16 InCount)
bool IsEndUnbound () const
bool IsInRange (uint16 InIndex) const
bool IsStartUnbound () const
bool IsUnbound () const
Data Fields
uint16 Count = Unbound
uint16 StartIndex = Unbound
Static Public Attributes
static constexpr uint16 Unbound = std::numeric_limits<uint16>::max()
Detailed Description
Definition at line 9 of file Text3DEffectExtensionBase.h.
Constructor & Destructor Documentation
FText3DRange() [1/2]
FText3DRange::FText3DRange () default
FText3DRange() [2/2]
FText3DRange::FText3DRange (uint16 InStartIndex, uint16 InCount) inline explicit
Definition at line 14 of file Text3DEffectExtensionBase.h.
References Count, and StartIndex.
Member Function Documentation
IsEndUnbound()
bool FText3DRange::IsEndUnbound () const inline
Definition at line 25 of file Text3DEffectExtensionBase.h.
References Count, and Unbound.
Referenced by IsInRange(), and IsUnbound().
IsInRange()
bool FText3DRange::IsInRange (uint16 InIndex) const inline
Definition at line 35 of file Text3DEffectExtensionBase.h.
References Count, IsEndUnbound(), IsStartUnbound(), IsUnbound(), and StartIndex.
IsStartUnbound()
bool FText3DRange::IsStartUnbound () const inline
Definition at line 30 of file Text3DEffectExtensionBase.h.
References StartIndex, and Unbound.
Referenced by IsInRange(), and IsUnbound().
IsUnbound()
bool FText3DRange::IsUnbound () const inline
Definition at line 20 of file Text3DEffectExtensionBase.h.
References IsEndUnbound(), and IsStartUnbound().
Referenced by IsInRange().
Field Documentation
Count
uint16 FText3DRange::Count = Unbound
Definition at line 44 of file Text3DEffectExtensionBase.h.
Referenced by FText3DRange(), IsEndUnbound(), and IsInRange().
StartIndex
uint16 FText3DRange::StartIndex = Unbound
Definition at line 43 of file Text3DEffectExtensionBase.h.
Referenced by FText3DRange(), IsInRange(), and IsStartUnbound().
Unbound
uint16 FText3DRange::Unbound = std::numeric_limits<uint16>::max() static constexpr
Definition at line 11 of file Text3DEffectExtensionBase.h.
Referenced by IsEndUnbound(), and IsStartUnbound().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/Text3D/Source/Text3D/Public/Extensions/Text3DEffectExtensionBase.h