Unreal Engine 5.6 C++ API: UE::Geometry::TQuaternion< RealType > Struct Template Reference
UE::Geometry::TQuaternion< RealType > Struct Template Reference
#include "Quaternion.h"
Public Member Functions
TQuaternion ()
TQuaternion (const FQuat4d &Quat)
TQuaternion (const FQuat4f &Quat)
TQuaternion (const FRotator &Rotator)
TQuaternion (const RealType *Values)
TQuaternion (const TMatrix3< RealType > &RotationMatrix)
PRAGMA_DISABLE_DEPRECATION_WARNINGS TQuaternion (const TQuaternion &Copy)=default
TQuaternion (const TQuaternion< RealType > &From, const TQuaternion< RealType > &To, RealType InterpT)
template<typename RealType2>
PRAGMA_ENABLE_DEPRECATION_WARNINGS TQuaternion (const TQuaternion< RealType2 > &Copy)
template<typename RealType2>
TQuaternion (const TQuaternion< RealType2 > &Copy)
TQuaternion (const TVector< RealType > &Axis, RealType Angle, bool bAngleIsDegrees)
TQuaternion (const TVector< RealType > &From, const TVector< RealType > &To)
TQuaternion (RealType X, RealType Y, RealType Z, RealType W)
TVector< RealType > AxisX () const
TVector< RealType > AxisY () const
TVector< RealType > AxisZ () const
RealType Dot (const TQuaternion< RealType > &Other) const
bool EpsilonEqual (const TQuaternion< RealType > &Other, RealType Tolerance=TMathUtil< RealType >::ZeroTolerance) const
void GetAxes (TVector< RealType > &X, TVector< RealType > &Y, TVector< RealType > &Z) const
TQuaternion< RealType > Inverse () const
TVector< RealType > InverseMultiply (const TVector< RealType > &Other) const
bool IsIdentity (RealType Tolerance=TMathUtil< RealType >::ZeroTolerance) const
RealType Length () const
RealType Normalize (const RealType epsilon=0)
TQuaternion< RealType > Normalized (const RealType epsilon=0) const
operator FQuat4d () const
operator FQuat4f () const
operator FRotator () const
operator UE::Math::TVector4< RealType > () const
constexpr TQuaternion< RealType > operator- () const
TQuaternion & operator= (const TQuaternion &Copy)=default
RealType & operator[] (int i)
const RealType & operator[] (int i) const
void SetAxisAngleD (const TVector< RealType > &Axis, RealType AngleDeg)
void SetAxisAngleR (const TVector< RealType > &Axis, RealType AngleRad)
void SetFromRotationMatrix (const TMatrix3< RealType > &RotationMatrix)
void SetFromTo (const TVector< RealType > &From, const TVector< RealType > &To)
void SetToSlerp (TQuaternion< RealType > From, TQuaternion< RealType > To, RealType InterpT)
RealType SquaredLength () const
TMatrix3< RealType > ToRotationMatrix () const
Static Public Member Functions
static TQuaternion< RealType > Identity ()
static TQuaternion< RealType > Zero ()
Data Fields
union {
struct {
RealType W
RealType X
RealType Y
RealType Z
}
};
Detailed Description
template<typename RealType>
struct UE::Geometry::TQuaternion< RealType >
Definition at line 21 of file Quaternion.h.
Constructor & Destructor Documentation
TQuaternion() [1/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion ()
Definition at line 169 of file Quaternion.h.
References W, X, Y, and Z.
Referenced by TQuaternion(), Dot(), EpsilonEqual(), UE::Geometry::TQuaternion< float >::Identity(), Inverse(), Normalized(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::operator+(), UE::Geometry::operator-(), UE::Geometry::TQuaternion< float >::operator-(), SetToSlerp(), and UE::Geometry::TQuaternion< float >::Zero().
TQuaternion() [2/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (RealType X, RealType Y, RealType Z, RealType W)
Definition at line 175 of file Quaternion.h.
References W, X, Y, and Z.
TQuaternion() [3/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const RealType * Values) explicit
Definition at line 184 of file Quaternion.h.
References W, X, Y, and Z.
TQuaternion() [4/13]
template<typename RealType> PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::TQuaternion< RealType >::TQuaternion (const TQuaternion< RealType > & Copy) default
TQuaternion() [5/13]
template<typename RealType> template<typename RealType2> PRAGMA_ENABLE_DEPRECATION_WARNINGS UE::Geometry::TQuaternion< RealType >::TQuaternion (const TQuaternion< RealType2 > & Copy) explicit
TQuaternion() [6/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const TVector< RealType > & Axis, RealType Angle, bool bAngleIsDegrees)
Definition at line 203 of file Quaternion.h.
References Angle, Axis, SetAxisAngleR(), W, X, Y, and Z.
TQuaternion() [7/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const TVector< RealType > & From, const TVector< RealType > & To)
Definition at line 210 of file Quaternion.h.
References SetFromTo(), W, X, Y, and Z.
TQuaternion() [8/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const TQuaternion< RealType > & From, const TQuaternion< RealType > & To, RealType InterpT)
Definition at line 217 of file Quaternion.h.
References TQuaternion(), SetToSlerp(), W, X, Y, and Z.
TQuaternion() [9/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const TMatrix3< RealType > & RotationMatrix)
Definition at line 224 of file Quaternion.h.
References SetFromRotationMatrix(), W, X, Y, and Z.
TQuaternion() [10/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const FQuat4f & Quat) inline explicit
Definition at line 132 of file Quaternion.h.
TQuaternion() [11/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const FQuat4d & Quat) inline explicit
Definition at line 139 of file Quaternion.h.
TQuaternion() [12/13]
template<typename RealType> UE::Geometry::TQuaternion< RealType >::TQuaternion (const FRotator & Rotator) inline explicit
Definition at line 146 of file Quaternion.h.
TQuaternion() [13/13]
template<typename RealType> template<typename RealType2> UE::Geometry::TQuaternion< RealType >::TQuaternion (const TQuaternion< RealType2 > & Copy)
Definition at line 194 of file Quaternion.h.
Member Function Documentation
AxisX()
template<typename RealType> TVector< RealType > UE::Geometry::TQuaternion< RealType >::AxisX () const
Definition at line 345 of file Quaternion.h.
References W, X, Y, and Z.
AxisY()
template<typename RealType> TVector< RealType > UE::Geometry::TQuaternion< RealType >::AxisY () const
Definition at line 355 of file Quaternion.h.
References W, X, Y, and Z.
AxisZ()
template<typename RealType> TVector< RealType > UE::Geometry::TQuaternion< RealType >::AxisZ () const
Definition at line 364 of file Quaternion.h.
References W, X, Y, and Z.
Referenced by UE::Geometry::GetShape().
Dot()
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::Dot (const TQuaternion< RealType > & Other) const
Definition at line 264 of file Quaternion.h.
References TQuaternion(), Other, W, X, Y, and Z.
Referenced by SetToSlerp().
EpsilonEqual()
template<typename RealType> bool UE::Geometry::TQuaternion< RealType >::EpsilonEqual (const TQuaternion< RealType > & Other, RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) const
Definition at line 573 of file Quaternion.h.
References TQuaternion(), Other, W, X, Y, and Z.
Referenced by UE::Geometry::TQuaternion< float >::IsIdentity().
GetAxes()
template<typename RealType> void UE::Geometry::TQuaternion< RealType >::GetAxes (TVector< RealType > & X, TVector< RealType > & Y, TVector< RealType > & Z) const
Definition at line 373 of file Quaternion.h.
References W, X, Y, and Z.
Identity()
template<typename RealType> TQuaternion< RealType > UE::Geometry::TQuaternion< RealType >::Identity () inline static
Definition at line 59 of file Quaternion.h.
Referenced by UE::Geometry::TFrame3< float >::TFrame3(), UE::Geometry::TFrame3< float >::TFrame3(), UE::Geometry::TTransformSRT3< float >::TTransformSRT3(), UE::Geometry::TTransformSRT3< float >::TTransformSRT3(), UE::Geometry::TTransformSRT3< float >::Identity(), and UE::Geometry::TQuaternion< float >::IsIdentity().
Inverse()
template<typename RealType> TQuaternion< RealType > UE::Geometry::TQuaternion< RealType >::Inverse () const
Definition at line 386 of file Quaternion.h.
References TQuaternion(), SquaredLength(), W, X, Y, Z, and Zero().
InverseMultiply()
template<typename RealType> TVector< RealType > UE::Geometry::TQuaternion< RealType >::InverseMultiply (const TVector< RealType > & Other) const
Definition at line 324 of file Quaternion.h.
References SquaredLength(), W, X, UE::Math::TVector< T >::X, Y, UE::Math::TVector< T >::Y, Z, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::Zero().
Referenced by UE::Geometry::TOrientedBox3< float >::Merge().
IsIdentity()
template<typename RealType> bool UE::Geometry::TQuaternion< RealType >::IsIdentity (RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) const inline
Definition at line 77 of file Quaternion.h.
Length()
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::Length () const inline
Definition at line 82 of file Quaternion.h.
Referenced by Normalize(), and Normalized().
Normalize()
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::Normalize (const RealType epsilon = 0)
Definition at line 235 of file Quaternion.h.
References Length(), W, X, Y, and Z.
Referenced by UE::Geometry::TFrame3< float >::Rotate(), and SetToSlerp().
Normalized()
template<typename RealType> TQuaternion< RealType > UE::Geometry::TQuaternion< RealType >::Normalized (const RealType epsilon = 0) const
Definition at line 252 of file Quaternion.h.
References TQuaternion(), Length(), W, X, Y, Z, and Zero().
operator FQuat4d()
template<typename RealType> UE::Geometry::TQuaternion< RealType >::operator FQuat4d () const inline explicit
Definition at line 119 of file Quaternion.h.
operator FQuat4f()
template<typename RealType> UE::Geometry::TQuaternion< RealType >::operator FQuat4f () const inline explicit
Definition at line 110 of file Quaternion.h.
operator FRotator()
template<typename RealType> UE::Geometry::TQuaternion< RealType >::operator FRotator () const inline explicit
Definition at line 128 of file Quaternion.h.
operator UE::Math::TVector4< RealType >()
template<typename RealType> UE::Geometry::TQuaternion< RealType >::operator UE::Math::TVector4< RealType > () const inline explicit
Definition at line 154 of file Quaternion.h.
operator-()
template<typename RealType> TQuaternion< RealType > UE::Geometry::TQuaternion< RealType >::operator- () const inline constexpr
Definition at line 100 of file Quaternion.h.
operator=()
template<typename RealType> TQuaternion & UE::Geometry::TQuaternion< RealType >::operator= (const TQuaternion< RealType > & Copy) default
operator[]() [1/2]
template<typename RealType> RealType & UE::Geometry::TQuaternion< RealType >::operator[] (int i) inline
Definition at line 61 of file Quaternion.h.
operator[]() [2/2]
template<typename RealType> const RealType & UE::Geometry::TQuaternion< RealType >::operator[] (int i) const inline
Definition at line 67 of file Quaternion.h.
SetAxisAngleD()
template<typename RealType> void UE::Geometry::TQuaternion< RealType >::SetAxisAngleD (const TVector< RealType > & Axis, RealType AngleDeg)
Definition at line 400 of file Quaternion.h.
References Axis, and SetAxisAngleR().
Referenced by UE::Geometry::TFrame3< float >::ConstrainedAlignAxis().
SetAxisAngleR()
template<typename RealType> void UE::Geometry::TQuaternion< RealType >::SetAxisAngleR (const TVector< RealType > & Axis, RealType AngleRad)
Definition at line 406 of file Quaternion.h.
References Axis, W, X, Y, and Z.
Referenced by TQuaternion(), and SetAxisAngleD().
SetFromRotationMatrix()
template<typename RealType> void UE::Geometry::TQuaternion< RealType >::SetFromRotationMatrix (const TMatrix3< RealType > & RotationMatrix)
Definition at line 505 of file Quaternion.h.
References UE::Geometry::Normalize, W, X, UE::Math::TVector< T >::X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
Referenced by TQuaternion().
SetFromTo()
template<typename RealType> void UE::Geometry::TQuaternion< RealType >::SetFromTo (const TVector< RealType > & From, const TVector< RealType > & To)
Definition at line 420 of file Quaternion.h.
References UE::Math::TVector< T >::Cross(), UE::Math::TVector< T >::Dot(), UE::Geometry::Normalize, UE::Geometry::Normalized(), W, X, UE::Math::TVector< T >::X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
Referenced by TQuaternion().
SetToSlerp()
template<typename RealType> void UE::Geometry::TQuaternion< RealType >::SetToSlerp (TQuaternion< RealType > From, TQuaternion< RealType > To, RealType InterpT)
Definition at line 464 of file Quaternion.h.
References TQuaternion(), TMathUtil< RealType >::Abs(), TMathUtil< RealType >::ACos(), Dot(), UE::Geometry::Normalize, Normalize(), TMathUtil< RealType >::Sin(), W, X, Y, and Z.
Referenced by TQuaternion().
SquaredLength()
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::SquaredLength () const inline
Definition at line 83 of file Quaternion.h.
Referenced by Inverse(), and InverseMultiply().
ToRotationMatrix()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TQuaternion< RealType >::ToRotationMatrix () const
Definition at line 557 of file Quaternion.h.
References UE::Geometry::TMatrix3< RealType >::Row0, UE::Geometry::TMatrix3< RealType >::Row1, UE::Geometry::TMatrix3< RealType >::Row2, W, X, Y, Z, and UE::Geometry::TMatrix3< RealType >::Zero().
Zero()
template<typename RealType> TQuaternion< RealType > UE::Geometry::TQuaternion< RealType >::Zero () inline static
Definition at line 58 of file Quaternion.h.
Referenced by Inverse(), and Normalized().
Field Documentation
[union]
union { ... } UE::Geometry::TQuaternion< RealType >
W
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::W
Definition at line 31 of file Quaternion.h.
Referenced by TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), AxisX(), AxisY(), AxisZ(), Dot(), EpsilonEqual(), GetAxes(), Inverse(), InverseMultiply(), Normalize(), Normalized(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::operator*(), SetAxisAngleR(), SetFromRotationMatrix(), SetFromTo(), SetToSlerp(), and ToRotationMatrix().
X
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::X
Definition at line 28 of file Quaternion.h.
Referenced by TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), AxisX(), AxisY(), AxisZ(), Dot(), EpsilonEqual(), GetAxes(), Inverse(), InverseMultiply(), Normalize(), Normalized(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::operator*(), SetAxisAngleR(), SetFromRotationMatrix(), SetFromTo(), SetToSlerp(), and ToRotationMatrix().
Y
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::Y
Definition at line 29 of file Quaternion.h.
Referenced by TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), AxisX(), AxisY(), AxisZ(), Dot(), EpsilonEqual(), GetAxes(), Inverse(), InverseMultiply(), Normalize(), Normalized(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::operator*(), SetAxisAngleR(), SetFromRotationMatrix(), SetFromTo(), SetToSlerp(), and ToRotationMatrix().
Z
template<typename RealType> RealType UE::Geometry::TQuaternion< RealType >::Z
Definition at line 30 of file Quaternion.h.
Referenced by TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), TQuaternion(), AxisX(), AxisY(), AxisZ(), Dot(), EpsilonEqual(), GetAxes(), Inverse(), InverseMultiply(), Normalize(), Normalized(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::operator*(), SetAxisAngleR(), SetFromRotationMatrix(), SetFromTo(), SetToSlerp(), and ToRotationMatrix().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/Quaternion.h