Unreal Engine 5.6 C++ API: FInputCaptureUpdate Struct Reference
FInputCaptureUpdate Struct Reference
IInputBehavior returns an FInputCaptureUpdate from BeginCapture() and UpdateCapture(), which indicates to the InputRouter what the Behavior would like to have happen.
#include "InputBehavior.h"
Public Member Functions
FInputCaptureUpdate (EInputCaptureState StateIn, UInputBehavior *SourceBehaviorIn, EInputCaptureSide WhichSideIn, void *CustomData=nullptr)
Static Public Member Functions
static FInputCaptureUpdate Begin (UInputBehavior *SourceBehavior, EInputCaptureSide WhichSide, void *CustomData=nullptr)
Create a begin-capturing instance of FInputCaptureUpdate.
static FInputCaptureUpdate Continue ()
Create a default continue-capturing instance of FInputCaptureUpdate.
static FInputCaptureUpdate End ()
Create a default end-capturing instance of FInputCaptureUpdate.
static FInputCaptureUpdate Ignore ()
Create a default ignore-capturing instance of FInputCaptureUpdate.
Data Fields
FInputCaptureData Data
custom data for the active capture that should be propagated to next UpdateCapture() call
UInputBehavior * Source
Which Behavior did this update come from.
EInputCaptureState State
Indicates what capture state the Behavior wants to transition to.
Detailed Description
IInputBehavior returns an FInputCaptureUpdate from BeginCapture() and UpdateCapture(), which indicates to the InputRouter what the Behavior would like to have happen.
Definition at line 131 of file InputBehavior.h.
Constructor & Destructor Documentation
FInputCaptureUpdate()
FInputCaptureUpdate::FInputCaptureUpdate (EInputCaptureState StateIn, UInputBehavior * SourceBehaviorIn, EInputCaptureSide WhichSideIn, void * CustomData = nullptr) inline
Parameters
StateIn desired capture state
Source UInputBehavior that is returning this update
Which Which side we are capturing on
CustomData client-provided data that will be passed to UInputBehavior::UpdateCapture() calls. Client owns this memory!
Definition at line 173 of file InputBehavior.h.
References Data, Source, and State.
Referenced by Begin(), Continue(), End(), and Ignore().
Member Function Documentation
Begin()
FInputCaptureUpdate FInputCaptureUpdate::Begin (UInputBehavior * SourceBehavior, EInputCaptureSide WhichSide, void * CustomData = nullptr) inline static
Create a begin-capturing instance of FInputCaptureUpdate.
Parameters
Source UInputBehavior that is returning this update
Which Which side we are capturing on
CustomData client-provided data that will be passed to UInputBehavior::UpdateCapture() calls. Client owns this memory!
Definition at line 146 of file InputBehavior.h.
References FInputCaptureUpdate().
Continue()
FInputCaptureUpdate FInputCaptureUpdate::Continue () inline static
Create a default continue-capturing instance of FInputCaptureUpdate.
Definition at line 152 of file InputBehavior.h.
References FInputCaptureUpdate().
End()
FInputCaptureUpdate FInputCaptureUpdate::End () inline static
Create a default end-capturing instance of FInputCaptureUpdate.
Definition at line 157 of file InputBehavior.h.
References FInputCaptureUpdate().
Ignore()
FInputCaptureUpdate FInputCaptureUpdate::Ignore () inline static
Create a default ignore-capturing instance of FInputCaptureUpdate.
Definition at line 162 of file InputBehavior.h.
References FInputCaptureUpdate().
Field Documentation
Data
FInputCaptureData FInputCaptureUpdate::Data
custom data for the active capture that should be propagated to next UpdateCapture() call
Definition at line 138 of file InputBehavior.h.
Referenced by FInputCaptureUpdate().
Source
UInputBehavior* FInputCaptureUpdate::Source
Which Behavior did this update come from.
Definition at line 136 of file InputBehavior.h.
Referenced by FInputCaptureUpdate().
State
EInputCaptureState FInputCaptureUpdate::State
Indicates what capture state the Behavior wants to transition to.
Definition at line 134 of file InputBehavior.h.
Referenced by FInputCaptureUpdate().
The documentation for this struct was generated from the following file:
Runtime/InteractiveToolsFramework/Public/InputBehavior.h