Unreal Engine 5.6 C++ API: FGroomBuilder Struct Reference
FGroomBuilder Struct Reference
#include "GroomBuilder.h"
Public Member Functions
UE_DEPRECATED (5.6, "Please, no longer use this build function, as it does not contains certain build steps (decimation/shuffling)") static HAIRSTRANDSCORE_API void BuildData(const FHairStrandsRawDatas &In
Static Public Member Functions
static HAIRSTRANDSCORE_API void BuildBulkData (const FHairGroupInfo &InInfo, const FHairStrandsDatas &InData, FHairStrandsBulkData &OutBulkData, bool bAllowCompression)
static HAIRSTRANDSCORE_API void BuildClusterBulkData (const FHairStrandsDatas &InRenData, const float InGroomAssetRadius, const FHairGroupsLOD &InSettings, FHairStrandsClusterBulkData &OutClusterData)
static HAIRSTRANDSCORE_API void BuildData (const FHairDescriptionGroup &InHairDescriptionGroup, const FHairGroupsInterpolation &InSettings, FHairGroupInfo &OutGroupInfo, FHairStrandsDatas &OutStrands, FHairStrandsDatas &OutGuides, const bool bAllowCurveReordering=true, const bool bApplyDecimation=true, const bool bBuildSourceMapping=false)
static HAIRSTRANDSCORE_API void BuildData (const FHairDescriptionGroup &InHairDescriptionGroup, const FHairGroupsInterpolation &InSettings, FHairStrandsDatas &OutStrands, FHairStrandsDatas &OutGuides, const bool bAllowCurveReordering=true, const bool bApplyDecimation=true, const bool bBuildSourceMapping=false)
static HAIRSTRANDSCORE_API bool BuildHairDescriptionGroups (const FHairDescription &HairDescription, FHairDescriptionGroups &Out, const bool bAllowAddEndControlPoint=true)
static HAIRSTRANDSCORE_API void BuildInterplationBulkData (const FHairStrandsDatas &InSimData, const FHairStrandsInterpolationDatas &InInterpolationData, FHairStrandsInterpolationBulkData &OutInterpolationData)
static HAIRSTRANDSCORE_API void BuildInterplationData (const FHairGroupInfo &InInfo, const FHairStrandsDatas &InRenData, const FHairStrandsDatas &InSimData, const FHairInterpolationSettings &InInterpolationSettings, FHairStrandsInterpolationDatas &OutInterpolationData)
static HAIRSTRANDSCORE_API void BuildRenderCurveResourceBulkData (const FHairStrandsDatas &In, FRenderCurveResourceData &Out)
static HAIRSTRANDSCORE_API FString GetVersion ()
static HAIRSTRANDSCORE_API void VoxelizeGroupIndex (const FHairDescriptionGroups &In, FHairStrandsVoxelData &Out)
Data Fields
FHairStrandsDatas & Out
Detailed Description
Definition at line 59 of file GroomBuilder.h.
Member Function Documentation
BuildBulkData()
HAIRSTRANDSCORE_API void FGroomBuilder::BuildBulkData (const FHairGroupInfo & InInfo, const FHairStrandsDatas & InData, FHairStrandsBulkData & OutBulkData, bool bAllowCompression) static
References BuildBulkData(), and UE_API.
Referenced by BuildBulkData().
BuildClusterBulkData()
HAIRSTRANDSCORE_API void FGroomBuilder::BuildClusterBulkData (const FHairStrandsDatas & InRenData, const float InGroomAssetRadius, const FHairGroupsLOD & InSettings, FHairStrandsClusterBulkData & OutClusterData) static
References BuildClusterBulkData(), and UE_API.
Referenced by BuildClusterBulkData().
BuildData() [1/2]
HAIRSTRANDSCORE_API void FGroomBuilder::BuildData (const FHairDescriptionGroup & InHairDescriptionGroup, const FHairGroupsInterpolation & InSettings, FHairGroupInfo & OutGroupInfo, FHairStrandsDatas & OutStrands, FHairStrandsDatas & OutGuides, const bool bAllowCurveReordering = true, const bool bApplyDecimation = true, const bool bBuildSourceMapping = false) static
References UE_API.
BuildData() [2/2]
HAIRSTRANDSCORE_API void FGroomBuilder::BuildData (const FHairDescriptionGroup & InHairDescriptionGroup, const FHairGroupsInterpolation & InSettings, FHairStrandsDatas & OutStrands, FHairStrandsDatas & OutGuides, const bool bAllowCurveReordering = true, const bool bApplyDecimation = true, const bool bBuildSourceMapping = false) static
References UE_API.
BuildHairDescriptionGroups()
HAIRSTRANDSCORE_API bool FGroomBuilder::BuildHairDescriptionGroups (const FHairDescription & HairDescription, FHairDescriptionGroups & Out, const bool bAllowAddEndControlPoint = true) static
References Out, and UE_API.
BuildInterplationBulkData()
HAIRSTRANDSCORE_API void FGroomBuilder::BuildInterplationBulkData (const FHairStrandsDatas & InSimData, const FHairStrandsInterpolationDatas & InInterpolationData, FHairStrandsInterpolationBulkData & OutInterpolationData) static
References BuildInterplationBulkData(), and UE_API.
Referenced by BuildInterplationBulkData().
BuildInterplationData()
HAIRSTRANDSCORE_API void FGroomBuilder::BuildInterplationData (const FHairGroupInfo & InInfo, const FHairStrandsDatas & InRenData, const FHairStrandsDatas & InSimData, const FHairInterpolationSettings & InInterpolationSettings, FHairStrandsInterpolationDatas & OutInterpolationData) static
References BuildInterplationData(), and UE_API.
Referenced by BuildInterplationData().
BuildRenderCurveResourceBulkData()
HAIRSTRANDSCORE_API void FGroomBuilder::BuildRenderCurveResourceBulkData (const FHairStrandsDatas & In, FRenderCurveResourceData & Out) static
References BuildRenderCurveResourceBulkData(), Out, and UE_API.
Referenced by BuildRenderCurveResourceBulkData().
GetVersion()
HAIRSTRANDSCORE_API FString FGroomBuilder::GetVersion () static
References UE_API.
UE_DEPRECATED()
FGroomBuilder::UE_DEPRECATED (5. 6, " Please, no longer use this build function, as it does not contains certain build steps(decimation/shuffling)") const &
VoxelizeGroupIndex()
HAIRSTRANDSCORE_API void FGroomBuilder::VoxelizeGroupIndex (const FHairDescriptionGroups & In, FHairStrandsVoxelData & Out) static
References Out, UE_API, and VoxelizeGroupIndex().
Referenced by VoxelizeGroupIndex().
Field Documentation
Out
FHairStrandsDatas& FGroomBuilder::Out
Definition at line 91 of file GroomBuilder.h.
Referenced by BuildHairDescriptionGroups(), BuildRenderCurveResourceBulkData(), and VoxelizeGroupIndex().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/GroomBuilder.h