Unreal Engine 5.6 C++ API: FAsyncAddPrimitiveQueue::FAddPrimitivesTask Struct Reference
FAsyncAddPrimitiveQueue::FAddPrimitivesTask Struct Reference
Public Member Functions
bool IsCompleted () const
bool IsValid () const
void Launch (TArray< FPrimitiveBatch > &InBatch, FSceneInterface *InScene)
void Reset ()
void Wait ()
Static Public Member Functions
static void Execute (const TArray< FPrimitiveBatch > &InBatch, FSceneInterface *InScene)
static void Execute (UPrimitiveComponent *Component, FSceneInterface *InScene, bool bAppCanEverRender)
Data Fields
TArray< FPrimitiveBatch > Batches
UE::Tasks::TTask< void > Task
Detailed Description
Definition at line 28 of file AsyncRegisterLevelContext.h.
Member Function Documentation
Execute() [1/2]
void FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Execute (const TArray< FPrimitiveBatch > & InBatch, FSceneInterface * InScene) static
Definition at line 313 of file AsyncRegisterLevelContext.cpp.
References FApp::CanEverRender(), check, Component, EParallelGameThread, Execute(), Num, and ParallelFor().
Referenced by Execute(), Launch(), and FAsyncAddPrimitiveQueue::Tick().
Execute() [2/2]
void FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Execute (UPrimitiveComponent * Component, FSceneInterface * InScene, bool bAppCanEverRender) static
Definition at line 291 of file AsyncRegisterLevelContext.cpp.
References FSceneInterface::AddPrimitive(), and Component.
IsCompleted()
bool FAsyncAddPrimitiveQueue::FAddPrimitivesTask::IsCompleted () const
Definition at line 356 of file AsyncRegisterLevelContext.cpp.
References Task.
Referenced by Launch(), Reset(), and Wait().
IsValid()
bool FAsyncAddPrimitiveQueue::FAddPrimitivesTask::IsValid () const
Definition at line 361 of file AsyncRegisterLevelContext.cpp.
References Task.
Launch()
void FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Launch (TArray< FPrimitiveBatch > & InBatch, FSceneInterface * InScene)
Definition at line 280 of file AsyncRegisterLevelContext.cpp.
References Batches, check, Execute(), IsCompleted(), UE::Tasks::Launch(), MoveTemp(), QUICK_SCOPE_CYCLE_COUNTER, Task, and UE_SOURCE_LOCATION.
Reset()
void FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Reset ()
Definition at line 273 of file AsyncRegisterLevelContext.cpp.
References Batches, check, IsCompleted(), and Task.
Wait()
void FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Wait ()
Definition at line 347 of file AsyncRegisterLevelContext.cpp.
References check, IsCompleted(), and Task.
Field Documentation
Batches
TArray<FPrimitiveBatch> FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Batches
Definition at line 39 of file AsyncRegisterLevelContext.h.
Referenced by Launch(), and Reset().
Task
UE::Tasks::TTask<void> FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Task
Definition at line 40 of file AsyncRegisterLevelContext.h.
Referenced by IsCompleted(), IsValid(), Launch(), Reset(), and Wait().
The documentation for this struct was generated from the following files:
Runtime/Engine/Internal/Streaming/AsyncRegisterLevelContext.h
Runtime/Engine/Internal/Streaming/AsyncRegisterLevelContext.cpp