Unreal Engine 5.6 C++ API: Metasound::Frontend::FNodeClassRegistryKey Struct Reference
Metasound::Frontend::FNodeClassRegistryKey Struct Reference
#include "MetasoundFrontendRegistryKey.h"
Public Member Functions
FNodeClassRegistryKey ()=default
METASOUNDFRONTEND_API FNodeClassRegistryKey (const FMetaSoundAssetKey &AssetKey)
METASOUNDFRONTEND_API FNodeClassRegistryKey (const FMetasoundFrontendClassMetadata &InNodeMetadata)
METASOUNDFRONTEND_API FNodeClassRegistryKey (const FMetasoundFrontendGraphClass &InGraphClass)
METASOUNDFRONTEND_API FNodeClassRegistryKey (const FNodeClassInfo &InClassInfo)
METASOUNDFRONTEND_API FNodeClassRegistryKey (const FNodeClassMetadata &InNodeMetadata)
METASOUNDFRONTEND_API FNodeClassRegistryKey (EMetasoundFrontendClassType InType, const FMetasoundFrontendClassName &InClassName, const FMetasoundFrontendVersionNumber &InVersion)
METASOUNDFRONTEND_API FNodeClassRegistryKey (EMetasoundFrontendClassType InType, const FMetasoundFrontendClassName &InClassName, int32 InMajorVersion, int32 InMinorVersion)
METASOUNDFRONTEND_API bool IsValid () const
METASOUNDFRONTEND_API void Reset ()
METASOUNDFRONTEND_API FString ToString () const
METASOUNDFRONTEND_API FString ToString (const FString &InScopeHeader) const
Static Public Member Functions
static METASOUNDFRONTEND_API const FNodeClassRegistryKey & GetInvalid ()
static METASOUNDFRONTEND_API bool Parse (const FString &InKeyString, FNodeClassRegistryKey &OutKey)
Data Fields
FMetasoundFrontendClassName ClassName
EMetasoundFrontendClassType Type = EMetasoundFrontendClassType::Invalid
FMetasoundFrontendVersionNumber Version
Friends
FORCEINLINE uint32 GetTypeHash (const FNodeClassRegistryKey &InKey)
FORCEINLINE friend bool operator< (const FNodeClassRegistryKey &InLHS, const FNodeClassRegistryKey &InRHS)
FORCEINLINE friend bool operator== (const FNodeClassRegistryKey &InLHS, const FNodeClassRegistryKey &InRHS)
Detailed Description
Definition at line 66 of file MetasoundFrontendRegistryKey.h.
Constructor & Destructor Documentation
FNodeClassRegistryKey() [1/8]
Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey () default
Referenced by GetInvalid(), GetTypeHash, operator<, operator==, and Parse().
FNodeClassRegistryKey() [2/8]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey (EMetasoundFrontendClassType InType, const FMetasoundFrontendClassName & InClassName, int32 InMajorVersion, int32 InMinorVersion)
References UE_API.
FNodeClassRegistryKey() [3/8]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey (EMetasoundFrontendClassType InType, const FMetasoundFrontendClassName & InClassName, const FMetasoundFrontendVersionNumber & InVersion)
References UE_API.
FNodeClassRegistryKey() [4/8]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey (const FNodeClassMetadata & InNodeMetadata)
References UE_API.
FNodeClassRegistryKey() [5/8]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey (const FMetasoundFrontendClassMetadata & InNodeMetadata)
References UE_API.
FNodeClassRegistryKey() [6/8]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey (const FMetasoundFrontendGraphClass & InGraphClass)
References UE_API.
FNodeClassRegistryKey() [7/8]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey (const FNodeClassInfo & InClassInfo)
References UE_API.
FNodeClassRegistryKey() [8/8]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassRegistryKey::FNodeClassRegistryKey (const FMetaSoundAssetKey & AssetKey)
References UE_API.
Member Function Documentation
GetInvalid()
METASOUNDFRONTEND_API const FNodeClassRegistryKey & Metasound::Frontend::FNodeClassRegistryKey::GetInvalid () static
References FNodeClassRegistryKey(), and UE_API.
IsValid()
METASOUNDFRONTEND_API bool Metasound::Frontend::FNodeClassRegistryKey::IsValid () const
References UE_API.
Parse()
METASOUNDFRONTEND_API bool Metasound::Frontend::FNodeClassRegistryKey::Parse (const FString & InKeyString, FNodeClassRegistryKey & OutKey) static
References FNodeClassRegistryKey(), and UE_API.
Reset()
METASOUNDFRONTEND_API void Metasound::Frontend::FNodeClassRegistryKey::Reset ()
References UE_API.
ToString() [1/2]
METASOUNDFRONTEND_API FString Metasound::Frontend::FNodeClassRegistryKey::ToString () const
References UE_API.
ToString() [2/2]
METASOUNDFRONTEND_API FString Metasound::Frontend::FNodeClassRegistryKey::ToString (const FString & InScopeHeader) const
References UE_API.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FNodeClassRegistryKey & InKey) friend
Definition at line 101 of file MetasoundFrontendRegistryKey.h.
References FNodeClassRegistryKey(), ClassName, FORCEINLINE, GetTypeHash, Metasound::GetTypeHash(), Hash, HashCombineFast(), Type, and Version.
Referenced by GetTypeHash.
operator<
FORCEINLINE friend bool operator< (const FNodeClassRegistryKey & InLHS, const FNodeClassRegistryKey & InRHS) friend
Definition at line 86 of file MetasoundFrontendRegistryKey.h.
References FNodeClassRegistryKey(), ClassName, FORCEINLINE, Type, and Version.
operator==
FORCEINLINE friend bool operator== (const FNodeClassRegistryKey & InLHS, const FNodeClassRegistryKey & InRHS) friend
Definition at line 81 of file MetasoundFrontendRegistryKey.h.
References FNodeClassRegistryKey(), ClassName, FORCEINLINE, Type, and Version.
Field Documentation
ClassName
FMetasoundFrontendClassName Metasound::Frontend::FNodeClassRegistryKey::ClassName
Definition at line 69 of file MetasoundFrontendRegistryKey.h.
Referenced by GetTypeHash, operator<, and operator==.
Type
EMetasoundFrontendClassType Metasound::Frontend::FNodeClassRegistryKey::Type = EMetasoundFrontendClassType::Invalid
Definition at line 68 of file MetasoundFrontendRegistryKey.h.
Referenced by GetTypeHash, operator<, and operator==.
Version
FMetasoundFrontendVersionNumber Metasound::Frontend::FNodeClassRegistryKey::Version
Definition at line 70 of file MetasoundFrontendRegistryKey.h.
Referenced by GetTypeHash, operator<, and operator==.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundFrontendRegistryKey.h