Unreal Engine 5.6 C++ API: FGPUBaseSkinVertexFactory::FShaderDataType Struct Reference
FGPUBaseSkinVertexFactory::FShaderDataType Struct Reference
#include "GPUSkinVertexFactory.h"
Public Member Functions
FShaderDataType ()
const FVertexBufferAndSRV & GetBoneBufferForReading (bool bPrevious) const
FVertexBufferAndSRV & GetBoneBufferForWriting (bool bPrevious)
uint32 GetRevisionNumber (bool bPrevious) const
bool HasBoneBufferForReading (bool bPrevious) const
void ReleaseBoneData ()
void SetCurrentRevisionNumber (uint32)
void SetRevisionNumbers (uint32 InCurrentRevisionNumber, uint32 InPreviousRevisionNumber)
Static Public Member Functions
static void AllocateBoneBuffer (FRHICommandList &RHICmdList, uint32 BufferSize, FVertexBufferAndSRV &OutBoneBuffer)
static void UpdateBoneData (FRHICommandList &RHICmdList, const FName &AssetPathName, TConstArrayView< FMatrix44f > ReferenceToLocalMatrices, TConstArrayView< FBoneIndexType > BoneMap, FRHIBuffer *VertexBufferRHI)
Data Fields
int32 InputWeightIndexSize = 0
FShaderResourceViewRHIRef InputWeightStream
uint64 UpdatedFrameNumber = 0
Private Member Functions
const FVertexBufferAndSRV & GetBoneBufferInternal (bool bPrevious) const
bool GetPreviousForRead (bool bPrevious) const
Private Attributes
TStaticArray< FVertexBufferAndSRV, 2 > BoneBuffer
uint32 CurrentBuffer = 0
uint32 CurrentRevisionNumber = 0
uint32 PreviousRevisionNumber = 0
Static Private Attributes
static uint32 MaxGPUSkinBones
Detailed Description
Definition at line 214 of file GPUSkinVertexFactory.h.
Constructor & Destructor Documentation
FShaderDataType()
FGPUBaseSkinVertexFactory::FShaderDataType::FShaderDataType () inline
Definition at line 216 of file GPUSkinVertexFactory.h.
References check, FGPUBaseSkinVertexFactory::GetMaxGPUSkinBones(), FGPUBaseSkinVertexFactory::GHardwareMaxGPUSkinBones, and MaxGPUSkinBones.
Member Function Documentation
AllocateBoneBuffer()
void FGPUBaseSkinVertexFactory::FShaderDataType::AllocateBoneBuffer (FRHICommandList & RHICmdList, uint32 BufferSize, FVertexBufferAndSRV & OutBoneBuffer) static
GetBoneBufferForReading()
const FVertexBufferAndSRV & FGPUBaseSkinVertexFactory::FShaderDataType::GetBoneBufferForReading (bool bPrevious) const inline
Definition at line 245 of file GPUSkinVertexFactory.h.
References BoneBuffer, check, checkf, CurrentRevisionNumber, GetBoneBufferInternal(), GetPreviousForRead(), PreviousRevisionNumber, TEXT, and FVertexBufferAndSRV::VertexBufferRHI.
GetBoneBufferForWriting()
FVertexBufferAndSRV & FGPUBaseSkinVertexFactory::FShaderDataType::GetBoneBufferForWriting (bool bPrevious) inline
Definition at line 263 of file GPUSkinVertexFactory.h.
References GetBoneBufferInternal().
GetBoneBufferInternal()
const FVertexBufferAndSRV & FGPUBaseSkinVertexFactory::FShaderDataType::GetBoneBufferInternal (bool bPrevious) const inline private
Definition at line 303 of file GPUSkinVertexFactory.h.
References BoneBuffer, and CurrentBuffer.
Referenced by GetBoneBufferForReading(), GetBoneBufferForWriting(), and HasBoneBufferForReading().
GetPreviousForRead()
bool FGPUBaseSkinVertexFactory::FShaderDataType::GetPreviousForRead (bool bPrevious) const inline private
Definition at line 296 of file GPUSkinVertexFactory.h.
References CurrentRevisionNumber, and PreviousRevisionNumber.
Referenced by GetBoneBufferForReading(), and HasBoneBufferForReading().
GetRevisionNumber()
uint32 FGPUBaseSkinVertexFactory::FShaderDataType::GetRevisionNumber (bool bPrevious) const inline
Definition at line 275 of file GPUSkinVertexFactory.h.
References CurrentRevisionNumber, and PreviousRevisionNumber.
HasBoneBufferForReading()
bool FGPUBaseSkinVertexFactory::FShaderDataType::HasBoneBufferForReading (bool bPrevious) const inline
Definition at line 234 of file GPUSkinVertexFactory.h.
References GetBoneBufferInternal(), GetPreviousForRead(), and FVertexBufferAndSRV::VertexBufferRHI.
ReleaseBoneData()
void FGPUBaseSkinVertexFactory::FShaderDataType::ReleaseBoneData ()
SetCurrentRevisionNumber()
void FGPUBaseSkinVertexFactory::FShaderDataType::SetCurrentRevisionNumber (uint32) inline
Definition at line 281 of file GPUSkinVertexFactory.h.
References SetCurrentRevisionNumber().
Referenced by SetCurrentRevisionNumber().
SetRevisionNumbers()
void FGPUBaseSkinVertexFactory::FShaderDataType::SetRevisionNumbers (uint32 InCurrentRevisionNumber, uint32 InPreviousRevisionNumber) inline
Definition at line 268 of file GPUSkinVertexFactory.h.
References CurrentBuffer, CurrentRevisionNumber, INDEX_NONE, and PreviousRevisionNumber.
UpdateBoneData()
void FGPUBaseSkinVertexFactory::FShaderDataType::UpdateBoneData (FRHICommandList & RHICmdList, const FName & AssetPathName, TConstArrayView< FMatrix44f > ReferenceToLocalMatrices, TConstArrayView< FBoneIndexType > BoneMap, FRHIBuffer * VertexBufferRHI) static
Field Documentation
BoneBuffer
TStaticArray<FVertexBufferAndSRV, 2> FGPUBaseSkinVertexFactory::FShaderDataType::BoneBuffer private
Definition at line 289 of file GPUSkinVertexFactory.h.
Referenced by GetBoneBufferForReading(), and GetBoneBufferInternal().
CurrentBuffer
uint32 FGPUBaseSkinVertexFactory::FShaderDataType::CurrentBuffer = 0 private
Definition at line 290 of file GPUSkinVertexFactory.h.
Referenced by GetBoneBufferInternal(), and SetRevisionNumbers().
CurrentRevisionNumber
uint32 FGPUBaseSkinVertexFactory::FShaderDataType::CurrentRevisionNumber = 0 private
Definition at line 292 of file GPUSkinVertexFactory.h.
Referenced by GetBoneBufferForReading(), GetPreviousForRead(), GetRevisionNumber(), and SetRevisionNumbers().
InputWeightIndexSize
int32 FGPUBaseSkinVertexFactory::FShaderDataType::InputWeightIndexSize = 0
Definition at line 283 of file GPUSkinVertexFactory.h.
InputWeightStream
FShaderResourceViewRHIRef FGPUBaseSkinVertexFactory::FShaderDataType::InputWeightStream
Definition at line 284 of file GPUSkinVertexFactory.h.
MaxGPUSkinBones
uint32 FGPUBaseSkinVertexFactory::FShaderDataType::MaxGPUSkinBones static private
Definition at line 294 of file GPUSkinVertexFactory.h.
Referenced by FShaderDataType().
PreviousRevisionNumber
uint32 FGPUBaseSkinVertexFactory::FShaderDataType::PreviousRevisionNumber = 0 private
Definition at line 291 of file GPUSkinVertexFactory.h.
Referenced by GetBoneBufferForReading(), GetPreviousForRead(), GetRevisionNumber(), and SetRevisionNumbers().
UpdatedFrameNumber
uint64 FGPUBaseSkinVertexFactory::FShaderDataType::UpdatedFrameNumber = 0
Definition at line 286 of file GPUSkinVertexFactory.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/GPUSkinVertexFactory.h