Unreal Engine 5.6 C++ API: FParameterAllocation Struct Reference
FParameterAllocation Struct Reference
#include "ShaderCore.h"
Public Member Functions
FParameterAllocation ()=default
FParameterAllocation (uint16 InBufferIndex, uint16 InBaseIndex, uint16 InSize, EShaderParameterType InType)
Data Fields
uint16 BaseIndex = 0
bool bBound = false
uint16 BufferIndex = 0
uint16 Size = 0
EShaderParameterType Type { EShaderParameterType::Num }
Friends
bool operator!= (const FParameterAllocation &A, const FParameterAllocation &B)
FArchive & operator<< (FArchive &Ar, FParameterAllocation &Allocation)
bool operator== (const FParameterAllocation &A, const FParameterAllocation &B)
Detailed Description
Definition at line 280 of file ShaderCore.h.
Constructor & Destructor Documentation
FParameterAllocation() [1/2]
FParameterAllocation::FParameterAllocation () default
Referenced by operator!=, operator<<, and operator==.
FParameterAllocation() [2/2]
FParameterAllocation::FParameterAllocation (uint16 InBufferIndex, uint16 InBaseIndex, uint16 InSize, EShaderParameterType InType) inline
Definition at line 289 of file ShaderCore.h.
References BaseIndex, BufferIndex, Size, and Type.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FParameterAllocation & A, const FParameterAllocation & B) friend
Definition at line 310 of file ShaderCore.h.
References FParameterAllocation(), A, and B.
operator<<
FArchive & operator<< (FArchive & Ar, FParameterAllocation & Allocation) friend
Definition at line 297 of file ShaderCore.h.
References FParameterAllocation(), Ar, BaseIndex, bBound, BufferIndex, Size, and Type.
operator==
bool operator== (const FParameterAllocation & A, const FParameterAllocation & B) friend
Definition at line 304 of file ShaderCore.h.
References FParameterAllocation(), A, and B.
Field Documentation
BaseIndex
uint16 FParameterAllocation::BaseIndex = 0
Definition at line 283 of file ShaderCore.h.
Referenced by FParameterAllocation(), and operator<<.
bBound
bool FParameterAllocation::bBound = false mutable
Definition at line 286 of file ShaderCore.h.
Referenced by operator<<.
BufferIndex
uint16 FParameterAllocation::BufferIndex = 0
Definition at line 282 of file ShaderCore.h.
Referenced by FParameterAllocation(), and operator<<.
Size
uint16 FParameterAllocation::Size = 0
Definition at line 284 of file ShaderCore.h.
Referenced by FParameterAllocation(), and operator<<.
Type
EShaderParameterType FParameterAllocation::Type { EShaderParameterType::Num }
Definition at line 285 of file ShaderCore.h.
Referenced by FParameterAllocation(), and operator<<.
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/ShaderCore.h