Unreal Engine 5.6 C++ API: TextFilterUtils::FNameBufferWithNumber Struct Reference
TextFilterUtils::FNameBufferWithNumber Struct Reference
#include "TextFilterUtils.h"
Public Member Functions
FNameBufferWithNumber ()
FNameBufferWithNumber (const FName &Name)
FNameBufferWithNumber (const FNameEntry *const NameEntry, int32 NumberInternal)
FORCEINLINE ANSICHAR * GetAnsiNamePtr ()
FORCEINLINE int32 GetMaxBufferLength ()
FORCEINLINE WIDECHAR * GetWideNamePtr ()
FORCEINLINE void Init (const FName &Name)
FORCEINLINE void Init (const FNameEntry *const NameEntry, int32 NumberInternal)
FORCEINLINE bool IsWide () const
Private Attributes
union {
ANSICHAR _AnsiName [NAME_SIZE]
WIDECHAR _WideName [NAME_SIZE]
ANSICHAR AnsiName [NAME_WITH_NUMBER_SIZE]
WIDECHAR WideName [NAME_WITH_NUMBER_SIZE]
};
bool bIsWide
Detailed Description
Definition at line 154 of file TextFilterUtils.h.
Constructor & Destructor Documentation
FNameBufferWithNumber() [1/3]
TextFilterUtils::FNameBufferWithNumber::FNameBufferWithNumber () inline
Definition at line 158 of file TextFilterUtils.h.
References bIsWide.
FNameBufferWithNumber() [2/3]
TextFilterUtils::FNameBufferWithNumber::FNameBufferWithNumber (const FName & Name) inline
Definition at line 162 of file TextFilterUtils.h.
References bIsWide, Init, and Name.
FNameBufferWithNumber() [3/3]
TextFilterUtils::FNameBufferWithNumber::FNameBufferWithNumber (const FNameEntry *const NameEntry, int32 NumberInternal) inline
Definition at line 167 of file TextFilterUtils.h.
References bIsWide, and Init.
Member Function Documentation
GetAnsiNamePtr()
FORCEINLINE ANSICHAR * TextFilterUtils::FNameBufferWithNumber::GetAnsiNamePtr () inline
Definition at line 215 of file TextFilterUtils.h.
References AnsiName, checkSlow, FORCEINLINE, and IsWide().
GetMaxBufferLength()
FORCEINLINE int32 TextFilterUtils::FNameBufferWithNumber::GetMaxBufferLength () inline
Definition at line 227 of file TextFilterUtils.h.
References FORCEINLINE, and NAME_WITH_NUMBER_SIZE.
GetWideNamePtr()
FORCEINLINE WIDECHAR * TextFilterUtils::FNameBufferWithNumber::GetWideNamePtr () inline
Definition at line 221 of file TextFilterUtils.h.
References checkSlow, FORCEINLINE, IsWide(), and WideName.
Init() [1/2]
FORCEINLINE void TextFilterUtils::FNameBufferWithNumber::Init (const FName & Name) inline
Definition at line 172 of file TextFilterUtils.h.
References FORCEINLINE, Init, and Name.
Init() [2/2]
FORCEINLINE void TextFilterUtils::FNameBufferWithNumber::Init (const FNameEntry *const NameEntry, int32 NumberInternal) inline
Definition at line 177 of file TextFilterUtils.h.
References _AnsiName, _WideName, AnsiName, bIsWide, FORCEINLINE, FNameEntry::GetAnsiName(), FNameEntry::GetWideName(), TextFilterUtils::IntToStringBuffer(), FNameEntry::IsWide(), NAME_INTERNAL_TO_EXTERNAL, NAME_NO_NUMBER_INTERNAL, NAME_SIZE, TCString< ANSICHAR >::Strlen(), TCString< WIDECHAR >::Strlen(), TCString< TCHAR >::Strncpy(), TEXT, and WideName.
IsWide()
FORCEINLINE bool TextFilterUtils::FNameBufferWithNumber::IsWide () const inline
Definition at line 210 of file TextFilterUtils.h.
References bIsWide, and FORCEINLINE.
Referenced by GetAnsiNamePtr(), and GetWideNamePtr().
Field Documentation
[union]
union { ... } TextFilterUtils::FNameBufferWithNumber
_AnsiName
ANSICHAR TextFilterUtils::FNameBufferWithNumber::_AnsiName[NAME_SIZE]
Definition at line 240 of file TextFilterUtils.h.
Referenced by Init().
_WideName
WIDECHAR TextFilterUtils::FNameBufferWithNumber::_WideName[NAME_SIZE]
Definition at line 241 of file TextFilterUtils.h.
Referenced by Init().
AnsiName
ANSICHAR TextFilterUtils::FNameBufferWithNumber::AnsiName[NAME_WITH_NUMBER_SIZE]
Definition at line 238 of file TextFilterUtils.h.
Referenced by GetAnsiNamePtr(), and Init().
bIsWide
bool TextFilterUtils::FNameBufferWithNumber::bIsWide private
Definition at line 234 of file TextFilterUtils.h.
Referenced by FNameBufferWithNumber(), FNameBufferWithNumber(), FNameBufferWithNumber(), Init(), and IsWide().
WideName
WIDECHAR TextFilterUtils::FNameBufferWithNumber::WideName[NAME_WITH_NUMBER_SIZE]
Definition at line 239 of file TextFilterUtils.h.
Referenced by GetWideNamePtr(), and Init().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/TextFilterUtils.h