Unreal Engine 5.6 C++ API: FParse Struct Reference
FParse Struct Reference
#include "Parse.h"
Data Structures
struct FGrammarBasedParseResult
Public Types
enum class EGrammarBasedParseErrorCode { Succeeded , NotRun , UnBalancedQuote , DisallowedQuotedCommand }
enum class EGrammarBasedParseFlags { None = 0u , AllowQuotedCommands = 1 << 0u }
enum class ELineExtendedFlags : uint8 {
None = 0 , SwallowDoubleSlashComments = 1 , SwallowSemicolonComments = 2 , SwallowExtraEOLs = 4 ,
BreakOnPipe = 8 , AllowBracketedMultiline = 16 , AllowEscapedEOLMultiline = 32 , Standard = AllowEscapedEOLMultiline ,
OldDefaultMode = SwallowDoubleSlashComments | BreakOnPipe | AllowBracketedMultiline | AllowEscapedEOLMultiline | SwallowExtraEOLs , OldExactMode = AllowBracketedMultiline | AllowEscapedEOLMultiline
}
Get a line of Stream, with support for extending beyond that line with certain characters, e.g.
Public Member Functions
UE_DEPRECATED (5.6, "Use the version that takes ELineExtendedFlags") static bool LineExtended(const TCHAR **Stream
UE_DEPRECATED (5.6, "Use the version that takes ELineExtendedFlags") static bool LineExtended(const TCHAR **Stream
Static Public Member Functions
static bool AlnumToken (const TCHAR *&Str, FString &Arg)
Grabs the next alpha-numeric space-delimited token from the input stream.
static bool Bool (const TCHAR *Stream, const TCHAR *Match, bool &OnOff)
Parses a boolean value.
static bool Command (const TCHAR **Stream, const TCHAR *Match, bool bParseMightTriggerExecution=true)
Sees if Stream starts with the named command.
static bool Expression (const TCHAR *&Str, FString &OutExpression, bool bUseEscape, const TCHAR SingleCharacterDelimiter=TEXT('\0'))
Parse the next space-delimited (or SingleCharacterDelmiter-delimited) expression, using brackets (), {}, or [] to allow subexpressions to be part of the single expression even if they contain the delimiter.
static FGrammarBasedParseResult GrammarBasedCLIParse (const TCHAR *Stream, TFunctionRef< void(FStringView, FStringView)> OnCommandCallback, EGrammarBasedParseFlags Flags=EGrammarBasedParseFlags::AllowQuotedCommands)
Grammar Line -> Cmd* Cmd -> "Cmd*" – allowed if EGrammaredParseFlags::AllowQuotedCommands is given | Key(=Value)?
static FORCEINLINE int32 HexDigit (TCHAR c)
static uint32 HexNumber (FStringView HexString)
Parses a hexadecimal string value.
static uint64 HexNumber64 (FStringView HexString)
static bool Line (const TCHAR **Stream, FString &Result, bool Exact=false)
Get a line of Stream (everything up to, but not including, CR/LF.
static bool Line (const TCHAR **Stream, FStringView &Result, bool Exact=false)
Get a line of Stream (everything up to, but not including, CR/LF.
static bool Line (const TCHAR **Stream, TCHAR *Result, int32 MaxLen, bool Exact=false)
Get a line of Stream (everything up to, but not including, CR/LF.
static bool LineExtended (const TCHAR **Stream, FString &Result, int32 &LinesConsumed, ELineExtendedFlags Flags=ELineExtendedFlags::Standard)
static bool LineExtended (const TCHAR **Stream, FStringBuilderBase &Result, int32 &LinesConsumed, ELineExtendedFlags Flags=ELineExtendedFlags::Standard)
static void Next (const TCHAR **Stream)
Get next command.
static bool Param (const TCHAR *Stream, const TCHAR *Param)
Checks if a command-line parameter exists in the stream.
static bool QuotedString (const TCHAR *Stream, FString &Value, int32 *OutNumCharsRead=nullptr)
Parse a quoted string token.
static bool QuotedString (const TCHAR *Stream, FStringBuilderBase &Value, int32 *OutNumCharsRead=nullptr)
static bool SchemeNameFromURI (const TCHAR *InURI, FString &OutSchemeName)
Parses the scheme name from a URI.
static bool Text (const TCHAR *Stream, FText &Value, const TCHAR *Namespace=nullptr)
Parse an Text token.
static FString Token (const TCHAR *&Str, bool UseEscape)
Grabs the next space-delimited string from the input stream.
static bool Token (const TCHAR *&Str, FString &Arg, bool bUseEscape, const TCHAR SingleCharacterDelimiter=TEXT('\0'))
Grabs the next space-delimited (unless SingleCharacterDelimiter is provided) string from the input stream.
static bool Token (const TCHAR *&Str, TCHAR *Result, int32 MaxLen, bool bUseEscape, const TCHAR SingleCharacterDelimiter=TEXT('\0'))
Grabs the next space-delimited (unless SingleCharacterDelimiter is provided) string from the input stream.
static bool Value (const TCHAR *Stream, const TCHAR *Match, double &Value)
Parses a double precision floating-point value.
static bool Value (const TCHAR *Stream, const TCHAR *Match, float &Value)
Parses a floating-point value.
static bool Value (const TCHAR *Stream, const TCHAR *Match, FName &Name)
Parses a name.
static bool Value (const TCHAR *Stream, const TCHAR *Match, FString &Value, bool bShouldStopOnSeparator=true, const TCHAR **OptStreamGotTo=nullptr)
Parses a string.
static bool Value (const TCHAR *Stream, const TCHAR *Match, FText &Value, const TCHAR *Namespace=NULL)
Parses an FText.
static bool Value (const TCHAR *Stream, const TCHAR *Match, int16 &Value)
Parses a signed word.
static bool Value (const TCHAR *Stream, const TCHAR *Match, int32 &Value)
Parses a signed double word.
static bool Value (const TCHAR *Stream, const TCHAR *Match, int64 &Value)
Parses a signed quadword.
static bool Value (const TCHAR *Stream, const TCHAR *Match, int8 &Value)
Parses a signed byte.
static bool Value (const TCHAR *Stream, const TCHAR *Match, struct FGuid &Guid)
Parses a globally unique identifier.
static bool Value (const TCHAR *Stream, const TCHAR *Match, TCHAR *Value, int32 MaxLen, bool bShouldStopOnSeparator=true, const TCHAR **OptStreamGotTo=nullptr)
Parses a string from a text string.
static bool Value (const TCHAR *Stream, const TCHAR *Match, uint16 &Value)
Parses a uint16.
static bool Value (const TCHAR *Stream, const TCHAR *Match, uint32 &Value)
Parses a uint32.
static bool Value (const TCHAR *Stream, const TCHAR *Match, uint64 &Value)
Parses a quadword.
static bool Value (const TCHAR *Stream, const TCHAR *Match, uint8 &Value)
Parses a byte.
Data Fields
FString int32 bool bExact
FStringBuilderBase int32 bool bExact
FString int32 & LinesConsumed
FStringBuilderBase int32 & LinesConsumed
FString & Result
FStringBuilderBase & Result
Detailed Description
Definition at line 21 of file Parse.h.
Member Enumeration Documentation
EGrammarBasedParseErrorCode
enum class FParse::EGrammarBasedParseErrorCode strong
Enumerator
Succeeded
NotRun
UnBalancedQuote
DisallowedQuotedCommand
Definition at line 194 of file Parse.h.
EGrammarBasedParseFlags
enum class FParse::EGrammarBasedParseFlags strong
Enumerator
None
AllowQuotedCommands
Definition at line 188 of file Parse.h.
ELineExtendedFlags
enum class FParse::ELineExtendedFlags : uint8 strong
Get a line of Stream, with support for extending beyond that line with certain characters, e.g.
{} and \ the out character array will not include the ignored endlines
Enumerator
None
SwallowDoubleSlashComments
SwallowSemicolonComments
SwallowExtraEOLs
BreakOnPipe
AllowBracketedMultiline
AllowEscapedEOLMultiline
Standard
OldDefaultMode
OldExactMode
Definition at line 89 of file Parse.h.
Member Function Documentation
AlnumToken()
bool FParse::AlnumToken (const TCHAR *& Str, FString & Arg) static
Grabs the next alpha-numeric space-delimited token from the input stream.
Bool()
bool FParse::Bool (const TCHAR * Stream, const TCHAR * Match, bool & OnOff) static
Parses a boolean value.
References Match, and Stream.
Command()
bool FParse::Command (const TCHAR ** Stream, const TCHAR * Match, bool bParseMightTriggerExecution = true) static
Sees if Stream starts with the named command.
If it does, skips through the command and blanks past it. Returns true of match.
Parameters
bParseMightTriggerExecution true: Caller guarantees this is only part of parsing and no execution happens without further parsing (good for "DumpConsoleCommands").
References Match, and Stream.
Expression()
bool FParse::Expression (const TCHAR *& Str, FString & OutExpression, bool bUseEscape, const TCHAR SingleCharacterDelimiter = TEXT('\0')) static
Parse the next space-delimited (or SingleCharacterDelmiter-delimited) expression, using brackets (), {}, or [] to allow subexpressions to be part of the single expression even if they contain the delimiter.
The parsed expression can be either an atomic token such as "Value1" in the stream "Value1 Value2 Value3" or a bracketed expression such as "(Value1.1 Value1.2)" in the stream "(Value1.1 Value1.2) Value2 Value3". If quotes are encountered, text inside of the quotes is not interpreted (brackets and delimiters are ignored) and it is included verbatim in the parsed expression. Trailing delimiters are not consumed, only leading delimiters.
GrammarBasedCLIParse()
FGrammarBasedParseResult FParse::GrammarBasedCLIParse (const TCHAR * Stream, TFunctionRef< void(FStringView, FStringView)> OnCommandCallback, EGrammarBasedParseFlags Flags = EGrammarBasedParseFlags::AllowQuotedCommands) static
Grammar Line -> Cmd* Cmd -> "Cmd*" – allowed if EGrammaredParseFlags::AllowQuotedCommands is given | Key(=Value)?
– invokes OnCommandCallback Key -> (/|(-?-?))Ident Value -> "[^"]*" | [^" \t\r
]+ Ident -> [_a-zA-Z][_a-zA-Z0-9.]*
Grammar Key Expressions
Operators
= 0 or more of a expression
= 1 or more of a expression ? = 0 or 1 of an expression (IE, its optional) [] = set of characters () = treat enclosed expressions as 1 for purpose of other operators
References AllowQuotedCommands, Flags, and Stream.
HexDigit()
FORCEINLINE int32 FParse::HexDigit (TCHAR c) inline static
Definition at line 152 of file Parse.h.
References FORCEINLINE, and Result.
HexNumber()
uint32 FParse::HexNumber (FStringView HexString) static
Parses a hexadecimal string value.
HexNumber64()
uint64 FParse::HexNumber64 (FStringView HexString) static
Line() [1/3]
bool FParse::Line (const TCHAR ** Stream, FString & Result, bool Exact = false) static
Get a line of Stream (everything up to, but not including, CR/LF.
Returns 0 if ok, nonzero if at end of stream and returned 0-length string.
References Exact, Result, and Stream.
Line() [2/3]
bool FParse::Line (const TCHAR ** Stream, FStringView & Result, bool Exact = false) static
Get a line of Stream (everything up to, but not including, CR/LF.
Returns 0 if ok, nonzero if at end of stream and returned 0-length string.
References Exact, Result, and Stream.
Line() [3/3]
bool FParse::Line (const TCHAR ** Stream, TCHAR * Result, int32 MaxLen, bool Exact = false) static
Get a line of Stream (everything up to, but not including, CR/LF.
Returns 0 if ok, nonzero if at end of stream and returned 0-length string.
References Exact, Result, and Stream.
LineExtended() [1/2]
bool FParse::LineExtended (const TCHAR ** Stream, FString & Result, int32 & LinesConsumed, ELineExtendedFlags Flags = ELineExtendedFlags::Standard) static
References Flags, LinesConsumed, Result, Standard, and Stream.
LineExtended() [2/2]
bool FParse::LineExtended (const TCHAR ** Stream, FStringBuilderBase & Result, int32 & LinesConsumed, ELineExtendedFlags Flags = ELineExtendedFlags::Standard) static
References Flags, LinesConsumed, Result, Standard, and Stream.
Next()
void FParse::Next (const TCHAR ** Stream) static
Get next command.
Skips past comments and cr's.
References Stream.
Param()
bool FParse::Param (const TCHAR * Stream, const TCHAR * Param) static
Checks if a command-line parameter exists in the stream.
References Param(), and Stream.
Referenced by FApp::CanEverRender(), FApp::CanEverRenderAudio(), FApp::IsAudioMuted(), IsPlatformIoDispatcherEnabled(), IsRunningHybridCookedEditor(), Param(), PhysSingleThreadedMode(), FCachedReadPlatformFile::ShouldBeUsed(), and FPlatformFileOpenLog::ShouldBeUsed().
QuotedString() [1/2]
bool FParse::QuotedString (const TCHAR * Stream, FString & Value, int32 * OutNumCharsRead = nullptr) static
Parse a quoted string token.
References Stream, and Value().
QuotedString() [2/2]
bool FParse::QuotedString (const TCHAR * Stream, FStringBuilderBase & Value, int32 * OutNumCharsRead = nullptr) static
References Stream, and Value().
SchemeNameFromURI()
bool FParse::SchemeNameFromURI (const TCHAR * InURI, FString & OutSchemeName) static
Parses the scheme name from a URI.
Text()
bool FParse::Text (const TCHAR * Stream, FText & Value, const TCHAR * Namespace = nullptr) static
Parse an Text token.
References Stream, and Value().
Token() [1/3]
FString FParse::Token (const TCHAR *& Str, bool UseEscape) static
Grabs the next space-delimited string from the input stream.
If quoted, gets entire quoted string.
Token() [2/3]
bool FParse::Token (const TCHAR *& Str, FString & Arg, bool bUseEscape, const TCHAR SingleCharacterDelimiter = TEXT('\0')) static
Grabs the next space-delimited (unless SingleCharacterDelimiter is provided) string from the input stream.
If quoted, gets entire quoted string.
Token() [3/3]
bool FParse::Token (const TCHAR *& Str, TCHAR * Result, int32 MaxLen, bool bUseEscape, const TCHAR SingleCharacterDelimiter = TEXT('\0')) static
Grabs the next space-delimited (unless SingleCharacterDelimiter is provided) string from the input stream.
If quoted, gets entire quoted string.
References Result.
UE_DEPRECATED() [1/2]
FParse::UE_DEPRECATED (5. 6, "Use the version that takes ELineExtendedFlags") const
UE_DEPRECATED() [2/2]
FParse::UE_DEPRECATED (5. 6, "Use the version that takes ELineExtendedFlags") const
Value() [1/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, double & Value) static
Parses a double precision floating-point value.
References Match, Stream, and Value().
Value() [2/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, float & Value) static
Parses a floating-point value.
References Match, Stream, and Value().
Value() [3/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, FName & Name) static
Parses a name.
References Match, Name, and Stream.
Referenced by FDriverConfigEntryConstraints::FDriverConfigEntryConstraints(), FDriverDenyListEntry::FDriverDenyListEntry(), FSuggestedDriverEntry::FSuggestedDriverEntry(), DEFINE_LOG_CATEGORY_STATIC(), DisplayClusterHelpers::str::ExtractValue(), DisplayClusterTypesConverter::FromHexString(), DisplayClusterTypesConverter::FromString(), UE::Math::TVector< T >::InitFromCompactString(), UE::Math::TIntPoint< IntType >::InitFromString(), UE::Math::TIntVector2< int32 >::InitFromString(), UE::Math::TIntVector3< int32 >::InitFromString(), UE::Math::TIntVector4< int32 >::InitFromString(), UE::Math::TQuat< T >::InitFromString(), UE::Math::TRotator< T >::InitFromString(), UE::Math::TVector2< T >::InitFromString(), UE::Math::TVector4< T >::InitFromString(), UE::Math::TVector< T >::InitFromString(), IsPlatformIoDispatcherEnabled(), QuotedString(), QuotedString(), Text(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), and Value().
Value() [4/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, FString & Value, bool bShouldStopOnSeparator = true, const TCHAR ** OptStreamGotTo = nullptr) static
Parses a string.
Parameters
Stream,the string you want to extract the value from.
Match,the identifier for the value in the stream.
Value,the destination to the value to be extracted to.
bShouldStopOnSeparator,(default = true) If this is true, and the value doesn't start with a '"' then it may be truncated to ',' or ')' in addition to whitespace.
OptStreamGotTo,(default = nullptr) If this is not null, then its dereference is set to the address of the end of the value within Stream. This permits consuming of stream in a loop where Match may occur multiple times.
References Match, Stream, and Value().
Value() [5/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, FText & Value, const TCHAR * Namespace = NULL) static
Parses an FText.
References Match, Stream, and Value().
Value() [6/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, int16 & Value) static
Parses a signed word.
References Match, Stream, and Value().
Value() [7/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, int32 & Value) static
Parses a signed double word.
References Match, Stream, and Value().
Value() [8/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, int64 & Value) static
Parses a signed quadword.
References Match, Stream, and Value().
Value() [9/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, int8 & Value) static
Parses a signed byte.
References Match, Stream, and Value().
Value() [10/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, struct FGuid & Guid) static
Parses a globally unique identifier.
References Guid, Match, and Stream.
Value() [11/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, TCHAR * Value, int32 MaxLen, bool bShouldStopOnSeparator = true, const TCHAR ** OptStreamGotTo = nullptr) static
Parses a string from a text string.
Parameters
Stream,the string you want to extract the value from.
Match,the identifier for the value in the stream.
Value,the destination to the value to be extracted to.
MaxLen,the maximum size eof the string that can be extracted.
bShouldStopOnSeparator,(default = true) If this is true, and the value doesn't start with a '"' then it may be truncated to ',' or ')' in addition to whitespace.
OptStreamGotTo,(default = nullptr) If this is not null, then its dereference is set to the address of the end of the value within Stream. This permits consuming of stream in a loop where Match may occur multiple times.
References Match, Stream, and Value().
Value() [12/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, uint16 & Value) static
Parses a uint16.
References Match, Stream, and Value().
Value() [13/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, uint32 & Value) static
Parses a uint32.
References Match, Stream, and Value().
Value() [14/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, uint64 & Value) static
Parses a quadword.
References Match, Stream, and Value().
Value() [15/15]
bool FParse::Value (const TCHAR * Stream, const TCHAR * Match, uint8 & Value) static
Parses a byte.
References Match, Stream, and Value().
Field Documentation
bExact [1/2]
FString int32 bool FParse::bExact
Initial value:
{
        return LineExtended(Stream, Result, LinesConsumed, (bExact ? ELineExtendedFlags::OldExactMode : ELineExtendedFlags::OldDefaultMode))
Definition at line 111 of file Parse.h.
bExact [2/2]
FStringBuilderBase int32 bool FParse::bExact
Initial value:
{
        return LineExtended(Stream, Result, LinesConsumed, (bExact ? ELineExtendedFlags::OldExactMode : ELineExtendedFlags::OldDefaultMode))
Definition at line 116 of file Parse.h.
LinesConsumed [1/2]
FString int32& FParse::LinesConsumed
Definition at line 111 of file Parse.h.
Referenced by LineExtended(), and LineExtended().
LinesConsumed [2/2]
FStringBuilderBase int32& FParse::LinesConsumed
Definition at line 116 of file Parse.h.
Result [1/2]
FString& FParse::Result
Definition at line 111 of file Parse.h.
Referenced by HexDigit(), Line(), Line(), Line(), LineExtended(), LineExtended(), and Token().
Result [2/2]
FStringBuilderBase& FParse::Result
Definition at line 116 of file Parse.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Parse.h