Unreal Engine 5.6 C++ API: UE::AssetRegistry::FPackageCustomVersion Struct Reference
UE::AssetRegistry::FPackageCustomVersion Struct Reference
Low-memory version of FCustomVersion; holds only Guid and integer version.
#include "AssetData.h"
Public Member Functions
FPackageCustomVersion ()=default
FPackageCustomVersion (const FGuid &InKey, const int32 InVersion)
bool operator< (const FPackageCustomVersion &RHS) const
bool operator== (const FPackageCustomVersion &RHS) const
Data Fields
FGuid Key
int32 Version = 0
Private Member Functions
bool TryRead (const FCbFieldView &Field)
FCbWriter & Write (FCbWriter &Writer) const
Friends
bool LoadFromCompactBinary (const FCbFieldView &Field, FPackageCustomVersion &Value)
FArchive & operator<< (FArchive &Ar, FPackageCustomVersion &CustomVersion)
FCbWriter & operator<< (FCbWriter &Writer, const FPackageCustomVersion &Value)
Detailed Description
Low-memory version of FCustomVersion; holds only Guid and integer version.
Definition at line 876 of file AssetData.h.
Constructor & Destructor Documentation
FPackageCustomVersion() [1/2]
UE::AssetRegistry::FPackageCustomVersion::FPackageCustomVersion () default
Referenced by LoadFromCompactBinary, operator<(), operator<<, operator<<, and operator==().
FPackageCustomVersion() [2/2]
UE::AssetRegistry::FPackageCustomVersion::FPackageCustomVersion (const FGuid & InKey, const int32 InVersion) inline
Definition at line 882 of file AssetData.h.
References Key, and Version.
Member Function Documentation
operator<()
bool UE::AssetRegistry::FPackageCustomVersion::operator< (const FPackageCustomVersion & RHS) const inline
Definition at line 887 of file AssetData.h.
References FPackageCustomVersion(), Key, and Version.
operator==()
bool UE::AssetRegistry::FPackageCustomVersion::operator== (const FPackageCustomVersion & RHS) const inline
Definition at line 893 of file AssetData.h.
References FPackageCustomVersion(), Key, and Version.
TryRead()
bool UE::AssetRegistry::FPackageCustomVersion::TryRead (const FCbFieldView & Field) private
Write()
FCbWriter & UE::AssetRegistry::FPackageCustomVersion::Write (FCbWriter & Writer) const private
Friends And Related Symbol Documentation
LoadFromCompactBinary
bool LoadFromCompactBinary (const FCbFieldView & Field, FPackageCustomVersion & Value) friend
Definition at line 908 of file AssetData.h.
References FPackageCustomVersion(), and Value.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPackageCustomVersion & CustomVersion) friend
Definition at line 897 of file AssetData.h.
References FPackageCustomVersion(), Ar, Key, and Version.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FPackageCustomVersion & Value) friend
Definition at line 903 of file AssetData.h.
References FPackageCustomVersion(), and Value.
Field Documentation
Key
FGuid UE::AssetRegistry::FPackageCustomVersion::Key
Definition at line 878 of file AssetData.h.
Referenced by FPackageCustomVersion(), operator<(), operator<<, and operator==().
Version
int32 UE::AssetRegistry::FPackageCustomVersion::Version = 0
Definition at line 879 of file AssetData.h.
Referenced by FPackageCustomVersion(), operator<(), operator<<, and operator==().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetData.h