Unreal Engine 5.6 C++ API: FMovieSceneEvaluationState Struct Reference
FMovieSceneEvaluationState Struct Reference
Provides runtime evaluation functions with the ability to look up state from the main game environment.
#include "MovieSceneEvaluationState.h"
Data Structures
struct FVersionedObjectCache
Object cache with a last known serial of it.
Public Types
using FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Public Member Functions
FMovieSceneEvaluationState (const FMovieSceneEvaluationState &)=delete
MOVIESCENE_API void AssignSequence (FMovieSceneSequenceIDRef InSequenceID, UMovieSceneSequence &InSequence, IMovieScenePlayer &Player)
MOVIESCENE_API void AssignSequence (FMovieSceneSequenceIDRef InSequenceID, UMovieSceneSequence &InSequence, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Assign a sequence to a specific ID.
MOVIESCENE_API void ClearObjectCaches (IMovieScenePlayer &Player)
MOVIESCENE_API void ClearObjectCaches (TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Forcably clear all object caches.
MOVIESCENE_API void FilterObjectBindings (UObject *PredicateObject, IMovieScenePlayer &Player, TArray< FMovieSceneObjectBindingID > *OutBindings)
MOVIESCENE_API void FilterObjectBindings (UObject *PredicateObject, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, TArray< FMovieSceneObjectBindingID > *OutBindings)
Filter all the object bindings in this object cache that contain the specified predicate object.
TArrayView< TWeakObjectPtr<> > FindBoundObjects (const FGuid &ObjectBindingID, FMovieSceneSequenceIDRef SequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Locate objects bound to the specified object guid, in the specified sequence.
TArrayView< TWeakObjectPtr<> > FindBoundObjects (const FMovieSceneEvaluationOperand &Operand, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Locate objects bound to the specified sequence operand.
MOVIESCENE_API FGuid FindCachedObjectId (UObject &Object, FMovieSceneSequenceIDRef InSequenceID, IMovieScenePlayer &Player)
MOVIESCENE_API FGuid FindCachedObjectId (UObject &Object, FMovieSceneSequenceIDRef InSequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Attempt deduce the posessable or spawnable that relates to the specified object.
FORCEINLINE FMovieSceneObjectCache * FindObjectCache (FMovieSceneSequenceIDRef SequenceID)
Find an object cache pertaining to the specified sequence.
FORCEINLINE const FMovieSceneObjectCache * FindObjectCache (FMovieSceneSequenceIDRef SequenceID) const
Find an object cache pertaining to the specified sequence.
MOVIESCENE_API FGuid FindObjectId (UObject &Object, FMovieSceneSequenceIDRef InSequenceID, IMovieScenePlayer &Player)
MOVIESCENE_API FGuid FindObjectId (UObject &Object, FMovieSceneSequenceIDRef InSequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Attempt deduce the posessable or spawnable that relates to the specified object.
MOVIESCENE_API UMovieSceneSequence * FindSequence (FMovieSceneSequenceIDRef InSequenceID) const
Attempt to locate a sequence from its ID.
MOVIESCENE_API FMovieSceneSequenceID FindSequenceId (const UMovieSceneSequence *InSequence) const
MOVIESCENE_API FMovieSceneSequenceID FindSequenceId (UMovieSceneSequence *InSequence) const
Attempt to locate a sequence ID from a sequence.
MOVIESCENE_API bool GetBindingActivation (const FGuid &InGuid, FMovieSceneSequenceIDRef InSequenceID) const
FORCEINLINE FMovieSceneObjectCache & GetObjectCache (FMovieSceneSequenceIDRef SequenceID)
Get an object cache pertaining to the specified sequence.
MOVIESCENE_API uint32 GetSerialNumber ()
Get the serial number for this state.
virtual MOVIESCENE_API void Initialize (TSharedRef< const FSharedPlaybackState > Owner) override
IPlaybackCapability members.
MOVIESCENE_API void Invalidate (const FGuid &InGuid, FMovieSceneSequenceIDRef InSequenceID)
Forcably invalidate the specified object binding in the specified sequence.
MOVIESCENE_API void InvalidateExpiredObjects ()
Invalidate any object caches that may now contain expired objects.
virtual MOVIESCENE_API void OnSubInstanceCreated (TSharedRef< const FSharedPlaybackState > Owner, const UE::MovieScene::FInstanceHandle InstanceHandle) override
Called when a new sequence instance has been created and added to the sequence hierarchy.
FMovieSceneEvaluationState & operator= (const FMovieSceneEvaluationState &)=delete
MOVIESCENE_API void SetBindingActivation (const FGuid &InGuid, FMovieSceneSequenceIDRef InSequenceID, bool bActive)
UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API (MOVIESCENE_API, FMovieSceneEvaluationState) FMovieSceneEvaluationState()=default
Public Member Functions inherited from UE::MovieScene::IPlaybackCapability
virtual ~IPlaybackCapability ()
virtual void InvalidateCachedData (UMovieSceneEntitySystemLinker *Linker)
Called when the root sequence is cleaning cached data.
Data Fields
TMap< FMovieSceneEvaluationKey, TUniquePtr< IPersistentEvaluationData > > PersistentEntityData
A map of persistent evaluation data mapped by movie scene evaluation entity (i.e, a given track or section)
TMap< FSharedPersistentDataKey, TUniquePtr< IPersistentEvaluationData > > PersistentSharedData
A map of persistent evaluation data mapped by shared evaluation key.
Private Member Functions
void RegisterObjectCacheEvents (UMovieSceneEntitySystemLinker *Linker, const UE::MovieScene::FInstanceHandle &InstanceHandle, const FMovieSceneSequenceID SequenceID)
Private Attributes
TMap< FMovieSceneSequenceID, FVersionedObjectCache > ObjectCaches
Maps of bound objects, arranged by template ID.
uint32 SerialNumber = 0
Current serial number of this collection of caches.
Detailed Description
Provides runtime evaluation functions with the ability to look up state from the main game environment.
Definition at line 306 of file MovieSceneEvaluationState.h.
Member Typedef Documentation
FSharedPlaybackState
using FMovieSceneEvaluationState::FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Definition at line 308 of file MovieSceneEvaluationState.h.
Constructor & Destructor Documentation
FMovieSceneEvaluationState()
FMovieSceneEvaluationState::FMovieSceneEvaluationState (const FMovieSceneEvaluationState &) delete
References FMovieSceneEvaluationState().
Referenced by FMovieSceneEvaluationState(), operator=(), and UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API().
Member Function Documentation
AssignSequence() [1/2]
MOVIESCENE_API void FMovieSceneEvaluationState::AssignSequence (FMovieSceneSequenceIDRef InSequenceID, UMovieSceneSequence & InSequence, IMovieScenePlayer & Player)
AssignSequence() [2/2]
MOVIESCENE_API void FMovieSceneEvaluationState::AssignSequence (FMovieSceneSequenceIDRef InSequenceID, UMovieSceneSequence & InSequence, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Assign a sequence to a specific ID.
Parameters
InSequenceID The sequence ID to assign to
InSequence The sequence to assign
ClearObjectCaches() [1/2]
MOVIESCENE_API void FMovieSceneEvaluationState::ClearObjectCaches (IMovieScenePlayer & Player)
ClearObjectCaches() [2/2]
MOVIESCENE_API void FMovieSceneEvaluationState::ClearObjectCaches (TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Forcably clear all object caches.
FilterObjectBindings() [1/2]
MOVIESCENE_API void FMovieSceneEvaluationState::FilterObjectBindings (UObject * PredicateObject, IMovieScenePlayer & Player, TArray< FMovieSceneObjectBindingID > * OutBindings)
FilterObjectBindings() [2/2]
MOVIESCENE_API void FMovieSceneEvaluationState::FilterObjectBindings (UObject * PredicateObject, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, TArray< FMovieSceneObjectBindingID > * OutBindings)
Filter all the object bindings in this object cache that contain the specified predicate object.
Parameters
PredicateObject The object to filter by. Any bindings referencing this object will be added to the output array.
Player The movie scene player that is playing back the sequence
OutBindings (mandatory) Array to populate with bindings that relate to the object
FindBoundObjects() [1/2]
TArrayView< TWeakObjectPtr<> > FMovieSceneEvaluationState::FindBoundObjects (const FGuid & ObjectBindingID, FMovieSceneSequenceIDRef SequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) inline
Locate objects bound to the specified object guid, in the specified sequence.
Note
: Objects lists are cached internally until they are invalidate.
Parameters
ObjectBindingID The object to resolve
SequenceID ID of the sequence to resolve for
Returns
Iterable list of weak object pointers pertaining to the specified GUID
Definition at line 420 of file MovieSceneEvaluationState.h.
References FindObjectCache().
Referenced by FindBoundObjects().
FindBoundObjects() [2/2]
TArrayView< TWeakObjectPtr<> > FMovieSceneEvaluationState::FindBoundObjects (const FMovieSceneEvaluationOperand & Operand, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) inline
Locate objects bound to the specified sequence operand.
Note
: Objects lists are cached internally until they are invalidate.
Parameters
Operand The movie scene operand to resolve
Returns
Iterable list of weak object pointers pertaining to the specified GUID
Definition at line 439 of file MovieSceneEvaluationState.h.
References FindBoundObjects().
FindCachedObjectId() [1/2]
MOVIESCENE_API FGuid FMovieSceneEvaluationState::FindCachedObjectId (UObject & Object, FMovieSceneSequenceIDRef InSequenceID, IMovieScenePlayer & Player)
References Object.
FindCachedObjectId() [2/2]
MOVIESCENE_API FGuid FMovieSceneEvaluationState::FindCachedObjectId (UObject & Object, FMovieSceneSequenceIDRef InSequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Attempt deduce the posessable or spawnable that relates to the specified object.
Note
Does not clear the existing cache
Parameters
InObject The object whose binding ID is to be find
Player The movie scene player that is playing back the sequence
Returns
The object's spawnable or possessable GUID, or a zero GUID if it was not found
References Object.
FindObjectCache() [1/2]
FORCEINLINE FMovieSceneObjectCache * FMovieSceneEvaluationState::FindObjectCache (FMovieSceneSequenceIDRef SequenceID) inline
Find an object cache pertaining to the specified sequence.
Parameters
InSequenceID The sequence ID to lookup
Definition at line 373 of file MovieSceneEvaluationState.h.
References FORCEINLINE, and ObjectCaches.
Referenced by FindBoundObjects().
FindObjectCache() [2/2]
FORCEINLINE const FMovieSceneObjectCache * FMovieSceneEvaluationState::FindObjectCache (FMovieSceneSequenceIDRef SequenceID) const inline
Find an object cache pertaining to the specified sequence.
Parameters
InSequenceID The sequence ID to lookup
Definition at line 387 of file MovieSceneEvaluationState.h.
References FORCEINLINE, and ObjectCaches.
FindObjectId() [1/2]
MOVIESCENE_API FGuid FMovieSceneEvaluationState::FindObjectId (UObject & Object, FMovieSceneSequenceIDRef InSequenceID, IMovieScenePlayer & Player)
References Object.
FindObjectId() [2/2]
MOVIESCENE_API FGuid FMovieSceneEvaluationState::FindObjectId (UObject & Object, FMovieSceneSequenceIDRef InSequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Attempt deduce the posessable or spawnable that relates to the specified object.
Note
Will forcably resolve any out of date bindings in the entire sequence
Parameters
InObject The object whose binding ID is to be find
Player The movie scene player that is playing back the sequence
Returns
The object's spawnable or possessable GUID, or a zero GUID if it was not found
References Object.
FindSequence()
MOVIESCENE_API UMovieSceneSequence * FMovieSceneEvaluationState::FindSequence (FMovieSceneSequenceIDRef InSequenceID) const
Attempt to locate a sequence from its ID.
Parameters
InSequenceID The sequence ID to lookup
FindSequenceId() [1/2]
MOVIESCENE_API FMovieSceneSequenceID FMovieSceneEvaluationState::FindSequenceId (const UMovieSceneSequence * InSequence) const
FindSequenceId() [2/2]
MOVIESCENE_API FMovieSceneSequenceID FMovieSceneEvaluationState::FindSequenceId (UMovieSceneSequence * InSequence) const
Attempt to locate a sequence ID from a sequence.
Parameters
InSequence The sequence to look up
GetBindingActivation()
MOVIESCENE_API bool FMovieSceneEvaluationState::GetBindingActivation (const FGuid & InGuid, FMovieSceneSequenceIDRef InSequenceID) const
GetObjectCache()
FORCEINLINE FMovieSceneObjectCache & FMovieSceneEvaluationState::GetObjectCache (FMovieSceneSequenceIDRef SequenceID) inline
Get an object cache pertaining to the specified sequence.
Parameters
InSequenceID The sequence ID to lookup
Definition at line 401 of file MovieSceneEvaluationState.h.
References FORCEINLINE, and ObjectCaches.
GetSerialNumber()
MOVIESCENE_API uint32 FMovieSceneEvaluationState::GetSerialNumber ()
Get the serial number for this state.
Initialize()
virtual MOVIESCENE_API void FMovieSceneEvaluationState::Initialize (TSharedRef< const FSharedPlaybackState > Owner) override virtual
IPlaybackCapability members.
Reimplemented from UE::MovieScene::IPlaybackCapability.
References Owner.
Invalidate()
MOVIESCENE_API void FMovieSceneEvaluationState::Invalidate (const FGuid & InGuid, FMovieSceneSequenceIDRef InSequenceID)
Forcably invalidate the specified object binding in the specified sequence.
Parameters
InGuid The object binding ID to invalidate
InSequenceID The sequence ID to which the object binding belongs
InvalidateExpiredObjects()
MOVIESCENE_API void FMovieSceneEvaluationState::InvalidateExpiredObjects ()
Invalidate any object caches that may now contain expired objects.
OnSubInstanceCreated()
virtual MOVIESCENE_API void FMovieSceneEvaluationState::OnSubInstanceCreated (TSharedRef< const FSharedPlaybackState > Owner, const UE::MovieScene::FInstanceHandle InstanceHandle) override virtual
Called when a new sequence instance has been created and added to the sequence hierarchy.
Reimplemented from UE::MovieScene::IPlaybackCapability.
References Owner.
operator=()
FMovieSceneEvaluationState & FMovieSceneEvaluationState::operator= (const FMovieSceneEvaluationState &) delete
References FMovieSceneEvaluationState().
RegisterObjectCacheEvents()
void FMovieSceneEvaluationState::RegisterObjectCacheEvents (UMovieSceneEntitySystemLinker * Linker, const UE::MovieScene::FInstanceHandle & InstanceHandle, const FMovieSceneSequenceID SequenceID) private
SetBindingActivation()
MOVIESCENE_API void FMovieSceneEvaluationState::SetBindingActivation (const FGuid & InGuid, FMovieSceneSequenceIDRef InSequenceID, bool bActive)
UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API()
FMovieSceneEvaluationState::UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API (MOVIESCENE_API , FMovieSceneEvaluationState) default
References FMovieSceneEvaluationState().
Field Documentation
ObjectCaches
TMap<FMovieSceneSequenceID, FVersionedObjectCache> FMovieSceneEvaluationState::ObjectCaches private
Maps of bound objects, arranged by template ID.
Definition at line 519 of file MovieSceneEvaluationState.h.
Referenced by FindObjectCache(), FindObjectCache(), and GetObjectCache().
PersistentEntityData
TMap<FMovieSceneEvaluationKey, TUniquePtr<IPersistentEvaluationData> > FMovieSceneEvaluationState::PersistentEntityData
A map of persistent evaluation data mapped by movie scene evaluation entity (i.e, a given track or section)
Definition at line 482 of file MovieSceneEvaluationState.h.
PersistentSharedData
TMap<FSharedPersistentDataKey, TUniquePtr<IPersistentEvaluationData> > FMovieSceneEvaluationState::PersistentSharedData
A map of persistent evaluation data mapped by shared evaluation key.
Such data can be accessed from anywhere given an operand and a unique identifier.
Definition at line 485 of file MovieSceneEvaluationState.h.
SerialNumber
uint32 FMovieSceneEvaluationState::SerialNumber = 0 private
Current serial number of this collection of caches.
Definition at line 522 of file MovieSceneEvaluationState.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieSceneEvaluationState.h