Unreal Engine 5.6 C++ API: FGenericPlatformTLS Struct Reference
FGenericPlatformTLS Struct Reference
It should be possible to provide a generic implementation as long as a threadID is provided.
#include "GenericPlatformTLS.h"
Static Public Member Functions
static FORCEINLINE bool IsValidTlsSlot (uint32 SlotIndex)
Return false if this is an invalid TLS slot.
Static Public Attributes
static const uint32 InvalidTlsSlot = 0xFFFFFFFF
Detailed Description
It should be possible to provide a generic implementation as long as a threadID is provided.
We don't do that yet.
Definition at line 11 of file GenericPlatformTLS.h.
Member Function Documentation
IsValidTlsSlot()
FORCEINLINE bool FGenericPlatformTLS::IsValidTlsSlot (uint32 SlotIndex) inline static
Return false if this is an invalid TLS slot.
Parameters
SlotIndex the TLS index to check
Returns
true if this looks like a valid slot
Definition at line 20 of file GenericPlatformTLS.h.
References FORCEINLINE, and InvalidTlsSlot.
Referenced by TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::TLockFreeFixedSizeAllocator_TLSCacheBase(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::ClearTLS(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Get(), TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::GetTLS(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::SetTLS(), and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::SetupTLSCachesOnCurrentThread().
Field Documentation
InvalidTlsSlot
const uint32 FGenericPlatformTLS::InvalidTlsSlot = 0xFFFFFFFF static
Definition at line 13 of file GenericPlatformTLS.h.
Referenced by TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::~TLockFreeFixedSizeAllocator_TLSCacheBase(), TThreadSingleton< T >::~TThreadSingleton(), FAndroidTLS::AllocTlsSlot(), FApplePlatformTLS::AllocTlsSlot(), TThreadSingleton< T >::GetTlsSlot(), and IsValidTlsSlot().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformTLS.h