Unreal Engine 5.6 C++ API: SkeletalMeshImportData::FVertexAttribute Struct Reference
SkeletalMeshImportData::FVertexAttribute Struct Reference
#include "SkeletalMeshLODImporterData.h"
Public Member Functions
FVertexAttribute ()=default
FVertexAttribute (const FVertexAttribute &)=default
FVertexAttribute (FVertexAttribute &&)=default
FVertexAttribute (TArray< float > &&InAttributeValues, int32 InComponentCount)
Data Fields
TArray< float > AttributeValues
int32 ComponentCount
Friends
FArchive & operator<< (FArchive &Ar, FVertexAttribute &A)
Detailed Description
Definition at line 296 of file SkeletalMeshLODImporterData.h.
Constructor & Destructor Documentation
FVertexAttribute() [1/4]
SkeletalMeshImportData::FVertexAttribute::FVertexAttribute () default
Referenced by FVertexAttribute(), FVertexAttribute(), and operator<<.
FVertexAttribute() [2/4]
SkeletalMeshImportData::FVertexAttribute::FVertexAttribute (TArray< float > && InAttributeValues, int32 InComponentCount) inline
Definition at line 299 of file SkeletalMeshLODImporterData.h.
References AttributeValues, and ComponentCount.
FVertexAttribute() [3/4]
SkeletalMeshImportData::FVertexAttribute::FVertexAttribute (const FVertexAttribute &) default
References FVertexAttribute().
FVertexAttribute() [4/4]
SkeletalMeshImportData::FVertexAttribute::FVertexAttribute (FVertexAttribute &&) default
References FVertexAttribute().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FVertexAttribute & A) friend
Definition at line 308 of file SkeletalMeshLODImporterData.h.
References FVertexAttribute(), A, and Ar.
Field Documentation
AttributeValues
TArray<float> SkeletalMeshImportData::FVertexAttribute::AttributeValues
Definition at line 305 of file SkeletalMeshLODImporterData.h.
Referenced by FVertexAttribute().
ComponentCount
int32 SkeletalMeshImportData::FVertexAttribute::ComponentCount
Definition at line 306 of file SkeletalMeshLODImporterData.h.
Referenced by FVertexAttribute().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Rendering/SkeletalMeshLODImporterData.h