Unreal Engine 5.6 C++ API: FRPCDoSAnalyticsVars Struct Reference
FRPCDoSAnalyticsVars Struct Reference
Container class for separating analytics variables and processing, from the main RPC DoS Detection code.
#include "RPCDoSDetectionAnalytics.h"
Public Member Functions
FRPCDoSAnalyticsVars ()
Default constructor.
void CommitAnalytics (FRPCDoSAnalyticsVars &AggregatedData)
bool operator== (const FRPCDoSAnalyticsVars &A) const
Data Fields
FString MaxAnalyticsSeverityCategory
The name of the maximum severity state confirmed for analytics that was reached.
int32 MaxAnalyticsSeverityIndex = 0
The index of the maximum severity state confirmed for analytics that was reached.
TArray< FMaxRPCDoSEscalation > MaxPlayerSeverity
Aggregation variables.
const int32 MaxRPCAnalytics
The maximum number of RPC tracking analytics entries.
FString MaxSeverityCategory
The name of the maximum severity state that was reached.
int32 MaxSeverityIndex = 0
The index of the maximum severity state that was reached.
FString PlayerIP
The IP of the player.
FString PlayerUID
The UID of the player.
TArray< TSharedPtr< FRPCAnalytics > > RPCTrackingAnalytics
Analytics for RPC's that are being tracked.
Detailed Description
Container class for separating analytics variables and processing, from the main RPC DoS Detection code.
Definition at line 151 of file RPCDoSDetectionAnalytics.h.
Constructor & Destructor Documentation
FRPCDoSAnalyticsVars()
FRPCDoSAnalyticsVars::FRPCDoSAnalyticsVars ()
Default constructor.
Referenced by CommitAnalytics(), and operator==().
Member Function Documentation
CommitAnalytics()
void FRPCDoSAnalyticsVars::CommitAnalytics (FRPCDoSAnalyticsVars & AggregatedData)
References FRPCDoSAnalyticsVars().
operator==()
bool FRPCDoSAnalyticsVars::operator== (const FRPCDoSAnalyticsVars & A) const
References FRPCDoSAnalyticsVars(), and A.
Field Documentation
MaxAnalyticsSeverityCategory
FString FRPCDoSAnalyticsVars::MaxAnalyticsSeverityCategory
The name of the maximum severity state confirmed for analytics that was reached.
Definition at line 180 of file RPCDoSDetectionAnalytics.h.
MaxAnalyticsSeverityIndex
int32 FRPCDoSAnalyticsVars::MaxAnalyticsSeverityIndex = 0
The index of the maximum severity state confirmed for analytics that was reached.
Definition at line 177 of file RPCDoSDetectionAnalytics.h.
MaxPlayerSeverity
TArray<FMaxRPCDoSEscalation> FRPCDoSAnalyticsVars::MaxPlayerSeverity
Aggregation variables.
(Not filled until final commit) The maximum RPC DoS severity state reached, for each player
Definition at line 193 of file RPCDoSDetectionAnalytics.h.
MaxRPCAnalytics
const int32 FRPCDoSAnalyticsVars::MaxRPCAnalytics
The maximum number of RPC tracking analytics entries.
Definition at line 187 of file RPCDoSDetectionAnalytics.h.
MaxSeverityCategory
FString FRPCDoSAnalyticsVars::MaxSeverityCategory
The name of the maximum severity state that was reached.
Definition at line 174 of file RPCDoSDetectionAnalytics.h.
MaxSeverityIndex
int32 FRPCDoSAnalyticsVars::MaxSeverityIndex = 0
The index of the maximum severity state that was reached.
Definition at line 171 of file RPCDoSDetectionAnalytics.h.
PlayerIP
FString FRPCDoSAnalyticsVars::PlayerIP
The IP of the player.
Definition at line 165 of file RPCDoSDetectionAnalytics.h.
PlayerUID
FString FRPCDoSAnalyticsVars::PlayerUID
The UID of the player.
Definition at line 168 of file RPCDoSDetectionAnalytics.h.
RPCTrackingAnalytics
TArray<TSharedPtr<FRPCAnalytics> > FRPCDoSAnalyticsVars::RPCTrackingAnalytics
Analytics for RPC's that are being tracked.
Definition at line 184 of file RPCDoSDetectionAnalytics.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Analytics/RPCDoSDetectionAnalytics.h