Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityPtr< T > Struct Template Reference
UE::MovieScene::TEntityPtr< T > Struct Template Reference
#include "MovieSceneEntityRange.h"
Public Member Functions
TEntityPtr (int32 InEntityIndex, const TEntityRange< T > *InOwner)
Construct this range from a range and index.
template<int ComponentTypeIndex>
auto & Get () const
Retrieve the component at the specified Index within this TEntityPtr's parameters.
template<int ComponentTypeIndex>
auto * GetOptional () const
Optionally retrieve the component at the specified ComponentTypeIndex within this TEntityPtr's parameters.
operator bool () const
Test whether this pointer is valid.
T & operator* ()
Dereference this pointer.
TEntityPtr & operator++ ()
Increment this pointer.
TEntityPtr & operator-- ()
Increment this pointer.
template<int ComponentTypeIndex, typename ValueType>
void Set (ValueType &&InValue) const
Set the value of the component at the specified index withinin this entity.
Private Attributes
int32 EntityIndex
This entity's index within the range.
const TEntityRange< T > * Owner
The range that this entity ptr resides within.
Friends
bool operator!= (const TEntityPtr &A, const TEntityPtr &B)
Compare this pointer with another for equality.
Detailed Description
template<typename T>
struct UE::MovieScene::TEntityPtr< T >
Definition at line 324 of file MovieSceneEntityRange.h.
Constructor & Destructor Documentation
TEntityPtr()
template<typename T> UE::MovieScene::TEntityPtr< T >::TEntityPtr (int32 InEntityIndex, const TEntityRange< T > * InOwner) inline
Construct this range from a range and index.
Definition at line 327 of file MovieSceneEntityRange.h.
References checkSlow, EntityIndex, and Owner.
Referenced by operator!=, operator++(), and operator--().
Member Function Documentation
Get()
template<typename T> template<int ComponentTypeIndex> auto & UE::MovieScene::TEntityPtr< T >::Get () const inline
Retrieve the component at the specified Index within this TEntityPtr's parameters.
Not to be used for Read/WriteOptional variants.
Note
The const qualifier of the component will match the access mode for the component (const for read, non-const for write)
Returns
A reference to the component value
Definition at line 387 of file MovieSceneEntityRange.h.
References EntityIndex, and Owner.
GetOptional()
template<typename T> template<int ComponentTypeIndex> auto * UE::MovieScene::TEntityPtr< T >::GetOptional () const inline
Optionally retrieve the component at the specified ComponentTypeIndex within this TEntityPtr's parameters.
Note
The const qualifier of the component will match the access mode for the component (const for read, non-const for write)
Returns
A pointer to the component value, or nullptr if this entity does not have such a component.
Definition at line 400 of file MovieSceneEntityRange.h.
References EntityIndex, and Owner.
operator bool()
template<typename T> UE::MovieScene::TEntityPtr< T >::operator bool () const inline explicit
Test whether this pointer is valid.
Definition at line 374 of file MovieSceneEntityRange.h.
References EntityIndex, and Owner.
operator*()
template<typename T> T & UE::MovieScene::TEntityPtr< T >::operator* () inline
Dereference this pointer.
Definition at line 356 of file MovieSceneEntityRange.h.
operator++()
template<typename T> TEntityPtr & UE::MovieScene::TEntityPtr< T >::operator++ () inline
Increment this pointer.
Definition at line 337 of file MovieSceneEntityRange.h.
References TEntityPtr(), and EntityIndex.
operator--()
template<typename T> TEntityPtr & UE::MovieScene::TEntityPtr< T >::operator-- () inline
Increment this pointer.
Definition at line 347 of file MovieSceneEntityRange.h.
References TEntityPtr(), and EntityIndex.
Set()
template<typename T> template<int ComponentTypeIndex, typename ValueType> void UE::MovieScene::TEntityPtr< T >::Set (ValueType && InValue) const inline
Set the value of the component at the specified index withinin this entity.
Parameters
InValue The value to assign to the component
Definition at line 412 of file MovieSceneEntityRange.h.
References EntityIndex, Forward(), and Owner.
Friends And Related Symbol Documentation
operator!=
template<typename T> bool operator!= (const TEntityPtr< T > & A, const TEntityPtr< T > & B) friend
Compare this pointer with another for equality.
Definition at line 365 of file MovieSceneEntityRange.h.
References TEntityPtr(), A, and B.
Field Documentation
EntityIndex
template<typename T> int32 UE::MovieScene::TEntityPtr< T >::EntityIndex private
This entity's index within the range.
Definition at line 424 of file MovieSceneEntityRange.h.
Referenced by TEntityPtr(), Get(), GetOptional(), operator bool(), operator++(), operator--(), and Set().
Owner
template<typename T> const TEntityRange<T>* UE::MovieScene::TEntityPtr< T >::Owner private
The range that this entity ptr resides within.
Definition at line 421 of file MovieSceneEntityRange.h.
Referenced by TEntityPtr(), Get(), GetOptional(), operator bool(), and Set().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityRange.h