Unreal Engine 5.6 C++ API: FPoseLinkMappingRecord Struct Reference
FPoseLinkMappingRecord Struct Reference
#include "AnimGraphNode_Base.h"
Public Member Functions
UAnimGraphNode_Base * GetLinkedNode () const
UAnimGraphNode_Base * GetLinkingNode () const
bool IsValid () const
ANIMGRAPH_API void PatchLinkIndex (uint8 *DestinationPtr, int32 LinkID, int32 SourceLinkID) const
Static Public Member Functions
static FPoseLinkMappingRecord MakeFromArrayEntry (UAnimGraphNode_Base *LinkingNode, UAnimGraphNode_Base *LinkedNode, FArrayProperty *ArrayProperty, int32 ArrayIndex)
static FPoseLinkMappingRecord MakeFromMember (UAnimGraphNode_Base *LinkingNode, UAnimGraphNode_Base *LinkedNode, FStructProperty *MemberProperty)
static FPoseLinkMappingRecord MakeInvalid ()
Protected Member Functions
FPoseLinkMappingRecord ()
Protected Attributes
FProperty * ChildProperty
int32 ChildPropertyIndex
UAnimGraphNode_Base * LinkedNode
UAnimGraphNode_Base * LinkingNode
Detailed Description
Definition at line 36 of file AnimGraphNode_Base.h.
Constructor & Destructor Documentation
FPoseLinkMappingRecord()
FPoseLinkMappingRecord::FPoseLinkMappingRecord () inline protected
Definition at line 88 of file AnimGraphNode_Base.h.
References ChildProperty, ChildPropertyIndex, INDEX_NONE, LinkedNode, and LinkingNode.
Referenced by MakeFromArrayEntry(), MakeFromMember(), and MakeInvalid().
Member Function Documentation
GetLinkedNode()
UAnimGraphNode_Base * FPoseLinkMappingRecord::GetLinkedNode () const inline
Definition at line 76 of file AnimGraphNode_Base.h.
References LinkedNode.
GetLinkingNode()
UAnimGraphNode_Base * FPoseLinkMappingRecord::GetLinkingNode () const inline
Definition at line 81 of file AnimGraphNode_Base.h.
References LinkingNode.
IsValid()
bool FPoseLinkMappingRecord::IsValid () const inline
Definition at line 71 of file AnimGraphNode_Base.h.
References LinkedNode.
MakeFromArrayEntry()
FPoseLinkMappingRecord FPoseLinkMappingRecord::MakeFromArrayEntry (UAnimGraphNode_Base * LinkingNode, UAnimGraphNode_Base * LinkedNode, FArrayProperty * ArrayProperty, int32 ArrayIndex) inline static
Definition at line 39 of file AnimGraphNode_Base.h.
References FPoseLinkMappingRecord(), ArrayProperty, CastFieldChecked(), checkSlow, LinkedNode, and LinkingNode.
MakeFromMember()
FPoseLinkMappingRecord FPoseLinkMappingRecord::MakeFromMember (UAnimGraphNode_Base * LinkingNode, UAnimGraphNode_Base * LinkedNode, FStructProperty * MemberProperty) inline static
Definition at line 52 of file AnimGraphNode_Base.h.
References FPoseLinkMappingRecord(), checkSlow, INDEX_NONE, LinkedNode, and LinkingNode.
MakeInvalid()
FPoseLinkMappingRecord FPoseLinkMappingRecord::MakeInvalid () inline static
Definition at line 65 of file AnimGraphNode_Base.h.
References FPoseLinkMappingRecord().
PatchLinkIndex()
ANIMGRAPH_API void FPoseLinkMappingRecord::PatchLinkIndex (uint8 * DestinationPtr, int32 LinkID, int32 SourceLinkID) const
Field Documentation
ChildProperty
FProperty* FPoseLinkMappingRecord::ChildProperty protected
Definition at line 104 of file AnimGraphNode_Base.h.
Referenced by FPoseLinkMappingRecord().
ChildPropertyIndex
int32 FPoseLinkMappingRecord::ChildPropertyIndex protected
Definition at line 107 of file AnimGraphNode_Base.h.
Referenced by FPoseLinkMappingRecord().
LinkedNode
UAnimGraphNode_Base* FPoseLinkMappingRecord::LinkedNode protected
Definition at line 98 of file AnimGraphNode_Base.h.
Referenced by FPoseLinkMappingRecord(), GetLinkedNode(), IsValid(), MakeFromArrayEntry(), and MakeFromMember().
LinkingNode
UAnimGraphNode_Base* FPoseLinkMappingRecord::LinkingNode protected
Definition at line 101 of file AnimGraphNode_Base.h.
Referenced by FPoseLinkMappingRecord(), GetLinkingNode(), MakeFromArrayEntry(), and MakeFromMember().
The documentation for this struct was generated from the following file:
Editor/AnimGraph/Public/AnimGraphNode_Base.h