Unreal Engine 5.6 C++ API: FPropertyBindingWidgetArgs Struct Reference
FPropertyBindingWidgetArgs Struct Reference
Setup arguments structure for a property binding widget.
#include "IPropertyAccessEditor.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FPropertyBindingWidgetArgs ()=default
FPropertyBindingWidgetArgs (const FPropertyBindingWidgetArgs &)=default
FPropertyBindingWidgetArgs (FPropertyBindingWidgetArgs &&)=default
FPropertyBindingWidgetArgs & operator= (const FPropertyBindingWidgetArgs &)=default
FPropertyBindingWidgetArgs & operator= (FPropertyBindingWidgetArgs &&)=default
UE_DEPRECATED (5.4, "Please use OnCanAcceptPropertyOrChildrenWithBindingChain instead.") FOnCanAcceptPropertyOrChildren OnCanAcceptPropertyOrChildren
UE_DEPRECATED (5.4, "Please use OnCanBindPropertyWithBindingChain instead.") FOnCanBindProperty OnCanBindProperty
UE_DEPRECATED (5.5, "Please use OnCanBindToContextStructWithIndex instead.") FOnCanBindToContextStruct OnCanBindToContextStruct
Data Fields
bool bAllowArrayElementBindings = false
Whether to allow array element bindings.
bool bAllowFunctionBindings = true
Whether to allow function bindings (to "this" class of the blueprint in question)
bool bAllowFunctionLibraryBindings = false
Whether to allow function library bindings in addition to the passed-in blueprint's class.
bool bAllowNewBindings = true
Whether to allow new bindings to be made from within the widget's UI.
bool bAllowOnlyThreadSafeFunctions = false
Whether to allow only functions marked thread safe.
bool bAllowPropertyBindings = true
Whether to allow property bindings.
bool bAllowStructFunctions = false
Whether to allow UScriptStruct functions as non-leaf nodes.
bool bAllowStructMemberBindings = true
Whether to allow struct member bindings.
bool bAllowUObjectFunctions = false
Whether to allow UObject functions as non-leaf nodes.
bool bGeneratePureBindings = true
Whether to generate pure bindings.
UFunction * BindableSignature = nullptr
An optional signature to use to match binding functions.
const FButtonStyle * BindButtonStyle = nullptr
Optional style override for bind button.
bool bUseLinkIconStyle = false
Whether to format the SPropertyBinding widget to use a link icon (versus the standard combo button)
TAttribute< FLinearColor > CurrentBindingColor
The current binding's color.
TAttribute< const FSlateBrush * > CurrentBindingImage
The current binding's image.
TAttribute< FText > CurrentBindingText
The current binding's text label.
TAttribute< FSlateColor > CurrentBindingTextColor
The current binding's text label color.
TAttribute< FText > CurrentBindingToolTipText
The current binding's tooltip text label.
uint8 MaxDepth = 10
The maximum level of depth to generate.
TSharedPtr< FExtender > MenuExtender
Menu extender.
FOnAddBinding OnAddBinding
Delegate called to add a binding.
FOnCanAcceptPropertyOrChildrenWithBindingChain OnCanAcceptPropertyOrChildrenWithBindingChain
Delegate used to check whether a property is considered for binding.
FOnCanBindFunction OnCanBindFunction
Delegate used to check whether a function can be bound to the property in question.
FOnCanBindPropertyWithBindingChain OnCanBindPropertyWithBindingChain
Delegate used to check whether a property can be bound to the property in question.
FOnCanBindToClass OnCanBindToClass
Delegate called to see if a class can be bound to.
FOnCanBindToContextStructWithIndex OnCanBindToContextStructWithIndex
Delegate called to see if a context struct can be directly bound to.
FOnCanBindToSubObjectClass OnCanBindToSubObjectClass
Delegate called to see if a subobject can be bound to.
FOnCanGotoBinding OnCanGotoBinding
Delegate used to see if we can open a binding (e.g.
FOnCanRemoveBinding OnCanRemoveBinding
Delegate called to see if we can remove remove a binding (ie.
FOnDrop OnDrop
Delegate called when a property is dropped on the property binding widget.
FOnGenerateBindingName OnGenerateBindingName
Delegate used to generate a new binding function's name.
FOnGotoBinding OnGotoBinding
Delegate used to open a bound generated function.
FOnHasAnyBindings OnHasAnyBindings
Delegate called to see if the property has any bindings.
FOnNewFunctionBindingCreated OnNewFunctionBindingCreated
Delegate called once a new function binding has been created.
FOnRemoveBinding OnRemoveBinding
Delegate called to remove a binding.
FOnResolveIndirection OnResolveIndirection
Delegate called to resolve true type of the instance.
PRAGMA_ENABLE_DEPRECATION_WARNINGS FProperty * Property = nullptr
An optional bindable property.
Detailed Description
Setup arguments structure for a property binding widget.
Definition at line 164 of file IPropertyAccessEditor.h.
Constructor & Destructor Documentation
FPropertyBindingWidgetArgs() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FPropertyBindingWidgetArgs::FPropertyBindingWidgetArgs () default
Referenced by FPropertyBindingWidgetArgs(), FPropertyBindingWidgetArgs(), operator=(), and operator=().
FPropertyBindingWidgetArgs() [2/3]
FPropertyBindingWidgetArgs::FPropertyBindingWidgetArgs (const FPropertyBindingWidgetArgs &) default
References FPropertyBindingWidgetArgs().
FPropertyBindingWidgetArgs() [3/3]
FPropertyBindingWidgetArgs::FPropertyBindingWidgetArgs (FPropertyBindingWidgetArgs &&) default
References FPropertyBindingWidgetArgs().
Member Function Documentation
operator=() [1/2]
FPropertyBindingWidgetArgs & FPropertyBindingWidgetArgs::operator= (const FPropertyBindingWidgetArgs &) default
References FPropertyBindingWidgetArgs().
operator=() [2/2]
FPropertyBindingWidgetArgs & FPropertyBindingWidgetArgs::operator= (FPropertyBindingWidgetArgs &&) default
References FPropertyBindingWidgetArgs(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
UE_DEPRECATED() [1/3]
FPropertyBindingWidgetArgs::UE_DEPRECATED (5. 4, "Please use OnCanAcceptPropertyOrChildrenWithBindingChain instead.")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FPropertyBindingWidgetArgs::UE_DEPRECATED (5. 4, "Please use OnCanBindPropertyWithBindingChain instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FPropertyBindingWidgetArgs::UE_DEPRECATED (5. 5, "Please use OnCanBindToContextStructWithIndex instead.")
References UE_DEPRECATED().
Field Documentation
bAllowArrayElementBindings
bool FPropertyBindingWidgetArgs::bAllowArrayElementBindings = false
Whether to allow array element bindings.
Definition at line 275 of file IPropertyAccessEditor.h.
bAllowFunctionBindings
bool FPropertyBindingWidgetArgs::bAllowFunctionBindings = true
Whether to allow function bindings (to "this" class of the blueprint in question)
Definition at line 266 of file IPropertyAccessEditor.h.
bAllowFunctionLibraryBindings
bool FPropertyBindingWidgetArgs::bAllowFunctionLibraryBindings = false
Whether to allow function library bindings in addition to the passed-in blueprint's class.
Definition at line 269 of file IPropertyAccessEditor.h.
bAllowNewBindings
bool FPropertyBindingWidgetArgs::bAllowNewBindings = true
Whether to allow new bindings to be made from within the widget's UI.
Definition at line 281 of file IPropertyAccessEditor.h.
bAllowOnlyThreadSafeFunctions
bool FPropertyBindingWidgetArgs::bAllowOnlyThreadSafeFunctions = false
Whether to allow only functions marked thread safe.
Definition at line 287 of file IPropertyAccessEditor.h.
bAllowPropertyBindings
bool FPropertyBindingWidgetArgs::bAllowPropertyBindings = true
Whether to allow property bindings.
Definition at line 272 of file IPropertyAccessEditor.h.
bAllowStructFunctions
bool FPropertyBindingWidgetArgs::bAllowStructFunctions = false
Whether to allow UScriptStruct functions as non-leaf nodes.
Definition at line 290 of file IPropertyAccessEditor.h.
bAllowStructMemberBindings
bool FPropertyBindingWidgetArgs::bAllowStructMemberBindings = true
Whether to allow struct member bindings.
Definition at line 278 of file IPropertyAccessEditor.h.
bAllowUObjectFunctions
bool FPropertyBindingWidgetArgs::bAllowUObjectFunctions = false
Whether to allow UObject functions as non-leaf nodes.
Definition at line 284 of file IPropertyAccessEditor.h.
bGeneratePureBindings
bool FPropertyBindingWidgetArgs::bGeneratePureBindings = true
Whether to generate pure bindings.
Definition at line 263 of file IPropertyAccessEditor.h.
BindableSignature
UFunction* FPropertyBindingWidgetArgs::BindableSignature = nullptr
An optional signature to use to match binding functions.
Definition at line 179 of file IPropertyAccessEditor.h.
BindButtonStyle
const FButtonStyle* FPropertyBindingWidgetArgs::BindButtonStyle = nullptr
Optional style override for bind button.
Definition at line 257 of file IPropertyAccessEditor.h.
bUseLinkIconStyle
bool FPropertyBindingWidgetArgs::bUseLinkIconStyle = false
Whether to format the SPropertyBinding widget to use a link icon (versus the standard combo button)
Definition at line 293 of file IPropertyAccessEditor.h.
CurrentBindingColor
TAttribute<FLinearColor> FPropertyBindingWidgetArgs::CurrentBindingColor
The current binding's color.
Definition at line 251 of file IPropertyAccessEditor.h.
CurrentBindingImage
TAttribute<const FSlateBrush*> FPropertyBindingWidgetArgs::CurrentBindingImage
The current binding's image.
Definition at line 248 of file IPropertyAccessEditor.h.
CurrentBindingText
TAttribute<FText> FPropertyBindingWidgetArgs::CurrentBindingText
The current binding's text label.
Definition at line 239 of file IPropertyAccessEditor.h.
CurrentBindingTextColor
TAttribute<FSlateColor> FPropertyBindingWidgetArgs::CurrentBindingTextColor
The current binding's text label color.
Definition at line 242 of file IPropertyAccessEditor.h.
CurrentBindingToolTipText
TAttribute<FText> FPropertyBindingWidgetArgs::CurrentBindingToolTipText
The current binding's tooltip text label.
Definition at line 245 of file IPropertyAccessEditor.h.
MaxDepth
uint8 FPropertyBindingWidgetArgs::MaxDepth = 10
The maximum level of depth to generate.
Definition at line 260 of file IPropertyAccessEditor.h.
MenuExtender
TSharedPtr<FExtender> FPropertyBindingWidgetArgs::MenuExtender
Menu extender.
Definition at line 254 of file IPropertyAccessEditor.h.
OnAddBinding
FOnAddBinding FPropertyBindingWidgetArgs::OnAddBinding
Delegate called to add a binding.
Definition at line 218 of file IPropertyAccessEditor.h.
OnCanAcceptPropertyOrChildrenWithBindingChain
FOnCanAcceptPropertyOrChildrenWithBindingChain FPropertyBindingWidgetArgs::OnCanAcceptPropertyOrChildrenWithBindingChain
Delegate used to check whether a property is considered for binding.
Returning false will discard the property and all child properties.
Definition at line 191 of file IPropertyAccessEditor.h.
OnCanBindFunction
FOnCanBindFunction FPropertyBindingWidgetArgs::OnCanBindFunction
Delegate used to check whether a function can be bound to the property in question.
Definition at line 203 of file IPropertyAccessEditor.h.
OnCanBindPropertyWithBindingChain
FOnCanBindPropertyWithBindingChain FPropertyBindingWidgetArgs::OnCanBindPropertyWithBindingChain
Delegate used to check whether a property can be bound to the property in question.
Definition at line 197 of file IPropertyAccessEditor.h.
OnCanBindToClass
FOnCanBindToClass FPropertyBindingWidgetArgs::OnCanBindToClass
Delegate called to see if a class can be bound to.
Definition at line 206 of file IPropertyAccessEditor.h.
OnCanBindToContextStructWithIndex
FOnCanBindToContextStructWithIndex FPropertyBindingWidgetArgs::OnCanBindToContextStructWithIndex
Delegate called to see if a context struct can be directly bound to.
Definition at line 212 of file IPropertyAccessEditor.h.
OnCanBindToSubObjectClass
FOnCanBindToSubObjectClass FPropertyBindingWidgetArgs::OnCanBindToSubObjectClass
Delegate called to see if a subobject can be bound to.
Definition at line 215 of file IPropertyAccessEditor.h.
OnCanGotoBinding
FOnCanGotoBinding FPropertyBindingWidgetArgs::OnCanGotoBinding
Delegate used to see if we can open a binding (e.g.
a function)
Definition at line 188 of file IPropertyAccessEditor.h.
OnCanRemoveBinding
FOnCanRemoveBinding FPropertyBindingWidgetArgs::OnCanRemoveBinding
Delegate called to see if we can remove remove a binding (ie.
if it exists)
Definition at line 224 of file IPropertyAccessEditor.h.
OnDrop
FOnDrop FPropertyBindingWidgetArgs::OnDrop
Delegate called when a property is dropped on the property binding widget.
Definition at line 236 of file IPropertyAccessEditor.h.
OnGenerateBindingName
FOnGenerateBindingName FPropertyBindingWidgetArgs::OnGenerateBindingName
Delegate used to generate a new binding function's name.
Definition at line 182 of file IPropertyAccessEditor.h.
OnGotoBinding
FOnGotoBinding FPropertyBindingWidgetArgs::OnGotoBinding
Delegate used to open a bound generated function.
Definition at line 185 of file IPropertyAccessEditor.h.
OnHasAnyBindings
FOnHasAnyBindings FPropertyBindingWidgetArgs::OnHasAnyBindings
Delegate called to see if the property has any bindings.
Definition at line 227 of file IPropertyAccessEditor.h.
OnNewFunctionBindingCreated
FOnNewFunctionBindingCreated FPropertyBindingWidgetArgs::OnNewFunctionBindingCreated
Delegate called once a new function binding has been created.
Definition at line 230 of file IPropertyAccessEditor.h.
OnRemoveBinding
FOnRemoveBinding FPropertyBindingWidgetArgs::OnRemoveBinding
Delegate called to remove a binding.
Definition at line 221 of file IPropertyAccessEditor.h.
OnResolveIndirection
FOnResolveIndirection FPropertyBindingWidgetArgs::OnResolveIndirection
Delegate called to resolve true type of the instance.
Definition at line 233 of file IPropertyAccessEditor.h.
Property
PRAGMA_ENABLE_DEPRECATION_WARNINGS FProperty* FPropertyBindingWidgetArgs::Property = nullptr
An optional bindable property.
Definition at line 176 of file IPropertyAccessEditor.h.
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/IPropertyAccessEditor.h