Unreal Engine 5.6 C++ API: FSlateCachedElementsHandle Struct Reference
FSlateCachedElementsHandle Struct Reference
Handle used to uniquely identify a cached element list with some widget Used when a widget gets invalidated / additional elements added So we can modify that widget's existing cached element list.
#include "DrawElements.h"
Public Member Functions
FSlateCachedElementsHandle ()
void ClearCachedElements ()
bool HasCachedElements () const
bool IsOwnedByWidget (const SWidget *Widget) const
bool IsValid () const
bool operator!= (FSlateCachedElementsHandle &Other) const
void RemoveFromCache ()
Static Public Attributes
static FSlateCachedElementsHandle Invalid
Private Member Functions
FSlateCachedElementsHandle (TSharedRef< FSlateCachedElementList > &DataPtr)
Private Attributes
TWeakPtr< FSlateCachedElementList > Ptr
Friends
struct FSlateCachedElementData
Detailed Description
Handle used to uniquely identify a cached element list with some widget Used when a widget gets invalidated / additional elements added So we can modify that widget's existing cached element list.
Definition at line 105 of file DrawElements.h.
Constructor & Destructor Documentation
FSlateCachedElementsHandle() [1/2]
FSlateCachedElementsHandle::FSlateCachedElementsHandle () inline
Definition at line 120 of file DrawElements.h.
Referenced by operator!=().
FSlateCachedElementsHandle() [2/2]
FSlateCachedElementsHandle::FSlateCachedElementsHandle (TSharedRef< FSlateCachedElementList > & DataPtr) inline private
Definition at line 122 of file DrawElements.h.
References Ptr.
Member Function Documentation
ClearCachedElements()
void FSlateCachedElementsHandle::ClearCachedElements ()
HasCachedElements()
bool FSlateCachedElementsHandle::HasCachedElements () const
IsOwnedByWidget()
bool FSlateCachedElementsHandle::IsOwnedByWidget (const SWidget * Widget) const
IsValid()
bool FSlateCachedElementsHandle::IsValid () const inline
Definition at line 115 of file DrawElements.h.
References Ptr.
Referenced by FSlateWindowElementList::AddCachedElement().
operator!=()
bool FSlateCachedElementsHandle::operator!= (FSlateCachedElementsHandle & Other) const inline
Definition at line 118 of file DrawElements.h.
References FSlateCachedElementsHandle(), Other, and Ptr.
RemoveFromCache()
void FSlateCachedElementsHandle::RemoveFromCache ()
Friends And Related Symbol Documentation
FSlateCachedElementData
friend struct FSlateCachedElementData friend
Definition at line 107 of file DrawElements.h.
References FSlateCachedElementData.
Referenced by FSlateCachedElementData.
Field Documentation
Invalid
FSlateCachedElementsHandle FSlateCachedElementsHandle::Invalid static
Definition at line 109 of file DrawElements.h.
Ptr
TWeakPtr<FSlateCachedElementList> FSlateCachedElementsHandle::Ptr private
Definition at line 128 of file DrawElements.h.
Referenced by FSlateCachedElementsHandle(), FSlateCachedElementData::AddCachedElement(), IsValid(), and operator!=().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Rendering/DrawElements.h