Unreal Engine 5.6 C++ API: FMinimalName Struct Reference
FMinimalName Struct Reference
The minimum amount of data required to reconstruct a name This is smaller than FName when WITH_CASE_PRESERVING_NAME is set, but you lose the case-preserving behavior.
#include "NameTypes.h"
Public Member Functions
FMinimalName ()
FORCEINLINE FMinimalName (const FName &Name)
FMinimalName (EName N)
FORCEINLINE bool IsNone () const
FORCEINLINE bool operator< (FMinimalName Rhs) const
Data Fields
friend FName
Private Attributes
FNameEntryId Index
Index into the Names array (used to find String portion of the string/number pair)
int32 Number = 0
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Friends
FORCEINLINE uint32 GetTypeHash (FMinimalName Name)
FORCEINLINE bool operator!= (FMinimalName Lhs, FMinimalName Rhs)
FORCEINLINE bool operator== (FMinimalName Lhs, FMinimalName Rhs)
Detailed Description
The minimum amount of data required to reconstruct a name This is smaller than FName when WITH_CASE_PRESERVING_NAME is set, but you lose the case-preserving behavior.
The size of this type is not portable across different platforms and configurations, as with FName itself.
Definition at line 387 of file NameTypes.h.
Constructor & Destructor Documentation
FMinimalName() [1/3]
FMinimalName::FMinimalName () inline
Definition at line 391 of file NameTypes.h.
Referenced by GetTypeHash, operator!=, operator<(), and operator==.
FMinimalName() [2/3]
FMinimalName::FMinimalName (EName N) inline
Definition at line 393 of file NameTypes.h.
References Index.
FMinimalName() [3/3]
FORCEINLINE FMinimalName::FMinimalName (const FName & Name) explicit
Definition at line 1519 of file NameTypes.h.
References FName, FORCEINLINE, Index, Name, and Number.
Member Function Documentation
IsNone()
FORCEINLINE bool FMinimalName::IsNone () const
Definition at line 1543 of file NameTypes.h.
References FORCEINLINE, Index, NAME_NO_NUMBER_INTERNAL, and Number.
operator<()
FORCEINLINE bool FMinimalName::operator< (FMinimalName Rhs) const
Definition at line 1548 of file NameTypes.h.
References FMinimalName(), FORCEINLINE, Index, and Number.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (FMinimalName Name) friend
Definition at line 424 of file NameTypes.h.
References FMinimalName(), FORCEINLINE, GetTypeHash, and Name.
Referenced by GetTypeHash.
operator!=
FORCEINLINE bool operator!= (FMinimalName Lhs, FMinimalName Rhs) friend
Definition at line 429 of file NameTypes.h.
References FMinimalName(), FORCEINLINE, and operator==.
operator==
FORCEINLINE bool operator== (FMinimalName Lhs, FMinimalName Rhs) friend
Definition at line 420 of file NameTypes.h.
References FMinimalName(), FORCEINLINE, Index, and Number.
Referenced by operator!=.
Field Documentation
FName
friend FMinimalName::FName
Definition at line 389 of file NameTypes.h.
Referenced by FMinimalName().
Index
FNameEntryId FMinimalName::Index private
Index into the Names array (used to find String portion of the string/number pair)
Definition at line 404 of file NameTypes.h.
Referenced by FMinimalName(), FMinimalName(), IsNone(), operator<(), and operator==.
Number
int32 FMinimalName::Number = 0 private
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Definition at line 407 of file NameTypes.h.
Referenced by FMinimalName(), IsNone(), operator<(), and operator==.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/UObject/NameTypes.h