Unreal Engine 5.6 C++ API: UE::Geometry::TSegment3< T > Struct Template Reference
UE::Geometry::TSegment3< T > Struct Template Reference
#include "SegmentTypes.h"
Public Member Functions
TSegment3 ()=default
TSegment3 (const TVector< T > &CenterIn, const TVector< T > &DirectionIn, T ExtentIn)
Construct a segment from a Center Point, normalized Direction, and scalar Extent.
TSegment3 (const TVector< T > &Point0, const TVector< T > &Point1)
Construct a Segment from two Points.
T ConvertToUnitRange (T DistanceParameter) const
T DistanceSquared (const TVector< T > &Point) const
T DistanceSquared (const TVector< T > &Point, T &DistParameterOut) const
TVector< T > EndPoint () const
TAxisAlignedBox3< T > GetBounds () const
TAxisAlignedBox3< T > GetBounds (T SegmentRadius) const
TVector< T > GetPointFromIndex (int i) const
T Length () const
TVector< T > NearestPoint (const TVector< T > &QueryPoint) const
TVector< T > PointAt (T DistanceParameter) const
TVector< T > PointBetween (T UnitParameter) const
T Project (const TVector< T > &QueryPoint) const
T ProjectUnitRange (const TVector< T > &QueryPoint) const
void Reverse ()
Reverse the segment.
void SetEndPoint (const TVector< T > &Point)
Update the Segment with a new end point.
void SetStartPoint (const TVector< T > &Point)
Update the Segment with a new start point.
TVector< T > StartPoint () const
Data Fields
TVector< T > Center = TVector<T>::Zero()
Center point of segment.
TVector< T > Direction = TVector<T>::UnitX()
normalized Direction vector of segment
T Extent = (T)0
Extent of segment, which is half the total length.
Protected Member Functions
void update_from_endpoints (const TVector< T > &p0, const TVector< T > &p1)
Detailed Description
template<typename T>
struct UE::Geometry::TSegment3< T >
Definition at line 446 of file SegmentTypes.h.
Constructor & Destructor Documentation
TSegment3() [1/3]
template<typename T> UE::Geometry::TSegment3< T >::TSegment3 () default
TSegment3() [2/3]
template<typename T> UE::Geometry::TSegment3< T >::TSegment3 (const TVector< T > & Point0, const TVector< T > & Point1) inline
Construct a Segment from two Points.
Definition at line 461 of file SegmentTypes.h.
TSegment3() [3/3]
template<typename T> UE::Geometry::TSegment3< T >::TSegment3 (const TVector< T > & CenterIn, const TVector< T > & DirectionIn, T ExtentIn) inline
Construct a segment from a Center Point, normalized Direction, and scalar Extent.
Definition at line 472 of file SegmentTypes.h.
Member Function Documentation
ConvertToUnitRange()
template<typename T> T UE::Geometry::TSegment3< T >::ConvertToUnitRange (T DistanceParameter) const inline
Parameters
DistanceParameter distance on the segment from the segment Origin in range [-Extent, Extent]
Returns
unit value in range [0,1]
Definition at line 548 of file SegmentTypes.h.
DistanceSquared() [1/2]
template<typename T> T UE::Geometry::TSegment3< T >::DistanceSquared (const TVector< T > & Point) const inline
Returns
minimum squared distance from Point to segment
Definition at line 556 of file SegmentTypes.h.
Referenced by UE::Geometry::TSegment3< float >::DistanceSquared().
DistanceSquared() [2/2]
template<typename T> T UE::Geometry::TSegment3< T >::DistanceSquared (const TVector< T > & Point, T & DistParameterOut) const inline
Parameters
Point query point
DistParameterOut calculated distance parameter in range [-Extent,Extent]
Returns
minimum squared distance from Point to Segment
Definition at line 569 of file SegmentTypes.h.
EndPoint()
template<typename T> TVector< T > UE::Geometry::TSegment3< T >::EndPoint () const inline
Returns
end point of segment
Definition at line 509 of file SegmentTypes.h.
Referenced by UE::Geometry::TSegment3< float >::DistanceSquared(), UE::Geometry::TSegment3< float >::NearestPoint(), UE::Geometry::TSegment3< float >::Reverse(), and UE::Geometry::TSegment3< float >::SetStartPoint().
GetBounds() [1/2]
template<typename T> TAxisAlignedBox3< T > UE::Geometry::TSegment3< T >::GetBounds () const inline
Returns
axis-aligned bounding box of line segment
Definition at line 627 of file SegmentTypes.h.
Referenced by UE::Geometry::TSegment3< float >::GetBounds().
GetBounds() [2/2]
template<typename T> TAxisAlignedBox3< T > UE::Geometry::TSegment3< T >::GetBounds (T SegmentRadius) const inline
Returns
axis-aligned bounding box of line segment thickened to given SegmentRadius
Definition at line 644 of file SegmentTypes.h.
GetPointFromIndex()
template<typename T> TVector< T > UE::Geometry::TSegment3< T >::GetPointFromIndex (int i) const inline
Returns
first (i == 0) or second (i == 1) endpoint of the Segment
Definition at line 522 of file SegmentTypes.h.
Length()
template<typename T> T UE::Geometry::TSegment3< T >::Length () const inline
Returns
the Length of the segment
Definition at line 516 of file SegmentTypes.h.
NearestPoint()
template<typename T> TVector< T > UE::Geometry::TSegment3< T >::NearestPoint (const TVector< T > & QueryPoint) const inline
Returns
nearest point on segment to QueryPoint
Definition at line 590 of file SegmentTypes.h.
PointAt()
template<typename T> TVector< T > UE::Geometry::TSegment3< T >::PointAt (T DistanceParameter) const inline
Returns
point on segment at given (signed) Distance from the segment Origin
Definition at line 530 of file SegmentTypes.h.
PointBetween()
template<typename T> TVector< T > UE::Geometry::TSegment3< T >::PointBetween (T UnitParameter) const inline
Parameters
UnitParameter value in range [0,1]
Returns
point on segment at that linearly interpolates between start and end based on Unit Parameter
Definition at line 539 of file SegmentTypes.h.
Project()
template<typename T> T UE::Geometry::TSegment3< T >::Project (const TVector< T > & QueryPoint) const inline
Returns
scalar projection of QueryPoint onto line of Segment (not clamped to Extents)
Definition at line 608 of file SegmentTypes.h.
ProjectUnitRange()
template<typename T> T UE::Geometry::TSegment3< T >::ProjectUnitRange (const TVector< T > & QueryPoint) const inline
Returns
scalar projection of QueryPoint onto line of Segment, mapped to [0,1] range along segment
Definition at line 617 of file SegmentTypes.h.
Reverse()
template<typename T> void UE::Geometry::TSegment3< T >::Reverse () inline
Reverse the segment.
Definition at line 494 of file SegmentTypes.h.
SetEndPoint()
template<typename T> void UE::Geometry::TSegment3< T >::SetEndPoint (const TVector< T > & Point) inline
Update the Segment with a new end point.
Definition at line 488 of file SegmentTypes.h.
SetStartPoint()
template<typename T> void UE::Geometry::TSegment3< T >::SetStartPoint (const TVector< T > & Point) inline
Update the Segment with a new start point.
Definition at line 482 of file SegmentTypes.h.
StartPoint()
template<typename T> TVector< T > UE::Geometry::TSegment3< T >::StartPoint () const inline
Returns
start point of segment
Definition at line 503 of file SegmentTypes.h.
Referenced by UE::Geometry::TSegment3< float >::DistanceSquared(), UE::Geometry::TSegment3< float >::NearestPoint(), UE::Geometry::TSegment3< float >::Reverse(), and UE::Geometry::TSegment3< float >::SetEndPoint().
update_from_endpoints()
template<typename T> void UE::Geometry::TSegment3< T >::update_from_endpoints (const TVector< T > & p0, const TVector< T > & p1) inline protected
Definition at line 654 of file SegmentTypes.h.
Referenced by UE::Geometry::TSegment3< float >::Reverse(), UE::Geometry::TSegment3< float >::SetEndPoint(), and UE::Geometry::TSegment3< float >::SetStartPoint().
Field Documentation
Center
template<typename T> TVector<T> UE::Geometry::TSegment3< T >::Center = TVector<T>::Zero()
Center point of segment.
Definition at line 450 of file SegmentTypes.h.
Referenced by UE::Geometry::GetShape().
Direction
template<typename T> TVector<T> UE::Geometry::TSegment3< T >::Direction = TVector<T>::UnitX()
normalized Direction vector of segment
Definition at line 452 of file SegmentTypes.h.
Referenced by UE::Geometry::GetShape().
Extent
template<typename T> T UE::Geometry::TSegment3< T >::Extent = (T)0
Extent of segment, which is half the total length.
Definition at line 454 of file SegmentTypes.h.
Referenced by UE::Geometry::TDistLine3Triangle3< float >::ComputeResult(), UE::Geometry::TDistTriangle3Triangle3< float >::ComputeResult(), and UE::Geometry::GetShape().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/SegmentTypes.h