Unreal Engine 5.6 C++ API: UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... > Struct Template Reference
UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... > Struct Template Reference
#include "FormatStringSan.h"
Static Public Member Functions
static constexpr FResult Check (bool bInsideFormatSpec, int CurArgPos, const CharType *Fmt)
static constexpr FResult HandleDynamicLengthSpecifier (int CurArgPos, const CharType *Fmt)
Detailed Description
template<typename CharType, typename Arg, typename... Args>
struct UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >
Definition at line 116 of file FormatStringSan.h.
Member Function Documentation
Check()
template<typename CharType, typename Arg, typename... Args> constexpr FResult UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::Check (bool bInsideFormatSpec, int CurArgPos, const CharType * Fmt) inline static constexpr
Definition at line 130 of file FormatStringSan.h.
References UE::Core::Private::FormatStringSan::CapitalSNeedsDereferencedNarrowString, UE::Core::Private::FormatStringSan::CapitalSNeedsDereferencedWideString, UE::Core::Private::FormatStringSan::CapitalSNeedsNarrowCharPtrArg, UE::Core::Private::FormatStringSan::CapitalSNeedsNarrowCharPtrArgButGotWide, UE::Core::Private::FormatStringSan::CapitalSNeedsPtrButGotChar, UE::Core::Private::FormatStringSan::CapitalSNeedsWideCharPtrArg, UE::Core::Private::FormatStringSan::CapitalSNeedsWideCharPtrArgButGotNarrow, UE::Core::Private::FormatStringSan::CharIsDigit(), UE::Core::Private::FormatStringSan::CharIsIntegerFormatSpecifier(), UE::Core::Private::FormatStringSan::CNeedsCharArgOnNarrowString, UE::Core::Private::FormatStringSan::CNeedsCharArgOnWideString, UE::Core::Private::FormatStringSan::DNeedsIntegerArg, UE::Core::Private::FormatStringSan::FNeedsFloatOrDoubleArg, HandleDynamicLengthSpecifier(), UE::Core::Private::FormatStringSan::HHNeedsIntegerArg, UE::Core::Private::FormatStringSan::HHNeedsIntegerSpec, UE::Core::Private::FormatStringSan::HNeedsIntegerArg, UE::Core::Private::FormatStringSan::HSNeedsDereferencedNarrowString, UE::Core::Private::FormatStringSan::HSNeedsNarrowCharPtrArg, UE::Core::Private::FormatStringSan::HSNeedsNarrowCharPtrArgButGotWideOnNarrowString, UE::Core::Private::FormatStringSan::HSNeedsNarrowCharPtrArgButGotWideOnWideString, UE::Core::Private::FormatStringSan::HSNeedsPtrButGotChar, UE::Core::Private::FormatStringSan::I64BadSpec, UE::Core::Private::FormatStringSan::I64NeedsIntegerArg, UE::Core::Private::FormatStringSan::IncompleteFormatSpecifierOrUnescapedPercent, UE::Core::Private::FormatStringSan::InvalidFormatSpec, UE::Core::Private::FormatStringSan::LLNeedsIntegerArg, UE::Core::Private::FormatStringSan::LLNeedsIntegerSpec, UE::Core::Private::FormatStringSan::LNeedsIntegerArg, UE::Core::Private::FormatStringSan::LSNeedsDereferencedWideString, UE::Core::Private::FormatStringSan::LSNeedsPtrButGotChar, UE::Core::Private::FormatStringSan::LSNeedsWideCharPtrArg, UE::Core::Private::FormatStringSan::LSNeedsWideCharPtrArgButGotNarrowOnNarrowString, UE::Core::Private::FormatStringSan::LSNeedsWideCharPtrArgButGotNarrowOnWideString, UE::Core::Private::FormatStringSan::NotEnoughSpecifiers, UE::Core::Private::FormatStringSan::Ok, UE::Core::Private::FormatStringSan::PNeedsPointerArg, UE::Core::Private::FormatStringSan::SkipInteger(), UE::Core::Private::FormatStringSan::SNeedsDereferencedNarrowString, UE::Core::Private::FormatStringSan::SNeedsDereferencedWideString, UE::Core::Private::FormatStringSan::SNeedsNarrowCharPtrArg, UE::Core::Private::FormatStringSan::SNeedsNarrowCharPtrArgButGotWide, UE::Core::Private::FormatStringSan::SNeedsPtrButGotChar, UE::Core::Private::FormatStringSan::SNeedsWideCharPtrArg, UE::Core::Private::FormatStringSan::SNeedsWideCharPtrArgButGotNarrow, TIsCharType_V, UE::Core::Private::FormatStringSan::TIsFloatOrDouble_V, UE::Core::Private::FormatStringSan::TIsIntegralEnum_V, TIsTString_V, UE::Core::Private::FormatStringSan::ZNeedsIntegerArg, and UE::Core::Private::FormatStringSan::ZNeedsIntegerSpec.
HandleDynamicLengthSpecifier()
template<typename CharType, typename Arg, typename... Args> constexpr FResult UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::HandleDynamicLengthSpecifier (int CurArgPos, const CharType * Fmt) inline static constexpr
Definition at line 118 of file FormatStringSan.h.
References UE::Core::Private::FormatStringSan::DynamicLengthSpecNeedsIntegerArg, and UE::Core::Private::FormatStringSan::TIsIntegralEnum_V.
Referenced by Check().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/String/FormatStringSan.h