Unreal Engine 5.6 C++ API: TMovieSceneChannelData< const ValueType > Struct Template Reference
TMovieSceneChannelData< const ValueType > Struct Template Reference
Specialization of TMovieSceneChannelData for const value types (limited read-only access to data)
#include "MovieSceneChannelData.h"
Public Types
typedef TCallTraits< ValueType >::ParamType ParamType
Public Member Functions
TMovieSceneChannelData (const TArray< FFrameNumber > *InTimes, const TArray< ValueType > *InValues)
Constructor that takes a non-owning pointer to an array of times and values, and a key handle map.
int32 FindKey (FFrameNumber InTime, FFrameNumber InTolerance=0) const
Attempt to find a key at a given time and tolerance.
void FindKeys (FFrameNumber InTime, int32 MaxNum, int32 &OutMinIndex, int32 &OutMaxIndex, FFrameNumber InTolerance) const
Find the range of keys that fall around InTime +/- InTolerance up to a maximum.
FORCEINLINE TArrayView< const FFrameNumber > GetTimes () const
Read-only access to this channel's key times.
TRange< FFrameNumber > GetTotalRange () const
Compute the total time range of the channel data.
FORCEINLINE TArrayView< const ValueType > GetValues () const
Read-only access to this channel's values.
UE_DEPRECATED (5.5, "Constructor that takes an optional FMovieSceneChannel is now deprecated. FMovieSceneChannel is now required.") TMovieSceneChannelData(TArray< FFrameNumber > *InTimes
Constructor that takes a non-owning pointer to an array of times and values, and a key handle map.
Public Member Functions inherited from FMovieSceneChannelData
MOVIESCENE_API int32 FindKey (FFrameNumber InTime, FFrameNumber InTolerance=0)
Attempt to find a key at a given time and tolerance.
MOVIESCENE_API void FindKeys (FFrameNumber InTime, int32 MaxNum, int32 &OutMinIndex, int32 &OutMaxIndex, int32 InTolerance)
Find the range of keys that fall around InTime +/- InTolerance up to a maximum.
MOVIESCENE_API FKeyHandle GetHandle (int32 Index)
Retrieve a key handle for the specified key time index.
MOVIESCENE_API int32 GetIndex (FKeyHandle Handle)
Attempt to retrieve the index of key from its handle.
MOVIESCENE_API void GetKeys (const TRange< FFrameNumber > &WithinRange, TArray< FFrameNumber > *OutKeyTimes, TArray< FKeyHandle > *OutKeyHandles)
Get all the keys in the given range.
MOVIESCENE_API void GetKeyTimes (TArrayView< const FKeyHandle > InHandles, TArrayView< FFrameNumber > OutKeyTimes)
Get key times for a number of keys in the channel data.
FORCEINLINE TArrayView< FFrameNumber > GetTimes ()
Mutable access to this channel's key times.
FORCEINLINE TArrayView< const FFrameNumber > GetTimes () const
Read-only access to this channel's key times.
MOVIESCENE_API TRange< FFrameNumber > GetTotalRange () const
Compute the total time range of the channel data.
MOVIESCENE_API void Offset (FFrameNumber DeltaTime)
Offset the channel data by a given delta time.
UE_DEPRECATED (5.6, "Please use RemapTimes") MOVIESCENE_API void ChangeFrameResolution(FFrameRate SourceRate
Convert the frame resolution of a movie scene channel by moving the key times to the equivalent frame time.
Data Fields
TArray< ValueType > FKeyHandleLookupTable FMovieSceneChannel * InChannel
TArray< ValueType > FKeyHandleLookupTable * InKeyHandles
TArray< ValueType > * InValues
Data Fields inherited from FMovieSceneChannelData
FFrameRate DestinationRate
Private Attributes
const TArray< FFrameNumber > * Times
Pointer to an external array of sorted times.
const TArray< ValueType > * Values
Pointer to an external array of values, to be kept in sync with Times.
Additional Inherited Members
Protected Member Functions inherited from FMovieSceneChannelData
MOVIESCENE_API FMovieSceneChannelData (FMovieSceneChannel *InChannel, TArray< FFrameNumber > *InTimes, FKeyHandleLookupTable *InKeyHandles)
Constructor that takes a non-owning pointer to an array of times and a key handle map.
MOVIESCENE_API int32 AddKeyInternal (FFrameNumber InTime)
Add a new key at the specified time.
MOVIESCENE_API int32 MoveKeyInternal (int32 KeyIndex, FFrameNumber InNewTime)
Move the key at index KeyIndex to a new time.
UE_DEPRECATED (5.5, "Constructor that takes an optional FMovieSceneChannel is now deprecated. FMovieSceneChannel is now required.") MOVIESCENE_API FMovieSceneChannelData(TArray< FFrameNumber > *InTimes
Protected Attributes inherited from FMovieSceneChannelData
FKeyHandleLookupTable FMovieSceneChannel * InChannel = nullptr)
FKeyHandleLookupTable * InKeyHandles
FKeyHandleLookupTable * KeyHandles
Pointer to an external key handle map.
FMovieSceneChannel * OwningChannel
Optional Pointer to the owning FMovieSceneChannel, should be set if the add,move, and delete callbacks are needed.
TArray< FFrameNumber > * Times
Pointer to an external array of sorted times.
Detailed Description
template<typename ValueType>
struct TMovieSceneChannelData< const ValueType >
Specialization of TMovieSceneChannelData for const value types (limited read-only access to data)
Definition at line 704 of file MovieSceneChannelData.h.
Member Typedef Documentation
ParamType
template<typename ValueType> typedef TCallTraits<ValueType>::ParamType TMovieSceneChannelData< const ValueType >::ParamType
Definition at line 706 of file MovieSceneChannelData.h.
Constructor & Destructor Documentation
TMovieSceneChannelData()
template<typename ValueType> TMovieSceneChannelData< const ValueType >::TMovieSceneChannelData (const TArray< FFrameNumber > * InTimes, const TArray< ValueType > * InValues) inline
Constructor that takes a non-owning pointer to an array of times and values, and a key handle map.
Parameters
InTimes A pointer to an array of times that should be operated on by this class. Externally owned.
InValues A pointer to an array of values that should be operated on by this class. Externally owned.
InKeyHandles A key handle map used for persistent, order independent identification of keys
Definition at line 716 of file MovieSceneChannelData.h.
References check, InValues, Times, and Values.
Member Function Documentation
FindKey()
template<typename ValueType> int32 TMovieSceneChannelData< const ValueType >::FindKey (FFrameNumber InTime, FFrameNumber InTolerance = 0) const inline
Attempt to find a key at a given time and tolerance.
Parameters
InTime The time at which to search
InTolerance A tolerance of frame numbers to allow either side of the specified time
Returns
The index of the key closest to InTime and within InTolerance, INDEX_NONE or Times.Num()
Definition at line 745 of file MovieSceneChannelData.h.
References UE::MovieScene::FindRange(), InTime, and Times.
FindKeys()
template<typename ValueType> void TMovieSceneChannelData< const ValueType >::FindKeys (FFrameNumber InTime, int32 MaxNum, int32 & OutMinIndex, int32 & OutMaxIndex, FFrameNumber InTolerance) const inline
Find the range of keys that fall around InTime +/- InTolerance up to a maximum.
Parameters
InTime The time around which to search
MaxNum A maximum number of times to find, starting with those closest to the predicate time
OutMin The earliest index that met the conditions of the search
OutMax The latest index that met the conditions of the search
InTolerance The tolerance range to search around PredicateTime with
Definition at line 761 of file MovieSceneChannelData.h.
References UE::MovieScene::FindRange(), InTime, and Times.
GetTimes()
template<typename ValueType> FORCEINLINE TArrayView< const FFrameNumber > TMovieSceneChannelData< const ValueType >::GetTimes () const inline
Read-only access to this channel's key times.
Definition at line 725 of file MovieSceneChannelData.h.
References FORCEINLINE, and Times.
GetTotalRange()
template<typename ValueType> TRange< FFrameNumber > TMovieSceneChannelData< const ValueType >::GetTotalRange () const inline
Compute the total time range of the channel data.
Returns
The range of this channel data
Definition at line 771 of file MovieSceneChannelData.h.
References TRange< ElementType >::Empty(), TRangeBound< ElementType >::Inclusive(), and Times.
GetValues()
template<typename ValueType> FORCEINLINE TArrayView< const ValueType > TMovieSceneChannelData< const ValueType >::GetValues () const inline
Read-only access to this channel's values.
Definition at line 733 of file MovieSceneChannelData.h.
References FORCEINLINE, and Values.
UE_DEPRECATED()
TMovieSceneChannelData< ValueType >::UE_DEPRECATED (5. 5, "Constructor that takes an optional FMovieSceneChannel is now deprecated. FMovieSceneChannel is now required.")
Constructor that takes a non-owning pointer to an array of times and values, and a key handle map.
Parameters
InTimes A pointer to an array of times that should be operated on by this class. Externally owned.
InValues A pointer to an array of values that should be operated on by this class. Externally owned.
InKeyHandles A key handle map used for persistent, order independent identification of keys
InChannel A option point to the owning channel, should be set if the move,add, delete delegates are utilizaed
Field Documentation
InChannel
TArray<ValueType> FKeyHandleLookupTable FMovieSceneChannel* TMovieSceneChannelData< ValueType >::InChannel
Definition at line 264 of file MovieSceneChannelData.h.
InKeyHandles
TArray<ValueType> FKeyHandleLookupTable* TMovieSceneChannelData< ValueType >::InKeyHandles
Definition at line 264 of file MovieSceneChannelData.h.
InValues
TArray<ValueType>* TMovieSceneChannelData< ValueType >::InValues
Definition at line 264 of file MovieSceneChannelData.h.
Referenced by TMovieSceneChannelData().
Times
template<typename ValueType> const TArray<FFrameNumber>* TMovieSceneChannelData< const ValueType >::Times private
Pointer to an external array of sorted times.
Must be kept in sync with Values.
Definition at line 779 of file MovieSceneChannelData.h.
Referenced by TMovieSceneChannelData(), FindKey(), FindKeys(), GetTimes(), and GetTotalRange().
Values
template<typename ValueType> const TArray<ValueType>* TMovieSceneChannelData< const ValueType >::Values private
Pointer to an external array of values, to be kept in sync with Times.
Definition at line 782 of file MovieSceneChannelData.h.
Referenced by TMovieSceneChannelData(), and GetValues().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Channels/MovieSceneChannelData.h