Unreal Engine 5.6 C++ API: UE::MovieScene::FCompositePropertyTypeID Struct Reference
UE::MovieScene::FCompositePropertyTypeID Struct Reference
#include "MovieScenePropertySystemTypes.h"
Public Member Functions
FCompositePropertyTypeID ()
int32 AsIndex () const
operator bool () const
Static Public Member Functions
static FCompositePropertyTypeID FromIndex (int32 Index)
Private Member Functions
FCompositePropertyTypeID (int32 InTypeIndex)
Private Attributes
int32 TypeIndex
Friends
class FPropertyRegistry
Detailed Description
Definition at line 30 of file MovieScenePropertySystemTypes.h.
Constructor & Destructor Documentation
FCompositePropertyTypeID() [1/2]
UE::MovieScene::FCompositePropertyTypeID::FCompositePropertyTypeID () inline
Definition at line 32 of file MovieScenePropertySystemTypes.h.
References INDEX_NONE, and TypeIndex.
Referenced by FromIndex().
FCompositePropertyTypeID() [2/2]
UE::MovieScene::FCompositePropertyTypeID::FCompositePropertyTypeID (int32 InTypeIndex) inline private
Definition at line 50 of file MovieScenePropertySystemTypes.h.
References TypeIndex.
Member Function Documentation
AsIndex()
int32 UE::MovieScene::FCompositePropertyTypeID::AsIndex () const inline
Definition at line 39 of file MovieScenePropertySystemTypes.h.
References TypeIndex.
FromIndex()
FCompositePropertyTypeID UE::MovieScene::FCompositePropertyTypeID::FromIndex (int32 Index) inline static
Definition at line 34 of file MovieScenePropertySystemTypes.h.
References FCompositePropertyTypeID().
Referenced by UE::MovieScene::FPropertyRegistry::DefinePropertyImpl().
operator bool()
UE::MovieScene::FCompositePropertyTypeID::operator bool () const inline explicit
Definition at line 44 of file MovieScenePropertySystemTypes.h.
References INDEX_NONE, and TypeIndex.
Friends And Related Symbol Documentation
FPropertyRegistry
friend class FPropertyRegistry friend
Definition at line 52 of file MovieScenePropertySystemTypes.h.
References FPropertyRegistry.
Referenced by FPropertyRegistry.
Field Documentation
TypeIndex
int32 UE::MovieScene::FCompositePropertyTypeID::TypeIndex private
Definition at line 53 of file MovieScenePropertySystemTypes.h.
Referenced by FCompositePropertyTypeID(), FCompositePropertyTypeID(), AsIndex(), UE::MovieScene::FPropertyRegistry::GetDefinition(), and operator bool().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieScenePropertySystemTypes.h