Unreal Engine 5.6 C++ API: FPhysScene_AsyncPhysicsStateJobQueue::FJob Struct Reference
FPhysScene_AsyncPhysicsStateJobQueue::FJob Struct Reference
#include "PhysScene_AsyncPhysicsStateJobQueue.h"
Public Member Functions
FJob (IAsyncPhysicsStateProcessor *InProcessor, EJobType InType)
bool Execute (UE::FTimeout &Timeout) const
bool IsValid () const
void OnPostExecute_GameThread () const
void OnPreExecute_GameThread () const
bool operator== (const FJob &Other) const
Data Fields
IAsyncPhysicsStateProcessor * Processor
EJobType Type
Friends
uint32 GetTypeHash (const FJob &InJob)
Detailed Description
Definition at line 23 of file PhysScene_AsyncPhysicsStateJobQueue.h.
Constructor & Destructor Documentation
FJob()
FPhysScene_AsyncPhysicsStateJobQueue::FJob::FJob (IAsyncPhysicsStateProcessor * InProcessor, EJobType InType) inline
Definition at line 25 of file PhysScene_AsyncPhysicsStateJobQueue.h.
References Processor, and Type.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
Execute()
bool FPhysScene_AsyncPhysicsStateJobQueue::FJob::Execute (UE::FTimeout & Timeout) const
References Timeout.
IsValid()
bool FPhysScene_AsyncPhysicsStateJobQueue::FJob::IsValid () const inline
Definition at line 30 of file PhysScene_AsyncPhysicsStateJobQueue.h.
References IsValid(), and Processor.
Referenced by IsValid().
OnPostExecute_GameThread()
void FPhysScene_AsyncPhysicsStateJobQueue::FJob::OnPostExecute_GameThread () const
OnPreExecute_GameThread()
void FPhysScene_AsyncPhysicsStateJobQueue::FJob::OnPreExecute_GameThread () const
operator==()
bool FPhysScene_AsyncPhysicsStateJobQueue::FJob::operator== (const FJob & Other) const inline
Definition at line 39 of file PhysScene_AsyncPhysicsStateJobQueue.h.
References FJob(), Other, Processor, and Type.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FJob & InJob) friend
Definition at line 44 of file PhysScene_AsyncPhysicsStateJobQueue.h.
References FJob(), GetTypeHash, Processor, and Type.
Referenced by GetTypeHash.
Field Documentation
Processor
IAsyncPhysicsStateProcessor* FPhysScene_AsyncPhysicsStateJobQueue::FJob::Processor
Definition at line 49 of file PhysScene_AsyncPhysicsStateJobQueue.h.
Referenced by FJob(), GetTypeHash, IsValid(), and operator==().
Type
EJobType FPhysScene_AsyncPhysicsStateJobQueue::FJob::Type
Definition at line 50 of file PhysScene_AsyncPhysicsStateJobQueue.h.
Referenced by FJob(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Physics/Experimental/PhysScene_AsyncPhysicsStateJobQueue.h