Unreal Engine 5.6 C++ API: FMallocLeakReportOptions Struct Reference
FMallocLeakReportOptions Struct Reference
Options that can be supplied when calling FMallocLeakDetection::DumpOpenCallstacks.
#include "MallocLeakDetection.h"
Public Types
enum class ESortOption { SortSize , SortRate , SortHash }
Public Member Functions
FMallocLeakReportOptions ()
Data Fields
uint32 FrameEnd
Only show allocations from before this frame.
uint32 FrameStart
Only show allocations after this frame.
bool OnlyNonDeleters
Restrict report to allocations that have no history of being deleted.
FOutputDevice * OutputDevice
Output device used for writing reports.
float RateFilter
If >0 only report allocations at a greater bytes/frame than this.
uint32 SizeFilter
If >0 only report allocations greater than this size.
ESortOption SortBy
Sort allocations by this (default - size)
Detailed Description
Options that can be supplied when calling FMallocLeakDetection::DumpOpenCallstacks.
Definition at line 28 of file MallocLeakDetection.h.
Member Enumeration Documentation
ESortOption
enum class FMallocLeakReportOptions::ESortOption strong
Enumerator
SortSize
SortRate
SortHash
Definition at line 30 of file MallocLeakDetection.h.
Constructor & Destructor Documentation
FMallocLeakReportOptions()
FMallocLeakReportOptions::FMallocLeakReportOptions () inline
Definition at line 37 of file MallocLeakDetection.h.
References FMallocLeakReportOptions(), and FMemory::Memzero().
Referenced by FMallocLeakReportOptions().
Field Documentation
FrameEnd
uint32 FMallocLeakReportOptions::FrameEnd
Only show allocations from before this frame.
Definition at line 55 of file MallocLeakDetection.h.
FrameStart
uint32 FMallocLeakReportOptions::FrameStart
Only show allocations after this frame.
Definition at line 52 of file MallocLeakDetection.h.
OnlyNonDeleters
bool FMallocLeakReportOptions::OnlyNonDeleters
Restrict report to allocations that have no history of being deleted.
Definition at line 49 of file MallocLeakDetection.h.
OutputDevice
FOutputDevice* FMallocLeakReportOptions::OutputDevice
Output device used for writing reports.
If null, a memreport file will be written
Definition at line 61 of file MallocLeakDetection.h.
RateFilter
float FMallocLeakReportOptions::RateFilter
If >0 only report allocations at a greater bytes/frame than this.
Definition at line 46 of file MallocLeakDetection.h.
SizeFilter
uint32 FMallocLeakReportOptions::SizeFilter
If >0 only report allocations greater than this size.
Definition at line 43 of file MallocLeakDetection.h.
SortBy
ESortOption FMallocLeakReportOptions::SortBy
Sort allocations by this (default - size)
Definition at line 58 of file MallocLeakDetection.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/HAL/MallocLeakDetection.h