Unreal Engine 5.6 C++ API: FResourceSizeEx Struct Reference
FResourceSizeEx Struct Reference
Struct used to count up the amount of memory used by a resource.
#include "ResourceSize.h"
Public Member Functions
FResourceSizeEx ()
Default constructor.
FResourceSizeEx (const EResourceSizeMode::Type InResourceSizeMode)
Construct using a given mode.
FResourceSizeEx (const EResourceSizeMode::Type InResourceSizeMode, const SIZE_T InDedicatedSystemMemoryBytes, const SIZE_T InDedicatedVideoMemoryBytes)
Construct from known sizes.
FResourceSizeEx (const EResourceSizeMode::Type InResourceSizeMode, const SIZE_T InUnknownMemoryBytes)
Construct from legacy unknown size.
FResourceSizeEx & AddDedicatedSystemMemoryBytes (const FName &Tag, const SIZE_T InMemoryBytes)
FResourceSizeEx & AddDedicatedSystemMemoryBytes (const SIZE_T InMemoryBytes)
Add the given number of bytes to the dedicated system memory count.
FResourceSizeEx & AddDedicatedVideoMemoryBytes (const FName &Tag, const SIZE_T InMemoryBytes)
FResourceSizeEx & AddDedicatedVideoMemoryBytes (const SIZE_T InMemoryBytes)
Add the given number of bytes to the dedicated video memory count.
FResourceSizeEx & AddUnknownMemoryBytes (const FName &Tag, const SIZE_T InMemoryBytes)
FResourceSizeEx & AddUnknownMemoryBytes (const SIZE_T InMemoryBytes)
Add the given number of bytes to the unknown memory count.
SIZE_T GetDedicatedSystemMemoryBytes () const
Get the number of bytes allocated from dedicated system memory.
SIZE_T GetDedicatedVideoMemoryBytes () const
Get the number of bytes allocated from dedicated video memory.
EResourceSizeMode::Type GetResourceSizeMode () const
Get the type of resource size held in this struct.
SIZE_T GetTotalMemoryBytes () const
Get the total number of bytes allocated from any memory.
SIZE_T GetUnknownMemoryBytes () const
Get the number of bytes allocated from unknown memory.
void LogSummary (FOutputDevice &Ar) const
FResourceSizeEx & operator+= (const FResourceSizeEx &InRHS)
Add another FResourceSizeEx to this one.
Private Attributes
TMap< FName, SIZE_T > DedicatedSystemMemoryBytesMap
The number of bytes of memory that this resource is using for CPU resources that have been allocated from dedicated system memory.
TMap< FName, SIZE_T > DedicatedVideoMemoryBytesMap
The number of bytes of memory that this resource is using for GPU resources that have been allocated from dedicated video memory.
EResourceSizeMode::Type ResourceSizeMode
Type of resource size held in this struct.
TMap< FName, SIZE_T > UnknownMemoryBytesMap
The number of bytes of memory that this resource is using from an unspecified section of memory.
Detailed Description
Struct used to count up the amount of memory used by a resource.
This is typically used for assets via UObject::GetResourceSizeEx(...).
Definition at line 30 of file ResourceSize.h.
Constructor & Destructor Documentation
FResourceSizeEx() [1/4]
FResourceSizeEx::FResourceSizeEx () explicit
Default constructor.
Referenced by AddDedicatedSystemMemoryBytes(), AddDedicatedSystemMemoryBytes(), AddDedicatedVideoMemoryBytes(), AddDedicatedVideoMemoryBytes(), AddUnknownMemoryBytes(), AddUnknownMemoryBytes(), and operator+=().
FResourceSizeEx() [2/4]
FResourceSizeEx::FResourceSizeEx (const EResourceSizeMode::Type InResourceSizeMode) explicit
Construct using a given mode.
FResourceSizeEx() [3/4]
FResourceSizeEx::FResourceSizeEx (const EResourceSizeMode::Type InResourceSizeMode, const SIZE_T InDedicatedSystemMemoryBytes, const SIZE_T InDedicatedVideoMemoryBytes)
Construct from known sizes.
FResourceSizeEx() [4/4]
FResourceSizeEx::FResourceSizeEx (const EResourceSizeMode::Type InResourceSizeMode, const SIZE_T InUnknownMemoryBytes)
Construct from legacy unknown size.
Deliberately explicit to avoid accidental use.
Member Function Documentation
AddDedicatedSystemMemoryBytes() [1/2]
FResourceSizeEx & FResourceSizeEx::AddDedicatedSystemMemoryBytes (const FName & Tag, const SIZE_T InMemoryBytes)
References FResourceSizeEx().
Referenced by FCardRepresentationData::GetResourceSizeEx(), FDistanceFieldVolumeData::GetResourceSizeEx(), and FSparseDistanceFieldMip::GetResourceSizeEx().
AddDedicatedSystemMemoryBytes() [2/2]
FResourceSizeEx & FResourceSizeEx::AddDedicatedSystemMemoryBytes (const SIZE_T InMemoryBytes)
Add the given number of bytes to the dedicated system memory count.
See also
DedicatedSystemMemoryBytes for a description of that memory type.
References FResourceSizeEx().
AddDedicatedVideoMemoryBytes() [1/2]
FResourceSizeEx & FResourceSizeEx::AddDedicatedVideoMemoryBytes (const FName & Tag, const SIZE_T InMemoryBytes)
References FResourceSizeEx().
AddDedicatedVideoMemoryBytes() [2/2]
FResourceSizeEx & FResourceSizeEx::AddDedicatedVideoMemoryBytes (const SIZE_T InMemoryBytes)
Add the given number of bytes to the dedicated video memory count.
See also
DedicatedVideoMemoryBytes for a description of that memory type.
References FResourceSizeEx().
AddUnknownMemoryBytes() [1/2]
FResourceSizeEx & FResourceSizeEx::AddUnknownMemoryBytes (const FName & Tag, const SIZE_T InMemoryBytes)
References FResourceSizeEx().
AddUnknownMemoryBytes() [2/2]
FResourceSizeEx & FResourceSizeEx::AddUnknownMemoryBytes (const SIZE_T InMemoryBytes)
Add the given number of bytes to the unknown memory count.
See also
UnknownMemoryBytes for a description of that memory type.
References FResourceSizeEx().
GetDedicatedSystemMemoryBytes()
SIZE_T FResourceSizeEx::GetDedicatedSystemMemoryBytes () const
Get the number of bytes allocated from dedicated system memory.
See also
DedicatedSystemMemoryBytes for a description of that memory type.
GetDedicatedVideoMemoryBytes()
SIZE_T FResourceSizeEx::GetDedicatedVideoMemoryBytes () const
Get the number of bytes allocated from dedicated video memory.
See also
DedicatedVideoMemoryBytes for a description of that memory type.
GetResourceSizeMode()
EResourceSizeMode::Type FResourceSizeEx::GetResourceSizeMode () const
Get the type of resource size held in this struct.
GetTotalMemoryBytes()
SIZE_T FResourceSizeEx::GetTotalMemoryBytes () const
Get the total number of bytes allocated from any memory.
Referenced by FCardRepresentationData::GetResourceSizeBytes(), FDistanceFieldVolumeData::GetResourceSizeBytes(), FSparseDistanceFieldMip::GetResourceSizeBytes(), and UObject::GetResourceSizeBytes().
GetUnknownMemoryBytes()
SIZE_T FResourceSizeEx::GetUnknownMemoryBytes () const
Get the number of bytes allocated from unknown memory.
See also
UnknownMemoryBytes for a description of that memory type.
LogSummary()
void FResourceSizeEx::LogSummary (FOutputDevice & Ar) const
References Ar.
operator+=()
FResourceSizeEx & FResourceSizeEx::operator+= (const FResourceSizeEx & InRHS)
Add another FResourceSizeEx to this one.
References FResourceSizeEx().
Field Documentation
DedicatedSystemMemoryBytesMap
TMap<FName, SIZE_T> FResourceSizeEx::DedicatedSystemMemoryBytesMap private
The number of bytes of memory that this resource is using for CPU resources that have been allocated from dedicated system memory.
On platforms with unified memory, this typically refers to the things allocated in the preferred memory for CPU use.
Definition at line 124 of file ResourceSize.h.
DedicatedVideoMemoryBytesMap
TMap<FName, SIZE_T> FResourceSizeEx::DedicatedVideoMemoryBytesMap private
The number of bytes of memory that this resource is using for GPU resources that have been allocated from dedicated video memory.
On platforms with unified memory, this typically refers to the things allocated in the preferred memory for GPU use.
Definition at line 130 of file ResourceSize.h.
ResourceSizeMode
EResourceSizeMode::Type FResourceSizeEx::ResourceSizeMode private
Type of resource size held in this struct.
Definition at line 118 of file ResourceSize.h.
UnknownMemoryBytesMap
TMap<FName, SIZE_T> FResourceSizeEx::UnknownMemoryBytesMap private
The number of bytes of memory that this resource is using from an unspecified section of memory.
This exists so that the legacy GetResourceSize(...) functions can still report back memory usage until they're updated to use FResourceSizeEx, and should not be used in new memory tracking code.
Definition at line 136 of file ResourceSize.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/ResourceSize.h