Unreal Engine 5.6 C++ API: FScopedCurveEditorTreeEventGuard Struct Reference
FScopedCurveEditorTreeEventGuard Struct Reference
Scoped guard that prevents the broadcast of tree events for the duration of its lifetime.
#include "CurveEditorTree.h"
Public Member Functions
FScopedCurveEditorTreeEventGuard (FCurveEditorTree *InTree)
FScopedCurveEditorTreeEventGuard (FScopedCurveEditorTreeEventGuard &&RHS)
~FScopedCurveEditorTreeEventGuard ()
FScopedCurveEditorTreeEventGuard & operator= (FScopedCurveEditorTreeEventGuard &&RHS)
Private Attributes
uint32 CachedFiltersSerialNumber
OnFiltersChanged.SerialNumber cached on construction.
uint32 CachedItemSerialNumber
OnItemsChanged.SerialNumber cached on construction.
uint32 CachedSelectionSerialNumber
OnSelectionChanged.SerialNumber cached on construction.
FCurveEditorTree * Tree
Pointer back to the owning tree.
Detailed Description
Scoped guard that prevents the broadcast of tree events for the duration of its lifetime.
Will trigger necessary events after the last remaining guard has been destroyed.
Definition at line 50 of file CurveEditorTree.h.
Constructor & Destructor Documentation
FScopedCurveEditorTreeEventGuard() [1/2]
FScopedCurveEditorTreeEventGuard::FScopedCurveEditorTreeEventGuard (FCurveEditorTree * InTree) explicit
Referenced by FScopedCurveEditorTreeEventGuard(), and operator=().
~FScopedCurveEditorTreeEventGuard()
FScopedCurveEditorTreeEventGuard::~FScopedCurveEditorTreeEventGuard ()
FScopedCurveEditorTreeEventGuard() [2/2]
FScopedCurveEditorTreeEventGuard::FScopedCurveEditorTreeEventGuard (FScopedCurveEditorTreeEventGuard && RHS)
References FScopedCurveEditorTreeEventGuard().
Member Function Documentation
operator=()
FScopedCurveEditorTreeEventGuard & FScopedCurveEditorTreeEventGuard::operator= (FScopedCurveEditorTreeEventGuard && RHS)
References FScopedCurveEditorTreeEventGuard().
Field Documentation
CachedFiltersSerialNumber
uint32 FScopedCurveEditorTreeEventGuard::CachedFiltersSerialNumber private
OnFiltersChanged.SerialNumber cached on construction.
Used to detect whether OnFiltersChanged should be broadcast.
Definition at line 64 of file CurveEditorTree.h.
CachedItemSerialNumber
uint32 FScopedCurveEditorTreeEventGuard::CachedItemSerialNumber private
OnItemsChanged.SerialNumber cached on construction.
Used to detect whether OnItemsChanged should be broadcast.
Definition at line 60 of file CurveEditorTree.h.
CachedSelectionSerialNumber
uint32 FScopedCurveEditorTreeEventGuard::CachedSelectionSerialNumber private
OnSelectionChanged.SerialNumber cached on construction.
Used to detect whether OnSelectionChanged should be broadcast.
Definition at line 62 of file CurveEditorTree.h.
Tree
FCurveEditorTree* FScopedCurveEditorTreeEventGuard::Tree private
Pointer back to the owning tree.
Definition at line 66 of file CurveEditorTree.h.
The documentation for this struct was generated from the following file:
Editor/CurveEditor/Public/Tree/CurveEditorTree.h