Unreal Engine 5.6 C++ API: TStateTreePropertyRefExternalHandle< TRef > Struct Template Reference
TStateTreePropertyRefExternalHandle< TRef > Struct Template Reference
Single type safe external handle allows to wrap-up property reference to make it accessible without having an access to StateTreeExecutionContext.
#include "StateTreePropertyRef.h"
Public Member Functions
TStateTreePropertyRefExternalHandle (TStateTreePropertyRef< TRef > InPropertyRef, FStateTreeExecutionContext &InContext)
FStateTreePropertyRefExternalHandle (FStateTreePropertyRef InPropertyRef, FStateTreeExecutionContext &InContext)
TRef * GetMutablePtr () const
TTuple< TRef *, TArray< TRef > * > GetMutablePtrTuple () const
Public Member Functions inherited from FStateTreePropertyRefExternalHandle
FStateTreePropertyRefExternalHandle (FStateTreePropertyRef InPropertyRef, FStateTreeExecutionContext &InContext)
template<class TRef>
TRef * GetMutablePtr () const
template<class... TRef>
TTuple< TRef *... > GetMutablePtrTuple () const
Additional Inherited Members
Protected Attributes inherited from FStateTreePropertyRefExternalHandle
FStateTreePropertyRef PropertyRef
FStateTreeStateHandle RootState = FStateTreeStateHandle::Invalid
TWeakPtr< FStateTreeInstanceStorage > WeakInstanceStorage
TWeakObjectPtr< const UStateTree > WeakStateTree = nullptr
Detailed Description
template<class TRef>
struct TStateTreePropertyRefExternalHandle< TRef >
Single type safe external handle allows to wrap-up property reference to make it accessible without having an access to StateTreeExecutionContext.
Useful for capturing property reference in callbacks.
Definition at line 306 of file StateTreePropertyRef.h.
Constructor & Destructor Documentation
TStateTreePropertyRefExternalHandle()
template<class TRef> TStateTreePropertyRefExternalHandle< TRef >::TStateTreePropertyRefExternalHandle (TStateTreePropertyRef< TRef > InPropertyRef, FStateTreeExecutionContext & InContext) inline
Definition at line 309 of file StateTreePropertyRef.h.
References FStateTreePropertyRefExternalHandle().
Member Function Documentation
FStateTreePropertyRefExternalHandle()
template<class TRef> FStateTreePropertyRefExternalHandle::FStateTreePropertyRefExternalHandle (FStateTreePropertyRef InPropertyRef, FStateTreeExecutionContext & InContext) inline
Definition at line 258 of file StateTreePropertyRef.h.
Referenced by TStateTreePropertyRefExternalHandle().
GetMutablePtr()
template<class TRef> TRef * TStateTreePropertyRefExternalHandle< TRef >::GetMutablePtr () const inline
Returns
pointer to the property if possible, nullptr otherwise.
Definition at line 315 of file StateTreePropertyRef.h.
References FStateTreePropertyRefExternalHandle::GetMutablePtr().
GetMutablePtrTuple()
template<class TRef> TTuple< TRef *, TArray< TRef > * > TStateTreePropertyRefExternalHandle< TRef >::GetMutablePtrTuple () const inline
Returns
a tuple of pointer to the property of the type or array of type, nullptr otherwise.
Definition at line 321 of file StateTreePropertyRef.h.
References FStateTreePropertyRefExternalHandle::GetMutablePtrTuple().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreePropertyRef.h