Unreal Engine 5.6 C++ API: TMovieSceneEvaluationTree< DataType > Struct Template Reference
TMovieSceneEvaluationTree< DataType > Struct Template Reference
Templated version of FMovieSceneEvaluationTree that is also able to associate arbitrary data with nodes.
#include "MovieSceneEvaluationTree.h"
Data Structures
struct FAddOperator
Operator that adds data to nodes.
struct FAddUniqueOperator
Operator that adds data to nodes provided it doesn't already exist on the node.
Public Member Functions
void Add (TRange< FFrameNumber > InTimeRange)
Add a time range with no data associated.
void Add (TRange< FFrameNumber > InTimeRange, DataType InData)
Add a new time range with the associated data to the tree.
void AddIfEmpty (TRange< FFrameNumber > InTimeRange, DataType InData)
Adds a new time range with the associated data to the tree, only for segments where there's no data yet.
void AddIfEmptySelective (TRange< FFrameNumber > InTimeRange, DataType InData, TFunctionRef< bool(FMovieSceneEvaluationTreeNodeHandle)> Predicate)
Adds a new time range with the associated data to the tree, only for segments where there's no data yet.
void AddSelective (TRange< FFrameNumber > InTimeRange, DataType InData, TFunctionRef< bool(FMovieSceneEvaluationTreeNodeHandle)> Predicate)
Add a new time range with the associated data to the tree.
void AddUnique (TRange< FFrameNumber > InTimeRange, DataType InData)
Add a new time range with the associated data to the tree.
void Compact ()
Compact the memory used by this tree so it's using as little as possible.
TMovieSceneEvaluationTreeDataIterator< DataType > GetAllData (FMovieSceneEvaluationTreeNodeHandle NodeHandle) const
Create an iterator that will iterate all data associated with the specified node.
TArrayView< const DataType > GetDataForSingleNode (const FMovieSceneEvaluationTreeNode &InNode) const
Access the data associated with a single node in the tree.
TArrayView< DataType > GetMutableDataForSingleNode (const FMovieSceneEvaluationTreeNode &InNode)
Access the data associated with a single node in the tree.
bool IsEmpty () const
Check whether this tree is empty.
void Reset ()
Reset this tree.
Public Member Functions inherited from FMovieSceneEvaluationTree
FMovieSceneEvaluationTree ()
FMovieSceneEvaluationTree (const FMovieSceneEvaluationTree &RHS)=default
FMovieSceneEvaluationTree (FMovieSceneEvaluationTree &&RHS)
Move construction must ensure that the root node is correctly restored to its default to ensure that invariant.
MOVIESCENE_API void AddTimeRange (TRange< FFrameNumber > InTimeRange)
Insert the specified time range into this tree.
MOVIESCENE_API TArrayView< FMovieSceneEvaluationTreeNode > GetChildren (const FMovieSceneEvaluationTreeNode &InNode)
Get the children associated with the specified node.
MOVIESCENE_API TArrayView< const FMovieSceneEvaluationTreeNode > GetChildren (const FMovieSceneEvaluationTreeNode &InNode) const
Get the children associated with the specified node.
FMovieSceneEvaluationTreeNode & GetNode (FMovieSceneEvaluationTreeNodeHandle Handle)
Non-const access to a node from its handle.
const FMovieSceneEvaluationTreeNode & GetNode (FMovieSceneEvaluationTreeNodeHandle Handle) const
Const access to a node from its handle.
const FMovieSceneEvaluationTreeNode & GetRootNode () const
Access this tree's root node (infinite range)
bool IsValid (FMovieSceneEvaluationTreeNodeHandle Handle) const
Check whether the specified handle corresponds to a node within this tree.
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator IterateFromLowerBound (TRangeBound< FFrameNumber > InStartingLowerBound) const
Start iterating this tree from the specified lower boundary.
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator IterateFromTime (FFrameNumber Time) const
Start iterating this tree from the specified time.
FMovieSceneEvaluationTree & operator= (const FMovieSceneEvaluationTree &RHS)=default
FMovieSceneEvaluationTree & operator= (FMovieSceneEvaluationTree &&RHS)
Move assignment must ensure that the root node is correctly restored to its default to ensure that invariant.
void Reset ()
Private Attributes
TEvaluationTreeEntryContainer< DataType > Data
Tree data container that corresponds to FMovieSceneEvaluationTreeNode::DataID.
Friends
FArchive & operator<< (FArchive &Ar, TMovieSceneEvaluationTree< DataType > &In)
Serialization operator.
bool operator== (const TMovieSceneEvaluationTree< DataType > &A, const TMovieSceneEvaluationTree< DataType > &B)
Equality operator.
struct TMovieSceneEvaluationTreeFormatter< DataType >
Additional Inherited Members
Protected Member Functions inherited from FMovieSceneEvaluationTree
MOVIESCENE_API void AddTimeRange (TRange< FFrameNumber > InTimeRange, const IMovieSceneEvaluationTreeNodeOperator &InOperator, FMovieSceneEvaluationTreeNodeHandle InParent, const TFunctionRef< bool(FMovieSceneEvaluationTreeNodeHandle)> *Predicate)
Insert the specified time range into this tree.
FMovieSceneEvaluationTreeNode & GetNode (FEvaluationTreeEntryHandle ChildrenID, int32 Index)
Non-const access to a node from its parent's ChildrenID and this node's index.
const FMovieSceneEvaluationTreeNode & GetNode (FEvaluationTreeEntryHandle ChildrenID, int32 Index) const
Const access to a node from its parent's ChildrenID and this node's index.
MOVIESCENE_API void InsertNewChild (TRange< FFrameNumber > InEffectiveRange, const IMovieSceneEvaluationTreeNodeOperator &InOperator, int32 InsertIndex, FMovieSceneEvaluationTreeNodeHandle InParent)
Helper function that creates a new child for the specified parent node.
Protected Attributes inherited from FMovieSceneEvaluationTree
TEvaluationTreeEntryContainer< FMovieSceneEvaluationTreeNode > ChildNodes
Segmented array of all child nodes within this tree (in no particular order)
FMovieSceneEvaluationTreeNode RootNode
This tree's root node.
Detailed Description
template<typename DataType>
struct TMovieSceneEvaluationTree< DataType >
Templated version of FMovieSceneEvaluationTree that is also able to associate arbitrary data with nodes.
Definition at line 602 of file MovieSceneEvaluationTree.h.
Member Function Documentation
Add() [1/2]
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::Add (TRange< FFrameNumber > InTimeRange) inline
Add a time range with no data associated.
Parameters
InTimeRange The range with which this data should be associated
Definition at line 618 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree::AddTimeRange(), and FMovieSceneEvaluationTreeNodeHandle::Root().
Add() [2/2]
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::Add (TRange< FFrameNumber > InTimeRange, DataType InData) inline
Add a new time range with the associated data to the tree.
Parameters
InTimeRange The range with which this data should be associated
InData The data to assoicate with this time range
Definition at line 683 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree::AddTimeRange(), MoveTemp(), and FMovieSceneEvaluationTreeNodeHandle::Root().
AddIfEmpty()
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::AddIfEmpty (TRange< FFrameNumber > InTimeRange, DataType InData) inline
Adds a new time range with the associated data to the tree, only for segments where there's no data yet.
Parameters
InTimeRange The range with which this data should be associated
InData The data to assoicate with this time range
Definition at line 646 of file MovieSceneEvaluationTree.h.
References AddSelective(), GetAllData(), and MoveTemp().
AddIfEmptySelective()
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::AddIfEmptySelective (TRange< FFrameNumber > InTimeRange, DataType InData, TFunctionRef< bool(FMovieSceneEvaluationTreeNodeHandle)> Predicate) inline
Adds a new time range with the associated data to the tree, only for segments where there's no data yet.
Parameters
InTimeRange The range with which this data should be associated
InData The data to assoicate with this time range
Definition at line 659 of file MovieSceneEvaluationTree.h.
References AddSelective(), GetAllData(), MoveTemp(), and Predicate.
AddSelective()
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::AddSelective (TRange< FFrameNumber > InTimeRange, DataType InData, TFunctionRef< bool(FMovieSceneEvaluationTreeNodeHandle)> Predicate) inline
Add a new time range with the associated data to the tree.
Parameters
InTimeRange The range with which this data should be associated
InData The data to assoicate with this time range
Definition at line 672 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree::AddTimeRange(), MoveTemp(), Predicate, and FMovieSceneEvaluationTreeNodeHandle::Root().
Referenced by AddIfEmpty(), and AddIfEmptySelective().
AddUnique()
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::AddUnique (TRange< FFrameNumber > InTimeRange, DataType InData) inline
Add a new time range with the associated data to the tree.
Ensures no duplicates.
Parameters
InTimeRange The range with which this data should be associated
InData The data to assoicate with this time range
Definition at line 635 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree::AddTimeRange(), MoveTemp(), and FMovieSceneEvaluationTreeNodeHandle::Root().
Compact()
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::Compact () inline
Compact the memory used by this tree so it's using as little as possible.
Definition at line 691 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree::ChildNodes, and Data.
GetAllData()
template<typename DataType> TMovieSceneEvaluationTreeDataIterator< DataType > TMovieSceneEvaluationTree< DataType >::GetAllData (FMovieSceneEvaluationTreeNodeHandle NodeHandle) const inline
Create an iterator that will iterate all data associated with the specified node.
Parameters
NodeHandle The node to get all data for
Definition at line 727 of file MovieSceneEvaluationTree.h.
Referenced by AddIfEmpty(), and AddIfEmptySelective().
GetDataForSingleNode()
template<typename DataType> TArrayView< const DataType > TMovieSceneEvaluationTree< DataType >::GetDataForSingleNode (const FMovieSceneEvaluationTreeNode & InNode) const inline
Access the data associated with a single node in the tree.
Definition at line 709 of file MovieSceneEvaluationTree.h.
References Data, FMovieSceneEvaluationTreeNode::DataID, and FEvaluationTreeEntryHandle::IsValid().
Referenced by TMovieSceneEvaluationTreeDataIterator< DataType >::TMovieSceneEvaluationTreeDataIterator(), and IsEmpty().
GetMutableDataForSingleNode()
template<typename DataType> TArrayView< DataType > TMovieSceneEvaluationTree< DataType >::GetMutableDataForSingleNode (const FMovieSceneEvaluationTreeNode & InNode) inline
Access the data associated with a single node in the tree.
Definition at line 717 of file MovieSceneEvaluationTree.h.
References Data, FMovieSceneEvaluationTreeNode::DataID, and FEvaluationTreeEntryHandle::IsValid().
IsEmpty()
template<typename DataType> bool TMovieSceneEvaluationTree< DataType >::IsEmpty () const inline
Check whether this tree is empty.
Definition at line 608 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree::GetChildren(), GetDataForSingleNode(), and FMovieSceneEvaluationTree::GetRootNode().
Reset()
template<typename DataType> void TMovieSceneEvaluationTree< DataType >::Reset () inline
Reset this tree.
Definition at line 700 of file MovieSceneEvaluationTree.h.
References Data, and FMovieSceneEvaluationTree::Reset().
Friends And Related Symbol Documentation
operator<<
template<typename DataType> FArchive & operator<< (FArchive & Ar, TMovieSceneEvaluationTree< DataType > & In) friend
Serialization operator.
Definition at line 735 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree::FMovieSceneEvaluationTree(), Ar, and Data.
operator==
template<typename DataType> bool operator== (const TMovieSceneEvaluationTree< DataType > & A, const TMovieSceneEvaluationTree< DataType > & B) friend
Equality operator.
Definition at line 744 of file MovieSceneEvaluationTree.h.
References A, and B.
TMovieSceneEvaluationTreeFormatter< DataType >
template<typename DataType> friend struct TMovieSceneEvaluationTreeFormatter< DataType > friend
Definition at line 752 of file MovieSceneEvaluationTree.h.
Field Documentation
Data
template<typename DataType> TEvaluationTreeEntryContainer<DataType> TMovieSceneEvaluationTree< DataType >::Data private
Tree data container that corresponds to FMovieSceneEvaluationTreeNode::DataID.
Definition at line 752 of file MovieSceneEvaluationTree.h.
Referenced by Compact(), GetDataForSingleNode(), GetMutableDataForSingleNode(), operator<<, and Reset().
The documentation for this struct was generated from the following files:
Runtime/MovieScene/Public/Compilation/MovieSceneEvaluationTreePopulationRules.h
Runtime/MovieScene/Public/Evaluation/MovieSceneEvaluationTree.h