Unreal Engine 5.6 C++ API: FRDGTextureDesc Struct Reference
FRDGTextureDesc Struct Reference
#include "RenderGraphDefinitions.h"
Public Member Functions
FRDGTextureDesc ()=default
FRDGTextureDesc (ETextureDimension InDimension, ETextureCreateFlags InFlags, EPixelFormat InFormat, FClearValueBinding InClearValue, FIntPoint InExtent, uint16 InDepth, uint16 InArraySize, uint8 InNumMips, uint8 InNumSamples, uint32 InExtData)
Static Public Member Functions
static FRDGTextureDesc Create2D (FIntPoint Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint8 NumMips=1, uint8 NumSamples=1, uint32 ExtData=0)
static FRDGTextureDesc Create2DArray (FIntPoint Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint16 ArraySize, uint8 NumMips=1, uint8 NumSamples=1, uint32 ExtData=0)
static FRDGTextureDesc Create3D (FIntVector Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint8 NumMips=1, uint32 ExtData=0)
static FRDGTextureDesc CreateCube (uint32 Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint8 NumMips=1, uint8 NumSamples=1, uint32 ExtData=0)
static FRDGTextureDesc CreateCubeArray (uint32 Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint16 ArraySize, uint8 NumMips=1, uint8 NumSamples=1, uint32 ExtData=0)
static FRDGTextureDesc CreateRenderTargetTextureDesc (FIntPoint Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, const bool bRequireMultiView, uint16 MobileMultiViewRenderTargetNumLayers=2)
Detailed Description
Definition at line 626 of file RenderGraphDefinitions.h.
Constructor & Destructor Documentation
FRDGTextureDesc() [1/2]
FRDGTextureDesc::FRDGTextureDesc () default
Referenced by Create2D(), Create2DArray(), Create3D(), CreateCube(), CreateCubeArray(), and CreateRenderTargetTextureDesc().
FRDGTextureDesc() [2/2]
FRDGTextureDesc::FRDGTextureDesc (ETextureDimension InDimension, ETextureCreateFlags InFlags, EPixelFormat InFormat, FClearValueBinding InClearValue, FIntPoint InExtent, uint16 InDepth, uint16 InArraySize, uint8 InNumMips, uint8 InNumSamples, uint32 InExtData) inline
Definition at line 725 of file RenderGraphDefinitions.h.
Member Function Documentation
Create2D()
FRDGTextureDesc FRDGTextureDesc::Create2D (FIntPoint Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint8 NumMips = 1, uint8 NumSamples = 1, uint32 ExtData = 0) inline static
Definition at line 628 of file RenderGraphDefinitions.h.
References FRDGTextureDesc(), Depth, Flags, Format, and TSequenceHistory< HistorySize >::Size.
Referenced by CreateRenderTargetTextureDesc().
Create2DArray()
FRDGTextureDesc FRDGTextureDesc::Create2DArray (FIntPoint Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint16 ArraySize, uint8 NumMips = 1, uint8 NumSamples = 1, uint32 ExtData = 0) inline static
Definition at line 643 of file RenderGraphDefinitions.h.
References FRDGTextureDesc(), Depth, Flags, Format, and TSequenceHistory< HistorySize >::Size.
Referenced by CreateRenderTargetTextureDesc().
Create3D()
FRDGTextureDesc FRDGTextureDesc::Create3D (FIntVector Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint8 NumMips = 1, uint32 ExtData = 0) inline static
Definition at line 658 of file RenderGraphDefinitions.h.
References FRDGTextureDesc(), checkf, Flags, Format, Max, TEXT, and TSequenceHistory< HistorySize >::Size.
CreateCube()
FRDGTextureDesc FRDGTextureDesc::CreateCube (uint32 Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint8 NumMips = 1, uint8 NumSamples = 1, uint32 ExtData = 0) inline static
Definition at line 675 of file RenderGraphDefinitions.h.
References FRDGTextureDesc(), checkf, Depth, Flags, Format, TEXT, and TSequenceHistory< HistorySize >::Size.
CreateCubeArray()
FRDGTextureDesc FRDGTextureDesc::CreateCubeArray (uint32 Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, uint16 ArraySize, uint8 NumMips = 1, uint8 NumSamples = 1, uint32 ExtData = 0) inline static
Definition at line 692 of file RenderGraphDefinitions.h.
References FRDGTextureDesc(), checkf, Depth, Flags, Format, TEXT, and TSequenceHistory< HistorySize >::Size.
CreateRenderTargetTextureDesc()
FRDGTextureDesc FRDGTextureDesc::CreateRenderTargetTextureDesc (FIntPoint Size, EPixelFormat Format, FClearValueBinding ClearValue, ETextureCreateFlags Flags, const bool bRequireMultiView, uint16 MobileMultiViewRenderTargetNumLayers = 2) inline static
Definition at line 709 of file RenderGraphDefinitions.h.
References FRDGTextureDesc(), Create2D(), Create2DArray(), Flags, Format, and TSequenceHistory< HistorySize >::Size.
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphDefinitions.h