Unreal Engine 5.6 C++ API: UE::FPropertyPathNameSegment Struct Reference
UE::FPropertyPathNameSegment Struct Reference
Represents one segment of a property path including the property type and the container index.
#include "PropertyPathName.h"
Public Member Functions
FName PackNameWithIndex () const
FPropertyPathNameSegment SetNameWithIndex (FName NameWithIndex) const
FPropertyPathNameSegment SetType (FPropertyTypeName NewType) const
Data Fields
int32 Index = INDEX_NONE
Index within a container, or INDEX_NONE if not in a container.
FName Name
Name of the property.
FPropertyTypeName Type
Type of the property, if available.
Detailed Description
Represents one segment of a property path including the property type and the container index.
Definition at line 19 of file PropertyPathName.h.
Member Function Documentation
PackNameWithIndex()
FName UE::FPropertyPathNameSegment::PackNameWithIndex () const inline nodiscard
Definition at line 28 of file PropertyPathName.h.
References FName, Index, Name, and NAME_EXTERNAL_TO_INTERNAL.
SetNameWithIndex()
FPropertyPathNameSegment UE::FPropertyPathNameSegment::SetNameWithIndex (FName NameWithIndex) const inline nodiscard
Definition at line 33 of file PropertyPathName.h.
References FName, FName::GetNumber(), NAME_INTERNAL_TO_EXTERNAL, NAME_NO_NUMBER_INTERNAL, and Type.
Referenced by UE::FPropertyPathName::FSegment::Unpack().
SetType()
FPropertyPathNameSegment UE::FPropertyPathNameSegment::SetType (FPropertyTypeName NewType) const inline nodiscard
Definition at line 38 of file PropertyPathName.h.
References Index, and Name.
Referenced by UE::FPropertyPathName::FSegment::Unpack().
Field Documentation
Index
int32 UE::FPropertyPathNameSegment::Index = INDEX_NONE
Index within a container, or INDEX_NONE if not in a container.
Uses ElementId for associative containers.
Definition at line 26 of file PropertyPathName.h.
Referenced by PackNameWithIndex(), and SetType().
Name
FName UE::FPropertyPathNameSegment::Name
Name of the property.
Definition at line 22 of file PropertyPathName.h.
Referenced by PackNameWithIndex(), and SetType().
Type
FPropertyTypeName UE::FPropertyPathNameSegment::Type
Type of the property, if available.
Definition at line 24 of file PropertyPathName.h.
Referenced by SetNameWithIndex().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PropertyPathName.h