Unreal Engine 5.6 C++ API: FParticlePerfStats_GT Struct Reference
FParticlePerfStats_GT Struct Reference
Stats gathered on the game thread or game thread spawned tasks.
#include "ParticlePerfStats.h"
Public Member Functions
FParticlePerfStats_GT ()
FParticlePerfStats_GT (const FParticlePerfStats_GT &Other)
FParticlePerfStats_GT (FParticlePerfStats_GT &&Other)
FORCEINLINE uint64 GetPerInstanceAvgCycles () const
FORCEINLINE uint64 GetPerInstanceAvgCycles_GTOnly () const
FORCEINLINE uint64 GetTotalCycles () const
FORCEINLINE uint64 GetTotalCycles_GTOnly () const
FParticlePerfStats_GT & operator+= (FParticlePerfStats_GT &Other)
FParticlePerfStats_GT & operator= (const FParticlePerfStats_GT &Other)
FParticlePerfStats_GT & operator= (FParticlePerfStats_GT &&Other)
FORCEINLINE void Reset ()
Data Fields
TAtomic< uint64 > ActivationCycles
TAtomic< uint64 > EndOfFrameCycles
uint64 FinalizeCycles
uint64 NumInstances
TAtomic< uint64 > TickConcurrentCycles
uint64 TickGameThreadCycles
uint64 WaitCycles
Detailed Description
Stats gathered on the game thread or game thread spawned tasks.
Definition at line 42 of file ParticlePerfStats.h.
Constructor & Destructor Documentation
FParticlePerfStats_GT() [1/3]
FParticlePerfStats_GT::FParticlePerfStats_GT () inline
Definition at line 52 of file ParticlePerfStats.h.
References Reset().
Referenced by FParticlePerfStats_GT(), FParticlePerfStats_GT(), operator+=(), operator=(), and operator=().
FParticlePerfStats_GT() [2/3]
FParticlePerfStats_GT::FParticlePerfStats_GT (const FParticlePerfStats_GT & Other) inline
Definition at line 54 of file ParticlePerfStats.h.
References FParticlePerfStats_GT(), ActivationCycles, EndOfFrameCycles, FinalizeCycles, NumInstances, Other, TickConcurrentCycles, TickGameThreadCycles, and WaitCycles.
FParticlePerfStats_GT() [3/3]
FParticlePerfStats_GT::FParticlePerfStats_GT (FParticlePerfStats_GT && Other) inline
Definition at line 77 of file ParticlePerfStats.h.
References FParticlePerfStats_GT(), and Other.
Member Function Documentation
GetPerInstanceAvgCycles()
FORCEINLINE uint64 FParticlePerfStats_GT::GetPerInstanceAvgCycles () const inline
Definition at line 117 of file ParticlePerfStats.h.
References FORCEINLINE, GetTotalCycles(), and NumInstances.
GetPerInstanceAvgCycles_GTOnly()
FORCEINLINE uint64 FParticlePerfStats_GT::GetPerInstanceAvgCycles_GTOnly () const inline
Definition at line 114 of file ParticlePerfStats.h.
References FORCEINLINE, GetTotalCycles_GTOnly(), and NumInstances.
GetTotalCycles()
FORCEINLINE uint64 FParticlePerfStats_GT::GetTotalCycles () const inline
Definition at line 116 of file ParticlePerfStats.h.
References EndOfFrameCycles, FORCEINLINE, GetTotalCycles_GTOnly(), and TickConcurrentCycles.
Referenced by GetPerInstanceAvgCycles().
GetTotalCycles_GTOnly()
FORCEINLINE uint64 FParticlePerfStats_GT::GetTotalCycles_GTOnly () const inline
Definition at line 113 of file ParticlePerfStats.h.
References ActivationCycles, FinalizeCycles, FORCEINLINE, TickGameThreadCycles, and WaitCycles.
Referenced by GetPerInstanceAvgCycles_GTOnly(), and GetTotalCycles().
operator+=()
FParticlePerfStats_GT & FParticlePerfStats_GT::operator+= (FParticlePerfStats_GT & Other) inline
Definition at line 90 of file ParticlePerfStats.h.
References FParticlePerfStats_GT(), ActivationCycles, EndOfFrameCycles, FinalizeCycles, NumInstances, Other, TickConcurrentCycles, TickGameThreadCycles, and WaitCycles.
operator=() [1/2]
FParticlePerfStats_GT & FParticlePerfStats_GT::operator= (const FParticlePerfStats_GT & Other) inline
Definition at line 65 of file ParticlePerfStats.h.
References FParticlePerfStats_GT(), ActivationCycles, EndOfFrameCycles, FinalizeCycles, NumInstances, Other, TickConcurrentCycles, TickGameThreadCycles, and WaitCycles.
operator=() [2/2]
FParticlePerfStats_GT & FParticlePerfStats_GT::operator= (FParticlePerfStats_GT && Other) inline
Definition at line 83 of file ParticlePerfStats.h.
References FParticlePerfStats_GT(), and Other.
Reset()
FORCEINLINE void FParticlePerfStats_GT::Reset () inline
Definition at line 102 of file ParticlePerfStats.h.
References ActivationCycles, EndOfFrameCycles, FinalizeCycles, FORCEINLINE, NumInstances, TickConcurrentCycles, TickGameThreadCycles, and WaitCycles.
Referenced by FParticlePerfStats_GT().
Field Documentation
ActivationCycles
TAtomic<uint64> FParticlePerfStats_GT::ActivationCycles
Definition at line 49 of file ParticlePerfStats.h.
Referenced by FParticlePerfStats_GT(), GetTotalCycles_GTOnly(), operator+=(), operator=(), and Reset().
EndOfFrameCycles
TAtomic<uint64> FParticlePerfStats_GT::EndOfFrameCycles
Definition at line 48 of file ParticlePerfStats.h.
Referenced by FParticlePerfStats_GT(), GetTotalCycles(), operator+=(), operator=(), and Reset().
FinalizeCycles
uint64 FParticlePerfStats_GT::FinalizeCycles
Definition at line 47 of file ParticlePerfStats.h.
Referenced by FParticlePerfStats_GT(), GetTotalCycles_GTOnly(), operator+=(), operator=(), and Reset().
NumInstances
uint64 FParticlePerfStats_GT::NumInstances
Definition at line 44 of file ParticlePerfStats.h.
Referenced by FParticlePerfStats_GT(), GetPerInstanceAvgCycles(), GetPerInstanceAvgCycles_GTOnly(), operator+=(), operator=(), and Reset().
TickConcurrentCycles
TAtomic<uint64> FParticlePerfStats_GT::TickConcurrentCycles
Definition at line 46 of file ParticlePerfStats.h.
Referenced by FParticlePerfStats_GT(), GetTotalCycles(), operator+=(), operator=(), and Reset().
TickGameThreadCycles
uint64 FParticlePerfStats_GT::TickGameThreadCycles
Definition at line 45 of file ParticlePerfStats.h.
Referenced by FParticlePerfStats_GT(), GetTotalCycles_GTOnly(), operator+=(), operator=(), and Reset().
WaitCycles
uint64 FParticlePerfStats_GT::WaitCycles
Definition at line 50 of file ParticlePerfStats.h.
Referenced by FParticlePerfStats_GT(), GetTotalCycles_GTOnly(), operator+=(), operator=(), and Reset().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Particles/ParticlePerfStats.h