Unreal Engine 5.6 C++ API: UE::Graph::FMappingOneToMany Struct Reference
UE::Graph::FMappingOneToMany Struct Reference
Represents a mapping between two graphs where each vertex in a source graph maps to multiple vertices in a target graph.
#include "GraphConvert.h"
Public Member Functions
FMappingOneToMany ()=default
FMappingOneToMany (const FMappingOneToMany &)=delete
FMappingOneToMany (FMappingOneToMany &&)=default
SIZE_T GetAllocatedSize () const
FMappingOneToMany & operator= (const FMappingOneToMany &)=delete
FMappingOneToMany & operator= (FMappingOneToMany &&)=default
Data Fields
TArray64< FVertex > Buffer
TArray< TConstArrayView< FVertex > > Mapping
Detailed Description
Represents a mapping between two graphs where each vertex in a source graph maps to multiple vertices in a target graph.
The length of Mapping is the number of vertices in the source graph and the contents of each mapping are vertices in the target graph. Buffer stores the contents of all array views in Mapping. e.g. a mapping between the vertices in a condensation graph and the original cyclic graph it was generated from.
Definition at line 60 of file GraphConvert.h.
Constructor & Destructor Documentation
FMappingOneToMany() [1/3]
UE::Graph::FMappingOneToMany::FMappingOneToMany () default
Referenced by FMappingOneToMany(), FMappingOneToMany(), operator=(), and operator=().
FMappingOneToMany() [2/3]
UE::Graph::FMappingOneToMany::FMappingOneToMany (const FMappingOneToMany &) delete
References FMappingOneToMany().
FMappingOneToMany() [3/3]
UE::Graph::FMappingOneToMany::FMappingOneToMany (FMappingOneToMany &&) default
References FMappingOneToMany().
Member Function Documentation
GetAllocatedSize()
SIZE_T UE::Graph::FMappingOneToMany::GetAllocatedSize () const inline
Definition at line 72 of file GraphConvert.h.
References Buffer, and Mapping.
operator=() [1/2]
FMappingOneToMany & UE::Graph::FMappingOneToMany::operator= (const FMappingOneToMany &) delete
References FMappingOneToMany().
operator=() [2/2]
FMappingOneToMany & UE::Graph::FMappingOneToMany::operator= (FMappingOneToMany &&) default
References FMappingOneToMany().
Field Documentation
Buffer
TArray64<FVertex> UE::Graph::FMappingOneToMany::Buffer
Definition at line 62 of file GraphConvert.h.
Referenced by GetAllocatedSize().
Mapping
TArray<TConstArrayView<FVertex> > UE::Graph::FMappingOneToMany::Mapping
Definition at line 63 of file GraphConvert.h.
Referenced by GetAllocatedSize().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Experimental/Graph/GraphConvert.h