Unreal Engine 5.6 C++ API: FWindowsPlatformMisc Struct Reference
FWindowsPlatformMisc Struct Reference
Windows implementation of the misc OS functions.
#include "WindowsPlatformMisc.h"
Public Member Functions
UE_DEPRECATED (4.21, "void FPlatformMisc::GetEnvironmentVariable(Name, Result, Length) is deprecated. Use FString FPlatformMisc::GetEnvironmentVariable(Name) instead.") static 1 void GetEnvironmentVariable(const TCHAR *VariableName
UE_DEPRECATED (5.2, "Please use PLATFORM_CACHE_LINE_SIZE instead, runtime query of cache line size not supported") static 1 int32 GetCacheLineSize()
Public Member Functions inherited from FGenericPlatformMisc
UE_DEPRECATED (4.14, "GetHasedMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetHashedMacAddressString()
Retrieve the Mac address of the current adapter as a hashed string (privacy).
UE_DEPRECATED (4.14, "GetMacAddress is deprecated. It is not reliable on all platforms") static 1 TArray< uint8 > GetMacAddress()
Retrieve the Mac address of the current adapter.
UE_DEPRECATED (4.14, "GetMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetMacAddressString()
Retrieve the Mac address of the current adapter as a string.
UE_DEPRECATED (4.14, "GetMachineId is deprecated. Use GetLoginId instead.") static 1 FGuid GetMachineId()
Get (or create) the unique ID used to identify this computer.
UE_DEPRECATED (4.18, "FPaths::SetOverrideGameDir() has been superseded by FPaths::SetOverrideProjectDir().") static FORCEINLINE void SetOverrideGameDir(const FString &InOverrideDir)
UE_DEPRECATED (4.19, "FPlatformMisc::DebugBreak is deprecated. Use the UE_DEBUG_BREAK() macro instead.") FORCEINLINE static void DebugBreak()
Break into the debugger, if IsDebuggerPresent returns true, otherwise do nothing.
UE_DEPRECATED (5.1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.") static 1 void SetDeviceOrientation(EDeviceScreenOrientation NewDeviceOrientation)
Change the orientation of the device.
UE_DEPRECATED (5.2, "Must supply size when prefetching a block of data") FORCEINLINE static void PrefetchBlock(const void *Ptr)
Static Public Member Functions
static void AsymmetricThreadFenceHeavy ()
static FORCEINLINE void AsymmetricThreadFenceLight ()
static void CallGracefulTerminationHandler ()
static FORCEINLINE void ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat &OutputDevice, EDisplayColorGamut &ColorGamut)
static bool CoInitialize (ECOMModel Model=ECOMModel::Singlethreaded)
static bool CommandLineCommands ()
static void CoUninitialize ()
static void CreateGuid (struct FGuid &Result)
static bool DeleteStoredSection (const FString &InStoreId, const FString &InSectionName)
static bool DeleteStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName)
static int GetBatteryLevel ()
Returns the current battery level between 0 and 100, or -1 if a battery is not present or if the current battery level cannot be retrieved.
static bool GetBlockingIOStats (FProcessIOStats &OutStats, EInputOutputFlags Flags=EInputOutputFlags::All)
static EConvertibleLaptopMode GetConvertibleLaptopMode ()
static FString GetCPUBrand ()
static uint32 GetCPUInfo ()
Uses cpuid instruction to get the vendor string.
static FString GetCPUVendor ()
static ECrashHandlingType GetCrashHandlingType ()
static FString GetDefaultLanguage ()
static FString GetDefaultLocale ()
static const TCHAR * GetDefaultPathSeparator ()
static bool GetDiskTotalAndFreeSpace (const FString &InPath, uint64 &TotalNumberOfBytes, uint64 &NumberOfFreeBytes)
static const FPlatformDriveStats * GetDriveStats (WIDECHAR DriveLetter)
Retrieve information about a drive, or nullptr if no information is available.
static FString GetEnvironmentVariable (const TCHAR *VariableName)
static FText GetFileManagerName ()
static uint64 GetFileVersion (const FString &FileName)
static struct FGPUDriverInfo GetGPUDriverInfo (const FString &DeviceDescription, bool bVerbose=true)
static FString GetHostArchitecture ()
static uint32 GetLastError ()
static TArray< uint8 > GetMacAddress ()
static int32 GetMaxPathLength ()
static int32 GetMaxRefreshRate ()
static FString GetOperatingSystemId ()
Gets a globally unique ID the represents a particular operating system install.
static FString GetOSVersion ()
static void GetOSVersions (FString &out_OSVersionLabel, FString &out_OSSubVersionLabel)
static bool GetPageFaultStats (FPageFaultStats &OutStats, EPageFaultFlags Flags=EPageFaultFlags::All)
static IPlatformChunkInstall * GetPlatformChunkInstall ()
static const TCHAR * GetPlatformFeaturesModuleName ()
static FString GetPrimaryGPUBrand ()
static EProcessDiagnosticFlags GetProcessDiagnostics ()
static const FProcessorGroupDesc & GetProcessorGroupDesc ()
static bool GetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, FString &OutValue)
static const TCHAR * GetSystemErrorMessage (TCHAR *OutBuffer, int32 BufferCount, int32 Error)
static Windows::HWND GetTopLevelWindowHandle (uint32 ProcessId)
Attempts to get the handle to a top-level window of the specified process.
static bool GetVSComnTools (int32 Version, FString &OutData)
Gets Visual Studio common tools path.
static bool HasActiveWiFiConnection ()
Returns whether WiFi connection is currently active.
static bool HasAVX2InstructionSupport ()
Determines if AVX2 instruction set is supported on this platform.
static bool HasCPUIDInstruction ()
Determines if the cpuid instruction is supported on this processor.
static bool HasNonoptionalCPUFeatures ()
static bool HasSecureBootSupport ()
static bool HasTimedPauseCPUFeature ()
static bool HasTPM2Support ()
static bool Is64bitOperatingSystem ()
static bool IsDebuggerPresent ()
static bool IsLocalPrintThreadSafe ()
static bool IsRemoteSession ()
static bool IsRunningOnBattery ()
Returns whether the platform is running on battery power or not.
static bool IsUsingBatterySaver ()
Returns whether the platform is currently running with battery saver enabled.
static bool IsValidAbsolutePathFormat (const FString &Path)
static bool IsWine ()
Determines if we are running under Wine rather than a real version of Windows.
static void LocalPrint (const TCHAR *Message)
static FORCEINLINE void MemoryBarrier ()
static EAppReturnType::Type MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR *Text, const TCHAR *Caption)
static bool NeedsNonoptionalCPUFeaturesCheck ()
static int32 NumberOfCores ()
static int32 NumberOfCoresIncludingHyperthreads ()
static int32 NumberOfWorkerThreadsToSpawn ()
static bool OsExecute (const TCHAR *CommandType, const TCHAR *Command, const TCHAR *CommandLine=NULL)
Has the OS execute a command and path pair (such as launch a browser)
static void PlatformInit ()
static void PlatformPreInit ()
static void PlatformTearDown ()
static void PromptForRemoteDebugging (bool bIsEnsure)
static void PumpMessagesOutsideMainLoop ()
static bool QueryRegKey (const Windows::HKEY InKey, const TCHAR *InSubKey, const TCHAR *InValueName, FString &OutData)
Provides a simpler interface for fetching and cleanup of registry value queries.
static void RaiseException (uint32 ExceptionCode)
static void RequestExit (bool Force, const TCHAR *CallSite=nullptr)
static void RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR *CallSite=nullptr)
static ECrashHandlingType SetCrashHandlingType (ECrashHandlingType)
static void SetEnvironmentVar (const TCHAR *VariableName, const TCHAR *Value)
static void SetGracefulTerminationHandler ()
static void SetLastError (uint32 ErrorCode)
static bool SetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, const FString &InValue)
static void SetUTF8Output ()
static void SubmitErrorReport (const TCHAR *InErrorHist, EErrorReportMode::Type InMode)
static bool SupportsWindows11 ()
Checks whether this device has the required hardware and software capabilities required to run Windows 11.
static void UpdateDriveFreeSpace ()
Update statistics of free/used bytes on all drives.
static bool VerifyWindowsVersion (uint32 MajorVersion, uint32 MinorVersion, uint32 BuildNumber=0)
Determines if we are running on the Windows version or newer.
Static Public Member Functions inherited from FGenericPlatformMisc
static void AddAdditionalRootDirectory (const FString &RootDir)
add an additional root directory
static FDelegateHandle AddNetworkListener (FOnNetworkConnectionChangedDelegate &&InNewDelegate)
static bool AllowAudioThread ()
Checks if platform wants to allow an audio thread on current device (note: does not imply it will, only if okay given other criteria met)
static bool AllowLocalCaching ()
static bool AllowThreadHeartBeat ()
Checks if platform wants to allow the thread heartbeat hang detection.
static void BeginEnterBackgroundEvent (const TCHAR *Text)
Profiler enter background events.
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const ANSICHAR *Text)
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const TCHAR *Text)
static FORCEINLINE void BeginNamedEventFrame ()
static void CacheLaunchDir ()
Function to store the current working directory for use with LaunchDir()
static bool CheckPersistentDownloadStorageSpaceAvailable (uint64 BytesRequired, bool bAttemptToUseUI)
Ensure that there enough space in the persistent download dir.
static FORCEINLINE void ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat &OutputDevice, EDisplayColorGamut &ColorGamut)
static FString CloudDir ()
Return the CloudDir.
static bool CommandLineCommands ()
Handles Game Explorer, Firewall and FirstInstall commands, typically from the installer.
static void CreateGuid (struct FGuid &Result)
Create a new globally unique identifier.
static FORCEINLINE void CustomNamedStat (const ANSICHAR *Text, float Value, const ANSICHAR *Graph, const ANSICHAR *Unit)
static FORCEINLINE void CustomNamedStat (const TCHAR *Text, float Value, const TCHAR *Graph, const TCHAR *Unit)
static bool DeleteStoredSection (const FString &InStoreId, const FString &InSectionName)
Deletes the given section and its contained values in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DeleteStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName)
Deletes value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DesktopTouchScreen ()
static void DisableScreenTimeout ()
static void EnableScreenTimeout ()
static void EndEnterBackgroundEvent ()
static FORCEINLINE void EndNamedEvent ()
static const TCHAR * EngineDir ()
Get the engine directory.
static void EnsureNetworkIfNecessary ()
static bool Exec (class UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Out)
Platform-specific Exec function.
static FORCEINLINE bool Expand16BitIndicesTo32BitOnLoad ()
static bool FileExistsInPlatformPackage (const FString &RelativePath)
static bool FullscreenSameAsWindowedFullscreen ()
static const TCHAR * GamePersistentDownloadDir ()
Return the GamePersistentDownloadDir.
static const TCHAR * GameTemporaryDownloadDir ()
Return the temporary directory.
static const TCHAR * GeneratedConfigDir ()
static TArray< FString > GetAdditionalRootDirectories ()
get additional directories which can be considered as root directories
static EDeviceScreenOrientation GetAllowedDeviceOrientation ()
Returns the allowed orientation of the device.
static FORCEINLINE int GetBatteryLevel ()
Gets the current battery level.
static bool GetBlockingIOStats (FProcessIOStats &OutStats, EInputOutputFlags Flags=EInputOutputFlags::All)
Gets Blocking Input/Output stats covering the lifetime of the process.
static FORCEINLINE float GetBrightness ()
static FORCEINLINE int32 GetChunkIDFromPakchunkIndex (int32 PakchunkIndex)
static const FString * GetConfigRulesVariable (const FString &Key)
static const class TMap< FString, FString > & GetConfigRuleVars ()
static bool GetContextSwitchStats (FContextSwitchStats &OutStats, EContextSwitchFlags Flags=EContextSwitchFlags::All)
Gets Context Switch stats covering the lifetime of the process.
static EConvertibleLaptopMode GetConvertibleLaptopMode ()
Gets the current mode of convertible laptops, i.e.
static FString GetCPUBrand ()
Uses cpuid instruction to get the CPU brand string.
static FString GetCPUChipset ()
Returns the CPU chipset if known.
static uint32 GetCPUInfo ()
On x86(-64) platforms, uses cpuid instruction to get the CPU signature.
static FString GetCPUVendor ()
Uses cpuid instruction to get the vendor string.
static ECrashHandlingType GetCrashHandlingType ()
Gets the current crash handling type.
static const TCHAR * GetDefaultDeviceProfileName ()
Gets the default profile name.
static FString GetDefaultLanguage ()
Get the default language (for localization) used by this platform.
static FString GetDefaultLocale ()
Get the default locale (for internationalization) used by this platform.
static const TCHAR * GetDefaultPathSeparator ()
static FString GetDeviceId ()
Returns a unique string for device identification.
static FString GetDeviceMakeAndModel ()
static EDeviceScreenOrientation GetDeviceOrientation ()
Returns the current orientation of the device: will be either Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight.
static FString GetDeviceTag ()
Get Device Tag of the device running the session.
static float GetDeviceTemperatureLevel ()
Returns the current device temperature level.
static int32 GetDeviceVolume ()
Returns the device volume if the device is capable of returning that information.
static bool GetDiskTotalAndFreeSpace (const FString &InPath, uint64 &TotalNumberOfBytes, uint64 &NumberOfFreeBytes)
Retrieves information about the total number of bytes and number of free bytes for the specified disk path.
static bool GetEngineAndProjectAbsoluteDirsFromExecutable (FString &OutProjectDir, FString &OutEngineDir)
Return the engine and project directory based from the executable.
static const TCHAR * GetEngineMode ()
Get a string description of the mode the engine was running in.
static FString GetEnvironmentVariable (const TCHAR *VariableName)
Retrieve a environment variable from the system.
static FString GetEpicAccountId ()
Get the Epic account ID for the user who last used the Launcher.
static FText GetFileManagerName ()
static struct FGPUDriverInfo GetGPUDriverInfo (const FString &DeviceDescription)
static FString GetHostArchitecture ()
static FORCEINLINE uint32 GetLastError ()
static FString GetLocalCurrencyCode ()
Returns the currency code associated with the device's locale.
static FString GetLocalCurrencySymbol ()
Returns the currency symbol associated with the device's locale.
static FString GetLoginId ()
Returns a unique string associated with the login account of the current machine.
static FORCEINLINE int32 GetMaxPathLength ()
Returns the maximum length of a path.
static int32 GetMaxRefreshRate ()
retrieves the current maximum refresh rate supported by the platform
static int32 GetMaxSupportedRefreshRate ()
retrieves the maximum refresh rate supported by the platform
static int32 GetMaxSyncInterval ()
Returns the platform's maximum allowed value for rhi.SyncInterval.
static int GetMobilePropagateAlphaSetting ()
static ENetworkConnectionStatus GetNetworkConnectionStatus ()
Returns the current status for the network connection.
static ENetworkConnectionType GetNetworkConnectionType ()
Returns whether WiFi connection is currently active.
static FORCEINLINE void GetNetworkFileCustomData (TMap< FString, FString > &OutCustomPlatformData)
Returns any platform-specific key-value data that needs to be sent to the network file server.
static const TCHAR * GetNullRHIShaderFormat ()
Determines the shader format for the platform.
static FString GetOperatingSystemId ()
Gets a globally unique ID the represents a particular operating system install.
static FString GetOSVersion ()
Gets a string representing the numeric OS version (as opposed to a translated OS version that GetOSVersions returns).
static void GetOSVersions (FString &out_OSVersionLabel, FString &out_OSSubVersionLabel)
Gets the OS Version and OS Subversion.
static bool GetPageFaultStats (FPageFaultStats &OutStats, EPageFaultFlags Flags=EPageFaultFlags::All)
Gets Page Fault stats covering the lifetime of the process.
static int32 GetPakchunkIndexFromPakFile (FStringView InFilename)
static FStringView GetPakFilenamePrefix ()
static const TCHAR * GetPathVarDelimiter ()
return the delimiter between paths in the PATH environment variable.
static FString GetPendingActivationProtocol ()
Returns activation protocol that's waiting to be broadcast.
static IPlatformChunkInstall * GetPlatformChunkInstall ()
Returns the platform specific chunk based install interface.
static IPlatformCompression * GetPlatformCompression ()
Returns the platform specific compression interface.
static const TCHAR * GetPlatformFeaturesModuleName ()
Return the name of the platform features module.
static IPlatformHostCommunication & GetPlatformHostCommunication ()
Returns the platform specific interface for communication with processes running on the host pc.
static bool GetPlatformScreenWarnings (TArray< FText > &PlatformScreenWarnings)
Returns any platform specific warning messages we want printed on screen.
static struct FAsyncIOSystemBase * GetPlatformSpecificAsyncIOSystem ()
Return the platform specific async IO system, or nullptr if the standard one should be used.
static FPlatformUserId GetPlatformUserForUserIndex (int32 LocalUserIndex)
static TArray< FString > GetPreferredLanguages ()
Returns an array of the user's preferred languages in order of preference.
static FString GetPrimaryGPUBrand ()
static EProcessDiagnosticFlags GetProcessDiagnostics ()
Returns non-zero if a performance-sensitive diagnostic, like a memory sanitizer, is detected for this process.
static const FProcessorGroupDesc & GetProcessorGroupDesc ()
static bool GetSHA256Signature (const void *Data, uint32 ByteSize, FSHA256Signature &OutSignature)
Generates the SHA256 signature of the given data.
static bool GetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, FString &OutValue)
Get the value for the given section and key from the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static const TCHAR * GetSystemErrorMessage (TCHAR *OutBuffer, int32 BufferCount, int32 Error)
Returns the last system error code in string form.
static TArray< uint8 > GetSystemFontBytes ()
static FString GetTimeZoneId ()
Get the timezone identifier for this platform, or an empty string if the default timezone calculation will work.
static const TCHAR * GetUBTPlatform ()
static const TCHAR * GetUBTTarget ()
static const TCHAR * GetUBTTargetName ()
static FString GetUniqueAdvertisingId ()
Returns a unique string for advertising identification.
static int32 GetUserIndexForPlatformUser (FPlatformUserId PlatformUser)
static bool GetUseVirtualJoysticks ()
Returns whether the platform wants to use a touch screen for virtual joysticks.
static void GetValidTargetPlatforms (TArray< FString > &TargetPlatformNames)
Return an ordered list of target platforms this runtime can support (ie Android_DXT, Android would mean that it prefers Android_DXT, but can use Android as well)
static const float GetVirtualKeyboardInputHeight ()
static bool GetVolumeButtonsHandledBySystem ()
static bool HasActiveWiFiConnection ()
Returns whether WiFi connection is currently active.
static bool HasMemoryWarningHandler ()
Determines if a warning handler has been set.
static bool HasNonoptionalCPUFeatures ()
static bool HasPlatformFeature (const TCHAR *FeatureName)
Returns whether the given platform feature is currently available (for instance, Metal is only available in IOS8 and with A7 devices)
static bool HasProjectPersistentDownloadDir ()
Return true if the PersistentDownloadDir is available.
static bool HasSeparateChannelForDebugOutput ()
Whether the platform has a separate debug channel to stdout (eg.
static bool HasVariableHardware ()
Returns whether the platform has variable hardware (configurable/upgradeable system).
static void HidePlatformStartupScreen ()
static FORCEINLINE void InitTaggedStorage (uint32 NumTags)
Platform specific function for initializing storage of tagged memory buffers.
static FORCEINLINE bool Is64bitOperatingSystem ()
Detects whether we're running in a 64-bit operating system.
static bool IsCacheStorageAvailable ()
For platforms that support cache storage functionality, setting a directory for it when it's not available can result in errors.
static FORCEINLINE bool IsDebuggerPresent ()
Return true if a debugger is present.
static bool IsEnsureAllowed ()
Allows disabling ensure()s without rebuilding the binary, by either a commandline switch or a hotfix.
static FORCEINLINE bool IsInLowPowerMode ()
static bool IsLocalPrintThreadSafe ()
Whether LocalPrint can be called from any thread without overlapping.
static bool IsLowLevelOutputDebugStringStructured ()
Whether LowLevelOutputDebugString[f] can receive structured output as lines of JSON.
static bool IsPackagedForDistribution ()
static bool IsPGIActive ()
Returns true if PGI (profile-guided instrumentation, needed for PGO) is currently ongoing.
static bool IsPGICapableBinary ()
Returns true if this binary has been instrumented for collection of data needed for profile-guided optimization (PGO) This value is not expected to change during the run-time.
static bool IsPGOEnabled ()
Returns true if PGO is currently enabled.
static bool IsRegisteredForRemoteNotifications ()
Returns whether or not the device has been registered to receive remote notifications.
static bool IsRemoteSession ()
Check to see if the platform is being viewed remotely.
static bool IsRunningInCloud ()
Return if the game is running on cloud server.
static bool IsRunningOnBattery ()
Returns whether the platform is running on battery power or not.
static bool IsValidAbsolutePathFormat (const FString &Path)
Checks structure of the path against platform formatting requirements.
static const TCHAR * LaunchDir ()
Get the directory the application was launched from (useful for commandline utilities)
static FString LoadTextFileFromPlatformPackage (const FString &RelativePath)
Loads a text file relative to the package root on platforms that distribute apps in package formats.
static void LocalPrint (const TCHAR *Str)
Prints string to the default output.
static void LogNameEventStatsInit ()
static void LowLevelOutputDebugString (const TCHAR *Message)
Sends a message to a remote tool, and debugger consoles.
static void VARARGS LowLevelOutputDebugStringf (const TCHAR *Format,...)
static FORCENOINLINE void MemoryBarrier ()
Enforces strict memory load/store ordering across the memory barrier call.
static EAppReturnType::Type MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR *Text, const TCHAR *Caption)
Show a message box if possible, otherwise print a message and return the default.
static bool NeedsNonoptionalCPUFeaturesCheck ()
static void NormalizePath (FString &InPath)
Platform-specific normalization of path E.g.
static void NormalizePath (FStringBuilderBase &InPath)
Platform-specific normalization of path E.g.
static int32 NumberOfCores ()
return the number of hardware CPU cores
static int32 NumberOfCoresIncludingHyperthreads ()
return the number of logical CPU cores
static int32 NumberOfIOWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn to service IO, NOT based on number of cores.
static int32 NumberOfWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn, based on number of cores.
static bool OsExecute (const TCHAR *CommandType, const TCHAR *Command, const TCHAR *CommandLine=NULL)
Has the OS execute a command and path pair (such as launch a browser)
static void ParseChunkIdPakchunkIndexMapping (TArray< FString > ChunkIndexRedirects, TMap< int32, int32 > &OutMapping)
static void PlatformHandleSplashScreen (bool ShowSplashScreen=false)
Called to dismiss splash screen.
static void PlatformInit ()
static void PlatformPreInit ()
Called during appInit() after cmd line setup.
static void PlatformTearDown ()
Called during AppExit().
static FORCEINLINE void Prefetch (const void *Ptr)
static FORCEINLINE void Prefetch (const void *Ptr, int32 Offset)
static FORCEINLINE void PrefetchBlock (const void *Ptr, int32 NumBytes)
static void PrepareMobileHaptics (EMobileHapticsType Type)
For mobile devices, this will crank up a haptic engine for the specified type to be played later with TriggerMobileHaptics If this is called again before Release, it will switch to this type.
static const TCHAR * ProjectDir ()
Return the project directory.
static void PromptForRemoteDebugging (bool bIsEnsure)
static void PumpEssentialAppMessages ()
Pumps app messages only if there are essential keep-alive messages pending.
static void PumpMessagesForSlowTask ()
static void PumpMessagesOutsideMainLoop ()
static void RaiseException (uint32 ExceptionCode)
static void RegisterForRemoteNotifications ()
Requests permission to send remote notifications to the user's device.
static void ReleaseMobileHaptics ()
For mobile devices, this will shutdown the haptics, allowing system to put it to reset as needed.
static bool RemoveNetworkListener (FDelegateHandle Handle)
static bool RequestDeviceCheckToken (TFunction< void(const TArray< uint8 > &)> QuerySucceededFunc, TFunction< void(const FString &, const FString &)> QueryFailedFunc)
static void RequestExit (bool Force, const TCHAR *CallSite=nullptr)
Requests application exit.
static void RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR *CallSite=nullptr)
Requests application exit with a specified return code.
static bool RestartApplication ()
Requests application to restart.
static bool RestartApplicationWithCmdLine (const char *CmdLine)
Requests application to restart appending the passed in CmdLine to the restart.
static const TCHAR * RootDir ()
Get the application root directory.
static void SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation)
Change the allowed orientation of the device.
static FORCEINLINE void SetBrightness (float bBright)
static void SetCrashHandler (void(*CrashHandler)(const FGenericCrashContext &Context))
Installs handler for the unexpected (due to error) termination of the program, including, but not limited to, crashes.
static ECrashHandlingType SetCrashHandlingType (ECrashHandlingType Type)
Sets the type of crash handling done by the engine.
static void SetEnvironmentVar (const TCHAR *VariableName, const TCHAR *Value)
Sets an environment variable to the local process's environment.
static void SetGracefulTerminationHandler ()
Set/restore the Console Interrupt (Control-C, Control-Break, Close) handler.
static void SetLastError (uint32 ErrorCode)
static void SetMemoryWarningHandler (void(*Handler)(const FGenericMemoryWarningContext &Context))
Set a handler to be called when there is a memory warning from the OS.
static void SetNetworkConnectionStatus (ENetworkConnectionStatus NewNetworkConnectionStatus)
Updates the current status for the network connection.
static void SetOverrideProjectDir (const FString &InOverrideDir)
Allows a game/program/etc to control the game directory in a special place (for instance, monolithic programs that don't have .uprojects)
static void SetShouldPromptForRemoteDebugging (bool bInShouldPrompt)
static void SetShouldPromptForRemoteDebugOnEnsure (bool bInShouldPrompt)
static bool SetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, const FString &InValue)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool SetStoredValues (const FString &InStoreId, const FString &InSectionName, const TMap< FString, FString > &InKeyValues)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static void SetUBTTargetName (const TCHAR *InTargetName)
static bool SetupSyscallFilters ()
static void SetUTF8Output ()
Sets the default output to UTF8.
static void SetVolumeButtonsHandledBySystem (bool enabled)
static void ShareURL (const FString &URL, const FText &Description, int32 LocationHintX, int32 LocationHintY)
Perform a mobile-style sharing of a URL.
static bool ShouldDisablePluginAtRuntime (const FString &PluginName)
Allows platform at runtime to disable unsupported plugins.
static bool ShouldDisplayTouchInterfaceOnFakingTouchEvents ()
static void ShowConsoleWindow ()
static FORCEINLINE void ShutdownTaggedStorage ()
Platform specific function for freeing storage of tagged memory buffers.
static bool StartNewPGOCollection (const FString &AbsoluteFileName)
On platforms that support run-time PGI on/off, starts a new collection with a given file name.
template<typename CharType>
static void StatNamedEvent (const CharType *Text)
Stats logging for named event.
static bool StopPGOCollectionAndCloseFile ()
On platforms that support run-time PGI on/off, stops the current collection and writes out the file (or completes its write).
static void SubmitErrorReport (const TCHAR *InErrorHist, EErrorReportMode::Type InMode)
Submits a crash report to a central server (release builds only)
static FORCEINLINE bool SupportsBackbufferSampling ()
static FORCEINLINE bool SupportsBrightness ()
static bool SupportsDeviceCheckToken ()
static bool SupportsForceTouchInput ()
static bool SupportsFullCrashDumps ()
Platform can generate a full-memory crashdump during crash handling.
static bool SupportsLocalCaching ()
static bool SupportsMessaging ()
static bool SupportsMultithreadedFileHandles ()
static bool SupportsTouchInput ()
static FORCEINLINE void TagBuffer (const char *Label, uint32 Category, const void *Buffer, size_t BufferSize)
Platform specific function for tagging a memory buffer with a label.
static void TearDown ()
Frees any memory retained by FGenericPlatformMisc.
static void TickHotfixables ()
Ticks values that can be hotfixable in the config.
static void TickStatNamedEvents ()
static void TriggerMobileHaptics ()
For mobile devices, this will kick the haptic type that was set in PrepareMobileHaptics.
static void UnregisterForRemoteNotifications ()
Requests unregistering from receiving remote notifications on the user's device.
static void UpdateHotfixableEnsureSettings ()
Updates hotfixable ensure settings from config and commandline (config takes priority).
static FORCEINLINE bool UseHDRByDefault ()
static bool UseRenderThread ()
Checks if platform wants to use a rendering thread on current device.
static const FString VersionCheckPlatformName ()
static bool WasLaunchedStreaming ()
Return true if the game is being streamed to a separate client device.
Data Fields
TCHAR * Result
TCHAR int32 ResultLength
Additional Inherited Members
Static Protected Member Functions inherited from FGenericPlatformMisc
static void GetConfiguredCoreLimits (int32 PlatformNumPhysicalCores, int32 PlatformNumLogicalCores, bool &bOutFullyInitialized, int32 &OutPhysicalCoreLimit, int32 &OutLogicalCoreLimit, bool &bOutSetPhysicalCountToLogicalCount)
Parse CoreLimit from CommandLine or from the SetCoreLimit value.
Static Protected Attributes inherited from FGenericPlatformMisc
static EDeviceScreenOrientation AllowedDeviceOrientation
static bool bPromptForRemoteDebugOnEnsure
Whether the user should be prompted to allow for a remote debugger to be attached on an ensure.
static bool bShouldPromptForRemoteDebugging
Whether the user should be prompted to allow for a remote debugger to be attached.
static ENetworkConnectionStatus CurrentNetworkConnectionStatus
Detailed Description
Windows implementation of the misc OS functions.
Definition at line 96 of file WindowsPlatformMisc.h.
Member Function Documentation
AsymmetricThreadFenceHeavy()
void FWindowsPlatformMisc::AsymmetricThreadFenceHeavy () static
AsymmetricThreadFenceLight()
FORCEINLINE void FWindowsPlatformMisc::AsymmetricThreadFenceLight () inline static
Definition at line 133 of file WindowsPlatformMisc.h.
References FORCEINLINE.
CallGracefulTerminationHandler()
void FWindowsPlatformMisc::CallGracefulTerminationHandler () static
ChooseHDRDeviceAndColorGamut()
FORCEINLINE void FWindowsPlatformMisc::ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat & OutputDevice, EDisplayColorGamut & ColorGamut) inline static
Definition at line 346 of file WindowsPlatformMisc.h.
References FORCEINLINE, HDR_ACES_1000nit_ScRGB, HDR_ACES_1000nit_ST2084, HDR_ACES_2000nit_ScRGB, HDR_ACES_2000nit_ST2084, Rec2020_D65, and sRGB_D65.
CoInitialize()
bool FWindowsPlatformMisc::CoInitialize (ECOMModel Model = ECOMModel::Singlethreaded) static
References Singlethreaded.
CommandLineCommands()
bool FWindowsPlatformMisc::CommandLineCommands () static
CoUninitialize()
void FWindowsPlatformMisc::CoUninitialize () static
CreateGuid()
void FWindowsPlatformMisc::CreateGuid (struct FGuid & Result) static
References Result.
DeleteStoredSection()
bool FWindowsPlatformMisc::DeleteStoredSection (const FString & InStoreId, const FString & InSectionName) static
DeleteStoredValue()
bool FWindowsPlatformMisc::DeleteStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName) static
GetBatteryLevel()
int FWindowsPlatformMisc::GetBatteryLevel () static
Returns the current battery level between 0 and 100, or -1 if a battery is not present or if the current battery level cannot be retrieved.
GetBlockingIOStats()
bool FWindowsPlatformMisc::GetBlockingIOStats (FProcessIOStats & OutStats, EInputOutputFlags Flags = EInputOutputFlags::All) static
References All, and Flags.
GetConvertibleLaptopMode()
EConvertibleLaptopMode FWindowsPlatformMisc::GetConvertibleLaptopMode () static
GetCPUBrand()
FString FWindowsPlatformMisc::GetCPUBrand () static
GetCPUInfo()
uint32 FWindowsPlatformMisc::GetCPUInfo () static
Uses cpuid instruction to get the vendor string.
Returns
CPU info bitfield
    Bits 0-3    Stepping ID
    Bits 4-7    Model
    Bits 8-11   Family
    Bits 12-13  Processor type (Intel) / Reserved (AMD)
    Bits 14-15  Reserved
    Bits 16-19  Extended model
    Bits 20-27  Extended family
    Bits 28-31  Reserved
GetCPUVendor()
FString FWindowsPlatformMisc::GetCPUVendor () static
GetCrashHandlingType()
ECrashHandlingType FWindowsPlatformMisc::GetCrashHandlingType () static
GetDefaultLanguage()
FString FWindowsPlatformMisc::GetDefaultLanguage () static
GetDefaultLocale()
FString FWindowsPlatformMisc::GetDefaultLocale () static
GetDefaultPathSeparator()
const TCHAR * FWindowsPlatformMisc::GetDefaultPathSeparator () static
Returns
Windows path separator.
References GetDefaultPathSeparator().
Referenced by GetDefaultPathSeparator().
GetDiskTotalAndFreeSpace()
bool FWindowsPlatformMisc::GetDiskTotalAndFreeSpace (const FString & InPath, uint64 & TotalNumberOfBytes, uint64 & NumberOfFreeBytes) static
GetDriveStats()
const FPlatformDriveStats * FWindowsPlatformMisc::GetDriveStats (WIDECHAR DriveLetter) static
Retrieve information about a drive, or nullptr if no information is available.
GetEnvironmentVariable()
FString FWindowsPlatformMisc::GetEnvironmentVariable (const TCHAR * VariableName) static
References GetEnvironmentVariable().
Referenced by GetEnvironmentVariable().
GetFileManagerName()
FText FWindowsPlatformMisc::GetFileManagerName () static
Returns
Get the name of the platform specific file manager (Explorer)
References GetFileManagerName().
Referenced by GetFileManagerName().
GetFileVersion()
uint64 FWindowsPlatformMisc::GetFileVersion (const FString & FileName) static
GetGPUDriverInfo()
struct FGPUDriverInfo FWindowsPlatformMisc::GetGPUDriverInfo (const FString & DeviceDescription, bool bVerbose = true) static
References GetGPUDriverInfo().
Referenced by GetGPUDriverInfo().
GetHostArchitecture()
FString FWindowsPlatformMisc::GetHostArchitecture () static
Returns
architecture of the host machine (x64, arm64)
GetLastError()
uint32 FWindowsPlatformMisc::GetLastError () static
GetMacAddress()
TArray< uint8 > FWindowsPlatformMisc::GetMacAddress () static
References GetMacAddress().
Referenced by GetMacAddress().
GetMaxPathLength()
int32 FWindowsPlatformMisc::GetMaxPathLength () static
GetMaxRefreshRate()
int32 FWindowsPlatformMisc::GetMaxRefreshRate () static
GetOperatingSystemId()
FString FWindowsPlatformMisc::GetOperatingSystemId () static
Gets a globally unique ID the represents a particular operating system install.
GetOSVersion()
FString FWindowsPlatformMisc::GetOSVersion () static
GetOSVersions()
void FWindowsPlatformMisc::GetOSVersions (FString & out_OSVersionLabel, FString & out_OSSubVersionLabel) static
GetPageFaultStats()
bool FWindowsPlatformMisc::GetPageFaultStats (FPageFaultStats & OutStats, EPageFaultFlags Flags = EPageFaultFlags::All) static
References All, and Flags.
GetPlatformChunkInstall()
IPlatformChunkInstall * FWindowsPlatformMisc::GetPlatformChunkInstall () static
GetPlatformFeaturesModuleName()
const TCHAR * FWindowsPlatformMisc::GetPlatformFeaturesModuleName () static
GetPrimaryGPUBrand()
FString FWindowsPlatformMisc::GetPrimaryGPUBrand () static
GetProcessDiagnostics()
EProcessDiagnosticFlags FWindowsPlatformMisc::GetProcessDiagnostics () static
GetProcessorGroupDesc()
const FProcessorGroupDesc & FWindowsPlatformMisc::GetProcessorGroupDesc () static
GetStoredValue()
bool FWindowsPlatformMisc::GetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, FString & OutValue) static
GetSystemErrorMessage()
const TCHAR * FWindowsPlatformMisc::GetSystemErrorMessage (TCHAR * OutBuffer, int32 BufferCount, int32 Error) static
References Error.
GetTopLevelWindowHandle()
Windows::HWND FWindowsPlatformMisc::GetTopLevelWindowHandle (uint32 ProcessId) static
Attempts to get the handle to a top-level window of the specified process.
If the process has a single main window (root), its handle will be returned. If the process has multiple top-level windows, the first one found is returned.
Parameters
ProcessId The identifier of the process to get the window for.
Returns
Window handle, or 0 if not found.
GetVSComnTools()
bool FWindowsPlatformMisc::GetVSComnTools (int32 Version, FString & OutData) static
Gets Visual Studio common tools path.
Parameters
Version Version of VS to get (11 - 2012, 12 - 2013).
OutData Output parameter with common tools path.
Returns
Returns if succeeded.
HasActiveWiFiConnection()
bool FWindowsPlatformMisc::HasActiveWiFiConnection () inline static
Returns whether WiFi connection is currently active.
Definition at line 325 of file WindowsPlatformMisc.h.
References HasActiveWiFiConnection().
Referenced by HasActiveWiFiConnection().
HasAVX2InstructionSupport()
bool FWindowsPlatformMisc::HasAVX2InstructionSupport () static
Determines if AVX2 instruction set is supported on this platform.
Returns
Returns true if instruction-set is supported
HasCPUIDInstruction()
bool FWindowsPlatformMisc::HasCPUIDInstruction () static
Determines if the cpuid instruction is supported on this processor.
Returns
Returns true if cpuid is supported
HasNonoptionalCPUFeatures()
bool FWindowsPlatformMisc::HasNonoptionalCPUFeatures () static
Returns
whether this cpu supports certain required instructions or not
HasSecureBootSupport()
bool FWindowsPlatformMisc::HasSecureBootSupport () static
HasTimedPauseCPUFeature()
bool FWindowsPlatformMisc::HasTimedPauseCPUFeature () static
Returns
whether this cpu has timed pause instruction support or not
HasTPM2Support()
bool FWindowsPlatformMisc::HasTPM2Support () static
Is64bitOperatingSystem()
bool FWindowsPlatformMisc::Is64bitOperatingSystem () static
IsDebuggerPresent()
bool FWindowsPlatformMisc::IsDebuggerPresent () static
Referenced by IsLocalPrintThreadSafe().
IsLocalPrintThreadSafe()
bool FWindowsPlatformMisc::IsLocalPrintThreadSafe () inline static
Definition at line 143 of file WindowsPlatformMisc.h.
References IsDebuggerPresent().
IsRemoteSession()
bool FWindowsPlatformMisc::IsRemoteSession () static
IsRunningOnBattery()
bool FWindowsPlatformMisc::IsRunningOnBattery () static
Returns whether the platform is running on battery power or not.
For Windows laptops this is true regardless of charging state.
IsUsingBatterySaver()
bool FWindowsPlatformMisc::IsUsingBatterySaver () static
Returns whether the platform is currently running with battery saver enabled.
IsValidAbsolutePathFormat()
bool FWindowsPlatformMisc::IsValidAbsolutePathFormat (const FString & Path) static
References Path.
IsWine()
bool FWindowsPlatformMisc::IsWine () static
Determines if we are running under Wine rather than a real version of Windows.
Returns
Returns true if the current runtime environment is Wine
LocalPrint()
void FWindowsPlatformMisc::LocalPrint (const TCHAR * Message) static
MemoryBarrier()
FORCEINLINE void FWindowsPlatformMisc::MemoryBarrier () inline static
Definition at line 122 of file WindowsPlatformMisc.h.
References FORCEINLINE.
MessageBoxExt()
EAppReturnType::Type FWindowsPlatformMisc::MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR * Text, const TCHAR * Caption) static
References Caption, and Text.
NeedsNonoptionalCPUFeaturesCheck()
bool FWindowsPlatformMisc::NeedsNonoptionalCPUFeaturesCheck () static
Returns
whether to check for specific CPU compatibility or not
NumberOfCores()
int32 FWindowsPlatformMisc::NumberOfCores () static
NumberOfCoresIncludingHyperthreads()
int32 FWindowsPlatformMisc::NumberOfCoresIncludingHyperthreads () static
NumberOfWorkerThreadsToSpawn()
int32 FWindowsPlatformMisc::NumberOfWorkerThreadsToSpawn () static
OsExecute()
bool FWindowsPlatformMisc::OsExecute (const TCHAR * CommandType, const TCHAR * Command, const TCHAR * CommandLine = NULL) static
Has the OS execute a command and path pair (such as launch a browser)
Parameters
ComandType OS hint as to the type of command
Command the command to execute
CommandLine the commands to pass to the executable
Returns
whether the command was successful or not
PlatformInit()
void FWindowsPlatformMisc::PlatformInit () static
PlatformPreInit()
void FWindowsPlatformMisc::PlatformPreInit () static
PlatformTearDown()
void FWindowsPlatformMisc::PlatformTearDown () static
PromptForRemoteDebugging()
void FWindowsPlatformMisc::PromptForRemoteDebugging (bool bIsEnsure) static
PumpMessagesOutsideMainLoop()
void FWindowsPlatformMisc::PumpMessagesOutsideMainLoop () static
QueryRegKey()
bool FWindowsPlatformMisc::QueryRegKey (const Windows::HKEY InKey, const TCHAR * InSubKey, const TCHAR * InValueName, FString & OutData) static
Provides a simpler interface for fetching and cleanup of registry value queries.
Parameters
InKey The Key (folder) in the registry to search under
InSubKey The Sub Key (folder) within the main Key to look for
InValueName The Name of the Value (file) withing the Sub Key to look for
OutData The Data entered into the Value
Returns
true, if it successfully found the Value
RaiseException()
void FWindowsPlatformMisc::RaiseException (uint32 ExceptionCode) static
RequestExit()
void FWindowsPlatformMisc::RequestExit (bool Force, const TCHAR * CallSite = nullptr) static
References Force.
RequestExitWithStatus()
void FWindowsPlatformMisc::RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR * CallSite = nullptr) static
References Force.
SetCrashHandlingType()
ECrashHandlingType FWindowsPlatformMisc::SetCrashHandlingType (ECrashHandlingType) static
SetEnvironmentVar()
void FWindowsPlatformMisc::SetEnvironmentVar (const TCHAR * VariableName, const TCHAR * Value) static
References SetEnvironmentVar(), and Value.
Referenced by SetEnvironmentVar().
SetGracefulTerminationHandler()
void FWindowsPlatformMisc::SetGracefulTerminationHandler () static
SetLastError()
void FWindowsPlatformMisc::SetLastError (uint32 ErrorCode) static
SetStoredValue()
bool FWindowsPlatformMisc::SetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, const FString & InValue) static
SetUTF8Output()
void FWindowsPlatformMisc::SetUTF8Output () static
SubmitErrorReport()
void FWindowsPlatformMisc::SubmitErrorReport (const TCHAR * InErrorHist, EErrorReportMode::Type InMode) static
References SubmitErrorReport().
Referenced by SubmitErrorReport().
SupportsWindows11()
bool FWindowsPlatformMisc::SupportsWindows11 () static
Checks whether this device has the required hardware and software capabilities required to run Windows 11.
Returns
True if the Windows 11 min spec is met.
UE_DEPRECATED() [1/2]
FWindowsPlatformMisc::UE_DEPRECATED (4. 21, "void FPlatformMisc::GetEnvironmentVariable(Name, Result, Length) is deprecated. Use FString FPlatformMisc::GetEnvironmentVariable(Name) instead.") const
UE_DEPRECATED() [2/2]
FWindowsPlatformMisc::UE_DEPRECATED (5. 2, "Please use PLATFORM_CACHE_LINE_SIZE instead, runtime query of cache line size not supported")
UpdateDriveFreeSpace()
void FWindowsPlatformMisc::UpdateDriveFreeSpace () static
Update statistics of free/used bytes on all drives.
VerifyWindowsVersion()
bool FWindowsPlatformMisc::VerifyWindowsVersion (uint32 MajorVersion, uint32 MinorVersion, uint32 BuildNumber = 0) static
Determines if we are running on the Windows version or newer.
See the 'Remarks' section of https://msdn.microsoft.com/en-us/library/windows/desktop/ms724833(v=vs.85).aspx for a list of MajorVersion/MinorVersion version combinations for Microsoft Windows.
Returns
Returns true if the current Windows version if equal or newer than MajorVersion
Field Documentation
Result
TCHAR* FWindowsPlatformMisc::Result
Definition at line 109 of file WindowsPlatformMisc.h.
Referenced by CreateGuid().
ResultLength
TCHAR int32 FWindowsPlatformMisc::ResultLength
Definition at line 109 of file WindowsPlatformMisc.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Windows/WindowsPlatformMisc.h