Unreal Engine 5.6 C++ API: FDFVector4 Struct Reference
FDFVector4 Struct Reference
#include "DoubleFloat.h"
Public Member Functions
FDFVector4 ()=default
template<typename TInputScalar = double>
FDFVector4 (const UE::Math::TVector4< TInputScalar > &In)
template<typename TInputScalar = double>
FDFVector4 (const UE::Math::TVector< TInputScalar > &In, TInputScalar InW)
FDFVector4 (FVector4f High, FVector4f Low)
FVector4d GetVector4d () const
FDFScalar W () const
FDFScalar X () const
FDFScalar Y () const
FDFScalar Z () const
Data Fields
FVector4f High {}
FVector4f Low {}
Detailed Description
Definition at line 116 of file DoubleFloat.h.
Constructor & Destructor Documentation
FDFVector4() [1/4]
template<typename TInputScalar = double> FDFVector4::FDFVector4 (const UE::Math::TVector4< TInputScalar > & In) inline explicit
Definition at line 124 of file DoubleFloat.h.
References High, Low, W(), UE::Math::TVector4< T >::W, X(), UE::Math::TVector4< T >::X, Y(), UE::Math::TVector4< T >::Y, Z(), and UE::Math::TVector4< T >::Z.
FDFVector4() [2/4]
template<typename TInputScalar = double> FDFVector4::FDFVector4 (const UE::Math::TVector< TInputScalar > & In, TInputScalar InW) inline explicit
Definition at line 135 of file DoubleFloat.h.
References High, Low, W(), X(), UE::Math::TVector< T >::X, Y(), UE::Math::TVector< T >::Y, Z(), and UE::Math::TVector< T >::Z.
FDFVector4() [3/4]
FDFVector4::FDFVector4 (FVector4f High, FVector4f Low) inline
Definition at line 145 of file DoubleFloat.h.
References High, and Low.
FDFVector4() [4/4]
FDFVector4::FDFVector4 () default
Member Function Documentation
GetVector4d()
FVector4d FDFVector4::GetVector4d () const inline nodiscard
Definition at line 118 of file DoubleFloat.h.
References FDFScalar::GetDouble(), W(), X(), Y(), and Z().
W()
FDFScalar FDFVector4::W () const inline nodiscard
Definition at line 166 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector4(), FDFVector4(), and GetVector4d().
X()
FDFScalar FDFVector4::X () const inline nodiscard
Definition at line 151 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector4(), FDFVector4(), and GetVector4d().
Y()
FDFScalar FDFVector4::Y () const inline nodiscard
Definition at line 156 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector4(), FDFVector4(), and GetVector4d().
Z()
FDFScalar FDFVector4::Z () const inline nodiscard
Definition at line 161 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector4(), FDFVector4(), and GetVector4d().
Field Documentation
High
FVector4f FDFVector4::High {}
Definition at line 171 of file DoubleFloat.h.
Referenced by FDFVector4(), FDFVector4(), FDFVector4(), W(), X(), Y(), and Z().
Low
FVector4f FDFVector4::Low {}
Definition at line 172 of file DoubleFloat.h.
Referenced by FDFVector4(), FDFVector4(), FDFVector4(), W(), X(), Y(), and Z().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/DoubleFloat.h