Unreal Engine 5.6 C++ API: FReferenceCollector::AROPrivate Struct Reference
FReferenceCollector::AROPrivate Struct Reference final
#include "UObjectGlobals.h"
Static Public Member Functions
template<class UObjectType>
static void AddReferencedObject (FReferenceCollector &Coll, const UObjectType *&Object, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<class UObjectType>
static void AddReferencedObject (FReferenceCollector &Coll, UObjectType *&Object, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
static void AddReferencedObjects (FReferenceCollector &Coll, const UScriptStruct *&ScriptStruct, void *Instance, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<class UObjectType>
static void AddReferencedObjects (FReferenceCollector &Coll, TArray< const UObjectType * > &ObjectArray, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to an array of const objects, these objects can still be nulled out if forcefully collected.
template<class UObjectType>
static void AddReferencedObjects (FReferenceCollector &Coll, TArray< UObjectType * > &ObjectArray, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
static void AddReferencedObjects (FReferenceCollector &Coll, TMapBase< KeyType *, ValueType *, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
static void AddReferencedObjects (FReferenceCollector &Coll, TMapBase< KeyType *, ValueType, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
static void AddReferencedObjects (FReferenceCollector &Coll, TMapBase< KeyType, ValueType *, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<class UObjectType>
static void AddReferencedObjects (FReferenceCollector &Coll, TSet< UObjectType * > &ObjectSet, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Detailed Description
Definition at line 2887 of file UObjectGlobals.h.
Member Function Documentation
AddReferencedObject() [1/2]
template<class UObjectType> void FReferenceCollector::AROPrivate::AddReferencedObject (FReferenceCollector & Coll, const UObjectType *& Object, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Definition at line 2900 of file UObjectGlobals.h.
References FReferenceCollector::HandleObjectReference(), and Object.
AddReferencedObject() [2/2]
template<class UObjectType> void FReferenceCollector::AROPrivate::AddReferencedObject (FReferenceCollector & Coll, UObjectType *& Object, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Definition at line 2890 of file UObjectGlobals.h.
References FReferenceCollector::HandleObjectReference(), and Object.
Referenced by FReferenceCollector::AddReferencedObject(), and FReferenceCollector::AddReferencedObject().
AddReferencedObjects() [1/7]
void FReferenceCollector::AROPrivate::AddReferencedObjects (FReferenceCollector & Coll, const UScriptStruct *& ScriptStruct, void * Instance, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) static
References Instance, and ScriptStruct.
AddReferencedObjects() [2/7]
template<class UObjectType> void FReferenceCollector::AROPrivate::AddReferencedObjects (FReferenceCollector & Coll, TArray< const UObjectType * > & ObjectArray, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Adds references to an array of const objects, these objects can still be nulled out if forcefully collected.
Parameters
ObjectArray Referenced objects array.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2930 of file UObjectGlobals.h.
References TArray< InElementType, InAllocatorType >::GetData(), FReferenceCollector::HandleObjectReferences(), TArray< InElementType, InAllocatorType >::Num(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [3/7]
template<class UObjectType> void FReferenceCollector::AROPrivate::AddReferencedObjects (FReferenceCollector & Coll, TArray< UObjectType * > & ObjectArray, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Definition at line 2912 of file UObjectGlobals.h.
References TArray< InElementType, InAllocatorType >::GetData(), FReferenceCollector::HandleObjectReferences(), TArray< InElementType, InAllocatorType >::Num(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
Referenced by FReferenceCollector::AddReferencedObjects(), FReferenceCollector::AddReferencedObjects(), FReferenceCollector::AddReferencedObjects(), FReferenceCollector::AddReferencedObjects(), FReferenceCollector::AddReferencedObjects(), and FReferenceCollector::AddReferencedObjects().
AddReferencedObjects() [4/7]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AROPrivate::AddReferencedObjects (FReferenceCollector & Coll, TMapBase< KeyType *, ValueType *, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Definition at line 2983 of file UObjectGlobals.h.
References FReferenceCollector::HandleObjectReference(), Map, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [5/7]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AROPrivate::AddReferencedObjects (FReferenceCollector & Coll, TMapBase< KeyType *, ValueType, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Definition at line 2955 of file UObjectGlobals.h.
References FReferenceCollector::HandleObjectReference(), Map, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [6/7]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AROPrivate::AddReferencedObjects (FReferenceCollector & Coll, TMapBase< KeyType, ValueType *, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Definition at line 2969 of file UObjectGlobals.h.
References FReferenceCollector::HandleObjectReference(), Map, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [7/7]
template<class UObjectType> void FReferenceCollector::AROPrivate::AddReferencedObjects (FReferenceCollector & Coll, TSet< UObjectType * > & ObjectSet, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline static
Definition at line 2941 of file UObjectGlobals.h.
References FReferenceCollector::HandleObjectReference(), Object, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectGlobals.h