Unreal Engine 5.6 C++ API: FHairCardsDeformedResource Struct Reference
FHairCardsDeformedResource Struct Reference
#include "GroomResources.h"
Public Types
enum EFrameType { Previous , Current }
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
FHairCardsDeformedResource (const FHairCardsBulkData &BulkData, bool bInitializeData, const FHairResourceName &ResourceName, const FName &OwnerName)
Build the hair strands resource.
FRDGExternalBuffer & GetBuffer (EFrameType T)
virtual FString GetFriendlyName () const override
uint32 GetIndex (EFrameType T)
uint32 GetResourcesSize () const
virtual void InternalAllocate (FRDGBuilder &GraphBuilder) override
virtual void InternalRelease () override
Public Member Functions inherited from FHairCommonResource
FHairCommonResource (EHairStrandsAllocationType AllocationType, const FHairResourceName &InResourceName, const FName &InOwnerName, bool bUseRenderGraph=true)
Build the hair strands resource.
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status, uint32 InRequestedCurveCount, uint32 InRequestedPointCount, bool bAllowDeallocation=true)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void InternalAllocate ()
virtual void InternalAllocate (FRDGBuilder &GraphBuilder, uint32 InCurveCount, uint32 InPointCount)
virtual FHairStrandsBulkCommon * InternalGetBulkData ()
virtual bool InternalGetOrRequestData (uint32 InRequestedCurveCount, uint32 InRequestedPointCount)
virtual void InternalResetLoadedSize ()
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void StreamInData ()
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
const bool bInitializedData = false
const FHairCardsBulkData & BulkData
FRDGExternalBuffer DeformedNormalBuffer
FRDGExternalBuffer DeformedPositionBuffer [2]
Data Fields inherited from FHairCommonResource
EHairStrandsAllocationType AllocationType = EHairStrandsAllocationType::Deferred
bool bIsInitialized = false
bool bUseRenderGraph = true
uint32 MaxAvailableCurveCount = HAIR_MAX_NUM_CURVE_PER_GROUP
FName OwnerName
FHairResourceName ResourceName
FHairStreamingRequest StreamingRequest
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Additional Inherited Members
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 762 of file GroomResources.h.
Member Enumeration Documentation
EFrameType
enum FHairCardsDeformedResource::EFrameType
Enumerator
Previous
Current
Definition at line 793 of file GroomResources.h.
Constructor & Destructor Documentation
FHairCardsDeformedResource()
FHairCardsDeformedResource::FHairCardsDeformedResource (const FHairCardsBulkData & BulkData, bool bInitializeData, const FHairResourceName & ResourceName, const FName & OwnerName)
Build the hair strands resource.
References BulkData, FHairCommonResource::OwnerName, and FHairCommonResource::ResourceName.
Member Function Documentation
GetBuffer()
FRDGExternalBuffer & FHairCardsDeformedResource::GetBuffer (EFrameType T) inline
Definition at line 801 of file GroomResources.h.
References DeformedPositionBuffer, and GetIndex().
GetFriendlyName()
virtual FString FHairCardsDeformedResource::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FRenderResource.
Definition at line 772 of file GroomResources.h.
References TEXT.
GetIndex()
uint32 FHairCardsDeformedResource::GetIndex (EFrameType T) inline
Definition at line 800 of file GroomResources.h.
References Current.
Referenced by GetBuffer().
GetResourcesSize()
uint32 FHairCardsDeformedResource::GetResourcesSize () const inline
Definition at line 775 of file GroomResources.h.
References DeformedPositionBuffer, and GetBufferTotalNumBytes().
InternalAllocate()
virtual void FHairCardsDeformedResource::InternalAllocate (FRDGBuilder & GraphBuilder) override virtual
Reimplemented from FHairCommonResource.
InternalRelease()
virtual void FHairCardsDeformedResource::InternalRelease () override virtual
Reimplemented from FHairCommonResource.
Field Documentation
bInitializedData
const bool FHairCardsDeformedResource::bInitializedData = false
Definition at line 791 of file GroomResources.h.
BulkData
const FHairCardsBulkData& FHairCardsDeformedResource::BulkData
Definition at line 788 of file GroomResources.h.
Referenced by FHairCardsDeformedResource().
DeformedNormalBuffer
FRDGExternalBuffer FHairCardsDeformedResource::DeformedNormalBuffer
Definition at line 785 of file GroomResources.h.
DeformedPositionBuffer
FRDGExternalBuffer FHairCardsDeformedResource::DeformedPositionBuffer[2]
Definition at line 784 of file GroomResources.h.
Referenced by GetBuffer(), and GetResourcesSize().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/GroomResources.h