Unreal Engine 5.6 C++ API: TMovieSceneInterrogationIterator< DataType > Struct Template Reference
TMovieSceneInterrogationIterator< DataType > Struct Template Reference
#include "MovieSceneTemplateInterrogation.h"
Public Member Functions
TMovieSceneInterrogationIterator (const FMovieSceneInterrogationData &InContainer, FMovieSceneInterrogationKey InPredicateKey)
void NextElement ()
FORCEINLINE operator bool () const
FORCEINLINE bool operator! () const
const DataType & operator* () const
TMovieSceneInterrogationIterator & operator++ ()
const DataType * operator-> () const
Private Attributes
const FMovieSceneInterrogationData & Container
int32 Index
TOptional< FMovieSceneInterrogationKey > PredicateKey
Friends
FORCEINLINE friend TMovieSceneInterrogationIterator< DataType > begin (const TMovieSceneInterrogationIterator< DataType > &In)
FORCEINLINE friend TMovieSceneInterrogationIterator< DataType > end (const TMovieSceneInterrogationIterator< DataType > &In)
FORCEINLINE friend bool operator!= (const TMovieSceneInterrogationIterator &LHS, const TMovieSceneInterrogationIterator &RHS)
FORCEINLINE friend bool operator== (const TMovieSceneInterrogationIterator &LHS, const TMovieSceneInterrogationIterator &RHS)
Detailed Description
template<typename DataType>
struct TMovieSceneInterrogationIterator< DataType >
Definition at line 113 of file MovieSceneTemplateInterrogation.h.
Constructor & Destructor Documentation
TMovieSceneInterrogationIterator()
template<typename DataType> TMovieSceneInterrogationIterator< DataType >::TMovieSceneInterrogationIterator (const FMovieSceneInterrogationData & InContainer, FMovieSceneInterrogationKey InPredicateKey) inline
Definition at line 115 of file MovieSceneTemplateInterrogation.h.
References Container, InContainer, Index, NextElement(), and PredicateKey.
Referenced by begin, end, operator!=, operator++(), and operator==.
Member Function Documentation
NextElement()
template<typename DataType> void TMovieSceneInterrogationIterator< DataType >::NextElement () inline
Definition at line 155 of file MovieSceneTemplateInterrogation.h.
References Container, Index, and PredicateKey.
Referenced by TMovieSceneInterrogationIterator(), and operator++().
operator bool()
template<typename DataType> FORCEINLINE TMovieSceneInterrogationIterator< DataType >::operator bool () const inline explicit
Definition at line 139 of file MovieSceneTemplateInterrogation.h.
References Container, FORCEINLINE, and Index.
operator!()
template<typename DataType> FORCEINLINE bool TMovieSceneInterrogationIterator< DataType >::operator! () const inline
Definition at line 144 of file MovieSceneTemplateInterrogation.h.
References bool, and FORCEINLINE.
operator*()
template<typename DataType> const DataType & TMovieSceneInterrogationIterator< DataType >::operator* () const inline
Definition at line 129 of file MovieSceneTemplateInterrogation.h.
References Container, TMovieSceneInterrogationToken< T >::Data, and Index.
operator++()
template<typename DataType> TMovieSceneInterrogationIterator & TMovieSceneInterrogationIterator< DataType >::operator++ () inline
Definition at line 123 of file MovieSceneTemplateInterrogation.h.
References TMovieSceneInterrogationIterator(), and NextElement().
operator->()
template<typename DataType> const DataType * TMovieSceneInterrogationIterator< DataType >::operator-> () const inline
Definition at line 134 of file MovieSceneTemplateInterrogation.h.
References Container, TMovieSceneInterrogationToken< T >::Data, and Index.
Friends And Related Symbol Documentation
begin
template<typename DataType> FORCEINLINE friend TMovieSceneInterrogationIterator< DataType > begin (const TMovieSceneInterrogationIterator< DataType > & In) friend
Definition at line 152 of file MovieSceneTemplateInterrogation.h.
References TMovieSceneInterrogationIterator(), and FORCEINLINE.
end
template<typename DataType> FORCEINLINE friend TMovieSceneInterrogationIterator< DataType > end (const TMovieSceneInterrogationIterator< DataType > & In) friend
Definition at line 153 of file MovieSceneTemplateInterrogation.h.
References TMovieSceneInterrogationIterator(), FORCEINLINE, and New().
operator!=
template<typename DataType> FORCEINLINE friend bool operator!= (const TMovieSceneInterrogationIterator< DataType > & LHS, const TMovieSceneInterrogationIterator< DataType > & RHS) friend
Definition at line 150 of file MovieSceneTemplateInterrogation.h.
References TMovieSceneInterrogationIterator(), Container, FORCEINLINE, and Index.
operator==
template<typename DataType> FORCEINLINE friend bool operator== (const TMovieSceneInterrogationIterator< DataType > & LHS, const TMovieSceneInterrogationIterator< DataType > & RHS) friend
Definition at line 149 of file MovieSceneTemplateInterrogation.h.
References TMovieSceneInterrogationIterator(), Container, FORCEINLINE, and Index.
Field Documentation
Container
template<typename DataType> const FMovieSceneInterrogationData& TMovieSceneInterrogationIterator< DataType >::Container private
Definition at line 172 of file MovieSceneTemplateInterrogation.h.
Referenced by TMovieSceneInterrogationIterator(), NextElement(), operator bool(), operator!=, operator*(), operator->(), and operator==.
Index
template<typename DataType> int32 TMovieSceneInterrogationIterator< DataType >::Index private
Definition at line 174 of file MovieSceneTemplateInterrogation.h.
Referenced by TMovieSceneInterrogationIterator(), NextElement(), operator bool(), operator!=, operator*(), operator->(), and operator==.
PredicateKey
template<typename DataType> TOptional<FMovieSceneInterrogationKey> TMovieSceneInterrogationIterator< DataType >::PredicateKey private
Definition at line 173 of file MovieSceneTemplateInterrogation.h.
Referenced by TMovieSceneInterrogationIterator(), and NextElement().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Compilation/MovieSceneTemplateInterrogation.h