Unreal Engine 5.6 C++ API: UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType > Struct Template Reference
UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType > Struct Template Reference
#include "KMeans.h"
Public Member Functions
void Accumulate (int32 Index, const TVectorType &In)
void Assign (int32 Index, const TVectorType &In)
TVectorType DivideBy (int32 Index, int32 InDivider)
void RemoveAtSwap (size_t Index, EAllowShrinking AllowShrinking)
void SetNumZeroed (uint32 Num)
Private Attributes
TStaticArray< TArray< std::atomic< typename TVectorType::FReal > >, TVectorType::NumComponents > AtomicValues
TArray< TVectorType > Values
Detailed Description
template<typename TVectorType, bool bUseAtomicType>
struct UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >
Definition at line 26 of file KMeans.h.
Member Function Documentation
Accumulate()
template<typename TVectorType, bool bUseAtomicType> void UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::Accumulate (int32 Index, const TVectorType & In) inline
Definition at line 88 of file KMeans.h.
References AtomicValues, and Values.
Referenced by UE::Geometry::FClusterKMeans::ComputeClusters().
Assign()
template<typename TVectorType, bool bUseAtomicType> void UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::Assign (int32 Index, const TVectorType & In) inline
Definition at line 52 of file KMeans.h.
References AtomicValues, and Values.
Referenced by UE::Geometry::FClusterKMeans::ComputeClusters().
DivideBy()
template<typename TVectorType, bool bUseAtomicType> TVectorType UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::DivideBy (int32 Index, int32 InDivider) inline
Definition at line 69 of file KMeans.h.
References AtomicValues, and Values.
Referenced by UE::Geometry::FClusterKMeans::ComputeClusters().
RemoveAtSwap()
template<typename TVectorType, bool bUseAtomicType> void UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::RemoveAtSwap (size_t Index, EAllowShrinking AllowShrinking) inline
Definition at line 105 of file KMeans.h.
References AtomicValues, and Values.
Referenced by UE::Geometry::FClusterKMeans::ComputeClusters().
SetNumZeroed()
template<typename TVectorType, bool bUseAtomicType> void UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::SetNumZeroed (uint32 Num) inline
Definition at line 35 of file KMeans.h.
References AtomicValues, Num, and Values.
Referenced by UE::Geometry::FClusterKMeans::ComputeClusters().
Field Documentation
AtomicValues
template<typename TVectorType, bool bUseAtomicType> TStaticArray<TArray<std::atomic<typename TVectorType::FReal> >, TVectorType::NumComponents> UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::AtomicValues private
Definition at line 30 of file KMeans.h.
Referenced by Accumulate(), Assign(), DivideBy(), RemoveAtSwap(), and SetNumZeroed().
Values
template<typename TVectorType, bool bUseAtomicType> TArray<TVectorType> UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::Values private
Definition at line 33 of file KMeans.h.
Referenced by Accumulate(), Assign(), DivideBy(), RemoveAtSwap(), and SetNumZeroed().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/Clustering/KMeans.h