Unreal Engine 5.6 C++ API: FRDGBarrierBatchEndId Struct Reference
FRDGBarrierBatchEndId Struct Reference
#include "RenderGraphPass.h"
Public Member Functions
FRDGBarrierBatchEndId ()=default
FRDGBarrierBatchEndId (FRDGPassHandle InPassHandle, ERDGBarrierLocation InBarrierLocation)
bool operator!= (FRDGBarrierBatchEndId Other) const
bool operator== (FRDGBarrierBatchEndId Other) const
Data Fields
ERDGBarrierLocation BarrierLocation = ERDGBarrierLocation::Epilogue
FRDGPassHandle PassHandle
Detailed Description
Definition at line 85 of file RenderGraphPass.h.
Constructor & Destructor Documentation
FRDGBarrierBatchEndId() [1/2]
FRDGBarrierBatchEndId::FRDGBarrierBatchEndId () default
Referenced by operator!=(), and operator==().
FRDGBarrierBatchEndId() [2/2]
FRDGBarrierBatchEndId::FRDGBarrierBatchEndId (FRDGPassHandle InPassHandle, ERDGBarrierLocation InBarrierLocation) inline
Definition at line 88 of file RenderGraphPass.h.
References BarrierLocation, and PassHandle.
Member Function Documentation
operator!=()
bool FRDGBarrierBatchEndId::operator!= (FRDGBarrierBatchEndId Other) const inline
Definition at line 98 of file RenderGraphPass.h.
References FRDGBarrierBatchEndId(), and Other.
operator==()
bool FRDGBarrierBatchEndId::operator== (FRDGBarrierBatchEndId Other) const inline
Definition at line 93 of file RenderGraphPass.h.
References FRDGBarrierBatchEndId(), BarrierLocation, Other, and PassHandle.
Field Documentation
BarrierLocation
ERDGBarrierLocation FRDGBarrierBatchEndId::BarrierLocation = ERDGBarrierLocation::Epilogue
Definition at line 104 of file RenderGraphPass.h.
Referenced by FRDGBarrierBatchEndId(), and operator==().
PassHandle
FRDGPassHandle FRDGBarrierBatchEndId::PassHandle
Definition at line 103 of file RenderGraphPass.h.
Referenced by FRDGBarrierBatchEndId(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphPass.h