Unreal Engine 5.6 C++ API: FRigVMMemoryHandle Struct Reference
FRigVMMemoryHandle Struct Reference
Memory handle.
#include "RigVMMemoryStorage.h"
Public Member Functions
FRigVMMemoryHandle ()
FRigVMMemoryHandle (uint8 *InPtr, const FProperty *InProperty, const FRigVMPropertyPath *InPropertyPath, FRigVMLazyBranch *InLazyBranch=nullptr)
RIGVM_API bool ComputeLazyValueIfNecessary (FRigVMExtendedExecuteContext &Context, uint32 InSliceHash)
Computes the data if necessary and returns true if the value is valid.
uint8 * GetData (bool bFollowPropertyPath=false, int32 InSliceIndex=INDEX_NONE)
Returns the cached pointer stored within the handle.
const uint8 * GetData (bool bFollowPropertyPath=false, int32 InSliceIndex=INDEX_NONE) const
Computes the data if necessary and returns the cached pointer stored within the handle.
template<typename ComputedType>
TRigVMLazyValue< ComputedType > GetDataLazily (bool bFollowPropertyPath=false, int32 InSliceIndex=INDEX_NONE) const
Computes the data if necessary and returns the cached pointer stored within the handle.
const FProperty * GetProperty () const
const FRigVMPropertyPath * GetPropertyPath () const
const FRigVMPropertyPath & GetPropertyPathRef () const
const FProperty * GetResolvedProperty (bool bIsHiddenArgument=false) const
bool IsBool (bool bIsHiddenArgument=false) const
bool IsBoolArray (bool bIsHiddenArgument=false) const
bool IsDouble (bool bIsHiddenArgument=false) const
bool IsDoubleArray (bool bIsHiddenArgument=false) const
template<typename T>
bool IsEnum (bool bIsHiddenArgument=false) const
bool IsEnum (const UEnum *InEnum, bool bIsHiddenArgument=false) const
template<typename T>
bool IsEnumArray (bool bIsHiddenArgument=false) const
bool IsEnumArray (const UEnum *InEnum, bool bIsHiddenArgument=false) const
bool IsFloat (bool bIsHiddenArgument=false) const
bool IsFloatArray (bool bIsHiddenArgument=false) const
bool IsInt32 (bool bIsHiddenArgument=false) const
bool IsInt32Array (bool bIsHiddenArgument=false) const
bool IsLazy () const
Returns true if this memory handle depends on a lazily executed branch.
bool IsName (bool bIsHiddenArgument=false) const
bool IsNameArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr>
bool IsObject (bool bIsHiddenArgument=false) const
bool IsObject (const UClass *InClass, bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr>
bool IsObjectArray (bool bIsHiddenArgument=false) const
bool IsObjectArray (const UClass *InClass, bool bIsHiddenArgument=false) const
template<typename PropertyType>
bool IsPropertyArrayType (bool bIsHiddenArgument=false) const
template<typename PropertyType>
bool IsPropertyType (bool bIsHiddenArgument=false) const
bool IsString (bool bIsHiddenArgument=false) const
bool IsStringArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr>
bool IsStruct (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
bool IsStruct (bool bIsHiddenArgument=false) const
bool IsStruct (const UScriptStruct *InStruct, bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr>
bool IsStructArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
bool IsStructArray (bool bIsHiddenArgument=false) const
bool IsStructArray (const UScriptStruct *InStruct, bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TIsTArray_V< T > >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsBool< T >::Value, T >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsFloat< T >::Value, T >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsDouble< T >::Value, T >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsInt32< T >::Value, T >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsName< T >::Value, T >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsString< T >::Value, T >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr>
bool IsType (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsBool< T >::Value, T >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsFloat< T >::Value, T >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsDouble< T >::Value, T >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsInt32< T >::Value, T >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsName< T >::Value, T >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsString< T >::Value, T >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr>
bool IsTypeArray (bool bIsHiddenArgument=false) const
Private Member Functions
uint8 * GetData_Internal (bool bFollowPropertyPath, int32 InSliceIndex) const
TRigVMLazyValueBase GetDataLazily_Internal (bool bFollowPropertyPath, uint32 InSliceHash) const
Static Private Member Functions
static const FProperty * GetArrayElementProperty (const FProperty *InProperty)
static const FProperty * GetArrayElementPropertyChecked (const FProperty *InProperty)
static bool IsEnum (const FProperty *InProperty, const UEnum *InEnum, bool bUseArrayElement)
static bool IsObject (const FProperty *InProperty, const UClass *InClass, bool bUseArrayElement)
static bool IsStruct (const FProperty *InProperty, const UScriptStruct *InScriptStruct, bool bUseArrayElement)
Private Attributes
FRigVMLazyBranch * LazyBranch
const FProperty * Property
const FRigVMPropertyPath * PropertyPath
uint8 * Ptr
Friends
struct TRigVMLazyValueBase
class URigVM
Detailed Description
Memory handle.
The FRigVMMemoryHandle is used to access the memory used within a URigMemoryStorage. The Memory Handle caches the pointer of the head property, and can rely on a RigVMPropertyPath to traverse towards a tail property. For example it can cache the pointer of a TArray<FTransform> property's memory and use a property path of '[2].Translation.X' to retrieve the element 2's translation X float / double. Additionally the FRigVMMemoryHandle can be used to access 'sliced' memory. Sliced memory in this case simply means another level of a nested TArray. So a 'sliced' FTransform is stored as a TArray<FTransform>, which the handle can traverse into and return the memory of a specific FTransform within that array.
Definition at line 239 of file RigVMMemoryStorage.h.
Constructor & Destructor Documentation
FRigVMMemoryHandle() [1/2]
FRigVMMemoryHandle::FRigVMMemoryHandle () inline
Definition at line 244 of file RigVMMemoryStorage.h.
References LazyBranch, Property, PropertyPath, and Ptr.
Referenced by GetDataLazily_Internal().
FRigVMMemoryHandle() [2/2]
FRigVMMemoryHandle::FRigVMMemoryHandle (uint8 * InPtr, const FProperty * InProperty, const FRigVMPropertyPath * InPropertyPath, FRigVMLazyBranch * InLazyBranch = nullptr) inline
Definition at line 252 of file RigVMMemoryStorage.h.
References LazyBranch, Property, PropertyPath, and Ptr.
Member Function Documentation
ComputeLazyValueIfNecessary()
RIGVM_API bool FRigVMMemoryHandle::ComputeLazyValueIfNecessary (FRigVMExtendedExecuteContext & Context, uint32 InSliceHash)
Computes the data if necessary and returns true if the value is valid.
Returns
True if the value of the handle is valid after the compute
GetArrayElementProperty()
const FProperty * FRigVMMemoryHandle::GetArrayElementProperty (const FProperty * InProperty) inline static private
Definition at line 882 of file RigVMMemoryStorage.h.
References ArrayProperty, and CastField().
Referenced by IsPropertyArrayType().
GetArrayElementPropertyChecked()
const FProperty * FRigVMMemoryHandle::GetArrayElementPropertyChecked (const FProperty * InProperty) inline static private
Definition at line 891 of file RigVMMemoryStorage.h.
References ArrayProperty, and CastFieldChecked().
Referenced by GetResolvedProperty(), IsEnum(), IsEnumArray(), IsObject(), IsObjectArray(), IsStruct(), and IsStructArray().
GetData() [1/2]
uint8 * FRigVMMemoryHandle::GetData (bool bFollowPropertyPath = false, int32 InSliceIndex = INDEX_NONE) inline
Returns the cached pointer stored within the handle.
Parameters
bFollowPropertyPath If set to true the memory handle will traverse the memory using the property path
InSliceIndex If this is != INDEX_NONE the memory handle will return the slice of the memory requested
Returns
The traversed memory cached by this handle.
Definition at line 266 of file RigVMMemoryStorage.h.
References GetData_Internal(), and INDEX_NONE.
GetData() [2/2]
const uint8 * FRigVMMemoryHandle::GetData (bool bFollowPropertyPath = false, int32 InSliceIndex = INDEX_NONE) const inline
Computes the data if necessary and returns the cached pointer stored within the handle.
Parameters
bFollowPropertyPath If set to true the memory handle will traverse the memory using the property path
InSliceIndex If this is != INDEX_NONE the memory handle will return the slice of the memory requested
Returns
The traversed memory cached by this handle (const)
Definition at line 277 of file RigVMMemoryStorage.h.
References GetData_Internal(), and INDEX_NONE.
GetData_Internal()
uint8 * FRigVMMemoryHandle::GetData_Internal (bool bFollowPropertyPath, int32 InSliceIndex) const inline private
Definition at line 790 of file RigVMMemoryStorage.h.
References FScriptArrayHelper::AddValues(), ArrayProperty, CastFieldChecked(), check, FProperty::CopyCompleteValue(), Display, FProperty::ExportText_Direct(), FScriptArrayHelper::GetRawPtr(), INDEX_NONE, FMath::Max, FScriptArrayHelper::Num(), PPF_None, Property, PropertyPath, Ptr, TEXT, and UE_LOG.
Referenced by GetData(), and GetData().
GetDataLazily()
template<typename ComputedType> TRigVMLazyValue< ComputedType > FRigVMMemoryHandle::GetDataLazily (bool bFollowPropertyPath = false, int32 InSliceIndex = INDEX_NONE) const inline
Computes the data if necessary and returns the cached pointer stored within the handle.
Parameters
bFollowPropertyPath If set to true the memory handle will traverse the memory using the property path
InSliceIndex If this is != INDEX_NONE the memory handle will return the slice of the memory requested
Returns
The traversed memory cached by this handle (const)
Definition at line 289 of file RigVMMemoryStorage.h.
References GetDataLazily_Internal(), and INDEX_NONE.
GetDataLazily_Internal()
TRigVMLazyValueBase FRigVMMemoryHandle::GetDataLazily_Internal (bool bFollowPropertyPath, uint32 InSliceHash) const inline private
Definition at line 872 of file RigVMMemoryStorage.h.
References FRigVMMemoryHandle(), TRigVMLazyValueBase::bFollowPropertyPath, TRigVMLazyValueBase::MemoryHandle, TRigVMLazyValueBase::SliceHash, and TRigVMLazyValueBase.
Referenced by GetDataLazily().
GetProperty()
const FProperty * FRigVMMemoryHandle::GetProperty () const inline
Definition at line 310 of file RigVMMemoryStorage.h.
References Property.
GetPropertyPath()
const FRigVMPropertyPath * FRigVMMemoryHandle::GetPropertyPath () const inline
Definition at line 316 of file RigVMMemoryStorage.h.
References PropertyPath.
GetPropertyPathRef()
const FRigVMPropertyPath & FRigVMMemoryHandle::GetPropertyPathRef () const inline
Definition at line 322 of file RigVMMemoryStorage.h.
References FRigVMPropertyPath::Empty, and PropertyPath.
GetResolvedProperty()
const FProperty * FRigVMMemoryHandle::GetResolvedProperty (bool bIsHiddenArgument = false) const inline
Definition at line 332 of file RigVMMemoryStorage.h.
References check, GetArrayElementPropertyChecked(), Property, and PropertyPath.
Referenced by IsEnum(), IsEnumArray(), IsObject(), IsObjectArray(), IsPropertyArrayType(), IsPropertyType(), IsStruct(), and IsStructArray().
IsBool()
bool FRigVMMemoryHandle::IsBool (bool bIsHiddenArgument = false) const inline
Definition at line 577 of file RigVMMemoryStorage.h.
References IsPropertyType().
Referenced by IsType().
IsBoolArray()
bool FRigVMMemoryHandle::IsBoolArray (bool bIsHiddenArgument = false) const inline
Definition at line 583 of file RigVMMemoryStorage.h.
References IsPropertyArrayType().
Referenced by IsTypeArray().
IsDouble()
bool FRigVMMemoryHandle::IsDouble (bool bIsHiddenArgument = false) const inline
Definition at line 601 of file RigVMMemoryStorage.h.
References IsPropertyType().
Referenced by IsType().
IsDoubleArray()
bool FRigVMMemoryHandle::IsDoubleArray (bool bIsHiddenArgument = false) const inline
Definition at line 607 of file RigVMMemoryStorage.h.
References IsPropertyArrayType().
Referenced by IsTypeArray().
IsEnum() [1/3]
template<typename T> bool FRigVMMemoryHandle::IsEnum (bool bIsHiddenArgument = false) const inline
Definition at line 672 of file RigVMMemoryStorage.h.
References IsEnum(), and StaticEnum().
IsEnum() [2/3]
bool FRigVMMemoryHandle::IsEnum (const FProperty * InProperty, const UEnum * InEnum, bool bUseArrayElement) inline static private
Definition at line 897 of file RigVMMemoryStorage.h.
References CastField(), EnumProperty, GetArrayElementPropertyChecked(), and Property.
IsEnum() [3/3]
bool FRigVMMemoryHandle::IsEnum (const UEnum * InEnum, bool bIsHiddenArgument = false) const inline
Definition at line 649 of file RigVMMemoryStorage.h.
References GetResolvedProperty(), and IsEnum().
Referenced by IsEnum(), IsEnum(), IsEnumArray(), and IsType().
IsEnumArray() [1/2]
template<typename T> bool FRigVMMemoryHandle::IsEnumArray (bool bIsHiddenArgument = false) const inline
Definition at line 679 of file RigVMMemoryStorage.h.
References IsEnumArray(), and StaticEnum().
IsEnumArray() [2/2]
bool FRigVMMemoryHandle::IsEnumArray (const UEnum * InEnum, bool bIsHiddenArgument = false) const inline
Definition at line 656 of file RigVMMemoryStorage.h.
References ArrayProperty, CastField(), GetArrayElementPropertyChecked(), GetResolvedProperty(), and IsEnum().
Referenced by IsEnumArray(), and IsTypeArray().
IsFloat()
bool FRigVMMemoryHandle::IsFloat (bool bIsHiddenArgument = false) const inline
Definition at line 589 of file RigVMMemoryStorage.h.
References IsPropertyType().
Referenced by IsType().
IsFloatArray()
bool FRigVMMemoryHandle::IsFloatArray (bool bIsHiddenArgument = false) const inline
Definition at line 595 of file RigVMMemoryStorage.h.
References IsPropertyArrayType().
Referenced by IsTypeArray().
IsInt32()
bool FRigVMMemoryHandle::IsInt32 (bool bIsHiddenArgument = false) const inline
Definition at line 613 of file RigVMMemoryStorage.h.
References IsPropertyType().
Referenced by IsType().
IsInt32Array()
bool FRigVMMemoryHandle::IsInt32Array (bool bIsHiddenArgument = false) const inline
Definition at line 619 of file RigVMMemoryStorage.h.
References IsPropertyArrayType().
Referenced by IsTypeArray().
IsLazy()
bool FRigVMMemoryHandle::IsLazy () const inline
Returns true if this memory handle depends on a lazily executed branch.
Returns
True if this memory handle depends on a lazily executed branch
Definition at line 298 of file RigVMMemoryStorage.h.
References LazyBranch.
IsName()
bool FRigVMMemoryHandle::IsName (bool bIsHiddenArgument = false) const inline
Definition at line 625 of file RigVMMemoryStorage.h.
References IsPropertyType().
Referenced by IsType().
IsNameArray()
bool FRigVMMemoryHandle::IsNameArray (bool bIsHiddenArgument = false) const inline
Definition at line 631 of file RigVMMemoryStorage.h.
References IsPropertyArrayType().
Referenced by IsTypeArray().
IsObject() [1/3]
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsObject (bool bIsHiddenArgument = false) const inline
Definition at line 773 of file RigVMMemoryStorage.h.
References IsObject().
IsObject() [2/3]
bool FRigVMMemoryHandle::IsObject (const FProperty * InProperty, const UClass * InClass, bool bUseArrayElement) inline static private
Definition at line 938 of file RigVMMemoryStorage.h.
References CastField(), GetArrayElementPropertyChecked(), ObjectProperty, and Property.
IsObject() [3/3]
bool FRigVMMemoryHandle::IsObject (const UClass * InClass, bool bIsHiddenArgument = false) const inline
Definition at line 747 of file RigVMMemoryStorage.h.
References GetResolvedProperty(), and IsObject().
Referenced by IsObject(), IsObject(), IsObjectArray(), and IsType().
IsObjectArray() [1/2]
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsObjectArray (bool bIsHiddenArgument = false) const inline
Definition at line 783 of file RigVMMemoryStorage.h.
References IsObjectArray().
IsObjectArray() [2/2]
bool FRigVMMemoryHandle::IsObjectArray (const UClass * InClass, bool bIsHiddenArgument = false) const inline
Definition at line 754 of file RigVMMemoryStorage.h.
References ArrayProperty, CastField(), GetArrayElementPropertyChecked(), GetResolvedProperty(), and IsObject().
Referenced by IsObjectArray(), and IsTypeArray().
IsPropertyArrayType()
template<typename PropertyType> bool FRigVMMemoryHandle::IsPropertyArrayType (bool bIsHiddenArgument = false) const inline
Definition at line 356 of file RigVMMemoryStorage.h.
References GetArrayElementProperty(), and GetResolvedProperty().
Referenced by IsBoolArray(), IsDoubleArray(), IsFloatArray(), IsInt32Array(), IsNameArray(), and IsStringArray().
IsPropertyType()
template<typename PropertyType> bool FRigVMMemoryHandle::IsPropertyType (bool bIsHiddenArgument = false) const inline
Definition at line 348 of file RigVMMemoryStorage.h.
References GetResolvedProperty(), and FField::IsA().
Referenced by IsBool(), IsDouble(), IsFloat(), IsInt32(), IsName(), and IsString().
IsString()
bool FRigVMMemoryHandle::IsString (bool bIsHiddenArgument = false) const inline
Definition at line 637 of file RigVMMemoryStorage.h.
References IsPropertyType().
Referenced by IsType().
IsStringArray()
bool FRigVMMemoryHandle::IsStringArray (bool bIsHiddenArgument = false) const inline
Definition at line 643 of file RigVMMemoryStorage.h.
References IsPropertyArrayType().
Referenced by IsTypeArray().
IsStruct() [1/4]
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsStruct (bool bIsHiddenArgument = false) const inline
Definition at line 711 of file RigVMMemoryStorage.h.
References TBaseStructureBase< T, bHasStaticStruct >::Get(), and IsStruct.
IsStruct() [2/4]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsStruct (bool bIsHiddenArgument = false) const inline
Definition at line 721 of file RigVMMemoryStorage.h.
References IsStruct.
IsStruct() [3/4]
bool FRigVMMemoryHandle::IsStruct (const FProperty * InProperty, const UScriptStruct * InScriptStruct, bool bUseArrayElement) inline static private
Definition at line 921 of file RigVMMemoryStorage.h.
References CastField(), GetArrayElementPropertyChecked(), Property, and StructProperty.
IsStruct() [4/4]
bool FRigVMMemoryHandle::IsStruct (const UScriptStruct * InStruct, bool bIsHiddenArgument = false) const inline
Definition at line 685 of file RigVMMemoryStorage.h.
References GetResolvedProperty(), and IsStruct.
IsStructArray() [1/3]
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsStructArray (bool bIsHiddenArgument = false) const inline
Definition at line 731 of file RigVMMemoryStorage.h.
References TBaseStructureBase< T, bHasStaticStruct >::Get(), and IsStructArray().
IsStructArray() [2/3]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsStructArray (bool bIsHiddenArgument = false) const inline
Definition at line 741 of file RigVMMemoryStorage.h.
References IsStructArray().
IsStructArray() [3/3]
bool FRigVMMemoryHandle::IsStructArray (const UScriptStruct * InStruct, bool bIsHiddenArgument = false) const inline
Definition at line 692 of file RigVMMemoryStorage.h.
References ArrayProperty, CastField(), GetArrayElementPropertyChecked(), GetResolvedProperty(), and IsStruct.
Referenced by IsStructArray(), and IsTypeArray().
IsType() [1/11]
template<typename T, typename TEnableIf< TIsTArray_V< T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 371 of file RigVMMemoryStorage.h.
References IsTypeArray().
IsType() [2/11]
template<typename T, typename TEnableIf< TRigVMIsBool< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 382 of file RigVMMemoryStorage.h.
References IsBool().
IsType() [3/11]
template<typename T, typename TEnableIf< TRigVMIsFloat< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 402 of file RigVMMemoryStorage.h.
References IsFloat().
IsType() [4/11]
template<typename T, typename TEnableIf< TRigVMIsDouble< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 422 of file RigVMMemoryStorage.h.
References IsDouble().
IsType() [5/11]
template<typename T, typename TEnableIf< TRigVMIsInt32< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 442 of file RigVMMemoryStorage.h.
References IsInt32().
IsType() [6/11]
template<typename T, typename TEnableIf< TRigVMIsName< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 461 of file RigVMMemoryStorage.h.
References IsName().
IsType() [7/11]
template<typename T, typename TEnableIf< TRigVMIsString< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 481 of file RigVMMemoryStorage.h.
References IsString().
IsType() [8/11]
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 501 of file RigVMMemoryStorage.h.
References IsStruct.
IsType() [9/11]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 521 of file RigVMMemoryStorage.h.
References IsStruct.
IsType() [10/11]
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 541 of file RigVMMemoryStorage.h.
References IsEnum().
IsType() [11/11]
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsType (bool bIsHiddenArgument = false) const inline
Definition at line 561 of file RigVMMemoryStorage.h.
References IsObject().
IsTypeArray() [1/10]
template<typename T, typename TEnableIf< TRigVMIsBool< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 392 of file RigVMMemoryStorage.h.
References IsBoolArray().
Referenced by IsType().
IsTypeArray() [2/10]
template<typename T, typename TEnableIf< TRigVMIsFloat< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 412 of file RigVMMemoryStorage.h.
References IsFloatArray().
IsTypeArray() [3/10]
template<typename T, typename TEnableIf< TRigVMIsDouble< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 432 of file RigVMMemoryStorage.h.
References IsDoubleArray().
IsTypeArray() [4/10]
template<typename T, typename TEnableIf< TRigVMIsInt32< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 452 of file RigVMMemoryStorage.h.
References IsInt32Array().
IsTypeArray() [5/10]
template<typename T, typename TEnableIf< TRigVMIsName< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 471 of file RigVMMemoryStorage.h.
References IsNameArray().
IsTypeArray() [6/10]
template<typename T, typename TEnableIf< TRigVMIsString< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 491 of file RigVMMemoryStorage.h.
References IsStringArray().
IsTypeArray() [7/10]
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 511 of file RigVMMemoryStorage.h.
References IsStructArray().
IsTypeArray() [8/10]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 531 of file RigVMMemoryStorage.h.
References IsStructArray().
IsTypeArray() [9/10]
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 551 of file RigVMMemoryStorage.h.
References IsEnumArray().
IsTypeArray() [10/10]
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr> bool FRigVMMemoryHandle::IsTypeArray (bool bIsHiddenArgument = false) const inline
Definition at line 571 of file RigVMMemoryStorage.h.
References IsObjectArray().
Friends And Related Symbol Documentation
TRigVMLazyValueBase
friend struct TRigVMLazyValueBase friend
Definition at line 968 of file RigVMMemoryStorage.h.
References TRigVMLazyValueBase.
Referenced by GetDataLazily_Internal(), and TRigVMLazyValueBase.
URigVM
friend class URigVM friend
Definition at line 967 of file RigVMMemoryStorage.h.
References URigVM.
Referenced by URigVM.
Field Documentation
LazyBranch
FRigVMLazyBranch* FRigVMMemoryHandle::LazyBranch private
Definition at line 965 of file RigVMMemoryStorage.h.
Referenced by FRigVMMemoryHandle(), FRigVMMemoryHandle(), and IsLazy().
Property
const FProperty* FRigVMMemoryHandle::Property private
Definition at line 959 of file RigVMMemoryStorage.h.
Referenced by FRigVMMemoryHandle(), FRigVMMemoryHandle(), GetData_Internal(), GetProperty(), GetResolvedProperty(), IsEnum(), IsObject(), and IsStruct().
PropertyPath
const FRigVMPropertyPath* FRigVMMemoryHandle::PropertyPath private
Definition at line 962 of file RigVMMemoryStorage.h.
Referenced by FRigVMMemoryHandle(), FRigVMMemoryHandle(), GetData_Internal(), GetPropertyPath(), GetPropertyPathRef(), and GetResolvedProperty().
Ptr
uint8* FRigVMMemoryHandle::Ptr private
Definition at line 956 of file RigVMMemoryStorage.h.
Referenced by FRigVMMemoryHandle(), FRigVMMemoryHandle(), and GetData_Internal().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMMemoryStorage.h