Unreal Engine 5.6 C++ API: FTimeToPixel Struct Reference
FTimeToPixel Struct Reference
Utility for converting time units to slate pixel units and vice versa This class will eventually be deprecated in favor of UE::Sequencer::FTimeToPixelSpace.
#include "TimeToPixel.h"
Public Member Functions
FTimeToPixel ()=delete
FTimeToPixel (const FGeometry &AllottedGeometry, const TRange< double > &InLocalViewRange, const FFrameRate &InTickResolution)
FTimeToPixel (const UE::Sequencer::FTimeToPixelSpace &InOther)
FTimeToPixel (float WidthPx, const TRange< double > &InLocalViewRange, const FFrameRate &InTickResolution)
FTimeToPixel CreateNonLinear (TSharedPtr< UE::Sequencer::INonLinearTimeTransform > InNonLinearTransform) const
FTimeToPixel & operator= (const UE::Sequencer::FTimeToPixelSpace &InOther)
SEQUENCERCORE_API FTimeToPixel RelativeTo (const FFrameTime &FrameZero) const
Make this converter relative to the specified time (ie, such that pixel 0 == FrameAmount)
Public Member Functions inherited from UE::Sequencer::FTimeToPixelSpace
SEQUENCERCORE_API FTimeToPixelSpace (const FGeometry &AllottedGeometry, const TRange< double > &InLocalViewRange, const FFrameRate &InTickResolution)
SEQUENCERCORE_API FTimeToPixelSpace (float WidthPx, const TRange< double > &InLocalViewRange, const FFrameRate &InTickResolution)
SEQUENCERCORE_API FTimeToPixelSpace CreateNonLinear (TSharedPtr< INonLinearTimeTransform > InNonLinearTransform) const
SEQUENCERCORE_API float FrameDeltaToPixel (const FFrameTime &TimeDelta) const
Converts a frame delta value to pixel delta.
SEQUENCERCORE_API float FrameToPixel (const FFrameTime &Time) const
Converts a frame time to a pixel point relative to the geometry of a widget (passed into the constructor)
SEQUENCERCORE_API FFrameRate GetTickResolution () const
Retrieve the tick resolution of the current sequence.
SEQUENCERCORE_API FFrameTime PixelDeltaToFrame (float PixelDelta) const
Converts a pixel delta value to delta frame time.
SEQUENCERCORE_API double PixelDeltaToSeconds (float PixelDelta) const
Converts a pixel delta value to delta seconds time.
SEQUENCERCORE_API FFrameTime PixelToFrame (float PixelX) const
Converts a pixel value to frame time.
SEQUENCERCORE_API double PixelToSeconds (float PixelX) const
Converts a pixel value to time.
SEQUENCERCORE_API FTimeToPixelSpace RelativeTo (const FFrameTime &FrameZero) const
Make this converter relative to the specified time (ie, such that pixel 0 == FrameAmount)
SEQUENCERCORE_API float SecondsDeltaToPixel (double TimeDelta) const
Converts a time delta to a pixel delta.
SEQUENCERCORE_API float SecondsToPixel (double Time) const
Converts a time to a pixel point relative to the geometry of a widget (passed into the constructor)
Additional Inherited Members
Data Fields inherited from UE::Sequencer::FTimeToPixelSpace
TSharedPtr< INonLinearTimeTransform > NonLinearTransform
Protected Member Functions inherited from UE::Sequencer::FTimeToPixelSpace
FTimeToPixelSpace ()
Protected Attributes inherited from UE::Sequencer::FTimeToPixelSpace
float PixelOffset
float PixelsPerSecond
The number of pixels in the view range.
FFrameRate TickResolution
The tick resolution of the current timeline.
Detailed Description
Utility for converting time units to slate pixel units and vice versa This class will eventually be deprecated in favor of UE::Sequencer::FTimeToPixelSpace.
Definition at line 132 of file TimeToPixel.h.
Constructor & Destructor Documentation
FTimeToPixel() [1/4]
FTimeToPixel::FTimeToPixel () delete
Referenced by CreateNonLinear(), operator=(), and RelativeTo().
FTimeToPixel() [2/4]
FTimeToPixel::FTimeToPixel (const FGeometry & AllottedGeometry, const TRange< double > & InLocalViewRange, const FFrameRate & InTickResolution) inline
Definition at line 138 of file TimeToPixel.h.
References UE::Sequencer::FTimeToPixelSpace::FTimeToPixelSpace(), and X.
FTimeToPixel() [3/4]
FTimeToPixel::FTimeToPixel (float WidthPx, const TRange< double > & InLocalViewRange, const FFrameRate & InTickResolution) inline
Definition at line 143 of file TimeToPixel.h.
References UE::Sequencer::FTimeToPixelSpace::FTimeToPixelSpace().
FTimeToPixel() [4/4]
FTimeToPixel::FTimeToPixel (const UE::Sequencer::FTimeToPixelSpace & InOther) inline
Definition at line 148 of file TimeToPixel.h.
References UE::Sequencer::FTimeToPixelSpace::FTimeToPixelSpace().
Member Function Documentation
CreateNonLinear()
FTimeToPixel FTimeToPixel::CreateNonLinear (TSharedPtr< UE::Sequencer::INonLinearTimeTransform > InNonLinearTransform) const inline
Definition at line 153 of file TimeToPixel.h.
References FTimeToPixel(), and Copy.
operator=()
FTimeToPixel & FTimeToPixel::operator= (const UE::Sequencer::FTimeToPixelSpace & InOther) inline
Definition at line 160 of file TimeToPixel.h.
References FTimeToPixel().
RelativeTo()
SEQUENCERCORE_API FTimeToPixel FTimeToPixel::RelativeTo (const FFrameTime & FrameZero) const
Make this converter relative to the specified time (ie, such that pixel 0 == FrameAmount)
References FTimeToPixel().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/TimeToPixel.h