Unreal Engine 5.6 C++ API: UE::PixelStreaming2::FBufferBuilder Struct Reference
UE::PixelStreaming2::FBufferBuilder Struct Reference
#include "EpicRtcDataTrack.h"
Public Member Functions
FBufferBuilder (size_t size)
template<typename T>
void Insert (const T &&Value)
size_t Serialize (const void *Data, size_t DataSize)
Data Fields
TArray< uint8 > Buffer
size_t Pos
Detailed Description
Definition at line 63 of file EpicRtcDataTrack.h.
Constructor & Destructor Documentation
FBufferBuilder()
UE::PixelStreaming2::FBufferBuilder::FBufferBuilder (size_t size) inline
Definition at line 68 of file EpicRtcDataTrack.h.
References Buffer, and Pos.
Member Function Documentation
Insert()
template<typename T> void UE::PixelStreaming2::FBufferBuilder::Insert (const T && Value) inline
Definition at line 82 of file EpicRtcDataTrack.h.
References Buffer, check, Forward(), UE::PixelStreaming2::GetByteSizeOf(), UE::PixelStreaming2::GetDataPointer(), FMemory::Memcpy(), Pos, and Value.
Referenced by UE::PixelStreaming2::FEpicRtcDataTrack::EncodeMessage().
Serialize()
size_t UE::PixelStreaming2::FBufferBuilder::Serialize (const void * Data, size_t DataSize) inline
Definition at line 74 of file EpicRtcDataTrack.h.
References Buffer, check, DataSize, FMemory::Memcpy(), and Pos.
Field Documentation
Buffer
TArray<uint8> UE::PixelStreaming2::FBufferBuilder::Buffer
Definition at line 65 of file EpicRtcDataTrack.h.
Referenced by FBufferBuilder(), Insert(), UE::PixelStreaming2::FEpicRtcDataTrack::SendMessage(), and Serialize().
Pos
size_t UE::PixelStreaming2::FBufferBuilder::Pos
Definition at line 66 of file EpicRtcDataTrack.h.
Referenced by FBufferBuilder(), Insert(), and Serialize().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming2/Source/PixelStreaming2RTC/Internal/EpicRtcDataTrack.h