Unreal Engine 5.6 C++ API: UE::AnimNext::TReferencePose< AllocatorType, SetAllocator > Struct Template Reference
UE::AnimNext::TReferencePose< AllocatorType, SetAllocator > Struct Template Reference
#include "ReferencePose.h"
Public Member Functions
TReferencePose ()=default
FBoneIndexType FindLODBoneIndexFromBoneName (FName BoneName) const
const TMap< FName, FBoneIndexType > & GetBoneNameToLODBoneIndexMap () const
int32 GetLODBoneIndexFromMeshBoneIndex (int32 MeshBoneIndex) const
int32 GetLODBoneIndexFromSkeletonBoneIndex (int32 SkeletionBoneIndex) const
const TArrayView< const FBoneIndexType > GetLODBoneIndexToMeshBoneIndexMap (int32 LODLevel) const
const TArrayView< const FBoneIndexType > GetLODBoneIndexToParentLODBoneIndexMap (int32 LODLevel) const
const TArrayView< const FBoneIndexType > GetLODBoneIndexToSkeletonBoneIndexMap (int32 LODLevel) const
int32 GetLODParentBoneIndex (int32 LODLevel, int32 LODBoneIndex) const
int32 GetMeshBoneIndexFromLODBoneIndex (int32 LODBoneIndex) const
const TArrayView< const FBoneIndexType > GetMeshBoneIndexToLODBoneIndexMap () const
TConstArrayView< FBoneIndexType > GetMeshBoneIndexToParentMeshBoneIndexMap () const
int32 GetNumBonesForLOD (int32 LODLevel) const
const FQuat GetRefPoseRotation (int32 LODBoneIndex) const
const FVector GetRefPoseScale3D (int32 LODBoneIndex) const
FTransform GetRefPoseTransform (int32 LODBoneIndex) const
const FVector GetRefPoseTranslation (int32 LODBoneIndex) const
const USkeletalMesh * GetSkeletalMeshAsset () const
const USkeleton * GetSkeletonAsset () const
int32 GetSkeletonBoneIndexFromLODBoneIndex (int32 LODBoneIndex) const
const TArrayView< const FBoneIndexType > GetSkeletonBoneIndexToLODBoneIndexMap () const
int32 GetSourceLODLevel () const
void Initialize (const FReferenceSkeleton &RefSkeleton, const TArray< TArray< FBoneIndexType > > &InLODBoneIndexToParentLODBoneIndexMapPerLOD, const TArray< TArray< FBoneIndexType > > &InLODBoneIndexToMeshBoneIndexMapPerLOD, const TArray< TArray< FBoneIndexType > > &InLODBoneIndexToSkeletonBoneIndexMapPerLOD, const TArray< FBoneIndexType > &InSkeletonBoneIndexToLODBoneIndexMap, const TArray< FBoneIndexType > &InMeshBoneIndexToLODBoneIndexMap, const TArray< int32, AllocatorType > &InLODNumBones, const TMap< FName, FBoneIndexType > &InNameToLODBoneIndexMap, bool bFastPath)
bool IsBoneEnabled (int32 BoneIndex, int32 LODLevel) const
bool IsFastPath () const
bool IsValid () const
Data Fields
TMap< FName, FBoneIndexType, SetAllocator > BoneNameToLODBoneIndexMap
EReferencePoseGenerationFlags GenerationFlags = EReferencePoseGenerationFlags::None
TArray< TArray< FBoneIndexType, AllocatorType >, AllocatorType > LODBoneIndexToMeshBoneIndexMapPerLOD
TArray< TArray< FBoneIndexType, AllocatorType >, AllocatorType > LODBoneIndexToParentLODBoneIndexMapPerLOD
TArray< TArray< FBoneIndexType, AllocatorType >, AllocatorType > LODBoneIndexToSkeletonBoneIndexMapPerLOD
TArray< int32, AllocatorType > LODNumBones
TArray< FBoneIndexType, AllocatorType > MeshBoneIndexToLODBoneIndexMap
TArray< FBoneIndexType, AllocatorType > MeshBoneIndexToParentMeshBoneIndexMap
TTransformArray< AllocatorType > ReferenceLocalTransforms
TWeakObjectPtr< const USkeletalMesh > SkeletalMesh = nullptr
TWeakObjectPtr< const USkeletalMeshComponent > SkeletalMeshComponent = nullptr
TWeakObjectPtr< const USkeleton > Skeleton = nullptr
TArray< FBoneIndexType, AllocatorType > SkeletonBoneIndexToLODBoneIndexMap
Static Public Attributes
static constexpr FBoneIndexType RootBoneIndex = 0
Detailed Description
template<typename AllocatorType, typename SetAllocator>
struct UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >
Definition at line 32 of file ReferencePose.h.
Constructor & Destructor Documentation
TReferencePose()
template<typename AllocatorType, typename SetAllocator> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::TReferencePose () default
Member Function Documentation
FindLODBoneIndexFromBoneName()
template<typename AllocatorType, typename SetAllocator> FBoneIndexType UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::FindLODBoneIndexFromBoneName (FName BoneName) const inline
Definition at line 213 of file ReferencePose.h.
GetBoneNameToLODBoneIndexMap()
template<typename AllocatorType, typename SetAllocator> const TMap< FName, FBoneIndexType > & UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetBoneNameToLODBoneIndexMap () const inline
Definition at line 206 of file ReferencePose.h.
GetLODBoneIndexFromMeshBoneIndex()
template<typename AllocatorType, typename SetAllocator> int32 UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetLODBoneIndexFromMeshBoneIndex (int32 MeshBoneIndex) const inline
Definition at line 244 of file ReferencePose.h.
GetLODBoneIndexFromSkeletonBoneIndex()
template<typename AllocatorType, typename SetAllocator> int32 UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetLODBoneIndexFromSkeletonBoneIndex (int32 SkeletionBoneIndex) const inline
Definition at line 250 of file ReferencePose.h.
GetLODBoneIndexToMeshBoneIndexMap()
template<typename AllocatorType, typename SetAllocator> const TArrayView< const FBoneIndexType > UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetLODBoneIndexToMeshBoneIndexMap (int32 LODLevel) const inline
Definition at line 163 of file ReferencePose.h.
GetLODBoneIndexToParentLODBoneIndexMap()
template<typename AllocatorType, typename SetAllocator> const TArrayView< const FBoneIndexType > UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetLODBoneIndexToParentLODBoneIndexMap (int32 LODLevel) const inline
Definition at line 147 of file ReferencePose.h.
Referenced by UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODParentBoneIndex().
GetLODBoneIndexToSkeletonBoneIndexMap()
template<typename AllocatorType, typename SetAllocator> const TArrayView< const FBoneIndexType > UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetLODBoneIndexToSkeletonBoneIndexMap (int32 LODLevel) const inline
Definition at line 179 of file ReferencePose.h.
GetLODParentBoneIndex()
template<typename AllocatorType, typename SetAllocator> int32 UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetLODParentBoneIndex (int32 LODLevel, int32 LODBoneIndex) const inline
Definition at line 256 of file ReferencePose.h.
GetMeshBoneIndexFromLODBoneIndex()
template<typename AllocatorType, typename SetAllocator> int32 UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetMeshBoneIndexFromLODBoneIndex (int32 LODBoneIndex) const inline
Definition at line 222 of file ReferencePose.h.
GetMeshBoneIndexToLODBoneIndexMap()
template<typename AllocatorType, typename SetAllocator> const TArrayView< const FBoneIndexType > UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetMeshBoneIndexToLODBoneIndexMap () const inline
Definition at line 201 of file ReferencePose.h.
GetMeshBoneIndexToParentMeshBoneIndexMap()
template<typename AllocatorType, typename SetAllocator> TConstArrayView< FBoneIndexType > UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetMeshBoneIndexToParentMeshBoneIndexMap () const inline
Definition at line 230 of file ReferencePose.h.
GetNumBonesForLOD()
template<typename AllocatorType, typename SetAllocator> int32 UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetNumBonesForLOD (int32 LODLevel) const inline
Definition at line 88 of file ReferencePose.h.
Referenced by UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToMeshBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToParentLODBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToSkeletonBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::IsBoneEnabled(), and UE::AnimNext::TLODPose< FDefaultAllocator >::PrepareForLOD().
GetRefPoseRotation()
template<typename AllocatorType, typename SetAllocator> const FQuat UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetRefPoseRotation (int32 LODBoneIndex) const inline
Definition at line 287 of file ReferencePose.h.
GetRefPoseScale3D()
template<typename AllocatorType, typename SetAllocator> const FVector UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetRefPoseScale3D (int32 LODBoneIndex) const inline
Definition at line 303 of file ReferencePose.h.
GetRefPoseTransform()
template<typename AllocatorType, typename SetAllocator> FTransform UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetRefPoseTransform (int32 LODBoneIndex) const inline
Definition at line 279 of file ReferencePose.h.
GetRefPoseTranslation()
template<typename AllocatorType, typename SetAllocator> const FVector UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetRefPoseTranslation (int32 LODBoneIndex) const inline
Definition at line 295 of file ReferencePose.h.
GetSkeletalMeshAsset()
template<typename AllocatorType, typename SetAllocator> const USkeletalMesh * UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetSkeletalMeshAsset () const inline
Definition at line 270 of file ReferencePose.h.
GetSkeletonAsset()
template<typename AllocatorType, typename SetAllocator> const USkeleton * UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetSkeletonAsset () const inline
Definition at line 274 of file ReferencePose.h.
GetSkeletonBoneIndexFromLODBoneIndex()
template<typename AllocatorType, typename SetAllocator> int32 UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetSkeletonBoneIndexFromLODBoneIndex (int32 LODBoneIndex) const inline
Definition at line 236 of file ReferencePose.h.
GetSkeletonBoneIndexToLODBoneIndexMap()
template<typename AllocatorType, typename SetAllocator> const TArrayView< const FBoneIndexType > UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetSkeletonBoneIndexToLODBoneIndexMap () const inline
Definition at line 195 of file ReferencePose.h.
GetSourceLODLevel()
template<typename AllocatorType, typename SetAllocator> int32 UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GetSourceLODLevel () const inline
Definition at line 316 of file ReferencePose.h.
Initialize()
template<typename AllocatorType, typename SetAllocator> void UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::Initialize (const FReferenceSkeleton & RefSkeleton, const TArray< TArray< FBoneIndexType > > & InLODBoneIndexToParentLODBoneIndexMapPerLOD, const TArray< TArray< FBoneIndexType > > & InLODBoneIndexToMeshBoneIndexMapPerLOD, const TArray< TArray< FBoneIndexType > > & InLODBoneIndexToSkeletonBoneIndexMapPerLOD, const TArray< FBoneIndexType > & InSkeletonBoneIndexToLODBoneIndexMap, const TArray< FBoneIndexType > & InMeshBoneIndexToLODBoneIndexMap, const TArray< int32, AllocatorType > & InLODNumBones, const TMap< FName, FBoneIndexType > & InNameToLODBoneIndexMap, bool bFastPath) inline
Definition at line 105 of file ReferencePose.h.
IsBoneEnabled()
template<typename AllocatorType, typename SetAllocator> bool UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::IsBoneEnabled (int32 BoneIndex, int32 LODLevel) const inline
Definition at line 95 of file ReferencePose.h.
IsFastPath()
template<typename AllocatorType, typename SetAllocator> bool UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::IsFastPath () const inline
Definition at line 100 of file ReferencePose.h.
Referenced by UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToMeshBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToParentLODBoneIndexMap(), and UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToSkeletonBoneIndexMap().
IsValid()
template<typename AllocatorType, typename SetAllocator> bool UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::IsValid () const inline
Definition at line 83 of file ReferencePose.h.
Field Documentation
BoneNameToLODBoneIndexMap
template<typename AllocatorType, typename SetAllocator> TMap<FName, FBoneIndexType, SetAllocator> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::BoneNameToLODBoneIndexMap
Definition at line 72 of file ReferencePose.h.
GenerationFlags
template<typename AllocatorType, typename SetAllocator> EReferencePoseGenerationFlags UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::GenerationFlags = EReferencePoseGenerationFlags::None
Definition at line 77 of file ReferencePose.h.
LODBoneIndexToMeshBoneIndexMapPerLOD
template<typename AllocatorType, typename SetAllocator> TArray<TArray<FBoneIndexType, AllocatorType>, AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::LODBoneIndexToMeshBoneIndexMapPerLOD
Definition at line 46 of file ReferencePose.h.
LODBoneIndexToParentLODBoneIndexMapPerLOD
template<typename AllocatorType, typename SetAllocator> TArray<TArray<FBoneIndexType, AllocatorType>, AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::LODBoneIndexToParentLODBoneIndexMapPerLOD
Definition at line 41 of file ReferencePose.h.
LODBoneIndexToSkeletonBoneIndexMapPerLOD
template<typename AllocatorType, typename SetAllocator> TArray<TArray<FBoneIndexType, AllocatorType>, AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::LODBoneIndexToSkeletonBoneIndexMapPerLOD
Definition at line 51 of file ReferencePose.h.
LODNumBones
template<typename AllocatorType, typename SetAllocator> TArray<int32, AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::LODNumBones
Definition at line 66 of file ReferencePose.h.
MeshBoneIndexToLODBoneIndexMap
template<typename AllocatorType, typename SetAllocator> TArray<FBoneIndexType, AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::MeshBoneIndexToLODBoneIndexMap
Definition at line 63 of file ReferencePose.h.
MeshBoneIndexToParentMeshBoneIndexMap
template<typename AllocatorType, typename SetAllocator> TArray<FBoneIndexType, AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::MeshBoneIndexToParentMeshBoneIndexMap
Definition at line 69 of file ReferencePose.h.
ReferenceLocalTransforms
template<typename AllocatorType, typename SetAllocator> TTransformArray<AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::ReferenceLocalTransforms
Definition at line 36 of file ReferencePose.h.
Referenced by UE::AnimNext::FLODPose::CopyFrom().
RootBoneIndex
template<typename AllocatorType, typename SetAllocator> FBoneIndexType UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::RootBoneIndex = 0 static constexpr
Definition at line 79 of file ReferencePose.h.
SkeletalMesh
template<typename AllocatorType, typename SetAllocator> TWeakObjectPtr<const USkeletalMesh> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::SkeletalMesh = nullptr
Definition at line 75 of file ReferencePose.h.
SkeletalMeshComponent
template<typename AllocatorType, typename SetAllocator> TWeakObjectPtr<const USkeletalMeshComponent> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::SkeletalMeshComponent = nullptr
Definition at line 74 of file ReferencePose.h.
Skeleton
template<typename AllocatorType, typename SetAllocator> TWeakObjectPtr<const USkeleton> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::Skeleton = nullptr
Definition at line 76 of file ReferencePose.h.
SkeletonBoneIndexToLODBoneIndexMap
template<typename AllocatorType, typename SetAllocator> TArray<FBoneIndexType, AllocatorType> UE::AnimNext::TReferencePose< AllocatorType, SetAllocator >::SkeletonBoneIndexToLODBoneIndexMap
Definition at line 57 of file ReferencePose.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNext/Source/AnimNext/Public/ReferencePose.h