Unreal Engine 5.6 C++ API: FReplayPlaylistTracker Struct Reference
FReplayPlaylistTracker Struct Reference
Used with UGameInstance::PlayReplayPlaylist to manage playing a set of Replays in succession.
#include "ReplayPlaylistTracker.h"
Public Member Functions
~FReplayPlaylistTracker ()
const TArrayView< const FString > GetAdditionalOptions () const
Gets the last updated value of AdditionalOptions.
const int32 GetCurrentReplay () const
Gets the index of the current replay in the playlist.
class UGameInstance * GetGameInstance () const
Gets the GameInstance used to start replays.
const int32 GetNumReplays () const
Gets the number of replays in the playlist.
const TArrayView< const FString > GetPlaylist () const
Gets the actual playlist.
class UWorld * GetWorldOverride () const
Gets the last updated value of WorldOverride.
const int32 IsOnLastReplay () const
Whether or not we're currently on the last replay in a playlist.
Public Member Functions inherited from TSharedFromThis< FReplayPlaylistTracker >
TSharedRef< FReplayPlaylistTracker, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FReplayPlaylistTracker, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Types
using ThisClass = FReplayPlaylistTracker
Private Member Functions
FReplayPlaylistTracker (const FReplayPlaylistParams &Params, class UGameInstance *InGameInstance)
void OnDemoPlaybackFailed (UWorld *InWorld, const UE::Net::TNetResult< EReplayResult > &Result)
Called if an error occurs after the replay was requested to start (successfully), but before the replay actually starts.
void OnDemoPlaybackFinished (UWorld *InWorld)
Called when a replay has reached its end.
void OnDemoStopped (UWorld *InWorld)
Called when the DemoNetDriver hits a Hard Stop, like an error or a user requesting a stop.
void PlayNextReplay ()
void Quit ()
void Reset ()
bool Restart ()
bool Start ()
Private Attributes
TArray< FString > AdditionalOptions
bool bIsStartingReplay
int32 CurrentReplay
TWeakObjectPtr< class UDemoNetDriver > DemoNetDriver
TWeakObjectPtr< class UGameInstance > GameInstance
FDelegateHandle OnDemoPlaybackFailedHandle
FDelegateHandle OnDemoPlaybackFinishedHandle
FDelegateHandle OnDemoStoppedHandle
TArray< FString > Playlist
FPreStartNextPlaylistReplay PreStartNextReplay
TWeakObjectPtr< class UWorld > WorldOverride
Friends
class FDemoNetDriverReplayPlaylistHelper
class FGameInstanceReplayPlaylistHelper
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FReplayPlaylistTracker >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Static Protected Member Functions inherited from TSharedFromThis< FReplayPlaylistTracker >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Used with UGameInstance::PlayReplayPlaylist to manage playing a set of Replays in succession.
Definition at line 44 of file ReplayPlaylistTracker.h.
Member Typedef Documentation
ThisClass
using FReplayPlaylistTracker::ThisClass = FReplayPlaylistTracker private
Definition at line 48 of file ReplayPlaylistTracker.h.
Constructor & Destructor Documentation
~FReplayPlaylistTracker()
FReplayPlaylistTracker::~FReplayPlaylistTracker () inline
Definition at line 54 of file ReplayPlaylistTracker.h.
References bIsStartingReplay, and Reset().
FReplayPlaylistTracker()
FReplayPlaylistTracker::FReplayPlaylistTracker (const FReplayPlaylistParams & Params, class UGameInstance * InGameInstance) private
References Params.
Member Function Documentation
GetAdditionalOptions()
const TArrayView< const FString > FReplayPlaylistTracker::GetAdditionalOptions () const inline
Gets the last updated value of AdditionalOptions.
Definition at line 86 of file ReplayPlaylistTracker.h.
References AdditionalOptions.
GetCurrentReplay()
const int32 FReplayPlaylistTracker::GetCurrentReplay () const inline
Gets the index of the current replay in the playlist.
Definition at line 74 of file ReplayPlaylistTracker.h.
References CurrentReplay.
Referenced by IsOnLastReplay().
GetGameInstance()
class UGameInstance * FReplayPlaylistTracker::GetGameInstance () const inline
Gets the GameInstance used to start replays.
Definition at line 98 of file ReplayPlaylistTracker.h.
References GameInstance.
GetNumReplays()
const int32 FReplayPlaylistTracker::GetNumReplays () const inline
Gets the number of replays in the playlist.
Definition at line 68 of file ReplayPlaylistTracker.h.
References Playlist.
Referenced by IsOnLastReplay().
GetPlaylist()
const TArrayView< const FString > FReplayPlaylistTracker::GetPlaylist () const inline
Gets the actual playlist.
Definition at line 80 of file ReplayPlaylistTracker.h.
References Playlist.
GetWorldOverride()
class UWorld * FReplayPlaylistTracker::GetWorldOverride () const inline
Gets the last updated value of WorldOverride.
Definition at line 92 of file ReplayPlaylistTracker.h.
References WorldOverride.
IsOnLastReplay()
const int32 FReplayPlaylistTracker::IsOnLastReplay () const inline
Whether or not we're currently on the last replay in a playlist.
Definition at line 62 of file ReplayPlaylistTracker.h.
References GetCurrentReplay(), and GetNumReplays().
OnDemoPlaybackFailed()
void FReplayPlaylistTracker::OnDemoPlaybackFailed (UWorld * InWorld, const UE::Net::TNetResult< EReplayResult > & Result) private
Called if an error occurs after the replay was requested to start (successfully), but before the replay actually starts.
OnDemoPlaybackFinished()
void FReplayPlaylistTracker::OnDemoPlaybackFinished (UWorld * InWorld) private
Called when a replay has reached its end.
OnDemoStopped()
void FReplayPlaylistTracker::OnDemoStopped (UWorld * InWorld) private
Called when the DemoNetDriver hits a Hard Stop, like an error or a user requesting a stop.
PlayNextReplay()
void FReplayPlaylistTracker::PlayNextReplay () private
Quit()
void FReplayPlaylistTracker::Quit () private
Reset()
void FReplayPlaylistTracker::Reset () private
Referenced by ~FReplayPlaylistTracker().
Restart()
bool FReplayPlaylistTracker::Restart () private
Start()
bool FReplayPlaylistTracker::Start () private
Friends And Related Symbol Documentation
FDemoNetDriverReplayPlaylistHelper
friend class FDemoNetDriverReplayPlaylistHelper friend
Definition at line 50 of file ReplayPlaylistTracker.h.
References FDemoNetDriverReplayPlaylistHelper.
Referenced by FDemoNetDriverReplayPlaylistHelper.
FGameInstanceReplayPlaylistHelper
friend class FGameInstanceReplayPlaylistHelper friend
Definition at line 49 of file ReplayPlaylistTracker.h.
References FGameInstanceReplayPlaylistHelper.
Referenced by FGameInstanceReplayPlaylistHelper.
Field Documentation
AdditionalOptions
TArray<FString> FReplayPlaylistTracker::AdditionalOptions private
Definition at line 129 of file ReplayPlaylistTracker.h.
Referenced by GetAdditionalOptions().
bIsStartingReplay
bool FReplayPlaylistTracker::bIsStartingReplay private
Definition at line 126 of file ReplayPlaylistTracker.h.
Referenced by ~FReplayPlaylistTracker().
CurrentReplay
int32 FReplayPlaylistTracker::CurrentReplay private
Definition at line 127 of file ReplayPlaylistTracker.h.
Referenced by GetCurrentReplay().
DemoNetDriver
TWeakObjectPtr<class UDemoNetDriver> FReplayPlaylistTracker::DemoNetDriver private
Definition at line 132 of file ReplayPlaylistTracker.h.
GameInstance
TWeakObjectPtr<class UGameInstance> FReplayPlaylistTracker::GameInstance private
Definition at line 131 of file ReplayPlaylistTracker.h.
Referenced by GetGameInstance().
OnDemoPlaybackFailedHandle
FDelegateHandle FReplayPlaylistTracker::OnDemoPlaybackFailedHandle private
Definition at line 134 of file ReplayPlaylistTracker.h.
OnDemoPlaybackFinishedHandle
FDelegateHandle FReplayPlaylistTracker::OnDemoPlaybackFinishedHandle private
Definition at line 135 of file ReplayPlaylistTracker.h.
OnDemoStoppedHandle
FDelegateHandle FReplayPlaylistTracker::OnDemoStoppedHandle private
Definition at line 136 of file ReplayPlaylistTracker.h.
Playlist
TArray<FString> FReplayPlaylistTracker::Playlist private
Definition at line 128 of file ReplayPlaylistTracker.h.
Referenced by GetNumReplays(), and GetPlaylist().
PreStartNextReplay
FPreStartNextPlaylistReplay FReplayPlaylistTracker::PreStartNextReplay private
Definition at line 138 of file ReplayPlaylistTracker.h.
WorldOverride
TWeakObjectPtr<class UWorld> FReplayPlaylistTracker::WorldOverride private
Definition at line 130 of file ReplayPlaylistTracker.h.
Referenced by GetWorldOverride().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Net/ReplayPlaylistTracker.h