Unreal Engine 5.6 C++ API: FCoreRedirects::FRedirectTypeMap Struct Reference
FCoreRedirects::FRedirectTypeMap Struct Reference
Map from name of thing being mapped to full list.
Public Member Functions
FRedirectTypeMap ()=default
FRedirectTypeMap (const FRedirectTypeMap &&Other)=delete
FRedirectTypeMap (const FRedirectTypeMap &Other)
TArray< TPair< ECoreRedirectFlags, FRedirectNameMap > >::RangedForIteratorType begin ()
void Empty ()
TArray< TPair< ECoreRedirectFlags, FRedirectNameMap > >::RangedForIteratorType end ()
FRedirectNameMap * Find (ECoreRedirectFlags Key)
FRedirectNameMap & FindOrAdd (ECoreRedirectFlags Key)
FRedirectTypeMap & operator= (const FRedirectTypeMap &&Other)=delete
FRedirectTypeMap & operator= (const FRedirectTypeMap &Other)
Private Attributes
TArray< TPair< ECoreRedirectFlags, FRedirectNameMap > > FastIterable
TMap< ECoreRedirectFlags, FRedirectNameMap * > Map
Detailed Description
Map from name of thing being mapped to full list.
List must be filtered further
Definition at line 501 of file CoreRedirects.h.
Constructor & Destructor Documentation
FRedirectTypeMap() [1/3]
FCoreRedirects::FRedirectTypeMap::FRedirectTypeMap () default
Referenced by FRedirectTypeMap(), FRedirectTypeMap(), operator=(), and operator=().
FRedirectTypeMap() [2/3]
FCoreRedirects::FRedirectTypeMap::FRedirectTypeMap (const FRedirectTypeMap & Other)
References FRedirectTypeMap(), and Other.
FRedirectTypeMap() [3/3]
FCoreRedirects::FRedirectTypeMap::FRedirectTypeMap (const FRedirectTypeMap && Other) delete
References FRedirectTypeMap(), and Other.
Member Function Documentation
begin()
TArray< TPair< ECoreRedirectFlags, FRedirectNameMap > >::RangedForIteratorType FCoreRedirects::FRedirectTypeMap::begin () inline
Definition at line 511 of file CoreRedirects.h.
References FastIterable.
Empty()
void FCoreRedirects::FRedirectTypeMap::Empty ()
end()
TArray< TPair< ECoreRedirectFlags, FRedirectNameMap > >::RangedForIteratorType FCoreRedirects::FRedirectTypeMap::end () inline
Definition at line 512 of file CoreRedirects.h.
References FastIterable.
Find()
FRedirectNameMap * FCoreRedirects::FRedirectTypeMap::Find (ECoreRedirectFlags Key)
References Key.
FindOrAdd()
FRedirectNameMap & FCoreRedirects::FRedirectTypeMap::FindOrAdd (ECoreRedirectFlags Key)
References Key.
operator=() [1/2]
FRedirectTypeMap & FCoreRedirects::FRedirectTypeMap::operator= (const FRedirectTypeMap && Other) delete
References FRedirectTypeMap(), and Other.
operator=() [2/2]
FRedirectTypeMap & FCoreRedirects::FRedirectTypeMap::operator= (const FRedirectTypeMap & Other)
References FRedirectTypeMap(), and Other.
Field Documentation
FastIterable
TArray<TPair<ECoreRedirectFlags, FRedirectNameMap> > FCoreRedirects::FRedirectTypeMap::FastIterable private
Definition at line 518 of file CoreRedirects.h.
Referenced by begin(), and end().
Map
TMap<ECoreRedirectFlags, FRedirectNameMap*> FCoreRedirects::FRedirectTypeMap::Map private
Definition at line 517 of file CoreRedirects.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/CoreRedirects.h