Unreal Engine 5.6 C++ API: FRedirectCollector::FSimpleOrChainedRedirect Struct Reference
FRedirectCollector::FSimpleOrChainedRedirect Struct Reference
Variant structure to save memory for storing redirects' target data: most redirects are non-chained, and FirstTarget == FinalTarget; a few can end up being chained and we need to store extra data for them.
#include "RedirectCollector.h"
Public Member Functions
FSimpleOrChainedRedirect ()
FSimpleOrChainedRedirect (FSoftObjectPath InFirstTarget, FSoftObjectPath InFinalTarget)
FSimpleOrChainedRedirect (FSoftObjectPath InSimpleTarget)
const FSoftObjectPath & GetFinalTarget () const
const FSoftObjectPath & GetFirstTarget () const
bool IsChainedRedirect () const
bool IsSimpleRedirect () const
Static Public Member Functions
static FSimpleOrChainedRedirect ConstructSimpleOrChained (FSoftObjectPath InFirstTarget, FSoftObjectPath InFinalTarget)
Private Attributes
TVariant< FSoftObjectPath, TUniquePtr< FChainedRedirectionData > > Data
Detailed Description
Variant structure to save memory for storing redirects' target data: most redirects are non-chained, and FirstTarget == FinalTarget; a few can end up being chained and we need to store extra data for them.
Definition at line 220 of file RedirectCollector.h.
Constructor & Destructor Documentation
FSimpleOrChainedRedirect() [1/3]
FRedirectCollector::FSimpleOrChainedRedirect::FSimpleOrChainedRedirect () inline
Definition at line 267 of file RedirectCollector.h.
References Data.
Referenced by ConstructSimpleOrChained().
FSimpleOrChainedRedirect() [2/3]
FRedirectCollector::FSimpleOrChainedRedirect::FSimpleOrChainedRedirect (FSoftObjectPath InSimpleTarget) inline
Definition at line 272 of file RedirectCollector.h.
References Data, and MoveTemp().
FSimpleOrChainedRedirect() [3/3]
FRedirectCollector::FSimpleOrChainedRedirect::FSimpleOrChainedRedirect (FSoftObjectPath InFirstTarget, FSoftObjectPath InFinalTarget) inline
Definition at line 278 of file RedirectCollector.h.
References Data, and MoveTemp().
Member Function Documentation
ConstructSimpleOrChained()
FRedirectCollector::FSimpleOrChainedRedirect FRedirectCollector::FSimpleOrChainedRedirect::ConstructSimpleOrChained (FSoftObjectPath InFirstTarget, FSoftObjectPath InFinalTarget) inline static
Definition at line 286 of file RedirectCollector.h.
References FSimpleOrChainedRedirect(), and MoveTemp().
GetFinalTarget()
const FSoftObjectPath & FRedirectCollector::FSimpleOrChainedRedirect::GetFinalTarget () const inline
Definition at line 301 of file RedirectCollector.h.
References Data, and IsSimpleRedirect().
GetFirstTarget()
const FSoftObjectPath & FRedirectCollector::FSimpleOrChainedRedirect::GetFirstTarget () const inline
Definition at line 294 of file RedirectCollector.h.
References Data, and IsSimpleRedirect().
IsChainedRedirect()
bool FRedirectCollector::FSimpleOrChainedRedirect::IsChainedRedirect () const inline
Definition at line 313 of file RedirectCollector.h.
References Data.
IsSimpleRedirect()
bool FRedirectCollector::FSimpleOrChainedRedirect::IsSimpleRedirect () const inline
Definition at line 308 of file RedirectCollector.h.
References Data.
Referenced by GetFinalTarget(), and GetFirstTarget().
Field Documentation
Data
TVariant<FSoftObjectPath, TUniquePtr<FChainedRedirectionData> > FRedirectCollector::FSimpleOrChainedRedirect::Data private
Definition at line 235 of file RedirectCollector.h.
Referenced by FSimpleOrChainedRedirect(), FSimpleOrChainedRedirect(), FSimpleOrChainedRedirect(), GetFinalTarget(), GetFirstTarget(), IsChainedRedirect(), and IsSimpleRedirect().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Misc/RedirectCollector.h