Unreal Engine 5.6 C++ API: FSlateIcon Struct Reference
FSlateIcon Struct Reference
Struct used to represent an icon in Slate.
#include "SlateIcon.h"
Public Member Functions
FSlateIcon ()
Default constructor (empty icon).
FSlateIcon (const FName InStyleSetName, const FName InStyleName, const FName InSmallStyleName=NAME_None, const FName InStatusOverlayStyleName=NAME_None)
Creates and initializes a new icon from a style set and style name.
const FSlateBrush * GetIcon () const
Gets the resolved icon.
const FSlateBrush * GetOptionalIcon () const
Optionally gets the resolved icon, returning nullptr if it's not defined.
const FSlateBrush * GetOptionalSmallIcon () const
Optionally gets the resolved small icon, returning nullptr if it's not defined.
const FSlateBrush * GetOverlayIcon () const
const FSlateBrush * GetSmallIcon () const
Gets the resolved small icon.
const FName & GetSmallStyleName () const
Gets the name of the style for the icon.
const FName & GetStyleName () const
Gets the name of the style for the icon.
const class ISlateStyle * GetStyleSet () const
Gets the resolved style set.
const FName & GetStyleSetName () const
Gets the name of the style set the icon can be found in.
const bool IsSet () const
Checks whether the icon is set to something.
Private Attributes
FName SmallStyleName
FName StatusOverlayStyleName
FName StyleName
FName StyleSetName
Friends
bool operator!= (const FSlateIcon &A, const FSlateIcon &B)
Compare 2 slate icons for inequality.
bool operator== (const FSlateIcon &A, const FSlateIcon &B)
Compare 2 slate icons for equality.
Detailed Description
Struct used to represent an icon in Slate.
Definition at line 12 of file SlateIcon.h.
Constructor & Destructor Documentation
FSlateIcon() [1/2]
FSlateIcon::FSlateIcon ()
Default constructor (empty icon).
Referenced by operator!=, and operator==.
FSlateIcon() [2/2]
FSlateIcon::FSlateIcon (const FName InStyleSetName, const FName InStyleName, const FName InSmallStyleName = NAME_None, const FName InStatusOverlayStyleName = NAME_None)
Creates and initializes a new icon from a style set and style name.
Parameters
InStyleSetName The name of the style set the icon can be found in.
StyleName The name of the style for the icon
InSmallStyleName The name of the style for the small icon
InStatusOverlayStyleName The name of the style for a status icon to overlay on the base image
Member Function Documentation
GetIcon()
const FSlateBrush * FSlateIcon::GetIcon () const
Gets the resolved icon.
Returns
Icon brush, or FStyleDefaults::GetNoBrush() if the icon wasn't found.
See also
GetSmallIcon
Referenced by FSlateIconFinder::FindCustomIconBrushForClass(), and FSlateIconFinder::FindIconBrushForClass().
GetOptionalIcon()
const FSlateBrush * FSlateIcon::GetOptionalIcon () const
Optionally gets the resolved icon, returning nullptr if it's not defined.
Returns
Icon brush, or nullptr if the icon wasn't found.
GetOptionalSmallIcon()
const FSlateBrush * FSlateIcon::GetOptionalSmallIcon () const
Optionally gets the resolved small icon, returning nullptr if it's not defined.
Returns
Icon brush, or nullptr if the icon wasn't found.
GetOverlayIcon()
const FSlateBrush * FSlateIcon::GetOverlayIcon () const
GetSmallIcon()
const FSlateBrush * FSlateIcon::GetSmallIcon () const
Gets the resolved small icon.
Returns
Icon brush, or FStyleDefaults::GetNoBrush() if the icon wasn't found.
See also
GetIcon
GetSmallStyleName()
const FName & FSlateIcon::GetSmallStyleName () const inline
Gets the name of the style for the icon.
Returns
Style name.
See also
GetStyleName, GetStyleSet, GetStyleSetName
Definition at line 91 of file SlateIcon.h.
References SmallStyleName.
GetStyleName()
const FName & FSlateIcon::GetStyleName () const inline
Gets the name of the style for the icon.
Returns
Style name.
See also
GetSmallStyleName, GetStyleSet, GetStyleSetName
Definition at line 102 of file SlateIcon.h.
References StyleName.
GetStyleSet()
const class ISlateStyle * FSlateIcon::GetStyleSet () const
Gets the resolved style set.
Returns
Style set, or nullptr if the style set wasn't found.
See also
GetSmallStyleName, GetStyleName, GetStyleSetName
GetStyleSetName()
const FName & FSlateIcon::GetStyleSetName () const inline
Gets the name of the style set the icon can be found in.
Returns
Style name.
See also
GetSmallStyleName, GetStyleName, GetStyleSet
Definition at line 121 of file SlateIcon.h.
References StyleSetName.
IsSet()
const bool FSlateIcon::IsSet () const inline
Checks whether the icon is set to something.
Returns
true if the icon is set, false otherwise.
Definition at line 131 of file SlateIcon.h.
References StyleName, and StyleSetName.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FSlateIcon & A, const FSlateIcon & B) friend
Compare 2 slate icons for inequality.
Definition at line 46 of file SlateIcon.h.
References FSlateIcon(), A, and B.
operator==
bool operator== (const FSlateIcon & A, const FSlateIcon & B) friend
Compare 2 slate icons for equality.
Definition at line 34 of file SlateIcon.h.
References FSlateIcon(), A, and B.
Field Documentation
SmallStyleName
FName FSlateIcon::SmallStyleName private
Definition at line 145 of file SlateIcon.h.
Referenced by GetSmallStyleName().
StatusOverlayStyleName
FName FSlateIcon::StatusOverlayStyleName private
Definition at line 148 of file SlateIcon.h.
StyleName
FName FSlateIcon::StyleName private
Definition at line 142 of file SlateIcon.h.
Referenced by GetStyleName(), and IsSet().
StyleSetName
FName FSlateIcon::StyleSetName private
Definition at line 139 of file SlateIcon.h.
Referenced by GetStyleSetName(), and IsSet().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Textures/SlateIcon.h