Unreal Engine 5.6 C++ API: UE::SourceLocation::FFullAdapter Struct Reference
UE::SourceLocation::FFullAdapter Struct Reference
Adapter for formatting a source location with full information.
#include "SourceLocationUtils.h"
Public Member Functions
void AppendString (FUtf8StringBuilderBase &Out) const
void AppendString (FWideStringBuilderBase &Out) const
Converts the source location to a readable format with full information, appending to an existing string.
FString ToString () const
Converts the source location to a readable format with full information.
void ToString (FUtf8String &Out) const
void ToString (FWideString &Out) const
Converts the source location to a readable format with full information, in place.
FUtf8String ToUtf8String () const
Data Fields
const FSourceLocation & Location
Friends
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase &Builder, const FFullAdapter &Adapter)
FWideStringBuilderBase & operator<< (FWideStringBuilderBase &Builder, const FFullAdapter &Adapter)
void SerializeForLog (FCbWriter &Writer, const FFullAdapter &Adapter)
Detailed Description
Adapter for formatting a source location with full information.
Definition at line 27 of file SourceLocationUtils.h.
Member Function Documentation
AppendString() [1/2]
void UE::SourceLocation::FFullAdapter::AppendString (FUtf8StringBuilderBase & Out) const
AppendString() [2/2]
void UE::SourceLocation::FFullAdapter::AppendString (FWideStringBuilderBase & Out) const
Converts the source location to a readable format with full information, appending to an existing string.
Parameters
Out StringBuilder to append with the string representation of the source location.
Referenced by operator<<, and operator<<.
ToString() [1/3]
FString UE::SourceLocation::FFullAdapter::ToString () const nodiscard
Converts the source location to a readable format with full information.
Returns
String representation of the source location.
ToString() [2/3]
void UE::SourceLocation::FFullAdapter::ToString (FUtf8String & Out) const
ToString() [3/3]
void UE::SourceLocation::FFullAdapter::ToString (FWideString & Out) const
Converts the source location to a readable format with full information, in place.
Parameters
Out String to fill with the string representation of the source location.
ToUtf8String()
FUtf8String UE::SourceLocation::FFullAdapter::ToUtf8String () const nodiscard
Friends And Related Symbol Documentation
operator<< [1/2]
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase & Builder, const FFullAdapter & Adapter) friend
Definition at line 65 of file SourceLocationUtils.h.
References AppendString().
operator<< [2/2]
FWideStringBuilderBase & operator<< (FWideStringBuilderBase & Builder, const FFullAdapter & Adapter) friend
Definition at line 60 of file SourceLocationUtils.h.
References AppendString().
SerializeForLog
void SerializeForLog (FCbWriter & Writer, const FFullAdapter & Adapter) friend
Definition at line 55 of file SourceLocationUtils.h.
References Location, and UE::SourceLocation::Private::SerializeForLogFull().
Field Documentation
Location
const FSourceLocation& UE::SourceLocation::FFullAdapter::Location
Definition at line 29 of file SourceLocationUtils.h.
Referenced by SerializeForLog.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/SourceLocationUtils.h