Unreal Engine 5.6 C++ API: TNetSimCueDispatcher< ModelDef > Struct Template Reference
TNetSimCueDispatcher< ModelDef > Struct Template Reference
#include "NetworkPredictionCues.h"
Public Types
using DriverType = typename ModelDef::Driver
Public Member Functions
template<typename T>
void DispatchCueRecord (T &Handler, const int32 SimFrame, const int32 CurrentSimTime, const int32 FixedTimeStepMS)
FString GetDebugName () const final override
void NetRecvSavedCues (FArchive &Ar, const bool bSerializeFrameNumber, const int32 InLastRecvFrame, const int32 InLastRecvTime)
void NetSendSavedCues (FArchive &Ar, ENetSimCueReplicationTarget ReplicationMask, bool bSerializeFrameNumber)
void NotifyRollback (int32 InRollbackFrame)
void SetReceiveReplicationTarget (ENetSimCueReplicationTarget InReplicationMask)
Public Member Functions inherited from FNetSimCueDispatcher
virtual ~FNetSimCueDispatcher ()=default
const FContext & GetContext () const
template<typename T, typename... ArgsType>
void Invoke (ArgsType &&... Args)
void PopContext ()
void PushContext (const FContext &InContext)
Data Fields
DriverType * Driver = nullptr
Private Attributes
int32 LastRecvFrame = INDEX_NONE
int32 LastRecvMS = 0
ENetSimCueReplicationTarget RecvReplicationMask
Additional Inherited Members
Protected Member Functions inherited from FNetSimCueDispatcher
bool EnsureValidContext ()
TArray< FSavedCue > & GetBuffer (const bool &bTransient)
Protected Attributes inherited from FNetSimCueDispatcher
FContext Context
int32 RollbackFrame = INDEX_NONE
TArray< FSavedCue > SavedCues
TArray< FSavedCue > TransientCues
Detailed Description
template<typename ModelDef = void>
struct TNetSimCueDispatcher< ModelDef >
Definition at line 569 of file NetworkPredictionCues.h.
Member Typedef Documentation
DriverType
template<typename ModelDef = void> using TNetSimCueDispatcher< ModelDef >::DriverType = typename ModelDef::Driver
Definition at line 571 of file NetworkPredictionCues.h.
Member Function Documentation
DispatchCueRecord()
template<typename ModelDef = void> template<typename T> void TNetSimCueDispatcher< ModelDef >::DispatchCueRecord (T & Handler, const int32 SimFrame, const int32 CurrentSimTime, const int32 FixedTimeStepMS) inline
Definition at line 676 of file NetworkPredictionCues.h.
References FSavedCue::bDispatched, FSavedCue::bNetConfirmed, FSavedCue::bPendingResimulateRollback, FSavedCue::Callbacks, FSavedCue::Frame, TCueDispatchTable< TCueHandler >::Get(), FSavedCue::GetDebugName(), GetDebugName(), INDEX_NONE, LastRecvFrame, LastRecvMS, Log, FMath::Min, No, npEnsureSlow, FCueDispatcherTraitsBase::ReplicationWindowFrames(), FCueDispatcherTraitsBase::ReplicationWindowMS(), FNetSimCueDispatcher::RollbackFrame, FNetSimCueDispatcher::SavedCues, TEXT, Time, FSavedCue::Time, FNetSimCueDispatcher::TransientCues, UE_CLOG, UE_LOG, and Warning.
GetDebugName()
template<typename ModelDef = void> FString TNetSimCueDispatcher< ModelDef >::GetDebugName () const inline final override virtual
Implements FNetSimCueDispatcher.
Definition at line 836 of file NetworkPredictionCues.h.
References Driver, FNetworkPredictionDriverBase< ModelDef >::GetDebugString(), and TStringBuilderBase< CharType >::ToString().
Referenced by DispatchCueRecord(), NetRecvSavedCues(), and NotifyRollback().
NetRecvSavedCues()
template<typename ModelDef = void> void TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues (FArchive & Ar, const bool bSerializeFrameNumber, const int32 InLastRecvFrame, const int32 InLastRecvTime) inline
Definition at line 602 of file NetworkPredictionCues.h.
References Ar, FSavedCue::bNetConfirmed, EnumHasAnyFlags(), FSavedCue::Frame, FSavedCue::GetDebugName(), GetDebugName(), INDEX_NONE, LastRecvFrame, LastRecvMS, Log, MoveTemp(), FSavedCue::NetIdentical(), FSavedCue::NetSerialize(), npCheckSlow, RecvReplicationMask, FSavedCue::ReplicationTarget, FNetSimCueDispatcher::SavedCues, TEXT, FSavedCue::Time, and UE_LOG.
NetSendSavedCues()
template<typename ModelDef = void> void TNetSimCueDispatcher< ModelDef >::NetSendSavedCues (FArchive & Ar, ENetSimCueReplicationTarget ReplicationMask, bool bSerializeFrameNumber) inline
Definition at line 575 of file NetworkPredictionCues.h.
References Ar, EnumHasAnyFlags(), npCheckSlow, and FNetSimCueDispatcher::SavedCues.
NotifyRollback()
template<typename ModelDef = void> void TNetSimCueDispatcher< ModelDef >::NotifyRollback (int32 InRollbackFrame) inline
Definition at line 804 of file NetworkPredictionCues.h.
References GetDebugName(), INDEX_NONE, Log, npEnsure, npEnsureSlow, FNetSimCueDispatcher::RollbackFrame, FNetSimCueDispatcher::SavedCues, TEXT, and UE_LOG.
SetReceiveReplicationTarget()
template<typename ModelDef = void> void TNetSimCueDispatcher< ModelDef >::SetReceiveReplicationTarget (ENetSimCueReplicationTarget InReplicationMask) inline
Definition at line 830 of file NetworkPredictionCues.h.
References RecvReplicationMask.
Field Documentation
Driver
template<typename ModelDef = void> DriverType* TNetSimCueDispatcher< ModelDef >::Driver = nullptr
Definition at line 835 of file NetworkPredictionCues.h.
Referenced by GetDebugName().
LastRecvFrame
template<typename ModelDef = void> int32 TNetSimCueDispatcher< ModelDef >::LastRecvFrame = INDEX_NONE private
Definition at line 854 of file NetworkPredictionCues.h.
Referenced by DispatchCueRecord(), and NetRecvSavedCues().
LastRecvMS
template<typename ModelDef = void> int32 TNetSimCueDispatcher< ModelDef >::LastRecvMS = 0 private
Definition at line 855 of file NetworkPredictionCues.h.
Referenced by DispatchCueRecord(), and NetRecvSavedCues().
RecvReplicationMask
template<typename ModelDef = void> ENetSimCueReplicationTarget TNetSimCueDispatcher< ModelDef >::RecvReplicationMask private
Definition at line 852 of file NetworkPredictionCues.h.
Referenced by NetRecvSavedCues(), and SetReceiveReplicationTarget().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionCues.h