Unreal Engine 5.6 C++ API: FGameInstancePIEResult Struct Reference
FGameInstancePIEResult Struct Reference
#include "GameInstance.h"
Public Member Functions
bool IsSuccess () const
Static Public Member Functions
static FGameInstancePIEResult Failure (const FText &InReason)
static FGameInstancePIEResult Success ()
Data Fields
bool bSuccess
FText FailureReason
Private Member Functions
FGameInstancePIEResult (bool bWasSuccess, const FText &InReason)
Detailed Description
Definition at line 68 of file GameInstance.h.
Constructor & Destructor Documentation
FGameInstancePIEResult()
FGameInstancePIEResult::FGameInstancePIEResult (bool bWasSuccess, const FText & InReason) inline private
Definition at line 93 of file GameInstance.h.
References bSuccess, and FailureReason.
Referenced by Failure(), and Success().
Member Function Documentation
Failure()
FGameInstancePIEResult FGameInstancePIEResult::Failure (const FText & InReason) inline static
Definition at line 83 of file GameInstance.h.
References FGameInstancePIEResult().
IsSuccess()
bool FGameInstancePIEResult::IsSuccess () const inline
Definition at line 88 of file GameInstance.h.
References bSuccess.
Success()
FGameInstancePIEResult FGameInstancePIEResult::Success () inline static
Definition at line 78 of file GameInstance.h.
References FGameInstancePIEResult(), and FText::GetEmpty().
Field Documentation
bSuccess
bool FGameInstancePIEResult::bSuccess
Definition at line 75 of file GameInstance.h.
Referenced by FGameInstancePIEResult(), and IsSuccess().
FailureReason
FText FGameInstancePIEResult::FailureReason
Definition at line 72 of file GameInstance.h.
Referenced by FGameInstancePIEResult().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Engine/GameInstance.h