Unreal Engine 5.6 C++ API: FAssetBundleEntry Struct Reference
FAssetBundleEntry Struct Reference
A struct representing a single AssetBundle.
#include "AssetBundleData.h"
Public Member Functions
FORCEINLINE FAssetBundleEntry ()
Declare constructors inline so this can be a header only class.
FAssetBundleEntry (const FAssetBundleEntry &)=default
FAssetBundleEntry (FAssetBundleEntry &&)=default
FAssetBundleEntry (FName InBundleName)
PRAGMA_DISABLE_DEPRECATION_WARNINGS FORCEINLINE ~FAssetBundleEntry ()
bool ExportTextItem (FString &ValueStr, const FAssetBundleEntry &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText)
bool IsValid () const
Returns true if this represents a real entry.
bool operator!= (const FAssetBundleEntry &Other) const
FAssetBundleEntry & operator= (const FAssetBundleEntry &)=default
FAssetBundleEntry & operator= (FAssetBundleEntry &&)=default
bool operator== (const FAssetBundleEntry &Other) const
Equality.
Data Fields
TArray< FTopLevelAssetPath > AssetPaths
List of references to top-level assets contained in this bundle.
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName BundleName
Specific name of this bundle, should be unique for a given scope.
Detailed Description
A struct representing a single AssetBundle.
Definition at line 20 of file AssetBundleData.h.
Constructor & Destructor Documentation
FAssetBundleEntry() [1/4]
FORCEINLINE FAssetBundleEntry::FAssetBundleEntry () inline
Declare constructors inline so this can be a header only class.
Definition at line 23 of file AssetBundleData.h.
References FORCEINLINE.
Referenced by FAssetBundleEntry(), FAssetBundleEntry(), ExportTextItem(), operator!=(), operator=(), operator=(), and operator==().
~FAssetBundleEntry()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FORCEINLINE FAssetBundleEntry::~FAssetBundleEntry () inline
Definition at line 25 of file AssetBundleData.h.
References FORCEINLINE.
FAssetBundleEntry() [2/4]
FAssetBundleEntry::FAssetBundleEntry (const FAssetBundleEntry &) default
References FAssetBundleEntry().
FAssetBundleEntry() [3/4]
FAssetBundleEntry::FAssetBundleEntry (FAssetBundleEntry &&) default
References FAssetBundleEntry().
FAssetBundleEntry() [4/4]
FAssetBundleEntry::FAssetBundleEntry (FName InBundleName) inline explicit
Definition at line 46 of file AssetBundleData.h.
References BundleName.
Member Function Documentation
ExportTextItem()
bool FAssetBundleEntry::ExportTextItem (FString & ValueStr, const FAssetBundleEntry & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
References FAssetBundleEntry(), and Parent.
ImportTextItem()
bool FAssetBundleEntry::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText)
References Buffer, and Parent.
IsValid()
bool FAssetBundleEntry::IsValid () const inline
Returns true if this represents a real entry.
Definition at line 53 of file AssetBundleData.h.
References BundleName.
operator!=()
bool FAssetBundleEntry::operator!= (const FAssetBundleEntry & Other) const inline
Definition at line 62 of file AssetBundleData.h.
References FAssetBundleEntry(), and Other.
operator=() [1/2]
FAssetBundleEntry & FAssetBundleEntry::operator= (const FAssetBundleEntry &) default
References FAssetBundleEntry().
operator=() [2/2]
FAssetBundleEntry & FAssetBundleEntry::operator= (FAssetBundleEntry &&) default
References FAssetBundleEntry(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator==()
bool FAssetBundleEntry::operator== (const FAssetBundleEntry & Other) const inline
Equality.
Definition at line 56 of file AssetBundleData.h.
References FAssetBundleEntry(), AssetPaths, BundleName, and Other.
Field Documentation
AssetPaths
TArray<FTopLevelAssetPath> FAssetBundleEntry::AssetPaths
List of references to top-level assets contained in this bundle.
Definition at line 44 of file AssetBundleData.h.
Referenced by operator==().
BundleName
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FAssetBundleEntry::BundleName
Specific name of this bundle, should be unique for a given scope.
Definition at line 35 of file AssetBundleData.h.
Referenced by FAssetBundleEntry(), IsValid(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetBundleData.h