Unreal Engine 5.6 C++ API: FMovieSceneChannelProxy Struct Reference
FMovieSceneChannelProxy Struct Reference
Proxy type stored inside UMovieSceneSection for access to all its channels.
#include "MovieSceneChannelProxy.h"
Public Member Functions
FMovieSceneChannelProxy ()
Default construction - emtpy proxy.
template<typename ChannelType>
FMovieSceneChannelProxy (ChannelType &InChannel, const FMovieSceneChannelMetaData &InMetaData)
Construction via a single channel, and its editor data Channel's address is stored internally as a voic* and should exist as long as this channel proxy does.
template<typename ChannelType, typename ExtendedEditorDataType>
FMovieSceneChannelProxy (ChannelType &InChannel, const FMovieSceneChannelMetaData &InMetaData, ExtendedEditorDataType &&InExtendedEditorData)
Construction via a single channel, and its editor data Channel's address is stored internally as a voic* and should exist as long as this channel proxy does.
FMovieSceneChannelProxy (const FMovieSceneChannelProxy &)=delete
Not copyable or moveable to ensure that previously retrieved pointers remain valid for the lifetime of this object.
FMovieSceneChannelProxy (FMovieSceneChannelProxy &&)=delete
FMovieSceneChannelProxy (FMovieSceneChannelProxyData &&InChannels)
Construction via multiple channels.
~FMovieSceneChannelProxy ()
template<typename ChannelType>
TMovieSceneChannelHandle< ChannelType > CopyHandle (TMovieSceneChannelHandle< ChannelType > InOtherHandle)
Make a new channel handle for the same channel type name and index for this channel proxy.
MOVIESCENE_API const FMovieSceneChannelEntry * FindEntry (FName ChannelTypeName) const
Find an entry by its channel type name.
MOVIESCENE_API int32 FindIndex (FName ChannelTypeName, const FMovieSceneChannel *ChannelPtr) const
Find the index of the specified channel ptr in this proxy.
TArrayView< const FMovieSceneChannelEntry > GetAllEntries () const
Const access to all the entries in this proxy.
template<typename ChannelType>
TArrayView< const typename TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType > GetAllExtendedEditorData () const
Access all the extended data for the templated channel type.
MOVIESCENE_API FMovieSceneChannel * GetChannel (FName ChannelTypeName, int32 ChannelIndex) const
Get the channel for the specified index of a particular type.
template<typename ChannelType>
ChannelType * GetChannel (int32 ChannelIndex) const
Get the channel for the specified index of a particular type.
template<typename ChannelType>
TMovieSceneChannelHandle< ChannelType > GetChannelByName (FName ChannelName) const
Get the channel with the specified name, assuming it is of a given type.
MOVIESCENE_API FMovieSceneChannelHandle GetChannelByName (FName ChannelName) const
Get the channel with the specified name.
template<typename ChannelType>
TArrayView< ChannelType * > GetChannels () const
Get all channels of the specified type.
template<typename ChannelType>
TArrayView< const FMovieSceneChannelMetaData > GetMetaData () const
Access all the editor meta data for the templated channel type.
MOVIESCENE_API FMovieSceneChannelHandle MakeHandle (FName ChannelTypeName, int32 Index)
Make a channel handle out for the specified index and channel type name.
template<typename ChannelType>
TMovieSceneChannelHandle< ChannelType > MakeHandle (int32 Index)
Make a channel handle out for the specified index and templated channel type.
MOVIESCENE_API int32 NumChannels () const
Returns the total number of channels.
FMovieSceneChannelProxy & operator= (const FMovieSceneChannelProxy &)=delete
FMovieSceneChannelProxy & operator= (FMovieSceneChannelProxy &&)=delete
Public Member Functions inherited from TSharedFromThis< FMovieSceneChannelProxy >
TSharedRef< FMovieSceneChannelProxy, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FMovieSceneChannelProxy, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FSimpleMulticastDelegate OnDestroy
Private Member Functions
TSharedRef< ObjectType, Mode > AsShared ()
Do not expose shared-ownership semantics of this object.
TSharedRef< ObjectType const, Mode > AsShared () const
Do not expose shared-ownership semantics of this object.
MOVIESCENE_API void EnsureHandlesByNamePopulated () const
Populate the named channel table.
Private Attributes
bool bHandlesByNamePopulated = false
Whether the named channel table has been populated.
TArray< FMovieSceneChannelEntry, TInlineAllocator< 1 > > Entries
Array of channel entries, one per channel type.
TMap< FName, FMovieSceneChannelHandle > HandlesByName
Lazy-created lookup table between a channel name and a channel handle.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FMovieSceneChannelProxy >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FMovieSceneChannelProxy >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Proxy type stored inside UMovieSceneSection for access to all its channels.
Construction via either a single channel, or a FMovieSceneChannelProxyData structure This proxy exists as a generic accessor to any channel data existing in derived types
Definition at line 197 of file MovieSceneChannelProxy.h.
Constructor & Destructor Documentation
FMovieSceneChannelProxy() [1/6]
FMovieSceneChannelProxy::FMovieSceneChannelProxy () inline
Default construction - emtpy proxy.
Definition at line 204 of file MovieSceneChannelProxy.h.
Referenced by FMovieSceneChannelProxy(), FMovieSceneChannelProxy(), operator=(), and operator=().
~FMovieSceneChannelProxy()
FMovieSceneChannelProxy::~FMovieSceneChannelProxy () inline
Definition at line 206 of file MovieSceneChannelProxy.h.
References OnDestroy.
FMovieSceneChannelProxy() [2/6]
FMovieSceneChannelProxy::FMovieSceneChannelProxy (FMovieSceneChannelProxyData && InChannels) inline
Construction via multiple channels.
Definition at line 214 of file MovieSceneChannelProxy.h.
References Entries, and MoveTemp().
FMovieSceneChannelProxy() [3/6]
FMovieSceneChannelProxy::FMovieSceneChannelProxy (const FMovieSceneChannelProxy &) delete
Not copyable or moveable to ensure that previously retrieved pointers remain valid for the lifetime of this object.
References FMovieSceneChannelProxy().
FMovieSceneChannelProxy() [4/6]
FMovieSceneChannelProxy::FMovieSceneChannelProxy (FMovieSceneChannelProxy &&) delete
References FMovieSceneChannelProxy().
FMovieSceneChannelProxy() [5/6]
template<typename ChannelType> FMovieSceneChannelProxy::FMovieSceneChannelProxy (ChannelType & InChannel, const FMovieSceneChannelMetaData & InMetaData)
Construction via a single channel, and its editor data Channel's address is stored internally as a voic* and should exist as long as this channel proxy does.
Definition at line 480 of file MovieSceneChannelProxy.h.
References Entries.
FMovieSceneChannelProxy() [6/6]
template<typename ChannelType, typename ExtendedEditorDataType> FMovieSceneChannelProxy::FMovieSceneChannelProxy (ChannelType & InChannel, const FMovieSceneChannelMetaData & InMetaData, ExtendedEditorDataType && InExtendedEditorDataType)
Construction via a single channel, and its editor data Channel's address is stored internally as a voic* and should exist as long as this channel proxy does.
Construction via a single channel, its editor data, and its extended editor data.
Compulsary for channel types with a TMovieSceneChannelTraits<ChannelType>::ExtendedEditorDataType. Channel's address is stored internally as a voic* and should exist as long as this channel proxy does.
Definition at line 497 of file MovieSceneChannelProxy.h.
References Entries, and Forward().
Member Function Documentation
AsShared() [1/2]
TSharedRef< ObjectType, Mode > TSharedFromThis< ObjectType, Mode >::AsShared () inline nodiscard private
Do not expose shared-ownership semantics of this object.
Definition at line 1581 of file SharedPointer.h.
AsShared() [2/2]
TSharedRef< ObjectType const, Mode > TSharedFromThis< ObjectType, Mode >::AsShared () const inline nodiscard private
Do not expose shared-ownership semantics of this object.
Definition at line 1608 of file SharedPointer.h.
CopyHandle()
template<typename ChannelType> TMovieSceneChannelHandle< ChannelType > FMovieSceneChannelProxy::CopyHandle (TMovieSceneChannelHandle< ChannelType > InOtherHandle) inline
Make a new channel handle for the same channel type name and index for this channel proxy.
Returns
A handle to the supplied channel that will become nullptr when the proxy is reallocated, or nullptr if the index or channel type name are invalid.
Definition at line 307 of file MovieSceneChannelProxy.h.
References Cast(), and MakeHandle().
EnsureHandlesByNamePopulated()
MOVIESCENE_API void FMovieSceneChannelProxy::EnsureHandlesByNamePopulated () const private
Populate the named channel table.
FindEntry()
MOVIESCENE_API const FMovieSceneChannelEntry * FMovieSceneChannelProxy::FindEntry (FName ChannelTypeName) const
Find an entry by its channel type name.
Returns
A pointer to the channel, or nullptr
Referenced by GetAllExtendedEditorData(), GetChannels(), and GetMetaData().
FindIndex()
MOVIESCENE_API int32 FMovieSceneChannelProxy::FindIndex (FName ChannelTypeName, const FMovieSceneChannel * ChannelPtr) const
Find the index of the specified channel ptr in this proxy.
Parameters
ChannelTypeName The type name of the channel
ChannelPtr The channel pointer to find
Returns
The index of the channel if found, else INDEX_NONE
GetAllEntries()
TArrayView< const FMovieSceneChannelEntry > FMovieSceneChannelProxy::GetAllEntries () const inline
Const access to all the entries in this proxy.
Returns
Array view of all this proxy's entries (channels grouped by type)
Definition at line 232 of file MovieSceneChannelProxy.h.
References Entries.
GetAllExtendedEditorData()
template<typename ChannelType> TArrayView< const typename TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType > FMovieSceneChannelProxy::GetAllExtendedEditorData () const
Access all the extended data for the templated channel type.
Returns
A potentially empty array view for all the extended editor data for the template channel type
Definition at line 515 of file MovieSceneChannelProxy.h.
References FindEntry(), and FMovieSceneChannelEntry::GetAllExtendedEditorData().
GetChannel() [1/2]
MOVIESCENE_API FMovieSceneChannel * FMovieSceneChannelProxy::GetChannel (FName ChannelTypeName, int32 ChannelIndex) const
Get the channel for the specified index of a particular type.
Returns
A pointer to the channel, or nullptr if the index was invalid, or the type was not present
GetChannel() [2/2]
template<typename ChannelType> ChannelType * FMovieSceneChannelProxy::GetChannel (int32 ChannelIndex) const
Get the channel for the specified index of a particular type.
Returns
A pointer to the channel, or nullptr if the index was invalid, or the type was not present
Definition at line 448 of file MovieSceneChannelProxy.h.
References GetChannels().
Referenced by TAddKeyImpl< ChannelType, ValueType >::Apply(), TAddKeyImpl< FMovieSceneBoolChannel, bool >::Apply(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::Apply(), TAddKeyImpl< FMovieSceneFloatChannel, float >::Apply(), TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::Apply(), TAddKeyImpl< ChannelType, ValueType >::ApplyDefault(), TAddKeyImpl< FMovieSceneBoolChannel, bool >::ApplyDefault(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::ApplyDefault(), TAddKeyImpl< FMovieSceneFloatChannel, float >::ApplyDefault(), TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ApplyDefault(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::ModifyByCurrentAndWeight(), TAddKeyImpl< FMovieSceneFloatChannel, float >::ModifyByCurrentAndWeight(), and TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ModifyByCurrentAndWeight().
GetChannelByName() [1/2]
template<typename ChannelType> TMovieSceneChannelHandle< ChannelType > FMovieSceneChannelProxy::GetChannelByName (FName ChannelName) const
Get the channel with the specified name, assuming it is of a given type.
Get the channel for the specified sort index of a particular type.
Returns
A typed handle to the channel, or an invalid handle if no channel of that name was found, or it wasn't of the specified type
A pointer to the channel, or nullptr if the index was invalid, or the type was not present
Definition at line 553 of file MovieSceneChannelProxy.h.
References FMovieSceneChannelHandle::Cast(), GetChannelByName(), and FMovieSceneChannelHandle::GetChannelTypeName().
Referenced by GetChannelByName().
GetChannelByName() [2/2]
MOVIESCENE_API FMovieSceneChannelHandle FMovieSceneChannelProxy::GetChannelByName (FName ChannelName) const
Get the channel with the specified name.
Returns
A handle to the channel, or an invalid handle if no channel of that name was found
References TSharedFromThis< ObjectType, Mode >::AsShared().
GetChannels()
template<typename ChannelType> TArrayView< ChannelType * > FMovieSceneChannelProxy::GetChannels () const
Get all channels of the specified type.
Returns
A possibly empty array view of all the channels in this proxy that match the template type
Definition at line 429 of file MovieSceneChannelProxy.h.
References FMovieSceneChannelEntry::Channels, FindEntry(), TArray< InElementType, InAllocatorType >::GetData(), and TArray< InElementType, InAllocatorType >::Num().
Referenced by GetChannel().
GetMetaData()
template<typename ChannelType> TArrayView< const FMovieSceneChannelMetaData > FMovieSceneChannelProxy::GetMetaData () const
Access all the editor meta data for the templated channel type.
Returns
A potentially empty array view for all the editor meta data for the template channel type
Definition at line 534 of file MovieSceneChannelProxy.h.
References FindEntry(), and FMovieSceneChannelEditorDataEntry::GetMetaData().
MakeHandle() [1/2]
MOVIESCENE_API FMovieSceneChannelHandle FMovieSceneChannelProxy::MakeHandle (FName ChannelTypeName, int32 Index)
Make a channel handle out for the specified index and channel type name.
Returns
A handle to the supplied channel that will become nullptr when the proxy is reallocated, or nullptr if the index or channel type name are invalid.
Referenced by CopyHandle(), and MakeHandle().
MakeHandle() [2/2]
template<typename ChannelType> TMovieSceneChannelHandle< ChannelType > FMovieSceneChannelProxy::MakeHandle (int32 Index) inline
Make a channel handle out for the specified index and templated channel type.
Returns
A handle to the supplied channel that will become nullptr when the proxy is reallocated, or nullptr if the index or channel type name are invalid.
Definition at line 295 of file MovieSceneChannelProxy.h.
References Cast(), and MakeHandle().
NumChannels()
MOVIESCENE_API int32 FMovieSceneChannelProxy::NumChannels () const
Returns the total number of channels.
Returns
The total number of channels
operator=() [1/2]
FMovieSceneChannelProxy & FMovieSceneChannelProxy::operator= (const FMovieSceneChannelProxy &) delete
References FMovieSceneChannelProxy().
operator=() [2/2]
FMovieSceneChannelProxy & FMovieSceneChannelProxy::operator= (FMovieSceneChannelProxy &&) delete
References FMovieSceneChannelProxy().
Field Documentation
bHandlesByNamePopulated
bool FMovieSceneChannelProxy::bHandlesByNamePopulated = false mutable private
Whether the named channel table has been populated.
Definition at line 387 of file MovieSceneChannelProxy.h.
Entries
TArray<FMovieSceneChannelEntry, TInlineAllocator<1> > FMovieSceneChannelProxy::Entries private
Array of channel entries, one per channel type.
Should never be changed or reallocated after construction to keep pointers alive.
Definition at line 377 of file MovieSceneChannelProxy.h.
Referenced by FMovieSceneChannelProxy(), FMovieSceneChannelProxy(), FMovieSceneChannelProxy(), and GetAllEntries().
HandlesByName
TMap<FName, FMovieSceneChannelHandle> FMovieSceneChannelProxy::HandlesByName mutable private
Lazy-created lookup table between a channel name and a channel handle.
Definition at line 385 of file MovieSceneChannelProxy.h.
OnDestroy
FSimpleMulticastDelegate FMovieSceneChannelProxy::OnDestroy
Definition at line 201 of file MovieSceneChannelProxy.h.
Referenced by ~FMovieSceneChannelProxy().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Channels/MovieSceneChannelProxy.h