Unreal Engine 5.6 C++ API: MIR::FValueRef Struct Reference
MIR::FValueRef Struct Reference
#include "MaterialIREmitter.h"
Public Member Functions
FValueRef ()
FValueRef (FValue *Value)
FValueRef (FValue *Value, const FExpressionInput *Input)
bool IsValid () const
operator bool () const
operator FValue * () const
FValue * operator-> () const
FValueRef To (FValue *Value) const
FValueRef ToPoison () const
Data Fields
const FExpressionInput * Input {}
FValue * Value {}
Detailed Description
Definition at line 73 of file MaterialIREmitter.h.
Constructor & Destructor Documentation
FValueRef() [1/3]
MIR::FValueRef::FValueRef () inline
Definition at line 76 of file MaterialIREmitter.h.
Referenced by To(), and ToPoison().
FValueRef() [2/3]
MIR::FValueRef::FValueRef (FValue * Value) inline
Definition at line 79 of file MaterialIREmitter.h.
References Value.
FValueRef() [3/3]
MIR::FValueRef::FValueRef (FValue * Value, const FExpressionInput * Input) inline
Definition at line 82 of file MaterialIREmitter.h.
References Input, and Value.
Member Function Documentation
IsValid()
bool MIR::FValueRef::IsValid () const
operator bool()
MIR::FValueRef::operator bool () const inline
Definition at line 85 of file MaterialIREmitter.h.
References Value.
operator FValue *()
MIR::FValueRef::operator FValue * () const inline
Definition at line 88 of file MaterialIREmitter.h.
References Value.
operator->()
FValue * MIR::FValueRef::operator-> () const inline
Definition at line 91 of file MaterialIREmitter.h.
References Value.
To()
FValueRef MIR::FValueRef::To (FValue * Value) const
References FValueRef(), and Value.
ToPoison()
FValueRef MIR::FValueRef::ToPoison () const
References FValueRef().
Field Documentation
Input
const FExpressionInput* MIR::FValueRef::Input {}
Definition at line 106 of file MaterialIREmitter.h.
Referenced by FValueRef().
Value
FValue* MIR::FValueRef::Value {}
Definition at line 103 of file MaterialIREmitter.h.
Referenced by FValueRef(), FValueRef(), operator bool(), operator FValue *(), operator->(), and To().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Materials/MaterialIREmitter.h