Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModelChildren Struct Reference
UE::Sequencer::FViewModelChildren Struct Reference
#include "ViewModelHierarchy.h"
Public Member Functions
void AddChild (const TSharedPtr< FViewModel > &Child)
Add a child from a different parent to these children.
void Empty ()
Empty this specific sub-list, resetting all parent ptrs.
template<typename T>
TViewModelPtr< T > FindFirstChildOfType () const
FViewModelPtr GetHead () const
Returns the head model of this list.
FViewModelPtr GetParent () const
Get this children's parent.
FViewModelPtr GetTail () const
Finds the last model of this list.
EViewModelListType GetType () const
Get the collective type of these children.
void InsertChild (const TSharedPtr< FViewModel > &Child, const TSharedPtr< FViewModel > &PreviousSibling)
Add a child from a different parent to these children to the specified previous sibling, or the head if nullptr.
bool IsEmpty () const
Returns whether this list is empty.
FViewModelSubListIterator IterateSubList () const
Returns an iterator over this list.
template<typename T>
TViewModelSubListIterator< T > IterateSubList () const
Returns an iterator over this list which will skip any item not of type T.
void MoveChildrenTo (const FViewModelChildren &OutDestination)
Move all these children into the specified destination list, changing parent pointers if necessary.
template<typename T, typename Callback>
void MoveChildrenTo (const FViewModelChildren &OutDestination, Callback &&InCallback)
Invoke a callback on these children, and move them all into the specified destination list, changing parent pointers if necessary.
Private Member Functions
FViewModelChildren (const TSharedPtr< FViewModel > &InOwner, FViewModelListHead *InListHead)
Private Attributes
friend FScopedViewModelListHead
friend FViewModel
FViewModelListHead * ListHead
TSharedPtr< FViewModel > Owner
Detailed Description
Definition at line 182 of file ViewModelHierarchy.h.
Constructor & Destructor Documentation
FViewModelChildren()
UE::Sequencer::FViewModelChildren::FViewModelChildren (const TSharedPtr< FViewModel > & InOwner, FViewModelListHead * InListHead) private
Referenced by MoveChildrenTo(), and MoveChildrenTo().
Member Function Documentation
AddChild()
void UE::Sequencer::FViewModelChildren::AddChild (const TSharedPtr< FViewModel > & Child)
Add a child from a different parent to these children.
Note
: If the child is already under this parent, this function is a noop
References Child.
Empty()
void UE::Sequencer::FViewModelChildren::Empty ()
Empty this specific sub-list, resetting all parent ptrs.
FindFirstChildOfType()
template<typename T> TViewModelPtr< T > UE::Sequencer::FViewModelChildren::FindFirstChildOfType () const inline
Definition at line 254 of file ViewModelHierarchy.h.
References Child, and IterateSubList().
GetHead()
FViewModelPtr UE::Sequencer::FViewModelChildren::GetHead () const
Returns the head model of this list.
GetParent()
FViewModelPtr UE::Sequencer::FViewModelChildren::GetParent () const
Get this children's parent.
GetTail()
FViewModelPtr UE::Sequencer::FViewModelChildren::GetTail () const
Finds the last model of this list.
GetType()
EViewModelListType UE::Sequencer::FViewModelChildren::GetType () const
Get the collective type of these children.
InsertChild()
void UE::Sequencer::FViewModelChildren::InsertChild (const TSharedPtr< FViewModel > & Child, const TSharedPtr< FViewModel > & PreviousSibling)
Add a child from a different parent to these children to the specified previous sibling, or the head if nullptr.
Note
: If the child is already the specified model's next sibling, this function is a noop
References Child.
IsEmpty()
bool UE::Sequencer::FViewModelChildren::IsEmpty () const inline
Returns whether this list is empty.
Definition at line 242 of file ViewModelHierarchy.h.
References ListHead.
IterateSubList() [1/2]
FViewModelSubListIterator UE::Sequencer::FViewModelChildren::IterateSubList () const
Returns an iterator over this list.
Referenced by FindFirstChildOfType(), and MoveChildrenTo().
IterateSubList() [2/2]
template<typename T> TViewModelSubListIterator< T > UE::Sequencer::FViewModelChildren::IterateSubList () const inline
Returns an iterator over this list which will skip any item not of type T.
Definition at line 236 of file ViewModelHierarchy.h.
References ListHead.
MoveChildrenTo() [1/2]
void UE::Sequencer::FViewModelChildren::MoveChildrenTo (const FViewModelChildren & OutDestination)
Move all these children into the specified destination list, changing parent pointers if necessary.
References FViewModelChildren().
Referenced by MoveChildrenTo().
MoveChildrenTo() [2/2]
template<typename T, typename Callback> void UE::Sequencer::FViewModelChildren::MoveChildrenTo (const FViewModelChildren & OutDestination, Callback && InCallback) inline
Invoke a callback on these children, and move them all into the specified destination list, changing parent pointers if necessary.
Definition at line 215 of file ViewModelHierarchy.h.
References FViewModelChildren(), Item, IterateSubList(), and MoveChildrenTo().
Field Documentation
FScopedViewModelListHead
friend UE::Sequencer::FViewModelChildren::FScopedViewModelListHead private
Definition at line 266 of file ViewModelHierarchy.h.
FViewModel
friend UE::Sequencer::FViewModelChildren::FViewModel private
Definition at line 265 of file ViewModelHierarchy.h.
ListHead
FViewModelListHead* UE::Sequencer::FViewModelChildren::ListHead private
Definition at line 271 of file ViewModelHierarchy.h.
Referenced by IsEmpty(), and IterateSubList().
Owner
TSharedPtr<FViewModel> UE::Sequencer::FViewModelChildren::Owner private
Definition at line 270 of file ViewModelHierarchy.h.
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModels/ViewModelHierarchy.h