Unreal Engine 5.6 C++ API: Metasound::FOutputDataSource Struct Reference
Metasound::FOutputDataSource Struct Reference
FOutputDataSource describes the source of data which is produced within a graph and exposed external to the graph.
#include "MetasoundNodeInterface.h"
Public Member Functions
FOutputDataSource ()
FOutputDataSource (const INode &InNode, const FOutputDataVertex &InVertex)
Data Fields
const INode * Node = nullptr
Node containing the output data vertex.
FOutputDataVertex Vertex
Output data vertex.
Friends
bool METASOUNDGRAPHCORE_API operator!= (const FOutputDataSource &InLeft, const FOutputDataSource &InRight)
bool METASOUNDGRAPHCORE_API operator< (const FOutputDataSource &InLeft, const FOutputDataSource &InRight)
bool METASOUNDGRAPHCORE_API operator== (const FOutputDataSource &InLeft, const FOutputDataSource &InRight)
Check if two FOutputDataSources are equal.
Detailed Description
FOutputDataSource describes the source of data which is produced within a graph and exposed external to the graph.
Definition at line 254 of file MetasoundNodeInterface.h.
Constructor & Destructor Documentation
FOutputDataSource() [1/2]
Metasound::FOutputDataSource::FOutputDataSource () inline
Definition at line 262 of file MetasoundNodeInterface.h.
Referenced by operator!=, operator<, and operator==.
FOutputDataSource() [2/2]
Metasound::FOutputDataSource::FOutputDataSource (const INode & InNode, const FOutputDataVertex & InVertex) inline
Definition at line 266 of file MetasoundNodeInterface.h.
References Node, and Vertex.
Friends And Related Symbol Documentation
operator!=
bool METASOUNDGRAPHCORE_API operator!= (const FOutputDataSource & InLeft, const FOutputDataSource & InRight) friend
References FOutputDataSource().
operator<
bool METASOUNDGRAPHCORE_API operator< (const FOutputDataSource & InLeft, const FOutputDataSource & InRight) friend
References FOutputDataSource().
operator==
bool METASOUNDGRAPHCORE_API operator== (const FOutputDataSource & InLeft, const FOutputDataSource & InRight) friend
Check if two FOutputDataSources are equal.
References FOutputDataSource().
Field Documentation
Node
const INode* Metasound::FOutputDataSource::Node = nullptr
Node containing the output data vertex.
Definition at line 257 of file MetasoundNodeInterface.h.
Referenced by FOutputDataSource(), and Metasound::MakeSourceDataVertexKey().
Vertex
FOutputDataVertex Metasound::FOutputDataSource::Vertex
Output data vertex.
Definition at line 260 of file MetasoundNodeInterface.h.
Referenced by FOutputDataSource(), and Metasound::MakeSourceDataVertexKey().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundNodeInterface.h