Unreal Engine 5.6 C++ API: FRDGScope Struct Reference
FRDGScope Struct Reference
#include "RenderGraphEvent.h"
Data Structures
class TStorage
Public Types
typedef TStorage< FRDGScope_Budget > FStorage
Public Member Functions
FRDGScope (FRDGScope *Parent)
void BeginCPU (FRHIComputeCommandList &RHICmdList, bool bPreScope)
void BeginGPU (FRHIComputeCommandList &RHICmdList)
void EndCPU (FRHIComputeCommandList &RHICmdList, bool bPreScope)
void EndGPU (FRHIComputeCommandList &RHICmdList)
template<typename TScopeType>
TScopeType * Get ()
template<typename TScopeType>
TScopeType const * Get () const
FString GetFullPath (FRDGEventName const &PassName)
void ImmediateEnd (FRDGScopeState &State)
Static Public Member Functions
template<typename TScopeType>
static constexpr uint32 GetTypeMask ()
Data Fields
FRDGPass * CPUFirstPass = nullptr
FRDGPass * CPULastPass = nullptr
TRHIPipelineArray< FRDGPass * > GPUFirstPass { InPlace, nullptr }
TRHIPipelineArray< FRDGPass * > GPULastPass { InPlace, nullptr }
FStorage Impl
FRDGScope *const Parent
Detailed Description
Definition at line 235 of file RenderGraphEvent.h.
Member Typedef Documentation
FStorage
typedef TStorage< FRDGScope_Budget > FRDGScope::FStorage
Definition at line 296 of file RenderGraphEvent.h.
Constructor & Destructor Documentation
FRDGScope()
FRDGScope::FRDGScope (FRDGScope * Parent) inline
Definition at line 310 of file RenderGraphEvent.h.
References FRDGScope(), and Parent.
Referenced by FRDGScope().
Member Function Documentation
BeginCPU()
void FRDGScope::BeginCPU (FRHIComputeCommandList & RHICmdList, bool bPreScope) inline
Definition at line 316 of file RenderGraphEvent.h.
BeginGPU()
void FRDGScope::BeginGPU (FRHIComputeCommandList & RHICmdList) inline
Definition at line 317 of file RenderGraphEvent.h.
EndCPU()
void FRDGScope::EndCPU (FRHIComputeCommandList & RHICmdList, bool bPreScope) inline
Definition at line 318 of file RenderGraphEvent.h.
EndGPU()
void FRDGScope::EndGPU (FRHIComputeCommandList & RHICmdList) inline
Definition at line 319 of file RenderGraphEvent.h.
Get() [1/2]
template<typename TScopeType> TScopeType * FRDGScope::Get () inline
Definition at line 321 of file RenderGraphEvent.h.
Get() [2/2]
template<typename TScopeType> TScopeType const * FRDGScope::Get () const inline
Definition at line 322 of file RenderGraphEvent.h.
GetFullPath()
FString FRDGScope::GetFullPath (FRDGEventName const & PassName)
GetTypeMask()
template<typename TScopeType> constexpr uint32 FRDGScope::GetTypeMask () inline static constexpr
Definition at line 301 of file RenderGraphEvent.h.
References FRDGScope::TStorage< FRDGScope_Budget >::GetTypeIndex().
ImmediateEnd()
void FRDGScope::ImmediateEnd (FRDGScopeState & State) inline
Definition at line 314 of file RenderGraphEvent.h.
References State.
Field Documentation
CPUFirstPass
FRDGPass* FRDGScope::CPUFirstPass = nullptr
Definition at line 238 of file RenderGraphEvent.h.
CPULastPass
FRDGPass* FRDGScope::CPULastPass = nullptr
Definition at line 239 of file RenderGraphEvent.h.
GPUFirstPass
TRHIPipelineArray<FRDGPass*> FRDGScope::GPUFirstPass { InPlace, nullptr }
Definition at line 240 of file RenderGraphEvent.h.
GPULastPass
TRHIPipelineArray<FRDGPass*> FRDGScope::GPULastPass { InPlace, nullptr }
Definition at line 241 of file RenderGraphEvent.h.
Impl
FStorage FRDGScope::Impl
Definition at line 298 of file RenderGraphEvent.h.
Parent
FRDGScope* const FRDGScope::Parent
Definition at line 237 of file RenderGraphEvent.h.
Referenced by FRDGScope().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphEvent.h