Unreal Engine 5.6 C++ API: FMetasoundParameterPackStorage Struct Reference
FMetasoundParameterPackStorage Struct Reference
#include "MetasoundParameterPack.h"
Data Structures
struct ParameterIterator
Public Member Functions
FMetasoundParameterPackStorage ()=default
FMetasoundParameterPackStorage (const FMetasoundParameterPackStorage &Other)
FMetasoundParameterPackStorage (FMetasoundParameterPackStorage &&Other)
template<typename T, int32 MaxNumItems>
std::enable_if_t< std::is_class_v< T > &&TIsTArray_V< T >, void > AddArrayParameter (const FName &Name, const FName &InTypeName, const T &InValue)
template<typename T>
std::enable_if_t<!std::is_class_v< T >, T * > AddParameter (const FName &Name, const FName &InTypeName, const T &InValue)
template<typename T>
std::enable_if_t< std::is_class_v< T > &&!TIsTArray_V< T >, T * > AddParameter (const FName &Name, const FName &InTypeName, const T &InValue)
ParameterIterator begin ()
ParameterIterator end ()
template<typename T, int32 MaxNumItems = 0>
MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems > * FindParameter (const FName &ParamName, const FName &InTypeName)
Data Fields
TArray< uint8 > Storage
int32 StorageBytesInUse = 0
Detailed Description
Definition at line 79 of file MetasoundParameterPack.h.
Constructor & Destructor Documentation
FMetasoundParameterPackStorage() [1/3]
FMetasoundParameterPackStorage::FMetasoundParameterPackStorage () default
Referenced by FMetasoundParameterPackStorage(), and FMetasoundParameterPackStorage().
FMetasoundParameterPackStorage() [2/3]
FMetasoundParameterPackStorage::FMetasoundParameterPackStorage (const FMetasoundParameterPackStorage & Other) inline
Definition at line 85 of file MetasoundParameterPack.h.
References FMetasoundParameterPackStorage(), Other, Storage, and StorageBytesInUse.
FMetasoundParameterPackStorage() [3/3]
FMetasoundParameterPackStorage::FMetasoundParameterPackStorage (FMetasoundParameterPackStorage && Other) inline
Definition at line 89 of file MetasoundParameterPack.h.
References FMetasoundParameterPackStorage(), MoveTemp(), Other, Storage, and StorageBytesInUse.
Member Function Documentation
AddArrayParameter()
template<typename T, int32 MaxNumItems> std::enable_if_t< std::is_class_v< T > &&TIsTArray_V< T >, void > FMetasoundParameterPackStorage::AddArrayParameter (const FName & Name, const FName & InTypeName, const T & InValue) inline
Definition at line 235 of file MetasoundParameterPack.h.
References AlignArbitrary(), check, Name, MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase::NextHeaderOffset, MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems >::SizeOfParam(), Storage, StorageBytesInUse, and TIsTArray_V.
AddParameter() [1/2]
template<typename T> std::enable_if_t<!std::is_class_v< T >, T * > FMetasoundParameterPackStorage::AddParameter (const FName & Name, const FName & InTypeName, const T & InValue) inline
Definition at line 203 of file MetasoundParameterPack.h.
References AlignArbitrary(), Name, MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase::NextHeaderOffset, MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems >::SizeOfParam(), Storage, StorageBytesInUse, and MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems >::Value.
AddParameter() [2/2]
template<typename T> std::enable_if_t< std::is_class_v< T > &&!TIsTArray_V< T >, T * > FMetasoundParameterPackStorage::AddParameter (const FName & Name, const FName & InTypeName, const T & InValue) inline
Definition at line 219 of file MetasoundParameterPack.h.
References AlignArbitrary(), Name, MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase::NextHeaderOffset, MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems >::SizeOfParam(), Storage, StorageBytesInUse, TIsTArray_V, and MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems >::Value.
begin()
ParameterIterator FMetasoundParameterPackStorage::begin () inline
Definition at line 154 of file MetasoundParameterPack.h.
References Storage, and StorageBytesInUse.
end()
ParameterIterator FMetasoundParameterPackStorage::end () inline
Definition at line 163 of file MetasoundParameterPack.h.
FindParameter()
template<typename T, int32 MaxNumItems = 0> MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems > * FMetasoundParameterPackStorage::FindParameter (const FName & ParamName, const FName & InTypeName) inline
Definition at line 169 of file MetasoundParameterPack.h.
References MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase::Name, MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase::NextHeaderOffset, Storage, StorageBytesInUse, and MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase::TypeName.
Field Documentation
Storage
TArray<uint8> FMetasoundParameterPackStorage::Storage
Definition at line 81 of file MetasoundParameterPack.h.
Referenced by FMetasoundParameterPackStorage(), FMetasoundParameterPackStorage(), AddArrayParameter(), AddParameter(), begin(), FindParameter(), and FMetasoundParameterStorageWrapper::GetTypeHash.
StorageBytesInUse
int32 FMetasoundParameterPackStorage::StorageBytesInUse = 0
Definition at line 82 of file MetasoundParameterPack.h.
Referenced by FMetasoundParameterPackStorage(), FMetasoundParameterPackStorage(), AddArrayParameter(), AddParameter(), begin(), and FindParameter().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundParameterPack.h