Unreal Engine 5.6 C++ API: FMovieSceneExecutionTokens::FEntry Struct Reference
FMovieSceneExecutionTokens::FEntry Struct Reference
Public Member Functions
FEntry (const FMovieSceneEvaluationOperand &InOperand, const FMovieSceneEvaluationScope &InScope, const FMovieSceneContext &InContext, TInlineValue< IMovieSceneExecutionToken, 64 > &&InToken)
FEntry (FEntry &&)=default
FEntry & operator= (FEntry &&)=default
Data Fields
FMovieSceneContext Context
The context from when this token was added.
FMovieSceneEvaluationOperand Operand
The operand we were operating on when this token was added.
FMovieSceneEvaluationScope Scope
The evaluation scope at the time this token was created.
TInlineValue< IMovieSceneExecutionToken, 64 > Token
The user-provided token.
Detailed Description
Definition at line 150 of file MovieSceneExecutionTokens.h.
Constructor & Destructor Documentation
FEntry() [1/2]
FMovieSceneExecutionTokens::FEntry::FEntry (const FMovieSceneEvaluationOperand & InOperand, const FMovieSceneEvaluationScope & InScope, const FMovieSceneContext & InContext, TInlineValue< IMovieSceneExecutionToken, 64 > && InToken) inline
Definition at line 152 of file MovieSceneExecutionTokens.h.
References Context, MoveTemp(), Operand, Scope, and Token.
Referenced by FEntry(), and operator=().
FEntry() [2/2]
FMovieSceneExecutionTokens::FEntry::FEntry (FEntry &&) default
References FEntry().
Member Function Documentation
operator=()
FEntry & FMovieSceneExecutionTokens::FEntry::operator= (FEntry &&) default
References FEntry().
Field Documentation
Context
FMovieSceneContext FMovieSceneExecutionTokens::FEntry::Context
The context from when this token was added.
Definition at line 168 of file MovieSceneExecutionTokens.h.
Referenced by FEntry().
Operand
FMovieSceneEvaluationOperand FMovieSceneExecutionTokens::FEntry::Operand
The operand we were operating on when this token was added.
Definition at line 164 of file MovieSceneExecutionTokens.h.
Referenced by FEntry().
Scope
FMovieSceneEvaluationScope FMovieSceneExecutionTokens::FEntry::Scope
The evaluation scope at the time this token was created.
Definition at line 166 of file MovieSceneExecutionTokens.h.
Referenced by FEntry().
Token
TInlineValue<IMovieSceneExecutionToken, 64> FMovieSceneExecutionTokens::FEntry::Token
The user-provided token.
Definition at line 170 of file MovieSceneExecutionTokens.h.
Referenced by FEntry().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieSceneExecutionTokens.h