Unreal Engine 5.6 C++ API: UE::MovieScene::FHierarchicalBlendTarget Struct Reference
UE::MovieScene::FHierarchicalBlendTarget Struct Reference
Specifies a unique, sorted path of hbiases that contribute to a blended output Supports up to 8 unique HBiases in its path.
#include "BuiltInComponentTypes.h"
Public Member Functions
MOVIESCENE_API FHierarchicalBlendTarget ()
Default Constructor.
MOVIESCENE_API FHierarchicalBlendTarget (const FHierarchicalBlendTarget &RHS)
MOVIESCENE_API FHierarchicalBlendTarget (FHierarchicalBlendTarget &&RHS)
MOVIESCENE_API ~FHierarchicalBlendTarget ()
MOVIESCENE_API void Add (int16 HBias)
Add the specified HBias to this blend target.
MOVIESCENE_API TArrayView< const int16 > AsArray () const
Convert this blend target into an array view.
uint16 GetCapacity () const
Retrieve the current capacity of this container - only to be used for debugging and testing purposes.
MOVIESCENE_API int32 Num () const
Return the number of hbiases that contribute to this blend target.
MOVIESCENE_API FHierarchicalBlendTarget & operator= (const FHierarchicalBlendTarget &RHS)
MOVIESCENE_API FHierarchicalBlendTarget & operator= (FHierarchicalBlendTarget &&RHS)
MOVIESCENE_API int16 operator[] (int32 Index) const
Return the HBias at the specified index.
Private Member Functions
void FreeAllocation ()
TArrayView< int16 > GetAllEntries ()
TArrayView< const int16 > GetAllEntries () const
MOVIESCENE_API int16 * GetMemory ()
MOVIESCENE_API const int16 * GetMemory () const
void Grow (uint16 NewCapacity)
Private Attributes
uint16 Capacity
2 bytes - maximum number of hbiases in this chain.
uint8 Data [14]
14 bytes of hbias chain.
Static Private Attributes
static constexpr uint16 GrowAmount = 16u
static constexpr int32 InlineCapacity = sizeof(Data) / sizeof(int16)
Friends
uint32 GetTypeHash (const FHierarchicalBlendTarget &In)
bool operator!= (const FHierarchicalBlendTarget &A, const FHierarchicalBlendTarget &B)
bool operator< (const FHierarchicalBlendTarget &A, const FHierarchicalBlendTarget &B)
bool operator== (const FHierarchicalBlendTarget &A, const FHierarchicalBlendTarget &B)
Detailed Description
Specifies a unique, sorted path of hbiases that contribute to a blended output Supports up to 8 unique HBiases in its path.
Definition at line 349 of file BuiltInComponentTypes.h.
Constructor & Destructor Documentation
FHierarchicalBlendTarget() [1/3]
MOVIESCENE_API UE::MovieScene::FHierarchicalBlendTarget::FHierarchicalBlendTarget ()
Default Constructor.
Referenced by FHierarchicalBlendTarget(), FHierarchicalBlendTarget(), GetTypeHash, operator!=, operator<, operator=(), operator=(), and operator==.
FHierarchicalBlendTarget() [2/3]
MOVIESCENE_API UE::MovieScene::FHierarchicalBlendTarget::FHierarchicalBlendTarget (const FHierarchicalBlendTarget & RHS)
References FHierarchicalBlendTarget().
FHierarchicalBlendTarget() [3/3]
MOVIESCENE_API UE::MovieScene::FHierarchicalBlendTarget::FHierarchicalBlendTarget (FHierarchicalBlendTarget && RHS)
References FHierarchicalBlendTarget().
~FHierarchicalBlendTarget()
MOVIESCENE_API UE::MovieScene::FHierarchicalBlendTarget::~FHierarchicalBlendTarget ()
Member Function Documentation
Add()
MOVIESCENE_API void UE::MovieScene::FHierarchicalBlendTarget::Add (int16 HBias)
Add the specified HBias to this blend target.
Duplicates are not supported - if the HBias already exists in this chain, this function does nothing.
AsArray()
MOVIESCENE_API TArrayView< const int16 > UE::MovieScene::FHierarchicalBlendTarget::AsArray () const
Convert this blend target into an array view.
FreeAllocation()
void UE::MovieScene::FHierarchicalBlendTarget::FreeAllocation () private
GetAllEntries() [1/2]
TArrayView< int16 > UE::MovieScene::FHierarchicalBlendTarget::GetAllEntries () private
GetAllEntries() [2/2]
TArrayView< const int16 > UE::MovieScene::FHierarchicalBlendTarget::GetAllEntries () const private
GetCapacity()
uint16 UE::MovieScene::FHierarchicalBlendTarget::GetCapacity () const inline
Retrieve the current capacity of this container - only to be used for debugging and testing purposes.
Definition at line 386 of file BuiltInComponentTypes.h.
References Capacity.
GetMemory() [1/2]
MOVIESCENE_API int16 * UE::MovieScene::FHierarchicalBlendTarget::GetMemory () private
Referenced by GetTypeHash.
GetMemory() [2/2]
MOVIESCENE_API const int16 * UE::MovieScene::FHierarchicalBlendTarget::GetMemory () const private
Grow()
void UE::MovieScene::FHierarchicalBlendTarget::Grow (uint16 NewCapacity) private
Num()
MOVIESCENE_API int32 UE::MovieScene::FHierarchicalBlendTarget::Num () const
Return the number of hbiases that contribute to this blend target.
operator=() [1/2]
MOVIESCENE_API FHierarchicalBlendTarget & UE::MovieScene::FHierarchicalBlendTarget::operator= (const FHierarchicalBlendTarget & RHS)
References FHierarchicalBlendTarget().
operator=() [2/2]
MOVIESCENE_API FHierarchicalBlendTarget & UE::MovieScene::FHierarchicalBlendTarget::operator= (FHierarchicalBlendTarget && RHS)
References FHierarchicalBlendTarget().
operator[]()
MOVIESCENE_API int16 UE::MovieScene::FHierarchicalBlendTarget::operator[] (int32 Index) const
Return the HBias at the specified index.
Out of bounds indices will fail an assertion
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FHierarchicalBlendTarget & In) friend
Definition at line 393 of file BuiltInComponentTypes.h.
References FHierarchicalBlendTarget(), Capacity, check, GetMemory(), GrowAmount, Hash, HashCombine(), InlineCapacity, and Memory.
operator!=
bool operator!= (const FHierarchicalBlendTarget & A, const FHierarchicalBlendTarget & B) friend
Definition at line 435 of file BuiltInComponentTypes.h.
References FHierarchicalBlendTarget(), A, B, and FMemory::Memcmp().
operator<
bool operator< (const FHierarchicalBlendTarget & A, const FHierarchicalBlendTarget & B) friend
Definition at line 419 of file BuiltInComponentTypes.h.
References FHierarchicalBlendTarget(), A, B, and FMemory::Memcmp().
operator==
bool operator== (const FHierarchicalBlendTarget & A, const FHierarchicalBlendTarget & B) friend
Definition at line 427 of file BuiltInComponentTypes.h.
References FHierarchicalBlendTarget(), A, B, and FMemory::Memcmp().
Field Documentation
Capacity
uint16 UE::MovieScene::FHierarchicalBlendTarget::Capacity private
2 bytes - maximum number of hbiases in this chain.
Definition at line 467 of file BuiltInComponentTypes.h.
Referenced by GetCapacity(), and GetTypeHash.
Data
uint8 UE::MovieScene::FHierarchicalBlendTarget::Data[14] private
14 bytes of hbias chain.
Type is either: int16[7] where Capacity == InlineCapacity int16* (heap allocated) where Capacity > InlineCapacity Supports inline up to a maximum of 7 sub-sequences, or any number on the heap allocation. Implemented using type-erasure since a union would be padded up to 16 bytes, and we want to keep sizeof this type == 16 bytes
Definition at line 464 of file BuiltInComponentTypes.h.
GrowAmount
uint16 UE::MovieScene::FHierarchicalBlendTarget::GrowAmount = 16u static constexpr private
Definition at line 470 of file BuiltInComponentTypes.h.
Referenced by GetTypeHash.
InlineCapacity
int32 UE::MovieScene::FHierarchicalBlendTarget::InlineCapacity = sizeof(Data) / sizeof(int16) static constexpr private
Definition at line 469 of file BuiltInComponentTypes.h.
Referenced by GetTypeHash.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/BuiltInComponentTypes.h