Unreal Engine 5.6 C++ API: FCompression Struct Reference
FCompression Struct Reference
#include "Compression.h"
Public Member Functions
UE_DEPRECATED (5.5, "Use the 64 bit version") 1 static int32 GetMaximumCompressedSize(FName FormatName
UE_DEPRECATED (5.5, "Use the direct FName instead e.g NAME_Oodle") 1 static FName GetCompressionFormatFromDeprecatedFlags(ECompressionFlags DeprecatedFlags)
Static Public Member Functions
static bool CompressMemory (FName FormatName, void *CompressedBuffer, int32 &CompressedSize, const void *UncompressedBuffer, int32 UncompressedSize, ECompressionFlags Flags=COMPRESS_NoFlags, int32 CompressionData=0)
static bool CompressMemory (FName FormatName, void *CompressedBuffer, int64 &CompressedSize, const void *UncompressedBuffer, int64 UncompressedSize, ECompressionFlags Flags=COMPRESS_NoFlags, uintptr_t CompressionData=0)
Thread-safe abstract compression routine.
static int32 CompressMemoryBound (FName FormatName, int32 UncompressedSize, ECompressionFlags Flags=COMPRESS_NoFlags, int32 CompressionData=0)
static bool CompressMemoryBound (FName InFormatName, int64 &OutBufferSizeRequired, int64 InUncompressedSizeBytes, uintptr_t InCompressionData=0)
Thread-safe abstract compression routine to query buffer requirements for a compression operation.
static bool CompressMemoryIfWorthDecompressing (FName FormatName, bool &bOutWasCompressed, int64 MinBytesSaved, int32 MinPercentSaved, void *CompressedBuffer, int64 &CompressedSize, const void *UncompressedBuffer, int64 UncompressedSize, ECompressionFlags Flags=COMPRESS_NoFlags, uintptr_t CompressionData=0)
Same as CompressMemory but evaluates if the compression gain is worth the runtime decode time.
static bool CompressMemoryIfWorthDecompressing (FName FormatName, int32 MinBytesSaved, int32 MinPercentSaved, void *CompressedBuffer, int32 &CompressedSize, const void *UncompressedBuffer, int32 UncompressedSize, ECompressionFlags Flags=COMPRESS_NoFlags, int32 CompressionData=0)
static FString GetCompressorDDCSuffix (FName FormatName)
Returns a string which can be used to identify if a format has become out of date.
static uint32 GetCompressorVersion (FName FormatName)
Returns a version number for a specified format.
static bool GetMaximumCompressedSize (FName InFormatName, int64 &OutMaxCompressedSize, int64 InUncompressedSizeBytes, uintptr_t InCompressionData=0)
Thread-safe abstract compression routine to query maximum compressed size that could be made.
static bool IsFormatValid (FName FormatName)
Checks to see if a format will be usable, so that a fallback can be used.
static bool UncompressMemory (FName FormatName, void *UncompressedBuffer, int64 UncompressedSize, const void *CompressedBuffer, int64 CompressedSize, ECompressionFlags Flags=COMPRESS_NoFlags, uintptr_t CompressionData=0)
Thread-safe abstract decompression routine.
static bool UncompressMemoryStream (FName FormatName, void *UncompressedBuffer, int64 UncompressedSize, IMemoryReadStream *Stream, int64 StreamOffset, int64 CompressedSize, ECompressionFlags Flags=COMPRESS_NoFlags, uintptr_t CompressionData=0)
Wraps UncompressMemory to provide access with a IMemoryReadStream interface, attempting to avoid copying in to a contiguous buffer doe decompression if the format supports it.
static bool VerifyCompressionFlagsValid (int32 InCompressionFlags)
Verifies if the passed in value represents valid compression flags.
Data Fields
int32 ECompressionFlags int32 CompressionData = 0)
int32 ECompressionFlags Flags = COMPRESS_NoFlags
int32 UncompressedSize
Static Public Attributes
static TAtomic< uint64 > CompressorDstBytes
Number of bytes after compression.
static TAtomic< uint64 > CompressorSrcBytes
Number of bytes before compression.
static TAtomic< uint64 > CompressorTimeCycles
CompressionData is per-compressor data passed through this API and is interpreted by the codecs.
Static Private Member Functions
static struct ICompressionFormat * GetCompressionFormat (FName Method, bool bErrorOnFailure=true)
Find a compression format module by name, returning nullptr if no module found.
Static Private Attributes
static TMap< FName, struct ICompressionFormat * > CompressionFormats
Mapping of Compression FNames to their compressor objects.
static FCriticalSection CompressionFormatsCriticalSection
Detailed Description
Definition at line 28 of file Compression.h.
Member Function Documentation
CompressMemory() [1/2]
bool FCompression::CompressMemory (FName FormatName, void * CompressedBuffer, int32 & CompressedSize, const void * UncompressedBuffer, int32 UncompressedSize, ECompressionFlags Flags = COMPRESS_NoFlags, int32 CompressionData = 0) static
References COMPRESS_NoFlags, CompressionData, CompressMemory(), Flags, and UncompressedSize.
CompressMemory() [2/2]
bool FCompression::CompressMemory (FName FormatName, void * CompressedBuffer, int64 & CompressedSize, const void * UncompressedBuffer, int64 UncompressedSize, ECompressionFlags Flags = COMPRESS_NoFlags, uintptr_t CompressionData = 0) static
Thread-safe abstract compression routine.
Compresses memory from uncompressed buffer and writes it to compressed buffer. Updates CompressedSize with size of compressed data. Compression controlled by the passed in flags. CompressMemory is expected to return true and write valid data even if it expanded bytes. Always check CompressedSize >= UncompressedSize and fall back to uncompressed, or use CompressMemoryIfWorthDecompressing
Parameters
FormatName Name of the compression format
CompressedBuffer Buffer compressed data is going to be written to
CompressedSize [in/out] Size of CompressedBuffer, at exit will be size of compressed data
UncompressedBuffer Buffer containing uncompressed data
UncompressedSize Size of uncompressed data in bytes
Flags Flags to control what method to use and optionally control memory vs speed
CompressionData Additional compression parameter - see comments a top of FCompression struct.
Returns
true if compression succeeds, false if it fails because CompressedBuffer was too small or other reasons
References COMPRESS_NoFlags, CompressionData, CompressMemory(), Flags, and UncompressedSize.
Referenced by CompressMemory(), and CompressMemory().
CompressMemoryBound() [1/2]
int32 FCompression::CompressMemoryBound (FName FormatName, int32 UncompressedSize, ECompressionFlags Flags = COMPRESS_NoFlags, int32 CompressionData = 0) static
References COMPRESS_NoFlags, CompressionData, Flags, and UncompressedSize.
CompressMemoryBound() [2/2]
bool FCompression::CompressMemoryBound (FName InFormatName, int64 & OutBufferSizeRequired, int64 InUncompressedSizeBytes, uintptr_t InCompressionData = 0) static
Thread-safe abstract compression routine to query buffer requirements for a compression operation.
This is the minimize size to allocate the buffer for CompressMemory (encoding). Use GetMaximumCompressedSize at decode to know how large a compressed buffer may be.
Despite the name, this has nothing to do with how much memory will be allocated during compression.
Parameters
FormatName Name of the compression format
UncompressedSize Size of uncompressed data in bytes
CompressionData Additional compression parameter - see comments a top of FCompression struct.
OutBufferSizeRequired The maximum possible bytes needed for compression of a data buffer of the given size.
Returns
false if the bounds couldn't be determined - e.g. the format is unknown or the size isn't supported by the format.
CompressMemoryIfWorthDecompressing() [1/2]
bool FCompression::CompressMemoryIfWorthDecompressing (FName FormatName, bool & bOutWasCompressed, int64 MinBytesSaved, int32 MinPercentSaved, void * CompressedBuffer, int64 & CompressedSize, const void * UncompressedBuffer, int64 UncompressedSize, ECompressionFlags Flags = COMPRESS_NoFlags, uintptr_t CompressionData = 0) static
Same as CompressMemory but evaluates if the compression gain is worth the runtime decode time.
Parameters
FormatName Name of the compression format
bOutWasCompressed [out] Whether the compression was worth it. The data is still compressed.
MinBytesSaved Minimum amount of bytes which should be saved when performing compression, otherwise false is returned
MinPercentSaved Minimum percentage of the buffer which should be saved when performing compression, otherwise false is returned
CompressedBuffer Buffer compressed data is going to be written to
CompressedSize [in/out] Size of CompressedBuffer, at exit will be size of compressed data
UncompressedBuffer Buffer containing uncompressed data
UncompressedSize Size of uncompressed data in bytes
Flags Flags to control what method to use and optionally control memory vs speed
CompressionData Additional compression parameter - see comments a top of FCompression struct.
Returns
true if compression succeeds, false if it fails because CompressedBuffer was too small or other reasons
References COMPRESS_NoFlags, CompressionData, CompressMemoryIfWorthDecompressing(), Flags, and UncompressedSize.
Referenced by CompressMemoryIfWorthDecompressing(), and CompressMemoryIfWorthDecompressing().
CompressMemoryIfWorthDecompressing() [2/2]
bool FCompression::CompressMemoryIfWorthDecompressing (FName FormatName, int32 MinBytesSaved, int32 MinPercentSaved, void * CompressedBuffer, int32 & CompressedSize, const void * UncompressedBuffer, int32 UncompressedSize, ECompressionFlags Flags = COMPRESS_NoFlags, int32 CompressionData = 0) static
References COMPRESS_NoFlags, CompressionData, CompressMemoryIfWorthDecompressing(), Flags, and UncompressedSize.
GetCompressionFormat()
struct ICompressionFormat * FCompression::GetCompressionFormat (FName Method, bool bErrorOnFailure = true) static private
Find a compression format module by name, returning nullptr if no module found.
References GetCompressionFormat().
Referenced by GetCompressionFormat().
GetCompressorDDCSuffix()
FString FCompression::GetCompressorDDCSuffix (FName FormatName) static
Returns a string which can be used to identify if a format has become out of date.
Parameters
FormatName name of the format to retrieve the DDC suffix for
Returns
unique DDC key string which will be different when the format is changed / updated
References GetCompressorDDCSuffix().
Referenced by GetCompressorDDCSuffix().
GetCompressorVersion()
uint32 FCompression::GetCompressorVersion (FName FormatName) static
Returns a version number for a specified format.
Parameters
FormatName Compressor format name (eg NAME_Zlib)
Returns
An interpretation of an internal version number for a specific format (different formats will have different layouts) this should change if a version is updated
GetMaximumCompressedSize()
bool FCompression::GetMaximumCompressedSize (FName InFormatName, int64 & OutMaxCompressedSize, int64 InUncompressedSizeBytes, uintptr_t InCompressionData = 0) static
Thread-safe abstract compression routine to query maximum compressed size that could be made.
This is used for making buffers that could hold any compressed buffer that started uncompressed with the given size. It's distinct from the buffer needed to compress! If you are calling CompressMemory then you need to pass a buffer sized based on CompressMemoryBound!
CompressMemoryBound is strictly greater equal GetMaximumCompressedSize.
Parameters
FormatName Name of the compression format
OutMaxCompressedSize The maximum possible size of valid compressed data made by this format
InUncompressedSizeBytes Size of uncompressed data in bytes
CompressionData Additional compression parameter - see comments a top of FCompression struct.
Returns
success
IsFormatValid()
bool FCompression::IsFormatValid (FName FormatName) static
Checks to see if a format will be usable, so that a fallback can be used.
Parameters
FormatName The name of the format to test
References IsFormatValid().
Referenced by IsFormatValid().
UE_DEPRECATED() [1/2]
FCompression::UE_DEPRECATED (5. 5, "Use the 64 bit version")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FCompression::UE_DEPRECATED (5. 5, "Use the direct FName instead e.g NAME_Oodle")
References UE_DEPRECATED().
UncompressMemory()
bool FCompression::UncompressMemory (FName FormatName, void * UncompressedBuffer, int64 UncompressedSize, const void * CompressedBuffer, int64 CompressedSize, ECompressionFlags Flags = COMPRESS_NoFlags, uintptr_t CompressionData = 0) static
Thread-safe abstract decompression routine.
Uncompresses memory from compressed buffer and writes it to uncompressed buffer. UncompressedSize is expected to be the exact size of the data after decompression.
Parameters
FormatName Name of the compression format
UncompressedBuffer Buffer containing uncompressed data
UncompressedSize Size of uncompressed data in bytes
CompressedBuffer Buffer compressed data is going to be read from
CompressedSize Size of CompressedBuffer data in bytes
Flags Flags to control what method to use to decompress
CompressionData Additional decompression parameter (specifies BitWindow value for ZLIB compression format)
Returns
true if compression succeeds, false if it fails because CompressedBuffer was too small or other reasons
References COMPRESS_NoFlags, CompressionData, Flags, UncompressedSize, and UncompressMemory().
Referenced by UncompressMemory().
UncompressMemoryStream()
bool FCompression::UncompressMemoryStream (FName FormatName, void * UncompressedBuffer, int64 UncompressedSize, IMemoryReadStream * Stream, int64 StreamOffset, int64 CompressedSize, ECompressionFlags Flags = COMPRESS_NoFlags, uintptr_t CompressionData = 0) static
Wraps UncompressMemory to provide access with a IMemoryReadStream interface, attempting to avoid copying in to a contiguous buffer doe decompression if the format supports it.
If not, a CompressedSize temp buffer will be allocated.
References COMPRESS_NoFlags, CompressionData, Flags, Stream, UncompressedSize, and UncompressMemoryStream().
Referenced by UncompressMemoryStream().
VerifyCompressionFlagsValid()
bool FCompression::VerifyCompressionFlagsValid (int32 InCompressionFlags) static
Verifies if the passed in value represents valid compression flags.
Parameters
InCompressionFlags Value to test
References VerifyCompressionFlagsValid().
Referenced by VerifyCompressionFlagsValid().
Field Documentation
CompressionData
int32 ECompressionFlags int32 FCompression::CompressionData = 0)
Definition at line 90 of file Compression.h.
Referenced by CompressMemory(), CompressMemory(), CompressMemoryBound(), CompressMemoryIfWorthDecompressing(), CompressMemoryIfWorthDecompressing(), UncompressMemory(), and UncompressMemoryStream().
CompressionFormats
TMap<FName, struct ICompressionFormat*> FCompression::CompressionFormats static private
Mapping of Compression FNames to their compressor objects.
Definition at line 186 of file Compression.h.
CompressionFormatsCriticalSection
FCriticalSection FCompression::CompressionFormatsCriticalSection static private
Definition at line 187 of file Compression.h.
CompressorDstBytes
TAtomic<uint64> FCompression::CompressorDstBytes static
Number of bytes after compression.
Definition at line 44 of file Compression.h.
CompressorSrcBytes
TAtomic<uint64> FCompression::CompressorSrcBytes static
Number of bytes before compression.
Definition at line 42 of file Compression.h.
CompressorTimeCycles
TAtomic<uint64> FCompression::CompressorTimeCycles static
CompressionData is per-compressor data passed through this API and is interpreted by the codecs.
For builtins: NAME_Zlib BitWindow NAME_LZ4 Unused NAME_Gzip Unused NAME_Oodle Unused Time spent compressing data in cycles.
Definition at line 40 of file Compression.h.
Flags
int32 ECompressionFlags FCompression::Flags = COMPRESS_NoFlags
Definition at line 90 of file Compression.h.
Referenced by CompressMemory(), CompressMemory(), CompressMemoryBound(), CompressMemoryIfWorthDecompressing(), CompressMemoryIfWorthDecompressing(), UncompressMemory(), and UncompressMemoryStream().
UncompressedSize
int32 FCompression::UncompressedSize
Definition at line 90 of file Compression.h.
Referenced by CompressMemory(), CompressMemory(), CompressMemoryBound(), CompressMemoryIfWorthDecompressing(), CompressMemoryIfWorthDecompressing(), UncompressMemory(), and UncompressMemoryStream().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Compression.h