Unreal Engine 5.6 C++ API: UE::Sequencer::FParentModelIterator Struct Reference
UE::Sequencer::FParentModelIterator Struct Reference
Iterator going up the parent relationships towards the root.
#include "ViewModelIterators.h"
Public Member Functions
FParentModelIterator ()=default
FParentModelIterator (TSharedPtr< FViewModel > StartAtChild, bool bIncludeThis=false)
FORCEINLINE FParentModelIterator begin () const
FORCEINLINE FParentModelIterator end () const
FORCEINLINE const FViewModelPtr & GetCurrentItem () const
FORCEINLINE operator bool () const
FORCEINLINE const FViewModelPtr & operator* () const
FORCEINLINE void operator++ ()
FORCEINLINE FViewModel * operator-> () const
Protected Attributes
FViewModelPtr Node
Friends
FORCEINLINE friend bool operator!= (const FParentModelIterator &A, const FParentModelIterator &B)
Detailed Description
Iterator going up the parent relationships towards the root.
Definition at line 433 of file ViewModelIterators.h.
Constructor & Destructor Documentation
FParentModelIterator() [1/2]
UE::Sequencer::FParentModelIterator::FParentModelIterator () default
Referenced by begin(), end(), and operator!=.
FParentModelIterator() [2/2]
UE::Sequencer::FParentModelIterator::FParentModelIterator (TSharedPtr< FViewModel > StartAtChild, bool bIncludeThis = false) inline
Definition at line 437 of file ViewModelIterators.h.
References Node.
Member Function Documentation
begin()
FORCEINLINE FParentModelIterator UE::Sequencer::FParentModelIterator::begin () const inline
Definition at line 474 of file ViewModelIterators.h.
References FParentModelIterator(), and FORCEINLINE.
end()
FORCEINLINE FParentModelIterator UE::Sequencer::FParentModelIterator::end () const inline
Definition at line 475 of file ViewModelIterators.h.
References FParentModelIterator(), and FORCEINLINE.
GetCurrentItem()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FParentModelIterator::GetCurrentItem () const inline
Definition at line 449 of file ViewModelIterators.h.
References FORCEINLINE, and Node.
operator bool()
FORCEINLINE UE::Sequencer::FParentModelIterator::operator bool () const inline explicit
Definition at line 461 of file ViewModelIterators.h.
References FORCEINLINE, and Node.
operator*()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FParentModelIterator::operator* () const inline
Definition at line 453 of file ViewModelIterators.h.
References FORCEINLINE, and Node.
operator++()
FORCEINLINE void UE::Sequencer::FParentModelIterator::operator++ () inline
Definition at line 465 of file ViewModelIterators.h.
References FORCEINLINE, and Node.
operator->()
FORCEINLINE FViewModel * UE::Sequencer::FParentModelIterator::operator-> () const inline
Definition at line 457 of file ViewModelIterators.h.
References FORCEINLINE, and Node.
Friends And Related Symbol Documentation
operator!=
FORCEINLINE friend bool operator!= (const FParentModelIterator & A, const FParentModelIterator & B) friend
Definition at line 469 of file ViewModelIterators.h.
References FParentModelIterator(), A, B, and FORCEINLINE.
Field Documentation
Node
FViewModelPtr UE::Sequencer::FParentModelIterator::Node protected
Definition at line 479 of file ViewModelIterators.h.
Referenced by FParentModelIterator(), GetCurrentItem(), operator bool(), operator*(), operator++(), and operator->().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModels/ViewModelIterators.h