Unreal Engine 5.6 C++ API: FSequencerKeyCollectionSignature Struct Reference
FSequencerKeyCollectionSignature Struct Reference
#include "SequencerKeyCollection.h"
Public Types
using FViewModel = UE::Sequencer::FViewModel
Public Member Functions
FSequencerKeyCollectionSignature ()
FFrameNumber GetDuplicateThreshold () const
Access duplicate threshold that this signature was generated for.
const TMap< TSharedRef< IKeyArea >, FGuid > & GetKeyAreas () const
Access the map of keyareas and signatures this signature was generated for.
const TMap< FGuid, TRange< FFrameNumber > > & GetSectionBounds () const
Access the map of signatures to section bounds that this signature was generated for.
Static Public Member Functions
static SEQUENCER_API FSequencerKeyCollectionSignature FromNodeRecursive (TSharedRef< FViewModel > InNode, UMovieSceneSection *InSection, FFrameNumber InDuplicateThreshold)
Initialize this key collection from the specified node and section index.
static SEQUENCER_API FSequencerKeyCollectionSignature FromNodes (const TArray< TSharedRef< FViewModel > > &InNodes, FFrameNumber InDuplicateThreshold)
Initialize this key collection from the specified nodes.
static SEQUENCER_API FSequencerKeyCollectionSignature FromNodesRecursive (const TArray< TSharedRef< FViewModel > > &InNodes, FFrameNumber InDuplicateThreshold)
Initialize this key collection from the specified nodes.
Private Member Functions
bool HasUncachableContent () const
Check whether this signature contains content that cannot be cached (such content causes this signature to never compare equal with another)
Private Attributes
FFrameNumber DuplicateThresholdTime
The time at which proximal keys are considered duplicates.
TMap< TSharedRef< IKeyArea >, FGuid > KeyAreaToSignature
Map of key areas to the section signature with with this signature was generated.
TMap< FGuid, TRange< FFrameNumber > > SignatureToSectionBounds
Map of the section signature to the section bounds.
Friends
SEQUENCER_API friend bool operator!= (const FSequencerKeyCollectionSignature &A, const FSequencerKeyCollectionSignature &B)
Compare this signature for inequality with another.
SEQUENCER_API friend bool operator== (const FSequencerKeyCollectionSignature &A, const FSequencerKeyCollectionSignature &B)
Compare this signature for equality with another.
Detailed Description
Definition at line 43 of file SequencerKeyCollection.h.
Member Typedef Documentation
FViewModel
using FSequencerKeyCollectionSignature::FViewModel = UE::Sequencer::FViewModel
Definition at line 45 of file SequencerKeyCollection.h.
Constructor & Destructor Documentation
FSequencerKeyCollectionSignature()
FSequencerKeyCollectionSignature::FSequencerKeyCollectionSignature () inline
Definition at line 47 of file SequencerKeyCollection.h.
Referenced by FromNodeRecursive(), FromNodes(), FromNodesRecursive(), operator!=, and operator==.
Member Function Documentation
FromNodeRecursive()
SEQUENCER_API FSequencerKeyCollectionSignature FSequencerKeyCollectionSignature::FromNodeRecursive (TSharedRef< FViewModel > InNode, UMovieSceneSection * InSection, FFrameNumber InDuplicateThreshold) static
Initialize this key collection from the specified node and section index.
References FSequencerKeyCollectionSignature().
FromNodes()
SEQUENCER_API FSequencerKeyCollectionSignature FSequencerKeyCollectionSignature::FromNodes (const TArray< TSharedRef< FViewModel > > & InNodes, FFrameNumber InDuplicateThreshold) static
Initialize this key collection from the specified nodes.
Only gathers keys from those explicitly specified.
References FSequencerKeyCollectionSignature().
FromNodesRecursive()
SEQUENCER_API FSequencerKeyCollectionSignature FSequencerKeyCollectionSignature::FromNodesRecursive (const TArray< TSharedRef< FViewModel > > & InNodes, FFrameNumber InDuplicateThreshold) static
Initialize this key collection from the specified nodes.
Gathers keys from all child nodes.
References FSequencerKeyCollectionSignature().
GetDuplicateThreshold()
FFrameNumber FSequencerKeyCollectionSignature::GetDuplicateThreshold () const inline
Access duplicate threshold that this signature was generated for.
Definition at line 78 of file SequencerKeyCollection.h.
References DuplicateThresholdTime.
GetKeyAreas()
const TMap< TSharedRef< IKeyArea >, FGuid > & FSequencerKeyCollectionSignature::GetKeyAreas () const inline
Access the map of keyareas and signatures this signature was generated for.
Definition at line 66 of file SequencerKeyCollection.h.
References KeyAreaToSignature.
GetSectionBounds()
const TMap< FGuid, TRange< FFrameNumber > > & FSequencerKeyCollectionSignature::GetSectionBounds () const inline
Access the map of signatures to section bounds that this signature was generated for.
Definition at line 72 of file SequencerKeyCollection.h.
References SignatureToSectionBounds.
HasUncachableContent()
bool FSequencerKeyCollectionSignature::HasUncachableContent () const private
Check whether this signature contains content that cannot be cached (such content causes this signature to never compare equal with another)
Friends And Related Symbol Documentation
operator!=
SEQUENCER_API friend bool operator!= (const FSequencerKeyCollectionSignature & A, const FSequencerKeyCollectionSignature & B) friend
Compare this signature for inequality with another.
References FSequencerKeyCollectionSignature(), A, and B.
operator==
SEQUENCER_API friend bool operator== (const FSequencerKeyCollectionSignature & A, const FSequencerKeyCollectionSignature & B) friend
Compare this signature for equality with another.
References FSequencerKeyCollectionSignature(), A, and B.
Field Documentation
DuplicateThresholdTime
FFrameNumber FSequencerKeyCollectionSignature::DuplicateThresholdTime private
The time at which proximal keys are considered duplicates.
Definition at line 89 of file SequencerKeyCollection.h.
Referenced by GetDuplicateThreshold().
KeyAreaToSignature
TMap<TSharedRef<IKeyArea>, FGuid> FSequencerKeyCollectionSignature::KeyAreaToSignature private
Map of key areas to the section signature with with this signature was generated.
Definition at line 92 of file SequencerKeyCollection.h.
Referenced by GetKeyAreas().
SignatureToSectionBounds
TMap<FGuid, TRange<FFrameNumber> > FSequencerKeyCollectionSignature::SignatureToSectionBounds private
Map of the section signature to the section bounds.
Definition at line 95 of file SequencerKeyCollection.h.
Referenced by GetSectionBounds().
The documentation for this struct was generated from the following file:
Editor/Sequencer/Public/SequencerKeyCollection.h