Unreal Engine 5.6 C++ API: FEvaluatedParameterSectionValues Struct Reference
FEvaluatedParameterSectionValues Struct Reference
Evaluation structure that holds evaluated values.
#include "MovieSceneParameterTemplate.h"
Public Member Functions
FEvaluatedParameterSectionValues ()=default
FEvaluatedParameterSectionValues (const FEvaluatedParameterSectionValues &)=delete
FEvaluatedParameterSectionValues (FEvaluatedParameterSectionValues &&)=default
FEvaluatedParameterSectionValues & operator= (const FEvaluatedParameterSectionValues &)=delete
FEvaluatedParameterSectionValues & operator= (FEvaluatedParameterSectionValues &&)=default
Data Fields
TArray< FBoolParameterNameAndValue, TInlineAllocator< 2 > > BoolValues
Array of evaluated bool values.
TArray< FColorParameterNameAndValue, TInlineAllocator< 2 > > ColorValues
Array of evaluated color values.
TArray< FScalarParameterNameAndValue, TInlineAllocator< 2 > > ScalarValues
Array of evaluated scalar values.
TArray< FTransformParameterNameAndValue, TInlineAllocator< 2 > > TransformValues
Array of evaluated transform values.
TArray< FVector2DParameterNameAndValue, TInlineAllocator< 2 > > Vector2DValues
Array of evaluated vector2D values.
TArray< FVectorParameterNameAndValue, TInlineAllocator< 2 > > VectorValues
Array of evaluated vector values.
Detailed Description
Evaluation structure that holds evaluated values.
Definition at line 18 of file MovieSceneParameterTemplate.h.
Constructor & Destructor Documentation
FEvaluatedParameterSectionValues() [1/3]
FEvaluatedParameterSectionValues::FEvaluatedParameterSectionValues () default
Referenced by FEvaluatedParameterSectionValues(), FEvaluatedParameterSectionValues(), operator=(), and operator=().
FEvaluatedParameterSectionValues() [2/3]
FEvaluatedParameterSectionValues::FEvaluatedParameterSectionValues (FEvaluatedParameterSectionValues &&) default
References FEvaluatedParameterSectionValues().
FEvaluatedParameterSectionValues() [3/3]
FEvaluatedParameterSectionValues::FEvaluatedParameterSectionValues (const FEvaluatedParameterSectionValues &) delete
References FEvaluatedParameterSectionValues().
Member Function Documentation
operator=() [1/2]
FEvaluatedParameterSectionValues & FEvaluatedParameterSectionValues::operator= (const FEvaluatedParameterSectionValues &) delete
References FEvaluatedParameterSectionValues().
operator=() [2/2]
FEvaluatedParameterSectionValues & FEvaluatedParameterSectionValues::operator= (FEvaluatedParameterSectionValues &&) default
References FEvaluatedParameterSectionValues().
Field Documentation
BoolValues
TArray<FBoolParameterNameAndValue, TInlineAllocator<2> > FEvaluatedParameterSectionValues::BoolValues
Array of evaluated bool values.
Definition at line 32 of file MovieSceneParameterTemplate.h.
ColorValues
TArray<FColorParameterNameAndValue, TInlineAllocator<2> > FEvaluatedParameterSectionValues::ColorValues
Array of evaluated color values.
Definition at line 38 of file MovieSceneParameterTemplate.h.
ScalarValues
TArray<FScalarParameterNameAndValue, TInlineAllocator<2> > FEvaluatedParameterSectionValues::ScalarValues
Array of evaluated scalar values.
Definition at line 30 of file MovieSceneParameterTemplate.h.
TransformValues
TArray<FTransformParameterNameAndValue, TInlineAllocator<2> > FEvaluatedParameterSectionValues::TransformValues
Array of evaluated transform values.
Definition at line 40 of file MovieSceneParameterTemplate.h.
Vector2DValues
TArray<FVector2DParameterNameAndValue, TInlineAllocator<2> > FEvaluatedParameterSectionValues::Vector2DValues
Array of evaluated vector2D values.
Definition at line 34 of file MovieSceneParameterTemplate.h.
VectorValues
TArray<FVectorParameterNameAndValue, TInlineAllocator<2> > FEvaluatedParameterSectionValues::VectorValues
Array of evaluated vector values.
Definition at line 36 of file MovieSceneParameterTemplate.h.
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/Evaluation/MovieSceneParameterTemplate.h