Unreal Engine 5.6 C++ API: FRigVMStringWithTag Struct Reference
FRigVMStringWithTag Struct Reference
#include "RigVMEdGraph.h"
Public Member Functions
FRigVMStringWithTag ()=default
FRigVMStringWithTag (const FString &InString, const FRigVMStringTag &InTag=FRigVMStringTag())
bool Equals (const FRigVMStringWithTag &InOther) const
bool Equals (const FString &InOther) const
const FString & GetString () const
FString GetStringWithTag () const
const FRigVMStringTag & GetTag () const
bool HasTag () const
bool operator< (const FRigVMStringWithTag &InOther) const
bool operator== (const FRigVMStringWithTag &InOther) const
bool operator> (const FRigVMStringWithTag &InOther) const
Private Attributes
FString String
FRigVMStringTag Tag
Detailed Description
Definition at line 61 of file RigVMEdGraph.h.
Constructor & Destructor Documentation
FRigVMStringWithTag() [1/2]
FRigVMStringWithTag::FRigVMStringWithTag () default
Referenced by Equals(), operator<(), operator==(), and operator>().
FRigVMStringWithTag() [2/2]
FRigVMStringWithTag::FRigVMStringWithTag (const FString & InString, const FRigVMStringTag & InTag = FRigVMStringTag()) inline
Definition at line 67 of file RigVMEdGraph.h.
References String, and Tag.
Member Function Documentation
Equals() [1/2]
bool FRigVMStringWithTag::Equals (const FRigVMStringWithTag & InOther) const inline
Definition at line 118 of file RigVMEdGraph.h.
References FRigVMStringWithTag(), Equals(), and GetString().
Equals() [2/2]
bool FRigVMStringWithTag::Equals (const FString & InOther) const inline
Definition at line 113 of file RigVMEdGraph.h.
References ESearchCase::CaseSensitive, and GetString().
Referenced by Equals(), and operator==().
GetString()
const FString & FRigVMStringWithTag::GetString () const inline
Definition at line 73 of file RigVMEdGraph.h.
References String.
Referenced by Equals(), Equals(), GetStringWithTag(), operator<(), and operator>().
GetStringWithTag()
FString FRigVMStringWithTag::GetStringWithTag () const inline
Definition at line 78 of file RigVMEdGraph.h.
References Format, GetString(), GetTag(), HasTag(), TEXT, and ToString().
GetTag()
const FRigVMStringTag & FRigVMStringWithTag::GetTag () const inline
Definition at line 93 of file RigVMEdGraph.h.
References Tag.
Referenced by GetStringWithTag().
HasTag()
bool FRigVMStringWithTag::HasTag () const inline
Definition at line 88 of file RigVMEdGraph.h.
References Tag.
Referenced by GetStringWithTag().
operator<()
bool FRigVMStringWithTag::operator< (const FRigVMStringWithTag & InOther) const inline
Definition at line 108 of file RigVMEdGraph.h.
References FRigVMStringWithTag(), and GetString().
operator==()
bool FRigVMStringWithTag::operator== (const FRigVMStringWithTag & InOther) const inline
Definition at line 98 of file RigVMEdGraph.h.
References FRigVMStringWithTag(), and Equals().
operator>()
bool FRigVMStringWithTag::operator> (const FRigVMStringWithTag & InOther) const inline
Definition at line 103 of file RigVMEdGraph.h.
References FRigVMStringWithTag(), and GetString().
Field Documentation
String
FString FRigVMStringWithTag::String private
Definition at line 124 of file RigVMEdGraph.h.
Referenced by FRigVMStringWithTag(), and GetString().
Tag
FRigVMStringTag FRigVMStringWithTag::Tag private
Definition at line 125 of file RigVMEdGraph.h.
Referenced by FRigVMStringWithTag(), GetTag(), and HasTag().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/EdGraph/RigVMEdGraph.h