Unreal Engine 5.6 C++ API: FDisplayClusterShaderParameters_GenerateMips Struct Reference
FDisplayClusterShaderParameters_GenerateMips Struct Reference
#include "DisplayClusterShaderParameters_GenerateMips.h"
Public Member Functions
int32 GetRequiredNumMips (const FIntPoint &InDim) const
bool IsEnabled () const
void Reset ()
Data Fields
bool bAutoGenerateMips = false
int32 MaxNumMipsLimit = -1
TEnumAsByte< enum TextureAddress > MipsAddressU = TA_Clamp
TEnumAsByte< enum TextureAddress > MipsAddressV = TA_Clamp
TEnumAsByte< enum TextureFilter > MipsSamplerFilter = TF_Trilinear
Detailed Description
Definition at line 11 of file DisplayClusterShaderParameters_GenerateMips.h.
Member Function Documentation
GetRequiredNumMips()
int32 FDisplayClusterShaderParameters_GenerateMips::GetRequiredNumMips (const FIntPoint & InDim) const inline
Definition at line 36 of file DisplayClusterShaderParameters_GenerateMips.h.
References FGenericPlatformMath::FloorToInt(), IsEnabled(), FGenericPlatformMath::Log2(), MaxNumMipsLimit, FGenericPlatformMath::Min(), FMath::Min, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
IsEnabled()
bool FDisplayClusterShaderParameters_GenerateMips::IsEnabled () const inline
Definition at line 31 of file DisplayClusterShaderParameters_GenerateMips.h.
References bAutoGenerateMips, and MaxNumMipsLimit.
Referenced by GetRequiredNumMips().
Reset()
void FDisplayClusterShaderParameters_GenerateMips::Reset () inline
Definition at line 26 of file DisplayClusterShaderParameters_GenerateMips.h.
References bAutoGenerateMips.
Field Documentation
bAutoGenerateMips
bool FDisplayClusterShaderParameters_GenerateMips::bAutoGenerateMips = false
Definition at line 15 of file DisplayClusterShaderParameters_GenerateMips.h.
Referenced by IsEnabled(), and Reset().
MaxNumMipsLimit
int32 FDisplayClusterShaderParameters_GenerateMips::MaxNumMipsLimit = -1
Definition at line 23 of file DisplayClusterShaderParameters_GenerateMips.h.
Referenced by GetRequiredNumMips(), and IsEnabled().
MipsAddressU
TEnumAsByte<enum TextureAddress> FDisplayClusterShaderParameters_GenerateMips::MipsAddressU = TA_Clamp
Definition at line 19 of file DisplayClusterShaderParameters_GenerateMips.h.
MipsAddressV
TEnumAsByte<enum TextureAddress> FDisplayClusterShaderParameters_GenerateMips::MipsAddressV = TA_Clamp
Definition at line 20 of file DisplayClusterShaderParameters_GenerateMips.h.
MipsSamplerFilter
TEnumAsByte<enum TextureFilter> FDisplayClusterShaderParameters_GenerateMips::MipsSamplerFilter = TF_Trilinear
Definition at line 18 of file DisplayClusterShaderParameters_GenerateMips.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterShaders/Public/ShaderParameters/DisplayClusterShaderParameters_GenerateMips.h