Unreal Engine 5.6 C++ API: UE::Sequencer::TViewModelTypeID< T > Struct Template Reference
UE::Sequencer::TViewModelTypeID< T > Struct Template Reference
#include "ViewModelTypeID.h"
Public Member Functions
uint32 GetTypeID () const
FCastableTypeTable * GetTypeTable () const
operator FViewModelTypeID () const
void Register () const
Protected Member Functions
bool IsRegistered () const
Protected Attributes
uint32 ID = ~0u
friend T
FCastableTypeTable * TypeTable = nullptr
Detailed Description
template<typename T>
struct UE::Sequencer::TViewModelTypeID< T >
Definition at line 67 of file ViewModelTypeID.h.
Member Function Documentation
GetTypeID()
template<typename T> uint32 UE::Sequencer::TViewModelTypeID< T >::GetTypeID () const inline
Definition at line 75 of file ViewModelTypeID.h.
References ID, and Register().
GetTypeTable()
template<typename T> FCastableTypeTable * UE::Sequencer::TViewModelTypeID< T >::GetTypeTable () const inline
Definition at line 81 of file ViewModelTypeID.h.
References Register(), and TypeTable.
IsRegistered()
template<typename T> bool UE::Sequencer::TViewModelTypeID< T >::IsRegistered () const inline protected
Definition at line 98 of file ViewModelTypeID.h.
References ID.
Referenced by Register().
operator FViewModelTypeID()
template<typename T> UE::Sequencer::TViewModelTypeID< T >::operator FViewModelTypeID () const inline
Definition at line 69 of file ViewModelTypeID.h.
References ID, Register(), and TypeTable.
Register()
template<typename T> void UE::Sequencer::TViewModelTypeID< T >::Register () const inline
Definition at line 87 of file ViewModelTypeID.h.
References IsRegistered().
Referenced by GetTypeID(), GetTypeTable(), and operator FViewModelTypeID().
Field Documentation
ID
template<typename T> uint32 UE::Sequencer::TViewModelTypeID< T >::ID = ~0u protected
Definition at line 104 of file ViewModelTypeID.h.
Referenced by GetTypeID(), IsRegistered(), and operator FViewModelTypeID().
T
template<typename T> friend UE::Sequencer::TViewModelTypeID< T >::T protected
Definition at line 96 of file ViewModelTypeID.h.
TypeTable
template<typename T> FCastableTypeTable* UE::Sequencer::TViewModelTypeID< T >::TypeTable = nullptr protected
Definition at line 103 of file ViewModelTypeID.h.
Referenced by GetTypeTable(), and operator FViewModelTypeID().
The documentation for this struct was generated from the following files:
Editor/SequencerCore/Public/MVVM/CastableTypeTable.h
Editor/SequencerCore/Public/MVVM/ViewModelTypeID.h