Unreal Engine 5.6 C++ API: FScopedPreAnimatedCaptureSource Struct Reference
FScopedPreAnimatedCaptureSource Struct Reference
Scoped structure that can be used to wrap a call to SavePreAnimatedState to associate the capture with a specific capture source.
#include "MovieScenePreAnimatedCaptureSource.h"
Public Types
using FRootInstanceHandle = UE::MovieScene::FRootInstanceHandle
using FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Public Member Functions
FScopedPreAnimatedCaptureSource (const FScopedPreAnimatedCaptureSource &)=delete
MOVIESCENE_API FScopedPreAnimatedCaptureSource (FMovieScenePreAnimatedState *InPreAnimatedState, const FMovieSceneEvaluationKey &InEvalKey, bool bInWantsRestoreState)
Construct this capture source from a template (FMovieSceneEvalTemplate) evaluation key, and whether this should restore state when the template is finished.
MOVIESCENE_API FScopedPreAnimatedCaptureSource (FMovieScenePreAnimatedState *InPreAnimatedState, const UObject *InEvalHook, FMovieSceneSequenceID InSequenceID, bool bInWantsRestoreState)
Construct this capture source from an evaluation hook (UMovieSceneEvaluationHookSection), its instance handle, and whether this should restore state when the template is finished.
FScopedPreAnimatedCaptureSource (FScopedPreAnimatedCaptureSource &&)=delete
MOVIESCENE_API FScopedPreAnimatedCaptureSource (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const FMovieSceneEvaluationKey &InEvalKey, bool bInWantsRestoreState)
Construct this capture source from a template (FMovieSceneEvalTemplate) evaluation key, and whether this should restore state when the template is finished.
MOVIESCENE_API FScopedPreAnimatedCaptureSource (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const UObject *InEvalHook, FMovieSceneSequenceID InSequenceID, bool bInWantsRestoreState)
Construct this capture source from an evaluation hook (UMovieSceneEvaluationHookSection), its instance handle, and whether this should restore state when the template is finished.
MOVIESCENE_API FScopedPreAnimatedCaptureSource (UMovieSceneEntitySystemLinker *InLinker, const FMovieSceneTrackInstanceInput &TrackInstanceInput)
Construct this capture source from a track instance input (UMovieSceneTrackInstance + FMovieSceneTrackInstanceInput) and whether this should restore state when the template is finished.
MOVIESCENE_API FScopedPreAnimatedCaptureSource (UMovieSceneEntitySystemLinker *InLinker, UMovieSceneTrackInstance *InTrackInstance, bool bInWantsRestoreState)
Construct this capture source from a track instance (UMovieSceneTrackInstance) and whether this should restore state when the template is finished.
MOVIESCENE_API ~FScopedPreAnimatedCaptureSource ()
void operator= (const FScopedPreAnimatedCaptureSource &)=delete
void operator= (FScopedPreAnimatedCaptureSource &&)=delete
bool WantsRestoreState () const
Private Types
using CaptureSourceType = TVariant<FPreAnimatedEvaluationKeyType, FPreAnimatedEvalHookKeyType, UMovieSceneTrackInstance*, FMovieSceneTrackInstanceInput>
using FPreAnimatedEvalHookKeyType = UE::MovieScene::FPreAnimatedEvalHookKeyType
using FPreAnimatedEvaluationKeyType = UE::MovieScene::FPreAnimatedEvaluationKeyType
Private Member Functions
void BeginTracking (const UE::MovieScene::FPreAnimatedStateMetaData &MetaData, UMovieSceneEntitySystemLinker *Linker)
FRootInstanceHandle GetRootInstanceHandle (UMovieSceneEntitySystemLinker *Linker) const
Static Private Member Functions
static FScopedPreAnimatedCaptureSource *& GetCaptureSourcePtr ()
Private Attributes
bool bWantsRestoreState
FScopedPreAnimatedCaptureSource * PrevCaptureSource
FRootInstanceHandle RootInstanceHandle
CaptureSourceType Variant
TWeakObjectPtr< UMovieSceneEntitySystemLinker > WeakLinker
Friends
class FMovieSceneEntitySystemRunner
struct UE::MovieScene::FPreAnimatedStateExtension
Detailed Description
Scoped structure that can be used to wrap a call to SavePreAnimatedState to associate the capture with a specific capture source.
Definition at line 39 of file MovieScenePreAnimatedCaptureSource.h.
Member Typedef Documentation
CaptureSourceType
using FScopedPreAnimatedCaptureSource::CaptureSourceType = TVariant<FPreAnimatedEvaluationKeyType, FPreAnimatedEvalHookKeyType, UMovieSceneTrackInstance*, FMovieSceneTrackInstanceInput> private
Definition at line 99 of file MovieScenePreAnimatedCaptureSource.h.
FPreAnimatedEvalHookKeyType
using FScopedPreAnimatedCaptureSource::FPreAnimatedEvalHookKeyType = UE::MovieScene::FPreAnimatedEvalHookKeyType private
Definition at line 98 of file MovieScenePreAnimatedCaptureSource.h.
FPreAnimatedEvaluationKeyType
using FScopedPreAnimatedCaptureSource::FPreAnimatedEvaluationKeyType = UE::MovieScene::FPreAnimatedEvaluationKeyType private
Definition at line 97 of file MovieScenePreAnimatedCaptureSource.h.
FRootInstanceHandle
using FScopedPreAnimatedCaptureSource::FRootInstanceHandle = UE::MovieScene::FRootInstanceHandle
Definition at line 41 of file MovieScenePreAnimatedCaptureSource.h.
FSharedPlaybackState
using FScopedPreAnimatedCaptureSource::FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Definition at line 42 of file MovieScenePreAnimatedCaptureSource.h.
Constructor & Destructor Documentation
FScopedPreAnimatedCaptureSource() [1/8]
MOVIESCENE_API FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const FMovieSceneEvaluationKey & InEvalKey, bool bInWantsRestoreState) explicit
Construct this capture source from a template (FMovieSceneEvalTemplate) evaluation key, and whether this should restore state when the template is finished.
Referenced by FScopedPreAnimatedCaptureSource(), FScopedPreAnimatedCaptureSource(), GetCaptureSourcePtr(), operator=(), and operator=().
FScopedPreAnimatedCaptureSource() [2/8]
MOVIESCENE_API FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (FMovieScenePreAnimatedState * InPreAnimatedState, const FMovieSceneEvaluationKey & InEvalKey, bool bInWantsRestoreState) explicit
Construct this capture source from a template (FMovieSceneEvalTemplate) evaluation key, and whether this should restore state when the template is finished.
FScopedPreAnimatedCaptureSource() [3/8]
MOVIESCENE_API FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const UObject * InEvalHook, FMovieSceneSequenceID InSequenceID, bool bInWantsRestoreState) explicit
Construct this capture source from an evaluation hook (UMovieSceneEvaluationHookSection), its instance handle, and whether this should restore state when the template is finished.
FScopedPreAnimatedCaptureSource() [4/8]
MOVIESCENE_API FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (FMovieScenePreAnimatedState * InPreAnimatedState, const UObject * InEvalHook, FMovieSceneSequenceID InSequenceID, bool bInWantsRestoreState) explicit
Construct this capture source from an evaluation hook (UMovieSceneEvaluationHookSection), its instance handle, and whether this should restore state when the template is finished.
FScopedPreAnimatedCaptureSource() [5/8]
MOVIESCENE_API FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (UMovieSceneEntitySystemLinker * InLinker, UMovieSceneTrackInstance * InTrackInstance, bool bInWantsRestoreState) explicit
Construct this capture source from a track instance (UMovieSceneTrackInstance) and whether this should restore state when the template is finished.
FScopedPreAnimatedCaptureSource() [6/8]
MOVIESCENE_API FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (UMovieSceneEntitySystemLinker * InLinker, const FMovieSceneTrackInstanceInput & TrackInstanceInput) explicit
Construct this capture source from a track instance input (UMovieSceneTrackInstance + FMovieSceneTrackInstanceInput) and whether this should restore state when the template is finished.
FScopedPreAnimatedCaptureSource() [7/8]
FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (const FScopedPreAnimatedCaptureSource &) delete
References FScopedPreAnimatedCaptureSource().
FScopedPreAnimatedCaptureSource() [8/8]
FScopedPreAnimatedCaptureSource::FScopedPreAnimatedCaptureSource (FScopedPreAnimatedCaptureSource &&) delete
References FScopedPreAnimatedCaptureSource().
~FScopedPreAnimatedCaptureSource()
MOVIESCENE_API FScopedPreAnimatedCaptureSource::~FScopedPreAnimatedCaptureSource ()
Member Function Documentation
BeginTracking()
void FScopedPreAnimatedCaptureSource::BeginTracking (const UE::MovieScene::FPreAnimatedStateMetaData & MetaData, UMovieSceneEntitySystemLinker * Linker) private
References MetaData.
GetCaptureSourcePtr()
FScopedPreAnimatedCaptureSource *& FScopedPreAnimatedCaptureSource::GetCaptureSourcePtr () static private
References FScopedPreAnimatedCaptureSource().
GetRootInstanceHandle()
FRootInstanceHandle FScopedPreAnimatedCaptureSource::GetRootInstanceHandle (UMovieSceneEntitySystemLinker * Linker) const private
operator=() [1/2]
void FScopedPreAnimatedCaptureSource::operator= (const FScopedPreAnimatedCaptureSource &) delete
References FScopedPreAnimatedCaptureSource().
operator=() [2/2]
void FScopedPreAnimatedCaptureSource::operator= (FScopedPreAnimatedCaptureSource &&) delete
References FScopedPreAnimatedCaptureSource().
WantsRestoreState()
bool FScopedPreAnimatedCaptureSource::WantsRestoreState () const inline
Definition at line 82 of file MovieScenePreAnimatedCaptureSource.h.
References bWantsRestoreState.
Friends And Related Symbol Documentation
FMovieSceneEntitySystemRunner
friend class FMovieSceneEntitySystemRunner friend
Definition at line 89 of file MovieScenePreAnimatedCaptureSource.h.
References FMovieSceneEntitySystemRunner.
Referenced by FMovieSceneEntitySystemRunner.
UE::MovieScene::FPreAnimatedStateExtension
friend struct UE::MovieScene::FPreAnimatedStateExtension friend
Definition at line 90 of file MovieScenePreAnimatedCaptureSource.h.
Field Documentation
bWantsRestoreState
bool FScopedPreAnimatedCaptureSource::bWantsRestoreState private
Definition at line 105 of file MovieScenePreAnimatedCaptureSource.h.
Referenced by WantsRestoreState().
PrevCaptureSource
FScopedPreAnimatedCaptureSource* FScopedPreAnimatedCaptureSource::PrevCaptureSource private
Definition at line 104 of file MovieScenePreAnimatedCaptureSource.h.
RootInstanceHandle
FRootInstanceHandle FScopedPreAnimatedCaptureSource::RootInstanceHandle private
Definition at line 102 of file MovieScenePreAnimatedCaptureSource.h.
Variant
CaptureSourceType FScopedPreAnimatedCaptureSource::Variant private
Definition at line 101 of file MovieScenePreAnimatedCaptureSource.h.
WeakLinker
TWeakObjectPtr<UMovieSceneEntitySystemLinker> FScopedPreAnimatedCaptureSource::WeakLinker private
Definition at line 103 of file MovieScenePreAnimatedCaptureSource.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/PreAnimatedState/MovieScenePreAnimatedCaptureSource.h