Unreal Engine 5.6 C++ API: FDFVector2 Struct Reference
FDFVector2 Struct Reference
#include "DoubleFloat.h"
Public Member Functions
FDFVector2 ()=default
template<typename TInputScalar = double>
FDFVector2 (const UE::Math::TVector2< TInputScalar > &In)
FDFVector2 (FVector2f High, FVector2f Low)
FVector2d GetVector2d () const
FDFScalar X () const
FDFScalar Y () const
Data Fields
FVector2f High {}
FVector2f Low {}
Detailed Description
Definition at line 38 of file DoubleFloat.h.
Constructor & Destructor Documentation
FDFVector2() [1/3]
template<typename TInputScalar = double> FDFVector2::FDFVector2 (const UE::Math::TVector2< TInputScalar > & In) inline nodiscard
Definition at line 46 of file DoubleFloat.h.
References High, Low, X(), UE::Math::TVector2< T >::X, Y(), and UE::Math::TVector2< T >::Y.
FDFVector2() [2/3]
FDFVector2::FDFVector2 (FVector2f High, FVector2f Low) inline nodiscard
Definition at line 54 of file DoubleFloat.h.
References High, and Low.
FDFVector2() [3/3]
FDFVector2::FDFVector2 () nodiscard default
Member Function Documentation
GetVector2d()
FVector2d FDFVector2::GetVector2d () const inline nodiscard
Definition at line 40 of file DoubleFloat.h.
References FDFScalar::GetDouble(), X(), and Y().
X()
FDFScalar FDFVector2::X () const inline nodiscard
Definition at line 60 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector2(), and GetVector2d().
Y()
FDFScalar FDFVector2::Y () const inline nodiscard
Definition at line 65 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector2(), and GetVector2d().
Field Documentation
High
FVector2f FDFVector2::High {}
Definition at line 70 of file DoubleFloat.h.
Referenced by FDFVector2(), FDFVector2(), X(), and Y().
Low
FVector2f FDFVector2::Low {}
Definition at line 71 of file DoubleFloat.h.
Referenced by FDFVector2(), FDFVector2(), X(), and Y().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/DoubleFloat.h