Unreal Engine 5.6 C++ API: FDFVector3 Struct Reference
FDFVector3 Struct Reference
#include "DoubleFloat.h"
Public Member Functions
FDFVector3 ()=default
template<typename TInputScalar = double>
FDFVector3 (const UE::Math::TVector< TInputScalar > &In)
FDFVector3 (FVector3f High, FVector3f Low)
FVector3d GetVector3d () const
FDFScalar X () const
FDFScalar Y () const
FDFScalar Z () const
Data Fields
FVector3f High {}
FVector3f Low {}
Detailed Description
Definition at line 74 of file DoubleFloat.h.
Constructor & Destructor Documentation
FDFVector3() [1/3]
template<typename TInputScalar = double> FDFVector3::FDFVector3 (const UE::Math::TVector< TInputScalar > & In) inline
Definition at line 82 of file DoubleFloat.h.
References High, Low, X(), UE::Math::TVector< T >::X, Y(), UE::Math::TVector< T >::Y, Z(), and UE::Math::TVector< T >::Z.
FDFVector3() [2/3]
FDFVector3::FDFVector3 (FVector3f High, FVector3f Low) inline
Definition at line 91 of file DoubleFloat.h.
References High, and Low.
FDFVector3() [3/3]
FDFVector3::FDFVector3 () default
Member Function Documentation
GetVector3d()
FVector3d FDFVector3::GetVector3d () const inline nodiscard
Definition at line 76 of file DoubleFloat.h.
References FDFScalar::GetDouble(), X(), Y(), and Z().
X()
FDFScalar FDFVector3::X () const inline nodiscard
Definition at line 97 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector3(), and GetVector3d().
Y()
FDFScalar FDFVector3::Y () const inline nodiscard
Definition at line 102 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector3(), and GetVector3d().
Z()
FDFScalar FDFVector3::Z () const inline nodiscard
Definition at line 107 of file DoubleFloat.h.
References High, and Low.
Referenced by FDFVector3(), and GetVector3d().
Field Documentation
High
FVector3f FDFVector3::High {}
Definition at line 112 of file DoubleFloat.h.
Referenced by FDFVector3(), FDFVector3(), FPrimitiveUniformShaderParametersBuilder::Build(), X(), Y(), and Z().
Low
FVector3f FDFVector3::Low {}
Definition at line 113 of file DoubleFloat.h.
Referenced by FDFVector3(), FDFVector3(), FPrimitiveUniformShaderParametersBuilder::Build(), X(), Y(), and Z().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/DoubleFloat.h