Unreal Engine 5.6 C++ API: FMaterialShaderType::CompiledShaderInitializerType Struct Reference
FMaterialShaderType::CompiledShaderInitializerType Struct Reference
#include "MaterialShaderType.h"
Public Member Functions
CompiledShaderInitializerType (const FShaderType *InType, int32 InPermutationId, const FShaderCompilerOutput &CompilerOutput, const FUniformExpressionSet &InUniformExpressionSet, const FSHAHash &InMaterialShaderMapHash, const FShaderPipelineType *InShaderPipeline, const FVertexFactoryType *InVertexFactoryType, const FString &InDebugDescription)
Public Member Functions inherited from FShaderCompiledShaderInitializerType
RENDERCORE_API FShaderCompiledShaderInitializerType (const FShaderType *InType, const FShaderType::FParameters *InParameters, int32 InPermutationId, const FShaderCompilerOutput &CompilerOutput, const FSHAHash &InMaterialShaderMapHash, const FShaderPipelineType *InShaderPipeline, const FVertexFactoryType *InVertexFactoryType)
Data Fields
const FString DebugDescription
const FUniformExpressionSet & UniformExpressionSet
Data Fields inherited from FShaderCompiledShaderInitializerType
TConstArrayView< uint8 > Code
uint32 CodeSize
FSHAHash MaterialShaderMapHash
uint32 NumInstructions
uint32 NumTextureSamplers
const FSHAHash & OutputHash
const FShaderParameterMap & ParameterMap
const FShaderType::FParameters * Parameters
int32 PermutationId
const FShaderPipelineType * ShaderPipeline
TArray< FGenericShaderStat > ShaderStatistics
FShaderTarget Target
const FShaderType * Type
const FVertexFactoryType * VertexFactoryType
Detailed Description
Definition at line 104 of file MaterialShaderType.h.
Constructor & Destructor Documentation
CompiledShaderInitializerType()
FMaterialShaderType::CompiledShaderInitializerType::CompiledShaderInitializerType (const FShaderType * InType, int32 InPermutationId, const FShaderCompilerOutput & CompilerOutput, const FUniformExpressionSet & InUniformExpressionSet, const FSHAHash & InMaterialShaderMapHash, const FShaderPipelineType * InShaderPipeline, const FVertexFactoryType * InVertexFactoryType, const FString & InDebugDescription) inline
Definition at line 109 of file MaterialShaderType.h.
References CompiledShaderInitializerType(), FShaderType::FShaderType(), DebugDescription, and UniformExpressionSet.
Referenced by CompiledShaderInitializerType().
Field Documentation
DebugDescription
const FString FMaterialShaderType::CompiledShaderInitializerType::DebugDescription
Definition at line 107 of file MaterialShaderType.h.
Referenced by CompiledShaderInitializerType().
UniformExpressionSet
const FUniformExpressionSet& FMaterialShaderType::CompiledShaderInitializerType::UniformExpressionSet
Definition at line 106 of file MaterialShaderType.h.
Referenced by CompiledShaderInitializerType().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/MaterialShaderType.h