Unreal Engine 5.6 C++ API: UE::Geometry::FGeoSelectionID Struct Reference
UE::Geometry::FGeoSelectionID Struct Reference
FGeoSelectionID provides a pair of 32-bit unsigned integers that can be packed into a 64-bit unsigned integer for use with FGeometrySelection.
#include "GeometrySelection.h"
Public Member Functions
FGeoSelectionID ()
FGeoSelectionID (uint32 GeometryIDIn, uint32 TopologyIDIn=0)
Initialize the TopologyID and GeometryID with the given values.
FGeoSelectionID (uint64 EncodedID)
Initialize the TopologyID and GeometryID by unpacking the 64-bit packed EncodedID.
uint64 Encoded () const
Static Public Member Functions
static FGeoSelectionID GroupFace (int32 TriangleID, int32 GroupID)
static FGeoSelectionID MeshEdge (UE::Geometry::FMeshTriEdgeID EdgeKey)
static FGeoSelectionID MeshTriangle (int32 TriangleID)
static FGeoSelectionID MeshVertex (int32 VertexID)
Data Fields
uint32 GeometryID
Geometry ID, stored in lower 32 bits when packed into 64-bits.
uint32 TopologyID
Topology ID, stored in upper 32 bits when packed into 64-bits.
Friends
uint32 GetTypeHash (const FGeoSelectionID &TopoKey)
Detailed Description
FGeoSelectionID provides a pair of 32-bit unsigned integers that can be packed into a 64-bit unsigned integer for use with FGeometrySelection.
This is generally intended to be used to encode a mesh geometry ID (eg TriangleID, EdgeID, VertexID) combined with a "Topology ID", eg something like a Face Group ID. However none of this is enforced and so a caller can use these two integers for any purpose.
Note that since the ints are unsigned, IndexConstants::InvalidID is not directly representable (-1 will become positive 0xFFFFFFFF).
Definition at line 31 of file GeometrySelection.h.
Constructor & Destructor Documentation
FGeoSelectionID() [1/3]
UE::Geometry::FGeoSelectionID::FGeoSelectionID () inline
Definition at line 38 of file GeometrySelection.h.
References GeometryID, and TopologyID.
Referenced by GetTypeHash, GroupFace(), MeshEdge(), MeshTriangle(), and MeshVertex().
FGeoSelectionID() [2/3]
UE::Geometry::FGeoSelectionID::FGeoSelectionID (uint32 GeometryIDIn, uint32 TopologyIDIn = 0) inline explicit
Initialize the TopologyID and GeometryID with the given values.
Definition at line 47 of file GeometrySelection.h.
References GeometryID, and TopologyID.
FGeoSelectionID() [3/3]
UE::Geometry::FGeoSelectionID::FGeoSelectionID (uint64 EncodedID) inline explicit
Initialize the TopologyID and GeometryID by unpacking the 64-bit packed EncodedID.
Definition at line 56 of file GeometrySelection.h.
References GeometryID, and TopologyID.
Member Function Documentation
Encoded()
uint64 UE::Geometry::FGeoSelectionID::Encoded () const inline
Returns
the packed 64-bit representation of [TopologyID, GeometryID]
Definition at line 65 of file GeometrySelection.h.
References GeometryID, and TopologyID.
Referenced by GetTypeHash.
GroupFace()
FGeoSelectionID UE::Geometry::FGeoSelectionID::GroupFace (int32 TriangleID, int32 GroupID) inline static
Returns
a FGeoSelectionID initialized with the given TriangleID and GroupID used as the TopologyID
Definition at line 97 of file GeometrySelection.h.
References FGeoSelectionID().
MeshEdge()
FGeoSelectionID UE::Geometry::FGeoSelectionID::MeshEdge (UE::Geometry::FMeshTriEdgeID EdgeKey) inline static
Returns
a FGeoSelectionID initialized with the given 32-bit encoding of the MeshTriEdgeID, and a TopologyID of 0
Definition at line 89 of file GeometrySelection.h.
References FGeoSelectionID(), and UE::Geometry::FMeshTriEdgeID::Encoded().
MeshTriangle()
FGeoSelectionID UE::Geometry::FGeoSelectionID::MeshTriangle (int32 TriangleID) inline static
Returns
a FGeoSelectionID initialized with the given TriangleID, and a TopologyID of 0
Definition at line 73 of file GeometrySelection.h.
References FGeoSelectionID().
MeshVertex()
FGeoSelectionID UE::Geometry::FGeoSelectionID::MeshVertex (int32 VertexID) inline static
Returns
a FGeoSelectionID initialized with the given VertexID, and a TopologyID of 0
Definition at line 81 of file GeometrySelection.h.
References FGeoSelectionID().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FGeoSelectionID & TopoKey) friend
Definition at line 102 of file GeometrySelection.h.
References FGeoSelectionID(), and Encoded().
Field Documentation
GeometryID
uint32 UE::Geometry::FGeoSelectionID::GeometryID
Geometry ID, stored in lower 32 bits when packed into 64-bits.
Definition at line 36 of file GeometrySelection.h.
Referenced by FGeoSelectionID(), FGeoSelectionID(), FGeoSelectionID(), and Encoded().
TopologyID
uint32 UE::Geometry::FGeoSelectionID::TopologyID
Topology ID, stored in upper 32 bits when packed into 64-bits.
Definition at line 34 of file GeometrySelection.h.
Referenced by FGeoSelectionID(), FGeoSelectionID(), FGeoSelectionID(), and Encoded().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Selections/GeometrySelection.h