Unreal Engine 5.6 C++ API: FAggregator Struct Reference
FAggregator Struct Reference
#include "GameplayEffectAggregator.h"
Public Member Functions
FAggregator (float InBaseValue=0.f)
GAMEPLAYABILITIES_API ~FAggregator ()
GAMEPLAYABILITIES_API void AddAggregatorMod (float EvaluatedData, TEnumAsByte< EGameplayModOp::Type > ModifierOp, EGameplayModEvaluationChannel ModifierChannel, const FGameplayTagRequirements *SourceTagReqs, const FGameplayTagRequirements *TargetTagReqs, bool IsPredicted, FActiveGameplayEffectHandle ActiveHandle=FActiveGameplayEffectHandle())
GAMEPLAYABILITIES_API void AddDependent (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API void AddModsFrom (const FAggregator &SourceAggregator)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAggregatorDirty, FAggregator *)
GAMEPLAYABILITIES_API float Evaluate (const FAggregatorEvaluateParameters &Parameters) const
Evaluates the Aggregator with the internal base value and given parameters.
GAMEPLAYABILITIES_API float EvaluateBonus (const FAggregatorEvaluateParameters &Parameters) const
Evaluates the Aggregator to compute its "bonus" (final - base) value.
GAMEPLAYABILITIES_API float EvaluateContribution (const FAggregatorEvaluateParameters &Parameters, FActiveGameplayEffectHandle ActiveHandle) const
Evaluates the contribution from the GE associated with ActiveHandle.
GAMEPLAYABILITIES_API void EvaluateQualificationForAllMods (const FAggregatorEvaluateParameters &Parameters) const
Calls ::UpdateQualifies on each mod.
GAMEPLAYABILITIES_API float EvaluateToChannel (const FAggregatorEvaluateParameters &Parameters, EGameplayModEvaluationChannel FinalChannel) const
Evaluates the aggregator with the internal base value and given parameters, up to the specified evaluation channel (inclusive)
GAMEPLAYABILITIES_API float EvaluateWithBase (float InlineBaseValue, const FAggregatorEvaluateParameters &Parameters) const
Evaluates the Aggregator with an arbitrary base value.
GAMEPLAYABILITIES_API void ExecModOnBaseValue (TEnumAsByte< EGameplayModOp::Type > ModifierOp, float EvaluatedMagnitude)
GAMEPLAYABILITIES_API void ForEachMod (TFunction< void(const FAggregatorModInfo &) >) const
Helper function for iterating through all mods within the aggregator.
GAMEPLAYABILITIES_API void GetAllAggregatorMods (OUT TMap< EGameplayModEvaluationChannel, const TArray< FAggregatorMod > * > &OutMods) const
Populate a mapping of channel to corresponding mods.
GAMEPLAYABILITIES_API float GetBaseValue () const
Simple accessor to base value.
GAMEPLAYABILITIES_API void OnActiveEffectDependenciesSwapped (const TMap< FActiveGameplayEffectHandle, FActiveGameplayEffectHandle > &SwappedDependencies)
Called when the aggregator's gameplay effect dependencies have potentially been swapped out for new ones, like when GE arrays are cloned.
GAMEPLAYABILITIES_API void RemoveAggregatorMod (FActiveGameplayEffectHandle ActiveHandle)
Removes all mods for the passed in handle and marks this as dirty to recalculate the aggregator.
GAMEPLAYABILITIES_API void RemoveDependent (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API float ReverseEvaluate (float FinalValue, const FAggregatorEvaluateParameters &Parameters) const
Works backwards to calculate the base value.
GAMEPLAYABILITIES_API void SetBaseValue (float NewBaseValue, bool BroadcastDirtyEvent=true)
GAMEPLAYABILITIES_API void TakeSnapshotOf (const FAggregator &AggToSnapshot)
GAMEPLAYABILITIES_API void UpdateAggregatorMod (FActiveGameplayEffectHandle ActiveHandle, const FGameplayAttribute &Attribute, const FGameplayEffectSpec &Spec, bool bWasLocallyGenerated, FActiveGameplayEffectHandle InHandle)
Updates the aggregators for the past in handle, this will handle it so the UAttributeSets stats only get one update for the delta change.
Public Member Functions inherited from TSharedFromThis< FAggregator >
TSharedRef< FAggregator, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAggregator, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static GAMEPLAYABILITIES_API float StaticExecModOnBaseValue (float BaseValue, TEnumAsByte< EGameplayModOp::Type > ModifierOp, float EvaluatedMagnitude)
Data Fields
FAggregatorEvaluateMetaData * EvaluationMetaData
Custom meta data for the aggregator.
int32 NetUpdateID
NetworkID that we had our last update from.
FOnAggregatorDirty OnDirty
FOnAggregatorDirty OnDirtyRecursive
Private Member Functions
GAMEPLAYABILITIES_API void BroadcastOnDirty ()
Private Attributes
float BaseValue
int32 BroadcastingDirtyCount
TArray< FActiveGameplayEffectHandle > Dependents
ActiveGE handles that we need to notify if we change.
FAggregatorModChannelContainer ModChannels
Friends
struct FActiveGameplayEffectsContainer
struct FScopedAggregatorOnDirtyBatch
class UAbilitySystemComponent
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FAggregator >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FAggregator >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 278 of file GameplayEffectAggregator.h.
Constructor & Destructor Documentation
FAggregator()
FAggregator::FAggregator (float InBaseValue = 0.f) inline
Definition at line 282 of file GameplayEffectAggregator.h.
References BaseValue, BroadcastingDirtyCount, EvaluationMetaData, and NetUpdateID.
Referenced by AddModsFrom(), DECLARE_MULTICAST_DELEGATE_OneParam(), and TakeSnapshotOf().
~FAggregator()
GAMEPLAYABILITIES_API FAggregator::~FAggregator ()
References UE_API.
Member Function Documentation
AddAggregatorMod()
GAMEPLAYABILITIES_API void FAggregator::AddAggregatorMod (float EvaluatedData, TEnumAsByte< EGameplayModOp::Type > ModifierOp, EGameplayModEvaluationChannel ModifierChannel, const FGameplayTagRequirements * SourceTagReqs, const FGameplayTagRequirements * TargetTagReqs, bool IsPredicted, FActiveGameplayEffectHandle ActiveHandle = FActiveGameplayEffectHandle())
References UE_API.
AddDependent()
GAMEPLAYABILITIES_API void FAggregator::AddDependent (FActiveGameplayEffectHandle Handle)
References Handle, and UE_API.
AddModsFrom()
GAMEPLAYABILITIES_API void FAggregator::AddModsFrom (const FAggregator & SourceAggregator)
References FAggregator(), and UE_API.
BroadcastOnDirty()
GAMEPLAYABILITIES_API void FAggregator::BroadcastOnDirty () private
References UE_API.
DECLARE_MULTICAST_DELEGATE_OneParam()
FAggregator::DECLARE_MULTICAST_DELEGATE_OneParam (FOnAggregatorDirty , FAggregator *)
References FAggregator().
Evaluate()
GAMEPLAYABILITIES_API float FAggregator::Evaluate (const FAggregatorEvaluateParameters & Parameters) const
Evaluates the Aggregator with the internal base value and given parameters.
References UE_API.
EvaluateBonus()
GAMEPLAYABILITIES_API float FAggregator::EvaluateBonus (const FAggregatorEvaluateParameters & Parameters) const
Evaluates the Aggregator to compute its "bonus" (final - base) value.
References UE_API.
EvaluateContribution()
GAMEPLAYABILITIES_API float FAggregator::EvaluateContribution (const FAggregatorEvaluateParameters & Parameters, FActiveGameplayEffectHandle ActiveHandle) const
Evaluates the contribution from the GE associated with ActiveHandle.
References UE_API.
EvaluateQualificationForAllMods()
GAMEPLAYABILITIES_API void FAggregator::EvaluateQualificationForAllMods (const FAggregatorEvaluateParameters & Parameters) const
Calls ::UpdateQualifies on each mod.
Useful for when you need to manually inspect aggregators
References UE_API.
EvaluateToChannel()
GAMEPLAYABILITIES_API float FAggregator::EvaluateToChannel (const FAggregatorEvaluateParameters & Parameters, EGameplayModEvaluationChannel FinalChannel) const
Evaluates the aggregator with the internal base value and given parameters, up to the specified evaluation channel (inclusive)
References UE_API.
EvaluateWithBase()
GAMEPLAYABILITIES_API float FAggregator::EvaluateWithBase (float InlineBaseValue, const FAggregatorEvaluateParameters & Parameters) const
Evaluates the Aggregator with an arbitrary base value.
References UE_API.
ExecModOnBaseValue()
GAMEPLAYABILITIES_API void FAggregator::ExecModOnBaseValue (TEnumAsByte< EGameplayModOp::Type > ModifierOp, float EvaluatedMagnitude)
References UE_API.
ForEachMod()
GAMEPLAYABILITIES_API void FAggregator::ForEachMod (TFunction< void(const FAggregatorModInfo &) >) const
Helper function for iterating through all mods within the aggregator.
References UE_API.
GetAllAggregatorMods()
GAMEPLAYABILITIES_API void FAggregator::GetAllAggregatorMods (OUT TMap< EGameplayModEvaluationChannel, const TArray< FAggregatorMod > * > & OutMods) const
Populate a mapping of channel to corresponding mods.
Parameters
OutMods Mapping of channel enum to mods
References OUT, and UE_API.
GetBaseValue()
GAMEPLAYABILITIES_API float FAggregator::GetBaseValue () const
Simple accessor to base value.
References UE_API.
OnActiveEffectDependenciesSwapped()
GAMEPLAYABILITIES_API void FAggregator::OnActiveEffectDependenciesSwapped (const TMap< FActiveGameplayEffectHandle, FActiveGameplayEffectHandle > & SwappedDependencies)
Called when the aggregator's gameplay effect dependencies have potentially been swapped out for new ones, like when GE arrays are cloned.
Updates the modifier channel container appropriately, as well as directly-specified dependents.
Parameters
SwappedDependencies Mapping of old gameplay effect handles to new replacements
References UE_API.
RemoveAggregatorMod()
GAMEPLAYABILITIES_API void FAggregator::RemoveAggregatorMod (FActiveGameplayEffectHandle ActiveHandle)
Removes all mods for the passed in handle and marks this as dirty to recalculate the aggregator.
References UE_API.
RemoveDependent()
GAMEPLAYABILITIES_API void FAggregator::RemoveDependent (FActiveGameplayEffectHandle Handle)
References Handle, and UE_API.
ReverseEvaluate()
GAMEPLAYABILITIES_API float FAggregator::ReverseEvaluate (float FinalValue, const FAggregatorEvaluateParameters & Parameters) const
Works backwards to calculate the base value.
Used on clients for doing predictive modifiers
References UE_API.
SetBaseValue()
GAMEPLAYABILITIES_API void FAggregator::SetBaseValue (float NewBaseValue, bool BroadcastDirtyEvent = true)
References UE_API.
StaticExecModOnBaseValue()
GAMEPLAYABILITIES_API float FAggregator::StaticExecModOnBaseValue (float BaseValue, TEnumAsByte< EGameplayModOp::Type > ModifierOp, float EvaluatedMagnitude) static
References BaseValue, and UE_API.
TakeSnapshotOf()
GAMEPLAYABILITIES_API void FAggregator::TakeSnapshotOf (const FAggregator & AggToSnapshot)
References FAggregator(), and UE_API.
UpdateAggregatorMod()
GAMEPLAYABILITIES_API void FAggregator::UpdateAggregatorMod (FActiveGameplayEffectHandle ActiveHandle, const FGameplayAttribute & Attribute, const FGameplayEffectSpec & Spec, bool bWasLocallyGenerated, FActiveGameplayEffectHandle InHandle)
Updates the aggregators for the past in handle, this will handle it so the UAttributeSets stats only get one update for the delta change.
References Attribute, and UE_API.
Friends And Related Symbol Documentation
FActiveGameplayEffectsContainer
friend struct FActiveGameplayEffectsContainer friend
Definition at line 373 of file GameplayEffectAggregator.h.
References FActiveGameplayEffectsContainer.
Referenced by FActiveGameplayEffectsContainer.
FScopedAggregatorOnDirtyBatch
friend struct FScopedAggregatorOnDirtyBatch friend
Definition at line 374 of file GameplayEffectAggregator.h.
References FScopedAggregatorOnDirtyBatch.
Referenced by FScopedAggregatorOnDirtyBatch.
UAbilitySystemComponent
friend class UAbilitySystemComponent friend
Definition at line 375 of file GameplayEffectAggregator.h.
References UAbilitySystemComponent.
Referenced by UAbilitySystemComponent.
Field Documentation
BaseValue
float FAggregator::BaseValue private
Definition at line 365 of file GameplayEffectAggregator.h.
Referenced by FAggregator(), and StaticExecModOnBaseValue().
BroadcastingDirtyCount
int32 FAggregator::BroadcastingDirtyCount private
Definition at line 370 of file GameplayEffectAggregator.h.
Referenced by FAggregator().
Dependents
TArray<FActiveGameplayEffectHandle> FAggregator::Dependents private
ActiveGE handles that we need to notify if we change.
NOT copied over during snapshots.
Definition at line 369 of file GameplayEffectAggregator.h.
EvaluationMetaData
FAggregatorEvaluateMetaData* FAggregator::EvaluationMetaData
Custom meta data for the aggregator.
Definition at line 356 of file GameplayEffectAggregator.h.
Referenced by FAggregator().
ModChannels
FAggregatorModChannelContainer FAggregator::ModChannels private
Definition at line 366 of file GameplayEffectAggregator.h.
NetUpdateID
int32 FAggregator::NetUpdateID
NetworkID that we had our last update from.
Will only be set on clients and is only used to ensure we don't recompute server base value twice.
Definition at line 359 of file GameplayEffectAggregator.h.
Referenced by FAggregator().
OnDirty
FOnAggregatorDirty FAggregator::OnDirty
Definition at line 329 of file GameplayEffectAggregator.h.
OnDirtyRecursive
FOnAggregatorDirty FAggregator::OnDirtyRecursive
Definition at line 330 of file GameplayEffectAggregator.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/GameplayEffectAggregator.h