Unreal Engine 5.6 C++ API: FGenericPlatformString Struct Reference
FGenericPlatformString Struct Reference
Generic string implementation for most platforms.
#include "GenericPlatformString.h"
Static Public Member Functions
template<typename DestEncoding, typename SourceEncoding>
static constexpr bool CanConvertCodepoint (SourceEncoding Codepoint)
Tests whether a particular codepoint can be converted to the destination encoding.
template<typename SourceEncoding, typename DestEncoding>
static FORCEINLINE DestEncoding * Convert (DestEncoding *Dest, int32 DestSize, const SourceEncoding *Src)
Converts the null-terminated Src string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range, including a null terminator.
template<typename SourceEncoding, typename DestEncoding>
static FORCEINLINE DestEncoding * Convert (DestEncoding *Dest, int32 DestSize, const SourceEncoding *Src, int32 SrcSize)
Converts the [Src, Src+SrcSize) string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range.
template<typename DestEncoding, typename SourceEncoding>
static int32 ConvertedLength (const SourceEncoding *Src)
Returns the required buffer length for the null-terminated Src string when converted to the DestChar encoding.
template<typename DestEncoding, typename SourceEncoding>
static int32 ConvertedLength (const SourceEncoding *Src, int32 SrcSize)
Returns the required buffer length for the [Src, Src+SrcSize) string when converted to the DestChar encoding.
static const ANSICHAR * GetEncodingName ()
template<typename Encoding>
static const TCHAR * GetEncodingTypeName ()
Returns the string representing the name of the given encoding type.
static int32 Strncmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
Static Public Member Functions inherited from FGenericPlatformStricmp
static int32 Stricmp (const ANSICHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const WIDECHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const WIDECHAR *String2)
static int32 Strnicmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
Static Public Attributes
static constexpr bool IsUnicodeEncoded = true
True if the encoding type of the string is some form of unicode.
Static Private Member Functions
static void * Memcpy (void *Dest, const void *Src, SIZE_T Count)
Forwarding function because we can't call FMemory::Memcpy directly due to #include ordering issues.
Detailed Description
Generic string implementation for most platforms.
Definition at line 60 of file GenericPlatformString.h.
Member Function Documentation
CanConvertCodepoint()
template<typename DestEncoding, typename SourceEncoding> constexpr bool FGenericPlatformString::CanConvertCodepoint (SourceEncoding Codepoint) inline static constexpr
Tests whether a particular codepoint can be converted to the destination encoding.
Parameters
Ch The character to test.
Returns
True if Ch can be encoded as a DestEncoding.
Definition at line 69 of file GenericPlatformString.h.
References TIsCharEncodingSimplyConvertibleTo_V, TIsFixedWidthCharEncoding_V, and TIsCharType< T >::Value.
Referenced by Convert(), and Convert().
Convert() [1/2]
template<typename SourceEncoding, typename DestEncoding> FORCEINLINE DestEncoding * FGenericPlatformString::Convert (DestEncoding * Dest, int32 DestSize, const SourceEncoding * Src) inline static
Converts the null-terminated Src string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range, including a null terminator.
If the Dest range is not big enough to hold the converted output, NULL is returned. In this case, nothing should be assumed about the contents of Dest.
Parameters
Dest The start of the destination buffer.
DestSize The size of the destination buffer.
Src The start of the string to convert.
Returns
A pointer to one past the last-written element.
Definition at line 138 of file GenericPlatformString.h.
References CanConvertCodepoint(), UE::Core::Private::Convert(), FORCEINLINE, TIsCharEncodingSimplyConvertibleTo_V, TIsFixedWidthCharEncoding_V, and UNICODE_BOGUS_CHAR_CODEPOINT.
Referenced by FMemoryImageString::FMemoryImageString(), TStringBuilderBase< TCHAR >::Append(), TStringBuilderBase< TCHAR >::AppendChar(), TStringPassthru< ToType, FromType, DefaultConversionSize >::Apply(), CharCast(), FUTF8ToTCHAR_Convert::Convert(), FUTF8ToTCHAR_Convert::Convert(), TStringConvert< From, To >::Convert(), UE::Core::Private::FTCHARToUTF8_Convert::Convert(), FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), and StringToArray().
Convert() [2/2]
template<typename SourceEncoding, typename DestEncoding> FORCEINLINE DestEncoding * FGenericPlatformString::Convert (DestEncoding * Dest, int32 DestSize, const SourceEncoding * Src, int32 SrcSize) inline static
Converts the [Src, Src+SrcSize) string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range.
The Src range should contain a null terminator if a null terminator is required in the output. If the Dest range is not big enough to hold the converted output, NULL is returned. In this case, nothing should be assumed about the contents of Dest.
Parameters
Dest The start of the destination buffer.
DestSize The size of the destination buffer.
Src The start of the string to convert.
SrcSize The number of Src elements to convert.
Returns
A pointer to one past the last-written element.
Definition at line 232 of file GenericPlatformString.h.
References CanConvertCodepoint(), UE::Core::Private::Convert(), FORCEINLINE, Memcpy(), TIsCharEncodingCompatibleWith_V, TIsCharEncodingSimplyConvertibleTo_V, TIsFixedWidthCharEncoding_V, TSequenceHistory< HistorySize >::Size, and UNICODE_BOGUS_CHAR_CODEPOINT.
ConvertedLength() [1/2]
template<typename DestEncoding, typename SourceEncoding> int32 FGenericPlatformString::ConvertedLength (const SourceEncoding * Src) inline static
Returns the required buffer length for the null-terminated Src string when converted to the DestChar encoding.
The returned length includes the space for the null terminator (equivalent to strlen+1).
Parameters
Src The start of the string to convert.
Returns
The number of DestChar elements that Src will be converted into.
Definition at line 293 of file GenericPlatformString.h.
References UE::Core::Private::GetConvertedLength(), TIsCharEncodingSimplyConvertibleTo_V, and TIsFixedWidthCharEncoding_V.
Referenced by FMemoryImageString::FMemoryImageString(), TStringBuilderBase< TCHAR >::Append(), TStringBuilderBase< TCHAR >::AppendChar(), TStringPassthru< ToType, FromType, DefaultConversionSize >::Apply(), FUTF8ToTCHAR_Convert::ConvertedLength(), FUTF8ToTCHAR_Convert::ConvertedLength(), TStringConvert< From, To >::ConvertedLength(), UE::Core::Private::FTCHARToUTF8_Convert::ConvertedLength(), FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), and StringToArray().
ConvertedLength() [2/2]
template<typename DestEncoding, typename SourceEncoding> int32 FGenericPlatformString::ConvertedLength (const SourceEncoding * Src, int32 SrcSize) inline static
Returns the required buffer length for the [Src, Src+SrcSize) string when converted to the DestChar encoding.
The Src range should contain a null terminator if a null terminator is required in the output.
Parameters
Src The start of the string to convert.
SrcSize The number of Src elements to convert.
Returns
The number of DestChar elements that Src will be converted into.
Definition at line 320 of file GenericPlatformString.h.
References UE::Core::Private::GetConvertedLength(), TIsCharEncodingSimplyConvertibleTo_V, and TIsFixedWidthCharEncoding_V.
GetEncodingName()
const ANSICHAR * FGenericPlatformString::GetEncodingName () inline static
Definition at line 113 of file GenericPlatformString.h.
GetEncodingTypeName()
template<typename Encoding> const TCHAR * FGenericPlatformString::GetEncodingTypeName () static
Returns the string representing the name of the given encoding type.
Returns
The name of the CharType as a TCHAR string.
Memcpy()
void * FGenericPlatformString::Memcpy (void * Dest, const void * Src, SIZE_T Count) static private
Forwarding function because we can't call FMemory::Memcpy directly due to #include ordering issues.
Parameters
Dest The destination buffer.
Src The source buffer.
Count The number of bytes to copy.
Returns
Dest
References Count.
Referenced by Convert().
Strncmp() [1/9]
int32 FGenericPlatformString::Strncmp (const ANSICHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [2/9]
int32 FGenericPlatformString::Strncmp (const ANSICHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [3/9]
int32 FGenericPlatformString::Strncmp (const ANSICHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [4/9]
int32 FGenericPlatformString::Strncmp (const UTF8CHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [5/9]
int32 FGenericPlatformString::Strncmp (const UTF8CHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [6/9]
int32 FGenericPlatformString::Strncmp (const UTF8CHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [7/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [8/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
References Count.
Strncmp() [9/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
References Count.
Field Documentation
IsUnicodeEncoded
bool FGenericPlatformString::IsUnicodeEncoded = true static constexpr
True if the encoding type of the string is some form of unicode.
Definition at line 125 of file GenericPlatformString.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformString.h