Unreal Engine 5.6 C++ API: UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData Struct Reference
UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData Struct Reference
#include "QuadricError.h"
Public Member Functions
FPlaneData ()
FPlaneData (const FPlaneData &other)
FPlaneData (const TVector< RealType > &Normal, const TVector< RealType > &Point)
FPlaneData (RealType w, const FPlaneData &other)
void Add (const FPlaneData &other)
void Add (RealType w, const FPlaneData &other)
Add scalar multiple of a FPlaneData to this FPlaneData.
FPlaneData & operator= (const FPlaneData &other)
Data Fields
RealType Dist
TVector< RealType > N
Detailed Description
template<typename RealType>
struct UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData
Definition at line 264 of file QuadricError.h.
Constructor & Destructor Documentation
FPlaneData() [1/4]
template<typename RealType> UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::FPlaneData (const TVector< RealType > & Normal, const TVector< RealType > & Point) inline
Definition at line 266 of file QuadricError.h.
References Dist, N, UE::Geometry::Normal, and Point.
Referenced by FPlaneData(), FPlaneData(), Add(), Add(), and operator=().
FPlaneData() [2/4]
template<typename RealType> UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::FPlaneData (RealType w, const FPlaneData & other) inline
Definition at line 272 of file QuadricError.h.
References FPlaneData(), Dist, and N.
FPlaneData() [3/4]
template<typename RealType> UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::FPlaneData (const FPlaneData & other) inline
Definition at line 278 of file QuadricError.h.
References FPlaneData(), Dist, and N.
FPlaneData() [4/4]
template<typename RealType> UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::FPlaneData () inline
Definition at line 284 of file QuadricError.h.
References Dist, N, and UE::Math::TVector< T >::Zero().
Member Function Documentation
Add() [1/2]
template<typename RealType> void UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::Add (const FPlaneData & other) inline
Definition at line 290 of file QuadricError.h.
References FPlaneData(), Dist, and N.
Add() [2/2]
template<typename RealType> void UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::Add (RealType w, const FPlaneData & other) inline
Add scalar multiple of a FPlaneData to this FPlaneData.
Definition at line 299 of file QuadricError.h.
References FPlaneData(), Dist, and N.
operator=()
template<typename RealType> FPlaneData & UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::operator= (const FPlaneData & other) inline
Definition at line 305 of file QuadricError.h.
References FPlaneData(), Dist, and N.
Field Documentation
Dist
template<typename RealType> RealType UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::Dist
Definition at line 314 of file QuadricError.h.
Referenced by FPlaneData(), FPlaneData(), FPlaneData(), FPlaneData(), Add(), Add(), and operator=().
N
template<typename RealType> TVector<RealType> UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::N
Definition at line 313 of file QuadricError.h.
Referenced by FPlaneData(), FPlaneData(), FPlaneData(), FPlaneData(), Add(), Add(), and operator=().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/QuadricError.h