Unreal Engine 5.6 C++ API: ImmediatePhysics_Chaos::FJointHandle Struct Reference
ImmediatePhysics_Chaos::FJointHandle Struct Reference
handle associated with a physics joint.
#include "ImmediatePhysicsJointHandle_Chaos.h"
Public Types
using FChaosConstraintContainer = Chaos::FPBDJointConstraints
using FChaosConstraintHandle = typename Chaos::FPBDJointConstraintHandle
Public Member Functions
FJointHandle (FChaosConstraintContainer *InConstraints, const FJointSetup &JointSetup)
~FJointHandle ()
const Chaos::TVec2< FActorHandle * > & GetActorHandles ()
const Chaos::TVec2< const FActorHandle * > & GetActorHandles () const
FChaosConstraintHandle * GetConstraint ()
const FChaosConstraintHandle * GetConstraint () const
void SetSoftLinearSettings (bool bLinearSoft, FReal LinearStiffness, FReal LinearDamping)
UE_DEPRECATED (5.6, "Use constructor which takes FJointSetup") 1 FJointHandle(FChaosConstraintContainer *InConstraints
UE_DEPRECATED (5.6, "Use constructor which takes FJointSetup") 1 FJointHandle(FChaosConstraintContainer *InConstraints
Data Fields
FConstraintInstance * ConstraintInstance
const Chaos::FPBDJointSettings & ConstraintSettings
FConstraintInstance FActorHandle * InActor1
const Chaos::FPBDJointSettings FActorHandle * InActor1
FConstraintInstance FActorHandle FActorHandle * InActor2
const Chaos::FPBDJointSettings FActorHandle FActorHandle * InActor2
Private Member Functions
void CreateJoint (FChaosConstraintContainer *InConstraints, const Chaos::FPBDJointSettings &ConstraintSettings, FActorHandle *const Actor1, FActorHandle *const Actor2)
void SetActorInertiaConditioningDirty ()
Private Attributes
Chaos::TVec2< FActorHandle * > ActorHandles
FChaosConstraintHandle * ConstraintHandle
FChaosConstraintContainer * Constraints
Detailed Description
handle associated with a physics joint.
This is the proper way to read/write to the physics simulation
Definition at line 38 of file ImmediatePhysicsJointHandle_Chaos.h.
Member Typedef Documentation
FChaosConstraintContainer
using ImmediatePhysics_Chaos::FJointHandle::FChaosConstraintContainer = Chaos::FPBDJointConstraints
Definition at line 41 of file ImmediatePhysicsJointHandle_Chaos.h.
FChaosConstraintHandle
using ImmediatePhysics_Chaos::FJointHandle::FChaosConstraintHandle = typename Chaos::FPBDJointConstraintHandle
Definition at line 42 of file ImmediatePhysicsJointHandle_Chaos.h.
Constructor & Destructor Documentation
FJointHandle()
ImmediatePhysics_Chaos::FJointHandle::FJointHandle (FChaosConstraintContainer * InConstraints, const FJointSetup & JointSetup)
References FJointHandle().
Referenced by FJointHandle(), and ~FJointHandle().
~FJointHandle()
ImmediatePhysics_Chaos::FJointHandle::~FJointHandle ()
References FJointHandle().
Member Function Documentation
CreateJoint()
void ImmediatePhysics_Chaos::FJointHandle::CreateJoint (FChaosConstraintContainer * InConstraints, const Chaos::FPBDJointSettings & ConstraintSettings, FActorHandle *const Actor1, FActorHandle *const Actor2) private
References ConstraintSettings, and CreateJoint().
Referenced by CreateJoint().
GetActorHandles() [1/2]
const Chaos::TVec2< FActorHandle * > & ImmediatePhysics_Chaos::FJointHandle::GetActorHandles ()
References GetActorHandles().
Referenced by GetActorHandles(), and GetActorHandles().
GetActorHandles() [2/2]
const Chaos::TVec2< const FActorHandle * > & ImmediatePhysics_Chaos::FJointHandle::GetActorHandles () const
References GetActorHandles().
GetConstraint() [1/2]
FChaosConstraintHandle * ImmediatePhysics_Chaos::FJointHandle::GetConstraint ()
References GetConstraint().
Referenced by GetConstraint(), and GetConstraint().
GetConstraint() [2/2]
const FChaosConstraintHandle * ImmediatePhysics_Chaos::FJointHandle::GetConstraint () const
References GetConstraint().
SetActorInertiaConditioningDirty()
void ImmediatePhysics_Chaos::FJointHandle::SetActorInertiaConditioningDirty () private
References SetActorInertiaConditioningDirty().
Referenced by SetActorInertiaConditioningDirty().
SetSoftLinearSettings()
void ImmediatePhysics_Chaos::FJointHandle::SetSoftLinearSettings (bool bLinearSoft, FReal LinearStiffness, FReal LinearDamping)
References SetSoftLinearSettings().
Referenced by SetSoftLinearSettings().
UE_DEPRECATED() [1/2]
ImmediatePhysics_Chaos::FJointHandle::UE_DEPRECATED (5. 6, "Use constructor which takes FJointSetup")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
ImmediatePhysics_Chaos::FJointHandle::UE_DEPRECATED (5. 6, "Use constructor which takes FJointSetup")
References UE_DEPRECATED().
Field Documentation
ActorHandles
Chaos::TVec2<FActorHandle*> ImmediatePhysics_Chaos::FJointHandle::ActorHandles private
Definition at line 67 of file ImmediatePhysicsJointHandle_Chaos.h.
ConstraintHandle
FChaosConstraintHandle* ImmediatePhysics_Chaos::FJointHandle::ConstraintHandle private
Definition at line 69 of file ImmediatePhysicsJointHandle_Chaos.h.
ConstraintInstance
FConstraintInstance* ImmediatePhysics_Chaos::FJointHandle::ConstraintInstance
Definition at line 47 of file ImmediatePhysicsJointHandle_Chaos.h.
Constraints
FChaosConstraintContainer* ImmediatePhysics_Chaos::FJointHandle::Constraints private
Definition at line 68 of file ImmediatePhysicsJointHandle_Chaos.h.
ConstraintSettings
const Chaos::FPBDJointSettings& ImmediatePhysics_Chaos::FJointHandle::ConstraintSettings
Definition at line 50 of file ImmediatePhysicsJointHandle_Chaos.h.
Referenced by CreateJoint().
InActor1 [1/2]
FConstraintInstance FActorHandle* ImmediatePhysics_Chaos::FJointHandle::InActor1
Definition at line 47 of file ImmediatePhysicsJointHandle_Chaos.h.
InActor1 [2/2]
const Chaos::FPBDJointSettings FActorHandle* ImmediatePhysics_Chaos::FJointHandle::InActor1
Definition at line 50 of file ImmediatePhysicsJointHandle_Chaos.h.
InActor2 [1/2]
FConstraintInstance FActorHandle FActorHandle* ImmediatePhysics_Chaos::FJointHandle::InActor2
Definition at line 47 of file ImmediatePhysicsJointHandle_Chaos.h.
InActor2 [2/2]
const Chaos::FPBDJointSettings FActorHandle FActorHandle* ImmediatePhysics_Chaos::FJointHandle::InActor2
Definition at line 50 of file ImmediatePhysicsJointHandle_Chaos.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Physics/ImmediatePhysics/ImmediatePhysicsChaos/ImmediatePhysicsJointHandle_Chaos.h