Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicSubmesh3 Struct Reference
UE::Geometry::FDynamicSubmesh3 Struct Reference
#include "DynamicSubmesh3.h"
Public Member Functions
FDynamicSubmesh3 ()
Default constructor.
FDynamicSubmesh3 (const FDynamicMesh3 *BaseMesh)
Base mesh-only constructor; does not build submesh.
FDynamicSubmesh3 (const FDynamicMesh3 *BaseMesh, const TArray< int > &Triangles, int WantComponents=(int) EMeshComponents::All, bool bAttributes=true)
Constructor sets the base mesh and computes the submesh.
void Compute (const TArrayView< const int > &SubTriangles, int WantComponents=(int) EMeshComponents::All, bool bAttributes=true)
Computes the Submesh object, index mappings corresponding sub to base mesh, and boundary between sub and base mesh.
void Compute (FDynamicMesh3 *Base, const TArrayView< const int > &Triangles, int WantComponents=(int) EMeshComponents::All, bool bAttributes=true)
Computes submesh object, setting a new BaseMesh first.
const TSet< int > GetBaseBorderEdges () const
const TSet< int > GetBaseBorderVertices () const
const TSet< int > GetBaseBoundaryEdges () const
const FDynamicMesh3 * GetBaseMesh () const
const accessor for base mesh
FDynamicMesh3 & GetSubmesh ()
accessor for submesh
const FDynamicMesh3 & GetSubmesh () const
const accessor for submesh
bool InBaseBorderEdges (int BaseEID) const
bool InBaseBorderVertices (int BaseVID) const
bool InBaseBoundaryEdges (int BaseEID) const
int MapColorToBaseMesh (int SubCID) const
int MapColorToSubmesh (int BaseCID) const
void MapEdgesToSubmesh (TArrayView< int > &Edges) const
int MapEdgeToBaseMesh (int SubEID) const
int MapEdgeToSubmesh (int BaseEID) const
void MapGroupsToSubmesh (TArrayView< int32 > GroupIDs) const
int MapGroupToBaseMesh (int SubGID) const
int MapGroupToSubmesh (int BaseGID) const
int MapNormalToBaseMesh (int NormalLayer, int SubNID) const
int MapNormalToSubmesh (int NormalLayer, int BaseNID) const
void MapTrianglesToSubmesh (TArrayView< int > &Triangles) const
int MapTriangleToBaseMesh (int SubTID) const
int MapTriangleToSubmesh (int BaseTID) const
int MapUVToBaseMesh (int UVLayer, int SubUVID) const
int MapUVToSubmesh (int UVLayer, int BaseUVID) const
int MapVertexToBaseMesh (int SubVID) const
int MapVertexToSubmesh (int BaseVID) const
FIndex2i MapVerticesToBaseMesh (FIndex2i VIDs) const
FIndex2i MapVerticesToSubmesh (FIndex2i VIDs) const
void MapVerticesToSubmesh (TArrayView< int > &Vertices) const
Data Fields
bool bComputeTriMaps = true
Whether to compute triangle maps (adds additional cost).
Protected Member Functions
void ComputeBoundaryInfo (const TArrayView< const int > &SubTriangles)
Compute boundary vertices and edges between the SubTriangles and the rest of the mesh Called by Compute after the Submesh is computed.
Protected Attributes
TSet< int > BaseBorderE
TSet< int > BaseBorderV
TSet< int > BaseBoundaryE
const FDynamicMesh3 * BaseMesh
FMeshIndexMappings Mappings
FDynamicMesh3 Submesh
Detailed Description
Definition at line 16 of file DynamicSubmesh3.h.
Constructor & Destructor Documentation
FDynamicSubmesh3() [1/3]
UE::Geometry::FDynamicSubmesh3::FDynamicSubmesh3 () inline
Default constructor.
Definition at line 38 of file DynamicSubmesh3.h.
References BaseMesh.
FDynamicSubmesh3() [2/3]
UE::Geometry::FDynamicSubmesh3::FDynamicSubmesh3 (const FDynamicMesh3 * BaseMesh) inline
Base mesh-only constructor; does not build submesh.
Definition at line 41 of file DynamicSubmesh3.h.
References BaseMesh.
FDynamicSubmesh3() [3/3]
UE::Geometry::FDynamicSubmesh3::FDynamicSubmesh3 (const FDynamicMesh3 * BaseMesh, const TArray< int > & Triangles, int WantComponents = (int)EMeshComponents::All, bool bAttributes = true) inline
Constructor sets the base mesh and computes the submesh.
Definition at line 46 of file DynamicSubmesh3.h.
References UE::Geometry::All, BaseMesh, and Compute.
Member Function Documentation
Compute() [1/2]
void UE::Geometry::FDynamicSubmesh3::Compute (const TArrayView< const int > & SubTriangles, int WantComponents = (int)EMeshComponents::All, bool bAttributes = true) inline
Computes the Submesh object, index mappings corresponding sub to base mesh, and boundary between sub and base mesh.
Parameters
SubTriangles ArrayView of triangle IDs to include in the submesh
WantComponents Bit flag of desired mesh components; will only enable if flag is set AND the components are enabled in the BaseMesh
bAttributes Flag indicating if attributes are needed for submesh; will only enable attributes if flag is set AND attributes are enabled in the BaseMesh
Definition at line 247 of file DynamicSubmesh3.h.
References UE::Geometry::All, BaseMesh, bComputeTriMaps, check, ComputeBoundaryInfo(), Mappings, TArrayView< InElementType, InSizeType >::Num(), and Submesh.
Compute() [2/2]
void UE::Geometry::FDynamicSubmesh3::Compute (FDynamicMesh3 * Base, const TArrayView< const int > & Triangles, int WantComponents = (int)EMeshComponents::All, bool bAttributes = true) inline
Computes submesh object, setting a new BaseMesh first.
Definition at line 269 of file DynamicSubmesh3.h.
References UE::Geometry::All, BaseMesh, and Compute.
ComputeBoundaryInfo()
void UE::Geometry::FDynamicSubmesh3::ComputeBoundaryInfo (const TArrayView< const int > & SubTriangles) inline protected
Compute boundary vertices and edges between the SubTriangles and the rest of the mesh Called by Compute after the Submesh is computed.
Definition at line 281 of file DynamicSubmesh3.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndexFlagSet::Add(), UE::Geometry::FIndex2i::B, BaseBorderE, BaseBorderV, BaseBoundaryE, BaseMesh, check, UE::Geometry::FDynamicMesh3::InvalidID, and TArrayView< InElementType, InSizeType >::Num().
Referenced by Compute().
GetBaseBorderEdges()
const TSet< int > UE::Geometry::FDynamicSubmesh3::GetBaseBorderEdges () const inline
Returns
set of internal border edge indices on base mesh. Does not include mesh boundary edges.
Definition at line 70 of file DynamicSubmesh3.h.
References BaseBorderE.
GetBaseBorderVertices()
const TSet< int > UE::Geometry::FDynamicSubmesh3::GetBaseBorderVertices () const inline
Returns
set of border vertex indices on base mesh (ie verts of BaseBorderE - does not include mesh boundary vertices)
Definition at line 82 of file DynamicSubmesh3.h.
References BaseBorderV.
GetBaseBoundaryEdges()
const TSet< int > UE::Geometry::FDynamicSubmesh3::GetBaseBoundaryEdges () const inline
Returns
set of mesh-boundary edges on base mesh that are in submesh
Definition at line 76 of file DynamicSubmesh3.h.
References BaseBoundaryE.
GetBaseMesh()
const FDynamicMesh3 * UE::Geometry::FDynamicSubmesh3::GetBaseMesh () const inline
const accessor for base mesh
Definition at line 52 of file DynamicSubmesh3.h.
References BaseMesh.
GetSubmesh() [1/2]
FDynamicMesh3 & UE::Geometry::FDynamicSubmesh3::GetSubmesh () inline
accessor for submesh
Definition at line 58 of file DynamicSubmesh3.h.
References Submesh.
GetSubmesh() [2/2]
const FDynamicMesh3 & UE::Geometry::FDynamicSubmesh3::GetSubmesh () const inline
const accessor for submesh
Definition at line 64 of file DynamicSubmesh3.h.
References Submesh.
InBaseBorderEdges()
bool UE::Geometry::FDynamicSubmesh3::InBaseBorderEdges (int BaseEID) const inline
Returns
true if edge ID is in base border edge ID set
Definition at line 88 of file DynamicSubmesh3.h.
References BaseBorderE.
InBaseBorderVertices()
bool UE::Geometry::FDynamicSubmesh3::InBaseBorderVertices (int BaseVID) const inline
Returns
true if vertex ID is in base border vertex ID set
Definition at line 100 of file DynamicSubmesh3.h.
References BaseBorderV.
InBaseBoundaryEdges()
bool UE::Geometry::FDynamicSubmesh3::InBaseBoundaryEdges (int BaseEID) const inline
Returns
true if edge ID is in base boundary edge ID set
Definition at line 94 of file DynamicSubmesh3.h.
References BaseBoundaryE.
MapColorToBaseMesh()
int UE::Geometry::FDynamicSubmesh3::MapColorToBaseMesh (int SubCID) const inline
Returns
Vertex Color ID in the base mesh, mapped from the submesh
Definition at line 236 of file DynamicSubmesh3.h.
References Mappings.
MapColorToSubmesh()
int UE::Geometry::FDynamicSubmesh3::MapColorToSubmesh (int BaseCID) const inline
Returns
Vertex Color ID in the submesh, mapped from the base mesh
Definition at line 230 of file DynamicSubmesh3.h.
References Mappings.
MapEdgesToSubmesh()
void UE::Geometry::FDynamicSubmesh3::MapEdgesToSubmesh (TArrayView< int > & Edges) const inline
Parameters
Edges Array of edge IDs in base mesh that will all be changed to the corresponding IDs in the submesh
Definition at line 152 of file DynamicSubmesh3.h.
References MapEdgeToSubmesh(), and TArrayView< InElementType, InSizeType >::Num().
MapEdgeToBaseMesh()
int UE::Geometry::FDynamicSubmesh3::MapEdgeToBaseMesh (int SubEID) const inline
Returns
Edge ID in base mesh, mapped from submesh
Definition at line 144 of file DynamicSubmesh3.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, BaseMesh, check, MapVerticesToBaseMesh(), and Submesh.
MapEdgeToSubmesh()
int UE::Geometry::FDynamicSubmesh3::MapEdgeToSubmesh (int BaseEID) const inline
Returns
Edge ID in submesh, mapped from base mesh
Definition at line 136 of file DynamicSubmesh3.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, BaseMesh, check, MapVerticesToSubmesh(), and Submesh.
Referenced by MapEdgesToSubmesh().
MapGroupsToSubmesh()
void UE::Geometry::FDynamicSubmesh3::MapGroupsToSubmesh (TArrayView< int32 > GroupIDs) const inline
Parameters
GroupIDs Array of group IDs in the base mesh that will all be changed to the corresponding IDs in the submesh
Definition at line 196 of file DynamicSubmesh3.h.
References bComputeTriMaps, checkSlow, MapGroupToSubmesh(), and TArrayView< InElementType, InSizeType >::Num().
MapGroupToBaseMesh()
int UE::Geometry::FDynamicSubmesh3::MapGroupToBaseMesh (int SubGID) const inline
Returns
Group ID in the base mesh, mapped from submesh
Definition at line 190 of file DynamicSubmesh3.h.
References bComputeTriMaps, checkSlow, and Mappings.
MapGroupToSubmesh()
int UE::Geometry::FDynamicSubmesh3::MapGroupToSubmesh (int BaseGID) const inline
Returns
Group ID in the submesh, mapped from base mesh
Definition at line 184 of file DynamicSubmesh3.h.
References bComputeTriMaps, checkSlow, and Mappings.
Referenced by MapGroupsToSubmesh().
MapNormalToBaseMesh()
int UE::Geometry::FDynamicSubmesh3::MapNormalToBaseMesh (int NormalLayer, int SubNID) const inline
Returns
Normal ID in the base mesh, mapped from the submesh
Definition at line 212 of file DynamicSubmesh3.h.
References Mappings.
MapNormalToSubmesh()
int UE::Geometry::FDynamicSubmesh3::MapNormalToSubmesh (int NormalLayer, int BaseNID) const inline
Returns
Normal ID in the submesh, mapped from the base mesh
Definition at line 206 of file DynamicSubmesh3.h.
References Mappings.
MapTrianglesToSubmesh()
void UE::Geometry::FDynamicSubmesh3::MapTrianglesToSubmesh (TArrayView< int > & Triangles) const inline
Parameters
Triangles Array of triangle IDs in the base mesh that will all be changed to the corresponding IDs in the submesh
Definition at line 174 of file DynamicSubmesh3.h.
References bComputeTriMaps, checkSlow, MapTriangleToSubmesh(), and TArrayView< InElementType, InSizeType >::Num().
MapTriangleToBaseMesh()
int UE::Geometry::FDynamicSubmesh3::MapTriangleToBaseMesh (int SubTID) const inline
Returns
Triangle ID in the base mesh, mapped from submesh
Definition at line 168 of file DynamicSubmesh3.h.
References bComputeTriMaps, checkSlow, and Mappings.
MapTriangleToSubmesh()
int UE::Geometry::FDynamicSubmesh3::MapTriangleToSubmesh (int BaseTID) const inline
Returns
Triangle ID in the submesh, mapped from base mesh
Definition at line 162 of file DynamicSubmesh3.h.
References bComputeTriMaps, checkSlow, and Mappings.
Referenced by MapTrianglesToSubmesh().
MapUVToBaseMesh()
int UE::Geometry::FDynamicSubmesh3::MapUVToBaseMesh (int UVLayer, int SubUVID) const inline
Returns
UV ID in the base mesh, mapped from the submesh
Definition at line 224 of file DynamicSubmesh3.h.
References Mappings.
MapUVToSubmesh()
int UE::Geometry::FDynamicSubmesh3::MapUVToSubmesh (int UVLayer, int BaseUVID) const inline
Returns
UV ID in the submesh, mapped from the base mesh
Definition at line 218 of file DynamicSubmesh3.h.
References Mappings.
MapVertexToBaseMesh()
int UE::Geometry::FDynamicSubmesh3::MapVertexToBaseMesh (int SubVID) const inline
Returns
Vertex ID in base mesh, mapped from submesh
Definition at line 111 of file DynamicSubmesh3.h.
References Mappings.
Referenced by MapVerticesToBaseMesh().
MapVertexToSubmesh()
int UE::Geometry::FDynamicSubmesh3::MapVertexToSubmesh (int BaseVID) const inline
Returns
Vertex ID in submesh, mapped from base mesh
Definition at line 106 of file DynamicSubmesh3.h.
References Mappings.
Referenced by MapVerticesToSubmesh(), and MapVerticesToSubmesh().
MapVerticesToBaseMesh()
FIndex2i UE::Geometry::FDynamicSubmesh3::MapVerticesToBaseMesh (FIndex2i VIDs) const inline
Returns
Pair of vertex IDs in base mesh, mapped from submesh
Definition at line 122 of file DynamicSubmesh3.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, and MapVertexToBaseMesh().
Referenced by MapEdgeToBaseMesh().
MapVerticesToSubmesh() [1/2]
FIndex2i UE::Geometry::FDynamicSubmesh3::MapVerticesToSubmesh (FIndex2i VIDs) const inline
Returns
Pair of vertex IDs in submesh, mapped from base mesh
Definition at line 117 of file DynamicSubmesh3.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, and MapVertexToSubmesh().
Referenced by MapEdgeToSubmesh().
MapVerticesToSubmesh() [2/2]
void UE::Geometry::FDynamicSubmesh3::MapVerticesToSubmesh (TArrayView< int > & Vertices) const inline
Parameters
Vertices Array of vertex IDs in base mesh that will all be changed to the corresponding IDs in the submesh
Definition at line 127 of file DynamicSubmesh3.h.
References MapVertexToSubmesh(), and UE::Geometry::Vertices.
Field Documentation
BaseBorderE
TSet<int> UE::Geometry::FDynamicSubmesh3::BaseBorderE protected
Definition at line 26 of file DynamicSubmesh3.h.
Referenced by ComputeBoundaryInfo(), GetBaseBorderEdges(), and InBaseBorderEdges().
BaseBorderV
TSet<int> UE::Geometry::FDynamicSubmesh3::BaseBorderV protected
Definition at line 28 of file DynamicSubmesh3.h.
Referenced by ComputeBoundaryInfo(), GetBaseBorderVertices(), and InBaseBorderVertices().
BaseBoundaryE
TSet<int> UE::Geometry::FDynamicSubmesh3::BaseBoundaryE protected
Definition at line 27 of file DynamicSubmesh3.h.
Referenced by ComputeBoundaryInfo(), GetBaseBoundaryEdges(), and InBaseBoundaryEdges().
BaseMesh
const FDynamicMesh3* UE::Geometry::FDynamicSubmesh3::BaseMesh protected
Definition at line 19 of file DynamicSubmesh3.h.
Referenced by FDynamicSubmesh3(), FDynamicSubmesh3(), FDynamicSubmesh3(), Compute(), Compute(), ComputeBoundaryInfo(), GetBaseMesh(), MapEdgeToBaseMesh(), and MapEdgeToSubmesh().
bComputeTriMaps
bool UE::Geometry::FDynamicSubmesh3::bComputeTriMaps = true
Whether to compute triangle maps (adds additional cost).
True by default.
Definition at line 34 of file DynamicSubmesh3.h.
Referenced by Compute(), MapGroupsToSubmesh(), MapGroupToBaseMesh(), MapGroupToSubmesh(), MapTrianglesToSubmesh(), MapTriangleToBaseMesh(), and MapTriangleToSubmesh().
Mappings
FMeshIndexMappings UE::Geometry::FDynamicSubmesh3::Mappings protected
Definition at line 24 of file DynamicSubmesh3.h.
Referenced by Compute(), MapColorToBaseMesh(), MapColorToSubmesh(), MapGroupToBaseMesh(), MapGroupToSubmesh(), MapNormalToBaseMesh(), MapNormalToSubmesh(), MapTriangleToBaseMesh(), MapTriangleToSubmesh(), MapUVToBaseMesh(), MapUVToSubmesh(), MapVertexToBaseMesh(), and MapVertexToSubmesh().
Submesh
FDynamicMesh3 UE::Geometry::FDynamicSubmesh3::Submesh protected
Definition at line 20 of file DynamicSubmesh3.h.
Referenced by Compute(), GetSubmesh(), GetSubmesh(), MapEdgeToBaseMesh(), and MapEdgeToSubmesh().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/DynamicSubmesh3.h