var structUE_1_1MeshDescription_1_1FStaticMeshBuildSettingChange =
[
    [ "AutoGeneratedNormals", "structUE_1_1MeshDescription_1_1FStaticMeshBuildSettingChange.html#a956757baad2b3c8ea7e76988e4e067e1", null ],
    [ "AutoGeneratedTangents", "structUE_1_1MeshDescription_1_1FStaticMeshBuildSettingChange.html#a5c2135bb870684f0023bd83c12a62d92", null ],
    [ "UseMikkTSpaceTangents", "structUE_1_1MeshDescription_1_1FStaticMeshBuildSettingChange.html#ac0991241fffbc9d3fe89775618d5c421", null ]
];