Unreal Engine 5.6 C++ API: FVariablePrecisionNumericInterface Struct Reference
FVariablePrecisionNumericInterface Struct Reference
#include "SAudioTextBox.h"
Public Member Functions
FVariablePrecisionNumericInterface ()
FVariablePrecisionNumericInterface ()
virtual FString ToString (const float &Value) const override
Convert the type to/from a string.
virtual FString ToString (const float &Value) const override
Convert the type to/from a string.
Public Member Functions inherited from TDefaultNumericTypeInterface< float >
virtual TOptional< float > FromString (const FString &InString, const float &InExistingValue) override
virtual bool GetIndicateNearlyInteger () const override
Get if we should indicate nearly integer values.
virtual int32 GetMaxFractionalDigits () const override
virtual int32 GetMinFractionalDigits () const override
Gets the minimum and maximum fractional digits.
virtual bool IsCharacterValid (TCHAR InChar) const override
Check whether the typed character is valid.
virtual void SetIndicateNearlyInteger (const TAttribute< TOptional< bool > > &NewValue) override
Sets if we should indicate that a value is being rounded to an integer via '...' (Ex: 0.0 shown, real value 1e-18).
virtual void SetMaxFractionalDigits (const TAttribute< TOptional< int32 > > &NewValue) override
virtual void SetMinFractionalDigits (const TAttribute< TOptional< int32 > > &NewValue) override
Sets the minimum and maximum fractional digits - A minimum greater than 0 will always have that many trailing zeros.
Public Member Functions inherited from INumericTypeInterface< float >
virtual ~INumericTypeInterface ()
virtual FOnSettingChanged * GetOnSettingChanged ()
Optional callback to broadcast when a setting in the type interface changes.
Additional Inherited Members
Data Fields inherited from TDefaultNumericTypeInterface< float >
bool bIndicateNearlyInteger
True implies indicate when a value is displayed as rounded via '...'.
int16 MaxFractionalDigits
The current maximum fractional digits.
int16 MinFractionalDigits
The current minimum fractional digits.
Static Public Attributes inherited from TDefaultNumericTypeInterface< float >
static const bool DefaultIndicateNearlyInteger
The default indicate nearly integer.
static const int16 DefaultMaxFractionalDigits
The default maximum fractional digits.
static const int16 DefaultMinFractionalDigits
The default minimum fractional digits.
Detailed Description
Definition at line 22 of file SAudioTextBox.h.
Constructor & Destructor Documentation
FVariablePrecisionNumericInterface() [1/2]
FVariablePrecisionNumericInterface::FVariablePrecisionNumericInterface () inline
Definition at line 24 of file SAudioTextBox.h.
FVariablePrecisionNumericInterface() [2/2]
FVariablePrecisionNumericInterface::FVariablePrecisionNumericInterface () inline
Definition at line 14 of file VariablePrecisionNumericInterface.h.
Member Function Documentation
ToString() [1/2]
virtual FString FVariablePrecisionNumericInterface::ToString (const float & Value) const inline override virtual
Convert the type to/from a string.
Reimplemented from TDefaultNumericTypeInterface< float >.
Definition at line 26 of file SAudioTextBox.h.
References FastDecimalFormat::NumberToString(), FNumberFormattingOptions::SetMaximumFractionalDigits(), FNumberFormattingOptions::SetMinimumFractionalDigits(), FNumberFormattingOptions::SetUseGrouping(), and Value.
ToString() [2/2]
virtual FString FVariablePrecisionNumericInterface::ToString (const float & Value) const inline override virtual
Convert the type to/from a string.
Reimplemented from TDefaultNumericTypeInterface< float >.
Definition at line 17 of file VariablePrecisionNumericInterface.h.
References FastDecimalFormat::NumberToString(), FNumberFormattingOptions::SetMaximumFractionalDigits(), FNumberFormattingOptions::SetMinimumFractionalDigits(), FNumberFormattingOptions::SetUseGrouping(), and Value.
The documentation for this struct was generated from the following files:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/AudioWidgets/Source/AudioWidgets/Public/SAudioTextBox.h
Editor/PropertyEditor/Public/VariablePrecisionNumericInterface.h