Unreal Engine 5.6 C++ API: UE::MovieScene::FMovieSceneEntityID Struct Reference
UE::MovieScene::FMovieSceneEntityID Struct Reference
#include "MovieSceneEntityIDs.h"
Public Member Functions
FMovieSceneEntityID ()
int32 AsIndex () const
bool IsValid () const
operator bool () const
Static Public Member Functions
static FMovieSceneEntityID FromIndex (int32 Index)
static FMovieSceneEntityID Invalid ()
static FMovieSceneEntityID Max ()
Private Member Functions
FMovieSceneEntityID (uint16 SpecifiedValue)
Private Attributes
uint16 Value
Static Private Attributes
static const uint16 INVALID = uint16(-1)
Friends
uint32 GetTypeHash (FMovieSceneEntityID In)
bool operator!= (FMovieSceneEntityID A, FMovieSceneEntityID B)
bool operator< (FMovieSceneEntityID A, FMovieSceneEntityID B)
bool operator== (FMovieSceneEntityID A, FMovieSceneEntityID B)
Detailed Description
Definition at line 301 of file MovieSceneEntityIDs.h.
Constructor & Destructor Documentation
FMovieSceneEntityID() [1/2]
UE::MovieScene::FMovieSceneEntityID::FMovieSceneEntityID () inline
Definition at line 303 of file MovieSceneEntityIDs.h.
References INVALID, and Value.
Referenced by FromIndex(), GetTypeHash, Invalid(), Max(), operator!=, operator<, and operator==.
FMovieSceneEntityID() [2/2]
UE::MovieScene::FMovieSceneEntityID::FMovieSceneEntityID (uint16 SpecifiedValue) inline explicit private
Definition at line 360 of file MovieSceneEntityIDs.h.
References Value.
Member Function Documentation
AsIndex()
int32 UE::MovieScene::FMovieSceneEntityID::AsIndex () const inline
Definition at line 348 of file MovieSceneEntityIDs.h.
References Value.
Referenced by UE::MovieScene::FEntityManager::IsAllocated(), UE::MovieScene::FEntityManager::ReadComponent(), and UE::MovieScene::FEntityManager::WriteComponent().
FromIndex()
FMovieSceneEntityID UE::MovieScene::FMovieSceneEntityID::FromIndex (int32 Index) inline static
Definition at line 337 of file MovieSceneEntityIDs.h.
References FMovieSceneEntityID(), and check.
Invalid()
FMovieSceneEntityID UE::MovieScene::FMovieSceneEntityID::Invalid () inline static
Definition at line 343 of file MovieSceneEntityIDs.h.
References FMovieSceneEntityID().
Referenced by UE::MovieScene::FPropertyRecomposerPropertyInfo::Invalid().
IsValid()
bool UE::MovieScene::FMovieSceneEntityID::IsValid () const inline
Definition at line 353 of file MovieSceneEntityIDs.h.
References INVALID, and Value.
Referenced by operator bool().
Max()
FMovieSceneEntityID UE::MovieScene::FMovieSceneEntityID::Max () inline static
Definition at line 332 of file MovieSceneEntityIDs.h.
References FMovieSceneEntityID().
operator bool()
UE::MovieScene::FMovieSceneEntityID::operator bool () const inline explicit
Definition at line 307 of file MovieSceneEntityIDs.h.
References IsValid().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FMovieSceneEntityID In) friend
Definition at line 327 of file MovieSceneEntityIDs.h.
References FMovieSceneEntityID(), and Value.
operator!=
bool operator!= (FMovieSceneEntityID A, FMovieSceneEntityID B) friend
Definition at line 317 of file MovieSceneEntityIDs.h.
References FMovieSceneEntityID(), A, and B.
operator<
bool operator< (FMovieSceneEntityID A, FMovieSceneEntityID B) friend
Definition at line 322 of file MovieSceneEntityIDs.h.
References FMovieSceneEntityID(), A, and B.
operator==
bool operator== (FMovieSceneEntityID A, FMovieSceneEntityID B) friend
Definition at line 312 of file MovieSceneEntityIDs.h.
References FMovieSceneEntityID(), A, and B.
Field Documentation
INVALID
const uint16 UE::MovieScene::FMovieSceneEntityID::INVALID = uint16(-1) static private
Definition at line 364 of file MovieSceneEntityIDs.h.
Referenced by FMovieSceneEntityID(), and IsValid().
Value
uint16 UE::MovieScene::FMovieSceneEntityID::Value private
Definition at line 366 of file MovieSceneEntityIDs.h.
Referenced by FMovieSceneEntityID(), FMovieSceneEntityID(), AsIndex(), GetTypeHash, and IsValid().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityIDs.h