Unreal Engine 5.6 C++ API: IAudioStreamingManager Struct Reference
IAudioStreamingManager Struct Reference abstract
Interface to add functions specifically related to audio streaming.
#include "ContentStreaming.h"
Public Member Functions
virtual void AddForceInlineSoundWave (const FSoundWaveProxyPtr &SoundWave)
Adds the memory usage of the force inline sound to the streaming cache budget.
virtual FString GenerateMemoryReport ()=0
Generate a memory report as a formatted string for this streaming manager.
virtual FAudioChunkHandle GetLoadedChunk (const FSoundWaveProxyPtr &SoundWave, uint32 ChunkIndex, bool bBlockForLoad=false, bool bForImmediatePlayback=false) const =0
Gets a pointer to a chunk of audio data.
virtual void HandleStarvation (const FSoundWaveProxyPtr &SoundWave, const uint32 ChunkIndex, const uint32 InBytesProduced, const uint32 InBytesExpected)
In the event that the decoder playing back the chunks is in a starvation state due to an outstanding chunk load, handle that here.
virtual void RemoveForceInlineSoundWave (const FSoundWaveProxyPtr &SoundWave)
Removes the memory usage of the force inline sound from the streaming cache budget.
virtual int32 RenderStatAudioStreaming (UWorld *World, FViewport *Viewport, FCanvas *Canvas, int32 X, int32 Y, const FVector *ViewLocation, const FRotator *ViewRotation)=0
Used for rendering debug info:
virtual bool RequestChunk (const FSoundWaveProxyPtr &SoundWave, uint32 ChunkIndex, TFunction< void(EAudioChunkLoadResult)> OnLoadCompleted=LoadCompletedDefault, ENamedThreads::Type ThreadToCallOnLoadCompletedOn=ENamedThreads::AnyThread, bool bForImmediatePlayback=false)=0
virtual void SetProfilingMode (bool bEnabled)=0
Whether to toggle a performance intensive profiling mode the streaming manager.
virtual uint64 TrimMemory (uint64 NumBytesToFree)=0
This will start evicting elements from the cache until either hit our target of bytes or run out of chunks we can free.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual bool CanCreateSoundSource(const FWaveInstance *WaveInstance) const
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual bool IsManagedStreamingSoundSource(const FSoundSource *SoundSource) const
Returns true if this is a streaming Sound Source that is managed by the streaming manager.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual bool IsManagedStreamingSoundWave(const FSoundWaveProxyPtr &SoundWave) const
Returns true if this is a Sound Wave that is managed by the streaming manager.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual bool IsStreamingInProgress(const FSoundWaveProxyPtr &SoundWave)
Returns true if this Sound Wave is currently streaming a chunk.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual void AddDecoder(ICompressedAudioInfo *CompressedAudioInfo)
Adds the decoder to the streaming manager to prevent stream chunks from getting reaped from underneath it.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual void AddStreamingSoundSource(FSoundSource *SoundSource)
Adds a new Sound Source to the streaming manager.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual void AddStreamingSoundWave(const FSoundWaveProxyPtr &SoundWave)
Adds a new Sound Wave to the streaming manager.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual void RemoveDecoder(ICompressedAudioInfo *CompressedAudioInfo)
Removes the decoder from the streaming manager.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual void RemoveStreamingSoundSource(FSoundSource *SoundSource)
Removes a Sound Source from the streaming manager.
UE_DEPRECATED (5.5, "Use These methods are no longer used (removing the unused legacy streaming manager)") virtual void RemoveStreamingSoundWave(const FSoundWaveProxyPtr &SoundWave)
Removes a Sound Wave from the streaming manager.
Public Member Functions inherited from IStreamingManager
IStreamingManager ()
virtual ~IStreamingManager ()
Virtual destructor.
virtual void AddLevel (class ULevel *Level)=0
Adds a ULevel that has already prepared StreamingData to the streaming manager.
void AddViewInformation (const FVector &ViewOrigin, float ScreenSize, float FOVScreenSize, float BoostFactor=1.0f, bool bOverrideLocation=false, float Duration=0.0f, TWeakObjectPtr< AActor > InActorToBoost=NULL, TWeakObjectPtr< UWorld > InWorld=NULL)
Adds the passed in view information to the static array.
void AddViewLocation (const FVector &Location, float BoostFactor=1.0f, bool bOverrideLocation=false, float Duration=0.0f)
Queue up view locations to the streaming system.
virtual int32 BlockTillAllRequestsFinished (float TimeLimit=0.0f, bool bLogResults=false)=0
Blocks till all pending requests are fulfilled.
virtual void CancelForcedResources ()=0
Cancels the timed Forced resources (i.e used the Kismet action "Stream In Textures").
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Allows the streaming manager to process exec commands.
int32 GetNumViews () const
Returns the number of view infos.
virtual int32 GetNumWantingResources () const
Returns the number of resources that currently wants to be streamed in.
virtual int32 GetNumWantingResourcesID () const
Returns the current ID for GetNumWantingResources().
const FStreamingViewInfo & GetViewInformation (int32 ViewIndex) const
Returns the view info by the specified index.
virtual void NotifyActorDestroyed (AActor *Actor)
Called when a spawned actor is destroyed.
virtual void NotifyLevelChange ()=0
Notifies manager of "level" change.
virtual void NotifyLevelOffset (class ULevel *Level, const FVector &Offset)=0
Notifies manager that level primitives were shifted.
virtual void NotifyPrimitiveDetached (const UPrimitiveComponent *Primitive)
Called when a primitive is detached from an actor or another component.
virtual void NotifyPrimitiveUpdated (const UPrimitiveComponent *Primitive)
Called when a primitive streaming data needs to be updated.
virtual void NotifyPrimitiveUpdated_Concurrent (const UPrimitiveComponent *Primitive)
Called when a primitive streaming data needs to be updated in the last stage of the frame.
virtual void OnAudioStreamingParamsChanged ()
virtual void PropagateLightingScenarioChange ()
Propagates a change to the active lighting scenario.
virtual void RemoveLevel (class ULevel *Level)=0
Removes a ULevel from the streaming manager.
void RemoveStreamingViews (ERemoveStreamingViews RemovalType)
Removes streaming views from the streaming manager.
virtual int32 StreamAllResources (float TimeLimit=0.0f)
Streams in/out all resources that wants to and blocks until it's done.
virtual void Tick (float DeltaTime, bool bProcessEverything=false)
Calls UpdateResourceStreaming(), and does per-frame cleaning.
UE_DEPRECATED (5.1, "This is deprecated to follow inclusive naming rules. Use AddViewLocation() instead.") void AddViewSlaveLocation(const FVector &Location
virtual void UpdateResourceStreaming (float DeltaTime, bool bProcessEverything=false)=0
Updates streaming, taking into account all current view infos.
Static Public Attributes
static constexpr auto LoadCompletedDefault = [](EAudioChunkLoadResult) {}
Manually prepare a chunk to start playing back.
Protected Member Functions
virtual void AddMemoryCountedFeature (const FAudioStreamCacheMemoryHandle &Feature)
This can be used to increase the memory count for external features.
virtual void AddReferenceToChunk (const FAudioChunkHandle &InHandle)=0
This can be used to increment reference counted handles to audio chunks.
virtual void RemoveMemoryCountedFeature (const FAudioStreamCacheMemoryHandle &Feature)
This can be used to decrease the memory count for external features.
virtual void RemoveReferenceToChunk (const FAudioChunkHandle &InHandle)=0
This can be used to decrement reference counted handles to audio chunks.
Protected Member Functions inherited from IStreamingManager
void SetupViewInfos (float DeltaTime)
Sets up the CurrentViewInfos array based on PendingViewInfos, LastingViewInfos and SecondaryLocations.
Static Protected Member Functions
static FAudioChunkHandle BuildChunkHandle (const uint8 *InData, uint32 NumBytes, const FSoundWaveProxyPtr &InSoundWave, const FName &SoundWaveName, uint32 InChunkIndex, uint64 CacheLookupID)
This can be called by implementers of IAudioStreamingManager to construct an FAudioChunkHandle using an otherwise inaccessible constructor.
Static Protected Member Functions inherited from IStreamingManager
static void AddViewInfoToArray (TArray< FStreamingViewInfo > &ViewInfos, const FVector &ViewOrigin, float ScreenSize, float FOVScreenSize, float BoostFactor, bool bOverrideLocation, float Duration, TWeakObjectPtr< AActor > InActorToBoost, TWeakObjectPtr< UWorld > InWorld)
Adds the passed in view information to the static array.
static void RemoveViewInfoFromArray (TArray< FStreamingViewInfo > &ViewInfos, const FVector &ViewOrigin)
Remove view infos with the same location from the given array.
Protected Attributes
friend FAudioChunkHandle
friend FAudioStreamCacheMemoryHandle
Protected Attributes inherited from IStreamingManager
int32 NumWantingResources
Number of resources that currently wants to be streamed in.
int32 NumWantingResourcesCounter
The current counter for NumWantingResources.
Static Private Member Functions
static void LogWarning ()
Additional Inherited Members
Static Public Member Functions inherited from IStreamingManager
static struct FStreamingManagerCollection & Get ()
static struct FStreamingManagerCollection * Get_Concurrent ()
Same as get but could fail if state not allocated or shutdown.
static bool HasShutdown ()
Checks if the streaming manager has already been shut down.
static void Shutdown ()
Data Fields inherited from IStreamingManager
float BoostFactor = 1.0f
float bool bOverrideLocation = false
float bool float Duration
Static Protected Attributes inherited from IStreamingManager
static bool bPendingRemoveViews
Set when Tick() has been called.
static TArray< FStreamingViewInfo > CurrentViewInfos
Current collection of views that need to be taken into account for streaming.
static TArray< FStreamingViewInfo > LastingViewInfos
Views that stick around for a while.
static TArray< FStreamingViewInfo > PendingViewInfos
Pending views.
static TArray< FSecondaryLocation > SecondaryLocations
Collection of view locations that will be added at the next call to AddViewInformation.
Detailed Description
Interface to add functions specifically related to audio streaming.
Definition at line 519 of file ContentStreaming.h.
Member Function Documentation
AddForceInlineSoundWave()
virtual void IAudioStreamingManager::AddForceInlineSoundWave (const FSoundWaveProxyPtr & SoundWave) inline virtual
Adds the memory usage of the force inline sound to the streaming cache budget.
Reimplemented in FCachedAudioStreamingManager.
Definition at line 522 of file ContentStreaming.h.
AddMemoryCountedFeature()
virtual void IAudioStreamingManager::AddMemoryCountedFeature (const FAudioStreamCacheMemoryHandle & Feature) inline protected virtual
This can be used to increase the memory count for external features.
Called by FAudioStreamCacheMemoryHandle. The pattern for changing the amount of memory of an already added feature is to first remove and then add again with the new number
Reimplemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
Definition at line 599 of file ContentStreaming.h.
References FAudioStreamCacheMemoryHandle.
AddReferenceToChunk()
virtual void IAudioStreamingManager::AddReferenceToChunk (const FAudioChunkHandle & InHandle) protected pure virtual
This can be used to increment reference counted handles to audio chunks.
Called by the copy constructor of FAudioChunkHandle.
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
References FAudioChunkHandle.
BuildChunkHandle()
FAudioChunkHandle IAudioStreamingManager::BuildChunkHandle (const uint8 * InData, uint32 NumBytes, const FSoundWaveProxyPtr & InSoundWave, const FName & SoundWaveName, uint32 InChunkIndex, uint64 CacheLookupID) static protected
This can be called by implementers of IAudioStreamingManager to construct an FAudioChunkHandle using an otherwise inaccessible constructor.
References FAudioChunkHandle.
GenerateMemoryReport()
virtual FString IAudioStreamingManager::GenerateMemoryReport () pure virtual
Generate a memory report as a formatted string for this streaming manager.
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
GetLoadedChunk()
virtual FAudioChunkHandle IAudioStreamingManager::GetLoadedChunk (const FSoundWaveProxyPtr & SoundWave, uint32 ChunkIndex, bool bBlockForLoad = false, bool bForImmediatePlayback = false) const pure virtual
Gets a pointer to a chunk of audio data.
Parameters
SoundWave SoundWave we want a chunk from
ChunkIndex Index of the chunk we want
bBlockForLoad if true, will block this thread until we finish loading this chunk.
bForImmediatePlayback if true, will optionally reprioritize this chunk's load request. See au.streamcaching.PlaybackRequestPriority.
Returns
a handle to the loaded chunk. Can return a default constructed FAudioChunkHandle if the chunk is not loaded yet.
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
References FAudioChunkHandle.
HandleStarvation()
virtual void IAudioStreamingManager::HandleStarvation (const FSoundWaveProxyPtr & SoundWave, const uint32 ChunkIndex, const uint32 InBytesProduced, const uint32 InBytesExpected) inline virtual
In the event that the decoder playing back the chunks is in a starvation state due to an outstanding chunk load, handle that here.
Reimplemented in FCachedAudioStreamingManager.
Definition at line 576 of file ContentStreaming.h.
LogWarning()
void IAudioStreamingManager::LogWarning () static private
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
RemoveForceInlineSoundWave()
virtual void IAudioStreamingManager::RemoveForceInlineSoundWave (const FSoundWaveProxyPtr & SoundWave) inline virtual
Removes the memory usage of the force inline sound from the streaming cache budget.
Reimplemented in FCachedAudioStreamingManager.
Definition at line 525 of file ContentStreaming.h.
RemoveMemoryCountedFeature()
virtual void IAudioStreamingManager::RemoveMemoryCountedFeature (const FAudioStreamCacheMemoryHandle & Feature) inline protected virtual
This can be used to decrease the memory count for external features.
Called by FAudioStreamCacheMemoryHandle.
Reimplemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
Definition at line 604 of file ContentStreaming.h.
References FAudioStreamCacheMemoryHandle.
RemoveReferenceToChunk()
virtual void IAudioStreamingManager::RemoveReferenceToChunk (const FAudioChunkHandle & InHandle) protected pure virtual
This can be used to decrement reference counted handles to audio chunks.
Called by the destructor of FAudioChunkHandle.
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
References FAudioChunkHandle.
RenderStatAudioStreaming()
virtual int32 IAudioStreamingManager::RenderStatAudioStreaming (UWorld * World, FViewport * Viewport, FCanvas * Canvas, int32 X, int32 Y, const FVector * ViewLocation, const FRotator * ViewRotation) pure virtual
Used for rendering debug info:
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
References FVector, X, and Y.
RequestChunk()
virtual bool IAudioStreamingManager::RequestChunk (const FSoundWaveProxyPtr & SoundWave, uint32 ChunkIndex, TFunction< void(EAudioChunkLoadResult)> OnLoadCompleted = LoadCompletedDefault, ENamedThreads::Type ThreadToCallOnLoadCompletedOn = ENamedThreads::AnyThread, bool bForImmediatePlayback = false) pure virtual
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
References ENamedThreads::AnyThread, and LoadCompletedDefault.
SetProfilingMode()
virtual void IAudioStreamingManager::SetProfilingMode (bool bEnabled) pure virtual
Whether to toggle a performance intensive profiling mode the streaming manager.
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
TrimMemory()
virtual uint64 IAudioStreamingManager::TrimMemory (uint64 NumBytesToFree) pure virtual
This will start evicting elements from the cache until either hit our target of bytes or run out of chunks we can free.
Parameters
NumBytesToFree The amount of memory we would like to free, in bytes.
Returns
the amount of bytes we managed to free.
Implemented in FCachedAudioStreamingManager, and FDummyAudioStreamingManager.
UE_DEPRECATED() [1/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") const inline
Definition at line 635 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [2/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") const inline
Returns true if this is a streaming Sound Source that is managed by the streaming manager.
Definition at line 647 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [3/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") const & inline
Returns true if this is a Sound Wave that is managed by the streaming manager.
Definition at line 628 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [4/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") const & inline
Returns true if this Sound Wave is currently streaming a chunk.
Definition at line 632 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [5/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") inline
Adds the decoder to the streaming manager to prevent stream chunks from getting reaped from underneath it.
Definition at line 620 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [6/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") inline
Adds a new Sound Source to the streaming manager.
Definition at line 639 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [7/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") const & inline
Adds a new Sound Wave to the streaming manager.
Definition at line 612 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [8/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") inline
Removes the decoder from the streaming manager.
Definition at line 624 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [9/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") inline
Removes a Sound Source from the streaming manager.
Definition at line 643 of file ContentStreaming.h.
References LogWarning().
UE_DEPRECATED() [10/10]
IAudioStreamingManager::UE_DEPRECATED (5. 5, "Use These methods are no longer used (removing the unused legacy streaming manager)") const & inline
Removes a Sound Wave from the streaming manager.
Definition at line 616 of file ContentStreaming.h.
References LogWarning().
Field Documentation
FAudioChunkHandle
friend IAudioStreamingManager::FAudioChunkHandle protected
Definition at line 579 of file ContentStreaming.h.
Referenced by FCachedAudioStreamingManager::AddReferenceToChunk(), FDummyAudioStreamingManager::AddReferenceToChunk(), AddReferenceToChunk(), BuildChunkHandle(), FCachedAudioStreamingManager::GetLoadedChunk(), FDummyAudioStreamingManager::GetLoadedChunk(), GetLoadedChunk(), FCachedAudioStreamingManager::RemoveReferenceToChunk(), FDummyAudioStreamingManager::RemoveReferenceToChunk(), and RemoveReferenceToChunk().
FAudioStreamCacheMemoryHandle
friend IAudioStreamingManager::FAudioStreamCacheMemoryHandle protected
Definition at line 580 of file ContentStreaming.h.
Referenced by FCachedAudioStreamingManager::AddMemoryCountedFeature(), FDummyAudioStreamingManager::AddMemoryCountedFeature(), AddMemoryCountedFeature(), FCachedAudioStreamingManager::RemoveMemoryCountedFeature(), FDummyAudioStreamingManager::RemoveMemoryCountedFeature(), and RemoveMemoryCountedFeature().
LoadCompletedDefault
auto IAudioStreamingManager::LoadCompletedDefault = [](EAudioChunkLoadResult) {} static constexpr
Manually prepare a chunk to start playing back.
This should only be used when the Load On Demand feature is enabled, and returns false on failure.
Parameters
SoundWave SoundWave we would like to request a chunk of.
ChunkIndex the index of that soundwave we'd like to request a chunk of.
OnLoadCompleted optional callback when the load completes.
ThreadToCallOnLoadCompleteOn. Optional specifier for which thread OnLoadCompleted should be called on.
bForImmediatePlaybac if true, this will optionally reprioritize this chunk's load request.
Definition at line 535 of file ContentStreaming.h.
Referenced by FDummyAudioStreamingManager::RequestChunk(), and RequestChunk().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/ContentStreaming.h