Unreal Engine 5.6 C++ API: FObjectsBeingDebuggedIterator Struct Reference
FObjectsBeingDebuggedIterator Struct Reference
#include "KismetDebugUtilities.h"
Public Member Functions
UNREALED_API FObjectsBeingDebuggedIterator ()
Element access
FSelectionIterator SelectedActorsIter
Advances iterator to the next element in the container.
int32 LevelScriptActorIndex
Advances iterator to the next element in the container.
UNREALED_API UObject * operator* () const
Advances iterator to the next element in the container.
UNREALED_API UObject * operator-> () const
Advances iterator to the next element in the container.
UNREALED_API FObjectsBeingDebuggedIterator & operator++ ()
Advances iterator to the next element in the container.
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator has not reached the last element.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
UNREALED_API void FindNextLevelScriptActor ()
Advances iterator to the next element in the container.
UNREALED_API bool IsValid () const
Advances iterator to the next element in the container.
UNREALED_API UWorld * GetWorld () const
Advances iterator to the next element in the container.
Detailed Description
Definition at line 124 of file KismetDebugUtilities.h.
Constructor & Destructor Documentation
FObjectsBeingDebuggedIterator()
UNREALED_API FObjectsBeingDebuggedIterator::FObjectsBeingDebuggedIterator ()
Referenced by operator++().
Member Function Documentation
FindNextLevelScriptActor()
UNREALED_API void FObjectsBeingDebuggedIterator::FindNextLevelScriptActor () private
Advances iterator to the next element in the container.
GetWorld()
UNREALED_API UWorld * FObjectsBeingDebuggedIterator::GetWorld () const private
Advances iterator to the next element in the container.
IsValid()
UNREALED_API bool FObjectsBeingDebuggedIterator::IsValid () const private
Advances iterator to the next element in the container.
Referenced by operator bool().
operator bool()
FORCEINLINE FObjectsBeingDebuggedIterator::operator bool () const inline explicit
conversion to "bool" returning true if the iterator has not reached the last element.
Definition at line 139 of file KismetDebugUtilities.h.
References FORCEINLINE, and IsValid().
operator!()
FORCEINLINE bool FObjectsBeingDebuggedIterator::operator! () const inline
inverse of the "bool" operator
Definition at line 144 of file KismetDebugUtilities.h.
References bool, and FORCEINLINE.
operator*()
UNREALED_API UObject * FObjectsBeingDebuggedIterator::operator* () const
Advances iterator to the next element in the container.
operator++()
UNREALED_API FObjectsBeingDebuggedIterator & FObjectsBeingDebuggedIterator::operator++ ()
Advances iterator to the next element in the container.
References FObjectsBeingDebuggedIterator().
operator->()
UNREALED_API UObject * FObjectsBeingDebuggedIterator::operator-> () const
Advances iterator to the next element in the container.
Field Documentation
LevelScriptActorIndex
int32 FObjectsBeingDebuggedIterator::LevelScriptActorIndex private
Advances iterator to the next element in the container.
Definition at line 151 of file KismetDebugUtilities.h.
SelectedActorsIter
FSelectionIterator FObjectsBeingDebuggedIterator::SelectedActorsIter private
Advances iterator to the next element in the container.
Definition at line 150 of file KismetDebugUtilities.h.
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/Kismet2/KismetDebugUtilities.h