Unreal Engine 5.6 C++ API: FGenericPlatformAtomics Struct Reference
FGenericPlatformAtomics Struct Reference
DEPRECATED!
#include "GenericPlatformAtomics.h"
Static Public Member Functions
static FORCEINLINE bool CanUseCompareExchange128 ()
Static Protected Member Functions
static bool IsAligned (const volatile void *Ptr, const uint32 Alignment=sizeof(void *))
Checks if a pointer is aligned and can be used with atomic functions.
Detailed Description
DEPRECATED!
UE atomics are not maintained and potentially will be physically deprecated. Use std::atomic<T> for new code
Generic implementation...you are required to implement at least FPlatformAtomics::InterlockedCompareExchange but they are listed here to provide a base implementation in terms of FPlatformAtomics::InterlockedCompareExchange and easy copy-paste
Definition at line 25 of file GenericPlatformAtomics.h.
Member Function Documentation
CanUseCompareExchange128()
FORCEINLINE bool FGenericPlatformAtomics::CanUseCompareExchange128 () inline static
Returns
true, if the processor we are running on can execute compare and exchange 128-bit operation.
See also
cmpxchg16b, early AMD64 processors don't support this operation.
Definition at line 313 of file GenericPlatformAtomics.h.
References FORCEINLINE.
IsAligned()
bool FGenericPlatformAtomics::IsAligned (const volatile void * Ptr, const uint32 Alignment = sizeof(void*)) inline static protected
Checks if a pointer is aligned and can be used with atomic functions.
Parameters
Ptr - The pointer to check.
Returns
true if the pointer is aligned, false otherwise.
Definition at line 326 of file GenericPlatformAtomics.h.
Referenced by FWindowsPlatformAtomics::InterlockedCompareExchange(), FWindowsPlatformAtomics::InterlockedCompareExchangePointer(), and FWindowsPlatformAtomics::InterlockedExchangePtr().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformAtomics.h