Unreal Engine 5.6 C++ API: FGameplayAbilityInputBinds Struct Reference
FGameplayAbilityInputBinds Struct Reference
Structure that tells AbilitySystemComponent what to bind to an InputComponent (see BindAbilityActivationToInputComponent)
#include "GameplayAbilityTypes.h"
Public Member Functions
FGameplayAbilityInputBinds (const FGameplayAbilityInputBinds &)=default
UEnum * GetBindEnum ()
FGameplayAbilityInputBinds & operator= (const FGameplayAbilityInputBinds &)=default
FGameplayAbilityInputBinds & operator= (FGameplayAbilityInputBinds &&)=default
UE_DEPRECATED (5.1, "Enum names are now represented by path names. Please use a version of FGameplayAbilityInputBinds constructor that accepts FTopLevelAssetPath.") FGameplayAbilityInputBinds(FString InConfirmTargetCommand
UE_DEPRECATED (5.1, "Enum names are now represented by path names. Please use EnumPathName.") FString EnumName
Returns enum to use for ability binds.
Data Fields
FString CancelTargetCommand
Defines command string that will be bound to Cancel Targeting.
int32 CancelTargetInputID
If >=0, Cancel is bound to an entry in the enum.
PRAGMA_ENABLE_DEPRECATION_WARNINGS FString ConfirmTargetCommand
Defines command string that will be bound to Confirm Targeting.
int32 ConfirmTargetInputID
If >=0, Confirm is bound to an entry in the enum.
FTopLevelAssetPath EnumPathName
Returns enum to use for ability binds.
FString InCancelTargetCommand
FString FString int32 int32 InCancelTargetInputID
FString FString int32 InConfirmTargetInputID = INDEX_NONE
FString FString InEnumName
Private Member Functions
void TryFixShortEnumName ()
Detailed Description
Structure that tells AbilitySystemComponent what to bind to an InputComponent (see BindAbilityActivationToInputComponent)
Definition at line 335 of file GameplayAbilityTypes.h.
Constructor & Destructor Documentation
FGameplayAbilityInputBinds()
FGameplayAbilityInputBinds::FGameplayAbilityInputBinds (const FGameplayAbilityInputBinds &) default
References FGameplayAbilityInputBinds().
Referenced by FGameplayAbilityInputBinds(), operator=(), and operator=().
Member Function Documentation
GetBindEnum()
UEnum * FGameplayAbilityInputBinds::GetBindEnum () inline
Definition at line 383 of file GameplayAbilityTypes.h.
References EnumPathName, GetBindEnum(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by GetBindEnum().
operator=() [1/2]
FGameplayAbilityInputBinds & FGameplayAbilityInputBinds::operator= (const FGameplayAbilityInputBinds &) default
References FGameplayAbilityInputBinds(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FGameplayAbilityInputBinds & FGameplayAbilityInputBinds::operator= (FGameplayAbilityInputBinds &&) default
References FGameplayAbilityInputBinds().
TryFixShortEnumName()
void FGameplayAbilityInputBinds::TryFixShortEnumName () inline private
Definition at line 396 of file GameplayAbilityTypes.h.
References EnumPathName, GetPathNameSafe(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UClass::TryFindTypeSlow().
UE_DEPRECATED() [1/2]
FGameplayAbilityInputBinds::UE_DEPRECATED (5. 1, "Enum names are now represented by path names. Please use a version of FGameplayAbilityInputBinds constructor that accepts FTopLevelAssetPath.")
UE_DEPRECATED() [2/2]
FGameplayAbilityInputBinds::UE_DEPRECATED (5. 1, "Enum names are now represented by path names. Please use EnumPathName.")
Returns enum to use for ability binds.
E.g., "Ability1"-"Ability9" input commands will be bound to ability activations inside the AbiltiySystemComponent
Field Documentation
CancelTargetCommand
FString FGameplayAbilityInputBinds::CancelTargetCommand
Defines command string that will be bound to Cancel Targeting.
Definition at line 368 of file GameplayAbilityTypes.h.
CancelTargetInputID
int32 FGameplayAbilityInputBinds::CancelTargetInputID
If >=0, Cancel is bound to an entry in the enum.
Definition at line 381 of file GameplayAbilityTypes.h.
ConfirmTargetCommand
PRAGMA_ENABLE_DEPRECATION_WARNINGS FString FGameplayAbilityInputBinds::ConfirmTargetCommand
Defines command string that will be bound to Confirm Targeting.
Definition at line 365 of file GameplayAbilityTypes.h.
ConfirmTargetInputID
int32 FGameplayAbilityInputBinds::ConfirmTargetInputID
If >=0, Confirm is bound to an entry in the enum.
Definition at line 378 of file GameplayAbilityTypes.h.
EnumPathName
FTopLevelAssetPath FGameplayAbilityInputBinds::EnumPathName
Returns enum to use for ability binds.
E.g., "Ability1"-"Ability9" input commands will be bound to ability activations inside the AbiltiySystemComponent
Definition at line 375 of file GameplayAbilityTypes.h.
Referenced by GetBindEnum(), and TryFixShortEnumName().
InCancelTargetCommand
FString FGameplayAbilityInputBinds::InCancelTargetCommand
Definition at line 338 of file GameplayAbilityTypes.h.
InCancelTargetInputID
FString FString int32 int32 FGameplayAbilityInputBinds::InCancelTargetInputID
Initial value:
= INDEX_NONE)
        : ConfirmTargetCommand(InConfirmTargetCommand)
        , CancelTargetCommand(InCancelTargetCommand)
PRAGMA_DISABLE_DEPRECATION_WARNINGS
        , EnumName(InEnumName)
PRAGMA_ENABLE_DEPRECATION_WARNINGS
        , ConfirmTargetInputID(InConfirmTargetInputID)
        , CancelTargetInputID(InCancelTargetInputID)
    {
        TryFixShortEnumName();
    }
    FGameplayAbilityInputBinds(FString InConfirmTargetCommand, FString InCancelTargetCommand, FTopLevelAssetPath InEnumPathName, int32 InConfirmTargetInputID = INDEX_NONE, int32 InCancelTargetInputID = INDEX_NONE)
        : ConfirmTargetCommand(InConfirmTargetCommand)
        , CancelTargetCommand(InCancelTargetCommand)
        , EnumPathName(InEnumPathName)
        , ConfirmTargetInputID(InConfirmTargetInputID)
        , CancelTargetInputID(InCancelTargetInputID)
    {
    }
PRAGMA_DISABLE_DEPRECATION_WARNINGS
    FGameplayAbilityInputBinds(FGameplayAbilityInputBinds&&) = default
Definition at line 338 of file GameplayAbilityTypes.h.
InConfirmTargetInputID
FString FString int32 FGameplayAbilityInputBinds::InConfirmTargetInputID = INDEX_NONE
Definition at line 338 of file GameplayAbilityTypes.h.
InEnumName
FString FString FGameplayAbilityInputBinds::InEnumName
Definition at line 338 of file GameplayAbilityTypes.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/Abilities/GameplayAbilityTypes.h