Unreal Engine 5.6 C++ API: FAudioChunkCache::FCacheElement Struct Reference
FAudioChunkCache::FCacheElement Struct Reference
Public Member Functions
FCacheElement (uint32 InCacheIndex)
~FCacheElement ()
bool CanEvictChunk () const
FStreamedAudioChunk * GetChunk (uint32 InChunkIndex) const
uint32 GetNumChunks () const
bool IsBeingPlayed () const
bool IsChunkStale ()
bool IsInUse () const
bool IsLoadInProgress () const
bool IsSoundWaveRetainingAudio () const
void ReleaseRetainedAudioOnSoundWave ()
void UpdateDebugInfoLoadingBehavior ()
void WaitForAsyncLoadCompletion (bool bCancel)
bool WantsFilteredLogging () const
Data Fields
FThreadSafeBool bIsLoaded
bool bWantsExtraLogging = false
uint64 CacheLookupID = InvalidAudioStreamCacheLookupID
uint8 * ChunkData
uint32 ChunkDataSize
FCacheElementDebugInfo DebugInfo
FChunkKey Key
FCacheElement * LessRecentElement
FCacheElement * MoreRecentElement
FThreadSafeCounter NumConsumers
EAsyncIOPriorityAndFlags Priority = AIOP_MIN
FBulkDataBatchRequest Read
TWeakPtr< FSoundWaveData, ESPMode::ThreadSafe > SoundWaveWeakPtr
Detailed Description
Definition at line 292 of file AudioStreamingCache.h.
Constructor & Destructor Documentation
FCacheElement()
FAudioChunkCache::FCacheElement::FCacheElement (uint32 InCacheIndex) inline
Definition at line 333 of file AudioStreamingCache.h.
References bIsLoaded, CacheLookupID, ChunkData, ChunkDataSize, LessRecentElement, and MoreRecentElement.
~FCacheElement()
FAudioChunkCache::FCacheElement::~FCacheElement () inline
TODO: This is failing because of Key.GetLoadingBehavior(). We could get this from the FSoundWaveData or store it, or ignore it here. UE_LOG(LogAudioStreamCaching, Error, TEXT("Tried to destroy streaming cache while the cached data was in use! (Sound: %s - Loading Behavior: %s - Chunk Index: %i)") , *Key.SoundWaveName.ToString(), EnumToString(Key.GetLoadingBehavior()), Key.ChunkIndex);
Definition at line 374 of file AudioStreamingCache.h.
References ChunkData, FMemory::Free(), NumConsumers, and WaitForAsyncLoadCompletion().
Member Function Documentation
CanEvictChunk()
bool FAudioChunkCache::FCacheElement::CanEvictChunk () const inline
Definition at line 360 of file AudioStreamingCache.h.
References IsInUse(), and IsLoadInProgress().
GetChunk()
FStreamedAudioChunk * FAudioChunkCache::FCacheElement::GetChunk (uint32 InChunkIndex) const
GetNumChunks()
uint32 FAudioChunkCache::FCacheElement::GetNumChunks () const
IsBeingPlayed()
bool FAudioChunkCache::FCacheElement::IsBeingPlayed () const
IsChunkStale()
bool FAudioChunkCache::FCacheElement::IsChunkStale ()
IsInUse()
bool FAudioChunkCache::FCacheElement::IsInUse () const inline
Definition at line 350 of file AudioStreamingCache.h.
References NumConsumers.
Referenced by CanEvictChunk().
IsLoadInProgress()
bool FAudioChunkCache::FCacheElement::IsLoadInProgress () const inline
Definition at line 345 of file AudioStreamingCache.h.
References bIsLoaded.
Referenced by CanEvictChunk().
IsSoundWaveRetainingAudio()
bool FAudioChunkCache::FCacheElement::IsSoundWaveRetainingAudio () const
ReleaseRetainedAudioOnSoundWave()
void FAudioChunkCache::FCacheElement::ReleaseRetainedAudioOnSoundWave ()
UpdateDebugInfoLoadingBehavior()
void FAudioChunkCache::FCacheElement::UpdateDebugInfoLoadingBehavior ()
WaitForAsyncLoadCompletion()
void FAudioChunkCache::FCacheElement::WaitForAsyncLoadCompletion (bool bCancel)
Referenced by ~FCacheElement().
WantsFilteredLogging()
bool FAudioChunkCache::FCacheElement::WantsFilteredLogging () const inline
UE_BUILD_SHIPPING
Definition at line 310 of file AudioStreamingCache.h.
References bWantsExtraLogging.
Field Documentation
bIsLoaded
FThreadSafeBool FAudioChunkCache::FCacheElement::bIsLoaded
Definition at line 303 of file AudioStreamingCache.h.
Referenced by FCacheElement(), and IsLoadInProgress().
bWantsExtraLogging
bool FAudioChunkCache::FCacheElement::bWantsExtraLogging = false
Definition at line 308 of file AudioStreamingCache.h.
Referenced by WantsFilteredLogging().
CacheLookupID
uint64 FAudioChunkCache::FCacheElement::CacheLookupID = InvalidAudioStreamCacheLookupID
Definition at line 299 of file AudioStreamingCache.h.
Referenced by FCacheElement().
ChunkData
uint8* FAudioChunkCache::FCacheElement::ChunkData
Definition at line 295 of file AudioStreamingCache.h.
Referenced by FCacheElement(), and ~FCacheElement().
ChunkDataSize
uint32 FAudioChunkCache::FCacheElement::ChunkDataSize
Definition at line 296 of file AudioStreamingCache.h.
Referenced by FCacheElement().
DebugInfo
FCacheElementDebugInfo FAudioChunkCache::FCacheElement::DebugInfo
Definition at line 330 of file AudioStreamingCache.h.
Key
FChunkKey FAudioChunkCache::FCacheElement::Key
Definition at line 294 of file AudioStreamingCache.h.
LessRecentElement
FCacheElement* FAudioChunkCache::FCacheElement::LessRecentElement
Definition at line 298 of file AudioStreamingCache.h.
Referenced by FCacheElement().
MoreRecentElement
FCacheElement* FAudioChunkCache::FCacheElement::MoreRecentElement
Definition at line 297 of file AudioStreamingCache.h.
Referenced by FCacheElement().
NumConsumers
FThreadSafeCounter FAudioChunkCache::FCacheElement::NumConsumers
Definition at line 320 of file AudioStreamingCache.h.
Referenced by ~FCacheElement(), and IsInUse().
Priority
EAsyncIOPriorityAndFlags FAudioChunkCache::FCacheElement::Priority = AIOP_MIN
Definition at line 327 of file AudioStreamingCache.h.
Read
FBulkDataBatchRequest FAudioChunkCache::FCacheElement::Read
Definition at line 326 of file AudioStreamingCache.h.
SoundWaveWeakPtr
TWeakPtr<FSoundWaveData, ESPMode::ThreadSafe> FAudioChunkCache::FCacheElement::SoundWaveWeakPtr
Definition at line 301 of file AudioStreamingCache.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/AudioStreamingCache.h