Unreal Engine 5.6 C++ API: FLightmapSceneShaderData Struct Reference
FLightmapSceneShaderData Struct Reference
#include "LightmapUniformShaderParameters.h"
Public Types
enum { DataStrideInFloat4s = 15 }
Public Member Functions
FLightmapSceneShaderData ()
FLightmapSceneShaderData (const class FLightCacheInterface *LCI, ERHIFeatureLevel::Type FeatureLevel)
FLightmapSceneShaderData (const FPrecomputedLightingUniformParameters &ShaderParameters)
void Setup (const FPrecomputedLightingUniformParameters &ShaderParameters)
Data Fields
TStaticArray< FVector4f, DataStrideInFloat4s > Data
Detailed Description
Definition at line 35 of file LightmapUniformShaderParameters.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DataStrideInFloat4s
Definition at line 38 of file LightmapUniformShaderParameters.h.
Constructor & Destructor Documentation
FLightmapSceneShaderData() [1/3]
FLightmapSceneShaderData::FLightmapSceneShaderData () inline
Definition at line 42 of file LightmapUniformShaderParameters.h.
References Data, InPlace, NoInit, and Setup().
FLightmapSceneShaderData() [2/3]
FLightmapSceneShaderData::FLightmapSceneShaderData (const FPrecomputedLightingUniformParameters & ShaderParameters) inline explicit
Definition at line 50 of file LightmapUniformShaderParameters.h.
References Data, InPlace, NoInit, and Setup().
FLightmapSceneShaderData() [3/3]
FLightmapSceneShaderData::FLightmapSceneShaderData (const class FLightCacheInterface * LCI, ERHIFeatureLevel::Type FeatureLevel)
Member Function Documentation
Setup()
void FLightmapSceneShaderData::Setup (const FPrecomputedLightingUniformParameters & ShaderParameters)
Referenced by FLightmapSceneShaderData(), and FLightmapSceneShaderData().
Field Documentation
Data
TStaticArray<FVector4f, DataStrideInFloat4s> FLightmapSceneShaderData::Data
Definition at line 40 of file LightmapUniformShaderParameters.h.
Referenced by FLightmapSceneShaderData(), and FLightmapSceneShaderData().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/LightmapUniformShaderParameters.h