Unreal Engine 5.6 C++ API: TPerlinNoiseChannelInterface< ChannelContainerType > Struct Template Reference
TPerlinNoiseChannelInterface< ChannelContainerType > Struct Template Reference
#include "PerlinNoiseChannelInterface.h"
Public Types
using ChannelType = typename ChannelContainerType::ChannelType
Public Member Functions
virtual FKeyHandle AddOrUpdateKey_Raw (FMovieSceneChannel *Channel, UMovieSceneSection *SectionToKey, const void *ExtendedEditorData, FFrameNumber InTime, ISequencer &InSequencer, const FGuid &ObjectBindingID, FTrackInstancePropertyBindings *PropertyBindings) const override
Add (or update) a key to the specified channel using it's current value at that time, or some external value specified by the extended editor data.
virtual bool CanCreateKeyEditor_Raw (const FMovieSceneChannel *Channel) const override
Check whether an editor on the sequencer node tree can be created for the specified channel.
virtual void CopyKeys_Raw (FMovieSceneChannel *Channel, const UMovieSceneSection *Section, FName KeyAreaName, FMovieSceneClipboardBuilder &ClipboardBuilder, TArrayView< const FKeyHandle > KeyMask) const override
Copy all the keys specified in KeyMask to the specified clipboard.
virtual TSharedPtr< UE::Sequencer::FChannelModel > CreateChannelModel_Raw (const FMovieSceneChannelHandle &InChannelHandle, const UE::Sequencer::FSectionModel &InSection, FName InChannelName) const override
Create a new channel model for this type of channel.
virtual TSharedPtr< UE::Sequencer::STrackAreaLaneView > CreateChannelView_Raw (const FMovieSceneChannelHandle &InChannelHandle, TWeakPtr< UE::Sequencer::FChannelModel > InWeakModel, const UE::Sequencer::FCreateTrackLaneViewParams &Parameters) const override
Create a new channel view for this type of channel.
virtual TUniquePtr< FCurveModel > CreateCurveEditorModel_Raw (const FMovieSceneChannelHandle &Channel, const UE::Sequencer::FCreateCurveEditorModelParams &Params) const override
Create a new model for this channel that can be used on the curve editor interface.
virtual TSharedRef< SWidget > CreateKeyEditor_Raw (const FMovieSceneChannelHandle &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params) const override
Create an editor on the sequencer node tree.
virtual void DeleteKeys_Raw (FMovieSceneChannel *Channel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime) const override
Delete the specified keys.
virtual int32 DrawExtra_Raw (FMovieSceneChannel *InChannel, const UMovieSceneSection *InOwner, const FSequencerChannelPaintArgs &PaintArgs, int32 LayerId) const override
Draw additional content in addition to keys for a particular channel.
virtual void DrawKeys_Raw (FMovieSceneChannel *Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection *InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams) const override
Gather information on how to draw the specified keys.
virtual void ExtendKeyMenu_Raw (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > MenuExtender, TArrayView< const FExtendKeyMenuParams > Parameters, TWeakPtr< ISequencer > InSequencer) const override
Extend the key context menu.
virtual void ExtendSectionMenu_Raw (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const override
Extend the section context menu.
virtual TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu_Raw (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const override
Extend the section sidebar menu.
virtual TSharedPtr< FStructOnScope > GetKeyStruct_Raw (FMovieSceneChannelHandle Channel, FKeyHandle KeyHandle) const override
Get an editable key struct for the specified key.
virtual void PasteKeys_Raw (FMovieSceneChannel *Channel, UMovieSceneSection *Section, const FMovieSceneClipboardKeyTrack &KeyTrack, const FMovieSceneClipboardEnvironment &SrcEnvironment, const FSequencerPasteEnvironment &DstEnvironment, TArray< FKeyHandle > &OutPastedKeys) const override
Paste the specified key track into the specified channel.
virtual bool ShouldShowCurve_Raw (const FMovieSceneChannel *Channel, UMovieSceneSection *InSection) const override
Whether this channel should draw a curve on its editor UI.
virtual bool SupportsCurveEditorModels_Raw (const FMovieSceneChannelHandle &InChannel) const override
Whether this channel supports curve models.
Public Member Functions inherited from ISequencerChannelInterface
virtual ~ISequencerChannelInterface ()
Detailed Description
template<typename ChannelContainerType>
struct TPerlinNoiseChannelInterface< ChannelContainerType >
Definition at line 80 of file PerlinNoiseChannelInterface.h.
Member Typedef Documentation
ChannelType
template<typename ChannelContainerType> using TPerlinNoiseChannelInterface< ChannelContainerType >::ChannelType = typename ChannelContainerType::ChannelType
Definition at line 82 of file PerlinNoiseChannelInterface.h.
Member Function Documentation
AddOrUpdateKey_Raw()
template<typename ChannelContainerType> virtual FKeyHandle TPerlinNoiseChannelInterface< ChannelContainerType >::AddOrUpdateKey_Raw (FMovieSceneChannel * Channel, UMovieSceneSection * SectionToKey, const void * ExtendedEditorData, FFrameNumber InTime, ISequencer & InSequencer, const FGuid & ObjectBindingID, FTrackInstancePropertyBindings * PropertyBindings) const inline override virtual
Add (or update) a key to the specified channel using it's current value at that time, or some external value specified by the extended editor data.
Parameters
Channel The channel to add a key to
SectionToKey The SectionToKey
ExtendedEditorData A pointer to the extended editor data for this channel of type TMovieSceneChannelTraits<>::ExtendedEditorDataType
InTime The time at which to add a key
InSequencer The currently active sequencer
ObjectBindingID The object binding ID for the track that this channel resides within
PropertyBindings (Optional) Property bindings where this channel exists on a property track
Returns
A handle to the new or updated key
Implements ISequencerChannelInterface.
Definition at line 84 of file PerlinNoiseChannelInterface.h.
References InTime, and FKeyHandle::Invalid().
CanCreateKeyEditor_Raw()
template<typename ChannelContainerType> virtual bool TPerlinNoiseChannelInterface< ChannelContainerType >::CanCreateKeyEditor_Raw (const FMovieSceneChannel * Channel) const inline override virtual
Check whether an editor on the sequencer node tree can be created for the specified channel.
Parameters
Channel The channel to check
Returns
true if a key editor should be constructed, false otherwise
Implements ISequencerChannelInterface.
Definition at line 106 of file PerlinNoiseChannelInterface.h.
CopyKeys_Raw()
template<typename ChannelContainerType> virtual void TPerlinNoiseChannelInterface< ChannelContainerType >::CopyKeys_Raw (FMovieSceneChannel * Channel, const UMovieSceneSection * Section, FName KeyAreaName, FMovieSceneClipboardBuilder & ClipboardBuilder, TArrayView< const FKeyHandle > KeyMask) const inline override virtual
Copy all the keys specified in KeyMask to the specified clipboard.
Parameters
Channel The channel to copy from
Section The section that owns the channel
KeyAreaName The name of the key area
ClipboardBuilder The structure responsible for building clipboard information for each key
KeyMask A specific set of keys to copy
Implements ISequencerChannelInterface.
Definition at line 93 of file PerlinNoiseChannelInterface.h.
CreateChannelModel_Raw()
template<typename ChannelContainerType> virtual TSharedPtr< UE::Sequencer::FChannelModel > TPerlinNoiseChannelInterface< ChannelContainerType >::CreateChannelModel_Raw (const FMovieSceneChannelHandle & InChannelHandle, const UE::Sequencer::FSectionModel & InSection, FName InChannelName) const inline override virtual
Create a new channel model for this type of channel.
Parameters
InChannelHandle The channel handle to create a model for
InSectionModel The section that owns this channel model
InChannelName The identifying name of this channel
Returns
(Optional) A new model to be added to a curve editor
Implements ISequencerChannelInterface.
Definition at line 202 of file PerlinNoiseChannelInterface.h.
CreateChannelView_Raw()
template<typename ChannelContainerType> virtual TSharedPtr< UE::Sequencer::STrackAreaLaneView > TPerlinNoiseChannelInterface< ChannelContainerType >::CreateChannelView_Raw (const FMovieSceneChannelHandle & InChannelHandle, TWeakPtr< UE::Sequencer::FChannelModel > InWeakModel, const UE::Sequencer::FCreateTrackLaneViewParams & Parameters) const inline override virtual
Create a new channel view for this type of channel.
Parameters
InChannelHandle The channel handle to create a model for
InWeakModel The model that is creating the view. Should not be Pinned persistently.
Parameters View construction parameters
Returns
(Optional) A new model to be added to a curve editor
Implements ISequencerChannelInterface.
Definition at line 206 of file PerlinNoiseChannelInterface.h.
CreateCurveEditorModel_Raw()
template<typename ChannelContainerType> virtual TUniquePtr< FCurveModel > TPerlinNoiseChannelInterface< ChannelContainerType >::CreateCurveEditorModel_Raw (const FMovieSceneChannelHandle & Channel, const UE::Sequencer::FCreateCurveEditorModelParams & Params) const inline override virtual
Create a new model for this channel that can be used on the curve editor interface.
Returns
(Optional) A new model to be added to a curve editor
Implements ISequencerChannelInterface.
Definition at line 164 of file PerlinNoiseChannelInterface.h.
References Params.
CreateKeyEditor_Raw()
template<typename ChannelContainerType> virtual TSharedRef< SWidget > TPerlinNoiseChannelInterface< ChannelContainerType >::CreateKeyEditor_Raw (const FMovieSceneChannelHandle & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params) const inline override virtual
Create an editor on the sequencer node tree.
Parameters
Channel The channel handle to create a key editor for
Params Creation parameters containing all the necessary structures for creating the key editor
Returns
The editor widget to display on the node tree
Implements ISequencerChannelInterface.
Definition at line 111 of file PerlinNoiseChannelInterface.h.
References FMovieSceneChannelHandle::Cast(), SNullWidget::NullWidget, TMovieSceneExternalValue< T >::OnGetExternalValue, Params, and SNew.
DeleteKeys_Raw()
template<typename ChannelContainerType> virtual void TPerlinNoiseChannelInterface< ChannelContainerType >::DeleteKeys_Raw (FMovieSceneChannel * Channel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime) const inline override virtual
Delete the specified keys.
If all keys are removed, the current value at that time will be set as the default value for the channel
Parameters
Channel The channel to remove the keys from
InHandles The key handles to delete
InTime The time at which to evaluate for the default value if there are no keys remaining
Implements ISequencerChannelInterface.
Definition at line 89 of file PerlinNoiseChannelInterface.h.
References InTime.
DrawExtra_Raw()
template<typename ChannelContainerType> virtual int32 TPerlinNoiseChannelInterface< ChannelContainerType >::DrawExtra_Raw (FMovieSceneChannel * InChannel, const UMovieSceneSection * InOwner, const FSequencerChannelPaintArgs & PaintArgs, int32 LayerId) const inline override virtual
Draw additional content in addition to keys for a particular channel.
Parameters
InChannel The channel to draw extra display information for
InOwner The owning movie scene section for this channel
PaintArgs Paint arguments containing the draw element list, time-to-pixel converter and other structures
LayerId The slate layer to paint onto
Returns
The new slate layer ID for subsequent elements to paint onto
Implements ISequencerChannelInterface.
Definition at line 169 of file PerlinNoiseChannelInterface.h.
References TArray< InElementType, InAllocatorType >::Add(), FSequencerChannelPaintArgs::DrawElements, FSequencerChannelPaintArgs::Geometry, FSlateDrawElement::MakeLines(), UE::Sequencer::FTimeToPixelSpace::PixelToSeconds(), PreMultipliedAlpha, TArray< InElementType, InAllocatorType >::Reserve(), Seconds, FSequencerChannelPaintArgs::TimeToPixel, X, and Y.
DrawKeys_Raw()
template<typename ChannelContainerType> virtual void TPerlinNoiseChannelInterface< ChannelContainerType >::DrawKeys_Raw (FMovieSceneChannel * Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection * InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams) const inline override virtual
Gather information on how to draw the specified keys.
Parameters
Channel The channel to query
InKeyHandles Array of handles to duplicate
InOwner The section that owns the channel
OutKeyDrawParams Pre-sized array to receive key draw parameters. Invalid key handles will not be assigned to this array. Must match size of InKeyHandles.
Implements ISequencerChannelInterface.
Definition at line 150 of file PerlinNoiseChannelInterface.h.
ExtendKeyMenu_Raw()
template<typename ChannelContainerType> virtual void TPerlinNoiseChannelInterface< ChannelContainerType >::ExtendKeyMenu_Raw (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > MenuExtender, TArrayView< const FExtendKeyMenuParams > Parameters, TWeakPtr< ISequencer > InSequencer) const inline override virtual
Extend the key context menu.
Parameters
MenuBuilder The menu builder used to create this context menu
Channels Array of channels and handles that are being shown in the context menu
InSequencer The currently active sequencer
Implements ISequencerChannelInterface.
Definition at line 128 of file PerlinNoiseChannelInterface.h.
ExtendSectionMenu_Raw()
template<typename ChannelContainerType> virtual void TPerlinNoiseChannelInterface< ChannelContainerType >::ExtendSectionMenu_Raw (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > MenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const inline override virtual
Extend the section context menu.
Parameters
MenuBuilder The menu builder used to create this context menu
MenuExtender The menu extender to use
Channels Array of type specific channels that exist in the selected sections
Sections Array of sections being shown on the context menu
InWeakSequencer The currently active sequencer
Implements ISequencerChannelInterface.
Definition at line 132 of file PerlinNoiseChannelInterface.h.
References EExtensionHook::First, MakeShared(), and TEXT.
ExtendSidebarMenu_Raw()
template<typename ChannelContainerType> virtual TSharedPtr< ISidebarChannelExtension > TPerlinNoiseChannelInterface< ChannelContainerType >::ExtendSidebarMenu_Raw (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const inline override virtual
Extend the section sidebar menu.
Parameters
MenuBuilder The menu builder used to create this context menu
InMenuExtender The menu extender to use
InChannels Array of type specific channels that exist in the selected sections
InWeakSections Array of sections being shown on the context menu
InWeakSequencer The currently active sequencer
Implements ISequencerChannelInterface.
Definition at line 143 of file PerlinNoiseChannelInterface.h.
References MakeShared().
GetKeyStruct_Raw()
template<typename ChannelContainerType> virtual TSharedPtr< FStructOnScope > TPerlinNoiseChannelInterface< ChannelContainerType >::GetKeyStruct_Raw (FMovieSceneChannelHandle Channel, FKeyHandle KeyHandle) const inline override virtual
Get an editable key struct for the specified key.
Parameters
Channel The channel on which the key resides
KeyHandle Handle of the key to get
Returns
A shared editable key struct
Implements ISequencerChannelInterface.
Definition at line 101 of file PerlinNoiseChannelInterface.h.
PasteKeys_Raw()
template<typename ChannelContainerType> virtual void TPerlinNoiseChannelInterface< ChannelContainerType >::PasteKeys_Raw (FMovieSceneChannel * Channel, UMovieSceneSection * Section, const FMovieSceneClipboardKeyTrack & KeyTrack, const FMovieSceneClipboardEnvironment & SrcEnvironment, const FSequencerPasteEnvironment & DstEnvironment, TArray< FKeyHandle > & OutPastedKeys) const inline override virtual
Paste the specified key track into the specified channel.
Parameters
Channel The channel to copy from
Section The section that owns the channel
KeyTrack The source clipboard data to paste
SrcEnvironment The environment the source data was copied from
DstEnvironment The environment we're pasting into
OutPastedKeys Array to receive key handles for any pasted keys
Implements ISequencerChannelInterface.
Definition at line 97 of file PerlinNoiseChannelInterface.h.
ShouldShowCurve_Raw()
template<typename ChannelContainerType> virtual bool TPerlinNoiseChannelInterface< ChannelContainerType >::ShouldShowCurve_Raw (const FMovieSceneChannel * Channel, UMovieSceneSection * InSection) const inline override virtual
Whether this channel should draw a curve on its editor UI.
Parameters
Channel The channel to query
InSection The section that owns the channel
Returns
true to show the curve on the UI, false otherwise
Implements ISequencerChannelInterface.
Definition at line 154 of file PerlinNoiseChannelInterface.h.
SupportsCurveEditorModels_Raw()
template<typename ChannelContainerType> virtual bool TPerlinNoiseChannelInterface< ChannelContainerType >::SupportsCurveEditorModels_Raw (const FMovieSceneChannelHandle & InChannel) const inline override virtual
Whether this channel supports curve models.
Implements ISequencerChannelInterface.
Definition at line 159 of file PerlinNoiseChannelInterface.h.
The documentation for this struct was generated from the following file:
Editor/MovieSceneTools/Public/Channels/PerlinNoiseChannelInterface.h