Unreal Engine 5.6 C++ API: FPrimitiveSceneShaderData Struct Reference
FPrimitiveSceneShaderData Struct Reference
#include "PrimitiveSceneShaderData.h"
Public Member Functions
FPrimitiveSceneShaderData ()
FPrimitiveSceneShaderData (const FPrimitiveSceneProxy *RESTRICT Proxy)
FPrimitiveSceneShaderData (const FPrimitiveUniformShaderParameters &PrimitiveUniformShaderParameters)
void Setup (const FPrimitiveUniformShaderParameters &PrimitiveUniformShaderParameters)
Static Public Member Functions
static void BuildDataFromProxy (const FPrimitiveSceneProxy *RESTRICT Proxy, FVector4f *RESTRICT OutData)
Directly construct the data from the proxy into an output array, removing the need to construct an intermediate.
static void Setup (const FPrimitiveUniformShaderParameters &PrimitiveUniformShaderParameters, FVector4f *RESTRICT OutData)
Data Fields
TStaticArray< FVector4f, DataStrideInFloat4s > Data
Static Public Attributes
static const uint32 DataStrideInFloat4s = PRIMITIVE_SCENE_DATA_STRIDE
Detailed Description
Definition at line 17 of file PrimitiveSceneShaderData.h.
Constructor & Destructor Documentation
FPrimitiveSceneShaderData() [1/3]
FPrimitiveSceneShaderData::FPrimitiveSceneShaderData () inline
Definition at line 23 of file PrimitiveSceneShaderData.h.
References Data, GetIdentityPrimitiveParameters(), InPlace, NoInit, and Setup().
FPrimitiveSceneShaderData() [2/3]
FPrimitiveSceneShaderData::FPrimitiveSceneShaderData (const FPrimitiveUniformShaderParameters & PrimitiveUniformShaderParameters) inline explicit
Definition at line 29 of file PrimitiveSceneShaderData.h.
References Data, InPlace, NoInit, and Setup().
FPrimitiveSceneShaderData() [3/3]
FPrimitiveSceneShaderData::FPrimitiveSceneShaderData (const FPrimitiveSceneProxy *RESTRICT Proxy)
References RESTRICT.
Member Function Documentation
BuildDataFromProxy()
void FPrimitiveSceneShaderData::BuildDataFromProxy (const FPrimitiveSceneProxy *RESTRICT Proxy, FVector4f *RESTRICT OutData) static
Directly construct the data from the proxy into an output array, removing the need to construct an intermediate.
References RESTRICT.
Setup() [1/2]
void FPrimitiveSceneShaderData::Setup (const FPrimitiveUniformShaderParameters & PrimitiveUniformShaderParameters)
Setup() [2/2]
void FPrimitiveSceneShaderData::Setup (const FPrimitiveUniformShaderParameters & PrimitiveUniformShaderParameters, FVector4f *RESTRICT OutData) static
References RESTRICT.
Referenced by FPrimitiveSceneShaderData(), and FPrimitiveSceneShaderData().
Field Documentation
Data
TStaticArray<FVector4f, DataStrideInFloat4s> FPrimitiveSceneShaderData::Data
Definition at line 21 of file PrimitiveSceneShaderData.h.
Referenced by FPrimitiveSceneShaderData(), and FPrimitiveSceneShaderData().
DataStrideInFloat4s
const uint32 FPrimitiveSceneShaderData::DataStrideInFloat4s = PRIMITIVE_SCENE_DATA_STRIDE static
Definition at line 19 of file PrimitiveSceneShaderData.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/PrimitiveSceneShaderData.h