Unreal Engine 5.6 C++ API: UE::MovieScene::FBuiltInComponentTypes Struct Reference
UE::MovieScene::FBuiltInComponentTypes Struct Reference
Pre-defined built in component types.
#include "BuiltInComponentTypes.h"
Public Member Functions
MOVIESCENE_API ~FBuiltInComponentTypes ()
MOVIESCENE_API FComponentTypeID GetBaseValueComponentType (const FComponentTypeID &InResultComponentType)
UE_DEPRECATED (5.5, "Please use GenericObjectBinding and BoundObjectResolver") TComponentTypeID< FGuid > SceneComponentBinding
Static Public Member Functions
static MOVIESCENE_API void Destroy ()
static MOVIESCENE_API FBuiltInComponentTypes * Get ()
static FORCEINLINE bool IsBoundObjectGarbage (UObject *InObject)
Data Fields
TComponentTypeID< uint8 > BaseByte
TComponentTypeID< double > BaseDouble [9]
TComponentTypeID< int32 > BaseInteger
TComponentTypeID< double > BaseValueEvalSeconds
TComponentTypeID< FFrameTime > BaseValueEvalTime
TComponentTypeID< FMovieSceneBindingLifetimeComponentData > BindingLifetime
TComponentTypeID< FMovieSceneBlendChannelID > BlendChannelInput
TComponentTypeID< FMovieSceneBlendChannelID > BlendChannelOutput
TComponentTypeID< TSubclassOf< UMovieSceneBlenderSystem > > BlenderType
A blender type that should be used for blending this entity.
TComponentTypeID< int32 > BlendingOrder
Value that is used to sort blending order.
TComponentTypeID< FSourceBoolChannel > BoolChannel
TComponentTypeID< bool > BoolResult
TComponentTypeID< UObject * > BoundObject
A bound object ptr component that defines the object being animated.
TComponentTypeID< FObjectKey > BoundObjectKey
TComponentTypeID< FBoundObjectResolver > BoundObjectResolver
TComponentTypeID< FSourceByteChannel > ByteChannel
TComponentTypeID< uint8 > ByteResult
TComponentTypeID< Interpolation::FCachedInterpolation > CachedInterpolation [9]
TComponentTypeID< Interpolation::FCachedInterpolation > CachedWeightChannelInterpolation
TComponentTypeID< TObjectPtr< const UMovieSceneCondition > > Condition
TComponentTypeID< FCustomPropertyIndex > CustomPropertyIndex
TComponentTypeID< FSourceDoubleChannel > DoubleChannel [9]
TComponentTypeID< double > DoubleResult [9]
TComponentTypeID< FEasingComponentData > Easing
TComponentTypeID< double > EasingResult
TComponentTypeID< double > EvalSeconds
TComponentTypeID< FFrameTime > EvalTime
TComponentTypeID< FMovieSceneEvaluationHookComponent > EvaluationHook
TComponentTypeID< FEvaluationHookFlags > EvaluationHookFlags
TComponentTypeID< uint16 > FastPropertyOffset
FComponentMask FinishedMask
TComponentTypeID< FSourceFloatChannel > FloatChannel [9]
TComponentTypeID< FGuid > GenericObjectBinding
TComponentTypeID< FEntityGroupID > Group
TComponentTypeID< int16 > HierarchicalBias
TComponentTypeID< FHierarchicalBlendTarget > HierarchicalBlendTarget
TComponentTypeID< uint16 > HierarchicalEasingChannel
TComponentTypeID< FMovieSceneSequenceID > HierarchicalEasingProvider
TComponentTypeID< FInitialValueIndex > InitialValueIndex
TComponentTypeID< FInstanceHandle > InstanceHandle
TComponentTypeID< FSourceIntegerChannel > IntegerChannel
TComponentTypeID< int32 > IntegerResult
struct {
TComponentTypeID< FInterrogationKey > InputKey
TComponentTypeID< FInterrogationInstance > Instance
TComponentTypeID< FInterrogationKey > OutputKey
} Interrogation
TComponentTypeID< FSourceObjectPathChannel > ObjectPathChannel
TComponentTypeID< FObjectComponent > ObjectResult
TComponentTypeID< FMovieSceneEntityID > ParentEntity
TComponentTypeID< FMovieScenePropertyBinding > PropertyBinding
FPropertyRegistry PropertyRegistry
FComponentMask RequiresInstantiationMask
Component mask where set bits denot component types that should trigger instantiation when present.
TComponentTypeID< FRootInstanceHandle > RootInstanceHandle
TComponentTypeID< FMovieSceneSequenceID > SequenceID
TComponentTypeID< TSharedPtr< FTrackInstancePropertyBindings > > SlowProperty
TComponentTypeID< FGuid > SpawnableBinding
TComponentTypeID< FSourceStringChannel > StringChannel
TComponentTypeID< FString > StringResult
struct {
FComponentTypeID CreatesEntities
} SymbolicTags
struct {
FComponentTypeID AbsoluteBlend
FComponentTypeID AdditiveAnimation
FComponentTypeID AdditiveBlend
FComponentTypeID AdditiveFromBaseBlend
FComponentTypeID AlwaysCacheInitialValue
FComponentTypeID BlendHierarchicalBias
FComponentTypeID DontOptimizeConstants
FComponentTypeID ExternalBlending
FComponentTypeID Finished
FComponentTypeID FixedTime
FComponentTypeID HasAssignedInitialValue
FComponentTypeID HasUnresolvedBinding
Tag that is added to imported entities with a GenericObjectBinding whose binding did not resolve.
FComponentTypeID Ignored
FComponentTypeID IgnoreHierarchicalBias
FComponentTypeID ImportedEntity
FComponentTypeID NeedsLink
FComponentTypeID NeedsUnlink
FComponentTypeID OldStyleSpawnable
FComponentTypeID OverrideBlend
FComponentTypeID PreRoll
FComponentTypeID RelativeBlend
FComponentTypeID RestoreState
FComponentTypeID Root
FComponentTypeID SectionPreRoll
FComponentTypeID SubInstance
} Tags
TComponentTypeID< FMovieSceneTrackInstanceComponent > TrackInstance
TComponentTypeID< FTrackInstanceInputComponent > TrackInstanceInput
TComponentTypeID< double > WeightAndEasingResult
TComponentTypeID< FSourceFloatChannel > WeightChannel
TComponentTypeID< double > WeightResult
Private Member Functions
MOVIESCENE_API FBuiltInComponentTypes ()
Private Attributes
TMap< FComponentTypeID, FComponentTypeID > ResultToBase
Detailed Description
Pre-defined built in component types.
Definition at line 559 of file BuiltInComponentTypes.h.
Constructor & Destructor Documentation
~FBuiltInComponentTypes()
MOVIESCENE_API UE::MovieScene::FBuiltInComponentTypes::~FBuiltInComponentTypes ()
FBuiltInComponentTypes()
MOVIESCENE_API UE::MovieScene::FBuiltInComponentTypes::FBuiltInComponentTypes () private
Referenced by Get().
Member Function Documentation
Destroy()
MOVIESCENE_API void UE::MovieScene::FBuiltInComponentTypes::Destroy () static
Get()
MOVIESCENE_API FBuiltInComponentTypes * UE::MovieScene::FBuiltInComponentTypes::Get () static
References FBuiltInComponentTypes().
Referenced by UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::TAddBoundMaterialMutationImpl(), UE::MovieScene::TPreAnimatedStateTaskParams< InputTypes >::TPreAnimatedStateTaskParams(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask(), UE::MovieScene::TOverlappingEntityTracker_WithGarbage< OutputType, InputTypes... >::CleanTaggedGarbage(), UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun(), UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::ProcessAllocation(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ProcessInvalidatedOutputs(), UE::MovieScene::FSystemInterrogator::QueryPropertyValues(), UE::MovieScene::FPropertyRecomposerImpl::RecomposeBlendOperational(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateFromComponents(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateUnlinkedOnly(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::VisitActiveAllocationImpl().
GetBaseValueComponentType()
MOVIESCENE_API FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::GetBaseValueComponentType (const FComponentTypeID & InResultComponentType)
IsBoundObjectGarbage()
FORCEINLINE bool UE::MovieScene::FBuiltInComponentTypes::IsBoundObjectGarbage (UObject * InObject) inline static
Definition at line 811 of file BuiltInComponentTypes.h.
References FORCEINLINE, UObjectBaseUtility::IsUnreachable(), and IsValidChecked().
Referenced by UE::MovieScene::FGarbageTraits::IsGarbage(), UE::MovieScene::FGarbageTraits::IsGarbage(), and UE::MovieScene::FGarbageTraits::IsGarbage().
UE_DEPRECATED()
UE::MovieScene::FBuiltInComponentTypes::UE_DEPRECATED (5. 5, "Please use GenericObjectBinding and BoundObjectResolver")
Field Documentation
AbsoluteBlend
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::AbsoluteBlend
Definition at line 747 of file BuiltInComponentTypes.h.
AdditiveAnimation
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::AdditiveAnimation
Definition at line 753 of file BuiltInComponentTypes.h.
AdditiveBlend
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::AdditiveBlend
Definition at line 749 of file BuiltInComponentTypes.h.
AdditiveFromBaseBlend
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::AdditiveFromBaseBlend
Definition at line 750 of file BuiltInComponentTypes.h.
AlwaysCacheInitialValue
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::AlwaysCacheInitialValue
Definition at line 780 of file BuiltInComponentTypes.h.
BaseByte
TComponentTypeID<uint8> UE::MovieScene::FBuiltInComponentTypes::BaseByte
Definition at line 638 of file BuiltInComponentTypes.h.
BaseDouble
TComponentTypeID<double> UE::MovieScene::FBuiltInComponentTypes::BaseDouble[9]
Definition at line 675 of file BuiltInComponentTypes.h.
BaseInteger
TComponentTypeID<int32> UE::MovieScene::FBuiltInComponentTypes::BaseInteger
Definition at line 647 of file BuiltInComponentTypes.h.
BaseValueEvalSeconds
TComponentTypeID<double> UE::MovieScene::FBuiltInComponentTypes::BaseValueEvalSeconds
Definition at line 679 of file BuiltInComponentTypes.h.
BaseValueEvalTime
TComponentTypeID<FFrameTime> UE::MovieScene::FBuiltInComponentTypes::BaseValueEvalTime
Definition at line 678 of file BuiltInComponentTypes.h.
BindingLifetime
TComponentTypeID<FMovieSceneBindingLifetimeComponentData> UE::MovieScene::FBuiltInComponentTypes::BindingLifetime
Definition at line 624 of file BuiltInComponentTypes.h.
BlendChannelInput
TComponentTypeID<FMovieSceneBlendChannelID> UE::MovieScene::FBuiltInComponentTypes::BlendChannelInput
Definition at line 598 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), and UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule().
BlendChannelOutput
TComponentTypeID<FMovieSceneBlendChannelID> UE::MovieScene::FBuiltInComponentTypes::BlendChannelOutput
Definition at line 600 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), and UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule().
BlenderType
TComponentTypeID<TSubclassOf<UMovieSceneBlenderSystem> > UE::MovieScene::FBuiltInComponentTypes::BlenderType
A blender type that should be used for blending this entity.
Definition at line 709 of file BuiltInComponentTypes.h.
BlendHierarchicalBias
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::BlendHierarchicalBias
Definition at line 745 of file BuiltInComponentTypes.h.
BlendingOrder
TComponentTypeID<int32> UE::MovieScene::FBuiltInComponentTypes::BlendingOrder
Value that is used to sort blending order.
Definition at line 712 of file BuiltInComponentTypes.h.
BoolChannel
TComponentTypeID<FSourceBoolChannel> UE::MovieScene::FBuiltInComponentTypes::BoolChannel
Definition at line 650 of file BuiltInComponentTypes.h.
BoolResult
TComponentTypeID<bool> UE::MovieScene::FBuiltInComponentTypes::BoolResult
Definition at line 629 of file BuiltInComponentTypes.h.
BoundObject
TComponentTypeID<UObject*> UE::MovieScene::FBuiltInComponentTypes::BoundObject
A bound object ptr component that defines the object being animated.
This ptr is explicitly hidden from the reference graph and cleaned up after a garbage collection pass if it becomes invalid by checking the BoundObjectKey component that must exist alongside it
Definition at line 581 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
BoundObjectKey
TComponentTypeID<FObjectKey> UE::MovieScene::FBuiltInComponentTypes::BoundObjectKey
Definition at line 582 of file BuiltInComponentTypes.h.
BoundObjectResolver
TComponentTypeID<FBoundObjectResolver> UE::MovieScene::FBuiltInComponentTypes::BoundObjectResolver
Definition at line 614 of file BuiltInComponentTypes.h.
ByteChannel
TComponentTypeID<FSourceByteChannel> UE::MovieScene::FBuiltInComponentTypes::ByteChannel
Definition at line 632 of file BuiltInComponentTypes.h.
ByteResult
TComponentTypeID<uint8> UE::MovieScene::FBuiltInComponentTypes::ByteResult
Definition at line 635 of file BuiltInComponentTypes.h.
CachedInterpolation
TComponentTypeID<Interpolation::FCachedInterpolation> UE::MovieScene::FBuiltInComponentTypes::CachedInterpolation[9]
Definition at line 662 of file BuiltInComponentTypes.h.
CachedWeightChannelInterpolation
TComponentTypeID<Interpolation::FCachedInterpolation> UE::MovieScene::FBuiltInComponentTypes::CachedWeightChannelInterpolation
Definition at line 666 of file BuiltInComponentTypes.h.
Condition
TComponentTypeID<TObjectPtr<const UMovieSceneCondition> > UE::MovieScene::FBuiltInComponentTypes::Condition
Definition at line 725 of file BuiltInComponentTypes.h.
CreatesEntities
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::CreatesEntities
Definition at line 800 of file BuiltInComponentTypes.h.
CustomPropertyIndex
TComponentTypeID<FCustomPropertyIndex> UE::MovieScene::FBuiltInComponentTypes::CustomPropertyIndex
Definition at line 730 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
DontOptimizeConstants
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::DontOptimizeConstants
Definition at line 782 of file BuiltInComponentTypes.h.
DoubleChannel
TComponentTypeID<FSourceDoubleChannel> UE::MovieScene::FBuiltInComponentTypes::DoubleChannel[9]
Definition at line 656 of file BuiltInComponentTypes.h.
DoubleResult
TComponentTypeID<double> UE::MovieScene::FBuiltInComponentTypes::DoubleResult[9]
Definition at line 672 of file BuiltInComponentTypes.h.
Easing
TComponentTypeID<FEasingComponentData> UE::MovieScene::FBuiltInComponentTypes::Easing
Definition at line 694 of file BuiltInComponentTypes.h.
EasingResult
TComponentTypeID<double> UE::MovieScene::FBuiltInComponentTypes::EasingResult
Definition at line 683 of file BuiltInComponentTypes.h.
EvalSeconds
TComponentTypeID<double> UE::MovieScene::FBuiltInComponentTypes::EvalSeconds
Definition at line 592 of file BuiltInComponentTypes.h.
EvalTime
TComponentTypeID<FFrameTime> UE::MovieScene::FBuiltInComponentTypes::EvalTime
Definition at line 590 of file BuiltInComponentTypes.h.
EvaluationHook
TComponentTypeID<FMovieSceneEvaluationHookComponent> UE::MovieScene::FBuiltInComponentTypes::EvaluationHook
Definition at line 721 of file BuiltInComponentTypes.h.
EvaluationHookFlags
TComponentTypeID<FEvaluationHookFlags> UE::MovieScene::FBuiltInComponentTypes::EvaluationHookFlags
Definition at line 723 of file BuiltInComponentTypes.h.
ExternalBlending
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::ExternalBlending
Definition at line 778 of file BuiltInComponentTypes.h.
FastPropertyOffset
TComponentTypeID<uint16> UE::MovieScene::FBuiltInComponentTypes::FastPropertyOffset
Definition at line 733 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
Finished
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::Finished
Definition at line 774 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask().
FinishedMask
FComponentMask UE::MovieScene::FBuiltInComponentTypes::FinishedMask
Definition at line 803 of file BuiltInComponentTypes.h.
FixedTime
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::FixedTime
Definition at line 769 of file BuiltInComponentTypes.h.
FloatChannel
TComponentTypeID<FSourceFloatChannel> UE::MovieScene::FBuiltInComponentTypes::FloatChannel[9]
Definition at line 653 of file BuiltInComponentTypes.h.
GenericObjectBinding
TComponentTypeID<FGuid> UE::MovieScene::FBuiltInComponentTypes::GenericObjectBinding
Definition at line 611 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), and UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit().
Group
TComponentTypeID<FEntityGroupID> UE::MovieScene::FBuiltInComponentTypes::Group
Definition at line 594 of file BuiltInComponentTypes.h.
HasAssignedInitialValue
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::HasAssignedInitialValue
Definition at line 761 of file BuiltInComponentTypes.h.
HasUnresolvedBinding
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::HasUnresolvedBinding
Tag that is added to imported entities with a GenericObjectBinding whose binding did not resolve.
Definition at line 759 of file BuiltInComponentTypes.h.
HierarchicalBias
TComponentTypeID<int16> UE::MovieScene::FBuiltInComponentTypes::HierarchicalBias
Definition at line 602 of file BuiltInComponentTypes.h.
HierarchicalBlendTarget
TComponentTypeID<FHierarchicalBlendTarget> UE::MovieScene::FBuiltInComponentTypes::HierarchicalBlendTarget
Definition at line 703 of file BuiltInComponentTypes.h.
HierarchicalEasingChannel
TComponentTypeID<uint16> UE::MovieScene::FBuiltInComponentTypes::HierarchicalEasingChannel
Definition at line 697 of file BuiltInComponentTypes.h.
HierarchicalEasingProvider
TComponentTypeID<FMovieSceneSequenceID> UE::MovieScene::FBuiltInComponentTypes::HierarchicalEasingProvider
Definition at line 700 of file BuiltInComponentTypes.h.
Ignored
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::Ignored
Definition at line 776 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
IgnoreHierarchicalBias
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::IgnoreHierarchicalBias
Definition at line 744 of file BuiltInComponentTypes.h.
ImportedEntity
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::ImportedEntity
Definition at line 763 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun().
InitialValueIndex
TComponentTypeID<FInitialValueIndex> UE::MovieScene::FBuiltInComponentTypes::InitialValueIndex
Definition at line 604 of file BuiltInComponentTypes.h.
InputKey
TComponentTypeID<FInterrogationKey> UE::MovieScene::FBuiltInComponentTypes::InputKey
Definition at line 793 of file BuiltInComponentTypes.h.
Instance
TComponentTypeID<FInterrogationInstance> UE::MovieScene::FBuiltInComponentTypes::Instance
Definition at line 794 of file BuiltInComponentTypes.h.
InstanceHandle
TComponentTypeID<FInstanceHandle> UE::MovieScene::FBuiltInComponentTypes::InstanceHandle
Definition at line 584 of file BuiltInComponentTypes.h.
IntegerChannel
TComponentTypeID<FSourceIntegerChannel> UE::MovieScene::FBuiltInComponentTypes::IntegerChannel
Definition at line 641 of file BuiltInComponentTypes.h.
IntegerResult
TComponentTypeID<int32> UE::MovieScene::FBuiltInComponentTypes::IntegerResult
Definition at line 644 of file BuiltInComponentTypes.h.
[struct]
struct { ... } UE::MovieScene::FBuiltInComponentTypes::Interrogation
NeedsLink
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::NeedsLink
Definition at line 755 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPreAnimatedStateTaskParams< InputTypes >::TPreAnimatedStateTaskParams(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun(), UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::ProcessAllocation(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateFromComponents().
NeedsUnlink
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::NeedsUnlink
Definition at line 756 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask(), UE::MovieScene::TOverlappingEntityTracker_WithGarbage< OutputType, InputTypes... >::CleanTaggedGarbage(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun(), UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::ProcessAllocation(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateFromComponents(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateUnlinkedOnly().
ObjectPathChannel
TComponentTypeID<FSourceObjectPathChannel> UE::MovieScene::FBuiltInComponentTypes::ObjectPathChannel
Definition at line 669 of file BuiltInComponentTypes.h.
ObjectResult
TComponentTypeID<FObjectComponent> UE::MovieScene::FBuiltInComponentTypes::ObjectResult
Definition at line 689 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun().
OldStyleSpawnable
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::OldStyleSpawnable
Definition at line 787 of file BuiltInComponentTypes.h.
OutputKey
TComponentTypeID<FInterrogationKey> UE::MovieScene::FBuiltInComponentTypes::OutputKey
Definition at line 795 of file BuiltInComponentTypes.h.
OverrideBlend
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::OverrideBlend
Definition at line 751 of file BuiltInComponentTypes.h.
ParentEntity
TComponentTypeID<FMovieSceneEntityID> UE::MovieScene::FBuiltInComponentTypes::ParentEntity
Definition at line 575 of file BuiltInComponentTypes.h.
PreRoll
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::PreRoll
Definition at line 772 of file BuiltInComponentTypes.h.
PropertyBinding
TComponentTypeID<FMovieScenePropertyBinding> UE::MovieScene::FBuiltInComponentTypes::PropertyBinding
Definition at line 608 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), and UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit().
PropertyRegistry
FPropertyRegistry UE::MovieScene::FBuiltInComponentTypes::PropertyRegistry
Definition at line 565 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::FPropertyRecomposerImpl::RecomposeBlendOperational().
RelativeBlend
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::RelativeBlend
Definition at line 748 of file BuiltInComponentTypes.h.
RequiresInstantiationMask
FComponentMask UE::MovieScene::FBuiltInComponentTypes::RequiresInstantiationMask
Component mask where set bits denot component types that should trigger instantiation when present.
After instantiation, these components will be removed from any entities to prevent instantiation being run constantly
Definition at line 573 of file BuiltInComponentTypes.h.
RestoreState
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::RestoreState
Definition at line 741 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ProcessInvalidatedOutputs().
ResultToBase
TMap<FComponentTypeID, FComponentTypeID> UE::MovieScene::FBuiltInComponentTypes::ResultToBase private
Definition at line 822 of file BuiltInComponentTypes.h.
Root
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::Root
Definition at line 767 of file BuiltInComponentTypes.h.
RootInstanceHandle
TComponentTypeID<FRootInstanceHandle> UE::MovieScene::FBuiltInComponentTypes::RootInstanceHandle
Definition at line 586 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask().
SectionPreRoll
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::SectionPreRoll
Definition at line 771 of file BuiltInComponentTypes.h.
SequenceID
TComponentTypeID<FMovieSceneSequenceID> UE::MovieScene::FBuiltInComponentTypes::SequenceID
Definition at line 588 of file BuiltInComponentTypes.h.
SlowProperty
TComponentTypeID<TSharedPtr<FTrackInstancePropertyBindings> > UE::MovieScene::FBuiltInComponentTypes::SlowProperty
Definition at line 736 of file BuiltInComponentTypes.h.
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
SpawnableBinding
TComponentTypeID<FGuid> UE::MovieScene::FBuiltInComponentTypes::SpawnableBinding
Definition at line 621 of file BuiltInComponentTypes.h.
StringChannel
TComponentTypeID<FSourceStringChannel> UE::MovieScene::FBuiltInComponentTypes::StringChannel
Definition at line 659 of file BuiltInComponentTypes.h.
StringResult
TComponentTypeID<FString> UE::MovieScene::FBuiltInComponentTypes::StringResult
Definition at line 686 of file BuiltInComponentTypes.h.
SubInstance
FComponentTypeID UE::MovieScene::FBuiltInComponentTypes::SubInstance
Definition at line 765 of file BuiltInComponentTypes.h.
[struct]
struct { ... } UE::MovieScene::FBuiltInComponentTypes::SymbolicTags
[struct]
struct { ... } UE::MovieScene::FBuiltInComponentTypes::Tags
Referenced by UE::MovieScene::TPreAnimatedStateTaskParams< InputTypes >::TPreAnimatedStateTaskParams(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask(), UE::MovieScene::TOverlappingEntityTracker_WithGarbage< OutputType, InputTypes... >::CleanTaggedGarbage(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun(), UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::ProcessAllocation(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ProcessInvalidatedOutputs(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateFromComponents(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateUnlinkedOnly().
TrackInstance
TComponentTypeID<FMovieSceneTrackInstanceComponent> UE::MovieScene::FBuiltInComponentTypes::TrackInstance
Definition at line 715 of file BuiltInComponentTypes.h.
TrackInstanceInput
TComponentTypeID<FTrackInstanceInputComponent> UE::MovieScene::FBuiltInComponentTypes::TrackInstanceInput
Definition at line 718 of file BuiltInComponentTypes.h.
WeightAndEasingResult
TComponentTypeID<double> UE::MovieScene::FBuiltInComponentTypes::WeightAndEasingResult
Definition at line 706 of file BuiltInComponentTypes.h.
WeightChannel
TComponentTypeID<FSourceFloatChannel> UE::MovieScene::FBuiltInComponentTypes::WeightChannel
Definition at line 665 of file BuiltInComponentTypes.h.
WeightResult
TComponentTypeID<double> UE::MovieScene::FBuiltInComponentTypes::WeightResult
Definition at line 682 of file BuiltInComponentTypes.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/BuiltInComponentTypes.h