Unreal Engine 5.6 C++ API: TInputUnifiedDelegate< DelegateType, DynamicDelegateType > Struct Template Reference
TInputUnifiedDelegate< DelegateType, DynamicDelegateType > Struct Template Reference
Utility delegate class to allow binding to either a C++ function or a blueprint script delegate.
#include "InputComponent.h"
Public Member Functions
TInputUnifiedDelegate ()
TInputUnifiedDelegate (DelegateType D)
TInputUnifiedDelegate (DynamicDelegateType D)
void BindDelegate (UObject *Object, const FName FuncName)
Binds a dynamic delegate and unbinds any bound native delegate.
template<class UserClass>
void BindDelegate (UserClass *Object, typename DelegateType::template TMethodPtr< UserClass > Func)
Binds a native delegate and unbinds any bound dynamic delegate.
const DelegateType & GetDelegate () const
Returns a const reference to the Function Delegate.
DelegateType & GetDelegateForManualSet ()
Returns a reference to the native delegate and unbinds any bound dynamic delegate.
const DynamicDelegateType & GetDynamicDelegate () const
Returns a const reference to the Dynamic Function Delegate.
bool IsBound () const
Returns if either the native or dynamic delegate is bound.
bool IsBoundToObject (void const *Object) const
Returns if either the native or dynamic delegate is bound to an object.
void Unbind ()
Unbinds any bound delegates.
Protected Attributes
TSharedPtr< DelegateType > FuncDelegate
Holds the delegate to call.
TSharedPtr< DynamicDelegateType > FuncDynDelegate
Holds the dynamic delegate to call.
Static Protected Attributes
static const DelegateType UnboundDelegate
static const DynamicDelegateType UnboundDynamicDelegate
Detailed Description
template<class DelegateType, class DynamicDelegateType>
struct TInputUnifiedDelegate< DelegateType, DynamicDelegateType >
Utility delegate class to allow binding to either a C++ function or a blueprint script delegate.
Definition at line 16 of file InputComponent.h.
Constructor & Destructor Documentation
TInputUnifiedDelegate() [1/3]
template<class DelegateType, class DynamicDelegateType> TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::TInputUnifiedDelegate () inline
Definition at line 18 of file InputComponent.h.
TInputUnifiedDelegate() [2/3]
template<class DelegateType, class DynamicDelegateType> TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::TInputUnifiedDelegate (DelegateType D) inline
Definition at line 19 of file InputComponent.h.
References FuncDelegate, MakeShared(), and MoveTemp().
TInputUnifiedDelegate() [3/3]
template<class DelegateType, class DynamicDelegateType> TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::TInputUnifiedDelegate (DynamicDelegateType D) inline
Definition at line 20 of file InputComponent.h.
References FuncDynDelegate, MakeShared(), and MoveTemp().
Member Function Documentation
BindDelegate() [1/2]
template<class DelegateType, class DynamicDelegateType> void TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::BindDelegate (UObject * Object, const FName FuncName) inline
Binds a dynamic delegate and unbinds any bound native delegate.
Definition at line 58 of file InputComponent.h.
References FuncDelegate, FuncDynDelegate, MakeShared(), and Object.
BindDelegate() [2/2]
template<class DelegateType, class DynamicDelegateType> template<class UserClass> void TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::BindDelegate (UserClass * Object, typename DelegateType::template TMethodPtr< UserClass > Func) inline
Binds a native delegate and unbinds any bound dynamic delegate.
Definition at line 51 of file InputComponent.h.
References FuncDelegate, FuncDynDelegate, MakeShared(), and Object.
Referenced by UInputComponent::BindAxis(), UInputComponent::BindAxisKey(), UInputComponent::BindGesture(), UInputComponent::BindTouch(), and UInputComponent::BindVectorAxis().
GetDelegate()
template<class DelegateType, class DynamicDelegateType> const DelegateType & TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::GetDelegate () const inline
Returns a const reference to the Function Delegate.
Definition at line 81 of file InputComponent.h.
References FuncDelegate, and UnboundDelegate.
GetDelegateForManualSet()
template<class DelegateType, class DynamicDelegateType> DelegateType & TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::GetDelegateForManualSet () inline
Returns a reference to the native delegate and unbinds any bound dynamic delegate.
Definition at line 66 of file InputComponent.h.
References FuncDelegate, FuncDynDelegate, and MakeShared().
GetDynamicDelegate()
template<class DelegateType, class DynamicDelegateType> const DynamicDelegateType & TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::GetDynamicDelegate () const inline
Returns a const reference to the Dynamic Function Delegate.
Definition at line 87 of file InputComponent.h.
References FuncDynDelegate, and UnboundDynamicDelegate.
IsBound()
template<class DelegateType, class DynamicDelegateType> bool TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::IsBound () const inline
Returns if either the native or dynamic delegate is bound.
Definition at line 23 of file InputComponent.h.
References FuncDelegate, and FuncDynDelegate.
IsBoundToObject()
template<class DelegateType, class DynamicDelegateType> bool TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::IsBoundToObject (void const * Object) const inline
Returns if either the native or dynamic delegate is bound to an object.
Definition at line 29 of file InputComponent.h.
References FuncDelegate, FuncDynDelegate, and Object.
Unbind()
template<class DelegateType, class DynamicDelegateType> void TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::Unbind () inline
Unbinds any bound delegates.
Definition at line 74 of file InputComponent.h.
References FuncDelegate, and FuncDynDelegate.
Field Documentation
FuncDelegate
template<class DelegateType, class DynamicDelegateType> TSharedPtr<DelegateType> TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::FuncDelegate protected
Holds the delegate to call.
Definition at line 94 of file InputComponent.h.
Referenced by TInputUnifiedDelegate(), BindDelegate(), BindDelegate(), GetDelegate(), GetDelegateForManualSet(), IsBound(), IsBoundToObject(), and Unbind().
FuncDynDelegate
template<class DelegateType, class DynamicDelegateType> TSharedPtr<DynamicDelegateType> TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::FuncDynDelegate protected
Holds the dynamic delegate to call.
Definition at line 96 of file InputComponent.h.
Referenced by TInputUnifiedDelegate(), BindDelegate(), BindDelegate(), GetDelegateForManualSet(), GetDynamicDelegate(), IsBound(), IsBoundToObject(), and Unbind().
UnboundDelegate
template<class DelegateType, class DynamicDelegateType> const DelegateType TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::UnboundDelegate static protected
Definition at line 98 of file InputComponent.h.
Referenced by GetDelegate().
UnboundDynamicDelegate
template<class DelegateType, class DynamicDelegateType> const DynamicDelegateType TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::UnboundDynamicDelegate static protected
Definition at line 99 of file InputComponent.h.
Referenced by GetDynamicDelegate().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Components/InputComponent.h