Unreal Engine 5.6 C++ API: FSquare2DGridHelper::FGrid2D Struct Reference
FSquare2DGridHelper::FGrid2D Struct Reference
#include "RuntimeSpatialHashGridHelper.h"
Public Member Functions
FGrid2D (const FVector2D &InOrigin, int64 InCellSize, int64 InGridSize)
int32 ForEachIntersectingCells (const FBox &InBox, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const
int32 ForEachIntersectingCells (const FSphere &InSphere, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const
Runs a function on all intersecting cells for the provided sphere.
int32 ForEachIntersectingCells (const FSphericalSector &InShape, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const
Runs a function on all intersecting cells for the provided spherical sector.
int32 ForEachIntersectingCellsBreakable (const FBox &InBox, TFunctionRef< bool(const FGridCellCoord2 &)> InOperation) const
Runs a function on all intersecting cells for the provided box.
bool GetCellBounds (const FGridCellCoord2 &InCoords, FBox2D &OutBounds, bool bCheckIsValidCoord=true) const
Returns the cell bounds.
bool GetCellBounds (int64 InIndex, FBox2D &OutBounds) const
Returns the cell bounds.
bool GetCellCoords (const FBox2D &InBounds2D, FGridCellCoord2 &OutMinCellCoords, FGridCellCoord2 &OutMaxCellCoords) const
Returns the cells coordinates of the provided box.
bool GetCellCoords (const FVector2D &InPos, FGridCellCoord2 &OutCoords) const
Returns the cell coordinates of the provided position.
bool GetCellIndex (const FGridCellCoord2 &InCoords, uint64 &OutIndex) const
Returns the cell index of the provided coords.
bool GetCellIndex (const FVector &InPos, uint64 &OutIndex) const
Returns the cell index of the provided position.
int32 GetNumIntersectingCells (const FBox &InBox) const
Get the number of intersecting cells of the provided box.
bool IsValidCoords (const FGridCellCoord2 &InCoords) const
Validate that the coordinates fit the grid size.
Data Fields
int64 CellSize
int64 GridSize
FVector2D Origin
Private Member Functions
bool DoesCircleSectorIntersectsCell (const FGridCellCoord2 &Coords, const FSphericalSector &InShape) const
Detailed Description
Definition at line 28 of file RuntimeSpatialHashGridHelper.h.
Constructor & Destructor Documentation
FGrid2D()
FSquare2DGridHelper::FGrid2D::FGrid2D (const FVector2D & InOrigin, int64 InCellSize, int64 InGridSize) inline
Definition at line 34 of file RuntimeSpatialHashGridHelper.h.
References CellSize, GridSize, FSquare2DGridHelper::InCellSize, FSquare2DGridHelper::InOrigin, and Origin.
Referenced by FSquare2DGridHelper::FGridLevel::FGridLevel().
Member Function Documentation
DoesCircleSectorIntersectsCell()
bool FSquare2DGridHelper::FGrid2D::DoesCircleSectorIntersectsCell (const FGridCellCoord2 & Coords, const FSphericalSector & InShape) const private
ForEachIntersectingCells() [1/3]
int32 FSquare2DGridHelper::FGrid2D::ForEachIntersectingCells (const FBox & InBox, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const inline
Definition at line 218 of file RuntimeSpatialHashGridHelper.h.
References ForEachIntersectingCellsBreakable(), and Vector.
Referenced by ForEachIntersectingCells().
ForEachIntersectingCells() [2/3]
int32 FSquare2DGridHelper::FGrid2D::ForEachIntersectingCells (const FSphere & InSphere, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const inline
Runs a function on all intersecting cells for the provided sphere.
Returns
the number of intersecting cells
Definition at line 228 of file RuntimeSpatialHashGridHelper.h.
References Box, ForEachIntersectingCells(), FVector, GetCellBounds(), UE::Math::TBox2< T >::Max, UE::Math::TVector2< double >::Max(), UE::Math::TBox2< T >::Min, and UE::Math::TVector2< double >::Min().
ForEachIntersectingCells() [3/3]
int32 FSquare2DGridHelper::FGrid2D::ForEachIntersectingCells (const FSphericalSector & InShape, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const
Runs a function on all intersecting cells for the provided spherical sector.
Returns
the number of intersecting cells
ForEachIntersectingCellsBreakable()
int32 FSquare2DGridHelper::FGrid2D::ForEachIntersectingCellsBreakable (const FBox & InBox, TFunctionRef< bool(const FGridCellCoord2 &)> InOperation) const inline
Runs a function on all intersecting cells for the provided box.
Returns
the number of intersecting cells
Definition at line 187 of file RuntimeSpatialHashGridHelper.h.
References GetCellCoords(), IsValidCoords(), UE::Math::TBox< T >::Max, UE::Math::TBox< T >::Min, UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
Referenced by ForEachIntersectingCells().
GetCellBounds() [1/2]
bool FSquare2DGridHelper::FGrid2D::GetCellBounds (const FGridCellCoord2 & InCoords, FBox2D & OutBounds, bool bCheckIsValidCoord = true) const inline
Returns the cell bounds.
Returns
true if the specified coord was valid
Definition at line 79 of file RuntimeSpatialHashGridHelper.h.
References CellSize, GridSize, IsValidCoords(), Max, Origin, UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
GetCellBounds() [2/2]
bool FSquare2DGridHelper::FGrid2D::GetCellBounds (int64 InIndex, FBox2D & OutBounds) const inline
Returns the cell bounds.
Returns
true if the specified index was valid
Definition at line 63 of file RuntimeSpatialHashGridHelper.h.
References GetCellBounds(), and GridSize.
Referenced by ForEachIntersectingCells(), and GetCellBounds().
GetCellCoords() [1/2]
bool FSquare2DGridHelper::FGrid2D::GetCellCoords (const FBox2D & InBounds2D, FGridCellCoord2 & OutMinCellCoords, FGridCellCoord2 & OutMaxCellCoords) const inline
Returns the cells coordinates of the provided box.
Returns
true if the bounds was intersecting with the grid
Definition at line 112 of file RuntimeSpatialHashGridHelper.h.
References FMath::Clamp(), GetCellCoords(), GridSize, UE::Math::TBox2< T >::Max, UE::Math::TBox2< T >::Min, UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
GetCellCoords() [2/2]
bool FSquare2DGridHelper::FGrid2D::GetCellCoords (const FVector2D & InPos, FGridCellCoord2 & OutCoords) const inline
Returns the cell coordinates of the provided position.
Returns
true if the position was inside the grid
Definition at line 97 of file RuntimeSpatialHashGridHelper.h.
References CellSize, GridSize, IsValidCoords(), Origin, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by ForEachIntersectingCellsBreakable(), GetCellCoords(), and GetNumIntersectingCells().
GetCellIndex() [1/2]
bool FSquare2DGridHelper::FGrid2D::GetCellIndex (const FGridCellCoord2 & InCoords, uint64 & OutIndex) const inline
Returns the cell index of the provided coords.
Returns
true if the coords was inside the grid
Definition at line 138 of file RuntimeSpatialHashGridHelper.h.
References GridSize, IsValidCoords(), UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
Referenced by FSquare2DGridHelper::FGridLevel::GetCell(), FSquare2DGridHelper::FGridLevel::GetCell(), and GetCellIndex().
GetCellIndex() [2/2]
bool FSquare2DGridHelper::FGrid2D::GetCellIndex (const FVector & InPos, uint64 & OutIndex) const inline
Returns the cell index of the provided position.
Returns
true if the position was inside the grid
Definition at line 153 of file RuntimeSpatialHashGridHelper.h.
References CellSize, FVector, GetCellIndex(), GridSize, Origin, UE::Math::TVector< T >::X, and UE::Math::TVector< T >::Y.
GetNumIntersectingCells()
int32 FSquare2DGridHelper::FGrid2D::GetNumIntersectingCells (const FBox & InBox) const inline
Get the number of intersecting cells of the provided box.
Returns
the number of intersecting cells
Definition at line 168 of file RuntimeSpatialHashGridHelper.h.
References GetCellCoords(), UE::Math::TBox< T >::Max, UE::Math::TBox< T >::Min, UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
IsValidCoords()
bool FSquare2DGridHelper::FGrid2D::IsValidCoords (const FGridCellCoord2 & InCoords) const inline
Validate that the coordinates fit the grid size.
Returns
true if the specified coordinates are valid
Definition at line 45 of file RuntimeSpatialHashGridHelper.h.
References ensureMsgf, GridSize, TEXT, UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
Referenced by ForEachIntersectingCellsBreakable(), FSquare2DGridHelper::FGridLevel::GetCell(), FSquare2DGridHelper::FGridLevel::GetCell(), GetCellBounds(), GetCellCoords(), FSquare2DGridHelper::GetCellGlobalCoords(), and GetCellIndex().
Field Documentation
CellSize
int64 FSquare2DGridHelper::FGrid2D::CellSize
Definition at line 31 of file RuntimeSpatialHashGridHelper.h.
Referenced by FGrid2D(), GetCellBounds(), GetCellCoords(), and GetCellIndex().
GridSize
int64 FSquare2DGridHelper::FGrid2D::GridSize
Definition at line 32 of file RuntimeSpatialHashGridHelper.h.
Referenced by FGrid2D(), GetCellBounds(), GetCellBounds(), GetCellCoords(), GetCellCoords(), GetCellIndex(), GetCellIndex(), and IsValidCoords().
Origin
FVector2D FSquare2DGridHelper::FGrid2D::Origin
Definition at line 30 of file RuntimeSpatialHashGridHelper.h.
Referenced by FGrid2D(), GetCellBounds(), GetCellCoords(), and GetCellIndex().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/WorldPartition/RuntimeSpatialHash/RuntimeSpatialHashGridHelper.h