Unreal Engine 5.6 C++ API: IRenderAssetStreamingManager Struct Reference
IRenderAssetStreamingManager Struct Reference abstract
Interface to add functions specifically related to texture/mesh streaming.
#include "ContentStreaming.h"
Public Member Functions
virtual void AddRenderedTextureStats (TMap< FString, FRenderedTextureStats > &InOutRenderedTextureAssets)=0
virtual void AddStreamingRenderAsset (UStreamableRenderAsset *RenderAsset)=0
Adds a new texture/mesh to the streaming manager.
void AddStreamingTexture (UTexture2D *Texture)
virtual void BoostTextures (AActor *Actor, float BoostFactor)=0
Temporarily boosts the streaming distance factor by the specified number.
virtual bool FastForceFullyResident (UStreamableRenderAsset *RenderAsset)=0
Stream in non-resident mips for an asset ASAP.
virtual void GetAssetComponents (const UStreamableRenderAsset *RenderAsset, TArray< const UPrimitiveComponent * > &OutComps, TFunction< bool(const UPrimitiveComponent *)> ShouldChoose=ShouldChooseDefault)=0
Return all components referencing the asset.
virtual float GetCachedMips () const =0
Amount of memory cached in pool.
virtual int64 GetMaxEverRequired () const =0
Max required textures/meshes ever seen in bytes.
virtual int64 GetMemoryOverBudget () const =0
virtual void GetObjectReferenceBounds (const UObject *RefObject, TArray< FBox > &AssetBoxes)=0
Return all bounds related to the ref object.
virtual int64 GetPoolSize () const =0
Pool size for streaming.
virtual int64 GetRequiredPoolSize () const =0
Estimated memory in bytes the streamer would use if there was no limit.
virtual bool IsFullyStreamedIn (UStreamableRenderAsset *RenderAsset)=0
Check whether all runtime-allowed LODs have been loaded.
virtual void MarkMountedStateDirty (FIoFilenameHash FilenameHash)=0
Notify the streamer that the mounted state of a file needs to be re-evaluated.
virtual void PauseRenderAssetStreaming (bool bInShouldPause)=0
Set current pause state for texture/mesh streaming.
void PauseTextureStreaming (bool bInShouldPause)
virtual void RemoveStreamingRenderAsset (UStreamableRenderAsset *RenderAsset)=0
Removes a texture/mesh from the streaming manager.
void RemoveStreamingTexture (UTexture2D *Texture)
virtual void ResetMaxEverRequired ()=0
Resets the max ever required textures/meshes.
virtual bool StreamOutRenderAssetData (int64 RequiredMemorySize)=0
Try to stream out texture/mesh mip-levels to free up more memory.
bool StreamOutTextureData (int64 RequiredMemorySize)
virtual void UpdateIndividualRenderAsset (UStreamableRenderAsset *RenderAsset)=0
Updates streaming for an individual texture/mesh, taking into account all view infos.
void UpdateIndividualTexture (UTexture2D *Texture)
Public Member Functions inherited from IStreamingManager
IStreamingManager ()
virtual ~IStreamingManager ()
Virtual destructor.
virtual void AddLevel (class ULevel *Level)=0
Adds a ULevel that has already prepared StreamingData to the streaming manager.
void AddViewInformation (const FVector &ViewOrigin, float ScreenSize, float FOVScreenSize, float BoostFactor=1.0f, bool bOverrideLocation=false, float Duration=0.0f, TWeakObjectPtr< AActor > InActorToBoost=NULL, TWeakObjectPtr< UWorld > InWorld=NULL)
Adds the passed in view information to the static array.
void AddViewLocation (const FVector &Location, float BoostFactor=1.0f, bool bOverrideLocation=false, float Duration=0.0f)
Queue up view locations to the streaming system.
virtual int32 BlockTillAllRequestsFinished (float TimeLimit=0.0f, bool bLogResults=false)=0
Blocks till all pending requests are fulfilled.
virtual void CancelForcedResources ()=0
Cancels the timed Forced resources (i.e used the Kismet action "Stream In Textures").
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Allows the streaming manager to process exec commands.
int32 GetNumViews () const
Returns the number of view infos.
virtual int32 GetNumWantingResources () const
Returns the number of resources that currently wants to be streamed in.
virtual int32 GetNumWantingResourcesID () const
Returns the current ID for GetNumWantingResources().
const FStreamingViewInfo & GetViewInformation (int32 ViewIndex) const
Returns the view info by the specified index.
virtual void NotifyActorDestroyed (AActor *Actor)
Called when a spawned actor is destroyed.
virtual void NotifyLevelChange ()=0
Notifies manager of "level" change.
virtual void NotifyLevelOffset (class ULevel *Level, const FVector &Offset)=0
Notifies manager that level primitives were shifted.
virtual void NotifyPrimitiveDetached (const UPrimitiveComponent *Primitive)
Called when a primitive is detached from an actor or another component.
virtual void NotifyPrimitiveUpdated (const UPrimitiveComponent *Primitive)
Called when a primitive streaming data needs to be updated.
virtual void NotifyPrimitiveUpdated_Concurrent (const UPrimitiveComponent *Primitive)
Called when a primitive streaming data needs to be updated in the last stage of the frame.
virtual void OnAudioStreamingParamsChanged ()
virtual void PropagateLightingScenarioChange ()
Propagates a change to the active lighting scenario.
virtual void RemoveLevel (class ULevel *Level)=0
Removes a ULevel from the streaming manager.
void RemoveStreamingViews (ERemoveStreamingViews RemovalType)
Removes streaming views from the streaming manager.
virtual int32 StreamAllResources (float TimeLimit=0.0f)
Streams in/out all resources that wants to and blocks until it's done.
virtual void Tick (float DeltaTime, bool bProcessEverything=false)
Calls UpdateResourceStreaming(), and does per-frame cleaning.
UE_DEPRECATED (5.1, "This is deprecated to follow inclusive naming rules. Use AddViewLocation() instead.") void AddViewSlaveLocation(const FVector &Location
virtual void UpdateResourceStreaming (float DeltaTime, bool bProcessEverything=false)=0
Updates streaming, taking into account all current view infos.
Static Public Attributes
static constexpr auto ShouldChooseDefault = [](const UPrimitiveComponent*) { return true; }
Additional Inherited Members
Static Public Member Functions inherited from IStreamingManager
static struct FStreamingManagerCollection & Get ()
static struct FStreamingManagerCollection * Get_Concurrent ()
Same as get but could fail if state not allocated or shutdown.
static bool HasShutdown ()
Checks if the streaming manager has already been shut down.
static void Shutdown ()
Data Fields inherited from IStreamingManager
float BoostFactor = 1.0f
float bool bOverrideLocation = false
float bool float Duration
Protected Member Functions inherited from IStreamingManager
void SetupViewInfos (float DeltaTime)
Sets up the CurrentViewInfos array based on PendingViewInfos, LastingViewInfos and SecondaryLocations.
Static Protected Member Functions inherited from IStreamingManager
static void AddViewInfoToArray (TArray< FStreamingViewInfo > &ViewInfos, const FVector &ViewOrigin, float ScreenSize, float FOVScreenSize, float BoostFactor, bool bOverrideLocation, float Duration, TWeakObjectPtr< AActor > InActorToBoost, TWeakObjectPtr< UWorld > InWorld)
Adds the passed in view information to the static array.
static void RemoveViewInfoFromArray (TArray< FStreamingViewInfo > &ViewInfos, const FVector &ViewOrigin)
Remove view infos with the same location from the given array.
Protected Attributes inherited from IStreamingManager
int32 NumWantingResources
Number of resources that currently wants to be streamed in.
int32 NumWantingResourcesCounter
The current counter for NumWantingResources.
Static Protected Attributes inherited from IStreamingManager
static bool bPendingRemoveViews
Set when Tick() has been called.
static TArray< FStreamingViewInfo > CurrentViewInfos
Current collection of views that need to be taken into account for streaming.
static TArray< FStreamingViewInfo > LastingViewInfos
Views that stick around for a while.
static TArray< FStreamingViewInfo > PendingViewInfos
Pending views.
static TArray< FSecondaryLocation > SecondaryLocations
Collection of view locations that will be added at the next call to AddViewInformation.
Detailed Description
Interface to add functions specifically related to texture/mesh streaming.
Definition at line 428 of file ContentStreaming.h.
Member Function Documentation
AddRenderedTextureStats()
virtual void IRenderAssetStreamingManager::AddRenderedTextureStats (TMap< FString, FRenderedTextureStats > & InOutRenderedTextureAssets) pure virtual
AddStreamingRenderAsset()
virtual void IRenderAssetStreamingManager::AddStreamingRenderAsset (UStreamableRenderAsset * RenderAsset) pure virtual
Adds a new texture/mesh to the streaming manager.
AddStreamingTexture()
void IRenderAssetStreamingManager::AddStreamingTexture (UTexture2D * Texture)
References Texture.
BoostTextures()
virtual void IRenderAssetStreamingManager::BoostTextures (AActor * Actor, float BoostFactor) pure virtual
Temporarily boosts the streaming distance factor by the specified number.
This factor is automatically reset to 1.0 after it's been used for mip-calculations.
References Actor, and IStreamingManager::BoostFactor.
FastForceFullyResident()
virtual bool IRenderAssetStreamingManager::FastForceFullyResident (UStreamableRenderAsset * RenderAsset) pure virtual
Stream in non-resident mips for an asset ASAP.
Returns true if streaming request will be successful.
GetAssetComponents()
virtual void IRenderAssetStreamingManager::GetAssetComponents (const UStreamableRenderAsset * RenderAsset, TArray< const UPrimitiveComponent * > & OutComps, TFunction< bool(const UPrimitiveComponent *)> ShouldChoose = ShouldChooseDefault) pure virtual
Return all components referencing the asset.
References ShouldChooseDefault.
Referenced by FSkeletalMeshStreamOut::ConditionalMarkComponentsDirty().
GetCachedMips()
virtual float IRenderAssetStreamingManager::GetCachedMips () const pure virtual
Amount of memory cached in pool.
GetMaxEverRequired()
virtual int64 IRenderAssetStreamingManager::GetMaxEverRequired () const pure virtual
Max required textures/meshes ever seen in bytes.
GetMemoryOverBudget()
virtual int64 IRenderAssetStreamingManager::GetMemoryOverBudget () const pure virtual
GetObjectReferenceBounds()
virtual void IRenderAssetStreamingManager::GetObjectReferenceBounds (const UObject * RefObject, TArray< FBox > & AssetBoxes) pure virtual
Return all bounds related to the ref object.
GetPoolSize()
virtual int64 IRenderAssetStreamingManager::GetPoolSize () const pure virtual
Pool size for streaming.
GetRequiredPoolSize()
virtual int64 IRenderAssetStreamingManager::GetRequiredPoolSize () const pure virtual
Estimated memory in bytes the streamer would use if there was no limit.
IsFullyStreamedIn()
virtual bool IRenderAssetStreamingManager::IsFullyStreamedIn (UStreamableRenderAsset * RenderAsset) pure virtual
Check whether all runtime-allowed LODs have been loaded.
MarkMountedStateDirty()
virtual void IRenderAssetStreamingManager::MarkMountedStateDirty (FIoFilenameHash FilenameHash) pure virtual
Notify the streamer that the mounted state of a file needs to be re-evaluated.
Referenced by FSkeletalMeshStreamIn_IO::ReportIOError().
PauseRenderAssetStreaming()
virtual void IRenderAssetStreamingManager::PauseRenderAssetStreaming (bool bInShouldPause) pure virtual
Set current pause state for texture/mesh streaming.
PauseTextureStreaming()
void IRenderAssetStreamingManager::PauseTextureStreaming (bool bInShouldPause)
RemoveStreamingRenderAsset()
virtual void IRenderAssetStreamingManager::RemoveStreamingRenderAsset (UStreamableRenderAsset * RenderAsset) pure virtual
Removes a texture/mesh from the streaming manager.
RemoveStreamingTexture()
void IRenderAssetStreamingManager::RemoveStreamingTexture (UTexture2D * Texture)
References Texture.
ResetMaxEverRequired()
virtual void IRenderAssetStreamingManager::ResetMaxEverRequired () pure virtual
Resets the max ever required textures/meshes.
For possibly when changing resolutions or screen pct.
StreamOutRenderAssetData()
virtual bool IRenderAssetStreamingManager::StreamOutRenderAssetData (int64 RequiredMemorySize) pure virtual
Try to stream out texture/mesh mip-levels to free up more memory.
Parameters
RequiredMemorySize - Required minimum available texture memory
Returns
- Whether it succeeded or not
StreamOutTextureData()
bool IRenderAssetStreamingManager::StreamOutTextureData (int64 RequiredMemorySize)
UpdateIndividualRenderAsset()
virtual void IRenderAssetStreamingManager::UpdateIndividualRenderAsset (UStreamableRenderAsset * RenderAsset) pure virtual
Updates streaming for an individual texture/mesh, taking into account all view infos.
Parameters
RenderAsset Texture or mesh to update
UpdateIndividualTexture()
void IRenderAssetStreamingManager::UpdateIndividualTexture (UTexture2D * Texture)
References Texture.
Field Documentation
ShouldChooseDefault
auto IRenderAssetStreamingManager::ShouldChooseDefault = [](const UPrimitiveComponent*) { return true; } static constexpr
Definition at line 485 of file ContentStreaming.h.
Referenced by GetAssetComponents().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/ContentStreaming.h