Unreal Engine 5.6 C++ API: FScopedCookStat Struct Reference
FScopedCookStat Struct Reference
#include "CookStats.h"
Public Member Functions
FScopedCookStat (const FScopedCookStat &)=delete
FScopedCookStat (FScopedCookStat &&)=delete
FScopedCookStat (uint64 Id, EPackageEventStatType InStatType)
~FScopedCookStat ()
Private Attributes
uint64 Id
EPackageEventStatType StatType
Detailed Description
Definition at line 457 of file CookStats.h.
Constructor & Destructor Documentation
FScopedCookStat() [1/3]
FScopedCookStat::FScopedCookStat (const FScopedCookStat &) delete
References FScopedCookStat().
Referenced by FScopedCookStat(), and FScopedCookStat().
FScopedCookStat() [2/3]
FScopedCookStat::FScopedCookStat (FScopedCookStat &&) delete
References FScopedCookStat().
FScopedCookStat() [3/3]
FScopedCookStat::FScopedCookStat (uint64 Id, EPackageEventStatType InStatType) inline
Definition at line 462 of file CookStats.h.
References FAndroidTime::Cycles64(), Id, StatType, and TracePackageStatBeginScope().
~FScopedCookStat()
FScopedCookStat::~FScopedCookStat () inline
Definition at line 469 of file CookStats.h.
References FAndroidTime::Cycles64(), Id, StatType, and TracePackageStatEndScope().
Field Documentation
Id
uint64 FScopedCookStat::Id private
Definition at line 475 of file CookStats.h.
Referenced by FScopedCookStat(), and ~FScopedCookStat().
StatType
EPackageEventStatType FScopedCookStat::StatType private
Definition at line 476 of file CookStats.h.
Referenced by FScopedCookStat(), and ~FScopedCookStat().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/CookStats.h