Unreal Engine 5.6 C++ API: FSlateInvalidationRootHandle Struct Reference
FSlateInvalidationRootHandle Struct Reference
#include "SlateInvalidationRootHandle.h"
Public Member Functions
FSlateInvalidationRootHandle ()
FSlateInvalidationRootHandle (int32 UniqueId)
FSlateInvalidationRoot * Advanced_GetInvalidationRootNoCheck () const
FSlateInvalidationRoot * GetInvalidationRoot () const
int32 GetUniqueId () const
bool IsStale () const
bool operator== (const FSlateInvalidationRootHandle &Other) const
Private Attributes
FSlateInvalidationRoot * InvalidationRoot
int32 UniqueId
Detailed Description
Definition at line 9 of file SlateInvalidationRootHandle.h.
Constructor & Destructor Documentation
FSlateInvalidationRootHandle() [1/2]
FSlateInvalidationRootHandle::FSlateInvalidationRootHandle ()
Referenced by operator==().
FSlateInvalidationRootHandle() [2/2]
FSlateInvalidationRootHandle::FSlateInvalidationRootHandle (int32 UniqueId)
References UniqueId.
Member Function Documentation
Advanced_GetInvalidationRootNoCheck()
FSlateInvalidationRoot * FSlateInvalidationRootHandle::Advanced_GetInvalidationRootNoCheck () const inline
Definition at line 28 of file SlateInvalidationRootHandle.h.
References InvalidationRoot.
GetInvalidationRoot()
FSlateInvalidationRoot * FSlateInvalidationRootHandle::GetInvalidationRoot () const
Referenced by IsStale().
GetUniqueId()
int32 FSlateInvalidationRootHandle::GetUniqueId () const inline
Definition at line 15 of file SlateInvalidationRootHandle.h.
References UniqueId.
IsStale()
bool FSlateInvalidationRootHandle::IsStale () const inline
Returns
true if this used to point to a InvalidatationRoot, but doesn't any more and has not been assigned or reset in the mean time.
Definition at line 21 of file SlateInvalidationRootHandle.h.
References GetInvalidationRoot(), and InvalidationRoot.
operator==()
bool FSlateInvalidationRootHandle::operator== (const FSlateInvalidationRootHandle & Other) const inline
Definition at line 33 of file SlateInvalidationRootHandle.h.
References FSlateInvalidationRootHandle(), Other, and UniqueId.
Field Documentation
InvalidationRoot
FSlateInvalidationRoot* FSlateInvalidationRootHandle::InvalidationRoot private
Definition at line 39 of file SlateInvalidationRootHandle.h.
Referenced by Advanced_GetInvalidationRootNoCheck(), and IsStale().
UniqueId
int32 FSlateInvalidationRootHandle::UniqueId private
Definition at line 40 of file SlateInvalidationRootHandle.h.
Referenced by FSlateInvalidationRootHandle(), GetUniqueId(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/FastUpdate/SlateInvalidationRootHandle.h