Unreal Engine 5.6 C++ API: FMeshRenderBufferSetConversionUtil Struct Reference
FMeshRenderBufferSetConversionUtil Struct Reference
Parameters and accompanying functions used to build and update FMeshRenderBuffers from a dynamic mesh.
#include "MeshRenderBufferSet.h"
Public Member Functions
FColor GetOverlayColorAsFColor (const FDynamicMeshColorOverlay *ColorOverlay, int32 ElementID)
Get the overlay color the FColor, respecting the ColorSpaceTransformMode utilizing the VertexColorRemappingFunc if requested.
template<typename TriangleEnumerable>
void InitializeBuffersFromOverlays (FMeshRenderBufferSet *RenderBuffers, const FDynamicMesh3 *Mesh, int NumTriangles, const TriangleEnumerable &Enumerable, const FDynamicMeshUVOverlay *UVOverlay, const FDynamicMeshNormalOverlay *NormalOverlay, const FDynamicMeshColorOverlay *ColorOverlay, TFunctionRef< void(int, int, int, const FVector3f &, FVector3f &, FVector3f &)> TangentsFunc, bool bTrackTriangles=false, bool bParallel=false)
Initialize rendering buffers from given attribute overlays.
template<typename TriangleEnumerable, typename UVOverlayListAllocator>
void InitializeBuffersFromOverlays (FMeshRenderBufferSet *RenderBuffers, const FDynamicMesh3 *Mesh, int NumTriangles, const TriangleEnumerable &Enumerable, const TArray< const FDynamicMeshUVOverlay *, UVOverlayListAllocator > &UVOverlays, const FDynamicMeshNormalOverlay *NormalOverlay, const FDynamicMeshColorOverlay *ColorOverlay, TFunctionRef< void(int, int, int, const FVector3f &, FVector3f &, FVector3f &)> TangentsFunc, bool bTrackTriangles=false, bool bParallel=false)
Initialize rendering buffers from given attribute overlays.
void GEOMETRYFRAMEWORK_API RecomputeRenderBufferTriangleIndexSets (FMeshRenderBufferSet *RenderBuffers, const FDynamicMesh3 *Mesh)
RecomputeRenderBufferTriangleIndexSets re-sorts the existing set of triangles in a FMeshRenderBufferSet into primary and secondary index buffers.
void GEOMETRYFRAMEWORK_API UpdateSecondaryTriangleBuffer (FMeshRenderBufferSet *RenderBuffers, const FDynamicMesh3 *Mesh, bool bDuplicate)
Filter the triangles in a FMeshRenderBufferSet into the SecondaryIndexBuffer.
template<typename TriangleEnumerable>
void UpdateVertexBuffersFromOverlays (FMeshRenderBufferSet *RenderBuffers, const FDynamicMesh3 *Mesh, int NumTriangles, const TriangleEnumerable &Enumerable, const FDynamicMeshNormalOverlay *NormalOverlay, const FDynamicMeshColorOverlay *ColorOverlay, TFunctionRef< void(int, int, int, const FVector3f &, FVector3f &, FVector3f &)> TangentsFunc, bool bUpdatePositions=true, bool bUpdateNormals=false, bool bUpdateColors=false)
Update vertex positions/normals/colors of an existing set of render buffers.
template<typename TriangleEnumerable, typename UVOverlayListAllocator>
void UpdateVertexUVBufferFromOverlays (FMeshRenderBufferSet *RenderBuffers, const FDynamicMesh3 *Mesh, int32 NumTriangles, const TriangleEnumerable &Enumerable, const TArray< const FDynamicMeshUVOverlay *, UVOverlayListAllocator > &UVOverlays)
Update vertex uvs of an existing set of render buffers.
Data Fields
bool bApplyVertexColorRemapping = false
If true, VertexColorRemappingFunc is called on Vertex Colors provided from Mesh to remap them to a different color.
bool bIgnoreVertexColors = false
If true, vertex colors on the FDynamicMesh will be ignored.
bool bUsePerTriangleColor = false
If true, a per-triangle color is used to set vertex colors.
bool bUsePerTriangleNormals = false
If true, a facet normals are used instead of mesh normals.
bool bUseSecondaryTriBuffers = false
If true, populate secondary buffers using SecondaryTriFilterFunc.
EDynamicMeshVertexColorTransformMode ColorSpaceTransformMode = EDynamicMeshVertexColorTransformMode::NoTransform
Color Space Transform/Conversion applied to Vertex Colors provided from Mesh Color Overlay Attribute Color Space Conversion is applied after any Vertex Color Remapping.
FColor ConstantVertexColor = FColor::White
Constant color assigned to vertices if no other vertex color is specified.
TFunction< FColor(const FDynamicMesh3 *, int)> PerTriangleColorFunc = nullptr
Per-triangle color function.
TUniqueFunction< bool(const FDynamicMesh3 *, int32)> SecondaryTriFilterFunc = nullptr
Filter predicate for secondary triangle index buffer.
TUniqueFunction< void(FVector4f &)> VertexColorRemappingFunc = nullptr
Vertex color remapping function.
Private Types
using FIndex2i = UE::Geometry::FIndex2i
using FIndex3i = UE::Geometry::FIndex3i
Detailed Description
Parameters and accompanying functions used to build and update FMeshRenderBuffers from a dynamic mesh.
For usage, see FBaseDynamicMeshSceneProxy or the simple converter below FDynamicMeshComponentToMeshRenderBufferSet
Note: This is low-level and methods assume, but do not check, all input data is consistent (e.g. that all overlays, the triangle count and enumerator are all consistent with the provided mesh.)
Definition at line 297 of file MeshRenderBufferSet.h.
Member Typedef Documentation
FIndex2i
using FMeshRenderBufferSetConversionUtil::FIndex2i = UE::Geometry::FIndex2i private
Definition at line 468 of file MeshRenderBufferSet.h.
FIndex3i
using FMeshRenderBufferSetConversionUtil::FIndex3i = UE::Geometry::FIndex3i private
Definition at line 469 of file MeshRenderBufferSet.h.
Member Function Documentation
GetOverlayColorAsFColor()
FColor FMeshRenderBufferSetConversionUtil::GetOverlayColorAsFColor (const FDynamicMeshColorOverlay * ColorOverlay, int32 ElementID) inline
Get the overlay color the FColor, respecting the ColorSpaceTransformMode utilizing the VertexColorRemappingFunc if requested.
Definition at line 442 of file MeshRenderBufferSet.h.
References bApplyVertexColorRemapping, checkSlow, ColorSpaceTransformMode, UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetElement(), FLinearColor::ToFColor(), and VertexColorRemappingFunc.
Referenced by InitializeBuffersFromOverlays(), and UpdateVertexBuffersFromOverlays().
InitializeBuffersFromOverlays() [1/2]
template<typename TriangleEnumerable> void FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays (FMeshRenderBufferSet * RenderBuffers, const FDynamicMesh3 * Mesh, int NumTriangles, const TriangleEnumerable & Enumerable, const FDynamicMeshUVOverlay * UVOverlay, const FDynamicMeshNormalOverlay * NormalOverlay, const FDynamicMeshColorOverlay * ColorOverlay, TFunctionRef< void(int, int, int, const FVector3f &, FVector3f &, FVector3f &)> TangentsFunc, bool bTrackTriangles = false, bool bParallel = false) inline
Initialize rendering buffers from given attribute overlays.
Creates three vertices per triangle, IE no shared vertices in buffers.
Definition at line 357 of file MeshRenderBufferSet.h.
References TArray< InElementType, InAllocatorType >::Add(), InitializeBuffersFromOverlays(), and Mesh.
Referenced by InitializeBuffersFromOverlays().
InitializeBuffersFromOverlays() [2/2]
template<typename TriangleEnumerable, typename UVOverlayListAllocator> void FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays (FMeshRenderBufferSet * RenderBuffers, const FDynamicMesh3 * Mesh, int NumTriangles, const TriangleEnumerable & Enumerable, const TArray< const FDynamicMeshUVOverlay *, UVOverlayListAllocator > & UVOverlays, const FDynamicMeshNormalOverlay * NormalOverlay, const FDynamicMeshColorOverlay * ColorOverlay, TFunctionRef< void(int, int, int, const FVector3f &, FVector3f &, FVector3f &)> TangentsFunc, bool bTrackTriangles = false, bool bParallel = false)
Initialize rendering buffers from given attribute overlays.
Creates three vertices per triangle, IE no shared vertices in buffers.
Definition at line 504 of file MeshRenderBufferSet.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::AddUninitialized(), bIgnoreVertexColors, bUsePerTriangleNormals, bUseSecondaryTriBuffers, FMeshRenderBufferSet::ColorVertexBuffer, UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetElement(), GetOverlayColorAsFColor(), IndexBuffer, FMeshRenderBufferSet::IndexBuffer, FDynamicMeshIndexBuffer32::Indices, FColorVertexBuffer::Init(), FPositionVertexBuffer::Init(), FStaticMeshVertexBuffer::Init(), UE::Geometry::FIndex3i::Invalid(), FDynamicMesh3::InvalidID, FMath::Max, Mesh, Normal, TArray< InElementType, InAllocatorType >::Num(), ParallelFor(), FMeshRenderBufferSet::PositionVertexBuffer, TArray< InElementType, InAllocatorType >::Reserve(), FStaticMeshVertexBuffer::SetVertexTangents(), FStaticMeshVertexBuffer::SetVertexUV(), FMeshRenderBufferSet::StaticMeshVertexBuffer, FMeshRenderBufferSet::TriangleCount, UV, FColorVertexBuffer::VertexColor(), FPositionVertexBuffer::VertexPosition(), and UE::Math::TVector2< float >::Zero().
RecomputeRenderBufferTriangleIndexSets()
void GEOMETRYFRAMEWORK_API FMeshRenderBufferSetConversionUtil::RecomputeRenderBufferTriangleIndexSets (FMeshRenderBufferSet * RenderBuffers, const FDynamicMesh3 * Mesh)
RecomputeRenderBufferTriangleIndexSets re-sorts the existing set of triangles in a FMeshRenderBufferSet into primary and secondary index buffers.
Note that UploadIndexBufferUpdate() must be called after this function!
References Mesh.
UpdateSecondaryTriangleBuffer()
void GEOMETRYFRAMEWORK_API FMeshRenderBufferSetConversionUtil::UpdateSecondaryTriangleBuffer (FMeshRenderBufferSet * RenderBuffers, const FDynamicMesh3 * Mesh, bool bDuplicate)
Filter the triangles in a FMeshRenderBufferSet into the SecondaryIndexBuffer.
Requires that RenderBuffers->Triangles has been initialized.
Parameters
bDuplicate if set, then primary IndexBuffer is unmodified and SecondaryIndexBuffer contains duplicates. Otherwise triangles are sorted via predicate into either primary or secondary.
References Mesh.
UpdateVertexBuffersFromOverlays()
template<typename TriangleEnumerable> void FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays (FMeshRenderBufferSet * RenderBuffers, const FDynamicMesh3 * Mesh, int NumTriangles, const TriangleEnumerable & Enumerable, const FDynamicMeshNormalOverlay * NormalOverlay, const FDynamicMeshColorOverlay * ColorOverlay, TFunctionRef< void(int, int, int, const FVector3f &, FVector3f &, FVector3f &)> TangentsFunc, bool bUpdatePositions = true, bool bUpdateNormals = false, bool bUpdateColors = false)
Update vertex positions/normals/colors of an existing set of render buffers.
Assumes that buffers were created with unshared vertices, ie three vertices per triangle, eg by InitializeBuffersFromOverlays()
Definition at line 637 of file MeshRenderBufferSet.h.
References bIgnoreVertexColors, bUsePerTriangleColor, bUsePerTriangleNormals, FMeshRenderBufferSet::ColorVertexBuffer, ConstantVertexColor, ensure, UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetElement(), FColorVertexBuffer::GetNumVertices(), FPositionVertexBuffer::GetNumVertices(), FStaticMeshVertexBuffer::GetNumVertices(), GetOverlayColorAsFColor(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetTriangle(), FDynamicMesh3::InvalidID, Mesh, Normal, PerTriangleColorFunc, FMeshRenderBufferSet::PositionVertexBuffer, FStaticMeshVertexBuffer::SetVertexTangents(), FMeshRenderBufferSet::StaticMeshVertexBuffer, FMeshRenderBufferSet::TriangleCount, FColorVertexBuffer::VertexColor(), FPositionVertexBuffer::VertexPosition(), and UE::Geometry::FIndex3i::Zero().
UpdateVertexUVBufferFromOverlays()
template<typename TriangleEnumerable, typename UVOverlayListAllocator> void FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays (FMeshRenderBufferSet * RenderBuffers, const FDynamicMesh3 * Mesh, int32 NumTriangles, const TriangleEnumerable & Enumerable, const TArray< const FDynamicMeshUVOverlay *, UVOverlayListAllocator > & UVOverlays)
Update vertex uvs of an existing set of render buffers.
Assumes that buffers were created with unshared vertices, ie three vertices per triangle, eg by InitializeBuffersFromOverlays()
Definition at line 717 of file MeshRenderBufferSet.h.
References ensure, FStaticMeshVertexBuffer::GetNumTexCoords(), FStaticMeshVertexBuffer::GetNumVertices(), UE::Geometry::FIndex3i::Invalid(), FDynamicMesh3::InvalidID, Mesh, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::SetNum(), FStaticMeshVertexBuffer::SetVertexUV(), FMeshRenderBufferSet::StaticMeshVertexBuffer, FMeshRenderBufferSet::TriangleCount, UV, and UE::Math::TVector2< float >::Zero().
Field Documentation
bApplyVertexColorRemapping
bool FMeshRenderBufferSetConversionUtil::bApplyVertexColorRemapping = false
If true, VertexColorRemappingFunc is called on Vertex Colors provided from Mesh to remap them to a different color.
Definition at line 323 of file MeshRenderBufferSet.h.
Referenced by GetOverlayColorAsFColor().
bIgnoreVertexColors
bool FMeshRenderBufferSetConversionUtil::bIgnoreVertexColors = false
If true, vertex colors on the FDynamicMesh will be ignored.
Definition at line 308 of file MeshRenderBufferSet.h.
Referenced by InitializeBuffersFromOverlays(), and UpdateVertexBuffersFromOverlays().
bUsePerTriangleColor
bool FMeshRenderBufferSetConversionUtil::bUsePerTriangleColor = false
If true, a per-triangle color is used to set vertex colors.
Definition at line 313 of file MeshRenderBufferSet.h.
Referenced by UpdateVertexBuffersFromOverlays().
bUsePerTriangleNormals
bool FMeshRenderBufferSetConversionUtil::bUsePerTriangleNormals = false
If true, a facet normals are used instead of mesh normals.
Definition at line 339 of file MeshRenderBufferSet.h.
Referenced by InitializeBuffersFromOverlays(), and UpdateVertexBuffersFromOverlays().
bUseSecondaryTriBuffers
bool FMeshRenderBufferSetConversionUtil::bUseSecondaryTriBuffers = false
If true, populate secondary buffers using SecondaryTriFilterFunc.
Definition at line 344 of file MeshRenderBufferSet.h.
Referenced by InitializeBuffersFromOverlays().
ColorSpaceTransformMode
EDynamicMeshVertexColorTransformMode FMeshRenderBufferSetConversionUtil::ColorSpaceTransformMode = EDynamicMeshVertexColorTransformMode::NoTransform
Color Space Transform/Conversion applied to Vertex Colors provided from Mesh Color Overlay Attribute Color Space Conversion is applied after any Vertex Color Remapping.
Definition at line 334 of file MeshRenderBufferSet.h.
Referenced by GetOverlayColorAsFColor().
ConstantVertexColor
FColor FMeshRenderBufferSetConversionUtil::ConstantVertexColor = FColor::White
Constant color assigned to vertices if no other vertex color is specified.
Definition at line 303 of file MeshRenderBufferSet.h.
Referenced by UpdateVertexBuffersFromOverlays().
PerTriangleColorFunc
TFunction<FColor(const FDynamicMesh3*, int)> FMeshRenderBufferSetConversionUtil::PerTriangleColorFunc = nullptr
Per-triangle color function.
Only called if bUsePerTriangleColor=true
Definition at line 318 of file MeshRenderBufferSet.h.
Referenced by UpdateVertexBuffersFromOverlays().
SecondaryTriFilterFunc
TUniqueFunction<bool(const FDynamicMesh3*, int32)> FMeshRenderBufferSetConversionUtil::SecondaryTriFilterFunc = nullptr
Filter predicate for secondary triangle index buffer.
Only called if bUseSecondaryTriBuffers=true
Definition at line 349 of file MeshRenderBufferSet.h.
VertexColorRemappingFunc
TUniqueFunction<void(FVector4f&)> FMeshRenderBufferSetConversionUtil::VertexColorRemappingFunc = nullptr
Vertex color remapping function.
Only called if bApplyVertexColorRemapping == true, for mesh vertex colors
Definition at line 328 of file MeshRenderBufferSet.h.
Referenced by GetOverlayColorAsFColor().
The documentation for this struct was generated from the following file:
Runtime/GeometryFramework/Public/Components/MeshRenderBufferSet.h