Unreal Engine 5.6 C++ API: FGraphActionListBuilderBase Struct Reference
FGraphActionListBuilderBase Struct Reference
#include "EdGraphSchema.h"
Public Member Functions
FGraphActionListBuilderBase ()
virtual ~FGraphActionListBuilderBase ()
Virtual destructor.
virtual void AddAction (const TSharedPtr< FEdGraphSchemaAction > &NewAction)
Adds an action entry containing a single action.
void Append (FGraphActionListBuilderBase &Other)
Appends all the action entries from a different graph action builder.
template<typename NodeType>
NodeType * CreateTemplateNode (UClass *Class=NodeType::StaticClass())
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void Empty ()
Clears the action entries.
int32 GetNumActions () const
Returns the current number of entries.
TSharedPtr< FEdGraphSchemaAction > & GetSchemaAction (int32 Index)
Returns the specified entry.
class UE_DEPRECATED (5.5, "ActionGroup has been deprecated - operate only on TSharedPtr<FEdGraphSchemaAction> or const FEdGraphSchemaAction& as appropriate") ActionGroup
A single entry in the list - can contain multiple actions.
UE_DEPRECATED (5.5, "Collections of Action lists were ambiguous and unused - make a compound FEdGraphSchemaAction and Add it") 1 virtual void AddActionList(const TArray< TSharedPtr< FEdGraphSchemaAction > > &NewActions
Adds an action entry containing multiple actions.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.5, "FGraphActionListBuilderBase::ActionGroup has been deprecated, access TSharedPtr<FEdGraphSchemaAction> directly using GetSchemaAction") 1 ActionGroup GetAction(int32 Index)
UE_DEPRECATED (5.5, "Overriding the schema action category is no longer supported, set the category via CosmeticUpdateRootCategory or CosmeticUpdateCategory") 1 virtual void AddAction(const TSharedPtr< FEdGraphSchemaAction > &NewAction
Data Fields
FString const & Category = FString())
UEdGraph * OwnerOfTemporaries
Private Attributes
TArray< TSharedPtr< FEdGraphSchemaAction > > Entries
All of the action entries.
Detailed Description
Definition at line 485 of file EdGraphSchema.h.
Constructor & Destructor Documentation
~FGraphActionListBuilderBase()
virtual FGraphActionListBuilderBase::~FGraphActionListBuilderBase () inline virtual
Virtual destructor.
Definition at line 576 of file EdGraphSchema.h.
FGraphActionListBuilderBase()
FGraphActionListBuilderBase::FGraphActionListBuilderBase () inline
Definition at line 614 of file EdGraphSchema.h.
References OwnerOfTemporaries.
Referenced by Append().
Member Function Documentation
AddAction()
virtual void FGraphActionListBuilderBase::AddAction (const TSharedPtr< FEdGraphSchemaAction > & NewAction) virtual
Adds an action entry containing a single action.
Reimplemented in FCategorizedGraphActionListBuilder.
Referenced by SRigVMActionMenu::TryInsertPromoteToVariable().
Append()
void FGraphActionListBuilderBase::Append (FGraphActionListBuilderBase & Other)
Appends all the action entries from a different graph action builder.
References FGraphActionListBuilderBase(), Append(), and Other.
Referenced by Append().
CreateTemplateNode()
template<typename NodeType> NodeType * FGraphActionListBuilderBase::CreateTemplateNode (UClass * Class = NodeType::StaticClass()) inline
Definition at line 609 of file EdGraphSchema.h.
References Class, CreateTemplateNode(), NewObject, OwnerOfTemporaries, and StaticClass().
Referenced by CreateTemplateNode().
Empty()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void FGraphActionListBuilderBase::Empty () virtual
Clears the action entries.
Reimplemented in FBlueprintActionMenuBuilder, and FRigVMActionMenuBuilder.
References Empty().
Referenced by Empty().
GetNumActions()
int32 FGraphActionListBuilderBase::GetNumActions () const
Returns the current number of entries.
References GetNumActions().
Referenced by GetNumActions().
GetSchemaAction()
TSharedPtr< FEdGraphSchemaAction > & FGraphActionListBuilderBase::GetSchemaAction (int32 Index)
Returns the specified entry.
References GetSchemaAction(), and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by GetSchemaAction().
UE_DEPRECATED() [1/4]
class FGraphActionListBuilderBase::UE_DEPRECATED (5. 5, "ActionGroup has been deprecated - operate only on TSharedPtr<FEdGraphSchemaAction> or const FEdGraphSchemaAction& as appropriate") inline
A single entry in the list - can contain multiple actions.
Constructor accepting a single action
Constructor accepting multiple actions
Move constructor and move assignment operator
Copy constructor and assignment operator
Returns
A reference to the array of strings that represent the category chain
Goes through all actions and calls PerformAction on them individually
Parameters
ParentGraph The graph we are operating in the context of.
FromPins Optional pins that the action was dragged from.
Location The position on the graph to place new nodes.
Returns a the string that should be used when searching for matching actions. Looks only at the first action.
Returns the SearchKeywordsArray
Returns the MenuDescriptionArray
Returns the SearchTitleArray
Returns the SearchCategoryArray
Returns the localized SearchKeywordsArray
Returns the localized MenuDescriptionArray
Returns the localized SearchTitleArray
Returns the localized SearchCategoryArray
All of the actions this entry contains
Concatenates RootCategory with the first action's category (RootCategory coming first, as a prefix, and the splits the category hierarchy apart into separate entries.
Initializes the search text.
The category to list this entry under (could be left empty, as it gets concatenated with the first sub-action's category)
The chain of categories
Definition at line 480 of file EdGraphSchema.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FGraphActionListBuilderBase::UE_DEPRECATED (5. 5, "Collections of Action lists were ambiguous and unused - make a compound FEdGraphSchemaAction and Add it") const &
Adds an action entry containing multiple actions.
References Category, and UE_DEPRECATED().
UE_DEPRECATED() [3/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FGraphActionListBuilderBase::UE_DEPRECATED (5. 5, "FGraphActionListBuilderBase::ActionGroup has been deprecated, access TSharedPtr< FEdGraphSchemaAction > directly using GetSchemaAction")
References PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
FGraphActionListBuilderBase::UE_DEPRECATED (5. 5, "Overriding the schema action category is no longer supported, set the category via CosmeticUpdateRootCategory or CosmeticUpdateCategory") const &
Field Documentation
Category
FString const & FGraphActionListBuilderBase::Category = FString())
Definition at line 581 of file EdGraphSchema.h.
Referenced by UE_DEPRECATED().
Entries
TArray< TSharedPtr<FEdGraphSchemaAction> > FGraphActionListBuilderBase::Entries private
All of the action entries.
Definition at line 571 of file EdGraphSchema.h.
OwnerOfTemporaries
UEdGraph* FGraphActionListBuilderBase::OwnerOfTemporaries
Definition at line 605 of file EdGraphSchema.h.
Referenced by FGraphActionListBuilderBase(), and CreateTemplateNode().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/EdGraph/EdGraphSchema.h