Unreal Engine 5.6 C++ API: TEvaluationTreeEntryContainer< ElementType > Struct Template Reference
TEvaluationTreeEntryContainer< ElementType > Struct Template Reference
Sub-divided container type that allocates smaller 'buckets' of capacity within a single allocation.
#include "MovieSceneEvaluationTree.h"
Data Structures
struct FEntry
Public Member Functions
void Add (FEvaluationTreeEntryHandle ID, ElementType &&Element)
Add a new element to the entry contents with the specified identifier.
FEvaluationTreeEntryHandle AllocateEntry (int32 InitialCapacity=2)
Allocate a new entry of the specified capacity.
void Compact ()
Compress the item array to remove any unused capacity.
TArrayView< ElementType > Get (FEvaluationTreeEntryHandle ID)
Access the entry contents corresponding to the specified ID.
TArrayView< const ElementType > Get (FEvaluationTreeEntryHandle ID) const
Const access to the entry contents corresponding to the specified ID.
void Insert (FEvaluationTreeEntryHandle ID, int32 Index, ElementType &&Element)
Insert a new element to the entry with the specified identifier at a specific index within the entry.
void Reset ()
Reset this container to its default state.
Private Member Functions
void ReserveEntry (FEvaluationTreeEntryHandle ID, int32 NewCapacity)
Reserves the entry with the specified identifier to a new capacity.
Private Attributes
TArray< FEntry > Entries
List of allocated entries for each allocated entry.
TArray< ElementType > Items
Linear array of allocated entry contents.
Friends
FArchive & operator<< (FArchive &Ar, TEvaluationTreeEntryContainer &In)
Serialize this container.
bool operator== (const TEvaluationTreeEntryContainer< ElementType > &A, const TEvaluationTreeEntryContainer< ElementType > &B)
Equality operator.
Detailed Description
template<typename ElementType>
struct TEvaluationTreeEntryContainer< ElementType >
Sub-divided container type that allocates smaller 'buckets' of capacity within a single allocation.
New entries, or entries needing additional capacity are reallocated at the end of the array to avoid reallocation or shuffling. Memory footprint can be compacted once the container is fully built using TEvaluationTreeEntryContainer::Compact Designed specifically to solve allocation cost incurred when compiling very large trees of sequence data. Restrictions: Container can only ever add entries, never remove
Definition at line 74 of file MovieSceneEvaluationTree.h.
Member Function Documentation
Add()
template<typename ElementType> void TEvaluationTreeEntryContainer< ElementType >::Add (FEvaluationTreeEntryHandle ID, ElementType && Element)
Add a new element to the entry contents with the specified identifier.
Parameters
ID The entry identifier, obtained through AllocateEntry
Element The element to add
Definition at line 898 of file MovieSceneEvaluationTree.h.
References TEvaluationTreeEntryContainer< ElementType >::FEntry::Capacity, Entries, ID, Items, FMath::Max, MoveTemp(), ReserveEntry(), TEvaluationTreeEntryContainer< ElementType >::FEntry::Size, and TEvaluationTreeEntryContainer< ElementType >::FEntry::StartIndex.
AllocateEntry()
template<typename ElementType> FEvaluationTreeEntryHandle TEvaluationTreeEntryContainer< ElementType >::AllocateEntry (int32 InitialCapacity = 2)
Allocate a new entry of the specified capacity.
Will default-construct Capacity elements in the item array.
Parameters
InitialCapacity The initial capacity of the entry
Returns
The identifier to be used to access the entry
Definition at line 875 of file MovieSceneEvaluationTree.h.
References Entries, ID, and Items.
Compact()
template<typename ElementType> void TEvaluationTreeEntryContainer< ElementType >::Compact ()
Compress the item array to remove any unused capacity.
Definition at line 937 of file MovieSceneEvaluationTree.h.
References TArray< InElementType, InAllocatorType >::Append(), Entries, INDEX_NONE, Items, MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::Shrink().
Referenced by operator<<.
Get() [1/2]
template<typename ElementType> TArrayView< ElementType > TEvaluationTreeEntryContainer< ElementType >::Get (FEvaluationTreeEntryHandle ID)
Access the entry contents corresponding to the specified ID.
Returns
An array view for the currently allocated elements, not including spare capacity
Definition at line 884 of file MovieSceneEvaluationTree.h.
References Entries, ID, Items, TEvaluationTreeEntryContainer< ElementType >::FEntry::Size, and TEvaluationTreeEntryContainer< ElementType >::FEntry::StartIndex.
Get() [2/2]
template<typename ElementType> TArrayView< const ElementType > TEvaluationTreeEntryContainer< ElementType >::Get (FEvaluationTreeEntryHandle ID) const
Const access to the entry contents corresponding to the specified ID.
Returns
A const array view for the currently allocated elements, not including spare capacity
Definition at line 891 of file MovieSceneEvaluationTree.h.
References Entries, ID, Items, TEvaluationTreeEntryContainer< ElementType >::FEntry::Size, and TEvaluationTreeEntryContainer< ElementType >::FEntry::StartIndex.
Insert()
template<typename ElementType> void TEvaluationTreeEntryContainer< ElementType >::Insert (FEvaluationTreeEntryHandle ID, int32 Index, ElementType && Element)
Insert a new element to the entry with the specified identifier at a specific index within the entry.
Parameters
ID The entry identifier, obtained through AllocateEntry
Index The index within the entry at which to insert the new element
Element The element to add
Definition at line 911 of file MovieSceneEvaluationTree.h.
References TEvaluationTreeEntryContainer< ElementType >::FEntry::Capacity, FMath::Clamp(), DefaultConstructItems(), Entries, ID, Items, FMath::Max, MoveTemp(), RelocateConstructItems(), ReserveEntry(), TEvaluationTreeEntryContainer< ElementType >::FEntry::Size, and TEvaluationTreeEntryContainer< ElementType >::FEntry::StartIndex.
ReserveEntry()
template<typename ElementType> void TEvaluationTreeEntryContainer< ElementType >::ReserveEntry (FEvaluationTreeEntryHandle ID, int32 NewCapacity) private
Reserves the entry with the specified identifier to a new capacity.
Parameters
ID The entry identifier, obtained through AllocateEntry
NewCapacity The new capacity to hold in the entry
Definition at line 962 of file MovieSceneEvaluationTree.h.
References TEvaluationTreeEntryContainer< ElementType >::FEntry::Capacity, check, DefaultConstructItems(), Entries, ID, Items, RelocateConstructItems(), TEvaluationTreeEntryContainer< ElementType >::FEntry::Size, and TEvaluationTreeEntryContainer< ElementType >::FEntry::StartIndex.
Referenced by Add(), and Insert().
Reset()
template<typename ElementType> void TEvaluationTreeEntryContainer< ElementType >::Reset () inline
Reset this container to its default state.
Definition at line 122 of file MovieSceneEvaluationTree.h.
References Entries, and Items.
Friends And Related Symbol Documentation
operator<<
template<typename ElementType> FArchive & operator<< (FArchive & Ar, TEvaluationTreeEntryContainer< ElementType > & In) friend
Serialize this container.
Definition at line 131 of file MovieSceneEvaluationTree.h.
References Ar, Compact(), Entries, FSequencerObjectVersion::GUID, and Items.
operator==
template<typename ElementType> bool operator== (const TEvaluationTreeEntryContainer< ElementType > & A, const TEvaluationTreeEntryContainer< ElementType > & B) friend
Equality operator.
Definition at line 145 of file MovieSceneEvaluationTree.h.
References A, and B.
Field Documentation
Entries
template<typename ElementType> TArray<FEntry> TEvaluationTreeEntryContainer< ElementType >::Entries private
List of allocated entries for each allocated entry.
Should only ever grow, never shrink. Shrinking would cause previously established handles to become invalid.
Definition at line 185 of file MovieSceneEvaluationTree.h.
Referenced by Add(), AllocateEntry(), Compact(), Get(), Get(), Insert(), operator<<, ReserveEntry(), and Reset().
Items
template<typename ElementType> TArray<ElementType> TEvaluationTreeEntryContainer< ElementType >::Items private
Linear array of allocated entry contents.
Once allocated, indices are never invalidated until Compact is called. Entries needing more capacity are re-allocated on the end of the array.
Definition at line 187 of file MovieSceneEvaluationTree.h.
Referenced by Add(), AllocateEntry(), Compact(), Get(), Get(), Insert(), operator<<, ReserveEntry(), and Reset().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieSceneEvaluationTree.h