Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModelTypeID Struct Reference
UE::Sequencer::FViewModelTypeID Struct Reference
#include "ViewModelTypeID.h"
Public Member Functions
FViewModelTypeID (FCastableTypeTable *InTypeTable, uint32 InID)
uint32 GetTypeID () const
Static Public Member Functions
static SEQUENCERCORE_API uint32 RegisterNewID ()
Private Attributes
uint32 ID
FCastableTypeTable * TypeTable
Friends
uint32 GetTypeHash (FViewModelTypeID In)
bool operator< (FViewModelTypeID A, FViewModelTypeID B)
bool operator== (FViewModelTypeID A, FViewModelTypeID B)
Detailed Description
Definition at line 31 of file ViewModelTypeID.h.
Constructor & Destructor Documentation
FViewModelTypeID()
UE::Sequencer::FViewModelTypeID::FViewModelTypeID (FCastableTypeTable * InTypeTable, uint32 InID) inline
Definition at line 55 of file ViewModelTypeID.h.
References ID, and TypeTable.
Referenced by GetTypeHash, operator<, and operator==.
Member Function Documentation
GetTypeID()
uint32 UE::Sequencer::FViewModelTypeID::GetTypeID () const inline
Definition at line 48 of file ViewModelTypeID.h.
References ID.
RegisterNewID()
SEQUENCERCORE_API uint32 UE::Sequencer::FViewModelTypeID::RegisterNewID () static
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FViewModelTypeID In) friend
Definition at line 33 of file ViewModelTypeID.h.
References FViewModelTypeID(), and ID.
operator<
bool operator< (FViewModelTypeID A, FViewModelTypeID B) friend
Definition at line 38 of file ViewModelTypeID.h.
References FViewModelTypeID(), A, and B.
operator==
bool operator== (FViewModelTypeID A, FViewModelTypeID B) friend
Definition at line 43 of file ViewModelTypeID.h.
References FViewModelTypeID(), A, and B.
Field Documentation
ID
uint32 UE::Sequencer::FViewModelTypeID::ID private
Definition at line 63 of file ViewModelTypeID.h.
Referenced by FViewModelTypeID(), GetTypeHash, and GetTypeID().
TypeTable
FCastableTypeTable* UE::Sequencer::FViewModelTypeID::TypeTable private
Definition at line 62 of file ViewModelTypeID.h.
Referenced by FViewModelTypeID().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModelTypeID.h