Unreal Engine 5.6 C++ API: FDynamicAllocReadBuffer Struct Reference
FDynamicAllocReadBuffer Struct Reference
#include "DynamicBufferAllocator.h"
Public Member Functions
void Lock (FRHICommandListBase &RHICmdList)
UE_DEPRECATED (5.3, "Lock now requires a command list.") void Lock()
UE_DEPRECATED (5.3, "Lock now requires a command list.") void Unlock()
void Unlock (FRHICommandListBase &RHICmdList)
Unocks the buffer so the GPU may read from it.
Data Fields
int32 AllocatedByteCount = 0
int32 NumFramesUnused = 0
Number of successive frames for which AllocatedByteCount == 0.
TArray< FShaderResourceViewRHIRef > SubAllocations
Detailed Description
Definition at line 18 of file DynamicBufferAllocator.h.
Member Function Documentation
Lock()
void FDynamicAllocReadBuffer::Lock (FRHICommandListBase & RHICmdList) inline
Definition at line 32 of file DynamicBufferAllocator.h.
References SubAllocations.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/2]
FDynamicAllocReadBuffer::UE_DEPRECATED (5. 3, "Lock now requires a command list.") inline
Definition at line 26 of file DynamicBufferAllocator.h.
References Lock().
UE_DEPRECATED() [2/2]
FDynamicAllocReadBuffer::UE_DEPRECATED (5. 3, "Lock now requires a command list.") inline
Definition at line 29 of file DynamicBufferAllocator.h.
References Unlock().
Unlock()
void FDynamicAllocReadBuffer::Unlock (FRHICommandListBase & RHICmdList) inline
Unocks the buffer so the GPU may read from it.
Definition at line 41 of file DynamicBufferAllocator.h.
References AllocatedByteCount, and NumFramesUnused.
Referenced by UE_DEPRECATED().
Field Documentation
AllocatedByteCount
int32 FDynamicAllocReadBuffer::AllocatedByteCount = 0
Definition at line 20 of file DynamicBufferAllocator.h.
Referenced by Unlock().
NumFramesUnused
int32 FDynamicAllocReadBuffer::NumFramesUnused = 0
Number of successive frames for which AllocatedByteCount == 0.
Used as a metric to decide when to free the allocation.
Definition at line 22 of file DynamicBufferAllocator.h.
Referenced by Unlock().
SubAllocations
TArray<FShaderResourceViewRHIRef> FDynamicAllocReadBuffer::SubAllocations
Definition at line 24 of file DynamicBufferAllocator.h.
Referenced by Lock().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/DynamicBufferAllocator.h