Unreal Engine 5.6 C++ API: FMovieSceneMediaData Struct Reference
FMovieSceneMediaData Struct Reference
Persistent data that's stored for each currently evaluating section.
#include "MovieSceneMediaData.h"
Public Member Functions
MEDIACOMPOSITING_API FMovieSceneMediaData ()
Default constructor.
virtual MEDIACOMPOSITING_API ~FMovieSceneMediaData () override
Virtual destructor.
MEDIACOMPOSITING_API UMediaPlayer * GetMediaPlayer ()
Get the media player used by this persistent data.
UObject * GetPlayerProxy ()
Get the optional proxy object used by this persistent data.
int32 GetProxyLayerIndex ()
Get the layer index we are using (when using a proxy).
MEDIACOMPOSITING_API UMediaTexture * GetProxyMediaTexture ()
Get the proxy media texture.
int32 GetProxyTextureIndex ()
Get the texture index we are using (when using a proxy).
MEDIACOMPOSITING_API void Initialize (bool bIsEvaluating)
Called from FMovieSceneMediaSectionTemplate::Initialize.
MEDIACOMPOSITING_API void SeekOnOpen (FTimespan Time)
Set the time to seek to after opening a media source has finished.
MEDIACOMPOSITING_API void Setup (const TSharedPtr< FMovieSceneMediaPlayerStore > &InMediaPlayerStore, const UObject *InSection, UMediaPlayer *OverrideMediaPlayer, UObject *InPlayerProxy, int32 InProxyLayerIndex, int32 InProxyTextureIndex, const FMovieSceneMediaPlaybackParams &InPlaybackParams)
Set up this persistent data object.
MEDIACOMPOSITING_API void TearDown ()
Called from FMovieSceneMediaSectionTemplate::TearDown.
MEDIACOMPOSITING_API TSharedPtr< FMediaTextureSampleQueue > TransferSampleQueue ()
Retrieve the sample queue and release the ownership.
UE_DEPRECATED (5.6, "Use new Setup function with the playback parameters") MEDIACOMPOSITING_API void Setup(const TSharedPtr< FMovieSceneMediaPlayerStore > &InMediaPlayerStore
Public Member Functions inherited from PropertyTemplate::FSectionData
MOVIESCENE_API FSectionData ()
MOVIESCENE_API void Initialize (FName InPropertyName, FString InPropertyPath)
Initialize track data with the specified property name, path, optional setter function, and optional notify function.
Public Member Functions inherited from IPersistentEvaluationData
virtual ~IPersistentEvaluationData ()
Data Fields
bool bHasBeenExecuted = false
Indicate if the section template has been executed already or not.
bool bIsAspectRatioSet
Stores if the aspect ratio has been set yet.
const UObject UMediaPlayer UObject * InPlayerProxy
const UObject UMediaPlayer UObject int32 InProxyLayerIndex
const UObject UMediaPlayer UObject int32 int32 InProxyTextureIndex
const UObject * InSection
const UObject UMediaPlayer * OverrideMediaPlayer
Data Fields inherited from PropertyTemplate::FSectionData
TSharedPtr< FTrackInstancePropertyBindings > PropertyBindings
Property bindings used to get and set the property.
FMovieSceneAnimTypeID PropertyID
Cached identifier of the property we're editing.
Private Member Functions
MEDIACOMPOSITING_API void HandleMediaPlayerEvent (EMediaEvent Event)
Callback for media player events.
MEDIACOMPOSITING_API void StartUsingProxyMediaTexture ()
Does the work needed so we can use our proxy media texture.
MEDIACOMPOSITING_API void StopUsingProxyMediaTexture ()
Does the work needed when we no longer use our proxy media texture.
Private Attributes
bool bOverrideMediaPlayer
UMediaPlayer * MediaPlayer
The media player used by this object.
TWeakPtr< FMovieSceneMediaPlayerStore > MediaPlayerStoreWeak
Pointer to the media player store this section data was setup with.
FObjectKey MediaSection
Owning Media Section.
FMovieSceneMediaPlaybackParams PlaybackParams
Additional player parameters to set before the first seek.
TWeakObjectPtr< UObject > PlayerProxy
Optional proxy for the media player.
int32 ProxyLayerIndex
Layer that this section should reside in.
TWeakObjectPtr< UMediaTexture > ProxyMediaTexture
Media texture allocated from the proxy.
int32 ProxyTextureIndex
Index of texture allocated from the proxy.
TSharedPtr< FMediaTextureSampleQueue > SampleQueue
Sample queue to be used as video sink for the media player.
FTimespan SeekOnOpenTime
The time to seek to after the media source is opened.
Detailed Description
Persistent data that's stored for each currently evaluating section.
Definition at line 42 of file MovieSceneMediaData.h.
Constructor & Destructor Documentation
FMovieSceneMediaData()
MEDIACOMPOSITING_API FMovieSceneMediaData::FMovieSceneMediaData ()
Default constructor.
References UE_API.
~FMovieSceneMediaData()
virtual MEDIACOMPOSITING_API FMovieSceneMediaData::~FMovieSceneMediaData () override virtual
Virtual destructor.
References UE_API.
Member Function Documentation
GetMediaPlayer()
MEDIACOMPOSITING_API UMediaPlayer * FMovieSceneMediaData::GetMediaPlayer ()
Get the media player used by this persistent data.
Returns
The currently used media player, if any.
References UE_API.
GetPlayerProxy()
UObject * FMovieSceneMediaData::GetPlayerProxy () inline
Get the optional proxy object used by this persistent data.
Definition at line 63 of file MovieSceneMediaData.h.
References PlayerProxy.
GetProxyLayerIndex()
int32 FMovieSceneMediaData::GetProxyLayerIndex () inline
Get the layer index we are using (when using a proxy).
Definition at line 68 of file MovieSceneMediaData.h.
References ProxyLayerIndex.
GetProxyMediaTexture()
MEDIACOMPOSITING_API UMediaTexture * FMovieSceneMediaData::GetProxyMediaTexture ()
Get the proxy media texture.
References GetProxyMediaTexture(), and UE_API.
Referenced by GetProxyMediaTexture().
GetProxyTextureIndex()
int32 FMovieSceneMediaData::GetProxyTextureIndex () inline
Get the texture index we are using (when using a proxy).
Definition at line 73 of file MovieSceneMediaData.h.
References ProxyTextureIndex.
HandleMediaPlayerEvent()
MEDIACOMPOSITING_API void FMovieSceneMediaData::HandleMediaPlayerEvent (EMediaEvent Event) private
Callback for media player events.
References Event, HandleMediaPlayerEvent(), and UE_API.
Referenced by HandleMediaPlayerEvent().
Initialize()
MEDIACOMPOSITING_API void FMovieSceneMediaData::Initialize (bool bIsEvaluating)
Called from FMovieSceneMediaSectionTemplate::Initialize.
References Initialize(), and UE_API.
Referenced by Initialize().
SeekOnOpen()
MEDIACOMPOSITING_API void FMovieSceneMediaData::SeekOnOpen (FTimespan Time)
Set the time to seek to after opening a media source has finished.
Parameters
Time The time to seek to.
References Time, and UE_API.
Setup()
MEDIACOMPOSITING_API void FMovieSceneMediaData::Setup (const TSharedPtr< FMovieSceneMediaPlayerStore > & InMediaPlayerStore, const UObject * InSection, UMediaPlayer * OverrideMediaPlayer, UObject * InPlayerProxy, int32 InProxyLayerIndex, int32 InProxyTextureIndex, const FMovieSceneMediaPlaybackParams & InPlaybackParams)
Set up this persistent data object.
References InPlayerProxy, InProxyLayerIndex, InProxyTextureIndex, InSection, OverrideMediaPlayer, Setup(), and UE_API.
Referenced by Setup().
StartUsingProxyMediaTexture()
MEDIACOMPOSITING_API void FMovieSceneMediaData::StartUsingProxyMediaTexture () private
Does the work needed so we can use our proxy media texture.
References StartUsingProxyMediaTexture(), and UE_API.
Referenced by StartUsingProxyMediaTexture().
StopUsingProxyMediaTexture()
MEDIACOMPOSITING_API void FMovieSceneMediaData::StopUsingProxyMediaTexture () private
Does the work needed when we no longer use our proxy media texture.
References StopUsingProxyMediaTexture(), and UE_API.
Referenced by StopUsingProxyMediaTexture().
TearDown()
MEDIACOMPOSITING_API void FMovieSceneMediaData::TearDown ()
Called from FMovieSceneMediaSectionTemplate::TearDown.
References TearDown(), and UE_API.
Referenced by TearDown().
TransferSampleQueue()
MEDIACOMPOSITING_API TSharedPtr< FMediaTextureSampleQueue > FMovieSceneMediaData::TransferSampleQueue ()
Retrieve the sample queue and release the ownership.
References TransferSampleQueue(), and UE_API.
Referenced by TransferSampleQueue().
UE_DEPRECATED()
FMovieSceneMediaData::UE_DEPRECATED (5. 6, "Use new Setup function with the playback parameters") const &
Field Documentation
bHasBeenExecuted
bool FMovieSceneMediaData::bHasBeenExecuted = false
Indicate if the section template has been executed already or not.
This is used to detect when a evaluation template was rebuilt and has potentially changed.
Definition at line 113 of file MovieSceneMediaData.h.
bIsAspectRatioSet
bool FMovieSceneMediaData::bIsAspectRatioSet
Stores if the aspect ratio has been set yet.
Definition at line 107 of file MovieSceneMediaData.h.
bOverrideMediaPlayer
bool FMovieSceneMediaData::bOverrideMediaPlayer private
Definition at line 130 of file MovieSceneMediaData.h.
InPlayerProxy
const UObject UMediaPlayer UObject* FMovieSceneMediaData::InPlayerProxy
Definition at line 83 of file MovieSceneMediaData.h.
Referenced by Setup().
InProxyLayerIndex
const UObject UMediaPlayer UObject int32 FMovieSceneMediaData::InProxyLayerIndex
Definition at line 83 of file MovieSceneMediaData.h.
Referenced by Setup().
InProxyTextureIndex
const UObject UMediaPlayer UObject int32 int32 FMovieSceneMediaData::InProxyTextureIndex
Definition at line 83 of file MovieSceneMediaData.h.
Referenced by Setup().
InSection
const UObject* FMovieSceneMediaData::InSection
Definition at line 83 of file MovieSceneMediaData.h.
Referenced by Setup().
MediaPlayer
UMediaPlayer* FMovieSceneMediaData::MediaPlayer private
The media player used by this object.
Definition at line 133 of file MovieSceneMediaData.h.
MediaPlayerStoreWeak
TWeakPtr<FMovieSceneMediaPlayerStore> FMovieSceneMediaData::MediaPlayerStoreWeak private
Pointer to the media player store this section data was setup with.
Will be used to return the media player to the store on destruction.
Definition at line 156 of file MovieSceneMediaData.h.
MediaSection
FObjectKey FMovieSceneMediaData::MediaSection private
Owning Media Section.
Used as persistent identifier for media player data.
Definition at line 159 of file MovieSceneMediaData.h.
OverrideMediaPlayer
const UObject UMediaPlayer* FMovieSceneMediaData::OverrideMediaPlayer
Definition at line 83 of file MovieSceneMediaData.h.
Referenced by Setup().
PlaybackParams
FMovieSceneMediaPlaybackParams FMovieSceneMediaData::PlaybackParams private
Additional player parameters to set before the first seek.
Definition at line 162 of file MovieSceneMediaData.h.
PlayerProxy
TWeakObjectPtr<UObject> FMovieSceneMediaData::PlayerProxy private
Optional proxy for the media player.
Definition at line 135 of file MovieSceneMediaData.h.
Referenced by GetPlayerProxy().
ProxyLayerIndex
int32 FMovieSceneMediaData::ProxyLayerIndex private
Layer that this section should reside in.
Definition at line 139 of file MovieSceneMediaData.h.
Referenced by GetProxyLayerIndex().
ProxyMediaTexture
TWeakObjectPtr<UMediaTexture> FMovieSceneMediaData::ProxyMediaTexture private
Media texture allocated from the proxy.
Definition at line 137 of file MovieSceneMediaData.h.
ProxyTextureIndex
int32 FMovieSceneMediaData::ProxyTextureIndex private
Index of texture allocated from the proxy.
Definition at line 141 of file MovieSceneMediaData.h.
Referenced by GetProxyTextureIndex().
SampleQueue
TSharedPtr<FMediaTextureSampleQueue> FMovieSceneMediaData::SampleQueue private
Sample queue to be used as video sink for the media player.
It is owned by the media section because it must be set in the player prior to entering the playback section, i.e. in preroll. We can't ue the internal media texture sample queue because it is in use by another section during this section's preroll. Each section needs it's sample queue independently of the media texture.
Definition at line 150 of file MovieSceneMediaData.h.
SeekOnOpenTime
FTimespan FMovieSceneMediaData::SeekOnOpenTime private
The time to seek to after the media source is opened.
Definition at line 153 of file MovieSceneMediaData.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/MediaCompositing/Source/MediaCompositing/Public/MovieSceneMediaData.h