Unreal Engine 5.6 C++ API: FStaticMeshVertexBuffers Struct Reference
FStaticMeshVertexBuffers Struct Reference
#include "StaticMeshResources.h"
Public Member Functions
void InitComponentVF (FLocalVertexFactory *VertexFactory, int32 LightMapCoordinateIndex, bool bOverrideColorVertexBuffer, FLocalVertexFactory::FDataType &OutDat) const
void InitFromDynamicVertex (FLocalVertexFactory *VertexFactory, TArray< FDynamicMeshVertex > &Vertices, uint32 NumTexCoords=1, uint32 LightMapIndex=0)
void InitFromDynamicVertex (FRenderCommandPipe *RenderCommandPipe, FLocalVertexFactory *VertexFactory, TArray< FDynamicMeshVertex > &Vertices, uint32 NumTexCoords=1, uint32 LightMapIndex=0)
void InitFromDynamicVertex (FRHICommandListBase &RHICmdList, FLocalVertexFactory *VertexFactory, TArray< FDynamicMeshVertex > &Vertices, uint32 NumTexCoords=1, uint32 LightMapIndex=0)
void InitModelBuffers (TArray< FModelVertex > &Vertices)
void InitModelVF (FLocalVertexFactory *VertexFactory)
void InitModelVF (FRenderCommandPipe *RenderCommandPipe, FLocalVertexFactory *VertexFactory)
void InitModelVF (FRHICommandListBase &RHICmdList, FLocalVertexFactory *VertexFactory)
void InitWithDummyData (FLocalVertexFactory *VertexFactory, uint32 NumVertices, uint32 NumTexCoords=1, uint32 LightMapIndex=0)
void InitWithDummyData (FRenderCommandPipe *RenderCommandPipe, FLocalVertexFactory *VertexFactory, uint32 NumVertices, uint32 NumTexCoords=1, uint32 LightMapIndex=0)
void InitWithDummyData (FRHICommandListBase &RHICmdList, FLocalVertexFactory *VertexFactory, uint32 NumVertices, uint32 NumTexCoords=1, uint32 LightMapIndex=0)
void SetOwnerName (FName OwnerName)
Data Fields
FColorVertexBuffer ColorVertexBuffer
The buffer containing the vertex color data.
FPositionVertexBuffer PositionVertexBuffer
The buffer containing the position vertex data.
FStaticMeshVertexBuffer StaticMeshVertexBuffer
The buffer containing vertex data.
Private Member Functions
void InitFromDynamicVertex (FRHICommandListBase *RHICmdList, FRenderCommandPipe *RenderCommandPipe, FLocalVertexFactory *VertexFactory, TArray< FDynamicMeshVertex > &Vertices, uint32 NumTexCoords, uint32 LightMapIndex)
void InitModelVF (FRHICommandListBase *RHICmdList, FRenderCommandPipe *RenderCommandPipe, FLocalVertexFactory *VertexFactory)
void InitWithDummyData (FRHICommandListBase *RHICmdList, FRenderCommandPipe *RenderCommandPipe, FLocalVertexFactory *VertexFactory, uint32 NumVertices, uint32 NumTexCoords, uint32 LightMapIndex)
Detailed Description
Definition at line 319 of file StaticMeshResources.h.
Member Function Documentation
InitComponentVF()
void FStaticMeshVertexBuffers::InitComponentVF (FLocalVertexFactory * VertexFactory, int32 LightMapCoordinateIndex, bool bOverrideColorVertexBuffer, FLocalVertexFactory::FDataType & OutDat) const
References LightMapCoordinateIndex, and VertexFactory.
InitFromDynamicVertex() [1/4]
void FStaticMeshVertexBuffers::InitFromDynamicVertex (FLocalVertexFactory * VertexFactory, TArray< FDynamicMeshVertex > & Vertices, uint32 NumTexCoords = 1, uint32 LightMapIndex = 0) inline
Definition at line 355 of file StaticMeshResources.h.
References InitFromDynamicVertex(), and VertexFactory.
InitFromDynamicVertex() [2/4]
void FStaticMeshVertexBuffers::InitFromDynamicVertex (FRenderCommandPipe * RenderCommandPipe, FLocalVertexFactory * VertexFactory, TArray< FDynamicMeshVertex > & Vertices, uint32 NumTexCoords = 1, uint32 LightMapIndex = 0) inline
Definition at line 350 of file StaticMeshResources.h.
References InitFromDynamicVertex(), and VertexFactory.
InitFromDynamicVertex() [3/4]
void FStaticMeshVertexBuffers::InitFromDynamicVertex (FRHICommandListBase & RHICmdList, FLocalVertexFactory * VertexFactory, TArray< FDynamicMeshVertex > & Vertices, uint32 NumTexCoords = 1, uint32 LightMapIndex = 0) inline
Definition at line 345 of file StaticMeshResources.h.
References InitFromDynamicVertex(), and VertexFactory.
Referenced by InitFromDynamicVertex(), InitFromDynamicVertex(), and InitFromDynamicVertex().
InitFromDynamicVertex() [4/4]
void FStaticMeshVertexBuffers::InitFromDynamicVertex (FRHICommandListBase * RHICmdList, FRenderCommandPipe * RenderCommandPipe, FLocalVertexFactory * VertexFactory, TArray< FDynamicMeshVertex > & Vertices, uint32 NumTexCoords, uint32 LightMapIndex) private
References VertexFactory.
InitModelBuffers()
void FStaticMeshVertexBuffers::InitModelBuffers (TArray< FModelVertex > & Vertices)
InitModelVF() [1/4]
void FStaticMeshVertexBuffers::InitModelVF (FLocalVertexFactory * VertexFactory) inline
Definition at line 373 of file StaticMeshResources.h.
References InitModelVF(), and VertexFactory.
InitModelVF() [2/4]
void FStaticMeshVertexBuffers::InitModelVF (FRenderCommandPipe * RenderCommandPipe, FLocalVertexFactory * VertexFactory) inline
Definition at line 368 of file StaticMeshResources.h.
References InitModelVF(), and VertexFactory.
InitModelVF() [3/4]
void FStaticMeshVertexBuffers::InitModelVF (FRHICommandListBase & RHICmdList, FLocalVertexFactory * VertexFactory) inline
Definition at line 363 of file StaticMeshResources.h.
References InitModelVF(), and VertexFactory.
Referenced by InitModelVF(), InitModelVF(), and InitModelVF().
InitModelVF() [4/4]
void FStaticMeshVertexBuffers::InitModelVF (FRHICommandListBase * RHICmdList, FRenderCommandPipe * RenderCommandPipe, FLocalVertexFactory * VertexFactory) private
References VertexFactory.
InitWithDummyData() [1/4]
void FStaticMeshVertexBuffers::InitWithDummyData (FLocalVertexFactory * VertexFactory, uint32 NumVertices, uint32 NumTexCoords = 1, uint32 LightMapIndex = 0) inline
Definition at line 340 of file StaticMeshResources.h.
References InitWithDummyData(), and VertexFactory.
InitWithDummyData() [2/4]
void FStaticMeshVertexBuffers::InitWithDummyData (FRenderCommandPipe * RenderCommandPipe, FLocalVertexFactory * VertexFactory, uint32 NumVertices, uint32 NumTexCoords = 1, uint32 LightMapIndex = 0) inline
Definition at line 335 of file StaticMeshResources.h.
References InitWithDummyData(), and VertexFactory.
InitWithDummyData() [3/4]
void FStaticMeshVertexBuffers::InitWithDummyData (FRHICommandListBase & RHICmdList, FLocalVertexFactory * VertexFactory, uint32 NumVertices, uint32 NumTexCoords = 1, uint32 LightMapIndex = 0) inline
Definition at line 330 of file StaticMeshResources.h.
References InitWithDummyData(), and VertexFactory.
Referenced by InitWithDummyData(), InitWithDummyData(), and InitWithDummyData().
InitWithDummyData() [4/4]
void FStaticMeshVertexBuffers::InitWithDummyData (FRHICommandListBase * RHICmdList, FRenderCommandPipe * RenderCommandPipe, FLocalVertexFactory * VertexFactory, uint32 NumVertices, uint32 NumTexCoords, uint32 LightMapIndex) private
References VertexFactory.
SetOwnerName()
void FStaticMeshVertexBuffers::SetOwnerName (FName OwnerName) inline
Definition at line 378 of file StaticMeshResources.h.
References ColorVertexBuffer, PositionVertexBuffer, and StaticMeshVertexBuffer.
Field Documentation
ColorVertexBuffer
FColorVertexBuffer FStaticMeshVertexBuffers::ColorVertexBuffer
The buffer containing the vertex color data.
Definition at line 328 of file StaticMeshResources.h.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData(), FSkeletalMeshStreamOut::ReleaseBuffers(), SetOwnerName(), and FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
PositionVertexBuffer
FPositionVertexBuffer FStaticMeshVertexBuffers::PositionVertexBuffer
The buffer containing the position vertex data.
Definition at line 325 of file StaticMeshResources.h.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData(), FSkeletalMeshStreamOut::ReleaseBuffers(), SetOwnerName(), and FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
StaticMeshVertexBuffer
FStaticMeshVertexBuffer FStaticMeshVertexBuffers::StaticMeshVertexBuffer
The buffer containing vertex data.
Definition at line 322 of file StaticMeshResources.h.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData(), FSkeletalMeshStreamOut::ReleaseBuffers(), SetOwnerName(), and FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/StaticMeshResources.h