Unreal Engine 5.6 C++ API: UE::GC::FProcessorStats Struct Reference
UE::GC::FProcessorStats Struct Reference
#include "FastReferenceCollector.h"
Public Member Functions
FORCEINLINE void AddObjects (uint32 Num)
FORCEINLINE void AddReferences (uint32 Num)
void AddStats (FProcessorStats Stats)
FORCEINLINE void AddVerseCells (uint32 Num)
FORCEINLINE void TrackPotentialGarbageReference (bool bDetectedGarbage)
Data Fields
bool bFoundGarbageRef = false
uint32 NumObjects = 0
uint32 NumReferences = 0
uint32 NumVerseCells = 0
Detailed Description
Definition at line 244 of file FastReferenceCollector.h.
Member Function Documentation
AddObjects()
FORCEINLINE void UE::GC::FProcessorStats::AddObjects (uint32 Num) inline
Definition at line 260 of file FastReferenceCollector.h.
References FORCEINLINE, Num, and NumObjects.
Referenced by AddStats().
AddReferences()
FORCEINLINE void UE::GC::FProcessorStats::AddReferences (uint32 Num) inline
Definition at line 261 of file FastReferenceCollector.h.
References FORCEINLINE, Num, and NumReferences.
Referenced by AddStats().
AddStats()
void UE::GC::FProcessorStats::AddStats (FProcessorStats Stats) inline
Definition at line 266 of file FastReferenceCollector.h.
References AddObjects(), AddReferences(), AddVerseCells(), and TrackPotentialGarbageReference().
AddVerseCells()
FORCEINLINE void UE::GC::FProcessorStats::AddVerseCells (uint32 Num) inline
Definition at line 262 of file FastReferenceCollector.h.
References FORCEINLINE, Num, and NumVerseCells.
Referenced by AddStats().
TrackPotentialGarbageReference()
FORCEINLINE void UE::GC::FProcessorStats::TrackPotentialGarbageReference (bool bDetectedGarbage) inline
Definition at line 263 of file FastReferenceCollector.h.
References bFoundGarbageRef, and FORCEINLINE.
Referenced by AddStats().
Field Documentation
bFoundGarbageRef
bool UE::GC::FProcessorStats::bFoundGarbageRef = false
Definition at line 259 of file FastReferenceCollector.h.
Referenced by TrackPotentialGarbageReference().
NumObjects
uint32 UE::GC::FProcessorStats::NumObjects = 0
Definition at line 256 of file FastReferenceCollector.h.
Referenced by AddObjects().
NumReferences
uint32 UE::GC::FProcessorStats::NumReferences = 0
Definition at line 257 of file FastReferenceCollector.h.
Referenced by AddReferences().
NumVerseCells
uint32 UE::GC::FProcessorStats::NumVerseCells = 0
Definition at line 258 of file FastReferenceCollector.h.
Referenced by AddVerseCells().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/FastReferenceCollector.h