Unreal Engine 5.6 C++ API: FGenericPlatformMemory Struct Reference
FGenericPlatformMemory Struct Reference
Generic implementation for most platforms, these tend to be unused and unimplemented.
#include "GenericPlatformMemory.h"
Data Structures
class FBasicVirtualMemoryBlock
struct FSharedMemoryRegion
Generic representation of a shared memory region.
Public Types
enum EMemoryAllocatorToUse {
Ansi , Stomp , TBB , Jemalloc ,
Binned , Binned2 , Binned3 , Platform ,
Mimalloc , Libpas
}
Which allocator is being used.
enum EMemoryCounterRegion {
MCR_Invalid , MCR_Physical , MCR_GPU , MCR_GPUSystem ,
MCR_TexturePool , MCR_StreamingPool , MCR_UsedStreamingPool , MCR_GPUDefragPool ,
MCR_PhysicalLLM , MCR_MAX
}
Various memory regions that can be used with memory stats.
enum ESharedMemoryAccess { Read = (1 << 1) , Write = (1 << 2) }
Flags used for shared memory creation/open.
Static Public Member Functions
static FMalloc * BaseAllocator ()
static void * BinnedAllocFromOS (SIZE_T Size)
Allocates pages from the OS.
static void BinnedFreeToOS (void *Ptr, SIZE_T Size)
Returns pages allocated by BinnedAllocFromOS to the OS.
static bool BinnedPlatformHasMemoryPoolForThisSize (SIZE_T Size)
Some platforms may pool allocations of this size to reduce OS calls.
static void DumpPlatformAndAllocatorStats (FOutputDevice &Ar)
Dumps basic platform memory statistics and allocator specific statistics into the specified output device.
static void DumpStats (FOutputDevice &Ar)
Dumps basic platform memory statistics into the specified output device.
static uint32 GetBackMemoryPoolSize ()
static const FPlatformMemoryConstants & GetConstants ()
static EPlatformMemorySizeBucket GetMemorySizeBucket ()
Return which "high level", per platform, memory bucket we are in.
static uint64 GetMemoryUsedFast ()
static uint32 GetPhysicalGBRam ()
static FPlatformMemoryStats GetStats ()
static void GetStatsForMallocProfiler (FGenericMemoryStats &out_Stats)
Writes all platform specific current memory statistics in the format usable by the malloc profiler.
static FPlatformMemoryStats GetStatsRaw ()
static void Init ()
Initializes platform memory specific constants.
static bool IsNanoMallocAvailable ()
Nano Malloc is Apple's tiny block allocator.
static void MiMallocInit ()
Performs initial setup for MiMalloc.
static void NanoMallocInit ()
Performs initial setup for Nano malloc.
static void OnOutOfMemory (uint64 Size, uint32 Alignment)
static bool PageProtect (void *const Ptr, const SIZE_T Size, const bool bCanRead, const bool bCanWrite)
Changes the protection on a region of committed pages in the virtual address space.
static bool PtrIsFromNanoMalloc (void *Ptr)
Was this pointer allocated by in the Nano Malloc Zone?
static bool PtrIsOSMalloc (void *Ptr)
Was this pointer allocated by the OS malloc?
static void SetupMemoryPools ()
Initializes the memory pools, should be called by the init function.
Static Public Attributes
static EMemoryAllocatorToUse AllocatorToUse
Current allocator.
static void * BackupOOMMemoryPool
Preallocated buffer to delete on out of memory.
static uint32 BackupOOMMemoryPoolSize
Size of BackupOOMMemoryPool in bytes.
static bool bIsOOM
Set to true if we encounters out of memory.
static uint32 OOMAllocationAlignment
Set to alignment of allocation that triggered out of memory, zero otherwise.
static uint64 OOMAllocationSize
Set to size of allocation that triggered out of memory, zero otherwise.
Memory functions
struct FGenericStatsUpdater
Program memory allocation in bytes.
static uint64 ProgramSize
Program memory allocation in bytes.
static FORCEINLINE void * Memmove (void *Dest, const void *Src, SIZE_T Count)
Copies count bytes of characters from Src to Dest.
static FORCEINLINE int32 Memcmp (const void *Buf1, const void *Buf2, SIZE_T Count)
Program memory allocation in bytes.
static FORCEINLINE void * Memset (void *Dest, uint8 Char, SIZE_T Count)
Program memory allocation in bytes.
static FORCEINLINE void * Memzero (void *Dest, SIZE_T Count)
Program memory allocation in bytes.
static FORCEINLINE void * Memcpy (void *Dest, const void *Src, SIZE_T Count)
Program memory allocation in bytes.
static FORCEINLINE void * BigBlockMemcpy (void *Dest, const void *Src, SIZE_T Count)
Memcpy optimized for big blocks.
static FORCEINLINE void * StreamingMemcpy (void *Dest, const void *Src, SIZE_T Count)
On some platforms memcpy optimized for big blocks that avoid L2 cache pollution are available.
static FORCEINLINE void * ParallelMemcpy (void *Dest, const void *Src, SIZE_T Count, EMemcpyCachePolicy Policy=EMemcpyCachePolicy::StoreCached)
On some platforms memcpy can be distributed over multiple threads for throughput.
static void Memswap (void *Ptr1, void *Ptr2, SIZE_T Size)
Program memory allocation in bytes.
template<typename T>
static FORCEINLINE T ReadUnaligned (const void *Ptr)
Loads a simple POD type from unaligned memory.
template<typename T>
static FORCEINLINE void WriteUnaligned (void *Ptr, const T &InValue)
Stores a simple POD type to unaligned memory.
static FSharedMemoryRegion * MapNamedSharedMemoryRegion (const FString &Name, bool bCreate, uint32 AccessMode, SIZE_T Size)
Maps a named shared memory region into process address space (creates or opens it)
static bool UnmapNamedSharedMemoryRegion (FSharedMemoryRegion *MemoryRegion)
Unmaps a name shared memory region.
static FORCEINLINE bool SupportsFastVRAMMemory ()
Gets whether this platform supports Fast VRAM memory Ie, whether TexCreate_FastVRAM flags actually mean something or not.
static bool IsExtraDevelopmentMemoryAvailable ()
Returns true if debug memory has been assigned to the title for general use.
static uint64 GetExtraDevelopmentMemorySize ()
Returns >0 if debug memory has been assigned to the title for general use.
static uint64 GetProgramSize ()
Returns initial program size or 0 if the platform doesn't track initial program size.
static void SetProgramSize (uint64 InProgramSize)
Sets the initial program size.
static bool GetLLMAllocFunctions (void *(*&OutAllocFunction)(size_t), void(*&OutFreeFunction)(void *, size_t), int32 &OutAlignment)
This function sets AllocFunction and FreeFunction and returns true, or just returns false.
static FORCEINLINE void OnLowLevelMemory_Alloc (void const *Pointer, uint64 Size, uint64 Tag)
Called for all default tracker LLM allocations and frees, when LLM is enabled.
static FORCEINLINE void OnLowLevelMemory_Free (void const *Pointer, uint64 Size, uint64 Tag)
Program memory allocation in bytes.
static void RegisterCustomLLMTags ()
Called once at LLM initialization time to let the platform add any custom tags.
static void UpdateCustomLLMTags ()
Called once per frame when LLM is collating the data for the current frame.
static bool TracksLLMAllocations ()
Indicates whether LLM allocations are already accounted for with tracking and in GetStats.
static bool HasForkPageProtectorEnabled ()
Returns true if Protecting the parent processes pages has been enabled Only supported on platforms that support forking.
static bool GetForkedPageAllocationInfo (TArray< FForkedPageAllocation > &OutPageAllocationInfos)
Return the page allocations from the operating system (/proc/self/smaps).
static FString PrettyMemory (uint64 Memory)
Returns a pretty-string for an amount of memory given in bytes.
static FORCEINLINE bool CanOverallocateVirtualMemory ()
Return true if the platform can allocate a lot more virtual memory than physical memory It's true for most platforms, but iOS needs a special entitlement and Linux a kernel config for this.
template<typename T>
static FORCEINLINE void Valswap (T &A, T &B)
Program memory allocation in bytes.
static void MemswapGreaterThan8 (void *Ptr1, void *Ptr2, SIZE_T Size)
Program memory allocation in bytes.
static void InternalUpdateStats (const FPlatformMemoryStats &MemoryStats)
Updates platform specific stats.
Detailed Description
Generic implementation for most platforms, these tend to be unused and unimplemented.
Definition at line 224 of file GenericPlatformMemory.h.
Member Enumeration Documentation
EMemoryAllocatorToUse
enum FGenericPlatformMemory::EMemoryAllocatorToUse
Which allocator is being used.
Enumerator
Ansi
Stomp
TBB
Jemalloc
Binned
Binned2
Binned3
Platform
Mimalloc
Libpas
Definition at line 263 of file GenericPlatformMemory.h.
EMemoryCounterRegion
enum FGenericPlatformMemory::EMemoryCounterRegion
Various memory regions that can be used with memory stats.
The exact meaning of the enums are relatively platform-dependent, although the general ones (Physical, GPU) are straightforward. A platform can add more of these, and it won't affect other platforms, other than a minuscule amount of memory for the StatManager to track the max available memory for each region (uses an array FPlatformMemory::MCR_MAX big)
Enumerator
MCR_Invalid
MCR_Physical
MCR_GPU
MCR_GPUSystem
MCR_TexturePool
MCR_StreamingPool
MCR_UsedStreamingPool
MCR_GPUDefragPool
MCR_PhysicalLLM
MCR_MAX
Definition at line 248 of file GenericPlatformMemory.h.
ESharedMemoryAccess
enum FGenericPlatformMemory::ESharedMemoryAccess
Flags used for shared memory creation/open.
Enumerator
Read
Write
Definition at line 283 of file GenericPlatformMemory.h.
Member Function Documentation
BaseAllocator()
FMalloc * FGenericPlatformMemory::BaseAllocator () static
Returns
the default allocator.
BigBlockMemcpy()
FORCEINLINE void * FGenericPlatformMemory::BigBlockMemcpy (void * Dest, const void * Src, SIZE_T Count) inline static
Memcpy optimized for big blocks.
Definition at line 597 of file GenericPlatformMemory.h.
References Count, and FORCEINLINE.
Referenced by FMemory::BigBlockMemcpy().
BinnedAllocFromOS()
void * FGenericPlatformMemory::BinnedAllocFromOS (SIZE_T Size) static
Allocates pages from the OS.
Parameters
Size Size to allocate, not necessarily aligned
Returns
OS allocated pointer for use by binned allocator
References TSequenceHistory< HistorySize >::Size.
BinnedFreeToOS()
void FGenericPlatformMemory::BinnedFreeToOS (void * Ptr, SIZE_T Size) static
Returns pages allocated by BinnedAllocFromOS to the OS.
Parameters
A pointer previously returned from BinnedAllocFromOS
Size size of the allocation previously passed to BinnedAllocFromOS
References TSequenceHistory< HistorySize >::Size.
BinnedPlatformHasMemoryPoolForThisSize()
bool FGenericPlatformMemory::BinnedPlatformHasMemoryPoolForThisSize (SIZE_T Size) inline static
Some platforms may pool allocations of this size to reduce OS calls.
This function serves as a hint for BinnedMalloc's CachedOSPageAllocator so it does not cache these allocations additionally
Definition at line 548 of file GenericPlatformMemory.h.
References TSequenceHistory< HistorySize >::Size.
Referenced by FCachedOSPageAllocator::IsOSAllocation().
CanOverallocateVirtualMemory()
FORCEINLINE bool FGenericPlatformMemory::CanOverallocateVirtualMemory () inline static
Return true if the platform can allocate a lot more virtual memory than physical memory It's true for most platforms, but iOS needs a special entitlement and Linux a kernel config for this.
Definition at line 832 of file GenericPlatformMemory.h.
References FORCEINLINE.
DumpPlatformAndAllocatorStats()
void FGenericPlatformMemory::DumpPlatformAndAllocatorStats (FOutputDevice & Ar) static
Dumps basic platform memory statistics and allocator specific statistics into the specified output device.
References Ar.
DumpStats()
void FGenericPlatformMemory::DumpStats (FOutputDevice & Ar) static
Dumps basic platform memory statistics into the specified output device.
References Ar.
GetBackMemoryPoolSize()
uint32 FGenericPlatformMemory::GetBackMemoryPoolSize () inline static
Returns
how much memory the platform should pre-allocate for crash handling (this will be allocated ahead of time, and freed when system runs out of memory).
Definition at line 343 of file GenericPlatformMemory.h.
GetConstants()
const FPlatformMemoryConstants & FGenericPlatformMemory::GetConstants () static
Returns
platform specific memory constants.
GetExtraDevelopmentMemorySize()
uint64 FGenericPlatformMemory::GetExtraDevelopmentMemorySize () static
Returns >0 if debug memory has been assigned to the title for general use.
Only applies to platforms with fixed memory and no paging.
GetForkedPageAllocationInfo()
bool FGenericPlatformMemory::GetForkedPageAllocationInfo (TArray< FForkedPageAllocation > & OutPageAllocationInfos) inline static
Return the page allocations from the operating system (/proc/self/smaps).
This only means something on platforms that can fork and have Copy On Write behavior.
Definition at line 815 of file GenericPlatformMemory.h.
GetLLMAllocFunctions()
bool FGenericPlatformMemory::GetLLMAllocFunctions (void *(*&)(size_t) OutAllocFunction, void(*&)(void *, size_t) OutFreeFunction, int32 & OutAlignment) static
This function sets AllocFunction and FreeFunction and returns true, or just returns false.
These functions are the platform dependant low low low level functions that LLM uses to allocate memory.
GetMemorySizeBucket()
EPlatformMemorySizeBucket FGenericPlatformMemory::GetMemorySizeBucket () static
Return which "high level", per platform, memory bucket we are in.
GetMemoryUsedFast()
uint64 FGenericPlatformMemory::GetMemoryUsedFast () static
Returns
memory used for platforms that can do it quickly (without affecting stat unit much)
GetPhysicalGBRam()
uint32 FGenericPlatformMemory::GetPhysicalGBRam () static
Returns
approximate physical RAM in GB.
GetProgramSize()
uint64 FGenericPlatformMemory::GetProgramSize () inline static
Returns initial program size or 0 if the platform doesn't track initial program size.
Definition at line 759 of file GenericPlatformMemory.h.
References ProgramSize.
GetStats()
FPlatformMemoryStats FGenericPlatformMemory::GetStats () static
Returns
platform specific current memory statistics. Note: On some platforms, unused allocator cached memory is taken into account in AvailablePhysical.
GetStatsForMallocProfiler()
void FGenericPlatformMemory::GetStatsForMallocProfiler (FGenericMemoryStats & out_Stats) static
Writes all platform specific current memory statistics in the format usable by the malloc profiler.
GetStatsRaw()
FPlatformMemoryStats FGenericPlatformMemory::GetStatsRaw () static
Returns
platform specific raw stats.
HasForkPageProtectorEnabled()
bool FGenericPlatformMemory::HasForkPageProtectorEnabled () inline static
Returns true if Protecting the parent processes pages has been enabled Only supported on platforms that support forking.
Definition at line 809 of file GenericPlatformMemory.h.
Init()
void FGenericPlatformMemory::Init () static
Initializes platform memory specific constants.
InternalUpdateStats()
void FGenericPlatformMemory::InternalUpdateStats (const FPlatformMemoryStats & MemoryStats) static protected
Updates platform specific stats.
This method is called through FGenericStatsUpdater from the task graph thread.
IsExtraDevelopmentMemoryAvailable()
bool FGenericPlatformMemory::IsExtraDevelopmentMemoryAvailable () static
Returns true if debug memory has been assigned to the title for general use.
Only applies to platforms with fixed memory and no paging.
IsNanoMallocAvailable()
bool FGenericPlatformMemory::IsNanoMallocAvailable () inline static
Nano Malloc is Apple's tiny block allocator.
Does the Nano malloc zone exist?
Returns
True if Nano malloc is enabled and available.
Definition at line 450 of file GenericPlatformMemory.h.
MapNamedSharedMemoryRegion()
FSharedMemoryRegion * FGenericPlatformMemory::MapNamedSharedMemoryRegion (const FString & Name, bool bCreate, uint32 AccessMode, SIZE_T Size) static
Maps a named shared memory region into process address space (creates or opens it)
Parameters
Name unique name of the shared memory region (should not contain [back]slashes to remain cross-platform).
bCreate whether we're creating it or just opening existing (created by some other process).
AccessMode mode which we will be accessing it (use values from ESharedMemoryAccess)
Size size of the buffer (should be >0. Also, the real size is subject to platform limitations and may be increased to match page size)
Returns
pointer to FSharedMemoryRegion (or its descendants) if successful, NULL if not.
References Name, and TSequenceHistory< HistorySize >::Size.
Memcmp()
FORCEINLINE int32 FGenericPlatformMemory::Memcmp (const void * Buf1, const void * Buf2, SIZE_T Count) inline static
Program memory allocation in bytes.
Definition at line 576 of file GenericPlatformMemory.h.
References Count, and FORCEINLINE.
Referenced by FMemory::Memcmp(), FFileJournalFileHandle::operator!=(), and FFileJournalFileHandle::operator==().
Memcpy()
FORCEINLINE void * FGenericPlatformMemory::Memcpy (void * Dest, const void * Src, SIZE_T Count) inline static
Program memory allocation in bytes.
Definition at line 591 of file GenericPlatformMemory.h.
References Count, and FORCEINLINE.
Referenced by HazardPointer_Impl::FHazardDeleter::FHazardDeleter(), FMemory::Memcpy(), and HazardPointer_Impl::FHazardDeleter::operator=().
Memmove()
FORCEINLINE void * FGenericPlatformMemory::Memmove (void * Dest, const void * Src, SIZE_T Count) inline static
Copies count bytes of characters from Src to Dest.
If some regions of the source area and the destination overlap, memmove ensures that the original source bytes in the overlapping region are copied before being overwritten. NOTE: make sure that the destination buffer is the same size or larger than the source buffer!
Definition at line 571 of file GenericPlatformMemory.h.
References Count, and FORCEINLINE.
Referenced by FMemory::Memmove().
Memset()
FORCEINLINE void * FGenericPlatformMemory::Memset (void * Dest, uint8 Char, SIZE_T Count) inline static
Program memory allocation in bytes.
Definition at line 581 of file GenericPlatformMemory.h.
References Count, and FORCEINLINE.
Referenced by FMemory::Memset(), and TSequenceHistory< HistorySize >::Reset().
Memswap()
void FGenericPlatformMemory::Memswap (void * Ptr1, void * Ptr2, SIZE_T Size) inline static
Program memory allocation in bytes.
Definition at line 631 of file GenericPlatformMemory.h.
References MemswapGreaterThan8(), TSequenceHistory< HistorySize >::Size, and Valswap().
Referenced by FMemory::Memswap().
MemswapGreaterThan8()
void FGenericPlatformMemory::MemswapGreaterThan8 (void * Ptr1, void * Ptr2, SIZE_T Size) static private
Program memory allocation in bytes.
References TSequenceHistory< HistorySize >::Size.
Referenced by Memswap().
Memzero()
FORCEINLINE void * FGenericPlatformMemory::Memzero (void * Dest, SIZE_T Count) inline static
Program memory allocation in bytes.
Definition at line 586 of file GenericPlatformMemory.h.
References Count, and FORCEINLINE.
Referenced by FMemory::Memzero(), and RigVM::ZeroPaddedMemory().
MiMallocInit()
void FGenericPlatformMemory::MiMallocInit () inline static
Performs initial setup for MiMalloc.
This is a noop on platforms that do not support MiMalloc, or when MIMALLOC_ENABLED is not defined.
Definition at line 416 of file GenericPlatformMemory.h.
NanoMallocInit()
void FGenericPlatformMemory::NanoMallocInit () inline static
Performs initial setup for Nano malloc.
This is a noop on non-apple platforms
Definition at line 424 of file GenericPlatformMemory.h.
OnLowLevelMemory_Alloc()
FORCEINLINE void FGenericPlatformMemory::OnLowLevelMemory_Alloc (void const * Pointer, uint64 Size, uint64 Tag) inline static
Called for all default tracker LLM allocations and frees, when LLM is enabled.
Provides a single alloc/free hook that platforms can implement to support platform specific memory analysis tools.
Definition at line 782 of file GenericPlatformMemory.h.
References FORCEINLINE, Pointer, and TSequenceHistory< HistorySize >::Size.
OnLowLevelMemory_Free()
FORCEINLINE void FGenericPlatformMemory::OnLowLevelMemory_Free (void const * Pointer, uint64 Size, uint64 Tag) inline static
Program memory allocation in bytes.
Definition at line 783 of file GenericPlatformMemory.h.
References FORCEINLINE, Pointer, and TSequenceHistory< HistorySize >::Size.
OnOutOfMemory()
void FGenericPlatformMemory::OnOutOfMemory (uint64 Size, uint32 Alignment) static
References TSequenceHistory< HistorySize >::Size.
Referenced by FVirtualAllocator::AllocateVirtualPages(), and FMallocBinnedCommonBase::OutOfMemory().
PageProtect()
bool FGenericPlatformMemory::PageProtect (void *const Ptr, const SIZE_T Size, const bool bCanRead, const bool bCanWrite) static
Changes the protection on a region of committed pages in the virtual address space.
Parameters
Ptr Address to the starting page of the region of pages whose access protection attributes are to be changed.
Size The size of the region whose access protection attributes are to be changed, in bytes.
bCanRead Can the memory be read.
bCanWrite Can the memory be written to.
Returns
True if the specified pages' protection mode was changed.
References TSequenceHistory< HistorySize >::Size.
ParallelMemcpy()
FORCEINLINE void * FGenericPlatformMemory::ParallelMemcpy (void * Dest, const void * Src, SIZE_T Count, EMemcpyCachePolicy Policy = EMemcpyCachePolicy::StoreCached) inline static
On some platforms memcpy can be distributed over multiple threads for throughput.
Definition at line 609 of file GenericPlatformMemory.h.
References Count, FORCEINLINE, and StoreCached.
Referenced by FMemory::ParallelMemcpy().
PrettyMemory()
FString FGenericPlatformMemory::PrettyMemory (uint64 Memory) static
Returns a pretty-string for an amount of memory given in bytes.
Parameters
Memory amount in bytes
Returns
Memory in a pretty formatted string
References Memory.
PtrIsFromNanoMalloc()
bool FGenericPlatformMemory::PtrIsFromNanoMalloc (void * Ptr) inline static
Was this pointer allocated by in the Nano Malloc Zone?
Currently only Apple platforms implement this to detect small block allocations.
Parameters
The pointer to query
Returns
True if this pointer is in the Nano Malloc Region
Definition at line 463 of file GenericPlatformMemory.h.
PtrIsOSMalloc()
bool FGenericPlatformMemory::PtrIsOSMalloc (void * Ptr) inline static
Was this pointer allocated by the OS malloc?
Currently only Apple platforms implement this to detect small block allocations.
Parameters
The pointer to query
Returns
True if this pointer was allocated by the OS.
Definition at line 437 of file GenericPlatformMemory.h.
ReadUnaligned()
template<typename T> FORCEINLINE T FGenericPlatformMemory::ReadUnaligned (const void * Ptr) inline static
Loads a simple POD type from unaligned memory.
Parameters
Ptr unaligned memory of at least size sizeof(T)
Returns
Value at Ptr
Definition at line 693 of file GenericPlatformMemory.h.
References FORCEINLINE.
Referenced by FCbValue::AsDateTimeTicks(), FCbValue::AsFloat32(), FCbValue::AsFloat64(), FCbValue::AsTimeSpanTicks(), FCbValue::AsUuid(), FArchive::FastPathLoad(), FFrame::Read(), FFrame::ReadCodeSkipCount(), FFrame::ReadName(), and FFrame::ReadPointer().
RegisterCustomLLMTags()
void FGenericPlatformMemory::RegisterCustomLLMTags () inline static
Called once at LLM initialization time to let the platform add any custom tags.
Definition at line 788 of file GenericPlatformMemory.h.
SetProgramSize()
void FGenericPlatformMemory::SetProgramSize (uint64 InProgramSize) inline static
Sets the initial program size.
Definition at line 767 of file GenericPlatformMemory.h.
References ProgramSize.
SetupMemoryPools()
void FGenericPlatformMemory::SetupMemoryPools () static
Initializes the memory pools, should be called by the init function.
StreamingMemcpy()
FORCEINLINE void * FGenericPlatformMemory::StreamingMemcpy (void * Dest, const void * Src, SIZE_T Count) inline static
On some platforms memcpy optimized for big blocks that avoid L2 cache pollution are available.
Definition at line 603 of file GenericPlatformMemory.h.
References Count, and FORCEINLINE.
Referenced by FMemory::StreamingMemcpy().
SupportsFastVRAMMemory()
FORCEINLINE bool FGenericPlatformMemory::SupportsFastVRAMMemory () inline static
Gets whether this platform supports Fast VRAM memory Ie, whether TexCreate_FastVRAM flags actually mean something or not.
Returns
bool true if supported, false if not
Definition at line 739 of file GenericPlatformMemory.h.
References FORCEINLINE.
Referenced by FPooledRenderTargetDesc::Compare().
TracksLLMAllocations()
bool FGenericPlatformMemory::TracksLLMAllocations () inline static
Indicates whether LLM allocations are already accounted for with tracking and in GetStats.
Returns true if LLM allocations come from a memory pool separate from the main engine's memory or are already tagged with tracking by the platform memory system. Returns false if LLM uses the regular memory shared with the engine and allocations are not tracked.
See also
GetLLMAllocFunctions
Definition at line 803 of file GenericPlatformMemory.h.
UnmapNamedSharedMemoryRegion()
bool FGenericPlatformMemory::UnmapNamedSharedMemoryRegion (FSharedMemoryRegion * MemoryRegion) static
Unmaps a name shared memory region.
Parameters
MemoryRegion an object that encapsulates a shared memory region (will be destroyed even if function fails!)
Returns
true if successful
UpdateCustomLLMTags()
void FGenericPlatformMemory::UpdateCustomLLMTags () inline static
Called once per frame when LLM is collating the data for the current frame.
Can be used to set platform-specific calculated tag data via SetTagAmountForTracker
Definition at line 794 of file GenericPlatformMemory.h.
Valswap()
template<typename T> FORCEINLINE void FGenericPlatformMemory::Valswap (T & A, T & B) inline static private
Program memory allocation in bytes.
Definition at line 617 of file GenericPlatformMemory.h.
References A, B, and FORCEINLINE.
Referenced by Memswap().
WriteUnaligned()
template<typename T> FORCEINLINE void FGenericPlatformMemory::WriteUnaligned (void * Ptr, const T & InValue) inline static
Stores a simple POD type to unaligned memory.
Parameters
Ptr unaligned memory of at least size sizeof(T)
Value value to write at Ptr
Definition at line 707 of file GenericPlatformMemory.h.
References FORCEINLINE.
Friends And Related Symbol Documentation
FGenericStatsUpdater
friend struct FGenericStatsUpdater friend
Program memory allocation in bytes.
Definition at line 846 of file GenericPlatformMemory.h.
References FGenericStatsUpdater.
Referenced by FGenericStatsUpdater.
Field Documentation
AllocatorToUse
EMemoryAllocatorToUse FGenericPlatformMemory::AllocatorToUse static
Current allocator.
Definition at line 278 of file GenericPlatformMemory.h.
BackupOOMMemoryPool
void* FGenericPlatformMemory::BackupOOMMemoryPool static
Preallocated buffer to delete on out of memory.
Used by OOM handling and crash reporting.
Definition at line 236 of file GenericPlatformMemory.h.
BackupOOMMemoryPoolSize
uint32 FGenericPlatformMemory::BackupOOMMemoryPoolSize static
Size of BackupOOMMemoryPool in bytes.
Definition at line 239 of file GenericPlatformMemory.h.
bIsOOM
bool FGenericPlatformMemory::bIsOOM static
Set to true if we encounters out of memory.
Definition at line 227 of file GenericPlatformMemory.h.
OOMAllocationAlignment
uint32 FGenericPlatformMemory::OOMAllocationAlignment static
Set to alignment of allocation that triggered out of memory, zero otherwise.
Definition at line 233 of file GenericPlatformMemory.h.
OOMAllocationSize
uint64 FGenericPlatformMemory::OOMAllocationSize static
Set to size of allocation that triggered out of memory, zero otherwise.
Definition at line 230 of file GenericPlatformMemory.h.
ProgramSize
uint64 FGenericPlatformMemory::ProgramSize static protected
Program memory allocation in bytes.
Definition at line 852 of file GenericPlatformMemory.h.
Referenced by GetProgramSize(), and SetProgramSize().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformMemory.h