Unreal Engine 5.6 C++ API: UE::Slate::Containers::TObservableArray< InElementType > Struct Template Reference
UE::Slate::Containers::TObservableArray< InElementType > Struct Template Reference
#include "ObservableArray.h"
Public Types
using AllocatorType = typename ArrayType::AllocatorType
using ArrayType = TArray<InElementType>
using ElementType = typename ArrayType::ElementType
using ObservableArrayChangedArgsType = TObservableArrayChangedArgs<InElementType>
using RangedForConstIteratorType = typename ArrayType::RangedForConstIteratorType
using RangedForIteratorType = typename ArrayType::RangedForIteratorType
using SizeType = typename ArrayType::SizeType
Public Member Functions
TObservableArray ()=default
TObservableArray (const ElementType *Ptr, SizeType Count)
template<typename InOtherAllocatorType>
TObservableArray (const TArray< ElementType, InOtherAllocatorType > &Other)
TObservableArray (const TObservableArray &)=delete
TObservableArray (std::initializer_list< ElementType > InitList)
template<typename InOtherAllocatorType>
TObservableArray (TArray< ElementType, InOtherAllocatorType > &&Other)
TObservableArray (TObservableArray &&Other)=delete
~TObservableArray ()
SizeType Add (const ElementType &Item)
SizeType Add (ElementType &&Item)
template<typename OtherElementType, typename OtherAllocatorType>
void Append (const TArray< OtherElementType, OtherAllocatorType > &Source)
template<typename OtherElementType>
void Append (const TObservableArray< OtherElementType > &Source)
template<typename OtherElementType, typename OtherAllocator>
void Append (TArray< OtherElementType, OtherAllocator > &&Source)
RangedForIteratorType begin ()
RangedForConstIteratorType begin () const
template<typename ComparisonType>
bool Contains (const ComparisonType &Item) const
template<typename InPredicate>
SizeType ContainsByPredicate (InPredicate Pred) const
DECLARE_MULTICAST_DELEGATE_OneParam (FArrayChangedDelegate, ObservableArrayChangedArgsType)
template<typename... InArgTypes>
SizeType Emplace (InArgTypes &&... Args)
template<typename... InArgTypes>
void EmplaceAt (SizeType Index, InArgTypes &&... Args)
RangedForIteratorType end ()
RangedForConstIteratorType end () const
SizeType Find (const ElementType &Item) const
template<typename InPredicate>
ElementType * FindByPredicate (InPredicate Pred)
template<typename InPredicate>
const ElementType * FindByPredicate (InPredicate Pred) const
ElementType * GetData ()
const ElementType * GetData () const
template<typename InPredicate>
SizeType IndexOfByPredicate (InPredicate Pred) const
bool IsEmpty () const
bool IsValidIndex (SizeType Index) const
int32 Num () const
FArrayChangedDelegate & OnArrayChanged ()
TObservableArray & operator= (const TObservableArray &)=delete
TObservableArray & operator= (TObservableArray &&Other)=delete
bool operator== (const TObservableArray &OtherArray) const
template<typename InOtherAllocatorType>
bool operator== (TArray< ElementType, InOtherAllocatorType > &OtherArray) const
ElementType & operator[] (SizeType Index)
const ElementType & operator[] (SizeType Index) const
template<typename CountType UE_REQUIRES>
void RemoveAt (SizeType Index, CountType NumToRemove, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void RemoveAt (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
template<typename CountType UE_REQUIRES>
void RemoveAtSwap (SizeType Index, CountType NumToRemove, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
SizeType RemoveSingle (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
SizeType RemoveSingleSwap (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void Reserve (SizeType Number)
void Reset (SizeType NewSize=0)
void Swap (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt") FORCEINLINE void RemoveAt(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap") FORCEINLINE void RemoveAtSwap(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingle") FORCEINLINE SizeType RemoveSingle(const ElementType &Item
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingleSwap") FORCEINLINE SizeType RemoveSingleSwap(const ElementType &Item
template<typename InPredicate>
UE_DEPRECATED (5.4, "IndexByPredicate is deprecated. Use IndexOfByPredicate instead") SizeType IndexByPredicate(InPredicate Pred) const
Data Fields
bool bAllowShrinking
SizeType bool bAllowShrinking
SizeType NumToRemove
Private Attributes
ArrayType Array
FArrayChangedDelegate ArrayChangedDelegate
Friends
template<typename InOtherAllocatorType>
bool operator== (TArray< ElementType, InOtherAllocatorType > &OtherArray, const TObservableArray &Self)
Detailed Description
template<typename InElementType>
struct UE::Slate::Containers::TObservableArray< InElementType >
Definition at line 185 of file ObservableArray.h.
Member Typedef Documentation
AllocatorType
template<typename InElementType> using UE::Slate::Containers::TObservableArray< InElementType >::AllocatorType = typename ArrayType::AllocatorType
Definition at line 191 of file ObservableArray.h.
ArrayType
template<typename InElementType> using UE::Slate::Containers::TObservableArray< InElementType >::ArrayType = TArray<InElementType>
Definition at line 188 of file ObservableArray.h.
ElementType
template<typename InElementType> using UE::Slate::Containers::TObservableArray< InElementType >::ElementType = typename ArrayType::ElementType
Definition at line 190 of file ObservableArray.h.
ObservableArrayChangedArgsType
template<typename InElementType> using UE::Slate::Containers::TObservableArray< InElementType >::ObservableArrayChangedArgsType = TObservableArrayChangedArgs<InElementType>
Definition at line 194 of file ObservableArray.h.
RangedForConstIteratorType
template<typename InElementType> using UE::Slate::Containers::TObservableArray< InElementType >::RangedForConstIteratorType = typename ArrayType::RangedForConstIteratorType
Definition at line 193 of file ObservableArray.h.
RangedForIteratorType
template<typename InElementType> using UE::Slate::Containers::TObservableArray< InElementType >::RangedForIteratorType = typename ArrayType::RangedForIteratorType
Definition at line 192 of file ObservableArray.h.
SizeType
template<typename InElementType> using UE::Slate::Containers::TObservableArray< InElementType >::SizeType = typename ArrayType::SizeType
Definition at line 189 of file ObservableArray.h.
Constructor & Destructor Documentation
TObservableArray() [1/7]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray () default
Referenced by TObservableArray(), TObservableArray(), Append(), operator=(), operator=(), operator==(), and operator==.
TObservableArray() [2/7]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray (const ElementType * Ptr, SizeType Count) inline explicit
Definition at line 200 of file ObservableArray.h.
References Array, and UE::Count.
TObservableArray() [3/7]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray (std::initializer_list< ElementType > InitList) inline
Definition at line 206 of file ObservableArray.h.
References Array.
TObservableArray() [4/7]
template<typename InElementType> template<typename InOtherAllocatorType> UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray (const TArray< ElementType, InOtherAllocatorType > & Other) inline explicit
Definition at line 213 of file ObservableArray.h.
References Array, and Other.
TObservableArray() [5/7]
template<typename InElementType> template<typename InOtherAllocatorType> UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray (TArray< ElementType, InOtherAllocatorType > && Other) inline explicit
Definition at line 220 of file ObservableArray.h.
References Array, MoveTemp(), and Other.
TObservableArray() [6/7]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray (const TObservableArray< InElementType > &) delete
References TObservableArray().
TObservableArray() [7/7]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray (TObservableArray< InElementType > && Other) delete
References TObservableArray(), and Other.
~TObservableArray()
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::~TObservableArray () inline
Definition at line 232 of file ObservableArray.h.
Member Function Documentation
Add() [1/2]
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArray< InElementType >::Add (const ElementType & Item) inline
Definition at line 243 of file ObservableArray.h.
References Array, ArrayChangedDelegate, GetData(), Item, and UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeAddAction().
Add() [2/2]
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArray< InElementType >::Add (ElementType && Item) inline
Definition at line 250 of file ObservableArray.h.
References Array, ArrayChangedDelegate, GetData(), Item, UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeAddAction(), and MoveTempIfPossible().
Append() [1/3]
template<typename InElementType> template<typename OtherElementType, typename OtherAllocatorType> void UE::Slate::Containers::TObservableArray< InElementType >::Append (const TArray< OtherElementType, OtherAllocatorType > & Source) inline
Definition at line 279 of file ObservableArray.h.
References Array, ArrayChangedDelegate, GetData(), UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeAddAction(), and Source.
Append() [2/3]
template<typename InElementType> template<typename OtherElementType> void UE::Slate::Containers::TObservableArray< InElementType >::Append (const TObservableArray< OtherElementType > & Source) inline
Definition at line 273 of file ObservableArray.h.
References TObservableArray(), Append(), and Source.
Referenced by Append().
Append() [3/3]
template<typename InElementType> template<typename OtherElementType, typename OtherAllocator> void UE::Slate::Containers::TObservableArray< InElementType >::Append (TArray< OtherElementType, OtherAllocator > && Source) inline
Definition at line 291 of file ObservableArray.h.
References Array, ArrayChangedDelegate, GetData(), UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeAddAction(), MoveTempIfPossible(), and Source.
begin() [1/2]
template<typename InElementType> RangedForIteratorType UE::Slate::Containers::TObservableArray< InElementType >::begin () inline
Definition at line 553 of file ObservableArray.h.
References Array.
begin() [2/2]
template<typename InElementType> RangedForConstIteratorType UE::Slate::Containers::TObservableArray< InElementType >::begin () const inline
Definition at line 558 of file ObservableArray.h.
References Array.
Contains()
template<typename InElementType> template<typename ComparisonType> bool UE::Slate::Containers::TObservableArray< InElementType >::Contains (const ComparisonType & Item) const inline
Definition at line 493 of file ObservableArray.h.
References Array, and Item.
ContainsByPredicate()
template<typename InElementType> template<typename InPredicate> SizeType UE::Slate::Containers::TObservableArray< InElementType >::ContainsByPredicate (InPredicate Pred) const inline
Definition at line 499 of file ObservableArray.h.
References Array.
DECLARE_MULTICAST_DELEGATE_OneParam()
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::DECLARE_MULTICAST_DELEGATE_OneParam (FArrayChangedDelegate , ObservableArrayChangedArgsType)
Emplace()
template<typename InElementType> template<typename... InArgTypes> SizeType UE::Slate::Containers::TObservableArray< InElementType >::Emplace (InArgTypes &&... Args) inline
Definition at line 258 of file ObservableArray.h.
References Array, ArrayChangedDelegate, Forward(), GetData(), and UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeAddAction().
EmplaceAt()
template<typename InElementType> template<typename... InArgTypes> void UE::Slate::Containers::TObservableArray< InElementType >::EmplaceAt (SizeType Index, InArgTypes &&... Args) inline
Definition at line 266 of file ObservableArray.h.
References Array, ArrayChangedDelegate, Forward(), GetData(), and UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeAddAction().
end() [1/2]
template<typename InElementType> RangedForIteratorType UE::Slate::Containers::TObservableArray< InElementType >::end () inline
Definition at line 563 of file ObservableArray.h.
References Array.
end() [2/2]
template<typename InElementType> RangedForConstIteratorType UE::Slate::Containers::TObservableArray< InElementType >::end () const inline
Definition at line 568 of file ObservableArray.h.
References Array.
Find()
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArray< InElementType >::Find (const ElementType & Item) const inline
Definition at line 504 of file ObservableArray.h.
References Array, and Item.
FindByPredicate() [1/2]
template<typename InElementType> template<typename InPredicate> ElementType * UE::Slate::Containers::TObservableArray< InElementType >::FindByPredicate (InPredicate Pred) inline
Definition at line 510 of file ObservableArray.h.
References Array.
FindByPredicate() [2/2]
template<typename InElementType> template<typename InPredicate> const ElementType * UE::Slate::Containers::TObservableArray< InElementType >::FindByPredicate (InPredicate Pred) const inline
Definition at line 516 of file ObservableArray.h.
References Array.
GetData() [1/2]
template<typename InElementType> ElementType * UE::Slate::Containers::TObservableArray< InElementType >::GetData () inline
Definition at line 482 of file ObservableArray.h.
References Array.
Referenced by Add(), Add(), Append(), Append(), Emplace(), EmplaceAt(), operator[](), and operator[]().
GetData() [2/2]
template<typename InElementType> const ElementType * UE::Slate::Containers::TObservableArray< InElementType >::GetData () const inline
Definition at line 487 of file ObservableArray.h.
References Array.
IndexOfByPredicate()
template<typename InElementType> template<typename InPredicate> SizeType UE::Slate::Containers::TObservableArray< InElementType >::IndexOfByPredicate (InPredicate Pred) const inline
Definition at line 529 of file ObservableArray.h.
References Array.
IsEmpty()
template<typename InElementType> bool UE::Slate::Containers::TObservableArray< InElementType >::IsEmpty () const inline
Definition at line 457 of file ObservableArray.h.
References Array.
IsValidIndex()
template<typename InElementType> bool UE::Slate::Containers::TObservableArray< InElementType >::IsValidIndex (SizeType Index) const inline
Definition at line 467 of file ObservableArray.h.
References Array.
Num()
template<typename InElementType> int32 UE::Slate::Containers::TObservableArray< InElementType >::Num () const inline
Definition at line 462 of file ObservableArray.h.
References Array.
Referenced by RemoveAt(), RemoveAt(), and RemoveAtSwap().
OnArrayChanged()
template<typename InElementType> FArrayChangedDelegate & UE::Slate::Containers::TObservableArray< InElementType >::OnArrayChanged () inline
Definition at line 237 of file ObservableArray.h.
References ArrayChangedDelegate.
Referenced by UE::Slate::ItemsSource::FObservableArrayPointer< InItemType >::FObservableArrayPointer().
operator=() [1/2]
template<typename InElementType> TObservableArray & UE::Slate::Containers::TObservableArray< InElementType >::operator= (const TObservableArray< InElementType > &) delete
References TObservableArray().
operator=() [2/2]
template<typename InElementType> TObservableArray & UE::Slate::Containers::TObservableArray< InElementType >::operator= (TObservableArray< InElementType > && Other) delete
References TObservableArray(), and Other.
operator==() [1/2]
template<typename InElementType> bool UE::Slate::Containers::TObservableArray< InElementType >::operator== (const TObservableArray< InElementType > & OtherArray) const inline
Definition at line 541 of file ObservableArray.h.
References TObservableArray(), and Array.
operator==() [2/2]
template<typename InElementType> template<typename InOtherAllocatorType> bool UE::Slate::Containers::TObservableArray< InElementType >::operator== (TArray< ElementType, InOtherAllocatorType > & OtherArray) const inline
Definition at line 536 of file ObservableArray.h.
References Array.
operator[]() [1/2]
template<typename InElementType> ElementType & UE::Slate::Containers::TObservableArray< InElementType >::operator[] (SizeType Index) inline
Definition at line 472 of file ObservableArray.h.
References GetData().
operator[]() [2/2]
template<typename InElementType> const ElementType & UE::Slate::Containers::TObservableArray< InElementType >::operator[] (SizeType Index) const inline
Definition at line 477 of file ObservableArray.h.
References GetData().
RemoveAt() [1/2]
template<typename InElementType> template<typename CountType UE_REQUIRES> void UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt (SizeType Index, CountType NumToRemove, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 347 of file ObservableArray.h.
References TArray< InElementType, InAllocatorType >::Add(), Array, ArrayChangedDelegate, check, Default, TArray< InElementType, InAllocatorType >::GetData(), UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeRemoveAction(), MoveTemp(), Num(), NumToRemove, and TArray< InElementType, InAllocatorType >::Reserve().
RemoveAt() [2/2]
template<typename InElementType> void UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt (SizeType Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 334 of file ObservableArray.h.
References Array, ArrayChangedDelegate, check, Default, UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeRemoveAction(), MoveTemp(), and Num().
Referenced by RemoveSingle().
RemoveAtSwap() [1/2]
template<typename InElementType> template<typename CountType UE_REQUIRES> void UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap (SizeType Index, CountType NumToRemove, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 395 of file ObservableArray.h.
References TArray< InElementType, InAllocatorType >::Add(), Array, ArrayChangedDelegate, check, Default, TArray< InElementType, InAllocatorType >::GetData(), UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeRemoveSwapAction(), MoveTemp(), Num(), NumToRemove, and TArray< InElementType, InAllocatorType >::Reserve().
RemoveAtSwap() [2/2]
template<typename InElementType> void UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 381 of file ObservableArray.h.
References Array, ArrayChangedDelegate, Default, UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeRemoveSwapAction(), and MoveTemp().
Referenced by RemoveSingleSwap(), and UE_ALLOWSHRINKING_BOOL_DEPRECATED().
RemoveSingle()
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArray< InElementType >::RemoveSingle (const ElementType & Item, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 302 of file ObservableArray.h.
References Array, Default, INDEX_NONE, Item, and RemoveAt().
RemoveSingleSwap()
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArray< InElementType >::RemoveSingleSwap (const ElementType & Item, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 318 of file ObservableArray.h.
References Array, Default, INDEX_NONE, Item, and RemoveAtSwap().
Referenced by UE_ALLOWSHRINKING_BOOL_DEPRECATED().
Reserve()
template<typename InElementType> void UE::Slate::Containers::TObservableArray< InElementType >::Reserve (SizeType Number) inline
Definition at line 452 of file ObservableArray.h.
References Array.
Reset()
template<typename InElementType> void UE::Slate::Containers::TObservableArray< InElementType >::Reset (SizeType NewSize = 0) inline
Definition at line 442 of file ObservableArray.h.
References Array, ArrayChangedDelegate, and UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeResetAction().
Swap()
template<typename InElementType> void UE::Slate::Containers::TObservableArray< InElementType >::Swap (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap) inline
Definition at line 432 of file ObservableArray.h.
References Array, ArrayChangedDelegate, check, and UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeSwapAction().
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [1/4]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [2/4]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap")
References bAllowShrinking, FORCEINLINE, No, NumToRemove, RemoveAtSwap(), and Yes.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [3/4]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingle") const &
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [4/4]
template<typename InElementType> UE::Slate::Containers::TObservableArray< InElementType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingleSwap") const &
References bAllowShrinking, FORCEINLINE, Item, No, RemoveSingleSwap(), and Yes.
UE_DEPRECATED()
template<typename InElementType> template<typename InPredicate> UE::Slate::Containers::TObservableArray< InElementType >::UE_DEPRECATED (5. 4, "IndexByPredicate is deprecated. Use IndexOfByPredicate instead") const inline
Definition at line 522 of file ObservableArray.h.
References Array.
Friends And Related Symbol Documentation
operator==
template<typename InElementType> template<typename InOtherAllocatorType> bool operator== (TArray< ElementType, InOtherAllocatorType > & OtherArray, const TObservableArray< InElementType > & Self) friend
Definition at line 547 of file ObservableArray.h.
References TObservableArray(), and Self.
Field Documentation
Array
template<typename InElementType> ArrayType UE::Slate::Containers::TObservableArray< InElementType >::Array private
Definition at line 574 of file ObservableArray.h.
Referenced by TObservableArray(), TObservableArray(), TObservableArray(), TObservableArray(), Add(), Add(), Append(), Append(), begin(), begin(), Contains(), ContainsByPredicate(), Emplace(), EmplaceAt(), end(), end(), Find(), FindByPredicate(), FindByPredicate(), GetData(), GetData(), IndexOfByPredicate(), IsEmpty(), IsValidIndex(), Num(), operator==(), operator==(), RemoveAt(), RemoveAt(), RemoveAtSwap(), RemoveAtSwap(), RemoveSingle(), RemoveSingleSwap(), Reserve(), Reset(), Swap(), and UE_DEPRECATED().
ArrayChangedDelegate
template<typename InElementType> FArrayChangedDelegate UE::Slate::Containers::TObservableArray< InElementType >::ArrayChangedDelegate private
Definition at line 575 of file ObservableArray.h.
Referenced by Add(), Add(), Append(), Append(), Emplace(), EmplaceAt(), OnArrayChanged(), RemoveAt(), RemoveAt(), RemoveAtSwap(), RemoveAtSwap(), Reset(), and Swap().
bAllowShrinking [1/2]
template<typename InElementType> SizeType bool UE::Slate::Containers::TObservableArray< InElementType >::bAllowShrinking
Initial value:
{
        return RemoveSingle(Item, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 313 of file ObservableArray.h.
Referenced by UE_ALLOWSHRINKING_BOOL_DEPRECATED(), and UE_ALLOWSHRINKING_BOOL_DEPRECATED().
bAllowShrinking [2/2]
template<typename InElementType> SizeType bool UE::Slate::Containers::TObservableArray< InElementType >::bAllowShrinking
Initial value:
{
        RemoveAt(Index, NumToRemove, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 376 of file ObservableArray.h.
NumToRemove
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArray< InElementType >::NumToRemove
Definition at line 376 of file ObservableArray.h.
Referenced by RemoveAt(), RemoveAtSwap(), and UE_ALLOWSHRINKING_BOOL_DEPRECATED().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Containers/ObservableArray.h