Unreal Engine 5.6 C++ API: FWidgetBlueprintApplicationModes Struct Reference
FWidgetBlueprintApplicationModes Struct Reference
#include "WidgetBlueprintApplicationModes.h"
Public Member Functions
UE_DEPRECATED (5.3, "DebugMode is deprecated. Use PreviewMode instead.") static const FName DebugMode
UE_DEPRECATED (5.3, "IsDebugModeEnabled is deprecated. Use IsPreviewModeEnabled instead.") static bool IsDebugModeEnabled()
Static Public Member Functions
static FText GetLocalizedMode (const FName InMode)
static bool IsPreviewModeEnabled ()
Static Public Attributes
static const FName DesignerMode
static const FName GraphMode
static const FName PreviewMode
Private Member Functions
FWidgetBlueprintApplicationModes ()=delete
Detailed Description
Definition at line 13 of file WidgetBlueprintApplicationModes.h.
Constructor & Destructor Documentation
FWidgetBlueprintApplicationModes()
FWidgetBlueprintApplicationModes::FWidgetBlueprintApplicationModes () private delete
References FWidgetBlueprintApplicationModes().
Referenced by FWidgetBlueprintApplicationModes().
Member Function Documentation
GetLocalizedMode()
FText FWidgetBlueprintApplicationModes::GetLocalizedMode (const FName InMode) static
References GetLocalizedMode().
Referenced by GetLocalizedMode().
IsPreviewModeEnabled()
bool FWidgetBlueprintApplicationModes::IsPreviewModeEnabled () static
References IsPreviewModeEnabled().
Referenced by IsPreviewModeEnabled().
UE_DEPRECATED() [1/2]
FWidgetBlueprintApplicationModes::UE_DEPRECATED (5. 3, "DebugMode is deprecated. Use PreviewMode instead.") const
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FWidgetBlueprintApplicationModes::UE_DEPRECATED (5. 3, "IsDebugModeEnabled is deprecated. Use IsPreviewModeEnabled instead.")
References UE_DEPRECATED().
Field Documentation
DesignerMode
const FName FWidgetBlueprintApplicationModes::DesignerMode static
Definition at line 16 of file WidgetBlueprintApplicationModes.h.
GraphMode
const FName FWidgetBlueprintApplicationModes::GraphMode static
Definition at line 17 of file WidgetBlueprintApplicationModes.h.
PreviewMode
const FName FWidgetBlueprintApplicationModes::PreviewMode static
Definition at line 20 of file WidgetBlueprintApplicationModes.h.
The documentation for this struct was generated from the following file:
Editor/UMGEditor/Public/BlueprintModes/WidgetBlueprintApplicationModes.h