Unreal Engine 5.6 C++ API: FSavePackageResultStruct Struct Reference
FSavePackageResultStruct Struct Reference
Struct returned from save package, contains the enum as well as extra data about what was written.
#include "Package.h"
Public Member Functions
FSavePackageResultStruct ()
Constructors, it will implicitly construct from the result enum.
FSavePackageResultStruct (ESavePackageResult InResult)
FSavePackageResultStruct (ESavePackageResult InResult, int64 InTotalFileSize)
FSavePackageResultStruct (ESavePackageResult InResult, int64 InTotalFileSize, uint32 InSerializedPackageFlags)
FSavePackageResultStruct (FSavePackageResultStruct &&Other)
~FSavePackageResultStruct ()
bool IsSuccessful () const
Returns whether the package save was successful.
bool operator!= (const FSavePackageResultStruct &Other) const
FSavePackageResultStruct & operator= (FSavePackageResultStruct &&Other)
bool operator== (const FSavePackageResultStruct &Other) const
UE_DEPRECATED (5.1, "CookedHash is now available through PackageWriter->CommitPackage instead. For waiting on completion in the non-cook case, use UPackage::WaitForAsyncFileWrites.") TFuture< FMD5Hash > CookedHash
UE_DEPRECATED (5.6, "Returning the LinkerSave for comparison is no longer used. Contact Epic if you need this functionality.") 1 FSavePackageResultStruct(ESavePackageResult InResult
UE_DEPRECATED (5.6, "Returning the LinkerSave for comparison is no longer used. Contact Epic if you need this functionality.") TPimplPtr< FLinkerSave > LinkerSave
Data Fields
UE_DEPRECATED(5.6, "Use BuildResultDependencies instead..") TArray< UE UE::Cook::FBuildResultDependenciesMap BuildResultDependencies
TArray< UObject * > Exports
Only populated during cook saves.
TArray< FName > ImportPackages
TArray< UObject * > Imports
Only populated during cook saves.
int64 uint32 InSerializedPackageFlags
int64 InTotalFileSize
int64 uint32 TPimplPtr< FLinkerSave > Linker
UE_INTERNAL TArray< UE::SavePackageUtilities::FPreloadDependency > PreloadDependencies
Only populated during cook saves.
ESavePackageResult Result
Success/failure of the save operation.
TArray< FAssetData > SavedAssets
uint32 SerializedPackageFlags
Serialized package flags.
TArray< FName > SoftPackageReferences
int64 TotalFileSize
Total size of all files written out, including bulk data.
TArray< FName > UntrackedSoftPackageReferences
Detailed Description
Struct returned from save package, contains the enum as well as extra data about what was written.
Definition at line 127 of file Package.h.
Constructor & Destructor Documentation
FSavePackageResultStruct() [1/5]
FSavePackageResultStruct::FSavePackageResultStruct ()
Constructors, it will implicitly construct from the result enum.
Referenced by FSavePackageResultStruct(), ~FSavePackageResultStruct(), operator!=(), operator=(), and operator==().
FSavePackageResultStruct() [2/5]
FSavePackageResultStruct::FSavePackageResultStruct (ESavePackageResult InResult)
FSavePackageResultStruct() [3/5]
FSavePackageResultStruct::FSavePackageResultStruct (ESavePackageResult InResult, int64 InTotalFileSize)
References InTotalFileSize.
FSavePackageResultStruct() [4/5]
FSavePackageResultStruct::FSavePackageResultStruct (ESavePackageResult InResult, int64 InTotalFileSize, uint32 InSerializedPackageFlags)
References InSerializedPackageFlags, and InTotalFileSize.
FSavePackageResultStruct() [5/5]
FSavePackageResultStruct::FSavePackageResultStruct (FSavePackageResultStruct && Other)
References FSavePackageResultStruct(), and Other.
~FSavePackageResultStruct()
FSavePackageResultStruct::~FSavePackageResultStruct ()
References FSavePackageResultStruct().
Member Function Documentation
IsSuccessful()
bool FSavePackageResultStruct::IsSuccessful () const inline
Returns whether the package save was successful.
Definition at line 194 of file Package.h.
References Result.
operator!=()
bool FSavePackageResultStruct::operator!= (const FSavePackageResultStruct & Other) const inline
Definition at line 188 of file Package.h.
References FSavePackageResultStruct(), Other, and Result.
operator=()
FSavePackageResultStruct & FSavePackageResultStruct::operator= (FSavePackageResultStruct && Other)
References FSavePackageResultStruct(), and Other.
operator==()
bool FSavePackageResultStruct::operator== (const FSavePackageResultStruct & Other) const inline
Definition at line 183 of file Package.h.
References FSavePackageResultStruct(), Other, and Result.
UE_DEPRECATED() [1/3]
FSavePackageResultStruct::UE_DEPRECATED (5. 1, "CookedHash is now available through PackageWriter->CommitPackage instead. For waiting on completion in the non-cook case, use UPackage::WaitForAsyncFileWrites.")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FSavePackageResultStruct::UE_DEPRECATED (5. 6, "Returning the LinkerSave for comparison is no longer used. Contact Epic if you need this functionality.")
UE_DEPRECATED() [3/3]
FSavePackageResultStruct::UE_DEPRECATED (5. 6, "Returning the LinkerSave for comparison is no longer used. Contact Epic if you need this functionality.")
References UE_DEPRECATED().
Field Documentation
BuildResultDependencies
UE_DEPRECATED (5.6, "Use BuildResultDependencies instead..") TArray<UE UE::Cook::FBuildResultDependenciesMap FSavePackageResultStruct::BuildResultDependencies
Definition at line 153 of file Package.h.
Exports
TArray<UObject*> FSavePackageResultStruct::Exports
Only populated during cook saves.
Definition at line 158 of file Package.h.
ImportPackages
TArray<FName> FSavePackageResultStruct::ImportPackages
Definition at line 146 of file Package.h.
Imports
TArray<UObject*> FSavePackageResultStruct::Imports
Only populated during cook saves.
Definition at line 156 of file Package.h.
InSerializedPackageFlags
int64 uint32 FSavePackageResultStruct::InSerializedPackageFlags
Definition at line 178 of file Package.h.
Referenced by FSavePackageResultStruct().
InTotalFileSize
int64 FSavePackageResultStruct::InTotalFileSize
Definition at line 177 of file Package.h.
Referenced by FSavePackageResultStruct(), and FSavePackageResultStruct().
Linker
int64 uint32 TPimplPtr<FLinkerSave> FSavePackageResultStruct::Linker
Definition at line 178 of file Package.h.
PreloadDependencies
UE_INTERNAL TArray<UE::SavePackageUtilities::FPreloadDependency> FSavePackageResultStruct::PreloadDependencies
Only populated during cook saves.
The list of object dependencies from exports in this package to other objects, either imports or exports, and also specifying which stage of the source object and which stage of the target object have the dependency. These dependencies are also recorded in the save package and are used for runtime loading of cooked packages. This output variable allows the cooker to run validation on that graph of dependencies. Experimental, may be changed without deprecation.
Definition at line 167 of file Package.h.
Result
ESavePackageResult FSavePackageResultStruct::Result
Success/failure of the save operation.
Definition at line 130 of file Package.h.
Referenced by IsSuccessful(), operator!=(), and operator==().
SavedAssets
TArray<FAssetData> FSavePackageResultStruct::SavedAssets
Definition at line 144 of file Package.h.
SerializedPackageFlags
uint32 FSavePackageResultStruct::SerializedPackageFlags
Serialized package flags.
Definition at line 139 of file Package.h.
SoftPackageReferences
TArray<FName> FSavePackageResultStruct::SoftPackageReferences
Definition at line 147 of file Package.h.
TotalFileSize
int64 FSavePackageResultStruct::TotalFileSize
Total size of all files written out, including bulk data.
Definition at line 133 of file Package.h.
UntrackedSoftPackageReferences
TArray<FName> FSavePackageResultStruct::UntrackedSoftPackageReferences
Definition at line 148 of file Package.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/Package.h