Unreal Engine 5.6 C++ API: FChildren::FWidgetRef Struct Reference
FChildren::FWidgetRef Struct Reference
#include "ChildrenBase.h"
Public Member Functions
FWidgetRef (const FWidgetRef &Other)
FWidgetRef (ECopyConstruct, TSharedRef< SWidget > InWidgetCopy)
FWidgetRef (ERefConstruct, SWidget &InWidgetRef)
FWidgetRef (FWidgetRef &&Other)
SWidget & GetWidget () const
FWidgetRef & operator= (const FWidgetRef &)=delete
FWidgetRef & operator= (FWidgetRef &&)=delete
Private Attributes
TOptional< TSharedRef< SWidget > > WidgetCopy
SWidget & WidgetReference
Detailed Description
Definition at line 127 of file ChildrenBase.h.
Constructor & Destructor Documentation
FWidgetRef() [1/4]
FChildren::FWidgetRef::FWidgetRef (ECopyConstruct , TSharedRef< SWidget > InWidgetCopy) inline
Definition at line 134 of file ChildrenBase.h.
References MoveTemp(), WidgetCopy, and WidgetReference.
Referenced by FWidgetRef(), FWidgetRef(), operator=(), and operator=().
FWidgetRef() [2/4]
FChildren::FWidgetRef::FWidgetRef (ERefConstruct , SWidget & InWidgetRef) inline
Definition at line 138 of file ChildrenBase.h.
References WidgetCopy, and WidgetReference.
FWidgetRef() [3/4]
FChildren::FWidgetRef::FWidgetRef (const FWidgetRef & Other) inline
Definition at line 142 of file ChildrenBase.h.
References FWidgetRef(), Other, WidgetCopy, and WidgetReference.
FWidgetRef() [4/4]
FChildren::FWidgetRef::FWidgetRef (FWidgetRef && Other) inline
Definition at line 146 of file ChildrenBase.h.
References FWidgetRef(), MoveTemp(), Other, WidgetCopy, and WidgetReference.
Member Function Documentation
GetWidget()
SWidget & FChildren::FWidgetRef::GetWidget () const inline
Definition at line 152 of file ChildrenBase.h.
References WidgetReference.
Referenced by FChildren::ForEachWidget().
operator=() [1/2]
FWidgetRef & FChildren::FWidgetRef::operator= (const FWidgetRef &) delete
References FWidgetRef().
operator=() [2/2]
FWidgetRef & FChildren::FWidgetRef::operator= (FWidgetRef &&) delete
References FWidgetRef().
Field Documentation
WidgetCopy
TOptional<TSharedRef<SWidget> > FChildren::FWidgetRef::WidgetCopy private
Definition at line 130 of file ChildrenBase.h.
Referenced by FWidgetRef(), FWidgetRef(), FWidgetRef(), and FWidgetRef().
WidgetReference
SWidget& FChildren::FWidgetRef::WidgetReference private
Definition at line 131 of file ChildrenBase.h.
Referenced by FWidgetRef(), FWidgetRef(), FWidgetRef(), FWidgetRef(), and GetWidget().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Layout/ChildrenBase.h