Unreal Engine 5.6 C++ API: UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 > Struct Template Reference
UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 > Struct Template Reference
#include "Tuple.h"
Public Member Functions
TTupleBaseElement ()
TTupleBaseElement (const TTupleBaseElement &)=default
template<typename ArgType UE_REQUIRES>
TTupleBaseElement (EForwardingConstructor, ArgType &&Arg)
TTupleBaseElement (TTupleBaseElement &&)=default
TTupleBaseElement & operator= (const TTupleBaseElement &)=default
TTupleBaseElement & operator= (TTupleBaseElement &&)=default
Data Fields
T Key
T Value
Detailed Description
template<typename T>
struct UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >
Definition at line 95 of file Tuple.h.
Constructor & Destructor Documentation
TTupleBaseElement() [1/4]
template<typename T> template<typename ArgType UE_REQUIRES> UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::TTupleBaseElement (EForwardingConstructor , ArgType && Arg) inline explicit
Definition at line 101 of file Tuple.h.
References Forward(), and Key.
Referenced by TTupleBaseElement(), TTupleBaseElement(), operator=(), and operator=().
TTupleBaseElement() [2/4]
template<typename T> UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::TTupleBaseElement () inline
Definition at line 106 of file Tuple.h.
References Key.
TTupleBaseElement() [3/4]
template<typename T> UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::TTupleBaseElement (TTupleBaseElement< T, 0, 2 > &&) default
References TTupleBaseElement().
TTupleBaseElement() [4/4]
template<typename T> UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::TTupleBaseElement (const TTupleBaseElement< T, 0, 2 > &) default
References TTupleBaseElement().
Member Function Documentation
operator=() [1/2]
template<typename T> TTupleBaseElement & UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::operator= (const TTupleBaseElement< T, 0, 2 > &) default
References TTupleBaseElement().
operator=() [2/2]
template<typename T> TTupleBaseElement & UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::operator= (TTupleBaseElement< T, 0, 2 > &&) default
References TTupleBaseElement().
Field Documentation
Key
template<typename T> T UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::Key
Definition at line 119 of file Tuple.h.
Referenced by TTupleBaseElement(), and TTupleBaseElement().
Value
T UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::Value
Definition at line 91 of file Tuple.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/Tuple.h