Unreal Engine 5.6 C++ API: FInputKeyManager Struct Reference
FInputKeyManager Struct Reference
#include "InputCoreTypes.h"
Public Member Functions
INPUTCORE_API void GetCodesFromKey (const FKey Key, const uint32 *&KeyCode, const uint32 *&CharCode) const
INPUTCORE_API FKey GetKeyFromCodes (const uint32 KeyCode, const uint32 CharCode) const
Retrieves the key mapped to the specified character code.
INPUTCORE_API void InitKeyMappings ()
Static Public Member Functions
static INPUTCORE_API FInputKeyManager & Get ()
Private Member Functions
FInputKeyManager ()
Private Attributes
TMap< uint32, FKey > KeyMapCharToEnum
TMap< uint32, FKey > KeyMapVirtualToEnum
Static Private Attributes
static TSharedPtr< FInputKeyManager > Instance
Detailed Description
Definition at line 752 of file InputCoreTypes.h.
Constructor & Destructor Documentation
FInputKeyManager()
FInputKeyManager::FInputKeyManager () inline private
Definition at line 766 of file InputCoreTypes.h.
References InitKeyMappings().
Referenced by Get().
Member Function Documentation
Get()
INPUTCORE_API FInputKeyManager & FInputKeyManager::Get () static
References FInputKeyManager().
GetCodesFromKey()
INPUTCORE_API void FInputKeyManager::GetCodesFromKey (const FKey Key, const uint32 *& KeyCode, const uint32 *& CharCode) const
References Key.
GetKeyFromCodes()
INPUTCORE_API FKey FInputKeyManager::GetKeyFromCodes (const uint32 KeyCode, const uint32 CharCode) const
Retrieves the key mapped to the specified character code.
Parameters
KeyCode The key code to get the name for.
InitKeyMappings()
INPUTCORE_API void FInputKeyManager::InitKeyMappings ()
Referenced by FInputKeyManager().
Field Documentation
Instance
TSharedPtr< FInputKeyManager > FInputKeyManager::Instance static private
Definition at line 771 of file InputCoreTypes.h.
KeyMapCharToEnum
TMap<uint32, FKey> FInputKeyManager::KeyMapCharToEnum private
Definition at line 773 of file InputCoreTypes.h.
KeyMapVirtualToEnum
TMap<uint32, FKey> FInputKeyManager::KeyMapVirtualToEnum private
Definition at line 772 of file InputCoreTypes.h.
The documentation for this struct was generated from the following file:
Runtime/InputCore/Classes/InputCoreTypes.h