Unreal Engine 5.6 C++ API: FCancelCompressionSignal Struct Reference
FCancelCompressionSignal Struct Reference
#include "AnimCompressionTypes.h"
Public Member Functions
FCancelCompressionSignal ()=default
FCancelCompressionSignal (const FCancelCompressionSignal &)=default
void Cancel ()
bool IsCancelled () const
FCancelCompressionSignal & operator= (const FCancelCompressionSignal &Other)
Private Attributes
FThreadSafeBool Signal
Detailed Description
Definition at line 174 of file AnimCompressionTypes.h.
Constructor & Destructor Documentation
FCancelCompressionSignal() [1/2]
FCancelCompressionSignal::FCancelCompressionSignal () default
Referenced by FCancelCompressionSignal(), and operator=().
FCancelCompressionSignal() [2/2]
FCancelCompressionSignal::FCancelCompressionSignal (const FCancelCompressionSignal &) default
References FCancelCompressionSignal().
Member Function Documentation
Cancel()
void FCancelCompressionSignal::Cancel () inline
Definition at line 189 of file AnimCompressionTypes.h.
References Signal.
IsCancelled()
bool FCancelCompressionSignal::IsCancelled () const inline
Definition at line 194 of file AnimCompressionTypes.h.
References Signal.
operator=()
FCancelCompressionSignal & FCancelCompressionSignal::operator= (const FCancelCompressionSignal & Other) inline
Definition at line 183 of file AnimCompressionTypes.h.
References FCancelCompressionSignal(), bool, Other, and Signal.
Field Documentation
Signal
FThreadSafeBool FCancelCompressionSignal::Signal private
Definition at line 177 of file AnimCompressionTypes.h.
Referenced by Cancel(), IsCancelled(), and operator=().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/AnimCompressionTypes.h