Unreal Engine 5.6 C++ API: FAnimGraphNodeAlphaOptions Struct Reference
FAnimGraphNodeAlphaOptions Struct Reference
#include "AnimGraphNodeAlphaOptions.h"
Static Public Member Functions
template<typename AnimNodeType>
static void HandleCustomizeDetails (const AnimNodeType &InAnimNode, TSharedRef< IPropertyHandle > InNodeHandle, IDetailLayoutBuilder &InDetailBuilder)
template<typename AnimNodeType>
static void HandleCustomizePinData (const AnimNodeType &InAnimNode, UEdGraphPin *InPin)
template<typename AnimNodeType>
static void HandlePostEditChangeProperty (const AnimNodeType &InAnimNode, UAnimGraphNode_Base *InNode, FPropertyChangedEvent &PropertyChangedEvent)
Detailed Description
Definition at line 13 of file AnimGraphNodeAlphaOptions.h.
Member Function Documentation
HandleCustomizeDetails()
template<typename AnimNodeType> void FAnimGraphNodeAlphaOptions::HandleCustomizeDetails (const AnimNodeType & InAnimNode, TSharedRef< IPropertyHandle > InNodeHandle, IDetailLayoutBuilder & InDetailBuilder) inline static
Definition at line 137 of file AnimGraphNodeAlphaOptions.h.
References Alpha, GET_MEMBER_NAME_CHECKED, and IDetailLayoutBuilder::HideProperty().
HandleCustomizePinData()
template<typename AnimNodeType> void FAnimGraphNodeAlphaOptions::HandleCustomizePinData (const AnimNodeType & InAnimNode, UEdGraphPin * InPin) inline static
Definition at line 43 of file AnimGraphNodeAlphaOptions.h.
References Alpha, GET_MEMBER_NAME_STRING_CHECKED, and UEdGraphPin::PinName.
HandlePostEditChangeProperty()
template<typename AnimNodeType> void FAnimGraphNodeAlphaOptions::HandlePostEditChangeProperty (const AnimNodeType & InAnimNode, UAnimGraphNode_Base * InNode, FPropertyChangedEvent & PropertyChangedEvent) inline static
Definition at line 73 of file AnimGraphNodeAlphaOptions.h.
References Alpha, UEdGraphPin::BreakAllPinLinks(), GET_MEMBER_NAME_STRING_CHECKED, FField::GetFName(), FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(), Max, NSLOCTEXT, UEdGraphPin::PinName, FPropertyChangedEvent::Property, PropertyName, and Scale.
The documentation for this struct was generated from the following file:
Editor/AnimGraph/Public/AnimGraphNodeAlphaOptions.h