Unreal Engine 5.6 C++ API: FInputDeviceTriggerDynamicReleaseDeadZoneProperty Struct Reference
FInputDeviceTriggerDynamicReleaseDeadZoneProperty Struct Reference
A generic input device property that sets "Dynamic Release DeadZones" for Analog Triggers.
#include "IInputInterface.h"
Public Member Functions
FInputDeviceTriggerDynamicReleaseDeadZoneProperty ()
FInputDeviceTriggerDynamicReleaseDeadZoneProperty (EInputDeviceTriggerMask InAffectedTriggers, float InDeadZone)
Public Member Functions inherited from FInputDeviceTriggerProperty
FInputDeviceTriggerProperty (FName InName)
Static Public Member Functions
static FName PropertyName ()
Data Fields
float DeadZone = 1.0f
Data Fields inherited from FInputDeviceTriggerProperty
EInputDeviceTriggerMask AffectedTriggers = EInputDeviceTriggerMask::None
Which trigger this property should effect.
Detailed Description
A generic input device property that sets "Dynamic Release DeadZones" for Analog Triggers.
NOTE: Dynamic Triggers allow for Release and Press to be triggered even if the user fails to fully release the trigger before beginning another press. Smaller deadzones increase this effect. A deadzone of 1.0 isn't dynamic at all.
Definition at line 287 of file IInputInterface.h.
Constructor & Destructor Documentation
FInputDeviceTriggerDynamicReleaseDeadZoneProperty() [1/2]
FInputDeviceTriggerDynamicReleaseDeadZoneProperty::FInputDeviceTriggerDynamicReleaseDeadZoneProperty () inline
Definition at line 289 of file IInputInterface.h.
References FInputDeviceTriggerProperty::FInputDeviceTriggerProperty(), and PropertyName().
FInputDeviceTriggerDynamicReleaseDeadZoneProperty() [2/2]
FInputDeviceTriggerDynamicReleaseDeadZoneProperty::FInputDeviceTriggerDynamicReleaseDeadZoneProperty (EInputDeviceTriggerMask InAffectedTriggers, float InDeadZone) inline
Definition at line 293 of file IInputInterface.h.
References FInputDeviceTriggerProperty::FInputDeviceTriggerProperty(), FInputDeviceTriggerProperty::AffectedTriggers, DeadZone, and PropertyName().
Member Function Documentation
PropertyName()
FName FInputDeviceTriggerDynamicReleaseDeadZoneProperty::PropertyName () inline static
Definition at line 300 of file IInputInterface.h.
References FName.
Referenced by FInputDeviceTriggerDynamicReleaseDeadZoneProperty(), and FInputDeviceTriggerDynamicReleaseDeadZoneProperty().
Field Documentation
DeadZone
float FInputDeviceTriggerDynamicReleaseDeadZoneProperty::DeadZone = 1.0f
Definition at line 302 of file IInputInterface.h.
Referenced by FInputDeviceTriggerDynamicReleaseDeadZoneProperty().
The documentation for this struct was generated from the following file:
Runtime/ApplicationCore/Public/GenericPlatform/IInputInterface.h