Unreal Engine 5.6 C++ API: FStateTreeExecutionContext Struct Reference
FStateTreeExecutionContext Struct Reference
StateTree Execution Context is a helper that is used to update StateTree instance data.
#include "StateTreeExecutionContext.h"
Data Structures
struct FAllowDirectTransitionsScope
Helper struct to track when it is allowed to request transitions.
struct FCollectedExternalDataCache
struct FCurrentFrameStateSelectionEventsScope
Helper struct to track currently processed state selection events.
struct FCurrentlyProcessedFrameScope
Helper struct to track currently processed frame.
struct FCurrentlyProcessedStateScope
Helper struct to track currently processed state.
struct FCurrentlyProcessedTransitionEventScope
Helper struct to track currently processed transition event.
struct FExternalGlobalParameters
Structure to-be-populated and set for any StateTree using any EStateTreeDataSourceType::ExternalGlobalParameterData bindings.
struct FNodeInstanceDataScope
Helper struct to set current node data.
struct FStartParameters
struct FStateSelectionResult
Describes a result of States Selection.
struct FTickTaskArguments
struct FTickTaskResult
Public Member Functions
STATETREEMODULE_API FStateTreeExecutionContext (const FStateTreeExecutionContext &InContextToCopy, const UStateTree &InStateTree, FStateTreeInstanceData &InInstanceData)
Construct an execution context from a parent context and another tree.
STATETREEMODULE_API FStateTreeExecutionContext (const FStateTreeExecutionContext &InContextToCopy, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData &InInstanceData)
Construct an execution context from a parent context and another tree.
STATETREEMODULE_API FStateTreeExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData &InInstanceData, const FOnCollectStateTreeExternalData &CollectExternalDataCallback={}, const EStateTreeRecordTransitions RecordTransitions=EStateTreeRecordTransitions::No)
STATETREEMODULE_API FStateTreeExecutionContext (UObject &InOwner, const UStateTree &InStateTree, FStateTreeInstanceData &InInstanceData, const FOnCollectStateTreeExternalData &CollectExternalDataCallback={}, const EStateTreeRecordTransitions RecordTransitions=EStateTreeRecordTransitions::No)
virtual STATETREEMODULE_API ~FStateTreeExecutionContext ()
STATETREEMODULE_API bool AreContextDataViewsValid () const
STATETREEMODULE_API void BindDelegate (const FStateTreeDelegateListener &Listener, FSimpleDelegate Delegate)
Registers the delegate to the listener.
STATETREEMODULE_API void BroadcastDelegate (const FStateTreeDelegateDispatcher &Dispatcher)
Broadcasts the delegate.
void ConsumeEvent (const FStateTreeSharedEvent &Event)
Consumes and removes the specified event from the event queue.
STATETREEMODULE_API void FinishTask (const FStateTreeTaskBase &Task, EStateTreeFinishTaskType FinishType)
Finishes a task.
STATETREEMODULE_API EStateTreeRunStatus ForceTransition (const FRecordedStateTreeTransitionResult &Transition)
Forces transition to a state from a previously recorded state tree transition result.
template<typename TFunc>
TEnableIf< TIsInvocable< TFunc, FStateTreeSharedEvent >::Value, void >::Type ForEachEvent (TFunc &&Function) const
Iterates over all events.
template<typename TFunc>
TEnableIf< TIsInvocable< TFunc, FStateTreeEvent >::Value, void >::Type ForEachEvent (TFunc &&Function) const
Iterates over all events.
STATETREEMODULE_API FStateTreeDataView GetContextDataByName (const FName Name) const
TConstArrayView< FStateTreeExternalDataDesc > GetContextDataDescs () const
const FStateTreeExecutionFrame * GetCurrentlyProcessedFrame () const
FStateTreeIndex16 GetCurrentlyProcessedNodeIndex () const
FStateTreeDataHandle GetCurrentlyProcessedNodeInstanceData () const
const FStateTreeExecutionFrame * GetCurrentlyProcessedParentFrame () const
FStateTreeStateHandle GetCurrentlyProcessedState () const
const FStateTreeEventQueue & GetEventQueue () const
TConstArrayView< FStateTreeSharedEvent > GetEventsToProcessView () const
template<typename T>
T::DataType & GetExternalData (const T Handle) const
Returns reference to external data based on provided handle.
template<typename T>
T::DataType * GetExternalDataPtr (const T Handle) const
Returns pointer to external data based on provided item handle.
FStateTreeDataView GetExternalDataView (const FStateTreeExternalDataHandle Handle)
const FStateTreeInstanceData * GetInstanceData () const
template<typename T>
T & GetInstanceData (const FStateTreeNodeBase &Node) const
template<typename T>
T::FInstanceDataType & GetInstanceData (const T &Node) const
template<typename T>
T * GetInstanceDataPtr (const FStateTreeNodeBase &Node) const
template<typename T>
TStateTreeInstanceDataStructRef< typename T::FInstanceDataType > GetInstanceDataStructRef (const T &Node) const
STATETREEMODULE_API const FStateTreeReference * GetLinkedStateTreeOverrideForTag (const FGameplayTag StateTag) const
FStateTreeEventQueue & GetMutableEventQueue () const
TArrayView< FStateTreeSharedEvent > GetMutableEventsToProcessView ()
FStateTreeInstanceData * GetMutableInstanceData () const
TConstArrayView< FRecordedStateTreeTransitionResult > GetRecordedTransitions () const
Returns the recorded transitions for this context.
STATETREEMODULE_API FStateTreeWeakExecutionContext MakeWeakExecutionContext () const
STATETREEMODULE_API void RequestTransition (const FStateTreeTransitionRequest &Request)
Requests transition to a state.
STATETREEMODULE_API void RequestTransition (FStateTreeStateHandle TargetState, EStateTreeTransitionPriority Priority=EStateTreeTransitionPriority::Normal, EStateTreeSelectionFallback Fallback=EStateTreeSelectionFallback::None)
Requests transition to a state.
STATETREEMODULE_API void SetCollectExternalDataCallback (const FOnCollectStateTreeExternalData &Callback)
Sets callback used to collect external data views during State Tree execution.
void SetContextData (const FStateTreeExternalDataHandle Handle, FStateTreeDataView DataView)
Sets context data view value for specific item.
STATETREEMODULE_API bool SetContextDataByName (const FName Name, FStateTreeDataView DataView)
Sets the context data based on name (name is defined in the schema), returns true if data was found.
STATETREEMODULE_API void SetExternalGlobalParameters (const FExternalGlobalParameters *Parameters)
STATETREEMODULE_API void SetLinkedStateTreeOverrides (FStateTreeReferenceOverrides InLinkedStateTreeOverrides)
Overrides for linked State Trees.
STATETREEMODULE_API EStateTreeRunStatus Start (const FInstancedPropertyBag *InitialParameters=nullptr, int32 RandomSeed=-1)
Start executing.
STATETREEMODULE_API EStateTreeRunStatus Start (FStartParameters Parameter)
Start executing.
STATETREEMODULE_API EStateTreeRunStatus Stop (const EStateTreeRunStatus CompletionStatus=EStateTreeRunStatus::Stopped)
Stop executing if the tree is running.
STATETREEMODULE_API EStateTreeRunStatus Tick (const float DeltaTime)
Tick the state tree logic, updates the tasks and triggers transitions.
STATETREEMODULE_API EStateTreeRunStatus TickTriggerTransitions ()
Tick the state tree logic partially, triggers the transitions.
STATETREEMODULE_API EStateTreeRunStatus TickUpdateTasks (const float DeltaTime)
Tick the state tree logic partially, updates the tasks.
UE_DEPRECATED (5.5, "Use GetEventsToProcessView() instead.") TConstArrayView< FStateTreeEvent > GetEventsToProcess() const
UE_DEPRECATED (5.5, "Use UE::StateTree::InstanceData::GetDataView instead.") static FStateTreeDataView GetDataView(FStateTreeInstanceStorage &InstanceDataStorage
template<typename T>
PRAGMA_ENABLE_DEPRECATION_WARNINGS PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "FStateTreeWeakTaskRef is no longer used.") FStateTreeWeakTaskRef MakeWeakTaskRefFromInstanceData(const T &InInstanceData) const
template<typename T>
PRAGMA_ENABLE_DEPRECATION_WARNINGS PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "FStateTreeWeakTaskRef is no longer used.") FStateTreeWeakTaskRef MakeWeakTaskRefFromInstanceDataPtr(const T *InInstanceData) const
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "FStateTreeWeakTaskRef is no longer used.") STATETREEMODULE_API FStateTreeWeakTaskRef MakeWeakTaskRef(const FStateTreeTaskBase &Node) const
UE_DEPRECATED (5.6, "Use BindDelegate") STATETREEMODULE_API bool AddDelegateListener(const FStateTreeDelegateListener &Listener
Adds delegate listener.
UE_DEPRECATED (5.6, "Use GetCurrentlyProcessedNodeInstanceData() instead.") FStateTreeDataHandle GetCurrentlyProcessedNode() const
UE_DEPRECATED (5.6, "Use SetLinkedStateTreeOverrides that creates a copy.") STATETREEMODULE_API void SetLinkedStateTreeOverrides(const FStateTreeReferenceOverrides *InLinkedStateTreeOverrides)
Overrides for linked State Trees.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Use UE::StateTree::InstanceData::GetDataView instead.") static FStateTreeDataView GetDataViewFromInstanceStorage(FStateTreeInstanceStorage &InstanceDataStorage
Finishes a task.
UE_DEPRECATED (5.6, "Use UnbindDelegate") STATETREEMODULE_API void RemoveDelegateListener(const FStateTreeDelegateListener &Listener)
Removes delegate listener.
STATETREEMODULE_API void UnbindDelegate (const FStateTreeDelegateListener &Listener)
Unregisters the callback bound to the listener.
Public Member Functions inherited from FStateTreeMinimalExecutionContext
STATETREEMODULE_API FStateTreeMinimalExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData &InInstanceData)
STATETREEMODULE_API FStateTreeMinimalExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceStorage &Storage)
virtual STATETREEMODULE_API ~FStateTreeMinimalExecutionContext ()
STATETREEMODULE_API UE::StateTree::FScheduledTickHandle AddScheduledTickRequest (FStateTreeScheduledTick ScheduledTick)
Adds a scheduled tick request.
STATETREEMODULE_API void RemoveScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle)
Removes a scheduled tick request.
STATETREEMODULE_API void SendEvent (const FGameplayTag Tag, const FConstStructView Payload=FConstStructView(), const FName Origin=FName())
Sends event for the StateTree.
UE_DEPRECATED (5.6, "Use FStateTreeMinimalExecutionContext with the not null pointer.") STATETREEMODULE_API explicit FStateTreeMinimalExecutionContext(UObject &Owner
UE_DEPRECATED (5.6, "Use FStateTreeMinimalExecutionContext with the not null pointer.") STATETREEMODULE_API explicit FStateTreeMinimalExecutionContext(UObject &Owner
STATETREEMODULE_API void UpdateScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle, FStateTreeScheduledTick ScheduledTick)
Updates the scheduled tick of a previous request.
Public Member Functions inherited from FStateTreeReadOnlyExecutionContext
STATETREEMODULE_API FStateTreeReadOnlyExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData &InInstanceData)
STATETREEMODULE_API FStateTreeReadOnlyExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceStorage &Storage)
virtual STATETREEMODULE_API ~FStateTreeReadOnlyExecutionContext ()
STATETREEMODULE_API void DebugPrintInternalLayout ()
STATETREEMODULE_API TConstArrayView< FStateTreeExecutionFrame > GetActiveFrames () const
STATETREEMODULE_API FString GetActiveStateName () const
STATETREEMODULE_API TArray< FName > GetActiveStateNames () const
STATETREEMODULE_API EStateTreeRunStatus GetLastTickStatus () const
STATETREEMODULE_API FStateTreeScheduledTick GetNextScheduledTick () const
UObject * GetOwner () const
STATETREEMODULE_API int32 GetStateChangeCount () const
const FCompactStateTreeState * GetStateFromHandle (const FStateTreeStateHandle StateHandle) const
const UStateTree * GetStateTree () const
STATETREEMODULE_API EStateTreeRunStatus GetStateTreeRunStatus () const
UWorld * GetWorld () const
bool HasEventToProcess (const FGameplayTag Tag) const
bool IsValid () const
Indicates if the instance is valid and would be able to run the instance of the associated StateTree asset with a regular execution context.
Static Public Member Functions
static STATETREEMODULE_API const FStateTreeExecutionFrame * FindFrame (const UStateTree *StateTree, FStateTreeStateHandle RootState, TConstArrayView< FStateTreeExecutionFrame > Frames, const FStateTreeExecutionFrame *&OutParentFrame)
Looks for a frame in provided list of frames.
Data Fields
FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame TConstArrayView< FStateTreeDataView > ContextAndExternalDataViews
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame & CurrentFrame
FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame & CurrentFrame
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceStorage * CurrentlyProcessedSharedInstanceStorage = nullptr
Pointer to the shared instance data of the current frame we're processing.
FStateTreeInstanceStorage * CurrentlyProcessedSharedInstanceStorage = nullptr
Pointer to the shared instance data of the current frame we're processing.
FSimpleDelegate Delegate
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame const FStateTreeDataHandle Handle
FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame TConstArrayView< FStateTreeDataView > const FStateTreeDataHandle Handle
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceStorage const FStateTreeExecutionFrame * ParentFrame
FStateTreeInstanceStorage const FStateTreeExecutionFrame * ParentFrame
Data Fields inherited from FStateTreeMinimalExecutionContext
const UStateTree FStateTreeInstanceData & InInstanceData
const UStateTree & StateTree
const UStateTree FStateTreeInstanceStorage & Storage
Protected Member Functions
STATETREEMODULE_API FStateTreeDataView AddTemporaryInstance (const FStateTreeExecutionFrame &Frame, const FStateTreeIndex16 OwnerNodeIndex, const FStateTreeDataHandle DataHandle, FConstStructView NewInstanceData)
Adds a temporary instance that can be located using frame and data handle later.
virtual void BeginDelayedTransition (const FStateTreeTransitionDelayedState &DelayedState)
Callback when delayed transition is triggered.
STATETREEMODULE_API void CallStopOnEvaluatorsAndGlobalTasks (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &Frame, const FStateTreeTransitionResult &Transition, const FStateTreeIndex16 LastInitializedTaskIndex=FStateTreeIndex16())
Stops evaluators and global tasks of the given frame.
STATETREEMODULE_API void CaptureNewStateEvents (TConstArrayView< FStateTreeExecutionFrame > PrevFrames, TConstArrayView< FStateTreeExecutionFrame > NewFrames, TArrayView< FStateTreeFrameStateSelectionEvents > FramesStateSelectionEvents)
Captures StateTree events used during the state selection.
STATETREEMODULE_API bool CollectActiveExternalData ()
Collects external data for all StateTrees in active frames.
STATETREEMODULE_API FStateTreeIndex16 CollectExternalData (const UStateTree *StateTree)
Collects external data for specific State Tree asset.
STATETREEMODULE_API bool CopyBatchOnActiveInstances (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataView TargetView, const FStateTreeIndex16 BindingsBatch)
Copies a batch of properties to the data in TargetView.
STATETREEMODULE_API bool CopyBatchWithValidation (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataView TargetView, const FStateTreeIndex16 BindingsBatch)
Copies a batch of properties to the data in TargetView.
STATETREEMODULE_API FString DebugGetEventsAsString () const
STATETREEMODULE_API FString DebugGetStatePath (TConstArrayView< FStateTreeExecutionFrame > ActiveFrames, const FStateTreeExecutionFrame *CurrentFrame=nullptr, const int32 ActiveStateIndex=INDEX_NONE) const
STATETREEMODULE_API EStateTreeRunStatus EnterState (FStateTreeTransitionResult &Transition)
Handles logic for entering State.
STATETREEMODULE_API void EvaluatePropertyFunctionsOnActiveInstances (const FStateTreeExecutionFrame *CurrentParentFrame, const FStateTreeExecutionFrame &CurrentFrame, FStateTreeIndex16 FuncsBegin, uint16 FuncsNum)
STATETREEMODULE_API void EvaluatePropertyFunctionsWithValidation (const FStateTreeExecutionFrame *CurrentParentFrame, const FStateTreeExecutionFrame &CurrentFrame, FStateTreeIndex16 FuncsBegin, uint16 FuncsNum)
STATETREEMODULE_API float EvaluateUtility (const FStateTreeExecutionFrame *CurrentParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const int32 ConsiderationsOffset, const int32 ConsiderationsNum, const float StateWeight)
Calculate the final score of all considerations at given range.
STATETREEMODULE_API void ExitState (const FStateTreeTransitionResult &Transition)
Handles logic for exiting State.
STATETREEMODULE_API FStateTreeDataView GetDataView (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FPropertyBindingCopyInfo &CopyInfo)
STATETREEMODULE_API FStateTreeDataView GetDataView (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataHandle Handle)
STATETREEMODULE_API FStateTreeDataView GetDataViewOrTemporary (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FPropertyBindingCopyInfo &CopyInfo)
STATETREEMODULE_API FStateTreeDataView GetDataViewOrTemporary (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataHandle Handle)
FStateTreeExecutionState & GetExecState ()
const FStateTreeExecutionState & GetExecState () const
STATETREEMODULE_API FString GetSafeStateName (const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeStateHandle State) const
STATETREEMODULE_API FString GetStateStatusString (const FStateTreeExecutionState &ExecState) const
STATETREEMODULE_API FStateTreeDataView GetTemporaryDataView (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataHandle Handle)
STATETREEMODULE_API bool IsHandleSourceValid (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FPropertyBindingCopyInfo &CopyInfo) const
STATETREEMODULE_API bool IsHandleSourceValid (const FStateTreeExecutionFrame *ParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataHandle Handle) const
STATETREEMODULE_API FRecordedStateTreeTransitionResult MakeRecordedTransitionResult (const FStateTreeTransitionResult &Transition) const
Create a new recorded transition from a transition result.
STATETREEMODULE_API TOptional< FStateTreeTransitionResult > MakeTransitionResult (const FRecordedStateTreeTransitionResult &Transition) const
Create a new transition result from a recorded transition result.
STATETREEMODULE_API void RemoveAllDelegateListeners ()
Removes all delegate listeners.
STATETREEMODULE_API bool RequestTransition (const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeStateHandle NextState, const EStateTreeTransitionPriority Priority, const FStateTreeSharedEvent *TransitionEvent=nullptr, const EStateTreeSelectionFallback Fallback=EStateTreeSelectionFallback::None)
Requests transition to a specified state with specified priority.
STATETREEMODULE_API bool SelectState (const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeStateHandle NextState, FStateSelectionResult &OutSelectionResult, const FStateTreeSharedEvent *TransitionEvent=nullptr, const EStateTreeSelectionFallback Fallback=EStateTreeSelectionFallback::None)
Runs state selection logic starting at the specified state, walking towards the leaf states.
STATETREEMODULE_API bool SelectStateInternal (const FStateTreeExecutionFrame *CurrentParentFrame, FStateTreeExecutionFrame &CurrentFrame, const FStateTreeExecutionFrame *CurrentFrameInActiveFrames, TConstArrayView< FStateTreeStateHandle > PathToNextState, FStateSelectionResult &OutSelectionResult, const FStateTreeSharedEvent *TransitionEvent=nullptr)
Used internally to do the recursive part of the SelectState().
STATETREEMODULE_API bool SetGlobalParameters (const FInstancedPropertyBag &Parameters)
Stores copy of provided parameters as State Tree global parameters.
STATETREEMODULE_API void SetUpdatePhaseInExecutionState (FStateTreeExecutionState &ExecutionState, EStateTreeUpdatePhase UpdatePhase) const
Updates the update phase of the statetree execution state.
STATETREEMODULE_API void SetupNextTransition (const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeStateHandle NextState, const EStateTreeTransitionPriority Priority)
Sets up NextTransition based on the provided parameters and the current execution status.
STATETREEMODULE_API EStateTreeRunStatus StartEvaluatorsAndGlobalTasks (FStateTreeIndex16 &OutLastInitializedTaskIndex)
Starts evaluators and global tasks.
STATETREEMODULE_API EStateTreeRunStatus StartTemporaryEvaluatorsAndGlobalTasks (const FStateTreeExecutionFrame *CurrentParentFrame, FStateTreeExecutionFrame &CurrentFrame)
Starts temporary instances of global evaluators and tasks for a given frame.
STATETREEMODULE_API void StateCompleted ()
Handles logic for signaling State completed.
STATETREEMODULE_API void StopEvaluatorsAndGlobalTasks (const EStateTreeRunStatus CompletionStatus, const FStateTreeIndex16 LastInitializedTaskIndex=FStateTreeIndex16())
Stops evaluators and global tasks.
STATETREEMODULE_API void StopTemporaryEvaluatorsAndGlobalTasks (const FStateTreeExecutionFrame *CurrentParentFrame, const FStateTreeExecutionFrame &CurrentFrame)
Stops temporary global evaluators and tasks for the provided frame.
STATETREEMODULE_API bool TestAllConditions (const FStateTreeExecutionFrame *CurrentParentFrame, const FStateTreeExecutionFrame &CurrentFrame, const int32 ConditionsOffset, const int32 ConditionsNum)
Checks all conditions at given range.
STATETREEMODULE_API EStateTreeRunStatus TickEvaluatorsAndGlobalTasks (const float DeltaTime, bool bTickGlobalTasks=true)
Tick evaluators and global tasks by delta time.
STATETREEMODULE_API EStateTreeRunStatus TickEvaluatorsAndGlobalTasksForFrame (const float DeltaTime, const bool bTickGlobalTasks, const int32 FrameIndex, const FStateTreeExecutionFrame *CurrentParentFrame, const TNotNull< FStateTreeExecutionFrame * > CurrentFrame)
Tick evaluators and global tasks of a specific frame.
STATETREEMODULE_API EStateTreeRunStatus TickPostlude ()
STATETREEMODULE_API EStateTreeRunStatus TickPrelude ()
Common functionality shared by the tick methods.
STATETREEMODULE_API EStateTreeRunStatus TickTasks (const float DeltaTime)
Ticks tasks of all active states starting from current state by delta time.
STATETREEMODULE_API FTickTaskResult TickTasks (const FTickTaskArguments &Args)
Ticks tasks and updates the bindings for a specific state or frame.
STATETREEMODULE_API void TickTriggerTransitionsInternal ()
Handles transition triggering part of the tick.
STATETREEMODULE_API void TickUpdateTasksInternal (float DeltaTime)
Handles task ticking part of the tick.
STATETREEMODULE_API bool TriggerTransitions ()
Triggers transitions based on current run status.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "FStateTreeWeakTaskRef is no longer used.") STATETREEMODULE_API FStateTreeWeakTaskRef MakeWeakTaskRefInternal() const
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Replaced with FStateTreeTasksCompletionStatus") STATETREEMODULE_API void MarkStateCompleted(UE PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Replaced with FStateTreeTasksCompletionStatus") STATETREEMODULE_API EStateTreeRunStatus GetGlobalTasksCompletedStatesStatus() const
Adds the state to the completed list from a finished task.
UE_DEPRECATED (5.6, "Replaced with FStateTreeTasksCompletionStatus") STATETREEMODULE_API void UpdateCompletedStateList()
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Replaced with FStateTreeTasksCompletionStatus") STATETREEMODULE_API bool IsFinishedTaskValid(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Replaced with FStateTreeTasksCompletionStatus") STATETREEMODULE_API void UpdateCompletedStateList(bool bMarkTaskProcessed)
Confirms that the frame and state ID are valid and the task index is correct.
UE_DEPRECATED (5.6, "Use FStateTreeExecutionExtension::GetInstanceDescription instead") STATETREEMODULE_API virtual FString GetInstanceDescription() const final
UE_DEPRECATED (5.6, "Use Storage instead.") FStateTreeInstanceStorage *InstanceDataStorage
Data storage of the instance data, cached for less indirections.
UE_DEPRECATED (5.6, "Use the non const version of StartTemporaryEvaluatorsAndGlobalTasks") EStateTreeRunStatus StartTemporaryEvaluatorsAndGlobalTasks(const FStateTreeExecutionFrame *CurrentParentFrame
STATETREEMODULE_API void UpdateInstanceData (TConstArrayView< FStateTreeExecutionFrame > CurrentActiveFrames, TArrayView< FStateTreeExecutionFrame > NextActiveFrames)
Protected Member Functions inherited from FStateTreeMinimalExecutionContext
STATETREEMODULE_API void ScheduleNextTick ()
Informs the owner when the instance of the tree must woke up from a scheduled tick sleep.
Protected Member Functions inherited from FStateTreeReadOnlyExecutionContext
STATETREEMODULE_API FString GetInstanceDescriptionInternal () const
Protected Attributes
bool bActiveExternalDataCollected = false
bool bAllowDirectTransitions = false
True if transitions are allowed to be requested directly instead of buffering.
bool bRecordTransitions = false
If true, the state tree context will create snapshots of transition events and capture them within RecordedTransitions for later use.
TArray< FCollectedExternalDataCache, FNonconcurrentLinearArrayAllocator > CollectedExternalCache
FOnCollectStateTreeExternalData CollectExternalDataDelegate
TArray< FStateTreeDataView, FNonconcurrentLinearArrayAllocator > ContextAndExternalDataViews
Data view of the context data.
const FStateTreeExecutionFrame & CurrentFrame
const FStateTreeExecutionFrame * CurrentlyProcessedFrame = nullptr
const FStateTreeExecutionFrame * CurrentlyProcessedParentFrame = nullptr
Current frame we're processing.
FStateTreeStateHandle CurrentlyProcessedState
Current state we're processing, or invalid if not applicable.
FStateTreeFrameStateSelectionEvents * CurrentlyProcessedStateSelectionEvents = nullptr
Current frames events we're processing during the state selection, or invalid if not applicable.
const FStateTreeEvent * CurrentlyProcessedTransitionEvent = nullptr
Current event we're processing in transition, or invalid if not applicable.
const FStateTreeNodeBase * CurrentNode = nullptr
Currently processed nodes instance data.
FStateTreeDataHandle CurrentNodeDataHandle
int32 CurrentNodeIndex = FStateTreeIndex16::InvalidValue
FStateTreeDataView CurrentNodeInstanceData
const FStateSelectionResult * CurrentSelectionResult = nullptr
Current state selection result when performing recursive state selection, or nullptr if not applicable.
TSharedPtr< FStateTreeEventQueue > EventQueue
Events queue to use, cached for less indirections.
const FExternalGlobalParameters * ExternalGlobalParameters = nullptr
Memory mapping structure used for redirecting property-bag copies to external (raw) memory pointers.
PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceData & InstanceData
Instance data used during current tick.
FStateTreeReferenceOverrides LinkedAssetStateTreeOverrides
Current linked state tree overrides.
FStateTreeTransitionResult NextTransition
Next transition, used by RequestTransition().
FStateTreeTransitionSource NextTransitionSource
Structure describing the origin of the state transition that caused the state change.
TArray< FRecordedStateTreeTransitionResult > RecordedTransitions
Captured snapshots for transition results that can be used to recreate transitions.
TOptional< int32 > TriggerTransitionsFromFrameIndex
When set, start the transitions loop from TriggerTransitionsFromFrameIndex.
Protected Attributes inherited from FStateTreeMinimalExecutionContext
bool bAllowedToScheduleNextTick = true
The context is processing the tree.
Protected Attributes inherited from FStateTreeReadOnlyExecutionContext
UObject & Owner
Owner of the instance data.
const UStateTree & RootStateTree
The StateTree asset the context is initialized for.
FStateTreeInstanceStorage & Storage
Data storage of the instance data.
Private Member Functions
FStateTreeExecutionContext (const FStateTreeExecutionContext &)=delete
FStateTreeExecutionContext & operator= (const FStateTreeExecutionContext &)=delete
Detailed Description
StateTree Execution Context is a helper that is used to update StateTree instance data.
The context is meant to be temporary, you should not store a context across multiple frames.
The owner is used as the owner of the instantiated UObjects in the instance data and logging, it should have same or greater lifetime as the InstanceData.
In common case you can use the constructor to initialize the context, and us a helper struct to set up the context data and external data getter:
FStateTreeExecutionContext Context(*GetOwner(), *StateTreeRef.GetStateTree(), InstanceData);
if (SetContextRequirements(Context))
{
    Context.Tick(DeltaTime);
    }
bool UMyComponent::SetContextRequirements(FStateTreeExecutionContext& Context)
{
    if (!Context.IsValid())
    {
        return false;
    }
    // Setup context data
    Context.SetContextDataByName(...);
    ...
    Context.SetCollectExternalDataCallback(FOnCollectStateTreeExternalData::CreateUObject(this, &UMyComponent::CollectExternalData);
    return Context.AreContextDataViewsValid();
}
bool UMyComponent::CollectExternalData(const FStateTreeExecutionContext& Context, const UStateTree* StateTree, TArrayView<const FStateTreeExternalDataDesc> ExternalDataDescs, TArrayView<FStateTreeDataView> OutDataViews)
{
    ...
    for (int32 Index = 0; Index < ExternalDataDescs.Num(); Index++)
    {
        const FStateTreeExternalDataDesc& Desc = ExternalDataDescs[Index];
        if (Desc.Struct->IsChildOf(UWorldSubsystem::StaticClass()))
        {
            UWorldSubsystem* Subsystem = World->GetSubsystemBase(Cast<UClass>(const_cast<UStruct*>(Desc.Struct.Get())));
            OutDataViews[Index] = FStateTreeDataView(Subsystem);
        }
        ...
    }
    return true;
}
In this example the SetContextRequirements() method is used to set the context defined in the schema, and the delegate FOnCollectStateTreeExternalData is used to query the external data required by the tasks and conditions.
In case the State Tree links to other state tree assets, the collect external data might get called multiple times, once for each asset.
Definition at line 288 of file StateTreeExecutionContext.h.
Constructor & Destructor Documentation
FStateTreeExecutionContext() [1/5]
STATETREEMODULE_API FStateTreeExecutionContext::FStateTreeExecutionContext (UObject & InOwner, const UStateTree & InStateTree, FStateTreeInstanceData & InInstanceData, const FOnCollectStateTreeExternalData & CollectExternalDataCallback = {}, const EStateTreeRecordTransitions RecordTransitions = EStateTreeRecordTransitions::No)
References FStateTreeMinimalExecutionContext::InInstanceData, and UE_API.
Referenced by FStateTreeExecutionContext::FAllowDirectTransitionsScope::FAllowDirectTransitionsScope(), FStateTreeExecutionContext::FCurrentFrameStateSelectionEventsScope::FCurrentFrameStateSelectionEventsScope(), FStateTreeExecutionContext::FCurrentlyProcessedFrameScope::FCurrentlyProcessedFrameScope(), FStateTreeExecutionContext::FCurrentlyProcessedStateScope::FCurrentlyProcessedStateScope(), FStateTreeExecutionContext::FCurrentlyProcessedTransitionEventScope::FCurrentlyProcessedTransitionEventScope(), FStateTreeExecutionContext::FNodeInstanceDataScope::FNodeInstanceDataScope(), FStateTreeExecutionContext(), FStateTreeExecutionContext(), FStateTreeExecutionContext(), and operator=().
FStateTreeExecutionContext() [2/5]
STATETREEMODULE_API FStateTreeExecutionContext::FStateTreeExecutionContext (const FStateTreeExecutionContext & InContextToCopy, const UStateTree & InStateTree, FStateTreeInstanceData & InInstanceData)
Construct an execution context from a parent context and another tree.
Useful to run a subtree from the parent context with the same schema.
References FStateTreeExecutionContext(), FStateTreeMinimalExecutionContext::InInstanceData, and UE_API.
FStateTreeExecutionContext() [3/5]
STATETREEMODULE_API FStateTreeExecutionContext::FStateTreeExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData & InInstanceData, const FOnCollectStateTreeExternalData & CollectExternalDataCallback = {}, const EStateTreeRecordTransitions RecordTransitions = EStateTreeRecordTransitions::No)
References FStateTreeMinimalExecutionContext::InInstanceData, FStateTreeReadOnlyExecutionContext::Owner, FStateTreeMinimalExecutionContext::StateTree, and UE_API.
FStateTreeExecutionContext() [4/5]
STATETREEMODULE_API FStateTreeExecutionContext::FStateTreeExecutionContext (const FStateTreeExecutionContext & InContextToCopy, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData & InInstanceData)
Construct an execution context from a parent context and another tree.
Useful to run a subtree from the parent context with the same schema.
References FStateTreeExecutionContext(), FStateTreeMinimalExecutionContext::InInstanceData, FStateTreeMinimalExecutionContext::StateTree, and UE_API.
~FStateTreeExecutionContext()
virtual STATETREEMODULE_API FStateTreeExecutionContext::~FStateTreeExecutionContext () virtual
References UE_API.
FStateTreeExecutionContext() [5/5]
FStateTreeExecutionContext::FStateTreeExecutionContext (const FStateTreeExecutionContext &) private delete
References FStateTreeExecutionContext().
Member Function Documentation
AddTemporaryInstance()
STATETREEMODULE_API FStateTreeDataView FStateTreeExecutionContext::AddTemporaryInstance (const FStateTreeExecutionFrame & Frame, const FStateTreeIndex16 OwnerNodeIndex, const FStateTreeDataHandle DataHandle, FConstStructView NewInstanceData) protected
Adds a temporary instance that can be located using frame and data handle later.
Returns
view to the newly added instance. If NewInstanceData is Object wrapper, the new object is returned.
References UE_API.
AreContextDataViewsValid()
STATETREEMODULE_API bool FStateTreeExecutionContext::AreContextDataViewsValid () const
Returns
True if all context data pointers are set.
References UE_API.
BeginDelayedTransition()
virtual void FStateTreeExecutionContext::BeginDelayedTransition (const FStateTreeTransitionDelayedState & DelayedState) inline protected virtual
Callback when delayed transition is triggered.
Contexts that are event based can use this to trigger a future event.
Definition at line 805 of file StateTreeExecutionContext.h.
References BeginDelayedTransition().
Referenced by BeginDelayedTransition().
BindDelegate()
STATETREEMODULE_API void FStateTreeExecutionContext::BindDelegate (const FStateTreeDelegateListener & Listener, FSimpleDelegate Delegate)
Registers the delegate to the listener.
If the listener was previously registered, then unregister it first before registering it again with the new delegate callback. The listener is bound to a dispatcher in the editor.
References BindDelegate(), Delegate, and UE_API.
Referenced by BindDelegate().
BroadcastDelegate()
STATETREEMODULE_API void FStateTreeExecutionContext::BroadcastDelegate (const FStateTreeDelegateDispatcher & Dispatcher)
Broadcasts the delegate.
It executes bound delegates immediately and triggers bound transitions (when transitions are evaluated).
References UE_API.
CallStopOnEvaluatorsAndGlobalTasks()
STATETREEMODULE_API void FStateTreeExecutionContext::CallStopOnEvaluatorsAndGlobalTasks (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & Frame, const FStateTreeTransitionResult & Transition, const FStateTreeIndex16 LastInitializedTaskIndex = FStateTreeIndex16()) protected
Stops evaluators and global tasks of the given frame.
Expects nodes data to be already bound.
References ParentFrame, and UE_API.
CaptureNewStateEvents()
STATETREEMODULE_API void FStateTreeExecutionContext::CaptureNewStateEvents (TConstArrayView< FStateTreeExecutionFrame > PrevFrames, TConstArrayView< FStateTreeExecutionFrame > NewFrames, TArrayView< FStateTreeFrameStateSelectionEvents > FramesStateSelectionEvents) protected
Captures StateTree events used during the state selection.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and UE_API.
CollectActiveExternalData()
STATETREEMODULE_API bool FStateTreeExecutionContext::CollectActiveExternalData () protected
Collects external data for all StateTrees in active frames.
Returns
true if all external data are set successfully.
References UE_API.
CollectExternalData()
STATETREEMODULE_API FStateTreeIndex16 FStateTreeExecutionContext::CollectExternalData (const UStateTree * StateTree) protected
Collects external data for specific State Tree asset.
If the data is already collected, cached index is returned.
Returns
index in ContextAndExternalDataViews for the first external data.
References FStateTreeMinimalExecutionContext::StateTree, and UE_API.
ConsumeEvent()
void FStateTreeExecutionContext::ConsumeEvent (const FStateTreeSharedEvent & Event) inline
Consumes and removes the specified event from the event queue.
Definition at line 526 of file StateTreeExecutionContext.h.
References Event, and EventQueue.
CopyBatchOnActiveInstances()
STATETREEMODULE_API bool FStateTreeExecutionContext::CopyBatchOnActiveInstances (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataView TargetView, const FStateTreeIndex16 BindingsBatch) protected
Copies a batch of properties to the data in TargetView.
Should be used only on active instances, assumes valid handles and does not consider temporary instances.
References CurrentFrame, ParentFrame, and UE_API.
CopyBatchWithValidation()
STATETREEMODULE_API bool FStateTreeExecutionContext::CopyBatchWithValidation (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataView TargetView, const FStateTreeIndex16 BindingsBatch) protected
Copies a batch of properties to the data in TargetView.
This version validates the data handles and looks up temporary instances.
References CurrentFrame, ParentFrame, and UE_API.
DebugGetEventsAsString()
STATETREEMODULE_API FString FStateTreeExecutionContext::DebugGetEventsAsString () const protected
Returns
String describing all events that are currently being processed for logging and debug.
References UE_API.
DebugGetStatePath()
STATETREEMODULE_API FString FStateTreeExecutionContext::DebugGetStatePath (TConstArrayView< FStateTreeExecutionFrame > ActiveFrames, const FStateTreeExecutionFrame * CurrentFrame = nullptr, const int32 ActiveStateIndex = INDEX_NONE) const protected
Returns
String describing full path of an activate state for logging and debug.
References CurrentFrame, INDEX_NONE, and UE_API.
EnterState()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::EnterState (FStateTreeTransitionResult & Transition) protected
Handles logic for entering State.
EnterState is called on new active Evaluators and Tasks that are part of the re-planned tree. Re-planned tree is from the transition target up to the leaf state. States that are parent to the transition target state and still active after the transition will remain intact.
Returns
Run status returned by the tasks.
References UE_API.
EvaluatePropertyFunctionsOnActiveInstances()
STATETREEMODULE_API void FStateTreeExecutionContext::EvaluatePropertyFunctionsOnActiveInstances (const FStateTreeExecutionFrame * CurrentParentFrame, const FStateTreeExecutionFrame & CurrentFrame, FStateTreeIndex16 FuncsBegin, uint16 FuncsNum) protected
References CurrentFrame, and UE_API.
EvaluatePropertyFunctionsWithValidation()
STATETREEMODULE_API void FStateTreeExecutionContext::EvaluatePropertyFunctionsWithValidation (const FStateTreeExecutionFrame * CurrentParentFrame, const FStateTreeExecutionFrame & CurrentFrame, FStateTreeIndex16 FuncsBegin, uint16 FuncsNum) protected
References CurrentFrame, and UE_API.
EvaluateUtility()
STATETREEMODULE_API float FStateTreeExecutionContext::EvaluateUtility (const FStateTreeExecutionFrame * CurrentParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const int32 ConsiderationsOffset, const int32 ConsiderationsNum, const float StateWeight) protected
Calculate the final score of all considerations at given range.
Returns
the final score
References CurrentFrame, and UE_API.
ExitState()
STATETREEMODULE_API void FStateTreeExecutionContext::ExitState (const FStateTreeTransitionResult & Transition) protected
Handles logic for exiting State.
ExitState is called on current active Evaluators and Tasks that are part of the re-planned tree. Re-planned tree is from the transition target up to the leaf state. States that are parent to the transition target state and still active after the transition will remain intact.
References UE_API.
FindFrame()
STATETREEMODULE_API const FStateTreeExecutionFrame * FStateTreeExecutionContext::FindFrame (const UStateTree * StateTree, FStateTreeStateHandle RootState, TConstArrayView< FStateTreeExecutionFrame > Frames, const FStateTreeExecutionFrame *& OutParentFrame) static
Looks for a frame in provided list of frames.
References FStateTreeMinimalExecutionContext::StateTree, and UE_API.
Referenced by UE::StateTree::PropertyRefHelpers::GetMutablePtrToProperty(), and FStateTreePropertyRefExternalHandle::GetMutablePtrTuple().
FinishTask()
STATETREEMODULE_API void FStateTreeExecutionContext::FinishTask (const FStateTreeTaskBase & Task, EStateTreeFinishTaskType FinishType)
Finishes a task.
This fails if the Task is not currently the processed node. ie. Must be called from inside a FStateTreeTaskBase EnterState, ExitState, StateCompleted, Tick, TriggerTransitions. If called during tick processing, then the state completes immediately. If called outside of the tick processing, then the request is buffered and handled on the next tick.
References FinishTask(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, FStateTreeMinimalExecutionContext::StateTree, and UE_API.
Referenced by FinishTask().
ForceTransition()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::ForceTransition (const FRecordedStateTreeTransitionResult & Transition)
Forces transition to a state from a previously recorded state tree transition result.
Primarily used for replication purposes so that a client state tree stay in sync with its server counterpart.
Parameters
Recorded state transition to run on the state tree.
Returns
The new run status for the state tree.
References UE_API.
ForEachEvent() [1/2]
template<typename TFunc> TEnableIf< TIsInvocable< TFunc, FStateTreeSharedEvent >::Value, void >::Type FStateTreeExecutionContext::ForEachEvent (TFunc && Function) const inline
Iterates over all events.
Parameters
Function a lambda which takes const FStateTreeSharedEvent& Event, and returns EStateTreeLoopEvents.
Definition at line 486 of file StateTreeExecutionContext.h.
References EventQueue, ForEachEvent(), Function, and Value.
Referenced by ForEachEvent().
ForEachEvent() [2/2]
template<typename TFunc> TEnableIf< TIsInvocable< TFunc, FStateTreeEvent >::Value, void >::Type FStateTreeExecutionContext::ForEachEvent (TFunc && Function) const inline
Iterates over all events.
Parameters
Function a lambda which takes const FStateTreeEvent& Event, and returns EStateTreeLoopEvents. Less preferable than FStateTreeSharedEvent version.
Definition at line 501 of file StateTreeExecutionContext.h.
References Event, EventQueue, and Function.
GetContextDataByName()
STATETREEMODULE_API FStateTreeDataView FStateTreeExecutionContext::GetContextDataByName (const FName Name) const
Returns
the context data based on name (name is defined in the schema)
References Name, and UE_API.
GetContextDataDescs()
TConstArrayView< FStateTreeExternalDataDesc > FStateTreeExecutionContext::GetContextDataDescs () const inline
Returns
Array view to named external data descriptors associated with this context. Note: Init() must be called before calling this method.
Definition at line 573 of file StateTreeExecutionContext.h.
References FStateTreeReadOnlyExecutionContext::RootStateTree.
GetCurrentlyProcessedFrame()
const FStateTreeExecutionFrame * FStateTreeExecutionContext::GetCurrentlyProcessedFrame () const inline
Returns
the currently processed execution frame if applicable.
Definition at line 561 of file StateTreeExecutionContext.h.
References CurrentlyProcessedFrame.
GetCurrentlyProcessedNodeIndex()
FStateTreeIndex16 FStateTreeExecutionContext::GetCurrentlyProcessedNodeIndex () const inline
Definition at line 537 of file StateTreeExecutionContext.h.
References CurrentNodeIndex.
GetCurrentlyProcessedNodeInstanceData()
FStateTreeDataHandle FStateTreeExecutionContext::GetCurrentlyProcessedNodeInstanceData () const inline
Definition at line 542 of file StateTreeExecutionContext.h.
References CurrentNodeDataHandle.
GetCurrentlyProcessedParentFrame()
const FStateTreeExecutionFrame * FStateTreeExecutionContext::GetCurrentlyProcessedParentFrame () const inline
Returns
the currently processed execution parent frame if applicable.
Definition at line 567 of file StateTreeExecutionContext.h.
References CurrentlyProcessedParentFrame.
GetCurrentlyProcessedState()
FStateTreeStateHandle FStateTreeExecutionContext::GetCurrentlyProcessedState () const inline
Returns
the currently processed state if applicable.
Definition at line 555 of file StateTreeExecutionContext.h.
References CurrentlyProcessedState.
GetDataView() [1/2]
STATETREEMODULE_API FStateTreeDataView FStateTreeExecutionContext::GetDataView (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FPropertyBindingCopyInfo & CopyInfo) protected
References CurrentFrame, ParentFrame, and UE_API.
GetDataView() [2/2]
STATETREEMODULE_API FStateTreeDataView FStateTreeExecutionContext::GetDataView (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataHandle Handle) protected
Returns
data view of the specified handle relative to given frame.
References CurrentFrame, Handle, ParentFrame, and UE_API.
GetDataViewOrTemporary() [1/2]
STATETREEMODULE_API FStateTreeDataView FStateTreeExecutionContext::GetDataViewOrTemporary (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FPropertyBindingCopyInfo & CopyInfo) protected
References CurrentFrame, ParentFrame, and UE_API.
GetDataViewOrTemporary() [2/2]
STATETREEMODULE_API FStateTreeDataView FStateTreeExecutionContext::GetDataViewOrTemporary (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataHandle Handle) protected
Returns
data view of the specified handle relative to the given frame, or tries to find a matching temporary instance.
References CurrentFrame, Handle, ParentFrame, and UE_API.
GetEventQueue()
const FStateTreeEventQueue & FStateTreeExecutionContext::GetEventQueue () const inline
Returns
mutable references to the instance data in use.
Definition at line 348 of file StateTreeExecutionContext.h.
References InstanceData.
GetEventsToProcessView()
TConstArrayView< FStateTreeSharedEvent > FStateTreeExecutionContext::GetEventsToProcessView () const inline
Returns
events to process this tick.
Definition at line 520 of file StateTreeExecutionContext.h.
References EventQueue.
GetExecState() [1/2]
FStateTreeExecutionState & FStateTreeExecutionContext::GetExecState () inline protected
Returns
StateTree execution state from the instance storage.
Definition at line 1015 of file StateTreeExecutionContext.h.
References GetExecState(), and FStateTreeMinimalExecutionContext::Storage.
Referenced by GetExecState().
GetExecState() [2/2]
const FStateTreeExecutionState & FStateTreeExecutionContext::GetExecState () const inline protected
Returns
const StateTree execution state from the instance storage.
Definition at line 1021 of file StateTreeExecutionContext.h.
References FStateTreeMinimalExecutionContext::Storage.
GetExternalData()
template<typename T> T::DataType & FStateTreeExecutionContext::GetExternalData (const T Handle) const inline
Returns reference to external data based on provided handle.
The return type is deduced from the handle's template type.
Parameters
Handle Valid TStateTreeExternalDataHandle<> handle.
Returns
reference to external data based on handle or null if data is not set.
Definition at line 601 of file StateTreeExecutionContext.h.
References check, ContextAndExternalDataViews, CurrentlyProcessedFrame, and Handle.
GetExternalDataPtr()
template<typename T> T::DataType * FStateTreeExecutionContext::GetExternalDataPtr (const T Handle) const inline
Returns pointer to external data based on provided item handle.
The return type is deduced from the handle's template type.
Parameters
Handle Valid TStateTreeExternalDataHandle<> handle.
Returns
pointer to external data based on handle or null if item is not set or handle is invalid.
Definition at line 616 of file StateTreeExecutionContext.h.
References check, ContextAndExternalDataViews, CurrentlyProcessedFrame, and Handle.
GetExternalDataView()
FStateTreeDataView FStateTreeExecutionContext::GetExternalDataView (const FStateTreeExternalDataHandle Handle) inline
Definition at line 627 of file StateTreeExecutionContext.h.
References check, ContextAndExternalDataViews, CurrentlyProcessedFrame, and Handle.
GetInstanceData() [1/3]
const FStateTreeInstanceData * FStateTreeExecutionContext::GetInstanceData () const inline
Returns
const references to the instance data in use, or nullptr if the context is not valid.
Definition at line 336 of file StateTreeExecutionContext.h.
References InstanceData.
GetInstanceData() [2/3]
template<typename T> T & FStateTreeExecutionContext::GetInstanceData (const FStateTreeNodeBase & Node) const inline
Returns
reference to the instance data of specified node.
Definition at line 648 of file StateTreeExecutionContext.h.
References check, CurrentNodeDataHandle, and CurrentNodeInstanceData.
GetInstanceData() [3/3]
template<typename T> T::FInstanceDataType & FStateTreeExecutionContext::GetInstanceData (const T & Node) const inline
Returns
reference to the instance data of specified node. Infers the instance data type from the node's FInstanceDataType.
Definition at line 656 of file StateTreeExecutionContext.h.
References check, CurrentNodeDataHandle, CurrentNodeInstanceData, and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
GetInstanceDataPtr()
template<typename T> T * FStateTreeExecutionContext::GetInstanceDataPtr (const FStateTreeNodeBase & Node) const inline
Returns
pointer to the instance data of specified node.
Definition at line 640 of file StateTreeExecutionContext.h.
References check, CurrentNodeDataHandle, and CurrentNodeInstanceData.
GetInstanceDataStructRef()
template<typename T> TStateTreeInstanceDataStructRef< typename T::FInstanceDataType > FStateTreeExecutionContext::GetInstanceDataStructRef (const T & Node) const inline
Returns
reference to instance data struct that can be passed to lambdas. See TStateTreeInstanceDataStructRef for usage.
Definition at line 665 of file StateTreeExecutionContext.h.
References check, CurrentlyProcessedFrame, InstanceData, and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
GetLinkedStateTreeOverrideForTag()
STATETREEMODULE_API const FStateTreeReference * FStateTreeExecutionContext::GetLinkedStateTreeOverrideForTag (const FGameplayTag StateTag) const
Returns
the first state tree reference set by SetLinkedStateTreeOverrides that matches the StateTag. Or null if not found.
References GetLinkedStateTreeOverrideForTag(), and UE_API.
Referenced by GetLinkedStateTreeOverrideForTag().
GetMutableEventQueue()
FStateTreeEventQueue & FStateTreeExecutionContext::GetMutableEventQueue () const inline
Returns
mutable references to the instance data in use.
Definition at line 354 of file StateTreeExecutionContext.h.
References InstanceData.
GetMutableEventsToProcessView()
TArrayView< FStateTreeSharedEvent > FStateTreeExecutionContext::GetMutableEventsToProcessView () inline
Returns
events to process this tick.
Definition at line 514 of file StateTreeExecutionContext.h.
References EventQueue.
GetMutableInstanceData()
FStateTreeInstanceData * FStateTreeExecutionContext::GetMutableInstanceData () const inline
Returns
mutable references to the instance data in use, or nullptr if the context is not valid.
Definition at line 342 of file StateTreeExecutionContext.h.
References InstanceData.
GetRecordedTransitions()
TConstArrayView< FRecordedStateTreeTransitionResult > FStateTreeExecutionContext::GetRecordedTransitions () const inline
Returns the recorded transitions for this context.
Definition at line 735 of file StateTreeExecutionContext.h.
References RecordedTransitions.
GetSafeStateName()
STATETREEMODULE_API FString FStateTreeExecutionContext::GetSafeStateName (const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeStateHandle State) const protected
Returns
String describing state name for logging and debug.
References CurrentFrame, State, and UE_API.
GetStateStatusString()
STATETREEMODULE_API FString FStateTreeExecutionContext::GetStateStatusString (const FStateTreeExecutionState & ExecState) const protected
Returns
String describing state status for logging and debug.
References UE_API.
GetTemporaryDataView()
STATETREEMODULE_API FStateTreeDataView FStateTreeExecutionContext::GetTemporaryDataView (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataHandle Handle) protected
Returns
data view of the specified handle from temporary instance.
References CurrentFrame, Handle, ParentFrame, and UE_API.
IsHandleSourceValid() [1/2]
STATETREEMODULE_API bool FStateTreeExecutionContext::IsHandleSourceValid (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FPropertyBindingCopyInfo & CopyInfo) const protected
References CurrentFrame, ParentFrame, and UE_API.
IsHandleSourceValid() [2/2]
STATETREEMODULE_API bool FStateTreeExecutionContext::IsHandleSourceValid (const FStateTreeExecutionFrame * ParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataHandle Handle) const protected
Returns
true if handle source is valid cified handle relative to given frame.
References CurrentFrame, Handle, ParentFrame, and UE_API.
MakeRecordedTransitionResult()
STATETREEMODULE_API FRecordedStateTreeTransitionResult FStateTreeExecutionContext::MakeRecordedTransitionResult (const FStateTreeTransitionResult & Transition) const protected
Create a new recorded transition from a transition result.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, FStateTreeMinimalExecutionContext::StateTree, and UE_API.
MakeTransitionResult()
STATETREEMODULE_API TOptional< FStateTreeTransitionResult > FStateTreeExecutionContext::MakeTransitionResult (const FRecordedStateTreeTransitionResult & Transition) const protected
Create a new transition result from a recorded transition result.
It will fail if the recorded transition is malformed.
References UE_API.
MakeWeakExecutionContext()
STATETREEMODULE_API FStateTreeWeakExecutionContext FStateTreeExecutionContext::MakeWeakExecutionContext () const
Returns
a weak context to interact with the state tree instance data that can be stored for later uses.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and UE_API.
operator=()
FStateTreeExecutionContext & FStateTreeExecutionContext::operator= (const FStateTreeExecutionContext &) private delete
References FStateTreeExecutionContext().
RemoveAllDelegateListeners()
STATETREEMODULE_API void FStateTreeExecutionContext::RemoveAllDelegateListeners () protected
Removes all delegate listeners.
References UE_API.
RequestTransition() [1/3]
STATETREEMODULE_API bool FStateTreeExecutionContext::RequestTransition (const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeStateHandle NextState, const EStateTreeTransitionPriority Priority, const FStateTreeSharedEvent * TransitionEvent = nullptr, const EStateTreeSelectionFallback Fallback = EStateTreeSelectionFallback::None) protected
Requests transition to a specified state with specified priority.
References CurrentFrame, and UE_API.
RequestTransition() [2/3]
STATETREEMODULE_API void FStateTreeExecutionContext::RequestTransition (const FStateTreeTransitionRequest & Request)
Requests transition to a state.
If called during during transition processing (e.g. from FStateTreeTaskBase::TriggerTransitions()) the transition is attempted to be activate immediately (it can fail e.g. because of preconditions on a target state). If called outside the transition handling, the request is buffered and handled at the beginning of next transition processing.
Parameters
Request The state to transition to.
References UE_API.
RequestTransition() [3/3]
STATETREEMODULE_API void FStateTreeExecutionContext::RequestTransition (FStateTreeStateHandle TargetState, EStateTreeTransitionPriority Priority = EStateTreeTransitionPriority::Normal, EStateTreeSelectionFallback Fallback = EStateTreeSelectionFallback::None)
Requests transition to a state.
If called during during transition processing (e.g. from FStateTreeTaskBase::TriggerTransitions()) the transition is attempted to be activate immediately (it can fail e.g. because of preconditions on a target state). If called outside the transition handling, the request is buffered and handled at the beginning of next transition processing.
Parameters
TargetState The state to transition to.
Priority The priority of the transition.
Fallback of the transition if it fails to select the target state.
References UE_API.
SelectState()
STATETREEMODULE_API bool FStateTreeExecutionContext::SelectState (const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeStateHandle NextState, FStateSelectionResult & OutSelectionResult, const FStateTreeSharedEvent * TransitionEvent = nullptr, const EStateTreeSelectionFallback Fallback = EStateTreeSelectionFallback::None) protected
Runs state selection logic starting at the specified state, walking towards the leaf states.
If a state cannot be selected, false is returned. If NextState is a selector state, SelectStateInternal is called recursively (depth-first) to all child states (where NextState will be one of child states). If NextState is a leaf state, the active states leading from root to the leaf are returned.
Parameters
CurrentFrame The frame where the NextState is valid.
NextState The state which we try to select next.
OutSelectionResult The result of selection.
TransitionEvent Event used by transition to trigger the state selection.
Fallback selection behavior to execute if it fails to select the desired state
Returns
True if succeeded to select new active states.
References CurrentFrame, None, SelectState(), and UE_API.
Referenced by SelectState().
SelectStateInternal()
STATETREEMODULE_API bool FStateTreeExecutionContext::SelectStateInternal (const FStateTreeExecutionFrame * CurrentParentFrame, FStateTreeExecutionFrame & CurrentFrame, const FStateTreeExecutionFrame * CurrentFrameInActiveFrames, TConstArrayView< FStateTreeStateHandle > PathToNextState, FStateSelectionResult & OutSelectionResult, const FStateTreeSharedEvent * TransitionEvent = nullptr) protected
Used internally to do the recursive part of the SelectState().
References CurrentFrame, SelectStateInternal(), and UE_API.
Referenced by SelectStateInternal().
SetCollectExternalDataCallback()
STATETREEMODULE_API void FStateTreeExecutionContext::SetCollectExternalDataCallback (const FOnCollectStateTreeExternalData & Callback)
Sets callback used to collect external data views during State Tree execution.
References UE_API.
SetContextData()
void FStateTreeExecutionContext::SetContextData (const FStateTreeExternalDataHandle Handle, FStateTreeDataView DataView) inline
Sets context data view value for specific item.
Definition at line 579 of file StateTreeExecutionContext.h.
References check, ContextAndExternalDataViews, and Handle.
SetContextDataByName()
STATETREEMODULE_API bool FStateTreeExecutionContext::SetContextDataByName (const FName Name, FStateTreeDataView DataView)
Sets the context data based on name (name is defined in the schema), returns true if data was found.
References Name, and UE_API.
SetExternalGlobalParameters()
STATETREEMODULE_API void FStateTreeExecutionContext::SetExternalGlobalParameters (const FExternalGlobalParameters * Parameters)
References UE_API.
SetGlobalParameters()
STATETREEMODULE_API bool FStateTreeExecutionContext::SetGlobalParameters (const FInstancedPropertyBag & Parameters) protected
Stores copy of provided parameters as State Tree global parameters.
Parameters
Parameters parameters to copy
Returns
true if successfully set the parameters
References UE_API.
SetLinkedStateTreeOverrides()
STATETREEMODULE_API void FStateTreeExecutionContext::SetLinkedStateTreeOverrides (FStateTreeReferenceOverrides InLinkedStateTreeOverrides)
Overrides for linked State Trees.
This table is used to override State Tree references on linked states. If a linked state's tag is exact match of the tag specified on the table, the reference from the table is used instead.
References SetLinkedStateTreeOverrides(), and UE_API.
Referenced by SetLinkedStateTreeOverrides(), and UE_DEPRECATED().
SetUpdatePhaseInExecutionState()
STATETREEMODULE_API void FStateTreeExecutionContext::SetUpdatePhaseInExecutionState (FStateTreeExecutionState & ExecutionState, EStateTreeUpdatePhase UpdatePhase) const protected
Updates the update phase of the statetree execution state.
References UE_API.
SetupNextTransition()
STATETREEMODULE_API void FStateTreeExecutionContext::SetupNextTransition (const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeStateHandle NextState, const EStateTreeTransitionPriority Priority) protected
Sets up NextTransition based on the provided parameters and the current execution status.
References CurrentFrame, and UE_API.
Start() [1/2]
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::Start (const FInstancedPropertyBag * InitialParameters = nullptr, int32 RandomSeed = -1)
Start executing.
Parameters
InitialParameters Optional override of parameters initial values
RandomSeed Optional override of initial seed for RandomStream. By default FPlatformTime::Cycles() will be used.
Returns
Tree execution status after the start.
References UE_API.
Start() [2/2]
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::Start (FStartParameters Parameter)
Start executing.
Returns
Tree execution status after the start.
References UE_API.
StartEvaluatorsAndGlobalTasks()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::StartEvaluatorsAndGlobalTasks (FStateTreeIndex16 & OutLastInitializedTaskIndex) protected
Starts evaluators and global tasks.
Returns
run status returned by the global tasks.
References UE_API.
StartTemporaryEvaluatorsAndGlobalTasks()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::StartTemporaryEvaluatorsAndGlobalTasks (const FStateTreeExecutionFrame * CurrentParentFrame, FStateTreeExecutionFrame & CurrentFrame) protected
Starts temporary instances of global evaluators and tasks for a given frame.
References CurrentFrame, and UE_API.
StateCompleted()
STATETREEMODULE_API void FStateTreeExecutionContext::StateCompleted () protected
Handles logic for signaling State completed.
StateCompleted is called on current active Evaluators and Tasks in reverse order (from leaf to root).
References UE_API.
Stop()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::Stop (const EStateTreeRunStatus CompletionStatus = EStateTreeRunStatus::Stopped)
Stop executing if the tree is running.
Parameters
CompletionStatus Status (and terminal state) reported in the transition when the tree is stopped.
Returns
Tree execution status at stop, can be CompletionStatus, or earlier status if the tree is not running.
References UE_API.
StopEvaluatorsAndGlobalTasks()
STATETREEMODULE_API void FStateTreeExecutionContext::StopEvaluatorsAndGlobalTasks (const EStateTreeRunStatus CompletionStatus, const FStateTreeIndex16 LastInitializedTaskIndex = FStateTreeIndex16()) protected
Stops evaluators and global tasks.
References UE_API.
StopTemporaryEvaluatorsAndGlobalTasks()
STATETREEMODULE_API void FStateTreeExecutionContext::StopTemporaryEvaluatorsAndGlobalTasks (const FStateTreeExecutionFrame * CurrentParentFrame, const FStateTreeExecutionFrame & CurrentFrame) protected
Stops temporary global evaluators and tasks for the provided frame.
References CurrentFrame, and UE_API.
TestAllConditions()
STATETREEMODULE_API bool FStateTreeExecutionContext::TestAllConditions (const FStateTreeExecutionFrame * CurrentParentFrame, const FStateTreeExecutionFrame & CurrentFrame, const int32 ConditionsOffset, const int32 ConditionsNum) protected
Checks all conditions at given range.
Returns
True if all conditions pass.
References CurrentFrame, and UE_API.
Tick()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::Tick (const float DeltaTime)
Tick the state tree logic, updates the tasks and triggers transitions.
Parameters
DeltaTime time to advance the logic.
Returns
tree run status after the tick.
References DeltaTime, and UE_API.
TickEvaluatorsAndGlobalTasks()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::TickEvaluatorsAndGlobalTasks (const float DeltaTime, bool bTickGlobalTasks = true) protected
Tick evaluators and global tasks by delta time.
References DeltaTime, and UE_API.
TickEvaluatorsAndGlobalTasksForFrame()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::TickEvaluatorsAndGlobalTasksForFrame (const float DeltaTime, const bool bTickGlobalTasks, const int32 FrameIndex, const FStateTreeExecutionFrame * CurrentParentFrame, const TNotNull< FStateTreeExecutionFrame * > CurrentFrame) protected
Tick evaluators and global tasks of a specific frame.
References CurrentFrame, DeltaTime, and UE_API.
TickPostlude()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::TickPostlude () protected
References UE_API.
TickPrelude()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::TickPrelude () protected
Common functionality shared by the tick methods.
References UE_API.
TickTasks() [1/2]
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::TickTasks (const float DeltaTime) protected
Ticks tasks of all active states starting from current state by delta time.
Returns
Run status returned by the tasks.
References DeltaTime, and UE_API.
TickTasks() [2/2]
STATETREEMODULE_API FTickTaskResult FStateTreeExecutionContext::TickTasks (const FTickTaskArguments & Args) protected
Ticks tasks and updates the bindings for a specific state or frame.
References UE_API.
TickTriggerTransitions()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::TickTriggerTransitions ()
Tick the state tree logic partially, triggers the transitions.
For full update TickUpdateTasks() should be called before.
Returns
tree run status after the partial tick.
References UE_API.
TickTriggerTransitionsInternal()
STATETREEMODULE_API void FStateTreeExecutionContext::TickTriggerTransitionsInternal () protected
Handles transition triggering part of the tick.
References UE_API.
TickUpdateTasks()
STATETREEMODULE_API EStateTreeRunStatus FStateTreeExecutionContext::TickUpdateTasks (const float DeltaTime)
Tick the state tree logic partially, updates the tasks.
For full update TickTriggerTransitions() should be called after.
Parameters
DeltaTime time to advance the logic.
Returns
tree run status after the partial tick.
References DeltaTime, and UE_API.
TickUpdateTasksInternal()
STATETREEMODULE_API void FStateTreeExecutionContext::TickUpdateTasksInternal (float DeltaTime) protected
Handles task ticking part of the tick.
References DeltaTime, and UE_API.
TriggerTransitions()
STATETREEMODULE_API bool FStateTreeExecutionContext::TriggerTransitions () protected
Triggers transitions based on current run status.
CurrentStatus is used to select which transitions events are triggered. If CurrentStatus is "Running", "Conditional" transitions pass, "Completed/Failed" will trigger "OnCompleted/OnSucceeded/OnFailed" transitions. Transition target state can point to a selector state. For that reason the result contains both the target state, as well ass the actual next state returned by the selector.
Returns
Transition result describing the source state, state transitioned to, and next selected state.
References UE_API.
UE_DEPRECATED() [1/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 5, "Use GetEventsToProcessView() instead.") const inline
Definition at line 534 of file StateTreeExecutionContext.h.
UE_DEPRECATED() [2/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 5, "Use UE::StateTree::InstanceData::GetDataView instead.") &
UE_DEPRECATED() [3/17]
template<typename T> PRAGMA_ENABLE_DEPRECATION_WARNINGS PRAGMA_DISABLE_DEPRECATION_WARNINGS FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "FStateTreeWeakTaskRef is no longer used.") const & inline
Returns
a weak reference for a task that can be stored for later uses.
Note
similar to GetInstanceData, the instance data needs to be the current processing node.
Definition at line 377 of file StateTreeExecutionContext.h.
References check, CurrentNodeInstanceData, FStateTreeMinimalExecutionContext::InInstanceData, and UE_DEPRECATED().
UE_DEPRECATED() [4/17]
template<typename T> PRAGMA_ENABLE_DEPRECATION_WARNINGS PRAGMA_DISABLE_DEPRECATION_WARNINGS FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "FStateTreeWeakTaskRef is no longer used.") const inline
Returns
a weak reference for a task that can be stored for later uses.
Note
similar to GetInstanceData, the instance data needs to be the current processing node.
Definition at line 391 of file StateTreeExecutionContext.h.
References check, CurrentNodeInstanceData, and FStateTreeMinimalExecutionContext::InInstanceData.
UE_DEPRECATED() [5/17]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "FStateTreeWeakTaskRef is no longer used.") const &
Returns
a weak reference for a task that can be stored for later uses.
Note
similar to GetInstanceData, the node needs to be the current processing node.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_API.
UE_DEPRECATED() [6/17]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "FStateTreeWeakTaskRef is no longer used.") const protected
Returns
a weak reference for a task that can be stored for later uses.
References PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_API.
UE_DEPRECATED() [7/17]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Replaced with FStateTreeTasksCompletionStatus") STATETREEMODULE_API void MarkStateCompleted(UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Replaced with FStateTreeTasksCompletionStatus") const protected
Adds the state to the completed list from a finished task.
In the list of completed states, returns the run status when it's completed by a global task.
References UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [8/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Replaced with FStateTreeTasksCompletionStatus") protected
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, FStateTreeMinimalExecutionContext::StateTree, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [9/17]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Replaced with FStateTreeTasksCompletionStatus") STATETREEMODULE_API bool IsFinishedTaskValid(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Replaced with FStateTreeTasksCompletionStatus") protected
Confirms that the frame and state ID are valid and the task index is correct.
Removes stale entries and fills the completed states list. The tree can be in a different state from when a finished task was added to the pending list and the finished task may not be valid.
Parameters
bMarkTaskProcessed when true, marks the tasks as processed. When false, only used the already marked tasks.
References UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [10/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use BindDelegate") const &
Adds delegate listener.
UE_DEPRECATED() [11/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use FStateTreeExecutionExtension::GetInstanceDescription instead") const final protected
Returns
Prefix that will be used by STATETREE_LOG and STATETREE_CLOG, Owner name by default.
References UE_API.
UE_DEPRECATED() [12/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use GetCurrentlyProcessedNodeInstanceData() instead.") const inline
Returns
the currently processed node if applicable.
Definition at line 547 of file StateTreeExecutionContext.h.
References CurrentNodeDataHandle.
UE_DEPRECATED() [13/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use SetLinkedStateTreeOverrides that creates a copy.") const
Overrides for linked State Trees.
This table is used to override State Tree references on linked states. If a linked state's tag is exact match of the tag specified on the table, the reference from the table is used instead.
References SetLinkedStateTreeOverrides(), and UE_API.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [14/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use Storage instead.") protected
Data storage of the instance data, cached for less indirections.
References UE_DEPRECATED().
UE_DEPRECATED() [15/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use the non const version of StartTemporaryEvaluatorsAndGlobalTasks") const protected
UE_DEPRECATED() [16/17]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use UE::StateTree::InstanceData::GetDataView instead.") &
Finishes a task.
If called during tick processing, then the state completes immediately. If called outside of the tick processing, then the request is buffered and handled on the next tick.
Returns
data view of the specified handle relative to given frame.
References UE_DEPRECATED().
UE_DEPRECATED() [17/17]
FStateTreeExecutionContext::UE_DEPRECATED (5. 6, "Use UnbindDelegate") const &
Removes delegate listener.
References UE_API, and UE_DEPRECATED().
UnbindDelegate()
STATETREEMODULE_API void FStateTreeExecutionContext::UnbindDelegate (const FStateTreeDelegateListener & Listener)
Unregisters the callback bound to the listener.
References UE_API, and UnbindDelegate().
Referenced by UnbindDelegate().
UpdateInstanceData()
STATETREEMODULE_API void FStateTreeExecutionContext::UpdateInstanceData (TConstArrayView< FStateTreeExecutionFrame > CurrentActiveFrames, TArrayView< FStateTreeExecutionFrame > NextActiveFrames) protected
References UE_API.
Field Documentation
bActiveExternalDataCollected
bool FStateTreeExecutionContext::bActiveExternalDataCollected = false protected
Definition at line 1127 of file StateTreeExecutionContext.h.
bAllowDirectTransitions
bool FStateTreeExecutionContext::bAllowDirectTransitions = false protected
True if transitions are allowed to be requested directly instead of buffering.
Definition at line 1237 of file StateTreeExecutionContext.h.
bRecordTransitions
bool FStateTreeExecutionContext::bRecordTransitions = false protected
If true, the state tree context will create snapshots of transition events and capture them within RecordedTransitions for later use.
Definition at line 1280 of file StateTreeExecutionContext.h.
CollectedExternalCache
TArray<FCollectedExternalDataCache, FNonconcurrentLinearArrayAllocator> FStateTreeExecutionContext::CollectedExternalCache protected
Definition at line 1125 of file StateTreeExecutionContext.h.
CollectExternalDataDelegate
FOnCollectStateTreeExternalData FStateTreeExecutionContext::CollectExternalDataDelegate protected
Definition at line 1118 of file StateTreeExecutionContext.h.
ContextAndExternalDataViews [1/2]
FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame TConstArrayView<FStateTreeDataView> FStateTreeExecutionContext::ContextAndExternalDataViews
Definition at line 721 of file StateTreeExecutionContext.h.
Referenced by GetExternalData(), GetExternalDataPtr(), GetExternalDataView(), and SetContextData().
ContextAndExternalDataViews [2/2]
TArray<FStateTreeDataView, FNonconcurrentLinearArrayAllocator> FStateTreeExecutionContext::ContextAndExternalDataViews protected
Data view of the context data.
Definition at line 1116 of file StateTreeExecutionContext.h.
CurrentFrame [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame& FStateTreeExecutionContext::CurrentFrame
Definition at line 712 of file StateTreeExecutionContext.h.
Referenced by FStateTreeExecutionContext::FCurrentlyProcessedFrameScope::FCurrentlyProcessedFrameScope(), CopyBatchOnActiveInstances(), CopyBatchWithValidation(), DebugGetStatePath(), EvaluatePropertyFunctionsOnActiveInstances(), EvaluatePropertyFunctionsWithValidation(), EvaluateUtility(), GetDataView(), GetDataView(), GetDataViewOrTemporary(), GetDataViewOrTemporary(), GetSafeStateName(), GetTemporaryDataView(), IsHandleSourceValid(), IsHandleSourceValid(), RequestTransition(), SelectState(), SelectStateInternal(), SetupNextTransition(), StartTemporaryEvaluatorsAndGlobalTasks(), StopTemporaryEvaluatorsAndGlobalTasks(), TestAllConditions(), and TickEvaluatorsAndGlobalTasksForFrame().
CurrentFrame [2/3]
FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame& FStateTreeExecutionContext::CurrentFrame
Definition at line 721 of file StateTreeExecutionContext.h.
CurrentFrame [3/3]
const FStateTreeExecutionFrame& FStateTreeExecutionContext::CurrentFrame protected
Initial value:
{
        return StartTemporaryEvaluatorsAndGlobalTasks(CurrentParentFrame, const_cast<FStateTreeExecutionFrame&>(CurrentFrame))
Definition at line 864 of file StateTreeExecutionContext.h.
CurrentlyProcessedFrame
const FStateTreeExecutionFrame* FStateTreeExecutionContext::CurrentlyProcessedFrame = nullptr protected
Definition at line 1146 of file StateTreeExecutionContext.h.
Referenced by GetCurrentlyProcessedFrame(), GetExternalData(), GetExternalDataPtr(), GetExternalDataView(), and GetInstanceDataStructRef().
CurrentlyProcessedParentFrame
const FStateTreeExecutionFrame* FStateTreeExecutionContext::CurrentlyProcessedParentFrame = nullptr protected
Current frame we're processing.
Definition at line 1145 of file StateTreeExecutionContext.h.
Referenced by GetCurrentlyProcessedParentFrame().
CurrentlyProcessedSharedInstanceStorage [1/2]
FStateTreeInstanceStorage * FStateTreeExecutionContext::CurrentlyProcessedSharedInstanceStorage = nullptr
Pointer to the shared instance data of the current frame we're processing.
Definition at line 712 of file StateTreeExecutionContext.h.
CurrentlyProcessedSharedInstanceStorage [2/2]
FStateTreeInstanceStorage* FStateTreeExecutionContext::CurrentlyProcessedSharedInstanceStorage = nullptr
Pointer to the shared instance data of the current frame we're processing.
Definition at line 721 of file StateTreeExecutionContext.h.
CurrentlyProcessedState
FStateTreeStateHandle FStateTreeExecutionContext::CurrentlyProcessedState protected
Current state we're processing, or invalid if not applicable.
Definition at line 1169 of file StateTreeExecutionContext.h.
Referenced by GetCurrentlyProcessedState().
CurrentlyProcessedStateSelectionEvents
FStateTreeFrameStateSelectionEvents* FStateTreeExecutionContext::CurrentlyProcessedStateSelectionEvents = nullptr protected
Current frames events we're processing during the state selection, or invalid if not applicable.
Definition at line 1214 of file StateTreeExecutionContext.h.
CurrentlyProcessedTransitionEvent
const FStateTreeEvent* FStateTreeExecutionContext::CurrentlyProcessedTransitionEvent = nullptr protected
Current event we're processing in transition, or invalid if not applicable.
Definition at line 1192 of file StateTreeExecutionContext.h.
CurrentNode
const FStateTreeNodeBase* FStateTreeExecutionContext::CurrentNode = nullptr protected
Currently processed nodes instance data.
Ideally we would pass these to the nodes directly, but do not want to change the API currently.
Definition at line 1260 of file StateTreeExecutionContext.h.
CurrentNodeDataHandle
FStateTreeDataHandle FStateTreeExecutionContext::CurrentNodeDataHandle protected
Definition at line 1262 of file StateTreeExecutionContext.h.
Referenced by GetCurrentlyProcessedNodeInstanceData(), GetInstanceData(), GetInstanceData(), GetInstanceDataPtr(), and UE_DEPRECATED().
CurrentNodeIndex
int32 FStateTreeExecutionContext::CurrentNodeIndex = FStateTreeIndex16::InvalidValue protected
Definition at line 1261 of file StateTreeExecutionContext.h.
Referenced by GetCurrentlyProcessedNodeIndex().
CurrentNodeInstanceData
FStateTreeDataView FStateTreeExecutionContext::CurrentNodeInstanceData protected
Definition at line 1263 of file StateTreeExecutionContext.h.
Referenced by GetInstanceData(), GetInstanceData(), GetInstanceDataPtr(), UE_DEPRECATED(), and UE_DEPRECATED().
CurrentSelectionResult
const FStateSelectionResult* FStateTreeExecutionContext::CurrentSelectionResult = nullptr protected
Current state selection result when performing recursive state selection, or nullptr if not applicable.
Definition at line 1166 of file StateTreeExecutionContext.h.
Delegate
FSimpleDelegate FStateTreeExecutionContext::Delegate
Definition at line 465 of file StateTreeExecutionContext.h.
Referenced by BindDelegate().
EventQueue
TSharedPtr<FStateTreeEventQueue> FStateTreeExecutionContext::EventQueue protected
Events queue to use, cached for less indirections.
Definition at line 1105 of file StateTreeExecutionContext.h.
Referenced by ConsumeEvent(), ForEachEvent(), GetEventsToProcessView(), and GetMutableEventsToProcessView().
ExternalGlobalParameters
const FExternalGlobalParameters* FStateTreeExecutionContext::ExternalGlobalParameters = nullptr protected
Memory mapping structure used for redirecting property-bag copies to external (raw) memory pointers.
Definition at line 1286 of file StateTreeExecutionContext.h.
Handle [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame const FStateTreeDataHandle FStateTreeExecutionContext::Handle
Initial value:
{
        return UE::StateTree::InstanceData::GetDataView(InstanceDataStorage, CurrentlyProcessedSharedInstanceStorage, ParentFrame, CurrentFrame, Handle)
Definition at line 712 of file StateTreeExecutionContext.h.
Referenced by GetDataView(), GetDataViewOrTemporary(), GetExternalData(), GetExternalDataPtr(), GetExternalDataView(), GetTemporaryDataView(), IsHandleSourceValid(), and SetContextData().
Handle [2/2]
FStateTreeInstanceStorage const FStateTreeExecutionFrame const FStateTreeExecutionFrame TConstArrayView<FStateTreeDataView> const FStateTreeDataHandle FStateTreeExecutionContext::Handle
Initial value:
{
        return UE::StateTree::InstanceData::GetDataView(InstanceDataStorage, CurrentlyProcessedSharedInstanceStorage, ParentFrame, CurrentFrame, Handle)
Definition at line 721 of file StateTreeExecutionContext.h.
InstanceData
PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceData& FStateTreeExecutionContext::InstanceData protected
Instance data used during current tick.
Definition at line 1098 of file StateTreeExecutionContext.h.
Referenced by GetEventQueue(), GetInstanceData(), GetInstanceDataStructRef(), GetMutableEventQueue(), and GetMutableInstanceData().
LinkedAssetStateTreeOverrides
FStateTreeReferenceOverrides FStateTreeExecutionContext::LinkedAssetStateTreeOverrides protected
Current linked state tree overrides.
Definition at line 1113 of file StateTreeExecutionContext.h.
NextTransition
FStateTreeTransitionResult FStateTreeExecutionContext::NextTransition protected
Next transition, used by RequestTransition().
Definition at line 1136 of file StateTreeExecutionContext.h.
NextTransitionSource
FStateTreeTransitionSource FStateTreeExecutionContext::NextTransitionSource protected
Structure describing the origin of the state transition that caused the state change.
Definition at line 1139 of file StateTreeExecutionContext.h.
ParentFrame [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.6, "Use the weak context to finish a task async or FinishTask(FStateTreeTaskBase, EStateTreeFinishTaskType) to finish the current task.") STATETREEMODULE_API void FinishTask(const UE PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeInstanceStorage const FStateTreeExecutionFrame* FStateTreeExecutionContext::ParentFrame
Definition at line 712 of file StateTreeExecutionContext.h.
Referenced by CallStopOnEvaluatorsAndGlobalTasks(), CopyBatchOnActiveInstances(), CopyBatchWithValidation(), GetDataView(), GetDataView(), GetDataViewOrTemporary(), GetDataViewOrTemporary(), GetTemporaryDataView(), IsHandleSourceValid(), and IsHandleSourceValid().
ParentFrame [2/2]
FStateTreeInstanceStorage const FStateTreeExecutionFrame* FStateTreeExecutionContext::ParentFrame
Definition at line 721 of file StateTreeExecutionContext.h.
RecordedTransitions
TArray<FRecordedStateTreeTransitionResult> FStateTreeExecutionContext::RecordedTransitions protected
Captured snapshots for transition results that can be used to recreate transitions.
This array is only populated if bRecordTransitions is true.
Definition at line 1283 of file StateTreeExecutionContext.h.
Referenced by GetRecordedTransitions().
TriggerTransitionsFromFrameIndex
TOptional<int32> FStateTreeExecutionContext::TriggerTransitionsFromFrameIndex protected
When set, start the transitions loop from TriggerTransitionsFromFrameIndex.
Definition at line 1142 of file StateTreeExecutionContext.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreeExecutionContext.h