Unreal Engine 5.6 C++ API: FRigVMCodeGenerator Struct Reference
FRigVMCodeGenerator Struct Reference
#include "RigVMCodeGenerator.h"
Data Structures
struct FInstructionGroup
struct FPropertyInfo
struct FRigVMDispatchInfo
Public Member Functions
FRigVMCodeGenerator (const FString &InClassName, const FString &InModuleName, URigVMGraph *InModelToNativize, URigVM *InVMToNativize, FRigVMExtendedExecuteContext &InVMContext, const UScriptStruct *PublicContextStruct, TMap< FString, FRigVMOperand > InPinToOperandMap, int32 InMaxInstructionsPerFunction=100)
FString DumpBlockNames (bool bForHeader, bool bLog=false)
FString DumpDispatches (bool bLog=false)
FString DumpEntries (bool bForHeader, bool bLog=false)
FString DumpIncludes (bool bLog=false)
FString DumpInitialize (bool bLog=false)
FString DumpLines (const TArray< FString > &InLines, bool bLog=false)
FString DumpRequiredUProperties (bool bLog=false)
UE_DEPRECATED (5.4, "Please, use DumpExternalVariables with ExtendedExecuteContext parameter") FString DumpExternalVariables(bool bForHeader
UE_DEPRECATED (5.4, "Please, use DumpHeader with ExtendedExecuteContext parameter") FString DumpHeader(bool bLog
UE_DEPRECATED (5.4, "Please, use DumpInstructions with ExtendedExecuteContext parameter") FString DumpInstructions(int32 InInstructionGroup
UE_DEPRECATED (5.4, "Please, use DumpProperties with ExtendedExecuteContext parameter") FString DumpProperties(bool bForHeader
UE_DEPRECATED (5.4, "Please, use DumpSource with ExtendedExecuteContext parameter") FString DumpSource(bool bLog
Data Fields
bool bLog
int32 bool bLog
int32 InInstructionGroup
Private Types
enum ERigVMNativizedPropertyType { Literal , Work , Sliced , Invalid }
typedef TTuple< FString, FString > FMappedType
typedef TArray< FRigVMPropertyDescription > FRigVMPropertyDescriptionArray
typedef TArray< FString > FStringArray
typedef TMap< FString, FString > FStringMap
typedef TFunction< FString(const FString &)> TStructConstGenerator
Private Member Functions
void CheckOperand (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
FString DumpInstructions (const FRigVMExtendedExecuteContext &Context, const FString &InPrefix, const TArray< int32 > InInstructionIndices, const FInstructionGroup &InGroup, bool bLog=false)
FString DumpInstructions (const FRigVMExtendedExecuteContext &Context, const FString &InPrefix, int32 InFirstInstruction, int32 InLastInstruction, const FInstructionGroup &InGroup, bool bLog=false)
FString GetEntryParameters () const
const FInstructionGroup & GetGroup (int32 InGroupIndex) const
FString GetMappedArrayTypeName (const FString InBaseElementType) const
FString GetMappedType (const FString &InCPPType) const
const FString & GetMappedTypeSuffix (const FString &InCPPType) const
FString GetOperandCPPBaseType (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
FString GetOperandCPPType (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
FString GetOperandName (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand, bool bPerSlice=true, bool bAsInput=true) const
FRigVMPropertyDescription GetPropertyDescForOperand (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
FRigVMPropertyDescription GetPropertyForOperand (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
int32 GetPropertyIndex (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
int32 GetPropertyIndex (const FRigVMPropertyDescription &InProperty) const
const FRigVMPropertyPathDescription & GetPropertyPathForOperand (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
ERigVMNativizedPropertyType GetPropertyType (const FRigVMExtendedExecuteContext &Context, const FRigVMOperand &InOperand) const
ERigVMNativizedPropertyType GetPropertyType (const FRigVMPropertyDescription &InProperty) const
bool IsInstructionPartOfGroup (int32 InInstructionIndex, int32 InGroupIndex, bool bIncludeChildGroups) const
bool IsPropertyPartOfGroup (int32 InPropertyIndex, int32 InGroupIndex) const
void ParseInclude (UStruct *InDependency, const FName &InMethodName=NAME_None)
void ParseInstructionGroups (const FRigVMExtendedExecuteContext &Context)
void ParseMemory (const FRigVMExtendedExecuteContext &Context, FRigVMMemoryStorageStruct *InMemory)
void ParseProperty (const FRigVMExtendedExecuteContext &Context, ERigVMMemoryType InMemoryType, const FProperty *InProperty, FRigVMMemoryStorageStruct *InMemory)
void ParseRequiredUProperties (const FRigVMExtendedExecuteContext &Context)
void ParseVM (const FString &InClassName, const FString &InModuleName, URigVMGraph *InModelToNativize, URigVM *InVMToNativize, FRigVMExtendedExecuteContext &InVMContext, const UScriptStruct *PublicContextStruct, TMap< FString, FRigVMOperand > InPinToOperandMap, int32 InMaxInstructionsPerFunction)
void Reset ()
Static Private Member Functions
template<typename TypeA>
static FString Format (const TCHAR *InFormatString, const TypeA &InArgA)
template<typename TypeA, typename TypeB>
static FString Format (const TCHAR *InFormatString, const TypeA &InArgA, const TypeB &InArgB)
template<typename TypeA, typename TypeB, typename TypeC>
static FString Format (const TCHAR *InFormatString, const TypeA &InArgA, const TypeB &InArgB, const TypeC &InArgC)
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD>
static FString Format (const TCHAR *InFormatString, const TypeA &InArgA, const TypeB &InArgB, const TypeC &InArgC, const TypeD &InArgD)
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD, typename TypeE>
static FString Format (const TCHAR *InFormatString, const TypeA &InArgA, const TypeB &InArgB, const TypeC &InArgC, const TypeD &InArgD, const TypeE &InArgE)
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD, typename TypeE, typename TypeF>
static FString Format (const TCHAR *InFormatString, const TypeA &InArgA, const TypeB &InArgB, const TypeC &InArgC, const TypeD &InArgD, const TypeE &InArgE, const TypeF &InArgF)
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD, typename TypeE, typename TypeF, typename TypeG>
static FString Format (const TCHAR *InFormatString, const TypeA &InArgA, const TypeB &InArgB, const TypeC &InArgC, const TypeD &InArgD, const TypeE &InArgE, const TypeF &InArgF, const TypeG &InArgG)
static FString FormatArgs (const TCHAR *InFormatString, const FStringFormatOrderedArguments &InArgs)
static TArray< int32 > GetInstructionIndicesFromRange (int32 First, int32 Last)
static const TMap< FName, TStructConstGenerator > & GetStructConstGenerators ()
static FString SanitizeName (const FString &InName, const FString &CPPType=FString())
static FString SanitizeValue (const FString &InValue, const FString &CPPType, const UObject *CPPTypeObject)
Private Attributes
FString ClassName
TMap< FString, FRigVMDispatchInfo > Dispatches
FString ExecuteContextType
FStringArray Includes
TArray< FInstructionGroup > InstructionGroups
FStringArray Libraries
TMap< FString, FMappedType > MappedCPPTypes
TMap< FName, FName > MappedPropertyNames
int32 MaxInstructionsPerFunction
TStrongObjectPtr< URigVMGraph > Model
FString ModuleName
TMap< FRigVMOperand, FString > OperandToPinMap
TMap< FString, FString > OverriddenOperatorNames
TMap< FString, FRigVMOperand > PinToOperandMap
TArray< FPropertyInfo > Properties
TMap< FName, int32 > PropertyNameToIndex
TMap< TRigVMTypeIndex, TTuple< FString, FString > > RequiredUProperties
TStrongObjectPtr< URigVM > VM
Detailed Description
Definition at line 13 of file RigVMCodeGenerator.h.
Member Typedef Documentation
FMappedType
typedef TTuple<FString, FString> FRigVMCodeGenerator::FMappedType private
Definition at line 53 of file RigVMCodeGenerator.h.
FRigVMPropertyDescriptionArray
typedef TArray<FRigVMPropertyDescription> FRigVMCodeGenerator::FRigVMPropertyDescriptionArray private
Definition at line 52 of file RigVMCodeGenerator.h.
FStringArray
typedef TArray<FString> FRigVMCodeGenerator::FStringArray private
Definition at line 50 of file RigVMCodeGenerator.h.
FStringMap
typedef TMap<FString, FString> FRigVMCodeGenerator::FStringMap private
Definition at line 51 of file RigVMCodeGenerator.h.
TStructConstGenerator
typedef TFunction<FString(const FString&)> FRigVMCodeGenerator::TStructConstGenerator private
Definition at line 54 of file RigVMCodeGenerator.h.
Member Enumeration Documentation
ERigVMNativizedPropertyType
enum FRigVMCodeGenerator::ERigVMNativizedPropertyType private
Enumerator
Literal
Work
Sliced
Invalid
Definition at line 56 of file RigVMCodeGenerator.h.
Constructor & Destructor Documentation
FRigVMCodeGenerator()
FRigVMCodeGenerator::FRigVMCodeGenerator (const FString & InClassName, const FString & InModuleName, URigVMGraph * InModelToNativize, URigVM * InVMToNativize, FRigVMExtendedExecuteContext & InVMContext, const UScriptStruct * PublicContextStruct, TMap< FString, FRigVMOperand > InPinToOperandMap, int32 InMaxInstructionsPerFunction = 100) inline
Definition at line 17 of file RigVMCodeGenerator.h.
References ParseVM().
Member Function Documentation
CheckOperand()
void FRigVMCodeGenerator::CheckOperand (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
DumpBlockNames()
FString FRigVMCodeGenerator::DumpBlockNames (bool bForHeader, bool bLog = false)
References bLog.
DumpDispatches()
FString FRigVMCodeGenerator::DumpDispatches (bool bLog = false)
References bLog.
DumpEntries()
FString FRigVMCodeGenerator::DumpEntries (bool bForHeader, bool bLog = false)
References bLog.
DumpIncludes()
FString FRigVMCodeGenerator::DumpIncludes (bool bLog = false)
References bLog.
DumpInitialize()
FString FRigVMCodeGenerator::DumpInitialize (bool bLog = false)
References bLog.
DumpInstructions() [1/2]
FString FRigVMCodeGenerator::DumpInstructions (const FRigVMExtendedExecuteContext & Context, const FString & InPrefix, const TArray< int32 > InInstructionIndices, const FInstructionGroup & InGroup, bool bLog = false) private
References bLog.
DumpInstructions() [2/2]
FString FRigVMCodeGenerator::DumpInstructions (const FRigVMExtendedExecuteContext & Context, const FString & InPrefix, int32 InFirstInstruction, int32 InLastInstruction, const FInstructionGroup & InGroup, bool bLog = false) private
References bLog.
Referenced by UE_DEPRECATED().
DumpLines()
FString FRigVMCodeGenerator::DumpLines (const TArray< FString > & InLines, bool bLog = false)
References bLog.
DumpRequiredUProperties()
FString FRigVMCodeGenerator::DumpRequiredUProperties (bool bLog = false)
References bLog.
Format() [1/7]
template<typename TypeA> FString FRigVMCodeGenerator::Format (const TCHAR * InFormatString, const TypeA & InArgA) inline static private
Definition at line 141 of file RigVMCodeGenerator.h.
References FormatArgs().
Format() [2/7]
template<typename TypeA, typename TypeB> FString FRigVMCodeGenerator::Format (const TCHAR * InFormatString, const TypeA & InArgA, const TypeB & InArgB) inline static private
Definition at line 149 of file RigVMCodeGenerator.h.
References FormatArgs().
Format() [3/7]
template<typename TypeA, typename TypeB, typename TypeC> FString FRigVMCodeGenerator::Format (const TCHAR * InFormatString, const TypeA & InArgA, const TypeB & InArgB, const TypeC & InArgC) inline static private
Definition at line 158 of file RigVMCodeGenerator.h.
References FormatArgs().
Format() [4/7]
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD> FString FRigVMCodeGenerator::Format (const TCHAR * InFormatString, const TypeA & InArgA, const TypeB & InArgB, const TypeC & InArgC, const TypeD & InArgD) inline static private
Definition at line 168 of file RigVMCodeGenerator.h.
References FormatArgs().
Format() [5/7]
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD, typename TypeE> FString FRigVMCodeGenerator::Format (const TCHAR * InFormatString, const TypeA & InArgA, const TypeB & InArgB, const TypeC & InArgC, const TypeD & InArgD, const TypeE & InArgE) inline static private
Definition at line 184 of file RigVMCodeGenerator.h.
References FormatArgs().
Format() [6/7]
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD, typename TypeE, typename TypeF> FString FRigVMCodeGenerator::Format (const TCHAR * InFormatString, const TypeA & InArgA, const TypeB & InArgB, const TypeC & InArgC, const TypeD & InArgD, const TypeE & InArgE, const TypeF & InArgF) inline static private
Definition at line 202 of file RigVMCodeGenerator.h.
References FormatArgs().
Format() [7/7]
template<typename TypeA, typename TypeB, typename TypeC, typename TypeD, typename TypeE, typename TypeF, typename TypeG> FString FRigVMCodeGenerator::Format (const TCHAR * InFormatString, const TypeA & InArgA, const TypeB & InArgB, const TypeC & InArgC, const TypeD & InArgD, const TypeE & InArgE, const TypeF & InArgF, const TypeG & InArgG) inline static private
Definition at line 222 of file RigVMCodeGenerator.h.
References FormatArgs().
FormatArgs()
FString FRigVMCodeGenerator::FormatArgs (const TCHAR * InFormatString, const FStringFormatOrderedArguments & InArgs) inline static private
Definition at line 135 of file RigVMCodeGenerator.h.
Referenced by Format(), Format(), Format(), Format(), Format(), Format(), and Format().
GetEntryParameters()
FString FRigVMCodeGenerator::GetEntryParameters () const private
GetGroup()
const FInstructionGroup & FRigVMCodeGenerator::GetGroup (int32 InGroupIndex) const private
GetInstructionIndicesFromRange()
TArray< int32 > FRigVMCodeGenerator::GetInstructionIndicesFromRange (int32 First, int32 Last) static private
References First, and Last.
GetMappedArrayTypeName()
FString FRigVMCodeGenerator::GetMappedArrayTypeName (const FString InBaseElementType) const private
GetMappedType()
FString FRigVMCodeGenerator::GetMappedType (const FString & InCPPType) const private
GetMappedTypeSuffix()
const FString & FRigVMCodeGenerator::GetMappedTypeSuffix (const FString & InCPPType) const private
GetOperandCPPBaseType()
FString FRigVMCodeGenerator::GetOperandCPPBaseType (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
GetOperandCPPType()
FString FRigVMCodeGenerator::GetOperandCPPType (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
GetOperandName()
FString FRigVMCodeGenerator::GetOperandName (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand, bool bPerSlice = true, bool bAsInput = true) const private
GetPropertyDescForOperand()
FRigVMPropertyDescription FRigVMCodeGenerator::GetPropertyDescForOperand (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
GetPropertyForOperand()
FRigVMPropertyDescription FRigVMCodeGenerator::GetPropertyForOperand (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
GetPropertyIndex() [1/2]
int32 FRigVMCodeGenerator::GetPropertyIndex (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
GetPropertyIndex() [2/2]
int32 FRigVMCodeGenerator::GetPropertyIndex (const FRigVMPropertyDescription & InProperty) const private
GetPropertyPathForOperand()
const FRigVMPropertyPathDescription & FRigVMCodeGenerator::GetPropertyPathForOperand (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
GetPropertyType() [1/2]
ERigVMNativizedPropertyType FRigVMCodeGenerator::GetPropertyType (const FRigVMExtendedExecuteContext & Context, const FRigVMOperand & InOperand) const private
GetPropertyType() [2/2]
ERigVMNativizedPropertyType FRigVMCodeGenerator::GetPropertyType (const FRigVMPropertyDescription & InProperty) const private
GetStructConstGenerators()
const TMap< FName, TStructConstGenerator > & FRigVMCodeGenerator::GetStructConstGenerators () static private
IsInstructionPartOfGroup()
bool FRigVMCodeGenerator::IsInstructionPartOfGroup (int32 InInstructionIndex, int32 InGroupIndex, bool bIncludeChildGroups) const private
IsPropertyPartOfGroup()
bool FRigVMCodeGenerator::IsPropertyPartOfGroup (int32 InPropertyIndex, int32 InGroupIndex) const private
ParseInclude()
void FRigVMCodeGenerator::ParseInclude (UStruct * InDependency, const FName & InMethodName = NAME_None) private
ParseInstructionGroups()
void FRigVMCodeGenerator::ParseInstructionGroups (const FRigVMExtendedExecuteContext & Context) private
ParseMemory()
void FRigVMCodeGenerator::ParseMemory (const FRigVMExtendedExecuteContext & Context, FRigVMMemoryStorageStruct * InMemory) private
ParseProperty()
void FRigVMCodeGenerator::ParseProperty (const FRigVMExtendedExecuteContext & Context, ERigVMMemoryType InMemoryType, const FProperty * InProperty, FRigVMMemoryStorageStruct * InMemory) private
ParseRequiredUProperties()
void FRigVMCodeGenerator::ParseRequiredUProperties (const FRigVMExtendedExecuteContext & Context) private
ParseVM()
void FRigVMCodeGenerator::ParseVM (const FString & InClassName, const FString & InModuleName, URigVMGraph * InModelToNativize, URigVM * InVMToNativize, FRigVMExtendedExecuteContext & InVMContext, const UScriptStruct * PublicContextStruct, TMap< FString, FRigVMOperand > InPinToOperandMap, int32 InMaxInstructionsPerFunction) private
Referenced by FRigVMCodeGenerator().
Reset()
void FRigVMCodeGenerator::Reset () private
SanitizeName()
FString FRigVMCodeGenerator::SanitizeName (const FString & InName, const FString & CPPType = FString()) static private
References InName.
SanitizeValue()
FString FRigVMCodeGenerator::SanitizeValue (const FString & InValue, const FString & CPPType, const UObject * CPPTypeObject) static private
UE_DEPRECATED() [1/5]
FRigVMCodeGenerator::UE_DEPRECATED (5. 4, " Please, use DumpExternalVariables with ExtendedExecuteContext parameter")
UE_DEPRECATED() [2/5]
FRigVMCodeGenerator::UE_DEPRECATED (5. 4, " Please, use DumpHeader with ExtendedExecuteContext parameter")
References bLog.
UE_DEPRECATED() [3/5]
FRigVMCodeGenerator::UE_DEPRECATED (5. 4, " Please, use DumpInstructions with ExtendedExecuteContext parameter")
References bLog, DumpInstructions(), and InInstructionGroup.
UE_DEPRECATED() [4/5]
FRigVMCodeGenerator::UE_DEPRECATED (5. 4, " Please, use DumpProperties with ExtendedExecuteContext parameter")
UE_DEPRECATED() [5/5]
FRigVMCodeGenerator::UE_DEPRECATED (5. 4, " Please, use DumpSource with ExtendedExecuteContext parameter")
References bLog.
Field Documentation
bLog [1/2]
bool FRigVMCodeGenerator::bLog
Initial value:
= false) { return FString(); }
    FString DumpExternalVariables(const FRigVMExtendedExecuteContext& Context, bool bForHeader, bool bLog = false)
Definition at line 27 of file RigVMCodeGenerator.h.
Referenced by DumpBlockNames(), DumpDispatches(), DumpEntries(), DumpIncludes(), DumpInitialize(), DumpInstructions(), DumpInstructions(), DumpLines(), DumpRequiredUProperties(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
bLog [2/2]
int32 bool FRigVMCodeGenerator::bLog
Initial value:
= false) { return FString(); }
    FString DumpProperties(const FRigVMExtendedExecuteContext& Context, bool bForHeader, int32 InInstructionGroup, bool bLog = false)
Definition at line 32 of file RigVMCodeGenerator.h.
ClassName
FString FRigVMCodeGenerator::ClassName private
Definition at line 248 of file RigVMCodeGenerator.h.
Dispatches
TMap<FString, FRigVMDispatchInfo> FRigVMCodeGenerator::Dispatches private
Definition at line 262 of file RigVMCodeGenerator.h.
ExecuteContextType
FString FRigVMCodeGenerator::ExecuteContextType private
Definition at line 250 of file RigVMCodeGenerator.h.
Includes
FStringArray FRigVMCodeGenerator::Includes private
Definition at line 253 of file RigVMCodeGenerator.h.
InInstructionGroup
int32 FRigVMCodeGenerator::InInstructionGroup
Definition at line 32 of file RigVMCodeGenerator.h.
Referenced by UE_DEPRECATED().
InstructionGroups
TArray<FInstructionGroup> FRigVMCodeGenerator::InstructionGroups private
Definition at line 264 of file RigVMCodeGenerator.h.
Libraries
FStringArray FRigVMCodeGenerator::Libraries private
Definition at line 252 of file RigVMCodeGenerator.h.
MappedCPPTypes
TMap<FString, FMappedType> FRigVMCodeGenerator::MappedCPPTypes private
Definition at line 265 of file RigVMCodeGenerator.h.
MappedPropertyNames
TMap<FName, FName> FRigVMCodeGenerator::MappedPropertyNames private
Definition at line 268 of file RigVMCodeGenerator.h.
MaxInstructionsPerFunction
int32 FRigVMCodeGenerator::MaxInstructionsPerFunction private
Definition at line 247 of file RigVMCodeGenerator.h.
Model
TStrongObjectPtr<URigVMGraph> FRigVMCodeGenerator::Model private
Definition at line 243 of file RigVMCodeGenerator.h.
ModuleName
FString FRigVMCodeGenerator::ModuleName private
Definition at line 249 of file RigVMCodeGenerator.h.
OperandToPinMap
TMap<FRigVMOperand, FString> FRigVMCodeGenerator::OperandToPinMap private
Definition at line 246 of file RigVMCodeGenerator.h.
OverriddenOperatorNames
TMap<FString, FString> FRigVMCodeGenerator::OverriddenOperatorNames private
Definition at line 269 of file RigVMCodeGenerator.h.
PinToOperandMap
TMap<FString,FRigVMOperand> FRigVMCodeGenerator::PinToOperandMap private
Definition at line 245 of file RigVMCodeGenerator.h.
Properties
TArray<FPropertyInfo> FRigVMCodeGenerator::Properties private
Definition at line 266 of file RigVMCodeGenerator.h.
PropertyNameToIndex
TMap<FName, int32> FRigVMCodeGenerator::PropertyNameToIndex private
Definition at line 267 of file RigVMCodeGenerator.h.
RequiredUProperties
TMap<TRigVMTypeIndex,TTuple<FString,FString> > FRigVMCodeGenerator::RequiredUProperties private
Definition at line 263 of file RigVMCodeGenerator.h.
VM
TStrongObjectPtr<URigVM> FRigVMCodeGenerator::VM private
Definition at line 244 of file RigVMCodeGenerator.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMCompiler/RigVMCodeGenerator.h