Unreal Engine 5.6 C++ API: TBitArray< Allocator >::FWordIterator Struct Reference
TBitArray< Allocator >::FWordIterator Struct Reference
#include "BitArray.h"
Public Member Functions
FWordIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND)
void SetWord (uint32 InWord)
Public Member Functions inherited from TBitArray< Allocator >::TWordIteratorBase< uint32 >
void FillMissingBits (uint32 InMissingBitsFill)
int32 GetIndex () const
uint32 GetWord () const
operator bool () const
void operator++ ()
Additional Inherited Members
Protected Member Functions inherited from TBitArray< Allocator >::TWordIteratorBase< uint32 >
TWordIteratorBase (uint32 *InData, int32 InStartBitIndex, int32 InEndBitIndex)
Protected Attributes inherited from TBitArray< Allocator >::TWordIteratorBase< uint32 >
int32 CurrentIndex
uint32 CurrentMask
uint32 *RESTRICT Data
uint32 FinalMask
uint32 MissingBitsFill
int32 NumWords
Detailed Description
template<typename Allocator>
struct TBitArray< Allocator >::FWordIterator
Definition at line 1787 of file BitArray.h.
Constructor & Destructor Documentation
FWordIterator()
template<typename Allocator> TBitArray< Allocator >::FWordIterator::FWordIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND) inline explicit nodiscard
Definition at line 1789 of file BitArray.h.
References TBitArray< Allocator >::TBitArray(), TBitArray< Allocator >::TWordIteratorBase< uint32 >::TWordIteratorBase(), TBitArray< Allocator >::GetData(), TBitArray< Allocator >::Num(), and UE_LIFETIMEBOUND.
Member Function Documentation
SetWord()
template<typename Allocator> void TBitArray< Allocator >::FWordIterator::SetWord (uint32 InWord) inline
Definition at line 1794 of file BitArray.h.
References checkSlow, TBitArray< Allocator >::TWordIteratorBase< uint32 >::CurrentIndex, TBitArray< Allocator >::TWordIteratorBase< uint32 >::Data, TBitArray< Allocator >::TWordIteratorBase< uint32 >::FinalMask, and TBitArray< Allocator >::TWordIteratorBase< uint32 >::NumWords.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/BitArray.h