Unreal Engine 5.6 C++ API: FFolder Struct Reference
FFolder Struct Reference
#include "Folder.h"
Public Types
typedef FObjectKey FRootObject
Public Member Functions
FFolder ()
FFolder (const FRootObject &InRootObject, const FGuid &InActorFolderGuid)
FFolder (const FRootObject &InRootObject, const FName &InPath=GetEmptyPath())
UActorFolder * GetActorFolder () const
FORCEINLINE const FGuid & GetActorFolderGuid () const
FORCEINLINE FName GetLeafName () const
FFolder GetParent () const
const FName GetPath () const
FORCEINLINE const FRootObject & GetRootObject () const
FORCEINLINE ULevel * GetRootObjectAssociatedLevel () const
FORCEINLINE UObject * GetRootObjectPtr () const
FORCEINLINE bool IsChildOf (const FFolder &InParent) const
FORCEINLINE bool IsNone () const
FORCEINLINE bool IsRootObjectPersistentLevel () const
FORCEINLINE bool IsRootObjectValid () const
FORCEINLINE bool IsValid () const
FORCEINLINE bool operator!= (const FFolder &InOther) const
FORCEINLINE bool operator== (const FFolder &InOther) const
FORCEINLINE FString ToString () const
Static Public Member Functions
static FORCEINLINE FName GetEmptyPath ()
static bool GetFolderPathsAndCommonRootObject (const TArray< FFolder > &InFolders, TArray< FName > &OutFolders, FRootObject &OutCommonRootObject)
static const FFolder & GetInvalidFolder ()
static const FRootObject & GetInvalidRootObject ()
static TOptional< FRootObject > GetOptionalFolderRootObject (const ULevel *InLevel)
static ULevel * GetRootObjectAssociatedLevel (const FRootObject &Key)
static FORCEINLINE UObject * GetRootObjectPtr (const FRootObject &InRootObject)
static FFolder GetWorldRootFolder (UWorld *InWorld)
static bool IsRootObjectPersistentLevel (const FRootObject &Key)
static FORCEINLINE bool IsRootObjectValid (const FRootObject &Key)
Private Member Functions
bool PathIsChildOf (const FName &InPotentialChild, const FName &InParent) const
bool PathIsChildOf (const FString &InPotentialChild, const FString &InParent) const
Private Attributes
FGuid ActorFolderGuid
bool bPathInitialized
FName Path
FRootObject RootObject
Friends
FORCEINLINE uint32 GetTypeHash (const FFolder &InFolder)
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, FFolder &Folder)
Detailed Description
Definition at line 17 of file Folder.h.
Member Typedef Documentation
FRootObject
typedef FObjectKey FFolder::FRootObject
Definition at line 20 of file Folder.h.
Constructor & Destructor Documentation
FFolder() [1/3]
FFolder::FFolder () inline
Definition at line 23 of file Folder.h.
References bPathInitialized, GetEmptyPath(), GetInvalidRootObject(), Path, and RootObject.
Referenced by GetInvalidFolder(), GetParent(), GetTypeHash, GetWorldRootFolder(), IsChildOf(), operator!=(), operator<<, and operator==().
FFolder() [2/3]
FFolder::FFolder (const FRootObject & InRootObject, const FName & InPath = GetEmptyPath()) inline
Definition at line 29 of file Folder.h.
References bPathInitialized, GetEmptyPath(), Path, RootObject, and TEXT.
FFolder() [3/3]
FFolder::FFolder (const FRootObject & InRootObject, const FGuid & InActorFolderGuid) inline
Definition at line 51 of file Folder.h.
References ActorFolderGuid, bPathInitialized, check, Path, and RootObject.
Member Function Documentation
GetActorFolder()
UActorFolder * FFolder::GetActorFolder () const
GetActorFolderGuid()
FORCEINLINE const FGuid & FFolder::GetActorFolderGuid () const inline
Definition at line 119 of file Folder.h.
References ActorFolderGuid, and FORCEINLINE.
Referenced by USTRUCT().
GetEmptyPath()
FORCEINLINE FName FFolder::GetEmptyPath () inline static
Definition at line 70 of file Folder.h.
References FORCEINLINE.
Referenced by FFolder(), and FFolder().
GetFolderPathsAndCommonRootObject()
bool FFolder::GetFolderPathsAndCommonRootObject (const TArray< FFolder > & InFolders, TArray< FName > & OutFolders, FRootObject & OutCommonRootObject) static
GetInvalidFolder()
const FFolder & FFolder::GetInvalidFolder () static
References FFolder().
GetInvalidRootObject()
const FRootObject & FFolder::GetInvalidRootObject () static
Referenced by FFolder(), FActorFolders::ForEachActorDescInstanceInFolders(), FActorFolders::ForEachActorInFolders(), FActorFolders::ForEachActorInFolders(), FActorFolders::GetActorsFromFolders(), FActorFolders::GetActorsFromFolders(), FActorFolders::GetWeakActorsFromFolders(), FActorFolders::GetWeakActorsFromFolders(), FFolderDragDropOp::Init(), and IsRootObjectValid().
GetLeafName()
FORCEINLINE FName FFolder::GetLeafName () const inline
Definition at line 124 of file Folder.h.
References FName, FORCEINLINE, GetPath(), and FName::ToString().
GetOptionalFolderRootObject()
TOptional< FRootObject > FFolder::GetOptionalFolderRootObject (const ULevel * InLevel) static
GetParent()
FFolder FFolder::GetParent () const
References FFolder().
GetPath()
const FName FFolder::GetPath () const
Referenced by GetLeafName(), GetTypeHash, IsChildOf(), IsNone(), operator==(), ToString(), and USTRUCT().
GetRootObject()
FORCEINLINE const FRootObject & FFolder::GetRootObject () const inline
Definition at line 109 of file Folder.h.
References FORCEINLINE, and RootObject.
Referenced by GetTypeHash.
GetRootObjectAssociatedLevel() [1/2]
FORCEINLINE ULevel * FFolder::GetRootObjectAssociatedLevel () const inline
Definition at line 80 of file Folder.h.
References FORCEINLINE, GetRootObjectAssociatedLevel(), and RootObject.
Referenced by GetRootObjectAssociatedLevel().
GetRootObjectAssociatedLevel() [2/2]
ULevel * FFolder::GetRootObjectAssociatedLevel (const FRootObject & Key) static
References Key.
GetRootObjectPtr() [1/2]
FORCEINLINE UObject * FFolder::GetRootObjectPtr () const inline
Definition at line 114 of file Folder.h.
References FORCEINLINE, GetRootObjectPtr(), and RootObject.
Referenced by GetRootObjectPtr().
GetRootObjectPtr() [2/2]
FORCEINLINE UObject * FFolder::GetRootObjectPtr (const FRootObject & InRootObject) inline static
Definition at line 60 of file Folder.h.
References FORCEINLINE, and FObjectKey::ResolveObjectPtr().
Referenced by USTRUCT().
GetWorldRootFolder()
FFolder FFolder::GetWorldRootFolder (UWorld * InWorld) static
References FFolder().
IsChildOf()
FORCEINLINE bool FFolder::IsChildOf (const FFolder & InParent) const inline
Definition at line 95 of file Folder.h.
References FFolder(), FORCEINLINE, GetPath(), PathIsChildOf(), and RootObject.
IsNone()
FORCEINLINE bool FFolder::IsNone () const inline
Definition at line 104 of file Folder.h.
References FORCEINLINE, GetPath(), and FName::IsNone().
IsRootObjectPersistentLevel() [1/2]
FORCEINLINE bool FFolder::IsRootObjectPersistentLevel () const inline
Definition at line 85 of file Folder.h.
References FORCEINLINE, IsRootObjectPersistentLevel(), and RootObject.
Referenced by IsRootObjectPersistentLevel().
IsRootObjectPersistentLevel() [2/2]
bool FFolder::IsRootObjectPersistentLevel (const FRootObject & Key) static
References Key.
IsRootObjectValid() [1/2]
FORCEINLINE bool FFolder::IsRootObjectValid () const inline
Definition at line 75 of file Folder.h.
References FORCEINLINE, IsRootObjectValid(), and RootObject.
Referenced by IsRootObjectValid(), and IsValid().
IsRootObjectValid() [2/2]
FORCEINLINE bool FFolder::IsRootObjectValid (const FRootObject & Key) inline static
Definition at line 65 of file Folder.h.
References FORCEINLINE, GetInvalidRootObject(), and Key.
IsValid()
FORCEINLINE bool FFolder::IsValid () const inline
Definition at line 90 of file Folder.h.
References FORCEINLINE, and IsRootObjectValid().
operator!=()
FORCEINLINE bool FFolder::operator!= (const FFolder & InOther) const inline
Definition at line 144 of file Folder.h.
References FFolder(), FORCEINLINE, and operator==().
operator==()
FORCEINLINE bool FFolder::operator== (const FFolder & InOther) const inline
Definition at line 139 of file Folder.h.
References FFolder(), FORCEINLINE, GetPath(), and RootObject.
Referenced by operator!=().
PathIsChildOf() [1/2]
bool FFolder::PathIsChildOf (const FName & InPotentialChild, const FName & InParent) const inline private
Definition at line 190 of file Folder.h.
References PathIsChildOf(), and FName::ToString().
PathIsChildOf() [2/2]
bool FFolder::PathIsChildOf (const FString & InPotentialChild, const FString & InParent) const inline private
Definition at line 174 of file Folder.h.
Referenced by IsChildOf(), and PathIsChildOf().
ToString()
FORCEINLINE FString FFolder::ToString () const inline
Definition at line 149 of file Folder.h.
References FORCEINLINE, GetPath(), and FName::ToString().
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FFolder & InFolder) friend
Definition at line 200 of file Folder.h.
References FFolder(), FORCEINLINE, GetPath(), GetRootObject(), GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
operator<<
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, FFolder & Folder) friend
Definition at line 154 of file Folder.h.
References FFolder(), ActorFolderGuid, Ar, bPathInitialized, check, FORCEINLINE, Path, and RootObject.
Field Documentation
ActorFolderGuid
FGuid FFolder::ActorFolderGuid mutable private
Definition at line 198 of file Folder.h.
Referenced by FFolder(), GetActorFolderGuid(), and operator<<.
bPathInitialized
bool FFolder::bPathInitialized mutable private
Definition at line 195 of file Folder.h.
Referenced by FFolder(), FFolder(), FFolder(), and operator<<.
Path
FName FFolder::Path mutable private
Definition at line 196 of file Folder.h.
Referenced by FFolder(), FFolder(), FFolder(), and operator<<.
RootObject
FRootObject FFolder::RootObject private
Definition at line 197 of file Folder.h.
Referenced by FFolder(), FFolder(), FFolder(), GetRootObject(), GetRootObjectAssociatedLevel(), GetRootObjectPtr(), IsChildOf(), IsRootObjectPersistentLevel(), IsRootObjectValid(), operator<<, and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Folder.h