Unreal Engine 5.6 C++ API: FRigVMRegistry_NoLock Struct Reference
FRigVMRegistry_NoLock Struct Reference abstract
The FRigVMRegistry is used to manage all known function pointers for use in the RigVM.
#include "RigVMRegistry.h"
Data Structures
struct FTypeInfo
Public Types
enum ELockType : uint8 { LockType_Read , LockType_Write , LockType_Invalid }
enum class ERegisterObjectOperation { Class , ClassAndParents , ClassAndChildren }
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Public Member Functions
virtual RIGVM_API ~FRigVMRegistry_NoLock () override
virtual RIGVM_API void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
virtual RIGVM_API const FRigVMTemplate * AddTemplateFromArguments_NoLock (const FName &InName, const TArray< FRigVMTemplateArgumentInfo > &InInfos, const FRigVMTemplateDelegates &InDelegates)
virtual RIGVM_API bool CanMatchTypes_NoLock (TRigVMTypeIndex InTypeIndexA, TRigVMTypeIndex InTypeIndexB, bool bAllowFloatingPointCasts) const
virtual RIGVM_API bool ConvertExecuteContextToBaseType_NoLock (TRigVMTypeIndex &InOutTypeIndex) const
DECLARE_MULTICAST_DELEGATE (FOnRigVMRegistryChanged)
virtual RIGVM_API FRigVMDispatchFactory * FindDispatchFactory_NoLock (const FName &InFactoryName) const
virtual RIGVM_API const FRigVMFunction * FindFunction_NoLock (const TCHAR *InName, const FRigVMUserDefinedTypeResolver &InTypeResolver=FRigVMUserDefinedTypeResolver()) const
virtual RIGVM_API const FRigVMFunction * FindFunction_NoLock (UScriptStruct *InStruct, const TCHAR *InName, const FRigVMUserDefinedTypeResolver &InResolvalInfo=FRigVMUserDefinedTypeResolver()) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
FRigVMDispatchFactory * FindOrAddDispatchFactory_NoLock ()
virtual RIGVM_API FRigVMDispatchFactory * FindOrAddDispatchFactory_NoLock (UScriptStruct *InFactoryStruct)
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
FString FindOrAddSingletonDispatchFunction_NoLock ()
virtual RIGVM_API FString FindOrAddSingletonDispatchFunction_NoLock (UScriptStruct *InFactoryStruct)
virtual RIGVM_API TRigVMTypeIndex FindOrAddType_NoLock (const FRigVMTemplateArgumentType &InType, bool bForce=false)
virtual RIGVM_API const FRigVMTemplate * FindTemplate_NoLock (const FName &InNotation, bool bIncludeDeprecated=false) const
virtual RIGVM_API const FRigVMTemplateArgumentType & FindTypeFromCPPType_NoLock (const FString &InCPPType) const
virtual RIGVM_API int32 GetArrayDimensionsForType_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual RIGVM_API TRigVMTypeIndex GetArrayTypeFromBaseTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual RIGVM_API TRigVMTypeIndex GetBaseTypeFromArrayTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual RIGVM_API const TArray< TRigVMTypeIndex > & GetCompatibleTypes_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual RIGVM_API const TArray< FRigVMDispatchFactory * > & GetFactories_NoLock () const
virtual RIGVM_API const TChunkedArray< FRigVMFunction > & GetFunctions_NoLock () const
virtual RIGVM_API uint32 GetHashForEnum_NoLock (const UEnum *InEnum, bool bCheckTypeIndex=true) const
virtual RIGVM_API uint32 GetHashForProperty_NoLock (const FProperty *InProperty) const
virtual RIGVM_API uint32 GetHashForScriptStruct_NoLock (const UScriptStruct *InScriptStruct, bool bCheckTypeIndex=true) const
virtual RIGVM_API uint32 GetHashForStruct_NoLock (const UStruct *InStruct) const
virtual RIGVM_API uint32 GetHashForType_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual RIGVM_API const FRigVMTemplate * GetOrAddTemplateFromArguments_NoLock (const FName &InName, const TArray< FRigVMTemplateArgumentInfo > &InInfos, const FRigVMTemplateDelegates &InDelegates)
virtual RIGVM_API const TArray< FRigVMFunction > * GetPredicatesForStruct_NoLock (const FName &InStructName) const
virtual RIGVM_API FString GetReferencerName () const override
Overload this method to report a name for your referencer.
virtual RIGVM_API const TChunkedArray< FRigVMTemplate > & GetTemplates_NoLock () const
virtual RIGVM_API const FRigVMTemplateArgumentType & GetType_NoLock (TRigVMTypeIndex InTypeIndex) const
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
virtual TRigVMTypeIndex GetTypeIndex_NoLock (const FName &InCPPType, UObject *InCPPTypeObject) const
virtual RIGVM_API TRigVMTypeIndex GetTypeIndex_NoLock (const FRigVMTemplateArgumentType &InType) const
virtual RIGVM_API TRigVMTypeIndex GetTypeIndexFromCPPType_NoLock (const FString &InCPPType) const
virtual RIGVM_API const TArray< TRigVMTypeIndex > & GetTypesForCategory_NoLock (FRigVMTemplateArgument::ETypeCategory InCategory) const
virtual RIGVM_API bool IsArrayType_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual RIGVM_API bool IsExecuteType_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual RIGVM_API bool IsWildCardType_NoLock (TRigVMTypeIndex InTypeIndex) const
virtual int32 NumTypes_NoLock () const
virtual RIGVM_API void OnAnimationAttributeTypesChanged_NoLock (const UScriptStruct *InStruct, bool bIsAdded)
virtual RIGVM_API bool OnAssetRemoved_NoLock (const FAssetData &InAssetData)
virtual RIGVM_API void OnAssetRenamed_NoLock (const FAssetData &InAssetData, const FString &InOldObjectPath)
virtual RIGVM_API bool OnPluginLoaded_NoLock (IPlugin &InPlugin)
virtual RIGVM_API bool OnPluginUnloaded_NoLock (IPlugin &InPlugin)
virtual RIGVM_API void RebuildRegistry_NoLock ()
virtual RIGVM_API void RefreshEngineTypes_NoLock ()
virtual RIGVM_API void RefreshEngineTypesIfRequired_NoLock ()
virtual RIGVM_API bool RefreshFunctionsAndDispatches_NoLock ()
virtual RIGVM_API void Register_NoLock (const TCHAR *InName, FRigVMFunctionPtr InFunctionPtr, UScriptStruct *InStruct=nullptr, const TArray< FRigVMFunctionArgument > &InArguments=TArray< FRigVMFunctionArgument >())
virtual RIGVM_API const FRigVMDispatchFactory * RegisterFactory_NoLock (UScriptStruct *InFactoryStruct)
virtual RIGVM_API void RegisterObjectTypes_NoLock (TConstArrayView< TPair< UClass *, ERegisterObjectOperation > > InClasses)
virtual RIGVM_API void RegisterPredicate_NoLock (UScriptStruct *InStruct, const TCHAR *InName, const TArray< FRigVMFunctionArgument > &InArguments)
virtual RIGVM_API void RegisterStructTypes_NoLock (TConstArrayView< UScriptStruct * > InStructs)
virtual RIGVM_API bool RemoveType_NoLock (const FSoftObjectPath &InObjectPath, const UClass *InObjectClass)
virtual RIGVM_API void Reset_NoLock ()
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Member Functions
static RIGVM_API FRigVMRegistry_NoLock & Get (ELockType InLockType)
static const FRigVMRegistry_NoLock & GetForRead ()
static FRigVMRegistry_NoLock & GetForWrite ()
static RIGVM_API const TArray< UScriptStruct * > & GetMathTypes ()
static RIGVM_API void OnEngineInit ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes
static const FLazyName TemplateNameMetaName = FLazyName(TEXT("TemplateName"))
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Member Functions
RIGVM_API FRigVMRegistry_NoLock ()
FRigVMRegistry_NoLock (const FRigVMRegistry_NoLock &)=delete
virtual void Initialize (bool bLockRegistry)=0
RIGVM_API void Initialize_NoLock ()
RIGVM_API bool IsAllowedType_NoLock (const FProperty *InProperty) const
RIGVM_API bool IsAllowedType_NoLock (const UClass *InClass) const
RIGVM_API bool IsAllowedType_NoLock (const UEnum *InEnum) const
RIGVM_API bool IsAllowedType_NoLock (const UStruct *InStruct) const
FRigVMRegistry_NoLock & operator= (const FRigVMRegistry_NoLock &InOther)=delete
RIGVM_API void PropagateTypeAddedToCategory_NoLock (const FRigVMTemplateArgument::ETypeCategory InCategory, const TRigVMTypeIndex InTypeIndex)
RIGVM_API void RegisterTypeInCategory_NoLock (const FRigVMTemplateArgument::ETypeCategory InCategory, const TRigVMTypeIndex InTypeIndex)
RIGVM_API void RemoveTypeInCategory_NoLock (FRigVMTemplateArgument::ETypeCategory InCategory, TRigVMTypeIndex InTypeIndex)
Static Protected Member Functions
static EObjectFlags DisallowedFlags ()
static RIGVM_API bool IsTypeOfByName (const UObject *InObject, const FName &InName)
static EObjectFlags NeededFlags ()
Protected Attributes
TSet< TObjectPtr< const UClass > > AllowedClasses
TSet< TObjectPtr< const UScriptStruct > > AllowedStructs
bool bAvoidTypePropagation
bool bEverRefreshedDispatchFactoriesAfterEngineInit
bool bEverRefreshedEngineTypes
TMap< FName, int32 > DeprecatedTemplateNotationToIndex
TChunkedArray< FRigVMTemplate > DeprecatedTemplates
TArray< FRigVMDispatchFactory * > Factories
TMap< FName, int32 > FunctionNameToIndex
TChunkedArray< FRigVMFunction > Functions
TMap< FName, TArray< FRigVMFunction > > StructNameToPredicates
TMap< FName, int32 > TemplateNotationToIndex
TChunkedArray< FRigVMTemplate > Templates
TMap< FRigVMTemplateArgument::ETypeCategory, TArray< int32 > > TemplatesPerCategory
TArray< FTypeInfo > Types
TMap< FRigVMTemplateArgument::ETypeCategory, TArray< TRigVMTypeIndex > > TypesPerCategory
TMap< FRigVMTemplateArgumentType, TRigVMTypeIndex > TypeToIndex
TMap< FSoftObjectPath, TRigVMTypeIndex > UserDefinedTypeToIndex
Friends
struct FRigVMDispatchFactory
struct FRigVMStruct
struct FRigVMTemplate
struct FRigVMTemplateArgument
Detailed Description
The FRigVMRegistry is used to manage all known function pointers for use in the RigVM.
The Register method is called automatically when the static struct is initially constructed for each USTRUCT hosting a RIGVM_METHOD enabled virtual function.
Inheriting from FGCObject to ensure that all type objects cannot be GCed
Definition at line 42 of file RigVMRegistry.h.
Member Enumeration Documentation
ELockType
enum FRigVMRegistry_NoLock::ELockType : uint8
Enumerator
LockType_Read
LockType_Write
LockType_Invalid
Definition at line 46 of file RigVMRegistry.h.
ERegisterObjectOperation
enum class FRigVMRegistry_NoLock::ERegisterObjectOperation strong
Enumerator
Class
ClassAndParents
ClassAndChildren
Definition at line 78 of file RigVMRegistry.h.
Constructor & Destructor Documentation
~FRigVMRegistry_NoLock()
virtual RIGVM_API FRigVMRegistry_NoLock::~FRigVMRegistry_NoLock () override virtual
References UE_API.
FRigVMRegistry_NoLock() [1/2]
RIGVM_API FRigVMRegistry_NoLock::FRigVMRegistry_NoLock () protected
References UE_API.
Referenced by FRigVMRegistry_NoLock(), Get(), GetForRead(), GetForWrite(), and operator=().
FRigVMRegistry_NoLock() [2/2]
FRigVMRegistry_NoLock::FRigVMRegistry_NoLock (const FRigVMRegistry_NoLock &) protected delete
References FRigVMRegistry_NoLock().
Member Function Documentation
AddReferencedObjects()
virtual RIGVM_API void FRigVMRegistry_NoLock::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
References UE_API.
AddTemplateFromArguments_NoLock()
virtual RIGVM_API const FRigVMTemplate * FRigVMRegistry_NoLock::AddTemplateFromArguments_NoLock (const FName & InName, const TArray< FRigVMTemplateArgumentInfo > & InInfos, const FRigVMTemplateDelegates & InDelegates) virtual
Reimplemented in FRigVMRegistry_RWLock.
References FRigVMTemplate, InName, and UE_API.
Referenced by FRigVMRegistry_RWLock::AddTemplateFromArguments(), and FRigVMRegistry_RWLock::AddTemplateFromArguments_NoLock().
CanMatchTypes_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::CanMatchTypes_NoLock (TRigVMTypeIndex InTypeIndexA, TRigVMTypeIndex InTypeIndexB, bool bAllowFloatingPointCasts) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::CanMatchTypes(), and FRigVMRegistry_RWLock::CanMatchTypes_NoLock().
ConvertExecuteContextToBaseType_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::ConvertExecuteContextToBaseType_NoLock (TRigVMTypeIndex & InOutTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::ConvertExecuteContextToBaseType(), and FRigVMRegistry_RWLock::ConvertExecuteContextToBaseType_NoLock().
DECLARE_MULTICAST_DELEGATE()
FRigVMRegistry_NoLock::DECLARE_MULTICAST_DELEGATE (FOnRigVMRegistryChanged)
DisallowedFlags()
EObjectFlags FRigVMRegistry_NoLock::DisallowedFlags () inline static protected
Definition at line 353 of file RigVMRegistry.h.
References RF_BeginDestroyed, and RF_FinishDestroyed.
FindDispatchFactory_NoLock()
virtual RIGVM_API FRigVMDispatchFactory * FRigVMRegistry_NoLock::FindDispatchFactory_NoLock (const FName & InFactoryName) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References FRigVMDispatchFactory, and UE_API.
Referenced by FRigVMRegistry_RWLock::FindDispatchFactory(), and FRigVMRegistry_RWLock::FindDispatchFactory_NoLock().
FindFunction_NoLock() [1/2]
virtual RIGVM_API const FRigVMFunction * FRigVMRegistry_NoLock::FindFunction_NoLock (const TCHAR * InName, const FRigVMUserDefinedTypeResolver & InTypeResolver = FRigVMUserDefinedTypeResolver()) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References InName, and UE_API.
Referenced by FRigVMRegistry_RWLock::FindFunction(), FRigVMRegistry_RWLock::FindFunction(), FRigVMRegistry_RWLock::FindFunction_NoLock(), and FRigVMRegistry_RWLock::FindFunction_NoLock().
FindFunction_NoLock() [2/2]
virtual RIGVM_API const FRigVMFunction * FRigVMRegistry_NoLock::FindFunction_NoLock (UScriptStruct * InStruct, const TCHAR * InName, const FRigVMUserDefinedTypeResolver & InResolvalInfo = FRigVMUserDefinedTypeResolver()) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References InName, and UE_API.
FindOrAddDispatchFactory_NoLock() [1/2]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> FRigVMDispatchFactory * FRigVMRegistry_NoLock::FindOrAddDispatchFactory_NoLock () inline
Definition at line 280 of file RigVMRegistry.h.
References FindOrAddDispatchFactory_NoLock(), and FRigVMDispatchFactory.
Referenced by FRigVMRegistry_RWLock::FindOrAddDispatchFactory(), FRigVMRegistry_RWLock::FindOrAddDispatchFactory(), FindOrAddDispatchFactory_NoLock(), and FRigVMRegistry_RWLock::FindOrAddDispatchFactory_NoLock().
FindOrAddDispatchFactory_NoLock() [2/2]
virtual RIGVM_API FRigVMDispatchFactory * FRigVMRegistry_NoLock::FindOrAddDispatchFactory_NoLock (UScriptStruct * InFactoryStruct) virtual
Reimplemented in FRigVMRegistry_RWLock.
References FRigVMDispatchFactory, and UE_API.
FindOrAddSingletonDispatchFunction_NoLock() [1/2]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> FString FRigVMRegistry_NoLock::FindOrAddSingletonDispatchFunction_NoLock () inline
Definition at line 293 of file RigVMRegistry.h.
References FindOrAddSingletonDispatchFunction_NoLock().
Referenced by FRigVMRegistry_RWLock::FindOrAddSingletonDispatchFunction(), FRigVMRegistry_RWLock::FindOrAddSingletonDispatchFunction(), FindOrAddSingletonDispatchFunction_NoLock(), and FRigVMRegistry_RWLock::FindOrAddSingletonDispatchFunction_NoLock().
FindOrAddSingletonDispatchFunction_NoLock() [2/2]
virtual RIGVM_API FString FRigVMRegistry_NoLock::FindOrAddSingletonDispatchFunction_NoLock (UScriptStruct * InFactoryStruct) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
FindOrAddType_NoLock()
virtual RIGVM_API TRigVMTypeIndex FRigVMRegistry_NoLock::FindOrAddType_NoLock (const FRigVMTemplateArgumentType & InType, bool bForce = false) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::FindOrAddType(), and FRigVMRegistry_RWLock::FindOrAddType_NoLock().
FindTemplate_NoLock()
virtual RIGVM_API const FRigVMTemplate * FRigVMRegistry_NoLock::FindTemplate_NoLock (const FName & InNotation, bool bIncludeDeprecated = false) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References FRigVMTemplate, and UE_API.
Referenced by FRigVMRegistry_RWLock::FindTemplate(), and FRigVMRegistry_RWLock::FindTemplate_NoLock().
FindTypeFromCPPType_NoLock()
virtual RIGVM_API const FRigVMTemplateArgumentType & FRigVMRegistry_NoLock::FindTypeFromCPPType_NoLock (const FString & InCPPType) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::FindTypeFromCPPType(), and FRigVMRegistry_RWLock::FindTypeFromCPPType_NoLock().
Get()
RIGVM_API FRigVMRegistry_NoLock & FRigVMRegistry_NoLock::Get (ELockType InLockType) static
References FRigVMRegistry_NoLock(), and UE_API.
Referenced by GetForRead(), and GetForWrite().
GetArrayDimensionsForType_NoLock()
virtual RIGVM_API int32 FRigVMRegistry_NoLock::GetArrayDimensionsForType_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetArrayDimensionsForType(), and FRigVMRegistry_RWLock::GetArrayDimensionsForType_NoLock().
GetArrayTypeFromBaseTypeIndex_NoLock()
virtual RIGVM_API TRigVMTypeIndex FRigVMRegistry_NoLock::GetArrayTypeFromBaseTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetArrayTypeFromBaseTypeIndex(), and FRigVMRegistry_RWLock::GetArrayTypeFromBaseTypeIndex_NoLock().
GetBaseTypeFromArrayTypeIndex_NoLock()
virtual RIGVM_API TRigVMTypeIndex FRigVMRegistry_NoLock::GetBaseTypeFromArrayTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetBaseTypeFromArrayTypeIndex(), and FRigVMRegistry_RWLock::GetBaseTypeFromArrayTypeIndex_NoLock().
GetCompatibleTypes_NoLock()
virtual RIGVM_API const TArray< TRigVMTypeIndex > & FRigVMRegistry_NoLock::GetCompatibleTypes_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetCompatibleTypes(), and FRigVMRegistry_RWLock::GetCompatibleTypes_NoLock().
GetFactories_NoLock()
virtual RIGVM_API const TArray< FRigVMDispatchFactory * > & FRigVMRegistry_NoLock::GetFactories_NoLock () const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetFactories(), and FRigVMRegistry_RWLock::GetFactories_NoLock().
GetForRead()
const FRigVMRegistry_NoLock & FRigVMRegistry_NoLock::GetForRead () inline static
Definition at line 55 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock(), Get(), and LockType_Read.
GetForWrite()
FRigVMRegistry_NoLock & FRigVMRegistry_NoLock::GetForWrite () inline static
Definition at line 56 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock(), Get(), and LockType_Write.
GetFunctions_NoLock()
virtual RIGVM_API const TChunkedArray< FRigVMFunction > & FRigVMRegistry_NoLock::GetFunctions_NoLock () const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetFunctions(), and FRigVMRegistry_RWLock::GetFunctions_NoLock().
GetHashForEnum_NoLock()
virtual RIGVM_API uint32 FRigVMRegistry_NoLock::GetHashForEnum_NoLock (const UEnum * InEnum, bool bCheckTypeIndex = true) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetHashForEnum(), and FRigVMRegistry_RWLock::GetHashForEnum_NoLock().
GetHashForProperty_NoLock()
virtual RIGVM_API uint32 FRigVMRegistry_NoLock::GetHashForProperty_NoLock (const FProperty * InProperty) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetHashForProperty(), and FRigVMRegistry_RWLock::GetHashForProperty_NoLock().
GetHashForScriptStruct_NoLock()
virtual RIGVM_API uint32 FRigVMRegistry_NoLock::GetHashForScriptStruct_NoLock (const UScriptStruct * InScriptStruct, bool bCheckTypeIndex = true) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetHashForScriptStruct(), and FRigVMRegistry_RWLock::GetHashForScriptStruct_NoLock().
GetHashForStruct_NoLock()
virtual RIGVM_API uint32 FRigVMRegistry_NoLock::GetHashForStruct_NoLock (const UStruct * InStruct) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetHashForStruct(), and FRigVMRegistry_RWLock::GetHashForStruct_NoLock().
GetHashForType_NoLock()
virtual RIGVM_API uint32 FRigVMRegistry_NoLock::GetHashForType_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetHashForType(), and FRigVMRegistry_RWLock::GetHashForType_NoLock().
GetMathTypes()
RIGVM_API const TArray< UScriptStruct * > & FRigVMRegistry_NoLock::GetMathTypes () static
References UE_API.
GetOrAddTemplateFromArguments_NoLock()
virtual RIGVM_API const FRigVMTemplate * FRigVMRegistry_NoLock::GetOrAddTemplateFromArguments_NoLock (const FName & InName, const TArray< FRigVMTemplateArgumentInfo > & InInfos, const FRigVMTemplateDelegates & InDelegates) virtual
Reimplemented in FRigVMRegistry_RWLock.
References FRigVMTemplate, InName, and UE_API.
Referenced by FRigVMRegistry_RWLock::GetOrAddTemplateFromArguments(), and FRigVMRegistry_RWLock::GetOrAddTemplateFromArguments_NoLock().
GetPredicatesForStruct_NoLock()
virtual RIGVM_API const TArray< FRigVMFunction > * FRigVMRegistry_NoLock::GetPredicatesForStruct_NoLock (const FName & InStructName) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetPredicatesForStruct(), and FRigVMRegistry_RWLock::GetPredicatesForStruct_NoLock().
GetReferencerName()
virtual RIGVM_API FString FRigVMRegistry_NoLock::GetReferencerName () const override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
References UE_API.
GetTemplates_NoLock()
virtual RIGVM_API const TChunkedArray< FRigVMTemplate > & FRigVMRegistry_NoLock::GetTemplates_NoLock () const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetTemplates(), and FRigVMRegistry_RWLock::GetTemplates_NoLock().
GetType_NoLock()
virtual RIGVM_API const FRigVMTemplateArgumentType & FRigVMRegistry_NoLock::GetType_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetType(), and FRigVMRegistry_RWLock::GetType_NoLock().
GetTypeIndex_NoLock() [1/6]
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr> TRigVMTypeIndex FRigVMRegistry_NoLock::GetTypeIndex_NoLock (bool bAsArray = false) const inline
Definition at line 145 of file RigVMRegistry.h.
References GetTypeIndex_NoLock(), and StaticEnum().
GetTypeIndex_NoLock() [2/6]
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr> TRigVMTypeIndex FRigVMRegistry_NoLock::GetTypeIndex_NoLock (bool bAsArray = false) const inline
Definition at line 160 of file RigVMRegistry.h.
References TBaseStructureBase< T, bHasStaticStruct >::Get(), and GetTypeIndex_NoLock().
GetTypeIndex_NoLock() [3/6]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> TRigVMTypeIndex FRigVMRegistry_NoLock::GetTypeIndex_NoLock (bool bAsArray = false) const inline
Definition at line 175 of file RigVMRegistry.h.
References GetTypeIndex_NoLock().
GetTypeIndex_NoLock() [4/6]
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr> TRigVMTypeIndex FRigVMRegistry_NoLock::GetTypeIndex_NoLock (bool bAsArray = false) const inline
Definition at line 190 of file RigVMRegistry.h.
References RigVMTypeUtils::AsObject, and GetTypeIndex_NoLock().
GetTypeIndex_NoLock() [5/6]
virtual TRigVMTypeIndex FRigVMRegistry_NoLock::GetTypeIndex_NoLock (const FName & InCPPType, UObject * InCPPTypeObject) const inline virtual
Reimplemented in FRigVMRegistry_RWLock.
Definition at line 135 of file RigVMRegistry.h.
References GetTypeIndex_NoLock().
GetTypeIndex_NoLock() [6/6]
virtual RIGVM_API TRigVMTypeIndex FRigVMRegistry_NoLock::GetTypeIndex_NoLock (const FRigVMTemplateArgumentType & InType) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetTypeIndex(), FRigVMRegistry_RWLock::GetTypeIndex(), GetTypeIndex_NoLock(), GetTypeIndex_NoLock(), FRigVMRegistry_RWLock::GetTypeIndex_NoLock(), and FRigVMRegistry_RWLock::GetTypeIndex_NoLock().
GetTypeIndexFromCPPType_NoLock()
virtual RIGVM_API TRigVMTypeIndex FRigVMRegistry_NoLock::GetTypeIndexFromCPPType_NoLock (const FString & InCPPType) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetTypeIndexFromCPPType(), and FRigVMRegistry_RWLock::GetTypeIndexFromCPPType_NoLock().
GetTypesForCategory_NoLock()
virtual RIGVM_API const TArray< TRigVMTypeIndex > & FRigVMRegistry_NoLock::GetTypesForCategory_NoLock (FRigVMTemplateArgument::ETypeCategory InCategory) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::GetTypesForCategory(), and FRigVMRegistry_RWLock::GetTypesForCategory_NoLock().
Initialize()
virtual void FRigVMRegistry_NoLock::Initialize (bool bLockRegistry) protected pure virtual
Implemented in FRigVMRegistry_RWLock.
Initialize_NoLock()
RIGVM_API void FRigVMRegistry_NoLock::Initialize_NoLock () protected
References UE_API.
IsAllowedType_NoLock() [1/4]
RIGVM_API bool FRigVMRegistry_NoLock::IsAllowedType_NoLock (const FProperty * InProperty) const protected
References UE_API.
IsAllowedType_NoLock() [2/4]
RIGVM_API bool FRigVMRegistry_NoLock::IsAllowedType_NoLock (const UClass * InClass) const protected
References UE_API.
IsAllowedType_NoLock() [3/4]
RIGVM_API bool FRigVMRegistry_NoLock::IsAllowedType_NoLock (const UEnum * InEnum) const protected
References UE_API.
IsAllowedType_NoLock() [4/4]
RIGVM_API bool FRigVMRegistry_NoLock::IsAllowedType_NoLock (const UStruct * InStruct) const protected
References UE_API.
IsArrayType_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::IsArrayType_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::IsArrayType(), and FRigVMRegistry_RWLock::IsArrayType_NoLock().
IsExecuteType_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::IsExecuteType_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::IsExecuteType(), and FRigVMRegistry_RWLock::IsExecuteType_NoLock().
IsTypeOfByName()
RIGVM_API bool FRigVMRegistry_NoLock::IsTypeOfByName (const UObject * InObject, const FName & InName) static protected
References InName, and UE_API.
IsWildCardType_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::IsWildCardType_NoLock (TRigVMTypeIndex InTypeIndex) const virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::IsWildCardType(), and FRigVMRegistry_RWLock::IsWildCardType_NoLock().
NeededFlags()
EObjectFlags FRigVMRegistry_NoLock::NeededFlags () inline static protected
Definition at line 358 of file RigVMRegistry.h.
References RF_Public.
NumTypes_NoLock()
virtual int32 FRigVMRegistry_NoLock::NumTypes_NoLock () const inline virtual
Reimplemented in FRigVMRegistry_RWLock.
Definition at line 204 of file RigVMRegistry.h.
References Types.
Referenced by FRigVMRegistry_RWLock::NumTypes(), and FRigVMRegistry_RWLock::NumTypes_NoLock().
OnAnimationAttributeTypesChanged_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::OnAnimationAttributeTypesChanged_NoLock (const UScriptStruct * InStruct, bool bIsAdded) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::OnAnimationAttributeTypesChanged_NoLock().
OnAssetRemoved_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::OnAssetRemoved_NoLock (const FAssetData & InAssetData) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::OnAssetRemoved_NoLock().
OnAssetRenamed_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::OnAssetRenamed_NoLock (const FAssetData & InAssetData, const FString & InOldObjectPath) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::OnAssetRenamed(), and FRigVMRegistry_RWLock::OnAssetRenamed_NoLock().
OnEngineInit()
RIGVM_API void FRigVMRegistry_NoLock::OnEngineInit () static
References UE_API.
OnPluginLoaded_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::OnPluginLoaded_NoLock (IPlugin & InPlugin) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::OnPluginLoaded_NoLock().
OnPluginUnloaded_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::OnPluginUnloaded_NoLock (IPlugin & InPlugin) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::OnPluginUnloaded_NoLock().
operator=()
FRigVMRegistry_NoLock & FRigVMRegistry_NoLock::operator= (const FRigVMRegistry_NoLock & InOther) protected delete
References FRigVMRegistry_NoLock().
PropagateTypeAddedToCategory_NoLock()
RIGVM_API void FRigVMRegistry_NoLock::PropagateTypeAddedToCategory_NoLock (const FRigVMTemplateArgument::ETypeCategory InCategory, const TRigVMTypeIndex InTypeIndex) protected
References UE_API.
RebuildRegistry_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::RebuildRegistry_NoLock () virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::RebuildRegistry(), and FRigVMRegistry_RWLock::RebuildRegistry_NoLock().
RefreshEngineTypes_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::RefreshEngineTypes_NoLock () virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::RefreshEngineTypes(), and FRigVMRegistry_RWLock::RefreshEngineTypes_NoLock().
RefreshEngineTypesIfRequired_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::RefreshEngineTypesIfRequired_NoLock () virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::RefreshEngineTypesIfRequired(), and FRigVMRegistry_RWLock::RefreshEngineTypesIfRequired_NoLock().
RefreshFunctionsAndDispatches_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::RefreshFunctionsAndDispatches_NoLock () virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::RefreshFunctionsAndDispatches(), and FRigVMRegistry_RWLock::RefreshFunctionsAndDispatches_NoLock().
Register_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::Register_NoLock (const TCHAR * InName, FRigVMFunctionPtr InFunctionPtr, UScriptStruct * InStruct = nullptr, const TArray< FRigVMFunctionArgument > & InArguments = TArray< FRigVMFunctionArgument >()) virtual
Reimplemented in FRigVMRegistry_RWLock.
References InName, and UE_API.
Referenced by FRigVMRegistry_RWLock::Register(), and FRigVMRegistry_RWLock::Register_NoLock().
RegisterFactory_NoLock()
virtual RIGVM_API const FRigVMDispatchFactory * FRigVMRegistry_NoLock::RegisterFactory_NoLock (UScriptStruct * InFactoryStruct) virtual
Reimplemented in FRigVMRegistry_RWLock.
References FRigVMDispatchFactory, and UE_API.
Referenced by FRigVMRegistry_RWLock::RegisterFactory(), and FRigVMRegistry_RWLock::RegisterFactory_NoLock().
RegisterObjectTypes_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::RegisterObjectTypes_NoLock (TConstArrayView< TPair< UClass *, ERegisterObjectOperation > > InClasses) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::RegisterObjectTypes(), and FRigVMRegistry_RWLock::RegisterObjectTypes_NoLock().
RegisterPredicate_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::RegisterPredicate_NoLock (UScriptStruct * InStruct, const TCHAR * InName, const TArray< FRigVMFunctionArgument > & InArguments) virtual
Reimplemented in FRigVMRegistry_RWLock.
References InName, and UE_API.
Referenced by FRigVMRegistry_RWLock::RegisterPredicate(), and FRigVMRegistry_RWLock::RegisterPredicate_NoLock().
RegisterStructTypes_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::RegisterStructTypes_NoLock (TConstArrayView< UScriptStruct * > InStructs) virtual
References UE_API.
Referenced by FRigVMRegistry_RWLock::RegisterStructTypes().
RegisterTypeInCategory_NoLock()
RIGVM_API void FRigVMRegistry_NoLock::RegisterTypeInCategory_NoLock (const FRigVMTemplateArgument::ETypeCategory InCategory, const TRigVMTypeIndex InTypeIndex) protected
References UE_API.
RemoveType_NoLock()
virtual RIGVM_API bool FRigVMRegistry_NoLock::RemoveType_NoLock (const FSoftObjectPath & InObjectPath, const UClass * InObjectClass) virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::RemoveType(), and FRigVMRegistry_RWLock::RemoveType_NoLock().
RemoveTypeInCategory_NoLock()
RIGVM_API void FRigVMRegistry_NoLock::RemoveTypeInCategory_NoLock (FRigVMTemplateArgument::ETypeCategory InCategory, TRigVMTypeIndex InTypeIndex) protected
References UE_API.
Reset_NoLock()
virtual RIGVM_API void FRigVMRegistry_NoLock::Reset_NoLock () virtual
Reimplemented in FRigVMRegistry_RWLock.
References UE_API.
Referenced by FRigVMRegistry_RWLock::Reset(), and FRigVMRegistry_RWLock::Reset_NoLock().
Friends And Related Symbol Documentation
FRigVMDispatchFactory
friend struct FRigVMDispatchFactory friend
Definition at line 431 of file RigVMRegistry.h.
References FRigVMDispatchFactory.
Referenced by FindDispatchFactory_NoLock(), FindOrAddDispatchFactory_NoLock(), FindOrAddDispatchFactory_NoLock(), FRigVMDispatchFactory, and RegisterFactory_NoLock().
FRigVMStruct
friend struct FRigVMStruct friend
Definition at line 428 of file RigVMRegistry.h.
References FRigVMStruct.
Referenced by FRigVMStruct.
FRigVMTemplate
friend struct FRigVMTemplate friend
Definition at line 429 of file RigVMRegistry.h.
References FRigVMTemplate.
Referenced by AddTemplateFromArguments_NoLock(), FindTemplate_NoLock(), FRigVMTemplate, and GetOrAddTemplateFromArguments_NoLock().
FRigVMTemplateArgument
friend struct FRigVMTemplateArgument friend
Definition at line 430 of file RigVMRegistry.h.
References FRigVMTemplateArgument.
Referenced by FRigVMTemplateArgument.
Field Documentation
AllowedClasses
TSet<TObjectPtr<const UClass> > FRigVMRegistry_NoLock::AllowedClasses protected
Definition at line 413 of file RigVMRegistry.h.
AllowedStructs
TSet<TObjectPtr<const UScriptStruct> > FRigVMRegistry_NoLock::AllowedStructs protected
Definition at line 416 of file RigVMRegistry.h.
bAvoidTypePropagation
bool FRigVMRegistry_NoLock::bAvoidTypePropagation protected
Definition at line 420 of file RigVMRegistry.h.
bEverRefreshedDispatchFactoriesAfterEngineInit
bool FRigVMRegistry_NoLock::bEverRefreshedDispatchFactoriesAfterEngineInit protected
Definition at line 426 of file RigVMRegistry.h.
bEverRefreshedEngineTypes
bool FRigVMRegistry_NoLock::bEverRefreshedEngineTypes protected
Definition at line 423 of file RigVMRegistry.h.
DeprecatedTemplateNotationToIndex
TMap<FName, int32> FRigVMRegistry_NoLock::DeprecatedTemplateNotationToIndex protected
Definition at line 400 of file RigVMRegistry.h.
DeprecatedTemplates
TChunkedArray<FRigVMTemplate> FRigVMRegistry_NoLock::DeprecatedTemplates protected
Definition at line 385 of file RigVMRegistry.h.
Factories
TArray<FRigVMDispatchFactory*> FRigVMRegistry_NoLock::Factories protected
Definition at line 388 of file RigVMRegistry.h.
FunctionNameToIndex
TMap<FName, int32> FRigVMRegistry_NoLock::FunctionNameToIndex protected
Definition at line 391 of file RigVMRegistry.h.
Functions
TChunkedArray<FRigVMFunction> FRigVMRegistry_NoLock::Functions protected
Definition at line 379 of file RigVMRegistry.h.
StructNameToPredicates
TMap<FName, TArray<FRigVMFunction> > FRigVMRegistry_NoLock::StructNameToPredicates protected
Definition at line 394 of file RigVMRegistry.h.
TemplateNameMetaName
const FLazyName FRigVMRegistry_NoLock::TemplateNameMetaName = FLazyName(TEXT("TemplateName")) inline static
Definition at line 316 of file RigVMRegistry.h.
TemplateNotationToIndex
TMap<FName, int32> FRigVMRegistry_NoLock::TemplateNotationToIndex protected
Definition at line 397 of file RigVMRegistry.h.
Templates
TChunkedArray<FRigVMTemplate> FRigVMRegistry_NoLock::Templates protected
Definition at line 382 of file RigVMRegistry.h.
TemplatesPerCategory
TMap<FRigVMTemplateArgument::ETypeCategory, TArray<int32> > FRigVMRegistry_NoLock::TemplatesPerCategory protected
Definition at line 406 of file RigVMRegistry.h.
Types
TArray<FTypeInfo> FRigVMRegistry_NoLock::Types protected
Definition at line 374 of file RigVMRegistry.h.
Referenced by NumTypes_NoLock().
TypesPerCategory
TMap<FRigVMTemplateArgument::ETypeCategory, TArray<TRigVMTypeIndex> > FRigVMRegistry_NoLock::TypesPerCategory protected
Definition at line 403 of file RigVMRegistry.h.
TypeToIndex
TMap<FRigVMTemplateArgumentType, TRigVMTypeIndex> FRigVMRegistry_NoLock::TypeToIndex protected
Definition at line 375 of file RigVMRegistry.h.
UserDefinedTypeToIndex
TMap<FSoftObjectPath, TRigVMTypeIndex> FRigVMRegistry_NoLock::UserDefinedTypeToIndex protected
Definition at line 410 of file RigVMRegistry.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMRegistry.h