Unreal Engine 5.6 C++ API: UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType > Struct Template Reference
UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType > Struct Template Reference
#include "MovieSceneEntityFactoryTemplates.h"
Public Member Functions
TChildEntityInitializer (TComponentTypeID< ParentComponentType > InParentComponent, TComponentTypeID< ChildComponentType > InChildComponent)
TComponentTypeID< ChildComponentType > GetChildComponent () const
TComponentLock< TWrite< ChildComponentType > > GetChildComponents (const FEntityAllocation *Allocation) const
TComponentTypeID< ParentComponentType > GetParentComponent () const
TComponentLock< TRead< ParentComponentType > > GetParentComponents (const FEntityAllocation *Allocation) const
Public Member Functions inherited from UE::MovieScene::FChildEntityInitializer
virtual ~FChildEntityInitializer ()
FComponentTypeID GetChildComponent () const
FComponentTypeID GetParentComponent () const
virtual bool IsRelevant (const FComponentMask &InParentType, const FComponentMask &InChildType) const
virtual void Run (const FEntityRange &, const FEntityAllocation *, TArrayView< const int32 >)=0
Additional Inherited Members
Protected Member Functions inherited from UE::MovieScene::FChildEntityInitializer
FChildEntityInitializer (FComponentTypeID InParentComponent, FComponentTypeID InChildComponent)
Protected Attributes inherited from UE::MovieScene::FChildEntityInitializer
FComponentTypeID ChildComponent
FComponentTypeID ParentComponent
Detailed Description
template<typename ParentComponentType, typename ChildComponentType>
struct UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >
Definition at line 32 of file MovieSceneEntityFactoryTemplates.h.
Constructor & Destructor Documentation
TChildEntityInitializer()
template<typename ParentComponentType, typename ChildComponentType> UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::TChildEntityInitializer (TComponentTypeID< ParentComponentType > InParentComponent, TComponentTypeID< ChildComponentType > InChildComponent) inline explicit
Definition at line 34 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FChildEntityInitializer::FChildEntityInitializer().
Referenced by UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType >::TStaticChildEntityInitializer().
Member Function Documentation
GetChildComponent()
template<typename ParentComponentType, typename ChildComponentType> TComponentTypeID< ChildComponentType > UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::GetChildComponent () const inline
Definition at line 43 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FChildEntityInitializer::ChildComponent.
Referenced by GetChildComponents(), and UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType >::Run().
GetChildComponents()
template<typename ParentComponentType, typename ChildComponentType> TComponentLock< TWrite< ChildComponentType > > UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::GetChildComponents (const FEntityAllocation * Allocation) const inline
Definition at line 53 of file MovieSceneEntityFactoryTemplates.h.
References GetChildComponent().
GetParentComponent()
template<typename ParentComponentType, typename ChildComponentType> TComponentTypeID< ParentComponentType > UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::GetParentComponent () const inline
Definition at line 38 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FChildEntityInitializer::ParentComponent.
Referenced by GetParentComponents(), and UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType >::Run().
GetParentComponents()
template<typename ParentComponentType, typename ChildComponentType> TComponentLock< TRead< ParentComponentType > > UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::GetParentComponents (const FEntityAllocation * Allocation) const inline
Definition at line 48 of file MovieSceneEntityFactoryTemplates.h.
References GetParentComponent().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityFactoryTemplates.h