Unreal Engine 5.6 C++ API: NEnumRangePrivate::TEnumContiguousIterator< EnumType > Struct Template Reference
NEnumRangePrivate::TEnumContiguousIterator< EnumType > Struct Template Reference
#include "EnumRange.h"
Public Types
using IntType = std::underlying_type_t<EnumType>
Public Member Functions
FORCEINLINE TEnumContiguousIterator (IntType InValue)
FORCEINLINE EnumType operator* () const
FORCEINLINE TEnumContiguousIterator & operator++ ()
Private Attributes
IntType Value
Friends
FORCEINLINE friend bool operator!= (const TEnumContiguousIterator &Lhs, const TEnumContiguousIterator &Rhs)
Detailed Description
template<typename EnumType>
struct NEnumRangePrivate::TEnumContiguousIterator< EnumType >
Definition at line 103 of file EnumRange.h.
Member Typedef Documentation
IntType
template<typename EnumType> using NEnumRangePrivate::TEnumContiguousIterator< EnumType >::IntType = std::underlying_type_t<EnumType>
Definition at line 105 of file EnumRange.h.
Constructor & Destructor Documentation
TEnumContiguousIterator()
template<typename EnumType> FORCEINLINE NEnumRangePrivate::TEnumContiguousIterator< EnumType >::TEnumContiguousIterator (IntType InValue) inline explicit
Definition at line 107 of file EnumRange.h.
References FORCEINLINE, and Value.
Referenced by operator!=, and operator++().
Member Function Documentation
operator*()
template<typename EnumType> FORCEINLINE EnumType NEnumRangePrivate::TEnumContiguousIterator< EnumType >::operator* () const inline
Definition at line 118 of file EnumRange.h.
References FORCEINLINE, and Value.
operator++()
template<typename EnumType> FORCEINLINE TEnumContiguousIterator & NEnumRangePrivate::TEnumContiguousIterator< EnumType >::operator++ () inline
Definition at line 112 of file EnumRange.h.
References TEnumContiguousIterator(), FORCEINLINE, and Value.
Friends And Related Symbol Documentation
operator!=
template<typename EnumType> FORCEINLINE friend bool operator!= (const TEnumContiguousIterator< EnumType > & Lhs, const TEnumContiguousIterator< EnumType > & Rhs) friend
Definition at line 126 of file EnumRange.h.
References TEnumContiguousIterator(), FORCEINLINE, and Value.
Field Documentation
Value
template<typename EnumType> IntType NEnumRangePrivate::TEnumContiguousIterator< EnumType >::Value private
Definition at line 124 of file EnumRange.h.
Referenced by TEnumContiguousIterator(), operator!=, operator*(), and operator++().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/EnumRange.h