Unreal Engine 5.6 C++ API: UE::AnimNext::FNodeID Struct Reference
UE::AnimNext::FNodeID Struct Reference final
Node ID.
#include "NodeID.h"
Public Member Functions
constexpr FNodeID () noexcept
constexpr FNodeID GetNextID () const noexcept
constexpr uint32 GetNodeIndex () const noexcept
constexpr bool IsValid () const noexcept
constexpr bool operator!= (const FNodeID RHS) const noexcept
constexpr bool operator== (const FNodeID RHS) const noexcept
Static Public Member Functions
static constexpr FNodeID GetFirstID () noexcept
Private Member Functions
constexpr FNodeID (uint16 InID) noexcept
constexpr uint32 GetRawValue () const
Static Private Member Functions
static constexpr FNodeID FromRawValue (uint32 InID) noexcept
Private Attributes
uint16 ID
Static Private Attributes
static constexpr uint16 INVALID_NODE_ID = 0
Friends
struct FNodeHandle
FArchive & operator<< (FArchive &Ar, FNodeID &Value)
Detailed Description
Node ID.
A node ID fits on 16 bits and is used to encode a node index. The zero ID is reserved as an invalid value, this means that the node index is 1-based.
Node IDs are assigned during compilation of an AnimNext graph to each node. The trait reader is then used to convert them into a shared offset within the graph.
See also
FTraitReader
Definition at line 23 of file NodeID.h.
Constructor & Destructor Documentation
FNodeID() [1/2]
UE::AnimNext::FNodeID::FNodeID () inline constexpr noexcept
Definition at line 26 of file NodeID.h.
References ID, and INVALID_NODE_ID.
Referenced by FromRawValue(), GetFirstID(), GetNextID(), operator!=(), operator<<, and operator==().
FNodeID() [2/2]
UE::AnimNext::FNodeID::FNodeID (uint16 InID) inline explicit constexpr private noexcept
Definition at line 57 of file NodeID.h.
Member Function Documentation
FromRawValue()
constexpr FNodeID UE::AnimNext::FNodeID::FromRawValue (uint32 InID) inline static constexpr private noexcept
Definition at line 63 of file NodeID.h.
References FNodeID().
Referenced by UE::AnimNext::FNodeHandle::GetNodeID().
GetFirstID()
constexpr FNodeID UE::AnimNext::FNodeID::GetFirstID () inline static constexpr noexcept
Definition at line 36 of file NodeID.h.
References FNodeID().
GetNextID()
FNodeID UE::AnimNext::FNodeID::GetNextID () const inline constexpr noexcept
Definition at line 42 of file NodeID.h.
References FNodeID(), ID, and IsValid().
GetNodeIndex()
uint32 UE::AnimNext::FNodeID::GetNodeIndex () const inline constexpr noexcept
Definition at line 33 of file NodeID.h.
References ID.
GetRawValue()
uint32 UE::AnimNext::FNodeID::GetRawValue () const inline constexpr private
Definition at line 60 of file NodeID.h.
References ID.
IsValid()
bool UE::AnimNext::FNodeID::IsValid () const inline constexpr noexcept
Definition at line 29 of file NodeID.h.
References ID, and INVALID_NODE_ID.
Referenced by GetNextID().
operator!=()
bool UE::AnimNext::FNodeID::operator!= (const FNodeID RHS) const inline constexpr noexcept
Definition at line 46 of file NodeID.h.
References FNodeID(), and ID.
operator==()
bool UE::AnimNext::FNodeID::operator== (const FNodeID RHS) const inline constexpr noexcept
Definition at line 45 of file NodeID.h.
References FNodeID(), and ID.
Friends And Related Symbol Documentation
FNodeHandle
friend struct FNodeHandle friend
Definition at line 69 of file NodeID.h.
References FNodeHandle.
Referenced by FNodeHandle.
operator<<
FArchive & operator<< (FArchive & Ar, FNodeID & Value) friend
Definition at line 49 of file NodeID.h.
References FNodeID(), Ar, and Value.
Field Documentation
ID
uint16 UE::AnimNext::FNodeID::ID private
Definition at line 67 of file NodeID.h.
Referenced by FNodeID(), GetNextID(), GetNodeIndex(), GetRawValue(), IsValid(), operator!=(), and operator==().
INVALID_NODE_ID
uint16 UE::AnimNext::FNodeID::INVALID_NODE_ID = 0 static constexpr private
Definition at line 65 of file NodeID.h.
Referenced by FNodeID(), and IsValid().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitCore/NodeID.h