Unreal Engine 5.6 C++ API: TWeakObjectPtr< T, TWeakObjectPtrBase > Struct Template Reference
TWeakObjectPtr< T, TWeakObjectPtrBase > Struct Template Reference
TWeakObjectPtr is the templated version of the generic FWeakObjectPtr.
#include "WeakObjectPtrTemplates.h"
Public Types
using ElementType = T
Public Member Functions
TWeakObjectPtr ()=default
TWeakObjectPtr (const TWeakObjectPtr &)=default
template<typename OtherT UE_REQUIRES>
FORCEINLINE TWeakObjectPtr (const TWeakObjectPtr< OtherT, TWeakObjectPtrBase > &Other)
Construct from another weak pointer of another type, intended for derived-to-base conversions.
FORCEINLINE TWeakObjectPtr (TYPE_OF_NULLPTR)
Construct from a null pointer.
template<typename U UE_REQUIRES>
FORCEINLINE TWeakObjectPtr (U Object)
Construct from an object pointer.
~TWeakObjectPtr ()=default
FORCEINLINE T * Get () const
Dereference the weak pointer.
FORCEINLINE T * Get (bool bEvenIfPendingKill) const
Dereference the weak pointer.
FORCEINLINE T * GetEvenIfUnreachable () const
Deferences the weak pointer even if its marked RF_Unreachable.
FORCEINLINE uint32 GetWeakPtrTypeHash () const
Hash function.
FORCEINLINE bool HasSameIndexAndSerialNumber (const TWeakObjectPtr &Other) const
Returns true if two weak pointers were originally set to the same object, even if they are now stale.
template<typename OtherT UE_REQUIRES>
FORCEINLINE bool HasSameIndexAndSerialNumber (const TWeakObjectPtr< OtherT, TWeakObjectPtrBase > &Other) const
Returns true if two weak pointers were originally set to the same object, even if they are now stale.
FORCEINLINE bool IsExplicitlyNull () const
Returns true if this pointer was explicitly assigned to null, was reset, or was never initialized.
FORCEINLINE bool IsRemote () const
FORCEINLINE bool IsStale (bool bIncludingIfPendingKill=true, bool bThreadsafeTest=false) const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
FORCEINLINE bool IsValid (bool bEvenIfPendingKill, bool bThreadsafeTest=false) const
Test if this points to a live UObject.
operator bool () const =delete
operator TWeakObjectPtrBase () const
Cast to the underlying generic FWeakObjectPtr type.
template<typename RhsT, typename = decltype((T*)nullptr != (RhsT*)nullptr)>
FORCEINLINE bool operator!= (const RhsT *Rhs) const
template<typename RhsT, typename = decltype((T*)nullptr != (RhsT*)nullptr)>
FORCEINLINE bool operator!= (const TWeakObjectPtr< RhsT, TWeakObjectPtrBase > &Rhs) const
Compare weak pointers for inequality.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
FORCEINLINE T & operator* () const
Dereference the weak pointer.
FORCEINLINE T * operator-> () const
Dereference the weak pointer.
TWeakObjectPtr & operator= (const TWeakObjectPtr &)=default
template<typename OtherT UE_REQUIRES>
FORCEINLINE TWeakObjectPtr & operator= (const TWeakObjectPtr< OtherT, TWeakObjectPtrBase > &Other)
Assign from another weak pointer, intended for derived-to-base conversions.
template<typename U UE_REQUIRES>
FORCEINLINE TWeakObjectPtr & operator= (U *Object)
Copy from an object pointer.
template<typename RhsT, typename = decltype((T*)nullptr == (RhsT*)nullptr)>
FORCENOINLINE bool operator== (const RhsT *Rhs) const
template<typename RhsT, typename = decltype((T*)nullptr == (RhsT*)nullptr)>
FORCENOINLINE bool operator== (const TWeakObjectPtr< RhsT, TWeakObjectPtrBase > &Rhs) const
Compare weak pointers for equality.
FORCENOINLINE bool operator== (TYPE_OF_NULLPTR) const
FORCEINLINE TStrongObjectPtr< T > Pin () const
Pin the weak pointer as a strong ptr.
FORCEINLINE TStrongObjectPtr< T > Pin (bool bEvenIfPendingKill) const
Pin the weak pointer and get a strongptr.
FORCEINLINE void Reset ()
Reset the weak pointer back to the null state.
FORCEINLINE void Serialize (FArchive &Ar)
Weak object pointer serialization, this forwards to FArchive::operator<<(struct FWeakObjectPtr&) or an override.
FORCEINLINE TStrongObjectPtr< T > TryPin (bool &bOutPinValid) const
Pin the weak pointer as a strong ptr.
FORCEINLINE TStrongObjectPtr< T > TryPin (bool &bOutPinValid, bool bEvenIfPendingKill) const
Pin the weak pointer and get a strongptr.
Private Member Functions
FORCEINLINE FUObjectItem * Internal_GetObjectItem () const
Private Attributes
TWeakObjectPtrBase WeakPtr
Friends
template<class, class>
struct TWeakObjectPtr
struct FFieldPath
Detailed Description
template<class T, class TWeakObjectPtrBase>
struct TWeakObjectPtr< T, TWeakObjectPtrBase >
TWeakObjectPtr is the templated version of the generic FWeakObjectPtr.
Definition at line 23 of file WeakObjectPtrTemplates.h.
Member Typedef Documentation
ElementType
template<class T, class TWeakObjectPtrBase> using TWeakObjectPtr< T, TWeakObjectPtrBase >::ElementType = T
Definition at line 37 of file WeakObjectPtrTemplates.h.
Constructor & Destructor Documentation
TWeakObjectPtr() [1/5]
template<class T, class TWeakObjectPtrBase> TWeakObjectPtr< T, TWeakObjectPtrBase >::TWeakObjectPtr () nodiscard default
TWeakObjectPtr() [2/5]
template<class T, class TWeakObjectPtrBase> TWeakObjectPtr< T, TWeakObjectPtrBase >::TWeakObjectPtr (const TWeakObjectPtr< T, TWeakObjectPtrBase > &) nodiscard default
~TWeakObjectPtr()
template<class T, class TWeakObjectPtrBase> TWeakObjectPtr< T, TWeakObjectPtrBase >::~TWeakObjectPtr () default
TWeakObjectPtr() [3/5]
template<class T, class TWeakObjectPtrBase> FORCEINLINE TWeakObjectPtr< T, TWeakObjectPtrBase >::TWeakObjectPtr (TYPE_OF_NULLPTR) inline nodiscard
Construct from a null pointer.
Definition at line 47 of file WeakObjectPtrTemplates.h.
TWeakObjectPtr() [4/5]
template<class T, class TWeakObjectPtrBase> template<typename U UE_REQUIRES> FORCEINLINE TWeakObjectPtr< T, TWeakObjectPtrBase >::TWeakObjectPtr (U Object) inline nodiscard
Construct from an object pointer.
Parameters
Object object to create a weak pointer to
Definition at line 60 of file WeakObjectPtrTemplates.h.
TWeakObjectPtr() [5/5]
template<class T, class TWeakObjectPtrBase> template<typename OtherT UE_REQUIRES> FORCEINLINE TWeakObjectPtr< T, TWeakObjectPtrBase >::TWeakObjectPtr (const TWeakObjectPtr< OtherT, TWeakObjectPtrBase > & Other) inline nodiscard
Construct from another weak pointer of another type, intended for derived-to-base conversions.
Parameters
Other weak pointer to copy from
Definition at line 76 of file WeakObjectPtrTemplates.h.
Member Function Documentation
Get() [1/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE T * TWeakObjectPtr< T, TWeakObjectPtrBase >::Get () const inline nodiscard
Dereference the weak pointer.
This is an optimized version implying bEvenIfPendingKill=false.
Definition at line 139 of file WeakObjectPtrTemplates.h.
Referenced by TWeakObjectPtr< const T >::operator*(), and TWeakObjectPtr< const T >::operator->().
Get() [2/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE T * TWeakObjectPtr< T, TWeakObjectPtrBase >::Get (bool bEvenIfPendingKill) const inline nodiscard
Dereference the weak pointer.
Parameters
bEvenIfPendingKill if this is true, pendingkill objects are considered valid
Returns
nullptr if this object is gone or the weak pointer is explicitly null, otherwise a valid uobject pointer
Definition at line 131 of file WeakObjectPtrTemplates.h.
Referenced by FTrackInstancePropertyBindings::CallFunction(), Cast(), CastChecked(), CastChecked(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), TListTypeTraits< TWeakObjectPtr< T > >::DebugDump(), ExactCast(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::operator!=(), FTrackInstancePropertyBindings::SetCurrentValue(), USTRUCT(), and UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::VisitInterrogationAllocation().
GetEvenIfUnreachable()
template<class T, class TWeakObjectPtrBase> FORCEINLINE T * TWeakObjectPtr< T, TWeakObjectPtrBase >::GetEvenIfUnreachable () const inline nodiscard
Deferences the weak pointer even if its marked RF_Unreachable.
This is needed to resolve weak pointers during GC (such as ::AddReferenceObjects)
Definition at line 188 of file WeakObjectPtrTemplates.h.
GetWeakPtrTypeHash()
template<class T, class TWeakObjectPtrBase> FORCEINLINE uint32 TWeakObjectPtr< T, TWeakObjectPtrBase >::GetWeakPtrTypeHash () const inline nodiscard
Hash function.
Definition at line 311 of file WeakObjectPtrTemplates.h.
HasSameIndexAndSerialNumber() [1/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::HasSameIndexAndSerialNumber (const TWeakObjectPtr< T, TWeakObjectPtrBase > & Other) const inline nodiscard
Returns true if two weak pointers were originally set to the same object, even if they are now stale.
Parameters
Other weak pointer to compare to
Definition at line 272 of file WeakObjectPtrTemplates.h.
HasSameIndexAndSerialNumber() [2/2]
template<class T, class TWeakObjectPtrBase> template<typename OtherT UE_REQUIRES> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::HasSameIndexAndSerialNumber (const TWeakObjectPtr< OtherT, TWeakObjectPtrBase > & Other) const inline nodiscard
Returns true if two weak pointers were originally set to the same object, even if they are now stale.
Parameters
Other weak pointer to compare to
Definition at line 285 of file WeakObjectPtrTemplates.h.
Internal_GetObjectItem()
template<class T, class TWeakObjectPtrBase> FORCEINLINE FUObjectItem * TWeakObjectPtr< T, TWeakObjectPtrBase >::Internal_GetObjectItem () const inline private
Definition at line 363 of file WeakObjectPtrTemplates.h.
IsExplicitlyNull()
template<class T, class TWeakObjectPtrBase> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::IsExplicitlyNull () const inline nodiscard
Returns true if this pointer was explicitly assigned to null, was reset, or was never initialized.
If this returns true, IsValid() and IsStale() will both return false.
Definition at line 263 of file WeakObjectPtrTemplates.h.
IsRemote()
template<class T, class TWeakObjectPtrBase> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::IsRemote () const inline nodiscard
Definition at line 297 of file WeakObjectPtrTemplates.h.
IsStale()
template<class T, class TWeakObjectPtrBase> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::IsStale (bool bIncludingIfPendingKill = true, bool bThreadsafeTest = false) const inline nodiscard
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
Parameters
bIncludingIfPendingKill if this is true, pendingkill objects are considered stale
bThreadsafeTest set it to true when testing outside of Game Thread. Results in false if WeakObjPtr point to an existing object (no flags checked)
Returns
true if this used to point at a real object but no longer does.
Definition at line 254 of file WeakObjectPtrTemplates.h.
IsValid() [1/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::IsValid () const inline nodiscard
Test if this points to a live UObject.
This is an optimized version implying bEvenIfPendingKill=false, bThreadsafeTest=false. This should be done only when needed as excess resolution of the underlying pointer can cause performance issues. Note that IsValid can not be used on another thread as it will incorrectly return false during the mark phase of the GC due to the Unreachable flag being set. (see bThreadsafeTest above)
Returns
true if Get() would return a valid non-null pointer
Definition at line 243 of file WeakObjectPtrTemplates.h.
Referenced by TWeakObjectPtr< const T >::operator==().
IsValid() [2/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::IsValid (bool bEvenIfPendingKill, bool bThreadsafeTest = false) const inline nodiscard
Test if this points to a live UObject.
This should be done only when needed as excess resolution of the underlying pointer can cause performance issues.
Parameters
bEvenIfPendingKill if this is true, pendingkill objects are considered valid
bThreadsafeTest if true then function will just give you information whether referenced UObject is gone forever (return false) or if it is still there (return true, no object flags checked). This is required as without it IsValid can return false during the mark phase of the GC due to the presence of the Unreachable flag.
Returns
true if Get() would return a valid non-null pointer
Definition at line 231 of file WeakObjectPtrTemplates.h.
Referenced by FGuardSkipDirtyBlueprintStatus::FGuardSkipDirtyBlueprintStatus(), IDetailLayoutBuilder::GetObjectsOfTypeBeingCustomized(), IDetailLayoutBuilder::GetSelectedObjectsOfType(), UE::Anim::AttributeTypes::GetTypeOperator(), TListTypeTraits< TWeakObjectPtr< T > >::IsPtrValid(), and USTRUCT().
operator bool()
template<class T, class TWeakObjectPtrBase> TWeakObjectPtr< T, TWeakObjectPtrBase >::operator bool () const explicit delete
operator TWeakObjectPtrBase()
template<class T, class TWeakObjectPtrBase> TWeakObjectPtr< T, TWeakObjectPtrBase >::operator TWeakObjectPtrBase () const inline explicit
Cast to the underlying generic FWeakObjectPtr type.
Definition at line 215 of file WeakObjectPtrTemplates.h.
operator!=() [1/3]
template<class T, class TWeakObjectPtrBase> template<typename RhsT, typename = decltype((T*)nullptr != (RhsT*)nullptr)> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::operator!= (const RhsT * Rhs) const inline nodiscard
Definition at line 351 of file WeakObjectPtrTemplates.h.
operator!=() [2/3]
template<class T, class TWeakObjectPtrBase> template<typename RhsT, typename = decltype((T*)nullptr != (RhsT*)nullptr)> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::operator!= (const TWeakObjectPtr< RhsT, TWeakObjectPtrBase > & Rhs) const inline nodiscard
Compare weak pointers for inequality.
Parameters
Other weak pointer to compare to
Definition at line 345 of file WeakObjectPtrTemplates.h.
operator!=() [3/3]
template<class T, class TWeakObjectPtrBase> FORCEINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::operator!= (TYPE_OF_NULLPTR) const inline nodiscard
Definition at line 356 of file WeakObjectPtrTemplates.h.
operator*()
template<class T, class TWeakObjectPtrBase> FORCEINLINE T & TWeakObjectPtr< T, TWeakObjectPtrBase >::operator* () const inline nodiscard
Dereference the weak pointer.
Definition at line 196 of file WeakObjectPtrTemplates.h.
operator->()
template<class T, class TWeakObjectPtrBase> FORCEINLINE T * TWeakObjectPtr< T, TWeakObjectPtrBase >::operator-> () const inline nodiscard
Dereference the weak pointer.
Definition at line 204 of file WeakObjectPtrTemplates.h.
operator=() [1/3]
template<class T, class TWeakObjectPtrBase> TWeakObjectPtr & TWeakObjectPtr< T, TWeakObjectPtrBase >::operator= (const TWeakObjectPtr< T, TWeakObjectPtrBase > &) default
operator=() [2/3]
template<class T, class TWeakObjectPtrBase> template<typename OtherT UE_REQUIRES> FORCEINLINE TWeakObjectPtr & TWeakObjectPtr< T, TWeakObjectPtrBase >::operator= (const TWeakObjectPtr< OtherT, TWeakObjectPtrBase > & Other) inline
Assign from another weak pointer, intended for derived-to-base conversions.
Parameters
Other weak pointer to copy from
Definition at line 119 of file WeakObjectPtrTemplates.h.
operator=() [3/3]
template<class T, class TWeakObjectPtrBase> template<typename U UE_REQUIRES> FORCEINLINE TWeakObjectPtr & TWeakObjectPtr< T, TWeakObjectPtrBase >::operator= (U * Object) inline
Copy from an object pointer.
Parameters
Object object to create a weak pointer to
Definition at line 104 of file WeakObjectPtrTemplates.h.
operator==() [1/3]
template<class T, class TWeakObjectPtrBase> template<typename RhsT, typename = decltype((T*)nullptr == (RhsT*)nullptr)> FORCENOINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::operator== (const RhsT * Rhs) const inline nodiscard
Definition at line 328 of file WeakObjectPtrTemplates.h.
operator==() [2/3]
template<class T, class TWeakObjectPtrBase> template<typename RhsT, typename = decltype((T*)nullptr == (RhsT*)nullptr)> FORCENOINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::operator== (const TWeakObjectPtr< RhsT, TWeakObjectPtrBase > & Rhs) const inline nodiscard
Compare weak pointers for equality.
If both pointers would return nullptr from Get() they count as equal even if they were not initialized to the same object.
Parameters
Other weak pointer to compare to
Definition at line 322 of file WeakObjectPtrTemplates.h.
operator==() [3/3]
template<class T, class TWeakObjectPtrBase> FORCENOINLINE bool TWeakObjectPtr< T, TWeakObjectPtrBase >::operator== (TYPE_OF_NULLPTR) const inline nodiscard
Definition at line 334 of file WeakObjectPtrTemplates.h.
Pin() [1/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE TStrongObjectPtr< T > TWeakObjectPtr< T, TWeakObjectPtrBase >::Pin () const inline nodiscard
Pin the weak pointer as a strong ptr.
This is an optimized version implying bEvenIfPendingKill=false.
Definition at line 159 of file WeakObjectPtrTemplates.h.
Pin() [2/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE TStrongObjectPtr< T > TWeakObjectPtr< T, TWeakObjectPtrBase >::Pin (bool bEvenIfPendingKill) const inline nodiscard
Pin the weak pointer and get a strongptr.
Parameters
bEvenIfPendingKill if this is true, pendingkill objects are considered valid
Returns
nullptr if this object is gone or the weak pointer is explicitly null, otherwise a valid uobject pointer
Definition at line 149 of file WeakObjectPtrTemplates.h.
Referenced by IAnimationEditorsAssetFamilyInterface::GetAssetOfType().
Reset()
template<class T, class TWeakObjectPtrBase> FORCEINLINE void TWeakObjectPtr< T, TWeakObjectPtrBase >::Reset () inline
Reset the weak pointer back to the null state.
Definition at line 91 of file WeakObjectPtrTemplates.h.
Referenced by TListTypeTraits< TWeakObjectPtr< T > >::ResetPtr(), and USTRUCT().
Serialize()
template<class T, class TWeakObjectPtrBase> FORCEINLINE void TWeakObjectPtr< T, TWeakObjectPtrBase >::Serialize (FArchive & Ar) inline
Weak object pointer serialization, this forwards to FArchive::operator<<(struct FWeakObjectPtr&) or an override.
Definition at line 305 of file WeakObjectPtrTemplates.h.
TryPin() [1/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE TStrongObjectPtr< T > TWeakObjectPtr< T, TWeakObjectPtrBase >::TryPin (bool & bOutPinValid) const inline nodiscard
Pin the weak pointer as a strong ptr.
This is an optimized version implying bEvenIfPendingKill=false.
Definition at line 182 of file WeakObjectPtrTemplates.h.
TryPin() [2/2]
template<class T, class TWeakObjectPtrBase> FORCEINLINE TStrongObjectPtr< T > TWeakObjectPtr< T, TWeakObjectPtrBase >::TryPin (bool & bOutPinValid, bool bEvenIfPendingKill) const inline nodiscard
Pin the weak pointer and get a strongptr.
Parameters
bOutPinValid true if garbage collection was not in progress, and OutResult was successfully captured, false if garbage collection was in progress and OutResult was not captured
bEvenIfPendingKill if this is true, pendingkill objects are considered valid
Returns
nullptr if this object is gone or the weak pointer is explicitly null, otherwise a valid uobject pointer
Definition at line 172 of file WeakObjectPtrTemplates.h.
Referenced by TWeakObjectPtr< const T >::TryPin().
Friends And Related Symbol Documentation
TWeakObjectPtr
template<class T, class TWeakObjectPtrBase> template<class, class> friend struct TWeakObjectPtr friend
Definition at line 28 of file WeakObjectPtrTemplates.h.
FFieldPath
template<class T, class TWeakObjectPtrBase> FFieldPath friend
Definition at line 25 of file WeakObjectPtrTemplates.h.
Field Documentation
WeakPtr
template<class T, class TWeakObjectPtrBase> TWeakObjectPtrBase TWeakObjectPtr< T, TWeakObjectPtrBase >::WeakPtr private
Definition at line 368 of file WeakObjectPtrTemplates.h.
Referenced by TWeakObjectPtr< const T >::operator==().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/UObject/WeakObjectPtrTemplates.h