Unreal Engine 5.6 C++ API: UE::Math::TRotator< T > Struct Template Reference
UE::Math::TRotator< T > Struct Template Reference
Implements a container for rotation information.
#include "Rotator.h"
Public Types
using FReal = T
Public Member Functions
TRotator ()=default
Default constructor (no initialization).
TRotator (const TQuat< T > &Quat)
Constructor.
template<typename FArg UE_REQUIRES>
TRotator (const TRotator< FArg > &From)
FORCEINLINE TRotator (EForceInit)
Constructor.
FORCEINLINE TRotator (T InF)
Constructor.
FORCEINLINE TRotator (T InPitch, T InYaw, T InRoll)
Constructor.
TRotator Add (T DeltaPitch, T DeltaYaw, T DeltaRoll)
Adds to each component of the rotator.
TRotator< T > Clamp () const
Gets the rotation values so they fall within the range [0,360].
bool ContainsNaN () const
Utility to check if there are any non-finite values (NaN or Inf) in this Rotator.
FORCEINLINE void DiagnosticCheckNaN () const
FORCEINLINE void DiagnosticCheckNaN (const TCHAR *Message) const
bool Equals (const TRotator< T > &R, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether two rotators are equal within specified tolerance, when treated as an orientation.
bool EqualsOrientation (const TRotator< T > &R, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether two rotators have the same orientation within the specified tolerance, without requiring similar angles or wound multiples of 360.
TVector< T > Euler () const
Convert a Rotator into floating-point Euler angles (in degrees).
T GetComponentForAxis (EAxis::Type Axis) const
Get a specific component of the vector, given a specific axis by enum.
TRotator< T > GetDenormalized () const
Create a copy of this rotator and denormalize, clamping each axis to 0 - 360.
TRotator GetEquivalentRotator () const
Return a Rotator that has the same rotation but has different degree values for Yaw, Pitch, and Roll.
TRotator GetInverse () const
Returns the inverse of the rotator.
T GetManhattanDistance (const TRotator< T > &Rotator) const
Return the manhattan distance in degrees between this Rotator and the passed in one.
TRotator< T > GetNormalized () const
Create a copy of this rotator and normalize, removes all winding and creates the "shortest route" rotation.
void GetWindingAndRemainder (TRotator< T > &Winding, TRotator< T > &Remainder) const
Decompose this Rotator into a Winding part (multiples of 360) and a Remainder part.
TRotator GridSnap (const TRotator< T > &RotGrid) const
Get the rotation, snapped to specified degree segments.
bool InitFromString (const FString &InSourceString)
Initialize this Rotator based on an FString.
bool IsNearlyZero (T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether rotator is nearly zero within specified tolerance, when treated as an orientation.
bool IsZero () const
Checks whether this has exactly zero rotation, when treated as an orientation.
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess)
void Normalize ()
In-place normalize, removes all winding and creates the "shortest route" rotation.
bool operator!= (const TRotator< T > &V) const
Checks whether two rotators are different.
template<typename FArg UE_REQUIRES>
FORCEINLINE TRotator operator* (FArg Scale) const
Get the result of scaling this rotator.
template<typename FArg UE_REQUIRES>
FORCEINLINE TRotator operator*= (FArg Scale)
Multiply this rotator by a scaling factor.
TRotator operator+ (const TRotator< T > &R) const
Get the result of adding a rotator to this.
TRotator operator+= (const TRotator< T > &R)
Adds another rotator to this.
TRotator operator- (const TRotator< T > &R) const
Get the result of subtracting a rotator from this.
TRotator operator-= (const TRotator< T > &R)
Subtracts another rotator from this.
bool operator== (const TRotator< T > &R) const
Checks whether two rotators are identical.
TQuat< T > Quaternion () const
Get Rotation as a quaternion.
TVector< T > RotateVector (const UE::Math::TVector< T > &V) const
Rotate a vector rotated by this rotator.
bool Serialize (FArchive &Ar)
void SerializeCompressed (FArchive &Ar)
Serializes the rotator compressed for e.g.
void SerializeCompressedShort (FArchive &Ar)
Serializes the rotator compressed for e.g.
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
void SetClosestToMe (TRotator &MakeClosest) const
Modify if necessary the passed in rotator to be the closest rotator to it based upon it's equivalent.
void SetComponentForAxis (EAxis::Type Axis, T Component)
Set a specified componet of the vector, given a specific axis by enum.
FString ToCompactString () const
Get a short textural representation of this vector, for compact readable logging.
FString ToString () const
Get a textual representation of the vector.
TVector< T > UnrotateVector (const UE::Math::TVector< T > &V) const
Returns the vector rotated by the inverse of this rotator.
TVector< T > Vector () const
Convert a rotation into a unit vector facing in its direction.
Static Public Member Functions
static T ClampAxis (T Angle)
Clamps an angle to the range of [0, 360).
static uint8 CompressAxisToByte (T Angle)
Compresses a floating point angle into a byte.
static uint16 CompressAxisToShort (T Angle)
Compress a floating point angle into a word.
static T DecompressAxisFromByte (uint8 Angle)
Decompress a word into a floating point angle.
static T DecompressAxisFromShort (uint16 Angle)
Decompress a short into a floating point angle.
static TRotator MakeFromEuler (const TVector< T > &Euler)
Convert a vector of floating-point Euler angles (in degrees) into a Rotator.
static T NormalizeAxis (T Angle)
Clamps an angle to the range of (-180, 180].
Data Fields
T Pitch
Rotation around the right axis (around Y axis), Looking up and down (0=Straight Ahead, +Up, -Down)
T Roll
Rotation around the forward axis (around X axis), Tilting your head, (0=Straight, +Clockwise, -CCW)
T Yaw
Rotation around the up axis (around Z axis), Turning around (0=Forward, +Right, -Left)
Static Public Attributes
static const TRotator< T > ZeroRotator
A rotator of zero degrees on each axis.
Detailed Description
template<typename T>
struct UE::Math::TRotator< T >
Implements a container for rotation information.
All rotation values are stored in degrees.
The angles are interpreted as intrinsic rotations applied in the order Yaw, then Pitch, then Roll. I.e., an object would be rotated first by the specified yaw around its up axis (with positive angles interpreted as clockwise when viewed from above, along -Z), then pitched around its (new) right axis (with positive angles interpreted as 'nose up', i.e. clockwise when viewed along +Y), and then finally rolled around its (final) forward axis (with positive angles interpreted as clockwise rotations when viewed along +X).
Note that these conventions differ from quaternion axis/angle. UE Quat always considers a positive angle to be a left-handed rotation, whereas Rotator treats yaw as left-handed but pitch and roll as right-handed.
Definition at line 36 of file Rotator.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TRotator< T >::FReal = T
Definition at line 43 of file Rotator.h.
Constructor & Destructor Documentation
TRotator() [1/6]
template<typename T> UE::Math::TRotator< T >::TRotator () nodiscard default
Default constructor (no initialization).
Referenced by Add(), Clamp(), Equals(), EqualsOrientation(), GetDenormalized(), GetEquivalentRotator(), GetManhattanDistance(), GetNormalized(), GridSnap(), operator!=(), UE::Math::TRotator< double >::operator*(), operator+(), operator+=(), operator-(), operator-=(), operator==(), and SetClosestToMe().
TRotator() [2/6]
template<typename T> FORCEINLINE UE::Math::TRotator< T >::TRotator (T InF) explicit nodiscard
Constructor.
Parameters
InF Value to set all components to.
Definition at line 561 of file Rotator.h.
References DiagnosticCheckNaN(), FORCEINLINE, Pitch, Roll, and Yaw.
TRotator() [3/6]
template<typename T> FORCEINLINE UE::Math::TRotator< T >::TRotator (T InPitch, T InYaw, T InRoll) nodiscard
Constructor.
Parameters
InPitch Pitch in degrees.
InYaw Yaw in degrees.
InRoll Roll in degrees.
Definition at line 568 of file Rotator.h.
References DiagnosticCheckNaN(), FORCEINLINE, Pitch, Roll, and Yaw.
TRotator() [4/6]
template<typename T> FORCEINLINE UE::Math::TRotator< T >::TRotator (EForceInit) explicit nodiscard
Constructor.
Parameters
EForceInit Force Init Enum.
Definition at line 575 of file Rotator.h.
References FORCEINLINE, Pitch, Roll, and Yaw.
TRotator() [5/6]
template<typename T> UE::Math::TRotator< T >::TRotator (const TQuat< T > & Quat) explicit nodiscard
Constructor.
Parameters
Quat Quaternion used to specify rotation.
TRotator() [6/6]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TRotator< T >::TRotator (const TRotator< FArg > & From) inline explicit
Definition at line 499 of file Rotator.h.
Member Function Documentation
Add()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::Add (T DeltaPitch, T DeltaYaw, T DeltaRoll)
Adds to each component of the rotator.
Parameters
DeltaPitch Change in pitch. (+/-)
DeltaYaw Change in yaw. (+/-)
DeltaRoll Change in roll. (+/-)
Returns
Copy of rotator after addition.
Definition at line 664 of file Rotator.h.
References TRotator(), DiagnosticCheckNaN(), FORCEINLINE, Pitch, Roll, and Yaw.
Clamp()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::Clamp () const nodiscard
Gets the rotation values so they fall within the range [0,360].
Returns
Clamped version of rotator.
Definition at line 685 of file Rotator.h.
References TRotator(), ClampAxis(), FORCEINLINE, Pitch, Roll, and Yaw.
ClampAxis()
template<typename T> FORCEINLINE T UE::Math::TRotator< T >::ClampAxis (T Angle) static nodiscard
Clamps an angle to the range of [0, 360).
Parameters
Angle The angle to clamp.
Returns
The clamped angle.
Definition at line 691 of file Rotator.h.
References Angle, and FORCEINLINE.
Referenced by Clamp(), FMath::ClampAngle(), GetDenormalized(), IsZero(), and NormalizeAxis().
CompressAxisToByte()
template<typename T> FORCEINLINE uint8 UE::Math::TRotator< T >::CompressAxisToByte (T Angle) static nodiscard
Compresses a floating point angle into a byte.
Parameters
Angle The angle to compress.
Returns
The angle as a byte.
Definition at line 721 of file Rotator.h.
References Angle, and FORCEINLINE.
CompressAxisToShort()
template<typename T> FORCEINLINE uint16 UE::Math::TRotator< T >::CompressAxisToShort (T Angle) static nodiscard
Compress a floating point angle into a word.
Parameters
Angle The angle to compress.
Returns
The decompressed angle.
Definition at line 735 of file Rotator.h.
References Angle, and FORCEINLINE.
ContainsNaN()
template<typename T> FORCEINLINE bool UE::Math::TRotator< T >::ContainsNaN () const nodiscard
Utility to check if there are any non-finite values (NaN or Inf) in this Rotator.
Returns
true if there are any non-finite values in this Rotator, otherwise false.
Definition at line 873 of file Rotator.h.
References FORCEINLINE, Pitch, Roll, and Yaw.
DecompressAxisFromByte()
template<typename T> FORCEINLINE T UE::Math::TRotator< T >::DecompressAxisFromByte (uint8 Angle) static nodiscard
Decompress a word into a floating point angle.
Parameters
Angle The word angle.
Returns
The decompressed angle.
Definition at line 728 of file Rotator.h.
References Angle, and FORCEINLINE.
DecompressAxisFromShort()
template<typename T> FORCEINLINE T UE::Math::TRotator< T >::DecompressAxisFromShort (uint16 Angle) static nodiscard
Decompress a short into a floating point angle.
Parameters
Angle The word angle.
Returns
The decompressed angle.
Definition at line 742 of file Rotator.h.
References Angle, and FORCEINLINE.
DiagnosticCheckNaN() [1/2]
template<typename T> FORCEINLINE void UE::Math::TRotator< T >::DiagnosticCheckNaN () const inline
Definition at line 80 of file Rotator.h.
Referenced by TRotator(), TRotator(), Add(), InitFromString(), Normalize(), UE::Math::TRotator< double >::operator*=(), operator+=(), and operator-=().
DiagnosticCheckNaN() [2/2]
template<typename T> FORCEINLINE void UE::Math::TRotator< T >::DiagnosticCheckNaN (const TCHAR * Message) const inline
Definition at line 81 of file Rotator.h.
Equals()
template<typename T> FORCEINLINE bool UE::Math::TRotator< T >::Equals (const TRotator< T > & R, T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Checks whether two rotators are equal within specified tolerance, when treated as an orientation.
This means that TRotator(0, 0, 360).Equals(TRotator(0,0,0)) is true, because they represent the same final orientation. It can compare only wound rotators (i.e. multiples of 360 degrees) that end up in a same rotation Rotators that represent the same final rotation, but get there via different intermediate rotations aren't equal i.e. TRotator(0, 45, 0).Equals(TRotator(180, 135, 180)) is false
Parameters
R The other rotator.
Tolerance Error Tolerance.
Returns
true if two rotators are equal, within specified tolerance, otherwise false.
Definition at line 642 of file Rotator.h.
References TRotator(), FORCEINLINE, NormalizeAxis(), Pitch, R, Roll, VectorAbs(), VectorAnyGreaterThan(), VectorLoadFloat1(), VectorSubtract(), and Yaw.
EqualsOrientation()
template<typename T> bool UE::Math::TRotator< T >::EqualsOrientation (const TRotator< T > & R, T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Checks whether two rotators have the same orientation within the specified tolerance, without requiring similar angles or wound multiples of 360.
Unlike Equals(), it can compare Rotators that represent the same final orientation, but get there via different intermediate rotations. i.e. If we compare two rotators with different angles, but same orientation like so: A = TRotator(0, 45, 0) B = TRotator(180, 135, 180) Then A.EqualsOrientation(B) would be TRUE while A.Equals(B) would be FALSE
Parameters
R The other rotator.
Tolerance Error Tolerance.
Returns
true if two rotators are equal, within specified tolerance, otherwise false.
Definition at line 658 of file Rotator.h.
References TRotator(), Quaternion(), and R.
Euler()
template<typename T> TVector< T > UE::Math::TRotator< T >::Euler () const nodiscard
Convert a Rotator into floating-point Euler angles (in degrees).
Rotator now stored in degrees.
Returns
Rotation as a Euler angle vector.
Referenced by UE::MovieScene::MultiChannelFromData().
GetComponentForAxis()
template<typename T> FORCEINLINE T UE::Math::TRotator< T >::GetComponentForAxis (EAxis::Type Axis) const nodiscard
Get a specific component of the vector, given a specific axis by enum.
Definition at line 782 of file Rotator.h.
References Axis, FORCEINLINE, EAxis::None, Pitch, Roll, EAxis::X, EAxis::Y, Yaw, and EAxis::Z.
GetDenormalized()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::GetDenormalized () const nodiscard
Create a copy of this rotator and denormalize, clamping each axis to 0 - 360.
Returns
Denormalized copy of this rotator
Definition at line 757 of file Rotator.h.
References TRotator(), ClampAxis(), FORCEINLINE, Pitch, Roll, and Yaw.
GetEquivalentRotator()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::GetEquivalentRotator () const nodiscard
Return a Rotator that has the same rotation but has different degree values for Yaw, Pitch, and Roll.
This rotator should be within -180,180 range,
Returns
A Rotator with the same rotation but different degrees.
Definition at line 887 of file Rotator.h.
References TRotator(), FORCEINLINE, Pitch, Roll, and Yaw.
Referenced by SetClosestToMe().
GetInverse()
template<typename T> TRotator UE::Math::TRotator< T >::GetInverse () const nodiscard
Returns the inverse of the rotator.
GetManhattanDistance()
template<typename T> FORCEINLINE T UE::Math::TRotator< T >::GetManhattanDistance (const TRotator< T > & Rotator) const nodiscard
Return the manhattan distance in degrees between this Rotator and the passed in one.
Parameters
Rotator[In] the Rotator we are comparing with.
Returns
Distance(Manhattan) between the two rotators.
Definition at line 881 of file Rotator.h.
References TRotator(), FORCEINLINE, Pitch, Roll, Rotator, and Yaw.
Referenced by SetClosestToMe().
GetNormalized()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::GetNormalized () const nodiscard
Create a copy of this rotator and normalize, removes all winding and creates the "shortest route" rotation.
Returns
Normalized copy of this rotator
Definition at line 749 of file Rotator.h.
References TRotator(), FORCEINLINE, and Normalize().
Referenced by FMath::LerpRange(), and FRotationConversionCache::RotatorToQuat().
GetWindingAndRemainder()
template<typename T> void UE::Math::TRotator< T >::GetWindingAndRemainder (TRotator< T > & Winding, TRotator< T > & Remainder) const
Decompose this Rotator into a Winding part (multiples of 360) and a Remainder part.
Remainder will always be in [-180, 180] range.
Parameters
Winding[Out] the Winding part of this Rotator
Remainder[Out] the Remainder
GridSnap()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::GridSnap (const TRotator< T > & RotGrid) const nodiscard
Get the rotation, snapped to specified degree segments.
Parameters
RotGrid A Rotator specifying how to snap each component.
Returns
Snapped version of rotation.
Definition at line 674 of file Rotator.h.
References TRotator(), FORCEINLINE, FMath::GridSnap(), Pitch, Roll, and Yaw.
InitFromString()
template<typename T> FORCEINLINE bool UE::Math::TRotator< T >::InitFromString (const FString & InSourceString)
Initialize this Rotator based on an FString.
The String is expected to contain P=, Y=, R=. The TRotator will be bogus when InitFromString returns false.
Parameters
InSourceString FString containing the rotator values.
Returns
true if the P,Y,R values were read successfully; false otherwise.
Definition at line 862 of file Rotator.h.
References DiagnosticCheckNaN(), FORCEINLINE, Pitch, Roll, TEXT, FParse::Value(), and Yaw.
Referenced by DisplayClusterTypesConverter::FromString().
IsNearlyZero()
template<typename T> FORCEINLINE bool UE::Math::TRotator< T >::IsNearlyZero (T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Checks whether rotator is nearly zero within specified tolerance, when treated as an orientation.
This means that TRotator(0, 0, 360) is "zero", because it is the same final orientation as the zero rotator.
Parameters
Tolerance Error Tolerance.
Returns
true if rotator is nearly zero, within specified tolerance, otherwise false.
Definition at line 620 of file Rotator.h.
References FORCEINLINE, NormalizeAxis(), Pitch, Roll, VectorAbs(), VectorAnyGreaterThan(), VectorLoadFloat1(), and Yaw.
Referenced by FStreamingSourceShapeHelper::ForEachShape(), and ToCompactString().
IsZero()
template<typename T> FORCEINLINE bool UE::Math::TRotator< T >::IsZero () const nodiscard
Checks whether this has exactly zero rotation, when treated as an orientation.
This means that TRotator(0, 0, 360) is "zero", because it is the same final orientation as the zero rotator.
Returns
true if this has exactly zero rotation, otherwise false.
Definition at line 636 of file Rotator.h.
References ClampAxis(), FORCEINLINE, Pitch, Roll, and Yaw.
MakeFromEuler()
template<typename T> TRotator UE::Math::TRotator< T >::MakeFromEuler (const TVector< T > & Euler) static nodiscard
Convert a vector of floating-point Euler angles (in degrees) into a Rotator.
Rotator now stored in degrees
Parameters
Euler Euler angle vector.
Returns
A rotator from a Euler angle.
Referenced by Inverse().
NetSerialize()
template<typename T> bool UE::Math::TRotator< T >::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess)
Normalize()
template<typename T> FORCEINLINE void UE::Math::TRotator< T >::Normalize ()
In-place normalize, removes all winding and creates the "shortest route" rotation.
Definition at line 767 of file Rotator.h.
References DiagnosticCheckNaN(), FORCEINLINE, NormalizeAxis(), Pitch, Roll, VectorStoreFloat3(), and Yaw.
Referenced by GetNormalized().
NormalizeAxis()
template<typename T> FORCEINLINE T UE::Math::TRotator< T >::NormalizeAxis (T Angle) static nodiscard
Clamps an angle to the range of (-180, 180].
Parameters
Angle The Angle to clamp.
Returns
The clamped angle.
Definition at line 706 of file Rotator.h.
References Angle, ClampAxis(), and FORCEINLINE.
Referenced by FMath::ClampAngle(), Equals(), IsNearlyZero(), and Normalize().
operator!=()
template<typename T> FORCEINLINE bool UE::Math::TRotator< T >::operator!= (const TRotator< T > & V) const nodiscard
Checks whether two rotators are different.
Parameters
V The other rotator.
Returns
true if two rotators are different, otherwise false.
Definition at line 598 of file Rotator.h.
References TRotator(), FORCEINLINE, Pitch, Roll, and Yaw.
operator*()
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TRotator UE::Math::TRotator< T >::operator* (FArg Scale) const inline nodiscard
Get the result of scaling this rotator.
Parameters
Scale The scaling factor.
Returns
The result of scaling.
Definition at line 146 of file Rotator.h.
operator*=()
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TRotator UE::Math::TRotator< T >::operator*= (FArg Scale) inline
Multiply this rotator by a scaling factor.
Parameters
Scale The scaling factor.
Returns
Copy of the rotator after scaling.
Definition at line 158 of file Rotator.h.
operator+()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::operator+ (const TRotator< T > & R) const nodiscard
Get the result of adding a rotator to this.
Parameters
R The other rotator.
Returns
The result of adding a rotator to this.
Definition at line 580 of file Rotator.h.
References TRotator(), FORCEINLINE, Pitch, R, Roll, and Yaw.
operator+=()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::operator+= (const TRotator< T > & R)
Adds another rotator to this.
Parameters
R The other rotator.
Returns
Copy of rotator after addition.
Definition at line 604 of file Rotator.h.
References TRotator(), DiagnosticCheckNaN(), FORCEINLINE, Pitch, R, Roll, and Yaw.
operator-()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::operator- (const TRotator< T > & R) const nodiscard
Get the result of subtracting a rotator from this.
Parameters
R The other rotator.
Returns
The result of subtracting a rotator from this.
Definition at line 586 of file Rotator.h.
References TRotator(), FORCEINLINE, Pitch, R, Roll, and Yaw.
operator-=()
template<typename T> FORCEINLINE TRotator< T > UE::Math::TRotator< T >::operator-= (const TRotator< T > & R)
Subtracts another rotator from this.
Parameters
R The other rotator.
Returns
Copy of rotator after subtraction.
Definition at line 612 of file Rotator.h.
References TRotator(), DiagnosticCheckNaN(), FORCEINLINE, Pitch, R, Roll, and Yaw.
operator==()
template<typename T> FORCEINLINE bool UE::Math::TRotator< T >::operator== (const TRotator< T > & R) const nodiscard
Checks whether two rotators are identical.
This checks each component for exact equality.
Parameters
R The other rotator.
Returns
true if two rotators are identical, otherwise false.
See also
Equals()
Definition at line 592 of file Rotator.h.
References TRotator(), FORCEINLINE, Pitch, R, Roll, and Yaw.
Quaternion()
template<typename T> TQuat< T > UE::Math::TRotator< T >::Quaternion () const nodiscard
Get Rotation as a quaternion.
Returns
Rotation as a quaternion.
Referenced by EqualsOrientation(), FRotationConversionCache::RotatorToQuat(), FRotationConversionCache::RotatorToQuat_ReadOnly(), and FDisplayClusterShaderParameters_ICVFX::FCameraSettings::SetViewProjection().
RotateVector()
template<typename T> TVector< T > UE::Math::TRotator< T >::RotateVector (const UE::Math::TVector< T > & V) const nodiscard
Rotate a vector rotated by this rotator.
Parameters
V The vector to rotate.
Returns
The rotated vector.
Serialize()
template<typename T> bool UE::Math::TRotator< T >::Serialize (FArchive & Ar) inline
Definition at line 479 of file Rotator.h.
SerializeCompressed()
template<typename T> void UE::Math::TRotator< T >::SerializeCompressed (FArchive & Ar)
Serializes the rotator compressed for e.g.
network transmission.
Parameters
Ar Archive to serialize to/ from
SerializeCompressedShort()
template<typename T> void UE::Math::TRotator< T >::SerializeCompressedShort (FArchive & Ar)
Serializes the rotator compressed for e.g.
network transmission (use shorts though).
Parameters
Ar Archive to serialize to/ from
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TRotator< T >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 485 of file Rotator.h.
SetClosestToMe()
template<typename T> FORCEINLINE void UE::Math::TRotator< T >::SetClosestToMe (TRotator< T > & MakeClosest) const
Modify if necessary the passed in rotator to be the closest rotator to it based upon it's equivalent.
This Rotator should be within (-180, 180], usually just constructed from a Matrix or a Quaternion.
Parameters
MakeClosest[In/Out] the Rotator we want to make closest to us. Should be between (-180, 180]. This Rotator may change if we need to use different degree values to make it closer.
Definition at line 893 of file Rotator.h.
References TRotator(), FORCEINLINE, GetEquivalentRotator(), and GetManhattanDistance().
SetComponentForAxis()
template<typename T> FORCEINLINE void UE::Math::TRotator< T >::SetComponentForAxis (EAxis::Type Axis, T Component)
Set a specified componet of the vector, given a specific axis by enum.
Definition at line 799 of file Rotator.h.
References Axis, Component, FORCEINLINE, EAxis::None, Pitch, Roll, EAxis::X, EAxis::Y, Yaw, and EAxis::Z.
ToCompactString()
template<typename T> FORCEINLINE FString UE::Math::TRotator< T >::ToCompactString () const nodiscard
Get a short textural representation of this vector, for compact readable logging.
Definition at line 825 of file Rotator.h.
References FORCEINLINE, FMath::IsNearlyZero(), IsNearlyZero(), Pitch, Roll, TEXT, and Yaw.
ToString()
template<typename T> FORCEINLINE FString UE::Math::TRotator< T >::ToString () const nodiscard
Get a textual representation of the vector.
Returns
Text describing the vector.
Definition at line 819 of file Rotator.h.
References FORCEINLINE, Pitch, Roll, TEXT, and Yaw.
Referenced by DisplayClusterTypesConverter::ToString().
UnrotateVector()
template<typename T> TVector< T > UE::Math::TRotator< T >::UnrotateVector (const UE::Math::TVector< T > & V) const nodiscard
Returns the vector rotated by the inverse of this rotator.
Parameters
V The vector to rotate.
Returns
The rotated vector.
Vector()
template<typename T> TVector< T > UE::Math::TRotator< T >::Vector () const nodiscard
Convert a rotation into a unit vector facing in its direction.
Returns
Rotation as a unit direction vector.
Referenced by FStreamingSourceShapeHelper::ForEachShape().
Field Documentation
Pitch
template<typename T> T UE::Math::TRotator< T >::Pitch
Rotation around the right axis (around Y axis), Looking up and down (0=Straight Ahead, +Up, -Down)
Definition at line 46 of file Rotator.h.
Referenced by UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), TRotator(), TRotator(), TRotator(), UE::Math::TScaleRotationTranslationMatrix< T >::TScaleRotationTranslationMatrix(), Add(), Clamp(), ContainsNaN(), Equals(), GetComponentForAxis(), GetDenormalized(), GetEquivalentRotator(), GetManhattanDistance(), GridSnap(), InitFromString(), IsNearlyZero(), IsZero(), Normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator==(), SetComponentForAxis(), ToCompactString(), DisplayClusterTypesConverter::ToHexString(), and ToString().
Roll
template<typename T> T UE::Math::TRotator< T >::Roll
Rotation around the forward axis (around X axis), Tilting your head, (0=Straight, +Clockwise, -CCW)
Definition at line 52 of file Rotator.h.
Referenced by UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), TRotator(), TRotator(), TRotator(), UE::Math::TScaleRotationTranslationMatrix< T >::TScaleRotationTranslationMatrix(), Add(), Clamp(), ContainsNaN(), Equals(), GetComponentForAxis(), GetDenormalized(), GetEquivalentRotator(), GetManhattanDistance(), GridSnap(), InitFromString(), IsNearlyZero(), IsZero(), Normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator==(), SetComponentForAxis(), ToCompactString(), DisplayClusterTypesConverter::ToHexString(), and ToString().
Yaw
template<typename T> T UE::Math::TRotator< T >::Yaw
Rotation around the up axis (around Z axis), Turning around (0=Forward, +Right, -Left)
Definition at line 49 of file Rotator.h.
Referenced by UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), TRotator(), TRotator(), TRotator(), UE::Math::TScaleRotationTranslationMatrix< T >::TScaleRotationTranslationMatrix(), Add(), Clamp(), ContainsNaN(), Equals(), FStreamingSourceShapeHelper::ForEachShape(), GetComponentForAxis(), GetDenormalized(), GetEquivalentRotator(), GetManhattanDistance(), GridSnap(), InitFromString(), IsNearlyZero(), IsZero(), Normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator==(), SetComponentForAxis(), ToCompactString(), DisplayClusterTypesConverter::ToHexString(), and ToString().
ZeroRotator
template<typename T> const TRotator<T> UE::Math::TRotator< T >::ZeroRotator static
A rotator of zero degrees on each axis.
Definition at line 57 of file Rotator.h.
The documentation for this struct was generated from the following files:
Runtime/Core/Public/Math/MathFwd.h
Runtime/Core/Public/Math/Rotator.h