Unreal Engine 5.6 C++ API: TTypeCompatibleBytes< T & > Struct Template Reference
TTypeCompatibleBytes< T & > Struct Template Reference
#include "TypeCompatibleBytes.h"
Public Types
using ConstGetType = T&
using ElementTypeAlias_NatVisHelper = T&
using MutableGetType = T&
using RvalueGetType = T&
Public Member Functions
TTypeCompatibleBytes ()=default
TTypeCompatibleBytes (const TTypeCompatibleBytes &)=delete
TTypeCompatibleBytes (TTypeCompatibleBytes &&)=delete
~TTypeCompatibleBytes ()=default
void DestroyUnchecked ()
void EmplaceUnchecked (T &Ref)
T &* GetTypedPtr ()
T & GetUnchecked () const
TTypeCompatibleBytes & operator= (const TTypeCompatibleBytes &)=delete
TTypeCompatibleBytes & operator= (TTypeCompatibleBytes &&)=delete
Data Fields
uint8 Pad [sizeof(T &)]
T * Ptr
Detailed Description
template<typename T>
struct TTypeCompatibleBytes< T & >
Definition at line 85 of file TypeCompatibleBytes.h.
Member Typedef Documentation
ConstGetType
template<typename T> using TTypeCompatibleBytes< T & >::ConstGetType = T&
Definition at line 100 of file TypeCompatibleBytes.h.
ElementTypeAlias_NatVisHelper
template<typename T> using TTypeCompatibleBytes< T & >::ElementTypeAlias_NatVisHelper = T&
Definition at line 87 of file TypeCompatibleBytes.h.
MutableGetType
template<typename T> using TTypeCompatibleBytes< T & >::MutableGetType = T&
Definition at line 99 of file TypeCompatibleBytes.h.
RvalueGetType
template<typename T> using TTypeCompatibleBytes< T & >::RvalueGetType = T&
Definition at line 101 of file TypeCompatibleBytes.h.
Constructor & Destructor Documentation
TTypeCompatibleBytes() [1/3]
template<typename T> TTypeCompatibleBytes< T & >::TTypeCompatibleBytes () default
Referenced by TTypeCompatibleBytes(), TTypeCompatibleBytes(), operator=(), and operator=().
~TTypeCompatibleBytes()
template<typename T> TTypeCompatibleBytes< T & >::~TTypeCompatibleBytes () default
TTypeCompatibleBytes() [2/3]
template<typename T> TTypeCompatibleBytes< T & >::TTypeCompatibleBytes (TTypeCompatibleBytes< T & > &&) delete
References TTypeCompatibleBytes().
TTypeCompatibleBytes() [3/3]
template<typename T> TTypeCompatibleBytes< T & >::TTypeCompatibleBytes (const TTypeCompatibleBytes< T & > &) delete
References TTypeCompatibleBytes().
Member Function Documentation
DestroyUnchecked()
template<typename T> void TTypeCompatibleBytes< T & >::DestroyUnchecked () inline
Definition at line 118 of file TypeCompatibleBytes.h.
EmplaceUnchecked()
template<typename T> void TTypeCompatibleBytes< T & >::EmplaceUnchecked (T & Ref) inline
Definition at line 111 of file TypeCompatibleBytes.h.
References Ptr.
GetTypedPtr()
T & * TTypeCompatibleBytes< T & >::GetTypedPtr () inline
Definition at line 38 of file TypeCompatibleBytes.h.
GetUnchecked()
template<typename T> T & TTypeCompatibleBytes< T & >::GetUnchecked () const inline
Definition at line 104 of file TypeCompatibleBytes.h.
References Ptr.
operator=() [1/2]
template<typename T> TTypeCompatibleBytes & TTypeCompatibleBytes< T & >::operator= (const TTypeCompatibleBytes< T & > &) delete
References TTypeCompatibleBytes().
operator=() [2/2]
template<typename T> TTypeCompatibleBytes & TTypeCompatibleBytes< T & >::operator= (TTypeCompatibleBytes< T & > &&) delete
References TTypeCompatibleBytes().
Field Documentation
Pad
uint8 TTypeCompatibleBytes< T & >::Pad[sizeof(T &)]
Definition at line 81 of file TypeCompatibleBytes.h.
Ptr
template<typename T> T* TTypeCompatibleBytes< T & >::Ptr
Definition at line 122 of file TypeCompatibleBytes.h.
Referenced by EmplaceUnchecked(), and GetUnchecked().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/TypeCompatibleBytes.h