Unreal Engine 5.6 C++ API: SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType > Struct Template Reference
SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType > Struct Template Reference
Public Types
using WidgetArgsType = ArgumentType
Public Member Functions
FORCENOINLINE FVectorXArguments ()
OnXChanged ToggleXChecked ContextMenuExtenderX OnXEndSliderMovement SLATE_ATTRIBUTE (FText, XDisplayName) SLATE_ATTRIBUTE(FLinearColor
The DisplayName of the X component of the vector.
SLATE_ATTRIBUTE (TOptional< NumericType >, X) SLATE_EVENT(FOnNumericValueChanged
X Component of the vector.
OnXChanged ToggleXChecked SLATE_EVENT (FOnCheckStateChanged, OnToggleXChanged) SLATE_EVENT(FMenuExtensionDelegate
Called whenever the toggle X changes state.
OnXChanged SLATE_EVENT (FOnNumericValueCommitted, OnXCommitted) SLATE_ATTRIBUTE(ECheckBoxState
Called when the x value of the vector is committed.
OnXChanged ToggleXChecked ContextMenuExtenderX SLATE_EVENT (FSimpleDelegate, OnXBeginSliderMovement) SLATE_EVENT(FOnNumericValueChanged
Called when the x value of the vector slider began movement.
Detailed Description
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3>
template<typename ArgumentType>
struct SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >
Definition at line 51 of file SVectorInputBox.h.
Member Typedef Documentation
WidgetArgsType
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> using SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::WidgetArgsType = ArgumentType
Definition at line 53 of file SVectorInputBox.h.
Constructor & Destructor Documentation
FVectorXArguments()
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> FORCENOINLINE SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::FVectorXArguments () inline
Definition at line 55 of file SVectorInputBox.h.
References FORCENOINLINE, AxisDisplayInfo::GetAxisColor(), AxisDisplayInfo::GetAxisDisplayName(), NSLOCTEXT, AxisDisplayInfo::UseForwardRightUpDisplayNames(), and EAxisList::X.
Member Function Documentation
SLATE_ATTRIBUTE() [1/2]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnXChanged ToggleXChecked ContextMenuExtenderX OnXEndSliderMovement SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::SLATE_ATTRIBUTE (FText , XDisplayName)
The DisplayName of the X component of the vector.
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/2]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::SLATE_ATTRIBUTE (TOptional< NumericType > , X)
X Component of the vector.
Called when the x value of the vector is changed
References X.
Referenced by SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_EVENT() [1/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnXChanged ToggleXChecked SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::SLATE_EVENT (FOnCheckStateChanged , OnToggleXChanged)
Called whenever the toggle X changes state.
Menu extender delegate for the X value
References SLATE_EVENT().
SLATE_EVENT() [2/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnXChanged SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::SLATE_EVENT (FOnNumericValueCommitted , OnXCommitted)
Called when the x value of the vector is committed.
The value of the toggle X checkbox
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
Referenced by SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [3/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnXChanged ToggleXChecked ContextMenuExtenderX SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::SLATE_EVENT (FSimpleDelegate , OnXBeginSliderMovement)
Called when the x value of the vector slider began movement.
Called when the x value of the vector slider ended movement
References SLATE_EVENT().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SVectorInputBox.h