Unreal Engine 5.6 C++ API: UE::Math::TRotationMatrix< T > Struct Template Reference
UE::Math::TRotationMatrix< T > Struct Template Reference
Rotation matrix no translation.
#include "RotationMatrix.h"
Public Member Functions
TRotationMatrix (const TRotator< T > &Rot)
Constructor.
Public Member Functions inherited from UE::Math::TRotationTranslationMatrix< T >
template<typename FArg UE_REQUIRES>
TRotationTranslationMatrix (const TRotationTranslationMatrix< FArg > &From)
TRotationTranslationMatrix (const TRotator< T > &Rot, const TVector< T > &Origin)
Constructor.
Public Member Functions inherited from UE::Math::TMatrix< T >
TMatrix ()=default
template<typename FArg UE_REQUIRES>
TMatrix (const TMatrix< FArg > &From)
FORCEINLINE TMatrix (const TPlane< T > &InX, const TPlane< T > &InY, const TPlane< T > &InZ, const TPlane< T > &InW)
Constructor.
FORCEINLINE TMatrix (const TVector< T > &InX, const TVector< T > &InY, const TVector< T > &InZ, const TVector< T > &InW)
Constructor.
FORCEINLINE TMatrix (EForceInit)
Constructor.
TMatrix< T > ApplyScale (T Scale) const
Apply Scale to this matrix.
uint32 ComputeHash () const
For debugging purpose, could be changed.
TMatrix< T > ConcatTranslation (const TVector< T > &Translation) const
Returns a matrix with an additional translation concatenated.
bool ContainsNaN () const
Returns true if any element of this matrix is NaN.
void DebugPrint () const
Output ToString.
T Determinant () const
FORCEINLINE void DiagnosticCheckNaN () const
bool Equals (const TMatrix< T > &Other, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether another Matrix is equal to this, within specified tolerance.
TVector< T > ExtractScaling (T Tolerance=UE_SMALL_NUMBER)
Remove any scaling from this matrix (ie magnitude of each row is 1) and return the 3D scale vector that was initially present with error Tolerance.
TVector< T > GetColumn (int32 i) const
get a column of this matrix
FORCEINLINE bool GetFrustumBottomPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumFarPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumLeftPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumNearPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumRightPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumTopPlane (TPlane< T > &OuTPln) const
TMatrix< T > GetMatrixWithoutScale (T Tolerance=UE_SMALL_NUMBER) const
T GetMaximumAxisScale () const
T GetMinimumAxisScale () const
TVector< T > GetOrigin () const
void GetScaledAxes (TVector< T > &X, TVector< T > &Y, TVector< T > &Z) const
get axes of this matrix scaled by the scale of the matrix
TVector< T > GetScaledAxis (EAxis::Type Axis) const
get axis of this matrix scaled by the scale of the matrix
TVector< T > GetScaleVector (T Tolerance=UE_SMALL_NUMBER) const
return a 3D scale vector calculated from this matrix (where each component is the magnitude of a row vector) with error Tolerance.
FORCEINLINE TMatrix< T > GetTransposed () const
void GetUnitAxes (TVector< T > &X, TVector< T > &Y, TVector< T > &Z) const
get unit length axes of this matrix
TVector< T > GetUnitAxis (EAxis::Type Axis) const
get unit length axis of this matrix
TMatrix< T > Inverse () const
Get the inverse of this matrix.
TMatrix< T > InverseFast () const
Get the inverse of this matrix.
FORCEINLINE TVector< T > InverseTransformPosition (const TVector< T > &V) const
Inverts the matrix and then transforms V - correctly handles scaling in this matrix.
FORCEINLINE TVector< T > InverseTransformVector (const TVector< T > &V) const
Transform a direction vector by the inverse of this matrix - will not take into account translation part.
void Mirror (EAxis::Type MirrorAxis, EAxis::Type FlipAxis)
Utility for mirroring this transform across a certain plane, and flipping one of the axis as well.
bool operator!= (const TMatrix< T > &Other) const
Checks whether another Matrix is not equal to this, within specified tolerance.
FORCEINLINE TMatrix< T > operator* (const TMatrix< T > &Other) const
Gets the result of multiplying a Matrix to this.
FORCEINLINE TMatrix< T > operator* (T Other) const
This isn't applying SCALE, just multiplying the value to all members - i.e.
FORCEINLINE void operator*= (const TMatrix< T > &Other)
Multiply this by a matrix.
FORCEINLINE void operator*= (T Other)
Multiply this matrix by a weighting factor.
FORCEINLINE TMatrix< T > operator+ (const TMatrix< T > &Other) const
Gets the result of adding a matrix to this.
FORCEINLINE void operator+= (const TMatrix< T > &Other)
Adds to this matrix.
bool operator== (const TMatrix< T > &Other) const
Checks whether two matrix are identical.
void RemoveScaling (T Tolerance=UE_SMALL_NUMBER)
TMatrix< T > RemoveTranslation () const
UE::Math::TRotator< T > Rotator () const
T RotDeterminant () const
void ScaleTranslation (const TVector< T > &Scale3D)
Scale the translation part of the matrix by the supplied vector.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
void SetAxes (const TVector< T > *Axis0=NULL, const TVector< T > *Axis1=NULL, const TVector< T > *Axis2=NULL, const TVector< T > *Origin=NULL)
Update the axes of the matrix if any value is NULL do not update that axis.
void SetAxis (int32 i, const TVector< T > &Axis)
set an axis of this matrix
void SetColumn (int32 i, TVector< T > Value)
Set a column of this matrix.
void SetIdentity ()
void SetOrigin (const TVector< T > &NewOrigin)
FORCEINLINE void To3x4MatrixTranspose (T *Out) const
Convert this Atom to the 3x4 transpose of the transformation matrix.
UE::Math::TQuat< T > ToQuat () const
Transform a rotation matrix into a quaternion.
FString ToString () const
Get a textual representation of the vector.
FORCEINLINE TVector4< T > TransformFVector4 (const TVector4< T > &V) const
FORCEINLINE TVector4< T > TransformPosition (const TVector< T > &V) const
Transform a location - will take into account translation part of the TMatrix<T>.
FORCEINLINE TVector4< T > TransformVector (const TVector< T > &V) const
Transform a direction vector - will not take into account translation part of the TMatrix<T>.
TMatrix< T > TransposeAdjoint () const
Static Public Member Functions
static TMatrix< T > Make (TQuat< T > const &Rot)
Matrix factory.
static TMatrix< T > Make (TRotator< T > const &Rot)
Matrix factory.
static TMatrix< T > MakeFromX (TVector< T > const &XAxis)
Builds a rotation matrix given only a XAxis.
static TMatrix< T > MakeFromXY (TVector< T > const &XAxis, TVector< T > const &YAxis)
Builds a matrix with given X and Y axes.
static TMatrix< T > MakeFromXZ (TVector< T > const &XAxis, TVector< T > const &ZAxis)
Builds a matrix with given X and Z axes.
static TMatrix< T > MakeFromY (TVector< T > const &YAxis)
Builds a rotation matrix given only a YAxis.
static TMatrix< T > MakeFromYX (TVector< T > const &YAxis, TVector< T > const &XAxis)
Builds a matrix with given Y and X axes.
static TMatrix< T > MakeFromYZ (TVector< T > const &YAxis, TVector< T > const &ZAxis)
Builds a matrix with given Y and Z axes.
static TMatrix< T > MakeFromZ (TVector< T > const &ZAxis)
Builds a rotation matrix given only a ZAxis.
static TMatrix< T > MakeFromZX (TVector< T > const &ZAxis, TVector< T > const &XAxis)
Builds a matrix with given Z and X axes.
static TMatrix< T > MakeFromZY (TVector< T > const &ZAxis, TVector< T > const &YAxis)
Builds a matrix with given Z and Y axes.
Static Public Member Functions inherited from UE::Math::TRotationTranslationMatrix< T >
static TMatrix< T > Make (const TRotator< T > &Rot, const TVector< T > &Origin)
Matrix factory.
Additional Inherited Members
Public Types inherited from UE::Math::TMatrix< T >
using FReal = T
Data Fields inherited from UE::Math::TMatrix< T >
T M [4][4]
Static Public Attributes inherited from UE::Math::TMatrix< T >
static const TMatrix Identity
Detailed Description
template<typename T>
struct UE::Math::TRotationMatrix< T >
Rotation matrix no translation.
Definition at line 17 of file RotationMatrix.h.
Constructor & Destructor Documentation
TRotationMatrix()
template<typename T> UE::Math::TRotationMatrix< T >::TRotationMatrix (const TRotator< T > & Rot) inline nodiscard
Constructor.
Parameters
Rot rotation
Definition at line 28 of file RotationMatrix.h.
References UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix().
Referenced by Make().
Member Function Documentation
Make() [1/2]
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::Make (TQuat< T > const & Rot) static nodiscard
Matrix factory.
Return an TMatrix<T> so we don't have type conversion issues in expressions.
Definition at line 70 of file RotationMatrix.h.
References UE::Math::TVector< T >::ZeroVector.
Make() [2/2]
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::Make (TRotator< T > const & Rot) inline static nodiscard
Matrix factory.
Return an TMatrix<T> so we don't have type conversion issues in expressions.
Definition at line 33 of file RotationMatrix.h.
References TRotationMatrix().
Referenced by ToMatrix(), and ToMatrix().
MakeFromX()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromX (TVector< T > const & XAxis) static nodiscard
Builds a rotation matrix given only a XAxis.
Y and Z are unspecified but will be orthonormal. XAxis need not be normalized.
Definition at line 76 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromXY()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromXY (TVector< T > const & XAxis, TVector< T > const & YAxis) static nodiscard
Builds a matrix with given X and Y axes.
X will remain fixed, Y may be changed minimally to enforce orthogonality. Z will be computed. Inputs need not be normalized.
Definition at line 118 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), FMath::IsNearlyEqual(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromXZ()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromXZ (TVector< T > const & XAxis, TVector< T > const & ZAxis) static nodiscard
Builds a matrix with given X and Z axes.
X will remain fixed, Z may be changed minimally to enforce orthogonality. Y will be computed. Inputs need not be normalized.
Definition at line 137 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), FMath::IsNearlyEqual(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromY()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromY (TVector< T > const & YAxis) static nodiscard
Builds a rotation matrix given only a YAxis.
X and Z are unspecified but will be orthonormal. YAxis need not be normalized.
Definition at line 90 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromYX()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromYX (TVector< T > const & YAxis, TVector< T > const & XAxis) static nodiscard
Builds a matrix with given Y and X axes.
Y will remain fixed, X may be changed minimally to enforce orthogonality. Z will be computed. Inputs need not be normalized.
Definition at line 156 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), FMath::IsNearlyEqual(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromYZ()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromYZ (TVector< T > const & YAxis, TVector< T > const & ZAxis) static nodiscard
Builds a matrix with given Y and Z axes.
Y will remain fixed, Z may be changed minimally to enforce orthogonality. X will be computed. Inputs need not be normalized.
Definition at line 175 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), FMath::IsNearlyEqual(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromZ()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromZ (TVector< T > const & ZAxis) static nodiscard
Builds a rotation matrix given only a ZAxis.
X and Y are unspecified but will be orthonormal. ZAxis need not be normalized.
Definition at line 104 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromZX()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromZX (TVector< T > const & ZAxis, TVector< T > const & XAxis) static nodiscard
Builds a matrix with given Z and X axes.
Z will remain fixed, X may be changed minimally to enforce orthogonality. Y will be computed. Inputs need not be normalized.
Definition at line 194 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), FMath::IsNearlyEqual(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
MakeFromZY()
template<typename T> TMatrix< T > UE::Math::TRotationMatrix< T >::MakeFromZY (TVector< T > const & ZAxis, TVector< T > const & YAxis) static nodiscard
Builds a matrix with given Z and Y axes.
Z will remain fixed, Y may be changed minimally to enforce orthogonality. X will be computed. Inputs need not be normalized.
Definition at line 213 of file RotationMatrix.h.
References UE::Math::TVector< T >::GetSafeNormal(), FMath::IsNearlyEqual(), UE_KINDA_SMALL_NUMBER, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::ZeroVector.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/RotationMatrix.h