Unreal Engine 5.6 C++ API: Runtime/Core/Public/Async/TaskGraphInterfaces.h File Reference
TaskGraphInterfaces.h File Reference
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/Array.h"
#include "Containers/UnrealString.h"
#include "Templates/Function.h"
#include "Delegates/Delegate.h"
#include "HAL/ThreadSafeCounter.h"
#include "Containers/LockFreeList.h"
#include "Stats/Stats.h"
#include "HAL/IConsoleManager.h"
#include "HAL/Event.h"
#include "HAL/LowLevelMemTracker.h"
#include "Templates/RefCounting.h"
#include "Containers/LockFreeFixedSizeAllocator.h"
#include "Experimental/ConcurrentLinearAllocator.h"
#include "Misc/MemStack.h"
#include "Misc/Timeout.h"
#include "Templates/Atomic.h"
#include "Templates/Models.h"
#include "ProfilingDebugging/MetadataTrace.h"
#include "Async/Fundamental/Task.h"
#include "Async/TaskGraphFwd.h"
#include "Async/TaskTrace.h"
#include "Tasks/TaskPrivate.h"
#include "Async/InheritedContext.h"
Data Structures
struct ENamedThreads::FRenderThreadStatics
class FAutoConsoleTaskPriority
class FBaseGraphTask
Base class for all graph tasks, used for both TGraphTask and simple graph events.
class FCustomStatIDGraphTaskBase
Class that generalizes functionality of storing and exposing custom stat id.
class FDelegateGraphTask
Task class for more full featured delegate based tasks.
struct FFunctionGraphTask
class FGraphEventImpl
class FNullGraphTask
FNullGraphTask is a task that does nothing.
class FReturnGraphTask
FReturnGraphTask is a task used to return flow control from a named thread back to the original caller of ProcessThreadUntilRequestReturn.
class FSimpleDelegateGraphTask
Task class for simple delegate based tasks.
struct FTaskGraphBlockAllocationTag
class FTaskGraphInterface
Interface to the task graph system.
class FTriggerEventGraphTask
FTriggerEventGraphTask is a task that triggers an event.
class TFunctionGraphTaskImpl< Signature, SubsequentsMode >
Task class for lambda based tasks.
class TGraphTask< TTask >
Templated graph task that is created to execute a specific function.
struct TGraphTask< TTask >::CGetStatIdProvider
class TGraphTask< TTask >::FConstructor
This is a helper class returned from the factory.
Namespaces
namespace ENamedThreads
Forward declaration for ENamedThreads.
namespace ESubsequentsMode
Macros
#define checkThreadGraph checkSlow
Typedefs
typedef TArray< FGraphEventRef, TInlineAllocator< 4 > > FGraphEventArray
Convenience typedef for a an array a graph events.
using FGraphEventImplAllocator = TLockFreeFixedSizeAllocator_TLSCache<sizeof(FGraphEventImpl), PLATFORM_CACHE_LINE_SIZE>
Enumerations
enum ENamedThreads::Type : int32 {
ENamedThreads::UnusedAnchor = -1 , ENamedThreads::RHIThread , ENamedThreads::GameThread , ENamedThreads::ActualRenderingThread = GameThread + 1 ,
ENamedThreads::AnyThread = 0xff , ENamedThreads::MainQueue = 0x000 , ENamedThreads::LocalQueue = 0x100 , ENamedThreads::NumQueues = 2 ,
ENamedThreads::ThreadIndexMask = 0xff , ENamedThreads::QueueIndexMask = 0x100 , ENamedThreads::QueueIndexShift = 8 , ENamedThreads::NormalTaskPriority = 0x000 ,
ENamedThreads::HighTaskPriority = 0x200 , ENamedThreads::NumTaskPriorities = 2 , ENamedThreads::TaskPriorityMask = 0x200 , ENamedThreads::TaskPriorityShift = 9 ,
ENamedThreads::NormalThreadPriority = 0x000 , ENamedThreads::HighThreadPriority = 0x400 , ENamedThreads::BackgroundThreadPriority = 0x800 , ENamedThreads::NumThreadPriorities = 3 ,
ENamedThreads::ThreadPriorityMask = 0xC00 , ENamedThreads::ThreadPriorityShift = 10 , ENamedThreads::GameThread_Local = GameThread | LocalQueue , ENamedThreads::ActualRenderingThread_Local = ActualRenderingThread | LocalQueue ,
ENamedThreads::AnyHiPriThreadNormalTask = AnyThread | HighThreadPriority | NormalTaskPriority , ENamedThreads::AnyHiPriThreadHiPriTask = AnyThread | HighThreadPriority | HighTaskPriority , ENamedThreads::AnyNormalThreadNormalTask = AnyThread | NormalThreadPriority | NormalTaskPriority , ENamedThreads::AnyNormalThreadHiPriTask = AnyThread | NormalThreadPriority | HighTaskPriority ,
ENamedThreads::AnyBackgroundThreadNormalTask = AnyThread | BackgroundThreadPriority | NormalTaskPriority , ENamedThreads::AnyBackgroundHiPriTask = AnyThread | BackgroundThreadPriority | HighTaskPriority
}
enum ESubsequentsMode::Type { ESubsequentsMode::TrackSubsequents , ESubsequentsMode::FireAndForget }
Functions
FGraphEventRef AnyTaskCompleted (const FGraphEventArray &GraphEvents)
DECLARE_CYCLE_STAT_EXTERN (TEXT("FReturnGraphTask"), STAT_FReturnGraphTask, STATGROUP_TaskGraphTasks, 1)
DECLARE_CYCLE_STAT_EXTERN (TEXT("FTriggerEventGraphTask"), STAT_FTriggerEventGraphTask, STATGROUP_TaskGraphTasks, 1)
DECLARE_CYCLE_STAT_EXTERN (TEXT("ParallelFor"), STAT_ParallelFor, STATGROUP_TaskGraphTasks, 1)
DECLARE_CYCLE_STAT_EXTERN (TEXT("ParallelForTask"), STAT_ParallelForTask, STATGROUP_TaskGraphTasks, 1)
DECLARE_INTRINSIC_TYPE_LAYOUT (ENamedThreads::Type)
DECLARE_STATS_GROUP (TEXT("Task Graph Tasks"), STATGROUP_TaskGraphTasks, STATCAT_Advanced)
FGraphEventImplAllocator & GetGraphEventImplAllocator ()
FORCEINLINE int32 ENamedThreads::GetQueueIndex (Type ThreadAndIndex)
FORCEINLINE Type ENamedThreads::GetRenderThread ()
FORCEINLINE Type ENamedThreads::GetRenderThread_Local ()
FORCEINLINE int32 ENamedThreads::GetTaskPriority (Type ThreadAndIndex)
FORCEINLINE Type ENamedThreads::GetThreadIndex (Type ThreadAndIndex)
FORCEINLINE int32 ENamedThreads::GetThreadPriorityIndex (Type ThreadAndIndex)
TArray< TaskTrace::FId > GetTraceIds (const FGraphEventArray &Tasks)
returns trace IDs of given tasks
FORCEINLINE Type ENamedThreads::SetPriorities (Type ThreadAndIndex, int32 PriorityIndex, bool bHiPri)
FORCEINLINE Type ENamedThreads::SetPriorities (Type ThreadAndIndex, Type ThreadPriority, Type TaskPriority)
FORCEINLINE void ENamedThreads::SetRenderThread (Type Thread)
FORCEINLINE void ENamedThreads::SetRenderThread_Local (Type Thread)
FORCEINLINE Type ENamedThreads::SetTaskPriority (Type ThreadAndIndex, Type TaskPriority)
FORCEINLINE Type ENamedThreads::SetThreadPriority (Type ThreadAndIndex, Type ThreadPriority)
int32 WaitForAnyTaskCompleted (const FGraphEventArray &GraphEvents, FTimespan Timeout=FTimespan::MaxValue())
Variables
int32 ENamedThreads::bHasBackgroundThreads
int32 ENamedThreads::bHasHighPriorityThreads
Macro Definition Documentation
checkThreadGraph
#define checkThreadGraph checkSlow
Definition at line 43 of file TaskGraphInterfaces.h.
Referenced by FReturnGraphTask::FReturnGraphTask(), and FReturnGraphTask::DoTask().
Typedef Documentation
FGraphEventArray
typedef TArray<FGraphEventRef, TInlineAllocator<4> > FGraphEventArray
Convenience typedef for a an array a graph events.
Definition at line 268 of file TaskGraphInterfaces.h.
FGraphEventImplAllocator
using FGraphEventImplAllocator = TLockFreeFixedSizeAllocator_TLSCache<sizeof(FGraphEventImpl), PLATFORM_CACHE_LINE_SIZE>
Definition at line 740 of file TaskGraphInterfaces.h.
Function Documentation
AnyTaskCompleted()
FGraphEventRef AnyTaskCompleted (const FGraphEventArray & GraphEvents)
DECLARE_CYCLE_STAT_EXTERN() [1/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("FReturnGraphTask") , STAT_FReturnGraphTask , STATGROUP_TaskGraphTasks , 1)
DECLARE_CYCLE_STAT_EXTERN() [2/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("FTriggerEventGraphTask") , STAT_FTriggerEventGraphTask , STATGROUP_TaskGraphTasks , 1)
DECLARE_CYCLE_STAT_EXTERN() [3/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("ParallelFor") , STAT_ParallelFor , STATGROUP_TaskGraphTasks , 1)
DECLARE_CYCLE_STAT_EXTERN() [4/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("ParallelForTask") , STAT_ParallelForTask , STATGROUP_TaskGraphTasks , 1)
DECLARE_INTRINSIC_TYPE_LAYOUT()
DECLARE_INTRINSIC_TYPE_LAYOUT (ENamedThreads::Type)
DECLARE_STATS_GROUP()
DECLARE_STATS_GROUP (TEXT("Task Graph Tasks") , STATGROUP_TaskGraphTasks , STATCAT_Advanced)
GetGraphEventImplAllocator()
FGraphEventImplAllocator & GetGraphEventImplAllocator ()
Referenced by FGraphEventImpl::operator delete(), and FGraphEventImpl::operator new().
GetTraceIds()
TArray< TaskTrace::FId > GetTraceIds (const FGraphEventArray & Tasks)
returns trace IDs of given tasks
WaitForAnyTaskCompleted()
int32 WaitForAnyTaskCompleted (const FGraphEventArray & GraphEvents, FTimespan Timeout = FTimespan::MaxValue())
References FTimespan::MaxValue(), and Timeout.