Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Engine/Texture2DArray.cpp File Reference
Texture2DArray.cpp File Reference
#include "Engine/Texture2DArray.h"
#include "Engine/Texture2D.h"
#include "Engine/TextureMipDataProviderFactory.h"
#include "EngineLogs.h"
#include "EngineUtils.h"
#include "ImageUtils.h"
#include "Misc/ScopedSlowTask.h"
#include "RenderUtils.h"
#include "Rendering/Texture2DArrayResource.h"
#include "Streaming/Texture2DArrayStreaming.h"
#include "Streaming/Texture2DMipDataProvider_DDC.h"
#include "Streaming/TextureStreamIn.h"
#include "Streaming/Texture2DMipDataProvider_IO.h"
#include "Streaming/TextureStreamOut.h"
#include "TextureCompiler.h"
#include "UObject/AssetRegistryTagsContext.h"
#include "UObject/Package.h"
#include "UObject/StrongObjectPtr.h"
#include "ImageCoreUtils.h"
#include "AsyncCompilationHelpers.h"
#include <UE_INLINE_GENERATED_CPP_BY_NAME(Texture2DArray)>
Macros
#define LOCTEXT_NAMESPACE "UTexture2DArray"
Functions
static UTexture2DArray * GetDefaultTexture2DArray (const UTexture2DArray *Texture)
Get the optimal placeholder to use during texture compilation.
Variables
static TAutoConsoleVariable< int32 > CVarAllowTexture2DArrayAssetCreation (TEXT("r.AllowTexture2DArrayCreation"), 1, TEXT("Enable UTexture2DArray assets"), ECVF_Default)
static FAutoConsoleVariableRef CVarSupportsTexture2DArrayStreaming (TEXT("r.SupportsTexture2DArrayStreaming"), GSupportsTexture2DArrayStreaming, TEXT("Enable Support of Texture2DArray Streaming\n"))
bool GSupportsTexture2DArrayStreaming = true
Macro Definition Documentation
LOCTEXT_NAMESPACE
#define LOCTEXT_NAMESPACE "UTexture2DArray"
Definition at line 35 of file Texture2DArray.cpp.
Function Documentation
GetDefaultTexture2DArray()
UTexture2DArray * GetDefaultTexture2DArray (const UTexture2DArray * Texture) static
Get the optimal placeholder to use during texture compilation.
Definition at line 91 of file Texture2DArray.cpp.
References FImageUtils::CreateCheckerboardTexture2DArray(), TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Get(), TStrongObjectPtr< ObjectType, ReferencerNameProvider >::IsValid(), TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Reset(), and Texture.
Variable Documentation
CVarAllowTexture2DArrayAssetCreation
TAutoConsoleVariable< int32 > CVarAllowTexture2DArrayAssetCreation(TEXT("r.AllowTexture2DArrayCreation"), 1, TEXT("Enable UTexture2DArray assets"), ECVF_Default) (TEXT("r.AllowTexture2DArrayCreation") , 1 , TEXT("Enable UTexture2DArray assets") , ECVF_Default) static
CVarSupportsTexture2DArrayStreaming
FAutoConsoleVariableRef CVarSupportsTexture2DArrayStreaming(TEXT("r.SupportsTexture2DArrayStreaming"), GSupportsTexture2DArrayStreaming, TEXT("Enable Support of Texture2DArray Streaming\n")) (TEXT("r.SupportsTexture2DArrayStreaming") , GSupportsTexture2DArrayStreaming , TEXT("Enable Support of Texture2DArray Streaming\n")) static
GSupportsTexture2DArrayStreaming
bool GSupportsTexture2DArrayStreaming = true
Definition at line 38 of file Texture2DArray.cpp.