Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/Text3D/Source/Text3D/Public/Text3DTypes.h File Reference
Text3DTypes.h File Reference
#include "Misc/EnumClassFlags.h"
#include "Text3DTypes.generated.h"
Data Structures
struct FText3DFontFamily
struct FText3DStatistics
struct FText3DTypeFaceMetrics
struct FText3DWordStatistics
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Text3D
namespace UE::Text3D::Metrics
Enumerations
enum class EText3DGroupType : uint8 {
Front = 0 , Bevel = 1 , Extrude = 2 , Back = 3 ,
TypeCount = 4
}
enum class EText3DRendererFlags : uint8 {
None , Geometry = 1 << 0 , Layout = 1 << 1 , Material = 1 << 2 ,
Visibility = 1 << 3 , All = Geometry | Layout | Visibility | Material
}
Enumerate Text3D update flags based on their priority.
Functions
USTRUCT () struct FText3DMaterialKey
Used to identify a specific material type.
Variables
static constexpr float UE::Text3D::Metrics::FontDPI = 96.f
DPI used to match slate.
static constexpr float UE::Text3D::Metrics::FontSize = 64
Original value to match size across different Text3D version.
static constexpr float UE::Text3D::Metrics::FontSizeInverse = 1.0f / FontSize
Scale used to transform freetype face result to get normalized values.
static constexpr float UE::Text3D::Metrics::SlateFontSize = 48
Value used to match size across Text3D implementation.
Enumeration Type Documentation
EText3DGroupType
enum class EText3DGroupType : uint8 strong
Enumerator
Front
Bevel
Extrude
Back
TypeCount
Definition at line 63 of file Text3DTypes.h.
EText3DRendererFlags
enum class EText3DRendererFlags : uint8 strong
Enumerate Text3D update flags based on their priority.
Enumerator
None
Geometry
Update whole geometry for text.
Layout
Update layout for characters (transform)
Material
Update materials slots.
Visibility
Update visibility/lighting properties.
All
Update everything.
Definition at line 9 of file Text3DTypes.h.
Function Documentation
USTRUCT()
USTRUCT ()
Used to identify a specific material type.
Definition at line 143 of file Text3DTypes.h.
References GENERATED_BODY, GetTypeHash(), HashCombineFast(), operator!=(), operator==(), Other, and UPROPERTY.