Unreal Engine 5.6 C++ API: Runtime/Core/Public/Math/TransformCalculus2D.h File Reference
TransformCalculus2D.h File Reference
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "Math/UnrealMathUtility.h"
#include "Math/Vector2D.h"
#include "Math/TransformCalculus.h"
#include <type_traits>
Data Structures
struct ConcatenateRules< double, TMatrix2x2< T > >
struct ConcatenateRules< double, TScale2< T > >
struct ConcatenateRules< float, TMatrix2x2< T > >
Concatenation rules for Matrix2x2 and any other type,.
struct ConcatenateRules< float, TScale2< T > >
concatenation rules for 2D scales.
struct ConcatenateRules< std::enable_if_t<!TransformCalculusHelper::TIsTransform2< TransformType >::Value, FTransform2d >, TransformType >
struct ConcatenateRules< std::enable_if_t<!TransformCalculusHelper::TIsTransform2< TransformType >::Value, FTransform2f >, TransformType >
Partial specialization of ConcatenateRules for FTransform2D and any other type via Upcast to FTransform2D first.
struct ConcatenateRules< TMatrix2x2< T >, double >
struct ConcatenateRules< TMatrix2x2< T >, float >
struct ConcatenateRules< TMatrix2x2< T >, TQuat2< T > >
struct ConcatenateRules< TMatrix2x2< T >, TScale2< T > >
struct ConcatenateRules< TMatrix2x2< T >, TShear2< T > >
struct ConcatenateRules< TQuat2< T >, TMatrix2x2< T > >
struct ConcatenateRules< TQuat2< T >, TScale2< T > >
struct ConcatenateRules< TQuat2< T >, TShear2< T > >
struct ConcatenateRules< TransformType, std::enable_if_t<!TransformCalculusHelper::TIsTransform2< TransformType >::Value, FTransform2d > >
struct ConcatenateRules< TransformType, std::enable_if_t<!TransformCalculusHelper::TIsTransform2< TransformType >::Value, FTransform2f > >
struct ConcatenateRules< TScale2< T >, double >
struct ConcatenateRules< TScale2< T >, float >
concatenation rules for 2D scales.
struct ConcatenateRules< TScale2< T >, TMatrix2x2< T > >
struct ConcatenateRules< TScale2< T >, TQuat2< T > >
struct ConcatenateRules< TScale2< T >, TShear2< T > >
Concatenation rules for 2x2 transform types.
struct ConcatenateRules< TShear2< T >, TMatrix2x2< T > >
struct ConcatenateRules< TShear2< T >, TQuat2< T > >
struct ConcatenateRules< TShear2< T >, TScale2< T > >
struct TIsPODType< FTransform2d >
struct TIsPODType< FTransform2f >
class TMatrix2x2< T >
2x2 generalized matrix.
class TQuat2< T >
Represents a 2D rotation as a complex number (analagous to quaternions).
struct TransformCalculusHelper::TIsTransform2< T >
struct TransformCalculusHelper::TIsTransform2< FTransform2d >
struct TransformCalculusHelper::TIsTransform2< FTransform2f >
class TScale2< T >
Represents a 2D non-uniform scale (to disambiguate from an FVector2D, which is used for translation)
class TShear2< T >
Represents a 2D shear: [1 YY] [XX 1] XX represents a shear parallel to the X axis.
class TTransform2< T >
Support for generalized 2D affine transforms.
Namespaces
namespace TransformCalculusHelper
Helper to determine if a type is based on TTransform2.
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Math
Implements an axis-aligned box.
Typedefs
typedef FMatrix2x2f FMatrix2x2
typedef TMatrix2x2< double > FMatrix2x2d
typedef TMatrix2x2< float > FMatrix2x2f
Base typedefs.
typedef FQuat2f FQuat2D
typedef TQuat2< double > FQuat2d
typedef TQuat2< float > FQuat2f
Base typedefs.
typedef FScale2f FScale2D
typedef TScale2< double > FScale2d
typedef TScale2< float > FScale2f
Base typedefs.
typedef FShear2f FShear2D
typedef TShear2< double > FShear2d
typedef TShear2< float > FShear2f
Base typedefs.
typedef FTransform2f FTransform2D
typedef TTransform2< double > FTransform2d
typedef TTransform2< float > FTransform2f
Core typedefs.
Functions
template<typename T, typename V>
TTransform2< T > Concatenate (const TMatrix2x2< T > &Transform, const UE::Math::TVector2< V > &Translation)
Specialization for concatenating 2D generalized transform and 2D Translation.
template<typename T, typename V>
TTransform2< T > Concatenate (const TQuat2< T > &Rot, const UE::Math::TVector2< V > &Translation)
Specialization for concatenating 2D Rotation and 2D Translation.
template<typename T, typename V>
TTransform2< T > Concatenate (const TScale2< T > &Scale, const UE::Math::TVector2< V > &Translation)
Specialization for concatenating a 2D scale and 2D Translation.
template<typename T, typename V>
TTransform2< T > Concatenate (const TShear2< T > &Shear, const UE::Math::TVector2< V > &Translation)
Specialization for concatenating a 2D shear and 2D Translation.
template<typename T, typename V>
TTransform2< T > Concatenate (const TTransform2< T > &Transform, const UE::Math::TVector2< V > &Translation)
Specialization for concatenating transform and 2D Translation.
template<typename T, typename V>
TTransform2< T > Concatenate (const UE::Math::TVector2< V > &Translation, const TMatrix2x2< T > &Transform)
Specialization for concatenating 2D Translation and 2D generalized transform.
template<typename T, typename V>
TTransform2< T > Concatenate (const UE::Math::TVector2< V > &Translation, const TQuat2< T > &Rot)
Specialization for concatenating 2D Translation and 2D Rotation.
template<typename T, typename V>
TTransform2< T > Concatenate (const UE::Math::TVector2< V > &Translation, const TScale2< T > &Scale)
Specialization for concatenating a 2D Translation and 2D scale.
template<typename T, typename V>
TTransform2< T > Concatenate (const UE::Math::TVector2< V > &Translation, const TShear2< T > &Shear)
Specialization for concatenating a 2D Translation and 2D shear.
template<typename T, typename V>
TTransform2< T > Concatenate (const UE::Math::TVector2< V > &Translation, const TTransform2< T > &Transform)
Specialization for concatenating 2D Translation and transform.
template<typename T>
UE::Math::TVector2< T > UE::Math::Concatenate (const UE::Math::TVector2< T > &LHS, const UE::Math::TVector2< T > &RHS)
Specialization for concatenating two 2D Translations.
template<typename T>
UE::Math::TVector2< T > Inverse (const UE::Math::TVector2< T > &Transform)
Specialization for inverting a 2D translation.
template<typename T>
UE::Math::TVector2< T > TransformPoint (const UE::Math::TVector2< T > &Transform, const UE::Math::TVector2< T > &Point)
Specialization for TVector2 Translation.
template<typename PositionType>
UE::Math::TVector2< PositionType > TransformPoint (double Transform, const UE::Math::TVector2< PositionType > &Point)
template<typename PositionType>
UE::Math::TVector2< PositionType > TransformPoint (float Transform, const UE::Math::TVector2< PositionType > &Point)
Specialization for uniform Scale.
template<typename T>
const UE::Math::TVector2< T > & TransformVector (const UE::Math::TVector2< T > &Transform, const UE::Math::TVector2< T > &Vector)
Specialization for FVector2D Translation (does nothing).
template<typename VectorType>
UE::Math::TVector2< VectorType > TransformVector (double Transform, const UE::Math::TVector2< VectorType > &Vector)
template<typename VectorType>
UE::Math::TVector2< VectorType > TransformVector (float Transform, const UE::Math::TVector2< VectorType > &Vector)
Specialization for uniform Scale.
Typedef Documentation
FMatrix2x2
typedef FMatrix2x2f FMatrix2x2
Definition at line 629 of file TransformCalculus2D.h.
FMatrix2x2d
typedef TMatrix2x2<double> FMatrix2x2d
Definition at line 628 of file TransformCalculus2D.h.
FMatrix2x2f
typedef TMatrix2x2<float> FMatrix2x2f
Base typedefs.
Definition at line 627 of file TransformCalculus2D.h.
FQuat2D
typedef FQuat2f FQuat2D
Definition at line 395 of file TransformCalculus2D.h.
FQuat2d
typedef TQuat2<double> FQuat2d
Definition at line 394 of file TransformCalculus2D.h.
FQuat2f
typedef TQuat2<float> FQuat2f
Base typedefs.
Definition at line 393 of file TransformCalculus2D.h.
FScale2D
typedef FScale2f FScale2D
Definition at line 182 of file TransformCalculus2D.h.
FScale2d
typedef TScale2<double> FScale2d
Definition at line 181 of file TransformCalculus2D.h.
FScale2f
typedef TScale2<float> FScale2f
Base typedefs.
Definition at line 180 of file TransformCalculus2D.h.
FShear2D
typedef FShear2f FShear2D
Definition at line 291 of file TransformCalculus2D.h.
FShear2d
typedef TShear2<double> FShear2d
Definition at line 290 of file TransformCalculus2D.h.
FShear2f
typedef TShear2<float> FShear2f
Base typedefs.
Definition at line 289 of file TransformCalculus2D.h.
FTransform2D
typedef FTransform2f FTransform2D
Definition at line 858 of file TransformCalculus2D.h.
FTransform2d
typedef TTransform2<double> FTransform2d
Definition at line 857 of file TransformCalculus2D.h.
FTransform2f
typedef TTransform2<float> FTransform2f
Core typedefs.
Definition at line 856 of file TransformCalculus2D.h.
Function Documentation
Concatenate() [1/10]
template<typename T, typename V> TTransform2< T > Concatenate (const TMatrix2x2< T > & Transform, const UE::Math::TVector2< V > & Translation) inline
Specialization for concatenating 2D generalized transform and 2D Translation.
Definition at line 893 of file TransformCalculus2D.h.
References Transform, and Translation.
Concatenate() [2/10]
template<typename T, typename V> TTransform2< T > Concatenate (const TQuat2< T > & Rot, const UE::Math::TVector2< V > & Translation) inline
Specialization for concatenating 2D Rotation and 2D Translation.
Definition at line 886 of file TransformCalculus2D.h.
References Translation.
Concatenate() [3/10]
template<typename T, typename V> TTransform2< T > Concatenate (const TScale2< T > & Scale, const UE::Math::TVector2< V > & Translation) inline
Specialization for concatenating a 2D scale and 2D Translation.
Definition at line 872 of file TransformCalculus2D.h.
References Scale, and Translation.
Concatenate() [4/10]
template<typename T, typename V> TTransform2< T > Concatenate (const TShear2< T > & Shear, const UE::Math::TVector2< V > & Translation) inline
Specialization for concatenating a 2D shear and 2D Translation.
Definition at line 879 of file TransformCalculus2D.h.
References Translation.
Concatenate() [5/10]
template<typename T, typename V> TTransform2< T > Concatenate (const TTransform2< T > & Transform, const UE::Math::TVector2< V > & Translation) inline
Specialization for concatenating transform and 2D Translation.
Definition at line 900 of file TransformCalculus2D.h.
References Concatenate(), Transform, and Translation.
Concatenate() [6/10]
template<typename T, typename V> TTransform2< T > Concatenate (const UE::Math::TVector2< V > & Translation, const TMatrix2x2< T > & Transform) inline
Specialization for concatenating 2D Translation and 2D generalized transform.
See docs for TTransform2<T>::Inverse for details on how this math is derived.
Definition at line 928 of file TransformCalculus2D.h.
References Transform, TransformPoint(), and Translation.
Concatenate() [7/10]
template<typename T, typename V> TTransform2< T > Concatenate (const UE::Math::TVector2< V > & Translation, const TQuat2< T > & Rot) inline
Specialization for concatenating 2D Translation and 2D Rotation.
Definition at line 921 of file TransformCalculus2D.h.
References TransformPoint(), and Translation.
Concatenate() [8/10]
template<typename T, typename V> TTransform2< T > Concatenate (const UE::Math::TVector2< V > & Translation, const TScale2< T > & Scale) inline
Specialization for concatenating a 2D Translation and 2D scale.
Definition at line 907 of file TransformCalculus2D.h.
References Scale, TransformPoint(), and Translation.
Concatenate() [9/10]
template<typename T, typename V> TTransform2< T > Concatenate (const UE::Math::TVector2< V > & Translation, const TShear2< T > & Shear) inline
Specialization for concatenating a 2D Translation and 2D shear.
Definition at line 914 of file TransformCalculus2D.h.
References TransformPoint(), and Translation.
Concatenate() [10/10]
template<typename T, typename V> TTransform2< T > Concatenate (const UE::Math::TVector2< V > & Translation, const TTransform2< T > & Transform) inline
Specialization for concatenating 2D Translation and transform.
See docs for TTransform2<T>::Inverse for details on how this math is derived.
Definition at line 935 of file TransformCalculus2D.h.
References Concatenate(), Transform, TransformPoint(), and Translation.
Inverse()
template<typename T> UE::Math::TVector2< T > Inverse (const UE::Math::TVector2< T > & Transform) inline nodiscard
Specialization for inverting a 2D translation.
Definition at line 55 of file TransformCalculus2D.h.
References Transform.
TransformPoint() [1/3]
template<typename T> UE::Math::TVector2< T > TransformPoint (const UE::Math::TVector2< T > & Transform, const UE::Math::TVector2< T > & Point) inline nodiscard
Specialization for TVector2 Translation.
Definition at line 62 of file TransformCalculus2D.h.
References Point, and Transform.
TransformPoint() [2/3]
template<typename PositionType> UE::Math::TVector2< PositionType > TransformPoint (double Transform, const UE::Math::TVector2< PositionType > & Point) inline nodiscard
Definition at line 91 of file TransformCalculus2D.h.
References Point, and Transform.
TransformPoint() [3/3]
template<typename PositionType> UE::Math::TVector2< PositionType > TransformPoint (float Transform, const UE::Math::TVector2< PositionType > & Point) inline nodiscard
Specialization for uniform Scale.
Definition at line 85 of file TransformCalculus2D.h.
References Point, and Transform.
TransformVector() [1/3]
template<typename T> const UE::Math::TVector2< T > & TransformVector (const UE::Math::TVector2< T > & Transform, const UE::Math::TVector2< T > & Vector) inline nodiscard
Specialization for FVector2D Translation (does nothing).
Definition at line 69 of file TransformCalculus2D.h.
References Transform, and Vector.
TransformVector() [2/3]
template<typename VectorType> UE::Math::TVector2< VectorType > TransformVector (double Transform, const UE::Math::TVector2< VectorType > & Vector) inline nodiscard
Definition at line 106 of file TransformCalculus2D.h.
References Transform, and Vector.
TransformVector() [3/3]
template<typename VectorType> UE::Math::TVector2< VectorType > TransformVector (float Transform, const UE::Math::TVector2< VectorType > & Vector) inline nodiscard
Specialization for uniform Scale.
Definition at line 100 of file TransformCalculus2D.h.
References Transform, and Vector.