Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/TypeCompatibleBytes.h File Reference
TypeCompatibleBytes.h File Reference
#include "CoreTypes.h"
#include <string.h>
#include <new>
#include <type_traits>
Data Structures
struct TAlignedBytes< Size, Alignment >
Used to declare an untyped array of data with compile-time alignment.
struct TTypeCompatibleBytes< ElementType >
An untyped array of data with compile-time alignment and size derived from another type.
struct TTypeCompatibleBytes< T & >
struct TTypeCompatibleBytes< void >
Functions
template<typename ToType, typename FromType, std::enable_if_t< sizeof(ToType)==sizeof(FromType) &&std::is_trivially_copyable_v< ToType > &&std::is_trivially_copyable_v< FromType > > * = nullptr>
ToType BitCast (const FromType &From)
Function Documentation
BitCast()
template<typename ToType, typename FromType, std::enable_if_t< sizeof(ToType)==sizeof(FromType) &&std::is_trivially_copyable_v< ToType > &&std::is_trivially_copyable_v< FromType > > * = nullptr> ToType BitCast (const FromType & From) inline
Definition at line 167 of file TypeCompatibleBytes.h.
Referenced by FFloat3PackedSE::FFloat3PackedSE(), FReferenceToken::FReferenceToken(), FReferenceToken::FReferenceToken(), FReferenceToken::FReferenceToken(), FReferenceToken::FReferenceToken(), FReferenceToken::FReferenceToken(), Verse::TPtrVariant< Ts >::TPtrVariant(), Verse::TPtrVariant< Ts >::As(), FReferenceToken::AsGCObject(), FReferenceToken::AsGCObjectInfo(), FReferenceToken::AsGCVerseCellInfo(), FReferenceToken::AsObject(), FReferenceToken::AsVerseCell(), Verse::GetTypeHash(), FGenericPlatformMath::IsFinite(), FGenericPlatformMath::IsFinite(), FGenericPlatformMath::IsNaN(), FGenericPlatformMath::IsNaN(), FGenericPlatformMath::IsNegativeOrNegativeZero(), FGenericPlatformMath::IsNegativeOrNegativeZero(), ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::operator UPTRINT(), FFloat3PackedSE::ToLinearColor(), and USTRUCT().