Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/TypeHash.h File Reference
TypeHash.h File Reference
#include "CoreTypes.h"
#include "Templates/Requires.h"
#include "Misc/Crc.h"
#include <stdint.h>
#include <type_traits>
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Private
The global memory allocator.
Functions
template<typename BuilderType, typename ArgType>
void DispatchAppendHash (BuilderType &Builder, const ArgType &Arg)
template<typename T>
uint32 GetArrayHash (const T *Ptr, uint64 Size, uint32 PreviousHash=0)
template<typename ScalarType, std::enable_if_t< std::is_scalar_v< ScalarType > &&!std::is_same_v< ScalarType, TCHAR * > &&!std::is_same_v< ScalarType, const TCHAR * > > * = nullptr>
uint32 GetTypeHash (ScalarType Value)
template<typename T>
FORCEINLINE uint32 GetTypeHashHelper (const T &V)
template<typename... Types UE_REQUIRES>
FORCEINLINE constexpr uint32 HashCombine (uint32 A, Types... Vals)
constexpr uint32 HashCombine (uint32 A, uint32 C)
Combines two hash values to get a third.
template<typename... Types UE_REQUIRES>
FORCEINLINE constexpr uint32 HashCombineFast (uint32 A, Types... Vals)
constexpr uint32 HashCombineFast (uint32 A, uint32 B)
Combines two hash values to get a third.
FORCEINLINE uint32 UE::Private::MurmurFinalize32 (uint32 Hash)
uint32 PointerHash (const void *Key)
uint32 PointerHash (const void *Key, uint32 C)
template<typename T, std::enable_if_t< std::is_same_v< const T, const TCHAR > > * = nullptr>
UE_DEPRECATED (5.3, "Hashing TCHAR arrays is deprecated - use PointerHash() to force a conversion to a pointer or FCrc::Strihash_DEPRECATED to do a string hash, or use TStringPointerSetKeyFuncs_DEPRECATED or TStringPointerMapKeyFuncs_DEPRECATED as keyfuncs for a TSet or TMap respectively") inline uint32 GetTypeHash(T *Value)
template<typename T, uint32 N, std::enable_if_t<!std::is_same_v< const T, const TCHAR > > * = nullptr>
UE_DEPRECATED (all, "Hashing arrays is deprecated - use PointerHash() instead to force a conversion to a pointer or GetArrayHash to hash the array contents") inline uint32 GetTypeHash(T(&Array)[N])
Function Documentation
DispatchAppendHash()
template<typename BuilderType, typename ArgType> void DispatchAppendHash (BuilderType & Builder, const ArgType & Arg) inline
Definition at line 219 of file TypeHash.h.
References AppendHash().
Referenced by UE::FPropertyPathNameTree::FKey::AppendHash.
GetArrayHash()
template<typename T> uint32 GetArrayHash (const T * Ptr, uint64 Size, uint32 PreviousHash = 0) inline nodiscard
Definition at line 200 of file TypeHash.h.
References GetTypeHash(), HashCombineFast(), and TSequenceHistory< HistorySize >::Size.
Referenced by USTRUCT().
GetTypeHash()
template<typename ScalarType, std::enable_if_t< std::is_scalar_v< ScalarType > &&!std::is_same_v< ScalarType, TCHAR * > &&!std::is_same_v< ScalarType, const TCHAR * > > * = nullptr> uint32 GetTypeHash (ScalarType Value) inline nodiscard
Definition at line 118 of file TypeHash.h.
References GetTypeHash(), High, Low, PointerHash(), and Value.
Referenced by GetArrayHash(), GetTypeHash(), and GetTypeHashHelper().
GetTypeHashHelper()
template<typename T> FORCEINLINE uint32 GetTypeHashHelper (const T & V) nodiscard
Definition at line 215 of file TypeHash.h.
References FORCEINLINE, and GetTypeHash().
Referenced by UE::Core::Private::Tuple::TGetTupleHashHelper< ArgToCombine, ArgCount >::Do(), FInternetAddrDemo::GetConstTypeHash(), UScriptStruct::TCppStructOps< CPPSTRUCT >::GetStructTypeHash(), FRichCurveEditInfoTemplate< FRealCurve * >::GetTypeHash(), and TNotNull< T * >::GetTypeHash.
HashCombine() [1/2]
template<typename... Types UE_REQUIRES> FORCEINLINE constexpr uint32 HashCombine (uint32 A, Types... Vals) nodiscard constexpr
Definition at line 57 of file TypeHash.h.
References A, FORCEINLINE, and HashCombine().
HashCombine() [2/2]
uint32 HashCombine (uint32 A, uint32 C) inline nodiscard constexpr
Combines two hash values to get a third.
Note - this function is not commutative.
This function cannot change for backward compatibility reasons. You may want to choose HashCombineFast for a better in-memory hash combining function.
Definition at line 36 of file TypeHash.h.
References A, and B.
Referenced by FPropertyLocalizationDataGatherer::FObjectAndGatherFlags::FObjectAndGatherFlags(), FSlateFontKey::FSlateFontKey(), FSlateVectorGraphicsCache::FVectorCacheKey::FVectorCacheKey(), FSlateClippingZone::ComputeHash(), FRigVMCallstack::GetEntryTypeHash(), FAllocatedVTDescription::GetTypeHash, FAnalogNavigationKey::GetTypeHash, FAssetData::GetTypeHash, FAssetIdentifier::GetTypeHash, FCachedShapedTextKey::GetTypeHash, FCoreRedirectObjectName::GetTypeHash, FEdGraphNodeHandle::GetTypeHash, FEdGraphPinHandle::GetTypeHash, FFieldPath::GetTypeHash, FFolder::GetTypeHash, FFrameRate::GetTypeHash, FGCObjectInfo::GetTypeHash, FGeometryIdentifier::GetTypeHash, FGraphPinHandle::GetTypeHash, FISMClientInstanceId::GetTypeHash, FLayoutBlockTextContext::GetTypeHash, FMaterialListItem::GetTypeHash, FMaterialPSOPrecacheParams::GetTypeHash, FMemoryImageMaterialParameterInfo::GetTypeHash, FMovieSceneBlendChannelID::GetTypeHash, FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey::GetTypeHash, FNavigationElementHandle::GetTypeHash, FObjectKey::GetTypeHash, FOperatorFunctionID::GetTypeHash, FPrimaryAssetId::GetTypeHash, FPropertyVisitorInfo::GetTypeHash, FPSOPrecacheVertexFactoryData::GetTypeHash, FPublicExportKey::GetTypeHash, FRDGBufferDesc::GetTypeHash, FRDGBufferSRVDesc::GetTypeHash, FRDGBufferUAVDesc::GetTypeHash, FRDGTextureSRVDesc::GetTypeHash, FRDGTextureUAVDesc::GetTypeHash, FRedirectCollector::FSoftObjectPathProperty::GetTypeHash, FRetargetSourceCachedDataKey::GetTypeHash, FRichCurveEditInfoTemplate< FRealCurve * >::GetTypeHash(), FRigVMBranchInfoKey::GetTypeHash, FRigVMCompilerWorkData::FFunctionRegisterData::GetTypeHash, FRigVMExplorerElementKey::GetTypeHash, FRigVMNameOp::GetTypeHash(), FRigVMNameOp::GetTypeHash, FRigVMPropertyPath::GetTypeHash, FSetProfileRequest::GetTypeHash, FShaderId::GetTypeHash, FShaderKey::GetTypeHash, FShapedTextContext::GetTypeHash, FSharedPersistentDataKey::GetTypeHash, FSlateRect::GetTypeHash, FSMInstanceElementId::GetTypeHash, FSMInstanceId::GetTypeHash, FStructTypeBitSet::FConstBitSetContainer::GetTypeHash, FTextId::GetTypeHash, FTextLocation::GetTypeHash, FTextRange::GetTypeHash, FUniformParameterOverrides::FNumericParameterKey::GetTypeHash, FUniformParameterOverrides::FTextureParameterKey::GetTypeHash, GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), Metasound::Frontend::FConverterNodeClassRegistryKey::GetTypeHash, TInterval< float >::GetTypeHash, TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::GetTypeHash, TShaderTypePermutation< FShaderType >::GetTypeHash, TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeHash, UE::Math::GetTypeHash(), UE::Math::GetTypeHash(), UE::MovieScene::FComplexInclusivityFilter::GetTypeHash, UE::MovieScene::FComponentMaterialKey::GetTypeHash, UE::MovieScene::FEntityGroupID::GetTypeHash, UE::MovieScene::FHierarchicalBlendTarget::GetTypeHash, UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FKeyType::GetTypeHash, UE::SequenceNavigator::FNavigationToolExtender::FIconCustomizationKey::GetTypeHash, UE::Transaction::FPersistentObjectRef::GetTypeHash, HashCombine(), TextKeyUtil::HashString(), FShaderCompileJobKey::MakeHash(), FShaderPipelineCompileJobKey::MakeHash(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
HashCombineFast() [1/2]
template<typename... Types UE_REQUIRES> FORCEINLINE constexpr uint32 HashCombineFast (uint32 A, Types... Vals) nodiscard constexpr
Definition at line 82 of file TypeHash.h.
References A, FORCEINLINE, and HashCombineFast().
HashCombineFast() [2/2]
uint32 HashCombineFast (uint32 A, uint32 B) inline nodiscard constexpr
Combines two hash values to get a third.
Note - this function is not commutative.
WARNING! This function is subject to change and should only be used for creating combined hash values which don't leave the running process, e.g. GetTypeHash() overloads.
Definition at line 74 of file TypeHash.h.
References A, and B.
Referenced by FHashBuilder::Append(), FHashBuilder::AppendRaw(), UE::Core::Private::Tuple::TGetTupleHashHelper< ArgToCombine, ArgCount >::Do(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), GetArrayHash(), TActorDescList< DescType >::FActorGuidKeyFuncs::GetKeyHash(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeSharedStateId(), FAudioChunkCache::FCacheMissEntry::GetTypeHash, FAudioChunkCache::FChunkKey::GetTypeHash, FRDGBarrierBatchBeginId::GetTypeHash, FSkinWeightProfileStack::GetTypeHash, FSoftObjectPath::GetTypeHash, FTopLevelAssetPath::GetTypeHash, GetTypeHash(), GetTypeHash(), GetTypeHash(), Metasound::FOperatorSettings::GetTypeHash, Metasound::Frontend::FGraphClassRegistryKey::GetTypeHash, Metasound::Frontend::FNamedEdge::GetTypeHash, Metasound::Frontend::FNodeClassRegistryKey::GetTypeHash, Metasound::Frontend::IMetaSoundAssetManager::FAssetRef::GetTypeHash, UE::ConfigAccessTracking::FConfigAccessData::GetTypeHash, UE::FPropertyPathNameTree::FKey::GetTypeHash, UE::Math::GetTypeHash(), UE::Math::GetTypeHash(), UE::Net::GetTypeHash(), HashCombineFast(), PointerHash(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
PointerHash() [1/2]
uint32 PointerHash (const void * Key) inline nodiscard
Definition at line 91 of file TypeHash.h.
References Key, and UE::Private::MurmurFinalize32().
Referenced by FMaterialExpressionKey::GetTypeHash, FMaterialPSOPrecacheParams::GetTypeHash, FPSOPrecacheVertexFactoryData::GetTypeHash, FRichCurveEditInfoTemplate< FRealCurve * >::GetTypeHash(), FSharedBuffer::GetTypeHash, FUniqueBuffer::GetTypeHash, FWeakSharedBuffer::GetTypeHash, GetTypeHash(), TNonNullPtr< T >::GetTypeHash, TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeHash, Verse::GetTypeHash(), PointerHash(), SHADER_PARAMETER_TEXTURE(), UE_DEPRECATED(), and USTRUCT().
PointerHash() [2/2]
uint32 PointerHash (const void * Key, uint32 C) inline nodiscard
Definition at line 99 of file TypeHash.h.
References HashCombineFast(), Key, and PointerHash().
UE_DEPRECATED() [1/2]
template<typename T, std::enable_if_t< std::is_same_v< const T, const TCHAR > > * = nullptr> UE_DEPRECATED (5. 3, "Hashing TCHAR arrays is deprecated - use PointerHash() to force a conversion to a pointer or FCrc::Strihash_DEPRECATED to do a string hash, or use TStringPointerSetKeyFuncs_DEPRECATED or TStringPointerMapKeyFuncs_DEPRECATED as keyfuncs for a TSet or TMap respectively")
Definition at line 191 of file TypeHash.h.
References GetTypeHash(), FCrc::Strihash_DEPRECATED(), and Value.
UE_DEPRECATED() [2/2]
template<typename T, uint32 N, std::enable_if_t<!std::is_same_v< const T, const TCHAR > > * = nullptr> UE_DEPRECATED (all , "Hashing arrays is deprecated - use PointerHash() instead to force a conversion to a pointer or GetArrayHash to hash the array contents"))[N] &
Definition at line 181 of file TypeHash.h.
References Array, GetTypeHash(), and PointerHash().