Unreal Engine 5.6 C++ API: FVirtualTextureLocalTileRequest Union Reference
FVirtualTextureLocalTileRequest Union Reference
Identifies a VT tile request : a VT tile, along with priority information for processing this request.
#include "VirtualTexturing.h"
Public Member Functions
FVirtualTextureLocalTileRequest ()
FVirtualTextureLocalTileRequest (const FVirtualTextureLocalTile &InTile, EVTProducerPriority InProducerPriority, EVTInvalidatePriority InInvalidatePriority)
uint64 GetIdentity () const
EVTInvalidatePriority GetInvalidatePriority () const
uint16 GetMurmurHash () const
EVTProducerPriority GetProducerPriority () const
FVirtualTextureLocalTile GetTile () const
FVirtualTextureLocalTileRequest & MergeWith (const FVirtualTextureLocalTileRequest &InOther)
Data Fields
struct {
uint64 InvalidatePriority: 1
uint64 ProducerPriority: 3
uint64 TilePackedValue: 60
};
uint64 PackedValue
Private Member Functions
RENDERCORE_API void ValidatePriorities () const
Friends
uint32 GetTypeHash (const FVirtualTextureLocalTileRequest &T)
bool operator!= (const FVirtualTextureLocalTileRequest &Lhs, const FVirtualTextureLocalTileRequest &Rhs)
bool operator== (const FVirtualTextureLocalTileRequest &Lhs, const FVirtualTextureLocalTileRequest &Rhs)
Detailed Description
Identifies a VT tile request : a VT tile, along with priority information for processing this request.
Definition at line 529 of file VirtualTexturing.h.
Constructor & Destructor Documentation
FVirtualTextureLocalTileRequest() [1/2]
FVirtualTextureLocalTileRequest::FVirtualTextureLocalTileRequest () inline explicit
Definition at line 531 of file VirtualTexturing.h.
Referenced by GetTypeHash, MergeWith(), operator!=, and operator==.
FVirtualTextureLocalTileRequest() [2/2]
FVirtualTextureLocalTileRequest::FVirtualTextureLocalTileRequest (const FVirtualTextureLocalTile & InTile, EVTProducerPriority InProducerPriority, EVTInvalidatePriority InInvalidatePriority) inline explicit
Definition at line 532 of file VirtualTexturing.h.
References checkSlow, GetTile(), InvalidatePriority, PackedValue, ProducerPriority, TilePackedValue, and ValidatePriorities().
Member Function Documentation
GetIdentity()
uint64 FVirtualTextureLocalTileRequest::GetIdentity () const inline
Definition at line 570 of file VirtualTexturing.h.
References TilePackedValue.
Referenced by GetMurmurHash(), operator!=, and operator==.
GetInvalidatePriority()
EVTInvalidatePriority FVirtualTextureLocalTileRequest::GetInvalidatePriority () const inline
Definition at line 543 of file VirtualTexturing.h.
References InvalidatePriority.
GetMurmurHash()
uint16 FVirtualTextureLocalTileRequest::GetMurmurHash () const inline
Definition at line 571 of file VirtualTexturing.h.
References GetIdentity(), and MurmurFinalize64().
GetProducerPriority()
EVTProducerPriority FVirtualTextureLocalTileRequest::GetProducerPriority () const inline
Definition at line 542 of file VirtualTexturing.h.
References ProducerPriority.
GetTile()
FVirtualTextureLocalTile FVirtualTextureLocalTileRequest::GetTile () const inline
Definition at line 541 of file VirtualTexturing.h.
References TilePackedValue.
Referenced by FVirtualTextureLocalTileRequest(), and MergeWith().
MergeWith()
FVirtualTextureLocalTileRequest & FVirtualTextureLocalTileRequest::MergeWith (const FVirtualTextureLocalTileRequest & InOther) inline
Definition at line 545 of file VirtualTexturing.h.
References FVirtualTextureLocalTileRequest(), checkSlow, GetTile(), InvalidatePriority, FMath::Max, ProducerPriority, and ValidatePriorities().
ValidatePriorities()
RENDERCORE_API void FVirtualTextureLocalTileRequest::ValidatePriorities () const private
Referenced by FVirtualTextureLocalTileRequest(), and MergeWith().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FVirtualTextureLocalTileRequest & T) friend
Definition at line 569 of file VirtualTexturing.h.
References FVirtualTextureLocalTileRequest(), and GetTypeHash.
Referenced by GetTypeHash.
operator!=
bool operator!= (const FVirtualTextureLocalTileRequest & Lhs, const FVirtualTextureLocalTileRequest & Rhs) friend
Definition at line 568 of file VirtualTexturing.h.
References FVirtualTextureLocalTileRequest(), and GetIdentity().
operator==
bool operator== (const FVirtualTextureLocalTileRequest & Lhs, const FVirtualTextureLocalTileRequest & Rhs) friend
Definition at line 567 of file VirtualTexturing.h.
References FVirtualTextureLocalTileRequest(), and GetIdentity().
Field Documentation
[struct]
struct { ... } FVirtualTextureLocalTileRequest
InvalidatePriority
uint64 FVirtualTextureLocalTileRequest::InvalidatePriority
Definition at line 564 of file VirtualTexturing.h.
Referenced by FVirtualTextureLocalTileRequest(), GetInvalidatePriority(), and MergeWith().
PackedValue
uint64 FVirtualTextureLocalTileRequest::PackedValue
Definition at line 557 of file VirtualTexturing.h.
Referenced by FVirtualTextureLocalTileRequest().
ProducerPriority
uint64 FVirtualTextureLocalTileRequest::ProducerPriority
Definition at line 563 of file VirtualTexturing.h.
Referenced by FVirtualTextureLocalTileRequest(), GetProducerPriority(), and MergeWith().
TilePackedValue
uint64 FVirtualTextureLocalTileRequest::TilePackedValue
Definition at line 561 of file VirtualTexturing.h.
Referenced by FVirtualTextureLocalTileRequest(), GetIdentity(), and GetTile().
The documentation for this union was generated from the following file:
Runtime/RenderCore/Public/VirtualTexturing.h