Unreal Engine 5.6 C++ API: LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData Union Reference
LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData Union Reference
Public Member Functions
FPackedData (const FPackedData &Other, ETaskState State)
FPackedData (const TCHAR *InDebugName, ETaskPriority InPriority, ETaskState InState, ETaskFlags InFlags)
const TCHAR * GetDebugName () const
ETaskFlags GetFlags () const
ETaskPriority GetPriority () const
ETaskState GetState () const
Data Fields
struct {
uintptr_t DebugName: 53
uintptr_t Flags: 2
uintptr_t Priority: 3
uintptr_t State: 6
};
uintptr_t PackedData
Private Member Functions
constexpr FPackedData ()
FPackedData (uintptr_t InPackedData)
Friends
class FTaskBase::FPackedDataAtomic
Detailed Description
Definition at line 195 of file Task.h.
Constructor & Destructor Documentation
FPackedData() [1/4]
LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::FPackedData (uintptr_t InPackedData) inline private
Definition at line 208 of file Task.h.
References PackedData.
Referenced by FPackedData(), and FPackedData().
FPackedData() [2/4]
LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::FPackedData () inline constexpr private
Definition at line 211 of file Task.h.
References LowLevelTasks::Count, DebugName, LowLevelTasks::DefaultFlags, Flags, PLATFORM_32BITS, Priority, and State.
FPackedData() [3/4]
LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::FPackedData (const TCHAR * InDebugName, ETaskPriority InPriority, ETaskState InState, ETaskFlags InFlags) inline
Definition at line 224 of file Task.h.
References FPackedData(), checkSlow, DebugName, Flags, Priority, and State.
FPackedData() [4/4]
LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::FPackedData (const FPackedData & Other, ETaskState State) inline
Definition at line 238 of file Task.h.
References FPackedData(), GetDebugName(), GetFlags(), GetPriority(), Other, and State.
Member Function Documentation
GetDebugName()
const TCHAR * LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetDebugName () const inline
Definition at line 243 of file Task.h.
References DebugName.
Referenced by FPackedData(), and LowLevelTasks::FTask::GetInitData().
GetFlags()
ETaskFlags LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetFlags () const inline
Definition at line 258 of file Task.h.
References Flags.
Referenced by FPackedData(), LowLevelTasks::FTask::GetInitData(), and LowLevelTasks::FTask::TryCancel().
GetPriority()
ETaskPriority LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetPriority () const inline
Definition at line 248 of file Task.h.
References Priority.
Referenced by FPackedData(), and LowLevelTasks::FTask::GetInitData().
GetState()
ETaskState LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetState () const inline
Definition at line 253 of file Task.h.
References State.
Referenced by LowLevelTasks::FTask::TryRevive().
Friends And Related Symbol Documentation
FTaskBase::FPackedDataAtomic
friend class FTaskBase::FPackedDataAtomic friend
Definition at line 207 of file Task.h.
Field Documentation
[struct]
struct { ... } LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData
DebugName
uintptr_t LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::DebugName
Definition at line 201 of file Task.h.
Referenced by FPackedData(), FPackedData(), and GetDebugName().
Flags
uintptr_t LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::Flags
Definition at line 203 of file Task.h.
Referenced by FPackedData(), FPackedData(), and GetFlags().
PackedData
uintptr_t LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::PackedData
Definition at line 197 of file Task.h.
Referenced by FPackedData(), LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::compare_exchange_strong(), LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::compare_exchange_strong(), and LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::store().
Priority
uintptr_t LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::Priority
Definition at line 202 of file Task.h.
Referenced by FPackedData(), FPackedData(), and GetPriority().
State
uintptr_t LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::State
Definition at line 200 of file Task.h.
Referenced by FPackedData(), FPackedData(), FPackedData(), and GetState().
The documentation for this union was generated from the following file:
Runtime/Core/Public/Async/Fundamental/Task.h