Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/UniquePtr.h File Reference
UniquePtr.h File Reference
#include "CoreTypes.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/IsArray.h"
#include "Templates/RemoveExtent.h"
#include "Templates/Requires.h"
#include "Serialization/MemoryLayout.h"
#include <type_traits>
Data Structures
struct TDefaultDelete< T >
struct TDefaultDelete< T[]>
struct TIsBitwiseConstructible< TUniquePtr< T >, T * >
struct TIsZeroConstructType< TUniquePtr< T > >
class TUniquePtr< T, Deleter >
class TUniquePtr< T[], Deleter >
Functions
template<typename T UE_REQUIRES>
FORCEINLINE TUniquePtr< T > MakeUnique (SIZE_T Size)
Allocates a new array of type T with the given size and returns it as a TUniquePtr.
template<typename T, typename... TArgs UE_REQUIRES>
FORCEINLINE TUniquePtr< T > MakeUnique (TArgs &&... Args)
Allocates a new object of type T with the given arguments and returns it as a TUniquePtr.
template<typename T, typename... TArgs UE_REQUIRES>
TUniquePtr< T > MakeUnique (TArgs &&... Args)=delete
Overload to cause a compile error when MakeUnique<T[N]> is attempted.
template<typename T, typename... TArgs UE_REQUIRES>
FORCEINLINE TUniquePtr< T > MakeUniqueForOverwrite ()
Allocates a new object of type T with the given arguments and returns it as a TUniquePtr.
template<typename T UE_REQUIRES>
FORCEINLINE TUniquePtr< T > MakeUniqueForOverwrite (SIZE_T Size)
Allocates a new array of type T with the given size and returns it as a TUniquePtr.
template<typename T>
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR, const TUniquePtr< T > &Rhs)
template<typename T>
FORCEINLINE bool operator== (TYPE_OF_NULLPTR, const TUniquePtr< T > &Rhs)
Variables
template<typename T>
constexpr bool TIsTUniquePtr_V = false
Trait which determines whether or not a type is a TUniquePtr.
template<typename T, typename Deleter>
constexpr bool TIsTUniquePtr_V< const TUniquePtr< T, Deleter > > = true
template<typename T, typename Deleter>
constexpr bool TIsTUniquePtr_V< const volatile TUniquePtr< T, Deleter > > = true
template<typename T, typename Deleter>
constexpr bool TIsTUniquePtr_V< TUniquePtr< T, Deleter > > = true
template<typename T, typename Deleter>
constexpr bool TIsTUniquePtr_V< volatile TUniquePtr< T, Deleter > > = true
Function Documentation
MakeUnique() [1/3]
template<typename T UE_REQUIRES> FORCEINLINE TUniquePtr< T > MakeUnique (SIZE_T Size) nodiscard
Allocates a new array of type T with the given size and returns it as a TUniquePtr.
Only enabled for array-type TUniquePtrs. Elements are value-initialized, which will call a user-defined default constructor if it exists, but causes trivial types to be zeroed.
Parameters
Size The size of the array to allocate.
Returns
A TUniquePtr which points to a newly-constructed T array of the specified Size.
Definition at line 831 of file UniquePtr.h.
References FORCEINLINE, and TSequenceHistory< HistorySize >::Size.
MakeUnique() [2/3]
template<typename T, typename... TArgs UE_REQUIRES> FORCEINLINE TUniquePtr< T > MakeUnique (TArgs &&... Args) nodiscard delete
Allocates a new object of type T with the given arguments and returns it as a TUniquePtr.
Overload to cause a compile error when MakeUnique<T[N]> is attempted.
Disabled for array-type TUniquePtrs. The object is value-initialized, which will call a user-defined default constructor if it exists, but a trivial type will be zeroed.
Parameters
Args The arguments to pass to the constructor of T.
Returns
A TUniquePtr which points to a newly-constructed T with the specified Args.
Definition at line 796 of file UniquePtr.h.
References FORCEINLINE, and Forward().
Referenced by UE::Anim::Compression::FAnimationCompressionMemorySummaryScope::FAnimationCompressionMemorySummaryScope(), FAttributesSetEntry::FAttributesSetEntry(), FCharacterMovementComponentAsyncOutput::FCharacterMovementComponentAsyncOutput(), UAnimSequence::FCompressedAnimationDataReadScope::FCompressedAnimationDataReadScope(), UE::Geometry::FDynamicMeshOperator::FDynamicMeshOperator(), FMeshElementTypeWrapper::FMeshElementTypeWrapper(), FMeshElementTypeWrapper::FMeshElementTypeWrapper(), UAnimSequence::FScopedCompressedAnimSequence::FScopedCompressedAnimSequence(), TAnimatedAttribute< NumericType >::TAnimatedAttribute(), TAsyncTreeDifferences< InNodeType >::TAsyncTreeDifferences(), TActorDescContainerCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::TBaseIterator(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::TBaseIterator(), Metasound::Frontend::NodeRegistrationPrivate::TDeprecatedNodeAPIAdapter< TNodeType >::TDeprecatedNodeAPIAdapter(), UE::Geometry::TGenericDataOperator< ResultDataType >::TGenericDataOperator(), UE::Geometry::TSparseListSet< ElementType >::TSparseListSet(), UE::Geometry::TSparseListSet< ElementType >::TSparseListSet(), TUniqueObj< T >::TUniqueObj(), TUniqueObj< T >::TUniqueObj(), TUniqueObj< T >::TUniqueObj(), TWaterMeshUserDataBuffers< WITH_WATER_SELECTION_SUPPORT >::TWaterMeshUserDataBuffers(), FPackedLevelActorBuilder::AddBuilder(), Metasound::AddBuildError(), Metasound::FFrontendQuery::AddFunctionStep(), SSegmentedControl< OptionType >::AddSlot(), Metasound::FFrontendQuery::AddStep(), UE::FChangeTransactor::AddTransactionChange(), TActorDescContainerCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::AdvanceToRelevantActorInNextContainer(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::AdvanceToRelevantActorInNextContainer(), UE::Logging::Private::FUniqueLogTemplateStorage::Allocate(), UE::Geometry::TSparseListSet< ElementType >::AllocateNewBlockMemory(), FMeshRenderDecomposition::AppendGroup(), TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::BeginNewChange(), TBasicMeshSculptBrushOpFactory< OpType >::Build(), Metasound::TDataReadReference< FMidiClockSongPosition >::Clone(), Metasound::TDataValueReference< DataType >::Clone(), Metasound::TDataWriteReference< FMidiClockSongPosition >::Clone(), Metasound::TMetasoundEnvironmentVariable< Type >::Clone(), Metasound::TOutputStorage< DataType >::Clone(), TMeshAttributeArraySet< AttributeType >::Clone(), TMeshUnboundedAttributeArraySet< AttributeType >::Clone(), TNetRewindHistory< DataType >::Clone(), TNetworkPhysicsDataHelper< DataType >::Clone(), UE::FChangeTransactor::CloseTransaction(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), IAnimationDataController::ConditionalBracket(), FNetworkPredictionServiceRegistry::ConditionalCallFuncOnService(), IAnimationDataController::ConditionalTransaction(), TNetRewindHistory< DataType >::CopyFramesWithOffset(), UE::FGenericPlatformIoDispatcherFactory::Create(), FAsyncRegisterLevelContext::CreateInstance(), TNetRewindHistory< DataType >::CreateNew(), Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >::CreateNode(), Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::CreateOperator(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateOperator(), Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateOperator(), Metasound::TArrayConcatOperator< ArrayType >::CreateOperator(), Metasound::TArrayGetOperator< ArrayType >::CreateOperator(), Metasound::TArrayLastIndexOperator< ArrayType >::CreateOperator(), Metasound::TArrayNumOperator< ArrayType >::CreateOperator(), Metasound::TArrayRandomGetOperator< ArrayType >::CreateOperator(), Metasound::TArraySetOperator< ArrayType >::CreateOperator(), Metasound::TArrayShuffleOperator< ArrayType >::CreateOperator(), Metasound::TArraySubsetOperator< ArrayType >::CreateOperator(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory::CreateOperator(), Metasound::TLiteralOperatorLiteralFactory< DataType >::CreateOperator(), Metasound::TVariableNode< DataType >::FFactory::CreateOperator(), TNetworkPhysicsDataHelper< DataType >::CreateUniqueData(), TNetworkPhysicsDataHelper< DataType >::CreateUniqueRewindHistory(), CreateTypeImpl::Dispatch(), TActorDescViewMap< Type >::Emplace(), Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerNext(), Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerReset(), Metasound::Frontend::GenerateClass(), FStyleFonts::Get(), FNetworkPredictionServiceRegistry::GetDataStore(), SNodePanel::SNode::GetOrAddSlot(), FRotationConversionCache::GetOrCreatePayload(), FCharacterMovementComponentAsyncInput::Initialize(), FMeshRenderDecomposition::Initialize(), UE::FIoFileBlockCache::Initialize(), Metasound::TArrayShuffleOperator< ArrayType >::InitializeShufflers(), Metasound::FSharedStateShuffleManager::InitSharedState(), SHorizontalBox::InsertSlot(), SStackBox::InsertSlot(), SVerticalBox::InsertSlot(), TAsyncComponentDataComputeQueue< DataType >::LaunchJob(), UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOps(), UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOps(), UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOpsNoAddReferencedObjects(), UE::MovieScene::FComponentRegistry::MakeComponentTypeInfoWithoutComponentOps(), UE::MakeGenericPlatformIoDispatcher(), UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >::NewBlankChange(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::NewBlankChange(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::NewBlankChange(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::NewBlankChange(), UE::FGenericPlatformIoDispatcher::OpenFile(), UE::FChangeTransactor::OpenTransaction(), FObjectInitializer::FOverrides::FOverride::operator=(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), Audio::Quartz::PrivateDefs::TQuartzCommandQueue< IMetronomeEventListener, ICommandListener, IQueueCommandListener >::PushLambda(), Metasound::TCopyableDataChannel< TDataType >::PushLiteral(), Metasound::TCopyableDataChannel< TDataType >::PushOpaque(), Metasound::TReceiver< TDataType >::PushPayload(), Metasound::TSender< TDataType >::PushToDataChannel(), TAsyncTreeDifferences< InNodeType >::QueueParallelNodeLists(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal(), FBlueprintAssetHandler::RegisterHandler(), Metasound::Frontend::RegisterNode(), Metasound::Frontend::RegisterNode(), UE::Anim::AttributeTypes::RegisterType(), UE::Anim::AttributeTypes::RegisterTypeWithOperator(), Chaos::TUserDataManagerPT< TUserData >::SetData_GT(), TAsyncTreeDifferences< InNodeType >::SetDiffSpecification(), UPackage::SetFileSize(), SListView< TSharedPtr< FString > >::SetItemsSource(), SListView< TSharedPtr< FString > >::SetItemsSource(), UPackage::SetLinker(), UPackage::SetLinkerCustomVersions(), UPackage::SetLinkerLicenseeVersion(), UPackage::SetLinkerPackageVersion(), STreeView< FRigVMSearchResult >::SetRootItemsSource(), STreeView< FRigVMSearchResult >::SetRootItemsSource(), TGenericDataBackgroundCompute< ResultDataType >::Setup(), Metasound::FMetasoundEnvironment::SetValue(), UPackage::SetWorldTileInfo(), SNodePanel::SetZoomLevelsContainer(), SHorizontalBox::Slot(), SResponsiveGridPanel::Slot(), SSegmentedControl< OptionType >::Slot(), SStackBox::Slot(), SUniformWrapPanel::Slot(), SVerticalBox::Slot(), SWrapBox::Slot(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::TouchBlockData(), Metasound::Frontend::UnregisterNode(), TDisplayClusterDataCache< InDataType >::UpdateTickableGameObject(), USTRUCT(), FWatchablePropertySet::WatchProperty(), FWatchablePropertySet::WatchProperty(), FWatchablePropertySet::WatchProperty(), and FWatchablePropertySet::WatchProperty().
MakeUnique() [3/3]
template<typename T, typename... TArgs UE_REQUIRES> TUniquePtr< T > MakeUnique (TArgs &&... Args) nodiscard delete
Overload to cause a compile error when MakeUnique<T[N]> is attempted.
Use MakeUnique<T>(N) instead.
Overload to cause a compile error when MakeUnique<T[N]> is attempted.
Disabled for array-type TUniquePtrs. The object is value-initialized, which will call a user-defined default constructor if it exists, but a trivial type will be zeroed.
Parameters
Args The arguments to pass to the constructor of T.
Returns
A TUniquePtr which points to a newly-constructed T with the specified Args.
Definition at line 796 of file UniquePtr.h.
References FORCEINLINE, and Forward().
Referenced by UE::Anim::Compression::FAnimationCompressionMemorySummaryScope::FAnimationCompressionMemorySummaryScope(), FAttributesSetEntry::FAttributesSetEntry(), FCharacterMovementComponentAsyncOutput::FCharacterMovementComponentAsyncOutput(), UAnimSequence::FCompressedAnimationDataReadScope::FCompressedAnimationDataReadScope(), UE::Geometry::FDynamicMeshOperator::FDynamicMeshOperator(), FMeshElementTypeWrapper::FMeshElementTypeWrapper(), FMeshElementTypeWrapper::FMeshElementTypeWrapper(), UAnimSequence::FScopedCompressedAnimSequence::FScopedCompressedAnimSequence(), TAnimatedAttribute< NumericType >::TAnimatedAttribute(), TAsyncTreeDifferences< InNodeType >::TAsyncTreeDifferences(), TActorDescContainerCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::TBaseIterator(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::TBaseIterator(), Metasound::Frontend::NodeRegistrationPrivate::TDeprecatedNodeAPIAdapter< TNodeType >::TDeprecatedNodeAPIAdapter(), UE::Geometry::TGenericDataOperator< ResultDataType >::TGenericDataOperator(), UE::Geometry::TSparseListSet< ElementType >::TSparseListSet(), UE::Geometry::TSparseListSet< ElementType >::TSparseListSet(), TUniqueObj< T >::TUniqueObj(), TUniqueObj< T >::TUniqueObj(), TUniqueObj< T >::TUniqueObj(), TWaterMeshUserDataBuffers< WITH_WATER_SELECTION_SUPPORT >::TWaterMeshUserDataBuffers(), FPackedLevelActorBuilder::AddBuilder(), Metasound::AddBuildError(), Metasound::FFrontendQuery::AddFunctionStep(), SSegmentedControl< OptionType >::AddSlot(), Metasound::FFrontendQuery::AddStep(), UE::FChangeTransactor::AddTransactionChange(), TActorDescContainerCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::AdvanceToRelevantActorInNextContainer(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::AdvanceToRelevantActorInNextContainer(), UE::Logging::Private::FUniqueLogTemplateStorage::Allocate(), UE::Geometry::TSparseListSet< ElementType >::AllocateNewBlockMemory(), FMeshRenderDecomposition::AppendGroup(), TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::BeginNewChange(), TBasicMeshSculptBrushOpFactory< OpType >::Build(), Metasound::TDataReadReference< FMidiClockSongPosition >::Clone(), Metasound::TDataValueReference< DataType >::Clone(), Metasound::TDataWriteReference< FMidiClockSongPosition >::Clone(), Metasound::TMetasoundEnvironmentVariable< Type >::Clone(), Metasound::TOutputStorage< DataType >::Clone(), TMeshAttributeArraySet< AttributeType >::Clone(), TMeshUnboundedAttributeArraySet< AttributeType >::Clone(), TNetRewindHistory< DataType >::Clone(), TNetworkPhysicsDataHelper< DataType >::Clone(), UE::FChangeTransactor::CloseTransaction(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), IAnimationDataController::ConditionalBracket(), FNetworkPredictionServiceRegistry::ConditionalCallFuncOnService(), IAnimationDataController::ConditionalTransaction(), TNetRewindHistory< DataType >::CopyFramesWithOffset(), UE::FGenericPlatformIoDispatcherFactory::Create(), FAsyncRegisterLevelContext::CreateInstance(), TNetRewindHistory< DataType >::CreateNew(), Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >::CreateNode(), Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::CreateOperator(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateOperator(), Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateOperator(), Metasound::TArrayConcatOperator< ArrayType >::CreateOperator(), Metasound::TArrayGetOperator< ArrayType >::CreateOperator(), Metasound::TArrayLastIndexOperator< ArrayType >::CreateOperator(), Metasound::TArrayNumOperator< ArrayType >::CreateOperator(), Metasound::TArrayRandomGetOperator< ArrayType >::CreateOperator(), Metasound::TArraySetOperator< ArrayType >::CreateOperator(), Metasound::TArrayShuffleOperator< ArrayType >::CreateOperator(), Metasound::TArraySubsetOperator< ArrayType >::CreateOperator(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory::CreateOperator(), Metasound::TLiteralOperatorLiteralFactory< DataType >::CreateOperator(), Metasound::TVariableNode< DataType >::FFactory::CreateOperator(), TNetworkPhysicsDataHelper< DataType >::CreateUniqueData(), TNetworkPhysicsDataHelper< DataType >::CreateUniqueRewindHistory(), CreateTypeImpl::Dispatch(), TActorDescViewMap< Type >::Emplace(), Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerNext(), Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerReset(), Metasound::Frontend::GenerateClass(), FStyleFonts::Get(), FNetworkPredictionServiceRegistry::GetDataStore(), SNodePanel::SNode::GetOrAddSlot(), FRotationConversionCache::GetOrCreatePayload(), FCharacterMovementComponentAsyncInput::Initialize(), FMeshRenderDecomposition::Initialize(), UE::FIoFileBlockCache::Initialize(), Metasound::TArrayShuffleOperator< ArrayType >::InitializeShufflers(), Metasound::FSharedStateShuffleManager::InitSharedState(), SHorizontalBox::InsertSlot(), SStackBox::InsertSlot(), SVerticalBox::InsertSlot(), TAsyncComponentDataComputeQueue< DataType >::LaunchJob(), UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOps(), UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOps(), UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOpsNoAddReferencedObjects(), UE::MovieScene::FComponentRegistry::MakeComponentTypeInfoWithoutComponentOps(), UE::MakeGenericPlatformIoDispatcher(), UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >::NewBlankChange(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::NewBlankChange(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::NewBlankChange(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::NewBlankChange(), UE::FGenericPlatformIoDispatcher::OpenFile(), UE::FChangeTransactor::OpenTransaction(), FObjectInitializer::FOverrides::FOverride::operator=(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), Audio::Quartz::PrivateDefs::TQuartzCommandQueue< IMetronomeEventListener, ICommandListener, IQueueCommandListener >::PushLambda(), Metasound::TCopyableDataChannel< TDataType >::PushLiteral(), Metasound::TCopyableDataChannel< TDataType >::PushOpaque(), Metasound::TReceiver< TDataType >::PushPayload(), Metasound::TSender< TDataType >::PushToDataChannel(), TAsyncTreeDifferences< InNodeType >::QueueParallelNodeLists(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal(), FBlueprintAssetHandler::RegisterHandler(), Metasound::Frontend::RegisterNode(), Metasound::Frontend::RegisterNode(), UE::Anim::AttributeTypes::RegisterType(), UE::Anim::AttributeTypes::RegisterTypeWithOperator(), Chaos::TUserDataManagerPT< TUserData >::SetData_GT(), TAsyncTreeDifferences< InNodeType >::SetDiffSpecification(), UPackage::SetFileSize(), SListView< TSharedPtr< FString > >::SetItemsSource(), SListView< TSharedPtr< FString > >::SetItemsSource(), UPackage::SetLinker(), UPackage::SetLinkerCustomVersions(), UPackage::SetLinkerLicenseeVersion(), UPackage::SetLinkerPackageVersion(), STreeView< FRigVMSearchResult >::SetRootItemsSource(), STreeView< FRigVMSearchResult >::SetRootItemsSource(), TGenericDataBackgroundCompute< ResultDataType >::Setup(), Metasound::FMetasoundEnvironment::SetValue(), UPackage::SetWorldTileInfo(), SNodePanel::SetZoomLevelsContainer(), SHorizontalBox::Slot(), SResponsiveGridPanel::Slot(), SSegmentedControl< OptionType >::Slot(), SStackBox::Slot(), SUniformWrapPanel::Slot(), SVerticalBox::Slot(), SWrapBox::Slot(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::TouchBlockData(), Metasound::Frontend::UnregisterNode(), TDisplayClusterDataCache< InDataType >::UpdateTickableGameObject(), USTRUCT(), FWatchablePropertySet::WatchProperty(), FWatchablePropertySet::WatchProperty(), FWatchablePropertySet::WatchProperty(), and FWatchablePropertySet::WatchProperty().
MakeUniqueForOverwrite() [1/2]
template<typename T, typename... TArgs UE_REQUIRES> FORCEINLINE TUniquePtr< T > MakeUniqueForOverwrite () nodiscard
Allocates a new object of type T with the given arguments and returns it as a TUniquePtr.
Disabled for array-type TUniquePtrs. The object is default-initialized, which will call a user-defined default constructor if it exists, but a trivial type will be uninitialized.
Parameters
Args The arguments to pass to the constructor of T.
Returns
A TUniquePtr which points to a newly-constructed T with the specified Args.
Definition at line 814 of file UniquePtr.h.
References FORCEINLINE.
MakeUniqueForOverwrite() [2/2]
template<typename T UE_REQUIRES> FORCEINLINE TUniquePtr< T > MakeUniqueForOverwrite (SIZE_T Size) nodiscard
Allocates a new array of type T with the given size and returns it as a TUniquePtr.
Only enabled for array-type TUniquePtrs. Elements are default-initialized, which will call a user-defined default constructor if it exists, but causes trivial types to be left uninitialized.
Parameters
Size The size of the array to allocate.
Returns
A TUniquePtr which points to a newly-constructed T array of the specified Size.
Definition at line 849 of file UniquePtr.h.
References FORCEINLINE, and TSequenceHistory< HistorySize >::Size.
operator!=()
template<typename T> FORCEINLINE bool operator!= (TYPE_OF_NULLPTR , const TUniquePtr< T > & Rhs) nodiscard
Definition at line 763 of file UniquePtr.h.
References FORCEINLINE, and TUniquePtr< T, Deleter >::IsValid().
operator==()
template<typename T> FORCEINLINE bool operator== (TYPE_OF_NULLPTR , const TUniquePtr< T > & Rhs) nodiscard
Definition at line 757 of file UniquePtr.h.
References FORCEINLINE, and TUniquePtr< T, Deleter >::IsValid().
Variable Documentation
TIsTUniquePtr_V
template<typename T> bool TIsTUniquePtr_V = false constexpr
Trait which determines whether or not a type is a TUniquePtr.
Definition at line 868 of file UniquePtr.h.
TIsTUniquePtr_V< const TUniquePtr< T, Deleter > >
template<typename T, typename Deleter> bool TIsTUniquePtr_V< const TUniquePtr< T, Deleter > > = true constexpr
Definition at line 870 of file UniquePtr.h.
TIsTUniquePtr_V< const volatile TUniquePtr< T, Deleter > >
template<typename T, typename Deleter> bool TIsTUniquePtr_V< const volatile TUniquePtr< T, Deleter > > = true constexpr
Definition at line 872 of file UniquePtr.h.
TIsTUniquePtr_V< TUniquePtr< T, Deleter > >
template<typename T, typename Deleter> bool TIsTUniquePtr_V< TUniquePtr< T, Deleter > > = true constexpr
Definition at line 869 of file UniquePtr.h.
TIsTUniquePtr_V< volatile TUniquePtr< T, Deleter > >
template<typename T, typename Deleter> bool TIsTUniquePtr_V< volatile TUniquePtr< T, Deleter > > = true constexpr
Definition at line 871 of file UniquePtr.h.