Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/UnrealTemplate.h File Reference
UnrealTemplate.h File Reference
#include "CoreTypes.h"
#include "Templates/IsPointer.h"
#include "HAL/UnrealMemory.h"
#include "Templates/CopyQualifiersAndRefsFromTo.h"
#include "Templates/UnrealTypeTraits.h"
#include "Templates/RemoveReference.h"
#include "Templates/Requires.h"
#include "Templates/TypeCompatibleBytes.h"
#include "Templates/Identity.h"
#include "Traits/IsContiguousContainer.h"
#include "Traits/UseBitwiseSwap.h"
#include <type_traits>
Data Structures
class FNoncopyable
utility template for a class that should not be copyable.
struct FNoopStruct
Used to avoid cluttering code with ifdefs.
struct TForceInitAtBoot< T >
Template for initializing a singleton at the boot.
struct TGuardValue< RefType, AssignedType >
exception-safe guard around saving/restoring a value.
struct TGuardValue_Bitfield_Cleanup< FuncType >
struct TKeyValuePair< KeyType, ValueType >
Helper class to make it easy to use key/value pairs with a container.
struct TOptionalGuardValue< RefType, AssignedType >
exception-safe guard around saving/restoring a value.
struct TRemovePointer< T >
Removes one level of pointer from a type, e.g.:
struct TRemovePointer< T * >
struct TRValueToLValueReference< T >
TRValueToLValueReference converts any rvalue reference type into the equivalent lvalue reference, otherwise returns the same type.
struct TRValueToLValueReference< T && >
struct TScopeCounter< Type >
Commonly used to make sure a value is incremented, and then decremented anyway the function can terminate.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define FGuardValue_Bitfield(ReferenceValue, NewValue)
Macro variant on TGuardValue<bool> that can deal with bitfields which cannot be passed by reference in to TGuardValue.
#define STRUCT_OFFSET(struc, member)
#define TEMPLATE_PARAMETERS2(X, Y)
#define UE_ARRAY_COUNT(array)
#define UE_FORCE_CONSTEVAL(expr)
#define VTABLE_OFFSET(Class, MultipleInheritenceParent)
Functions
template<typename T>
void AsConst (const T &&Ref)=delete
Disallowed for rvalue references because it cannot extend their lifetime.
template<typename T>
constexpr FORCEINLINE const T & AsConst (T &Ref)
Returns a non-const reference type as const.
template<typename T, SIZE_T N>
constexpr FORCEINLINE const T(& AsConst (T(&Array)[N]))[N]
Returns a non-const reference type as const.
template<typename T>
FORCEINLINE T BitMask (uint32 Count)
Generates a bitmask with a given number of bits set.
template<>
FORCEINLINE uint16 BitMask< uint16 > (uint32 Count)
template<>
FORCEINLINE uint32 BitMask< uint32 > (uint32 Count)
template<>
FORCEINLINE uint64 BitMask< uint64 > (uint32 Count)
template<>
FORCEINLINE uint8 BitMask< uint8 > (uint32 Count)
template<typename T>
FORCEINLINE T CopyTemp (const T &Val)
template<typename T>
FORCEINLINE T CopyTemp (T &Val)
CopyTemp will enforce the creation of a prvalue which can bind to rvalue reference parameters.
template<typename T>
FORCEINLINE constexpr std::decay_t< T > CopyTempIfNecessary (T &&Val)
CopyTempIfNecessary will enforce the creation of a prvalue.
template<typename T>
T && DeclVal ()
Equivalent to std::declval.
template<typename T>
constexpr void Exchange (T &A, T &B)
template<typename OutType, typename InType>
OutType FloatCastChecked (InType In, InType Precision)
template<typename OutType, typename InType>
constexpr bool FloatFitsIn (InType In, InType Precision)
Test if value can make a static_cast roundtrip via OutType whilst maintaining precision.
template<typename T>
UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr T && Forward (std::remove_reference_t< T > &&Obj) noexcept
template<typename T>
UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr T && Forward (std::remove_reference_t< T > &Obj) noexcept
Forward will cast a reference to an rvalue reference.
template<typename T, typename Base UE_REQUIRES>
UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE decltype(auto) ForwardAsBase (std::remove_reference_t< T > &&Obj)
template<typename T, typename Base UE_REQUIRES>
UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE decltype(auto) ForwardAsBase (std::remove_reference_t< T > &Obj)
ForwardAsBase will cast a reference to an rvalue reference of a base type.
template<typename T, SIZE_T N>
constexpr const T * GetData (const T(&&Container)[N])
template<typename T, SIZE_T N>
constexpr const T * GetData (const T(&Container)[N])
template<typename T>
constexpr const T * GetData (std::initializer_list< T > List)
template<typename T UE_REQUIRES>
constexpr auto GetData (T &&Container) -> decltype(Container.GetData())
Generically gets the data pointer of a contiguous container.
template<typename T, SIZE_T N>
constexpr T * GetData (T(&&Container)[N])
template<typename T, SIZE_T N>
constexpr T * GetData (T(&Container)[N])
template<typename T, SIZE_T N>
constexpr SIZE_T GetNum (const T(&&Container)[N])
template<typename T, SIZE_T N>
constexpr SIZE_T GetNum (const T(&Container)[N])
template<typename T>
constexpr int32 GetNum (std::initializer_list< T > List)
Gets the number of items in an initializer list.
template<typename T UE_REQUIRES>
constexpr auto GetNum (T &&Container) -> decltype(Container.Num())
Generically gets the number of items in a contiguous container.
template<typename T, SIZE_T N>
constexpr SIZE_T GetNum (T(&&Container)[N])
template<typename T, SIZE_T N>
constexpr SIZE_T GetNum (T(&Container)[N])
template<typename T>
FORCEINLINE T ImplicitConv (typename TIdentity< T >::Type Obj)
Uses implicit conversion to create an instance of a specific type.
template<typename OutType, typename InType>
OutType IntCastChecked (InType In)
Cast and check that value fits in OutType.
template<typename OutType, typename InType>
constexpr bool IntFitsIn (InType In)
Test if value can make a lossless static_cast roundtrip via OutType without a sign change.
template<class ForwardIt>
ForwardIt MaxElement (ForwardIt First, ForwardIt Last)
works just like std::max_element.
template<class ForwardIt, class PredicateType>
ForwardIt MaxElement (ForwardIt First, ForwardIt Last, PredicateType Predicate)
works just like std::max_element.
template<class ForwardIt>
ForwardIt MinElement (ForwardIt First, ForwardIt Last)
works just like std::min_element.
template<class ForwardIt, class PredicateType>
ForwardIt MinElement (ForwardIt First, ForwardIt Last, PredicateType Predicate)
works just like std::min_element.
template<typename T>
FORCEINLINE void Move (T &A, typename TMoveSupportTraits< T >::Copy B)
This is used to provide type specific behavior for a copy which cannot change the value of B.
template<typename T>
FORCEINLINE void Move (T &A, typename TMoveSupportTraits< T >::Move B)
This is used to provide type specific behavior for a move which may change the value of B.
template<typename T>
UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr std::remove_reference_t< T > && MoveTemp (T &&Obj) noexcept
MoveTemp will cast a reference to an rvalue reference.
template<typename T>
UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr std::remove_reference_t< T > && MoveTempIfPossible (T &&Obj) noexcept
MoveTempIfPossible will cast a reference to an rvalue reference.
template<typename T UE_REQUIRES>
FORCEINLINE T ReverseBits (T Bits)
Reverses the order of the bits of a value.
template<typename T, typename ArgType>
FORCEINLINE T StaticCast (ArgType &&Arg)
This exists to avoid a Visual Studio bug where using a cast to forward an rvalue reference array argument to a pointer parameter will cause bad code generation.
template<typename T>
constexpr void Swap (T &A, T &B)
Swap two values.
template<typename ReferencedType>
UE_DEPRECATED (5.4, "IfAThenAElseB has been deprecated - use regular C++ constructs instead") FORCEINLINE ReferencedType *IfAThenAElseB(ReferencedType *A
Chooses between the two parameters based on whether the first is nullptr or not.
template<typename PredicateType, typename ReferencedType>
UE_DEPRECATED (5.4, "IfPThenAElseB has been deprecated - use regular C++ constructs instead") FORCEINLINE ReferencedType *IfPThenAElseB(PredicateType Predicate
branchless pointer selection based on predicate return PTRINT(Predicate) ?
UE_DEPRECATED (5.4, "XOR has been deprecated - use regular C++ constructs instead") inline bool XOR(bool A
A logical exclusive or function.
template<typename T, uint32 N>
char(& UEArrayCountHelper (const T(&)[N]))[N+1]
Variables
ReferencedType * A
ReferencedType * B
template<typename T, T Val>
constexpr T UE::Core::Private::TForceConstEval_V = Val
Macro Definition Documentation
FGuardValue_Bitfield
#define FGuardValue_Bitfield (ReferenceValue, NewValue)
Value:
    const bool PREPROCESSOR_JOIN(TempBitfield, __LINE__) = ReferenceValue; \
    ReferenceValue = NewValue; \
    const TGuardValue_Bitfield_Cleanup<TFunction<void()>> PREPROCESSOR_JOIN(TempBitfieldCleanup, __LINE__)([&](){ ReferenceValue = PREPROCESSOR_JOIN(TempBitfield, __LINE__); });
Macro variant on TGuardValue<bool> that can deal with bitfields which cannot be passed by reference in to TGuardValue.
Definition at line 458 of file UnrealTemplate.h.
STRUCT_OFFSET
#define STRUCT_OFFSET (struc, member)
Value:
offsetof(struc, member)
Definition at line 223 of file UnrealTemplate.h.
Referenced by FMemoryImageName::FMemoryImageName(), UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl(), UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::CheckConstraints(), TScriptMap< FDefaultSetAllocator, FScriptMap >::CheckConstraints(), TScriptSet< FDefaultSetAllocator, FScriptSet >::CheckConstraints(), TScriptSparseArray< typename Allocator::SparseArrayAllocator >::CheckConstraints(), FLightVolumeOctreeSemantics::GetBoundingBox(), FFilterVertexDeclaration::InitRHI(), FScreenVertexDeclaration::InitRHI(), FFileHelper::IsFilenameValidForSaving(), and FName::ToUnstableInt().
TEMPLATE_PARAMETERS2
#define TEMPLATE_PARAMETERS2 (X, Y)
Value:
X,Y
Definition at line 529 of file UnrealTemplate.h.
UE_ARRAY_COUNT
#define UE_ARRAY_COUNT (array)
Value:
(sizeof(UEArrayCountHelper(array)) - 1)
Definition at line 217 of file UnrealTemplate.h.
Referenced by FShadowMapInteraction::FShadowMapInteraction(), FSimulatedNavigationMetaData::FSimulatedNavigationMetaData(), FVertexFactory::FVertexFactory(), TBigInt< NumBits, bSigned >::TBigInt(), TConsoleVariableData< T >::TConsoleVariableData(), FNetControlMessageInfo::CheckInitialized(), FPaths::CombineImpl(), UE::Core::Private::TCopyConstructorLookup< Ts >::Construct(), UE::Core::Private::TMoveConstructorLookup< Ts >::Construct(), ConvertToIoDispatcherPriority(), UE::Core::Private::TDestructorLookup< Ts >::Destruct(), ExtractQueryCollisionResponseContainer(), ExtractSimCollisionResponseContainer(), FVolumetricLightmapBrickData::GetAllocatedBytes(), FCachedFileHandle::GetCacheIndex(), FRPCTrackingInfo::GetCurrentHistoryIdx(), FFileSystemError::GetMessage(), FLandscapeLayerUsageRenderProxy::GetParameterValue(), FLightMap2D::GetReferencedTextures(), FSHAHash::GetStringLen(), FVolumetricLightmapBrickTextureSet::Initialize(), UE::Math::TBox< T >::InverseTransformBy(), UE::Core::Private::TIsType< LookupType, Ts >::IsSame(), UE::Core::Private::TVariantLoadFromArchiveLookup< Ts >::Load(), TraceServices::ModuleStatusToString(), FFileSystemError::operator<<, FRunnableThreadAndroid::PreRun(), TraceServices::QueryResultToString(), FVolumetricLightmapBrickTextureSet::Release(), FVolumetricLightmapBrickData::ReleaseRHI(), FVolumetricLightmapBrickData::SetNeedsCPUAccess(), FApp::SetProjectName(), FSHAHash::ToString(), UE::Math::TBox< T >::TransformProjectBy(), and FIOSCommandLineHelper::TryReadCommandLineFile().
UE_FORCE_CONSTEVAL
#define UE_FORCE_CONSTEVAL (expr)
Value:
UE::Core::Private::TForceConstEval_V<std::decay_t<decltype(expr)>, (expr)>
Definition at line 251 of file UnrealTemplate.h.
Referenced by UE::FDynamicallyTypedValue::IsInline().
VTABLE_OFFSET
#define VTABLE_OFFSET (Class, MultipleInheritenceParent)
Value:
(((PTRINT) static_cast<MultipleInheritenceParent*>((Class*)1)) - 1)
Definition at line 229 of file UnrealTemplate.h.
Function Documentation
AsConst() [1/3]
template<typename T> void AsConst (const T && Ref) delete
Disallowed for rvalue references because it cannot extend their lifetime.
AsConst() [2/3]
template<typename T> FORCEINLINE const T & AsConst (T & Ref) constexpr
Returns a non-const reference type as const.
Definition at line 128 of file UnrealTemplate.h.
References FORCEINLINE.
Referenced by FSceneViewFamily::GetExtentionData().
AsConst() [3/3]
template<typename T, SIZE_T N> FORCEINLINE const T(& AsConst (T(&) Array[N]))[N] constexpr
Returns a non-const reference type as const.
This overload is only required until the pointer overloads are removed.
Definition at line 144 of file UnrealTemplate.h.
References Array, and FORCEINLINE.
BitMask()
template<typename T> FORCEINLINE T BitMask (uint32 Count)
Generates a bitmask with a given number of bits set.
References Count, and FORCEINLINE.
BitMask< uint16 >()
template<> FORCEINLINE uint16 BitMask< uint16 > (uint32 Count)
Definition at line 720 of file UnrealTemplate.h.
References checkSlow, Count, and FORCEINLINE.
BitMask< uint32 >()
template<> FORCEINLINE uint32 BitMask< uint32 > (uint32 Count)
Definition at line 713 of file UnrealTemplate.h.
References checkSlow, Count, and FORCEINLINE.
BitMask< uint64 >()
template<> FORCEINLINE uint64 BitMask< uint64 > (uint32 Count)
Definition at line 706 of file UnrealTemplate.h.
References checkSlow, Count, and FORCEINLINE.
BitMask< uint8 >()
template<> FORCEINLINE uint8 BitMask< uint8 > (uint32 Count)
Definition at line 727 of file UnrealTemplate.h.
References checkSlow, Count, and FORCEINLINE.
CopyTemp() [1/2]
template<typename T> FORCEINLINE T CopyTemp (const T & Val)
Definition at line 589 of file UnrealTemplate.h.
References FORCEINLINE.
CopyTemp() [2/2]
template<typename T> FORCEINLINE T CopyTemp (T & Val)
CopyTemp will enforce the creation of a prvalue which can bind to rvalue reference parameters.
Unlike MoveTemp, a source lvalue will never be modified. (i.e. a copy will always be made) There is no std:: equivalent, though there is the exposition function std::decay-copy: https://eel.is/c++draft/expos.only.func CopyTemp(<rvalue>) is regarded as an error and will not compile, similarly to how MoveTemp(<rvalue>) does not compile, and CopyTempIfNecessary should be used instead when the nature of the argument is not known in advance.
Definition at line 583 of file UnrealTemplate.h.
References FORCEINLINE.
Referenced by TMovieSceneEvaluationTree< DataType >::FAddOperator::operator()(), TMovieSceneEvaluationTree< DataType >::FAddUniqueOperator::operator()(), TDirectoryTree< ValueType >::FTreeNode::operator=(), IBreakIterator::SetString(), and IBreakIterator::SetString().
CopyTempIfNecessary()
template<typename T> FORCEINLINE constexpr std::decay_t< T > CopyTempIfNecessary (T && Val) constexpr
CopyTempIfNecessary will enforce the creation of a prvalue.
This is UE's equivalent of the exposition std::decay-copy: https://eel.is/c++draft/expos.only.func It doesn't static assert like CopyTemp, because it is useful in templates or macros where it's not obvious what the argument is, but you want to create a PR value without stopping compilation.
Definition at line 603 of file UnrealTemplate.h.
References FORCEINLINE.
DeclVal()
template<typename T> T && DeclVal ()
Equivalent to std::declval.
Note that this function is unimplemented, and is only intended to be used in unevaluated contexts, like sizeof and trait expressions.
Referenced by UE::Core::Private::Tuple::AssignableConceptCheck(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::CheckConstraints(), TScriptMap< FDefaultSetAllocator, FScriptMap >::CheckConstraints(), TScriptSet< FDefaultSetAllocator, FScriptSet >::CheckConstraints(), TScriptSparseArray< typename Allocator::SparseArrayAllocator >::CheckConstraints(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerEntityImpl(), MakeAttributeLambda(), MakeAttributeSPLambda(), MakeAttributeSPLambda(), and MakeAttributeWeakLambda().
Exchange()
template<typename T> void Exchange (T & A, T & B) constexpr
Definition at line 656 of file UnrealTemplate.h.
References A, B, and Swap.
Referenced by TOctree_DEPRECATED< ElementType, OctreeSemantics >::AddElementToNode(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CompactStable(), FTriangleRasterizer< RasterPolicyType >::DrawTriangle(), FTriangleRasterizer< RasterPolicyType >::DrawTriangleTrapezoid(), FPoly::GetOutsideWindings(), FWindowsPlatformAtomics::InterlockedCompareExchange(), FWindowsPlatformAtomics::InterlockedCompareExchange(), FWindowsPlatformAtomics::InterlockedCompareExchange(), FWindowsPlatformAtomics::InterlockedCompareExchange(), FWindowsPlatformAtomics::InterlockedCompareExchangePointer(), FWindowsPlatformAtomics::InterlockedExchange(), FWindowsPlatformAtomics::InterlockedExchange(), FWindowsPlatformAtomics::InterlockedExchange(), FWindowsPlatformAtomics::InterlockedExchange(), FWindowsPlatformAtomics::InterlockedExchangePtr(), MS_ALIGN(), TAtomic< T >::operator=(), Algo::Partition(), TJugglingRotation< TGCDPolicy >::Rotate(), TMergeSort< TMergePolicy, MinMergeSubgroupSize >::Sort(), FTransaction::FObjectRecord::FSerializedObject::Swap(), FTransactionObjectId::Swap(), UE::Transaction::FDiffableObject::Swap(), UE::Transaction::FSerializedObject::Swap(), UE::Transaction::FSerializedObjectInfo::Swap(), and UE_DEPRECATED().
FloatCastChecked()
template<typename OutType, typename InType> OutType FloatCastChecked (InType In, InType Precision)
Definition at line 195 of file UnrealTemplate.h.
References checkf, FloatFitsIn(), and TEXT.
Referenced by UE::Slate::FDeprecateVector2DParameter::FDeprecateVector2DParameter(), UE::LWC::NarrowWorldPositionChecked(), UE::LWC::NarrowWorldPositionChecked(), FCanvas::UE_DEPRECATED(), and FCanvas::UE_DEPRECATED().
FloatFitsIn()
template<typename OutType, typename InType> bool FloatFitsIn (InType In, InType Precision) constexpr
Test if value can make a static_cast roundtrip via OutType whilst maintaining precision.
Definition at line 186 of file UnrealTemplate.h.
Referenced by FloatCastChecked().
Forward() [1/2]
template<typename T> UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr T && Forward (std::remove_reference_t< T > && Obj) constexpr noexcept
Definition at line 619 of file UnrealTemplate.h.
References FORCEINLINE, UE_INTRINSIC_CAST, and UE_NODEBUG.
Forward() [2/2]
template<typename T> UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr T && Forward (std::remove_reference_t< T > & Obj) constexpr noexcept
Forward will cast a reference to an rvalue reference.
This is UE's equivalent of std::forward.
Definition at line 613 of file UnrealTemplate.h.
References FORCEINLINE, UE_INTRINSIC_CAST, and UE_NODEBUG.
Referenced by FAsyncTask< FAsyncSoundWavePCMWriteWorker >::FAsyncTask(), UE::Geometry::FAsyncTaskExecuterWithAbort< TTask >::FAsyncTaskExecuterWithAbort(), UE::Geometry::FAsyncTaskExecuterWithProgressCancel< TTask >::FAsyncTaskExecuterWithProgressCancel(), FAutoDeleteAsyncTask< FCancelIORequestsTask >::FAutoDeleteAsyncTask(), FCbAttachment::FBinaryValue::FBinaryValue(), FCbAttachment::FBinaryValue::FBinaryValue(), FStructTypeBitSet::FBitSetContainer::FBitSetContainer(), FCbAttachment::FCbAttachment(), FCbAttachment::FCbAttachment(), FCbAttachment::FCbAttachment(), FCompositeBuffer::FCompositeBuffer(), FCbAttachment::FCompressedBinaryValue::FCompressedBinaryValue(), FCbAttachment::FCompressedBinaryValue::FCompressedBinaryValue(), FStructTypeBitSet::FConstBitSetContainer::FConstBitSetContainer(), Metasound::FEnvironmentVertexInterface::FEnvironmentVertexInterface(), Metasound::FInputVertexInterface::FInputVertexInterface(), FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FInvalidateWidgetReasonAttribute(), FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FInvalidateWidgetReasonAttribute(), Metasound::FLiteral::FLiteral(), FMovieSceneChannelProxy::FMovieSceneChannelProxy(), Verse::FNativeString::FNativeString(), Metasound::FOutputVertexInterface::FOutputVertexInterface(), FRegisterCompiledInInfo::FRegisterCompiledInInfo(), FSceneRenderGroupScope::FSceneRenderGroupScope(), FSkinWeightProfileStack::FSkinWeightProfileStack(), TValueOrError< ValueType, ErrorType >::FWrapErrorType::FWrapErrorType(), UE::MovieScene::TAdd< T >::TAdd(), UE::MovieScene::TAddConditional< T >::TAddConditional(), TAllocPlaybackLog< FModifier, FAllocOp >::TAllocPlaybackLog(), TAllocRecordingLog< FModifier, FAllocOp >::TAllocRecordingLog(), UE::MovieScene::TAnonTaskWrapper< TaskType >::TAnonTaskWrapper(), TStaticArray< InElementType, NumElements, Alignment >::TArrayStorage::TArrayStorage(), TStaticArray< InElementType, NumElements, Alignment >::TArrayStorageElementAligned::TArrayStorageElementAligned(), TArrayView< FTransform >::TArrayView(), TArrayView< FTransform >::TArrayView(), TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::TBaseFunctorDelegateInstance(), TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseRawMethodDelegateInstance(), TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::TBaseSPLambdaDelegateInstance(), TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseSPMethodDelegateInstance(), TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseStaticDelegateInstance(), TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseUFunctionDelegateInstance(), TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseUObjectMethodDelegateInstance(), TBlendableToken< DataType >::TBlendableToken(), TBlendableToken< DataType >::TBlendableToken(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::TCommonDelegateInstanceState(), Metasound::TDataReadReference< FMidiClockSongPosition >::TDataReadReference(), Metasound::TDataReference< DataType >::TDataReference(), Metasound::TDataValueReference< DataType >::TDataValueReference(), Metasound::TDataWriteReference< FMidiClockSongPosition >::TDataWriteReference(), TEnqueueUniqueRenderCommandType< TagType, LambdaType >::TEnqueueUniqueRenderCommandType(), UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >::TEntityAllocationTask(), UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >::TEntityAllocationTask(), UE::MovieScene::TEntityBuilder<>::TEntityBuilder(), UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >::TEntityTask(), UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >::TEntityTask(), UE::MovieScene::TEntityTaskComponents< T >::TEntityTaskComponents(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::TEntityTaskComponentsImpl(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::TFixedSparseBitSet(), UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::TFunction_OwnedObject(), TFunctionRef< Ret(ParamTypes...)>::TFunctionRef(), UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase(), TInlineValue< FChannelOverrideProviderTraits, 64 >::TInlineValue(), TInlineValue< FChannelOverrideProviderTraits, 64 >::TInlineValue(), Metasound::TInputConstructorVertex< DataType >::TInputConstructorVertex(), Metasound::TInputDataVertex< DataType >::TInputDataVertex(), SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::TIntrusiveReferenceController(), UE::CurveEditor::TInvertedCurveModel< TBase >::TInvertedCurveModel(), TIoStatusOr< T >::TIoStatusOr(), TIteratorAdapter< TIteratorBase< InElementType, InSizeType > >< const ElementType, SizeType >::TIteratorAdapter(), Experimental::RobinHoodHashTable_Private::TKeyValue< KeyType, ValueType >::TKeyValue(), Experimental::RobinHoodHashTable_Private::TKeyValue< KeyType, FUnitType >::TKeyValue(), FCookStatsManager::TKeyValuePair< FString, FString >::TKeyValuePair(), UE::GC::TMemberDeclaration< T >::TMemberDeclaration(), Metasound::TMetasoundEnvironmentVariable< Type >::TMetasoundEnvironmentVariable(), TMovieSceneInterrogationToken< T >::TMovieSceneInterrogationToken(), Verse::TNativeTuple< Type >::TNativeTuple(), Verse::TNativeTuple< Type, RestTypes... >::TNativeTuple(), TNetSimCueWrapper< TCue >::TNetSimCueWrapper(), FRDGAllocator::TObject< T >::TObject(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::TOptional(), UE::Anim::TOptionalScopedGraphMessage< TGraphMessageType >::TOptionalScopedGraphMessage(), UE::Sequencer::TOutlinerModelMixin< BaseType >::TOutlinerModelMixin(), Metasound::TOutputConstructorVertex< DataType >::TOutputConstructorVertex(), Metasound::TOutputDataVertex< DataType >::TOutputDataVertex(), UE::MovieScene::TOverlappingEntityInput< InputKeyTypes... >::TOverlappingEntityInput(), TPayload< Ret(Types...)>::TPayload(), TPayload< void(Types...)>::TPayload(), UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl(), UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl(), AwaitableTask_Detail::TPromise< ReturnType, CallableType >::TPromise(), TRangeAllocator< FAllocatorModifier >::TRangeAllocator(), TRenderThreadStruct< StructType >::TRenderThreadStruct(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::TScheduledEntityTask(), UE::Anim::TScopedGraphMessage< TGraphMessageType >::TScopedGraphMessage(), TSetElement< InElementType >::TSetElement(), TSetElementBase< InElementType, THasTypeLayout< InElementType >::Value >::TSetElementBase(), TSetElementBase< InElementType, true >::TSetElementBase(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedRef< INavigationToolItem >::TSharedRef(), TStaticArray< int32, MAX_PHYSICS_FIELD_TARGETS, 16 >::TStaticArray(), TStaticArray< int32, MAX_PHYSICS_FIELD_TARGETS, 16 >::TStaticArray(), FRDGBlackboard::TStruct< StructType >::TStruct(), TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet(), LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::TTaskDelegateImpl(), LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::TTaskDelegateImpl(), TToolCompatibleMixin< ToolCompatibleWidget >::TToolCompatibleMixin(), TTuple< const UFleshAsset *, const UFleshComponent *, FTransform >::TTuple(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::TTupleBase(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::TTupleBase(), UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::TTupleBaseElement(), UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >::TTupleBaseElement(), UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::TTypedIndexRange(), UE::Sequencer::TTypedIterator< T, FParentModelIterator >::TTypedIterator(), UE::Sequencer::TTypedIteratorBase< T, IteratorType >::TTypedIteratorBase(), TUnderlyingArchiveContainer< T >::TUnderlyingArchiveContainer(), TUniqueObj< T >::TUniqueObj(), UE::MovieScene::TUnstructuredTask< TaskImpl >::TUnstructuredTask(), TValueOrError_ErrorProxy< ArgTypes >::TValueOrError_ErrorProxy(), TValueOrError_ValueProxy< ArgTypes >::TValueOrError_ValueProxy(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::TVariant(), TVersionedReader< T >::TVersionedReader(), TVersionedWriter< T >::TVersionedWriter(), TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::TWeakBaseFunctorDelegateInstance(), Algo::Private::TTiedTupleAdder< OutputTypes >::Add(), FMovieSceneChannelProxyData::Add(), FMovieSceneExecutionTokens::Add(), FMovieSceneInterrogationData::Add(), TMeshElementArray< ElementType, ElementIDType >::Add(), UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::Add(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::Add(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Add(), FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotationInternal(), FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotationInternal(), FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AddAnnotationInternal(), FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::AddAnnotationInternal(), UE::MovieScene::FImportedEntity::AddBuilder(), Metasound::AddBuildError(), UE::MovieScene::FPlaybackCapabilities::AddCapability(), UE::MovieScene::FPlaybackCapabilities::AddCapability(), UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), UE::MovieScene::FSharedPlaybackState::AddCapability(), UE::MovieScene::FEntityManager::AddComponent(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::AddConditional(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddConditional(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::AddDelegateInstance(), UE::SequenceNavigator::FNavigationToolItemDragDropOp::AddDropHandler(), UE::Sequencer::FDynamicExtensionContainer::AddDynamicExtension(), UE::Sequencer::FViewModel::AddDynamicExtension(), UE::Sequencer::FViewModel::AddDynamicExtension(), FPixelShaderUtils::AddFullscreenInstancedMultiViewportPass(), FPixelShaderUtils::AddFullscreenPass(), UE::MovieScene::AddKeyToChannel(), FMovieSceneChannelEditorDataEntry::AddMetaData(), FCanvasRenderContext::AddPass(), FCanvasRenderContext::AddPass(), FCanvasRenderThreadScope::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FRDGBuilder::AddPostExecuteCallback(), FPixelShaderUtils::AddRasterizeToRectsPass(), Metasound::FFrontendQuery::AddStep(), UE::MovieScene::IEntitySystemScheduler::AddTask(), FTokenizedMessage::AddText(), UE::FChangeTransactor::AddTransactionChange(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddUniqueImpl(), FSlateRenderBatch::AddVertex(), FCanvasRenderContext::Alloc(), FRDGAllocator::Alloc(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Allocate(), TRDGHandleRegistry< FRDGPassHandle >::Allocate(), UE::AnimNext::FDataRegistry::AllocateData(), FMeshElementCollector::AllocateOneFrameResource(), UE::MemStack::AllocateStringf(), UE::MemStack::AllocateStringViewf(), FRDGAllocator::AllocNoDestruct(), TStringBuilderBase< TCHAR >::Append(), FCompositeBuffer::AppendBuffers(), TStringBuilderBase< TCHAR >::Appendf(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Apply(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Apply(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyAfter(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::ApplyBefore(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyUnlocked(), UE::Core::Private::Tuple::Assign(), UE::MovieScene::AssignValue(), Async(), AsyncPool(), AsyncThread(), UE::Core::Private::Function::TFunctionStorage< bUnique >::Bind(), TAttribute< ObjectType >::BindLambda(), TAttribute< ObjectType >::BindSPLambda(), TAttribute< ObjectType >::BindSPLambda(), TAttribute< ObjectType >::BindWeakLambda(), FMovieSceneBlendingAccumulator::BlendToken(), FMovieSceneBlendingAccumulator::BlendToken(), Metasound::VertexPrivate::FInputVertexInterfaceDeclarationBuilder::Build(), Metasound::VertexPrivate::FOutputVertexInterfaceDeclarationBuilder::Build(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue(), UE::Core::Private::Function::TFunctionRefCaller< Functor, Ret, ParamTypes >::Call(), UE::Sequencer::ICastable::CastedCall(), UE::Sequencer::ICastable::CastedCall(), FPaths::Combine(), UE::MovieScene::TDirectPropertyTraits< float >::CombineComposites(), UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::CombineComposites(), TBitArray< typename Allocator::BitArrayAllocator >::CombineWithBinaryOp(), UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::Commit(), UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::Commit(), TStringView< TCHAR >::Compare(), FAtmosphereSetup::ComputeViewData(), Concatenate(), IAnimationDataController::ConditionalAction(), TSingleThreadedSlabAllocator< FIoEncodedBlockRequest >::Construct(), TGraphTask< TTask >::FConstructor::ConstructAndDispatchWhenReady(), TGraphTask< TTask >::FConstructor::ConstructAndHold(), TGraphTask< TTask >::FConstructor::ConstructAndHoldImpl(), Algo::Contains(), Algo::ContainsBy(), PropertyTemplate::ConvertToIntermediateType(), FMovieSceneChannelValueSetter::Create(), FRDGBlackboard::Create(), FStreamableDownloadCachePin::Create(), TAnimatedAttribute< NumericType >::Create(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::Create(), UE::PixelStreaming2::FPixelStreamingTickableTask::Create(), Metasound::TDataFactory< DataType, CreatorType >::CreateAny(), FStructSharedMemory::CreateArgs(), AWorldDataLayers::CreateDataLayer(), Metasound::TDataFactory< DataType, CreatorType >::CreateExplicit(), Metasound::TDataFactory< DataType, CreatorType >::CreateExplicitArgs(), FCookStatsManager::CreateKeyValueArray(), TAttribute< ObjectType >::CreateLambda(), Metasound::DataFactoryPrivate::TDataTypeCreator< DataType >::CreateNew(), Metasound::TDataReadReference< FMidiClockSongPosition >::CreateNew(), Metasound::TDataReference< DataType >::CreateNew(), Metasound::TDataValueReference< DataType >::CreateNew(), Metasound::TDataWriteReference< FMidiClockSongPosition >::CreateNew(), TAttribute< ObjectType >::CreateSPLambda(), TAttribute< ObjectType >::CreateSPLambda(), TAttribute< ObjectType >::CreateWeakLambda(), Metasound::VertexDataPrivate::TFactoryFacade< Type >::CreateWithArgs(), Metasound::VertexDataPrivate::TFactoryFacade< TDataReadReference< DataType > >::CreateWithArgs(), Metasound::VertexDataPrivate::TFactoryFacade< TDataValueReference< DataType > >::CreateWithArgs(), Metasound::VertexDataPrivate::TFactoryFacade< TDataWriteReference< DataType > >::CreateWithArgs(), UE::GC::DeclareMember(), UE::GC::DeclareMember(), UE::SequenceNavigator::TNavigationToolItemProxyDefaultFactoryBase< InItemProxyType, InItemProxyPriority, typename >::DefaultCreateItemProxy(), FCanvasRenderContext::DeferredRelease(), UE::MovieScene::FEntityFactories::DefineChildComponent(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity(), UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerEntity(), UE::Core::Private::Tuple::TTransformTuple_Impl< TIntegerSequence< uint32, Indices... > >::Do(), UE::Core::Private::Tuple::TVisitTupleElements_Impl< TIntegerSequence< uint32, Indices... > >::Do(), UE::MovieScene::FPlaybackCapabilities::DoAddCapability(), UE::MovieScene::FPlaybackCapabilities::DoOverwriteCapability(), UE::CoreUObject::Private::DynamicCast(), FRDGScope::TStorage< FRDGScope_Budget >::Emplace(), RangedForIteratorType< FAnimNextTraitEventPtr >::Emplace(), TBasicArray< T >::Emplace(), TChunkedArray< TUniquePtr< DescType > >::Emplace(), TInlineValue< FChannelOverrideProviderTraits, 64 >::Emplace(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Emplace(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Emplace(), TRingBuffer< T, AllocatorT >::Emplace(), TSet< class UObject * >::Emplace(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Emplace(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Emplace(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Emplace(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Emplace(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Emplace(), UE::AnimNext::TPool< ElementType >::Emplace(), UE::Slate::Containers::TObservableArray< InElementType >::Emplace(), RangedForIteratorType< FAnimNextTraitEventPtr >::Emplace_GetRef(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Emplace_GetRef(), TRingBuffer< T, AllocatorT >::Emplace_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::EmplaceAt(), TBasicArray< T >::EmplaceAt(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::EmplaceAt(), UE::Slate::Containers::TObservableArray< InElementType >::EmplaceAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::EmplaceAt_GetRef(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::EmplaceAtLowestFreeIndex(), TraceServices::TCachedPagedArray< InItemType, PageSize >::EmplaceBack(), TraceServices::TPagedArray< InItemType, InPageType >::EmplaceBack(), TraceServices::TIntervalTimeline< EventType, SettingsType >::EmplaceBeginEvent(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::EmplaceByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::EmplaceByHash(), TSet< class UObject * >::EmplaceByHash(), TraceServices::TPointTimeline< EventType, SettingsType >::EmplaceEvent(), TDeque< InElementType, InAllocatorType >::EmplaceFirst(), TRingBuffer< T, AllocatorT >::EmplaceFront(), TRingBuffer< T, AllocatorT >::EmplaceFront_GetRef(), TDeque< InElementType, InAllocatorType >::EmplaceLast(), TFutureState< ResultType >::EmplaceResult(), TConstKeyIterator< FFixedObjectBindingID, FName >::EmplaceUnique(), TPromise< ResultType >::EmplaceValue(), UE::PixelStreaming2::FEpicRtcDataTrack::EncodeMessage(), TClosableMpscQueue< T >::Enqueue(), TMpscQueue< T, AllocatorType >::Enqueue(), TSpscQueue< T, AllocatorType >::Enqueue(), UE::SequenceNavigator::INavigationTool::EnqueueItemAction(), TStringView< TCHAR >::Equals(), TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Execute(), TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute(), TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Execute(), TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute(), TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute(), TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute(), TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute(), TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Execute(), TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ExecuteIfSafe(), TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe(), TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ExecuteIfSafe(), TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe(), TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe(), TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe(), TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe(), TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ExecuteIfSafe(), Algo::Find(), Algo::FindBy(), AlgoImpl::FindBy(), Algo::FindByPredicate(), AlgoImpl::FindByPredicate(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::FindEntry(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrAdd(), UE::SequenceNavigator::INavigationTool::FindOrAdd(), TSet< class UObject * >::FindOrAddByHash(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrAddId(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrAddIdByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddImpl(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddImpl(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindOrAddImpl(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrUpdateIdByHashInternal(), UE::MovieScene::FPlaybackCapabilities::ForEachCapabilityInterface(), UE::MovieScene::TEntityTaskComponents< T >::Fork_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Fork_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Fork_PerEntity(), UE::MovieScene::TFilteredEntityTask< T >::Fork_PerEntity(), FText::FormatNamed(), TextFormatUtil::FormatNamed(), TextFormatUtil::FormatNamed(), FText::FormatOrdered(), TextFormatUtil::FormatOrdered(), TextFormatUtil::FormatOrdered(), ForwardAsTuple(), UE::Core::Private::Tuple::TTupleElementGetterByIndex< Index, TupleSize >::Get(), UE::Core::Private::Tuple::TTupleElementGetterByType< Type, TupleSize >::Get(), UE::Core::ArrayView::Private::TIsCompatibleRangeType< T, ElementType >::GetData(), UE::Core::ArrayView::Private::TIsReinterpretableRangeType< T, ElementType >::GetData(), UE::Core::ArrayView::Private::GetDataHelper(), UE::Core::Private::GetDataHelper(), Metasound::FDataReferenceCollection::GetDataReadReferenceOrConstruct(), Metasound::FDataReferenceCollection::GetDataWriteReferenceOrConstruct(), UE::Core::Private::Tuple::TTupleElementGetterByType< Type, TupleSize >::GetImpl(), Metasound::VertexDataPrivate::FInputBinding::GetOrConstructAs(), Metasound::VertexDataPrivate::FOutputBinding::GetOrConstructAs(), Metasound::FOutputVertexInterfaceData::GetOrConstructDataReadReference(), Metasound::FOutputVertexInterfaceData::GetOrConstructDataWriteReference(), FRDGBlackboard::GetOrCreate(), UE::Core::ArrayView::Private::GetReinterpretedDataHelper(), TSlateAttributeComparePredicate< ComparePredicate >::IdenticalTo(), FCookStatsManager::ImplCreateKeyValueArray(), FCookStatsManager::ImplCreateKeyValueArray(), FCookStatsManager::ImplCreateKeyValueArray(), LowLevelTasks::FTask::Init(), LowLevelTasks::FTask::Init(), TAwaitableTask< ReturnType >::Init(), TAwaitableTask< ReturnType >::Init(), TAwaitableTask< ReturnType >::InitAndLaunch(), TAwaitableTask< ReturnType >::InitAndLaunch(), TConstSharedStruct< BaseStructT >::Initialize(), TSharedStruct< BaseStructT >::Initialize(), TInstancedStruct< BaseStructT >::InitializeAs(), TStructOnScope< T >::InitializeAs(), TInlineValue< FChannelOverrideProviderTraits, 64 >::InitializeFrom(), TMeshElementArray< ElementType, ElementIDType >::Insert(), UE::PixelStreaming2::FBufferBuilder::Insert(), UE::PixelStreaming::BufferBuilder::Insert(), FNetSimCueDispatcher::Invoke(), Invoke(), Invoke(), Invoke(), UE::Core::Private::Tuple::TVisitTupleElements_Impl< TIntegerSequence< uint32, Indices... > >::InvokeFunc(), UE::MovieScene::TFilteredEntityTask< T >::Iterate_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Iterate_PerEntity(), TStringBuilderBase< TCHAR >::Join(), UE::String::Join(), UE::String::JoinBy(), UE::String::JoinByTo(), TStringBuilderBase< TCHAR >::JoinQuoted(), UE::String::JoinQuoted(), UE::String::JoinQuotedBy(), UE::String::JoinQuotedByTo(), UE::String::JoinQuotedTo(), UE::String::JoinTo(), UE::String::JoinTuple(), UE::String::JoinTupleBy(), UE::String::JoinTupleQuoted(), UE::String::JoinTupleQuotedBy(), UE::String::JoinTupleQuotedTo(), UE::String::JoinTupleTo(), Algo::KahnTopologicalSort(), UE::Tasks::FPipe::Launch(), UE::Tasks::FPipe::Launch(), UE::Tasks::Launch(), UE::Tasks::Launch(), UE::Tasks::Private::FTaskHandle::Launch(), TConstSharedStruct< BaseStructT >::Make(), TInstancedStruct< BaseStructT >::Make(), TSharedStruct< BaseStructT >::Make(), MakeArrayView(), MakeArrayView(), MakeAttributeLambda(), MakeAttributeSPLambda(), MakeAttributeSPLambda(), MakeAttributeWeakLambda(), UE::Tasks::MakeCompletedTask(), MakeConstArrayView(), MakeConstArrayView(), MakeConstStridedView(), CoroTask_Detail::MakeDummyType(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::MakeEntry(), MakeError(), MakeFulfilledPromise(), MakeInlineValue(), Metasound::MakeOperatorFactoryRef(), FCookStatsManager::MakePair(), TPimplPtr< T, EPimplPtrMode::DeepCopy >::MakePimpl, MakeRefCount(), MakeShareable(), MakeShared(), MakeStridedView(), MakeStructOnScope(), MakeTDecl(), MakeTraitEvent(), MakeTuple(), UE::Core::Private::Tuple::MakeTupleImpl(), MakeUnique(), MakeValue(), MakeYCombinator(), SharedPointerInternals::NewCustomReferenceController(), FSceneViewExtensions::NewExtension(), SharedPointerInternals::NewIntrusiveReferenceController(), UE::SequenceNavigator::INavigationTool::NewItemAction(), TStringView< TCHAR >::operator!=, TStringView< TCHAR >::operator!=, TEqualTo< void >::operator()(), TGreater< void >::operator()(), TLess< void >::operator()(), TOverrideVoidReturnInvoker< ReturnType, FuncType >::operator()(), TPlacementNewer< T >::operator()(), TReversePredicate< PredicateType >::operator()(), TYCombinator< LAMBDA >::operator()(), TYCombinator< LAMBDA >::operator()(), Verse::FNativeString::operator+, Verse::FNativeString::operator+=(), TStringView< TCHAR >::operator<, TStringView< TCHAR >::operator<, operator<<(), TInlineValue< FChannelOverrideProviderTraits, 64 >::operator=(), TUniqueObj< T >::operator=(), UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::operator=(), Verse::FNativeString::operator=(), TStringView< TCHAR >::operator==, TStringView< TCHAR >::operator==, UE::MovieScene::FPlaybackCapabilities::OverwriteCapability(), UE::MovieScene::FPlaybackCapabilitiesImpl::OverwriteCapability(), ParallelForWithPreWorkWithExistingTaskContext(), ParallelForWithPreWorkWithTaskContext(), ParallelForWithPreWorkWithTaskContext(), FPixelStreamingPeerConnection::PostSignalingTask(), UE::TConsumeAllMpmcQueue< T, AllocatorType >::ProduceItem(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Read(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Read(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ReadByHash(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ReadByHash(), UE::Geometry::FRefCountVector::Rebuild(), TAllocRecordingLog< FModifier, FAllocOp >::RecordAlloc(), UE::SequenceNavigator::FNavigationToolItemProxyRegistry::RegisterItemProxyFactory(), UE::Anim::AttributeTypes::RegisterTypeWithOperator(), TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleasePooledResource(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleasePooledResource(), Algo::Replace(), Algo::ReplaceIf(), FStreamableManager::RequestAsyncLoad(), FStreamableManager::RequestSyncLoad(), UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ResolveComponent(), TBlendableTokenStack< DataType >::SavePreAnimatedStateImpl(), UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerEntity(), UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerEntity(), UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl(), Algo::SelectRandomWeightedBy(), AlgoImpl::SelectRandomWeightedBy(), UE::Sequencer::FKeySelection::SelectRange(), FPixelStreamingDataChannel::SendMessage(), UE::PixelStreaming2::FEpicRtcDataTrack::SendMessage(), Metasound::FLiteral::Set(), UE::MovieScene::TEntityPtr< T >::Set(), UE::MovieScene::TEntityPtr< T... >::Set(), FEditPropertyChain::SetAffectedArchetypeInstances(), SetBatchedShaderParametersMixed(), SetBatchedShaderParametersMixed(), UE::MovieScene::TEntityRange< T >::SetComponent(), FMovieSceneChannelEditorDataEntry::SetExtendedEditorData(), FPropertyChangedEvent::SetInstancesChanged(), UE::MovieScene::FSharedPlaybackState::SetOrAddCapability(), SetPromise(), SetPromise(), SetShaderParametersLegacy(), SetShaderParametersLegacyAS(), SetShaderParametersLegacyCS(), SetShaderParametersLegacyGS(), SetShaderParametersLegacyMS(), SetShaderParametersLegacyPS(), SetShaderParametersLegacyVS(), SetShaderParametersMixed(), SetShaderParametersMixedAS(), SetShaderParametersMixedAS(), SetShaderParametersMixedCS(), SetShaderParametersMixedCS(), SetShaderParametersMixedGS(), SetShaderParametersMixedGS(), SetShaderParametersMixedMS(), SetShaderParametersMixedMS(), SetShaderParametersMixedPS(), SetShaderParametersMixedPS(), SetShaderParametersMixedVS(), SetShaderParametersMixedVS(), SetShaderParametersMixedWS(), IStereoLayers::FLayerDesc::SetShape(), TLinearCircularRamper< T >::SetTarget(), TAnimatedAttribute< NumericType >::SetValueAndStop(), Algo::Sort(), Algo::Sort(), Algo::SortBy(), Algo::SortBy(), UE::Insights::STableTreeView::StartTableDataTask(), FMaxErrorStatTracker< DataType, SortType, MaxItems >::StoreErrorStat(), UE::Core::Private::StringViewGetData(), FSharedBuffer::TakeOwnership(), FUniqueBuffer::TakeOwnership(), Algo::TopologicalSort(), Verse::FNativeConverter::ToVValue(), UCLASS(), Metasound::FInputVertexInterfaceData::UE_DEPRECATED(), Metasound::TVertexInterfaceImpl< VertexType >::UE_DEPRECATED(), UE::Tasks::Private::FTaskBase::UE_DEPRECATED(), UE::UE_DEPRECATED(), UENUM(), UENUM(), Experimental::RobinHoodHashTable_Private::TKeyValue< KeyType, ValueType >::Update(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Update(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::UpdateId(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::UpdateIdByHash(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), Visit(), UE::Core::Private::VisitApplyEncoded(), UE::Core::Private::VisitImpl(), VisitTupleElements(), UE::ParkingLot::Wait(), UE::ParkingLot::WaitFor(), UE::ParkingLot::WaitUntil(), UE::ParkingLot::WakeOne(), UE::DataValidation::IFixer::WrappedIn(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Write(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::WriteByHash(), and UE::MovieScene::FEntityManager::WriteComponentChecked().
ForwardAsBase() [1/2]
template<typename T, typename Base UE_REQUIRES> UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE decltype(auto) ForwardAsBase (std::remove_reference_t< T > && Obj)
Definition at line 796 of file UnrealTemplate.h.
References FORCEINLINE, UE_INTRINSIC_CAST, and UE_NODEBUG.
ForwardAsBase() [2/2]
template<typename T, typename Base UE_REQUIRES> UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE decltype(auto) ForwardAsBase (std::remove_reference_t< T > & Obj)
ForwardAsBase will cast a reference to an rvalue reference of a base type.
This allows the perfect forwarding of a reference as a base class.
Definition at line 786 of file UnrealTemplate.h.
References FORCEINLINE, UE_INTRINSIC_CAST, and UE_NODEBUG.
Referenced by UE::Core::Private::Tuple::TTupleElementGetterByIndex< 0, 2 >::Get(), and UE::Core::Private::Tuple::TTupleElementGetterByIndex< Index, TupleSize >::GetImpl().
GetData() [1/6]
template<typename T, SIZE_T N> const T * GetData (const T(&&) Container[N]) constexpr
Definition at line 87 of file UnrealTemplate.h.
References Container.
GetData() [2/6]
template<typename T, SIZE_T N> const T * GetData (const T(&) Container[N]) constexpr
Definition at line 86 of file UnrealTemplate.h.
References Container.
GetData() [3/6]
template<typename T> const T * GetData (std::initializer_list< T > List) constexpr
Definition at line 90 of file UnrealTemplate.h.
GetData() [4/6]
template<typename T UE_REQUIRES> auto GetData (T && Container) -> decltype(Container.GetData()) constexpr
Generically gets the data pointer of a contiguous container.
Definition at line 79 of file UnrealTemplate.h.
References Container.
GetData() [5/6]
template<typename T, SIZE_T N> T * GetData (T(&&) Container[N]) constexpr
Definition at line 85 of file UnrealTemplate.h.
References Container.
GetData() [6/6]
template<typename T, SIZE_T N> T * GetData (T(&) Container[N]) constexpr
Definition at line 84 of file UnrealTemplate.h.
References Container.
GetNum() [1/6]
template<typename T, SIZE_T N> SIZE_T GetNum (const T(&&) Container[N]) constexpr
Definition at line 110 of file UnrealTemplate.h.
References Container.
GetNum() [2/6]
template<typename T, SIZE_T N> SIZE_T GetNum (const T(&) Container[N]) constexpr
Definition at line 109 of file UnrealTemplate.h.
References Container.
GetNum() [3/6]
template<typename T> int32 GetNum (std::initializer_list< T > List) constexpr
Gets the number of items in an initializer list.
The return type is int32 for compatibility with other code in the engine. Realistically, an initializer list should not exceed the limits of int32.
Definition at line 119 of file UnrealTemplate.h.
GetNum() [4/6]
template<typename T UE_REQUIRES> auto GetNum (T && Container) -> decltype(Container.Num()) constexpr
Generically gets the number of items in a contiguous container.
Definition at line 102 of file UnrealTemplate.h.
References Container.
GetNum() [5/6]
template<typename T, SIZE_T N> SIZE_T GetNum (T(&&) Container[N]) constexpr
Definition at line 108 of file UnrealTemplate.h.
References Container.
GetNum() [6/6]
template<typename T, SIZE_T N> SIZE_T GetNum (T(&) Container[N]) constexpr
Definition at line 107 of file UnrealTemplate.h.
References Container.
ImplicitConv()
template<typename T> FORCEINLINE T ImplicitConv (typename TIdentity< T >::Type Obj)
Uses implicit conversion to create an instance of a specific type.
Useful to make things clearer or circumvent unintended type deduction in templates. Safer than C casts and static_casts, e.g. does not allow down-casts
Parameters
Obj The object (usually pointer or reference) to convert.
Returns
The object converted to the specified type.
Definition at line 772 of file UnrealTemplate.h.
References FORCEINLINE.
Referenced by FCbFieldViewIterator::FCbFieldViewIterator(), FFieldVariant::FFieldVariant(), FObjectKey::FObjectKey(), FWeakObjectPtr::FWeakObjectPtr(), TMemoryView< const void >::TMemoryView(), TObjectKey< URigVM >::TObjectKey(), TObjectPtr< T >::TObjectPtr(), TScriptInterface< const InterfaceType >::TScriptInterface(), TWeakInterfacePtr< IActorInstanceManagerInterface >::TWeakInterfacePtr(), FArchive::GetArchiveState(), FArchive::GetArchiveState(), TStringView< TCHAR >::operator!=, TStringView< TCHAR >::operator!=, TStringView< TCHAR >::operator<, TStringView< TCHAR >::operator<, operator<<(), FBindingObject::operator=(), TObjectPtr< T >::operator=(), TStringView< TCHAR >::operator==, and TStringView< TCHAR >::operator==.
IntCastChecked()
template<typename OutType, typename InType> OutType IntCastChecked (InType In)
Cast and check that value fits in OutType.
Definition at line 171 of file UnrealTemplate.h.
References checkf, INT64_FMT, IntFitsIn(), TEXT, and UINT64_FMT.
Referenced by FBlackboard::FKey::FKey(), FTextureLayout::FTextureLayout(), FTextureLayout3d::FTextureLayout3d(), UE::Math::TIntPoint< IntType >::TIntPoint(), UE::Math::TIntVector2< int32 >::TIntVector2(), UE::Math::TIntVector3< InIntType >::TIntVector3(), UE::Math::TIntVector3< int32 >::TIntVector3(), UE::Math::TIntVector4< int32 >::TIntVector4(), TStringView< TCHAR >::TStringView(), FTextureLayout3d::AddSurfaceInner(), FTextureLayout::AddSurfaceInner(), FMaterialResourceMemoryWriter::BeginSerializingMaterialResource(), TSimpleCellGrid< CellType, InvalidCellValue >::GetAllocatedSize(), TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoordsUnsafe(), TDefaultNumericTypeInterface< NumericType >::GetMaxFractionalDigits(), TDefaultNumericTypeInterface< NumericType >::GetMinFractionalDigits(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), UE::Math::TIntRect< int32 >::Scale(), UE::FPlatformIoDispatcherBase::ScatterGather(), FObjectReader::Serialize(), FTransactionallySafeArchiveWriter::Serialize(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Serialize(), TDefaultNumericTypeInterface< NumericType >::SetMaxFractionalDigits(), TDefaultNumericTypeInterface< NumericType >::SetMinFractionalDigits(), and USTRUCT().
IntFitsIn()
template<typename OutType, typename InType> bool IntFitsIn (InType In) constexpr
Test if value can make a lossless static_cast roundtrip via OutType without a sign change.
Definition at line 151 of file UnrealTemplate.h.
Referenced by ICompressionFormat::Compress(), ICompressionFormat::GetCompressedBufferSize(), IntCastChecked(), and ICompressionFormat::Uncompress().
MaxElement() [1/2]
template<class ForwardIt> ForwardIt MaxElement (ForwardIt First, ForwardIt Last) inline
works just like std::max_element.
Definition at line 291 of file UnrealTemplate.h.
References First, and Last.
MaxElement() [2/2]
template<class ForwardIt, class PredicateType> ForwardIt MaxElement (ForwardIt First, ForwardIt Last, PredicateType Predicate) inline
works just like std::max_element.
Definition at line 308 of file UnrealTemplate.h.
References First, Last, and Predicate.
MinElement() [1/2]
template<class ForwardIt> ForwardIt MinElement (ForwardIt First, ForwardIt Last) inline
works just like std::min_element.
Definition at line 257 of file UnrealTemplate.h.
References First, and Last.
MinElement() [2/2]
template<class ForwardIt, class PredicateType> ForwardIt MinElement (ForwardIt First, ForwardIt Last, PredicateType Predicate) inline
works just like std::min_element.
Definition at line 274 of file UnrealTemplate.h.
References First, Last, and Predicate.
Move() [1/2]
template<typename T> FORCEINLINE void Move (T & A, typename TMoveSupportTraits< T >::Copy B)
This is used to provide type specific behavior for a copy which cannot change the value of B.
Definition at line 52 of file UnrealTemplate.h.
References A, B, and FORCEINLINE.
Referenced by TRefCountPtr< FBaseGraphTask >::TRefCountPtr(), TRefCountPtr< FBaseGraphTask >::TRefCountPtr(), FNetworkPredictionData_Client_Character::FreeMove(), PREDECLARE_GEOMETRY(), and PREDECLARE_USE_GEOMETRY_CLASS().
Move() [2/2]
template<typename T> FORCEINLINE void Move (T & A, typename TMoveSupportTraits< T >::Move B)
This is used to provide type specific behavior for a move which may change the value of B.
Definition at line 63 of file UnrealTemplate.h.
References A, B, FORCEINLINE, and MoveTemp().
MoveTemp()
template<typename T> UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr std::remove_reference_t< T > && MoveTemp (T && Obj) constexpr noexcept
MoveTemp will cast a reference to an rvalue reference.
This is UE's equivalent of std::move except that it will not compile when passed an rvalue or const object, because we would prefer to be informed when MoveTemp will have no effect.
Definition at line 549 of file UnrealTemplate.h.
References FORCEINLINE, UE_INTRINSIC_CAST, and UE_NODEBUG.
Referenced by FAAArrayQueue< T >::DequeueHazard::DequeueHazard(), FAAArrayQueue< T >::EnqueueHazard::EnqueueHazard(), UAbilitySystemComponent::FAbilityListLockActiveChange::FAbilityListLockActiveChange(), FWorldPartitionLevelHelper::FActorPropertyOverridesAnnotation::FActorPropertyOverridesAnnotation(), FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer(), FAssetDataTagMap::FAssetDataTagMap(), UObject::FAssetRegistryTag::FAssetRegistryTag(), Metasound::Frontend::FAutoUpdateRootGraph::FAutoUpdateRootGraph(), UE::MediaIOCore::FBlendDeinterlacer::FBlendDeinterlacer(), UE::MediaIOCore::FBobDeinterlacer::FBobDeinterlacer(), UE::CurveEditor::FPositionMirrorSolver::FCachedCurveData::FCachedCurveData(), UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::FCachedData::FCachedData(), UE::Sequencer::SOutlinerView::FCachedGeometry::FCachedGeometry(), UE::Anim::FCachedPoseSkippedUpdateHandler::FCachedPoseSkippedUpdateHandler(), FCbAttachment::FCbAttachment(), FCbAttachment::FCbAttachment(), FCbPackage::FCbPackage(), FCbPackage::FCbPackage(), FCbPackage::FCbPackage(), FCbPackage::FCbPackage(), FCharacterMovementComponentAsyncOutput::FCharacterMovementComponentAsyncOutput(), FRenderCommandPipe::FCommand::FCommand(), FRenderThreadCommandPipe::FCommand::FCommand(), FCompoundChange::FCompoundChange(), FCompoundChangeInput::FCompoundChangeInput(), FConfigValue::FConfigValue(), FConfigValue::FConfigValue(), FConfigValue::FConfigValue(), FInstanceAttributeTracker::FDeltaRange< Flag >::FConstIterator::FConstIterator(), FMeshElementContainer::FElementIDs::FConstIterator::FConstIterator(), FChildren::FConstWidgetRef::FConstWidgetRef(), FChildren::FConstWidgetRef::FConstWidgetRef(), UE::Geometry::FConvexShape3d::FConvexShape3d(), UE::Cook::FCookDependencyContext::FCookDependencyContext(), FCrashStackFrame::FCrashStackFrame(), UE::CurveEditor::FCurveTangentMirrorData::FCurveTangentMirrorData(), UE::CurveEditor::FCurveTangentMirrorData::FCurveTangentMirrorData(), UE::MediaIOCore::FDeinterlacer::FDeinterlacer(), Metasound::FGraph::FDeprecationNodeStorageAdapter::FDeprecationNodeStorageAdapter(), UE::MediaIOCore::FDiscardDeinterlacer::FDiscardDeinterlacer(), UE::FDynamicallyTypedValue::FDynamicallyTypedValue(), FEdGraphSchemaAction_Dummy::FEdGraphSchemaAction_Dummy(), FEditMeshPolygonsToolMeshChange::FEditMeshPolygonsToolMeshChange(), FMovieSceneExecutionTokens::FEntry::FEntry(), FEraseToBaseMeshBrushOp::FEraseToBaseMeshBrushOp(), Metasound::FExecuter::FExecuter(), Metasound::TVariableNode< DataType >::FFactory::FFactory(), FFileSystemError::FFileSystemError(), FFixToken::FFixToken(), FFormatArgumentValue::FFormatArgumentValue(), FFutureState::FFutureState(), UE::FGenericPlatformIoDispatcher::FGenericPlatformIoDispatcher(), FSlateAttributeMetaData::FGetterItem::FGetterItem(), FSlateAttributeMetaData::FGetterItem::FGetterItem(), FGroomBindingAsyncBuildTask::FGroomBindingAsyncBuildTask(), FGroomBindingAsyncBuildWorker::FGroomBindingAsyncBuildWorker(), FHandleToCmdIndex::FHandleToCmdIndex(), FHistoricTextFormatData::FHistoricTextFormatData(), FInertializationCurve::FInertializationCurve(), FInitBodiesHelperWithData< bCompileStatic >::FInitBodiesHelperWithData(), FInitBodiesHelperWithData< bCompileStatic >::FInitBodiesHelperWithData(), Metasound::FMetaSoundParameterTransmitter::FInitParams::FInitParams(), FInputActionUnifiedDelegate::FInputActionUnifiedDelegate(), FInputActionUnifiedDelegate::FInputActionUnifiedDelegate(), FInputActionUnifiedDelegate::FInputActionUnifiedDelegate(), FInstanceUpdateChangeSet::FInstanceUpdateChangeSet(), UE::FIoPlatformReadRequest::FIoPlatformReadRequest(), UE::FIoPlatformReadRequest::FIoPlatformReadRequest(), FKeyChain::FKeyChain(), FLambdaMeshSculptBrushOpFactory::FLambdaMeshSculptBrushOpFactory(), UE::Geometry::FLevelSetShape3d::FLevelSetShape3d(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::FLiveLinkBaseDataStruct(), FLocItem::FLocItem(), FLocItem::FLocItem(), FLocKey::FLocKey(), FLocKey::FLocKey(), FManagedStorageFileWriteHandle::FManagedStorageFileWriteHandle(), FManagedStorageScopeFileLock::FManagedStorageScopeFileLock(), FMemStackBase::FMemStackBase(), FMeshElementContainer::FMeshElementContainer(), FMetasoundParameterPackStorage::FMetasoundParameterPackStorage(), HarmonixMetasound::FMidiClockEvent::FMidiClockEvent(), FMovieSceneChannelProxy::FMovieSceneChannelProxy(), FMovieSceneClipboardKey::FMovieSceneClipboardKey(), FMovieSceneEvaluationTree::FMovieSceneEvaluationTree(), Verse::FNativeString::FNativeString(), UE::SequenceNavigator::FNavigationToolFilter_ItemType< InItemType >::FNavigationToolFilter_ItemType(), FNetAsyncLoadDelinquencyAnalytics::FNetAsyncLoadDelinquencyAnalytics(), FNetQueuedActorDelinquencyAnalytics::FNetQueuedActorDelinquencyAnalytics(), FTextLayout::FNewLineData::FNewLineData(), FNewSpawnable::FNewSpawnable(), Metasound::FNodeFacade::FNodeFacade(), FNotificationButtonInfo::FNotificationButtonInfo(), FNotificationButtonInfo::FNotificationButtonInfo(), FObjectPtr::FObjectPtr(), FPackageReloadedEvent::FPackageReloadedEvent(), FPackedLevelActorBuilderClusterID::FPackedLevelActorBuilderClusterID(), FPackedLevelActorBuilderClusterID::FPackedLevelActorBuilderClusterID(), FPathAndMountPoint::FPathAndMountPoint(), FPersistentStorageCategory::FPersistentStorageCategory(), FPinConnectionResponse::FPinConnectionResponse(), FPinConnectionResponse::FPinConnectionResponse(), Audio::FQuartzOffset::FQuartzOffset(), Audio::FQuartzOffset::FQuartzOffset(), FRDGDispatchPass::FRDGDispatchPass(), FRDGPooledBuffer::FRDGPooledBuffer(), FRDGSentinelPass::FRDGSentinelPass(), UE::Text::Private::FRefCountedDisplayString::FRefCountedDisplayString(), FReferenceChainSearch::FReferenceChain::FReferenceChain(), UE::AnimNext::FDataRegistry::FReferencePoseData::FReferencePoseData(), FReplayExternalData::FReplayExternalData(), FRepStateStaticBuffer::FRepStateStaticBuffer(), FRigVMPinConnectionResponse::FRigVMPinConnectionResponse(), FSyntaxTokenizer::FRule::FRule(), FRunInfo::FRunInfo(), FSavePackageContext::FSavePackageContext(), FScopedAdditionalCrashContextProvider::FScopedAdditionalCrashContextProvider(), FScopedDurationTimeLogger::FScopedDurationTimeLogger(), SBoxPanel::FScopedWidgetSlotArguments< SlotType >::FScopedWidgetSlotArguments(), TPanelChildren< SlotType >::FScopedWidgetSlotArguments::FScopedWidgetSlotArguments(), TPanelChildren< SlotType >::FScopedWidgetSlotArguments::FScopedWidgetSlotArguments(), FSequencerTrackFilter_ClassType< InClassType >::FSequencerTrackFilter_ClassType(), FSequencerTrackFilter_ComponentType< InComponentType >::FSequencerTrackFilter_ComponentType(), FSequencerTrackFilter_ModelType< InModelType >::FSequencerTrackFilter_ModelType(), FShaderCompilerError::FShaderCompilerError(), FShaderCompilerError::FShaderCompilerError(), FShaderKeyGenerator::FShaderKeyGenerator(), FShaderPreloadData::FShaderPreloadData(), FShadowMap::FShadowMap(), IStereoLayers::FShapeWrapper::FShapeWrapper(), FRedirectCollector::FSimpleOrChainedRedirect::FSimpleOrChainedRedirect(), FRedirectCollector::FSimpleOrChainedRedirect::FSimpleOrChainedRedirect(), FSkeletalMeshLODModel::FSkeletalMeshLODModel(), FSkinnedAssetAsyncBuildTask::FSkinnedAssetAsyncBuildTask(), FSkinnedAssetAsyncBuildTask::FSkinnedAssetAsyncBuildTask(), FSkinnedAssetAsyncBuildTask::FSkinnedAssetAsyncBuildTask(), FSkinnedAssetAsyncBuildWorker::FSkinnedAssetAsyncBuildWorker(), FSkinnedAssetAsyncBuildWorker::FSkinnedAssetAsyncBuildWorker(), FSkinnedAssetAsyncBuildWorker::FSkinnedAssetAsyncBuildWorker(), TSlotBase< SlotType >::FSlotArguments::FSlotArguments(), GPUMessage::FSocket::FSocket(), FRedirectCollector::FSoftObjectPathProperty::FSoftObjectPathProperty(), FStandaloneCompositeFont::FStandaloneCompositeFont(), FStaticMeshAsyncBuildTask::FStaticMeshAsyncBuildTask(), FStaticMeshAsyncBuildTask::FStaticMeshAsyncBuildTask(), FStaticMeshAsyncBuildWorker::FStaticMeshAsyncBuildWorker(), FStaticMeshAsyncBuildWorker::FStaticMeshAsyncBuildWorker(), FixedTagPrivate::FStoreBuilder::FStoreBuilder(), FStringFormatArg::FStringFormatArg(), FSurfaceMaxSculptBrushOp::FSurfaceMaxSculptBrushOp(), FSurfaceSculptBrushOp::FSurfaceSculptBrushOp(), FText::FText(), FTextFormatString::FTextFormatString(), FTextFormatString::FTextFormatString(), TextFilterExpressionParser::FTextToken::FTextToken(), TextFilterExpressionParser::FTextToken::FTextToken(), TTypeContainer< Mode >::FThreadInstanceProvider::FThreadInstanceProvider(), FAssetThumbnailPool::FThumbId::FThumbId(), FTimerUnifiedDelegate::FTimerUnifiedDelegate(), HarmonixMetasound::MidiClockMessageTypes::FTimeSignatureChange::FTimeSignatureChange(), FTransactionallySafeArchiveWriter::FTransactionallySafeArchiveWriter(), TDirectoryTree< ValueType >::FTreeNode::FTreeNode(), FTypedElementCommonActionsElement::FTypedElementCommonActionsElement(), FRDGBuilder::FUploadedBuffer::FUploadedBuffer(), FRDGBuilder::FUploadedBuffer::FUploadedBuffer(), FRDGBuilder::FUploadedBuffer::FUploadedBuffer(), FRDGBuilder::FUploadedBuffer::FUploadedBuffer(), FVariant::FVariant(), FVariant::FVariant(), FVertexBufferAndSRV::FVertexBufferAndSRV(), FViewAlignedSculptBrushOp::FViewAlignedSculptBrushOp(), FViewportDisplayDelegate::FViewportDisplayDelegate(), FChildren::FWidgetRef::FWidgetRef(), FChildren::FWidgetRef::FWidgetRef(), UE::Geometry::FWindingNumberBasedSolidify::FWindingNumberBasedSolidify(), IBufferedCurveModel::IBufferedCurveModel(), UE::Geometry::FSmallListSet::MappedValueEnumerable::MappedValueEnumerable(), Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr(), TArrowWrapper< WrappedType >::TArrowWrapper(), TAsyncGraphTask< ResultType >::TAsyncGraphTask(), TAsyncQueuedWork< ResultType >::TAsyncQueuedWork(), TAsyncResult< ResultType >::TAsyncResult(), TAsyncResult< ResultType >::TAsyncResult(), TAsyncRunnable< ResultType >::TAsyncRunnable(), TAttribute< ObjectType >::TAttribute(), TAttribute< ObjectType >::TAttribute(), Metasound::TAudioReceiver< TDataType >::TAudioReceiver(), Metasound::TAudioSender< TDataType >::TAudioSender(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::TAutoConverterNode(), TAwaitableTask< ReturnType >::TAwaitableTask(), UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr(), UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr(), UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >::TBufferOwnerTArray(), TBVTree< InElementType, InAllocator >::TBVTree(), TCbBuffer< ViewType >::TCbBuffer(), TCbBuffer< ViewType >::TCbBuffer(), TCbBuffer< ViewType >::TCbBuffer(), TCbFieldIterator< FieldType >::TCbFieldIterator(), TCbFieldIterator< FieldType >::TCbFieldIterator(), TCompiledToken< TCHAR >::TCompiledToken(), TMeshElementArray< ElementType, ElementIDType >::TElementIDs::TConstIterator::TConstIterator(), TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator::TConstIterator(), TConstSharedStruct< BaseStructT >::TConstSharedStruct(), TConstSharedStruct< BaseStructT >::TConstSharedStruct(), TBlendableToken< DataType >::TData< T >::TData(), TDelegateBase< FThreadSafetyMode >::TDelegateBase(), TDelegateBase< FThreadSafetyMode >::TDelegateBase(), SharedPointerInternals::TDeleterHolder< DeleterType, bIsZeroSize >::TDeleterHolder(), SharedPointerInternals::TDeleterHolder< DeleterType, false >::TDeleterHolder(), Metasound::Frontend::NodeRegistrationPrivate::TDeprecatedNodeAPIAdapter< TNodeType >::TDeprecatedNodeAPIAdapter(), TDeque< InElementType, InAllocatorType >::TDeque(), CoroTask_Detail::TDummyType< T >::TDummyType(), UE::Sequencer::TDynamicExtensionContainerIterator< T >::TDynamicExtensionContainerIterator(), UE::Geometry::TDynamicVector< Type, BlockSize >::TDynamicVector(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::TEntityBuilderImpl(), UE::MovieScene::TEntityGroupingHandler< GroupingPolicy, ComponentTypes >::TEntityGroupingHandler(), UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::TEntityGroupingHandlerImpl(), UE::UnifiedError::TErrorDetails< T >::TErrorDetails(), UE::UnifiedError::TErrorDetails< T >::TErrorDetails(), UE::Tasks::Private::TExecutableTask< TaskBodyType >::TExecutableTask(), UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::TExecutableTaskBase(), UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, typename TEnableIf< std::is_same_v< TInvokeResult_T< TaskBodyType >, void > >::Type >::TExecutableTaskBase(), TExpressionToken< TCHAR >::TExpressionToken(), TFieldPtrAccessor< T >::TFieldPtrAccessor(), TFrameValue< ValueType >::TFrameValue(), TFrameValue< ValueType >::TFrameValue(), TFunctionGraphTaskImpl< Signature, SubsequentsMode >::TFunctionGraphTaskImpl(), TTypeContainer< Mode >::TFunctionInstanceProvider< T >::TFunctionInstanceProvider(), UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase(), UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase(), UE::Core::Private::Function::TFunctionStorage< bUnique >::TFunctionStorage(), TFutureBase< ResultType >::TFutureBase(), TFutureState< ResultType >::TFutureState(), TGuardValue_Bitfield_Cleanup< FuncType >::TGuardValue_Bitfield_Cleanup(), THashTable< FMemoryImageAllocator >::THashTable(), TInlineValue< FChannelOverrideProviderTraits, 64 >::TInlineValue(), Metasound::TInputNode< DataType, VertexAccess >::TInputNode(), Metasound::TInputNode< DataType, VertexAccess >::TInputNode(), TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::TInputUnifiedDelegate(), TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::TInputUnifiedDelegate(), TInstancedStruct< BaseStructT >::TInstancedStruct(), FMovieSceneClipboardKey::TKey< T >::TKey(), TKeyFrameManipulator< TimeType >::TKeyFrameManipulator(), GPUMessage::TLambdaHandler< LambdaType >::TLambdaHandler(), Metasound::TLiteralNode< DataType >::TLiteralNode(), Metasound::TLiteralOperatorLiteralFactory< DataType >::TLiteralOperatorLiteralFactory(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::TMap(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TMapBase(), UE::Geometry::TModelingOpTask< OpType >::TModelingOpTask(), UE::Cook::TMPCollectorClientMessageCallback< MessageType >::TMPCollectorClientMessageCallback(), UE::Cook::TMPCollectorServerMessageCallback< MessageType >::TMPCollectorServerMessageCallback(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::TMulticastDelegateBase(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::TMulticastScriptDelegate(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::TMulticastScriptDelegate(), UE::TMultiUniqueLock< TLockType >::TMultiUniqueLock(), Verse::TNativeSubtype< T, FNativeCastableType >::TNativeSubtype(), TNetworkPredictionBuffer< ElementType, SingleElement >::TNetworkPredictionBuffer(), TQueue< T, Mode >::TNode::TNode(), Metasound::TNodeFacade< TArrayNumOperator< ArrayType > >::TNodeFacade(), TObjectCacheIterator< T >::TObjectCacheIterator(), TObjectPtr< T >::TObjectPtr(), UE::Slate::Containers::TObservableArray< InElementType >::TObservableArray(), Metasound::TOutputNode< DataType, VertexAccess >::TOutputNode(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::TPagedArray(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::TPreAnimatedStateStorage(), TPromise< ResultType >::TPromise(), TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::TPropertyTrackExecutionToken(), FWatchablePropertySet::TPropertyWatcher< PropType >::TPropertyWatcher(), FWatchablePropertySet::TPropertyWatcher< PropType >::TPropertyWatcher(), SharedPointerInternals::TRawPtrProxyWithDeleter< ObjectType, DeleterType >::TRawPtrProxyWithDeleter(), TRDGDispatchPass< ParameterStructType, LaunchLambdaType >::TRDGDispatchPass(), TRDGEmptyLambdaPass< ExecuteLambdaType >::TRDGEmptyLambdaPass(), TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::TRDGLambdaPass(), SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >::TReferenceControllerWithDeleter(), TRingBuffer< T, AllocatorT >::TRingBuffer(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::TRobinHoodHashTable(), TSet< class UObject * >::TSet(), TSet< class UObject * >::TSet(), TSharedFuture< ResultType >::TSharedFuture(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedRef< INavigationToolItem >::TSharedRef(), TSharedRef< INavigationToolItem >::TSharedRef(), TSharedStruct< BaseStructT >::TSharedStruct(), TSoftObjectPtr< const T >::TSoftObjectPtr(), TSoftObjectPtr< const T >::TSoftObjectPtr(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TSortableMapBase(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::TSortedMap(), TTypeContainer< Mode >::TThreadInstanceProvider< T >::TThreadInstanceProvider(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap(), FMovieSceneAccumulatedBlendState::TTokenEntry< DataType >::TTokenEntry(), TTuple< const UFleshAsset *, const UFleshComponent *, FTransform >::TTuple(), UE::CurveEditor::TUniformMirrorSolver< TNumeric >::TUniformMirrorSolver(), TUniqueFunction< Ret(ParamTypes...)>::TUniqueFunction(), TUniqueObj< T >::TUniqueObj(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::TUniquePtr(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::TUniquePtr(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::TUniquePtr(), TUniquePtr< T[], Deleter >::TUniquePtr(), TUniquePtr< T[], Deleter >::TUniquePtr(), TUniquePtr< T[], Deleter >::TUniquePtr(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::TValueOrError(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::TValueOrError(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::TValueOrError(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::TValueOrError(), TValueOrError< ValueType, void >::TValueOrError(), TValueOrError< ValueType, void >::TValueOrError(), TValueOrError< void, ErrorType >::TValueOrError(), TValueOrError< void, ErrorType >::TValueOrError(), Metasound::TVariableNode< DataType >::TVariableNode(), Metasound::TVariableNode< DataType >::TVariableNode(), Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::TVertexAnalyzerForwardValue(), Metasound::TVertexInterfaceImpl< VertexType >::TVertexInterfaceImpl(), TWeakPtr< INavigationToolItem >::TWeakPtr(), TWeakPtr< INavigationToolItem >::TWeakPtr(), TWidgetFactory< UUserWidget >::TWidgetFactory(), TWidgetFactory< UUserWidget >::TWidgetFactory(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TYCombinator< LAMBDA >::TYCombinator(), SBoxPanel::FScopedWidgetSlotArguments< SlotType >::~FScopedWidgetSlotArguments(), TPanelChildren< SlotType >::FScopedWidgetSlotArguments::~FScopedWidgetSlotArguments(), FTransactionallySafeArchiveWriter::~FTransactionallySafeArchiveWriter(), FSparseDelegate::__Internal_AddUnique(), Algo::Accumulate(), Algo::Accumulate(), FAcquiredResources::Add(), FAcquiredResources::Add(), FMovieSceneAccumulatedBlendState::Add(), FSimpleStreamableAssetManager::TSimpleSparseArray< T >::Add(), Metasound::TVertexInterfaceImpl< VertexType >::Add(), TEvaluationTreeEntryContainer< ElementType >::Add(), TMovieSceneEvaluationTree< DataType >::Add(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Add(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Add(), UE::Geometry::TSpatialPhotoSet< FVector4f, float >::Add(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Add(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Add(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::Add(), FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotation(), FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotation(), FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotation(), FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotation(), FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AddAnnotation(), FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::AddAnnotation(), FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AddAnnotationInternal(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddConditional(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::AddConditional(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::AddConditional(), Metasound::FDataReferenceCollection::AddDataReadReference(), Metasound::FDataReferenceCollection::AddDataWriteReference(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddDefaulted(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddDefaultedConditional(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal(), FFeedbackContext::AddError(), UE::Virtualization::FRehydrationResult::AddError(), UE::Virtualization::FVirtualizationResult::AddError(), Metasound::FFrontendQuery::AddFunctionStep(), TMovieSceneEvaluationTree< DataType >::AddIfEmpty(), TMovieSceneEvaluationTree< DataType >::AddIfEmptySelective(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddInternal(), FMovieSceneClipboardKeyTrack::AddKey(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddMutualComponents(), Metasound::TVertexInterfaceImpl< VertexType >::AddOrUpdateVertex(), AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FRDGScatterUploadBuilder::AddPass(), FRDGScatterUploadBuilder::AddPass_PreSized(), AddPassIfDebug(), FObjectInitializer::AddPropertyPostInitCallback(), AddReadbackBufferPass(), AddReadbackTexturePass(), ISceneRenderBuilder::AddRenderCommand(), ISceneRenderBuilder::AddRenderer(), FObjectCollectSaveOverridesContext::AddSaveOverride(), FObjectSaveContextData::AddSaveOverride(), TMovieSceneEvaluationTree< DataType >::AddSelective(), FMovieSceneExecutionTokens::AddShared(), FScopedWidgetSlotArguments< FNodeSlot >::AddSlot(), FScopedWidgetSlotArguments< FNodeSlot >::AddSlots(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddTag(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddTagConditional(), UE::CurveEditor::FTangentMirrorSolver::AddTangents(), UE::FChangeTransactor::AddTransactionChange(), TMovieSceneEvaluationTree< DataType >::AddUnique(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::AddUnique(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUniqueInternal(), FFeedbackContext::AddWarning(), Algo::AnyOf(), Algo::AnyOf(), FConfigFile::Append(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Append(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::Append(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Append(), FCompositeBuffer::AppendBuffers(), FCompositeBuffer::AppendBuffers(), FToolCommandChangeSequence::AppendChange(), FTextBuilder::AppendLineFormat(), UE::AnimNext::FEvaluateTraversalContext::AppendTask(), UE::AnimNext::FEvaluationProgram::AppendTask(), UE::MovieScene::TAdd< T >::Apply(), UE::MovieScene::TAddConditional< T >::Apply(), FCbField::AsArray(), FCbField::AsBinary(), FCbArray::AsField(), FCbObject::AsField(), FCbField::AsObject(), TSharedFromThis< ObjectType, Mode >::AsShared(), TSharedFromThis< ObjectType, Mode >::AsShared(), TTransArray< T >::AssignButKeepOwner(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::AssignPreAnimatedValue(), Async(), AsyncPool(), AsyncThread(), UE::Geometry::FDynamicMeshChange::AttachAttributeChanges(), FSlotBase::AttachWidget(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), TAttribute< ObjectType >::Bind(), UInputComponent::BindAction(), UInputComponent::BindAction(), UInputComponent::BindAction(), UInputComponent::BindAxis(), UInputComponent::BindAxis(), UInputComponent::BindAxisKey(), UInputComponent::BindAxisKey(), UInputComponent::BindGesture(), UInputComponent::BindKey(), UInputComponent::BindKey(), Metasound::Frontend::FVertexAnalyzerBase::BindOutputData(), UInputComponent::BindTouch(), UInputComponent::BindVectorAxis(), UInputComponent::BindVectorAxis(), FMovieSceneBlendingAccumulator::BlendToken(), FMovieSceneBlendingAccumulator::BlendToken(), FMovieSceneExecutionTokens::BlendToken(), Metasound::VertexPrivate::FEnvironmentDeclarationBuilder::Build(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue(), UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::CachePreAnimatedValue(), UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::CachePreAnimatedValue(), UE::MovieScene::TPreAnimatedPropertyStorageImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::CachePreAnimatedValues(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValuesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CacheTrackedPreAnimatedValue(), UE::FPlatformIoDispatcherBase::CancelRequest(), UE::Cook::IMPCollectorForMessage< MessageType >::ClientReceiveMessage(), UE::Cook::TMPCollectorClientMessageCallback< MessageType >::ClientReceiveMessage(), UE::Tasks::Private::FTaskBase::FSubsequents< AllocatorType >::Close(), TClosableMpscQueue< T >::Close_NonMember(), UE::FChangeTransactor::CloseTransaction(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::CollapseNodesInternal(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), IMeshDescriptionCommitter::CommitMeshDescription(), TPackageWriterToSharedBuffer< IPackageWriter >::CommitPackage(), FPackageWriterToRecord::CommitPackageInternal(), TEvaluationTreeEntryContainer< ElementType >::Compact(), TMeshElementArrayBase< ElementType >::Compact(), Algo::Compare(), Algo::CompareBy(), Algo::CompareBy(), UE::FPlatformIoDispatcherBase::CompleteEncodedBlockRequest(), TDirectoryTree< ValueType >::FTreeNode::ConditionalCompactNode(), SSegmentedControl< OptionType >::Construct(), SUniformGridPanel::FSlot::Construct(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::Construct(), TWidgetSlotWithAttributeSupport< SlotType >::Construct(), UE::Core::Private::TMoveConstructorCaller< T >::Construct(), TPaddingSingleWidgetSlotMixin< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >, InPaddingInvalidationReason >::ConstructMixin(), TPaddingWidgetSlotMixin< MixedIntoType >::ConstructMixin(), TResizingWidgetSlotMixin< MixedIntoType >::ConstructMixin(), Metasound::TAudioDataChannel< TDataType >::ConstructNewReceiverImplementation(), Metasound::TAudioDataChannel< TDataType >::ConstructNewSenderImplementation(), FRedirectCollector::FSimpleOrChainedRedirect::ConstructSimpleOrChained(), TFuture< ResultType >::Consume(), UE::TConsumeAllMpmcQueue< T, AllocatorType >::ConsumeAll(), TIoStatusOr< T >::ConsumeValueOrDie(), Algo::ContainsBy(), TArrayAttribute< T >::ContainsByPredicate(), FCSPose< PoseType >::ConvertComponentPosesToLocalPoses(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::CopyFrom(), FMovieSceneChannelValueSetter::Create(), FMovieSceneClipboardKeyTrack::Create(), TAttribute< ObjectType >::Create(), TAttribute< ObjectType >::Create(), TBVTree< InElementType, InAllocator >::Create(), UE::FGenericPlatformIoDispatcherFactory::Create(), UE::FPlatformIoDispatcher::Create(), UE::Tasks::Private::TExecutableTask< TaskBodyType >::Create(), FFunctionGraphTask::CreateAndDispatchWhenReady(), FFunctionGraphTask::CreateAndDispatchWhenReady(), CreateByteAddressBuffer(), CreateByteAddressBuffer(), CreateByteAddressUploadBuffer(), CreateByteAddressUploadBuffer(), UE::FPlatformIoDispatcherRequestMgr::CreateDirectReadRequest(), ILiveLinkProvider::CreateLiveLinkProvider(), Metasound::DataFactoryPrivate::TDataVariantFactoryInternal< DataType, CreatorType >::CreateNewFromVariant(), Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >::CreateNode(), Metasound::TArrayGetOperator< ArrayType >::CreateOperator(), Metasound::TArraySetOperator< ArrayType >::CreateOperator(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory::CreateOperator(), TAttribute< ObjectType >::CreateRaw(), UE::FPlatformIoDispatcherRequestMgr::CreateScatterGatherRequest(), TAttribute< ObjectType >::CreateSP(), TAttribute< ObjectType >::CreateStatic(), CreateStructuredBuffer(), CreateStructuredBuffer(), TAnimatedAttribute< NumericType >::CreateWithGetter(), UE::FSourceLocation::Current(), DECLARE_DELEGATE(), DECLARE_MULTICAST_DELEGATE_OneParam(), FMaterial::DeferredDeleteArray(), UE::MovieScene::FEntityManager::DefineInstancedChildInitializer(), UE::MovieScene::FPropertyRegistry::DefinePropertyImpl(), TManagedStoragePlatformFile< BaseClass >::DeleteFiles(), TCircularQueue< T >::Dequeue(), TMpscQueue< T, AllocatorType >::Dequeue(), TQueue< T, Mode >::Dequeue(), TSpscQueue< T, AllocatorType >::Dequeue(), LowLevelTasks::DoReserveWorkUntil(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::DrainPool(), ITypedElementWorldInterface::DuplicateElement(), FScopedWidgetSlotArguments< FNodeSlot >::Empty(), TSlotlessChildren< ChildType >::Empty(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Empty(), UE::PixelStreaming2::FEpicRtcDataTrack::EncodeMessage(), FRenderCommandPipe::Enqueue(), FRenderCommandPipe::Enqueue(), FRenderCommandPipe::Enqueue(), FRenderCommandPipe::Enqueue(), FRenderCommandPipe::Enqueue(), FRenderThreadCommandPipe::Enqueue(), TCircularQueue< T >::Enqueue(), TQueue< T, Mode >::Enqueue(), FRenderCommandPipe::EnqueueAndLaunch(), FRenderCommandPipe::EnqueueAndLaunch(), UE::FPlatformIoDispatcherBase::EnqueueBlockToDecode(), FCanvasRenderThreadScope::EnqueueRenderCommand(), FRenderThreadScope::EnqueueRenderCommand(), EnqueueUniqueRenderCommand(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), FRDGDispatchPass::Execute(), FRenderCommandPipe::ExecuteCommand(), FRenderCommandPipe::ExecuteCommand(), ExecuteOnGameThread(), TSlateDecl< WidgetType, RequiredArgsPayloadType >::Expose(), TSlateDecl< WidgetType, RequiredArgsPayloadType >::Expose(), TSlateDecl< WidgetType, RequiredArgsPayloadType >::Expose(), TSequencerChannelInterfaceCommon< ChannelType >::ExtendKeyMenu_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::ExtendSectionMenu_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::ExtendSidebarMenu_Raw(), UE::Geometry::FSubRegionRemesher::ExtractFinalTriangleROI(), UE::Geometry::TModelingOpTask< OpType >::ExtractOperator(), FDynamicMeshGroupEditBuilder::ExtractResult(), TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::ExtractResult(), UE::Geometry::FDynamicMeshOperator::ExtractResult(), UE::Geometry::TGenericDataOperator< ResultDataType >::ExtractResult(), TLocklessGrowingStorage< T >::ExtractShards(), FAAArrayQueue< T >::DequeueHazard::FAAArrayQueue< T >, SScrollBox::FSlot::FillContentSize(), SScrollBox::FSlot::FillSize(), FShaderCode::FinalizeShaderCode(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindAndRemoveChecked(), Algo::FindBy(), Algo::FindByPredicate(), TArrayAttribute< T >::FindByPredicate(), FAndroidWindowManager::FindFromANativeWindow(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles(), Algo::FindLastBy(), Algo::FindLastByPredicate(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAdd(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAdd(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAdd(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAdd(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAdd(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAdd(), Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAdd(), Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAdd(), TDirectoryTree< ValueType >::FTreeNode::FindOrAdd(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindOrAdd(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddId(), Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddId(), Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::FindOrAddIdByHash(), Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddIdByHash(), Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddIdByHash(), FMovieSceneClipboardBuilder::FindOrAddKeyTrack(), FReplayHelper::FindOrAddLevelStatus(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrTryProduceAndApply(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrTryProduceAndApplyForWrite(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrUpdateIdByHashInternal(), FAudioDevice::ForEachSubsystem(), FAudioSubsystemCollection::ForEachSubsystem(), FObjectSubsystemCollection< TBaseType >::ForEachSubsystemWithInterface(), FText::Format(), TStringFormatter< CharType >::Format(), TStringFormatter< CharType >::Format(), FText::FormatNamed(), FText::FormatOrdered(), Nanite::FStreamingManager::GetAndClearModifiedResources(), FLiveLinkProvider::GetAnnotations(), FCompressedBuffer::GetCompressed(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::GetError(), TValueOrError< void, ErrorType >::GetError(), FFeedbackContext::GetErrorsAndWarningsAndEmpty(), FAndroidWindowManager::GetMainWindowAsNativeAccessor(), Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::GetMemberAccessPtr(), UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::TDirectPropertyTraits< float >::GetObjectPropertyValue(), TCbBuffer< ViewType >::GetOuterBuffer(), FPersistentStorageManager::GetPersistentStorageUsage(), SMInstanceElementDataUtil::GetSMInstancesFromHandles(), SMInstanceElementDataUtil::GetSMInstancesFromHandlesChecked(), IWorldPartitionStreamingSourceProvider::GetStreamingSources(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::GetValue(), TValueOrError< ValueType, void >::GetValue(), Verse::TFromVValue< NativeType, typename >::GetValue(), FTokenizedMessageAccumulatorErrorHandler::HandleTokenizedMessage(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPop(), Algo::HeapSort(), Algo::HeapSortBy(), SSegmentedControl< OptionType >::FSlot::if(), SSegmentedControl< OptionType >::FSlot::if(), SSegmentedControl< OptionType >::FSlot::if(), SSegmentedControl< OptionType >::FSlot::if(), SSegmentedControl< OptionType >::FSlot::if(), Algo::Includes(), Algo::IncludesBy(), Algo::IncludesBy(), Algo::IndexOfBy(), Algo::IndexOfByPredicate(), TArrayAttribute< T >::IndexOfByPredicate(), FFolderDragDropOp::Init(), FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::Init(), TStaticSpatialIndex< ValueType, Profile, SpatialIndexType, ElementsSorter >::Init(), UChaosVehicleSimulation::Init(), UE::ChaosDeformable::FFloatArrayBufferWithSRV::Init(), FBaseCompactPose< InAllocator >::InitFrom(), UE::Geometry::TMeshSurfaceUVSampler< SampleType >::Initialize(), TStructOnScope< T >::InitializeFrom(), TStructOnScope< T >::InitializeFromChecked(), FCSPose< PoseType >::InitPose(), TEvaluationTreeEntryContainer< ElementType >::Insert(), TDirectoryTree< ValueType >::FTreeNode::InsertChildNode(), FScopedWidgetSlotArguments< FNodeSlot >::InsertSlot(), Algo::IntroSort(), Algo::IntroSortBy(), Algo::IntroSortBy(), Algo::IsHeap(), Algo::IsHeapBy(), Algo::IsHeapBy(), Algo::IsSorted(), Algo::IsSortedBy(), Algo::IsSortedBy(), FText::Join(), UE::String::JoinBy(), UE::String::JoinQuotedBy(), UE::String::JoinTupleBy(), UE::String::JoinTupleQuotedBy(), Algo::KahnTopologicalSort(), CoroTask_Detail::TDummyType< T >::Launch(), FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Launch(), TAsyncComponentDataComputeQueue< DataType >::LaunchJob(), Algo::LegacySort(), Algo::LegacySortBy(), Algo::LegacySortBy(), TSoftClassPtr< const T >::LoadAsync(), TSoftObjectPtr< const T >::LoadAsync(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FStreamableManager::LoadSynchronous(), FStreamableManager::LoadSynchronous(), FStreamableManager::LoadSynchronous(), FShaderPreprocessOutput::LogError(), UE::Cook::FCookDependencyContext::LogError(), UE::Cook::FCookDependencyContext::LogInvalidated(), MakeAttributeRaw(), MakeAttributeSP(), MakeAttributeSP(), MakeAttributeUObject(), UE::MovieScene::MakeChannelProxy(), FFontFaceData::MakeFontFaceData(), UE::MakeGenericPlatformIoDispatcher(), FFrameNumberDetailsCustomization::MakeInstance(), FCompressedBuffer::MakeOwned(), FCbFieldIterator::MakeRange(), FCbFieldIterator::MakeRangeView(), MakeSharedBufferFromArray(), FSequencerFilterSuggestion::MakeSimpleSuggestion(), FCbFieldIterator::MakeSingle(), MakeTextDisplayString(), MakeUniqueBufferFromArray(), TCbBufferFactory< Type, ViewType >::MakeView(), TCbBufferFactory< Type, ViewType >::MakeView(), FFutureState::MarkComplete(), Algo::MaxElement(), Algo::MaxElementBy(), Algo::MaxElementBy(), SScrollBox::FSlot::MaxSize(), TResizingWidgetSlotMixin< MixedIntoType >::FSlotArgumentsMixin::MaxSize(), Algo::MinElement(), Algo::MinElementBy(), Algo::MinElementBy(), SScrollBox::FSlot::MinSize(), TResizingWidgetSlotMixin< MixedIntoType >::FSlotArgumentsMixin::MinSize(), Algo::Mismatch(), Algo::MismatchBy(), Algo::MismatchBy(), FBlueprintActionUiSpec::Move(), FScopedWidgetSlotArguments< FNodeSlot >::Move(), LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::Move(), Move(), template FRangedForSupport< FBaseCompactPose, FCompactPoseBoneIndexIterator >::MoveBones(), FBaseCompactPose< InAllocator >::MoveBonesFrom(), FBaseCompactPose< InAllocator >::MoveBonesTo(), FShaderCacheSerializeContext::MoveCode(), FUObjectSerializeContext::MoveDelayedLinkerClosePackages(), FShaderPreprocessOutput::MoveDirectives(), TBaseBlendedCurve< InAllocatorType, InElementType >::MoveFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::MoveFrom(), UE::Geometry::FMeshRegionGraph::MoveRegionTris(), UE::Geometry::TConvexHull3< float >::MoveTriangles(), UE::Sequencer::FCreateBindingParams::Name(), TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues(), UE::MovieScene::FComponentRegistry::NewComponentType(), UE::MovieScene::FComponentRegistry::NewComponentTypeNoAddReferencedObjects(), FStringTableEntry::NewStringTableEntry(), TFutureBase< ResultType >::Next(), Chaos::TUserDataManagerPT< TUserData >::OnPreSimulate_Internal(), TManagedStoragePlatformFile< BaseClass >::OpenWrite(), CoroTask_Detail::TDummyType< T >::operator T(), TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::operator+(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::operator+(), Verse::FNativeString::operator+, Verse::FNativeString::operator+, RangedForIteratorType< FAnimNextTraitEventPtr >::operator+=(), TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::operator-(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::operator-(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::operator=(), FAAArrayQueue< T >::DequeueHazard::operator=(), FAssetDataTagMap::operator=(), FConfigValue::operator=(), FConfigValue::operator=(), FCoroSpinLock::FScope::operator=(), FHandleToCmdIndex::operator=(), FKeyChain::operator=(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator=(), FLocKey::operator=(), FMeshElementContainer::operator=(), FMovieSceneEvaluationTree::operator=(), FObjectPtr::operator=(), FProgressCancel::FProgressScope::operator=(), FSkinWeightsVertexAttributesConstRef::operator=(), FSkinWeightsVertexAttributesRef::operator=(), FTextFormatString::operator=(), FVariant::operator=(), FVariant::operator=(), FVertexBufferAndSRV::operator=(), HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemPeekRef::operator=(), IStereoLayers::FShapeWrapper::operator=(), TAsyncResult< ResultType >::operator=(), TAwaitableTask< ReturnType >::operator=(), TBasicArray< T >::operator=(), TConstKeyIterator< FFixedObjectBindingID, FName >::operator=(), TDelegateBase< FThreadSafetyMode >::operator=(), TDeque< InElementType, InAllocatorType >::operator=(), TDirectoryTree< ValueType >::FTreeNode::operator=(), TextFilterExpressionParser::FTextToken::operator=(), TFrameValue< ValueType >::operator=(), TFrameValue< ValueType >::operator=(), THashTable< FMemoryImageAllocator >::operator=(), TIndirectArray< FChunk, AllocatorType >::operator=(), TInlineValue< FChannelOverrideProviderTraits, 64 >::operator=(), TInstancedStruct< BaseStructT >::operator=(), TKeyFrameManipulator< TimeType >::operator=(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::operator=(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator=(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::operator=(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::operator=(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::operator=(), TNetworkPredictionBuffer< ElementType, SingleElement >::operator=(), TObjectPtr< T >::operator=(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator=(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator=(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator=(), TSharedRef< INavigationToolItem >::operator=(), TSharedStruct< BaseStructT >::operator=(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator=(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::operator=(), TTuple< const UFleshAsset *, const UFleshComponent *, FTransform >::operator=(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator=(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator=(), TUniquePtr< T[], Deleter >::operator=(), TUniquePtr< T[], Deleter >::operator=(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::operator=(), TWeakPtr< INavigationToolItem >::operator=(), TWeakPtr< INavigationToolItem >::operator=(), TWidgetFactory< UUserWidget >::operator=(), UE::FDynamicallyTypedValue::operator=(), UE::Geometry::TDynamicVector< Type, BlockSize >::operator=(), UE::Geometry::TSparseGrid2< ElemType >::operator=(), UE::Geometry::TSparseGrid3< ElemType >::operator=(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator=(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator=(), UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator=(), UE::SharedBuffer::Private::TBufferOwnerPtr< UE::SharedBuffer::Private::FSharedOps >::operator=(), Verse::TNativeSubtype< T, FNativeCastableType >::operator=(), Verse::TToVValue< NativeType, typename >::operator=(), Verse::TToVValue< NativeType, typename >::operator=(), TSlotBase< SlotType >::FSlotArguments::operator[](), TSlotBase< SlotType >::operator[](), UE::MovieScene::Optimize(), TBaseBlendedCurve< InAllocatorType, InElementType >::OverrideMove(), LandscapeDataAccess::PackHeight(), TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::FSlotArgumentsMixin::Padding(), TPaddingSingleWidgetSlotMixin< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >, InPaddingInvalidationReason >::Padding(), TPaddingWidgetSlotMixin< MixedIntoType >::FSlotArgumentsMixin::Padding(), Algo::Partition(), TWeakPtr< INavigationToolItem >::Pin(), TAllocPlaybackLog< FModifier, FAllocOp >::Play(), UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::PopAll(), TRingBuffer< T, AllocatorT >::PopFrontValue(), TRingBuffer< T, AllocatorT >::PopValue(), UE::AnimNext::FEvaluationVM::PopValue(), FRDGScatterUploadBuilder::Process(), FRDGScatterUploadBuilder::Process_PreSized(), UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), UE::FPlatformIoDispatcherBase::ProcessDecodedBlock(), SModalEditorDialog< ResultType >::ProvideResult(), FAsyncAddPrimitiveQueue::Push(), FSendRenderDynamicDataPrimitivesQueue::Push(), TLocklessGrowingStorage< T >::Push(), UE::AnimNext::FTraitEventList::Push(), UE::Tasks::FTaskConcurrencyLimiter::Push(), UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::Push(), UE::UnifiedError::FError::PushErrorContext(), UE::AnimNext::TTraitBinding< IBlendStack >::PushGraph(), UE::AnimNext::FUpdateGraphContext::PushInputEvent(), UE::AnimNext::FEvaluationVM::PushValue(), TAsyncTreeDifferences< InNodeType >::QueueParallelNodeLists(), RadixSort64(), TDirectoryTree< ValueType >::FTreeNode::Realloc(), TRingBuffer< T, AllocatorT >::Reallocate(), Audio::Analytics::RecordEvent_Usage(), TBVTree< InElementType, InAllocator >::RecreateTree(), ISequencerModule::RegisterChannelInterface(), FConstraintChannelInterfaceRegistry::RegisterConstraintChannelInterface(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal(), GPUMessage::RegisterHandler(), Metasound::FAddressRouter::RegisterNewReceiver(), Metasound::FDataTransmissionCenter::RegisterNewReceiver(), Metasound::FAddressRouter::RegisterNewSender(), Metasound::FDataTransmissionCenter::RegisterNewSender(), ISequencerModule::RegisterSequenceEditor(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::ReindexBoneIndicesToSkeleton(), FTransactionallySafeArchiveWriter::Release(), Metasound::FExecuter::ReleaseOperator(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleasePooledResource(), UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >::RelocateConstructItems(), TAttributeArrayContainer< AttributeType >::Remap(), TMeshAttributeArrayBase< AttributeType >::Remap(), TMeshElementArrayBase< ElementType >::Remap(), TRingBuffer< T, AllocatorT >::RemoveAll(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::RemoveAndCopyValue(), FScopedWidgetSlotArguments< FNodeSlot >::RemoveAt(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::RemoveByElementId(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::RemoveByHash(), TDirectoryTree< ValueType >::FTreeNode::RemoveChildNodeAt(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::RemoveElement(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::RemoveElement(), IProjectExternalContentInterface::RemoveExternalContent(), Algo::RemoveIf(), TLruCache< KeyType, ValueType, KeyComp >::RemoveLeastRecent(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::ReplaceWith(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::ReplaceWith(), FStreamableManager::RequestAsyncLoad(), FStreamableManager::RequestSyncLoad(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Reserve(), TSlotlessChildren< ChildType >::Reset(), TNetworkPredictionBuffer< ElementType, SingleElement >::Resize(), TNetworkSimAuxBuffer< ElementType >::Resize(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::RestorePreAnimatedStateStorage(), TJugglingRotation< TGCDPolicy >::Rotate(), TDeltaSetup< ElementType, DeltaType >::FReader::Scatter(), TDeltaSetup< ElementType, DeltaType >::FReader::Scatter(), UE::FPlatformIoDispatcherBase::ScatterGather(), Algo::SelectRandomWeightedBy(), FStateTreeMinimalExecutionContext::SendEvent(), UE::Cook::IMPCollectorForMessage< MessageType >::ServerReceiveMessage(), UE::Cook::TMPCollectorServerMessageCallback< MessageType >::ServerReceiveMessage(), Metasound::TOutputStorage< DataType >::Set(), TAttribute< ObjectType >::Set(), TTlsAutoCleanupValue< TSharedPtr< T, Mode > >::Set(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Set(), SNodePanel::SNode::FNodeSlot::SetAllowScaling(), FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::SetAnnotationCacheKeyAndValue(), SButton::SetAppearPressed(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SetBuildOptions(), FPopupLayerSlot::SetClampBuffer(), FPopupLayerSlot::SetClampToWindow(), FShaderCompilerOutput::SetCodeFromResource(), SCompoundWidget::SetColorAndOpacity(), FFutureState::SetContinuation(), FAssetPackageData::SetCustomVersions(), FSlateCustomVertsElement::SetCustomVerts(), UE::MovieScene::FEntityManager::SetDebugName(), Metasound::TAudioSender< TDataType >::SetDelay(), FPopupLayerSlot::SetDesktopPosition(), SWidget::SetEnabled(), SInputKeySelector::SetEscapeKeys(), UE::Geometry::FMeshRefinerBase::SetExternalConstraints(), UE::FLogRecord::SetFields(), UPackage::SetFileSize(), SCompoundWidget::SetForegroundColor(), FShaderCode::SetFromResource(), FSlateGradientElement::SetGradient(), FSlateSplineElement::SetGradientHermiteSpline(), FPopupLayerSlot::SetHeightOverride(), SWidget::SetHover(), SSegmentedControl< OptionType >::FSlot::SetIcon(), FObjectThumbnail::SetImage(), FObjectThumbnail::SetImage(), FSlateTextureData::SetImage(), FSlateTextureData::SetImage(), UE::Geometry::FSubRegionRemesher::SetInitialVertexROI(), SListView< TSharedPtr< FString > >::SetItemsSource(), SListView< TSharedPtr< FString > >::SetItemsSource(), SInputKeySelector::SetKeySelectionText(), FSlateLineElement::SetLines(), FSlateLineElement::SetLines(), UPackage::SetLinkerCustomVersions(), UPackage::SetLinkerPackageVersion(), TResizingWidgetSlotMixin< MixedIntoType >::SetMaxSize(), TResizingWidgetSlotMixin< MixedIntoType >::SetMinSize(), SInputKeySelector::SetNoKeySpecifiedText(), FCbPackage::SetObject(), FCbPackage::SetObject(), FCbPackage::SetObject(), FCbPackage::SetObject(), Audio::FQuartzGameThreadSubscriber::SetOffset(), Metasound::FExecuter::SetOperator(), SNodePanel::SNode::FNodeSlot::SetPadding(), TPaddingSingleWidgetSlotMixin< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >, InPaddingInvalidationReason >::SetPadding(), TPaddingWidgetSlotMixin< MixedIntoType >::SetPadding(), UE::Virtualization::FPullRequest::SetPayload(), FutureDetail::SetPromiseValue(), FutureDetail::SetPromiseValue(), SWidget::SetRenderTransform(), SWidget::SetRenderTransformPivot(), UE::Geometry::TGenericDataOperator< ResultDataType >::SetResult(), STreeView< FRigVMSearchResult >::SetRootItemsSource(), STreeView< FRigVMSearchResult >::SetRootItemsSource(), FPopupLayerSlot::SetScale(), TResizingWidgetSlotMixin< MixedIntoType >::SetSizeParam(), TResizingWidgetSlotMixin< MixedIntoType >::SetSizeToStretch(), TResizingWidgetSlotMixin< MixedIntoType >::SetSizeToStretchContent(), SSplitter::FSlot::SetSizeValue(), SSplitter::FSlot::SetSizingRule(), SNodePanel::SNode::FNodeSlot::SetSlotOffset(), SNodePanel::SNode::FNodeSlot::SetSlotSize(), SSegmentedControl< OptionType >::FSlot::SetText(), FTimerManager::SetTimer(), FTimerManager::SetTimer(), FTimerManager::SetTimerForNextTick(), SSegmentedControl< OptionType >::FSlot::SetToolTip(), UStruct::SetUnresolvedScriptProperties(), FSavePackageContext::SetValidator(), Metasound::FMetasoundEnvironment::SetValue(), TDirectoryTree< ValueType >::FTreeNode::SetValue(), TPromise< ResultType >::SetValue(), FPopupLayerSlot::SetWidthOverride(), UPackage::SetWorldTileInfo(), TFuture< ResultType >::Share(), TRingBuffer< T, AllocatorT >::ShiftLastToFirst(), Nanite::FNaniteResourcesHelper::ShouldCreateNaniteProxy(), TGenericDataBackgroundCompute< ResultDataType >::Shutdown(), UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), SModalEditorDialog< ResultType >::SLATE_END_ARGS(), FDriverIdMetaData::SLATE_METADATA_TYPE(), TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >::SLATE_SLOT_BEGIN_ARGS_TwoMixins(), Algo::Sort(), Algo::SortBy(), Algo::SortBy(), Algo::StableRemoveIf(), Algo::StableSort(), Algo::StableSortBy(), Algo::StableSortBy(), UE::Geometry::TBackgroundModelingComputeSource< OpType, OpTypeFactory >::StartNewCompute(), TAttribute< ObjectType >::Steal(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::StealError(), TValueOrError< void, ErrorType >::StealError(), TSlotBase< SlotType >::FSlotArguments::StealSlot(), TValueOrError< TUniquePtr< IFileHandle >, FFileSystemError >::StealValue(), TValueOrError< ValueType, void >::StealValue(), TLocklessStaticStorage< T, 512 >::Store(), Swap(), UE::Geometry::FUniqueIndexSet::SwapValuesWith(), UE::Geometry::FMeshCurvatureMapBaker::TakeResult(), UE::Geometry::FMeshGenericWorldPositionColorBaker::TakeResult(), UE::Geometry::FMeshGenericWorldPositionNormalBaker::TakeResult(), UE::Geometry::FMeshNormalMapBaker::TakeResult(), UE::Geometry::FMeshOcclusionMapBaker::TakeResult(), UE::Geometry::FMeshPropertyMapBaker::TakeResult(), UE::Geometry::FMeshResampleImageBaker::TakeResult(), UE::Geometry::FUniqueIndexSet::TakeValues(), TFutureBase< ResultType >::Then(), FAsyncAddPrimitiveQueue::Tick(), FSendRenderDynamicDataPrimitivesQueue::Tick(), STreeView< FRigVMSearchResult >::Tick(), TConstKeyIterator< FFixedObjectBindingID, FName >::TMultiMap(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::ToArray(), FSharedBuffer::ToPrivateOwnerPtr, FUniqueBuffer::ToPrivateOwnerPtr, TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::ToSharedRef(), UE::Core::FVersePath::ToString(), Algo::TransformAccumulate(), Algo::TransformAccumulate(), TransformTuple(), TransformTuple(), UE::Geometry::FDelaunay2::Triangulate(), LowLevelTasks::FTask::TryFinish(), TFrameValue< ValueType >::TryGetValue(), TFrameValue< ValueType >::TryGetValue(), FPersistentStorageManager::TryManageFile(), SNodePanel::SNode::FNodeSlot::UE_DEPRECATED(), SNodePanel::SNode::FNodeSlot::UE_DEPRECATED(), STreeView< FRigVMSearchResult >::UE_DEPRECATED(), TSoftObjectPtr< const T >::UE_DEPRECATED(), UE::UE_DEPRECATED(), UE::Anim::FNamedValueArrayUtils::Union(), AlgoImpl::Unique(), UE::MovieScene::TOverlappingEntityInput< InputKeyTypes... >::Unpack(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::Update(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::Update(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::Update(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::Update(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::Update(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::Update(), TComponentReregisterContext< ComponentType >::UpdateAllPrimitiveSceneInfos(), UE::Cook::FAssetRegistryReporterLocal::UpdateAssetRegistryData(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateId(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateIdByHash(), Experimental::TRobinHoodHashMap< FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs >::UpdateIdByHash(), FMeshRenderBufferSet::UpdateRaytracingGeometryIfEnabled(), FScopedSkeletalMeshRenderData::USkeletalMesh, USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), FTaskGraphInterface::WaitUntilTaskCompletes(), and UE::StreamableManager::Private::WrapDelegate().
MoveTempIfPossible()
template<typename T> UE_INTRINSIC_CAST UE_NODEBUG FORCEINLINE constexpr std::remove_reference_t< T > && MoveTempIfPossible (T && Obj) constexpr noexcept
MoveTempIfPossible will cast a reference to an rvalue reference.
This is UE's equivalent of std::move. It doesn't static assert like MoveTemp, because it is useful in templates or macros where it's not obvious what the argument is, but you want to take advantage of move semantics where you can but not stop compilation.
Definition at line 567 of file UnrealTemplate.h.
References FORCEINLINE, UE_INTRINSIC_CAST, and UE_NODEBUG.
Referenced by TraceServices::TIntervalTimeline< EventType, SettingsType >::FEventInternal::FEventInternal(), TraceServices::TPointTimeline< EventType, SettingsType >::FEventInternal::FEventInternal(), PropertyTemplate::TCachedState< PropertyValueType, IntermediateType >::TCachedState(), TIoStatusOr< T >::TIoStatusOr(), TIoStatusOr< T >::TIoStatusOr(), TNetSimCueWrapper< TCue >::TNetSimCueWrapper(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::TOptional(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::TOptional(), Audio::Quartz::PrivateDefs::TVisitorPatternBase< Ts >::TVisitWithLambda< TargetInterface >::TVisitWithLambda(), FConfigFile::Add(), FConfigFile::Add(), FConfigFile::Add(), RangedForIteratorType< FAnimNextTraitEventPtr >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Add(), TRingBuffer< T, AllocatorT >::Add(), TSet< class UObject * >::Add(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add(), UE::Slate::Containers::TObservableArray< InElementType >::Add(), RangedForIteratorType< FAnimNextTraitEventPtr >::Add_GetRef(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Add_GetRef(), TRingBuffer< T, AllocatorT >::Add_GetRef(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash(), TSet< class UObject * >::AddByHash(), TRingBuffer< T, AllocatorT >::AddFront(), TRingBuffer< T, AllocatorT >::AddFront_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddUnique(), TConstKeyIterator< FFixedObjectBindingID, FName >::AddUnique(), TConstKeyIterator< FFixedObjectBindingID, FName >::AddUnique(), TConstKeyIterator< FFixedObjectBindingID, FName >::AddUnique(), TConstKeyIterator< FFixedObjectBindingID, FName >::Append(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Append(), UE::Slate::Containers::TObservableArray< InElementType >::Append(), FTrackInstancePropertyBindings::CallFunction(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CompactStable(), Algo::CompareMap(), TMpscQueue< T, AllocatorType >::Dequeue(), TSpscQueue< T, AllocatorType >::Dequeue(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::FindAndRemoveChecked(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::FindAndRemoveChecked(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd(), TSet< class UObject * >::FindOrAdd(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert_GetRef(), FNetSimCueDispatcher::Invoke(), TIoStatusOr< T >::operator=(), TIoStatusOr< T >::operator=(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::Pop(), RangedForIteratorType< FAnimNextTraitEventPtr >::Push(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Push(), TDeque< InElementType, InAllocatorType >::PushFirst(), Audio::Quartz::PrivateDefs::TQuartzCommandQueue< IMetronomeEventListener, ICommandListener, IQueueCommandListener >::PushLambda(), TDeque< InElementType, InAllocatorType >::PushLast(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::RemoveAndCopyValue(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValue(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::RemoveAndCopyValueByHash(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValueByHash(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::RemoveAtSwap(), Metasound::TSender< TDataType >::RetrievePayload(), FShaderCompilerEnvironment::SetCompileArgument(), TDeque< InElementType, InAllocatorType >::TryPopFirst(), and TDeque< InElementType, InAllocatorType >::TryPopLast().
ReverseBits()
template<typename T UE_REQUIRES> FORCEINLINE T ReverseBits (T Bits)
Reverses the order of the bits of a value.
This is a constrained template to ensure that no undesirable conversions occur. Overloads for other types can be added in the same way.
Parameters
Bits - The value to bit-swap.
Returns
The bit-swapped value.
Definition at line 689 of file UnrealTemplate.h.
References FORCEINLINE.
StaticCast()
template<typename T, typename ArgType> FORCEINLINE T StaticCast (ArgType && Arg)
This exists to avoid a Visual Studio bug where using a cast to forward an rvalue reference array argument to a pointer parameter will cause bad code generation.
Wrapping the cast in a function causes the correct code to be generated.
Definition at line 667 of file UnrealTemplate.h.
References FORCEINLINE.
Referenced by FLiveLinkBaseDataStruct< BaseType >::FCastImpl< Type >::Cast(), FLiveLinkBaseDataStruct< BaseType >::FCastImpl< Type >::ConstCast(), FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetDefault(), TPerPlatformProperty< _StructType, _ValueType, _BasePropertyName >::GetDefault(), FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetLowestValue(), TPerPlatformProperty< _StructType, _ValueType, _BasePropertyName >::GetValue(), TPerPlatformProperty< _StructType, _ValueType, _BasePropertyName >::GetValueForPlatform(), FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetValueForQualityLevel(), TKeyInitializer< KeyInitType >::operator TPair< KeyType, ValueType >(), TPairInitializer< KeyInitType, ValueInitType >::operator TPair< KeyType, ValueType >(), TActorDescContainerCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::operator*(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::operator*(), TActorDescList< DescType >::TBaseIterator< false, ActorType >::operator*(), TActorDescContainerCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::operator->(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::operator->(), TActorDescList< DescType >::TBaseIterator< false, ActorType >::operator->(), FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::SerializeFromMismatchedTag(), and TPerPlatformProperty< _StructType, _ValueType, _BasePropertyName >::SerializeFromMismatchedTag().
Swap()
template<typename T> void Swap (T & A, T & B) inline constexpr
Swap two values.
Assumes the types are trivially relocatable.
Definition at line 628 of file UnrealTemplate.h.
References A, B, Bytes, MoveTemp(), and TUseBitwiseSwap< T >::Value.
UE_DEPRECATED() [1/3]
template<typename ReferencedType> UE_DEPRECATED (5. 4, "IfAThenAElseB has been deprecated - use regular C++ constructs instead")
Chooses between the two parameters based on whether the first is nullptr or not.
Returns
If the first parameter provided is non-nullptr, it is returned; otherwise the second parameter is returned.
UE_DEPRECATED() [2/3]
template<typename PredicateType, typename ReferencedType> UE_DEPRECATED (5. 4, "IfPThenAElseB has been deprecated - use regular C++ constructs instead")
branchless pointer selection based on predicate return PTRINT(Predicate) ?
A : B;
UE_DEPRECATED() [3/3]
UE_DEPRECATED (5. 4, "XOR has been deprecated - use regular C++ constructs instead")
A logical exclusive or function.
References A, and B.
UEArrayCountHelper()
template<typename T, uint32 N> char(& UEArrayCountHelper (const T(&)[N]))[N+1]
Variable Documentation
A
ReferencedType* A
Definition at line 38 of file UnrealTemplate.h.
Referenced by FUInt128::FUInt128(), FUInt128::FUInt128(), FUInt128::FUInt128(), UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), TPimplPtr< T, EPimplPtrMode::DeepCopy >::TPimplPtr(), UE::Math::TPlane< T >::TPlane(), UE::Math::TPlane< double >::TPlane(), FWatchablePropertySet::TPropertyWatcher< PropType >::TPropertyWatcher(), TRange< float >::TRange(), TRange< float >::TRange(), UE::Math::TVector< NumericType >::TVector(), UE::Math::TVector4< U >::TVector4(), FGenericPlatformMath::Abs(), FGenericPlatformMath::Abs(), FGenericPlatformMath::Abs(), MIR::FEmitter::Abs(), Algo::Accumulate(), Algo::Accumulate(), MIR::FEmitter::ACos(), MIR::FEmitter::ACosh(), FMaterialCompiler::Add(), FProxyMaterialCompiler::Add(), MIR::FEmitter::Add(), UE::Geometry::TConstrainedDelaunay2< float >::Add(), UE::Geometry::FDynamicGraph::add_edge(), FGenericPlatformMath::AddAndCheckForOverflow(), FScriptSetHelper::AddElement(), FUInt128::AddInternal(), FScriptMapHelper::AddPair(), AddStructReferencedObjectsOrNot(), UE::Math::TTransform< double >::AddTranslations(), MIR::FEmitter::And(), FRigVMMathLibrary::AngleBetween(), UE::Geometry::FDynamicGraph2< double >::append_new_split_vertex(), UE::Geometry::FDynamicGraph3< double >::append_new_split_vertex(), UE::Geometry::FDynamicGraph::append_new_split_vertex(), UE::Geometry::FDynamicGraphN::append_new_split_vertex(), UE::Geometry::FMarchingCubes::append_triangle(), UE::Geometry::FMeshShapeGenerator::AppendTriangle(), FMaterialCompiler::AppendVector(), FProxyMaterialCompiler::AppendVector(), FSmartObjectOctreeSemantics::AreElementsEqual(), FWedgeInfoOctreeSemantics::AreElementsEqual(), FRK4SpringInterpolatorUtils::AreEqual(), FRK4SpringInterpolatorUtils::AreEqual(), FStructUtils::ArePropertiesTheSame(), UE::Math::TTransform< double >::AreRotationsEqual(), UE::Math::TTransform< double >::AreScale3DsEqual(), FConfigSection::AreSectionsEqualForWriting(), FUpdatedComponentAsyncInput::AreSymmetricRotations(), UCapsuleComponent::AreSymmetricRotations(), USphereComponent::AreSymmetricRotations(), UE::Math::TTransform< double >::AreTranslationsEqual(), UE::Cook::FCookDependency::ARFilterEqual(), UE::Cook::FCookDependency::ARFilterLessThan(), MIR::FEmitter::ASin(), MIR::FEmitter::ASinh(), MIR::FEmitter::ATan(), MIR::FEmitter::ATanh(), UE::Geometry::TImageBuilder< PixelType >::BilinearSample(), MIR::FEmitter::BitShiftLeft(), MIR::FEmitter::BitShiftRight(), TBitArray< typename Allocator::BitArrayAllocator >::BitwiseAND(), UE::MovieScene::FComponentMask::BitwiseAND(), MIR::FEmitter::BitwiseAnd(), UE::MovieScene::FComponentMask::BitwiseNOT(), MIR::FEmitter::BitwiseNot(), TBitArray< typename Allocator::BitArrayAllocator >::BitwiseOR(), UE::MovieScene::FComponentMask::BitwiseOR(), MIR::FEmitter::BitwiseOr(), TBitArray< typename Allocator::BitArrayAllocator >::BitwiseXOR(), UE::MovieScene::FComponentMask::BitwiseXOR(), UE::Geometry::Blend3(), UELocal::BlendColors_Lerp(), UELocal::BlendColors_Multiply(), FNavigationSystem::BoxesAreSame(), UE::Math::TBoxSphereBounds< float, float >::BoxesIntersect(), MIR::FEmitter::Ceil(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::CheckValidity(), FRigVMMathLibrary::ChooseBetterEulerAngleForAxisFilter(), UE::Geometry::VectorUtil::Circumcenter(), FMaterialCompiler::Clamp(), FProxyMaterialCompiler::Clamp(), MIR::FEmitter::Clamp(), TPropertyTypeFundamentals< InTCppType >::ClearIntrusiveOptionalValue(), FMath::ClosestPointOnTetrahedronToPoint(), FMath::ClosestPointOnTriangleToPoint(), UE::Geometry::FDynamicGraph::CollapseEdge(), FMovieSceneAnimTypeID::Combine(), FSubstrateOperator::CombineFlagsForParameterBlending(), Algo::Private::Compare(), UE::Sequencer::FSortingKey::CompareCustomOrderFirst(), CompareItems(), Algo::CompareMap(), Algo::CompareMap(), Algo::CompareMap(), UE::ComparisonUtility::CompareNaturalOrder(), ConvexHull2D::ComparePoints(), UE::Sequencer::FSortingKey::ComparePriorityFirst(), UScriptStruct::CompareScriptStruct(), Algo::CompareSet(), Algo::CompareSet(), TBitArray< typename Allocator::BitArrayAllocator >::CompareSetBits(), FTextComparison::CompareTo(), FTextComparison::CompareToCaseIgnored(), CompareUnsortedArrays(), CompareUnsortedArrays(), CompareValueArraysByExpressionGUID(), UE::ComparisonUtility::CompareWithNumericSuffix(), UE::ComparisonUtility::CompareWithNumericSuffix(), CompareWithOp(), CompileShadingModelBlendFunction(), CompileSubstrateBlendFunction(), FMaterialCompiler::ComponentMask(), FProxyMaterialCompiler::ComponentMask(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), FMath::ComputeBaryCentric2D(), FMath::ComputeBaryCentric3D(), FMath::ComputeBarycentricTri(), FastTriWinding::ComputeCoeffs(), ConvexHull2D::ComputeConvexHull(), ConvexHull2D::ComputeConvexHullLegacy(), ConvexHull2D::ComputeDeterminant(), ConvexHull2D::ComputeDeterminant2D(), TMatrix2x2< float >::Concatenate(), UE::Cook::FCookDependency::ConfigAccessDataEqual(), UE::Cook::FCookDependency::ConfigAccessDataLessThan(), UE::Geometry::CurveUtil::Contains2(), FSubstrateOperator::CopyFlagsForParameterBlending(), UE::Core::Private::PimplPtr::CopyFunc(), MIR::FEmitter::Cos(), MIR::FEmitter::Cosh(), UE::Math::TVector< T >::CosineAngle2D(), FMath::CriticallyDampedSmoothing(), FMaterialCompiler::Cross(), FProxyMaterialCompiler::Cross(), MIR::FEmitter::Cross(), UE::AI::Cross2D(), UE::AI::Cross2D(), UE::Math::TVector2< T >::CrossProduct(), UE::Math::TVector2< FVector::FReal >::CrossProduct(), UE::Math::TVector< T >::CrossProduct(), UE::Math::TVector< NumericType >::CrossProduct(), UE::Geometry::CrossProductMatrix(), FMath::Cube(), FMath::CubicInterp(), TCustomLerp< UE::Math::TQuat< T > >::CubicInterp(), FMath::CubicInterpDerivative(), FMath::CubicInterpSecondDerivative(), UE::Core::Private::Unsafe::Decay(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_STATS_GROUP(), UE::Color::DecodeBT1886(), UE::Color::DecodeREDLog3G10(), TPropertyTypeFundamentals< InTCppType >::DestroyPropertyValue(), TMatrix2x2< float >::Determinant(), TSequenceNumber< NumBits, SequenceType >::Diff(), TSequenceNumber< SequenceNumberBits, uint16 >::Diff(), UE::AnimNext::FGenerationTools::DifferenceBoneIndexArrays(), FMaterialCompiler::Div(), FProxyMaterialCompiler::Div(), MIR::FEmitter::Divide(), UE::Geometry::DoesTriangleIntersectCircle2D(), FSlateRect::DoRectanglesIntersect(), FMaterialCompiler::Dot(), FProxyMaterialCompiler::Dot(), MIR::FEmitter::Dot(), TSHVectorRGB< 3 >::Dot, UE::Math::TVector2< T >::DotProduct(), UE::Math::TVector2< FVector::FReal >::DotProduct(), UE::Math::TVector< T >::DotProduct(), UE::Math::TVector< NumericType >::DotProduct(), FEditorCommonDrawHelper::DrawGridSection(), FToolDataVisualizer::DrawLine(), FToolDataVisualizer::DrawLine(), FToolDataVisualizer::DrawLine(), FToolDataVisualizer::DrawLine(), FEditorCommonDrawHelper::DrawOriginAxisLine(), DrawTriangle(), FMaterialCompiler::DynamicBranch(), FProxyMaterialCompiler::DynamicBranch(), UE::Geometry::FDynamicGraph::edge_has_v(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStats(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStatsFromEdges(), UE::Color::EncodeBT1886(), UE::Color::EncodeREDLog3G10(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), UE::Geometry::VectorUtil::EpsilonEqual(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FPathViews::Equals(), MIR::FEmitter::Equals(), UE::Math::TQuat< T >::Equals(), FTextComparison::EqualTo(), FTextComparison::EqualToCaseIgnored(), UE::Math::TQuat< T >::ErrorAutoNormalize(), UE::Math::TQuat< double >::ErrorAutoNormalize(), Exchange(), Exchange(), Exchange(), Exchange(), MIR::FEmitter::Exponential(), MIR::FEmitter::Exponential2(), FMath::ExponentialSmoothingApprox(), UE::Geometry::ExactPredicates::Facing2(), UE::Geometry::ExactPredicates::Facing3(), UE::Math::TQuat< T >::FastLerp(), UE::Math::TQuat< double >::FastLerp(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::FArrangement2d::find_intersecting_edges(), UE::MovieScene::FSubSequencePath::FindCommonParent(), FScriptSetHelper::FindElementIndexFromHash(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangles_LinearSearch(), FScriptMapHelper::FindMapPairIndexFromHash(), FInterpCurve< T >::FindNearestOnSegment(), FScriptMapHelper::FindOrAdd(), UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindOrTestWithoutCoplanar(), FRigVMMathLibrary::FindQuatBetweenNormals(), FRigVMMathLibrary::FindQuatBetweenVectors(), UE::Geometry::FDynamicMesh3::FindTriangle(), FScriptMapHelper::FindValueFromHash(), MIR::FEmitter::Floor(), FMaterialCompiler::Fmod(), FProxyMaterialCompiler::Fmod(), MIR::FEmitter::Fmod(), FRigVMMathLibrary::FourPointBezier(), MIR::FEmitter::Frac(), FEuclidDivisionGCD::GCD(), UE::Geometry::GenerateArcSegments(), UE::Geometry::GenerateBoxSegments(), UE::Geometry::GenerateCircleSegments(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::get_value_pair(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), FMath::GetBaryCentric2D(), FMath::GetBaryCentric2D(), FOctreeNodeContext::GetChildOffsetVec(), MIR::FEmitter::GetCommonType(), UE::Geometry::FDynamicGraph2< double >::GetEdgeV(), UE::Geometry::FDynamicGraph3< double >::GetEdgeV(), UE::Geometry::FDynamicGraph::GetEdgeV(), UE::Geometry::FSceneGeometrySpatialCache::GetGeometry(), UE::Geometry::ISceneGeometrySpatial::GetGeometry(), GetHemiOrthoBasis(), FTypePromotion::GetHigherType(), FTypePromotion::GetHigherType_Internal(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValue(), TMatrix2x2< float >::GetMatrix(), TMatrix2x2< float >::GetMatrix(), FGenericPlatformMath::GetMinMax(), UE::StateTree::ExecutionContext::GetPriorityRunStatus(), FBoolProperty::GetPropertyValue(), TPropertyTypeFundamentals< InTCppType >::GetPropertyValue(), FBoolProperty::GetPropertyValue_InContainer(), TProperty< InTCppType, FObjectPropertyBase >::GetPropertyValue_InContainer(), TPropertyTypeFundamentals< InTCppType >::GetPropertyValuePtr(), TPropertyTypeFundamentals< InTCppType >::GetPropertyValuePtr(), TProperty< InTCppType, FObjectPropertyBase >::GetPropertyValuePtr_InContainer(), TProperty< InTCppType, FObjectPropertyBase >::GetPropertyValuePtr_InContainer(), TMatrix2x2< float >::GetRotationAngle(), UE::Math::TQuat< T >::GetRotationAxis(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), UE::Math::TTransform< T >::GetScaled(), UE::Math::TTransform< T >::GetScaled(), TMatrix2x2< float >::GetScaleSquared(), UE::Geometry::TetUtil::GetTetFaces(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTrianglesBounds(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetTriElements(), FCompactFullName::GetTypeHash, FFrameNumber::GetTypeHash, FInternetAddrDemo::GetTypeHash, FMovieSceneBlendChannelID::GetTypeHash, FPropertyVisitorInfo::GetTypeHash, FPropertyVisitorPath::GetTypeHash, FSetProfileRequest::GetTypeHash, FTextId::GetTypeHash, FTextKey::GetTypeHash, FWaveInstance::GetTypeHash, GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), UE::MovieScene::FFixedObjectBindingID::GetTypeHash, UE::Geometry::FFFDLattice::GetValuePair(), MIR::FEmitter::GreaterThan(), MIR::FEmitter::GreaterThanOrEquals(), FStructTypeBitSet::FConstBitSetContainer::HasAll(), FStructTypeBitSet::FConstBitSetContainer::HasAny(), FGPUSortManager::HasEither(), HashCombine(), HashCombine(), HashCombineFast(), HashCombineFast(), FixedTagPrivate::HashCombineQuick(), FixedTagPrivate::HashCombineQuick(), FPredictMatch8::HashFn(), FPathViews::HasRedundantTerminatingSeparator(), FArrayProperty::Identical(), FBoolProperty::Identical(), FClassProperty::Identical(), FDelegateProperty::Identical(), FDoubleProperty::Identical(), FEnumProperty::Identical(), FFieldPathProperty::Identical(), FFloatProperty::Identical(), FInterfaceProperty::Identical(), FLazyObjectProperty::Identical(), FMapProperty::Identical(), FMulticastDelegateProperty::Identical(), FObjectProperty::Identical(), FObjectPropertyBase::Identical(), FOptionalProperty::Identical(), FSetProperty::Identical(), FSoftObjectProperty::Identical(), FStructProperty::Identical(), FTextProperty::Identical(), TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty >::Identical(), UScriptStruct::ICppStructOps::Identical(), UScriptStruct::TCppStructOps< CPPSTRUCT >::Identical(), FTextProperty::Identical_Implementation(), FTextProperty::Identical_Implementation(), FProperty::Identical_InContainer(), FMaterialCompiler::If(), FProxyMaterialCompiler::If(), UE::Geometry::ExactPredicates::InCircle2(), UE::Geometry::TMeshUniformSurfaceSampling< FDynamicMesh3, double >::Init(), TPropertyTypeFundamentals< InTCppType >::InitializePropertyValue(), TStaticSpatialIndex< ValueType, Profile, SpatialIndexType, ElementsSorter >::InitSpatialIndex(), UE::Geometry::FArrangement2d::Insert(), UE::Geometry::FArrangement2d::insert_segment(), UE::Geometry::ExactPredicates::InSphere3(), FToolDataVisualizer::InternalDrawTransformedLine(), FMath::InterpCircularIn(), FMath::InterpCircularInOut(), FMath::InterpCircularOut(), FMath::InterpEaseIn(), FMath::InterpEaseInOut(), FMath::InterpEaseOut(), FMath::InterpExpoIn(), FMath::InterpExpoInOut(), FMath::InterpExpoOut(), AnimationCompressionUtils::Interpolate(), AnimationCompressionUtils::Interpolate< FQuat4d >(), AnimationCompressionUtils::Interpolate< FQuat4f >(), AnimationCompressionUtils::Interpolate< FVector3d >(), AnimationCompressionUtils::Interpolate< FVector3f >(), FMath::InterpSinIn(), FMath::InterpSinInOut(), FMath::InterpSinOut(), FMath::InterpStep(), FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, TInterval< float >::Intersect, TSet< class UObject * >::Intersect(), UE::StateTree::FActiveStatePath::Intersect(), TMatrix2x2< float >::Inverse(), FMath::InvExpApprox(), FMaterialCompiler::InvLerp(), FProxyMaterialCompiler::InvLerp(), FGenericPlatformMath::IsFinite(), FGenericPlatformMath::IsFinite(), UE::Geometry::TTriangle2< float >::IsInside(), UE::Geometry::TTriangle2< float >::IsInsideOrOn(), UE::Geometry::TTriangle2< float >::IsInsideOrOn_Oriented(), TPropertyTypeFundamentals< InTCppType >::IsIntrusiveOptionalValueSet(), FGenericPlatformMath::IsNaN(), FGenericPlatformMath::IsNaN(), FMath::IsNearlyEqual(), FMath::IsNearlyEqual(), FMath::IsNearlyEqualByULP(), FMath::IsNearlyEqualByULP(), FGenericPlatformMath::IsNegativeOrNegativeZero(), FGenericPlatformMath::IsNegativeOrNegativeZero(), UE::Math::TQuat< T >::IsNormalized(), FSlateRect::IsRectangleContained(), FTypePromotion::IsValidPromotion(), FAppStyle::Join(), ISlateStyle::Join(), FSubstrateOperator::LAYOUT_FIELD_EDITORONLY(), LegacyCompareEqual(), LegacyCompareEqual(), TMapPrivateFriend::LegacyCompareEqual(), TSetPrivateFriend::LegacyCompareEqual(), LegacyCompareNotEqual(), LegacyCompareNotEqual(), MIR::FEmitter::Length(), FMaterialCompiler::Lerp(), FMath::Lerp(), FMath::Lerp(), FProxyMaterialCompiler::Lerp(), MIR::FEmitter::Lerp(), TBaseBlendedCurve< InAllocatorType, InElementType >::Lerp(), TCustomLerp< UE::Math::TQuat< T > >::Lerp(), TCustomLerp< UE::Math::TRotator< T > >::Lerp(), TMathUtil< RealType >::Lerp(), TMathUtil< float >::Lerp(), UE::Geometry::Lerp(), UE::Geometry::Lerp(), UE::Geometry::Lerp(), UE::Geometry::Lerp(), FAnimationRuntime::LerpBoneTransforms(), FMath::LerpRange(), FMath::LerpStable(), FMath::LerpStable(), FMath::LerpStable(), FRigVMMathLibrary::LerpTransform(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpValid(), FPathViews::Less(), MIR::FEmitter::LessThan(), MIR::FEmitter::LessThanOrEquals(), LexToString(), LexToString(), MIR::FEmitter::Logarithm(), MIR::FEmitter::Logarithm10(), MIR::FEmitter::Logarithm2(), UE::Geometry::LinearColors::MakeColor4f(), UE::Geometry::TInterval1< float >::MakeFromUnordered(), UE::Geometry::VectorUtil::MakePerpVector(), UE::Geometry::VectorUtil::MakePerpVectors(), UE::Geometry::MakeSelectAllConnectedSelection(), FCurveAttributes::MaskCommon(), DefaultKeyComparer< KeyType >::Matches(), DefaultKeyFuncs< FCurveEditorTreeItemID >::Matches(), DefaultKeyFuncs< FCurveEditorTreeItemID >::Matches(), Experimental::TSherwoodHashKeyFuncs< KeyType, ValueType >::Matches(), FAnimBankDescKeyFuncs::Matches(), FApplePlatformSymbolDatabaseKeyFuncs::Matches(), FCachedLandscapeFoliage::FGrassCompKeyFuncs::Matches(), FGenericPlatformSymbolDatabaseKeyFuncs::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FLocKeyMapFuncs< ValueType >::Matches(), FLocKeyMultiMapFuncs< ValueType >::Matches(), FLocKeySetFuncs::Matches(), FMovieSceneEvaluationFieldEntityKeyFuncs::Matches(), FMovieSceneObjectCache::TFastGuidKeyFuncs< ValueType >::Matches(), FNetworkObjectInfo::FNetConnectionKeyFuncs::Matches(), FNetworkObjectKeyFuncs::Matches(), FNetworkObjectList::FSubObjectChannelRefKeyFuncs::Matches(), FSlateFontKeyFuncs< ValueType >::Matches(), KeyInitType< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), KeyInitType< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), MIR::FEmitter::FValueKeyFuncs::Matches(), TLruCache< KeyType, ValueType, KeyComp >::FKeyFuncs::Matches(), TPropertyPathMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), TStringPointerMapKeyFuncs_DEPRECATED< InKeyType, InValueType, bInAllowDuplicateKeys >::Matches(), TStringPointerSetKeyFuncs_DEPRECATED< InKeyType, bInAllowDuplicateKeys >::Matches(), TWeakFieldPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), TWeakObjectPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), TWeakObjectPtrSetKeyFuncs< ElementType, bInAllowDuplicateKeys >::Matches(), UE::StateTree::FActiveStatePath::Matches(), FGenericPlatformMath::Max(), FGenericPlatformMath::Max(), FMaterialCompiler::Max(), FProxyMaterialCompiler::Max(), MIR::FEmitter::Max(), TMathUtil< RealType >::Max(), TMathUtil< float >::Max(), TRDGHandle< FSocket, uint32 >::Max(), UE::Math::TVector2< T >::Max(), UE::Math::TVector2< FVector::FReal >::Max(), UE::Math::TVector< T >::Max(), UE::Math::TVector< NumericType >::Max(), FMath::Max3(), TMathUtil< RealType >::Max3(), TMathUtil< float >::Max3(), UE::Math::TVector< T >::Max3(), UE::Math::TVector< NumericType >::Max3(), FMath::Max3Index(), TMathUtil< RealType >::Max3Index(), TMathUtil< float >::Max3Index(), TRangeBound< FDateTime >::MaxLower(), TRangeBound< FDateTime >::MaxUpper(), Merge(), FGenericPlatformMath::Min(), FGenericPlatformMath::Min(), FMaterialCompiler::Min(), FProxyMaterialCompiler::Min(), MIR::FEmitter::Min(), TMathUtil< RealType >::Min(), TMathUtil< float >::Min(), TRDGHandle< FSocket, uint32 >::Min(), UE::Math::TVector2< T >::Min(), UE::Math::TVector2< FVector::FReal >::Min(), UE::Math::TVector< T >::Min(), UE::Math::TVector< NumericType >::Min(), FMath::Min3(), TMathUtil< RealType >::Min3(), TMathUtil< float >::Min3(), UE::Math::TVector< T >::Min3(), UE::Math::TVector< NumericType >::Min3(), FMath::Min3Index(), TMathUtil< RealType >::Min3Index(), TMathUtil< float >::Min3Index(), TRangeBound< FDateTime >::MinLower(), TMathUtil< RealType >::MinMax(), TMathUtil< float >::MinMax(), TRangeBound< FDateTime >::MinUpper(), Algo::Private::Mismatch(), FMaterialCompiler::Modulo(), FProxyMaterialCompiler::Modulo(), Move(), Move(), MoveByRelocate(), FMaterialCompiler::Mul(), FProxyMaterialCompiler::Mul(), MIR::FEmitter::Multiply(), UE::Math::TTransform< T >::Multiply(), UE::Math::TTransform< double >::Multiply(), FGenericPlatformMath::MultiplyAndCheckForOverflow(), TBigInt< NumBits, bSigned >::MultiplyFast(), UE::Math::TTransform< T >::MultiplyUsingMatrixWithScale(), UE::Math::TTransform< double >::MultiplyUsingMatrixWithScale(), MutableView(), UnFbx::FFbxHelper::NameCompareWeight(), MIR::FEmitter::Negate(), NetworkGuidSetsAreSame(), MIR::FEmitter::Not(), MIR::FEmitter::NotEquals(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnCollapseEdge(), UE::Geometry::FRestrictedSubRegionRemesher::OnEdgeFlip(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnFlipEdge(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnMergeEdges(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnMergeVertices(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnNewTriangle(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnNewVertex(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnPokeTriangle(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnRemoveTriangle(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnRemoveVertex(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnReverseTriOrientation(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnSplitEdge(), UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::OnSplitVertex(), UE::Geometry::FDynamicGraph2< double >::OpeningAngle(), UE::Geometry::VectorUtil::OpeningAngleD(), MIR::FEmitter::Operator(), operator!(), FAssetDataTagMapSharedView::operator!=, FAssetDataTagMapSharedView::operator!=, FAssetDataTagMapSharedView::operator!=, FAssetTagValueRef::operator!=, FAssetTagValueRef::operator!=, FAssetTagValueRef::operator!=, FAssetTagValueRef::operator!=, FCurveEditorToolID::operator!=, FCurveEditorTreeItemID::operator!=, FCurveEditorViewAxisID::operator!=, FCurveModelID::operator!=, FEdGraphSchemaActionDefiningObject::operator!=, FEvaluationTreeEntryHandle::operator!=, FFrameNumber::operator!=, FFrameRate::operator!=, FFrameTime::operator!=, FIoHash::operator!=, FMovieSceneAnimTypeID::operator!=, FMovieSceneBlendingActuatorID::operator!=, FMovieSceneBlendTypeField::operator!=, FMovieSceneChannelHandle::operator!=, FMovieSceneEvaluationTreeNodeHandle::operator!=, FMovieSceneInterrogationKey::operator!=, FMusicalTime::operator!=, FParameterAllocation::operator!=, FPoly::operator!=, FPropertyVisitorInfo::operator!=, FPropertyVisitorPath::operator!=, FSequencerKeyCollectionSignature::operator!=, FSetElementId::operator!=, FShaderCodeVendorExtension::operator!=, FSlateIcon::operator!=, FTextId::operator!=, FTextKey::operator!=, FTimecode::operator!=, FTimecode::operator!=, operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), TMovieSceneEvaluationTreeDataIterator< DataType >::operator!=, UE::FDerivedDataIoPriority::operator!=, UE::GC::FMemberId::operator!=, UE::Math::TQuat< T >::operator!=(), UE::MovieScene::FComponentTypeID::operator!=, UE::MovieScene::FDirectedGraph::FDirectionalEdge::operator!=, UE::MovieScene::FFixedObjectBindingID::operator!=, UE::MovieScene::FHierarchicalBlendTarget::operator!=, UE::MovieScene::FInstanceHandle::operator!=, UE::MovieScene::FMovieSceneEntityID::operator!=, UE::MovieScene::TDynamicSparseBitSet< HashType, BucketStorage >::FIterator::operator!=, UE::MovieScene::TEntityPtr< T >::operator!=, UE::MovieScene::TEntityPtr< T... >::operator!=, UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::operator!=, UE::Sequencer::FDynamicExtensionContainerIterator::operator!=, UE::Sequencer::FOutlinerSizing::operator!=, UE::Sequencer::FParentFirstChildIterator::operator!=, UE::Sequencer::FParentModelIterator::operator!=, UE::Sequencer::FViewModelListIterator::operator!=, UE::Sequencer::FViewModelSubListIterator::operator!=, UE::Sequencer::FViewModelVariantIterator::operator!=, UE::Sequencer::TSelectionSetIteratorState< StorageKeyType, TFilteredSelectionSetIteratorImpl< StorageKeyType, FilterType > >::operator!=, UE::Sequencer::TUniqueFragmentSelectionSetIterator< KeyType >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TWeakViewModelPtr< ExtensionType >::operator!=, FFrameNumber::operator%, FFrameTime::operator%, operator&(), operator&(), TStaticBitArray< NumBits >::operator&, FAbilityInstanceClassPredicate::operator()(), FAbilityInstanceNamePredicate::operator()(), FAISightQuery::FSortPredicate::operator()(), FBehaviorTreeNodeInitializationData::FMemorySort::operator()(), FCompareBoneTransformIndex::operator()(), FCompareFActorPriority::operator()(), FCompareFNewTextureInfoByTextureSize::operator()(), FCompareShaderTypes::operator()(), FCompareSpectralDataByFrequencyHz::operator()(), FCompareVertexFactoryTypes::operator()(), FCookStatsManager::TKeyValuePair< FString, FString >::operator()(), FGameplayTaskInstanceClassPredicate::operator()(), FGameplayTaskInstanceNamePredicate::operator()(), FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FNodeSorter::operator()(), FLocKeySortedMapLess::operator()(), FNameFastLess::operator()(), FNameFastLess::operator()(), FNameLexicalLess::operator()(), FNameLexicalLess::operator()(), FObjectMemoryAnalyzer::FCompareFSortBySize::operator()(), FRedirectionSummary::FCompareRedirect::operator()(), FScriptStructSortOperator::operator()(), FStructTypeSortOperator::operator()(), FText::FSortPredicate::operator()(), FTickStats::operator()(), FTopLevelAssetPathFastLess::operator()(), FTopLevelAssetPathLexicalLess::operator()(), FWedgePositionHelper::FCompareIndexAndZ::operator()(), FWorkspaceItem::FWorkspaceItemSort::operator()(), TCompareShaderTypePermutation< MetaShaderType >::operator()(), TDereferenceWrapper< T, PREDICATE_CLASS >::operator()(), TDereferenceWrapper< T, PREDICATE_CLASS >::operator()(), TDereferenceWrapper< T *, PREDICATE_CLASS >::operator()(), TDereferenceWrapper< TObjectPtr< T >, PREDICATE_CLASS >::operator()(), TGreater< T >::operator()(), TGreater< void >::operator()(), TKeyValuePair< double, uint32 >::operator()(), TLess< T >::operator()(), TLess< void >::operator()(), TPlus< T >::operator()(), TPlus< void >::operator()(), TReversePredicate< PredicateType >::operator()(), TSet< InElementType, KeyFuncs, Allocator >::FElementCompareClass< PREDICATE_CLASS >::operator()(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FKeyComparisonClass< PREDICATE_CLASS >::operator()(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FValueComparisonClass< PREDICATE_CLASS >::operator()(), TSparseArray< InElementType, Allocator >::FElementCompareClass< PREDICATE_CLASS >::operator()(), FFrameNumber::operator*, FFrameRate::operator*, FFrameTime::operator*, FFrameTime::operator*, FStaticLightingVertex::operator*, operator*(), TSHVectorRGB< 3 >::operator*, TSHVectorRGB< 3 >::operator*, TSHVectorRGB< 3 >::operator*, TSHVectorRGB< 3 >::operator*, UE::Geometry::operator*(), UE::Math::TQuat< double >::operator*(), UE::Math::TQuat< T >::operator*=(), UE::Math::TQuat< double >::operator*=(), FFrameNumber::operator+, FFrameTime::operator+, FSlateRect::operator+, FStaticLightingVertex::operator+, TSHVectorRGB< 3 >::operator+, UE::Geometry::operator+(), UE::Math::TQuat< T >::operator+(), UE::Math::TVector2< T >::operator+(), UE::Math::TVector2< FVector::FReal >::operator+(), UE::Math::TQuat< T >::operator+=(), FFrameNumber::operator-, FFrameNumber::operator-, FFrameTime::operator-, FFrameTime::operator-, FSlateRect::operator-, FStaticLightingVertex::operator-, TSHVectorRGB< 3 >::operator-, UE::Geometry::operator-(), UE::Math::TQuat< T >::operator-(), UE::Math::TVector2< T >::operator-(), UE::Math::TVector2< FVector::FReal >::operator-(), UE::Math::TQuat< T >::operator-=(), FFrameNumber::operator/, FFrameRate::operator/, FFrameTime::operator/, FStaticLightingVertex::operator/, TSHVectorRGB< 3 >::operator/, UE::Math::TQuat< double >::operator/(), UE::Math::TQuat< double >::operator/=(), FCurveEditorViewAxisID::operator<, FCurveModelID::operator<, FFrameNumber::operator<, FFrameTime::operator<, FIoHash::operator<, FKeyHandle::operator<, FMovieSceneBlenderSystemID::operator<, FMusicalTime::operator<, UE::FDerivedDataIoPriority::operator<, UE::MovieScene::FComponentTypeID::operator<, UE::MovieScene::FDirectedGraph::FDirectionalEdge::operator<, UE::MovieScene::FEntityHandle::operator<, UE::MovieScene::FHierarchicalBlendTarget::operator<, UE::MovieScene::FInstanceHandle::operator<, UE::MovieScene::FMovieSceneEntityID::operator<, UE::MovieScene::FPreAnimatedStorageID::operator<, UE::SequenceNavigator::FNavigationToolViewModelTypeID::operator<, UE::Sequencer::FOutlinerColumnPosition::operator<, UE::Sequencer::FViewModelTypeID::operator<, FImplementedInterface::operator<<, operator<<(), operator<<(), SkeletalMeshImportData::FVertexAttribute::operator<<, TTransArray< T >::operator<<, FFrameNumber::operator<=, FFrameTime::operator<=, FMusicalTime::operator<=, TPimplPtr< T, EPimplPtrMode::DeepCopy >::operator=(), TPimplPtr< T, EPimplPtrMode::DeepCopy >::operator=(), FAnimatedPropertyKey::operator==, FAssetDataTagMapSharedView::operator==, FAssetDataTagMapSharedView::operator==, FAssetDataTagMapSharedView::operator==, FAssetIdentifier::operator==, FAssetRegistryExportPath::operator==, FAssetTagValueRef::operator==, FAssetTagValueRef::operator==, FAssetTagValueRef::operator==, FAssetTagValueRef::operator==, FCurveEditorToolID::operator==, FCurveEditorTreeItemID::operator==, FCurveEditorViewAxisID::operator==, FCurveModelID::operator==, FDisplayNameEntryId::operator==, FDisplayNameEntryId::operator==, FDisplayNameEntryId::operator==, FEdGraphSchemaActionDefiningObject::operator==, FEvaluationTreeEntryHandle::operator==, FFrameNumber::operator==, FFrameRate::operator==, FFrameTime::operator==, FIoHash::operator==, FixedTagPrivate::FMapHandle::operator==, FixedTagPrivate::operator==(), FLazyName::operator==, FMallocCallstackHandler::FCallStackMapKey::operator==, FMaxRPCDoSEscalation::operator==(), FMovieSceneAnimTypeID::operator==, FMovieSceneBlendChannelID::operator==, FMovieSceneBlenderSystemID::operator==, FMovieSceneBlendingActuatorID::operator==, FMovieSceneBlendingKey::operator==, FMovieSceneBlendTypeField::operator==, FMovieSceneChannelHandle::operator==, FMovieSceneEvaluationTreeNode::operator==, FMovieSceneEvaluationTreeNodeHandle::operator==, FMovieSceneInterrogationKey::operator==, FMovieSceneSharedDataId::operator==, FMusicalTime::operator==, FNetConnAnalyticsVars::operator==(), FOperatorFunctionID::operator==, FParameterAllocation::operator==, FPinConnectionResponse::operator==, FPoly::operator==, FPropertyPermissionList::operator==, FPropertyVisitorInfo::operator==, FPropertyVisitorPath::operator==, FRepSharedPropertyKey::operator==, FRigVMExplorerElementKey::operator==, FRigVMPinConnectionResponse::operator==, FRPCAnalytics::operator==(), FRPCDoSAnalyticsVars::operator==(), FSceneViewOwner::operator==, FSequencerKeyCollectionSignature::operator==, FSetElementId::operator==, FSetProfileRequest::operator==, FShaderCodeLibraryPipeline::operator==, FShaderCodeVendorExtension::operator==, FSharedPersistentDataKey::operator==, FSimpleStreamableAssetManager::FAssetRecord::operator==, FSlateIcon::operator==, FStableShaderKeyAndValue::operator==, FTextId::operator==, FTextKey::operator==, FTimecode::operator==, FTimecode::operator==, FVertexFactory::FVertexStream::operator==, operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), TEvaluationTreeEntryContainer< ElementType >::FEntry::operator==, TEvaluationTreeEntryContainer< ElementType >::operator==, TMatrix2x2< float >::operator==(), TMovieSceneEvaluationTree< DataType >::operator==, TMovieSceneEvaluationTreeDataIterator< DataType >::operator==, TStaticArray< int32, MAX_PHYSICS_FIELD_TARGETS, 16 >::operator==, UE::FDerivedDataIoPriority::operator==, UE::FIoBlockKey::operator==, UE::GC::FMemberId::operator==, UE::Math::TQuat< T >::operator==(), UE::MovieScene::FComplexInclusivityFilter::operator==, UE::MovieScene::FComponentMask::operator==, UE::MovieScene::FComponentMaterialKey::operator==, UE::MovieScene::FComponentTypeID::operator==, UE::MovieScene::FDirectedGraph::FDirectionalEdge::operator==, UE::MovieScene::FEntityGroupID::operator==, UE::MovieScene::FEntityGroupingPolicyKey::operator==, UE::MovieScene::FEntityHandle::operator==, UE::MovieScene::FFixedObjectBindingID::operator==, UE::MovieScene::FHierarchicalBlendTarget::operator==, UE::MovieScene::FInstanceHandle::operator==, UE::MovieScene::FMaterialParameterKey::operator==, UE::MovieScene::FMovieSceneEntityID::operator==, UE::MovieScene::FObjectComponent::operator==, UE::MovieScene::FPreAnimatedEvalHookKeyType::operator==, UE::MovieScene::FPreAnimatedEvaluationKeyType::operator==, UE::MovieScene::FPreAnimatedStateCachedValueHandle::operator==, UE::MovieScene::FPreAnimatedStateEntry::operator==, UE::MovieScene::FPreAnimatedStorageGroupHandle::operator==, UE::MovieScene::FPreAnimatedStorageID::operator==, UE::MovieScene::FPreAnimatedStorageIndex::operator==, UE::MovieScene::TDynamicSparseBitSet< HashType, BucketStorage >::FIterator::operator==, UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::operator==, UE::MovieScene::TOverlappingEntityInput< InputKeyTypes... >::operator==, UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FKeyType::operator==, UE::SequenceNavigator::FNavigationToolViewModelTypeID::operator==, UE::Sequencer::FOutlinerSizing::operator==, UE::Sequencer::FSortingKey::operator==, UE::Sequencer::FViewModelTypeID::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TWeakViewModelPtr< ExtensionType >::operator==, FFrameNumber::operator>, FFrameTime::operator>, FKeyHandle::operator>, FMusicalTime::operator>, UE::Sequencer::FObjectSchemaRelevancy::operator>, FFrameNumber::operator>=, FFrameTime::operator>=, FMusicalTime::operator>=, TStaticBitArray< NumBits >::operator^, operator|(), operator|(), TStaticBitArray< NumBits >::operator|, UE::MovieScene::FComponentTypeID::operator|, UE::MovieScene::FComponentTypeID::operator|, FKeyPropertyResult::operator|=(), TStaticBitArray< NumBits >::operator~, MIR::FEmitter::Or(), UE::Geometry::Orient(), UE::Geometry::ExactPredicates::Orient2(), UE::Geometry::ExactPredicates::Orient2Origin(), UE::Geometry::ExactPredicates::Orient3(), FTabInfo::PayloadMatches(), FGeomTools::PointInTriangle(), UE::Geometry::PointInTriangle2d(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::PointInTriangle2d(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointInTriangle2d(), UE::Math::TVector< T >::PointPlaneProject(), UE::Math::TVector< NumericType >::PointPlaneProject(), FGenericPlatformMath::Pow(), FGenericPlatformMath::Pow(), UE::Math::TVector< T >::ProjectOnTo(), UE::Math::TVector< NumericType >::ProjectOnTo(), FMath::RandHelper(), FRandomStream::RandHelper(), FMath::RandHelper64(), FBlueprintCompileReinstancer::ReinstancerOrderingFunction(), UE::Geometry::FDynamicGraph::RemoveEdge(), FScriptSetHelper::RemoveElement(), FScriptMapHelper::RemovePair(), UE::Geometry::FDynamicGraph::replace_edge_vertex(), CEqualityComparableWith::Requires(), FNetworkPredictionDriverBase< ModelDef >::CFinalizeFrameMemberFuncable::Requires(), FNetworkPredictionDriverBase< ModelDef >::CFinalizeSmoothingFrameMemberFuncable::Requires(), FNetworkPredictionDriverBase< ModelDef >::CRestoreFrameMemberFuncable::Requires(), FWatchablePropertySet::TPropertyWatcher< PropType >::CInequalityComparable::Requires(), MIR::FEmitter::Round(), MIR::FEmitter::Saturate(), FMath::SegmentTriangleIntersection(), MIR::FEmitter::Select(), TArrayPrivateFriend::Serialize(), FWeakObjectProperty::SerializeItem(), UE::Geometry::TInterval1< float >::Set(), FExpressionInput::SetMask(), FExpressionOutput::SetMask(), FBoolProperty::SetPropertyValue(), TPropertyTypeFundamentals< InTCppType >::SetPropertyValue(), FBoolProperty::SetPropertyValue_InContainer(), TProperty< InTCppType, FObjectPropertyBase >::SetPropertyValue_InContainer(), UE::Geometry::TIntrTriangle3Triangle3< float >::SetResult(), UE::Geometry::FMeshShapeGenerator::SetTriangle(), UE::Geometry::FMeshShapeGenerator::SetTriangle(), UE::Geometry::FMeshShapeGenerator::SetTriangleNormals(), UE::Geometry::FMeshShapeGenerator::SetTriangleNormals(), UE::Geometry::FMeshShapeGenerator::SetTriangleUVs(), UE::Geometry::FMeshShapeGenerator::SetTriangleUVs(), UE::Geometry::FMeshShapeGenerator::SetTriangleWithMatchedUVNormal(), FGenericPlatformMath::Sign(), UE::Geometry::TTriangle2< float >::SignedArea(), MIR::FEmitter::Sin(), MIR::FEmitter::Sinh(), TMathUtil< RealType >::SmoothMax(), TMathUtil< float >::SmoothMax(), TMathUtil< RealType >::SmoothMin(), TMathUtil< float >::SmoothMin(), FMaterialCompiler::SmoothStep(), FMath::SmoothStep(), FProxyMaterialCompiler::SmoothStep(), MIR::FEmitter::Smoothstep(), FStaticSpatialIndex::TNodeSorterHilbert< FStaticSpatialIndex::FSpatialIndexProfile3D, 65536 >::Sort(), FStaticSpatialIndex::TNodeSorterMinX< Profile >::Sort(), FStaticSpatialIndex::TNodeSorterMorton< Profile, BucketSize >::Sort(), FStaticSpatialIndex::TNodeSorterNoSort< Profile >::Sort(), FThreadPoolPriorityQueue::Sort(), UE::MovieScene::FEvaluationTreePopulationRules::FSortedSection::SortByOverlapPriorityAndRow(), FMovieSceneAdditiveCameraTrackBlender::SortByStartTime(), MovieSceneHelpers::SortLowerBounds(), MovieSceneHelpers::SortOverlappingSections(), MovieSceneHelpers::SortUpperBounds(), UE::Math::TBoxSphereBounds< float, float >::SpheresIntersect(), UE::Geometry::FDynamicGraph::SplitEdge(), UE::Geometry::FDynamicGraph::SplitEdgeWithExistingVertex(), FMath::SpringDamper(), MIR::FEmitter::Sqrt(), FMath::Square(), StateStreamEquals(), FObjectPropertyBase::StaticIdentical(), FMaterialCompiler::Sub(), FProxyMaterialCompiler::Sub(), TBVTree< InElementType, InAllocator >::Subdivide(), FMaterialCompiler::SubstrateAdd(), FProxyMaterialCompiler::SubstrateAdd(), FMaterialCompiler::SubstrateAddParameterBlending(), FProxyMaterialCompiler::SubstrateAddParameterBlending(), SubstrateMergeSubSurfaceType(), FMaterialCompiler::SubstrateSelectParameterBlending(), FProxyMaterialCompiler::SubstrateSelectParameterBlending(), FMaterialCompiler::SubstrateWeight(), FProxyMaterialCompiler::SubstrateWeight(), FMaterialCompiler::SubstrateWeightParameterBlending(), FProxyMaterialCompiler::SubstrateWeightParameterBlending(), MIR::FEmitter::Subtract(), FGenericPlatformMath::SubtractAndCheckForOverflow(), UE::Math::TTransform< double >::SubtractTranslations(), Swap(), Swap(), Swap(), Swap(), TScriptArray< FHeapAllocator >::SwapMemory(), FScriptArrayHelper::SwapValues(), MIR::FEmitter::Tan(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), FMath::TIsNearlyEqualByULP(), TTransform2< float >::To3DMatrix(), UE::Geometry::TMeshQueries< TriangleMeshType >::TotalEdgeLength(), Algo::TransformAccumulate(), Algo::TransformAccumulate(), FMaterialCompiler::TransformFromPeriodicWorldPosition(), FMaterialCompiler::TransformPosition(), FMaterialCompiler::TransformPosition(), FProxyMaterialCompiler::TransformPosition(), FMaterialCompiler::TransformToPeriodicWorldPosition(), FMaterialCompiler::TransformVector(), FMaterialCompiler::TransformVector(), FProxyMaterialCompiler::TransformVector(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TriangleIntersectionFilter(), UE::AI::TriArea2D(), UE::AI::TriArea2D(), UE::Geometry::VectorUtil::TriSolidAngle(), MIR::FEmitter::Truncate(), MIR::FEmitter::TryGetCommonType(), UCLASS(), FGenericPlatformMath::UE_DEPRECATED(), FGenericPlatformMath::UE_DEPRECATED(), FGenericPlatformMath::UE_DEPRECATED(), FGenericPlatformMath::UE_DEPRECATED(), TStaticBitArray< NumBits >::UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintSetLibrary::UFUNCTION(), UKismetInputLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UE::Geometry::VectorUtil::UniformSampleTrianglePoint(), UE::Geometry::VectorUtil::UniformSampleTrianglePoint(), UE::Geometry::FSizedDisjointSet::Union(), UE::Math::TBoxSphereBounds< float, float >::Union, FMath::UnwindDegrees(), FMath::UnwindRadians(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), FGenericPlatformMemory::Valswap(), VectorDoubleToInt(), VectorFloatToInt(), VectorFloatToInt(), VectorIntAbs(), VectorIntAdd(), VectorIntAnd(), VectorIntAndNot(), VectorIntCompareEQ(), VectorIntCompareGE(), VectorIntCompareGT(), VectorIntCompareLE(), VectorIntCompareLT(), VectorIntCompareNEQ(), VectorIntMax(), VectorIntMin(), VectorIntMultiply(), VectorIntNegate(), VectorIntNot(), VectorIntOr(), VectorIntStore(), VectorIntStoreAligned(), VectorIntSubtract(), VectorIntToFloat(), VectorIntXor(), VectorMatrixMultiply(), VectorMatrixMultiply(), FPixelStreamingVideoInputBackBufferComposited::VectorMax(), UE::EditorPixelStreaming2::FVideoProducerBackBufferComposited::VectorMax(), FPixelStreamingVideoInputBackBufferComposited::VectorMin(), UE::EditorPixelStreaming2::FVideoProducerBackBufferComposited::VectorMin(), VectorQuaternionMultiply(), VectorQuaternionMultiply(), VectorRoundToIntHalfToEven(), FGeomTools::VectorsOnSameSide(), UE::Geometry::VectorUtil::VectorTanHalfAngle(), UE::Geometry::VectorUtil::VectorTanHalfAngle(), and UE::Geometry::CurveUtil::WindingIntegral2().
B
TArray< T * > & B
Initial value:
{
    return A ? A : B
Definition at line 28 of file UnrealTemplate.h.
Referenced by UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >::FBCSplineFilter(), FUInt128::FUInt128(), FUInt128::FUInt128(), UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Math::TPlane< T >::TPlane(), UE::Math::TPlane< double >::TPlane(), FWatchablePropertySet::TPropertyWatcher< PropType >::TPropertyWatcher(), TRange< float >::TRange(), UE::Math::TVector< T >::TVector(), UE::Math::TVector4< U >::TVector4(), UE::Math::TVector4< U >::TVector4(), FMaterialCompiler::Add(), FProxyMaterialCompiler::Add(), MIR::FEmitter::Add(), UE::Geometry::TConstrainedDelaunay2< float >::Add(), UE::Geometry::FDynamicGraph::add_edge(), FGenericPlatformMath::AddAndCheckForOverflow(), FScriptSetHelper::AddElement(), FUInt128::AddInternal(), FScriptMapHelper::AddPair(), UE::Math::TTransform< double >::AddTranslations(), MIR::FEmitter::And(), FRigVMMathLibrary::AngleBetween(), UE::Geometry::FDynamicGraph2< double >::append_new_split_vertex(), UE::Geometry::FDynamicGraph3< double >::append_new_split_vertex(), UE::Geometry::FDynamicGraph::append_new_split_vertex(), UE::Geometry::FDynamicGraphN::append_new_split_vertex(), UE::Geometry::FMarchingCubes::append_triangle(), UE::Geometry::FMeshShapeGenerator::AppendTriangle(), FMaterialCompiler::AppendVector(), FProxyMaterialCompiler::AppendVector(), FSmartObjectOctreeSemantics::AreElementsEqual(), FWedgeInfoOctreeSemantics::AreElementsEqual(), FRK4SpringInterpolatorUtils::AreEqual(), FRK4SpringInterpolatorUtils::AreEqual(), FStructUtils::ArePropertiesTheSame(), UE::Math::TTransform< double >::AreRotationsEqual(), UE::Math::TTransform< double >::AreScale3DsEqual(), FConfigSection::AreSectionsEqualForWriting(), FUpdatedComponentAsyncInput::AreSymmetricRotations(), UCapsuleComponent::AreSymmetricRotations(), USphereComponent::AreSymmetricRotations(), UE::Math::TTransform< double >::AreTranslationsEqual(), UE::Cook::FCookDependency::ARFilterEqual(), UE::Cook::FCookDependency::ARFilterLessThan(), MIR::FEmitter::BitShiftLeft(), MIR::FEmitter::BitShiftRight(), TBitArray< typename Allocator::BitArrayAllocator >::BitwiseAND(), UE::MovieScene::FComponentMask::BitwiseAND(), MIR::FEmitter::BitwiseAnd(), TBitArray< typename Allocator::BitArrayAllocator >::BitwiseOR(), UE::MovieScene::FComponentMask::BitwiseOR(), MIR::FEmitter::BitwiseOr(), TBitArray< typename Allocator::BitArrayAllocator >::BitwiseXOR(), UE::MovieScene::FComponentMask::BitwiseXOR(), UE::Geometry::Blend3(), UELocal::BlendColors_Lerp(), UELocal::BlendColors_Multiply(), UE::Geometry::TDistanceFieldToSkeletalField< InputBoundedImplicitType, RealType >::Bounds(), FNavigationSystem::BoxesAreSame(), UE::Math::TBoxSphereBounds< float, float >::BoxesIntersect(), CalculateGridZParams(), FRigVMMathLibrary::ChooseBetterEulerAngleForAxisFilter(), UE::Geometry::VectorUtil::Circumcenter(), FMaterialCompiler::Clamp(), FProxyMaterialCompiler::Clamp(), MIR::FEmitter::Clamp(), FMath::ClosestPointOnTetrahedronToPoint(), FMath::ClosestPointOnTriangleToPoint(), UE::Geometry::FDynamicGraph::CollapseEdge(), FMovieSceneAnimTypeID::Combine(), FSubstrateOperator::CombineFlagsForParameterBlending(), Algo::Private::Compare(), UE::Sequencer::FSortingKey::CompareCustomOrderFirst(), CompareItems(), Algo::CompareMap(), Algo::CompareMap(), Algo::CompareMap(), UE::ComparisonUtility::CompareNaturalOrder(), ConvexHull2D::ComparePoints(), UE::Sequencer::FSortingKey::ComparePriorityFirst(), UScriptStruct::CompareScriptStruct(), Algo::CompareSet(), Algo::CompareSet(), TBitArray< typename Allocator::BitArrayAllocator >::CompareSetBits(), FTextComparison::CompareTo(), FTextComparison::CompareToCaseIgnored(), CompareUnsortedArrays(), CompareUnsortedArrays(), CompareValueArraysByExpressionGUID(), UE::ComparisonUtility::CompareWithNumericSuffix(), UE::ComparisonUtility::CompareWithNumericSuffix(), CompareWithOp(), CompileShadingModelBlendFunction(), CompileSubstrateBlendFunction(), FMaterialCompiler::ComponentMask(), FProxyMaterialCompiler::ComponentMask(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), FMath::ComputeBaryCentric2D(), FMath::ComputeBaryCentric3D(), FMath::ComputeBarycentricTri(), FastTriWinding::ComputeCoeffs(), ConvexHull2D::ComputeConvexHull(), ConvexHull2D::ComputeConvexHullLegacy(), ConvexHull2D::ComputeDeterminant(), ConvexHull2D::ComputeDeterminant2D(), TMatrix2x2< float >::Concatenate(), UE::Cook::FCookDependency::ConfigAccessDataEqual(), UE::Cook::FCookDependency::ConfigAccessDataLessThan(), UE::Geometry::CurveUtil::Contains2(), UE::Math::TVector< T >::CosineAngle2D(), UE::Math::TVector< NumericType >::CosineAngle2D(), FMath::CriticallyDampedSmoothing(), FMaterialCompiler::Cross(), FProxyMaterialCompiler::Cross(), MIR::FEmitter::Cross(), UE::AI::Cross2D(), UE::AI::Cross2D(), UE::Math::TVector2< T >::CrossProduct(), UE::Math::TVector2< FVector::FReal >::CrossProduct(), UE::Math::TVector< T >::CrossProduct(), UE::Math::TVector< NumericType >::CrossProduct(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_STATS_GROUP(), UE::Color::DecodeBT1886(), UE::Color::DecodeREDLog3G10(), TMatrix2x2< float >::Determinant(), TSequenceNumber< NumBits, SequenceType >::Diff(), TSequenceNumber< SequenceNumberBits, uint16 >::Diff(), UE::AnimNext::FGenerationTools::DifferenceBoneIndexArrays(), FMaterialCompiler::Div(), FProxyMaterialCompiler::Div(), MIR::FEmitter::Divide(), FShortRect::DoesIntersect(), FShortRect::DoesIntersect(), UE::Geometry::DoesTriangleIntersectCircle2D(), FSlateRect::DoRectanglesIntersect(), FMaterialCompiler::Dot(), FProxyMaterialCompiler::Dot(), MIR::FEmitter::Dot(), UE::Math::TVector2< T >::DotProduct(), UE::Math::TVector2< FVector::FReal >::DotProduct(), UE::Math::TVector< T >::DotProduct(), UE::Math::TVector< NumericType >::DotProduct(), FEditorCommonDrawHelper::DrawGridSection(), FToolDataVisualizer::DrawLine(), FToolDataVisualizer::DrawLine(), FToolDataVisualizer::DrawLine(), FToolDataVisualizer::DrawLine(), FEditorCommonDrawHelper::DrawOriginAxisLine(), DrawTriangle(), FMaterialCompiler::DynamicBranch(), FProxyMaterialCompiler::DynamicBranch(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStats(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStatsFromEdges(), UE::Color::EncodeBT1886(), UE::Color::EncodeREDLog3G10(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), UE::Geometry::VectorUtil::EpsilonEqual(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FName::Equals(), FPathViews::Equals(), MIR::FEmitter::Equals(), UE::Math::TQuat< T >::Equals(), FTextComparison::EqualTo(), FTextComparison::EqualToCaseIgnored(), UE::Math::TQuat< T >::ErrorAutoNormalize(), UE::Math::TQuat< double >::ErrorAutoNormalize(), Exchange(), Exchange(), Exchange(), Exchange(), UE::Geometry::ExactPredicates::Facing2(), UE::Geometry::ExactPredicates::Facing3(), UE::Math::TQuat< T >::FastLerp(), UE::Math::TQuat< double >::FastLerp(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::FArrangement2d::find_intersecting_edges(), UE::Geometry::FArrangement2d::find_nearest_boundary_vertex(), UE::Geometry::FArrangement2d::find_nearest_vertex(), UE::MovieScene::FSubSequencePath::FindCommonParent(), UE::Geometry::FDynamicGraph::FindEdge(), FScriptSetHelper::FindElementIndexFromHash(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangles_LinearSearch(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), FScriptMapHelper::FindMapPairIndexFromHash(), FInterpCurve< T >::FindNearestOnSegment(), FScriptMapHelper::FindOrAdd(), UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindOrTestWithoutCoplanar(), FRigVMMathLibrary::FindQuatBetweenNormals(), FRigVMMathLibrary::FindQuatBetweenVectors(), UE::Geometry::FDynamicMesh3::FindTriangle(), FScriptMapHelper::FindValueFromHash(), FMaterialCompiler::Fmod(), FProxyMaterialCompiler::Fmod(), MIR::FEmitter::Fmod(), FRigVMMathLibrary::FourPointBezier(), FEuclidDivisionGCD::GCD(), UE::Geometry::GenerateArcSegments(), UE::Geometry::GenerateBoxSegments(), UE::Geometry::GenerateCircleSegments(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::get_value_pair(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), FMath::GetBaryCentric2D(), FMath::GetBaryCentric2D(), MIR::FEmitter::GetCommonType(), UE::Geometry::FDynamicGraph2< double >::GetEdgeV(), UE::Geometry::FDynamicGraph3< double >::GetEdgeV(), UE::Geometry::FDynamicGraph::GetEdgeV(), UE::Geometry::FSceneGeometrySpatialCache::GetGeometry(), UE::Geometry::ISceneGeometrySpatial::GetGeometry(), GetHemiOrthoBasis(), FTypePromotion::GetHigherType(), FTypePromotion::GetHigherType_Internal(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValue(), TMatrix2x2< float >::GetMatrix(), TMatrix2x2< float >::GetMatrix(), FGenericPlatformMath::GetMinMax(), FBoolProperty::GetOptionalPropertyValue(), TPropertyTypeFundamentals< InTCppType >::GetOptionalPropertyValue(), FBoolProperty::GetOptionalPropertyValue_InContainer(), TProperty< InTCppType, FObjectPropertyBase >::GetOptionalPropertyValue_InContainer(), UE::StateTree::ExecutionContext::GetPriorityRunStatus(), TMatrix2x2< float >::GetRotationAngle(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), TMatrix2x2< float >::GetScaleSquared(), UE::Geometry::TetUtil::GetTetFaces(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTrianglesBounds(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetTriElements(), UE::Geometry::FFFDLattice::GetValuePair(), MIR::FEmitter::GreaterThan(), MIR::FEmitter::GreaterThanOrEquals(), FStructTypeBitSet::FConstBitSetContainer::HasAll(), FStructTypeBitSet::FConstBitSetContainer::HasAny(), FGPUSortManager::HasEither(), HashCombine(), HashCombineFast(), FixedTagPrivate::HashCombineQuick(), FixedTagPrivate::HashCombineQuick(), FPredictMatch8::HashFn(), FArrayProperty::Identical(), FBoolProperty::Identical(), FClassProperty::Identical(), FDelegateProperty::Identical(), FDoubleProperty::Identical(), FEnumProperty::Identical(), FFieldPathProperty::Identical(), FFloatProperty::Identical(), FInterfaceProperty::Identical(), FLazyObjectProperty::Identical(), FMapProperty::Identical(), FMulticastDelegateProperty::Identical(), FObjectProperty::Identical(), FObjectPropertyBase::Identical(), FOptionalProperty::Identical(), FSetProperty::Identical(), FSoftObjectProperty::Identical(), FStructProperty::Identical(), FTextProperty::Identical(), TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty >::Identical(), UScriptStruct::ICppStructOps::Identical(), UScriptStruct::TCppStructOps< CPPSTRUCT >::Identical(), FTextProperty::Identical_Implementation(), FTextProperty::Identical_Implementation(), FProperty::Identical_InContainer(), FMaterialCompiler::If(), FProxyMaterialCompiler::If(), UE::Geometry::ExactPredicates::InCircle2(), UE::Geometry::TMeshUniformSurfaceSampling< FDynamicMesh3, double >::Init(), TStaticSpatialIndex< ValueType, Profile, SpatialIndexType, ElementsSorter >::InitSpatialIndex(), UE::Geometry::FArrangement2d::Insert(), UE::Geometry::FArrangement2d::insert_segment(), UE::Geometry::ExactPredicates::InSphere3(), FToolDataVisualizer::InternalDrawTransformedLine(), FMath::InterpCircularIn(), FMath::InterpCircularInOut(), FMath::InterpCircularOut(), FMath::InterpEaseIn(), FMath::InterpEaseInOut(), FMath::InterpEaseOut(), FMath::InterpExpoIn(), FMath::InterpExpoInOut(), FMath::InterpExpoOut(), AnimationCompressionUtils::Interpolate(), AnimationCompressionUtils::Interpolate< FQuat4d >(), AnimationCompressionUtils::Interpolate< FQuat4f >(), AnimationCompressionUtils::Interpolate< FVector3d >(), AnimationCompressionUtils::Interpolate< FVector3f >(), FMath::InterpSinIn(), FMath::InterpSinInOut(), FMath::InterpSinOut(), FMath::InterpStep(), FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, TInterval< float >::Intersect, TSet< class UObject * >::Intersect(), UE::StateTree::FActiveStatePath::Intersect(), TMatrix2x2< float >::Inverse(), FMath::InvExpApprox(), UE::Geometry::TTriangle2< float >::IsInside(), UE::Geometry::TTriangle2< float >::IsInsideOrOn(), UE::Geometry::TTriangle2< float >::IsInsideOrOn_Oriented(), FMath::IsNearlyEqual(), FMath::IsNearlyEqual(), FMath::IsNearlyEqualByULP(), FMath::IsNearlyEqualByULP(), FSlateRect::IsRectangleContained(), FTypePromotion::IsValidPromotion(), FAppStyle::Join(), ISlateStyle::Join(), FSubstrateOperator::LAYOUT_FIELD_EDITORONLY(), LegacyCompareEqual(), LegacyCompareEqual(), TMapPrivateFriend::LegacyCompareEqual(), TSetPrivateFriend::LegacyCompareEqual(), LegacyCompareNotEqual(), LegacyCompareNotEqual(), FMath::Lerp(), FMath::Lerp(), MIR::FEmitter::Lerp(), TBaseBlendedCurve< InAllocatorType, InElementType >::Lerp(), TCustomLerp< UE::Math::TQuat< T > >::Lerp(), TCustomLerp< UE::Math::TRotator< T > >::Lerp(), TMathUtil< RealType >::Lerp(), TMathUtil< float >::Lerp(), UE::Geometry::Lerp(), UE::Geometry::Lerp(), UE::Geometry::Lerp(), UE::Geometry::Lerp(), FAnimationRuntime::LerpBoneTransforms(), FMath::LerpRange(), FMath::LerpStable(), FMath::LerpStable(), FMath::LerpStable(), FRigVMMathLibrary::LerpTransform(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpValid(), FPathViews::Less(), MIR::FEmitter::LessThan(), MIR::FEmitter::LessThanOrEquals(), UE::Geometry::LinearColors::MakeColor3f(), UE::Geometry::LinearColors::MakeColor4f(), UE::Geometry::TInterval1< float >::MakeFromUnordered(), UE::Geometry::VectorUtil::MakePerpVector(), UE::Geometry::VectorUtil::MakePerpVectors(), UE::Geometry::MakeSelectAllConnectedSelection(), FCurveAttributes::MaskCommon(), DefaultKeyComparer< KeyType >::Matches(), DefaultKeyFuncs< FCurveEditorTreeItemID >::Matches(), DefaultKeyFuncs< FCurveEditorTreeItemID >::Matches(), Experimental::TSherwoodHashKeyFuncs< KeyType, ValueType >::Matches(), FAnimBankDescKeyFuncs::Matches(), FApplePlatformSymbolDatabaseKeyFuncs::Matches(), FCachedLandscapeFoliage::FGrassCompKeyFuncs::Matches(), FGenericPlatformSymbolDatabaseKeyFuncs::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches(), FLocKeyMapFuncs< ValueType >::Matches(), FLocKeyMultiMapFuncs< ValueType >::Matches(), FLocKeySetFuncs::Matches(), FMovieSceneEvaluationFieldEntityKeyFuncs::Matches(), FMovieSceneObjectCache::TFastGuidKeyFuncs< ValueType >::Matches(), FNetworkObjectInfo::FNetConnectionKeyFuncs::Matches(), FNetworkObjectKeyFuncs::Matches(), FNetworkObjectList::FSubObjectChannelRefKeyFuncs::Matches(), FSlateFontKeyFuncs< ValueType >::Matches(), KeyInitType< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), KeyInitType< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), MIR::FEmitter::FValueKeyFuncs::Matches(), TLruCache< KeyType, ValueType, KeyComp >::FKeyFuncs::Matches(), TPropertyPathMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), TStringPointerMapKeyFuncs_DEPRECATED< InKeyType, InValueType, bInAllowDuplicateKeys >::Matches(), TStringPointerSetKeyFuncs_DEPRECATED< InKeyType, bInAllowDuplicateKeys >::Matches(), TWeakFieldPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), TWeakObjectPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::Matches(), TWeakObjectPtrSetKeyFuncs< ElementType, bInAllowDuplicateKeys >::Matches(), UE::StateTree::FActiveStatePath::Matches(), FGenericPlatformMath::Max(), FMaterialCompiler::Max(), FProxyMaterialCompiler::Max(), MIR::FEmitter::Max(), TMathUtil< RealType >::Max(), TMathUtil< float >::Max(), TRDGHandle< FSocket, uint32 >::Max(), UE::Math::TVector2< T >::Max(), UE::Math::TVector2< FVector::FReal >::Max(), UE::Math::TVector< T >::Max(), UE::Math::TVector< NumericType >::Max(), FMath::Max3(), TMathUtil< RealType >::Max3(), TMathUtil< float >::Max3(), UE::Math::TVector< T >::Max3(), UE::Math::TVector< NumericType >::Max3(), FMath::Max3Index(), TMathUtil< RealType >::Max3Index(), TMathUtil< float >::Max3Index(), TRangeBound< FDateTime >::MaxLower(), TRangeBound< FDateTime >::MaxUpper(), Merge(), FGenericPlatformMath::Min(), FMaterialCompiler::Min(), FProxyMaterialCompiler::Min(), MIR::FEmitter::Min(), TMathUtil< RealType >::Min(), TMathUtil< float >::Min(), TRDGHandle< FSocket, uint32 >::Min(), UE::Math::TVector2< T >::Min(), UE::Math::TVector2< FVector::FReal >::Min(), UE::Math::TVector< T >::Min(), UE::Math::TVector< NumericType >::Min(), FMath::Min3(), TMathUtil< RealType >::Min3(), TMathUtil< float >::Min3(), UE::Math::TVector< T >::Min3(), UE::Math::TVector< NumericType >::Min3(), FMath::Min3Index(), TMathUtil< RealType >::Min3Index(), TMathUtil< float >::Min3Index(), TRangeBound< FDateTime >::MinLower(), TMathUtil< RealType >::MinMax(), TMathUtil< float >::MinMax(), TRangeBound< FDateTime >::MinUpper(), Algo::Private::Mismatch(), FMaterialCompiler::Modulo(), FProxyMaterialCompiler::Modulo(), Move(), Move(), MoveByRelocate(), FMaterialCompiler::Mul(), FProxyMaterialCompiler::Mul(), MIR::FEmitter::Multiply(), UE::Math::TTransform< T >::Multiply(), UE::Math::TTransform< double >::Multiply(), FGenericPlatformMath::MultiplyAndCheckForOverflow(), TBigInt< NumBits, bSigned >::MultiplyFast(), UE::Math::TTransform< T >::MultiplyUsingMatrixWithScale(), UE::Math::TTransform< double >::MultiplyUsingMatrixWithScale(), UnFbx::FFbxHelper::NameCompareWeight(), NetworkGuidSetsAreSame(), MIR::FEmitter::NotEquals(), UE::Geometry::FRestrictedSubRegionRemesher::OnEdgeFlip(), UE::Geometry::FDynamicGraph2< double >::OpeningAngle(), UE::Geometry::VectorUtil::OpeningAngleD(), MIR::FEmitter::Operator(), FAssetDataTagMapSharedView::operator!=, FAssetDataTagMapSharedView::operator!=, FAssetDataTagMapSharedView::operator!=, FAssetTagValueRef::operator!=, FAssetTagValueRef::operator!=, FAssetTagValueRef::operator!=, FAssetTagValueRef::operator!=, FBlake3Hash::operator!=(), FCbObjectId::operator!=(), FCurveEditorToolID::operator!=, FCurveEditorTreeItemID::operator!=, FCurveEditorViewAxisID::operator!=, FCurveModelID::operator!=, FEdGraphSchemaActionDefiningObject::operator!=, FEvaluationTreeEntryHandle::operator!=, FFrameNumber::operator!=, FFrameRate::operator!=, FFrameTime::operator!=, FIoHash::operator!=, FMovieSceneAnimTypeID::operator!=, FMovieSceneBlendingActuatorID::operator!=, FMovieSceneBlendTypeField::operator!=, FMovieSceneChannelHandle::operator!=, FMovieSceneEvaluationTreeNodeHandle::operator!=, FMovieSceneInterrogationKey::operator!=, FMusicalTime::operator!=, FPackedNormal::operator!=(), FPackedRGB10A2N::operator!=(), FPackedRGBA16N::operator!=(), FParameterAllocation::operator!=, FPoly::operator!=, FPropertyVisitorInfo::operator!=, FPropertyVisitorPath::operator!=, FSequencerKeyCollectionSignature::operator!=, FSetElementId::operator!=, FShaderCodeVendorExtension::operator!=, FSlateIcon::operator!=, FTextId::operator!=, FTextKey::operator!=, FTimecode::operator!=, FTimecode::operator!=, FXxHash128::operator!=(), FXxHash64::operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), TMovieSceneEvaluationTreeDataIterator< DataType >::operator!=, TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator!=(), TStaticArray< InElementType, NumElements, Alignment >::FRangedForIterator< TArrayStorageElementAligned >::operator!=(), TStaticArray< int32, MAX_PHYSICS_FIELD_TARGETS, 16 >::operator!=(), UE::FDerivedDataIoPriority::operator!=, UE::GC::FMemberId::operator!=, UE::Math::TQuat< T >::operator!=(), UE::MovieScene::FComponentTypeID::operator!=, UE::MovieScene::FDirectedGraph::FDirectionalEdge::operator!=, UE::MovieScene::FFixedObjectBindingID::operator!=, UE::MovieScene::FHierarchicalBlendTarget::operator!=, UE::MovieScene::FInstanceHandle::operator!=, UE::MovieScene::FMovieSceneEntityID::operator!=, UE::MovieScene::TDynamicSparseBitSet< HashType, BucketStorage >::FIterator::operator!=, UE::MovieScene::TEntityPtr< T >::operator!=, UE::MovieScene::TEntityPtr< T... >::operator!=, UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::operator!=, UE::Sequencer::FDynamicExtensionContainerIterator::operator!=, UE::Sequencer::FOutlinerSizing::operator!=, UE::Sequencer::FParentFirstChildIterator::operator!=, UE::Sequencer::FParentModelIterator::operator!=, UE::Sequencer::FViewModelListIterator::operator!=, UE::Sequencer::FViewModelSubListIterator::operator!=, UE::Sequencer::FViewModelVariantIterator::operator!=, UE::Sequencer::TSelectionSetIteratorState< StorageKeyType, TFilteredSelectionSetIteratorImpl< StorageKeyType, FilterType > >::operator!=, UE::Sequencer::TUniqueFragmentSelectionSetIterator< KeyType >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TViewModelPtr< FViewModel >::operator!=, UE::Sequencer::TWeakViewModelPtr< ExtensionType >::operator!=, FFrameNumber::operator%, FFrameTime::operator%, operator&(), operator&(), TStaticBitArray< NumBits >::operator&, FAISightQuery::FSortPredicate::operator()(), FBehaviorTreeNodeInitializationData::FMemorySort::operator()(), FCompareBoneTransformIndex::operator()(), FCompareFActorPriority::operator()(), FCompareFNewTextureInfoByTextureSize::operator()(), FCompareShaderTypes::operator()(), FCompareSpectralDataByFrequencyHz::operator()(), FCompareVertexFactoryTypes::operator()(), FCookStatsManager::TKeyValuePair< FString, FString >::operator()(), FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FNodeSorter::operator()(), FLocKeySortedMapLess::operator()(), FNameFastLess::operator()(), FNameFastLess::operator()(), FNameLexicalLess::operator()(), FNameLexicalLess::operator()(), FObjectMemoryAnalyzer::FCompareFSortBySize::operator()(), FRedirectionSummary::FCompareRedirect::operator()(), FScriptStructSortOperator::operator()(), FStructTypeSortOperator::operator()(), FText::FSortPredicate::operator()(), FTickStats::operator()(), FTopLevelAssetPathFastLess::operator()(), FTopLevelAssetPathLexicalLess::operator()(), FWedgePositionHelper::FCompareIndexAndZ::operator()(), FWorkspaceItem::FWorkspaceItemSort::operator()(), TCompareShaderTypePermutation< MetaShaderType >::operator()(), TDereferenceWrapper< T, PREDICATE_CLASS >::operator()(), TDereferenceWrapper< T, PREDICATE_CLASS >::operator()(), TDereferenceWrapper< T *, PREDICATE_CLASS >::operator()(), TGreater< T >::operator()(), TGreater< void >::operator()(), TKeyValuePair< double, uint32 >::operator()(), TLess< T >::operator()(), TLess< void >::operator()(), TPlus< T >::operator()(), TPlus< void >::operator()(), TReversePredicate< PredicateType >::operator()(), TSet< InElementType, KeyFuncs, Allocator >::FElementCompareClass< PREDICATE_CLASS >::operator()(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FKeyComparisonClass< PREDICATE_CLASS >::operator()(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FValueComparisonClass< PREDICATE_CLASS >::operator()(), TSparseArray< InElementType, Allocator >::FElementCompareClass< PREDICATE_CLASS >::operator()(), FFrameRate::operator*, FStaticLightingVertex::operator*, operator*(), UE::Geometry::operator*(), UE::Math::TDualQuat< T >::operator*(), UE::Math::TQuat< double >::operator*(), UE::Math::TQuat< T >::operator*=(), UE::Math::TQuat< double >::operator*=(), FFrameNumber::operator+, FFrameTime::operator+, FSlateRect::operator+, FStaticLightingVertex::operator+, UE::Geometry::operator+(), UE::Math::TDualQuat< T >::operator+(), UE::Math::TQuat< T >::operator+(), UE::Math::TQuat< T >::operator+=(), FFrameNumber::operator-, FFrameTime::operator-, FSlateRect::operator-, FStaticLightingVertex::operator-, UE::Geometry::operator-(), UE::Math::TQuat< T >::operator-(), UE::Math::TQuat< T >::operator-=(), FFrameRate::operator/, FStaticLightingVertex::operator/, UE::Math::TQuat< double >::operator/(), UE::Math::TQuat< double >::operator/=(), FBlake3Hash::operator<(), FCbObjectId::operator<(), FCurveEditorViewAxisID::operator<, FCurveModelID::operator<, FFrameNumber::operator<, FFrameTime::operator<, FIoHash::operator<, FKeyHandle::operator<, FMovieSceneBlenderSystemID::operator<, FMusicalTime::operator<, FXxHash128::operator<(), FXxHash64::operator<(), UE::FDerivedDataIoPriority::operator<, UE::MovieScene::FComponentTypeID::operator<, UE::MovieScene::FDirectedGraph::FDirectionalEdge::operator<, UE::MovieScene::FEntityHandle::operator<, UE::MovieScene::FHierarchicalBlendTarget::operator<, UE::MovieScene::FInstanceHandle::operator<, UE::MovieScene::FMovieSceneEntityID::operator<, UE::MovieScene::FPreAnimatedStorageID::operator<, UE::SequenceNavigator::FNavigationToolViewModelTypeID::operator<, UE::Sequencer::FOutlinerColumnPosition::operator<, UE::Sequencer::FViewModelTypeID::operator<, FBoneContainer::operator<<, FModelVertexBuffer::operator<<, FRenderBounds::operator<<, FFrameNumber::operator<=, FFrameTime::operator<=, FMusicalTime::operator<=, FAnimatedPropertyKey::operator==, FAssetDataTagMapSharedView::operator==, FAssetDataTagMapSharedView::operator==, FAssetDataTagMapSharedView::operator==, FAssetIdentifier::operator==, FAssetRegistryExportPath::operator==, FAssetTagValueRef::operator==, FAssetTagValueRef::operator==, FAssetTagValueRef::operator==, FAssetTagValueRef::operator==, FBlake3Hash::operator==(), FCardRepresentationDataId::operator==(), FCbObjectId::operator==(), FCurveEditorToolID::operator==, FCurveEditorTreeItemID::operator==, FCurveEditorViewAxisID::operator==, FCurveModelID::operator==, FDisplayNameEntryId::operator==, FDisplayNameEntryId::operator==, FDisplayNameEntryId::operator==, FEdGraphSchemaActionDefiningObject::operator==, FEvaluationTreeEntryHandle::operator==, FFrameNumber::operator==, FFrameRate::operator==, FFrameTime::operator==, FIoHash::operator==, FixedTagPrivate::FMapHandle::operator==, FixedTagPrivate::operator==(), FLazyName::operator==, FMallocCallstackHandler::FCallStackMapKey::operator==, FMeshBoneInfo::operator==(), FMovieSceneAnimTypeID::operator==, FMovieSceneBlendChannelID::operator==, FMovieSceneBlenderSystemID::operator==, FMovieSceneBlendingActuatorID::operator==, FMovieSceneBlendingKey::operator==, FMovieSceneBlendTypeField::operator==, FMovieSceneChannelHandle::operator==, FMovieSceneEvaluationTreeNode::operator==, FMovieSceneEvaluationTreeNodeHandle::operator==, FMovieSceneInterrogationKey::operator==, FMovieSceneSharedDataId::operator==, FMusicalTime::operator==, FOperatorFunctionID::operator==, FPackedNormal::operator==(), FPackedRGB10A2N::operator==(), FPackedRGBA16N::operator==(), FParameterAllocation::operator==, FPinConnectionResponse::operator==, FPoly::operator==, FPropertyPermissionList::operator==, FPropertyVisitorInfo::operator==, FPropertyVisitorPath::operator==, FRepSharedPropertyKey::operator==, FRigVMExplorerElementKey::operator==, FRigVMPinConnectionResponse::operator==, FSceneViewOwner::operator==, FSequencerKeyCollectionSignature::operator==, FSetElementId::operator==, FSetProfileRequest::operator==, FShaderCodeLibraryPipeline::operator==, FShaderCodeVendorExtension::operator==, FSharedPersistentDataKey::operator==, FSimpleStreamableAssetManager::FAssetRecord::operator==, FSlateIcon::operator==, FStableShaderKeyAndValue::operator==, FTextId::operator==, FTextKey::operator==, FTimecode::operator==, FTimecode::operator==, FVertexFactory::FVertexStream::operator==, FXxHash128::operator==(), FXxHash64::operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), TEvaluationTreeEntryContainer< ElementType >::FEntry::operator==, TEvaluationTreeEntryContainer< ElementType >::operator==, TMatrix2x2< float >::operator==(), TMovieSceneEvaluationTree< DataType >::operator==, TMovieSceneEvaluationTreeDataIterator< DataType >::operator==, TRefCountPtr< FBaseGraphTask >::operator==(), TRefCountPtr< FBaseGraphTask >::operator==(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator==(), TStaticArray< int32, MAX_PHYSICS_FIELD_TARGETS, 16 >::operator==, TStaticBitArray< NumBits >::operator==(), UE::FDerivedDataIoPriority::operator==, UE::FIoBlockKey::operator==, UE::GC::FMemberId::operator==, UE::Math::TQuat< T >::operator==(), UE::MovieScene::FComplexInclusivityFilter::operator==, UE::MovieScene::FComponentMask::operator==, UE::MovieScene::FComponentMaterialKey::operator==, UE::MovieScene::FComponentTypeID::operator==, UE::MovieScene::FDirectedGraph::FDirectionalEdge::operator==, UE::MovieScene::FEntityGroupID::operator==, UE::MovieScene::FEntityGroupingPolicyKey::operator==, UE::MovieScene::FEntityHandle::operator==, UE::MovieScene::FFixedObjectBindingID::operator==, UE::MovieScene::FHierarchicalBlendTarget::operator==, UE::MovieScene::FInstanceHandle::operator==, UE::MovieScene::FMaterialParameterKey::operator==, UE::MovieScene::FMovieSceneEntityID::operator==, UE::MovieScene::FObjectComponent::operator==, UE::MovieScene::FPreAnimatedEvalHookKeyType::operator==, UE::MovieScene::FPreAnimatedEvaluationKeyType::operator==, UE::MovieScene::FPreAnimatedStateCachedValueHandle::operator==, UE::MovieScene::FPreAnimatedStateEntry::operator==, UE::MovieScene::FPreAnimatedStorageGroupHandle::operator==, UE::MovieScene::FPreAnimatedStorageID::operator==, UE::MovieScene::FPreAnimatedStorageIndex::operator==, UE::MovieScene::TDynamicSparseBitSet< HashType, BucketStorage >::FIterator::operator==, UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::operator==, UE::MovieScene::TOverlappingEntityInput< InputKeyTypes... >::operator==, UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FKeyType::operator==, UE::SequenceNavigator::FNavigationToolViewModelTypeID::operator==, UE::Sequencer::FOutlinerSizing::operator==, UE::Sequencer::FSortingKey::operator==, UE::Sequencer::FViewModelTypeID::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TViewModelPtr< FViewModel >::operator==, UE::Sequencer::TWeakViewModelPtr< ExtensionType >::operator==, FFrameNumber::operator>, FFrameTime::operator>, FKeyHandle::operator>, FMusicalTime::operator>, UE::Sequencer::FObjectSchemaRelevancy::operator>, FFrameNumber::operator>=, FFrameTime::operator>=, FMusicalTime::operator>=, TStaticBitArray< NumBits >::operator^, operator|(), operator|(), TStaticBitArray< NumBits >::operator|, UE::MovieScene::FComponentTypeID::operator|, UE::MovieScene::FComponentTypeID::operator|, FMaterialRelevance::operator|=(), FPrimitiveViewRelevance::operator|=(), MIR::FEmitter::Or(), UE::Geometry::Orient(), UE::Geometry::ExactPredicates::Orient2(), UE::Geometry::ExactPredicates::Orient2Origin(), UE::Geometry::ExactPredicates::Orient3(), FHairStrandsRootUtils::PackBarycentrics(), FTabInfo::PayloadMatches(), FGeomTools::PointInTriangle(), UE::Geometry::PointInTriangle2d(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::PointInTriangle2d(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointInTriangle2d(), UE::Math::TVector< T >::PointPlaneProject(), UE::Math::TVector< NumericType >::PointPlaneProject(), FGenericPlatformMath::Pow(), FGenericPlatformMath::Pow(), FBlueprintCompileReinstancer::ReinstancerOrderingFunction(), UE::Geometry::FDynamicGraph::RemoveEdge(), FScriptSetHelper::RemoveElement(), FScriptMapHelper::RemovePair(), UE::Geometry::FDynamicGraph::replace_edge_vertex(), CEqualityComparableWith::Requires(), FWatchablePropertySet::TPropertyWatcher< PropType >::CInequalityComparable::Requires(), FMath::SegmentTriangleIntersection(), MIR::FEmitter::Select(), FWeakObjectProperty::SerializeItem(), UE::Geometry::TInterval1< float >::Set(), FExpressionInput::SetMask(), FExpressionOutput::SetMask(), UE::Geometry::TIntrTriangle3Triangle3< float >::SetResult(), UE::Geometry::FMeshShapeGenerator::SetTriangle(), UE::Geometry::FMeshShapeGenerator::SetTriangle(), UE::Geometry::FMeshShapeGenerator::SetTriangleNormals(), UE::Geometry::FMeshShapeGenerator::SetTriangleNormals(), UE::Geometry::FMeshShapeGenerator::SetTriangleUVs(), UE::Geometry::FMeshShapeGenerator::SetTriangleUVs(), UE::Geometry::FMeshShapeGenerator::SetTriangleWithMatchedUVNormal(), UE::Geometry::TTriangle2< float >::SignedArea(), TMathUtil< RealType >::SmoothMax(), TMathUtil< float >::SmoothMax(), TMathUtil< RealType >::SmoothMin(), TMathUtil< float >::SmoothMin(), FMath::SmoothStep(), MIR::FEmitter::Smoothstep(), FStaticSpatialIndex::TNodeSorterHilbert< FStaticSpatialIndex::FSpatialIndexProfile3D, 65536 >::Sort(), FStaticSpatialIndex::TNodeSorterMinX< Profile >::Sort(), FStaticSpatialIndex::TNodeSorterMorton< Profile, BucketSize >::Sort(), FStaticSpatialIndex::TNodeSorterNoSort< Profile >::Sort(), FThreadPoolPriorityQueue::Sort(), UE::MovieScene::FEvaluationTreePopulationRules::FSortedSection::SortByOverlapPriorityAndRow(), FMovieSceneAdditiveCameraTrackBlender::SortByStartTime(), MovieSceneHelpers::SortLowerBounds(), MovieSceneHelpers::SortOverlappingSections(), MovieSceneHelpers::SortUpperBounds(), UE::Math::TBoxSphereBounds< float, float >::SpheresIntersect(), UE::Geometry::FDynamicGraph::SplitEdge(), UE::Geometry::FDynamicGraph::SplitEdgeWithExistingVertex(), FMath::SpringDamper(), UE::StateTree::FActiveStatePath::StartsWith(), StateStreamEquals(), FObjectPropertyBase::StaticIdentical(), FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), FCrc::Strihash_DEPRECATED(), FMaterialCompiler::Sub(), FProxyMaterialCompiler::Sub(), TBVTree< InElementType, InAllocator >::Subdivide(), FMaterialCompiler::SubstrateAdd(), FProxyMaterialCompiler::SubstrateAdd(), FMaterialCompiler::SubstrateAddParameterBlending(), FProxyMaterialCompiler::SubstrateAddParameterBlending(), SubstrateMergeSubSurfaceType(), FMaterialCompiler::SubstrateSelectParameterBlending(), FProxyMaterialCompiler::SubstrateSelectParameterBlending(), MIR::FEmitter::Subtract(), FGenericPlatformMath::SubtractAndCheckForOverflow(), UE::Math::TTransform< double >::SubtractTranslations(), Swap(), Swap(), Swap(), Swap(), TScriptArray< FHeapAllocator >::SwapMemory(), FScriptArrayHelper::SwapValues(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), FMath::TIsNearlyEqualByULP(), TTransform2< float >::To3DMatrix(), UE::Geometry::TMeshQueries< TriangleMeshType >::TotalEdgeLength(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TriangleIntersectionFilter(), UE::AI::TriArea2D(), UE::AI::TriArea2D(), UE::Geometry::VectorUtil::TriSolidAngle(), MIR::FEmitter::TryGetCommonType(), UCLASS(), UE_DEPRECATED(), UE_DEPRECATED(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UBlueprintSetLibrary::UFUNCTION(), UKismetInputLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UE::Geometry::VectorUtil::UniformSampleTrianglePoint(), UE::Geometry::VectorUtil::UniformSampleTrianglePoint(), UE::Geometry::FSizedDisjointSet::Union(), UE::Math::TBoxSphereBounds< float, float >::Union, FHairStrandsRootUtils::UnpackBarycentrics(), FModelVertexBuffer::UpdateHash, USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), FGenericPlatformMemory::Valswap(), VectorIntAdd(), VectorIntAnd(), VectorIntAndNot(), VectorIntCompareEQ(), VectorIntCompareGE(), VectorIntCompareGT(), VectorIntCompareLE(), VectorIntCompareLT(), VectorIntCompareNEQ(), VectorIntMax(), VectorIntMin(), VectorIntMultiply(), VectorIntOr(), VectorIntSubtract(), VectorIntXor(), VectorMatrixMultiply(), VectorMatrixMultiply(), FPixelStreamingVideoInputBackBufferComposited::VectorMax(), UE::EditorPixelStreaming2::FVideoProducerBackBufferComposited::VectorMax(), FPixelStreamingVideoInputBackBufferComposited::VectorMin(), UE::EditorPixelStreaming2::FVideoProducerBackBufferComposited::VectorMin(), VectorQuaternionMultiply(), VectorQuaternionMultiply(), FGeomTools::VectorsOnSameSide(), UE::Geometry::VectorUtil::VectorTanHalfAngle(), UE::Geometry::VectorUtil::VectorTanHalfAngle(), and UE::Geometry::CurveUtil::WindingIntegral2().