Unreal Engine 5.6 C++ API: Runtime/Core/Public/Containers/UnrealString.h File Reference
UnrealString.h File Reference
#include "Containers/UnrealStringIncludes.h.inl"
#include "Containers/UnrealString.h.inl"
#include "Misc/StringFormatArg.h"
Data Structures
class FStringOutputDevice
class FStringOutputDeviceCountLines
struct FTextRange
struct TIsContiguousContainer< FStringOutputDevice >
struct TIsContiguousContainer< FStringOutputDeviceCountLines >
struct TTypeFromString< T >
struct TTypeToString< T >
Shorthand legacy use for Lex functions.
Namespaces
namespace StringConv
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define UE_STRING_CHARTYPE TCHAR
#define UE_STRING_CHARTYPE_IS_TCHAR 1
#define UE_STRING_CLASS FString
#define UE_STRING_DEPRECATED(Version, Message)
#define UE_STRING_PRINTF_FMT_CHARTYPE TCHAR
Functions
FString BytesToHex (const uint8 *Bytes, int32 NumBytes)
Convert bytes to uppercase hex string.
FString BytesToHexLower (const uint8 *Bytes, int32 NumBytes)
Convert bytes to lowercase hex string.
FString BytesToString (const uint8 *In, int32 Count)
Convert an array of bytes to a string.
void ByteToHex (uint8 In, FString &Result)
Convert a byte to hex.
const bool CheckTCharIsHex (const TCHAR Char)
Checks if the TChar is a valid hex character.
void StringConv::InlineCombineSurrogates (FString &Str)
Inline combine any UTF-16 surrogate pairs in the given string.
template<typename StringType = FString, typename T>
StringType LexToSanitizedString (const T &Value)
Helper template to convert to sanitized strings.
template<typename StringType = FString>
StringType LexToSanitizedString (double Value)
Overloaded for doubles.
template<typename StringType = FString>
StringType LexToSanitizedString (float Value)
Overloaded for floats.
template<typename StringType = FString>
StringType LexToString (bool Value)
template<typename StringType = FString, typename CharType UE_REQUIRES>
StringType LexToString (const CharType *Ptr)
template<typename StringType = FString, typename T UE_REQUIRES>
StringType LexToString (const T &Value)
Convert numeric types to a string.
template<typename CharType>
bool LexTryParseString (bool &OutValue, const CharType *Buffer)
Try and parse a bool - always returns true.
template<typename T, typename CharType UE_REQUIRES>
bool LexTryParseString (T &OutValue, const CharType *Buffer)
Parse a string into this type, returning whether it was successful.
TCHAR NibbleToTChar (uint8 Num)
Returns uppercase Char value of Nibble.
TCHAR NibbleToTCharLower (uint8 Num)
Returns lowercase Char value of Nibble.
int32 StringToBytes (const FString &String, uint8 *OutBytes, int32 MaxBufferSize)
Convert FString of bytes into the byte array.
void UE::Core::Private::StripNegativeZero (double &InFloat)
const uint8 TCharToNibble (const TCHAR Hex)
Convert a TChar to equivalent hex value as a uint8.
Macro Definition Documentation
UE_STRING_CHARTYPE
#define UE_STRING_CHARTYPE TCHAR
Definition at line 12 of file UnrealString.h.
UE_STRING_CHARTYPE_IS_TCHAR
#define UE_STRING_CHARTYPE_IS_TCHAR 1
Definition at line 13 of file UnrealString.h.
UE_STRING_CLASS
#define UE_STRING_CLASS FString
Definition at line 11 of file UnrealString.h.
UE_STRING_DEPRECATED
#define UE_STRING_DEPRECATED (Version, Message)
Definition at line 15 of file UnrealString.h.
UE_STRING_PRINTF_FMT_CHARTYPE
#define UE_STRING_PRINTF_FMT_CHARTYPE TCHAR
Definition at line 14 of file UnrealString.h.
Function Documentation
BytesToHex()
FString BytesToHex (const uint8 * Bytes, int32 NumBytes) inline nodiscard
Convert bytes to uppercase hex string.
Definition at line 101 of file UnrealString.h.
References Bytes, and BytesToHex().
Referenced by FSHAHash::AppendString(), BytesToHex(), DisplayClusterTypesConverter::ToHexString(), DisplayClusterTypesConverter::ToHexString(), and FSHAHash::ToString().
BytesToHexLower()
FString BytesToHexLower (const uint8 * Bytes, int32 NumBytes) inline nodiscard
Convert bytes to lowercase hex string.
Definition at line 109 of file UnrealString.h.
References Bytes, and BytesToHexLower().
Referenced by BytesToHexLower().
BytesToString()
FString BytesToString (const uint8 * In, int32 Count) inline nodiscard
Convert an array of bytes to a string.
Parameters
In byte array values to convert
Count number of bytes to convert
Returns
Valid string representing bytes.
Definition at line 29 of file UnrealString.h.
References Count, and Value.
ByteToHex()
void ByteToHex (uint8 In, FString & Result) inline
Convert a byte to hex.
Parameters
In byte value to convert
Result out hex value output
Definition at line 94 of file UnrealString.h.
References NibbleToTChar().
Referenced by FArcToHexString::MakeString().
CheckTCharIsHex()
const bool CheckTCharIsHex (const TCHAR Char) inline nodiscard
Checks if the TChar is a valid hex character.
Parameters
Char The character
Returns
True if in 0-9 and A-F ranges
Definition at line 121 of file UnrealString.h.
References TEXT.
LexToSanitizedString() [1/3]
template<typename StringType = FString, typename T> StringType LexToSanitizedString (const T & Value) nodiscard
Helper template to convert to sanitized strings.
Definition at line 180 of file UnrealString.h.
References LexToString(), and Value.
Referenced by SGridLineSpacingList::GetValueText(), SGraphPinNumSlider< NumericType >::OnValueChanged(), SGraphPinNumSlider< NumericType >::OnValueCommitted(), TTypeToString< T >::ToSanitizedString(), and UE::Math::TSphere< double >::ToString().
LexToSanitizedString() [2/3]
template<typename StringType = FString> StringType LexToSanitizedString (double Value) inline nodiscard
Overloaded for doubles.
Definition at line 194 of file UnrealString.h.
References Value.
LexToSanitizedString() [3/3]
template<typename StringType = FString> StringType LexToSanitizedString (float Value) inline nodiscard
Overloaded for floats.
Definition at line 187 of file UnrealString.h.
References Value.
LexToString() [1/3]
template<typename StringType = FString> StringType LexToString (bool Value) inline nodiscard
Definition at line 172 of file UnrealString.h.
References CHARTEXT, and Value.
LexToString() [2/3]
template<typename StringType = FString, typename CharType UE_REQUIRES> StringType LexToString (const CharType * Ptr) nodiscard
Definition at line 166 of file UnrealString.h.
LexToString() [3/3]
template<typename StringType = FString, typename T UE_REQUIRES> StringType LexToString (const T & Value) nodiscard
Convert numeric types to a string.
Definition at line 155 of file UnrealString.h.
References Value.
Referenced by LexToSanitizedString(), and TTypeToString< T >::ToString().
LexTryParseString() [1/2]
template<typename CharType> bool LexTryParseString (bool & OutValue, const CharType * Buffer) inline
Try and parse a bool - always returns true.
Definition at line 259 of file UnrealString.h.
References Buffer, and LexFromString().
LexTryParseString() [2/2]
template<typename T, typename CharType UE_REQUIRES> bool LexTryParseString (T & OutValue, const CharType * Buffer)
Parse a string into this type, returning whether it was successful.
Specialization for arithmetic types
Definition at line 223 of file UnrealString.h.
References Buffer, CHARTEXT, TChar< CharType >::IsWhitespace(), and LexFromString().
NibbleToTChar()
TCHAR NibbleToTChar (uint8 Num) inline nodiscard
Returns uppercase Char value of Nibble.
Definition at line 70 of file UnrealString.h.
References Num.
Referenced by ByteToHex(), and FSHAHash::ToString().
NibbleToTCharLower()
TCHAR NibbleToTCharLower (uint8 Num) inline nodiscard
Returns lowercase Char value of Nibble.
Definition at line 80 of file UnrealString.h.
References Num.
StringToBytes()
int32 StringToBytes (const FString & String, uint8 * OutBytes, int32 MaxBufferSize) inline
Convert FString of bytes into the byte array.
Parameters
String The FString of byte values
OutBytes Ptr to memory must be preallocated large enough
MaxBufferSize Max buffer size of the OutBytes array, to prevent overflow
Returns
The number of bytes copied
Definition at line 55 of file UnrealString.h.
References String.
TCharToNibble()
const uint8 TCharToNibble (const TCHAR Hex) inline nodiscard
Convert a TChar to equivalent hex value as a uint8.
Parameters
Hex The character
Returns
The uint8 value of a hex character
Definition at line 131 of file UnrealString.h.
References checkf, and TEXT.