Unreal Engine 5.6 C++ API: Runtime/Core/Public/Math/UnrealMathFPU.h File Reference
UnrealMathFPU.h File Reference
#include "HAL/UnrealMemory.h"
#include <cmath>
#include "Math/UnrealMathVectorConstants.h.inl"
Data Structures
struct AlignedDouble4
struct AlignedFloat4
struct VectorRegister2Double
struct VectorRegister4Double
double[4] vector register type, where the first double (X) is stored in the lowest 64 bits, and so on.
struct VectorRegister4Float
float4 vector register type, where the first float (X) is stored in the lowest 32 bits, and so on.
struct VectorRegister4Int
int32[4] vector register type, where the first int32 (X) is stored in the lowest 32 bits, and so on.
struct VectorRegister4x4Float
struct VectorRegisterConstInit
Macros
#define DECLARE_VECTOR_REGISTER(X, Y, Z, W)
#define USE_FAST_QUAT_MUL 1
#define VECTOR_DENORMALS_FLUSH_TO_ZERO 0
Denormal operands and results will be flushed to zero.
#define VECTOR_ROUND_TOWARD_ZERO 0
Control status bit to round all floating point math results towards zero.
#define VectorCastDoubleToInt(Vec)
#define VectorCastFloatToInt(Vec)
#define VectorCastIntToDouble(Vec)
#define VectorCastIntToFloat(Vec)
#define VectorGetComponent(Vec, ComponentIndex)
#define VectorGetControlRegister()
Returns the control register.
#define VectorIntExpandLow16To32(V0)
#define VectorIntSet1(F)
#define VectorIntSign(A)
#define VectorLoadByte4(Ptr)
Loads 4 BYTEs from unaligned memory and converts them into 4 FLOATs.
#define VectorLoadByte4Reverse(Ptr)
Loads 4 BYTEs from unaligned memory and converts them into 4 FLOATs in reversed order.
#define VectorLoadSignedByte4(Ptr)
Loads 4 signed BYTEs from unaligned memory and converts them into 4 FLOATs.
#define VectorOneVectorRegister()
#define VectorReplicate(Vec, ElementIndex)
Replicates one element into all four elements and returns the new vector.
#define VectorResetFloatRegisters()
Resets the floating point registers so that they can be used again.
#define VectorSet1(F)
#define VectorSetControlRegister(ControlStatus)
Sets the control register.
#define VectorSetZero()
#define VectorShiftLeftImm(Vec, ImmAmt)
#define VectorShiftRightImmArithmetic(Vec, ImmAmt)
#define VectorShiftRightImmLogical(Vec, ImmAmt)
#define VectorShuffle(Vec1, Vec2, X, Y, Z, W)
Creates a vector through selecting two components from each vector via a shuffle mask.
#define VectorShuffleImmediate(Vec, I0, I1, I2, I3)
#define VectorSwizzle(Vec, X, Y, Z, W)
Swizzles the 4 components of a vector and returns the result.
#define VectorZeroVectorRegister()
Typedefs
typedef AlignedDouble4 AlignedRegister4
typedef VectorRegister4 VectorRegister
typedef VectorRegister2Double VectorRegister2d
typedef VectorRegister4Double VectorRegister4
typedef VectorRegister4Double VectorRegister4d
typedef VectorRegister4Float VectorRegister4f
typedef VectorRegister4Int VectorRegister4i
typedef VectorRegister4Int VectorRegisterInt
Functions
FORCEINLINE VectorRegister4Double MakeVectorRegister (double X, double Y, double Z, double W)
FORCEINLINE VectorRegister4Float MakeVectorRegister (float X, float Y, float Z, float W)
FORCEINLINE VectorRegister4Float MakeVectorRegister (uint32 X, uint32 Y, uint32 Z, uint32 W)
FORCEINLINE VectorRegister2Double MakeVectorRegister2Double (double X, double Y)
FORCEINLINE constexpr VectorRegister2Double MakeVectorRegister2DoubleConstant (double X, double Y)
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (const VectorRegister2Double &XY, const VectorRegister2Double &ZW)
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (const VectorRegister4Float &From)
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (double X, double Y, double Z, double W)
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (uint64 X, uint64 Y, uint64 Z, uint64 W)
FORCEINLINE VectorRegister4Double MakeVectorRegisterDoubleMask (uint64 X, uint64 Y, uint64 Z, uint64 W)
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloat (float X, float Y, float Z, float W)
Returns a vector based on 4 FLOATs.
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloat (uint32 X, uint32 Y, uint32 Z, uint32 W)
Returns a bitwise equivalent vector based on 4 DWORDs.
FORCEINLINE constexpr VectorRegister4Float MakeVectorRegisterFloatConstant (float X, float Y, float Z, float W)
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloatFromDouble (const VectorRegister4Double &Vec4d)
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloatMask (uint32 X, uint32 Y, uint32 Z, uint32 W)
FORCEINLINE VectorRegister4Int MakeVectorRegisterInt (int32 X, int32 Y, int32 Z, int32 W)
Returns a vector based on 4 int32.
FORCEINLINE VectorRegister4Int MakeVectorRegisterInt64 (int64 X, int64 Y)
FORCEINLINE constexpr VectorRegister4Int MakeVectorRegisterIntConstant (int32 X, int32 Y, int32 Z, int32 W)
FORCEINLINE VectorRegister4Double VectorAbs (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorAbs (const VectorRegister4Float &Vec)
Returns the absolute value (component-wise).
FORCEINLINE VectorRegister4Double VectorACos (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorACos (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorAdd (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorAdd (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Adds two vectors (component-wise) and returns the result.
FORCEINLINE uint32 VectorAnyGreaterThan (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE uint32 VectorAnyGreaterThan (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Returns non-zero if any element in Vec1 is greater than the corresponding element in Vec2, otherwise 0.
FORCEINLINE VectorRegister4Double VectorASin (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorASin (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorATan (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorATan (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorATan2 (const VectorRegister4Double &Y, const VectorRegister4Double &X)
FORCEINLINE VectorRegister4Float VectorATan2 (const VectorRegister4Float &Y, const VectorRegister4Float &X)
FORCEINLINE VectorRegister4Double VectorBitwiseAnd (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorBitwiseAnd (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Combines two vectors using bitwise AND (treating each vector as a 128 bit field)
FORCEINLINE VectorRegister4Double VectorBitwiseOr (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorBitwiseOr (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Combines two vectors using bitwise OR (treating each vector as a 128 bit field)
FORCEINLINE VectorRegister4Double VectorBitwiseXor (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorBitwiseXor (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Combines two vectors using bitwise XOR (treating each vector as a 128 bit field)
FORCEINLINE VectorRegister4Double VectorCeil (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorCeil (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorCombineHigh (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCombineHigh (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a vector by combining two high components from each vector.
FORCEINLINE VectorRegister4Double VectorCombineLow (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCombineLow (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a vector by combining two low components from each vector.
FORCEINLINE VectorRegister4Double VectorCompareEQ (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCompareEQ (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a four-part mask based on component-wise == compares of the input vectors.
FORCEINLINE VectorRegister4Double VectorCompareGE (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCompareGE (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a four-part mask based on component-wise >= compares of the input vectors.
FORCEINLINE VectorRegister4Double VectorCompareGT (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCompareGT (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a four-part mask based on component-wise > compares of the input vectors.
FORCEINLINE VectorRegister4Double VectorCompareLE (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCompareLE (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a four-part mask based on component-wise <= compares of the input vectors.
FORCEINLINE VectorRegister4Double VectorCompareLT (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCompareLT (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a four-part mask based on component-wise < compares of the input vectors.
FORCEINLINE VectorRegister4Double VectorCompareNE (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCompareNE (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Creates a four-part mask based on component-wise != compares of the input vectors.
bool VectorContainsNaNOrInfinite (const VectorRegister4Double &Vec)
bool VectorContainsNaNOrInfinite (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorCos (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorCos (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorCross (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorCross (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Calculates the cross product of two vectors (XYZ components).
FORCEINLINE void VectorDeinterleave (VectorRegister4Double &RESTRICT OutEvens, VectorRegister4Double &RESTRICT OutOdds, const VectorRegister4Double &RESTRICT Lo, const VectorRegister4Double &RESTRICT Hi)
FORCEINLINE void VectorDeinterleave (VectorRegister4Float &RESTRICT OutEvens, VectorRegister4Float &RESTRICT OutOdds, const VectorRegister4Float &RESTRICT Lo, const VectorRegister4Float &RESTRICT Hi)
Deinterleaves the components of the two given vectors such that the even components are in one vector and the odds in another.
FORCEINLINE VectorRegister4Double VectorDivide (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorDivide (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Divides two vectors (component-wise) and returns the result.
FORCEINLINE VectorRegister4Double VectorDot3 (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorDot3 (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Calculates the dot3 product of two vectors and returns a vector with the result in all 4 components.
FORCEINLINE double VectorDot3Scalar (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE float VectorDot3Scalar (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Calculates the dot3 product of two vectors and returns a scalar value.
FORCEINLINE VectorRegister4Double VectorDot4 (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorDot4 (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Calculates the dot4 product of two vectors and returns a vector with the result in all 4 components.
FORCEINLINE VectorRegister2Double VectorDoubleLoad (const void *Ptr)
Loads 2 doubles from unaligned memory.
FORCEINLINE VectorRegister4Int VectorDoubleToInt (const VectorRegister4Double &A)
FORCEINLINE VectorRegister4Double VectorExp (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorExp (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorExp2 (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorExp2 (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Int VectorFloatToInt (const VectorRegister4Double &A)
FORCEINLINE VectorRegister4Int VectorFloatToInt (const VectorRegister4Float &A)
FORCEINLINE VectorRegister4Double VectorFloor (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorFloor (const VectorRegister4Float &Vec)
FORCEINLINE double VectorGetComponentDynamic (const VectorRegister4Double &Vec, uint32 ComponentIndex)
FORCEINLINE float VectorGetComponentDynamic (const VectorRegister4Float &Vec, uint32 ComponentIndex)
template<uint32 ComponentIndex>
FORCEINLINE double VectorGetComponentImpl (const VectorRegister4Double &Vec)
template<uint32 ComponentIndex>
FORCEINLINE float VectorGetComponentImpl (const VectorRegister4Float &Vec)
Returns an component from a vector.
FORCEINLINE VectorRegister4Int VectorInt64Load (const void *Ptr)
Loads 2 int64s from unaligned memory.
FORCEINLINE VectorRegister4Int VectorIntAbs (const VectorRegister4Int &A)
FORCEINLINE VectorRegister4Int VectorIntAdd (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntAnd (const VectorRegister4Int &A, const VectorRegister4Int &B)
= a & b
FORCEINLINE VectorRegister4Int VectorIntAndNot (const VectorRegister4Int &A, const VectorRegister4Int &B)
= (~a) & b to match _mm_andnot_si128
FORCEINLINE VectorRegister4Int VectorIntCompareEQ (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntCompareGE (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntCompareGT (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntCompareLE (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntCompareLT (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntCompareNEQ (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntLoad (const void *Ptr)
Loads 4 int32s from unaligned memory.
FORCEINLINE VectorRegister4Int VectorIntLoad1 (const void *Ptr)
Loads 1 int32 from unaligned memory into all components of a vector register.
FORCEINLINE VectorRegister4Int VectorIntLoadAligned (const void *Ptr)
Loads 4 int32s from aligned memory.
FORCEINLINE VectorRegister4Int VectorIntMax (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntMin (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntMultiply (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Int VectorIntNegate (const VectorRegister4Int &A)
FORCEINLINE VectorRegister4Int VectorIntNot (const VectorRegister4Int &A)
= ~a
FORCEINLINE VectorRegister4Int VectorIntOr (const VectorRegister4Int &A, const VectorRegister4Int &B)
= a | b
FORCEINLINE VectorRegister4Int VectorIntSelect (const VectorRegister4Int &Mask, const VectorRegister4Int &Vec1, const VectorRegister4Int &Vec2)
FORCEINLINE void VectorIntStore (const VectorRegister4Int &A, const void *Ptr)
Stores a vector to memory (aligned or unaligned).
FORCEINLINE void VectorIntStoreAligned (const VectorRegister4Int &A, const void *Ptr)
Stores a vector to memory (aligned).
FORCEINLINE VectorRegister4Int VectorIntSubtract (const VectorRegister4Int &A, const VectorRegister4Int &B)
FORCEINLINE VectorRegister4Float VectorIntToFloat (const VectorRegister4Int &A)
FORCEINLINE VectorRegister4Int VectorIntXor (const VectorRegister4Int &A, const VectorRegister4Int &B)
= a ^ b
FORCEINLINE VectorRegister4Double VectorLoad (const double *Ptr)
FORCEINLINE VectorRegister4Float VectorLoad (const float *Ptr)
Loads 4 FLOATs from unaligned memory.
FORCEINLINE VectorRegister4x4Float VectorLoad16 (const float *Ptr)
Loads 16 floats from unaligned memory into 4 vector registers.
VectorRegister4Double VectorLoadAligned (const double *Ptr)
VectorRegister4Float VectorLoadAligned (const float *Ptr)
Loads 4 FLOATs from aligned memory.
FORCEINLINE VectorRegister4Double VectorLoadDouble1 (const double *Ptr)
FORCEINLINE VectorRegister4Float VectorLoadFloat1 (const float *Ptr)
Loads 1 float from unaligned memory and replicates it to all 4 elements.
FORCEINLINE VectorRegister4Double VectorLoadFloat2 (const double *Ptr)
FORCEINLINE VectorRegister4Float VectorLoadFloat2 (const float *Ptr)
Loads 2 floats from unaligned memory into X and Y and duplicates them in Z and W.
FORCEINLINE VectorRegister4Double VectorLoadFloat3 (const double *Ptr)
Loads 3 FLOATs from unaligned memory and sets W=0.
FORCEINLINE VectorRegister4Double VectorLoadFloat3_W1 (const double *Ptr)
Loads 3 FLOATs from unaligned memory and sets W=1.
FORCEINLINE VectorRegister4Float VectorLoadSRGBA16N (void *Ptr)
Loads packed signed RGBA16(4 bytes) from unaligned memory and converts them into 4 FLOATs.
FORCEINLINE VectorRegister4Double VectorLoadTwoPairsFloat (const double *Ptr1, const double *Ptr2)
FORCEINLINE VectorRegister4Float VectorLoadTwoPairsFloat (const float *Ptr1, const float *Ptr2)
Loads 4 unaligned floats - 2 from the first pointer, 2 from the second, and packs them in to 1 vector.
FORCEINLINE VectorRegister4Float VectorLoadURGB10A2N (void *Ptr)
Loads packed RGB10A2(4 bytes) from unaligned memory and converts them into 4 FLOATs.
FORCEINLINE VectorRegister4Float VectorLoadURGBA16N (void *Ptr)
Loads packed RGBA16(4 bytes) from unaligned memory and converts them into 4 FLOATs.
FORCEINLINE VectorRegister4Double VectorLog (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorLog (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorLog2 (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorLog2 (const VectorRegister4Float &Vec)
FORCEINLINE int32 VectorMaskBits (const VectorRegister4Double &Vec1)
FORCEINLINE int32 VectorMaskBits (const VectorRegister4Float &Vec1)
Returns an integer bit-mask (0x00 - 0x0f) based on the sign-bit for each component in a vector.
FORCEINLINE bool VectorMatrixInverse (FMatrix44d *DstMatrix, const FMatrix44d *SrcMatrix)
Calculate the inverse of an FMatrix44.
FORCEINLINE bool VectorMatrixInverse (FMatrix44f *DstMatrix, const FMatrix44f *SrcMatrix)
FORCEINLINE void VectorMatrixMultiply (FMatrix44d *Result, const FMatrix44d *Matrix1, const FMatrix44d *Matrix2)
Multiplies two 4x4 matrices.
FORCEINLINE void VectorMatrixMultiply (FMatrix44f *Result, const FMatrix44f *Matrix1, const FMatrix44f *Matrix2)
FORCEINLINE VectorRegister4Double VectorMax (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorMax (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Returns the maximum values of two vectors (component-wise).
FORCEINLINE VectorRegister4Double VectorMergeVecXYZ_VecW (const VectorRegister4Double &VecXYZ, const VectorRegister4Double &VecW)
FORCEINLINE VectorRegister4Float VectorMergeVecXYZ_VecW (const VectorRegister4Float &VecXYZ, const VectorRegister4Float &VecW)
Merges the XYZ components of one vector with the W component of another vector and returns the result.
FORCEINLINE VectorRegister4Double VectorMin (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorMin (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Returns the minimum values of two vectors (component-wise).
FORCEINLINE VectorRegister4Double VectorMod (const VectorRegister4Double &X, const VectorRegister4Double &Y)
FORCEINLINE VectorRegister4Float VectorMod (const VectorRegister4Float &X, const VectorRegister4Float &Y)
FORCEINLINE VectorRegister4Double VectorMultiply (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorMultiply (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Multiplies two vectors (component-wise) and returns the result.
FORCEINLINE VectorRegister4Double VectorMultiplyAdd (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2, const VectorRegister4Double &Vec3)
FORCEINLINE VectorRegister4Float VectorMultiplyAdd (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2, const VectorRegister4Float &Vec3)
Multiplies two vectors (component-wise), adds in the third vector and returns the result.
FORCEINLINE VectorRegister4Double VectorNegate (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorNegate (const VectorRegister4Float &Vec)
Returns the negated value (component-wise).
FORCEINLINE VectorRegister4Double VectorNegateMultiplyAdd (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2, const VectorRegister4Double &Vec3)
FORCEINLINE VectorRegister4Float VectorNegateMultiplyAdd (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2, const VectorRegister4Float &Vec3)
Multiplies two vectors (component-wise), negates the results and adds it to the third vector i.e.
FORCEINLINE VectorRegister4Double VectorOneDouble (void)
FORCEINLINE VectorRegister4Float VectorOneFloat (void)
Returns a vector with all ones.
FORCEINLINE VectorRegister4Double VectorPow (const VectorRegister4Double &Base, const VectorRegister4Double &Exponent)
FORCEINLINE VectorRegister4Float VectorPow (const VectorRegister4Float &Base, const VectorRegister4Float &Exponent)
Calculates x raised to the power of y (component-wise).
FORCEINLINE void VectorQuaternionMultiply (VectorRegister4Double *RESTRICT Result, const VectorRegister4Double *RESTRICT Quat1, const VectorRegister4Double *RESTRICT Quat2)
FORCEINLINE void VectorQuaternionMultiply (VectorRegister4Float *RESTRICT Result, const VectorRegister4Float *RESTRICT Quat1, const VectorRegister4Float *RESTRICT Quat2)
Multiplies two quaternions; the order matters.
FORCEINLINE VectorRegister4Double VectorQuaternionMultiply2 (const VectorRegister4Double &Quat1, const VectorRegister4Double &Quat2)
FORCEINLINE VectorRegister4Float VectorQuaternionMultiply2 (const VectorRegister4Float &Quat1, const VectorRegister4Float &Quat2)
Multiplies two quaternions; the order matters.
FORCEINLINE VectorRegister4Double VectorReciprocal (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorReciprocal (const VectorRegister4Float &Vec)
Computes the reciprocal of a vector (component-wise) and returns the result.
FORCEINLINE VectorRegister4Double VectorReciprocalEstimate (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorReciprocalEstimate (const VectorRegister4Float &Vec)
Computes an estimate of the reciprocal of a vector (component-wise) and returns the result.
FORCEINLINE VectorRegister4Double VectorReciprocalLen (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorReciprocalLen (const VectorRegister4Float &Vec)
Return Reciprocal Length of the vector.
FORCEINLINE VectorRegister4Double VectorReciprocalLenEstimate (const VectorRegister4Double &Vector)
FORCEINLINE VectorRegister4Float VectorReciprocalLenEstimate (const VectorRegister4Float &Vector)
Return Reciprocal Length of the vector (estimate)
FORCEINLINE VectorRegister4Double VectorReciprocalSqrt (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorReciprocalSqrt (const VectorRegister4Float &Vec)
Returns an estimate of 1/sqrt(c) for each component of the vector.
FORCEINLINE VectorRegister4Double VectorReciprocalSqrtEstimate (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorReciprocalSqrtEstimate (const VectorRegister4Float &Vec)
Returns an estimate of 1/sqrt(c) for each component of the vector.
FORCEINLINE VectorRegister4Double VectorRound (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorRound (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Int VectorRoundToIntHalfToEven (const VectorRegister4Float &A)
FORCEINLINE VectorRegister4Double VectorSelect (const VectorRegister4Double &Mask, const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorSelect (const VectorRegister4Float &Mask, const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Does a bitwise vector selection based on a mask (e.g., created from VectorCompareXX)
FORCEINLINE VectorRegister4Double VectorSet_W0 (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorSet_W0 (const VectorRegister4Float &Vec)
Loads XYZ and sets W=0.
FORCEINLINE VectorRegister4Double VectorSet_W1 (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorSet_W1 (const VectorRegister4Float &Vec)
Loads XYZ and sets W=1.
FORCEINLINE VectorRegister4Double VectorSetFloat1 (double D)
FORCEINLINE VectorRegister4Float VectorSetFloat1 (float F)
Propagates passed in float to all registers.
FORCEINLINE VectorRegister4Int VectorShuffleByte4 (const VectorRegister4Int &Vec, const VectorRegister4Int &Mask)
FORCEINLINE VectorRegister4Double VectorSign (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorSign (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorSin (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorSin (const VectorRegister4Float &Vec)
FORCEINLINE void VectorSinCos (VectorRegister4Double *RESTRICT VSinAngles, VectorRegister4Double *RESTRICT VCosAngles, const VectorRegister4Double *RESTRICT VAngles)
FORCEINLINE void VectorSinCos (VectorRegister4Float *RESTRICT VSinAngles, VectorRegister4Float *RESTRICT VCosAngles, const VectorRegister4Float *RESTRICT VAngles)
Computes the sine and cosine of each component of a Vector.
FORCEINLINE VectorRegister4Double VectorSqrt (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorSqrt (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorStep (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorStep (const VectorRegister4Float &Vec)
FORCEINLINE void VectorStore (const VectorRegister4Double &Vec, double *Dst)
FORCEINLINE void VectorStore (const VectorRegister4Float &Vec, float *Dst)
Stores a vector to memory (aligned or unaligned).
FORCEINLINE void VectorStore16 (const VectorRegister4x4Float &Vec, float *Dst)
Stores 4 vectors to memory (aligned or unaligned).
void VectorStoreAligned (const VectorRegister4Double &Vec, double *Dst)
void VectorStoreAligned (const VectorRegister4Float &Vec, float *Dst)
Stores a vector to aligned memory.
FORCEINLINE void VectorStoreAlignedStreamed (const VectorRegister4Double &Vec, double *Dst)
FORCEINLINE void VectorStoreAlignedStreamed (const VectorRegister4Float &Vec, float *Dst)
Performs non-temporal store of a vector to aligned memory without polluting the caches.
FORCEINLINE void VectorStoreByte4 (const VectorRegister4Float &Vec, void *Ptr)
Converts the 4 FLOATs in the vector to 4 BYTEs, clamped to [0,255], and stores to unaligned memory.
FORCEINLINE void VectorStoreFloat1 (const VectorRegister4Double &Vec, double *Dst)
FORCEINLINE void VectorStoreFloat1 (const VectorRegister4Float &Vec, float *Dst)
Stores the X component of a vector to unaligned memory.
FORCEINLINE void VectorStoreFloat3 (const VectorRegister4Double &Vec, double *Dst)
FORCEINLINE void VectorStoreFloat3 (const VectorRegister4Float &Vec, float *Dst)
Stores the XYZ components of a vector to unaligned memory.
FORCEINLINE void VectorStoreSignedByte4 (const VectorRegister4Float &Vec, void *Ptr)
Converts the 4 FLOATs in the vector to 4 BYTEs, clamped to [-127,127], and stores to unaligned memory.
FORCEINLINE void VectorStoreURGB10A2N (const VectorRegister4Float &Vec, void *Ptr)
Converts the 4 FLOATs in the vector RGB10A2, clamped to [0, 1023] and [0, 3], and stores to unaligned memory.
FORCEINLINE void VectorStoreURGBA16N (const VectorRegister4Float &Vec, void *Ptr)
Converts the 4 FLOATs in the vector RGBA16, clamped to [0, 65535], and stores to unaligned memory.
FORCEINLINE VectorRegister4Double VectorSubtract (const VectorRegister4Double &Vec1, const VectorRegister4Double &Vec2)
FORCEINLINE VectorRegister4Float VectorSubtract (const VectorRegister4Float &Vec1, const VectorRegister4Float &Vec2)
Subtracts a vector from another (component-wise) and returns the result.
FORCEINLINE VectorRegister4Double VectorTan (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorTan (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorTransformVector (const VectorRegister4Double &VecP, const FMatrix44d *MatrixM)
FORCEINLINE VectorRegister4Double VectorTransformVector (const VectorRegister4Double &VecP, const FMatrix44f *MatrixM)
FORCEINLINE VectorRegister4Float VectorTransformVector (const VectorRegister4Float &VecP, const FMatrix44d *MatrixM)
FORCEINLINE VectorRegister4Float VectorTransformVector (const VectorRegister4Float &VecP, const FMatrix44f *MatrixM)
Calculate Homogeneous transform.
FORCEINLINE VectorRegister4Double VectorTruncate (const VectorRegister4Double &Vec)
FORCEINLINE VectorRegister4Float VectorTruncate (const VectorRegister4Float &Vec)
FORCEINLINE VectorRegister4Double VectorZeroDouble (void)
FORCEINLINE VectorRegister4Float VectorZeroFloat (void)
Returns a vector with all zeros.
Macro Definition Documentation
DECLARE_VECTOR_REGISTER
#define DECLARE_VECTOR_REGISTER (X, Y, Z, W)
Value:
MakeVectorRegister(X, Y, Z, W)
Definition at line 155 of file UnrealMathFPU.h.
USE_FAST_QUAT_MUL
#define USE_FAST_QUAT_MUL 1
Definition at line 1419 of file UnrealMathFPU.h.
VECTOR_DENORMALS_FLUSH_TO_ZERO
#define VECTOR_DENORMALS_FLUSH_TO_ZERO 0
Denormal operands and results will be flushed to zero.
Definition at line 1957 of file UnrealMathFPU.h.
Referenced by FScopedFTZFloatMode::FScopedFTZFloatMode().
VECTOR_ROUND_TOWARD_ZERO
#define VECTOR_ROUND_TOWARD_ZERO 0
Control status bit to round all floating point math results towards zero.
Definition at line 1952 of file UnrealMathFPU.h.
VectorCastDoubleToInt
#define VectorCastDoubleToInt (Vec)
Value:
VectorInt64Load(Vec.V)
Definition at line 2655 of file UnrealMathFPU.h.
VectorCastFloatToInt
#define VectorCastFloatToInt (Vec)
Value:
VectorIntLoad(Vec.V)
Definition at line 2654 of file UnrealMathFPU.h.
VectorCastIntToDouble
#define VectorCastIntToDouble (Vec)
Value:
VectorDoubleLoad(Vec.V)
Definition at line 2656 of file UnrealMathFPU.h.
VectorCastIntToFloat
#define VectorCastIntToFloat (Vec)
Value:
VectorLoad((float*)(Vec.V))
Definition at line 2653 of file UnrealMathFPU.h.
VectorGetComponent
#define VectorGetComponent (Vec, ComponentIndex)
Value:
VectorGetComponentImpl<ComponentIndex>(Vec)
Definition at line 385 of file UnrealMathFPU.h.
Referenced by UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
VectorGetControlRegister
#define VectorGetControlRegister ()
Value:
0
Returns the control register.
Returns
The uint32 control register
Definition at line 1940 of file UnrealMathFPU.h.
Referenced by FScopedFTZFloatMode::FScopedFTZFloatMode().
VectorIntExpandLow16To32
#define VectorIntExpandLow16To32 (V0)
Value:
static_assert(false, "Unimplemented")
Definition at line 2661 of file UnrealMathFPU.h.
VectorIntSet1
#define VectorIntSet1 (F)
Value:
MakeVectorRegisterInt(F, F, F, F)
Definition at line 2652 of file UnrealMathFPU.h.
VectorIntSign
#define VectorIntSign (A)
Value:
VectorIntSelect(VectorIntCompareGE(A, GlobalVectorConstants::IntZero), GlobalVectorConstants::IntOne, GlobalVectorConstants::IntMinusOne)
Definition at line 2480 of file UnrealMathFPU.h.
VectorLoadByte4
#define VectorLoadByte4 (Ptr)
Value:
MakeVectorRegisterFloat(float(((const uint8*)(Ptr))[0]), float(((const uint8*)(Ptr))[1]), float(((const uint8*)(Ptr))[2]), float(((const uint8*)(Ptr))[3]))
Loads 4 BYTEs from unaligned memory and converts them into 4 FLOATs.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Ptr Unaligned memory pointer to the 4 BYTEs.
Returns
VectorRegister(float(Ptr[0]), float(Ptr[1]), float(Ptr[2]), float(Ptr[3]))
Definition at line 1814 of file UnrealMathFPU.h.
Referenced by FDeprecatedSerializedPackedNormal::operator FVector3f(), and FDeprecatedSerializedPackedNormal::operator FVector4f().
VectorLoadByte4Reverse
#define VectorLoadByte4Reverse (Ptr)
Value:
MakeVectorRegisterFloat(float(((const uint8*)(Ptr))[3]), float(((const uint8*)(Ptr))[2]), float(((const uint8*)(Ptr))[1]), float(((const uint8*)(Ptr))[0]))
Loads 4 BYTEs from unaligned memory and converts them into 4 FLOATs in reversed order.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Ptr Unaligned memory pointer to the 4 BYTEs.
Returns
VectorRegister(float(Ptr[3]), float(Ptr[2]), float(Ptr[1]), float(Ptr[0]))
Definition at line 1833 of file UnrealMathFPU.h.
VectorLoadSignedByte4
#define VectorLoadSignedByte4 (Ptr)
Value:
MakeVectorRegisterFloat(float(((const int8*)(Ptr))[0]), float(((const int8*)(Ptr))[1]), float(((const int8*)(Ptr))[2]), float(((const int8*)(Ptr))[3]))
Loads 4 signed BYTEs from unaligned memory and converts them into 4 FLOATs.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Ptr Unaligned memory pointer to the 4 BYTEs.
Returns
VectorRegister(float(Ptr[0]), float(Ptr[1]), float(Ptr[2]), float(Ptr[3]))
Definition at line 1823 of file UnrealMathFPU.h.
Referenced by FPackedNormal::GetVectorRegister().
VectorOneVectorRegister
#define VectorOneVectorRegister ()
Value:
VectorOneDouble()
Definition at line 152 of file UnrealMathFPU.h.
VectorReplicate
#define VectorReplicate (Vec, ElementIndex)
Value:
MakeVectorRegister((Vec).V[ElementIndex], (Vec).V[ElementIndex], (Vec).V[ElementIndex], (Vec).V[ElementIndex])
Replicates one element into all four elements and returns the new vector.
Parameters
Vec Source vector
ElementIndex Index (0-3) of the element to replicate
Returns
VectorRegister(Vec[ElementIndex], Vec[ElementIndex], Vec[ElementIndex], Vec[ElementIndex])
Definition at line 627 of file UnrealMathFPU.h.
Referenced by appLineCheckTriangleSOA(), UE::Math::TBox< T >::TransformBy(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
VectorResetFloatRegisters
#define VectorResetFloatRegisters ()
Resets the floating point registers so that they can be used again.
Some intrinsics use these for MMX purposes (e.g. VectorLoadByte4 and VectorStoreByte4).
Definition at line 1933 of file UnrealMathFPU.h.
Referenced by FPackedRGB10A2N::GetVectorRegister().
VectorSet1
#define VectorSet1 (F)
Value:
VectorSetFloat1(F)
Definition at line 2651 of file UnrealMathFPU.h.
VectorSetControlRegister
#define VectorSetControlRegister (ControlStatus)
Sets the control register.
Parameters
ControlStatus The uint32 control status value to set
Definition at line 1947 of file UnrealMathFPU.h.
Referenced by FScopedFTZFloatMode::FScopedFTZFloatMode(), and FScopedFTZFloatMode::~FScopedFTZFloatMode().
VectorSetZero
#define VectorSetZero ()
Value:
MakeVectorRegisterFloat(0.f, 0.f, 0.f, 0.f)
Definition at line 2650 of file UnrealMathFPU.h.
VectorShiftLeftImm
#define VectorShiftLeftImm (Vec, ImmAmt)
Value:
static_assert(false, "Unimplemented")
Definition at line 2658 of file UnrealMathFPU.h.
VectorShiftRightImmArithmetic
#define VectorShiftRightImmArithmetic (Vec, ImmAmt)
Value:
static_assert(false, "Unimplemented")
Definition at line 2659 of file UnrealMathFPU.h.
VectorShiftRightImmLogical
#define VectorShiftRightImmLogical (Vec, ImmAmt)
Value:
static_assert(false, "Unimplemented")
Definition at line 2660 of file UnrealMathFPU.h.
VectorShuffle
#define VectorShuffle (Vec1, Vec2, X, Y, Z, W)
Value:
MakeVectorRegister((Vec1).V[X], (Vec1).V[Y], (Vec2).V[Z], (Vec2).V[W])
Creates a vector through selecting two components from each vector via a shuffle mask.
Parameters
Vec1 Source vector1
Vec2 Source vector2
X Index for which component of Vector1 to use for X (literal 0-3)
Y Index for which component to Vector1 to use for Y (literal 0-3)
Z Index for which component to Vector2 to use for Z (literal 0-3)
W Index for which component to Vector2 to use for W (literal 0-3)
Returns
The swizzled vector
Definition at line 652 of file UnrealMathFPU.h.
Referenced by VectorCombineHigh(), VectorCombineHigh(), VectorCombineLow(), and VectorCombineLow().
VectorShuffleImmediate
#define VectorShuffleImmediate (Vec, I0, I1, I2, I3)
Value:
VectorShuffle(Vec, Vec, I3, I2, I1, I0)
Definition at line 2657 of file UnrealMathFPU.h.
VectorSwizzle
#define VectorSwizzle (Vec, X, Y, Z, W)
Value:
MakeVectorRegister((Vec).V[X], (Vec).V[Y], (Vec).V[Z], (Vec).V[W])
Swizzles the 4 components of a vector and returns the result.
Parameters
Vec Source vector
X Index for which component to use for X (literal 0-3)
Y Index for which component to use for Y (literal 0-3)
Z Index for which component to use for Z (literal 0-3)
W Index for which component to use for W (literal 0-3)
Returns
The swizzled vector
Definition at line 639 of file UnrealMathFPU.h.
Referenced by appLineCheckTriangleSOA().
VectorZeroVectorRegister
#define VectorZeroVectorRegister ()
Value:
VectorZeroDouble()
Definition at line 151 of file UnrealMathFPU.h.
Typedef Documentation
AlignedRegister4
typedef AlignedDouble4 AlignedRegister4
Definition at line 150 of file UnrealMathFPU.h.
VectorRegister
typedef VectorRegister4 VectorRegister
Definition at line 95 of file UnrealMathFPU.h.
VectorRegister2d
typedef VectorRegister2Double VectorRegister2d
Definition at line 91 of file UnrealMathFPU.h.
VectorRegister4
typedef VectorRegister4Double VectorRegister4
Definition at line 94 of file UnrealMathFPU.h.
VectorRegister4d
typedef VectorRegister4Double VectorRegister4d
Definition at line 90 of file UnrealMathFPU.h.
VectorRegister4f
typedef VectorRegister4Float VectorRegister4f
Definition at line 89 of file UnrealMathFPU.h.
VectorRegister4i
typedef VectorRegister4Int VectorRegister4i
Definition at line 88 of file UnrealMathFPU.h.
VectorRegisterInt
typedef VectorRegister4Int VectorRegisterInt
Definition at line 96 of file UnrealMathFPU.h.
Function Documentation
MakeVectorRegister() [1/3]
FORCEINLINE VectorRegister4Double MakeVectorRegister (double X, double Y, double Z, double W)
Definition at line 250 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), X, Y, and Z.
MakeVectorRegister() [2/3]
FORCEINLINE VectorRegister4Float MakeVectorRegister (float X, float Y, float Z, float W)
Definition at line 245 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), X, Y, and Z.
MakeVectorRegister() [3/3]
FORCEINLINE VectorRegister4Float MakeVectorRegister (uint32 X, uint32 Y, uint32 Z, uint32 W)
Definition at line 195 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), X, Y, and Z.
Referenced by UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildOffsetVec(), FPackedRGB10A2N::GetVectorRegister(), VectorDeinterleave(), VectorDeinterleave(), VectorLoadTwoPairsFloat(), and VectorLoadTwoPairsFloat().
MakeVectorRegister2Double()
FORCEINLINE VectorRegister2Double MakeVectorRegister2Double (double X, double Y)
Definition at line 158 of file UnrealMathFPU.h.
References FORCEINLINE, X, and Y.
Referenced by VectorDoubleLoad().
MakeVectorRegister2DoubleConstant()
FORCEINLINE constexpr VectorRegister2Double MakeVectorRegister2DoubleConstant (double X, double Y) constexpr
Definition at line 302 of file UnrealMathFPU.h.
References FORCEINLINE, X, and Y.
MakeVectorRegisterDouble() [1/4]
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (const VectorRegister2Double & XY, const VectorRegister2Double & ZW)
Definition at line 240 of file UnrealMathFPU.h.
References FORCEINLINE.
MakeVectorRegisterDouble() [2/4]
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (const VectorRegister4Float & From)
Definition at line 256 of file UnrealMathFPU.h.
References FORCEINLINE.
MakeVectorRegisterDouble() [3/4]
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (double X, double Y, double Z, double W)
Definition at line 230 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Double::V, X, Y, and Z.
MakeVectorRegisterDouble() [4/4]
FORCEINLINE VectorRegister4Double MakeVectorRegisterDouble (uint64 X, uint64 Y, uint64 Z, uint64 W)
Definition at line 185 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Double::V, X, Y, and Z.
Referenced by MakeVectorRegister(), MakeVectorRegisterDoubleMask(), VectorACos(), VectorASin(), VectorATan(), VectorATan2(), VectorBitwiseAnd(), VectorBitwiseOr(), VectorBitwiseXor(), VectorCeil(), VectorCompareEQ(), VectorCompareGE(), VectorCompareGT(), VectorCompareLE(), VectorCompareLT(), VectorCompareNE(), VectorCos(), VectorDot3(), VectorDot4(), VectorExp(), VectorExp2(), VectorFloor(), VectorLoad(), VectorLoadDouble1(), VectorLoadFloat2(), VectorLoadFloat3(), VectorLoadFloat3_W1(), VectorLog(), VectorLog2(), VectorMergeVecXYZ_VecW(), VectorMod(), VectorNegate(), VectorReciprocalSqrt(), VectorReciprocalSqrtEstimate(), VectorRound(), VectorSelect(), VectorSet_W0(), VectorSet_W1(), VectorSetFloat1(), VectorSign(), VectorSin(), VectorSqrt(), VectorStep(), VectorTan(), VectorTransformVector(), and VectorTruncate().
MakeVectorRegisterDoubleMask()
FORCEINLINE VectorRegister4Double MakeVectorRegisterDoubleMask (uint64 X, uint64 Y, uint64 Z, uint64 W)
Definition at line 206 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), X, Y, and Z.
MakeVectorRegisterFloat() [1/2]
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloat (float X, float Y, float Z, float W)
Returns a vector based on 4 FLOATs.
Parameters
X 1st float component
Y 2nd float component
Z 3rd float component
W 4th float component
Returns
Vector of the 4 FLOATs
Definition at line 220 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Float::V, X, Y, and Z.
MakeVectorRegisterFloat() [2/2]
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloat (uint32 X, uint32 Y, uint32 Z, uint32 W)
Returns a bitwise equivalent vector based on 4 DWORDs.
Parameters
X 1st uint32 component
Y 2nd uint32 component
Z 3rd uint32 component
W 4th uint32 component
Returns
Bitwise equivalent vector with 4 floats
Definition at line 175 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Float::V, X, Y, and Z.
Referenced by TAudioBuffer< float >::_MultiplyAccumulateSIMD(), MakeVectorRegister(), MakeVectorRegister(), MakeVectorRegisterFloatMask(), FRenderTransform::To3x4MatrixTranspose(), FRenderTransform::ToMatrix44f(), VectorACos(), VectorASin(), VectorATan(), VectorATan2(), VectorBitwiseAnd(), VectorBitwiseOr(), VectorBitwiseXor(), VectorCeil(), VectorCompareEQ(), VectorCompareGE(), VectorCompareGT(), VectorCompareLE(), VectorCompareLT(), VectorCompareNE(), VectorCos(), VectorDot3(), VectorDot4(), VectorExp(), VectorExp2(), VectorFloor(), VectorIntToFloat(), VectorLoad(), VectorLoadFloat1(), VectorLoadFloat2(), VectorLoadSRGBA16N(), VectorLoadURGB10A2N(), VectorLoadURGBA16N(), VectorLog(), VectorLog2(), VectorMergeVecXYZ_VecW(), VectorMod(), VectorNegate(), VectorReciprocalSqrt(), VectorReciprocalSqrtEstimate(), VectorRound(), VectorSelect(), VectorSet_W0(), VectorSet_W1(), VectorSetFloat1(), VectorSign(), VectorSin(), VectorSqrt(), VectorStep(), VectorStoreURGB10A2N(), VectorStoreURGBA16N(), VectorTan(), and VectorTruncate().
MakeVectorRegisterFloatConstant()
FORCEINLINE constexpr VectorRegister4Float MakeVectorRegisterFloatConstant (float X, float Y, float Z, float W) constexpr
Definition at line 297 of file UnrealMathFPU.h.
References FORCEINLINE, X, Y, and Z.
MakeVectorRegisterFloatFromDouble()
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloatFromDouble (const VectorRegister4Double & Vec4d)
Definition at line 262 of file UnrealMathFPU.h.
References float, FORCEINLINE, VectorRegister4Double::V, and VectorRegister4Float::V.
Referenced by UE::Math::TMatrix< double >::TMatrix(), and VectorTransformVector().
MakeVectorRegisterFloatMask()
FORCEINLINE VectorRegister4Float MakeVectorRegisterFloatMask (uint32 X, uint32 Y, uint32 Z, uint32 W)
Definition at line 201 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), X, Y, and Z.
MakeVectorRegisterInt()
FORCEINLINE VectorRegister4Int MakeVectorRegisterInt (int32 X, int32 Y, int32 Z, int32 W)
Returns a vector based on 4 int32.
Parameters
X 1st int32 component
Y 2nd int32 component
Z 3rd int32 component
W 4th int32 component
Returns
Vector of the 4 int32
Definition at line 282 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Int::V, X, Y, and Z.
Referenced by VectorFloatToInt(), VectorFloatToInt(), VectorIntAbs(), VectorIntAdd(), VectorIntAnd(), VectorIntAndNot(), VectorIntCompareEQ(), VectorIntCompareGE(), VectorIntCompareGT(), VectorIntCompareLE(), VectorIntCompareLT(), VectorIntCompareNEQ(), VectorIntLoad(), VectorIntLoad1(), VectorIntLoadAligned(), VectorIntMax(), VectorIntMin(), VectorIntMultiply(), VectorIntNegate(), VectorIntNot(), VectorIntOr(), VectorIntSubtract(), VectorIntXor(), and VectorRoundToIntHalfToEven().
MakeVectorRegisterInt64()
FORCEINLINE VectorRegister4Int MakeVectorRegisterInt64 (int64 X, int64 Y)
Definition at line 307 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Int::V, X, and Y.
Referenced by VectorInt64Load().
MakeVectorRegisterIntConstant()
FORCEINLINE constexpr VectorRegister4Int MakeVectorRegisterIntConstant (int32 X, int32 Y, int32 Z, int32 W) constexpr
Definition at line 292 of file UnrealMathFPU.h.
References FORCEINLINE, X, Y, and Z.
VectorAbs() [1/2]
FORCEINLINE VectorRegister4Double VectorAbs (const VectorRegister4Double & Vec)
Definition at line 671 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorAbs() [2/2]
FORCEINLINE VectorRegister4Float VectorAbs (const VectorRegister4Float & Vec)
Returns the absolute value (component-wise).
Parameters
Vec Source vector
Returns
VectorRegister(abs(Vec.x), abs(Vec.y), abs(Vec.z), abs(Vec.w))
Definition at line 661 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by UE::Math::TQuat< T >::Equals(), UE::Math::TRotator< T >::Equals(), FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, UE::Math::TRotator< T >::IsNearlyZero(), UE::Math::TQuat< T >::IsNormalized(), UE::Math::TBox< T >::TransformBy(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
VectorACos() [1/2]
FORCEINLINE VectorRegister4Double VectorACos (const VectorRegister4Double & Vec)
Definition at line 2066 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorACos() [2/2]
FORCEINLINE VectorRegister4Float VectorACos (const VectorRegister4Float & Vec)
Definition at line 2061 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorAdd() [1/2]
FORCEINLINE VectorRegister4Double VectorAdd (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 714 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorAdd() [2/2]
FORCEINLINE VectorRegister4Float VectorAdd (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Adds two vectors (component-wise) and returns the result.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x+Vec2.x, Vec1.y+Vec2.y, Vec1.z+Vec2.z, Vec1.w+Vec2.w)
Definition at line 704 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by TAudioBuffer< float >::_AccumulateSIMD(), TAudioBuffer< float >::_MultiplyAccumulateSIMD(), FGainMatrix::ApplyAndAccumulateToBuffer(), UE::Math::TQuat< T >::Equals(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FGainMatrix::Lerp(), UE::Math::TQuat< T >::operator+(), UE::Math::TQuat< T >::operator+=(), Harmonix::Dsp::Effects::FFourBiquads::Process(), Harmonix::Dsp::Effects::FFourBiquads::Process(), Harmonix::Dsp::Effects::FFourBiquads::ProcessOne(), UE::Math::TBox< T >::TransformBy(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
VectorAnyGreaterThan() [1/2]
FORCEINLINE uint32 VectorAnyGreaterThan (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1923 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorAnyGreaterThan() [2/2]
FORCEINLINE uint32 VectorAnyGreaterThan (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Returns non-zero if any element in Vec1 is greater than the corresponding element in Vec2, otherwise 0.
Parameters
Vec1 1st source vector
Vec2 2nd source vector
Returns
Non-zero integer if (Vec1.x > Vec2.x) || (Vec1.y > Vec2.y) || (Vec1.z > Vec2.z) || (Vec1.w > Vec2.w)
Definition at line 1917 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by UE::Math::TQuat< T >::Equals(), UE::Math::TRotator< T >::Equals(), FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, TBounds< float >::Intersect(), UE::Math::TRotator< T >::IsNearlyZero(), and UE::Math::TQuat< T >::IsNormalized().
VectorASin() [1/2]
FORCEINLINE VectorRegister4Double VectorASin (const VectorRegister4Double & Vec)
Definition at line 2055 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorASin() [2/2]
FORCEINLINE VectorRegister4Float VectorASin (const VectorRegister4Float & Vec)
Definition at line 2050 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorATan() [1/2]
FORCEINLINE VectorRegister4Double VectorATan (const VectorRegister4Double & Vec)
Definition at line 2077 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorATan() [2/2]
FORCEINLINE VectorRegister4Float VectorATan (const VectorRegister4Float & Vec)
Definition at line 2072 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorATan2() [1/2]
FORCEINLINE VectorRegister4Double VectorATan2 (const VectorRegister4Double & Y, const VectorRegister4Double & X)
Definition at line 2092 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), X, and Y.
VectorATan2() [2/2]
FORCEINLINE VectorRegister4Float VectorATan2 (const VectorRegister4Float & Y, const VectorRegister4Float & X)
Definition at line 2083 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), X, and Y.
VectorBitwiseAnd() [1/2]
FORCEINLINE VectorRegister4Double VectorBitwiseAnd (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1174 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorBitwiseAnd() [2/2]
FORCEINLINE VectorRegister4Float VectorBitwiseAnd (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Combines two vectors using bitwise AND (treating each vector as a 128 bit field)
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(for each bit i: Vec1[i] & Vec2[i])
Definition at line 1165 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by appLineCheckTriangleSOA(), and TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds().
VectorBitwiseOr() [1/2]
FORCEINLINE VectorRegister4Double VectorBitwiseOr (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1149 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorBitwiseOr() [2/2]
FORCEINLINE VectorRegister4Float VectorBitwiseOr (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Combines two vectors using bitwise OR (treating each vector as a 128 bit field)
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(for each bit i: Vec1[i] | Vec2[i])
Definition at line 1140 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorBitwiseXor() [1/2]
FORCEINLINE VectorRegister4Double VectorBitwiseXor (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1199 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorBitwiseXor() [2/2]
FORCEINLINE VectorRegister4Float VectorBitwiseXor (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Combines two vectors using bitwise XOR (treating each vector as a 128 bit field)
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(for each bit i: Vec1[i] ^ Vec2[i])
Definition at line 1190 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorCeil() [1/2]
FORCEINLINE VectorRegister4Double VectorCeil (const VectorRegister4Double & Vec)
Definition at line 2136 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCeil() [2/2]
FORCEINLINE VectorRegister4Float VectorCeil (const VectorRegister4Float & Vec)
Definition at line 2131 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorCombineHigh() [1/2]
FORCEINLINE VectorRegister4Double VectorCombineHigh (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1745 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorShuffle.
VectorCombineHigh() [2/2]
FORCEINLINE VectorRegister4Float VectorCombineHigh (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a vector by combining two high components from each vector.
Parameters
Vec1 Source vector1
Vec2 Source vector2
Returns
The combined vector
Definition at line 1740 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorShuffle.
Referenced by FRenderTransform::To3x4MatrixTranspose().
VectorCombineLow() [1/2]
FORCEINLINE VectorRegister4Double VectorCombineLow (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1762 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorShuffle.
VectorCombineLow() [2/2]
FORCEINLINE VectorRegister4Float VectorCombineLow (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a vector by combining two low components from each vector.
Parameters
Vec1 Source vector1
Vec2 Source vector2
Returns
The combined vector
Definition at line 1757 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorShuffle.
Referenced by FRenderTransform::To3x4MatrixTranspose().
VectorCompareEQ() [1/2]
FORCEINLINE VectorRegister4Double VectorCompareEQ (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 932 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCompareEQ() [2/2]
FORCEINLINE VectorRegister4Float VectorCompareEQ (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a four-part mask based on component-wise == compares of the input vectors.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x == Vec2.x ? 0xFFFFFFFF : 0, same for yzw)
Definition at line 923 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by UE::Math::TQuat< T >::operator==().
VectorCompareGE() [1/2]
FORCEINLINE VectorRegister4Double VectorCompareGE (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1009 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCompareGE() [2/2]
FORCEINLINE VectorRegister4Float VectorCompareGE (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a four-part mask based on component-wise >= compares of the input vectors.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x >= Vec2.x ? 0xFFFFFFFF : 0, same for yzw)
Definition at line 1000 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by TBounds< float >::Contains(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), and UE::Math::TQuat< T >::Normalize().
VectorCompareGT() [1/2]
FORCEINLINE VectorRegister4Double VectorCompareGT (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 983 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCompareGT() [2/2]
FORCEINLINE VectorRegister4Float VectorCompareGT (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a four-part mask based on component-wise > compares of the input vectors.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x > Vec2.x ? 0xFFFFFFFF : 0, same for yzw)
Definition at line 974 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds().
VectorCompareLE() [1/2]
FORCEINLINE VectorRegister4Double VectorCompareLE (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1059 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCompareLE() [2/2]
FORCEINLINE VectorRegister4Float VectorCompareLE (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a four-part mask based on component-wise <= compares of the input vectors.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x <= Vec2.x ? 0xFFFFFFFF : 0, same for yzw)
Definition at line 1050 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by TBounds< float >::Contains().
VectorCompareLT() [1/2]
FORCEINLINE VectorRegister4Double VectorCompareLT (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1034 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCompareLT() [2/2]
FORCEINLINE VectorRegister4Float VectorCompareLT (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a four-part mask based on component-wise < compares of the input vectors.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x < Vec2.x ? 0xFFFFFFFF : 0, same for yzw)
Definition at line 1025 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorCompareNE() [1/2]
FORCEINLINE VectorRegister4Double VectorCompareNE (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 957 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCompareNE() [2/2]
FORCEINLINE VectorRegister4Float VectorCompareNE (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Creates a four-part mask based on component-wise != compares of the input vectors.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x != Vec2.x ? 0xFFFFFFFF : 0, same for yzw)
Definition at line 948 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by TAudioBuffer< float >::_SaturateSIMD(), and UE::Math::TQuat< T >::operator!=().
VectorContainsNaNOrInfinite() [1/2]
bool VectorContainsNaNOrInfinite (const VectorRegister4Double & Vec) inline
Definition at line 1965 of file UnrealMathFPU.h.
References VectorRegister4Double::V.
VectorContainsNaNOrInfinite() [2/2]
bool VectorContainsNaNOrInfinite (const VectorRegister4Float & Vec) inline
Definition at line 1960 of file UnrealMathFPU.h.
References VectorRegister4Float::V.
VectorCos() [1/2]
FORCEINLINE VectorRegister4Double VectorCos (const VectorRegister4Double & Vec)
Definition at line 2032 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorCos() [2/2]
FORCEINLINE VectorRegister4Float VectorCos (const VectorRegister4Float & Vec)
Definition at line 2027 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by VectorSinCos().
VectorCross() [1/2]
FORCEINLINE VectorRegister4Double VectorCross (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1226 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorCross() [2/2]
FORCEINLINE VectorRegister4Float VectorCross (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Calculates the cross product of two vectors (XYZ components).
W of the input should be 0, and will remain 0.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
cross(Vec1.xyz, Vec2.xyz). W of the input should be 0, and will remain 0.
Definition at line 1216 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
VectorDeinterleave() [1/2]
FORCEINLINE void VectorDeinterleave (VectorRegister4Double &RESTRICT OutEvens, VectorRegister4Double &RESTRICT OutOdds, const VectorRegister4Double &RESTRICT Lo, const VectorRegister4Double &RESTRICT Hi)
Definition at line 1783 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegister(), and RESTRICT.
VectorDeinterleave() [2/2]
FORCEINLINE void VectorDeinterleave (VectorRegister4Float &RESTRICT OutEvens, VectorRegister4Float &RESTRICT OutOdds, const VectorRegister4Float &RESTRICT Lo, const VectorRegister4Float &RESTRICT Hi)
Deinterleaves the components of the two given vectors such that the even components are in one vector and the odds in another.
Parameters
Lo [Even0, Odd0, Even1, Odd1]
Hi [Even2, Odd2, Even3, Odd3]
OutEvens [Even0, Even1, Even2, Even3]
OutOdds [Odd0, Odd1, Odd2, Odd3]
Definition at line 1777 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegister(), and RESTRICT.
Referenced by FRenderTransform::To3x4MatrixTranspose().
VectorDivide() [1/2]
FORCEINLINE VectorRegister4Double VectorDivide (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 844 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorDivide() [2/2]
FORCEINLINE VectorRegister4Float VectorDivide (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Divides two vectors (component-wise) and returns the result.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x/Vec2.x, Vec1.y/Vec2.y, Vec1.z/Vec2.z, Vec1.w/Vec2.w)
Definition at line 834 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by appLineCheckTriangleSOA(), UE::Math::TQuat< double >::operator/(), UE::Math::TQuat< double >::operator/=(), VectorReciprocal(), and VectorReciprocal().
VectorDot3() [1/2]
FORCEINLINE VectorRegister4Double VectorDot3 (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 887 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorDot3Scalar().
VectorDot3() [2/2]
FORCEINLINE VectorRegister4Float VectorDot3 (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Calculates the dot3 product of two vectors and returns a vector with the result in all 4 components.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
d = dot3(Vec1.xyz, Vec2.xyz), VectorRegister(d, d, d, d)
Definition at line 880 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorDot3Scalar().
VectorDot3Scalar() [1/2]
FORCEINLINE double VectorDot3Scalar (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 867 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorDot3Scalar() [2/2]
FORCEINLINE float VectorDot3Scalar (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Calculates the dot3 product of two vectors and returns a scalar value.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
d = dot3(Vec1.xyz, Vec2.xyz)
Definition at line 861 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by TBounds< float >::DistSqr(), UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy(), VectorDot3(), and VectorDot3().
VectorDot4() [1/2]
FORCEINLINE VectorRegister4Double VectorDot4 (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 908 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorDot4() [2/2]
FORCEINLINE VectorRegister4Float VectorDot4 (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Calculates the dot4 product of two vectors and returns a vector with the result in all 4 components.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
d = dot4(Vec1.xyzw, Vec2.xyzw), VectorRegister(d, d, d, d)
Definition at line 901 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by UE::Math::TQuat< T >::IsNormalized(), UE::Math::TQuat< T >::Normalize(), VectorReciprocalLen(), and VectorReciprocalLen().
VectorDoubleLoad()
FORCEINLINE VectorRegister2Double VectorDoubleLoad (const void * Ptr)
Loads 2 doubles from unaligned memory.
Parameters
Ptr Unaligned memory pointer to the 2 doubles
Returns
VectorRegister2Double(Ptr[0], Ptr[1])
Definition at line 2642 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegister2Double().
VectorDoubleToInt()
FORCEINLINE VectorRegister4Int VectorDoubleToInt (const VectorRegister4Double & A)
Definition at line 2510 of file UnrealMathFPU.h.
References A, FORCEINLINE, and VectorFloatToInt().
VectorExp() [1/2]
FORCEINLINE VectorRegister4Double VectorExp (const VectorRegister4Double & Vec)
Definition at line 1976 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorExp() [2/2]
FORCEINLINE VectorRegister4Float VectorExp (const VectorRegister4Float & Vec)
Definition at line 1971 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorExp2() [1/2]
FORCEINLINE VectorRegister4Double VectorExp2 (const VectorRegister4Double & Vec)
Definition at line 1987 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorExp2() [2/2]
FORCEINLINE VectorRegister4Float VectorExp2 (const VectorRegister4Float & Vec)
Definition at line 1982 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorFloatToInt() [1/2]
FORCEINLINE VectorRegister4Int VectorFloatToInt (const VectorRegister4Double & A)
Definition at line 2501 of file UnrealMathFPU.h.
References A, FORCEINLINE, and MakeVectorRegisterInt().
VectorFloatToInt() [2/2]
FORCEINLINE VectorRegister4Int VectorFloatToInt (const VectorRegister4Float & A)
Definition at line 2491 of file UnrealMathFPU.h.
References A, FORCEINLINE, and MakeVectorRegisterInt().
Referenced by VectorDoubleToInt().
VectorFloor() [1/2]
FORCEINLINE VectorRegister4Double VectorFloor (const VectorRegister4Double & Vec)
Definition at line 2147 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorFloor() [2/2]
FORCEINLINE VectorRegister4Float VectorFloor (const VectorRegister4Float & Vec)
Definition at line 2142 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorGetComponentDynamic() [1/2]
FORCEINLINE double VectorGetComponentDynamic (const VectorRegister4Double & Vec, uint32 ComponentIndex)
Definition at line 380 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorGetComponentDynamic() [2/2]
FORCEINLINE float VectorGetComponentDynamic (const VectorRegister4Float & Vec, uint32 ComponentIndex)
Definition at line 369 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckTriangles().
VectorGetComponentImpl() [1/2]
template<uint32 ComponentIndex> FORCEINLINE double VectorGetComponentImpl (const VectorRegister4Double & Vec)
Definition at line 375 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorGetComponentImpl() [2/2]
template<uint32 ComponentIndex> FORCEINLINE float VectorGetComponentImpl (const VectorRegister4Float & Vec)
Returns an component from a vector.
Parameters
Vec Vector register
ComponentIndex Which component to get, X=0, Y=1, Z=2, W=3
Returns
The component as a float
Definition at line 364 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
VectorInt64Load()
FORCEINLINE VectorRegister4Int VectorInt64Load (const void * Ptr)
Loads 2 int64s from unaligned memory.
Parameters
Ptr Unaligned memory pointer to the 2 int64s
Returns
VectorRegister4Int(Ptr[0], Ptr[1])
Definition at line 2627 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterInt64().
VectorIntAbs()
FORCEINLINE VectorRegister4Int VectorIntAbs (const VectorRegister4Int & A)
Definition at line 2471 of file UnrealMathFPU.h.
References A, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntAdd()
FORCEINLINE VectorRegister4Int VectorIntAdd (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2417 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntAnd()
FORCEINLINE VectorRegister4Int VectorIntAnd (const VectorRegister4Int & A, const VectorRegister4Int & B)
= a & b
Definition at line 2308 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
Referenced by FOctreeNodeContext::GetChildOffsetVec(), and VectorIntSelect().
VectorIntAndNot()
FORCEINLINE VectorRegister4Int VectorIntAndNot (const VectorRegister4Int & A, const VectorRegister4Int & B)
= (~a) & b to match _mm_andnot_si128
Definition at line 2337 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntCompareEQ()
FORCEINLINE VectorRegister4Int VectorIntCompareEQ (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2356 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
Referenced by FOctreeNodeContext::GetChildOffsetVec().
VectorIntCompareGE()
FORCEINLINE VectorRegister4Int VectorIntCompareGE (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2392 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntCompareGT()
FORCEINLINE VectorRegister4Int VectorIntCompareGT (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2374 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntCompareLE()
FORCEINLINE VectorRegister4Int VectorIntCompareLE (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2401 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntCompareLT()
FORCEINLINE VectorRegister4Int VectorIntCompareLT (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2383 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntCompareNEQ()
FORCEINLINE VectorRegister4Int VectorIntCompareNEQ (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2365 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntLoad()
FORCEINLINE VectorRegister4Int VectorIntLoad (const void * Ptr)
Loads 4 int32s from unaligned memory.
Parameters
Ptr Unaligned memory pointer to the 4 int32s
Returns
VectorRegister4Int(Ptr[0], Ptr[1], Ptr[2], Ptr[3])
Definition at line 2562 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterInt().
VectorIntLoad1()
FORCEINLINE VectorRegister4Int VectorIntLoad1 (const void * Ptr)
Loads 1 int32 from unaligned memory into all components of a vector register.
Parameters
Ptr Unaligned memory pointer to the 4 int32s
Returns
VectorRegister4Int(*Ptr, *Ptr, *Ptr, *Ptr)
Definition at line 2609 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterInt().
Referenced by FOctreeNodeContext::GetChildOffsetVec().
VectorIntLoadAligned()
FORCEINLINE VectorRegister4Int VectorIntLoadAligned (const void * Ptr)
Loads 4 int32s from aligned memory.
Parameters
Ptr Aligned memory pointer to the 4 int32s
Returns
VectorRegister4Int(Ptr[0], Ptr[1], Ptr[2], Ptr[3])
Definition at line 2593 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterInt().
VectorIntMax()
FORCEINLINE VectorRegister4Int VectorIntMax (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2462 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, MakeVectorRegisterInt(), and FMath::Max.
VectorIntMin()
FORCEINLINE VectorRegister4Int VectorIntMin (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2453 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, MakeVectorRegisterInt(), and FMath::Min.
VectorIntMultiply()
FORCEINLINE VectorRegister4Int VectorIntMultiply (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2435 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntNegate()
FORCEINLINE VectorRegister4Int VectorIntNegate (const VectorRegister4Int & A)
Definition at line 2444 of file UnrealMathFPU.h.
References A, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntNot()
FORCEINLINE VectorRegister4Int VectorIntNot (const VectorRegister4Int & A)
= ~a
Definition at line 2346 of file UnrealMathFPU.h.
References A, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntOr()
FORCEINLINE VectorRegister4Int VectorIntOr (const VectorRegister4Int & A, const VectorRegister4Int & B)
= a | b
Definition at line 2318 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntSelect()
FORCEINLINE VectorRegister4Int VectorIntSelect (const VectorRegister4Int & Mask, const VectorRegister4Int & Vec1, const VectorRegister4Int & Vec2)
Definition at line 2411 of file UnrealMathFPU.h.
References FORCEINLINE, Mask, VectorIntAnd(), and VectorIntXor().
VectorIntStore()
FORCEINLINE void VectorIntStore (const VectorRegister4Int & A, const void * Ptr)
Stores a vector to memory (aligned or unaligned).
Parameters
Vec Vector to store
Ptr Memory pointer
Definition at line 2546 of file UnrealMathFPU.h.
References A, and FORCEINLINE.
VectorIntStoreAligned()
FORCEINLINE void VectorIntStoreAligned (const VectorRegister4Int & A, const void * Ptr)
Stores a vector to memory (aligned).
Parameters
Vec Vector to store
Ptr Aligned Memory pointer
Definition at line 2578 of file UnrealMathFPU.h.
References A, and FORCEINLINE.
VectorIntSubtract()
FORCEINLINE VectorRegister4Int VectorIntSubtract (const VectorRegister4Int & A, const VectorRegister4Int & B)
Definition at line 2426 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
VectorIntToFloat()
FORCEINLINE VectorRegister4Float VectorIntToFloat (const VectorRegister4Int & A)
Definition at line 2482 of file UnrealMathFPU.h.
References A, FORCEINLINE, and MakeVectorRegisterFloat().
VectorIntXor()
FORCEINLINE VectorRegister4Int VectorIntXor (const VectorRegister4Int & A, const VectorRegister4Int & B)
= a ^ b
Definition at line 2327 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, and MakeVectorRegisterInt().
Referenced by VectorIntSelect().
VectorLoad() [1/2]
FORCEINLINE VectorRegister4Double VectorLoad (const double * Ptr)
Definition at line 399 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorLoad() [2/2]
FORCEINLINE VectorRegister4Float VectorLoad (const float * Ptr)
Loads 4 FLOATs from unaligned memory.
Parameters
Ptr Unaligned memory pointer to the 4 FLOATs
Returns
VectorRegister(Ptr[0], Ptr[1], Ptr[2], Ptr[3])
Definition at line 394 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterFloat().
Referenced by UE::Math::TMatrix< double >::TMatrix(), UE::Math::TTransform< double >::GetRotationRegister(), FRenderTransform::To3x4MatrixTranspose(), FRenderTransform::ToMatrix44f(), VectorLoad16(), VectorLoadAligned(), and VectorLoadAligned().
VectorLoad16()
FORCEINLINE VectorRegister4x4Float VectorLoad16 (const float * Ptr)
Loads 16 floats from unaligned memory into 4 vector registers.
Parameters
Ptr Unaligned memory pointer to the 4 floats
Returns
VectorRegister4x4Float containing 16 floats
Definition at line 410 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorLoad().
VectorLoadAligned() [1/2]
FORCEINLINE VectorRegister4Double VectorLoadAligned (const double * Ptr)
Definition at line 456 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorLoad().
VectorLoadAligned() [2/2]
FORCEINLINE VectorRegister4Float VectorLoadAligned (const float * Ptr)
Loads 4 FLOATs from aligned memory.
Parameters
Ptr Aligned memory pointer to the 4 FLOATs
Returns
VectorRegister4Float(Ptr[0], Ptr[1], Ptr[2], Ptr[3])
Definition at line 451 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorLoad().
Referenced by TAudioBuffer< float >::_AccumulateSIMD(), TAudioBuffer< float >::_CopySIMD(), TAudioBuffer< float >::_MultiplyAccumulateSIMD(), TAudioBuffer< float >::_SaturateSIMD(), TAudioBuffer< float >::_ScaleSIMD(), FGainMatrix::ApplyAndAccumulateToBuffer(), FGainMatrix::ApplyToBuffer(), TBounds< float >::Contains(), TBounds< float >::DistSqr(), UE::Math::TQuat< T >::Equals(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), UE::Math::TQuat< T >::GetRotationAxis(), FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, TBounds< float >::Intersect(), UE::Math::TQuat< T >::Inverse(), UE::Math::TQuat< T >::IsNormalized(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), UE::Math::TQuat< T >::Normalize(), UE::Math::TQuat< T >::operator!=(), UE::Math::TQuat< double >::operator*(), UE::Math::TQuat< T >::operator*=(), UE::Math::TQuat< double >::operator*=(), UE::Math::TQuat< T >::operator+(), TBounds< float >::operator+=(), TBounds< float >::operator+=(), UE::Math::TQuat< T >::operator+=(), UE::Math::TQuat< T >::operator-(), UE::Math::TQuat< T >::operator-(), UE::Math::TQuat< T >::operator-=(), UE::Math::TQuat< double >::operator/(), UE::Math::TQuat< double >::operator/=(), UE::Math::TQuat< T >::operator==(), Harmonix::Dsp::Effects::FFourBiquads::SetComponent(), AlignedDouble4::ToVectorRegister(), AlignedFloat4::ToVectorRegister(), UE::Math::TBox< T >::TransformBy(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
VectorLoadDouble1()
FORCEINLINE VectorRegister4Double VectorLoadDouble1 (const double * Ptr)
Definition at line 473 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorLoadFloat1()
FORCEINLINE VectorRegister4Float VectorLoadFloat1 (const float * Ptr)
Loads 1 float from unaligned memory and replicates it to all 4 elements.
Parameters
Ptr Unaligned memory pointer to the float
Returns
VectorRegister4Float(Ptr[0], Ptr[0], Ptr[0], Ptr[0])
Definition at line 468 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterFloat().
Referenced by TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::TkDOPLineCollisionCheck(), appLineCheckTriangleSOA(), UE::Math::TQuat< T >::Equals(), UE::Math::TRotator< T >::Equals(), FBoxCenterAndExtent::Intersect, UE::Math::TRotator< T >::IsNearlyZero(), and UE::Math::TQuat< T >::Normalize().
VectorLoadFloat2() [1/2]
FORCEINLINE VectorRegister4Double VectorLoadFloat2 (const double * Ptr)
Definition at line 490 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorLoadFloat2() [2/2]
FORCEINLINE VectorRegister4Float VectorLoadFloat2 (const float * Ptr)
Loads 2 floats from unaligned memory into X and Y and duplicates them in Z and W.
Parameters
Ptr Unaligned memory pointer to the floats
Returns
VectorRegister4Float(Ptr[0], Ptr[1], Ptr[0], Ptr[1])
Definition at line 485 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterFloat().
VectorLoadFloat3()
FORCEINLINE VectorRegister4Double VectorLoadFloat3 (const double * Ptr)
Loads 3 FLOATs from unaligned memory and sets W=0.
Parameters
Ptr Unaligned memory pointer to the 3 FLOATs
Returns
VectorRegister4Float(Ptr[0], Ptr[1], Ptr[2], 0)
Definition at line 427 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
Referenced by TBounds< float >::DistSqr(), FRenderBounds::operator+=(), FRenderBounds::operator+=(), TBounds< float >::operator+=(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
VectorLoadFloat3_W1()
FORCEINLINE VectorRegister4Double VectorLoadFloat3_W1 (const double * Ptr)
Loads 3 FLOATs from unaligned memory and sets W=1.
Parameters
Ptr Unaligned memory pointer to the 3 FLOATs
Returns
VectorRegister4Float(Ptr[0], Ptr[1], Ptr[2], 1.0f)
Definition at line 439 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorLoadSRGBA16N()
FORCEINLINE VectorRegister4Float VectorLoadSRGBA16N (void * Ptr)
Loads packed signed RGBA16(4 bytes) from unaligned memory and converts them into 4 FLOATs.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Ptr Unaligned memory pointer to the RGBA16(8 bytes).
Returns
VectorRegister with 4 FLOATs loaded from Ptr.
Definition at line 2268 of file UnrealMathFPU.h.
References float, FORCEINLINE, and MakeVectorRegisterFloat().
Referenced by FPackedRGBA16N::GetVectorRegister().
VectorLoadTwoPairsFloat() [1/2]
FORCEINLINE VectorRegister4Double VectorLoadTwoPairsFloat (const double * Ptr1, const double * Ptr2)
Definition at line 507 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegister().
VectorLoadTwoPairsFloat() [2/2]
FORCEINLINE VectorRegister4Float VectorLoadTwoPairsFloat (const float * Ptr1, const float * Ptr2)
Loads 4 unaligned floats - 2 from the first pointer, 2 from the second, and packs them in to 1 vector.
Parameters
Ptr1 Unaligned memory pointer to the first 2 floats
Ptr2 Unaligned memory pointer to the second 2 floats
Returns
VectorRegister(Ptr1[0], Ptr1[1], Ptr2[0], Ptr2[1])
Definition at line 503 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegister().
VectorLoadURGB10A2N()
FORCEINLINE VectorRegister4Float VectorLoadURGB10A2N (void * Ptr)
Loads packed RGB10A2(4 bytes) from unaligned memory and converts them into 4 FLOATs.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Ptr Unaligned memory pointer to the RGB10A2(4 bytes).
Returns
VectorRegister with 4 FLOATs loaded from Ptr.
Definition at line 1875 of file UnrealMathFPU.h.
References float, FORCEINLINE, and MakeVectorRegisterFloat().
Referenced by FPackedRGB10A2N::GetVectorRegister().
VectorLoadURGBA16N()
FORCEINLINE VectorRegister4Float VectorLoadURGBA16N (void * Ptr)
Loads packed RGBA16(4 bytes) from unaligned memory and converts them into 4 FLOATs.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Ptr Unaligned memory pointer to the RGBA16(8 bytes).
Returns
VectorRegister with 4 FLOATs loaded from Ptr.
Definition at line 2248 of file UnrealMathFPU.h.
References float, FORCEINLINE, and MakeVectorRegisterFloat().
VectorLog() [1/2]
FORCEINLINE VectorRegister4Double VectorLog (const VectorRegister4Double & Vec)
Definition at line 1998 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorLog() [2/2]
FORCEINLINE VectorRegister4Float VectorLog (const VectorRegister4Float & Vec)
Definition at line 1993 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorLog2() [1/2]
FORCEINLINE VectorRegister4Double VectorLog2 (const VectorRegister4Double & Vec)
Definition at line 2009 of file UnrealMathFPU.h.
References FORCEINLINE, FMath::Log2(), MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorLog2() [2/2]
FORCEINLINE VectorRegister4Float VectorLog2 (const VectorRegister4Float & Vec)
Definition at line 2004 of file UnrealMathFPU.h.
References FORCEINLINE, FMath::Log2(), MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorMaskBits() [1/2]
FORCEINLINE int32 VectorMaskBits (const VectorRegister4Double & Vec1)
Definition at line 1085 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorMaskBits() [2/2]
FORCEINLINE int32 VectorMaskBits (const VectorRegister4Float & Vec1)
Returns an integer bit-mask (0x00 - 0x0f) based on the sign-bit for each component in a vector.
Parameters
VecMask Vector
Returns
Bit 0 = sign(VecMask.x), Bit 1 = sign(VecMask.y), Bit 2 = sign(VecMask.z), Bit 3 = sign(VecMask.w)
Definition at line 1075 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by TAudioBuffer< float >::_SaturateSIMD(), appLineCheckTriangleSOA(), TBounds< float >::Contains(), UE::Math::TQuat< T >::operator!=(), and UE::Math::TQuat< T >::operator==().
VectorMatrixInverse() [1/2]
FORCEINLINE bool VectorMatrixInverse (FMatrix44d * DstMatrix, const FMatrix44d * SrcMatrix)
Calculate the inverse of an FMatrix44.
Src == Dst is allowed
Parameters
DstMatrix FMatrix44 pointer to where the result should be stored
SrcMatrix FMatrix44 pointer to the Matrix to be inversed
Returns
bool returns false if matrix is not invertable and stores identity
Definition at line 1603 of file UnrealMathFPU.h.
References FORCEINLINE, and FMath::MatrixInverse().
VectorMatrixInverse() [2/2]
FORCEINLINE bool VectorMatrixInverse (FMatrix44f * DstMatrix, const FMatrix44f * SrcMatrix)
Definition at line 1607 of file UnrealMathFPU.h.
References FORCEINLINE, and FMath::MatrixInverse().
VectorMatrixMultiply() [1/2]
FORCEINLINE void VectorMatrixMultiply (FMatrix44d * Result, const FMatrix44d * Matrix1, const FMatrix44d * Matrix2)
Multiplies two 4x4 matrices.
Parameters
Result Pointer to where the result should be stored
Matrix1 Pointer to the first matrix
Matrix2 Pointer to the second matrix
Definition at line 1538 of file UnrealMathFPU.h.
References A, B, and FORCEINLINE.
VectorMatrixMultiply() [2/2]
FORCEINLINE void VectorMatrixMultiply (FMatrix44f * Result, const FMatrix44f * Matrix1, const FMatrix44f * Matrix2)
Definition at line 1566 of file UnrealMathFPU.h.
References A, B, and FORCEINLINE.
VectorMax() [1/2]
FORCEINLINE VectorRegister4Double VectorMax (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1723 of file UnrealMathFPU.h.
References FORCEINLINE, FMath::Max, and VectorRegister4Double::V.
VectorMax() [2/2]
FORCEINLINE VectorRegister4Float VectorMax (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Returns the maximum values of two vectors (component-wise).
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(max(Vec1.x,Vec2.x), max(Vec1.y,Vec2.y), max(Vec1.z,Vec2.z), max(Vec1.w,Vec2.w))
Definition at line 1713 of file UnrealMathFPU.h.
References FORCEINLINE, FMath::Max, and VectorRegister4Float::V.
Referenced by TAudioBuffer< float >::_CopySIMD(), TAudioBuffer< float >::_SaturateSIMD(), TBounds< float >::DistSqr(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), FRenderBounds::operator+=(), FRenderBounds::operator+=(), TBounds< float >::operator+=(), TBounds< float >::operator+=(), UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy(), VectorStoreURGB10A2N(), and VectorStoreURGBA16N().
VectorMergeVecXYZ_VecW() [1/2]
FORCEINLINE VectorRegister4Double VectorMergeVecXYZ_VecW (const VectorRegister4Double & VecXYZ, const VectorRegister4Double & VecW)
Definition at line 1802 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorMergeVecXYZ_VecW() [2/2]
FORCEINLINE VectorRegister4Float VectorMergeVecXYZ_VecW (const VectorRegister4Float & VecXYZ, const VectorRegister4Float & VecW)
Merges the XYZ components of one vector with the W component of another vector and returns the result.
Parameters
VecXYZ Source vector for XYZ_
VecW Source register for ___W (note: the fourth component is used, not the first)
Returns
VectorRegister(VecXYZ.x, VecXYZ.y, VecXYZ.z, VecW.w)
Definition at line 1797 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorMin() [1/2]
FORCEINLINE VectorRegister4Double VectorMin (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1696 of file UnrealMathFPU.h.
References FORCEINLINE, FMath::Min, and VectorRegister4Double::V.
VectorMin() [2/2]
FORCEINLINE VectorRegister4Float VectorMin (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Returns the minimum values of two vectors (component-wise).
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(min(Vec1.x,Vec2.x), min(Vec1.y,Vec2.y), min(Vec1.z,Vec2.z), min(Vec1.w,Vec2.w))
Definition at line 1686 of file UnrealMathFPU.h.
References FORCEINLINE, FMath::Min, and VectorRegister4Float::V.
Referenced by TAudioBuffer< float >::_CopySIMD(), TAudioBuffer< float >::_SaturateSIMD(), appLineCheckTriangleSOA(), TBounds< float >::DistSqr(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), FRenderBounds::operator+=(), FRenderBounds::operator+=(), TBounds< float >::operator+=(), TBounds< float >::operator+=(), VectorStoreURGB10A2N(), and VectorStoreURGBA16N().
VectorMod() [1/2]
FORCEINLINE VectorRegister4Double VectorMod (const VectorRegister4Double & X, const VectorRegister4Double & Y)
Definition at line 2194 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), X, and Y.
VectorMod() [2/2]
FORCEINLINE VectorRegister4Float VectorMod (const VectorRegister4Float & X, const VectorRegister4Float & Y)
Definition at line 2185 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), X, and Y.
VectorMultiply() [1/2]
FORCEINLINE VectorRegister4Double VectorMultiply (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 768 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorMultiply() [2/2]
FORCEINLINE VectorRegister4Float VectorMultiply (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Multiplies two vectors (component-wise) and returns the result.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x*Vec2.x, Vec1.y*Vec2.y, Vec1.z*Vec2.z, Vec1.w*Vec2.w)
Definition at line 758 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), TAudioBuffer< float >::_CopySIMD(), TAudioBuffer< float >::_MultiplyAccumulateSIMD(), TAudioBuffer< float >::_ScaleSIMD(), appLineCheckTriangleSOA(), FGainMatrix::ApplyAndAccumulateToBuffer(), FGainMatrix::ApplyToBuffer(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FPackedNormal::GetVectorRegister(), FPackedRGBA16N::GetVectorRegister(), FGainMatrix::Lerp(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), UE::Math::TQuat< T >::Normalize(), FGainMatrix::operator*(), UE::Math::TQuat< double >::operator*(), FGainMatrix::operator*=(), UE::Math::TQuat< double >::operator*=(), Harmonix::Dsp::Effects::FFourBiquads::Process(), Harmonix::Dsp::Effects::FFourBiquads::Process(), Harmonix::Dsp::Effects::FFourBiquads::ProcessOne(), UE::Math::TBox< T >::TransformBy(), UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy(), VectorNegateMultiplyAdd(), VectorNegateMultiplyAdd(), and VectorStoreURGB10A2N().
VectorMultiplyAdd() [1/2]
FORCEINLINE VectorRegister4Double VectorMultiplyAdd (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2, const VectorRegister4Double & Vec3)
Definition at line 796 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorMultiplyAdd() [2/2]
FORCEINLINE VectorRegister4Float VectorMultiplyAdd (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2, const VectorRegister4Float & Vec3)
Multiplies two vectors (component-wise), adds in the third vector and returns the result.
Parameters
Vec1 1st vector
Vec2 2nd vector
Vec3 3rd vector
Returns
VectorRegister(Vec1.x*Vec2.x + Vec3.x, Vec1.y*Vec2.y + Vec3.y, Vec1.z*Vec2.z + Vec3.z, Vec1.w*Vec2.w + Vec3.w)
Definition at line 786 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by appLineCheckTriangleSOA(), FPackedRGB10A2N::GetVectorRegister(), FDeprecatedSerializedPackedNormal::operator FVector3f(), FDeprecatedSerializedPackedNormal::operator FVector4f(), UE::Math::TBox< T >::TransformBy(), UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy(), and VectorStoreURGBA16N().
VectorNegate() [1/2]
FORCEINLINE VectorRegister4Double VectorNegate (const VectorRegister4Double & Vec)
Definition at line 692 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorNegate() [2/2]
FORCEINLINE VectorRegister4Float VectorNegate (const VectorRegister4Float & Vec)
Returns the negated value (component-wise).
Parameters
Vec Source vector
Returns
VectorRegister(-Vec.x, -Vec.y, -Vec.z, -Vec.w)
Definition at line 687 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterFloat().
Referenced by UE::Math::TQuat< T >::operator-().
VectorNegateMultiplyAdd() [1/2]
FORCEINLINE VectorRegister4Double VectorNegateMultiplyAdd (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2, const VectorRegister4Double & Vec3)
Definition at line 820 of file UnrealMathFPU.h.
References FORCEINLINE, VectorMultiply(), and VectorSubtract().
VectorNegateMultiplyAdd() [2/2]
FORCEINLINE VectorRegister4Float VectorNegateMultiplyAdd (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2, const VectorRegister4Float & Vec3)
Multiplies two vectors (component-wise), negates the results and adds it to the third vector i.e.
-AB + C = C - AB
Parameters
Vec1 1st vector
Vec2 2nd vector
Vec3 3rd vector
Returns
VectorRegister(Vec3.x - Vec1.x*Vec2.x, Vec3.y - Vec1.y*Vec2.y, Vec3.z - Vec1.z*Vec2.z, Vec3.w - Vec1.w*Vec2.w)
Definition at line 815 of file UnrealMathFPU.h.
References FORCEINLINE, VectorMultiply(), and VectorSubtract().
Referenced by appLineCheckTriangleSOA().
VectorOneDouble()
FORCEINLINE VectorRegister4Double VectorOneDouble (void)
Definition at line 351 of file UnrealMathFPU.h.
References FORCEINLINE.
VectorOneFloat()
FORCEINLINE VectorRegister4Float VectorOneFloat (void)
Returns a vector with all ones.
Returns
VectorRegister4Float(1.0f, 1.0f, 1.0f, 1.0f)
Definition at line 346 of file UnrealMathFPU.h.
References FORCEINLINE.
VectorPow() [1/2]
FORCEINLINE VectorRegister4Double VectorPow (const VectorRegister4Double & Base, const VectorRegister4Double & Exponent)
Definition at line 1253 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorPow() [2/2]
FORCEINLINE VectorRegister4Float VectorPow (const VectorRegister4Float & Base, const VectorRegister4Float & Exponent)
Calculates x raised to the power of y (component-wise).
Parameters
Base Base vector
Exponent Exponent vector
Returns
VectorRegister(Base.x^Exponent.x, Base.y^Exponent.y, Base.z^Exponent.z, Base.w^Exponent.w)
Definition at line 1243 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
VectorQuaternionMultiply() [1/2]
FORCEINLINE void VectorQuaternionMultiply (VectorRegister4Double *RESTRICT Result, const VectorRegister4Double *RESTRICT Quat1, const VectorRegister4Double *RESTRICT Quat2)
Definition at line 1469 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, R, and RESTRICT.
VectorQuaternionMultiply() [2/2]
FORCEINLINE void VectorQuaternionMultiply (VectorRegister4Float *RESTRICT Result, const VectorRegister4Float *RESTRICT Quat1, const VectorRegister4Float *RESTRICT Quat2)
Multiplies two quaternions; the order matters.
When composing quaternions: VectorQuaternionMultiply(C, A, B) will yield a quaternion C = A * B that logically first applies B then A to any subsequent transformation (right first, then left).
Parameters
Result Pointer to where the result Quat1 * Quat2 should be stored
Quat1 Pointer to the first quaternion (must not be the destination)
Quat2 Pointer to the second quaternion (must not be the destination)
Definition at line 1431 of file UnrealMathFPU.h.
References A, B, FORCEINLINE, R, and RESTRICT.
Referenced by UE::Math::TQuat< T >::operator*(), VectorQuaternionMultiply2(), and VectorQuaternionMultiply2().
VectorQuaternionMultiply2() [1/2]
FORCEINLINE VectorRegister4Double VectorQuaternionMultiply2 (const VectorRegister4Double & Quat1, const VectorRegister4Double & Quat2)
Definition at line 1524 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorQuaternionMultiply().
VectorQuaternionMultiply2() [2/2]
FORCEINLINE VectorRegister4Float VectorQuaternionMultiply2 (const VectorRegister4Float & Quat1, const VectorRegister4Float & Quat2)
Multiplies two quaternions; the order matters.
Order matters when composing quaternions: C = VectorQuaternionMultiply2(A, B) will yield a quaternion C = A * B that logically first applies B then A to any subsequent transformation (right first, then left).
Parameters
Quat1 Pointer to the first quaternion
Quat2 Pointer to the second quaternion
Returns
Quat1 * Quat2
Definition at line 1517 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorQuaternionMultiply().
Referenced by UE::Math::TQuat< T >::operator*=().
VectorReciprocal() [1/2]
FORCEINLINE VectorRegister4Double VectorReciprocal (const VectorRegister4Double & Vec)
Definition at line 1316 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorDivide().
VectorReciprocal() [2/2]
FORCEINLINE VectorRegister4Float VectorReciprocal (const VectorRegister4Float & Vec)
Computes the reciprocal of a vector (component-wise) and returns the result.
Parameters
Vec 1st vector
Returns
VectorRegister4Float(1.0f / Vec.x, 1.0f / Vec.y, 1.0f / Vec.z, 1.0f / Vec.w)
Definition at line 1311 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorDivide().
Referenced by VectorReciprocalEstimate(), and VectorReciprocalEstimate().
VectorReciprocalEstimate() [1/2]
FORCEINLINE VectorRegister4Double VectorReciprocalEstimate (const VectorRegister4Double & Vec)
Definition at line 1332 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorReciprocal().
VectorReciprocalEstimate() [2/2]
FORCEINLINE VectorRegister4Float VectorReciprocalEstimate (const VectorRegister4Float & Vec)
Computes an estimate of the reciprocal of a vector (component-wise) and returns the result.
Parameters
Vec 1st vector
Returns
VectorRegister((Estimate) 1.0f / Vec.x, (Estimate) 1.0f / Vec.y, (Estimate) 1.0f / Vec.z, (Estimate) 1.0f / Vec.w)
Definition at line 1327 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorReciprocal().
VectorReciprocalLen() [1/2]
FORCEINLINE VectorRegister4Double VectorReciprocalLen (const VectorRegister4Double & Vec)
Definition at line 1356 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Double::V, and VectorDot4().
VectorReciprocalLen() [2/2]
FORCEINLINE VectorRegister4Float VectorReciprocalLen (const VectorRegister4Float & Vec)
Return Reciprocal Length of the vector.
Parameters
Vec Vector
Returns
VectorRegister(rlen, rlen, rlen, rlen) when rlen = 1/sqrt(dot4(V))
Definition at line 1343 of file UnrealMathFPU.h.
References FORCEINLINE, VectorRegister4Float::V, and VectorDot4().
Referenced by VectorReciprocalLenEstimate(), and VectorReciprocalLenEstimate().
VectorReciprocalLenEstimate() [1/2]
FORCEINLINE VectorRegister4Double VectorReciprocalLenEstimate (const VectorRegister4Double & Vector)
Definition at line 1380 of file UnrealMathFPU.h.
References FORCEINLINE, Vector, and VectorReciprocalLen().
VectorReciprocalLenEstimate() [2/2]
FORCEINLINE VectorRegister4Float VectorReciprocalLenEstimate (const VectorRegister4Float & Vector)
Return Reciprocal Length of the vector (estimate)
Parameters
Vector Vector
Returns
VectorRegister4Float(rlen, rlen, rlen, rlen) when rlen = 1/sqrt(dot4(V))
Definition at line 1375 of file UnrealMathFPU.h.
References FORCEINLINE, Vector, and VectorReciprocalLen().
VectorReciprocalSqrt() [1/2]
FORCEINLINE VectorRegister4Double VectorReciprocalSqrt (const VectorRegister4Double & Vec)
Definition at line 1284 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorReciprocalSqrt() [2/2]
FORCEINLINE VectorRegister4Float VectorReciprocalSqrt (const VectorRegister4Float & Vec)
Returns an estimate of 1/sqrt(c) for each component of the vector.
Parameters
Vector Vector
Returns
VectorRegister(1/sqrt(t), 1/sqrt(t), 1/sqrt(t), 1/sqrt(t))
Definition at line 1279 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorReciprocalSqrtEstimate() [1/2]
FORCEINLINE VectorRegister4Double VectorReciprocalSqrtEstimate (const VectorRegister4Double & Vec)
Definition at line 1300 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorReciprocalSqrtEstimate() [2/2]
FORCEINLINE VectorRegister4Float VectorReciprocalSqrtEstimate (const VectorRegister4Float & Vec)
Returns an estimate of 1/sqrt(c) for each component of the vector.
Parameters
Vector Vector
Returns
VectorRegister(1/sqrt(t), 1/sqrt(t), 1/sqrt(t), 1/sqrt(t))
Definition at line 1295 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorRound() [1/2]
FORCEINLINE VectorRegister4Double VectorRound (const VectorRegister4Double & Vec)
Definition at line 2169 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorRound() [2/2]
FORCEINLINE VectorRegister4Float VectorRound (const VectorRegister4Float & Vec)
Definition at line 2164 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorRoundToIntHalfToEven()
FORCEINLINE VectorRegister4Int VectorRoundToIntHalfToEven (const VectorRegister4Float & A)
Definition at line 2175 of file UnrealMathFPU.h.
References A, FORCEINLINE, MakeVectorRegisterInt(), and FMath::RoundHalfToEven().
VectorSelect() [1/2]
FORCEINLINE VectorRegister4Double VectorSelect (const VectorRegister4Double & Mask, const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 1119 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), Mask, and VectorRegister4Double::V.
VectorSelect() [2/2]
FORCEINLINE VectorRegister4Float VectorSelect (const VectorRegister4Float & Mask, const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Does a bitwise vector selection based on a mask (e.g., created from VectorCompareXX)
Parameters
Mask Mask (when 1: use the corresponding bit from Vec1 otherwise from Vec2)
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(for each bit i: Mask[i] ? Vec1[i] : Vec2[i])
Definition at line 1105 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), Mask, and VectorRegister4Float::V.
Referenced by appLineCheckTriangleSOA(), FOctreeNodeContext::GetChildOffsetVec(), and UE::Math::TQuat< T >::Normalize().
VectorSet_W0() [1/2]
FORCEINLINE VectorRegister4Double VectorSet_W0 (const VectorRegister4Double & Vec)
Definition at line 1396 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorSet_W0() [2/2]
FORCEINLINE VectorRegister4Float VectorSet_W0 (const VectorRegister4Float & Vec)
Loads XYZ and sets W=0.
Parameters
Vec VectorRegister
Returns
VectorRegister(X, Y, Z, 0.0f)
Definition at line 1391 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterFloat().
Referenced by UE::Math::TQuat< T >::GetRotationAxis(), FBoxCenterAndExtent::Intersect, and FRenderTransform::ToMatrix44f().
VectorSet_W1() [1/2]
FORCEINLINE VectorRegister4Double VectorSet_W1 (const VectorRegister4Double & Vec)
Definition at line 1412 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorSet_W1() [2/2]
FORCEINLINE VectorRegister4Float VectorSet_W1 (const VectorRegister4Float & Vec)
Loads XYZ and sets W=1.
Parameters
Vec VectorRegister
Returns
VectorRegister(X, Y, Z, 1.0f)
Definition at line 1407 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterFloat().
VectorSetFloat1() [1/2]
FORCEINLINE VectorRegister4Double VectorSetFloat1 (double D)
Definition at line 523 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterDouble().
VectorSetFloat1() [2/2]
FORCEINLINE VectorRegister4Float VectorSetFloat1 (float F)
Propagates passed in float to all registers.
Parameters
F Float to set
Returns
VectorRegister4Float(F,F,F,F)
Definition at line 518 of file UnrealMathFPU.h.
References FORCEINLINE, and MakeVectorRegisterFloat().
Referenced by Harmonix::Dsp::Effects::FFourBiquads::FFourBiquads(), TAudioBuffer< float >::_CopySIMD(), TAudioBuffer< float >::_MultiplyAccumulateSIMD(), TAudioBuffer< float >::_SaturateSIMD(), TAudioBuffer< float >::_ScaleSIMD(), FGainMatrix::ApplyAndAccumulateToBuffer(), FGainMatrix::ApplyToBuffer(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildOffsetVec(), FPackedNormal::GetVectorRegister(), FPackedRGBA16N::GetVectorRegister(), FGainMatrix::Lerp(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), FDeprecatedSerializedPackedNormal::operator FVector3f(), FDeprecatedSerializedPackedNormal::operator FVector4f(), FGainMatrix::operator*(), UE::Math::TQuat< double >::operator*(), FGainMatrix::operator*=(), UE::Math::TQuat< double >::operator*=(), UE::Math::TQuat< double >::operator/(), UE::Math::TQuat< double >::operator/=(), FGainMatrix::operator=(), Harmonix::Dsp::Effects::FFourBiquads::Process(), and UE::Math::TBox< T >::TransformBy().
VectorShuffleByte4()
FORCEINLINE VectorRegister4Int VectorShuffleByte4 (const VectorRegister4Int & Vec, const VectorRegister4Int & Mask)
Definition at line 2515 of file UnrealMathFPU.h.
References FORCEINLINE, and Mask.
VectorSign() [1/2]
FORCEINLINE VectorRegister4Double VectorSign (const VectorRegister4Double & Vec)
Definition at line 2213 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorSign() [2/2]
FORCEINLINE VectorRegister4Float VectorSign (const VectorRegister4Float & Vec)
Definition at line 2204 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorSin() [1/2]
FORCEINLINE VectorRegister4Double VectorSin (const VectorRegister4Double & Vec)
Definition at line 2020 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorSin() [2/2]
FORCEINLINE VectorRegister4Float VectorSin (const VectorRegister4Float & Vec)
Definition at line 2015 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by VectorSinCos().
VectorSinCos() [1/2]
FORCEINLINE void VectorSinCos (VectorRegister4Double *RESTRICT VSinAngles, VectorRegister4Double *RESTRICT VCosAngles, const VectorRegister4Double *RESTRICT VAngles)
Definition at line 2123 of file UnrealMathFPU.h.
References FORCEINLINE, RESTRICT, VectorCos(), and VectorSin().
VectorSinCos() [2/2]
FORCEINLINE void VectorSinCos (VectorRegister4Float *RESTRICT VSinAngles, VectorRegister4Float *RESTRICT VCosAngles, const VectorRegister4Float *RESTRICT VAngles)
Computes the sine and cosine of each component of a Vector.
Parameters
VSinAngles VectorRegister Pointer to where the Sin result should be stored
VCosAngles VectorRegister Pointer to where the Cos result should be stored
VAngles VectorRegister Pointer to the input angles
Definition at line 2109 of file UnrealMathFPU.h.
References FORCEINLINE, RESTRICT, and FMath::SinCos().
Referenced by UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix().
VectorSqrt() [1/2]
FORCEINLINE VectorRegister4Double VectorSqrt (const VectorRegister4Double & Vec)
Definition at line 1268 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorSqrt() [2/2]
FORCEINLINE VectorRegister4Float VectorSqrt (const VectorRegister4Float & Vec)
Definition at line 1263 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorStep() [1/2]
FORCEINLINE VectorRegister4Double VectorStep (const VectorRegister4Double & Vec)
Definition at line 2232 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorStep() [2/2]
FORCEINLINE VectorRegister4Float VectorStep (const VectorRegister4Float & Vec)
Definition at line 2223 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorStore() [1/2]
FORCEINLINE void VectorStore (const VectorRegister4Double & Vec, double * Dst)
Definition at line 571 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
VectorStore() [2/2]
FORCEINLINE void VectorStore (const VectorRegister4Float & Vec, float * Dst)
Stores a vector to memory (aligned or unaligned).
Parameters
Vec Vector to store
Ptr Memory pointer
Definition at line 566 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
Referenced by UE::Math::TMatrix< double >::TMatrix(), FDeprecatedSerializedPackedNormal::operator FVector4f(), UE::Math::TTransform< double >::SetRotationRegister(), FRenderTransform::To3x4MatrixTranspose(), FPackedNormal::ToFVector4f(), FPackedRGBA16N::ToFVector4f(), and FRenderTransform::ToMatrix44f().
VectorStore16()
FORCEINLINE void VectorStore16 (const VectorRegister4x4Float & Vec, float * Dst)
Stores 4 vectors to memory (aligned or unaligned).
Parameters
Vec Vector to store
Ptr Memory pointer
Definition at line 582 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
VectorStoreAligned() [1/2]
FORCEINLINE void VectorStoreAligned (const VectorRegister4Double & Vec, double * Dst)
Definition at line 539 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
VectorStoreAligned() [2/2]
FORCEINLINE void VectorStoreAligned (const VectorRegister4Float & Vec, float * Dst)
Stores a vector to aligned memory.
Parameters
Vec Vector to store
Ptr Aligned memory pointer
Definition at line 534 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
Referenced by AlignedDouble4::AlignedDouble4(), AlignedFloat4::AlignedFloat4(), UE::Math::TQuat< T >::TQuat(), TAudioBuffer< float >::_AccumulateSIMD(), TAudioBuffer< float >::_CopySIMD(), TAudioBuffer< float >::_MultiplyAccumulateSIMD(), TAudioBuffer< float >::_SaturateSIMD(), TAudioBuffer< float >::_ScaleSIMD(), FGainMatrix::ApplyAndAccumulateToBuffer(), FGainMatrix::ApplyToBuffer(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), FOctreeNodeContext::GetChildContext(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), UE::Math::TQuat< T >::Normalize(), UE::Math::TQuat< T >::operator*=(), UE::Math::TQuat< double >::operator*=(), TBounds< float >::operator+=(), TBounds< float >::operator+=(), UE::Math::TQuat< T >::operator+=(), UE::Math::TQuat< T >::operator-=(), UE::Math::TQuat< double >::operator/=(), Harmonix::Dsp::Effects::FFourBiquads::SetComponent(), VectorStoreAlignedStreamed(), and VectorStoreAlignedStreamed().
VectorStoreAlignedStreamed() [1/2]
FORCEINLINE void VectorStoreAlignedStreamed (const VectorRegister4Double & Vec, double * Dst)
Definition at line 555 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorStoreAligned().
VectorStoreAlignedStreamed() [2/2]
FORCEINLINE void VectorStoreAlignedStreamed (const VectorRegister4Float & Vec, float * Dst)
Performs non-temporal store of a vector to aligned memory without polluting the caches.
Parameters
Vec Vector to store
Ptr Aligned memory pointer
Definition at line 550 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorStoreAligned().
VectorStoreByte4()
FORCEINLINE void VectorStoreByte4 (const VectorRegister4Float & Vec, void * Ptr)
Converts the 4 FLOATs in the vector to 4 BYTEs, clamped to [0,255], and stores to unaligned memory.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Vec Vector containing 4 FLOATs
Ptr Unaligned memory pointer to store the 4 BYTEs.
Definition at line 1842 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
VectorStoreFloat1() [1/2]
FORCEINLINE void VectorStoreFloat1 (const VectorRegister4Double & Vec, double * Dst)
Definition at line 615 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
VectorStoreFloat1() [2/2]
FORCEINLINE void VectorStoreFloat1 (const VectorRegister4Float & Vec, float * Dst)
Stores the X component of a vector to unaligned memory.
Parameters
Vec Vector to store X
Ptr Unaligned memory pointer
Definition at line 610 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
Referenced by appLineCheckTriangleSOA().
VectorStoreFloat3() [1/2]
FORCEINLINE void VectorStoreFloat3 (const VectorRegister4Double & Vec, double * Dst)
Definition at line 599 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
VectorStoreFloat3() [2/2]
FORCEINLINE void VectorStoreFloat3 (const VectorRegister4Float & Vec, float * Dst)
Stores the XYZ components of a vector to unaligned memory.
Parameters
Vec Vector to store XYZ
Ptr Unaligned memory pointer
Definition at line 594 of file UnrealMathFPU.h.
References FORCEINLINE, and FMemory::Memcpy().
Referenced by UE::Math::TQuat< T >::GetRotationAxis(), UE::Math::TRotator< T >::Normalize(), FDeprecatedSerializedPackedNormal::operator FVector3f(), FRenderBounds::operator+=(), FRenderBounds::operator+=(), UE::Math::TTransform< double >::SetTranslationRegister(), FPackedNormal::ToFVector3f(), FPackedRGBA16N::ToFVector3f(), UE::Math::TBox< T >::TransformBy(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
VectorStoreSignedByte4()
FORCEINLINE void VectorStoreSignedByte4 (const VectorRegister4Float & Vec, void * Ptr)
Converts the 4 FLOATs in the vector to 4 BYTEs, clamped to [-127,127], and stores to unaligned memory.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Vec Vector containing 4 FLOATs
Ptr Unaligned memory pointer to store the 4 BYTEs.
Definition at line 1858 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
VectorStoreURGB10A2N()
FORCEINLINE void VectorStoreURGB10A2N (const VectorRegister4Float & Vec, void * Ptr)
Converts the 4 FLOATs in the vector RGB10A2, clamped to [0, 1023] and [0, 3], and stores to unaligned memory.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Vec Vector containing 4 FLOATs
Ptr Unaligned memory pointer to store the packed RGB10A2(4 bytes).
Definition at line 1895 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), VectorRegister4Float::V, VectorMax(), VectorMin(), and VectorMultiply().
VectorStoreURGBA16N()
FORCEINLINE void VectorStoreURGBA16N (const VectorRegister4Float & Vec, void * Ptr)
Converts the 4 FLOATs in the vector RGBA16, clamped to [0, 65535], and stores to unaligned memory.
IMPORTANT: You need to call VectorResetFloatRegisters() before using scalar FLOATs after you've used this intrinsic!
Parameters
Vec Vector containing 4 FLOATs
Ptr Unaligned memory pointer to store the packed RGBA16(8 bytes).
Definition at line 2288 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), VectorRegister4Float::V, VectorMax(), VectorMin(), VectorMultiplyAdd(), and VectorTruncate().
VectorSubtract() [1/2]
FORCEINLINE VectorRegister4Double VectorSubtract (const VectorRegister4Double & Vec1, const VectorRegister4Double & Vec2)
Definition at line 741 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorSubtract() [2/2]
FORCEINLINE VectorRegister4Float VectorSubtract (const VectorRegister4Float & Vec1, const VectorRegister4Float & Vec2)
Subtracts a vector from another (component-wise) and returns the result.
Parameters
Vec1 1st vector
Vec2 2nd vector
Returns
VectorRegister(Vec1.x-Vec2.x, Vec1.y-Vec2.y, Vec1.z-Vec2.z, Vec1.w-Vec2.w)
Definition at line 731 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
Referenced by TAudioBuffer< float >::_SaturateSIMD(), appLineCheckTriangleSOA(), TBounds< float >::DistSqr(), UE::Math::TQuat< T >::Equals(), UE::Math::TRotator< T >::Equals(), FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, FBoxCenterAndExtent::Intersect, UE::Math::TQuat< T >::IsNormalized(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), UE::Math::TQuat< T >::operator-(), UE::Math::TQuat< T >::operator-=(), Harmonix::Dsp::Effects::FFourBiquads::Process(), Harmonix::Dsp::Effects::FFourBiquads::Process(), Harmonix::Dsp::Effects::FFourBiquads::ProcessOne(), UE::Math::TBox< T >::TransformBy(), VectorNegateMultiplyAdd(), and VectorNegateMultiplyAdd().
VectorTan() [1/2]
FORCEINLINE VectorRegister4Double VectorTan (const VectorRegister4Double & Vec)
Definition at line 2044 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorTan() [2/2]
FORCEINLINE VectorRegister4Float VectorTan (const VectorRegister4Float & Vec)
Definition at line 2039 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
VectorTransformVector() [1/4]
FORCEINLINE VectorRegister4Double VectorTransformVector (const VectorRegister4Double & VecP, const FMatrix44d * MatrixM)
Definition at line 1649 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorTransformVector() [2/4]
FORCEINLINE VectorRegister4Double VectorTransformVector (const VectorRegister4Double & VecP, const FMatrix44f * MatrixM)
Definition at line 1663 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Double::V.
VectorTransformVector() [3/4]
FORCEINLINE VectorRegister4Float VectorTransformVector (const VectorRegister4Float & VecP, const FMatrix44d * MatrixM)
Definition at line 1633 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), MakeVectorRegisterFloatFromDouble(), and VectorRegister4Double::V.
VectorTransformVector() [4/4]
FORCEINLINE VectorRegister4Float VectorTransformVector (const VectorRegister4Float & VecP, const FMatrix44f * MatrixM)
Calculate Homogeneous transform.
Parameters
VecP VectorRegister
MatrixM FMatrix44d pointer to the Matrix to apply transform
Returns
VectorRegister = VecP*MatrixM
Definition at line 1619 of file UnrealMathFPU.h.
References FORCEINLINE, and VectorRegister4Float::V.
VectorTruncate() [1/2]
FORCEINLINE VectorRegister4Double VectorTruncate (const VectorRegister4Double & Vec)
Definition at line 2158 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterDouble(), and VectorRegister4Double::V.
VectorTruncate() [2/2]
FORCEINLINE VectorRegister4Float VectorTruncate (const VectorRegister4Float & Vec)
Definition at line 2153 of file UnrealMathFPU.h.
References FORCEINLINE, MakeVectorRegisterFloat(), and VectorRegister4Float::V.
Referenced by VectorStoreURGBA16N().
VectorZeroDouble()
FORCEINLINE VectorRegister4Double VectorZeroDouble (void)
Definition at line 336 of file UnrealMathFPU.h.
References FORCEINLINE.
VectorZeroFloat()
FORCEINLINE VectorRegister4Float VectorZeroFloat (void)
Returns a vector with all zeros.
Returns
MakeVectorRegister(0.0f, 0.0f, 0.0f, 0.0f)
Definition at line 331 of file UnrealMathFPU.h.
References FORCEINLINE.