Unreal Engine 5.6 C++ API: Runtime/Core/Public/Serialization/VarInt.h File Reference
VarInt.h File Reference
#include "CoreTypes.h"
#include "HAL/PlatformMath.h"
Functions
FORCEINLINE uint32 MeasureVarInt (const void *InData)
Measure the length in bytes (1-9) of an encoded variable-length integer.
FORCEINLINE uint32 MeasureVarInt (int32 InValue)
Measure the number of bytes (1-5) required to encode the 32-bit input.
FORCEINLINE uint32 MeasureVarInt (int64 InValue)
Measure the number of bytes (1-9) required to encode the 64-bit input.
FORCEINLINE uint32 MeasureVarUInt (const void *InData)
Measure the length in bytes (1-9) of an encoded variable-length integer.
FORCEINLINE uint32 MeasureVarUInt (uint32 InValue)
Measure the number of bytes (1-5) required to encode the 32-bit input.
FORCEINLINE uint32 MeasureVarUInt (uint64 InValue)
Measure the number of bytes (1-9) required to encode the 64-bit input.
FORCEINLINE int64 ReadVarInt (const void *InData, uint32 &OutByteCount)
Read a variable-length signed integer.
int64 ReadVarIntFromArchive (FArchive &Ar)
FORCEINLINE uint64 ReadVarUInt (const void *InData, uint32 &OutByteCount)
Read a variable-length unsigned integer.
uint64 ReadVarUIntFromArchive (FArchive &Ar)
void SerializeVarInt (FArchive &Ar, int64 &Value)
void SerializeVarUInt (FArchive &Ar, uint64 &Value)
FORCEINLINE uint32 WriteVarInt (int32 InValue, void *OutData)
Write a variable-length signed integer.
FORCEINLINE uint32 WriteVarInt (int64 InValue, void *OutData)
Write a variable-length signed integer.
void WriteVarIntToArchive (FArchive &Ar, int64 Value)
FORCEINLINE uint32 WriteVarUInt (uint32 InValue, void *OutData)
Write a variable-length unsigned integer.
FORCEINLINE uint32 WriteVarUInt (uint64 InValue, void *OutData)
Write a variable-length unsigned integer.
void WriteVarUIntToArchive (FArchive &Ar, uint64 Value)
Function Documentation
MeasureVarInt() [1/3]
FORCEINLINE uint32 MeasureVarInt (const void * InData)
Measure the length in bytes (1-9) of an encoded variable-length integer.
See also
MeasureVarUInt
Definition at line 67 of file VarInt.h.
References FORCEINLINE, and MeasureVarUInt().
MeasureVarInt() [2/3]
FORCEINLINE uint32 MeasureVarInt (int32 InValue)
Measure the number of bytes (1-5) required to encode the 32-bit input.
See also
MeasureVarUInt
Definition at line 85 of file VarInt.h.
References FORCEINLINE, and MeasureVarUInt().
MeasureVarInt() [3/3]
FORCEINLINE uint32 MeasureVarInt (int64 InValue)
Measure the number of bytes (1-9) required to encode the 64-bit input.
See also
MeasureVarUInt
Definition at line 91 of file VarInt.h.
References FORCEINLINE, and MeasureVarUInt().
MeasureVarUInt() [1/3]
FORCEINLINE uint32 MeasureVarUInt (const void * InData)
Measure the length in bytes (1-9) of an encoded variable-length integer.
Parameters
InData A variable-length encoding of an (signed or unsigned) integer.
Returns
The number of bytes used to encode the integer, in the range 1-9.
Definition at line 61 of file VarInt.h.
References FORCEINLINE.
Referenced by MeasureVarInt(), MeasureVarInt(), MeasureVarInt(), ReadVarUInt(), WriteVarUInt(), and WriteVarUInt().
MeasureVarUInt() [2/3]
FORCEINLINE uint32 MeasureVarUInt (uint32 InValue)
Measure the number of bytes (1-5) required to encode the 32-bit input.
Definition at line 73 of file VarInt.h.
References FORCEINLINE.
MeasureVarUInt() [3/3]
FORCEINLINE uint32 MeasureVarUInt (uint64 InValue)
Measure the number of bytes (1-9) required to encode the 64-bit input.
Definition at line 79 of file VarInt.h.
References FORCEINLINE.
ReadVarInt()
FORCEINLINE int64 ReadVarInt (const void * InData, uint32 & OutByteCount)
Read a variable-length signed integer.
Parameters
InData A variable-length encoding of a signed integer.
OutByteCount The number of bytes consumed from the input.
Returns
A signed integer.
Definition at line 132 of file VarInt.h.
References FORCEINLINE, ReadVarUInt(), and Value.
ReadVarIntFromArchive()
int64 ReadVarIntFromArchive (FArchive & Ar)
References Ar.
ReadVarUInt()
FORCEINLINE uint64 ReadVarUInt (const void * InData, uint32 & OutByteCount)
Read a variable-length unsigned integer.
Parameters
InData A variable-length encoding of an unsigned integer.
OutByteCount The number of bytes consumed from the input.
Returns
An unsigned integer.
Definition at line 103 of file VarInt.h.
References FORCEINLINE, MeasureVarUInt(), and Value.
Referenced by FCbValue::AsBinary(), FCbValue::AsCustomById(), FCbValue::AsCustomByName(), FCbValue::AsInteger(), FCbValue::AsIntegerNegative(), FCbValue::AsIntegerPositive(), FCbValue::AsString(), and ReadVarInt().
ReadVarUIntFromArchive()
uint64 ReadVarUIntFromArchive (FArchive & Ar)
References Ar.
SerializeVarInt()
void SerializeVarInt (FArchive & Ar, int64 & Value)
References Ar, and Value.
SerializeVarUInt()
void SerializeVarUInt (FArchive & Ar, uint64 & Value)
References Ar, and Value.
WriteVarInt() [1/2]
FORCEINLINE uint32 WriteVarInt (int32 InValue, void * OutData)
Write a variable-length signed integer.
See also
WriteVarUInt
Definition at line 189 of file VarInt.h.
References FORCEINLINE, Value, and WriteVarUInt().
WriteVarInt() [2/2]
FORCEINLINE uint32 WriteVarInt (int64 InValue, void * OutData)
Write a variable-length signed integer.
See also
WriteVarUInt
Definition at line 196 of file VarInt.h.
References FORCEINLINE, Value, and WriteVarUInt().
WriteVarIntToArchive()
void WriteVarIntToArchive (FArchive & Ar, int64 Value)
References Ar, and Value.
WriteVarUInt() [1/2]
FORCEINLINE uint32 WriteVarUInt (uint32 InValue, void * OutData)
Write a variable-length unsigned integer.
Parameters
InValue An unsigned integer to encode.
OutData A buffer of at least 5 bytes to write the output to.
Returns
The number of bytes used in the output.
Definition at line 145 of file VarInt.h.
References FORCEINLINE, and MeasureVarUInt().
Referenced by WriteVarInt(), and WriteVarInt().
WriteVarUInt() [2/2]
FORCEINLINE uint32 WriteVarUInt (uint64 InValue, void * OutData)
Write a variable-length unsigned integer.
Parameters
InValue An unsigned integer to encode.
OutData A buffer of at least 9 bytes to write the output to.
Returns
The number of bytes used in the output.
Definition at line 168 of file VarInt.h.
References FORCEINLINE, and MeasureVarUInt().
WriteVarUIntToArchive()
void WriteVarUIntToArchive (FArchive & Ar, uint64 Value)
References Ar, and Value.