Unreal Engine 5.6 C++ API: Runtime/Core/Public/Math/Vector4.h File Reference
Vector4.h File Reference
#include "CoreTypes.h"
#include "Misc/Crc.h"
#include "Math/MathFwd.h"
#include "Math/UnrealMathUtility.h"
#include "Containers/UnrealString.h"
#include "Misc/Parse.h"
#include "Misc/LargeWorldCoordinatesSerializer.h"
#include "Logging/LogMacros.h"
#include "Math/Vector2D.h"
#include "Math/Vector.h"
#include "Serialization/MemoryLayout.h"
#include "Templates/Requires.h"
#include <type_traits>
Data Structures
struct TCanBulkSerialize< FVector4d >
struct TCanBulkSerialize< FVector4f >
struct TIsPODType< FVector4d >
struct TIsPODType< FVector4f >
struct TIsUECoreVariant< FVector4d >
struct TIsUECoreVariant< FVector4f >
struct UE::Math::TVector4< T >
A 4D homogeneous vector, 4x1 FLOATs, 16-byte aligned.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Math
Implements an axis-aligned box.
Functions
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector4d)
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector4f)
template<typename T>
FORCEINLINE T Dot3 (const UE::Math::TVector4< T > &V1, const UE::Math::TVector4< T > &V2)
Calculates 3D Dot product of two 4D vectors.
template<typename T>
FORCEINLINE T Dot3 (const UE::Math::TVector4< T > &V1, const UE::Math::TVector< T > &V2)
Calculates 3D Dot product of one 4D vectors and one 3D vector.
template<typename T>
FORCEINLINE T Dot3 (const UE::Math::TVector< T > &V1, const UE::Math::TVector4< T > &V2)
template<typename T>
FORCEINLINE T Dot4 (const UE::Math::TVector4< T > &V1, const UE::Math::TVector4< T > &V2)
Calculates 4D Dot product.
template<typename T, typename T2 UE_REQUIRES>
FORCEINLINE TVector4< T > UE::Math::operator* (T2 Scale, const TVector4< T > &V)
Scales a vector.
FArchive & UE::Math::operator<< (FArchive &Ar, TVector4< double > &V)
FArchive & UE::Math::operator<< (FArchive &Ar, TVector4< float > &V)
Serializer.
UE_DECLARE_LWC_TYPE (Vector4)
Function Documentation
DECLARE_INTRINSIC_TYPE_LAYOUT() [1/2]
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector4d)
DECLARE_INTRINSIC_TYPE_LAYOUT() [2/2]
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector4f)
Dot3() [1/3]
template<typename T> FORCEINLINE T Dot3 (const UE::Math::TVector4< T > & V1, const UE::Math::TVector4< T > & V2)
Calculates 3D Dot product of two 4D vectors.
Parameters
V1 The first vector.
V2 The second vector.
Returns
The 3D Dot product.
Definition at line 1018 of file Vector4.h.
References FORCEINLINE, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Referenced by appLineCheckTriangle(), UE::Math::TVector4< T >::FindBestAxisVectors3(), FkDOPBuildCollisionTriangle< KDOP_IDX_TYPE >::GetLocalNormal(), and UE::Math::TVector4< T >::Reflect3().
Dot3() [2/3]
template<typename T> FORCEINLINE T Dot3 (const UE::Math::TVector4< T > & V1, const UE::Math::TVector< T > & V2)
Calculates 3D Dot product of one 4D vectors and one 3D vector.
Parameters
V1 The first vector.
V2 The second vector.
Returns
The 3D Dot product.
Definition at line 1033 of file Vector4.h.
References FORCEINLINE, UE::Math::TVector4< T >::X, UE::Math::TVector< T >::X, UE::Math::TVector4< T >::Y, UE::Math::TVector< T >::Y, UE::Math::TVector4< T >::Z, and UE::Math::TVector< T >::Z.
Dot3() [3/3]
template<typename T> FORCEINLINE T Dot3 (const UE::Math::TVector< T > & V1, const UE::Math::TVector4< T > & V2)
Definition at line 1039 of file Vector4.h.
References FORCEINLINE, UE::Math::TVector4< T >::X, UE::Math::TVector< T >::X, UE::Math::TVector4< T >::Y, UE::Math::TVector< T >::Y, UE::Math::TVector4< T >::Z, and UE::Math::TVector< T >::Z.
Dot4()
template<typename T> FORCEINLINE T Dot4 (const UE::Math::TVector4< T > & V1, const UE::Math::TVector4< T > & V2)
Calculates 4D Dot product.
Parameters
V1 The first vector.
V2 The second vector.
Returns
The 4D Dot Product.
Definition at line 1052 of file Vector4.h.
References FORCEINLINE, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
UE_DECLARE_LWC_TYPE()
UE_DECLARE_LWC_TYPE (Vector4)
References Vector4.