Unreal Engine 5.6 C++ API: Runtime/Core/Public/Math/Vector.h File Reference
Vector.h File Reference
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "Math/MathFwd.h"
#include "Math/NumericLimits.h"
#include "Misc/Crc.h"
#include "Math/UnrealMathUtility.h"
#include "Containers/UnrealString.h"
#include "Misc/Parse.h"
#include "Misc/LargeWorldCoordinatesSerializer.h"
#include "Misc/NetworkVersion.h"
#include "Math/Color.h"
#include "Math/IntPoint.h"
#include "Logging/LogMacros.h"
#include "Math/Vector2D.h"
#include "Misc/ByteSwap.h"
#include "Internationalization/Text.h"
#include "Internationalization/Internationalization.h"
#include "Math/IntVector.h"
#include "Math/Axis.h"
#include "Serialization/MemoryLayout.h"
#include "UObject/ObjectVersion.h"
#include <type_traits>
Data Structures
struct TCanBulkSerialize< FVector3d >
struct TCanBulkSerialize< FVector3f >
struct TIsPODType< FVector3d >
struct TIsPODType< FVector3f >
struct TIsUECoreVariant< FVector3d >
struct TIsUECoreVariant< FVector3f >
struct UE::Math::TVector< T >
A vector in 3-D space composed of components (X, Y, Z) with floating point precision.
struct UE::Math::TVectorConstInit
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::LWC
namespace UE::Math
Implements an axis-aligned box.
Functions
template<typename T>
FORCEINLINE UE::Math::TVector< T > ClampVector (const UE::Math::TVector< T > &V, const UE::Math::TVector< T > &Min, const UE::Math::TVector< T > &Max)
Component-wise clamp for TVector.
template<typename T, typename U>
FORCEINLINE T ComputeSquaredDistanceFromBoxToPoint (const UE::Math::TVector< T > &Mins, const UE::Math::TVector< T > &Maxs, const UE::Math::TVector< U > &Point)
Util to calculate distance from a point to a bounding box.
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector3d)
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector3f)
template<typename T>
FORCEINLINE uint32 UE::Math::GetTypeHash (const TVector< T > &Vector)
Creates a hash value from an FVector.
template<typename T>
static FORCEINLINE UE::Math::TVector< T > INTEL_ORDER_VECTOR (UE::Math::TVector< T > v)
FORCEINLINE FVector3f UE::LWC::NarrowWorldPositionChecked (const FVector &WorldPosition)
FORCEINLINE FVector3f UE::LWC::NarrowWorldPositionChecked (const FVector::FReal InX, const FVector::FReal InY, const FVector::FReal InZ)
template<typename T, typename T2 UE_REQUIRES>
FORCEINLINE TVector< T > UE::Math::operator* (T2 Scale, const TVector< T > &V)
Multiplies a vector by a scaling factor.
FArchive & UE::Math::operator<< (FArchive &Ar, TVector< double > &V)
Serializer for FVector3d.
FArchive & UE::Math::operator<< (FArchive &Ar, TVector< float > &V)
Serializer for FVector3f.
void UE::Math::operator<< (FStructuredArchive::FSlot Slot, TVector< double > &V)
Structured archive slot serializer for FVector3d.
void UE::Math::operator<< (FStructuredArchive::FSlot Slot, TVector< float > &V)
Structured archive slot serializer for FVector3f.
Variables
constexpr FVector::FReal UE::LWC::DefaultFloatPrecision = 1./16.
Function Documentation
ClampVector()
template<typename T> FORCEINLINE UE::Math::TVector< T > ClampVector (const UE::Math::TVector< T > & V, const UE::Math::TVector< T > & Min, const UE::Math::TVector< T > & Max)
Component-wise clamp for TVector.
Definition at line 2601 of file Vector.h.
References FMath::Clamp(), FORCEINLINE, Max, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
ComputeSquaredDistanceFromBoxToPoint()
template<typename T, typename U> FORCEINLINE T ComputeSquaredDistanceFromBoxToPoint (const UE::Math::TVector< T > & Mins, const UE::Math::TVector< T > & Maxs, const UE::Math::TVector< U > & Point)
Util to calculate distance from a point to a bounding box.
Parameters
Mins 3D Point defining the lower values of the axis of the bound box
Max 3D Point defining the lower values of the axis of the bound box
Point 3D position of interest
Returns
the distance from the Point to the bounding box.
Definition at line 2630 of file Vector.h.
References FORCEINLINE, Point, FMath::Square(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Math::TBox< double >::ComputeSquaredDistanceToPoint().
DECLARE_INTRINSIC_TYPE_LAYOUT() [1/2]
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector3d)
DECLARE_INTRINSIC_TYPE_LAYOUT() [2/2]
DECLARE_INTRINSIC_TYPE_LAYOUT (FVector3f)
INTEL_ORDER_VECTOR()
template<typename T> FORCEINLINE UE::Math::TVector< T > INTEL_ORDER_VECTOR (UE::Math::TVector< T > v) static
Definition at line 2614 of file Vector.h.
References FORCEINLINE, INTEL_ORDERF, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.