Unreal Engine 5.6 C++ API: Runtime/Engine/Public/WorldPartition/Filter/WorldPartitionActorFilter.h File Reference
WorldPartitionActorFilter.h File Reference
#include "CoreMinimal.h"
#include "Containers/Map.h"
#include "Misc/Guid.h"
#include "Misc/Optional.h"
#include "UObject/SoftObjectPath.h"
#include "WorldPartitionActorFilter.generated.h"
Enumerations
enum class EWorldPartitionActorFilterType : uint8 { None = 0 , Loading = 1 << 1 , Packing = 1 << 0 , All = Packing | Loading }
Functions
ENUM_CLASS_FLAGS (EWorldPartitionActorFilterType)
USTRUCT () struct FWorldPartitionActorFilter
Enumeration Type Documentation
EWorldPartitionActorFilterType
enum class EWorldPartitionActorFilterType : uint8 strong
Enumerator
None
Loading
Packing
All
Definition at line 12 of file WorldPartitionActorFilter.h.
Function Documentation
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EWorldPartitionActorFilterType)
USTRUCT()
USTRUCT ()
Definition at line 21 of file WorldPartitionActorFilter.h.
References Ar, Buffer, DECLARE_MULTICAST_DELEGATE, Filter, GENERATED_USTRUCT_BODY, operator!=(), operator<<(), operator=(), operator==(), Other, Override, Parent, and ToString().