Unreal Engine 5.6 C++ API: Runtime/Engine/Public/WorldPartition/WorldPartition.h File Reference
WorldPartition.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Misc/CoreDelegates.h"
#include "Misc/Optional.h"
#include "GameFramework/Actor.h"
#include "Templates/SubclassOf.h"
#include "UObject/LinkerInstancingContext.h"
#include "WorldPartition/WorldPartitionLog.h"
#include "WorldPartition/WorldPartitionActorDesc.h"
#include "WorldPartition/WorldPartitionStreamingSource.h"
#include "WorldPartition/WorldPartitionHandle.h"
#include "WorldPartition/ActorDescContainerInstanceCollection.h"
#include "WorldPartition/Cook/WorldPartitionCookPackageGenerator.h"
#include "WorldPartition/ActorDescContainerInstance.h"
#include "WorldPartition/WorldPartitionActorDescInstance.h"
#include "WorldPartition/WorldPartitionStreamingGeneration.h"
#include "WorldPartition/WorldPartitionActorLoaderInterface.h"
#include "WorldPartition/WorldPartitionEditorLoaderAdapter.h"
#include "WorldPartition/WorldPartitionRuntimeCellTransformer.h"
#include "ActorReferencesUtils.h"
#include "ExternalDirtyActorsTracker.h"
#include "PackageSourceControlHelper.h"
#include "CookPackageSplitter.h"
#include "Delegates/DelegateCombinations.h"
#include "WorldPartition.generated.h"
Data Structures
class ISourceControlHelper
struct IWorldPartitionEditor
Interface for the world partition editor.
Enumerations
enum class EWorldPartitionInitState { Uninitialized , Initializing , Initialized , Uninitializing }
Functions
UCLASS ()
USTRUCT () struct FRuntimeCellTransformerInstance
Holds an instance of a runtime cell transformer.
Enumeration Type Documentation
EWorldPartitionInitState
enum class EWorldPartitionInitState strong
Enumerator
Uninitialized
Initializing
Initialized
Uninitializing
Definition at line 62 of file WorldPartition.h.
Function Documentation
UCLASS()
UCLASS ()
References Actor, TArray< InElementType, InAllocatorType >::Add(), UObject::AddReferencedObjects(), Ar, AutoExpandCategories, UObject::BeginDestroy(), bool, UObject::CanEditChange(), Category, check, Container, DECLARE_DELEGATE_TwoParams, DECLARE_MULTICAST_DELEGATE_OneParam, DECLARE_MULTICAST_DELEGATE_TwoParams, FORCEINLINE, Forward(), FVector, IWorldPartitionCookPackageGenerator::GatherPackagesToCook(), GENERATED_UCLASS_BODY, TActorDescContainerInstanceCollection< TObjectPtr< UActorDescContainerInstance > >::GetActorDescContainerInstance(), IWorldPartitionCookPackageGenerator::GetCellForPackage(), GetTransientPackage(), Guid, INDEX_NONE, Initialize, IsInitialized, IsValid(), UE::Math::TBox< T >::IsValid, meta, MinimalAPI, NewObject, TActorDescContainerInstanceCollection< TObjectPtr< UActorDescContainerInstance > >::OnActorDescInstanceAdded(), TActorDescContainerInstanceCollection< TObjectPtr< UActorDescContainerInstance > >::OnActorDescInstanceRemoved(), UObject::OnCookEvent(), Package, PackageName, Params, Path, IWorldPartitionCookPackageGenerator::PopulateGeneratedPackageForCook(), IWorldPartitionCookPackageGenerator::PopulateGeneratorPackageForCook(), UObject::PostDuplicate(), UObject::PostEditChangeChainProperty(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, IWorldPartitionCookPackageGenerator::PrepareGeneratorPackageForCook(), PreSave, Replay, TArray< InElementType, InAllocatorType >::Reset(), UObject::ResolveSubobject(), UObject::Serialize(), SetTransform(), Transform, Transient, transient, UE_DEPRECATED, UFUNCTION, UPROPERTY, and verify.
USTRUCT()
USTRUCT ()
Holds an instance of a runtime cell transformer.
Definition at line 119 of file WorldPartition.h.
References Category, Class, GENERATED_USTRUCT_BODY, Instance, Meta, Transform, and UPROPERTY.