Unreal Engine 5.6 C++ API: ObjectHandle.h File Reference
ObjectHandle.h File Reference
#include "Containers/Map.h"
#include "Containers/ScriptArray.h"
#include "CoreTypes.h"
#include "HAL/CriticalSection.h"
#include "HAL/Platform.h"
#include "Misc/AssertionMacros.h"
#include "Templates/TypeHash.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectHandleTracking.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ObjectRef.h"
#include "UObject/PackedObjectRef.h"
#include "UObject/RemoteObject.h"
Data Structures
struct UE::CoreUObject::Private::FObjectDescriptorDebug
struct UE::CoreUObject::Private::FObjectHandleDataClassDescriptor
struct UE::CoreUObject::Private::FObjectHandlePackageDebugData
struct UE::CoreUObject::Private::FObjectPathIdDebug
struct UE::CoreUObject::Private::FStoredObjectPathDebug
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::CoreUObject
namespace UE::CoreUObject::Private
Typedefs
using FObjectHandle = UObject*
FObjectHandle is either a packed object ref or the resolved pointer to an object.
Functions
bool IsObjectHandleNull (FObjectHandle Handle)
bool IsObjectHandleResolved (FObjectHandle Handle)
bool IsObjectHandleResolved_ForGC (FObjectHandle Handle)
bool IsObjectHandleTypeSafe (FObjectHandle Handle)
FObjectHandle UE::CoreUObject::Private::MakeObjectHandle (UObject *Object)
these functions are always defined regardless of UE_WITH_OBJECT_HANDLE_LATE_RESOLVE value
UObject * UE::CoreUObject::Private::NoResolveObjectHandleNoRead (const FObjectHandle &Handle)
UObject * UE::CoreUObject::Private::ReadObjectHandlePointerNoCheck (FObjectHandle Handle)
Read the handle as a pointer without checking if it is resolved.
UObject * UE::CoreUObject::Private::ResolveObjectHandle (FObjectHandle &Handle)
UClass * UE::CoreUObject::Private::ResolveObjectHandleClass (FObjectHandle Handle)
UObject * UE::CoreUObject::Private::ResolveObjectHandleNoRead (FObjectHandle &Handle)
UObject * UE::CoreUObject::Private::ResolveObjectHandleNoReadNoCheck (FObjectHandle &Handle)
Resolves an ObjectHandle without checking if already resolved.
Variables
constexpr uint32 UE::CoreUObject::Private::ObjectIdShift = 2
constexpr uint32 UE::CoreUObject::Private::PackageIdMask = 0x3FFF'FFFF
constexpr uint32 UE::CoreUObject::Private::PackageIdShift = 34
constexpr uint32 UE::CoreUObject::Private::TypeIdShift = 1
Typedef Documentation
FObjectHandle
using FObjectHandle = UObject*
FObjectHandle is either a packed object ref or the resolved pointer to an object.
Depending on configuration when you create a handle, it may immediately be resolved to a pointer.
Definition at line 46 of file ObjectHandle.h.
Function Documentation
IsObjectHandleNull()
bool IsObjectHandleNull (FObjectHandle Handle) inline
Definition at line 132 of file ObjectHandle.h.
References Handle.
Referenced by IsObjectHandleResolved(), FObjectPtr::operator bool(), FObjectPtr::operator!(), and UE::CoreUObject::Private::ResolveObjectHandleNoRead().
IsObjectHandleResolved()
bool IsObjectHandleResolved (FObjectHandle Handle) inline
Definition at line 147 of file ObjectHandle.h.
References Handle, IsObjectHandleNull(), and UE::RemoteObject::Handle::IsRemote().
Referenced by FObjectPtr::IsResolved(), UE::CoreUObject::Private::ResolveObjectHandleClass(), and UE::CoreUObject::Private::ResolveObjectHandleNoRead().
IsObjectHandleResolved_ForGC()
bool IsObjectHandleResolved_ForGC (FObjectHandle Handle) inline
Definition at line 170 of file ObjectHandle.h.
References Handle.
Referenced by FReferenceCollector::AddReferencedObject(), UE::GC::TDirectDispatcher< ProcessorType >::HandleReferenceDirectly(), UE::CoreUObject::Private::NoResolveObjectHandleNoRead(), and UE::CoreUObject::Private::ResolveObjectHandleNoReadNoCheck().
IsObjectHandleTypeSafe()
bool IsObjectHandleTypeSafe (FObjectHandle Handle) inline
Definition at line 184 of file ObjectHandle.h.
References Handle.
Referenced by UE::CoreUObject::Private::ResolveObjectHandleNoRead(), and UE::CoreUObject::Private::ResolveObjectHandleNoReadNoCheck().