Unreal Engine 5.6 C++ API: Metasound::Frontend::IDocumentCache Class Reference
Metasound::Frontend::IDocumentCache Class Reference abstract
Interface for querying cached document dependencies.
#include "MetasoundFrontendDocumentCacheInterface.h"
Public Member Functions
virtual ~IDocumentCache ()=default
virtual bool ContainsDependency (const FNodeRegistryKey &InClassKey) const =0
virtual bool ContainsDependencyOfType (EMetasoundFrontendClassType ClassType) const =0
virtual const FMetasoundFrontendClass * FindDependency (const FGuid &InClassID) const =0
virtual const FMetasoundFrontendClass * FindDependency (const Metasound::Frontend::FNodeRegistryKey &InClassKey) const =0
virtual const int32 * FindDependencyIndex (const FGuid &InClassID) const =0
virtual const int32 * FindDependencyIndex (const Metasound::Frontend::FNodeRegistryKey &InClassKey) const =0
virtual const FMetasoundFrontendDocument & GetDocument () const =0
virtual const IDocumentGraphEdgeCache & GetEdgeCache (const FGuid &InPageID) const =0
virtual const IDocumentGraphInterfaceCache & GetInterfaceCache () const =0
virtual const IDocumentGraphNodeCache & GetNodeCache (const FGuid &InPageID) const =0
UE_DEPRECATED (5.5, "Use overload providing pageID") virtual const IDocumentGraphEdgeCache &GetEdgeCache() const
UE_DEPRECATED (5.5, "Use overload providing pageID") virtual const IDocumentGraphNodeCache &GetNodeCache() const
Public Member Functions inherited from TSharedFromThis< IDocumentCache >
TSharedRef< IDocumentCache, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDocumentCache, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IDocumentCache >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IDocumentCache >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Interface for querying cached document dependencies.
Definition at line 97 of file MetasoundFrontendDocumentCacheInterface.h.
Constructor & Destructor Documentation
~IDocumentCache()
virtual Metasound::Frontend::IDocumentCache::~IDocumentCache () virtual default
Member Function Documentation
ContainsDependency()
virtual bool Metasound::Frontend::IDocumentCache::ContainsDependency (const FNodeRegistryKey & InClassKey) const pure virtual
ContainsDependencyOfType()
virtual bool Metasound::Frontend::IDocumentCache::ContainsDependencyOfType (EMetasoundFrontendClassType ClassType) const pure virtual
FindDependency() [1/2]
virtual const FMetasoundFrontendClass * Metasound::Frontend::IDocumentCache::FindDependency (const FGuid & InClassID) const pure virtual
FindDependency() [2/2]
virtual const FMetasoundFrontendClass * Metasound::Frontend::IDocumentCache::FindDependency (const Metasound::Frontend::FNodeRegistryKey & InClassKey) const pure virtual
FindDependencyIndex() [1/2]
virtual const int32 * Metasound::Frontend::IDocumentCache::FindDependencyIndex (const FGuid & InClassID) const pure virtual
FindDependencyIndex() [2/2]
virtual const int32 * Metasound::Frontend::IDocumentCache::FindDependencyIndex (const Metasound::Frontend::FNodeRegistryKey & InClassKey) const pure virtual
GetDocument()
virtual const FMetasoundFrontendDocument & Metasound::Frontend::IDocumentCache::GetDocument () const pure virtual
GetEdgeCache()
virtual const IDocumentGraphEdgeCache & Metasound::Frontend::IDocumentCache::GetEdgeCache (const FGuid & InPageID) const pure virtual
Referenced by UE_DEPRECATED().
GetInterfaceCache()
virtual const IDocumentGraphInterfaceCache & Metasound::Frontend::IDocumentCache::GetInterfaceCache () const pure virtual
GetNodeCache()
virtual const IDocumentGraphNodeCache & Metasound::Frontend::IDocumentCache::GetNodeCache (const FGuid & InPageID) const pure virtual
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/2]
Metasound::Frontend::IDocumentCache::UE_DEPRECATED (5. 5, "Use overload providing pageID") const & inline
Definition at line 117 of file MetasoundFrontendDocumentCacheInterface.h.
References Metasound::Frontend::DefaultPageID(), and GetEdgeCache().
UE_DEPRECATED() [2/2]
Metasound::Frontend::IDocumentCache::UE_DEPRECATED (5. 5, "Use overload providing pageID") const & inline
Definition at line 111 of file MetasoundFrontendDocumentCacheInterface.h.
References Metasound::Frontend::DefaultPageID(), and GetNodeCache().
The documentation for this class was generated from the following file:
MetasoundFrontendDocumentCacheInterface.h