Unreal Engine 5.6 C++ API: FGameplayTagQueryExpression Struct Reference
FGameplayTagQueryExpression Struct Reference
#include "GameplayTagContainer.h"
Public Member Functions
FGameplayTagQueryExpression & AddExpr (FGameplayTagQueryExpression &Expr)
FGameplayTagQueryExpression & AddTag (FGameplayTag Tag)
GAMEPLAYTAGS_API FGameplayTagQueryExpression & AddTag (FName TagName)
FGameplayTagQueryExpression & AddTag (TCHAR const *TagString)
FGameplayTagQueryExpression & AddTags (FGameplayTagContainer const &Tags)
FGameplayTagQueryExpression & AllExprMatch ()
FGameplayTagQueryExpression & AllTagsMatch ()
FGameplayTagQueryExpression & AnyExprMatch ()
FGameplayTagQueryExpression & AnyTagsMatch ()
Fluid syntax approach for setting the type of this expression.
GAMEPLAYTAGS_API bool ConvertToJsonObject (TSharedRef< FJsonObject > &OutObject) const
Converts the existing TagQueryExpression into a json object.
GAMEPLAYTAGS_API void EmitTokens (TArray< uint8 > &TokenStream, TArray< FGameplayTag > &TagDictionary) const
Writes this expression to the given token stream.
FGameplayTagQueryExpression & NoExprMatch ()
FGameplayTagQueryExpression & NoTagsMatch ()
FORCEINLINE bool UsesExprSet () const
Returns true if this expression uses the expression list data.
FORCEINLINE bool UsesTagSet () const
Returns true if this expression uses the tag data.
Static Public Member Functions
static GAMEPLAYTAGS_API bool MakeFromJsonObject (const TSharedRef< FJsonObject > &InObject, FGameplayTagQueryExpression &OutQueryExpression)
Uses the input json object and fills out the OutQueryExpression with the data.
Data Fields
TArray< struct FGameplayTagQueryExpression > ExprSet
Expression list, for expression types that need it.
EGameplayTagQueryExprType ExprType
Which type of expression this is.
TArray< FGameplayTag > TagSet
Tag list, for expression types that need it.
Detailed Description
Definition at line 934 of file GameplayTagContainer.h.
Member Function Documentation
AddExpr()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AddExpr (FGameplayTagQueryExpression & Expr) inline
Definition at line 995 of file GameplayTagContainer.h.
References ensure, ExprSet, and UsesExprSet().
AddTag() [1/3]
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AddTag (FGameplayTag Tag) inline
Definition at line 981 of file GameplayTagContainer.h.
References ensure, TagSet, and UsesTagSet().
AddTag() [2/3]
GAMEPLAYTAGS_API FGameplayTagQueryExpression & FGameplayTagQueryExpression::AddTag (FName TagName)
AddTag() [3/3]
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AddTag (TCHAR const * TagString) inline
Definition at line 976 of file GameplayTagContainer.h.
References AddTag(), and FName.
Referenced by AddTag().
AddTags()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AddTags (FGameplayTagContainer const & Tags) inline
Definition at line 988 of file GameplayTagContainer.h.
References ensure, Tags, TagSet, and UsesTagSet().
AllExprMatch()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AllExprMatch () inline
Definition at line 964 of file GameplayTagContainer.h.
References ExprType.
AllTagsMatch()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AllTagsMatch () inline
Definition at line 946 of file GameplayTagContainer.h.
References ExprType.
AnyExprMatch()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AnyExprMatch () inline
Definition at line 958 of file GameplayTagContainer.h.
References ExprType.
AnyTagsMatch()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::AnyTagsMatch () inline
Fluid syntax approach for setting the type of this expression.
Definition at line 940 of file GameplayTagContainer.h.
References ExprType.
ConvertToJsonObject()
GAMEPLAYTAGS_API bool FGameplayTagQueryExpression::ConvertToJsonObject (TSharedRef< FJsonObject > & OutObject) const
Converts the existing TagQueryExpression into a json object.
Returns true on success
EmitTokens()
GAMEPLAYTAGS_API void FGameplayTagQueryExpression::EmitTokens (TArray< uint8 > & TokenStream, TArray< FGameplayTag > & TagDictionary) const
Writes this expression to the given token stream.
MakeFromJsonObject()
GAMEPLAYTAGS_API bool FGameplayTagQueryExpression::MakeFromJsonObject (const TSharedRef< FJsonObject > & InObject, FGameplayTagQueryExpression & OutQueryExpression) static
Uses the input json object and fills out the OutQueryExpression with the data.
NoExprMatch()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::NoExprMatch () inline
Definition at line 970 of file GameplayTagContainer.h.
References ExprType.
NoTagsMatch()
FGameplayTagQueryExpression & FGameplayTagQueryExpression::NoTagsMatch () inline
Definition at line 952 of file GameplayTagContainer.h.
References ExprType.
UsesExprSet()
FORCEINLINE bool FGameplayTagQueryExpression::UsesExprSet () const inline
Returns true if this expression uses the expression list data.
Definition at line 1020 of file GameplayTagContainer.h.
References ExprType, and FORCEINLINE.
Referenced by AddExpr().
UsesTagSet()
FORCEINLINE bool FGameplayTagQueryExpression::UsesTagSet () const inline
Returns true if this expression uses the tag data.
Definition at line 1015 of file GameplayTagContainer.h.
References ExprType, and FORCEINLINE.
Referenced by AddTag(), and AddTags().
Field Documentation
ExprSet
TArray<struct FGameplayTagQueryExpression> FGameplayTagQueryExpression::ExprSet
Expression list, for expression types that need it.
Definition at line 1009 of file GameplayTagContainer.h.
Referenced by AddExpr().
ExprType
EGameplayTagQueryExprType FGameplayTagQueryExpression::ExprType
Which type of expression this is.
Definition at line 1006 of file GameplayTagContainer.h.
Referenced by AllExprMatch(), AllTagsMatch(), AnyExprMatch(), AnyTagsMatch(), NoExprMatch(), NoTagsMatch(), UsesExprSet(), and UsesTagSet().
TagSet
TArray<FGameplayTag> FGameplayTagQueryExpression::TagSet
Tag list, for expression types that need it.
Definition at line 1012 of file GameplayTagContainer.h.
Referenced by AddTag(), and AddTags().
The documentation for this struct was generated from the following file:
GameplayTagContainer.h