Unreal Engine 5.6 C++ API: FGPUSortManager Class Reference
FGPUSortManager Class Reference
A manager that handles different GPU sort tasks.
#include "GPUSortManager.h"
Data Structures
struct FAllocationInfo
Information about the bindings for a given sort task.
struct FCallbackInfo
Holds data relative to client systems of the GPU sort manager.
struct FDynamicValueBuffer
Encapsulates the idea of a growable FValueBuffer, that dynamically change in size depending on requirements.
struct FKeyGenInfo
A little helper to generate the batch element keys based on the number of elements in the batch and the sort precision.
struct FSettings
Different settings used to manage the buffer allocations.
struct FSortBatch
Defines a sort batch that regroups several sort tasks created by FGPUSortManager::AddTask(), becoming sort the batch elements.
class FValueBuffer
A vertex buffer owning the final sorted values.
Public Member Functions
FGPUSortManager (ERHIFeatureLevel::Type InFeatureLevel)
Creates the sort manager, this is when the settings are configured.
~FGPUSortManager ()
bool AddTask (FRHICommandListBase &RHICmdList, FAllocationInfo &OutInfo, int32 ValueCount, EGPUSortFlags TaskFlags)
Add a GPU sort task to process this frame.
DECLARE_EVENT_OneParam (FGPUSortManager, FPostPostRenderEvent, FRHICommandListImmediate &)
Event to register and receive post-postrender notification.
DECLARE_EVENT_OneParam (FGPUSortManager, FPostPreRenderEvent, FRHICommandListImmediate &)
Event to register and receive post-prerender notification.
void OnPostRenderOpaque (class FRDGBuilder &GraphBuilder)
Callback that needs to be called in the rendering loop, after calls to FFXSystemInterface::PostRenderOpaque() are issued.
void OnPreRender (class FRDGBuilder &GraphBuilder)
Callback that needs to be called in the rendering loop, after calls to FFXSystemInterface::PreRender() are issued.
void Register (const FGPUSortKeyGenDelegate &CallbackDelegate, EGPUSortFlags UsedFlags, const FName &InName)
Register a client system into the sort manager.
UE_DEPRECATED (5.4, "AddTask now requires a command list.") 1 bool AddTask(FAllocationInfo &OutInfo
Public Member Functions inherited from FRefCountedObject
FRefCountedObject ()
FRefCountedObject (const FRefCountedObject &Rhs)=delete
virtual ~FRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountedObject & operator= (const FRefCountedObject &Rhs)=delete
uint32 Release () const
Data Fields
FPostPreRenderEvent PostPostRenderEvent
FPostPreRenderEvent PostPreRenderEvent
int32 EGPUSortFlags TaskFlags
int32 ValueCount
Private Types
enum class ESortBatchProcessingOrder : uint32 { Undefined = 0 , KeyGenAndSortAfterPreRender = 1 , KeyGenAfterPreRenderAndSortAfterPostRenderOpaque = 2 , KeyGenAndSortAfterPostRenderOpaque = 3 }
Defines the order in which sort batches are processed every frame.
typedef TArray< FCallbackInfo > FCallbackArray
typedef TIndirectArray< FDynamicValueBuffer, TInlineAllocator< 4 > > FDynamicValueBufferArray
typedef TArray< FSortBatch, TInlineAllocator< 4 > > FSortBatchArray
Expected that few will be enough, since we only need severals batches when ESortBatchProcessingOrder::KeyGenAfterPreRenderAndSortAfterPostRenderOpaque.
typedef TIndirectArray< FValueBuffer, TInlineAllocator< 4 > > FValueBufferArray
Private Member Functions
void FinalizeSortBatches ()
Setup the final sort flags and the processing order of all batches.
FDynamicValueBuffer * GetDynamicValueBufferFromPool (EGPUSortFlags TaskFlags, int32 SortBatchId)
Find an unused buffer to assign to a newly created FSortBatch.
void ReleaseSortBuffers ()
Delete all GPU sort buffers.
void ResetDynamicValuesBuffers (FRHICommandListBase &RHICmdList)
Resize (shrink) the DynamicValueBuffers and free the unused ones.
void UpdateSortBuffersPool (FRHICommandListBase &RHICmdList)
Make sure there is enough GPU sort buffers to satisfy all batches created this frame.
Static Private Member Functions
static FORCEINLINE EGPUSortFlags CombineBatchFlags (EGPUSortFlags BatchFlags, EGPUSortFlags TaskFlags)
Update a batch flags after adding a task into it.
static FORCEINLINE EGPUSortFlags GetBatchFlags (EGPUSortFlags TaskFlags)
Create the initial batch flags from a task flags.
static FORCEINLINE auto GetPrecisionString (EGPUSortFlags BatchFlags) -> TCHAR const(&)[1]
Convert the precision flags into a string, used for GPU markers.
static FORCEINLINE bool HasEither (EGPUSortFlags Flags, EGPUSortFlags A, EGPUSortFlags B)
A helper to test that a flag has one and exactly one of A or B.
static FORCEINLINE bool TestBatchFlags (EGPUSortFlags BatchFlags, EGPUSortFlags TaskFlags)
Test whether a batch flags are compatible with a given task.
Private Attributes
FCallbackArray Callbacks
The client system callbacks, see Register().
FDynamicValueBufferArray DynamicValueBufferPool
A pool of buffer to hold the final sorted values for each batch.
ERHIFeatureLevel::Type FeatureLevel
The current feature level, needed to access the global shader map.
FSettings Settings
Settings to handle the buffer reallocation strategy.
FSortBatchArray SortBatches
The different batches that will be used this frame, each one ending up being sorting work on the GPU.
TArray< FParticleSortBuffers *, TInlineAllocator< 2 > > SortBuffersPool
A pool of GPU sort buffers.
Detailed Description
A manager that handles different GPU sort tasks.
Each task has different constraints about when the data can be generated and when the sorted results need to be available. The usecase involes registering a sort task through AddTask() and then initializing the sort data through the KeyGen callback. The sort manager can be enabled or disabled through "fx.AllowGPUSorting"
Definition at line 166 of file GPUSortManager.h.
Member Typedef Documentation
FCallbackArray
typedef TArray<FCallbackInfo> FGPUSortManager::FCallbackArray private
Definition at line 212 of file GPUSortManager.h.
FDynamicValueBufferArray
typedef TIndirectArray<FDynamicValueBuffer, TInlineAllocator<4> > FGPUSortManager::FDynamicValueBufferArray private
Definition at line 322 of file GPUSortManager.h.
FSortBatchArray
typedef TArray<FSortBatch, TInlineAllocator<4> > FGPUSortManager::FSortBatchArray private
Expected that few will be enough, since we only need severals batches when ESortBatchProcessingOrder::KeyGenAfterPreRenderAndSortAfterPostRenderOpaque.
Definition at line 395 of file GPUSortManager.h.
FValueBufferArray
typedef TIndirectArray<FValueBuffer, TInlineAllocator<4> > FGPUSortManager::FValueBufferArray private
Definition at line 271 of file GPUSortManager.h.
Member Enumeration Documentation
ESortBatchProcessingOrder
enum class FGPUSortManager::ESortBatchProcessingOrder : uint32 strong private
Defines the order in which sort batches are processed every frame.
KeyGenAfterPreRenderAndSortAfterPostRenderOpaque is the most complex case since the KeyGen is called after PreRendeR() while the sort only happens after PostRenderOpaque(). This creates a situation where the FParticleSortBuffers need to be keep bound to the batch and can not be reused by other batches with this processing order. Note also that KeyGenAfterPreRenderAndSortAfterPostRenderOpaque could include KeyGen after PostRenderOpaque().
Enumerator
Undefined
KeyGenAndSortAfterPreRender
KeyGenAfterPreRenderAndSortAfterPostRenderOpaque
KeyGenAndSortAfterPostRenderOpaque
Definition at line 332 of file GPUSortManager.h.
Constructor & Destructor Documentation
FGPUSortManager()
FGPUSortManager::FGPUSortManager (ERHIFeatureLevel::Type InFeatureLevel)
Creates the sort manager, this is when the settings are configured.
Referenced by DECLARE_EVENT_OneParam(), and DECLARE_EVENT_OneParam().
~FGPUSortManager()
FGPUSortManager::~FGPUSortManager ()
Member Function Documentation
AddTask()
bool FGPUSortManager::AddTask (FRHICommandListBase & RHICmdList, FAllocationInfo & OutInfo, int32 ValueCount, EGPUSortFlags TaskFlags)
Add a GPU sort task to process this frame.
Tasks are expected to be created before OnPreRender() gets called.
Parameters
OutInfo - The details about the allocation bindings, if success.
IndexCount - The number of values that need to be sorted by this task.
SortFlags - The sort task requirements.
Return true if the task was added to a batch, false otherwise, could be because GPU sorting is disabled.
References int32, TaskFlags, and ValueCount.
CombineBatchFlags()
FORCEINLINE EGPUSortFlags FGPUSortManager::CombineBatchFlags (EGPUSortFlags BatchFlags, EGPUSortFlags TaskFlags) static private
Update a batch flags after adding a task into it.
References CombineBatchFlags(), FORCEINLINE, and TaskFlags.
Referenced by CombineBatchFlags().
DECLARE_EVENT_OneParam() [1/2]
FGPUSortManager::DECLARE_EVENT_OneParam (FGPUSortManager , FPostPostRenderEvent , FRHICommandListImmediate &)
Event to register and receive post-postrender notification.
References FGPUSortManager(), and DECLARE_EVENT_OneParam().
DECLARE_EVENT_OneParam() [2/2]
FGPUSortManager::DECLARE_EVENT_OneParam (FGPUSortManager , FPostPreRenderEvent , FRHICommandListImmediate &)
Event to register and receive post-prerender notification.
References FGPUSortManager(), and DECLARE_EVENT_OneParam().
Referenced by DECLARE_EVENT_OneParam(), and DECLARE_EVENT_OneParam().
FinalizeSortBatches()
void FGPUSortManager::FinalizeSortBatches () private
Setup the final sort flags and the processing order of all batches.
Called after no other tasks will be added this frame.
References FinalizeSortBatches().
Referenced by FinalizeSortBatches().
GetBatchFlags()
FORCEINLINE EGPUSortFlags FGPUSortManager::GetBatchFlags (EGPUSortFlags TaskFlags) static private
Create the initial batch flags from a task flags.
References FORCEINLINE, GetBatchFlags(), and TaskFlags.
Referenced by GetBatchFlags().
GetDynamicValueBufferFromPool()
FDynamicValueBuffer * FGPUSortManager::GetDynamicValueBufferFromPool (EGPUSortFlags TaskFlags, int32 SortBatchId) private
Find an unused buffer to assign to a newly created FSortBatch.
Although the sort batches are recreated every frame depending on what is being visible, the buffers used to sort the indices and store the sorted results are persistent to some extent (see FBufferAllocationSettings which define the allocation and lifetime strategy).
Each persistent buffer being assigned to one frame batch, we try to rebind the same buffers to the same batches by using the constraints being imposed on the batch through the sortflags. The reason to do so is that the allocation strategy for the buffer is meant to be optimal if the required buffer size is consistent between frames. (the batch flags are linked to the emitters being grouped into it, and so is the batch sorted indices count)
Parameters
TaskFlags - Some constraints being applied to the batch, using to help match the same buffers to the same batches between frames.
SortBatchId - The newly created batch index which will use the buffer this frame.
Return a buffer to store the sorted particle indices.
References GetDynamicValueBufferFromPool(), int32, and TaskFlags.
Referenced by GetDynamicValueBufferFromPool().
GetPrecisionString()
FORCEINLINE auto FGPUSortManager::GetPrecisionString (EGPUSortFlags BatchFlags) -> TCHAR const(&)[1] static private
Convert the precision flags into a string, used for GPU markers.
References FORCEINLINE, and GetPrecisionString().
Referenced by GetPrecisionString().
HasEither()
FORCEINLINE bool FGPUSortManager::HasEither (EGPUSortFlags Flags, EGPUSortFlags A, EGPUSortFlags B) static private
A helper to test that a flag has one and exactly one of A or B.
References A, B, Flags, FORCEINLINE, and HasEither().
Referenced by HasEither().
OnPostRenderOpaque()
void FGPUSortManager::OnPostRenderOpaque (class FRDGBuilder & GraphBuilder)
Callback that needs to be called in the rendering loop, after calls to FFXSystemInterface::PostRenderOpaque() are issued.
Tasks with EGPUSortFlags::KeyGenAfterPostRenderOpaque get their client callbacks issued to set the initial keys and values. After this any sort task that hasn't been processed yet, in OnPreRender(), gets processed now.
Parameters
RHICmdList - The command list to be used.
References OnPostRenderOpaque().
Referenced by OnPostRenderOpaque().
OnPreRender()
void FGPUSortManager::OnPreRender (class FRDGBuilder & GraphBuilder)
Callback that needs to be called in the rendering loop, after calls to FFXSystemInterface::PreRender() are issued.
At this point, no other GPU sort tasks are allowed to be created through AddTask() as the sort batches get finalized. At this point, any task with the EGPUSortFlags::SortAfterPreRender will possibly be done, unless it also had the EGPUSortFlags::SortAfterPostRenderOpaque flag. Tasks with EGPUSortFlags::KeyGenAfterPreRender get their client callbacks issued to set the initial keys and values.
Parameters
RHICmdList - The command list to be used.
References OnPreRender().
Referenced by OnPreRender().
Register()
void FGPUSortManager::Register (const FGPUSortKeyGenDelegate & CallbackDelegate, EGPUSortFlags UsedFlags, const FName & InName)
Register a client system into the sort manager.
Client systems are systems that will call AddTask(). Those systems need to register a callback, the possible used flags for their tasks and a name. The callback is required because the initial content to perform GPU sorts is only configured long after AddTask() gets called in the rendering loop.
Parameters
CallbackDelegate - The callback that will be used to set the initial keys and values for each batch elements.
UsedFlags - The possibly used flags for each of the client system tasks, used to perform some optimizations.
InName - A name defining this client system, used for GPU markers.
References InName.
ReleaseSortBuffers()
void FGPUSortManager::ReleaseSortBuffers () private
Delete all GPU sort buffers.
References ReleaseSortBuffers().
Referenced by ReleaseSortBuffers().
ResetDynamicValuesBuffers()
void FGPUSortManager::ResetDynamicValuesBuffers (FRHICommandListBase & RHICmdList) private
Resize (shrink) the DynamicValueBuffers and free the unused ones.
References ResetDynamicValuesBuffers().
Referenced by ResetDynamicValuesBuffers().
TestBatchFlags()
FORCEINLINE bool FGPUSortManager::TestBatchFlags (EGPUSortFlags BatchFlags, EGPUSortFlags TaskFlags) static private
Test whether a batch flags are compatible with a given task.
Used to know if the task can be merged in the batch.
References FORCEINLINE, TaskFlags, and TestBatchFlags().
Referenced by TestBatchFlags().
UE_DEPRECATED()
FGPUSortManager::UE_DEPRECATED (5. 4, "AddTask now requires a command list.") &
UpdateSortBuffersPool()
void FGPUSortManager::UpdateSortBuffersPool (FRHICommandListBase & RHICmdList) private
Make sure there is enough GPU sort buffers to satisfy all batches created this frame.
Free one used ones.
References UpdateSortBuffersPool().
Referenced by UpdateSortBuffersPool().
Field Documentation
Callbacks
FCallbackArray FGPUSortManager::Callbacks private
The client system callbacks, see Register().
Definition at line 519 of file GPUSortManager.h.
DynamicValueBufferPool
FDynamicValueBufferArray FGPUSortManager::DynamicValueBufferPool private
A pool of buffer to hold the final sorted values for each batch.
Reused between frames.
Definition at line 513 of file GPUSortManager.h.
FeatureLevel
ERHIFeatureLevel::Type FGPUSortManager::FeatureLevel private
The current feature level, needed to access the global shader map.
Definition at line 522 of file GPUSortManager.h.
PostPostRenderEvent
FPostPreRenderEvent FGPUSortManager::PostPostRenderEvent
Definition at line 460 of file GPUSortManager.h.
PostPreRenderEvent
FPostPreRenderEvent FGPUSortManager::PostPreRenderEvent
Definition at line 454 of file GPUSortManager.h.
Settings
FSettings FGPUSortManager::Settings private
Settings to handle the buffer reallocation strategy.
Definition at line 510 of file GPUSortManager.h.
SortBatches
FSortBatchArray FGPUSortManager::SortBatches private
The different batches that will be used this frame, each one ending up being sorting work on the GPU.
In many cases, there will only be one batch but some cases makes it possible to have 2 or more (for example when different key precision are used).
Definition at line 507 of file GPUSortManager.h.
SortBuffersPool
TArray<FParticleSortBuffers*, TInlineAllocator<2> > FGPUSortManager::SortBuffersPool private
A pool of GPU sort buffers.
The same sort GPU buffer can normally be used in several sort batches.
Definition at line 516 of file GPUSortManager.h.
TaskFlags
int32 EGPUSortFlags FGPUSortManager::TaskFlags
Definition at line 428 of file GPUSortManager.h.
Referenced by AddTask(), CombineBatchFlags(), GetBatchFlags(), GetDynamicValueBufferFromPool(), and TestBatchFlags().
ValueCount
int32 FGPUSortManager::ValueCount
Definition at line 428 of file GPUSortManager.h.
Referenced by AddTask(), FGPUSortManager::FDynamicValueBuffer::Allocate(), and FGPUSortManager::FValueBuffer::Allocate().
The documentation for this class was generated from the following file:
GPUSortManager.h