Unreal Engine 5.6 C++ API: ISequencerObjectChangeListener Class Reference
ISequencerObjectChangeListener Class Reference abstract
Listens for changes objects and calls delegates when those objects change.
#include "ISequencerObjectChangeListener.h"
Public Member Functions
virtual bool CanKeyProperty (FCanKeyPropertyParams KeyPropertyParams, FPropertyPath &OutPropertyPath) const =0
virtual FOnAnimatablePropertyChanged & GetOnAnimatablePropertyChanged (const FProperty *Property)=0
A delegate for when a property of a specific path is changed.
virtual FOnAnimatablePropertyChanged & GetOnAnimatablePropertyChanged (FAnimatedPropertyKey PropertyKey)=0
A delegate for when a property of a specific FProperty class is changed.
virtual FOnObjectPropertyChanged & GetOnAnyPropertyChanged (UObject &Object)=0
A delegate for when any property of a specific object is changed.
virtual FOnPropagateObjectChanges & GetOnPropagateObjectChanges ()=0
A delegate for when object changes should be propagated to/from puppet actors.
virtual void KeyProperty (FKeyPropertyParams KeyPropertyParams) const =0
virtual void ReportObjectDestroyed (UObject &Object)=0
Report that an object is about to be destroyed (removes any object change delegates bound to the object)
virtual void TriggerAllPropertiesChanged (UObject *Object)=0
Triggers all properties as changed for the passed in object.
UE_DEPRECATED (5.4, "CanKeyProperty taking in only FCanKeyPropertyParams is deprecated. Please use the alternative CanKeyProperty that takes in FCanKeyPropertyParams and an out FPropertyPath.") virtual bool CanKeyProperty(FCanKeyPropertyParams KeyPropertyParams) const =0
Detailed Description
Listens for changes objects and calls delegates when those objects change.
Definition at line 18 of file ISequencerObjectChangeListener.h.
Member Function Documentation
CanKeyProperty()
virtual bool ISequencerObjectChangeListener::CanKeyProperty (FCanKeyPropertyParams KeyPropertyParams, FPropertyPath & OutPropertyPath) const pure virtual
References CanKeyProperty().
Referenced by CanKeyProperty(), and UE_DEPRECATED().
GetOnAnimatablePropertyChanged() [1/2]
virtual FOnAnimatablePropertyChanged & ISequencerObjectChangeListener::GetOnAnimatablePropertyChanged (const FProperty * Property) pure virtual
A delegate for when a property of a specific path is changed.
References Property.
GetOnAnimatablePropertyChanged() [2/2]
virtual FOnAnimatablePropertyChanged & ISequencerObjectChangeListener::GetOnAnimatablePropertyChanged (FAnimatedPropertyKey PropertyKey) pure virtual
A delegate for when a property of a specific FProperty class is changed.
Referenced by FPropertyTrackEditor< TrackType >::~FPropertyTrackEditor(), and FPropertyTrackEditor< TrackType >::AddWatchedProperty().
GetOnAnyPropertyChanged()
virtual FOnObjectPropertyChanged & ISequencerObjectChangeListener::GetOnAnyPropertyChanged (UObject & Object) pure virtual
A delegate for when any property of a specific object is changed.
References Object.
GetOnPropagateObjectChanges()
virtual FOnPropagateObjectChanges & ISequencerObjectChangeListener::GetOnPropagateObjectChanges () pure virtual
A delegate for when object changes should be propagated to/from puppet actors.
KeyProperty()
virtual void ISequencerObjectChangeListener::KeyProperty (FKeyPropertyParams KeyPropertyParams) const pure virtual
References KeyProperty().
Referenced by KeyProperty().
ReportObjectDestroyed()
virtual void ISequencerObjectChangeListener::ReportObjectDestroyed (UObject & Object) pure virtual
Report that an object is about to be destroyed (removes any object change delegates bound to the object)
References Object.
TriggerAllPropertiesChanged()
virtual void ISequencerObjectChangeListener::TriggerAllPropertiesChanged (UObject * Object) pure virtual
Triggers all properties as changed for the passed in object.
References Object.
UE_DEPRECATED()
ISequencerObjectChangeListener::UE_DEPRECATED (5. 4, "CanKeyProperty taking in only FCanKeyPropertyParams is deprecated. Please use the alternative CanKeyProperty that takes in FCanKeyPropertyParams and an out FPropertyPath.") const pure virtual
References CanKeyProperty().
The documentation for this class was generated from the following file:
ISequencerObjectChangeListener.h