Unreal Engine 5.6 C++ API: FWholeSceneProjectedShadowInitializer Class Reference
FWholeSceneProjectedShadowInitializer Class Reference
Information needed to create a whole scene projected shadow.
#include "SceneManagement.h"
Public Member Functions
FWholeSceneProjectedShadowInitializer ()
bool IsCachedShadowValid (const FWholeSceneProjectedShadowInitializer &CachedShadow) const
Public Member Functions inherited from FProjectedShadowInitializer
FProjectedShadowInitializer ()
Default constructor.
bool IsCachedShadowValid (const FProjectedShadowInitializer &CachedShadow) const
Data Fields
bool bOnePassPointLightShadow
bool bRayTracedDistanceField
FShadowCascadeSettings CascadeSettings
Data Fields inherited from FProjectedShadowInitializer
float MaxDistanceToCastInLightW
float MinLightW
FVector PreShadowTranslation
A translation that is applied to world-space before transforming by one of the shadow matrices.
FVector2D Scales
Non-uniform scale to be applied after WorldToLight.
FBoxSphereBounds SubjectBounds
FVector4 WAxis
FMatrix WorldToLight
Detailed Description
Information needed to create a whole scene projected shadow.
Definition at line 1055 of file SceneManagement.h.
Constructor & Destructor Documentation
FWholeSceneProjectedShadowInitializer()
FWholeSceneProjectedShadowInitializer::FWholeSceneProjectedShadowInitializer () inline
Definition at line 1062 of file SceneManagement.h.
References bOnePassPointLightShadow, and bRayTracedDistanceField.
Referenced by IsCachedShadowValid().
Member Function Documentation
IsCachedShadowValid()
bool FWholeSceneProjectedShadowInitializer::IsCachedShadowValid (const FWholeSceneProjectedShadowInitializer & CachedShadow) const inline
Definition at line 1067 of file SceneManagement.h.
References FProjectedShadowInitializer::FProjectedShadowInitializer(), FWholeSceneProjectedShadowInitializer(), bOnePassPointLightShadow, bRayTracedDistanceField, and FProjectedShadowInitializer::IsCachedShadowValid().
Field Documentation
bOnePassPointLightShadow
bool FWholeSceneProjectedShadowInitializer::bOnePassPointLightShadow
Definition at line 1059 of file SceneManagement.h.
Referenced by FWholeSceneProjectedShadowInitializer(), and IsCachedShadowValid().
bRayTracedDistanceField
bool FWholeSceneProjectedShadowInitializer::bRayTracedDistanceField
Definition at line 1060 of file SceneManagement.h.
Referenced by FWholeSceneProjectedShadowInitializer(), and IsCachedShadowValid().
CascadeSettings
FShadowCascadeSettings FWholeSceneProjectedShadowInitializer::CascadeSettings
Definition at line 1058 of file SceneManagement.h.
The documentation for this class was generated from the following file:
SceneManagement.h