Unreal Engine 5.6 C++ API: UE::Geometry::FArrangement2d Struct Reference
UE::Geometry::FArrangement2d Struct Reference
Arrangement2d constructs a planar arrangement of a set of 2D line segments.
#include "Arrangement2d.h"
Data Structures
struct FIntersection
struct FSegmentPoint
Public Member Functions
FArrangement2d (const FAxisAlignedBox2d &BoundsHint)
FArrangement2d (double PointHashCellSize)
void ConnectOpenBoundaries (double DistThresh)
connect open boundary vertices within DistThresh, by inserting new segments
bool HasSelfIntersections ()
Check if current Graph has self-intersections; not optimized, only for debugging.
bool HasVertexNear (FVector2d Point, double SearchRadius)
Check if vertex exists in region.
void Insert (const FPolygon2d &Poly, int GID=-1)
sequentially insert segments of polyline
void Insert (const FSegment2d &Segment, int GID=-1)
insert segment into the arrangement
void Insert (const FVector2d &A, const FVector2d &B, int GID=-1)
insert segment [A,B] into the arrangement
int Insert (const FVector2d &Pt)
Insert isolated point P into the arrangement.
int32 InsertNewIsolatedPointUnsafe (const FVector2d &Pt)
Insert isolated point P into the arrangement when you know by construction it's not too close to any vertex or edge Much faster, but will break things if you use it to insert a point that is on top of any existing element!
FIndex2i SplitEdgeAtPoint (int EdgeID, FVector2d Point)
Subdivide edge at a given position.
bool GEOMETRYALGORITHMS_API Triangulate (TArray< FIndex3i > &Triangles)
Attempts to triangulate the arrangement with a constrained Delaunay triangulation NOTE: May fail if arrangement has self-intersections.
bool GEOMETRYALGORITHMS_API TriangulateWithBoundary (TArray< FIndex3i > &Triangles, int32 BoundaryEdgeGroupID)
Attempts to triangulate the arrangement with a constrained Delaunay triangulation NOTE: May fail if arrangement has self-intersections.
bool GEOMETRYALGORITHMS_API TriangulateWithBoundaryAndHoles (TArray< FIndex3i > &Triangles, int32 BoundaryEdgeGroupID, int32 HoleEdgeGroupID)
Attempts to triangulate the arrangement with a constrained Delaunay triangulation NOTE: May fail if arrangement has self-intersections.
UE_DEPRECATED (5.1, "Please use the Triangulate or TriangulateWithBoundary functions instead, which are explicit about whether a BoundaryEdgeGroupID should be present") bool GEOMETRYALGORITHMS_API AttemptTriangulate(TArray< FIndex3i > &Triangles
Attempts to triangulates the arrangement with a constrained Delaunay triangulation NOTE: Will return all triangles if no edges found with the BoundaryEdgeGroupID NOTE: May fail if arrangement has self-intersections.
UE_DEPRECATED (5.1, "Please use the Triangulate or TriangulateWithBoundary functions instead, which are explicit about whether a BoundaryEdgeGroupID should be present") bool GEOMETRYALGORITHMS_API AttemptTriangulate(TArray< FIntVector > &Triangles
Data Fields
TArray< int32 > int32 BoundaryEdgeGroupID
FDynamicGraph2d Graph
TPointHashGrid2d< int > PointHash
TArray< int32 > & SkippedEdges
double VertexSnapTol = 0.00001
Protected Member Functions
int find_existing_vertex (FVector2d Pt)
find existing vertex at point, if it exists
bool find_intersecting_edges (FVector2d A, FVector2d B, TArray< FIntersection > &Hits, double Tol=0)
find set of edges in graph that intersect with edge [A,B]
bool find_intersecting_floating_vertices (const FSegment2d &SegAB, int32 AID, int32 BID, TArray< FSegmentPoint > &Hits, double Tol=0)
int find_nearest_boundary_vertex (FVector2d Pt, double SearchRadius, int IgnoreVID=-1)
find nearest boundary vertex, within SearchRadius
int find_nearest_vertex (FVector2d Pt, double SearchRadius, int IgnoreVID=-1)
find closest vertex, within SearchRadius
int insert_point (const FVector2d &P, double Tol=0)
insert pt P into the arrangement, splitting existing edges as necessary
bool insert_segment (FVector2d A, FVector2d B, int GID=-1, double Tol=0)
insert edge [A,B] into the arrangement, splitting existing edges as necessary
FIndex2i split_segment_at_t (int EID, double T, double Tol)
insert new point into segment EID at parameter value T If T is within Tol of endpoint of segment, we use that instead.
Private Member Functions
bool GEOMETRYALGORITHMS_API TriangulateInternal (TArray< FIndex3i > &Triangles, bool bHasBoundaryEdgeGroupID, int32 BoundaryEdgeGroupID, bool bHasHoleGroupID, int32 HoleEdgeGroupID, bool bLegacyKeepTrianglesIfBoundaryNotFound, TArray< int32 > *SkippedEdges)
Detailed Description
Arrangement2d constructs a planar arrangement of a set of 2D line segments.
When a segment is inserted, existing edges are split, and the inserted segment becomes multiple graph edges. So, the resulting FDynamicGraph2d should not have any edges that intersect.
Calculations are performed in double-precision, so there is no guarantee of correctness.
[TODO] multi-level segment has to accelerate find_intersecting_edges() [TODO] maybe smarter handling
Definition at line 34 of file Arrangement2d.h.
Constructor & Destructor Documentation
FArrangement2d() [1/2]
UE::Geometry::FArrangement2d::FArrangement2d (const FAxisAlignedBox2d & BoundsHint) inline
Definition at line 45 of file Arrangement2d.h.
References UE::Geometry::Max(), and PointHash.
FArrangement2d() [2/2]
UE::Geometry::FArrangement2d::FArrangement2d (double PointHashCellSize) inline
Definition at line 50 of file Arrangement2d.h.
References UE::Geometry::Max(), and PointHash.
Member Function Documentation
ConnectOpenBoundaries()
void UE::Geometry::FArrangement2d::ConnectOpenBoundaries (double DistThresh) inline
connect open boundary vertices within DistThresh, by inserting new segments
Definition at line 211 of file Arrangement2d.h.
References find_nearest_boundary_vertex(), Graph, and Insert().
find_existing_vertex()
int UE::Geometry::FArrangement2d::find_existing_vertex (FVector2d Pt) inline protected
find existing vertex at point, if it exists
Definition at line 468 of file Arrangement2d.h.
References find_nearest_vertex(), and VertexSnapTol.
Referenced by insert_point(), insert_segment(), and split_segment_at_t().
find_intersecting_edges()
bool UE::Geometry::FArrangement2d::find_intersecting_edges (FVector2d A, FVector2d B, TArray< FIntersection > & Hits, double Tol = 0) inline protected
find set of edges in graph that intersect with edge [A,B]
Definition at line 515 of file Arrangement2d.h.
References A, TArray< InElementType, InAllocatorType >::Add(), B, UE::Math::TVector2< T >::Dot(), UE::Geometry::TIntrSegment2Segment2< RealType >::Find(), Graph, UE::Geometry::Normalize, UE::Geometry::PerpCW(), UE::Geometry::TIntrSegment2Segment2< RealType >::SetDotThreshold(), UE::Geometry::TIntrSegment2Segment2< RealType >::SetIntervalThreshold(), and UE::Math::TVector2< double >::Zero().
Referenced by insert_segment().
find_intersecting_floating_vertices()
bool UE::Geometry::FArrangement2d::find_intersecting_floating_vertices (const FSegment2d & SegAB, int32 AID, int32 BID, TArray< FSegmentPoint > & Hits, double Tol = 0) inline protected
Definition at line 550 of file Arrangement2d.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::TSegment2< T >::DistanceSquared(), and Graph.
Referenced by insert_segment().
find_nearest_boundary_vertex()
int UE::Geometry::FArrangement2d::find_nearest_boundary_vertex (FVector2d Pt, double SearchRadius, int IgnoreVID = -1) inline protected
find nearest boundary vertex, within SearchRadius
Definition at line 491 of file Arrangement2d.h.
References B, UE::Geometry::DistanceSquared(), Graph, and PointHash.
Referenced by ConnectOpenBoundaries().
find_nearest_vertex()
int UE::Geometry::FArrangement2d::find_nearest_vertex (FVector2d Pt, double SearchRadius, int IgnoreVID = -1) inline protected
find closest vertex, within SearchRadius
Definition at line 475 of file Arrangement2d.h.
References B, UE::Geometry::DistanceSquared(), Graph, and PointHash.
Referenced by find_existing_vertex(), and HasVertexNear().
HasSelfIntersections()
bool UE::Geometry::FArrangement2d::HasSelfIntersections () inline
Check if current Graph has self-intersections; not optimized, only for debugging.
Definition at line 105 of file Arrangement2d.h.
References Graph, and HasSelfIntersections().
Referenced by HasSelfIntersections().
HasVertexNear()
bool UE::Geometry::FArrangement2d::HasVertexNear (FVector2d Point, double SearchRadius) inline
Check if vertex exists in region.
Definition at line 139 of file Arrangement2d.h.
References find_nearest_vertex(), and Point.
Insert() [1/4]
void UE::Geometry::FArrangement2d::Insert (const FPolygon2d & Poly, int GID = -1) inline
sequentially insert segments of polyline
sequentially insert segments of polygon
Definition at line 195 of file Arrangement2d.h.
References insert_segment(), UE::Geometry::TPolygon2< T >::VertexCount(), and VertexSnapTol.
Insert() [2/4]
void UE::Geometry::FArrangement2d::Insert (const FSegment2d & Segment, int GID = -1) inline
insert segment into the arrangement
Definition at line 174 of file Arrangement2d.h.
References insert_segment(), Segment, and VertexSnapTol.
Insert() [3/4]
void UE::Geometry::FArrangement2d::Insert (const FVector2d & A, const FVector2d & B, int GID = -1) inline
insert segment [A,B] into the arrangement
Definition at line 166 of file Arrangement2d.h.
References A, B, insert_segment(), and VertexSnapTol.
Insert() [4/4]
int UE::Geometry::FArrangement2d::Insert (const FVector2d & Pt) inline
Insert isolated point P into the arrangement.
Definition at line 147 of file Arrangement2d.h.
References insert_point(), and VertexSnapTol.
Referenced by ConnectOpenBoundaries().
insert_point()
int UE::Geometry::FArrangement2d::insert_point (const FVector2d & P, double Tol = 0) inline protected
insert pt P into the arrangement, splitting existing edges as necessary
Definition at line 241 of file Arrangement2d.h.
References UE::Geometry::TSegment2< T >::DistanceSquared(), ensureMsgf, find_existing_vertex(), Graph, UE::Geometry::Ok, PointHash, TEXT, UE::Geometry::FDynamicGraph::FEdgeSplitInfo::VNew, and UE::Math::TVector2< double >::Zero().
Referenced by Insert(), and insert_segment().
insert_segment()
bool UE::Geometry::FArrangement2d::insert_segment (FVector2d A, FVector2d B, int GID = -1, double Tol = 0) inline protected
insert edge [A,B] into the arrangement, splitting existing edges as necessary
Definition at line 287 of file Arrangement2d.h.
References A, UE::Geometry::FIndex2i::A, TArray< InElementType, InAllocatorType >::Add(), B, UE::Geometry::FIndex2i::B, UE::Geometry::DistanceSquared(), UE::Geometry::FArrangement2d::FIntersection::EID, ensureMsgf, UE::Geometry::TSegment2< T >::Extent, find_existing_vertex(), find_intersecting_edges(), find_intersecting_floating_vertices(), UE::Geometry::TIntrSegment2Segment2< RealType >::GetSegment1(), Graph, insert_point(), UE::Geometry::FArrangement2d::FIntersection::Intr, UE::Geometry::FDynamicGraph::InvalidID, TArray< InElementType, InAllocatorType >::Num(), UE::Geometry::TIntrSegment2Segment2< RealType >::Parameter0, UE::Geometry::TIntrSegment2Segment2< RealType >::Parameter1, Point, UE::Geometry::TSegment2< T >::PointAt(), PointHash, UE::Geometry::TSegment2< T >::Project(), Segment, TArray< InElementType, InAllocatorType >::Sort(), split_segment_at_t(), UE::Geometry::FArrangement2d::FSegmentPoint::T, TEXT, UE::Geometry::TIntrSegment2Segment2< RealType >::Type, and VertexSnapTol.
Referenced by Insert(), Insert(), and Insert().
InsertNewIsolatedPointUnsafe()
int32 UE::Geometry::FArrangement2d::InsertNewIsolatedPointUnsafe (const FVector2d & Pt) inline
Insert isolated point P into the arrangement when you know by construction it's not too close to any vertex or edge Much faster, but will break things if you use it to insert a point that is on top of any existing element!
Definition at line 156 of file Arrangement2d.h.
References Graph, and PointHash.
split_segment_at_t()
FIndex2i UE::Geometry::FArrangement2d::split_segment_at_t (int EID, double T, double Tol) inline protected
insert new point into segment EID at parameter value T If T is within Tol of endpoint of segment, we use that instead.
Definition at line 424 of file Arrangement2d.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, UE::Geometry::FDynamicGraph::FEdgeSplitInfo::ENewBN, ensureMsgf, UE::Geometry::TSegment2< T >::Extent, find_existing_vertex(), Graph, UE::Geometry::Ok, UE::Geometry::TSegment2< T >::PointAt(), PointHash, TEXT, and UE::Geometry::FDynamicGraph::FEdgeSplitInfo::VNew.
Referenced by insert_segment().
SplitEdgeAtPoint()
FIndex2i UE::Geometry::FArrangement2d::SplitEdgeAtPoint (int EdgeID, FVector2d Point) inline
Subdivide edge at a given position.
Definition at line 126 of file Arrangement2d.h.
References UE::Geometry::FDynamicGraph::FEdgeSplitInfo::ENewBN, ensureMsgf, Graph, UE::Geometry::Ok, Point, PointHash, TEXT, and UE::Geometry::FDynamicGraph::FEdgeSplitInfo::VNew.
Triangulate()
bool GEOMETRYALGORITHMS_API UE::Geometry::FArrangement2d::Triangulate (TArray< FIndex3i > & Triangles)
Attempts to triangulate the arrangement with a constrained Delaunay triangulation NOTE: May fail if arrangement has self-intersections.
Parameters
Triangles Output triangles (as indices into Graph vertices)
Returns
false if triangulation algo knows it failed; will still likely have some triangulation even in this case
References Triangulate().
Referenced by Triangulate().
TriangulateInternal()
bool GEOMETRYALGORITHMS_API UE::Geometry::FArrangement2d::TriangulateInternal (TArray< FIndex3i > & Triangles, bool bHasBoundaryEdgeGroupID, int32 BoundaryEdgeGroupID, bool bHasHoleGroupID, int32 HoleEdgeGroupID, bool bLegacyKeepTrianglesIfBoundaryNotFound, TArray< int32 > * SkippedEdges) private
References BoundaryEdgeGroupID, and SkippedEdges.
TriangulateWithBoundary()
bool GEOMETRYALGORITHMS_API UE::Geometry::FArrangement2d::TriangulateWithBoundary (TArray< FIndex3i > & Triangles, int32 BoundaryEdgeGroupID)
Attempts to triangulate the arrangement with a constrained Delaunay triangulation NOTE: May fail if arrangement has self-intersections.
Parameters
Triangles Output triangles (as indices into Graph vertices)
BoundaryEdgeGroupID ID of edges corresponding to a boundary: triangles outside these edges will be removed
Returns
false if triangulation algo knows it failed; will still likely have some triangulation even in this case
References BoundaryEdgeGroupID, and TriangulateWithBoundary().
Referenced by TriangulateWithBoundary().
TriangulateWithBoundaryAndHoles()
bool GEOMETRYALGORITHMS_API UE::Geometry::FArrangement2d::TriangulateWithBoundaryAndHoles (TArray< FIndex3i > & Triangles, int32 BoundaryEdgeGroupID, int32 HoleEdgeGroupID)
Attempts to triangulate the arrangement with a constrained Delaunay triangulation NOTE: May fail if arrangement has self-intersections.
Parameters
Triangles Output triangles (as indices into Graph vertices)
BoundaryEdgeGroupID ID of edges corresponding to a boundary: triangles outside these edges will be removed
HoleEdgeGroupID ID of edges corresponding to internal holes: triangles inside these edges will be removed
Returns
false if triangulation algo knows it failed; will still likely have some triangulation even in this case
References BoundaryEdgeGroupID, and TriangulateWithBoundaryAndHoles().
Referenced by TriangulateWithBoundaryAndHoles().
UE_DEPRECATED() [1/2]
UE::Geometry::FArrangement2d::UE_DEPRECATED (5. 1, "Please use the Triangulate or TriangulateWithBoundary functions instead, which are explicit about whether a BoundaryEdgeGroupID should be present") &
Attempts to triangulates the arrangement with a constrained Delaunay triangulation NOTE: Will return all triangles if no edges found with the BoundaryEdgeGroupID NOTE: May fail if arrangement has self-intersections.
Triangles: Output triangles (as indices into Graph vertices) SkippedEdges: Output indices of edges that the algorithm failed to insert BoundaryEdgeGroupID: ID of edges corresponding to a boundary; if we have a closed loop of these boundary edges on output triangulation, will discard triangles outside this return: false if triangulation algo knows it failed (note Triangles may still have some triangulation of the input in this case; for example it may just be missing some required edges)
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Geometry::FArrangement2d::UE_DEPRECATED (5. 1, "Please use the Triangulate or TriangulateWithBoundary functions instead, which are explicit about whether a BoundaryEdgeGroupID should be present") &
References BoundaryEdgeGroupID, SkippedEdges, and UE_DEPRECATED().
Field Documentation
BoundaryEdgeGroupID
TArray< int32 > int32 UE::Geometry::FArrangement2d::BoundaryEdgeGroupID
Definition at line 66 of file Arrangement2d.h.
Referenced by TriangulateInternal(), TriangulateWithBoundary(), TriangulateWithBoundaryAndHoles(), and UE_DEPRECATED().
Graph
FDynamicGraph2d UE::Geometry::FArrangement2d::Graph
Definition at line 37 of file Arrangement2d.h.
Referenced by ConnectOpenBoundaries(), find_intersecting_edges(), find_intersecting_floating_vertices(), find_nearest_boundary_vertex(), find_nearest_vertex(), HasSelfIntersections(), insert_point(), insert_segment(), InsertNewIsolatedPointUnsafe(), split_segment_at_t(), and SplitEdgeAtPoint().
PointHash
TPointHashGrid2d<int> UE::Geometry::FArrangement2d::PointHash
Definition at line 40 of file Arrangement2d.h.
Referenced by FArrangement2d(), FArrangement2d(), find_nearest_boundary_vertex(), find_nearest_vertex(), insert_point(), insert_segment(), InsertNewIsolatedPointUnsafe(), split_segment_at_t(), and SplitEdgeAtPoint().
SkippedEdges
TArray< int32 > & UE::Geometry::FArrangement2d::SkippedEdges
Definition at line 66 of file Arrangement2d.h.
Referenced by TriangulateInternal(), and UE_DEPRECATED().
VertexSnapTol
double UE::Geometry::FArrangement2d::VertexSnapTol = 0.00001
Definition at line 43 of file Arrangement2d.h.
Referenced by find_existing_vertex(), Insert(), Insert(), Insert(), Insert(), and insert_segment().
The documentation for this struct was generated from the following file:
Arrangement2d.h