Unreal Engine 5.6 C++ API: FFloat16 Class Reference
FFloat16 Class Reference
16 bit float components and conversion
#include "Float16.h"
Public Member Functions
FFloat16 ()
Default constructor.
FFloat16 (const FFloat16 &FP16Value)
Copy constructor.
FFloat16 (float FP32Value)
Conversion constructor.
FFloat16 GetClampedFinite () const
Return float clamp in [-MaxF16Float,MaxF16Float] , no infinites or nans returned.
FFloat16 GetClampedNonNegativeAndFinite () const
Return float clamp in [0,MaxF16Float] , no negatives or infinites or nans returned.
float GetFloat () const
Convert from Fp16 to Fp32.
bool IsNegative () const
Is the float negative without converting NOTE: returns true for negative zero!
operator float () const
Convert from Fp16 to Fp32.
FFloat16 & operator= (const FFloat16 &FP16Value)
Assignment operator.
FFloat16 & operator= (float FP32Value)
Assignment operator.
void Set (float FP32Value)
Convert from Fp32 to Fp16, round-to-nearest-even.
void SetClamped (float FP32Value)
void SetOne ()
Set to 1.0.
void SetTruncate (float FP32Value)
Convert from Fp32 to Fp16, truncating low bits.
void SetZero ()
Set to 0.0.
Data Fields
uint16 Encoded
Static Public Attributes
static constexpr float MaxF16Float = 65504.f
Friends
FArchive & operator<< (FArchive &Ar, FFloat16 &V)
Serializes the FFloat16.
Detailed Description
16 bit float components and conversion
IEEE float 16 Represented by 10-bit mantissa M, 5-bit exponent E, and 1-bit sign S
Specials:
E=0, M=0 == 0.0 E=0, M!=0 == Denormalized value (M / 2^10) * 2^-14 0<E<31, M=any == (1 + M / 2^10) * 2^(E-15) E=31, M=0 == Infinity E=31, M!=0 == NAN
conversion from 32 bit float is with RTNE (round to nearest even)
Legacy code truncated in the conversion. SetTruncate can be used for backwards compatibility.
Definition at line 33 of file Float16.h.
Constructor & Destructor Documentation
FFloat16() [1/3]
FORCEINLINE FFloat16::FFloat16 () nodiscard
Default constructor.
Definition at line 123 of file Float16.h.
References Encoded, and FORCEINLINE.
Referenced by FFloat16(), GetClampedFinite(), GetClampedNonNegativeAndFinite(), operator<<, operator=(), and operator=().
FFloat16() [2/3]
FORCEINLINE FFloat16::FFloat16 (const FFloat16 & FP16Value) nodiscard
Copy constructor.
Definition at line 128 of file Float16.h.
References FFloat16(), Encoded, and FORCEINLINE.
FFloat16() [3/3]
FORCEINLINE FFloat16::FFloat16 (float FP32Value) nodiscard
Conversion constructor.
Convert from Fp32 to Fp16.
Definition at line 134 of file Float16.h.
References FORCEINLINE, and Set().
Member Function Documentation
GetClampedFinite()
FORCEINLINE FFloat16 FFloat16::GetClampedFinite () const nodiscard
Return float clamp in [-MaxF16Float,MaxF16Float] , no infinites or nans returned.
Definition at line 258 of file Float16.h.
References FFloat16(), Encoded, and FORCEINLINE.
GetClampedNonNegativeAndFinite()
FORCEINLINE FFloat16 FFloat16::GetClampedNonNegativeAndFinite () const nodiscard
Return float clamp in [0,MaxF16Float] , no negatives or infinites or nans returned.
Definition at line 242 of file Float16.h.
References FFloat16(), Encoded, and FORCEINLINE.
GetFloat()
FORCEINLINE float FFloat16::GetFloat () const nodiscard
Convert from Fp16 to Fp32.
Definition at line 169 of file Float16.h.
References Encoded, and FORCEINLINE.
Referenced by operator float().
IsNegative()
bool FFloat16::IsNegative () const inline nodiscard
Is the float negative without converting NOTE: returns true for negative zero!
Definition at line 99 of file Float16.h.
References Encoded.
operator float()
FORCEINLINE FFloat16::operator float () const
Convert from Fp16 to Fp32.
Definition at line 154 of file Float16.h.
References FORCEINLINE, and GetFloat().
operator=() [1/2]
FORCEINLINE FFloat16 & FFloat16::operator= (const FFloat16 & FP16Value)
Assignment operator.
Copy Fp16 value.
Definition at line 147 of file Float16.h.
References FFloat16(), Encoded, and FORCEINLINE.
operator=() [2/2]
FORCEINLINE FFloat16 & FFloat16::operator= (float FP32Value)
Assignment operator.
Convert from Fp32 to Fp16.
Definition at line 140 of file Float16.h.
References FFloat16(), FORCEINLINE, and Set().
Set()
FORCEINLINE void FFloat16::Set (float FP32Value)
Convert from Fp32 to Fp16, round-to-nearest-even.
(RTNE) Stores values out of range as +-Inf
Definition at line 161 of file Float16.h.
References Encoded, and FORCEINLINE.
Referenced by FFloat16(), operator=(), and SetClamped().
SetClamped()
void FFloat16::SetClamped (float FP32Value) inline
Definition at line 66 of file Float16.h.
References FMath::Clamp(), MaxF16Float, and Set().
SetOne()
void FFloat16::SetOne () inline
Set to 1.0.
Definition at line 83 of file Float16.h.
References Encoded.
SetTruncate()
FORCEINLINE void FFloat16::SetTruncate (float FP32Value)
Convert from Fp32 to Fp16, truncating low bits.
(backward-compatible conversion; was used by Set() previously) Clamps values out of range to [-MaxF16Float,MaxF16Float]
Definition at line 176 of file Float16.h.
References Components, FFloat32::Components, Encoded, FFloat32::Exponent, FORCEINLINE, FFloat32::Mantissa, and FFloat32::Sign.
SetZero()
void FFloat16::SetZero () inline
Set to 0.0.
Definition at line 77 of file Float16.h.
References Encoded.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FFloat16 & V) friend
Serializes the FFloat16.
Parameters
Ar Reference to the serialization archive.
V Reference to the FFloat16 being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 114 of file Float16.h.
References FFloat16(), Ar, and Encoded.
Field Documentation
Encoded
uint16 FFloat16::Encoded
Definition at line 40 of file Float16.h.
Referenced by FFloat16(), FFloat16(), GetClampedFinite(), GetClampedNonNegativeAndFinite(), GetFloat(), IsNegative(), operator<<, operator=(), Set(), SetOne(), SetTruncate(), and SetZero().
MaxF16Float
float FFloat16::MaxF16Float = 65504.f static constexpr
Definition at line 38 of file Float16.h.
Referenced by SetClamped().
The documentation for this class was generated from the following file:
Float16.h