Unreal Engine 5.6 C++ API: UMaterialExpressionCurveAtlasRowParameter Class Reference
UMaterialExpressionCurveAtlasRowParameter Class Reference
#include "MaterialExpressionCurveAtlasRowParameter.h"
Private Member Functions
virtual bool CanReferenceTexture () const
virtual int32 Compile (class FMaterialCompiler *Compiler, int32 OutputIndex) override
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UCurveLinearColor > Curve
virtual void GetCaption (TArray< FString > &OutCaptions) const override
virtual FName GetInputName (int32 InputIndex) const override
virtual EMaterialValueType GetInputValueType (int32 InputIndex) override
virtual bool GetParameterValue (FMaterialParameterMetadata &OutMeta) const override
virtual UObject * GetReferencedTexture () const override
virtual void GetTexturesForceMaterialRecompile (TArray< UTexture * > &Textures) const override
virtual bool IsInputConnectionRequired (int32 InputIndex) const override
virtual bool IsUsedAsAtlasPosition () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual bool SetParameterValue (const FName &Name, const FMaterialParameterMetadata &Meta, EMaterialExpressionSetParameterValueFlags Flags) override
UPROPERTY () FExpressionInput InputTime
UPROPERTY () TObjectPtr< class UCurveLinearColorAtlas > Atlas
Detailed Description
Definition at line 12 of file MaterialExpressionCurveAtlasRowParameter.h.
Member Function Documentation
CanReferenceTexture()
virtual bool UMaterialExpressionCurveAtlasRowParameter::CanReferenceTexture () const inline private virtual
Definition at line 27 of file MaterialExpressionCurveAtlasRowParameter.h.
Compile()
virtual int32 UMaterialExpressionCurveAtlasRowParameter::Compile (class FMaterialCompiler * Compiler, int32 OutputIndex) override private virtual
GENERATED_UCLASS_BODY()
UMaterialExpressionCurveAtlasRowParameter::GENERATED_UCLASS_BODY () private
References Category, and UPROPERTY().
GetCaption()
virtual void UMaterialExpressionCurveAtlasRowParameter::GetCaption (TArray< FString > & OutCaptions) const inline override private virtual
Definition at line 42 of file MaterialExpressionCurveAtlasRowParameter.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Empty(), and TEXT.
GetInputName()
virtual FName UMaterialExpressionCurveAtlasRowParameter::GetInputName (int32 InputIndex) const inline override private virtual
Definition at line 48 of file MaterialExpressionCurveAtlasRowParameter.h.
References TEXT.
GetInputValueType()
virtual EMaterialValueType UMaterialExpressionCurveAtlasRowParameter::GetInputValueType (int32 InputIndex) inline override private virtual
Definition at line 33 of file MaterialExpressionCurveAtlasRowParameter.h.
References MCT_Float.
GetParameterValue()
virtual bool UMaterialExpressionCurveAtlasRowParameter::GetParameterValue (FMaterialParameterMetadata & OutMeta) const override private virtual
GetReferencedTexture()
virtual UObject * UMaterialExpressionCurveAtlasRowParameter::GetReferencedTexture () const override private virtual
GetTexturesForceMaterialRecompile()
virtual void UMaterialExpressionCurveAtlasRowParameter::GetTexturesForceMaterialRecompile (TArray< UTexture * > & Textures) const override private virtual
IsInputConnectionRequired()
virtual bool UMaterialExpressionCurveAtlasRowParameter::IsInputConnectionRequired (int32 InputIndex) const inline override private virtual
Definition at line 38 of file MaterialExpressionCurveAtlasRowParameter.h.
IsUsedAsAtlasPosition()
virtual bool UMaterialExpressionCurveAtlasRowParameter::IsUsedAsAtlasPosition () const inline override private virtual
Definition at line 25 of file MaterialExpressionCurveAtlasRowParameter.h.
References IsUsedAsAtlasPosition().
Referenced by IsUsedAsAtlasPosition().
PostEditChangeProperty()
virtual void UMaterialExpressionCurveAtlasRowParameter::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
SetParameterValue()
virtual bool UMaterialExpressionCurveAtlasRowParameter::SetParameterValue (const FName & Name, const FMaterialParameterMetadata & Meta, EMaterialExpressionSetParameterValueFlags Flags) override private virtual
References Flags, Meta, and Name.
UPROPERTY() [1/2]
UMaterialExpressionCurveAtlasRowParameter::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [2/2]
UMaterialExpressionCurveAtlasRowParameter::UPROPERTY () private
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
MaterialExpressionCurveAtlasRowParameter.h