Unreal Engine 5.6 C++ API: UE::GC::FMemberId Class Reference
UE::GC::FMemberId Class Reference
Debug identifier for a schema index or a memberless reference.
#include "GarbageCollectionSchema.h"
Public Member Functions
FORCEINLINE FMemberId (EMemberlessId Memberless)
FORCEINLINE FMemberId (uint32 Idx)
EMemberlessId AsMemberless () const
int32 AsPrintableIndex () const
uint32 GetIndex () const
bool IsMemberless () const
Private Member Functions
void StaticAssert ()
Private Attributes
uint32 Index: IndexBits
uint32 MemberlessId: MemberlessIdBits
Static Private Attributes
static constexpr uint32 IndexBits = 32 - MemberlessIdBits
static constexpr uint32 MemberlessIdBits = 3
Friends
bool operator!= (FMemberId A, FMemberId B)
bool operator== (FMemberId A, FMemberId B)
Detailed Description
Debug identifier for a schema index or a memberless reference.
Definition at line 155 of file GarbageCollectionSchema.h.
Constructor & Destructor Documentation
FMemberId() [1/2]
FORCEINLINE UE::GC::FMemberId::FMemberId (EMemberlessId Memberless) inline
Definition at line 158 of file GarbageCollectionSchema.h.
References FORCEINLINE, Index, and MemberlessId.
Referenced by operator!=, and operator==.
FMemberId() [2/2]
FORCEINLINE UE::GC::FMemberId::FMemberId (uint32 Idx) inline explicit
Definition at line 159 of file GarbageCollectionSchema.h.
References FORCEINLINE, Index, and MemberlessId.
Member Function Documentation
AsMemberless()
EMemberlessId UE::GC::FMemberId::AsMemberless () const inline
Definition at line 164 of file GarbageCollectionSchema.h.
References check, IsMemberless(), and MemberlessId.
AsPrintableIndex()
int32 UE::GC::FMemberId::AsPrintableIndex () const inline
Definition at line 163 of file GarbageCollectionSchema.h.
References Index, IsMemberless(), and MemberlessId.
GetIndex()
uint32 UE::GC::FMemberId::GetIndex () const inline
Definition at line 162 of file GarbageCollectionSchema.h.
References check, Index, and IsMemberless().
IsMemberless()
bool UE::GC::FMemberId::IsMemberless () const inline
Definition at line 161 of file GarbageCollectionSchema.h.
References MemberlessId.
Referenced by AsMemberless(), AsPrintableIndex(), and GetIndex().
StaticAssert()
void UE::GC::FMemberId::StaticAssert () private
Friends And Related Symbol Documentation
operator!=
bool operator!= (FMemberId A, FMemberId B) friend
Definition at line 167 of file GarbageCollectionSchema.h.
References FMemberId(), A, and B.
operator==
bool operator== (FMemberId A, FMemberId B) friend
Definition at line 166 of file GarbageCollectionSchema.h.
References FMemberId(), A, and B.
Field Documentation
Index
uint32 UE::GC::FMemberId::Index private
Definition at line 173 of file GarbageCollectionSchema.h.
Referenced by FMemberId(), FMemberId(), AsPrintableIndex(), and GetIndex().
IndexBits
uint32 UE::GC::FMemberId::IndexBits = 32 - MemberlessIdBits static constexpr private
Definition at line 171 of file GarbageCollectionSchema.h.
MemberlessId
uint32 UE::GC::FMemberId::MemberlessId private
Definition at line 174 of file GarbageCollectionSchema.h.
Referenced by FMemberId(), FMemberId(), AsMemberless(), AsPrintableIndex(), and IsMemberless().
MemberlessIdBits
uint32 UE::GC::FMemberId::MemberlessIdBits = 3 static constexpr private
Definition at line 170 of file GarbageCollectionSchema.h.
The documentation for this class was generated from the following file:
GarbageCollectionSchema.h