Unreal Engine 5.6 C++ API: FRigVMASTLinkDescription Struct Reference
FRigVMASTLinkDescription Struct Reference
#include "RigVMAST.h"
Public Member Functions
FRigVMASTLinkDescription ()
FRigVMASTLinkDescription (const FRigVMASTLinkDescription &InOther)
FRigVMASTLinkDescription (const FRigVMASTProxy &InSourceProxy, const FRigVMASTProxy &InTargetProxy, const FString &InSegmentPath)
FRigVMASTLinkDescription & operator= (const FRigVMASTLinkDescription &)=default
Data Fields
int32 LinkIndex
FString SegmentPath
FRigVMASTProxy SourceProxy
FRigVMASTProxy TargetProxy
Detailed Description
Definition at line 40 of file RigVMAST.h.
Constructor & Destructor Documentation
FRigVMASTLinkDescription() [1/3]
FRigVMASTLinkDescription::FRigVMASTLinkDescription () inline
Definition at line 42 of file RigVMAST.h.
Referenced by FRigVMASTLinkDescription(), and operator=().
FRigVMASTLinkDescription() [2/3]
FRigVMASTLinkDescription::FRigVMASTLinkDescription (const FRigVMASTProxy & InSourceProxy, const FRigVMASTProxy & InTargetProxy, const FString & InSegmentPath) inline
Definition at line 44 of file RigVMAST.h.
References INDEX_NONE, LinkIndex, SegmentPath, SourceProxy, and TargetProxy.
FRigVMASTLinkDescription() [3/3]
FRigVMASTLinkDescription::FRigVMASTLinkDescription (const FRigVMASTLinkDescription & InOther) inline
Definition at line 51 of file RigVMAST.h.
References FRigVMASTLinkDescription(), INDEX_NONE, LinkIndex, SegmentPath, SourceProxy, and TargetProxy.
Member Function Documentation
operator=()
FRigVMASTLinkDescription & FRigVMASTLinkDescription::operator= (const FRigVMASTLinkDescription &) default
References FRigVMASTLinkDescription().
Field Documentation
LinkIndex
int32 FRigVMASTLinkDescription::LinkIndex
Definition at line 64 of file RigVMAST.h.
Referenced by FRigVMASTLinkDescription(), and FRigVMASTLinkDescription().
SegmentPath
FString FRigVMASTLinkDescription::SegmentPath
Definition at line 63 of file RigVMAST.h.
Referenced by FRigVMASTLinkDescription(), and FRigVMASTLinkDescription().
SourceProxy
FRigVMASTProxy FRigVMASTLinkDescription::SourceProxy
Definition at line 61 of file RigVMAST.h.
Referenced by FRigVMASTLinkDescription(), and FRigVMASTLinkDescription().
TargetProxy
FRigVMASTProxy FRigVMASTLinkDescription::TargetProxy
Definition at line 62 of file RigVMAST.h.
Referenced by FRigVMASTLinkDescription(), and FRigVMASTLinkDescription().
The documentation for this struct was generated from the following file:
RigVMAST.h