Unreal Engine 5.6 C++ API: FTexture2DMipMap Struct Reference
FTexture2DMipMap Struct Reference
A 2D texture mip-map.
#include "TextureResource.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FTexture2DMipMap ()=default
FTexture2DMipMap (const FTexture2DMipMap &)=default
FTexture2DMipMap (FTexture2DMipMap &&)=default
FTexture2DMipMap (uint32 InSizeX, uint32 InSizeY, uint32 InSizeZ=0)
~FTexture2DMipMap ()=default
FTexture2DMipMap & operator= (const FTexture2DMipMap &)=default
FTexture2DMipMap & operator= (FTexture2DMipMap &&)=default
PRAGMA_ENABLE_DEPRECATION_WARNINGS void Serialize (FArchive &Ar, UObject *Owner, int32 MipIndex, bool bSerializeMipData)
Serialization.
Data Fields
FByteBulkData BulkData
Stores the data for the mip when it is loaded.
UE::FDerivedData DerivedData
Reference to the data for the mip if it can be streamed.
uint16 SizeX = 0
Width of the mip-map.
uint16 SizeY = 0
Height of the mip-map.
uint16 SizeZ = 0
Depth of the mip-map.
Detailed Description
A 2D texture mip-map.
Definition at line 45 of file TextureResource.h.
Constructor & Destructor Documentation
FTexture2DMipMap() [1/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FTexture2DMipMap::FTexture2DMipMap () default
Referenced by FTexture2DMipMap(), FTexture2DMipMap(), operator=(), and operator=().
FTexture2DMipMap() [2/4]
FTexture2DMipMap::FTexture2DMipMap (uint32 InSizeX, uint32 InSizeY, uint32 InSizeZ = 0) inline
Definition at line 61 of file TextureResource.h.
References LowLevelFatalError, SizeX, SizeY, SizeZ, and TEXT.
FTexture2DMipMap() [3/4]
FTexture2DMipMap::FTexture2DMipMap (FTexture2DMipMap &&) default
References FTexture2DMipMap().
FTexture2DMipMap() [4/4]
FTexture2DMipMap::FTexture2DMipMap (const FTexture2DMipMap &) default
References FTexture2DMipMap().
~FTexture2DMipMap()
FTexture2DMipMap::~FTexture2DMipMap () default
References PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Member Function Documentation
operator=() [1/2]
FTexture2DMipMap & FTexture2DMipMap::operator= (const FTexture2DMipMap &) default
References FTexture2DMipMap().
operator=() [2/2]
FTexture2DMipMap & FTexture2DMipMap::operator= (FTexture2DMipMap &&) default
References FTexture2DMipMap().
Serialize()
PRAGMA_ENABLE_DEPRECATION_WARNINGS void FTexture2DMipMap::Serialize (FArchive & Ar, UObject * Owner, int32 MipIndex, bool bSerializeMipData)
Serialization.
References Ar, bool, DerivedData, None, and Owner.
Field Documentation
BulkData
FByteBulkData FTexture2DMipMap::BulkData
Stores the data for the mip when it is loaded.
Definition at line 50 of file TextureResource.h.
DerivedData
UE::FDerivedData FTexture2DMipMap::DerivedData
Reference to the data for the mip if it can be streamed.
Definition at line 48 of file TextureResource.h.
Referenced by Serialize().
SizeX
uint16 FTexture2DMipMap::SizeX = 0
Width of the mip-map.
Definition at line 53 of file TextureResource.h.
Referenced by FTexture2DMipMap().
SizeY
uint16 FTexture2DMipMap::SizeY = 0
Height of the mip-map.
Definition at line 55 of file TextureResource.h.
Referenced by FTexture2DMipMap().
SizeZ
uint16 FTexture2DMipMap::SizeZ = 0
Depth of the mip-map.
This also holds array size. It's thunked through to FStreamableTextureResource::SizeZ and is not used for cubemap arrays or cubemaps
Definition at line 57 of file TextureResource.h.
Referenced by FTexture2DMipMap().
The documentation for this struct was generated from the following file:
TextureResource.h