Unreal Engine 5.6 C++ API: DisplayClusterHelpers::map Namespace Reference
DisplayClusterHelpers::map Namespace Reference
Functions
template<typename TVal>
bool ExtractArrayFromString (const TMap< FString, FString > &InMap, const FString &InKey, TArray< TVal > &OutArray, const FString &InSeparator=DisplayClusterStrings::common::ArrayValSeparator, bool bCullEmpty=true, ESearchCase::Type SearchCase=ESearchCase::IgnoreCase)
template<typename TKey, typename TVal>
bool ExtractMapFromString (const TMap< FString, FString > &InMap, const FString &InKey, TMap< TKey, TVal > &OutMap, const FString &InPairSeparator=FString(DisplayClusterStrings::common::PairSeparator), const FString &InKeyValSeparator=FString(DisplayClusterStrings::common::KeyValSeparator), ESearchCase::Type SearchCase=ESearchCase::IgnoreCase)
template<typename TVal>
TVal ExtractValue (const TMap< FString, TVal > &InMap, const FString &InKey, const TVal &DefaultValue, ESearchCase::Type SearchCase=ESearchCase::IgnoreCase)
template<typename TVal>
bool ExtractValue (const TMap< FString, TVal > &InMap, const FString &InKey, TVal &OutValue, ESearchCase::Type SearchCase=ESearchCase::IgnoreCase)
template<typename TReturn>
TReturn ExtractValueFromString (const TMap< FString, FString > &InMap, const FString &InKey, const TReturn &DefaultValue, ESearchCase::Type SearchCase=ESearchCase::IgnoreCase)
template<typename TReturn>
bool ExtractValueFromString (const TMap< FString, FString > &InMap, const FString &InKey, TReturn &OutValue, ESearchCase::Type SearchCase=ESearchCase::IgnoreCase)
Function Documentation
ExtractArrayFromString()
template<typename TVal> bool DisplayClusterHelpers::map::ExtractArrayFromString (const TMap< FString, FString > & InMap, const FString & InKey, TArray< TVal > & OutArray, const FString & InSeparator = DisplayClusterStrings::common::ArrayValSeparator, bool bCullEmpty = true, ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
Definition at line 337 of file DisplayClusterHelpers.h.
References DisplayClusterStrings::common::ArrayValSeparator, ExtractValue(), and ESearchCase::IgnoreCase.
ExtractMapFromString()
template<typename TKey, typename TVal> bool DisplayClusterHelpers::map::ExtractMapFromString (const TMap< FString, FString > & InMap, const FString & InKey, TMap< TKey, TVal > & OutMap, const FString & InPairSeparator = FString(DisplayClusterStrings::common::PairSeparator), const FString & InKeyValSeparator = FString(DisplayClusterStrings::common::KeyValSeparator), ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
Definition at line 356 of file DisplayClusterHelpers.h.
References ExtractValue(), ESearchCase::IgnoreCase, DisplayClusterStrings::common::KeyValSeparator, and DisplayClusterStrings::common::PairSeparator.
ExtractValue() [1/2]
template<typename TVal> TVal DisplayClusterHelpers::map::ExtractValue (const TMap< FString, TVal > & InMap, const FString & InKey, const TVal & DefaultValue, ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
Definition at line 302 of file DisplayClusterHelpers.h.
References ExtractValue(), and ESearchCase::IgnoreCase.
ExtractValue() [2/2]
template<typename TVal> bool DisplayClusterHelpers::map::ExtractValue (const TMap< FString, TVal > & InMap, const FString & InKey, TVal & OutValue, ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
Definition at line 286 of file DisplayClusterHelpers.h.
References ESearchCase::IgnoreCase.
Referenced by ExtractArrayFromString(), ExtractMapFromString(), ExtractValue(), ExtractValueFromString(), and ExtractValueFromString().
ExtractValueFromString() [1/2]
template<typename TReturn> TReturn DisplayClusterHelpers::map::ExtractValueFromString (const TMap< FString, FString > & InMap, const FString & InKey, const TReturn & DefaultValue, ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
Definition at line 324 of file DisplayClusterHelpers.h.
References ExtractValue(), and ESearchCase::IgnoreCase.
ExtractValueFromString() [2/2]
template<typename TReturn> bool DisplayClusterHelpers::map::ExtractValueFromString (const TMap< FString, FString > & InMap, const FString & InKey, TReturn & OutValue, ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
Definition at line 310 of file DisplayClusterHelpers.h.
References ExtractValue(), and ESearchCase::IgnoreCase.