Unreal Engine 5.6 C++ API: FPooledRenderTargetDesc Struct Reference
FPooledRenderTargetDesc Struct Reference
All necessary data to create a render target from the pooled render targets.
#include "RendererInterface.h"
Public Member Functions
FPooledRenderTargetDesc ()
Default constructor, use one of the factory functions below to make a valid description.
bool Compare (const FPooledRenderTargetDesc &rhs, bool bExact) const
Comparison operator to test if a render target can be reused.
FString GenerateInfoString () const
for debugging purpose
FIntVector GetSize () const
bool Is2DTexture () const
bool Is3DTexture () const
bool IsArray () const
bool IsCubemap () const
bool IsValid () const
void Reset ()
Static Public Member Functions
static FPooledRenderTargetDesc Create2DArrayDesc (FIntPoint InExtent, EPixelFormat InFormat, const FClearValueBinding &InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint16 InArraySize, uint8 InNumMips=1, bool InAutowritable=true, bool InCreateRTWriteMask=false, bool InCreateFmask=false)
Factory function to create 2D array texture description.
static FPooledRenderTargetDesc Create2DDesc (FIntPoint InExtent, EPixelFormat InFormat, const FClearValueBinding &InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint8 InNumMips=1, bool InAutowritable=true, bool InCreateRTWriteMask=false, bool InCreateFmask=false)
Factory function to create 2D texture description.
static FPooledRenderTargetDesc CreateCubemapArrayDesc (uint32 InExtent, EPixelFormat InFormat, const FClearValueBinding &InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint16 InArraySize, uint8 InNumMips=1, bool InAutowritable=true)
Factory function to create cube map array texture description.
static FPooledRenderTargetDesc CreateCubemapDesc (uint32 InExtent, EPixelFormat InFormat, const FClearValueBinding &InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint16 InArraySize=1, uint8 InNumMips=1, bool InAutowritable=true)
Factory function to create cube map texture description.
static FPooledRenderTargetDesc CreateVolumeDesc (uint32 InSizeX, uint32 InSizeY, uint16 InSizeZ, EPixelFormat InFormat, const FClearValueBinding &InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint8 InNumMips=1, bool InAutowritable=true)
Factory function to create 3D texture description.
Data Fields
union {
struct {
uint8 bIsArray: 1
true if an array texture.
uint8 bIsCubemap: 1
true if a cubemap texture
uint8 bReserved0: 6
Unused flags.
}
uint8 PackedBits
};
uint16 ArraySize = 1
>1 if a texture array should be used (not supported on DX9)
FClearValueBinding ClearValue
Value allowed for fast clears for this target.
const TCHAR * DebugName = TEXT("UnknownTexture")
only set a pointer to memory that never gets released
uint16 Depth = 0
0, unless it's texture array or volume texture
FIntPoint Extent = FIntPoint::ZeroValue
In pixels, (0,0) if not set, (x,0) for cube maps, todo: make 3d int vector for volume textures.
uint8 FastVRAMPercentage = 0xFF
Resource memory percentage which should be allocated onto fast VRAM (hint-only).
ETextureCreateFlags Flags = TexCreate_None
The flags that must be set on both the shader-resource and the targetable texture.
EPixelFormat Format = PF_Unknown
Texture format e.g.
uint8 NumMips = 0
Number of mips.
uint8 NumSamples = 1
Number of MSAA samples, default: 1.
EPixelFormat UAVFormat = PF_Unknown
Texture format used when creating the UAV (if TexCreate_UAV is also passed in TargetableFlags, ignored otherwise).
Detailed Description
All necessary data to create a render target from the pooled render targets.
Definition at line 80 of file RendererInterface.h.
Constructor & Destructor Documentation
FPooledRenderTargetDesc()
FPooledRenderTargetDesc::FPooledRenderTargetDesc () inline
Default constructor, use one of the factory functions below to make a valid description.
Definition at line 85 of file RendererInterface.h.
References check, IsValid(), and PackedBits.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), and CreateVolumeDesc().
Member Function Documentation
Compare()
bool FPooledRenderTargetDesc::Compare (const FPooledRenderTargetDesc & rhs, bool bExact) const inline
Comparison operator to test if a render target can be reused.
Definition at line 268 of file RendererInterface.h.
References FPooledRenderTargetDesc(), ArraySize, ClearValue, Depth, Extent, FastVRAMPercentage, Flags, Format, NumMips, NumSamples, PackedBits, FGenericPlatformMemory::SupportsFastVRAMMemory(), and UAVFormat.
Create2DArrayDesc()
FPooledRenderTargetDesc FPooledRenderTargetDesc::Create2DArrayDesc (FIntPoint InExtent, EPixelFormat InFormat, const FClearValueBinding & InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint16 InArraySize, uint8 InNumMips = 1, bool InAutowritable = true, bool InCreateRTWriteMask = false, bool InCreateFmask = false) inline static
Factory function to create 2D array texture description.
Parameters
InFlags bit mask combined from elements of ETextureCreateFlags e.g. TexCreate_UAV
Definition at line 130 of file RendererInterface.h.
References FPooledRenderTargetDesc(), ArraySize, bIsArray, bIsCubemap, check, ClearValue, DebugName, Depth, Extent, Flags, Format, Is2DTexture(), NumMips, NumSamples, TEXT, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
Create2DDesc()
FPooledRenderTargetDesc FPooledRenderTargetDesc::Create2DDesc (FIntPoint InExtent, EPixelFormat InFormat, const FClearValueBinding & InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint8 InNumMips = 1, bool InAutowritable = true, bool InCreateRTWriteMask = false, bool InCreateFmask = false) inline static
Factory function to create 2D texture description.
Parameters
InFlags bit mask combined from elements of ETextureCreateFlags e.g. TexCreate_UAV
Definition at line 95 of file RendererInterface.h.
References FPooledRenderTargetDesc(), ArraySize, bIsArray, bIsCubemap, check, ClearValue, DebugName, Depth, Extent, Flags, Format, Is2DTexture(), NumMips, NumSamples, TEXT, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
CreateCubemapArrayDesc()
FPooledRenderTargetDesc FPooledRenderTargetDesc::CreateCubemapArrayDesc (uint32 InExtent, EPixelFormat InFormat, const FClearValueBinding & InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint16 InArraySize, uint8 InNumMips = 1, bool InAutowritable = true) inline static
Factory function to create cube map array texture description.
Parameters
InFlags bit mask combined from elements of ETextureCreateFlags e.g. TexCreate_UAV
Definition at line 237 of file RendererInterface.h.
References FPooledRenderTargetDesc(), ArraySize, bIsArray, bIsCubemap, check, ClearValue, DebugName, Depth, Extent, Flags, Format, IsCubemap(), NumMips, NumSamples, and TEXT.
CreateCubemapDesc()
FPooledRenderTargetDesc FPooledRenderTargetDesc::CreateCubemapDesc (uint32 InExtent, EPixelFormat InFormat, const FClearValueBinding & InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint16 InArraySize = 1, uint8 InNumMips = 1, bool InAutowritable = true) inline static
Factory function to create cube map texture description.
Parameters
InFlags bit mask combined from elements of ETextureCreateFlags e.g. TexCreate_UAV
Definition at line 202 of file RendererInterface.h.
References FPooledRenderTargetDesc(), ArraySize, bIsArray, bIsCubemap, check, ClearValue, DebugName, Depth, Extent, Flags, Format, IsCubemap(), NumMips, NumSamples, and TEXT.
CreateVolumeDesc()
FPooledRenderTargetDesc FPooledRenderTargetDesc::CreateVolumeDesc (uint32 InSizeX, uint32 InSizeY, uint16 InSizeZ, EPixelFormat InFormat, const FClearValueBinding & InClearValue, ETextureCreateFlags InFlags, ETextureCreateFlags InTargetableFlags, bool bInForceSeparateTargetAndShaderResource, uint8 InNumMips = 1, bool InAutowritable = true) inline static
Factory function to create 3D texture description.
Parameters
InFlags bit mask combined from elements of ETextureCreateFlags e.g. TexCreate_UAV
Definition at line 167 of file RendererInterface.h.
References FPooledRenderTargetDesc(), ArraySize, bIsArray, bIsCubemap, check, ClearValue, DebugName, Depth, Extent, Flags, Format, Is3DTexture(), NumMips, NumSamples, and TEXT.
GenerateInfoString()
FString FPooledRenderTargetDesc::GenerateInfoString () const inline
for debugging purpose
Returns
e.g. (2D 128x64 PF_R8)
Definition at line 342 of file RendererInterface.h.
References ArraySize, Depth, EnumHasAnyFlags(), Extent, Flags, Format, GetPixelFormatString(), Is2DTexture(), Is3DTexture(), IsArray(), IsCubemap(), NumSamples, and TEXT.
GetSize()
FIntVector FPooledRenderTargetDesc::GetSize () const inline
Definition at line 333 of file RendererInterface.h.
References Depth, and Extent.
Is2DTexture()
bool FPooledRenderTargetDesc::Is2DTexture () const inline
Definition at line 297 of file RendererInterface.h.
References bIsCubemap, Depth, and Extent.
Referenced by Create2DArrayDesc(), Create2DDesc(), GenerateInfoString(), and IsValid().
Is3DTexture()
bool FPooledRenderTargetDesc::Is3DTexture () const inline
Definition at line 302 of file RendererInterface.h.
References bIsCubemap, Depth, and Extent.
Referenced by CreateVolumeDesc(), and GenerateInfoString().
IsArray()
bool FPooledRenderTargetDesc::IsArray () const inline
Definition at line 308 of file RendererInterface.h.
References bIsArray.
Referenced by GenerateInfoString().
IsCubemap()
bool FPooledRenderTargetDesc::IsCubemap () const inline
Definition at line 292 of file RendererInterface.h.
References bIsCubemap.
Referenced by CreateCubemapArrayDesc(), CreateCubemapDesc(), and GenerateInfoString().
IsValid()
bool FPooledRenderTargetDesc::IsValid () const inline
Definition at line 313 of file RendererInterface.h.
References EnumHasAnyFlags(), Extent, Flags, Format, Is2DTexture(), NumMips, NumSamples, and PF_Unknown.
Referenced by FPooledRenderTargetDesc().
Reset()
void FPooledRenderTargetDesc::Reset () inline
Definition at line 398 of file RendererInterface.h.
References Flags, and NumSamples.
Field Documentation
[union]
union { ... } FPooledRenderTargetDesc
ArraySize
uint16 FPooledRenderTargetDesc::ArraySize = 1
>1 if a texture array should be used (not supported on DX9)
Definition at line 423 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), and GenerateInfoString().
bIsArray
uint8 FPooledRenderTargetDesc::bIsArray
true if an array texture.
Note that ArraySize still can be 1
Definition at line 435 of file RendererInterface.h.
Referenced by Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), and IsArray().
bIsCubemap
uint8 FPooledRenderTargetDesc::bIsCubemap
true if a cubemap texture
Definition at line 437 of file RendererInterface.h.
Referenced by Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), Is2DTexture(), Is3DTexture(), and IsCubemap().
bReserved0
uint8 FPooledRenderTargetDesc::bReserved0
Unused flags.
Definition at line 439 of file RendererInterface.h.
ClearValue
FClearValueBinding FPooledRenderTargetDesc::ClearValue
Value allowed for fast clears for this target.
Definition at line 411 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), and CreateVolumeDesc().
DebugName
const TCHAR* FPooledRenderTargetDesc::DebugName = TEXT("UnknownTexture")
only set a pointer to memory that never gets released
Definition at line 409 of file RendererInterface.h.
Referenced by Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), and CreateVolumeDesc().
Depth
uint16 FPooledRenderTargetDesc::Depth = 0
0, unless it's texture array or volume texture
Definition at line 421 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), GenerateInfoString(), GetSize(), Is2DTexture(), and Is3DTexture().
Extent
FIntPoint FPooledRenderTargetDesc::Extent = FIntPoint::ZeroValue
In pixels, (0,0) if not set, (x,0) for cube maps, todo: make 3d int vector for volume textures.
Definition at line 419 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), GenerateInfoString(), GetSize(), Is2DTexture(), Is3DTexture(), and IsValid().
FastVRAMPercentage
uint8 FPooledRenderTargetDesc::FastVRAMPercentage = 0xFF
Resource memory percentage which should be allocated onto fast VRAM (hint-only).
(encoding into 8bits, 0..255 -> 0%..100%)
Definition at line 429 of file RendererInterface.h.
Referenced by Compare().
Flags
ETextureCreateFlags FPooledRenderTargetDesc::Flags = TexCreate_None
The flags that must be set on both the shader-resource and the targetable texture.
bit mask combined from elements of ETextureCreateFlags e.g. TexCreate_UAV
Definition at line 413 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), GenerateInfoString(), IsValid(), and Reset().
Format
EPixelFormat FPooledRenderTargetDesc::Format = PF_Unknown
Texture format e.g.
PF_B8G8R8A8
Definition at line 415 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), GenerateInfoString(), and IsValid().
NumMips
uint8 FPooledRenderTargetDesc::NumMips = 0
Number of mips.
Definition at line 425 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), and IsValid().
NumSamples
uint8 FPooledRenderTargetDesc::NumSamples = 1
Number of MSAA samples, default: 1.
Definition at line 427 of file RendererInterface.h.
Referenced by Compare(), Create2DArrayDesc(), Create2DDesc(), CreateCubemapArrayDesc(), CreateCubemapDesc(), CreateVolumeDesc(), GenerateInfoString(), IsValid(), and Reset().
PackedBits
uint8 FPooledRenderTargetDesc::PackedBits
Definition at line 441 of file RendererInterface.h.
Referenced by FPooledRenderTargetDesc(), and Compare().
UAVFormat
EPixelFormat FPooledRenderTargetDesc::UAVFormat = PF_Unknown
Texture format used when creating the UAV (if TexCreate_UAV is also passed in TargetableFlags, ignored otherwise).
PF_Unknown == use default (same as Format)
Definition at line 417 of file RendererInterface.h.
Referenced by Compare().
The documentation for this struct was generated from the following file:
RendererInterface.h