Unreal Engine 5.6 C++ API: UE::MovieScene::IEntitySystemScheduler Class Reference
UE::MovieScene::IEntitySystemScheduler Class Reference
#include "IMovieSceneTaskScheduler.h"
Public Member Functions
MOVIESCENE_API void AddChildBack (FTaskID Parent, FTaskID Child)
Add a child to the front of a previously created 'forked' task.
MOVIESCENE_API void AddChildFront (FTaskID Parent, FTaskID Child)
Add a child to the back of a previously created 'forked' task.
template<typename TaskType>
FTaskID AddMemberFunctionTask (const FTaskParams &InParams, TaskType *Instance, typename TMemberFunctionTaskWrapper< TaskType >::MemberFunctionPtr FunctionPtr)
Add a new task that calls a member function of the type void (*)()
MOVIESCENE_API FTaskID AddNullTask ()
Add a 'null' task that can be used to join many tasks into a single dependency.
MOVIESCENE_API void AddPrerequisite (FTaskID Prerequisite, FTaskID Subsequent)
Define a prerequisite for the given task.
template<typename TaskType, typename ... TaskArgTypes>
FTaskID AddTask (const FTaskParams &InParams, TaskArgTypes &&... Args)
Add a new task of the specified type for the currently open node ID.
MOVIESCENE_API FTaskID AddTask (const FTaskParams &InParams, TSharedPtr< ITaskContext > InTaskContext, TaskFunctionPtr InTaskFunction)
Add an anonymous unbound task for doing non-ecs work.
MOVIESCENE_API FTaskID CreateForkedAllocationTask (const FTaskParams &InParams, TSharedPtr< ITaskContext > InTaskContext, TaskFunctionPtr InTaskFunction, TFunctionRef< void(FEntityAllocationIteratorItem, TArray< FPreLockedDataPtr > &)> InPreLockFunc, const FEntityComponentFilter &Filter, const FComponentMask &ReadDeps, const FComponentMask &WriteDeps)
Create one task for each of the entity allocations that match the specified filter.
Private Member Functions
IEntitySystemScheduler ()=default
Friends
class FEntitySystemScheduler
Detailed Description
Definition at line 161 of file IMovieSceneTaskScheduler.h.
Constructor & Destructor Documentation
IEntitySystemScheduler()
UE::MovieScene::IEntitySystemScheduler::IEntitySystemScheduler () private default
Member Function Documentation
AddChildBack()
MOVIESCENE_API void UE::MovieScene::IEntitySystemScheduler::AddChildBack (FTaskID Parent, FTaskID Child)
Add a child to the front of a previously created 'forked' task.
Used for defining 'PreTask' work
References Child, and Parent.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), and UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl().
AddChildFront()
MOVIESCENE_API void UE::MovieScene::IEntitySystemScheduler::AddChildFront (FTaskID Parent, FTaskID Child)
Add a child to the back of a previously created 'forked' task.
Used for defining 'PostTask' work
References Child, and Parent.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), and UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl().
AddMemberFunctionTask()
template<typename TaskType> FTaskID UE::MovieScene::IEntitySystemScheduler::AddMemberFunctionTask (const FTaskParams & InParams, TaskType * Instance, typename TMemberFunctionTaskWrapper< TaskType >::MemberFunctionPtr FunctionPtr) inline
Add a new task that calls a member function of the type void (*)()
Example usage: TaskScheduler->AddTask(FTaskParams(GET_STAT_ID(StatId)), this, &UMyClass::ResetWeights);
Definition at line 186 of file IMovieSceneTaskScheduler.h.
References AddTask(), UE::MovieScene::TMemberFunctionTaskWrapper< ClassType >::Execute(), Function, Instance, and MakeShared().
Referenced by UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule().
AddNullTask()
MOVIESCENE_API FTaskID UE::MovieScene::IEntitySystemScheduler::AddNullTask ()
Add a 'null' task that can be used to join many tasks into a single dependency.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), and UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl().
AddPrerequisite()
MOVIESCENE_API void UE::MovieScene::IEntitySystemScheduler::AddPrerequisite (FTaskID Prerequisite, FTaskID Subsequent)
Define a prerequisite for the given task.
Referenced by UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule().
AddTask() [1/2]
template<typename TaskType, typename ... TaskArgTypes> FTaskID UE::MovieScene::IEntitySystemScheduler::AddTask (const FTaskParams & InParams, TaskArgTypes &&... Args) inline
Add a new task of the specified type for the currently open node ID.
Example usage: TaskScheduler->AddTask<FMyTaskType>(FTaskParams(GET_STAT_ID(StatId))); TaskScheduler->AddTask<FMyTaskType2>(FTaskParams(GET_STAT_ID(StatId)), ConstructorArg1, ConstructorArg2);
Definition at line 173 of file IMovieSceneTaskScheduler.h.
References AddTask(), UE::MovieScene::TAnonTaskWrapper< TaskType >::Execute(), Forward(), Function, and MakeShared().
Referenced by AddMemberFunctionTask(), AddTask(), UE::MovieScene::SchedulePostTask(), and UE::MovieScene::SchedulePreTask().
AddTask() [2/2]
MOVIESCENE_API FTaskID UE::MovieScene::IEntitySystemScheduler::AddTask (const FTaskParams & InParams, TSharedPtr< ITaskContext > InTaskContext, TaskFunctionPtr InTaskFunction)
Add an anonymous unbound task for doing non-ecs work.
CreateForkedAllocationTask()
MOVIESCENE_API FTaskID UE::MovieScene::IEntitySystemScheduler::CreateForkedAllocationTask (const FTaskParams & InParams, TSharedPtr< ITaskContext > InTaskContext, TaskFunctionPtr InTaskFunction, TFunctionRef< void(FEntityAllocationIteratorItem, TArray< FPreLockedDataPtr > &)> InPreLockFunc, const FEntityComponentFilter & Filter, const FComponentMask & ReadDeps, const FComponentMask & WriteDeps)
Create one task for each of the entity allocations that match the specified filter.
References Filter.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), and UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl().
Friends And Related Symbol Documentation
FEntitySystemScheduler
friend class FEntitySystemScheduler friend
Definition at line 223 of file IMovieSceneTaskScheduler.h.
References FEntitySystemScheduler.
Referenced by FEntitySystemScheduler.
The documentation for this class was generated from the following file:
IMovieSceneTaskScheduler.h