Unreal Engine 5.6 C++ API: TFieldIterator< T > Class Template Reference
TFieldIterator< T > Class Template Reference
#include "UnrealType.h"
Public Member Functions
TFieldIterator (const UStruct *InStruct, EFieldIterationFlags InIterationFlags=EFieldIterationFlags::Default)
TFieldIterator (const UStruct *InStruct, EFieldIteratorFlags::SuperClassFlags InSuperClassFlags, EFieldIteratorFlags::DeprecatedPropertyFlags InDeprecatedFieldFlags=EFieldIteratorFlags::IncludeDeprecated, EFieldIteratorFlags::InterfaceClassFlags InInterfaceFieldFlags=EFieldIteratorFlags::ExcludeInterfaces)
Legacy version taking the flags as 3 separate values.
const UStruct * GetStruct ()
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
bool operator!= (const TFieldIterator< T > &Rhs) const
T * operator* ()
const T * operator* () const
void operator++ ()
T * operator-> ()
bool operator== (const TFieldIterator< T > &Rhs) const
Protected Member Functions
void IterateToNext ()
Private Attributes
const bool bIncludeDeprecated
Whether to include deprecated fields or not.
const bool bIncludeInterface
Whether to include interface fields or not.
const bool bIncludeSuper
Whether to include the super class or not.
T::BaseFieldClass * Field
The current location in the list of fields being iterated.
int32 InterfaceIndex
The index of the current interface being iterated.
const UStruct * Struct
The object being searched for the specified field.
Detailed Description
template<class T>
class TFieldIterator< T >
Definition at line 6659 of file UnrealType.h.
Constructor & Destructor Documentation
TFieldIterator() [1/2]
template<class T> TFieldIterator< T >::TFieldIterator (const UStruct * InStruct, EFieldIterationFlags InIterationFlags = EFieldIterationFlags::Default) inline
Definition at line 6676 of file UnrealType.h.
References bIncludeDeprecated, bIncludeInterface, bIncludeSuper, Default, EnumHasAnyFlags(), Field, GetChildFieldsFromStruct(), IncludeDeprecated, IncludeInterfaces, IncludeSuper, InterfaceIndex, IterateToNext(), StaticClass(), and Struct.
Referenced by TFieldIterator(), operator!=(), and operator==().
TFieldIterator() [2/2]
template<class T> TFieldIterator< T >::TFieldIterator (const UStruct * InStruct, EFieldIteratorFlags::SuperClassFlags InSuperClassFlags, EFieldIteratorFlags::DeprecatedPropertyFlags InDeprecatedFieldFlags = EFieldIteratorFlags::IncludeDeprecated, EFieldIteratorFlags::InterfaceClassFlags InInterfaceFieldFlags = EFieldIteratorFlags::ExcludeInterfaces) inline
Legacy version taking the flags as 3 separate values.
Definition at line 6688 of file UnrealType.h.
References TFieldIterator(), EFieldIteratorFlags::ExcludeInterfaces, and EFieldIteratorFlags::IncludeDeprecated.
Member Function Documentation
GetStruct()
template<class T> const UStruct * TFieldIterator< T >::GetStruct () inline
Definition at line 6731 of file UnrealType.h.
References Struct.
IterateToNext()
template<class T> void TFieldIterator< T >::IterateToNext () inline protected
Definition at line 6736 of file UnrealType.h.
References bIncludeDeprecated, bIncludeInterface, bIncludeSuper, CASTCLASS_FProperty, Field, GetChildFieldsFromStruct(), UStruct::GetInheritanceSuper(), FProperty::HasAllPropertyFlags(), Interface, InterfaceIndex, UClass::Interfaces, and Struct.
Referenced by TFieldIterator(), and operator++().
operator bool()
template<class T> FORCEINLINE TFieldIterator< T >::operator bool () const inline explicit
conversion to "bool" returning true if the iterator is valid.
Definition at line 6697 of file UnrealType.h.
References Field, and FORCEINLINE.
operator!()
template<class T> FORCEINLINE bool TFieldIterator< T >::operator! () const inline
inverse of the "bool" operator
Definition at line 6702 of file UnrealType.h.
References bool, and FORCEINLINE.
operator!=()
template<class T> bool TFieldIterator< T >::operator!= (const TFieldIterator< T > & Rhs) const inline
Definition at line 6708 of file UnrealType.h.
References TFieldIterator(), and Field.
operator*() [1/2]
template<class T> T * TFieldIterator< T >::operator* () inline
Definition at line 6716 of file UnrealType.h.
References checkSlow, and Field.
operator*() [2/2]
template<class T> const T * TFieldIterator< T >::operator* () const inline
Definition at line 6721 of file UnrealType.h.
References checkSlow, and Field.
operator++()
template<class T> void TFieldIterator< T >::operator++ () inline
Definition at line 6710 of file UnrealType.h.
References checkSlow, Field, and IterateToNext().
operator->()
template<class T> T * TFieldIterator< T >::operator-> () inline
Definition at line 6726 of file UnrealType.h.
References checkSlow, and Field.
operator==()
template<class T> bool TFieldIterator< T >::operator== (const TFieldIterator< T > & Rhs) const inline
Definition at line 6707 of file UnrealType.h.
References TFieldIterator(), and Field.
Field Documentation
bIncludeDeprecated
template<class T> const bool TFieldIterator< T >::bIncludeDeprecated private
Whether to include deprecated fields or not.
Definition at line 6671 of file UnrealType.h.
Referenced by TFieldIterator(), and IterateToNext().
bIncludeInterface
template<class T> const bool TFieldIterator< T >::bIncludeInterface private
Whether to include interface fields or not.
Definition at line 6673 of file UnrealType.h.
Referenced by TFieldIterator(), and IterateToNext().
bIncludeSuper
template<class T> const bool TFieldIterator< T >::bIncludeSuper private
Whether to include the super class or not.
Definition at line 6669 of file UnrealType.h.
Referenced by TFieldIterator(), and IterateToNext().
Field
template<class T> T::BaseFieldClass* TFieldIterator< T >::Field private
The current location in the list of fields being iterated.
Definition at line 6665 of file UnrealType.h.
Referenced by TFieldIterator(), IterateToNext(), operator bool(), operator!=(), operator*(), operator*(), operator++(), operator->(), and operator==().
InterfaceIndex
template<class T> int32 TFieldIterator< T >::InterfaceIndex private
The index of the current interface being iterated.
Definition at line 6667 of file UnrealType.h.
Referenced by TFieldIterator(), and IterateToNext().
Struct
template<class T> const UStruct* TFieldIterator< T >::Struct private
The object being searched for the specified field.
Definition at line 6663 of file UnrealType.h.
Referenced by TFieldIterator(), GetStruct(), and IterateToNext().
The documentation for this class was generated from the following file:
UnrealType.h