Unreal Engine 5.6 C++ API: UE::Geometry::FPolygonEdgeMeshGenerator Class Reference
UE::Geometry::FPolygonEdgeMeshGenerator Class Reference
Mesh generator that generates a quad for each edge of a closed polygon.
#include "PolygonEdgeMeshGenerator.h"
Public Member Functions
GEOMETRYCORE_API FPolygonEdgeMeshGenerator (const TArray< FFrame3d > &InPolygon, bool bInClosed, const TArray< double > &InOffsetScaleFactors, double InWidth=1.0, FVector3d InNormal=FVector3d::UnitZ(), bool bInRoundedCorners=false, double InCornerRadius=0.0, bool bInLimitCornerRadius=false, int InNumArcVertices=3)
GEOMETRYCORE_API ~FPolygonEdgeMeshGenerator ()
virtual GEOMETRYCORE_API FMeshShapeGenerator & Generate () final
Subclasses implement this to generate mesh.
Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
virtual ~FMeshShapeGenerator ()
int AppendNormal (const FVector3f &Normal, int ParentVertex)
int AppendTriangle (int A, int B, int C)
int AppendUV (const FVector2f &UV, int ParentVertex)
int AppendVertex (const FVector3d &Position)
Append a new vertex at the given Position.
void ExtendBufferSizes (int AddVertices, int AddTriangles, int AddUVs, int AddNormals)
Extends the various internal buffers to the correct sizes for the given additional element counts.
bool HasAttributes () const
void Reset ()
clear arrays so that Generate() can be run again
void ResetAttributes (bool bResetPolygonIDs=false)
void SetBufferSizes (int NumVertices, int NumTriangles, int NumUVs, int NumNormals)
Set the various internal buffers to the correct sizes for the given element counts.
void SetNormal (int Index, const FVector3f &Normal, int ParentVertex)
Set Normal at Index to given value with given ParentVertex.
void SetTriangle (int Index, const FIndex3i &Tri)
void SetTriangle (int Index, int A, int B, int C)
void SetTriangle (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleNormals (int Index, const FIndex3i &Tri)
void SetTriangleNormals (int Index, int A, int B, int C)
void SetTriangleNormals (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTrianglePolygon (int Index, int PolygonID)
void SetTriangleUVs (int Index, const FIndex3i &Tri)
void SetTriangleUVs (int Index, int A, int B, int C)
void SetTriangleUVs (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleWithMatchedUVNormal (int Index, int A, int B, int C)
Set triangle and UVs and normals with matching indices Convenience function for shapes with no uv or normal seams.
void SetUV (int Index, const FVector2f &UV, int ParentVertex)
Set UV at Index to given value with given ParentVertex.
void SetVertex (int Index, const FVector3d &Position)
Set vertex at Index to given Position.
Data Fields
bool bLimitCornerRadius = false
Limit corner radius to prevent overlapping.
bool bRoundedCorners = false
Use arc segments instead of straight lines in corners.
bool bScaleUVByAspectRatio = true
bool bSinglePolyGroup = false
If true, output mesh has a single polygroup, otherwise each quad gets a separate group.
double CornerRadius = 0.0
Radius of the corner arcs; this is only available if Rounded Corners is enabled.
int NumArcVertices
Number of radial subdivisions for rounded corners.
double UVHeight = 1.0
double UVWidth = 1.0
Data Fields inherited from UE::Geometry::FMeshShapeGenerator
bool bReverseOrientation = false
If true, reverse orientation of created mesh.
TArray< int > NormalParentVertex
Parent vertex index for each Normal.
TArray< FVector3f > Normals
Array of Normals.
TArray< FIndex3i > TriangleNormals
Array of triangle corner Normals, stored as tuples of indices into Normals array.
TArray< int > TrianglePolygonIDs
Array of per-triangle integer polygon IDs.
TArray< FIndex3i > Triangles
Array of triangle corner positions, stored as tuples of indices into Vertices array.
TArray< FIndex3i > TriangleUVs
Array of triangle corner UVs, stored as tuples of indices into UVs array.
TArray< int > UVParentVertex
Parent vertex index for each UV.
TArray< FVector2f > UVs
Array of UV positions.
TArray< FVector3d > Vertices
Array of vertex positions.
Private Member Functions
void CurvePath (const TArray< FVector3d > &InPath, const TArray< bool > &InteriorAngleFlag, const TArray< double > &MaxCornerRadii, const TArray< double > &OtherSideMaxCornerRadii, const FFrame3d &PolygonFrame, TArray< FVector3d > &OutPath) const
Private Attributes
bool bClosed
FVector3d Normal = FVector3d::UnitZ()
TArray< double > OffsetScaleFactors
TArray< FFrame3d > Polygon
double Width = 1.0
Additional Inherited Members
Static Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
static FVector2d BilinearInterp (const FVector2d &v00, const FVector2d &v10, const FVector2d &v11, const FVector2d &v01, double tx, double ty)
static FVector2f BilinearInterp (const FVector2f &v00, const FVector2f &v10, const FVector2f &v11, const FVector2f &v01, float tx, float ty)
static FVector3d BilinearInterp (const FVector3d &v00, const FVector3d &v10, const FVector3d &v11, const FVector3d &v01, double tx, double ty)
static FVector3i LinearInterp (const FVector3i &a, const FVector3i &b, double t)
Detailed Description
Mesh generator that generates a quad for each edge of a closed polygon.
Definition at line 17 of file PolygonEdgeMeshGenerator.h.
Constructor & Destructor Documentation
FPolygonEdgeMeshGenerator()
GEOMETRYCORE_API UE::Geometry::FPolygonEdgeMeshGenerator::FPolygonEdgeMeshGenerator (const TArray< FFrame3d > & InPolygon, bool bInClosed, const TArray< double > & InOffsetScaleFactors, double InWidth = 1.0, FVector3d InNormal = FVector3d::UnitZ(), bool bInRoundedCorners = false, double InCornerRadius = 0.0, bool bInLimitCornerRadius = false, int InNumArcVertices = 3)
References UE::Math::TVector< double >::UnitZ().
~FPolygonEdgeMeshGenerator()
GEOMETRYCORE_API UE::Geometry::FPolygonEdgeMeshGenerator::~FPolygonEdgeMeshGenerator ()
Member Function Documentation
CurvePath()
void UE::Geometry::FPolygonEdgeMeshGenerator::CurvePath (const TArray< FVector3d > & InPath, const TArray< bool > & InteriorAngleFlag, const TArray< double > & MaxCornerRadii, const TArray< double > & OtherSideMaxCornerRadii, const FFrame3d & PolygonFrame, TArray< FVector3d > & OutPath) const private
References CurvePath().
Referenced by CurvePath().
Generate()
virtual GEOMETRYCORE_API FMeshShapeGenerator & UE::Geometry::FPolygonEdgeMeshGenerator::Generate () final virtual
Subclasses implement this to generate mesh.
Implements UE::Geometry::FMeshShapeGenerator.
Field Documentation
bClosed
bool UE::Geometry::FPolygonEdgeMeshGenerator::bClosed private
Definition at line 27 of file PolygonEdgeMeshGenerator.h.
bLimitCornerRadius
bool UE::Geometry::FPolygonEdgeMeshGenerator::bLimitCornerRadius = false
Limit corner radius to prevent overlapping.
Definition at line 55 of file PolygonEdgeMeshGenerator.h.
bRoundedCorners
bool UE::Geometry::FPolygonEdgeMeshGenerator::bRoundedCorners = false
Use arc segments instead of straight lines in corners.
Definition at line 49 of file PolygonEdgeMeshGenerator.h.
bScaleUVByAspectRatio
bool UE::Geometry::FPolygonEdgeMeshGenerator::bScaleUVByAspectRatio = true
Definition at line 43 of file PolygonEdgeMeshGenerator.h.
bSinglePolyGroup
bool UE::Geometry::FPolygonEdgeMeshGenerator::bSinglePolyGroup = false
If true, output mesh has a single polygroup, otherwise each quad gets a separate group.
Definition at line 46 of file PolygonEdgeMeshGenerator.h.
CornerRadius
double UE::Geometry::FPolygonEdgeMeshGenerator::CornerRadius = 0.0
Radius of the corner arcs; this is only available if Rounded Corners is enabled.
Definition at line 52 of file PolygonEdgeMeshGenerator.h.
Normal
FVector3d UE::Geometry::FPolygonEdgeMeshGenerator::Normal = FVector3d::UnitZ() private
Definition at line 37 of file PolygonEdgeMeshGenerator.h.
NumArcVertices
int UE::Geometry::FPolygonEdgeMeshGenerator::NumArcVertices
Number of radial subdivisions for rounded corners.
Definition at line 58 of file PolygonEdgeMeshGenerator.h.
OffsetScaleFactors
TArray<double> UE::Geometry::FPolygonEdgeMeshGenerator::OffsetScaleFactors private
Definition at line 31 of file PolygonEdgeMeshGenerator.h.
Polygon
TArray<FFrame3d> UE::Geometry::FPolygonEdgeMeshGenerator::Polygon private
Definition at line 24 of file PolygonEdgeMeshGenerator.h.
UVHeight
double UE::Geometry::FPolygonEdgeMeshGenerator::UVHeight = 1.0
Definition at line 42 of file PolygonEdgeMeshGenerator.h.
UVWidth
double UE::Geometry::FPolygonEdgeMeshGenerator::UVWidth = 1.0
Definition at line 41 of file PolygonEdgeMeshGenerator.h.
Width
double UE::Geometry::FPolygonEdgeMeshGenerator::Width = 1.0 private
Definition at line 34 of file PolygonEdgeMeshGenerator.h.
The documentation for this class was generated from the following file:
PolygonEdgeMeshGenerator.h