Unreal Engine 5.6 C++ API: EditorAnimUtils Namespace Reference
EditorAnimUtils Namespace Reference
Data Structures
class FAnimationRetargetContext
struct FNameDuplicationRule
Functions
template<class AssetType>
TMap< AssetType *, AssetType * > DuplicateAssets (const TArray< AssetType * > &AssetsToDuplicate, UPackage *DestinationPackage, const FNameDuplicationRule *NameRule)
Duplicates the supplied AssetsToDuplicate and returns a map of original asset to duplicate.
UNREALED_API TMap< UObject *, UObject * > DuplicateAssetsInternal (const TArray< UObject * > &AssetsToDuplicate, UPackage *DestinationPackage, const FNameDuplicationRule *NameRule)
Duplicates the supplied AssetsToDuplicate and returns a map of original asset to duplicate.
UNREALED_API void GetAllAnimationSequencesReferredInBlueprint (UAnimBlueprint *AnimBlueprint, TArray< UAnimationAsset * > &AnimationAsset)
template<class AssetType>
void GetAssetsFromProperties (TArray< FProperty * > InProperties, UObject *Scope, TArray< AssetType * > &OutAssets)
UNREALED_API void ReplaceReferredAnimationsInBlueprint (UAnimBlueprint *AnimBlueprint, const TMap< UAnimationAsset *, UAnimationAsset * > &AnimAssetReplacementMap)
UNREALED_API UObject * RetargetAnimations (USkeleton *OldSkeleton, USkeleton *NewSkeleton, const TArray< FAssetData > &AssetsToRetarget, bool bRetargetReferredAssets, const FNameDuplicationRule *NameRule, bool bConvertSpace)
Retargets the supplied FAssetDatas (as long as they are an animation asset), optionally duplicating them and retargetting their reference assets too.
UNREALED_API UObject * RetargetAnimations (USkeleton *OldSkeleton, USkeleton *NewSkeleton, FAnimationRetargetContext &RetargetContext, bool bRetargetReferredAssets, const FNameDuplicationRule *NameRule)
Retargets the supplied FAnimationRetargetContext, optionally duplicating the assets and retargeting the assets reference assets too.
UNREALED_API UObject * RetargetAnimations (USkeleton *OldSkeleton, USkeleton *NewSkeleton, TArray< TWeakObjectPtr< UObject > > AssetsToRetarget, bool bRetargetReferredAssets, const FNameDuplicationRule *NameRule, bool bConvertSpace)
Retargets the supplied UObjects (as long as they are an animation asset), optionally duplicating them and retargeting their reference assets too.
UE_DEPRECATED (5.0, "CopyAnimCurves has been deprecated, see UAnimationBlueprintLibrary::CopyAnimationCurveNamesToSkeleton instead") UNREALED_API void CopyAnimCurves(USkeleton *OldSkeleton
Variables
USkeleton UAnimSequenceBase const FName ContainerName
USkeleton UAnimSequenceBase const FName ERawCurveTrackTypes CurveType
USkeleton * NewSkeleton
USkeleton UAnimSequenceBase * SequenceBase
Function Documentation
DuplicateAssets()
template<class AssetType> TMap< AssetType *, AssetType * > EditorAnimUtils::DuplicateAssets (const TArray< AssetType * > & AssetsToDuplicate, UPackage * DestinationPackage, const FNameDuplicationRule * NameRule)
Duplicates the supplied AssetsToDuplicate and returns a map of original asset to duplicate.
Templated wrapper that calls DuplicateAssetInternal.
Parameters
AssetsToDuplicate The animations to duplicate
DestinationPackage The package that the duplicates should be placed in
NameRule Options for renaming the file, adding prefix/suffix or search/replace
Returns
TMap of original animation to duplicate
Definition at line 143 of file EditorAnimUtils.h.
References TArray< InElementType, InAllocatorType >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), Cast(), TArray< InElementType, InAllocatorType >::CreateConstIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CreateIterator(), and DuplicateAssetsInternal().
DuplicateAssetsInternal()
UNREALED_API TMap< UObject *, UObject * > EditorAnimUtils::DuplicateAssetsInternal (const TArray< UObject * > & AssetsToDuplicate, UPackage * DestinationPackage, const FNameDuplicationRule * NameRule)
Duplicates the supplied AssetsToDuplicate and returns a map of original asset to duplicate.
Parameters
AssetsToDuplicate The animations to duplicate
DestinationPackage The package that the duplicates should be placed in
NameRule Options for renaming the file, adding prefix/suffix or search/replace
Returns
TMap of original animation to duplicate
Referenced by DuplicateAssets().
GetAllAnimationSequencesReferredInBlueprint()
UNREALED_API void EditorAnimUtils::GetAllAnimationSequencesReferredInBlueprint (UAnimBlueprint * AnimBlueprint, TArray< UAnimationAsset * > & AnimationAsset)
GetAssetsFromProperties()
template<class AssetType> void EditorAnimUtils::GetAssetsFromProperties (TArray< FProperty * > InProperties, UObject * Scope, TArray< AssetType * > & OutAssets)
Definition at line 162 of file EditorAnimUtils.h.
References TArray< InElementType, InAllocatorType >::Add(), Asset, Cast(), CastField(), check, TArray< InElementType, InAllocatorType >::Empty(), FScriptArrayHelper::GetRawPtr(), FScriptArrayHelper::Num(), and Object.
ReplaceReferredAnimationsInBlueprint()
UNREALED_API void EditorAnimUtils::ReplaceReferredAnimationsInBlueprint (UAnimBlueprint * AnimBlueprint, const TMap< UAnimationAsset *, UAnimationAsset * > & AnimAssetReplacementMap)
RetargetAnimations() [1/3]
UNREALED_API UObject * EditorAnimUtils::RetargetAnimations (USkeleton * OldSkeleton, USkeleton * NewSkeleton, const TArray< FAssetData > & AssetsToRetarget, bool bRetargetReferredAssets, const FNameDuplicationRule * NameRule, bool bConvertSpace)
Retargets the supplied FAssetDatas (as long as they are an animation asset), optionally duplicating them and retargetting their reference assets too.
Parameters
NewSkeleton The skeleton the supplied assets should be retargeted to
AssetsToRetarget The animation assets to copy/retarget
bRetargetReferredAssets If true retargets any assets referred to by assets in AssetsToRetarget. If false then the references are cleared.
bDuplicatedAssetsBeforeRetarget If true the assets are duplicated and then the duplicates are retargeted
bConvertSpace Do the conversion in component space of the animation to match new target
References NewSkeleton.
RetargetAnimations() [2/3]
UNREALED_API UObject * EditorAnimUtils::RetargetAnimations (USkeleton * OldSkeleton, USkeleton * NewSkeleton, FAnimationRetargetContext & RetargetContext, bool bRetargetReferredAssets, const FNameDuplicationRule * NameRule)
Retargets the supplied FAnimationRetargetContext, optionally duplicating the assets and retargeting the assets reference assets too.
Is called by other overloads of RetargetAnimations
Parameters
NewSkeleton The skeleton the supplied assets should be retargeted to
AssetsToRetarget The animation assets to copy/retarget
bRetargetReferredAssets If true retargets any assets referred to by assets in AssetsToRetarget. If false then the references are cleared.
bDuplicatedAssetsBeforeRetarget If true the assets are duplicated and then the duplicates are retargeted
bConvertSpace Do the conversion in component space of the animation to match new target
References NewSkeleton.
RetargetAnimations() [3/3]
UNREALED_API UObject * EditorAnimUtils::RetargetAnimations (USkeleton * OldSkeleton, USkeleton * NewSkeleton, TArray< TWeakObjectPtr< UObject > > AssetsToRetarget, bool bRetargetReferredAssets, const FNameDuplicationRule * NameRule, bool bConvertSpace)
Retargets the supplied UObjects (as long as they are an animation asset), optionally duplicating them and retargeting their reference assets too.
Parameters
NewSkeleton The skeleton the supplied assets should be retargeted to
AssetsToRetarget The animation assets to copy/retarget
bRetargetReferredAssets If true retargets any assets referred to by assets in AssetsToRetarget. If false then the references are cleared.
bDuplicatedAssetsBeforeRetarget If true the assets are duplicated and then the duplicates are retargeted
bConvertSpace Do the conversion in component space of the animation to match new target
References NewSkeleton.
UE_DEPRECATED()
EditorAnimUtils::UE_DEPRECATED (5. 0, "CopyAnimCurves has been deprecated , see UAnimationBlueprintLibrary::CopyAnimationCurveNamesToSkeleton instead")
Variable Documentation
ContainerName
USkeleton UAnimSequenceBase const FName EditorAnimUtils::ContainerName
Definition at line 214 of file EditorAnimUtils.h.
CurveType
USkeleton UAnimSequenceBase const FName ERawCurveTrackTypes EditorAnimUtils::CurveType
Definition at line 214 of file EditorAnimUtils.h.
NewSkeleton
USkeleton* EditorAnimUtils::NewSkeleton
Definition at line 214 of file EditorAnimUtils.h.
Referenced by EditorAnimUtils::FAnimationRetargetContext::RetargetAnimations(), RetargetAnimations(), RetargetAnimations(), and RetargetAnimations().
SequenceBase
USkeleton UAnimSequenceBase* EditorAnimUtils::SequenceBase
Definition at line 214 of file EditorAnimUtils.h.