Unreal Engine 5.6 C++ API: FShaderParametersMetadata Class Reference
FShaderParametersMetadata Class Reference
A uniform buffer struct.
#include "ShaderParameterMetadata.h"
Data Structures
class FMember
A member of a shader parameter structure.
Public Types
enum class EUsageFlags : uint8 {
None = 0 , NoEmulatedUniformBuffer = 1 << 0 , UniformView = 1 << 1 , NeedsReflectedMembers = 1 << 2 ,
ManuallyBoundByPass = 1 << 3
}
Additional flags that can be used to determine usage.
enum class EUseCase : uint8 { ShaderParameterStruct , UniformBuffer , DataDrivenUniformBuffer }
The use case of the uniform buffer structures.
Public Member Functions
RENDERCORE_API FShaderParametersMetadata (EUseCase UseCase, EUniformBufferBindingFlags InBindingFlags, const TCHAR *InLayoutName, const TCHAR *InStructTypeName, const TCHAR *InShaderVariableName, const TCHAR *InStaticSlotName, const ANSICHAR *InFileName, const int32 InFileLine, uint32 InSize, const TArray< FMember > &InMembers, bool bForceCompleteInitialization=false, FRHIUniformBufferLayoutInitializer *OutLayoutInitializer=nullptr, EUsageFlags InUsageFlags=EUsageFlags::None)
Initialization constructor.
virtual RENDERCORE_API ~FShaderParametersMetadata ()
RENDERCORE_API void AddResourceTableEntries (FShaderResourceTableMap &ResourceTableMap, TMap< FString, FUniformBufferEntry > &UniformBufferMap) const
RENDERCORE_API void Append (FShaderKeyGenerator &KeyGen) const
RENDERCORE_API void AppendKeyString (FString &OutKeyString) const
RENDERCORE_API void FindMemberFromOffset (uint16 MemberOffset, const FShaderParametersMetadata **OutContainingStruct, const FShaderParametersMetadata::FMember **OutMember, int32 *ArrayElementId, FString *NamePrefix) const
Find a member for a given offset.
EUniformBufferBindingFlags GetBindingFlags () const
const int32 GetFileLine () const
Returns the C++ line number where the parameter structure is declared.
const ANSICHAR * GetFileName () const
Returns the C++ file name where the parameter structure is declared.
RENDERCORE_API FString GetFullMemberCodeName (uint16 MemberOffset) const
Returns the full C++ member name from it's byte offset in the structure.
const FRHIUniformBufferLayout & GetLayout () const
uint32 GetLayoutHash () const
Returns a hash about the entire layout of the structure.
const FRHIUniformBufferLayout * GetLayoutPtr () const
const FBlake3Hash & GetLayoutSignature () const
const TArray< FMember > & GetMembers () const
RENDERCORE_API void GetNestedStructs (TArray< const FShaderParametersMetadata * > &OutNestedStructs) const
EUniformBufferBindingFlags GetPreferredBindingFlag () const
const FHashedName & GetShaderVariableHashedName () const
const TCHAR * GetShaderVariableName () const
uint32 GetSize () const
const TCHAR * GetStaticSlotName () const
const TCHAR * GetStructTypeName () const
const FString & GetUniformBufferDeclaration () const
FThreadSafeSharedAnsiStringPtr GetUniformBufferDeclarationAnsiPtr () const
FThreadSafeSharedStringPtr GetUniformBufferDeclarationPtr () const
FORCEINLINE const FString & GetUniformBufferInclude () const
FORCEINLINE const FString & GetUniformBufferPath () const
FORCEINLINE uint32 GetUniformBufferPathHash () const
EUsageFlags GetUsageFlags () const
EUseCase GetUseCase () const
bool HasStaticSlot () const
bool IsLayoutInitialized () const
bool IsUniformBufferDeclarationInitialized () const
template<typename TParameterFunction>
void IterateStructureMetadataDependencies (TParameterFunction Lambda) const
Iterate recursively over all FShaderParametersMetadata.
Static Public Member Functions
static RENDERCORE_API TMap< FHashedName, FShaderParametersMetadata * > & GetNameStructMap ()
Speed up finding the uniform buffer by its name.
static RENDERCORE_API TMap< FString, FShaderParametersMetadata * > & GetStringStructMap ()
static RENDERCORE_API TLinkedList< FShaderParametersMetadata * > *& GetStructList ()
static RENDERCORE_API void InitializeAllUniformBufferStructs ()
Initialize all the global shader parameter structs.
Static Public Attributes
static constexpr int32 kRootCBufferBindingIndex = 0
Shader binding name of the uniform buffer that contains the root shader parameters.
static constexpr const TCHAR * kRootUniformBufferBindingName = TEXT("_RootShaderParameters")
Shader binding name of the uniform buffer that contains the root shader parameters.
Private Member Functions
template<typename FHasherType, typename FHashType>
void HashLayout (TMemoryHasher< FHasherType, FHashType > &Hasher)
RENDERCORE_API void InitializeLayout (FRHIUniformBufferLayoutInitializer *OutLayoutInitializer=nullptr)
RENDERCORE_API void InitializeUniformBufferDeclaration ()
Private Attributes
const EUniformBufferBindingFlags BindingFlags
The binding model used by this parameter struct.
const int32 FileLine
Line in the C++ file where the parameter structure is declared.
const ANSICHAR *const FileName
Name of the C++ file where the parameter structure is declared.
TLinkedList< FShaderParametersMetadata * > GlobalListLink
Shackle elements in global link list of globally named shader parameters.
FUniformBufferLayoutRHIRef Layout {}
Layout of all the resources in the shader parameter struct.
uint32 LayoutHash = 0
Hash about the entire memory layout of the structure.
const TCHAR *const LayoutName
FBlake3Hash LayoutSignature
Strong persistable hash representing the binary layout of the entire parameter structure.
FThreadSafeNameBufferPtr MemberNameBuffer
TArray< FMember > Members
TArray< FUniformResourceEntry > ResourceTableCache
Cache of uniform buffer resource table, and storage for member names used by the table, created once.
FHashedName ShaderVariableHashedName
const TCHAR *const ShaderVariableName
Name of the shader variable name for global shader parameter structs.
uint32 ShaderVariableNameHash
const uint32 Size
Size of the entire struct in bytes.
const TCHAR *const StaticSlotName
Name of the static slot to use for the uniform buffer (or null).
const TCHAR *const StructTypeName
Name of the structure type in C++ and shader code.
FThreadSafeSharedStringPtr UniformBufferDeclaration
Uniform buffer declaration, created once.
FThreadSafeSharedAnsiStringPtr UniformBufferDeclarationAnsi
FString UniformBufferInclude
FString UniformBufferPath
Strings for uniform buffer generated path and include, created once.
uint32 UniformBufferPathHash
Hashes for frequently used strings.
const EUsageFlags UsageFlags
Additional flags for how to use the buffer.
const EUseCase UseCase
The use case of this shader parameter struct.
Detailed Description
A uniform buffer struct.
Definition at line 135 of file ShaderParameterMetadata.h.
Member Enumeration Documentation
EUsageFlags
enum class FShaderParametersMetadata::EUsageFlags : uint8 strong
Additional flags that can be used to determine usage.
Enumerator
None
NoEmulatedUniformBuffer
On platforms that support emulated uniform buffers, disable them for this uniform buffer.
UniformView
This struct is a view into uniform buffer object, on platforms that support UBO.
NeedsReflectedMembers
This struct needs its members reflected for binding information.
ManuallyBoundByPass
Signals that the uniform buffer is manually bound by the pass and should be ignored by the mesh pass processor.
Definition at line 152 of file ShaderParameterMetadata.h.
EUseCase
enum class FShaderParametersMetadata::EUseCase : uint8 strong
The use case of the uniform buffer structures.
Enumerator
ShaderParameterStruct
Stand alone shader parameter struct used for render passes and shader parameters.
UniformBuffer
Uniform buffer definition authored at compile-time.
DataDrivenUniformBuffer
Uniform buffer generated from assets, such as material parameter collection or Niagara.
Definition at line 139 of file ShaderParameterMetadata.h.
Constructor & Destructor Documentation
FShaderParametersMetadata()
RENDERCORE_API FShaderParametersMetadata::FShaderParametersMetadata (EUseCase UseCase, EUniformBufferBindingFlags InBindingFlags, const TCHAR * InLayoutName, const TCHAR * InStructTypeName, const TCHAR * InShaderVariableName, const TCHAR * InStaticSlotName, const ANSICHAR * InFileName, const int32 InFileLine, uint32 InSize, const TArray< FMember > & InMembers, bool bForceCompleteInitialization = false, FRHIUniformBufferLayoutInitializer * OutLayoutInitializer = nullptr, EUsageFlags InUsageFlags = EUsageFlags::None)
Initialization constructor.
EUseCase::UniformBuffer are listed in the global GetStructList() that will be visited at engine startup to know all the global uniform buffer that can generate code in /Engine/Generated/GeneratedUniformBuffers.ush. Their initialization will be finished during the this list traversal. bForceCompleteInitialization force to ignore the list for EUseCase::UniformBuffer and instead handle it like a standalone non globally listed EUseCase::ShaderParameterStruct. This is required for the ShaderCompileWorker to deserialize them without side global effects.
References None, and UseCase.
Referenced by FindMemberFromOffset(), and IterateStructureMetadataDependencies().
~FShaderParametersMetadata()
virtual RENDERCORE_API FShaderParametersMetadata::~FShaderParametersMetadata () virtual
Member Function Documentation
AddResourceTableEntries()
RENDERCORE_API void FShaderParametersMetadata::AddResourceTableEntries (FShaderResourceTableMap & ResourceTableMap, TMap< FString, FUniformBufferEntry > & UniformBufferMap) const
Append()
RENDERCORE_API void FShaderParametersMetadata::Append (FShaderKeyGenerator & KeyGen) const
AppendKeyString()
RENDERCORE_API void FShaderParametersMetadata::AppendKeyString (FString & OutKeyString) const
FindMemberFromOffset()
RENDERCORE_API void FShaderParametersMetadata::FindMemberFromOffset (uint16 MemberOffset, const FShaderParametersMetadata ** OutContainingStruct, const FShaderParametersMetadata::FMember ** OutMember, int32 * ArrayElementId, FString * NamePrefix) const
Find a member for a given offset.
References FShaderParametersMetadata().
GetBindingFlags()
EUniformBufferBindingFlags FShaderParametersMetadata::GetBindingFlags () const inline
Definition at line 352 of file ShaderParameterMetadata.h.
References BindingFlags.
GetFileLine()
const int32 FShaderParametersMetadata::GetFileLine () const inline
Returns the C++ line number where the parameter structure is declared.
Definition at line 366 of file ShaderParameterMetadata.h.
References FileLine.
GetFileName()
const ANSICHAR * FShaderParametersMetadata::GetFileName () const inline
Returns the C++ file name where the parameter structure is declared.
Definition at line 363 of file ShaderParameterMetadata.h.
References FileName.
GetFullMemberCodeName()
RENDERCORE_API FString FShaderParametersMetadata::GetFullMemberCodeName (uint16 MemberOffset) const
Returns the full C++ member name from it's byte offset in the structure.
GetLayout()
const FRHIUniformBufferLayout & FShaderParametersMetadata::GetLayout () const inline
Definition at line 373 of file ShaderParameterMetadata.h.
References check, IsLayoutInitialized(), and Layout.
GetLayoutHash()
uint32 FShaderParametersMetadata::GetLayoutHash () const inline
Returns a hash about the entire layout of the structure.
Definition at line 416 of file ShaderParameterMetadata.h.
References check, IsLayoutInitialized(), LayoutHash, ShaderParameterStruct, UniformBuffer, and UseCase.
GetLayoutPtr()
const FRHIUniformBufferLayout * FShaderParametersMetadata::GetLayoutPtr () const inline
Definition at line 378 of file ShaderParameterMetadata.h.
References check, IsLayoutInitialized(), and Layout.
GetLayoutSignature()
const FBlake3Hash & FShaderParametersMetadata::GetLayoutSignature () const inline
Definition at line 428 of file ShaderParameterMetadata.h.
References check, checkNoEntry, IsLayoutInitialized(), and LayoutSignature.
GetMembers()
const TArray< FMember > & FShaderParametersMetadata::GetMembers () const inline
Definition at line 383 of file ShaderParameterMetadata.h.
References Members.
Referenced by FShaderParametersMetadataBuilder::FShaderParametersMetadataBuilder().
GetNameStructMap()
RENDERCORE_API TMap< FHashedName, FShaderParametersMetadata * > & FShaderParametersMetadata::GetNameStructMap () static
Speed up finding the uniform buffer by its name.
GetNestedStructs()
RENDERCORE_API void FShaderParametersMetadata::GetNestedStructs (TArray< const FShaderParametersMetadata * > & OutNestedStructs) const
GetPreferredBindingFlag()
EUniformBufferBindingFlags FShaderParametersMetadata::GetPreferredBindingFlag () const inline
Definition at line 354 of file ShaderParameterMetadata.h.
References BindingFlags.
GetShaderVariableHashedName()
const FHashedName & FShaderParametersMetadata::GetShaderVariableHashedName () const inline
Definition at line 347 of file ShaderParameterMetadata.h.
References ShaderVariableHashedName.
Referenced by FShader::GetUniformBufferParameter().
GetShaderVariableName()
const TCHAR * FShaderParametersMetadata::GetShaderVariableName () const inline
Definition at line 346 of file ShaderParameterMetadata.h.
References ShaderVariableName.
GetSize()
uint32 FShaderParametersMetadata::GetSize () const inline
Definition at line 368 of file ShaderParameterMetadata.h.
References Size.
Referenced by FShaderParametersMetadataBuilder::FShaderParametersMetadataBuilder().
GetStaticSlotName()
const TCHAR * FShaderParametersMetadata::GetStaticSlotName () const inline
Definition at line 348 of file ShaderParameterMetadata.h.
References StaticSlotName.
GetStringStructMap()
RENDERCORE_API TMap< FString, FShaderParametersMetadata * > & FShaderParametersMetadata::GetStringStructMap () static
GetStructList()
RENDERCORE_API TLinkedList< FShaderParametersMetadata * > *& FShaderParametersMetadata::GetStructList () static
GetStructTypeName()
const TCHAR * FShaderParametersMetadata::GetStructTypeName () const inline
Definition at line 345 of file ShaderParameterMetadata.h.
References StructTypeName.
GetUniformBufferDeclaration()
const FString & FShaderParametersMetadata::GetUniformBufferDeclaration () const inline
Definition at line 389 of file ShaderParameterMetadata.h.
References UniformBufferDeclaration.
GetUniformBufferDeclarationAnsiPtr()
FThreadSafeSharedAnsiStringPtr FShaderParametersMetadata::GetUniformBufferDeclarationAnsiPtr () const inline
Definition at line 388 of file ShaderParameterMetadata.h.
References UniformBufferDeclarationAnsi.
GetUniformBufferDeclarationPtr()
FThreadSafeSharedStringPtr FShaderParametersMetadata::GetUniformBufferDeclarationPtr () const inline
Definition at line 387 of file ShaderParameterMetadata.h.
References UniformBufferDeclaration.
GetUniformBufferInclude()
FORCEINLINE const FString & FShaderParametersMetadata::GetUniformBufferInclude () const inline
Definition at line 391 of file ShaderParameterMetadata.h.
References FORCEINLINE, and UniformBufferInclude.
GetUniformBufferPath()
FORCEINLINE const FString & FShaderParametersMetadata::GetUniformBufferPath () const inline
Definition at line 390 of file ShaderParameterMetadata.h.
References FORCEINLINE, and UniformBufferPath.
GetUniformBufferPathHash()
FORCEINLINE uint32 FShaderParametersMetadata::GetUniformBufferPathHash () const inline
Definition at line 392 of file ShaderParameterMetadata.h.
References FORCEINLINE, and UniformBufferPathHash.
GetUsageFlags()
EUsageFlags FShaderParametersMetadata::GetUsageFlags () const inline
Definition at line 371 of file ShaderParameterMetadata.h.
References UsageFlags.
GetUseCase()
EUseCase FShaderParametersMetadata::GetUseCase () const inline
Definition at line 369 of file ShaderParameterMetadata.h.
References UseCase.
HashLayout()
template<typename FHasherType, typename FHashType> void FShaderParametersMetadata::HashLayout (TMemoryHasher< FHasherType, FHashType > & Hasher) inline private
Definition at line 523 of file ShaderParameterMetadata.h.
References Members.
HasStaticSlot()
bool FShaderParametersMetadata::HasStaticSlot () const inline
Definition at line 350 of file ShaderParameterMetadata.h.
References StaticSlotName.
InitializeAllUniformBufferStructs()
RENDERCORE_API void FShaderParametersMetadata::InitializeAllUniformBufferStructs () static
Initialize all the global shader parameter structs.
InitializeLayout()
RENDERCORE_API void FShaderParametersMetadata::InitializeLayout (FRHIUniformBufferLayoutInitializer * OutLayoutInitializer = nullptr) private
InitializeUniformBufferDeclaration()
RENDERCORE_API void FShaderParametersMetadata::InitializeUniformBufferDeclaration () private
IsLayoutInitialized()
bool FShaderParametersMetadata::IsLayoutInitialized () const inline
Definition at line 370 of file ShaderParameterMetadata.h.
References Layout.
Referenced by GetLayout(), GetLayoutHash(), GetLayoutPtr(), and GetLayoutSignature().
IsUniformBufferDeclarationInitialized()
bool FShaderParametersMetadata::IsUniformBufferDeclarationInitialized () const inline
Definition at line 386 of file ShaderParameterMetadata.h.
References UniformBufferDeclaration.
IterateStructureMetadataDependencies()
template<typename TParameterFunction> void FShaderParametersMetadata::IterateStructureMetadataDependencies (TParameterFunction Lambda) const inline
Iterate recursively over all FShaderParametersMetadata.
Definition at line 445 of file ShaderParameterMetadata.h.
References FShaderParametersMetadata(), IterateStructureMetadataDependencies(), and Members.
Referenced by IterateStructureMetadataDependencies().
Field Documentation
BindingFlags
const EUniformBufferBindingFlags FShaderParametersMetadata::BindingFlags private
The binding model used by this parameter struct.
Definition at line 487 of file ShaderParameterMetadata.h.
Referenced by GetBindingFlags(), and GetPreferredBindingFlag().
FileLine
const int32 FShaderParametersMetadata::FileLine private
Line in the C++ file where the parameter structure is declared.
Definition at line 478 of file ShaderParameterMetadata.h.
Referenced by GetFileLine().
FileName
const ANSICHAR* const FShaderParametersMetadata::FileName private
Name of the C++ file where the parameter structure is declared.
Definition at line 475 of file ShaderParameterMetadata.h.
Referenced by GetFileName().
GlobalListLink
TLinkedList<FShaderParametersMetadata*> FShaderParametersMetadata::GlobalListLink private
Shackle elements in global link list of globally named shader parameters.
Definition at line 517 of file ShaderParameterMetadata.h.
kRootCBufferBindingIndex
int32 FShaderParametersMetadata::kRootCBufferBindingIndex = 0 static constexpr
Shader binding name of the uniform buffer that contains the root shader parameters.
Definition at line 173 of file ShaderParameterMetadata.h.
kRootUniformBufferBindingName
const TCHAR* FShaderParametersMetadata::kRootUniformBufferBindingName = TEXT("_RootShaderParameters") static constexpr
Shader binding name of the uniform buffer that contains the root shader parameters.
Definition at line 170 of file ShaderParameterMetadata.h.
Layout
FUniformBufferLayoutRHIRef FShaderParametersMetadata::Layout {} private
Layout of all the resources in the shader parameter struct.
Definition at line 493 of file ShaderParameterMetadata.h.
Referenced by GetLayout(), GetLayoutPtr(), and IsLayoutInitialized().
LayoutHash
uint32 FShaderParametersMetadata::LayoutHash = 0 private
Hash about the entire memory layout of the structure.
Definition at line 520 of file ShaderParameterMetadata.h.
Referenced by GetLayoutHash().
LayoutName
const TCHAR* const FShaderParametersMetadata::LayoutName private
Definition at line 461 of file ShaderParameterMetadata.h.
LayoutSignature
FBlake3Hash FShaderParametersMetadata::LayoutSignature private
Strong persistable hash representing the binary layout of the entire parameter structure.
Definition at line 534 of file ShaderParameterMetadata.h.
Referenced by GetLayoutSignature().
MemberNameBuffer
FThreadSafeNameBufferPtr FShaderParametersMetadata::MemberNameBuffer private
Definition at line 505 of file ShaderParameterMetadata.h.
Members
TArray<FMember> FShaderParametersMetadata::Members private
Definition at line 496 of file ShaderParameterMetadata.h.
Referenced by GetMembers(), HashLayout(), and IterateStructureMetadataDependencies().
ResourceTableCache
TArray<FUniformResourceEntry> FShaderParametersMetadata::ResourceTableCache private
Cache of uniform buffer resource table, and storage for member names used by the table, created once.
Definition at line 504 of file ShaderParameterMetadata.h.
ShaderVariableHashedName
FHashedName FShaderParametersMetadata::ShaderVariableHashedName private
Definition at line 472 of file ShaderParameterMetadata.h.
Referenced by GetShaderVariableHashedName().
ShaderVariableName
const TCHAR* const FShaderParametersMetadata::ShaderVariableName private
Name of the shader variable name for global shader parameter structs.
Definition at line 467 of file ShaderParameterMetadata.h.
Referenced by GetShaderVariableName().
ShaderVariableNameHash
uint32 FShaderParametersMetadata::ShaderVariableNameHash private
Definition at line 513 of file ShaderParameterMetadata.h.
Size
const uint32 FShaderParametersMetadata::Size private
Size of the entire struct in bytes.
Definition at line 481 of file ShaderParameterMetadata.h.
Referenced by GetSize().
StaticSlotName
const TCHAR* const FShaderParametersMetadata::StaticSlotName private
Name of the static slot to use for the uniform buffer (or null).
Definition at line 470 of file ShaderParameterMetadata.h.
Referenced by GetStaticSlotName(), and HasStaticSlot().
StructTypeName
const TCHAR* const FShaderParametersMetadata::StructTypeName private
Name of the structure type in C++ and shader code.
Definition at line 464 of file ShaderParameterMetadata.h.
Referenced by GetStructTypeName().
UniformBufferDeclaration
FThreadSafeSharedStringPtr FShaderParametersMetadata::UniformBufferDeclaration private
Uniform buffer declaration, created once.
Definition at line 500 of file ShaderParameterMetadata.h.
Referenced by GetUniformBufferDeclaration(), GetUniformBufferDeclarationPtr(), and IsUniformBufferDeclarationInitialized().
UniformBufferDeclarationAnsi
FThreadSafeSharedAnsiStringPtr FShaderParametersMetadata::UniformBufferDeclarationAnsi private
Definition at line 501 of file ShaderParameterMetadata.h.
Referenced by GetUniformBufferDeclarationAnsiPtr().
UniformBufferInclude
FString FShaderParametersMetadata::UniformBufferInclude private
Definition at line 509 of file ShaderParameterMetadata.h.
Referenced by GetUniformBufferInclude().
UniformBufferPath
FString FShaderParametersMetadata::UniformBufferPath private
Strings for uniform buffer generated path and include, created once.
Definition at line 508 of file ShaderParameterMetadata.h.
Referenced by GetUniformBufferPath().
UniformBufferPathHash
uint32 FShaderParametersMetadata::UniformBufferPathHash private
Hashes for frequently used strings.
Definition at line 512 of file ShaderParameterMetadata.h.
Referenced by GetUniformBufferPathHash().
UsageFlags
const EUsageFlags FShaderParametersMetadata::UsageFlags private
Additional flags for how to use the buffer.
Definition at line 490 of file ShaderParameterMetadata.h.
Referenced by GetUsageFlags().
UseCase
const EUseCase FShaderParametersMetadata::UseCase private
The use case of this shader parameter struct.
Definition at line 484 of file ShaderParameterMetadata.h.
Referenced by FShaderParametersMetadata(), GetLayoutHash(), and GetUseCase().
The documentation for this class was generated from the following file:
ShaderParameterMetadata.h