Unreal Engine 5.6 C++ API: UE::Geometry::FWorldSpaceProjectionTarget Class Reference
UE::Geometry::FWorldSpaceProjectionTarget Class Reference
#include "ProjectionTargets.h"
Public Member Functions
FWorldSpaceProjectionTarget ()=default
FWorldSpaceProjectionTarget (const FDynamicMesh3 *MeshIn, FDynamicMeshAABBTree3 *SpatialIn, const FTransformSRT3d &TargetMeshLocalToWorldIn, const FTransformSRT3d &ToolMeshLocalToWorldIn)
virtual ~FWorldSpaceProjectionTarget ()=default
virtual FVector3d Project (const FVector3d &Point, FVector3d &ProjectNormalOut, int Identifier=-1) override
virtual FVector3d Project (const FVector3d &Point, int Identifier=-1) override
Public Member Functions inherited from UE::Geometry::FMeshProjectionTarget
FMeshProjectionTarget ()=default
FMeshProjectionTarget (const FDynamicMesh3 *MeshIn, FDynamicMeshAABBTree3 *SpatialIn)
virtual ~FMeshProjectionTarget ()=default
Public Member Functions inherited from UE::Geometry::IOrientedProjectionTarget
virtual ~IOrientedProjectionTarget ()
Public Member Functions inherited from UE::Geometry::IProjectionTarget
virtual ~IProjectionTarget ()
Protected Attributes
FTransformSRT3d TargetMeshLocalToWorld
FTransformSRT3d ToolMeshLocalToWorld
Additional Inherited Members
Data Fields inherited from UE::Geometry::FMeshProjectionTarget
const FDynamicMesh3 * Mesh = nullptr
The mesh to project onto.
FDynamicMeshAABBTree3 * Spatial = nullptr
An AABBTree for Mesh.
Detailed Description
Definition at line 52 of file ProjectionTargets.h.
Constructor & Destructor Documentation
~FWorldSpaceProjectionTarget()
virtual UE::Geometry::FWorldSpaceProjectionTarget::~FWorldSpaceProjectionTarget () virtual default
FWorldSpaceProjectionTarget() [1/2]
UE::Geometry::FWorldSpaceProjectionTarget::FWorldSpaceProjectionTarget () default
FWorldSpaceProjectionTarget() [2/2]
UE::Geometry::FWorldSpaceProjectionTarget::FWorldSpaceProjectionTarget (const FDynamicMesh3 * MeshIn, FDynamicMeshAABBTree3 * SpatialIn, const FTransformSRT3d & TargetMeshLocalToWorldIn, const FTransformSRT3d & ToolMeshLocalToWorldIn) inline
Definition at line 59 of file ProjectionTargets.h.
References UE::Geometry::FMeshProjectionTarget::FMeshProjectionTarget(), TargetMeshLocalToWorld, and ToolMeshLocalToWorld.
Member Function Documentation
Project() [1/2]
virtual FVector3d UE::Geometry::FWorldSpaceProjectionTarget::Project (const FVector3d & Point, FVector3d & ProjectNormalOut, int Identifier = -1) inline override virtual
Returns
Projection of Point onto this target, and set ProjectNormalOut to the triangle normal at the returned point (not interpolated vertex normal)
Reimplemented from UE::Geometry::FMeshProjectionTarget.
Definition at line 90 of file ProjectionTargets.h.
References Point, UE::Geometry::FMeshProjectionTarget::Project(), TargetMeshLocalToWorld, and ToolMeshLocalToWorld.
Project() [2/2]
virtual FVector3d UE::Geometry::FWorldSpaceProjectionTarget::Project (const FVector3d & Point, int Identifier = -1) inline override virtual
Returns
Projection of Point onto this target
Reimplemented from UE::Geometry::FMeshProjectionTarget.
Definition at line 71 of file ProjectionTargets.h.
References Point, UE::Geometry::FMeshProjectionTarget::Project(), TargetMeshLocalToWorld, and ToolMeshLocalToWorld.
Field Documentation
TargetMeshLocalToWorld
FTransformSRT3d UE::Geometry::FWorldSpaceProjectionTarget::TargetMeshLocalToWorld protected
Definition at line 110 of file ProjectionTargets.h.
Referenced by FWorldSpaceProjectionTarget(), Project(), and Project().
ToolMeshLocalToWorld
FTransformSRT3d UE::Geometry::FWorldSpaceProjectionTarget::ToolMeshLocalToWorld protected
Definition at line 111 of file ProjectionTargets.h.
Referenced by FWorldSpaceProjectionTarget(), Project(), and Project().
The documentation for this class was generated from the following file:
ProjectionTargets.h