Unreal Engine 5.6 C++ API: FStaticLightingTextureMapping Class Reference
FStaticLightingTextureMapping Class Reference abstract
A mapping between world-space surfaces and static lighting cache textures.
#include "StaticLighting.h"
Public Member Functions
FStaticLightingTextureMapping (const FArchive &Ar)
Default constructor used by serializer.
FStaticLightingTextureMapping (FStaticLightingMesh *InMesh, UObject *InOwner, int32 InSizeX, int32 InSizeY, int32 InLightmapTextureCoordinateIndex, bool bInBilinearFilter=true)
Initialization constructor.
virtual void Apply (struct FQuantizedLightmapData *QuantizedData, const TMap< ULightComponent *, class FShadowMapData2D * > &ShadowMapData, const FStaticLightingBuildContext *LightingContext)=0
Called when the static lighting has been computed to apply it to the mapping's owner.
virtual UNREALED_API bool DebugThisMapping () const
virtual FString GetDescription () const
virtual int32 GetTexelCount () const
virtual FStaticLightingTextureMapping * GetTextureMapping ()
virtual bool IsTextureMapping () const
virtual bool IsValidMapping () const
Whether or not this mapping should be processed or imported.
virtual void Serialize (FArchive &Ar)
Public Member Functions inherited from FStaticLightingMapping
FStaticLightingMapping (const FArchive &)
FStaticLightingMapping (FStaticLightingMesh *InMesh, UObject *InOwner)
Initialization constructor.
virtual ~FStaticLightingMapping ()
Virtual destructor.
virtual void ExportMapping (class FLightmassExporter *Exporter)
Export static lighting mapping instance data to an exporter.
virtual const FGuid & GetLightingGuid () const
Returns the Guid used for static lighting.
virtual UObject * GetMappedObject () const
bool IsDeferred () const
Public Member Functions inherited from FRefCountedObject
FRefCountedObject ()
FRefCountedObject (const FRefCountedObject &Rhs)=delete
virtual ~FRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountedObject & operator= (const FRefCountedObject &Rhs)=delete
uint32 Release () const
Data Fields
bool bBilinearFilter
Whether to apply a bilinear filter to the sample or not.
int32 LightmapTextureCoordinateIndex
The lightmap texture coordinate index which is used for the mapping.
int32 SizeX
The width of the static lighting textures used by the mapping.
int32 SizeY
The height of the static lighting textures used by the mapping.
Data Fields inherited from FStaticLightingMapping
uint32 bIsDeferred: 1
true if the mapping should be deferred until a finalizing pass.
uint32 bProcessMapping: 1
true if the mapping should be processed by Lightmass.
class FStaticLightingMesh * Mesh
The mesh associated with the mapping.
UObject * Owner
The object which owns the mapping.
Detailed Description
A mapping between world-space surfaces and static lighting cache textures.
Definition at line 405 of file StaticLighting.h.
Constructor & Destructor Documentation
FStaticLightingTextureMapping() [1/2]
FStaticLightingTextureMapping::FStaticLightingTextureMapping (FStaticLightingMesh * InMesh, UObject * InOwner, int32 InSizeX, int32 InSizeY, int32 InLightmapTextureCoordinateIndex, bool bInBilinearFilter = true)
Initialization constructor.
Referenced by FStaticMeshStaticLightingTextureMapping::FStaticMeshStaticLightingTextureMapping(), and GetTextureMapping().
FStaticLightingTextureMapping() [2/2]
FStaticLightingTextureMapping::FStaticLightingTextureMapping (const FArchive & Ar) inline
Default constructor used by serializer.
Definition at line 462 of file StaticLighting.h.
References FStaticLightingMapping::FStaticLightingMapping(), and Ar.
Member Function Documentation
Apply()
virtual void FStaticLightingTextureMapping::Apply (struct FQuantizedLightmapData * QuantizedData, const TMap< ULightComponent *, class FShadowMapData2D * > & ShadowMapData, const FStaticLightingBuildContext * LightingContext) pure virtual
Called when the static lighting has been computed to apply it to the mapping's owner.
This function is responsible for deleting ShadowMapData and QuantizedData.
Parameters
LightMapData - The light-map data which has been computed for the mapping.
Implemented in FBSPSurfaceStaticLighting, FLandscapeStaticLightingGlobalVolumeMapping, FLandscapeStaticLightingTextureMapping, FStaticLightingGlobalVolumeMapping, FStaticLightingTextureMapping_InstancedStaticMesh, and FStaticMeshStaticLightingTextureMapping.
DebugThisMapping()
virtual UNREALED_API bool FStaticLightingTextureMapping::DebugThisMapping () const virtual
Implements FStaticLightingMapping.
Reimplemented in FBSPSurfaceStaticLighting, FLandscapeStaticLightingGlobalVolumeMapping, FStaticLightingGlobalVolumeMapping, and FStaticLightingTextureMapping_InstancedStaticMesh.
GetDescription()
virtual FString FStaticLightingTextureMapping::GetDescription () const inline virtual
Reimplemented from FStaticLightingMapping.
Reimplemented in FBSPSurfaceStaticLighting, FLandscapeStaticLightingGlobalVolumeMapping, FLandscapeStaticLightingTextureMapping, FStaticLightingGlobalVolumeMapping, FStaticLightingTextureMapping_InstancedStaticMesh, and FStaticMeshStaticLightingTextureMapping.
Definition at line 451 of file StaticLighting.h.
References TEXT.
GetTexelCount()
virtual int32 FStaticLightingTextureMapping::GetTexelCount () const inline virtual
Reimplemented from FStaticLightingMapping.
Definition at line 456 of file StaticLighting.h.
References SizeX, and SizeY.
GetTextureMapping()
virtual FStaticLightingTextureMapping * FStaticLightingTextureMapping::GetTextureMapping () inline virtual
Returns
If the mapping is a texture mapping, returns a pointer to this mapping as a texture mapping. Otherwise, returns NULL.
Reimplemented from FStaticLightingMapping.
Definition at line 432 of file StaticLighting.h.
References FStaticLightingTextureMapping().
IsTextureMapping()
virtual bool FStaticLightingTextureMapping::IsTextureMapping () const inline virtual
Returns
true if the mapping is a texture mapping. Otherwise, returns false.
Reimplemented from FStaticLightingMapping.
Definition at line 438 of file StaticLighting.h.
IsValidMapping()
virtual bool FStaticLightingTextureMapping::IsValidMapping () const inline virtual
Whether or not this mapping should be processed or imported.
Reimplemented in FBSPSurfaceStaticLighting, FLandscapeStaticLightingGlobalVolumeMapping, FStaticLightingGlobalVolumeMapping, and FStaticMeshStaticLightingTextureMapping.
Definition at line 444 of file StaticLighting.h.
Serialize()
virtual void FStaticLightingTextureMapping::Serialize (FArchive & Ar) virtual
Reimplemented from FStaticLightingMapping.
Reimplemented in FLandscapeStaticLightingTextureMapping, FStaticLightingTextureMapping_InstancedStaticMesh, and FStaticMeshStaticLightingTextureMapping.
References Ar.
Field Documentation
bBilinearFilter
bool FStaticLightingTextureMapping::bBilinearFilter
Whether to apply a bilinear filter to the sample or not.
Definition at line 419 of file StaticLighting.h.
LightmapTextureCoordinateIndex
int32 FStaticLightingTextureMapping::LightmapTextureCoordinateIndex
The lightmap texture coordinate index which is used for the mapping.
Definition at line 416 of file StaticLighting.h.
SizeX
int32 FStaticLightingTextureMapping::SizeX
The width of the static lighting textures used by the mapping.
Definition at line 410 of file StaticLighting.h.
Referenced by GetTexelCount().
SizeY
int32 FStaticLightingTextureMapping::SizeY
The height of the static lighting textures used by the mapping.
Definition at line 413 of file StaticLighting.h.
Referenced by GetTexelCount().
The documentation for this class was generated from the following file:
StaticLighting.h