Unreal Engine 5.6 C++ API: FMoveCursor Class Reference
FMoveCursor Class Reference
Argument to the ITextEditorWidget::Move(); it decouples performing cursor movement and text highlighting actions from event handling.
#include "ISlateEditableTextWidget.h"
Public Member Functions
ECursorAction GetAction () const
float GetGeometryScale () const
Geometry Scale at the time of the event that caused this action.
ECursorMoveGranularity GetGranularity () const
Move one character at a time, or one word?
FVector2D GetLocalPosition () const
Which position in the widget where the user touched when using ScreenPosition mode.
FIntPoint GetMoveDirection () const
When using directional movement (i.e.
ECursorMoveMethod GetMoveMethod () const
bool IsHorizontalMovement () const
Is the cursor moving left/right; Only valid for word and character movement methods.
bool IsVerticalMovement () const
Is the cursor moving up/down; Only valid for word and character movement methods.
Static Public Member Functions
static FMoveCursor Cardinal (ECursorMoveGranularity Granularity, FIntPoint Direction, ECursorAction Action)
Creates a MoveCursor action that describes moving by a single character in any of the cardinal directions.
static FMoveCursor ViaScreenPointer (FVector2D LocalPosition, float GeometryScale, ECursorAction Action)
Creates a MoveCursor action that describes moving the text cursor by selecting an arbitrary coordinate on the screen.
Private Member Functions
FMoveCursor (ECursorMoveGranularity InGranularity, ECursorMoveMethod InMethod, FVector2D InDirectionOrPosition, float InGeometryScale, ECursorAction InAction)
Private Attributes
ECursorAction Action
FVector2f DirectionOrPosition
float GeometryScale
ECursorMoveGranularity Granularity
ECursorMoveMethod Method
Detailed Description
Argument to the ITextEditorWidget::Move(); it decouples performing cursor movement and text highlighting actions from event handling.
FMoveCursor describes how the cursor can be moved via keyboard, mouse, and other mechanisms in the future.
Definition at line 81 of file ISlateEditableTextWidget.h.
Constructor & Destructor Documentation
FMoveCursor()
FMoveCursor::FMoveCursor (ECursorMoveGranularity InGranularity, ECursorMoveMethod InMethod, FVector2D InDirectionOrPosition, float InGeometryScale, ECursorAction InAction) private
Referenced by Cardinal(), and ViaScreenPointer().
Member Function Documentation
Cardinal()
FMoveCursor FMoveCursor::Cardinal (ECursorMoveGranularity Granularity, FIntPoint Direction, ECursorAction Action) static
Creates a MoveCursor action that describes moving by a single character in any of the cardinal directions.
Parameters
Granularity Move one character at a time, or on word boundaries (e.g. Ctrl is held down, or double-click mouse+drag)
Direction Axis-aligned unit vector along which to move. e.g. Move right: (0,1) or Move Up: (-1, 0)
Action Just move or also select text?
References FMoveCursor(), Action, and Granularity.
GetAction()
ECursorAction FMoveCursor::GetAction () const
See also
ECursorAction
GetGeometryScale()
float FMoveCursor::GetGeometryScale () const
Geometry Scale at the time of the event that caused this action.
GetGranularity()
ECursorMoveGranularity FMoveCursor::GetGranularity () const
Move one character at a time, or one word?
GetLocalPosition()
FVector2D FMoveCursor::GetLocalPosition () const
Which position in the widget where the user touched when using ScreenPosition mode.
GetMoveDirection()
FIntPoint FMoveCursor::GetMoveDirection () const
When using directional movement (i.e.
Character or Word granularity; not screen position, which way to move.)
GetMoveMethod()
ECursorMoveMethod FMoveCursor::GetMoveMethod () const
See also
ECursorMoveMethod
IsHorizontalMovement()
bool FMoveCursor::IsHorizontalMovement () const
Is the cursor moving left/right; Only valid for word and character movement methods.
IsVerticalMovement()
bool FMoveCursor::IsVerticalMovement () const
Is the cursor moving up/down; Only valid for word and character movement methods.
ViaScreenPointer()
FMoveCursor FMoveCursor::ViaScreenPointer (FVector2D LocalPosition, float GeometryScale, ECursorAction Action) static
Creates a MoveCursor action that describes moving the text cursor by selecting an arbitrary coordinate on the screen.
e.g. User user touches a touch device screen or uses the mouse to point at text.
Parameters
LocalPosition Position in the text widget where the user wants to move the cursor by pointing
GeometryScale DPI Scale of the widget geometry.
Action Just move or also select text?
References FMoveCursor(), Action, and GeometryScale.
Field Documentation
Action
ECursorAction FMoveCursor::Action private
Definition at line 133 of file ISlateEditableTextWidget.h.
Referenced by Cardinal(), and ViaScreenPointer().
DirectionOrPosition
FVector2f FMoveCursor::DirectionOrPosition private
Definition at line 132 of file ISlateEditableTextWidget.h.
GeometryScale
float FMoveCursor::GeometryScale private
Definition at line 134 of file ISlateEditableTextWidget.h.
Referenced by ViaScreenPointer().
Granularity
ECursorMoveGranularity FMoveCursor::Granularity private
Definition at line 130 of file ISlateEditableTextWidget.h.
Referenced by Cardinal().
Method
ECursorMoveMethod FMoveCursor::Method private
Definition at line 131 of file ISlateEditableTextWidget.h.
The documentation for this class was generated from the following file:
ISlateEditableTextWidget.h