Unreal Engine 5.6 C++ API: FMallocBinnedCommonUtils Class Reference
FMallocBinnedCommonUtils Class Reference
#include "MallocBinnedCommonUtils.h"
Static Public Member Functions
template<class AllocType>
static void FlushCurrentThreadCache (AllocType &Allocator, bool bNewEpochOnly=false)
template<class AllocType>
static void Trim (AllocType &Allocator)
template<class AllocType>
static void TrimThreadFreeBlockLists (AllocType &Allocator, typename AllocType::FPerThreadFreeBlockLists *FreeBlockLists)
Detailed Description
Definition at line 97 of file MallocBinnedCommonUtils.h.
Member Function Documentation
FlushCurrentThreadCache()
template<class AllocType> void FMallocBinnedCommonUtils::FlushCurrentThreadCache (AllocType & Allocator, bool bNewEpochOnly = false) inline static
Definition at line 119 of file MallocBinnedCommonUtils.h.
References Allocator, FlushCurrentThreadCache(), GMallocBinnedFlushThreadCacheMaxWaitTime, LogMemory, QUICK_SCOPE_CYCLE_COUNTER, FAndroidTime::Seconds(), TEXT, TRACE_CPUPROFILER_EVENT_SCOPE, TrimThreadFreeBlockLists(), UE_LOG, and Warning.
Referenced by FlushCurrentThreadCache(), and Trim().
Trim()
template<class AllocType> void FMallocBinnedCommonUtils::Trim (AllocType & Allocator) inline static
Definition at line 141 of file MallocBinnedCommonUtils.h.
References Allocator, FTaskGraphInterface::BroadcastSlow_OnlyUseForSpecialPurposes(), FlushCurrentThreadCache(), GMallocBinnedFlushRegisteredThreadCachesOnOneThread, PLATFORM_DESKTOP, QUICK_SCOPE_CYCLE_COUNTER, FApp::ShouldUseThreadingForPerformance(), FGenericPlatformProcess::SupportsMultithreading(), and TrimThreadFreeBlockLists().
TrimThreadFreeBlockLists()
template<class AllocType> void FMallocBinnedCommonUtils::TrimThreadFreeBlockLists (AllocType & Allocator, typename AllocType::FPerThreadFreeBlockLists * FreeBlockLists) inline static
Definition at line 101 of file MallocBinnedCommonUtils.h.
References Allocator, TRACE_CPUPROFILER_EVENT_SCOPE, and TrimThreadFreeBlockLists().
Referenced by FlushCurrentThreadCache(), Trim(), and TrimThreadFreeBlockLists().
The documentation for this class was generated from the following file:
MallocBinnedCommonUtils.h