Unreal Engine 5.6 C++ API: FEmbeddedCommunication Class Reference
FEmbeddedCommunication Class Reference
#include "EmbeddedCommunication.h"
Static Public Member Functions
static void AllowSleep (FName Requester)
static void ForceTick (int ID, float MinTimeSlice=0.1f, float MaxTimeSlice=0.5f)
static FString GetDebugInfo ()
static void Init ()
static bool IsAwakeForRendering ()
static bool IsAwakeForTicking ()
static void KeepAwake (FName Requester, bool bNeedsRendering)
static void RunOnGameThread (int Priority, TFunction< void()> Lambda)
static bool TickGameThread (float DeltaTime)
static void UELogDisplay (const TCHAR *String)
static void UELogError (const TCHAR *String)
static void UELogFatal (const TCHAR *String)
static void UELogLog (const TCHAR *String)
static void UELogVerbose (const TCHAR *String)
static void UELogWarning (const TCHAR *String)
static void WakeGameThread ()
Detailed Description
Definition at line 70 of file EmbeddedCommunication.h.
Member Function Documentation
AllowSleep()
void FEmbeddedCommunication::AllowSleep (FName Requester) static
Referenced by FEmbeddedKeepAwake::~FEmbeddedKeepAwake(), FEmbeddedKeepAwake::operator=(), and FEmbeddedKeepAwake::operator=().
ForceTick()
void FEmbeddedCommunication::ForceTick (int ID, float MinTimeSlice = 0.1f, float MaxTimeSlice = 0.5f) static
References ID.
GetDebugInfo()
FString FEmbeddedCommunication::GetDebugInfo () static
Init()
void FEmbeddedCommunication::Init () static
IsAwakeForRendering()
bool FEmbeddedCommunication::IsAwakeForRendering () static
IsAwakeForTicking()
bool FEmbeddedCommunication::IsAwakeForTicking () static
KeepAwake()
void FEmbeddedCommunication::KeepAwake (FName Requester, bool bNeedsRendering) static
Referenced by FEmbeddedKeepAwake::FEmbeddedKeepAwake(), FEmbeddedKeepAwake::FEmbeddedKeepAwake(), and FEmbeddedKeepAwake::operator=().
RunOnGameThread()
void FEmbeddedCommunication::RunOnGameThread (int Priority, TFunction< void()> Lambda) static
TickGameThread()
bool FEmbeddedCommunication::TickGameThread (float DeltaTime) static
References DeltaTime.
UELogDisplay()
void FEmbeddedCommunication::UELogDisplay (const TCHAR * String) static
References String.
UELogError()
void FEmbeddedCommunication::UELogError (const TCHAR * String) static
References String.
UELogFatal()
void FEmbeddedCommunication::UELogFatal (const TCHAR * String) static
References String.
UELogLog()
void FEmbeddedCommunication::UELogLog (const TCHAR * String) static
References String.
UELogVerbose()
void FEmbeddedCommunication::UELogVerbose (const TCHAR * String) static
References String.
UELogWarning()
void FEmbeddedCommunication::UELogWarning (const TCHAR * String) static
References String.
WakeGameThread()
void FEmbeddedCommunication::WakeGameThread () static
The documentation for this class was generated from the following file:
EmbeddedCommunication.h