Unreal Engine 5.6 C++ API: FConfigContext Class Reference
FConfigContext Class Reference
#include "ConfigContext.h"
Data Structures
struct FPerPlatformDirs
Public Member Functions
~FConfigContext ()
const FPerPlatformDirs & GetPerPlatformDirs (const FString &PlatformName)
Return the paths to use to find hierarchical config files for the given platform (note that these are independent of the ini name)
bool Load (const TCHAR *IniName)
Use the context to perform the actual load operation.
bool Load (const TCHAR *IniName, FString &OutFilename)
Use the context to perform the actual load operation as above, but will return the generated final ini filename (in the case of GConfig, this would be the key used to look up into GConfig, for example)
void VisualizeHierarchy (FOutputDevice &Ar, const TCHAR *IniName)
Visualize an existing hierarchy.
Static Public Member Functions
static void EnsureRequiredGlobalPathsHaveBeenInitialized ()
Call to make before attempting parallel config init.
static FConfigContext FixupBranchAfterBinaryConfig ()
Create a context to read only the saved/generated file (eg.
static FConfigContext ForceReloadIntoGConfig ()
Create a context to read a hierarchical config into GConfig.
static FConfigContext ReadIntoConfigSystem (FConfigCacheIni *ConfigSystem, const FString &Platform)
Create a context to read a hierarchical config into the given ConfigSystem structure - usually will be for other platforms.
static FConfigContext ReadIntoGConfig ()
Create a context to read a hierarchical config into GConfig.
static FConfigContext ReadIntoLocalFile (FConfigFile &DestConfigFile, const FString &Platform=FString())
Create a context to read a hierarchical config into the given local FConfigFile, optionally for another platform.
static FConfigContext ReadIntoPluginFile (FConfigFile &DestConfigFile, const FString &PluginRootDir, const TArray< FString > &ChildPluginsBaseDirs, const FString &Platform=FString())
Create a context to read a plugin's ini file named for the plugin.
static FConfigContext ReadPluginIntoConfigSystem (FConfigCacheIni *ConfigSystem, FName PluginName, const FString &PluginRootDir, const TArray< FString > &ChildPluginsBaseDirs)
Inserts plugin ini files into an existing Branch.
static FConfigContext ReadPluginToModifyConfigSystem (FConfigCacheIni *ConfigSystem, DynamicLayerPriority Priority, FName PluginName, const FString &PluginRootDir, const TArray< FString > &ChildPluginsBaseDirs, FConfigModificationTracker *ChangeTracker=nullptr)
Inserts plugin ini files into an existing Branch.
static FConfigContext ReadSingleIntoConfigSystem (FConfigCacheIni *ConfigSystem, const FString &Platform)
Create a context to read a non-hierarchical config into the given ConfigSystem structure - usually will be for other platforms.
static FConfigContext ReadSingleIntoGConfig ()
Create a context to read a non-hierarchical config into GConfig.
static FConfigContext ReadSingleIntoLocalFile (FConfigFile &DestConfigFile, const FString &Platform=FString())
Create a context to read a non-hierarchical config into the given local FConfigFile, optionally for another platform.
static FConfigContext ReadUpToBeforeFile (FConfigFile &DestConfigFile, const FString &Platform, const FString &StartSkippingAtFilename)
Create a context to read a hierarchy, but once it reaches the given filename (StartDeletingFilename), it will not read in anymore files at that point.
static void VisualizeHierarchy (FOutputDevice &Ar, const TCHAR *IniName, const TCHAR *OverridePlatform, const TCHAR *OverrideProjectOrProgramDataDir, const TCHAR *OverridePluginDir=nullptr, const TArray< FString > *ChildPluginBaseDirs=nullptr)
Log out the config full hierarchy of a file, with various overrides to see other projects/platforms/etc hierarchies.
Data Fields
bool bAllowGeneratedIniWhenCooked = false
bool bAllowRemoteConfig = false
FString BaseIniName
bool bDefaultEngineRequired = false
bool bForceReload = false
bool bIncludeTagNameInBranchName = false
bool bIsFixingUpAfterBinaryConfig = false
bool bIsForPlugin = false
bool bIsForPluginModification = false
bool bIsHierarchicalConfig
bool bIsMakingBinaryConfig = false
FConfigBranch * Branch = nullptr
bool bUseHierarchyCache = false
bool bWriteDestIni = false
FConfigModificationTracker * ChangeTracker = nullptr
TArray< FString > ChildPluginBaseDirs
FName ConfigFileTag
FConfigCacheIni * ConfigSystem
FString DestIniFilename
FString EngineConfigDir
FString EngineRootDir
FConfigFile * ExistingFile = nullptr
FString GeneratedConfigDir
TFunction< void(const TArray< FDynamicLayerInfo > &)> HandleLayersFunction = nullptr
const TSet< FString > * IniCacheSet = nullptr
TArray< FConfigLayer > OverrideLayers
TMap< FString, FPerPlatformDirs > PerPlatformDirs
FString Platform
DynamicLayerPriority PluginModificationPriority
FString PluginRootDir
FString ProjectConfigDir
FString ProjectLimitedAccessDir
FString ProjectNoRedistDir
FString ProjectNotForLicenseesDir
FString ProjectRootDir
FString SavePlatform
const TSet< FString > * StagedGlobalConfigCache = nullptr
const TSet< FString > * StagedPluginConfigCache = nullptr
FString StartSkippingAtFilename
FConfigBranch * TemporaryBranch = nullptr
Protected Member Functions
FConfigContext (FConfigCacheIni *InConfigSystem, bool InIsHierarchicalConfig, const FString &InPlatform, FConfigFile *DestConfigFile=nullptr)
Protected Attributes
bool bCacheOnNextLoad = true
bool bDoNotResetConfigFile = false
Private Member Functions
void AddStaticLayersToHierarchy (TArray< FString > *GatheredLayerFilenames=nullptr, bool bIsForLogging=false)
void CachePaths ()
bool GenerateDestIniFile ()
bool LoadIniFileHierarchy ()
void LogVariables (const TCHAR *InBaseIniName, const FString &Platform)
FString PerformFinalExpansions (const FString &InString, const FString &Platform)
bool PerformLoad ()
bool PerformSingleFileLoad ()
bool PrepareForLoad (bool &bPerformLoad)
FConfigContext & ResetBaseIni (const TCHAR *InBaseIniName)
Detailed Description
Definition at line 30 of file ConfigContext.h.
Constructor & Destructor Documentation
~FConfigContext()
FConfigContext::~FConfigContext ()
FConfigContext()
FConfigContext::FConfigContext (FConfigCacheIni * InConfigSystem, bool InIsHierarchicalConfig, const FString & InPlatform, FConfigFile * DestConfigFile = nullptr) protected
Referenced by FixupBranchAfterBinaryConfig(), ForceReloadIntoGConfig(), ReadIntoConfigSystem(), ReadIntoGConfig(), ReadIntoLocalFile(), ReadIntoPluginFile(), ReadPluginIntoConfigSystem(), ReadPluginToModifyConfigSystem(), ReadSingleIntoConfigSystem(), ReadSingleIntoGConfig(), ReadSingleIntoLocalFile(), ReadUpToBeforeFile(), and ResetBaseIni().
Member Function Documentation
AddStaticLayersToHierarchy()
void FConfigContext::AddStaticLayersToHierarchy (TArray< FString > * GatheredLayerFilenames = nullptr, bool bIsForLogging = false) private
CachePaths()
void FConfigContext::CachePaths () private
EnsureRequiredGlobalPathsHaveBeenInitialized()
void FConfigContext::EnsureRequiredGlobalPathsHaveBeenInitialized () static
Call to make before attempting parallel config init.
FixupBranchAfterBinaryConfig()
FConfigContext FConfigContext::FixupBranchAfterBinaryConfig () inline static
Create a context to read only the saved/generated file (eg.
<Project>/Saved/Windows/Input.ini) and commandline options after loading a binary config, that was of course made without saved files and commandline options
Definition at line 158 of file ConfigContext.h.
References FConfigContext(), and GConfig.
ForceReloadIntoGConfig()
FConfigContext FConfigContext::ForceReloadIntoGConfig () inline static
Create a context to read a hierarchical config into GConfig.
Only for current platform.
Definition at line 62 of file ConfigContext.h.
References FConfigContext(), and GConfig.
GenerateDestIniFile()
bool FConfigContext::GenerateDestIniFile () private
GetPerPlatformDirs()
const FPerPlatformDirs & FConfigContext::GetPerPlatformDirs (const FString & PlatformName)
Return the paths to use to find hierarchical config files for the given platform (note that these are independent of the ini name)
Load() [1/2]
bool FConfigContext::Load (const TCHAR * IniName)
Use the context to perform the actual load operation.
Note that this is where you specify the Ini name (for instance "Engine"), meaning you can use the same context for multiple configs (Engine, Game, Input, etc)
Load() [2/2]
bool FConfigContext::Load (const TCHAR * IniName, FString & OutFilename)
Use the context to perform the actual load operation as above, but will return the generated final ini filename (in the case of GConfig, this would be the key used to look up into GConfig, for example)
LoadIniFileHierarchy()
bool FConfigContext::LoadIniFileHierarchy () private
LogVariables()
void FConfigContext::LogVariables (const TCHAR * InBaseIniName, const FString & Platform) private
References Platform.
PerformFinalExpansions()
FString FConfigContext::PerformFinalExpansions (const FString & InString, const FString & Platform) private
References Platform.
PerformLoad()
bool FConfigContext::PerformLoad () private
PerformSingleFileLoad()
bool FConfigContext::PerformSingleFileLoad () private
PrepareForLoad()
bool FConfigContext::PrepareForLoad (bool & bPerformLoad) private
ReadIntoConfigSystem()
FConfigContext FConfigContext::ReadIntoConfigSystem (FConfigCacheIni * ConfigSystem, const FString & Platform) inline static
Create a context to read a hierarchical config into the given ConfigSystem structure - usually will be for other platforms.
Definition at line 80 of file ConfigContext.h.
References FConfigContext(), ConfigSystem, and Platform.
ReadIntoGConfig()
FConfigContext FConfigContext::ReadIntoGConfig () inline static
Create a context to read a hierarchical config into GConfig.
Only for current platform.
Definition at line 54 of file ConfigContext.h.
References FConfigContext(), and GConfig.
ReadIntoLocalFile()
FConfigContext FConfigContext::ReadIntoLocalFile (FConfigFile & DestConfigFile, const FString & Platform = FString()) inline static
Create a context to read a hierarchical config into the given local FConfigFile, optionally for another platform.
Definition at line 38 of file ConfigContext.h.
References FConfigContext(), and Platform.
ReadIntoPluginFile()
FConfigContext FConfigContext::ReadIntoPluginFile (FConfigFile & DestConfigFile, const FString & PluginRootDir, const TArray< FString > & ChildPluginsBaseDirs, const FString & Platform = FString()) inline static
Create a context to read a plugin's ini file named for the plugin.
This is not used for inserting, say, Engine.ini into GConfig
Definition at line 96 of file ConfigContext.h.
References FConfigContext(), Platform, and PluginRootDir.
ReadPluginIntoConfigSystem()
FConfigContext FConfigContext::ReadPluginIntoConfigSystem (FConfigCacheIni * ConfigSystem, FName PluginName, const FString & PluginRootDir, const TArray< FString > & ChildPluginsBaseDirs) inline static
Inserts plugin ini files into an existing Branch.
Definition at line 115 of file ConfigContext.h.
References FConfigContext(), ConfigSystem, and PluginRootDir.
ReadPluginToModifyConfigSystem()
FConfigContext FConfigContext::ReadPluginToModifyConfigSystem (FConfigCacheIni * ConfigSystem, DynamicLayerPriority Priority, FName PluginName, const FString & PluginRootDir, const TArray< FString > & ChildPluginsBaseDirs, FConfigModificationTracker * ChangeTracker = nullptr) inline static
Inserts plugin ini files into an existing Branch.
Definition at line 129 of file ConfigContext.h.
References FConfigContext(), ChangeTracker, ConfigSystem, and PluginRootDir.
ReadSingleIntoConfigSystem()
FConfigContext FConfigContext::ReadSingleIntoConfigSystem (FConfigCacheIni * ConfigSystem, const FString & Platform) inline static
Create a context to read a non-hierarchical config into the given ConfigSystem structure - usually will be for other platforms.
Definition at line 88 of file ConfigContext.h.
References FConfigContext(), ConfigSystem, GConfig, and Platform.
ReadSingleIntoGConfig()
FConfigContext FConfigContext::ReadSingleIntoGConfig () inline static
Create a context to read a non-hierarchical config into GConfig.
Only for current platform.
Definition at line 72 of file ConfigContext.h.
References FConfigContext(), and GConfig.
ReadSingleIntoLocalFile()
FConfigContext FConfigContext::ReadSingleIntoLocalFile (FConfigFile & DestConfigFile, const FString & Platform = FString()) inline static
Create a context to read a non-hierarchical config into the given local FConfigFile, optionally for another platform.
Definition at line 46 of file ConfigContext.h.
References FConfigContext(), and Platform.
ReadUpToBeforeFile()
FConfigContext FConfigContext::ReadUpToBeforeFile (FConfigFile & DestConfigFile, const FString & Platform, const FString & StartSkippingAtFilename) inline static
Create a context to read a hierarchy, but once it reaches the given filename (StartDeletingFilename), it will not read in anymore files at that point.
Definition at line 147 of file ConfigContext.h.
References FConfigContext(), Platform, and StartSkippingAtFilename.
ResetBaseIni()
FConfigContext & FConfigContext::ResetBaseIni (const TCHAR * InBaseIniName) private
References FConfigContext().
VisualizeHierarchy() [1/2]
void FConfigContext::VisualizeHierarchy (FOutputDevice & Ar, const TCHAR * IniName)
Visualize an existing hierarchy.
References Ar.
VisualizeHierarchy() [2/2]
void FConfigContext::VisualizeHierarchy (FOutputDevice & Ar, const TCHAR * IniName, const TCHAR * OverridePlatform, const TCHAR * OverrideProjectOrProgramDataDir, const TCHAR * OverridePluginDir = nullptr, const TArray< FString > * ChildPluginBaseDirs = nullptr) static
Log out the config full hierarchy of a file, with various overrides to see other projects/platforms/etc hierarchies.
References Ar, and ChildPluginBaseDirs.
Field Documentation
bAllowGeneratedIniWhenCooked
bool FConfigContext::bAllowGeneratedIniWhenCooked = false
Definition at line 241 of file ConfigContext.h.
bAllowRemoteConfig
bool FConfigContext::bAllowRemoteConfig = false
Definition at line 243 of file ConfigContext.h.
BaseIniName
FString FConfigContext::BaseIniName
Definition at line 218 of file ConfigContext.h.
bCacheOnNextLoad
bool FConfigContext::bCacheOnNextLoad = true protected
Definition at line 266 of file ConfigContext.h.
bDefaultEngineRequired
bool FConfigContext::bDefaultEngineRequired = false
Definition at line 246 of file ConfigContext.h.
bDoNotResetConfigFile
bool FConfigContext::bDoNotResetConfigFile = false protected
Definition at line 265 of file ConfigContext.h.
bForceReload
bool FConfigContext::bForceReload = false
Definition at line 242 of file ConfigContext.h.
bIncludeTagNameInBranchName
bool FConfigContext::bIncludeTagNameInBranchName = false
Definition at line 250 of file ConfigContext.h.
bIsFixingUpAfterBinaryConfig
bool FConfigContext::bIsFixingUpAfterBinaryConfig = false
Definition at line 252 of file ConfigContext.h.
bIsForPlugin
bool FConfigContext::bIsForPlugin = false
Definition at line 247 of file ConfigContext.h.
bIsForPluginModification
bool FConfigContext::bIsForPluginModification = false
Definition at line 248 of file ConfigContext.h.
bIsHierarchicalConfig
bool FConfigContext::bIsHierarchicalConfig
Definition at line 244 of file ConfigContext.h.
bIsMakingBinaryConfig
bool FConfigContext::bIsMakingBinaryConfig = false
Definition at line 251 of file ConfigContext.h.
Branch
FConfigBranch* FConfigContext::Branch = nullptr
Definition at line 211 of file ConfigContext.h.
bUseHierarchyCache
bool FConfigContext::bUseHierarchyCache = false
Definition at line 240 of file ConfigContext.h.
bWriteDestIni
bool FConfigContext::bWriteDestIni = false
Definition at line 245 of file ConfigContext.h.
ChangeTracker
FConfigModificationTracker* FConfigContext::ChangeTracker = nullptr
Definition at line 227 of file ConfigContext.h.
Referenced by ReadPluginToModifyConfigSystem().
ChildPluginBaseDirs
TArray<FString> FConfigContext::ChildPluginBaseDirs
Definition at line 226 of file ConfigContext.h.
Referenced by VisualizeHierarchy().
ConfigFileTag
FName FConfigContext::ConfigFileTag
Definition at line 229 of file ConfigContext.h.
ConfigSystem
FConfigCacheIni* FConfigContext::ConfigSystem
Definition at line 208 of file ConfigContext.h.
Referenced by ReadIntoConfigSystem(), ReadPluginIntoConfigSystem(), ReadPluginToModifyConfigSystem(), and ReadSingleIntoConfigSystem().
DestIniFilename
FString FConfigContext::DestIniFilename
Definition at line 214 of file ConfigContext.h.
EngineConfigDir
FString FConfigContext::EngineConfigDir
Definition at line 221 of file ConfigContext.h.
EngineRootDir
FString FConfigContext::EngineRootDir
Definition at line 222 of file ConfigContext.h.
ExistingFile
FConfigFile* FConfigContext::ExistingFile = nullptr
Definition at line 210 of file ConfigContext.h.
GeneratedConfigDir
FString FConfigContext::GeneratedConfigDir
Definition at line 217 of file ConfigContext.h.
HandleLayersFunction
TFunction<void(const TArray<FDynamicLayerInfo>&)> FConfigContext::HandleLayersFunction = nullptr
Definition at line 261 of file ConfigContext.h.
IniCacheSet
const TSet<FString>* FConfigContext::IniCacheSet = nullptr
Definition at line 257 of file ConfigContext.h.
OverrideLayers
TArray<FConfigLayer> FConfigContext::OverrideLayers
Definition at line 238 of file ConfigContext.h.
PerPlatformDirs
TMap<FString, FPerPlatformDirs> FConfigContext::PerPlatformDirs
Definition at line 235 of file ConfigContext.h.
Platform
FString FConfigContext::Platform
Definition at line 215 of file ConfigContext.h.
Referenced by LogVariables(), PerformFinalExpansions(), ReadIntoConfigSystem(), ReadIntoLocalFile(), ReadIntoPluginFile(), ReadSingleIntoConfigSystem(), ReadSingleIntoLocalFile(), and ReadUpToBeforeFile().
PluginModificationPriority
DynamicLayerPriority FConfigContext::PluginModificationPriority
Definition at line 254 of file ConfigContext.h.
PluginRootDir
FString FConfigContext::PluginRootDir
Definition at line 225 of file ConfigContext.h.
Referenced by ReadIntoPluginFile(), ReadPluginIntoConfigSystem(), and ReadPluginToModifyConfigSystem().
ProjectConfigDir
FString FConfigContext::ProjectConfigDir
Definition at line 223 of file ConfigContext.h.
ProjectLimitedAccessDir
FString FConfigContext::ProjectLimitedAccessDir
Definition at line 232 of file ConfigContext.h.
ProjectNoRedistDir
FString FConfigContext::ProjectNoRedistDir
Definition at line 234 of file ConfigContext.h.
ProjectNotForLicenseesDir
FString FConfigContext::ProjectNotForLicenseesDir
Definition at line 233 of file ConfigContext.h.
ProjectRootDir
FString FConfigContext::ProjectRootDir
Definition at line 224 of file ConfigContext.h.
SavePlatform
FString FConfigContext::SavePlatform
Definition at line 216 of file ConfigContext.h.
StagedGlobalConfigCache
const TSet<FString>* FConfigContext::StagedGlobalConfigCache = nullptr
Definition at line 258 of file ConfigContext.h.
StagedPluginConfigCache
const TSet<FString>* FConfigContext::StagedPluginConfigCache = nullptr
Definition at line 259 of file ConfigContext.h.
StartSkippingAtFilename
FString FConfigContext::StartSkippingAtFilename
Definition at line 219 of file ConfigContext.h.
Referenced by ReadUpToBeforeFile().
TemporaryBranch
FConfigBranch* FConfigContext::TemporaryBranch = nullptr
Definition at line 212 of file ConfigContext.h.
The documentation for this class was generated from the following file:
ConfigContext.h