Unreal Engine 5.6 C++ API: UnifiedBuffer.h File Reference
UnifiedBuffer.h File Reference
#include "Containers/ArrayView.h"
#include "Containers/DynamicRHIResourceArray.h"
#include "CoreMinimal.h"
#include "GenericPlatform/GenericPlatformMemory.h"
#include "HAL/Platform.h"
#include "HAL/UnrealMemory.h"
#include "Misc/AssertionMacros.h"
#include "PixelFormat.h"
#include "RHI.h"
#include "RHIUtilities.h"
#include "RenderGraphDefinitions.h"
#include "RenderGraphResources.h"
#include "Templates/RefCounting.h"
Data Structures
struct FAsyncScatterCopyParams
struct FMemcpyResourceParams
struct FMemsetResourceParams
class FRDGAsyncScatterUploadBuffer
class FRDGScatterUploadBase
class FRDGScatterUploadBuffer
class FRDGScatterUploadBuilder
struct FRDGScatterUploadBuilder::FPass
class FRDGScatterUploader
struct FResizeResourceSOAParams
struct FScatterCopyParams
class FScatterUploadBuffer
Functions
void LockIfValid (FRHICommandListBase &RHICmdList, FRDGScatterUploader *Uploader)
RENDERCORE_API void MemcpyResource (FRDGBuilder &GraphBuilder, FRDGBuffer *DstResource, FRDGBuffer *SrcResource, const FMemcpyResourceParams &Params)
RENDERCORE_API void MemcpyResource (FRDGBuilder &GraphBuilder, FRDGBufferUAV *DstResource, FRDGBufferSRV *SrcResource, const FMemcpyResourceParams &Params)
template<typename ResourceType>
RENDERCORE_API void MemcpyResource (FRHICommandList &RHICmdList, const ResourceType &DstBuffer, const ResourceType &SrcBuffer, const FMemcpyResourceParams &Params, bool bAlreadyInUAVOverlap=false)
RENDERCORE_API void MemsetResource (FRDGBuilder &GraphBuilder, FRDGBuffer *DstResource, const FMemsetResourceParams &Params)
RENDERCORE_API void MemsetResource (FRDGBuilder &GraphBuilder, FRDGBufferUAV *DstResource, const FMemsetResourceParams &Params)
template<typename ResourceType>
RENDERCORE_API void MemsetResource (FRHICommandList &RHICmdList, const ResourceType &DstBuffer, const FMemsetResourceParams &Params)
RENDERCORE_API FRDGBuffer * ResizeBufferIfNeeded (FRDGBuilder &GraphBuilder, TRefCountPtr< FRDGPooledBuffer > &ExternalBuffer, const FRDGBufferDesc &BufferDesc, const TCHAR *Name)
RENDERCORE_API FRDGBuffer * ResizeBufferIfNeeded (FRDGBuilder &GraphBuilder, TRefCountPtr< FRDGPooledBuffer > &ExternalBuffer, EPixelFormat Format, uint32 NumElements, const TCHAR *Name)
RENDERCORE_API FRDGBuffer * ResizeByteAddressBufferIfNeeded (FRDGBuilder &GraphBuilder, TRefCountPtr< FRDGPooledBuffer > &ExternalBuffer, uint32 NumBytes, const TCHAR *Name)
FRDGBuffer * ResizeByteAddressBufferIfNeededWithCurrentLLMTag (FRDGBuilder &GraphBuilder, TRefCountPtr< FRDGPooledBuffer > &ExternalBuffer, uint32 NumBytes, const TCHAR *Name)
RENDERCORE_API bool ResizeResourceIfNeeded (FRDGBuilder &GraphBuilder, FRWBuffer &Buffer, EPixelFormat Format, uint32 NumElements, const TCHAR *DebugName)
RENDERCORE_API bool ResizeResourceIfNeeded (FRDGBuilder &GraphBuilder, FRWBufferStructured &Buffer, uint32 NumBytes, const TCHAR *DebugName)
RENDERCORE_API bool ResizeResourceIfNeeded (FRDGBuilder &GraphBuilder, FRWByteAddressBuffer &Buffer, uint32 NumBytes, const TCHAR *DebugName)
RENDERCORE_API bool ResizeResourceIfNeeded (FRHICommandList &RHICmdList, FRWBuffer &Buffer, EPixelFormat Format, uint32 NumElements, const TCHAR *DebugName)
template<typename ResourceType>
RENDERCORE_API bool ResizeResourceIfNeeded (FRHICommandList &RHICmdList, ResourceType &Buffer, uint32 NumBytes, const TCHAR *DebugName)
RENDERCORE_API bool ResizeResourceSOAIfNeeded (FRDGBuilder &GraphBuilder, FRWBufferStructured &Buffer, const FResizeResourceSOAParams &Params, const TCHAR *DebugName)
This version will resize/allocate the buffer at once and add a RDG pass to perform the copy on the RDG time-line if there was previous data).
RENDERCORE_API bool ResizeResourceSOAIfNeeded (FRHICommandList &RHICmdList, FRWBufferStructured &Texture, const FResizeResourceSOAParams &Params, const TCHAR *DebugName)
RENDERCORE_API FRDGBuffer * ResizeStructuredBufferIfNeeded (FRDGBuilder &GraphBuilder, TRefCountPtr< FRDGPooledBuffer > &ExternalBuffer, uint32 NumBytes, const TCHAR *Name)
RENDERCORE_API FRDGBuffer * ResizeStructuredBufferSOAIfNeeded (FRDGBuilder &GraphBuilder, TRefCountPtr< FRDGPooledBuffer > &ExternalBuffer, const FResizeResourceSOAParams &Params, const TCHAR *DebugName)
void RENDERCORE_API ScatterCopyResource (FRDGBuilder &GraphBuilder, FRDGBuffer *DstResource, FRDGBufferSRV *ScatterBufferSRV, FRDGBufferSRV *UploadBufferSRV, const FAsyncScatterCopyParams &Params)
void RENDERCORE_API ScatterCopyResource (FRDGBuilder &GraphBuilder, FRDGBuffer *DstResource, FRDGBufferSRV *ScatterBufferSRV, FRDGBufferSRV *UploadBufferSRV, const FScatterCopyParams &Params)
void UnlockIfValid (FRHICommandListBase &RHICmdList, FRDGScatterUploader *Uploader)
Function Documentation
LockIfValid()
void LockIfValid (FRHICommandListBase & RHICmdList, FRDGScatterUploader * Uploader) inline
Definition at line 342 of file UnifiedBuffer.h.
References FRDGScatterUploader::Lock().
MemcpyResource() [1/3]
RENDERCORE_API void MemcpyResource (FRDGBuilder & GraphBuilder, FRDGBuffer * DstResource, FRDGBuffer * SrcResource, const FMemcpyResourceParams & Params) extern
References Params.
MemcpyResource() [2/3]
RENDERCORE_API void MemcpyResource (FRDGBuilder & GraphBuilder, FRDGBufferUAV * DstResource, FRDGBufferSRV * SrcResource, const FMemcpyResourceParams & Params) extern
References Params.
MemcpyResource() [3/3]
template<typename ResourceType> RENDERCORE_API void MemcpyResource (FRHICommandList & RHICmdList, const ResourceType & DstBuffer, const ResourceType & SrcBuffer, const FMemcpyResourceParams & Params, bool bAlreadyInUAVOverlap = false) extern
References Params.
MemsetResource() [1/3]
RENDERCORE_API void MemsetResource (FRDGBuilder & GraphBuilder, FRDGBuffer * DstResource, const FMemsetResourceParams & Params) extern
References Params.
MemsetResource() [2/3]
RENDERCORE_API void MemsetResource (FRDGBuilder & GraphBuilder, FRDGBufferUAV * DstResource, const FMemsetResourceParams & Params) extern
References Params.
MemsetResource() [3/3]
template<typename ResourceType> RENDERCORE_API void MemsetResource (FRHICommandList & RHICmdList, const ResourceType & DstBuffer, const FMemsetResourceParams & Params) extern
References Params.
ResizeBufferIfNeeded() [1/2]
RENDERCORE_API FRDGBuffer * ResizeBufferIfNeeded (FRDGBuilder & GraphBuilder, TRefCountPtr< FRDGPooledBuffer > & ExternalBuffer, const FRDGBufferDesc & BufferDesc, const TCHAR * Name) extern
References Name.
ResizeBufferIfNeeded() [2/2]
RENDERCORE_API FRDGBuffer * ResizeBufferIfNeeded (FRDGBuilder & GraphBuilder, TRefCountPtr< FRDGPooledBuffer > & ExternalBuffer, EPixelFormat Format, uint32 NumElements, const TCHAR * Name) extern
References Format, and Name.
ResizeByteAddressBufferIfNeeded()
RENDERCORE_API FRDGBuffer * ResizeByteAddressBufferIfNeeded (FRDGBuilder & GraphBuilder, TRefCountPtr< FRDGPooledBuffer > & ExternalBuffer, uint32 NumBytes, const TCHAR * Name) extern
References Name.
Referenced by ResizeByteAddressBufferIfNeededWithCurrentLLMTag().
ResizeByteAddressBufferIfNeededWithCurrentLLMTag()
FRDGBuffer * ResizeByteAddressBufferIfNeededWithCurrentLLMTag (FRDGBuilder & GraphBuilder, TRefCountPtr< FRDGPooledBuffer > & ExternalBuffer, uint32 NumBytes, const TCHAR * Name) inline
Definition at line 225 of file UnifiedBuffer.h.
References Name, and ResizeByteAddressBufferIfNeeded().
ResizeResourceIfNeeded() [1/5]
RENDERCORE_API bool ResizeResourceIfNeeded (FRDGBuilder & GraphBuilder, FRWBuffer & Buffer, EPixelFormat Format, uint32 NumElements, const TCHAR * DebugName)
References Buffer, and Format.
ResizeResourceIfNeeded() [2/5]
RENDERCORE_API bool ResizeResourceIfNeeded (FRDGBuilder & GraphBuilder, FRWBufferStructured & Buffer, uint32 NumBytes, const TCHAR * DebugName)
References Buffer.
ResizeResourceIfNeeded() [3/5]
RENDERCORE_API bool ResizeResourceIfNeeded (FRDGBuilder & GraphBuilder, FRWByteAddressBuffer & Buffer, uint32 NumBytes, const TCHAR * DebugName)
References Buffer.
ResizeResourceIfNeeded() [4/5]
RENDERCORE_API bool ResizeResourceIfNeeded (FRHICommandList & RHICmdList, FRWBuffer & Buffer, EPixelFormat Format, uint32 NumElements, const TCHAR * DebugName)
References Buffer, and Format.
ResizeResourceIfNeeded() [5/5]
template<typename ResourceType> RENDERCORE_API bool ResizeResourceIfNeeded (FRHICommandList & RHICmdList, ResourceType & Buffer, uint32 NumBytes, const TCHAR * DebugName) extern
References Buffer.
ResizeResourceSOAIfNeeded() [1/2]
RENDERCORE_API bool ResizeResourceSOAIfNeeded (FRDGBuilder & GraphBuilder, FRWBufferStructured & Buffer, const FResizeResourceSOAParams & Params, const TCHAR * DebugName)
This version will resize/allocate the buffer at once and add a RDG pass to perform the copy on the RDG time-line if there was previous data).
References Buffer, and Params.
ResizeResourceSOAIfNeeded() [2/2]
RENDERCORE_API bool ResizeResourceSOAIfNeeded (FRHICommandList & RHICmdList, FRWBufferStructured & Texture, const FResizeResourceSOAParams & Params, const TCHAR * DebugName)
References Params, and Texture.
ResizeStructuredBufferIfNeeded()
RENDERCORE_API FRDGBuffer * ResizeStructuredBufferIfNeeded (FRDGBuilder & GraphBuilder, TRefCountPtr< FRDGPooledBuffer > & ExternalBuffer, uint32 NumBytes, const TCHAR * Name) extern
References Name.
ResizeStructuredBufferSOAIfNeeded()
RENDERCORE_API FRDGBuffer * ResizeStructuredBufferSOAIfNeeded (FRDGBuilder & GraphBuilder, TRefCountPtr< FRDGPooledBuffer > & ExternalBuffer, const FResizeResourceSOAParams & Params, const TCHAR * DebugName) extern
References Params.
ScatterCopyResource() [1/2]
void RENDERCORE_API ScatterCopyResource (FRDGBuilder & GraphBuilder, FRDGBuffer * DstResource, FRDGBufferSRV * ScatterBufferSRV, FRDGBufferSRV * UploadBufferSRV, const FAsyncScatterCopyParams & Params)
References Params.
ScatterCopyResource() [2/2]
void RENDERCORE_API ScatterCopyResource (FRDGBuilder & GraphBuilder, FRDGBuffer * DstResource, FRDGBufferSRV * ScatterBufferSRV, FRDGBufferSRV * UploadBufferSRV, const FScatterCopyParams & Params)
References Params.
UnlockIfValid()
void UnlockIfValid (FRHICommandListBase & RHICmdList, FRDGScatterUploader * Uploader) inline
Definition at line 350 of file UnifiedBuffer.h.
References FRDGScatterUploader::Unlock().