Unreal Engine 5.6 C++ API: FRawObjectIterator Class Reference
FRawObjectIterator Class Reference
Class for iterating through all objects, including class default objects, unreachable objects...all UObjects.
#include "UObjectIterator.h"
Public Member Functions
FRawObjectIterator (bool bOnlyGCedObjects=false)
Constructor.
FORCEINLINE FUObjectItem * operator* () const
Iterator dereference.
FORCEINLINE FUObjectItem * operator-> () const
Iterator dereference.
Public Member Functions inherited from FUObjectArray::TIterator
TIterator (const FUObjectArray &InArray, bool bOnlyGCedObjects=false)
Constructor.
TIterator (EEndTagType, const TIterator &InIter)
Constructor.
FORCEINLINE int32 GetIndex () const
FORCEINLINE operator bool () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
bool operator!= (const TIterator &Rhs) const
FORCEINLINE void operator++ ()
Iterator advance.
bool operator== (const TIterator &Rhs) const
Additional Inherited Members
Public Types inherited from FUObjectArray::TIterator
enum EEndTagType { EndTag }
Protected Member Functions inherited from FUObjectArray::TIterator
FORCEINLINE bool Advance ()
Iterator advance with ordinary name for clarity in subclasses.
const FUObjectArray & GetIteratedArray () const
Gets the array this iterator iterates over.
FORCEINLINE FUObjectItem * GetObject () const
Dereferences the iterator with an ordinary name for clarity in derived classes.
Detailed Description
Class for iterating through all objects, including class default objects, unreachable objects...all UObjects.
Definition at line 20 of file UObjectIterator.h.
Constructor & Destructor Documentation
FRawObjectIterator()
FRawObjectIterator::FRawObjectIterator (bool bOnlyGCedObjects = false) inline
Constructor.
Parameters
bOnlyGCedObjects if true, skip all of the permanent objects
Definition at line 27 of file UObjectIterator.h.
References FUObjectArray::TIterator::TIterator(), and GUObjectArray.
Member Function Documentation
operator*()
FORCEINLINE FUObjectItem * FRawObjectIterator::operator* () const inline
Iterator dereference.
Returns
the object pointer pointed at by the iterator
Definition at line 35 of file UObjectIterator.h.
References FORCEINLINE, and FUObjectArray::TIterator::GetObject().
operator->()
FORCEINLINE FUObjectItem * FRawObjectIterator::operator-> () const inline
Iterator dereference.
Returns
the object pointer pointed at by the iterator
Definition at line 44 of file UObjectIterator.h.
References FORCEINLINE, and FUObjectArray::TIterator::GetObject().
The documentation for this class was generated from the following file:
UObjectIterator.h