Unreal Engine 5.6 C++ API: IInterpolationIndexProvider Class Reference
IInterpolationIndexProvider Class Reference abstract
Interface used to provide interpolation indices for per bone blends.
#include "AnimationRuntime.h"
Data Structures
struct FPerBoneInterpolationData
Public Member Functions
~IInterpolationIndexProvider ()=default
virtual TSharedPtr< FPerBoneInterpolationData > GetPerBoneInterpolationData (const USkeleton *Skeleton) const
virtual int32 GetPerBoneInterpolationIndex (const FCompactPoseBoneIndex &InCompactPoseBoneIndex, const FBoneContainer &RequiredBones, const FPerBoneInterpolationData *Data) const =0
virtual int32 GetPerBoneInterpolationIndex (const FSkeletonPoseBoneIndex InSkeletonBoneIndex, const USkeleton *TargetSkeleton, const IInterpolationIndexProvider::FPerBoneInterpolationData *Data) const =0
UE_DEPRECATED (5.0, "Please use the overload that takes a FCompactPoseBoneIndex") 1 virtual int32 GetPerBoneInterpolationIndex(int32 BoneIndex
Data Fields
const FBoneContainer const FPerBoneInterpolationData *Data const
const FBoneContainer & RequiredBones
Detailed Description
Interface used to provide interpolation indices for per bone blends.
Definition at line 73 of file AnimationRuntime.h.
Constructor & Destructor Documentation
~IInterpolationIndexProvider()
IInterpolationIndexProvider::~IInterpolationIndexProvider () default
Member Function Documentation
GetPerBoneInterpolationData()
virtual TSharedPtr< FPerBoneInterpolationData > IInterpolationIndexProvider::GetPerBoneInterpolationData (const USkeleton * Skeleton) const inline virtual
Definition at line 85 of file AnimationRuntime.h.
References Skeleton.
GetPerBoneInterpolationIndex() [1/2]
virtual int32 IInterpolationIndexProvider::GetPerBoneInterpolationIndex (const FCompactPoseBoneIndex & InCompactPoseBoneIndex, const FBoneContainer & RequiredBones, const FPerBoneInterpolationData * Data) const pure virtual
References const, GetPerBoneInterpolationIndex(), and RequiredBones.
Referenced by GetPerBoneInterpolationIndex(), GetPerBoneInterpolationIndex(), and UE_DEPRECATED().
GetPerBoneInterpolationIndex() [2/2]
virtual int32 IInterpolationIndexProvider::GetPerBoneInterpolationIndex (const FSkeletonPoseBoneIndex InSkeletonBoneIndex, const USkeleton * TargetSkeleton, const IInterpolationIndexProvider::FPerBoneInterpolationData * Data) const pure virtual
References const, and GetPerBoneInterpolationIndex().
UE_DEPRECATED()
IInterpolationIndexProvider::UE_DEPRECATED (5. 0, "Please use the overload that takes a FCompactPoseBoneIndex")
References GetPerBoneInterpolationIndex().
Field Documentation
const
const FBoneContainer const FPerBoneInterpolationData* Data IInterpolationIndexProvider::const
Definition at line 89 of file AnimationRuntime.h.
Referenced by GetPerBoneInterpolationIndex(), and GetPerBoneInterpolationIndex().
RequiredBones
const FBoneContainer& IInterpolationIndexProvider::RequiredBones
Definition at line 89 of file AnimationRuntime.h.
Referenced by GetPerBoneInterpolationIndex().
The documentation for this class was generated from the following file:
AnimationRuntime.h