Unreal Engine 5.6 C++ API: TIntrusiveDoubleLinkedList< InElementType, ContainerType > Class Template Reference
TIntrusiveDoubleLinkedList< InElementType, ContainerType > Class Template Reference
Intrusive double linked list.
#include "IntrusiveDoubleLinkedList.h"
Public Types
using ElementType = InElementType
using NodeType = TIntrusiveDoubleLinkedListNode<ElementType, ContainerType>
using TConstIterator = TIntrusiveDoubleLinkedListIterator<const NodeType>
using TIterator = TIntrusiveDoubleLinkedListIterator<NodeType>
Public Member Functions
FORCEINLINE TIntrusiveDoubleLinkedList ()
FORCEINLINE TIntrusiveDoubleLinkedList (const TIntrusiveDoubleLinkedList &)=delete
FORCEINLINE void AddHead (ElementType *Element)
FORCEINLINE void AddHead (TIntrusiveDoubleLinkedList &&Other)
FORCEINLINE void AddTail (ElementType *Element)
FORCEINLINE void AddTail (TIntrusiveDoubleLinkedList &&Other)
FORCEINLINE TIterator begin ()
FORCEINLINE TConstIterator begin () const
FORCEINLINE TIterator end ()
FORCEINLINE TConstIterator end () const
FORCEINLINE ElementType * GetHead ()
FORCEINLINE ElementType * GetTail ()
FORCEINLINE bool IsEmpty () const
FORCEINLINE bool IsFilled () const
FORCEINLINE TIntrusiveDoubleLinkedList & operator= (const TIntrusiveDoubleLinkedList &)=delete
FORCEINLINE ElementType * PopHead ()
FORCEINLINE ElementType * PopTail ()
FORCEINLINE void Reset ()
Fast empty that clears this list without changing the links in any elements.
Static Public Member Functions
static FORCEINLINE void InsertAfter (ElementType *InsertThis, ElementType *AfterThis)
static FORCEINLINE void InsertBefore (ElementType *InsertThis, ElementType *BeforeThis)
static FORCEINLINE void Remove (ElementType *Element)
Private Member Functions
FORCEINLINE ElementType * GetSentinel ()
FORCEINLINE const ElementType * GetSentinel () const
Private Attributes
NodeType Sentinel
Detailed Description
template<class InElementType, class ContainerType = InElementType>
class TIntrusiveDoubleLinkedList< InElementType, ContainerType >
Intrusive double linked list.
See also
TDoubleLinkedList
Definition at line 174 of file IntrusiveDoubleLinkedList.h.
Member Typedef Documentation
ElementType
template<class InElementType, class ContainerType = InElementType> using TIntrusiveDoubleLinkedList< InElementType, ContainerType >::ElementType = InElementType
Definition at line 178 of file IntrusiveDoubleLinkedList.h.
NodeType
template<class InElementType, class ContainerType = InElementType> using TIntrusiveDoubleLinkedList< InElementType, ContainerType >::NodeType = TIntrusiveDoubleLinkedListNode<ElementType, ContainerType>
Definition at line 179 of file IntrusiveDoubleLinkedList.h.
TConstIterator
template<class InElementType, class ContainerType = InElementType> using TIntrusiveDoubleLinkedList< InElementType, ContainerType >::TConstIterator = TIntrusiveDoubleLinkedListIterator<const NodeType>
Definition at line 295 of file IntrusiveDoubleLinkedList.h.
TIterator
template<class InElementType, class ContainerType = InElementType> using TIntrusiveDoubleLinkedList< InElementType, ContainerType >::TIterator = TIntrusiveDoubleLinkedListIterator<NodeType>
Definition at line 294 of file IntrusiveDoubleLinkedList.h.
Constructor & Destructor Documentation
TIntrusiveDoubleLinkedList() [1/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE TIntrusiveDoubleLinkedList< InElementType, ContainerType >::TIntrusiveDoubleLinkedList () inline nodiscard
Definition at line 181 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE.
Referenced by TIntrusiveDoubleLinkedList(), AddHead(), AddTail(), and operator=().
TIntrusiveDoubleLinkedList() [2/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE TIntrusiveDoubleLinkedList< InElementType, ContainerType >::TIntrusiveDoubleLinkedList (const TIntrusiveDoubleLinkedList< InElementType, ContainerType > &) delete
References TIntrusiveDoubleLinkedList(), and FORCEINLINE.
Member Function Documentation
AddHead() [1/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::AddHead (ElementType * Element) inline
Definition at line 211 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, GetSentinel(), and InsertAfter().
AddHead() [2/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::AddHead (TIntrusiveDoubleLinkedList< InElementType, ContainerType > && Other) inline
Definition at line 216 of file IntrusiveDoubleLinkedList.h.
References TIntrusiveDoubleLinkedList(), FORCEINLINE, GetSentinel(), Other, and Sentinel.
AddTail() [1/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::AddTail (ElementType * Element) inline
Definition at line 228 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, GetSentinel(), and InsertBefore().
AddTail() [2/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::AddTail (TIntrusiveDoubleLinkedList< InElementType, ContainerType > && Other) inline
Definition at line 233 of file IntrusiveDoubleLinkedList.h.
References TIntrusiveDoubleLinkedList(), FORCEINLINE, GetSentinel(), Other, and Sentinel.
begin() [1/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE TIterator TIntrusiveDoubleLinkedList< InElementType, ContainerType >::begin () inline nodiscard
Definition at line 297 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and Sentinel.
begin() [2/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE TConstIterator TIntrusiveDoubleLinkedList< InElementType, ContainerType >::begin () const inline nodiscard
Definition at line 298 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and Sentinel.
end() [1/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE TIterator TIntrusiveDoubleLinkedList< InElementType, ContainerType >::end () inline nodiscard
Definition at line 299 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and GetSentinel().
end() [2/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE TConstIterator TIntrusiveDoubleLinkedList< InElementType, ContainerType >::end () const inline nodiscard
Definition at line 300 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and GetSentinel().
GetHead()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedList< InElementType, ContainerType >::GetHead () inline nodiscard
Definition at line 245 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, IsFilled(), and Sentinel.
GetSentinel() [1/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedList< InElementType, ContainerType >::GetSentinel () inline nodiscard private
Definition at line 304 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and Sentinel.
Referenced by AddHead(), AddHead(), AddTail(), AddTail(), end(), end(), IsEmpty(), and IsFilled().
GetSentinel() [2/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE const ElementType * TIntrusiveDoubleLinkedList< InElementType, ContainerType >::GetSentinel () const inline nodiscard private
Definition at line 305 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and Sentinel.
GetTail()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedList< InElementType, ContainerType >::GetTail () inline nodiscard
Definition at line 250 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, IsFilled(), and Sentinel.
InsertAfter()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::InsertAfter (ElementType * InsertThis, ElementType * AfterThis) inline static
Definition at line 284 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and InsertAfter().
Referenced by AddHead(), and InsertAfter().
InsertBefore()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::InsertBefore (ElementType * InsertThis, ElementType * BeforeThis) inline static
Definition at line 289 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and InsertBefore().
Referenced by AddTail(), and InsertBefore().
IsEmpty()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE bool TIntrusiveDoubleLinkedList< InElementType, ContainerType >::IsEmpty () const inline nodiscard
Definition at line 200 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, GetSentinel(), and Sentinel.
Referenced by PopHead(), and PopTail().
IsFilled()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE bool TIntrusiveDoubleLinkedList< InElementType, ContainerType >::IsFilled () const inline nodiscard
Definition at line 204 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, GetSentinel(), and Sentinel.
Referenced by GetHead(), and GetTail().
operator=()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE TIntrusiveDoubleLinkedList & TIntrusiveDoubleLinkedList< InElementType, ContainerType >::operator= (const TIntrusiveDoubleLinkedList< InElementType, ContainerType > &) delete
References TIntrusiveDoubleLinkedList(), and FORCEINLINE.
PopHead()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedList< InElementType, ContainerType >::PopHead () inline nodiscard
Definition at line 255 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, IsEmpty(), Remove, and Sentinel.
PopTail()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedList< InElementType, ContainerType >::PopTail () inline nodiscard
Definition at line 267 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, IsEmpty(), Remove, and Sentinel.
Remove()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::Remove (ElementType * Element) inline static
Definition at line 279 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and Remove.
Reset()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedList< InElementType, ContainerType >::Reset () inline
Fast empty that clears this list without changing the links in any elements.
See also
IsEmpty, IsFilled
Definition at line 193 of file IntrusiveDoubleLinkedList.h.
References FORCEINLINE, and Sentinel.
Field Documentation
Sentinel
template<class InElementType, class ContainerType = InElementType> NodeType TIntrusiveDoubleLinkedList< InElementType, ContainerType >::Sentinel private
Definition at line 307 of file IntrusiveDoubleLinkedList.h.
Referenced by AddHead(), AddTail(), begin(), begin(), GetHead(), GetSentinel(), GetSentinel(), GetTail(), IsEmpty(), IsFilled(), PopHead(), PopTail(), and Reset().
The documentation for this class was generated from the following file:
IntrusiveDoubleLinkedList.h