Unreal Engine 5.6 C++ API: UE::MovieScene::TFilteredEntityTask< T > Struct Template Reference
UE::MovieScene::TFilteredEntityTask< T > Struct Template Reference
#include "MovieSceneEntitySystemTask.h"
Public Member Functions
TFilteredEntityTask (const TEntityTaskComponents< T... > &InComponents)
TFilteredEntityTask (const TEntityTaskComponents< T... > &InComponents, const FEntityComponentFilter &InFilter)
TFilteredEntityTask< T... > & AddDynamicReadDependency (const FComponentMask &InDynamicReadDependency)
TFilteredEntityTask< T... > & AddDynamicReadDependency (std::initializer_list< FComponentTypeID > InReadDependencies)
template<typename ComponentType>
TFilteredEntityTask< T... > & AddDynamicReadDependency (TArrayView< ComponentType > InReadDependencies)
TFilteredEntityTask< T... > & AddDynamicWriteDependency (const FComponentMask &InDynamicWriteDependency)
TFilteredEntityTask< T... > & AddDynamicWriteDependency (std::initializer_list< FComponentTypeID > InWriteDependencies)
template<typename ComponentType>
TFilteredEntityTask< T... > & AddDynamicWriteDependency (TArrayView< ComponentType > InWriteDependencies)
TFilteredEntityTask< T... > & CombineFilter (const FEntityComponentFilter &InFilter)
Combine this task's filter with the specified filter.
template<typename TaskImpl, typename... TaskConstructionArgs>
FGraphEventRef Dispatch_PerAllocation (FEntityManager *EntityManager, const FSystemTaskPrerequisites &Prerequisites, FSystemSubsequentTasks *Subsequents, TaskConstructionArgs &&... InArgs) const
Dispatch a task for every entity that matches the filters and component types.
template<typename TaskImpl, typename... TaskConstructionArgs>
FGraphEventRef Dispatch_PerEntity (FEntityManager *EntityManager, const FSystemTaskPrerequisites &Prerequisites, FSystemSubsequentTasks *Subsequents, TaskConstructionArgs &&... InArgs) const
Dispatch a task for every entity that matches the filters and component types.
TFilteredEntityTask< T... > & FilterAll (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that have all the specified components or tags.
TFilteredEntityTask< T... > & FilterAll (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that have all the specified components or tags.
TFilteredEntityTask< T... > & FilterAny (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that have at least one of the specified components or tags.
TFilteredEntityTask< T... > & FilterAny (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that have at least one of the specified components or tags.
TFilteredEntityTask< T... > & FilterNone (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that have none the specified components or tags.
TFilteredEntityTask< T... > & FilterNone (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that have none the specified components or tags.
TFilteredEntityTask< T... > & FilterOut (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that do not have the specific combination of components or tags.
TFilteredEntityTask< T... > & FilterOut (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that do not have the specific combination of components or tags.
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Fork_PerAllocation (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Fork_PerEntity (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
const TEntityTaskComponents< T... > & GetComponents () const
Access the underlying component access definitions.
ENamedThreads::Type GetDesiredThread () const
Get the desired thread for this task to run on.
const FEntityComponentFilter & GetFilter () const
Access the pre-populated filter that should be used for iterating relevant entities for this task.
TStatId GetStatId () const
Return this task's stat id.
template<typename Callback>
void Iterate_PerAllocation (FEntityManager *EntityManager, Callback &&InCallback) const
Perform a thread-safe iteration of all matching allocations within the specified entity manager using this task, inline on the current thread.
template<typename Callback>
void Iterate_PerEntity (FEntityManager *EntityManager, Callback &&InCallback) const
Perform a thread-safe iteration of all matching entities specified entity manager using this task, inline on the current thread.
template<typename TaskImpl>
void RunInline_PerAllocation (FEntityManager *EntityManager, TaskImpl &Task) const
template<typename TaskImpl>
void RunInline_PerEntity (FEntityManager *EntityManager, TaskImpl Task) const
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Schedule_PerAllocation (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Schedule_PerEntity (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
TFilteredEntityTask< T... > & SetDesiredThread (ENamedThreads::Type InDesiredThread)
Assign a desired thread for this task to run on.
TFilteredEntityTask< T... > & SetParams (const FTaskParams &InOtherParams)
Assign the scheduled task parameters for this task.
TFilteredEntityTask< T... > & SetStat (TStatId InStatId)
Assign a stat ID for this task.
bool ShouldBreakOnRun () const
Check whether we should break the debugger when this task is run.
Private Member Functions
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID ScheduleImpl (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, const FTaskParams &TaskParams, TaskFunctionPtr InFunction, TaskConstructionArgs &&... InArgs) const
Private Attributes
TEntityTaskComponents< T... > Components
FComponentMask DynamicReadMask
FComponentMask DynamicWriteMask
FEntityComponentFilter Filter
Detailed Description
template<typename... T>
struct UE::MovieScene::TFilteredEntityTask< T >
Definition at line 1028 of file MovieSceneEntitySystemTask.h.
Constructor & Destructor Documentation
TFilteredEntityTask() [1/2]
template<typename... T> UE::MovieScene::TFilteredEntityTask< T >::TFilteredEntityTask (const TEntityTaskComponents< T... > & InComponents) inline
Definition at line 1030 of file MovieSceneEntitySystemTask.h.
References Components, and Filter.
Referenced by AddDynamicReadDependency(), AddDynamicReadDependency(), AddDynamicReadDependency(), AddDynamicWriteDependency(), AddDynamicWriteDependency(), AddDynamicWriteDependency(), CombineFilter(), FilterAll(), FilterAll(), FilterAny(), FilterAny(), FilterNone(), FilterNone(), FilterOut(), FilterOut(), SetDesiredThread(), SetParams(), and SetStat().
TFilteredEntityTask() [2/2]
template<typename... T> UE::MovieScene::TFilteredEntityTask< T >::TFilteredEntityTask (const TEntityTaskComponents< T... > & InComponents, const FEntityComponentFilter & InFilter) inline
Definition at line 1035 of file MovieSceneEntitySystemTask.h.
References Components, and Filter.
Member Function Documentation
AddDynamicReadDependency() [1/3]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::AddDynamicReadDependency (const FComponentMask & InDynamicReadDependency) inline
Definition at line 1206 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), DynamicReadMask, and MaxSize.
AddDynamicReadDependency() [2/3]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::AddDynamicReadDependency (std::initializer_list< FComponentTypeID > InReadDependencies) inline
Definition at line 1192 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and DynamicReadMask.
AddDynamicReadDependency() [3/3]
template<typename... T> template<typename ComponentType> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::AddDynamicReadDependency (TArrayView< ComponentType > InReadDependencies) inline
Definition at line 1198 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), Component, and DynamicReadMask.
AddDynamicWriteDependency() [1/3]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::AddDynamicWriteDependency (const FComponentMask & InDynamicWriteDependency) inline
Definition at line 1226 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), DynamicWriteMask, and MaxSize.
AddDynamicWriteDependency() [2/3]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::AddDynamicWriteDependency (std::initializer_list< FComponentTypeID > InWriteDependencies) inline
Definition at line 1212 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and DynamicWriteMask.
AddDynamicWriteDependency() [3/3]
template<typename... T> template<typename ComponentType> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::AddDynamicWriteDependency (TArrayView< ComponentType > InWriteDependencies) inline
Definition at line 1218 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), Component, and DynamicWriteMask.
CombineFilter()
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::CombineFilter (const FEntityComponentFilter & InFilter) inline
Combine this task's filter with the specified filter.
Definition at line 1118 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
Referenced by UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateFromComponents(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateUnlinkedOnly().
Dispatch_PerAllocation()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FGraphEventRef UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerAllocation (FEntityManager * EntityManager, const FSystemTaskPrerequisites & Prerequisites, FSystemSubsequentTasks * Subsequents, TaskConstructionArgs &&... InArgs) const inline
Dispatch a task for every entity that matches the filters and component types.
Must be explicitly instantiated with the task type to dispatch. Construction arguments are deduced. Tasks must implement a ForEachEntity function that matches this task's component accessor types.
For example: struct FForEachEntity { void ForEachEntity(FMovieSceneEntityID InEntityID, const FMovieSceneFloatChannel& Channel); };
TComponentTypeID<FMovieSceneFloatChannel> FloatChannelComponent = ...;
FGraphEventRef Task = FEntityTaskBuilder() .ReadEntityIDs() .Read(FloatChannelComponent) .SetStat(GET_STATID(MyStatName)) .SetDesiredThread(ENamedThreads::AnyThread) .Dispatch_PerEntity<FForEachEntity>(EntityManager, Prerequisites);
Parameters
EntityManager The entity manager to run the task on. All component types must relate to this entity manager.
Prerequisites Prerequisite tasks that must run before this one, or nullptr if there are no prerequisites
Subsequents (Optional) Subsequent task tracking that this task should be added to for each writable component type
InArgs Optional arguments that are forwarded to the constructor of TaskImpl
Returns
A pointer to the graph event for the task, or nullptr if this task is not valid (ie contains invalid component types that would be necessary for the task to run), or threading is disabled
Definition at line 1258 of file MovieSceneEntitySystemTask.h.
References ENamedThreads::AnyThread, checkfSlow, checkSlow, Components, ensure, Forward(), IsInGameThread(), UE::MovieScene::NoThreading, TArray< InElementType, InAllocatorType >::Num(), and TEXT.
Dispatch_PerEntity()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FGraphEventRef UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerEntity (FEntityManager * EntityManager, const FSystemTaskPrerequisites & Prerequisites, FSystemSubsequentTasks * Subsequents, TaskConstructionArgs &&... InArgs) const inline
Dispatch a task for every entity that matches the filters and component types.
Must be explicitly instantiated with the task type to dispatch. Construction arguments are deduced. Tasks must implement a ForEachEntity function that matches this task's component accessor types.
For example: struct FForEachEntity { void ForEachEntity(FMovieSceneEntityID InEntityID, const FMovieSceneFloatChannel& Channel); };
TComponentTypeID<FMovieSceneFloatChannel> FloatChannelComponent = ...;
FGraphEventRef Task = FEntityTaskBuilder() .ReadEntityIDs() .Read(FloatChannelComponent) .SetStat(GET_STATID(MyStatName)) .SetDesiredThread(ENamedThreads::AnyThread) .Dispatch_PerEntity<FForEachEntity>(EntityManager, Prerequisites);
Parameters
EntityManager The entity manager to run the task on. All component types must relate to this entity manager.
Prerequisites Prerequisite tasks that must run before this one, or nullptr if there are no prerequisites
Subsequents (Optional) Subsequent task tracking that this task should be added to for each writable component type
InArgs Optional arguments that are forwarded to the constructor of TaskImpl
Returns
A pointer to the graph event for the task, or nullptr if this task is not valid (ie contains invalid component types that would be necessary for the task to run), or threading is disabled
Definition at line 1336 of file MovieSceneEntitySystemTask.h.
References ENamedThreads::AnyThread, checkfSlow, checkSlow, Components, ensure, Forward(), IsInGameThread(), UE::MovieScene::NoThreading, TArray< InElementType, InAllocatorType >::Num(), and TEXT.
FilterAll() [1/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterAll (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that have all the specified components or tags.
Definition at line 1046 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
FilterAll() [2/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterAll (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that have all the specified components or tags.
Definition at line 1055 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
FilterAny() [1/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterAny (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that have at least one of the specified components or tags.
Definition at line 1082 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
FilterAny() [2/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterAny (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that have at least one of the specified components or tags.
Definition at line 1091 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
FilterNone() [1/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterNone (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that have none the specified components or tags.
Definition at line 1064 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
FilterNone() [2/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterNone (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that have none the specified components or tags.
Definition at line 1073 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
FilterOut() [1/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterOut (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that do not have the specific combination of components or tags.
Definition at line 1100 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
FilterOut() [2/2]
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::FilterOut (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that do not have the specific combination of components or tags.
Definition at line 1109 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Filter.
Fork_PerAllocation()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TFilteredEntityTask< T >::Fork_PerAllocation (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 1398 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, Components, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerAllocation(), and ScheduleImpl().
Fork_PerEntity()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TFilteredEntityTask< T >::Fork_PerEntity (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 1380 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, Components, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerEntity(), and ScheduleImpl().
GetComponents()
template<typename... T> const TEntityTaskComponents< T... > & UE::MovieScene::TFilteredEntityTask< T >::GetComponents () const inline
Access the underlying component access definitions.
Definition at line 1187 of file MovieSceneEntitySystemTask.h.
References Components.
GetDesiredThread()
template<typename... T> ENamedThreads::Type UE::MovieScene::TFilteredEntityTask< T >::GetDesiredThread () const inline
Get the desired thread for this task to run on.
Definition at line 1155 of file MovieSceneEntitySystemTask.h.
References Components.
GetFilter()
template<typename... T> const FEntityComponentFilter & UE::MovieScene::TFilteredEntityTask< T >::GetFilter () const inline
Access the pre-populated filter that should be used for iterating relevant entities for this task.
Definition at line 1179 of file MovieSceneEntitySystemTask.h.
References Filter.
GetStatId()
template<typename... T> TStatId UE::MovieScene::TFilteredEntityTask< T >::GetStatId () const inline
Return this task's stat id.
Definition at line 1163 of file MovieSceneEntitySystemTask.h.
References Components.
Iterate_PerAllocation()
template<typename... T> template<typename Callback> void UE::MovieScene::TFilteredEntityTask< T >::Iterate_PerAllocation (FEntityManager * EntityManager, Callback && InCallback) const inline
Perform a thread-safe iteration of all matching allocations within the specified entity manager using this task, inline on the current thread.
Parameters
EntityManager The entity manager to iterate allocations for. All component type IDs in this class must relate to this entity manager
InCallback A callable type that matches the signature defined by ForEachAllocation ie void(FEntityAllocation*, const TFilteredEntityTask<T...>&)
Definition at line 1479 of file MovieSceneEntitySystemTask.h.
References Components, Filter, and Forward().
Iterate_PerEntity()
template<typename... T> template<typename Callback> void UE::MovieScene::TFilteredEntityTask< T >::Iterate_PerEntity (FEntityManager * EntityManager, Callback && InCallback) const inline
Perform a thread-safe iteration of all matching entities specified entity manager using this task, inline on the current thread.
Parameters
EntityManager The entity manager to iterate allocations for. All component type IDs in this class must relate to this entity manager
InCallback A callable type that matches the signature defined by ForEachEntity ie void(typename T::AccessType...)
Definition at line 1467 of file MovieSceneEntitySystemTask.h.
References Components, Filter, and Forward().
RunInline_PerAllocation()
template<typename... T> template<typename TaskImpl> void UE::MovieScene::TFilteredEntityTask< T >::RunInline_PerAllocation (FEntityManager * EntityManager, TaskImpl & Task) const inline
Definition at line 1302 of file MovieSceneEntitySystemTask.h.
References Components.
RunInline_PerEntity()
template<typename... T> template<typename TaskImpl> void UE::MovieScene::TFilteredEntityTask< T >::RunInline_PerEntity (FEntityManager * EntityManager, TaskImpl Task) const inline
Definition at line 1452 of file MovieSceneEntitySystemTask.h.
References Components.
Schedule_PerAllocation()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerAllocation (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 1434 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, Components, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerAllocation(), and ScheduleImpl().
Schedule_PerEntity()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerEntity (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 1416 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, Components, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerEntity(), and ScheduleImpl().
ScheduleImpl()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, const FTaskParams & TaskParams, TaskFunctionPtr InFunction, TaskConstructionArgs &&... InArgs) const inline private
Definition at line 1487 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::IEntitySystemScheduler::AddChildBack(), UE::MovieScene::IEntitySystemScheduler::AddChildFront(), UE::MovieScene::IEntitySystemScheduler::AddNullTask(), UE::MovieScene::FTaskParams::bForcePrePostTask, Components, UE::MovieScene::IEntitySystemScheduler::CreateForkedAllocationTask(), DynamicReadMask, DynamicWriteMask, Filter, Forward(), MakeShared(), UE::MovieScene::FTaskID::None(), UE::MovieScene::SchedulePostTask(), and UE::MovieScene::SchedulePreTask().
Referenced by Fork_PerAllocation(), Fork_PerEntity(), Schedule_PerAllocation(), and Schedule_PerEntity().
SetDesiredThread()
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::SetDesiredThread (ENamedThreads::Type InDesiredThread) inline
Assign a desired thread for this task to run on.
Definition at line 1127 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), Components, ENamedThreads::GameThread, and ENamedThreads::GameThread_Local.
SetParams()
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::SetParams (const FTaskParams & InOtherParams) inline
Assign the scheduled task parameters for this task.
Definition at line 1146 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Components.
SetStat()
template<typename... T> TFilteredEntityTask< T... > & UE::MovieScene::TFilteredEntityTask< T >::SetStat (TStatId InStatId) inline
Assign a stat ID for this task.
Definition at line 1137 of file MovieSceneEntitySystemTask.h.
References TFilteredEntityTask(), and Components.
ShouldBreakOnRun()
template<typename... T> bool UE::MovieScene::TFilteredEntityTask< T >::ShouldBreakOnRun () const inline
Check whether we should break the debugger when this task is run.
Definition at line 1171 of file MovieSceneEntitySystemTask.h.
References Components.
Field Documentation
Components
template<typename... T> TEntityTaskComponents<T...> UE::MovieScene::TFilteredEntityTask< T >::Components private
Definition at line 1531 of file MovieSceneEntitySystemTask.h.
Referenced by TFilteredEntityTask(), TFilteredEntityTask(), Dispatch_PerAllocation(), Dispatch_PerEntity(), Fork_PerAllocation(), Fork_PerEntity(), GetComponents(), GetDesiredThread(), GetStatId(), Iterate_PerAllocation(), Iterate_PerEntity(), RunInline_PerAllocation(), RunInline_PerEntity(), Schedule_PerAllocation(), Schedule_PerEntity(), ScheduleImpl(), SetDesiredThread(), SetParams(), SetStat(), and ShouldBreakOnRun().
DynamicReadMask
template<typename... T> FComponentMask UE::MovieScene::TFilteredEntityTask< T >::DynamicReadMask private
Definition at line 1534 of file MovieSceneEntitySystemTask.h.
Referenced by AddDynamicReadDependency(), AddDynamicReadDependency(), AddDynamicReadDependency(), and ScheduleImpl().
DynamicWriteMask
template<typename... T> FComponentMask UE::MovieScene::TFilteredEntityTask< T >::DynamicWriteMask private
Definition at line 1535 of file MovieSceneEntitySystemTask.h.
Referenced by AddDynamicWriteDependency(), AddDynamicWriteDependency(), AddDynamicWriteDependency(), and ScheduleImpl().
Filter
template<typename... T> FEntityComponentFilter UE::MovieScene::TFilteredEntityTask< T >::Filter private
Definition at line 1533 of file MovieSceneEntitySystemTask.h.
Referenced by TFilteredEntityTask(), TFilteredEntityTask(), CombineFilter(), FilterAll(), FilterAll(), FilterAny(), FilterAny(), FilterNone(), FilterNone(), FilterOut(), FilterOut(), GetFilter(), Iterate_PerAllocation(), Iterate_PerEntity(), and ScheduleImpl().
The documentation for this struct was generated from the following file:
MovieSceneEntitySystemTask.h