Unreal Engine 5.6 C++ API: IndexedHandle.h File Reference
IndexedHandle.h File Reference
#include "CoreMinimal.h"
#include "Containers/Array.h"
#include <atomic>
#include "IndexedHandle.generated.h"
Data Structures
struct FCompactIndexedHandleManager< TIndexedHandle, bOptimizeHandleReuse >
struct FIndexedHandleManager< TIndexedHandle, bOptimizeHandleReuse >
struct FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >
Handle Manager meant for FIndexedHandleBase and FCompactIndexedHandleBase derived classes, handles are given out from a freelist and are zero based and consecutive in nature, so ideal for being used as indices in to arrays.
Macros
#define UE_DO_INDEXED_HANDLE_MANAGER_ID 1
Functions
USTRUCT () struct FSimpleIndexedHandleBase
Index based handle that doesn't use a serial number.
Variables
template<typename TIndexedHandle, typename TIndexType, typename TSerialType, bool bOptimizeHandleReuse>
std::atomic< uint32 > FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >::ManagerIDCounter = { 0 }
template<typename TIndexedHandle, typename TIndexType, typename TSerialType, bool bOptimizeHandleReuse>
std::atomic< TSerialType > FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >::SerialNumberCounter = { 0 }
Macro Definition Documentation
UE_DO_INDEXED_HANDLE_MANAGER_ID
#define UE_DO_INDEXED_HANDLE_MANAGER_ID 1
Definition at line 11 of file IndexedHandle.h.
Function Documentation
USTRUCT()
USTRUCT ()
Index based handle that doesn't use a serial number.
Index based handle that has a serial number to verify stale handles.
For fast access in to index based data structures when we don't expect handles to be able to be stale
For fast safe access in to index based data structures Compact Index based handle that has a serial number to verify stale handles. For fast safe access in to index based data structures.
Parameters
InIndex - passing INDEX_NONE will make this handle Invalid
Returns
INDEX_NONE if invalid or >=0 for a potentially valid handle
true if this handle is valid, this doesn't check that it's in the correct range for the underlying resource it's providing a handle for
boolean operator useful when embedding declaration in if statement
Returns
same as IsValid()
See also
IsValid
Makes the handle Invalid
Parameters
InIndex - passing INDEX_NONE will make this handle Invalid
Note
passing INDEX_NONE as index will make this handle Invalid
Returns
INDEX_NONE if invalid or >=0 for a potentially valid handle
true if this handle is valid, this doesn't check that it's in the correct range for the underlying resource it's providing a handle for
boolean operator useful when embedding declaration in if statement
Returns
same as IsValid()
See also
IsValid
Makes the handle Invalid
Parameters
InIndex - passing INDEX_NONE will make this handle Invalid
Definition at line 21 of file IndexedHandle.h.
References bool, GENERATED_BODY, GetTypeHash(), Handle, INDEX_NONE, IsValid(), operator!=(), operator==(), and Other.
Variable Documentation
FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >::ManagerIDCounter
template<typename TIndexedHandle, typename TIndexType, typename TSerialType, bool bOptimizeHandleReuse> std::atomic<uint32> FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >::ManagerIDCounter = { 0 }
Definition at line 328 of file IndexedHandle.h.
FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >::SerialNumberCounter
template<typename TIndexedHandle, typename TIndexType, typename TSerialType, bool bOptimizeHandleReuse> std::atomic<TSerialType> FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >::SerialNumberCounter = { 0 }
Definition at line 324 of file IndexedHandle.h.