Unreal Engine 5.6 C++ API: TManagedStoragePlatformFile< BaseClass > Class Template Reference
TManagedStoragePlatformFile< BaseClass > Class Template Reference
#include "IPlatformFileManagedStorageWrapper.h"
Public Member Functions
TManagedStoragePlatformFile ()
virtual bool CopyFile (const TCHAR *To, const TCHAR *From, EPlatformFileRead ReadFlags=EPlatformFileRead::None, EPlatformFileWrite WriteFlags=EPlatformFileWrite::None) override
virtual bool DeleteFile (const TCHAR *Filename) override
virtual bool DeleteFiles (const TArrayView< const TCHAR * > &Filenames) override
virtual bool MoveFile (const TCHAR *To, const TCHAR *From) override
virtual IFileHandle * OpenWrite (const TCHAR *Filename, bool bAppend=false, bool bAllowRead=false) override
Static Private Member Functions
static bool IsReady ()
Detailed Description
template<class BaseClass>
class TManagedStoragePlatformFile< BaseClass >
Definition at line 826 of file IPlatformFileManagedStorageWrapper.h.
Constructor & Destructor Documentation
TManagedStoragePlatformFile()
template<class BaseClass> TManagedStoragePlatformFile< BaseClass >::TManagedStoragePlatformFile () inline
Definition at line 837 of file IPlatformFileManagedStorageWrapper.h.
References check, IPlatformFile::CopyDirectoryTree(), IPlatformFile::DeleteDirectoryRecursively(), LowLevelFatalError, and TEXT.
Member Function Documentation
CopyFile()
template<class BaseClass> virtual bool TManagedStoragePlatformFile< BaseClass >::CopyFile (const TCHAR * To, const TCHAR * From, EPlatformFileRead ReadFlags = EPlatformFileRead::None, EPlatformFileWrite WriteFlags = EPlatformFileWrite::None) inline override virtual
Definition at line 1030 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::AddOrUpdateFile(), ensureAlways, EnumHasAnyFlags(), Error, FPersistentStorageManager::Get(), IsReady(), None, OnlyUpdateIfLess, FPersistentStorageManager::RemoveFileFromManager(), RespectQuota, TEXT, FPersistentStorageManager::TryManageFile(), and UE_LOG.
DeleteFile()
template<class BaseClass> virtual bool TManagedStoragePlatformFile< BaseClass >::DeleteFile (const TCHAR * Filename) inline override virtual
Definition at line 858 of file IPlatformFileManagedStorageWrapper.h.
References Filename, FPersistentStorageManager::Get(), IsReady(), FPersistentStorageManager::RemoveFileFromManager(), and FPersistentStorageManager::TryManageFile().
DeleteFiles()
template<class BaseClass> virtual bool TManagedStoragePlatformFile< BaseClass >::DeleteFiles (const TArrayView< const TCHAR * > & Filenames) inline override virtual
Definition at line 880 of file IPlatformFileManagedStorageWrapper.h.
References Count, Display, TArray< InElementType, InAllocatorType >::Emplace(), Filename, FPersistentStorageManager::Get(), IsReady(), Key, MoveTemp(), TArrayView< InElementType, InSizeType >::Num(), FPersistentStorageManager::RemoveFileFromManager(), TArray< InElementType, InAllocatorType >::Reserve(), TEXT, FPersistentStorageManager::TryManageFile(), UE_LOG, and Warning.
IsReady()
template<class BaseClass> bool TManagedStoragePlatformFile< BaseClass >::IsReady () inline static private
Definition at line 829 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::IsReady().
Referenced by CopyFile(), DeleteFile(), DeleteFiles(), MoveFile(), and OpenWrite().
MoveFile()
template<class BaseClass> virtual bool TManagedStoragePlatformFile< BaseClass >::MoveFile (const TCHAR * To, const TCHAR * From) inline override virtual
Definition at line 916 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::AddOrUpdateFile(), ensureAlways, EnumHasAnyFlags(), Error, FPersistentStorageManager::Get(), IsReady(), OnlyUpdateIfLess, FPersistentStorageManager::RemoveFileFromManager(), RespectQuota, TEXT, FPersistentStorageManager::TryManageFile(), and UE_LOG.
OpenWrite()
template<class BaseClass> virtual IFileHandle * TManagedStoragePlatformFile< BaseClass >::OpenWrite (const TCHAR * Filename, bool bAppend = false, bool bAllowRead = false) inline override virtual
Definition at line 984 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::AddOrUpdateFile(), FPaths::ConvertRelativePathToFull(), Error, Filename, FPersistentManagedFile::FullFilename, FPersistentStorageManager::Get(), FPersistentStorageManager::IsCategoryForFileFull(), IsReady(), MoveTemp(), IFileHandle::Size(), TEXT, FPersistentStorageManager::TryManageFile(), and UE_LOG.
The documentation for this class was generated from the following file:
IPlatformFileManagedStorageWrapper.h