Unreal Engine 5.6 C++ API: FBitSet Struct Reference
FBitSet Struct Reference
#include "BitArray.h"
Static Public Member Functions
static FORCEINLINE uint32 CalculateNumWords (int32 NumBits)
static FORCEINLINE uint32 GetAndClearNextBit (uint32 &Mask)
Clears the next set bit in the mask and returns its index.
Static Public Attributes
static constexpr uint32 BitsPerWord = NumBitsPerDWORD
Detailed Description
Definition at line 25 of file BitArray.h.
Member Function Documentation
CalculateNumWords()
FORCEINLINE uint32 FBitSet::CalculateNumWords (int32 NumBits) inline static
Definition at line 39 of file BitArray.h.
References BitsPerWord, checkSlow, FMath::DivideAndRoundUp(), and FORCEINLINE.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Empty(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Empty(), TBitArray< typename Allocator::BitArrayAllocator >::FindFromImpl(), TBitArray< typename Allocator::BitArrayAllocator >::FindLastFromImpl(), TBitArray< typename Allocator::BitArrayAllocator >::GetAllocatedSize(), TBitArray< typename Allocator::BitArrayAllocator >::GetMaxWords(), TBitArray< typename Allocator::BitArrayAllocator >::GetNumWords(), GetTypeHash(), TBitArray< typename Allocator::BitArrayAllocator >::Realloc(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Realloc(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::ReallocGrow(), TBitArray< typename Allocator::BitArrayAllocator >::Reserve(), TBitArray< typename Allocator::BitArrayAllocator >::Serialize(), and TBitArray< typename Allocator::BitArrayAllocator >::SetNumUninitialized().
GetAndClearNextBit()
FORCEINLINE uint32 FBitSet::GetAndClearNextBit (uint32 & Mask) inline static
Clears the next set bit in the mask and returns its index.
Definition at line 28 of file BitArray.h.
References FORCEINLINE, and Mask.
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
Field Documentation
BitsPerWord
uint32 FBitSet::BitsPerWord = NumBitsPerDWORD static constexpr
Definition at line 37 of file BitArray.h.
Referenced by CalculateNumWords(), TBitArray< typename Allocator::BitArrayAllocator >::FindFromImpl(), and TBitArray< typename Allocator::BitArrayAllocator >::GetLastWordMask().
The documentation for this struct was generated from the following file:
BitArray.h