Unreal Engine 5.6 C++ API: FRDGParameter Class Reference
FRDGParameter Class Reference final
A helper class for identifying and accessing a render graph pass parameter.
#include "RenderGraphParameter.h"
Public Member Functions
FRDGParameter ()=default
FRDGBufferRef GetAsBuffer () const
FRDGBufferAccess GetAsBufferAccess () const
const FRDGBufferAccessArray & GetAsBufferAccessArray () const
FRDGBufferSRVRef GetAsBufferSRV () const
FRDGBufferUAVRef GetAsBufferUAV () const
const FRenderTargetBindingSlots & GetAsRenderTargetBindingSlots () const
FRDGResourceRef GetAsResource () const
FRDGShaderResourceViewRef GetAsSRV () const
FRDGTextureRef GetAsTexture () const
FRDGTextureAccess GetAsTextureAccess () const
const FRDGTextureAccessArray & GetAsTextureAccessArray () const
FRDGTextureSRVRef GetAsTextureSRV () const
FRDGTextureUAVRef GetAsTextureUAV () const
FRDGUnorderedAccessViewRef GetAsUAV () const
FRDGUniformBufferBinding GetAsUniformBuffer () const
FRDGViewRef GetAsView () const
FRDGViewableResource * GetAsViewableResource () const
EUniformBufferBaseType GetType () const
bool IsBuffer () const
bool IsBufferAccess () const
bool IsBufferAccessArray () const
bool IsRenderTargetBindingSlots () const
bool IsResource () const
bool IsResourceAccessArray () const
bool IsSRV () const
bool IsTexture () const
bool IsTextureAccess () const
bool IsTextureAccessArray () const
bool IsUAV () const
bool IsUniformBuffer () const
bool IsView () const
bool IsViewableResource () const
Private Member Functions
FRDGParameter (EUniformBufferBaseType InMemberType, void *InMemberPtr)
template<typename T>
T * GetAs () const
Private Attributes
void *const MemberPtr = nullptr
const EUniformBufferBaseType MemberType = UBMT_INVALID
Friends
class FRDGParameterStruct
Detailed Description
A helper class for identifying and accessing a render graph pass parameter.
Definition at line 9 of file RenderGraphParameter.h.
Constructor & Destructor Documentation
FRDGParameter() [1/2]
FRDGParameter::FRDGParameter () default
FRDGParameter() [2/2]
FRDGParameter::FRDGParameter (EUniformBufferBaseType InMemberType, void * InMemberPtr) inline private
Definition at line 194 of file RenderGraphParameter.h.
References MemberPtr, and MemberType.
Member Function Documentation
GetAs()
template<typename T> T * FRDGParameter::GetAs () const inline private
Definition at line 200 of file RenderGraphParameter.h.
References MemberPtr.
Referenced by GetAsBuffer(), GetAsBufferAccess(), GetAsBufferAccessArray(), GetAsBufferSRV(), GetAsBufferUAV(), GetAsRenderTargetBindingSlots(), GetAsResource(), GetAsSRV(), GetAsTexture(), GetAsTextureAccess(), GetAsTextureAccessArray(), GetAsTextureSRV(), GetAsTextureUAV(), GetAsUAV(), GetAsUniformBuffer(), GetAsView(), and GetAsViewableResource().
GetAsBuffer()
FRDGBufferRef FRDGParameter::GetAsBuffer () const inline
Definition at line 145 of file RenderGraphParameter.h.
References check, GetAs(), and IsBuffer().
GetAsBufferAccess()
FRDGBufferAccess FRDGParameter::GetAsBufferAccess () const inline
Definition at line 151 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsBufferAccessArray()
const FRDGBufferAccessArray & FRDGParameter::GetAsBufferAccessArray () const inline
Definition at line 157 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsBufferSRV()
FRDGBufferSRVRef FRDGParameter::GetAsBufferSRV () const inline
Definition at line 169 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsBufferUAV()
FRDGBufferUAVRef FRDGParameter::GetAsBufferUAV () const inline
Definition at line 181 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsRenderTargetBindingSlots()
const FRenderTargetBindingSlots & FRDGParameter::GetAsRenderTargetBindingSlots () const inline
Definition at line 187 of file RenderGraphParameter.h.
References check, GetAs(), and IsRenderTargetBindingSlots().
GetAsResource()
FRDGResourceRef FRDGParameter::GetAsResource () const inline
Definition at line 91 of file RenderGraphParameter.h.
References check, GetAs(), and IsResource().
GetAsSRV()
FRDGShaderResourceViewRef FRDGParameter::GetAsSRV () const inline
Definition at line 115 of file RenderGraphParameter.h.
References check, GetAs(), and IsSRV().
GetAsTexture()
FRDGTextureRef FRDGParameter::GetAsTexture () const inline
Definition at line 127 of file RenderGraphParameter.h.
References check, GetAs(), and IsTexture().
GetAsTextureAccess()
FRDGTextureAccess FRDGParameter::GetAsTextureAccess () const inline
Definition at line 133 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsTextureAccessArray()
const FRDGTextureAccessArray & FRDGParameter::GetAsTextureAccessArray () const inline
Definition at line 139 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsTextureSRV()
FRDGTextureSRVRef FRDGParameter::GetAsTextureSRV () const inline
Definition at line 163 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsTextureUAV()
FRDGTextureUAVRef FRDGParameter::GetAsTextureUAV () const inline
Definition at line 175 of file RenderGraphParameter.h.
References check, GetAs(), and MemberType.
GetAsUAV()
FRDGUnorderedAccessViewRef FRDGParameter::GetAsUAV () const inline
Definition at line 121 of file RenderGraphParameter.h.
References check, GetAs(), and IsUAV().
GetAsUniformBuffer()
FRDGUniformBufferBinding FRDGParameter::GetAsUniformBuffer () const inline
Definition at line 97 of file RenderGraphParameter.h.
References check, GetAs(), and IsUniformBuffer().
GetAsView()
FRDGViewRef FRDGParameter::GetAsView () const inline
Definition at line 109 of file RenderGraphParameter.h.
References check, GetAs(), and IsView().
GetAsViewableResource()
FRDGViewableResource * FRDGParameter::GetAsViewableResource () const inline
Definition at line 103 of file RenderGraphParameter.h.
References check, GetAs(), and IsViewableResource().
GetType()
EUniformBufferBaseType FRDGParameter::GetType () const inline
Definition at line 86 of file RenderGraphParameter.h.
References MemberType.
IsBuffer()
bool FRDGParameter::IsBuffer () const inline
Definition at line 51 of file RenderGraphParameter.h.
References MemberType.
Referenced by GetAsBuffer(), and IsViewableResource().
IsBufferAccess()
bool FRDGParameter::IsBufferAccess () const inline
Definition at line 56 of file RenderGraphParameter.h.
References MemberType.
IsBufferAccessArray()
bool FRDGParameter::IsBufferAccessArray () const inline
Definition at line 61 of file RenderGraphParameter.h.
References MemberType.
Referenced by IsResourceAccessArray().
IsRenderTargetBindingSlots()
bool FRDGParameter::IsRenderTargetBindingSlots () const inline
Definition at line 81 of file RenderGraphParameter.h.
References MemberType.
Referenced by GetAsRenderTargetBindingSlots(), and IsResource().
IsResource()
bool FRDGParameter::IsResource () const inline
Definition at line 14 of file RenderGraphParameter.h.
References IsRenderTargetBindingSlots(), and IsResourceAccessArray().
Referenced by GetAsResource().
IsResourceAccessArray()
bool FRDGParameter::IsResourceAccessArray () const inline
Definition at line 66 of file RenderGraphParameter.h.
References IsBufferAccessArray(), and IsTextureAccessArray().
Referenced by IsResource().
IsSRV()
bool FRDGParameter::IsSRV () const inline
Definition at line 19 of file RenderGraphParameter.h.
References MemberType.
Referenced by GetAsSRV(), and IsView().
IsTexture()
bool FRDGParameter::IsTexture () const inline
Definition at line 34 of file RenderGraphParameter.h.
References MemberType.
Referenced by GetAsTexture(), and IsViewableResource().
IsTextureAccess()
bool FRDGParameter::IsTextureAccess () const inline
Definition at line 41 of file RenderGraphParameter.h.
References MemberType.
IsTextureAccessArray()
bool FRDGParameter::IsTextureAccessArray () const inline
Definition at line 46 of file RenderGraphParameter.h.
References MemberType.
Referenced by IsResourceAccessArray().
IsUAV()
bool FRDGParameter::IsUAV () const inline
Definition at line 24 of file RenderGraphParameter.h.
References MemberType.
Referenced by GetAsUAV(), and IsView().
IsUniformBuffer()
bool FRDGParameter::IsUniformBuffer () const inline
Definition at line 71 of file RenderGraphParameter.h.
References MemberType.
Referenced by GetAsUniformBuffer().
IsView()
bool FRDGParameter::IsView () const inline
Definition at line 29 of file RenderGraphParameter.h.
References IsSRV(), and IsUAV().
Referenced by GetAsView().
IsViewableResource()
bool FRDGParameter::IsViewableResource () const inline
Definition at line 76 of file RenderGraphParameter.h.
References IsBuffer(), and IsTexture().
Referenced by GetAsViewableResource().
Friends And Related Symbol Documentation
FRDGParameterStruct
friend class FRDGParameterStruct friend
Definition at line 208 of file RenderGraphParameter.h.
References FRDGParameterStruct.
Referenced by FRDGParameterStruct.
Field Documentation
MemberPtr
void* const FRDGParameter::MemberPtr = nullptr private
Definition at line 206 of file RenderGraphParameter.h.
Referenced by FRDGParameter(), and GetAs().
MemberType
const EUniformBufferBaseType FRDGParameter::MemberType = UBMT_INVALID private
Definition at line 205 of file RenderGraphParameter.h.
Referenced by FRDGParameter(), GetAsBufferAccess(), GetAsBufferAccessArray(), GetAsBufferSRV(), GetAsBufferUAV(), GetAsTextureAccess(), GetAsTextureAccessArray(), GetAsTextureSRV(), GetAsTextureUAV(), GetType(), IsBuffer(), IsBufferAccess(), IsBufferAccessArray(), IsRenderTargetBindingSlots(), IsSRV(), IsTexture(), IsTextureAccess(), IsTextureAccessArray(), IsUAV(), and IsUniformBuffer().
The documentation for this class was generated from the following file:
RenderGraphParameter.h