Unreal Engine 5.6 C++ API: StreamableManagerError.h File Reference
StreamableManagerError.h File Reference
#include "Experimental/UnifiedError/UnifiedError.h"
#include "UObject/UObjectGlobals.h"
Data Structures
class UE::UnifiedError::StreamableManager::FStreamableManagerAdditionalContext
class UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::UnifiedError
namespace UE::UnifiedError::StreamableManager
Functions
DECLARE_ERROR (AsyncLoadCancelled, 9, StreamableManager, NSLOCTEXT("StreamableManager", "AsyncLoadCancelled", "Async load cancelled"))
DECLARE_ERROR (AsyncLoadFailed, 8, StreamableManager, NSLOCTEXT("StreamableManager", "AsyncLoadFailed", "Async load failed"))
DECLARE_ERROR (AsyncLoadNotInstalled, 12, StreamableManager, NSLOCTEXT("StreamableManager", "AsyncLoadNotInstalled", "Async load failed because the package is not installed."))
DECLARE_ERROR (DownloadError, 3, StreamableManager, NSLOCTEXT("StreamableManager", "DownloadError", "Failed to download"))
DECLARE_ERROR (IoStoreNotFound, 6, StreamableManager, NSLOCTEXT("StreamableManager", "IoStoreNotFound", "IoStore did not load correctly."))
DECLARE_ERROR (UnknownError, 11, StreamableManager, NSLOCTEXT("StreamableManager", "UnknownError", "Unknown error occured while streaming asset"))
DECLARE_ERROR_MODULE (StreamableManager, 0x10)
DECLARE_ERROR_ONEPARAM (AsyncLoadUnknownError, 10, StreamableManager, NSLOCTEXT("StreamableManager", "AsyncLoadUnknownError", "Unknown async loading error {AsyncLoadingErrorId}."), int32, AsyncLoadingErrorId, -1)
DECLARE_ERROR_ONEPARAM (PackageLoadCanceled, 2, StreamableManager, NSLOCTEXT("StreamableManager", "PackageLoadCancelled", "Async load canceled {PackageName}"), FString, PackageName, TEXT("Unknown"))
DECLARE_ERROR_ONEPARAM (PackageLoadFailed, 1, StreamableManager, NSLOCTEXT("StreamableManager", "PackageLoadError", "Failed to load package {PackageName}"), FString, PackageName, TEXT("Unknown"))
DECLARE_ERROR_ONEPARAM (PackageNameInvalid, 4, StreamableManager, NSLOCTEXT("StreamableManager", "PackageNameInvalid", "Found invalid package name {InvalidPackageName}"), FString, InvalidPackageName, TEXT("Unknown"))
DECLARE_ERROR_ONEPARAM (SyncLoadIncomplete, 7, StreamableManager, NSLOCTEXT("StreamableManager", "SyncLoadIncomplete", "Sync load did not complete correctly for {DebugName}."), FString, DebugName, TEXT("Unknown"))
DECLARE_ERRORSTRUCT_FEATURES (StreamableManager::FStreamableManagerAdditionalContext)
void UE::UnifiedError::StreamableManager::GatherPropertiesForError (const UE::UnifiedError::FError &Error, const UE::UnifiedError::StreamableManager::FStreamableManagerAdditionalContext &Context, UE::UnifiedError::IErrorPropertyExtractor &PropertyExtractor)
UE::UnifiedError::FError UE::UnifiedError::StreamableManager::GetStreamableError (EAsyncLoadingResult::Type Result)
void SerializeForLog (FCbWriter &Writer, const UE::UnifiedError::StreamableManager::FStreamableManagerAdditionalContext &Context)
Function Documentation
DECLARE_ERROR() [1/6]
DECLARE_ERROR (AsyncLoadCancelled , 9 , StreamableManager , NSLOCTEXT("StreamableManager", "AsyncLoadCancelled", "Async load cancelled"))
DECLARE_ERROR() [2/6]
DECLARE_ERROR (AsyncLoadFailed , 8 , StreamableManager , NSLOCTEXT("StreamableManager", "AsyncLoadFailed", "Async load failed"))
DECLARE_ERROR() [3/6]
DECLARE_ERROR (AsyncLoadNotInstalled , 12 , StreamableManager , NSLOCTEXT("StreamableManager", "AsyncLoadNotInstalled", "Async load failed because the package is not installed."))
DECLARE_ERROR() [4/6]
DECLARE_ERROR (DownloadError , 3 , StreamableManager , NSLOCTEXT("StreamableManager", "DownloadError", "Failed to download"))
DECLARE_ERROR() [5/6]
DECLARE_ERROR (IoStoreNotFound , 6 , StreamableManager , NSLOCTEXT("StreamableManager", "IoStoreNotFound", "IoStore did not load correctly."))
DECLARE_ERROR() [6/6]
DECLARE_ERROR (UnknownError , 11 , StreamableManager , NSLOCTEXT("StreamableManager", "UnknownError", "Unknown error occured while streaming asset"))
DECLARE_ERROR_MODULE()
DECLARE_ERROR_MODULE (StreamableManager , 0x10)
DECLARE_ERROR_ONEPARAM() [1/5]
DECLARE_ERROR_ONEPARAM (AsyncLoadUnknownError , 10 , StreamableManager , NSLOCTEXT("StreamableManager", "AsyncLoadUnknownError", "Unknown async loading error {AsyncLoadingErrorId}.") , int32 , AsyncLoadingErrorId , - 1)
DECLARE_ERROR_ONEPARAM() [2/5]
DECLARE_ERROR_ONEPARAM (PackageLoadCanceled , 2 , StreamableManager , NSLOCTEXT("StreamableManager", "PackageLoadCancelled", "Async load canceled {PackageName}") , FString , PackageName , TEXT("Unknown"))
References PackageName.
DECLARE_ERROR_ONEPARAM() [3/5]
DECLARE_ERROR_ONEPARAM (PackageLoadFailed , 1 , StreamableManager , NSLOCTEXT("StreamableManager", "PackageLoadError", "Failed to load package {PackageName}") , FString , PackageName , TEXT("Unknown"))
References PackageName.
DECLARE_ERROR_ONEPARAM() [4/5]
DECLARE_ERROR_ONEPARAM (PackageNameInvalid , 4 , StreamableManager , NSLOCTEXT("StreamableManager", "PackageNameInvalid", "Found invalid package name {InvalidPackageName}") , FString , InvalidPackageName , TEXT("Unknown"))
DECLARE_ERROR_ONEPARAM() [5/5]
DECLARE_ERROR_ONEPARAM (SyncLoadIncomplete , 7 , StreamableManager , NSLOCTEXT("StreamableManager", "SyncLoadIncomplete", "Sync load did not complete correctly for {DebugName}.") , FString , DebugName , TEXT("Unknown"))
DECLARE_ERRORSTRUCT_FEATURES()
DECLARE_ERRORSTRUCT_FEATURES (StreamableManager::FStreamableManagerAdditionalContext)
SerializeForLog()
void SerializeForLog (FCbWriter & Writer, const UE::UnifiedError::StreamableManager::FStreamableManagerAdditionalContext & Context) inline
Definition at line 89 of file StreamableManagerError.h.
References FCbWriter::AddString(), ANSITEXTVIEW, FCbWriter::BeginObject(), FCbWriter::EndObject(), and TEXT.