Unreal Engine 5.6 C++ API: SmartObjectTypes.h File Reference
SmartObjectTypes.h File Reference
#include "CollisionShape.h"
#include "Containers/ArrayView.h"
#include "Engine/ActorInstanceHandle.h"
#include "Engine/CollisionProfile.h"
#include "Engine/EngineTypes.h"
#include "EngineDefines.h"
#include "GameplayTagContainer.h"
#include "StructUtils/InstancedStruct.h"
#include "StructUtils/StructView.h"
#include "SmartObjectTypes.generated.h"
Data Structures
struct FSmartObjectAnnotationCollider
Struct defining a collider in world space.
struct FSmartObjectHandleFactory
Struct used as a friend to FSmartObjectHandle that is the only caller allowed to create a handle from a Guid.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::SmartObject
namespace UE::SmartObject::EnabledReason
Macros
#define UE_DEPRECATED(Version, Message)
Macro for marking up deprecated code, functions and types.
#define WITH_SMARTOBJECT_DEBUG (!(UE_BUILD_SHIPPING || UE_BUILD_SHIPPING_WITH_EDITOR) && 1)
Functions
SMARTOBJECTSMODULE_API DECLARE_LOG_CATEGORY_EXTERN (LogSmartObject, Warning, All)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSmartObjectEvent, const FSmartObjectEventData &)
Delegate called when Smart Object or Slot is changed.
UENUM() enum class ESmartObjectTagMergingPolicy UENUM() enum class ESmartObjectTagFilteringPolicy UENUM() enum class ESmartObjectSlotNavigationLocationType UENUM() enum class ESmartObjectClaimPriority USTRUCT () struct FSmartObjectUserHandle
Indicates how Tags from slots and parent object are combined to be evaluated by a TagQuery from a find request.
Variables
Deprecated
UCLASS() class USmartObjectSpacePartition This type is deprecated and no longer being used SMARTOBJECTSMODULE_API FSmartObjectSlotIndex
SMARTOBJECTSMODULE_API FGameplayTag UE::SmartObject::EnabledReason::Gameplay
Macro Definition Documentation
UE_DEPRECATED
#define UE_DEPRECATED (Version, Message)
Macro for marking up deprecated code, functions and types.
This should be used as syntactic replacement for the [[deprecated]] attribute which provides a UE version number like the old DEPRECATED macro.
Features that are marked as deprecated are scheduled to be removed from the code base in a future release. If you are using a deprecated feature in your code, you should replace it before upgrading to the next release. See the Upgrade Notes in the release notes for the release in which the feature was marked deprecated.
Sample usage (note the slightly different syntax for classes and structures):
UE_DEPRECATED(5.xx, "MyFunction has been deprecated, please use MyNewFunction instead.")
void MyFunction();
UE_DEPRECATED(5.xx, "FMyType has been deprecated, please use MyNewType instead.")
typedef FThing FMyType;
using FMyAlias UE_DEPRECATED(5.xx, "FMyAlias has been deprecated, please use MyNewAlias instead.") = FThing;
UE_DEPRECATED(5.xx, "MyVariable has been deprecated and serves no purpose anymore")
int32 MyVariable;
namespace UE_DEPRECATED(5.xx, "MyNamespace has been renamed MyNewNamespace, please use this instead.") MyNamespace
{
}
Unfortunately, clang will complain that [the] "declaration of [an] anonymous class must
be a definition" for API types.  To work around this, first forward declare the type as
deprecated, then declare the type with the visibility macro.  Note that macros like
USTRUCT must immediately precede the the type declaration, not the forward declaration.
struct UE_DEPRECATED(5.xx, "FMyStruct has been deprecated and shall not be used anymore.") FMyStruct;
USTRUCT()
struct MODULE_API FMyStruct
{
};
class UE_DEPRECATED(5.xx, "FMyClass has been deprecated and shall not be used anymore.") FMyClass;
class MODULE_API FMyClass
{
};
enum class UE_DEPRECATED(5.xx, "EMyEnumeration has been deprecated, use EMyEnumeration instead.") EMyEnumeration
{
    Zero = 0,
    One UE_DEPRECATED(5.xx, "EMyEnumeration::One is not a valid enum entry anymore, please use another one.") = 1,
    Two = 2
};
Unfortunately, VC++ will complain about using member functions and fields from deprecated
class/structs even for class/struct implementation e.g.:
class UE_DEPRECATED(5.xx, "DeprecatedClass has been deprecated and shall not be used anymore.") DeprecatedClass
{
public:
    DeprecatedClass() {}
    float GetMyFloat()
    {
        return MyFloat; // This line will cause warning that deprecated field is used.
    }
private:
    float MyFloat;
};
To get rid of this warning, place all code not called in class implementation in non-deprecated
base class and deprecate only derived one. This may force you to change some access specifiers
from private to protected, e.g.:
class DeprecatedClass_Base_DEPRECATED
{
protected: // MyFloat is protected now, so DeprecatedClass has access to it.
    float MyFloat;
};
class UE_DEPRECATED(5.xx, "DeprecatedClass has been deprecated and shall not be used anymore.") DeprecatedClass : DeprecatedClass_Base_DEPRECATED
{
public:
    DeprecatedClass() {}
    float GetMyFloat()
    {
        return MyFloat;
    }
};
template <typename T>
class UE_DEPRECATED(5.xx, "DeprecatedClassTemplate has been deprecated and shall not be used anymore.") DeprecatedClassTemplate
{
};
template <typename T>
UE_DEPRECATED(5.xx, "DeprecatedFunctionTemplate has been deprecated and shall not be used anymore.")
void DeprecatedFunctionTemplate()
{
}
Parameters
Version The release number in which the feature was marked deprecated. Note: 'all', as in UE_DEPRECATED(all, ...), can be used for reflected code which has to stick around forever and is marked with meta-data like DeprecatedFunction or DeprecatedProperty. It indicates that the deprecation grace period is now over but that this property/function will remain deprecated for all time.
Message A message containing upgrade notes.
Definition at line 299 of file CoreMiscDefines.h.
WITH_SMARTOBJECT_DEBUG
#define WITH_SMARTOBJECT_DEBUG (!(UE_BUILD_SHIPPING || UE_BUILD_SHIPPING_WITH_EDITOR) && 1)
Definition at line 25 of file SmartObjectTypes.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
SMARTOBJECTSMODULE_API DECLARE_LOG_CATEGORY_EXTERN (LogSmartObject , Warning , All)
References All, and Warning.
DECLARE_MULTICAST_DELEGATE_OneParam()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSmartObjectEvent , const FSmartObjectEventData &)
Delegate called when Smart Object or Slot is changed.
USTRUCT()
UENUM() enum class ESmartObjectTagMergingPolicy UENUM() enum class ESmartObjectTagFilteringPolicy UENUM() enum class ESmartObjectSlotNavigationLocationType UENUM() enum class ESmartObjectClaimPriority USTRUCT ()
Indicates how Tags from slots and parent object are combined to be evaluated by a TagQuery from a find request.
Used internally by USmartObjectDefinition to refer to a specific piece of data like the definition itself, its parameters struct, slot data, etc.
Struct that can be used to pass data related to the owner of a created SmartObject.
Struct that can be used to pass data to the find or filtering methods.
Class used to define settings for Smart Object navigation and collision validation.
Parameters for Smart Object navigation and collision validation.
Struct defining Smart Object user capsule size.
Indicates how TagQueries from slots and parent object will be processed against Tags from a find request.
Reference to a specific Smart Object slot in a Smart Object Definition.
Base class for space partitioning structure that can be used to store smart object locations.
This is the base struct to inherit from to store some data associated to a specific entry in the spatial representation structure.
This is the base struct to inherit from to store custom state data associated to a slot.
This is the base struct to inherit from to store custom definition data within the main slot definition.
Struct used to identify a runtime slot instance.
Handle to a registered smartobject.
Indicates how TagQueries from slots and parent object will be processed against Tags from a find request. Enum indicating if we're looking for a location to enter or exit the Smart Object slot. Enum indicating the claim priority of a Smart Object slot. Handle to a smartobject user.
Helper struct to wrap basic functionalities to store the index of a slot in a SmartObject definition
When placed on a slot definition data, the Index is resolved automatically when changed, on load and save.
Struct used to define how traces should be handled.
It is possible to specify two set of validation parameters. The one labeled "entry" is used for validating entry locations and other general collision validation. A separate set can be defined for checking exit locations. This allows the exit location checking to be relaxed. E.g. we might not allow to enter the SO on water area, but it is fine to exit on water. The values of the CDO are used, the users are expected to derive from this class to create custom settings. Describes how Smart Object or slot was changed. Struct describing a change in Smart Object or Slot.
Properties will be used as user data to fill values expected by the world condition schema specified by the smart object definition. e.g. FilterSlotsBySelectionConditions(SlotHandles, FConstStructView::Make(FSmartObjectActorUserData(Pawn)));
It can be inherited from to provide additional data to another world condition schema inheriting from USmartObjectWorldConditionSchema. e.g. UCLASS() class USmartObjectWorldConditionExtendedSchema : public USmartObjectWorldConditionSchema { ... USmartObjectWorldConditionExtendedSchema(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { OtherActorRef = AddContextDataDesc(TEXT("OtherActor"), AActor::StaticClass(), EWorldConditionContextDataType::Dynamic); }
FWorldConditionContextDataRef OtherActorRef; };
USTRUCT() struct FSmartObjectActorExtendedUserData : public FSmartObjectActorUserData { UPROPERTY() TWeakObjectPtr<const AActor> OtherActor = nullptr; }
The struct can also be used to be added to a Smart Object slot when it gets claimed. e.g. Claim(SlotHandle, FConstStructView::Make(FSmartObjectActorUserData(Pawn)));
It identifies an instanced actor that could be in its lightweight representation or a normal actor.
Valid Id must be created by the subsystem
Indicates that the handle was properly assigned but doesn't guarantee that the associated object is still accessible. This information requires a call to USmartObjectSubsystem::IsObjectValid using the handle.
Has meaning only for sorting purposes (can't use default version since it is not available in FGuid)
Valid Id must be created by the collection
Indicates that the handle was properly assigned but doesn't guarantee that the associated slot is still accessible. This information requires a call to USmartObjectSubsystem::IsSlotValid using the handle.
Has meaning only for sorting purposes
Do not expose the EntityHandle anywhere else than SlotView or the Subsystem.
Type of trace to use.
Trace channel to use to determine collisions.
Object types to use to determine collisions.
Collision profile to use to determine collisions.
Whether we should trace against complex collision
Invalid capsule.
Returns the capsule as an annotation collider at specified world location and rotation. The capsule is placed so that Z-axis of the rotation is considered up. The values specified in the struct will be constrained to create valid collider (and thus can differ from the set values).
Parameters
Location Location of the collider.
Rotation Rotation of the collider.
Returns
annotation collider representing the capsule.
Radius of the capsule
Full height of the capsule
Step up height. This space is ignored when testing collisions.
Returns
navigation filter class to be used for navigation checks.
search extents used to define how far the validation can move the points.
trace parameters for finding ground location.
trace parameters for testing if there are collision transitioning from navigation location to slot location.
reference to user capsule parameters.
Selects between specified NavigationCapsule size and capsule size defined in the params based on bUseNavigationCapsuleSize.
Parameters
NavigationCapsule Size of the navigation capsule.
Returns
reference to selected capsule.
Gets user capsule for a specified actor, if bUseNavigationCapsuleSize is specified uses INavAgentInterface to forward the values from navigation system. The method can fail if the navigation capsule is requested, but we fail to get the navigation properties from the actor.
Parameters
UserActor Actor used to look up navigation settings from.
OutCapsule Dimensions of the user capsule.
Returns
true operation succeeds.
Gets default user capsule size used for preview when the user actor is now known. The method can fail if the navigation capsule is requested, but we fail to get the navigation properties from the world.
Parameters
World where to look for default navigation settings.
OutCapsule Dimensions of the user capsule.
Returns
true if operation succeeds.
Navigation filter used to validate entrance locations.
How far we allow the validated location to be from the specified navigation location.
Trace parameters used for finding navigation location on ground.
Trace parameters user for checking if the transition between navigation location and slot is unblocked.
If true, the capsule size is queried from the user actor via INavAgentInterface.
Dimensions of the capsule used for testing if user can fit into a specific location. If bUseNavigationCapsuleSize is set, the capsule size from the Actor navigation settings is used if the actor is present (otherwise we fallback to the UserCapsule).
Handle to the changed Smart Object.
Handle to the changed slot, if invalid, the event is for the object.
Change reason.
Added/Removed tag, or event tag, depending on Reason.
Event payload. For external event (i.e. SendSlotEvent) payload is provided by the caller. For internal event types (e.g. OnClaimed, OnReleased, etc.) payload is the user data struct provided on claim.
Definition at line 100 of file SmartObjectTypes.h.
References Category, GENERATED_BODY, ID, INDEX_NONE, Invalid, IsValid(), LexToString(), operator!=(), operator==(), Other, and UPROPERTY.
Variable Documentation
Deprecated
Deprecated
Definition at line 91 of file RigVMFunction_Noise.h.
FSmartObjectSlotIndex
UCLASS() class USmartObjectSpacePartition This type is deprecated and no longer being used SMARTOBJECTSMODULE_API FSmartObjectSlotIndex
Definition at line 360 of file SmartObjectTypes.h.