Unreal Engine 5.6 C++ API: FArchiveSavePackageDataBuffer Struct Reference
FArchiveSavePackageDataBuffer Struct Reference
This is the structure that should be used by most callers of an archive (other than SavePackage which handles the full complexity) that need to provide SavePackage or Cook information to the archive.
#include "ArchiveSavePackageDataBuffer.h"
Public Member Functions
FArchiveSavePackageDataBuffer (const ITargetPlatform *InTargetPlatform=nullptr, UPackage *Package=nullptr, UE::Cook::ICookInfo *CookInfo=nullptr)
FArchiveSavePackageDataBuffer (FArchiveCookContext InContext)
FArchiveSavePackageDataBuffer (FObjectSaveContextData &InData, UPackage *InPackage=nullptr)
Public Member Functions inherited from FArchiveSavePackageData
FArchiveSavePackageData (FObjectSavePackageSerializeContext &InSavePackageContext, const ITargetPlatform *InTargetPlatform, FArchiveCookContext *InCookContext)
Data Fields
FArchiveCookContext CookContextBuffer
TOptional< FObjectSaveContextData > ObjectSaveContextData
FObjectSavePackageSerializeContext ObjectSavePackageSerializeContextBuffer
Data Fields inherited from FArchiveSavePackageData
FArchiveCookContext * CookContext = nullptr
Non-null if a cook save.
FObjectSavePackageSerializeContext & SavePackageContext
const ITargetPlatform * TargetPlatform = nullptr
Non-null if a cook save.
Private Member Functions
void SetConstructorTargetPlatform (const ITargetPlatform *InTargetPlatform)
Detailed Description
This is the structure that should be used by most callers of an archive (other than SavePackage which handles the full complexity) that need to provide SavePackage or Cook information to the archive.
FArchiveSavePackageData is a minimalist struct that holds pointers to types it cannot have defined, because they are defined in modules higher in the dependency graph. Because of that minimalism, it needs pointers to several pieces of related data. Collect all of those pieces of related data in this module that knows all of the types, and keep them in a single amalgamated structure the sets the base class pointers to the appropriate internal structures.
Definition at line 22 of file ArchiveSavePackageDataBuffer.h.
Constructor & Destructor Documentation
FArchiveSavePackageDataBuffer() [1/3]
FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer (const ITargetPlatform * InTargetPlatform = nullptr, UPackage * Package = nullptr, UE::Cook::ICookInfo * CookInfo = nullptr) inline
Definition at line 25 of file ArchiveSavePackageDataBuffer.h.
References FArchiveSavePackageData::FArchiveSavePackageData(), CookContextBuffer, ObjectSaveContextData, ObjectSavePackageSerializeContextBuffer, Package, SetConstructorTargetPlatform(), and Unknown.
FArchiveSavePackageDataBuffer() [2/3]
FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer (FArchiveCookContext InContext) inline
Definition at line 38 of file ArchiveSavePackageDataBuffer.h.
References FArchiveSavePackageData::FArchiveSavePackageData(), CookContextBuffer, FArchiveCookContext::GetTargetPlatform(), MoveTemp(), ObjectSaveContextData, ObjectSavePackageSerializeContextBuffer, and SetConstructorTargetPlatform().
FArchiveSavePackageDataBuffer() [3/3]
FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer (FObjectSaveContextData & InData, UPackage * InPackage = nullptr) inline
Definition at line 47 of file ArchiveSavePackageDataBuffer.h.
References FArchiveSavePackageData::FArchiveSavePackageData(), CookContextBuffer, ObjectSavePackageSerializeContextBuffer, SetConstructorTargetPlatform(), and FArchiveSavePackageData::TargetPlatform.
Member Function Documentation
SetConstructorTargetPlatform()
void FArchiveSavePackageDataBuffer::SetConstructorTargetPlatform (const ITargetPlatform * InTargetPlatform) inline private
Definition at line 60 of file ArchiveSavePackageDataBuffer.h.
References FArchiveSavePackageData::CookContext, CookContextBuffer, and FArchiveSavePackageData::TargetPlatform.
Referenced by FArchiveSavePackageDataBuffer(), FArchiveSavePackageDataBuffer(), and FArchiveSavePackageDataBuffer().
Field Documentation
CookContextBuffer
FArchiveCookContext FArchiveSavePackageDataBuffer::CookContextBuffer
Definition at line 57 of file ArchiveSavePackageDataBuffer.h.
Referenced by FArchiveSavePackageDataBuffer(), FArchiveSavePackageDataBuffer(), FArchiveSavePackageDataBuffer(), and SetConstructorTargetPlatform().
ObjectSaveContextData
TOptional<FObjectSaveContextData> FArchiveSavePackageDataBuffer::ObjectSaveContextData
Definition at line 55 of file ArchiveSavePackageDataBuffer.h.
Referenced by FArchiveSavePackageDataBuffer(), and FArchiveSavePackageDataBuffer().
ObjectSavePackageSerializeContextBuffer
FObjectSavePackageSerializeContext FArchiveSavePackageDataBuffer::ObjectSavePackageSerializeContextBuffer
Definition at line 56 of file ArchiveSavePackageDataBuffer.h.
Referenced by FArchiveSavePackageDataBuffer(), FArchiveSavePackageDataBuffer(), and FArchiveSavePackageDataBuffer().
The documentation for this struct was generated from the following file:
ArchiveSavePackageDataBuffer.h