Unreal Engine 5.6 C++ API: Engine.h File Reference
Engine.h File Reference
#include "CoreMinimal.h"
#include "Containers/IndirectArray.h"
#include "UObject/PrintStaleReferencesOptions.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Misc/Guid.h"
#include "Templates/SubclassOf.h"
#include "Engine/EngineTypes.h"
#include "Engine/EngineBaseTypes.h"
#include "UObject/SoftObjectPath.h"
#include "Engine/World.h"
#include "Misc/FrameRate.h"
#include "Subsystems/SubsystemCollection.h"
#include "Subsystems/EngineSubsystem.h"
#include "RHIDefinitions.h"
#include "Templates/PimplPtr.h"
#include "Templates/UniqueObj.h"
#include "Containers/Ticker.h"
#include "DynamicRenderScaling.h"
#include "Misc/StatusLog.h"
#include "Engine.generated.h"
Data Structures
struct FDynamicResolutionStateInfos
Information about the state of dynamic resolution.
Macros
#define WITH_DYNAMIC_RESOLUTION (!UE_SERVER)
Enumerations
enum class EDynamicResolutionStatus {
Unsupported , Disabled , Paused , Enabled ,
DebugForceEnabled
}
Enumerates types of fully loaded packages.
enum class EGarbageCollectionType { None , Incremental , Full }
Type of UObject purge type to be performed by the engine.
enum class EGetWorldErrorMode { ReturnNull , LogAndReturnNull , Assert }
Functions
DECLARE_DELEGATE (FEndStreamingPauseDelegate)
DECLARE_DELEGATE_OneParam (FBeginStreamingPauseDelegate, FViewport *)
DECLARE_DELEGATE_RetVal_ThreeParams (EBrowseReturnVal::Type, FBrowseURL, FWorldContext &WorldContext, FURL URL, FString &Error)
DECLARE_DELEGATE_TwoParams (FPendingLevelUpdate, FWorldContext &Context, float DeltaSeconds)
DECLARE_MULTICAST_DELEGATE (FPostRenderDelegate)
DECLARE_MULTICAST_DELEGATE (FPreRenderDelegate)
DECLARE_MULTICAST_DELEGATE_OneParam (FPostRenderDelegateEx, class FRDGBuilder &)
DECLARE_MULTICAST_DELEGATE_OneParam (FPreRenderDelegateEx, class FRDGBuilder &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FEngineHitchDetectedDelegate, EFrameHitchType, float)
USTRUCT () struct FFullyLoadedPackagesInfo
Struct to help hold information about packages needing to be fully-loaded for DLC, etc.
Variables
UCLASS() class UEngine class UEngine * GEngine
Abstract base class of all Engine classes, responsible for management of systems critical to editor or game systems.
Macro Definition Documentation
WITH_DYNAMIC_RESOLUTION
#define WITH_DYNAMIC_RESOLUTION (!UE_SERVER)
Definition at line 27 of file Classes/Engine/Engine.h.
Enumeration Type Documentation
EDynamicResolutionStatus
enum class EDynamicResolutionStatus strong
Enumerates types of fully loaded packages.
Enumerates transition types. Status of dynamic resolution that depends on project setting cvar, game user settings, and pause
Enumerator
Unsupported
Disabled
Paused
Enabled
DebugForceEnabled
Definition at line 111 of file Classes/Engine/Engine.h.
EGarbageCollectionType
enum class EGarbageCollectionType strong
Type of UObject purge type to be performed by the engine.
Enumerator
None
Incremental
Full
Definition at line 696 of file Classes/Engine/Engine.h.
EGetWorldErrorMode
enum class EGetWorldErrorMode strong
Enumerator
ReturnNull
LogAndReturnNull
Assert
Definition at line 62 of file Classes/Engine/Engine.h.
Function Documentation
DECLARE_DELEGATE()
DECLARE_DELEGATE (FEndStreamingPauseDelegate)
References DECLARE_DELEGATE.
DECLARE_DELEGATE_OneParam()
DECLARE_DELEGATE_OneParam (FBeginStreamingPauseDelegate , FViewport *)
References DECLARE_DELEGATE_OneParam.
DECLARE_DELEGATE_RetVal_ThreeParams()
DECLARE_DELEGATE_RetVal_ThreeParams (EBrowseReturnVal::Type , FBrowseURL , FWorldContext & WorldContext, FURL URL, FString & Error)
References DECLARE_DELEGATE_RetVal_ThreeParams, and Error.
DECLARE_DELEGATE_TwoParams()
DECLARE_DELEGATE_TwoParams (FPendingLevelUpdate , FWorldContext & Context, float DeltaSeconds)
References DECLARE_DELEGATE_TwoParams.
DECLARE_MULTICAST_DELEGATE() [1/2]
DECLARE_MULTICAST_DELEGATE (FPostRenderDelegate)
References DECLARE_MULTICAST_DELEGATE.
DECLARE_MULTICAST_DELEGATE() [2/2]
DECLARE_MULTICAST_DELEGATE (FPreRenderDelegate)
References DECLARE_MULTICAST_DELEGATE.
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
DECLARE_MULTICAST_DELEGATE_OneParam (FPostRenderDelegateEx , class FRDGBuilder &)
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
DECLARE_MULTICAST_DELEGATE_OneParam (FPreRenderDelegateEx , class FRDGBuilder &)
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_TwoParams()
DECLARE_MULTICAST_DELEGATE_TwoParams (FEngineHitchDetectedDelegate , EFrameHitchType , float)
References DECLARE_MULTICAST_DELEGATE_TwoParams.
USTRUCT()
USTRUCT ()
Struct to help hold information about packages needing to be fully-loaded for DLC, etc.
On-screen debug message handling.
Info about one note dropped in the map during PIE.
FWorldContext A context for dealing with UWorlds at the engine level.
Active and named net drivers instantiated from an FNetDriverDefinition The net driver will remain instantiated on this struct until it is destroyed.
Struct used to configure which NetDriver is started with Iris enabled or not Only one attribute out of the NetDriverDefinition, NetDriverName or NetDriverWildcardName should be set along with the bEnableIris property.
Container for describing various types of netdrivers available to the engine The engine will try to construct a netdriver of a given type and, failing that, the fallback version.
level streaming updates that should be applied immediately after committing the map change
As the engine brings up and destroys world, we need a way to keep straight what world belongs to what.
WorldContexts can be thought of as a track. By default we have 1 track that we load and unload levels on. Adding a second context is adding a second track; another track of progression for worlds to live on.
For the GameEngine, there will be one WorldContext until we decide to support multiple simultaneous worlds. For the EditorEngine, there may be one WorldContext for the EditorWorld and one for the PIE World.
FWorldContext provides both a way to manage 'the current PIE UWorld*' as well as state that goes along with connecting/travelling to new worlds.
FWorldContext should remain internal to the UEngine classes. Outside code should not keep pointers or try to manage FWorldContexts directly. Outside code can still deal with UWorld*, and pass UWorld*s into Engine level functions. The Engine code can look up the relevant context for a given UWorld*.
For convenience, FWorldContext can maintain outside pointers to UWorld*s. For example, PIE can tie UWorld* UEditorEngine::PlayWorld to the PIE world context. If the PIE UWorld changes, the UEditorEngine::PlayWorld pointer will be automatically updated. This is done with AddRef() and SetCurrentWorld().
Helper struct for tracking on screen messages.
When to load these packages
When this map or gametype is loaded, the packages in the following array will be loaded and added to root, then removed from root when map is unloaded
The list of packages that will be fully loaded when the above Map is loaded
List of objects that were loaded, for faster cleanup
Constructors
Unique name of this net driver definition
Class name of primary net driver
Class name of the fallback net driver if the main net driver class fails to initialize
Name of the net driver definition to configure e.g. GameNetDriver, BeaconNetDriver, etc.
Name of the named driver to configure. e.g. GameNetDriver, DemoNetDriver, etc.
Wildcard match the netdriver name to configure e.g. NetDriverWildcardName="UnitTestNetDriver*" matches with UnitTestNetDriver_1, UnitTestNetDriver_2, etc.
Configurable property that decides if the NetDriver will use the Iris replication system or not if Iris is enabled
Instantiation of named net driver
Definition associated with this net driver
URL to travel to for pending client connect
TravelType for pending client connects
URL the last time we traveled
last server we connected to (for "reconnect" command)
A list of tag/array pairs that is used at LoadMap time to fully load packages that may be needed for the map/game with DLC, but we can't use DynamicLoadObject to load from the packages
Array of package/ level names that need to be loaded for the pending map change. First level in that array is going to be made a fake persistent one by using ULevelStreamingPersistent.
Array of already loaded levels. The ordering is arbitrary and depends on what is already loaded and such.
Human readable error string for any failure during a map change request. Empty if there were no failures.
If true, commit map change the next frame.
Handles to object references; used by the engine to e.g. the prevent objects from being garbage collected.
A list of active net drivers
The PIE instance of this world, -1 is default
The Prefix in front of PIE level names, empty is default
The feature level that PIE world should use
Is this running as a dedicated server
Is this world context waiting for an online login to complete (for PIE)
Is this the 'primary' PIE instance. Primary is preferred when, for example, unique hardware like a VR headset can be used by only one PIE instance.
Handle to this world context's audio device.
Custom description to be display in blueprint debugger UI
On a transition to another level (e.g. LoadMap), the engine will verify that these objects have been cleaned up by garbage collection
Outside pointers to CurrentWorld that should be kept in sync if current world changes
Adds an external reference
Removes an external reference
Set CurrentWorld and update external reference pointers to reflect this
Collect FWorldContext references for garbage collection
Location to create Note actor in edited level.
Rotation to create Note actor in edited level.
Text to assign to Note actor in edited level.
The 'key' for this message.
The message to display.
The color to display the message in.
The number of frames to display it.
The number of frames it has been displayed so far.
Scale of text
Definition at line 146 of file Classes/Engine/Engine.h.
References GENERATED_USTRUCT_BODY, and UPROPERTY.
Variable Documentation
GEngine
UCLASS () class UEngine class UEngine* GEngine () extern
Abstract base class of all Engine classes, responsible for management of systems critical to editor or game systems.
Also defines default classes for certain engine systems. Global engine pointer. Can be 0 so don't use without checking.
Referenced by UE::FChangeTransactor::CanTransactChanges(), UE::FChangeTransactor::CloseTransaction(), FSceneViewExtensionContext::IsStereoSupported(), UE::FChangeTransactor::OpenTransaction(), and FDisplayClusterActorRef::UpdateWorldPtr().