Unreal Engine 5.6 C++ API: TDeque< InElementType, InAllocatorType > Class Template Reference
TDeque< InElementType, InAllocatorType > Class Template Reference
Sequential double-ended queue (deque) container class.
#include "Deque.h"
Public Types
using AllocatorType = InAllocatorType
using ConstIteratorType = UE::Deque::Private::TIterator<const ElementType, SizeType>
using ElementAllocatorType
using ElementType = InElementType
using IteratorType = UE::Deque::Private::TIterator<ElementType, SizeType>
using SizeType = typename InAllocatorType::SizeType
Public Member Functions
TDeque ()
TDeque (const TDeque &Other)
TDeque (std::initializer_list< ElementType > InList)
TDeque (TDeque &&Other)
~TDeque ()
FORCEINLINE IteratorType begin ()
FORCEINLINE ConstIteratorType begin () const
template<typename... ArgsType>
ElementType & EmplaceFirst (ArgsType &&... Args)
template<typename... ArgsType>
ElementType & EmplaceLast (ArgsType &&... Args)
void Empty ()
FORCEINLINE IteratorType end ()
FORCEINLINE ConstIteratorType end () const
FORCEINLINE ElementType & First ()
FORCEINLINE const ElementType & First () const
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container.
FORCEINLINE bool IsEmpty () const
FORCEINLINE ElementType & Last ()
FORCEINLINE const ElementType & Last () const
FORCEINLINE SizeType Max () const
FORCEINLINE SizeType Num () const
bool operator!= (const TDeque &Right) const
TDeque & operator= (const TDeque &Other)
TDeque & operator= (std::initializer_list< ElementType > InList)
TDeque & operator= (TDeque &&Other)
bool operator== (const TDeque &Right) const
FORCEINLINE ElementType & operator[] (SizeType Index)
FORCEINLINE const ElementType & operator[] (SizeType Index) const
void PopFirst ()
void PopLast ()
FORCEINLINE void PushFirst (const ElementType &Element)
FORCEINLINE void PushFirst (ElementType &&Element)
FORCEINLINE void PushLast (const ElementType &Element)
FORCEINLINE void PushLast (ElementType &&Element)
void Reserve (SizeType InCount)
void Reset ()
bool TryPopFirst (ElementType &OutValue)
bool TryPopLast (ElementType &OutValue)
Private Member Functions
FORCEINLINE void CheckValidIndex (SizeType Index) const
void CopyElements (const TDeque &Other)
void CopyUnchecked (const TDeque &Other)
void CopyUnchecked (std::initializer_list< ElementType > InList)
FORCEINLINE ElementType * GetData ()
FORCEINLINE const ElementType * GetData () const
FORCEINLINE IteratorType GetIterator (SizeType HeadOffset)
FORCEINLINE ConstIteratorType GetIterator (SizeType HeadOffset) const
void Grow (SizeType InCapacity)
Grows the container's storage to the parameter capacity value.
void GrowIfRequired ()
Grows the container to the next capacity value (determined by the storage allocator) if full.
void Linearize ()
Shifts the contained range to the beginning of the storage so it's linear.
void MoveUnchecked (TDeque &&Other)
void ShiftElementsLeft (SizeType InCount)
Moves the parameter number of elements to the left shifting the head to the beginning of the storage.
Private Attributes
SizeType Capacity = 0
SizeType Count = 0
SizeType Head = 0
ElementAllocatorType Storage
SizeType Tail = 0
Friends
template<typename AnyElementType, typename AnyAllocatorType>
class TDeque
Detailed Description
template<typename InElementType, typename InAllocatorType>
class TDeque< InElementType, InAllocatorType >
Sequential double-ended queue (deque) container class.
A dynamically sized sequential queue of arbitrary size.
Definition at line 88 of file Deque.h.
Member Typedef Documentation
AllocatorType
template<typename InElementType, typename InAllocatorType> using TDeque< InElementType, InAllocatorType >::AllocatorType = InAllocatorType
Definition at line 94 of file Deque.h.
ConstIteratorType
template<typename InElementType, typename InAllocatorType> using TDeque< InElementType, InAllocatorType >::ConstIteratorType = UE::Deque::Private::TIterator<const ElementType, SizeType>
Definition at line 103 of file Deque.h.
ElementAllocatorType
template<typename InElementType, typename InAllocatorType> using TDeque< InElementType, InAllocatorType >::ElementAllocatorType
Initial value:
 std::conditional_t<
        AllocatorType::NeedsElementType,
        typename AllocatorType::template ForElementType<ElementType>,
        typename AllocatorType::ForAnyElementType>
Definition at line 98 of file Deque.h.
ElementType
template<typename InElementType, typename InAllocatorType> using TDeque< InElementType, InAllocatorType >::ElementType = InElementType
Definition at line 96 of file Deque.h.
IteratorType
template<typename InElementType, typename InAllocatorType> using TDeque< InElementType, InAllocatorType >::IteratorType = UE::Deque::Private::TIterator<ElementType, SizeType>
Definition at line 104 of file Deque.h.
SizeType
template<typename InElementType, typename InAllocatorType> using TDeque< InElementType, InAllocatorType >::SizeType = typename InAllocatorType::SizeType
Definition at line 95 of file Deque.h.
Constructor & Destructor Documentation
TDeque() [1/4]
template<typename InElementType, typename InAllocatorType> TDeque< InElementType, InAllocatorType >::TDeque () inline nodiscard
Definition at line 106 of file Deque.h.
References Capacity, and Storage.
TDeque() [2/4]
template<typename InElementType, typename InAllocatorType> TDeque< InElementType, InAllocatorType >::TDeque (TDeque< InElementType, InAllocatorType > && Other) inline nodiscard
Definition at line 110 of file Deque.h.
References TDeque, MoveTemp(), MoveUnchecked(), and Other.
TDeque() [3/4]
template<typename InElementType, typename InAllocatorType> TDeque< InElementType, InAllocatorType >::TDeque (const TDeque< InElementType, InAllocatorType > & Other) inline nodiscard
Definition at line 115 of file Deque.h.
References TDeque, Capacity, CopyUnchecked(), Other, and Storage.
TDeque() [4/4]
template<typename InElementType, typename InAllocatorType> TDeque< InElementType, InAllocatorType >::TDeque (std::initializer_list< ElementType > InList) inline nodiscard
Definition at line 121 of file Deque.h.
References Capacity, CopyUnchecked(), and Storage.
~TDeque()
template<typename InElementType, typename InAllocatorType> TDeque< InElementType, InAllocatorType >::~TDeque () inline
Definition at line 127 of file Deque.h.
References Empty().
Member Function Documentation
begin() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE IteratorType TDeque< InElementType, InAllocatorType >::begin () inline nodiscard
Definition at line 388 of file Deque.h.
References FORCEINLINE, GetIterator(), and Head.
begin() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE ConstIteratorType TDeque< InElementType, InAllocatorType >::begin () const inline nodiscard
Definition at line 384 of file Deque.h.
References FORCEINLINE, GetIterator(), and Head.
Referenced by operator==().
CheckValidIndex()
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TDeque< InElementType, InAllocatorType >::CheckValidIndex (SizeType Index) const inline private
Definition at line 576 of file Deque.h.
References Capacity, checkf, checkSlow, Count, FORCEINLINE, and TEXT.
Referenced by First(), First(), Last(), Last(), operator[](), operator[](), PopFirst(), and PopLast().
CopyElements()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::CopyElements (const TDeque< InElementType, InAllocatorType > & Other) inline private
Definition at line 519 of file Deque.h.
References TDeque, Capacity, ConstructItems(), Count, GetData(), Head, Other, Tail, and UE::Deque::Private::WrapAround().
Referenced by CopyUnchecked().
CopyUnchecked() [1/2]
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::CopyUnchecked (const TDeque< InElementType, InAllocatorType > & Other) inline private
Definition at line 461 of file Deque.h.
References TDeque, Capacity, checkSlow, CopyElements(), Count, Other, and Reserve().
Referenced by TDeque(), TDeque(), operator=(), and operator=().
CopyUnchecked() [2/2]
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::CopyUnchecked (std::initializer_list< ElementType > InList) inline private
Definition at line 476 of file Deque.h.
References Capacity, checkSlow, ConstructItems(), Count, GetData(), Reserve(), Storage, and Tail.
EmplaceFirst()
template<typename InElementType, typename InAllocatorType> template<typename... ArgsType> ElementType & TDeque< InElementType, InAllocatorType >::EmplaceFirst (ArgsType &&... Args) inline
Definition at line 241 of file Deque.h.
References Capacity, Count, Forward(), GetData(), GrowIfRequired(), Head, Target, and UE::Deque::Private::WrapAround().
Referenced by PushFirst(), and PushFirst().
EmplaceLast()
template<typename InElementType, typename InAllocatorType> template<typename... ArgsType> ElementType & TDeque< InElementType, InAllocatorType >::EmplaceLast (ArgsType &&... Args) inline
Definition at line 226 of file Deque.h.
References Capacity, Count, Forward(), GetData(), GrowIfRequired(), Tail, Target, and UE::Deque::Private::WrapAround().
Referenced by PushLast(), and PushLast().
Empty()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::Empty () inline
Definition at line 360 of file Deque.h.
References Capacity, Reset(), and Storage.
Referenced by ~TDeque().
end() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE IteratorType TDeque< InElementType, InAllocatorType >::end () inline nodiscard
Definition at line 396 of file Deque.h.
References Count, FORCEINLINE, GetIterator(), and Head.
end() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE ConstIteratorType TDeque< InElementType, InAllocatorType >::end () const inline nodiscard
Definition at line 392 of file Deque.h.
References Count, FORCEINLINE, GetIterator(), and Head.
Referenced by operator==().
First() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE ElementType & TDeque< InElementType, InAllocatorType >::First () inline nodiscard
Definition at line 189 of file Deque.h.
References CheckValidIndex(), FORCEINLINE, GetData(), and Head.
First() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE const ElementType & TDeque< InElementType, InAllocatorType >::First () const inline nodiscard
Definition at line 183 of file Deque.h.
References CheckValidIndex(), FORCEINLINE, GetData(), and Head.
GetAllocatedSize()
template<typename InElementType, typename InAllocatorType> FORCEINLINE SIZE_T TDeque< InElementType, InAllocatorType >::GetAllocatedSize () const inline nodiscard
Helper function to return the amount of memory allocated by this container.
Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
Number of bytes allocated by this container.
Definition at line 216 of file Deque.h.
References Capacity, FORCEINLINE, and Storage.
GetData() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE ElementType * TDeque< InElementType, InAllocatorType >::GetData () inline nodiscard private
Definition at line 413 of file Deque.h.
References FORCEINLINE, and Storage.
GetData() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE const ElementType * TDeque< InElementType, InAllocatorType >::GetData () const inline nodiscard private
Definition at line 408 of file Deque.h.
References FORCEINLINE, and Storage.
Referenced by CopyElements(), CopyUnchecked(), EmplaceFirst(), EmplaceLast(), First(), First(), GetIterator(), GetIterator(), Last(), Last(), Linearize(), operator[](), operator[](), PopFirst(), PopLast(), Reset(), ShiftElementsLeft(), TryPopFirst(), and TryPopLast().
GetIterator() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE IteratorType TDeque< InElementType, InAllocatorType >::GetIterator (SizeType HeadOffset) inline nodiscard private
Definition at line 423 of file Deque.h.
References FORCEINLINE, GetData(), InPlace, and Max().
GetIterator() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE ConstIteratorType TDeque< InElementType, InAllocatorType >::GetIterator (SizeType HeadOffset) const inline nodiscard private
Definition at line 418 of file Deque.h.
References FORCEINLINE, GetData(), InPlace, and Max().
Referenced by begin(), begin(), end(), and end().
Grow()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::Grow (SizeType InCapacity) inline private
Grows the container's storage to the parameter capacity value.
This method preserves existing data.
Definition at line 432 of file Deque.h.
References Capacity, checkSlow, Count, Head, Linearize(), Storage, and Tail.
Referenced by GrowIfRequired(), and Reserve().
GrowIfRequired()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::GrowIfRequired () inline private
Grows the container to the next capacity value (determined by the storage allocator) if full.
This method preserves existing data.
Definition at line 449 of file Deque.h.
References Capacity, Count, Grow(), and Storage.
Referenced by EmplaceFirst(), and EmplaceLast().
IsEmpty()
template<typename InElementType, typename InAllocatorType> FORCEINLINE bool TDeque< InElementType, InAllocatorType >::IsEmpty () const inline nodiscard
Definition at line 195 of file Deque.h.
References Count, and FORCEINLINE.
Referenced by TryPopFirst(), and TryPopLast().
Last() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE ElementType & TDeque< InElementType, InAllocatorType >::Last () inline nodiscard
Definition at line 177 of file Deque.h.
References Capacity, CheckValidIndex(), FORCEINLINE, GetData(), Tail, and UE::Deque::Private::WrapAround().
Last() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE const ElementType & TDeque< InElementType, InAllocatorType >::Last () const inline nodiscard
Definition at line 171 of file Deque.h.
References Capacity, CheckValidIndex(), FORCEINLINE, GetData(), Tail, and UE::Deque::Private::WrapAround().
Linearize()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::Linearize () inline private
Shifts the contained range to the beginning of the storage so it's linear.
This method is faster than a full range rotation but requires a temporary extra storage whenever the tail is wrapped around.
Definition at line 541 of file Deque.h.
References Capacity, Count, GetData(), Head, RelocateConstructItems(), ShiftElementsLeft(), and Tail.
Referenced by Grow().
Max()
template<typename InElementType, typename InAllocatorType> FORCEINLINE SizeType TDeque< InElementType, InAllocatorType >::Max () const inline nodiscard
Definition at line 200 of file Deque.h.
References Capacity, and FORCEINLINE.
Referenced by GetIterator(), and GetIterator().
MoveUnchecked()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::MoveUnchecked (TDeque< InElementType, InAllocatorType > && Other) inline private
Definition at line 496 of file Deque.h.
References TDeque, Capacity, checkSlow, Count, Head, Other, Storage, and Tail.
Referenced by TDeque(), and operator=().
Num()
template<typename InElementType, typename InAllocatorType> FORCEINLINE SizeType TDeque< InElementType, InAllocatorType >::Num () const inline nodiscard
Definition at line 205 of file Deque.h.
References Count, and FORCEINLINE.
Referenced by operator==().
operator!=()
template<typename InElementType, typename InAllocatorType> bool TDeque< InElementType, InAllocatorType >::operator!= (const TDeque< InElementType, InAllocatorType > & Right) const inline nodiscard
Definition at line 609 of file Deque.h.
References TDeque, and Right.
operator=() [1/3]
template<typename InElementType, typename InAllocatorType> TDeque & TDeque< InElementType, InAllocatorType >::operator= (const TDeque< InElementType, InAllocatorType > & Other) inline
Definition at line 142 of file Deque.h.
References TDeque, CopyUnchecked(), Other, and Reset().
operator=() [2/3]
template<typename InElementType, typename InAllocatorType> TDeque & TDeque< InElementType, InAllocatorType >::operator= (std::initializer_list< ElementType > InList) inline
Definition at line 152 of file Deque.h.
References TDeque, CopyUnchecked(), and Reset().
operator=() [3/3]
template<typename InElementType, typename InAllocatorType> TDeque & TDeque< InElementType, InAllocatorType >::operator= (TDeque< InElementType, InAllocatorType > && Other) inline
Definition at line 132 of file Deque.h.
References TDeque, MoveTemp(), MoveUnchecked(), Other, and Reset().
operator==()
template<typename InElementType, typename InAllocatorType> bool TDeque< InElementType, InAllocatorType >::operator== (const TDeque< InElementType, InAllocatorType > & Right) const inline nodiscard
Definition at line 589 of file Deque.h.
References TDeque, begin(), end(), Num(), and Right.
operator[]() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE ElementType & TDeque< InElementType, InAllocatorType >::operator[] (SizeType Index) inline nodiscard
Definition at line 165 of file Deque.h.
References Capacity, CheckValidIndex(), FORCEINLINE, GetData(), Head, and UE::Deque::Private::WrapAround().
operator[]() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE const ElementType & TDeque< InElementType, InAllocatorType >::operator[] (SizeType Index) const inline nodiscard
Definition at line 159 of file Deque.h.
References Capacity, CheckValidIndex(), FORCEINLINE, GetData(), Head, and UE::Deque::Private::WrapAround().
PopFirst()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::PopFirst () inline
Definition at line 294 of file Deque.h.
References Capacity, CheckValidIndex(), Count, DestructItem(), GetData(), Head, and UE::Deque::Private::WrapAround().
PopLast()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::PopLast () inline
Definition at line 281 of file Deque.h.
References Capacity, CheckValidIndex(), Count, DestructItem(), GetData(), Tail, and UE::Deque::Private::WrapAround().
PushFirst() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TDeque< InElementType, InAllocatorType >::PushFirst (const ElementType & Element) inline
Definition at line 267 of file Deque.h.
References EmplaceFirst(), and FORCEINLINE.
PushFirst() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TDeque< InElementType, InAllocatorType >::PushFirst (ElementType && Element) inline
Definition at line 272 of file Deque.h.
References EmplaceFirst(), FORCEINLINE, and MoveTempIfPossible().
PushLast() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TDeque< InElementType, InAllocatorType >::PushLast (const ElementType & Element) inline
Definition at line 254 of file Deque.h.
References EmplaceLast(), and FORCEINLINE.
PushLast() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TDeque< InElementType, InAllocatorType >::PushLast (ElementType && Element) inline
Definition at line 259 of file Deque.h.
References EmplaceLast(), FORCEINLINE, and MoveTempIfPossible().
Reserve()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::Reserve (SizeType InCount) inline
Definition at line 373 of file Deque.h.
References Capacity, Grow(), and Storage.
Referenced by CopyUnchecked(), and CopyUnchecked().
Reset()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::Reset () inline
Definition at line 340 of file Deque.h.
References Capacity, Count, DestructItems(), GetData(), Head, and Tail.
Referenced by Empty(), operator=(), operator=(), and operator=().
ShiftElementsLeft()
template<typename InElementType, typename InAllocatorType> void TDeque< InElementType, InAllocatorType >::ShiftElementsLeft (SizeType InCount) inline private
Moves the parameter number of elements to the left shifting the head to the beginning of the storage.
Definition at line 561 of file Deque.h.
References GetData(), Head, FMath::Min, and RelocateConstructItems().
Referenced by Linearize().
TryPopFirst()
template<typename InElementType, typename InAllocatorType> bool TDeque< InElementType, InAllocatorType >::TryPopFirst (ElementType & OutValue) inline nodiscard
Definition at line 324 of file Deque.h.
References Capacity, Count, DestructItem(), GetData(), Head, IsEmpty(), MoveTempIfPossible(), and UE::Deque::Private::WrapAround().
TryPopLast()
template<typename InElementType, typename InAllocatorType> bool TDeque< InElementType, InAllocatorType >::TryPopLast (ElementType & OutValue) inline nodiscard
Definition at line 306 of file Deque.h.
References Capacity, Count, DestructItem(), GetData(), IsEmpty(), MoveTempIfPossible(), Tail, and UE::Deque::Private::WrapAround().
Friends And Related Symbol Documentation
TDeque
template<typename InElementType, typename InAllocatorType> template<typename AnyElementType, typename AnyAllocatorType> friend class TDeque friend
Definition at line 91 of file Deque.h.
References TDeque.
Referenced by TDeque, TDeque(), TDeque(), CopyElements(), CopyUnchecked(), MoveUnchecked(), operator!=(), operator=(), operator=(), operator=(), and operator==().
Field Documentation
Capacity
template<typename InElementType, typename InAllocatorType> SizeType TDeque< InElementType, InAllocatorType >::Capacity = 0 private
Definition at line 403 of file Deque.h.
Referenced by TDeque(), TDeque(), TDeque(), CheckValidIndex(), CopyElements(), CopyUnchecked(), CopyUnchecked(), EmplaceFirst(), EmplaceLast(), Empty(), GetAllocatedSize(), Grow(), GrowIfRequired(), Last(), Last(), Linearize(), Max(), MoveUnchecked(), operator[](), operator[](), PopFirst(), PopLast(), Reserve(), Reset(), TryPopFirst(), and TryPopLast().
Count
template<typename InElementType, typename InAllocatorType> SizeType TDeque< InElementType, InAllocatorType >::Count = 0 private
Definition at line 404 of file Deque.h.
Referenced by CheckValidIndex(), CopyElements(), CopyUnchecked(), CopyUnchecked(), EmplaceFirst(), EmplaceLast(), end(), end(), Grow(), GrowIfRequired(), IsEmpty(), Linearize(), MoveUnchecked(), Num(), PopFirst(), PopLast(), Reset(), TryPopFirst(), and TryPopLast().
Head
template<typename InElementType, typename InAllocatorType> SizeType TDeque< InElementType, InAllocatorType >::Head = 0 private
Definition at line 405 of file Deque.h.
Referenced by begin(), begin(), CopyElements(), EmplaceFirst(), end(), end(), First(), First(), Grow(), Linearize(), MoveUnchecked(), operator[](), operator[](), PopFirst(), Reset(), ShiftElementsLeft(), and TryPopFirst().
Storage
template<typename InElementType, typename InAllocatorType> ElementAllocatorType TDeque< InElementType, InAllocatorType >::Storage private
Definition at line 402 of file Deque.h.
Referenced by TDeque(), TDeque(), TDeque(), CopyUnchecked(), Empty(), GetAllocatedSize(), GetData(), GetData(), Grow(), GrowIfRequired(), MoveUnchecked(), and Reserve().
Tail
template<typename InElementType, typename InAllocatorType> SizeType TDeque< InElementType, InAllocatorType >::Tail = 0 private
Definition at line 406 of file Deque.h.
Referenced by CopyElements(), CopyUnchecked(), EmplaceLast(), Grow(), Last(), Last(), Linearize(), MoveUnchecked(), PopLast(), Reset(), and TryPopLast().
The documentation for this class was generated from the following file:
Deque.h