Unreal Engine 5.6 C++ API: UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ > Class Template Reference
UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ > Class Template Reference
TBasicBlockedDenseGrid3 represents a 3D blocked uniform grid.
#include "BlockedDenseGrid3.h"
Data Structures
struct FBlock3
Public Types
typedef TBlockData3< ElemType, BlockSize_ > BlockData3Type
typedef TBlockedGrid3Layout< BlockSize_ > BlockedGrid3LayoutType
Public Types inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
typedef TBlockData3Layout< BlockSize_ > FBlockData3Layout
Public Member Functions
TBasicBlockedDenseGrid3 ()
Create empty grid.
TBasicBlockedDenseGrid3 (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue)
Create grid with specified domain.
int32 GetNumBlocks () const
ElemType GetValue (const FVector3i &CellIJK) const
ElemType GetValue (int32 I, int32 J, int32 K) const
template<typename OtherElemType>
bool PreAllocateFromSourceGrid (const TBasicBlockedDenseGrid3< OtherElemType, BlockSize > &SourceGrid)
Pre-allocate the grid blocks that also exist in SourceGrid of the same dimensions.
template<typename ProcessFunc>
void ProcessValue (const FVector3i &CellIJK, ProcessFunc Func)
Call an external lambda with a reference to the grid value at CellIJK.
template<typename ProcessFunc>
void ProcessValue (int32 I, int32 J, int32 K, ProcessFunc Func)
Call an external lambda with a reference to the grid value at (I,J,K).
void Reset ()
Discard all allocated blocks but retain grid dimensions.
void Reset (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue)
Reconfigure the grid to have the target dimensions and default value.
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Reconfigure the grid to have the target dimensions.
void SetValue (const FVector3i &CellIJK, ElemType NewValue)
Set the grid value at CellIJK.
void SetValue (int32 I, int32 J, int32 K, ElemType NewValue)
Set the grid value at (I,J,K)
Public Member Functions inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
TBlockedGrid3Layout ()
TBlockedGrid3Layout (FVector3i Dims)
TBlockedGrid3Layout (int32 DimI, int32 DimJ, int32 DimK)
int32 BlockIJKToBlockIndex (const FVector3i &BlockIJK) const
FVector3i BlockIndexToBlockIJK (const int32 BlockIndex) const
FAxisAlignedBox3i Bounds () const
FAxisAlignedBox3i BoundsInclusive () const
void GetBlockAndLocalIndex (const FVector3i &IJK, int32 &BlockIndexOut, int32 &LocalIndexOut) const
return the block index and local index of the cell at (I,J,K).
void GetBlockAndLocalIndex (int32 I, int32 J, int32 K, int32 &BlockIndexOut, int32 &LocalIndexOut) const
const FVector3i & GetBlockDimensions () const
const FVector3i & GetDimensions () const
int32 IJKtoBlockIndex (const FVector3i &IJK) const
bool IsValidBlockIJK (const FVector3i &BlockIJK)
bool IsValidIJK (const FVector3i &IJK) const
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Recompute the block dimensions required to cover the requested cell dimensions.
int64 Size () const
Static Public Attributes
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = BlockSize_
Static Public Attributes inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = BlockSize_
Protected Member Functions
template<typename OtherGridType>
bool AllocateTopologyUnionImpl (const OtherGridType &OtherGrid)
FBlock3 & GetBlock (int32 Index)
const FBlock3 & GetBlock (int32 Index) const
bool IsBlockAllocated (const FBlock3 &Block) const
bool IsBlockAllocated (const int32 BlockIndex) const
ElemType ReadValue (const int32 &BlockIndex, const int32 &LocalIndex) const
ElemType ReadValue (int32 I, int32 J, int32 K) const
ElemType ReadValueWithLock (const int32 &BlockIndex, const int32 &LocalIndex, FCriticalSection *CriticalSection)
BlockData3Type & TouchBlockData (const int32 BlockIndex)
return a reference to the block data buffer associated with the specified block, allocating if needed
template<typename FuncType>
void WriteValue (const int32 &BlockIndex, const int32 &LocalIndex, FuncType Func)
template<typename FuncType>
void WriteValue (int32 I, int32 J, int32 K, FuncType Func)
template<typename FuncType>
void WriteValueWithLock (const int32 &BlockIndex, const int32 &LocalIndex, FuncType Func, FCriticalSection *CriticalSection)
Protected Attributes
TArray< FBlock3 > Blocks
ElemType DefaultValue = (ElemType)0
The value to use to initialize new blocks.
Protected Attributes inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
FVector3i BlockDimensions
FVector3i Dimensions
Friends
template<class OtherElemType, int32 OtherBlockSize>
class TBasicBlockedDenseGrid3
Detailed Description
template<typename ElemType, int32 BlockSize_>
class UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >
TBasicBlockedDenseGrid3 represents a 3D blocked uniform grid.
The grid is allocated in BlockSize^3 blocks on-demand (BlockSize is a compile-time constant) allowing very large grids to be used without having to pre-allocate all the memory, eg for sparse/narrow-band use cases.
Block-level default values are returned when querying a grid cell in an unallocated block.
For multi-threaded applications consider using the derived classes TBlockedDenseGrid3 which manages internal locks, or TBlockedGrid3 with your own lock provider.
Definition at line 140 of file BlockedDenseGrid3.h.
Member Typedef Documentation
BlockData3Type
template<typename ElemType, int32 BlockSize_> typedef TBlockData3<ElemType, BlockSize_> UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::BlockData3Type
Definition at line 144 of file BlockedDenseGrid3.h.
BlockedGrid3LayoutType
template<typename ElemType, int32 BlockSize_> typedef TBlockedGrid3Layout<BlockSize_> UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::BlockedGrid3LayoutType
Definition at line 143 of file BlockedDenseGrid3.h.
Constructor & Destructor Documentation
TBasicBlockedDenseGrid3() [1/2]
template<typename ElemType, int32 BlockSize_> UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::TBasicBlockedDenseGrid3 () inline
Create empty grid.
Definition at line 268 of file BlockedDenseGrid3.h.
TBasicBlockedDenseGrid3() [2/2]
template<typename ElemType, int32 BlockSize_> UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::TBasicBlockedDenseGrid3 (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue) inline
Create grid with specified domain.
Definition at line 275 of file BlockedDenseGrid3.h.
Member Function Documentation
AllocateTopologyUnionImpl()
template<typename ElemType, int32 BlockSize_> template<typename OtherGridType> bool UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::AllocateTopologyUnionImpl (const OtherGridType & OtherGrid) inline protected
Definition at line 397 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::PreAllocateFromSourceGrid().
GetBlock() [1/2]
template<typename ElemType, int32 BlockSize_> FBlock3 & UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::GetBlock (int32 Index) inline protected
Definition at line 191 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::GetBlockData(), UE::Geometry::TBlockedGrid3< float, 8 >::GetBlockData(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::IsBlockAllocated(), UE::Geometry::TBlockedGrid3< float, 8 >::ReadBlockDefaultValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::ReadValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::TouchBlockData(), and UE::Geometry::TBlockedGrid3< float, 8 >::WriteBlockDefaultValue().
GetBlock() [2/2]
template<typename ElemType, int32 BlockSize_> const FBlock3 & UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::GetBlock (int32 Index) const inline protected
Definition at line 192 of file BlockedDenseGrid3.h.
GetNumBlocks()
template<typename ElemType, int32 BlockSize_> int32 UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::GetNumBlocks () const inline
Returns
the total number of block units form the spatial decomposition of the grid. Note these block may not all be allocated
Definition at line 389 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::AllocateTopologyUnionImpl(), UE::Geometry::TBlockedGrid3< float, 8 >::GetAllocatedBlocks(), UE::Geometry::TBlockedGrid3< float, 8 >::GetAllocatedConstBlocks(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::Resize().
GetValue() [1/2]
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::GetValue (const FVector3i & CellIJK) const inline
Returns
the grid value at CellIJK. Note this is safe to call from multiple read threads (but not if simultaneously writing!)
Definition at line 327 of file BlockedDenseGrid3.h.
GetValue() [2/2]
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::GetValue (int32 I, int32 J, int32 K) const inline
Returns
the grid value at (I,J,K)
Definition at line 319 of file BlockedDenseGrid3.h.
IsBlockAllocated() [1/2]
template<typename ElemType, int32 BlockSize_> bool UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::IsBlockAllocated (const FBlock3 & Block) const inline protected
Returns
true if Block has an allocated block data buffer
Definition at line 196 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::GetAllocatedBlocks(), UE::Geometry::TBlockedGrid3< float, 8 >::GetAllocatedConstBlocks(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::IsBlockAllocated(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::TouchBlockData().
IsBlockAllocated() [2/2]
template<typename ElemType, int32 BlockSize_> bool UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::IsBlockAllocated (const int32 BlockIndex) const inline protected
Returns
true if the specified Block has an allocated block data buffer
Definition at line 201 of file BlockedDenseGrid3.h.
PreAllocateFromSourceGrid()
template<typename ElemType, int32 BlockSize_> template<typename OtherElemType> bool UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::PreAllocateFromSourceGrid (const TBasicBlockedDenseGrid3< OtherElemType, BlockSize > & SourceGrid) inline
Pre-allocate the grid blocks that also exist in SourceGrid of the same dimensions.
This is useful in grid-processing algorithms where parallel grid operations can be done without locking if the blocks are already allocated.
Returns
false on failure (e.g. different sized grids), otherwise true.
Definition at line 383 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill().
ProcessValue() [1/2]
template<typename ElemType, int32 BlockSize_> template<typename ProcessFunc> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::ProcessValue (const FVector3i & CellIJK, ProcessFunc Func) inline
Call an external lambda with a reference to the grid value at CellIJK.
Called as Func(ElemType&), so the caller can both read and write the grid cell
Note: if doing pure reads prefer the GetValue() methods because the ProcessValue method will allocate the underlying data block.
Definition at line 369 of file BlockedDenseGrid3.h.
ProcessValue() [2/2]
template<typename ElemType, int32 BlockSize_> template<typename ProcessFunc> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::ProcessValue (int32 I, int32 J, int32 K, ProcessFunc Func) inline
Call an external lambda with a reference to the grid value at (I,J,K).
Called as Func(ElemType&), so the caller can both read and write the grid cell.
Note: if doing pure reads prefer the GetValue() methods because the ProcessValue method will allocate the underlying data block.
Definition at line 357 of file BlockedDenseGrid3.h.
ReadValue() [1/2]
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::ReadValue (const int32 & BlockIndex, const int32 & LocalIndex) const inline protected
Definition at line 244 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::GetValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::GetValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::ReadValue(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::ReadValueWithLock().
ReadValue() [2/2]
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::ReadValue (int32 I, int32 J, int32 K) const inline protected
Definition at line 249 of file BlockedDenseGrid3.h.
ReadValueWithLock()
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::ReadValueWithLock (const int32 & BlockIndex, const int32 & LocalIndex, FCriticalSection * CriticalSection) inline protected
Definition at line 256 of file BlockedDenseGrid3.h.
Reset() [1/2]
template<typename ElemType, int32 BlockSize_> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::Reset () inline
Discard all allocated blocks but retain grid dimensions.
This also resets the block-level default values.
Definition at line 301 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::Reset().
Reset() [2/2]
template<typename ElemType, int32 BlockSize_> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::Reset (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue) inline
Reconfigure the grid to have the target dimensions and default value.
This clears all the existing grid memory, and resets default values to the specified InitialValue.
Definition at line 310 of file BlockedDenseGrid3.h.
Resize()
template<typename ElemType, int32 BlockSize_> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::Resize (int32 DimI, int32 DimJ, int32 DimK) inline
Reconfigure the grid to have the target dimensions.
This clears all the existing grid memory and resets the block-level default value.
Definition at line 285 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::Reset(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::TBasicBlockedDenseGrid3().
SetValue() [1/2]
template<typename ElemType, int32 BlockSize_> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::SetValue (const FVector3i & CellIJK, ElemType NewValue) inline
Set the grid value at CellIJK.
Definition at line 344 of file BlockedDenseGrid3.h.
SetValue() [2/2]
template<typename ElemType, int32 BlockSize_> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::SetValue (int32 I, int32 J, int32 K, ElemType NewValue) inline
Set the grid value at (I,J,K)
Definition at line 336 of file BlockedDenseGrid3.h.
TouchBlockData()
template<typename ElemType, int32 BlockSize_> BlockData3Type & UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::TouchBlockData (const int32 BlockIndex) inline protected
return a reference to the block data buffer associated with the specified block, allocating if needed
Definition at line 208 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::AllocateTopologyUnionImpl(), UE::Geometry::TBlockedGrid3< float, 8 >::TouchBlockData(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::WriteValue().
WriteValue() [1/2]
template<typename ElemType, int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::WriteValue (const int32 & BlockIndex, const int32 & LocalIndex, FuncType Func) inline protected
Definition at line 221 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::ProcessValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::ProcessValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::SetValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::SetValue(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::WriteValue(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::WriteValueWithLock().
WriteValue() [2/2]
template<typename ElemType, int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::WriteValue (int32 I, int32 J, int32 K, FuncType Func) inline protected
Definition at line 228 of file BlockedDenseGrid3.h.
WriteValueWithLock()
template<typename ElemType, int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::WriteValueWithLock (const int32 & BlockIndex, const int32 & LocalIndex, FuncType Func, FCriticalSection * CriticalSection) inline protected
Definition at line 236 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::ProcessValueWithLock(), and UE::Geometry::TBlockedGrid3< float, 8 >::SetValueWithLock().
Friends And Related Symbol Documentation
TBasicBlockedDenseGrid3
template<typename ElemType, int32 BlockSize_> template<class OtherElemType, int32 OtherBlockSize> friend class TBasicBlockedDenseGrid3 friend
Definition at line 182 of file BlockedDenseGrid3.h.
Field Documentation
BlockElemCount
template<typename ElemType, int32 BlockSize_> int32 UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::BlockElemCount = BlockSize * BlockSize * BlockSize static constexpr
Definition at line 148 of file BlockedDenseGrid3.h.
Blocks
template<typename ElemType, int32 BlockSize_> TArray<FBlock3> UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::Blocks protected
Definition at line 176 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::GetAllocatedBlocks(), and UE::Geometry::TBlockedGrid3< float, 8 >::GetAllocatedConstBlocks().
BlockSize
template<typename ElemType, int32 BlockSize_> int32 UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::BlockSize = BlockSize_ static constexpr
Definition at line 147 of file BlockedDenseGrid3.h.
DefaultValue
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::DefaultValue = (ElemType)0 protected
The value to use to initialize new blocks.
Definition at line 152 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedDenseGrid3< float >::TBlockedDenseGrid3(), UE::Geometry::TBlockedDenseGrid3< float >::Reset(), and UE::Geometry::TBlockedDenseGrid3< float >::Reset().
The documentation for this class was generated from the following file:
BlockedDenseGrid3.h