Unreal Engine 5.6 C++ API: FSlotBase Class Reference
FSlotBase Class Reference
Slot are a container of a SWidget used by the FChildren.
#include "SlotBase.h"
Data Structures
struct FSlotArguments
Public Member Functions
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Protected Member Functions
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Private Member Functions
void AfterContentOrOwnerAssigned ()
void DetatchParentFromContent ()
Private Attributes
const FChildren * Owner
The children that own the slot.
TSharedRef< SWidget > Widget
The content widget of the slot.
Detailed Description
Slot are a container of a SWidget used by the FChildren.
Definition at line 13 of file SlotBase.h.
Constructor & Destructor Documentation
FSlotBase() [1/4]
FSlotBase::FSlotBase ()
Referenced by FSlotBase(), and operator=().
FSlotBase() [2/4]
FSlotBase::FSlotBase (const FChildren & InParent)
FSlotBase() [3/4]
FSlotBase::FSlotBase (const TSharedRef< SWidget > & InWidget)
FSlotBase() [4/4]
FSlotBase::FSlotBase (const FSlotBase &) delete
References FSlotBase().
~FSlotBase()
virtual FSlotBase::~FSlotBase () virtual
Member Function Documentation
AfterContentOrOwnerAssigned()
void FSlotBase::AfterContentOrOwnerAssigned () private
Referenced by AttachWidget(), and AttachWidget().
AttachWidget() [1/2]
FORCEINLINE_DEBUGGABLE void FSlotBase::AttachWidget (const TSharedRef< SWidget > & InWidget) inline
Definition at line 53 of file SlotBase.h.
References AfterContentOrOwnerAssigned(), DetatchParentFromContent(), FORCEINLINE_DEBUGGABLE, and Widget.
AttachWidget() [2/2]
FORCEINLINE_DEBUGGABLE void FSlotBase::AttachWidget (TSharedRef< SWidget > && InWidget) inline
Attach the child widget the slot now owns.
Definition at line 47 of file SlotBase.h.
References AfterContentOrOwnerAssigned(), DetatchParentFromContent(), FORCEINLINE_DEBUGGABLE, MoveTemp(), and Widget.
Referenced by TSlotBase< SlotType >::Construct(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::operator[](), TSlotBase< SlotType >::operator[](), and TSlotBase< SlotType >::operator[]().
DetachWidget()
const TSharedPtr< SWidget > FSlotBase::DetachWidget ()
Remove the widget from its current slot.
The removed widget is returned so that operations could be performed on it. If the null widget was being stored, an invalid shared ptr is returned instead.
DetatchParentFromContent()
void FSlotBase::DetatchParentFromContent () private
Referenced by AttachWidget(), and AttachWidget().
GetOwner()
const FChildren * FSlotBase::GetOwner () const inline
Access the FChildren that own the slot.
The owner can be invalid when the slot is not attached.
Definition at line 32 of file SlotBase.h.
References Owner.
Referenced by TWidgetSlotWithAttributeSupport< SlotType >::GetContainerName(), and TWidgetSlotWithAttributeSupport< SlotType >::GetContainerSortOrder().
GetOwnerWidget()
SWidget * FSlotBase::GetOwnerWidget () const
Access the widget that own the slot.
The owner can be invalid when the slot is not attached.
Referenced by TWidgetSlotWithAttributeSupport< SlotType >::~TWidgetSlotWithAttributeSupport(), TWidgetSlotWithAttributeSupport< SlotType >::GetContainerWidget(), and TWidgetSlotWithAttributeSupport< SlotType >::RequestSortAttribute().
GetWidget()
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & FSlotBase::GetWidget () const inline
Access the widget in the current slot.
There will always be a widget in the slot; sometimes it is the SNullWidget instance.
Definition at line 65 of file SlotBase.h.
References FORCEINLINE_DEBUGGABLE, and Widget.
Referenced by SNodePanel::SNode::ComputeDesiredSize(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::GetChildAt(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::GetChildAt(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::GetChildRefAt(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::GetChildRefAt(), and SNodePanel::SNode::OnArrangeChildren().
Invalidate()
void FSlotBase::Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
Referenced by SetAttribute(), SUniformGridPanel::FSlot::SetColumn(), SGridPanel::FSlot::SetNudge(), and SUniformGridPanel::FSlot::SetRow().
operator=()
FSlotBase & FSlotBase::operator= (const FSlotBase &) delete
References FSlotBase().
SetAttribute()
template<typename TargetValueType, typename SourceValueType> bool FSlotBase::SetAttribute (TAttribute< TargetValueType > & TargetValue, const TAttribute< SourceValueType > & SourceValue, EInvalidateWidgetReason BaseInvalidationReason) inline protected
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
So if the boundness of the attribute didn't change volatility won't need to be recalculated. Returns true if the value changed.
Definition at line 86 of file SlotBase.h.
References TAttribute< ObjectType >::IdenticalTo(), Invalidate(), TAttribute< ObjectType >::IsBound(), and Volatility.
Referenced by SConstraintCanvas::FSlot::SetAlignment(), SConstraintCanvas::FSlot::SetAnchors(), SConstraintCanvas::FSlot::SetAutoSize(), and SConstraintCanvas::FSlot::SetOffset().
SetOwner()
void FSlotBase::SetOwner (const FChildren & Children)
Set the owner of the slot.
Slots cannot be reassigned to different parents.
Referenced by TSlotBase< SlotType >::Construct().
Field Documentation
Owner
const FChildren* FSlotBase::Owner private
The children that own the slot.
Definition at line 113 of file SlotBase.h.
Referenced by GetOwner().
Widget
TSharedRef<SWidget> FSlotBase::Widget private
The content widget of the slot.
Definition at line 115 of file SlotBase.h.
Referenced by AttachWidget(), AttachWidget(), and GetWidget().
The documentation for this class was generated from the following file:
SlotBase.h