Unreal Engine 5.6 C++ API: ExponentialHeightFogStateStream.h File Reference
ExponentialHeightFogStateStream.h File Reference
#include "EngineDefines.h"
#include "ExponentialHeightFogStateStreamHandle.h"
#include "Rendering/ExponentialHeightFogData.h"
#include "StateStreamDefinitions.h"
#include "TransformStateStreamMath.h"
#include "ExponentialHeightFogStateStream.generated.h"
Data Structures
class IExponentialHeightFogStateStream
Functions
bool StateStreamEquals (const FExponentialHeightFogData &A, const FExponentialHeightFogData &B)
void StateStreamInterpolate (FStateStreamInterpolateContext &Context, FExponentialHeightFogData &Out, const FExponentialHeightFogData &From, const FExponentialHeightFogData &To)
USTRUCT () struct FExponentialHeightFogStaticState
Variables
constexpr uint32 ExponentialHeightFogStateStreamId = 7
Function Documentation
StateStreamEquals()
bool StateStreamEquals (const FExponentialHeightFogData & A, const FExponentialHeightFogData & B) inline
Definition at line 117 of file ExponentialHeightFogStateStream.h.
References A, B, and StateStreamEquals().
Referenced by StateStreamEquals().
StateStreamInterpolate()
void StateStreamInterpolate (FStateStreamInterpolateContext & Context, FExponentialHeightFogData & Out, const FExponentialHeightFogData & From, const FExponentialHeightFogData & To) inline
Definition at line 122 of file ExponentialHeightFogStateStream.h.
References StateStreamInterpolate().
Referenced by StateStreamInterpolate().
USTRUCT()
USTRUCT ()
Definition at line 19 of file ExponentialHeightFogStateStream.h.
References GENERATED_USTRUCT_BODY.
Variable Documentation
ExponentialHeightFogStateStreamId
uint32 ExponentialHeightFogStateStreamId = 7 inline constexpr
Definition at line 103 of file ExponentialHeightFogStateStream.h.