Unreal Engine 5.6 C++ API: SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType > Struct Template Reference
SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType > Struct Template Reference
Public Types
using WidgetArgsType = ArgumentType
Public Member Functions
FORCENOINLINE FVectorWArguments ()
OnWChanged ToggleWChecked ContextMenuExtenderW OnWEndSliderMovement SLATE_ATTRIBUTE (FText, WDisplayName) SLATE_ATTRIBUTE(FLinearColor
The DisplayName of the W component of the vector.
SLATE_ATTRIBUTE (TOptional< NumericType >, W) SLATE_EVENT(FOnNumericValueChanged
W Component of the vector.
OnWChanged ToggleWChecked SLATE_EVENT (FOnCheckStateChanged, OnToggleWChanged) SLATE_EVENT(FMenuExtensionDelegate
Called whenever the toggle W changes state.
OnWChanged SLATE_EVENT (FOnNumericValueCommitted, OnWCommitted) SLATE_ATTRIBUTE(ECheckBoxState
Called when the W value of the vector is committed.
OnWChanged ToggleWChecked ContextMenuExtenderW SLATE_EVENT (FSimpleDelegate, OnWBeginSliderMovement) SLATE_EVENT(FOnNumericValueChanged
Called when the w value of the vector slider began movement.
Detailed Description
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3>
template<typename ArgumentType>
struct SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >
Definition at line 201 of file SVectorInputBox.h.
Member Typedef Documentation
WidgetArgsType
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> using SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::WidgetArgsType = ArgumentType
Definition at line 203 of file SVectorInputBox.h.
Constructor & Destructor Documentation
FVectorWArguments()
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> FORCENOINLINE SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::FVectorWArguments () inline
Definition at line 205 of file SVectorInputBox.h.
References FORCENOINLINE, SNumericEntryBox< NumericType >::LilacLabelBackgroundColor, and NSLOCTEXT.
Referenced by SLATE_ATTRIBUTE().
Member Function Documentation
SLATE_ATTRIBUTE() [1/2]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnWChanged ToggleWChecked ContextMenuExtenderW OnWEndSliderMovement SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::SLATE_ATTRIBUTE (FText , WDisplayName)
The DisplayName of the W component of the vector.
References FVectorWArguments(), FORCENOINLINE, FAppStyle::Get(), SLATE_ARGUMENT, SLATE_ATTRIBUTE, SLATE_ATTRIBUTE(), SLATE_EVENT, SLATE_STYLE_ARGUMENT, and Vector.
SLATE_ATTRIBUTE() [2/2]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::SLATE_ATTRIBUTE (TOptional< NumericType > , W)
W Component of the vector.
Called when the W value of the vector is changed
Referenced by SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_EVENT() [1/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnWChanged ToggleWChecked SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::SLATE_EVENT (FOnCheckStateChanged , OnToggleWChanged)
Called whenever the toggle W changes state.
Menu extender delegate for the W value
References SLATE_EVENT().
SLATE_EVENT() [2/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnWChanged SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::SLATE_EVENT (FOnNumericValueCommitted , OnWCommitted)
Called when the W value of the vector is committed.
The value of the toggle W checkbox
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
Referenced by SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [3/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnWChanged ToggleWChecked ContextMenuExtenderW SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::SLATE_EVENT (FSimpleDelegate , OnWBeginSliderMovement)
Called when the w value of the vector slider began movement.
Called when the w value of the vector slider ended movement
References SLATE_EVENT().
The documentation for this struct was generated from the following file:
SVectorInputBox.h