Unreal Engine 5.6 C++ API: FSimpleStreamableAssetManager::FUpdate Struct Reference
FSimpleStreamableAssetManager::FUpdate Struct Reference
#include "SimpleStreamableAssetManager.h"
Public Member Functions
FUpdate ()=default
FUpdate (const FUpdate &)=default
FUpdate (const void *InObject, const TSharedPtr< int32, ESPMode::ThreadSafe > &InObjectRegistrationIndex, const FBoxSphereBounds &InBounds, const float InMinDistance, const float InMaxDistance, const float InLastRenderedTime, bool InForceMipStreaming)
FUpdate (FUpdate &&)=default
FUpdate & operator= (const FUpdate &)=default
FUpdate & operator= (FUpdate &&)=default
Data Fields
union {
UPTRINT ObjectKey = 0
const FPrimitiveSceneProxy * SceneProxy_ForDebug
};
uint8 bForceMipStreaming: 1 = false
float LastRenderedTime = -1000.0f
float MaxDistance = FLT_MAX
float MinDistance = 0.0f
FBoxSphereBounds ObjectBounds {}
TSharedPtr< int32, ESPMode::ThreadSafe > ObjectRegistrationIndex {}
Detailed Description
Definition at line 181 of file SimpleStreamableAssetManager.h.
Constructor & Destructor Documentation
FUpdate() [1/4]
FSimpleStreamableAssetManager::FUpdate::FUpdate () default
Referenced by FSimpleStreamableAssetManager::FRegister::FRegister(), FUpdate(), FUpdate(), operator=(), and operator=().
FUpdate() [2/4]
FSimpleStreamableAssetManager::FUpdate::FUpdate (const FUpdate &) default
References FUpdate().
FUpdate() [3/4]
FSimpleStreamableAssetManager::FUpdate::FUpdate (FUpdate &&) default
References FUpdate().
FUpdate() [4/4]
FSimpleStreamableAssetManager::FUpdate::FUpdate (const void * InObject, const TSharedPtr< int32, ESPMode::ThreadSafe > & InObjectRegistrationIndex, const FBoxSphereBounds & InBounds, const float InMinDistance, const float InMaxDistance, const float InLastRenderedTime, bool InForceMipStreaming) inline
Definition at line 203 of file SimpleStreamableAssetManager.h.
References bForceMipStreaming, LastRenderedTime, MaxDistance, MinDistance, ObjectBounds, ObjectKey, ObjectRegistrationIndex, and SIMPLE_STREAMABLE_ASSET_MANAGER_ALLOW_DEBUG_POINTER.
Member Function Documentation
operator=() [1/2]
FUpdate & FSimpleStreamableAssetManager::FUpdate::operator= (const FUpdate &) default
References FUpdate().
operator=() [2/2]
FUpdate & FSimpleStreamableAssetManager::FUpdate::operator= (FUpdate &&) default
References FUpdate().
Field Documentation
[union]
union { ... } FSimpleStreamableAssetManager::FUpdate
bForceMipStreaming
uint8 FSimpleStreamableAssetManager::FUpdate::bForceMipStreaming
Definition at line 195 of file SimpleStreamableAssetManager.h.
Referenced by FUpdate().
LastRenderedTime
float FSimpleStreamableAssetManager::FUpdate::LastRenderedTime = -1000.0f
Definition at line 194 of file SimpleStreamableAssetManager.h.
Referenced by FUpdate().
MaxDistance
float FSimpleStreamableAssetManager::FUpdate::MaxDistance = FLT_MAX
Definition at line 193 of file SimpleStreamableAssetManager.h.
Referenced by FUpdate().
MinDistance
float FSimpleStreamableAssetManager::FUpdate::MinDistance = 0.0f
Definition at line 192 of file SimpleStreamableAssetManager.h.
Referenced by FUpdate().
ObjectBounds
FBoxSphereBounds FSimpleStreamableAssetManager::FUpdate::ObjectBounds {}
Definition at line 184 of file SimpleStreamableAssetManager.h.
Referenced by FUpdate().
ObjectKey
UPTRINT FSimpleStreamableAssetManager::FUpdate::ObjectKey = 0
Definition at line 188 of file SimpleStreamableAssetManager.h.
Referenced by FUpdate().
ObjectRegistrationIndex
TSharedPtr<int32, ESPMode::ThreadSafe> FSimpleStreamableAssetManager::FUpdate::ObjectRegistrationIndex {}
Definition at line 183 of file SimpleStreamableAssetManager.h.
Referenced by FUpdate().
SceneProxy_ForDebug
const FPrimitiveSceneProxy* FSimpleStreamableAssetManager::FUpdate::SceneProxy_ForDebug
Definition at line 189 of file SimpleStreamableAssetManager.h.
The documentation for this struct was generated from the following file:
SimpleStreamableAssetManager.h