Unreal Engine 5.6 C++ API: TIntrusiveList< TypeTraits > Class Template Reference
TIntrusiveList< TypeTraits > Class Template Reference
#include "IoContainers.h"
Public Types
using ElementType = typename TypeTraits::ElementType
using FConstIterator = UE::Private::TIntrusiveListIterator<const TypeTraits>
using FIterator = UE::Private::TIntrusiveListIterator<TypeTraits>
Public Member Functions
TIntrusiveList ()=default
TIntrusiveList (const TIntrusiveList &)=delete
TIntrusiveList (ElementType *Element)
TIntrusiveList (TIntrusiveList &&Other)
void AddTail (ElementType *Element)
void AddTail (ElementType *First, ElementType *Last)
void AddTail (TIntrusiveList &&Other)
FIterator begin ()
FConstIterator begin () const
FIterator end ()
FConstIterator end () const
ElementType * GetHead ()
const ElementType * GetHead () const
ElementType * GetTail ()
const ElementType * GetTail () const
bool IsEmpty () const
TIntrusiveList & operator= (const TIntrusiveList &)=delete
TIntrusiveList & operator= (TIntrusiveList &&Other)
ElementType * PeekHead ()
ElementType * PopHead ()
bool Remove (ElementType *Element)
Private Attributes
ElementType * Head = nullptr
ElementType * Tail = nullptr
Detailed Description
template<typename TypeTraits>
class TIntrusiveList< TypeTraits >
Definition at line 48 of file IoContainers.h.
Member Typedef Documentation
ElementType
template<typename TypeTraits> using TIntrusiveList< TypeTraits >::ElementType = typename TypeTraits::ElementType
Definition at line 51 of file IoContainers.h.
FConstIterator
template<typename TypeTraits> using TIntrusiveList< TypeTraits >::FConstIterator = UE::Private::TIntrusiveListIterator<const TypeTraits>
Definition at line 53 of file IoContainers.h.
FIterator
template<typename TypeTraits> using TIntrusiveList< TypeTraits >::FIterator = UE::Private::TIntrusiveListIterator<TypeTraits>
Definition at line 52 of file IoContainers.h.
Constructor & Destructor Documentation
TIntrusiveList() [1/4]
template<typename TypeTraits> TIntrusiveList< TypeTraits >::TIntrusiveList () default
TIntrusiveList() [2/4]
template<typename TypeTraits> TIntrusiveList< TypeTraits >::TIntrusiveList (const TIntrusiveList< TypeTraits > &) delete
TIntrusiveList() [3/4]
template<typename TypeTraits> TIntrusiveList< TypeTraits >::TIntrusiveList (TIntrusiveList< TypeTraits > && Other) inline
Definition at line 57 of file IoContainers.h.
TIntrusiveList() [4/4]
template<typename TypeTraits> TIntrusiveList< TypeTraits >::TIntrusiveList (ElementType * Element) inline explicit
Definition at line 63 of file IoContainers.h.
Member Function Documentation
AddTail() [1/3]
template<typename TypeTraits> void TIntrusiveList< TypeTraits >::AddTail (ElementType * Element) inline
Definition at line 77 of file IoContainers.h.
Referenced by TIntrusiveList< FIoEncodedBlockRequest >::AddTail(), UE::FPlatformIoDispatcherBase::CompleteEncodedBlockRequest(), UE::FIoFileBlockRequestQueue::Enqueue(), UE::FPlatformIoDispatcherBase::EnqueueBlocksToDecode(), UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), UE::FIoFileBlockRequestQueue::Reprioritize(), and UE::FPlatformIoDispatcherBase::ScatterGather().
AddTail() [2/3]
template<typename TypeTraits> void TIntrusiveList< TypeTraits >::AddTail (ElementType * First, ElementType * Last) inline
Definition at line 94 of file IoContainers.h.
AddTail() [3/3]
template<typename TypeTraits> void TIntrusiveList< TypeTraits >::AddTail (TIntrusiveList< TypeTraits > && Other) inline
Definition at line 113 of file IoContainers.h.
begin() [1/2]
template<typename TypeTraits> FIterator TIntrusiveList< TypeTraits >::begin () inline
Definition at line 185 of file IoContainers.h.
begin() [2/2]
template<typename TypeTraits> FConstIterator TIntrusiveList< TypeTraits >::begin () const inline
Definition at line 186 of file IoContainers.h.
end() [1/2]
template<typename TypeTraits> FIterator TIntrusiveList< TypeTraits >::end () inline
Definition at line 187 of file IoContainers.h.
end() [2/2]
template<typename TypeTraits> FConstIterator TIntrusiveList< TypeTraits >::end () const inline
Definition at line 188 of file IoContainers.h.
GetHead() [1/2]
template<typename TypeTraits> ElementType * TIntrusiveList< TypeTraits >::GetHead () inline
Definition at line 180 of file IoContainers.h.
GetHead() [2/2]
template<typename TypeTraits> const ElementType * TIntrusiveList< TypeTraits >::GetHead () const inline
Definition at line 181 of file IoContainers.h.
GetTail() [1/2]
template<typename TypeTraits> ElementType * TIntrusiveList< TypeTraits >::GetTail () inline
Definition at line 182 of file IoContainers.h.
GetTail() [2/2]
template<typename TypeTraits> const ElementType * TIntrusiveList< TypeTraits >::GetTail () const inline
Definition at line 183 of file IoContainers.h.
IsEmpty()
template<typename TypeTraits> bool TIntrusiveList< TypeTraits >::IsEmpty () const inline
Definition at line 179 of file IoContainers.h.
Referenced by UE::FIoFileBlockRequestQueue::GetByOffset(), UE::FIoFileBlockRequestQueue::GetByOffset(), UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), and TIntrusiveList< FIoEncodedBlockRequest >::Remove().
operator=() [1/2]
template<typename TypeTraits> TIntrusiveList & TIntrusiveList< TypeTraits >::operator= (const TIntrusiveList< TypeTraits > &) delete
operator=() [2/2]
template<typename TypeTraits> TIntrusiveList & TIntrusiveList< TypeTraits >::operator= (TIntrusiveList< TypeTraits > && Other) inline
Definition at line 69 of file IoContainers.h.
PeekHead()
template<typename TypeTraits> ElementType * TIntrusiveList< TypeTraits >::PeekHead () inline
Definition at line 138 of file IoContainers.h.
Referenced by UE::FIoFileBlockRequestQueue::GetByOffset().
PopHead()
template<typename TypeTraits> ElementType * TIntrusiveList< TypeTraits >::PopHead () inline
Definition at line 122 of file IoContainers.h.
Referenced by UE::FPlatformIoDispatcherBase::CompleteEncodedBlockRequest(), UE::FPlatformIoDispatcherBase::EnqueueBlocksToDecode(), UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), and TIntrusiveList< FIoEncodedBlockRequest >::Remove().
Remove()
template<typename TypeTraits> bool TIntrusiveList< TypeTraits >::Remove (ElementType * Element) inline
Definition at line 143 of file IoContainers.h.
Referenced by UE::FIoFileBlockRequestQueue::GetByOffset().
Field Documentation
Head
template<typename TypeTraits> ElementType* TIntrusiveList< TypeTraits >::Head = nullptr private
Definition at line 191 of file IoContainers.h.
Tail
template<typename TypeTraits> ElementType* TIntrusiveList< TypeTraits >::Tail = nullptr private
Definition at line 192 of file IoContainers.h.
The documentation for this class was generated from the following file:
IoContainers.h