Unreal Engine 5.6 C++ API: FWidgetBlueprintEditorUtils Class Reference
FWidgetBlueprintEditorUtils Class Reference
#include "WidgetBlueprintEditorUtils.h"
Data Structures
struct FCreateWidgetFromBlueprintParams
struct FUsableWidgetClassResult
struct FWidgetThumbnailProperties
Public Types
enum class EDeleteWidgetWarningType { WarnAndAskUser , DeleteSilently }
enum class EReplaceWidgetNamingMethod { MaintainNameAndReferences , MaintainNameAndReferencesForUnmatchingClass , UseNewGeneratedName }
Public Member Functions
void IsUsableWidgetClass (const FAssetData &WidgetAsset)
UE_DEPRECATED (5.3, "This function has been deprecated. Use the version of IsUsableWidgetClass that takes a second argument of TSharedRef<FWidgetBlueprintEditor>.") static bool IsUsableWidgetClass(const UClass *WidgetClass)
UE_DEPRECATED (5.3, "This function has been deprecated. Use the version of IsUsableWidgetClass that takes a second argument of TSharedRef<FWidgetBlueprintEditor>.") static TValueOrError< FUsableWidgetClassResult
UE_DEPRECATED (5.6, "FWidgetBlueprintEditorUtils::DeleteWidgets no longer takes in the BlueprintEditor, use the version without it instead") static void DeleteWidgets(TSharedRef< FWidgetBlueprintEditor > BlueprintEditor
Static Public Member Functions
static bool CanPasteWidgetsExtension (TSet< FWidgetReference > SelectedWidgets)
static EDesignPreviewSizeMode ConvertThumbnailSizeModeToDesignerSizeMode (EThumbnailPreviewSizeMode ThumbnailSizeMode, UUserWidget *WidgetInstance)
static void CopyWidgets (UWidgetBlueprint *BP, TSet< FWidgetReference > Widgets)
static UUserWidget * CreateUserWidgetFromBlueprint (UObject *Outer, UWidgetBlueprint *BP, const FCreateWidgetFromBlueprintParams &Params)
static void CreateWidgetContextMenu (FMenuBuilder &MenuBuilder, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, FVector2D TargetLocation)
static void CutWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, TSet< FWidgetReference > Widgets)
static void DeleteWidgets (UWidgetBlueprint *BP, TSet< UWidget * > Widgets, EDeleteWidgetWarningType WarningType)
static void DestroyUserWidget (UUserWidget *UserWidget)
Performs cleanup on the specified UserWidget.
static bool DoesClipboardTextContainWidget (UWidgetBlueprint *BP)
static TOptional< FWidgetThumbnailProperties > DrawSWidgetInRenderTarget (UUserWidget *WidgetInstance, UTextureRenderTarget2D *RenderTarget2D)
static TOptional< FWidgetThumbnailProperties > DrawSWidgetInRenderTargetForThumbnail (UUserWidget *WidgetInstance, FRenderTarget *RenderTarget2D, FVector2D ThumbnailSize, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode=EThumbnailPreviewSizeMode::MatchDesignerMode)
static TOptional< FWidgetThumbnailProperties > DrawSWidgetInRenderTargetForThumbnail (UUserWidget *WidgetInstance, UTextureRenderTarget2D *RenderTarget2D, FVector2D ThumbnailSize, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode)
static TArray< UWidget * > DuplicateWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, TSet< FWidgetReference > Widgets)
static void ExportPropertiesToText (UObject *Object, TMap< FName, FString > &ExportedProperties)
Exports the individual properties of an object to text and stores them in a map.
static void ExportWidgetsToText (TArray< UWidget * > WidgetsToExport, FString &ExportedText)
static void FindAllAncestorNamedSlotHostWidgetsForContent (TArray< FWidgetReference > &OutSlotHostWidgets, UWidget *WidgetTemplate, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor)
static UWidgetTree * FindLatestWidgetTree (UWidgetBlueprint *Blueprint, UUserWidget *UserWidget)
static TScriptInterface< INamedSlotInterface > FindNamedSlotHostForContent (UWidget *WidgetTemplate, UWidgetTree *WidgetTree)
static UWidget * FindNamedSlotHostWidgetForContent (UWidget *WidgetTemplate, UWidgetTree *WidgetTree)
static FText GetPaletteCategory (const FAssetData &WidgetAsset, const TSubclassOf< UWidget > NativeClass)
static FText GetPaletteCategory (const TSubclassOf< UWidget > Widget)
static UWidgetEditingProjectSettings * GetRelevantMutableSettings (TWeakPtr< FWidgetBlueprintEditor > CurrentEditor)
static const UWidgetEditingProjectSettings * GetRelevantSettings (TWeakPtr< FWidgetBlueprintEditor > CurrentEditor)
static TTuple< float, FVector2D > GetThumbnailImageScaleAndOffset (FVector2D WidgetSize, FVector2D ThumbnailSize)
static UWidgetBlueprint * GetWidgetBlueprintFromWidget (const UWidget *Widget)
static TTuple< FVector2D, FVector2D > GetWidgetPreviewAreaAndSize (UUserWidget *UserWidget, FVector2D DesiredSize, FVector2D PreviewSize, EDesignPreviewSizeMode ThumbnailSizeMode, TOptional< FVector2D > ThumbnailCustomSize)
static float GetWidgetPreviewDPIScale (UUserWidget *UserWidget, FVector2D PreviewSize)
static FVector2D GetWidgetPreviewUnScaledCustomSize (FVector2D DesiredSize, UUserWidget *UserWidget, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode=EThumbnailPreviewSizeMode::MatchDesignerMode)
static UWidget * GetWidgetTemplateFromDragDrop (UWidgetBlueprint *Blueprint, UWidgetTree *RootWidgetTree, TSharedPtr< FDragDropOperation > &DragDropOp)
static void ImportPropertiesFromText (UObject *Object, const TMap< FName, FString > &ExportedProperties)
Attempts to import any property in the map and apply it to a property with the same name on the object.
static void ImportWidgetsFromText (UWidgetBlueprint *BP, const FString &TextToImport, TSet< UWidget * > &ImportedWidgetSet, TMap< FName, UWidgetSlotPair * > &PastedExtraSlotData)
static bool IsAnySelectedWidgetLocked (TSet< FWidgetReference > SelectedWidgets)
static bool IsBindWidgetAnimProperty (const FProperty *InProperty)
static bool IsBindWidgetAnimProperty (const FProperty *InProperty, bool &bIsOptional)
static bool IsBindWidgetProperty (const FProperty *InProperty)
static bool IsBindWidgetProperty (const FProperty *InProperty, bool &bIsOptional)
static TValueOrError< FUsableWidgetClassResult, void > IsUsableWidgetClass (const FAssetData &WidgetAsset, TSharedRef< FWidgetBlueprintEditor > InCurrentActiveBlueprintEditor)
static bool IsUsableWidgetClass (const UClass *WidgetClass, TSharedRef< FWidgetBlueprintEditor > InCurrentActiveBlueprintEditor)
static TArray< UWidget * > PasteWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, FWidgetReference ParentWidget, FName SlotName, FVector2D PasteLocation)
static bool RemoveNamedSlotHostContent (UWidget *WidgetTemplate, TScriptInterface< INamedSlotInterface > NamedSlotHost)
static bool RenameWidget (TSharedRef< class FWidgetBlueprintEditor > BlueprintEditor, const FName &OldObjectName, const FString &NewDisplayName)
static void ReplaceDesiredFocus (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, const FName &OldName, const FName &NewName)
static void ReplaceDesiredFocus (UWidgetBlueprint *Blueprint, const FName &OldName, const FName &NewName)
static bool ReplaceNamedSlotHostContent (UWidget *WidgetTemplate, TScriptInterface< INamedSlotInterface > NamedSlotHost, UWidget *NewContentWidget)
static void ReplaceWidgets (UWidgetBlueprint *BP, TSet< UWidget * > Widgets, UClass *WidgetClass, EReplaceWidgetNamingMethod NewWidgetNamingMethod)
static TSet< UWidget * > ResolveWidgetTemplates (const TSet< FWidgetReference > &Widgets)
static void SetDesiredFocus (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, const FName DesiredFocusWidgetName)
static void SetDesiredFocus (UWidgetBlueprint *Blueprint, const FName &DesiredFocusWidgetName)
static void SetTextureAsAssetThumbnail (UWidgetBlueprint *WidgetBlueprint, UTexture2D *ThumbnailTexture)
static bool ShouldPreventDropOnTargetExtensions (const UWidget *Target, const TSharedPtr< FDragDropOperation > &DragDropOp, FText &OutFailureText)
static int32 UpdateHittestGrid (FHittestGrid &HitTestGrid, TSharedRef< SWindow > Window, float Scale, FVector2D DrawSize, float DeltaTime)
static bool VerifyWidgetRename (TSharedRef< class FWidgetBlueprintEditor > BlueprintEditor, FWidgetReference Widget, const FText &NewName, FText &OutErrorMessage)
Data Fields
UWidgetBlueprint * BP
UWidgetBlueprint TSet< FWidgetReference > bool bSilentDelete = false)
UWidgetBlueprint TSet< FWidgetReference > Widgets
Static Private Member Functions
static void BuildReplaceWithMenu (FMenuBuilder &Menu, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, TSet< FWidgetReference > Widgets)
static void BuildWrapWithMenu (FMenuBuilder &Menu, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, TSet< FWidgetReference > Widgets)
static bool CanBeReplacedWithTemplate (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, FWidgetReference Widget)
static bool CanOpenSelectedWidgetsForEdit (TSet< FWidgetReference > SelectedWidgets)
static FString CopyWidgetsInternal (UWidgetBlueprint *BP, TSet< FWidgetReference > Widgets)
static bool DisplayPasteWarningAndEarlyExit ()
static TOptional< FWidgetThumbnailProperties > DrawSWidgetInRenderTargetInternal (UUserWidget *WidgetInstance, FRenderTarget *RenderTarget2D, UTextureRenderTarget2D *TextureRenderTarget, FVector2D ThumbnailSize, bool bIsForThumbnail, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode)
static void ExecuteOpenSelectedWidgetsForEdit (TSet< FWidgetReference > SelectedWidgets)
static bool FindAndRemoveNamedSlotContent (UWidget *WidgetTemplate, UWidgetTree *WidgetTree)
static FString FindNextValidName (UWidgetTree *WidgetTree, const FString &Name)
static void FindUsedVariablesForWidgets (const TSet< UWidget * > &Widgets, const UWidgetBlueprint *BP, TArray< UWidget * > &UsedVariables, TArray< FText > &WidgetNames, bool bIncludeVariablesOnChildren)
static bool IsDesiredFocusWidget (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidget *Widget)
static bool IsDesiredFocusWidget (UWidgetBlueprint *Blueprint, UWidget *Widget)
static TArray< UWidget * > PasteWidgetsInternal (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, const FString &TextToImport, FWidgetReference ParentWidget, FName SlotName, FVector2D PasteLocation, bool bForceSibling, bool &TransactionSuccesful)
static FWidgetObjectTextFactory ProcessImportedText (UWidgetBlueprint *BP, const FString &TextToImport, UPackage *&TempPackage)
static void ReplaceWidgetWithChildren (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, FWidgetReference Widget)
static void ReplaceWidgetWithNamedSlot (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, FWidgetReference Widget, FName NamedSlot)
static void ReplaceWidgetWithSelectedTemplate (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, FWidgetReference Widget)
static bool ShouldContinueDeleteOperation (UWidgetBlueprint *BP, const TArray< FText > &WidgetNames)
static bool ShouldContinueReplaceOperation (UWidgetBlueprint *BP, const TArray< FText > &WidgetNames)
static void WrapWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint *BP, TSet< FWidgetReference > Widgets, UClass *WidgetClass)
Detailed Description
Definition at line 24 of file WidgetBlueprintEditorUtils.h.
Member Enumeration Documentation
EDeleteWidgetWarningType
enum class FWidgetBlueprintEditorUtils::EDeleteWidgetWarningType strong
Enumerator
WarnAndAskUser
DeleteSilently
Definition at line 73 of file WidgetBlueprintEditorUtils.h.
EReplaceWidgetNamingMethod
enum class FWidgetBlueprintEditorUtils::EReplaceWidgetNamingMethod strong
Enumerator
MaintainNameAndReferences
MaintainNameAndReferencesForUnmatchingClass
UseNewGeneratedName
Definition at line 56 of file WidgetBlueprintEditorUtils.h.
Member Function Documentation
BuildReplaceWithMenu()
void FWidgetBlueprintEditorUtils::BuildReplaceWithMenu (FMenuBuilder & Menu, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, TSet< FWidgetReference > Widgets) static private
References BP, BuildReplaceWithMenu(), Menu, and Widgets.
Referenced by BuildReplaceWithMenu().
BuildWrapWithMenu()
void FWidgetBlueprintEditorUtils::BuildWrapWithMenu (FMenuBuilder & Menu, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, TSet< FWidgetReference > Widgets) static private
References BP, BuildWrapWithMenu(), Menu, and Widgets.
Referenced by BuildWrapWithMenu().
CanBeReplacedWithTemplate()
bool FWidgetBlueprintEditorUtils::CanBeReplacedWithTemplate (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, FWidgetReference Widget) static private
References BP, and CanBeReplacedWithTemplate().
Referenced by CanBeReplacedWithTemplate().
CanOpenSelectedWidgetsForEdit()
bool FWidgetBlueprintEditorUtils::CanOpenSelectedWidgetsForEdit (TSet< FWidgetReference > SelectedWidgets) static private
References CanOpenSelectedWidgetsForEdit().
Referenced by CanOpenSelectedWidgetsForEdit().
CanPasteWidgetsExtension()
bool FWidgetBlueprintEditorUtils::CanPasteWidgetsExtension (TSet< FWidgetReference > SelectedWidgets) static
ConvertThumbnailSizeModeToDesignerSizeMode()
EDesignPreviewSizeMode FWidgetBlueprintEditorUtils::ConvertThumbnailSizeModeToDesignerSizeMode (EThumbnailPreviewSizeMode ThumbnailSizeMode, UUserWidget * WidgetInstance) static
References ConvertThumbnailSizeModeToDesignerSizeMode().
Referenced by ConvertThumbnailSizeModeToDesignerSizeMode().
CopyWidgets()
void FWidgetBlueprintEditorUtils::CopyWidgets (UWidgetBlueprint * BP, TSet< FWidgetReference > Widgets) static
References BP, and Widgets.
CopyWidgetsInternal()
FString FWidgetBlueprintEditorUtils::CopyWidgetsInternal (UWidgetBlueprint * BP, TSet< FWidgetReference > Widgets) static private
References BP, CopyWidgetsInternal(), and Widgets.
Referenced by CopyWidgetsInternal().
CreateUserWidgetFromBlueprint()
UUserWidget * FWidgetBlueprintEditorUtils::CreateUserWidgetFromBlueprint (UObject * Outer, UWidgetBlueprint * BP, const FCreateWidgetFromBlueprintParams & Params) static
References BP, Outer, and Params.
CreateWidgetContextMenu()
void FWidgetBlueprintEditorUtils::CreateWidgetContextMenu (FMenuBuilder & MenuBuilder, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, FVector2D TargetLocation) static
CutWidgets()
void FWidgetBlueprintEditorUtils::CutWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, TSet< FWidgetReference > Widgets) static
References BP, and Widgets.
DeleteWidgets()
void FWidgetBlueprintEditorUtils::DeleteWidgets (UWidgetBlueprint * BP, TSet< UWidget * > Widgets, EDeleteWidgetWarningType WarningType) static
References BP, and Widgets.
DestroyUserWidget()
void FWidgetBlueprintEditorUtils::DestroyUserWidget (UUserWidget * UserWidget) static
Performs cleanup on the specified UserWidget.
DisplayPasteWarningAndEarlyExit()
bool FWidgetBlueprintEditorUtils::DisplayPasteWarningAndEarlyExit () static private
References DisplayPasteWarningAndEarlyExit().
Referenced by DisplayPasteWarningAndEarlyExit().
DoesClipboardTextContainWidget()
bool FWidgetBlueprintEditorUtils::DoesClipboardTextContainWidget (UWidgetBlueprint * BP) static
References BP, and DoesClipboardTextContainWidget().
Referenced by DoesClipboardTextContainWidget().
DrawSWidgetInRenderTarget()
TOptional< FWidgetThumbnailProperties > FWidgetBlueprintEditorUtils::DrawSWidgetInRenderTarget (UUserWidget * WidgetInstance, UTextureRenderTarget2D * RenderTarget2D) static
References DrawSWidgetInRenderTarget().
Referenced by DrawSWidgetInRenderTarget().
DrawSWidgetInRenderTargetForThumbnail() [1/2]
TOptional< FWidgetThumbnailProperties > FWidgetBlueprintEditorUtils::DrawSWidgetInRenderTargetForThumbnail (UUserWidget * WidgetInstance, FRenderTarget * RenderTarget2D, FVector2D ThumbnailSize, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode = EThumbnailPreviewSizeMode::MatchDesignerMode) static
References DrawSWidgetInRenderTargetForThumbnail().
Referenced by DrawSWidgetInRenderTargetForThumbnail(), and DrawSWidgetInRenderTargetForThumbnail().
DrawSWidgetInRenderTargetForThumbnail() [2/2]
TOptional< FWidgetThumbnailProperties > FWidgetBlueprintEditorUtils::DrawSWidgetInRenderTargetForThumbnail (UUserWidget * WidgetInstance, UTextureRenderTarget2D * RenderTarget2D, FVector2D ThumbnailSize, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode) static
References DrawSWidgetInRenderTargetForThumbnail().
DrawSWidgetInRenderTargetInternal()
TOptional< FWidgetThumbnailProperties > FWidgetBlueprintEditorUtils::DrawSWidgetInRenderTargetInternal (UUserWidget * WidgetInstance, FRenderTarget * RenderTarget2D, UTextureRenderTarget2D * TextureRenderTarget, FVector2D ThumbnailSize, bool bIsForThumbnail, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode) static private
References DrawSWidgetInRenderTargetInternal().
Referenced by DrawSWidgetInRenderTargetInternal().
DuplicateWidgets()
TArray< UWidget * > FWidgetBlueprintEditorUtils::DuplicateWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, TSet< FWidgetReference > Widgets) static
References BP, and Widgets.
ExecuteOpenSelectedWidgetsForEdit()
void FWidgetBlueprintEditorUtils::ExecuteOpenSelectedWidgetsForEdit (TSet< FWidgetReference > SelectedWidgets) static private
References ExecuteOpenSelectedWidgetsForEdit().
Referenced by ExecuteOpenSelectedWidgetsForEdit().
ExportPropertiesToText()
void FWidgetBlueprintEditorUtils::ExportPropertiesToText (UObject * Object, TMap< FName, FString > & ExportedProperties) static
Exports the individual properties of an object to text and stores them in a map.
References ExportPropertiesToText(), and Object.
Referenced by ExportPropertiesToText().
ExportWidgetsToText()
void FWidgetBlueprintEditorUtils::ExportWidgetsToText (TArray< UWidget * > WidgetsToExport, FString & ExportedText) static
References ExportWidgetsToText().
Referenced by ExportWidgetsToText().
FindAllAncestorNamedSlotHostWidgetsForContent()
void FWidgetBlueprintEditorUtils::FindAllAncestorNamedSlotHostWidgetsForContent (TArray< FWidgetReference > & OutSlotHostWidgets, UWidget * WidgetTemplate, TSharedRef< FWidgetBlueprintEditor > BlueprintEditor) static
References FindAllAncestorNamedSlotHostWidgetsForContent().
Referenced by FindAllAncestorNamedSlotHostWidgetsForContent().
FindAndRemoveNamedSlotContent()
bool FWidgetBlueprintEditorUtils::FindAndRemoveNamedSlotContent (UWidget * WidgetTemplate, UWidgetTree * WidgetTree) static private
References FindAndRemoveNamedSlotContent().
Referenced by FindAndRemoveNamedSlotContent().
FindLatestWidgetTree()
UWidgetTree * FWidgetBlueprintEditorUtils::FindLatestWidgetTree (UWidgetBlueprint * Blueprint, UUserWidget * UserWidget) static
References FindLatestWidgetTree().
Referenced by FindLatestWidgetTree().
FindNamedSlotHostForContent()
TScriptInterface< INamedSlotInterface > FWidgetBlueprintEditorUtils::FindNamedSlotHostForContent (UWidget * WidgetTemplate, UWidgetTree * WidgetTree) static
References FindNamedSlotHostForContent().
Referenced by FindNamedSlotHostForContent().
FindNamedSlotHostWidgetForContent()
UWidget * FWidgetBlueprintEditorUtils::FindNamedSlotHostWidgetForContent (UWidget * WidgetTemplate, UWidgetTree * WidgetTree) static
References FindNamedSlotHostWidgetForContent().
Referenced by FindNamedSlotHostWidgetForContent().
FindNextValidName()
FString FWidgetBlueprintEditorUtils::FindNextValidName (UWidgetTree * WidgetTree, const FString & Name) static private
References FindNextValidName(), and Name.
Referenced by FindNextValidName().
FindUsedVariablesForWidgets()
void FWidgetBlueprintEditorUtils::FindUsedVariablesForWidgets (const TSet< UWidget * > & Widgets, const UWidgetBlueprint * BP, TArray< UWidget * > & UsedVariables, TArray< FText > & WidgetNames, bool bIncludeVariablesOnChildren) static private
References BP, FindUsedVariablesForWidgets(), and Widgets.
Referenced by FindUsedVariablesForWidgets().
GetPaletteCategory() [1/2]
FText FWidgetBlueprintEditorUtils::GetPaletteCategory (const FAssetData & WidgetAsset, const TSubclassOf< UWidget > NativeClass) static
References GetPaletteCategory().
GetPaletteCategory() [2/2]
FText FWidgetBlueprintEditorUtils::GetPaletteCategory (const TSubclassOf< UWidget > Widget) static
References GetPaletteCategory().
Referenced by GetPaletteCategory(), and GetPaletteCategory().
GetRelevantMutableSettings()
UWidgetEditingProjectSettings * FWidgetBlueprintEditorUtils::GetRelevantMutableSettings (TWeakPtr< FWidgetBlueprintEditor > CurrentEditor) static
References GetRelevantMutableSettings().
Referenced by GetRelevantMutableSettings().
GetRelevantSettings()
const UWidgetEditingProjectSettings * FWidgetBlueprintEditorUtils::GetRelevantSettings (TWeakPtr< FWidgetBlueprintEditor > CurrentEditor) static
References GetRelevantSettings().
Referenced by GetRelevantSettings().
GetThumbnailImageScaleAndOffset()
TTuple< float, FVector2D > FWidgetBlueprintEditorUtils::GetThumbnailImageScaleAndOffset (FVector2D WidgetSize, FVector2D ThumbnailSize) static
References GetThumbnailImageScaleAndOffset().
Referenced by GetThumbnailImageScaleAndOffset().
GetWidgetBlueprintFromWidget()
UWidgetBlueprint * FWidgetBlueprintEditorUtils::GetWidgetBlueprintFromWidget (const UWidget * Widget) static
References GetWidgetBlueprintFromWidget().
Referenced by GetWidgetBlueprintFromWidget().
GetWidgetPreviewAreaAndSize()
TTuple< FVector2D, FVector2D > FWidgetBlueprintEditorUtils::GetWidgetPreviewAreaAndSize (UUserWidget * UserWidget, FVector2D DesiredSize, FVector2D PreviewSize, EDesignPreviewSizeMode ThumbnailSizeMode, TOptional< FVector2D > ThumbnailCustomSize) static
References GetWidgetPreviewAreaAndSize().
Referenced by GetWidgetPreviewAreaAndSize().
GetWidgetPreviewDPIScale()
float FWidgetBlueprintEditorUtils::GetWidgetPreviewDPIScale (UUserWidget * UserWidget, FVector2D PreviewSize) static
References GetWidgetPreviewDPIScale().
Referenced by GetWidgetPreviewDPIScale().
GetWidgetPreviewUnScaledCustomSize()
FVector2D FWidgetBlueprintEditorUtils::GetWidgetPreviewUnScaledCustomSize (FVector2D DesiredSize, UUserWidget * UserWidget, TOptional< FVector2D > ThumbnailCustomSize, EThumbnailPreviewSizeMode ThumbnailSizeMode = EThumbnailPreviewSizeMode::MatchDesignerMode) static
References GetWidgetPreviewUnScaledCustomSize().
Referenced by GetWidgetPreviewUnScaledCustomSize().
GetWidgetTemplateFromDragDrop()
UWidget * FWidgetBlueprintEditorUtils::GetWidgetTemplateFromDragDrop (UWidgetBlueprint * Blueprint, UWidgetTree * RootWidgetTree, TSharedPtr< FDragDropOperation > & DragDropOp) static
ImportPropertiesFromText()
void FWidgetBlueprintEditorUtils::ImportPropertiesFromText (UObject * Object, const TMap< FName, FString > & ExportedProperties) static
Attempts to import any property in the map and apply it to a property with the same name on the object.
References ImportPropertiesFromText(), and Object.
Referenced by ImportPropertiesFromText().
ImportWidgetsFromText()
void FWidgetBlueprintEditorUtils::ImportWidgetsFromText (UWidgetBlueprint * BP, const FString & TextToImport, TSet< UWidget * > & ImportedWidgetSet, TMap< FName, UWidgetSlotPair * > & PastedExtraSlotData) static
References BP, and ImportWidgetsFromText().
Referenced by ImportWidgetsFromText().
IsAnySelectedWidgetLocked()
bool FWidgetBlueprintEditorUtils::IsAnySelectedWidgetLocked (TSet< FWidgetReference > SelectedWidgets) static
IsBindWidgetAnimProperty() [1/2]
bool FWidgetBlueprintEditorUtils::IsBindWidgetAnimProperty (const FProperty * InProperty) static
IsBindWidgetAnimProperty() [2/2]
bool FWidgetBlueprintEditorUtils::IsBindWidgetAnimProperty (const FProperty * InProperty, bool & bIsOptional) static
IsBindWidgetProperty() [1/2]
bool FWidgetBlueprintEditorUtils::IsBindWidgetProperty (const FProperty * InProperty) static
IsBindWidgetProperty() [2/2]
bool FWidgetBlueprintEditorUtils::IsBindWidgetProperty (const FProperty * InProperty, bool & bIsOptional) static
IsDesiredFocusWidget() [1/2]
bool FWidgetBlueprintEditorUtils::IsDesiredFocusWidget (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidget * Widget) static private
References IsDesiredFocusWidget().
Referenced by IsDesiredFocusWidget(), and IsDesiredFocusWidget().
IsDesiredFocusWidget() [2/2]
bool FWidgetBlueprintEditorUtils::IsDesiredFocusWidget (UWidgetBlueprint * Blueprint, UWidget * Widget) static private
References IsDesiredFocusWidget().
IsUsableWidgetClass() [1/3]
void FWidgetBlueprintEditorUtils::IsUsableWidgetClass (const FAssetData & WidgetAsset)
References IsUsableWidgetClass().
Referenced by IsUsableWidgetClass(), IsUsableWidgetClass(), IsUsableWidgetClass(), and UE_DEPRECATED().
IsUsableWidgetClass() [2/3]
TValueOrError< FUsableWidgetClassResult, void > FWidgetBlueprintEditorUtils::IsUsableWidgetClass (const FAssetData & WidgetAsset, TSharedRef< FWidgetBlueprintEditor > InCurrentActiveBlueprintEditor) static
References IsUsableWidgetClass().
IsUsableWidgetClass() [3/3]
bool FWidgetBlueprintEditorUtils::IsUsableWidgetClass (const UClass * WidgetClass, TSharedRef< FWidgetBlueprintEditor > InCurrentActiveBlueprintEditor) static
References IsUsableWidgetClass().
PasteWidgets()
TArray< UWidget * > FWidgetBlueprintEditorUtils::PasteWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, FWidgetReference ParentWidget, FName SlotName, FVector2D PasteLocation) static
References BP.
PasteWidgetsInternal()
TArray< UWidget * > FWidgetBlueprintEditorUtils::PasteWidgetsInternal (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, const FString & TextToImport, FWidgetReference ParentWidget, FName SlotName, FVector2D PasteLocation, bool bForceSibling, bool & TransactionSuccesful) static private
References BP, and PasteWidgetsInternal().
Referenced by PasteWidgetsInternal().
ProcessImportedText()
FWidgetObjectTextFactory FWidgetBlueprintEditorUtils::ProcessImportedText (UWidgetBlueprint * BP, const FString & TextToImport, UPackage *& TempPackage) static private
References BP, and ProcessImportedText().
Referenced by ProcessImportedText().
RemoveNamedSlotHostContent()
bool FWidgetBlueprintEditorUtils::RemoveNamedSlotHostContent (UWidget * WidgetTemplate, TScriptInterface< INamedSlotInterface > NamedSlotHost) static
References RemoveNamedSlotHostContent().
Referenced by RemoveNamedSlotHostContent().
RenameWidget()
bool FWidgetBlueprintEditorUtils::RenameWidget (TSharedRef< class FWidgetBlueprintEditor > BlueprintEditor, const FName & OldObjectName, const FString & NewDisplayName) static
ReplaceDesiredFocus() [1/2]
void FWidgetBlueprintEditorUtils::ReplaceDesiredFocus (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, const FName & OldName, const FName & NewName) static
ReplaceDesiredFocus() [2/2]
void FWidgetBlueprintEditorUtils::ReplaceDesiredFocus (UWidgetBlueprint * Blueprint, const FName & OldName, const FName & NewName) static
ReplaceNamedSlotHostContent()
bool FWidgetBlueprintEditorUtils::ReplaceNamedSlotHostContent (UWidget * WidgetTemplate, TScriptInterface< INamedSlotInterface > NamedSlotHost, UWidget * NewContentWidget) static
References ReplaceNamedSlotHostContent().
Referenced by ReplaceNamedSlotHostContent().
ReplaceWidgets()
void FWidgetBlueprintEditorUtils::ReplaceWidgets (UWidgetBlueprint * BP, TSet< UWidget * > Widgets, UClass * WidgetClass, EReplaceWidgetNamingMethod NewWidgetNamingMethod) static
References BP, and Widgets.
ReplaceWidgetWithChildren()
void FWidgetBlueprintEditorUtils::ReplaceWidgetWithChildren (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, FWidgetReference Widget) static private
References BP, and ReplaceWidgetWithChildren().
Referenced by ReplaceWidgetWithChildren().
ReplaceWidgetWithNamedSlot()
void FWidgetBlueprintEditorUtils::ReplaceWidgetWithNamedSlot (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, FWidgetReference Widget, FName NamedSlot) static private
References BP, and ReplaceWidgetWithNamedSlot().
Referenced by ReplaceWidgetWithNamedSlot().
ReplaceWidgetWithSelectedTemplate()
void FWidgetBlueprintEditorUtils::ReplaceWidgetWithSelectedTemplate (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, FWidgetReference Widget) static private
References BP, and ReplaceWidgetWithSelectedTemplate().
Referenced by ReplaceWidgetWithSelectedTemplate().
ResolveWidgetTemplates()
TSet< UWidget * > FWidgetBlueprintEditorUtils::ResolveWidgetTemplates (const TSet< FWidgetReference > & Widgets) static
References ResolveWidgetTemplates(), and Widgets.
Referenced by ResolveWidgetTemplates().
SetDesiredFocus() [1/2]
void FWidgetBlueprintEditorUtils::SetDesiredFocus (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, const FName DesiredFocusWidgetName) static
SetDesiredFocus() [2/2]
void FWidgetBlueprintEditorUtils::SetDesiredFocus (UWidgetBlueprint * Blueprint, const FName & DesiredFocusWidgetName) static
SetTextureAsAssetThumbnail()
void FWidgetBlueprintEditorUtils::SetTextureAsAssetThumbnail (UWidgetBlueprint * WidgetBlueprint, UTexture2D * ThumbnailTexture) static
References SetTextureAsAssetThumbnail().
Referenced by SetTextureAsAssetThumbnail().
ShouldContinueDeleteOperation()
bool FWidgetBlueprintEditorUtils::ShouldContinueDeleteOperation (UWidgetBlueprint * BP, const TArray< FText > & WidgetNames) static private
References BP, and ShouldContinueDeleteOperation().
Referenced by ShouldContinueDeleteOperation().
ShouldContinueReplaceOperation()
bool FWidgetBlueprintEditorUtils::ShouldContinueReplaceOperation (UWidgetBlueprint * BP, const TArray< FText > & WidgetNames) static private
References BP, and ShouldContinueReplaceOperation().
Referenced by ShouldContinueReplaceOperation().
ShouldPreventDropOnTargetExtensions()
bool FWidgetBlueprintEditorUtils::ShouldPreventDropOnTargetExtensions (const UWidget * Target, const TSharedPtr< FDragDropOperation > & DragDropOp, FText & OutFailureText) static
References Target.
UE_DEPRECATED() [1/3]
FWidgetBlueprintEditorUtils::UE_DEPRECATED (5. 3, "This function has been deprecated. Use the version of IsUsableWidgetClass that takes a second argument of TSharedRef<FWidgetBlueprintEditor>.") const
References IsUsableWidgetClass().
UE_DEPRECATED() [2/3]
FWidgetBlueprintEditorUtils::UE_DEPRECATED (5. 3, "This function has been deprecated. Use the version of IsUsableWidgetClass that takes a second argument of TSharedRef<FWidgetBlueprintEditor>.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FWidgetBlueprintEditorUtils::UE_DEPRECATED (5. 6, "FWidgetBlueprintEditorUtils::DeleteWidgets no longer takes in the BlueprintEditor, use the version without it instead")
Referenced by UE_DEPRECATED().
UpdateHittestGrid()
int32 FWidgetBlueprintEditorUtils::UpdateHittestGrid (FHittestGrid & HitTestGrid, TSharedRef< SWindow > Window, float Scale, FVector2D DrawSize, float DeltaTime) static
References DeltaTime, Scale, and UpdateHittestGrid().
Referenced by UpdateHittestGrid().
VerifyWidgetRename()
bool FWidgetBlueprintEditorUtils::VerifyWidgetRename (TSharedRef< class FWidgetBlueprintEditor > BlueprintEditor, FWidgetReference Widget, const FText & NewName, FText & OutErrorMessage) static
WrapWidgets()
void FWidgetBlueprintEditorUtils::WrapWidgets (TSharedRef< FWidgetBlueprintEditor > BlueprintEditor, UWidgetBlueprint * BP, TSet< FWidgetReference > Widgets, UClass * WidgetClass) static private
References BP, Widgets, and WrapWidgets().
Referenced by WrapWidgets().
Field Documentation
BP
UWidgetBlueprint* FWidgetBlueprintEditorUtils::BP
Definition at line 71 of file WidgetBlueprintEditorUtils.h.
Referenced by BuildReplaceWithMenu(), BuildWrapWithMenu(), CanBeReplacedWithTemplate(), CopyWidgets(), CopyWidgetsInternal(), CreateUserWidgetFromBlueprint(), CutWidgets(), DeleteWidgets(), DoesClipboardTextContainWidget(), DuplicateWidgets(), FindUsedVariablesForWidgets(), ImportWidgetsFromText(), PasteWidgets(), PasteWidgetsInternal(), ProcessImportedText(), ReplaceWidgets(), ReplaceWidgetWithChildren(), ReplaceWidgetWithNamedSlot(), ReplaceWidgetWithSelectedTemplate(), ShouldContinueDeleteOperation(), ShouldContinueReplaceOperation(), and WrapWidgets().
bSilentDelete
UWidgetBlueprint TSet<FWidgetReference> bool FWidgetBlueprintEditorUtils::bSilentDelete = false)
Definition at line 71 of file WidgetBlueprintEditorUtils.h.
Widgets
UWidgetBlueprint TSet<FWidgetReference> FWidgetBlueprintEditorUtils::Widgets
Definition at line 71 of file WidgetBlueprintEditorUtils.h.
Referenced by BuildReplaceWithMenu(), BuildWrapWithMenu(), CopyWidgets(), CopyWidgetsInternal(), CutWidgets(), DeleteWidgets(), DuplicateWidgets(), FindUsedVariablesForWidgets(), ReplaceWidgets(), ResolveWidgetTemplates(), and WrapWidgets().
The documentation for this class was generated from the following file:
WidgetBlueprintEditorUtils.h