Unreal Engine 5.6 C++ API: FWindowsConsoleOutputDevice2 Class Reference
FWindowsConsoleOutputDevice2 Class Reference final
Windows implementation of console log window, utilizing the Win32 console API.
#include "WindowsConsoleOutputDevice2.h"
Data Structures
struct FLogHighlight
An entry for log category highlighting.
struct FLogStringHighlight
An entry for log string highlighting.
Public Member Functions
APPLICATIONCORE_API FWindowsConsoleOutputDevice2 ()
Constructor, setting console control handler.
APPLICATIONCORE_API ~FWindowsConsoleOutputDevice2 ()
void AddCommand (const FString &InCommand)
virtual APPLICATIONCORE_API bool CanBeUsedOnAnyThread () const override
bool GetLastCommand (FString &OutCommand)
bool GetNextCommand (FString &OutCommand)
bool GetPreviousCommand (FString &OutCommand)
virtual APPLICATIONCORE_API bool IsAttached ()
Returns whether the application is already attached to a console window.
virtual APPLICATIONCORE_API bool IsShown ()
Returns whether console is currently shown or not.
virtual APPLICATIONCORE_API void Serialize (const TCHAR *Data, ELogVerbosity::Type Verbosity, const class FName &Category) override
virtual APPLICATIONCORE_API void Serialize (const TCHAR *Data, ELogVerbosity::Type Verbosity, const class FName &Category, const double Time) override
Displays text on the console and scrolls if necessary.
APPLICATIONCORE_API void SetColor (const TCHAR *Color)
virtual APPLICATIONCORE_API void Show (bool ShowWindow)
Shows or hides the console window.
Public Member Functions inherited from FOutputDeviceConsole
void SetIniFilename (const TCHAR *InFilename)
Sets the INI file name to write console settings to.
Public Member Functions inherited from FOutputDevice
FOutputDevice ()
FOutputDevice (const FOutputDevice &)
FOutputDevice (FOutputDevice &&)
virtual ~FOutputDevice ()
virtual bool CanBeUsedOnMultipleThreads () const
virtual bool CanBeUsedOnPanicThread () const
template<typename FmtType, typename... Types>
FORCEINLINE void CategorizedLogf (const FName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
virtual void Dump (class FArchive &Ar)
Dumps the contents of this output device's buffer to an archive (supported by output device that have a memory buffer)
virtual void Flush ()
FORCEINLINE bool GetAutoEmitLineTerminator () const
FORCEINLINE bool GetSuppressEventTag () const
virtual bool IsMemoryOnly () const
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const FString &S)
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Str)
void Log (const FString &S)
void Log (const FText &S)
void Log (const TCHAR *S)
void Log (ELogVerbosity::Type Verbosity, const FString &S)
void Log (ELogVerbosity::Type Verbosity, const TCHAR *S)
template<typename FmtType>
void Logf (const FmtType &Fmt)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (const FmtType &Fmt, Types... Args)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
FOutputDevice & operator= (const FOutputDevice &)
FOutputDevice & operator= (FOutputDevice &&)
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category)=0
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category, const double Time)
virtual void SerializeRecord (const UE::FLogRecord &Record)
void SetAutoEmitLineTerminator (bool bInAutoEmitLineTerminator)
void SetSuppressEventTag (bool bInSuppressEventTag)
virtual void TearDown ()
Closes output device and cleans up.
Private Member Functions
FWindowsConsoleOutputDevice2 (const FWindowsConsoleOutputDevice2 &)=delete
FWindowsConsoleOutputDevice2 & operator= (const FWindowsConsoleOutputDevice2 &)=delete
void SaveToINI ()
Saves the console window's position and size to the game .ini.
Static Private Member Functions
static const FString & GetConfigFilename ()
Private Attributes
ELogVerbosity::Type AllowedLogVerbosity = ELogVerbosity::All
maximum allowed log verbosity
TArray< FString > CommandHistory
int32 CommandHistoryCursor = 0
TArray< FLogHighlight, TInlineAllocator< 8 > > LogHighlights
Log categories to be highlighted.
TArray< FLogStringHighlight, TInlineAllocator< 8 > > LogStringHighlights
Log strings to be highlighted.
bool OverrideColorSet
true if the color is currently set by the caller
uint16 TextAttribute
FConsoleWindow * Window
FRWLock WindowRWLock
Additional Inherited Members
Protected Attributes inherited from FOutputDeviceConsole
FString IniFilename
Ini file name to write console settings to.
Protected Attributes inherited from FOutputDevice
bool bAutoEmitLineTerminator
Whether to output a line-terminator after each log call...
bool bSuppressEventTag
Whether to output the 'Log: ' type front...
Detailed Description
Windows implementation of console log window, utilizing the Win32 console API.
Definition at line 12 of file WindowsConsoleOutputDevice2.h.
Constructor & Destructor Documentation
FWindowsConsoleOutputDevice2() [1/2]
APPLICATIONCORE_API FWindowsConsoleOutputDevice2::FWindowsConsoleOutputDevice2 ()
Constructor, setting console control handler.
Referenced by FWindowsConsoleOutputDevice2(), and operator=().
~FWindowsConsoleOutputDevice2()
APPLICATIONCORE_API FWindowsConsoleOutputDevice2::~FWindowsConsoleOutputDevice2 ()
FWindowsConsoleOutputDevice2() [2/2]
FWindowsConsoleOutputDevice2::FWindowsConsoleOutputDevice2 (const FWindowsConsoleOutputDevice2 &) private delete
References FWindowsConsoleOutputDevice2().
Member Function Documentation
AddCommand()
void FWindowsConsoleOutputDevice2::AddCommand (const FString & InCommand)
CanBeUsedOnAnyThread()
virtual APPLICATIONCORE_API bool FWindowsConsoleOutputDevice2::CanBeUsedOnAnyThread () const override virtual
Returns
whether this output device can be used on any thread.
Reimplemented from FOutputDevice.
GetConfigFilename()
const FString & FWindowsConsoleOutputDevice2::GetConfigFilename () static private
GetLastCommand()
bool FWindowsConsoleOutputDevice2::GetLastCommand (FString & OutCommand)
GetNextCommand()
bool FWindowsConsoleOutputDevice2::GetNextCommand (FString & OutCommand)
GetPreviousCommand()
bool FWindowsConsoleOutputDevice2::GetPreviousCommand (FString & OutCommand)
IsAttached()
virtual APPLICATIONCORE_API bool FWindowsConsoleOutputDevice2::IsAttached () virtual
Returns whether the application is already attached to a console window.
Returns
true if console is attached, false otherwise.
Reimplemented from FOutputDeviceConsole.
IsShown()
virtual APPLICATIONCORE_API bool FWindowsConsoleOutputDevice2::IsShown () virtual
Returns whether console is currently shown or not.
Returns
true if console is shown, false otherwise
Implements FOutputDeviceConsole.
operator=()
FWindowsConsoleOutputDevice2 & FWindowsConsoleOutputDevice2::operator= (const FWindowsConsoleOutputDevice2 &) private delete
References FWindowsConsoleOutputDevice2().
SaveToINI()
void FWindowsConsoleOutputDevice2::SaveToINI () private
Saves the console window's position and size to the game .ini.
Serialize() [1/2]
virtual APPLICATIONCORE_API void FWindowsConsoleOutputDevice2::Serialize (const TCHAR * Data, ELogVerbosity::Type Verbosity, const class FName & Category) override virtual
References Category.
Serialize() [2/2]
virtual APPLICATIONCORE_API void FWindowsConsoleOutputDevice2::Serialize (const TCHAR * Data, ELogVerbosity::Type Verbosity, const class FName & Category, const double Time) override virtual
Displays text on the console and scrolls if necessary.
Parameters
Data Text to display
Event Event type, used for filtering/ suppression
References Category, and Time.
SetColor()
APPLICATIONCORE_API void FWindowsConsoleOutputDevice2::SetColor (const TCHAR * Color)
References Color.
Show()
virtual APPLICATIONCORE_API void FWindowsConsoleOutputDevice2::Show (bool ShowWindow) virtual
Shows or hides the console window.
Parameters
ShowWindow Whether to show (true) or hide (false) the console window.
Implements FOutputDeviceConsole.
Field Documentation
AllowedLogVerbosity
ELogVerbosity::Type FWindowsConsoleOutputDevice2::AllowedLogVerbosity = ELogVerbosity::All private
maximum allowed log verbosity
Definition at line 27 of file WindowsConsoleOutputDevice2.h.
CommandHistory
TArray<FString> FWindowsConsoleOutputDevice2::CommandHistory private
Definition at line 23 of file WindowsConsoleOutputDevice2.h.
CommandHistoryCursor
int32 FWindowsConsoleOutputDevice2::CommandHistoryCursor = 0 private
Definition at line 24 of file WindowsConsoleOutputDevice2.h.
LogHighlights
TArray<FLogHighlight, TInlineAllocator<8> > FWindowsConsoleOutputDevice2::LogHighlights private
Log categories to be highlighted.
Definition at line 46 of file WindowsConsoleOutputDevice2.h.
LogStringHighlights
TArray<FLogStringHighlight, TInlineAllocator<8> > FWindowsConsoleOutputDevice2::LogStringHighlights private
Log strings to be highlighted.
Definition at line 59 of file WindowsConsoleOutputDevice2.h.
OverrideColorSet
bool FWindowsConsoleOutputDevice2::OverrideColorSet private
true if the color is currently set by the caller
Definition at line 18 of file WindowsConsoleOutputDevice2.h.
TextAttribute
uint16 FWindowsConsoleOutputDevice2::TextAttribute private
Definition at line 15 of file WindowsConsoleOutputDevice2.h.
Window
FConsoleWindow* FWindowsConsoleOutputDevice2::Window private
Definition at line 21 of file WindowsConsoleOutputDevice2.h.
WindowRWLock
FRWLock FWindowsConsoleOutputDevice2::WindowRWLock private
Definition at line 22 of file WindowsConsoleOutputDevice2.h.
The documentation for this class was generated from the following file:
WindowsConsoleOutputDevice2.h