Unreal Engine 5.6 C++ API: UE::Geometry::TDenseGrid2< ElemType > Class Template Reference
UE::Geometry::TDenseGrid2< ElemType > Class Template Reference
2D dense grid of scalar values.
#include "DenseGrid2.h"
Public Member Functions
TDenseGrid2 ()
Create empty grid.
TDenseGrid2 (int32 DimX, int32 DimY, ElemType InitialValue)
void Apply (TFunctionRef< ElemType(ElemType)> ApplyFunc)
void AssignAll (ElemType Value)
constexpr ElemType & At (int32 X, int32 Y)
constexpr const ElemType & At (int32 X, int32 Y) const
constexpr ElemType & At (int64 X, int64 Y)
constexpr const ElemType & At (int64 X, int64 Y) const
FAxisAlignedBox2i Bounds () const
FAxisAlignedBox2i BoundsInclusive () const
FVector2i GetCoords (int64 LinearIndex) const
FVector2i GetDimensions () const
int64 GetIndex (const FVector2i &IJK) const
int64 GetIndex (int32 X, int32 Y) const
void GetXPair (int32 X0, int32 Y, ElemType &AOut, ElemType &BOut) const
TArray64< ElemType > & GridValues ()
const TArray64< ElemType > & GridValues () const
int64 Height () const
constexpr ElemType & operator[] (FVector2i Idx)
constexpr const ElemType & operator[] (FVector2i Idx) const
constexpr ElemType & operator[] (int64 Idx)
constexpr const ElemType & operator[] (int64 Idx) const
void Resize (int32 DimX, int32 DimY, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void SetMax (const FVector2i &IJK, ElemType NewValue)
void SetMin (const FVector2i &IJK, ElemType NewValue)
int64 Size () const
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Resize") FORCEINLINE void Resize(int32 DimX
int64 Width () const
Data Fields
int32 bool bAllowShrinking
int32 DimY
Protected Attributes
TArray64< ElemType > Buffer
grid of allocated elements
int64 DimensionX
dimensions per axis
int64 DimensionY
Detailed Description
template<typename ElemType>
class UE::Geometry::TDenseGrid2< ElemType >
2D dense grid of scalar values.
Definition at line 22 of file DenseGrid2.h.
Constructor & Destructor Documentation
TDenseGrid2() [1/2]
template<typename ElemType> UE::Geometry::TDenseGrid2< ElemType >::TDenseGrid2 () inline
Create empty grid.
Definition at line 35 of file DenseGrid2.h.
TDenseGrid2() [2/2]
template<typename ElemType> UE::Geometry::TDenseGrid2< ElemType >::TDenseGrid2 (int32 DimX, int32 DimY, ElemType InitialValue) inline
Definition at line 39 of file DenseGrid2.h.
Member Function Documentation
Apply()
template<typename ElemType> void UE::Geometry::TDenseGrid2< ElemType >::Apply (TFunctionRef< ElemType(ElemType)> ApplyFunc) inline
Definition at line 155 of file DenseGrid2.h.
AssignAll()
template<typename ElemType> void UE::Geometry::TDenseGrid2< ElemType >::AssignAll (ElemType Value) inline
Definition at line 78 of file DenseGrid2.h.
At() [1/4]
template<typename ElemType> ElemType & UE::Geometry::TDenseGrid2< ElemType >::At (int32 X, int32 Y) inline constexpr
Definition at line 121 of file DenseGrid2.h.
At() [2/4]
template<typename ElemType> const ElemType & UE::Geometry::TDenseGrid2< ElemType >::At (int32 X, int32 Y) const inline constexpr
Definition at line 125 of file DenseGrid2.h.
At() [3/4]
template<typename ElemType> ElemType & UE::Geometry::TDenseGrid2< ElemType >::At (int64 X, int64 Y) inline constexpr
Definition at line 129 of file DenseGrid2.h.
At() [4/4]
template<typename ElemType> const ElemType & UE::Geometry::TDenseGrid2< ElemType >::At (int64 X, int64 Y) const inline constexpr
Definition at line 133 of file DenseGrid2.h.
Bounds()
template<typename ElemType> FAxisAlignedBox2i UE::Geometry::TDenseGrid2< ElemType >::Bounds () const inline
Definition at line 163 of file DenseGrid2.h.
BoundsInclusive()
template<typename ElemType> FAxisAlignedBox2i UE::Geometry::TDenseGrid2< ElemType >::BoundsInclusive () const inline
Definition at line 167 of file DenseGrid2.h.
GetCoords()
template<typename ElemType> FVector2i UE::Geometry::TDenseGrid2< ElemType >::GetCoords (int64 LinearIndex) const inline
Definition at line 172 of file DenseGrid2.h.
GetDimensions()
template<typename ElemType> FVector2i UE::Geometry::TDenseGrid2< ElemType >::GetDimensions () const inline
Definition at line 61 of file DenseGrid2.h.
GetIndex() [1/2]
template<typename ElemType> int64 UE::Geometry::TDenseGrid2< ElemType >::GetIndex (const FVector2i & IJK) const inline
Definition at line 181 of file DenseGrid2.h.
GetIndex() [2/2]
template<typename ElemType> int64 UE::Geometry::TDenseGrid2< ElemType >::GetIndex (int32 X, int32 Y) const inline
Definition at line 177 of file DenseGrid2.h.
GetXPair()
template<typename ElemType> void UE::Geometry::TDenseGrid2< ElemType >::GetXPair (int32 X0, int32 Y, ElemType & AOut, ElemType & BOut) const inline
Definition at line 148 of file DenseGrid2.h.
GridValues() [1/2]
template<typename ElemType> TArray64< ElemType > & UE::Geometry::TDenseGrid2< ElemType >::GridValues () inline
Definition at line 138 of file DenseGrid2.h.
GridValues() [2/2]
template<typename ElemType> const TArray64< ElemType > & UE::Geometry::TDenseGrid2< ElemType >::GridValues () const inline
Definition at line 142 of file DenseGrid2.h.
Height()
template<typename ElemType> int64 UE::Geometry::TDenseGrid2< ElemType >::Height () const inline
Definition at line 56 of file DenseGrid2.h.
Referenced by UE::Geometry::TSampledScalarField2< double, double >::CopyConfiguration().
operator[]() [1/4]
template<typename ElemType> ElemType & UE::Geometry::TDenseGrid2< ElemType >::operator[] (FVector2i Idx) inline constexpr
Definition at line 113 of file DenseGrid2.h.
operator[]() [2/4]
template<typename ElemType> const ElemType & UE::Geometry::TDenseGrid2< ElemType >::operator[] (FVector2i Idx) const inline constexpr
Definition at line 117 of file DenseGrid2.h.
operator[]() [3/4]
template<typename ElemType> ElemType & UE::Geometry::TDenseGrid2< ElemType >::operator[] (int64 Idx) inline constexpr
Definition at line 104 of file DenseGrid2.h.
operator[]() [4/4]
template<typename ElemType> const ElemType & UE::Geometry::TDenseGrid2< ElemType >::operator[] (int64 Idx) const inline constexpr
Definition at line 108 of file DenseGrid2.h.
Resize()
template<typename ElemType> void UE::Geometry::TDenseGrid2< ElemType >::Resize (int32 DimX, int32 DimY, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 66 of file DenseGrid2.h.
SetMax()
template<typename ElemType> void UE::Geometry::TDenseGrid2< ElemType >::SetMax (const FVector2i & IJK, ElemType NewValue) inline
Definition at line 95 of file DenseGrid2.h.
SetMin()
template<typename ElemType> void UE::Geometry::TDenseGrid2< ElemType >::SetMin (const FVector2i & IJK, ElemType NewValue) inline
Definition at line 86 of file DenseGrid2.h.
Size()
template<typename ElemType> int64 UE::Geometry::TDenseGrid2< ElemType >::Size () const inline
Definition at line 46 of file DenseGrid2.h.
Referenced by UE::Geometry::TDenseGrid2< float >::TDenseGrid2(), UE::Geometry::TDenseGrid2< float >::Apply(), and UE::Geometry::TDenseGrid2< float >::AssignAll().
UE_ALLOWSHRINKING_BOOL_DEPRECATED()
template<typename ElemType> UE::Geometry::TDenseGrid2< ElemType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Resize")
Width()
template<typename ElemType> int64 UE::Geometry::TDenseGrid2< ElemType >::Width () const inline
Definition at line 51 of file DenseGrid2.h.
Referenced by UE::Geometry::TSampledScalarField2< double, double >::CopyConfiguration().
Field Documentation
bAllowShrinking
template<typename ElemType> int32 bool UE::Geometry::TDenseGrid2< ElemType >::bAllowShrinking
Initial value:
{
        Resize(DimX, DimY, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 73 of file DenseGrid2.h.
Buffer
template<typename ElemType> TArray64<ElemType> UE::Geometry::TDenseGrid2< ElemType >::Buffer protected
grid of allocated elements
Definition at line 26 of file DenseGrid2.h.
DimensionX
template<typename ElemType> int64 UE::Geometry::TDenseGrid2< ElemType >::DimensionX protected
dimensions per axis
Definition at line 29 of file DenseGrid2.h.
DimensionY
template<typename ElemType> int64 UE::Geometry::TDenseGrid2< ElemType >::DimensionY protected
Definition at line 29 of file DenseGrid2.h.
DimY
template<typename ElemType> int32 UE::Geometry::TDenseGrid2< ElemType >::DimY
Definition at line 73 of file DenseGrid2.h.
The documentation for this class was generated from the following file:
DenseGrid2.h