Unreal Engine 5.6 C++ API: SkeletalMeshUpdate.cpp File Reference
SkeletalMeshUpdate.cpp File Reference
#include "Streaming/SkeletalMeshUpdate.h"
#include "HAL/PlatformFile.h"
#include "RenderUtils.h"
#include "ContentStreaming.h"
#include "Streaming/TextureStreamingHelpers.h"
#include "Serialization/MemoryReader.h"
#include "Rendering/SkeletalMeshRenderData.h"
#include "Rendering/RayTracingGeometryManager.h"
#include "Components/SkinnedMeshComponent.h"
#include "Streaming/RenderAssetUpdate.inl"
#include "RHIResourceReplace.h"
#include "ProfilingDebugging/IoStoreTrace.h"
Variables
static constexpr uint32 GSkelMeshMaxNumResourceUpdatesPerBatch = (MAX_MESH_LOD_COUNT - 1) * GSkelMeshMaxNumResourceUpdatesPerLOD
static constexpr uint32 GSkelMeshMaxNumResourceUpdatesPerLOD = 16
int32 GStreamingMaxReferenceChecks
Variable Documentation
GSkelMeshMaxNumResourceUpdatesPerBatch
uint32 GSkelMeshMaxNumResourceUpdatesPerBatch = (MAX_MESH_LOD_COUNT - 1) * GSkelMeshMaxNumResourceUpdatesPerLOD static constexpr
Definition at line 25 of file SkeletalMeshUpdate.cpp.
Referenced by FSkeletalMeshStreamIn::CreateBuffers(), FSkeletalMeshStreamIn::DoFinishUpdate(), and FSkeletalMeshStreamOut::ReleaseBuffers().
GSkelMeshMaxNumResourceUpdatesPerLOD
uint32 GSkelMeshMaxNumResourceUpdatesPerLOD = 16 static constexpr
Definition at line 24 of file SkeletalMeshUpdate.cpp.
GStreamingMaxReferenceChecks
int32 GStreamingMaxReferenceChecks extern
Referenced by FSkeletalMeshStreamOut::WaitForReferences().