Unreal Engine 5.6 C++ API: FUnixPlatformProcess::FProcEnumerator Class Reference
FUnixPlatformProcess::FProcEnumerator Class Reference
Process enumerator.
#include "UnixPlatformProcess.h"
Public Member Functions
FProcEnumerator ()
FProcEnumerator (const FProcEnumerator &)=delete
~FProcEnumerator ()
FProcEnumInfo GetCurrent () const
bool MoveNext ()
Moves current to the next process.
FProcEnumerator & operator= (const FProcEnumerator &)=delete
Private Attributes
struct FProcEnumData * Data
Detailed Description
Process enumerator.
Definition at line 215 of file UnixPlatformProcess.h.
Constructor & Destructor Documentation
FProcEnumerator() [1/2]
FUnixPlatformProcess::FProcEnumerator::FProcEnumerator ()
Referenced by FProcEnumerator(), and operator=().
FProcEnumerator() [2/2]
FUnixPlatformProcess::FProcEnumerator::FProcEnumerator (const FProcEnumerator &) delete
References FProcEnumerator().
~FProcEnumerator()
FUnixPlatformProcess::FProcEnumerator::~FProcEnumerator ()
Member Function Documentation
GetCurrent()
FProcEnumInfo FUnixPlatformProcess::FProcEnumerator::GetCurrent () const
MoveNext()
bool FUnixPlatformProcess::FProcEnumerator::MoveNext ()
Moves current to the next process.
Returns
True if succeeded. False otherwise.
operator=()
FProcEnumerator & FUnixPlatformProcess::FProcEnumerator::operator= (const FProcEnumerator &) delete
References FProcEnumerator().
Field Documentation
Data
struct FProcEnumData* FUnixPlatformProcess::FProcEnumerator::Data private
Definition at line 237 of file UnixPlatformProcess.h.
The documentation for this class was generated from the following file:
UnixPlatformProcess.h