Unreal Engine 5.6 C++ API: IPixelStreaming2VideoSink Class Reference
IPixelStreaming2VideoSink Class Reference abstract
Interface for a sink that collects video coming in from the browser and passes into into UE.
#include "IPixelStreaming2VideoSink.h"
Private Member Functions
virtual void AddVideoConsumer (const TWeakPtrVariant< IPixelStreaming2VideoConsumer > &VideoConsumer)=0
Add a video consumer to the sink.
GENERATED_BODY () public
Add a video consumer to the sink.
virtual void RemoveVideoConsumer (const TWeakPtrVariant< IPixelStreaming2VideoConsumer > &VideoConsumer)=0
Remove a video consumer to remove from the sink.
UE_DEPRECATED (5.6, "RemoveVideoConsumer(IPixelStreaming2VideoConsumer*) has been deprecated. Please use RemoveVideoConsumer(const TWeakPtrVariant<IPixelStreaming2VideoConsumer>&) instead.") virtual void RemoveVideoConsumer(IPixelStreaming2VideoConsumer *VideoConsumer)
Remove a video consumer to remove from the sink.
Detailed Description
Interface for a sink that collects video coming in from the browser and passes into into UE.
Definition at line 23 of file IPixelStreaming2VideoSink.h.
Member Function Documentation
AddVideoConsumer()
virtual void IPixelStreaming2VideoSink::AddVideoConsumer (const TWeakPtrVariant< IPixelStreaming2VideoConsumer > & VideoConsumer) private pure virtual
Add a video consumer to the sink.
Parameters
VideoConsumer The video consumer to add to the sink.
Implemented in UE::PixelStreaming2::FVideoSink.
Referenced by GENERATED_BODY().
GENERATED_BODY()
IPixelStreaming2VideoSink::GENERATED_BODY () inline private
Add a video consumer to the sink.
Parameters
VideoConsumer The video consumer to add to the sink.
Definition at line 25 of file IPixelStreaming2VideoSink.h.
References AddVideoConsumer(), and UE_DEPRECATED().
RemoveVideoConsumer()
virtual void IPixelStreaming2VideoSink::RemoveVideoConsumer (const TWeakPtrVariant< IPixelStreaming2VideoConsumer > & VideoConsumer) private pure virtual
Remove a video consumer to remove from the sink.
Parameters
VideoConsumer The video consumer to remove from the sink.
Implemented in UE::PixelStreaming2::FVideoSink.
Referenced by UE_DEPRECATED().
UE_DEPRECATED()
IPixelStreaming2VideoSink::UE_DEPRECATED (5. 6, "RemoveVideoConsumer(IPixelStreaming2VideoConsumer*) has been deprecated. Please use RemoveVideoConsumer(const TWeakPtrVariant<IPixelStreaming2VideoConsumer>&) instead.") inline private
Remove a video consumer to remove from the sink.
Parameters
VideoConsumer The video consumer to remove from the sink.
Definition at line 45 of file IPixelStreaming2VideoSink.h.
References RemoveVideoConsumer().
Referenced by GENERATED_BODY().
The documentation for this class was generated from the following file:
IPixelStreaming2VideoSink.h