Unreal Engine 5.6 C++ API: FSubstrateOperator Struct Reference
FSubstrateOperator Struct Reference
#include "SubstrateMaterialShared.h"
Public Member Functions
FSubstrateOperator ()
void CombineFlagsForParameterBlending (FSubstrateOperator &A, FSubstrateOperator &B)
void CopyFlagsForParameterBlending (FSubstrateOperator &A)
DECLARE_TYPE_LAYOUT (FSubstrateOperator, NonVirtual)
bool Has (ESubstrateBsdfFeature In) const
bool Has (uint32 In) const
bool IsDiscarded () const
LAYOUT_FIELD_EDITORONLY (FGuid, MaterialExpressionGuid)
LAYOUT_FIELD_EDITORONLY (FSubstrateRegisteredSharedLocalBasis, BSDFRegisteredSharedLocalBasis)
LAYOUT_FIELD_EDITORONLY (int32, BSDFIndex)
LAYOUT_FIELD_EDITORONLY (int32, BSDFType)
LAYOUT_FIELD_EDITORONLY (int32, Index)
LAYOUT_FIELD_EDITORONLY (int32, LayerDepth)
LAYOUT_FIELD_EDITORONLY (int32, LeftIndex)
LAYOUT_FIELD_EDITORONLY (int32, MaxDistanceFromLeaves)
LAYOUT_FIELD_EDITORONLY (int32, OperatorType)
LAYOUT_FIELD_EDITORONLY (int32, ParentIndex)
LAYOUT_FIELD_EDITORONLY (int32, RightIndex)
LAYOUT_FIELD_EDITORONLY (int32, ThicknessIndex)
LAYOUT_FIELD_EDITORONLY (uint32, BSDFFeatures)
LAYOUT_FIELD_EDITORONLY (uint8, bBSDFWritesAmbientOcclusion)
LAYOUT_FIELD_EDITORONLY (uint8, bBSDFWritesEmissive)
LAYOUT_FIELD_EDITORONLY (uint8, bIsBottom)
LAYOUT_FIELD_EDITORONLY (uint8, bIsTop)
LAYOUT_FIELD_EDITORONLY (uint8, bNodeRequestParameterBlending)
LAYOUT_FIELD_EDITORONLY (uint8, bRootOfParameterBlendingSubTree)
LAYOUT_FIELD_EDITORONLY (uint8, bUseParameterBlending)
LAYOUT_FIELD_EDITORONLY (uint8, SubSurfaceType)
LAYOUT_FIELD_EDITORONLY (uint8, SubUsage)
Detailed Description
Definition at line 61 of file SubstrateMaterialShared.h.
Constructor & Destructor Documentation
FSubstrateOperator()
FSubstrateOperator::FSubstrateOperator ()
Definition at line 36 of file SubstrateMaterialShared.cpp.
References INDEX_NONE.
Referenced by CombineFlagsForParameterBlending(), CopyFlagsForParameterBlending(), DECLARE_TYPE_LAYOUT(), and LAYOUT_FIELD_EDITORONLY().
Member Function Documentation
CombineFlagsForParameterBlending()
void FSubstrateOperator::CombineFlagsForParameterBlending (FSubstrateOperator & A, FSubstrateOperator & B)
Definition at line 67 of file SubstrateMaterialShared.cpp.
References FSubstrateOperator(), A, B, and SubstrateMergeSubSurfaceType().
CopyFlagsForParameterBlending()
void FSubstrateOperator::CopyFlagsForParameterBlending (FSubstrateOperator & A)
Definition at line 75 of file SubstrateMaterialShared.cpp.
References FSubstrateOperator(), and A.
DECLARE_TYPE_LAYOUT()
FSubstrateOperator::DECLARE_TYPE_LAYOUT (FSubstrateOperator , NonVirtual)
References FSubstrateOperator().
Has() [1/2]
bool FSubstrateOperator::Has (ESubstrateBsdfFeature In) const inline
Definition at line 108 of file SubstrateMaterialShared.h.
Has() [2/2]
bool FSubstrateOperator::Has (uint32 In) const inline
Definition at line 117 of file SubstrateMaterialShared.h.
IsDiscarded()
bool FSubstrateOperator::IsDiscarded () const
Definition at line 83 of file SubstrateMaterialShared.cpp.
LAYOUT_FIELD_EDITORONLY() [1/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (FGuid , MaterialExpressionGuid)
References FSubstrateOperator(), A, and B.
LAYOUT_FIELD_EDITORONLY() [2/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (FSubstrateRegisteredSharedLocalBasis , BSDFRegisteredSharedLocalBasis)
LAYOUT_FIELD_EDITORONLY() [3/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , BSDFIndex)
LAYOUT_FIELD_EDITORONLY() [4/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , BSDFType)
LAYOUT_FIELD_EDITORONLY() [5/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , Index)
LAYOUT_FIELD_EDITORONLY() [6/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , LayerDepth)
LAYOUT_FIELD_EDITORONLY() [7/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , LeftIndex)
LAYOUT_FIELD_EDITORONLY() [8/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , MaxDistanceFromLeaves)
LAYOUT_FIELD_EDITORONLY() [9/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , OperatorType)
LAYOUT_FIELD_EDITORONLY() [10/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , ParentIndex)
LAYOUT_FIELD_EDITORONLY() [11/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , RightIndex)
LAYOUT_FIELD_EDITORONLY() [12/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (int32 , ThicknessIndex)
LAYOUT_FIELD_EDITORONLY() [13/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint32 , BSDFFeatures)
LAYOUT_FIELD_EDITORONLY() [14/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , bBSDFWritesAmbientOcclusion)
LAYOUT_FIELD_EDITORONLY() [15/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , bBSDFWritesEmissive)
LAYOUT_FIELD_EDITORONLY() [16/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , bIsBottom)
LAYOUT_FIELD_EDITORONLY() [17/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , bIsTop)
LAYOUT_FIELD_EDITORONLY() [18/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , bNodeRequestParameterBlending)
LAYOUT_FIELD_EDITORONLY() [19/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , bRootOfParameterBlendingSubTree)
LAYOUT_FIELD_EDITORONLY() [20/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , bUseParameterBlending)
LAYOUT_FIELD_EDITORONLY() [21/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , SubSurfaceType)
LAYOUT_FIELD_EDITORONLY() [22/22]
FSubstrateOperator::LAYOUT_FIELD_EDITORONLY (uint8 , SubUsage)
The documentation for this struct was generated from the following files:
SubstrateMaterialShared.h
SubstrateMaterialShared.cpp