Unreal Engine 5.6 C++ API: LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue Class Reference
LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue Class Reference
#include "LocalQueue.h"
Public Member Functions
TLocalQueue (TLocalQueueRegistry &InRegistry, ELocalQueueType InQueueType)
~TLocalQueue ()
FTask * Dequeue (bool GetBackGroundTasks)
FTask * DequeueSteal (bool GetBackGroundTasks)
void Enqueue (FTask *Item, uint32 PriorityIndex)
FTask * StealLocal (bool GetBackGroundTasks)
Private Attributes
uint32 CachedPriorityIndex = 0
uint32 CachedRandomIndex = InvalidIndex
DequeueHazard DequeueHazards [uint32(ETaskPriority::Count)]
FLocalQueueType LocalQueues [uint32(ETaskPriority::Count)]
ELocalQueueType QueueType
TLocalQueueRegistry * Registry
Static Private Attributes
static constexpr uint32 InvalidIndex = ~0u
Friends
template<uint32, uint32>
class TLocalQueueRegistry
Detailed Description
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024>
class LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue
Definition at line 175 of file LocalQueue.h.
Constructor & Destructor Documentation
TLocalQueue()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::TLocalQueue (TLocalQueueRegistry & InRegistry, ELocalQueueType InQueueType) inline
Definition at line 181 of file LocalQueue.h.
References LowLevelTasks::Count, DequeueHazards, QueueType, Registry, and TLocalQueueRegistry.
~TLocalQueue()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::~TLocalQueue () inline
Definition at line 191 of file LocalQueue.h.
References LowLevelTasks::Count, Item, LocalQueues, and Registry.
Member Function Documentation
Dequeue()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FTask * LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::Dequeue (bool GetBackGroundTasks) inline
Definition at line 237 of file LocalQueue.h.
References LowLevelTasks::Count, DequeueHazards, LowLevelTasks::ForegroundCount, Item, LocalQueues, and Registry.
DequeueSteal()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FTask * LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::DequeueSteal (bool GetBackGroundTasks) inline
Definition at line 258 of file LocalQueue.h.
References CachedPriorityIndex, CachedRandomIndex, InvalidIndex, LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::Rand(), and Registry.
Enqueue()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> void LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::Enqueue (FTask * Item, uint32 PriorityIndex) inline
Definition at line 209 of file LocalQueue.h.
References checkSlow, LowLevelTasks::Count, Item, LocalQueues, and Registry.
StealLocal()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FTask * LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::StealLocal (bool GetBackGroundTasks) inline
Definition at line 221 of file LocalQueue.h.
References LowLevelTasks::Count, LowLevelTasks::ForegroundCount, Item, and LocalQueues.
Friends And Related Symbol Documentation
TLocalQueueRegistry
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> template<uint32, uint32> friend class TLocalQueueRegistry friend
Definition at line 178 of file LocalQueue.h.
References TLocalQueueRegistry.
Referenced by TLocalQueue(), and TLocalQueueRegistry.
Field Documentation
CachedPriorityIndex
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> uint32 LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::CachedPriorityIndex = 0 private
Definition at line 279 of file LocalQueue.h.
Referenced by DequeueSteal().
CachedRandomIndex
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> uint32 LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::CachedRandomIndex = InvalidIndex private
Definition at line 278 of file LocalQueue.h.
Referenced by DequeueSteal().
DequeueHazards
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> DequeueHazard LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::DequeueHazards[uint32(ETaskPriority::Count)] private
Definition at line 276 of file LocalQueue.h.
Referenced by TLocalQueue(), and Dequeue().
InvalidIndex
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> uint32 LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::InvalidIndex = ~0u static constexpr private
Definition at line 274 of file LocalQueue.h.
Referenced by DequeueSteal(), and LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::StealItem().
LocalQueues
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FLocalQueueType LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::LocalQueues[uint32(ETaskPriority::Count)] private
Definition at line 275 of file LocalQueue.h.
Referenced by ~TLocalQueue(), Dequeue(), Enqueue(), and StealLocal().
QueueType
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> ELocalQueueType LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::QueueType private
Definition at line 280 of file LocalQueue.h.
Referenced by TLocalQueue().
Registry
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> TLocalQueueRegistry* LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::Registry private
Definition at line 277 of file LocalQueue.h.
Referenced by TLocalQueue(), ~TLocalQueue(), Dequeue(), DequeueSteal(), and Enqueue().
The documentation for this class was generated from the following file:
LocalQueue.h