Unreal Engine 5.6 C++ API: TQuadTree< ElementType, NodeCapacity > Class Template Reference
TQuadTree< ElementType, NodeCapacity > Class Template Reference
#include "GenericQuadTree.h"
Data Structures
struct FNode
Node used to hold the element and its corresponding 2D box.
Public Member Functions
TQuadTree ()
DO NOT USE.
TQuadTree (const FBox2D &InBox, float InMinimumQuadSize=100.f)
TQuadTree (const TQuadTree &)
~TQuadTree ()
void Duplicate (TreeType &OutDuplicate) const
Does a deep copy of the tree by going through and re-creating the internal data.
void Empty ()
Removes all elements of the tree.
template<typename CallbackType>
void GetElements (const FBox2D &Box, CallbackType &&Callback) const
Given a 2D box, iterates over intersecting elements and execute the callback for each.
template<typename ElementAllocatorType>
void GetElements (const FBox2D &Box, TArray< ElementType, ElementAllocatorType > &ElementsOut) const
Given a 2D box, returns an array of elements within the box.
const FBox2D & GetTreeBox () const
Gets the TreeBox so systems can test insertions before trying to do so with invalid regions.
void Insert (const ElementType &Element, const FBox2D &Box, const TCHAR *DebugContext=nullptr)
Inserts an object of type ElementType with an associated 2D box of size Box (log n).
TQuadTree & operator= (const TQuadTree &Other)
bool Remove (const ElementType &Instance, const FBox2D &Box)
Removes an object of type ElementType with an associated 2D box of size Box (log n).
void Serialize (FArchive &Ar)
Private Types
enum QuadNames { TopLeft = 0 , TopRight = 1 , BottomLeft = 2 , BottomRight = 3 }
typedef TQuadTree< ElementType, NodeCapacity > TreeType
Private Member Functions
template<typename CallbackType>
bool GetIntersectingElements (const FBox2D &Box, CallbackType &Callback) const
Given a list of nodes, execute Callback for any elements that intersect the box.
template<typename ElementAllocatorType>
void GetIntersectingElements (const FBox2D &Box, TArray< ElementType, ElementAllocatorType > &ElementsOut) const
Given a list of nodes, return which ones actually intersect the box.
int32 GetQuads (const FBox2D &Box, TreeType *Quads[4]) const
Given a 2D box, return the subtrees that are touched.
void InsertElementRecursive (const ElementType &Element, const FBox2D &Box, const TCHAR *DebugContext)
Internal recursive implementation of.
bool RemoveNodeForElement (const ElementType &Element)
Given a list of nodes, remove the node that contains the given element.
void Split ()
Split the tree into 4 sub-trees.
Private Attributes
bool bInternal
Whether this is a leaf or an internal sub-tree.
float MinimumQuadSize
The smallest size of a quad allowed in the tree.
TArray< FNode > Nodes
Contains the actual elements this tree is responsible for.
FVector2D Position
Center position of the tree.
TreeType * SubTrees [4] = {nullptr}
The sub-trees of this tree.
FBox2D TreeBox
AABB of the tree.
Detailed Description
template<typename ElementType, int32 NodeCapacity = 4>
class TQuadTree< ElementType, NodeCapacity >
Definition at line 10 of file GenericQuadTree.h.
Member Typedef Documentation
TreeType
template<typename ElementType, int32 NodeCapacity = 4> typedef TQuadTree<ElementType, NodeCapacity> TQuadTree< ElementType, NodeCapacity >::TreeType private
Definition at line 12 of file GenericQuadTree.h.
Member Enumeration Documentation
QuadNames
template<typename ElementType, int32 NodeCapacity = 4> enum TQuadTree::QuadNames private
Enumerator
TopLeft
TopRight
BottomLeft
BottomRight
Definition at line 52 of file GenericQuadTree.h.
Constructor & Destructor Documentation
TQuadTree() [1/3]
template<typename ElementType, int32 NodeCapacity> TQuadTree< ElementType, NodeCapacity >::TQuadTree ()
DO NOT USE.
This constructor is for internal usage only for hot-reload purposes.
Definition at line 174 of file GenericQuadTree.h.
References EnsureRetrievingVTablePtrDuringCtor(), and TEXT.
Referenced by TQuadTree(), and operator=().
TQuadTree() [2/3]
template<typename ElementType, int32 NodeCapacity> TQuadTree< ElementType, NodeCapacity >::TQuadTree (const FBox2D & InBox, float InMinimumQuadSize = 100.f)
Definition at line 164 of file GenericQuadTree.h.
References bInternal, Box, MinimumQuadSize, Position, SubTrees, and TreeBox.
TQuadTree() [3/3]
template<typename ElementType, int32 NodeCapacity> TQuadTree< ElementType, NodeCapacity >::TQuadTree (const TQuadTree< ElementType, NodeCapacity > & Other)
Definition at line 125 of file GenericQuadTree.h.
References TQuadTree(), and Other.
~TQuadTree()
template<typename ElementType, int32 NodeCapacity> TQuadTree< ElementType, NodeCapacity >::~TQuadTree ()
Definition at line 180 of file GenericQuadTree.h.
References SubTrees.
Member Function Documentation
Duplicate()
template<typename ElementType, int32 NodeCapacity> void TQuadTree< ElementType, NodeCapacity >::Duplicate (TreeType & OutDuplicate) const
Does a deep copy of the tree by going through and re-creating the internal data.
Cheaper than re-insertion as it should be linear instead of nlogn
Definition at line 455 of file GenericQuadTree.h.
References bInternal, MinimumQuadSize, Nodes, Position, SubTrees, and TreeBox.
Empty()
template<typename ElementType, int32 NodeCapacity> void TQuadTree< ElementType, NodeCapacity >::Empty ()
Removes all elements of the tree.
Definition at line 475 of file GenericQuadTree.h.
References bInternal, Nodes, and SubTrees.
GetElements() [1/2]
template<typename ElementType, int32 NodeCapacity> template<typename CallbackType> void TQuadTree< ElementType, NodeCapacity >::GetElements (const FBox2D & Box, CallbackType && Callback) const inline
Given a 2D box, iterates over intersecting elements and execute the callback for each.
If Callback returns true, it will continue processing, if it returns false, iteration will end.
Definition at line 383 of file GenericQuadTree.h.
References Box, GetElements(), GetIntersectingElements(), and GetQuads().
GetElements() [2/2]
template<typename ElementType, int32 NodeCapacity> template<typename ElementAllocatorType> void TQuadTree< ElementType, NodeCapacity >::GetElements (const FBox2D & Box, TArray< ElementType, ElementAllocatorType > & ElementsOut) const
Given a 2D box, returns an array of elements within the box.
There will not be any duplicates in the list.
Definition at line 350 of file GenericQuadTree.h.
References Box, GetElements(), GetIntersectingElements(), and GetQuads().
Referenced by GetElements(), and GetElements().
GetIntersectingElements() [1/2]
template<typename ElementType, int32 NodeCapacity> template<typename CallbackType> bool TQuadTree< ElementType, NodeCapacity >::GetIntersectingElements (const FBox2D & Box, CallbackType & Callback) const private
Given a list of nodes, execute Callback for any elements that intersect the box.
Definition at line 403 of file GenericQuadTree.h.
References Box, and Nodes.
GetIntersectingElements() [2/2]
template<typename ElementType, int32 NodeCapacity> template<typename ElementAllocatorType> void TQuadTree< ElementType, NodeCapacity >::GetIntersectingElements (const FBox2D & Box, TArray< ElementType, ElementAllocatorType > & ElementsOut) const private
Given a list of nodes, return which ones actually intersect the box.
Definition at line 367 of file GenericQuadTree.h.
References TArray< InElementType, InAllocatorType >::Add(), Box, checkSlow, TArray< InElementType, InAllocatorType >::Contains(), Nodes, TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::Reserve().
Referenced by GetElements(), and GetElements().
GetQuads()
template<typename ElementType, int32 NodeCapacity> int32 TQuadTree< ElementType, NodeCapacity >::GetQuads (const FBox2D & Box, TreeType * Quads[4]) const private
Given a 2D box, return the subtrees that are touched.
Returns 0 for leaves.
Definition at line 419 of file GenericQuadTree.h.
References bInternal, BottomLeft, BottomRight, Box, Position, SubTrees, TopLeft, and TopRight.
Referenced by GetElements(), GetElements(), InsertElementRecursive(), Remove(), and Split().
GetTreeBox()
template<typename ElementType, int32 NodeCapacity = 4> const FBox2D & TQuadTree< ElementType, NodeCapacity >::GetTreeBox () const inline
Gets the TreeBox so systems can test insertions before trying to do so with invalid regions.
Definition at line 21 of file GenericQuadTree.h.
Insert()
template<typename ElementType, int32 NodeCapacity> void TQuadTree< ElementType, NodeCapacity >::Insert (const ElementType & Element, const FBox2D & Box, const TCHAR * DebugContext = nullptr)
Inserts an object of type ElementType with an associated 2D box of size Box (log n).
Pass in a DebugContext so when an issue occurs the log can report what requested this insert.
Definition at line 249 of file GenericQuadTree.h.
References Box, InsertElementRecursive(), TEXT, TreeBox, UE_LOG, and Warning.
InsertElementRecursive()
template<typename ElementType, int32 NodeCapacity> void TQuadTree< ElementType, NodeCapacity >::InsertElementRecursive (const ElementType & Element, const FBox2D & Box, const TCHAR * DebugContext) private
Internal recursive implementation of.
See also
Insert
Definition at line 263 of file GenericQuadTree.h.
References bInternal, Box, check, GetQuads(), InsertElementRecursive(), MinimumQuadSize, Nodes, Position, Split(), FMath::Square(), TEXT, TreeBox, UE_LOG, and Verbose.
Referenced by Insert(), and InsertElementRecursive().
operator=()
template<typename ElementType, int32 NodeCapacity> TQuadTree< ElementType, NodeCapacity > & TQuadTree< ElementType, NodeCapacity >::operator= (const TQuadTree< ElementType, NodeCapacity > & Other)
Definition at line 131 of file GenericQuadTree.h.
References TQuadTree(), and Other.
Remove()
template<typename ElementType, int32 NodeCapacity> bool TQuadTree< ElementType, NodeCapacity >::Remove (const ElementType & Instance, const FBox2D & Box)
Removes an object of type ElementType with an associated 2D box of size Box (log n).
Does not cleanup tree
Definition at line 329 of file GenericQuadTree.h.
References Box, GetQuads(), Remove(), and RemoveNodeForElement().
Referenced by Remove().
RemoveNodeForElement()
template<typename ElementType, int32 NodeCapacity> bool TQuadTree< ElementType, NodeCapacity >::RemoveNodeForElement (const ElementType & Element) private
Given a list of nodes, remove the node that contains the given element.
Definition at line 307 of file GenericQuadTree.h.
References INDEX_NONE, No, and Nodes.
Referenced by Remove().
Serialize()
template<typename ElementType, int32 NodeCapacity> void TQuadTree< ElementType, NodeCapacity >::Serialize (FArchive & Ar)
Definition at line 138 of file GenericQuadTree.h.
References Ar, bInternal, MinimumQuadSize, Nodes, Position, SubTrees, and TreeBox.
Split()
template<typename ElementType, int32 NodeCapacity> void TQuadTree< ElementType, NodeCapacity >::Split () private
Split the tree into 4 sub-trees.
Definition at line 190 of file GenericQuadTree.h.
References TArray< InElementType, InAllocatorType >::Add(), bInternal, BottomLeft, BottomRight, check, GetQuads(), MinimumQuadSize, Nodes, Position, SubTrees, TopLeft, TopRight, TreeBox, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by InsertElementRecursive().
Field Documentation
bInternal
template<typename ElementType, int32 NodeCapacity = 4> bool TQuadTree< ElementType, NodeCapacity >::bInternal private
Whether this is a leaf or an internal sub-tree.
Definition at line 121 of file GenericQuadTree.h.
Referenced by TQuadTree(), Duplicate(), Empty(), GetQuads(), InsertElementRecursive(), Serialize(), and Split().
MinimumQuadSize
template<typename ElementType, int32 NodeCapacity = 4> float TQuadTree< ElementType, NodeCapacity >::MinimumQuadSize private
The smallest size of a quad allowed in the tree.
Definition at line 118 of file GenericQuadTree.h.
Referenced by TQuadTree(), Duplicate(), InsertElementRecursive(), Serialize(), and Split().
Nodes
template<typename ElementType, int32 NodeCapacity = 4> TArray<FNode> TQuadTree< ElementType, NodeCapacity >::Nodes private
Contains the actual elements this tree is responsible for.
Nodes are used to keep track of each element's AABB as well. For a non-internal leaf, this is the list of nodes that are fully contained within this tree. For an internal tree, this contains the nodes that overlap multiple subtrees.
Definition at line 106 of file GenericQuadTree.h.
Referenced by Duplicate(), Empty(), GetIntersectingElements(), GetIntersectingElements(), InsertElementRecursive(), RemoveNodeForElement(), Serialize(), and Split().
Position
template<typename ElementType, int32 NodeCapacity = 4> FVector2D TQuadTree< ElementType, NodeCapacity >::Position private
Center position of the tree.
Definition at line 115 of file GenericQuadTree.h.
Referenced by TQuadTree(), Duplicate(), GetQuads(), InsertElementRecursive(), Serialize(), and Split().
SubTrees
template<typename ElementType, int32 NodeCapacity = 4> TreeType* TQuadTree< ElementType, NodeCapacity >::SubTrees[4] = {nullptr} private
The sub-trees of this tree.
Definition at line 109 of file GenericQuadTree.h.
Referenced by TQuadTree(), ~TQuadTree(), Duplicate(), Empty(), GetQuads(), Serialize(), and Split().
TreeBox
template<typename ElementType, int32 NodeCapacity = 4> FBox2D TQuadTree< ElementType, NodeCapacity >::TreeBox private
AABB of the tree.
Definition at line 112 of file GenericQuadTree.h.
Referenced by TQuadTree(), Duplicate(), Insert(), InsertElementRecursive(), Serialize(), and Split().
The documentation for this class was generated from the following file:
GenericQuadTree.h