Unreal Engine 5.6 C++ API: FCachingEditorCommands Class Reference
FCachingEditorCommands Class Reference
#include "CacheEditorCommands.h"
Public Member Functions
FCachingEditorCommands ()
virtual ~FCachingEditorCommands ()=default
virtual CHAOSCACHINGEDITOR_API void RegisterCommands ()
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TSharedPtr< FUICommandInfo > CreateCacheManager
Additional Inherited Members
Static Public Member Functions inherited from TCommands< FCachingEditorCommands >
static FCachingEditorCommands & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Protected Member Functions inherited from TCommands< FCachingEditorCommands >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TCommands< FCachingEditorCommands >
static TWeakPtr< FCachingEditorCommands > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 8 of file CacheEditorCommands.h.
Constructor & Destructor Documentation
FCachingEditorCommands()
FCachingEditorCommands::FCachingEditorCommands () inline
Definition at line 11 of file CacheEditorCommands.h.
References FCachingEditorCommands(), TCommands< FCachingEditorCommands >::TCommands(), NSLOCTEXT, and TEXT.
Referenced by FCachingEditorCommands().
~FCachingEditorCommands()
virtual FCachingEditorCommands::~FCachingEditorCommands () virtual default
Member Function Documentation
RegisterCommands()
virtual CHAOSCACHINGEDITOR_API void FCachingEditorCommands::RegisterCommands () virtual
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Implements TCommands< FCachingEditorCommands >.
Field Documentation
CreateCacheManager
TSharedPtr<FUICommandInfo> FCachingEditorCommands::CreateCacheManager
Definition at line 21 of file CacheEditorCommands.h.
The documentation for this class was generated from the following file:
CacheEditorCommands.h