Unreal Engine 5.6 C++ API: Metasound::VertexDataPrivate::TFactoryFacade< Type > Struct Template Reference
Metasound::VertexDataPrivate::TFactoryFacade< Type > Struct Template Reference
TFactoryFacace is a factory for data types which uses the class template type to determine which flavor of DataReference to create.
#include "MetasoundVertexData.h"
Static Public Member Functions
template<typename ... ArgTypes>
static Type CreateWithArgs (ArgTypes &&... Args)
static Type CreateWithLiteral (const FOperatorSettings &InSettings, const FLiteral &InLiteral)
Detailed Description
template<typename Type>
struct Metasound::VertexDataPrivate::TFactoryFacade< Type >
TFactoryFacace is a factory for data types which uses the class template type to determine which flavor of DataReference to create.
Definition at line 97 of file MetasoundVertexData.h.
Member Function Documentation
CreateWithArgs()
template<typename Type> template<typename ... ArgTypes> Type Metasound::VertexDataPrivate::TFactoryFacade< Type >::CreateWithArgs (ArgTypes &&... Args) inline static
Definition at line 105 of file MetasoundVertexData.h.
References Forward().
Referenced by Metasound::VertexDataPrivate::FInputBinding::GetOrConstructAs(), and Metasound::VertexDataPrivate::FOutputBinding::GetOrConstructAs().
CreateWithLiteral()
template<typename Type> Type Metasound::VertexDataPrivate::TFactoryFacade< Type >::CreateWithLiteral (const FOperatorSettings & InSettings, const FLiteral & InLiteral) inline static
Definition at line 99 of file MetasoundVertexData.h.
References Metasound::TDataLiteralFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateExplicitArgs().
Referenced by Metasound::VertexDataPrivate::FInputBinding::GetOrCreateDefaultAs().
The documentation for this struct was generated from the following file:
MetasoundVertexData.h