Unreal Engine 5.6 C++ API: Metasound::Frontend::TBoundAnalyzerOutput< DataType > Class Template Reference
Metasound::Frontend::TBoundAnalyzerOutput< DataType > Class Template Reference final
#include "MetasoundFrontendVertexAnalyzer.h"
Public Member Functions
TBoundAnalyzerOutput (const FAnalyzerAddress &InAnalyzerOutputAddress, const FOperatorSettings &InOperatorSettings, TDataReadReference< DataType > InData)
virtual ~TBoundAnalyzerOutput () override
virtual TSharedPtr< IOutputStorage > CreateOutputData () const override
virtual FAnyDataReference GetDataReference () const override
virtual void PushData () override
Public Member Functions inherited from Metasound::Frontend::IBoundAnalyzerOutput
virtual ~IBoundAnalyzerOutput ()=default
Private Attributes
FAnalyzerAddress Address
TDataReadReference< DataType > DataRef
TUniquePtr< TSender< DataType > > Sender
Detailed Description
template<typename DataType>
class Metasound::Frontend::TBoundAnalyzerOutput< DataType >
Definition at line 84 of file MetasoundFrontendVertexAnalyzer.h.
Constructor & Destructor Documentation
TBoundAnalyzerOutput()
template<typename DataType> Metasound::Frontend::TBoundAnalyzerOutput< DataType >::TBoundAnalyzerOutput (const FAnalyzerAddress & InAnalyzerOutputAddress, const FOperatorSettings & InOperatorSettings, TDataReadReference< DataType > InData) inline
Definition at line 87 of file MetasoundFrontendVertexAnalyzer.h.
References Address, DataRef, ensure, Metasound::FDataTransmissionCenter::Get(), Metasound::FDataTransmissionCenter::RegisterNewSender(), and Sender.
~TBoundAnalyzerOutput()
template<typename DataType> virtual Metasound::Frontend::TBoundAnalyzerOutput< DataType >::~TBoundAnalyzerOutput () inline override virtual
Definition at line 95 of file MetasoundFrontendVertexAnalyzer.h.
References Address, Metasound::FDataTransmissionCenter::Get(), Sender, and Metasound::FDataTransmissionCenter::UnregisterDataChannel().
Member Function Documentation
CreateOutputData()
template<typename DataType> virtual TSharedPtr< IOutputStorage > Metasound::Frontend::TBoundAnalyzerOutput< DataType >::CreateOutputData () const inline override virtual
Implements Metasound::Frontend::IBoundAnalyzerOutput.
Definition at line 122 of file MetasoundFrontendVertexAnalyzer.h.
References MakeShared().
GetDataReference()
template<typename DataType> virtual FAnyDataReference Metasound::Frontend::TBoundAnalyzerOutput< DataType >::GetDataReference () const inline override virtual
Implements Metasound::Frontend::IBoundAnalyzerOutput.
Definition at line 109 of file MetasoundFrontendVertexAnalyzer.h.
References DataRef.
PushData()
template<typename DataType> virtual void Metasound::Frontend::TBoundAnalyzerOutput< DataType >::PushData () inline override virtual
Implements Metasound::Frontend::IBoundAnalyzerOutput.
Definition at line 114 of file MetasoundFrontendVertexAnalyzer.h.
References DataRef, and Sender.
Field Documentation
Address
template<typename DataType> FAnalyzerAddress Metasound::Frontend::TBoundAnalyzerOutput< DataType >::Address private
Definition at line 128 of file MetasoundFrontendVertexAnalyzer.h.
Referenced by TBoundAnalyzerOutput(), and ~TBoundAnalyzerOutput().
DataRef
template<typename DataType> TDataReadReference<DataType> Metasound::Frontend::TBoundAnalyzerOutput< DataType >::DataRef private
Definition at line 129 of file MetasoundFrontendVertexAnalyzer.h.
Referenced by TBoundAnalyzerOutput(), GetDataReference(), and PushData().
Sender
template<typename DataType> TUniquePtr<TSender<DataType> > Metasound::Frontend::TBoundAnalyzerOutput< DataType >::Sender private
Definition at line 130 of file MetasoundFrontendVertexAnalyzer.h.
Referenced by TBoundAnalyzerOutput(), ~TBoundAnalyzerOutput(), and PushData().
The documentation for this class was generated from the following file:
MetasoundFrontendVertexAnalyzer.h