Unreal Engine 5.6 C++ API: UCurveLinearColor Class Reference
UCurveLinearColor Class Reference
#include "CurveLinearColor.h"
Public Member Functions
void DrawThumbnail (class FCanvas *Canvas, FVector2D StartXY, FVector2D SizeXY)
virtual void OnCurveChanged (const TArray< FRichCurveEditInfo > &ChangedCurveEditInfos) override
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
void PushToSourceData (TArray< FFloat16Color > &SrcData, int32 StartXY, FVector2D SizeXY)
void PushUnadjustedToSourceData (TArray< FFloat16Color > &SrcData, int32 StartXY, FVector2D SizeXY)
virtual void Serialize (FArchive &Ar) override
UPROPERTY ()) float AdjustBrightness
UPROPERTY ()) float AdjustBrightnessCurve
UPROPERTY ()) float AdjustHue
UPROPERTY ()) float AdjustMaxAlpha
UPROPERTY ()) float AdjustMinAlpha
UPROPERTY ()) float AdjustSaturation
UPROPERTY ()) float AdjustVibrance
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() FRichCurve FloatCurves[4]
Keyframe data, one curve for red, green, blue, and alpha.
virtual TArray< FRichCurveEditInfoConst > GetCurves () const override
virtual TArray< FRichCurveEditInfo > GetCurves () override
bool HasAnyAlphaKeys () const override
virtual bool IsLinearColorCurve () const override
virtual bool IsValidCurve (FRichCurveEditInfo CurveInfo) override
bool operator== (const UCurveLinearColor &Curve) const
Determine if Curve is the same.
UFUNCTION () 1 FLinearColor GetUnadjustedLinearColorValue(float InTime) const
UFUNCTION () 1 virtual FLinearColor GetClampedLinearColorValue(float InTime) const override
UFUNCTION () 1 virtual FLinearColor GetLinearColorValue(float InTime) const override
Detailed Description
Definition at line 30 of file CurveLinearColor.h.
Member Function Documentation
DrawThumbnail()
void UCurveLinearColor::DrawThumbnail (class FCanvas * Canvas, FVector2D StartXY, FVector2D SizeXY)
GENERATED_UCLASS_BODY()
UCurveLinearColor::GENERATED_UCLASS_BODY () private
Keyframe data, one curve for red, green, blue, and alpha.
References UPROPERTY().
GetCurves() [1/2]
virtual TArray< FRichCurveEditInfoConst > UCurveLinearColor::GetCurves () const override private virtual
References GetCurves().
Referenced by GetCurves(), and GetCurves().
GetCurves() [2/2]
virtual TArray< FRichCurveEditInfo > UCurveLinearColor::GetCurves () override private virtual
References GetCurves().
HasAnyAlphaKeys()
bool UCurveLinearColor::HasAnyAlphaKeys () const inline override private
Definition at line 52 of file CurveLinearColor.h.
References HasAnyAlphaKeys().
Referenced by HasAnyAlphaKeys().
IsLinearColorCurve()
virtual bool UCurveLinearColor::IsLinearColorCurve () const inline override private virtual
Definition at line 41 of file CurveLinearColor.h.
References IsLinearColorCurve().
Referenced by IsLinearColorCurve().
IsValidCurve()
virtual bool UCurveLinearColor::IsValidCurve (FRichCurveEditInfo CurveInfo) override private virtual
OnCurveChanged()
virtual void UCurveLinearColor::OnCurveChanged (const TArray< FRichCurveEditInfo > & ChangedCurveEditInfos) override virtual
operator==()
bool UCurveLinearColor::operator== (const UCurveLinearColor & Curve) const private
Determine if Curve is the same.
PostEditChangeProperty()
virtual void UCurveLinearColor::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostLoad()
virtual void UCurveLinearColor::PostLoad () override virtual
PushToSourceData()
void UCurveLinearColor::PushToSourceData (TArray< FFloat16Color > & SrcData, int32 StartXY, FVector2D SizeXY)
PushUnadjustedToSourceData()
void UCurveLinearColor::PushUnadjustedToSourceData (TArray< FFloat16Color > & SrcData, int32 StartXY, FVector2D SizeXY)
Serialize()
virtual void UCurveLinearColor::Serialize (FArchive & Ar) override virtual
References Ar.
UFUNCTION() [1/3]
UCurveLinearColor::UFUNCTION () const private
References Category, InTime, and UFUNCTION().
UFUNCTION() [2/3]
UCurveLinearColor::UFUNCTION () const override private
References Category, InTime, and UFUNCTION().
UFUNCTION() [3/3]
UCurveLinearColor::UFUNCTION () const override private
References Category, and InTime.
Referenced by UFUNCTION(), and UFUNCTION().
UPROPERTY() [1/7]
UCurveLinearColor::UPROPERTY ()
References Category, meta, and UPROPERTY().
UPROPERTY() [2/7]
UCurveLinearColor::UPROPERTY ()
References Category, meta, and UPROPERTY().
UPROPERTY() [3/7]
UCurveLinearColor::UPROPERTY ()
References Category, float, and meta.
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [4/7]
UCurveLinearColor::UPROPERTY ()
References Category, meta, and UPROPERTY().
UPROPERTY() [5/7]
UCurveLinearColor::UPROPERTY ()
References Category, meta, and UPROPERTY().
UPROPERTY() [6/7]
UCurveLinearColor::UPROPERTY ()
References Category, meta, and UPROPERTY().
UPROPERTY() [7/7]
UCurveLinearColor::UPROPERTY ()
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
CurveLinearColor.h