Unreal Engine 5.6 C++ API: FNavigationConfig Class Reference
FNavigationConfig Class Reference
This class is used to control which FKeys and analog axis should move focus.
#include "NavigationConfig.h"
Public Member Functions
FNavigationConfig ()
ctor
virtual ~FNavigationConfig ()
dtor
virtual EUINavigationAction GetNavigationActionFromKey (const FKeyEvent &InKeyEvent) const
Returns the navigation action corresponding to a key event.
virtual EUINavigation GetNavigationDirectionFromAnalog (const FAnalogInputEvent &InAnalogEvent)
Gets the navigation direction from a given analog event.
virtual EUINavigation GetNavigationDirectionFromKey (const FKeyEvent &InKeyEvent) const
Gets the navigation direction from a given key event.
bool IsAnalogEventBeyondNavigationThreshold (const FAnalogInputEvent &InAnalogEvent) const
Returns whether the analog event is beyond the navigation thresholds set in this config.
virtual void OnNavigationChangedFocus (TSharedPtr< SWidget > OldWidget, TSharedPtr< SWidget > NewWidget, FFocusEvent FocusEvent)
Notified when navigation has caused a widget change to occur.
virtual void OnRegister ()
Called when the navigation config is registered with Slate Application.
virtual void OnUnregister ()
Called when the navigation config is registered with Slate Application.
virtual void OnUserRemoved (int32 UserIndex)
Notified when users are removed from the system, good chance to clean up any user specific state.
virtual FString ToString () const
Simplification of config as string.
UE_DEPRECATED (4.24, "GetNavigationActionForKey doesn't handle multiple users properly, use GetNavigationActionFromKey instead") 1 virtual EUINavigationAction GetNavigationActionForKey(const FKey &InKey) const
Public Member Functions inherited from TSharedFromThis< FNavigationConfig >
TSharedRef< FNavigationConfig, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FNavigationConfig, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FKey AnalogHorizontalKey
Which Axis Key controls horizontal navigation.
float AnalogNavigationHorizontalThreshold
float AnalogNavigationVerticalThreshold
FKey AnalogVerticalKey
Which Axis Key controls vertical navigation.
bool bAnalogNavigation
Should we respect the analog stick for navigation.
bool bIgnoreModifiersForNavigationActions
Should we ignore modifier keys when checking for navigation actions.
bool bKeyNavigation
Should we respect keys for navigation.
bool bTabNavigation
Should the Tab key perform next and previous style navigation.
TMap< FKey, EUINavigationAction > KeyActionRules
Digital key action rules.
TMap< FKey, EUINavigation > KeyEventRules
Digital key navigation rules.
Protected Member Functions
virtual EUINavigation GetNavigationDirectionFromAnalogInternal (const FAnalogInputEvent &InAnalogEvent)
Gets the navigation direction from the analog internally.
virtual float GetRepeatRateForPressure (float InPressure, int32 InRepeats) const
Gets the repeat rate of the navigation based on the current pressure being applied.
virtual bool IsAnalogHorizontalKey (const FKey &InKey) const
virtual bool IsAnalogVerticalKey (const FKey &InKey) const
Protected Member Functions inherited from TSharedFromThis< FNavigationConfig >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TMap< int, FUserNavigationState > UserNavigationState
Navigation state that we store per user.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FNavigationConfig >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
This class is used to control which FKeys and analog axis should move focus.
Definition at line 60 of file NavigationConfig.h.
Constructor & Destructor Documentation
FNavigationConfig()
FNavigationConfig::FNavigationConfig ()
ctor
~FNavigationConfig()
virtual FNavigationConfig::~FNavigationConfig () virtual
dtor
Member Function Documentation
GetNavigationActionFromKey()
virtual EUINavigationAction FNavigationConfig::GetNavigationActionFromKey (const FKeyEvent & InKeyEvent) const virtual
Returns the navigation action corresponding to a key event.
This version will handle multiple users correctly
GetNavigationDirectionFromAnalog()
virtual EUINavigation FNavigationConfig::GetNavigationDirectionFromAnalog (const FAnalogInputEvent & InAnalogEvent) virtual
Gets the navigation direction from a given analog event.
GetNavigationDirectionFromAnalogInternal()
virtual EUINavigation FNavigationConfig::GetNavigationDirectionFromAnalogInternal (const FAnalogInputEvent & InAnalogEvent) protected virtual
Gets the navigation direction from the analog internally.
References GetNavigationDirectionFromAnalogInternal().
Referenced by GetNavigationDirectionFromAnalogInternal().
GetNavigationDirectionFromKey()
virtual EUINavigation FNavigationConfig::GetNavigationDirectionFromKey (const FKeyEvent & InKeyEvent) const virtual
Gets the navigation direction from a given key event.
GetRepeatRateForPressure()
virtual float FNavigationConfig::GetRepeatRateForPressure (float InPressure, int32 InRepeats) const protected virtual
Gets the repeat rate of the navigation based on the current pressure being applied.
The idea being that if the user moves the stick a little, we would navigate slowly, if they move it a lot, we would repeat the navigation often.
References GetRepeatRateForPressure().
Referenced by GetRepeatRateForPressure().
IsAnalogEventBeyondNavigationThreshold()
bool FNavigationConfig::IsAnalogEventBeyondNavigationThreshold (const FAnalogInputEvent & InAnalogEvent) const
Returns whether the analog event is beyond the navigation thresholds set in this config.
References IsAnalogEventBeyondNavigationThreshold().
Referenced by IsAnalogEventBeyondNavigationThreshold().
IsAnalogHorizontalKey()
virtual bool FNavigationConfig::IsAnalogHorizontalKey (const FKey & InKey) const inline protected virtual
Reimplemented in FTwinStickNavigationConfig.
Definition at line 134 of file NavigationConfig.h.
References AnalogHorizontalKey, and IsAnalogHorizontalKey().
Referenced by IsAnalogHorizontalKey().
IsAnalogVerticalKey()
virtual bool FNavigationConfig::IsAnalogVerticalKey (const FKey & InKey) const inline protected virtual
Reimplemented in FTwinStickNavigationConfig.
Definition at line 135 of file NavigationConfig.h.
References AnalogVerticalKey.
OnNavigationChangedFocus()
virtual void FNavigationConfig::OnNavigationChangedFocus (TSharedPtr< SWidget > OldWidget, TSharedPtr< SWidget > NewWidget, FFocusEvent FocusEvent) inline virtual
Notified when navigation has caused a widget change to occur.
Definition at line 81 of file NavigationConfig.h.
OnRegister()
virtual void FNavigationConfig::OnRegister () virtual
Called when the navigation config is registered with Slate Application.
OnUnregister()
virtual void FNavigationConfig::OnUnregister () virtual
Called when the navigation config is registered with Slate Application.
OnUserRemoved()
virtual void FNavigationConfig::OnUserRemoved (int32 UserIndex) virtual
Notified when users are removed from the system, good chance to clean up any user specific state.
ToString()
virtual FString FNavigationConfig::ToString () const virtual
Simplification of config as string.
References ToString().
Referenced by ToString().
UE_DEPRECATED()
FNavigationConfig::UE_DEPRECATED (4. 24, "GetNavigationActionForKey doesn't handle multiple users properly, use GetNavigationActionFromKey instead") const &
Field Documentation
AnalogHorizontalKey
FKey FNavigationConfig::AnalogHorizontalKey
Which Axis Key controls horizontal navigation.
Definition at line 111 of file NavigationConfig.h.
Referenced by IsAnalogHorizontalKey().
AnalogNavigationHorizontalThreshold
float FNavigationConfig::AnalogNavigationHorizontalThreshold
Definition at line 106 of file NavigationConfig.h.
AnalogNavigationVerticalThreshold
float FNavigationConfig::AnalogNavigationVerticalThreshold
Definition at line 108 of file NavigationConfig.h.
AnalogVerticalKey
FKey FNavigationConfig::AnalogVerticalKey
Which Axis Key controls vertical navigation.
Definition at line 113 of file NavigationConfig.h.
Referenced by IsAnalogVerticalKey().
bAnalogNavigation
bool FNavigationConfig::bAnalogNavigation
Should we respect the analog stick for navigation.
Definition at line 101 of file NavigationConfig.h.
Referenced by FNullNavigationConfig::FNullNavigationConfig().
bIgnoreModifiersForNavigationActions
bool FNavigationConfig::bIgnoreModifiersForNavigationActions
Should we ignore modifier keys when checking for navigation actions.
If false, only unmodified keys will be processed.
Definition at line 103 of file NavigationConfig.h.
bKeyNavigation
bool FNavigationConfig::bKeyNavigation
Should we respect keys for navigation.
Definition at line 99 of file NavigationConfig.h.
Referenced by FNullNavigationConfig::FNullNavigationConfig().
bTabNavigation
bool FNavigationConfig::bTabNavigation
Should the Tab key perform next and previous style navigation.
Definition at line 97 of file NavigationConfig.h.
Referenced by FNullNavigationConfig::FNullNavigationConfig().
KeyActionRules
TMap<FKey, EUINavigationAction> FNavigationConfig::KeyActionRules
Digital key action rules.
Definition at line 119 of file NavigationConfig.h.
KeyEventRules
TMap<FKey, EUINavigation> FNavigationConfig::KeyEventRules
Digital key navigation rules.
Definition at line 116 of file NavigationConfig.h.
UserNavigationState
TMap<int, FUserNavigationState> FNavigationConfig::UserNavigationState protected
Navigation state that we store per user.
Definition at line 138 of file NavigationConfig.h.
The documentation for this class was generated from the following file:
NavigationConfig.h