Unreal Engine 5.6 C++ API: FAnimationUtils Class Reference
FAnimationUtils Class Reference
A collection of useful functions for skeletal mesh animation.
#include "AnimationUtils.h"
Public Member Functions
UE_DEPRECATED (5.1, "ExtractTransformFromCompressionData has been deprecated, use different signature") static void ExtractTransformFromCompressionData(const FCompressibleAnimData &CompressibleAnimData
UE_DEPRECATED (5.1, "ExtractTransformFromTrack has been deprecated, use different signature") 1 static void ExtractTransformFromTrack(float Time
Static Public Member Functions
static void BuildComponentSpaceTransform (FTransform &OutTransform, int32 BoneIndex, const TArray< FTransform > &BoneSpaceTransforms, const TArray< FBoneData > &BoneData)
Builds the local-to-component matrix for the specified bone.
static void BuildSkeletonMetaData (USkeleton *Skeleton, TArray< FBoneData > &OutBoneData)
static void CalculateTrackHeights (const FCompressibleAnimData &CompressibleAnimData, int NumTracks, TArray< int32 > &TrackHeights)
Computes the 'height' of each track, relative to a given animation linkup.
static bool CompressAnimBones (FCompressibleAnimData &AnimSeq, FCompressibleAnimDataResult &Target)
Compresses the animation bones within a sequence with the chosen settings.
static bool CompressAnimCurves (FCompressibleAnimData &AnimSeq, FCompressedAnimSequence &Target)
Compresses the animation curves within a sequence with the chosen settings.
static void ComputeCompressionError (const FCompressibleAnimData &CompressibleAnimData, FCompressibleAnimDataResult &CompressedData, AnimationErrorStats &ErrorStats)
Utility function to measure the accuracy of a compressed animation.
static void EnsureAnimSequenceLoaded (UAnimSequence &AnimSeq)
Makes sure that the animation sequence and all its dependencies required for compression are loaded.
static void ExtractTransformForFrameFromTrack (const FRawAnimSequenceTrack &RawTrack, int32 Frame, FTransform &OutAtom)
static void ExtractTransformForFrameFromTrackSafe (const FRawAnimSequenceTrack &RawTrack, int32 Frame, FTransform &OutAtom)
static void ExtractTransformFromCompressionData (const FCompressibleAnimData &CompressibleAnimData, FCompressibleAnimDataResult &CompressedAnimData, double Time, int32 TrackIndex, bool bUseRawData, FTransform &OutBoneTransform)
static void ExtractTransformFromTrack (const struct FRawAnimSequenceTrack &RawTrack, double Time, int32 NumFrames, double SequenceLength, EAnimInterpolationType Interpolation, FTransform &OutAtom)
static FString GetAnimationCompressionFormatString (enum AnimationCompressionFormat InFormat)
Converts an animation compression type into a human readable string.
static FString GetAnimationKeyFormatString (enum AnimationKeyFormat InFormat)
Converts an animation codec format into a human readable string.
static int32 GetAnimTrackIndexForSkeletonBone (const int32 InSkeletonBoneIndex, const TArray< FTrackToSkeletonMap > &TrackToSkelMap)
static UAnimBoneCompressionSettings * GetDefaultAnimationBoneCompressionSettings ()
Returns the default animation bone compression settings, can never by null.
static UAnimCurveCompressionSettings * GetDefaultAnimationCurveCompressionSettings ()
Returns the default animation curve compression settings, can never by null.
static UAnimBoneCompressionSettings * GetDefaultAnimationRecorderBoneCompressionSettings ()
Returns the default animation bone compression settings for the FAnimRecorder, can never by null.
static UObject * GetDefaultAnimSequenceOuter (UAnimSet *InAnimSet, bool bCreateIfNotFound)
Get default Outer for AnimSequences contained in this AnimSet.
static UVariableFrameStrippingSettings * GetDefaultVariableFrameStrippingSettings ()
Returns the default animation variable frame stripping settings, can never by null.
static bool GetForcedRecompressionSetting ()
Determines the current setting for recompressing all animations upon load.
static bool HasUniformKeySpacing (int32 NumFrames, const TArray< float > &Times)
Checks a set of key times to see if the spacing is uniform or non-uniform.
static void PreloadCompressionSettings ()
Preload the bone, curve and recorder compression settings.
static void TallyErrorsFromPerturbation (const FCompressibleAnimData &CompressibleAnimData, int32 NumTracks, const FVector &PositionNudge, const FQuat &RotationNudge, const FVector &ScaleNudge, TArray< FAnimPerturbationError > &InducedErrors)
Perturbs the bone(s) associated with each track in turn, measuring the maximum error introduced in end effectors as a result.
Data Fields
FCompressibleAnimDataResult float int32 bool bUseRawData
FCompressibleAnimDataResult & CompressedAnimData
int32 float const struct FRawAnimSequenceTrack EAnimInterpolationType Interpolation
int32 NumFrames
int32 float const struct FRawAnimSequenceTrack EAnimInterpolationType FTransform & OutAtom
FCompressibleAnimDataResult float int32 bool FTransform & OutBoneTransform
int32 float const struct FRawAnimSequenceTrack & RawTrack
int32 float SequenceLength
FCompressibleAnimDataResult float Time
FCompressibleAnimDataResult float int32 TrackIndex
Detailed Description
A collection of useful functions for skeletal mesh animation.
Definition at line 53 of file AnimationUtils.h.
Member Function Documentation
BuildComponentSpaceTransform()
void FAnimationUtils::BuildComponentSpaceTransform (FTransform & OutTransform, int32 BoneIndex, const TArray< FTransform > & BoneSpaceTransforms, const TArray< FBoneData > & BoneData) static
Builds the local-to-component matrix for the specified bone.
BuildSkeletonMetaData()
void FAnimationUtils::BuildSkeletonMetaData (USkeleton * Skeleton, TArray< FBoneData > & OutBoneData) static
References Skeleton.
CalculateTrackHeights()
void FAnimationUtils::CalculateTrackHeights (const FCompressibleAnimData & CompressibleAnimData, int NumTracks, TArray< int32 > & TrackHeights) static
Computes the 'height' of each track, relative to a given animation linkup.
The track height is defined as the minimal number of bones away from an end effector (end effectors are 0, their parents are 1, etc...)
Parameters
AnimLinkup The animation linkup
NumTracks The number of tracks
TrackHeights [OUT] The computed track heights
CompressAnimBones()
bool FAnimationUtils::CompressAnimBones (FCompressibleAnimData & AnimSeq, FCompressibleAnimDataResult & Target) static
Compresses the animation bones within a sequence with the chosen settings.
Note: This modifies the sequence.
Returns
Returns true on success, false it we fail to compress
References CompressAnimBones(), and Target.
Referenced by CompressAnimBones().
CompressAnimCurves()
bool FAnimationUtils::CompressAnimCurves (FCompressibleAnimData & AnimSeq, FCompressedAnimSequence & Target) static
Compresses the animation curves within a sequence with the chosen settings.
Note: This modifies the sequence.
Returns
Returns true on success, false it we fail to compress
References CompressAnimCurves(), and Target.
Referenced by CompressAnimCurves().
ComputeCompressionError()
void FAnimationUtils::ComputeCompressionError (const FCompressibleAnimData & CompressibleAnimData, FCompressibleAnimDataResult & CompressedData, AnimationErrorStats & ErrorStats) static
Utility function to measure the accuracy of a compressed animation.
Each end-effector is checked for world-space movement as a result of compression.
Parameters
AnimSet The animset to calculate compression error for.
BoneData BoneData array describing the hierarchy of the animated skeleton
ErrorStats Output structure containing the final compression error values
Returns
None.
References CompressedData.
EnsureAnimSequenceLoaded()
void FAnimationUtils::EnsureAnimSequenceLoaded (UAnimSequence & AnimSeq) static
Makes sure that the animation sequence and all its dependencies required for compression are loaded.
ExtractTransformForFrameFromTrack()
void FAnimationUtils::ExtractTransformForFrameFromTrack (const FRawAnimSequenceTrack & RawTrack, int32 Frame, FTransform & OutAtom) static
References OutAtom, and RawTrack.
ExtractTransformForFrameFromTrackSafe()
void FAnimationUtils::ExtractTransformForFrameFromTrackSafe (const FRawAnimSequenceTrack & RawTrack, int32 Frame, FTransform & OutAtom) static
References OutAtom, and RawTrack.
ExtractTransformFromCompressionData()
void FAnimationUtils::ExtractTransformFromCompressionData (const FCompressibleAnimData & CompressibleAnimData, FCompressibleAnimDataResult & CompressedAnimData, double Time, int32 TrackIndex, bool bUseRawData, FTransform & OutBoneTransform) static
References bUseRawData, CompressedAnimData, ExtractTransformFromCompressionData(), OutBoneTransform, Time, and TrackIndex.
Referenced by ExtractTransformFromCompressionData().
ExtractTransformFromTrack()
void FAnimationUtils::ExtractTransformFromTrack (const struct FRawAnimSequenceTrack & RawTrack, double Time, int32 NumFrames, double SequenceLength, EAnimInterpolationType Interpolation, FTransform & OutAtom) static
References ExtractTransformFromTrack(), Interpolation, NumFrames, OutAtom, RawTrack, SequenceLength, and Time.
Referenced by ExtractTransformFromTrack().
GetAnimationCompressionFormatString()
FString FAnimationUtils::GetAnimationCompressionFormatString (enum AnimationCompressionFormat InFormat) static
Converts an animation compression type into a human readable string.
Parameters
InFormat The compression format to convert into a string
Returns
The format as a string
GetAnimationKeyFormatString()
FString FAnimationUtils::GetAnimationKeyFormatString (enum AnimationKeyFormat InFormat) static
Converts an animation codec format into a human readable string.
Parameters
InFormat The format to convert into a string
Returns
The format as a string
GetAnimTrackIndexForSkeletonBone()
int32 FAnimationUtils::GetAnimTrackIndexForSkeletonBone (const int32 InSkeletonBoneIndex, const TArray< FTrackToSkeletonMap > & TrackToSkelMap) static
GetDefaultAnimationBoneCompressionSettings()
UAnimBoneCompressionSettings * FAnimationUtils::GetDefaultAnimationBoneCompressionSettings () static
Returns the default animation bone compression settings, can never by null.
GetDefaultAnimationCurveCompressionSettings()
UAnimCurveCompressionSettings * FAnimationUtils::GetDefaultAnimationCurveCompressionSettings () static
Returns the default animation curve compression settings, can never by null.
GetDefaultAnimationRecorderBoneCompressionSettings()
UAnimBoneCompressionSettings * FAnimationUtils::GetDefaultAnimationRecorderBoneCompressionSettings () static
Returns the default animation bone compression settings for the FAnimRecorder, can never by null.
GetDefaultAnimSequenceOuter()
UObject * FAnimationUtils::GetDefaultAnimSequenceOuter (UAnimSet * InAnimSet, bool bCreateIfNotFound) static
Get default Outer for AnimSequences contained in this AnimSet.
The intent is to use that when Constructing new AnimSequences to put into that set. The Outer will be Package.<AnimSetName>_Group.
Parameters
bCreateIfNotFound if true, Group will be created. This is only in the editor.
GetDefaultVariableFrameStrippingSettings()
UVariableFrameStrippingSettings * FAnimationUtils::GetDefaultVariableFrameStrippingSettings () static
Returns the default animation variable frame stripping settings, can never by null.
GetForcedRecompressionSetting()
bool FAnimationUtils::GetForcedRecompressionSetting () static
Determines the current setting for recompressing all animations upon load.
The default value is False, but may be overridden by an optional field in the base engine INI file.
Returns
true if the engine settings request that all animations be recompiled
HasUniformKeySpacing()
bool FAnimationUtils::HasUniformKeySpacing (int32 NumFrames, const TArray< float > & Times) static
Checks a set of key times to see if the spacing is uniform or non-uniform.
Note: If there are as many times as frames, they are automatically assumed to be uniformly spaced. Note: If there are two or fewer times, they are automatically assumed to be uniformly spaced.
Parameters
NumFrames The number of frames in the source animation data
Times The array of key times
Returns
true if the keys are uniformly spaced (or one of the trivial conditions is detected). false if any key spacing is greater than 1e-4 off.
References NumFrames.
PreloadCompressionSettings()
void FAnimationUtils::PreloadCompressionSettings () static
Preload the bone, curve and recorder compression settings.
TallyErrorsFromPerturbation()
void FAnimationUtils::TallyErrorsFromPerturbation (const FCompressibleAnimData & CompressibleAnimData, int32 NumTracks, const FVector & PositionNudge, const FQuat & RotationNudge, const FVector & ScaleNudge, TArray< FAnimPerturbationError > & InducedErrors) static
Perturbs the bone(s) associated with each track in turn, measuring the maximum error introduced in end effectors as a result.
References FVector.
UE_DEPRECATED() [1/2]
FAnimationUtils::UE_DEPRECATED (5. 1, "ExtractTransformFromCompressionData has been deprecated, use different signature") const &
UE_DEPRECATED() [2/2]
FAnimationUtils::UE_DEPRECATED (5. 1, "ExtractTransformFromTrack has been deprecated, use different signature")
Field Documentation
bUseRawData
FCompressibleAnimDataResult float int32 bool FAnimationUtils::bUseRawData
Definition at line 185 of file AnimationUtils.h.
Referenced by ExtractTransformFromCompressionData().
CompressedAnimData
FCompressibleAnimDataResult& FAnimationUtils::CompressedAnimData
Definition at line 185 of file AnimationUtils.h.
Referenced by ExtractTransformFromCompressionData().
Interpolation
int32 float const struct FRawAnimSequenceTrack EAnimInterpolationType FAnimationUtils::Interpolation
Definition at line 179 of file AnimationUtils.h.
Referenced by ExtractTransformFromTrack().
NumFrames
int32 FAnimationUtils::NumFrames
Definition at line 179 of file AnimationUtils.h.
Referenced by ExtractTransformFromTrack(), and HasUniformKeySpacing().
OutAtom
int32 float const struct FRawAnimSequenceTrack EAnimInterpolationType FTransform& FAnimationUtils::OutAtom
Definition at line 179 of file AnimationUtils.h.
Referenced by ExtractTransformForFrameFromTrack(), ExtractTransformForFrameFromTrackSafe(), and ExtractTransformFromTrack().
OutBoneTransform
FCompressibleAnimDataResult float int32 bool FTransform& FAnimationUtils::OutBoneTransform
Definition at line 185 of file AnimationUtils.h.
Referenced by ExtractTransformFromCompressionData().
RawTrack
int32 float const struct FRawAnimSequenceTrack& FAnimationUtils::RawTrack
Definition at line 179 of file AnimationUtils.h.
Referenced by ExtractTransformForFrameFromTrack(), ExtractTransformForFrameFromTrackSafe(), and ExtractTransformFromTrack().
SequenceLength
int32 float FAnimationUtils::SequenceLength
Definition at line 179 of file AnimationUtils.h.
Referenced by ExtractTransformFromTrack().
Time
FCompressibleAnimDataResult float FAnimationUtils::Time
Definition at line 185 of file AnimationUtils.h.
Referenced by ExtractTransformFromCompressionData(), and ExtractTransformFromTrack().
TrackIndex
FCompressibleAnimDataResult float int32 FAnimationUtils::TrackIndex
Definition at line 185 of file AnimationUtils.h.
Referenced by ExtractTransformFromCompressionData().
The documentation for this class was generated from the following file:
AnimationUtils.h