Unreal Engine 5.6 C++ API: TAutoConsoleVariable< T > Class Template Reference
TAutoConsoleVariable< T > Class Template Reference
Autoregistering float, int variable class...this changes that value when the console variable is changed.
#include "IConsoleManager.h"
Public Member Functions
TAutoConsoleVariable (const TCHAR *Name, const T &DefaultValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a float, int or string console variable.
TAutoConsoleVariable (const TCHAR *Name, const T &DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a float, int or string console variable.
TAutoConsoleVariable (IConsoleVariable *ExistingObject)
T GetValueOnAnyThread (bool bForceGameThread=false) const
T GetValueOnGameThread () const
T GetValueOnRenderThread () const
FORCEINLINE IConsoleVariable & operator* ()
Dereference back to a variable.
FORCEINLINE const IConsoleVariable & operator* () const
FORCEINLINE IConsoleVariable * operator-> ()
Dereference back to a variable.
FORCEINLINE const IConsoleVariable * operator-> () const
Public Member Functions inherited from FAutoConsoleObject
virtual ~FAutoConsoleObject ()
Destructor, removes the console object.
FORCEINLINE IConsoleVariable * AsVariable ()
returns the contained console object as an IConsoleVariable
FORCEINLINE const IConsoleVariable * AsVariable () const
returns the contained console object as an IConsoleVariable
Private Attributes
TConsoleVariableData< T > * Ref
Additional Inherited Members
Static Public Member Functions inherited from FAutoConsoleObject
static TArray< const FAutoConsoleObject * > & AccessDesktopShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessGeneralShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessMobileShaderChangeCvars ()
Protected Member Functions inherited from FAutoConsoleObject
FAutoConsoleObject (IConsoleObject *InTarget)
Constructor, saves the argument for future removal from the console variable system.
Detailed Description
template<class T>
class TAutoConsoleVariable< T >
Autoregistering float, int variable class...this changes that value when the console variable is changed.
Definition at line 1753 of file IConsoleManager.h.
Constructor & Destructor Documentation
TAutoConsoleVariable() [1/3]
template<class T> TAutoConsoleVariable< T >::TAutoConsoleVariable (IConsoleVariable * ExistingObject) inline
Definition at line 1757 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), IConsoleObject::AsVariableBool(), IConsoleObject::AsVariableFloat(), IConsoleObject::AsVariableInt(), IConsoleObject::AsVariableString(), and Ref.
Referenced by TAutoConsoleVariable(), and TAutoConsoleVariable().
TAutoConsoleVariable() [2/3]
template<class T> TAutoConsoleVariable< T >::TAutoConsoleVariable (const TCHAR * Name, const T & DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a float, int or string console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1788 of file IConsoleManager.h.
References TAutoConsoleVariable(), ECVF_Default, Flags, and Name.
TAutoConsoleVariable() [3/3]
template<class T> TAutoConsoleVariable< T >::TAutoConsoleVariable (const TCHAR * Name, const T & DefaultValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a float, int or string console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1800 of file IConsoleManager.h.
References TAutoConsoleVariable(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
Member Function Documentation
GetValueOnAnyThread()
template<class T> T TAutoConsoleVariable< T >::GetValueOnAnyThread (bool bForceGameThread = false) const inline
Definition at line 1816 of file IConsoleManager.h.
References Ref.
GetValueOnGameThread()
template<class T> T TAutoConsoleVariable< T >::GetValueOnGameThread () const inline
Definition at line 1806 of file IConsoleManager.h.
References Ref.
GetValueOnRenderThread()
template<class T> T TAutoConsoleVariable< T >::GetValueOnRenderThread () const inline
Definition at line 1811 of file IConsoleManager.h.
References Ref.
operator*() [1/2]
template<class T> FORCEINLINE IConsoleVariable & TAutoConsoleVariable< T >::operator* () inline
Dereference back to a variable.
Definition at line 1822 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator*() [2/2]
template<class T> FORCEINLINE const IConsoleVariable & TAutoConsoleVariable< T >::operator* () const inline
Definition at line 1826 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator->() [1/2]
template<class T> FORCEINLINE IConsoleVariable * TAutoConsoleVariable< T >::operator-> () inline
Dereference back to a variable.
Definition at line 1831 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator->() [2/2]
template<class T> FORCEINLINE const IConsoleVariable * TAutoConsoleVariable< T >::operator-> () const inline
Definition at line 1835 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
Field Documentation
Ref
template<class T> TConsoleVariableData<T>* TAutoConsoleVariable< T >::Ref private
Definition at line 1840 of file IConsoleManager.h.
Referenced by TAutoConsoleVariable(), GetValueOnAnyThread(), GetValueOnGameThread(), and GetValueOnRenderThread().
The documentation for this class was generated from the following file:
IConsoleManager.h