Unreal Engine 5.6 C++ API: RenderingThread.h File Reference
RenderingThread.h File Reference
#include "Async/TaskGraphInterfaces.h"
#include "Containers/Array.h"
#include "Containers/List.h"
#include "CoreGlobals.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "Delegates/Delegate.h"
#include "HAL/PlatformMemory.h"
#include "Misc/AssertionMacros.h"
#include "Misc/TVariant.h"
#include "MultiGPU.h"
#include "ProfilingDebugging/CpuProfilerTrace.h"
#include "RHI.h"
#include "RHICommandList.h"
#include "Serialization/MemoryLayout.h"
#include "Stats/Stats.h"
#include "Templates/Atomic.h"
#include "Templates/Function.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "Trace/Trace.h"
#include "Async/Mutex.h"
#include "Tasks/Pipe.h"
Data Structures
class FCoreRenderDelegates
class FRenderCommand
The parent class of commands stored in the rendering command queue.
class FRenderCommandPipe
struct FRenderCommandPipe::FCommand
struct FRenderCommandPipe::FFrame
class FRenderThreadCommandPipe
struct FRenderThreadCommandPipe::FCommand
class FRenderThreadScope
struct FRenderThreadStructBase
class TEnqueueUniqueRenderCommandType< TagType, LambdaType >
struct TRenderCommandTag< TSTR >
Type that contains profiler data necessary to mark up render commands for various profilers.
class TRenderThreadStruct< StructType >
Represents a struct with a lifetime that spans multiple render commands with scoped initialization and release on the render thread.
class UE::RenderCommandPipe::FSyncScope
Namespaces
namespace FFrameEndSync
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::RenderCommandPipe
namespace UE::Trace
Macros
#define DECLARE_RENDER_COMMAND_PIPE(Name, PrefixKeywords)
Declares an extern reference to a render command pipe.
#define DECLARE_RENDER_COMMAND_TAG(Type, Name)
Declares a new render command tag type from a name.
#define DEFINE_RENDER_COMMAND_PIPE(Name, Flags)
Defines a render command pipe.
#define ENQUEUE_RENDER_COMMAND(Type)
Enqueues a render command to a render pipe.
#define LogRenderCommand(TypeName)
#define ShouldExecuteOnRenderThread()
#define UE_API RENDERCORE_API
Typedefs
using FRenderCommandPipeBitArray = TBitArray<FRenderCommandPipeBitArrayAllocator>
using FRenderCommandPipeBitArrayAllocator = TInlineAllocator<1, FConcurrentLinearBitArrayAllocator>
using FRenderCommandPipeSetBitIterator = TConstSetBitIterator<FRenderCommandPipeBitArrayAllocator>
using FStopRenderingThreadDelegate = FStopRenderingThread::FDelegate
Enumerations
enum class FFrameEndSync::EFlushMode { FFrameEndSync::EndFrame , FFrameEndSync::Threads }
enum class ERenderCommandPipeFlags : uint8 { None = 0 , Disabled = 1 << 0 }
enum class ERenderCommandPipeMode { None , RenderThread , All }
Describes which pipes are configured to use the render command pipe system.
Functions
RENDERCORE_API void AdvanceRenderingThreadStatsGT (bool bDiscardCallstack, int64 StatsFrame, int32 DisableChangeTagStartFrame)
Advances stats for the rendering thread.
FORCEINLINE void CheckNotBlockedOnRenderThread ()
Asserts if called from the main thread when the main thread is blocked on the rendering thread.
RENDERCORE_API void CheckRenderingThreadHealth ()
Checks if the rendering thread is healthy and running.
DECLARE_MULTICAST_DELEGATE (FStopRenderingThread)
UE::RenderCommandPipe::DECLARE_MULTICAST_DELEGATE_OneParam (FStopRecordingDelegate, const FRenderCommandPipeBitArray &)
DECLARE_STATS_GROUP (TEXT("Render Thread Commands"), STATGROUP_RenderThreadCommands, STATCAT_Advanced)
template<typename RenderCommandTag, typename LambdaType>
FORCEINLINE_DEBUGGABLE void EnqueueUniqueRenderCommand (LambdaType &&Lambda)
template<typename RenderCommandTag, typename LambdaType>
FORCEINLINE_DEBUGGABLE void EnqueueUniqueRenderCommand (LambdaType &Lambda)
ENUM_CLASS_FLAGS (ERenderCommandPipeFlags)
RENDERCORE_API void FlushRenderingCommands ()
Waits for the rendering thread to finish executing all pending rendering commands.
RENDERCORE_API class FRHICommandListImmediate & GetImmediateCommandList_ForRenderCommand ()
TConstArrayView< FRenderCommandPipe * > UE::RenderCommandPipe::GetPipes ()
RENDERCORE_API FStopRecordingDelegate & UE::RenderCommandPipe::GetStopRecordingDelegate ()
RENDERCORE_API void UE::RenderCommandPipe::Initialize ()
RENDERCORE_API void InitRenderingThread ()
RENDERCORE_API bool UE::RenderCommandPipe::IsRecording ()
RENDERCORE_API bool IsRenderingThreadHealthy ()
Checks if the rendering thread is healthy and running, without crashing.
RENDERCORE_API bool UE::RenderCommandPipe::IsReplaying ()
RENDERCORE_API bool UE::RenderCommandPipe::IsReplaying (const FRenderCommandPipe &Pipe)
RENDERCORE_API void LatchRenderThreadConfiguration ()
RENDERCORE_API FDelegateHandle RegisterStopRenderingThreadDelegate (const FStopRenderingThreadDelegate &InDelegate)
RENDERCORE_API void ShutdownRenderingThread ()
RENDERCORE_API void UE::RenderCommandPipe::StartRecording ()
RENDERCORE_API void UE::RenderCommandPipe::StartRecording (const FRenderCommandPipeBitArray &PipeBits)
RENDERCORE_API void StartRenderCommandFenceBundler ()
RENDERCORE_API FRenderCommandPipeBitArray UE::RenderCommandPipe::StopRecording ()
RENDERCORE_API FRenderCommandPipeBitArray UE::RenderCommandPipe::StopRecording (TConstArrayView< FRenderCommandPipe * > Pipes)
RENDERCORE_API void StopRenderCommandFenceBundler ()
RENDERCORE_API void FFrameEndSync::Sync (EFlushMode FlushMode)
RENDERCORE_API void TickRenderingTickables ()
UE_DEPRECATED (5.6, "FlushPendingDeleteRHIResources_GameThread is deprecated. Enqueue a render command that calls ImmediateFlush(EImmediateFlushType::FlushRHIThreadFlushResources) on the immediate RHI command list instead.") extern RENDERCORE_API void FlushPendingDeleteRHIResources_GameThread()
UE_DEPRECATED (5.6, "FlushPendingDeleteRHIResources_RenderThread is deprecated. Call ImmediateFlush(EImmediateFlushType::FlushRHIThreadFlushResources) on the immediate RHI command list instead.") extern RENDERCORE_API void FlushPendingDeleteRHIResources_RenderThread()
UE_TRACE_CHANNEL_EXTERN (RenderCommandsChannel, RENDERCORE_API)
RENDERCORE_API void UnregisterStopRenderingThreadDelegate (FDelegateHandle InDelegateHandle)
Variables
RENDERCORE_API bool GIsThreadedRendering
Whether the renderer is currently running in a separate thread.
RENDERCORE_API TAtomic< bool > GMainThreadBlockedOnRenderThread
Whether the main thread is currently blocked on the rendering thread, e.g.
RENDERCORE_API TOptional< bool > GPendingUseThreadedRendering
RENDERCORE_API ERenderCommandPipeMode GRenderCommandPipeMode
RENDERCORE_API bool GUseThreadedRendering
Whether the rendering thread should be created or not.
Macro Definition Documentation
DECLARE_RENDER_COMMAND_PIPE
#define DECLARE_RENDER_COMMAND_PIPE (Name, PrefixKeywords)
Value:
    namespace UE::RenderCommandPipe { extern PrefixKeywords FRenderCommandPipe Name; }
Declares an extern reference to a render command pipe.
Definition at line 578 of file RenderingThread.h.
DECLARE_RENDER_COMMAND_TAG
#define DECLARE_RENDER_COMMAND_TAG (Type, Name)
Value:
    struct PREPROCESSOR_JOIN(TSTR_, PREPROCESSOR_JOIN(Name, __LINE__)) \
    {  \
        static const char* CStr() { return #Name; } \
        static const TCHAR* TStr() { return TEXT(#Name); } \
    }; \
    using Type = TRenderCommandTag<PREPROCESSOR_JOIN(TSTR_, PREPROCESSOR_JOIN(Name, __LINE__))>;
Declares a new render command tag type from a name.
Definition at line 214 of file RenderingThread.h.
DEFINE_RENDER_COMMAND_PIPE
#define DEFINE_RENDER_COMMAND_PIPE (Name, Flags)
Value:
    namespace UE::RenderCommandPipe \
    { \
        FRenderCommandPipe Name( \
            TEXT(#Name), \
            Flags, \
            TEXT("r.RenderCommandPipe." #Name), \
            TEXT("Whether to enable the " #Name " Render Command Pipe") \
            TEXT(" 0: off;") \
            TEXT(" 1: on (default)") \
        ); \
    }
Defines a render command pipe.
Definition at line 582 of file RenderingThread.h.
ENQUEUE_RENDER_COMMAND
#define ENQUEUE_RENDER_COMMAND (Type)
Value:
    DECLARE_RENDER_COMMAND_TAG(PREPROCESSOR_JOIN(FRenderCommandTag_, PREPROCESSOR_JOIN(Type, __LINE__)), Type) \
    FRenderCommandPipe::Enqueue<PREPROCESSOR_JOIN(FRenderCommandTag_, PREPROCESSOR_JOIN(Type, __LINE__))>
Enqueues a render command to a render pipe.
The default implementation takes a lambda and schedules on the render thread. Alternative implementations accept either a reference or pointer to an FRenderCommandPipe instance to schedule on an async pipe, if enabled.
Definition at line 599 of file RenderingThread.h.
Referenced by TRenderThreadStruct< StructType >::TRenderThreadStruct(), TWaterInstanceDataBuffers< WITH_WATER_SELECTION_SUPPORT >::TWaterInstanceDataBuffers(), FRenderThreadScope::~FRenderThreadScope(), TRenderThreadStruct< StructType >::~TRenderThreadStruct(), ISceneRenderBuilder::AddRenderCommand(), BeginSetUniformBufferContents(), FGeometryCollectionVertexFactory::Copy(), and FSplineMeshVertexFactory::Copy().
LogRenderCommand
#define LogRenderCommand (TypeName)
Definition at line 149 of file RenderingThread.h.
ShouldExecuteOnRenderThread
#define ShouldExecuteOnRenderThread ()
Value:
(LIKELY(GIsThreadedRendering || !IsInGameThread()))
Definition at line 156 of file RenderingThread.h.
Referenced by EnqueueUniqueRenderCommand().
UE_API
#define UE_API RENDERCORE_API
Definition at line 33 of file RenderingThread.h.
Typedef Documentation
FRenderCommandPipeBitArray
using FRenderCommandPipeBitArray = TBitArray<FRenderCommandPipeBitArrayAllocator>
Definition at line 287 of file RenderingThread.h.
FRenderCommandPipeBitArrayAllocator
using FRenderCommandPipeBitArrayAllocator = TInlineAllocator<1, FConcurrentLinearBitArrayAllocator>
Definition at line 286 of file RenderingThread.h.
FRenderCommandPipeSetBitIterator
using FRenderCommandPipeSetBitIterator = TConstSetBitIterator<FRenderCommandPipeBitArrayAllocator>
Definition at line 288 of file RenderingThread.h.
FStopRenderingThreadDelegate
using FStopRenderingThreadDelegate = FStopRenderingThread::FDelegate
Definition at line 767 of file RenderingThread.h.
Enumeration Type Documentation
ERenderCommandPipeFlags
enum class ERenderCommandPipeFlags : uint8 strong
Enumerator
None
Disabled
Initializes the render command pipe in a disabled state.
Definition at line 275 of file RenderingThread.h.
ERenderCommandPipeMode
enum class ERenderCommandPipeMode strong
Describes which pipes are configured to use the render command pipe system.
Enumerator
None
Bypasses the render command pipe system altogether.
Render commands are issued using tasks.
RenderThread
The render command pipe on the render thread pipe is active, and all other pipes forward to the render thread pipe.
All
All render command pipes are active.
Definition at line 263 of file RenderingThread.h.
Function Documentation
AdvanceRenderingThreadStatsGT()
RENDERCORE_API void AdvanceRenderingThreadStatsGT (bool bDiscardCallstack, int64 StatsFrame, int32 DisableChangeTagStartFrame) extern
Advances stats for the rendering thread.
Called from the game thread.
CheckNotBlockedOnRenderThread()
FORCEINLINE void CheckNotBlockedOnRenderThread ()
Asserts if called from the main thread when the main thread is blocked on the rendering thread.
Definition at line 78 of file RenderingThread.h.
References ensure, FORCEINLINE, GMainThreadBlockedOnRenderThread, IsInGameThread(), and Relaxed.
Referenced by EnqueueUniqueRenderCommand().
CheckRenderingThreadHealth()
RENDERCORE_API void CheckRenderingThreadHealth () extern
Checks if the rendering thread is healthy and running.
If it has crashed, UE_LOG is called with the exception information.
DECLARE_MULTICAST_DELEGATE()
DECLARE_MULTICAST_DELEGATE (FStopRenderingThread)
DECLARE_STATS_GROUP()
DECLARE_STATS_GROUP (TEXT("Render Thread Commands") , STATGROUP_RenderThreadCommands , STATCAT_Advanced)
EnqueueUniqueRenderCommand() [1/2]
template<typename RenderCommandTag, typename LambdaType> FORCEINLINE_DEBUGGABLE void EnqueueUniqueRenderCommand (LambdaType && Lambda)
Definition at line 378 of file RenderingThread.h.
References CheckNotBlockedOnRenderThread(), FRenderThreadCommandPipe::Enqueue(), FORCEINLINE_DEBUGGABLE, GetImmediateCommandList_ForRenderCommand(), IsInRenderingThread(), MoveTemp(), ShouldExecuteOnRenderThread, and TRACE_CPUPROFILER_EVENT_SCOPE_USE_ON_CHANNEL.
Referenced by FRenderCommandPipe::Enqueue(), FRenderCommandPipe::Enqueue(), and FRenderCommandPipe::Enqueue().
EnqueueUniqueRenderCommand() [2/2]
template<typename RenderCommandTag, typename LambdaType> FORCEINLINE_DEBUGGABLE void EnqueueUniqueRenderCommand (LambdaType & Lambda)
Definition at line 399 of file RenderingThread.h.
References FORCEINLINE_DEBUGGABLE.
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (ERenderCommandPipeFlags)
FlushRenderingCommands()
RENDERCORE_API void FlushRenderingCommands () extern
Waits for the rendering thread to finish executing all pending rendering commands.
Should only be used from the game thread.
Referenced by TComponentReregisterContext< ComponentType >::TComponentReregisterContext().
GetImmediateCommandList_ForRenderCommand()
RENDERCORE_API class FRHICommandListImmediate & GetImmediateCommandList_ForRenderCommand () extern
Referenced by TEnqueueUniqueRenderCommandType< TagType, LambdaType >::DoTask(), and EnqueueUniqueRenderCommand().
InitRenderingThread()
RENDERCORE_API void InitRenderingThread () extern
IsRenderingThreadHealthy()
RENDERCORE_API bool IsRenderingThreadHealthy () extern
Checks if the rendering thread is healthy and running, without crashing.
LatchRenderThreadConfiguration()
RENDERCORE_API void LatchRenderThreadConfiguration () extern
RegisterStopRenderingThreadDelegate()
RENDERCORE_API FDelegateHandle RegisterStopRenderingThreadDelegate (const FStopRenderingThreadDelegate & InDelegate) extern
ShutdownRenderingThread()
RENDERCORE_API void ShutdownRenderingThread () extern
StartRenderCommandFenceBundler()
RENDERCORE_API void StartRenderCommandFenceBundler () extern
References StartRenderCommandFenceBundler().
Referenced by StartRenderCommandFenceBundler().
StopRenderCommandFenceBundler()
RENDERCORE_API void StopRenderCommandFenceBundler () extern
References StopRenderCommandFenceBundler().
Referenced by StopRenderCommandFenceBundler().
TickRenderingTickables()
RENDERCORE_API void TickRenderingTickables () extern
References TickRenderingTickables().
Referenced by TickRenderingTickables().
UE_DEPRECATED() [1/2]
UE_DEPRECATED (5. 6, "FlushPendingDeleteRHIResources_GameThread is deprecated. Enqueue a render command that calls ImmediateFlush(EImmediateFlushType::FlushRHIThreadFlushResources) on the immediate RHI command list instead.")
UE_DEPRECATED() [2/2]
UE_DEPRECATED (5. 6, "FlushPendingDeleteRHIResources_RenderThread is deprecated. Call ImmediateFlush(EImmediateFlushType::FlushRHIThreadFlushResources) on the immediate RHI command list instead.")
References UE_DEPRECATED.
UE_TRACE_CHANNEL_EXTERN()
UE_TRACE_CHANNEL_EXTERN (RenderCommandsChannel , RENDERCORE_API)
UnregisterStopRenderingThreadDelegate()
RENDERCORE_API void UnregisterStopRenderingThreadDelegate (FDelegateHandle InDelegateHandle) extern
Variable Documentation
GIsThreadedRendering
RENDERCORE_API bool GIsThreadedRendering extern
Whether the renderer is currently running in a separate thread.
If this is false, then all rendering commands will be executed immediately instead of being enqueued in the rendering command buffer.
Referenced by FRenderCommand::GetDesiredThread().
GMainThreadBlockedOnRenderThread
RENDERCORE_API TAtomic<bool> GMainThreadBlockedOnRenderThread extern
Whether the main thread is currently blocked on the rendering thread, e.g.
a call to FlushRenderingCommands.
Referenced by CheckNotBlockedOnRenderThread().
GPendingUseThreadedRendering
RENDERCORE_API TOptional<bool> GPendingUseThreadedRendering extern
GRenderCommandPipeMode
RENDERCORE_API ERenderCommandPipeMode GRenderCommandPipeMode extern
Referenced by FRenderCommandPipe::Enqueue(), FRenderCommandPipe::Enqueue(), and FRenderThreadCommandPipe::Enqueue().
GUseThreadedRendering
RENDERCORE_API bool GUseThreadedRendering extern
Whether the rendering thread should be created or not.
Currently set by command line parameter and by the ToggleRenderingThread console command.