Unreal Engine 5.6 C++ API: UE::GC::FWorkerContext Struct Reference
UE::GC::FWorkerContext Struct Reference
Thread-local context containing initial objects and references to collect.
#include "FastReferenceCollector.h"
Public Member Functions
FWorkerContext ()
~FWorkerContext ()
void AllocateWorkerIndex ()
void FreeWorkerIndex ()
int64 GetAllocatedSize () const
Returns the size of memory allocated by internal arrays.
TConstArrayView< UObject * > GetInitialObjects ()
FORCEINLINE UObject * GetReferencingObject ()
FORCEINLINE int32 GetWorkerIndex () const
void ResetInitialObjects ()
void SetInitialObjectsPrepadded (TConstArrayView< UObject * > PaddedObjects)
void SetInitialObjectsUnpadded (TArray< UObject * > &Objects)
UE_NONCOPYABLE (FWorkerContext)
Data Fields
bool bDidWork = false
bool bIsSuspended = false
FWorkCoordinator * Coordinator = nullptr
TArray< FGarbageReferenceInfo > GarbageReferences
FSuspendedStructBatch IncrementalStructs
TConstArrayView< UObject ** > InitialNativeReferences
FWorkBlockifier ObjectsToSerialize
FDebugSchemaStackNode * SchemaStack = nullptr
FProcessorStats Stats
TArray< FWeakReferenceInfo > WeakReferences
Private Attributes
TConstArrayView< UObject * > InitialObjects
UObject * ReferencingObject = nullptr
Friends
class FSlowAROManager
template<typename ProcessorType, typename CollectorType>
class TFastReferenceCollector
Detailed Description
Thread-local context containing initial objects and references to collect.
Definition at line 333 of file FastReferenceCollector.h.
Constructor & Destructor Documentation
FWorkerContext()
UE::GC::FWorkerContext::FWorkerContext ()
Referenced by UE_NONCOPYABLE().
~FWorkerContext()
UE::GC::FWorkerContext::~FWorkerContext ()
Member Function Documentation
AllocateWorkerIndex()
void UE::GC::FWorkerContext::AllocateWorkerIndex ()
FreeWorkerIndex()
void UE::GC::FWorkerContext::FreeWorkerIndex ()
GetAllocatedSize()
int64 UE::GC::FWorkerContext::GetAllocatedSize () const inline
Returns the size of memory allocated by internal arrays.
Definition at line 401 of file FastReferenceCollector.h.
References WeakReferences.
GetInitialObjects()
TConstArrayView< UObject * > UE::GC::FWorkerContext::GetInitialObjects () inline
Definition at line 372 of file FastReferenceCollector.h.
References InitialObjects.
GetReferencingObject()
FORCEINLINE UObject * UE::GC::FWorkerContext::GetReferencingObject () inline
Definition at line 370 of file FastReferenceCollector.h.
References FORCEINLINE, and ReferencingObject.
GetWorkerIndex()
FORCEINLINE int32 UE::GC::FWorkerContext::GetWorkerIndex () const inline
Definition at line 406 of file FastReferenceCollector.h.
References FORCEINLINE, and ObjectsToSerialize.
ResetInitialObjects()
void UE::GC::FWorkerContext::ResetInitialObjects () inline
Definition at line 373 of file FastReferenceCollector.h.
References InitialObjects.
SetInitialObjectsPrepadded()
void UE::GC::FWorkerContext::SetInitialObjectsPrepadded (TConstArrayView< UObject * > PaddedObjects) inline
Parameters
PaddedObjects must already be padded to allow reading valid objects past the end
Definition at line 383 of file FastReferenceCollector.h.
References check, InitialObjects, and UE::GC::ObjectLookahead.
Referenced by SetInitialObjectsUnpadded().
SetInitialObjectsUnpadded()
void UE::GC::FWorkerContext::SetInitialObjectsUnpadded (TArray< UObject * > & Objects) inline
Parameters
Objects must outlive this context. It's data is padded by repeating the last object to allow prefetching past the end.
Definition at line 376 of file FastReferenceCollector.h.
References UE::GC::PadObjectArray(), and SetInitialObjectsPrepadded().
UE_NONCOPYABLE()
UE::GC::FWorkerContext::UE_NONCOPYABLE (FWorkerContext)
References FWorkerContext().
Friends And Related Symbol Documentation
FSlowAROManager
friend class FSlowAROManager friend
Definition at line 338 of file FastReferenceCollector.h.
References FSlowAROManager.
Referenced by FSlowAROManager.
TFastReferenceCollector
template<typename ProcessorType, typename CollectorType> friend class TFastReferenceCollector friend
Definition at line 337 of file FastReferenceCollector.h.
References TFastReferenceCollector.
Referenced by TFastReferenceCollector.
Field Documentation
bDidWork
bool UE::GC::FWorkerContext::bDidWork = false
Definition at line 366 of file FastReferenceCollector.h.
bIsSuspended
bool UE::GC::FWorkerContext::bIsSuspended = false
Definition at line 365 of file FastReferenceCollector.h.
Coordinator
FWorkCoordinator* UE::GC::FWorkerContext::Coordinator = nullptr
Definition at line 353 of file FastReferenceCollector.h.
GarbageReferences
TArray<FGarbageReferenceInfo> UE::GC::FWorkerContext::GarbageReferences
Definition at line 358 of file FastReferenceCollector.h.
IncrementalStructs
FSuspendedStructBatch UE::GC::FWorkerContext::IncrementalStructs
Definition at line 364 of file FastReferenceCollector.h.
InitialNativeReferences
TConstArrayView<UObject**> UE::GC::FWorkerContext::InitialNativeReferences
Definition at line 352 of file FastReferenceCollector.h.
InitialObjects
TConstArrayView<UObject*> UE::GC::FWorkerContext::InitialObjects private
Definition at line 342 of file FastReferenceCollector.h.
Referenced by GetInitialObjects(), ResetInitialObjects(), and SetInitialObjectsPrepadded().
ObjectsToSerialize
FWorkBlockifier UE::GC::FWorkerContext::ObjectsToSerialize
Definition at line 351 of file FastReferenceCollector.h.
Referenced by GetWorkerIndex().
ReferencingObject
UObject* UE::GC::FWorkerContext::ReferencingObject = nullptr private
Definition at line 341 of file FastReferenceCollector.h.
Referenced by GetReferencingObject().
SchemaStack
FDebugSchemaStackNode* UE::GC::FWorkerContext::SchemaStack = nullptr
Definition at line 368 of file FastReferenceCollector.h.
Referenced by UE::GC::FDebugSchemaStackScope::FDebugSchemaStackScope().
Stats
FProcessorStats UE::GC::FWorkerContext::Stats
Definition at line 355 of file FastReferenceCollector.h.
WeakReferences
TArray<FWeakReferenceInfo> UE::GC::FWorkerContext::WeakReferences
Definition at line 354 of file FastReferenceCollector.h.
Referenced by GetAllocatedSize().
The documentation for this struct was generated from the following file:
FastReferenceCollector.h