Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModelVariantIterator Struct Reference
UE::Sequencer::FViewModelVariantIterator Struct Reference
An iterator that can accomodate different types of data model lists, arrays, etc.
#include "ViewModelIterators.h"
Public Member Functions
FViewModelVariantIterator ()
FViewModelVariantIterator (const FViewModelListHead *DirectList)
template<typename T>
FViewModelVariantIterator (const TArray< TViewModelPtr< T > > *InStrongArrayView)
template<typename T>
FViewModelVariantIterator (const TArray< TWeakViewModelPtr< T > > *InWeakArrayView)
FORCEINLINE FViewModelVariantIterator begin () const
FORCEINLINE FViewModelVariantIterator end () const
FORCEINLINE const FViewModelPtr & GetCurrentItem () const
FORCEINLINE operator bool () const
FORCEINLINE const FViewModelPtr & operator* () const
FORCEINLINE void operator++ ()
FORCEINLINE FViewModel * operator-> () const
Private Types
using ProjectionType = TSharedPtr<FViewModel> (*)(int32 Index, const void*)
Static Private Member Functions
template<typename T>
static TSharedPtr< FViewModel > ProjectStrong (int32 Index, const void *InData)
template<typename T>
static TSharedPtr< FViewModel > ProjectWeak (int32 Index, const void *InData)
Private Attributes
int32 ArrayIndex
int32 ArrayNum
ProjectionType ArrayProjection
const void * Data
FViewModelPtr Value
Friends
FORCEINLINE friend bool operator!= (const FViewModelVariantIterator &A, const FViewModelVariantIterator &B)
Detailed Description
An iterator that can accomodate different types of data model lists, arrays, etc.
Definition at line 230 of file ViewModelIterators.h.
Member Typedef Documentation
ProjectionType
using UE::Sequencer::FViewModelVariantIterator::ProjectionType = TSharedPtr<FViewModel> (*)(int32 Index, const void*) private
Definition at line 326 of file ViewModelIterators.h.
Constructor & Destructor Documentation
FViewModelVariantIterator() [1/4]
UE::Sequencer::FViewModelVariantIterator::FViewModelVariantIterator () inline
Definition at line 232 of file ViewModelIterators.h.
References ArrayIndex, ArrayNum, ArrayProjection, Data, and Value.
Referenced by begin(), end(), and operator!=.
FViewModelVariantIterator() [2/4]
UE::Sequencer::FViewModelVariantIterator::FViewModelVariantIterator (const FViewModelListHead * DirectList) inline
Definition at line 241 of file ViewModelIterators.h.
References ArrayIndex, ArrayNum, ArrayProjection, Data, and Value.
FViewModelVariantIterator() [3/4]
template<typename T> UE::Sequencer::FViewModelVariantIterator::FViewModelVariantIterator (const TArray< TWeakViewModelPtr< T > > * InWeakArrayView) inline
Definition at line 251 of file ViewModelIterators.h.
References ArrayIndex, ArrayNum, ArrayProjection, Data, GetData(), Num, operator++(), and ProjectWeak().
FViewModelVariantIterator() [4/4]
template<typename T> UE::Sequencer::FViewModelVariantIterator::FViewModelVariantIterator (const TArray< TViewModelPtr< T > > * InStrongArrayView) inline
Definition at line 261 of file ViewModelIterators.h.
References ArrayIndex, ArrayNum, ArrayProjection, Data, GetData(), Num, operator++(), and ProjectStrong().
Member Function Documentation
begin()
FORCEINLINE FViewModelVariantIterator UE::Sequencer::FViewModelVariantIterator::begin () const inline
Definition at line 308 of file ViewModelIterators.h.
References FViewModelVariantIterator(), and FORCEINLINE.
end()
FORCEINLINE FViewModelVariantIterator UE::Sequencer::FViewModelVariantIterator::end () const inline
Definition at line 309 of file ViewModelIterators.h.
References FViewModelVariantIterator(), Data, and FORCEINLINE.
GetCurrentItem()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FViewModelVariantIterator::GetCurrentItem () const inline
Definition at line 270 of file ViewModelIterators.h.
References FORCEINLINE, and Value.
operator bool()
FORCEINLINE UE::Sequencer::FViewModelVariantIterator::operator bool () const inline explicit
Definition at line 283 of file ViewModelIterators.h.
References FORCEINLINE, and Value.
operator*()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FViewModelVariantIterator::operator* () const inline
Definition at line 274 of file ViewModelIterators.h.
References FORCEINLINE, and Value.
operator++()
FORCEINLINE void UE::Sequencer::FViewModelVariantIterator::operator++ () inline
Definition at line 287 of file ViewModelIterators.h.
References ArrayIndex, ArrayNum, ArrayProjection, Data, FORCEINLINE, and Value.
Referenced by FViewModelVariantIterator(), and FViewModelVariantIterator().
operator->()
FORCEINLINE FViewModel * UE::Sequencer::FViewModelVariantIterator::operator-> () const inline
Definition at line 278 of file ViewModelIterators.h.
References check, FORCEINLINE, and Value.
ProjectStrong()
template<typename T> TSharedPtr< FViewModel > UE::Sequencer::FViewModelVariantIterator::ProjectStrong (int32 Index, const void * InData) inline static private
Definition at line 320 of file ViewModelIterators.h.
Referenced by FViewModelVariantIterator().
ProjectWeak()
template<typename T> TSharedPtr< FViewModel > UE::Sequencer::FViewModelVariantIterator::ProjectWeak (int32 Index, const void * InData) inline static private
Definition at line 314 of file ViewModelIterators.h.
References TWeakPtr< ObjectType, InMode >::Pin().
Referenced by FViewModelVariantIterator().
Friends And Related Symbol Documentation
operator!=
FORCEINLINE friend bool operator!= (const FViewModelVariantIterator & A, const FViewModelVariantIterator & B) friend
Definition at line 303 of file ViewModelIterators.h.
References FViewModelVariantIterator(), A, B, and FORCEINLINE.
Field Documentation
ArrayIndex
int32 UE::Sequencer::FViewModelVariantIterator::ArrayIndex private
Definition at line 331 of file ViewModelIterators.h.
Referenced by FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), and operator++().
ArrayNum
int32 UE::Sequencer::FViewModelVariantIterator::ArrayNum private
Definition at line 332 of file ViewModelIterators.h.
Referenced by FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), and operator++().
ArrayProjection
ProjectionType UE::Sequencer::FViewModelVariantIterator::ArrayProjection private
Definition at line 330 of file ViewModelIterators.h.
Referenced by FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), and operator++().
Data
const void* UE::Sequencer::FViewModelVariantIterator::Data private
Definition at line 329 of file ViewModelIterators.h.
Referenced by FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), FViewModelVariantIterator(), end(), and operator++().
Value
FViewModelPtr UE::Sequencer::FViewModelVariantIterator::Value private
Definition at line 328 of file ViewModelIterators.h.
Referenced by FViewModelVariantIterator(), FViewModelVariantIterator(), GetCurrentItem(), operator bool(), operator*(), operator++(), and operator->().
The documentation for this struct was generated from the following file:
ViewModelIterators.h