Unreal Engine 5.6 C++ API: TAtomic< T > Class Template Reference
TAtomic< T > Class Template Reference
DEPRECATED!
#include "Atomic.h"
Public Types
using ElementType = T
Public Member Functions
FORCEINLINE TAtomic ()=default
Default initializes the element type.
constexpr TAtomic (T Arg)
Initializes the element type with the given argument types.
FORCEINLINE operator T () const
Gets a copy of the current value of the element.
FORCEINLINE T operator= (T Value)
Sets the element to a specific value, returning a copy of the value.
Private Member Functions
TAtomic (const TAtomic &)=delete
TAtomic (TAtomic &&)=delete
TAtomic & operator= (const TAtomic &)=delete
TAtomic & operator= (TAtomic &&)=delete
Detailed Description
template<typename T>
class TAtomic< T >
DEPRECATED!
UE atomics are not maintained and potentially will be physically deprecated. Use std::atomic<T> for new code
Atomic object wrapper class which wraps an element of T. This allows the following benefits:
Changes made to the element on one thread can never be observed as a partial state by other threads. (atomicity)
Memory accesses within a thread are not reordered across any access of the element. (acquire/release semantics)
There is a single, visible, global order of atomic accesses throughout the system. (sequential consistency)
Definition at line 537 of file Atomic.h.
Member Typedef Documentation
ElementType
template<typename T> using TAtomic< T >::ElementType = T
Definition at line 542 of file Atomic.h.
Constructor & Destructor Documentation
TAtomic() [1/4]
template<typename T> FORCEINLINE TAtomic< T >::TAtomic () default
Default initializes the element type.
NOTE: This will leave the value uninitialized if it has no constructor.
References FORCEINLINE.
Referenced by TAtomic(), TAtomic(), operator=(), and operator=().
TAtomic() [2/4]
template<typename T> TAtomic< T >::TAtomic (T Arg) inline constexpr
Initializes the element type with the given argument types.
Parameters
Arg The value to initialize the element counter to
Note
This constructor is not atomic.
Definition at line 556 of file Atomic.h.
References Core, and Private.
TAtomic() [3/4]
template<typename T> TAtomic< T >::TAtomic (TAtomic< T > &&) private delete
References TAtomic().
TAtomic() [4/4]
template<typename T> TAtomic< T >::TAtomic (const TAtomic< T > &) private delete
References TAtomic().
Member Function Documentation
operator T()
template<typename T> FORCEINLINE TAtomic< T >::operator T () const inline
Gets a copy of the current value of the element.
Returns
The current value.
Definition at line 566 of file Atomic.h.
operator=() [1/3]
template<typename T> TAtomic & TAtomic< T >::operator= (const TAtomic< T > &) private delete
References TAtomic().
operator=() [2/3]
template<typename T> FORCEINLINE T TAtomic< T >::operator= (T Value) inline
Sets the element to a specific value, returning a copy of the value.
Parameters
Value The value to set the element to.
Returns
A copy of Value.
Definition at line 578 of file Atomic.h.
References Exchange(), FORCEINLINE, and Value.
operator=() [3/3]
template<typename T> TAtomic & TAtomic< T >::operator= (TAtomic< T > &&) private delete
References TAtomic().
The documentation for this class was generated from the following files:
MemoryBase.h
Atomic.h