Unreal Engine 5.6 C++ API: UE::Geometry::FVertexInfo Struct Reference
UE::Geometry::FVertexInfo Struct Reference
FVertexInfo stores information about vertex attributes - position, normal, color, UV.
#include "InfoTypes.h"
Public Member Functions
FVertexInfo ()=default
FVertexInfo (const FVector3d &PositionIn)
FVertexInfo (const FVector3d &PositionIn, const FVector3f &NormalIn)
FVertexInfo (const FVector3d &PositionIn, const FVector3f &NormalIn, const FVector3f &ColorIn)
FVertexInfo (const FVector3d &PositionIn, const FVector3f &NormalIn, const FVector3f &ColorIn, const FVector2f &UVIn)
Data Fields
bool bHaveC {}
bool bHaveN {}
bool bHaveUV {}
FVector3f Color { FVector3f::Zero() }
FVector3f Normal { FVector3f::Zero() }
FVector3d Position { FVector3d::Zero() }
FVector2f UV { FVector2f::Zero() }
Detailed Description
FVertexInfo stores information about vertex attributes - position, normal, color, UV.
Definition at line 16 of file InfoTypes.h.
Constructor & Destructor Documentation
FVertexInfo() [1/5]
UE::Geometry::FVertexInfo::FVertexInfo () default
FVertexInfo() [2/5]
UE::Geometry::FVertexInfo::FVertexInfo (const FVector3d & PositionIn) inline
Definition at line 25 of file InfoTypes.h.
References Position.
FVertexInfo() [3/5]
UE::Geometry::FVertexInfo::FVertexInfo (const FVector3d & PositionIn, const FVector3f & NormalIn) inline
Definition at line 27 of file InfoTypes.h.
References bHaveN, Normal, and Position.
FVertexInfo() [4/5]
UE::Geometry::FVertexInfo::FVertexInfo (const FVector3d & PositionIn, const FVector3f & NormalIn, const FVector3f & ColorIn) inline
Definition at line 29 of file InfoTypes.h.
References bHaveC, bHaveN, Color, Normal, and Position.
FVertexInfo() [5/5]
UE::Geometry::FVertexInfo::FVertexInfo (const FVector3d & PositionIn, const FVector3f & NormalIn, const FVector3f & ColorIn, const FVector2f & UVIn) inline
Definition at line 31 of file InfoTypes.h.
References bHaveC, bHaveN, bHaveUV, Color, Normal, Position, and UV.
Field Documentation
bHaveC
bool UE::Geometry::FVertexInfo::bHaveC {}
Definition at line 22 of file InfoTypes.h.
Referenced by FVertexInfo(), and FVertexInfo().
bHaveN
bool UE::Geometry::FVertexInfo::bHaveN {}
Definition at line 22 of file InfoTypes.h.
Referenced by FVertexInfo(), FVertexInfo(), and FVertexInfo().
bHaveUV
bool UE::Geometry::FVertexInfo::bHaveUV {}
Definition at line 22 of file InfoTypes.h.
Referenced by FVertexInfo().
Color
FVector3f UE::Geometry::FVertexInfo::Color { FVector3f::Zero() }
Definition at line 20 of file InfoTypes.h.
Referenced by FVertexInfo(), and FVertexInfo().
Normal
FVector3f UE::Geometry::FVertexInfo::Normal { FVector3f::Zero() }
Definition at line 19 of file InfoTypes.h.
Referenced by FVertexInfo(), FVertexInfo(), and FVertexInfo().
Position
FVector3d UE::Geometry::FVertexInfo::Position { FVector3d::Zero() }
Definition at line 18 of file InfoTypes.h.
Referenced by FVertexInfo(), FVertexInfo(), FVertexInfo(), and FVertexInfo().
UV
FVector2f UE::Geometry::FVertexInfo::UV { FVector2f::Zero() }
Definition at line 21 of file InfoTypes.h.
Referenced by FVertexInfo().
The documentation for this struct was generated from the following file:
InfoTypes.h