Unreal Engine 5.6 C++ API: AVolume Class Reference
AVolume Class Reference
#include "Volume.h"
Public Member Functions
virtual void CheckForErrors () override
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
bool EncompassesPoint (FVector Point, float SphereRadius=0.f, float *OutDistanceToPoint=0) const
FBoxSphereBounds GetBounds () const
virtual FName GetCustomIconName () const override
virtual bool IsLevelBoundsRelevant () const override
virtual bool IsStaticBrush () const override
virtual bool IsVolumeBrush () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostEditImport () override
virtual bool ShouldCheckCollisionComponentForErrors () const
Public Member Functions inherited from ABrush
virtual bool CanDeleteSelectedActor (FText &OutReason) const override
bool CanEverAffectBSP () const
virtual bool CanReplaceSelectedActor (FText &OutReason) const override
FORCEINLINE void ClearNotForClientOrServer ()
Indicate that brush need should be loaded on client or servers.
virtual void CopyPosRotScaleFrom (ABrush *Other)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnBrushRegistered, ABrush *)
Delegate used for notifications when PostRegisterAllComponents is called for a Brush.
virtual void Destroyed () override
class UBrushComponent * GetBrushComponent () const
Returns BrushComponent subobject.
virtual FColor GetWireColor () const
Figures out the best color to use for this brushes wireframe drawing.
virtual void InitPosRotScale ()
virtual bool IsActorLabelEditable () const override
virtual bool IsBrushShape () const
virtual bool IsComponentRelevantForNavigation (UActorComponent *Component) const override
FORCEINLINE bool IsNotForClientOrServer () const
Return if true if this brush is not used for gameplay (i.e.
virtual bool Modify (bool bAlwaysMarkDirty=true) override
virtual bool NeedsLoadForClient () const override
virtual bool NeedsLoadForServer () const override
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostEditMove (bool bFinished) override
virtual void PostLoad () override
virtual void PostRegisterAllComponents () override
virtual void RebuildNavigationData ()
virtual bool SetIsHiddenEdLayer (bool bIsHiddenEdLayer) override
virtual void SetIsTemporarilyHiddenInEditor (bool bIsHidden) override
FORCEINLINE void SetNotForClientOrServer ()
Indicate that this brush need not be loaded on client or servers.
bool ShouldExportStaticNavigableGeometry () const
virtual bool SupportsExternalPackaging () const override
virtual bool SupportsLayers () const override
UPROPERTY() uint32 bInManipulation UPROPERTY () TArray< struct FGeomSelection > SavedSelections
Flag set when we are in a manipulation (scaling, translation, brush builder param change etc.)
Private Member Functions
GENERATED_UCLASS_BODY () DECLARE_MULTICAST_DELEGATE_OneParam(FOnVolumeShapeChanged
Delegate used for notifications when a volumes initial shape changes.
Static Private Member Functions
AVolume &static FOnVolumeShapeChanged & GetOnVolumeShapeChangedDelegate ()
Function to get the 'Volume imported' delegate.
Static Private Attributes
static FOnVolumeShapeChanged OnVolumeShapeChanged
Called during posteditchange after the volume's initial shape has changed.
Additional Inherited Members
Static Public Member Functions inherited from ABrush
static FOnBrushRegistered & GetOnBrushRegisteredDelegate ()
Function to get the 'brush registered' delegate.
static bool GetSuppressBSPRegeneration ()
static bool NeedsRebuild (TArray< TWeakObjectPtr< ULevel > > *OutLevels=nullptr)
Called to see if any of the levels need rebuilding.
static void OnRebuildDone ()
Called upon finishing the csg rebuild to clear the rebuild bool.
static void SetNeedRebuild (ULevel *InLevel)
Called to make not of the level that needs rebuilding.
static void SetSuppressBSPRegeneration (bool bSuppress)
Static Public Attributes inherited from ABrush
static const TCHAR * GGeometryRebuildCause
Debug purposes only; an attempt to catch the cause of UE-36265.
Detailed Description
Definition at line 17 of file Volume.h.
Member Function Documentation
CheckForErrors()
virtual void AVolume::CheckForErrors () override virtual
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
Reimplemented from ABrush.
Reimplemented in ALevelStreamingVolume.
EncompassesPoint()
bool AVolume::EncompassesPoint (FVector Point, float SphereRadius = 0.f, float * OutDistanceToPoint = 0) const
Returns
true if a sphere/point (with optional radius CheckRadius) overlaps this volume
References FVector, and Point.
Referenced by UCLASS().
GENERATED_UCLASS_BODY()
AVolume::GENERATED_UCLASS_BODY () private
Delegate used for notifications when a volumes initial shape changes.
Referenced by UCLASS().
GetBounds()
FBoxSphereBounds AVolume::GetBounds () const
Returns
the coarse bounds of this volume
GetCustomIconName()
virtual FName AVolume::GetCustomIconName () const override virtual
Reimplemented from ABrush.
GetOnVolumeShapeChangedDelegate()
AVolume &static FOnVolumeShapeChanged & AVolume::GetOnVolumeShapeChangedDelegate () inline static private
Function to get the 'Volume imported' delegate.
Definition at line 26 of file Volume.h.
References GetOnVolumeShapeChangedDelegate(), and OnVolumeShapeChanged.
Referenced by GetOnVolumeShapeChangedDelegate().
IsLevelBoundsRelevant()
virtual bool AVolume::IsLevelBoundsRelevant () const override virtual
Reimplemented from ABrush.
Reimplemented in AHierarchicalLODVolume.
IsStaticBrush()
virtual bool AVolume::IsStaticBrush () const override virtual
Returns
true if this is a static brush
Reimplemented from ABrush.
IsVolumeBrush()
virtual bool AVolume::IsVolumeBrush () const override virtual
Returns
false
Reimplemented from ABrush.
PostEditChangeProperty()
virtual void AVolume::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented from ABrush.
Reimplemented in AAudioVolume, and ACullDistanceVolume.
Referenced by ALightmassImportanceVolume::GENERATED_UCLASS_BODY(), and UCLASS().
PostEditImport()
virtual void AVolume::PostEditImport () override virtual
ShouldCheckCollisionComponentForErrors()
virtual bool AVolume::ShouldCheckCollisionComponentForErrors () const inline virtual
Definition at line 40 of file Volume.h.
Field Documentation
OnVolumeShapeChanged
FOnVolumeShapeChanged AVolume::OnVolumeShapeChanged static private
Called during posteditchange after the volume's initial shape has changed.
Definition at line 32 of file Volume.h.
Referenced by GetOnVolumeShapeChangedDelegate().
The documentation for this class was generated from the following file:
Volume.h