Unreal Engine 5.6 C++ API: FSubsystemCollectionBase Class Reference
FSubsystemCollectionBase Class Reference
#include "SubsystemCollection.h"
Data Structures
struct FSubsystemArray
Public Member Functions
void AddReferencedObjects (UObject *Referencer, FReferenceCollector &Collector)
Collect references held by this collection.
void Deinitialize ()
const UClass * GetBaseType () const
Get the collection BaseType.
void Initialize (UObject *NewOuter)
Initialize the collection of systems, systems will be created and initialized.
template<typename TSubsystemClass>
TSubsystemClass * InitializeDependency ()
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
USubsystem * InitializeDependency (TSubclassOf< USubsystem > SubsystemClass)
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
bool IsInitialized () const
Returns true if collection was already initialized.
Static Public Member Functions
static void ActivateExternalSubsystem (UClass *SubsystemClass)
Registers and adds instances of the specified Subsystem class to all existing SubsystemCollections of the correct type.
static void DeactivateExternalSubsystem (UClass *SubsystemClass)
Unregisters and removed instances of the specified Subsystem class from all existing SubsystemCollections of the correct type.
Protected Member Functions
FSubsystemCollectionBase ()
protected constructor - Use the FSubsystemCollection<TBaseType> class
FSubsystemCollectionBase (UClass *InBaseType)
protected constructor - for use by the template only(FSubsystemCollection<TBaseType>)
virtual ~FSubsystemCollectionBase ()
destructor will be called from virtual ~FGCObject in GC cleanup
FSubsystemArray & FindAndPopulateSubsystemArrayInternal (UClass *SubsystemClass) const
void ForEachSubsystem (TFunctionRef< void(USubsystem *)> Operation) const
Run the given operation on each registered subsystem.
void ForEachSubsystemOfClass (UClass *SubsystemClass, TFunctionRef< void(USubsystem *)> Operation) const
Perform an operation on all subsystems that derive from the given class.
TArray< USubsystem * > GetSubsystemArrayCopy (UClass *SubsystemClass) const
Get a list of Subsystems by type.
USubsystem * GetSubsystemInternal (UClass *SubsystemClass) const
Get a Subsystem by type.
UE_DEPRECATED (5.4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystemOfClass or GetSubsystemArrayCopy instead") 1 const TArray< USubsystem * > &GetSubsystemArrayInternal(UClass *SubsystemClass) const
Get a list of Subsystems by type.
Private Member Functions
USubsystem * AddAndInitializeSubsystem (UClass *SubsystemClass)
void RemoveAndDeinitializeSubsystem (USubsystem *Subsystem)
Static Private Member Functions
static void AddAllInstances (UClass *SubsystemClass)
Add Instances of the specified Subsystem class to all existing SubsystemCollections of the correct type.
static void RemoveAllInstances (UClass *SubsystemClass)
Remove Instances of the specified Subsystem class from all existing SubsystemCollections of the correct type.
Private Attributes
UClass * BaseType
bool bIterating = false
bool bPopulating
UObject * Outer
TMap< UClass *, TUniquePtr< FSubsystemArray > > SubsystemArrayMap
TMap< TObjectPtr< UClass >, TObjectPtr< USubsystem > > SubsystemMap
Friends
class FSubsystemModuleWatcher
Detailed Description
Definition at line 14 of file SubsystemCollection.h.
Constructor & Destructor Documentation
FSubsystemCollectionBase() [1/2]
FSubsystemCollectionBase::FSubsystemCollectionBase (UClass * InBaseType) protected
protected constructor - for use by the template only(FSubsystemCollection<TBaseType>)
Referenced by FObjectSubsystemCollection< TBaseType >::FObjectSubsystemCollection(), and FSubsystemCollection< TBaseType >::FSubsystemCollection().
FSubsystemCollectionBase() [2/2]
FSubsystemCollectionBase::FSubsystemCollectionBase () protected
protected constructor - Use the FSubsystemCollection<TBaseType> class
~FSubsystemCollectionBase()
virtual FSubsystemCollectionBase::~FSubsystemCollectionBase () protected virtual
destructor will be called from virtual ~FGCObject in GC cleanup
Member Function Documentation
ActivateExternalSubsystem()
void FSubsystemCollectionBase::ActivateExternalSubsystem (UClass * SubsystemClass) static
Registers and adds instances of the specified Subsystem class to all existing SubsystemCollections of the correct type.
Should be used by specific subsystems in plug ins when plugin is activated.
AddAllInstances()
void FSubsystemCollectionBase::AddAllInstances (UClass * SubsystemClass) static private
Add Instances of the specified Subsystem class to all existing SubsystemCollections of the correct type.
References AddAllInstances().
Referenced by AddAllInstances().
AddAndInitializeSubsystem()
USubsystem * FSubsystemCollectionBase::AddAndInitializeSubsystem (UClass * SubsystemClass) private
References AddAndInitializeSubsystem().
Referenced by AddAndInitializeSubsystem().
AddReferencedObjects()
void FSubsystemCollectionBase::AddReferencedObjects (UObject * Referencer, FReferenceCollector & Collector)
Collect references held by this collection.
Referenced by FSubsystemCollection< TBaseType >::AddReferencedObjects().
DeactivateExternalSubsystem()
void FSubsystemCollectionBase::DeactivateExternalSubsystem (UClass * SubsystemClass) static
Unregisters and removed instances of the specified Subsystem class from all existing SubsystemCollections of the correct type.
Should be used by specific subsystems in plug ins when plugin is deactivated.
Deinitialize()
void FSubsystemCollectionBase::Deinitialize ()
FindAndPopulateSubsystemArrayInternal()
FSubsystemArray & FSubsystemCollectionBase::FindAndPopulateSubsystemArrayInternal (UClass * SubsystemClass) const protected
References FindAndPopulateSubsystemArrayInternal().
Referenced by FindAndPopulateSubsystemArrayInternal(), FObjectSubsystemCollection< TBaseType >::GetSubsystemArrayCopy(), FSubsystemCollection< TBaseType >::GetSubsystemArrayCopy(), FObjectSubsystemCollection< TBaseType >::UE_DEPRECATED(), and FSubsystemCollection< TBaseType >::UE_DEPRECATED().
ForEachSubsystem()
void FSubsystemCollectionBase::ForEachSubsystem (TFunctionRef< void(USubsystem *)> Operation) const protected
Run the given operation on each registered subsystem.
Any new subsystems registered during this operation will also be visited. It is not permitted to remove subsystems (e.g. by calling DeactivateExternalSubsystem) during this operation.
References ForEachSubsystem().
Referenced by ForEachSubsystem().
ForEachSubsystemOfClass()
void FSubsystemCollectionBase::ForEachSubsystemOfClass (UClass * SubsystemClass, TFunctionRef< void(USubsystem *)> Operation) const protected
Perform an operation on all subsystems that derive from the given class.
References ForEachSubsystemOfClass().
Referenced by FAudioSubsystemCollection::ForEachSubsystem(), ForEachSubsystemOfClass(), and FObjectSubsystemCollection< TBaseType >::ForEachSubsystemWithInterface().
GetBaseType()
const UClass * FSubsystemCollectionBase::GetBaseType () const inline
Get the collection BaseType.
Definition at line 27 of file SubsystemCollection.h.
References BaseType.
GetSubsystemArrayCopy()
TArray< USubsystem * > FSubsystemCollectionBase::GetSubsystemArrayCopy (UClass * SubsystemClass) const protected
Get a list of Subsystems by type.
References GetSubsystemArrayCopy().
Referenced by GetSubsystemArrayCopy().
GetSubsystemInternal()
USubsystem * FSubsystemCollectionBase::GetSubsystemInternal (UClass * SubsystemClass) const protected
Get a Subsystem by type.
Referenced by FObjectSubsystemCollection< TBaseType >::GetSubsystem(), and FSubsystemCollection< TBaseType >::GetSubsystem().
Initialize()
void FSubsystemCollectionBase::Initialize (UObject * NewOuter)
Initialize the collection of systems, systems will be created and initialized.
InitializeDependency() [1/2]
template<typename TSubsystemClass> TSubsystemClass * FSubsystemCollectionBase::InitializeDependency () inline
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
Definition at line 40 of file SubsystemCollection.h.
References Cast(), and InitializeDependency().
Referenced by InitializeDependency().
InitializeDependency() [2/2]
USubsystem * FSubsystemCollectionBase::InitializeDependency (TSubclassOf< USubsystem > SubsystemClass)
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
IsInitialized()
bool FSubsystemCollectionBase::IsInitialized () const inline
Returns true if collection was already initialized.
Definition at line 24 of file SubsystemCollection.h.
References Outer.
RemoveAllInstances()
void FSubsystemCollectionBase::RemoveAllInstances (UClass * SubsystemClass) static private
Remove Instances of the specified Subsystem class from all existing SubsystemCollections of the correct type.
References RemoveAllInstances().
Referenced by RemoveAllInstances().
RemoveAndDeinitializeSubsystem()
void FSubsystemCollectionBase::RemoveAndDeinitializeSubsystem (USubsystem * Subsystem) private
References RemoveAndDeinitializeSubsystem().
Referenced by RemoveAndDeinitializeSubsystem().
UE_DEPRECATED()
FSubsystemCollectionBase::UE_DEPRECATED (5. 4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystemOfClass or GetSubsystemArrayCopy instead") const & protected
Get a list of Subsystems by type.
Friends And Related Symbol Documentation
FSubsystemModuleWatcher
friend class FSubsystemModuleWatcher friend
Definition at line 113 of file SubsystemCollection.h.
References FSubsystemModuleWatcher.
Referenced by FSubsystemModuleWatcher.
Field Documentation
BaseType
UClass* FSubsystemCollectionBase::BaseType private
Definition at line 105 of file SubsystemCollection.h.
Referenced by GetBaseType().
bIterating
bool FSubsystemCollectionBase::bIterating = false mutable private
Definition at line 110 of file SubsystemCollection.h.
bPopulating
bool FSubsystemCollectionBase::bPopulating private
Definition at line 109 of file SubsystemCollection.h.
Outer
UObject* FSubsystemCollectionBase::Outer private
Definition at line 107 of file SubsystemCollection.h.
Referenced by IsInitialized().
SubsystemArrayMap
TMap<UClass*, TUniquePtr<FSubsystemArray> > FSubsystemCollectionBase::SubsystemArrayMap mutable private
Definition at line 103 of file SubsystemCollection.h.
SubsystemMap
TMap<TObjectPtr<UClass>, TObjectPtr<USubsystem> > FSubsystemCollectionBase::SubsystemMap private
Definition at line 101 of file SubsystemCollection.h.
The documentation for this class was generated from the following file:
SubsystemCollection.h