Unreal Engine 5.6 C++ API: FSoftObjectPath Struct Reference
FSoftObjectPath Struct Reference
A struct that contains a string reference to an object, either a package, a top level asset or a subobject.
#include "SoftObjectPath.h"
Public Member Functions
FSoftObjectPath ()=default
FSoftObjectPath (const ANSICHAR *Path)
FSoftObjectPath (const FObjectPtr &InObject)
FSoftObjectPath (const FSoftObjectPath &Other)=default
FSoftObjectPath (const FString &Path)
Construct from a path string.
template<typename T>
FSoftObjectPath (const TObjectPtr< T > &InObject)
FSoftObjectPath (const UObject *InObject)
Construct from an existing object in memory.
FSoftObjectPath (const WIDECHAR *Path)
FSoftObjectPath (FAnsiStringView Path)
FSoftObjectPath (FSoftObjectPath &&Other)=default
FSoftObjectPath (FTopLevelAssetPath InAssetPath)
Explicitly extend a top-level object path with an empty subobject path.
FSoftObjectPath (FTopLevelAssetPath InAssetPath, TStringOverload< FUtf8String > InSubPathString)
FSoftObjectPath (FTopLevelAssetPath InAssetPath, TStringOverload< FWideString > InSubPathString)
FSoftObjectPath (FWideStringView Path)
FSoftObjectPath (TYPE_OF_NULLPTR)
~FSoftObjectPath ()=default
void AppendString (FString &Builder) const
Append string representation of reference, in form /package/path.assetname[:subpath].
void AppendString (FStringBuilderBase &Builder) const
void AppendString (FUtf8StringBuilderBase &Builder) const
bool ExportTextItem (FString &ValueStr, FSoftObjectPath const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
bool FastLess (const FSoftObjectPath &Other) const
Return true if this path appears before Other using fast index-based fname order.
bool FixupCoreRedirects ()
Fixes soft object path for CoreRedirects to handle renamed native objects, returns true if it was modified.
bool FixupForPIE (int32 PIEInstance, TFunctionRef< void(int32, FSoftObjectPath &)> InPreFixupForPIECustomFunction=FSoftObjectPath_DefaultPreFixupForPIEFunction)
Fixes up this SoftObjectPath to add the PIE prefix for the given PIEInstance index, returns true if it was modified.
bool FixupForPIE (TFunctionRef< void(int32, FSoftObjectPath &)> InPreFixupForPIECustomFunction=FSoftObjectPath_DefaultPreFixupForPIEFunction)
Fixes up this SoftObjectPath to add the PIE prefix depending on what is currently active, returns true if it was modified.
FName GetAssetFName () const
Returns assetname string, leaving off the /package/path part and sub object.
FString GetAssetName () const
Returns assetname string, leaving off the /package/path part and sub object.
FTopLevelAssetPath GetAssetPath () const
Returns the top-level asset part of this path, without the subobject path.
FORCEINLINE FString GetAssetPathString () const
Returns string version of asset path, including both package and asset but not sub object.
FName GetLongPackageFName () const
Returns /package/path, leaving off the asset name and sub object.
FString GetLongPackageName () const
Returns /package/path, leaving off the asset name and sub object.
FORCEINLINE FString GetSubPathString () const
Returns the sub path, which is often empty.
FORCEINLINE const FUtf8String & GetSubPathUtf8String () const
FSoftObjectPath GetWithoutSubPath () const
Returns this path without the SubPath component, restricting the result to a top level asset but keeping the type as FSoftObjectPath in contrast to GetAssetPath.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText, FArchive *InSerializingArchive=nullptr)
FORCEINLINE bool IsAsset () const
Check if this represents an asset, meaning it is not null but does not have a sub path.
FORCEINLINE bool IsNull () const
Checks to see if this is initialized to null.
FORCEINLINE bool IsSubobject () const
Check if this represents a sub object, meaning it has a sub path.
FORCEINLINE bool IsValid () const
Check if this could possibly refer to a real object, or was initialized to null.
bool LexicalLess (const FSoftObjectPath &Other) const
Return true if this path appears before Other in lexical order.
int32 LoadAsync (FLoadSoftObjectPathAsyncDelegate InCompletionDelegate, FLoadAssetAsyncOptionalParams InOptionalParams=FLoadAssetAsyncOptionalParams()) const
Attempts to asynchronously load the object referenced by this path.
bool operator!= (FSoftObjectPath const &Other) const
FSoftObjectPath & operator= (const ANSICHAR *Path)
FSoftObjectPath & operator= (const FSoftObjectPath &Path)=default
FSoftObjectPath & operator= (const FString &Path)
FSoftObjectPath & operator= (const FTopLevelAssetPath Path)
FSoftObjectPath & operator= (const WIDECHAR *Path)
FSoftObjectPath & operator= (FAnsiStringView Path)
FSoftObjectPath & operator= (FSoftObjectPath &&Path)=default
FSoftObjectPath & operator= (FWideStringView Path)
FSoftObjectPath & operator= (TYPE_OF_NULLPTR)
bool operator== (FSoftObjectPath const &Other) const
void PostLoadPath (FArchive *InArchive) const
Handles when a path has been loaded, call if loading with a method that skips SerializePath.
bool PreSavePath (bool *bReportSoftObjectPathRedirects=nullptr)
Fixes up path for saving, call if saving with a method that skips SerializePath.
bool RemapPackage (FName OldPackageName, FName NewPackageName)
Remap the package to handle renames.
void Reset ()
Resets reference to point to null.
UObject * ResolveObject () const
Attempts to find a currently loaded object that matches this path.
bool Serialize (FArchive &Ar)
Struct overrides.
bool Serialize (FStructuredArchive::FSlot Slot)
bool SerializeFromMismatchedTag (struct FPropertyTag const &Tag, FStructuredArchive::FSlot Slot)
void SerializePath (FArchive &Ar)
Serializes the internal path and also handles save/PIE fixups.
void SerializePathWithoutFixup (FArchive &Ar)
Serializes the internal path without any save/PIE fixups.
void SetPath (const ANSICHAR *Path)
void SetPath (const FString &Path)
void SetPath (const FTopLevelAssetPath &InAssetPath)
Sets asset path of this reference based on a string path.
void SetPath (const FTopLevelAssetPath &InAssetPath, TStringOverload< FUtf8String > InSubPathString)
void SetPath (const FTopLevelAssetPath &InAssetPath, TStringOverload< FWideString > InSubPathString)
void SetPath (const UObject *InObject)
void SetPath (const WIDECHAR *Path)
void SetPath (FAnsiStringView Path)
void SetPath (FUtf8StringView Path)
void SetPath (FWideStringView Path)
FORCEINLINE void SetSubPathString (TStringOverload< FUtf8String > InSubPathString)
FORCEINLINE void SetSubPathString (TStringOverload< FWideString > InSubPathString)
FString ToString () const
Returns string representation of reference, in form /package/path.assetname[:subpath].
void ToString (FStringBuilderBase &Builder) const
Append string representation of reference, in form /package/path.assetname[:subpath].
void ToString (FUtf8StringBuilderBase &Builder) const
UObject * TryLoad (FUObjectSerializeContext *InLoadContext=nullptr) const
Attempts to load the asset, this will call LoadObject which can be very slow.
UE_DEPRECATED (5.6, "FSoftObjectPath which takes a package name and asset name has been deprecated - please pass FTopLevelAssetPath instead.") explicit FSoftObjectPath(FName InPackageName
UE_DEPRECATED (5.6, "FSoftObjectPath::ConstructFromPackageAsset has been deprecated - please use ConstructFromAssetPath instead.") 1 static FSoftObjectPath ConstructFromPackageAsset(FName InPackageName
UE_DEPRECATED (5.6, "FSoftObjectPath::ConstructFromPackageAssetSubpath has been deprecated - please use ConstructFromAssetPathAndSubpath instead.") 1 static FSoftObjectPath ConstructFromPackageAssetSubpath(FName InPackageName
Static methods for more meaningful construction sites.
Static Public Member Functions
static void AddPIEPackageName (FName NewPIEPackageName)
Adds list of packages names that have been created specifically for PIE, this is used for editor fixup.
static void ClearPIEPackageNames ()
Disables special PIE path handling, call when PIE finishes to clear list.
static FSoftObjectPath ConstructFromAssetPath (FTopLevelAssetPath InAssetPath)
static FSoftObjectPath ConstructFromAssetPathAndSubpath (FTopLevelAssetPath InAssetPath, TStringOverload< FUtf8String > InSubPathString)
static FSoftObjectPath ConstructFromAssetPathAndSubpath (FTopLevelAssetPath InAssetPath, TStringOverload< FWideString > InSubPathString)
static FSoftObjectPath ConstructFromObject (const FObjectPtr &InObject)
template<typename T>
static FSoftObjectPath ConstructFromObject (const TObjectPtr< T > &InObject)
static FSoftObjectPath ConstructFromObject (const UObject *InObject)
static FSoftObjectPath ConstructFromStringPath (FString &&InPath)
static FSoftObjectPath ConstructFromStringPath (FStringView InPath)
static FSoftObjectPath ConstructFromStringPath (FUtf8StringView InPath)
static FORCEINLINE FSoftObjectPath GetOrCreateIDForObject (const UObject *Object)
static FSoftObjectPath GetOrCreateIDForObject (FObjectPtr Object)
template<typename T>
static FORCEINLINE FSoftObjectPath GetOrCreateIDForObject (TObjectPtr< T > Object)
Data Fields
FName InAssetName
FName const FString & InSubPathString
Static Public Attributes
static FName NAME_Untracked
Text of the Untracked parameter in a UPROPERTY's meta field, if this parameter is present it marks that the SoftObjectPath reference should not cause the target package to be added to the cook.
Private Member Functions
UObject * ResolveObjectInternal () const
Private Attributes
FTopLevelAssetPath AssetPath
Asset path, patch to a top level object in a package.
FUtf8String SubPathString
Optional FString for subobject within an asset.
Static Private Attributes
static TSet< FName > PIEPackageNames
Package names currently being duplicated, needed by FixupForPIE.
Friends
FORCEINLINE friend uint32 GetTypeHash (FSoftObjectPath const &This)
void SerializeForLog (FCbWriter &Writer, const FSoftObjectPath &Value)
struct Z_Construct_UScriptStruct_FSoftObjectPath_Statics
Detailed Description
A struct that contains a string reference to an object, either a package, a top level asset or a subobject.
This can be used to make soft references to assets that are loaded on demand. This is stored internally as an FTopLevelAssetPath pointing to the top level asset (/package/path.assetname) and an optional string subobject path. If the MetaClass metadata is applied to a FProperty with this the UI will restrict to that type of asset.
Definition at line 51 of file SoftObjectPath.h.
Constructor & Destructor Documentation
FSoftObjectPath() [1/15]
FSoftObjectPath::FSoftObjectPath () nodiscard default
Referenced by FSoftClassPath::FSoftClassPath(), FSoftClassPath::FSoftClassPath(), FSoftObjectPath(), FSoftObjectPath(), ConstructFromAssetPath(), ConstructFromAssetPathAndSubpath(), ConstructFromAssetPathAndSubpath(), ConstructFromObject(), ConstructFromObject(), ConstructFromObject(), ConstructFromStringPath(), ConstructFromStringPath(), ConstructFromStringPath(), ExportTextItem(), FastLess(), FixupForPIE(), FixupForPIE(), FSoftClassPath::GetOrCreateIDForObject(), GetOrCreateIDForObject(), GetOrCreateIDForObject(), GetOrCreateIDForObject(), GetTypeHash, GetWithoutSubPath(), LexicalLess(), operator!=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator==(), SerializeForLog, UE_DEPRECATED(), and UE_DEPRECATED().
FSoftObjectPath() [2/15]
FSoftObjectPath::FSoftObjectPath (const FSoftObjectPath & Other) nodiscard default
References FSoftObjectPath(), and Other.
FSoftObjectPath() [3/15]
FSoftObjectPath::FSoftObjectPath (FSoftObjectPath && Other) nodiscard default
References FSoftObjectPath(), and Other.
~FSoftObjectPath()
FSoftObjectPath::~FSoftObjectPath () default
FSoftObjectPath() [4/15]
FSoftObjectPath::FSoftObjectPath (const FString & Path) inline nodiscard
Construct from a path string.
Non-explicit for backwards compatibility.
Definition at line 61 of file SoftObjectPath.h.
References Path, and SetPath().
FSoftObjectPath() [5/15]
FSoftObjectPath::FSoftObjectPath (FTopLevelAssetPath InAssetPath, TStringOverload< FWideString > InSubPathString) inline explicit nodiscard
Definition at line 66 of file SoftObjectPath.h.
References InSubPathString, and SetPath().
FSoftObjectPath() [6/15]
FSoftObjectPath::FSoftObjectPath (FTopLevelAssetPath InAssetPath, TStringOverload< FUtf8String > InSubPathString) inline explicit nodiscard
Definition at line 70 of file SoftObjectPath.h.
References InSubPathString, and SetPath().
FSoftObjectPath() [7/15]
FSoftObjectPath::FSoftObjectPath (FTopLevelAssetPath InAssetPath) inline explicit nodiscard
Explicitly extend a top-level object path with an empty subobject path.
Definition at line 81 of file SoftObjectPath.h.
References SetPath().
FSoftObjectPath() [8/15]
FSoftObjectPath::FSoftObjectPath (FWideStringView Path) inline explicit nodiscard
Definition at line 85 of file SoftObjectPath.h.
References Path, and SetPath().
FSoftObjectPath() [9/15]
FSoftObjectPath::FSoftObjectPath (FAnsiStringView Path) inline explicit nodiscard
Definition at line 89 of file SoftObjectPath.h.
References Path, and SetPath().
FSoftObjectPath() [10/15]
FSoftObjectPath::FSoftObjectPath (const WIDECHAR * Path) inline explicit nodiscard
Definition at line 93 of file SoftObjectPath.h.
References Path, and SetPath().
FSoftObjectPath() [11/15]
FSoftObjectPath::FSoftObjectPath (const ANSICHAR * Path) inline explicit nodiscard
Definition at line 97 of file SoftObjectPath.h.
References Path, and SetPath().
FSoftObjectPath() [12/15]
FSoftObjectPath::FSoftObjectPath (TYPE_OF_NULLPTR) inline explicit nodiscard
Definition at line 101 of file SoftObjectPath.h.
FSoftObjectPath() [13/15]
template<typename T> FSoftObjectPath::FSoftObjectPath (const TObjectPtr< T > & InObject) inline nodiscard
Definition at line 106 of file SoftObjectPath.h.
References TObjectPtr< T >::Get(), TObjectPtr< T >::GetPathName(), TObjectPtr< T >::IsResolved(), and SetPath().
FSoftObjectPath() [14/15]
FSoftObjectPath::FSoftObjectPath (const FObjectPtr & InObject) inline nodiscard
Definition at line 120 of file SoftObjectPath.h.
References FObjectPtr::Get(), FObjectPtr::GetPathName(), FObjectPtr::IsResolved(), and SetPath().
FSoftObjectPath() [15/15]
FSoftObjectPath::FSoftObjectPath (const UObject * InObject) inline nodiscard
Construct from an existing object in memory.
Definition at line 134 of file SoftObjectPath.h.
References SetPath().
Member Function Documentation
AddPIEPackageName()
void FSoftObjectPath::AddPIEPackageName (FName NewPIEPackageName) static
Adds list of packages names that have been created specifically for PIE, this is used for editor fixup.
AppendString() [1/3]
void FSoftObjectPath::AppendString (FString & Builder) const
Append string representation of reference, in form /package/path.assetname[:subpath].
AppendString() [2/3]
void FSoftObjectPath::AppendString (FStringBuilderBase & Builder) const
AppendString() [3/3]
void FSoftObjectPath::AppendString (FUtf8StringBuilderBase & Builder) const
ClearPIEPackageNames()
void FSoftObjectPath::ClearPIEPackageNames () static
Disables special PIE path handling, call when PIE finishes to clear list.
ConstructFromAssetPath()
FSoftObjectPath FSoftObjectPath::ConstructFromAssetPath (FTopLevelAssetPath InAssetPath) static nodiscard
References FSoftObjectPath().
ConstructFromAssetPathAndSubpath() [1/2]
FSoftObjectPath FSoftObjectPath::ConstructFromAssetPathAndSubpath (FTopLevelAssetPath InAssetPath, TStringOverload< FUtf8String > InSubPathString) static nodiscard
References FSoftObjectPath(), and InSubPathString.
ConstructFromAssetPathAndSubpath() [2/2]
FSoftObjectPath FSoftObjectPath::ConstructFromAssetPathAndSubpath (FTopLevelAssetPath InAssetPath, TStringOverload< FWideString > InSubPathString) static nodiscard
References FSoftObjectPath(), and InSubPathString.
ConstructFromObject() [1/3]
FSoftObjectPath FSoftObjectPath::ConstructFromObject (const FObjectPtr & InObject) static nodiscard
References FSoftObjectPath().
ConstructFromObject() [2/3]
template<typename T> FSoftObjectPath FSoftObjectPath::ConstructFromObject (const TObjectPtr< T > & InObject) inline static nodiscard
Definition at line 155 of file SoftObjectPath.h.
References FSoftObjectPath(), ConstructFromObject(), and TObjectPtr< T >::Get().
ConstructFromObject() [3/3]
FSoftObjectPath FSoftObjectPath::ConstructFromObject (const UObject * InObject) static nodiscard
References FSoftObjectPath().
Referenced by ConstructFromObject().
ConstructFromStringPath() [1/3]
FSoftObjectPath FSoftObjectPath::ConstructFromStringPath (FString && InPath) static nodiscard
References FSoftObjectPath().
ConstructFromStringPath() [2/3]
FSoftObjectPath FSoftObjectPath::ConstructFromStringPath (FStringView InPath) static nodiscard
References FSoftObjectPath().
ConstructFromStringPath() [3/3]
FSoftObjectPath FSoftObjectPath::ConstructFromStringPath (FUtf8StringView InPath) static nodiscard
References FSoftObjectPath().
ExportTextItem()
bool FSoftObjectPath::ExportTextItem (FString & ValueStr, FSoftObjectPath const & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
References FSoftObjectPath(), and Parent.
FastLess()
bool FSoftObjectPath::FastLess (const FSoftObjectPath & Other) const inline nodiscard
Return true if this path appears before Other using fast index-based fname order.
Definition at line 371 of file SoftObjectPath.h.
References FSoftObjectPath(), AssetPath, Other, and SubPathString.
Referenced by FSoftObjectPathFastLess::operator()().
FixupCoreRedirects()
bool FSoftObjectPath::FixupCoreRedirects ()
Fixes soft object path for CoreRedirects to handle renamed native objects, returns true if it was modified.
FixupForPIE() [1/2]
bool FSoftObjectPath::FixupForPIE (int32 PIEInstance, TFunctionRef< void(int32, FSoftObjectPath &)> InPreFixupForPIECustomFunction = FSoftObjectPath_DefaultPreFixupForPIEFunction)
Fixes up this SoftObjectPath to add the PIE prefix for the given PIEInstance index, returns true if it was modified.
References FSoftObjectPath(), and FSoftObjectPath_DefaultPreFixupForPIEFunction.
FixupForPIE() [2/2]
bool FSoftObjectPath::FixupForPIE (TFunctionRef< void(int32, FSoftObjectPath &)> InPreFixupForPIECustomFunction = FSoftObjectPath_DefaultPreFixupForPIEFunction)
Fixes up this SoftObjectPath to add the PIE prefix depending on what is currently active, returns true if it was modified.
The overload that takes an explicit PIE instance is preferred, if it's available.
References FSoftObjectPath(), and FSoftObjectPath_DefaultPreFixupForPIEFunction.
GetAssetFName()
FName FSoftObjectPath::GetAssetFName () const inline nodiscard
Returns assetname string, leaving off the /package/path part and sub object.
Definition at line 273 of file SoftObjectPath.h.
References FTopLevelAssetPath::GetAssetName(), and GetAssetPath().
GetAssetName()
FString FSoftObjectPath::GetAssetName () const inline nodiscard
Returns assetname string, leaving off the /package/path part and sub object.
Definition at line 266 of file SoftObjectPath.h.
References FTopLevelAssetPath::GetAssetName(), and GetAssetPath().
Referenced by FSoftObjectPtr::GetAssetName(), TSoftClassPtr< const T >::GetAssetName(), and TSoftObjectPtr< const T >::GetAssetName().
GetAssetPath()
FTopLevelAssetPath FSoftObjectPath::GetAssetPath () const inline nodiscard
Returns the top-level asset part of this path, without the subobject path.
Definition at line 209 of file SoftObjectPath.h.
References AssetPath.
Referenced by GetAssetFName(), GetAssetName(), GetLongPackageFName(), and GetLongPackageName().
GetAssetPathString()
FORCEINLINE FString FSoftObjectPath::GetAssetPathString () const inline nodiscard
Returns string version of asset path, including both package and asset but not sub object.
Definition at line 221 of file SoftObjectPath.h.
References AssetPath, and FORCEINLINE.
GetLongPackageFName()
FName FSoftObjectPath::GetLongPackageFName () const inline nodiscard
Returns /package/path, leaving off the asset name and sub object.
Definition at line 260 of file SoftObjectPath.h.
References GetAssetPath(), and FTopLevelAssetPath::GetPackageName().
Referenced by FSoftObjectPtr::GetLongPackageFName(), TSoftClassPtr< const T >::GetLongPackageFName(), and TSoftObjectPtr< const T >::GetLongPackageFName().
GetLongPackageName()
FString FSoftObjectPath::GetLongPackageName () const inline nodiscard
Returns /package/path, leaving off the asset name and sub object.
Definition at line 253 of file SoftObjectPath.h.
References GetAssetPath(), FTopLevelAssetPath::GetPackageName(), and PackageName.
Referenced by FSoftObjectPtr::GetLongPackageName(), TSoftClassPtr< const T >::GetLongPackageName(), and TSoftObjectPtr< const T >::GetLongPackageName().
GetOrCreateIDForObject() [1/3]
FORCEINLINE FSoftObjectPath FSoftObjectPath::GetOrCreateIDForObject (const UObject * Object) inline static nodiscard
Definition at line 434 of file SoftObjectPath.h.
References FSoftObjectPath(), FORCEINLINE, GetOrCreateIDForObject(), and Object.
GetOrCreateIDForObject() [2/3]
FSoftObjectPath FSoftObjectPath::GetOrCreateIDForObject (FObjectPtr Object) static nodiscard
References FSoftObjectPath(), and Object.
Referenced by GetOrCreateIDForObject(), and GetOrCreateIDForObject().
GetOrCreateIDForObject() [3/3]
template<typename T> FORCEINLINE FSoftObjectPath FSoftObjectPath::GetOrCreateIDForObject (TObjectPtr< T > Object) inline static nodiscard
Definition at line 439 of file SoftObjectPath.h.
References FSoftObjectPath(), FORCEINLINE, GetOrCreateIDForObject(), and Object.
GetSubPathString()
FORCEINLINE FString FSoftObjectPath::GetSubPathString () const inline nodiscard
Returns the sub path, which is often empty.
Definition at line 233 of file SoftObjectPath.h.
References FORCEINLINE, and SubPathString.
GetSubPathUtf8String()
FORCEINLINE const FUtf8String & FSoftObjectPath::GetSubPathUtf8String () const inline nodiscard
Definition at line 237 of file SoftObjectPath.h.
References FORCEINLINE, and SubPathString.
GetWithoutSubPath()
FSoftObjectPath FSoftObjectPath::GetWithoutSubPath () const inline nodiscard
Returns this path without the SubPath component, restricting the result to a top level asset but keeping the type as FSoftObjectPath in contrast to GetAssetPath.
Definition at line 215 of file SoftObjectPath.h.
References FSoftObjectPath(), and AssetPath.
ImportTextItem()
bool FSoftObjectPath::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText, FArchive * InSerializingArchive = nullptr)
References Buffer, and Parent.
IsAsset()
FORCEINLINE bool FSoftObjectPath::IsAsset () const inline nodiscard
Check if this represents an asset, meaning it is not null but does not have a sub path.
Definition at line 348 of file SoftObjectPath.h.
References AssetPath, FORCEINLINE, and SubPathString.
IsNull()
FORCEINLINE bool FSoftObjectPath::IsNull () const inline nodiscard
Checks to see if this is initialized to null.
Definition at line 342 of file SoftObjectPath.h.
References AssetPath, and FORCEINLINE.
IsSubobject()
FORCEINLINE bool FSoftObjectPath::IsSubobject () const inline nodiscard
Check if this represents a sub object, meaning it has a sub path.
Definition at line 354 of file SoftObjectPath.h.
References AssetPath, FORCEINLINE, and SubPathString.
IsValid()
FORCEINLINE bool FSoftObjectPath::IsValid () const inline nodiscard
Check if this could possibly refer to a real object, or was initialized to null.
Definition at line 336 of file SoftObjectPath.h.
References AssetPath, and FORCEINLINE.
Referenced by FSoftClassPath::TryLoadClass().
LexicalLess()
bool FSoftObjectPath::LexicalLess (const FSoftObjectPath & Other) const inline nodiscard
Return true if this path appears before Other in lexical order.
Definition at line 360 of file SoftObjectPath.h.
References FSoftObjectPath(), AssetPath, Other, and SubPathString.
Referenced by FSoftObjectPathLexicalLess::operator()().
LoadAsync()
int32 FSoftObjectPath::LoadAsync (FLoadSoftObjectPathAsyncDelegate InCompletionDelegate, FLoadAssetAsyncOptionalParams InOptionalParams = FLoadAssetAsyncOptionalParams()) const
Attempts to asynchronously load the object referenced by this path.
This will call LoadAssetAsync to load the top level asset and resolve the sub paths before calling the delegate. FStreamableManager can be used for more control over callback timing and garbage collection.
Parameters
InCompletionDelegate Delegate to be invoked when the async load finishes, this will execute on the game thread as soon as the load succeeds or fails
InOptionalParams Optional parameters for async loading the asset
Returns
Unique ID associated with this load request (the same object or package can be associated with multiple IDs).
operator!=()
bool FSoftObjectPath::operator!= (FSoftObjectPath const & Other) const inline nodiscard
Definition at line 387 of file SoftObjectPath.h.
References FSoftObjectPath(), and Other.
operator=() [1/9]
FSoftObjectPath & FSoftObjectPath::operator= (const ANSICHAR * Path) inline
Definition at line 185 of file SoftObjectPath.h.
References FSoftObjectPath(), Path, and SetPath().
operator=() [2/9]
FSoftObjectPath & FSoftObjectPath::operator= (const FSoftObjectPath & Path) default
References FSoftObjectPath(), and Path.
operator=() [3/9]
FSoftObjectPath & FSoftObjectPath::operator= (const FString & Path) inline
Definition at line 165 of file SoftObjectPath.h.
References FSoftObjectPath(), Path, and SetPath().
operator=() [4/9]
FSoftObjectPath & FSoftObjectPath::operator= (const FTopLevelAssetPath Path) inline
Definition at line 160 of file SoftObjectPath.h.
References FSoftObjectPath(), Path, and SetPath().
operator=() [5/9]
FSoftObjectPath & FSoftObjectPath::operator= (const WIDECHAR * Path) inline
Definition at line 180 of file SoftObjectPath.h.
References FSoftObjectPath(), Path, and SetPath().
operator=() [6/9]
FSoftObjectPath & FSoftObjectPath::operator= (FAnsiStringView Path) inline
Definition at line 175 of file SoftObjectPath.h.
References FSoftObjectPath(), Path, and SetPath().
operator=() [7/9]
FSoftObjectPath & FSoftObjectPath::operator= (FSoftObjectPath && Path) default
References FSoftObjectPath(), and Path.
operator=() [8/9]
FSoftObjectPath & FSoftObjectPath::operator= (FWideStringView Path) inline
Definition at line 170 of file SoftObjectPath.h.
References FSoftObjectPath(), Path, and SetPath().
operator=() [9/9]
FSoftObjectPath & FSoftObjectPath::operator= (TYPE_OF_NULLPTR) inline
Definition at line 190 of file SoftObjectPath.h.
References FSoftObjectPath(), and Reset().
operator==()
bool FSoftObjectPath::operator== (FSoftObjectPath const & Other) const nodiscard
References FSoftObjectPath(), and Other.
PostLoadPath()
void FSoftObjectPath::PostLoadPath (FArchive * InArchive) const
Handles when a path has been loaded, call if loading with a method that skips SerializePath.
This does not modify path but might call callbacks
Parameters
InArchive The archive that loaded this path
PreSavePath()
bool FSoftObjectPath::PreSavePath (bool * bReportSoftObjectPathRedirects = nullptr)
Fixes up path for saving, call if saving with a method that skips SerializePath.
This can modify the path, it will return true if it was modified
RemapPackage()
bool FSoftObjectPath::RemapPackage (FName OldPackageName, FName NewPackageName)
Remap the package to handle renames.
Reset()
void FSoftObjectPath::Reset () inline
Resets reference to point to null.
Definition at line 329 of file SoftObjectPath.h.
References AssetPath, and SubPathString.
Referenced by operator=().
ResolveObject()
UObject * FSoftObjectPath::ResolveObject () const nodiscard
Attempts to find a currently loaded object that matches this path.
Returns
Found UObject, or nullptr if not currently in memory
Referenced by FSoftObjectPtr::Get(), and operator<<().
ResolveObjectInternal()
UObject * FSoftObjectPath::ResolveObjectInternal () const nodiscard private
Serialize() [1/2]
bool FSoftObjectPath::Serialize (FArchive & Ar)
Struct overrides.
References Ar.
Serialize() [2/2]
bool FSoftObjectPath::Serialize (FStructuredArchive::FSlot Slot)
SerializeFromMismatchedTag()
bool FSoftObjectPath::SerializeFromMismatchedTag (struct FPropertyTag const & Tag, FStructuredArchive::FSlot Slot)
SerializePath()
void FSoftObjectPath::SerializePath (FArchive & Ar)
Serializes the internal path and also handles save/PIE fixups.
Call this from the archiver overrides
References Ar.
SerializePathWithoutFixup()
void FSoftObjectPath::SerializePathWithoutFixup (FArchive & Ar)
Serializes the internal path without any save/PIE fixups.
Only call this directly if you know what you are doing
References Ar.
SetPath() [1/10]
void FSoftObjectPath::SetPath (const ANSICHAR * Path) inline
Definition at line 291 of file SoftObjectPath.h.
References Path, and SetPath().
SetPath() [2/10]
void FSoftObjectPath::SetPath (const FString & Path) inline
Definition at line 295 of file SoftObjectPath.h.
References Path, and SetPath().
SetPath() [3/10]
void FSoftObjectPath::SetPath (const FTopLevelAssetPath & InAssetPath)
Sets asset path of this reference based on a string path.
Referenced by FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), FSoftObjectPath(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), SetPath(), SetPath(), SetPath(), SetPath(), SetPath(), SetPath(), SetPath(), SetPath(), and SetPath().
SetPath() [4/10]
void FSoftObjectPath::SetPath (const FTopLevelAssetPath & InAssetPath, TStringOverload< FUtf8String > InSubPathString)
References InSubPathString, and SetPath().
SetPath() [5/10]
void FSoftObjectPath::SetPath (const FTopLevelAssetPath & InAssetPath, TStringOverload< FWideString > InSubPathString)
References InSubPathString, and SetPath().
SetPath() [6/10]
void FSoftObjectPath::SetPath (const UObject * InObject)
References SetPath().
SetPath() [7/10]
void FSoftObjectPath::SetPath (const WIDECHAR * Path) inline
Definition at line 287 of file SoftObjectPath.h.
References Path, and SetPath().
SetPath() [8/10]
void FSoftObjectPath::SetPath (FAnsiStringView Path)
References Path, and SetPath().
SetPath() [9/10]
void FSoftObjectPath::SetPath (FUtf8StringView Path)
References Path, and SetPath().
SetPath() [10/10]
void FSoftObjectPath::SetPath (FWideStringView Path)
References Path, and SetPath().
SetSubPathString() [1/2]
FORCEINLINE void FSoftObjectPath::SetSubPathString (TStringOverload< FUtf8String > InSubPathString) inline
Definition at line 247 of file SoftObjectPath.h.
References FORCEINLINE, InSubPathString, and SubPathString.
SetSubPathString() [2/2]
FORCEINLINE void FSoftObjectPath::SetSubPathString (TStringOverload< FWideString > InSubPathString) inline
Definition at line 243 of file SoftObjectPath.h.
References FORCEINLINE, InSubPathString, SetSubPathString(), and SubPathString.
Referenced by SetSubPathString().
ToString() [1/3]
FString FSoftObjectPath::ToString () const nodiscard
Returns string representation of reference, in form /package/path.assetname[:subpath].
Referenced by FRigVMCompilerWorkData::FFunctionRegisterData::GetTypeHash, FSoftObjectPtr::ToString(), TSoftClassPtr< const T >::ToString(), TSoftObjectPtr< const T >::ToString(), and FSoftClassPath::TryLoadClass().
ToString() [2/3]
void FSoftObjectPath::ToString (FStringBuilderBase & Builder) const
Append string representation of reference, in form /package/path.assetname[:subpath].
ToString() [3/3]
void FSoftObjectPath::ToString (FUtf8StringBuilderBase & Builder) const
TryLoad()
UObject * FSoftObjectPath::TryLoad (FUObjectSerializeContext * InLoadContext = nullptr) const
Attempts to load the asset, this will call LoadObject which can be very slow.
Parameters
InLoadContext Optional load context when called from nested load callstack
Returns
Loaded UObject, or nullptr if the reference is null or the asset fails to load
Referenced by FSoftObjectPtr::LoadSynchronous().
UE_DEPRECATED() [1/3]
FSoftObjectPath::UE_DEPRECATED (5. 6, "FSoftObjectPath which takes a package name and asset name has been deprecated - please pass FTopLevelAssetPath instead.") nodiscard
UE_DEPRECATED() [2/3]
FSoftObjectPath::UE_DEPRECATED (5. 6, "FSoftObjectPath::ConstructFromPackageAsset has been deprecated - please use ConstructFromAssetPath instead.") nodiscard
References FSoftObjectPath(), and InAssetName.
UE_DEPRECATED() [3/3]
FSoftObjectPath::UE_DEPRECATED (5. 6, "FSoftObjectPath::ConstructFromPackageAssetSubpath has been deprecated - please use ConstructFromAssetPathAndSubpath instead.") nodiscard
Static methods for more meaningful construction sites.
References FSoftObjectPath(), InAssetName, and InSubPathString.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE friend uint32 GetTypeHash (FSoftObjectPath const & This) friend
Definition at line 421 of file SoftObjectPath.h.
References FSoftObjectPath(), FORCEINLINE, GetTypeHash, Hash, and HashCombineFast().
Referenced by GetTypeHash.
SerializeForLog
void SerializeForLog (FCbWriter & Writer, const FSoftObjectPath & Value) friend
References FSoftObjectPath(), and Value.
Z_Construct_UScriptStruct_FSoftObjectPath_Statics
friend struct Z_Construct_UScriptStruct_FSoftObjectPath_Statics friend
Definition at line 476 of file SoftObjectPath.h.
References Z_Construct_UScriptStruct_FSoftObjectPath_Statics.
Referenced by Z_Construct_UScriptStruct_FSoftObjectPath_Statics.
Field Documentation
AssetPath
FTopLevelAssetPath FSoftObjectPath::AssetPath private
Asset path, patch to a top level object in a package.
This is /package/path.assetname
Definition at line 465 of file SoftObjectPath.h.
Referenced by FastLess(), GetAssetPath(), GetAssetPathString(), GetWithoutSubPath(), IsAsset(), IsNull(), IsSubobject(), IsValid(), LexicalLess(), and Reset().
InAssetName
FName FSoftObjectPath::InAssetName
Definition at line 75 of file SoftObjectPath.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
InSubPathString
FName const FString & FSoftObjectPath::InSubPathString
Initial value:
{
        SetPath(FTopLevelAssetPath(InPackageName, InAssetName), FUtf8String(InSubPathString))
Definition at line 75 of file SoftObjectPath.h.
Referenced by FSoftObjectPath(), FSoftObjectPath(), ConstructFromAssetPathAndSubpath(), ConstructFromAssetPathAndSubpath(), SetPath(), SetPath(), SetSubPathString(), SetSubPathString(), and UE_DEPRECATED().
NAME_Untracked
FName FSoftObjectPath::NAME_Untracked static
Text of the Untracked parameter in a UPROPERTY's meta field, if this parameter is present it marks that the SoftObjectPath reference should not cause the target package to be added to the cook.
Definition at line 461 of file SoftObjectPath.h.
PIEPackageNames
TSet<FName> FSoftObjectPath::PIEPackageNames static private
Package names currently being duplicated, needed by FixupForPIE.
Definition at line 471 of file SoftObjectPath.h.
SubPathString
FUtf8String FSoftObjectPath::SubPathString private
Optional FString for subobject within an asset.
This is the sub path after the :
Definition at line 468 of file SoftObjectPath.h.
Referenced by FastLess(), GetSubPathString(), GetSubPathUtf8String(), IsAsset(), IsSubobject(), LexicalLess(), Reset(), SetSubPathString(), and SetSubPathString().
The documentation for this struct was generated from the following file:
SoftObjectPath.h