Unreal Engine 5.6 C++ API: FPixelStreamingSignallingConnection Class Reference
FPixelStreamingSignallingConnection Class Reference
A specialized signalling server connection object for web socket based Pixel Streaming signalling servers.
#include "PixelStreamingSignallingConnection.h"
Public Member Functions
FPixelStreamingSignallingConnection (TSharedPtr< IPixelStreamingSignallingConnectionObserver > InObserver, FString InStreamerId="", TSharedPtr< IWebSocket > InWebSocket=nullptr)
virtual ~FPixelStreamingSignallingConnection ()
virtual void Disconnect (FString Reason) override
Disconnects from the signalling server with a reason message.
virtual bool IsConnected () const override
Checks if the connection is established.
virtual void RequestStreamerList () override
Request a list of active streamers from the signalling server.
virtual void SendAnswer (const webrtc::SessionDescriptionInterface &SDP) override
[Stream receiver only] Sends an answer back to the streamer after receiving an offer.
virtual void SendAnswer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface &SDP) override
[Streamer only] Sends an answer to the specified player.
virtual void SendDisconnectPlayer (FPixelStreamingPlayerId PlayerId, const FString &Reason) override
[Streamer only] Send a disconnect message to the specified player.
virtual void SendIceCandidate (const webrtc::IceCandidateInterface &IceCandidate) override
[Stream receiver only] Sends ICE candidate information to the streamer.
virtual void SendIceCandidate (FPixelStreamingPlayerId PlayerId, const webrtc::IceCandidateInterface &IceCandidate) override
[Streamer only] Sends ice candidate information to the specified player.
virtual void SendMessage (const FString &Msg) override
Send a message to the signalling server.
virtual void SendOffer (const webrtc::SessionDescriptionInterface &SDP) override
[Stream receiver only] Sends an offer to the streamer.
virtual void SendOffer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface &SDP) override
[Streamer only] Sends an offer to the specified player.
virtual void SendSubscribe (const FString &StreamerId) override
[Stream receiver only] Send a subscription request to the signalling server.
virtual void SendUnsubscribe () override
[Stream receiver only] Send an unsubscribe request to the signalling server.
virtual void SetAutoReconnect (bool bAutoReconnect) override
Toggles automatic reconnecting when websocket is closed or unreachable.
virtual void SetKeepAlive (bool bKeepAlive) override
Enables or disables the keep alive pings on this connection.
virtual void TryConnect (FString URL) override
Connect to a specified signalling server at ths given URL.
UE_DEPRECATED (5.4, "Disconnect has been deprecated and will be removed in future versions. Please use: Disconnect(FString Reason)") virtual void Disconnect() override
Disconnects from the signalling server.
Public Member Functions inherited from IPixelStreamingSignallingConnection
virtual ~IPixelStreamingSignallingConnection ()
Private Types
using FJsonObjectPtr = TSharedPtr<FJsonObject>
Private Member Functions
void Connect (FString Url, bool bIsReconnect)
bool GetPlayerIdJson (const FJsonObjectPtr &Json, FPixelStreamingPlayerId &OutPlayerId, const FString &FieldId=TEXT("playerId"))
void OnBinaryMessage (const uint8 *Data, int32 Length, bool bIsLastFragment)
void OnClosed (int32 StatusCode, const FString &Reason, bool bWasClean)
void OnConfig (const FJsonObjectPtr &Json)
void OnConnected ()
void OnConnectionError (const FString &Error)
void OnIceCandidate (const FJsonObjectPtr &Json)
void OnIdRequested ()
void OnMessage (const FString &Msg)
void OnPeerDataChannels (const FJsonObjectPtr &Json)
void OnPing (const FJsonObjectPtr &Json)
void OnPlayerConnected (const FJsonObjectPtr &Json)
void OnPlayerCount (const FJsonObjectPtr &Json)
void OnPlayerDisconnected (const FJsonObjectPtr &Json)
void OnPong (const FJsonObjectPtr &Json)
void OnSessionDescription (const FJsonObjectPtr &Json)
void OnSFUPeerDataChannels (const FJsonObjectPtr &Json)
void OnStreamerList (const FJsonObjectPtr &Json)
void PlayerError (FPixelStreamingPlayerId PlayerId, const FString &Msg)
template<typename... T>
void PlayerError (FPixelStreamingPlayerId PlayerId, UE::Core::TCheckedFormatString< FString::FmtCharType, T... > Msg, T... args)
void RegisterHandler (const FString &messageType, const TFunction< void(FJsonObjectPtr)> &handler)
template<typename T>
void SafeGameThreadExecute (T &&Func)
These templates are defined in the cpp since theyre private and we dont want to include the private include file "Utils.h" here in this public header.
template<typename T>
void SafeGameThreadExecuteAndWait (uint32 Timeout, T &&Func)
void SetPlayerIdJson (FJsonObjectPtr &JsonObject, FPixelStreamingPlayerId PlayerId)
void StartKeepAliveTimer ()
void StartReconnectTimer ()
void StopKeepAliveTimer ()
void StopReconnectTimer ()
Private Attributes
TSharedPtr< int > AliveSemaphore
bool bAutoReconnectEnabled = true
bool bIsConnected = false
bool bKeepAliveEnabled = true
const float KEEP_ALIVE_INTERVAL = 60.0f
TMap< FString, TFunction< void(FJsonObjectPtr)> > MessageHandlers
TSharedPtr< IPixelStreamingSignallingConnectionObserver > Observer
FDelegateHandle OnBinaryMessageHandle
FDelegateHandle OnClosedHandle
FDelegateHandle OnConnectedHandle
FDelegateHandle OnConnectionErrorHandle
FDelegateHandle OnMessageHandle
FString StreamerId
FTimerHandle TimerHandle_KeepAlive
Handle for efficient management of KeepAlive timer.
FTimerHandle TimerHandle_Reconnect
FString Url
TSharedPtr< IWebSocket > WebSocket
Detailed Description
A specialized signalling server connection object for web socket based Pixel Streaming signalling servers.
Definition at line 17 of file PixelStreamingSignallingConnection.h.
Member Typedef Documentation
FJsonObjectPtr
using FPixelStreamingSignallingConnection::FJsonObjectPtr = TSharedPtr<FJsonObject> private
Definition at line 51 of file PixelStreamingSignallingConnection.h.
Constructor & Destructor Documentation
FPixelStreamingSignallingConnection()
FPixelStreamingSignallingConnection::FPixelStreamingSignallingConnection (TSharedPtr< IPixelStreamingSignallingConnectionObserver > InObserver, FString InStreamerId = "", TSharedPtr< IWebSocket > InWebSocket = nullptr)
~FPixelStreamingSignallingConnection()
virtual FPixelStreamingSignallingConnection::~FPixelStreamingSignallingConnection () virtual
Member Function Documentation
Connect()
void FPixelStreamingSignallingConnection::Connect (FString Url, bool bIsReconnect) private
References Connect(), and Url.
Referenced by Connect().
Disconnect()
virtual void FPixelStreamingSignallingConnection::Disconnect (FString Reason) override virtual
Disconnects from the signalling server with a reason message.
Safe to call even when not connected.
Implements IPixelStreamingSignallingConnection.
References Disconnect().
Referenced by Disconnect(), and UE_DEPRECATED().
GetPlayerIdJson()
bool FPixelStreamingSignallingConnection::GetPlayerIdJson (const FJsonObjectPtr & Json, FPixelStreamingPlayerId & OutPlayerId, const FString & FieldId = TEXT("playerId")) private
References GetPlayerIdJson(), and TEXT.
Referenced by GetPlayerIdJson().
IsConnected()
virtual bool FPixelStreamingSignallingConnection::IsConnected () const override virtual
Checks if the connection is established.
Returns
True when the signalling server is connected.
Implements IPixelStreamingSignallingConnection.
References IsConnected().
Referenced by IsConnected().
OnBinaryMessage()
void FPixelStreamingSignallingConnection::OnBinaryMessage (const uint8 * Data, int32 Length, bool bIsLastFragment) private
References OnBinaryMessage().
Referenced by OnBinaryMessage().
OnClosed()
void FPixelStreamingSignallingConnection::OnClosed (int32 StatusCode, const FString & Reason, bool bWasClean) private
References OnClosed().
Referenced by OnClosed().
OnConfig()
void FPixelStreamingSignallingConnection::OnConfig (const FJsonObjectPtr & Json) private
References OnConfig().
Referenced by OnConfig().
OnConnected()
void FPixelStreamingSignallingConnection::OnConnected () private
References OnConnected().
Referenced by OnConnected().
OnConnectionError()
void FPixelStreamingSignallingConnection::OnConnectionError (const FString & Error) private
References Error, and OnConnectionError().
Referenced by OnConnectionError().
OnIceCandidate()
void FPixelStreamingSignallingConnection::OnIceCandidate (const FJsonObjectPtr & Json) private
References OnIceCandidate().
Referenced by OnIceCandidate().
OnIdRequested()
void FPixelStreamingSignallingConnection::OnIdRequested () private
References OnIdRequested().
Referenced by OnIdRequested().
OnMessage()
void FPixelStreamingSignallingConnection::OnMessage (const FString & Msg) private
References OnMessage().
Referenced by OnMessage().
OnPeerDataChannels()
void FPixelStreamingSignallingConnection::OnPeerDataChannels (const FJsonObjectPtr & Json) private
References OnPeerDataChannels().
Referenced by OnPeerDataChannels().
OnPing()
void FPixelStreamingSignallingConnection::OnPing (const FJsonObjectPtr & Json) private
References OnPing().
Referenced by OnPing().
OnPlayerConnected()
void FPixelStreamingSignallingConnection::OnPlayerConnected (const FJsonObjectPtr & Json) private
References OnPlayerConnected().
Referenced by OnPlayerConnected().
OnPlayerCount()
void FPixelStreamingSignallingConnection::OnPlayerCount (const FJsonObjectPtr & Json) private
References OnPlayerCount().
Referenced by OnPlayerCount().
OnPlayerDisconnected()
void FPixelStreamingSignallingConnection::OnPlayerDisconnected (const FJsonObjectPtr & Json) private
References OnPlayerDisconnected().
Referenced by OnPlayerDisconnected().
OnPong()
void FPixelStreamingSignallingConnection::OnPong (const FJsonObjectPtr & Json) private
References OnPong().
Referenced by OnPong().
OnSessionDescription()
void FPixelStreamingSignallingConnection::OnSessionDescription (const FJsonObjectPtr & Json) private
References OnSessionDescription().
Referenced by OnSessionDescription().
OnSFUPeerDataChannels()
void FPixelStreamingSignallingConnection::OnSFUPeerDataChannels (const FJsonObjectPtr & Json) private
References OnSFUPeerDataChannels().
Referenced by OnSFUPeerDataChannels().
OnStreamerList()
void FPixelStreamingSignallingConnection::OnStreamerList (const FJsonObjectPtr & Json) private
References OnStreamerList().
Referenced by OnStreamerList().
PlayerError() [1/2]
void FPixelStreamingSignallingConnection::PlayerError (FPixelStreamingPlayerId PlayerId, const FString & Msg) private
PlayerError() [2/2]
template<typename... T> void FPixelStreamingSignallingConnection::PlayerError (FPixelStreamingPlayerId PlayerId, UE::Core::TCheckedFormatString< FString::FmtCharType, T... > Msg, T... args) inline private
Definition at line 76 of file PixelStreamingSignallingConnection.h.
References Core, and PlayerError().
Referenced by PlayerError().
RegisterHandler()
void FPixelStreamingSignallingConnection::RegisterHandler (const FString & messageType, const TFunction< void(FJsonObjectPtr)> & handler) private
References RegisterHandler().
Referenced by RegisterHandler().
RequestStreamerList()
virtual void FPixelStreamingSignallingConnection::RequestStreamerList () override virtual
Request a list of active streamers from the signalling server.
This is a request to the signalling server so can be used by anyone.
Implements IPixelStreamingSignallingConnection.
References RequestStreamerList().
Referenced by RequestStreamerList().
SafeGameThreadExecute()
template<typename T> void FPixelStreamingSignallingConnection::SafeGameThreadExecute (T && Func) private
These templates are defined in the cpp since theyre private and we dont want to include the private include file "Utils.h" here in this public header.
SafeGameThreadExecuteAndWait()
template<typename T> void FPixelStreamingSignallingConnection::SafeGameThreadExecuteAndWait (uint32 Timeout, T && Func) private
References Timeout.
SendAnswer() [1/2]
virtual void FPixelStreamingSignallingConnection::SendAnswer (const webrtc::SessionDescriptionInterface & SDP) override virtual
[Stream receiver only] Sends an answer back to the streamer after receiving an offer.
Parameters
SDP The local description answer.
Implements IPixelStreamingSignallingConnection.
References SendAnswer().
SendAnswer() [2/2]
virtual void FPixelStreamingSignallingConnection::SendAnswer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface & SDP) override virtual
[Streamer only] Sends an answer to the specified player.
Parameters
PlayerId The Id of the destination player.
SDP The answer session description for the player.
Implements IPixelStreamingSignallingConnection.
References SendAnswer().
Referenced by SendAnswer(), and SendAnswer().
SendDisconnectPlayer()
virtual void FPixelStreamingSignallingConnection::SendDisconnectPlayer (FPixelStreamingPlayerId PlayerId, const FString & Reason) override virtual
[Streamer only] Send a disconnect message to the specified player.
Parameters
PlayerId The Id of the destination player.
Reason An optional reason for the disconnection.
Implements IPixelStreamingSignallingConnection.
References SendDisconnectPlayer().
Referenced by SendDisconnectPlayer().
SendIceCandidate() [1/2]
virtual void FPixelStreamingSignallingConnection::SendIceCandidate (const webrtc::IceCandidateInterface & IceCandidate) override virtual
[Stream receiver only] Sends ICE candidate information to the streamer.
Parameters
IceCandidate The ICE candidate information.
Implements IPixelStreamingSignallingConnection.
References SendIceCandidate().
SendIceCandidate() [2/2]
virtual void FPixelStreamingSignallingConnection::SendIceCandidate (FPixelStreamingPlayerId PlayerId, const webrtc::IceCandidateInterface & IceCandidate) override virtual
[Streamer only] Sends ice candidate information to the specified player.
Parameters
PlayerId The Id of the destination player.
IceCandidate The ice candidate information to send.
Implements IPixelStreamingSignallingConnection.
References SendIceCandidate().
Referenced by SendIceCandidate(), and SendIceCandidate().
SendMessage()
virtual void FPixelStreamingSignallingConnection::SendMessage (const FString & Msg) override virtual
Send a message to the signalling server.
Parameters
Msg A string message to send - typically a JSON payload.
Implements IPixelStreamingSignallingConnection.
References SendMessage().
Referenced by SendMessage().
SendOffer() [1/2]
virtual void FPixelStreamingSignallingConnection::SendOffer (const webrtc::SessionDescriptionInterface & SDP) override virtual
[Stream receiver only] Sends an offer to the streamer.
Parameters
SDP The local description offer.
Implements IPixelStreamingSignallingConnection.
References SendOffer().
SendOffer() [2/2]
virtual void FPixelStreamingSignallingConnection::SendOffer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface & SDP) override virtual
[Streamer only] Sends an offer to the specified player.
Parameters
PlayerId The Id of the destination player.
SDP The offer session description for the player.
Implements IPixelStreamingSignallingConnection.
References SendOffer().
Referenced by SendOffer(), and SendOffer().
SendSubscribe()
virtual void FPixelStreamingSignallingConnection::SendSubscribe (const FString & StreamerId) override virtual
[Stream receiver only] Send a subscription request to the signalling server.
Parameters
StreamerId The ID of the streamer to subscribe to.
Implements IPixelStreamingSignallingConnection.
References SendSubscribe(), and StreamerId.
Referenced by SendSubscribe().
SendUnsubscribe()
virtual void FPixelStreamingSignallingConnection::SendUnsubscribe () override virtual
[Stream receiver only] Send an unsubscribe request to the signalling server.
Implements IPixelStreamingSignallingConnection.
References SendUnsubscribe().
Referenced by SendUnsubscribe().
SetAutoReconnect()
virtual void FPixelStreamingSignallingConnection::SetAutoReconnect (bool bAutoReconnect) override virtual
Toggles automatic reconnecting when websocket is closed or unreachable.
Parameters
bAutoReconnect True to enable auto reconnect. False to disable.
Implements IPixelStreamingSignallingConnection.
References SetAutoReconnect().
Referenced by SetAutoReconnect().
SetKeepAlive()
virtual void FPixelStreamingSignallingConnection::SetKeepAlive (bool bKeepAlive) override virtual
Enables or disables the keep alive pings on this connection.
Receiving connections should disable the keep alive since the reference signalling server will reject pings from players and close the connection.
Parameters
bKeepAlive True to enable keep alive pings. False to disable.
Implements IPixelStreamingSignallingConnection.
References SetKeepAlive().
Referenced by SetKeepAlive().
SetPlayerIdJson()
void FPixelStreamingSignallingConnection::SetPlayerIdJson (FJsonObjectPtr & JsonObject, FPixelStreamingPlayerId PlayerId) private
References SetPlayerIdJson().
Referenced by SetPlayerIdJson().
StartKeepAliveTimer()
void FPixelStreamingSignallingConnection::StartKeepAliveTimer () private
References StartKeepAliveTimer().
Referenced by StartKeepAliveTimer().
StartReconnectTimer()
void FPixelStreamingSignallingConnection::StartReconnectTimer () private
References StartReconnectTimer().
Referenced by StartReconnectTimer().
StopKeepAliveTimer()
void FPixelStreamingSignallingConnection::StopKeepAliveTimer () private
References StopKeepAliveTimer().
Referenced by StopKeepAliveTimer().
StopReconnectTimer()
void FPixelStreamingSignallingConnection::StopReconnectTimer () private
References StopReconnectTimer().
Referenced by StopReconnectTimer().
TryConnect()
virtual void FPixelStreamingSignallingConnection::TryConnect (FString URL) override virtual
Connect to a specified signalling server at ths given URL.
Parameters
URL The url of the destination signalling server.
Implements IPixelStreamingSignallingConnection.
UE_DEPRECATED()
FPixelStreamingSignallingConnection::UE_DEPRECATED (5. 4, "Disconnect has been deprecated and will be removed in future versions. Please use: Disconnect(FString Reason)") override virtual
Disconnects from the signalling server.
Safe to call even when not connected.
Implements IPixelStreamingSignallingConnection.
References Disconnect().
Field Documentation
AliveSemaphore
TSharedPtr<int> FPixelStreamingSignallingConnection::AliveSemaphore private
Definition at line 109 of file PixelStreamingSignallingConnection.h.
bAutoReconnectEnabled
bool FPixelStreamingSignallingConnection::bAutoReconnectEnabled = true private
Definition at line 96 of file PixelStreamingSignallingConnection.h.
bIsConnected
bool FPixelStreamingSignallingConnection::bIsConnected = false private
Definition at line 98 of file PixelStreamingSignallingConnection.h.
bKeepAliveEnabled
bool FPixelStreamingSignallingConnection::bKeepAliveEnabled = true private
Definition at line 97 of file PixelStreamingSignallingConnection.h.
KEEP_ALIVE_INTERVAL
const float FPixelStreamingSignallingConnection::KEEP_ALIVE_INTERVAL = 60.0f private
Definition at line 102 of file PixelStreamingSignallingConnection.h.
MessageHandlers
TMap<FString, TFunction<void(FJsonObjectPtr)> > FPixelStreamingSignallingConnection::MessageHandlers private
Definition at line 104 of file PixelStreamingSignallingConnection.h.
Observer
TSharedPtr<IPixelStreamingSignallingConnectionObserver> FPixelStreamingSignallingConnection::Observer private
Definition at line 84 of file PixelStreamingSignallingConnection.h.
OnBinaryMessageHandle
FDelegateHandle FPixelStreamingSignallingConnection::OnBinaryMessageHandle private
Definition at line 94 of file PixelStreamingSignallingConnection.h.
OnClosedHandle
FDelegateHandle FPixelStreamingSignallingConnection::OnClosedHandle private
Definition at line 92 of file PixelStreamingSignallingConnection.h.
OnConnectedHandle
FDelegateHandle FPixelStreamingSignallingConnection::OnConnectedHandle private
Definition at line 90 of file PixelStreamingSignallingConnection.h.
OnConnectionErrorHandle
FDelegateHandle FPixelStreamingSignallingConnection::OnConnectionErrorHandle private
Definition at line 91 of file PixelStreamingSignallingConnection.h.
OnMessageHandle
FDelegateHandle FPixelStreamingSignallingConnection::OnMessageHandle private
Definition at line 93 of file PixelStreamingSignallingConnection.h.
StreamerId
FString FPixelStreamingSignallingConnection::StreamerId private
Definition at line 85 of file PixelStreamingSignallingConnection.h.
Referenced by SendSubscribe().
TimerHandle_KeepAlive
FTimerHandle FPixelStreamingSignallingConnection::TimerHandle_KeepAlive private
Handle for efficient management of KeepAlive timer.
Definition at line 100 of file PixelStreamingSignallingConnection.h.
TimerHandle_Reconnect
FTimerHandle FPixelStreamingSignallingConnection::TimerHandle_Reconnect private
Definition at line 101 of file PixelStreamingSignallingConnection.h.
Url
FString FPixelStreamingSignallingConnection::Url private
Definition at line 86 of file PixelStreamingSignallingConnection.h.
Referenced by Connect().
WebSocket
TSharedPtr<IWebSocket> FPixelStreamingSignallingConnection::WebSocket private
Definition at line 88 of file PixelStreamingSignallingConnection.h.
The documentation for this class was generated from the following file:
PixelStreamingSignallingConnection.h