Unreal Engine 5.6 C++ API: FChaosDerivedDataReader< T, d > Class Template Reference
FChaosDerivedDataReader< T, d > Class Template Reference
#include "ChaosDerivedDataReader.h"
Public Member Functions
FChaosDerivedDataReader (FBulkData *InBulkData)
Data Fields
UE_DEPRECATED(5.4, "Please use ConvexGeometries instead") TArray< TSharedPtr< Chaos UE_DEPRECATED(5.4, "Please use TrimeshGeometries instead") TArray< TSharedPtr< Chaos TArray< Chaos::FConvexPtr > ConvexGeometries
TArray< int32 > FaceRemap
TArray< Chaos::FTriangleMeshImplicitObjectPtr > TriMeshGeometries
FBodySetupUVInfo UVInfo
Private Member Functions
FChaosDerivedDataReader ()=delete
FChaosDerivedDataReader (const FChaosDerivedDataReader &Other)=delete
FChaosDerivedDataReader (FChaosDerivedDataReader &&Other)=delete
FChaosDerivedDataReader & operator= (const FChaosDerivedDataReader &Other)=delete
FChaosDerivedDataReader & operator= (FChaosDerivedDataReader &&Other)=delete
Private Attributes
bool bReadSuccessful
Detailed Description
template<typename T, int d>
class FChaosDerivedDataReader< T, d >
Definition at line 17 of file ChaosDerivedDataReader.h.
Constructor & Destructor Documentation
FChaosDerivedDataReader() [1/4]
template<typename T, int d> FChaosDerivedDataReader< T, d >::FChaosDerivedDataReader (FBulkData * InBulkData) explicit
References ThreadSafe, and UE_DEPRECATED.
Referenced by FChaosDerivedDataReader(), FChaosDerivedDataReader(), FChaosDerivedDataReader(), operator=(), and operator=().
FChaosDerivedDataReader() [2/4]
template<typename T, int d> FChaosDerivedDataReader< T, d >::FChaosDerivedDataReader () private delete
References FChaosDerivedDataReader().
FChaosDerivedDataReader() [3/4]
template<typename T, int d> FChaosDerivedDataReader< T, d >::FChaosDerivedDataReader (const FChaosDerivedDataReader< T, d > & Other) private delete
References FChaosDerivedDataReader(), and Other.
FChaosDerivedDataReader() [4/4]
template<typename T, int d> FChaosDerivedDataReader< T, d >::FChaosDerivedDataReader (FChaosDerivedDataReader< T, d > && Other) private delete
References FChaosDerivedDataReader(), and Other.
Member Function Documentation
operator=() [1/2]
template<typename T, int d> FChaosDerivedDataReader & FChaosDerivedDataReader< T, d >::operator= (const FChaosDerivedDataReader< T, d > & Other) private delete
References FChaosDerivedDataReader(), and Other.
operator=() [2/2]
template<typename T, int d> FChaosDerivedDataReader & FChaosDerivedDataReader< T, d >::operator= (FChaosDerivedDataReader< T, d > && Other) private delete
References FChaosDerivedDataReader(), and Other.
Field Documentation
bReadSuccessful
template<typename T, int d> bool FChaosDerivedDataReader< T, d >::bReadSuccessful private
Definition at line 42 of file ChaosDerivedDataReader.h.
ConvexGeometries
template<typename T, int d> UE_DEPRECATED (5.4, "Please use ConvexGeometries instead") TArray<TSharedPtr<Chaos UE_DEPRECATED (5.4, "Please use TrimeshGeometries instead") TArray<TSharedPtr<Chaos TArray<Chaos::FConvexPtr> FChaosDerivedDataReader< T, d >::ConvexGeometries
Definition at line 30 of file ChaosDerivedDataReader.h.
FaceRemap
template<typename T, int d> TArray<int32> FChaosDerivedDataReader< T, d >::FaceRemap
Definition at line 33 of file ChaosDerivedDataReader.h.
TriMeshGeometries
template<typename T, int d> TArray<Chaos::FTriangleMeshImplicitObjectPtr> FChaosDerivedDataReader< T, d >::TriMeshGeometries
Definition at line 31 of file ChaosDerivedDataReader.h.
UVInfo
template<typename T, int d> FBodySetupUVInfo FChaosDerivedDataReader< T, d >::UVInfo
Definition at line 32 of file ChaosDerivedDataReader.h.
The documentation for this class was generated from the following files:
BodySetup.h
ChaosDerivedDataReader.h