Unreal Engine 5.6 C++ API: Metasound::TAudioSender< TDataType > Class Template Reference
Metasound::TAudioSender< TDataType > Class Template Reference
#include "MetasoundRouter.h"
Public Member Functions
TAudioSender (const FSenderInitParams &InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, TArray< Audio::FPatchInput > &&Inputs)
int64 GetPayloadID () const override
bool Push (const TDataType &InElement)
bool PushLiteral (const FLiteral &InLiteral) override
bool SetDelay (float InSeconds)
Public Member Functions inherited from Metasound::ISender
ISender (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType)
virtual METASOUNDFRONTEND_API ~ISender ()
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Static Public Member Functions
static FName GetDataTypeName ()
Private Attributes
TArray< Audio::FPatchInput > DataChannelInputs
TArray< Audio::TCircularAudioBuffer< float > > DelayLines
uint32 DelayTimeInFrames
TArray< Audio::FAlignedFloatBuffer > IntermediaryBuffers
FSenderInitParams Params
Static Private Attributes
static constexpr float BufferResizeThreshold = 2.0f
static const int32 MaxChannels = 8
Additional Inherited Members
Protected Attributes inherited from Metasound::ISender
TSharedPtr< IDataChannel, ESPMode::ThreadSafe > DataChannel
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
template<typename TDataType>
class Metasound::TAudioSender< TDataType >
Definition at line 712 of file MetasoundRouter.h.
Constructor & Destructor Documentation
TAudioSender()
template<typename TDataType> Metasound::TAudioSender< TDataType >::TAudioSender (const FSenderInitParams & InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, TArray< Audio::FPatchInput > && Inputs) inline
Definition at line 782 of file MetasoundRouter.h.
References Metasound::ISender::ISender(), DataChannelInputs, Metasound::FSenderInitParams::DelayTimeInSeconds, GetDataTypeName(), MoveTemp(), Params, and SetDelay().
Member Function Documentation
GetDataTypeName()
template<typename TDataType> FName Metasound::TAudioSender< TDataType >::GetDataTypeName () inline static
Definition at line 777 of file MetasoundRouter.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by TAudioSender(), and Metasound::Downcast().
GetPayloadID()
template<typename TDataType> int64 Metasound::TAudioSender< TDataType >::GetPayloadID () const inline override virtual
Implements Metasound::ISender.
Definition at line 741 of file MetasoundRouter.h.
References INDEX_NONE.
Push()
template<typename TDataType> bool Metasound::TAudioSender< TDataType >::Push (const TDataType & InElement) inline
Definition at line 718 of file MetasoundRouter.h.
References check, DataChannelInputs, DelayLines, DelayTimeInFrames, Metasound::FAudioBuffer::GetData(), IntermediaryBuffers, IntermediateBuffer, MaxChannels, Metasound::FAudioBuffer::Num(), and Num.
PushLiteral()
template<typename TDataType> bool Metasound::TAudioSender< TDataType >::PushLiteral (const FLiteral & InLiteral) inline override virtual
Implements Metasound::ISender.
Definition at line 746 of file MetasoundRouter.h.
References ensureMsgf, and TEXT.
SetDelay()
template<typename TDataType> bool Metasound::TAudioSender< TDataType >::SetDelay (float InSeconds) inline
Definition at line 753 of file MetasoundRouter.h.
References BufferResizeThreshold, DelayLines, DelayTimeInFrames, IntermediaryBuffers, MaxChannels, FMath::Min, MoveTemp(), Num, and Params.
Referenced by TAudioSender().
Field Documentation
BufferResizeThreshold
template<typename TDataType> float Metasound::TAudioSender< TDataType >::BufferResizeThreshold = 2.0f static constexpr private
Definition at line 714 of file MetasoundRouter.h.
Referenced by SetDelay().
DataChannelInputs
template<typename TDataType> TArray<Audio::FPatchInput> Metasound::TAudioSender< TDataType >::DataChannelInputs private
Definition at line 796 of file MetasoundRouter.h.
Referenced by TAudioSender(), and Push().
DelayLines
template<typename TDataType> TArray<Audio::TCircularAudioBuffer<float> > Metasound::TAudioSender< TDataType >::DelayLines private
Definition at line 792 of file MetasoundRouter.h.
Referenced by Push(), and SetDelay().
DelayTimeInFrames
template<typename TDataType> uint32 Metasound::TAudioSender< TDataType >::DelayTimeInFrames private
Definition at line 794 of file MetasoundRouter.h.
Referenced by Push(), and SetDelay().
IntermediaryBuffers
template<typename TDataType> TArray<Audio::FAlignedFloatBuffer> Metasound::TAudioSender< TDataType >::IntermediaryBuffers private
Definition at line 798 of file MetasoundRouter.h.
Referenced by Push(), and SetDelay().
MaxChannels
template<typename TDataType> const int32 Metasound::TAudioSender< TDataType >::MaxChannels = 8 static private
Definition at line 715 of file MetasoundRouter.h.
Referenced by Push(), and SetDelay().
Params
template<typename TDataType> FSenderInitParams Metasound::TAudioSender< TDataType >::Params private
Definition at line 800 of file MetasoundRouter.h.
Referenced by TAudioSender(), and SetDelay().
The documentation for this class was generated from the following file:
MetasoundRouter.h