Unreal Engine 5.6 C++ API: SceneComponent.h File Reference
SceneComponent.h File Reference
#include "EngineDefines.h"
#include "UObject/ObjectMacros.h"
#include "Math/BoxSphereBounds.h"
#include "UObject/UObjectGlobals.h"
#include "ComponentInstanceDataCache.h"
#include "Components/ActorComponent.h"
#include "TransformStateStreamHandle.h"
#include "SceneComponent.generated.h"
Data Structures
struct FDirectAttachChildrenAccessor
Struct to allow direct access to the AttachChildren array for a handful of cases that will require more work than can be done
immediately to fix up in light of the privatization steps.
class FScopedPreventAttachedComponentMove
Component instance cached data base class for scene components.
class USceneComponent
Namespaces
namespace ERHIFeatureLevel
Macros
#define SCENECOMPONENT_QUAT_TOLERANCE (1.e-8f)
Comparison tolerance for checking if two FQuats are the same when moving SceneComponents.
#define SCENECOMPONENT_ROTATOR_TOLERANCE (1.e-4f)
Comparison tolerance for checking if two FRotators are the same when moving SceneComponents.
Typedefs
typedef TArrayView< const FOverlapInfo > TOverlapArrayView
Enumerations
enum EMoveComponentFlags {
MOVECOMP_NoFlags = 0x0000 , MOVECOMP_IgnoreBases = 0x0001 , MOVECOMP_SkipPhysicsMove = 0x0002 , MOVECOMP_NeverIgnoreBlockingOverlaps = 0x0004 ,
MOVECOMP_DisableBlockingOverlapDispatch = 0x0008 , MOVECOMP_CheckBlockingRootActorInIgnoreList = 0x0010
}
Detail mode for scene component rendering, corresponds with the integer value of UWorld::GetDetailMode()
Functions
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FPhysicsVolumeChanged, USceneComponent, PhysicsVolumeChangedDelegate, class APhysicsVolume *, NewVolume)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FIsRootComponentChanged, USceneComponent, IsRootComponentChanged, USceneComponent *, UpdatedComponent, bool, bIsRootComponent)
DECLARE_EVENT_ThreeParams (USceneComponent, FTransformUpdated, USceneComponent *, EUpdateTransformFlags, ETeleportType)
ENUM_CLASS_FLAGS (EMoveComponentFlags)
UCLASS ()
A SceneComponent has a transform and supports attachment, but has no rendering or collision capabilities.
Variables
BlueprintType
hideCategories =(Trigger, PhysicsVolume)
meta =(BlueprintSpawnableComponent, IgnoreCategoryKeywordsInSubclasses, ShortTooltip="A Scene Component is a component that has a scene transform and can be attached to other scene components.")
Macro Definition Documentation
SCENECOMPONENT_QUAT_TOLERANCE
#define SCENECOMPONENT_QUAT_TOLERANCE (1.e-8f)
Comparison tolerance for checking if two FQuats are the same when moving SceneComponents.
Definition at line 71 of file SceneComponent.h.
SCENECOMPONENT_ROTATOR_TOLERANCE
#define SCENECOMPONENT_ROTATOR_TOLERANCE (1.e-4f)
Comparison tolerance for checking if two FRotators are the same when moving SceneComponents.
Definition at line 73 of file SceneComponent.h.
Typedef Documentation
TOverlapArrayView
typedef TArrayView<const FOverlapInfo> TOverlapArrayView
Definition at line 23 of file SceneComponent.h.
Enumeration Type Documentation
EMoveComponentFlags
enum EMoveComponentFlags
Detail mode for scene component rendering, corresponds with the integer value of UWorld::GetDetailMode()
The space for the transform MoveComponent options, stored as bitflags
Enumerator
MOVECOMP_NoFlags
Default options.
MOVECOMP_IgnoreBases
Ignore collisions with things the Actor is based on.
MOVECOMP_SkipPhysicsMove
When moving this component, do not move the physics representation.
Used internally to avoid looping updates when syncing with physics.
MOVECOMP_NeverIgnoreBlockingOverlaps
Never ignore initial blocking overlaps during movement, which are usually ignored when moving out of an object.
MOVECOMP_IgnoreBases is still respected.
MOVECOMP_DisableBlockingOverlapDispatch
avoid dispatching blocking hit events when the hit started in penetration (and is not ignored, see MOVECOMP_NeverIgnoreBlockingOverlaps).
MOVECOMP_CheckBlockingRootActorInIgnoreList
Compare the root actor of a blocking hit with the ignore UPrimitiveComponent::MoveIgnoreActors array.
Definition at line 52 of file SceneComponent.h.
Function Documentation
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FPhysicsVolumeChanged , USceneComponent , PhysicsVolumeChangedDelegate , class APhysicsVolume * , NewVolume)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FIsRootComponentChanged , USceneComponent , IsRootComponentChanged , USceneComponent * , UpdatedComponent , bool , bIsRootComponent)
DECLARE_EVENT_ThreeParams()
DECLARE_EVENT_ThreeParams (USceneComponent , FTransformUpdated , USceneComponent * , EUpdateTransformFlags , ETeleportType)
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EMoveComponentFlags)
UCLASS()
UCLASS ()
A SceneComponent has a transform and supports attachment, but has no rendering or collision capabilities.
Useful as a 'dummy' component in the hierarchy to offset others.
See also
Scene Components
Variable Documentation
BlueprintType
BlueprintType
Definition at line 84 of file SceneComponent.h.
hideCategories
hideCategories =(Trigger, PhysicsVolume)
Definition at line 84 of file SceneComponent.h.
meta
meta =(BlueprintSpawnableComponent, IgnoreCategoryKeywordsInSubclasses, ShortTooltip="A Scene Component is a component that has a scene transform and can be attached to other scene components.")
Definition at line 84 of file SceneComponent.h.
Referenced by USceneComponent::SetShouldSnapScaleWhenAttached(), USceneComponent::UE_DEPRECATED(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UFUNCTION(), USceneComponent::UPROPERTY(), USceneComponent::UPROPERTY(), USceneComponent::UPROPERTY(), and USceneComponent::UPROPERTY().