Unreal Engine 5.6 C++ API: Metasound::Frontend::FClassInterfaceUpdates Struct Reference
Metasound::Frontend::FClassInterfaceUpdates Struct Reference
Provides list of interface members that have been added or removed when querying if a node's class has been updated.
#include "MetasoundFrontendController.h"
Public Member Functions
FClassInterfaceUpdates ()=default
bool ContainsAddedMembers () const
bool ContainsChanges () const
bool ContainsRemovedMembers () const
bool ContainsUpdatedNodeClassInterfaceOverride () const
bool ContainsUpdatedNodeConfig () const
Data Fields
TInstancedStruct< FMetasoundFrontendClassInterface > AddedClassInterfaceOverride
TInstancedStruct< FMetaSoundFrontendNodeConfiguration > AddedConfiguration
TArray< const FMetasoundFrontendClassInput * > AddedInputs
TArray< const FMetasoundFrontendClassOutput * > AddedOutputs
FMetasoundFrontendClass RegistryClass
TConstStructView< FMetasoundFrontendClassInterface > RemovedClassInterfaceOverride
TConstStructView< FMetaSoundFrontendNodeConfiguration > RemovedConfiguration
TArray< const FMetasoundFrontendClassInput * > RemovedInputs
TArray< const FMetasoundFrontendClassOutput * > RemovedOutputs
Detailed Description
Provides list of interface members that have been added or removed when querying if a node's class has been updated.
Definition at line 105 of file MetasoundFrontendController.h.
Constructor & Destructor Documentation
FClassInterfaceUpdates()
Metasound::Frontend::FClassInterfaceUpdates::FClassInterfaceUpdates () default
Member Function Documentation
ContainsAddedMembers()
bool Metasound::Frontend::FClassInterfaceUpdates::ContainsAddedMembers () const inline
Definition at line 122 of file MetasoundFrontendController.h.
References AddedInputs, and AddedOutputs.
Referenced by ContainsChanges().
ContainsChanges()
bool Metasound::Frontend::FClassInterfaceUpdates::ContainsChanges () const inline
Definition at line 137 of file MetasoundFrontendController.h.
References ContainsAddedMembers(), ContainsRemovedMembers(), ContainsUpdatedNodeClassInterfaceOverride(), and ContainsUpdatedNodeConfig().
ContainsRemovedMembers()
bool Metasound::Frontend::FClassInterfaceUpdates::ContainsRemovedMembers () const inline
Definition at line 117 of file MetasoundFrontendController.h.
References RemovedInputs, and RemovedOutputs.
Referenced by ContainsChanges().
ContainsUpdatedNodeClassInterfaceOverride()
bool Metasound::Frontend::FClassInterfaceUpdates::ContainsUpdatedNodeClassInterfaceOverride () const inline
Definition at line 132 of file MetasoundFrontendController.h.
References AddedClassInterfaceOverride, and RemovedClassInterfaceOverride.
Referenced by ContainsChanges().
ContainsUpdatedNodeConfig()
bool Metasound::Frontend::FClassInterfaceUpdates::ContainsUpdatedNodeConfig () const inline
Definition at line 127 of file MetasoundFrontendController.h.
References AddedConfiguration, and RemovedConfiguration.
Referenced by ContainsChanges().
Field Documentation
AddedClassInterfaceOverride
TInstancedStruct<FMetasoundFrontendClassInterface> Metasound::Frontend::FClassInterfaceUpdates::AddedClassInterfaceOverride
Definition at line 114 of file MetasoundFrontendController.h.
Referenced by ContainsUpdatedNodeClassInterfaceOverride().
AddedConfiguration
TInstancedStruct<FMetaSoundFrontendNodeConfiguration> Metasound::Frontend::FClassInterfaceUpdates::AddedConfiguration
Definition at line 112 of file MetasoundFrontendController.h.
Referenced by ContainsUpdatedNodeConfig().
AddedInputs
TArray<const FMetasoundFrontendClassInput*> Metasound::Frontend::FClassInterfaceUpdates::AddedInputs
Definition at line 108 of file MetasoundFrontendController.h.
Referenced by ContainsAddedMembers().
AddedOutputs
TArray<const FMetasoundFrontendClassOutput*> Metasound::Frontend::FClassInterfaceUpdates::AddedOutputs
Definition at line 109 of file MetasoundFrontendController.h.
Referenced by ContainsAddedMembers().
RegistryClass
FMetasoundFrontendClass Metasound::Frontend::FClassInterfaceUpdates::RegistryClass
Definition at line 143 of file MetasoundFrontendController.h.
RemovedClassInterfaceOverride
TConstStructView<FMetasoundFrontendClassInterface> Metasound::Frontend::FClassInterfaceUpdates::RemovedClassInterfaceOverride
Definition at line 115 of file MetasoundFrontendController.h.
Referenced by ContainsUpdatedNodeClassInterfaceOverride().
RemovedConfiguration
TConstStructView<FMetaSoundFrontendNodeConfiguration> Metasound::Frontend::FClassInterfaceUpdates::RemovedConfiguration
Definition at line 113 of file MetasoundFrontendController.h.
Referenced by ContainsUpdatedNodeConfig().
RemovedInputs
TArray<const FMetasoundFrontendClassInput*> Metasound::Frontend::FClassInterfaceUpdates::RemovedInputs
Definition at line 110 of file MetasoundFrontendController.h.
Referenced by ContainsRemovedMembers().
RemovedOutputs
TArray<const FMetasoundFrontendClassOutput*> Metasound::Frontend::FClassInterfaceUpdates::RemovedOutputs
Definition at line 111 of file MetasoundFrontendController.h.
Referenced by ContainsRemovedMembers().
The documentation for this struct was generated from the following file:
MetasoundFrontendController.h