Unreal Engine 5.6 C++ API: FPlatformFileManager Class Reference
FPlatformFileManager Class Reference
Platform File chain manager.
#include "PlatformFileManager.h"
Public Member Functions
FPlatformFileManager ()
Constructor.
IPlatformFile * FindPlatformFile (const TCHAR *Name)
Finds a platform file in the chain of active platform files.
IPlatformFile & GetPlatformFile ()
Gets the currently used platform file.
IPlatformFile * GetPlatformFile (const TCHAR *Name)
Creates a new platform file instance.
IPlatformFile & GetPlatformPhysical ()
void InitializeNewAsyncIO ()
Performs additional initialization when the new async IO is enabled.
bool InsertPlatformFile (IPlatformFile *NewPlatformFile)
Inserts a new platform file into the platform file wrapper chain.
void RemovePlatformFile (IPlatformFile *PlatformFileToRemove)
Removes the specified file wrapper from the platform file wrapper chain.
void SetPlatformFile (IPlatformFile &NewTopmostPlatformFile)
Sets the current platform file.
void SetPlatformPhysical (IPlatformFile &NewPhysicalPlatformFile)
void TickActivePlatformFile ()
calls Tick on the platform files in the TopmostPlatformFile chain
Static Public Member Functions
static FPlatformFileManager & Get ()
Gets FPlatformFileManager Singleton.
Private Attributes
TAtomic< class IPlatformFile * > PhysicalPlatformFile
TAtomic< class IPlatformFile * > TopmostPlatformFile
Currently used platform file.
Detailed Description
Platform File chain manager.
Definition at line 16 of file PlatformFileManager.h.
Constructor & Destructor Documentation
FPlatformFileManager()
FPlatformFileManager::FPlatformFileManager ()
Constructor.
Referenced by Get().
Member Function Documentation
FindPlatformFile()
IPlatformFile * FPlatformFileManager::FindPlatformFile (const TCHAR * Name)
Finds a platform file in the chain of active platform files.
Parameters
Name of the platform file.
Returns
Pointer to the active platform file or nullptr if the platform file was not found.
References Name.
Get()
FPlatformFileManager & FPlatformFileManager::Get () static
Gets FPlatformFileManager Singleton.
References FPlatformFileManager().
Referenced by FFileManagerGeneric::GetLowLevel().
GetPlatformFile() [1/2]
IPlatformFile & FPlatformFileManager::GetPlatformFile ()
Gets the currently used platform file.
Returns
Reference to the currently used platform file.
Referenced by FFileManagerGeneric::GetLowLevel().
GetPlatformFile() [2/2]
IPlatformFile * FPlatformFileManager::GetPlatformFile (const TCHAR * Name)
Creates a new platform file instance.
Parameters
Name of the platform file to create.
Returns
Platform file instance of the platform file type was found, nullptr otherwise.
References Name.
GetPlatformPhysical()
IPlatformFile & FPlatformFileManager::GetPlatformPhysical ()
InitializeNewAsyncIO()
void FPlatformFileManager::InitializeNewAsyncIO ()
Performs additional initialization when the new async IO is enabled.
InsertPlatformFile()
bool FPlatformFileManager::InsertPlatformFile (IPlatformFile * NewPlatformFile)
Inserts a new platform file into the platform file wrapper chain.
The file is inserted before NewPlatformFile->GetLowerLevel().
THIS IS EXTREMELY DANGEROUS AFTER THE ENGINE HAS BEEN INITIALIZED AS WE MAY BE MODIFYING THE WRAPPER CHAIN WHILE THINGS ARE BEING LOADED
Parameters
The platform file to insert.
Returns
true if the platform file was inserted.
RemovePlatformFile()
void FPlatformFileManager::RemovePlatformFile (IPlatformFile * PlatformFileToRemove)
Removes the specified file wrapper from the platform file wrapper chain.
THIS IS EXTREMELY DANGEROUS AFTER THE ENGINE HAS BEEN INITIALIZED AS WE MAY BE MODIFYING THE WRAPPER CHAIN WHILE THINGS ARE BEING LOADED
Parameters
The platform file to remove.
SetPlatformFile()
void FPlatformFileManager::SetPlatformFile (IPlatformFile & NewTopmostPlatformFile)
Sets the current platform file.
Parameters
NewTopmostPlatformFile Platform file to be used.
SetPlatformPhysical()
void FPlatformFileManager::SetPlatformPhysical (IPlatformFile & NewPhysicalPlatformFile)
TickActivePlatformFile()
void FPlatformFileManager::TickActivePlatformFile ()
calls Tick on the platform files in the TopmostPlatformFile chain
Field Documentation
PhysicalPlatformFile
TAtomic<class IPlatformFile*> FPlatformFileManager::PhysicalPlatformFile private
Definition at line 21 of file PlatformFileManager.h.
TopmostPlatformFile
TAtomic<class IPlatformFile*> FPlatformFileManager::TopmostPlatformFile private
Currently used platform file.
Definition at line 20 of file PlatformFileManager.h.
The documentation for this class was generated from the following file:
PlatformFileManager.h