Unreal Engine 5.6 C++ API: UE::MovieScene::FErasedOptionalReadAccess Struct Reference
UE::MovieScene::FErasedOptionalReadAccess Struct Reference
#include "MovieSceneComponentAccessors.h"
Public Member Functions
FErasedOptionalReadAccess (FComponentTypeID InComponentTypeID, FComponentTypeIDFilter InCondition)
FORCEINLINE FOptionalComponentReader LockComponentData (FEntityAllocationIteratorItem Item, FEntityAllocationWriteContext WriteContext) const
FORCEINLINE void PreLockComponentData (FEntityAllocationIteratorItem Item, FPreLockedDataPtr *PrelockedComponentData) const
FORCEINLINE FReadErasedOptional ResolvePreLockedComponentData (const FEntityAllocation *Allocation, const FPreLockedDataPtr *Ptr, FEntityAllocationWriteContext WriteContext) const
Public Member Functions inherited from UE::MovieScene::FReadAccess
FReadAccess (FComponentTypeID InComponentType)
Public Member Functions inherited from UE::MovieScene::FComponentAccess
FORCEINLINE void PreLockComponentData (const FEntityAllocation *Allocation, FPreLockedDataPtr *PrelockedComponentData) const
Data Fields
FComponentTypeIDFilter Condition
Data Fields inherited from UE::MovieScene::FComponentAccess
FComponentTypeID ComponentType
Static Public Attributes
static constexpr int32 PreLockedDataNum = 1
Detailed Description
Definition at line 186 of file MovieSceneComponentAccessors.h.
Constructor & Destructor Documentation
FErasedOptionalReadAccess()
UE::MovieScene::FErasedOptionalReadAccess::FErasedOptionalReadAccess (FComponentTypeID InComponentTypeID, FComponentTypeIDFilter InCondition) inline
Definition at line 192 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FReadAccess::FReadAccess(), and Condition.
Member Function Documentation
LockComponentData()
FORCEINLINE FOptionalComponentReader UE::MovieScene::FErasedOptionalReadAccess::LockComponentData (FEntityAllocationIteratorItem Item, FEntityAllocationWriteContext WriteContext) const inline
Definition at line 217 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FComponentAccess::ComponentType, Condition, FORCEINLINE, and Item.
PreLockComponentData()
FORCEINLINE void UE::MovieScene::FErasedOptionalReadAccess::PreLockComponentData (FEntityAllocationIteratorItem Item, FPreLockedDataPtr * PrelockedComponentData) const inline
Definition at line 197 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FComponentAccess::ComponentType, Condition, FORCEINLINE, Header, Item, and TRelativePtr< T, OffsetType >::Reset().
ResolvePreLockedComponentData()
FORCEINLINE FReadErasedOptional UE::MovieScene::FErasedOptionalReadAccess::ResolvePreLockedComponentData (const FEntityAllocation * Allocation, const FPreLockedDataPtr * Ptr, FEntityAllocationWriteContext WriteContext) const inline
Definition at line 212 of file MovieSceneComponentAccessors.h.
References FORCEINLINE, and TRelativePtr< T, OffsetType >::Resolve().
Field Documentation
Condition
FComponentTypeIDFilter UE::MovieScene::FErasedOptionalReadAccess::Condition
Definition at line 190 of file MovieSceneComponentAccessors.h.
Referenced by FErasedOptionalReadAccess(), LockComponentData(), and PreLockComponentData().
PreLockedDataNum
int32 UE::MovieScene::FErasedOptionalReadAccess::PreLockedDataNum = 1 static constexpr
Definition at line 188 of file MovieSceneComponentAccessors.h.
The documentation for this struct was generated from the following file:
MovieSceneComponentAccessors.h