Unreal Engine 5.6 C++ API: EdGraphNode.h File Reference
EdGraphNode.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Misc/Guid.h"
#include "UObject/WeakObjectPtr.h"
#include "Types/SlateVector2.h"
#include "EdGraphNode.generated.h"
Data Structures
struct FEdGraphNodeDeprecationResponse
Deprecation response data.
struct FNodeMetadata
Holds metadata keys, so as to discourage text duplication throughout the engine.
struct FSetAsIntermediateNode
Enumerations
enum class EEdGraphNodeDeprecationMessageType { None , Note , Warning }
Deprecation response message types.
enum class EEdGraphNodeDeprecationType { NodeTypeIsDeprecated , NodeHasDeprecatedReference }
This is the context for GetContextMenuActions and GetNodeContextMenuActions calls.
enum class EGetFindReferenceSearchStringFlags : int8 { None = 0 , Legacy = 1 << 0 , UseSearchSyntax = 1 << 1 }
Options when getting a Find References search string from a node.
enum class ESaveOrphanPinMode : uint8 { SaveNone , SaveAll , SaveAllButExec }
Enum that defines what kind of orphaned pins should be retained.
Functions
ENUM_CLASS_FLAGS (EGetFindReferenceSearchStringFlags)
UENUM() enum EEdGraphPinDirection const TCHAR *const LexToString (const EEdGraphPinDirection State)
Enum used to define which way data flows into or out of this pin.
UENUM() enum class ENodeEnabledState const TCHAR *const LexToString (const ENodeEnabledState State)
Enum to indicate a node's enabled state.
UENUM() enum class EPinContainerType UENUM () namespace ENodeTitleType
Enum used to define what container type a pin represents.
USTRUCT () struct FEdGraphTerminalType
Struct used to define information for terminal types, e.g.
Enumeration Type Documentation
EEdGraphNodeDeprecationMessageType
enum class EEdGraphNodeDeprecationMessageType strong
Deprecation response message types.
Enumerator
None
No message.
The Blueprint will compile successfully.
Note
Emit the message as a note at compile time.
This will appear as a note on the node and in the compiler log.
Warning
Emit the message as a Blueprint compiler warning.
This will appear as a warning on the node and in the compiler log.
Definition at line 254 of file EdGraphNode.h.
EEdGraphNodeDeprecationType
enum class EEdGraphNodeDeprecationType strong
This is the context for GetContextMenuActions and GetNodeContextMenuActions calls.
Deprecation types for node response.
Enumerator
NodeTypeIsDeprecated
The node type is deprecated.
NodeHasDeprecatedReference
The node references a deprecated member or type (e.g.
variable or function).
Definition at line 245 of file EdGraphNode.h.
EGetFindReferenceSearchStringFlags
enum class EGetFindReferenceSearchStringFlags : int8 strong
Options when getting a Find References search string from a node.
Enumerator
None
No options.
Legacy
Use search behavior from before there were different Find References options.
UseSearchSyntax
Use search syntax to do exact search.
Definition at line 275 of file EdGraphNode.h.
ESaveOrphanPinMode
enum class ESaveOrphanPinMode : uint8 strong
Enum that defines what kind of orphaned pins should be retained.
Enumerator
SaveNone
SaveAll
SaveAllButExec
Definition at line 196 of file EdGraphNode.h.
Function Documentation
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EGetFindReferenceSearchStringFlags)
References MinimalAPI, Pins, Transient, and UPROPERTY.
LexToString() [1/2]
UENUM() enum EEdGraphPinDirection const TCHAR *const LexToString (const EEdGraphPinDirection State) inline
Enum used to define which way data flows into or out of this pin.
Definition at line 104 of file EdGraphNode.h.
References checkf, State, and TEXT.
LexToString() [2/2]
UENUM() enum class ENodeEnabledState const TCHAR *const LexToString (const ENodeEnabledState State) inline
Enum to indicate a node's enabled state.
Definition at line 177 of file EdGraphNode.h.
References checkf, State, and TEXT.
UENUM()
UENUM() enum class EPinContainerType UENUM ()
Enum used to define what container type a pin represents.
Enum to indicate if a node has advanced-display-pins, and whether they are shown.
Enum to indicate what sort of title we want.
The full title, may be multiple lines.
More concise, single line title.
Returns the editable title (which might not be a title at all).
Menu Title for context menus to be displayed in context menus referencing the node.
No advanced pins.
There are some advanced pins, and they are shown.
There are some advanced pins, and they are hidden.
Definition at line 132 of file EdGraphNode.h.
USTRUCT()
USTRUCT ()
Struct used to define information for terminal types, e.g.
types that can be contained by a container. Currently can represent strong/weak references to a type (only UObjects), a structure, or a primitive. Support for "Container of Containers" is done by wrapping a structure, rather than implicitly defining names for containers.
Category
Sub-category
Sub-category object
Whether or not this pin is a immutable const value
Whether or not this is a weak reference
Whether or not this is a "wrapped" Unreal object ptr type (e.g. TSubclassOf<T> instead of UClass*)
Creates a TerminalType from the primary portion of the PinType
Definition at line 36 of file EdGraphNode.h.
References A, Ar, B, GENERATED_USTRUCT_BODY, operator!=(), operator<<(), operator==(), and UPROPERTY.