Unreal Engine 5.6 C++ API: Metasound::FDataEdge Struct Reference
Metasound::FDataEdge Struct Reference
FDataEdge.
#include "MetasoundNodeInterface.h"
Public Member Functions
FDataEdge ()
FDataEdge (const FOutputDataSource &InFrom, const FInputDataDestination &InTo)
Data Fields
FOutputDataSource From
FInputDataDestination To
Friends
bool METASOUNDGRAPHCORE_API operator!= (const FDataEdge &InLeft, const FDataEdge &InRight)
bool METASOUNDGRAPHCORE_API operator< (const FDataEdge &InLeft, const FDataEdge &InRight)
bool METASOUNDGRAPHCORE_API operator== (const FDataEdge &InLeft, const FDataEdge &InRight)
Check if two FDataEdges are equal.
Detailed Description
FDataEdge.
An edge describes a connection between two Nodes.
Definition at line 334 of file MetasoundNodeInterface.h.
Constructor & Destructor Documentation
FDataEdge() [1/2]
Metasound::FDataEdge::FDataEdge () inline
Definition at line 340 of file MetasoundNodeInterface.h.
Referenced by operator!=, operator<, and operator==.
FDataEdge() [2/2]
Metasound::FDataEdge::FDataEdge (const FOutputDataSource & InFrom, const FInputDataDestination & InTo) inline
Definition at line 344 of file MetasoundNodeInterface.h.
References From, and To.
Friends And Related Symbol Documentation
operator!=
bool METASOUNDGRAPHCORE_API operator!= (const FDataEdge & InLeft, const FDataEdge & InRight) friend
References FDataEdge().
operator<
bool METASOUNDGRAPHCORE_API operator< (const FDataEdge & InLeft, const FDataEdge & InRight) friend
References FDataEdge().
operator==
bool METASOUNDGRAPHCORE_API operator== (const FDataEdge & InLeft, const FDataEdge & InRight) friend
Check if two FDataEdges are equal.
References FDataEdge().
Field Documentation
From
FOutputDataSource Metasound::FDataEdge::From
Definition at line 336 of file MetasoundNodeInterface.h.
Referenced by FDataEdge().
To
FInputDataDestination Metasound::FDataEdge::To
Definition at line 338 of file MetasoundNodeInterface.h.
Referenced by FDataEdge().
The documentation for this struct was generated from the following file:
MetasoundNodeInterface.h