Unreal Engine 5.6 C++ API: FProgressCancel::FProgressData Struct Reference
FProgressCancel::FProgressData Struct Reference
Public Member Functions
float Range () const
float SafeAdvance (float CurrentFraction, float AdvanceAmount) const
Data Fields
float CurrentMax = 1
float CurrentMin = 0
FText Message
int ScopeDepth = 0
Detailed Description
Definition at line 192 of file ProgressCancel.h.
Member Function Documentation
Range()
float FProgressCancel::FProgressData::Range () const inline
Definition at line 202 of file ProgressCancel.h.
References CurrentMax, and CurrentMin.
Referenced by SafeAdvance().
SafeAdvance()
float FProgressCancel::FProgressData::SafeAdvance (float CurrentFraction, float AdvanceAmount) const inline
Definition at line 208 of file ProgressCancel.h.
References CurrentMax, TMathUtil< float >::Min(), and Range().
Field Documentation
CurrentMax
float FProgressCancel::FProgressData::CurrentMax = 1
Definition at line 196 of file ProgressCancel.h.
Referenced by Range(), and SafeAdvance().
CurrentMin
float FProgressCancel::FProgressData::CurrentMin = 0
Definition at line 195 of file ProgressCancel.h.
Referenced by Range().
Message
FText FProgressCancel::FProgressData::Message
Definition at line 200 of file ProgressCancel.h.
ScopeDepth
int FProgressCancel::FProgressData::ScopeDepth = 0
Definition at line 198 of file ProgressCancel.h.
The documentation for this struct was generated from the following file:
ProgressCancel.h