Unreal Engine 5.6 C++ API: FDisplayClusterRender_StaticMeshComponentRef Class Reference
FDisplayClusterRender_StaticMeshComponentRef Class Reference
#include "DisplayClusterRender_StaticMeshComponentRef.h"
Public Member Functions
FDisplayClusterRender_StaticMeshComponentRef ()
FDisplayClusterRender_StaticMeshComponentRef (const FDisplayClusterRender_StaticMeshComponentRef &In)
UStaticMeshComponent * GetOrFindStaticMeshComponent () const
bool IsStaticMeshGeometryDirty () const
void MarkStaticMeshGeometryDirty () const
void ResetStaticMeshComponentRef ()
void ResetStaticMeshGeometryDirty () const
bool SetStaticMeshComponentRef (UStaticMeshComponent *InStaticMeshComponent)
Public Member Functions inherited from FDisplayClusterSceneComponentRef
FDisplayClusterSceneComponentRef ()
FDisplayClusterSceneComponentRef (const FDisplayClusterSceneComponentRef &InComponentRef)
FDisplayClusterSceneComponentRef (USceneComponent *InComponent)
USceneComponent * GetOrFindSceneComponent () const
bool IsDefinedSceneComponent () const
bool IsEqualsComponentName (const FName &InComponentName) const
bool IsSceneComponentValid () const
void ResetSceneComponent ()
bool SetSceneComponent (USceneComponent *const InComponent)
Public Member Functions inherited from FDisplayClusterActorRef
FDisplayClusterActorRef ()
FDisplayClusterActorRef (const FDisplayClusterActorRef &InActorRef)
virtual ~FDisplayClusterActorRef ()
AActor * GetOrFindSceneActor () const
const TWeakObjectPtr< AActor > GetSceneActorWeakPtr () const
Returns the current weak ptr of the scene actor object.
bool IsDefinedSceneActor () const
void ResetSceneActor ()
bool SetSceneActor (const AActor *InActor)
Private Attributes
bool bIsStaticMeshGeometryDirty = false
FName MeshGeometryName
Additional Inherited Members
Protected Attributes inherited from FDisplayClusterActorRef
FCriticalSection DataGuard
Detailed Description
Definition at line 11 of file DisplayClusterRender_StaticMeshComponentRef.h.
Constructor & Destructor Documentation
FDisplayClusterRender_StaticMeshComponentRef() [1/2]
FDisplayClusterRender_StaticMeshComponentRef::FDisplayClusterRender_StaticMeshComponentRef () inline
Definition at line 15 of file DisplayClusterRender_StaticMeshComponentRef.h.
References FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef().
Referenced by FDisplayClusterRender_StaticMeshComponentRef().
FDisplayClusterRender_StaticMeshComponentRef() [2/2]
FDisplayClusterRender_StaticMeshComponentRef::FDisplayClusterRender_StaticMeshComponentRef (const FDisplayClusterRender_StaticMeshComponentRef & In) inline
Definition at line 19 of file DisplayClusterRender_StaticMeshComponentRef.h.
References FDisplayClusterRender_StaticMeshComponentRef(), FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef(), bIsStaticMeshGeometryDirty, and MeshGeometryName.
Member Function Documentation
GetOrFindStaticMeshComponent()
UStaticMeshComponent * FDisplayClusterRender_StaticMeshComponentRef::GetOrFindStaticMeshComponent () const
IsStaticMeshGeometryDirty()
bool FDisplayClusterRender_StaticMeshComponentRef::IsStaticMeshGeometryDirty () const
MarkStaticMeshGeometryDirty()
void FDisplayClusterRender_StaticMeshComponentRef::MarkStaticMeshGeometryDirty () const
ResetStaticMeshComponentRef()
void FDisplayClusterRender_StaticMeshComponentRef::ResetStaticMeshComponentRef ()
ResetStaticMeshGeometryDirty()
void FDisplayClusterRender_StaticMeshComponentRef::ResetStaticMeshGeometryDirty () const
SetStaticMeshComponentRef()
bool FDisplayClusterRender_StaticMeshComponentRef::SetStaticMeshComponentRef (UStaticMeshComponent * InStaticMeshComponent)
Field Documentation
bIsStaticMeshGeometryDirty
bool FDisplayClusterRender_StaticMeshComponentRef::bIsStaticMeshGeometryDirty = false mutable private
Definition at line 36 of file DisplayClusterRender_StaticMeshComponentRef.h.
Referenced by FDisplayClusterRender_StaticMeshComponentRef().
MeshGeometryName
FName FDisplayClusterRender_StaticMeshComponentRef::MeshGeometryName private
Definition at line 38 of file DisplayClusterRender_StaticMeshComponentRef.h.
Referenced by FDisplayClusterRender_StaticMeshComponentRef().
The documentation for this class was generated from the following file:
DisplayClusterRender_StaticMeshComponentRef.h