Unreal Engine 5.6 C++ API: UParticleModuleCameraOffset Class Reference
UParticleModuleCameraOffset Class Reference
#include "ParticleModuleCameraOffset.h"
Private Member Functions
virtual bool CanTickInAnyThread () override
GENERATED_UCLASS_BODY () UPROPERTY() struct FRawDistributionFloat CameraOffset
The camera-relative offset to apply to sprite location.
void InitializeDefaults ()
Initializes the default values for this property.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual uint32 RequiredBytes (UParticleModuleTypeDataBase *TypeData) override
virtual void Spawn (const FSpawnContext &Context) override
virtual void Update (const FUpdateContext &Context) override
UPROPERTY() uint32 bSpawnTimeOnly UPROPERTY () TEnumAsByte< enum EParticleCameraOffsetUpdateMethod > UpdateMethod
If true, the offset will only be processed at spawn time.
Detailed Description
Definition at line 28 of file ParticleModuleCameraOffset.h.
Member Function Documentation
CanTickInAnyThread()
virtual bool UParticleModuleCameraOffset::CanTickInAnyThread () override private virtual
GENERATED_UCLASS_BODY()
UParticleModuleCameraOffset::GENERATED_UCLASS_BODY () private
The camera-relative offset to apply to sprite location.
References Camera, Category, and UPROPERTY().
InitializeDefaults()
void UParticleModuleCameraOffset::InitializeDefaults () private
Initializes the default values for this property.
References InitializeDefaults().
Referenced by InitializeDefaults().
PostEditChangeProperty()
virtual void UParticleModuleCameraOffset::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostInitProperties()
virtual void UParticleModuleCameraOffset::PostInitProperties () override private virtual
RequiredBytes()
virtual uint32 UParticleModuleCameraOffset::RequiredBytes (UParticleModuleTypeDataBase * TypeData) override private virtual
Spawn()
virtual void UParticleModuleCameraOffset::Spawn (const FSpawnContext & Context) override private virtual
Update()
virtual void UParticleModuleCameraOffset::Update (const FUpdateContext & Context) override private virtual
UPROPERTY()
UPROPERTY() uint32 bSpawnTimeOnly UParticleModuleCameraOffset::UPROPERTY () private
If true, the offset will only be processed at spawn time.
How to update the offset for this module. DirectSet - Set the value directly (overwrite any previous setting) Additive - Add the offset of this module to the existing offset Scalar - Scale the existing offset by the value of this module
References Camera, Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), and UPROPERTY().
The documentation for this class was generated from the following file:
ParticleModuleCameraOffset.h