Unreal Engine 5.6 C++ API: FConnectionDrawingPolicy Class Reference
FConnectionDrawingPolicy Class Reference
#include "ConnectionDrawingPolicy.h"
Data Structures
struct FRelinkConnection
Handle for a currently relinked connection.
Public Member Functions
FConnectionDrawingPolicy (int32 InBackLayerID, int32 InFrontLayerID, float InZoomFactor, const FSlateRect &InClippingRect, FSlateWindowElementList &InDrawElements)
virtual ~FConnectionDrawingPolicy ()
virtual void ApplyHoverDeemphasis (UEdGraphPin *OutputPin, UEdGraphPin *InputPin, float &Thickness, FLinearColor &WireColor)
virtual FVector2f ComputeSplineTangent (const FVector2f &Start, const FVector2f &End) const
virtual void DetermineLinkGeometry (FArrangedChildren &ArrangedNodes, TSharedRef< SWidget > &OutputPinWidget, UEdGraphPin *OutputPin, UEdGraphPin *InputPin, FArrangedWidget *&StartWidgetGeometry, FArrangedWidget *&EndWidgetGeometry)
virtual void DetermineWiringStyle (UEdGraphPin *OutputPin, UEdGraphPin *InputPin, FConnectionParams &Params)
virtual void Draw (TMap< TSharedRef< SWidget >, FArrangedWidget > &InPinGeometries, FArrangedChildren &ArrangedNodes)
virtual void DrawConnection (int32 LayerId, const FVector2f &Start, const FVector2f &End, const FConnectionParams &Params)
virtual void DrawPreviewConnector (const FGeometry &PinGeometry, const FVector2f &StartPoint, const FVector2f &EndPoint, UEdGraphPin *Pin)
virtual void DrawSplineWithArrow (const FGeometry &StartGeom, const FGeometry &EndGeom, const FConnectionParams &Params)
virtual void DrawSplineWithArrow (const FVector2f &StartPoint, const FVector2f &EndPoint, const FConnectionParams &Params)
virtual TSharedPtr< IToolTip > GetConnectionToolTip (const SGraphPanel &GraphPanel, const FGraphSplineOverlapResult &OverlapData) const
virtual bool IsConnectionCulled (const FArrangedWidget &StartLink, const FArrangedWidget &EndLink) const
virtual void ResetIncompatiblePinDrawState (const TSet< TSharedRef< SWidget > > &VisiblePins)
void SetHoveredPins (const TSet< FEdGraphPinReference > &InHoveredPins, const TArray< TSharedPtr< SGraphPin > > &OverridePins, double HoverTime)
virtual void SetIncompatiblePinDrawState (const TSharedPtr< SGraphPin > &StartPin, const TSet< TSharedRef< SWidget > > &VisiblePins)
void SetMarkedPin (TWeakPtr< SGraphPin > InMarkedPin)
void SetMousePosition (const UE::Slate::FDeprecateVector2DParameter &InMousePos)
void SetRelinkConnections (const TArray< FRelinkConnection > &Connections)
void SetSelectedNodes (const TArray< UEdGraphNode * > &InSelectedNodes)
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FVector2D ComputeSplineTangent(const FVector2D &Start
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual void DrawConnection(int32 LayerId
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual void DrawPreviewConnector(const FGeometry &PinGeometry
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual void DrawSplineWithArrow(const FVector2D &StartPoint
virtual bool UseDrawStateCaching () const
Static Public Member Functions
static float MakeSplineReparamTable (const UE::Slate::FDeprecateVector2DParameter &P0, const UE::Slate::FDeprecateVector2DParameter &P0Tangent, const UE::Slate::FDeprecateVector2DParameter &P1, const UE::Slate::FDeprecateVector2DParameter &P1Tangent, FInterpCurve< float > &OutReparamTable)
Data Fields
FDeprecateSlateVector2D ArrowRadius
const FVector2D &End const
const FVector2D const FVector2D & End
const FVector2D & EndPoint
const FVector2D const FVector2D & EndPoint
FDeprecateSlateVector2D MidpointRadius
const FVector2D const FConnectionParams & Params
const FVector2D const FVector2D const FConnectionParams & Params
const FVector2D const FVector2D UEdGraphPin * Pin
FGraphSplineOverlapResult SplineOverlapResult
const FVector2D & Start
const FVector2D & StartPoint
Protected Member Functions
virtual void BuildPinToPinWidgetMap (TMap< TSharedRef< SWidget >, FArrangedWidget > &InPinGeometries)
virtual void DrawPinGeometries (TMap< TSharedRef< SWidget >, FArrangedWidget > &InPinGeometries, FArrangedChildren &ArrangedNodes)
Protected Attributes
const FSlateBrush * ArrowImage
int32 ArrowLayerID
const FSlateBrush * BubbleImage
const FSlateRect & ClippingRect
FSlateWindowElementList & DrawElementsList
float HoverDeemphasisDarkFraction
TSet< FEdGraphPinReference > HoveredPins
double LastHoverTimeEvent
FDeprecateSlateVector2D LocalMousePosition
const FSlateBrush * MidpointImage
TMap< TSharedRef< SWidget >, FArrangedWidget > * PinGeometries
TMap< UEdGraphPin *, TSharedPtr< SGraphPin > > PinToPinWidgetMap
TArray< FRelinkConnection > RelinkConnections
List of currently relinked connections.
TArray< UEdGraphNode * > SelectedGraphNodes
Selected nodes in the graph panel.
const UGraphEditorSettings * Settings
int32 WireLayerID
float ZoomFactor
Private Member Functions
UE::Slate::FDeprecateVector2DResult ComputeSplineTangent_DeprecationHelper (const UE::Slate::FDeprecateVector2DParameter &Start, const UE::Slate::FDeprecateVector2DParameter &End) const
void DrawConnection_DeprecationHelper (int32 LayerId, const UE::Slate::FDeprecateVector2DParameter &Start, const UE::Slate::FDeprecateVector2DParameter &End, const FConnectionParams &Params)
void DrawPreviewConnector_DeprecationHelper (const FGeometry &PinGeometry, const UE::Slate::FDeprecateVector2DParameter &StartPoint, const UE::Slate::FDeprecateVector2DParameter &EndPoint, UEdGraphPin *Pin)
void DrawSplineWithArrow_DeprecationHelper (const UE::Slate::FDeprecateVector2DParameter &StartPoint, const UE::Slate::FDeprecateVector2DParameter &EndPoint, const FConnectionParams &Params)
Detailed Description
Definition at line 99 of file ConnectionDrawingPolicy.h.
Constructor & Destructor Documentation
~FConnectionDrawingPolicy()
virtual FConnectionDrawingPolicy::~FConnectionDrawingPolicy () inline virtual
Definition at line 141 of file ConnectionDrawingPolicy.h.
FConnectionDrawingPolicy()
FConnectionDrawingPolicy::FConnectionDrawingPolicy (int32 InBackLayerID, int32 InFrontLayerID, float InZoomFactor, const FSlateRect & InClippingRect, FSlateWindowElementList & InDrawElements)
Member Function Documentation
ApplyHoverDeemphasis()
virtual void FConnectionDrawingPolicy::ApplyHoverDeemphasis (UEdGraphPin * OutputPin, UEdGraphPin * InputPin, float & Thickness, FLinearColor & WireColor) virtual
BuildPinToPinWidgetMap()
virtual void FConnectionDrawingPolicy::BuildPinToPinWidgetMap (TMap< TSharedRef< SWidget >, FArrangedWidget > & InPinGeometries) protected virtual
Reimplemented in FRigVMEdGraphConnectionDrawingPolicy.
ComputeSplineTangent()
virtual FVector2f FConnectionDrawingPolicy::ComputeSplineTangent (const FVector2f & Start, const FVector2f & End) const virtual
References ComputeSplineTangent(), const, End, and Start.
Referenced by ComputeSplineTangent().
ComputeSplineTangent_DeprecationHelper()
UE::Slate::FDeprecateVector2DResult FConnectionDrawingPolicy::ComputeSplineTangent_DeprecationHelper (const UE::Slate::FDeprecateVector2DParameter & Start, const UE::Slate::FDeprecateVector2DParameter & End) const private
References End, and Start.
DetermineLinkGeometry()
virtual void FConnectionDrawingPolicy::DetermineLinkGeometry (FArrangedChildren & ArrangedNodes, TSharedRef< SWidget > & OutputPinWidget, UEdGraphPin * OutputPin, UEdGraphPin * InputPin, FArrangedWidget *& StartWidgetGeometry, FArrangedWidget *& EndWidgetGeometry) virtual
Reimplemented in FRigVMEdGraphConnectionDrawingPolicy.
References DetermineLinkGeometry().
Referenced by DetermineLinkGeometry().
DetermineWiringStyle()
virtual void FConnectionDrawingPolicy::DetermineWiringStyle (UEdGraphPin * OutputPin, UEdGraphPin * InputPin, FConnectionParams & Params) virtual
Reimplemented in FDataflowConnectionDrawingPolicy, FKismetConnectionDrawingPolicy, FRigVMEdGraphConnectionDrawingPolicy, and FSoundSubmixGraphConnectionDrawingPolicy.
References DetermineWiringStyle(), and Params.
Referenced by DetermineWiringStyle().
Draw()
virtual void FConnectionDrawingPolicy::Draw (TMap< TSharedRef< SWidget >, FArrangedWidget > & InPinGeometries, FArrangedChildren & ArrangedNodes) virtual
Reimplemented in FKismetConnectionDrawingPolicy.
References Draw().
Referenced by Draw().
DrawConnection()
virtual void FConnectionDrawingPolicy::DrawConnection (int32 LayerId, const FVector2f & Start, const FVector2f & End, const FConnectionParams & Params) virtual
References const, DrawConnection(), End, Params, and Start.
Referenced by DrawConnection().
DrawConnection_DeprecationHelper()
void FConnectionDrawingPolicy::DrawConnection_DeprecationHelper (int32 LayerId, const UE::Slate::FDeprecateVector2DParameter & Start, const UE::Slate::FDeprecateVector2DParameter & End, const FConnectionParams & Params) private
References End, Params, and Start.
DrawPinGeometries()
virtual void FConnectionDrawingPolicy::DrawPinGeometries (TMap< TSharedRef< SWidget >, FArrangedWidget > & InPinGeometries, FArrangedChildren & ArrangedNodes) protected virtual
Reimplemented in FRigVMEdGraphConnectionDrawingPolicy.
DrawPreviewConnector()
virtual void FConnectionDrawingPolicy::DrawPreviewConnector (const FGeometry & PinGeometry, const FVector2f & StartPoint, const FVector2f & EndPoint, UEdGraphPin * Pin) virtual
References const, DrawPreviewConnector(), EndPoint, Pin, and StartPoint.
Referenced by DrawPreviewConnector().
DrawPreviewConnector_DeprecationHelper()
void FConnectionDrawingPolicy::DrawPreviewConnector_DeprecationHelper (const FGeometry & PinGeometry, const UE::Slate::FDeprecateVector2DParameter & StartPoint, const UE::Slate::FDeprecateVector2DParameter & EndPoint, UEdGraphPin * Pin) private
References EndPoint, Pin, and StartPoint.
DrawSplineWithArrow() [1/2]
virtual void FConnectionDrawingPolicy::DrawSplineWithArrow (const FGeometry & StartGeom, const FGeometry & EndGeom, const FConnectionParams & Params) virtual
References const, DrawSplineWithArrow(), and Params.
DrawSplineWithArrow() [2/2]
virtual void FConnectionDrawingPolicy::DrawSplineWithArrow (const FVector2f & StartPoint, const FVector2f & EndPoint, const FConnectionParams & Params) virtual
References const, DrawSplineWithArrow(), EndPoint, Params, and StartPoint.
Referenced by DrawSplineWithArrow(), and DrawSplineWithArrow().
DrawSplineWithArrow_DeprecationHelper()
void FConnectionDrawingPolicy::DrawSplineWithArrow_DeprecationHelper (const UE::Slate::FDeprecateVector2DParameter & StartPoint, const UE::Slate::FDeprecateVector2DParameter & EndPoint, const FConnectionParams & Params) private
References EndPoint, Params, and StartPoint.
GetConnectionToolTip()
virtual TSharedPtr< IToolTip > FConnectionDrawingPolicy::GetConnectionToolTip (const SGraphPanel & GraphPanel, const FGraphSplineOverlapResult & OverlapData) const virtual
IsConnectionCulled()
virtual bool FConnectionDrawingPolicy::IsConnectionCulled (const FArrangedWidget & StartLink, const FArrangedWidget & EndLink) const virtual
MakeSplineReparamTable()
float FConnectionDrawingPolicy::MakeSplineReparamTable (const UE::Slate::FDeprecateVector2DParameter & P0, const UE::Slate::FDeprecateVector2DParameter & P0Tangent, const UE::Slate::FDeprecateVector2DParameter & P1, const UE::Slate::FDeprecateVector2DParameter & P1Tangent, FInterpCurve< float > & OutReparamTable) static
ResetIncompatiblePinDrawState()
virtual void FConnectionDrawingPolicy::ResetIncompatiblePinDrawState (const TSet< TSharedRef< SWidget > > & VisiblePins) virtual
Reimplemented in FKismetConnectionDrawingPolicy, and FRigVMEdGraphConnectionDrawingPolicy.
SetHoveredPins()
void FConnectionDrawingPolicy::SetHoveredPins (const TSet< FEdGraphPinReference > & InHoveredPins, const TArray< TSharedPtr< SGraphPin > > & OverridePins, double HoverTime)
SetIncompatiblePinDrawState()
virtual void FConnectionDrawingPolicy::SetIncompatiblePinDrawState (const TSharedPtr< SGraphPin > & StartPin, const TSet< TSharedRef< SWidget > > & VisiblePins) virtual
Reimplemented in FKismetConnectionDrawingPolicy, and FRigVMEdGraphConnectionDrawingPolicy.
SetMarkedPin()
void FConnectionDrawingPolicy::SetMarkedPin (TWeakPtr< SGraphPin > InMarkedPin)
SetMousePosition()
void FConnectionDrawingPolicy::SetMousePosition (const UE::Slate::FDeprecateVector2DParameter & InMousePos)
SetRelinkConnections()
void FConnectionDrawingPolicy::SetRelinkConnections (const TArray< FRelinkConnection > & Connections) inline
Definition at line 157 of file ConnectionDrawingPolicy.h.
References RelinkConnections.
SetSelectedNodes()
void FConnectionDrawingPolicy::SetSelectedNodes (const TArray< UEdGraphNode * > & InSelectedNodes) inline
Definition at line 154 of file ConnectionDrawingPolicy.h.
References SelectedGraphNodes.
UE_DEPRECATED() [1/4]
FConnectionDrawingPolicy::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FConnectionDrawingPolicy::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FConnectionDrawingPolicy::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [4/4]
FConnectionDrawingPolicy::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") const &
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UseDrawStateCaching()
virtual bool FConnectionDrawingPolicy::UseDrawStateCaching () const inline virtual
Reimplemented in FRigVMEdGraphConnectionDrawingPolicy.
Definition at line 195 of file ConnectionDrawingPolicy.h.
References UseDrawStateCaching().
Referenced by UseDrawStateCaching().
Field Documentation
ArrowImage
const FSlateBrush* FConnectionDrawingPolicy::ArrowImage protected
Definition at line 105 of file ConnectionDrawingPolicy.h.
Referenced by FRigVMEdGraphConnectionDrawingPolicy::FRigVMEdGraphConnectionDrawingPolicy().
ArrowLayerID
int32 FConnectionDrawingPolicy::ArrowLayerID protected
Definition at line 103 of file ConnectionDrawingPolicy.h.
ArrowRadius
FDeprecateSlateVector2D FConnectionDrawingPolicy::ArrowRadius
Definition at line 112 of file ConnectionDrawingPolicy.h.
Referenced by FRigVMEdGraphConnectionDrawingPolicy::FRigVMEdGraphConnectionDrawingPolicy().
BubbleImage
const FSlateBrush* FConnectionDrawingPolicy::BubbleImage protected
Definition at line 107 of file ConnectionDrawingPolicy.h.
ClippingRect
const FSlateRect& FConnectionDrawingPolicy::ClippingRect protected
Definition at line 127 of file ConnectionDrawingPolicy.h.
const
const FVector2D& End FConnectionDrawingPolicy::const
Definition at line 168 of file ConnectionDrawingPolicy.h.
Referenced by ComputeSplineTangent(), DrawConnection(), DrawPreviewConnector(), DrawSplineWithArrow(), and DrawSplineWithArrow().
DrawElementsList
FSlateWindowElementList& FConnectionDrawingPolicy::DrawElementsList protected
Definition at line 128 of file ConnectionDrawingPolicy.h.
End
const FVector2D const FVector2D& FConnectionDrawingPolicy::End
Definition at line 173 of file ConnectionDrawingPolicy.h.
Referenced by ComputeSplineTangent(), ComputeSplineTangent_DeprecationHelper(), DrawConnection(), and DrawConnection_DeprecationHelper().
EndPoint [1/2]
const FVector2D& FConnectionDrawingPolicy::EndPoint
Definition at line 162 of file ConnectionDrawingPolicy.h.
Referenced by DrawPreviewConnector(), DrawPreviewConnector_DeprecationHelper(), DrawSplineWithArrow(), and DrawSplineWithArrow_DeprecationHelper().
EndPoint [2/2]
const FVector2D const FVector2D& FConnectionDrawingPolicy::EndPoint
Definition at line 177 of file ConnectionDrawingPolicy.h.
HoverDeemphasisDarkFraction
float FConnectionDrawingPolicy::HoverDeemphasisDarkFraction protected
Definition at line 126 of file ConnectionDrawingPolicy.h.
HoveredPins
TSet< FEdGraphPinReference > FConnectionDrawingPolicy::HoveredPins protected
Definition at line 130 of file ConnectionDrawingPolicy.h.
LastHoverTimeEvent
double FConnectionDrawingPolicy::LastHoverTimeEvent protected
Definition at line 132 of file ConnectionDrawingPolicy.h.
LocalMousePosition
FDeprecateSlateVector2D FConnectionDrawingPolicy::LocalMousePosition protected
Definition at line 133 of file ConnectionDrawingPolicy.h.
MidpointImage
const FSlateBrush* FConnectionDrawingPolicy::MidpointImage protected
Definition at line 106 of file ConnectionDrawingPolicy.h.
Referenced by FRigVMEdGraphConnectionDrawingPolicy::FRigVMEdGraphConnectionDrawingPolicy().
MidpointRadius
FDeprecateSlateVector2D FConnectionDrawingPolicy::MidpointRadius
Definition at line 113 of file ConnectionDrawingPolicy.h.
Referenced by FRigVMEdGraphConnectionDrawingPolicy::FRigVMEdGraphConnectionDrawingPolicy().
Params [1/2]
const FVector2D const FConnectionParams& FConnectionDrawingPolicy::Params
Definition at line 162 of file ConnectionDrawingPolicy.h.
Referenced by DetermineWiringStyle(), FDataflowConnectionDrawingPolicy::DetermineWiringStyle(), FKismetConnectionDrawingPolicy::DetermineWiringStyle(), FRigVMEdGraphConnectionDrawingPolicy::DetermineWiringStyle(), FSoundSubmixGraphConnectionDrawingPolicy::DetermineWiringStyle(), DrawConnection(), DrawConnection_DeprecationHelper(), DrawSplineWithArrow(), DrawSplineWithArrow(), and DrawSplineWithArrow_DeprecationHelper().
Params [2/2]
const FVector2D const FVector2D const FConnectionParams& FConnectionDrawingPolicy::Params
Definition at line 173 of file ConnectionDrawingPolicy.h.
Pin
const FVector2D const FVector2D UEdGraphPin* FConnectionDrawingPolicy::Pin
Definition at line 177 of file ConnectionDrawingPolicy.h.
Referenced by DrawPreviewConnector(), DrawPreviewConnector_DeprecationHelper(), and FKismetConnectionDrawingPolicy::FindPinCenter().
PinGeometries
TMap<TSharedRef<SWidget>, FArrangedWidget>* FConnectionDrawingPolicy::PinGeometries protected
Definition at line 131 of file ConnectionDrawingPolicy.h.
Referenced by FKismetConnectionDrawingPolicy::Draw().
PinToPinWidgetMap
TMap< UEdGraphPin*, TSharedPtr<SGraphPin> > FConnectionDrawingPolicy::PinToPinWidgetMap protected
Definition at line 129 of file ConnectionDrawingPolicy.h.
RelinkConnections
TArray<FRelinkConnection> FConnectionDrawingPolicy::RelinkConnections protected
List of currently relinked connections.
Definition at line 136 of file ConnectionDrawingPolicy.h.
Referenced by SetRelinkConnections().
SelectedGraphNodes
TArray<UEdGraphNode*> FConnectionDrawingPolicy::SelectedGraphNodes protected
Selected nodes in the graph panel.
Definition at line 139 of file ConnectionDrawingPolicy.h.
Referenced by SetSelectedNodes().
Settings
const UGraphEditorSettings* FConnectionDrawingPolicy::Settings protected
Definition at line 109 of file ConnectionDrawingPolicy.h.
SplineOverlapResult
FGraphSplineOverlapResult FConnectionDrawingPolicy::SplineOverlapResult
Definition at line 115 of file ConnectionDrawingPolicy.h.
Start
const FVector2D& FConnectionDrawingPolicy::Start
Definition at line 173 of file ConnectionDrawingPolicy.h.
Referenced by ComputeSplineTangent(), ComputeSplineTangent_DeprecationHelper(), DrawConnection(), and DrawConnection_DeprecationHelper().
StartPoint
const FVector2D& FConnectionDrawingPolicy::StartPoint
Definition at line 177 of file ConnectionDrawingPolicy.h.
Referenced by DrawPreviewConnector(), DrawPreviewConnector_DeprecationHelper(), DrawSplineWithArrow(), and DrawSplineWithArrow_DeprecationHelper().
WireLayerID
int32 FConnectionDrawingPolicy::WireLayerID protected
Definition at line 102 of file ConnectionDrawingPolicy.h.
ZoomFactor
float FConnectionDrawingPolicy::ZoomFactor protected
Definition at line 125 of file ConnectionDrawingPolicy.h.
Referenced by FKismetConnectionDrawingPolicy::FKismetConnectionDrawingPolicy(), FSoundSubmixGraphConnectionDrawingPolicy::FSoundSubmixGraphConnectionDrawingPolicy(), and FRigVMEdGraphConnectionDrawingPolicy::UseLowDetailConnections().
The documentation for this class was generated from the following file:
ConnectionDrawingPolicy.h