Unreal Engine 5.6 C++ API: UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T > Struct Template Reference
UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T > Struct Template Reference
#include "PimplPtr.h"
Public Types
enum class EDeepCopyType { ConstructType }
enum class ENoCopyType { ConstructType }
Public Member Functions
template<typename... ArgTypes>
TPimplHeapObjectImpl (EDeepCopyType, ArgTypes &&... Args)
template<typename... ArgTypes>
TPimplHeapObjectImpl (ENoCopyType, ArgTypes &&... Args)
TPimplHeapObjectImpl (void *InVal)
Data Fields
FCopyFunc Copier = nullptr
FDeleteFunc Deleter = &DeleterFunc<T>
T Val
Detailed Description
template<typename T>
struct UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >
Definition at line 84 of file PimplPtr.h.
Member Enumeration Documentation
EDeepCopyType
template<typename T> enum class UE::Core::Private::PimplPtr::TPimplHeapObjectImpl::EDeepCopyType strong
Enumerator
ConstructType
Definition at line 87 of file PimplPtr.h.
ENoCopyType
template<typename T> enum class UE::Core::Private::PimplPtr::TPimplHeapObjectImpl::ENoCopyType strong
Enumerator
ConstructType
Definition at line 86 of file PimplPtr.h.
Constructor & Destructor Documentation
TPimplHeapObjectImpl() [1/3]
template<typename T> template<typename... ArgTypes> UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl (ENoCopyType , ArgTypes &&... Args) inline explicit
Definition at line 90 of file PimplPtr.h.
References TPimplHeapObjectImpl(), Forward(), UE::Core::Private::PimplPtr::RequiredAlignment, STRUCT_OFFSET, and Val.
Referenced by TPimplHeapObjectImpl(), and TPimplHeapObjectImpl().
TPimplHeapObjectImpl() [2/3]
template<typename T> template<typename... ArgTypes> UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl (EDeepCopyType , ArgTypes &&... Args) inline explicit
Definition at line 99 of file PimplPtr.h.
References TPimplHeapObjectImpl(), Copier, UE::Core::Private::PimplPtr::CopyFunc(), Forward(), UE::Core::Private::PimplPtr::RequiredAlignment, STRUCT_OFFSET, and Val.
TPimplHeapObjectImpl() [3/3]
template<typename T> UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl (void * InVal) inline explicit
Definition at line 108 of file PimplPtr.h.
References Copier, UE::Core::Private::PimplPtr::CopyFunc(), and Val.
Field Documentation
Copier
template<typename T> FCopyFunc UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::Copier = nullptr
Definition at line 116 of file PimplPtr.h.
Referenced by TPimplHeapObjectImpl(), and TPimplHeapObjectImpl().
Deleter
template<typename T> FDeleteFunc UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::Deleter = &DeleterFunc<T>
Definition at line 115 of file PimplPtr.h.
Val
template<typename T> T UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::Val
Definition at line 118 of file PimplPtr.h.
Referenced by TPimplHeapObjectImpl(), TPimplHeapObjectImpl(), and TPimplHeapObjectImpl().
The documentation for this struct was generated from the following file:
PimplPtr.h