Unreal Engine 5.6 C++ API: FTwoVectors Struct Reference
FTwoVectors Struct Reference
A pair of 3D vectors.
#include "TwoVectors.h"
Public Member Functions
FORCEINLINE FTwoVectors ()
Default constructor.
FORCEINLINE FTwoVectors (EForceInit)
Constructor.
FORCEINLINE FTwoVectors (FVector In1, FVector In2)
Creates and initializes a new instance with the specified vectors.
bool Equals (const FTwoVectors &V, float Tolerance=UE_KINDA_SMALL_NUMBER) const
Error-tolerant comparison.
FVector::FReal GetMax () const
Get the maximum value of all the vector coordinates.
FVector::FReal GetMin () const
Get the minimum value of all the vector coordinates.
bool operator!= (const FTwoVectors &V) const
Checks two pairs for inequality.
FORCEINLINE FTwoVectors operator* (const FTwoVectors &V) const
Gets result of multiplying two pairs of vectors.
FORCEINLINE FTwoVectors operator* (float Scale) const
Gets result of scaling pair of vectors.
FTwoVectors operator*= (const FTwoVectors &V)
Multiply the pair by another.
FORCEINLINE FTwoVectors operator*= (float Scale)
Scale the pair.
FORCEINLINE FTwoVectors operator+ (const FTwoVectors &V) const
Gets result of addition of two pairs of vectors.
FORCEINLINE FTwoVectors operator+= (const FTwoVectors &V)
Add a pair to this.
FORCEINLINE FTwoVectors operator- () const
Get a negated copy of the pair.
FORCEINLINE FTwoVectors operator- (const FTwoVectors &V) const
Gets result of subtraction of two pairs of vectors.
FORCEINLINE FTwoVectors operator-= (const FTwoVectors &V)
Subtract a pair from this.
FORCEINLINE FTwoVectors operator/ (const FTwoVectors &V) const
Gets result of division of two pairs of vectors.
FTwoVectors operator/ (float Scale) const
Gets result of dividing pair of vectors.
FTwoVectors operator/= (const FTwoVectors &V)
Divide the pair by another.
FTwoVectors operator/= (float V)
Divide the pair.
bool operator== (const FTwoVectors &V) const
Checks two pairs for equality.
FVector::FReal & operator[] (int32 i)
Get a specific component from the pair.
bool Serialize (FArchive &Ar)
FString ToString () const
Get a textual representation of this two-vector.
Data Fields
FVector v1
Holds the first vector.
FVector v2
Holds the second vector.
Friends
FArchive & operator<< (FArchive &Ar, FTwoVectors &TwoVectors)
Serializes the two-vector.
Detailed Description
A pair of 3D vectors.
Definition at line 14 of file TwoVectors.h.
Constructor & Destructor Documentation
FTwoVectors() [1/3]
FORCEINLINE FTwoVectors::FTwoVectors () nodiscard
Default constructor.
Definition at line 243 of file TwoVectors.h.
References FORCEINLINE, v1, and v2.
Referenced by Equals(), operator!=(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/(), operator/=(), operator/=(), operator<<, and operator==().
FTwoVectors() [2/3]
FORCEINLINE FTwoVectors::FTwoVectors (FVector In1, FVector In2) nodiscard
Creates and initializes a new instance with the specified vectors.
Parameters
In1 The first Vector.
In2 The second Vector.
Definition at line 249 of file TwoVectors.h.
References FORCEINLINE, FVector, v1, and v2.
FTwoVectors() [3/3]
FORCEINLINE FTwoVectors::FTwoVectors (EForceInit) explicit nodiscard
Constructor.
Parameters
EForceInit Force Init Enum
Definition at line 255 of file TwoVectors.h.
References ForceInit, FORCEINLINE, v1, and v2.
Member Function Documentation
Equals()
FORCEINLINE bool FTwoVectors::Equals (const FTwoVectors & V, float Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Error-tolerant comparison.
Parameters
V The other pair.
Tolerance Error Tolerance.
Returns
true if two pairs are equal within specified tolerance, false otherwise..
Definition at line 329 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
GetMax()
FORCEINLINE FVector::FReal FTwoVectors::GetMax () const nodiscard
Get the maximum value of all the vector coordinates.
Returns
The maximum value of all the vector coordinates.
Definition at line 399 of file TwoVectors.h.
References FORCEINLINE, FMath::Max, v1, and v2.
GetMin()
FORCEINLINE FVector::FReal FTwoVectors::GetMin () const nodiscard
Get the minimum value of all the vector coordinates.
Returns
The minimum value of all the vector coordinates.
Definition at line 408 of file TwoVectors.h.
References FORCEINLINE, FMath::Min, v1, and v2.
operator!=()
FORCEINLINE bool FTwoVectors::operator!= (const FTwoVectors & V) const nodiscard
Checks two pairs for inequality.
Parameters
V The other pair.
Returns
true if the two pairs are different, false otherwise..
Definition at line 323 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
operator*() [1/2]
FORCEINLINE FTwoVectors FTwoVectors::operator* (const FTwoVectors & V) const nodiscard
Gets result of multiplying two pairs of vectors.
Parameters
V The pair to multiply with.
Returns
Result of multiplication.
Definition at line 299 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, FVector, v1, and v2.
operator*() [2/2]
FORCEINLINE FTwoVectors FTwoVectors::operator* (float Scale) const nodiscard
Gets result of scaling pair of vectors.
Parameters
Scale The scaling factor.
Returns
Result of Scaling.
Definition at line 279 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, FVector, Scale, v1, and v2.
operator*=() [1/2]
FORCEINLINE FTwoVectors FTwoVectors::operator*= (const FTwoVectors & V)
Multiply the pair by another.
Parameters
The other pair.
Returns
Copy of the pair after multiplication.
Definition at line 382 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
operator*=() [2/2]
FORCEINLINE FTwoVectors FTwoVectors::operator*= (float Scale)
Scale the pair.
Parameters
Scale What to scale by.
Returns
Copy of the pair after scaling.
Definition at line 362 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, Scale, v1, and v2.
operator+()
FORCEINLINE FTwoVectors FTwoVectors::operator+ (const FTwoVectors & V) const nodiscard
Gets result of addition of two pairs of vectors.
Parameters
V The pair to add.
Returns
Result of addition.
Definition at line 261 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, FVector, v1, and v2.
operator+=()
FORCEINLINE FTwoVectors FTwoVectors::operator+= (const FTwoVectors & V)
Add a pair to this.
Parameters
The pair to add.
Returns
Copy of the pair after addition.
Definition at line 344 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
operator-() [1/2]
FORCEINLINE FTwoVectors FTwoVectors::operator- () const nodiscard
Get a negated copy of the pair.
Returns
A negated copy of the pair.
Definition at line 335 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, FVector, v1, and v2.
operator-() [2/2]
FORCEINLINE FTwoVectors FTwoVectors::operator- (const FTwoVectors & V) const nodiscard
Gets result of subtraction of two pairs of vectors.
Parameters
V The pair to subtract.
Returns
Result of subtraction.
Definition at line 270 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, FVector, v1, and v2.
operator-=()
FORCEINLINE FTwoVectors FTwoVectors::operator-= (const FTwoVectors & V)
Subtract a pair from this.
Parameters
The pair to subtract.
Returns
Copy of the pair after subtraction.
Definition at line 353 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
operator/() [1/2]
FORCEINLINE FTwoVectors FTwoVectors::operator/ (const FTwoVectors & V) const nodiscard
Gets result of division of two pairs of vectors.
Parameters
V The pair to divide by.
Returns
Result of division.
Definition at line 308 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, FVector, v1, and v2.
operator/() [2/2]
FORCEINLINE FTwoVectors FTwoVectors::operator/ (float Scale) const nodiscard
Gets result of dividing pair of vectors.
Parameters
Scale What to divide by.
Returns
Result of division.
Definition at line 288 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, FVector, Scale, v1, and v2.
operator/=() [1/2]
FORCEINLINE FTwoVectors FTwoVectors::operator/= (const FTwoVectors & V)
Divide the pair by another.
Parameters
The other pair.
Returns
Copy of the pair after multiplication.
Definition at line 390 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
operator/=() [2/2]
FORCEINLINE FTwoVectors FTwoVectors::operator/= (float V)
Divide the pair.
Parameters
What to divide by.
Returns
Copy of the pair after division.
Definition at line 371 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
operator==()
FORCEINLINE bool FTwoVectors::operator== (const FTwoVectors & V) const nodiscard
Checks two pairs for equality.
Parameters
V The other pair.
Returns
true if the two pairs are equal, false otherwise..
Definition at line 317 of file TwoVectors.h.
References FTwoVectors(), FORCEINLINE, v1, and v2.
operator[]()
FORCEINLINE FVector::FReal & FTwoVectors::operator[] (int32 i)
Get a specific component from the pair.
Parameters
i The index of the component, even indices are for the first vector, odd ones are for the second. Returns index 5 if out of range.
Returns
Reference to the specified component.
Definition at line 417 of file TwoVectors.h.
References check, FORCEINLINE, v1, and v2.
Serialize()
bool FTwoVectors::Serialize (FArchive & Ar) inline
Definition at line 226 of file TwoVectors.h.
References Ar.
ToString()
FORCEINLINE FString FTwoVectors::ToString () const nodiscard
Get a textual representation of this two-vector.
Returns
A string describing the two-vector.
Definition at line 434 of file TwoVectors.h.
References FORCEINLINE, TEXT, v1, and v2.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FTwoVectors & TwoVectors) friend
Serializes the two-vector.
Parameters
Ar The archive to serialize into.
TwoVectors The two-vector to serialize.
Returns
Reference to the Archive after serialization.
Definition at line 221 of file TwoVectors.h.
References FTwoVectors(), Ar, and TwoVectors.
Field Documentation
v1
FVector FTwoVectors::v1
Holds the first vector.
Definition at line 19 of file TwoVectors.h.
Referenced by FTwoVectors(), FTwoVectors(), FTwoVectors(), Equals(), GetMax(), GetMin(), operator!=(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/(), operator/=(), operator/=(), operator==(), operator[](), and ToString().
v2
FVector FTwoVectors::v2
Holds the second vector.
Definition at line 22 of file TwoVectors.h.
Referenced by FTwoVectors(), FTwoVectors(), FTwoVectors(), Equals(), GetMax(), GetMin(), operator!=(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/(), operator/=(), operator/=(), operator==(), operator[](), and ToString().
The documentation for this struct was generated from the following file:
TwoVectors.h