Unreal Engine 5.6 C++ API: UE::CoreUObject::Private Namespace Reference
UE::CoreUObject::Private Namespace Reference
Data Structures
struct FObjectDescriptorDebug
struct FObjectHandleDataClassDescriptor
struct FObjectHandlePackageDebugData
struct FObjectPathIdDebug
struct FStoredObjectPathDebug
struct TIsCastable
Enumerations
enum class ENonNullableBehavior { LogWarning = 0 , LogError = 1 , CreateDefaultObjectIfPossible = 2 }
Functions
template<typename To, typename From>
FORCEINLINE To DynamicCast (From &&Arg)
template<typename To, typename From>
FORCEINLINE To DynamicCast (From *Arg)
void ExportEnumToBuffer (const UEnum *Enum, const FProperty *Prop, const FNumericProperty *NumericProp, FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope)
UClass * GetClass (UObject *Obj)
FName GetFName (const UObject *Obj)
FString GetFullName (const UObject *Obj, const UObject *StopOuter=nullptr, EObjectFullNameFlags Flags=EObjectFullNameFlags::None)
ENonNullableBehavior GetNonNullableBehavior ()
UObject * GetOuter (const UObject *Obj)
UPackage * GetPackage (const UObject *Obj)
FString GetPathName (const UObject *Obj, const UObject *StopOuter=nullptr)
bool HasAnyFlags (const UObject *Obj, int32 FlagsToCheck)
const TCHAR * ImportEnumFromBuffer (UEnum *Enum, const FProperty *PropertyToSet, const FNumericProperty *UnderlyingProp, const TCHAR *PropertyClassName, const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, FOutputDevice *ErrorText)
bool IsIn (const UObject *Obj, const UObject *SomeOuter)
FObjectHandle MakeObjectHandle (UObject *Object)
these functions are always defined regardless of UE_WITH_OBJECT_HANDLE_LATE_RESOLVE value
FObjectKey MakeObjectKey (int32 ObjectIndex, int32 ObjectSerialNumber)
UObject * NoResolveObjectHandleNoRead (const FObjectHandle &Handle)
void OnClassReferenceResolved (const FObjectRef &ObjectRef, UPackage *Package, UClass *Class)
void OnHandleRead (const UObject *Object)
void OnHandleRead (TArrayView< const UObject * > Objects)
void OnReferenceLoaded (const FObjectRef &ObjectRef, UPackage *Package, UObject *Object)
void OnReferenceResolved (const FObjectRef &ObjectRef, UPackage *Package, UClass *Class)
UObject * ReadObjectHandlePointerNoCheck (FObjectHandle Handle)
Read the handle as a pointer without checking if it is resolved.
UObject * ResolveObjectHandle (FObjectHandle &Handle)
UClass * ResolveObjectHandleClass (FObjectHandle Handle)
UObject * ResolveObjectHandleNoRead (FObjectHandle &Handle)
UObject * ResolveObjectHandleNoReadNoCheck (FObjectHandle &Handle)
Resolves an ObjectHandle without checking if already resolved.
Variables
constexpr uint32 ObjectIdShift = 2
constexpr uint32 PackageIdMask = 0x3FFF'FFFF
constexpr uint32 PackageIdShift = 34
template<typename Type>
constexpr EClassCastFlags TCastFlags_V = CASTCLASS_None
template<typename Type>
constexpr EClassCastFlags TCastFlags_V< const Type > = TCastFlags_V<Type>
constexpr uint32 TypeIdShift = 1
Enumeration Type Documentation
ENonNullableBehavior
enum class UE::CoreUObject::Private::ENonNullableBehavior strong
Enumerator
LogWarning
LogError
CreateDefaultObjectIfPossible
Definition at line 98 of file UnrealType.h.
Function Documentation
DynamicCast() [1/2]
template<typename To, typename From> FORCEINLINE To UE::CoreUObject::Private::DynamicCast (From && Arg)
Definition at line 567 of file Casts.h.
References CastChecked(), FORCEINLINE, Forward(), TLosesQualifiersFromTo_V, and UE::CoreUObject::Private::TIsCastable< T >::Value.
DynamicCast() [2/2]
template<typename To, typename From> FORCEINLINE To UE::CoreUObject::Private::DynamicCast (From * Arg)
Definition at line 541 of file Casts.h.
References Cast(), FORCEINLINE, TLosesQualifiersFromTo_V, and UE::CoreUObject::Private::TIsCastable< T >::Value.
ExportEnumToBuffer()
void UE::CoreUObject::Private::ExportEnumToBuffer (const UEnum * Enum, const FProperty * Prop, const FNumericProperty * NumericProp, FString & ValueStr, const void * PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void * DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope)
References Enum, and Parent.
GetClass()
UClass * UE::CoreUObject::Private::GetClass (UObject * Obj)
Referenced by ResolveObjectHandleClass().
GetFName()
FName UE::CoreUObject::Private::GetFName (const UObject * Obj)
Referenced by FObjectPtr::GetFName().
GetFullName()
FString UE::CoreUObject::Private::GetFullName (const UObject * Obj, const UObject * StopOuter = nullptr, EObjectFullNameFlags Flags = EObjectFullNameFlags::None)
References Flags, and None.
Referenced by FObjectPtr::GetFullName().
GetNonNullableBehavior()
ENonNullableBehavior UE::CoreUObject::Private::GetNonNullableBehavior ()
GetOuter()
UObject * UE::CoreUObject::Private::GetOuter (const UObject * Obj)
Referenced by FObjectPtr::GetOuter().
GetPackage()
UPackage * UE::CoreUObject::Private::GetPackage (const UObject * Obj)
Referenced by FObjectPtr::GetPackage().
GetPathName()
FString UE::CoreUObject::Private::GetPathName (const UObject * Obj, const UObject * StopOuter = nullptr)
Referenced by FObjectPtr::GetPathName().
HasAnyFlags()
bool UE::CoreUObject::Private::HasAnyFlags (const UObject * Obj, int32 FlagsToCheck)
ImportEnumFromBuffer()
const TCHAR * UE::CoreUObject::Private::ImportEnumFromBuffer (UEnum * Enum, const FProperty * PropertyToSet, const FNumericProperty * UnderlyingProp, const TCHAR * PropertyClassName, const TCHAR * Buffer, void * ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, FOutputDevice * ErrorText)
References Buffer, and Enum.
IsIn()
bool UE::CoreUObject::Private::IsIn (const UObject * Obj, const UObject * SomeOuter)
Referenced by FObjectPtr::IsIn().
MakeObjectHandle()
FObjectHandle UE::CoreUObject::Private::MakeObjectHandle (UObject * Object) inline
these functions are always defined regardless of UE_WITH_OBJECT_HANDLE_LATE_RESOLVE value
Definition at line 356 of file ObjectHandle.h.
Referenced by FObjectPtr::operator=(), FObjectPtr::operator=(), FObjectPtr::operator=(), ResolveObjectHandleNoRead(), and ResolveObjectHandleNoReadNoCheck().
MakeObjectKey()
FObjectKey UE::CoreUObject::Private::MakeObjectKey (int32 ObjectIndex, int32 ObjectSerialNumber)
NoResolveObjectHandleNoRead()
UObject * UE::CoreUObject::Private::NoResolveObjectHandleNoRead (const FObjectHandle & Handle) inline
Definition at line 468 of file ObjectHandle.h.
References Handle, IsObjectHandleResolved_ForGC(), and ReadObjectHandlePointerNoCheck().
Referenced by ObjectPtr_Private::Friend::NoAccessTrackingGetNoResolve().
OnClassReferenceResolved()
void UE::CoreUObject::Private::OnClassReferenceResolved (const FObjectRef & ObjectRef, UPackage * Package, UClass * Class) inline
Definition at line 133 of file ObjectHandleTracking.h.
References Class.
OnHandleRead() [1/2]
void UE::CoreUObject::Private::OnHandleRead (const UObject * Object) inline
Definition at line 131 of file ObjectHandleTracking.h.
Referenced by Cast(), CastChecked(), ExactCast(), TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRangeContiguous(), TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRangeContiguous(), and ResolveObjectHandle().
OnHandleRead() [2/2]
void UE::CoreUObject::Private::OnHandleRead (TArrayView< const UObject * > Objects) inline
Definition at line 132 of file ObjectHandleTracking.h.
OnReferenceLoaded()
void UE::CoreUObject::Private::OnReferenceLoaded (const FObjectRef & ObjectRef, UPackage * Package, UObject * Object) inline
Definition at line 135 of file ObjectHandleTracking.h.
OnReferenceResolved()
void UE::CoreUObject::Private::OnReferenceResolved (const FObjectRef & ObjectRef, UPackage * Package, UClass * Class) inline
Definition at line 134 of file ObjectHandleTracking.h.
References Class.
ReadObjectHandlePointerNoCheck()
UObject * UE::CoreUObject::Private::ReadObjectHandlePointerNoCheck (FObjectHandle Handle) inline
Read the handle as a pointer without checking if it is resolved.
Invalid to call for unresolved handles.
Definition at line 517 of file ObjectHandle.h.
References Handle.
Referenced by FObjectPtr::ConditionallyMarkAsReachable(), TObjectPtr< T >::GetNoResolveNoCheck(), NoResolveObjectHandleNoRead(), ResolveObjectHandle(), ResolveObjectHandleClass(), ResolveObjectHandleNoRead(), and ResolveObjectHandleNoReadNoCheck().
ResolveObjectHandle()
UObject * UE::CoreUObject::Private::ResolveObjectHandle (FObjectHandle & Handle) inline
Definition at line 367 of file ObjectHandle.h.
References Handle, OnHandleRead(), ReadObjectHandlePointerNoCheck(), and ResolveObjectHandleNoRead().
Referenced by FObjectPtr::Get(), and ResolveObjectHandleClass().
ResolveObjectHandleClass()
UClass * UE::CoreUObject::Private::ResolveObjectHandleClass (FObjectHandle Handle) inline
Definition at line 388 of file ObjectHandle.h.
References GetClass(), Handle, IsObjectHandleResolved(), ReadObjectHandlePointerNoCheck(), and ResolveObjectHandle().
Referenced by FObjectPtr::GetClass().
ResolveObjectHandleNoRead()
UObject * UE::CoreUObject::Private::ResolveObjectHandleNoRead (FObjectHandle & Handle) inline
Definition at line 420 of file ObjectHandle.h.
References Handle, IsObjectHandleNull(), IsObjectHandleResolved(), IsObjectHandleTypeSafe(), UE::RemoteObject::Handle::IsRemote(), MakeObjectHandle(), ReadObjectHandlePointerNoCheck(), UE::RemoteObject::Handle::ResolveObject(), and UE::RemoteObject::Handle::TouchResidentObject().
Referenced by Cast(), CastChecked(), ExactCast(), ObjectPtr_Private::Friend::NoAccessTrackingGet(), TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRangeContiguous(), TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRangeContiguous(), and ResolveObjectHandle().
ResolveObjectHandleNoReadNoCheck()
UObject * UE::CoreUObject::Private::ResolveObjectHandleNoReadNoCheck (FObjectHandle & Handle) inline
Resolves an ObjectHandle without checking if already resolved.
Invalid to call for resolved handles
Definition at line 482 of file ObjectHandle.h.
References Handle, IsObjectHandleResolved_ForGC(), IsObjectHandleTypeSafe(), MakeObjectHandle(), ReadObjectHandlePointerNoCheck(), and UE::RemoteObject::Handle::ResolveObject().
Referenced by TObjectPtr< T >::GetNoReadNoCheck().
Variable Documentation
ObjectIdShift
uint32 UE::CoreUObject::Private::ObjectIdShift = 2 inline constexpr
Definition at line 570 of file ObjectHandle.h.
PackageIdMask
uint32 UE::CoreUObject::Private::PackageIdMask = 0x3FFF'FFFF inline constexpr
Definition at line 572 of file ObjectHandle.h.
PackageIdShift
uint32 UE::CoreUObject::Private::PackageIdShift = 34 inline constexpr
Definition at line 571 of file ObjectHandle.h.
TCastFlags_V
template<typename Type> EClassCastFlags UE::CoreUObject::Private::TCastFlags_V = CASTCLASS_None inline constexpr
Definition at line 81 of file Casts.h.
Referenced by Cast(), Cast(), and CastChecked().
TCastFlags_V< const Type >
template<typename Type> EClassCastFlags UE::CoreUObject::Private::TCastFlags_V< const Type > = TCastFlags_V<Type> inline constexpr
Definition at line 84 of file Casts.h.
TypeIdShift
uint32 UE::CoreUObject::Private::TypeIdShift = 1 inline constexpr
Definition at line 569 of file ObjectHandle.h.