Unreal Engine 5.6 C++ API: UWaterMeshComponent Class Reference
UWaterMeshComponent Class Reference abstract
#include "WaterMeshComponent.h"
Private Member Functions
virtual WATER_API FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual WATER_API void CollectPSOPrecacheData (const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams) override
virtual WATER_API FPrimitiveSceneProxy * CreateSceneProxy () override
WATER_API FIntPoint GetExtentInTiles () const
WATER_API FVector2D GetGlobalWaterMeshCenter () const
float GetLODScale () const
virtual int32 GetNumMaterials () const override
int32 GetTessellationFactor () const
float GetTileSize () const
virtual WATER_API void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
const TSet< TObjectPtr< UMaterialInterface > > & GetUsedMaterialsSet () const
WATER_API FMaterialRelevance GetWaterMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const
Use this instead of GetMaterialRelevance, since this one will go over all materials from all tiles.
const FWaterQuadTreeBuilder & GetWaterQuadTreeBuilder () const
WATER_API bool IsLocalOnlyTessellationEnabled () const
virtual bool IsNavigationRelevant () const override
void MarkWaterMeshGridDirty ()
virtual WATER_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual WATER_API void PostInitProperties () override
GENERATED_BODY() public virtual WATER_API void PostLoad () override
WATER_API void RebuildWaterMesh (float InTileSize, const FIntPoint &InExtentInTiles)
Based on all water bodies in the scene, rebuild the water mesh.
virtual WATER_API void SetMaterial (int32 ElementIndex, UMaterialInterface *Material) override
WATER_API void SetTileSize (float NewTileSize)
virtual WATER_API bool ShouldRenderSelected () const override
UE_DEPRECATED (5.5, "Dynamic water mesh center is now per-view and must be retrieved through the water view extension (water zone actor provides utilities to do this as well)") FVector2D GetDynamicWaterMeshCenter() const
UE_DEPRECATED (5.5, "It is no longer possible to manually set the dynamic mesh center. This is controlled per view by the water view extension.") void SetDynamicWaterMeshCenter(const FVector2D &NewCenter)
UFUNCTION () bool IsEnabled() const
WATER_API void Update ()
UPROPERTY () bool bUseFarMeshWithoutOcean
Forces the water mesh to always render the far mesh, regardless if there is an ocean or not.
UPROPERTY () mutable FIntPoint QuadTreeResolution
The current quad tree resolution derived from the extent of the water zone and the water mesh tile size (Extent / TileSize).
UPROPERTY () TMap< TObjectPtr< UMaterialInterface >
Maps from materials assigned to each water body to actually used MIDs.
UPROPERTY () TObjectPtr< UMaterialInterface > FarDistanceMaterial
UPROPERTY () TSet< TObjectPtr< UMaterialInterface > > UsedMaterials
Unique list of materials used by this component.
UPROPERTY ()) float FarDistanceMeshExtent=0.0f
UPROPERTY ()) float LODScale
World scale of the concentric LODs.
UPROPERTY ()) float TileSize
World size of the water tiles at LOD0.
UPROPERTY ()) int32 ForceCollapseDensityLevel
At above what density level a tile is allowed to force collapse even if not all leaf nodes in the subtree are present.
UPROPERTY ()) int32 TessellationFactor
Highest tessellation factor of a water tile.
Private Attributes
bool bIsEnabled = false
If the system is enabled.
bool bNeedsRebuild = true
Dirty flag which will make sure the water mesh is updated properly.
int32 LODCountBiasScalability = 0
Cached CVarWaterMeshLODCountBias to detect changes in scalability.
float LODScaleBiasScalability = 0.0f
Cached CVarWaterMeshLODScaleBias to detect changes in scalability.
TObjectPtr< UMaterialInstanceDynamic > MaterialToMID
int32 TessFactorBiasScalability = 0
Cached CVarWaterMeshTessFactorBias to detect changes in scalability.
FWaterQuadTree WaterQuadTree
Tiles containing water, stored in a quad tree.
FWaterQuadTreeBuilder WaterQuadTreeBuilder
Additional Inherited Members
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Detailed Description
Definition at line 19 of file WaterMeshComponent.h.
Member Function Documentation
CalcBounds()
virtual WATER_API FBoxSphereBounds UWaterMeshComponent::CalcBounds (const FTransform & LocalToWorld) const override private virtual
References UE_API.
CollectPSOPrecacheData()
virtual WATER_API void UWaterMeshComponent::CollectPSOPrecacheData (const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) override private virtual
References UE_API.
CreateSceneProxy()
virtual WATER_API FPrimitiveSceneProxy * UWaterMeshComponent::CreateSceneProxy () override private virtual
References UE_API.
GetExtentInTiles()
WATER_API FIntPoint UWaterMeshComponent::GetExtentInTiles () const private
References UE_API.
GetGlobalWaterMeshCenter()
WATER_API FVector2D UWaterMeshComponent::GetGlobalWaterMeshCenter () const private
References UE_API.
GetLODScale()
float UWaterMeshComponent::GetLODScale () const inline private
Definition at line 63 of file WaterMeshComponent.h.
References LODScaleBiasScalability.
GetNumMaterials()
virtual int32 UWaterMeshComponent::GetNumMaterials () const inline override private virtual
Reimplemented from UMeshComponent.
Definition at line 32 of file WaterMeshComponent.h.
GetTessellationFactor()
int32 UWaterMeshComponent::GetTessellationFactor () const inline private
Definition at line 61 of file WaterMeshComponent.h.
References FMath::Clamp(), and TessFactorBiasScalability.
GetTileSize()
float UWaterMeshComponent::GetTileSize () const inline private
Definition at line 77 of file WaterMeshComponent.h.
GetUsedMaterials()
virtual WATER_API void UWaterMeshComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override private virtual
Reimplemented from UMeshComponent.
References UE_API.
GetUsedMaterialsSet()
const TSet< TObjectPtr< UMaterialInterface > > & UWaterMeshComponent::GetUsedMaterialsSet () const inline private
Definition at line 57 of file WaterMeshComponent.h.
GetWaterMaterialRelevance()
WATER_API FMaterialRelevance UWaterMeshComponent::GetWaterMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const private
Use this instead of GetMaterialRelevance, since this one will go over all materials from all tiles.
References UE_API.
GetWaterQuadTreeBuilder()
const FWaterQuadTreeBuilder & UWaterMeshComponent::GetWaterQuadTreeBuilder () const inline private
Definition at line 55 of file WaterMeshComponent.h.
References WaterQuadTreeBuilder.
IsLocalOnlyTessellationEnabled()
WATER_API bool UWaterMeshComponent::IsLocalOnlyTessellationEnabled () const private
References UE_API.
IsNavigationRelevant()
virtual bool UWaterMeshComponent::IsNavigationRelevant () const inline override private virtual
Definition at line 45 of file WaterMeshComponent.h.
MarkWaterMeshGridDirty()
void UWaterMeshComponent::MarkWaterMeshGridDirty () inline private
Definition at line 59 of file WaterMeshComponent.h.
References bNeedsRebuild.
PostEditChangeProperty()
virtual WATER_API void UWaterMeshComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
References UE_API.
PostInitProperties()
virtual WATER_API void UWaterMeshComponent::PostInitProperties () override private virtual
References UE_API.
PostLoad()
GENERATED_BODY() public virtual WATER_API void UWaterMeshComponent::PostLoad () override private virtual
References UE_API.
RebuildWaterMesh()
WATER_API void UWaterMeshComponent::RebuildWaterMesh (float InTileSize, const FIntPoint & InExtentInTiles) private
Based on all water bodies in the scene, rebuild the water mesh.
References UE_API.
SetMaterial()
virtual WATER_API void UWaterMeshComponent::SetMaterial (int32 ElementIndex, UMaterialInterface * Material) override private virtual
Reimplemented from UMeshComponent.
References Material, and UE_API.
SetTileSize()
WATER_API void UWaterMeshComponent::SetTileSize (float NewTileSize) private
References UE_API.
ShouldRenderSelected()
virtual WATER_API bool UWaterMeshComponent::ShouldRenderSelected () const override private virtual
References UE_API.
UE_DEPRECATED() [1/2]
UWaterMeshComponent::UE_DEPRECATED (5. 5, "Dynamic water mesh center is now per-view and must be retrieved through the water view extension (water zone actor provides utilities to do this as well)") const inline private
Definition at line 69 of file WaterMeshComponent.h.
References UE::Math::TVector2< double >::ZeroVector.
UE_DEPRECATED() [2/2]
UWaterMeshComponent::UE_DEPRECATED (5. 5, "It is no longer possible to manually set the dynamic mesh center. This is controlled per view by the water view extension.") const & inline private
Definition at line 67 of file WaterMeshComponent.h.
UFUNCTION()
UWaterMeshComponent::UFUNCTION () const inline private
Definition at line 94 of file WaterMeshComponent.h.
References bIsEnabled, Category, and UFUNCTION().
Referenced by UFUNCTION().
Update()
WATER_API void UWaterMeshComponent::Update () private
References UE_API.
UPROPERTY() [1/10]
UWaterMeshComponent::UPROPERTY () private
Forces the water mesh to always render the far mesh, regardless if there is an ocean or not.
References Category, and UPROPERTY().
UPROPERTY() [2/10]
UWaterMeshComponent::UPROPERTY () private
The current quad tree resolution derived from the extent of the water zone and the water mesh tile size (Extent / TileSize).
References Category, Transient, and UPROPERTY().
UPROPERTY() [3/10]
UWaterMeshComponent::UPROPERTY () private
Maps from materials assigned to each water body to actually used MIDs.
Persists across rebuilds in order to cache MIDs
References Transient, and UPROPERTY().
UPROPERTY() [4/10]
UWaterMeshComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [5/10]
UWaterMeshComponent::UPROPERTY () private
Unique list of materials used by this component.
References Transient, and UPROPERTY().
UPROPERTY() [6/10]
UWaterMeshComponent::UPROPERTY () private pure virtual
References Category, meta, and UPROPERTY().
UPROPERTY() [7/10]
UWaterMeshComponent::UPROPERTY () private
World scale of the concentric LODs.
References Category, meta, and UPROPERTY().
UPROPERTY() [8/10]
UWaterMeshComponent::UPROPERTY () private
World size of the water tiles at LOD0.
Multiply this with the ExtentInTiles to get the world extents of the system
References Category, float, and meta.
UPROPERTY() [9/10]
UWaterMeshComponent::UPROPERTY () private
At above what density level a tile is allowed to force collapse even if not all leaf nodes in the subtree are present.
Collapsing will not occus if any child node in the subtree has different materials. Setting this to -1 means no collapsing is allowed and the water mesh will always keep it's silhouette at any distance. Setting this to 0 will allow every level to collapse Setting this to something higher than the LODCount will have no effect
References Category, and meta.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [10/10]
UWaterMeshComponent::UPROPERTY () private
Highest tessellation factor of a water tile.
Max number of verts on the side of a tile will be (2^TessellationFactor)+1)
References Category, meta, and UPROPERTY().
Field Documentation
bIsEnabled
bool UWaterMeshComponent::bIsEnabled = false private
If the system is enabled.
Definition at line 134 of file WaterMeshComponent.h.
Referenced by UFUNCTION().
bNeedsRebuild
bool UWaterMeshComponent::bNeedsRebuild = true private
Dirty flag which will make sure the water mesh is updated properly.
Definition at line 131 of file WaterMeshComponent.h.
Referenced by MarkWaterMeshGridDirty().
LODCountBiasScalability
int32 UWaterMeshComponent::LODCountBiasScalability = 0 private
Cached CVarWaterMeshLODCountBias to detect changes in scalability.
Definition at line 137 of file WaterMeshComponent.h.
LODScaleBiasScalability
float UWaterMeshComponent::LODScaleBiasScalability = 0.0f private
Cached CVarWaterMeshLODScaleBias to detect changes in scalability.
Definition at line 143 of file WaterMeshComponent.h.
Referenced by GetLODScale().
MaterialToMID
TObjectPtr<UMaterialInstanceDynamic> UWaterMeshComponent::MaterialToMID private
Definition at line 124 of file WaterMeshComponent.h.
TessFactorBiasScalability
int32 UWaterMeshComponent::TessFactorBiasScalability = 0 private
Cached CVarWaterMeshTessFactorBias to detect changes in scalability.
Definition at line 140 of file WaterMeshComponent.h.
Referenced by GetTessellationFactor().
WaterQuadTree
FWaterQuadTree UWaterMeshComponent::WaterQuadTree private
Tiles containing water, stored in a quad tree.
Definition at line 116 of file WaterMeshComponent.h.
WaterQuadTreeBuilder
FWaterQuadTreeBuilder UWaterMeshComponent::WaterQuadTreeBuilder private
Definition at line 113 of file WaterMeshComponent.h.
Referenced by GetWaterQuadTreeBuilder().
The documentation for this class was generated from the following file:
WaterMeshComponent.h