Unreal Engine 5.6 C++ API: FMeshRenderDecomposition Class Reference
FMeshRenderDecomposition Class Reference
FMeshRenderDecomposition represents a decomposition of a mesh into "chunks" of triangles, with associated materials.
#include "MeshRenderDecomposition.h"
Data Structures
struct FGroup
Public Member Functions
FMeshRenderDecomposition ()=default
FMeshRenderDecomposition (const FMeshRenderDecomposition &)=delete
FMeshRenderDecomposition (FMeshRenderDecomposition &&)=default
int32 AppendGroup ()
GEOMETRYFRAMEWORK_API void BuildAssociations (const FDynamicMesh3 *Mesh)
Construct mappings between mesh and groups (eg TriangleToGroupMap)
FGroup & GetGroup (int32 Index)
const FGroup & GetGroup (int32 Index) const
int32 GetGroupForTriangle (int32 TriangleID) const
void Initialize (int32 Count)
bool IsGroup (int32 Index) const
int32 Num () const
FMeshRenderDecomposition & operator= (const FMeshRenderDecomposition &)=delete
FMeshRenderDecomposition & operator= (FMeshRenderDecomposition &&)=default
Static Public Member Functions
static GEOMETRYFRAMEWORK_API void BuildChunkedDecomposition (const FDynamicMesh3 *Mesh, const FComponentMaterialSet *MaterialSet, FMeshRenderDecomposition &Decomp, int32 MaxChunkSize=1<< 14)
Build per-material decomposition, and then split each of those into chunks of at most MaxChunkSize (actual chunk sizes will be highly variable and some may be very small...)
static GEOMETRYFRAMEWORK_API void BuildMaterialDecomposition (const FDynamicMesh3 *Mesh, const FComponentMaterialSet *MaterialSet, FMeshRenderDecomposition &Decomp)
Build decomposition with one group for each MaterialID of mesh.
Data Fields
TArray< TUniquePtr< FGroup > > Groups
TArray< int32 > TriangleToGroupMap
Mapping from TriangleID to Groups array index.
Detailed Description
FMeshRenderDecomposition represents a decomposition of a mesh into "chunks" of triangles, with associated materials.
This is passed to the rendering components to split a mesh into multiple RenderBuffers, for more efficient updating.
Definition at line 19 of file MeshRenderDecomposition.h.
Constructor & Destructor Documentation
FMeshRenderDecomposition() [1/3]
FMeshRenderDecomposition::FMeshRenderDecomposition (FMeshRenderDecomposition &&) default
References FMeshRenderDecomposition().
Referenced by FMeshRenderDecomposition(), FMeshRenderDecomposition(), BuildChunkedDecomposition(), BuildMaterialDecomposition(), operator=(), and operator=().
FMeshRenderDecomposition() [2/3]
FMeshRenderDecomposition::FMeshRenderDecomposition () default
FMeshRenderDecomposition() [3/3]
FMeshRenderDecomposition::FMeshRenderDecomposition (const FMeshRenderDecomposition &) delete
References FMeshRenderDecomposition().
Member Function Documentation
AppendGroup()
int32 FMeshRenderDecomposition::AppendGroup () inline
Definition at line 51 of file MeshRenderDecomposition.h.
References Groups, and MakeUnique().
BuildAssociations()
GEOMETRYFRAMEWORK_API void FMeshRenderDecomposition::BuildAssociations (const FDynamicMesh3 * Mesh)
Construct mappings between mesh and groups (eg TriangleToGroupMap)
References Mesh.
BuildChunkedDecomposition()
GEOMETRYFRAMEWORK_API void FMeshRenderDecomposition::BuildChunkedDecomposition (const FDynamicMesh3 * Mesh, const FComponentMaterialSet * MaterialSet, FMeshRenderDecomposition & Decomp, int32 MaxChunkSize = 1<< 14) static
Build per-material decomposition, and then split each of those into chunks of at most MaxChunkSize (actual chunk sizes will be highly variable and some may be very small...)
References FMeshRenderDecomposition(), and Mesh.
BuildMaterialDecomposition()
GEOMETRYFRAMEWORK_API void FMeshRenderDecomposition::BuildMaterialDecomposition (const FDynamicMesh3 * Mesh, const FComponentMaterialSet * MaterialSet, FMeshRenderDecomposition & Decomp) static
Build decomposition with one group for each MaterialID of mesh.
References FMeshRenderDecomposition(), and Mesh.
GetGroup() [1/2]
FGroup & FMeshRenderDecomposition::GetGroup (int32 Index) inline
Definition at line 69 of file MeshRenderDecomposition.h.
References Groups.
GetGroup() [2/2]
const FGroup & FMeshRenderDecomposition::GetGroup (int32 Index) const inline
Definition at line 74 of file MeshRenderDecomposition.h.
References Groups.
GetGroupForTriangle()
int32 FMeshRenderDecomposition::GetGroupForTriangle (int32 TriangleID) const inline
Definition at line 79 of file MeshRenderDecomposition.h.
References TriangleToGroupMap.
Initialize()
void FMeshRenderDecomposition::Initialize (int32 Count) inline
Definition at line 42 of file MeshRenderDecomposition.h.
References Count, Groups, and MakeUnique().
IsGroup()
bool FMeshRenderDecomposition::IsGroup (int32 Index) const inline
Definition at line 64 of file MeshRenderDecomposition.h.
References Groups.
Num()
int32 FMeshRenderDecomposition::Num () const inline
Definition at line 59 of file MeshRenderDecomposition.h.
References Groups.
operator=() [1/2]
FMeshRenderDecomposition & FMeshRenderDecomposition::operator= (const FMeshRenderDecomposition &) delete
References FMeshRenderDecomposition().
operator=() [2/2]
FMeshRenderDecomposition & FMeshRenderDecomposition::operator= (FMeshRenderDecomposition &&) default
References FMeshRenderDecomposition().
Field Documentation
Groups
TArray<TUniquePtr<FGroup> > FMeshRenderDecomposition::Groups
Definition at line 36 of file MeshRenderDecomposition.h.
Referenced by AppendGroup(), GetGroup(), GetGroup(), Initialize(), IsGroup(), and Num().
TriangleToGroupMap
TArray<int32> FMeshRenderDecomposition::TriangleToGroupMap
Mapping from TriangleID to Groups array index.
Initialized by BuildAssociations()
Definition at line 40 of file MeshRenderDecomposition.h.
Referenced by GetGroupForTriangle().
The documentation for this class was generated from the following file:
MeshRenderDecomposition.h