Unreal Engine 5.6 C++ API: FMovieSceneChannelValueSetter Struct Reference
FMovieSceneChannelValueSetter Struct Reference
#include "KeyframeTrackEditor.h"
Public Member Functions
FMovieSceneChannelValueSetter (const FMovieSceneChannelValueSetter &)=delete
FMovieSceneChannelValueSetter (FMovieSceneChannelValueSetter &&)=default
IImpl * operator-> ()
const IImpl * operator-> () const
FMovieSceneChannelValueSetter & operator= (const FMovieSceneChannelValueSetter &)=delete
FMovieSceneChannelValueSetter & operator= (FMovieSceneChannelValueSetter &&)=default
Static Public Member Functions
template<typename ChannelType, typename ValueType>
static FMovieSceneChannelValueSetter Create (int32 ChannelIndex, ValueType InNewValue, bool bAddKey)
Templated construction function that can add a key (and potentially also set a default) for the specified channel and value.
Private Member Functions
FMovieSceneChannelValueSetter ()
Private Attributes
TInlineValue< IImpl > Impl
Detailed Description
Definition at line 411 of file KeyframeTrackEditor.h.
Constructor & Destructor Documentation
FMovieSceneChannelValueSetter() [1/3]
FMovieSceneChannelValueSetter::FMovieSceneChannelValueSetter (const FMovieSceneChannelValueSetter &) delete
References FMovieSceneChannelValueSetter().
Referenced by FMovieSceneChannelValueSetter(), FMovieSceneChannelValueSetter(), Create(), operator=(), and operator=().
FMovieSceneChannelValueSetter() [2/3]
FMovieSceneChannelValueSetter::FMovieSceneChannelValueSetter (FMovieSceneChannelValueSetter &&) default
References FMovieSceneChannelValueSetter().
FMovieSceneChannelValueSetter() [3/3]
FMovieSceneChannelValueSetter::FMovieSceneChannelValueSetter () inline private
Definition at line 441 of file KeyframeTrackEditor.h.
Member Function Documentation
Create()
template<typename ChannelType, typename ValueType> FMovieSceneChannelValueSetter FMovieSceneChannelValueSetter::Create (int32 ChannelIndex, ValueType InNewValue, bool bAddKey) inline static
Templated construction function that can add a key (and potentially also set a default) for the specified channel and value.
Definition at line 421 of file KeyframeTrackEditor.h.
References FMovieSceneChannelValueSetter(), Forward(), Impl, and MoveTemp().
operator->() [1/2]
IImpl * FMovieSceneChannelValueSetter::operator-> () inline
Definition at line 429 of file KeyframeTrackEditor.h.
operator->() [2/2]
const IImpl * FMovieSceneChannelValueSetter::operator-> () const inline
Definition at line 434 of file KeyframeTrackEditor.h.
operator=() [1/2]
FMovieSceneChannelValueSetter & FMovieSceneChannelValueSetter::operator= (const FMovieSceneChannelValueSetter &) delete
References FMovieSceneChannelValueSetter().
operator=() [2/2]
FMovieSceneChannelValueSetter & FMovieSceneChannelValueSetter::operator= (FMovieSceneChannelValueSetter &&) default
References FMovieSceneChannelValueSetter().
Field Documentation
Impl
TInlineValue<IImpl> FMovieSceneChannelValueSetter::Impl private
Definition at line 445 of file KeyframeTrackEditor.h.
Referenced by Create().
The documentation for this struct was generated from the following file:
KeyframeTrackEditor.h