Unreal Engine 5.6 C++ API: Metasound::TDataValueReference< DataType > Class Template Reference
Metasound::TDataValueReference< DataType > Class Template Reference
TDataValueReference represents a constant value and provides read only access.
#include "MetasoundDataReference.h"
Public Member Functions
TDataValueReference (const TDataValueReference< DataType > &Other)=default
Enable copy constructor.
TDataValueReference (TDataValueReference< DataType > &&Other)=default
Enable move constructor.
virtual TUniquePtr< IDataReference > Clone () const override
Create a clone of this parameter reference.
FORCEINLINE const DataType * Get () const
operator TDataReadReference< DataType > () const
Implicit conversion to a readable parameter.
FORCEINLINE const DataType & operator* () const
Const access to the underlying parameter object.
FORCEINLINE const DataType * operator-> () const
Const access to the underlying parameter object.
TDataValueReference< DataType > & operator= (const TDataValueReference< DataType > &Other)=default
Enable assignment operator.
TDataValueReference< DataType > & operator= (TDataValueReference< DataType > &&Other)=default
Enable move operator.
Public Member Functions inherited from Metasound::TDataReference< DataType >
TDataReference (const TDataReference< DataType > &Other)=default
Enable copy constructor.
TDataReference (TDataReference< DataType > &&Other)=default
Enable move constructor.
virtual const void *const GetDataTypeId () const override
Return the ID of the underlying type.
virtual const FName & GetDataTypeName () const override
Return the name of the underlying type.
virtual void * GetRaw () const override
Return a raw pointer to the data.
TDataReference< DataType > & operator= (const TDataReference< DataType > &Other)=default
Enable copy operator.
TDataReference< DataType > & operator= (TDataReference< DataType > &&Other)=default
Enable move operator.
Public Member Functions inherited from Metasound::IDataReference
virtual ~IDataReference ()=default
Static Public Member Functions
template<typename... ArgTypes>
static TDataValueReference< DataType > CreateNew (ArgTypes &&... Args)
This should be used to construct a new DataType object and return this TDataValueReference as a wrapper around it.
Static Public Member Functions inherited from Metasound::TDataReference< DataType >
template<typename... ArgTypes>
static TDataReference< DataType > CreateNew (ArgTypes &&... Args)
This should be used to construct a new DataType object and return this TDataReference as a wrapper around it.
Private Member Functions
TDataValueReference (const TDataReference< DataType > &InRef)
template<typename... ArgTypes>
TDataValueReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args)
Friends
template<typename T>
TDataValueReference< T > ValueCast (const TDataReadReference< T > &InRef)
Cast a TDataReadReference to a TDataValueReference.
template<typename T>
TDataValueReference< T > ValueCast (const TDataWriteReference< T > &InRef)
Cast a TDataWriteReference to a TDataValueReference.
Additional Inherited Members
Public Types inherited from Metasound::TDataReference< DataType >
typedef TDataReferenceTypeInfo< DataType > FInfoType
Static Public Attributes inherited from Metasound::IDataReference
static METASOUNDGRAPHCORE_API const FName RouterName
Protected Types inherited from Metasound::TDataReference< DataType >
typedef TSharedRef< DataType, ESPMode::NotThreadSafe > FRefType
Protected Member Functions inherited from Metasound::TDataReference< DataType >
template<typename... ArgTypes>
TDataReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args)
This constructor forwards arguments to an underlying constructor.
Protected Attributes inherited from Metasound::TDataReference< DataType >
FRefType ObjectReference
Detailed Description
template<typename DataType>
class Metasound::TDataValueReference< DataType >
TDataValueReference represents a constant value and provides read only access.
A TDataValueReference can never change value.
Definition at line 249 of file MetasoundDataReference.h.
Constructor & Destructor Documentation
TDataValueReference() [1/4]
template<typename DataType> template<typename... ArgTypes> Metasound::TDataValueReference< DataType >::TDataValueReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args) inline private
Definition at line 253 of file MetasoundDataReference.h.
References Metasound::TDataReference< DataType >::TDataReference(), and Forward().
Referenced by TDataValueReference(), TDataValueReference(), Clone(), CreateNew(), operator=(), operator=(), ValueCast, and ValueCast.
TDataValueReference() [2/4]
template<typename DataType> Metasound::TDataValueReference< DataType >::TDataValueReference (const TDataReference< DataType > & InRef) inline private
Definition at line 259 of file MetasoundDataReference.h.
References Metasound::TDataReference< DataType >::TDataReference().
TDataValueReference() [3/4]
template<typename DataType> Metasound::TDataValueReference< DataType >::TDataValueReference (const TDataValueReference< DataType > & Other) default
Enable copy constructor.
References TDataValueReference(), and Other.
TDataValueReference() [4/4]
template<typename DataType> Metasound::TDataValueReference< DataType >::TDataValueReference (TDataValueReference< DataType > && Other) default
Enable move constructor.
References TDataValueReference(), and Other.
Member Function Documentation
Clone()
template<typename DataType> virtual TUniquePtr< IDataReference > Metasound::TDataValueReference< DataType >::Clone () const inline override virtual
Create a clone of this parameter reference.
Implements Metasound::IDataReference.
Definition at line 316 of file MetasoundDataReference.h.
References TDataValueReference(), and MakeUnique().
CreateNew()
template<typename DataType> template<typename... ArgTypes> TDataValueReference< DataType > Metasound::TDataValueReference< DataType >::CreateNew (ArgTypes &&... Args) inline static
This should be used to construct a new DataType object and return this TDataValueReference as a wrapper around it.
Definition at line 274 of file MetasoundDataReference.h.
References TDataValueReference(), Forward(), and Metasound::NewObject.
Referenced by Metasound::VertexDataPrivate::TFactoryFacade< TDataValueReference< DataType > >::CreateWithArgs(), Metasound::VertexDataPrivate::FInputBinding::SetValue(), and Metasound::VertexDataPrivate::FOutputBinding::SetValue().
Get()
template<typename DataType> FORCEINLINE const DataType * Metasound::TDataValueReference< DataType >::Get () const inline
Definition at line 310 of file MetasoundDataReference.h.
References FORCEINLINE, and Metasound::TDataReference< DataType >::ObjectReference.
operator TDataReadReference< DataType >()
template<typename DataType> Metasound::TDataValueReference< DataType >::operator TDataReadReference< DataType > () const inline
Implicit conversion to a readable parameter.
Definition at line 293 of file MetasoundDataReference.h.
operator*()
template<typename DataType> FORCEINLINE const DataType & Metasound::TDataValueReference< DataType >::operator* () const inline
Const access to the underlying parameter object.
Definition at line 299 of file MetasoundDataReference.h.
References FORCEINLINE, and Metasound::TDataReference< DataType >::ObjectReference.
operator->()
template<typename DataType> FORCEINLINE const DataType * Metasound::TDataValueReference< DataType >::operator-> () const inline
Const access to the underlying parameter object.
Definition at line 305 of file MetasoundDataReference.h.
References FORCEINLINE, and Metasound::TDataReference< DataType >::ObjectReference.
operator=() [1/2]
template<typename DataType> TDataValueReference< DataType > & Metasound::TDataValueReference< DataType >::operator= (const TDataValueReference< DataType > & Other) default
Enable assignment operator.
References TDataValueReference(), and Other.
operator=() [2/2]
template<typename DataType> TDataValueReference< DataType > & Metasound::TDataValueReference< DataType >::operator= (TDataValueReference< DataType > && Other) default
Enable move operator.
References TDataValueReference(), and Other.
Friends And Related Symbol Documentation
ValueCast [1/2]
template<typename DataType> template<typename T> TDataValueReference< T > ValueCast (const TDataReadReference< T > & InRef) friend
Cast a TDataReadReference to a TDataValueReference.
In general TDataReadReferences should not be converted into TDataValueReferences unless the caller can be certain that no other TDataWriteReference exists for the underlying parameter. Having a TDataWriteReferences to an existing TDataValueReference can cause confusing behavior as values references are not expected to change value.
Definition at line 332 of file MetasoundDataReference.h.
References TDataValueReference().
ValueCast [2/2]
template<typename DataType> template<typename T> TDataValueReference< T > ValueCast (const TDataWriteReference< T > & InRef) friend
Cast a TDataWriteReference to a TDataValueReference.
In general TDataWriteReferences should never beconverted into TDataValueReferences unless the caller can be certain that no other TDataWriteReference exists for the underlying parameter. Having a TDataWriteReferences to an existing TDataValueReference can cause confusing behavior as values references are not expected to change value.
Definition at line 345 of file MetasoundDataReference.h.
References TDataValueReference().
The documentation for this class was generated from the following file:
MetasoundDataReference.h