Unreal Engine 5.6 C++ API: IVPBookmarkProvider Class Reference
IVPBookmarkProvider Class Reference
#include "IVPBookmarkProvider.h"
Private Member Functions
UFUNCTION () void GenerateBookmarkName()
UFUNCTION () void HideBookmarkSplineMeshIndicator()
GENERATED_BODY() public UFUNCTION () void OnBookmarkChanged(UVPBookmark *Bookmark)
UFUNCTION () void UpdateBookmarkSplineMeshIndicator()
Additional Inherited Members
Public Types inherited from IInterface
typedef UInterface UClassType
Protected Member Functions inherited from IInterface
virtual ~IInterface ()
Detailed Description
Definition at line 20 of file IVPBookmarkProvider.h.
Member Function Documentation
UFUNCTION() [1/4]
IVPBookmarkProvider::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [2/4]
IVPBookmarkProvider::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [3/4]
GENERATED_BODY() public IVPBookmarkProvider::UFUNCTION () private
References Category.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/4]
IVPBookmarkProvider::UFUNCTION () private
References Category, and UFUNCTION().
The documentation for this class was generated from the following file:
IVPBookmarkProvider.h