Unreal Engine 5.6 C++ API: MovieSceneTimeTransform.h File Reference
MovieSceneTimeTransform.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Misc/FrameTime.h"
#include "MovieSceneTimeTransform.generated.h"
Functions
FString LexToString (const FMovieSceneTimeTransform &InTransform)
Convert a FFrameTime into a string.
FMovieSceneTimeTransform operator* (const FMovieSceneTimeTransform &LHS, const FMovieSceneTimeTransform &RHS)
Multiply 2 transforms together, resulting in a single transform that gets from RHS parent to LHS space.
TRange< FFrameNumber > operator* (const TRange< FFrameNumber > &LHS, const FMovieSceneTimeTransform &RHS)
template<typename T>
TRange< T > operator* (const TRange< T > &LHS, const FMovieSceneTimeTransform &RHS)
Transform a time range by a sequence transform.
FFrameTime operator* (FFrameTime InTime, const FMovieSceneTimeTransform &RHS)
Transform a time by a sequence transform.
FFrameTime & operator*= (FFrameTime &InTime, const FMovieSceneTimeTransform &RHS)
Transform a time by a sequence transform.
template<typename T>
TRange< T > & operator*= (TRange< T > &LHS, const FMovieSceneTimeTransform &RHS)
Transform a time range by a sequence transform.
USTRUCT () struct FMovieSceneTimeTransform
Movie scene sequence transform class that transforms from one time-space to another.
Function Documentation
LexToString()
FString LexToString (const FMovieSceneTimeTransform & InTransform) inline
Convert a FFrameTime into a string.
Definition at line 188 of file MovieSceneTimeTransform.h.
References TEXT.
operator*() [1/4]
FMovieSceneTimeTransform operator* (const FMovieSceneTimeTransform & LHS, const FMovieSceneTimeTransform & RHS) inline
Multiply 2 transforms together, resulting in a single transform that gets from RHS parent to LHS space.
Note
Transforms apply from right to left
Definition at line 173 of file MovieSceneTimeTransform.h.
operator*() [2/4]
TRange< FFrameNumber > operator* (const TRange< FFrameNumber > & LHS, const FMovieSceneTimeTransform & RHS) inline
Definition at line 140 of file MovieSceneTimeTransform.h.
operator*() [3/4]
template<typename T> TRange< T > operator* (const TRange< T > & LHS, const FMovieSceneTimeTransform & RHS)
Transform a time range by a sequence transform.
Parameters
LHS The time range to transform
RHS The transform
Definition at line 124 of file MovieSceneTimeTransform.h.
operator*() [4/4]
FFrameTime operator* (FFrameTime InTime, const FMovieSceneTimeTransform & RHS) inline
Transform a time by a sequence transform.
Parameters
InTime The time to transform
RHS The transform
Definition at line 89 of file MovieSceneTimeTransform.h.
References InTime.
operator*=() [1/2]
FFrameTime & operator*= (FFrameTime & InTime, const FMovieSceneTimeTransform & RHS) inline
Transform a time by a sequence transform.
Parameters
InTime The time to transform
RHS The transform
Definition at line 111 of file MovieSceneTimeTransform.h.
References InTime.
operator*=() [2/2]
template<typename T> TRange< T > & operator*= (TRange< T > & LHS, const FMovieSceneTimeTransform & RHS)
Transform a time range by a sequence transform.
Parameters
InTime The time range to transform
RHS The transform
Definition at line 163 of file MovieSceneTimeTransform.h.
USTRUCT()
USTRUCT ()
Movie scene sequence transform class that transforms from one time-space to another.
Note
The transform can be thought of as the top row of a 2x2 matrix, where the bottom row is the identity: | TimeScale Offset | | 0 1 |
As such, traditional matrix mathematics can be applied to transform between different sequence's time-spaces.
Transforms apply time scale first, and then offset.
Default construction to the identity transform
Construction from an offset, and a scale
Parameters
InOffset The offset to translate by
InTimeScale The timescale. For instance, if a sequence is playing twice as fast, pass 2.f
Returns whether this transform is an identity transform.
Retrieve the inverse of this transform
The sequence's time scale (or play rate)
Scalar frame offset applied after the scale
Definition at line 21 of file MovieSceneTimeTransform.h.
References A, B, checkf, GENERATED_BODY, Inverse(), FMath::IsNearlyEqual(), FMath::IsNearlyZero(), operator!=(), operator==(), TEXT, and UPROPERTY.