Unreal Engine 5.6 C++ API: FCoreRedirect Struct Reference
FCoreRedirect Struct Reference
A single redirection from an old name to a new name, parsed out of an ini file.
#include "CoreRedirects.h"
Public Member Functions
FCoreRedirect (ECoreRedirectFlags InRedirectFlags, const FCoreRedirectObjectName &InOldName, const FCoreRedirectObjectName &InNewName)
Construct parsed out object names.
FCoreRedirect (ECoreRedirectFlags InRedirectFlags, FString InOldName, FString InNewName)
Construct from name strings, which may get parsed out.
void AppendHash (FBlake3 &Hasher) const
Update Hasher with all fields from this.
int Compare (const FCoreRedirect &Other) const
Returns -,0,+ based on a full lexical-fnames compare of all fields on the two CoreRedirects.
FName GetSearchKey () const
Returns the name used as the key into the acceleration map.
bool HasValueChanges () const
Returns true if this has value redirects.
bool IdenticalMatchRules (const FCoreRedirect &Other) const
See if search criteria is identical.
bool IsSubstringMatch () const
Returns true if this is a substring match.
bool Matches (const FCoreRedirectObjectName &InName, ECoreRedirectMatchFlags MatchFlags=ECoreRedirectMatchFlags::None) const
Returns true if the passed in name matches requirements.
bool Matches (ECoreRedirectFlags InFlags, const FCoreRedirectObjectName &InName, ECoreRedirectMatchFlags MatchFlags=ECoreRedirectMatchFlags::None) const
Returns true if the passed in name and flags match requirements.
void NormalizeNewName ()
Normalizes NewName with data from OldName.
const TCHAR * ParseValueChanges (const TCHAR *Buffer)
Parses a char buffer into the ValueChanges map.
FCoreRedirectObjectName RedirectName (const FCoreRedirectObjectName &OldObjectName) const
Convert to new names based on mapping.
Data Fields
FCoreRedirectObjectName NewName
Name to replace with.
FCoreRedirectObjectName OldName
Name of object to look for.
FCoreRedirectObjectName OverrideClassName
Change the class of this object when doing a redirect.
ECoreRedirectFlags RedirectFlags
Flags of this redirect.
TMap< FString, FString > ValueChanges
Map of value changes, from old value to new value.
Private Member Functions
bool IsPrefixMatch () const
Returns true if this is a prefix match.
bool IsSuffixMatch () const
Returns true if this is a prefix match.
bool IsWildcardMatch () const
Returns true if this is a Wildcard match (substring, prefix or suffix)
FCoreRedirectObjectName RedirectName (const FCoreRedirectObjectName &OldObjectName, bool bIsKnownToMatch) const
Friends
struct FCoreRedirects
Detailed Description
A single redirection from an old name to a new name, parsed out of an ini file.
Definition at line 219 of file CoreRedirects.h.
Constructor & Destructor Documentation
FCoreRedirect() [1/2]
FCoreRedirect::FCoreRedirect (ECoreRedirectFlags InRedirectFlags, FString InOldName, FString InNewName) inline
Construct from name strings, which may get parsed out.
Definition at line 237 of file CoreRedirects.h.
References NewName, NormalizeNewName(), OldName, and RedirectFlags.
Referenced by Compare(), and IdenticalMatchRules().
FCoreRedirect() [2/2]
FCoreRedirect::FCoreRedirect (ECoreRedirectFlags InRedirectFlags, const FCoreRedirectObjectName & InOldName, const FCoreRedirectObjectName & InNewName) inline
Construct parsed out object names.
Definition at line 244 of file CoreRedirects.h.
References NewName, NormalizeNewName(), OldName, and RedirectFlags.
Member Function Documentation
AppendHash()
void FCoreRedirect::AppendHash (FBlake3 & Hasher) const
Update Hasher with all fields from this.
Compare()
int FCoreRedirect::Compare (const FCoreRedirect & Other) const
Returns -,0,+ based on a full lexical-fnames compare of all fields on the two CoreRedirects.
References FCoreRedirect(), and Other.
GetSearchKey()
FName FCoreRedirect::GetSearchKey () const inline
Returns the name used as the key into the acceleration map.
Definition at line 276 of file CoreRedirects.h.
References OldName, and RedirectFlags.
HasValueChanges()
bool FCoreRedirect::HasValueChanges () const
Returns true if this has value redirects.
IdenticalMatchRules()
bool FCoreRedirect::IdenticalMatchRules (const FCoreRedirect & Other) const
See if search criteria is identical.
References FCoreRedirect(), and Other.
IsPrefixMatch()
bool FCoreRedirect::IsPrefixMatch () const inline private
Returns true if this is a prefix match.
Definition at line 300 of file CoreRedirects.h.
References EnumHasAllFlags(), Option_MatchPrefix, and RedirectFlags.
IsSubstringMatch()
bool FCoreRedirect::IsSubstringMatch () const
Returns true if this is a substring match.
IsSuffixMatch()
bool FCoreRedirect::IsSuffixMatch () const inline private
Returns true if this is a prefix match.
Definition at line 306 of file CoreRedirects.h.
References EnumHasAllFlags(), Option_MatchSuffix, and RedirectFlags.
IsWildcardMatch()
bool FCoreRedirect::IsWildcardMatch () const inline private
Returns true if this is a Wildcard match (substring, prefix or suffix)
Definition at line 294 of file CoreRedirects.h.
References EnumHasAnyFlags(), Option_MatchWildcardMask, and RedirectFlags.
Matches() [1/2]
bool FCoreRedirect::Matches (const FCoreRedirectObjectName & InName, ECoreRedirectMatchFlags MatchFlags = ECoreRedirectMatchFlags::None) const
Returns true if the passed in name matches requirements.
References InName, and None.
Matches() [2/2]
bool FCoreRedirect::Matches (ECoreRedirectFlags InFlags, const FCoreRedirectObjectName & InName, ECoreRedirectMatchFlags MatchFlags = ECoreRedirectMatchFlags::None) const
Returns true if the passed in name and flags match requirements.
References InName, and None.
NormalizeNewName()
void FCoreRedirect::NormalizeNewName ()
Normalizes NewName with data from OldName.
Referenced by FCoreRedirect(), and FCoreRedirect().
ParseValueChanges()
const TCHAR * FCoreRedirect::ParseValueChanges (const TCHAR * Buffer)
Parses a char buffer into the ValueChanges map.
References Buffer.
RedirectName() [1/2]
FCoreRedirectObjectName FCoreRedirect::RedirectName (const FCoreRedirectObjectName & OldObjectName) const
Convert to new names based on mapping.
RedirectName() [2/2]
FCoreRedirectObjectName FCoreRedirect::RedirectName (const FCoreRedirectObjectName & OldObjectName, bool bIsKnownToMatch) const private
Friends And Related Symbol Documentation
FCoreRedirects
friend struct FCoreRedirects friend
Definition at line 287 of file CoreRedirects.h.
References FCoreRedirects.
Referenced by FCoreRedirects.
Field Documentation
NewName
FCoreRedirectObjectName FCoreRedirect::NewName
Name to replace with.
Definition at line 228 of file CoreRedirects.h.
Referenced by FCoreRedirect(), and FCoreRedirect().
OldName
FCoreRedirectObjectName FCoreRedirect::OldName
Name of object to look for.
Definition at line 225 of file CoreRedirects.h.
Referenced by FCoreRedirect(), FCoreRedirect(), and GetSearchKey().
OverrideClassName
FCoreRedirectObjectName FCoreRedirect::OverrideClassName
Change the class of this object when doing a redirect.
Definition at line 231 of file CoreRedirects.h.
RedirectFlags
ECoreRedirectFlags FCoreRedirect::RedirectFlags
Flags of this redirect.
Definition at line 222 of file CoreRedirects.h.
Referenced by FCoreRedirect(), FCoreRedirect(), GetSearchKey(), IsPrefixMatch(), IsSuffixMatch(), and IsWildcardMatch().
ValueChanges
TMap<FString, FString> FCoreRedirect::ValueChanges
Map of value changes, from old value to new value.
Definition at line 234 of file CoreRedirects.h.
The documentation for this struct was generated from the following file:
CoreRedirects.h