Unreal Engine 5.6 C++ API: FInputCaptureRequest Struct Reference
FInputCaptureRequest Struct Reference
UInputBehavior returns an FInputCaptureRequest from WantsCapture() to indicate whether it wants to capture or ignore an input event.
#include "InputBehavior.h"
Public Member Functions
FInputCaptureRequest (EInputCaptureRequestType type, UInputBehavior *behavior, EInputCaptureSide whichSide, double hitDepth=TNumericLimits< double >::Max())
Static Public Member Functions
static FInputCaptureRequest Begin (UInputBehavior *behavior, EInputCaptureSide whichSide, double hitDepth=TNumericLimits< double >::Max())
Create a Begin-capture request.
static FInputCaptureRequest Ignore ()
Create an ignore-capture request.
Data Fields
double HitDepth
Depth along hit-test ray.
void * Owner
Owner of the requesting behavior.
EInputCaptureSide Side
Which side does request want to capture on.
UInputBehavior * Source
Which input behavior generated this request.
EInputCaptureRequestType Type
What type of capture request is this (Begin or Ignore)
Friends
bool operator< (const FInputCaptureRequest &l, const FInputCaptureRequest &r)
Detailed Description
UInputBehavior returns an FInputCaptureRequest from WantsCapture() to indicate whether it wants to capture or ignore an input event.
Definition at line 66 of file InputBehavior.h.
Constructor & Destructor Documentation
FInputCaptureRequest()
FInputCaptureRequest::FInputCaptureRequest (EInputCaptureRequestType type, UInputBehavior * behavior, EInputCaptureSide whichSide, double hitDepth = TNumericLimits<double>::Max()) inline
Definition at line 81 of file InputBehavior.h.
Referenced by Begin(), Ignore(), and operator<.
Member Function Documentation
Begin()
FInputCaptureRequest FInputCaptureRequest::Begin (UInputBehavior * behavior, EInputCaptureSide whichSide, double hitDepth = TNumericLimits<double>::Max()) inline static
Create a Begin-capture request.
Definition at line 96 of file InputBehavior.h.
References FInputCaptureRequest().
Ignore()
FInputCaptureRequest FInputCaptureRequest::Ignore () inline static
Create an ignore-capture request.
Definition at line 104 of file InputBehavior.h.
References FInputCaptureRequest().
Friends And Related Symbol Documentation
operator<
bool operator< (const FInputCaptureRequest & l, const FInputCaptureRequest & r) friend
References FInputCaptureRequest().
Field Documentation
HitDepth
double FInputCaptureRequest::HitDepth
Depth along hit-test ray.
Definition at line 76 of file InputBehavior.h.
Owner
void* FInputCaptureRequest::Owner
Owner of the requesting behavior.
Behavior doesn't know this, so this is initialized to null
Definition at line 79 of file InputBehavior.h.
Side
EInputCaptureSide FInputCaptureRequest::Side
Which side does request want to capture on.
Definition at line 73 of file InputBehavior.h.
Source
UInputBehavior* FInputCaptureRequest::Source
Which input behavior generated this request.
Definition at line 69 of file InputBehavior.h.
Type
EInputCaptureRequestType FInputCaptureRequest::Type
What type of capture request is this (Begin or Ignore)
Definition at line 71 of file InputBehavior.h.
The documentation for this struct was generated from the following file:
InputBehavior.h