Unreal Engine 5.6 C++ API: UE::Geometry::TMeshQueries< TriangleMeshType > Class Template Reference
UE::Geometry::TMeshQueries< TriangleMeshType > Class Template Reference
#include "MeshQueries.h"
Public Member Functions
TMeshQueries ()=delete
Static Public Member Functions
static double AverageEdgeLength (const TriangleMeshType &Mesh)
Compute the mean edge length for the given mesh.
static void EdgeLengthStats (const TriangleMeshType &Mesh, double &MinEdgeLength, double &MaxEdgeLength, double &AverageEdgeLength, int NumSamples=0)
Compute the min, max, and mean edge lengths for the given mesh.
static void EdgeLengthStatsFromEdges (const TriangleMeshType &Mesh, const TArray< int > &Edges, double &MinEdgeLength, double &MaxEdgeLength, double &AverageEdgeLength)
Given a mesh and a subset of mesh edges, compute the min, max, and mean edge lengths.
static void ExpandVertexSelectionToNeighbors (const TriangleMeshType &Mesh, const TArray< int32 > &Selection, TArray< int32 > &ExpandedSelection, TMap< int32, int32 > &VIDToExpandedSelectionIdx)
Expand selection of vertices with one-ring neighbors.
static int FindHitTriangle_LinearSearch (const TriangleMeshType &Mesh, const FRay3d &Ray)
static void FindHitTriangles_LinearSearch (const TriangleMeshType &Mesh, const FRay3d &Ray, TArray< TPair< float, int > > &SortedHitTriangles)
static FIndex2i FindIntersectingTriangles_LinearSearch (const TriangleMeshType &Mesh1, const TriangleMeshType &Mesh2)
brute force search for any intersecting triangles on two meshes
static FVector3d FindNearestPoint_LinearSearch (const TriangleMeshType &Mesh, const FVector3d &P)
static int FindNearestTriangle_LinearSearch (const TriangleMeshType &Mesh, const FVector3d &P)
static void GetAllEdgeLengths (const TriangleMeshType &Mesh, TArray< double > &Lengths, double &TotalLength)
Compute the length for each edge and return the result as an array of Mesh.MaxEdgeID() size.
static FAxisAlignedBox3d GetBounds (const TriangleMeshType &Mesh)
static FVector3d GetMeshVerticesCentroid (const TriangleMeshType &Mesh)
Get the average of the mesh vertices.
template<typename EnumerableTriListType>
static FAxisAlignedBox3d GetTrianglesBounds (const TriangleMeshType &Mesh, const EnumerableTriListType &Triangles, const FTransform &Transform=FTransform::Identity)
static FAxisAlignedBox3d GetTriBounds (const TriangleMeshType &Mesh, int TID)
static FVector3d GetTriCentroid (const TriangleMeshType &Mesh, int TriIdx)
Compute triangle centroid.
static void GetTriNormalAreaCentroid (const TriangleMeshType &Mesh, int TriIdx, FVector3d &Normal, double &Area, FVector3d &Centroid)
Compute the normal, area, and centroid of a triangle all together.
static TArray< int32 > GetVertexSelectedTriangles (const TriangleMeshType &Mesh, const TArray< int32 > &Vertices)
Get triangles that contain at least on vertex in the Vertices array.
static FVector3d GetVertexWeightsOnTriangle (const TriangleMeshType &Mesh, int TriID, double TriArea, bool bWeightByArea, bool bWeightByAngle)
Retrieve the area and/or angle weights for each vertex of a triangle.
template<typename EnumerableTriListType>
static FAxisAlignedBox3d GetVerticesBounds (const TriangleMeshType &Mesh, const EnumerableTriListType &Vertices, const FTransform &Transform=FTransform::Identity)
static FVector2d GetVolumeArea (const TriangleMeshType &Mesh)
static FVector2d GetVolumeArea (const TriangleMeshType &Mesh, const TArray< int > &TriIndices)
static FVector2d GetVolumeAreaCenter (const TriangleMeshType &Mesh, FVector3d &OutCenterOfMass)
static double GetVolumeNonWatertight (const TriangleMeshType &Mesh, double DimScaleFactor=1)
Get the volume of a mesh using a method that is more robust to inputs with holes.
template<typename MeshSpatialType>
static double HausdorffDistance (const TriangleMeshType &MeshA, const MeshSpatialType &SpatialB)
Compute all vertex-to-surface distances in parallel.
template<typename MeshSpatialType>
static double HausdorffDistanceSerial (const TriangleMeshType &MeshA, const MeshSpatialType &SpatialB)
Compute all distances in serial, then a serial raw loop to find max.
static double MaxEdgeLength (const TriangleMeshType &Mesh)
Compute the longest edge length for the given mesh.
template<typename MeshSpatialType>
static void MeshDistanceStatistics (const TriangleMeshType &MeshA, const MeshSpatialType &SpatialB, const TriangleMeshType *MeshB, const MeshSpatialType *SpatialA, bool bSymmetric, double &MaxDistance, double &MinDistance, double &AverageDistance, double &RootMeanSqrDeviation)
Compute various statistics on distances between two meshes.
static double MinEdgeLength (const TriangleMeshType &Mesh)
Compute the shortest edge length for the given mesh.
template<typename RayType = FRay3d>
static FIntrRay3Triangle3d RayTriangleIntersection (const TriangleMeshType &Mesh, int TriIdx, const RayType &Ray)
convenience function to construct a IntrRay3Triangle3 object for a Mesh triangle
static double TotalEdgeLength (const TriangleMeshType &Mesh, const TArray< int > &Edges)
Given a mesh and a subset of mesh edges, compute the total length of all the edges.
static FDistPoint3Triangle3d TriangleDistance (const TriangleMeshType &Mesh, int TriIdx, FVector3d Point)
construct a DistPoint3Triangle3 object for a Mesh triangle
static FIntrRay3Triangle3d TriangleIntersection (const TriangleMeshType &Mesh, int TriIdx, const FRay3d &Ray)
convenience function to construct a IntrRay3Triangle3 object for a Mesh triangle
static double TriDistanceSqr (const TriangleMeshType &Mesh, int TriIdx, const FVector3d &Point)
Compute distance from Point to triangle in Mesh, with minimal extra objects/etc.
template<typename MeshSpatialType>
static double TwoSidedHausdorffDistance (const TriangleMeshType &MeshA, const MeshSpatialType &SpatialA, const TriangleMeshType &MeshB, const MeshSpatialType &SpatialB)
Because Hausdorff distance is not symmetric, we compute the maximum of the distances between two surfaces.
template<typename MeshSpatialType>
static double TwoSidedHausdorffDistanceSerial (const TriangleMeshType &MeshA, const MeshSpatialType &SpatialA, const TriangleMeshType &MeshB, const MeshSpatialType &SpatialB)
template<typename MeshSpatialType>
static void VertexToSurfaceDistances (const TriangleMeshType &MeshA, const MeshSpatialType &SpatialB, TArray< double > &Distances)
For each vertex on MeshA, compute the distance to the nearest point on the surface contained in SpatialB.
template<typename MeshSpatialType>
static void VertexToSurfaceDistancesSerial (const TriangleMeshType &MeshA, const MeshSpatialType &SpatialB, TArray< double > &Distances)
Compute all vertex-to-surface distances in serial. Should only be used for debugging the parallel version above!
Detailed Description
template<class TriangleMeshType>
class UE::Geometry::TMeshQueries< TriangleMeshType >
Definition at line 20 of file MeshQueries.h.
Constructor & Destructor Documentation
TMeshQueries()
template<class TriangleMeshType> UE::Geometry::TMeshQueries< TriangleMeshType >::TMeshQueries () delete
Member Function Documentation
AverageEdgeLength()
template<class TriangleMeshType> double UE::Geometry::TMeshQueries< TriangleMeshType >::AverageEdgeLength (const TriangleMeshType & Mesh) inline static
Compute the mean edge length for the given mesh.
Definition at line 483 of file MeshQueries.h.
References UE::Geometry::Mesh, and Algo::TransformAccumulate().
Referenced by UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeFirstPass(), EdgeLengthStats(), and EdgeLengthStatsFromEdges().
EdgeLengthStats()
template<class TriangleMeshType> void UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStats (const TriangleMeshType & Mesh, double & MinEdgeLength, double & MaxEdgeLength, double & AverageEdgeLength, int NumSamples = 0) inline static
Compute the min, max, and mean edge lengths for the given mesh.
Optionally, choose a subest of size NumSamples and compute stats of that subset.
Definition at line 586 of file MeshQueries.h.
References A, AverageEdgeLength(), B, BIG_NUMBER, Distance, UE::Geometry::Length(), MaxEdgeLength(), UE::Geometry::Mesh, and MinEdgeLength().
EdgeLengthStatsFromEdges()
template<class TriangleMeshType> void UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStatsFromEdges (const TriangleMeshType & Mesh, const TArray< int > & Edges, double & MinEdgeLength, double & MaxEdgeLength, double & AverageEdgeLength) inline static
Given a mesh and a subset of mesh edges, compute the min, max, and mean edge lengths.
Definition at line 551 of file MeshQueries.h.
References A, AverageEdgeLength(), B, BIG_NUMBER, Distance, UE::Geometry::Length(), MaxEdgeLength(), UE::Geometry::Mesh, and MinEdgeLength().
ExpandVertexSelectionToNeighbors()
template<class TriangleMeshType> void UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors (const TriangleMeshType & Mesh, const TArray< int32 > & Selection, TArray< int32 > & ExpandedSelection, TMap< int32, int32 > & VIDToExpandedSelectionIdx) inline static
Expand selection of vertices with one-ring neighbors.
Parameters
Selection Array of Mesh vertex IDs.
ExpandedSelection All vertices in Selection plus one-ring neighbors for each vertex.
VIDToExpandedSelectionIdx Maps mesh Vertex ID to ExpandedSelection array index.
Definition at line 810 of file MeshQueries.h.
References TArray< InElementType, InAllocatorType >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Contains(), UE::Geometry::Mesh, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Reserve(), and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reserve().
FindHitTriangle_LinearSearch()
template<class TriangleMeshType> int UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangle_LinearSearch (const TriangleMeshType & Mesh, const FRay3d & Ray) inline static
Definition at line 371 of file MeshQueries.h.
References UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Find(), IndexConstants::InvalidID, UE::Geometry::Mesh, Ray, UE::Geometry::TIntrRay3Triangle3< Real, RayType >::RayParameter, and UE::Geometry::Triangle.
FindHitTriangles_LinearSearch()
template<class TriangleMeshType> void UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangles_LinearSearch (const TriangleMeshType & Mesh, const FRay3d & Ray, TArray< TPair< float, int > > & SortedHitTriangles) inline static
Definition at line 399 of file MeshQueries.h.
References A, B, UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Find(), UE::Geometry::Mesh, Ray, UE::Geometry::TIntrRay3Triangle3< Real, RayType >::RayParameter, and UE::Geometry::Triangle.
FindIntersectingTriangles_LinearSearch()
template<class TriangleMeshType> FIndex2i UE::Geometry::TMeshQueries< TriangleMeshType >::FindIntersectingTriangles_LinearSearch (const TriangleMeshType & Mesh1, const TriangleMeshType & Mesh2) inline static
brute force search for any intersecting triangles on two meshes
Returns
Index pair of IDs of first intersecting triangles found, or InvalidID if no intersection found
Definition at line 424 of file MeshQueries.h.
References UE::Geometry::TIntrTriangle3Triangle3< double >::Intersects(), UE::Geometry::FIndex2i::Invalid(), and UE::Geometry::TTriangle3< RealType >::V.
FindNearestPoint_LinearSearch()
template<class TriangleMeshType> FVector3d UE::Geometry::TMeshQueries< TriangleMeshType >::FindNearestPoint_LinearSearch (const TriangleMeshType & Mesh, const FVector3d & P) inline static
Returns
nearest point on Mesh to P, or P if nearest point was not found
Definition at line 340 of file MeshQueries.h.
References UE::Geometry::TDistPoint3Triangle3< Real >::ClosestTrianglePoint, UE::Geometry::TDistPoint3Triangle3< Real >::GetSquared(), UE::Geometry::Mesh, and TriangleDistance().
FindNearestTriangle_LinearSearch()
template<class TriangleMeshType> int UE::Geometry::TMeshQueries< TriangleMeshType >::FindNearestTriangle_LinearSearch (const TriangleMeshType & Mesh, const FVector3d & P) inline static
Definition at line 321 of file MeshQueries.h.
References IndexConstants::InvalidID, UE::Geometry::Mesh, and TriDistanceSqr().
GetAllEdgeLengths()
template<class TriangleMeshType> void UE::Geometry::TMeshQueries< TriangleMeshType >::GetAllEdgeLengths (const TriangleMeshType & Mesh, TArray< double > & Lengths, double & TotalLength) inline static
Compute the length for each edge and return the result as an array of Mesh.MaxEdgeID() size.
When mesh is not compact, the length of the missing edges is set to -1.0
Definition at line 469 of file MeshQueries.h.
References TArray< InElementType, InAllocatorType >::Init(), UE::Geometry::Length(), and UE::Geometry::Mesh.
GetBounds()
template<class TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TMeshQueries< TriangleMeshType >::GetBounds (const TriangleMeshType & Mesh) inline static
Definition at line 267 of file MeshQueries.h.
References UE::Geometry::TAxisAlignedBox3< RealType >::Contain(), UE::Geometry::TAxisAlignedBox3< double >::Empty(), and UE::Geometry::Mesh.
Referenced by UE::Geometry::TMeshSpatialSort< TriangleMeshType >::InitBounds().
GetMeshVerticesCentroid()
template<class TriangleMeshType> FVector3d UE::Geometry::TMeshQueries< TriangleMeshType >::GetMeshVerticesCentroid (const TriangleMeshType & Mesh) inline static
Get the average of the mesh vertices.
Definition at line 83 of file MeshQueries.h.
References UE::Geometry::Mesh.
Referenced by GetVolumeNonWatertight().
GetTrianglesBounds()
template<class TriangleMeshType> template<typename EnumerableTriListType> FAxisAlignedBox3d UE::Geometry::TMeshQueries< TriangleMeshType >::GetTrianglesBounds (const TriangleMeshType & Mesh, const EnumerableTriListType & Triangles, const FTransform & Transform = FTransform::Identity) inline static
Returns
bounding box of subset of triangles of Mesh
Definition at line 282 of file MeshQueries.h.
References A, B, UE::Geometry::TAxisAlignedBox3< RealType >::Contain(), UE::Geometry::TAxisAlignedBox3< double >::Empty(), UE::Math::TTransform< double >::Identity, UE::Geometry::Mesh, and UE::Geometry::Transform.
GetTriBounds()
template<class TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriBounds (const TriangleMeshType & Mesh, int TID) inline static
Definition at line 249 of file MeshQueries.h.
References UE::Geometry::FIndex3i::A, UE::Geometry::Mesh, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint().
GetTriCentroid()
template<class TriangleMeshType> FVector3d UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriCentroid (const TriangleMeshType & Mesh, int TriIdx) inline static
Compute triangle centroid.
Parameters
Mesh Mesh with triangle
TriIdx Index of triangle
Returns
Computed centroid
Definition at line 57 of file MeshQueries.h.
References UE::Geometry::Mesh, and UE::Geometry::Triangle.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown().
GetTriNormalAreaCentroid()
template<class TriangleMeshType> void UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriNormalAreaCentroid (const TriangleMeshType & Mesh, int TriIdx, FVector3d & Normal, double & Area, FVector3d & Centroid) inline static
Compute the normal, area, and centroid of a triangle all together.
Parameters
Mesh Mesh w/ triangle
TriIdx Index of triangle
Normal Computed normal (returned by reference)
Area Computed area (returned by reference)
Centroid Computed centroid (returned by reference)
Definition at line 72 of file MeshQueries.h.
References UE::Geometry::Area, UE::Geometry::Mesh, UE::Geometry::Normal, UE::Geometry::VectorUtil::NormalArea(), and UE::Geometry::Triangle.
Referenced by UE::Geometry::FMeshTriInfoCache::BuildTriInfoCache().
GetVertexSelectedTriangles()
template<class TriangleMeshType> TArray< int32 > UE::Geometry::TMeshQueries< TriangleMeshType >::GetVertexSelectedTriangles (const TriangleMeshType & Mesh, const TArray< int32 > & Vertices) inline static
Get triangles that contain at least on vertex in the Vertices array.
Parameters
Vertices Array of mesh vertex IDs.
Triangles Triangle IDs containing at least one vertex ID in Vertices.
Definition at line 788 of file MeshQueries.h.
References TSet< InElementType, KeyFuncs, Allocator >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Array(), UE::Geometry::Mesh, TSet< InElementType, KeyFuncs, Allocator >::Reserve(), and UE::Geometry::Vertices.
GetVertexWeightsOnTriangle()
template<class TriangleMeshType> FVector3d UE::Geometry::TMeshQueries< TriangleMeshType >::GetVertexWeightsOnTriangle (const TriangleMeshType & Mesh, int TriID, double TriArea, bool bWeightByArea, bool bWeightByAngle) inline static
Retrieve the area and/or angle weights for each vertex of a triangle.
Parameters
Mesh the mesh to query
TriID the triangle index of the mesh to query
TriArea the area of the triangle
bWeightByArea if true, include weighting by the area of the triangle
bWeightByAngle if true, include weighting by the interior angles of the triangle
Definition at line 768 of file MeshQueries.h.
References UE::Geometry::Mesh, and UE::Math::TVector< double >::One().
GetVerticesBounds()
template<class TriangleMeshType> template<typename EnumerableTriListType> FAxisAlignedBox3d UE::Geometry::TMeshQueries< TriangleMeshType >::GetVerticesBounds (const TriangleMeshType & Mesh, const EnumerableTriListType & Vertices, const FTransform & Transform = FTransform::Identity) inline static
Returns
bounding box of subset of vertices of Mesh
Definition at line 304 of file MeshQueries.h.
References UE::Geometry::TAxisAlignedBox3< RealType >::Contain(), UE::Geometry::TAxisAlignedBox3< double >::Empty(), UE::Math::TTransform< double >::Identity, UE::Geometry::Mesh, UE::Geometry::Transform, and UE::Geometry::Vertices.
GetVolumeArea() [1/2]
template<class TriangleMeshType> FVector2d UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea (const TriangleMeshType & Mesh) inline static
Definition at line 134 of file MeshQueries.h.
References UE::Geometry::Area, UE::Math::TVector< T >::Cross(), UE::Math::TVector< T >::Length(), UE::Geometry::Mesh, UE::Geometry::Volume, and UE::Math::TVector< T >::X.
GetVolumeArea() [2/2]
template<class TriangleMeshType> FVector2d UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea (const TriangleMeshType & Mesh, const TArray< int > & TriIndices) inline static
Definition at line 220 of file MeshQueries.h.
References UE::Geometry::Area, UE::Math::TVector< T >::Cross(), UE::Math::TVector< T >::Length(), UE::Geometry::Mesh, UE::Geometry::Volume, and UE::Math::TVector< T >::X.
GetVolumeAreaCenter()
template<class TriangleMeshType> FVector2d UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeAreaCenter (const TriangleMeshType & Mesh, FVector3d & OutCenterOfMass) inline static
Definition at line 163 of file MeshQueries.h.
References UE::Geometry::Area, UE::Math::TVector< T >::Cross(), UE::Math::TVector< T >::Length(), UE::Geometry::Mesh, UE::Geometry::Volume, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, UE::Math::TVector< T >::Z, and UE::Math::TVector< double >::ZeroVector.
GetVolumeNonWatertight()
template<class TriangleMeshType> double UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeNonWatertight (const TriangleMeshType & Mesh, double DimScaleFactor = 1) inline static
Get the volume of a mesh using a method that is more robust to inputs with holes.
Parameters
Mesh Input shape
DimScaleFactor Scale factor to apply to each dimension; useful for keeping volume calculation in a good range for floating point precision
Returns
Mesh volume (scaled by DimScaleFactor^3)
Definition at line 107 of file MeshQueries.h.
References UE::Math::TVector< T >::Cross(), UE::Geometry::Dot(), GetMeshVerticesCentroid(), UE::Geometry::Mesh, and UE::Geometry::Volume.
Referenced by UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute().
HausdorffDistance()
template<class TriangleMeshType> template<typename MeshSpatialType> double UE::Geometry::TMeshQueries< TriangleMeshType >::HausdorffDistance (const TriangleMeshType & MeshA, const MeshSpatialType & SpatialB) inline static
Compute all vertex-to-surface distances in parallel.
Serial raw loop to find max element (using Algo::MaxElement was never faster in initial benchmarking.)
Parameters
MeshA The mesh whose maximum vertex distance should be computed.
SpatialB The target surface's acceleration structure.
Returns
The maximum distance to the surface contained in SpatialB over all vertices in MeshA.
Definition at line 653 of file MeshQueries.h.
References BIG_NUMBER, FMath::Max, and VertexToSurfaceDistances().
Referenced by TwoSidedHausdorffDistance().
HausdorffDistanceSerial()
template<class TriangleMeshType> template<typename MeshSpatialType> double UE::Geometry::TMeshQueries< TriangleMeshType >::HausdorffDistanceSerial (const TriangleMeshType & MeshA, const MeshSpatialType & SpatialB) inline static
Compute all distances in serial, then a serial raw loop to find max.
Should only be used for debugging the parallel version above!
Definition at line 697 of file MeshQueries.h.
References BIG_NUMBER, FMath::Max, and VertexToSurfaceDistancesSerial().
Referenced by TwoSidedHausdorffDistanceSerial().
MaxEdgeLength()
template<class TriangleMeshType> double UE::Geometry::TMeshQueries< TriangleMeshType >::MaxEdgeLength (const TriangleMeshType & Mesh) inline static
Compute the longest edge length for the given mesh.
Definition at line 501 of file MeshQueries.h.
References UE::Geometry::Length(), FMath::Max, and UE::Geometry::Mesh.
Referenced by EdgeLengthStats(), and EdgeLengthStatsFromEdges().
MeshDistanceStatistics()
template<class TriangleMeshType> template<typename MeshSpatialType> void UE::Geometry::TMeshQueries< TriangleMeshType >::MeshDistanceStatistics (const TriangleMeshType & MeshA, const MeshSpatialType & SpatialB, const TriangleMeshType * MeshB, const MeshSpatialType * SpatialA, bool bSymmetric, double & MaxDistance, double & MinDistance, double & AverageDistance, double & RootMeanSqrDeviation) inline static
Compute various statistics on distances between two meshes.
Definition at line 722 of file MeshQueries.h.
References TArray< InElementType, InAllocatorType >::Append(), BIG_NUMBER, FMath::Max, FMath::Min, TArray< InElementType, InAllocatorType >::Num(), TMathUtil< double >::Sqrt(), and VertexToSurfaceDistances().
MinEdgeLength()
template<class TriangleMeshType> double UE::Geometry::TMeshQueries< TriangleMeshType >::MinEdgeLength (const TriangleMeshType & Mesh) inline static
Compute the shortest edge length for the given mesh.
Definition at line 515 of file MeshQueries.h.
References UE::Geometry::Length(), TMathUtilConstants< double >::MaxReal, UE::Geometry::Mesh, and FMath::Min.
Referenced by EdgeLengthStats(), and EdgeLengthStatsFromEdges().
RayTriangleIntersection()
template<class TriangleMeshType> template<typename RayType = FRay3d> FIntrRay3Triangle3d UE::Geometry::TMeshQueries< TriangleMeshType >::RayTriangleIntersection (const TriangleMeshType & Mesh, int TriIdx, const RayType & Ray) inline static
convenience function to construct a IntrRay3Triangle3 object for a Mesh triangle
Definition at line 455 of file MeshQueries.h.
References UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Find(), UE::Geometry::Mesh, Ray, and UE::Geometry::Triangle.
TotalEdgeLength()
template<class TriangleMeshType> double UE::Geometry::TMeshQueries< TriangleMeshType >::TotalEdgeLength (const TriangleMeshType & Mesh, const TArray< int > & Edges) inline static
Given a mesh and a subset of mesh edges, compute the total length of all the edges.
Definition at line 534 of file MeshQueries.h.
References A, B, Distance, and UE::Geometry::Mesh.
TriangleDistance()
template<class TriangleMeshType> FDistPoint3Triangle3d UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleDistance (const TriangleMeshType & Mesh, int TriIdx, FVector3d Point) inline static
construct a DistPoint3Triangle3 object for a Mesh triangle
Definition at line 28 of file MeshQueries.h.
References check, UE::Geometry::TDistPoint3Triangle3< Real >::GetSquared(), UE::Geometry::Mesh, Point, and UE::Geometry::TTriangle3< RealType >::V.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestPoint(), and FindNearestPoint_LinearSearch().
TriangleIntersection()
template<class TriangleMeshType> FIntrRay3Triangle3d UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleIntersection (const TriangleMeshType & Mesh, int TriIdx, const FRay3d & Ray) inline static
convenience function to construct a IntrRay3Triangle3 object for a Mesh triangle
Definition at line 41 of file MeshQueries.h.
References check, UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Find(), UE::Geometry::Mesh, Ray, and UE::Geometry::TTriangle3< RealType >::V.
Referenced by UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject(), and UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject().
TriDistanceSqr()
template<class TriangleMeshType> double UE::Geometry::TMeshQueries< TriangleMeshType >::TriDistanceSqr (const TriangleMeshType & Mesh, int TriIdx, const FVector3d & Point) inline static
Compute distance from Point to triangle in Mesh, with minimal extra objects/etc.
Definition at line 361 of file MeshQueries.h.
References Distance, UE::Geometry::Distance(), UE::Geometry::Mesh, Point, and UE::Geometry::Triangle.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::debug_check_child_tri_distances(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_tri(), and FindNearestTriangle_LinearSearch().
TwoSidedHausdorffDistance()
template<class TriangleMeshType> template<typename MeshSpatialType> double UE::Geometry::TMeshQueries< TriangleMeshType >::TwoSidedHausdorffDistance (const TriangleMeshType & MeshA, const MeshSpatialType & SpatialA, const TriangleMeshType & MeshB, const MeshSpatialType & SpatialB) inline static
Because Hausdorff distance is not symmetric, we compute the maximum of the distances between two surfaces.
Definition at line 669 of file MeshQueries.h.
References HausdorffDistance(), and FMath::Max.
TwoSidedHausdorffDistanceSerial()
template<class TriangleMeshType> template<typename MeshSpatialType> double UE::Geometry::TMeshQueries< TriangleMeshType >::TwoSidedHausdorffDistanceSerial (const TriangleMeshType & MeshA, const MeshSpatialType & SpatialA, const TriangleMeshType & MeshB, const MeshSpatialType & SpatialB) inline static
Definition at line 712 of file MeshQueries.h.
References HausdorffDistanceSerial(), and FMath::Max.
VertexToSurfaceDistances()
template<class TriangleMeshType> template<typename MeshSpatialType> void UE::Geometry::TMeshQueries< TriangleMeshType >::VertexToSurfaceDistances (const TriangleMeshType & MeshA, const MeshSpatialType & SpatialB, TArray< double > & Distances) inline static
For each vertex on MeshA, compute the distance to the nearest point on the surface contained in SpatialB.
Parameters
MeshA The mesh whose vertex distances should be computed.
SpatialB The target surface's acceleration structure.
Distances For each vertex in MeshA, the distance to the closest point in SpatialB.
Definition at line 631 of file MeshQueries.h.
References check, ParallelFor(), and TArray< InElementType, InAllocatorType >::SetNumZeroed().
Referenced by HausdorffDistance(), and MeshDistanceStatistics().
VertexToSurfaceDistancesSerial()
template<class TriangleMeshType> template<typename MeshSpatialType> void UE::Geometry::TMeshQueries< TriangleMeshType >::VertexToSurfaceDistancesSerial (const TriangleMeshType & MeshA, const MeshSpatialType & SpatialB, TArray< double > & Distances) inline static
Compute all vertex-to-surface distances in serial. Should only be used for debugging the parallel version above!
Definition at line 678 of file MeshQueries.h.
References check, and TArray< InElementType, InAllocatorType >::SetNumZeroed().
Referenced by HausdorffDistanceSerial().
The documentation for this class was generated from the following file:
MeshQueries.h