Unreal Engine 5.6 C++ API: FMovieSceneAccumulatedBlendState::TTokenEntry< DataType > Struct Template Reference
FMovieSceneAccumulatedBlendState::TTokenEntry< DataType > Struct Template Reference
Templated entry that is used to temporarily store token data for later consolidation.
Public Member Functions
TTokenEntry (FMovieSceneBlendingActuatorID InActuatorTypeID, TBlendableToken< DataType > &&InToken)
virtual void Consolidate (FActuatorTokenStackPtr &OutStack) override final
Consolidate this token into the specified array of stacks, one per actuator type.
Public Member Functions inherited from FMovieSceneAccumulatedBlendState::FTokenEntry
virtual ~FTokenEntry ()
FMovieSceneBlendingActuatorID GetActuatorID () const
FMovieSceneAnimTypeID GetDataTypeID () const
Access the result of GetBlendingDataType<DataType>() for the data that this token contains.
Data Fields
TBlendableToken< DataType > Token
The actual token data - defunct after Consolidate is called.
Additional Inherited Members
Protected Member Functions inherited from FMovieSceneAccumulatedBlendState::FTokenEntry
FTokenEntry (FMovieSceneBlendingActuatorID InActuatorTypeID, FMovieSceneAnimTypeID InDataTypeID)
Constructor.
Protected Attributes inherited from FMovieSceneAccumulatedBlendState::FTokenEntry
FMovieSceneBlendingActuatorID ActuatorTypeID
Type ID for the actuator that is to be used to apply this token.
FMovieSceneAnimTypeID DataTypeID
Type ID for data that is contained within the token entry.
Detailed Description
template<typename DataType>
struct FMovieSceneAccumulatedBlendState::TTokenEntry< DataType >
Templated entry that is used to temporarily store token data for later consolidation.
Definition at line 142 of file MovieSceneAccumulatedBlendState.h.
Constructor & Destructor Documentation
TTokenEntry()
template<typename DataType> FMovieSceneAccumulatedBlendState::TTokenEntry< DataType >::TTokenEntry (FMovieSceneBlendingActuatorID InActuatorTypeID, TBlendableToken< DataType > && InToken) inline
Definition at line 144 of file MovieSceneAccumulatedBlendState.h.
References FMovieSceneAccumulatedBlendState::FTokenEntry::FTokenEntry(), GetBlendingDataType(), MoveTemp(), and Token.
Member Function Documentation
Consolidate()
template<typename DataType> virtual void FMovieSceneAccumulatedBlendState::TTokenEntry< DataType >::Consolidate (FActuatorTokenStackPtr & OutStack) inline final override virtual
Consolidate this token into the specified array of stacks, one per actuator type.
Parameters
Stacks Array of token stacks to populate, one per actuator type
Implements FMovieSceneAccumulatedBlendState::FTokenEntry.
Definition at line 153 of file MovieSceneAccumulatedBlendState.h.
References TBlendableTokenStack< DataType >::AddToken(), FMovieSceneAccumulatedBlendState::FTokenEntry::DataTypeID, ensureMsgf, TEXT, and Token.
Field Documentation
Token
template<typename DataType> TBlendableToken<DataType> FMovieSceneAccumulatedBlendState::TTokenEntry< DataType >::Token
The actual token data - defunct after Consolidate is called.
Definition at line 187 of file MovieSceneAccumulatedBlendState.h.
Referenced by TTokenEntry(), and Consolidate().
The documentation for this struct was generated from the following file:
MovieSceneAccumulatedBlendState.h