Unreal Engine 5.6 C++ API: UAnimSequence::FScopedCompressedAnimSequence Struct Reference
UAnimSequence::FScopedCompressedAnimSequence Struct Reference
#include "AnimSequence.h"
Public Member Functions
FScopedCompressedAnimSequence ()=delete
FScopedCompressedAnimSequence (const FScopedCompressedAnimSequence &)=delete
FScopedCompressedAnimSequence (FScopedCompressedAnimSequence &&)=delete
~FScopedCompressedAnimSequence ()
const FCompressedAnimSequence & Get () const
const FCompressedAnimSequence & operator-> () const
FScopedCompressedAnimSequence & operator= (const FScopedCompressedAnimSequence &)=delete
FScopedCompressedAnimSequence & operator= (FScopedCompressedAnimSequence &&)=delete
Protected Member Functions
FScopedCompressedAnimSequence (const UAnimSequence *InAnimSequence, const FCompressedAnimSequence *InCompressedData)
Protected Attributes
const FCompressedAnimSequence * CompressedData = nullptr
TUniquePtr< UE::TSharedLock< UE::FSharedRecursiveMutex > > SharedLock
Friends
class UAnimSequence
Detailed Description
Definition at line 896 of file AnimSequence.h.
Constructor & Destructor Documentation
FScopedCompressedAnimSequence() [1/4]
UAnimSequence::FScopedCompressedAnimSequence::FScopedCompressedAnimSequence () delete
Referenced by FScopedCompressedAnimSequence(), FScopedCompressedAnimSequence(), operator=(), and operator=().
FScopedCompressedAnimSequence() [2/4]
UAnimSequence::FScopedCompressedAnimSequence::FScopedCompressedAnimSequence (const FScopedCompressedAnimSequence &) delete
References FScopedCompressedAnimSequence().
FScopedCompressedAnimSequence() [3/4]
UAnimSequence::FScopedCompressedAnimSequence::FScopedCompressedAnimSequence (FScopedCompressedAnimSequence &&) delete
References FScopedCompressedAnimSequence().
~FScopedCompressedAnimSequence()
UAnimSequence::FScopedCompressedAnimSequence::~FScopedCompressedAnimSequence () inline
Definition at line 907 of file AnimSequence.h.
References SharedLock.
FScopedCompressedAnimSequence() [4/4]
UAnimSequence::FScopedCompressedAnimSequence::FScopedCompressedAnimSequence (const UAnimSequence * InAnimSequence, const FCompressedAnimSequence * InCompressedData) inline protected
Definition at line 914 of file AnimSequence.h.
References check, CompressedData, MakeUnique(), UAnimSequence::SharedCompressedDataMutex, SharedLock, and UAnimSequence.
Member Function Documentation
Get()
const FCompressedAnimSequence & UAnimSequence::FScopedCompressedAnimSequence::Get () const inline
Definition at line 905 of file AnimSequence.h.
References CompressedData.
operator->()
const FCompressedAnimSequence & UAnimSequence::FScopedCompressedAnimSequence::operator-> () const inline
Definition at line 904 of file AnimSequence.h.
References CompressedData.
operator=() [1/2]
FScopedCompressedAnimSequence & UAnimSequence::FScopedCompressedAnimSequence::operator= (const FScopedCompressedAnimSequence &) delete
References FScopedCompressedAnimSequence().
operator=() [2/2]
FScopedCompressedAnimSequence & UAnimSequence::FScopedCompressedAnimSequence::operator= (FScopedCompressedAnimSequence &&) delete
References FScopedCompressedAnimSequence().
Friends And Related Symbol Documentation
UAnimSequence
friend class UAnimSequence friend
Definition at line 927 of file AnimSequence.h.
References UAnimSequence.
Referenced by FScopedCompressedAnimSequence(), and UAnimSequence.
Field Documentation
CompressedData
const FCompressedAnimSequence* UAnimSequence::FScopedCompressedAnimSequence::CompressedData = nullptr protected
Definition at line 923 of file AnimSequence.h.
Referenced by FScopedCompressedAnimSequence(), Get(), and operator->().
SharedLock
TUniquePtr<UE::TSharedLock<UE::FSharedRecursiveMutex> > UAnimSequence::FScopedCompressedAnimSequence::SharedLock protected
Definition at line 925 of file AnimSequence.h.
Referenced by FScopedCompressedAnimSequence(), and ~FScopedCompressedAnimSequence().
The documentation for this struct was generated from the following file:
AnimSequence.h