Unreal Engine 5.6 C++ API: UE::GC::TFastReferenceCollector< ProcessorType, CollectorType > Class Template Reference
UE::GC::TFastReferenceCollector< ProcessorType, CollectorType > Class Template Reference
Helper class that looks for UObject references by traversing UClass token stream and calls AddReferencedObjects.
#include "FastReferenceCollector.h"
Data Structures
struct HasFlushWork
struct HasFlushWork< T, std::void_t< decltype(std::declval< T >().FlushWork())> >
Public Member Functions
TFastReferenceCollector (ProcessorType &InProcessor)
void ProcessObjectArray (FWorkerContext &Context)
Private Types
using DispatcherType = typename TGetDispatcherType<CollectorType, ProcessorType>::Type
Private Member Functions
FORCEINLINE_DEBUGGABLE void FlushWork (DispatcherType &Dispatcher)
FORCEINLINE_DEBUGGABLE void ProcessObjects (DispatcherType &Dispatcher, TConstArrayView< UObject * > CurrentObjects)
FORCENOINLINE void ProcessStructs (DispatcherType &Dispatcher)
Private Attributes
ProcessorType & Processor
Static Private Attributes
static constexpr bool bIsParallel = IsParallel(Options)
static constexpr EGCOptions Options = ProcessorType::Options
Additional Inherited Members
Static Public Member Functions inherited from FGCInternals
static FORCEINLINE void ClearCachedField (FFieldPath &Path)
static FORCEINLINE FUObjectItem * GetResolvedOwner (FFieldPath &Path)
Detailed Description
template<typename ProcessorType, typename CollectorType>
class UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >
Helper class that looks for UObject references by traversing UClass token stream and calls AddReferencedObjects.
Provides a generic way of processing references that is used by Unreal Engine garbage collection. Can be used for fast (does not use serialization) reference collection purposes.
IT IS CRITICAL THIS CLASS DOES NOT CHANGE WITHOUT CONSIDERING PERFORMANCE IMPACT OF SAID CHANGES
See also
FSimpleReferenceProcessorBase and TDefaultCollector for documentation on required APIs
Definition at line 883 of file FastReferenceCollector.h.
Member Typedef Documentation
DispatcherType
template<typename ProcessorType, typename CollectorType> using UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::DispatcherType = typename TGetDispatcherType<CollectorType, ProcessorType>::Type private
Definition at line 971 of file FastReferenceCollector.h.
Constructor & Destructor Documentation
TFastReferenceCollector()
template<typename ProcessorType, typename CollectorType> UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::TFastReferenceCollector (ProcessorType & InProcessor) inline
Definition at line 886 of file FastReferenceCollector.h.
References Processor.
Member Function Documentation
FlushWork()
template<typename ProcessorType, typename CollectorType> FORCEINLINE_DEBUGGABLE void UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::FlushWork (DispatcherType & Dispatcher) inline private
Definition at line 1034 of file FastReferenceCollector.h.
References FORCEINLINE_DEBUGGABLE, and ProcessStructs().
Referenced by ProcessObjectArray().
ProcessObjectArray()
template<typename ProcessorType, typename CollectorType> void UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray (FWorkerContext & Context) inline
Definition at line 888 of file FastReferenceCollector.h.
References UE::GC::ARO, AutogenerateSchemas, bIsParallel, UE::GC::Block, UE::GC::Collector, UE::GC::Context, EnumHasAllFlags(), FlushWork(), UE::GC::GetDispatcher(), FGCObject::GGCObjectReferencer, UE::GC::InitialReference, MakeArrayView(), UE::GC::Nothing, UE::GC::FWorkBlock::ObjectCapacity, Options, UE::GC::Other, Parallel, UE::GC::FWorkBlockifier::PopFullBlock(), UE::GC::FWorkBlockifier::PopPartialBlock(), ProcessObjects(), Processor, UE::GC::FSlowARO::ProcessUnbalancedCalls(), UE::GC::StealWork(), and UE::GC::SuspendWork().
ProcessObjects()
template<typename ProcessorType, typename CollectorType> FORCEINLINE_DEBUGGABLE void UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjects (DispatcherType & Dispatcher, TConstArrayView< UObject * > CurrentObjects) inline private
Definition at line 977 of file FastReferenceCollector.h.
References AutogenerateSchemas, UE::GC::Class, CLASS_TokenStreamAssembled, UE::GC::ExternalPackage, FORCEINLINE_DEBUGGABLE, UObjectBase::GetClass(), UObjectBase::GetExternalPackageInternal(), UObjectBase::GetOuter(), UE::GC::FPrefetchingObjectIterator::HasMore(), UE::GC::FSchemaView::IsEmpty(), Options, UE::GC::Other, UE::GC::Outer, Processor, and UE::GC::Private::VisitMembers().
Referenced by ProcessObjectArray().
ProcessStructs()
template<typename ProcessorType, typename CollectorType> FORCENOINLINE void UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessStructs (DispatcherType & Dispatcher) private
References FORCENOINLINE.
Referenced by FlushWork().
Field Documentation
bIsParallel
template<typename ProcessorType, typename CollectorType> bool UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::bIsParallel = IsParallel(Options) static constexpr private
Definition at line 973 of file FastReferenceCollector.h.
Referenced by ProcessObjectArray().
Options
template<typename ProcessorType, typename CollectorType> EGCOptions UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::Options = ProcessorType::Options static constexpr private
Definition at line 972 of file FastReferenceCollector.h.
Referenced by ProcessObjectArray(), and ProcessObjects().
Processor
template<typename ProcessorType, typename CollectorType> ProcessorType& UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::Processor private
Definition at line 975 of file FastReferenceCollector.h.
Referenced by TFastReferenceCollector(), ProcessObjectArray(), and ProcessObjects().
The documentation for this class was generated from the following file:
FastReferenceCollector.h