Unreal Engine 5.6 C++ API: SSpinBox< NumericType > Class Template Reference
SSpinBox< NumericType > Class Template Reference
A Slate SpinBox resembles traditional spin boxes in that it is a widget that provides keyboard-based and mouse-based manipulation of a numeric value.
#include "SSpinBox.h"
Data Structures
struct FPendingCommitValue
Public Member Functions
virtual ~SSpinBox ()
void ApplySliderMaxValueChanged (float SliderDeltaToAdd, bool UpdateOnlyIfHigher)
void ApplySliderMinValueChanged (float SliderDeltaToAdd, bool UpdateOnlyIfLower)
const bool CommitWithMultiplier (const FPointerEvent &MouseEvent)
void Construct (const FArguments &InArgs)
Construct the widget.
DECLARE_DELEGATE_FourParams (FOnDynamicSliderMinMaxValueChanged, NumericType, TWeakPtr< SWidget >, bool, bool)
Notification when the max/min spinner values are changed (only apply if SupportDynamicSliderMaxValue or SupportDynamicSliderMinValue are true)
DECLARE_DELEGATE_OneParam (FOnValueChanged, NumericType)
Notification for numeric value change.
DECLARE_DELEGATE_RetVal_OneParam (TOptional< FText >, FOnGetDisplayValue, NumericType)
Optional customization of the display value based on the current value.
DECLARE_DELEGATE_TwoParams (FOnValueCommitted, NumericType, ETextCommit::Type)
Notification for numeric value committed.
bool GetAlwaysUsesDeltaSnap () const
See the AlwaysUsesDeltaSnap attribute.
NumericType GetDelta () const
See the Delta attribute.
bool GetEnableSlider () const
See the EnableSlider attribute.
int32 GetMaxFractionalDigits () const
See the MaxFractionalDigits attribute.
NumericType GetMaxSliderValue () const
NumericType GetMaxValue () const
See the MaxValue attribute.
float GetMinDesiredWidth () const
See the MinDesiredWidth attribute.
int32 GetMinFractionalDigits () const
See the MinFractionalDigits attribute.
NumericType GetMinSliderValue () const
NumericType GetMinValue () const
See the MinValue attribute.
float GetSliderExponent () const
See the SliderExponent attribute.
NumericType GetValue () const
See the Value attribute.
TAttribute< NumericType > GetValueAttribute () const
Return the Value attribute.
const FSpinBoxStyle * GetWidgetStyle () const
virtual bool HasKeyboardFocus () const override
Checks to see if this widget currently has the keyboard focus.
void InvalidateStyle ()
bool IsMaxSliderValueBound () const
See the MaxSliderValue attribute.
bool IsMinSliderValueBound () const
See the MinSliderValue attribute.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent) override
Called when focus is given to this widget.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when the mouse wheel is spun.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
void ResetCachedValueString ()
Reset the cached string.
void SetAlwaysUsesDeltaSnap (bool bNewValue)
void SetDelta (NumericType InDelta)
void SetEnableSlider (bool bNewValue)
void SetMaxFractionalDigits (const TAttribute< TOptional< int32 > > &InMaxFractionalDigits)
void SetMaxSliderValue (const TAttribute< TOptional< NumericType > > &InMaxSliderValue)
void SetMaxValue (const TAttribute< TOptional< NumericType > > &InMaxValue)
void SetMinDesiredWidth (const TAttribute< float > &InMinDesiredWidth)
void SetMinFractionalDigits (const TAttribute< TOptional< int32 > > &InMinFractionalDigits)
void SetMinSliderValue (const TAttribute< TOptional< NumericType > > &InMinSliderValue)
void SetMinValue (const TAttribute< TOptional< NumericType > > &InMinValue)
void SetSliderExponent (const TAttribute< float > &InSliderExponent)
void SetTextBlockFont (FSlateFontInfo InFont)
void SetTextClearKeyboardFocusOnCommit (bool bNewValue)
void SetTextJustification (ETextJustify::Type InJustification)
void SetTextRevertTextOnEscape (bool bNewValue)
void SetTextSelectAllTextOnCommit (bool bNewValue)
void SetValue (const TAttribute< NumericType > &InValueAttribute)
void SetWidgetStyle (const FSpinBoxStyle *InStyle)
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel SLATE_ARGUMENT (bool, BroadcastValueChangesPerKey) SLATE_ATTRIBUTE(TOptional< NumericType >
True to broadcast every time we type.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth KeyboardType PreventThrottling SLATE_ARGUMENT (bool, RevertTextOnEscape) SLATE_EVENT(FMenuExtensionDelegate
If the text should be reverted when pressing the escape key.
Value MaxValue MaxSliderValue MaxFractionalDigits SLATE_ATTRIBUTE (bool, AlwaysUsesDeltaSnap) SLATE_ATTRIBUTE(bool
Whether typed values should use delta snapping, defaults to false.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit SLATE_ATTRIBUTE (bool, SelectAllTextOnCommit) SLATE_ATTRIBUTE(float
Whether to select all text when pressing enter to commit changes.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue SLATE_ATTRIBUTE (bool, SupportDynamicSliderMinValue) SLATE_EVENT(FOnDynamicSliderMinMaxValueChanged
Tell us if we want to support dynamically changing of the min value using alt.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth SLATE_ATTRIBUTE (ETextJustify::Type, Justification) SLATE_ATTRIBUTE(EKeyboardType
How should the value be justified in the spinbox.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move SLATE_ATTRIBUTE (float, ShiftMultiplier) SLATE_ATTRIBUTE(float
Multiplier to use when shift is held down.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep SLATE_ATTRIBUTE (FSlateFontInfo, Font) SLATE_ATTRIBUTE(FMargin
Font used to display text in the slider.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SLATE_ATTRIBUTE (int32, LinearDeltaSensitivity) SLATE_ATTRIBUTE(bool
If we're an unbounded spinbox, what value do we divide mouse movement by before multiplying by Delta.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider SLATE_ATTRIBUTE (NumericType, Delta) SLATE_ATTRIBUTE_DEPRECATED(int32
Delta to increment the value as the slider moves.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent SLATE_ATTRIBUTE (NumericType, SliderExponentNeutralValue) SLATE_ARGUMENT(bool
When use exponential scale for the slider which is the neutral value.
Value MaxValue MaxSliderValue SLATE_ATTRIBUTE (TOptional< int32 >, MinFractionalDigits) SLATE_ATTRIBUTE(TOptional< int32 >
The minimum fractional digits the spin box displays, defaults to 1.
Value MaxValue SLATE_ATTRIBUTE (TOptional< NumericType >, MinSliderValue) SLATE_ATTRIBUTE(TOptional< NumericType >
The minimum value that can be specified by using the slider, defaults to MinValue.
Value SLATE_ATTRIBUTE (TOptional< NumericType >, MinValue) SLATE_ATTRIBUTE(TOptional< NumericType >
The minimum value that can be entered into the text edit box.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth KeyboardType SLATE_ATTRIBUTE (TSharedPtr< INumericTypeInterface< NumericType > >, TypeInterface) SLATE_ARGUMENT(bool
Provide custom type conversion functionality to this spin box.
SLATE_BEGIN_ARGS (SSpinBox< NumericType >)
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth KeyboardType PreventThrottling ContextMenuExtender SLATE_END_ARGS () 1 SSpinBox()
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SLATE_EVENT (FOnDynamicSliderMinMaxValueChanged, OnDynamicSliderMinValueChanged) SLATE_ATTRIBUTE(float
Called right after the min slider value is changed (only relevant if SupportDynamicSliderMinValue is true)
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement SLATE_EVENT (FOnGetDisplayValue, OnGetDisplayValue) SLATE_ATTRIBUTE(bool
Called to allow customization of what text is displayed when not typing.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding SLATE_EVENT (FOnValueChanged, OnValueChanged) SLATE_EVENT(FOnValueCommitted
Called when the value is changed by slider or typing.
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted SLATE_EVENT (FSimpleDelegate, OnBeginSliderMovement) SLATE_EVENT(FOnValueChanged
Called right before the slider begins to move.
SLATE_STYLE_ARGUMENT (FSpinBoxStyle, Style) SLATE_ATTRIBUTE(NumericType
The style used to draw this spinbox.
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
void Tick (const FGeometry &AlottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider ShiftMouseMovePixelPerDelta
Protected Types
enum ECommitMethod {
CommittedViaSpin , CommittedViaTypeIn , CommittedViaArrowKey , CommittedViaCode ,
CommittedViaSpinMultiplier
}
How user changed the value in the spinbox.
Protected Member Functions
void CommitValue (NumericType NewValue, double NewSpinValue, ECommitMethod CommitMethod, ETextCommit::Type OriginalCommitInfo)
Call this method when the user's interaction has changed the value.
void EnterTextMode ()
Make the spinbox switch to keyboard-based input mode.
void ExitTextMode ()
Make the spinbox switch to mouse-based input mode.
FText GetDisplayValue () const
FString GetValueAsString () const
FText GetValueAsText () const
bool IsInTextMode () const
void NotifyValueCommitted (NumericType CurrentValue) const
void TextField_OnTextChanged (const FText &NewText)
Invoked when the text in the text field changes.
void TextField_OnTextCommitted (const FText &NewText, ETextCommit::Type CommitInfo)
Invoked when the text field commits its text.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static float Fraction (double InValue, double InMinValue, double InMaxValue)
Calculates range fraction.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Private Member Functions
void CancelMouseCapture ()
double GetDefaultStepSize (const FInputEvent &InputEvent)
float GetTextMinDesiredWidth () const
bool IsCharacterValid (TCHAR InChar) const
Check whether a typed character is valid.
NumericType RoundIfIntegerValue (double ValueToRound) const
Rounds the submitted value to the correct value if it's an integer.
void UpdateIsSpinRangeUnlimited ()
Private Attributes
const FSlateBrush * ActiveFillBrush
TAttribute< bool > AlwaysUsesDeltaSnap
const FSlateBrush * BackgroundActiveBrush
const FSlateBrush * BackgroundBrush
const FSlateBrush * BackgroundHoveredBrush
bool bBroadcastValueChangesPerKey = false
True to broadcast every time we type.
bool bCachedValueStringDirty
Whetever the interfaced setting changed and the CachedValueString needs to be recomputed.
bool bDragging
Whether the user is dragging the slider.
bool bEnableWheel = true
Does this spin box have the mouse wheel feature enabled?
bool bIsTextChanging
Re-entrant guard for the text changed handler.
bool bPreventThrottling
bool bUnlimitedSpinRange
True when no range is specified, spinner can be spun indefinitely.
NumericType CachedExternalValue
This is the cached value the user believes it to be (usually different due to truncation to an int).
FIntPoint CachedMousePosition
Cached mouse position to restore after scrolling.
FString CachedValueString
Used to prevent per-frame re-conversion of the cached numeric value to a string.
TAttribute< float > CtrlMultiplier
TAttribute< NumericType > Delta
float DistanceDragged
TSharedPtr< SEditableText > EditableText
TAttribute< bool > EnableSlider
const FSlateBrush * HoveredFillBrush
const FSlateBrush * InactiveFillBrush
TAttribute< TSharedPtr< INumericTypeInterface< NumericType > > > InterfaceAttr
Interface that defines conversion functionality for the templated type.
double InternalValue
This value represents what the spinbox believes the value to be, regardless of delta and the user binding to an int.
TAttribute< int32 > LinearDeltaSensitivity
TAttribute< TOptional< int32 > > MaxFractionalDigits
TAttribute< TOptional< NumericType > > MaxSliderValue
TAttribute< TOptional< NumericType > > MaxValue
TAttribute< float > MinDesiredWidth
Prevents the spinbox from being smaller than desired in certain cases (e.g.
TAttribute< TOptional< int32 > > MinFractionalDigits
TAttribute< TOptional< NumericType > > MinSliderValue
TAttribute< TOptional< NumericType > > MinValue
FSimpleDelegate OnBeginSliderMovement
FOnDynamicSliderMinMaxValueChanged OnDynamicSliderMaxValueChanged
FOnDynamicSliderMinMaxValueChanged OnDynamicSliderMinValueChanged
FOnValueChanged OnEndSliderMovement
FOnGetDisplayValue OnGetDisplayValue
FOnValueChanged OnValueChanged
FOnValueCommitted OnValueCommitted
TOptional< FPendingCommitValue > PendingCommitValue
int32 PointerDraggingSliderIndex
Tracks which cursor is currently dragging the slider (e.g., the mouse cursor or a specific finger)
NumericType PreDragValue
The state of InternalValue before a drag operation was started.
TAttribute< float > ShiftMultiplier
TAttribute< float > SliderExponent
TAttribute< NumericType > SliderExponentNeutralValue
const double SmallStepSize = .1f
Step size to use when range is below SmallStepSizeMax.
const double SmallStepSizeMax = 10.f
Largest numerical value to use the SmallStepSize instead of StepSize.
const double StepSize = 1.f
Gets the default amount to change the slider when delta is not applicable.
const FSpinBoxStyle * Style
TAttribute< bool > SupportDynamicSliderMaxValue
TAttribute< bool > SupportDynamicSliderMinValue
TSharedPtr< STextBlock > TextBlock
TAttribute< NumericType > ValueAttribute
TAttribute< TOptional< NumericType > > WheelStep
Static Private Attributes
static constexpr int32 DefaultMaxFractionalDigits = 6
The default maximum fractional digits.
static constexpr int32 DefaultMinFractionalDigits = 1
The default minimum fractional digits.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
template<typename NumericType>
class SSpinBox< NumericType >
A Slate SpinBox resembles traditional spin boxes in that it is a widget that provides keyboard-based and mouse-based manipulation of a numeric value.
Mouse-based manipulation: drag anywhere on the spinbox to change the value. Keyboard-based manipulation: click on the spinbox to enter text mode.
Definition at line 62 of file SSpinBox.h.
Member Enumeration Documentation
ECommitMethod
template<typename NumericType> enum SSpinBox::ECommitMethod protected
How user changed the value in the spinbox.
Enumerator
CommittedViaSpin
CommittedViaTypeIn
CommittedViaArrowKey
CommittedViaCode
CommittedViaSpinMultiplier
Definition at line 366 of file SSpinBox.h.
Constructor & Destructor Documentation
~SSpinBox()
template<typename NumericType> virtual SSpinBox< NumericType >::~SSpinBox () virtual
Member Function Documentation
ApplySliderMaxValueChanged()
template<typename NumericType> void SSpinBox< NumericType >::ApplySliderMaxValueChanged (float SliderDeltaToAdd, bool UpdateOnlyIfHigher)
References ApplySliderMaxValueChanged().
Referenced by ApplySliderMaxValueChanged().
ApplySliderMinValueChanged()
template<typename NumericType> void SSpinBox< NumericType >::ApplySliderMinValueChanged (float SliderDeltaToAdd, bool UpdateOnlyIfLower)
References ApplySliderMinValueChanged().
Referenced by ApplySliderMinValueChanged().
CancelMouseCapture()
template<typename NumericType> void SSpinBox< NumericType >::CancelMouseCapture () private
CommitValue()
template<typename NumericType> void SSpinBox< NumericType >::CommitValue (NumericType NewValue, double NewSpinValue, ECommitMethod CommitMethod, ETextCommit::Type OriginalCommitInfo) protected
Call this method when the user's interaction has changed the value.
Parameters
NewValue Value resulting from the user's interaction
CommitMethod Did the user type in the value or spin to it.
OriginalCommitInfo If the user typed in the value, information about the source of the commit
CommitWithMultiplier()
template<typename NumericType> const bool SSpinBox< NumericType >::CommitWithMultiplier (const FPointerEvent & MouseEvent)
References CommitWithMultiplier(), and MouseEvent.
Referenced by CommitWithMultiplier().
Construct()
template<typename NumericType> void SSpinBox< NumericType >::Construct (const FArguments & InArgs)
Construct the widget.
Parameters
InArgs A declaration from which to construct the widget
References Construct().
Referenced by Construct().
DECLARE_DELEGATE_FourParams()
template<typename NumericType> SSpinBox< NumericType >::DECLARE_DELEGATE_FourParams (FOnDynamicSliderMinMaxValueChanged , NumericType , TWeakPtr< SWidget > , bool , bool)
Notification when the max/min spinner values are changed (only apply if SupportDynamicSliderMaxValue or SupportDynamicSliderMinValue are true)
DECLARE_DELEGATE_OneParam()
template<typename NumericType> SSpinBox< NumericType >::DECLARE_DELEGATE_OneParam (FOnValueChanged , NumericType)
Notification for numeric value change.
DECLARE_DELEGATE_RetVal_OneParam()
template<typename NumericType> SSpinBox< NumericType >::DECLARE_DELEGATE_RetVal_OneParam (TOptional< FText > , FOnGetDisplayValue , NumericType)
Optional customization of the display value based on the current value.
DECLARE_DELEGATE_TwoParams()
template<typename NumericType> SSpinBox< NumericType >::DECLARE_DELEGATE_TwoParams (FOnValueCommitted , NumericType , ETextCommit::Type)
Notification for numeric value committed.
EnterTextMode()
template<typename NumericType> void SSpinBox< NumericType >::EnterTextMode () protected
Make the spinbox switch to keyboard-based input mode.
References EnterTextMode().
Referenced by EnterTextMode().
ExitTextMode()
template<typename NumericType> void SSpinBox< NumericType >::ExitTextMode () protected
Make the spinbox switch to mouse-based input mode.
References ExitTextMode().
Referenced by ExitTextMode().
Fraction()
template<typename NumericType> float SSpinBox< NumericType >::Fraction (double InValue, double InMinValue, double InMaxValue) static protected
Calculates range fraction.
Possible to use on full numeric range
GetAlwaysUsesDeltaSnap()
template<typename NumericType> bool SSpinBox< NumericType >::GetAlwaysUsesDeltaSnap () const
See the AlwaysUsesDeltaSnap attribute.
References GetAlwaysUsesDeltaSnap().
Referenced by GetAlwaysUsesDeltaSnap().
GetDefaultStepSize()
template<typename NumericType> double SSpinBox< NumericType >::GetDefaultStepSize (const FInputEvent & InputEvent) private
GetDelta()
template<typename NumericType> NumericType SSpinBox< NumericType >::GetDelta () const
See the Delta attribute.
References GetDelta().
Referenced by GetDelta().
GetDisplayValue()
template<typename NumericType> FText SSpinBox< NumericType >::GetDisplayValue () const protected
Returns
the value to be displayed when not manually editing text
References GetDisplayValue().
Referenced by GetDisplayValue().
GetEnableSlider()
template<typename NumericType> bool SSpinBox< NumericType >::GetEnableSlider () const
See the EnableSlider attribute.
References GetEnableSlider().
Referenced by GetEnableSlider().
GetMaxFractionalDigits()
template<typename NumericType> int32 SSpinBox< NumericType >::GetMaxFractionalDigits () const
See the MaxFractionalDigits attribute.
References GetMaxFractionalDigits().
Referenced by GetMaxFractionalDigits().
GetMaxSliderValue()
template<typename NumericType> NumericType SSpinBox< NumericType >::GetMaxSliderValue () const
References GetMaxSliderValue().
Referenced by GetMaxSliderValue().
GetMaxValue()
template<typename NumericType> NumericType SSpinBox< NumericType >::GetMaxValue () const
See the MaxValue attribute.
References GetMaxValue().
Referenced by GetMaxValue().
GetMinDesiredWidth()
template<typename NumericType> float SSpinBox< NumericType >::GetMinDesiredWidth () const
See the MinDesiredWidth attribute.
References GetMinDesiredWidth().
Referenced by GetMinDesiredWidth().
GetMinFractionalDigits()
template<typename NumericType> int32 SSpinBox< NumericType >::GetMinFractionalDigits () const
See the MinFractionalDigits attribute.
References GetMinFractionalDigits().
Referenced by GetMinFractionalDigits().
GetMinSliderValue()
template<typename NumericType> NumericType SSpinBox< NumericType >::GetMinSliderValue () const
References GetMinSliderValue().
Referenced by GetMinSliderValue().
GetMinValue()
template<typename NumericType> NumericType SSpinBox< NumericType >::GetMinValue () const
See the MinValue attribute.
References GetMinValue().
Referenced by GetMinValue().
GetSliderExponent()
template<typename NumericType> float SSpinBox< NumericType >::GetSliderExponent () const
See the SliderExponent attribute.
References GetSliderExponent().
Referenced by GetSliderExponent().
GetTextMinDesiredWidth()
template<typename NumericType> float SSpinBox< NumericType >::GetTextMinDesiredWidth () const private
GetValue()
template<typename NumericType> NumericType SSpinBox< NumericType >::GetValue () const
See the Value attribute.
References GetValue().
Referenced by GetValue().
GetValueAsString()
template<typename NumericType> FString SSpinBox< NumericType >::GetValueAsString () const protected
Returns
the value being observed by the spinbox as a string
References GetValueAsString().
Referenced by GetValueAsString().
GetValueAsText()
template<typename NumericType> FText SSpinBox< NumericType >::GetValueAsText () const protected
Returns
the value being observed by the spinbox as FText - todo: spinbox FText support (reimplement me)
References GetValueAsText().
Referenced by GetValueAsText().
GetValueAttribute()
template<typename NumericType> TAttribute< NumericType > SSpinBox< NumericType >::GetValueAttribute () const
Return the Value attribute.
References GetValueAttribute().
Referenced by GetValueAttribute().
GetWidgetStyle()
template<typename NumericType> const FSpinBoxStyle * SSpinBox< NumericType >::GetWidgetStyle () const
References GetWidgetStyle().
Referenced by GetWidgetStyle(), and SLATE_BEGIN_ARGS().
HasKeyboardFocus()
template<typename NumericType> virtual bool SSpinBox< NumericType >::HasKeyboardFocus () const override virtual
Checks to see if this widget currently has the keyboard focus.
Returns
True if this widget has keyboard focus
Reimplemented from SWidget.
References HasKeyboardFocus().
Referenced by HasKeyboardFocus().
InvalidateStyle()
template<typename NumericType> void SSpinBox< NumericType >::InvalidateStyle ()
References InvalidateStyle().
Referenced by InvalidateStyle().
IsCharacterValid()
template<typename NumericType> bool SSpinBox< NumericType >::IsCharacterValid (TCHAR InChar) const private
Check whether a typed character is valid.
IsInTextMode()
template<typename NumericType> bool SSpinBox< NumericType >::IsInTextMode () const protected
Returns
true when we are in keyboard-based input mode; false otherwise
IsMaxSliderValueBound()
template<typename NumericType> bool SSpinBox< NumericType >::IsMaxSliderValueBound () const
See the MaxSliderValue attribute.
References IsMaxSliderValueBound().
Referenced by IsMaxSliderValueBound().
IsMinSliderValueBound()
template<typename NumericType> bool SSpinBox< NumericType >::IsMinSliderValueBound () const
See the MinSliderValue attribute.
References IsMinSliderValueBound().
Referenced by IsMinSliderValueBound().
NotifyValueCommitted()
template<typename NumericType> void SSpinBox< NumericType >::NotifyValueCommitted (NumericType CurrentValue) const protected
OnCursorQuery()
template<typename NumericType> virtual FCursorReply SSpinBox< NumericType >::OnCursorQuery (const FGeometry & MyGeometry, const FPointerEvent & CursorEvent) const override virtual
The system asks each widget under the mouse to provide a cursor.
This event is bubbled.
Returns
FCursorReply::Unhandled() if the event is not handled; return FCursorReply::Cursor() otherwise.
Reimplemented from SWidget.
References OnCursorQuery().
Referenced by OnCursorQuery().
OnFocusReceived()
template<typename NumericType> virtual FReply SSpinBox< NumericType >::OnFocusReceived (const FGeometry & MyGeometry, const FFocusEvent & InFocusEvent) override virtual
Called when focus is given to this widget.
This event does not bubble.
Parameters
MyGeometry The Geometry of the widget receiving the event
InFocusEvent The FocusEvent
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnFocusReceived().
Referenced by OnFocusReceived().
OnKeyDown()
template<typename NumericType> virtual FReply SSpinBox< NumericType >::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
OnMouseButtonDown()
template<typename NumericType> virtual FReply SSpinBox< NumericType >::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and OnMouseButtonDown().
Referenced by OnMouseButtonDown().
OnMouseButtonUp()
template<typename NumericType> virtual FReply SSpinBox< NumericType >::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and OnMouseButtonUp().
Referenced by OnMouseButtonUp().
OnMouseMove()
template<typename NumericType> virtual FReply SSpinBox< NumericType >::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and OnMouseMove().
Referenced by OnMouseMove().
OnMouseWheel()
template<typename NumericType> virtual FReply SSpinBox< NumericType >::OnMouseWheel (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Called when the mouse wheel is spun.
This event is bubbled.
Parameters
MouseEvent Mouse event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References MouseEvent, and OnMouseWheel().
Referenced by OnMouseWheel().
OnPaint()
template<typename NumericType> virtual int32 SSpinBox< NumericType >::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Reimplemented from SCompoundWidget.
References SWidget::FSlateWindowElementList, and OnPaint().
Referenced by OnPaint().
ResetCachedValueString()
template<typename NumericType> void SSpinBox< NumericType >::ResetCachedValueString ()
Reset the cached string.
Typically used when the value is the same but the display format changed (through the callback).
References ResetCachedValueString().
Referenced by ResetCachedValueString().
RoundIfIntegerValue()
template<typename NumericType> NumericType SSpinBox< NumericType >::RoundIfIntegerValue (double ValueToRound) const private
Rounds the submitted value to the correct value if it's an integer.
For int64, not all values can be represented by a double. We can only round until we reach that limit. This function should only be used when we drag the value. We accept that we can't drag huge numbers.
SetAlwaysUsesDeltaSnap()
template<typename NumericType> void SSpinBox< NumericType >::SetAlwaysUsesDeltaSnap (bool bNewValue)
References SetAlwaysUsesDeltaSnap().
Referenced by SetAlwaysUsesDeltaSnap().
SetDelta()
template<typename NumericType> void SSpinBox< NumericType >::SetDelta (NumericType InDelta)
References SetDelta().
Referenced by SetDelta().
SetEnableSlider()
template<typename NumericType> void SSpinBox< NumericType >::SetEnableSlider (bool bNewValue)
References SetEnableSlider().
Referenced by SetEnableSlider().
SetMaxFractionalDigits()
template<typename NumericType> void SSpinBox< NumericType >::SetMaxFractionalDigits (const TAttribute< TOptional< int32 > > & InMaxFractionalDigits)
References SetMaxFractionalDigits().
Referenced by SetMaxFractionalDigits().
SetMaxSliderValue()
template<typename NumericType> void SSpinBox< NumericType >::SetMaxSliderValue (const TAttribute< TOptional< NumericType > > & InMaxSliderValue)
References SetMaxSliderValue().
Referenced by SetMaxSliderValue().
SetMaxValue()
template<typename NumericType> void SSpinBox< NumericType >::SetMaxValue (const TAttribute< TOptional< NumericType > > & InMaxValue)
References SetMaxValue().
Referenced by SetMaxValue().
SetMinDesiredWidth()
template<typename NumericType> void SSpinBox< NumericType >::SetMinDesiredWidth (const TAttribute< float > & InMinDesiredWidth)
References SetMinDesiredWidth().
Referenced by SetMinDesiredWidth().
SetMinFractionalDigits()
template<typename NumericType> void SSpinBox< NumericType >::SetMinFractionalDigits (const TAttribute< TOptional< int32 > > & InMinFractionalDigits)
References SetMinFractionalDigits().
Referenced by SetMinFractionalDigits().
SetMinSliderValue()
template<typename NumericType> void SSpinBox< NumericType >::SetMinSliderValue (const TAttribute< TOptional< NumericType > > & InMinSliderValue)
References SetMinSliderValue().
Referenced by SetMinSliderValue().
SetMinValue()
template<typename NumericType> void SSpinBox< NumericType >::SetMinValue (const TAttribute< TOptional< NumericType > > & InMinValue)
References SetMinValue().
Referenced by SetMinValue().
SetSliderExponent()
template<typename NumericType> void SSpinBox< NumericType >::SetSliderExponent (const TAttribute< float > & InSliderExponent)
References SetSliderExponent().
Referenced by SetSliderExponent().
SetTextBlockFont()
template<typename NumericType> void SSpinBox< NumericType >::SetTextBlockFont (FSlateFontInfo InFont)
References SetTextBlockFont().
Referenced by SetTextBlockFont().
SetTextClearKeyboardFocusOnCommit()
template<typename NumericType> void SSpinBox< NumericType >::SetTextClearKeyboardFocusOnCommit (bool bNewValue)
References SetTextClearKeyboardFocusOnCommit().
Referenced by SetTextClearKeyboardFocusOnCommit().
SetTextJustification()
template<typename NumericType> void SSpinBox< NumericType >::SetTextJustification (ETextJustify::Type InJustification)
References SetTextJustification().
Referenced by SetTextJustification().
SetTextRevertTextOnEscape()
template<typename NumericType> void SSpinBox< NumericType >::SetTextRevertTextOnEscape (bool bNewValue)
References SetTextRevertTextOnEscape().
Referenced by SetTextRevertTextOnEscape().
SetTextSelectAllTextOnCommit()
template<typename NumericType> void SSpinBox< NumericType >::SetTextSelectAllTextOnCommit (bool bNewValue)
References SetTextSelectAllTextOnCommit().
Referenced by SetTextSelectAllTextOnCommit().
SetValue()
template<typename NumericType> void SSpinBox< NumericType >::SetValue (const TAttribute< NumericType > & InValueAttribute)
References SetValue().
Referenced by SetValue().
SetWidgetStyle()
template<typename NumericType> void SSpinBox< NumericType >::SetWidgetStyle (const FSpinBoxStyle * InStyle)
References SetWidgetStyle().
Referenced by SetWidgetStyle().
SLATE_ARGUMENT() [1/2]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel SSpinBox< NumericType >::SLATE_ARGUMENT (bool , BroadcastValueChangesPerKey)
True to broadcast every time we type.
Step to increment or decrement the value by when scrolling the mouse wheel. If not specified will determine automatically
References SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and WheelStep.
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_ARGUMENT() [2/2]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth KeyboardType PreventThrottling SSpinBox< NumericType >::SLATE_ARGUMENT (bool , RevertTextOnEscape)
If the text should be reverted when pressing the escape key.
Menu extender for the right-click context menu
References SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [1/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits SSpinBox< NumericType >::SLATE_ATTRIBUTE (bool , AlwaysUsesDeltaSnap)
Whether typed values should use delta snapping, defaults to false.
Whether this spin box should have slider feature enabled, defaults to true
References AlwaysUsesDeltaSnap, EnableSlider, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit SSpinBox< NumericType >::SLATE_ATTRIBUTE (bool , SelectAllTextOnCommit)
Whether to select all text when pressing enter to commit changes.
Minimum width that a spin box should be
References MinDesiredWidth, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue SSpinBox< NumericType >::SLATE_ATTRIBUTE (bool , SupportDynamicSliderMinValue)
Tell us if we want to support dynamically changing of the min value using alt.
Called right after the max slider value is changed (only relevant if SupportDynamicSliderMaxValue is true)
References OnDynamicSliderMaxValueChanged, SLATE_ATTRIBUTE(), SLATE_EVENT(), and SupportDynamicSliderMinValue.
SLATE_ATTRIBUTE() [4/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth SSpinBox< NumericType >::SLATE_ATTRIBUTE (ETextJustify::Type , Justification)
How should the value be justified in the spinbox.
What keyboard to display.
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [5/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move SSpinBox< NumericType >::SLATE_ATTRIBUTE (float , ShiftMultiplier)
Multiplier to use when shift is held down.
Multiplier to use when ctrl is held down
References CtrlMultiplier, ShiftMultiplier, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [6/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep SSpinBox< NumericType >::SLATE_ATTRIBUTE (FSlateFontInfo , Font)
Font used to display text in the slider.
Padding to add around this widget and its internal widgets
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [7/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SSpinBox< NumericType >::SLATE_ATTRIBUTE (int32 , LinearDeltaSensitivity)
If we're an unbounded spinbox, what value do we divide mouse movement by before multiplying by Delta.
Requires Delta to be set. Tell us if we want to support dynamically changing of the max value using alt
References LinearDeltaSensitivity, SLATE_ATTRIBUTE(), and SupportDynamicSliderMaxValue.
SLATE_ATTRIBUTE() [8/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider SSpinBox< NumericType >::SLATE_ATTRIBUTE (NumericType , Delta)
Delta to increment the value as the slider moves.
If not specified will determine automatically How many pixel the mouse must move to change the value of the delta step
References Delta, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [9/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent SSpinBox< NumericType >::SLATE_ATTRIBUTE (NumericType , SliderExponentNeutralValue)
When use exponential scale for the slider which is the neutral value.
Whether this spin box should have mouse wheel feature enabled, defaults to true
References SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and SliderExponentNeutralValue.
SLATE_ATTRIBUTE() [10/13]
template<typename NumericType> Value MaxValue MaxSliderValue SSpinBox< NumericType >::SLATE_ATTRIBUTE (TOptional< int32 > , MinFractionalDigits)
The minimum fractional digits the spin box displays, defaults to 1.
The maximum fractional digits the spin box displays, defaults to 6
References MaxFractionalDigits, MinFractionalDigits, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [11/13]
template<typename NumericType> Value MaxValue SSpinBox< NumericType >::SLATE_ATTRIBUTE (TOptional< NumericType > , MinSliderValue)
The minimum value that can be specified by using the slider, defaults to MinValue.
The maximum value that can be specified by using the slider, defaults to MaxValue
References MaxSliderValue, MinSliderValue, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [12/13]
template<typename NumericType> Value SSpinBox< NumericType >::SLATE_ATTRIBUTE (TOptional< NumericType > , MinValue)
The minimum value that can be entered into the text edit box.
The maximum value that can be entered into the text edit box
References MaxValue, MinValue, and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [13/13]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth KeyboardType SSpinBox< NumericType >::SLATE_ATTRIBUTE (TSharedPtr< INumericTypeInterface< NumericType > > , TypeInterface)
Provide custom type conversion functionality to this spin box.
If refresh requests for the viewport should happen for all value changes
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
template<typename NumericType> SSpinBox< NumericType >::SLATE_BEGIN_ARGS (SSpinBox< NumericType >) inline
Definition at line 79 of file SSpinBox.h.
References DefaultMaxFractionalDigits, DefaultMinFractionalDigits, GetWidgetStyle(), Keyboard_Default, Left, and TEXT.
SLATE_END_ARGS()
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement ClearKeyboardFocusOnCommit MinDesiredWidth KeyboardType PreventThrottling ContextMenuExtender SSpinBox< NumericType >::SLATE_END_ARGS ()
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
SLATE_EVENT() [1/4]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SSpinBox< NumericType >::SLATE_EVENT (FOnDynamicSliderMinMaxValueChanged , OnDynamicSliderMinValueChanged)
Called right after the min slider value is changed (only relevant if SupportDynamicSliderMinValue is true)
Use exponential scale for the slider
References OnDynamicSliderMinValueChanged, SLATE_ATTRIBUTE(), SLATE_EVENT(), and SliderExponent.
Referenced by SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [2/4]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted OnEndSliderMovement SSpinBox< NumericType >::SLATE_EVENT (FOnGetDisplayValue , OnGetDisplayValue)
Called to allow customization of what text is displayed when not typing.
An empty value falls back to the default behavior. Whether to clear keyboard focus when pressing enter to commit changes
References OnGetDisplayValue, SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_EVENT() [3/4]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding SSpinBox< NumericType >::SLATE_EVENT (FOnValueChanged , OnValueChanged)
Called when the value is changed by slider or typing.
Called when the value is committed (by pressing enter)
References OnValueChanged, OnValueCommitted, and SLATE_EVENT().
SLATE_EVENT() [4/4]
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SliderExponent EnableWheel WheelStep ContentPadding OnValueCommitted SSpinBox< NumericType >::SLATE_EVENT (FSimpleDelegate , OnBeginSliderMovement)
Called right before the slider begins to move.
Called right after the slider handle is released by the user
References OnBeginSliderMovement, OnEndSliderMovement, and SLATE_EVENT().
SLATE_STYLE_ARGUMENT()
template<typename NumericType> SSpinBox< NumericType >::SLATE_STYLE_ARGUMENT (FSpinBoxStyle , Style)
The style used to draw this spinbox.
The value to display
References Style, and Value.
SupportsKeyboardFocus()
template<typename NumericType> virtual bool SSpinBox< NumericType >::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
References SupportsKeyboardFocus().
Referenced by SupportsKeyboardFocus().
TextField_OnTextChanged()
template<typename NumericType> void SSpinBox< NumericType >::TextField_OnTextChanged (const FText & NewText) protected
Invoked when the text in the text field changes.
Parameters
NewText The value of the text in the text field
References TextField_OnTextChanged().
Referenced by TextField_OnTextChanged().
TextField_OnTextCommitted()
template<typename NumericType> void SSpinBox< NumericType >::TextField_OnTextCommitted (const FText & NewText, ETextCommit::Type CommitInfo) protected
Invoked when the text field commits its text.
Parameters
NewText The value of text coming from the editable text field.
CommitInfo Information about the source of the commit
References TextField_OnTextCommitted().
Referenced by TextField_OnTextCommitted().
Tick()
template<typename NumericType> void SSpinBox< NumericType >::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
References Tick().
Referenced by Tick().
UpdateIsSpinRangeUnlimited()
template<typename NumericType> void SSpinBox< NumericType >::UpdateIsSpinRangeUnlimited () private
Field Documentation
ActiveFillBrush
template<typename NumericType> const FSlateBrush* SSpinBox< NumericType >::ActiveFillBrush private
Definition at line 429 of file SSpinBox.h.
AlwaysUsesDeltaSnap
template<typename NumericType> TAttribute<bool> SSpinBox< NumericType >::AlwaysUsesDeltaSnap private
Definition at line 446 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
BackgroundActiveBrush
template<typename NumericType> const FSlateBrush* SSpinBox< NumericType >::BackgroundActiveBrush private
Definition at line 427 of file SSpinBox.h.
BackgroundBrush
template<typename NumericType> const FSlateBrush* SSpinBox< NumericType >::BackgroundBrush private
Definition at line 428 of file SSpinBox.h.
BackgroundHoveredBrush
template<typename NumericType> const FSlateBrush* SSpinBox< NumericType >::BackgroundHoveredBrush private
Definition at line 426 of file SSpinBox.h.
bBroadcastValueChangesPerKey
template<typename NumericType> bool SSpinBox< NumericType >::bBroadcastValueChangesPerKey = false private
True to broadcast every time we type.
Definition at line 515 of file SSpinBox.h.
bCachedValueStringDirty
template<typename NumericType> bool SSpinBox< NumericType >::bCachedValueStringDirty mutable private
Whetever the interfaced setting changed and the CachedValueString needs to be recomputed.
Definition at line 497 of file SSpinBox.h.
bDragging
template<typename NumericType> bool SSpinBox< NumericType >::bDragging private
Whether the user is dragging the slider.
Definition at line 500 of file SSpinBox.h.
bEnableWheel
template<typename NumericType> bool SSpinBox< NumericType >::bEnableWheel = true private
Does this spin box have the mouse wheel feature enabled?
Definition at line 512 of file SSpinBox.h.
bIsTextChanging
template<typename NumericType> bool SSpinBox< NumericType >::bIsTextChanging private
Re-entrant guard for the text changed handler.
Definition at line 503 of file SSpinBox.h.
bPreventThrottling
template<typename NumericType> bool SSpinBox< NumericType >::bPreventThrottling private
Definition at line 509 of file SSpinBox.h.
bUnlimitedSpinRange
template<typename NumericType> bool SSpinBox< NumericType >::bUnlimitedSpinRange private
True when no range is specified, spinner can be spun indefinitely.
Definition at line 421 of file SSpinBox.h.
CachedExternalValue
template<typename NumericType> NumericType SSpinBox< NumericType >::CachedExternalValue private
This is the cached value the user believes it to be (usually different due to truncation to an int).
Used for identifying external forces on the spinbox and syncing the internal value to them. Synced when a value is committed to the spinbox.
Definition at line 491 of file SSpinBox.h.
CachedMousePosition
template<typename NumericType> FIntPoint SSpinBox< NumericType >::CachedMousePosition private
Cached mouse position to restore after scrolling.
Definition at line 475 of file SSpinBox.h.
CachedValueString
template<typename NumericType> FString SSpinBox< NumericType >::CachedValueString private
Used to prevent per-frame re-conversion of the cached numeric value to a string.
Definition at line 494 of file SSpinBox.h.
CtrlMultiplier
template<typename NumericType> TAttribute<float> SSpinBox< NumericType >::CtrlMultiplier private
Definition at line 436 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
DefaultMaxFractionalDigits
template<typename NumericType> int32 SSpinBox< NumericType >::DefaultMaxFractionalDigits = 6 static constexpr private
The default maximum fractional digits.
Definition at line 407 of file SSpinBox.h.
Referenced by SLATE_BEGIN_ARGS().
DefaultMinFractionalDigits
template<typename NumericType> int32 SSpinBox< NumericType >::DefaultMinFractionalDigits = 1 static constexpr private
The default minimum fractional digits.
Definition at line 404 of file SSpinBox.h.
Referenced by SLATE_BEGIN_ARGS().
Delta
template<typename NumericType> TAttribute<NumericType> SSpinBox< NumericType >::Delta private
Definition at line 434 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
DistanceDragged
template<typename NumericType> float SSpinBox< NumericType >::DistanceDragged private
Definition at line 433 of file SSpinBox.h.
EditableText
template<typename NumericType> TSharedPtr<SEditableText> SSpinBox< NumericType >::EditableText private
Definition at line 415 of file SSpinBox.h.
EnableSlider
template<typename NumericType> TAttribute<bool> SSpinBox< NumericType >::EnableSlider private
Definition at line 447 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
HoveredFillBrush
template<typename NumericType> const FSlateBrush* SSpinBox< NumericType >::HoveredFillBrush private
Definition at line 430 of file SSpinBox.h.
InactiveFillBrush
template<typename NumericType> const FSlateBrush* SSpinBox< NumericType >::InactiveFillBrush private
Definition at line 431 of file SSpinBox.h.
InterfaceAttr
template<typename NumericType> TAttribute<TSharedPtr< INumericTypeInterface<NumericType> > > SSpinBox< NumericType >::InterfaceAttr private
Interface that defines conversion functionality for the templated type.
Definition at line 418 of file SSpinBox.h.
InternalValue
template<typename NumericType> double SSpinBox< NumericType >::InternalValue private
This value represents what the spinbox believes the value to be, regardless of delta and the user binding to an int.
The spinbox will always count using floats between values, this is important to keep it flowing smoothly and feeling right, and most importantly not conflicting with the user truncating the value to an int.
Definition at line 482 of file SSpinBox.h.
LinearDeltaSensitivity
template<typename NumericType> TAttribute<int32> SSpinBox< NumericType >::LinearDeltaSensitivity private
Definition at line 437 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
MaxFractionalDigits
template<typename NumericType> TAttribute< TOptional<int32> > SSpinBox< NumericType >::MaxFractionalDigits private
Definition at line 445 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
MaxSliderValue
template<typename NumericType> TAttribute< TOptional<NumericType> > SSpinBox< NumericType >::MaxSliderValue private
Definition at line 443 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
MaxValue
template<typename NumericType> TAttribute< TOptional<NumericType> > SSpinBox< NumericType >::MaxValue private
Definition at line 441 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
MinDesiredWidth
template<typename NumericType> TAttribute<float> SSpinBox< NumericType >::MinDesiredWidth private
Prevents the spinbox from being smaller than desired in certain cases (e.g.
when it is empty)
Definition at line 456 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
MinFractionalDigits
template<typename NumericType> TAttribute< TOptional<int32> > SSpinBox< NumericType >::MinFractionalDigits private
Definition at line 444 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
MinSliderValue
template<typename NumericType> TAttribute< TOptional<NumericType> > SSpinBox< NumericType >::MinSliderValue private
Definition at line 442 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
MinValue
template<typename NumericType> TAttribute< TOptional<NumericType> > SSpinBox< NumericType >::MinValue private
Definition at line 440 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
OnBeginSliderMovement
template<typename NumericType> FSimpleDelegate SSpinBox< NumericType >::OnBeginSliderMovement private
Definition at line 412 of file SSpinBox.h.
Referenced by SLATE_EVENT().
OnDynamicSliderMaxValueChanged
template<typename NumericType> FOnDynamicSliderMinMaxValueChanged SSpinBox< NumericType >::OnDynamicSliderMaxValueChanged private
Definition at line 451 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
OnDynamicSliderMinValueChanged
template<typename NumericType> FOnDynamicSliderMinMaxValueChanged SSpinBox< NumericType >::OnDynamicSliderMinValueChanged private
Definition at line 452 of file SSpinBox.h.
Referenced by SLATE_EVENT().
OnEndSliderMovement
template<typename NumericType> FOnValueChanged SSpinBox< NumericType >::OnEndSliderMovement private
Definition at line 413 of file SSpinBox.h.
Referenced by SLATE_EVENT().
OnGetDisplayValue
template<typename NumericType> FOnGetDisplayValue SSpinBox< NumericType >::OnGetDisplayValue private
Definition at line 453 of file SSpinBox.h.
Referenced by SLATE_EVENT().
OnValueChanged
template<typename NumericType> FOnValueChanged SSpinBox< NumericType >::OnValueChanged private
Definition at line 410 of file SSpinBox.h.
Referenced by SLATE_EVENT().
OnValueCommitted
template<typename NumericType> FOnValueCommitted SSpinBox< NumericType >::OnValueCommitted private
Definition at line 411 of file SSpinBox.h.
Referenced by SLATE_EVENT().
PendingCommitValue
template<typename NumericType> TOptional<FPendingCommitValue> SSpinBox< NumericType >::PendingCommitValue private
Definition at line 517 of file SSpinBox.h.
PointerDraggingSliderIndex
template<typename NumericType> int32 SSpinBox< NumericType >::PointerDraggingSliderIndex private
Tracks which cursor is currently dragging the slider (e.g., the mouse cursor or a specific finger)
Definition at line 472 of file SSpinBox.h.
PreDragValue
template<typename NumericType> NumericType SSpinBox< NumericType >::PreDragValue private
The state of InternalValue before a drag operation was started.
Definition at line 485 of file SSpinBox.h.
ShiftMouseMovePixelPerDelta
template<typename NumericType> Value MaxValue MaxSliderValue MaxFractionalDigits EnableSlider SSpinBox< NumericType >::ShiftMouseMovePixelPerDelta
Definition at line 131 of file SSpinBox.h.
ShiftMultiplier
template<typename NumericType> TAttribute<float> SSpinBox< NumericType >::ShiftMultiplier private
Definition at line 435 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
SliderExponent
template<typename NumericType> TAttribute<float> SSpinBox< NumericType >::SliderExponent private
Definition at line 438 of file SSpinBox.h.
Referenced by SLATE_EVENT().
SliderExponentNeutralValue
template<typename NumericType> TAttribute<NumericType> SSpinBox< NumericType >::SliderExponentNeutralValue private
Definition at line 439 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
SmallStepSize
template<typename NumericType> const double SSpinBox< NumericType >::SmallStepSize = .1f private
Step size to use when range is below SmallStepSizeMax.
Definition at line 529 of file SSpinBox.h.
SmallStepSizeMax
template<typename NumericType> const double SSpinBox< NumericType >::SmallStepSizeMax = 10.f private
Largest numerical value to use the SmallStepSize instead of StepSize.
Definition at line 532 of file SSpinBox.h.
StepSize
template<typename NumericType> const double SSpinBox< NumericType >::StepSize = 1.f private
Gets the default amount to change the slider when delta is not applicable.
Definition at line 526 of file SSpinBox.h.
Style
template<typename NumericType> const FSpinBoxStyle* SSpinBox< NumericType >::Style private
Definition at line 424 of file SSpinBox.h.
Referenced by SLATE_STYLE_ARGUMENT().
SupportDynamicSliderMaxValue
template<typename NumericType> TAttribute<bool> SSpinBox< NumericType >::SupportDynamicSliderMaxValue private
Definition at line 448 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
SupportDynamicSliderMinValue
template<typename NumericType> TAttribute<bool> SSpinBox< NumericType >::SupportDynamicSliderMinValue private
Definition at line 449 of file SSpinBox.h.
Referenced by SLATE_ATTRIBUTE().
TextBlock
template<typename NumericType> TSharedPtr<STextBlock> SSpinBox< NumericType >::TextBlock private
Definition at line 414 of file SSpinBox.h.
ValueAttribute
template<typename NumericType> TAttribute<NumericType> SSpinBox< NumericType >::ValueAttribute private
Definition at line 409 of file SSpinBox.h.
WheelStep
template<typename NumericType> TAttribute< TOptional<NumericType> > SSpinBox< NumericType >::WheelStep private
Definition at line 450 of file SSpinBox.h.
Referenced by SLATE_ARGUMENT().
The documentation for this class was generated from the following file:
SSpinBox.h