Unreal Engine 5.6 C++ API: UE::Anim Namespace Reference
UE::Anim Namespace Reference
Namespaces
namespace AnimationData
namespace Compression
namespace Conversion
namespace DataModel
namespace Decompression
namespace Private
namespace RetargetHelpers
namespace Retargeting
Data Structures
struct Attributes
Helper functionality for attributes animation runtime.
struct AttributeTypes
struct CBlendableAttribute
Concept used to verify a user-defined attribute type with its TAttributeTypeTraits::Blendable value set to true.
struct CNormalizedAttribute
Concept used to verify a user-defined attribute type with its TAttributeTypeTraits::RequiresNormalization value set to true.
class FActiveStateMachineScope
class FAnimBlendDebugScope
class FAnimInertializationSyncScope
class FAnimNotifyEndDataContext
class FAnimNotifyMirrorContext
class FAnimNotifyMontageInstanceContext
class FAnimNotifyStateMachineContext
struct FAnimPoseDecompressionData
struct FAnimSync
struct FAnimSyncDebugInfo
class FAnimSyncGroupScope
struct FAnimSyncParams
struct FAttributeBlendData
struct FAttributeId
Runtime identifier for an attribute.
struct FAttributes
struct FBaseBlendedCurve_DEPRECATED
struct FBuildRawPoseScratchArea
struct FBulkCurveFlags
Named value array used for bulk storage of curve flags.
struct FBulkCurves
Named value array used for bulk get/set of curves.
struct FCachedPoseScope
RAII helper for cached pose lifetimes (as they are stored on the mem stack)
class FCachedPoseSkippedUpdateHandler
struct FCurveElement
struct FCurveElementFlags
struct FCurveElementIndexed
struct FCurveFilter
Named value array that can act as a filter, creating allow/deny lists of curve names.
struct FCurveFilterElement
struct FCurveFilterSettings
Options for filtering curves.
struct FCurveUtils
struct FHeapAttributeContainer
struct FHeapAttributeContainerAccessor
struct FMeshAttributeContainer
struct FMessageStack
class FMirrorSyncScope
struct FNamedIndexElement
Name/index pair, used in FBulkCurves.
struct FNamedValueArrayUtils
struct FNodeDataId
struct FNodeFunctionCaller
class FNonBlendableAttributeBlendOperator
struct FScopedGraphMessage
struct FScopedGraphTag
class FSkeletonRemappingRegistry
struct FSkinnedMeshComponentExtensions
struct FStackAttributeContainer
struct FStackAttributeContainerAccessor
class IAnimEventsFilterContext
class IAnimNotifyEventContextDataInterface
class IAnimRootMotionProvider
class IAnimSequenceCompilingManager
class IAttributeBlendOperator
Interface required to implement for user-defined blending behaviour of an animation attribute type.
class IGraphMessage
class IInertializationRequester
class IPoseSearchProvider
Modular feature interface for PoseSearch.
class TAttributeBlendOperator
Default blend operator used for any registered attribute type, when no user-defined operator has been specified Using TEnableIf to select appropriate behaviour according to TAttributeTypeTraits<Type>::IsBlendable value for AttributeType template.
struct TAttributeContainer
Runtime container for Animation Attributes, providing a TMap like interface.
struct TAttributeContainerAccessor
Accessor for internal data of the TAttributeContainer.
struct TAttributeTypeTraits
struct TAttributeTypeTraits< FIntegerAnimationAttribute >
Integer attribute is step-interpolated by default.
struct TAttributeTypeTraits< FNonBlendableFloatAnimationAttribute >
struct TAttributeTypeTraits< FNonBlendableIntegerAnimationAttribute >
struct TAttributeTypeTraits< FNonBlendableQuaternionAnimationAttribute >
Non blendable types.
struct TAttributeTypeTraits< FNonBlendableTransformAnimationAttribute >
Non blendable types.
struct TAttributeTypeTraits< FNonBlendableVectorAnimationAttribute >
Non blendable types.
struct TAttributeTypeTraits< FQuaternionAnimationAttribute >
Quaternion attribute requires normalization.
struct TAttributeTypeTraits< FStringAnimationAttribute >
String attribute is not blend-able by default.
struct TAttributeTypeTraits< FTransformAnimationAttribute >
Transform attribute requires normalization.
struct TAttributeTypeTraitsBase
Set of type-traits, used by the Animation Attributes system to verify and implement certain behavior.
struct TNamedValueArray
Container of lazily-sorted name/value pairs.
struct TOptionalScopedGraphMessage
struct TScopedGraphMessage
class TTypedIndexRange
struct TWrappedAttribute
Helper struct to wrap and templated operate raw memory.
Typedefs
using FSlotInertializationRequest = TPair<float, const UBlendProfile*>
template<typename IndexType, typename ... TArrayArgs>
using TTypedIndexArray = TTypedIndexRange<IndexType, TArray<TArrayArgs...>>
template<typename IndexType, typename ... TArrayViewArgs>
using TTypedIndexArrayView = TTypedIndexRange<IndexType, TArrayView<TArrayViewArgs...>>
Enumerations
enum class ECurveElementFlags : uint8 { None = 0 , Material = 0x01 , MorphTarget = 0x02 }
enum class ECurveFilterFlags : uint8 { None = 0 , Disallowed = 0x01 , Filtered = 0x02 }
enum class ECurveFilterMode : uint8 { None , DisallowAll , AllowOnlyFiltered , DisallowFiltered }
enum class ENamedValueUnionFlags : uint8 { None = 0 , ValidArg0 = 0x01 , ValidArg1 = 0x02 , BothArgsValid = ValidArg0 | ValidArg1 }
Functions
template<typename AttributeType, typename ValueType>
bool AddTypedCustomAttribute (const FName &AttributeName, const FName &BoneName, UAnimSequenceBase *AnimSequenceBase, TArrayView< const float > Keys, TArrayView< const ValueType > Values, bool bShouldTransact=true)
Helper functionality allowing the user to add an attribute with a typed value array.
static FName BoneAttributeNamespace ("bone")
void BuildPoseFromModel (const IAnimationDataModel *Model, FAnimationPoseData &OutPoseData, const double Time, const EAnimInterpolationType &InterpolationType, const FName &RetargetSource, const TArray< FTransform > &RetargetTransforms)
Populates a FAnimationPoseData according to the data stored within a IAnimationDataModel provided a time to sample.
void CopyCurveDataToModel (const FRawCurveTracks &CurveData, const USkeleton *Skeleton, IAnimationDataController &Controller)
Copies over any individual curve from FRawCurveTracks to a IAnimationDataModel instance targeted by the provided controller.
bool CopyNotifies (const UAnimSequenceBase *SourceAnimSeq, UAnimSequenceBase *DestAnimSeq, bool bShowDialogs=true, bool bDeleteExistingNotifies=false)
Copies over any individual curve from FRawCurveTracks to a IAnimationDataModel instance targeted by the provided controller.
ENUM_CLASS_FLAGS (ECurveElementFlags)
ENUM_CLASS_FLAGS (ECurveFilterFlags)
void EvaluateFloatCurvesFromModel (const IAnimationDataModel *Model, FBlendedCurve &OutCurves, double Time)
Populates float curves according to the data stored within a IAnimationDataModel provided a time to sample.
void EvaluateTransformCurvesFromModel (const IAnimationDataModel *Model, TMap< FName, FTransform > &OutCurves, double Time, float BlendWeight)
Populates transform curves according to the data stored within a IAnimationDataModel provided a time to sample.
void ExtractBoneTransform (const struct FRawAnimSequenceTrack &RawTrack, FTransform &OutTransform, int32 KeyIndex)
Extract Bone Transform of the Time given, from the provided FRawAnimSequenceTrack.
FTransform ExtractRootMotionFromAnimationAsset (const UAnimationAsset *Animation, const UMirrorDataTable *MirrorDataTable, float StartPosition, float EndPosition)
Extract relative root motion between start and end position of the animation asset.
FTransform ExtractRootMotionFromAnimationAsset (const UAnimationAsset *Animation, const UMirrorDataTable *MirrorDataTable, float StartTime, float DeltaTime, bool bAllowLooping)
Extract relative root motion between start and end position of the animation asset.
FTransform ExtractRootTransformFromAnimationAsset (const UAnimationAsset *Animation, float Position)
Extract absolute root transform at specific position in time from the animation asset.
FTransform MirrorTransform (const FTransform &Transform, const UMirrorDataTable &MirrorDataTable)
Mirrors transform based on the specified mirror table.
UE_DEPRECATED (5.1, "Use BuildPoseFromModel with different signature instead") 1 void BuildPoseFromModel(const IAnimationDataModel *Model
Populates a FCompactPose according to the data stored within a IAnimationDataModel provided a time to sample.
UE_DEPRECATED (5.2, "GetBoneTransformFromModel with TrackIndex has been deprecated, use IAnimationDataModel::GetBoneTrackTransform instead") 1 void GetBoneTransformFromModel(const IAnimationDataModel *Model
Retrieves a single bone transform according to the data stored within a IAnimationDataModel provided a time and track to sample.
Variables
TAutoConsoleVariable< bool > CVarOutputMontageFrameRateWarning
FTransform int32 double const EAnimInterpolationType & Interpolation
FCompactPose const float const EAnimInterpolationType & InterpolationType
FTransform int32 int32 KeyIndex
FCompactPose & OutPose
FTransform & OutTransform
FCompactPose const float const EAnimInterpolationType const FName & RetargetSource
FCompactPose const float const EAnimInterpolationType const FName const TArray< FTransform > & RetargetTransforms
FCompactPose const float Time
FTransform int32 TrackIndex
Typedef Documentation
FSlotInertializationRequest
typedef TPair< float, const UBlendProfile * > UE::Anim::FSlotInertializationRequest = TPair<float, const UBlendProfile*>
Definition at line 55 of file AnimInstance.h.
TTypedIndexArray
template<typename IndexType, typename ... TArrayArgs> using UE::Anim::TTypedIndexArray = TTypedIndexRange<IndexType, TArray<TArrayArgs...>>
Definition at line 99 of file CustomBoneIndexArray.h.
TTypedIndexArrayView
template<typename IndexType, typename ... TArrayViewArgs> using UE::Anim::TTypedIndexArrayView = TTypedIndexRange<IndexType, TArrayView<TArrayViewArgs...>>
Definition at line 102 of file CustomBoneIndexArray.h.
Enumeration Type Documentation
ECurveElementFlags
enum class UE::Anim::ECurveElementFlags : uint8 strong
Enumerator
None
Material
MorphTarget
Definition at line 12 of file AnimCurveElementFlags.h.
ECurveFilterFlags
enum class UE::Anim::ECurveFilterFlags : uint8 strong
Enumerator
None
Disallowed
Filtered
Definition at line 17 of file AnimCurveFilter.h.
ECurveFilterMode
enum class UE::Anim::ECurveFilterMode : uint8 strong
Enumerator
None
DisallowAll
AllowOnlyFiltered
DisallowFiltered
Definition at line 34 of file AnimCurveFilter.h.
ENamedValueUnionFlags
enum class UE::Anim::ENamedValueUnionFlags : uint8 strong
Enumerator
None
ValidArg0
ValidArg1
BothArgsValid
Definition at line 236 of file NamedValueArray.h.
Function Documentation
AddTypedCustomAttribute()
template<typename AttributeType, typename ValueType> bool UE::Anim::AddTypedCustomAttribute (const FName & AttributeName, const FName & BoneName, UAnimSequenceBase * AnimSequenceBase, TArrayView< const float > Keys, TArrayView< const ValueType > Values, bool bShouldTransact = true)
Helper functionality allowing the user to add an attribute with a typed value array.
Definition at line 381 of file BuiltInAttributeTypes.h.
References AddTypedCustomAttribute(), Attribute, MakeArrayView(), IAnimationDataController::SetTypedAttributeKeys(), Algo::Transform(), and Value.
Referenced by AddTypedCustomAttribute().
BoneAttributeNamespace()
FName UE::Anim::BoneAttributeNamespace ("bone") static
Referenced by UE::Anim::FAttributeId::FAttributeId().
BuildPoseFromModel()
void UE::Anim::BuildPoseFromModel (const IAnimationDataModel * Model, FAnimationPoseData & OutPoseData, const double Time, const EAnimInterpolationType & InterpolationType, const FName & RetargetSource, const TArray< FTransform > & RetargetTransforms)
Populates a FAnimationPoseData according to the data stored within a IAnimationDataModel provided a time to sample.
Parameters
Model Model to sample from
OutPoseData [out] Pose data to be populated using the model
Time Time value to sample at
InterpolationType Method to be used to interpolate between different sample points
RetargetSource Name of the retarget source to retrieve from the skeleton
RetargetTransforms Base transforms to use when retargetting the pose
References BuildPoseFromModel(), InterpolationType, RetargetSource, RetargetTransforms, and Time.
Referenced by BuildPoseFromModel().
CopyCurveDataToModel()
void UE::Anim::CopyCurveDataToModel (const FRawCurveTracks & CurveData, const USkeleton * Skeleton, IAnimationDataController & Controller)
Copies over any individual curve from FRawCurveTracks to a IAnimationDataModel instance targeted by the provided controller.
Parameters
CurveData Container of the curves to be copied over
Skeleton Skeleton to use for verifying and or add the curve names
Controller Controller to use for adding curve data to a model
References CopyCurveDataToModel(), and Skeleton.
Referenced by CopyCurveDataToModel().
CopyNotifies()
bool UE::Anim::CopyNotifies (const UAnimSequenceBase * SourceAnimSeq, UAnimSequenceBase * DestAnimSeq, bool bShowDialogs = true, bool bDeleteExistingNotifies = false)
Copies over any individual curve from FRawCurveTracks to a IAnimationDataModel instance targeted by the provided controller.
Parameters
SourceAnimSeq Animation Sequence to copy the notifies from
DestAnimSeq Animation Sequence to copy the notifies to
bShowDialogs Whether or not to show any user-facing dialogs for confirmation of the copy
bDeleteExistingNotifies Whether or not to delete all notifies found on the destination sequence
Returns
Whether or not the copy was succesful
References CopyNotifies().
Referenced by CopyNotifies().
ENUM_CLASS_FLAGS() [1/2]
UE::Anim::ENUM_CLASS_FLAGS (ECurveElementFlags)
ENUM_CLASS_FLAGS() [2/2]
UE::Anim::ENUM_CLASS_FLAGS (ECurveFilterFlags)
EvaluateFloatCurvesFromModel()
void UE::Anim::EvaluateFloatCurvesFromModel (const IAnimationDataModel * Model, FBlendedCurve & OutCurves, double Time)
Populates float curves according to the data stored within a IAnimationDataModel provided a time to sample.
Parameters
Model Model to sample from
OutCurves [out] Curves to be populated using the model
Time Time value to sample at
References EvaluateFloatCurvesFromModel(), and Time.
Referenced by EvaluateFloatCurvesFromModel().
EvaluateTransformCurvesFromModel()
void UE::Anim::EvaluateTransformCurvesFromModel (const IAnimationDataModel * Model, TMap< FName, FTransform > & OutCurves, double Time, float BlendWeight)
Populates transform curves according to the data stored within a IAnimationDataModel provided a time to sample.
Parameters
Model Model to sample from
OutCurves [out] Curves which were sampled from the model, key-ed with their equivalent name
Time Time value to sample at
BlendWeight Blending weight to apply when sampling
References EvaluateTransformCurvesFromModel(), and Time.
Referenced by EvaluateTransformCurvesFromModel().
ExtractBoneTransform()
void UE::Anim::ExtractBoneTransform (const struct FRawAnimSequenceTrack & RawTrack, FTransform & OutTransform, int32 KeyIndex)
Extract Bone Transform of the Time given, from the provided FRawAnimSequenceTrack.
Parameters
RawTrack RawAnimationTrack it extracts bone transform from
OutAtom [out] Output bone transform.
KeyIndex Key index to retrieve from the track.
References KeyIndex, and OutTransform.
ExtractRootMotionFromAnimationAsset() [1/2]
FTransform UE::Anim::ExtractRootMotionFromAnimationAsset (const UAnimationAsset * Animation, const UMirrorDataTable * MirrorDataTable, float StartPosition, float EndPosition)
Extract relative root motion between start and end position of the animation asset.
Parameters
Animation Animation asset to extract the root motion from.
MirrorDataTable [optional] Animation data mirroring data table.
StartPosition Start Position of the animation.
EndPosition End Position of the animation.
ExtractRootMotionFromAnimationAsset() [2/2]
FTransform UE::Anim::ExtractRootMotionFromAnimationAsset (const UAnimationAsset * Animation, const UMirrorDataTable * MirrorDataTable, float StartTime, float DeltaTime, bool bAllowLooping)
Extract relative root motion between start and end position of the animation asset.
With optional looping if applicable. NOTE WELL: Our second time param is a delta time, not an end like like other variations of this API.
Parameters
Animation Animation asset to extract the root motion from.
MirrorDataTable [optional] Animation data mirroring data table.
StartTime Start Position of the animation.
DeltaTime Delta time to Advance, can be negative.
bAllowLooping True if we should accumulate and loop.
References DeltaTime.
ExtractRootTransformFromAnimationAsset()
FTransform UE::Anim::ExtractRootTransformFromAnimationAsset (const UAnimationAsset * Animation, float Position)
Extract absolute root transform at specific position in time from the animation asset.
Note: this function applies skeleton reference pose the transform (similar to ExtractRootMotionFromAnimationAsset, but unlike UAnimSequence::ExtractRootTrackTransform()).
Parameters
Animation Animation asset to extract the root motion from.
Position Start Position of the animation.
References Position.
MirrorTransform()
FTransform UE::Anim::MirrorTransform (const FTransform & Transform, const UMirrorDataTable & MirrorDataTable)
Mirrors transform based on the specified mirror table.
Parameters
Transform Transform to mirror
MirrorDataTable Animation data mirroring data table.
Returns
Transform mirrored based on the mirror data table.
References Transform.
UE_DEPRECATED() [1/2]
UE::Anim::UE_DEPRECATED (5. 1, "Use BuildPoseFromModel with different signature instead") const
Populates a FCompactPose according to the data stored within a IAnimationDataModel provided a time to sample.
Parameters
Model Model to sample from
OutPose [out] Pose to be populated using the model
Time Time value to sample at
InterpolationType Method to be used to interpolate between different sample points
RetargetSource Name of the retarget source to retrieve from the skeleton
RetargetTransforms Base transforms to use when retargetting the pose
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Anim::UE_DEPRECATED (5. 2, "GetBoneTransformFromModel with TrackIndex has been deprecated , use IAnimationDataModel::GetBoneTrackTransform instead") const
Retrieves a single bone transform according to the data stored within a IAnimationDataModel provided a time and track to sample.
Retrieves a single bone transform according to the data stored within a IAnimationDataModel provided a key and track to sample.
Parameters
Model Model to sample from
OutTransform [out] Transform which was sampled from the model
TrackIndex Track / bone index which should be sampld
Time Time value to sample at
InterpolationType Method to be used to interpolate between different sample points
Model Model to sample from
OutTransform [out] Transform which was sampled from the model
TrackIndex Track / bone index which should be sampld
KeyIndex Specific key index to sample
References UE_DEPRECATED().
Variable Documentation
CVarOutputMontageFrameRateWarning
TAutoConsoleVariable<bool> UE::Anim::CVarOutputMontageFrameRateWarning extern
Interpolation
FTransform int32 double const EAnimInterpolationType& UE::Anim::Interpolation
Definition at line 86 of file AnimSequenceHelpers.h.
InterpolationType
FCompactPose const float const EAnimInterpolationType& UE::Anim::InterpolationType
Definition at line 43 of file AnimSequenceHelpers.h.
Referenced by BuildPoseFromModel().
KeyIndex
FTransform int32 int32 UE::Anim::KeyIndex
Definition at line 97 of file AnimSequenceHelpers.h.
Referenced by ExtractBoneTransform().
OutPose
FCompactPose& UE::Anim::OutPose
Definition at line 43 of file AnimSequenceHelpers.h.
Referenced by UE::Anim::Decompression::DecompressPose(), and UE::Anim::Decompression::DecompressPose().
OutTransform
FTransform & UE::Anim::OutTransform
Definition at line 86 of file AnimSequenceHelpers.h.
Referenced by ExtractBoneTransform().
RetargetSource
FCompactPose const float const EAnimInterpolationType const FName& UE::Anim::RetargetSource
Definition at line 43 of file AnimSequenceHelpers.h.
Referenced by BuildPoseFromModel(), and UE::Anim::Decompression::DecompressPose().
RetargetTransforms
FCompactPose const float const EAnimInterpolationType const FName const TArray<FTransform>& UE::Anim::RetargetTransforms
Definition at line 43 of file AnimSequenceHelpers.h.
Referenced by BuildPoseFromModel(), and UE::Anim::Decompression::DecompressPose().
Time
FTransform int32 double UE::Anim::Time
Definition at line 43 of file AnimSequenceHelpers.h.
Referenced by BuildPoseFromModel(), EvaluateFloatCurvesFromModel(), and EvaluateTransformCurvesFromModel().
TrackIndex
FTransform int32 UE::Anim::TrackIndex
Definition at line 86 of file AnimSequenceHelpers.h.