Unreal Engine 5.6 C++ API: FCachedLandscapeFoliage::FGrassComp Struct Reference
FCachedLandscapeFoliage::FGrassComp Struct Reference
#include "LandscapeProxy.h"
Public Member Functions
FGrassComp ()
void Touch ()
Data Fields
TArray< FBox > ExcludedBoxes
uint32 ExclusionChangeTag
TWeakObjectPtr< UHierarchicalInstancedStaticMeshComponent > Foliage
FGrassCompKey Key
uint32 LastUsedFrameNumber
double LastUsedTime
bool Pending
bool PendingRemovalRebuild
TWeakObjectPtr< UHierarchicalInstancedStaticMeshComponent > PreviousFoliage
Detailed Description
Definition at line 302 of file LandscapeProxy.h.
Constructor & Destructor Documentation
FGrassComp()
FCachedLandscapeFoliage::FGrassComp::FGrassComp () inline
Definition at line 314 of file LandscapeProxy.h.
References ExclusionChangeTag, Pending, PendingRemovalRebuild, and Touch().
Member Function Documentation
Touch()
void FCachedLandscapeFoliage::FGrassComp::Touch () inline
Definition at line 321 of file LandscapeProxy.h.
References GFrameNumber, LastUsedFrameNumber, LastUsedTime, and FAndroidTime::Seconds().
Referenced by FGrassComp().
Field Documentation
ExcludedBoxes
TArray<FBox> FCachedLandscapeFoliage::FGrassComp::ExcludedBoxes
Definition at line 307 of file LandscapeProxy.h.
ExclusionChangeTag
uint32 FCachedLandscapeFoliage::FGrassComp::ExclusionChangeTag
Definition at line 309 of file LandscapeProxy.h.
Referenced by FGrassComp().
Foliage
TWeakObjectPtr<UHierarchicalInstancedStaticMeshComponent> FCachedLandscapeFoliage::FGrassComp::Foliage
Definition at line 305 of file LandscapeProxy.h.
Key
FGrassCompKey FCachedLandscapeFoliage::FGrassComp::Key
Definition at line 304 of file LandscapeProxy.h.
Referenced by FCachedLandscapeFoliage::FGrassCompKeyFuncs::GetSetKey().
LastUsedFrameNumber
uint32 FCachedLandscapeFoliage::FGrassComp::LastUsedFrameNumber
Definition at line 308 of file LandscapeProxy.h.
Referenced by Touch().
LastUsedTime
double FCachedLandscapeFoliage::FGrassComp::LastUsedTime
Definition at line 310 of file LandscapeProxy.h.
Referenced by Touch().
Pending
bool FCachedLandscapeFoliage::FGrassComp::Pending
Definition at line 311 of file LandscapeProxy.h.
Referenced by FGrassComp().
PendingRemovalRebuild
bool FCachedLandscapeFoliage::FGrassComp::PendingRemovalRebuild
Definition at line 312 of file LandscapeProxy.h.
Referenced by FGrassComp().
PreviousFoliage
TWeakObjectPtr<UHierarchicalInstancedStaticMeshComponent> FCachedLandscapeFoliage::FGrassComp::PreviousFoliage
Definition at line 306 of file LandscapeProxy.h.
The documentation for this struct was generated from the following file:
LandscapeProxy.h