Unreal Engine 5.6 C++ API: FVertexBuffer Class Reference
FVertexBuffer Class Reference
A vertex buffer resource.
#include "RenderResource.h"
Public Member Functions
RENDERCORE_API FVertexBuffer ()
RENDERCORE_API FVertexBuffer (const FVertexBuffer &)
virtual RENDERCORE_API ~FVertexBuffer ()
virtual RENDERCORE_API FString GetFriendlyName () const override
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FVertexBuffer & operator= (const FVertexBuffer &Other)
virtual RENDERCORE_API void ReleaseRHI () override
Releases the RHI resources used by this resource.
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
FBufferRHIRef VertexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A vertex buffer resource.
Definition at line 470 of file RenderResource.h.
Constructor & Destructor Documentation
FVertexBuffer() [1/2]
RENDERCORE_API FVertexBuffer::FVertexBuffer ()
Referenced by FVertexBuffer(), and operator=().
FVertexBuffer() [2/2]
RENDERCORE_API FVertexBuffer::FVertexBuffer (const FVertexBuffer &)
References FVertexBuffer().
~FVertexBuffer()
virtual RENDERCORE_API FVertexBuffer::~FVertexBuffer () virtual
Member Function Documentation
GetFriendlyName()
virtual RENDERCORE_API FString FVertexBuffer::GetFriendlyName () const override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FRenderResource.
Reimplemented in FColorVertexBuffer, FPositionVertexBuffer, FSkeletalMeshVertexClothBuffer, FSkinWeightDataVertexBuffer, FSkinWeightLookupVertexBuffer, FStaticMeshInstanceBuffer::FInstanceCustomDataBuffer, FStaticMeshInstanceBuffer::FInstanceLightmapBuffer, FStaticMeshInstanceBuffer::FInstanceOriginBuffer, FStaticMeshInstanceBuffer::FInstanceTransformBuffer, FStaticMeshVertexBuffer::FTangentsVertexBuffer, FStaticMeshVertexBuffer::FTexcoordVertexBuffer, UE::ChaosDeformable::FFloatArrayBufferWithSRV, UE::ChaosDeformable::FHalfArrayBufferWithSRV, and UE::ChaosDeformable::FIndexArrayBufferWithSRV.
Referenced by FLocalVertexFactory::GetColorOverrideStream().
GetRHI()
const FBufferRHIRef & FVertexBuffer::GetRHI () const inline
Definition at line 482 of file RenderResource.h.
References VertexBufferRHI.
operator=()
RENDERCORE_API FVertexBuffer & FVertexBuffer::operator= (const FVertexBuffer & Other)
References FVertexBuffer(), and Other.
ReleaseRHI()
virtual RENDERCORE_API void FVertexBuffer::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
Reimplemented in FColorVertexBuffer, FGPUSortManager::FValueBuffer, FNullColorVertexBuffer, FNullVertexBuffer, FParticleScratchVertexBuffer, FPositionVertexBuffer, FPrimitiveIdDummyBuffer, FRDGWrapperVertexBuffer, FSkeletalMeshVertexClothBuffer, FSkinWeightDataVertexBuffer, FSkinWeightLookupVertexBuffer, FSubUVBoundingGeometryBuffer, FVertexBufferWithSRV, and FWaterMeshVertexBuffer.
Referenced by FPrimitiveIdDummyBuffer::ReleaseRHI(), and FWaterMeshVertexBuffer::ReleaseRHI().
SetRHI()
RENDERCORE_API void FVertexBuffer::SetRHI (const FBufferRHIRef & BufferRHI)
Field Documentation
VertexBufferRHI
FBufferRHIRef FVertexBuffer::VertexBufferRHI
Definition at line 486 of file RenderResource.h.
Referenced by FLocalVertexFactory::GetColorOverrideStream(), GetRHI(), FNullDynamicParameterVertexBuffer::InitRHI(), FRDGWrapperVertexBuffer::InitRHI(), FWaterMeshVertexBuffer::InitRHI(), and FRDGWrapperVertexBuffer::ReleaseRHI().
The documentation for this class was generated from the following file:
RenderResource.h