Unreal Engine 5.6 C++ API: TActorDescList< DescType >::TBaseIterator< bConst, ActorType > Class Template Reference
TActorDescList< DescType >::TBaseIterator< bConst, ActorType > Class Template Reference
#include "ActorDescList.h"
Public Member Functions
TBaseIterator (ListType InActorDescList, UClass *InActorClass)
FORCEINLINE UClass * GetActorClass () const
Returns the actor class on which the iterator iterates on.
FORCEINLINE operator bool () const
Returns whether the iterator has reached the end and no longer points to a suitable actor desc.
FORCEINLINE ReturnType operator* () const
Returns the current suitable actor desc pointed at by the Iterator.
FORCEINLINE void operator++ ()
Iterates to next suitable actor desc.
FORCEINLINE ReturnType operator-> () const
Returns the current suitable actor desc pointed at by the Iterator.
FORCEINLINE void RemoveCurrent ()
Removes the current iterator element.
Protected Types
using IteratorType = std::conditional_t<bConst, typename MapType::TConstIterator, typename MapType::TIterator>
using ListType = std::conditional_t<bConst, const TActorDescList<DescType>*, TActorDescList<DescType>*>
using MapType = FGuidActorDescMap
using ReturnType = std::conditional_t<bConst, const ValueType*, ValueType*>
using ValueType = typename TActorDescListIteratorValueType<DescType, ActorType>::Type
Protected Member Functions
FORCEINLINE bool ShouldSkip () const
Determines whether the iterator currently points to a valid actor desc or not.
Protected Attributes
UClass * ActorClass
IteratorType ActorsIterator
bool bIsProxy
Detailed Description
template<class DescType>
template<bool bConst, class ActorType>
class TActorDescList< DescType >::TBaseIterator< bConst, ActorType >
Definition at line 54 of file ActorDescList.h.
Member Typedef Documentation
IteratorType
template<class DescType> template<bool bConst, class ActorType> using TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::IteratorType = std::conditional_t<bConst, typename MapType::TConstIterator, typename MapType::TIterator> protected
Definition at line 61 of file ActorDescList.h.
ListType
template<class DescType> template<bool bConst, class ActorType> using TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::ListType = std::conditional_t<bConst, const TActorDescList<DescType>*, TActorDescList<DescType>*> protected
Definition at line 62 of file ActorDescList.h.
MapType
template<class DescType> template<bool bConst, class ActorType> using TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::MapType = FGuidActorDescMap protected
Definition at line 59 of file ActorDescList.h.
ReturnType
template<class DescType> template<bool bConst, class ActorType> using TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::ReturnType = std::conditional_t<bConst, const ValueType*, ValueType*> protected
Definition at line 63 of file ActorDescList.h.
ValueType
template<class DescType> template<bool bConst, class ActorType> using TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::ValueType = typename TActorDescListIteratorValueType<DescType, ActorType>::Type protected
Definition at line 60 of file ActorDescList.h.
Constructor & Destructor Documentation
TBaseIterator()
template<class DescType> template<bool bConst, class ActorType> TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::TBaseIterator (ListType InActorDescList, UClass * InActorClass) inline
Definition at line 66 of file ActorDescList.h.
Member Function Documentation
GetActorClass()
template<class DescType> template<bool bConst, class ActorType> FORCEINLINE UClass * TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::GetActorClass () const inline
Returns the actor class on which the iterator iterates on.
Returns
the actor class
Definition at line 136 of file ActorDescList.h.
operator bool()
template<class DescType> template<bool bConst, class ActorType> FORCEINLINE TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::operator bool () const inline explicit
Returns whether the iterator has reached the end and no longer points to a suitable actor desc.
Returns
true if iterator points to a suitable actor desc, false if it has reached the end
Definition at line 126 of file ActorDescList.h.
operator*()
template<class DescType> template<bool bConst, class ActorType> FORCEINLINE ReturnType TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::operator* () const inline
Returns the current suitable actor desc pointed at by the Iterator.
Returns
Current suitable actor desc
Definition at line 105 of file ActorDescList.h.
operator++()
template<class DescType> template<bool bConst, class ActorType> FORCEINLINE void TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::operator++ () inline
Iterates to next suitable actor desc.
Definition at line 83 of file ActorDescList.h.
Referenced by TActorDescList< DescType >::TBaseIterator< false, ActorType >::TBaseIterator().
operator->()
template<class DescType> template<bool bConst, class ActorType> FORCEINLINE ReturnType TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::operator-> () const inline
Returns the current suitable actor desc pointed at by the Iterator.
Returns
Current suitable actor desc
Definition at line 115 of file ActorDescList.h.
RemoveCurrent()
template<class DescType> template<bool bConst, class ActorType> FORCEINLINE void TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::RemoveCurrent () inline
Removes the current iterator element.
Definition at line 94 of file ActorDescList.h.
ShouldSkip()
template<class DescType> template<bool bConst, class ActorType> FORCEINLINE bool TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::ShouldSkip () const inline protected
Determines whether the iterator currently points to a valid actor desc or not.
Returns
true if we should skip the actor desc
Definition at line 143 of file ActorDescList.h.
Referenced by TActorDescList< DescType >::TBaseIterator< false, ActorType >::TBaseIterator(), and TActorDescList< DescType >::TBaseIterator< false, ActorType >::operator++().
Field Documentation
ActorClass
template<class DescType> template<bool bConst, class ActorType> UClass* TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::ActorClass protected
Definition at line 154 of file ActorDescList.h.
ActorsIterator
template<class DescType> template<bool bConst, class ActorType> IteratorType TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::ActorsIterator protected
Definition at line 153 of file ActorDescList.h.
bIsProxy
template<class DescType> template<bool bConst, class ActorType> bool TActorDescList< DescType >::TBaseIterator< bConst, ActorType >::bIsProxy protected
Definition at line 155 of file ActorDescList.h.
The documentation for this class was generated from the following file:
ActorDescList.h