Unreal Engine 5.6 C++ API: FRemoteWorkPriority Struct Reference
FRemoteWorkPriority Struct Reference
#include "RemoteExecutor.h"
Public Member Functions
FRemoteWorkPriority CreateDependentWorkPriority () const
FRemoteServerId GetRootServerId () const
FRemoteTransactionId GetRootWorkTransactionId () const
uint32 GetWorkDepth () const
bool IsValid () const
FString ToString () const
Static Public Member Functions
static FRemoteWorkPriority CreateRootWorkPriority (FRemoteServerId ServerId, FRemoteTransactionId TransactionId)
Data Fields
uint64 PackedData = 0
Detailed Description
Definition at line 52 of file RemoteExecutor.h.
Member Function Documentation
CreateDependentWorkPriority()
FRemoteWorkPriority FRemoteWorkPriority::CreateDependentWorkPriority () const
CreateRootWorkPriority()
FRemoteWorkPriority FRemoteWorkPriority::CreateRootWorkPriority (FRemoteServerId ServerId, FRemoteTransactionId TransactionId) static
GetRootServerId()
FRemoteServerId FRemoteWorkPriority::GetRootServerId () const inline
Definition at line 69 of file RemoteExecutor.h.
References PackedData.
Referenced by IsValid().
GetRootWorkTransactionId()
FRemoteTransactionId FRemoteWorkPriority::GetRootWorkTransactionId () const inline
Definition at line 71 of file RemoteExecutor.h.
References PackedData.
GetWorkDepth()
uint32 FRemoteWorkPriority::GetWorkDepth () const inline
Definition at line 70 of file RemoteExecutor.h.
References PackedData.
IsValid()
bool FRemoteWorkPriority::IsValid () const inline
Definition at line 73 of file RemoteExecutor.h.
References GetRootServerId(), and FRemoteServerId::IsValid().
ToString()
FString FRemoteWorkPriority::ToString () const
Field Documentation
PackedData
uint64 FRemoteWorkPriority::PackedData = 0
Definition at line 65 of file RemoteExecutor.h.
Referenced by GetRootServerId(), GetRootWorkTransactionId(), and GetWorkDepth().
The documentation for this struct was generated from the following file:
RemoteExecutor.h