Unreal Engine 5.6 C++ API: FPackedLevelActorBuilderClusterID Class Reference
FPackedLevelActorBuilderClusterID Class Reference
#include "PackedLevelActorTypes.h"
Public Member Functions
FPackedLevelActorBuilderClusterID ()
FPackedLevelActorBuilderClusterID (FPackedLevelActorBuilderClusterID &&Other)
FPackedLevelActorBuilderClusterID (TUniquePtr< FPackedLevelActorBuilderCluster > &&InData)
FPackedLevelActorBuilderID GetBuilderID () const
FPackedLevelActorBuilderCluster * GetData () const
uint32 GetHash () const
bool operator!= (const FPackedLevelActorBuilderClusterID &Other) const
bool operator== (const FPackedLevelActorBuilderClusterID &Other) const
Static Public Attributes
static FPackedLevelActorBuilderClusterID Invalid
Private Member Functions
FPackedLevelActorBuilderClusterID (const FPackedLevelActorBuilderClusterID &)=delete
FPackedLevelActorBuilderClusterID & operator= (const FPackedLevelActorBuilderClusterID &)=delete
Private Attributes
TUniquePtr< FPackedLevelActorBuilderCluster > Data
uint32 Hash
Friends
uint32 GetTypeHash (const FPackedLevelActorBuilderClusterID &ID)
Detailed Description
Definition at line 40 of file PackedLevelActorTypes.h.
Constructor & Destructor Documentation
FPackedLevelActorBuilderClusterID() [1/4]
FPackedLevelActorBuilderClusterID::FPackedLevelActorBuilderClusterID () inline
Definition at line 45 of file PackedLevelActorTypes.h.
References Hash.
Referenced by FPackedLevelActorBuilderClusterID(), FPackedLevelActorBuilderClusterID(), GetTypeHash, operator!=(), operator=(), and operator==().
FPackedLevelActorBuilderClusterID() [2/4]
FPackedLevelActorBuilderClusterID::FPackedLevelActorBuilderClusterID (FPackedLevelActorBuilderClusterID && Other) inline
Definition at line 49 of file PackedLevelActorTypes.h.
References FPackedLevelActorBuilderClusterID(), Data, Hash, MoveTemp(), and Other.
FPackedLevelActorBuilderClusterID() [3/4]
FPackedLevelActorBuilderClusterID::FPackedLevelActorBuilderClusterID (TUniquePtr< FPackedLevelActorBuilderCluster > && InData) inline
Definition at line 54 of file PackedLevelActorTypes.h.
References Data, Hash, and MoveTemp().
FPackedLevelActorBuilderClusterID() [4/4]
FPackedLevelActorBuilderClusterID::FPackedLevelActorBuilderClusterID (const FPackedLevelActorBuilderClusterID &) private delete
References FPackedLevelActorBuilderClusterID().
Member Function Documentation
GetBuilderID()
FPackedLevelActorBuilderID FPackedLevelActorBuilderClusterID::GetBuilderID () const inline
Definition at line 72 of file PackedLevelActorTypes.h.
References Data.
GetData()
FPackedLevelActorBuilderCluster * FPackedLevelActorBuilderClusterID::GetData () const inline
Definition at line 79 of file PackedLevelActorTypes.h.
References Data.
GetHash()
uint32 FPackedLevelActorBuilderClusterID::GetHash () const inline
Definition at line 70 of file PackedLevelActorTypes.h.
References Hash.
operator!=()
bool FPackedLevelActorBuilderClusterID::operator!= (const FPackedLevelActorBuilderClusterID & Other) const inline
Definition at line 65 of file PackedLevelActorTypes.h.
References FPackedLevelActorBuilderClusterID(), and Other.
operator=()
FPackedLevelActorBuilderClusterID & FPackedLevelActorBuilderClusterID::operator= (const FPackedLevelActorBuilderClusterID &) private delete
References FPackedLevelActorBuilderClusterID().
operator==()
bool FPackedLevelActorBuilderClusterID::operator== (const FPackedLevelActorBuilderClusterID & Other) const inline
Definition at line 60 of file PackedLevelActorTypes.h.
References FPackedLevelActorBuilderClusterID(), Data, Hash, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPackedLevelActorBuilderClusterID & ID) friend
Definition at line 74 of file PackedLevelActorTypes.h.
References FPackedLevelActorBuilderClusterID(), and ID.
Field Documentation
Data
TUniquePtr<FPackedLevelActorBuilderCluster> FPackedLevelActorBuilderClusterID::Data private
Definition at line 89 of file PackedLevelActorTypes.h.
Referenced by FPackedLevelActorBuilderClusterID(), FPackedLevelActorBuilderClusterID(), GetBuilderID(), GetData(), and operator==().
Hash
uint32 FPackedLevelActorBuilderClusterID::Hash private
Definition at line 88 of file PackedLevelActorTypes.h.
Referenced by FPackedLevelActorBuilderClusterID(), FPackedLevelActorBuilderClusterID(), FPackedLevelActorBuilderClusterID(), GetHash(), and operator==().
Invalid
FPackedLevelActorBuilderClusterID FPackedLevelActorBuilderClusterID::Invalid static
Definition at line 43 of file PackedLevelActorTypes.h.
The documentation for this class was generated from the following file:
PackedLevelActorTypes.h