Unreal Engine 5.6 C++ API: FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry Struct Reference
FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry Struct Reference
#include "SlateAttributeDescriptor.h"
Public Member Functions
FAttributeEntry (FSlateAttributeDescriptor &Descriptor, FName ContainerName, int32 AttributeIndex)
FAttributeEntry & OnValueChanged (FAttributeValueChangedDelegate Callback)
Notified when the attribute value changed.
FAttributeEntry & UpdatePrerequisite (FName Prerequisite)
Update the attribute after the prerequisite.
Private Attributes
int32 AttributeIndex
FName ContainerName
FSlateAttributeDescriptor & Descriptor
Detailed Description
Definition at line 216 of file SlateAttributeDescriptor.h.
Constructor & Destructor Documentation
FAttributeEntry()
FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry::FAttributeEntry (FSlateAttributeDescriptor & Descriptor, FName ContainerName, int32 AttributeIndex)
References AttributeIndex, ContainerName, Descriptor, and FSlateAttributeDescriptor::FContainerInitializer::FSlateAttributeDescriptor.
Referenced by OnValueChanged(), and UpdatePrerequisite().
Member Function Documentation
OnValueChanged()
FAttributeEntry & FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry::OnValueChanged (FAttributeValueChangedDelegate Callback)
Notified when the attribute value changed.
It's preferable that you delay any action to the Tick or Paint function. You are not allowed to make changes that would affect the SWidget ChildOrder or its Visibility. It will not be called when the SWidget is in its construction phase.
See also
SWidget::IsConstructed
References FAttributeEntry().
UpdatePrerequisite()
FAttributeEntry & FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry::UpdatePrerequisite (FName Prerequisite)
Update the attribute after the prerequisite.
The order is guaranteed but other attributes may be updated in between. No order is guaranteed if the prerequisite or this property is updated manually.
References FAttributeEntry().
Field Documentation
AttributeIndex
int32 FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry::AttributeIndex private
Definition at line 239 of file SlateAttributeDescriptor.h.
Referenced by FAttributeEntry().
ContainerName
FName FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry::ContainerName private
Definition at line 238 of file SlateAttributeDescriptor.h.
Referenced by FAttributeEntry().
Descriptor
FSlateAttributeDescriptor& FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry::Descriptor private
Definition at line 237 of file SlateAttributeDescriptor.h.
Referenced by FAttributeEntry().
The documentation for this struct was generated from the following file:
SlateAttributeDescriptor.h