Unreal Engine 5.6 C++ API: FRemoteSubsystem< RequestType > Class Template Reference
FRemoteSubsystem< RequestType > Class Template Reference
#include "RemoteExecutor.h"
Public Member Functions
void ClearActiveRequest () final
void * CreateRequest (FRemoteTransactionId RequestId, FRemoteWorkPriority Priority) final
void DestroyRequest (FRemoteTransactionId RequestId) final
RequestType * GetRequestByIndex (int32 RequestIndex) const
void SetActiveRequest (FRemoteTransactionId RequestId) final
RequestType * TryGetRequest (FRemoteTransactionId RequestId) const
int32 TryGetRequestIndex (FRemoteTransactionId RequestId) const
Public Member Functions inherited from FRemoteSubsystemBase
FRemoteSubsystemBase ()=default
virtual ~FRemoteSubsystemBase ()=default
virtual void AbortMultiServerCommit ()=0
virtual bool AreDependenciesSatisfied () const =0
virtual void BeginMultiServerCommit (TArray< FRemoteServerId > &OutMultiServerCommitRemoteServers)=0
virtual void BeginRequest ()=0
virtual void CommitMultiServerCommit ()=0
virtual void EndRequest (bool bTransactionCommitted)=0
virtual void ExecuteMultiServerCommit ()=0
int32 GetRequestCount () const
virtual const TCHAR * NameForDebug ()=0
virtual void TickRequest ()=0
virtual void TickSubsystem ()=0
Data Fields
RequestType * ActiveRequest = nullptr
Additional Inherited Members
Protected Attributes inherited from FRemoteSubsystemBase
TArray< TTuple< FRemoteTransactionId, void * > > Requests
Detailed Description
template<typename RequestType>
class FRemoteSubsystem< RequestType >
Definition at line 122 of file RemoteExecutor.h.
Member Function Documentation
ClearActiveRequest()
template<typename RequestType> void FRemoteSubsystem< RequestType >::ClearActiveRequest () inline final virtual
Implements FRemoteSubsystemBase.
Definition at line 186 of file RemoteExecutor.h.
References ActiveRequest.
CreateRequest()
template<typename RequestType> void * FRemoteSubsystem< RequestType >::CreateRequest (FRemoteTransactionId RequestId, FRemoteWorkPriority Priority) inline final virtual
Implements FRemoteSubsystemBase.
Definition at line 162 of file RemoteExecutor.h.
References FRemoteSubsystemBase::Requests.
DestroyRequest()
template<typename RequestType> void FRemoteSubsystem< RequestType >::DestroyRequest (FRemoteTransactionId RequestId) inline final virtual
Implements FRemoteSubsystemBase.
Definition at line 171 of file RemoteExecutor.h.
References check, GetRequestByIndex(), INDEX_NONE, No, FRemoteSubsystemBase::Requests, and TryGetRequestIndex().
GetRequestByIndex()
template<typename RequestType> RequestType * FRemoteSubsystem< RequestType >::GetRequestByIndex (int32 RequestIndex) const inline
Definition at line 127 of file RemoteExecutor.h.
References FRemoteSubsystemBase::Requests.
Referenced by DestroyRequest().
SetActiveRequest()
template<typename RequestType> void FRemoteSubsystem< RequestType >::SetActiveRequest (FRemoteTransactionId RequestId) inline final virtual
Implements FRemoteSubsystemBase.
Definition at line 180 of file RemoteExecutor.h.
References ActiveRequest, check, and TryGetRequest().
TryGetRequest()
template<typename RequestType> RequestType * FRemoteSubsystem< RequestType >::TryGetRequest (FRemoteTransactionId RequestId) const inline
Definition at line 133 of file RemoteExecutor.h.
References FRemoteSubsystemBase::Requests.
Referenced by SetActiveRequest().
TryGetRequestIndex()
template<typename RequestType> int32 FRemoteSubsystem< RequestType >::TryGetRequestIndex (FRemoteTransactionId RequestId) const inline
Definition at line 145 of file RemoteExecutor.h.
References INDEX_NONE, and FRemoteSubsystemBase::Requests.
Referenced by DestroyRequest().
Field Documentation
ActiveRequest
template<typename RequestType> RequestType* FRemoteSubsystem< RequestType >::ActiveRequest = nullptr
Definition at line 125 of file RemoteExecutor.h.
Referenced by ClearActiveRequest(), and SetActiveRequest().
The documentation for this class was generated from the following file:
RemoteExecutor.h