Unreal Engine 5.6 C++ API: TInputDeviceMap< TDeviceKeyType > Class Template Reference
TInputDeviceMap< TDeviceKeyType > Class Template Reference
An interface which can be added to any IInputDevice (or any other type which is creating Human Interface Devices) to store it's unique identifier for those physical devices and associate them with a FInputDeviceId so that the rest of the Unreal Engine can interact with them.
#include "GenericInputDeviceMap.h"
Public Member Functions
TInputDeviceMap ()=default
~TInputDeviceMap ()=default
FInputDeviceId FindDeviceId (const TDeviceKeyType &DeviceKey) const
Returns the FInputDeviceId for the given device key.
FInputDeviceId FindDeviceIdChecked (const TDeviceKeyType &DeviceKey) const
Returns the FInputDeviceId associated with the given device key.
const TDeviceKeyType * FindDeviceKey (const FInputDeviceId DeviceId) const
Returns the device key for the given FInputDeviceId.
const TDeviceKeyType & GetDeviceKeyChecked (const FInputDeviceId DeviceId) const
Returns the device key for the given FInputDeviceId.
FInputDeviceId GetOrCreateDeviceId (const TDeviceKeyType &DeviceKey)
Given the DeviceKey, find it's associated FInputDeviceId.
FInputDeviceId MapDefaultInputDevice (const TDeviceKeyType &DeviceKey)
Maps a DeviceKey to the default FInputDeviceId which has the internal value 0.
Protected Attributes
TMap< TDeviceKeyType, FInputDeviceId > MappedDeviceIds
Map of the assigned DeviceKeyType to their assigned FInputDeviceId's from the engine.
TMap< FInputDeviceId, TDeviceKeyType > MappedIdToKey
A map of the assigned FInputDeviceId to their associated Device Key type for fast lookup.
Detailed Description
template<class TDeviceKeyType>
class TInputDeviceMap< TDeviceKeyType >
An interface which can be added to any IInputDevice (or any other type which is creating Human Interface Devices) to store it's unique identifier for those physical devices and associate them with a FInputDeviceId so that the rest of the Unreal Engine can interact with them.
Some input interfaces use simple int32's to identify input devices, while others may have more specific GUID types types which are needed.
Definition at line 19 of file GenericInputDeviceMap.h.
Constructor & Destructor Documentation
TInputDeviceMap()
template<class TDeviceKeyType> TInputDeviceMap< TDeviceKeyType >::TInputDeviceMap () default
~TInputDeviceMap()
template<class TDeviceKeyType> TInputDeviceMap< TDeviceKeyType >::~TInputDeviceMap () default
Member Function Documentation
FindDeviceId()
template<class TDeviceKeyType> FInputDeviceId TInputDeviceMap< TDeviceKeyType >::FindDeviceId (const TDeviceKeyType & DeviceKey) const inline nodiscard
Returns the FInputDeviceId for the given device key.
Returns FInputDeviceId::Invalid if it is not yet mapped.
Definition at line 75 of file GenericInputDeviceMap.h.
References INPUTDEVICEID_NONE, and MappedDeviceIds.
FindDeviceIdChecked()
template<class TDeviceKeyType> FInputDeviceId TInputDeviceMap< TDeviceKeyType >::FindDeviceIdChecked (const TDeviceKeyType & DeviceKey) const inline nodiscard
Returns the FInputDeviceId associated with the given device key.
Asserts if not found.
Definition at line 91 of file GenericInputDeviceMap.h.
References MappedDeviceIds.
FindDeviceKey()
template<class TDeviceKeyType> const TDeviceKeyType * TInputDeviceMap< TDeviceKeyType >::FindDeviceKey (const FInputDeviceId DeviceId) const inline nodiscard
Returns the device key for the given FInputDeviceId.
Nullptr if not found.
Definition at line 107 of file GenericInputDeviceMap.h.
References MappedIdToKey.
GetDeviceKeyChecked()
template<class TDeviceKeyType> const TDeviceKeyType & TInputDeviceMap< TDeviceKeyType >::GetDeviceKeyChecked (const FInputDeviceId DeviceId) const inline nodiscard
Returns the device key for the given FInputDeviceId.
Nullptr if not found.
Definition at line 99 of file GenericInputDeviceMap.h.
References MappedIdToKey.
GetOrCreateDeviceId()
template<class TDeviceKeyType> FInputDeviceId TInputDeviceMap< TDeviceKeyType >::GetOrCreateDeviceId (const TDeviceKeyType & DeviceKey) inline nodiscard
Given the DeviceKey, find it's associated FInputDeviceId.
If one does not exist yet, such as for a newly connected device, then create one from the IPlatformInputDeviceMapper.
Definition at line 32 of file GenericInputDeviceMap.h.
References IPlatformInputDeviceMapper::AllocateNewInputDeviceId(), IPlatformInputDeviceMapper::Get(), INPUTDEVICEID_NONE, MappedDeviceIds, and MappedIdToKey.
MapDefaultInputDevice()
template<class TDeviceKeyType> FInputDeviceId TInputDeviceMap< TDeviceKeyType >::MapDefaultInputDevice (const TDeviceKeyType & DeviceKey) inline nodiscard
Maps a DeviceKey to the default FInputDeviceId which has the internal value 0.
Returns the default FInputDeviceId for straightforward use.
Definition at line 60 of file GenericInputDeviceMap.h.
References IPlatformInputDeviceMapper::Get(), IPlatformInputDeviceMapper::GetDefaultInputDevice(), MappedDeviceIds, and MappedIdToKey.
Field Documentation
MappedDeviceIds
template<class TDeviceKeyType> TMap<TDeviceKeyType, FInputDeviceId> TInputDeviceMap< TDeviceKeyType >::MappedDeviceIds protected
Map of the assigned DeviceKeyType to their assigned FInputDeviceId's from the engine.
Definition at line 117 of file GenericInputDeviceMap.h.
Referenced by FindDeviceId(), FindDeviceIdChecked(), GetOrCreateDeviceId(), and MapDefaultInputDevice().
MappedIdToKey
template<class TDeviceKeyType> TMap<FInputDeviceId, TDeviceKeyType> TInputDeviceMap< TDeviceKeyType >::MappedIdToKey protected
A map of the assigned FInputDeviceId to their associated Device Key type for fast lookup.
Definition at line 123 of file GenericInputDeviceMap.h.
Referenced by FindDeviceKey(), GetDeviceKeyChecked(), GetOrCreateDeviceId(), and MapDefaultInputDevice().
The documentation for this class was generated from the following file:
GenericInputDeviceMap.h