Unreal Engine 5.6 C++ API: SSlider Class Reference
SSlider Class Reference
A Slate slider control is a linear scale and draggable handle.
#include "SSlider.h"
Public Member Functions
virtual FVector2D ComputeDesiredSize (float) const override
Overwritten from SWidget.
virtual bool IsInteractable () const override
bool IsLocked () const
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent) override
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent) override
Called when navigation is requested e.g.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
Overwritten from SWidget.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is started (finger down)
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
Public Member Functions inherited from SLeafWidget
SLeafWidget ()
virtual ~SLeafWidget ()
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual void CommitValue (float NewValue)
Commits the specified slider value.
const FSlateBrush * GetBarImage () const
TSlateAttributeRef< bool > GetIndentHandleAttribute () const
TSlateAttributeRef< bool > GetLockedAttribute () const
TSlateAttributeRef< FSlateColor > GetSliderBarColorAttribute () const
TSlateAttributeRef< FSlateColor > GetSliderHandleColorAttribute () const
const FSlateBrush * GetThumbImage () const
TSlateAttributeRef< float > GetValueAttribute () const
float PositionToValue (const FGeometry &MyGeometry, const UE::Slate::FDeprecateVector2DParameter &AbsolutePosition)
Calculates the new value based on the given absolute coordinates.
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bControllerInputCaptured
bool bIsFocusable
When true, this slider will be keyboard focusable.
bool bMouseUsesStep
Sets new value if mouse position is greater/less than half the step size.
bool bPreventThrottling = false
bool bRequiresControllerLock
Sets whether we have to lock input to change the slider value.
EMouseCursor::Type CachedCursor
float MaxValue
float MinValue
EOrientation Orientation
UE::Slate::FDeprecateVector2DResult PressedScreenSpaceTouchDownPosition
The location in screenspace the slider was pressed by a touch.
TAttribute< float > StepSize
Holds the amount to adjust the value by when using a controller or keyboard.
const FSliderStyle * Style
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
virtual ~SSlider ()
void Construct (const SSlider::FArguments &InDeclaration)
Construct the widget.
float GetMaxValue () const
Get the MaxValue attribute.
float GetMinValue () const
Get the MinValue attribute.
float GetNormalizedValue () const
Get the Value attribute scaled from 0 to 1.
float GetStepSize () const
Get the StepSize attribute.
float GetValue () const
Get the Value attribute.
void ResetControllerState ()
void SetIndentHandle (TAttribute< bool > InIndentHandle)
Set the IndentHandle attribute.
void SetLocked (TAttribute< bool > InLocked)
Set the Locked attribute.
void SetMinAndMaxValues (float InMinValue, float InMaxValue)
Set the MinValue and MaxValue attributes.
void SetMouseUsesStep (bool MouseUsesStep)
Set the MouseUsesStep attribute.
void SetOrientation (EOrientation InOrientation)
Set the Orientation attribute.
void SetRequiresControllerLock (bool RequiresControllerLock)
Set the RequiresControllerLock attribute.
void SetSliderBarColor (TAttribute< FSlateColor > InSliderBarColor)
Set the SliderBarColor attribute.
void SetSliderHandleColor (TAttribute< FSlateColor > InSliderHandleColor)
Set the SliderHandleColor attribute.
void SetStepSize (TAttribute< float > InStepSize)
Set the StepSize attribute.
void SetStyle (const FSliderStyle *InStyle)
Set the widget style.
void SetValue (TAttribute< float > InValueAttribute)
Set the Value attribute.
MouseUsesStep Locked SliderBarColor Style Value MaxValue SLATE_ARGUMENT (bool, IsFocusable) SLATE_EVENT(FSimpleDelegate
Sometimes a slider should only be mouse-clickable and never keyboard focusable.
MouseUsesStep Locked SliderBarColor Style Value MaxValue OnMouseCaptureBegin OnControllerCaptureBegin OnValueChanged SLATE_ARGUMENT (bool, PreventThrottling) SLATE_END_ARGS() 1 SSlider()
If refresh requests for the viewport should happen for all value changes.
MouseUsesStep SLATE_ARGUMENT (bool, RequiresControllerLock) SLATE_ATTRIBUTE(bool
Sets whether we have to lock input to change the slider value.
MouseUsesStep Locked SLATE_ARGUMENT (EOrientation, Orientation) SLATE_ATTRIBUTE(FSlateColor
The slider's orientation.
MouseUsesStep Locked SliderBarColor Style Value SLATE_ARGUMENT (float, MinValue) SLATE_ARGUMENT(float
The minimum value that can be specified by using the slider.
SLATE_ATTRIBUTE (bool, IndentHandle) SLATE_ARGUMENT(bool
Whether the slidable area should be indented to fit the handle.
MouseUsesStep Locked SliderBarColor Style SLATE_ATTRIBUTE (float, StepSize) SLATE_ATTRIBUTE(float
The input mode while using the controller.
MouseUsesStep Locked SliderBarColor SLATE_ATTRIBUTE (FSlateColor, SliderHandleColor) SLATE_STYLE_ARGUMENT(FSliderStyle
The color to draw the slider handle in.
SLATE_DECLARE_WIDGET_API (SSlider, SLeafWidget, 1) public
MouseUsesStep Locked SliderBarColor Style Value MaxValue OnMouseCaptureBegin OnControllerCaptureBegin SLATE_EVENT (FSimpleDelegate, OnControllerCaptureEnd) SLATE_EVENT(FOnFloatValueChanged
Invoked when the controller capture is released.
MouseUsesStep Locked SliderBarColor Style Value MaxValue OnMouseCaptureBegin SLATE_EVENT (FSimpleDelegate, OnMouseCaptureEnd) SLATE_EVENT(FSimpleDelegate
Invoked when the mouse is released and a capture ends.
Private Attributes
TSlateAttribute< bool > IndentHandleSlateAttribute
TSlateAttribute< bool > LockedSlateAttribute
FSimpleDelegate OnControllerCaptureBegin
FSimpleDelegate OnControllerCaptureEnd
FSimpleDelegate OnMouseCaptureBegin
FSimpleDelegate OnMouseCaptureEnd
FOnFloatValueChanged OnValueChanged
TSlateAttribute< FSlateColor > SliderBarColorSlateAttribute
TSlateAttribute< FSlateColor > SliderHandleColorSlateAttribute
TSlateAttribute< float > ValueSlateAttribute
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A Slate slider control is a linear scale and draggable handle.
Definition at line 22 of file SSlider.h.
Constructor & Destructor Documentation
~SSlider()
virtual SSlider::~SSlider () private virtual
Member Function Documentation
CommitValue()
virtual void SSlider::CommitValue (float NewValue) protected virtual
Commits the specified slider value.
Parameters
NewValue The value to commit.
ComputeDesiredSize()
virtual FVector2D SSlider::ComputeDesiredSize (float) const override virtual
Overwritten from SWidget.
LeafWidgets should compute their DesiredSize based solely on their visual representation. There is no need to take child widgets into account as LeafWidgets have none by definition. For example, the TextBlock widget simply measures the area necessary to display its text with the given font and font size.
Implements SLeafWidget.
Construct()
void SSlider::Construct (const SSlider::FArguments & InDeclaration) private
Construct the widget.
Parameters
InDeclaration A declaration from which to construct the widget.
References Construct().
Referenced by Construct(), and SAnalogSlider::SLATE_EVENT().
GetBarImage()
const FSlateBrush * SSlider::GetBarImage () const protected
GetIndentHandleAttribute()
TSlateAttributeRef< bool > SSlider::GetIndentHandleAttribute () const inline protected
Returns
an attribute reference of IndentHandle
Definition at line 221 of file SSlider.h.
References IndentHandleSlateAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetLockedAttribute()
TSlateAttributeRef< bool > SSlider::GetLockedAttribute () const inline protected
Returns
an attribute reference of Locked
Definition at line 227 of file SSlider.h.
References LockedSlateAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetMaxValue()
float SSlider::GetMaxValue () const inline private
Get the MaxValue attribute.
Definition at line 124 of file SSlider.h.
References MaxValue.
GetMinValue()
float SSlider::GetMinValue () const inline private
Get the MinValue attribute.
Definition at line 121 of file SSlider.h.
References GetMinValue(), and MinValue.
Referenced by GetMinValue().
GetNormalizedValue()
float SSlider::GetNormalizedValue () const private
Get the Value attribute scaled from 0 to 1.
GetSliderBarColorAttribute()
TSlateAttributeRef< FSlateColor > SSlider::GetSliderBarColorAttribute () const inline protected
Returns
an attribute reference of SliderBarColor
Definition at line 233 of file SSlider.h.
References TSharedFromThis< SWidget >::SharedThis(), and SliderBarColorSlateAttribute.
GetSliderHandleColorAttribute()
TSlateAttributeRef< FSlateColor > SSlider::GetSliderHandleColorAttribute () const inline protected
Returns
an attribute reference of SliderHandleColor
Definition at line 239 of file SSlider.h.
References TSharedFromThis< SWidget >::SharedThis(), and SliderHandleColorSlateAttribute.
GetStepSize()
float SSlider::GetStepSize () const private
Get the StepSize attribute.
GetThumbImage()
const FSlateBrush * SSlider::GetThumbImage () const protected
GetValue()
float SSlider::GetValue () const private
Get the Value attribute.
GetValueAttribute()
TSlateAttributeRef< float > SSlider::GetValueAttribute () const inline protected
Returns
an attribute reference of IndentHandle
Definition at line 215 of file SSlider.h.
References TSharedFromThis< SWidget >::SharedThis(), and ValueSlateAttribute.
IsInteractable()
virtual bool SSlider::IsInteractable () const override virtual
Returns
Is this widget interactive or not? Defaults to false
Reimplemented from SWidget.
IsLocked()
bool SSlider::IsLocked () const
Returns
Is the handle locked or not? Defaults to false
OnFocusLost()
virtual void SSlider::OnFocusLost (const FFocusEvent & InFocusEvent) override virtual
Called when this widget loses focus.
This event does not bubble.
Parameters
InFocusEvent The FocusEvent
Reimplemented from SWidget.
OnKeyDown()
virtual FReply SSlider::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnKeyUp()
virtual FReply SSlider::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMouseButtonDown()
virtual FReply SSlider::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
Reimplemented in SAnalogSlider.
References MouseEvent.
OnMouseButtonUp()
virtual FReply SSlider::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
Reimplemented in SAnalogSlider.
References MouseEvent.
OnMouseCaptureLost()
virtual void SSlider::OnMouseCaptureLost (const FCaptureLostEvent & CaptureLostEvent) override virtual
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
Reimplemented from SWidget.
OnMouseMove()
virtual FReply SSlider::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent.
OnNavigation()
virtual FNavigationReply SSlider::OnNavigation (const FGeometry & MyGeometry, const FNavigationEvent & InNavigationEvent) override virtual
Called when navigation is requested e.g.
Left Joystick, Direction Pad, Arrow Keys can generate navigation events.
Parameters
InNavigationEvent The navigation event generated
Reimplemented from SWidget.
Reimplemented in SAnalogSlider.
OnPaint()
virtual int32 SSlider::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
Overwritten from SWidget.
LeafWidgets provide a visual representation of themselves. They do so by adding DrawElement(s) to the OutDrawElements. DrawElements should have their positions set to absolute coordinates in Window space; for this purpose the Slate system provides the AllottedGeometry parameter. AllottedGeometry describes the space allocated for the visualization of this widget.
Whenever possible, LeafWidgets should avoid dealing with layout properties. See TextBlock for an example.
Implements SLeafWidget.
References SWidget::FSlateWindowElementList.
OnTouchEnded()
virtual FReply SSlider::OnTouchEnded (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is ended (finger lifted)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
OnTouchMoved()
virtual FReply SSlider::OnTouchMoved (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is moved (finger moved)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
OnTouchStarted()
virtual FReply SSlider::OnTouchStarted (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is started (finger down)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
PositionToValue()
float SSlider::PositionToValue (const FGeometry & MyGeometry, const UE::Slate::FDeprecateVector2DParameter & AbsolutePosition) protected
Calculates the new value based on the given absolute coordinates.
Parameters
MyGeometry The slider's geometry.
AbsolutePosition The absolute position of the slider.
Returns
The new value.
ResetControllerState()
void SSlider::ResetControllerState () private
SetIndentHandle()
void SSlider::SetIndentHandle (TAttribute< bool > InIndentHandle) private
Set the IndentHandle attribute.
SetLocked()
void SSlider::SetLocked (TAttribute< bool > InLocked) private
Set the Locked attribute.
SetMinAndMaxValues()
void SSlider::SetMinAndMaxValues (float InMinValue, float InMaxValue) private
Set the MinValue and MaxValue attributes.
If the new MinValue is more than the new MaxValue, MaxValue will be changed to equal MinValue.
SetMouseUsesStep()
void SSlider::SetMouseUsesStep (bool MouseUsesStep) private
Set the MouseUsesStep attribute.
SetOrientation()
void SSlider::SetOrientation (EOrientation InOrientation) private
Set the Orientation attribute.
SetRequiresControllerLock()
void SSlider::SetRequiresControllerLock (bool RequiresControllerLock) private
Set the RequiresControllerLock attribute.
SetSliderBarColor()
void SSlider::SetSliderBarColor (TAttribute< FSlateColor > InSliderBarColor) private
Set the SliderBarColor attribute.
SetSliderHandleColor()
void SSlider::SetSliderHandleColor (TAttribute< FSlateColor > InSliderHandleColor) private
Set the SliderHandleColor attribute.
SetStepSize()
void SSlider::SetStepSize (TAttribute< float > InStepSize) private
Set the StepSize attribute.
SetStyle()
void SSlider::SetStyle (const FSliderStyle * InStyle) private
Set the widget style.
References SetStyle().
Referenced by SetStyle().
SetValue()
void SSlider::SetValue (TAttribute< float > InValueAttribute) private
Set the Value attribute.
SLATE_ARGUMENT() [1/5]
MouseUsesStep Locked SliderBarColor Style Value MaxValue SSlider::SLATE_ARGUMENT (bool , IsFocusable) private
Sometimes a slider should only be mouse-clickable and never keyboard focusable.
Invoked when the mouse is pressed and a capture begins.
References OnMouseCaptureBegin, SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_ARGUMENT() [2/5]
MouseUsesStep Locked SliderBarColor Style Value MaxValue OnMouseCaptureBegin OnControllerCaptureBegin OnValueChanged SSlider::SLATE_ARGUMENT (bool , PreventThrottling) private
If refresh requests for the viewport should happen for all value changes.
References SLATE_ARGUMENT(), and SLATE_END_ARGS.
SLATE_ARGUMENT() [3/5]
MouseUsesStep SSlider::SLATE_ARGUMENT (bool , RequiresControllerLock) private
Sets whether we have to lock input to change the slider value.
Whether the handle is interactive or fixed.
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_ARGUMENT().
SLATE_ARGUMENT() [4/5]
MouseUsesStep Locked SSlider::SLATE_ARGUMENT (EOrientation , Orientation) private
The slider's orientation.
The color to draw the slider bar in.
References Orientation, SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ARGUMENT() [5/5]
MouseUsesStep Locked SliderBarColor Style Value SSlider::SLATE_ARGUMENT (float , MinValue) private
The minimum value that can be specified by using the slider.
The maximum value that can be specified by using the slider.
References MaxValue, MinValue, and SLATE_ARGUMENT().
SLATE_ATTRIBUTE() [1/3]
SSlider::SLATE_ATTRIBUTE (bool , IndentHandle) private
Whether the slidable area should be indented to fit the handle.
Sets new value if mouse position is greater/less than half the step size.
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/3]
MouseUsesStep Locked SliderBarColor Style SSlider::SLATE_ATTRIBUTE (float , StepSize) private
The input mode while using the controller.
A value that drives where the slider handle appears. Value is normalized between 0 and 1.
References SLATE_ATTRIBUTE(), StepSize, and Value.
SLATE_ATTRIBUTE() [3/3]
MouseUsesStep Locked SliderBarColor SSlider::SLATE_ATTRIBUTE (FSlateColor , SliderHandleColor) private
The color to draw the slider handle in.
The style used to draw the slider.
References SLATE_ATTRIBUTE(), SLATE_STYLE_ARGUMENT, and Style.
SLATE_DECLARE_WIDGET_API()
SSlider::SLATE_DECLARE_WIDGET_API (SSlider , SLeafWidget , 1) inline private
Definition at line 24 of file SSlider.h.
References SLeafWidget::SLeafWidget().
SLATE_EVENT() [1/2]
MouseUsesStep Locked SliderBarColor Style Value MaxValue OnMouseCaptureBegin OnControllerCaptureBegin SSlider::SLATE_EVENT (FSimpleDelegate , OnControllerCaptureEnd) private
Invoked when the controller capture is released.
Called when the value is changed by the slider.
References OnControllerCaptureEnd, OnValueChanged, and SLATE_EVENT().
SLATE_EVENT() [2/2]
MouseUsesStep Locked SliderBarColor Style Value MaxValue OnMouseCaptureBegin SSlider::SLATE_EVENT (FSimpleDelegate , OnMouseCaptureEnd) private
Invoked when the mouse is released and a capture ends.
Invoked when the Controller is pressed and capture begins.
References OnControllerCaptureBegin, OnMouseCaptureEnd, and SLATE_EVENT().
Referenced by SLATE_ARGUMENT(), SLATE_EVENT(), and SLATE_EVENT().
SupportsKeyboardFocus()
virtual bool SSlider::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
Field Documentation
bControllerInputCaptured
bool SSlider::bControllerInputCaptured protected
Definition at line 264 of file SSlider.h.
bIsFocusable
bool SSlider::bIsFocusable protected
When true, this slider will be keyboard focusable.
Defaults to false.
Definition at line 273 of file SSlider.h.
bMouseUsesStep
bool SSlider::bMouseUsesStep protected
Sets new value if mouse position is greater/less than half the step size.
Definition at line 267 of file SSlider.h.
bPreventThrottling
bool SSlider::bPreventThrottling = false protected
Definition at line 279 of file SSlider.h.
bRequiresControllerLock
bool SSlider::bRequiresControllerLock protected
Sets whether we have to lock input to change the slider value.
Definition at line 270 of file SSlider.h.
CachedCursor
EMouseCursor::Type SSlider::CachedCursor protected
Definition at line 251 of file SSlider.h.
IndentHandleSlateAttribute
TSlateAttribute<bool> SSlider::IndentHandleSlateAttribute private
Definition at line 290 of file SSlider.h.
Referenced by GetIndentHandleAttribute().
LockedSlateAttribute
TSlateAttribute<bool> SSlider::LockedSlateAttribute private
Definition at line 293 of file SSlider.h.
Referenced by GetLockedAttribute().
MaxValue
float SSlider::MaxValue protected
Definition at line 260 of file SSlider.h.
Referenced by GetMaxValue(), and SLATE_ARGUMENT().
MinValue
float SSlider::MinValue protected
Definition at line 259 of file SSlider.h.
Referenced by GetMinValue(), and SLATE_ARGUMENT().
OnControllerCaptureBegin
FSimpleDelegate SSlider::OnControllerCaptureBegin private
Definition at line 308 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_EVENT(), and SLATE_EVENT().
OnControllerCaptureEnd
FSimpleDelegate SSlider::OnControllerCaptureEnd private
Definition at line 311 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_EVENT(), and SLATE_EVENT().
OnMouseCaptureBegin
FSimpleDelegate SSlider::OnMouseCaptureBegin private
Definition at line 302 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_ARGUMENT(), and SLATE_ARGUMENT().
OnMouseCaptureEnd
FSimpleDelegate SSlider::OnMouseCaptureEnd private
Definition at line 305 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_EVENT(), and SLATE_EVENT().
OnValueChanged
FOnFloatValueChanged SSlider::OnValueChanged private
Definition at line 314 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_EVENT(), and SLATE_EVENT().
Orientation
EOrientation SSlider::Orientation protected
Definition at line 248 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_ARGUMENT(), and SLATE_ARGUMENT().
PressedScreenSpaceTouchDownPosition
UE::Slate::FDeprecateVector2DResult SSlider::PressedScreenSpaceTouchDownPosition protected
The location in screenspace the slider was pressed by a touch.
Definition at line 254 of file SSlider.h.
SliderBarColorSlateAttribute
TSlateAttribute<FSlateColor> SSlider::SliderBarColorSlateAttribute private
Definition at line 296 of file SSlider.h.
Referenced by GetSliderBarColorAttribute().
SliderHandleColorSlateAttribute
TSlateAttribute<FSlateColor> SSlider::SliderHandleColorSlateAttribute private
Definition at line 299 of file SSlider.h.
Referenced by GetSliderHandleColorAttribute().
StepSize
TAttribute<float> SSlider::StepSize protected
Holds the amount to adjust the value by when using a controller or keyboard.
Definition at line 257 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
Style
const FSliderStyle* SSlider::Style protected
Definition at line 245 of file SSlider.h.
Referenced by SAnalogSlider::SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
ValueSlateAttribute
TSlateAttribute<float> SSlider::ValueSlateAttribute private
Definition at line 287 of file SSlider.h.
Referenced by GetValueAttribute().
The documentation for this class was generated from the following file:
SSlider.h