Unreal Engine 5.6 C++ API: FInputActionUnifiedDelegate Struct Reference
FInputActionUnifiedDelegate Struct Reference
#include "InputComponent.h"
Public Member Functions
FInputActionUnifiedDelegate ()
FInputActionUnifiedDelegate (FInputActionHandlerDynamicSignature D)
FInputActionUnifiedDelegate (FInputActionHandlerSignature D)
FInputActionUnifiedDelegate (FInputActionHandlerWithKeySignature D)
void BindDelegate (UObject *Object, const FName FuncName)
Binds a dynamic delegate and unbinds any bound native delegate.
template<class DelegateType, class UserClass, typename... VarTypes>
void BindDelegate (UserClass *Object, typename DelegateType::template TMethodPtr< UserClass > Func, VarTypes... Vars)
template<class UserClass>
void BindDelegate (UserClass *Object, typename FInputActionHandlerSignature::template TMethodPtr< UserClass > Func)
Binds a native delegate and unbinds any bound dynamic delegate.
template<class UserClass>
void BindDelegate (UserClass *Object, typename FInputActionHandlerWithKeySignature::template TMethodPtr< UserClass > Func)
void Execute (const FKey Key) const
Execute function for the action unified delegate.
FInputActionHandlerSignature & GetDelegateForManualSet ()
Returns a reference to the native delegate and unbinds any bound dynamic delegate.
FInputActionHandlerWithKeySignature & GetDelegateWithKeyForManualSet ()
Returns a reference to the native delegate and unbinds any bound dynamic delegate.
const void * GetObject () const
Returns the object bound to either the native or dynamic delegate as a raw, untyped pointer.
const UObject * GetUObject () const
Returns the UObject bound to either the native or dynamic delegate (if either is a UFunction or UObject delegate)
bool IsBound () const
Returns if either the native or dynamic delegate is bound.
bool IsBoundToObject (FDelegateUserObjectConst Object) const
Returns if either the native or dynamic delegate is bound to an object.
void Unbind ()
Unbinds any bound delegates.
Private Types
enum class EBoundDelegate : uint8 { Unbound , Delegate , DelegateWithKey , DynamicDelegate }
Private Attributes
EBoundDelegate BoundDelegateType
TSharedPtr< FInputActionHandlerSignature > FuncDelegate
Holds the delegate to call.
TSharedPtr< FInputActionHandlerWithKeySignature > FuncDelegateWithKey
Holds the delegate that wants to know the key to call.
TSharedPtr< FInputActionHandlerDynamicSignature > FuncDynDelegate
Holds the dynamic delegate to call.
Detailed Description
Definition at line 129 of file InputComponent.h.
Member Enumeration Documentation
EBoundDelegate
enum class FInputActionUnifiedDelegate::EBoundDelegate : uint8 strong private
Enumerator
Unbound
Delegate
DelegateWithKey
DynamicDelegate
Definition at line 315 of file InputComponent.h.
Constructor & Destructor Documentation
FInputActionUnifiedDelegate() [1/4]
FInputActionUnifiedDelegate::FInputActionUnifiedDelegate () inline
Definition at line 131 of file InputComponent.h.
References BoundDelegateType, and Unbound.
FInputActionUnifiedDelegate() [2/4]
FInputActionUnifiedDelegate::FInputActionUnifiedDelegate (FInputActionHandlerSignature D) inline
Definition at line 132 of file InputComponent.h.
References BoundDelegateType, Delegate, FuncDelegate, MakeShared(), and MoveTemp().
FInputActionUnifiedDelegate() [3/4]
FInputActionUnifiedDelegate::FInputActionUnifiedDelegate (FInputActionHandlerWithKeySignature D) inline
Definition at line 133 of file InputComponent.h.
References BoundDelegateType, DelegateWithKey, FuncDelegateWithKey, MakeShared(), and MoveTemp().
FInputActionUnifiedDelegate() [4/4]
FInputActionUnifiedDelegate::FInputActionUnifiedDelegate (FInputActionHandlerDynamicSignature D) inline
Definition at line 134 of file InputComponent.h.
References BoundDelegateType, DynamicDelegate, FuncDynDelegate, MakeShared(), and MoveTemp().
Member Function Documentation
BindDelegate() [1/4]
void FInputActionUnifiedDelegate::BindDelegate (UObject * Object, const FName FuncName) inline
Binds a dynamic delegate and unbinds any bound native delegate.
Definition at line 234 of file InputComponent.h.
References BoundDelegateType, DynamicDelegate, FuncDynDelegate, MakeShared(), Object, and Unbind().
BindDelegate() [2/4]
template<class DelegateType, class UserClass, typename... VarTypes> void FInputActionUnifiedDelegate::BindDelegate (UserClass * Object, typename DelegateType::template TMethodPtr< UserClass > Func, VarTypes... Vars) inline
Definition at line 226 of file InputComponent.h.
References BoundDelegateType, Delegate, FuncDelegate, MakeShared(), Object, and Unbind().
BindDelegate() [3/4]
template<class UserClass> void FInputActionUnifiedDelegate::BindDelegate (UserClass * Object, typename FInputActionHandlerSignature::template TMethodPtr< UserClass > Func) inline
Binds a native delegate and unbinds any bound dynamic delegate.
Definition at line 210 of file InputComponent.h.
References BoundDelegateType, Delegate, FuncDelegate, MakeShared(), Object, and Unbind().
Referenced by UInputComponent::BindAction(), UInputComponent::BindAction(), UInputComponent::BindAction(), UInputComponent::BindKey(), and UInputComponent::BindKey().
BindDelegate() [4/4]
template<class UserClass> void FInputActionUnifiedDelegate::BindDelegate (UserClass * Object, typename FInputActionHandlerWithKeySignature::template TMethodPtr< UserClass > Func) inline
Definition at line 218 of file InputComponent.h.
References BoundDelegateType, DelegateWithKey, FuncDelegateWithKey, MakeShared(), Object, and Unbind().
Execute()
void FInputActionUnifiedDelegate::Execute (const FKey Key) const inline
Execute function for the action unified delegate.
Definition at line 281 of file InputComponent.h.
References BoundDelegateType, Delegate, DelegateWithKey, DynamicDelegate, FuncDelegate, FuncDelegateWithKey, FuncDynDelegate, and Key.
GetDelegateForManualSet()
FInputActionHandlerSignature & FInputActionUnifiedDelegate::GetDelegateForManualSet () inline
Returns a reference to the native delegate and unbinds any bound dynamic delegate.
Definition at line 243 of file InputComponent.h.
References BoundDelegateType, Delegate, FuncDelegate, MakeShared(), and Unbind().
GetDelegateWithKeyForManualSet()
FInputActionHandlerWithKeySignature & FInputActionUnifiedDelegate::GetDelegateWithKeyForManualSet () inline
Returns a reference to the native delegate and unbinds any bound dynamic delegate.
Definition at line 252 of file InputComponent.h.
References BoundDelegateType, DelegateWithKey, FuncDelegateWithKey, MakeShared(), and Unbind().
GetObject()
const void * FInputActionUnifiedDelegate::GetObject () const inline
Returns the object bound to either the native or dynamic delegate as a raw, untyped pointer.
If you're looking for a bound UObject, prefer GetUObject().
Definition at line 191 of file InputComponent.h.
References BoundDelegateType, Delegate, DelegateWithKey, DynamicDelegate, FuncDelegate, FuncDelegateWithKey, and FuncDynDelegate.
GetUObject()
const UObject * FInputActionUnifiedDelegate::GetUObject () const inline
Returns the UObject bound to either the native or dynamic delegate (if either is a UFunction or UObject delegate)
Definition at line 173 of file InputComponent.h.
References BoundDelegateType, Delegate, DelegateWithKey, DynamicDelegate, FuncDelegate, FuncDelegateWithKey, and FuncDynDelegate.
IsBound()
bool FInputActionUnifiedDelegate::IsBound () const inline
Returns if either the native or dynamic delegate is bound.
Definition at line 137 of file InputComponent.h.
References BoundDelegateType, Delegate, DelegateWithKey, DynamicDelegate, FuncDelegate, FuncDelegateWithKey, and FuncDynDelegate.
IsBoundToObject()
bool FInputActionUnifiedDelegate::IsBoundToObject (FDelegateUserObjectConst Object) const inline
Returns if either the native or dynamic delegate is bound to an object.
Definition at line 155 of file InputComponent.h.
References BoundDelegateType, Delegate, DelegateWithKey, DynamicDelegate, FuncDelegate, FuncDelegateWithKey, FuncDynDelegate, and Object.
Unbind()
void FInputActionUnifiedDelegate::Unbind () inline
Unbinds any bound delegates.
Definition at line 261 of file InputComponent.h.
References BoundDelegateType, Delegate, DelegateWithKey, DynamicDelegate, FuncDelegate, FuncDelegateWithKey, FuncDynDelegate, and Unbound.
Referenced by BindDelegate(), BindDelegate(), BindDelegate(), BindDelegate(), GetDelegateForManualSet(), and GetDelegateWithKeyForManualSet().
Field Documentation
BoundDelegateType
EBoundDelegate FInputActionUnifiedDelegate::BoundDelegateType private
Definition at line 323 of file InputComponent.h.
Referenced by FInputActionUnifiedDelegate(), FInputActionUnifiedDelegate(), FInputActionUnifiedDelegate(), FInputActionUnifiedDelegate(), BindDelegate(), BindDelegate(), BindDelegate(), BindDelegate(), Execute(), GetDelegateForManualSet(), GetDelegateWithKeyForManualSet(), GetObject(), GetUObject(), IsBound(), IsBoundToObject(), and Unbind().
FuncDelegate
TSharedPtr<FInputActionHandlerSignature> FInputActionUnifiedDelegate::FuncDelegate private
Holds the delegate to call.
Definition at line 309 of file InputComponent.h.
Referenced by FInputActionUnifiedDelegate(), BindDelegate(), BindDelegate(), Execute(), GetDelegateForManualSet(), GetObject(), GetUObject(), IsBound(), IsBoundToObject(), and Unbind().
FuncDelegateWithKey
TSharedPtr<FInputActionHandlerWithKeySignature> FInputActionUnifiedDelegate::FuncDelegateWithKey private
Holds the delegate that wants to know the key to call.
Definition at line 311 of file InputComponent.h.
Referenced by FInputActionUnifiedDelegate(), BindDelegate(), Execute(), GetDelegateWithKeyForManualSet(), GetObject(), GetUObject(), IsBound(), IsBoundToObject(), and Unbind().
FuncDynDelegate
TSharedPtr<FInputActionHandlerDynamicSignature> FInputActionUnifiedDelegate::FuncDynDelegate private
Holds the dynamic delegate to call.
Definition at line 313 of file InputComponent.h.
Referenced by FInputActionUnifiedDelegate(), BindDelegate(), Execute(), GetObject(), GetUObject(), IsBound(), IsBoundToObject(), and Unbind().
The documentation for this struct was generated from the following file:
InputComponent.h