Unreal Engine 5.6 C++ API: Metasound::FInputDataDestination Struct Reference
Metasound::FInputDataDestination Struct Reference
FInputDataSource describes the destination of data which produced external to the graph and read internal to the graph.
#include "MetasoundNodeInterface.h"
Public Member Functions
FInputDataDestination ()
FInputDataDestination (const INode &InNode, const FInputDataVertex &InVertex)
Data Fields
const INode * Node = nullptr
Node containing the input data vertex.
FInputDataVertex Vertex
Input data vertex of edge.
Friends
bool METASOUNDGRAPHCORE_API operator!= (const FInputDataDestination &InLeft, const FInputDataDestination &InRight)
bool METASOUNDGRAPHCORE_API operator< (const FInputDataDestination &InLeft, const FInputDataDestination &InRight)
bool METASOUNDGRAPHCORE_API operator== (const FInputDataDestination &InLeft, const FInputDataDestination &InRight)
Check if two FInputDataDestinations are equal.
Detailed Description
FInputDataSource describes the destination of data which produced external to the graph and read internal to the graph.
Definition at line 282 of file MetasoundNodeInterface.h.
Constructor & Destructor Documentation
FInputDataDestination() [1/2]
Metasound::FInputDataDestination::FInputDataDestination () inline
Definition at line 290 of file MetasoundNodeInterface.h.
Referenced by operator!=, operator<, and operator==.
FInputDataDestination() [2/2]
Metasound::FInputDataDestination::FInputDataDestination (const INode & InNode, const FInputDataVertex & InVertex) inline
Definition at line 294 of file MetasoundNodeInterface.h.
References Node, and Vertex.
Friends And Related Symbol Documentation
operator!=
bool METASOUNDGRAPHCORE_API operator!= (const FInputDataDestination & InLeft, const FInputDataDestination & InRight) friend
References FInputDataDestination().
operator<
bool METASOUNDGRAPHCORE_API operator< (const FInputDataDestination & InLeft, const FInputDataDestination & InRight) friend
References FInputDataDestination().
operator==
bool METASOUNDGRAPHCORE_API operator== (const FInputDataDestination & InLeft, const FInputDataDestination & InRight) friend
Check if two FInputDataDestinations are equal.
References FInputDataDestination().
Field Documentation
Node
const INode* Metasound::FInputDataDestination::Node = nullptr
Node containing the input data vertex.
Definition at line 285 of file MetasoundNodeInterface.h.
Referenced by FInputDataDestination(), and Metasound::MakeDestinationDataVertexKey().
Vertex
FInputDataVertex Metasound::FInputDataDestination::Vertex
Input data vertex of edge.
Definition at line 288 of file MetasoundNodeInterface.h.
Referenced by FInputDataDestination(), and Metasound::MakeDestinationDataVertexKey().
The documentation for this struct was generated from the following file:
MetasoundNodeInterface.h