Unreal Engine 5.6 C++ API: StructuredArchiveSlots.h File Reference
StructuredArchiveSlots.h File Reference
#include "Containers/Array.h"
#include "CoreTypes.h"
#include "Formatters/BinaryArchiveFormatter.h"
#include "Misc/Build.h"
#include "Misc/Optional.h"
#include "Serialization/Archive.h"
#include "Serialization/StructuredArchiveFwd.h"
#include "Serialization/StructuredArchiveNameHelpers.h"
#include "Serialization/StructuredArchiveSlotBase.h"
#include "Templates/EnableIf.h"
#include "Templates/IsEnumClass.h"
Data Structures
class FStructuredArchiveArray
Represents an array in the structured archive.
class FStructuredArchiveMap
Represents a map in the structured archive.
class FStructuredArchiveRecord
Represents a record in the structured archive.
class FStructuredArchiveSlot
Contains a value in the archive; either a field or array/map element.
class FStructuredArchiveStream
Represents an unsized sequence of slots in the structured archive (similar to an array, but without a known size).
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::StructuredArchive
namespace UE::StructuredArchive::Private
Macros
#define UE_API FORCEINLINE
Functions
FArchiveFormatterType & UE::StructuredArchive::Private::GetFormatterImpl (FStructuredArchive &Ar)
template<typename T>
FORCEINLINE_DEBUGGABLE void operator<< (FStructuredArchiveSlot Slot, TArray< T > &InArray)
template<>
FORCEINLINE_DEBUGGABLE void operator<< (FStructuredArchiveSlot Slot, TArray< uint8 > &InArray)
Macro Definition Documentation
UE_API
#define UE_API FORCEINLINE
Definition at line 18 of file StructuredArchiveSlots.h.
Function Documentation
operator<<() [1/2]
template<typename T> FORCEINLINE_DEBUGGABLE void operator<< (FStructuredArchiveSlot Slot, TArray< T > & InArray)
Definition at line 227 of file StructuredArchiveSlots.h.
References Array, FStructuredArchiveSlot::EnterArray(), FORCEINLINE_DEBUGGABLE, UE::StructuredArchive::Private::FSlotBase::GetArchiveState(), FArchiveState::IsLoading(), TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::SetNum().
operator<<() [2/2]
template<> FORCEINLINE_DEBUGGABLE void operator<< (FStructuredArchiveSlot Slot, TArray< uint8 > & InArray)
Definition at line 245 of file StructuredArchiveSlots.h.
References FORCEINLINE_DEBUGGABLE, and FStructuredArchiveSlot::Serialize().