Unreal Engine 5.6 C++ API: TMulticastScriptDelegate< InThreadSafetyMode > Class Template Reference
TMulticastScriptDelegate< InThreadSafetyMode > Class Template Reference
Script multi-cast delegate base class.
#include "ScriptDelegates.h"
Public Types
using InvocationListType = TArray<UnicastDelegateType>
using ThreadSafetyMode = typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::ThreadSafetyMode
Public Member Functions
TMulticastScriptDelegate ()=default
TMulticastScriptDelegate (const TMulticastScriptDelegate &Other)
TMulticastScriptDelegate (TMulticastScriptDelegate &&Other)
template<typename OtherThreadSafetyMode UE_REQUIRES>
void Add (const TScriptDelegate< OtherThreadSafetyMode > &InDelegate)
void Add (const TScriptDelegate< ThreadSafetyMode > &InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list.
template<typename OtherThreadSafetyMode UE_REQUIRES>
void AddUnique (const TScriptDelegate< OtherThreadSafetyMode > &InDelegate)
void AddUnique (const TScriptDelegate< ThreadSafetyMode > &InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list if a delegate with the same signature doesn't already exist in the invocation list.
void Clear ()
Removes all functions from this delegate's invocation list.
template<typename OtherThreadSafetyMode UE_REQUIRES>
bool Contains (const TScriptDelegate< OtherThreadSafetyMode > &InDelegate) const
bool Contains (const TScriptDelegate< ThreadSafetyMode > &InDelegate) const
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
bool Contains (const UObject *InObject, FName InFunctionName) const
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
TArray< typename UnicastDelegateType::WeakPtrType * > GetAllObjectRefsEvenIfUnreachable () const
TArray< UObject * > GetAllObjects () const
Returns all objects associated with this multicast-delegate.
TArray< UObject * > GetAllObjectsEvenIfUnreachable () const
Returns all objects associated with this multicast-delegate, even if unreachable.
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this delegate's invocation list, not including sizeof(*this).
bool IsBound () const
Checks to see if any functions are bound to this multi-cast delegate.
TMulticastScriptDelegate & operator= (const TMulticastScriptDelegate &Other)
TMulticastScriptDelegate & operator= (TMulticastScriptDelegate &&Other)
template<class UObjectTemplate>
void ProcessMulticastDelegate (void *Parameters) const
Executes a multi-cast delegate by calling all functions on objects bound to the delegate.
template<typename OtherThreadSafetyMode UE_REQUIRES>
void Remove (const TScriptDelegate< OtherThreadSafetyMode > &InDelegate)
void Remove (const TScriptDelegate< ThreadSafetyMode > &InDelegate)
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
void Remove (const UObject *InObject, FName InFunctionName)
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
void RemoveAll (const UObject *Object)
Removes all delegate bindings from this multicast delegate's invocation list that are bound to the specified object.
template<typename UObjectTemplate>
FString ToString () const
Converts this delegate to a string representation.
Protected Member Functions
void AddInternal (UnicastDelegateType &&InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list.
void AddUniqueInternal (UnicastDelegateType &&InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list, if a delegate with that signature doesn't already exist.
void CompactInvocationList () const
Cleans up any delegates in our invocation list that have expired (performance is O(N))
void RemoveInternal (const UnicastDelegateType &InDelegate) const
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
void RemoveInternal (const UObject *InObject, FName InFunctionName) const
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Protected Attributes
InvocationListType InvocationList
Ordered list functions to invoke when the Broadcast function is called.
Private Types
using Super = TDelegateAccessHandlerBase<InThreadSafetyMode>
using UnicastDelegateType = TScriptDelegate<typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::UnicastThreadSafetyModeForMulticasts>
Friends
class FCallDelegateHelper
class FMulticastDelegateProperty
class FMulticastInlineDelegateProperty
class FMulticastSparseDelegateProperty
FArchive & operator<< (FArchive &Ar, TMulticastScriptDelegate &D)
Multi-cast delegate serialization.
void operator<< (FStructuredArchive::FSlot Slot, TMulticastScriptDelegate &D)
struct TIsZeroConstructType< TMulticastScriptDelegate >
Detailed Description
template<typename InThreadSafetyMode>
class TMulticastScriptDelegate< InThreadSafetyMode >
Script multi-cast delegate base class.
Definition at line 508 of file ScriptDelegates.h.
Member Typedef Documentation
InvocationListType
template<typename InThreadSafetyMode> using TMulticastScriptDelegate< InThreadSafetyMode >::InvocationListType = TArray<UnicastDelegateType>
Definition at line 521 of file ScriptDelegates.h.
Super
template<typename InThreadSafetyMode> using TMulticastScriptDelegate< InThreadSafetyMode >::Super = TDelegateAccessHandlerBase<InThreadSafetyMode> private
Definition at line 511 of file ScriptDelegates.h.
ThreadSafetyMode
template<typename InThreadSafetyMode> using TMulticastScriptDelegate< InThreadSafetyMode >::ThreadSafetyMode = typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::ThreadSafetyMode
Definition at line 520 of file ScriptDelegates.h.
UnicastDelegateType
template<typename InThreadSafetyMode> using TMulticastScriptDelegate< InThreadSafetyMode >::UnicastDelegateType = TScriptDelegate<typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::UnicastThreadSafetyModeForMulticasts> private
Definition at line 517 of file ScriptDelegates.h.
Constructor & Destructor Documentation
TMulticastScriptDelegate() [1/3]
template<typename InThreadSafetyMode> TMulticastScriptDelegate< InThreadSafetyMode >::TMulticastScriptDelegate () default
TMulticastScriptDelegate() [2/3]
template<typename InThreadSafetyMode> TMulticastScriptDelegate< InThreadSafetyMode >::TMulticastScriptDelegate (const TMulticastScriptDelegate< InThreadSafetyMode > & Other) inline
Definition at line 525 of file ScriptDelegates.h.
TMulticastScriptDelegate() [3/3]
template<typename InThreadSafetyMode> TMulticastScriptDelegate< InThreadSafetyMode >::TMulticastScriptDelegate (TMulticastScriptDelegate< InThreadSafetyMode > && Other) inline
Definition at line 553 of file ScriptDelegates.h.
Member Function Documentation
Add() [1/2]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> void TMulticastScriptDelegate< InThreadSafetyMode >::Add (const TScriptDelegate< OtherThreadSafetyMode > & InDelegate) inline
Definition at line 674 of file ScriptDelegates.h.
Add() [2/2]
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::Add (const TScriptDelegate< ThreadSafetyMode > & InDelegate) inline
Adds a function delegate to this multi-cast delegate's invocation list.
Parameters
InDelegate Delegate to add
Definition at line 655 of file ScriptDelegates.h.
AddInternal()
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::AddInternal (UnicastDelegateType && InDelegate) inline protected
Adds a function delegate to this multi-cast delegate's invocation list.
Parameters
InDelegate Delegate to add
Definition at line 1018 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add().
AddUnique() [1/2]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> void TMulticastScriptDelegate< InThreadSafetyMode >::AddUnique (const TScriptDelegate< OtherThreadSafetyMode > & InDelegate) inline
Definition at line 714 of file ScriptDelegates.h.
AddUnique() [2/2]
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::AddUnique (const TScriptDelegate< ThreadSafetyMode > & InDelegate) inline
Adds a function delegate to this multi-cast delegate's invocation list if a delegate with the same signature doesn't already exist in the invocation list.
Parameters
InDelegate Delegate to add
Definition at line 695 of file ScriptDelegates.h.
AddUniqueInternal()
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::AddUniqueInternal (UnicastDelegateType && InDelegate) inline protected
Adds a function delegate to this multi-cast delegate's invocation list, if a delegate with that signature doesn't already exist.
Parameters
InDelegate Delegate to add
Definition at line 1037 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique().
Clear()
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::Clear () inline
Removes all functions from this delegate's invocation list.
Definition at line 813 of file ScriptDelegates.h.
CompactInvocationList()
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::CompactInvocationList () const inline protected
Cleans up any delegates in our invocation list that have expired (performance is O(N))
Definition at line 1074 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::ProcessMulticastDelegate(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove().
Contains() [1/3]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> bool TMulticastScriptDelegate< InThreadSafetyMode >::Contains (const TScriptDelegate< OtherThreadSafetyMode > & InDelegate) const inline
Definition at line 620 of file ScriptDelegates.h.
Contains() [2/3]
template<typename InThreadSafetyMode> bool TMulticastScriptDelegate< InThreadSafetyMode >::Contains (const TScriptDelegate< ThreadSafetyMode > & InDelegate) const inline
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
Parameters
InDelegate Delegate to check
Returns
True if the delegate is already in the list.
Definition at line 602 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains().
Contains() [3/3]
template<typename InThreadSafetyMode> bool TMulticastScriptDelegate< InThreadSafetyMode >::Contains (const UObject * InObject, FName InFunctionName) const inline
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
Parameters
InObject Object of the delegate to check
InFunctionName Function name of the delegate to check
Returns
True if the delegate is already in the list.
Definition at line 641 of file ScriptDelegates.h.
GetAllObjectRefsEvenIfUnreachable()
template<typename InThreadSafetyMode> TArray< typename UnicastDelegateType::WeakPtrType * > TMulticastScriptDelegate< InThreadSafetyMode >::GetAllObjectRefsEvenIfUnreachable () const inline
Definition at line 986 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::GetAllObjectsEvenIfUnreachable().
GetAllObjects()
template<typename InThreadSafetyMode> TArray< UObject * > TMulticastScriptDelegate< InThreadSafetyMode >::GetAllObjects () const inline
Returns all objects associated with this multicast-delegate.
For advanced uses only – you should never need call this function in normal circumstances.
Returns
List of objects bound to this delegate
Definition at line 954 of file ScriptDelegates.h.
GetAllObjectsEvenIfUnreachable()
template<typename InThreadSafetyMode> TArray< UObject * > TMulticastScriptDelegate< InThreadSafetyMode >::GetAllObjectsEvenIfUnreachable () const inline
Returns all objects associated with this multicast-delegate, even if unreachable.
For advanced uses only – you should never need call this function in normal circumstances.
Returns
List of objects bound to this delegate
Definition at line 975 of file ScriptDelegates.h.
GetAllocatedSize()
template<typename InThreadSafetyMode> SIZE_T TMulticastScriptDelegate< InThreadSafetyMode >::GetAllocatedSize () const inline
Returns the amount of memory allocated by this delegate's invocation list, not including sizeof(*this).
Definition at line 1005 of file ScriptDelegates.h.
IsBound()
template<typename InThreadSafetyMode> bool TMulticastScriptDelegate< InThreadSafetyMode >::IsBound () const inline
Checks to see if any functions are bound to this multi-cast delegate.
Returns
True if any functions are bound
Definition at line 589 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::ToString().
operator=() [1/2]
template<typename InThreadSafetyMode> TMulticastScriptDelegate & TMulticastScriptDelegate< InThreadSafetyMode >::operator= (const TMulticastScriptDelegate< InThreadSafetyMode > & Other) inline
Definition at line 537 of file ScriptDelegates.h.
operator=() [2/2]
template<typename InThreadSafetyMode> TMulticastScriptDelegate & TMulticastScriptDelegate< InThreadSafetyMode >::operator= (TMulticastScriptDelegate< InThreadSafetyMode > && Other) inline
Definition at line 565 of file ScriptDelegates.h.
ProcessMulticastDelegate()
template<typename InThreadSafetyMode> template<class UObjectTemplate> void TMulticastScriptDelegate< InThreadSafetyMode >::ProcessMulticastDelegate (void * Parameters) const inline
Executes a multi-cast delegate by calling all functions on objects bound to the delegate.
Always safe to call, even if when no objects are bound, or if objects have expired. In general, you should never call this function directly. Instead, call Broadcast() on a derived class. Note that this function is not truly const because it will clean up any compactable entries in the invocation list.
Parameters
Params Parameter structure
Definition at line 917 of file ScriptDelegates.h.
Remove() [1/3]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> void TMulticastScriptDelegate< InThreadSafetyMode >::Remove (const TScriptDelegate< OtherThreadSafetyMode > & InDelegate) inline
Definition at line 754 of file ScriptDelegates.h.
Remove() [2/3]
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::Remove (const TScriptDelegate< ThreadSafetyMode > & InDelegate) inline
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Note that the order of the delegates may not be preserved!
Parameters
InDelegate Delegate to remove
Definition at line 735 of file ScriptDelegates.h.
Remove() [3/3]
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::Remove (const UObject * InObject, FName InFunctionName) inline
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Note that the order of the delegates may not be preserved!
Parameters
InObject Object of the delegate to remove
InFunctionName Function name of the delegate to remove
Definition at line 776 of file ScriptDelegates.h.
RemoveAll()
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::RemoveAll (const UObject * Object) inline
Removes all delegate bindings from this multicast delegate's invocation list that are bound to the specified object.
This method also compacts the invocation list.
Parameters
InObject The object to remove bindings for.
Definition at line 795 of file ScriptDelegates.h.
RemoveInternal() [1/2]
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::RemoveInternal (const UnicastDelegateType & InDelegate) const inline protected
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Note that the order of the delegates may not be preserved!
Parameters
InDelegate Delegate to remove
Definition at line 1049 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove().
RemoveInternal() [2/2]
template<typename InThreadSafetyMode> void TMulticastScriptDelegate< InThreadSafetyMode >::RemoveInternal (const UObject * InObject, FName InFunctionName) const inline protected
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Note that the order of the delegates may not be preserved!
Parameters
InObject Object of the delegate to remove
InFunctionName Function name of the delegate to remove
Definition at line 1061 of file ScriptDelegates.h.
ToString()
template<typename InThreadSafetyMode> template<typename UObjectTemplate> FString TMulticastScriptDelegate< InThreadSafetyMode >::ToString () const inline
Converts this delegate to a string representation.
Returns
Delegate in string format
Definition at line 825 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::ToString().
Friends And Related Symbol Documentation
FCallDelegateHelper
template<typename InThreadSafetyMode> friend class FCallDelegateHelper friend
Definition at line 1092 of file ScriptDelegates.h.
FMulticastDelegateProperty
template<typename InThreadSafetyMode> friend class FMulticastDelegateProperty friend
Definition at line 1087 of file ScriptDelegates.h.
FMulticastInlineDelegateProperty
template<typename InThreadSafetyMode> friend class FMulticastInlineDelegateProperty friend
Definition at line 1088 of file ScriptDelegates.h.
FMulticastSparseDelegateProperty
template<typename InThreadSafetyMode> friend class FMulticastSparseDelegateProperty friend
Definition at line 1089 of file ScriptDelegates.h.
operator<< [1/2]
template<typename InThreadSafetyMode> FArchive & operator<< (FArchive & Ar, TMulticastScriptDelegate< InThreadSafetyMode > & D) friend
Multi-cast delegate serialization.
Definition at line 849 of file ScriptDelegates.h.
operator<< [2/2]
template<typename InThreadSafetyMode> void operator<< (FStructuredArchive::FSlot Slot, TMulticastScriptDelegate< InThreadSafetyMode > & D) friend
Definition at line 887 of file ScriptDelegates.h.
TIsZeroConstructType< TMulticastScriptDelegate >
template<typename InThreadSafetyMode> friend struct TIsZeroConstructType< TMulticastScriptDelegate > friend
Definition at line 1092 of file ScriptDelegates.h.
Field Documentation
InvocationList
template<typename InThreadSafetyMode> InvocationListType TMulticastScriptDelegate< InThreadSafetyMode >::InvocationList mutable protected
Ordered list functions to invoke when the Broadcast function is called.
Definition at line 1084 of file ScriptDelegates.h.
The documentation for this class was generated from the following file:
ScriptDelegates.h