Unreal Engine 5.6 C++ API: FRefCountBase Class Reference
FRefCountBase Class Reference
Base class implementing thread-safe reference counting.
#include "RefCounting.h"
Public Member Functions
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Private Types
using Super = UE::Private::TTransactionalAtomicRefCount<uint32>
Static Private Member Functions
static void DeleteThis (const Super *This)
Additional Inherited Members
Private Member Functions inherited from UE::Private::TTransactionalAtomicRefCount< uint32 >
uint32 AddRef () const
uint32 GetRefCount () const
uint32 Release () const
Detailed Description
Base class implementing thread-safe reference counting.
Definition at line 212 of file RefCounting.h.
Member Typedef Documentation
Super
using FRefCountBase::Super = UE::Private::TTransactionalAtomicRefCount<uint32> private
Definition at line 237 of file RefCounting.h.
Constructor & Destructor Documentation
FRefCountBase() [1/2]
FRefCountBase::FRefCountBase () default
Referenced by FRefCountBase(), DeleteThis(), and operator=().
~FRefCountBase()
virtual FRefCountBase::~FRefCountBase () virtual default
FRefCountBase() [2/2]
FRefCountBase::FRefCountBase (const FRefCountBase & Rhs) delete
References FRefCountBase().
Member Function Documentation
AddRef()
FReturnedRefCountValue FRefCountBase::AddRef () const inline
Definition at line 221 of file RefCounting.h.
References UE::Private::TTransactionalAtomicRefCount< uint32 >::AddRef().
Referenced by FSkeletalMeshLODRenderData::FSkeletalMeshLODRenderData(), and UE::UnifiedError::FRefCountedErrorDetails::AddRef().
DeleteThis()
void FRefCountBase::DeleteThis (const Super * This) inline static private
Definition at line 239 of file RefCounting.h.
References FRefCountBase().
GetRefCount()
uint32 FRefCountBase::GetRefCount () const inline
Definition at line 231 of file RefCounting.h.
References UE::Private::TTransactionalAtomicRefCount< uint32 >::GetRefCount().
Referenced by FSkeletalMeshLODRenderData::~FSkeletalMeshLODRenderData(), and UE::UnifiedError::FRefCountedErrorDetails::GetRefCount().
operator=()
FRefCountBase & FRefCountBase::operator= (const FRefCountBase & Rhs) delete
References FRefCountBase().
Release()
uint32 FRefCountBase::Release () const inline
Definition at line 226 of file RefCounting.h.
References UE::Private::TTransactionalAtomicRefCount< uint32 >::Release().
Referenced by UE::UnifiedError::FRefCountedErrorDetails::Release().
The documentation for this class was generated from the following file:
RefCounting.h