Unreal Engine 5.6 C++ API: UE::CurveEditor::FTangentMirrorSolver Class Reference
UE::CurveEditor::FTangentMirrorSolver Class Reference
Given keys that are between an imaginary, x-axis aligned mirror edge and dragged edge, this class facilitates recalculates the tangents for all specified keys.
#include "TangentMirrorSolver.h"
Public Member Functions
FTangentMirrorSolver (double InStartY, double InMiddlePointY)
InStartY and InMiddlePointY define two imaginary, x-axis aligned lines.
bool AddTangents (const FCurveEditor &InCurveEditor, const FCurveModelID &InCurveId, TConstArrayView< FKeyHandle > InKeys)
Adds tangents that are be mirrored.
template<typename TProcessCallback>
requires std::is_invocable_v<TProcessCallback, const FMirrorableTangentInfo& /*TangentInfo*/>
bool AddTangents (const FCurveEditor &InCurveEditor, const FCurveModelID &InCurveId, TConstArrayView< FKeyHandle > InKeys, TProcessCallback &&InProcessTangentInfo)
Version that allows you to do additional processing for the tangents.
void OnMoveEdge (const FCurveEditor &InCurveEditor, double InDraggedEdgeHeight)
Recomputes the tangents angles and updates the key attributes.
Data Fields
TMap< FCurveModelID, FCurveTangentMirrorData > CurveData
This memory is reused across OnMoveEdge to hold the updated tangents.
const double MiddlePointY
Height of the mirroring line.
const double StartY
Height of the dragged line.
Detailed Description
Given keys that are between an imaginary, x-axis aligned mirror edge and dragged edge, this class facilitates recalculates the tangents for all specified keys.
The tangents are linearly interpolated, ensuring that if the dragged edge crosses to the opposite side of the mirror edge, the tangents will flip, resulting in mirrored curves.
Inputs:
Height of the dragged edge aligned to the x-axis
Height of the x-axis-aligned mirror edge
Keys originally located between the dragged and mirror edges
Example: Given a grid with a single key at a 45-degree angle, moving the top edge:
An equal distance past the bottom edge will result in a tangent of -45 degrees for the key.
Halfway between the starting position and the bottom edge will result in a tangent of 22.5 degrees for the key.
Note
This class only recalculates tangents. To adjust the positions of the keys use e.g. FPositionMirrorSolver.
Definition at line 31 of file TangentMirrorSolver.h.
Constructor & Destructor Documentation
FTangentMirrorSolver()
UE::CurveEditor::FTangentMirrorSolver::FTangentMirrorSolver (double InStartY, double InMiddlePointY) inline explicit
InStartY and InMiddlePointY define two imaginary, x-axis aligned lines.
All keys added must be between or on these two lines for the mirroring to work as expected.
Parameters
InStartY The height of the line that is moved. It determines how the tangents are interpolated.
InMiddlePointY The height of the line on which the points are moved.
Definition at line 85 of file TangentMirrorSolver.h.
References MiddlePointY, and StartY.
Member Function Documentation
AddTangents() [1/2]
bool UE::CurveEditor::FTangentMirrorSolver::AddTangents (const FCurveEditor & InCurveEditor, const FCurveModelID & InCurveId, TConstArrayView< FKeyHandle > InKeys) inline
Adds tangents that are be mirrored.
InStartY and InMiddlePointY define two imaginary, x-axis aligned lines. All keys must be between or on these two lines for the mirroring to work as expected.
Parameters
InCurveEditor Used to get and set tangent values
InCurveId The curve that all keys lie on
InKeys The keys whose tangents to recompute
Returns
Whether any of the keys can be interpolated (only user specified tangents can be interpolated).
Definition at line 90 of file TangentMirrorSolver.h.
References AddTangents().
Referenced by AddTangents().
AddTangents() [2/2]
template<typename TProcessCallback> requires std::is_invocable_v<TProcessCallback, const FMirrorableTangentInfo& /*TangentInfo*/> bool UE::CurveEditor::FTangentMirrorSolver::AddTangents (const FCurveEditor & InCurveEditor, const FCurveModelID & InCurveId, TConstArrayView< FKeyHandle > InKeys, TProcessCallback && InProcessTangentInfo)
Version that allows you to do additional processing for the tangents.
For example, you may want to compute falloff values for each key. In that case, you probably want to manually iterate CurveData and use the version of RecomputeMirroringParallel that allows you to interpolate tangent values further.
Definition at line 96 of file TangentMirrorSolver.h.
References CurveData, UE::CurveEditor::FilterMirrorableTangents(), MiddlePointY, MoveTemp(), and StartY.
OnMoveEdge()
void UE::CurveEditor::FTangentMirrorSolver::OnMoveEdge (const FCurveEditor & InCurveEditor, double InDraggedEdgeHeight) inline
Recomputes the tangents angles and updates the key attributes.
Definition at line 113 of file TangentMirrorSolver.h.
References CurveData, and UE::CurveEditor::RecomputeMirroringParallel().
Field Documentation
CurveData
TMap<FCurveModelID, FCurveTangentMirrorData> UE::CurveEditor::FTangentMirrorSolver::CurveData
This memory is reused across OnMoveEdge to hold the updated tangents.
Caching the memory speeds up the re-computation.
Definition at line 41 of file TangentMirrorSolver.h.
Referenced by AddTangents(), and OnMoveEdge().
MiddlePointY
const double UE::CurveEditor::FTangentMirrorSolver::MiddlePointY
Height of the mirroring line.
Definition at line 38 of file TangentMirrorSolver.h.
Referenced by FTangentMirrorSolver(), and AddTangents().
StartY
const double UE::CurveEditor::FTangentMirrorSolver::StartY
Height of the dragged line.
Definition at line 36 of file TangentMirrorSolver.h.
Referenced by FTangentMirrorSolver(), and AddTangents().
The documentation for this class was generated from the following file:
TangentMirrorSolver.h