Unreal Engine 5.6 C++ API: IPixelStreaming2Module Class Reference
IPixelStreaming2Module Class Reference abstract
The IPixelStreaming2Module interface manages the core functionality of the Pixel Streaming system.
#include "IPixelStreaming2Module.h"
Public Member Functions
virtual TSharedPtr< IPixelStreaming2AudioProducer > CreateAudioProducer ()=0
Creates a new audio producer.
virtual TSharedPtr< IPixelStreaming2Streamer > CreateStreamer (const FString &StreamerId, const FString &Type=TEXT("DefaultRtc"))=0
Creates a new streamer.
virtual TSharedPtr< IPixelStreaming2VideoProducer > CreateVideoProducer ()=0
Creates a new video producer.
DECLARE_EVENT_OneParam (IPixelStreaming2Module, FReadyEvent, IPixelStreaming2Module &)
Event fired when internal streamer is initialized and the methods on this module are ready for use.
virtual TSharedPtr< IPixelStreaming2Streamer > DeleteStreamer (const FString &StreamerId)=0
Remove a streamer by an ID.
virtual void DeleteStreamer (TSharedPtr< IPixelStreaming2Streamer > ToBeDeleted)=0
Remove a streamer by its pointer.
virtual TSharedPtr< IPixelStreaming2Streamer > FindStreamer (const FString &StreamerId)=0
Find a streamer by an ID.
virtual void ForEachStreamer (const TFunction< void(TSharedPtr< IPixelStreaming2Streamer >)> &Func)=0
A method for iterating through all of the streamers on the module.
virtual FString GetDefaultConnectionURL ()=0
Get the Default Connection URL ("ws://127.0.0.1:8888").
virtual FString GetDefaultStreamerID ()=0
Get the Default Streamer ID.
virtual TArray< FString > GetStreamerIds ()=0
Returns a TArray containing the keys to the currently held streamers.
virtual bool IsReady ()=0
Is the PixelStreaming2 module actually ready to use?
virtual FReadyEvent & OnReady ()=0
A getter for the OnReady event.
virtual bool StartStreaming ()=0
Starts streaming on all streamers.
virtual void StopStreaming ()=0
Stops all streamers from streaming.
UE_DEPRECATED (5.6, "GetDefaultSignallingURL has been deprecated. Please use GetDefaultConnectionURL instead.") virtual FString GetDefaultSignallingURL()
Get the Default Signaling URL ("ws://127.0.0.1:8888").
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IPixelStreaming2Module & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded.
Detailed Description
The IPixelStreaming2Module interface manages the core functionality of the Pixel Streaming system.
This class provides access to streamers, video and audio producers, and handles starting and stopping the streaming process. It also allows interaction with the signalling server and manages the lifecycle of streamers within the Pixel Streaming system.
Definition at line 20 of file IPixelStreaming2Module.h.
Member Function Documentation
CreateAudioProducer()
virtual TSharedPtr< IPixelStreaming2AudioProducer > IPixelStreaming2Module::CreateAudioProducer () pure virtual
Creates a new audio producer.
Any audio you push in with PushAudio will be mixed with other audio sources before being streamed.
Note
Users are responsible for the lifetime of this object.
Returns
An audio producer interface for you to push audio in to.
CreateStreamer()
virtual TSharedPtr< IPixelStreaming2Streamer > IPixelStreaming2Module::CreateStreamer (const FString & StreamerId, const FString & Type = TEXT("DefaultRtc")) pure virtual
Creates a new streamer.
Parameters
StreamerId - The ID of the Streamer to be created.
Returns
SharedPtr to the streamer.
CreateVideoProducer()
virtual TSharedPtr< IPixelStreaming2VideoProducer > IPixelStreaming2Module::CreateVideoProducer () pure virtual
Creates a new video producer.
Returns
An video producer interface for you to push video frames in to.
DECLARE_EVENT_OneParam()
IPixelStreaming2Module::DECLARE_EVENT_OneParam (IPixelStreaming2Module , FReadyEvent , IPixelStreaming2Module &)
Event fired when internal streamer is initialized and the methods on this module are ready for use.
DeleteStreamer() [1/2]
virtual TSharedPtr< IPixelStreaming2Streamer > IPixelStreaming2Module::DeleteStreamer (const FString & StreamerId) pure virtual
Remove a streamer by an ID.
Parameters
StreamerId - The ID of the streamer to be removed.
Returns
The removed streamer. nullptr if the streamer wasn't found.
DeleteStreamer() [2/2]
virtual void IPixelStreaming2Module::DeleteStreamer (TSharedPtr< IPixelStreaming2Streamer > ToBeDeleted) pure virtual
Remove a streamer by its pointer.
Parameters
ToBeDeleted The streamer to remove from the internal management.
FindStreamer()
virtual TSharedPtr< IPixelStreaming2Streamer > IPixelStreaming2Module::FindStreamer (const FString & StreamerId) pure virtual
Find a streamer by an ID.
Parameters
StreamerId - The ID of the streamer to be found.
Returns
A pointer to the interface for a streamer. nullptr if the streamer isn't found.
ForEachStreamer()
virtual void IPixelStreaming2Module::ForEachStreamer (const TFunction< void(TSharedPtr< IPixelStreaming2Streamer >)> & Func) pure virtual
A method for iterating through all of the streamers on the module.
Parameters
Func The lambda to execute with each streamer.
Get()
IPixelStreaming2Module & IPixelStreaming2Module::Get () inline static
Singleton-like access to this module's interface.
Beware calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 29 of file IPixelStreaming2Module.h.
References FModuleManager::LoadModuleChecked().
GetDefaultConnectionURL()
virtual FString IPixelStreaming2Module::GetDefaultConnectionURL () pure virtual
Get the Default Connection URL ("ws://127.0.0.1:8888").
Returns
FString The default connection url ("ws://127.0.0.1:8888").
Referenced by UE_DEPRECATED().
GetDefaultStreamerID()
virtual FString IPixelStreaming2Module::GetDefaultStreamerID () pure virtual
Get the Default Streamer ID.
Returns
FString The default streamer ID.
GetStreamerIds()
virtual TArray< FString > IPixelStreaming2Module::GetStreamerIds () pure virtual
Returns a TArray containing the keys to the currently held streamers.
Returns
TArray containing the keys to the currently held streamers.
IsAvailable()
bool IPixelStreaming2Module::IsAvailable () inline static
Checks to see if this module is loaded.
Returns
True if the module is loaded.
Definition at line 39 of file IPixelStreaming2Module.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
IsReady()
virtual bool IPixelStreaming2Module::IsReady () pure virtual
Is the PixelStreaming2 module actually ready to use?
Is the streamer created.
Returns
True if Pixel Streaming module methods are ready for use.
OnReady()
virtual FReadyEvent & IPixelStreaming2Module::OnReady () pure virtual
A getter for the OnReady event.
Intent is for users to call IPixelStreaming2Module::Get().OnReady().AddXXX.
Returns
The bindable OnReady event.
StartStreaming()
virtual bool IPixelStreaming2Module::StartStreaming () pure virtual
Starts streaming on all streamers.
Returns
False if the module was not able to start streaming.
StopStreaming()
virtual void IPixelStreaming2Module::StopStreaming () pure virtual
Stops all streamers from streaming.
UE_DEPRECATED()
IPixelStreaming2Module::UE_DEPRECATED (5. 6, "GetDefaultSignallingURL has been deprecated. Please use GetDefaultConnectionURL instead.") inline
Get the Default Signaling URL ("ws://127.0.0.1:8888").
Returns
FString The default signaling url ("ws://127.0.0.1:8888").
Definition at line 134 of file IPixelStreaming2Module.h.
References GetDefaultConnectionURL().
The documentation for this class was generated from the following file:
IPixelStreaming2Module.h