Unreal Engine 5.6 C++ API: FTimerUnifiedDelegate Struct Reference
FTimerUnifiedDelegate Struct Reference
Simple interface to wrap a timer delegate that can be either native or dynamic.
#include "TimerManager.h"
Public Member Functions
FTimerUnifiedDelegate ()
FTimerUnifiedDelegate (const FTimerUnifiedDelegate &)=delete
FTimerUnifiedDelegate (FTimerDelegate const &D)
FTimerUnifiedDelegate (FTimerDynamicDelegate const &D)
FTimerUnifiedDelegate (FTimerFunction &&Callback)
FTimerUnifiedDelegate (FTimerUnifiedDelegate &&)=default
void Execute () const
const void * GetBoundObject () const
bool IsBound () const
FTimerUnifiedDelegate & operator= (const FTimerUnifiedDelegate &)=delete
FTimerUnifiedDelegate & operator= (FTimerUnifiedDelegate &&)=default
FString ToString () const
Utility to output info about delegate as a string.
void Unbind ()
Data Fields
FTimerDelegateVariant VariantDelegate
Holds the delegate to call.
Detailed Description
Simple interface to wrap a timer delegate that can be either native or dynamic.
Definition at line 31 of file TimerManager.h.
Constructor & Destructor Documentation
FTimerUnifiedDelegate() [1/6]
FTimerUnifiedDelegate::FTimerUnifiedDelegate () inline
Definition at line 36 of file TimerManager.h.
Referenced by FTimerUnifiedDelegate(), FTimerUnifiedDelegate(), operator=(), and operator=().
FTimerUnifiedDelegate() [2/6]
FTimerUnifiedDelegate::FTimerUnifiedDelegate (FTimerDelegate const & D) inline
Definition at line 38 of file TimerManager.h.
References VariantDelegate.
FTimerUnifiedDelegate() [3/6]
FTimerUnifiedDelegate::FTimerUnifiedDelegate (FTimerDynamicDelegate const & D) inline
Definition at line 39 of file TimerManager.h.
References VariantDelegate.
FTimerUnifiedDelegate() [4/6]
FTimerUnifiedDelegate::FTimerUnifiedDelegate (FTimerFunction && Callback) inline
Definition at line 40 of file TimerManager.h.
References MoveTemp(), and VariantDelegate.
FTimerUnifiedDelegate() [5/6]
FTimerUnifiedDelegate::FTimerUnifiedDelegate (FTimerUnifiedDelegate &&) default
References FTimerUnifiedDelegate().
FTimerUnifiedDelegate() [6/6]
FTimerUnifiedDelegate::FTimerUnifiedDelegate (const FTimerUnifiedDelegate &) delete
References FTimerUnifiedDelegate().
Member Function Documentation
Execute()
void FTimerUnifiedDelegate::Execute () const
GetBoundObject()
const void * FTimerUnifiedDelegate::GetBoundObject () const
IsBound()
bool FTimerUnifiedDelegate::IsBound () const
operator=() [1/2]
FTimerUnifiedDelegate & FTimerUnifiedDelegate::operator= (const FTimerUnifiedDelegate &) delete
References FTimerUnifiedDelegate().
operator=() [2/2]
FTimerUnifiedDelegate & FTimerUnifiedDelegate::operator= (FTimerUnifiedDelegate &&) default
References FTimerUnifiedDelegate().
ToString()
FString FTimerUnifiedDelegate::ToString () const
Utility to output info about delegate as a string.
Unbind()
void FTimerUnifiedDelegate::Unbind () inline
Definition at line 48 of file TimerManager.h.
References VariantDelegate.
Field Documentation
VariantDelegate
FTimerDelegateVariant FTimerUnifiedDelegate::VariantDelegate
Holds the delegate to call.
Definition at line 34 of file TimerManager.h.
Referenced by FTimerUnifiedDelegate(), FTimerUnifiedDelegate(), FTimerUnifiedDelegate(), and Unbind().
The documentation for this struct was generated from the following file:
TimerManager.h