Unreal Engine 5.6 C++ Documentation: FBasedMovementInfo Struct Reference
FBasedMovementInfo Struct Reference
Struct to hold information about the "base" object the character is standing on.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/Character.h>
Public Member Functions
bool HasRelativeLocation () const
Is location relative?
bool HasRelativeRotation () const
Is rotation relative or absolute?
bool IsBaseUnresolved () const
Return true if the client should have MovementBase, but it hasn't replicated (possibly component has not streamed in).
Public Attributes
uint16 BaseID = 0
Unique (within a reasonable timespan) ID of the base component.
uint8 bServerHasBaseComponent:1 = false
Whether the server says that there is a base.
uint8 bRelativeRotation:1 = false
Whether rotation is relative to the base or absolute.
uint8 bServerHasVelocity:1 = false
Whether there is a velocity on the server.
FName BoneName
Bone name on component, for skeletal meshes.
TObjectPtr< UPrimitiveComponent > MovementBase = nullptr
Component we are based on.
FVector_NetQuantize100 Location
Location relative to MovementBase.
FRotator Rotation = FRotator(0.f)
Rotation: relative to MovementBase if HasRelativeRotation() is true, absolute otherwise.
Detailed Description
Struct to hold information about the "base" object the character is standing on.
Definition at line 175 of file Character.h.
Member Function Documentation
HasRelativeLocation()
bool FBasedMovementInfo::HasRelativeLocation () const inline
Is location relative?
Definition at line 213 of file Character.h.
References HasRelativeLocation(), MovementBase, and MovementBaseUtility::UseRelativeLocation().
HasRelativeRotation()
bool FBasedMovementInfo::HasRelativeRotation () const inline
Is rotation relative or absolute?
It can only be relative if location is also relative.
Definition at line 219 of file Character.h.
References bRelativeRotation, and HasRelativeLocation().
IsBaseUnresolved()
bool FBasedMovementInfo::IsBaseUnresolved () const inline
Return true if the client should have MovementBase, but it hasn't replicated (possibly component has not streamed in).
Definition at line 225 of file Character.h.
References bServerHasBaseComponent, and MovementBase.
Member Data Documentation
BaseID
uint16 FBasedMovementInfo::BaseID = 0
Unique (within a reasonable timespan) ID of the base component.
Can be used to detect changes in the base when the pointer can't replicate, eg during fast shared replication.
Definition at line 182 of file Character.h.
BoneName
FName FBasedMovementInfo::BoneName
Bone name on component, for skeletal meshes.
NAME_None if not a skeletal mesh or if bone is invalid.
Definition at line 198 of file Character.h.
bRelativeRotation
uint8 FBasedMovementInfo::bRelativeRotation
Whether rotation is relative to the base or absolute.
It can only be relative if location is also relative.
Definition at line 190 of file Character.h.
bServerHasBaseComponent
uint8 FBasedMovementInfo::bServerHasBaseComponent
Whether the server says that there is a base.
On clients, the component may not have resolved yet.
Definition at line 186 of file Character.h.
bServerHasVelocity
uint8 FBasedMovementInfo::bServerHasVelocity
Whether there is a velocity on the server.
Used for forcing replication when velocity goes to zero.
Definition at line 194 of file Character.h.
Location
FVector_NetQuantize100 FBasedMovementInfo::Location
Location relative to MovementBase.
Only valid if HasRelativeLocation() is true.
Definition at line 206 of file Character.h.
MovementBase
TObjectPtr<UPrimitiveComponent> FBasedMovementInfo::MovementBase = nullptr
Component we are based on.
Definition at line 202 of file Character.h.
Rotation
FRotator FBasedMovementInfo::Rotation = FRotator(0.f)
Rotation: relative to MovementBase if HasRelativeRotation() is true, absolute otherwise.
Definition at line 210 of file Character.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/Character.h