Unreal Engine 5.6 C++ API: FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName > Struct Template Reference
FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName > Struct Template Reference
#include "PerQualityLevelProperties.h"
Public Types
typedef _StructType StructType
typedef _ValueType ValueType
Public Member Functions
FPerQualityLevelProperty ()
~FPerQualityLevelProperty ()
void ConvertQualityLevelData (const TMap< FName, _ValueType > &PlatformData, const TMultiMap< FName, FName > &PerPlatformToQualityLevel, _ValueType Default)
void ConvertQualityLevelDataUsingCVar (const TMap< FName, _ValueType > &PlatformData, _ValueType Default, bool bRequireAllPlatformsKnown)
_ValueType GetDefault () const
_ValueType GetLowestValue () const
FSupportedQualityLevelArray GetSupportedQualityLevels (const TCHAR *InPlatformName=nullptr) const
_ValueType GetValue (int32 QualityLevel) const
int32 GetValueForPlatform (const ITargetPlatform *TargetPlatform) const
_ValueType GetValueForQualityLevel (int32 QualityLevel) const
bool Serialize (FArchive &Ar)
bool Serialize (FStructuredArchive::FSlot Slot)
bool SerializeFromMismatchedTag (const FPropertyTag &Tag, FArchive &Ar)
void SetQualityLevelCVarForCooking (const TCHAR *InCVarName, const TCHAR *InSection)
void StripQualityLevelForCooking (const TCHAR *InPlatformName=nullptr)
UE_DEPRECATED (5.4, "If no cvar is associated with the property, all quality levels will be keept when cooking. Call SetQualityLevelCVarForCooking to strip unsupported quality levels when cooking") void Init(const TCHAR *InCVarName
UE_DEPRECATED (5.5, "Use ConvertQualityLevelData") void ConvertQualtiyLevelData(TMap< FName
UE_DEPRECATED (5.5, "Use StripQualityLevelForCooking") void StripQualtiyLevelForCooking(const TCHAR *InPlatformName
Data Fields
FString CVarName
_ValueType TMultiMap< FName, FName > _ValueType Default
const TCHAR * InSection
_ValueType TMultiMap< FName, FName > & PerPlatformToQualityLevel
_ValueType & PlatformData
FString ScalabilitySection
Private Member Functions
void StreamArchive (FArchive &Ar)
void StreamStructuredArchive (FStructuredArchive::FSlot Slot)
Private Attributes
TPimplPtr< QualityLevelProperty::FSavedData< ValueType >, EPimplPtrMode::DeepCopy > SavedValue
Store values here during harvesting so they can be restored during PostSave.
Friends
FArchive & operator<< (FArchive &Ar, FPerQualityLevelProperty &Property)
void operator<< (FStructuredArchive::FSlot Slot, FPerQualityLevelProperty &Property)
Detailed Description
template<typename _StructType, typename _ValueType, EName _BasePropertyName>
struct FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >
Definition at line 81 of file PerQualityLevelProperties.h.
Member Typedef Documentation
StructType
template<typename _StructType, typename _ValueType, EName _BasePropertyName> typedef _StructType FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::StructType
Definition at line 84 of file PerQualityLevelProperties.h.
ValueType
template<typename _StructType, typename _ValueType, EName _BasePropertyName> typedef _ValueType FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::ValueType
Definition at line 83 of file PerQualityLevelProperties.h.
Constructor & Destructor Documentation
FPerQualityLevelProperty()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::FPerQualityLevelProperty () inline
Definition at line 86 of file PerQualityLevelProperties.h.
Referenced by operator<<, and operator<<.
~FPerQualityLevelProperty()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::~FPerQualityLevelProperty () inline
Definition at line 89 of file PerQualityLevelProperties.h.
Member Function Documentation
ConvertQualityLevelData()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> void FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::ConvertQualityLevelData (const TMap< FName, _ValueType > & PlatformData, const TMultiMap< FName, FName > & PerPlatformToQualityLevel, _ValueType Default)
References Default, PerPlatformToQualityLevel, and PlatformData.
ConvertQualityLevelDataUsingCVar()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> void FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::ConvertQualityLevelDataUsingCVar (const TMap< FName, _ValueType > & PlatformData, _ValueType Default, bool bRequireAllPlatformsKnown)
References Default, and PlatformData.
GetDefault()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> _ValueType FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetDefault () const inline
Definition at line 148 of file PerQualityLevelProperties.h.
References StaticCast().
GetLowestValue()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> _ValueType FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetLowestValue () const inline
Definition at line 159 of file PerQualityLevelProperties.h.
References StaticCast(), and Value.
GetSupportedQualityLevels()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FSupportedQualityLevelArray FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetSupportedQualityLevels (const TCHAR * InPlatformName = nullptr) const
GetValue()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> _ValueType FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetValue (int32 QualityLevel) const inline
Definition at line 154 of file PerQualityLevelProperties.h.
References GetValueForQualityLevel().
GetValueForPlatform()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> int32 FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetValueForPlatform (const ITargetPlatform * TargetPlatform) const
GetValueForQualityLevel()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> _ValueType FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::GetValueForQualityLevel (int32 QualityLevel) const inline
Definition at line 91 of file PerQualityLevelProperties.h.
References StaticCast(), and Value.
Referenced by GetValue().
Serialize() [1/2]
template<typename _StructType, typename _ValueType, EName _BasePropertyName> bool FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::Serialize (FArchive & Ar) inline
Definition at line 189 of file PerQualityLevelProperties.h.
References Ar.
Serialize() [2/2]
template<typename _StructType, typename _ValueType, EName _BasePropertyName> bool FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::Serialize (FStructuredArchive::FSlot Slot) inline
Definition at line 196 of file PerQualityLevelProperties.h.
SerializeFromMismatchedTag()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> bool FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::SerializeFromMismatchedTag (const FPropertyTag & Tag, FArchive & Ar) inline
Definition at line 175 of file PerQualityLevelProperties.h.
References Ar, StaticCast(), and FPropertyTag::Type.
SetQualityLevelCVarForCooking()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> void FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::SetQualityLevelCVarForCooking (const TCHAR * InCVarName, const TCHAR * InSection) inline
Definition at line 134 of file PerQualityLevelProperties.h.
References CVarName, InSection, and ScalabilitySection.
StreamArchive()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> void FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::StreamArchive (FArchive & Ar) private
References Ar.
StreamStructuredArchive()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> void FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::StreamStructuredArchive (FStructuredArchive::FSlot Slot) private
StripQualityLevelForCooking()
template<typename _StructType, typename _ValueType, EName _BasePropertyName> void FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::StripQualityLevelForCooking (const TCHAR * InPlatformName = nullptr)
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/3]
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::UE_DEPRECATED (5. 4, "If no cvar is associated with the property, all quality levels will be keept when cooking. Call SetQualityLevelCVarForCooking to strip unsupported quality levels when cooking") const
UE_DEPRECATED() [2/3]
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::UE_DEPRECATED (5. 5, "Use ConvertQualityLevelData")
UE_DEPRECATED() [3/3]
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::UE_DEPRECATED (5. 5, "Use StripQualityLevelForCooking") const
References StripQualityLevelForCooking().
Friends And Related Symbol Documentation
operator<< [1/2]
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FArchive & operator<< (FArchive & Ar, FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName > & Property) friend
Definition at line 210 of file PerQualityLevelProperties.h.
References FPerQualityLevelProperty(), Ar, and Property.
operator<< [2/2]
template<typename _StructType, typename _ValueType, EName _BasePropertyName> void operator<< (FStructuredArchive::FSlot Slot, FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName > & Property) friend
Definition at line 211 of file PerQualityLevelProperties.h.
References FPerQualityLevelProperty(), and Property.
Field Documentation
CVarName
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FString FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::CVarName
Definition at line 205 of file PerQualityLevelProperties.h.
Referenced by SetQualityLevelCVarForCooking().
Default
template<typename _StructType, typename _ValueType, EName _BasePropertyName> _ValueType TMultiMap<FName, FName> _ValueType FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::Default
Initial value:
{
        ConvertQualityLevelData(PlatformData, PerPlatformToQualityLevel, Default)
Definition at line 123 of file PerQualityLevelProperties.h.
Referenced by ConvertQualityLevelData(), and ConvertQualityLevelDataUsingCVar().
InSection
template<typename _StructType, typename _ValueType, EName _BasePropertyName> const TCHAR* FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::InSection
Initial value:
{
        SetQualityLevelCVarForCooking(InCVarName, InSection)
Definition at line 143 of file PerQualityLevelProperties.h.
Referenced by SetQualityLevelCVarForCooking().
PerPlatformToQualityLevel
template<typename _StructType, typename _ValueType, EName _BasePropertyName> _ValueType TMultiMap<FName, FName>& FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::PerPlatformToQualityLevel
Definition at line 123 of file PerQualityLevelProperties.h.
Referenced by ConvertQualityLevelData().
PlatformData
template<typename _StructType, typename _ValueType, EName _BasePropertyName> _ValueType& FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::PlatformData
Definition at line 123 of file PerQualityLevelProperties.h.
Referenced by ConvertQualityLevelData(), and ConvertQualityLevelDataUsingCVar().
SavedValue
template<typename _StructType, typename _ValueType, EName _BasePropertyName> TPimplPtr<QualityLevelProperty::FSavedData<ValueType>, EPimplPtrMode::DeepCopy> FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::SavedValue private
Store values here during harvesting so they can be restored during PostSave.
Why is this a TPimplPtr<...>. The idea is to only restore the state if it was first saved in SavedValue. To detect if a value was saved, I simply check if the object was allocated. Using a TUniquePtr<...> would be better but compilation fails because this class has a compiler generated copy operator and a unique ptr can't be copied. So using a TPimplPtr is equivalent to using a unique ptr but it can be deep copied and the compiler is happy.
Definition at line 224 of file PerQualityLevelProperties.h.
ScalabilitySection
template<typename _StructType, typename _ValueType, EName _BasePropertyName> FString FPerQualityLevelProperty< _StructType, _ValueType, _BasePropertyName >::ScalabilitySection
Definition at line 203 of file PerQualityLevelProperties.h.
Referenced by SetQualityLevelCVarForCooking().
The documentation for this struct was generated from the following file:
PerQualityLevelProperties.h