Unreal Engine 5.6 C++ API: FindInBlueprintsHelpers::FSimpleFTextKeyStorage Struct Reference
FindInBlueprintsHelpers::FSimpleFTextKeyStorage Struct Reference
#include "FindInBlueprints.h"
Public Member Functions
FSimpleFTextKeyStorage (FText InText)
bool operator== (const FSimpleFTextKeyStorage &InObject) const
Data Fields
FText Text
Detailed Description
Definition at line 63 of file FindInBlueprints.h.
Constructor & Destructor Documentation
FSimpleFTextKeyStorage()
FindInBlueprintsHelpers::FSimpleFTextKeyStorage::FSimpleFTextKeyStorage (FText InText) inline
Definition at line 67 of file FindInBlueprints.h.
References Text.
Referenced by operator==().
Member Function Documentation
operator==()
bool FindInBlueprintsHelpers::FSimpleFTextKeyStorage::operator== (const FSimpleFTextKeyStorage & InObject) const inline
Definition at line 73 of file FindInBlueprints.h.
References FSimpleFTextKeyStorage(), FText::BuildSourceString(), and Text.
Field Documentation
Text
FText FindInBlueprintsHelpers::FSimpleFTextKeyStorage::Text
Definition at line 65 of file FindInBlueprints.h.
Referenced by FSimpleFTextKeyStorage(), FindInBlueprintsHelpers::GetTypeHash(), and operator==().
The documentation for this struct was generated from the following file:
FindInBlueprints.h