Unreal Engine 5.6 C++ API: ITypedElementWorldInterface Class Reference
ITypedElementWorldInterface Class Reference
#include "TypedElementWorldInterface.h"
Protected Member Functions
virtual class UTypedElementRegistry & GetRegistry () const
Return the registry associated with this interface implementation.
Private Member Functions
virtual bool AddIgnoredElementToCollisionQueryParams (const FTypedElementHandle &InElementHandle, FCollisionQueryParams &InOutParams, bool bAlsoIgnoreSubElements=true)
Attempt to modify FCollisionQueryParams so that the given element (and optionally any attached sub-elements, if the element is part of a hierarchy) is ignored in the query.
virtual bool CanCopyElement (const FTypedElementHandle &InElementHandle)
virtual bool CanDeleteElement (const FTypedElementHandle &InElementHandle)
Can the given element be deleted?
virtual bool CanDuplicateElement (const FTypedElementHandle &InElementHandle)
Can the given element be duplicated?
virtual bool CanEditElement (const FTypedElementHandle &InElementHandle)
Can this element actually be edited in the world?
virtual bool CanMoveElement (const FTypedElementHandle &InElementHandle, const ETypedElementWorldType InWorldType)
Can the given element be moved within the world?
virtual bool CanPromoteElement (const FTypedElementHandle &InElementHandle)
Can the element be promoted Generally available when the element is lighter representation of another element.
virtual bool CanScaleElement (const FTypedElementHandle &InElementHandle)
Can the given element be scaled?
virtual void CopyElement (const FTypedElementHandle &InElementHandle, FOutputDevice &Out)
Copy the given element into a object to export.
virtual void CopyElements (TArrayView< const FTypedElementHandle > InElementHandles, FOutputDevice &Out)
Copy the given set of elements into a object to export.
virtual bool DeleteElement (const FTypedElementHandle &InElementHandle, UWorld *InWorld, UTypedElementSelectionSet *InSelectionSet, const FTypedElementDeletionOptions &InDeletionOptions)
Delete the given element.
virtual bool DeleteElements (TArrayView< const FTypedElementHandle > InElementHandles, UWorld *InWorld, UTypedElementSelectionSet *InSelectionSet, const FTypedElementDeletionOptions &InDeletionOptions)
Delete the given set of elements.
virtual FTypedElementHandle DuplicateElement (const FTypedElementHandle &InElementHandle, UWorld *InWorld, const FVector &InLocationOffset)
Duplicate the given element.
virtual void DuplicateElements (TArrayView< const FTypedElementHandle > InElementHandles, UWorld *InWorld, const FVector &InLocationOffset, TArray< FTypedElementHandle > &OutNewElements)
Duplicate the given set of elements.
virtual bool FindSuitableTransformAlongPath (const FTypedElementHandle &InElementHandle, const FVector &InPathStart, const FVector &InPathEnd, const FCollisionShape &InTestShape, TArrayView< const FTypedElementHandle > InElementsToIgnore, FTransform &OutSuitableTransform)
Attempt to find a suitable (non-intersecting) transform for the given element along the given path.
virtual bool FindSuitableTransformAtPoint (const FTypedElementHandle &InElementHandle, const FTransform &InPotentialTransform, FTransform &OutSuitableTransform)
Attempt to find a suitable (non-intersecting) transform for the given element at the given point.
GENERATED_BODY () public
Is this element considered a template within its world (eg, a CDO or archetype).
virtual bool GetBounds (const FTypedElementHandle &InElementHandle, FBoxSphereBounds &OutBounds)
Get the bounds of this element, if any.
virtual ULevel * GetOwnerLevel (const FTypedElementHandle &InElementHandle)
Get the owner level associated with this element, if any.
virtual UWorld * GetOwnerWorld (const FTypedElementHandle &InElementHandle)
Get the owner world associated with this element, if any.
virtual TSharedPtr< FWorldElementPasteImporter > GetPasteImporter ()
virtual bool GetPivotOffset (const FTypedElementHandle &InElementHandle, FVector &OutPivotOffset)
Get the local space offset of this element that should be added to its pivot location, if any.
virtual bool GetRelativeTransform (const FTypedElementHandle &InElementHandle, FTransform &OutTransform)
Get the transform of this element relative to its parent, if any.
virtual TArray< FTypedElementHandle > GetSelectionElementsFromSelectionFunction (const FTypedElementHandle &Handle, const FWorldSelectionElementArgs &SelectionArgs, const TFunction< bool(const FTypedElementHandle &, const FWorldSelectionElementArgs &)> &SelectionFunction)
TArray< FTypedElementHandle > GetSelectionElementsInBox (const FTypedElementHandle &Handle, const FBox &InBox, const FWorldSelectionElementArgs &SelectionArgs)
Get the selectable elements from this element that are inside the the convex volume.
TArray< FTypedElementHandle > GetSelectionElementsInConvexVolume (const FTypedElementHandle &Handle, const FConvexVolume &InVolume, const FWorldSelectionElementArgs &SelectionArgs)
Get the selectable elements from this element that are inside the the convex volume.
virtual bool GetWorldTransform (const FTypedElementHandle &InElementHandle, FTransform &OutTransform)
Get the transform of this element within its owner world, if any.
virtual bool IsElementInBox (const FTypedElementHandle &Handle, const FBox &InBox, bool bMustEncompassEntireElement=false)
Return true if the element is in the Box Note: This should only be use for editor tools since it doesn't use the physics system and the performance would probably be to slow for a runtime application.
virtual bool IsElementInConvexVolume (const FTypedElementHandle &Handle, const FConvexVolume &InVolume, bool bMustEncompassEntireElement=false)
Return true if the element is in the volume Note: This should only be use for editor tools since it doesn't use the physics system and the performance would probably be to slow for a runtime application.
virtual void NotifyMovementEnded (const FTypedElementHandle &InElementHandle)
Notify that this element is done being moved.
virtual void NotifyMovementOngoing (const FTypedElementHandle &InElementHandle)
Notify that this element is currently being moved.
virtual void NotifyMovementStarted (const FTypedElementHandle &InElementHandle)
Notify that this element is about to be moved.
virtual FTypedElementHandle PromoteElement (const FTypedElementHandle &InElementHandle, UWorld *OverrideWorld=nullptr)
Promote a element when possible Generally available when the element is lighter representation of another element.
virtual bool SetPivotOffset (const FTypedElementHandle &InElementHandle, const FVector &InPivotOffset)
Attempt to set the local space offset of this element that should be added to its pivot location.
virtual bool SetRelativeTransform (const FTypedElementHandle &InElementHandle, const FTransform &InTransform)
Attempt to set the transform of this element relative to its parent.
virtual bool SetWorldTransform (const FTypedElementHandle &InElementHandle, const FTransform &InTransform)
Attempt to set the transform of this element within its owner world.
UFUNCTION () 1 virtual bool CanDeleteElement(const FScriptTypedElementHandle &InElementHandle)
Can the given element be deleted?
UFUNCTION () 1 virtual bool CanDuplicateElement(const FScriptTypedElementHandle &InElementHandle)
Can the given element be duplicated?
UFUNCTION () 1 virtual bool CanEditElement(const FScriptTypedElementHandle &InElementHandle)
Can this element actually be edited in the world?
UFUNCTION () 1 virtual bool CanMoveElement(const FScriptTypedElementHandle &InElementHandle
Can the given element be moved within the world?
UFUNCTION () 1 virtual bool CanPromoteElement(const FScriptTypedElementHandle &InElementHandle)
Can the element be promoted Generally available when the element is a lighter representation of another element.
UFUNCTION () 1 virtual bool CanScaleElement(const FScriptTypedElementHandle &InElementHandle)
Can the given element be scaled?
UFUNCTION () 1 virtual bool DeleteElement(const FScriptTypedElementHandle &InElementHandle
Delete the given element.
UFUNCTION () 1 virtual bool GetBounds(const FScriptTypedElementHandle &InElementHandle
Get the bounds of this element, if any.
UFUNCTION () 1 virtual bool GetPivotOffset(const FScriptTypedElementHandle &InElementHandle
Get the local space offset of this element that should be added to its pivot location, if any.
UFUNCTION () 1 virtual bool GetRelativeTransform(const FScriptTypedElementHandle &InElementHandle
Get the transform of this element relative to its parent, if any.
UFUNCTION () 1 virtual bool GetWorldTransform(const FScriptTypedElementHandle &InElementHandle
Get the transform of this element within its owner world, if any.
UFUNCTION () 1 virtual bool IsTemplateElement(const FScriptTypedElementHandle &InElementHandle)
Script Api.
UFUNCTION () 1 virtual bool SetPivotOffset(const FScriptTypedElementHandle &InElementHandle
Attempt to set the local space offset of this element that should be added to its pivot location.
UFUNCTION () 1 virtual bool SetRelativeTransform(const FScriptTypedElementHandle &InElementHandle
Attempt to set the transform of this element relative to its parent.
UFUNCTION () 1 virtual bool SetWorldTransform(const FScriptTypedElementHandle &InElementHandle
Attempt to set the transform of this element within its owner world.
UFUNCTION () 1 virtual FScriptTypedElementHandle DuplicateElement(const FScriptTypedElementHandle &InElementHandle
Duplicate the given element.
UFUNCTION () 1 virtual FScriptTypedElementHandle PromoteElement(const FScriptTypedElementHandle &InElementHandle
Promote an element when possible Generally available when the element is a lighter representation of another element.
UFUNCTION () 1 virtual ULevel *GetOwnerLevel(const FScriptTypedElementHandle &InElementHandle)
Get the owner level associated with this element, if any.
UFUNCTION () 1 virtual UWorld *GetOwnerWorld(const FScriptTypedElementHandle &InElementHandle)
Get the owner world associated with this element, if any.
UFUNCTION () 1 virtual void NotifyMovementEnded(const FScriptTypedElementHandle &InElementHandle)
Notify that this element is done being moved.
UFUNCTION () 1 virtual void NotifyMovementOngoing(const FScriptTypedElementHandle &InElementHandle)
Notify that this element is currently being moved.
UFUNCTION () 1 virtual void NotifyMovementStarted(const FScriptTypedElementHandle &InElementHandle)
Notify that this element is about to be moved.
Private Attributes
UWorld UTypedElementSelectionSet const FTypedElementDeletionOptions & InDeletionOptions
UWorld const FVector & InLocationOffset
const FVector & InPivotOffset
UWorld UTypedElementSelectionSet * InSelectionSet
const FTransform & InTransform
UWorld * InWorld
const ETypedElementWorldType InWorldType
FBoxSphereBounds & OutBounds
FVector & OutPivotOffset
FTransform & OutTransform
UWorld * OverrideWorld = nullptr)
Detailed Description
Definition at line 79 of file TypedElementWorldInterface.h.
Member Function Documentation
AddIgnoredElementToCollisionQueryParams()
virtual bool ITypedElementWorldInterface::AddIgnoredElementToCollisionQueryParams (const FTypedElementHandle & InElementHandle, FCollisionQueryParams & InOutParams, bool bAlsoIgnoreSubElements = true) inline private virtual
Attempt to modify FCollisionQueryParams so that the given element (and optionally any attached sub-elements, if the element is part of a hierarchy) is ignored in the query.
For instance, this can be used to support dragging elements into the scene and raycasting for a target location without hitting the preview.
Returns
true if the collision query parameters were modified.
Definition at line 190 of file TypedElementWorldInterface.h.
CanCopyElement()
virtual bool ITypedElementWorldInterface::CanCopyElement (const FTypedElementHandle & InElementHandle) inline private virtual
Definition at line 240 of file TypedElementWorldInterface.h.
CanDeleteElement()
virtual bool ITypedElementWorldInterface::CanDeleteElement (const FTypedElementHandle & InElementHandle) inline private virtual
Can the given element be deleted?
Definition at line 199 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
CanDuplicateElement()
virtual bool ITypedElementWorldInterface::CanDuplicateElement (const FTypedElementHandle & InElementHandle) inline private virtual
Can the given element be duplicated?
Definition at line 219 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
CanEditElement()
virtual bool ITypedElementWorldInterface::CanEditElement (const FTypedElementHandle & InElementHandle) inline private virtual
Can this element actually be edited in the world?
Definition at line 92 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
CanMoveElement()
virtual bool ITypedElementWorldInterface::CanMoveElement (const FTypedElementHandle & InElementHandle, const ETypedElementWorldType InWorldType) inline private virtual
Can the given element be moved within the world?
Definition at line 112 of file TypedElementWorldInterface.h.
References InWorldType.
CanPromoteElement()
virtual bool ITypedElementWorldInterface::CanPromoteElement (const FTypedElementHandle & InElementHandle) inline private virtual
Can the element be promoted Generally available when the element is lighter representation of another element.
Like promoting a static mesh instance from an instanced static static component to a static actor for example.
Definition at line 270 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
CanScaleElement()
virtual bool ITypedElementWorldInterface::CanScaleElement (const FTypedElementHandle & InElementHandle) inline private virtual
Can the given element be scaled?
Definition at line 117 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
CopyElement()
virtual void ITypedElementWorldInterface::CopyElement (const FTypedElementHandle & InElementHandle, FOutputDevice & Out) inline private virtual
Copy the given element into a object to export.
Note
Default version calls CopyElements with a single element.
Definition at line 247 of file TypedElementWorldInterface.h.
References CopyElements(), and MakeArrayView().
CopyElements()
virtual void ITypedElementWorldInterface::CopyElements (TArrayView< const FTypedElementHandle > InElementHandles, FOutputDevice & Out) inline private virtual
Copy the given set of elements into a object to export.
Note
If you want to copy an array of elements that are potentially different types, you probably want to use the higher-level UTypedElementCommonActions::CopyNormalizedElements function instead.
Definition at line 256 of file TypedElementWorldInterface.h.
Referenced by CopyElement().
DeleteElement()
virtual bool ITypedElementWorldInterface::DeleteElement (const FTypedElementHandle & InElementHandle, UWorld * InWorld, UTypedElementSelectionSet * InSelectionSet, const FTypedElementDeletionOptions & InDeletionOptions) inline private virtual
Delete the given element.
Note
Default version calls DeleteElements with a single element.
Definition at line 205 of file TypedElementWorldInterface.h.
References DeleteElements(), InDeletionOptions, InSelectionSet, InWorld, and MakeArrayView().
DeleteElements()
virtual bool ITypedElementWorldInterface::DeleteElements (TArrayView< const FTypedElementHandle > InElementHandles, UWorld * InWorld, UTypedElementSelectionSet * InSelectionSet, const FTypedElementDeletionOptions & InDeletionOptions) inline private virtual
Delete the given set of elements.
Note
If you want to delete an array of elements that are potentially different types, you probably want to use the higher-level UTypedElementCommonActions::DeleteNormalizedElements function instead.
Definition at line 214 of file TypedElementWorldInterface.h.
References InDeletionOptions, InSelectionSet, and InWorld.
Referenced by DeleteElement().
DuplicateElement()
virtual FTypedElementHandle ITypedElementWorldInterface::DuplicateElement (const FTypedElementHandle & InElementHandle, UWorld * InWorld, const FVector & InLocationOffset) inline private virtual
Duplicate the given element.
Note
Default version calls DuplicateElements with a single element.
Definition at line 225 of file TypedElementWorldInterface.h.
References DuplicateElements(), FVector, InLocationOffset, InWorld, MakeArrayView(), MoveTemp(), and TArray< InElementType, InAllocatorType >::Num().
DuplicateElements()
virtual void ITypedElementWorldInterface::DuplicateElements (TArrayView< const FTypedElementHandle > InElementHandles, UWorld * InWorld, const FVector & InLocationOffset, TArray< FTypedElementHandle > & OutNewElements) inline private virtual
Duplicate the given set of elements.
Note
If you want to duplicate an array of elements that are potentially different types, you probably want to use the higher-level UTypedElementCommonActions::DuplicateNormalizedElements function instead.
Definition at line 236 of file TypedElementWorldInterface.h.
References FVector, InLocationOffset, and InWorld.
Referenced by DuplicateElement().
FindSuitableTransformAlongPath()
virtual bool ITypedElementWorldInterface::FindSuitableTransformAlongPath (const FTypedElementHandle & InElementHandle, const FVector & InPathStart, const FVector & InPathEnd, const FCollisionShape & InTestShape, TArrayView< const FTypedElementHandle > InElementsToIgnore, FTransform & OutSuitableTransform) inline private virtual
Attempt to find a suitable (non-intersecting) transform for the given element along the given path.
Definition at line 176 of file TypedElementWorldInterface.h.
References FVector.
FindSuitableTransformAtPoint()
virtual bool ITypedElementWorldInterface::FindSuitableTransformAtPoint (const FTypedElementHandle & InElementHandle, const FTransform & InPotentialTransform, FTransform & OutSuitableTransform) inline private virtual
Attempt to find a suitable (non-intersecting) transform for the given element at the given point.
Definition at line 167 of file TypedElementWorldInterface.h.
GENERATED_BODY()
ITypedElementWorldInterface::GENERATED_BODY () inline private
Is this element considered a template within its world (eg, a CDO or archetype).
Definition at line 81 of file TypedElementWorldInterface.h.
GetBounds()
virtual bool ITypedElementWorldInterface::GetBounds (const FTypedElementHandle & InElementHandle, FBoxSphereBounds & OutBounds) inline private virtual
Get the bounds of this element, if any.
Definition at line 107 of file TypedElementWorldInterface.h.
References OutBounds.
GetOwnerLevel()
virtual ULevel * ITypedElementWorldInterface::GetOwnerLevel (const FTypedElementHandle & InElementHandle) inline private virtual
Get the owner level associated with this element, if any.
Definition at line 97 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
GetOwnerWorld()
virtual UWorld * ITypedElementWorldInterface::GetOwnerWorld (const FTypedElementHandle & InElementHandle) inline private virtual
Get the owner world associated with this element, if any.
Definition at line 102 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
GetPasteImporter()
virtual TSharedPtr< FWorldElementPasteImporter > ITypedElementWorldInterface::GetPasteImporter () inline private virtual
Definition at line 260 of file TypedElementWorldInterface.h.
GetPivotOffset()
virtual bool ITypedElementWorldInterface::GetPivotOffset (const FTypedElementHandle & InElementHandle, FVector & OutPivotOffset) inline private virtual
Get the local space offset of this element that should be added to its pivot location, if any.
Definition at line 142 of file TypedElementWorldInterface.h.
References FVector, and OutPivotOffset.
GetRegistry()
virtual class UTypedElementRegistry & ITypedElementWorldInterface::GetRegistry () const protected virtual
Return the registry associated with this interface implementation.
References GetRegistry().
Referenced by GetRegistry().
GetRelativeTransform()
virtual bool ITypedElementWorldInterface::GetRelativeTransform (const FTypedElementHandle & InElementHandle, FTransform & OutTransform) inline private virtual
Get the transform of this element relative to its parent, if any.
Definition at line 132 of file TypedElementWorldInterface.h.
References GetWorldTransform(), and OutTransform.
Referenced by UFUNCTION().
GetSelectionElementsFromSelectionFunction()
virtual TArray< FTypedElementHandle > ITypedElementWorldInterface::GetSelectionElementsFromSelectionFunction (const FTypedElementHandle & Handle, const FWorldSelectionElementArgs & SelectionArgs, const TFunction< bool(const FTypedElementHandle &, const FWorldSelectionElementArgs &)> & SelectionFunction) private virtual
References Handle.
GetSelectionElementsInBox()
TArray< FTypedElementHandle > ITypedElementWorldInterface::GetSelectionElementsInBox (const FTypedElementHandle & Handle, const FBox & InBox, const FWorldSelectionElementArgs & SelectionArgs) private
Get the selectable elements from this element that are inside the the convex volume.
References Handle.
GetSelectionElementsInConvexVolume()
TArray< FTypedElementHandle > ITypedElementWorldInterface::GetSelectionElementsInConvexVolume (const FTypedElementHandle & Handle, const FConvexVolume & InVolume, const FWorldSelectionElementArgs & SelectionArgs) private
Get the selectable elements from this element that are inside the the convex volume.
References Handle.
GetWorldTransform()
virtual bool ITypedElementWorldInterface::GetWorldTransform (const FTypedElementHandle & InElementHandle, FTransform & OutTransform) inline private virtual
Get the transform of this element within its owner world, if any.
Definition at line 122 of file TypedElementWorldInterface.h.
References OutTransform.
Referenced by GetRelativeTransform().
IsElementInBox()
virtual bool ITypedElementWorldInterface::IsElementInBox (const FTypedElementHandle & Handle, const FBox & InBox, bool bMustEncompassEntireElement = false) private virtual
Return true if the element is in the Box Note: This should only be use for editor tools since it doesn't use the physics system and the performance would probably be to slow for a runtime application.
References Handle.
IsElementInConvexVolume()
virtual bool ITypedElementWorldInterface::IsElementInConvexVolume (const FTypedElementHandle & Handle, const FConvexVolume & InVolume, bool bMustEncompassEntireElement = false) private virtual
Return true if the element is in the volume Note: This should only be use for editor tools since it doesn't use the physics system and the performance would probably be to slow for a runtime application.
References Handle.
NotifyMovementEnded()
virtual void ITypedElementWorldInterface::NotifyMovementEnded (const FTypedElementHandle & InElementHandle) inline private virtual
Notify that this element is done being moved.
Definition at line 162 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
NotifyMovementOngoing()
virtual void ITypedElementWorldInterface::NotifyMovementOngoing (const FTypedElementHandle & InElementHandle) inline private virtual
Notify that this element is currently being moved.
Definition at line 157 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
NotifyMovementStarted()
virtual void ITypedElementWorldInterface::NotifyMovementStarted (const FTypedElementHandle & InElementHandle) inline private virtual
Notify that this element is about to be moved.
Definition at line 152 of file TypedElementWorldInterface.h.
Referenced by UFUNCTION().
PromoteElement()
virtual FTypedElementHandle ITypedElementWorldInterface::PromoteElement (const FTypedElementHandle & InElementHandle, UWorld * OverrideWorld = nullptr) inline private virtual
Promote a element when possible Generally available when the element is lighter representation of another element.
Like promoting a static mesh instance from an instanced static static component to a static actor for example.
Parameters
OverrideWorld Override the world in which the promotion might create new elements. Leave it to null to use the world from the handle.
Definition at line 282 of file TypedElementWorldInterface.h.
References OverrideWorld.
SetPivotOffset()
virtual bool ITypedElementWorldInterface::SetPivotOffset (const FTypedElementHandle & InElementHandle, const FVector & InPivotOffset) inline private virtual
Attempt to set the local space offset of this element that should be added to its pivot location.
Definition at line 147 of file TypedElementWorldInterface.h.
References FVector, and InPivotOffset.
SetRelativeTransform()
virtual bool ITypedElementWorldInterface::SetRelativeTransform (const FTypedElementHandle & InElementHandle, const FTransform & InTransform) inline private virtual
Attempt to set the transform of this element relative to its parent.
Definition at line 137 of file TypedElementWorldInterface.h.
References InTransform, and SetWorldTransform().
Referenced by UFUNCTION().
SetWorldTransform()
virtual bool ITypedElementWorldInterface::SetWorldTransform (const FTypedElementHandle & InElementHandle, const FTransform & InTransform) inline private virtual
Attempt to set the transform of this element within its owner world.
Definition at line 127 of file TypedElementWorldInterface.h.
References InTransform.
Referenced by SetRelativeTransform().
UFUNCTION() [1/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Can the given element be deleted?
References CanDeleteElement(), Category, and UFUNCTION().
UFUNCTION() [2/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Can the given element be duplicated?
References CanDuplicateElement(), Category, and UFUNCTION().
UFUNCTION() [3/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Can this element actually be edited in the world?
References CanEditElement(), Category, and UFUNCTION().
UFUNCTION() [4/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Can the given element be moved within the world?
References Category, and UFUNCTION().
UFUNCTION() [5/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Can the element be promoted Generally available when the element is a lighter representation of another element.
Like an instance for example.
References CanPromoteElement(), Category, and UFUNCTION().
UFUNCTION() [6/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Can the given element be scaled?
References CanScaleElement(), Category, and UFUNCTION().
UFUNCTION() [7/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Delete the given element.
Note
Default version calls DeleteElements with a single element.
References Category, and UFUNCTION().
UFUNCTION() [8/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Get the bounds of this element, if any.
References Category, and UFUNCTION().
UFUNCTION() [9/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Get the local space offset of this element that should be added to its pivot location, if any.
References Category, and UFUNCTION().
UFUNCTION() [10/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Get the transform of this element relative to its parent, if any.
References Category, GetRelativeTransform(), OutTransform, and UFUNCTION().
UFUNCTION() [11/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Get the transform of this element within its owner world, if any.
References Category, and UFUNCTION().
UFUNCTION() [12/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Script Api.
Is this element considered a template within its world (eg, a CDO or archetype).
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [13/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Attempt to set the local space offset of this element that should be added to its pivot location.
References Category, and UFUNCTION().
UFUNCTION() [14/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Attempt to set the transform of this element relative to its parent.
References Category, InTransform, SetRelativeTransform(), and UFUNCTION().
UFUNCTION() [15/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Attempt to set the transform of this element within its owner world.
References Category, and UFUNCTION().
UFUNCTION() [16/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Duplicate the given element.
Note
Default version calls DuplicateElements with a single element.
References Category, and UFUNCTION().
UFUNCTION() [17/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Promote an element when possible Generally available when the element is a lighter representation of another element.
Like an instance for example.
Parameters
OverrideWorld Override the world in which the promotion might create new elements. Leave it to null to use the world from the handle.
References Category, and UFUNCTION().
UFUNCTION() [18/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Get the owner level associated with this element, if any.
References Category, GetOwnerLevel(), and UFUNCTION().
UFUNCTION() [19/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Get the owner world associated with this element, if any.
References Category, GetOwnerWorld(), and UFUNCTION().
UFUNCTION() [20/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Notify that this element is done being moved.
References Category, NotifyMovementEnded(), and UFUNCTION().
UFUNCTION() [21/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Notify that this element is currently being moved.
References Category, NotifyMovementOngoing(), and UFUNCTION().
UFUNCTION() [22/22]
ITypedElementWorldInterface::UFUNCTION () const & private
Notify that this element is about to be moved.
References Category, NotifyMovementStarted(), and UFUNCTION().
Field Documentation
InDeletionOptions
UWorld UTypedElementSelectionSet const FTypedElementDeletionOptions& ITypedElementWorldInterface::InDeletionOptions private
Definition at line 427 of file TypedElementWorldInterface.h.
Referenced by DeleteElement(), TTypedElement< ITypedElementWorldInterface >::DeleteElement(), and DeleteElements().
InLocationOffset
UWorld const FVector& ITypedElementWorldInterface::InLocationOffset private
Definition at line 440 of file TypedElementWorldInterface.h.
Referenced by DuplicateElement(), TTypedElement< ITypedElementWorldInterface >::DuplicateElement(), and DuplicateElements().
InPivotOffset
const FVector& ITypedElementWorldInterface::InPivotOffset private
Definition at line 396 of file TypedElementWorldInterface.h.
Referenced by SetPivotOffset(), and TTypedElement< ITypedElementWorldInterface >::SetPivotOffset().
InSelectionSet
UWorld UTypedElementSelectionSet* ITypedElementWorldInterface::InSelectionSet private
Definition at line 427 of file TypedElementWorldInterface.h.
Referenced by DeleteElement(), TTypedElement< ITypedElementWorldInterface >::DeleteElement(), and DeleteElements().
InTransform
const FTransform & ITypedElementWorldInterface::InTransform private
Definition at line 372 of file TypedElementWorldInterface.h.
Referenced by SetRelativeTransform(), TTypedElement< ITypedElementWorldInterface >::SetRelativeTransform(), SetWorldTransform(), TTypedElement< ITypedElementWorldInterface >::SetWorldTransform(), and UFUNCTION().
InWorld
UWorld * ITypedElementWorldInterface::InWorld private
Definition at line 427 of file TypedElementWorldInterface.h.
Referenced by DeleteElement(), TTypedElement< ITypedElementWorldInterface >::DeleteElement(), DeleteElements(), DuplicateElement(), TTypedElement< ITypedElementWorldInterface >::DuplicateElement(), and DuplicateElements().
InWorldType
const ETypedElementWorldType ITypedElementWorldInterface::InWorldType private
Definition at line 354 of file TypedElementWorldInterface.h.
Referenced by CanMoveElement(), and TTypedElement< ITypedElementWorldInterface >::CanMoveElement().
OutBounds
FBoxSphereBounds& ITypedElementWorldInterface::OutBounds private
Definition at line 348 of file TypedElementWorldInterface.h.
Referenced by GetBounds(), and TTypedElement< ITypedElementWorldInterface >::GetBounds().
OutPivotOffset
FVector& ITypedElementWorldInterface::OutPivotOffset private
Definition at line 390 of file TypedElementWorldInterface.h.
Referenced by GetPivotOffset(), and TTypedElement< ITypedElementWorldInterface >::GetPivotOffset().
OutTransform
FTransform & ITypedElementWorldInterface::OutTransform private
Definition at line 366 of file TypedElementWorldInterface.h.
Referenced by GetRelativeTransform(), TTypedElement< ITypedElementWorldInterface >::GetRelativeTransform(), GetWorldTransform(), TTypedElement< ITypedElementWorldInterface >::GetWorldTransform(), and UFUNCTION().
OverrideWorld
UWorld* ITypedElementWorldInterface::OverrideWorld = nullptr) private
Definition at line 458 of file TypedElementWorldInterface.h.
Referenced by PromoteElement(), and TTypedElement< ITypedElementWorldInterface >::PromoteElement().
The documentation for this class was generated from the following file:
TypedElementWorldInterface.h