Unreal Engine 5.6 C++ API: FEditorBuildUtils Class Reference
FEditorBuildUtils Class Reference
Utility class to hold functionality for building within the editor.
#include "EditorBuildUtils.h"
Data Structures
struct FCustomBuildType
Struct containing data for a custom build type.
struct FEditorAutomatedBuildSettings
Helper struct to specify settings for an automated editor build.
Public Types
enum EAutomatedBuildBehavior { ABB_PromptOnError , ABB_FailOnError , ABB_ProceedOnError }
Enumeration representing automated build behavior in the event of an error.
Static Public Member Functions
static UNREALED_API void AsyncBuildCompleted ()
Call this when an async custom build step has completed (successfully or not).
static UNREALED_API bool EditorAutomatedBuildAndSubmit (const FEditorAutomatedBuildSettings &BuildSettings, FText &OutErrorMessages)
Start an automated build of all current maps in the editor.
static UNREALED_API bool EditorBuild (UWorld *InWorld, FName Id, const bool bAllowLightingDialog=true)
Perform an editor build with behavior dependent upon the specified id.
static UNREALED_API void EditorBuildAllLandscape (UWorld *InWorld)
Perform an editor build for All Landscape Data.
static UNREALED_API bool EditorBuildMaterialTextureStreamingData (UPackage *Package)
Similar to EditorBuildTextureStreaming, but attempts to rebuild TextureStreamingData for all materials in loaded package(s).
static UNREALED_API bool EditorBuildTextureStreaming (UWorld *InWorld, EViewModeIndex SelectedViewMode=VMI_Unknown)
Perform an editor build for texture streaming.
static UNREALED_API bool EditorBuildVirtualTexture (UWorld *InWorld)
Perform an editor build for virtual textures.
static UNREALED_API bool EditorCanBuild (UWorld *InWorld, FName Id)
Validate if the editor build matching the specified id can be executed.
static UNREALED_API void GetBuildTypes (TArray< FName > &RegisteredBuildTypes)
Fills RegisteredBuildTypes with the names of all build types registered by 'RegisterCustomBuildType'.
static UNREALED_API void GetBuildTypesLocalizedLabels (TArray< FText > &RegisteredBuildTypesEntryLabels, TArray< FText > &RegisteredBuildTypesSectionLabels)
Fills provided arrays with localized menu entry and section labels.
static UNREALED_API bool IsBuildCurrentlyRunning ()
Is there currently an (async) build in progress?
static bool IsBuildingNavigationFromUserRequest ()
check if navigation build was was triggered from editor as user request
static void PathBuildingFinished ()
call it to notify that navigation builder finished building
static UNREALED_API void RegisterCustomBuildType (const FName Id, const FCanDoEditorBuildDelegate &CanDoBuild, const FDoEditorBuildDelegate &DoBuild, const FName BuildAllExtensionPoint, const FText &MenuEntryLabel=FText::GetEmpty(), const FText &MenuSectionLabel=FText::GetEmpty(), bool bExternalProcess=false)
Register a custom build type.
static UNREALED_API void RegisterCustomBuildType (const FName Id, const FDoEditorBuildDelegate &DoBuild, const FName BuildAllExtensionPoint, const FText &MenuEntryLabel=FText::GetEmpty(), const FText &MenuSectionLabel=FText::GetEmpty(), bool bExternalProcess=false)
Register a custom build type.
static UNREALED_API bool RunWorldPartitionBuilder (const FString &MapToLoad, const FText &ProgressText, const FText &CancelledText, const FText &FailureText, const FString &CommandLineArguments)
Runs another instance of the current executable with the provided command line arguments.
static UNREALED_API void UnregisterCustomBuildType (FName Id)
Unregister a custom build type.
static UNREALED_API void UpdateTextureStreamingMaterialBindings (UWorld *InWorld)
Update every used material texture binding (see FMaterialTextureInfo::TextureIndex)
Private Member Functions
FEditorBuildUtils ()
Intentionally hide constructors, etc.
FEditorBuildUtils (const FEditorBuildUtils &)
~FEditorBuildUtils ()
FEditorBuildUtils operator= (const FEditorBuildUtils &)
Static Private Member Functions
static void LogErrorMessage (const FText &InErrorMessage, FText &OutAccumulatedErrors)
Private helper method to log an error both to GWarn and to the build's list of accumulated errors.
static bool PrepForAutomatedBuild (const FEditorAutomatedBuildSettings &BuildSettings, TSet< UPackage * > &OutPkgsToSubmit, FText &OutErrorMessages)
Helper method designed to perform the necessary preparations required to complete an automated editor build.
static bool ProcessAutomatedBuildBehavior (EAutomatedBuildBehavior InBehavior, const FText &InErrorMsg, FText &OutAccumulatedErrors)
Helper method to handle automated build behavior in the event of an error.
static void SubmitPackagesForAutomatedBuild (const TSet< UPackage * > &InPkgsToSubmit, const FEditorAutomatedBuildSettings &BuildSettings)
Helper method to submit packages to source control as part of the automated build process.
static void TriggerHierarchicalLODBuilder (UWorld *InWorld)
Trigger HLOD builder to (re)generate HLOD actors.
static void TriggerLandscapeSplineMeshesBuilder (UWorld *InWorld)
Trigger LandscapeSplineMeshes builder to (re)generate landscape spline meshes actors.
static void TriggerMinimapBuilder (UWorld *InWorld)
Trigger minimap builder to (re)generate minimap.
static void TriggerNavigationBuilder (UWorld *&InOutWorld, FName Id)
Trigger navigation builder to (re)generate NavMesh.
static bool WorldPartitionBuildNavigation (const FString &InLongPackageName)
Static Private Attributes
static bool bBuildingNavigationFromUserRequest
static variable to cache data about user request.
static TMap< FName, FCustomBuildType > CustomBuildTypes
Map of custom build types registered with us.
static FName InProgressBuildId
Set to a valid build type if an async build is in progress.
Friends
class FBuildAllHandler
Detailed Description
Utility class to hold functionality for building within the editor.
Definition at line 73 of file EditorBuildUtils.h.
Member Enumeration Documentation
EAutomatedBuildBehavior
enum FEditorBuildUtils::EAutomatedBuildBehavior
Enumeration representing automated build behavior in the event of an error.
Enumerator
ABB_PromptOnError
ABB_FailOnError
ABB_ProceedOnError
Definition at line 77 of file EditorBuildUtils.h.
Constructor & Destructor Documentation
FEditorBuildUtils() [1/2]
FEditorBuildUtils::FEditorBuildUtils () private
Intentionally hide constructors, etc.
to prevent instantiation
Referenced by FEditorBuildUtils(), and operator=().
~FEditorBuildUtils()
FEditorBuildUtils::~FEditorBuildUtils () private
FEditorBuildUtils() [2/2]
FEditorBuildUtils::FEditorBuildUtils (const FEditorBuildUtils &) private
References FEditorBuildUtils().
Member Function Documentation
AsyncBuildCompleted()
UNREALED_API void FEditorBuildUtils::AsyncBuildCompleted () static
Call this when an async custom build step has completed (successfully or not).
EditorAutomatedBuildAndSubmit()
UNREALED_API bool FEditorBuildUtils::EditorAutomatedBuildAndSubmit (const FEditorAutomatedBuildSettings & BuildSettings, FText & OutErrorMessages) static
Start an automated build of all current maps in the editor.
Upon successful conclusion of the build, the newly built maps will be submitted to source control.
Parameters
BuildSettings Build settings used to dictate the behavior of the automated build
OutErrorMessages Error messages accumulated during the build process, if any
Returns
true if the build/submission process executed successfully; false if it did not
EditorBuild()
UNREALED_API bool FEditorBuildUtils::EditorBuild (UWorld * InWorld, FName Id, const bool bAllowLightingDialog = true) static
Perform an editor build with behavior dependent upon the specified id.
Parameters
InWorld WorldContext
Id Action Id specifying what kind of build is requested
bAllowLightingDialog True if the build lighting dialog should be displayed if we're building lighting only
Returns
true if the build completed successfully; false if it did not (or was manually canceled)
EditorBuildAllLandscape()
UNREALED_API void FEditorBuildUtils::EditorBuildAllLandscape (UWorld * InWorld) static
Perform an editor build for All Landscape Data.
Parameters
InWorld WorldContext
EditorBuildMaterialTextureStreamingData()
UNREALED_API bool FEditorBuildUtils::EditorBuildMaterialTextureStreamingData (UPackage * Package) static
Similar to EditorBuildTextureStreaming, but attempts to rebuild TextureStreamingData for all materials in loaded package(s).
Parameters
Package If non-NULL, only looks at materials under the specified package.
Returns
true if any packages were dirtied in the process.
References Package.
EditorBuildTextureStreaming()
UNREALED_API bool FEditorBuildUtils::EditorBuildTextureStreaming (UWorld * InWorld, EViewModeIndex SelectedViewMode = VMI_Unknown) static
Perform an editor build for texture streaming.
Parameters
InWorld WorldContext
SelectedViewMode The viewmode to build the data for. Unkown when running the full build.
Returns
true if the build completed successfully; false if it did not (or was manually canceled)
EditorBuildVirtualTexture()
UNREALED_API bool FEditorBuildUtils::EditorBuildVirtualTexture (UWorld * InWorld) static
Perform an editor build for virtual textures.
Parameters
InWorld WorldContext
Returns
true if the build completed successfully; false if it did not (or was manually canceled)
EditorCanBuild()
UNREALED_API bool FEditorBuildUtils::EditorCanBuild (UWorld * InWorld, FName Id) static
Validate if the editor build matching the specified id can be executed.
Parameters
InWorld WorldContext
Id Action Id specifying what kind of build is requested
Returns
true if the build can be executed for the provided world
GetBuildTypes()
UNREALED_API void FEditorBuildUtils::GetBuildTypes (TArray< FName > & RegisteredBuildTypes) static
Fills RegisteredBuildTypes with the names of all build types registered by 'RegisterCustomBuildType'.
Parameters
RegisteredBuildTypes Names of all registered build types.
GetBuildTypesLocalizedLabels()
UNREALED_API void FEditorBuildUtils::GetBuildTypesLocalizedLabels (TArray< FText > & RegisteredBuildTypesEntryLabels, TArray< FText > & RegisteredBuildTypesSectionLabels) static
Fills provided arrays with localized menu entry and section labels.
Parameters
RegisteredBuildTypesEntryLabels Labels for each registered build types. Can be empty.
RegisteredBuildTypesSectionLabels Labels for each registered build types section where the entry should reside. Can be empty.
IsBuildCurrentlyRunning()
UNREALED_API bool FEditorBuildUtils::IsBuildCurrentlyRunning () static
Is there currently an (async) build in progress?
IsBuildingNavigationFromUserRequest()
bool FEditorBuildUtils::IsBuildingNavigationFromUserRequest () inline static
check if navigation build was was triggered from editor as user request
Returns
true if the build was triggered as user request; false if it did not
Definition at line 198 of file EditorBuildUtils.h.
References bBuildingNavigationFromUserRequest.
LogErrorMessage()
void FEditorBuildUtils::LogErrorMessage (const FText & InErrorMessage, FText & OutAccumulatedErrors) static private
Private helper method to log an error both to GWarn and to the build's list of accumulated errors.
Parameters
InErrorMessage Message to log to GWarn/add to list of errors
OutAccumulatedErrors List of errors accumulated during a build process so far
operator=()
FEditorBuildUtils FEditorBuildUtils::operator= (const FEditorBuildUtils &) private
References FEditorBuildUtils().
PathBuildingFinished()
void FEditorBuildUtils::PathBuildingFinished () inline static
call it to notify that navigation builder finished building
Definition at line 203 of file EditorBuildUtils.h.
References bBuildingNavigationFromUserRequest.
PrepForAutomatedBuild()
bool FEditorBuildUtils::PrepForAutomatedBuild (const FEditorAutomatedBuildSettings & BuildSettings, TSet< UPackage * > & OutPkgsToSubmit, FText & OutErrorMessages) static private
Helper method designed to perform the necessary preparations required to complete an automated editor build.
Parameters
BuildSettings Build settings that will be used for the editor build
OutPkgsToSubmit Set of packages that need to be saved and submitted after a successful build
OutErrorMessages Errors that resulted from the preparation (may or may not force the build to stop, depending on build settings)
Returns
true if the preparation was successful and the build should continue; false if the preparation failed and the build should be aborted
ProcessAutomatedBuildBehavior()
bool FEditorBuildUtils::ProcessAutomatedBuildBehavior (EAutomatedBuildBehavior InBehavior, const FText & InErrorMsg, FText & OutAccumulatedErrors) static private
Helper method to handle automated build behavior in the event of an error.
Depending on the specified behavior, one of three results are possible: a) User is prompted on whether to proceed with the automated build or not, b) The error is regarded as a build-stopper and the method returns failure, or c) The error is acknowledged but not regarded as a build-stopper, and the method returns success. In any event, the error is logged for the user's information.
Parameters
InBehavior Behavior to use to respond to the error
InErrorMsg Error to log
OutAccumulatedErrors List of errors accumulated from the build process so far; InErrorMsg will be added to the list
Returns
true if the build should proceed after processing the error behavior; false if it should not
RegisterCustomBuildType() [1/2]
UNREALED_API void FEditorBuildUtils::RegisterCustomBuildType (const FName Id, const FCanDoEditorBuildDelegate & CanDoBuild, const FDoEditorBuildDelegate & DoBuild, const FName BuildAllExtensionPoint, const FText & MenuEntryLabel = FText::GetEmpty(), const FText & MenuSectionLabel = FText::GetEmpty(), bool bExternalProcess = false) static
Register a custom build type.
Parameters
Id The identifier to use for this build type.
CanDoBuild The delegate to validate if a given build could be executed.
DoBuild The delegate to execute to run this build.
BuildAllExtensionPoint If a valid name, run this build before running the build with this id when performing a Build All.
MenuEntryLabel If non empty, will be used as label for the command in the menu. Otherwise Build {FText::FromName(Id)} will be used.
MenuSectionLabel If non empty, will be used a label for a new submenu for this build type. Otherwise the entry will be created under External Types.
bExternalProcess If build spawns an external process.
References FText::GetEmpty().
RegisterCustomBuildType() [2/2]
UNREALED_API void FEditorBuildUtils::RegisterCustomBuildType (const FName Id, const FDoEditorBuildDelegate & DoBuild, const FName BuildAllExtensionPoint, const FText & MenuEntryLabel = FText::GetEmpty(), const FText & MenuSectionLabel = FText::GetEmpty(), bool bExternalProcess = false) static
Register a custom build type.
Parameters
Id The identifier to use for this build type.
DoBuild The delegate to execute to run this build.
BuildAllExtensionPoint If a valid name, run this build before running the build with this id when performing a Build All.
MenuEntryLabel If non empty, will be used as label for the command in the menu. Otherwise Build {FText::FromName(Id)} will be used.
MenuSectionLabel If non empty, will be used a label for a new submenu for this build type. Otherwise the entry will be created under External Types.
bExternalProcess If build spawns an external process.
References FText::GetEmpty().
RunWorldPartitionBuilder()
UNREALED_API bool FEditorBuildUtils::RunWorldPartitionBuilder (const FString & MapToLoad, const FText & ProgressText, const FText & CancelledText, const FText & FailureText, const FString & CommandLineArguments) static
Runs another instance of the current executable with the provided command line arguments.
On success the current level will be unloaded. Using MapToLoad allows to reload that specific level to reflect the changes.
Parameters
MapToLoad Map to load after successfully run the process
ProgressText Message used by the progress dialog
CancelledText Message shown to the user after cancelling the task
FailureText Message shown to the user if the process returned an error code
CommandLineArguments Arguments passed to the other instance commandline
Returns
True if process completed without returning any error code.
SubmitPackagesForAutomatedBuild()
void FEditorBuildUtils::SubmitPackagesForAutomatedBuild (const TSet< UPackage * > & InPkgsToSubmit, const FEditorAutomatedBuildSettings & BuildSettings) static private
Helper method to submit packages to source control as part of the automated build process.
Parameters
InPkgsToSubmit Set of packages which should be submitted to source control
BuildSettings Build settings used during the automated build
TriggerHierarchicalLODBuilder()
void FEditorBuildUtils::TriggerHierarchicalLODBuilder (UWorld * InWorld) static private
Trigger HLOD builder to (re)generate HLOD actors.
Parameters
InWorld WorldContext
TriggerLandscapeSplineMeshesBuilder()
void FEditorBuildUtils::TriggerLandscapeSplineMeshesBuilder (UWorld * InWorld) static private
Trigger LandscapeSplineMeshes builder to (re)generate landscape spline meshes actors.
Parameters
InWorld WorldContext
TriggerMinimapBuilder()
void FEditorBuildUtils::TriggerMinimapBuilder (UWorld * InWorld) static private
Trigger minimap builder to (re)generate minimap.
Parameters
InWorld WorldContext
TriggerNavigationBuilder()
void FEditorBuildUtils::TriggerNavigationBuilder (UWorld *& InOutWorld, FName Id) static private
Trigger navigation builder to (re)generate NavMesh.
Parameters
InOutWorld WorldContext
Id Build options requested
UnregisterCustomBuildType()
UNREALED_API void FEditorBuildUtils::UnregisterCustomBuildType (FName Id) static
Unregister a custom build type.
Parameters
Id The identifier of the build type to unregister.
UpdateTextureStreamingMaterialBindings()
UNREALED_API void FEditorBuildUtils::UpdateTextureStreamingMaterialBindings (UWorld * InWorld) static
Update every used material texture binding (see FMaterialTextureInfo::TextureIndex)
Parameters
InWorld WorldContext
WorldPartitionBuildNavigation()
bool FEditorBuildUtils::WorldPartitionBuildNavigation (const FString & InLongPackageName) static private
Friends And Related Symbol Documentation
FBuildAllHandler
friend class FBuildAllHandler friend
Definition at line 373 of file EditorBuildUtils.h.
References FBuildAllHandler.
Referenced by FBuildAllHandler.
Field Documentation
bBuildingNavigationFromUserRequest
bool FEditorBuildUtils::bBuildingNavigationFromUserRequest static private
static variable to cache data about user request.
navigation builder works in a background and we have to cache this information
Definition at line 376 of file EditorBuildUtils.h.
Referenced by IsBuildingNavigationFromUserRequest(), and PathBuildingFinished().
CustomBuildTypes
TMap<FName, FCustomBuildType> FEditorBuildUtils::CustomBuildTypes static private
Map of custom build types registered with us.
Definition at line 417 of file EditorBuildUtils.h.
InProgressBuildId
FName FEditorBuildUtils::InProgressBuildId static private
Set to a valid build type if an async build is in progress.
Definition at line 420 of file EditorBuildUtils.h.
The documentation for this class was generated from the following file:
EditorBuildUtils.h