Unreal Engine 5.6 C++ API: FEmbeddedKeepAwake Class Reference
FEmbeddedKeepAwake Class Reference
#include "EmbeddedCommunication.h"
Public Member Functions
FEmbeddedKeepAwake (const FEmbeddedKeepAwake &Other)
FEmbeddedKeepAwake (FEmbeddedKeepAwake &&Other)
FEmbeddedKeepAwake (FName InRequester, bool bInNeedsRendering)
~FEmbeddedKeepAwake ()
bool GetNeedsRendering () const
FName GetRequester () const
FEmbeddedKeepAwake & operator= (const FEmbeddedKeepAwake &Other) &
FEmbeddedKeepAwake & operator= (FEmbeddedKeepAwake &&Other) &
Private Attributes
bool bIsValid = true
bool bNeedsRendering = false
FName Requester
Detailed Description
Definition at line 110 of file EmbeddedCommunication.h.
Constructor & Destructor Documentation
FEmbeddedKeepAwake() [1/3]
FEmbeddedKeepAwake::FEmbeddedKeepAwake (FName InRequester, bool bInNeedsRendering) inline
Definition at line 115 of file EmbeddedCommunication.h.
References bNeedsRendering, FEmbeddedCommunication::KeepAwake(), and Requester.
Referenced by FEmbeddedKeepAwake(), FEmbeddedKeepAwake(), operator=(), and operator=().
FEmbeddedKeepAwake() [2/3]
FEmbeddedKeepAwake::FEmbeddedKeepAwake (const FEmbeddedKeepAwake & Other) inline
Definition at line 122 of file EmbeddedCommunication.h.
References FEmbeddedKeepAwake(), bIsValid, bNeedsRendering, FEmbeddedCommunication::KeepAwake(), Other, and Requester.
FEmbeddedKeepAwake() [3/3]
FEmbeddedKeepAwake::FEmbeddedKeepAwake (FEmbeddedKeepAwake && Other) inline
Definition at line 133 of file EmbeddedCommunication.h.
References FEmbeddedKeepAwake(), bIsValid, bNeedsRendering, Other, and Requester.
~FEmbeddedKeepAwake()
FEmbeddedKeepAwake::~FEmbeddedKeepAwake () inline
Definition at line 144 of file EmbeddedCommunication.h.
References FEmbeddedCommunication::AllowSleep(), bIsValid, and Requester.
Member Function Documentation
GetNeedsRendering()
bool FEmbeddedKeepAwake::GetNeedsRendering () const inline
Definition at line 190 of file EmbeddedCommunication.h.
References bNeedsRendering.
GetRequester()
FName FEmbeddedKeepAwake::GetRequester () const inline
Definition at line 191 of file EmbeddedCommunication.h.
References Requester.
operator=() [1/2]
FEmbeddedKeepAwake & FEmbeddedKeepAwake::operator= (const FEmbeddedKeepAwake & Other) & inline
Definition at line 152 of file EmbeddedCommunication.h.
References FEmbeddedKeepAwake(), FEmbeddedCommunication::AllowSleep(), bIsValid, bNeedsRendering, FEmbeddedCommunication::KeepAwake(), Other, and Requester.
operator=() [2/2]
FEmbeddedKeepAwake & FEmbeddedKeepAwake::operator= (FEmbeddedKeepAwake && Other) & inline
Definition at line 173 of file EmbeddedCommunication.h.
References FEmbeddedKeepAwake(), FEmbeddedCommunication::AllowSleep(), bIsValid, bNeedsRendering, Other, and Requester.
Field Documentation
bIsValid
bool FEmbeddedKeepAwake::bIsValid = true private
Definition at line 196 of file EmbeddedCommunication.h.
Referenced by FEmbeddedKeepAwake(), FEmbeddedKeepAwake(), ~FEmbeddedKeepAwake(), operator=(), and operator=().
bNeedsRendering
bool FEmbeddedKeepAwake::bNeedsRendering = false private
Definition at line 195 of file EmbeddedCommunication.h.
Referenced by FEmbeddedKeepAwake(), FEmbeddedKeepAwake(), FEmbeddedKeepAwake(), GetNeedsRendering(), operator=(), and operator=().
Requester
FName FEmbeddedKeepAwake::Requester private
Definition at line 194 of file EmbeddedCommunication.h.
Referenced by FEmbeddedKeepAwake(), FEmbeddedKeepAwake(), FEmbeddedKeepAwake(), ~FEmbeddedKeepAwake(), GetRequester(), operator=(), and operator=().
The documentation for this class was generated from the following file:
EmbeddedCommunication.h