Unreal Engine 5.6 C++ API: FInputDeviceTriggerResistanceProperty Struct Reference
FInputDeviceTriggerResistanceProperty Struct Reference
A generic trigger effect that allows analog triggers to have a resistance curve between two points (Start and End)
#include "IInputInterface.h"
Public Member Functions
FInputDeviceTriggerResistanceProperty ()
Public Member Functions inherited from FInputDeviceTriggerProperty
FInputDeviceTriggerProperty (FName InName)
Static Public Member Functions
static FName PropertyName ()
Data Fields
int32 EndPosition = 0
The position that the trigger should start providing resistance.
int32 EndStrengh = 0
How strong the resistance is.
int32 StartPosition = 0
The position that the trigger should start providing resistance.
int32 StartStrengh = 0
How strong the resistance is.
Data Fields inherited from FInputDeviceTriggerProperty
EInputDeviceTriggerMask AffectedTriggers = EInputDeviceTriggerMask::None
Which trigger this property should effect.
Detailed Description
A generic trigger effect that allows analog triggers to have a resistance curve between two points (Start and End)
Definition at line 206 of file IInputInterface.h.
Constructor & Destructor Documentation
FInputDeviceTriggerResistanceProperty()
FInputDeviceTriggerResistanceProperty::FInputDeviceTriggerResistanceProperty () inline
Definition at line 208 of file IInputInterface.h.
References FInputDeviceTriggerProperty::FInputDeviceTriggerProperty(), and PropertyName().
Member Function Documentation
PropertyName()
FName FInputDeviceTriggerResistanceProperty::PropertyName () inline static
Definition at line 212 of file IInputInterface.h.
References FName.
Referenced by FInputDeviceTriggerResistanceProperty().
Field Documentation
EndPosition
int32 FInputDeviceTriggerResistanceProperty::EndPosition = 0
The position that the trigger should start providing resistance.
Definition at line 221 of file IInputInterface.h.
EndStrengh
int32 FInputDeviceTriggerResistanceProperty::EndStrengh = 0
How strong the resistance is.
Definition at line 224 of file IInputInterface.h.
StartPosition
int32 FInputDeviceTriggerResistanceProperty::StartPosition = 0
The position that the trigger should start providing resistance.
Definition at line 215 of file IInputInterface.h.
StartStrengh
int32 FInputDeviceTriggerResistanceProperty::StartStrengh = 0
How strong the resistance is.
Definition at line 218 of file IInputInterface.h.
The documentation for this struct was generated from the following file:
IInputInterface.h