Unreal Engine 5.6 C++ API: Metasound::TInputConstructorVertex< DataType > Class Template Reference
Metasound::TInputConstructorVertex< DataType > Class Template Reference
Create a FInputDataVertex with a templated MetaSound data type which only reads data at operator time.
#include "MetasoundVertex.h"
Public Member Functions
TInputConstructorVertex ()=default
template<typename... ArgTypes>
TInputConstructorVertex (const FVertexName &InVertexName, const FDataVertexMetadata &InMetadata, ArgTypes &&... Args)
Public Member Functions inherited from Metasound::FInputDataVertex
FInputDataVertex ()=default
FInputDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType, const FLiteral &InLiteral)
template<typename LiteralValueType>
FInputDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType, const LiteralValueType &InLiteralValue)
Construct an FInputDataVertex with a default literal.
FInputDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType=EVertexAccessType::Reference)
Construct an FInputDataVertex.
FLiteral GetDefaultLiteral () const
Returns the default literal associated with this input.
void SetDefaultLiteral (const FLiteral &InLiteral)
Set the default literal for this vertex.
Public Member Functions inherited from Metasound::FDataVertex
FDataVertex ()=default
FDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType)
FDataVertex Constructor.
virtual ~FDataVertex ()=default
Additional Inherited Members
Data Fields inherited from Metasound::FDataVertex
EVertexAccessType AccessType
Access type of the vertex.
FName DataTypeName
Type name of data.
FVertexName VertexName
Name of vertex.
Detailed Description
template<typename DataType>
class Metasound::TInputConstructorVertex< DataType >
Create a FInputDataVertex with a templated MetaSound data type which only reads data at operator time.
Definition at line 200 of file MetasoundVertex.h.
Constructor & Destructor Documentation
TInputConstructorVertex() [1/2]
template<typename DataType> Metasound::TInputConstructorVertex< DataType >::TInputConstructorVertex () default
TInputConstructorVertex() [2/2]
template<typename DataType> template<typename... ArgTypes> Metasound::TInputConstructorVertex< DataType >::TInputConstructorVertex (const FVertexName & InVertexName, const FDataVertexMetadata & InMetadata, ArgTypes &&... Args) inline
Definition at line 206 of file MetasoundVertex.h.
References Metasound::FInputDataVertex::FInputDataVertex(), Forward(), Metasound::GetMetasoundDataTypeName(), and Metasound::Value.
The documentation for this class was generated from the following file:
MetasoundVertex.h