Unreal Engine 5.6 C++ API: TKeyFrameManipulator< TimeType > Class Template Reference
TKeyFrameManipulator< TimeType > Class Template Reference
Templated key frame manipulator that knows how to add, remove and (re)arrange key times.
#include "KeyFrameManipulator.h"
Public Types
typedef TCallTraits< TimeType >::ParamType TimeTypeRef
Public Member Functions
TKeyFrameManipulator (const TKeyFrameManipulator &Rhs)
TKeyFrameManipulator (TArray< TimeType > *KeyTimesParam, FKeyHandleLookupTable *ExternalKeyHandleLUT=nullptr)
Construction from an externally owned array of times.
TKeyFrameManipulator (TKeyFrameManipulator &&Rhs)
virtual ~TKeyFrameManipulator ()
FKeyHandle AddKey (TimeTypeRef InTime)
Add a new key time to the data structure.
TOptional< FKeyHandle > FindKey (const TFunctionRef< bool(TimeTypeRef)> &InPredicate) const
Attempt to find a key using a custom predicate.
TOptional< TimeType > GetKeyTime (FKeyHandle KeyHandle) const
Get the time that corresponds to the specified key handle.
TKeyTimeIterator< TimeType > IterateKeys () const
Iterate the times stored in the external data structure.
TKeyFrameManipulator & operator= (const TKeyFrameManipulator &Rhs)
TKeyFrameManipulator & operator= (TKeyFrameManipulator &&Rhs)
void RemoveKey (FKeyHandle KeyHandle)
Remove a key that corresponds to the specified key handle.
void Reset ()
Removes all keys.
void SetKeyTime (FKeyHandle KeyHandle, TimeTypeRef NewTime)
Set the time for a key that corresponds to the specified key handle.
Protected Member Functions
int32 ComputeInsertIndex (TimeTypeRef InTime, int32 StartAtIndex=0) const
Calculate the index at which to insert the given time such that the container remains sorted.
int32 GetIndex (FKeyHandle KeyHandle) const
Get the index that corresponds to the specified key handle.
FKeyHandle GetKeyHandleFromIndex (int32 Index) const
Get the handle that corresponds to the specified index.
TimeType GetKeyTimeChecked (int32 KeyIndex) const
Get the time of the specified key index.
FKeyHandle InsertKeyImpl (TimeTypeRef Time, int32 InsertIndex) const
Insert the specified time into our container at the specified index.
void RelocateKeyImpl (int32 OldIndex, int32 NewIndex)
Move a key from one index to another.
Private Member Functions
virtual FKeyHandle AddKeyImpl (TimeTypeRef InTime) override
Add a new key time to the data structure.
virtual TOptional< FKeyHandle > FindKeyImpl (const TFunctionRef< bool(TimeTypeRef)> &InPredicate) const override
Attempt to find a key using a custom predicate.
virtual TOptional< TimeType > GetKeyTimeImpl (FKeyHandle KeyHandle) const override
Get the time that corresponds to the specified key handle.
virtual TKeyTimeIterator< TimeType > IterateKeysImpl () const override
Iterate the times stored in the external data structure.
virtual void OnKeyAdded (int32 Index)
Called when a new key time has been added.
virtual void OnKeyRelocated (int32 OldIndex, int32 NewIndex)
Called when a key time has been moved in the array.
virtual void OnKeyRemoved (int32 Index)
Called when a key time has been removed from the array.
virtual void OnReset ()
Called when all key times have been removed.
virtual void RemoveKeyImpl (FKeyHandle KeyHandle) override
Remove a key that corresponds to the specified key handle.
virtual void SetKeyTimeImpl (FKeyHandle KeyHandle, TimeTypeRef NewTime) override
Set the time for a key that corresponds to the specified key handle.
Private Member Functions inherited from IKeyFrameManipulator< TimeType >
FORCEINLINE FKeyHandle AddKey (TimeTypeRef InTime)
Add a new key time to the data structure.
FORCEINLINE TOptional< FKeyHandle > FindKey (TimeTypeRef KeyTime, TimeTypeRef KeyTimeTolerance) const
Attempt to find a key using a custom predicate.
FORCEINLINE TOptional< TimeType > GetKeyTime (FKeyHandle KeyHandle) const
Get the time that corresponds to the specified key handle.
FORCEINLINE void RemoveKey (FKeyHandle KeyHandle)
Remove a key that corresponds to the specified key handle.
FORCEINLINE void SetKeyTime (FKeyHandle KeyHandle, TimeTypeRef NewTime)
Set the time for a key that corresponds to the specified key handle.
Private Attributes
FKeyHandleLookupTable * KeyHandleLUT
Lookup table for key handles.
TArray< TimeType > * KeyTimes
Ptr to array of key times.
FKeyHandleLookupTable TemporaryKeyHandleLUT
Lookup table for key handles used when the user did not supply one.
friend TKeyTimeIterator< TimeType >
Additional Inherited Members
Private Types inherited from IKeyFrameManipulator< TimeType >
typedef TCallTraits< TimeType >::ParamType TimeTypeRef
Detailed Description
template<typename TimeType>
class TKeyFrameManipulator< TimeType >
Templated key frame manipulator that knows how to add, remove and (re)arrange key times.
Guarantees that any manipulation of a previously sorted time array, will remain sorted.
Definition at line 16 of file KeyFrameManipulator.h.
Member Typedef Documentation
TimeTypeRef
template<typename TimeType> typedef TCallTraits<TimeType>::ParamType TKeyFrameManipulator< TimeType >::TimeTypeRef
Definition at line 20 of file KeyFrameManipulator.h.
Constructor & Destructor Documentation
TKeyFrameManipulator() [1/3]
template<typename TimeType> TKeyFrameManipulator< TimeType >::TKeyFrameManipulator (TArray< TimeType > * KeyTimesParam, FKeyHandleLookupTable * ExternalKeyHandleLUT = nullptr) inline
Construction from an externally owned array of times.
Definition at line 25 of file KeyFrameManipulator.h.
References check, Handle, KeyHandleLUT, KeyTimes, and TemporaryKeyHandleLUT.
Referenced by TKeyFrameManipulator(), TKeyFrameManipulator(), operator=(), and operator=().
TKeyFrameManipulator() [2/3]
template<typename TimeType> TKeyFrameManipulator< TimeType >::TKeyFrameManipulator (const TKeyFrameManipulator< TimeType > & Rhs) inline
Definition at line 41 of file KeyFrameManipulator.h.
References TKeyFrameManipulator(), KeyHandleLUT, KeyTimes, and TemporaryKeyHandleLUT.
TKeyFrameManipulator() [3/3]
template<typename TimeType> TKeyFrameManipulator< TimeType >::TKeyFrameManipulator (TKeyFrameManipulator< TimeType > && Rhs) inline
Definition at line 58 of file KeyFrameManipulator.h.
References TKeyFrameManipulator(), KeyHandleLUT, KeyTimes, MoveTemp(), and TemporaryKeyHandleLUT.
~TKeyFrameManipulator()
template<typename TimeType> virtual TKeyFrameManipulator< TimeType >::~TKeyFrameManipulator () inline virtual
Definition at line 75 of file KeyFrameManipulator.h.
Member Function Documentation
AddKey()
template<typename TimeType> FKeyHandle TKeyFrameManipulator< TimeType >::AddKey (TimeTypeRef InTime) inline
Add a new key time to the data structure.
Parameters
InTime The value of the time to add
Returns
A key handle for the new key
Definition at line 105 of file KeyFrameManipulator.h.
References ComputeInsertIndex(), Handle, InsertKeyImpl(), InTime, and OnKeyAdded().
Referenced by AddKeyImpl().
AddKeyImpl()
template<typename TimeType> virtual FKeyHandle TKeyFrameManipulator< TimeType >::AddKeyImpl (TimeTypeRef InTime) inline override private virtual
Add a new key time to the data structure.
Parameters
InTime The value of the time to add
Returns
A key handle for the new key
Implements IKeyFrameManipulator< TimeType >.
Definition at line 90 of file KeyFrameManipulator.h.
References AddKey(), and InTime.
ComputeInsertIndex()
template<typename TimeType> int32 TKeyFrameManipulator< TimeType >::ComputeInsertIndex (TimeTypeRef InTime, int32 StartAtIndex = 0) const inline protected
Calculate the index at which to insert the given time such that the container remains sorted.
Definition at line 216 of file KeyFrameManipulator.h.
References InTime, and KeyTimes.
Referenced by AddKey(), and SetKeyTime().
FindKey()
template<typename TimeType> TOptional< FKeyHandle > TKeyFrameManipulator< TimeType >::FindKey (const TFunctionRef< bool(TimeTypeRef)> & InPredicate) const inline
Attempt to find a key using a custom predicate.
Parameters
InPredicate Predicate function to use when searching
Returns
The key's handle if found, or an empty container if not
Definition at line 188 of file KeyFrameManipulator.h.
References KeyHandleLUT, and KeyTimes.
Referenced by FindKeyImpl().
FindKeyImpl()
template<typename TimeType> virtual TOptional< FKeyHandle > TKeyFrameManipulator< TimeType >::FindKeyImpl (const TFunctionRef< bool(TimeTypeRef)> & InPredicate) const inline override private virtual
Attempt to find a key using a custom predicate.
Parameters
InPredicate Predicate function to use when searching
Returns
The key's handle if found, or an empty container if not
Implements IKeyFrameManipulator< TimeType >.
Definition at line 94 of file KeyFrameManipulator.h.
References FindKey().
GetIndex()
template<typename TimeType> int32 TKeyFrameManipulator< TimeType >::GetIndex (FKeyHandle KeyHandle) const inline protected
Get the index that corresponds to the specified key handle.
Definition at line 242 of file KeyFrameManipulator.h.
References KeyHandleLUT.
Referenced by RemoveKey().
GetKeyHandleFromIndex()
template<typename TimeType> FKeyHandle TKeyFrameManipulator< TimeType >::GetKeyHandleFromIndex (int32 Index) const inline protected
Get the handle that corresponds to the specified index.
Definition at line 250 of file KeyFrameManipulator.h.
References KeyHandleLUT, and KeyTimes.
GetKeyTime()
template<typename TimeType> TOptional< TimeType > TKeyFrameManipulator< TimeType >::GetKeyTime (FKeyHandle KeyHandle) const inline
Get the time that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to get the time for.
Returns
The time that this key exists at, or an empty container if it was not found
Definition at line 176 of file KeyFrameManipulator.h.
References INDEX_NONE, and KeyHandleLUT.
Referenced by GetKeyTimeImpl().
GetKeyTimeChecked()
template<typename TimeType> TimeType TKeyFrameManipulator< TimeType >::GetKeyTimeChecked (int32 KeyIndex) const inline protected
Get the time of the specified key index.
Index is assumed to be valid.
Definition at line 234 of file KeyFrameManipulator.h.
References KeyTimes.
GetKeyTimeImpl()
template<typename TimeType> virtual TOptional< TimeType > TKeyFrameManipulator< TimeType >::GetKeyTimeImpl (FKeyHandle KeyHandle) const inline override private virtual
Get the time that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to get the time for.
Returns
The time that this key exists at, or an empty container if it was not found
Implements IKeyFrameManipulator< TimeType >.
Definition at line 93 of file KeyFrameManipulator.h.
References GetKeyTime().
InsertKeyImpl()
template<typename TimeType> FKeyHandle TKeyFrameManipulator< TimeType >::InsertKeyImpl (TimeTypeRef Time, int32 InsertIndex) const inline protected
Insert the specified time into our container at the specified index.
Definition at line 225 of file KeyFrameManipulator.h.
References KeyHandleLUT, KeyTimes, and Time.
Referenced by AddKey().
IterateKeys()
template<typename TimeType> TKeyTimeIterator< TimeType > TKeyFrameManipulator< TimeType >::IterateKeys () const inline
Iterate the times stored in the external data structure.
Returns
An iterator that iterates the keys in order, and can optionally supply handles
Definition at line 206 of file KeyFrameManipulator.h.
References TKeyTimeIterator< TimeType >.
Referenced by IterateKeysImpl().
IterateKeysImpl()
template<typename TimeType> virtual TKeyTimeIterator< TimeType > TKeyFrameManipulator< TimeType >::IterateKeysImpl () const inline override private virtual
Iterate the times stored in the external data structure.
Returns
An iterator that iterates the keys in order, and can optionally supply handles
Implements IKeyFrameManipulator< TimeType >.
Definition at line 95 of file KeyFrameManipulator.h.
References IterateKeys().
OnKeyAdded()
template<typename TimeType> virtual void TKeyFrameManipulator< TimeType >::OnKeyAdded (int32 Index) inline private virtual
Called when a new key time has been added.
Definition at line 80 of file KeyFrameManipulator.h.
Referenced by AddKey().
OnKeyRelocated()
template<typename TimeType> virtual void TKeyFrameManipulator< TimeType >::OnKeyRelocated (int32 OldIndex, int32 NewIndex) inline private virtual
Called when a key time has been moved in the array.
Definition at line 82 of file KeyFrameManipulator.h.
Referenced by SetKeyTime().
OnKeyRemoved()
template<typename TimeType> virtual void TKeyFrameManipulator< TimeType >::OnKeyRemoved (int32 Index) inline private virtual
Called when a key time has been removed from the array.
Definition at line 84 of file KeyFrameManipulator.h.
Referenced by RemoveKey().
OnReset()
template<typename TimeType> virtual void TKeyFrameManipulator< TimeType >::OnReset () inline private virtual
Called when all key times have been removed.
Definition at line 86 of file KeyFrameManipulator.h.
Referenced by Reset().
operator=() [1/2]
template<typename TimeType> TKeyFrameManipulator & TKeyFrameManipulator< TimeType >::operator= (const TKeyFrameManipulator< TimeType > & Rhs) inline
Definition at line 47 of file KeyFrameManipulator.h.
References TKeyFrameManipulator(), KeyHandleLUT, KeyTimes, and TemporaryKeyHandleLUT.
operator=() [2/2]
template<typename TimeType> TKeyFrameManipulator & TKeyFrameManipulator< TimeType >::operator= (TKeyFrameManipulator< TimeType > && Rhs) inline
Definition at line 64 of file KeyFrameManipulator.h.
References TKeyFrameManipulator(), KeyHandleLUT, KeyTimes, MoveTemp(), and TemporaryKeyHandleLUT.
RelocateKeyImpl()
template<typename TimeType> void TKeyFrameManipulator< TimeType >::RelocateKeyImpl (int32 OldIndex, int32 NewIndex) inline protected
Move a key from one index to another.
Definition at line 258 of file KeyFrameManipulator.h.
References check, KeyHandleLUT, KeyTimes, No, and Time.
Referenced by SetKeyTime().
RemoveKey()
template<typename TimeType> void TKeyFrameManipulator< TimeType >::RemoveKey (FKeyHandle KeyHandle) inline
Remove a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to remove
Definition at line 146 of file KeyFrameManipulator.h.
References GetIndex(), INDEX_NONE, KeyHandleLUT, KeyTimes, No, and OnKeyRemoved().
Referenced by RemoveKeyImpl().
RemoveKeyImpl()
template<typename TimeType> virtual void TKeyFrameManipulator< TimeType >::RemoveKeyImpl (FKeyHandle KeyHandle) inline override private virtual
Remove a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to remove
Implements IKeyFrameManipulator< TimeType >.
Definition at line 92 of file KeyFrameManipulator.h.
References RemoveKey().
Reset()
template<typename TimeType> void TKeyFrameManipulator< TimeType >::Reset () inline
Removes all keys.
Definition at line 161 of file KeyFrameManipulator.h.
References KeyHandleLUT, KeyTimes, and OnReset().
SetKeyTime()
template<typename TimeType> void TKeyFrameManipulator< TimeType >::SetKeyTime (FKeyHandle KeyHandle, TimeTypeRef NewTime) inline
Set the time for a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to set the time for
NewTime The time to assign to this key
Definition at line 121 of file KeyFrameManipulator.h.
References ComputeInsertIndex(), INDEX_NONE, KeyHandleLUT, OnKeyRelocated(), and RelocateKeyImpl().
Referenced by SetKeyTimeImpl().
SetKeyTimeImpl()
template<typename TimeType> virtual void TKeyFrameManipulator< TimeType >::SetKeyTimeImpl (FKeyHandle KeyHandle, TimeTypeRef NewTime) inline override private virtual
Set the time for a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to set the time for
NewTime The time to assign to this key
Implements IKeyFrameManipulator< TimeType >.
Definition at line 91 of file KeyFrameManipulator.h.
References SetKeyTime().
Field Documentation
KeyHandleLUT
template<typename TimeType> FKeyHandleLookupTable* TKeyFrameManipulator< TimeType >::KeyHandleLUT private
Lookup table for key handles.
Definition at line 283 of file KeyFrameManipulator.h.
Referenced by TKeyFrameManipulator(), TKeyFrameManipulator(), TKeyFrameManipulator(), FindKey(), GetIndex(), GetKeyHandleFromIndex(), GetKeyTime(), InsertKeyImpl(), operator=(), operator=(), RelocateKeyImpl(), RemoveKey(), Reset(), and SetKeyTime().
KeyTimes
template<typename TimeType> TArray<TimeType>* TKeyFrameManipulator< TimeType >::KeyTimes private
Ptr to array of key times.
Definition at line 280 of file KeyFrameManipulator.h.
Referenced by TKeyFrameManipulator(), TKeyFrameManipulator(), TKeyFrameManipulator(), ComputeInsertIndex(), FindKey(), GetKeyHandleFromIndex(), GetKeyTimeChecked(), InsertKeyImpl(), operator=(), operator=(), RelocateKeyImpl(), RemoveKey(), and Reset().
TemporaryKeyHandleLUT
template<typename TimeType> FKeyHandleLookupTable TKeyFrameManipulator< TimeType >::TemporaryKeyHandleLUT mutable private
Lookup table for key handles used when the user did not supply one.
Definition at line 286 of file KeyFrameManipulator.h.
Referenced by TKeyFrameManipulator(), TKeyFrameManipulator(), TKeyFrameManipulator(), operator=(), and operator=().
TKeyTimeIterator< TimeType >
template<typename TimeType> friend TKeyFrameManipulator< TimeType >::TKeyTimeIterator< TimeType > private
Definition at line 277 of file KeyFrameManipulator.h.
Referenced by IterateKeys().
The documentation for this class was generated from the following files:
IKeyFrameManipulator.h
KeyFrameManipulator.h