Unreal Engine 5.6 C++ API: SharedPointerInternals.h File Reference
SharedPointerInternals.h File Reference
#include "CoreTypes.h"
#include "HAL/UnrealMemory.h"
#include "Misc/AssertionMacros.h"
#include "Templates/RemoveReference.h"
#include "Templates/SharedPointerFwd.h"
#include "Templates/TypeCompatibleBytes.h"
#include "AutoRTFM.h"
#include <atomic>
#include <type_traits>
Data Structures
struct SharedPointerInternals::DefaultDeleter< Type >
Deletes an object via the standard delete operator.
struct SharedPointerInternals::FConstCastTag
struct SharedPointerInternals::FNullTag
class SharedPointerInternals::FSharedReferencer< Mode >
FSharedReferencer is a wrapper around a pointer to a reference controller that is used by either a TSharedRef or a TSharedPtr to keep track of a referenced object's lifetime.
struct SharedPointerInternals::FStaticCastTag
Dummy structures used internally as template arguments for typecasts.
class SharedPointerInternals::FWeakReferencer< Mode >
FWeakReferencer is a wrapper around a pointer to a reference controller that is used by a TWeakPtr to keep track of a referenced object's lifetime.
struct SharedPointerInternals::TDeleterHolder< DeleterType, bIsZeroSize >
struct SharedPointerInternals::TDeleterHolder< DeleterType, false >
class SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >
struct SharedPointerInternals::TRawPtrProxy< ObjectType >
Proxy structure for implicitly converting raw pointers to shared/weak pointers.
struct SharedPointerInternals::TRawPtrProxyWithDeleter< ObjectType, DeleterType >
Proxy structure for implicitly converting raw pointers to shared/weak pointers.
class SharedPointerInternals::TReferenceControllerBase< Mode >
class SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >
struct UE::Core::Private::FSharedFromThisBase
Namespaces
namespace SharedPointerInternals
SharedPointerInternals contains internal workings of shared and weak pointers.
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define THREAD_SANITISE_UNSAFEPTR 0
Default behavior.
#define TSAN_SAFE_UNSAFEPTR TSAN_SAFE
Functions
template<class SharedPtrType, class ObjectType>
FORCEINLINE void SharedPointerInternals::EnableSharedFromThis (SharedPtrType *InSharedPtrOrRef, ObjectType const *InObject)
Templated helper function (const) that creates a shared pointer from an object instance.
template<typename T>
constexpr bool IsDerivedFromSharedFromThis ()
template<ESPMode Mode, typename ObjectType, typename DeleterType>
TReferenceControllerBase< Mode > * SharedPointerInternals::NewCustomReferenceController (ObjectType *Object, DeleterType &&Deleter)
Creates a custom reference controller with a specified deleter.
template<ESPMode Mode, typename ObjectType>
TReferenceControllerBase< Mode > * SharedPointerInternals::NewDefaultReferenceController (ObjectType *Object)
Creates a reference controller which just calls delete.
template<ESPMode Mode, typename ObjectType, typename... ArgTypes>
TIntrusiveReferenceController< ObjectType, Mode > * SharedPointerInternals::NewIntrusiveReferenceController (ArgTypes &&... Args)
Creates an intrusive reference controller.
Macro Definition Documentation
THREAD_SANITISE_UNSAFEPTR
#define THREAD_SANITISE_UNSAFEPTR 0
Default behavior.
Definition at line 18 of file SharedPointerInternals.h.
TSAN_SAFE_UNSAFEPTR
#define TSAN_SAFE_UNSAFEPTR TSAN_SAFE
Definition at line 23 of file SharedPointerInternals.h.
Function Documentation
IsDerivedFromSharedFromThis()
template<typename T> bool IsDerivedFromSharedFromThis () constexpr
Definition at line 848 of file SharedPointerInternals.h.
Referenced by SharedPointerInternals::EnableSharedFromThis(), MakeShareable(), and MakeShareable().