Unreal Engine 5.6 C++ API: Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType > Class Template Reference
Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType > Class Template Reference
#include "MetasoundReceiveNode.h"
Public Member Functions
TReceiverOperator (TDataReadReference< TDataType > InInitDataRef, TDataWriteReference< TDataType > InOutDataRef, TDataReadReference< FSendAddress > InSendAddress, const FOperatorSettings &InOperatorSettings)
virtual ~TReceiverOperator ()
virtual void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TReceiverOperator< TDataType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static FVertexInterface DeclareVertexInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Member Functions
TReceiverOperator ()=delete
TReceiverPtr< TDataType > CreateNewReceiver () const
FSendAddress GetSendAddressWithDataType (const FSendAddress &InAddress) const
void ResetReceiverAndCleanupChannel ()
Private Attributes
bool bHasNotReceivedData
FReceiverInitParams CachedReceiverParams
FSendAddress CachedSendAddress
TDataReadReference< TDataType > DefaultData
TDataWriteReference< TDataType > OutputData
TReceiverPtr< TDataType > Receiver
TDataReadReference< FSendAddress > SendAddress
Additional Inherited Members
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Detailed Description
template<typename TDataType>
class Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >
Definition at line 38 of file MetasoundReceiveNode.h.
Constructor & Destructor Documentation
TReceiverOperator() [1/2]
template<typename TDataType> Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::TReceiverOperator () private delete
TReceiverOperator() [2/2]
template<typename TDataType> Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::TReceiverOperator (TDataReadReference< TDataType > InInitDataRef, TDataWriteReference< TDataType > InOutDataRef, TDataReadReference< FSendAddress > InSendAddress, const FOperatorSettings & InOperatorSettings) inline
Definition at line 101 of file MetasoundReceiveNode.h.
References bHasNotReceivedData, CachedReceiverParams, CachedSendAddress, DefaultData, OutputData, and SendAddress.
~TReceiverOperator()
template<typename TDataType> virtual Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::~TReceiverOperator () inline virtual
Definition at line 113 of file MetasoundReceiveNode.h.
References ResetReceiverAndCleanupChannel().
Member Function Documentation
BindInputs()
template<typename TDataType> virtual void Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 118 of file MetasoundReceiveNode.h.
References Metasound::FInputVertexInterfaceData::BindReadVertex(), DefaultData, METASOUND_GET_PARAM_NAME, and SendAddress.
BindOutputs()
template<typename TDataType> virtual void Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 125 of file MetasoundReceiveNode.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), METASOUND_GET_PARAM_NAME, and OutputData.
CreateNewReceiver()
template<typename TDataType> TReceiverPtr< TDataType > Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateNewReceiver () const inline private
Definition at line 199 of file MetasoundReceiveNode.h.
References CachedReceiverParams, ensure, Metasound::FDataTransmissionCenter::Get(), Metasound::GetMetasoundDataTypeName(), GetSendAddressWithDataType(), and SendAddress.
Referenced by Execute().
CreateOperator()
template<typename TDataType> TUniquePtr< IOperator > Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 170 of file MetasoundReceiveNode.h.
References Metasound::TDataFactory< DataType, TDataReadReference< DataType > >::CreateAny(), Metasound::TDataFactory< DataType, TDataWriteReference< DataType > >::CreateAny(), Metasound::FInputVertexInterfaceData::GetDataReadReference(), Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FBuildOperatorParams::InputData, Metasound::FInputVertexInterfaceData::IsVertexBound(), MakeUnique(), METASOUND_GET_PARAM_NAME, and Metasound::FBuildOperatorParams::OperatorSettings.
DeclareVertexInterface()
template<typename TDataType> FVertexInterface Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::DeclareVertexInterface () inline static
Definition at line 43 of file MetasoundReceiveNode.h.
References FText::GetEmpty(), METASOUND_GET_PARAM_DISPLAYNAME, and METASOUND_GET_PARAM_NAME.
Referenced by Metasound::TReceiveNode< TDataType >::DeclareVertexInterface(), and GetNodeInfo().
Execute()
template<typename TDataType> void Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::Execute () inline
Definition at line 131 of file MetasoundReceiveNode.h.
References bHasNotReceivedData, Metasound::TExecutableDataType< DataType >::bIsExecutable, CachedSendAddress, CreateNewReceiver(), DefaultData, ensure, Metasound::TExecutableDataType< DataType >::ExecuteInline(), OutputData, Receiver, ResetReceiverAndCleanupChannel(), and SendAddress.
GetNodeInfo()
template<typename TDataType> const FNodeClassMetadata & Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetNodeInfo () inline static
Definition at line 72 of file MetasoundReceiveNode.h.
References DeclareVertexInterface(), Metasound::ReceiveNodeInfo::GetCurrentMajorVersion(), Metasound::ReceiveNodeInfo::GetCurrentMinorVersion(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Info, METASOUND_LOCTEXT, METASOUND_LOCTEXT_FORMAT, Metasound::PluginAuthor, and Metasound::PluginNodeMissingPrompt.
Referenced by Metasound::TReceiveNode< TDataType >::GetNodeInfo().
GetSendAddressWithDataType()
template<typename TDataType> FSendAddress Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetSendAddressWithDataType (const FSendAddress & InAddress) const inline private
Definition at line 191 of file MetasoundReceiveNode.h.
References Metasound::FSendAddress::GetChannelName(), Metasound::FSendAddress::GetInstanceID(), and Metasound::GetMetasoundDataTypeName().
Referenced by CreateNewReceiver(), and ResetReceiverAndCleanupChannel().
Reset()
template<typename TDataType> void Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 164 of file MetasoundReceiveNode.h.
References bHasNotReceivedData, DefaultData, and OutputData.
ResetReceiverAndCleanupChannel()
template<typename TDataType> void Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::ResetReceiverAndCleanupChannel () inline private
Definition at line 208 of file MetasoundReceiveNode.h.
References CachedSendAddress, Metasound::FDataTransmissionCenter::Get(), GetSendAddressWithDataType(), and Receiver.
Referenced by ~TReceiverOperator(), and Execute().
Field Documentation
bHasNotReceivedData
template<typename TDataType> bool Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::bHasNotReceivedData private
Definition at line 214 of file MetasoundReceiveNode.h.
Referenced by TReceiverOperator(), Execute(), and Reset().
CachedReceiverParams
template<typename TDataType> FReceiverInitParams Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CachedReceiverParams private
Definition at line 221 of file MetasoundReceiveNode.h.
Referenced by TReceiverOperator(), and CreateNewReceiver().
CachedSendAddress
template<typename TDataType> FSendAddress Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CachedSendAddress private
Definition at line 220 of file MetasoundReceiveNode.h.
Referenced by TReceiverOperator(), Execute(), and ResetReceiverAndCleanupChannel().
DefaultData
template<typename TDataType> TDataReadReference<TDataType> Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::DefaultData private
Definition at line 216 of file MetasoundReceiveNode.h.
Referenced by TReceiverOperator(), BindInputs(), Execute(), and Reset().
OutputData
template<typename TDataType> TDataWriteReference<TDataType> Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::OutputData private
Definition at line 217 of file MetasoundReceiveNode.h.
Referenced by TReceiverOperator(), BindOutputs(), Execute(), and Reset().
Receiver
template<typename TDataType> TReceiverPtr<TDataType> Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::Receiver private
Definition at line 223 of file MetasoundReceiveNode.h.
Referenced by Execute(), and ResetReceiverAndCleanupChannel().
SendAddress
template<typename TDataType> TDataReadReference<FSendAddress> Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::SendAddress private
Definition at line 218 of file MetasoundReceiveNode.h.
Referenced by TReceiverOperator(), BindInputs(), CreateNewReceiver(), and Execute().
The documentation for this class was generated from the following file:
MetasoundReceiveNode.h