Unreal Engine 5.6 C++ API: FMusicalTime Struct Reference
FMusicalTime Struct Reference
#include "MusicalTime.h"
Public Member Functions
FMusicalTime ()
FMusicalTime (int32 InBar, int32 InTickInBar=0, int32 InTicksPerBar=MusicalTime::TicksPerQuarterNote *4, int32 InTicksPerBeat=MusicalTime::TicksPerQuarterNote)
double FractionalBar () const
double FractionalBeatInBar () const
bool IsValid () const
Verify that this musical time is valid to use.
double operator- (const FMusicalTime &Other)
return fractional bars between two musical times
bool Serialize (FArchive &Ar)
Serializes the given musical time from or into the specified archive.
Static Public Member Functions
static FMusicalTime FloorBar (const FMusicalTime &InMusicalTime)
static FMusicalTime FloorBeat (const FMusicalTime &InMusicalTime)
Data Fields
int32 Bar
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
int32 TickInBar
int32 TicksPerBar
int32 TicksPerBeat
Friends
FORCEINLINE_DEBUGGABLE bool operator!= (const FMusicalTime &A, const FMusicalTime &B)
FORCEINLINE_DEBUGGABLE bool operator< (const FMusicalTime &A, const FMusicalTime &B)
FArchive & operator<< (FArchive &Ar, FMusicalTime &MusicalTime)
FORCEINLINE_DEBUGGABLE bool operator<= (const FMusicalTime &A, const FMusicalTime &B)
FORCEINLINE_DEBUGGABLE bool operator== (const FMusicalTime &A, const FMusicalTime &B)
FORCEINLINE_DEBUGGABLE bool operator> (const FMusicalTime &A, const FMusicalTime &B)
FORCEINLINE_DEBUGGABLE bool operator>= (const FMusicalTime &A, const FMusicalTime &B)
Detailed Description
Definition at line 13 of file MusicalTime.h.
Constructor & Destructor Documentation
FMusicalTime() [1/2]
FMusicalTime::FMusicalTime () inline
Definition at line 15 of file MusicalTime.h.
References Bar, TickInBar, TicksPerBar, and TicksPerBeat.
Referenced by FloorBar(), FloorBeat(), operator!=, operator-(), operator<, operator<<, operator<=, operator==, operator>, and operator>=.
FMusicalTime() [2/2]
FMusicalTime::FMusicalTime (int32 InBar, int32 InTickInBar = 0, int32 InTicksPerBar = MusicalTime::TicksPerQuarterNote * 4, int32 InTicksPerBeat = MusicalTime::TicksPerQuarterNote) inline
Definition at line 22 of file MusicalTime.h.
References Bar, TickInBar, TicksPerBar, TicksPerBeat, and MusicalTime::TicksPerQuarterNote.
Member Function Documentation
FloorBar()
FMusicalTime FMusicalTime::FloorBar (const FMusicalTime & InMusicalTime) inline static
Definition at line 75 of file MusicalTime.h.
References FMusicalTime(), and TickInBar.
FloorBeat()
FMusicalTime FMusicalTime::FloorBeat (const FMusicalTime & InMusicalTime) inline static
Definition at line 82 of file MusicalTime.h.
References FMusicalTime(), TickInBar, and TicksPerBeat.
FractionalBar()
double FMusicalTime::FractionalBar () const inline
Definition at line 53 of file MusicalTime.h.
References Bar, IsValid(), TickInBar, and TicksPerBar.
Referenced by operator-().
FractionalBeatInBar()
double FMusicalTime::FractionalBeatInBar () const inline
Definition at line 44 of file MusicalTime.h.
References IsValid(), TickInBar, and TicksPerBeat.
IsValid()
bool FMusicalTime::IsValid () const inline
Verify that this musical time is valid to use.
Definition at line 39 of file MusicalTime.h.
References TicksPerBar, and TicksPerBeat.
Referenced by FractionalBar(), and FractionalBeatInBar().
operator-()
double FMusicalTime::operator- (const FMusicalTime & Other) inline
return fractional bars between two musical times
Definition at line 70 of file MusicalTime.h.
References FMusicalTime(), FractionalBar(), and Other.
Serialize()
bool FMusicalTime::Serialize (FArchive & Ar) inline
Serializes the given musical time from or into the specified archive.
Definition at line 134 of file MusicalTime.h.
References Ar, Bar, TickInBar, TicksPerBar, and TicksPerBeat.
Friends And Related Symbol Documentation
operator!=
FORCEINLINE_DEBUGGABLE bool operator!= (const FMusicalTime & A, const FMusicalTime & B) friend
Definition at line 104 of file MusicalTime.h.
References FMusicalTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator<
FORCEINLINE_DEBUGGABLE bool operator< (const FMusicalTime & A, const FMusicalTime & B) friend
Definition at line 122 of file MusicalTime.h.
References FMusicalTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator<<
FArchive & operator<< (FArchive & Ar, FMusicalTime & MusicalTime) friend
Definition at line 92 of file MusicalTime.h.
References FMusicalTime(), and Ar.
operator<=
FORCEINLINE_DEBUGGABLE bool operator<= (const FMusicalTime & A, const FMusicalTime & B) friend
Definition at line 128 of file MusicalTime.h.
References FMusicalTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator==
FORCEINLINE_DEBUGGABLE bool operator== (const FMusicalTime & A, const FMusicalTime & B) friend
Definition at line 98 of file MusicalTime.h.
References FMusicalTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator>
FORCEINLINE_DEBUGGABLE bool operator> (const FMusicalTime & A, const FMusicalTime & B) friend
Definition at line 110 of file MusicalTime.h.
References FMusicalTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator>=
FORCEINLINE_DEBUGGABLE bool operator>= (const FMusicalTime & A, const FMusicalTime & B) friend
Definition at line 116 of file MusicalTime.h.
References FMusicalTime(), A, B, and FORCEINLINE_DEBUGGABLE.
Field Documentation
Bar
int32 FMusicalTime::Bar
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
Definition at line 31 of file MusicalTime.h.
Referenced by FMusicalTime(), FMusicalTime(), FractionalBar(), and Serialize().
TickInBar
int32 FMusicalTime::TickInBar
Definition at line 32 of file MusicalTime.h.
Referenced by FMusicalTime(), FMusicalTime(), FloorBar(), FloorBeat(), FractionalBar(), FractionalBeatInBar(), and Serialize().
TicksPerBar
int32 FMusicalTime::TicksPerBar
Definition at line 33 of file MusicalTime.h.
Referenced by FMusicalTime(), FMusicalTime(), FractionalBar(), IsValid(), and Serialize().
TicksPerBeat
int32 FMusicalTime::TicksPerBeat
Definition at line 34 of file MusicalTime.h.
Referenced by FMusicalTime(), FMusicalTime(), FloorBeat(), FractionalBeatInBar(), IsValid(), and Serialize().
The documentation for this struct was generated from the following file:
MusicalTime.h