Unreal Engine 5.6 C++ API: IMovieSceneModule Class Reference
IMovieSceneModule Class Reference abstract
The public interface of the MovieScene module.
#include "IMovieSceneModule.h"
Public Member Functions
virtual FMovieSceneEvaluationGroupParameters GetEvaluationGroupParameters (FName GroupName) const =0
Find group parameters for a specific evaluation group.
virtual TWeakPtr< IMovieSceneModule > GetWeakPtr ()=0
Get this module ptr as a weak ptr.
virtual void RegisterEvaluationGroupParameters (FName GroupName, const FMovieSceneEvaluationGroupParameters &GroupParameters)=0
Register template parameters for compilation.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IMovieSceneModule & Get ()
Singleton-like access to IMovieScene.
static IMovieSceneModule & Get_Concurrent ()
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Detailed Description
The public interface of the MovieScene module.
Definition at line 27 of file IMovieSceneModule.h.
Member Function Documentation
Get()
IMovieSceneModule & IMovieSceneModule::Get () inline static
Singleton-like access to IMovieScene.
Returns
Returns MovieScene singleton instance, loading the module on demand if needed
Definition at line 37 of file IMovieSceneModule.h.
References FModuleManager::LoadModuleChecked().
Get_Concurrent()
IMovieSceneModule & IMovieSceneModule::Get_Concurrent () inline static
Definition at line 42 of file IMovieSceneModule.h.
References FModuleManager::GetModuleChecked().
GetEvaluationGroupParameters()
virtual FMovieSceneEvaluationGroupParameters IMovieSceneModule::GetEvaluationGroupParameters (FName GroupName) const pure virtual
Find group parameters for a specific evaluation group.
GetWeakPtr()
virtual TWeakPtr< IMovieSceneModule > IMovieSceneModule::GetWeakPtr () pure virtual
Get this module ptr as a weak ptr.
Note
: resulting weak ptr should not be used to hold persistent strong references
IsAvailable()
bool IMovieSceneModule::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 52 of file IMovieSceneModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
RegisterEvaluationGroupParameters()
virtual void IMovieSceneModule::RegisterEvaluationGroupParameters (FName GroupName, const FMovieSceneEvaluationGroupParameters & GroupParameters) pure virtual
Register template parameters for compilation.
The documentation for this class was generated from the following file:
IMovieSceneModule.h