Unreal Engine 5.6 C++ API: UE::Geometry::FMeshEdgeSelection Class Reference
UE::Geometry::FMeshEdgeSelection Class Reference
Currently a thin wrapper of a TSet<int> of Edge IDs paired with a Mesh; the backing storage will likely change as we need to optimize in the future.
#include "MeshEdgeSelection.h"
Public Member Functions
FMeshEdgeSelection (const FDynamicMesh3 *mesh)
GEOMETRYCORE_API FMeshEdgeSelection (const FDynamicMesh3 *mesh, const FMeshFaceSelection &convertT, int minCount=1)
GEOMETRYCORE_API FMeshEdgeSelection (const FDynamicMesh3 *mesh, const FMeshVertexSelection &convertV, int minCount=2)
TArray< int > AsArray () const
TBitArray< FDefaultBitArrayAllocator > AsBitArray () const
TSet< int > AsSet () const
TSet< int >::TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
TSet< int >::TRangedForConstIterator begin () const
void ContractByBorderEdges (int32 nRings=1)
For each contraction, remove edges in current selection set that have any unselected edge neighboring either of the edge's vertices.
void Deselect (int tid)
void Deselect (TArrayView< const int > edges)
void DeselectAll ()
TSet< int >::TRangedForIterator end ()
TSet< int >::TRangedForConstIterator end () const
void ExpandToOneRingNeighbors ()
void ExpandToOneRingNeighbors (int NumRings)
void ExpandToOneRingNeighbors (int NumRings, TFunctionRef< bool(int32)> FilterF)
void ExpandToOneRingNeighbors (TFunctionRef< bool(int32)> FilterF)
Add all one-ring neighbors of current selection to set.
bool IsSelected (int eid)
int Num ()
void Select (const TArray< int > &edges)
void Select (int eid)
void Select (TArrayView< const int > edges)
void Select (TFunctionRef< bool(int)> SelectF)
GEOMETRYCORE_API void SelectBoundaryTriEdges (const FMeshFaceSelection &Triangles)
void SelectTriangleEdges (TArrayView< const int > Triangles)
void SelectVertexEdges (TArrayView< const int > vertices)
Private Member Functions
void add (int eid)
template<bool bHasFilter, typename ExpandContainerType>
void ExpandToOneRingNeighbors_FindNeighborsHelper (const ExpandContainerType &ToExpand, TArray< int32 > &ToAdd, TFunctionRef< bool(int)> FilterF)
template<bool bHasFilter>
void ExpandToOneRingNeighbors_Helper (int32 NumRings, TFunctionRef< bool(int)> FilterF)
void remove (int eid)
Private Attributes
const FDynamicMesh3 * Mesh
TSet< int > Selected
Detailed Description
Currently a thin wrapper of a TSet<int> of Edge IDs paired with a Mesh; the backing storage will likely change as we need to optimize in the future.
Definition at line 21 of file MeshEdgeSelection.h.
Constructor & Destructor Documentation
FMeshEdgeSelection() [1/3]
UE::Geometry::FMeshEdgeSelection::FMeshEdgeSelection (const FDynamicMesh3 * mesh) inline
Definition at line 30 of file MeshEdgeSelection.h.
References Mesh.
FMeshEdgeSelection() [2/3]
GEOMETRYCORE_API UE::Geometry::FMeshEdgeSelection::FMeshEdgeSelection (const FDynamicMesh3 * mesh, const FMeshVertexSelection & convertV, int minCount = 2)
FMeshEdgeSelection() [3/3]
GEOMETRYCORE_API UE::Geometry::FMeshEdgeSelection::FMeshEdgeSelection (const FDynamicMesh3 * mesh, const FMeshFaceSelection & convertT, int minCount = 1)
Member Function Documentation
add()
void UE::Geometry::FMeshEdgeSelection::add (int eid) inline private
Definition at line 73 of file MeshEdgeSelection.h.
References Selected.
Referenced by ExpandToOneRingNeighbors_Helper(), Select(), Select(), Select(), Select(), SelectTriangleEdges(), and SelectVertexEdges().
AsArray()
TArray< int > UE::Geometry::FMeshEdgeSelection::AsArray () const inline
Definition at line 48 of file MeshEdgeSelection.h.
References Selected.
AsBitArray()
TBitArray< FDefaultBitArrayAllocator > UE::Geometry::FMeshEdgeSelection::AsBitArray () const inline
Definition at line 52 of file MeshEdgeSelection.h.
References Mesh, and Selected.
AsSet()
TSet< int > UE::Geometry::FMeshEdgeSelection::AsSet () const inline
Definition at line 44 of file MeshEdgeSelection.h.
References Selected.
begin() [1/2]
TSet< int >::TRangedForIterator UE::Geometry::FMeshEdgeSelection::begin () inline
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 67 of file MeshEdgeSelection.h.
References Selected.
begin() [2/2]
TSet< int >::TRangedForConstIterator UE::Geometry::FMeshEdgeSelection::begin () const inline
Definition at line 68 of file MeshEdgeSelection.h.
References Selected.
ContractByBorderEdges()
void UE::Geometry::FMeshEdgeSelection::ContractByBorderEdges (int32 nRings = 1) inline
For each contraction, remove edges in current selection set that have any unselected edge neighboring either of the edge's vertices.
Definition at line 268 of file MeshEdgeSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), Deselect(), IsSelected(), Mesh, TArray< InElementType, InAllocatorType >::Reset(), and Selected.
Deselect() [1/2]
void UE::Geometry::FMeshEdgeSelection::Deselect (int tid) inline
Definition at line 308 of file MeshEdgeSelection.h.
References remove().
Referenced by ContractByBorderEdges().
Deselect() [2/2]
void UE::Geometry::FMeshEdgeSelection::Deselect (TArrayView< const int > edges) inline
Definition at line 311 of file MeshEdgeSelection.h.
References remove().
DeselectAll()
void UE::Geometry::FMeshEdgeSelection::DeselectAll () inline
Definition at line 317 of file MeshEdgeSelection.h.
References Selected.
end() [1/2]
TSet< int >::TRangedForIterator UE::Geometry::FMeshEdgeSelection::end () inline
Definition at line 69 of file MeshEdgeSelection.h.
References Selected.
end() [2/2]
TSet< int >::TRangedForConstIterator UE::Geometry::FMeshEdgeSelection::end () const inline
Definition at line 70 of file MeshEdgeSelection.h.
References Selected.
ExpandToOneRingNeighbors() [1/4]
void UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors () inline
Definition at line 248 of file MeshEdgeSelection.h.
References ExpandToOneRingNeighbors_Helper().
ExpandToOneRingNeighbors() [2/4]
void UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors (int NumRings) inline
Definition at line 258 of file MeshEdgeSelection.h.
References ExpandToOneRingNeighbors_Helper().
ExpandToOneRingNeighbors() [3/4]
void UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors (int NumRings, TFunctionRef< bool(int32)> FilterF) inline
Definition at line 253 of file MeshEdgeSelection.h.
References ExpandToOneRingNeighbors_Helper().
ExpandToOneRingNeighbors() [4/4]
void UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors (TFunctionRef< bool(int32)> FilterF) inline
Add all one-ring neighbors of current selection to set.
On a large selection this is quite expensive as we don't know the boundary, so we have to iterate over all selected edges.
Return false from FilterF to prevent vertices from being included.
Definition at line 243 of file MeshEdgeSelection.h.
References ExpandToOneRingNeighbors_Helper().
ExpandToOneRingNeighbors_FindNeighborsHelper()
template<bool bHasFilter, typename ExpandContainerType> void UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors_FindNeighborsHelper (const ExpandContainerType & ToExpand, TArray< int32 > & ToAdd, TFunctionRef< bool(int)> FilterF) inline private
Definition at line 159 of file MeshEdgeSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), IsSelected(), and Mesh.
Referenced by ExpandToOneRingNeighbors_Helper().
ExpandToOneRingNeighbors_Helper()
template<bool bHasFilter> void UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors_Helper (int32 NumRings, TFunctionRef< bool(int)> FilterF) inline private
Definition at line 185 of file MeshEdgeSelection.h.
References add(), ExpandToOneRingNeighbors_FindNeighborsHelper(), ID, No, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::RemoveAtSwap(), TArray< InElementType, InAllocatorType >::Reset(), Selected, and Swap.
Referenced by ExpandToOneRingNeighbors(), ExpandToOneRingNeighbors(), ExpandToOneRingNeighbors(), and ExpandToOneRingNeighbors().
IsSelected()
bool UE::Geometry::FMeshEdgeSelection::IsSelected (int eid) inline
Definition at line 91 of file MeshEdgeSelection.h.
References Selected.
Referenced by ContractByBorderEdges(), and ExpandToOneRingNeighbors_FindNeighborsHelper().
Num()
int UE::Geometry::FMeshEdgeSelection::Num () inline
Definition at line 84 of file MeshEdgeSelection.h.
References Selected.
remove()
void UE::Geometry::FMeshEdgeSelection::remove (int eid) inline private
Definition at line 77 of file MeshEdgeSelection.h.
References Selected.
Referenced by Deselect(), and Deselect().
Select() [1/4]
void UE::Geometry::FMeshEdgeSelection::Select (const TArray< int > & edges) inline
Definition at line 106 of file MeshEdgeSelection.h.
References add(), and Mesh.
Select() [2/4]
void UE::Geometry::FMeshEdgeSelection::Select (int eid) inline
Definition at line 97 of file MeshEdgeSelection.h.
References add(), ensure, and Mesh.
Select() [3/4]
void UE::Geometry::FMeshEdgeSelection::Select (TArrayView< const int > edges) inline
Definition at line 116 of file MeshEdgeSelection.h.
References add(), and Mesh.
Select() [4/4]
void UE::Geometry::FMeshEdgeSelection::Select (TFunctionRef< bool(int)> SelectF) inline
Definition at line 126 of file MeshEdgeSelection.h.
References add(), and Mesh.
SelectBoundaryTriEdges()
GEOMETRYCORE_API void UE::Geometry::FMeshEdgeSelection::SelectBoundaryTriEdges (const FMeshFaceSelection & Triangles)
SelectTriangleEdges()
void UE::Geometry::FMeshEdgeSelection::SelectTriangleEdges (TArrayView< const int > Triangles) inline
Definition at line 148 of file MeshEdgeSelection.h.
References UE::Geometry::FIndex3i::A, add(), UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, and Mesh.
SelectVertexEdges()
void UE::Geometry::FMeshEdgeSelection::SelectVertexEdges (TArrayView< const int > vertices) inline
Definition at line 138 of file MeshEdgeSelection.h.
References add(), and Mesh.
Field Documentation
Mesh
const FDynamicMesh3* UE::Geometry::FMeshEdgeSelection::Mesh private
Definition at line 24 of file MeshEdgeSelection.h.
Referenced by FMeshEdgeSelection(), AsBitArray(), ContractByBorderEdges(), ExpandToOneRingNeighbors_FindNeighborsHelper(), Select(), Select(), Select(), Select(), SelectTriangleEdges(), and SelectVertexEdges().
Selected
TSet<int> UE::Geometry::FMeshEdgeSelection::Selected private
Definition at line 26 of file MeshEdgeSelection.h.
Referenced by add(), AsArray(), AsBitArray(), AsSet(), begin(), begin(), ContractByBorderEdges(), DeselectAll(), end(), end(), ExpandToOneRingNeighbors_Helper(), IsSelected(), Num(), and remove().
The documentation for this class was generated from the following file:
MeshEdgeSelection.h