Unreal Engine 5.6 C++ API: UE::Geometry::TFastWindingTree< TriangleMeshType > Class Template Reference
UE::Geometry::TFastWindingTree< TriangleMeshType > Class Template Reference
Fast Mesh Winding Number extension to a TMeshAABBTree3.
#include "FastWinding.h"
Data Structures
struct FWNInfo
Public Member Functions
TFastWindingTree (TMeshAABBTree3< TriangleMeshType > *TreeToRef, bool bAutoBuild=true)
void Build (bool bForceRebuild=true)
double FastWindingNumber (const FVector3d &P)
Fast approximation of winding number using far-field approximations.
double FastWindingNumber (const FVector3d &P) const
Const version does not auto-build on query.
TMeshAABBTree3< TriangleMeshType > * GetTree () const
bool IsBuilt () const
bool IsInside (const FVector3d &P, double WindingIsoThreshold=0.5) const
void SetTree (TMeshAABBTree3< TriangleMeshType > *TreeToRef, bool bAutoBuild=true)
Data Fields
int FWNApproxOrder = 2
FWN approximation order.
double FWNBeta = 2.0
FWN beta parameter - is 2.0 in paper.
Private Member Functions
double branch_fast_winding_num (int IBox, FVector3d P) const
void build_fast_winding_cache ()
int build_fast_winding_cache (int IBox, int Depth, int TriCountThresh, TOptional< TSet< int > > &TriHash, const FMeshTriInfoCache &TriCache)
bool can_use_fast_winding_cache (int IBox, const FVector3d &Q) const
void collect_triangles (int IBox, TSet< int > &Triangles)
double evaluate_box_fast_winding_cache (int IBox, const FVector3d &Q) const
void make_box_fast_winding_cache (int IBox, const TSet< int > &Triangles, const FMeshTriInfoCache &TriCache)
Private Attributes
TMap< int, FWNInfo > FastWindingCache
uint64 FastWindingCacheMeshChangeStamp = 0
TMeshAABBTree3< TriangleMeshType > * Tree
Detailed Description
template<class TriangleMeshType>
class UE::Geometry::TFastWindingTree< TriangleMeshType >
Fast Mesh Winding Number extension to a TMeshAABBTree3.
This class is an "add-on" to the AABBTree, that can compute the Fast Mesh Winding Number. This calculation requires a precomputation pass where information is cached at each tree node.
Definition at line 289 of file FastWinding.h.
Constructor & Destructor Documentation
TFastWindingTree()
template<class TriangleMeshType> UE::Geometry::TFastWindingTree< TriangleMeshType >::TFastWindingTree (TMeshAABBTree3< TriangleMeshType > * TreeToRef, bool bAutoBuild = true) inline
Definition at line 315 of file FastWinding.h.
References SetTree().
Member Function Documentation
branch_fast_winding_num()
template<class TriangleMeshType> double UE::Geometry::TFastWindingTree< TriangleMeshType >::branch_fast_winding_num (int IBox, FVector3d P) const inline private
Definition at line 386 of file FastWinding.h.
References branch_fast_winding_num(), can_use_fast_winding_cache(), evaluate_box_fast_winding_cache(), TMathUtilConstants< double >::FourPi, Tree, and UE::Geometry::VectorUtil::TriSolidAngle().
Referenced by branch_fast_winding_num(), FastWindingNumber(), and FastWindingNumber().
Build()
template<class TriangleMeshType> void UE::Geometry::TFastWindingTree< TriangleMeshType >::Build (bool bForceRebuild = true) inline
Definition at line 334 of file FastWinding.h.
References build_fast_winding_cache(), check, FastWindingCacheMeshChangeStamp, and Tree.
Referenced by FastWindingNumber(), and SetTree().
build_fast_winding_cache() [1/2]
template<class TriangleMeshType> void UE::Geometry::TFastWindingTree< TriangleMeshType >::build_fast_winding_cache () inline private
Definition at line 452 of file FastWinding.h.
References build_fast_winding_cache(), UE::Geometry::FMeshTriInfoCache::BuildTriInfoCache(), FastWindingCache, and Tree.
Referenced by Build(), build_fast_winding_cache(), and build_fast_winding_cache().
build_fast_winding_cache() [2/2]
template<class TriangleMeshType> int UE::Geometry::TFastWindingTree< TriangleMeshType >::build_fast_winding_cache (int IBox, int Depth, int TriCountThresh, TOptional< TSet< int > > & TriHash, const FMeshTriInfoCache & TriCache) inline private
Definition at line 465 of file FastWinding.h.
References build_fast_winding_cache(), check, collect_triangles(), Depth, TOptional< OptionalType >::GetValue(), TOptional< OptionalType >::IsSet(), make_box_fast_winding_cache(), and Tree.
can_use_fast_winding_cache()
template<class TriangleMeshType> bool UE::Geometry::TFastWindingTree< TriangleMeshType >::can_use_fast_winding_cache (int IBox, const FVector3d & Q) const inline private
Definition at line 540 of file FastWinding.h.
References UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::Center, Distance, FastWindingCache, FWNBeta, and UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::R.
Referenced by branch_fast_winding_num().
collect_triangles()
template<class TriangleMeshType> void UE::Geometry::TFastWindingTree< TriangleMeshType >::collect_triangles (int IBox, TSet< int > & Triangles) inline private
Definition at line 585 of file FastWinding.h.
References TSet< InElementType, KeyFuncs, Allocator >::Add(), collect_triangles(), and Tree.
Referenced by build_fast_winding_cache(), and collect_triangles().
evaluate_box_fast_winding_cache()
template<class TriangleMeshType> double UE::Geometry::TFastWindingTree< TriangleMeshType >::evaluate_box_fast_winding_cache (int IBox, const FVector3d & Q) const inline private
Definition at line 570 of file FastWinding.h.
References UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::Center, FastTriWinding::EvaluateOrder1Approx(), FastTriWinding::EvaluateOrder2Approx(), FastWindingCache, FWNApproxOrder, UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::Order1Vec, and UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::Order2Mat.
Referenced by branch_fast_winding_num().
FastWindingNumber() [1/2]
template<class TriangleMeshType> double UE::Geometry::TFastWindingTree< TriangleMeshType >::FastWindingNumber (const FVector3d & P) inline
Fast approximation of winding number using far-field approximations.
On a closed mesh the winding number will be 1 or more inside (depending on number of "winds"). Outside a closed mesh the winding number will be zero. On an open mesh, the above holds near the mesh but in the "hole" areas the value will smoothly blend from 1 to 0 over a band of width dependent on the hole extent
Definition at line 359 of file FastWinding.h.
References branch_fast_winding_num(), Build(), and Tree.
Referenced by UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute().
FastWindingNumber() [2/2]
template<class TriangleMeshType> double UE::Geometry::TFastWindingTree< TriangleMeshType >::FastWindingNumber (const FVector3d & P) const inline
Const version does not auto-build on query.
Definition at line 369 of file FastWinding.h.
References branch_fast_winding_num(), checkSlow, IsBuilt(), and Tree.
GetTree()
template<class TriangleMeshType> TMeshAABBTree3< TriangleMeshType > * UE::Geometry::TFastWindingTree< TriangleMeshType >::GetTree () const inline
Definition at line 329 of file FastWinding.h.
References Tree.
IsBuilt()
template<class TriangleMeshType> bool UE::Geometry::TFastWindingTree< TriangleMeshType >::IsBuilt () const inline
Definition at line 348 of file FastWinding.h.
References FastWindingCacheMeshChangeStamp, and Tree.
Referenced by FastWindingNumber().
IsInside()
template<class TriangleMeshType> bool UE::Geometry::TFastWindingTree< TriangleMeshType >::IsInside (const FVector3d & P, double WindingIsoThreshold = 0.5) const inline
Returns
true if fast winding number at point P is greater than winding threshold (default 0.5)
Definition at line 379 of file FastWinding.h.
References UE::Geometry::FastWindingNumber.
make_box_fast_winding_cache()
template<class TriangleMeshType> void UE::Geometry::TFastWindingTree< TriangleMeshType >::make_box_fast_winding_cache (int IBox, const TSet< int > & Triangles, const FMeshTriInfoCache & TriCache) inline private
Definition at line 558 of file FastWinding.h.
References UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::Center, check, FastTriWinding::ComputeCoeffs(), FastWindingCache, UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::Order1Vec, UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::Order2Mat, UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNInfo::R, and Tree.
Referenced by build_fast_winding_cache().
SetTree()
template<class TriangleMeshType> void UE::Geometry::TFastWindingTree< TriangleMeshType >::SetTree (TMeshAABBTree3< TriangleMeshType > * TreeToRef, bool bAutoBuild = true) inline
Definition at line 320 of file FastWinding.h.
References Build().
Referenced by TFastWindingTree().
Field Documentation
FastWindingCache
template<class TriangleMeshType> TMap<int, FWNInfo> UE::Geometry::TFastWindingTree< TriangleMeshType >::FastWindingCache private
Definition at line 301 of file FastWinding.h.
Referenced by build_fast_winding_cache(), can_use_fast_winding_cache(), evaluate_box_fast_winding_cache(), and make_box_fast_winding_cache().
FastWindingCacheMeshChangeStamp
template<class TriangleMeshType> uint64 UE::Geometry::TFastWindingTree< TriangleMeshType >::FastWindingCacheMeshChangeStamp = 0 private
Definition at line 302 of file FastWinding.h.
Referenced by Build(), and IsBuilt().
FWNApproxOrder
template<class TriangleMeshType> int UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNApproxOrder = 2
FWN approximation order.
Must be 1 or 2. 2 is more accurate, obviously.
Definition at line 313 of file FastWinding.h.
Referenced by evaluate_box_fast_winding_cache().
FWNBeta
template<class TriangleMeshType> double UE::Geometry::TFastWindingTree< TriangleMeshType >::FWNBeta = 2.0
FWN beta parameter - is 2.0 in paper.
Definition at line 308 of file FastWinding.h.
Referenced by can_use_fast_winding_cache().
Tree
template<class TriangleMeshType> TMeshAABBTree3<TriangleMeshType>* UE::Geometry::TFastWindingTree< TriangleMeshType >::Tree private
Definition at line 291 of file FastWinding.h.
Referenced by branch_fast_winding_num(), Build(), build_fast_winding_cache(), build_fast_winding_cache(), collect_triangles(), FastWindingNumber(), FastWindingNumber(), GetTree(), IsBuilt(), and make_box_fast_winding_cache().
The documentation for this class was generated from the following files:
ConvexDecomposition3.h
FastWinding.h