Unreal Engine 5.6 C++ API: Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType > Class Template Reference
Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType > Class Template Reference
#include "MetasoundInputNode.h"
Public Types
using FDataWriteReference = TDataWriteReference<DataType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TPostExecutableInputOperator (const FVertexName &InDataReferenceName, TDataWriteReference< DataType > InValue)
virtual void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Protected Member Functions
static void NoOpReset (IOperator *InOperator, const IOperator::FResetParams &InParams)
static void PostExecute (IOperator *InOperator)
Protected Attributes
FAnyDataReference DataRef
FVertexName DataReferenceName
Detailed Description
template<typename DataType>
class Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >
Definition at line 83 of file MetasoundInputNode.h.
Member Typedef Documentation
FDataWriteReference
template<typename DataType> using Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::FDataWriteReference = TDataWriteReference<DataType>
Definition at line 88 of file MetasoundInputNode.h.
Constructor & Destructor Documentation
TPostExecutableInputOperator()
template<typename DataType> Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::TPostExecutableInputOperator (const FVertexName & InDataReferenceName, TDataWriteReference< DataType > InValue) inline
Definition at line 90 of file MetasoundInputNode.h.
References DataRef, and DataReferenceName.
Referenced by Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::TResetablePostExecutableInputOperator(), Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::TResetablePostExecutableInputOperator(), and PostExecute().
Member Function Documentation
BindInputs()
template<typename DataType> virtual void Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 96 of file MetasoundInputNode.h.
References Metasound::FInputVertexInterfaceData::BindVertex(), DataRef, and DataReferenceName.
BindOutputs()
template<typename DataType> virtual void Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 101 of file MetasoundInputNode.h.
References Metasound::FOutputVertexInterfaceData::BindVertex(), DataRef, and DataReferenceName.
GetExecuteFunction()
template<typename DataType> virtual FExecuteFunction Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::GetExecuteFunction () inline override virtual
Return the execution function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be executed.
Implements Metasound::IOperator.
Definition at line 106 of file MetasoundInputNode.h.
GetPostExecuteFunction()
template<typename DataType> virtual FPostExecuteFunction Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::GetPostExecuteFunction () inline override virtual
Return the FPostExecute function to call during graph post execution.
The IOperator* argument to the FPostExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be post executed.
Implements Metasound::IOperator.
Definition at line 111 of file MetasoundInputNode.h.
References DataRef, PostExecute(), and Metasound::Write.
GetResetFunction()
template<typename DataType> virtual FResetFunction Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::GetResetFunction () inline override virtual
Return the reset function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be reset.
Implements Metasound::IOperator.
Reimplemented in Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >.
Definition at line 126 of file MetasoundInputNode.h.
References DataRef, NoOpReset(), and Metasound::Write.
NoOpReset()
template<typename DataType> void Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::NoOpReset (IOperator * InOperator, const IOperator::FResetParams & InParams) inline static protected
Definition at line 142 of file MetasoundInputNode.h.
Referenced by GetResetFunction().
PostExecute()
template<typename DataType> void Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::PostExecute (IOperator * InOperator) inline static protected
Definition at line 149 of file MetasoundInputNode.h.
References TPostExecutableInputOperator(), check, ensure, and Metasound::Value.
Referenced by GetPostExecuteFunction().
Field Documentation
DataRef
template<typename DataType> FAnyDataReference Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::DataRef protected
Definition at line 164 of file MetasoundInputNode.h.
Referenced by TPostExecutableInputOperator(), BindInputs(), BindOutputs(), GetPostExecuteFunction(), GetResetFunction(), and Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::GetResetFunction().
DataReferenceName
template<typename DataType> FVertexName Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::DataReferenceName protected
Definition at line 163 of file MetasoundInputNode.h.
Referenced by TPostExecutableInputOperator(), BindInputs(), and BindOutputs().
The documentation for this class was generated from the following file:
MetasoundInputNode.h