Unreal Engine 5.6 C++ API: FNetworkGUID Class Reference
FNetworkGUID Class Reference
Implements a globally unique identifier for network related use.
#include "NetworkGuid.h"
Public Member Functions
FNetworkGUID ()
bool IsDefault () const
A Valid but unassigned NetGUID.
bool IsDynamic () const
bool IsStatic () const
bool IsValid () const
bool operator< (const FNetworkGUID &Other) const
void Reset ()
FString ToString () const
UE_DEPRECATED (5.3, "Deprecated in favor of CreateFromIndex") static FNetworkGUID Make(int32 Seed
UE_DEPRECATED (5.3, "No longer used") FNetworkGUID(uint32 V)
UE_DEPRECATED (5.3, "No longer used") int32 ExtractNetIndex()
UE_DEPRECATED (5.3, "No longer used") void BuildFromNetIndex(int32 StaticNetIndex)
Static Public Member Functions
static FNetworkGUID CreateFromIndex (uint64 NetIndex, bool bIsStatic)
static FNetworkGUID GetDefault ()
Data Fields
union {
uint64 ObjectId
};
bool bIsStatic
Friends
uint32 GetTypeHash (const FNetworkGUID &Guid)
bool operator!= (const FNetworkGUID &X, const FNetworkGUID &Y)
FArchive & operator<< (FArchive &Ar, FNetworkGUID &G)
bool operator== (const FNetworkGUID &X, const FNetworkGUID &Y)
Detailed Description
Implements a globally unique identifier for network related use.
Definition at line 11 of file NetworkGuid.h.
Constructor & Destructor Documentation
FNetworkGUID()
FNetworkGUID::FNetworkGUID () inline
Definition at line 22 of file NetworkGuid.h.
References ObjectId.
Referenced by CreateFromIndex(), GetDefault(), GetTypeHash, operator!=, operator<(), operator<<, operator==, and UE_DEPRECATED().
Member Function Documentation
CreateFromIndex()
FNetworkGUID FNetworkGUID::CreateFromIndex (uint64 NetIndex, bool bIsStatic) inline static
Definition at line 111 of file NetworkGuid.h.
References FNetworkGUID(), bIsStatic, check, MAX_uint64, and ObjectId.
Referenced by GetDefault().
GetDefault()
FNetworkGUID FNetworkGUID::GetDefault () inline static
Definition at line 85 of file NetworkGuid.h.
References FNetworkGUID(), and CreateFromIndex().
IsDefault()
bool FNetworkGUID::IsDefault () const inline
A Valid but unassigned NetGUID.
Definition at line 80 of file NetworkGuid.h.
References ObjectId.
IsDynamic()
bool FNetworkGUID::IsDynamic () const inline
Definition at line 64 of file NetworkGuid.h.
References IsStatic(), and IsValid().
IsStatic()
bool FNetworkGUID::IsStatic () const inline
Definition at line 69 of file NetworkGuid.h.
References ObjectId.
Referenced by IsDynamic().
IsValid()
bool FNetworkGUID::IsValid () const inline
Definition at line 74 of file NetworkGuid.h.
References ObjectId.
Referenced by IsDynamic().
operator<()
bool FNetworkGUID::operator< (const FNetworkGUID & Other) const inline
Definition at line 100 of file NetworkGuid.h.
References FNetworkGUID(), ObjectId, and Other.
Reset()
void FNetworkGUID::Reset () inline
Definition at line 90 of file NetworkGuid.h.
References ObjectId.
ToString()
FString FNetworkGUID::ToString () const inline
Definition at line 95 of file NetworkGuid.h.
References ObjectId, TEXT, and UINT64_FMT.
UE_DEPRECATED() [1/4]
FNetworkGUID::UE_DEPRECATED (5. 3, "Deprecated in favor of CreateFromIndex")
UE_DEPRECATED() [2/4]
FNetworkGUID::UE_DEPRECATED (5. 3, "No longer used") inline
Definition at line 26 of file NetworkGuid.h.
References FNetworkGUID(), and ObjectId.
UE_DEPRECATED() [3/4]
FNetworkGUID::UE_DEPRECATED (5. 3, "No longer used") inline
Definition at line 53 of file NetworkGuid.h.
References ObjectId.
UE_DEPRECATED() [4/4]
FNetworkGUID::UE_DEPRECATED (5. 3, "No longer used") inline
Definition at line 47 of file NetworkGuid.h.
References ObjectId.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FNetworkGUID & Guid) friend
Definition at line 59 of file NetworkGuid.h.
References FNetworkGUID(), and Guid.
operator!=
bool operator!= (const FNetworkGUID & X, const FNetworkGUID & Y) friend
Definition at line 36 of file NetworkGuid.h.
References FNetworkGUID(), X, and Y.
operator<<
FArchive & operator<< (FArchive & Ar, FNetworkGUID & G) friend
Definition at line 41 of file NetworkGuid.h.
References FNetworkGUID(), Ar, and G.
operator==
bool operator== (const FNetworkGUID & X, const FNetworkGUID & Y) friend
Definition at line 31 of file NetworkGuid.h.
References FNetworkGUID(), X, and Y.
Field Documentation
[union]
union { ... } FNetworkGUID
bIsStatic
bool FNetworkGUID::bIsStatic
Initial value:
{
        return CreateFromIndex((uint64)Seed, bIsStatic)
Definition at line 106 of file NetworkGuid.h.
Referenced by CreateFromIndex().
ObjectId
uint64 FNetworkGUID::ObjectId
Definition at line 19 of file NetworkGuid.h.
Referenced by FNetworkGUID(), CreateFromIndex(), IsDefault(), IsStatic(), IsValid(), operator<(), Reset(), ToString(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
The documentation for this class was generated from the following file:
NetworkGuid.h