Unreal Engine 5.6 C++ API: Verse::TNativeTuple< Type > Struct Template Reference
Verse::TNativeTuple< Type > Struct Template Reference
#include "VVMNativeTuple.h"
Public Member Functions
TNativeTuple ()=default
TNativeTuple (const Type &Arg)
template<typename TArg, typename = typename TEnableIf<TIsConstructible<Type, TArg&&>::Value>::Type>
TNativeTuple (TArg &&Arg)
template<size_t Idx>
constexpr auto & Get ()
template<size_t Idx>
constexpr const auto & Get () const
Data Fields
Type First
Friends
bool operator!= (const TNativeTuple< Type > &Lhs, const TNativeTuple< Type > &Rhs)
bool operator== (const TNativeTuple< Type > &Lhs, const TNativeTuple< Type > &Rhs)
Detailed Description
template<typename Type>
struct Verse::TNativeTuple< Type >
Definition at line 59 of file VVMNativeTuple.h.
Constructor & Destructor Documentation
TNativeTuple() [1/3]
template<typename Type> Verse::TNativeTuple< Type >::TNativeTuple () default
Referenced by operator!=, and operator==.
TNativeTuple() [2/3]
template<typename Type> Verse::TNativeTuple< Type >::TNativeTuple (const Type & Arg) inline
Definition at line 65 of file VVMNativeTuple.h.
References First, and Verse::Type.
TNativeTuple() [3/3]
template<typename Type> template<typename TArg, typename = typename TEnableIf<TIsConstructible<Type, TArg&&>::Value>::Type> Verse::TNativeTuple< Type >::TNativeTuple (TArg && Arg) inline
Definition at line 71 of file VVMNativeTuple.h.
References First, and Forward().
Member Function Documentation
Get() [1/2]
template<typename Type> template<size_t Idx> auto & Verse::TNativeTuple< Type >::Get () inline constexpr
Definition at line 77 of file VVMNativeTuple.h.
References Get().
Referenced by Get(), and Get().
Get() [2/2]
template<typename Type> template<size_t Idx> const auto & Verse::TNativeTuple< Type >::Get () const inline constexpr
Definition at line 83 of file VVMNativeTuple.h.
References Get().
Friends And Related Symbol Documentation
operator!=
template<typename Type> bool operator!= (const TNativeTuple< Type > & Lhs, const TNativeTuple< Type > & Rhs) friend
Definition at line 92 of file VVMNativeTuple.h.
References TNativeTuple().
operator==
template<typename Type> bool operator== (const TNativeTuple< Type > & Lhs, const TNativeTuple< Type > & Rhs) friend
Definition at line 88 of file VVMNativeTuple.h.
References TNativeTuple().
Field Documentation
First
template<typename Type> Type Verse::TNativeTuple< Type >::First
Definition at line 61 of file VVMNativeTuple.h.
Referenced by TNativeTuple(), and TNativeTuple().
The documentation for this struct was generated from the following file:
VVMNativeTuple.h