Unreal Engine 5.6 C++ API: FMovieSceneEvaluationRange Struct Reference
FMovieSceneEvaluationRange Struct Reference
MovieScene evaluation context.
#include "MovieScenePlayback.h"
Public Member Functions
MOVIESCENE_API FMovieSceneEvaluationRange (FFrameTime InCurrentTime, FFrameTime InPreviousTime, FFrameRate InFrameRate, bool bInclusivePreviousTime=false, EPlayDirection PreferredDirection=EPlayDirection::Forwards)
Construct this range from 2 times, and whether the range should include the previous time or not.
MOVIESCENE_API FMovieSceneEvaluationRange (FFrameTime InTime, FFrameRate InFrameRate)
Construct this range from a single fixed time.
MOVIESCENE_API FMovieSceneEvaluationRange (TRange< FFrameTime > InRange, FFrameRate InFrameRate, EPlayDirection InDirection)
Construct this range from a raw range and a direction.
FORCEINLINE FFrameTime GetDelta () const
Get the absolute amount of time that has passed since the last update (will always be >= 0)
FORCEINLINE EPlayDirection GetDirection () const
Get the direction to evaluate our range.
FORCEINLINE FFrameNumber GetEvaluationFieldTime () const
Get the current time to use for looking up within an evaluation field.
FORCEINLINE TRange< FFrameNumber > GetFrameNumberRange () const
Get the range of frame numbers traversed over this evaluation range, not including partial frames.
FORCEINLINE FFrameRate GetFrameRate () const
Get the framerate that this context's times are in.
FORCEINLINE FFrameTime GetOffsetTime (FFrameTime InOffset) const
Get the current time offset by the specified amount in the direction of play.
FORCEINLINE FFrameTime GetPreviousTime () const
Get the previous time of evaluation.
FORCEINLINE TRange< FFrameTime > GetRange () const
Get the range that we should be evaluating.
FORCEINLINE FFrameTime GetTime () const
Get the current time of evaluation.
MOVIESCENE_API TRange< FFrameNumber > GetTraversedFrameNumberRange () const
Get the range of frame numbers traversed over this evaluation range by flooring the lower bound, and ceiling the upper bound.
FORCEINLINE void OverrideTime (FFrameNumber InTimeOverride)
Override the time that we're actually evaluating at.
MOVIESCENE_API void ResetRange (const TRange< FFrameTime > &NewRange)
Reset this range to a new range while retaining the current framerate and direction.
Static Public Member Functions
static MOVIESCENE_API TRange< FFrameTime > NumberRangeToTimeRange (const TRange< FFrameNumber > &InFrameTimeRange)
Convert a frame number range to a frame time range.
static MOVIESCENE_API TRange< FFrameNumber > TimeRangeToNumberRange (const TRange< FFrameTime > &InFrameTimeRange)
Convert a frame time range to a frame number range comprising all the frame numbers traversed in the range.
Protected Attributes
FFrameRate CurrentFrameRate
The framerate of the current sequence.
EPlayDirection Direction
Whether to evaluate the range forwards, or backwards.
TRange< FFrameTime > EvaluationRange
The range to evaluate.
FFrameNumber TimeOverride
Overridden current time (doesn't manipulate the actual evaluated range)
Detailed Description
MovieScene evaluation context.
Should remain bitwise copyable, and contain no external state since this has the potential to be used on a thread
Definition at line 32 of file MovieScenePlayback.h.
Constructor & Destructor Documentation
FMovieSceneEvaluationRange() [1/3]
MOVIESCENE_API FMovieSceneEvaluationRange::FMovieSceneEvaluationRange (FFrameTime InTime, FFrameRate InFrameRate)
Construct this range from a single fixed time.
References InTime.
Referenced by FMovieSceneContext::FMovieSceneContext(), FMovieSceneContext::FMovieSceneContext(), and FMovieSceneContext::FMovieSceneContext().
FMovieSceneEvaluationRange() [2/3]
MOVIESCENE_API FMovieSceneEvaluationRange::FMovieSceneEvaluationRange (TRange< FFrameTime > InRange, FFrameRate InFrameRate, EPlayDirection InDirection)
Construct this range from a raw range and a direction.
FMovieSceneEvaluationRange() [3/3]
MOVIESCENE_API FMovieSceneEvaluationRange::FMovieSceneEvaluationRange (FFrameTime InCurrentTime, FFrameTime InPreviousTime, FFrameRate InFrameRate, bool bInclusivePreviousTime = false, EPlayDirection PreferredDirection = EPlayDirection::Forwards)
Construct this range from 2 times, and whether the range should include the previous time or not.
References Forwards.
Member Function Documentation
GetDelta()
FORCEINLINE FFrameTime FMovieSceneEvaluationRange::GetDelta () const inline
Get the absolute amount of time that has passed since the last update (will always be >= 0)
Definition at line 123 of file MovieScenePlayback.h.
References EvaluationRange, and FORCEINLINE.
GetDirection()
FORCEINLINE EPlayDirection FMovieSceneEvaluationRange::GetDirection () const inline
Get the direction to evaluate our range.
Definition at line 84 of file MovieScenePlayback.h.
References Direction, and FORCEINLINE.
GetEvaluationFieldTime()
FORCEINLINE FFrameNumber FMovieSceneEvaluationRange::GetEvaluationFieldTime () const inline
Get the current time to use for looking up within an evaluation field.
Subtly different from GetTime in that it returns the previous tick for exclusive boundaries
Definition at line 106 of file MovieScenePlayback.h.
References Direction, UE::MovieScene::DiscreteExclusiveUpper(), UE::MovieScene::DiscreteInclusiveLower(), FORCEINLINE, Forwards, and GetFrameNumberRange().
GetFrameNumberRange()
FORCEINLINE TRange< FFrameNumber > FMovieSceneEvaluationRange::GetFrameNumberRange () const inline
Get the range of frame numbers traversed over this evaluation range, not including partial frames.
Definition at line 70 of file MovieScenePlayback.h.
References EvaluationRange, FORCEINLINE, and TimeRangeToNumberRange().
Referenced by GetEvaluationFieldTime().
GetFrameRate()
FORCEINLINE FFrameRate FMovieSceneEvaluationRange::GetFrameRate () const inline
Get the framerate that this context's times are in.
Returns
The framerate that all times are relative to
Definition at line 157 of file MovieScenePlayback.h.
References CurrentFrameRate, and FORCEINLINE.
GetOffsetTime()
FORCEINLINE FFrameTime FMovieSceneEvaluationRange::GetOffsetTime (FFrameTime InOffset) const inline
Get the current time offset by the specified amount in the direction of play.
Definition at line 139 of file MovieScenePlayback.h.
References Direction, FORCEINLINE, Forwards, and GetTime().
GetPreviousTime()
FORCEINLINE FFrameTime FMovieSceneEvaluationRange::GetPreviousTime () const inline
Get the previous time of evaluation.
Should not generally be used. Prefer GetRange instead.
Definition at line 131 of file MovieScenePlayback.h.
References Direction, EvaluationRange, FORCEINLINE, and Forwards.
GetRange()
FORCEINLINE TRange< FFrameTime > FMovieSceneEvaluationRange::GetRange () const inline
Get the range that we should be evaluating.
Definition at line 62 of file MovieScenePlayback.h.
References EvaluationRange, and FORCEINLINE.
GetTime()
FORCEINLINE FFrameTime FMovieSceneEvaluationRange::GetTime () const inline
Get the current time of evaluation.
Definition at line 92 of file MovieScenePlayback.h.
References Direction, EvaluationRange, FORCEINLINE, Forwards, and TimeOverride.
Referenced by GetOffsetTime(), and FMovieSceneContext::ReportOuterSectionRanges().
GetTraversedFrameNumberRange()
MOVIESCENE_API TRange< FFrameNumber > FMovieSceneEvaluationRange::GetTraversedFrameNumberRange () const
Get the range of frame numbers traversed over this evaluation range by flooring the lower bound, and ceiling the upper bound.
For example: a time range of [1.5, 5.6] will yield the equivalent of [1, 6). A time range of (2.0, 2.9) will yield the equivalent of [2,3).
NumberRangeToTimeRange()
MOVIESCENE_API TRange< FFrameTime > FMovieSceneEvaluationRange::NumberRangeToTimeRange (const TRange< FFrameNumber > & InFrameTimeRange) static
Convert a frame number range to a frame time range.
OverrideTime()
FORCEINLINE void FMovieSceneEvaluationRange::OverrideTime (FFrameNumber InTimeOverride) inline
Override the time that we're actually evaluating at.
Definition at line 148 of file MovieScenePlayback.h.
References FORCEINLINE, and TimeOverride.
ResetRange()
MOVIESCENE_API void FMovieSceneEvaluationRange::ResetRange (const TRange< FFrameTime > & NewRange)
Reset this range to a new range while retaining the current framerate and direction.
TimeRangeToNumberRange()
MOVIESCENE_API TRange< FFrameNumber > FMovieSceneEvaluationRange::TimeRangeToNumberRange (const TRange< FFrameTime > & InFrameTimeRange) static
Convert a frame time range to a frame number range comprising all the frame numbers traversed in the range.
Referenced by GetFrameNumberRange().
Field Documentation
CurrentFrameRate
FFrameRate FMovieSceneEvaluationRange::CurrentFrameRate protected
The framerate of the current sequence.
Definition at line 173 of file MovieScenePlayback.h.
Referenced by GetFrameRate().
Direction
EPlayDirection FMovieSceneEvaluationRange::Direction protected
Whether to evaluate the range forwards, or backwards.
Definition at line 176 of file MovieScenePlayback.h.
Referenced by FMovieSceneContext::ApplySectionPrePostRoll(), GetDirection(), GetEvaluationFieldTime(), GetOffsetTime(), GetPreviousTime(), GetTime(), and FMovieSceneContext::ReportOuterSectionRanges().
EvaluationRange
TRange<FFrameTime> FMovieSceneEvaluationRange::EvaluationRange protected
The range to evaluate.
Definition at line 170 of file MovieScenePlayback.h.
Referenced by FMovieSceneContext::Clamp(), GetDelta(), GetFrameNumberRange(), GetPreviousTime(), GetRange(), and GetTime().
TimeOverride
FFrameNumber FMovieSceneEvaluationRange::TimeOverride protected
Overridden current time (doesn't manipulate the actual evaluated range)
Definition at line 179 of file MovieScenePlayback.h.
Referenced by GetTime(), and OverrideTime().
The documentation for this struct was generated from the following file:
MovieScenePlayback.h