Unreal Engine 5.6 C++ API: FTrackEditorBindingIDPicker Class Reference
FTrackEditorBindingIDPicker Class Reference
#include "MovieSceneToolHelpers.h"
Public Member Functions
FTrackEditorBindingIDPicker (FMovieSceneSequenceID InLocalSequenceID, TWeakPtr< ISequencer > InSequencer)
DECLARE_EVENT_OneParam (FTrackEditorBindingIDPicker, FOnBindingPicked, FMovieSceneObjectBindingID) FOnBindingPicked &OnBindingPicked()
TSharedRef< SWidget > GetPickerMenu ()
Build menu content that allows the user to choose a binding from inside the source sequence.
void GetPickerMenu (FMenuBuilder &MenuBuilder)
Build menu content that allows the user to choose a binding from inside the source sequence.
Public Member Functions inherited from FMovieSceneObjectBindingIDPicker
FMovieSceneObjectBindingIDPicker ()
Default constructor used in contexts external to the sequencer interface.
FMovieSceneObjectBindingIDPicker (FMovieSceneSequenceID InLocalSequenceID, TWeakPtr< ISequencer > InSequencer)
Constructor used from within the sequencer interface to generate IDs from the currently focused sequence if possible (else from the root sequence).
bool IsEmpty () const
Check whether this picker actually has anything to pick.
Private Member Functions
virtual FMovieSceneObjectBindingID GetCurrentValue () const override
Get the current binding ID.
virtual UMovieSceneSequence * GetSequence () const override
Get the sequence to look up object bindings within.
virtual void SetCurrentValue (const FMovieSceneObjectBindingID &InBindingId) override
Set the current binding ID.
Private Attributes
FOnBindingPicked OnBindingPickedEvent
Additional Inherited Members
Protected Member Functions inherited from FMovieSceneObjectBindingIDPicker
virtual ~FMovieSceneObjectBindingIDPicker ()
FSlateIcon GetCurrentIcon () const
Get the icon that represents the currently assigned binding.
const FSlateBrush * GetCurrentIconBrush () const
TSharedRef< SWidget > GetCurrentItemWidget (TSharedRef< STextBlock > TextContent)
Get a widget that represents the currently chosen item.
FText GetCurrentText () const
Access the text that relates to the currently selected binding ID.
TSharedRef< SWidget > GetPickerMenu ()
Build menu content that allows the user to choose a binding from inside the source sequence.
void GetPickerMenu (FMenuBuilder &MenuBuilder)
Build menu content that allows the user to choose a binding from inside the source sequence.
EVisibility GetSpawnableIconOverlayVisibility () const
Get the visibility for the spawnable icon overlap.
FText GetToolTipText () const
Access the tooltip text that relates to the currently selected binding ID.
TSharedRef< SWidget > GetWarningWidget ()
Get a widget that represents a warning/fixup button for this binding.
virtual bool HasMultipleValues () const
Whether there are multiple values.
void Initialize ()
Initialize this class - rebuilds sequence hierarchy data and available IDs from the source sequence.
void SetBindingId (UE::MovieScene::FFixedObjectBindingID InBindingId)
Assign a new binding ID in response to user-input.
void UpdateCachedData ()
Update the cached text, tooltip and icon.
Protected Attributes inherited from FMovieSceneObjectBindingIDPicker
TArray< const UClass * > AllowedClassFilters
Classes that can be picked.
const UClass * ClassPropertyMetaClass = UObject::StaticClass()
The meta class for the property that classes must be a child-of.
TArray< const UClass * > DisallowedClassFilters
Classes that can't be picked.
const UClass * InterfaceThatMustBeImplemented = nullptr
The interface that must be implemented.
FMovieSceneSequenceID LocalSequenceID
The ID of the sequence to generate IDs relative to.
TWeakPtr< ISequencer > WeakSequencer
Optional sequencer ptr.
Detailed Description
Definition at line 1199 of file MovieSceneToolHelpers.h.
Constructor & Destructor Documentation
FTrackEditorBindingIDPicker()
FTrackEditorBindingIDPicker::FTrackEditorBindingIDPicker (FMovieSceneSequenceID InLocalSequenceID, TWeakPtr< ISequencer > InSequencer) inline
Definition at line 1202 of file MovieSceneToolHelpers.h.
References FMovieSceneObjectBindingIDPicker::FMovieSceneObjectBindingIDPicker(), and Initialize.
Referenced by DECLARE_EVENT_OneParam().
Member Function Documentation
DECLARE_EVENT_OneParam()
FTrackEditorBindingIDPicker::DECLARE_EVENT_OneParam (FTrackEditorBindingIDPicker , FOnBindingPicked , FMovieSceneObjectBindingID) & inline
Definition at line 1208 of file MovieSceneToolHelpers.h.
References FTrackEditorBindingIDPicker(), and OnBindingPickedEvent.
GetCurrentValue()
virtual FMovieSceneObjectBindingID FTrackEditorBindingIDPicker::GetCurrentValue () const inline override private virtual
Get the current binding ID.
Implements FMovieSceneObjectBindingIDPicker.
Definition at line 1220 of file MovieSceneToolHelpers.h.
GetPickerMenu() [1/2]
TSharedRef< SWidget > FMovieSceneObjectBindingIDPicker::GetPickerMenu ()
Build menu content that allows the user to choose a binding from inside the source sequence.
GetPickerMenu() [2/2]
void FMovieSceneObjectBindingIDPicker::GetPickerMenu (FMenuBuilder & MenuBuilder)
Build menu content that allows the user to choose a binding from inside the source sequence.
GetSequence()
virtual UMovieSceneSequence * FTrackEditorBindingIDPicker::GetSequence () const inline override private virtual
Get the sequence to look up object bindings within.
Only used when no sequencer is available.
Implements FMovieSceneObjectBindingIDPicker.
Definition at line 1218 of file MovieSceneToolHelpers.h.
References FMovieSceneObjectBindingIDPicker::WeakSequencer.
SetCurrentValue()
virtual void FTrackEditorBindingIDPicker::SetCurrentValue (const FMovieSceneObjectBindingID & InBindingId) inline override private virtual
Set the current binding ID.
Implements FMovieSceneObjectBindingIDPicker.
Definition at line 1219 of file MovieSceneToolHelpers.h.
References OnBindingPickedEvent.
Field Documentation
OnBindingPickedEvent
FOnBindingPicked FTrackEditorBindingIDPicker::OnBindingPickedEvent private
Definition at line 1222 of file MovieSceneToolHelpers.h.
Referenced by DECLARE_EVENT_OneParam(), and SetCurrentValue().
The documentation for this class was generated from the following file:
MovieSceneToolHelpers.h