Unreal Engine 5.6 C++ API: FCurveEditor Class Reference
FCurveEditor Class Reference
#include "CurveEditor.h"
Data Structures
struct FCurveFlipRangeSettings
Settings for Curve Flip dropdown menu selections.
Public Types
enum class ECurveFlipDirection : uint8 { Horizontal , Vertical }
Curve flip direction types.
enum class ECurveFlipRangeType : uint8 { KeyRange , CurveRange , CustomRange }
Curve Flip selection types.
Public Member Functions
FCurveEditor ()
Constructor.
FCurveEditor (const FCurveEditor &)=delete
Non-copyable (shared ptr semantics)
virtual ~FCurveEditor ()
void AddAxis (const FName &InIdentifier, TSharedPtr< FCurveEditorAxis > InAxis)
Adds a new axis to this curve editor with the specified name.
void AddBufferedCurves (const TSet< FCurveModelID > &InCurves)
Create a copy of the specified set of curves.
FCurveModelID AddCurve (TUniquePtr< FCurveModel > &&InCurve)
Add a new curve to this editor.
FCurveModelID AddCurveForTreeItem (TUniquePtr< FCurveModel > &&InCurve, FCurveEditorTreeItemID TreeItemID)
FCurveEditorToolID AddTool (TUniquePtr< ICurveEditorToolExtension > &&InTool)
FCurveEditorTreeItem * AddTreeItem (FCurveEditorTreeItemID ParentID)
Add a new tree item to this curve editor.
bool ApplyBufferedCurves (const TSet< FCurveModelID > &InCurvesToApplyTo, const bool bSwapBufferCurves)
Attempts to apply the buffered curve to the passed in curve set.
bool AreBoundTransformUpdatesSuppressed () const
void BindCommands ()
Bind UI commands that this curve editor responds to.
void BroadcastCurveChanged (FCurveModel *InCurve)
bool CanFlattenOrStraightenSelection () const
Do we currently have keys to flatten or straighten?
bool CanPaste (const FString &TextToImport) const
Returns whether the current clipboard contains objects which CurveEditor can paste.
bool CanSmartSnapSelection () const
void ClearAxes ()
Remove all custom axes definitions.
void ClearSelectionRange ()
void CopySelection () const
Copy the currently selected keys.
void CutSelection ()
Cut the currently selected keys.
void DeleteSelection ()
Delete the currently selected keys.
TSharedPtr< FCurveEditorAxis > FindAxis (const FName &InIdentifier) const
Find an axis by its ID.
FCurveModel * FindCurve (FCurveModelID CurveID) const
Find a curve by its ID.
const SCurveEditorView * FindFirstInteractiveView (FCurveModelID InCurveID) const
FCurveEditorTreeItem * FindTreeItem (FCurveEditorTreeItemID ItemID)
Finds a tree item from its ID.
const FCurveEditorTreeItem * FindTreeItem (FCurveEditorTreeItemID ItemID) const
Finds a tree item from its ID.
void FlattenSelection ()
Flatten the tangents on the selected keys.
void FlipCurve (ECurveFlipDirection Direction)
Flip the selected curve horizontally or vertically.
uint32 GetActiveCurvesSerialNumber () const
Retrieve a serial number that is incremented any time a curve is added or removed.
FCurveEditorAxisSnap GetAxisSnap () const
Returned the cached struct for snapping editing movement to a specific axis based on user preferences.
ICurveEditorBounds & GetBounds ()
Retrieve the current curve editor bounds implementation.
const ICurveEditorBounds & GetBounds () const
Retrieve the current curve editor bounds implementation.
const TArray< TUniquePtr< IBufferedCurveModel > > & GetBufferedCurves () const
Return the array of buffered curves.
TSharedPtr< FUICommandList > GetCommands () const
Retrieve this curve editor's command list.
ICurveEditorToolExtension * GetCurrentTool () const
Attempts to get the currently active tool.
const TMap< FCurveModelID, TUniquePtr< FCurveModel > > & GetCurves () const
Access all the curves currently contained in the Curve Editor regardless of visibility.
FCurveSnapMetrics GetCurveSnapMetrics (FCurveModelID CurveModel) const
Generate a utility struct for snapping values.
TAttribute< FKeyAttributes > GetDefaultKeyAttribute () const
Attribute used for determining default attributes to apply to a newly create key.
TAttribute< FKeyAttributes > GetDefaultKeyAttributes () const
TSet< FCurveModelID > GetEditedCurves () const
const TArray< TSharedRef< ICurveEditorExtension > > GetEditorExtensions () const
TAttribute< FText > GetGridLineLabelFormatXAttribute () const
TAttribute< FText > GetGridLineLabelFormatYAttribute () const
virtual void GetGridLinesX (TArray< float > &MajorGridLines, TArray< float > &MinorGridLines, TArray< FText > *MajorGridLabels) const
Called by SCurveEditorPanel to determine where to draw grid lines along the X-axis.
TOptional< float > GetGridSpacing () const
Returns the value grid line spacing state.
int32 GetNumBufferedCurves () const
Return the number of stored Buffered Curves.
TSharedPtr< SCurveEditorPanel > GetPanel () const
FCurveEditorScreenSpaceH GetPanelInputSpace () const
const TSet< FCurveModelID > & GetPinnedCurves () const
const TArray< FCurveEditorTreeItemID > & GetRootTreeItems () const
Get const access to the entire set of root tree items.
FCurveEditorSelection & GetSelection ()
const FCurveEditorSelection & GetSelection () const
TSet< FCurveModelID > GetSelectionFromTreeAndKeys () const
Return the curve model IDs that are selected in the tree or have selected keys.
UCurveEditorSettings * GetSettings () const
Retrieve this curve editor's settings.
virtual int32 GetSupportedTangentTypes ()
TSharedPtr< ITimeSliderController > GetTimeSliderController () const
Retrieve the optional Time Slider Controller that this Curve Editor may be sync'd with.
TSharedPtr< UE::CurveEditor::FPromotedFilterContainer > GetToolbarPromotedFilters () const
const TMap< FCurveEditorToolID, TUniquePtr< ICurveEditorToolExtension > > & GetToolExtensions () const
UE::CurveEditor::FTransactionManager * GetTransactionManager () const
FCurveEditorTree * GetTree ()
Access the curve editor tree.
const FCurveEditorTree * GetTree () const
Access the curve editor tree.
FCurveEditorTreeItemID GetTreeIDFromCurveID (FCurveModelID CurveID) const
Find a tree ID id associated with a CurveModelID.
FCurveEditorTreeItem & GetTreeItem (FCurveEditorTreeItemID ItemID)
Retrieve a tree item from its ID.
const FCurveEditorTreeItem & GetTreeItem (FCurveEditorTreeItemID ItemID) const
Retrieve a tree item from its ID.
const TMap< FCurveEditorTreeItemID, ECurveEditorTreeSelectionState > & GetTreeSelection () const
Retrieve the current tree selection.
ECurveEditorTreeSelectionState GetTreeSelectionState (FCurveEditorTreeItemID TreeItemID) const
Check whether this tree item is selected.
TSharedPtr< SCurveEditorView > GetView () const
const FCurveEditorZoomScaleConfig & GetZoomScaleConfig () const
void InitCurveEditor (const FCurveEditorInitParams &InInitParams)
void InvertSelection ()
bool IsActiveBufferedCurve (const TUniquePtr< IBufferedCurveModel > &BufferedCurve) const
Returns whether the buffered curve is to be acted on, ie.
bool IsBroadcasting ()
bool IsCurvePinned (FCurveModelID InCurveID) const
bool IsDoingDirectSelection () const
Whether or not we are are doign a direct selection, could be used to see why a curve model is being created or destroyed, by direct selection or by sequencer filtering?
bool IsInputSnappingEnabled () const
Check whether keys should be snapped to the input display rate when dragging around.
bool IsOutputSnappingEnabled () const
Check whether keys should be snapped to the output snap interval when dragging around.
bool IsToolActive (const FCurveEditorToolID InToolID) const
Returns true of the specified tool is currently active.
void JumpToEnd ()
void JumpToStart ()
void MakeToolActive (const FCurveEditorToolID InToolID)
Attempts to make the specified tool the active tool.
void MatchLastTangentToFirst (bool bLastToFirst=true)
Sets the last keys tangents to match the first, if bFirstToLast is false do the opposite.
FCurveEditor & operator= (const FCurveEditor &)=delete
void PasteKeys (UE::CurveEditor::FKeyPasteArgs InArgs={})
Pastes keys.
void PinCurve (FCurveModelID InCurveID)
virtual void PostRedo (bool bSuccess) override
Signal that client should run any PostRedo code.
virtual void PostUndo (bool bSuccess) override
Signal that client should run any PostUndo code.
void RemoveAllCurves ()
Remove all curves from this editor.
void RemoveAllTreeItems ()
Remove all tree items from the curve editor.
void RemoveAxis (const FName &InIdentifier)
Remove the axis with the specified ID.
void RemoveCurve (FCurveModelID InCurveID)
Remove a curve from this editor.
void RemoveFromTreeSelection (TArrayView< const FCurveEditorTreeItemID > TreeItems)
Removes items from the current tree selection.
void RemoveTreeItem (FCurveEditorTreeItemID ItemID)
Remove a tree item from the curve editor.
void ResetMinMaxes ()
void ResumeBroadcast ()
void SelectAllKeys ()
Selection.
void SelectBackward ()
void SelectForward ()
void SelectNone ()
void SetAxisSnap (const FCurveEditorAxisSnap &InAxisSnap)
void SetBounds (TUniquePtr< ICurveEditorBounds > &&InBounds)
Assign a new bounds container to this curve editor.
void SetCurveColorsForSelected ()
Pick a curve color and set on selected.
void SetPanel (TSharedPtr< SCurveEditorPanel > InPanel)
void SetRandomCurveColorsForSelected ()
Set random curve colors.
void SetSelectionRangeEnd ()
void SetSelectionRangeStart ()
Selection range for ie.
void SetTimeSliderController (TSharedPtr< ITimeSliderController > InTimeSliderController)
void SetTreeSelection (TArray< FCurveEditorTreeItemID > &&TreeItems)
Set the tree selection directly.
void SetView (TSharedPtr< SCurveEditorView > InPanel)
bool ShouldAutoFrame () const
Check whether this curve editor can automatically zoom to the current selection.
void SmartSnapSelection ()
Snaps the selected keys to their nearest whole frames and positions them on the frame intersection with the frame.
void SnapToSelectedKey ()
Snap time to the first selected key.
void StepBackward ()
void StepForward ()
Step forward/backward, jump to start/end.
void StepToNextKey ()
Step to next or previous key from the current time.
void StepToPreviousKey ()
void StraightenSelection ()
Straighten the tangents on the selected keys.
void SuppressBoundTransformUpdates (bool bSuppress)
void SuspendBroadcast ()
Suspend or resume broadcast of curve array changing.
void ToggleExpandCollapseNodes (bool bRecursive)
Toggle the expansion state of the selected nodes or all nodes if none selected.
void ToggleInputSnapping ()
void ToggleOutputSnapping ()
void TranslateSelectedKeys (double SecondsToAdd)
Nudge left or right.
void TranslateSelectedKeysLeft ()
void TranslateSelectedKeysRight ()
UE_DEPRECATED (5.6, "Use the version that takes FKeyPasteArg instead.") void PasteKeys(TSet< FCurveModelID > CurveModelIDs
Paste keys.
void UnpinCurve (FCurveModelID InCurveID)
void UpdateGeometry (const FGeometry &CurrentGeometry)
Called by SCurveEditorPanel to update the allocated geometry for this curve editor.
void ZoomToFit (EAxisList::Type Axes=EAxisList::All)
Zoom the curve editor to fit all the selected curves (or all curves if none selected)
void ZoomToFitAll (EAxisList::Type Axes=EAxisList::All)
Zoom the curve editor to fit all the currently visible curves.
void ZoomToFitCurves (TArrayView< const FCurveModelID > CurveModelIDs, EAxisList::Type Axes=EAxisList::All)
Zoom the curve editor to fit the requested curves.
void ZoomToFitSelection (EAxisList::Type Axes=EAxisList::All)
Zoom the curve editor to fit all the current key selection.
Public Member Functions inherited from FEditorUndoClient
virtual UNREALED_API ~FEditorUndoClient ()
Always unregister for undo on destruction, just in case.
virtual FString GetTransactionContext () const
Return the transaction context for this client.
virtual bool MatchesContext (const FTransactionContext &InContext, const TArray< TPair< UObject *, FTransactionObjectEvent > > &TransactionObjectContexts) const
Called to see if the context of the current undo/redo operation is a match for the client Default state matching old context-less undo is Context="" and PrimaryObject=NULL.
Public Member Functions inherited from TSharedFromThis< FCurveEditor >
TSharedRef< FCurveEditor, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FCurveEditor, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static void FlipCurveHorizontal (TArray< FKeyPosition > &AllKeyPositions, TArray< FKeyAttributes > &AllKeyAttributes, ECurveFlipRangeType RangeType, float InRangeMin, float InRangeMax, double CurveMinTime, double CurveMaxTime)
static void FlipCurveVertical (TArray< FKeyPosition > &AllKeyPositions, TArray< FKeyAttributes > &AllKeyAttributes, ECurveFlipRangeType RangeType, float InRangeMin, float InRangeMax, double CurveMinVal, double CurveMaxVal)
Data Fields
const bool bInOverwriteRange = false)
TAttribute< FKeyAttributes > DefaultKeyAttributes
Attribute used for determining default attributes to apply to a newly create key.
TAttribute< TOptional< float > > FixedGridSpacingAttribute
Attribute used to retrieve the current value-axis grid line state.
TAttribute< FText > GridLineLabelFormatXAttribute
Grid line label text format strings for the X and Y axis.
TAttribute< FText > GridLineLabelFormatYAttribute
FCurveFlipRangeSettings HorizontalCurveFlipRangeSettings
TAttribute< bool > InputSnapEnabledAttribute
Attribute used to determine if we should snap input values.
TAttribute< FFrameRate > InputSnapRateAttribute
Attribute used to retrieve the current input snap rate (also used for display)
TAttribute< double > InputZoomToFitPadding
Padding applied to zoom-to-fit the input.
FOnActiveToolChanged OnActiveToolChangedDelegate
Delegate that is invoked when a tool becomes active.
FOnCurveArrayChanged OnCurveArrayChanged
Delegate that's broadcast when the curve display changes.
FOnSetBoolean OnInputSnapEnabledChanged
Delegate that is invoked when the input snapping has been enabled/disabled.
FOnSetBoolean OnOutputSnapEnabledChanged
Delegate that is invoked when the output snapping has been enabled/disabled.
TAttribute< bool > OutputSnapEnabledAttribute
Attribute used to determine if we should snap output values.
TAttribute< double > OutputZoomToFitPadding
Padding applied to zoom-to-fit the output.
FCurveEditorSelection Selection
Container holding the current key/tangent selection.
FCurveFlipRangeSettings VerticalCurveFlipRangeSettings
Protected Member Functions
void ApplyBufferedCurveToTarget (const IBufferedCurveModel *BufferedCurve, FCurveModel *TargetCurve)
Apply a specific buffered curve to a specific target curve.
void ConstructXGridLines (TArray< float > &MajorGridLines, TArray< float > &MinorGridLines, TArray< FText > *MajorGridLabels) const
Construct grid lines along the current display frame rate or time-base.
bool CopyBufferCurveToCurveID (const UCurveEditorCopyableCurveKeys *InSourceCurve, const FCurveModelID InTargetCurve, TOptional< double > InTimeOffset, UE::CurveEditor::ECurveEditorPasteMode InMode, UE::CurveEditor::ECurveEditorPasteFlags InFlags)
void GetChildCurveModelIDs (const FCurveEditorTreeItemID TreeItemID, TSet< FCurveModelID > &CurveModelIDs) const
TSet< FCurveModelID > GetTargetCurvesForPaste () const
void ImportCopyBufferFromText (const FString &TextToImport, TArray< UCurveEditorCopyBuffer * > &ImportedCopyBuffers) const
void OnAxisSnappingChanged ()
void OnCustomColorsChanged ()
UE_DEPRECATED (5.6, "Use the version that takes in ECurveEditorPasteMode and ECurveEditorPasteFlags instead.") bool CopyBufferCurveToCurveID(const UCurveEditorCopyableCurveKeys *InSourceCurve
void ZoomToFitInternal (EAxisList::Type Axes, const TMap< FCurveModelID, FKeyHandleSet > &CurveKeySet)
Internal zoom to fit implementation.
Protected Member Functions inherited from TSharedFromThis< FCurveEditor >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
uint32 ActiveCurvesSerialNumber
A serial number that is incremented any time the currently active set of curves are changed.
TOptional< FCurveEditorToolID > ActiveTool
The currently active tool if any.
FCurveEditorAxisSnap AxisSnapMetrics
Track which axis UI movements should be snapped to (where applicable) based on limitations imposed by the UI.
bool bBoundTransformUpdatesSuppressed
Should attempts to update the bounds of each curve be ignored?
const FCurveModelID TOptional< double > const bool bInAddToSelection
const FCurveModelID TOptional< double > const bool const bool bInOverwriteRange
TUniquePtr< ICurveEditorBounds > Bounds
Curve editor bounds implementation.
TArray< TUniquePtr< IBufferedCurveModel > > BufferedCurves
Buffered Curves.
TMultiMap< FCurveModelID, FCurveModelID > ChildCurves
Map of child curves.
TSharedPtr< FUICommandList > CommandList
UI command list of actions mapped to this curve editor.
TMap< FCurveModelID, TUniquePtr< FCurveModel > > CurveData
Map from curve model ID to the actual curve model.
TSortedMap< FName, TSharedPtr< FCurveEditorAxis >, FDefaultAllocator, FNameFastLess > CustomAxes
Map of all axes.
TArray< TSharedRef< ICurveEditorExtension > > EditorExtensions
List of editor extensions we have initialized.
const FCurveModelID InTargetCurve
const FCurveModelID TOptional< double > InTimeOffset
TSet< FCurveModelID > PinnedCurves
Set of pinned curve models.
UCurveEditorSettings * Settings
Curve editor settings object.
int32 SuspendBroadcastCount
Counter to suspend broadcasting of changed delegates.
TMap< FCurveEditorToolID, TUniquePtr< ICurveEditorToolExtension > > ToolExtensions
List of tool extensions we have initialized.
TUniquePtr< UE::CurveEditor::FTransactionManager > TransactionManager
Orchestrates transaction that affect this curve editor.
FCurveEditorTree Tree
Hierarchical information pertaining to curve data.
TMap< FCurveModelID, FCurveEditorTreeItemID > TreeIDByCurveID
Map from curve model ID to its originating tree item.
TWeakPtr< SCurveEditorPanel > WeakPanel
TWeakPtr< ITimeSliderController > WeakTimeSliderController
Optional external Time Slider controller to sync with.
TWeakPtr< SCurveEditorView > WeakView
TAttribute< const FCurveEditorZoomScaleConfig * > ZoomScalingAttr
The zoom scale config that was passed in to us in InitCurveEditor.
Private Attributes
FVector2D CachedPhysicalSize
Cached physical size of the panel representing this editor.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FCurveEditor >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 77 of file CurveEditor.h.
Member Enumeration Documentation
ECurveFlipDirection
enum class FCurveEditor::ECurveFlipDirection : uint8 strong
Curve flip direction types.
Enumerator
Horizontal
Vertical
Definition at line 508 of file CurveEditor.h.
ECurveFlipRangeType
enum class FCurveEditor::ECurveFlipRangeType : uint8 strong
Curve Flip selection types.
Enumerator
KeyRange
CurveRange
CustomRange
Definition at line 515 of file CurveEditor.h.
Constructor & Destructor Documentation
FCurveEditor() [1/2]
FCurveEditor::FCurveEditor ()
Constructor.
Referenced by FCurveEditor(), and operator=().
FCurveEditor() [2/2]
FCurveEditor::FCurveEditor (const FCurveEditor &) delete
Non-copyable (shared ptr semantics)
References FCurveEditor().
~FCurveEditor()
virtual FCurveEditor::~FCurveEditor () virtual
Member Function Documentation
AddAxis()
void FCurveEditor::AddAxis (const FName & InIdentifier, TSharedPtr< FCurveEditorAxis > InAxis)
Adds a new axis to this curve editor with the specified name.
Note
Calling this function with the same identifier as a previously registered axis will overwrite the axis with the new one.
Parameters
InIdentifier A unique identifer for this axis that can be subsequently used to look up this axis
InAxis The axis definition
AddBufferedCurves()
void FCurveEditor::AddBufferedCurves (const TSet< FCurveModelID > & InCurves)
Create a copy of the specified set of curves.
AddCurve()
FCurveModelID FCurveEditor::AddCurve (TUniquePtr< FCurveModel > && InCurve)
Add a new curve to this editor.
AddCurveForTreeItem()
FCurveModelID FCurveEditor::AddCurveForTreeItem (TUniquePtr< FCurveModel > && InCurve, FCurveEditorTreeItemID TreeItemID)
AddTool()
FCurveEditorToolID FCurveEditor::AddTool (TUniquePtr< ICurveEditorToolExtension > && InTool)
AddTreeItem()
FCurveEditorTreeItem * FCurveEditor::AddTreeItem (FCurveEditorTreeItemID ParentID)
Add a new tree item to this curve editor.
ApplyBufferedCurves()
bool FCurveEditor::ApplyBufferedCurves (const TSet< FCurveModelID > & InCurvesToApplyTo, const bool bSwapBufferCurves)
Attempts to apply the buffered curve to the passed in curve set.
Returns true on success.
ApplyBufferedCurveToTarget()
void FCurveEditor::ApplyBufferedCurveToTarget (const IBufferedCurveModel * BufferedCurve, FCurveModel * TargetCurve) protected
Apply a specific buffered curve to a specific target curve.
AreBoundTransformUpdatesSuppressed()
bool FCurveEditor::AreBoundTransformUpdatesSuppressed () const inline
Definition at line 350 of file CurveEditor.h.
References bBoundTransformUpdatesSuppressed.
BindCommands()
void FCurveEditor::BindCommands ()
Bind UI commands that this curve editor responds to.
BroadcastCurveChanged()
void FCurveEditor::BroadcastCurveChanged (FCurveModel * InCurve)
CanFlattenOrStraightenSelection()
bool FCurveEditor::CanFlattenOrStraightenSelection () const
Do we currently have keys to flatten or straighten?
CanPaste()
bool FCurveEditor::CanPaste (const FString & TextToImport) const
Returns whether the current clipboard contains objects which CurveEditor can paste.
CanSmartSnapSelection()
bool FCurveEditor::CanSmartSnapSelection () const
Returns
Whether there is any key selection.
ClearAxes()
void FCurveEditor::ClearAxes ()
Remove all custom axes definitions.
ClearSelectionRange()
void FCurveEditor::ClearSelectionRange ()
ConstructXGridLines()
void FCurveEditor::ConstructXGridLines (TArray< float > & MajorGridLines, TArray< float > & MinorGridLines, TArray< FText > * MajorGridLabels) const protected
Construct grid lines along the current display frame rate or time-base.
Referenced by GetGridLinesX().
CopyBufferCurveToCurveID()
bool FCurveEditor::CopyBufferCurveToCurveID (const UCurveEditorCopyableCurveKeys * InSourceCurve, const FCurveModelID InTargetCurve, TOptional< double > InTimeOffset, UE::CurveEditor::ECurveEditorPasteMode InMode, UE::CurveEditor::ECurveEditorPasteFlags InFlags) protected
References CopyBufferCurveToCurveID(), InTargetCurve, and InTimeOffset.
Referenced by CopyBufferCurveToCurveID().
CopySelection()
void FCurveEditor::CopySelection () const
Copy the currently selected keys.
CutSelection()
void FCurveEditor::CutSelection ()
Cut the currently selected keys.
DeleteSelection()
void FCurveEditor::DeleteSelection ()
Delete the currently selected keys.
FindAxis()
TSharedPtr< FCurveEditorAxis > FCurveEditor::FindAxis (const FName & InIdentifier) const
Find an axis by its ID.
FindCurve()
FCurveModel * FCurveEditor::FindCurve (FCurveModelID CurveID) const
Find a curve by its ID.
Returns
a ptr to the curve if found, nullptr otherwise
Referenced by UE::CurveEditor::MirrorOnMidpoint(), UE::CurveEditor::ModifyCurves(), and UE::CurveEditor::RecomputeMirroringParallel().
FindFirstInteractiveView()
const SCurveEditorView * FCurveEditor::FindFirstInteractiveView (FCurveModelID InCurveID) const
FindTreeItem() [1/2]
FCurveEditorTreeItem * FCurveEditor::FindTreeItem (FCurveEditorTreeItemID ItemID)
Finds a tree item from its ID.
FindTreeItem() [2/2]
const FCurveEditorTreeItem * FCurveEditor::FindTreeItem (FCurveEditorTreeItemID ItemID) const
Finds a tree item from its ID.
FlattenSelection()
void FCurveEditor::FlattenSelection ()
Flatten the tangents on the selected keys.
FlipCurve()
void FCurveEditor::FlipCurve (ECurveFlipDirection Direction)
Flip the selected curve horizontally or vertically.
FlipCurveHorizontal()
void FCurveEditor::FlipCurveHorizontal (TArray< FKeyPosition > & AllKeyPositions, TArray< FKeyAttributes > & AllKeyAttributes, ECurveFlipRangeType RangeType, float InRangeMin, float InRangeMax, double CurveMinTime, double CurveMaxTime) static
FlipCurveVertical()
void FCurveEditor::FlipCurveVertical (TArray< FKeyPosition > & AllKeyPositions, TArray< FKeyAttributes > & AllKeyAttributes, ECurveFlipRangeType RangeType, float InRangeMin, float InRangeMax, double CurveMinVal, double CurveMaxVal) static
GetActiveCurvesSerialNumber()
uint32 FCurveEditor::GetActiveCurvesSerialNumber () const inline
Retrieve a serial number that is incremented any time a curve is added or removed.
Definition at line 482 of file CurveEditor.h.
References ActiveCurvesSerialNumber.
GetAxisSnap()
FCurveEditorAxisSnap FCurveEditor::GetAxisSnap () const inline
Returned the cached struct for snapping editing movement to a specific axis based on user preferences.
Definition at line 343 of file CurveEditor.h.
References AxisSnapMetrics.
GetBounds() [1/2]
ICurveEditorBounds & FCurveEditor::GetBounds () inline
Retrieve the current curve editor bounds implementation.
Definition at line 198 of file CurveEditor.h.
References Bounds.
GetBounds() [2/2]
const ICurveEditorBounds & FCurveEditor::GetBounds () const inline
Retrieve the current curve editor bounds implementation.
Definition at line 194 of file CurveEditor.h.
References Bounds.
GetBufferedCurves()
const TArray< TUniquePtr< IBufferedCurveModel > > & FCurveEditor::GetBufferedCurves () const inline
Return the array of buffered curves.
Definition at line 365 of file CurveEditor.h.
References BufferedCurves.
GetChildCurveModelIDs()
void FCurveEditor::GetChildCurveModelIDs (const FCurveEditorTreeItemID TreeItemID, TSet< FCurveModelID > & CurveModelIDs) const protected
References GetChildCurveModelIDs().
Referenced by GetChildCurveModelIDs().
GetCommands()
TSharedPtr< FUICommandList > FCurveEditor::GetCommands () const inline
Retrieve this curve editor's command list.
Definition at line 210 of file CurveEditor.h.
References CommandList.
GetCurrentTool()
ICurveEditorToolExtension * FCurveEditor::GetCurrentTool () const
Attempts to get the currently active tool.
Will return nullptr if there is no active tool. Do not store a reference to this returned pointer, instead only store FCurveEditorToolIDs!
GetCurves()
const TMap< FCurveModelID, TUniquePtr< FCurveModel > > & FCurveEditor::GetCurves () const
Access all the curves currently contained in the Curve Editor regardless of visibility.
GetCurveSnapMetrics()
FCurveSnapMetrics FCurveEditor::GetCurveSnapMetrics (FCurveModelID CurveModel) const
Generate a utility struct for snapping values.
GetDefaultKeyAttribute()
TAttribute< FKeyAttributes > FCurveEditor::GetDefaultKeyAttribute () const inline
Attribute used for determining default attributes to apply to a newly create key.
Definition at line 357 of file CurveEditor.h.
References DefaultKeyAttributes.
GetDefaultKeyAttributes()
TAttribute< FKeyAttributes > FCurveEditor::GetDefaultKeyAttributes () const inline
Definition at line 347 of file CurveEditor.h.
References DefaultKeyAttributes.
GetEditedCurves()
TSet< FCurveModelID > FCurveEditor::GetEditedCurves () const
GetEditorExtensions()
const TArray< TSharedRef< ICurveEditorExtension > > FCurveEditor::GetEditorExtensions () const inline
Definition at line 376 of file CurveEditor.h.
References EditorExtensions.
GetGridLineLabelFormatXAttribute()
TAttribute< FText > FCurveEditor::GetGridLineLabelFormatXAttribute () const inline
Definition at line 345 of file CurveEditor.h.
References GridLineLabelFormatXAttribute.
GetGridLineLabelFormatYAttribute()
TAttribute< FText > FCurveEditor::GetGridLineLabelFormatYAttribute () const inline
Definition at line 346 of file CurveEditor.h.
References GridLineLabelFormatYAttribute.
GetGridLinesX()
virtual void FCurveEditor::GetGridLinesX (TArray< float > & MajorGridLines, TArray< float > & MinorGridLines, TArray< FText > * MajorGridLabels) const inline virtual
Called by SCurveEditorPanel to determine where to draw grid lines along the X-axis.
This allows synchronization with an external data source (such as Sequencer's Timeline ticker). A similar function for the Y grid lines is not provided due to the Curve Editor's ability to have multiple views with repeated gridlines and values.
Definition at line 644 of file CurveEditor.h.
References ConstructXGridLines().
GetGridSpacing()
TOptional< float > FCurveEditor::GetGridSpacing () const inline
Returns the value grid line spacing state.
Definition at line 338 of file CurveEditor.h.
References FixedGridSpacingAttribute.
GetNumBufferedCurves()
int32 FCurveEditor::GetNumBufferedCurves () const inline
Return the number of stored Buffered Curves.
Definition at line 363 of file CurveEditor.h.
References BufferedCurves.
GetPanel()
TSharedPtr< SCurveEditorPanel > FCurveEditor::GetPanel () const
GetPanelInputSpace()
FCurveEditorScreenSpaceH FCurveEditor::GetPanelInputSpace () const
GetPinnedCurves()
const TSet< FCurveModelID > & FCurveEditor::GetPinnedCurves () const inline
Definition at line 311 of file CurveEditor.h.
References PinnedCurves.
GetRootTreeItems()
const TArray< FCurveEditorTreeItemID > & FCurveEditor::GetRootTreeItems () const
Get const access to the entire set of root tree items.
GetSelection() [1/2]
FCurveEditorSelection & FCurveEditor::GetSelection () inline
Definition at line 327 of file CurveEditor.h.
References Selection.
GetSelection() [2/2]
const FCurveEditorSelection & FCurveEditor::GetSelection () const inline
Definition at line 328 of file CurveEditor.h.
References Selection.
GetSelectionFromTreeAndKeys()
TSet< FCurveModelID > FCurveEditor::GetSelectionFromTreeAndKeys () const
Return the curve model IDs that are selected in the tree or have selected keys.
GetSettings()
UCurveEditorSettings * FCurveEditor::GetSettings () const inline
Retrieve this curve editor's settings.
Definition at line 321 of file CurveEditor.h.
References Settings.
GetSupportedTangentTypes()
virtual int32 FCurveEditor::GetSupportedTangentTypes () virtual
GetTargetCurvesForPaste()
TSet< FCurveModelID > FCurveEditor::GetTargetCurvesForPaste () const protected
GetTimeSliderController()
TSharedPtr< ITimeSliderController > FCurveEditor::GetTimeSliderController () const inline
Retrieve the optional Time Slider Controller that this Curve Editor may be sync'd with.
Definition at line 206 of file CurveEditor.h.
References WeakTimeSliderController.
GetToolbarPromotedFilters()
TSharedPtr< UE::CurveEditor::FPromotedFilterContainer > FCurveEditor::GetToolbarPromotedFilters () const
Returns
The object managing which filters are promoted to the toolbar for quick access.
GetToolExtensions()
const TMap< FCurveEditorToolID, TUniquePtr< ICurveEditorToolExtension > > & FCurveEditor::GetToolExtensions () const inline
Definition at line 381 of file CurveEditor.h.
References ToolExtensions.
GetTransactionManager()
UE::CurveEditor::FTransactionManager * FCurveEditor::GetTransactionManager () const inline
Definition at line 141 of file CurveEditor.h.
References TransactionManager.
GetTree() [1/2]
FCurveEditorTree * FCurveEditor::GetTree () inline
Access the curve editor tree.
Definition at line 457 of file CurveEditor.h.
References Tree.
GetTree() [2/2]
const FCurveEditorTree * FCurveEditor::GetTree () const inline
Access the curve editor tree.
Definition at line 465 of file CurveEditor.h.
References Tree.
GetTreeIDFromCurveID()
FCurveEditorTreeItemID FCurveEditor::GetTreeIDFromCurveID (FCurveModelID CurveID) const
Find a tree ID id associated with a CurveModelID.
GetTreeItem() [1/2]
FCurveEditorTreeItem & FCurveEditor::GetTreeItem (FCurveEditorTreeItemID ItemID)
Retrieve a tree item from its ID.
GetTreeItem() [2/2]
const FCurveEditorTreeItem & FCurveEditor::GetTreeItem (FCurveEditorTreeItemID ItemID) const
Retrieve a tree item from its ID.
GetTreeSelection()
const TMap< FCurveEditorTreeItemID, ECurveEditorTreeSelectionState > & FCurveEditor::GetTreeSelection () const
Retrieve the current tree selection.
GetTreeSelectionState()
ECurveEditorTreeSelectionState FCurveEditor::GetTreeSelectionState (FCurveEditorTreeItemID TreeItemID) const
Check whether this tree item is selected.
GetView()
TSharedPtr< SCurveEditorView > FCurveEditor::GetView () const
GetZoomScaleConfig()
const FCurveEditorZoomScaleConfig & FCurveEditor::GetZoomScaleConfig () const
Returns
The config to use for scaling the zooms.
ImportCopyBufferFromText()
void FCurveEditor::ImportCopyBufferFromText (const FString & TextToImport, TArray< UCurveEditorCopyBuffer * > & ImportedCopyBuffers) const protected
InitCurveEditor()
void FCurveEditor::InitCurveEditor (const FCurveEditorInitParams & InInitParams)
InvertSelection()
void FCurveEditor::InvertSelection ()
IsActiveBufferedCurve()
bool FCurveEditor::IsActiveBufferedCurve (const TUniquePtr< IBufferedCurveModel > & BufferedCurve) const
Returns whether the buffered curve is to be acted on, ie.
selected, in the tree view or with selected keys
IsBroadcasting()
bool FCurveEditor::IsBroadcasting () inline
Definition at line 671 of file CurveEditor.h.
References SuspendBroadcastCount.
IsCurvePinned()
bool FCurveEditor::IsCurvePinned (FCurveModelID InCurveID) const
IsDoingDirectSelection()
bool FCurveEditor::IsDoingDirectSelection () const inline
Whether or not we are are doign a direct selection, could be used to see why a curve model is being created or destroyed, by direct selection or by sequencer filtering?
Definition at line 473 of file CurveEditor.h.
References Tree.
IsInputSnappingEnabled()
bool FCurveEditor::IsInputSnappingEnabled () const
Check whether keys should be snapped to the input display rate when dragging around.
IsOutputSnappingEnabled()
bool FCurveEditor::IsOutputSnappingEnabled () const
Check whether keys should be snapped to the output snap interval when dragging around.
IsToolActive()
bool FCurveEditor::IsToolActive (const FCurveEditorToolID InToolID) const
Returns true of the specified tool is currently active.
JumpToEnd()
void FCurveEditor::JumpToEnd ()
JumpToStart()
void FCurveEditor::JumpToStart ()
MakeToolActive()
void FCurveEditor::MakeToolActive (const FCurveEditorToolID InToolID)
Attempts to make the specified tool the active tool.
This will cancel the current tool if there is one.
MatchLastTangentToFirst()
void FCurveEditor::MatchLastTangentToFirst (bool bLastToFirst = true)
Sets the last keys tangents to match the first, if bFirstToLast is false do the opposite.
OnAxisSnappingChanged()
void FCurveEditor::OnAxisSnappingChanged () protected
OnCustomColorsChanged()
void FCurveEditor::OnCustomColorsChanged () protected
operator=()
FCurveEditor & FCurveEditor::operator= (const FCurveEditor &) delete
References FCurveEditor().
PasteKeys()
void FCurveEditor::PasteKeys (UE::CurveEditor::FKeyPasteArgs InArgs = {})
Pastes keys.
Parameters
CurveModelIds Only the curve model IDs specified in this set. If empty, paste all in the clipboard.
Flags Flags that modify the operation.
References PasteKeys().
Referenced by PasteKeys().
PinCurve()
void FCurveEditor::PinCurve (FCurveModelID InCurveID)
PostRedo()
virtual void FCurveEditor::PostRedo (bool bSuccess) override virtual
Signal that client should run any PostRedo code.
Parameters
bSuccess If true than redo succeeded, false if redo failed
Reimplemented from FEditorUndoClient.
PostUndo()
virtual void FCurveEditor::PostUndo (bool bSuccess) override virtual
Signal that client should run any PostUndo code.
Parameters
bSuccess If true than undo succeeded, false if undo failed
Reimplemented from FEditorUndoClient.
RemoveAllCurves()
void FCurveEditor::RemoveAllCurves ()
Remove all curves from this editor.
RemoveAllTreeItems()
void FCurveEditor::RemoveAllTreeItems ()
Remove all tree items from the curve editor.
RemoveAxis()
void FCurveEditor::RemoveAxis (const FName & InIdentifier)
Remove the axis with the specified ID.
RemoveCurve()
void FCurveEditor::RemoveCurve (FCurveModelID InCurveID)
Remove a curve from this editor.
RemoveFromTreeSelection()
void FCurveEditor::RemoveFromTreeSelection (TArrayView< const FCurveEditorTreeItemID > TreeItems)
Removes items from the current tree selection.
RemoveTreeItem()
void FCurveEditor::RemoveTreeItem (FCurveEditorTreeItemID ItemID)
Remove a tree item from the curve editor.
ResetMinMaxes()
void FCurveEditor::ResetMinMaxes ()
ResumeBroadcast()
void FCurveEditor::ResumeBroadcast () inline
Definition at line 665 of file CurveEditor.h.
References checkf, SuspendBroadcastCount, and TEXT.
SelectAllKeys()
void FCurveEditor::SelectAllKeys ()
Selection.
SelectBackward()
void FCurveEditor::SelectBackward ()
SelectForward()
void FCurveEditor::SelectForward ()
SelectNone()
void FCurveEditor::SelectNone ()
SetAxisSnap()
void FCurveEditor::SetAxisSnap (const FCurveEditorAxisSnap & InAxisSnap) inline
Definition at line 344 of file CurveEditor.h.
References AxisSnapMetrics.
SetBounds()
void FCurveEditor::SetBounds (TUniquePtr< ICurveEditorBounds > && InBounds)
Assign a new bounds container to this curve editor.
SetCurveColorsForSelected()
void FCurveEditor::SetCurveColorsForSelected ()
Pick a curve color and set on selected.
SetPanel()
void FCurveEditor::SetPanel (TSharedPtr< SCurveEditorPanel > InPanel)
SetRandomCurveColorsForSelected()
void FCurveEditor::SetRandomCurveColorsForSelected ()
Set random curve colors.
SetSelectionRangeEnd()
void FCurveEditor::SetSelectionRangeEnd ()
SetSelectionRangeStart()
void FCurveEditor::SetSelectionRangeStart ()
Selection range for ie.
looping playback
SetTimeSliderController()
void FCurveEditor::SetTimeSliderController (TSharedPtr< ITimeSliderController > InTimeSliderController) inline
Definition at line 202 of file CurveEditor.h.
References WeakTimeSliderController.
SetTreeSelection()
void FCurveEditor::SetTreeSelection (TArray< FCurveEditorTreeItemID > && TreeItems)
Set the tree selection directly.
SetView()
void FCurveEditor::SetView (TSharedPtr< SCurveEditorView > InPanel)
ShouldAutoFrame()
bool FCurveEditor::ShouldAutoFrame () const
Check whether this curve editor can automatically zoom to the current selection.
SmartSnapSelection()
void FCurveEditor::SmartSnapSelection ()
Snaps the selected keys to their nearest whole frames and positions them on the frame intersection with the frame.
SnapToSelectedKey()
void FCurveEditor::SnapToSelectedKey ()
Snap time to the first selected key.
StepBackward()
void FCurveEditor::StepBackward ()
StepForward()
void FCurveEditor::StepForward ()
Step forward/backward, jump to start/end.
StepToNextKey()
void FCurveEditor::StepToNextKey ()
Step to next or previous key from the current time.
StepToPreviousKey()
void FCurveEditor::StepToPreviousKey ()
StraightenSelection()
void FCurveEditor::StraightenSelection ()
Straighten the tangents on the selected keys.
SuppressBoundTransformUpdates()
void FCurveEditor::SuppressBoundTransformUpdates (bool bSuppress) inline
Definition at line 349 of file CurveEditor.h.
References bBoundTransformUpdatesSuppressed.
SuspendBroadcast()
void FCurveEditor::SuspendBroadcast () inline
Suspend or resume broadcast of curve array changing.
Definition at line 660 of file CurveEditor.h.
References SuspendBroadcastCount.
ToggleExpandCollapseNodes()
void FCurveEditor::ToggleExpandCollapseNodes (bool bRecursive)
Toggle the expansion state of the selected nodes or all nodes if none selected.
ToggleInputSnapping()
void FCurveEditor::ToggleInputSnapping ()
ToggleOutputSnapping()
void FCurveEditor::ToggleOutputSnapping ()
TranslateSelectedKeys()
void FCurveEditor::TranslateSelectedKeys (double SecondsToAdd)
Nudge left or right.
TranslateSelectedKeysLeft()
void FCurveEditor::TranslateSelectedKeysLeft ()
TranslateSelectedKeysRight()
void FCurveEditor::TranslateSelectedKeysRight ()
UE_DEPRECATED() [1/2]
FCurveEditor::UE_DEPRECATED (5. 6, "Use the version that takes FKeyPasteArg instead.")
Paste keys.
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FCurveEditor::UE_DEPRECATED (5. 6, "Use the version that takes in ECurveEditorPasteMode and ECurveEditorPasteFlags instead.") const protected
Referenced by UE_DEPRECATED().
UnpinCurve()
void FCurveEditor::UnpinCurve (FCurveModelID InCurveID)
UpdateGeometry()
void FCurveEditor::UpdateGeometry (const FGeometry & CurrentGeometry)
Called by SCurveEditorPanel to update the allocated geometry for this curve editor.
ZoomToFit()
void FCurveEditor::ZoomToFit (EAxisList::Type Axes = EAxisList::All)
Zoom the curve editor to fit all the selected curves (or all curves if none selected)
Parameters
Axes (Optional) Axes to lock the zoom to
References EAxisList::All.
ZoomToFitAll()
void FCurveEditor::ZoomToFitAll (EAxisList::Type Axes = EAxisList::All)
Zoom the curve editor to fit all the currently visible curves.
Parameters
Axes (Optional) Axes to lock the zoom to
References EAxisList::All.
ZoomToFitCurves()
void FCurveEditor::ZoomToFitCurves (TArrayView< const FCurveModelID > CurveModelIDs, EAxisList::Type Axes = EAxisList::All)
Zoom the curve editor to fit the requested curves.
Parameters
CurveModelIDs The curve IDs to zoom to fit.
Axes (Optional) Axes to lock the zoom to
References EAxisList::All.
ZoomToFitInternal()
void FCurveEditor::ZoomToFitInternal (EAxisList::Type Axes, const TMap< FCurveModelID, FKeyHandleSet > & CurveKeySet) protected
Internal zoom to fit implementation.
Parameters
Axes The axes to zoom (only X or Y supported)
CurveKeySet Map from curve ID to keys that should be considered for zoom. Empty key sets will cause the entire curve range to be zoomed.
ZoomToFitSelection()
void FCurveEditor::ZoomToFitSelection (EAxisList::Type Axes = EAxisList::All)
Zoom the curve editor to fit all the current key selection.
Zooms to fit all if less than 2 keys are selected.
Parameters
Axes (Optional) Axes to lock the zoom to
References EAxisList::All.
Field Documentation
ActiveCurvesSerialNumber
uint32 FCurveEditor::ActiveCurvesSerialNumber protected
A serial number that is incremented any time the currently active set of curves are changed.
Definition at line 760 of file CurveEditor.h.
Referenced by GetActiveCurvesSerialNumber().
ActiveTool
TOptional<FCurveEditorToolID> FCurveEditor::ActiveTool protected
The currently active tool if any.
If unset then no tool is currently active and the next selection will default to the first tool.
Definition at line 727 of file CurveEditor.h.
AxisSnapMetrics
FCurveEditorAxisSnap FCurveEditor::AxisSnapMetrics protected
Track which axis UI movements should be snapped to (where applicable) based on limitations imposed by the UI.
Definition at line 754 of file CurveEditor.h.
Referenced by GetAxisSnap(), and SetAxisSnap().
bBoundTransformUpdatesSuppressed
bool FCurveEditor::bBoundTransformUpdatesSuppressed protected
Should attempts to update the bounds of each curve be ignored?
This allows tools to keep the bounds from being automatically updated each frame which allows Normalized views to push past their boundaries without the normalization ratio changing per-frame as you drag.
Definition at line 751 of file CurveEditor.h.
Referenced by AreBoundTransformUpdatesSuppressed(), and SuppressBoundTransformUpdates().
bInAddToSelection
const FCurveModelID TOptional<double> const bool FCurveEditor::bInAddToSelection protected
Definition at line 570 of file CurveEditor.h.
bInOverwriteRange [1/2]
const FCurveModelID TOptional<double> const bool const bool FCurveEditor::bInOverwriteRange protected
Definition at line 570 of file CurveEditor.h.
bInOverwriteRange [2/2]
const bool FCurveEditor::bInOverwriteRange = false)
Definition at line 580 of file CurveEditor.h.
Bounds
TUniquePtr<ICurveEditorBounds> FCurveEditor::Bounds protected
Curve editor bounds implementation.
Definition at line 704 of file CurveEditor.h.
Referenced by GetBounds(), and GetBounds().
BufferedCurves
TArray<TUniquePtr<IBufferedCurveModel> > FCurveEditor::BufferedCurves protected
Buffered Curves.
When a curve is buffered it is copied and the new copy is uniquely owned by the Curve Editor.
Definition at line 757 of file CurveEditor.h.
Referenced by GetBufferedCurves(), and GetNumBufferedCurves().
CachedPhysicalSize
FVector2D FCurveEditor::CachedPhysicalSize private
Cached physical size of the panel representing this editor.
Definition at line 770 of file CurveEditor.h.
ChildCurves
TMultiMap<FCurveModelID, FCurveModelID> FCurveEditor::ChildCurves protected
Map of child curves.
Definition at line 711 of file CurveEditor.h.
CommandList
TSharedPtr<FUICommandList> FCurveEditor::CommandList protected
UI command list of actions mapped to this curve editor.
Definition at line 730 of file CurveEditor.h.
Referenced by GetCommands().
CurveData
TMap<FCurveModelID, TUniquePtr<FCurveModel> > FCurveEditor::CurveData protected
Map from curve model ID to the actual curve model.
Definition at line 707 of file CurveEditor.h.
CustomAxes
TSortedMap<FName, TSharedPtr<FCurveEditorAxis>, FDefaultAllocator, FNameFastLess> FCurveEditor::CustomAxes protected
Map of all axes.
Definition at line 714 of file CurveEditor.h.
DefaultKeyAttributes
TAttribute<FKeyAttributes> FCurveEditor::DefaultKeyAttributes
Attribute used for determining default attributes to apply to a newly create key.
Definition at line 109 of file CurveEditor.h.
Referenced by GetDefaultKeyAttribute(), and GetDefaultKeyAttributes().
EditorExtensions
TArray<TSharedRef<ICurveEditorExtension> > FCurveEditor::EditorExtensions protected
List of editor extensions we have initialized.
Definition at line 736 of file CurveEditor.h.
Referenced by GetEditorExtensions().
FixedGridSpacingAttribute
TAttribute<TOptional<float> > FCurveEditor::FixedGridSpacingAttribute
Attribute used to retrieve the current value-axis grid line state.
Definition at line 94 of file CurveEditor.h.
Referenced by GetGridSpacing().
GridLineLabelFormatXAttribute
TAttribute<FText> FCurveEditor::GridLineLabelFormatXAttribute
Grid line label text format strings for the X and Y axis.
Definition at line 112 of file CurveEditor.h.
Referenced by GetGridLineLabelFormatXAttribute().
GridLineLabelFormatYAttribute
TAttribute<FText> FCurveEditor::GridLineLabelFormatYAttribute
Definition at line 112 of file CurveEditor.h.
Referenced by GetGridLineLabelFormatYAttribute().
HorizontalCurveFlipRangeSettings
FCurveFlipRangeSettings FCurveEditor::HorizontalCurveFlipRangeSettings
Definition at line 536 of file CurveEditor.h.
InputSnapEnabledAttribute
TAttribute<bool> FCurveEditor::InputSnapEnabledAttribute
Attribute used to determine if we should snap input values.
Definition at line 97 of file CurveEditor.h.
InputSnapRateAttribute
TAttribute<FFrameRate> FCurveEditor::InputSnapRateAttribute
Attribute used to retrieve the current input snap rate (also used for display)
Definition at line 91 of file CurveEditor.h.
InputZoomToFitPadding
TAttribute<double> FCurveEditor::InputZoomToFitPadding
Padding applied to zoom-to-fit the input.
Definition at line 115 of file CurveEditor.h.
InTargetCurve
const FCurveModelID FCurveEditor::InTargetCurve protected
Definition at line 570 of file CurveEditor.h.
Referenced by CopyBufferCurveToCurveID().
InTimeOffset
const FCurveModelID TOptional<double> FCurveEditor::InTimeOffset protected
Definition at line 570 of file CurveEditor.h.
Referenced by CopyBufferCurveToCurveID().
OnActiveToolChangedDelegate
FOnActiveToolChanged FCurveEditor::OnActiveToolChangedDelegate
Delegate that is invoked when a tool becomes active.
Also fired when the tool goes inactive.
Definition at line 121 of file CurveEditor.h.
OnCurveArrayChanged
FOnCurveArrayChanged FCurveEditor::OnCurveArrayChanged
Delegate that's broadcast when the curve display changes.
Definition at line 776 of file CurveEditor.h.
OnInputSnapEnabledChanged
FOnSetBoolean FCurveEditor::OnInputSnapEnabledChanged
Delegate that is invoked when the input snapping has been enabled/disabled.
Definition at line 103 of file CurveEditor.h.
OnOutputSnapEnabledChanged
FOnSetBoolean FCurveEditor::OnOutputSnapEnabledChanged
Delegate that is invoked when the output snapping has been enabled/disabled.
Definition at line 106 of file CurveEditor.h.
OutputSnapEnabledAttribute
TAttribute<bool> FCurveEditor::OutputSnapEnabledAttribute
Attribute used to determine if we should snap output values.
Definition at line 100 of file CurveEditor.h.
OutputZoomToFitPadding
TAttribute<double> FCurveEditor::OutputZoomToFitPadding
Padding applied to zoom-to-fit the output.
Definition at line 118 of file CurveEditor.h.
PinnedCurves
TSet<FCurveModelID> FCurveEditor::PinnedCurves protected
Set of pinned curve models.
Definition at line 717 of file CurveEditor.h.
Referenced by GetPinnedCurves().
Selection
FCurveEditorSelection FCurveEditor::Selection
Container holding the current key/tangent selection.
Definition at line 86 of file CurveEditor.h.
Referenced by GetSelection(), and GetSelection().
Settings
UCurveEditorSettings* FCurveEditor::Settings protected
Curve editor settings object.
Definition at line 733 of file CurveEditor.h.
Referenced by GetSettings().
SuspendBroadcastCount
int32 FCurveEditor::SuspendBroadcastCount protected
Counter to suspend broadcasting of changed delegates.
Definition at line 763 of file CurveEditor.h.
Referenced by IsBroadcasting(), ResumeBroadcast(), and SuspendBroadcast().
ToolExtensions
TMap<FCurveEditorToolID, TUniquePtr<ICurveEditorToolExtension> > FCurveEditor::ToolExtensions protected
List of tool extensions we have initialized.
Definition at line 742 of file CurveEditor.h.
Referenced by GetToolExtensions().
TransactionManager
TUniquePtr<UE::CurveEditor::FTransactionManager> FCurveEditor::TransactionManager protected
Orchestrates transaction that affect this curve editor.
Definition at line 766 of file CurveEditor.h.
Referenced by GetTransactionManager().
Tree
FCurveEditorTree FCurveEditor::Tree protected
Hierarchical information pertaining to curve data.
Definition at line 724 of file CurveEditor.h.
Referenced by GetTree(), GetTree(), and IsDoingDirectSelection().
TreeIDByCurveID
TMap<FCurveModelID, FCurveEditorTreeItemID> FCurveEditor::TreeIDByCurveID protected
Map from curve model ID to its originating tree item.
Definition at line 709 of file CurveEditor.h.
VerticalCurveFlipRangeSettings
FCurveFlipRangeSettings FCurveEditor::VerticalCurveFlipRangeSettings
Definition at line 537 of file CurveEditor.h.
WeakPanel
TWeakPtr<SCurveEditorPanel> FCurveEditor::WeakPanel protected
Definition at line 719 of file CurveEditor.h.
WeakTimeSliderController
TWeakPtr<ITimeSliderController> FCurveEditor::WeakTimeSliderController protected
Optional external Time Slider controller to sync with.
Enables some additional functionality.
Definition at line 745 of file CurveEditor.h.
Referenced by GetTimeSliderController(), and SetTimeSliderController().
WeakView
TWeakPtr<SCurveEditorView> FCurveEditor::WeakView protected
Definition at line 721 of file CurveEditor.h.
ZoomScalingAttr
TAttribute<const FCurveEditorZoomScaleConfig*> FCurveEditor::ZoomScalingAttr protected
The zoom scale config that was passed in to us in InitCurveEditor.
Definition at line 739 of file CurveEditor.h.
The documentation for this class was generated from the following file:
CurveEditor.h