Unreal Engine 5.6 C++ API: TInterval< ElementType > Struct Template Reference
TInterval< ElementType > Struct Template Reference
Template for numeric interval.
#include "Interval.h"
Public Member Functions
TInterval ()
Default constructor.
TInterval (ElementType InMin, ElementType InMax)
Creates and initializes a new interval with the specified lower and upper bounds.
ElementType Clamp (ElementType X) const
Clamps X to be between the interval inclusively.
bool Contains (const ElementType &Element) const
Checks whether this interval contains the specified element.
void Expand (ElementType ExpandAmount)
Expands this interval to both sides by the specified amount.
ElementType GetRangePct (ElementType X) const
Calculate the Percentage of X in the Interval.
void Include (ElementType X)
Expands this interval if necessary to include the specified element.
ElementType Interpolate (float Alpha) const
Interval interpolation.
bool IsValid () const
Whether interval is valid (Min <= Max).
bool operator!= (const TInterval &Other) const
Compare two intervals for inequality.
void operator+= (ElementType X)
Offset the interval by adding X.
void operator-= (ElementType X)
Offset the interval by subtracting X.
bool operator== (const TInterval &Other) const
Compare two intervals for equality.
ElementType Size () const
Computes the size of this interval.
Data Fields
ElementType Max
Holds the upper bound of the interval.
ElementType Min
Holds the lower bound of the interval.
Friends
uint32 GetTypeHash (const TInterval &Interval)
Gets the hash for the specified interval.
TInterval Intersect (const TInterval &A, const TInterval &B)
Calculates the intersection of two intervals.
class FArchive & operator<< (class FArchive &Ar, TInterval &Interval)
Serializes the interval.
Detailed Description
template<typename ElementType>
struct TInterval< ElementType >
Template for numeric interval.
Definition at line 32 of file Interval.h.
Constructor & Destructor Documentation
TInterval() [1/2]
template<typename ElementType> TInterval< ElementType >::TInterval () inline nodiscard
Default constructor.
The interval is invalid
Definition at line 47 of file Interval.h.
Referenced by TInterval< float >::Intersect.
TInterval() [2/2]
template<typename ElementType> TInterval< ElementType >::TInterval (ElementType InMin, ElementType InMax) inline nodiscard
Creates and initializes a new interval with the specified lower and upper bounds.
Parameters
InMin The lower bound of the constructed interval.
InMax The upper bound of the constructed interval.
Definition at line 58 of file Interval.h.
Member Function Documentation
Clamp()
template<typename ElementType> ElementType TInterval< ElementType >::Clamp (ElementType X) const inline nodiscard
Clamps X to be between the interval inclusively.
Parameters
X the element to clamp
Returns
zero if invalid(Min > Max), clamped result otherwise
Definition at line 210 of file Interval.h.
Contains()
template<typename ElementType> bool TInterval< ElementType >::Contains (const ElementType & Element) const inline nodiscard
Checks whether this interval contains the specified element.
Parameters
Element The element to check.
Returns
true if the range interval the element, false otherwise.
Definition at line 143 of file Interval.h.
Expand()
template<typename ElementType> void TInterval< ElementType >::Expand (ElementType ExpandAmount) inline
Expands this interval to both sides by the specified amount.
Parameters
ExpandAmount The amount to expand by.
Definition at line 153 of file Interval.h.
GetRangePct()
template<typename ElementType> ElementType TInterval< ElementType >::GetRangePct (ElementType X) const inline nodiscard
Calculate the Percentage of X in the Interval.
Parameters
X the element to calculate the percentage
Returns
zero if invalid(Min > Max), percentage otherwise
Definition at line 225 of file Interval.h.
Include()
template<typename ElementType> void TInterval< ElementType >::Include (ElementType X) inline
Expands this interval if necessary to include the specified element.
Parameters
X The element to include.
Definition at line 167 of file Interval.h.
Interpolate()
template<typename ElementType> ElementType TInterval< ElementType >::Interpolate (float Alpha) const inline nodiscard
Interval interpolation.
Parameters
Alpha interpolation amount
Returns
interpolation result
Definition at line 194 of file Interval.h.
Referenced by TSimpleCellGrid< CellType, InvalidCellValue >::SetVerticalInterval().
IsValid()
template<typename ElementType> bool TInterval< ElementType >::IsValid () const inline nodiscard
Whether interval is valid (Min <= Max).
Returns
false when interval is invalid, true otherwise
Definition at line 132 of file Interval.h.
Referenced by TInterval< float >::Clamp(), TInterval< float >::Contains(), TInterval< float >::Expand(), TInterval< float >::GetRangePct(), TInterval< float >::Include(), TInterval< float >::Interpolate(), TInterval< float >::operator+=(), TInterval< float >::operator-=(), and TSimpleCellGrid< CellType, InvalidCellValue >::SetVerticalInterval().
operator!=()
template<typename ElementType> bool TInterval< ElementType >::operator!= (const TInterval< ElementType > & Other) const inline nodiscard
Compare two intervals for inequality.
Parameters
Other The other interval being compared.
Returns
true if the intervals are not equal, false otherwise.
Definition at line 110 of file Interval.h.
operator+=()
template<typename ElementType> void TInterval< ElementType >::operator+= (ElementType X) inline
Offset the interval by adding X.
Parameters
X The offset.
Definition at line 70 of file Interval.h.
operator-=()
template<typename ElementType> void TInterval< ElementType >::operator-= (ElementType X) inline
Offset the interval by subtracting X.
Parameters
X The offset.
Definition at line 84 of file Interval.h.
operator==()
template<typename ElementType> bool TInterval< ElementType >::operator== (const TInterval< ElementType > & Other) const inline nodiscard
Compare two intervals for equality.
Parameters
Other The other interval being compared.
Returns
true if the intervals are equal, false otherwise.
Definition at line 99 of file Interval.h.
Size()
template<typename ElementType> ElementType TInterval< ElementType >::Size () const inline nodiscard
Computes the size of this interval.
Returns
Interval size.
Definition at line 122 of file Interval.h.
Referenced by TInterval< float >::Interpolate(), and TSimpleCellGrid< CellType, InvalidCellValue >::SetVerticalInterval().
Friends And Related Symbol Documentation
GetTypeHash
template<typename ElementType> uint32 GetTypeHash (const TInterval< ElementType > & Interval) friend
Gets the hash for the specified interval.
Parameters
Interval The Interval to get the hash for.
Returns
Hash value.
Definition at line 271 of file Interval.h.
Referenced by TInterval< float >::GetTypeHash.
Intersect
template<typename ElementType> TInterval Intersect (const TInterval< ElementType > & A, const TInterval< ElementType > & B) friend
Calculates the intersection of two intervals.
Parameters
A The first interval.
B The second interval.
Returns
The intersection.
Definition at line 243 of file Interval.h.
operator<<
template<typename ElementType> class FArchive & operator<< (class FArchive & Ar, TInterval< ElementType > & Interval) friend
Serializes the interval.
Parameters
Ar The archive to serialize into.
Interval The interval to serialize.
Returns
Reference to the Archive after serialization.
Definition at line 260 of file Interval.h.
Field Documentation
Max
template<typename ElementType> ElementType TInterval< ElementType >::Max
Holds the upper bound of the interval.
Definition at line 38 of file Interval.h.
Referenced by TInterval< float >::GetTypeHash, and TInterval< float >::operator<<.
Min
template<typename ElementType> ElementType TInterval< ElementType >::Min
Holds the lower bound of the interval.
Definition at line 35 of file Interval.h.
Referenced by TInterval< float >::GetTypeHash, and TInterval< float >::operator<<.
The documentation for this struct was generated from the following file:
Interval.h