Unreal Engine 5.6 C++ API: TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > Struct Template Reference
TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > Struct Template Reference
A node in the kDOP tree.
#include "kDOP.h"
Public Types
typedef COLL_DATA_PROVIDER DataProviderType
Exposes data provider type to clients.
typedef TkDOPNode< DataProviderType, KDOP_IDX_TYPE > NodeType
Exposes node type to clients.
Public Member Functions
FORCEINLINE TkDOPNode ()
Inits the data to no child nodes and an inverted volume.
bool LineCheck (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > &Check, TTraversalHistory< KDOP_IDX_TYPE > History) const
Determines the line in the FkDOPLineCollisionCheck intersects this node.
FORCEINLINE void LineCheckBounds (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > &Check, FVector4 &HitTime, int32 NodeHit[4]) const
The slab testing algorithm is based on the following papers.
bool LineCheckPreCalculated (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > &Check, const FVector4 &NodeHitTime, TTraversalHistory< KDOP_IDX_TYPE > History, int32 *NodeHit) const
Determines the line in the FkDOPLineCollisionCheck intersects this node.
bool LineCheckTriangles (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > &Check, const TTraversalHistory< KDOP_IDX_TYPE > &History) const
Works through the list of triangles in this node checking each one for a collision.
FBox SplitTriangleList (int32 Start, int32 NumTris, TArray< FkDOPBuildCollisionTriangle< KDOP_IDX_TYPE > > &BuildTriangles, TChunkedArray< FTriangleSOA > &SOATriangles, TChunkedArray< NodeType > &Nodes)
Determines if the node is a leaf or not.
Data Fields
union {
struct {
KDOP_IDX_TYPE LeftNode
KDOP_IDX_TYPE RightNode
} n
struct {
KDOP_IDX_TYPE NumTriangles
KDOP_IDX_TYPE StartIndex
} t
};
bool bIsLeaf
FFourBox BoundingVolumes
Set of bounding volumes for child nodes.
uint8 Occupancy
Detailed Description
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE>
struct TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >
A node in the kDOP tree.
The node contains the kDOP volume that encompasses it's children and/or triangles
Definition at line 378 of file kDOP.h.
Member Typedef Documentation
DataProviderType
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> typedef COLL_DATA_PROVIDER TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::DataProviderType
Exposes data provider type to clients.
Definition at line 381 of file kDOP.h.
NodeType
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> typedef TkDOPNode<DataProviderType,KDOP_IDX_TYPE> TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::NodeType
Exposes node type to clients.
Definition at line 384 of file kDOP.h.
Constructor & Destructor Documentation
TkDOPNode()
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> FORCEINLINE TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::TkDOPNode () inline
Inits the data to no child nodes and an inverted volume.
Definition at line 417 of file kDOP.h.
Member Function Documentation
LineCheck()
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> bool TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::LineCheck (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > & Check, TTraversalHistory< KDOP_IDX_TYPE > History) const inline
Determines the line in the FkDOPLineCollisionCheck intersects this node.
It also will check the child nodes if it is not a leaf, otherwise it will check against the triangle data.
Parameters
Check – The aggregated line check data
Definition at line 735 of file kDOP.h.
LineCheckBounds()
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> FORCEINLINE void TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::LineCheckBounds (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > & Check, FVector4 & HitTime, int32 NodeHit[4]) const inline
The slab testing algorithm is based on the following papers.
We chose to use the faster final hit determination, which means we'll get some false positives.
"A Cross-Platform Framework for Interactive Ray Tracing" Markus Geimer, Stefan Mueller http://www.uni-koblenz.de/~cg/publikationen/cp_raytrace.pdf
"Efficiency Issues for Ray Tracing" Brian Smits http://www.cs.utah.edu/~bes/papers/fastRT/paper-node10.html
We don't need to handle +/- INF, but we have permission to use Thierry Berger-Perrin trick available below.
http://www.flipcode.com/archives/SSE_RayBox_Intersection_Test.shtml
Parameters
Check Information about the ray to trace
HitTime [out] Time of hit
Definition at line 655 of file kDOP.h.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheck().
LineCheckPreCalculated()
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> bool TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::LineCheckPreCalculated (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > & Check, const FVector4 & NodeHitTime, TTraversalHistory< KDOP_IDX_TYPE > History, int32 * NodeHit) const inline
Determines the line in the FkDOPLineCollisionCheck intersects this node.
It also will check the child nodes if it is not a leaf, otherwise it will check against the triangle data.
Parameters
Check – The aggregated line check data
Definition at line 815 of file kDOP.h.
LineCheckTriangles()
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> bool TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::LineCheckTriangles (TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE > & Check, const TTraversalHistory< KDOP_IDX_TYPE > & History) const inline
Works through the list of triangles in this node checking each one for a collision.
Parameters
Check – The aggregated line check data
Definition at line 889 of file kDOP.h.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheck(), and TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckPreCalculated().
SplitTriangleList()
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> FBox TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::SplitTriangleList (int32 Start, int32 NumTris, TArray< FkDOPBuildCollisionTriangle< KDOP_IDX_TYPE > > & BuildTriangles, TChunkedArray< FTriangleSOA > & SOATriangles, TChunkedArray< NodeType > & Nodes) inline
Determines if the node is a leaf or not.
If it is not a leaf, it subdivides the list of triangles again adding two child nodes and splitting them on the mean (splatter method). Otherwise it sets up the triangle information.
Parameters
Start – The triangle index to start processing with
NumTris – The number of triangles to process
BuildTriangles – The list of triangles to use for the build process
Nodes – The list of nodes in this tree
Returns
bounding box for this node
Definition at line 434 of file kDOP.h.
Field Documentation
[union]
union { ... } TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >
bIsLeaf
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> bool TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::bIsLeaf
Definition at line 390 of file kDOP.h.
BoundingVolumes
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> FFourBox TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::BoundingVolumes
Set of bounding volumes for child nodes.
Definition at line 387 of file kDOP.h.
LeftNode
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> KDOP_IDX_TYPE TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::LeftNode
Definition at line 400 of file kDOP.h.
[struct]
struct { ... } TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::n
NumTriangles
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> KDOP_IDX_TYPE TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::NumTriangles
Definition at line 409 of file kDOP.h.
Occupancy
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> uint8 TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::Occupancy
Definition at line 391 of file kDOP.h.
RightNode
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> KDOP_IDX_TYPE TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::RightNode
Definition at line 401 of file kDOP.h.
StartIndex
template<typename COLL_DATA_PROVIDER, typename KDOP_IDX_TYPE> KDOP_IDX_TYPE TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::StartIndex
Definition at line 410 of file kDOP.h.
[struct]
struct { ... } TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::t
The documentation for this struct was generated from the following file:
kDOP.h