Unreal Engine 5.6 C++ API: UE::StateTree::FActiveStateID Struct Reference
UE::StateTree::FActiveStateID Struct Reference
A unique ID for FStateTreeActiveStates state.
#include "StateTreeStatePath.h"
Public Member Functions
FActiveStateID ()=default
FActiveStateID (uint32 NewID)
bool IsValid () const
bool operator!= (const FActiveStateID &) const =default
bool operator== (const FActiveStateID &) const =default
Static Public Attributes
static STATETREEMODULE_API const FActiveStateID Invalid
Private Attributes
uint32 Value = InvalidValue
Static Private Attributes
static constexpr uint32 InvalidValue = 0
Detailed Description
A unique ID for FStateTreeActiveStates state.
Definition at line 45 of file StateTreeStatePath.h.
Constructor & Destructor Documentation
FActiveStateID() [1/2]
UE::StateTree::FActiveStateID::FActiveStateID () explicit default
Referenced by operator!=(), and operator==().
FActiveStateID() [2/2]
UE::StateTree::FActiveStateID::FActiveStateID (uint32 NewID) inline explicit
Definition at line 54 of file StateTreeStatePath.h.
References check, InvalidValue, and Value.
Member Function Documentation
IsValid()
bool UE::StateTree::FActiveStateID::IsValid () const inline nodiscard
Definition at line 63 of file StateTreeStatePath.h.
References InvalidValue, and Value.
operator!=()
bool UE::StateTree::FActiveStateID::operator!= (const FActiveStateID &) const nodiscard default
References FActiveStateID().
operator==()
bool UE::StateTree::FActiveStateID::operator== (const FActiveStateID &) const nodiscard default
References FActiveStateID().
Field Documentation
Invalid
STATETREEMODULE_API const FActiveStateID UE::StateTree::FActiveStateID::Invalid static
Definition at line 51 of file StateTreeStatePath.h.
InvalidValue
uint32 UE::StateTree::FActiveStateID::InvalidValue = 0 static constexpr private
Definition at line 48 of file StateTreeStatePath.h.
Referenced by FActiveStateID(), and IsValid().
Value
uint32 UE::StateTree::FActiveStateID::Value = InvalidValue private
Definition at line 69 of file StateTreeStatePath.h.
Referenced by FActiveStateID(), and IsValid().
The documentation for this struct was generated from the following file:
StateTreeStatePath.h