Unreal Engine 5.6 C++ API: FAnalogCursor Class Reference
FAnalogCursor Class Reference
A class that simulates a cursor driven by an analog stick.
#include "AnalogCursor.h"
Public Member Functions
FAnalogCursor ()
FAnalogCursor (const FAnalogCursor &)
virtual ~FAnalogCursor ()
Dtor.
virtual const TCHAR * GetDebugName () const override
Debug name for logging purposes.
virtual int32 GetOwnerUserIndex () const
virtual bool HandleAnalogInputEvent (FSlateApplication &SlateApp, const FAnalogInputEvent &InAnalogInputEvent) override
Analog axis input.
virtual bool HandleKeyDownEvent (FSlateApplication &SlateApp, const FKeyEvent &InKeyEvent) override
Key down input.
virtual bool HandleKeyUpEvent (FSlateApplication &SlateApp, const FKeyEvent &InKeyEvent) override
Key up input.
virtual bool HandleMouseMoveEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent) override
Mouse movement input.
void SetAcceleration (float NewAcceleration)
void SetDeadZone (float NewDeadZone)
void SetMaxSpeed (float NewMaxSpeed)
void SetMode (AnalogCursorMode::Type NewMode)
void SetStickySlowdown (float NewStickySlowdown)
virtual void Tick (const float DeltaTime, FSlateApplication &SlateApp, TSharedRef< ICursor > Cursor) override
Public Member Functions inherited from IInputProcessor
IInputProcessor ()
virtual ~IInputProcessor ()
virtual bool HandleMotionDetectedEvent (FSlateApplication &SlateApp, const FMotionEvent &MotionEvent)
Called when a motion-driven device has new input.
virtual bool HandleMouseButtonDoubleClickEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent)
Mouse button double clicked.
virtual bool HandleMouseButtonDownEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent)
Mouse button press.
virtual bool HandleMouseButtonUpEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent)
Mouse button release.
virtual bool HandleMouseWheelOrGestureEvent (FSlateApplication &SlateApp, const FPointerEvent &InWheelEvent, const FPointerEvent *InGestureEvent)
Mouse wheel input.
Public Member Functions inherited from TSharedFromThis< FAnalogCursor >
TSharedRef< FAnalogCursor, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAnalogCursor, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual FVector2D CalculateTickedCursorPosition (const float DeltaTime, FSlateApplication &SlateApp, TSharedPtr< FSlateUser > SlateUser)
void ClearAnalogValues ()
Set the cached analog stick declinations to 0.
FORCEINLINE const FVector2D & GetAnalogValues (EAnalogStick Stick=EAnalogStick::Left) const
Getter.
virtual bool IsRelevantInput (const FAnalogInputEvent &AnalogInputEvent) const
virtual bool IsRelevantInput (const FInputEvent &InputEvent) const
virtual bool IsRelevantInput (const FKeyEvent &KeyEvent) const
virtual bool IsRelevantInput (const FPointerEvent &MouseEvent) const
UE_DEPRECATED (4.24, "FAnalogCursor now updates cursor position based on user, not the hardware cursor specifically.") 1 virtual void UpdateCursorPosition(FSlateApplication &SlateApp
Handles updating the cursor position and processing a Mouse Move Event.
virtual void UpdateCursorPosition (FSlateApplication &SlateApp, TSharedRef< FSlateUser > SlateUser, const FVector2D &NewPosition, bool bForce=false)
Protected Member Functions inherited from TSharedFromThis< FAnalogCursor >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
float Acceleration
Current settings.
TSharedRef< ICursor > const FVector2D bool bForce = false)
FVector2D CurrentOffset
Current sub-pixel offset.
FVector2D CurrentSpeed
Current speed of the cursor.
TSharedRef< ICursor > Cursor
float DeadZone
float MaxSpeed
AnalogCursorMode::Type Mode
TSharedRef< ICursor > const FVector2D & NewPosition
float StickySlowdown
Private Member Functions
FORCEINLINE FVector2D & GetAnalogValue (EAnalogStick Stick)
Private Attributes
FVector2D AnalogValues [static_cast< uint8 >(EAnalogStick::Max)]
Input from the gamepad.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FAnalogCursor >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A class that simulates a cursor driven by an analog stick.
Definition at line 35 of file AnalogCursor.h.
Constructor & Destructor Documentation
FAnalogCursor() [1/2]
FAnalogCursor::FAnalogCursor ()
Referenced by FAnalogCursor().
FAnalogCursor() [2/2]
FAnalogCursor::FAnalogCursor (const FAnalogCursor &)
References FAnalogCursor().
~FAnalogCursor()
virtual FAnalogCursor::~FAnalogCursor () virtual
Dtor.
Member Function Documentation
CalculateTickedCursorPosition()
virtual FVector2D FAnalogCursor::CalculateTickedCursorPosition (const float DeltaTime, FSlateApplication & SlateApp, TSharedPtr< FSlateUser > SlateUser) protected virtual
References CalculateTickedCursorPosition(), and DeltaTime.
Referenced by CalculateTickedCursorPosition().
ClearAnalogValues()
void FAnalogCursor::ClearAnalogValues () protected
Set the cached analog stick declinations to 0.
GetAnalogValue()
FORCEINLINE FVector2D & FAnalogCursor::GetAnalogValue (EAnalogStick Stick) inline private
Definition at line 100 of file AnalogCursor.h.
References AnalogValues, FORCEINLINE, and GetAnalogValue().
Referenced by GetAnalogValue().
GetAnalogValues()
FORCEINLINE const FVector2D & FAnalogCursor::GetAnalogValues (EAnalogStick Stick = EAnalogStick::Left) const inline protected
Getter.
Definition at line 69 of file AnalogCursor.h.
References AnalogValues, FORCEINLINE, and Left.
GetDebugName()
virtual const TCHAR * FAnalogCursor::GetDebugName () const inline override virtual
Debug name for logging purposes.
Reimplemented from IInputProcessor.
Definition at line 50 of file AnalogCursor.h.
References TEXT.
GetOwnerUserIndex()
virtual int32 FAnalogCursor::GetOwnerUserIndex () const inline virtual
Reimplemented in FCommonAnalogCursor.
Definition at line 53 of file AnalogCursor.h.
HandleAnalogInputEvent()
virtual bool FAnalogCursor::HandleAnalogInputEvent (FSlateApplication & SlateApp, const FAnalogInputEvent & InAnalogInputEvent) override virtual
Analog axis input.
Reimplemented from IInputProcessor.
Reimplemented in FCommonAnalogCursor.
HandleKeyDownEvent()
virtual bool FAnalogCursor::HandleKeyDownEvent (FSlateApplication & SlateApp, const FKeyEvent & InKeyEvent) override virtual
Key down input.
Reimplemented from IInputProcessor.
Reimplemented in FCommonAnalogCursor.
HandleKeyUpEvent()
virtual bool FAnalogCursor::HandleKeyUpEvent (FSlateApplication & SlateApp, const FKeyEvent & InKeyEvent) override virtual
Key up input.
Reimplemented from IInputProcessor.
Reimplemented in FCommonAnalogCursor.
HandleMouseMoveEvent()
virtual bool FAnalogCursor::HandleMouseMoveEvent (FSlateApplication & SlateApp, const FPointerEvent & MouseEvent) override virtual
Mouse movement input.
Reimplemented from IInputProcessor.
Reimplemented in FCommonAnalogCursor.
References MouseEvent.
IsRelevantInput() [1/4]
virtual bool FAnalogCursor::IsRelevantInput (const FAnalogInputEvent & AnalogInputEvent) const protected virtual
Reimplemented in FCommonAnalogCursor.
IsRelevantInput() [2/4]
virtual bool FAnalogCursor::IsRelevantInput (const FInputEvent & InputEvent) const protected virtual
IsRelevantInput() [3/4]
virtual bool FAnalogCursor::IsRelevantInput (const FKeyEvent & KeyEvent) const protected virtual
Reimplemented in FCommonAnalogCursor.
IsRelevantInput() [4/4]
virtual bool FAnalogCursor::IsRelevantInput (const FPointerEvent & MouseEvent) const protected virtual
References MouseEvent.
SetAcceleration()
void FAnalogCursor::SetAcceleration (float NewAcceleration)
SetDeadZone()
void FAnalogCursor::SetDeadZone (float NewDeadZone)
SetMaxSpeed()
void FAnalogCursor::SetMaxSpeed (float NewMaxSpeed)
SetMode()
void FAnalogCursor::SetMode (AnalogCursorMode::Type NewMode)
SetStickySlowdown()
void FAnalogCursor::SetStickySlowdown (float NewStickySlowdown)
Tick()
virtual void FAnalogCursor::Tick (const float DeltaTime, FSlateApplication & SlateApp, TSharedRef< ICursor > Cursor) override virtual
Implements IInputProcessor.
Reimplemented in FCommonAnalogCursor.
References Cursor, and DeltaTime.
UE_DEPRECATED()
FAnalogCursor::UE_DEPRECATED (4. 24, "FAnalogCursor now updates cursor position based on user, not the hardware cursor specifically.") & protected
Handles updating the cursor position and processing a Mouse Move Event.
UpdateCursorPosition()
virtual void FAnalogCursor::UpdateCursorPosition (FSlateApplication & SlateApp, TSharedRef< FSlateUser > SlateUser, const FVector2D & NewPosition, bool bForce = false) protected virtual
References bForce, NewPosition, and UpdateCursorPosition().
Referenced by UpdateCursorPosition().
Field Documentation
Acceleration
float FAnalogCursor::Acceleration protected
Current settings.
Definition at line 92 of file AnalogCursor.h.
AnalogValues
FVector2D FAnalogCursor::AnalogValues[static_cast< uint8 >(EAnalogStick::Max)] private
Input from the gamepad.
Definition at line 106 of file AnalogCursor.h.
Referenced by GetAnalogValue(), and GetAnalogValues().
bForce
TSharedRef<ICursor> const FVector2D bool FAnalogCursor::bForce = false) protected
Definition at line 79 of file AnalogCursor.h.
Referenced by UpdateCursorPosition().
CurrentOffset
FVector2D FAnalogCursor::CurrentOffset protected
Current sub-pixel offset.
Definition at line 89 of file AnalogCursor.h.
CurrentSpeed
FVector2D FAnalogCursor::CurrentSpeed protected
Current speed of the cursor.
Definition at line 86 of file AnalogCursor.h.
Cursor
TSharedRef<ICursor> FAnalogCursor::Cursor protected
Definition at line 79 of file AnalogCursor.h.
Referenced by Tick(), and FCommonAnalogCursor::Tick().
DeadZone
float FAnalogCursor::DeadZone protected
Definition at line 95 of file AnalogCursor.h.
MaxSpeed
float FAnalogCursor::MaxSpeed protected
Definition at line 93 of file AnalogCursor.h.
Mode
AnalogCursorMode::Type FAnalogCursor::Mode protected
Definition at line 96 of file AnalogCursor.h.
NewPosition
TSharedRef<ICursor> const FVector2D& FAnalogCursor::NewPosition protected
Definition at line 79 of file AnalogCursor.h.
Referenced by UpdateCursorPosition().
StickySlowdown
float FAnalogCursor::StickySlowdown protected
Definition at line 94 of file AnalogCursor.h.
The documentation for this class was generated from the following file:
AnalogCursor.h