Unreal Engine 5.6 C++ API: FSequencerCustomizationManager Class Reference
FSequencerCustomizationManager Class Reference
Manager class for sequencer customizations.
#include "SequencerCustomizationManager.h"
Data Structures
struct FCustomizationRegistryEntry
Public Member Functions
FSequencerCustomizationManager ()
void GetSequencerCustomizations (UMovieSceneSequence *FocusedSequence, TArray< TUniquePtr< ISequencerCustomization > > &OutCustomizations)
Gets the sequencer customizations for the given sequence.
bool NeedsCustomizationChange (const UMovieSceneSequence *OldFocusedSequence, const UMovieSceneSequence *NewFocusedSequence) const
Determines whether the new edited sequence requires changing the customizations.
void RegisterInstancedSequencerCustomization (const UClass *SequenceClass, FOnGetSequencerCustomizationInstance GetCustomizationDelegate)
Registers a sequencer customization against a specific type of sequence.
void UnregisterInstancedSequencerCustomization (const UClass *SequenceClass)
Unregisters a sequencer customization that was previously registered against a specific type of sequence.
Private Member Functions
FSequencerCustomizationManager (const FSequencerCustomizationManager &)=delete
FSequencerCustomizationManager & operator= (const FSequencerCustomizationManager &)=delete
Private Attributes
TArray< FCustomizationRegistryEntry > CustomizationRegistryEntries
Detailed Description
Manager class for sequencer customizations.
Definition at line 138 of file SequencerCustomizationManager.h.
Constructor & Destructor Documentation
FSequencerCustomizationManager() [1/2]
FSequencerCustomizationManager::FSequencerCustomizationManager ()
Referenced by FSequencerCustomizationManager(), and operator=().
FSequencerCustomizationManager() [2/2]
FSequencerCustomizationManager::FSequencerCustomizationManager (const FSequencerCustomizationManager &) private delete
References FSequencerCustomizationManager().
Member Function Documentation
GetSequencerCustomizations()
void FSequencerCustomizationManager::GetSequencerCustomizations (UMovieSceneSequence * FocusedSequence, TArray< TUniquePtr< ISequencerCustomization > > & OutCustomizations)
Gets the sequencer customizations for the given sequence.
NeedsCustomizationChange()
bool FSequencerCustomizationManager::NeedsCustomizationChange (const UMovieSceneSequence * OldFocusedSequence, const UMovieSceneSequence * NewFocusedSequence) const
Determines whether the new edited sequence requires changing the customizations.
operator=()
FSequencerCustomizationManager & FSequencerCustomizationManager::operator= (const FSequencerCustomizationManager &) private delete
References FSequencerCustomizationManager().
RegisterInstancedSequencerCustomization()
void FSequencerCustomizationManager::RegisterInstancedSequencerCustomization (const UClass * SequenceClass, FOnGetSequencerCustomizationInstance GetCustomizationDelegate)
Registers a sequencer customization against a specific type of sequence.
UnregisterInstancedSequencerCustomization()
void FSequencerCustomizationManager::UnregisterInstancedSequencerCustomization (const UClass * SequenceClass)
Unregisters a sequencer customization that was previously registered against a specific type of sequence.
Field Documentation
CustomizationRegistryEntries
TArray<FCustomizationRegistryEntry> FSequencerCustomizationManager::CustomizationRegistryEntries private
Definition at line 172 of file SequencerCustomizationManager.h.
The documentation for this class was generated from the following file:
SequencerCustomizationManager.h