Unreal Engine 5.6 C++ API: UE::MovieScene::FTypelessMutation Struct Reference
UE::MovieScene::FTypelessMutation Struct Reference
Specifies a mask of components to add and remove from an entity.
#include "MovieSceneEntityBuilder.h"
Public Member Functions
FTypelessMutation & Add (std::initializer_list< FComponentTypeID > TypeIDs)
Direct this mutation to add the specified component types to an entity.
FComponentMask MutateType (const FComponentMask &Current) const
Combine our masks into the specified pre-existing mask.
FTypelessMutation & Remove (std::initializer_list< FComponentTypeID > TypeIDs)
Direct this mutation to remove the specified component types to an entity.
FTypelessMutation & RemoveAll ()
Direct this mutation to remove all components from the entity.
Data Fields
FComponentMask AddMask
bool bRemoveAll = false
FComponentMask RemoveMask
Detailed Description
Specifies a mask of components to add and remove from an entity.
Definition at line 34 of file MovieSceneEntityBuilder.h.
Member Function Documentation
Add()
FTypelessMutation & UE::MovieScene::FTypelessMutation::Add (std::initializer_list< FComponentTypeID > TypeIDs) inline
Direct this mutation to add the specified component types to an entity.
Definition at line 44 of file MovieSceneEntityBuilder.h.
References AddMask.
MutateType()
FComponentMask UE::MovieScene::FTypelessMutation::MutateType (const FComponentMask & Current) const inline
Combine our masks into the specified pre-existing mask.
Definition at line 542 of file MovieSceneEntityBuilder.h.
References AddMask, UE::MovieScene::FComponentMask::BitwiseNOT(), bRemoveAll, UE::MovieScene::FComponentMask::CombineWithBitwiseAND(), UE::MovieScene::FComponentMask::CombineWithBitwiseOR(), MaintainSize, MaxSize, OneFillMissingBits, and RemoveMask.
Remove()
FTypelessMutation & UE::MovieScene::FTypelessMutation::Remove (std::initializer_list< FComponentTypeID > TypeIDs) inline
Direct this mutation to remove the specified component types to an entity.
Definition at line 53 of file MovieSceneEntityBuilder.h.
References RemoveMask.
RemoveAll()
FTypelessMutation & UE::MovieScene::FTypelessMutation::RemoveAll () inline
Direct this mutation to remove all components from the entity.
Definition at line 62 of file MovieSceneEntityBuilder.h.
References bRemoveAll.
Field Documentation
AddMask
FComponentMask UE::MovieScene::FTypelessMutation::AddMask
Definition at line 36 of file MovieSceneEntityBuilder.h.
Referenced by Add(), and MutateType().
bRemoveAll
bool UE::MovieScene::FTypelessMutation::bRemoveAll = false
Definition at line 39 of file MovieSceneEntityBuilder.h.
Referenced by MutateType(), and RemoveAll().
RemoveMask
FComponentMask UE::MovieScene::FTypelessMutation::RemoveMask
Definition at line 37 of file MovieSceneEntityBuilder.h.
Referenced by MutateType(), and Remove().
The documentation for this struct was generated from the following file:
MovieSceneEntityBuilder.h