Unreal Engine 5.6 C++ API: FShapedGlyphEntryKey Struct Reference
FShapedGlyphEntryKey Struct Reference
Minimal FShapedGlyphEntry key information used for map lookups.
#include "FontCache.h"
Public Member Functions
FShapedGlyphEntryKey (const FShapedGlyphFaceData &InFontFaceData, uint32 InGlyphIndex, const FFontOutlineSettings &InOutlineSettings)
FORCEINLINE bool operator!= (const FShapedGlyphEntryKey &Other) const
FORCEINLINE bool operator== (const FShapedGlyphEntryKey &Other) const
Private Attributes
TWeakPtr< FFreeTypeFace > FontFace
Weak pointer to the FreeType face to render with.
uint32 FontRenderSize
The size in pixel that Freetype will actually use to render the font, scale included.
float FontSkew
The skew transform amount for the rendered font.
uint32 GlyphIndex
The index of this glyph in the FreeType face.
uint32 KeyHash
Cached hash value used for map lookups.
bool OutlineMiteredCorners
If checked, the outline will have mitered corners, otherwise they will be rounded.
int32 OutlineRenderSize
The size in pixels of the outline to render, scale included.
bool OutlineSeparateFillAlpha
If checked, the outline will be completely translucent where the filled area will be.
Friends
struct FFontCacheStatsKey
class FSlateFontCache
uint32 GetTypeHash (const FShapedGlyphEntryKey &Key)
Detailed Description
Minimal FShapedGlyphEntry key information used for map lookups.
Definition at line 205 of file FontCache.h.
Constructor & Destructor Documentation
FShapedGlyphEntryKey()
FShapedGlyphEntryKey::FShapedGlyphEntryKey (const FShapedGlyphFaceData & InFontFaceData, uint32 InGlyphIndex, const FFontOutlineSettings & InOutlineSettings)
Referenced by GetTypeHash, operator!=(), and operator==().
Member Function Documentation
operator!=()
FORCEINLINE bool FShapedGlyphEntryKey::operator!= (const FShapedGlyphEntryKey & Other) const inline
Definition at line 224 of file FontCache.h.
References FShapedGlyphEntryKey(), FORCEINLINE, and Other.
operator==()
FORCEINLINE bool FShapedGlyphEntryKey::operator== (const FShapedGlyphEntryKey & Other) const inline
Definition at line 213 of file FontCache.h.
References FShapedGlyphEntryKey(), FontFace, FontRenderSize, FontSkew, FORCEINLINE, GlyphIndex, Other, OutlineMiteredCorners, OutlineRenderSize, and OutlineSeparateFillAlpha.
Friends And Related Symbol Documentation
FFontCacheStatsKey
friend struct FFontCacheStatsKey friend
Definition at line 207 of file FontCache.h.
References FFontCacheStatsKey.
Referenced by FFontCacheStatsKey.
FSlateFontCache
friend class FSlateFontCache friend
Definition at line 208 of file FontCache.h.
References FSlateFontCache.
Referenced by FSlateFontCache.
GetTypeHash
uint32 GetTypeHash (const FShapedGlyphEntryKey & Key) friend
Definition at line 229 of file FontCache.h.
References FShapedGlyphEntryKey(), and Key.
Field Documentation
FontFace
TWeakPtr<FFreeTypeFace> FShapedGlyphEntryKey::FontFace private
Weak pointer to the FreeType face to render with.
Definition at line 236 of file FontCache.h.
Referenced by operator==().
FontRenderSize
uint32 FShapedGlyphEntryKey::FontRenderSize private
The size in pixel that Freetype will actually use to render the font, scale included.
Definition at line 238 of file FontCache.h.
Referenced by operator==().
FontSkew
float FShapedGlyphEntryKey::FontSkew private
The skew transform amount for the rendered font.
Definition at line 250 of file FontCache.h.
Referenced by operator==().
GlyphIndex
uint32 FShapedGlyphEntryKey::GlyphIndex private
The index of this glyph in the FreeType face.
Definition at line 246 of file FontCache.h.
Referenced by operator==().
KeyHash
uint32 FShapedGlyphEntryKey::KeyHash private
Cached hash value used for map lookups.
Definition at line 248 of file FontCache.h.
OutlineMiteredCorners
bool FShapedGlyphEntryKey::OutlineMiteredCorners private
If checked, the outline will have mitered corners, otherwise they will be rounded.
See also
FFontOutlineSettings
Definition at line 242 of file FontCache.h.
Referenced by operator==().
OutlineRenderSize
int32 FShapedGlyphEntryKey::OutlineRenderSize private
The size in pixels of the outline to render, scale included.
Definition at line 240 of file FontCache.h.
Referenced by operator==().
OutlineSeparateFillAlpha
bool FShapedGlyphEntryKey::OutlineSeparateFillAlpha private
If checked, the outline will be completely translucent where the filled area will be.
See also
FFontOutlineSettings
Definition at line 244 of file FontCache.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
FontCache.h