Unreal Engine 5.6 C++ API: INavigationQueryFilterInterface Class Reference
INavigationQueryFilterInterface Class Reference abstract
#include "NavQueryFilter.h"
Public Member Functions
virtual ~INavigationQueryFilterInterface ()
virtual INavigationQueryFilterInterface * CreateCopy () const =0
virtual FVector GetAdjustedEndLocation (const FVector &EndLocation) const
virtual void GetAllAreaCosts (float *CostArray, float *FixedCostArray, const int32 Count) const =0
virtual uint16 GetExcludeFlags () const =0
virtual float GetHeuristicScale () const =0
virtual uint16 GetIncludeFlags () const =0
virtual bool IsBacktrackingEnabled () const =0
virtual bool IsEqual (const INavigationQueryFilterInterface *Other) const =0
virtual void Reset ()=0
virtual void SetAllAreaCosts (const float *CostArray, const int32 Count)=0
virtual void SetAreaCost (uint8 AreaType, float Cost)=0
virtual void SetBacktrackingEnabled (const bool bBacktracking)=0
virtual void SetExcludedArea (uint8 AreaType)=0
virtual void SetExcludeFlags (uint16 Flags)=0
virtual void SetFixedAreaEnteringCost (uint8 AreaType, float Cost)=0
virtual void SetIncludeFlags (uint16 Flags)=0
Detailed Description
Definition at line 9 of file NavQueryFilter.h.
Constructor & Destructor Documentation
~INavigationQueryFilterInterface()
virtual INavigationQueryFilterInterface::~INavigationQueryFilterInterface () inline virtual
Definition at line 12 of file NavQueryFilter.h.
Member Function Documentation
CreateCopy()
virtual INavigationQueryFilterInterface * INavigationQueryFilterInterface::CreateCopy () const pure virtual
Referenced by FNavigationQueryFilter::SetFilterImplementation().
GetAdjustedEndLocation()
virtual FVector INavigationQueryFilterInterface::GetAdjustedEndLocation (const FVector & EndLocation) const inline virtual
Definition at line 29 of file NavQueryFilter.h.
References FVector.
GetAllAreaCosts()
virtual void INavigationQueryFilterInterface::GetAllAreaCosts (float * CostArray, float * FixedCostArray, const int32 Count) const pure virtual
References Count.
GetExcludeFlags()
virtual uint16 INavigationQueryFilterInterface::GetExcludeFlags () const pure virtual
GetHeuristicScale()
virtual float INavigationQueryFilterInterface::GetHeuristicScale () const pure virtual
GetIncludeFlags()
virtual uint16 INavigationQueryFilterInterface::GetIncludeFlags () const pure virtual
IsBacktrackingEnabled()
virtual bool INavigationQueryFilterInterface::IsBacktrackingEnabled () const pure virtual
IsEqual()
virtual bool INavigationQueryFilterInterface::IsEqual (const INavigationQueryFilterInterface * Other) const pure virtual
References Other.
Referenced by FNavigationQueryFilter::operator==().
Reset()
virtual void INavigationQueryFilterInterface::Reset () pure virtual
Referenced by FNavigationQueryFilter::Reset().
SetAllAreaCosts()
virtual void INavigationQueryFilterInterface::SetAllAreaCosts (const float * CostArray, const int32 Count) pure virtual
References Count.
SetAreaCost()
virtual void INavigationQueryFilterInterface::SetAreaCost (uint8 AreaType, float Cost) pure virtual
SetBacktrackingEnabled()
virtual void INavigationQueryFilterInterface::SetBacktrackingEnabled (const bool bBacktracking) pure virtual
SetExcludedArea()
virtual void INavigationQueryFilterInterface::SetExcludedArea (uint8 AreaType) pure virtual
SetExcludeFlags()
virtual void INavigationQueryFilterInterface::SetExcludeFlags (uint16 Flags) pure virtual
References Flags.
SetFixedAreaEnteringCost()
virtual void INavigationQueryFilterInterface::SetFixedAreaEnteringCost (uint8 AreaType, float Cost) pure virtual
SetIncludeFlags()
virtual void INavigationQueryFilterInterface::SetIncludeFlags (uint16 Flags) pure virtual
References Flags.
The documentation for this class was generated from the following file:
NavQueryFilter.h