Unreal Engine 5.6 C++ API: UE::Sequencer::FAddKeyOperation Struct Reference
UE::Sequencer::FAddKeyOperation Struct Reference
Temporary structure used for consistent add-key behavior for a set of display nodes Ultimately the operation will call ISequencerTrackEditor::ProcessKeyOperation for each track editor that needs to add keys.
#include "SequencerAddKeyOperation.h"
Public Member Functions
void Commit (FFrameNumber InKeyTime, ISequencer &InSequencer, TArray< FAddKeyResult > *OutResults=nullptr)
Commit this operation by choosing the section(s) to key for each key area, and adding a key at the specified time.
Static Public Member Functions
static FAddKeyOperation FromKeyAreas (ISequencerTrackEditor *TrackEditor, const TArrayView< TSharedRef< IKeyArea > > InKeyAreas)
Construct an operation from some key areas on a track.
static FAddKeyOperation FromNode (TWeakPtr< FViewModel > InModel)
Construct an operation from a single display node.
static FAddKeyOperation FromNodes (const TSet< TWeakViewModelPtr< IOutlinerExtension > > &InModels)
Construct an operation from any set of display nodes.
Private Member Functions
FAddKeyOperation ()
void AddPreFilteredNodes (TArrayView< const TWeakPtr< FViewModel > > InNodes)
Add a set of nodes to this operation that have already had child nodes removed (ie only parent nodes should exist in the set)
bool ConsiderKeyableAreas (TSharedPtr< ITrackExtension > InTrackModel, FViewModelPtr InKeyAnythingBeneath)
Add any keyable areas to the list of potential things to key.
FKeyOperation & GetTrackOperation (ISequencerTrackEditor *TrackEditor)
Retrieve the operation that relates to a specific track editor instance.
bool ProcessKeyArea (ISequencerTrackEditor *InTrackEditor, TSharedPtr< IKeyArea > InKeyArea)
Add a key area to this operation.
bool ProcessKeyArea (TSharedPtr< ITrackExtension > InTrackModel, TViewModelPtr< FChannelGroupModel > InChannelGroupModel)
Add key areas for a key area display node to this operation.
Private Attributes
TMap< ISequencerTrackEditor *, FKeyOperation > OperationsByTrackEditor
Map of key operations stored by their track editor.
Detailed Description
Temporary structure used for consistent add-key behavior for a set of display nodes Ultimately the operation will call ISequencerTrackEditor::ProcessKeyOperation for each track editor that needs to add keys.
Definition at line 37 of file SequencerAddKeyOperation.h.
Constructor & Destructor Documentation
FAddKeyOperation()
UE::Sequencer::FAddKeyOperation::FAddKeyOperation () inline private
Definition at line 112 of file SequencerAddKeyOperation.h.
Referenced by FromKeyAreas(), FromNode(), and FromNodes().
Member Function Documentation
AddPreFilteredNodes()
void UE::Sequencer::FAddKeyOperation::AddPreFilteredNodes (TArrayView< const TWeakPtr< FViewModel > > InNodes) private
Add a set of nodes to this operation that have already had child nodes removed (ie only parent nodes should exist in the set)
Parameters
InNodes A set of nodes to add to this operation that contains no child nodes
Commit()
void UE::Sequencer::FAddKeyOperation::Commit (FFrameNumber InKeyTime, ISequencer & InSequencer, TArray< FAddKeyResult > * OutResults = nullptr)
Commit this operation by choosing the section(s) to key for each key area, and adding a key at the specified time.
Parameters
InKeyTime The time to add keys at
InSequencer The sequencer instance that is performing this operations &param OutResults The key handles that were added with this operation
ConsiderKeyableAreas()
bool UE::Sequencer::FAddKeyOperation::ConsiderKeyableAreas (TSharedPtr< ITrackExtension > InTrackModel, FViewModelPtr InKeyAnythingBeneath) private
Add any keyable areas to the list of potential things to key.
Parameters
InTrackEditor The track editor
InKeyAnythingBeneath A node to search within for key areas
FromKeyAreas()
FAddKeyOperation UE::Sequencer::FAddKeyOperation::FromKeyAreas (ISequencerTrackEditor * TrackEditor, const TArrayView< TSharedRef< IKeyArea > > InKeyAreas) static
Construct an operation from some key areas on a track.
References FAddKeyOperation().
FromNode()
FAddKeyOperation UE::Sequencer::FAddKeyOperation::FromNode (TWeakPtr< FViewModel > InModel) static
Construct an operation from a single display node.
Every key area underneath this node will receive keys.
References FAddKeyOperation().
FromNodes()
FAddKeyOperation UE::Sequencer::FAddKeyOperation::FromNodes (const TSet< TWeakViewModelPtr< IOutlinerExtension > > & InModels) static
Construct an operation from any set of display nodes.
Each node in the set will receive keys for all decendant key areas.
Parameters
InModels A set of all the models to key
References FAddKeyOperation().
GetTrackOperation()
FKeyOperation & UE::Sequencer::FAddKeyOperation::GetTrackOperation (ISequencerTrackEditor * TrackEditor) private
Retrieve the operation that relates to a specific track editor instance.
ProcessKeyArea() [1/2]
bool UE::Sequencer::FAddKeyOperation::ProcessKeyArea (ISequencerTrackEditor * InTrackEditor, TSharedPtr< IKeyArea > InKeyArea) private
Add a key area to this operation.
Parameters
InTrackEditor The track editor responsible for the key area
InKeyArea The key area to add
ProcessKeyArea() [2/2]
bool UE::Sequencer::FAddKeyOperation::ProcessKeyArea (TSharedPtr< ITrackExtension > InTrackModel, TViewModelPtr< FChannelGroupModel > InChannelGroupModel) private
Add key areas for a key area display node to this operation.
Parameters
InTrackNode The current track node
InKeyAreaNode The key area node to add key areas from
Field Documentation
OperationsByTrackEditor
TMap<ISequencerTrackEditor*, FKeyOperation> UE::Sequencer::FAddKeyOperation::OperationsByTrackEditor private
Map of key operations stored by their track editor.
Definition at line 115 of file SequencerAddKeyOperation.h.
The documentation for this struct was generated from the following file:
SequencerAddKeyOperation.h