Unreal Engine 5.6 C++ API: SCompoundWidget Class Reference
SCompoundWidget Class Reference
A CompoundWidget is the base from which most non-primitive widgets should be built.
#include "SCompoundWidget.h"
Inherits SWidget.
Inherited by SMediaPermutationsSelector< ItemType, ItemBuilder >, SNumericRotatorInputBox< float >, SNumericVectorInputBox< float, UE::Math::TVector< float >, 3 >, SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >, SSpinBox< float >, IAnimAssetFindReplace, IAnimSequenceCurveEditor, IAnimationSequenceBrowser, IPersonaViewport, ISinglePropertyView, ISocketManager, PropertyInfoViewStyle::SExpanderArrow, PropertyInfoViewStyle::SIndent, PropertyInfoViewStyle::STextHighlightOverlay, SAboutScreen, SActorEditorContext, SAnimAttributeView, SAnimAttributeViewer, SAnimationCompressionSelectionDialog, SAppIconWidget, SAssetEditorViewportsOverlay, SAudioInputWidget, SAudioOscilloscopePanelWidget, SAudioSpectrogram, SAudioSpectrumPlot, SAudioTextBox, SBackgroundBlur, SBlueprintDiff, SBlueprintEditorSelectedDebugObjectWidget, SBlueprintNamespaceEntry, SBlueprintRevisionMenu, SBoneMappingBase, SBoneSelectionWidget, SBoneTreeMenu, SBorder, SBreadcrumbTrailBase, SBuildProgressWidget, SCSVImportOptions, SCheckBox, SClassPickerDialog, SClassPropertyEntryBox, SCollectionSpreadSheet, SCollectionSpreadSheetWidget, SCommentBubble, SComplexGradient, SComponentClassCombo, SContentReference, SCreateAssetFromObject, SCreateClothingSettingsPanel, SCreditsScreen, SCurveEditorFilterPanel, SCurveEditorPanel, SCurveEditorToolProperties, SCurveEditorTreeFilterStatusBar, SCurveEditorTreePin, SCurveEditorTreeSelect, SCurveEditorTreeTextFilter, SCurveEditorView, SCurveKeyDetailPanel, SDataflowMembersWidget, SDataflowSimulationPanel, SDefaultGraphActionWidget, SDeleteAssetsDialog, SDesignSurface, SDetailsDiff, SDetailsSplitter, SEditorViewport, SEditorViewportToolBarButton, SEditorViewportToolbarMenu, SErrorHint, SExpandableArea, SExpanderArrow, SExtensionPanel, SFacesOutliner, SFilterableObjectList, SFindInBlueprints, SFindInGraph, SFixedSampledSequenceRuler, SFixedSampledSequenceViewerPanel, SFixupSelfContextDialog, SFxWidget, SGameLayerManager, SGenericDialogWidget, SGlobalPlayWorldActions, SGraphActionMenu, SGraphEditor, SGraphPalette, SGraphPaletteItem, SGraphPreviewer, SGridLineSpacingList, SInputKeySelector, SInvalidationPanel, SKeyEditInterface, SKeySelector, SKismetDebugTreeView, SKismetInspector, SLazyToolTip, SListView< ItemType >::SListViewPinnedRowWidget, SListViewSelectorDropdownMenu< ListType >, SLoadGuard, SMaterialSlotWidget, SMediaPermutationsSelector< ItemType, ItemBuilder >, SMenuOwner, SMiniCurveEditor, SModalEditorDialog< ResultType >, SModeWidget, SMotionTrailOptions, SMultiBlockBaseWidget, SMyBlueprint, SNameComboBox, SNodeTitle, SNotificationItem, SNotificationList, SNumericDropDown< NumericType >, SNumericEntryBox< NumericType >, SNumericRotatorInputBox< NumericType >, SNumericTextBlockKeyEditor< ChannelType, NumericType >, SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >, SObjectBindingTag, SObjectBindingTags, SObjectPropertyEntryBox, SOutputLogDialog, SOverridePropertiesWidget, SPersonaToolbox, SPinComboBox, SPinValueInspector, SPopup, SPreviewSceneProfileSelector, SPrivateAssetsDialog, SProperty, SReadOnlyHierarchyView, SReferenceSectionSelectionWidget, SReferenceTree, SResetToDefaultMenu, SResetToDefaultPropertyEditor, SRigVMBulkEditWidget, SRigVMChangesTreeView, SRigVMDetailsInspector, SRigVMEditorGraphExplorer, SRigVMEditorSelectedDebugObjectWidget, SRigVMEnumPicker, SRigVMExecutionStackView, SRigVMFindReferences, SRigVMGraphBreakLinksWidget, SRigVMGraphChangePinType, SRigVMGraphFunctionBulkEditWidget, SRigVMGraphFunctionLocalizationWidget, SRigVMGraphVariableBinding, SRigVMNodePreviewWidget, SRigVMSwapAssetReferencesWidget, SRigVMSwapFunctionsWidget, SRigVMUserDataPath, SRigVMVariableMappingWidget, SSCSEditor, SScalabilitySettings, SScaleBox, SScrollBorder, SScrollBox, SSegmentedControl< OptionType >, SSelectionView, SSelectionViewWidget, SSequencerFilter, SSequencerSearchBox, SSimpleGradient, SSkeletonBoneRemoval, SSkeletonSelectorWindow, SSkeletonWidget, SSkinWeightProfileImportOptions, SSpinBox< NumericType >, SStandaloneCustomizedValueWidget, SStructPropertyEntryBox, SSubMenuHandler, SSuggestionTextBox, STabDrawer, STableViewBase, STextComboBox, STextComboPopup, STextEntryPopup, STextScroller, SThrobber, STimecodeProvider, SToolTip, STransformOutliner, SUserWidget, SVPBookmarkListView, SVector2DSlider< NumericType >, SVector2DTextBox< NumericType >, SVector4Slider< NumericType >, SVector4TextBox< NumericType >, SVectorSlider< NumericType >, SVectorTextBox< NumericType >, SVerticesOutliner, SViewport, SViewportToolBar, SViewportToolBarComboMenu, SViewportToolBarIconMenu, SVolumeControl, SWindow, SWindowTitleBar, SWorldPartitionBuildNavigationDialog, SWorldPartitionViewportWidget, SZoomPan, UE::Insights::SAdvancedFilter, UE::Insights::SAsyncOperationStatus, UE::Insights::SFilterConfigurator, UE::Insights::STableTreeView, UE::Insights::STableTreeViewCell, UE::Sequencer::SOutlinerColumnButton, UE::Sequencer::SOutlinerItemViewBase, UE::Sequencer::SOutlinerTrackColorPicker, and UE::Sequencer::STrackAreaLaneView.
Data Structures
struct FCompoundWidgetOneChildSlot
Public Member Functions
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
FLinearColor GetColorAndOpacity () const
Gets the widget's color.
void SetColorAndOpacity (TAttribute< FLinearColor > InColorAndOpacity)
Sets the widget's color.
void SetForegroundColor (TAttribute< FSlateColor > InForegroundColor)
Sets the widget's foreground color.
SLATE_DECLARE_WIDGET_API (SCompoundWidget, SWidget, 1) public
Returns the size scaling factor for this widget.
Private Attributes
TSlateAttribute< FLinearColor > ColorAndOpacityAttribute
The color and opacity to apply to this widget and all its descendants.
TSlateAttribute< FVector2D > ContentScaleAttribute
The layout scale to apply to this widget's contents; useful for animation.
TSlateAttribute< FSlateColor > ForegroundColorAttribute
Optional foreground color that will be inherited by all of this widget's contents.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A CompoundWidget is the base from which most non-primitive widgets should be built.
CompoundWidgets have a protected member named ChildSlot.
Definition at line 21 of file SCompoundWidget.h.
Constructor & Destructor Documentation
SCompoundWidget()
SCompoundWidget::SCompoundWidget () protected
Disallow public construction.
Referenced by SBackgroundBlur::SLATE_DECLARE_WIDGET_API(), SBorder::SLATE_DECLARE_WIDGET_API(), SLATE_DECLARE_WIDGET_API(), SExpanderArrow::SLATE_DECLARE_WIDGET_API(), and SScaleBox::SLATE_DECLARE_WIDGET_API().
~SCompoundWidget()
virtual SCompoundWidget::~SCompoundWidget () protected virtual
Member Function Documentation
ComputeDesiredSize()
virtual FVector2D SCompoundWidget::ComputeDesiredSize (float LayoutScaleMultiplier) const override protected virtual
Compute the ideal size necessary to display this widget.
For aggregate widgets (e.g. panels) this size should include the size necessary to show all of its children. CacheDesiredSize() guarantees that the size of descendants is computed and cached before that of the parents, so it is safe to call GetDesiredSize() for any children while implementing this method.
Note that ComputeDesiredSize() is meant as an aide to the developer. It is NOT meant to be very robust in many cases. If your widget is simulating a bouncing ball, you should just return a reasonable size; e.g. 160x160. Let the programmer set up a reasonable rule of resizing the bouncy ball simulation.
Parameters
LayoutScaleMultiplier This parameter is safe to ignore for almost all widgets; only really affects text measuring.
Returns
The desired size.
Implements SWidget.
Reimplemented in SAudioMaterialLabeledKnob, SAudioMaterialLabeledSlider, SAudioRadialSlider, SAudioSliderBase, SBorder, SButton, SComplexGradient, SCurveEditorEventChannelView, SCurveEditorKeyBarView, SCurveEditorView, SCurveEditorViewStacked, SExpandableArea, SFixedSampledSequenceRuler, SFxWidget, SKeyEditInterface, SLoadGuard, SObjectBindingTag, SOutputLogDialog, SScaleBox, SSeparator, STabDrawer, SViewport, SVirtualWindow, SWindow, and UE::Sequencer::SOutlinerViewRow.
Referenced by SObjectBindingTag::ComputeDesiredSize().
GetChildren()
virtual FChildren * SCompoundWidget::GetChildren () override virtual
Returns the useful children (if any) of this widget.
Some widget type may hide widget if they are needed by the system. Allows for iteration over the Widget's children regardless of how they are actually stored.
Note
Should be renamed to GetVisibleChildren (not ALL children will be returned in all cases).
Implements SWidget.
Reimplemented in SInvalidationPanel.
GetColorAndOpacity()
FLinearColor SCompoundWidget::GetColorAndOpacity () const inline private
Gets the widget's color.
Definition at line 50 of file SCompoundWidget.h.
References ColorAndOpacityAttribute.
GetColorAndOpacityAttribute()
TSlateAttributeRef< FLinearColor > SCompoundWidget::GetColorAndOpacityAttribute () const inline protected
Returns
an attribute reference of ColorAndOpacity
Definition at line 95 of file SCompoundWidget.h.
References ColorAndOpacityAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetContentScaleAttribute()
TSlateAttributeRef< FVector2D > SCompoundWidget::GetContentScaleAttribute () const inline protected
Returns
an attribute reference of ContentScale
Definition at line 92 of file SCompoundWidget.h.
References ContentScaleAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetForegroundColor()
virtual FSlateColor SCompoundWidget::GetForegroundColor () const override virtual
Returns
the Foreground color that this widget sets; unset options if the widget does not set a foreground color
Reimplemented from SWidget.
Reimplemented in SButton, SCheckBox, SCommentBubble, and SDockTab.
GetForegroundColorAttribute()
TSlateAttributeRef< FSlateColor > SCompoundWidget::GetForegroundColorAttribute () const inline protected
Returns
an attribute reference of ForegroundColor
Definition at line 98 of file SCompoundWidget.h.
References ForegroundColorAttribute, and TSharedFromThis< SWidget >::SharedThis().
OnArrangeChildren()
virtual void SCompoundWidget::OnArrangeChildren (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren) const override virtual
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
Each type of Layout panel should arrange children based on desired behavior.
Parameters
AllottedGeometry The geometry allotted for this widget by its parent.
ArrangedChildren The array to which to add the WidgetGeometries that represent the arranged children.
Implements SWidget.
Reimplemented in SFxWidget, SScaleBox, STabDrawer, STextScroller, SViewport, SVirtualWindow, SZoomPan, and UE::Sequencer::SOutlinerViewRow.
OnPaint()
virtual int32 SCompoundWidget::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Implements SWidget.
Reimplemented in FArguments< ItemType >, PropertyInfoViewStyle::SIndent, SAudioSpectrogram, SAudioSpectrumPlot, SBackgroundBlur, SBorder, SButton, SComplexGradient, SCurveViewerPanel, SDesignSurface, SDetailsSplitter, SExpanderArrow, SFixedSampledSequenceRuler, SFxWidget, SGameLayerManager, SInteractiveCurveEditorView, SInvalidationPanel, SNotificationBackground, SPopup, SScaleBox, SScrollBox, SSimpleGradient, SSpinBox< NumericType >, SSpinBox< float >, STabDrawer, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, STableViewBase, STextScroller, SViewport, SVirtualWindow, SWindow, UE::Sequencer::SChannelView, UE::Sequencer::SOutlinerView, and UE::Sequencer::SOutlinerViewRow.
References SWidget::FSlateWindowElementList.
SetColorAndOpacity()
void SCompoundWidget::SetColorAndOpacity (TAttribute< FLinearColor > InColorAndOpacity) inline private
Sets the widget's color.
Parameters
InColorAndOpacity The ColorAndOpacity to be applied to this widget and all its contents.
Definition at line 60 of file SCompoundWidget.h.
References ColorAndOpacityAttribute, and MoveTemp().
SetForegroundColor()
void SCompoundWidget::SetForegroundColor (TAttribute< FSlateColor > InForegroundColor) inline private
Sets the widget's foreground color.
Parameters
InColor The color to set.
Definition at line 70 of file SCompoundWidget.h.
References ForegroundColorAttribute, and MoveTemp().
Referenced by FArguments< ItemType >::ConstructInternal().
SetVisibility()
virtual void SCompoundWidget::SetVisibility (TAttribute< EVisibility > InVisibility) final override virtual
Parameters
InVisibility should this widget be
Reimplemented from SWidget.
SLATE_DECLARE_WIDGET_API()
SCompoundWidget::SLATE_DECLARE_WIDGET_API (SCompoundWidget , SWidget , 1) inline private
Returns the size scaling factor for this widget.
Returns
Size scaling factor. Sets the content scale for this widget.
Parameters
InContentScale Content scaling factor.
Definition at line 23 of file SCompoundWidget.h.
References SCompoundWidget(), SWidget::SWidget(), and ContentScaleAttribute.
Field Documentation
ChildSlot
FCompoundWidgetOneChildSlot SCompoundWidget::ChildSlot protected
The slot that contains this widget's descendants.
Definition at line 113 of file SCompoundWidget.h.
Referenced by SNumericEntryBox< NumericType >::Construct(), SNumericRotatorInputBox< float >::Construct(), SUserWidget::Construct(), FArguments< ItemType >::ConstructChildren(), SMultiColumnTableRow< ItemType >::ConstructChildren(), SViewport::GetContent(), SSegmentedControl< OptionType >::RebuildChildren(), SMultiBoxWidget::SetContent(), SAppIconWidget::SetIcon(), SAppIconWidget::SLATE_ATTRIBUTE(), SListViewSelectorDropdownMenu< ListType >::SLATE_DEFAULT_SLOT(), SBreadcrumbTrail< ItemType >::SLATE_END_ARGS(), SGridLineSpacingList::SLATE_END_ARGS(), STileView< ItemType >::SLATE_END_ARGS(), SVector2DTextBox< NumericType >::SLATE_END_ARGS(), SVector4TextBox< NumericType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), SNumericDropDown< NumericType >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
ColorAndOpacityAttribute
TSlateAttribute<FLinearColor> SCompoundWidget::ColorAndOpacityAttribute private
The color and opacity to apply to this widget and all its descendants.
Definition at line 120 of file SCompoundWidget.h.
Referenced by GetColorAndOpacity(), GetColorAndOpacityAttribute(), and SetColorAndOpacity().
ContentScaleAttribute
TSlateAttribute<FVector2D> SCompoundWidget::ContentScaleAttribute private
The layout scale to apply to this widget's contents; useful for animation.
Definition at line 117 of file SCompoundWidget.h.
Referenced by GetContentScaleAttribute(), and SLATE_DECLARE_WIDGET_API().
ForegroundColorAttribute
TSlateAttribute<FSlateColor> SCompoundWidget::ForegroundColorAttribute private
Optional foreground color that will be inherited by all of this widget's contents.
Definition at line 123 of file SCompoundWidget.h.
Referenced by GetForegroundColorAttribute(), and SetForegroundColor().
The documentation for this class was generated from the following file:
SCompoundWidget.h