Unreal Engine 5.6 C++ API: IAsyncReadRequest Class Reference
IAsyncReadRequest Class Reference abstract
#include "AsyncFileHandle.h"
Public Member Functions
FORCEINLINE IAsyncReadRequest (FAsyncFileCallBack *InCallback, bool bInSizeRequest, uint8 *UserSuppliedMemory)
virtual ~IAsyncReadRequest ()
FORCEINLINE void Cancel ()
Cancel the request.
virtual void EnsureCompletion ()
Waits for the request to complete, with an additional guarantee that the second consecutive call won't ever block, which is not a case for WaitCompletion().
FORCEINLINE uint8 * GetReadResults ()
Return the bytes of a completed read request.
FORCEINLINE int64 GetSizeResults ()
Return the size of a completed size request.
FORCEINLINE bool PollCompletion ()
Nonblocking poll of the state of completion.
FORCEINLINE bool WaitCompletion (float TimeLimitSeconds=0.0f)
Waits for the request to complete, but not longer than the given time limit.
Public Member Functions inherited from IAsyncReadRequestFixLayout
virtual ~IAsyncReadRequestFixLayout ()=default
Protected Member Functions
virtual void CancelImpl ()=0
Cancel the request.
virtual void ReleaseMemoryOwnershipImpl ()=0
Transfer ownership of Memory from the async request to the outside caller (called in response to GetReadResults).
void SetAllComplete ()
void SetComplete ()
void SetDataComplete ()
TSAN_ATOMIC (bool) bCanceled
TSAN_ATOMIC (bool) bCompleteAndCallbackCalled
TSAN_ATOMIC (bool) bCompleteSync
TSAN_ATOMIC (bool) bDataIsReady
virtual void WaitCompletionImpl (float TimeLimitSeconds)=0
Waits for the request to complete, but not longer than the given time limit.
Protected Attributes
union {
uint8 * Memory
PTRINT Size
};
const bool bSizeRequest
const bool bUserSuppliedMemory
FAsyncFileCallBack Callback
Detailed Description
Definition at line 30 of file AsyncFileHandle.h.
Constructor & Destructor Documentation
IAsyncReadRequest()
FORCEINLINE IAsyncReadRequest::IAsyncReadRequest (FAsyncFileCallBack * InCallback, bool bInSizeRequest, uint8 * UserSuppliedMemory) inline
Definition at line 47 of file AsyncFileHandle.h.
References bSizeRequest, bUserSuppliedMemory, Callback, check, FORCEINLINE, INC_DWORD_STAT, Memory, and Size.
Referenced by FAsyncReadRequestNull::FAsyncReadRequestNull().
~IAsyncReadRequest()
virtual IAsyncReadRequest::~IAsyncReadRequest () inline virtual
Definition at line 73 of file AsyncFileHandle.h.
References bSizeRequest, DEC_DWORD_STAT, Fatal, LogHAL, Memory, TEXT, and UE_CLOG.
Member Function Documentation
Cancel()
FORCEINLINE void IAsyncReadRequest::Cancel () inline
Cancel the request.
This is a non-blocking async call and so does not ensure completion!
Definition at line 120 of file AsyncFileHandle.h.
References CancelImpl(), FORCEINLINE, FAndroidMisc::MemoryBarrier(), and PollCompletion().
CancelImpl()
virtual void IAsyncReadRequest::CancelImpl () protected pure virtual
Cancel the request.
This is a non-blocking async call and so does not ensure completion!
Implemented in FAsyncReadRequestNull.
Referenced by Cancel().
EnsureCompletion()
virtual void IAsyncReadRequest::EnsureCompletion () inline virtual
Waits for the request to complete, with an additional guarantee that the second consecutive call won't ever block, which is not a case for WaitCompletion().
Definition at line 110 of file AsyncFileHandle.h.
References WaitCompletionImpl().
GetReadResults()
FORCEINLINE uint8 * IAsyncReadRequest::GetReadResults () inline
Return the bytes of a completed read request.
Not legal to call unless the request is complete.
Returns
Returned memory block which if non-null contains the bytes read. Caller owns the memory block and must call FMemory::Free on it when done. Can be null if the file was not found or could not be read or the request was cancelled, or the request had AIOP_FLAG_PRECACHE.
Definition at line 148 of file AsyncFileHandle.h.
References bSizeRequest, bUserSuppliedMemory, check, FORCEINLINE, Memory, and ReleaseMemoryOwnershipImpl().
GetSizeResults()
FORCEINLINE int64 IAsyncReadRequest::GetSizeResults () inline
Return the size of a completed size request.
Not legal to call unless the request is complete.
Returns
Returned size of the file or -1 if the file was not found, the request was canceled or other error.
Definition at line 138 of file AsyncFileHandle.h.
References bSizeRequest, check, FORCEINLINE, and Size.
PollCompletion()
FORCEINLINE bool IAsyncReadRequest::PollCompletion () inline
Nonblocking poll of the state of completion.
Returns
true if the request is complete
Definition at line 86 of file AsyncFileHandle.h.
References FORCEINLINE.
Referenced by Cancel(), and WaitCompletion().
ReleaseMemoryOwnershipImpl()
virtual void IAsyncReadRequest::ReleaseMemoryOwnershipImpl () protected pure virtual
Transfer ownership of Memory from the async request to the outside caller (called in response to GetReadResults).
It's only relevant to Read requests, in which case the most common use is to update (decrease) the STAT_AsyncFileMemory stat which is typically incremented when async requests allocate Memory. It doesn't play any role in Size requests, so it may be left empty for them.
Implemented in FAsyncReadRequestNull.
Referenced by GetReadResults().
SetAllComplete()
void IAsyncReadRequest::SetAllComplete () inline protected
Definition at line 197 of file AsyncFileHandle.h.
References FAndroidMisc::MemoryBarrier().
Referenced by SetComplete().
SetComplete()
void IAsyncReadRequest::SetComplete () inline protected
Definition at line 203 of file AsyncFileHandle.h.
References SetAllComplete(), and SetDataComplete().
Referenced by FAsyncReadRequestNull::FAsyncReadRequestNull().
SetDataComplete()
void IAsyncReadRequest::SetDataComplete () inline protected
Definition at line 186 of file AsyncFileHandle.h.
References Callback, and FAndroidMisc::MemoryBarrier().
Referenced by SetComplete().
TSAN_ATOMIC() [1/4]
IAsyncReadRequest::TSAN_ATOMIC (bool) protected
TSAN_ATOMIC() [2/4]
IAsyncReadRequest::TSAN_ATOMIC (bool) protected
TSAN_ATOMIC() [3/4]
IAsyncReadRequest::TSAN_ATOMIC (bool) protected
TSAN_ATOMIC() [4/4]
IAsyncReadRequest::TSAN_ATOMIC (bool) protected
WaitCompletion()
FORCEINLINE bool IAsyncReadRequest::WaitCompletion (float TimeLimitSeconds = 0.0f) inline
Waits for the request to complete, but not longer than the given time limit.
Parameters
TimeLimitSeconds Zero to wait forever, otherwise the maximum amount of time to wait.
Returns
true if the request is complete
Definition at line 96 of file AsyncFileHandle.h.
References FORCEINLINE, PollCompletion(), and WaitCompletionImpl().
WaitCompletionImpl()
virtual void IAsyncReadRequest::WaitCompletionImpl (float TimeLimitSeconds) protected pure virtual
Waits for the request to complete, but not longer than the given time limit.
Parameters
TimeLimitSeconds Zero to wait forever, otherwise the maximum amount of time to wait.
Returns
true if the request is complete
Implemented in FAsyncReadRequestNull.
Referenced by EnsureCompletion(), and WaitCompletion().
Field Documentation
[union]
union { ... } IAsyncReadRequest
bSizeRequest
const bool IAsyncReadRequest::bSizeRequest protected
Definition at line 43 of file AsyncFileHandle.h.
Referenced by IAsyncReadRequest(), ~IAsyncReadRequest(), GetReadResults(), and GetSizeResults().
bUserSuppliedMemory
const bool IAsyncReadRequest::bUserSuppliedMemory protected
Definition at line 44 of file AsyncFileHandle.h.
Referenced by IAsyncReadRequest(), and GetReadResults().
Callback
FAsyncFileCallBack IAsyncReadRequest::Callback protected
Definition at line 38 of file AsyncFileHandle.h.
Referenced by IAsyncReadRequest(), and SetDataComplete().
Memory
uint8* IAsyncReadRequest::Memory
Definition at line 36 of file AsyncFileHandle.h.
Referenced by IAsyncReadRequest(), ~IAsyncReadRequest(), and GetReadResults().
Size
PTRINT IAsyncReadRequest::Size
Definition at line 35 of file AsyncFileHandle.h.
Referenced by IAsyncReadRequest(), and GetSizeResults().
The documentation for this class was generated from the following file:
AsyncFileHandle.h