Unreal Engine 5.6 C++ API: FStreamingManagerCollection Struct Reference
FStreamingManagerCollection Struct Reference
Streaming manager collection, routing function calls to streaming managers that have been added via AddStreamingManager.
#include "ContentStreaming.h"
Public Member Functions
FStreamingManagerCollection ()
Default constructor, initializing all member variables.
~FStreamingManagerCollection ()
virtual void AddLevel (class ULevel *Level) override
Adds a ULevel to the streaming manager.
void AddStreamingManager (IStreamingManager *StreamingManager)
Adds a streaming manager to the array of managers to route function calls to.
virtual int32 BlockTillAllRequestsFinished (float TimeLimit=0.0f, bool bLogResults=false) override
Blocks till all pending requests are fulfilled.
virtual void CancelForcedResources () override
Cancels the timed Forced resources (i.e used the Kismet action "Stream In Textures").
void DisableResourceStreaming ()
Disables resource streaming.
void EnableResourceStreaming ()
Enables resource streaming, previously disabled with enableResourceStreaming.
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar) override
Allows the streaming manager to process exec commands.
IAnimationStreamingManager & GetAnimationStreamingManager () const
Gets a reference to the Animation Streaming Manager interface.
IAudioStreamingManager & GetAudioStreamingManager () const
Gets a reference to the Audio Streaming Manager interface.
Nanite::FCoarseMeshStreamingManager * GetNaniteCoarseMeshStreamingManager () const
Gets a reference to the Nanite Coarse Mesh Streaming Manager.
virtual int32 GetNumWantingResources () const override
Returns the number of resources that currently wants to be streamed in.
virtual int32 GetNumWantingResourcesID () const override
Returns the current ID for GetNumWantingResources().
IRenderAssetStreamingManager & GetRenderAssetStreamingManager () const
Get the streaming manager for textures and meshes.
IRenderAssetStreamingManager & GetTextureStreamingManager () const
Gets a reference to the Texture Streaming Manager interface.
struct FVirtualTextureChunkStreamingManager & GetVirtualTextureStreamingManager () const
Gets a reference to the Virtual Texture Streaming Manager.
bool IsRenderAssetStreamingEnabled (EStreamableRenderAssetType FilteredAssetType) const
Checks whether texture/mesh streaming is enabled.
bool IsStreamingEnabled () const
Checks whether any kind of streaming is active.
bool IsTextureStreamingEnabled () const
Checks whether texture streaming is enabled.
virtual void NotifyActorDestroyed (AActor *Actor) override
Called when a spawned actor is destroyed.
virtual void NotifyLevelChange () override
Notifies manager of "level" change.
virtual void NotifyLevelOffset (class ULevel *Level, const FVector &Offset) override
Notifies manager that level primitives were shifted.
virtual void NotifyPrimitiveDetached (const UPrimitiveComponent *Primitive) override
Called when a primitive is detached from an actor or another component.
virtual void NotifyPrimitiveUpdated (const UPrimitiveComponent *Primitive) override
Called when a primitive streaming data needs to be updated.
virtual void NotifyPrimitiveUpdated_Concurrent (const UPrimitiveComponent *Primitive) override
Called when a primitive streaming data needs to be updated in the last stage of the frame.
virtual void OnAudioStreamingParamsChanged () override
void PropagateLightingScenarioChange () override
Propagates a change to the active lighting scenario.
virtual void RemoveLevel (class ULevel *Level) override
Removes a ULevel from the streaming manager.
void RemoveStreamingManager (IStreamingManager *StreamingManager)
Removes a streaming manager from the array of managers to route function calls to.
virtual void SetDisregardWorldResourcesForFrames (int32 NumFrames) override
Don't stream world resources for the next NumFrames.
void SetNumIterationsForNextFrame (int32 NumIterations)
Sets the number of iterations to use for the next time UpdateResourceStreaming is being called.
virtual int32 StreamAllResources (float TimeLimit=0.0f) override
Streams in/out all resources that wants to and blocks until it's done.
virtual void Tick (float DeltaTime, bool bProcessEverything=false) override
Calls UpdateResourceStreaming(), and does per-frame cleaning.
virtual void UpdateResourceStreaming (float DeltaTime, bool bProcessEverything=false) override
Updates streaming, taking into account all current view infos.
Public Member Functions inherited from IStreamingManager
IStreamingManager ()
virtual ~IStreamingManager ()
Virtual destructor.
void AddViewInformation (const FVector &ViewOrigin, float ScreenSize, float FOVScreenSize, float BoostFactor=1.0f, bool bOverrideLocation=false, float Duration=0.0f, TWeakObjectPtr< AActor > InActorToBoost=NULL, TWeakObjectPtr< UWorld > InWorld=NULL)
Adds the passed in view information to the static array.
void AddViewLocation (const FVector &Location, float BoostFactor=1.0f, bool bOverrideLocation=false, float Duration=0.0f)
Queue up view locations to the streaming system.
int32 GetNumViews () const
Returns the number of view infos.
const FStreamingViewInfo & GetViewInformation (int32 ViewIndex) const
Returns the view info by the specified index.
void RemoveStreamingViews (ERemoveStreamingViews RemovalType)
Removes streaming views from the streaming manager.
UE_DEPRECATED (5.1, "This is deprecated to follow inclusive naming rules. Use AddViewLocation() instead.") void AddViewSlaveLocation(const FVector &Location
Protected Member Functions
virtual void AddOrRemoveTextureStreamingManagerIfNeeded (bool bIsInit=false)
Protected Member Functions inherited from IStreamingManager
void SetupViewInfos (float DeltaTime)
Sets up the CurrentViewInfos array based on PendingViewInfos, LastingViewInfos and SecondaryLocations.
Protected Attributes
IAnimationStreamingManager * AnimationStreamingManager
The animation streaming manager, should always exist.
IAudioStreamingManager * AudioStreamingManager
The audio streaming manager, should always exist.
FCriticalSection AudioStreamingManagerCriticalSection
int32 DisableResourceStreamingCount
Count of how many nested DisableResourceStreaming's were called - will enable when this is 0.
float LoadMapTimeLimit
Maximum number of seconds to block in StreamAllResources(), by default (.ini setting).
Nanite::FCoarseMeshStreamingManager * NaniteCoarseMeshStreamingManager
The nanite coarse mesh streaming manager, should always exist.
int32 NumIterations
Number of iterations to perform.
FRenderAssetStreamingManager * RenderAssetStreamingManager
The currently added texture streaming manager.
TArray< IStreamingManager * > StreamingManagers
Array of streaming managers to route function calls to.
FVirtualTextureChunkStreamingManager * VirtualTextureStreamingManager
The virtual texture streaming manager, should always exist.
Protected Attributes inherited from IStreamingManager
int32 NumWantingResources
Number of resources that currently wants to be streamed in.
int32 NumWantingResourcesCounter
The current counter for NumWantingResources.
Additional Inherited Members
Static Public Member Functions inherited from IStreamingManager
static struct FStreamingManagerCollection & Get ()
static struct FStreamingManagerCollection * Get_Concurrent ()
Same as get but could fail if state not allocated or shutdown.
static bool HasShutdown ()
Checks if the streaming manager has already been shut down.
static void Shutdown ()
Data Fields inherited from IStreamingManager
float BoostFactor = 1.0f
float bool bOverrideLocation = false
float bool float Duration
Static Protected Member Functions inherited from IStreamingManager
static void AddViewInfoToArray (TArray< FStreamingViewInfo > &ViewInfos, const FVector &ViewOrigin, float ScreenSize, float FOVScreenSize, float BoostFactor, bool bOverrideLocation, float Duration, TWeakObjectPtr< AActor > InActorToBoost, TWeakObjectPtr< UWorld > InWorld)
Adds the passed in view information to the static array.
static void RemoveViewInfoFromArray (TArray< FStreamingViewInfo > &ViewInfos, const FVector &ViewOrigin)
Remove view infos with the same location from the given array.
Static Protected Attributes inherited from IStreamingManager
static bool bPendingRemoveViews
Set when Tick() has been called.
static TArray< FStreamingViewInfo > CurrentViewInfos
Current collection of views that need to be taken into account for streaming.
static TArray< FStreamingViewInfo > LastingViewInfos
Views that stick around for a while.
static TArray< FStreamingViewInfo > PendingViewInfos
Pending views.
static TArray< FSecondaryLocation > SecondaryLocations
Collection of view locations that will be added at the next call to AddViewInformation.
Detailed Description
Streaming manager collection, routing function calls to streaming managers that have been added via AddStreamingManager.
Definition at line 707 of file ContentStreaming.h.
Constructor & Destructor Documentation
FStreamingManagerCollection()
FStreamingManagerCollection::FStreamingManagerCollection ()
Default constructor, initializing all member variables.
~FStreamingManagerCollection()
FStreamingManagerCollection::~FStreamingManagerCollection ()
Member Function Documentation
AddLevel()
virtual void FStreamingManagerCollection::AddLevel (class ULevel * Level) override virtual
Adds a ULevel to the streaming manager.
Implements IStreamingManager.
AddOrRemoveTextureStreamingManagerIfNeeded()
virtual void FStreamingManagerCollection::AddOrRemoveTextureStreamingManagerIfNeeded (bool bIsInit = false) protected virtual
AddStreamingManager()
void FStreamingManagerCollection::AddStreamingManager (IStreamingManager * StreamingManager)
Adds a streaming manager to the array of managers to route function calls to.
Parameters
StreamingManager Streaming manager to add
References IStreamingManager::IStreamingManager().
BlockTillAllRequestsFinished()
virtual int32 FStreamingManagerCollection::BlockTillAllRequestsFinished (float TimeLimit = 0.0f, bool bLogResults = false) override virtual
Blocks till all pending requests are fulfilled.
Parameters
TimeLimit Optional time limit for processing, in seconds. Specifying 0 means infinite time limit.
bLogResults Whether to dump the results to the log.
Returns
Number of streaming requests still in flight, if the time limit was reached before they were finished.
Implements IStreamingManager.
References TimeLimit.
CancelForcedResources()
virtual void FStreamingManagerCollection::CancelForcedResources () override virtual
Cancels the timed Forced resources (i.e used the Kismet action "Stream In Textures").
Implements IStreamingManager.
DisableResourceStreaming()
void FStreamingManagerCollection::DisableResourceStreaming ()
Disables resource streaming.
Enable with EnableResourceStreaming. Disable/enable can be called multiple times nested
EnableResourceStreaming()
void FStreamingManagerCollection::EnableResourceStreaming ()
Enables resource streaming, previously disabled with enableResourceStreaming.
Disable/enable can be called multiple times nested (this will only actually enable when all disables are matched with enables)
Exec()
virtual bool FStreamingManagerCollection::Exec (UWorld * InWorld, const TCHAR * Cmd, FOutputDevice & Ar) override virtual
Allows the streaming manager to process exec commands.
Parameters
InWorld World context
Cmd Exec command
Ar Output device for feedback
Returns
true if the command was handled
Reimplemented from IStreamingManager.
References Ar, and Cmd.
GetAnimationStreamingManager()
IAnimationStreamingManager & FStreamingManagerCollection::GetAnimationStreamingManager () const
Gets a reference to the Animation Streaming Manager interface.
GetAudioStreamingManager()
IAudioStreamingManager & FStreamingManagerCollection::GetAudioStreamingManager () const
Gets a reference to the Audio Streaming Manager interface.
GetNaniteCoarseMeshStreamingManager()
Nanite::FCoarseMeshStreamingManager * FStreamingManagerCollection::GetNaniteCoarseMeshStreamingManager () const
Gets a reference to the Nanite Coarse Mesh Streaming Manager.
GetNumWantingResources()
virtual int32 FStreamingManagerCollection::GetNumWantingResources () const override virtual
Returns the number of resources that currently wants to be streamed in.
Reimplemented from IStreamingManager.
GetNumWantingResourcesID()
virtual int32 FStreamingManagerCollection::GetNumWantingResourcesID () const override virtual
Returns the current ID for GetNumWantingResources().
The ID is bumped every time NumWantingResources is updated by the streaming system (every few frames). Can be used to verify that any changes have been fully examined, by comparing current ID with what it was when the changes were made.
Reimplemented from IStreamingManager.
GetRenderAssetStreamingManager()
IRenderAssetStreamingManager & FStreamingManagerCollection::GetRenderAssetStreamingManager () const
Get the streaming manager for textures and meshes.
Referenced by FSkeletalMeshStreamIn_IO::ReportIOError().
GetTextureStreamingManager()
IRenderAssetStreamingManager & FStreamingManagerCollection::GetTextureStreamingManager () const
Gets a reference to the Texture Streaming Manager interface.
Referenced by FSkeletalMeshStreamOut::ConditionalMarkComponentsDirty().
GetVirtualTextureStreamingManager()
struct FVirtualTextureChunkStreamingManager & FStreamingManagerCollection::GetVirtualTextureStreamingManager () const
Gets a reference to the Virtual Texture Streaming Manager.
IsRenderAssetStreamingEnabled()
bool FStreamingManagerCollection::IsRenderAssetStreamingEnabled (EStreamableRenderAssetType FilteredAssetType) const
Checks whether texture/mesh streaming is enabled.
IsStreamingEnabled()
bool FStreamingManagerCollection::IsStreamingEnabled () const
Checks whether any kind of streaming is active.
IsTextureStreamingEnabled()
bool FStreamingManagerCollection::IsTextureStreamingEnabled () const
Checks whether texture streaming is enabled.
NotifyActorDestroyed()
virtual void FStreamingManagerCollection::NotifyActorDestroyed (AActor * Actor) override virtual
Called when a spawned actor is destroyed.
Reimplemented from IStreamingManager.
References Actor.
NotifyLevelChange()
virtual void FStreamingManagerCollection::NotifyLevelChange () override virtual
Notifies manager of "level" change.
Implements IStreamingManager.
NotifyLevelOffset()
virtual void FStreamingManagerCollection::NotifyLevelOffset (class ULevel * Level, const FVector & Offset) override virtual
Notifies manager that level primitives were shifted.
Implements IStreamingManager.
References FVector.
NotifyPrimitiveDetached()
virtual void FStreamingManagerCollection::NotifyPrimitiveDetached (const UPrimitiveComponent * Primitive) override virtual
Called when a primitive is detached from an actor or another component.
Reimplemented from IStreamingManager.
NotifyPrimitiveUpdated()
virtual void FStreamingManagerCollection::NotifyPrimitiveUpdated (const UPrimitiveComponent * Primitive) override virtual
Called when a primitive streaming data needs to be updated.
Reimplemented from IStreamingManager.
NotifyPrimitiveUpdated_Concurrent()
virtual void FStreamingManagerCollection::NotifyPrimitiveUpdated_Concurrent (const UPrimitiveComponent * Primitive) override virtual
Called when a primitive streaming data needs to be updated in the last stage of the frame.
Reimplemented from IStreamingManager.
OnAudioStreamingParamsChanged()
virtual void FStreamingManagerCollection::OnAudioStreamingParamsChanged () override virtual
Reimplemented from IStreamingManager.
PropagateLightingScenarioChange()
void FStreamingManagerCollection::PropagateLightingScenarioChange () override virtual
Propagates a change to the active lighting scenario.
Reimplemented from IStreamingManager.
RemoveLevel()
virtual void FStreamingManagerCollection::RemoveLevel (class ULevel * Level) override virtual
Removes a ULevel from the streaming manager.
Implements IStreamingManager.
RemoveStreamingManager()
void FStreamingManagerCollection::RemoveStreamingManager (IStreamingManager * StreamingManager)
Removes a streaming manager from the array of managers to route function calls to.
Parameters
StreamingManager Streaming manager to remove
References IStreamingManager::IStreamingManager().
SetDisregardWorldResourcesForFrames()
virtual void FStreamingManagerCollection::SetDisregardWorldResourcesForFrames (int32 NumFrames) override virtual
Don't stream world resources for the next NumFrames.
References NumFrames.
SetNumIterationsForNextFrame()
void FStreamingManagerCollection::SetNumIterationsForNextFrame (int32 NumIterations)
Sets the number of iterations to use for the next time UpdateResourceStreaming is being called.
This is being reset to 1 afterwards.
Parameters
NumIterations Number of iterations to perform the next time UpdateResourceStreaming is being called.
References NumIterations.
StreamAllResources()
virtual int32 FStreamingManagerCollection::StreamAllResources (float TimeLimit = 0.0f) override virtual
Streams in/out all resources that wants to and blocks until it's done.
Parameters
TimeLimit Maximum number of seconds to wait for streaming I/O. If zero, uses .ini setting
Returns
Number of streaming requests still in flight, if the time limit was reached before they were finished.
Reimplemented from IStreamingManager.
References TimeLimit.
Tick()
virtual void FStreamingManagerCollection::Tick (float DeltaTime, bool bProcessEverything = false) override virtual
Calls UpdateResourceStreaming(), and does per-frame cleaning.
Call once per frame.
Parameters
DeltaTime Time since last call in seconds
bProcessEverything [opt] If true, process all resources with no throttling limits
Reimplemented from IStreamingManager.
References DeltaTime.
UpdateResourceStreaming()
virtual void FStreamingManagerCollection::UpdateResourceStreaming (float DeltaTime, bool bProcessEverything = false) override virtual
Updates streaming, taking into account all current view infos.
Can be called multiple times per frame.
Parameters
DeltaTime Time since last call in seconds
bProcessEverything [opt] If true, process all resources with no throttling limits
Implements IStreamingManager.
References DeltaTime.
Field Documentation
AnimationStreamingManager
IAnimationStreamingManager* FStreamingManagerCollection::AnimationStreamingManager protected
The animation streaming manager, should always exist.
Definition at line 908 of file ContentStreaming.h.
AudioStreamingManager
IAudioStreamingManager* FStreamingManagerCollection::AudioStreamingManager protected
The audio streaming manager, should always exist.
Definition at line 905 of file ContentStreaming.h.
AudioStreamingManagerCriticalSection
FCriticalSection FStreamingManagerCollection::AudioStreamingManagerCriticalSection mutable protected
Definition at line 918 of file ContentStreaming.h.
DisableResourceStreamingCount
int32 FStreamingManagerCollection::DisableResourceStreamingCount protected
Count of how many nested DisableResourceStreaming's were called - will enable when this is 0.
Definition at line 896 of file ContentStreaming.h.
LoadMapTimeLimit
float FStreamingManagerCollection::LoadMapTimeLimit protected
Maximum number of seconds to block in StreamAllResources(), by default (.ini setting).
Definition at line 899 of file ContentStreaming.h.
NaniteCoarseMeshStreamingManager
Nanite::FCoarseMeshStreamingManager* FStreamingManagerCollection::NaniteCoarseMeshStreamingManager protected
The nanite coarse mesh streaming manager, should always exist.
Definition at line 914 of file ContentStreaming.h.
NumIterations
int32 FStreamingManagerCollection::NumIterations protected
Number of iterations to perform.
Gets reset to 1 each frame.
Definition at line 893 of file ContentStreaming.h.
Referenced by SetNumIterationsForNextFrame().
RenderAssetStreamingManager
FRenderAssetStreamingManager* FStreamingManagerCollection::RenderAssetStreamingManager protected
The currently added texture streaming manager.
Can be NULL
Definition at line 902 of file ContentStreaming.h.
StreamingManagers
TArray<IStreamingManager*> FStreamingManagerCollection::StreamingManagers protected
Array of streaming managers to route function calls to.
Definition at line 891 of file ContentStreaming.h.
VirtualTextureStreamingManager
FVirtualTextureChunkStreamingManager* FStreamingManagerCollection::VirtualTextureStreamingManager protected
The virtual texture streaming manager, should always exist.
Definition at line 911 of file ContentStreaming.h.
The documentation for this struct was generated from the following file:
ContentStreaming.h