Unreal Engine 5.6 C++ API: UE::Geometry::TIntersector1< RealType > Class Template Reference
UE::Geometry::TIntersector1< RealType > Class Template Reference
TIntersector1 computes the intersection of one-dimensional intervals [u0,u1] and [v0,v1].
#include "Intersector1.h"
Public Member Functions
TIntersector1 (const TInterval1< RealType > &u, const TInterval1< RealType > &v)
TIntersector1 (RealType u0, RealType u1, RealType v0, RealType v1)
bool Find ()
Calculate the intersection interval.
RealType GetIntersection (int i)
bool Test () const
Fast check to see if intervals intersect, but does not calculate intersection interval.
Data Fields
int NumIntersections = 0
Number of intersections found.
TInterval1< RealType > U
First interval.
TInterval1< RealType > V
Second interval.
Private Attributes
TInterval1< RealType > Intersections
intersection point/interval, access via GetIntersection
Detailed Description
template<typename RealType>
class UE::Geometry::TIntersector1< RealType >
TIntersector1 computes the intersection of one-dimensional intervals [u0,u1] and [v0,v1].
The end points of the input intervals must be ordered u0 <= u1 and v0 <= v1. Infinite and degenerate intervals are allowed.
Definition at line 24 of file Intersector1.h.
Constructor & Destructor Documentation
TIntersector1() [1/2]
template<typename RealType> UE::Geometry::TIntersector1< RealType >::TIntersector1 (RealType u0, RealType u1, RealType v0, RealType v1) inline
Definition at line 44 of file Intersector1.h.
TIntersector1() [2/2]
template<typename RealType> UE::Geometry::TIntersector1< RealType >::TIntersector1 (const TInterval1< RealType > & u, const TInterval1< RealType > & v) inline
Definition at line 50 of file Intersector1.h.
Member Function Documentation
Find()
template<typename RealType> bool UE::Geometry::TIntersector1< RealType >::Find () inline
Calculate the intersection interval.
Returns
true if the intervals intersect
Definition at line 75 of file Intersector1.h.
Referenced by UE::Geometry::TIntrLine2Triangle2< float >::Find(), UE::Geometry::TIntrSegment2Segment2< double >::Find(), and UE::Geometry::TIntrSegment2Triangle2< float >::Find().
GetIntersection()
template<typename RealType> RealType UE::Geometry::TIntersector1< RealType >::GetIntersection (int i) inline
Returns
first or second point of intersection interval
Definition at line 66 of file Intersector1.h.
Referenced by UE::Geometry::TIntrLine2Triangle2< float >::Find(), UE::Geometry::TIntrSegment2Segment2< double >::Find(), and UE::Geometry::TIntrSegment2Triangle2< float >::Find().
Test()
template<typename RealType> bool UE::Geometry::TIntersector1< RealType >::Test () const inline
Fast check to see if intervals intersect, but does not calculate intersection interval.
Returns
true if intervals intersect
Definition at line 58 of file Intersector1.h.
Field Documentation
Intersections
template<typename RealType> TInterval1<RealType> UE::Geometry::TIntersector1< RealType >::Intersections private
intersection point/interval, access via GetIntersection
Definition at line 28 of file Intersector1.h.
NumIntersections
template<typename RealType> int UE::Geometry::TIntersector1< RealType >::NumIntersections = 0
Number of intersections found.
0: intervals do not overlap 1: intervals are touching at a single point 2: intervals intersect in an interval
Definition at line 42 of file Intersector1.h.
Referenced by UE::Geometry::TIntrLine2Triangle2< float >::Find(), UE::Geometry::TIntrSegment2Segment2< double >::Find(), and UE::Geometry::TIntrSegment2Triangle2< float >::Find().
U
template<typename RealType> TInterval1<RealType> UE::Geometry::TIntersector1< RealType >::U
First interval.
Definition at line 32 of file Intersector1.h.
V
template<typename RealType> TInterval1<RealType> UE::Geometry::TIntersector1< RealType >::V
Second interval.
Definition at line 34 of file Intersector1.h.
The documentation for this class was generated from the following file:
Intersector1.h