Unreal Engine 5.6 C++ API: FSkeletalMeshHalfEdgeBuffer Class Reference
FSkeletalMeshHalfEdgeBuffer Class Reference
#include "SkeletalMeshHalfEdgeBuffer.h"
Data Structures
struct FRHIInfo
Public Member Functions
FSkeletalMeshHalfEdgeBuffer ()
~FSkeletalMeshHalfEdgeBuffer ()
void CleanUp ()
FRHIInfo CreateRHIBuffer (FRHICommandListBase &RHICmdList)
FRHIShaderResourceView * GetEdgeToTwinEdgeBufferSRV () const
int32 GetResourceSize () const
FRHIShaderResourceView * GetVertexToEdgeBufferSRV () const
void Init (const FSkeletalMeshLODRenderData &InLodRenderData)
void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InitRHIForStreaming (FRHIInfo RHIInfo, FRHIResourceReplaceBatcher &Batcher)
bool IsCPUDataValid () const
bool IsReadyForRendering () const
void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void Serialize (FArchive &Ar)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Member Functions
uint32 GetMinBufferSize () const
Private Attributes
FBufferRHIRef EdgeToTwinEdgeBufferRHI
FShaderResourceViewRHIRef EdgeToTwinEdgeBufferSRV
TResourceArray< int32 > EdgeToTwinEdgeData
FBufferRHIRef VertexToEdgeBufferRHI
FShaderResourceViewRHIRef VertexToEdgeBufferSRV
TResourceArray< int32 > VertexToEdgeData
Friends
class FSkeletalMeshLODRenderData
FArchive & operator<< (FArchive &Ar, FSkeletalMeshHalfEdgeBuffer &MorphTargetVertexInfoBuffers)
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 20 of file SkeletalMeshHalfEdgeBuffer.h.
Constructor & Destructor Documentation
FSkeletalMeshHalfEdgeBuffer()
FSkeletalMeshHalfEdgeBuffer::FSkeletalMeshHalfEdgeBuffer ()
Referenced by operator<<.
~FSkeletalMeshHalfEdgeBuffer()
FSkeletalMeshHalfEdgeBuffer::~FSkeletalMeshHalfEdgeBuffer ()
Member Function Documentation
CleanUp()
void FSkeletalMeshHalfEdgeBuffer::CleanUp ()
CreateRHIBuffer()
FRHIInfo FSkeletalMeshHalfEdgeBuffer::CreateRHIBuffer (FRHICommandListBase & RHICmdList)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
GetEdgeToTwinEdgeBufferSRV()
FRHIShaderResourceView * FSkeletalMeshHalfEdgeBuffer::GetEdgeToTwinEdgeBufferSRV () const inline
Definition at line 58 of file SkeletalMeshHalfEdgeBuffer.h.
References EdgeToTwinEdgeBufferSRV.
GetMinBufferSize()
uint32 FSkeletalMeshHalfEdgeBuffer::GetMinBufferSize () const private
GetResourceSize()
int32 FSkeletalMeshHalfEdgeBuffer::GetResourceSize () const
GetVertexToEdgeBufferSRV()
FRHIShaderResourceView * FSkeletalMeshHalfEdgeBuffer::GetVertexToEdgeBufferSRV () const inline
Definition at line 53 of file SkeletalMeshHalfEdgeBuffer.h.
References VertexToEdgeBufferSRV.
Init()
void FSkeletalMeshHalfEdgeBuffer::Init (const FSkeletalMeshLODRenderData & InLodRenderData)
References FSkeletalMeshLODRenderData.
InitRHI()
void FSkeletalMeshHalfEdgeBuffer::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHIForStreaming()
void FSkeletalMeshHalfEdgeBuffer::InitRHIForStreaming (FRHIInfo RHIInfo, FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
IsCPUDataValid()
bool FSkeletalMeshHalfEdgeBuffer::IsCPUDataValid () const
IsReadyForRendering()
bool FSkeletalMeshHalfEdgeBuffer::IsReadyForRendering () const
ReleaseRHI()
void FSkeletalMeshHalfEdgeBuffer::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseRHIForStreaming()
void FSkeletalMeshHalfEdgeBuffer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamOut::ReleaseBuffers().
Serialize()
void FSkeletalMeshHalfEdgeBuffer::Serialize (FArchive & Ar)
References Ar.
Friends And Related Symbol Documentation
FSkeletalMeshLODRenderData
friend class FSkeletalMeshLODRenderData friend
Definition at line 50 of file SkeletalMeshHalfEdgeBuffer.h.
References FSkeletalMeshLODRenderData.
Referenced by FSkeletalMeshLODRenderData, and Init().
operator<<
FArchive & operator<< (FArchive & Ar, FSkeletalMeshHalfEdgeBuffer & MorphTargetVertexInfoBuffers) friend
References FSkeletalMeshHalfEdgeBuffer(), and Ar.
Field Documentation
EdgeToTwinEdgeBufferRHI
FBufferRHIRef FSkeletalMeshHalfEdgeBuffer::EdgeToTwinEdgeBufferRHI private
Definition at line 74 of file SkeletalMeshHalfEdgeBuffer.h.
EdgeToTwinEdgeBufferSRV
FShaderResourceViewRHIRef FSkeletalMeshHalfEdgeBuffer::EdgeToTwinEdgeBufferSRV private
Definition at line 75 of file SkeletalMeshHalfEdgeBuffer.h.
Referenced by GetEdgeToTwinEdgeBufferSRV().
EdgeToTwinEdgeData
TResourceArray<int32> FSkeletalMeshHalfEdgeBuffer::EdgeToTwinEdgeData private
Definition at line 70 of file SkeletalMeshHalfEdgeBuffer.h.
VertexToEdgeBufferRHI
FBufferRHIRef FSkeletalMeshHalfEdgeBuffer::VertexToEdgeBufferRHI private
Definition at line 72 of file SkeletalMeshHalfEdgeBuffer.h.
VertexToEdgeBufferSRV
FShaderResourceViewRHIRef FSkeletalMeshHalfEdgeBuffer::VertexToEdgeBufferSRV private
Definition at line 73 of file SkeletalMeshHalfEdgeBuffer.h.
Referenced by GetVertexToEdgeBufferSRV().
VertexToEdgeData
TResourceArray<int32> FSkeletalMeshHalfEdgeBuffer::VertexToEdgeData private
Definition at line 69 of file SkeletalMeshHalfEdgeBuffer.h.
The documentation for this class was generated from the following file:
SkeletalMeshHalfEdgeBuffer.h