Unreal Engine 5.6 C++ API: Metasound::VertexPrivate::FInputVertexInterfaceDeclarationBuilder Class Reference
Metasound::VertexPrivate::FInputVertexInterfaceDeclarationBuilder Class Reference
Interface builder for FInputVertexInterface declarations.
#include "MetasoundVertex.h"
Public Member Functions
METASOUNDGRAPHCORE_API FInputVertexInterfaceDeclarationBuilder (TArray< FInputDataVertex > &OutVertices, TArray< FSubInterfaceLayout > &OutInstances)
template<typename... ArgTypes>
void Build (ArgTypes &&... InArgs)
Public Member Functions inherited from Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder
METASOUNDGRAPHCORE_API FSubInterfaceDeclarationBuilder (TArray< FSubInterfaceLayout > &OutSubInterfaceLayouts)
virtual METASOUNDGRAPHCORE_API ~FSubInterfaceDeclarationBuilder ()
METASOUNDGRAPHCORE_API PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS void Add (FBeginSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API void Add (FEndSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API PRAGMA_ENABLE_EXPERIMENTAL_WARNINGS void ReserveSubInterfaces (int32 Num)
Private Member Functions
METASOUNDGRAPHCORE_API PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS void Add (FBeginSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API void Add (FEndSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API void Add (FInputDataVertex &&InVertex)
Private Attributes
TArray< FInputDataVertex > & Vertices
Additional Inherited Members
Protected Member Functions inherited from Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder
METASOUNDGRAPHCORE_API void OnVertexAdded (const FVertexName &InVertexName)
Detailed Description
Interface builder for FInputVertexInterface declarations.
Definition at line 540 of file MetasoundVertex.h.
Constructor & Destructor Documentation
FInputVertexInterfaceDeclarationBuilder()
METASOUNDGRAPHCORE_API Metasound::VertexPrivate::FInputVertexInterfaceDeclarationBuilder::FInputVertexInterfaceDeclarationBuilder (TArray< FInputDataVertex > & OutVertices, TArray< FSubInterfaceLayout > & OutInstances)
References UE_API.
Member Function Documentation
Add() [1/3]
METASOUNDGRAPHCORE_API PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS void Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder::Add (FBeginSubInterface && InSubInterface) private
Add() [2/3]
METASOUNDGRAPHCORE_API void Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder::Add (FEndSubInterface && InSubInterface) private
Add() [3/3]
METASOUNDGRAPHCORE_API void Metasound::VertexPrivate::FInputVertexInterfaceDeclarationBuilder::Add (FInputDataVertex && InVertex) private
References UE_API.
Build()
template<typename... ArgTypes> void Metasound::VertexPrivate::FInputVertexInterfaceDeclarationBuilder::Build (ArgTypes &&... InArgs) inline
Definition at line 545 of file MetasoundVertex.h.
References Add, Forward(), Metasound::VertexPrivate::TNumOfTypeInPack< T >::Get(), PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS, PRAGMA_ENABLE_EXPERIMENTAL_WARNINGS, Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder::ReserveSubInterfaces(), and Vertices.
Referenced by Metasound::FInputVertexInterface::FInputVertexInterface().
Field Documentation
Vertices
TArray<FInputDataVertex>& Metasound::VertexPrivate::FInputVertexInterfaceDeclarationBuilder::Vertices private
Definition at line 574 of file MetasoundVertex.h.
Referenced by Build().
The documentation for this class was generated from the following file:
MetasoundVertex.h