Unreal Engine 5.6 C++ API: FPropertyChangedParams Class Reference
FPropertyChangedParams Class Reference
Parameters for the property changed callback.
#include "KeyPropertyParams.h"
Public Member Functions
FPropertyChangedParams (TArray< UObject * > InObjectsThatChanged, const FPropertyPath &InPropertyPath, const FPropertyPath &InStructPathToKey, ESequencerKeyMode InKeyMode)
FString GetPropertyPathString () const
Gets the property path as a period seperated string of property names.
template<typename ValueType>
ValueType GetPropertyValue () const
Gets the value of the property that changed.
Data Fields
const ESequencerKeyMode KeyMode
Keyframing params.
const TArray< UObject * > ObjectsThatChanged
An array of the objects that changed.
FPropertyPath PropertyPath
A path of properties to get from the root object to the property to be keyed.
FPropertyPath StructPathToKey
Represents the path of an inner property which should be keyed for a struct property.
Static Private Member Functions
template<typename ValueType>
static ValueType GetPropertyValueImpl (void *Data, const FPropertyInfo &Info)
template<>
SEQUENCER_API bool GetPropertyValueImpl (void *Data, const FPropertyInfo &Info)
template<>
SEQUENCER_API UObject * GetPropertyValueImpl (void *Data, const FPropertyInfo &Info)
Detailed Description
Parameters for the property changed callback.
Definition at line 86 of file KeyPropertyParams.h.
Constructor & Destructor Documentation
FPropertyChangedParams()
FPropertyChangedParams::FPropertyChangedParams (TArray< UObject * > InObjectsThatChanged, const FPropertyPath & InPropertyPath, const FPropertyPath & InStructPathToKey, ESequencerKeyMode InKeyMode)
Member Function Documentation
GetPropertyPathString()
FString FPropertyChangedParams::GetPropertyPathString () const
Gets the property path as a period seperated string of property names.
Referenced by FPropertyTrackEditor< TrackType >::InitializeNewTrack().
GetPropertyValue()
template<typename ValueType> ValueType FPropertyChangedParams::GetPropertyValue () const inline
Gets the value of the property that changed.
Definition at line 95 of file KeyPropertyParams.h.
References FPropertyInfo::ArrayIndex, CastField(), TWeakFieldPtr< T >::Get(), FField::GetOwner(), GetPropertyValueImpl(), FScriptArrayHelper::GetRawPtr(), INDEX_NONE, FScriptArrayHelper::IsValidIndex(), FMath::Max, ObjectsThatChanged, Property, FPropertyInfo::Property, and PropertyPath.
GetPropertyValueImpl() [1/3]
template<typename ValueType> ValueType FPropertyChangedParams::GetPropertyValueImpl (void * Data, const FPropertyInfo & Info) inline static private
Definition at line 167 of file KeyPropertyParams.h.
References Info.
Referenced by GetPropertyValue().
GetPropertyValueImpl() [2/3]
template<> SEQUENCER_API bool FPropertyChangedParams::GetPropertyValueImpl (void * Data, const FPropertyInfo & Info) static private
References Info.
GetPropertyValueImpl() [3/3]
template<> SEQUENCER_API UObject * FPropertyChangedParams::GetPropertyValueImpl (void * Data, const FPropertyInfo & Info) static private
References Info.
Field Documentation
KeyMode
const ESequencerKeyMode FPropertyChangedParams::KeyMode
Keyframing params.
Definition at line 162 of file KeyPropertyParams.h.
Referenced by FPropertyTrackEditor< TrackType >::OnKeyProperty().
ObjectsThatChanged
const TArray<UObject*> FPropertyChangedParams::ObjectsThatChanged
An array of the objects that changed.
Definition at line 152 of file KeyPropertyParams.h.
Referenced by GetPropertyValue(), and FPropertyTrackEditor< TrackType >::OnKeyProperty().
PropertyPath
FPropertyPath FPropertyChangedParams::PropertyPath
A path of properties to get from the root object to the property to be keyed.
Definition at line 155 of file KeyPropertyParams.h.
Referenced by GetPropertyValue(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), and FPropertyTrackEditor< TrackType >::OnKeyProperty().
StructPathToKey
FPropertyPath FPropertyChangedParams::StructPathToKey
Represents the path of an inner property which should be keyed for a struct property.
If all inner properties should be keyed, this will be empty.
Definition at line 159 of file KeyPropertyParams.h.
The documentation for this class was generated from the following file:
KeyPropertyParams.h