Unreal Engine 5.6 C++ API: UE::Insights::FTreeNodeGroupingByUniqueValue Class Reference
UE::Insights::FTreeNodeGroupingByUniqueValue Class Reference
Creates a group for each unique value.
#include "TreeNodeGrouping.h"
Public Member Functions
FTreeNodeGroupingByUniqueValue (TSharedRef< FTableColumn > InColumnRef)
virtual ~FTreeNodeGroupingByUniqueValue ()
TSharedRef< FTableColumn > GetColumn () const
virtual FName GetColumnId () const override
virtual FTreeNodeGroupInfo GetGroupForNode (const FBaseTreeNodePtr InNode) const override
Private Member Functions
INSIGHTS_DECLARE_RTTI (FTreeNodeGroupingByUniqueValue, FTreeNodeGrouping)
Private Attributes
TSharedRef< FTableColumn > ColumnRef
Additional Inherited Members
Protected Member Functions inherited from UE::Insights::FTreeNodeGrouping
UE_DEPRECATED (5.6, "BrushName is not used") FName BrushName
Protected Attributes inherited from UE::Insights::FTreeNodeGrouping
FText Description
const FSlateBrush * Icon
FText ShortName
FText TitleName
Detailed Description
Creates a group for each unique value.
Definition at line 115 of file TreeNodeGrouping.h.
Constructor & Destructor Documentation
FTreeNodeGroupingByUniqueValue()
UE::Insights::FTreeNodeGroupingByUniqueValue::FTreeNodeGroupingByUniqueValue (TSharedRef< FTableColumn > InColumnRef)
Referenced by UE::Insights::FTreeNodeGroupingByUniqueValueCString::FTreeNodeGroupingByUniqueValueCString(), UE::Insights::TTreeNodeGroupingByUniqueValue< bool >::TTreeNodeGroupingByUniqueValue(), and INSIGHTS_DECLARE_RTTI().
~FTreeNodeGroupingByUniqueValue()
virtual UE::Insights::FTreeNodeGroupingByUniqueValue::~FTreeNodeGroupingByUniqueValue () inline virtual
Definition at line 121 of file TreeNodeGrouping.h.
Member Function Documentation
GetColumn()
TSharedRef< FTableColumn > UE::Insights::FTreeNodeGroupingByUniqueValue::GetColumn () const inline
Definition at line 126 of file TreeNodeGrouping.h.
References ColumnRef.
Referenced by UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes().
GetColumnId()
virtual FName UE::Insights::FTreeNodeGroupingByUniqueValue::GetColumnId () const inline override virtual
Reimplemented from UE::Insights::FTreeNodeGrouping.
Definition at line 125 of file TreeNodeGrouping.h.
References ColumnRef.
GetGroupForNode()
virtual FTreeNodeGroupInfo UE::Insights::FTreeNodeGroupingByUniqueValue::GetGroupForNode (const FBaseTreeNodePtr InNode) const override virtual
Reimplemented from UE::Insights::FTreeNodeGrouping.
INSIGHTS_DECLARE_RTTI()
UE::Insights::FTreeNodeGroupingByUniqueValue::INSIGHTS_DECLARE_RTTI (FTreeNodeGroupingByUniqueValue , FTreeNodeGrouping) private
References UE::Insights::FTreeNodeGrouping::FTreeNodeGrouping(), and FTreeNodeGroupingByUniqueValue().
Field Documentation
ColumnRef
TSharedRef<FTableColumn> UE::Insights::FTreeNodeGroupingByUniqueValue::ColumnRef private
Definition at line 129 of file TreeNodeGrouping.h.
Referenced by GetColumn(), and GetColumnId().
The documentation for this class was generated from the following file:
TreeNodeGrouping.h