Unreal Engine 5.6 C++ API: TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes > Class Template Reference
TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes > Class Template Reference
Handles instancing thumbnail scenes for Object based Asset types (use the path as the key).
#include "ThumbnailHelpers.h"
Public Member Functions
TObjectInstanceThumbnailScene ()
Constructor.
void Clear ()
Clears all thumbnail scenes.
TSharedRef< ThumbnailSceneType > EnsureThumbnailScene (const UObject *InObject)
Find or create a thumbnail scene instance for this class type.
TSharedPtr< ThumbnailSceneType > FindThumbnailScene (const UObject *InObject) const
Find an existing thumbnail scene instance for this class type.
void RemoveThumbnailScene (const UObject *InObject)
Removes the thumbnail scene instance for the specified class.
Private Attributes
TMap< FString, TSharedPtr< ThumbnailSceneType > > InstancedThumbnailScenes
Mapping between the class type and its thumbnail scene.
Detailed Description
template<typename ThumbnailSceneType, int32 MaxNumScenes>
class TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >
Handles instancing thumbnail scenes for Object based Asset types (use the path as the key).
Definition at line 418 of file ThumbnailHelpers.h.
Constructor & Destructor Documentation
TObjectInstanceThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::TObjectInstanceThumbnailScene () inline
Constructor.
Definition at line 422 of file ThumbnailHelpers.h.
References InstancedThumbnailScenes.
Member Function Documentation
Clear()
template<typename ThumbnailSceneType, int32 MaxNumScenes> void TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::Clear () inline
Clears all thumbnail scenes.
Definition at line 467 of file ThumbnailHelpers.h.
References InstancedThumbnailScenes.
EnsureThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> TSharedRef< ThumbnailSceneType > TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene (const UObject * InObject) inline
Find or create a thumbnail scene instance for this class type.
Definition at line 437 of file ThumbnailHelpers.h.
References check, CollectGarbage(), GARBAGE_COLLECTION_KEEPFLAGS, UObjectBaseUtility::GetPathName(), InstancedThumbnailScenes, TSharedPtr< ObjectType, InMode >::IsValid(), MakeShareable(), and TSharedPtr< ObjectType, InMode >::ToSharedRef().
FindThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> TSharedPtr< ThumbnailSceneType > TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::FindThumbnailScene (const UObject * InObject) const inline
Find an existing thumbnail scene instance for this class type.
Definition at line 428 of file ThumbnailHelpers.h.
References check, UObjectBaseUtility::GetPathName(), and InstancedThumbnailScenes.
RemoveThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> void TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::RemoveThumbnailScene (const UObject * InObject) inline
Removes the thumbnail scene instance for the specified class.
Definition at line 460 of file ThumbnailHelpers.h.
References check, UObjectBaseUtility::GetPathName(), and InstancedThumbnailScenes.
Field Documentation
InstancedThumbnailScenes
template<typename ThumbnailSceneType, int32 MaxNumScenes> TMap<FString, TSharedPtr<ThumbnailSceneType> > TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::InstancedThumbnailScenes private
Mapping between the class type and its thumbnail scene.
Note
This uses the class name rather than the class pointer to avoid leaving behind stale class instances as Blueprints are re-compiled.
Definition at line 477 of file ThumbnailHelpers.h.
Referenced by TObjectInstanceThumbnailScene(), Clear(), EnsureThumbnailScene(), FindThumbnailScene(), and RemoveThumbnailScene().
The documentation for this class was generated from the following file:
ThumbnailHelpers.h