Unreal Engine 5.6 C++ API: TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... > Class Template Reference
TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Member Functions
template<typename InFunctorType, typename... InVarTypes>
TBaseSPLambdaDelegateInstance (const TWeakPtr< UserClass, SPMode > &InContextObject, InFunctorType &&InFunctor, InVarTypes &&... Vars)
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst InContextObject) const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
using UserClass = const void
Private Attributes
TWeakPtr< UserClass, SPMode > ContextObject
std::remove_const_t< FunctorType > Functor
Additional Inherited Members
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Detailed Description
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes>
class TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >
Definition at line 328 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 334 of file DelegateInstancesImpl.h.
Super
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 333 of file DelegateInstancesImpl.h.
UserClass
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::UserClass = const void private
Definition at line 336 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TBaseSPLambdaDelegateInstance()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> template<typename InFunctorType, typename... InVarTypes> TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::TBaseSPLambdaDelegateInstance (const TWeakPtr< UserClass, SPMode > & InContextObject, InFunctorType && InFunctor, InVarTypes &&... Vars) inline explicit
Definition at line 340 of file DelegateInstancesImpl.h.
References ContextObject, Forward(), and Functor.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 393 of file DelegateInstancesImpl.h.
References TBaseSPLambdaDelegateInstance().
CreateCopy() [2/3]
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 398 of file DelegateInstancesImpl.h.
References TBaseSPLambdaDelegateInstance().
CreateCopy() [3/3]
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 388 of file DelegateInstancesImpl.h.
References TBaseSPLambdaDelegateInstance().
Execute()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> RetValType TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 403 of file DelegateInstancesImpl.h.
References Forward(), Functor, Params, and TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload.
ExecuteIfSafe()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 408 of file DelegateInstancesImpl.h.
References ContextObject, Forward(), Functor, Params, and TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload.
GetBoundProgramCounterForTimerManager()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> uint64 TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 368 of file DelegateInstancesImpl.h.
GetObjectForTimerManager()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> const void * TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 363 of file DelegateInstancesImpl.h.
References ContextObject.
GetUObject()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> UObject * TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetUObject () const inline final
Definition at line 358 of file DelegateInstancesImpl.h.
HasSameObject()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::HasSameObject (FDelegateUserObjectConst InContextObject) const inline final
Definition at line 374 of file DelegateInstancesImpl.h.
References ContextObject.
IsSafeToExecute()
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 379 of file DelegateInstancesImpl.h.
References ContextObject.
Field Documentation
ContextObject
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> TWeakPtr<UserClass, SPMode> TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ContextObject private
Definition at line 422 of file DelegateInstancesImpl.h.
Referenced by TBaseSPLambdaDelegateInstance(), ExecuteIfSafe(), GetObjectForTimerManager(), HasSameObject(), and IsSafeToExecute().
Functor
template<ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> std::remove_const_t<FunctorType> TBaseSPLambdaDelegateInstance< SPMode, RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Functor mutable private
Definition at line 425 of file DelegateInstancesImpl.h.
Referenced by TBaseSPLambdaDelegateInstance(), Execute(), and ExecuteIfSafe().
The documentation for this class was generated from the following file:
DelegateInstancesImpl.h