Unreal Engine 5.6 C++ API: GlobalShader.h File Reference
GlobalShader.h File Reference
#include "Containers/Array.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "HAL/Platform.h"
#include "Misc/AssertionMacros.h"
#include "Misc/Paths.h"
#include "RHI.h"
#include "RHIDefinitions.h"
#include "RHIResources.h"
#include "Serialization/MemoryImage.h"
#include "Serialization/MemoryLayout.h"
#include "Shader.h"
#include "ShaderParameterUtils.h"
#include "Templates/Tuple.h"
#include "Templates/UniquePtr.h"
#include "UObject/NameTypes.h"
#include "UObject/UnrealNames.h"
Data Structures
class FGlobalShader
FGlobalShader.
class FGlobalShaderMap
class FGlobalShaderMapContent
class FGlobalShaderMapId
Class that encapsulates logic to create a DDC key for the global shader map.
class FGlobalShaderMapSection
struct FGlobalShaderPermutationParameters
class FGlobalShaderType
A shader meta type for the simplest shaders; shaders which are not material or vertex factory linked.
class FNULLPS
An internal dummy pixel shader to use when the user calls RHISetPixelShader(NULL).
Macros
#define DECLARE_EXPORTED_GLOBAL_SHADER(ShaderClass, RequiredAPI)
#define DECLARE_GLOBAL_SHADER(ShaderClass)
DECLARE_GLOBAL_SHADER and IMPLEMENT_GLOBAL_SHADER setup a global shader class's boiler plate.
#define IMPLEMENT_GLOBAL_SHADER(ShaderClass, SourceFilename, FunctionName, Frequency)
Enumerations
enum class ERecursiveShader { None = 0 , Resolve = 1 << 0 , Clear = 1 << 1 , Null = 1 << 2 }
Groups of global shaders which can be used in recursive RHI command lists by platform RHI implementations.
Functions
RENDERCORE_API void CreateRecursiveShaders ()
template<typename TShaderType>
void ForceInitGlobalShaderType ()
void ForceInitGlobalShaderType (FShaderType &ShaderType)
FGlobalShaderMap * GetGlobalShaderMap (ERHIFeatureLevel::Type FeatureLevel)
Overload for the above GetGlobalShaderMap which takes a feature level and translates to the appropriate shader platform.
RENDERCORE_API FGlobalShaderMap * GetGlobalShaderMap (EShaderPlatform Platform)
Accesses the global shader map.
constexpr bool operator! (ERecursiveShader E)
constexpr ERecursiveShader operator& (ERecursiveShader Lhs, ERecursiveShader Rhs)
ERecursiveShader & operator&= (ERecursiveShader &Lhs, ERecursiveShader Rhs)
constexpr ERecursiveShader operator^ (ERecursiveShader Lhs, ERecursiveShader Rhs)
ERecursiveShader & operator^= (ERecursiveShader &Lhs, ERecursiveShader Rhs)
constexpr ERecursiveShader operator| (ERecursiveShader Lhs, ERecursiveShader Rhs)
ERecursiveShader & operator|= (ERecursiveShader &Lhs, ERecursiveShader Rhs)
constexpr ERecursiveShader operator~ (ERecursiveShader E)
Variables
RENDERCORE_API FGlobalShaderMap * GGlobalShaderMap [SP_NumPlatforms]
RENDERCORE_API const int32 GlobalShaderMapId
Used to identify the global shader map in compile queues.
RENDERCORE_API ERecursiveShader GRequiredRecursiveShaders
Macro Definition Documentation
DECLARE_EXPORTED_GLOBAL_SHADER
#define DECLARE_EXPORTED_GLOBAL_SHADER (ShaderClass, RequiredAPI)
Value:
DECLARE_EXPORTED_SHADER_TYPE(ShaderClass, Global, RequiredAPI)
Definition at line 415 of file GlobalShader.h.
DECLARE_GLOBAL_SHADER
#define DECLARE_GLOBAL_SHADER (ShaderClass)
Value:
DECLARE_SHADER_TYPE(ShaderClass, Global)
DECLARE_GLOBAL_SHADER and IMPLEMENT_GLOBAL_SHADER setup a global shader class's boiler plate.
They are meant to be used like so:
class FMyGlobalShaderPS : public FGlobalShader { // Setup the shader's boiler plate. DECLARE_GLOBAL_SHADER(FMyGlobalShaderPS);
// Setup the shader's permutation domain. If no dimensions, can do FPermutationDomain = FShaderPermutationNone. using FPermutationDomain = TShaderPermutationDomain<DIMENSIONS...>;
// ... };
// Instantiates global shader's global variable that will take care of compilation process of the shader. This needs imperatively to be done in a .cpp file regardless of whether FMyGlobalShaderPS is in a header or not. IMPLEMENT_GLOBAL_SHADER(FMyGlobalShaderPS, "/Engine/Private/MyShaderFile.usf", "MainPS", SF_Pixel);
When the shader class is a public header, let say in RenderCore module public header, the class declaration macro then should have the RENDERCORE_API like this:
class FMyGlobalShaderPS : public FGlobalShader { // Setup the shader's boiler plate. DECLARE_EXPORTED_GLOBAL_SHADER(FMyGlobalShaderPS, RENDERCORE_API);
// ... };
Definition at line 414 of file GlobalShader.h.
IMPLEMENT_GLOBAL_SHADER
#define IMPLEMENT_GLOBAL_SHADER (ShaderClass, SourceFilename, FunctionName, Frequency)
Value:
IMPLEMENT_SHADER_TYPE(,ShaderClass,TEXT(SourceFilename),TEXT(FunctionName),Frequency)
Definition at line 416 of file GlobalShader.h.
Enumeration Type Documentation
ERecursiveShader
enum class ERecursiveShader strong
Groups of global shaders which can be used in recursive RHI command lists by platform RHI implementations.
Enumerator
None
Resolve
Clear
Null
Definition at line 422 of file GlobalShader.h.
Function Documentation
CreateRecursiveShaders()
RENDERCORE_API void CreateRecursiveShaders () extern
ForceInitGlobalShaderType() [1/2]
template<typename TShaderType> void ForceInitGlobalShaderType () inline
Definition at line 450 of file GlobalShader.h.
References ForceInitGlobalShaderType().
Referenced by ForceInitGlobalShaderType().
ForceInitGlobalShaderType() [2/2]
void ForceInitGlobalShaderType (FShaderType & ShaderType)
GetGlobalShaderMap() [1/2]
FGlobalShaderMap * GetGlobalShaderMap (ERHIFeatureLevel::Type FeatureLevel) inline
Overload for the above GetGlobalShaderMap which takes a feature level and translates to the appropriate shader platform.
Parameters
FeatureLevel - Which feature levels shader map to use
bRefreshShaderMap If true, the existing global shader map will be tossed first
Returns
A reference to the global shader map.
Definition at line 335 of file GlobalShader.h.
References GetGlobalShaderMap().
GetGlobalShaderMap() [2/2]
RENDERCORE_API FGlobalShaderMap * GetGlobalShaderMap (EShaderPlatform Platform) extern
Accesses the global shader map.
This is a global FGlobalShaderMap which contains an instance of each global shader type.
Parameters
Platform Which platform's global shader map to use
bRefreshShaderMap If true, the existing global shader map will be tossed first
Returns
A reference to the global shader map.
References Platform.
Referenced by ClearUAVShader_T(), ClearUAVShader_T(), and GetGlobalShaderMap().
operator!()
bool operator! (ERecursiveShader E) inline constexpr
Definition at line 435 of file GlobalShader.h.
References GRequiredRecursiveShaders.
operator&()
ERecursiveShader operator& (ERecursiveShader Lhs, ERecursiveShader Rhs) inline constexpr
Definition at line 435 of file GlobalShader.h.
operator&=()
ERecursiveShader & operator&= (ERecursiveShader & Lhs, ERecursiveShader Rhs) inline
Definition at line 435 of file GlobalShader.h.
operator^()
ERecursiveShader operator^ (ERecursiveShader Lhs, ERecursiveShader Rhs) inline constexpr
Definition at line 435 of file GlobalShader.h.
operator^=()
ERecursiveShader & operator^= (ERecursiveShader & Lhs, ERecursiveShader Rhs) inline
Definition at line 435 of file GlobalShader.h.
operator|()
ERecursiveShader operator| (ERecursiveShader Lhs, ERecursiveShader Rhs) inline constexpr
Definition at line 435 of file GlobalShader.h.
operator|=()
ERecursiveShader & operator|= (ERecursiveShader & Lhs, ERecursiveShader Rhs) inline
Definition at line 435 of file GlobalShader.h.
operator~()
ERecursiveShader operator~ (ERecursiveShader E) inline constexpr
Definition at line 435 of file GlobalShader.h.
Variable Documentation
GGlobalShaderMap
RENDERCORE_API FGlobalShaderMap* GGlobalShaderMap[SP_NumPlatforms] extern
GlobalShaderMapId
RENDERCORE_API const int32 GlobalShaderMapId extern
Used to identify the global shader map in compile queues.
GRequiredRecursiveShaders
RENDERCORE_API ERecursiveShader GRequiredRecursiveShaders extern
Referenced by operator!().