Unreal Engine 5.6 C++ API: ICompressedAnimData Struct Reference
ICompressedAnimData Struct Reference abstract
#include "AnimCompressionTypes.h"
Public Member Functions
ICompressedAnimData ()=default
ICompressedAnimData (const ICompressedAnimData &)
virtual ~ICompressedAnimData ()
virtual void Bind (const TArrayView< uint8 > BulkData)=0
virtual int64 GetApproxCompressedSize () const =0
virtual FString GetDebugString () const
virtual bool IsValid () const =0
ICompressedAnimData & operator= (const ICompressedAnimData &)
virtual void SerializeCompressedData (UObject *DataOwner, class FArchive &Ar)
UE_DEPRECATED (5.5, "SerializeCompressedData now accepts the DataOwner as an argument") 1 virtual void SerializeCompressedData(class FArchive &Ar)
Data Fields
int32 CompressedNumberOfKeys
Detailed Description
Definition at line 430 of file AnimCompressionTypes.h.
Constructor & Destructor Documentation
ICompressedAnimData() [1/2]
ICompressedAnimData::ICompressedAnimData () default
Referenced by FUECompressedAnimData::FUECompressedAnimData(), ICompressedAnimData(), and operator=().
ICompressedAnimData() [2/2]
ICompressedAnimData::ICompressedAnimData (const ICompressedAnimData &)
References ICompressedAnimData().
~ICompressedAnimData()
virtual ICompressedAnimData::~ICompressedAnimData () inline virtual
Definition at line 448 of file AnimCompressionTypes.h.
Member Function Documentation
Bind()
virtual void ICompressedAnimData::Bind (const TArrayView< uint8 > BulkData) pure virtual
Implemented in FUECompressedAnimData, and FUECompressedAnimDataMutable.
References Bind(), and BulkData.
Referenced by Bind().
GetApproxCompressedSize()
virtual int64 ICompressedAnimData::GetApproxCompressedSize () const pure virtual
Implemented in FUECompressedAnimData, and FUECompressedAnimDataMutable.
References GetApproxCompressedSize().
Referenced by GetApproxCompressedSize().
GetDebugString()
virtual FString ICompressedAnimData::GetDebugString () const inline virtual
Reimplemented in FUECompressedAnimData.
Definition at line 457 of file AnimCompressionTypes.h.
References GetDebugString().
Referenced by GetDebugString().
IsValid()
virtual bool ICompressedAnimData::IsValid () const pure virtual
Implemented in FUECompressedAnimData, and FUECompressedAnimDataMutable.
operator=()
ICompressedAnimData & ICompressedAnimData::operator= (const ICompressedAnimData &)
References ICompressedAnimData().
SerializeCompressedData()
virtual void ICompressedAnimData::SerializeCompressedData (UObject * DataOwner, class FArchive & Ar) virtual
References Ar, and SerializeCompressedData().
Referenced by SerializeCompressedData(), and UE_DEPRECATED().
UE_DEPRECATED()
ICompressedAnimData::UE_DEPRECATED (5. 5, "SerializeCompressedData now accepts the DataOwner as an argument") &
References Ar, and SerializeCompressedData().
Field Documentation
CompressedNumberOfKeys
int32 ICompressedAnimData::CompressedNumberOfKeys
Definition at line 433 of file AnimCompressionTypes.h.
Referenced by AEFVariableKeyLerp< FORMAT >::GetBoneAtomRotation(), AEFVariableKeyLerp< FORMAT >::GetBoneAtomScale(), and AEFVariableKeyLerp< FORMAT >::GetBoneAtomTranslation().
The documentation for this struct was generated from the following file:
AnimCompressionTypes.h