Unreal Engine 5.6 C++ API: UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes > Struct Template Reference
UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes > Struct Template Reference
Page traits struct for TPagedArray.
#include "PagedArray.h"
Public Types
using ElementType = InElementType
Static Public Attributes
static constexpr int32 Capacity = Size / sizeof(ElementType)
static constexpr int32 Size = InPageSizeInBytes
Detailed Description
template<typename InElementType, int32 InPageSizeInBytes>
struct UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >
Page traits struct for TPagedArray.
Definition at line 28 of file Runtime/Core/Public/Containers/PagedArray.h.
Member Typedef Documentation
ElementType
template<typename InElementType, int32 InPageSizeInBytes> using UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::ElementType = InElementType
Definition at line 32 of file Runtime/Core/Public/Containers/PagedArray.h.
Field Documentation
Capacity
template<typename InElementType, int32 InPageSizeInBytes> int32 UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity = Size / sizeof(ElementType) static constexpr
Definition at line 35 of file Runtime/Core/Public/Containers/PagedArray.h.
Referenced by TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::AddPage(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::CopyUnchecked(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Empty(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GetPageIndex(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GetPageOffset(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Max(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::MaxPerPage(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::NumRequiredPages(), and TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::SetNum().
Size
template<typename InElementType, int32 InPageSizeInBytes> int32 UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Size = InPageSizeInBytes static constexpr
Definition at line 34 of file Runtime/Core/Public/Containers/PagedArray.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/PagedArray.h