Unreal Engine 5.6 C++ API: TOptional< OptionalType > Struct Template Reference
TOptional< OptionalType > Struct Template Reference
When we have an optional value IsSet() returns true, and GetValue() is meaningful.
#include "Optional.h"
Public Types
using ElementType = OptionalType
Public Member Functions
TOptional ()
Construct an OptionalType with no value; i.e.
TOptional (const OptionalType &InValue)
Construct an OptionalType with a valid value.
TOptional (const TOptional &Other)
Copy/Move construction.
template<typename... ArgTypes>
TOptional (EInPlace, ArgTypes &&... Args)
TOptional (FNullOpt)
Construct an OptionalType with an invalid value.
TOptional (OptionalType &&InValue)
TOptional (TOptional &&Other)
~TOptional ()
template<typename... ArgsType>
OptionalType & Emplace (ArgsType &&... Args)
const OptionalType & Get (const OptionalType &DefaultValue UE_LIFETIMEBOUND) const UE_LIFETIMEBOUND
OptionalType * GetPtrOrNull ()
FORCEINLINE const OptionalType * GetPtrOrNull () const
OptionalType & GetValue ()
FORCEINLINE const OptionalType & GetValue () const
bool IsSet () const
FORCEINLINE operator bool () const
OptionalType & operator* ()
FORCEINLINE const OptionalType & operator* () const
OptionalType * operator-> ()
FORCEINLINE const OptionalType * operator-> () const
TOptional & operator= (const OptionalType &InValue)
TOptional & operator= (const TOptional &Other)
TOptional & operator= (OptionalType &&InValue)
TOptional & operator= (TOptional &&Other)
void Reset ()
void Serialize (FArchive &Ar)
Private Types
using ValueStorageType = std::conditional_t<bUsingIntrusiveUnsetState, uint8[sizeof(OptionalType)], UE::Core::Private::TNonIntrusiveOptionalStorage<sizeof(OptionalType)>>
Private Member Functions
FORCEINLINE void DestroyValue ()
Destroys the value, must only be called if the value is set, and callers must then mark the value unset or construct a new value in place.
Private Attributes
ValueStorageType Value
Static Private Attributes
static constexpr bool bUsingIntrusiveUnsetState = HasIntrusiveUnsetOptionalState<OptionalType>()
Friends
bool operator!= (const TOptional &Lhs, const TOptional &Rhs)
bool operator== (const TOptional &Lhs, const TOptional &Rhs)
Detailed Description
template<typename OptionalType>
struct TOptional< OptionalType >
When we have an optional value IsSet() returns true, and GetValue() is meaningful.
Otherwise GetValue() is not meaningful.
Definition at line 56 of file Optional.h.
Member Typedef Documentation
ElementType
template<typename OptionalType> using TOptional< OptionalType >::ElementType = OptionalType
Definition at line 62 of file Optional.h.
ValueStorageType
template<typename OptionalType> using TOptional< OptionalType >::ValueStorageType = std::conditional_t<bUsingIntrusiveUnsetState, uint8[sizeof(OptionalType)], UE::Core::Private::TNonIntrusiveOptionalStorage<sizeof(OptionalType)>> private
Definition at line 420 of file Optional.h.
Constructor & Destructor Documentation
TOptional() [1/7]
template<typename OptionalType> TOptional< OptionalType >::TOptional (const OptionalType & InValue) inline nodiscard
Construct an OptionalType with a valid value.
Definition at line 65 of file Optional.h.
TOptional() [2/7]
template<typename OptionalType> TOptional< OptionalType >::TOptional (OptionalType && InValue) inline nodiscard
Definition at line 69 of file Optional.h.
TOptional() [3/7]
template<typename OptionalType> template<typename... ArgTypes> TOptional< OptionalType >::TOptional (EInPlace , ArgTypes &&... Args) inline explicit nodiscard
Definition at line 74 of file Optional.h.
TOptional() [4/7]
template<typename OptionalType> TOptional< OptionalType >::TOptional (FNullOpt) inline nodiscard
Construct an OptionalType with an invalid value.
Definition at line 110 of file Optional.h.
TOptional() [5/7]
template<typename OptionalType> TOptional< OptionalType >::TOptional () inline nodiscard
Construct an OptionalType with no value; i.e.
unset
Definition at line 116 of file Optional.h.
~TOptional()
template<typename OptionalType> TOptional< OptionalType >::~TOptional () inline
Definition at line 128 of file Optional.h.
TOptional() [6/7]
template<typename OptionalType> TOptional< OptionalType >::TOptional (const TOptional< OptionalType > & Other) inline nodiscard
Copy/Move construction.
Definition at line 134 of file Optional.h.
TOptional() [7/7]
template<typename OptionalType> TOptional< OptionalType >::TOptional (TOptional< OptionalType > && Other) inline nodiscard
Definition at line 153 of file Optional.h.
Member Function Documentation
DestroyValue()
template<typename OptionalType> FORCEINLINE void TOptional< OptionalType >::DestroyValue () inline private
Destroys the value, must only be called if the value is set, and callers must then mark the value unset or construct a new value in place.
Definition at line 408 of file Optional.h.
Referenced by TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Emplace(), and TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Reset().
Emplace()
template<typename OptionalType> template<typename... ArgsType> OptionalType & TOptional< OptionalType >::Emplace (ArgsType &&... Args) inline
Definition at line 238 of file Optional.h.
Referenced by TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), UE::MovieScene::TMaskedBlendable< double, 1 >::Resolve(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Serialize(), and UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::VisitInterrogationAllocation().
Get()
template<typename OptionalType> const OptionalType & TOptional< OptionalType >::Get (const OptionalType &DefaultValue UE_LIFETIMEBOUND) const inline nodiscard
Returns
The optional value when set; DefaultValue otherwise.
Definition at line 389 of file Optional.h.
Referenced by SGraphPinVector< NumericType >::ConvertDefaultValueStringToVector(), SGraphPinVectorSlider< NumericType >::ConvertDefaultValueStringToVector(), TBlendableTokenStack< DataType >::SavePreAnimatedStateImpl(), and SNumericEntryBox< NumericType >::SendChangesFromText().
GetPtrOrNull() [1/2]
template<typename OptionalType> OptionalType * TOptional< OptionalType >::GetPtrOrNull () inline nodiscard
Returns
A pointer to the optional value when set, nullptr otherwise.
Definition at line 395 of file Optional.h.
Referenced by TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::GetPtrOrNull().
GetPtrOrNull() [2/2]
template<typename OptionalType> FORCEINLINE const OptionalType * TOptional< OptionalType >::GetPtrOrNull () const inline nodiscard
Definition at line 399 of file Optional.h.
GetValue() [1/2]
template<typename OptionalType> OptionalType & TOptional< OptionalType >::GetValue () inline nodiscard
Returns
The optional value; undefined when IsSet() returns false.
Definition at line 360 of file Optional.h.
Referenced by UE::Geometry::TFastWindingTree< TriangleMeshType >::build_fast_winding_cache(), DEFINE_EXPRESSION_NODE_TYPE(), TMpscQueue< T, AllocatorType >::Dequeue(), TSpscQueue< T, AllocatorType >::Dequeue(), UE::Insights::FAsTextValueFormatter::FormatValue(), UE::Insights::FInt64ValueFormatterAsHex32::FormatValue(), UE::Insights::FInt64ValueFormatterAsHex64::FormatValue(), UE::Insights::FInt64ValueFormatterAsNumber::FormatValue(), UE::Insights::FTextValueFormatter::FormatValue(), SGraphPinNumSlider< NumericType >::GetDefaultValueWidget(), FSlateApplication::GetUserFromControllerId(), FSlateApplication::GetUserFromControllerId(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::GetValue(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::ModifyByCurrentAndWeight(), TAddKeyImpl< FMovieSceneFloatChannel, float >::ModifyByCurrentAndWeight(), TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ModifyByCurrentAndWeight(), SGraphPinNumSlider< NumericType >::OnBeginSliderMovement(), FArguments< ItemType >::OnDrop(), SCommonListView< ItemType >::OnFocusReceived(), SListView< TSharedPtr< FString > >::OnNavigation(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator*(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator->(), Metasound::TArrayRandomGetOperator< ArrayType >::Reset(), UE::MovieScene::TMaskedBlendable< double, 1 >::Resolve(), SNumericEntryBox< NumericType >::SendChangesFromText(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Serialize(), SVector2DSlider< NumericType >::SyncValues(), SVector4Slider< NumericType >::SyncValues(), SVectorSlider< NumericType >::SyncValues(), SGridLineSpacingList::ValueTextCommitted(), UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::VisitAllocationCached(), and UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::VisitInterrogationAllocation().
GetValue() [2/2]
template<typename OptionalType> FORCEINLINE const OptionalType & TOptional< OptionalType >::GetValue () const inline nodiscard
Definition at line 365 of file Optional.h.
IsSet()
template<typename OptionalType> bool TOptional< OptionalType >::IsSet () const inline nodiscard
Returns
true when the value is meaningful; false if calling GetValue() is undefined.
Definition at line 343 of file Optional.h.
Referenced by TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::TOptional(), UE::Geometry::TFastWindingTree< TriangleMeshType >::build_fast_winding_cache(), DEFINE_EXPRESSION_NODE_TYPE(), TMpscQueue< T, AllocatorType >::Dequeue(), TSpscQueue< T, AllocatorType >::Dequeue(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Emplace(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::Execute(), UE::Insights::FAsTextValueFormatter::FormatValue(), UE::Insights::FInt64ValueFormatterAsHex32::FormatValue(), UE::Insights::FInt64ValueFormatterAsHex64::FormatValue(), UE::Insights::FInt64ValueFormatterAsNumber::FormatValue(), UE::Insights::FTextValueFormatter::FormatValue(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Get(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::GetPtrOrNull(), FSlateApplication::GetUserFromControllerId(), FSlateApplication::GetUserFromControllerId(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::GetValue(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::ModifyByCurrentAndWeight(), TAddKeyImpl< FMovieSceneFloatChannel, float >::ModifyByCurrentAndWeight(), TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ModifyByCurrentAndWeight(), FArguments< ItemType >::OnDrop(), SCommonListView< ItemType >::OnFocusReceived(), SListView< TSharedPtr< FString > >::OnNavigation(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator bool(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator==, Metasound::TArrayRandomGetOperator< ArrayType >::Reset(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Reset(), UE::MovieScene::TMaskedBlendable< double, 1 >::Resolve(), TArriveAttributeInterpolator< NumericType >::Restart(), TVerletAttributeInterpolator< NumericType >::Restart(), SNumericEntryBox< NumericType >::SendChangesFromText(), and TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Serialize().
operator bool()
template<typename OptionalType> FORCEINLINE TOptional< OptionalType >::operator bool () const inline explicit nodiscard
Definition at line 354 of file Optional.h.
operator*() [1/2]
template<typename OptionalType> OptionalType & TOptional< OptionalType >::operator* () inline nodiscard
Definition at line 379 of file Optional.h.
operator*() [2/2]
template<typename OptionalType> FORCEINLINE const OptionalType & TOptional< OptionalType >::operator* () const inline nodiscard
Definition at line 383 of file Optional.h.
operator->() [1/2]
template<typename OptionalType> OptionalType * TOptional< OptionalType >::operator-> () inline nodiscard
Definition at line 370 of file Optional.h.
operator->() [2/2]
template<typename OptionalType> FORCEINLINE const OptionalType * TOptional< OptionalType >::operator-> () const inline nodiscard
Definition at line 374 of file Optional.h.
operator=() [1/4]
template<typename OptionalType> TOptional & TOptional< OptionalType >::operator= (const OptionalType & InValue) inline
Definition at line 204 of file Optional.h.
operator=() [2/4]
template<typename OptionalType> TOptional & TOptional< OptionalType >::operator= (const TOptional< OptionalType > & Other) inline
Definition at line 173 of file Optional.h.
operator=() [3/4]
template<typename OptionalType> TOptional & TOptional< OptionalType >::operator= (OptionalType && InValue) inline
Definition at line 212 of file Optional.h.
operator=() [4/4]
template<typename OptionalType> TOptional & TOptional< OptionalType >::operator= (TOptional< OptionalType > && Other) inline
Definition at line 188 of file Optional.h.
Reset()
template<typename OptionalType> void TOptional< OptionalType >::Reset () inline
Definition at line 221 of file Optional.h.
Referenced by TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::~TOptional(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator=(), and TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::Serialize().
Serialize()
template<typename OptionalType> void TOptional< OptionalType >::Serialize (FArchive & Ar) inline
Definition at line 312 of file Optional.h.
Friends And Related Symbol Documentation
operator!=
template<typename OptionalType> bool operator!= (const TOptional< OptionalType > & Lhs, const TOptional< OptionalType > & Rhs) friend
Definition at line 307 of file Optional.h.
operator==
template<typename OptionalType> bool operator== (const TOptional< OptionalType > & Lhs, const TOptional< OptionalType > & Rhs) friend
Definition at line 290 of file Optional.h.
Field Documentation
bUsingIntrusiveUnsetState
template<typename OptionalType> bool TOptional< OptionalType >::bUsingIntrusiveUnsetState = HasIntrusiveUnsetOptionalState<OptionalType>() static constexpr private
Definition at line 59 of file Optional.h.
Value
template<typename OptionalType> ValueStorageType TOptional< OptionalType >::Value private
Definition at line 421 of file Optional.h.
Referenced by TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::operator==.
The documentation for this struct was generated from the following files:
NavigationToolItemDropHandler.h
Optional.h