Unreal Engine 5.6 C++ Documentation: UInputDeviceLibrary Class Reference
UInputDeviceLibrary Class Reference
A static BP library that exposes Input Device data to blueprints.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceLibrary.h>
Static Public Member Functions
static APlayerController * GetPlayerControllerFromPlatformUser (const FPlatformUserId UserId)
Get the player controller who has the given Platform User ID.
static APlayerController * GetPlayerControllerFromInputDevice (const FInputDeviceId DeviceId)
Get the player controller who owns the given input device id.
static bool IsDevicePropertyHandleValid (const FInputDevicePropertyHandle &InHandle)
Returns true if the given handle is valid.
static int32 GetAllInputDevicesForUser (const FPlatformUserId UserId, TArray< FInputDeviceId > &OutInputDevices)
Populates the OutInputDevices array with any InputDeviceID's that are mapped to the given platform user.
static int32 GetAllInputDevices (TArray< FInputDeviceId > &OutInputDevices)
Get all mapped input devices on this platform regardless of their connection state.
static int32 GetAllConnectedInputDevices (TArray< FInputDeviceId > &OutInputDevices)
Gather all currently connected input devices.
static int32 GetAllActiveUsers (TArray< FPlatformUserId > &OutUsers)
Get all currently active platform ids, anyone who has a mapped input device.
static FPlatformUserId GetUserForUnpairedInputDevices ()
Returns the platform user id that is being used for unmapped input devices.
static FPlatformUserId GetPrimaryPlatformUser ()
Returns the 'Primary' Platform user for this platform.
static bool IsUnpairedUserId (const FPlatformUserId PlatformId)
Returns true if the given Platform User Id is the user for unpaired input devices on this platform.
static bool IsInputDeviceMappedToUnpairedUser (const FInputDeviceId InputDevice)
Returns true if the given input device is mapped to the unpaired platform user id.
static FInputDeviceId GetDefaultInputDevice ()
Returns the default device id used for things like keyboard/mouse input.
static FPlatformUserId GetUserForInputDevice (FInputDeviceId DeviceId)
Returns the platform user attached to this input device, or PLATFORMUSERID_NONE if invalid.
static FInputDeviceId GetPrimaryInputDeviceForUser (FPlatformUserId UserId)
Returns the primary input device used by a specific player, or INPUTDEVICEID_NONE if invalid.
static EInputDeviceConnectionState GetInputDeviceConnectionState (const FInputDeviceId DeviceId)
Gets the connection state of the given input device.
static bool IsValidInputDevice (FInputDeviceId DeviceId)
Check if the given input device is valid.
static bool IsValidPlatformId (FPlatformUserId UserId)
Check if the given platform ID is valid.
static FPlatformUserId PlatformUserId_None ()
Static invalid platform user.
static FInputDeviceId InputDeviceId_None ()
Static invalid input device.
static bool EqualEqual_PlatformUserId (FPlatformUserId A, FPlatformUserId B)
Returns true if PlatformUserId A is equal to PlatformUserId B (A == B)
static bool NotEqual_PlatformUserId (FPlatformUserId A, FPlatformUserId B)
Returns true if PlatformUserId A is not equal to PlatformUserId B (A != B)
static bool EqualEqual_InputDeviceId (FInputDeviceId A, FInputDeviceId B)
Returns true if InputDeviceId A is equal to InputDeviceId B (A == B)
static bool NotEqual_InputDeviceId (FInputDeviceId A, FInputDeviceId B)
Returns true if InputDeviceId A is not equal to InputDeviceId B (A != B)
Detailed Description
A static BP library that exposes Input Device data to blueprints.
See also
IPlatformInputDeviceMapper \note Keep any function comments up to date with those in GenericPlatformInputDeviceMapper.h!
Definition at line 22 of file InputDeviceLibrary.h.
Member Function Documentation
EqualEqual_InputDeviceId()
bool UInputDeviceLibrary::EqualEqual_InputDeviceId (FInputDeviceId A, FInputDeviceId B) static
Returns true if InputDeviceId A is equal to InputDeviceId B (A == B)
References EqualEqual_InputDeviceId().
EqualEqual_PlatformUserId()
bool UInputDeviceLibrary::EqualEqual_PlatformUserId (FPlatformUserId A, FPlatformUserId B) static
Returns true if PlatformUserId A is equal to PlatformUserId B (A == B)
References EqualEqual_PlatformUserId().
GetAllActiveUsers()
int32 UInputDeviceLibrary::GetAllActiveUsers (TArray< FPlatformUserId > & OutUsers) static
Get all currently active platform ids, anyone who has a mapped input device.
Parameters
OutUsers Array that will be populated with the platform users.
Returns
The number of active platform users
References GetAllActiveUsers().
GetAllConnectedInputDevices()
int32 UInputDeviceLibrary::GetAllConnectedInputDevices (TArray< FInputDeviceId > & OutInputDevices) static
Gather all currently connected input devices.
Parameters
OutInputDevices Array of input devices to populate
Returns
The number of connected input devices
References GetAllConnectedInputDevices().
GetAllInputDevices()
int32 UInputDeviceLibrary::GetAllInputDevices (TArray< FInputDeviceId > & OutInputDevices) static
Get all mapped input devices on this platform regardless of their connection state.
Parameters
OutInputDevices Array of input devices to populate
Returns
The number of connected input devices
References GetAllInputDevices().
GetAllInputDevicesForUser()
int32 UInputDeviceLibrary::GetAllInputDevicesForUser (const FPlatformUserId UserId, TArray< FInputDeviceId > & OutInputDevices) static
Populates the OutInputDevices array with any InputDeviceID's that are mapped to the given platform user.
Parameters
UserId The Platform User to gather the input devices of.
OutInputDevices Array of input device ID's that will be populated with the mapped devices.
Returns
The number of mapped devices, INDEX_NONE if the user was not found.
References GetAllInputDevicesForUser().
GetDefaultInputDevice()
FInputDeviceId UInputDeviceLibrary::GetDefaultInputDevice () static
Returns the default device id used for things like keyboard/mouse input.
References GetDefaultInputDevice().
GetInputDeviceConnectionState()
EInputDeviceConnectionState UInputDeviceLibrary::GetInputDeviceConnectionState (const FInputDeviceId DeviceId) static
Gets the connection state of the given input device.
Parameters
DeviceId The device to get the connection state of
Returns
The connection state of the given device. EInputDeviceConnectionState::Unknown if the device is not mapped
References GetInputDeviceConnectionState().
GetPlayerControllerFromInputDevice()
APlayerController * UInputDeviceLibrary::GetPlayerControllerFromInputDevice (const FInputDeviceId DeviceId) static
Get the player controller who owns the given input device id.
References GetPlayerControllerFromInputDevice().
GetPlayerControllerFromPlatformUser()
APlayerController * UInputDeviceLibrary::GetPlayerControllerFromPlatformUser (const FPlatformUserId UserId) static
Get the player controller who has the given Platform User ID.
References GetPlayerControllerFromPlatformUser().
GetPrimaryInputDeviceForUser()
FInputDeviceId UInputDeviceLibrary::GetPrimaryInputDeviceForUser (FPlatformUserId UserId) static
Returns the primary input device used by a specific player, or INPUTDEVICEID_NONE if invalid.
References GetPrimaryInputDeviceForUser().
GetPrimaryPlatformUser()
FPlatformUserId UInputDeviceLibrary::GetPrimaryPlatformUser () static
Returns the 'Primary' Platform user for this platform.
This typically has an internal ID of '0' and is used as the default platform user to map devices such as the keyboard and mouse that don't get assigned unique ID's from their owning platform code.
References GetPrimaryPlatformUser().
GetUserForInputDevice()
FPlatformUserId UInputDeviceLibrary::GetUserForInputDevice (FInputDeviceId DeviceId) static
Returns the platform user attached to this input device, or PLATFORMUSERID_NONE if invalid.
References GetUserForInputDevice().
GetUserForUnpairedInputDevices()
FPlatformUserId UInputDeviceLibrary::GetUserForUnpairedInputDevices () static
Returns the platform user id that is being used for unmapped input devices.
Will be PLATFORMUSERID_NONE if platform does not support this (this is the default behavior)
References GetUserForUnpairedInputDevices().
InputDeviceId_None()
FInputDeviceId UInputDeviceLibrary::InputDeviceId_None () static
Static invalid input device.
References InputDeviceId_None().
IsDevicePropertyHandleValid()
bool UInputDeviceLibrary::IsDevicePropertyHandleValid (const FInputDevicePropertyHandle & InHandle) static
Returns true if the given handle is valid.
References IsDevicePropertyHandleValid().
IsInputDeviceMappedToUnpairedUser()
bool UInputDeviceLibrary::IsInputDeviceMappedToUnpairedUser (const FInputDeviceId InputDevice) static
Returns true if the given input device is mapped to the unpaired platform user id.
References IsInputDeviceMappedToUnpairedUser().
IsUnpairedUserId()
bool UInputDeviceLibrary::IsUnpairedUserId (const FPlatformUserId PlatformId) static
Returns true if the given Platform User Id is the user for unpaired input devices on this platform.
References IsUnpairedUserId().
IsValidInputDevice()
bool UInputDeviceLibrary::IsValidInputDevice (FInputDeviceId DeviceId) static
Check if the given input device is valid.
Returns
True if the given input device is valid (it has been assigned an ID by the PlatformInputDeviceMapper)
References IsValidInputDevice().
IsValidPlatformId()
bool UInputDeviceLibrary::IsValidPlatformId (FPlatformUserId UserId) static
Check if the given platform ID is valid.
Returns
True if the platform ID is valid (it has been assigned by the PlatformInputDeviceMapper)
References IsValidPlatformId().
NotEqual_InputDeviceId()
bool UInputDeviceLibrary::NotEqual_InputDeviceId (FInputDeviceId A, FInputDeviceId B) static
Returns true if InputDeviceId A is not equal to InputDeviceId B (A != B)
References NotEqual_InputDeviceId().
NotEqual_PlatformUserId()
bool UInputDeviceLibrary::NotEqual_PlatformUserId (FPlatformUserId A, FPlatformUserId B) static
Returns true if PlatformUserId A is not equal to PlatformUserId B (A != B)
References NotEqual_PlatformUserId().
PlatformUserId_None()
FPlatformUserId UInputDeviceLibrary::PlatformUserId_None () static
Static invalid platform user.
References PlatformUserId_None().
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceLibrary.h