Unreal Engine 5.6 C++ API: IAnimationDataModel::FModelNotifier Struct Reference
IAnimationDataModel::FModelNotifier Struct Reference
#include "IAnimationDataModel.h"
Public Member Functions
FModelNotifier (TScriptInterface< IAnimationDataModel > ModelInterface)
virtual ~FModelNotifier ()=default
int32 GetBracketDepth () const
void Notify (EAnimDataModelNotifyType NotifyType)
Broadcasts a new EAnimDataModelNotifyType alongside of an empty payload.
template<typename T>
void Notify (EAnimDataModelNotifyType NotifyType, const T &PayloadData)
Broadcasts a new EAnimDataModelNotifyType with the provided payload data alongside it.
Protected Attributes
int32 BracketCounter = 0
TScriptInterface< IAnimationDataModel > DataModel
FAnimDataModelModifiedEvent & ModifiedEvent
FAnimDataModelModifiedDynamicEvent & ModifiedEventDynamic
Detailed Description
Definition at line 446 of file IAnimationDataModel.h.
Constructor & Destructor Documentation
~FModelNotifier()
virtual IAnimationDataModel::FModelNotifier::~FModelNotifier () virtual default
FModelNotifier()
IAnimationDataModel::FModelNotifier::FModelNotifier (TScriptInterface< IAnimationDataModel > ModelInterface) inline
Definition at line 497 of file IAnimationDataModel.h.
References DataModel, IAnimationDataModel::GetModifiedDynamicEvent(), IAnimationDataModel::GetModifiedEvent(), ModifiedEvent, and ModifiedEventDynamic.
Member Function Documentation
GetBracketDepth()
int32 IAnimationDataModel::FModelNotifier::GetBracketDepth () const inline
Definition at line 504 of file IAnimationDataModel.h.
References BracketCounter.
Notify() [1/2]
void IAnimationDataModel::FModelNotifier::Notify (EAnimDataModelNotifyType NotifyType) inline
Broadcasts a new EAnimDataModelNotifyType alongside of an empty payload.
Parameters
NotifyType Type of notify to broadcast
Definition at line 491 of file IAnimationDataModel.h.
References Notify().
Notify() [2/2]
template<typename T> void IAnimationDataModel::FModelNotifier::Notify (EAnimDataModelNotifyType NotifyType, const T & PayloadData) inline
Broadcasts a new EAnimDataModelNotifyType with the provided payload data alongside it.
Parameters
NotifyType Type of notify to broadcast
PayloadData Typed payload data
Definition at line 457 of file IAnimationDataModel.h.
References BracketCounter, check, DataModel, ModifiedEvent, and ModifiedEventDynamic.
Referenced by Notify().
Field Documentation
BracketCounter
int32 IAnimationDataModel::FModelNotifier::BracketCounter = 0 protected
Definition at line 513 of file IAnimationDataModel.h.
Referenced by GetBracketDepth(), and Notify().
DataModel
TScriptInterface<IAnimationDataModel> IAnimationDataModel::FModelNotifier::DataModel protected
Definition at line 510 of file IAnimationDataModel.h.
Referenced by FModelNotifier(), and Notify().
ModifiedEvent
FAnimDataModelModifiedEvent& IAnimationDataModel::FModelNotifier::ModifiedEvent protected
Definition at line 511 of file IAnimationDataModel.h.
Referenced by FModelNotifier(), and Notify().
ModifiedEventDynamic
FAnimDataModelModifiedDynamicEvent& IAnimationDataModel::FModelNotifier::ModifiedEventDynamic protected
Definition at line 512 of file IAnimationDataModel.h.
Referenced by FModelNotifier(), and Notify().
The documentation for this struct was generated from the following file:
IAnimationDataModel.h