Unreal Engine 5.6 C++ API: Metasound::FGraphOperator Class Reference
Metasound::FGraphOperator Class Reference
#include "MetasoundGraphOperator.h"
Data Structures
struct FExecuteEntry
struct FPostExecuteEntry
struct FResetEntry
Public Types
using FExecuteFunction = IOperator::FExecuteFunction
using FOperatorPtr = TUniquePtr<IOperator>
using FResetFunction = IOperator::FResetFunction
using FResetParams = IOperator::FResetParams
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
FGraphOperator ()=default
METASOUNDGRAPHCORE_API FGraphOperator (TUniquePtr< DirectedGraphAlgo::FStaticGraphOperatorData > InOperatorData)
virtual ~FGraphOperator ()=default
METASOUNDGRAPHCORE_API void AppendOperator (FOperatorPtr InOperator)
virtual METASOUNDGRAPHCORE_API void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual METASOUNDGRAPHCORE_API void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
METASOUNDGRAPHCORE_API void Execute ()
virtual METASOUNDGRAPHCORE_API IOperator::FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
METASOUNDGRAPHCORE_API void PostExecute ()
METASOUNDGRAPHCORE_API void Reset (const FResetParams &InParams)
METASOUNDGRAPHCORE_API void SetVertexInterfaceData (FVertexInterfaceData &&InVertexData)
Public Member Functions inherited from Metasound::TExecutableOperator< FGraphOperator >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Private Member Functions
FGraphOperator (const FGraphOperator &)=delete
FGraphOperator & operator= (const FGraphOperator &)=delete
Static Private Member Functions
static METASOUNDGRAPHCORE_API void StaticPostExecute (IOperator *Operator)
Private Attributes
TArray< TUniquePtr< IOperator > > ActiveOperators
TArray< FExecuteEntry > ExecuteStack
TArray< FPostExecuteEntry > PostExecuteStack
TArray< FResetEntry > ResetStack
FVertexInterfaceData VertexData
Detailed Description
Definition at line 23 of file MetasoundGraphOperator.h.
Member Typedef Documentation
FExecuteFunction
using Metasound::FGraphOperator::FExecuteFunction = IOperator::FExecuteFunction
Definition at line 27 of file MetasoundGraphOperator.h.
FOperatorPtr
using Metasound::FGraphOperator::FOperatorPtr = TUniquePtr<IOperator>
Definition at line 26 of file MetasoundGraphOperator.h.
FResetFunction
using Metasound::FGraphOperator::FResetFunction = IOperator::FResetFunction
Definition at line 28 of file MetasoundGraphOperator.h.
FResetParams
using Metasound::FGraphOperator::FResetParams = IOperator::FResetParams
Definition at line 29 of file MetasoundGraphOperator.h.
Constructor & Destructor Documentation
FGraphOperator() [1/3]
Metasound::FGraphOperator::FGraphOperator () default
Referenced by FGraphOperator(), and operator=().
FGraphOperator() [2/3]
METASOUNDGRAPHCORE_API Metasound::FGraphOperator::FGraphOperator (TUniquePtr< DirectedGraphAlgo::FStaticGraphOperatorData > InOperatorData)
References UE_API.
~FGraphOperator()
virtual Metasound::FGraphOperator::~FGraphOperator () virtual default
FGraphOperator() [3/3]
Metasound::FGraphOperator::FGraphOperator (const FGraphOperator &) private delete
References FGraphOperator().
Member Function Documentation
AppendOperator()
METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::AppendOperator (FOperatorPtr InOperator)
References UE_API.
BindInputs()
virtual METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::BindInputs (FInputVertexInterfaceData & InVertexData) override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
References UE_API.
BindOutputs()
virtual METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::BindOutputs (FOutputVertexInterfaceData & InVertexData) override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
References UE_API.
Execute()
METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::Execute ()
References UE_API.
GetPostExecuteFunction()
virtual METASOUNDGRAPHCORE_API IOperator::FPostExecuteFunction Metasound::FGraphOperator::GetPostExecuteFunction () override virtual
Return the FPostExecute function to call during graph post execution.
The IOperator* argument to the FPostExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be post executed.
Reimplemented from Metasound::TExecutableOperator< FGraphOperator >.
References UE_API.
operator=()
FGraphOperator & Metasound::FGraphOperator::operator= (const FGraphOperator &) private delete
References FGraphOperator().
PostExecute()
METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::PostExecute ()
References UE_API.
Reset()
METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::Reset (const FResetParams & InParams)
References UE_API.
SetVertexInterfaceData()
METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::SetVertexInterfaceData (FVertexInterfaceData && InVertexData)
References UE_API.
StaticPostExecute()
METASOUNDGRAPHCORE_API void Metasound::FGraphOperator::StaticPostExecute (IOperator * Operator) static private
References UE_API.
Field Documentation
ActiveOperators
TArray<TUniquePtr<IOperator> > Metasound::FGraphOperator::ActiveOperators private
Definition at line 90 of file MetasoundGraphOperator.h.
ExecuteStack
TArray<FExecuteEntry> Metasound::FGraphOperator::ExecuteStack private
Definition at line 87 of file MetasoundGraphOperator.h.
PostExecuteStack
TArray<FPostExecuteEntry> Metasound::FGraphOperator::PostExecuteStack private
Definition at line 88 of file MetasoundGraphOperator.h.
ResetStack
TArray<FResetEntry> Metasound::FGraphOperator::ResetStack private
Definition at line 89 of file MetasoundGraphOperator.h.
VertexData
FVertexInterfaceData Metasound::FGraphOperator::VertexData private
Definition at line 91 of file MetasoundGraphOperator.h.
The documentation for this class was generated from the following file:
MetasoundGraphOperator.h