Unreal Engine 5.6 C++ API: UE::Insights::FStopwatch Struct Reference
UE::Insights::FStopwatch Struct Reference
#include "Stopwatch.h"
Public Member Functions
double GetAccumulatedTime () const
uint64 GetAccumulatedTimeMs () const
void Reset ()
void Restart ()
void Start ()
void Stop ()
void Update ()
Static Public Member Functions
static uint64 Cycles64ToMilliseconds (const uint64 Cycles64)
static double Cycles64ToSeconds (const uint64 Cycles64)
Data Fields
uint64 AccumulatedTime = 0
bool bIsStarted = false
uint64 StartTime = 0
Detailed Description
Definition at line 13 of file Stopwatch.h.
Member Function Documentation
Cycles64ToMilliseconds()
uint64 UE::Insights::FStopwatch::Cycles64ToMilliseconds (const uint64 Cycles64) inline static
Definition at line 76 of file Stopwatch.h.
References FGenericPlatformTime::GetSecondsPerCycle64(), and Milliseconds.
Referenced by GetAccumulatedTimeMs().
Cycles64ToSeconds()
double UE::Insights::FStopwatch::Cycles64ToSeconds (const uint64 Cycles64) inline static
Definition at line 71 of file Stopwatch.h.
References FGenericPlatformTime::GetSecondsPerCycle64().
Referenced by GetAccumulatedTime().
GetAccumulatedTime()
double UE::Insights::FStopwatch::GetAccumulatedTime () const inline
Definition at line 61 of file Stopwatch.h.
References AccumulatedTime, and Cycles64ToSeconds().
GetAccumulatedTimeMs()
uint64 UE::Insights::FStopwatch::GetAccumulatedTimeMs () const inline
Definition at line 66 of file Stopwatch.h.
References AccumulatedTime, and Cycles64ToMilliseconds().
Reset()
void UE::Insights::FStopwatch::Reset () inline
Definition at line 54 of file Stopwatch.h.
References AccumulatedTime, bIsStarted, and StartTime.
Restart()
void UE::Insights::FStopwatch::Restart () inline
Definition at line 47 of file Stopwatch.h.
References AccumulatedTime, bIsStarted, FAndroidTime::Cycles64(), and StartTime.
Start()
void UE::Insights::FStopwatch::Start () inline
Definition at line 19 of file Stopwatch.h.
References bIsStarted, FAndroidTime::Cycles64(), and StartTime.
Stop()
void UE::Insights::FStopwatch::Stop () inline
Definition at line 28 of file Stopwatch.h.
References AccumulatedTime, bIsStarted, FAndroidTime::Cycles64(), and StartTime.
Update()
void UE::Insights::FStopwatch::Update () inline
Definition at line 37 of file Stopwatch.h.
References AccumulatedTime, bIsStarted, FAndroidTime::Cycles64(), and StartTime.
Field Documentation
AccumulatedTime
uint64 UE::Insights::FStopwatch::AccumulatedTime = 0
Definition at line 15 of file Stopwatch.h.
Referenced by GetAccumulatedTime(), GetAccumulatedTimeMs(), Reset(), Restart(), Stop(), and Update().
bIsStarted
bool UE::Insights::FStopwatch::bIsStarted = false
Definition at line 17 of file Stopwatch.h.
Referenced by Reset(), Restart(), Start(), Stop(), and Update().
StartTime
uint64 UE::Insights::FStopwatch::StartTime = 0
Definition at line 16 of file Stopwatch.h.
Referenced by Reset(), Restart(), Start(), Stop(), and Update().
The documentation for this struct was generated from the following file:
Stopwatch.h