Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FMergeRenderContext Class Reference
UE::Landscape::EditLayers::FMergeRenderContext Class Reference
Utility class that contains everything necessary to perform the batched merge : scratch render targets, list of batches, etc.
#include "LandscapeEditLayerMergeRenderContext.h"
Data Structures
struct FOnRenderBatchTargetGroupDoneParams
Public Member Functions
FMergeRenderContext (const FMergeContext &InMergeContext)
FMergeRenderContext (const FMergeRenderContext &Other)=default
FMergeRenderContext (FMergeRenderContext &&Other)=default
virtual ~FMergeRenderContext ()
const TBitArray & GetFinalTargetLayerBitIndices () const
bool IsValid () const
FMergeRenderContext & operator= (const FMergeRenderContext &Other)=default
FMergeRenderContext & operator= (FMergeRenderContext &&Other)=default
void Render (TFunction< void(const FOnRenderBatchTargetGroupDoneParams &, UE::Landscape::FRDGBuilderRecorder &)> OnRenderBatchTargetGroupDone)
void RenderExpandedRenderTarget (UE::Landscape::FRDGBuilderRecorder &RDGBuilderRecorder)
Duplicates the vertex data from the (sub-)sections of the batch, assuming GetBlendRenderTargetRead() is the RT that is read from and GetBlendRenderTargetWrite() the one that is written to.
void RenderValidityRenderTargets (UE::Landscape::FRDGBuilderRecorder &RDGBuilderRecorder)
Render the stencil render targets for each target layer in this merge for this batch.
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>>
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") bool HasBlackboardItem() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const TArray< TInstancedStruct< FLandscapeEditLayerMergeRenderBlackboardItem > > &GetAllBlackboardItems() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline const TArray< FMergeRenderBatch > &GetRenderBatches() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline FIntPoint GetMaxNeededResolution() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API const FMergeRenderBatch *GetCurrentRenderBatch() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FTransform ComputeVisualLogTransform(const FTransform &InTransform) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeScratchRenderTarget *GetBlendRenderTargetRead() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeScratchRenderTarget *GetBlendRenderTargetReadPrevious() const
UE_EXPERIMENTAL(5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void CycleBlendRenderTargets(UE UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeScratchRenderTarget *GetBlendRenderTargetWrite() const
Cycle between the 3 render targets used for blending: Write becomes Read -> Read becomes ReadPrevious -> ReadPrevious becomes Write The new Write RT will be transitioned to state == InDesiredWriteAccess (if != ERHIAccess::None) The new Read RT will be transitioned to state ERHIAccess::SRVMask The new ReadPrevious RT will stay in state ERHIAccess::SRVMask.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeScratchRenderTarget *GetValidityRenderTarget(const FName &InTargetLayerName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void GenericBlendLayer(const FBlendParams &InBlendParams
Performs a generic blend assuming GetBlendRenderTargetWrite() is the RT that contains the layer to blend and GetBlendRenderTargetRead() the one that contains the result of the merge up until this layer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void IncrementVisualLogOffset()
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void ResetVisualLogOffset()
template<typename T, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>>
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") T &AddBlackboardItem(TArgs &&... InArgs)
Create a new blackboard item of type T and adds it to the context's list.
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>>
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") T &GetBlackboardItem()
template<typename T, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>>
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") T &GetOrCreateBlackboardItem(TArgs &&... InArgs)
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>>
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") T *TryGetBlackboardItem()
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>>
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") TArray< T * > GetBlackboardItems()
Public Member Functions inherited from UE::Landscape::EditLayers::FMergeContext
FMergeContext (ALandscape *InLandscape, bool bInIsHeightmapMerge, bool bInSkipProceduralRenderers)
FMergeContext (const FMergeContext &Other)=default
FMergeContext (FMergeContext &&Other)=default
virtual ~FMergeContext ()=default
const TBitArray & GetNegatedVisibilityTargetLayerMask () const
Same as GetVisibilityTargetLayerMask() but negated.
const TBitArray & GetValidTargetLayerBitIndices () const
int32 GetVisibilityTargetLayerIndex () const
const TBitArray & GetVisibilityTargetLayerMask () const
FMergeContext & operator= (const FMergeContext &Other)=default
FMergeContext & operator= (FMergeContext &&Other)=default
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline ALandscape *GetLandscape() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline bool IsHeightmapMerge() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline bool ShouldSkipProceduralRenderers() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline const TArray< FName > &GetAllTargetLayerNames() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline const TArray< ULandscapeLayerInfoObject * > &GetAllWeightmapLayerInfos() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline ULandscapeInfo *GetLandscapeInfo() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FName GetTargetLayerNameForIndex(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FName GetTargetLayerNameForIndexChecked(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForLayerInfo(ULandscapeLayerInfoObject *InLayerInfo) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForLayerInfoChecked(ULandscapeLayerInfoObject *InLayerInfo) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForName(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForNameChecked(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 IsTargetLayerIndexValid(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 IsValidTargetLayerName(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 IsValidTargetLayerNameChecked(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TArray< FName > ConvertTargetLayerBitIndicesToNames(const TBitArray<> &InTargetLayerBitIndices) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TArray< ULandscapeLayerInfoObject * > ConvertTargetLayerBitIndicesToLayerInfos(const TBitArray<> &InTargetLayerBitIndices) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> BuildTargetLayerBitIndices(bool bInBitValue) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> ConvertTargetLayerNamesToBitIndices(TConstArrayView< FName > InTargetLayerNames) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> ConvertTargetLayerNamesToBitIndicesChecked(TConstArrayView< FName > InTargetLayerNames) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeLayerInfoObject *GetTargetLayerInfoForIndex(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeLayerInfoObject *GetTargetLayerInfoForName(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeLayerInfoObject *GetTargetLayerInfoForNameChecked(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void ForEachTargetLayer(const TBitArray<> &InTargetLayerBitIndices
Runs the given function for each all valid target layer in the bit indices in parameters, with the possibility of early exit Most easily used with a lambda as follows: ForEachTargetLayer([](int32 InTargetLayerIndex, FName InTargetLayerName) -> bool { return continueLoop ?
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void ForEachValidTargetLayer(TFunctionRef< bool(int32
Same as ForEachTargetLayer but skips over invalid target layers.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") TArray< FName > GetValidTargetLayerNames() const
Data Fields
FRenderParams UE::Landscape::FRDGBuilderRecorder & RDGBuilderRecorder
FRenderParams & RenderParams
Data Fields inherited from UE::Landscape::EditLayers::FMergeContext
friend ALandscape
TFunctionRef< bool(int32, const FName &, ULandscapeLayerInfoObject *)> Fn const
const FName ULandscapeLayerInfoObject *Fn const
Private Member Functions
void AllocateBatchResources (const FMergeRenderBatch &InRenderBatch)
Allocate all needed render targets for this batch.
void AllocateResources ()
Allocate all needed render targets for this merge.
void FreeBatchResources (const FMergeRenderBatch &InRenderBatch)
Free all render targets used in this batch.
void FreeResources ()
Free all render targets used in this merge.
Private Attributes
TArray< TInstancedStruct< FLandscapeEditLayerMergeRenderBlackboardItem > > BlackboardItems
Generic data struct to store some data to pass around throughout the context's lifetime.
TStaticArray< ULandscapeScratchRenderTarget *, NumBlendRenderTargets > BlendRenderTargets
Render targets that are used throughout the blending operations (they could be texture arrays in the case of multiple weightmaps)
TMap< ULandscapeComponent *, TBitArray<> > ComponentToTargetLayerBitIndices
List of components involved in this merge and the target layers they're writing to (each bit corresponds to the target layer name in AllTargetLayerNames)
int32 CurrentBlendRenderTargetWriteIndex = -1
int32 CurrentRenderBatchIndex = INDEX_NONE
Current batch being rendered.
FVector CurrentVisualLogOffset = FVector(ForceInitToZero)
Offset for visual debugging.
TBitArray FinalTargetLayerBitIndices
Final list of target layer names being involved in this merge context.
double MaxLocalHeight = DBL_MIN
Maximum height of all components to render in local space.
int32 MaxNeededNumSlices = 0
Maximum number of slices needed by a given batch / target layer group in this context (means we won't ever need more than this number of slices in a given render target texture array during the whole merge.
FIntPoint MaxNeededResolution = FIntPoint(ForceInit)
Maximum resolution needed by a given batch in this context (means we won't ever need more than this size of a render target during the whole merge.
TMap< FName, ULandscapeScratchRenderTarget * > PerTargetLayerValidityRenderTargets
Render targets storing the validity of each pixel wrt the target layer (i.e.
TArray< FMergeRenderBatch > RenderBatches
Successive batches of components being processed by this context.
TArray< TSet< ULandscapeComponent * > > TargetLayersToComponents
Reverse lookup of ComponentToTargetLayerBitIndices : one entry per element in ComponentToTargetLayerBitIndices, each entry containing all of the components involved in this merge for this target layer.
Static Private Attributes
static constexpr int32 NumBlendRenderTargets = 3
Friends
class ::ALandscape
Additional Inherited Members
Protected Attributes inherited from UE::Landscape::EditLayers::FMergeContext
TArray< FName > AllTargetLayerNames
List of all target layer names that can possibly be rendered on this landscape (even invalid ones).
TArray< ULandscapeLayerInfoObject * > AllWeightmapLayerInfos
Per-target layer info.
bool bIsHeightmapMerge = false
Type of merge being requested.
bool bSkipProceduralRenderers = false
Allows to skip all non-default (i.e.
ALandscape * Landscape = nullptr
Landscape being merged.
ULandscapeInfo * LandscapeInfo = nullptr
Landscape info associated with the landscape being merged.
TBitArray NegatedVisibilityTargetLayerMask
Bit mask that corresponds to all target layers except the visibility layer.
TBitArray ValidTargetLayerBitIndices
List of valid target layers.
int32 VisibilityTargetLayerIndex = INDEX_NONE
TBitArray VisibilityTargetLayerMask
Bit mask that corresponds to only the visibility layer.
Detailed Description
Utility class that contains everything necessary to perform the batched merge : scratch render targets, list of batches, etc.
Definition at line 284 of file LandscapeEditLayerMergeRenderContext.h.
Constructor & Destructor Documentation
FMergeRenderContext() [1/3]
UE::Landscape::EditLayers::FMergeRenderContext::FMergeRenderContext (const FMergeContext & InMergeContext)
References UE::Landscape::EditLayers::FMergeContext::FMergeContext().
Referenced by FMergeRenderContext(), FMergeRenderContext(), UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::FOnRenderBatchTargetGroupDoneParams(), operator=(), and operator=().
~FMergeRenderContext()
virtual UE::Landscape::EditLayers::FMergeRenderContext::~FMergeRenderContext () virtual
FMergeRenderContext() [2/3]
UE::Landscape::EditLayers::FMergeRenderContext::FMergeRenderContext (const FMergeRenderContext & Other) default
References FMergeRenderContext(), and Other.
FMergeRenderContext() [3/3]
UE::Landscape::EditLayers::FMergeRenderContext::FMergeRenderContext (FMergeRenderContext && Other) default
References FMergeRenderContext(), and Other.
Member Function Documentation
AllocateBatchResources()
void UE::Landscape::EditLayers::FMergeRenderContext::AllocateBatchResources (const FMergeRenderBatch & InRenderBatch) private
Allocate all needed render targets for this batch.
AllocateResources()
void UE::Landscape::EditLayers::FMergeRenderContext::AllocateResources () private
Allocate all needed render targets for this merge.
FreeBatchResources()
void UE::Landscape::EditLayers::FMergeRenderContext::FreeBatchResources (const FMergeRenderBatch & InRenderBatch) private
Free all render targets used in this batch.
FreeResources()
void UE::Landscape::EditLayers::FMergeRenderContext::FreeResources () private
Free all render targets used in this merge.
GetFinalTargetLayerBitIndices()
const TBitArray & UE::Landscape::EditLayers::FMergeRenderContext::GetFinalTargetLayerBitIndices () const inline
Definition at line 398 of file LandscapeEditLayerMergeRenderContext.h.
References FinalTargetLayerBitIndices.
IsValid()
bool UE::Landscape::EditLayers::FMergeRenderContext::IsValid () const
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and RDGBuilderRecorder.
operator=() [1/2]
FMergeRenderContext & UE::Landscape::EditLayers::FMergeRenderContext::operator= (const FMergeRenderContext & Other) default
References FMergeRenderContext(), and Other.
operator=() [2/2]
FMergeRenderContext & UE::Landscape::EditLayers::FMergeRenderContext::operator= (FMergeRenderContext && Other) default
References FMergeRenderContext(), and Other.
Render()
void UE::Landscape::EditLayers::FMergeRenderContext::Render (TFunction< void(const FOnRenderBatchTargetGroupDoneParams &, UE::Landscape::FRDGBuilderRecorder &)> OnRenderBatchTargetGroupDone)
References UE::Landscape::EditLayers::FMergeContext::const, UE::Landscape::EditLayers::FMergeContext::Landscape, and Render().
Referenced by Render().
RenderExpandedRenderTarget()
void UE::Landscape::EditLayers::FMergeRenderContext::RenderExpandedRenderTarget (UE::Landscape::FRDGBuilderRecorder & RDGBuilderRecorder)
Duplicates the vertex data from the (sub-)sections of the batch, assuming GetBlendRenderTargetRead() is the RT that is read from and GetBlendRenderTargetWrite() the one that is written to.
Parameters
RDGBuilderRecorder recorder to append operations to a single FRDGBuilder, if the the recorder in "recording" mode. In "immediate" mode, a render command will be enqueued immediately
References RDGBuilderRecorder.
RenderValidityRenderTargets()
void UE::Landscape::EditLayers::FMergeRenderContext::RenderValidityRenderTargets (UE::Landscape::FRDGBuilderRecorder & RDGBuilderRecorder)
Render the stencil render targets for each target layer in this merge for this batch.
Parameters
RDGBuilderRecorder recorder to append operations to a single FRDGBuilder, if the the recorder in "recording" mode. In "immediate" mode, a render command will be enqueued immediately
References RDGBuilderRecorder.
UE_EXPERIMENTAL() [1/18]
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>> UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
true if there is at least one blackboard item of type T in the context's list
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [2/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const & inline
Returns
all blackboard items currently stored in the context
Definition at line 450 of file LandscapeEditLayerMergeRenderContext.h.
References BlackboardItems, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [3/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const & inline
Definition at line 355 of file LandscapeEditLayerMergeRenderContext.h.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and RenderBatches.
UE_EXPERIMENTAL() [4/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Definition at line 353 of file LandscapeEditLayerMergeRenderContext.h.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and MaxNeededResolution.
UE_EXPERIMENTAL() [5/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [6/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [7/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [8/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [9/18]
UE_EXPERIMENTAL(5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void CycleBlendRenderTargets(UE UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Cycle between the 3 render targets used for blending: Write becomes Read -> Read becomes ReadPrevious -> ReadPrevious becomes Write The new Write RT will be transitioned to state == InDesiredWriteAccess (if != ERHIAccess::None) The new Read RT will be transitioned to state ERHIAccess::SRVMask The new ReadPrevious RT will stay in state ERHIAccess::SRVMask.
Parameters
InDesiredWriteAccess RHI state of the write RT after the operation (if InDesiredWriteAccess != ERHIAccess::None)
RDGBuilderRecorder recorder to append operations to a single FRDGBuilder, if the the recorder in "recording" mode. In "immediate" mode, a render command will be enqueued immediately
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [10/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [11/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Performs a generic blend assuming GetBlendRenderTargetWrite() is the RT that contains the layer to blend and GetBlendRenderTargetRead() the one that contains the result of the merge up until this layer.
It will cycle the RTs such as after this call, GetBlendRenderTargetWrite() will contain the merge result
Parameters
InBlendParams defines how heightmaps/weightmaps should be blended. In the case of weightmaps, there must be as may entries in WeightmapBlendParams as there are layers in the target layers group
RDGBuilderRecorder recorder to append operations to a single FRDGBuilder, if the the recorder in "recording" mode. In "immediate" mode, a render command will be enqueued immediately
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [12/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [13/18]
UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [14/18]
template<typename T, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>> UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") &&
Create a new blackboard item of type T and adds it to the context's list.
Returns
the newly-created blackboard item
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [15/18]
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>> UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") &
Returns
the first blackboard item of type T from the context's list. Asserts if there isn't one
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [16/18]
template<typename T, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>> UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") &&
Returns
the first blackboard item of type T from the context's list or create a new one if there isn't one
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [17/18]
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>> UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Returns
the first blackboard item of type T from the context's list or nullptr if there isn't one
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [18/18]
template<typename T, typename = std::enable_if_t<std::is_base_of_v<FLandscapeEditLayerMergeRenderBlackboardItem, std::decay_t<T>>>> UE::Landscape::EditLayers::FMergeRenderContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Returns
all blackboard items of type T from the context's list
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
Friends And Related Symbol Documentation
::ALandscape
friend class ::ALandscape friend
Definition at line 287 of file LandscapeEditLayerMergeRenderContext.h.
Field Documentation
BlackboardItems
TArray<TInstancedStruct<FLandscapeEditLayerMergeRenderBlackboardItem> > UE::Landscape::EditLayers::FMergeRenderContext::BlackboardItems private
Generic data struct to store some data to pass around throughout the context's lifetime.
Basically, this is a mini-RTTI system that e.g. allows to store/pass around specific data between renderers in a generic way
Definition at line 506 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by UE_EXPERIMENTAL().
BlendRenderTargets
TStaticArray<ULandscapeScratchRenderTarget*, NumBlendRenderTargets> UE::Landscape::EditLayers::FMergeRenderContext::BlendRenderTargets private
Render targets that are used throughout the blending operations (they could be texture arrays in the case of multiple weightmaps)
Definition at line 469 of file LandscapeEditLayerMergeRenderContext.h.
ComponentToTargetLayerBitIndices
TMap<ULandscapeComponent*, TBitArray<> > UE::Landscape::EditLayers::FMergeRenderContext::ComponentToTargetLayerBitIndices private
List of components involved in this merge and the target layers they're writing to (each bit corresponds to the target layer name in AllTargetLayerNames)
Definition at line 500 of file LandscapeEditLayerMergeRenderContext.h.
CurrentBlendRenderTargetWriteIndex
int32 UE::Landscape::EditLayers::FMergeRenderContext::CurrentBlendRenderTargetWriteIndex = -1 private
Definition at line 470 of file LandscapeEditLayerMergeRenderContext.h.
CurrentRenderBatchIndex
int32 UE::Landscape::EditLayers::FMergeRenderContext::CurrentRenderBatchIndex = INDEX_NONE private
Current batch being rendered.
Definition at line 491 of file LandscapeEditLayerMergeRenderContext.h.
CurrentVisualLogOffset
FVector UE::Landscape::EditLayers::FMergeRenderContext::CurrentVisualLogOffset = FVector(ForceInitToZero) private
Offset for visual debugging.
Definition at line 494 of file LandscapeEditLayerMergeRenderContext.h.
FinalTargetLayerBitIndices
TBitArray UE::Landscape::EditLayers::FMergeRenderContext::FinalTargetLayerBitIndices private
Final list of target layer names being involved in this merge context.
If a target layer name is present here, it's because it's a valid target layer and it needs to be rendered because it has been requested or one of the target layers that have been requested needs it to be present (e.g. weight-blending). Each bit in that bit array corresponds to an entry in AllTargetLayerNames
Definition at line 474 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by GetFinalTargetLayerBitIndices().
MaxLocalHeight
double UE::Landscape::EditLayers::FMergeRenderContext::MaxLocalHeight = DBL_MIN private
Maximum height of all components to render in local space.
Definition at line 497 of file LandscapeEditLayerMergeRenderContext.h.
MaxNeededNumSlices
int32 UE::Landscape::EditLayers::FMergeRenderContext::MaxNeededNumSlices = 0 private
Maximum number of slices needed by a given batch / target layer group in this context (means we won't ever need more than this number of slices in a given render target texture array during the whole merge.
Definition at line 484 of file LandscapeEditLayerMergeRenderContext.h.
MaxNeededResolution
FIntPoint UE::Landscape::EditLayers::FMergeRenderContext::MaxNeededResolution = FIntPoint(ForceInit) private
Maximum resolution needed by a given batch in this context (means we won't ever need more than this size of a render target during the whole merge.
Definition at line 481 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by UE_EXPERIMENTAL().
NumBlendRenderTargets
int32 UE::Landscape::EditLayers::FMergeRenderContext::NumBlendRenderTargets = 3 static constexpr private
Definition at line 466 of file LandscapeEditLayerMergeRenderContext.h.
PerTargetLayerValidityRenderTargets
TMap<FName, ULandscapeScratchRenderTarget*> UE::Landscape::EditLayers::FMergeRenderContext::PerTargetLayerValidityRenderTargets private
Render targets storing the validity of each pixel wrt the target layer (i.e.
stencil-like buffer, but stored as a RT to let users access it as a standard texture) : Useful when sampling neighbors to know whether the data there corresponds to a valid neighbor.
Definition at line 478 of file LandscapeEditLayerMergeRenderContext.h.
RDGBuilderRecorder
FRenderParams UE::Landscape::FRDGBuilderRecorder& UE::Landscape::EditLayers::FMergeRenderContext::RDGBuilderRecorder
Definition at line 396 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by IsValid(), RenderExpandedRenderTarget(), and RenderValidityRenderTargets().
RenderBatches
TArray<FMergeRenderBatch> UE::Landscape::EditLayers::FMergeRenderContext::RenderBatches private
Successive batches of components being processed by this context.
Each batch should be self-contained so that we won't ever need to keep more than one in memory (VRAM) in order to compute the info we need (heightmap/weightmaps), i.e. nothing should ever depend on 2 different batches.
Definition at line 488 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by UE_EXPERIMENTAL().
RenderParams
FRenderParams& UE::Landscape::EditLayers::FMergeRenderContext::RenderParams
Definition at line 396 of file LandscapeEditLayerMergeRenderContext.h.
TargetLayersToComponents
TArray<TSet<ULandscapeComponent*> > UE::Landscape::EditLayers::FMergeRenderContext::TargetLayersToComponents private
Reverse lookup of ComponentToTargetLayerBitIndices : one entry per element in ComponentToTargetLayerBitIndices, each entry containing all of the components involved in this merge for this target layer.
Definition at line 503 of file LandscapeEditLayerMergeRenderContext.h.
The documentation for this class was generated from the following file:
LandscapeEditLayerMergeRenderContext.h