Unreal Engine 5.6 C++ API: FObjectPtr Struct Reference
FObjectPtr Struct Reference
FObjectPtr is the basic, minimally typed version of TObjectPtr.
#include "ObjectPtr.h"
Public Member Functions
FObjectPtr ()
FObjectPtr (const FObjectPtr &InOther)
FObjectPtr (ENoInit)
FObjectPtr (FObjectPtr &&InOther)
FORCEINLINE FObjectPtr (FRemoteObjectId ObjectId)
FORCEINLINE FObjectPtr (TYPE_OF_NULLPTR)
FORCEINLINE FObjectPtr (UObject *Object)
FORCEINLINE FObjectPtr (void *IncompleteObject)
FORCEINLINE UObject * Get () const
FORCEINLINE UClass * GetClass () const
FName GetFName () const
FString GetFullName (EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost.
FORCEINLINE FObjectHandle GetHandle () const
FORCEINLINE FObjectHandle & GetHandleRef () const
FString GetName () const
FObjectPtr GetOuter () const
FObjectPtr GetPackage () const
FString GetPath () const
FString GetPathName () const
FORCEINLINE FRemoteObjectId GetRemoteId () const
template<typename T>
FORCEINLINE bool IsA () const
bool IsA (const UClass *SomeBase) const
bool IsIn (FObjectPtr SomeOuter) const
FORCEINLINE bool IsRemote () const
FObjectPtr::IsRemote is only used when UE_WITH_REMOTE_OBJECT_HANDLE is true, and is mutually exclusive with other uses of unresolved FObjectPtr.
FORCEINLINE bool IsResolved () const
FORCEINLINE operator bool () const
FORCEINLINE bool operator! () const
FORCEINLINE bool operator!= (FObjectPtr Other) const
FORCEINLINE UObject & operator* () const
FORCEINLINE UObject * operator-> () const
FObjectPtr & operator= (const FObjectPtr &InOther)
FObjectPtr & operator= (FObjectPtr &&InOther)
FObjectPtr & operator= (TYPE_OF_NULLPTR)
FObjectPtr & operator= (UObject *Other)
FObjectPtr & operator= (void *IncompleteOther)
FORCEINLINE bool operator== (FObjectPtr Other) const
FORCEINLINE TObjectPtr< UObject > & ToTObjectPtr ()
FORCEINLINE const TObjectPtr< UObject > & ToTObjectPtr () const
Private Member Functions
FORCEINLINE void ConditionallyMarkAsReachable (const FObjectPtr &InPtr) const
FORCEINLINE void ConditionallyMarkAsReachable (const UObject *InObj) const
Private Attributes
union {
UObject * DebugPtr
FObjectHandle Handle
};
Friends
FORCEINLINE uint32 GetTypeHash (const FObjectPtr &Object)
Detailed Description
FObjectPtr is the basic, minimally typed version of TObjectPtr.
Definition at line 62 of file ObjectPtr.h.
Constructor & Destructor Documentation
FObjectPtr() [1/8]
FObjectPtr::FObjectPtr () inline nodiscard
Definition at line 65 of file ObjectPtr.h.
References CoreUObject, Handle, and Private.
Referenced by FObjectPtr(), FObjectPtr(), ConditionallyMarkAsReachable(), GetOuter(), GetPackage(), GetTypeHash, IsIn(), operator!=(), operator=(), operator=(), operator=(), operator=(), operator=(), and operator==().
FObjectPtr() [2/8]
FObjectPtr::FObjectPtr (ENoInit) inline explicit nodiscard
Definition at line 70 of file ObjectPtr.h.
FObjectPtr() [3/8]
FORCEINLINE FObjectPtr::FObjectPtr (TYPE_OF_NULLPTR) inline nodiscard
Definition at line 74 of file ObjectPtr.h.
References CoreUObject, FORCEINLINE, Handle, and Private.
FObjectPtr() [4/8]
FORCEINLINE FObjectPtr::FObjectPtr (UObject * Object) inline explicit nodiscard
Definition at line 79 of file ObjectPtr.h.
References ConditionallyMarkAsReachable(), CoreUObject, FORCEINLINE, Handle, Object, and Private.
FObjectPtr() [5/8]
FORCEINLINE FObjectPtr::FObjectPtr (void * IncompleteObject) inline explicit nodiscard
Definition at line 88 of file ObjectPtr.h.
References CoreUObject, FORCEINLINE, Handle, and Private.
FObjectPtr() [6/8]
FORCEINLINE FObjectPtr::FObjectPtr (FRemoteObjectId ObjectId) inline explicit nodiscard
Definition at line 103 of file ObjectPtr.h.
References FORCEINLINE, and ObjectId.
FObjectPtr() [7/8]
FObjectPtr::FObjectPtr (FObjectPtr && InOther) inline nodiscard
Definition at line 124 of file ObjectPtr.h.
References FObjectPtr(), ConditionallyMarkAsReachable(), Handle, and MoveTemp().
FObjectPtr() [8/8]
FObjectPtr::FObjectPtr (const FObjectPtr & InOther) inline nodiscard
Definition at line 130 of file ObjectPtr.h.
References FObjectPtr(), ConditionallyMarkAsReachable(), and Handle.
Member Function Documentation
ConditionallyMarkAsReachable() [1/2]
FORCEINLINE void FObjectPtr::ConditionallyMarkAsReachable (const FObjectPtr & InPtr) const inline private
Definition at line 312 of file ObjectPtr.h.
References FObjectPtr(), FORCEINLINE, GetHandleRef(), UE::GC::GIsIncrementalReachabilityPending, IsResolved(), UE::GC::MarkAsReachable(), and UE::CoreUObject::Private::ReadObjectHandlePointerNoCheck().
Referenced by FObjectPtr(), FObjectPtr(), FObjectPtr(), operator=(), operator=(), and operator=().
ConditionallyMarkAsReachable() [2/2]
FORCEINLINE void FObjectPtr::ConditionallyMarkAsReachable (const UObject * InObj) const inline private
Definition at line 322 of file ObjectPtr.h.
References FORCEINLINE, UE::GC::GIsIncrementalReachabilityPending, and UE::GC::MarkAsReachable().
Get()
FORCEINLINE UObject * FObjectPtr::Get () const inline nodiscard
Definition at line 112 of file ObjectPtr.h.
References FORCEINLINE, Handle, and UE::CoreUObject::Private::ResolveObjectHandle().
Referenced by FSoftObjectPath::FSoftObjectPath(), Cast(), ObjectPtr_Private::Get(), GetFName(), GetFullName(), GetOuter(), GetPackage(), GetPathName(), IsIn(), operator*(), and operator->().
GetClass()
FORCEINLINE UClass * FObjectPtr::GetClass () const inline nodiscard
Definition at line 117 of file ObjectPtr.h.
References FORCEINLINE, Handle, and UE::CoreUObject::Private::ResolveObjectHandleClass().
Referenced by Cast(), and FArchiveReplaceObjectRefBase::ShouldSkipReplacementCheckForObjectPtr().
GetFName()
FName FObjectPtr::GetFName () const inline nodiscard
Definition at line 235 of file ObjectPtr.h.
References Get(), and UE::CoreUObject::Private::GetFName().
Referenced by GetName().
GetFullName()
FString FObjectPtr::GetFullName (EObjectFullNameFlags Flags = EObjectFullNameFlags::None) const inline nodiscard
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost.
[Outer:]Name'.
Definition at line 270 of file ObjectPtr.h.
References Flags, Get(), UE::CoreUObject::Private::GetFullName(), and None.
GetHandle()
FORCEINLINE FObjectHandle FObjectPtr::GetHandle () const inline nodiscard
Definition at line 277 of file ObjectPtr.h.
References FORCEINLINE, and Handle.
Referenced by GetRemoteId().
GetHandleRef()
FORCEINLINE FObjectHandle & FObjectPtr::GetHandleRef () const inline nodiscard
Definition at line 278 of file ObjectPtr.h.
References FORCEINLINE, and Handle.
Referenced by Cast(), ConditionallyMarkAsReachable(), ObjectPtr_Private::Friend::NoAccessTrackingGet(), ObjectPtr_Private::Friend::NoAccessTrackingGetNoResolve(), TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRangeContiguous(), and TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRangeContiguous().
GetName()
FString FObjectPtr::GetName () const inline nodiscard
Definition at line 241 of file ObjectPtr.h.
References GetFName(), and FName::ToString().
GetOuter()
FObjectPtr FObjectPtr::GetOuter () const inline nodiscard
Definition at line 246 of file ObjectPtr.h.
References FObjectPtr(), Get(), and UE::CoreUObject::Private::GetOuter().
GetPackage()
FObjectPtr FObjectPtr::GetPackage () const inline nodiscard
Definition at line 252 of file ObjectPtr.h.
References FObjectPtr(), Get(), and UE::CoreUObject::Private::GetPackage().
GetPath()
FString FObjectPtr::GetPath () const inline nodiscard
Definition at line 202 of file ObjectPtr.h.
References GetPathName().
GetPathName()
FString FObjectPtr::GetPathName () const inline nodiscard
Definition at line 229 of file ObjectPtr.h.
References Get(), UE::CoreUObject::Private::GetPathName(), and TEXT.
Referenced by FSoftObjectPath::FSoftObjectPath(), and GetPath().
GetRemoteId()
FORCEINLINE FRemoteObjectId FObjectPtr::GetRemoteId () const inline nodiscard
Definition at line 288 of file ObjectPtr.h.
References FORCEINLINE, and GetHandle().
IsA() [1/2]
template<typename T> FORCEINLINE bool FObjectPtr::IsA () const inline nodiscard
Definition at line 283 of file ObjectPtr.h.
References FORCEINLINE, and IsA().
Referenced by IsA().
IsA() [2/2]
bool FObjectPtr::IsA (const UClass * SomeBase) const nodiscard
Referenced by Cast(), and FArchiveReplaceObjectRefBase::ShouldSkipReplacementCheckForObjectPtr().
IsIn()
bool FObjectPtr::IsIn (FObjectPtr SomeOuter) const inline nodiscard
Definition at line 258 of file ObjectPtr.h.
References FObjectPtr(), Get(), and UE::CoreUObject::Private::IsIn().
IsRemote()
FORCEINLINE bool FObjectPtr::IsRemote () const inline nodiscard
FObjectPtr::IsRemote is only used when UE_WITH_REMOTE_OBJECT_HANDLE is true, and is mutually exclusive with other uses of unresolved FObjectPtr.
When using UE_WITH_REMOTE_OBJECT_HANDLE, unresolved FObjectPtrs mean the object is not locally available and is present on another server, see @RemoteObject.h
Definition at line 198 of file ObjectPtr.h.
References FORCEINLINE, and IsResolved().
IsResolved()
FORCEINLINE bool FObjectPtr::IsResolved () const inline nodiscard
Definition at line 192 of file ObjectPtr.h.
References FORCEINLINE, Handle, and IsObjectHandleResolved().
Referenced by FSoftObjectPath::FSoftObjectPath(), ConditionallyMarkAsReachable(), IsRemote(), TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRangeContiguous(), TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRangeContiguous(), and FArchiveReplaceObjectRefBase::ShouldSkipReplacementCheckForObjectPtr().
operator bool()
FORCEINLINE FObjectPtr::operator bool () const inline explicit nodiscard
Definition at line 190 of file ObjectPtr.h.
References FORCEINLINE, Handle, and IsObjectHandleNull().
operator!()
FORCEINLINE bool FObjectPtr::operator! () const inline nodiscard
Definition at line 189 of file ObjectPtr.h.
References FORCEINLINE, Handle, and IsObjectHandleNull().
operator!=()
FORCEINLINE bool FObjectPtr::operator!= (FObjectPtr Other) const inline nodiscard
Definition at line 179 of file ObjectPtr.h.
References FObjectPtr(), FORCEINLINE, Handle, and Other.
operator*()
FORCEINLINE UObject & FObjectPtr::operator* () const inline nodiscard
Definition at line 187 of file ObjectPtr.h.
References FORCEINLINE, and Get().
operator->()
FORCEINLINE UObject * FObjectPtr::operator-> () const inline nodiscard
Definition at line 186 of file ObjectPtr.h.
References FORCEINLINE, and Get().
operator=() [1/5]
FObjectPtr & FObjectPtr::operator= (const FObjectPtr & InOther) inline
Definition at line 143 of file ObjectPtr.h.
References FObjectPtr(), ConditionallyMarkAsReachable(), and Handle.
operator=() [2/5]
FObjectPtr & FObjectPtr::operator= (FObjectPtr && InOther) inline
Definition at line 136 of file ObjectPtr.h.
References FObjectPtr(), ConditionallyMarkAsReachable(), Handle, and MoveTemp().
operator=() [3/5]
FObjectPtr & FObjectPtr::operator= (TYPE_OF_NULLPTR) inline
Definition at line 172 of file ObjectPtr.h.
References FObjectPtr(), Handle, and UE::CoreUObject::Private::MakeObjectHandle().
operator=() [4/5]
FObjectPtr & FObjectPtr::operator= (UObject * Other) inline
Definition at line 156 of file ObjectPtr.h.
References FObjectPtr(), ConditionallyMarkAsReachable(), Handle, UE::CoreUObject::Private::MakeObjectHandle(), and Other.
operator=() [5/5]
FObjectPtr & FObjectPtr::operator= (void * IncompleteOther) inline
Definition at line 166 of file ObjectPtr.h.
References FObjectPtr(), Handle, and UE::CoreUObject::Private::MakeObjectHandle().
operator==()
FORCEINLINE bool FObjectPtr::operator== (FObjectPtr Other) const inline nodiscard
Definition at line 178 of file ObjectPtr.h.
References FObjectPtr(), FORCEINLINE, Handle, and Other.
ToTObjectPtr() [1/2]
FORCEINLINE TObjectPtr< UObject > & FObjectPtr::ToTObjectPtr () nodiscard
Definition at line 1241 of file ObjectPtr.h.
References FORCEINLINE.
ToTObjectPtr() [2/2]
FORCEINLINE const TObjectPtr< UObject > & FObjectPtr::ToTObjectPtr () const nodiscard
Definition at line 1246 of file ObjectPtr.h.
References FORCEINLINE.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FObjectPtr & Object) friend
Definition at line 298 of file ObjectPtr.h.
References FObjectPtr(), FORCEINLINE, GetTypeHash, and Object.
Referenced by GetTypeHash.
Field Documentation
[union]
union { ... } FObjectPtr
DebugPtr
UObject* FObjectPtr::DebugPtr
Definition at line 308 of file ObjectPtr.h.
Handle
FObjectHandle FObjectPtr::Handle mutable
Definition at line 305 of file ObjectPtr.h.
Referenced by FObjectPtr(), FObjectPtr(), FObjectPtr(), FObjectPtr(), FObjectPtr(), FObjectPtr(), Get(), GetClass(), GetHandle(), GetHandleRef(), IsResolved(), operator bool(), operator!(), operator!=(), operator=(), operator=(), operator=(), operator=(), operator=(), and operator==().
The documentation for this struct was generated from the following file:
ObjectPtr.h