Unreal Engine 5.6 C++ API: GameplayTagContainer.h File Reference
GameplayTagContainer.h File Reference
#include "Stats/Stats.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "Misc/ComparisonUtility.h"
#include "GameplayTagContainer.generated.h"
Data Structures
struct FGameplayTagNativeAdder
Class that can be subclassed by a game/plugin to allow easily adding native gameplay tags at startup.
struct FGameplayTagQueryExpression
struct TStructOpsTypeTraits< FGameplayTag >
struct TStructOpsTypeTraits< FGameplayTagContainer >
struct TStructOpsTypeTraits< FGameplayTagQuery >
Namespaces
namespace EGameplayTagQueryStreamVersion
Enumerates the list of supported query expression types.
Macros
#define INVALID_TAGNETINDEX MAX_uint16
Enumerations
enum EGameplayTagQueryStreamVersion::Type { EGameplayTagQueryStreamVersion::InitialVersion = 0 , EGameplayTagQueryStreamVersion::VersionPlusOne , EGameplayTagQueryStreamVersion::LatestVersion = VersionPlusOne - 1 }
Functions
DECLARE_CYCLE_STAT_EXTERN (TEXT("FGameplayTagContainer::DoesTagContainerMatch"), STAT_FGameplayTagContainer_DoesTagContainerMatch, STATGROUP_GameplayTags, GAMEPLAYTAGS_API)
GAMEPLAYTAGS_API DECLARE_LOG_CATEGORY_EXTERN (LogGameplayTags, Log, All)
DECLARE_STATS_GROUP (TEXT("Gameplay Tags"), STATGROUP_GameplayTags, STATCAT_Advanced)
namespace UE_DEPRECATED (5.0, "Deprecated in favor of HasExact and related functions") EGameplayTagMatchType
USTRUCT ()) struct FGameplayTag
A single gameplay tag, which represents a hierarchical name of the form x.y that is registered in the GameplayTagsManager You can filter the gameplay tags displayed in the editor using, meta = (Categories = "Tag1.Tag2.Tag3"))
Variables
UENUM() enum class EGameplayContainerMatchType typedef uint16 FGameplayTagNetIndex
Macro Definition Documentation
INVALID_TAGNETINDEX
#define INVALID_TAGNETINDEX MAX_uint16
Definition at line 46 of file GameplayTagContainer.h.
Function Documentation
DECLARE_CYCLE_STAT_EXTERN()
DECLARE_CYCLE_STAT_EXTERN (TEXT("FGameplayTagContainer::DoesTagContainerMatch") , STAT_FGameplayTagContainer_DoesTagContainerMatch , STATGROUP_GameplayTags , GAMEPLAYTAGS_API)
References Explicit, and UE_DEPRECATED.
DECLARE_LOG_CATEGORY_EXTERN()
GAMEPLAYTAGS_API DECLARE_LOG_CATEGORY_EXTERN (LogGameplayTags , Log , All)
References All, and Log.
DECLARE_STATS_GROUP()
DECLARE_STATS_GROUP (TEXT("Gameplay Tags") , STATGROUP_GameplayTags , STATCAT_Advanced)
UE_DEPRECATED()
namespace UE_DEPRECATED (5. 0, "Deprecated in favor of HasExact and related functions")
Definition at line 24 of file GameplayTagContainer.h.
USTRUCT()
USTRUCT ()
A single gameplay tag, which represents a hierarchical name of the form x.y that is registered in the GameplayTagsManager You can filter the gameplay tags displayed in the editor using, meta = (Categories = "Tag1.Tag2.Tag3"))
An FGameplayTagQuery is a logical query that can be run against an FGameplayTagContainer.
Helper struct: drop this in another struct to get an embedded create new tag widget.
A Tag Container holds a collection of FGameplayTags, tags are included explicitly by adding them, and implicitly from adding child tags.
A query that succeeds is said to "match". Queries are logical expressions that can test the intersection properties of another tag container (all, any, or none), or the matching state of a set of sub-expressions (all, any, or none). This allows queries to be arbitrarily recursive and very expressive. For instance, if you wanted to test if a given tag container contained tags ((A && B) || (C)) && (!D), you would construct your query in the form ALL(ANY(ALL(A,B), ALL(C)), NONE(D))
You can expose the query structs to Blueprints and edit them with a custom editor, or you can construct them natively in code.
Example of how to build a query via code: FGameplayTagQuery Q; Q.BuildQuery(FGameplayTagQueryExpression() .AllTagsMatch() .AddTag(FGameplayTag::RequestGameplayTag(FName(TEXT("Animal.Mammal.Dog.Corgi")))) .AddTag(FGameplayTag::RequestGameplayTag(FName(TEXT("Plant.Tree.Spruce")))));
Queries are internally represented as a byte stream that is memory-efficient and can be evaluated quickly at runtime. Note: these have an extensive details and graph pin customization for editing, so there is no need to expose the internals to Blueprints.
Constructors
Gets the FGameplayTag that corresponds to the TagName
Parameters
TagName The Name of the tag to search for
ErrorIfNotfound ensure() that tag exists.
Returns
Will return the corresponding FGameplayTag or an empty one if not found.
Returns true if this is a valid gameplay tag string (foo.bar.baz). If false, it will fill
Parameters
TagString String to check for validity
OutError If non-null and string invalid, will fill in with an error message
OutFixedString If non-null and string invalid, will attempt to fix. Will be empty if no fix is possible
Returns
True if this can be added to the tag dictionary, false if there's a syntax error
Operators
Determine if this tag matches TagToCheck, expanding out parent tags "A.1".MatchesTag("A") will return True, "A".MatchesTag("A.1") will return False If TagToCheck is not Valid it will always return False
Returns
True if this tag matches TagToCheck
Determine if TagToCheck is valid and exactly matches this tag "A.1".MatchesTagExact("A") will return False If TagToCheck is not Valid it will always return False
Returns
True if TagToCheck is Valid and is exactly this tag
Check to see how closely two FGameplayTags match. Higher values indicate more matching terms in the tags.
Parameters
TagToCheck Tag to match against
Returns
The depth of the match, higher means they are closer to an exact match
Checks if this tag matches ANY of the tags in the specified container, also checks against our parent tags "A.1".MatchesAny({"A","B"}) will return True, "A".MatchesAny({"A.1","B"}) will return False If ContainerToCheck is empty/invalid it will always return False
Returns
True if this tag matches ANY of the tags of in ContainerToCheck
Checks if this tag matches ANY of the tags in the specified container, only allowing exact matches "A.1".MatchesAny({"A","B"}) will return False If ContainerToCheck is empty/invalid it will always return False
Returns
True if this tag matches ANY of the tags of in ContainerToCheck exactly
Returns whether the tag is valid or not; Invalid tags are set to NAME_None and do not exist in the game-specific global dictionary
Returns a GameplayTagContainer containing only this tag
Returns direct parent GameplayTag of this GameplayTag, calling on x.y will return x
Returns a new tag container that includes this tag and all parent tags as explicitly added tags. For example, calling this on x.y.z would return a tag container with x.y.z, x.y, and x
Parses the tag name and fills in UniqueParentTags with raw parent tags, without validating with the tag manager. For example, calling this on x.y.z would add x.y and x to UniqueParentTags if they were not already in the array
Parses the tag name and returns the name of the leaf. For example, calling this on x.y.z would return the z component.
Used so we can have a TMap of this struct
Displays gameplay tag as a string for blueprint graph usage
Get the tag represented as a name
Overridden for fast serialize
Handles fixup and errors. This is only called when not serializing a full FGameplayTagContainer
Used to upgrade a Name property to a GameplayTag struct property
Sets from a ImportText string, used in asset registry
Handles importing tag strings without (TagName=) in it
An empty Gameplay Tag
Intentionally private so only the tag manager can use
This Tags Name
Constructors
Explicit to prevent people from accidentally using the wrong type of operation
Creates a container from an array of tags, this is more efficient than adding them all individually
Assignment/Equality operators
Determine if TagToCheck is present in this container, also checking against parent tags {"A.1"}.HasTag("A") will return True, {"A"}.HasTag("A.1") will return False If TagToCheck is not Valid it will always return False
Returns
True if TagToCheck is in this container, false if it is not
Determine if TagToCheck is explicitly present in this container, only allowing exact matches {"A.1"}.HasTagExact("A") will return False If TagToCheck is not Valid it will always return False
Returns
True if TagToCheck is in this container, false if it is not
Checks if this container contains ANY of the tags in the specified container, also checks against parent tags {"A.1"}.HasAny({"A","B"}) will return True, {"A"}.HasAny({"A.1","B"}) will return False If ContainerToCheck is empty/invalid it will always return False
Returns
True if this container has ANY of the tags of in ContainerToCheck
Checks if this container contains ANY of the tags in the specified container, only allowing exact matches {"A.1"}.HasAny({"A","B"}) will return False If ContainerToCheck is empty/invalid it will always return False
Returns
True if this container has ANY of the tags of in ContainerToCheck
Checks if this container contains ALL of the tags in the specified container, also checks against parent tags {"A.1","B.1"}.HasAll({"A","B"}) will return True, {"A","B"}.HasAll({"A.1","B.1"}) will return False If ContainerToCheck is empty/invalid it will always return True, because there were no failed checks
Returns
True if this container has ALL of the tags of in ContainerToCheck, including if ContainerToCheck is empty
Checks if this container contains ALL of the tags in the specified container, only allowing exact matches {"A.1","B.1"}.HasAll({"A","B"}) will return False If ContainerToCheck is empty/invalid it will always return True, because there were no failed checks
Returns
True if this container has ALL of the tags of in ContainerToCheck, including if ContainerToCheck is empty
Returns the number of explicitly added tags
Returns whether the container has any valid tags
Returns true if container is empty
Returns a new container explicitly containing the tags of this container and all of their parent tags
Returns a filtered version of this container, returns all tags that match against any of the tags in OtherContainer, expanding parents
Parameters
OtherContainer The Container to filter against
Returns
A FGameplayTagContainer containing the filtered tags
Returns a filtered version of this container, returns all tags that match exactly one in OtherContainer
Parameters
OtherContainer The Container to filter against
Returns
A FGameplayTagContainer containing the filtered tags
Checks if this container matches the given query.
Parameters
Query Query we are checking against
Returns
True if this container matches the query, false otherwise.
Adds all the tags from one container to this container NOTE: From set theory, this effectively is the union of the container this is called on with Other.
Parameters
Other TagContainer that has the tags you want to add to this container
Adds all the tags that match between the two specified containers to this container. WARNING: This matches any parent tag in A, not just exact matches! So while this should be the union of the container this is called on with the intersection of OtherA and OtherB, it's not exactly that. Since OtherB matches against its parents, any tag in OtherA which has a parent match with a parent of OtherB will count. For example, if OtherA has Color.Green and OtherB has Color.Red, that will count as a match due to the Color parent match! If you want an exact match, you need to call A.FilterExact(B) (above) to get the intersection of A with B. If you need the disjunctive union (the union of two sets minus their intersection), use AppendTags to create Union, FilterExact to create Intersection, and then call Union.RemoveTags(Intersection).
Parameters
OtherA TagContainer that has the matching tags you want to add to this container, these tags have their parents expanded
OtherB TagContainer used to check for matching tags. If the tag matches on any parent, it counts as a match.
Add the specified tag to the container
Parameters
TagToAdd Tag to add to the container
Add the specified tag to the container without checking for uniqueness
Parameters
TagToAdd Tag to add to the container
Useful when building container from another data struct (TMap for example)
Adds a tag to the container and removes any direct parents, wont add if child already exists
Parameters
Tag The tag to try and add to this container
Returns
True if tag was added
Tag to remove from the container
Parameters
TagToRemove Tag to remove from the container
bDeferParentTags Skip calling FillParentTags for performance (must be handled by calling code)
Removes all tags in TagsToRemove from this container
Parameters
TagsToRemove Tags to remove from the container
Remove all tags from the container. Will maintain slack by default
Serialize the tag container
Efficient network serialize, takes advantage of the dictionary
Handles fixup after importing from text
Fill in the ParentTags array and any other transient parameters
Returns string version of container in ImportText format
Sets from a ImportText string, used in asset registry
Returns abbreviated human readable Tag list without parens or property names. If bQuoted is true it will quote each tag
Returns abbreviated human readable Tag list without parens or property names, but will limit each string to specified len. This is to get around output restrictions
Returns human readable description of what match is being looked for on the readable tag list.
Gets the explicit list of gameplay tags
Gets the explicit list of gameplay tags
Creates a const iterator for the contents of this array
Fills in ParentTags from GameplayTags
An empty Gameplay Tag Container
If a Tag with the specified tag name explicitly exists, it will remove that tag and return true. Otherwise, it returns false. It does NOT check the TagName for validity (i.e. the tag could be obsolete and so not exist in the table). It also does NOT check parents (because it cannot do so for a tag that isn't in the table). NOTE: This function should ONLY ever be used by GameplayTagsManager when redirecting tags. Do NOT make this function public!
Array of gameplay tags
Array of expanded parent tags, in addition to GameplayTags. Used to accelerate parent searches. May contain duplicates in some cases
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Assignment/Equality operators
Versioning for future token stream protocol changes. See EGameplayTagQueryStreamVersion.
List of tags referenced by this entire query. Token stream stored indices into this list.
Stream representation of the actual hierarchical query
User-provided string describing the query
Auto-generated string describing the query
Returns a gameplay tag from the tag dictionary
Replaces existing tags with passed in tags. Does not modify the tag query expression logic. Useful when you need to cache off and update often used query. Must use same sized tag container!
Replaces existing tags with passed in tag. Does not modify the tag query expression logic. Useful when you need to cache off and update often used query.
Returns true if the given tags match this query, or false otherwise.
Returns true if this query is empty, false otherwise.
Resets this query to its default empty state.
Creates this query with the given root expression.
Static function to assemble and return a query.
Builds a FGameplayTagQueryExpression from this query.
Serialize the tag query
Sets the user-specified description of this query.
Returns description string.
Gets the explicit list of all unique gameplay tags referenced by the query.
Gets the explicit list of all unique gameplay tags referenced by the query.
Creates this query based on the given EditableQuery object
Creates editable query object tree based on this query
Shortcuts for easily creating common query types
Todo
: add more as dictated by use cases
Creates a tag query that will match if there are any common tags between the given tags and the tags being queries against.
Definition at line 52 of file GameplayTagContainer.h.
References Ar, BlueprintType, Buffer, Category, UE::ComparisonUtility::CompareWithNumericSuffix(), ErrorIfNotFound, FORCEINLINE, GameplayTags, GENERATED_USTRUCT_BODY, GetTypeHash(), HasNativeBreak, HasNativeMake, IsValid(), Map, meta, operator!=(), operator<(), operator<<(), operator==(), Other, Parent, FName::ToString(), ToString(), and UPROPERTY.
Variable Documentation
FGameplayTagNetIndex
UENUM () enum class EGameplayContainerMatchType typedef uint16 FGameplayTagNetIndex ()
Definition at line 45 of file GameplayTagContainer.h.
Referenced by USTRUCT().