Unreal Engine 5.6 C++ API: UE::Logging::Private Namespace Reference
UE::Logging::Private Namespace Reference
Data Structures
class FInlineLogTemplateStorage
Store a log template in an inline byte array.
struct FLogContext
struct FLogField
struct FLogFieldCreator
Create log fields from values optionally preceded by names.
class FMemoryLogTemplateStorage
Store a log template in a detachable allocation from FMemory.
struct FStaticBasicLogDynamicData
Data about a static basic log that is created on-demand.
struct FStaticBasicLogRecord
Data about a static basic log that is constant for every occurrence.
struct FStaticLocalizedLogRecord
Data about a static localized log that is constant for every occurrence.
struct FStaticLogDynamicData
Data about a static log that is created on-demand.
struct FStaticLogRecord
Data about a static log that is constant for every occurrence.
class FUniqueLogTemplateStorage
Store a log template in a movable heap-allocated byte array.
struct TLogFieldName
Wrapper to identify field names interleaved with field values.
Functions
void BasicFatalLog (const FLogCategoryBase &Category, const FStaticBasicLogRecord *Log,...)
void BasicFatalLogWithProgramCounter (const FLogCategoryBase &Category, const FStaticBasicLogRecord *Log, void *ProgramCounter,...)
void BasicLog (const FLogCategoryBase &Category, const FStaticBasicLogRecord *Log,...)
template<typename NameType>
constexpr TLogFieldName< NameType > CheckFieldName (NameType &&Name)
Verify that the name is likely a string literal and forward it on.
void CreateLocalizedLogTemplate (const FText &Format, const FLogTemplateOptions &Options, const FLogField *Fields, int32 FieldCount, TFunctionRef< void *(int32)> Allocate)
void CreateLocalizedLogTemplate (const TCHAR *TextNamespace, const TCHAR *TextKey, const TCHAR *Format, const FLogTemplateOptions &Options, const FLogField *Fields, int32 FieldCount, TFunctionRef< void *(int32)> Allocate)
void CreateLogTemplate (const TCHAR *Format, const FLogTemplateOptions &Options, const FLogField *Fields, int32 FieldCount, TFunctionRef< void *(int32)> Allocate)
void DestroyLogTemplate (FLogTemplate *Template)
void FatalLogWithFieldArray (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log, const FLogField *Fields, int32 FieldCount)
void FatalLogWithFieldArray (const FLogCategoryBase &Category, const FStaticLogRecord &Log, const FLogField *Fields, int32 FieldCount)
template<typename LogType, typename... FieldArgTypes>
UE_COLD UE_DEBUG_SECTION void FatalLogWithFields (const FLogCategoryBase &Category, const LogType &Log, FieldArgTypes &&... FieldArgs)
Fatal log with fields created from the arguments, which may be values or pairs of name/value.
void FatalLogWithNoFields (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log)
void FatalLogWithNoFields (const FLogCategoryBase &Category, const FStaticLogRecord &Log)
void LogWithFieldArray (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log, const FLogField *Fields, int32 FieldCount)
void LogWithFieldArray (const FLogCategoryBase &Category, const FStaticLogRecord &Log, const FLogField *Fields, int32 FieldCount)
template<typename LogType, typename... FieldArgTypes>
UE_COLD UE_DEBUG_SECTION void LogWithFields (const FLogCategoryBase &Category, const LogType &Log, FieldArgTypes &&... FieldArgs)
Log with fields created from the arguments, which may be values or pairs of name/value.
void LogWithNoFields (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log)
void LogWithNoFields (const FLogCategoryBase &Category, const FStaticLogRecord &Log)
Function Documentation
BasicFatalLog()
void UE::Logging::Private::BasicFatalLog (const FLogCategoryBase & Category, const FStaticBasicLogRecord * Log, ...)
References Category, and Log.
BasicFatalLogWithProgramCounter()
void UE::Logging::Private::BasicFatalLogWithProgramCounter (const FLogCategoryBase & Category, const FStaticBasicLogRecord * Log, void * ProgramCounter, ...)
References Category, and Log.
BasicLog()
void UE::Logging::Private::BasicLog (const FLogCategoryBase & Category, const FStaticBasicLogRecord * Log, ...)
References Category, and Log.
CheckFieldName()
template<typename NameType> TLogFieldName< NameType > UE::Logging::Private::CheckFieldName (NameType && Name) inline constexpr
Verify that the name is likely a string literal and forward it on.
Definition at line 426 of file StructuredLog.h.
References Name, and TIsArrayOrRefOfType< T, ArrType >::Value.
CreateLocalizedLogTemplate() [1/2]
void UE::Logging::Private::CreateLocalizedLogTemplate (const FText & Format, const FLogTemplateOptions & Options, const FLogField * Fields, int32 FieldCount, TFunctionRef< void *(int32)> Allocate)
References Format, UE::Options, and UE_API.
CreateLocalizedLogTemplate() [2/2]
void UE::Logging::Private::CreateLocalizedLogTemplate (const TCHAR * TextNamespace, const TCHAR * TextKey, const TCHAR * Format, const FLogTemplateOptions & Options, const FLogField * Fields, int32 FieldCount, TFunctionRef< void *(int32)> Allocate)
References Format, UE::Options, and UE_API.
CreateLogTemplate()
void UE::Logging::Private::CreateLogTemplate (const TCHAR * Format, const FLogTemplateOptions & Options, const FLogField * Fields, int32 FieldCount, TFunctionRef< void *(int32)> Allocate)
References Format, UE::Options, and UE_API.
DestroyLogTemplate()
void UE::Logging::Private::DestroyLogTemplate (FLogTemplate * Template)
References UE_API.
Referenced by UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::~TLogTemplate().
FatalLogWithFieldArray() [1/2]
void UE::Logging::Private::FatalLogWithFieldArray (const FLogCategoryBase & Category, const FStaticLocalizedLogRecord & Log, const FLogField * Fields, int32 FieldCount)
References Category, Log, and UE_API.
FatalLogWithFieldArray() [2/2]
void UE::Logging::Private::FatalLogWithFieldArray (const FLogCategoryBase & Category, const FStaticLogRecord & Log, const FLogField * Fields, int32 FieldCount)
References Category, Log, and UE_API.
Referenced by FatalLogWithFields().
FatalLogWithFields()
template<typename LogType, typename... FieldArgTypes> UE_COLD UE_DEBUG_SECTION void UE::Logging::Private::FatalLogWithFields (const FLogCategoryBase & Category, const LogType & Log, FieldArgTypes &&... FieldArgs)
Fatal log with fields created from the arguments, which may be values or pairs of name/value.
Definition at line 483 of file StructuredLog.h.
References Category, UE::Logging::Private::FLogFieldCreator::Create(), FatalLogWithFieldArray(), FatalLogWithNoFields(), Log, UE_COLD, and UE_DEBUG_SECTION.
FatalLogWithNoFields() [1/2]
void UE::Logging::Private::FatalLogWithNoFields (const FLogCategoryBase & Category, const FStaticLocalizedLogRecord & Log)
References Category, Log, and UE_API.
FatalLogWithNoFields() [2/2]
void UE::Logging::Private::FatalLogWithNoFields (const FLogCategoryBase & Category, const FStaticLogRecord & Log)
References Category, Log, and UE_API.
Referenced by FatalLogWithFields().
LogWithFieldArray() [1/2]
void UE::Logging::Private::LogWithFieldArray (const FLogCategoryBase & Category, const FStaticLocalizedLogRecord & Log, const FLogField * Fields, int32 FieldCount)
References Category, Log, and UE_API.
LogWithFieldArray() [2/2]
void UE::Logging::Private::LogWithFieldArray (const FLogCategoryBase & Category, const FStaticLogRecord & Log, const FLogField * Fields, int32 FieldCount)
References Category, Log, and UE_API.
Referenced by LogWithFields().
LogWithFields()
template<typename LogType, typename... FieldArgTypes> UE_COLD UE_DEBUG_SECTION void UE::Logging::Private::LogWithFields (const FLogCategoryBase & Category, const LogType & Log, FieldArgTypes &&... FieldArgs)
Log with fields created from the arguments, which may be values or pairs of name/value.
Definition at line 465 of file StructuredLog.h.
References Category, UE::Logging::Private::FLogFieldCreator::Create(), Log, LogWithFieldArray(), LogWithNoFields(), UE_COLD, and UE_DEBUG_SECTION.
LogWithNoFields() [1/2]
void UE::Logging::Private::LogWithNoFields (const FLogCategoryBase & Category, const FStaticLocalizedLogRecord & Log)
References Category, Log, and UE_API.
LogWithNoFields() [2/2]
void UE::Logging::Private::LogWithNoFields (const FLogCategoryBase & Category, const FStaticLogRecord & Log)
References Category, Log, and UE_API.
Referenced by LogWithFields().