Unreal Engine 5.6 C++ API: FIoStoreTocResourceStorage Struct Reference
FIoStoreTocResourceStorage Struct Reference
#include "IoStore.h"
Data Structures
struct FIOStoreAllocationTag
struct FMappedFile
struct FReadBlocks
Public Member Functions
FIoStoreTocResourceStorage ()=default
FIoStoreTocResourceStorage (const TCHAR *TocFilePath)
template<typename T>
TArray< T > ChopArray (int32 Num)
template<typename T>
TConstArrayView< T > ChopView (int32 Num)
void FinalizeRead ()
uint64 GetAllocatedSize () const
bool IsLoaded () const
Private Types
using FDataAllocator = TConcurrentLinearArrayAllocator<FIOStoreAllocationTag>
using FLocalAllocator = TInlineAllocator<10>
Private Member Functions
TConstArrayView< uint8 > ChopBytes (FEmptyVariantState &, int32 Size)
TConstArrayView< uint8 > ChopBytes (int32 Size)
void ReleaseOwnershipOfLastBlock ()
Static Private Member Functions
static TConstArrayView< uint8 > ChopBytes (FMappedFile &File, int32 Size)
static TConstArrayView< uint8 > ChopBytes (FReadBlocks &File, int32 Size)
Private Attributes
TVariant< FEmptyVariantState, FMappedFile, FReadBlocks > Data
Detailed Description
Definition at line 179 of file IoStore.h.
Member Typedef Documentation
FDataAllocator
using FIoStoreTocResourceStorage::FDataAllocator = TConcurrentLinearArrayAllocator<FIOStoreAllocationTag> private
Definition at line 222 of file IoStore.h.
FLocalAllocator
using FIoStoreTocResourceStorage::FLocalAllocator = TInlineAllocator<10> private
Definition at line 223 of file IoStore.h.
Constructor & Destructor Documentation
FIoStoreTocResourceStorage() [1/2]
FIoStoreTocResourceStorage::FIoStoreTocResourceStorage () default
FIoStoreTocResourceStorage() [2/2]
FIoStoreTocResourceStorage::FIoStoreTocResourceStorage (const TCHAR * TocFilePath) explicit
Member Function Documentation
ChopArray()
template<typename T> TArray< T > FIoStoreTocResourceStorage::ChopArray (int32 Num) inline
Definition at line 197 of file IoStore.h.
References ChopView(), Num, and ReleaseOwnershipOfLastBlock().
ChopBytes() [1/4]
TConstArrayView< uint8 > FIoStoreTocResourceStorage::ChopBytes (FEmptyVariantState & , int32 Size) inline private
Definition at line 241 of file IoStore.h.
References TSequenceHistory< HistorySize >::Size.
ChopBytes() [2/4]
TConstArrayView< uint8 > FIoStoreTocResourceStorage::ChopBytes (FMappedFile & File, int32 Size) static private
References TSequenceHistory< HistorySize >::Size.
Referenced by ChopBytes(), and ChopView().
ChopBytes() [3/4]
TConstArrayView< uint8 > FIoStoreTocResourceStorage::ChopBytes (FReadBlocks & File, int32 Size) static private
References TSequenceHistory< HistorySize >::Size.
ChopBytes() [4/4]
TConstArrayView< uint8 > FIoStoreTocResourceStorage::ChopBytes (int32 Size) inline private
Definition at line 246 of file IoStore.h.
References ChopBytes(), Data, TSequenceHistory< HistorySize >::Size, Value, and Visit().
ChopView()
template<typename T> TConstArrayView< T > FIoStoreTocResourceStorage::ChopView (int32 Num) inline
Definition at line 188 of file IoStore.h.
References Bytes, check, ChopBytes(), and Num.
Referenced by ChopArray().
FinalizeRead()
void FIoStoreTocResourceStorage::FinalizeRead ()
GetAllocatedSize()
uint64 FIoStoreTocResourceStorage::GetAllocatedSize () const
IsLoaded()
bool FIoStoreTocResourceStorage::IsLoaded () const inline
Definition at line 184 of file IoStore.h.
References Data.
ReleaseOwnershipOfLastBlock()
void FIoStoreTocResourceStorage::ReleaseOwnershipOfLastBlock () private
Referenced by ChopArray().
Field Documentation
Data
TVariant<FEmptyVariantState, FMappedFile, FReadBlocks> FIoStoreTocResourceStorage::Data private
Definition at line 251 of file IoStore.h.
Referenced by ChopBytes(), and IsLoaded().
The documentation for this struct was generated from the following file:
IoStore.h