Unreal Engine 5.6 C++ API: Harmonix::Dsp::Parameters::TParameter< T > Class Template Reference
Harmonix::Dsp::Parameters::TParameter< T > Class Template Reference
An atomic config value for something that needs configuring.
#include "Parameter.h"
Public Member Functions
TParameter (const TParameter &Other)
TParameter (T Min, T Max)
TParameter (T Min, T Max, T Default, T Step=static_cast< T >(0))
T Get () const
operator T () const
bool operator!= (const TParameter &Other) const
TParameter & operator*= (const T &InValue)
TParameter & operator+= (const T &InValue)
TParameter & operator-= (const T &InValue)
TParameter & operator/= (const T &InValue)
bool operator< (const TParameter &Other) const
bool operator<= (const TParameter &Other) const
TParameter & operator= (const T &InValue)
TParameter & operator= (const TParameter &Other)
bool operator== (const T &InValue) const
bool operator== (const TParameter &Other) const
bool operator> (const TParameter &Other) const
bool operator>= (const TParameter &Other) const
void Set (T InValue)
Data Fields
const T Default
const T Max
const T Min
const T Step
Private Attributes
std::atomic< T > Value
Detailed Description
template<typename T>
class Harmonix::Dsp::Parameters::TParameter< T >
An atomic config value for something that needs configuring.
Template Parameters
T The underlying type of the parameter.
Definition at line 22 of file Parameter.h.
Constructor & Destructor Documentation
TParameter() [1/3]
template<typename T> Harmonix::Dsp::Parameters::TParameter< T >::TParameter (T Min, T Max, T Default, T Step = static_cast<T>(0)) inline
Definition at line 25 of file Parameter.h.
TParameter() [2/3]
template<typename T> Harmonix::Dsp::Parameters::TParameter< T >::TParameter (T Min, T Max) inline
Definition at line 35 of file Parameter.h.
TParameter() [3/3]
template<typename T> Harmonix::Dsp::Parameters::TParameter< T >::TParameter (const TParameter< T > & Other) inline
Definition at line 75 of file Parameter.h.
Member Function Documentation
Get()
template<typename T> T Harmonix::Dsp::Parameters::TParameter< T >::Get () const inline
Definition at line 69 of file Parameter.h.
Referenced by Harmonix::Dsp::Parameters::TParameter< bool >::operator bool(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator*=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator+=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator-=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator/=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator<(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator==(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator==(), and Harmonix::Dsp::Parameters::TParameter< uint8 >::operator>().
operator T()
template<typename T> Harmonix::Dsp::Parameters::TParameter< T >::operator T () const inline
Definition at line 148 of file Parameter.h.
operator!=()
template<typename T> bool Harmonix::Dsp::Parameters::TParameter< T >::operator!= (const TParameter< T > & Other) const inline
Definition at line 93 of file Parameter.h.
operator*=()
template<typename T> TParameter & Harmonix::Dsp::Parameters::TParameter< T >::operator*= (const T & InValue) inline
Definition at line 136 of file Parameter.h.
operator+=()
template<typename T> TParameter & Harmonix::Dsp::Parameters::TParameter< T >::operator+= (const T & InValue) inline
Definition at line 124 of file Parameter.h.
operator-=()
template<typename T> TParameter & Harmonix::Dsp::Parameters::TParameter< T >::operator-= (const T & InValue) inline
Definition at line 130 of file Parameter.h.
operator/=()
template<typename T> TParameter & Harmonix::Dsp::Parameters::TParameter< T >::operator/= (const T & InValue) inline
Definition at line 142 of file Parameter.h.
operator<()
template<typename T> bool Harmonix::Dsp::Parameters::TParameter< T >::operator< (const TParameter< T > & Other) const inline
Definition at line 98 of file Parameter.h.
operator<=()
template<typename T> bool Harmonix::Dsp::Parameters::TParameter< T >::operator<= (const TParameter< T > & Other) const inline
Definition at line 108 of file Parameter.h.
operator=() [1/2]
template<typename T> TParameter & Harmonix::Dsp::Parameters::TParameter< T >::operator= (const T & InValue) inline
Definition at line 118 of file Parameter.h.
operator=() [2/2]
template<typename T> TParameter & Harmonix::Dsp::Parameters::TParameter< T >::operator= (const TParameter< T > & Other) inline
Definition at line 82 of file Parameter.h.
operator==() [1/2]
template<typename T> bool Harmonix::Dsp::Parameters::TParameter< T >::operator== (const T & InValue) const inline
Definition at line 153 of file Parameter.h.
operator==() [2/2]
template<typename T> bool Harmonix::Dsp::Parameters::TParameter< T >::operator== (const TParameter< T > & Other) const inline
Definition at line 88 of file Parameter.h.
operator>()
template<typename T> bool Harmonix::Dsp::Parameters::TParameter< T >::operator> (const TParameter< T > & Other) const inline
Definition at line 103 of file Parameter.h.
operator>=()
template<typename T> bool Harmonix::Dsp::Parameters::TParameter< T >::operator>= (const TParameter< T > & Other) const inline
Definition at line 113 of file Parameter.h.
Set()
template<typename T> void Harmonix::Dsp::Parameters::TParameter< T >::Set (T InValue) inline
Definition at line 44 of file Parameter.h.
Referenced by Harmonix::Dsp::Parameters::TParameter< uint8 >::TParameter(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator*=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator+=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator-=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator/=(), Harmonix::Dsp::Parameters::TParameter< uint8 >::operator=(), and Harmonix::Dsp::Parameters::TParameter< uint8 >::operator=().
Field Documentation
Default
template<typename T> const T Harmonix::Dsp::Parameters::TParameter< T >::Default
Definition at line 41 of file Parameter.h.
Max
template<typename T> const T Harmonix::Dsp::Parameters::TParameter< T >::Max
Definition at line 40 of file Parameter.h.
Min
template<typename T> const T Harmonix::Dsp::Parameters::TParameter< T >::Min
Definition at line 39 of file Parameter.h.
Step
template<typename T> const T Harmonix::Dsp::Parameters::TParameter< T >::Step
Definition at line 42 of file Parameter.h.
Value
template<typename T> std::atomic<T> Harmonix::Dsp::Parameters::TParameter< T >::Value private
Definition at line 159 of file Parameter.h.
The documentation for this class was generated from the following file:
Parameter.h