Unreal Engine 5.6 C++ API: FGeometryHelper Class Reference
FGeometryHelper Class Reference
#include "ConnectionDrawingPolicy.h"
Public Member Functions
UE_DEPRECATED (5.6, "Use Array of FVector2f instead of FVector2D for slate positions") static void ConvertToPoints(const FGeometry &Geom
Static Public Member Functions
static UE::Slate::FDeprecateVector2DResult CenterOf (const FGeometry &SomeGeometry)
static void ConvertToPoints (const FGeometry &Geom, TArray< FVector2f > &Points)
static UE::Slate::FDeprecateVector2DResult FindClosestPointOnGeom (const FGeometry &Geom, const UE::Slate::FDeprecateVector2DParameter &TestPoint)
static UE::Slate::FDeprecateVector2DResult FindClosestPointOnLine (const UE::Slate::FDeprecateVector2DParameter &LineStart, const UE::Slate::FDeprecateVector2DParameter &LineEnd, const UE::Slate::FDeprecateVector2DParameter &TestPoint)
Find the point on line segment from LineStart to LineEnd which is closest to Point.
static UE::Slate::FDeprecateVector2DResult VerticalMiddleLeftOf (const FGeometry &SomeGeometry)
static UE::Slate::FDeprecateVector2DResult VerticalMiddleRightOf (const FGeometry &SomeGeometry)
Data Fields
TArray< FVector2D > & Points
Detailed Description
Definition at line 40 of file ConnectionDrawingPolicy.h.
Member Function Documentation
CenterOf()
UE::Slate::FDeprecateVector2DResult FGeometryHelper::CenterOf (const FGeometry & SomeGeometry) static
ConvertToPoints()
void FGeometryHelper::ConvertToPoints (const FGeometry & Geom, TArray< FVector2f > & Points) static
References ConvertToPoints(), and Points.
Referenced by ConvertToPoints().
FindClosestPointOnGeom()
UE::Slate::FDeprecateVector2DResult FGeometryHelper::FindClosestPointOnGeom (const FGeometry & Geom, const UE::Slate::FDeprecateVector2DParameter & TestPoint) static
References FindClosestPointOnGeom().
Referenced by FindClosestPointOnGeom().
FindClosestPointOnLine()
UE::Slate::FDeprecateVector2DResult FGeometryHelper::FindClosestPointOnLine (const UE::Slate::FDeprecateVector2DParameter & LineStart, const UE::Slate::FDeprecateVector2DParameter & LineEnd, const UE::Slate::FDeprecateVector2DParameter & TestPoint) static
Find the point on line segment from LineStart to LineEnd which is closest to Point.
References FindClosestPointOnLine().
Referenced by FindClosestPointOnLine().
UE_DEPRECATED()
FGeometryHelper::UE_DEPRECATED (5. 6, "Use Array of FVector2f instead of FVector2D for slate positions") const &
VerticalMiddleLeftOf()
UE::Slate::FDeprecateVector2DResult FGeometryHelper::VerticalMiddleLeftOf (const FGeometry & SomeGeometry) static
VerticalMiddleRightOf()
UE::Slate::FDeprecateVector2DResult FGeometryHelper::VerticalMiddleRightOf (const FGeometry & SomeGeometry) static
Field Documentation
Points
TArray<FVector2D>& FGeometryHelper::Points
Definition at line 48 of file ConnectionDrawingPolicy.h.
Referenced by ConvertToPoints().
The documentation for this class was generated from the following file:
ConnectionDrawingPolicy.h