Unreal Engine 5.6 C++ API: UE::Sequencer::ICastable Class Reference
UE::Sequencer::ICastable Class Reference
#include "ICastable.h"
Data Structures
struct FAutoRegisterTypeTable
Struct that assigns an ICastable instance's TypeTable.
Public Member Functions
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Static Public Member Functions
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Protected Attributes
FDynamicExtensionContainer * DynamicTypes = nullptr
Private Attributes
friend FAutoRegisterTypeTable
const FCastableTypeTable *const TypeTable = nullptr
Detailed Description
Definition at line 21 of file ICastable.h.
Member Function Documentation
CastedCall() [1/2]
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes> RetType UE::Sequencer::ICastable::CastedCall (RetType(InterfaceType::* MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) inline
Definition at line 26 of file ICastable.h.
References CastThisChecked(), Forward(), and Invoke().
CastedCall() [2/2]
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes> RetType UE::Sequencer::ICastable::CastedCall (RetType(InterfaceType::* MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const inline
Definition at line 32 of file ICastable.h.
References CastThisChecked(), Forward(), and Invoke().
CastRaw() [1/2]
void * UE::Sequencer::ICastable::CastRaw (FViewModelTypeID InType)
Referenced by CastThis(), CastThis(), and IsA().
CastRaw() [2/2]
const void * UE::Sequencer::ICastable::CastRaw (FViewModelTypeID InType) const
CastThis() [1/2]
template<typename T> T * UE::Sequencer::ICastable::CastThis () inline
Definition at line 72 of file ICastable.h.
References CastRaw().
Referenced by UE::Sequencer::FViewModel::AddDynamicExtension(), CastThisChecked(), CastThisChecked(), UE::Sequencer::FViewModel::CastThisShared(), UE::Sequencer::FViewModel::CastThisShared(), and IsA().
CastThis() [2/2]
template<typename T> const T * UE::Sequencer::ICastable::CastThis () const inline
Definition at line 78 of file ICastable.h.
References CastRaw().
CastThisChecked() [1/2]
template<typename T> T * UE::Sequencer::ICastable::CastThisChecked () inline
Definition at line 84 of file ICastable.h.
References CastThis(), and check.
Referenced by CastedCall(), CastedCall(), UE::Sequencer::FViewModel::CastThisSharedChecked(), and UE::Sequencer::FViewModel::CastThisSharedChecked().
CastThisChecked() [2/2]
template<typename T> const T * UE::Sequencer::ICastable::CastThisChecked () const inline
Definition at line 92 of file ICastable.h.
References CastThis(), and check.
CastWeakPtr()
template<typename T> T * UE::Sequencer::ICastable::CastWeakPtr (const TWeakPtr< ICastable > & InWeakPtr) inline static
Definition at line 38 of file ICastable.h.
References TWeakPtr< ObjectType, InMode >::Pin().
CastWeakPtrShared()
template<typename T> TSharedPtr< T > UE::Sequencer::ICastable::CastWeakPtrShared (const TWeakPtr< ICastable > & InWeakPtr) inline static
Definition at line 48 of file ICastable.h.
References TWeakPtr< ObjectType, InMode >::Pin().
GetTypeTable()
const FCastableTypeTable & UE::Sequencer::ICastable::GetTypeTable () const inline
Definition at line 99 of file ICastable.h.
References checkSlow, and TypeTable.
IsA() [1/2]
template<typename T> bool UE::Sequencer::ICastable::IsA () const inline
Definition at line 63 of file ICastable.h.
References CastThis().
IsA() [2/2]
bool UE::Sequencer::ICastable::IsA (FViewModelTypeID InType) const inline
Definition at line 57 of file ICastable.h.
References CastRaw().
Field Documentation
DynamicTypes
FDynamicExtensionContainer* UE::Sequencer::ICastable::DynamicTypes = nullptr protected
Definition at line 125 of file ICastable.h.
Referenced by UE::Sequencer::FViewModel::AddDynamicExtension().
FAutoRegisterTypeTable
friend UE::Sequencer::ICastable::FAutoRegisterTypeTable private
Definition at line 121 of file ICastable.h.
TypeTable
const FCastableTypeTable* const UE::Sequencer::ICastable::TypeTable = nullptr private
Definition at line 122 of file ICastable.h.
Referenced by GetTypeTable().
The documentation for this class was generated from the following file:
ICastable.h