Unreal Engine 5.6 C++ API: TBitArray< Allocator >::FConstIterator Class Reference
TBitArray< Allocator >::FConstIterator Class Reference
Const BitArray iterator.
#include "BitArray.h"
Public Member Functions
FORCEINLINE FConstIterator (const TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 StartIndex=0)
FORCEINLINE int32 GetIndex () const
FORCEINLINE FConstBitReference GetValue () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE FConstBitReference operator* () const
FORCEINLINE FConstIterator & operator++ ()
Public Member Functions inherited from FRelativeBitReference
FORCEINLINE FRelativeBitReference (int32 BitIndex)
FORCEINLINE bool operator!= (FRelativeBitReference Other) const
FORCEINLINE bool operator== (FRelativeBitReference Other) const
Private Attributes
const TBitArray< Allocator > & Array
int32 Index
Additional Inherited Members
Data Fields inherited from FRelativeBitReference
uint32 Mask
int32 WordIndex
Detailed Description
template<typename Allocator>
class TBitArray< Allocator >::FConstIterator
Const BitArray iterator.
Definition at line 1580 of file BitArray.h.
Constructor & Destructor Documentation
FConstIterator()
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::FConstIterator::FConstIterator (const TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 StartIndex = 0) inline explicit nodiscard
Definition at line 1583 of file BitArray.h.
References FRelativeBitReference::FRelativeBitReference(), TBitArray< Allocator >::TBitArray(), Array, FORCEINLINE, Index, and UE_LIFETIMEBOUND.
Referenced by operator++().
Member Function Documentation
GetIndex()
template<typename Allocator> FORCEINLINE int32 TBitArray< Allocator >::FConstIterator::GetIndex () const inline nodiscard
Definition at line 1619 of file BitArray.h.
References FORCEINLINE, and Index.
Referenced by TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::ExportTypes(), and TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::ExportTypes().
GetValue()
template<typename Allocator> FORCEINLINE FConstBitReference TBitArray< Allocator >::FConstIterator::GetValue () const inline nodiscard
Definition at line 1618 of file BitArray.h.
References Array, and FORCEINLINE.
Referenced by TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::ExportTypes(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::ExportTypes(), and operator*().
operator bool()
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::FConstIterator::operator bool () const inline explicit nodiscard
conversion to "bool" returning true if the iterator is valid.
Definition at line 1608 of file BitArray.h.
References Array, FORCEINLINE, and Index.
operator!()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::FConstIterator::operator! () const inline nodiscard
inverse of the "bool" operator
Definition at line 1613 of file BitArray.h.
References bool, and FORCEINLINE.
operator*()
template<typename Allocator> FORCEINLINE FConstBitReference TBitArray< Allocator >::FConstIterator::operator* () const inline nodiscard
Definition at line 1602 of file BitArray.h.
References FORCEINLINE, and GetValue().
operator++()
template<typename Allocator> FORCEINLINE FConstIterator & TBitArray< Allocator >::FConstIterator::operator++ () inline
Definition at line 1589 of file BitArray.h.
References FConstIterator(), FORCEINLINE, Index, and FRelativeBitReference::WordIndex.
Field Documentation
Array
template<typename Allocator> const TBitArray<Allocator>& TBitArray< Allocator >::FConstIterator::Array private
Definition at line 1621 of file BitArray.h.
Referenced by FConstIterator(), GetValue(), and operator bool().
Index
template<typename Allocator> int32 TBitArray< Allocator >::FConstIterator::Index private
Definition at line 1622 of file BitArray.h.
Referenced by FConstIterator(), GetIndex(), operator bool(), and operator++().
The documentation for this class was generated from the following file:
BitArray.h