Unreal Engine 5.6 C++ API: UE::FPackageTrailerBuilder Class Reference
UE::FPackageTrailerBuilder Class Reference
This class is used to build a FPackageTrailer and write it disk.
#include "PackageTrailer.h"
Data Structures
struct LocalEntry
All of the data required to add a payload that is stored locally within the trailer.
struct ReferencedEntry
All of the data required to add a reference to a payload stored in another trailer.
struct VirtualizedEntry
All of the data required to add a payload that is virtualized.
Public Types
using AdditionalDataCallback = TFunction<void(FLinkerSave& LinkerSave, const class FPackageTrailer& Trailer)>
Public Member Functions
FPackageTrailerBuilder ()=default
FPackageTrailerBuilder (FString &&DebugContext)
~FPackageTrailerBuilder ()=default
void AddPayload (const FIoHash &Identifier, FCompressedBuffer Payload, UE::Virtualization::EPayloadFilterReason Filter)
void AddPayload (const FIoHash &Identifier, FCompressedBuffer Payload, UE::Virtualization::EPayloadFilterReason Filter, AdditionalDataCallback &&Callback)
Adds a payload to the builder to be written to the trailer.
void AddVirtualizedPayload (const FIoHash &Identifier, int64 RawSize)
Adds an already virtualized payload to the builder to be written to the trailer.
bool BuildAndAppendTrailer (FLinkerSave *Linker, FArchive &DataArchive)
bool BuildAndAppendTrailer (FLinkerSave *Linker, FArchive &DataArchive, int64 &InOutPackageFileOffset)
uint64 CalculateTrailerLength ()
Returns the length of the trailer (in bytes) that the builder would currently create.
const FString & GetDebugContext () const
Returns the debug context associated with the builder, used for adding further description to error messages.
int32 GetNumLocalPayloads () const
Returns the number of payload entries in the builder with the access mode EPayloadAccessMode::Local.
int32 GetNumPayloads () const
Returns the total number of payload entries in the builder.
int32 GetNumReferencedPayloads () const
Returns the number of payload entries in the builder with the access mode EPayloadAccessMode::Referenced.
int32 GetNumVirtualizedPayloads () const
Returns the number of payload entries in the builder with the access mode EPayloadAccessMode::Virtualized.
bool IsEmpty () const
Returns if the builder has any payload entries or not.
bool IsLocalPayloadEntry (const FIoHash &Identifier) const
bool IsReferencedPayloadEntry (const FIoHash &Identifier) const
bool IsVirtualizedPayloadEntry (const FIoHash &Identifier) const
UE_DEPRECATED (5.1, "Use the overload that takes a FString instead of an FName for the last parameter") static FPackageTrailerBuilder CreateFromTrailer(const class FPackageTrailer &Trailer
UE_DEPRECATED (5.1, "Use the overload that takes a FString instead of an FName for the last parameter") static TUniquePtr< UE
UE_DEPRECATED (5.1, "Use the overload that takes a FString instead of an FName") 1 FPackageTrailerBuilder(const FName &InPackageName)
bool UpdatePayloadAsLocal (const FIoHash &Identifier, FCompressedBuffer Payload)
Allows the caller to replace a payload in the builder that is already marked as virtualized and replace it with one that will be stored locally.
Static Public Member Functions
static FPackageTrailerBuilder CreateFromTrailer (const class FPackageTrailer &Trailer, FArchive &Ar, FString DebugContext)
Creates a builder from a pre-existing FPackageTrailer.
static TUniquePtr< UE::FPackageTrailerBuilder > CreateReferenceToTrailer (const class FPackageTrailer &Trailer, FString DebugContext)
Creates a builder from a pre-existing FPackageTrailer that will will reference the local payloads of the source trailer.
Data Fields
FArchive & Ar
FArchive const FName & PackageName
Private Member Functions
uint32 CalculatePotentialHeaderSize () const
Returns the total length of the header if we were to build a trailer right now.
uint64 CalculatePotentialPayloadSize () const
Returns the total length of all payloads combined if we were to build a trailer right now.
void RemoveDuplicateEntries ()
Private Attributes
TArray< AdditionalDataCallback > Callbacks
Callbacks to invoke once the trailer has been written to the end of a package.
FString DebugContext
Context used when giving error messages so that the user can identify the cause of problems.
TMap< FIoHash, LocalEntry > LocalEntries
Payloads that will be stored locally when the trailer is written to disk.
TMap< FIoHash, ReferencedEntry > ReferencedEntries
Payloads that reference entries in another trailer.
TMap< FIoHash, VirtualizedEntry > VirtualizedEntries
Payloads that are already virtualized and so will not be written to disk.
Detailed Description
This class is used to build a FPackageTrailer and write it disk.
While saving a package, payloads should be added to a FPackageTrailer via AddPayload then once the package has been saved to disk BuildAndAppendTrailer should be called.
Definition at line 199 of file PackageTrailer.h.
Member Typedef Documentation
AdditionalDataCallback
using UE::FPackageTrailerBuilder::AdditionalDataCallback = TFunction<void(FLinkerSave& LinkerSave, const class FPackageTrailer& Trailer)>
Definition at line 202 of file PackageTrailer.h.
Constructor & Destructor Documentation
FPackageTrailerBuilder() [1/2]
UE::FPackageTrailerBuilder::FPackageTrailerBuilder () default
Referenced by FPackageTrailerBuilder(), ~FPackageTrailerBuilder(), CreateFromTrailer(), UE_DEPRECATED(), and UE_DEPRECATED().
FPackageTrailerBuilder() [2/2]
UE::FPackageTrailerBuilder::FPackageTrailerBuilder (FString && DebugContext)
References FPackageTrailerBuilder(), and DebugContext.
~FPackageTrailerBuilder()
UE::FPackageTrailerBuilder::~FPackageTrailerBuilder () default
References FPackageTrailerBuilder().
Member Function Documentation
AddPayload() [1/2]
void UE::FPackageTrailerBuilder::AddPayload (const FIoHash & Identifier, FCompressedBuffer Payload, UE::Virtualization::EPayloadFilterReason Filter)
References AddPayload(), and Filter.
AddPayload() [2/2]
void UE::FPackageTrailerBuilder::AddPayload (const FIoHash & Identifier, FCompressedBuffer Payload, UE::Virtualization::EPayloadFilterReason Filter, AdditionalDataCallback && Callback)
Adds a payload to the builder to be written to the trailer.
Duplicate payloads will be discarded and only a single instance stored in the trailer.
Parameters
Identifier The identifier of the payload
Payload The payload data
Flags The custom flags to be applied to the payload
Callback This callback will be invoked once the FPackageTrailer has been built and appended to disk.
References AddPayload(), and Filter.
Referenced by AddPayload(), and AddPayload().
AddVirtualizedPayload()
void UE::FPackageTrailerBuilder::AddVirtualizedPayload (const FIoHash & Identifier, int64 RawSize)
Adds an already virtualized payload to the builder to be written to the trailer.
When the trailer is written the payload will have EPayloadAccessMode::Virtualized set as it's access mode. It is assumed that the payload is already stored in the virtualization backends and it is up to the calling code to confirm this. Duplicate payloads will be discarded and only a single instance stored in the trailer.
Parameters
Identifier The identifier of the payload
RawSize The size of the payload (in bytes) when uncompressed
References AddVirtualizedPayload().
Referenced by AddVirtualizedPayload().
BuildAndAppendTrailer() [1/2]
bool UE::FPackageTrailerBuilder::BuildAndAppendTrailer (FLinkerSave * Linker, FArchive & DataArchive) nodiscard
Parameters
ExportsArchive The linker associated with the package being written to disk.
DataArchive The archive where the package data has been written to. This is where the FPackageTrailer will be written to
Returns
True if the builder was created and appended successfully and false if any error was encountered
References BuildAndAppendTrailer().
Referenced by BuildAndAppendTrailer(), and BuildAndAppendTrailer().
BuildAndAppendTrailer() [2/2]
bool UE::FPackageTrailerBuilder::BuildAndAppendTrailer (FLinkerSave * Linker, FArchive & DataArchive, int64 & InOutPackageFileOffset) nodiscard
Parameters
ExportsArchive The linker associated with the package being written to disk.
DataArchive The archive where the package data has been written to. This is where the FPackageTrailer will be written to
InOutPackageFileOffset The offset at which the trailer is written in the package file. In this function version, DataArchive might be an archive for the entire package file, or it might be a separate archive solely for the package trailer. The caller must provide the initial value with the accumulated offset, and the function will increment this value by how many bytes are written to DataArchive.
Returns
True if the builder was created and appended successfully and false if any error was encountered
References BuildAndAppendTrailer().
CalculatePotentialHeaderSize()
uint32 UE::FPackageTrailerBuilder::CalculatePotentialHeaderSize () const private
Returns the total length of the header if we were to build a trailer right now.
CalculatePotentialPayloadSize()
uint64 UE::FPackageTrailerBuilder::CalculatePotentialPayloadSize () const private
Returns the total length of all payloads combined if we were to build a trailer right now.
CalculateTrailerLength()
uint64 UE::FPackageTrailerBuilder::CalculateTrailerLength () nodiscard
Returns the length of the trailer (in bytes) that the builder would currently create.
NOTE: At the moment this is not const as we need to check for and remove duplicate payload entries as we do this before building the trailer not when gathering the entry info.
References CalculateTrailerLength().
Referenced by CalculateTrailerLength().
CreateFromTrailer()
FPackageTrailerBuilder UE::FPackageTrailerBuilder::CreateFromTrailer (const class FPackageTrailer & Trailer, FArchive & Ar, FString DebugContext) static nodiscard
Creates a builder from a pre-existing FPackageTrailer.
Payloads stored locally in the source trailer will be loaded from disk via the provided archive so that the builder can write them to any future trailer that it creates.
Parameters
Trailer The trailer to create the builder from
Ar An archive that the trailer can use to load payloads from
DebugContext The name or path of the of the file that owns the trailer. Used for error messages.
References FPackageTrailerBuilder(), Ar, and DebugContext.
CreateReferenceToTrailer()
TUniquePtr< UE::FPackageTrailerBuilder > UE::FPackageTrailerBuilder::CreateReferenceToTrailer (const class FPackageTrailer & Trailer, FString DebugContext) static nodiscard
Creates a builder from a pre-existing FPackageTrailer that will will reference the local payloads of the source trailer.
This means that there is no need to load the payloads.
Parameters
Trailer The trailer to create the reference from.
DebugContext The name or path of the of the file that owns the trailer. Used for error messages.
References DebugContext.
Referenced by UE_DEPRECATED().
GetDebugContext()
const FString & UE::FPackageTrailerBuilder::GetDebugContext () const inline nodiscard
Returns the debug context associated with the builder, used for adding further description to error messages.
Definition at line 322 of file PackageTrailer.h.
References DebugContext, and GetDebugContext().
Referenced by GetDebugContext().
GetNumLocalPayloads()
int32 UE::FPackageTrailerBuilder::GetNumLocalPayloads () const nodiscard
Returns the number of payload entries in the builder with the access mode EPayloadAccessMode::Local.
References GetNumLocalPayloads().
Referenced by GetNumLocalPayloads().
GetNumPayloads()
int32 UE::FPackageTrailerBuilder::GetNumPayloads () const nodiscard
Returns the total number of payload entries in the builder.
References GetNumPayloads().
Referenced by GetNumPayloads().
GetNumReferencedPayloads()
int32 UE::FPackageTrailerBuilder::GetNumReferencedPayloads () const nodiscard
Returns the number of payload entries in the builder with the access mode EPayloadAccessMode::Referenced.
References GetNumReferencedPayloads().
Referenced by GetNumReferencedPayloads().
GetNumVirtualizedPayloads()
int32 UE::FPackageTrailerBuilder::GetNumVirtualizedPayloads () const nodiscard
Returns the number of payload entries in the builder with the access mode EPayloadAccessMode::Virtualized.
References GetNumVirtualizedPayloads().
Referenced by GetNumVirtualizedPayloads().
IsEmpty()
bool UE::FPackageTrailerBuilder::IsEmpty () const nodiscard
Returns if the builder has any payload entries or not.
References IsEmpty().
Referenced by IsEmpty().
IsLocalPayloadEntry()
bool UE::FPackageTrailerBuilder::IsLocalPayloadEntry (const FIoHash & Identifier) const nodiscard
References IsLocalPayloadEntry().
Referenced by IsLocalPayloadEntry().
IsReferencedPayloadEntry()
bool UE::FPackageTrailerBuilder::IsReferencedPayloadEntry (const FIoHash & Identifier) const nodiscard
References IsReferencedPayloadEntry().
Referenced by IsReferencedPayloadEntry().
IsVirtualizedPayloadEntry()
bool UE::FPackageTrailerBuilder::IsVirtualizedPayloadEntry (const FIoHash & Identifier) const nodiscard
References IsVirtualizedPayloadEntry().
Referenced by IsVirtualizedPayloadEntry().
RemoveDuplicateEntries()
void UE::FPackageTrailerBuilder::RemoveDuplicateEntries () private
UE_DEPRECATED() [1/3]
UE::FPackageTrailerBuilder::UE_DEPRECATED (5. 1, "Use the overload that takes a FString instead of an FName for the last parameter") const &
UE_DEPRECATED() [2/3]
UE::FPackageTrailerBuilder::UE_DEPRECATED (5. 1, "Use the overload that takes a FString instead of an FName for the last parameter") inline
Definition at line 231 of file PackageTrailer.h.
References FPackageTrailerBuilder(), CreateReferenceToTrailer(), and PackageName.
UE_DEPRECATED() [3/3]
UE::FPackageTrailerBuilder::UE_DEPRECATED (5. 1, "Use the overload that takes a FString instead of an FName") const &
References FPackageTrailerBuilder().
UpdatePayloadAsLocal()
bool UE::FPackageTrailerBuilder::UpdatePayloadAsLocal (const FIoHash & Identifier, FCompressedBuffer Payload)
Allows the caller to replace a payload in the builder that is already marked as virtualized and replace it with one that will be stored locally.
Parameters
Identifier The identifier of the payload
Payload The content of the payload
Returns
true if a virtualized payload was replaced, false if the payload was not in the builder at all
References UpdatePayloadAsLocal().
Referenced by UpdatePayloadAsLocal().
Field Documentation
Ar
FArchive& UE::FPackageTrailerBuilder::Ar
Definition at line 216 of file PackageTrailer.h.
Referenced by CreateFromTrailer().
Callbacks
TArray<AdditionalDataCallback> UE::FPackageTrailerBuilder::Callbacks private
Callbacks to invoke once the trailer has been written to the end of a package.
Definition at line 397 of file PackageTrailer.h.
DebugContext
FString UE::FPackageTrailerBuilder::DebugContext private
Context used when giving error messages so that the user can identify the cause of problems.
Definition at line 388 of file PackageTrailer.h.
Referenced by FPackageTrailerBuilder(), CreateFromTrailer(), CreateReferenceToTrailer(), and GetDebugContext().
LocalEntries
TMap<FIoHash, LocalEntry> UE::FPackageTrailerBuilder::LocalEntries private
Payloads that will be stored locally when the trailer is written to disk.
Definition at line 391 of file PackageTrailer.h.
PackageName
FArchive const FName& UE::FPackageTrailerBuilder::PackageName
Initial value:
{
        return FPackageTrailerBuilder::CreateFromTrailer(Trailer, Ar, PackageName.ToString())
Definition at line 216 of file PackageTrailer.h.
Referenced by UE_DEPRECATED().
ReferencedEntries
TMap<FIoHash, ReferencedEntry> UE::FPackageTrailerBuilder::ReferencedEntries private
Payloads that reference entries in another trailer.
Definition at line 393 of file PackageTrailer.h.
VirtualizedEntries
TMap<FIoHash, VirtualizedEntry> UE::FPackageTrailerBuilder::VirtualizedEntries private
Payloads that are already virtualized and so will not be written to disk.
Definition at line 395 of file PackageTrailer.h.
The documentation for this class was generated from the following file:
PackageTrailer.h