Unreal Engine 5.6 C++ API: TFindObjectReferencers< T > Class Template Reference
TFindObjectReferencers< T > Class Template Reference
This class is used to find which objects reference any element from a list of "TargetObjects".
#include "FindObjectReferencers.h"
Public Member Functions
TFindObjectReferencers (TArray< T * > TargetObjects, UPackage *PackageToCheck=NULL, bool bIgnoreTemplates=true, bool bFindAlsoWeakReferences=false)
Default constructor.
Public Member Functions inherited from TMultiMap< T *, UObject * >
TMultiMap ()=default
FORCEINLINE UObject *& AddUnique (const T *&InKey, const UObject *&InValue)
Add a key-value association to the map.
void Append (TMultiMap< T *, UObject *, OtherSetAllocator, KeyFuncs > &&OtherMultiMap)
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
UObject *& EmplaceUnique (InitKeyType &&InKey, InitValueType &&InValue)
Add a key-value association to the map.
FORCEINLINE const UObject ** FindPair (KeyInitType Key, ValueInitType Value) const
Find an association between a specified key and value.
void MultiFind (KeyInitType Key, TArray< UObject *, Allocator > &OutValues, bool bMaintainOrder=false) const
Finds all values associated with the specified key.
void MultiFindPointer (KeyInitType Key, TArray< const UObject **, Allocator > &OutValues, bool bMaintainOrder=false) const
Finds all values associated with the specified key.
int32 Num (KeyInitType Key) const
Returns the number of values within this map associated with the specified key.
TMultiMap & operator= (TMultiMap &&)=default
bool operator== (FIntrusiveUnsetOptionalState Tag) const
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
int32 RemoveSingle (KeyInitType InKey, ValueInitType InValue)
Remove the first association between the specified key and value from the map.
Public Member Functions inherited from TSortableMapBase< T *, UObject *, SetAllocator, KeyFuncs >
FORCEINLINE void KeySort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
FORCEINLINE void KeyStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
void SortFreeList ()
Sort the free element list so that subsequent additions will occur in the lowest available TSet index resulting in tighter packing without moving any existing items.
FORCEINLINE void ValueSort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
FORCEINLINE void ValueStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
Public Member Functions inherited from TMapBase< T *, UObject *, SetAllocator, KeyFuncs >
FORCEINLINE UObject *& Add (const T *&InKey, const UObject *&InValue)
Set the value associated with a key.
FORCEINLINE UObject *& AddByHash (uint32 KeyHash, const T *&InKey, const UObject *&InValue)
See Add() and class documentation section on ByHash() functions.
TArray< ElementType > Array () const
Copy the key/value pairs in this map into an array.
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE void Compact ()
Compacts the pair set to remove holes.
FORCEINLINE void CompactStable ()
Compacts the pair set to remove holes.
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Check if map contains the specified key.
FORCEINLINE bool ContainsByHash (uint32 KeyHash, const ComparableKey &Key) const
See Contains() and class documentation section on ByHash() functions.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
FORCEINLINE void CountBytes (FArchive &Ar) const
Track the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (typename TConstKeyIterator::KeyArgumentType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (typename TKeyIterator::KeyArgumentType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
UObject *& Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
UObject *& EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey, InitValueType &&InValue)
See Emplace() and class documentation section on ByHash() functions.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map.
FORCEINLINE TRangedForIterator end ()
TMap< T *, UObject *, SetAllocator, KeyFuncs > FilterByPredicate (Predicate Pred) const
Filters the elements in the map based on a predicate functor.
FORCEINLINE UObject ** Find (KeyConstPointerType Key)
Find the value associated with a specified key.
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
FORCEINLINE UObject ** FindByHash (uint32 KeyHash, const ComparableKey &Key)
See Find() and class documentation section on ByHash() functions.
FORCEINLINE UObject *& FindByHashChecked (uint32 KeyHash, const ComparableKey &Key)
FORCEINLINE const UObject *& FindChecked (KeyConstPointerType Key) const
Find a reference to the value associated with a specified key.
FORCEINLINE FSetElementId FindId (KeyInitType Key) const
Finds the index of the first element that is assigned to the specified key.
FORCEINLINE FSetElementId FindIdByHash (uint32 KeyHash, const ComparableKey &Key) const
See FindId() and class documentation section on ByHash() functions.
const T ** FindKey (ValueInitType Value) const
Find the key associated with the specified value.
FORCEINLINE UObject *& FindOrAdd (const T *&Key)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE UObject *& FindOrAddByHash (uint32 KeyHash, const T *&Key)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE UObject * FindRef (KeyConstPointerType Key) const
Find the value associated with a specified key.
void GenerateKeyArray (TArray< T *, Allocator > &OutArray) const
Generate an array from the keys in this map.
void GenerateValueArray (TArray< UObject *, Allocator > &OutArray) const
Generate an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container .
int32 GetKeys (TArray< T *, Allocator > &OutKeys) const
Get the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
bool OrderIndependentCompareEqual (const TMapBase &Other) const
Compare this map with another for equality.
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
FORCEINLINE int32 RemoveByHash (uint32 KeyHash, const ComparableKey &Key)
See Remove() and class documentation section on ByHash() functions.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Additional Inherited Members
Public Types inherited from TMultiMap< T *, UObject * >
using IntrusiveUnsetOptionalStateType
typedef Super::KeyConstPointerType KeyConstPointerType
typedef Super::KeyInitType KeyInitType
typedef TSortableMapBase< T *, UObject *, SetAllocator, KeyFuncs > Super
typedef Super::ValueInitType ValueInitType
Public Types inherited from TMapBase< T *, UObject *, SetAllocator, KeyFuncs >
typedef TPair< T *, UObject * > ElementType
typedef TTypeTraits< T * >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< T * >::ConstInitType KeyInitType
using TRangedForConstIterator
using TRangedForIterator
typedef TTypeTraits< UObject * >::ConstInitType ValueInitType
Static Public Member Functions inherited from TMapBase< T *, UObject *, SetAllocator, KeyFuncs >
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Static Public Attributes inherited from TMultiMap< T *, UObject * >
static constexpr bool bHasIntrusiveUnsetOptionalState
Protected Types inherited from TSortableMapBase< T *, UObject *, SetAllocator, KeyFuncs >
using IntrusiveUnsetOptionalStateType
typedef TMapBase< T *, UObject *, SetAllocator, KeyFuncs > Super
Protected Types inherited from TMapBase< T *, UObject *, SetAllocator, KeyFuncs >
typedef TSet< ElementType, KeyFuncs, SetAllocator > ElementSetType
using IntrusiveUnsetOptionalStateType
Protected Member Functions inherited from TSortableMapBase< T *, UObject *, SetAllocator, KeyFuncs >
TSortableMapBase ()=default
TSortableMapBase & operator= (TSortableMapBase &&)=default
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Protected Member Functions inherited from TMapBase< T *, UObject *, SetAllocator, KeyFuncs >
TMapBase & operator= (TMapBase &&)=default
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Protected Attributes inherited from TMapBase< T *, UObject *, SetAllocator, KeyFuncs >
ElementSetType Pairs
A set of the key-value pairs in the map.
Static Protected Attributes inherited from TSortableMapBase< T *, UObject *, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState
Static Protected Attributes inherited from TMapBase< T *, UObject *, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState
Detailed Description
template<class T>
class TFindObjectReferencers< T >
This class is used to find which objects reference any element from a list of "TargetObjects".
When invoked, it will generate a mapping of each target object to an array of objects referencing that target object.
Each key corresponds to an element of the input TargetObjects array which was referenced by some other object. The values for these keys are the objects which are referencing them.
Definition at line 18 of file FindObjectReferencers.h.
Constructor & Destructor Documentation
TFindObjectReferencers()
template<class T> TFindObjectReferencers< T >::TFindObjectReferencers (TArray< T * > TargetObjects, UPackage * PackageToCheck = NULL, bool bIgnoreTemplates = true, bool bFindAlsoWeakReferences = false) inline
Default constructor.
Parameters
TargetObjects the list of objects to find references to
PackageToCheck if specified, only objects contained in this package will be searched for references to
bIgnoreTemplates If true, do not record template objects
bFindAlsoWeakReferences If true, also look into weak references
Definition at line 31 of file FindObjectReferencers.h.
References TMultiMap< T *, UObject * >::TMultiMap(), Add, TArray< InElementType, InAllocatorType >::Contains(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GenerateKeyArray(), FFindReferencersArchive::GetReferenceCounts(), UObjectBaseUtility::IsIn(), UObjectBaseUtility::IsTemplate(), TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Reset(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reset(), and FFindReferencersArchive::ResetPotentialReferencer().
The documentation for this class was generated from the following file:
FindObjectReferencers.h