Unreal Engine 5.6 C++ API: FRawStaticIndexBuffer16or32Interface Class Reference
FRawStaticIndexBuffer16or32Interface Class Reference abstract
Virtual interface for the FRawStaticIndexBuffer16or32 class.
#include "RawIndexBuffer.h"
Public Member Functions
virtual int32 AddItem (uint32 Val)=0
virtual void Empty (int32 Slack=0)=0
virtual uint32 Get (uint32 Idx) const =0
virtual bool GetNeedsCPUAccess () const =0
The following methods are basically just accessors that allow us to hide the implementation of FRawStaticIndexBuffer16or32 by making the index array a private member.
virtual void * GetPointerTo (uint32 Idx)=0
virtual int32 GetResourceDataSize () const =0
FRHIShaderResourceView * GetSRV () const
virtual void Insert (int32 Idx, int32 Num=1)=0
virtual int32 Num () const =0
virtual void Remove (int32 Idx, int32 Num=1)=0
virtual void Serialize (FArchive &Ar)=0
virtual void SerializeMetaData (FArchive &Ar)=0
virtual void SetMetaData (int32 InCachedNumIndices)=0
Public Member Functions inherited from FIndexBuffer
RENDERCORE_API FIndexBuffer ()
RENDERCORE_API FIndexBuffer (const FIndexBuffer &)
virtual RENDERCORE_API ~FIndexBuffer ()
virtual RENDERCORE_API FString GetFriendlyName () const override
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FIndexBuffer & operator= (const FIndexBuffer &Other)
virtual RENDERCORE_API void ReleaseRHI () override
Releases the RHI resources used by this resource.
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Protected Member Functions
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, size_t IndexSize, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
bool IsSRVNeeded (bool bAllowCPUAccess) const
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions
static FBufferRHIRef CreateRHIIndexBufferInternal (FRHICommandListBase &RHICmdList, const TCHAR *InDebugName, const FName &InOwnerName, int32 IndexCount, size_t IndexSize, FResourceArrayInterface *ResourceArray, bool bNeedSRV)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes
FShaderResourceViewRHIRef SRVValue
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FIndexBuffer
FBufferRHIRef IndexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Detailed Description
Virtual interface for the FRawStaticIndexBuffer16or32 class.
Definition at line 325 of file RawIndexBuffer.h.
Member Function Documentation
AddItem()
virtual int32 FRawStaticIndexBuffer16or32Interface::AddItem (uint32 Val) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
CreateRHIIndexBufferInternal()
FBufferRHIRef FRawStaticIndexBuffer16or32Interface::CreateRHIIndexBufferInternal (FRHICommandListBase & RHICmdList, const TCHAR * InDebugName, const FName & InOwnerName, int32 IndexCount, size_t IndexSize, FResourceArrayInterface * ResourceArray, bool bNeedSRV) static protected
Referenced by FRawStaticIndexBuffer16or32< INDEX_TYPE >::CreateRHIBuffer().
Empty()
virtual void FRawStaticIndexBuffer16or32Interface::Empty (int32 Slack = 0) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
Get()
virtual uint32 FRawStaticIndexBuffer16or32Interface::Get (uint32 Idx) const pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
GetNeedsCPUAccess()
virtual bool FRawStaticIndexBuffer16or32Interface::GetNeedsCPUAccess () const pure virtual
The following methods are basically just accessors that allow us to hide the implementation of FRawStaticIndexBuffer16or32 by making the index array a private member.
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
GetPointerTo()
virtual void * FRawStaticIndexBuffer16or32Interface::GetPointerTo (uint32 Idx) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
GetResourceDataSize()
virtual int32 FRawStaticIndexBuffer16or32Interface::GetResourceDataSize () const pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
GetSRV()
FRHIShaderResourceView * FRawStaticIndexBuffer16or32Interface::GetSRV () const inline
Definition at line 351 of file RawIndexBuffer.h.
References SRVValue.
InitRHIForStreaming()
void FRawStaticIndexBuffer16or32Interface::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, size_t IndexSize, FRHIResourceReplaceBatcher & Batcher) protected
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
References IntermediateBuffer.
Referenced by FRawStaticIndexBuffer16or32< INDEX_TYPE >::InitRHIForStreaming().
Insert()
virtual void FRawStaticIndexBuffer16or32Interface::Insert (int32 Idx, int32 Num = 1) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
References Num().
IsSRVNeeded()
bool FRawStaticIndexBuffer16or32Interface::IsSRVNeeded (bool bAllowCPUAccess) const protected
Referenced by FRawStaticIndexBuffer16or32< INDEX_TYPE >::CreateRHIBuffer(), and FRawStaticIndexBuffer16or32< INDEX_TYPE >::InitRHI().
Num()
virtual int32 FRawStaticIndexBuffer16or32Interface::Num () const pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
Referenced by Insert(), and Remove().
ReleaseRHIForStreaming()
void FRawStaticIndexBuffer16or32Interface::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher) protected
Referenced by FRawStaticIndexBuffer16or32< INDEX_TYPE >::ReleaseRHIForStreaming().
Remove()
virtual void FRawStaticIndexBuffer16or32Interface::Remove (int32 Idx, int32 Num = 1) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
References Num().
Serialize()
virtual void FRawStaticIndexBuffer16or32Interface::Serialize (FArchive & Ar) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
References Ar.
SerializeMetaData()
virtual void FRawStaticIndexBuffer16or32Interface::SerializeMetaData (FArchive & Ar) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
References Ar.
SetMetaData()
virtual void FRawStaticIndexBuffer16or32Interface::SetMetaData (int32 InCachedNumIndices) pure virtual
Implemented in FRawStaticIndexBuffer16or32< INDEX_TYPE >.
Field Documentation
SRVValue
FShaderResourceViewRHIRef FRawStaticIndexBuffer16or32Interface::SRVValue protected
Definition at line 374 of file RawIndexBuffer.h.
Referenced by GetSRV(), FRawStaticIndexBuffer16or32< INDEX_TYPE >::InitRHI(), and FRawStaticIndexBuffer16or32< INDEX_TYPE >::ReleaseRHI().
The documentation for this class was generated from the following file:
RawIndexBuffer.h