Unreal Engine 5.6 C++ API: UE::FPlatformIoDispatcherRequestMgr Class Reference
UE::FPlatformIoDispatcherRequestMgr Class Reference
#include "PlatformIoDispatcherBase.h"
Public Member Functions
FPlatformIoDispatcherRequestMgr ()
void AddFileBlockRequest (FIoPlatformReadRequest &ReadRequest, FIoFileBlockRequest &FileBlockRequest)
FIoPlatformReadRequest & CreateDirectReadRequest (FIoFileReadRequestCompleted &&OnCompleted, FIoBuffer &Dst, uint64 DstSize, uint64 FileOffset, void *UserData)
FIoFileBlockRequest & CreateFileBlockRequest ()
FIoPlatformReadRequest & CreateScatterGatherRequest (FIoFileReadRequestCompleted &&OnCompleted, FIoBuffer &Dst, uint64 DstSize, void *UserData, uint32 FileId)
void Destroy (FIoEncodedBlockRequest &Request)
void Destroy (FIoFileBlockLink *Link)
void Destroy (FIoFileBlockRequest &Request)
void Destroy (FIoPlatformReadRequest &ReadRequest)
FIoFileBlockRequest * GetFileBlockRequest (FIoBlockKey BlockKey)
void GetFileBlockRequests (FIoPlatformReadRequest &ReadRequest, FTempArray< FIoFileBlockRequest * > &OutRequests)
FIoEncodedBlockRequest & GetOrCreateEncodedBlockRequest (FIoBlockKey BlockKey, bool &bCreated)
FIoFileBlockRequest & GetOrCreateFileBlockRequest (FIoPlatformReadRequest &ReadRequest, FIoBlockKey BlockKey, bool &bCreated)
void Lock ()
void Remove (FIoEncodedBlockRequest &Request)
bool TryCancelAllReadRequests (FIoFileHandle FileHandle)
bool TryCancelReadRequest (FIoPlatformReadRequest &ReadRequest, bool &bAnyBlockCancelled)
void Unlock ()
Private Types
using FEncodedBlockLookup = TMap<FIoBlockKey, FIoEncodedBlockRequest*>
using FFileBlockLookup = TMap<FIoBlockKey, FIoFileBlockRequest*>
Private Member Functions
void AddToLink (FIoFileBlockLink *Link, FIoBlockKey FileBlockKey)
Private Attributes
FIoEncodedBlockRequestAllocator EncodedBlockAllocator
FEncodedBlockLookup EncodedBlockLookup
FIoFileBlockRequestAllocator FileBlockAllocator
FIoFileBlockLinkAllocator FileBlockLinkAllocator
FFileBlockLookup FileBlockLookup
UE::FMutex Mutex
FIoPlatformReadRequestAllocator ReadRequestAllocator
Detailed Description
Definition at line 412 of file PlatformIoDispatcherBase.h.
Member Typedef Documentation
FEncodedBlockLookup
using UE::FPlatformIoDispatcherRequestMgr::FEncodedBlockLookup = TMap<FIoBlockKey, FIoEncodedBlockRequest*> private
Definition at line 448 of file PlatformIoDispatcherBase.h.
FFileBlockLookup
using UE::FPlatformIoDispatcherRequestMgr::FFileBlockLookup = TMap<FIoBlockKey, FIoFileBlockRequest*> private
Definition at line 447 of file PlatformIoDispatcherBase.h.
Constructor & Destructor Documentation
FPlatformIoDispatcherRequestMgr()
UE::FPlatformIoDispatcherRequestMgr::FPlatformIoDispatcherRequestMgr ()
Definition at line 533 of file PlatformIoDispatcherBase.cpp.
Member Function Documentation
AddFileBlockRequest()
void UE::FPlatformIoDispatcherRequestMgr::AddFileBlockRequest (FIoPlatformReadRequest & ReadRequest, FIoFileBlockRequest & FileBlockRequest)
Definition at line 728 of file PlatformIoDispatcherBase.cpp.
References AddToLink(), UE::FIoFileBlockRequest::BlockKey, UE::FIoPlatformReadRequest::FScatterGather::FileBlockLink, and UE::FIoPlatformReadRequest::ScatterGather.
AddToLink()
void UE::FPlatformIoDispatcherRequestMgr::AddToLink (FIoFileBlockLink * Link, FIoBlockKey FileBlockKey) private
Definition at line 788 of file PlatformIoDispatcherBase.cpp.
References check, FileBlockLinkAllocator, UE::FIoBlockKey::GetBlockId(), UE::FIoBlockKey::IsValid(), and UE::FIoFileBlockLink::MaxFileCount.
Referenced by AddFileBlockRequest(), and GetOrCreateFileBlockRequest().
CreateDirectReadRequest()
FIoPlatformReadRequest & UE::FPlatformIoDispatcherRequestMgr::CreateDirectReadRequest (FIoFileReadRequestCompleted && OnCompleted, FIoBuffer & Dst, uint64 DstSize, uint64 FileOffset, void * UserData)
Definition at line 554 of file PlatformIoDispatcherBase.cpp.
References MoveTemp(), and ReadRequestAllocator.
CreateFileBlockRequest()
FIoFileBlockRequest & UE::FPlatformIoDispatcherRequestMgr::CreateFileBlockRequest ()
Definition at line 702 of file PlatformIoDispatcherBase.cpp.
References FileBlockAllocator.
CreateScatterGatherRequest()
FIoPlatformReadRequest & UE::FPlatformIoDispatcherRequestMgr::CreateScatterGatherRequest (FIoFileReadRequestCompleted && OnCompleted, FIoBuffer & Dst, uint64 DstSize, void * UserData, uint32 FileId)
Definition at line 537 of file PlatformIoDispatcherBase.cpp.
References MoveTemp(), and ReadRequestAllocator.
Destroy() [1/4]
void UE::FPlatformIoDispatcherRequestMgr::Destroy (FIoEncodedBlockRequest & Request)
Definition at line 769 of file PlatformIoDispatcherBase.cpp.
References EncodedBlockAllocator, UE::FIoEncodedBlockRequest::EncodedData, UE::FIoEncodedBlockRequest::FileBlockCount, and FMemory::Free().
Destroy() [2/4]
void UE::FPlatformIoDispatcherRequestMgr::Destroy (FIoFileBlockLink * Link)
Definition at line 778 of file PlatformIoDispatcherBase.cpp.
References FileBlockLinkAllocator.
Destroy() [3/4]
void UE::FPlatformIoDispatcherRequestMgr::Destroy (FIoFileBlockRequest & Request)
Definition at line 759 of file PlatformIoDispatcherBase.cpp.
References UE::FIoFileBlockRequest::BlockKey, Cancelled, UE::FIoFileBlockRequest::ErrorCode, FileBlockAllocator, and FileBlockLookup.
Destroy() [4/4]
void UE::FPlatformIoDispatcherRequestMgr::Destroy (FIoPlatformReadRequest & ReadRequest)
Definition at line 669 of file PlatformIoDispatcherBase.cpp.
References check, Destroy(), UE::FIoPlatformReadRequest::FScatterGather::FileBlockLink, UE::FIoPlatformReadRequest::IsScatterGather(), UE::FIoFileBlockLink::NextLink, ReadRequestAllocator, UE::FIoPlatformReadRequest::RefCount, and UE::FIoPlatformReadRequest::ScatterGather.
Referenced by Destroy().
GetFileBlockRequest()
FIoFileBlockRequest * UE::FPlatformIoDispatcherRequestMgr::GetFileBlockRequest (FIoBlockKey BlockKey)
Definition at line 707 of file PlatformIoDispatcherBase.cpp.
References FileBlockLookup.
GetFileBlockRequests()
void UE::FPlatformIoDispatcherRequestMgr::GetFileBlockRequests (FIoPlatformReadRequest & ReadRequest, FTempArray< FIoFileBlockRequest * > & OutRequests)
Definition at line 712 of file PlatformIoDispatcherBase.cpp.
References TArray< InElementType, InAllocatorType >::Add(), check, UE::FIoPlatformReadRequest::FScatterGather::FileBlockLink, FileBlockLookup, UE::FIoPlatformReadRequest::FScatterGather::FileId, and UE::FIoPlatformReadRequest::ScatterGather.
GetOrCreateEncodedBlockRequest()
FIoEncodedBlockRequest & UE::FPlatformIoDispatcherRequestMgr::GetOrCreateEncodedBlockRequest (FIoBlockKey BlockKey, bool & bCreated)
Definition at line 733 of file PlatformIoDispatcherBase.cpp.
References UE::FIoEncodedBlockRequest::BlockKey, check, EncodedBlockAllocator, EncodedBlockLookup, and UE::FIoBlockKey::IsValid().
GetOrCreateFileBlockRequest()
FIoFileBlockRequest & UE::FPlatformIoDispatcherRequestMgr::GetOrCreateFileBlockRequest (FIoPlatformReadRequest & ReadRequest, FIoBlockKey BlockKey, bool & bCreated)
Definition at line 682 of file PlatformIoDispatcherBase.cpp.
References AddToLink(), UE::FIoFileBlockRequest::BlockKey, check, FileBlockAllocator, UE::FIoPlatformReadRequest::FScatterGather::FileBlockLink, FileBlockLookup, UE::FIoBlockKey::IsValid(), and UE::FIoPlatformReadRequest::ScatterGather.
Lock()
void UE::FPlatformIoDispatcherRequestMgr::Lock () inline
Definition at line 442 of file PlatformIoDispatcherBase.h.
References Mutex.
Remove()
void UE::FPlatformIoDispatcherRequestMgr::Remove (FIoEncodedBlockRequest & Request)
Definition at line 750 of file PlatformIoDispatcherBase.cpp.
References UE::FIoEncodedBlockRequest::BlockKey, Cancelled, EncodedBlockLookup, and UE::FIoEncodedBlockRequest::ErrorCode.
TryCancelAllReadRequests()
bool UE::FPlatformIoDispatcherRequestMgr::TryCancelAllReadRequests (FIoFileHandle FileHandle)
Definition at line 636 of file PlatformIoDispatcherBase.cpp.
References TArray< InElementType, InAllocatorType >::Add(), UE::FIoEncodedBlockRequest::BlockKey, Cancelled, EncodedBlockLookup, UE::FIoFileBlockRequest::Enqueued, UE::FIoEncodedBlockRequest::ErrorCode, FileBlockLookup, UE::FIoFileBlockRequest::FileHandle, TArray< InElementType, InAllocatorType >::IsEmpty(), UE::FIoFileBlockRequest::QueueStatus, UE::FIoEncodedBlockRequest::ScatterTargets, and UE::FIoEncodedBlockRequest::FScatterTarget::SizeInBlock.
TryCancelReadRequest()
bool UE::FPlatformIoDispatcherRequestMgr::TryCancelReadRequest (FIoPlatformReadRequest & ReadRequest, bool & bAnyBlockCancelled)
Definition at line 571 of file PlatformIoDispatcherBase.cpp.
References UE::FIoEncodedBlockRequest::BlockKey, UE::FIoFileBlockRequest::BlockKey, Cancelled, check, UE::FIoFileBlockRequest::Dequeued, EncodedBlockLookup, UE::FIoFileBlockRequest::EncodedBlockRequests, UE::FIoEncodedBlockRequest::ErrorCode, UE::FIoFileBlockRequest::ErrorCode, UE::FIoPlatformReadRequest::FScatterGather::FileBlockLink, FileBlockLookup, UE::FIoPlatformReadRequest::FScatterGather::FileId, UE::FIoPlatformReadRequest::IsScatterGather(), UE::FIoFileBlockRequest::QueueStatus, UE::FIoPlatformReadRequest::FScatterGather::RemainingBlocks, UE::FIoEncodedBlockRequest::FScatterTarget::Request, UE::FIoPlatformReadRequest::ScatterGather, UE::FIoEncodedBlockRequest::ScatterTargets, and UE::FIoEncodedBlockRequest::FScatterTarget::SizeInBlock.
Unlock()
void UE::FPlatformIoDispatcherRequestMgr::Unlock () inline
Definition at line 443 of file PlatformIoDispatcherBase.h.
References Mutex.
Field Documentation
EncodedBlockAllocator
FIoEncodedBlockRequestAllocator UE::FPlatformIoDispatcherRequestMgr::EncodedBlockAllocator private
Definition at line 454 of file PlatformIoDispatcherBase.h.
Referenced by Destroy(), and GetOrCreateEncodedBlockRequest().
EncodedBlockLookup
FEncodedBlockLookup UE::FPlatformIoDispatcherRequestMgr::EncodedBlockLookup private
Definition at line 455 of file PlatformIoDispatcherBase.h.
Referenced by GetOrCreateEncodedBlockRequest(), Remove(), TryCancelAllReadRequests(), and TryCancelReadRequest().
FileBlockAllocator
FIoFileBlockRequestAllocator UE::FPlatformIoDispatcherRequestMgr::FileBlockAllocator private
Definition at line 451 of file PlatformIoDispatcherBase.h.
Referenced by CreateFileBlockRequest(), Destroy(), and GetOrCreateFileBlockRequest().
FileBlockLinkAllocator
FIoFileBlockLinkAllocator UE::FPlatformIoDispatcherRequestMgr::FileBlockLinkAllocator private
Definition at line 453 of file PlatformIoDispatcherBase.h.
Referenced by AddToLink(), and Destroy().
FileBlockLookup
FFileBlockLookup UE::FPlatformIoDispatcherRequestMgr::FileBlockLookup private
Definition at line 452 of file PlatformIoDispatcherBase.h.
Referenced by Destroy(), GetFileBlockRequest(), GetFileBlockRequests(), GetOrCreateFileBlockRequest(), TryCancelAllReadRequests(), and TryCancelReadRequest().
Mutex
UE::FMutex UE::FPlatformIoDispatcherRequestMgr::Mutex private
Definition at line 456 of file PlatformIoDispatcherBase.h.
Referenced by Lock(), and Unlock().
ReadRequestAllocator
FIoPlatformReadRequestAllocator UE::FPlatformIoDispatcherRequestMgr::ReadRequestAllocator private
Definition at line 450 of file PlatformIoDispatcherBase.h.
Referenced by CreateDirectReadRequest(), CreateScatterGatherRequest(), and Destroy().
The documentation for this class was generated from the following files:
PlatformIoDispatcherBase.h
PlatformIoDispatcherBase.cpp