Unreal Engine 5.6 C++ API: TStateTreeStrongExecutionContext< bWithWriteAccess > Struct Template Reference
TStateTreeStrongExecutionContext< bWithWriteAccess > Struct Template Reference
Execution context to interact with the state tree instance data asynchronously.
#include "StateTreeAsyncExecutionContext.h"
Public Member Functions
TStateTreeStrongExecutionContext ()=default
STATETREEMODULE_API TStateTreeStrongExecutionContext (const FStateTreeWeakExecutionContext &WeakContext)
TStateTreeStrongExecutionContext (const TStateTreeStrongExecutionContext &Other)=delete
STATETREEMODULE_API ~TStateTreeStrongExecutionContext ()
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
bool BindDelegate (const FStateTreeDelegateListener &Listener, FSimpleDelegate Delegate) const
Registers the delegate to the listener.
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
bool BroadcastDelegate (const FStateTreeDelegateDispatcher &Dispatcher) const
Broadcasts the delegate.
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
bool FinishTask (EStateTreeFinishTaskType FinishType) const
Finishes a task.
STATETREEMODULE_API UE::StateTree::Async::FActivePathInfo GetActivePathInfo () const
Get the info of active frame, state and node this Context is based on.
template<typename T>
std::conditional_t< bWithWriteAccess, T *, const T * > GetInstanceDataPtr () const
Get the Instance Data of recorded node.
TStrongObjectPtr< UObject > GetOwner () const
TStrongObjectPtr< const UStateTree > GetStateTree () const
TSharedPtr< const FStateTreeInstanceStorage > GetStorage () const
bool IsValid () const
Checks if the context is valid.
TStateTreeStrongExecutionContext & operator= (const TStateTreeStrongExecutionContext &Other)=delete
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
bool RequestTransition (FStateTreeStateHandle TargetState, EStateTreeTransitionPriority Priority=EStateTreeTransitionPriority::Normal, EStateTreeSelectionFallback Fallback=EStateTreeSelectionFallback::None) const
Requests transition to a state.
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
bool SendEvent (const FGameplayTag Tag, const FConstStructView Payload=FConstStructView(), const FName Origin=FName()) const
Sends event for the StateTree.
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
bool UnbindDelegate (const FStateTreeDelegateListener &Listener) const
Unregisters the callback bound to the listener.
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
bool UpdateScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle, FStateTreeScheduledTick ScheduledTick) const
Updates the scheduled tick of a previous request.
Private Member Functions
STATETREEMODULE_API FStateTreeDataView GetInstanceDataPtrInternal () const
bool IsValidInstanceStorage () const
Static Private Member Functions
template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)>
static void ScheduleNextTick (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > RootStateTree, FStateTreeInstanceStorage &Storage)
Private Attributes
uint8 bAccessAcquired: 1 = false
UE::StateTree::FActiveFrameID FrameID
FStateTreeIndex16 NodeIndex
TStrongObjectPtr< UObject > Owner
UE::StateTree::FActiveStateID StateID
TStrongObjectPtr< const UStateTree > StateTree
TSharedPtr< FStateTreeInstanceStorage > Storage
Friends
struct FStateTreePropertyRef
Detailed Description
template<bool bWithWriteAccess>
struct TStateTreeStrongExecutionContext< bWithWriteAccess >
Execution context to interact with the state tree instance data asynchronously.
It should only be allocated on the stack. You are responsible for making it thread-safe if needed. ThreadSafeAsyncCallback.AddLambda([MyTag, WeakContext = Context.MakeWeakExecutionContext()]() { TStateTreeStrongExecutionContext<true> StrongContext = WeakContext.CreateStrongContext(); if (StrongContext.SendEvent()) { ... } });
Definition at line 59 of file StateTreeAsyncExecutionContext.h.
Constructor & Destructor Documentation
TStateTreeStrongExecutionContext() [1/3]
template<bool bWithWriteAccess> TStateTreeStrongExecutionContext< bWithWriteAccess >::TStateTreeStrongExecutionContext () default
TStateTreeStrongExecutionContext() [2/3]
template<bool bWithWriteAccess> STATETREEMODULE_API TStateTreeStrongExecutionContext< bWithWriteAccess >::TStateTreeStrongExecutionContext (const FStateTreeWeakExecutionContext & WeakContext) explicit
~TStateTreeStrongExecutionContext()
template<bool bWithWriteAccess> STATETREEMODULE_API TStateTreeStrongExecutionContext< bWithWriteAccess >::~TStateTreeStrongExecutionContext ()
TStateTreeStrongExecutionContext() [3/3]
template<bool bWithWriteAccess> TStateTreeStrongExecutionContext< bWithWriteAccess >::TStateTreeStrongExecutionContext (const TStateTreeStrongExecutionContext< bWithWriteAccess > & Other) delete
Member Function Documentation
BindDelegate()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::BindDelegate (const FStateTreeDelegateListener & Listener, FSimpleDelegate Delegate) const
Registers the delegate to the listener.
If the listener was previously registered, then unregister it first before registering it again with the new delegate callback. The listener is bound to a dispatcher in the editor.
Returns
false if the context is not valid or doesn't have a valid frame anymore or the bind failed.
BroadcastDelegate()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::BroadcastDelegate (const FStateTreeDelegateDispatcher & Dispatcher) const
Broadcasts the delegate.
It executes bound delegates immediately and triggers bound transitions (when transitions are evaluated).
Returns
false if the context is not valid or doesn't have a valid frame anymore or the broadcast failed.
FinishTask()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::FinishTask (EStateTreeFinishTaskType FinishType) const
Finishes a task.
If called during tick processing, then the state completes immediately. If called outside of the tick processing, then the request is buffered and handled on the next tick.
Returns
false if the context is not valid or doesn't have a valid frame anymore or finish task failed.
GetActivePathInfo()
template<bool bWithWriteAccess> STATETREEMODULE_API UE::StateTree::Async::FActivePathInfo TStateTreeStrongExecutionContext< bWithWriteAccess >::GetActivePathInfo () const
Get the info of active frame, state and node this Context is based on.
Returns
an invalid FActivePathInfo if the frame or state containing the node is no longer active.
Referenced by TStateTreeStrongExecutionContext< true >::IsValid().
GetInstanceDataPtr()
template<bool bWithWriteAccess> template<typename T> std::conditional_t< bWithWriteAccess, T *, const T * > TStateTreeStrongExecutionContext< bWithWriteAccess >::GetInstanceDataPtr () const inline
Get the Instance Data of recorded node.
Returns
nullptr if the frame or state containing the node is no longer active.
Definition at line 153 of file StateTreeAsyncExecutionContext.h.
GetInstanceDataPtrInternal()
template<bool bWithWriteAccess> STATETREEMODULE_API FStateTreeDataView TStateTreeStrongExecutionContext< bWithWriteAccess >::GetInstanceDataPtrInternal () const private
Referenced by TStateTreeStrongExecutionContext< true >::GetInstanceDataPtr().
GetOwner()
template<bool bWithWriteAccess> TStrongObjectPtr< UObject > TStateTreeStrongExecutionContext< bWithWriteAccess >::GetOwner () const inline
Returns
The owner of the context
Definition at line 69 of file StateTreeAsyncExecutionContext.h.
GetStateTree()
template<bool bWithWriteAccess> TStrongObjectPtr< const UStateTree > TStateTreeStrongExecutionContext< bWithWriteAccess >::GetStateTree () const inline
Returns
the StateTree asset in use.
Definition at line 75 of file StateTreeAsyncExecutionContext.h.
GetStorage()
template<bool bWithWriteAccess> TSharedPtr< const FStateTreeInstanceStorage > TStateTreeStrongExecutionContext< bWithWriteAccess >::GetStorage () const inline
Returns
the Instance Storage.
Definition at line 81 of file StateTreeAsyncExecutionContext.h.
IsValid()
template<bool bWithWriteAccess> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::IsValid () const inline
Checks if the context is valid.
Validity: Pinned Members are valid AND (WeakContext is created outside the ExecContext loop OR the recorded frame and state are still active)
Returns
false if the context is not valid.
Definition at line 175 of file StateTreeAsyncExecutionContext.h.
Referenced by TStateTreeStrongExecutionContext< true >::IsValid().
IsValidInstanceStorage()
template<bool bWithWriteAccess> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::IsValidInstanceStorage () const inline private
Definition at line 182 of file StateTreeAsyncExecutionContext.h.
Referenced by TStateTreeStrongExecutionContext< true >::IsValid().
operator=()
template<bool bWithWriteAccess> TStateTreeStrongExecutionContext & TStateTreeStrongExecutionContext< bWithWriteAccess >::operator= (const TStateTreeStrongExecutionContext< bWithWriteAccess > & Other) delete
RequestTransition()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::RequestTransition (FStateTreeStateHandle TargetState, EStateTreeTransitionPriority Priority = EStateTreeTransitionPriority::Normal, EStateTreeSelectionFallback Fallback = EStateTreeSelectionFallback::None) const
Requests transition to a state.
If called during transition processing (e.g. from FStateTreeTaskBase::TriggerTransitions()) the transition is attempted to be activated immediately (it can fail e.g. because of preconditions on a target state). If called outside the transition handling, the request is buffered and handled at the beginning of next transition processing.
Parameters
TargetState The state to transition to.
Priority The priority of the transition.
Fallback of the transition if it fails to select the target state.
Returns
false if the context is not valid or doesn't have a valid frame anymore or the request failed.
ScheduleNextTick()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> void TStateTreeStrongExecutionContext< bWithWriteAccess >::ScheduleNextTick (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > RootStateTree, FStateTreeInstanceStorage & Storage) static private
SendEvent()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::SendEvent (const FGameplayTag Tag, const FConstStructView Payload = FConstStructView(), const FName Origin = FName()) const
Sends event for the StateTree.
Returns
false if the context is not valid or the event could not be sent.
UnbindDelegate()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::UnbindDelegate (const FStateTreeDelegateListener & Listener) const
Unregisters the callback bound to the listener.
Returns
false if the context is not valid or the unbind failed.
UpdateScheduledTickRequest()
template<bool bWithWriteAccess> template<bool bWriteAccess = bWithWriteAccess UE_REQUIRES(bWriteAccess)> bool TStateTreeStrongExecutionContext< bWithWriteAccess >::UpdateScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle, FStateTreeScheduledTick ScheduledTick) const
Updates the scheduled tick of a previous request.
Returns
false if the context is not valid.
Friends And Related Symbol Documentation
FStateTreePropertyRef
template<bool bWithWriteAccess> friend struct FStateTreePropertyRef friend
Definition at line 201 of file StateTreeAsyncExecutionContext.h.
Field Documentation
bAccessAcquired
template<bool bWithWriteAccess> uint8 TStateTreeStrongExecutionContext< bWithWriteAccess >::bAccessAcquired private
Definition at line 199 of file StateTreeAsyncExecutionContext.h.
FrameID
template<bool bWithWriteAccess> UE::StateTree::FActiveFrameID TStateTreeStrongExecutionContext< bWithWriteAccess >::FrameID private
Definition at line 196 of file StateTreeAsyncExecutionContext.h.
NodeIndex
template<bool bWithWriteAccess> FStateTreeIndex16 TStateTreeStrongExecutionContext< bWithWriteAccess >::NodeIndex private
Definition at line 198 of file StateTreeAsyncExecutionContext.h.
Owner
template<bool bWithWriteAccess> TStrongObjectPtr<UObject> TStateTreeStrongExecutionContext< bWithWriteAccess >::Owner private
Definition at line 192 of file StateTreeAsyncExecutionContext.h.
StateID
template<bool bWithWriteAccess> UE::StateTree::FActiveStateID TStateTreeStrongExecutionContext< bWithWriteAccess >::StateID private
Definition at line 197 of file StateTreeAsyncExecutionContext.h.
StateTree
template<bool bWithWriteAccess> TStrongObjectPtr<const UStateTree> TStateTreeStrongExecutionContext< bWithWriteAccess >::StateTree private
Definition at line 193 of file StateTreeAsyncExecutionContext.h.
Storage
template<bool bWithWriteAccess> TSharedPtr<FStateTreeInstanceStorage> TStateTreeStrongExecutionContext< bWithWriteAccess >::Storage private
Definition at line 194 of file StateTreeAsyncExecutionContext.h.
The documentation for this struct was generated from the following files:
StateTree.h
StateTreeAsyncExecutionContext.h