Unreal Engine 5.6 C++ API: FRigVMTreeFilter Class Reference
FRigVMTreeFilter Class Reference
A Filter is used to hide elements from a tree.
#include "RigVMTreeToolkitFilter.h"
Public Types
typedef FRigVMTreeElement Super
Public Member Functions
virtual bool CanBeToggledInUI () const
virtual bool Filters (TSharedRef< FRigVMTreeNode > &InNode, const TSharedRef< FRigVMTreeContext > &InContext)
virtual FText GetLabel () const
virtual FText GetToolTip () const
virtual FName GetType () const override
virtual uint32 GetVisibleChildrenHash () const
bool IsEnabled () const
virtual bool IsInvertedInUI () const
virtual bool IsOfType (const FName &InType) const override
void SetEnabled (bool InEnabled)
TSharedPtr< FRigVMTreeFilter > ToSharedPtr () const
TSharedRef< FRigVMTreeFilter > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename... Types>
static TSharedRef< FRigVMTreeFilter > Create (Types... Args)
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeFilter"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Private Attributes
bool bEnabled = true
Friends
template<typename T>
TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeFilter > &InElement)
template<typename T>
const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeFilter > &InElement)
Additional Inherited Members
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A Filter is used to hide elements from a tree.
Filters can be used to filter by folder, filter by tags or anything else.
Definition at line 15 of file RigVMTreeToolkitFilter.h.
Member Typedef Documentation
Super
typedef FRigVMTreeElement FRigVMTreeFilter::Super
Definition at line 18 of file RigVMTreeToolkitFilter.h.
Member Function Documentation
CanBeToggledInUI()
virtual bool FRigVMTreeFilter::CanBeToggledInUI () const inline virtual
Reimplemented in FRigVMTreeAssetVariantFilter, FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, FRigVMTreeFunctionVariantFilter, and FRigVMTreeFunctionWithNoRefsFilter.
Definition at line 20 of file RigVMTreeToolkitFilter.h.
References CanBeToggledInUI().
Referenced by CanBeToggledInUI().
Create()
template<typename... Types> TSharedRef< FRigVMTreeFilter > FRigVMTreeFilter::Create (Types... Args) inline static
Definition at line 18 of file RigVMTreeToolkitFilter.h.
Filters()
virtual bool FRigVMTreeFilter::Filters (TSharedRef< FRigVMTreeNode > & InNode, const TSharedRef< FRigVMTreeContext > & InContext) virtual
Reimplemented in FRigVMTreeAssetVariantFilter, FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, FRigVMTreeFunctionVariantFilter, FRigVMTreeFunctionWithNoRefsFilter, and FRigVMTreePathFilter.
GetLabel()
virtual FText FRigVMTreeFilter::GetLabel () const inline virtual
Reimplemented in FRigVMTreeAssetVariantFilter, FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, FRigVMTreeFunctionVariantFilter, and FRigVMTreeFunctionWithNoRefsFilter.
Definition at line 30 of file RigVMTreeToolkitFilter.h.
GetToolTip()
virtual FText FRigVMTreeFilter::GetToolTip () const inline virtual
Definition at line 35 of file RigVMTreeToolkitFilter.h.
GetType()
virtual FName FRigVMTreeFilter::GetType () const inline override virtual
Reimplemented from FRigVMTreeElement.
Reimplemented in FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, and FRigVMTreePathFilter.
Definition at line 18 of file RigVMTreeToolkitFilter.h.
GetVisibleChildrenHash()
virtual uint32 FRigVMTreeFilter::GetVisibleChildrenHash () const virtual
Reimplemented in FRigVMTreePathFilter.
IsEnabled()
bool FRigVMTreeFilter::IsEnabled () const inline
Definition at line 44 of file RigVMTreeToolkitFilter.h.
References bEnabled.
IsInvertedInUI()
virtual bool FRigVMTreeFilter::IsInvertedInUI () const inline virtual
Reimplemented in FRigVMTreeAssetVariantFilter, FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, FRigVMTreeFunctionVariantFilter, and FRigVMTreeFunctionWithNoRefsFilter.
Definition at line 25 of file RigVMTreeToolkitFilter.h.
IsOfType()
virtual bool FRigVMTreeFilter::IsOfType (const FName & InType) const inline override virtual
Reimplemented from FRigVMTreeElement.
Reimplemented in FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, and FRigVMTreePathFilter.
Definition at line 18 of file RigVMTreeToolkitFilter.h.
SetEnabled()
void FRigVMTreeFilter::SetEnabled (bool InEnabled) inline
Definition at line 49 of file RigVMTreeToolkitFilter.h.
References bEnabled.
ToSharedPtr()
TSharedPtr< FRigVMTreeFilter > FRigVMTreeFilter::ToSharedPtr () const inline
Definition at line 18 of file RigVMTreeToolkitFilter.h.
ToSharedRef()
TSharedRef< FRigVMTreeFilter > FRigVMTreeFilter::ToSharedRef () const inline
Definition at line 18 of file RigVMTreeToolkitFilter.h.
Friends And Related Symbol Documentation
Cast
template<typename T> TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeFilter > & InElement) friend
Definition at line 18 of file RigVMTreeToolkitFilter.h.
References FRigVMTreeElement::FRigVMTreeElement().
CastChecked
template<typename T> const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeFilter > & InElement) friend
Definition at line 18 of file RigVMTreeToolkitFilter.h.
Field Documentation
bEnabled
bool FRigVMTreeFilter::bEnabled = true private
Definition at line 55 of file RigVMTreeToolkitFilter.h.
Referenced by IsEnabled(), and SetEnabled().
Type
const FLazyName FRigVMTreeFilter::Type = FLazyName(TEXT("FRigVMTreeFilter")) inline static
Definition at line 18 of file RigVMTreeToolkitFilter.h.
The documentation for this class was generated from the following file:
RigVMTreeToolkitFilter.h