Unreal Engine 5.6 C++ API: TBasicArray< T > Class Template Reference
TBasicArray< T > Class Template Reference
Basic RAII array which can be used without the excessive dependencies needed by TArray, which needs to be serialisable, have a fixed ABI, have lots of helper algorithms as members, have auto-shrinking, support allocators etc.
#include "BasicArray.h"
Data Structures
struct FData
Public Member Functions
TBasicArray ()
TBasicArray (const TBasicArray &)=delete
TBasicArray (TBasicArray &&Other)
~TBasicArray ()
template<typename... ArgTypes>
int32 Emplace (ArgTypes &&... Args)
template<typename... ArgTypes>
void EmplaceAt (int32 Index, ArgTypes &&... Args)
T * GetData ()
FORCEINLINE const T * GetData () const
bool IsEmpty () const
int32 Num () const
TBasicArray & operator= (const TBasicArray &)=delete
TBasicArray & operator= (TBasicArray &&Other)
FORCEINLINE T & operator[] (int32 Index)
FORCEINLINE const T & operator[] (int32 Index) const
void RemoveAt (int32 Index, int32 NumToRemove=1)
Private Member Functions
void * InsertUninitialized (int32 IndexToAdd)
Static Private Member Functions
static FORCEINLINE int32 ApplyGrowthFactor (int32 CurrentNum)
Private Attributes
FData * Data
Static Private Attributes
static constexpr int32 InitialReservationSize = 16
Friends
const T * begin (const TBasicArray &Arr)
T * begin (TBasicArray &Arr)
const T * end (const TBasicArray &Arr)
T * end (TBasicArray &Arr)
Detailed Description
template<typename T>
class TBasicArray< T >
Basic RAII array which can be used without the excessive dependencies needed by TArray, which needs to be serialisable, have a fixed ABI, have lots of helper algorithms as members, have auto-shrinking, support allocators etc.
Definition at line 21 of file BasicArray.h.
Constructor & Destructor Documentation
TBasicArray() [1/3]
template<typename T> TBasicArray< T >::TBasicArray () inline nodiscard
Definition at line 24 of file BasicArray.h.
References Data.
Referenced by TBasicArray(), TBasicArray(), begin, begin, end, end, GetData(), operator=(), and operator=().
TBasicArray() [2/3]
template<typename T> TBasicArray< T >::TBasicArray (const TBasicArray< T > &) delete
References TBasicArray().
TBasicArray() [3/3]
template<typename T> TBasicArray< T >::TBasicArray (TBasicArray< T > && Other) inline nodiscard
Definition at line 33 of file BasicArray.h.
References TBasicArray(), Data, and Other.
~TBasicArray()
template<typename T> TBasicArray< T >::~TBasicArray () inline
Definition at line 50 of file BasicArray.h.
References Data, DestructItems(), and FMemory::Free().
Member Function Documentation
ApplyGrowthFactor()
template<typename T> FORCEINLINE int32 TBasicArray< T >::ApplyGrowthFactor (int32 CurrentNum) inline static private
Definition at line 126 of file BasicArray.h.
References FORCEINLINE.
Referenced by InsertUninitialized().
Emplace()
template<typename T> template<typename... ArgTypes> int32 TBasicArray< T >::Emplace (ArgTypes &&... Args) inline
Definition at line 60 of file BasicArray.h.
References Forward(), InsertUninitialized(), and Num().
EmplaceAt()
template<typename T> template<typename... ArgTypes> void TBasicArray< T >::EmplaceAt (int32 Index, ArgTypes &&... Args) inline
Definition at line 71 of file BasicArray.h.
References Forward(), and InsertUninitialized().
GetData() [1/2]
template<typename T> T * TBasicArray< T >::GetData () inline nodiscard
Definition at line 102 of file BasicArray.h.
References Data, and TBasicArray< T >::FData::Data.
Referenced by begin, begin, end, end, GetData(), operator[](), and operator[]().
GetData() [2/2]
template<typename T> FORCEINLINE const T * TBasicArray< T >::GetData () const inline nodiscard
Definition at line 108 of file BasicArray.h.
References TBasicArray(), FORCEINLINE, and GetData().
InsertUninitialized()
template<typename T> void * TBasicArray< T >::InsertUninitialized (int32 IndexToAdd) inline private
Definition at line 131 of file BasicArray.h.
References ApplyGrowthFactor(), Data, TBasicArray< T >::FData::Data, InitialReservationSize, TBasicArray< T >::FData::Max, TBasicArray< T >::FData::Num, and RelocateConstructItems().
Referenced by Emplace(), and EmplaceAt().
IsEmpty()
template<typename T> bool TBasicArray< T >::IsEmpty () const inline nodiscard
Definition at line 91 of file BasicArray.h.
References Num().
Num()
template<typename T> int32 TBasicArray< T >::Num () const inline nodiscard
Definition at line 96 of file BasicArray.h.
References Data, and TBasicArray< T >::FData::Num.
Referenced by Emplace(), end, end, and IsEmpty().
operator=() [1/2]
template<typename T> TBasicArray & TBasicArray< T >::operator= (const TBasicArray< T > &) delete
References TBasicArray().
operator=() [2/2]
template<typename T> TBasicArray & TBasicArray< T >::operator= (TBasicArray< T > && Other) inline
Definition at line 39 of file BasicArray.h.
References TBasicArray(), Data, MoveTemp(), and Other.
operator[]() [1/2]
template<typename T> FORCEINLINE T & TBasicArray< T >::operator[] (int32 Index) inline nodiscard
Definition at line 113 of file BasicArray.h.
References FORCEINLINE, and GetData().
operator[]() [2/2]
template<typename T> FORCEINLINE const T & TBasicArray< T >::operator[] (int32 Index) const inline nodiscard
Definition at line 118 of file BasicArray.h.
References FORCEINLINE, and GetData().
RemoveAt()
template<typename T> void TBasicArray< T >::RemoveAt (int32 Index, int32 NumToRemove = 1) inline
Definition at line 77 of file BasicArray.h.
References Data, TBasicArray< T >::FData::Data, DestructItems(), TBasicArray< T >::FData::Num, and RelocateConstructItems().
Friends And Related Symbol Documentation
begin [1/2]
template<typename T> const T * begin (const TBasicArray< T > & Arr) friend
Definition at line 175 of file BasicArray.h.
References TBasicArray(), and GetData().
begin [2/2]
template<typename T> T * begin (TBasicArray< T > & Arr) friend
Definition at line 174 of file BasicArray.h.
References TBasicArray(), and GetData().
end [1/2]
template<typename T> const T * end (const TBasicArray< T > & Arr) friend
Definition at line 177 of file BasicArray.h.
References TBasicArray(), GetData(), and Num().
end [2/2]
template<typename T> T * end (TBasicArray< T > & Arr) friend
Definition at line 176 of file BasicArray.h.
References TBasicArray(), GetData(), and Num().
Field Documentation
Data
template<typename T> FData* TBasicArray< T >::Data private
Definition at line 172 of file BasicArray.h.
Referenced by TBasicArray(), TBasicArray(), ~TBasicArray(), GetData(), InsertUninitialized(), Num(), operator=(), and RemoveAt().
InitialReservationSize
template<typename T> int32 TBasicArray< T >::InitialReservationSize = 16 static constexpr private
Definition at line 124 of file BasicArray.h.
Referenced by InsertUninitialized().
The documentation for this class was generated from the following file:
BasicArray.h