Unreal Engine 5.6 C++ API: WorldFolders.h File Reference
WorldFolders.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/WeakObjectPtr.h"
#include "Misc/Guid.h"
#include "WorldFoldersImplementation.h"
#include "WorldPersistentFolders.h"
#include "WorldTransientFolders.h"
#include "WorldFolders.generated.h"
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogWorldFolders, Log, All) USTRUCT() struct FActorFolderProps
USTRUCT () struct FActorPlacementFolder
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogWorldFolders , Log , All)
Definition at line 15 of file WorldFolders.h.
References All, Ar, FORCEINLINE, GENERATED_USTRUCT_BODY, Log, and operator<<().
USTRUCT()
USTRUCT ()
Definition at line 32 of file WorldFolders.h.
References GENERATED_BODY, TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), FFolder::GetActorFolderGuid(), FFolder::GetPath(), FFolder::GetRootObjectPtr(), FGuid::Invalidate(), FGuid::IsValid(), operator=(), Path, Reset, TWeakObjectPtr< T, TWeakObjectPtrBase >::Reset(), and UPROPERTY.