Unreal Engine 5.6 C++ API: FTransaction::FObjectRecord Class Reference
FTransaction::FObjectRecord Class Reference
#include "Transactor.h"
Data Structures
class FReader
Transfers data from an array.
struct FSerializedObject
class FWriter
Transfers data to an array.
Public Member Functions
FObjectRecord ()=default
UNREALED_API FObjectRecord (FTransaction *Owner, UObject *InObject, TUniquePtr< FChange > InCustomChange, FScriptArray *InArray, int32 InIndex, int32 InCount, int32 InOper, int32 InElementSize, uint32 InElementAlignment, STRUCT_DC InDefaultConstructor, STRUCT_AR InSerializer, STRUCT_DTOR InDestructor)
UNREALED_API void AddReferencedObjects (FReferenceCollector &Collector)
Used by GC to collect referenced objects.
UNREALED_API bool ContainsPieObject () const
UNREALED_API void Finalize (FTransaction *Owner, UE::Transaction::DiffUtil::FDiffableObjectArchetypeCache &ArchetypeCache, TSharedPtr< ITransactionObjectAnnotation > &OutFinalizedObjectAnnotation)
UNREALED_API UE::Transaction::FDiffableObject GetDiffableObject (TArrayView< const FProperty * > PropertiesToSerialize=TArrayView< const FProperty * >(), UE::Transaction::DiffUtil::EGetDiffableObjectMode ObjectSerializationMode=UE::Transaction::DiffUtil::EGetDiffableObjectMode::SerializeObject) const
UNREALED_API bool HasChanges () const
UNREALED_API bool HasExpired () const
UNREALED_API void Load (FTransaction *Owner)
UNREALED_API void Restore (FTransaction *Owner)
UNREALED_API void Save (FTransaction *Owner)
UNREALED_API void SerializeContents (FArchive &Ar, int32 InOper) const
UNREALED_API void SerializeObject (FArchive &Ar) const
UNREALED_API void Snapshot (FTransaction *Owner, UE::Transaction::DiffUtil::FDiffableObjectArchetypeCache &ArchetypeCache, TArrayView< const FProperty * > Properties)
Data Fields
TArray< const FProperty * > AllPropertiesSnapshot
The combined list of properties that have been passed any Snapshot call for this object (always empty once finalized)
FScriptArray * Array = nullptr
Array: If an array object, reference to script array.
bool bFinalized = false
True if object has been finalized and generated diff data.
bool bHasSerializedObjectChanges = false
True if the serialized object state changed between when the transaction started and when the transaction ended (set once finalized)
bool bRestored = false
True if object has already been restored from data.
bool bWantsBinarySerialization = true
True if record should serialize data as binary blob (more compact).
int32 Count = 0
Array: How many items to record.
TUniquePtr< FChange > CustomChange
Custom change to apply to this object to undo this record.
STRUCT_DC DefaultConstructor
Array: DefaultConstructor for each item in the array.
FTransactionObjectDeltaChange DeltaChange
Delta change information between the diffable state of the object when the transaction started, and the diffable state of the object when the transaction ended.
STRUCT_DTOR Destructor
Array: Destructor for each item in the array.
TUniquePtr< UE::Transaction::FDiffableObject > DiffableObject
The diffable object data (always null once finalized)
TUniquePtr< UE::Transaction::FDiffableObject > DiffableObjectSnapshot
The diffable object data when it was last snapshot (always null once finalized)
uint32 ElementAlignment = 0
Array: Alignment of each item in the array.
int32 ElementSize = 0
Array: Size of each item in the array.
int32 Index = 0
Array: Offset into the array.
UE::Transaction::FPersistentObjectRef Object
The object to track.
TSharedPtr< ITransactionObjectAnnotation > ObjectAnnotationSnapshot
Annotation data the last time the object was snapshot (always null once finalized)
int32 Oper = 0
FSerializedObject SerializedObject
The serialized object data.
FSerializedObject SerializedObjectFlip
The serialized object data that will be used when the transaction is flipped.
STRUCT_AR Serializer
Array: Serializer to use for each item in the array.
Private Member Functions
FObjectRecord (const FObjectRecord &)=delete
FObjectRecord & operator= (const FObjectRecord &)=delete
Detailed Description
Definition at line 42 of file Transactor.h.
Constructor & Destructor Documentation
FObjectRecord() [1/3]
FTransaction::FObjectRecord::FObjectRecord () default
Referenced by FObjectRecord(), operator=(), and FTransaction::FObjectRecord::FReader::Preload().
FObjectRecord() [2/3]
UNREALED_API FTransaction::FObjectRecord::FObjectRecord (FTransaction * Owner, UObject * InObject, TUniquePtr< FChange > InCustomChange, FScriptArray * InArray, int32 InIndex, int32 InCount, int32 InOper, int32 InElementSize, uint32 InElementAlignment, STRUCT_DC InDefaultConstructor, STRUCT_AR InSerializer, STRUCT_DTOR InDestructor)
References FTransaction::FTransaction(), and Owner.
FObjectRecord() [3/3]
FTransaction::FObjectRecord::FObjectRecord (const FObjectRecord &) private delete
References FObjectRecord().
Member Function Documentation
AddReferencedObjects()
UNREALED_API void FTransaction::FObjectRecord::AddReferencedObjects (FReferenceCollector & Collector)
Used by GC to collect referenced objects.
ContainsPieObject()
UNREALED_API bool FTransaction::FObjectRecord::ContainsPieObject () const
Returns
True if this record contains a reference to a pie object
Finalize()
UNREALED_API void FTransaction::FObjectRecord::Finalize (FTransaction * Owner, UE::Transaction::DiffUtil::FDiffableObjectArchetypeCache & ArchetypeCache, TSharedPtr< ITransactionObjectAnnotation > & OutFinalizedObjectAnnotation)
References FTransaction::FTransaction(), and Owner.
GetDiffableObject()
UNREALED_API UE::Transaction::FDiffableObject FTransaction::FObjectRecord::GetDiffableObject (TArrayView< const FProperty * > PropertiesToSerialize = TArrayView< const FProperty * >(), UE::Transaction::DiffUtil::EGetDiffableObjectMode ObjectSerializationMode = UE::Transaction::DiffUtil::EGetDiffableObjectMode::SerializeObject) const
References UE::Transaction::DiffUtil::SerializeObject.
HasChanges()
UNREALED_API bool FTransaction::FObjectRecord::HasChanges () const
Returns
true if the record has a delta change or a custom change
HasExpired()
UNREALED_API bool FTransaction::FObjectRecord::HasExpired () const
Returns
true if the record has a custom change and the change has expired
Load()
UNREALED_API void FTransaction::FObjectRecord::Load (FTransaction * Owner)
References FTransaction::FTransaction(), and Owner.
operator=()
FObjectRecord & FTransaction::FObjectRecord::operator= (const FObjectRecord &) private delete
References FObjectRecord().
Restore()
UNREALED_API void FTransaction::FObjectRecord::Restore (FTransaction * Owner)
References FTransaction::FTransaction(), and Owner.
Save()
UNREALED_API void FTransaction::FObjectRecord::Save (FTransaction * Owner)
References FTransaction::FTransaction(), and Owner.
SerializeContents()
UNREALED_API void FTransaction::FObjectRecord::SerializeContents (FArchive & Ar, int32 InOper) const
References Ar.
SerializeObject()
UNREALED_API void FTransaction::FObjectRecord::SerializeObject (FArchive & Ar) const
References Ar.
Snapshot()
UNREALED_API void FTransaction::FObjectRecord::Snapshot (FTransaction * Owner, UE::Transaction::DiffUtil::FDiffableObjectArchetypeCache & ArchetypeCache, TArrayView< const FProperty * > Properties)
References FTransaction::FTransaction(), and Owner.
Field Documentation
AllPropertiesSnapshot
TArray<const FProperty*> FTransaction::FObjectRecord::AllPropertiesSnapshot
The combined list of properties that have been passed any Snapshot call for this object (always empty once finalized)
Definition at line 135 of file Transactor.h.
Array
FScriptArray* FTransaction::FObjectRecord::Array = nullptr
Array: If an array object, reference to script array.
Definition at line 98 of file Transactor.h.
bFinalized
bool FTransaction::FObjectRecord::bFinalized = false
True if object has been finalized and generated diff data.
Definition at line 119 of file Transactor.h.
bHasSerializedObjectChanges
bool FTransaction::FObjectRecord::bHasSerializedObjectChanges = false
True if the serialized object state changed between when the transaction started and when the transaction ended (set once finalized)
Definition at line 123 of file Transactor.h.
bRestored
bool FTransaction::FObjectRecord::bRestored = false
True if object has already been restored from data.
False otherwise.
Definition at line 117 of file Transactor.h.
bWantsBinarySerialization
bool FTransaction::FObjectRecord::bWantsBinarySerialization = true
True if record should serialize data as binary blob (more compact).
False to use tagged serialization (more robust)
Definition at line 121 of file Transactor.h.
Count
int32 FTransaction::FObjectRecord::Count = 0
Array: How many items to record.
Definition at line 102 of file Transactor.h.
CustomChange
TUniquePtr<FChange> FTransaction::FObjectRecord::CustomChange
Custom change to apply to this object to undo this record.
Executing the undo will return an object that can be used to redo the change.
Definition at line 96 of file Transactor.h.
DefaultConstructor
STRUCT_DC FTransaction::FObjectRecord::DefaultConstructor
Array: DefaultConstructor for each item in the array.
Definition at line 111 of file Transactor.h.
DeltaChange
FTransactionObjectDeltaChange FTransaction::FObjectRecord::DeltaChange
Delta change information between the diffable state of the object when the transaction started, and the diffable state of the object when the transaction ended.
Definition at line 137 of file Transactor.h.
Destructor
STRUCT_DTOR FTransaction::FObjectRecord::Destructor
Array: Destructor for each item in the array.
Definition at line 115 of file Transactor.h.
DiffableObject
TUniquePtr<UE::Transaction::FDiffableObject> FTransaction::FObjectRecord::DiffableObject
The diffable object data (always null once finalized)
Definition at line 129 of file Transactor.h.
DiffableObjectSnapshot
TUniquePtr<UE::Transaction::FDiffableObject> FTransaction::FObjectRecord::DiffableObjectSnapshot
The diffable object data when it was last snapshot (always null once finalized)
Definition at line 131 of file Transactor.h.
ElementAlignment
uint32 FTransaction::FObjectRecord::ElementAlignment = 0
Array: Alignment of each item in the array.
Definition at line 109 of file Transactor.h.
ElementSize
int32 FTransaction::FObjectRecord::ElementSize = 0
Array: Size of each item in the array.
Definition at line 107 of file Transactor.h.
Index
int32 FTransaction::FObjectRecord::Index = 0
Array: Offset into the array.
Definition at line 100 of file Transactor.h.
Object
UE::Transaction::FPersistentObjectRef FTransaction::FObjectRecord::Object
The object to track.
Definition at line 94 of file Transactor.h.
ObjectAnnotationSnapshot
TSharedPtr<ITransactionObjectAnnotation> FTransaction::FObjectRecord::ObjectAnnotationSnapshot
Annotation data the last time the object was snapshot (always null once finalized)
Definition at line 133 of file Transactor.h.
Oper
int32 FTransaction::FObjectRecord::Oper = 0
Todo
document this Array: Operation performed on array: 1 (add/insert), 0 (modify), -1 (remove)?
Definition at line 105 of file Transactor.h.
SerializedObject
FSerializedObject FTransaction::FObjectRecord::SerializedObject
The serialized object data.
Definition at line 125 of file Transactor.h.
SerializedObjectFlip
FSerializedObject FTransaction::FObjectRecord::SerializedObjectFlip
The serialized object data that will be used when the transaction is flipped.
Definition at line 127 of file Transactor.h.
Serializer
STRUCT_AR FTransaction::FObjectRecord::Serializer
Array: Serializer to use for each item in the array.
Definition at line 113 of file Transactor.h.
The documentation for this class was generated from the following file:
Transactor.h