Unreal Engine 5.6 C++ API: Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator > Class Template Reference
Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator > Class Template Reference
#include "RobinHoodHashTable.h"
Public Member Functions
TRobinHoodHashSet ()
TRobinHoodHashSet (const TRobinHoodHashSet &Other)=default
TRobinHoodHashSet (TRobinHoodHashSet &&Other)=default
FindValueType FindOrAdd (const KeyType &Key)
FindValueType FindOrAdd (const KeyType &Key, bool &bIsAlreadyInSet)
FindValueType FindOrAdd (KeyType &&Key)
FindValueType FindOrAdd (KeyType &&Key, bool &bIsAlreadyInSet)
FHashElementId FindOrAddId (const KeyType &Key)
FHashElementId FindOrAddId (const KeyType &Key, bool &bIsAlreadyInSet)
FHashElementId FindOrAddId (KeyType &&Key)
FHashElementId FindOrAddId (KeyType &&Key, bool &bIsAlreadyInSet)
FHashElementId FindOrAddIdByHash (FHashType HashValue, const KeyType &Key)
FHashElementId FindOrAddIdByHash (FHashType HashValue, const KeyType &Key, bool &bIsAlreadyInSet)
FHashElementId FindOrAddIdByHash (FHashType HashValue, KeyType &&Key)
FHashElementId FindOrAddIdByHash (FHashType HashValue, KeyType &&Key, bool &bIsAlreadyInSet)
TRobinHoodHashSet & operator= (const TRobinHoodHashSet &Other)=default
TRobinHoodHashSet & operator= (TRobinHoodHashSet &&Other)=default
Public Member Functions inherited from Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >
FIteratorType begin ()
FConstIteratorType begin () const
bool ContainsElementId (FHashElementId Id) const
void Empty ()
FIteratorType end ()
FConstIteratorType end () const
FindValueType Find (const KeyType &Key)
FindValueTypeConst Find (const KeyType &Key) const
FindValueType FindByHash (const FHashType HashValue, const KeyType &Key)
const FindValueType FindByHash (const FHashType HashValue, const KeyType &Key) const
FHashElementId FindId (const KeyType &Key) const
FHashElementId FindIdByHash (const FHashType HashValue, const KeyType &ComparableKey) const
SizeType GetAllocatedSize () const
ElementType & GetByElementId (FHashElementId Id)
const ElementType & GetByElementId (FHashElementId Id) const
IndexType GetMaxIndex () const
int32 Num () const
bool Remove (const KeyType &Key)
bool RemoveByElementId (FHashElementId Id)
bool RemoveByHash (const FHashType HashValue, const KeyType &ComparableKey)
void Reserve (SizeType ReserveNum)
Private Types
using Base = typename RobinHoodHashTable_Private::TRobinHoodHashTable<KeyType, Unit, Hasher, HashMapAllocator>
using FindValueType = typename Base::FindValueType
using FindValueTypeConst = typename Base::FindValueTypeConst
using IndexType = typename Base::IndexType
using Unit = RobinHoodHashTable_Private::FUnitType
Additional Inherited Members
Static Public Member Functions inherited from Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >
static FHashType ComputeHash (const KeyType &Key)
Protected Types inherited from Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >
using ElementType = typename KeyValueType::ElementType
using FindValueType = typename KeyValueType::FindValueType
using FindValueTypeConst = typename KeyValueType::FindValueTypeConst
using IndexType = uint32
using InlineOneAllocatorType = TInlineAllocator<1, HashMapAllocator>
using KeyValueType = RobinHoodHashTable_Private::TKeyValue<KeyType, ValueType>
using SizeType = SIZE_T
Protected Member Functions inherited from Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >
TRobinHoodHashTable ()
TRobinHoodHashTable (const TRobinHoodHashTable &Other)
TRobinHoodHashTable (TRobinHoodHashTable &&Other)
template<typename DeducedKeyType, typename DeducedValueType>
FindValueType FindOrAdd (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId FindOrAddId (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId FindOrAddIdByHash (FHashType HashValue, DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
void InsertIntoTable (IndexType Index, FHashType Hash)
IndexType ModTableSize (IndexType HashValue) const
TRobinHoodHashTable & operator= (const TRobinHoodHashTable &Other)
TRobinHoodHashTable & operator= (TRobinHoodHashTable &&Other)
template<typename DeducedKeyType, typename DeducedValueType>
FindValueType Update (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId UpdateId (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId UpdateIdByHash (FHashType HashValue, DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
Static Protected Attributes inherited from Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >
static constexpr const IndexType InvalidIndex = ~IndexType(0)
static constexpr const IndexType LoadFactorDivisor = 3
static constexpr const IndexType LoadFactorQuotient = 5
Detailed Description
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator>
class Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >
Definition at line 1418 of file RobinHoodHashTable.h.
Member Typedef Documentation
Base
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> using Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::Base = typename RobinHoodHashTable_Private::TRobinHoodHashTable<KeyType, Unit, Hasher, HashMapAllocator> private
Definition at line 1421 of file RobinHoodHashTable.h.
FindValueType
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> using Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindValueType = typename Base::FindValueType private
Definition at line 1423 of file RobinHoodHashTable.h.
FindValueTypeConst
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> using Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindValueTypeConst = typename Base::FindValueTypeConst private
Definition at line 1424 of file RobinHoodHashTable.h.
IndexType
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> using Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::IndexType = typename Base::IndexType private
Definition at line 1422 of file RobinHoodHashTable.h.
Unit
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> using Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::Unit = RobinHoodHashTable_Private::FUnitType private
Definition at line 1420 of file RobinHoodHashTable.h.
Constructor & Destructor Documentation
TRobinHoodHashSet() [1/3]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::TRobinHoodHashSet () inline
Definition at line 1427 of file RobinHoodHashTable.h.
References TRobinHoodHashSet().
Referenced by TRobinHoodHashSet(), TRobinHoodHashSet(), TRobinHoodHashSet(), operator=(), and operator=().
TRobinHoodHashSet() [2/3]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::TRobinHoodHashSet (const TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator > & Other) default
References TRobinHoodHashSet(), and Other.
TRobinHoodHashSet() [3/3]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::TRobinHoodHashSet (TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator > && Other) default
References TRobinHoodHashSet(), and Other.
Member Function Documentation
FindOrAdd() [1/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FindValueType Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAdd (const KeyType & Key) inline
Definition at line 1491 of file RobinHoodHashTable.h.
References Key.
FindOrAdd() [2/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FindValueType Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAdd (const KeyType & Key, bool & bIsAlreadyInSet) inline
Definition at line 1457 of file RobinHoodHashTable.h.
References Key.
FindOrAdd() [3/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FindValueType Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAdd (KeyType && Key) inline
Definition at line 1497 of file RobinHoodHashTable.h.
References Key, and MoveTemp().
FindOrAdd() [4/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FindValueType Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAdd (KeyType && Key, bool & bIsAlreadyInSet) inline
Definition at line 1462 of file RobinHoodHashTable.h.
References Key, and MoveTemp().
FindOrAddId() [1/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddId (const KeyType & Key) inline
Definition at line 1479 of file RobinHoodHashTable.h.
References Key.
FindOrAddId() [2/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddId (const KeyType & Key, bool & bIsAlreadyInSet) inline
Definition at line 1447 of file RobinHoodHashTable.h.
References Key.
FindOrAddId() [3/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddId (KeyType && Key) inline
Definition at line 1485 of file RobinHoodHashTable.h.
References Key, and MoveTemp().
FindOrAddId() [4/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddId (KeyType && Key, bool & bIsAlreadyInSet) inline
Definition at line 1452 of file RobinHoodHashTable.h.
References Key, and MoveTemp().
FindOrAddIdByHash() [1/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddIdByHash (FHashType HashValue, const KeyType & Key) inline
Definition at line 1467 of file RobinHoodHashTable.h.
References Key.
FindOrAddIdByHash() [2/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddIdByHash (FHashType HashValue, const KeyType & Key, bool & bIsAlreadyInSet) inline
Definition at line 1437 of file RobinHoodHashTable.h.
References Key.
FindOrAddIdByHash() [3/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddIdByHash (FHashType HashValue, KeyType && Key) inline
Definition at line 1473 of file RobinHoodHashTable.h.
References Key, and MoveTemp().
FindOrAddIdByHash() [4/4]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> FHashElementId Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::FindOrAddIdByHash (FHashType HashValue, KeyType && Key, bool & bIsAlreadyInSet) inline
Definition at line 1442 of file RobinHoodHashTable.h.
References Key, and MoveTemp().
operator=() [1/2]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> TRobinHoodHashSet & Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::operator= (const TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator > & Other) default
References TRobinHoodHashSet(), and Other.
operator=() [2/2]
template<typename KeyType, typename Hasher = DefaultKeyFuncs<KeyType, false>, typename HashMapAllocator = FDefaultAllocator> TRobinHoodHashSet & Experimental::TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator >::operator= (TRobinHoodHashSet< KeyType, Hasher, HashMapAllocator > && Other) default
References TRobinHoodHashSet(), and Other.
The documentation for this class was generated from the following file:
RobinHoodHashTable.h