Unreal Engine 5.6 C++ API: FOutputDeviceRedirector Class Reference
FOutputDeviceRedirector Class Reference final
Class used for output redirection to allow logs to show in multiple output devices.
#include "OutputDeviceRedirector.h"
Public Member Functions
FOutputDeviceRedirector ()
Initialization constructor.
~FOutputDeviceRedirector ()
Destructor.
void AddOutputDevice (FOutputDevice *OutputDevice)
Adds an output device to the chain of redirections.
void EnableBacklog (bool bEnable)
Enables or disables the backlog.
void Flush () final
Passes on the flush request to all current output devices.
void FlushThreadedLogs (EOutputDeviceRedirectorFlushOptions Options=EOutputDeviceRedirectorFlushOptions::None)
Flushes lines buffered by secondary threads.
bool IsBacklogEnabled () const
Determine if the backlog is enabled.
bool IsRedirectingTo (FOutputDevice *OutputDevice)
Returns whether an output device is in the list of redirections.
void Panic ()
Attempts to set the calling thread as the panic thread and enable panic mode.
void RedirectLog (const FLazyName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Data)
void RedirectLog (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Data)
Same as Serialize().
void RemoveOutputDevice (FOutputDevice *OutputDevice)
Removes an output device from the chain of redirections.
void Serialize (const TCHAR *Data, ELogVerbosity::Type Verbosity, const FName &Category) final
Serializes the passed in data via all current output devices.
void Serialize (const TCHAR *Data, ELogVerbosity::Type Verbosity, const FName &Category, const double Time) final
Serializes the passed in data via all current output devices.
void SerializeBacklog (FOutputDevice *OutputDevice)
Serializes the current backlog to the specified output device.
void SerializeRecord (const UE::FLogRecord &Record) final
Serializes the log record via all current output devices.
void SetCurrentThreadAsPrimaryThread ()
Sets the current thread to be the thread that redirects logs to buffered output devices.
void TearDown () final
Closes output device and cleans up.
bool TryStartDedicatedPrimaryThread ()
Starts a dedicated primary thread that redirects logs to buffered output devices.
Public Member Functions inherited from FOutputDevice
FOutputDevice ()
FOutputDevice (const FOutputDevice &)
FOutputDevice (FOutputDevice &&)
virtual ~FOutputDevice ()
virtual bool CanBeUsedOnAnyThread () const
virtual bool CanBeUsedOnMultipleThreads () const
virtual bool CanBeUsedOnPanicThread () const
template<typename FmtType, typename... Types>
FORCEINLINE void CategorizedLogf (const FName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
virtual void Dump (class FArchive &Ar)
Dumps the contents of this output device's buffer to an archive (supported by output device that have a memory buffer)
FORCEINLINE bool GetAutoEmitLineTerminator () const
FORCEINLINE bool GetSuppressEventTag () const
virtual bool IsMemoryOnly () const
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const FString &S)
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Str)
void Log (const FString &S)
void Log (const FText &S)
void Log (const TCHAR *S)
void Log (ELogVerbosity::Type Verbosity, const FString &S)
void Log (ELogVerbosity::Type Verbosity, const TCHAR *S)
template<typename FmtType>
void Logf (const FmtType &Fmt)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (const FmtType &Fmt, Types... Args)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
FOutputDevice & operator= (const FOutputDevice &)
FOutputDevice & operator= (FOutputDevice &&)
void SetAutoEmitLineTerminator (bool bInAutoEmitLineTerminator)
void SetSuppressEventTag (bool bInSuppressEventTag)
Static Public Member Functions
static FOutputDeviceRedirector * Get ()
Get the GLog singleton.
Private Attributes
TPimplPtr< UE::Private::FOutputDeviceRedirectorState > State
Additional Inherited Members
Protected Attributes inherited from FOutputDevice
bool bAutoEmitLineTerminator
Whether to output a line-terminator after each log call...
bool bSuppressEventTag
Whether to output the 'Log: ' type front...
Detailed Description
Class used for output redirection to allow logs to show in multiple output devices.
Definition at line 51 of file OutputDeviceRedirector.h.
Constructor & Destructor Documentation
FOutputDeviceRedirector()
FOutputDeviceRedirector::FOutputDeviceRedirector ()
Initialization constructor.
Referenced by Get().
~FOutputDeviceRedirector()
FOutputDeviceRedirector::~FOutputDeviceRedirector ()
Destructor.
Member Function Documentation
AddOutputDevice()
void FOutputDeviceRedirector::AddOutputDevice (FOutputDevice * OutputDevice)
Adds an output device to the chain of redirections.
Parameters
OutputDevice Output device to add.
References FOutputDevice::FOutputDevice().
EnableBacklog()
void FOutputDeviceRedirector::EnableBacklog (bool bEnable)
Enables or disables the backlog.
Parameters
bEnable Starts saving a backlog if true, disables and discards any backlog if false.
Flush()
void FOutputDeviceRedirector::Flush () final virtual
Passes on the flush request to all current output devices.
Reimplemented from FOutputDevice.
FlushThreadedLogs()
void FOutputDeviceRedirector::FlushThreadedLogs (EOutputDeviceRedirectorFlushOptions Options = EOutputDeviceRedirectorFlushOptions::None)
Flushes lines buffered by secondary threads.
References None.
Get()
FOutputDeviceRedirector * FOutputDeviceRedirector::Get () static
Get the GLog singleton.
References FOutputDeviceRedirector().
IsBacklogEnabled()
bool FOutputDeviceRedirector::IsBacklogEnabled () const
Determine if the backlog is enabled.
References IsBacklogEnabled().
Referenced by IsBacklogEnabled().
IsRedirectingTo()
bool FOutputDeviceRedirector::IsRedirectingTo (FOutputDevice * OutputDevice)
Returns whether an output device is in the list of redirections.
Parameters
OutputDevice Output device to check the list against.
Returns
true if messages are currently redirected to the the passed in output device, false otherwise.
References FOutputDevice::FOutputDevice().
Panic()
void FOutputDeviceRedirector::Panic ()
Attempts to set the calling thread as the panic thread and enable panic mode.
Only one thread can be the panic thread. Subsequent calls from other threads are ignored. Only redirects logs to panic-safe output devices from this point forward. Makes the calling thread the primary log thread as well. Flushes buffered logs to panic-safe output devices. Flushes panic-safe output devices.
References Panic().
Referenced by Panic().
RedirectLog() [1/2]
void FOutputDeviceRedirector::RedirectLog (const FLazyName & Category, ELogVerbosity::Type Verbosity, const TCHAR * Data)
References Category.
RedirectLog() [2/2]
void FOutputDeviceRedirector::RedirectLog (const FName & Category, ELogVerbosity::Type Verbosity, const TCHAR * Data)
Same as Serialize().
References Category.
RemoveOutputDevice()
void FOutputDeviceRedirector::RemoveOutputDevice (FOutputDevice * OutputDevice)
Removes an output device from the chain of redirections.
Parameters
OutputDevice Output device to remove.
References FOutputDevice::FOutputDevice().
Serialize() [1/2]
void FOutputDeviceRedirector::Serialize (const TCHAR * Data, ELogVerbosity::Type Verbosity, const FName & Category) final virtual
Serializes the passed in data via all current output devices.
Parameters
Data Text to log.
Event Event name used for suppression purposes.
Implements FOutputDevice.
References Category.
Serialize() [2/2]
void FOutputDeviceRedirector::Serialize (const TCHAR * Data, ELogVerbosity::Type Verbosity, const FName & Category, const double Time) final virtual
Serializes the passed in data via all current output devices.
Parameters
Data Text to log.
Event Event name used for suppression purposes.
Reimplemented from FOutputDevice.
References Category, and Time.
SerializeBacklog()
void FOutputDeviceRedirector::SerializeBacklog (FOutputDevice * OutputDevice)
Serializes the current backlog to the specified output device.
Parameters
OutputDevice Output device that will receive the current backlog.
References FOutputDevice::FOutputDevice().
SerializeRecord()
void FOutputDeviceRedirector::SerializeRecord (const UE::FLogRecord & Record) final virtual
Serializes the log record via all current output devices.
The format string pointed to by the record must remain valid indefinitely.
Reimplemented from FOutputDevice.
References Record.
SetCurrentThreadAsPrimaryThread()
void FOutputDeviceRedirector::SetCurrentThreadAsPrimaryThread ()
Sets the current thread to be the thread that redirects logs to buffered output devices.
The current thread can redirect to buffered output devices without buffering, and becomes responsible for flushing buffered logs from secondary threads. Logs from secondary threads will not be redirected unless the current thread periodically flushes threaded logs.
TearDown()
void FOutputDeviceRedirector::TearDown () final virtual
Closes output device and cleans up.
This can't happen in the destructor as we might have to call "delete" which cannot be done for static/global objects.
Reimplemented from FOutputDevice.
References TearDown().
Referenced by TearDown().
TryStartDedicatedPrimaryThread()
bool FOutputDeviceRedirector::TryStartDedicatedPrimaryThread ()
Starts a dedicated primary thread that redirects logs to buffered output devices.
A thread will not be started for certain configurations or platforms, or when threading is disabled.
Returns
true if a dedicated primary logging thread is running, false otherwise.
Field Documentation
State
TPimplPtr<UE::Private::FOutputDeviceRedirectorState> FOutputDeviceRedirector::State private
Definition at line 173 of file OutputDeviceRedirector.h.
The documentation for this class was generated from the following file:
OutputDeviceRedirector.h