Unreal Engine 5.6 C++ API: FRDGUploadData< InElementType > Struct Template Reference
FRDGUploadData< InElementType > Struct Template Reference
Helper class to allocate data from a GraphBuilder in order to upload said data to an RDG resource.
#include "RenderGraphUtils.h"
Public Member Functions
FRDGUploadData ()=delete
FRDGUploadData (FRDGBuilder &GraphBuilder, uint32 InCount)
int32 GetTotalSize () const
Public Member Functions inherited from TArrayView< InElementType, int32 >
TArrayView (const TArrayView &)=default
~TArrayView ()=default
FORCEINLINE ElementType * begin () const
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE void CheckInvariants () const
Checks array invariants: if array size is greater than or equal to zero.
bool Contains (const ComparisonType &Item) const
Checks if this array contains the element.
FORCEINLINE bool ContainsByPredicate (Predicate Pred) const
Checks if this array contains an element for which the predicate is true.
FORCEINLINE ElementType * end () const
TArray< std::remove_const_t< ElementType > > FilterByPredicate (Predicate Pred) const
Filters the elements in the array based on a predicate functor.
FORCEINLINE bool Find (const ElementType &Item, SizeType &Index) const
Finds element within the array.
ElementType * FindByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
ElementType * FindByPredicate (Predicate Pred) const
Finds an element which matches a predicate functor.
FORCEINLINE bool FindLast (const ElementType &Item, SizeType &Index) const
Finds element within the array starting from the end.
SizeType FindLastByPredicate (Predicate Pred, SizeType StartIndex) const
Finds element within the array starting from StartIndex and going backwards.
FORCEINLINE ElementType * GetData () const
Helper function for returning a typed pointer to the first array entry.
SizeType IndexOfByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
SizeType IndexOfByPredicate (Predicate Pred) const
Finds an item by predicate.
bool IsEmpty () const
Returns true if the array view is empty and contains no elements.
FORCEINLINE bool IsValidIndex (SizeType Index) const
Tests if index is valid, i.e.
FORCEINLINE ElementType & Last (SizeType IndexFromTheEnd=0) const
Returns n-th last element from the array.
TArrayView Left (SizeType Count) const
Returns the left-most part of the view by taking the given number of elements from the left.
TArrayView LeftChop (SizeType Count) const
Returns the left-most part of the view by chopping the given number of elements from the right.
void LeftChopInline (SizeType CharCount)
Modifies the view by chopping the given number of elements from the right.
void LeftInline (SizeType CharCount)
Modifies the view to be the given number of elements from the left.
TArrayView Mid (SizeType Index, SizeType Count=TNumericLimits< SizeType >::Max()) const
Returns the middle part of the view by taking up to the given number of elements from the given position.
void MidInline (SizeType Position, SizeType CharCount=TNumericLimits< SizeType >::Max())
Modifies the view to be the middle part by taking up to the given number of elements from the given position.
FORCEINLINE SizeType Num () const
Returns number of elements in array.
FORCEINLINE SIZE_T NumBytes () const
TArrayView & operator= (const TArrayView &)=default
bool operator== (FIntrusiveUnsetOptionalState) const
FORCEINLINE ElementType & operator[] (SizeType Index) const
Array bracket operator.
FORCEINLINE void RangeCheck (SizeType Index) const
Checks if index is in array range.
FORCEINLINE TReversePointerIterator< ElementType > rbegin () const
FORCEINLINE TReversePointerIterator< ElementType > rend () const
TArrayView Right (SizeType Count) const
Returns the right-most part of the view by taking the given number of elements from the right.
TArrayView RightChop (SizeType Count) const
Returns the right-most part of the view by chopping the given number of elements from the left.
void RightChopInline (SizeType CharCount)
Modifies the view by chopping the given number of elements from the left.
void RightInline (SizeType CharCount)
Modifies the view to be the given number of elements from the right.
FORCEINLINE TArrayView Slice (SizeType Index, SizeType InNum) const
Returns a sliced view This is similar to Mid(), but with a narrow contract, i.e.
FORCEINLINE void SliceRangeCheck (SizeType Index, SizeType InNum) const
Checks if a slice range [Index, Index+InNum) is in array range.
void Sort ()
Sorts the array assuming < operator is defined for the item type.
void StableSort ()
Stable sorts the array assuming < operator is defined for the item type.
Additional Inherited Members
Public Types inherited from TArrayView< InElementType, int32 >
using ElementType
using IntrusiveUnsetOptionalStateType
using SizeType
Static Public Member Functions inherited from TArrayView< InElementType, int32 >
static FORCEINLINE constexpr size_t GetTypeAlignment ()
Helper function returning the alignment of the inner type.
static FORCEINLINE constexpr size_t GetTypeSize ()
Helper function returning the size of the inner type.
Static Public Attributes inherited from TArrayView< InElementType, int32 >
static constexpr bool bHasIntrusiveUnsetOptionalState
Detailed Description
template<typename InElementType>
struct FRDGUploadData< InElementType >
Helper class to allocate data from a GraphBuilder in order to upload said data to an RDG resource.
Allocating from the GraphBuilder makes it so we don't have to copy the data before deferring the upload.
Definition at line 863 of file RenderGraphUtils.h.
Constructor & Destructor Documentation
FRDGUploadData() [1/2]
template<typename InElementType> FRDGUploadData< InElementType >::FRDGUploadData () delete
FRDGUploadData() [2/2]
template<typename InElementType> FRDGUploadData< InElementType >::FRDGUploadData (FRDGBuilder & GraphBuilder, uint32 InCount) inline
Definition at line 866 of file RenderGraphUtils.h.
References TArrayView< InElementType, int32 >::TArrayView().
Member Function Documentation
GetTotalSize()
template<typename InElementType> int32 FRDGUploadData< InElementType >::GetTotalSize () const inline
Definition at line 871 of file RenderGraphUtils.h.
References FORCEINLINE, TArrayView< InElementType, int32 >::GetTypeSize(), and TArrayView< InElementType, int32 >::Num().
Referenced by CreateByteAddressBuffer(), CreateStructuredBuffer(), and CreateUploadBuffer().
The documentation for this struct was generated from the following file:
RenderGraphUtils.h