Unreal Engine 5.6 C++ API: SDataflowSimulationViewport Class Reference
SDataflowSimulationViewport Class Reference
#include "DataflowSimulationViewport.h"
Public Member Functions
virtual void BindCommands () override
virtual TSharedPtr< SWidget > BuildViewportToolbar () override
void Construct (const FArguments &InArgs, const FAssetEditorViewportConstructionArgs &InViewportConstructionArgs)
virtual TSharedPtr< IPreviewProfileController > CreatePreviewProfileController () override
virtual int32 GetCurrentLOD () const override
Gets the current LOD.
virtual TSharedPtr< FExtender > GetExtenders () const override
virtual int32 GetLODCount () const override
Gets the number of LODs currently supported.
const TSharedPtr< class FDataflowSimulationScene > & GetSimulationScene () const
Get the simulation scene.
virtual TSharedRef< class SEditorViewport > GetViewportWidget () override
virtual bool IsLODSelected (int32 LODIndex) const override
Gets whether a given LOD is active.
virtual bool IsVisible () const override
virtual TSharedPtr< SWidget > MakeViewportToolbar () override
virtual void OnFloatingButtonClicked () override
virtual void OnFocusViewportToSelection () override
virtual void SetLODLevel (int32 LODIndex) override
Sets the LOD level by index.
SLATE_ARGUMENT (TSharedPtr< FEditorViewportClient >, ViewportClient) SLATE_ARGUMENT(TSharedPtr< FUICommandList >
SLATE_BEGIN_ARGS (SDataflowSimulationViewport)
CommandList SLATE_END_ARGS () SDataflowSimulationViewport()
Public Member Functions inherited from IPreviewLODController
virtual ~IPreviewLODController ()=default
virtual void FillLODCommands (TArray< TSharedPtr< FUICommandInfo > > &Commands)
Provide LOD commands that should be included before any auto-generated LOD menu items.
virtual int32 GetAutoLODStartingIndex () const
Set which LOD level an auto-generated list of LOD options should start from.
Private Member Functions
FText GetDisplayString () const
UDataflowEditorMode * GetEdMode () const
float GetViewMaxInput () const
float GetViewMinInput () const
Detailed Description
Definition at line 16 of file DataflowSimulationViewport.h.
Member Function Documentation
BindCommands()
virtual void SDataflowSimulationViewport::BindCommands () override virtual
References BindCommands().
Referenced by BindCommands().
BuildViewportToolbar()
virtual TSharedPtr< SWidget > SDataflowSimulationViewport::BuildViewportToolbar () override virtual
References BuildViewportToolbar().
Referenced by BuildViewportToolbar().
Construct()
void SDataflowSimulationViewport::Construct (const FArguments & InArgs, const FAssetEditorViewportConstructionArgs & InViewportConstructionArgs)
References Construct().
Referenced by Construct().
CreatePreviewProfileController()
virtual TSharedPtr< IPreviewProfileController > SDataflowSimulationViewport::CreatePreviewProfileController () override virtual
References CreatePreviewProfileController().
Referenced by CreatePreviewProfileController().
GetCurrentLOD()
virtual int32 SDataflowSimulationViewport::GetCurrentLOD () const override virtual
Gets the current LOD.
A value of INDEX_NONE implies an 'Auto' LOD.
Implements IPreviewLODController.
References GetCurrentLOD().
Referenced by GetCurrentLOD().
GetDisplayString()
FText SDataflowSimulationViewport::GetDisplayString () const private
References GetDisplayString().
Referenced by GetDisplayString().
GetEdMode()
UDataflowEditorMode * SDataflowSimulationViewport::GetEdMode () const private
References GetEdMode().
Referenced by GetEdMode().
GetExtenders()
virtual TSharedPtr< FExtender > SDataflowSimulationViewport::GetExtenders () const override virtual
Implements ICommonEditorViewportToolbarInfoProvider.
References GetExtenders().
Referenced by GetExtenders().
GetLODCount()
virtual int32 SDataflowSimulationViewport::GetLODCount () const override virtual
Gets the number of LODs currently supported.
Implements IPreviewLODController.
References GetLODCount().
Referenced by GetLODCount().
GetSimulationScene()
const TSharedPtr< class FDataflowSimulationScene > & SDataflowSimulationViewport::GetSimulationScene () const
Get the simulation scene.
References GetSimulationScene().
Referenced by GetSimulationScene().
GetViewMaxInput()
float SDataflowSimulationViewport::GetViewMaxInput () const private
References GetViewMaxInput().
Referenced by GetViewMaxInput().
GetViewMinInput()
float SDataflowSimulationViewport::GetViewMinInput () const private
References GetViewMinInput().
Referenced by GetViewMinInput().
GetViewportWidget()
virtual TSharedRef< class SEditorViewport > SDataflowSimulationViewport::GetViewportWidget () override virtual
Implements ICommonEditorViewportToolbarInfoProvider.
References GetViewportWidget().
Referenced by GetViewportWidget().
IsLODSelected()
virtual bool SDataflowSimulationViewport::IsLODSelected (int32 LODIndex) const override virtual
Gets whether a given LOD is active.
Implements IPreviewLODController.
References IsLODSelected().
Referenced by IsLODSelected().
IsVisible()
virtual bool SDataflowSimulationViewport::IsVisible () const override virtual
References IsVisible().
Referenced by IsVisible().
MakeViewportToolbar()
virtual TSharedPtr< SWidget > SDataflowSimulationViewport::MakeViewportToolbar () override virtual
References MakeViewportToolbar().
Referenced by MakeViewportToolbar().
OnFloatingButtonClicked()
virtual void SDataflowSimulationViewport::OnFloatingButtonClicked () override virtual
Implements ICommonEditorViewportToolbarInfoProvider.
References OnFloatingButtonClicked().
Referenced by OnFloatingButtonClicked().
OnFocusViewportToSelection()
virtual void SDataflowSimulationViewport::OnFocusViewportToSelection () override virtual
References OnFocusViewportToSelection().
Referenced by OnFocusViewportToSelection().
SetLODLevel()
virtual void SDataflowSimulationViewport::SetLODLevel (int32 LODIndex) override virtual
Sets the LOD level by index.
A value of INDEX_NONE implies an 'Auto' LOD.
Implements IPreviewLODController.
References SetLODLevel().
Referenced by SetLODLevel().
SLATE_ARGUMENT()
SDataflowSimulationViewport::SLATE_ARGUMENT (TSharedPtr< FEditorViewportClient > , ViewportClient)
SLATE_BEGIN_ARGS()
SDataflowSimulationViewport::SLATE_BEGIN_ARGS (SDataflowSimulationViewport) inline
Definition at line 19 of file DataflowSimulationViewport.h.
SLATE_END_ARGS()
CommandList SDataflowSimulationViewport::SLATE_END_ARGS ()
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
The documentation for this class was generated from the following file:
DataflowSimulationViewport.h