Unreal Engine 5.6 C++ API: AnimNodeData.h File Reference
AnimNodeData.h File Reference
#include "CoreMinimal.h"
#include "AnimNodeData.generated.h"
Data Structures
struct UE::Anim::FNodeDataId
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Anim
Macros
#define ANIM_NODE_DATA_INSTANCE_DATA_FLAG 0x80000000
#define ANIM_NODE_DATA_INSTANCE_DATA_MASK ~ANIM_NODE_DATA_INSTANCE_DATA_FLAG
#define ANIM_NODE_DATA_INVALID_ENTRY 0xffffffff
Functions
UENUM() enum class EAnimNodeDataFlags ENUM_CLASS_FLAGS (EAnimNodeDataFlags)
USTRUCT () struct FAnimNodeStructData
Data about editor-side struct property indices.
Macro Definition Documentation
ANIM_NODE_DATA_INSTANCE_DATA_FLAG
#define ANIM_NODE_DATA_INSTANCE_DATA_FLAG 0x80000000
Definition at line 15 of file AnimNodeData.h.
ANIM_NODE_DATA_INSTANCE_DATA_MASK
#define ANIM_NODE_DATA_INSTANCE_DATA_MASK ~ANIM_NODE_DATA_INSTANCE_DATA_FLAG
Definition at line 16 of file AnimNodeData.h.
ANIM_NODE_DATA_INVALID_ENTRY
#define ANIM_NODE_DATA_INVALID_ENTRY 0xffffffff
Definition at line 14 of file AnimNodeData.h.
Function Documentation
ENUM_CLASS_FLAGS()
UENUM() enum class EAnimNodeDataFlags ENUM_CLASS_FLAGS (EAnimNodeDataFlags)
USTRUCT()
USTRUCT ()
Data about editor-side struct property indices.
Used to map property name to editor-only property indices. This allows us to avoid TMap lookups at runtime.
Get the specified data for the specified instance. The data may or may not reside on an anim instance itself as it may have been folded into constants.
Parameters
InId The data ID to use
InNode The anim node that this data is for
InCurrentObject The object that the node is held on. This is optional as it can be recovered via the node where needed, but can accelerate the operation if supplied.
Returns
the raw data value, either held on sparse class data or on the instance
Get the specified mutable data for the specified instance. If the data is not held on the instance this will return nullptr.
The class we are part of
Get the node index for this constant data block.
Check whether the node has the specified flags
Set whether the node has the specified flags
The class we are part of
Flags & Indices for table entries. Used to look up indices from NodePropertyIndex->FoldedDataIndex. If the MSB is set for an entry it is assumed to be on an instance, if not, it is assumed to be stored on the class.
The index of the node for this constant data block in the class that it is held in. INDEX_NONE if this node is not in a generated class or is per-instance data.
Common flags for this node
Definition at line 91 of file AnimNodeData.h.
References check, EnumAddFlags(), EnumHasAnyFlags(), Flags, GENERATED_BODY, GetData(), INDEX_NONE, and UPROPERTY.