Unreal Engine 5.6 C++ API: FUniqueObjectGuid Struct Reference
FUniqueObjectGuid Struct Reference
Wrapper structure for a GUID that uniquely identifies registered UObjects.
#include "LazyObjectPtr.h"
Public Member Functions
FUniqueObjectGuid ()
FUniqueObjectGuid (const FGuid &InGuid)
FUniqueObjectGuid (const UObject *InObject)
Construct from an existing object.
FUniqueObjectGuid FixupForPIE (int32 PlayInEditorID=UE::GetPlayInEditorID()) const
Fixes up this UniqueObjectID to add or remove the PIE prefix depending on what is currently active.
void FromString (const FString &From)
Converts from a string.
FORCEINLINE const FGuid & GetGuid () const
Returns wrapped Guid.
FORCEINLINE bool IsDefault () const
Returns true is this is the default value.
FORCEINLINE bool IsValid () const
Test if this can ever point to a live UObject.
FORCEINLINE bool operator!= (const FUniqueObjectGuid &Other) const
FORCEINLINE bool operator== (const FUniqueObjectGuid &Other) const
FORCEINLINE void Reset ()
Reset the guid pointer back to the invalid state.
UObject * ResolveObject () const
Attempts to find a currently loaded object that matches this object ID.
FString ToString () const
Converts into a string.
UE_DEPRECATED (5.4, "The current object tag is no longer used by TSoftObjectPtr, you can remove all calls") static int32 GetCurrentTag()
UE_DEPRECATED (5.4, "The current object tag is no longer used by TSoftObjectPtr, you can remove all calls") static int32 InvalidateTag()
Static Public Member Functions
static FORCEINLINE FUniqueObjectGuid GetOrCreateIDForObject (const UObject *Object)
static FUniqueObjectGuid GetOrCreateIDForObject (FObjectPtr Object)
template<typename T>
static FORCEINLINE FUniqueObjectGuid GetOrCreateIDForObject (TObjectPtr< T > Object)
Private Attributes
FGuid Guid
Guid representing the object, should be unique.
Friends
FORCEINLINE friend uint32 GetTypeHash (const FUniqueObjectGuid &ObjectGuid)
FArchive & operator<< (FArchive &Ar, FUniqueObjectGuid &ObjectGuid)
void operator<< (FStructuredArchive::FSlot Slot, FUniqueObjectGuid &ObjectGuid)
Detailed Description
Wrapper structure for a GUID that uniquely identifies registered UObjects.
The actual GUID is stored in an object annotation that is updated when a new reference is made.
Definition at line 33 of file LazyObjectPtr.h.
Constructor & Destructor Documentation
FUniqueObjectGuid() [1/3]
FUniqueObjectGuid::FUniqueObjectGuid () inline
Definition at line 35 of file LazyObjectPtr.h.
Referenced by FixupForPIE(), GetOrCreateIDForObject(), GetOrCreateIDForObject(), GetOrCreateIDForObject(), GetTypeHash, operator!=(), operator<<, operator<<, and operator==().
FUniqueObjectGuid() [2/3]
FUniqueObjectGuid::FUniqueObjectGuid (const FGuid & InGuid) inline
Definition at line 38 of file LazyObjectPtr.h.
References Guid.
FUniqueObjectGuid() [3/3]
FUniqueObjectGuid::FUniqueObjectGuid (const UObject * InObject) explicit
Construct from an existing object.
Member Function Documentation
FixupForPIE()
FUniqueObjectGuid FUniqueObjectGuid::FixupForPIE (int32 PlayInEditorID = UE::GetPlayInEditorID()) const
Fixes up this UniqueObjectID to add or remove the PIE prefix depending on what is currently active.
References FUniqueObjectGuid(), and UE::GetPlayInEditorID().
Referenced by FLazyObjectPtr::FixupForPIE().
FromString()
void FUniqueObjectGuid::FromString (const FString & From)
Converts from a string.
GetGuid()
FORCEINLINE const FGuid & FUniqueObjectGuid::GetGuid () const inline
Returns wrapped Guid.
Definition at line 95 of file LazyObjectPtr.h.
References FORCEINLINE, and Guid.
GetOrCreateIDForObject() [1/3]
FORCEINLINE FUniqueObjectGuid FUniqueObjectGuid::GetOrCreateIDForObject (const UObject * Object) inline static
Definition at line 123 of file LazyObjectPtr.h.
References FUniqueObjectGuid(), FORCEINLINE, GetOrCreateIDForObject(), and Object.
GetOrCreateIDForObject() [2/3]
FUniqueObjectGuid FUniqueObjectGuid::GetOrCreateIDForObject (FObjectPtr Object) static
References FUniqueObjectGuid(), and Object.
Referenced by GetOrCreateIDForObject(), and GetOrCreateIDForObject().
GetOrCreateIDForObject() [3/3]
template<typename T> FORCEINLINE FUniqueObjectGuid FUniqueObjectGuid::GetOrCreateIDForObject (TObjectPtr< T > Object) inline static
Definition at line 128 of file LazyObjectPtr.h.
References FUniqueObjectGuid(), FORCEINLINE, GetOrCreateIDForObject(), and Object.
IsDefault()
FORCEINLINE bool FUniqueObjectGuid::IsDefault () const inline
Returns true is this is the default value.
Definition at line 84 of file LazyObjectPtr.h.
References FORCEINLINE, and IsValid().
IsValid()
FORCEINLINE bool FUniqueObjectGuid::IsValid () const inline
Test if this can ever point to a live UObject.
Definition at line 68 of file LazyObjectPtr.h.
References FORCEINLINE, and Guid.
Referenced by IsDefault().
operator!=()
FORCEINLINE bool FUniqueObjectGuid::operator!= (const FUniqueObjectGuid & Other) const inline
Definition at line 78 of file LazyObjectPtr.h.
References FUniqueObjectGuid(), FORCEINLINE, Guid, and Other.
operator==()
FORCEINLINE bool FUniqueObjectGuid::operator== (const FUniqueObjectGuid & Other) const inline
Definition at line 73 of file LazyObjectPtr.h.
References FUniqueObjectGuid(), FORCEINLINE, Guid, and Other.
Reset()
FORCEINLINE void FUniqueObjectGuid::Reset () inline
Reset the guid pointer back to the invalid state.
Definition at line 43 of file LazyObjectPtr.h.
References FORCEINLINE, and Guid.
ResolveObject()
UObject * FUniqueObjectGuid::ResolveObject () const
Attempts to find a currently loaded object that matches this object ID.
Returns
Found UObject, or nullptr if not currently loaded
ToString()
FString FUniqueObjectGuid::ToString () const
Converts into a string.
UE_DEPRECATED() [1/2]
FUniqueObjectGuid::UE_DEPRECATED (5. 4, "The current object tag is no longer used by TSoftObjectPtr, you can remove all calls") inline
Definition at line 111 of file LazyObjectPtr.h.
UE_DEPRECATED() [2/2]
FUniqueObjectGuid::UE_DEPRECATED (5. 4, "The current object tag is no longer used by TSoftObjectPtr, you can remove all calls") inline
Definition at line 116 of file LazyObjectPtr.h.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE friend uint32 GetTypeHash (const FUniqueObjectGuid & ObjectGuid) friend
Definition at line 90 of file LazyObjectPtr.h.
References FUniqueObjectGuid(), FORCEINLINE, GetTypeHash, and Guid.
Referenced by GetTypeHash.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FUniqueObjectGuid & ObjectGuid) friend
Definition at line 100 of file LazyObjectPtr.h.
References FUniqueObjectGuid(), Ar, and Guid.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FUniqueObjectGuid & ObjectGuid) friend
Definition at line 106 of file LazyObjectPtr.h.
References FUniqueObjectGuid(), and Guid.
Field Documentation
Guid
FGuid FUniqueObjectGuid::Guid private
Guid representing the object, should be unique.
Definition at line 135 of file LazyObjectPtr.h.
Referenced by FUniqueObjectGuid(), GetGuid(), GetTypeHash, IsValid(), operator!=(), operator<<, operator<<, operator==(), and Reset().
The documentation for this struct was generated from the following file:
LazyObjectPtr.h