Unreal Engine 5.6 C++ API: UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType > Class Template Reference
UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType > Class Template Reference
Remove "occluded" triangles, i.e.
#include "RemoveOccludedTriangles.h"
Public Member Functions
TRemoveOccludedTriangles (FDynamicMesh3 *Mesh)
virtual ~TRemoveOccludedTriangles ()
virtual bool Apply (const FTransformSRT3d &MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > *Occluder)
Remove the occluded triangles – single instance case w/out precomputed winding tree.
virtual bool Apply (const FTransformSRT3d &MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > *Spatial, TFastWindingTree< OccluderTriangleMeshType > *FastWindingTree)
Remove the occluded triangles – single instance case.
virtual bool Apply (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, const TArrayView< TMeshAABBTree3< OccluderTriangleMeshType > * > Spatials, const TArrayView< TFastWindingTree< OccluderTriangleMeshType > * > FastWindingTrees, const TArrayView< const FTransformSRT3d > SpatialTransforms=TArrayView< const FTransformSRT3d >(), bool bTestOccludedByAny=false)
Remove the occluded triangles, considering the given occluder AABB trees (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you.
virtual bool Apply (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, TMeshAABBTree3< OccluderTriangleMeshType > *Spatial, TFastWindingTree< OccluderTriangleMeshType > *FastWindingTree)
Remove the occluded triangles, considering the given occluder AABB tree (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you.
virtual bool RemoveSelected ()
Remove triangles that were selected (the triangle IDs in the RemoveT array)
virtual bool Select (const FTransformSRT3d &MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > *Occluder)
Select the occluded triangles – single instance case w/out precomputed winding tree.
virtual bool Select (const FTransformSRT3d &MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > *Spatial, TFastWindingTree< OccluderTriangleMeshType > *FastWindingTree)
Select the occluded triangles – single instance case.
virtual bool Select (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, const TArrayView< TMeshAABBTree3< OccluderTriangleMeshType > * > Spatials, const TArrayView< TFastWindingTree< OccluderTriangleMeshType > * > FastWindingTrees, const TArrayView< const FTransformSRT3d > SpatialTransforms=TArrayView< const FTransformSRT3d >(), bool bTestOccludedByAny=false)
Select the occluded triangles, considering the given occluder AABB trees (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you Selection will be stored in the RemovedT array, but no triangles will be removed.
virtual bool Select (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, TMeshAABBTree3< OccluderTriangleMeshType > *Spatial, TFastWindingTree< OccluderTriangleMeshType > *FastWindingTree)
Select the occluded triangles, considering the given occluder AABB tree (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you.
virtual EOperationValidationResult Validate ()
Data Fields
int AddRandomRays = 0
Number of additional ray directions to add to raycast-based occlusion checks, beyond the default +/- major axis directions.
int AddTriangleSamples = 0
Number of additional samples to add per triangle.
bool bRemoveFailed = false
true if it wanted to remove triangles but the actual remove operation failed
EOcclusionCalculationMode InsideMode = EOcclusionCalculationMode::FastWindingNumber
FDynamicMesh3 * Mesh
double NormalOffset = FMathd::ZeroTolerance
FProgressCancel * Progress = nullptr
Set this to be able to cancel running operation.
TArray< int > RemovedT
indices of removed triangles.
EOcclusionTriangleSampling TriangleSamplingMethod = EOcclusionTriangleSampling::Vertices
double WindingIsoValue = 0.5
use this as winding isovalue for WindingNumber mode
Protected Member Functions
virtual bool Cancelled ()
if this returns true, abort computation.
Detailed Description
template<typename OccluderTriangleMeshType>
class UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >
Remove "occluded" triangles, i.e.
triangles on the "inside" of the mesh(es). This is a fuzzy definition, current implementation has a couple of options including a winding number-based version and an ambient-occlusion-ish version, where if face is occluded for all test rays, then we classify it as inside and remove it.
Note this class always removes triangles from an FDynamicMesh3, but can use any mesh type to define the occluding geometry (as long as the mesh type implements the TTriangleMeshAdapter fns)
Definition at line 85 of file RemoveOccludedTriangles.h.
Constructor & Destructor Documentation
TRemoveOccludedTriangles()
template<typename OccluderTriangleMeshType> UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::TRemoveOccludedTriangles (FDynamicMesh3 * Mesh) inline
Definition at line 91 of file RemoveOccludedTriangles.h.
References Mesh.
~TRemoveOccludedTriangles()
template<typename OccluderTriangleMeshType> virtual UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::~TRemoveOccludedTriangles () inline virtual
Definition at line 94 of file RemoveOccludedTriangles.h.
Member Function Documentation
Apply() [1/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Apply (const FTransformSRT3d & MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > * Occluder) inline virtual
Remove the occluded triangles – single instance case w/out precomputed winding tree.
Parameters
LocalToWorld Transform to take the local mesh into the space of the occluder geometry
Occluder AABB tree of occluding geometry
Returns
true on success
Definition at line 561 of file RemoveOccludedTriangles.h.
References Apply(), UE::Geometry::FastWindingNumber, and InsideMode.
Apply() [2/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Apply (const FTransformSRT3d & MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > * Spatial, TFastWindingTree< OccluderTriangleMeshType > * FastWindingTree) inline virtual
Remove the occluded triangles – single instance case.
Parameters
LocalToWorld Transform to take the local mesh into the space of the occluder geometry
Occluder AABB tree of occluding geometry
Returns
true on success
Definition at line 533 of file RemoveOccludedTriangles.h.
References Apply().
Apply() [3/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Apply (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, const TArrayView< TMeshAABBTree3< OccluderTriangleMeshType > * > Spatials, const TArrayView< TFastWindingTree< OccluderTriangleMeshType > * > FastWindingTrees, const TArrayView< const FTransformSRT3d > SpatialTransforms = TArrayView<const FTransformSRT3d>(), bool bTestOccludedByAny = false) inline virtual
Remove the occluded triangles, considering the given occluder AABB trees (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you.
Parameters
MeshLocalToOccluderSpaces Transforms to take instances of the local mesh into the space of the occluders
Spatials AABB trees for all occluders
FastWindingTrees Precomputed fast winding trees for occluders
SpatialTransforms Transforms AABB/winding tree to shared occluder space (if empty, Identity is used)
bTestOccludedByAny If true, a triangle is occluded if it is fully occluded by any occluder. Otherwise, we test if it's occluded by the combination of all occluders.
Returns
true on success
Definition at line 464 of file RemoveOccludedTriangles.h.
References RemoveSelected(), and Select().
Referenced by Apply(), Apply(), and Apply().
Apply() [4/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Apply (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, TMeshAABBTree3< OccluderTriangleMeshType > * Spatial, TFastWindingTree< OccluderTriangleMeshType > * FastWindingTree) inline virtual
Remove the occluded triangles, considering the given occluder AABB tree (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you.
Parameters
MeshLocalToOccluderSpaces Transforms to take instances of the local mesh into the space of the occluders
Spatials AABB trees for all occluders
FastWindingTrees Precomputed fast winding trees for occluders
Returns
true on success
Definition at line 504 of file RemoveOccludedTriangles.h.
References Apply().
Cancelled()
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Cancelled () inline protected virtual
if this returns true, abort computation.
Definition at line 619 of file RemoveOccludedTriangles.h.
References Progress.
Referenced by Select().
RemoveSelected()
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::RemoveSelected () inline virtual
Remove triangles that were selected (the triangle IDs in the RemoveT array)
Definition at line 435 of file RemoveOccludedTriangles.h.
References bRemoveFailed, Editor, Mesh, and RemovedT.
Referenced by Apply().
Select() [1/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select (const FTransformSRT3d & MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > * Occluder) inline virtual
Select the occluded triangles – single instance case w/out precomputed winding tree.
Parameters
LocalToWorld Transform to take the local mesh into the space of the occluder geometry
Occluder AABB tree of occluding geometry
Returns
true on success
Definition at line 547 of file RemoveOccludedTriangles.h.
References UE::Geometry::FastWindingNumber, InsideMode, and Select().
Select() [2/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select (const FTransformSRT3d & MeshLocalToOccluderSpace, TMeshAABBTree3< OccluderTriangleMeshType > * Spatial, TFastWindingTree< OccluderTriangleMeshType > * FastWindingTree) inline virtual
Select the occluded triangles – single instance case.
Parameters
LocalToWorld Transform to take the local mesh into the space of the occluder geometry
Occluder AABB tree of occluding geometry
Returns
true on success
Definition at line 519 of file RemoveOccludedTriangles.h.
References Select().
Select() [3/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, const TArrayView< TMeshAABBTree3< OccluderTriangleMeshType > * > Spatials, const TArrayView< TFastWindingTree< OccluderTriangleMeshType > * > FastWindingTrees, const TArrayView< const FTransformSRT3d > SpatialTransforms = TArrayView<const FTransformSRT3d>(), bool bTestOccludedByAny = false) inline virtual
Select the occluded triangles, considering the given occluder AABB trees (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you Selection will be stored in the RemovedT array, but no triangles will be removed.
Parameters
MeshLocalToOccluderSpaces Transforms to take instances of the local mesh into the space of the occluders
Spatials AABB trees for all occluders
FastWindingTrees Precomputed fast winding trees for occluders
SpatialTransforms Transforms AABB/winding tree to shared occluder space (if empty, Identity is used)
bTestOccludedByAny If true, a triangle is occluded if it is fully occluded by any occluder. Otherwise, we test if it's occluded by the combination of all occluders.
Returns
true on success
Definition at line 109 of file RemoveOccludedTriangles.h.
References TArray< InElementType, InAllocatorType >::Add(), AddRandomRays, AddTriangleSamples, bool, Cancelled(), UE::Geometry::Centroids, checkSlow, TArray< InElementType, InAllocatorType >::Emplace(), UE::Geometry::FastWindingNumber, FRandomStream::FRand(), UE::Geometry::TQuaternion< double >::Identity(), UE::Geometry::TTransformSRT3< double >::Identity(), TArray< InElementType, InAllocatorType >::Init(), InsideMode, Mesh, UE::Geometry::Normal, NormalOffset, Normals, TArray< InElementType, InAllocatorType >::Num(), TArrayView< InElementType, InSizeType >::Num(), UE::Math::TVector< double >::One(), Other, ParallelFor(), Ray, TMathUtil< double >::SignNonZero(), UE::Geometry::SimpleOcclusionTest, Transform, UE::Geometry::Transform, TriangleSamplingMethod, UE::Math::TVector< double >::UnitX(), UE::Math::TVector< double >::UnitY(), UE::Math::TVector< double >::UnitZ(), UE::Geometry::Vertices, UE::Geometry::VerticesAndCentroids, FRandomStream::VRand(), WindingIsoValue, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, UE::Math::TVector< T >::Z, and TMathUtilConstants< double >::ZeroTolerance.
Referenced by Apply(), Select(), Select(), and Select().
Select() [4/4]
template<typename OccluderTriangleMeshType> virtual bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select (const TArrayView< const FTransformSRT3d > MeshLocalToOccluderSpaces, TMeshAABBTree3< OccluderTriangleMeshType > * Spatial, TFastWindingTree< OccluderTriangleMeshType > * FastWindingTree) inline virtual
Select the occluded triangles, considering the given occluder AABB tree (which may represent more geometry than a single mesh) See simpler invocations below for the single instance case or the case where you'd like the spatial data structures built for you.
Parameters
MeshLocalToOccluderSpaces Transforms to take instances of the local mesh into the space of the occluders
Spatials AABB trees for all occluders
FastWindingTrees Precomputed fast winding trees for occluders
Returns
true on success
Definition at line 486 of file RemoveOccludedTriangles.h.
References Select().
Validate()
template<typename OccluderTriangleMeshType> virtual EOperationValidationResult UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Validate () inline virtual
Returns
EOperationValidationResult::Ok if we can apply operation, or error code if we cannot
Definition at line 570 of file RemoveOccludedTriangles.h.
References UE::Geometry::Ok.
Field Documentation
AddRandomRays
template<typename OccluderTriangleMeshType> int UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::AddRandomRays = 0
Number of additional ray directions to add to raycast-based occlusion checks, beyond the default +/- major axis directions.
Definition at line 593 of file RemoveOccludedTriangles.h.
Referenced by Select().
AddTriangleSamples
template<typename OccluderTriangleMeshType> int UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::AddTriangleSamples = 0
Number of additional samples to add per triangle.
Definition at line 596 of file RemoveOccludedTriangles.h.
Referenced by Select().
bRemoveFailed
template<typename OccluderTriangleMeshType> bool UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::bRemoveFailed = false
true if it wanted to remove triangles but the actual remove operation failed
Definition at line 612 of file RemoveOccludedTriangles.h.
Referenced by RemoveSelected().
InsideMode
template<typename OccluderTriangleMeshType> EOcclusionCalculationMode UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::InsideMode = EOcclusionCalculationMode::FastWindingNumber
Definition at line 590 of file RemoveOccludedTriangles.h.
Referenced by Apply(), Select(), and Select().
Mesh
template<typename OccluderTriangleMeshType> FDynamicMesh3* UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Mesh
Definition at line 89 of file RemoveOccludedTriangles.h.
Referenced by TRemoveOccludedTriangles(), RemoveSelected(), and Select().
NormalOffset
template<typename OccluderTriangleMeshType> double UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::NormalOffset = FMathd::ZeroTolerance
Definition at line 585 of file RemoveOccludedTriangles.h.
Referenced by Select().
Progress
template<typename OccluderTriangleMeshType> FProgressCancel* UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Progress = nullptr
Set this to be able to cancel running operation.
Definition at line 601 of file RemoveOccludedTriangles.h.
Referenced by Cancelled().
RemovedT
template<typename OccluderTriangleMeshType> TArray<int> UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::RemovedT
indices of removed triangles.
will be empty if nothing removed
Definition at line 609 of file RemoveOccludedTriangles.h.
Referenced by RemoveSelected().
TriangleSamplingMethod
template<typename OccluderTriangleMeshType> EOcclusionTriangleSampling UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::TriangleSamplingMethod = EOcclusionTriangleSampling::Vertices
Definition at line 582 of file RemoveOccludedTriangles.h.
Referenced by Select().
WindingIsoValue
template<typename OccluderTriangleMeshType> double UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::WindingIsoValue = 0.5
use this as winding isovalue for WindingNumber mode
Definition at line 588 of file RemoveOccludedTriangles.h.
Referenced by Select().
The documentation for this class was generated from the following file:
RemoveOccludedTriangles.h