Unreal Engine 5.6 C++ API: TContainerElementTypeCompatibility< TObjectPtr< T > > Struct Template Reference
TContainerElementTypeCompatibility< TObjectPtr< T > > Struct Template Reference
#include "ObjectPtr.h"
Public Types
typedef T * CopyFromOtherType
typedef T * ReinterpretType
Static Public Member Functions
static constexpr void CopyingFromOtherType ()
template<typename IterBeginType, typename IterEndType, typename OperatorType = std::remove_reference_t<decltype(*std::declval<IterBeginType>())>& (*)(IterBeginType&)>
static void ReinterpretRange (IterBeginType Iter, IterEndType IterEnd, OperatorType Operator=TContainerElementTypeCompatibility_DefaultOperatorFunc)
template<typename IterBeginType, typename IterEndType, typename SizeType, typename OperatorType = std::remove_reference_t<decltype(*std::declval<IterBeginType>())>& (*)(IterBeginType&)>
static void ReinterpretRangeContiguous (IterBeginType Iter, IterEndType IterEnd, SizeType Size, OperatorType Operator=TContainerElementTypeCompatibility_DefaultOperatorFunc)
Detailed Description
template<typename T>
struct TContainerElementTypeCompatibility< TObjectPtr< T > >
Definition at line 1105 of file ObjectPtr.h.
Member Typedef Documentation
CopyFromOtherType
template<typename T> typedef T* TContainerElementTypeCompatibility< TObjectPtr< T > >::CopyFromOtherType
Definition at line 1108 of file ObjectPtr.h.
ReinterpretType
template<typename T> typedef T* TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretType
Definition at line 1107 of file ObjectPtr.h.
Member Function Documentation
CopyingFromOtherType()
template<typename T> constexpr void TContainerElementTypeCompatibility< TObjectPtr< T > >::CopyingFromOtherType () inline static constexpr
Definition at line 1144 of file ObjectPtr.h.
References CopyingFromOtherType().
Referenced by CopyingFromOtherType().
ReinterpretRange()
template<typename T> template<typename IterBeginType, typename IterEndType, typename OperatorType = std::remove_reference_t<decltype(*std::declval<IterBeginType>())>& (*)(IterBeginType&)> void TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRange (IterBeginType Iter, IterEndType IterEnd, OperatorType Operator = TContainerElementTypeCompatibility_DefaultOperatorFunc) inline static
Definition at line 1112 of file ObjectPtr.h.
References check, and TContainerElementTypeCompatibility_DefaultOperatorFunc.
ReinterpretRangeContiguous()
template<typename T> template<typename IterBeginType, typename IterEndType, typename SizeType, typename OperatorType = std::remove_reference_t<decltype(*std::declval<IterBeginType>())>& (*)(IterBeginType&)> void TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRangeContiguous (IterBeginType Iter, IterEndType IterEnd, SizeType Size, OperatorType Operator = TContainerElementTypeCompatibility_DefaultOperatorFunc) inline static
Definition at line 1126 of file ObjectPtr.h.
References check, FObjectPtr::GetHandleRef(), FObjectPtr::IsResolved(), UE::CoreUObject::Private::OnHandleRead(), UE::CoreUObject::Private::ResolveObjectHandleNoRead(), TContainerElementTypeCompatibility_DefaultOperatorFunc, and TSequenceHistory< HistorySize >::Size.
The documentation for this struct was generated from the following file:
ObjectPtr.h