Unreal Engine 5.6 C++ API: FSkeletalMeshStreamOut Class Reference
FSkeletalMeshStreamOut Class Reference
#include "SkeletalMeshUpdate.h"
Public Member Functions
FSkeletalMeshStreamOut (const USkeletalMesh *InMesh)
virtual ~FSkeletalMeshStreamOut ()
Public Member Functions inherited from FSkeletalMeshUpdate
FSkeletalMeshUpdate (const USkeletalMesh *InMesh)
virtual ~FSkeletalMeshUpdate ()
virtual void Abort ()
Cancel the current update.
Public Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
TRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
EThreadType GetRelevantThread () const final override
Return the thread relevant to the next step of execution.
void PushTask (const FContext &Context, EThreadType InTaskThread, const FCallback &InTaskCallback, EThreadType InCancelationThread, const FCallback &InCancelationCallback)
Defines the next step to be executed.
Public Member Functions inherited from FRenderAssetUpdate
FRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
FReturnedRefCountValue AddRef () const final override
ETaskState DoLock ()
Perform a lock on the object, preventing any other thread from processing a pending task in Tick().
void DoUnlock (ETaskState PreviousTaskState)
Release any lock on the object, allowing other thread to modify it.
uint32 GetRefCount () const final override
bool IsCancelled () const
Returns whether the task was aborted through Abort() or cancelled.
bool IsCompleted () const
Returns whether the task has finished executing and there is no other thread possibly accessing it.
bool IsLocked () const
bool IsSuccessfullyFinished () const
Returns whether this update has finished successfully.
uint32 Release () const final override
void Tick (EThreadType InCurrentThread)
Do or schedule any pending work for a given texture.
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Private Member Functions
void Cancel (const FContext &Context)
Cancel the pending mip change.
void ConditionalMarkComponentsDirty (const FContext &Context)
Notify components that the LOD is being streamed out so that they can release references.
void ReleaseBuffers (const FContext &Context)
Release RHI buffers and update SRVs.
void WaitForReferences (const FContext &Context)
Wait for all references to be released.
Private Attributes
int32 NumReferenceChecks = 0
uint32 PreviousNumberOfExternalReferences = 0
Additional Inherited Members
Public Types inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
typedef TFunction< void(const FContext &Context)> FCallback
A callback used to perform a task in the update process.
typedef FSkelMeshUpdateContext FContext
Public Types inherited from FRenderAssetUpdate
enum ETaskState {
TS_Done , TS_Suspended , TS_InProgress , TS_Locked ,
TS_Init
}
The state of scheduled work for the update process.
enum EThreadType {
TT_None , TT_Render , TT_Async , TT_GameThread ,
TT_GameRunningAsync
}
A thread type used for doing a part of the update process.
Protected Types inherited from FRenderAssetUpdate
typedef FAutoDeleteAsyncTask< FMipUpdateTask > FAsyncMipUpdateTask
The async task to update this object, only one can be active at anytime.
Protected Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
void ClearCallbacks ()
ETaskState TickInternal (EThreadType InCurrentThread, bool bCheckForSuspension) final override
Protected Member Functions inherited from FRenderAssetUpdate
virtual ~FRenderAssetUpdate ()
void MarkAsCancelled ()
Set the task state as cancelled.
void MarkAsSuccessfullyFinished ()
void ScheduleAsyncTask ()
void ScheduleGTTask ()
void ScheduleRenderTask ()
Protected Attributes inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
FCallback CancelationCallback
The callback handling the cancellation of the update (only if the update gets cancelled).
EThreadType CancelationThread
The thread on which to call the cancellation of the update (only if the update gets cancelled).
FCallback TaskCallback
The callback that will perform the next step of the update.
EThreadType TaskThread
The thread on which to call the next step of the update, being TaskCallback.
Protected Attributes inherited from FRenderAssetUpdate
bool bDeferExecution
Defer execution even if a task pushes a new task on the same thread.
bool bIsCancelled
Whether the task has been cancelled because the update could not proceed or because the user called Abort().
bool bSuccess
Whether this update finished successfully.
FCriticalSection CS
Critical Section.
const int32 CurrentFirstLODIdx = INDEX_NONE
const int32 PendingFirstLODIdx = INDEX_NONE
const FStreamableRenderResourceState ResourceState
The streamable state requested.
int32 ScheduledAsyncTasks
Number of Ticks scheduled on async tasks.
int32 ScheduledGTTasks
Number of Ticks scheduled on the game thread.
int32 ScheduledRenderTasks
Number of Ticks scheduled on the render thread.
const UStreamableRenderAsset * StreamableAsset = nullptr
The asset updated.
volatile ETaskState TaskState
The state of the work yet to be performed to complete the update or cancelation.
FThreadSafeCounter TaskSynchronization
Synchronization used for trigger the task next step execution.
Detailed Description
Definition at line 144 of file SkeletalMeshUpdate.h.
Constructor & Destructor Documentation
FSkeletalMeshStreamOut()
FSkeletalMeshStreamOut::FSkeletalMeshStreamOut (const USkeletalMesh * InMesh)
Definition at line 259 of file SkeletalMeshUpdate.cpp.
References FSkeletalMeshUpdate::FSkeletalMeshUpdate(), ConditionalMarkComponentsDirty(), TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), SRA_UPDATE_CALLBACK, FRenderAssetUpdate::TT_GameThread, and FRenderAssetUpdate::TT_None.
~FSkeletalMeshStreamOut()
virtual FSkeletalMeshStreamOut::~FSkeletalMeshStreamOut () inline virtual
Definition at line 149 of file SkeletalMeshUpdate.h.
Member Function Documentation
Cancel()
void FSkeletalMeshStreamOut::Cancel (const FContext & Context) private
Cancel the pending mip change.
Definition at line 403 of file SkeletalMeshUpdate.cpp.
References DECLARE_SCOPE_CYCLE_COUNTER, and TEXT.
Referenced by ConditionalMarkComponentsDirty(), and WaitForReferences().
ConditionalMarkComponentsDirty()
void FSkeletalMeshStreamOut::ConditionalMarkComponentsDirty (const FContext & Context) private
Notify components that the LOD is being streamed out so that they can release references.
Definition at line 265 of file SkeletalMeshUpdate.cpp.
References FSkeletalMeshUpdate::Abort(), Cancel(), check, CSV_SCOPED_TIMING_STAT_GLOBAL, DECLARE_SCOPE_CYCLE_COUNTER, IStreamingManager::Get(), IRenderAssetStreamingManager::GetAssetComponents(), FStreamingManagerCollection::GetTextureStreamingManager(), FRenderAssetUpdate::IsCancelled(), Mesh, TArray< InElementType, InAllocatorType >::Num(), TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), RenderData, FRenderAssetUpdate::ResourceState, SRA_UPDATE_CALLBACK, TEXT, FRenderAssetUpdate::TT_Async, FRenderAssetUpdate::TT_GameThread, and WaitForReferences().
Referenced by FSkeletalMeshStreamOut().
ReleaseBuffers()
void FSkeletalMeshStreamOut::ReleaseBuffers (const FContext & Context) private
Release RHI buffers and update SRVs.
Definition at line 348 of file SkeletalMeshUpdate.cpp.
References check, FSkeletalMeshLODRenderData::ClothVertexBuffer, FStaticMeshVertexBuffers::ColorVertexBuffer, FRenderAssetUpdate::CurrentFirstLODIdx, DECLARE_SCOPE_CYCLE_COUNTER, FSkeletalMeshLODRenderData::DecrementMemoryStats(), GSkelMeshMaxNumResourceUpdatesPerBatch, FSkeletalMeshLODRenderData::HalfEdgeBuffer, FRenderAssetUpdate::IsCancelled(), IsInRenderingThread(), IsRayTracingAllowed(), FRenderAssetUpdate::MarkAsSuccessfullyFinished(), Mesh, FSkeletalMeshLODRenderData::MultiSizeIndexContainer, FRenderAssetUpdate::PendingFirstLODIdx, FStaticMeshVertexBuffers::PositionVertexBuffer, FColorVertexBuffer::ReleaseRHIForStreaming(), FMultiSizeIndexContainer::ReleaseRHIForStreaming(), FPositionVertexBuffer::ReleaseRHIForStreaming(), FSkeletalMeshHalfEdgeBuffer::ReleaseRHIForStreaming(), FSkeletalMeshVertexClothBuffer::ReleaseRHIForStreaming(), FSkinWeightProfilesData::ReleaseRHIForStreaming(), FSkinWeightVertexBuffer::ReleaseRHIForStreaming(), FStaticMeshVertexBuffer::ReleaseRHIForStreaming(), RenderData, FSkeletalMeshLODRenderData::SkinWeightProfilesData, FSkeletalMeshLODRenderData::SkinWeightVertexBuffer, FStaticMeshVertexBuffers::StaticMeshVertexBuffer, FSkeletalMeshLODRenderData::StaticVertexBuffers, TEXT, and FRenderAssetUpdate::TT_Render.
Referenced by WaitForReferences().
WaitForReferences()
void FSkeletalMeshStreamOut::WaitForReferences (const FContext & Context) private
Wait for all references to be released.
Definition at line 301 of file SkeletalMeshUpdate.cpp.
References FRenderAssetUpdate::bDeferExecution, Cancel(), check, FRenderAssetUpdate::CurrentFirstLODIdx, DECLARE_SCOPE_CYCLE_COUNTER, GStreamingMaxReferenceChecks, Mesh, NumReferenceChecks, FRenderAssetUpdate::PendingFirstLODIdx, PreviousNumberOfExternalReferences, TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), ReleaseBuffers(), RenderData, SRA_UPDATE_CALLBACK, TEXT, FRenderAssetUpdate::TT_Async, FRenderAssetUpdate::TT_Render, UE_LOG, WaitForReferences(), and Warning.
Referenced by ConditionalMarkComponentsDirty(), and WaitForReferences().
Field Documentation
NumReferenceChecks
int32 FSkeletalMeshStreamOut::NumReferenceChecks = 0 private
Definition at line 153 of file SkeletalMeshUpdate.h.
Referenced by WaitForReferences().
PreviousNumberOfExternalReferences
uint32 FSkeletalMeshStreamOut::PreviousNumberOfExternalReferences = 0 private
Definition at line 154 of file SkeletalMeshUpdate.h.
Referenced by WaitForReferences().
The documentation for this class was generated from the following files:
SkeletalMeshUpdate.h
SkeletalMeshUpdate.cpp