Unreal Engine 5.6 C++ API: FNavigationElement Struct Reference
FNavigationElement Struct Reference
Structure registered in the navigation system that holds the required properties and delegates to gather navigation data (navigable geometry, NavArea modifiers, NavLinks, etc.) and be stored in the navigation octree.
#include "NavigationElement.h"
Data Structures
struct FPrivateToken
Public Member Functions
FNavigationElement ()=delete
FNavigationElement (const INavRelevantInterface &NavRelevant, uint64 SubElementId=INDEX_NONE)
FNavigationElement (const UObject &Object, uint64 SubElementId=INDEX_NONE)
FNavigationElement (FPrivateToken, const UObject *Object, uint64 SubElementId)
UBodySetup * GetBodySetup () const
FBox GetBounds () const
bool GetDirtyAreaOnRegistration () const
FString GetFullName () const
EHasCustomNavigableGeometry::Type GetGeometryExportType () const
ENavDataGatheringMode GetGeometryGatheringMode () const
FNavigationElementHandle GetHandle () const
Returns a handle that can be used to uniquely identify this element.
FString GetName () const
const TWeakObjectPtr< const UObject > & GetNavigationParent () const
FString GetPathName () const
const FTransform & GetTransform () const
TWeakObjectPtr< const UObject > GetWeakUObject () const
Returns a weak pointer to the UObject associated with this navigation element.
bool IsFromLevelVisibilityChange () const
bool IsInBaseNavigationData () const
void SetBodySetup (UBodySetup *InBodySetup)
Sets the body setup to use for the default geometry export.
void SetBounds (const FBox &InBounds)
Sets the Bounds to use when registering the element in the navigation octree.
void SetDirtyAreaOnRegistration (const bool bInDirtyAreaOnRegistration)
Sets whether the area covered by the navigation bounds should be dirtied when inserting, or removing, the element in the navigation octree (default behavior).
void SetGeometryExportType (const EHasCustomNavigableGeometry::Type InCustomNavigableGeometry)
Sets the type of geometry export to use for the current element.
void SetGeometryGatheringMode (const ENavDataGatheringMode InGeometryGatheringMode)
Sets the mode that indicates when the geometry gathering must be executed.
void SetNavigationParent (const UObject *InNavigationParent)
Sets the UObject for which the associated octree node will be used to hold the current element navigation data.
void SetTransform (const FTransform &InGeometryTransform)
Sets the Transform to use for the default geometry export.
UE_DEPRECATED (5.5, "Temporary constructor to allow deprecation of other navigation types. Use the version taking an object reference instead.") explicit FNavigationElement(const UObject *Object
Public Member Functions inherited from TSharedFromThis< FNavigationElement >
TSharedRef< FNavigationElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FNavigationElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FCustomGeometryExport CustomGeometryExportDelegate
Delegate used during the geometry export based on the specified GeometryExportType.
FGeometrySliceExport GeometrySliceExportDelegate
Delegate that can be used by very large elements to gather a limited piece of geometry for navigation generation in a given area.
FNavigationDataExport NavigationDataExportDelegate
Delegate used to gather navigation data like NavLinks, NavAreaModifiers, etc.
const uint64 SubElementId
Private Member Functions
FNavigationElement (const UObject &Object, uint64 SubElementId, bool bTryInitializeFromInterface)
void InitializeFromInterface (const INavRelevantInterface *NavRelevantInterface)
Static Private Member Functions
static TSharedRef< FNavigationElement > MakeFromUObject_DEPRECATED (UObject *InOwner)
Private Attributes
bool bDirtyAreaOnRegistration = true
Indicates if the area covered by the navigation bounds should be dirtied when inserting, or removing, the element in the navigation octree (default behavior).
bool bIsFromLevelVisibilityChange = false
Indicates that the element was created from a UObject while its level was pending being made invisible or visible (i.e., loading/unloading).
bool bIsInBaseNavigationData = false
Indicates that the element was created from a UObject that is associated with a data layer in the list of runtime data layers that should be included in the base navigation data (cooked) or directly placed in the level.
TWeakObjectPtr< UBodySetup > BodySetup = nullptr
Associated body setup (if any) used by the default geometry export.
FBox Bounds
Bounds used to register the element in the navigation octree.
EHasCustomNavigableGeometry::Type GeometryExportType
Indicates the type of geometry export to use for the current element.
ENavDataGatheringMode GeometryGatheringMode
Indicates when the geometry gathering must be executed:
FTransform GeometryTransform = FTransform::Identity
Transform used by the default geometry export.
TWeakObjectPtr< const UObject > NavigationParent = nullptr
Indicates that this element is not registered as a new node in the navigation octree, but instead adds its navigation data to the parent octree node.
TWeakObjectPtr< const UObject > OwnerUObject
The associated UObject provided to create the element.
uint64 SubElementId = INDEX_NONE
Optional ID that can be used when a UObject owns and manages multiple sub-elements which should be represented individually in the navigation system (i.e., each sub-element has its own bounds and should be registered in an octree node).
Friends
struct FNavigationDirtyElement
Temporary solution to provide access to deprecated constructors.
FString GetFullNameSafe (const FNavigationElement *Element)
FString GetNameSafe (const FNavigationElement *Element)
FString GetPathNameSafe (const FNavigationElement *Element)
uint32 GetTypeHash (const FNavigationElement &Element)
Hash function to use TSet/TMap.
FString LexToString (const FNavigationElement &Element)
Stringifies FNavigationElementHandle.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FNavigationElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FNavigationElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Structure registered in the navigation system that holds the required properties and delegates to gather navigation data (navigable geometry, NavArea modifiers, NavLinks, etc.) and be stored in the navigation octree.
It represents a single element spatially located in a defined area in the level. That element can be created to represent two use cases:
Single UObject representing the navigation element constructed from a UObject raw or weak pointer
Single UObject managing multiple non-UObject navigation elements constructed from a UObject raw or weak pointer and using the optional constructor parameter to identity a unique sub-element
See also
FNavigationElementHandle
Definition at line 88 of file NavigationElement.h.
Constructor & Destructor Documentation
FNavigationElement() [1/5]
FNavigationElement::FNavigationElement (FPrivateToken , const UObject * Object, uint64 SubElementId) explicit
References Object, and SubElementId.
Referenced by GetFullName(), GetFullNameSafe, GetNameSafe, GetPathNameSafe, GetTypeHash, and LexToString.
FNavigationElement() [2/5]
FNavigationElement::FNavigationElement () delete
FNavigationElement() [3/5]
FNavigationElement::FNavigationElement (const UObject & Object, uint64 SubElementId = INDEX_NONE) explicit
References INDEX_NONE, Object, and SubElementId.
FNavigationElement() [4/5]
FNavigationElement::FNavigationElement (const INavRelevantInterface & NavRelevant, uint64 SubElementId = INDEX_NONE) explicit
References INDEX_NONE, and SubElementId.
FNavigationElement() [5/5]
FNavigationElement::FNavigationElement (const UObject & Object, uint64 SubElementId, bool bTryInitializeFromInterface) explicit private
References Object, and SubElementId.
Member Function Documentation
GetBodySetup()
UBodySetup * FNavigationElement::GetBodySetup () const inline
Returns
The associated body setup (if any) to use for the default geometry export.
Definition at line 407 of file NavigationElement.h.
References BodySetup.
GetBounds()
FBox FNavigationElement::GetBounds () const inline
Returns
The bounds to use when registering the element in the navigation octree.
Definition at line 397 of file NavigationElement.h.
References Bounds.
GetDirtyAreaOnRegistration()
bool FNavigationElement::GetDirtyAreaOnRegistration () const inline
Returns
True the area covered by the navigation bounds should be dirtied when inserting, or removing, the element in the navigation octree (default behavior).
See also
DirtyAreaOnRegistration
Definition at line 442 of file NavigationElement.h.
References bDirtyAreaOnRegistration.
GetFullName()
FString FNavigationElement::GetFullName () const
Returns
Name describing the element based on the associated UObject fullname and sub-element ID (if any).
References FNavigationElement().
Referenced by GetFullNameSafe.
GetGeometryExportType()
EHasCustomNavigableGeometry::Type FNavigationElement::GetGeometryExportType () const inline
Returns
The type of geometry export to use for the current element
See also
EHasCustomNavigableGeometry
Definition at line 422 of file NavigationElement.h.
References GeometryExportType.
GetGeometryGatheringMode()
ENavDataGatheringMode FNavigationElement::GetGeometryGatheringMode () const inline
Returns
The mode that indicates when the geometry gathering must be executed.
See also
GeometryGatheringMode
Definition at line 432 of file NavigationElement.h.
References GeometryGatheringMode.
GetHandle()
FNavigationElementHandle FNavigationElement::GetHandle () const
Returns a handle that can be used to uniquely identify this element.
Returns
Handle representing the current element.
GetName()
FString FNavigationElement::GetName () const
Returns
Name describing the element based on the associated UObject name and sub-element ID (if any).
Referenced by GetNameSafe.
GetNavigationParent()
const TWeakObjectPtr< const UObject > & FNavigationElement::GetNavigationParent () const inline
Returns
The UObject for which the associated octree node will be used to hold the current element navigation data.
Definition at line 412 of file NavigationElement.h.
References NavigationParent.
GetPathName()
FString FNavigationElement::GetPathName () const
Returns
Name describing the element based on the associated UObject pathname and sub-element ID (if any).
Referenced by GetPathNameSafe.
GetTransform()
const FTransform & FNavigationElement::GetTransform () const inline
Returns
Transform to use for the default geometry export.
Definition at line 387 of file NavigationElement.h.
References GeometryTransform.
GetWeakUObject()
TWeakObjectPtr< const UObject > FNavigationElement::GetWeakUObject () const inline
Returns a weak pointer to the UObject associated with this navigation element.
Returns
Weak pointer to the associated UObject if any.
Note
If called from the Game thread all regular TWeakObjectPtr concerns and limitation applies.
Definition at line 372 of file NavigationElement.h.
References OwnerUObject.
InitializeFromInterface()
void FNavigationElement::InitializeFromInterface (const INavRelevantInterface * NavRelevantInterface) private
IsFromLevelVisibilityChange()
bool FNavigationElement::IsFromLevelVisibilityChange () const inline
Returns
True if the element was created from a UObject while its level was pending being made invisible or visible (i.e., loading/unloading).
Definition at line 377 of file NavigationElement.h.
References bIsFromLevelVisibilityChange.
IsInBaseNavigationData()
bool FNavigationElement::IsInBaseNavigationData () const inline
Returns
True if the element was created from a UObject that is associated with a data layer in the list of runtime data layers that should be included in the base navigation data (cooked) or directly placed in the level.
Definition at line 382 of file NavigationElement.h.
References bIsInBaseNavigationData.
MakeFromUObject_DEPRECATED()
TSharedRef< FNavigationElement > FNavigationElement::MakeFromUObject_DEPRECATED (UObject * InOwner) inline static private
Definition at line 94 of file NavigationElement.h.
References INDEX_NONE, and MakeShared().
SetBodySetup()
void FNavigationElement::SetBodySetup (UBodySetup * InBodySetup)
Sets the body setup to use for the default geometry export.
SetBounds()
void FNavigationElement::SetBounds (const FBox & InBounds) inline
Sets the Bounds to use when registering the element in the navigation octree.
Definition at line 402 of file NavigationElement.h.
References Bounds.
SetDirtyAreaOnRegistration()
void FNavigationElement::SetDirtyAreaOnRegistration (const bool bInDirtyAreaOnRegistration) inline
Sets whether the area covered by the navigation bounds should be dirtied when inserting, or removing, the element in the navigation octree (default behavior).
See also
DirtyAreaOnRegistration
Definition at line 447 of file NavigationElement.h.
References bDirtyAreaOnRegistration.
SetGeometryExportType()
void FNavigationElement::SetGeometryExportType (const EHasCustomNavigableGeometry::Type InCustomNavigableGeometry) inline
Sets the type of geometry export to use for the current element.
See also
GeometryExportType
Definition at line 427 of file NavigationElement.h.
References GeometryExportType.
SetGeometryGatheringMode()
void FNavigationElement::SetGeometryGatheringMode (const ENavDataGatheringMode InGeometryGatheringMode) inline
Sets the mode that indicates when the geometry gathering must be executed.
See also
GeometryGatheringMode
Definition at line 437 of file NavigationElement.h.
References GeometryGatheringMode.
SetNavigationParent()
void FNavigationElement::SetNavigationParent (const UObject * InNavigationParent) inline
Sets the UObject for which the associated octree node will be used to hold the current element navigation data.
Definition at line 417 of file NavigationElement.h.
References NavigationParent.
SetTransform()
void FNavigationElement::SetTransform (const FTransform & InGeometryTransform) inline
Sets the Transform to use for the default geometry export.
Definition at line 392 of file NavigationElement.h.
References GeometryTransform.
UE_DEPRECATED()
FNavigationElement::UE_DEPRECATED (5. 5, "Temporary constructor to allow deprecation of other navigation types. Use the version taking an object reference instead.") const
Friends And Related Symbol Documentation
FNavigationDirtyElement
friend struct FNavigationDirtyElement friend
Temporary solution to provide access to deprecated constructors.
Definition at line 92 of file NavigationElement.h.
References FNavigationDirtyElement.
Referenced by FNavigationDirtyElement.
GetFullNameSafe
FString GetFullNameSafe (const FNavigationElement * Element) friend
Returns
Name describing the specified element based on the fullname of its associated UObject and sub-element ID (if any).
Definition at line 325 of file NavigationElement.h.
References FNavigationElement(), GetFullName(), and TEXT.
GetNameSafe
FString GetNameSafe (const FNavigationElement * Element) friend
Returns
Name describing the specified element based on the name of its associated UObject and sub-element ID (if any).
Definition at line 315 of file NavigationElement.h.
References FNavigationElement(), GetName(), and TEXT.
GetPathNameSafe
FString GetPathNameSafe (const FNavigationElement * Element) friend
Returns
Name describing the specified element based on the pathname of its associated UObject and sub-element ID (if any).
Definition at line 320 of file NavigationElement.h.
References FNavigationElement(), GetPathName(), and TEXT.
GetTypeHash
uint32 GetTypeHash (const FNavigationElement & Element) friend
Hash function to use TSet/TMap.
References FNavigationElement().
LexToString
FString LexToString (const FNavigationElement & Element) friend
Stringifies FNavigationElementHandle.
References FNavigationElement().
Field Documentation
bDirtyAreaOnRegistration
bool FNavigationElement::bDirtyAreaOnRegistration = true private
Indicates if the area covered by the navigation bounds should be dirtied when inserting, or removing, the element in the navigation octree (default behavior).
When returning false it is expected that the element will explicitly dirty areas (e.g. using UpdateNavigationElementBoundsDelegate).
Definition at line 293 of file NavigationElement.h.
Referenced by GetDirtyAreaOnRegistration(), and SetDirtyAreaOnRegistration().
bIsFromLevelVisibilityChange
bool FNavigationElement::bIsFromLevelVisibilityChange = false private
Indicates that the element was created from a UObject while its level was pending being made invisible or visible (i.e., loading/unloading).
Definition at line 303 of file NavigationElement.h.
Referenced by IsFromLevelVisibilityChange().
bIsInBaseNavigationData
bool FNavigationElement::bIsInBaseNavigationData = false private
Indicates that the element was created from a UObject that is associated with a data layer in the list of runtime data layers that should be included in the base navigation data (cooked) or directly placed in the level.
Definition at line 300 of file NavigationElement.h.
Referenced by IsInBaseNavigationData().
BodySetup
TWeakObjectPtr<UBodySetup> FNavigationElement::BodySetup = nullptr private
Associated body setup (if any) used by the default geometry export.
Definition at line 261 of file NavigationElement.h.
Referenced by GetBodySetup().
Bounds
FBox FNavigationElement::Bounds private
Bounds used to register the element in the navigation octree.
Definition at line 267 of file NavigationElement.h.
Referenced by GetBounds(), and SetBounds().
CustomGeometryExportDelegate
FCustomGeometryExport FNavigationElement::CustomGeometryExportDelegate
Delegate used during the geometry export based on the specified GeometryExportType.
See also
GeometryExportType
Definition at line 236 of file NavigationElement.h.
GeometryExportType
EHasCustomNavigableGeometry::Type FNavigationElement::GeometryExportType private
Indicates the type of geometry export to use for the current element.
See also
EHasCustomNavigableGeometry
Definition at line 279 of file NavigationElement.h.
Referenced by GetGeometryExportType(), and SetGeometryExportType().
GeometryGatheringMode
ENavDataGatheringMode FNavigationElement::GeometryGatheringMode private
Indicates when the geometry gathering must be executed:
Instant: The geometry export is executed as soon as the element is registered in the navigation octree.
Lazy: The geometry export is executed only when it is required to rebuild the navigation data intersecting with a given area (e.g., Tile generator).
Default: Use the default gathering mode defined by the navigation system.
Definition at line 287 of file NavigationElement.h.
Referenced by GetGeometryGatheringMode(), and SetGeometryGatheringMode().
GeometrySliceExportDelegate
FGeometrySliceExport FNavigationElement::GeometrySliceExportDelegate
Delegate that can be used by very large elements to gather a limited piece of geometry for navigation generation in a given area.
Definition at line 239 of file NavigationElement.h.
GeometryTransform
FTransform FNavigationElement::GeometryTransform = FTransform::Identity private
Transform used by the default geometry export.
Definition at line 264 of file NavigationElement.h.
Referenced by GetTransform(), and SetTransform().
NavigationDataExportDelegate
FNavigationDataExport FNavigationElement::NavigationDataExportDelegate
Delegate used to gather navigation data like NavLinks, NavAreaModifiers, etc.
Definition at line 230 of file NavigationElement.h.
NavigationParent
TWeakObjectPtr<const UObject> FNavigationElement::NavigationParent = nullptr private
Indicates that this element is not registered as a new node in the navigation octree, but instead adds its navigation data to the parent octree node.
Definition at line 273 of file NavigationElement.h.
Referenced by GetNavigationParent(), and SetNavigationParent().
OwnerUObject
TWeakObjectPtr<const UObject> FNavigationElement::OwnerUObject private
The associated UObject provided to create the element.
It is still currently used after creation for: ShouldSkipObjectPredicate (dirty areas), MetaModifier, logging and validation. This is always set when creating the object and should be valid for the lifetime of the element if it is properly unregistered based on the UObject lifetime (e.g., a Component will unregister its associated element when it gets unregistered from the world).
Definition at line 252 of file NavigationElement.h.
Referenced by GetWeakUObject().
SubElementId [1/2]
const uint64 FNavigationElement::SubElementId
Initial value:
= INDEX_NONE)
        : FNavigationElement(FPrivateToken{}, Object, SubElementId)
    {
    }
    static 1 TSharedRef<const FNavigationElement> CreateFromNavRelevantInterface(const INavRelevantInterface& NavRelevantInterface)
Definition at line 109 of file NavigationElement.h.
Referenced by FNavigationElement(), FNavigationElement(), FNavigationElement(), and FNavigationElement().
SubElementId [2/2]
uint64 FNavigationElement::SubElementId = INDEX_NONE private
Optional ID that can be used when a UObject owns and manages multiple sub-elements which should be represented individually in the navigation system (i.e., each sub-element has its own bounds and should be registered in an octree node).
Definition at line 258 of file NavigationElement.h.
The documentation for this struct was generated from the following file:
NavigationElement.h