Unreal Engine 5.6 C++ API: TLazyObjectPtr< T > Struct Template Reference
TLazyObjectPtr< T > Struct Template Reference
TLazyObjectPtr is the templatized version of the generic FLazyObjectPtr.
#include "LazyObjectPtr.h"
Public Types
using ElementType = T
Public Member Functions
TLazyObjectPtr ()=default
TLazyObjectPtr (const TLazyObjectPtr< T > &)=default
template<typename U UE_REQUIRES>
FORCEINLINE TLazyObjectPtr (const TLazyObjectPtr< U > &Other)
Construct from another lazy pointer with implicit upcasting allowed.
FORCEINLINE TLazyObjectPtr (T *Object)
Construct from an object pointer.
TLazyObjectPtr (TLazyObjectPtr< T > &&)=default
FORCEINLINE T * Get () const
Dereference the lazy pointer.
FORCEINLINE uint32 GetLazyObjecPtrTypeHash () const
Hash function.
FORCEINLINE const FUniqueObjectGuid & GetUniqueID () const
Gets the unique object identifier associated with this lazy pointer.
FORCEINLINE bool IsNull () const
Test if this can never point to a live UObject.
FORCEINLINE bool IsPending () const
Test if this does not point to a live UObject, but may in the future.
FORCEINLINE bool IsStale () const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
FORCEINLINE operator bool () const
Dereference lazy pointer to see if it points somewhere valid.
template<typename U, typename = decltype((T*)nullptr != (U*)nullptr)>
FORCEINLINE bool operator!= (const TLazyObjectPtr< U > &Rhs) const
template<typename U, typename = decltype((T*)nullptr != (U*)nullptr)>
FORCEINLINE bool operator!= (const U *Rhs) const
Compare for inequality with a raw pointer.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
Compare for inequality with null.
FORCEINLINE T & operator* () const
Dereference the lazy pointer.
FORCEINLINE T * operator-> () const
Dereference the lazy pointer.
FORCEINLINE void operator= (const FUniqueObjectGuid &InObjectID)
Copy from a unique object identifier WARNING: this doesn't check the type of the object is correct, because the object corresponding to this ID may not even be loaded!
TLazyObjectPtr< T > & operator= (const TLazyObjectPtr< T > &)=default
template<typename U UE_REQUIRES>
FORCEINLINE TLazyObjectPtr< T > & operator= (const TLazyObjectPtr< U > &Other)
Assign from another lazy pointer with implicit upcasting allowed.
FORCEINLINE void operator= (T *Object)
Copy from an object pointer.
TLazyObjectPtr< T > & operator= (TLazyObjectPtr< T > &&)=default
template<typename U, typename = decltype((T*)nullptr == (U*)nullptr)>
FORCEINLINE bool operator== (const TLazyObjectPtr< U > &Rhs) const
Compare with another TLazyObjectPtr of related type.
template<typename U, typename = decltype((T*)nullptr == (U*)nullptr)>
FORCEINLINE bool operator== (const U *Rhs) const
Compare for equality with a raw pointer.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
Compare to null.
FORCEINLINE void Reset ()
Reset the lazy pointer back to the null state.
FORCEINLINE void SerializePtr (FArchive &Ar)
Additional Inherited Members
Private Types inherited from TPersistentObjectPtr< FUniqueObjectGuid >
using ElementType
Private Member Functions inherited from FLazyObjectPtr
FORCEINLINE FLazyObjectPtr ()
Default constructor, sets to null.
FORCEINLINE FLazyObjectPtr (const UObject *Object)
FORCEINLINE FLazyObjectPtr (FObjectPtr Object)
Construct from object already in memory.
template<typename T>
FORCEINLINE FLazyObjectPtr (TObjectPtr< T > Object)
FORCEINLINE void FixupForPIE (int32 PIEInstance)
Fixes up this FLazyObjectPtr to target the right UID as set in PIEGuidMap, this only works for directly serialized pointers.
FORCEINLINE void operator= (const FUniqueObjectGuid &InObjectID)
Copy from a unique object identifier.
FORCEINLINE void operator= (const UObject *Object)
FORCEINLINE void operator= (FObjectPtr Object)
Copy from an object already in memory.
template<typename T>
FORCEINLINE void operator= (TObjectPtr< T > Object)
Private Member Functions inherited from TPersistentObjectPtr< FUniqueObjectGuid >
FORCEINLINE TPersistentObjectPtr ()
Default constructor, will be null.
FORCEINLINE TPersistentObjectPtr (const FUniqueObjectGuid &InObjectID)
Construct from a unique object identifier.
FORCEINLINE UObject * Get () const
Dereference the pointer, which may cause it to become valid again.
FORCEINLINE UObject * Get (bool bEvenIfPendingKill) const
Dereference the lazy pointer, which may cause it to become valid again.
FORCEINLINE FUniqueObjectGuid & GetUniqueID ()
Non-const version of the above.
FORCEINLINE const FUniqueObjectGuid & GetUniqueID () const
Gets the unique object identifier associated with this lazy pointer.
FORCEINLINE bool IsNull () const
Test if this can never point to a live UObject.
FORCEINLINE bool IsPending () const
Test if this does not point to a live UObject, but may in the future.
FORCEINLINE bool IsStale () const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
FORCEINLINE bool operator!= (const TPersistentObjectPtr &Rhs) const
Compare pointers for inequality.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
FORCEINLINE UObject & operator* () const
Dereference the pointer.
FORCEINLINE UObject * operator-> () const
Dereference the pointer.
FORCEINLINE void operator= (const FUniqueObjectGuid &InObjectID)
Copy from a unique object identifier.
FORCEINLINE void operator= (const FWeakObjectPtr &Other)
Copy from an existing weak pointer, reserve IDs if required.
FORCEINLINE void operator= (const UObject *Object)
void operator= (FObjectPtr Object)
Copy from an object pointer.
FORCEINLINE void operator= (TObjectPtr< T > Object)
FORCEINLINE bool operator== (const TPersistentObjectPtr &Rhs) const
Compare pointers for equality.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
FORCEINLINE void Reset ()
Reset the lazy pointer back to the null state.
FORCEINLINE void ResetWeakPtr ()
Resets the weak ptr only, call this when ObjectId may change.
Static Private Member Functions inherited from FLazyObjectPtr
static void PossiblySerializeObjectGuid (UObject *Object, FStructuredArchive::FRecord Record)
Called by UObject::Serialize so that we can save / load the Guid possibly associated with an object.
static void ResetPIEFixups ()
Called when entering PIE to prepare it for PIE-specific fixups.
Detailed Description
template<class T = UObject>
struct TLazyObjectPtr< T >
TLazyObjectPtr is the templatized version of the generic FLazyObjectPtr.
NOTE: This will be deprecated in a future engine version and new features should use TSoftObjectPtr instead.
Definition at line 229 of file LazyObjectPtr.h.
Member Typedef Documentation
ElementType
template<class T = UObject> using TLazyObjectPtr< T >::ElementType = T
Definition at line 232 of file LazyObjectPtr.h.
Constructor & Destructor Documentation
TLazyObjectPtr() [1/5]
template<class T = UObject> TLazyObjectPtr< T >::TLazyObjectPtr () default
Referenced by TLazyObjectPtr(), TLazyObjectPtr(), TLazyObjectPtr(), operator!=(), operator=(), operator=(), operator=(), and operator==().
TLazyObjectPtr() [2/5]
template<class T = UObject> TLazyObjectPtr< T >::TLazyObjectPtr (TLazyObjectPtr< T > &&) default
References TLazyObjectPtr().
TLazyObjectPtr() [3/5]
template<class T = UObject> TLazyObjectPtr< T >::TLazyObjectPtr (const TLazyObjectPtr< T > &) default
References TLazyObjectPtr().
TLazyObjectPtr() [4/5]
template<class T = UObject> template<typename U UE_REQUIRES> FORCEINLINE TLazyObjectPtr< T >::TLazyObjectPtr (const TLazyObjectPtr< U > & Other) inline
Construct from another lazy pointer with implicit upcasting allowed.
Definition at line 246 of file LazyObjectPtr.h.
References FLazyObjectPtr::FLazyObjectPtr(), TLazyObjectPtr(), FORCEINLINE, and Other.
TLazyObjectPtr() [5/5]
template<class T = UObject> FORCEINLINE TLazyObjectPtr< T >::TLazyObjectPtr (T * Object) inline
Construct from an object pointer.
Definition at line 263 of file LazyObjectPtr.h.
References FORCEINLINE, Object, and FLazyObjectPtr::operator=().
Member Function Documentation
Get()
template<class T = UObject> FORCEINLINE T * TLazyObjectPtr< T >::Get () const inline
Dereference the lazy pointer.
Returns
nullptr if this object is gone or the lazy pointer was null, otherwise a valid UObject pointer
Definition at line 307 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::Get().
Referenced by operator!=(), operator!=(), operator*(), operator->(), operator==(), and operator==().
GetLazyObjecPtrTypeHash()
template<class T = UObject> FORCEINLINE uint32 TLazyObjectPtr< T >::GetLazyObjecPtrTypeHash () const inline
Hash function.
Definition at line 370 of file LazyObjectPtr.h.
References FLazyObjectPtr::FLazyObjectPtr(), FORCEINLINE, and GetTypeHash().
GetUniqueID()
template<class T = UObject> FORCEINLINE const FUniqueObjectGuid & TLazyObjectPtr< T >::GetUniqueID () const inline
Gets the unique object identifier associated with this lazy pointer.
Valid even if pointer is not currently valid
Returns
Unique ID for this object, or an invalid FUniqueObjectID if this pointer isn't set to anything
Definition at line 297 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::GetUniqueID().
IsNull()
template<class T = UObject> FORCEINLINE bool TLazyObjectPtr< T >::IsNull () const inline
Test if this can never point to a live UObject.
Returns
true if this is explicitly pointing to no object
Definition at line 358 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::IsNull().
IsPending()
template<class T = UObject> FORCEINLINE bool TLazyObjectPtr< T >::IsPending () const inline
Test if this does not point to a live UObject, but may in the future.
Returns
true if this does not point to a real object, but could possibly
Definition at line 348 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::IsPending().
IsStale()
template<class T = UObject> FORCEINLINE bool TLazyObjectPtr< T >::IsStale () const inline
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
Returns
true if this used to point at a real object but no longer does.
Definition at line 338 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::IsStale().
IsValid()
template<class T = UObject> FORCEINLINE bool TLazyObjectPtr< T >::IsValid () const inline
Test if this points to a live UObject.
Definition at line 328 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::IsValid().
Referenced by operator bool(), operator!=(), operator!=(), operator==(), and operator==().
operator bool()
template<class T = UObject> FORCEINLINE TLazyObjectPtr< T >::operator bool () const inline explicit
Dereference lazy pointer to see if it points somewhere valid.
Definition at line 364 of file LazyObjectPtr.h.
References FORCEINLINE, and IsValid().
operator!=() [1/3]
template<class T = UObject> template<typename U, typename = decltype((T*)nullptr != (U*)nullptr)> FORCEINLINE bool TLazyObjectPtr< T >::operator!= (const TLazyObjectPtr< U > & Rhs) const inline
Definition at line 387 of file LazyObjectPtr.h.
References FLazyObjectPtr::FLazyObjectPtr(), TLazyObjectPtr(), and FORCEINLINE.
operator!=() [2/3]
template<class T = UObject> template<typename U, typename = decltype((T*)nullptr != (U*)nullptr)> FORCEINLINE bool TLazyObjectPtr< T >::operator!= (const U * Rhs) const inline
Compare for inequality with a raw pointer.
Definition at line 406 of file LazyObjectPtr.h.
References FORCEINLINE, and Get().
operator!=() [3/3]
template<class T = UObject> FORCEINLINE bool TLazyObjectPtr< T >::operator!= (TYPE_OF_NULLPTR) const inline
Compare for inequality with null.
Definition at line 412 of file LazyObjectPtr.h.
References FORCEINLINE, and IsValid().
operator*()
template<class T = UObject> FORCEINLINE T & TLazyObjectPtr< T >::operator* () const inline
Dereference the lazy pointer.
Definition at line 316 of file LazyObjectPtr.h.
References FORCEINLINE, and Get().
operator->()
template<class T = UObject> FORCEINLINE T * TLazyObjectPtr< T >::operator-> () const inline
Dereference the lazy pointer.
Definition at line 322 of file LazyObjectPtr.h.
References FORCEINLINE, and Get().
operator=() [1/5]
template<class T = UObject> FORCEINLINE void TLazyObjectPtr< T >::operator= (const FUniqueObjectGuid & InObjectID) inline
Copy from a unique object identifier WARNING: this doesn't check the type of the object is correct, because the object corresponding to this ID may not even be loaded!
Parameters
ObjectID Object identifier to create a lazy pointer to
Definition at line 287 of file LazyObjectPtr.h.
References FORCEINLINE, and FLazyObjectPtr::operator=().
operator=() [2/5]
template<class T = UObject> TLazyObjectPtr< T > & TLazyObjectPtr< T >::operator= (const TLazyObjectPtr< T > &) default
References TLazyObjectPtr().
operator=() [3/5]
template<class T = UObject> template<typename U UE_REQUIRES> FORCEINLINE TLazyObjectPtr< T > & TLazyObjectPtr< T >::operator= (const TLazyObjectPtr< U > & Other) inline
Assign from another lazy pointer with implicit upcasting allowed.
Definition at line 256 of file LazyObjectPtr.h.
References FLazyObjectPtr::FLazyObjectPtr(), TLazyObjectPtr(), FORCEINLINE, FLazyObjectPtr::operator=(), and Other.
operator=() [4/5]
template<class T = UObject> FORCEINLINE void TLazyObjectPtr< T >::operator= (T * Object) inline
Copy from an object pointer.
Definition at line 275 of file LazyObjectPtr.h.
References FORCEINLINE, Object, and FLazyObjectPtr::operator=().
operator=() [5/5]
template<class T = UObject> TLazyObjectPtr< T > & TLazyObjectPtr< T >::operator= (TLazyObjectPtr< T > &&) default
References TLazyObjectPtr().
operator==() [1/3]
template<class T = UObject> template<typename U, typename = decltype((T*)nullptr == (U*)nullptr)> FORCEINLINE bool TLazyObjectPtr< T >::operator== (const TLazyObjectPtr< U > & Rhs) const inline
Compare with another TLazyObjectPtr of related type.
Definition at line 382 of file LazyObjectPtr.h.
References FLazyObjectPtr::FLazyObjectPtr(), TLazyObjectPtr(), and FORCEINLINE.
operator==() [2/3]
template<class T = UObject> template<typename U, typename = decltype((T*)nullptr == (U*)nullptr)> FORCEINLINE bool TLazyObjectPtr< T >::operator== (const U * Rhs) const inline
Compare for equality with a raw pointer.
Definition at line 394 of file LazyObjectPtr.h.
References FORCEINLINE, and Get().
operator==() [3/3]
template<class T = UObject> FORCEINLINE bool TLazyObjectPtr< T >::operator== (TYPE_OF_NULLPTR) const inline
Compare to null.
Definition at line 400 of file LazyObjectPtr.h.
References FORCEINLINE, and IsValid().
Reset()
template<class T = UObject> FORCEINLINE void TLazyObjectPtr< T >::Reset () inline
Reset the lazy pointer back to the null state.
Definition at line 269 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::Reset().
SerializePtr()
template<class T = UObject> FORCEINLINE void TLazyObjectPtr< T >::SerializePtr (FArchive & Ar) inline
Definition at line 375 of file LazyObjectPtr.h.
References Ar, and FORCEINLINE.
The documentation for this struct was generated from the following file:
LazyObjectPtr.h