Unreal Engine 5.6 C++ API: IInterface_PostProcessVolume Class Reference
IInterface_PostProcessVolume Class Reference abstract
Interface for general PostProcessVolume access.
#include "Interface_PostProcessVolume.h"
Private Member Functions
GENERATED_IINTERFACE_BODY () virtual bool EncompassesPoint(FVector Point
virtual FString GetDebugName () const =0
virtual FPostProcessVolumeProperties GetProperties () const =0
Private Attributes
float float * OutDistanceToPoint = 0
float SphereRadius
Detailed Description
Interface for general PostProcessVolume access.
Definition at line 31 of file Interface_PostProcessVolume.h.
Member Function Documentation
GENERATED_IINTERFACE_BODY()
IInterface_PostProcessVolume::GENERATED_IINTERFACE_BODY () private
GetDebugName()
virtual FString IInterface_PostProcessVolume::GetDebugName () const private pure virtual
Referenced by UCLASS().
GetProperties()
virtual FPostProcessVolumeProperties IInterface_PostProcessVolume::GetProperties () const private pure virtual
Implemented in FUnderwaterPostProcessVolume, and UPostProcessComponent.
References GetProperties().
Referenced by GetProperties(), and UCLASS().
Field Documentation
OutDistanceToPoint
float float* IInterface_PostProcessVolume::OutDistanceToPoint = 0 private
Definition at line 35 of file Interface_PostProcessVolume.h.
Referenced by FUnderwaterPostProcessVolume::EncompassesPoint(), and UPostProcessComponent::EncompassesPoint().
SphereRadius
float IInterface_PostProcessVolume::SphereRadius private
Definition at line 35 of file Interface_PostProcessVolume.h.
Referenced by FUnderwaterPostProcessVolume::EncompassesPoint(), and UPostProcessComponent::EncompassesPoint().
The documentation for this class was generated from the following file:
Interface_PostProcessVolume.h