Unreal Engine 5.6 C++ API: MovieSceneFloatChannel.h File Reference
MovieSceneFloatChannel.h File Reference
#include "Channels/MovieSceneChannelEditorData.h"
#include "Channels/MovieSceneCurveChannelCommon.h"
#include "Channels/MovieScenePiecewiseCurve.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/EnumAsByte.h"
#include "CoreTypes.h"
#include "Curves/KeyHandle.h"
#include "Curves/RealCurve.h"
#include "Curves/RichCurve.h"
#include "HAL/PlatformCrt.h"
#include "KeyParams.h"
#include "Math/Range.h"
#include "Misc/FrameNumber.h"
#include "Misc/FrameRate.h"
#include "Misc/FrameTime.h"
#include "Misc/Optional.h"
#include "MovieSceneChannel.h"
#include "MovieSceneChannelData.h"
#include "MovieSceneChannelTraits.h"
#include "Serialization/StructuredArchive.h"
#include "Templates/Tuple.h"
#include "Templates/UnrealTemplate.h"
#include "UObject/Class.h"
#include "UObject/ObjectMacros.h"
#include "MovieSceneFloatChannel.generated.h"
Data Structures
struct TIsPODType< FMovieSceneFloatValue >
struct TMovieSceneChannelTraits< FMovieSceneFloatChannel >
struct TStructOpsTypeTraits< FMovieSceneFloatChannel >
struct TStructOpsTypeTraits< FMovieSceneFloatValue >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
namespace UE::MovieScene::Interpolation
This file contains structures that represent specific interpolation algorithms for either a continuous or discrete range.
Functions
MOVIESCENE_API FKeyHandle AddKeyToChannel (FMovieSceneFloatChannel *Channel, FFrameNumber InFrameNumber, float InValue, EMovieSceneKeyInterpolation Interpolation)
Overload for adding a new key to a float channel at a given time.
MOVIESCENE_API void AssignValue (FMovieSceneFloatChannel *InChannel, FKeyHandle InKeyHandle, float InValue)
MOVIESCENE_API void Dilate (FMovieSceneFloatChannel *InChannel, FFrameNumber Origin, float DilationFactor)
Overload for dilating float channel data.
MOVIESCENE_API EMovieSceneKeyInterpolation GetInterpolationMode (FMovieSceneFloatChannel *InChannel, const FFrameNumber &InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode)
Overload for getting the interpolation mode for a channel at a specified time, it could be the previous key's mode.See UE::MovieScene::GetInterpolationMode for default implementation.
MOVIESCENE_API void UE::MovieScene::OnRemapChannelKeyTime (const FMovieSceneChannel *Channel, const IRetimingInterface &Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, FMovieSceneFloatValue &InOutValue)
USTRUCT () struct FMovieSceneFloatValue
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneFloatChannel *InChannel, FFrameNumber InFrameNumber, const FMovieSceneFloatValue &InValue)
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneFloatChannel *InChannel, FFrameNumber InFrameNumber, float InValue)
Overloads for common utility functions.
Function Documentation
AddKeyToChannel()
MOVIESCENE_API FKeyHandle AddKeyToChannel (FMovieSceneFloatChannel * Channel, FFrameNumber InFrameNumber, float InValue, EMovieSceneKeyInterpolation Interpolation)
Overload for adding a new key to a float channel at a given time.
See UE::MovieScene::AddKeyToChannel for default implementation.
References Interpolation.
AssignValue()
MOVIESCENE_API void AssignValue (FMovieSceneFloatChannel * InChannel, FKeyHandle InKeyHandle, float InValue)
Dilate()
MOVIESCENE_API void Dilate (FMovieSceneFloatChannel * InChannel, FFrameNumber Origin, float DilationFactor)
Overload for dilating float channel data.
See UE::MovieScene::Dilate for default implementation.
References Origin.
GetInterpolationMode()
MOVIESCENE_API EMovieSceneKeyInterpolation GetInterpolationMode (FMovieSceneFloatChannel * InChannel, const FFrameNumber & InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode)
Overload for getting the interpolation mode for a channel at a specified time, it could be the previous key's mode.See UE::MovieScene::GetInterpolationMode for default implementation.
References InTime.
USTRUCT()
USTRUCT ()
float value = 4 bytes tangent data = 4 floats + byte enum = 4*4 + 1 = 17 bytes, rounded up to 20 bytes on clang-win64 interp and tangent modes = 2 byte enums = 2 bytes total = 26 bytes
Definition at line 48 of file MovieSceneFloatChannel.h.
References Ar, Category, GENERATED_BODY, operator!=(), operator<<(), operator==(), Other, FArchive::Serialize(), Tangent, UPROPERTY, and Value.
ValueExistsAtTime() [1/2]
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneFloatChannel * InChannel, FFrameNumber InFrameNumber, const FMovieSceneFloatValue & InValue)
ValueExistsAtTime() [2/2]
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneFloatChannel * InChannel, FFrameNumber InFrameNumber, float InValue)
Overloads for common utility functions.