Unreal Engine 5.6 C++ API: FReferenceCollector Class Reference
FReferenceCollector Class Reference abstract
Used by garbage collector to collect references via virtual AddReferencedObjects calls.
#include "UObjectGlobals.h"
Data Structures
struct AROPrivate
Public Member Functions
virtual ~FReferenceCollector ()
void AddPropertyReferences (const UStruct *Struct, void *Instance, const UObject *ReferencingObject=nullptr)
Adds all strong property references from a struct instance, but not the struct itself.
void AddPropertyReferencesLimitedToObjectProperties (const UStruct *Struct, void *Instance, const UObject *ReferencingObject=nullptr)
Internal use only.
void AddPropertyReferencesWithStructARO (const UClass *Class, void *Instance, const UObject *ReferencingObject=nullptr)
Same as AddPropertyReferences but also calls AddStructReferencedObjects on all nested structs.
void AddPropertyReferencesWithStructARO (const UScriptStruct *Struct, void *Instance, const UObject *ReferencingObject=nullptr)
Same as AddPropertyReferences but also calls AddStructReferencedObjects on Struct and all nested structs.
template<class UObjectType>
void AddReferencedObject (const UObjectType *&Object, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds const object reference, this reference can still be nulled out if forcefully collected.
void AddReferencedObject (FWeakObjectPtr &P, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<class UObjectType>
void AddReferencedObject (TObjectPtr< const UObjectType > &Object, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds const object reference, this reference can still be nulled out if forcefully collected.
template<class UObjectType>
void AddReferencedObject (TObjectPtr< UObjectType > &Object, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds object reference.
template<typename T>
void AddReferencedObject (TWeakObjectPtr< T > &P, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<class UObjectType>
void AddReferencedObject (UObjectType *&Object, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds object reference.
void AddReferencedObjects (const UScriptStruct *&ScriptStruct, void *Instance, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds all strong property references from a UScriptStruct instance including the struct itself.
template<class UObjectType>
void AddReferencedObjects (TArray< const UObjectType * > &ObjectArray, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to an array of const objects, these objects can still be nulled out if forcefully collected.
template<class UObjectType>
void AddReferencedObjects (TArray< TObjectPtr< const UObjectType > > &ObjectArray, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to an array of const objects, these objects can still be nulled out if forcefully collected.
template<class UObjectType>
void AddReferencedObjects (TArray< TObjectPtr< UObjectType > > &ObjectArray, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to an array of objects.
template<class UObjectType>
void AddReferencedObjects (TArray< UObjectType * > &ObjectArray, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to an array of objects.
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
void AddReferencedObjects (TMapBase< KeyType *, ValueType *, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
void AddReferencedObjects (TMapBase< KeyType *, ValueType, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to a map of objects.
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
void AddReferencedObjects (TMapBase< KeyType, TObjectPtr< ValueType >, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
void AddReferencedObjects (TMapBase< KeyType, ValueType *, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
void AddReferencedObjects (TMapBase< TObjectPtr< KeyType >, TObjectPtr< ValueType >, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
void AddReferencedObjects (TMapBase< TObjectPtr< KeyType >, ValueType, Allocator, KeyFuncs > &Map, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to a map of objects.
void AddReferencedObjects (TObjectPtr< const UScriptStruct > &ScriptStruct, void *Instance, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
template<class UObjectType>
void AddReferencedObjects (TSet< TObjectPtr< UObjectType > > &ObjectSet, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to a set of objects.
template<class UObjectType>
void AddReferencedObjects (TSet< UObjectType * > &ObjectSet, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
Adds references to a set of objects.
void AddReferencedObjects (TWeakObjectPtr< const UScriptStruct > &ScriptStruct, void *Instance, const UObject *ReferencingObject=nullptr, const FProperty *ReferencingProperty=nullptr)
virtual void AddStableReference (TObjectPtr< UObject > *Object)
Preferred way to add a reference that allows batching.
template<class UObjectType>
FORCEINLINE void AddStableReference (TObjectPtr< UObjectType > *Object)
virtual void AddStableReference (UObject **Object)
Preferred way to add a reference that allows batching.
template<class UObjectType>
FORCEINLINE void AddStableReference (UObjectType **Object)
virtual void AddStableReferenceArray (TArray< TObjectPtr< UObject > > *Objects)
Preferred way to add a reference array that allows batching.
template<class UObjectType>
FORCEINLINE void AddStableReferenceArray (TArray< TObjectPtr< UObjectType > > *Objects)
virtual void AddStableReferenceArray (TArray< UObject * > *Objects)
Preferred way to add a reference array that allows batching.
template<class UObjectType>
FORCEINLINE void AddStableReferenceArray (TArray< UObjectType * > *Objects)
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs>
FORCEINLINE_DEBUGGABLE void AddStableReferenceMap (TMapBase< KeyType, ValueType, Allocator, KeyFuncs > &Map)
virtual void AddStableReferenceSet (TSet< TObjectPtr< UObject > > *Objects)
Preferred way to add a reference set that allows batching.
template<class UObjectType>
FORCEINLINE void AddStableReferenceSet (TSet< TObjectPtr< UObjectType > > *Objects)
virtual void AddStableReferenceSet (TSet< UObject * > *Objects)
Preferred way to add a reference set that allows batching.
template<class UObjectType>
FORCEINLINE void AddStableReferenceSet (TSet< UObjectType * > *Objects)
virtual void AllowEliminatingReferences (bool bAllow)
Allows reference elimination by this collector.
virtual class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FReferenceCollectorArchive & GetVerySlowReferenceCollectorArchive ()
Get archive to collect references via SerializeBin / Serialize.
virtual bool IsIgnoringArchetypeRef () const =0
If true archetype references should not be added to this collector.
virtual bool IsIgnoringTransient () const =0
If true transient objects should not be added to this collector.
virtual bool IsProcessingNativeReferences () const
If true, this collector is currently processing native references (true by default).
virtual bool MarkWeakObjectReferenceForClearing (UObject **WeakReference, UObject *ReferenceOwner)
Marks a specific object reference as a weak reference.
virtual bool NeedsInitialReferences () const
Used by parallel reachability analysis to pre-collect and then exclude some initial FGCObject references.
virtual bool NeedsPropertyReferencer () const
Make Add[OnlyObject]PropertyReference/AddReferencedObjects(UScriptStruct) use AddReferencedObjects(UObject*&) callbacks with ReferencingObject and ReferencingProperty context supplied and check for null references before making a callback.
virtual void SetIsProcessingNativeReferences (bool bIsNative)
Sets whether this collector is currently processing native references or not.
virtual void SetSerializedProperty (class FProperty *Inproperty)
Sets the property that is currently being serialized.
Protected Member Functions
virtual void HandleObjectReference (UObject *&InObject, const UObject *InReferencingObject, const FProperty *InReferencingProperty)=0
Handle object reference.
virtual void HandleObjectReferences (FObjectPtr *InObjects, const int32 ObjectNum, const UObject *InReferencingObject, const FProperty *InReferencingProperty)
Handle multiple object references.
virtual void HandleObjectReferences (UObject **InObjects, const int32 ObjectNum, const UObject *InReferencingObject, const FProperty *InReferencingProperty)
Handle multiple object references.
Private Member Functions
void AddStableReferenceArrayFwd (TArray< FObjectPtr > *Objects)
void AddStableReferenceFwd (FObjectPtr *Object)
void AddStableReferenceSetFwd (TSet< FObjectPtr > *Objects)
void CreateVerySlowReferenceCollectorArchive ()
Creates the proxy archive that uses serialization to add objects to this collector.
Private Attributes
TUniquePtr< FReferenceCollectorArchive > DefaultReferenceCollectorArchive
Default proxy archive that uses serialization to add objects to this collector.
Detailed Description
Used by garbage collector to collect references via virtual AddReferencedObjects calls.
Definition at line 2427 of file UObjectGlobals.h.
Constructor & Destructor Documentation
~FReferenceCollector()
virtual FReferenceCollector::~FReferenceCollector () virtual
Member Function Documentation
AddPropertyReferences()
void FReferenceCollector::AddPropertyReferences (const UStruct * Struct, void * Instance, const UObject * ReferencingObject = nullptr)
Adds all strong property references from a struct instance, but not the struct itself.
Skips AddStructReferencedObjects.
References AddPropertyReferences(), Instance, and Struct.
Referenced by AddPropertyReferences().
AddPropertyReferencesLimitedToObjectProperties()
void FReferenceCollector::AddPropertyReferencesLimitedToObjectProperties (const UStruct * Struct, void * Instance, const UObject * ReferencingObject = nullptr)
Internal use only.
Same as AddPropertyReferences but skips field path and interface properties. Might get removed.
References AddPropertyReferencesLimitedToObjectProperties(), Instance, and Struct.
Referenced by AddPropertyReferencesLimitedToObjectProperties().
AddPropertyReferencesWithStructARO() [1/2]
void FReferenceCollector::AddPropertyReferencesWithStructARO (const UClass * Class, void * Instance, const UObject * ReferencingObject = nullptr)
Same as AddPropertyReferences but also calls AddStructReferencedObjects on all nested structs.
References AddPropertyReferencesWithStructARO(), Class, and Instance.
AddPropertyReferencesWithStructARO() [2/2]
void FReferenceCollector::AddPropertyReferencesWithStructARO (const UScriptStruct * Struct, void * Instance, const UObject * ReferencingObject = nullptr)
Same as AddPropertyReferences but also calls AddStructReferencedObjects on Struct and all nested structs.
References AddPropertyReferencesWithStructARO(), Instance, and Struct.
Referenced by AddPropertyReferencesWithStructARO(), and AddPropertyReferencesWithStructARO().
AddReferencedObject() [1/6]
template<class UObjectType> void FReferenceCollector::AddReferencedObject (const UObjectType *& Object, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds const object reference, this reference can still be nulled out if forcefully collected.
Parameters
Object Referenced object.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2549 of file UObjectGlobals.h.
References AddReferencedObject(), FReferenceCollector::AROPrivate::AddReferencedObject(), and Object.
AddReferencedObject() [2/6]
void FReferenceCollector::AddReferencedObject (FWeakObjectPtr & P, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr)
AddReferencedObject() [3/6]
template<class UObjectType> void FReferenceCollector::AddReferencedObject (TObjectPtr< const UObjectType > & Object, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds const object reference, this reference can still be nulled out if forcefully collected.
Parameters
Object Referenced object.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2648 of file UObjectGlobals.h.
References HandleObjectReference(), Object, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObject() [4/6]
template<class UObjectType> void FReferenceCollector::AddReferencedObject (TObjectPtr< UObjectType > & Object, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds object reference.
Parameters
Object Referenced object.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2632 of file UObjectGlobals.h.
References HandleObjectReference(), IsObjectHandleResolved_ForGC(), and Object.
AddReferencedObject() [5/6]
template<typename T> void FReferenceCollector::AddReferencedObject (TWeakObjectPtr< T > & P, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Definition at line 2783 of file UObjectGlobals.h.
References AddReferencedObject().
AddReferencedObject() [6/6]
template<class UObjectType> void FReferenceCollector::AddReferencedObject (UObjectType *& Object, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds object reference.
Parameters
Object Referenced object.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2535 of file UObjectGlobals.h.
References AddReferencedObject(), FReferenceCollector::AROPrivate::AddReferencedObject(), and Object.
Referenced by AddReferencedObject(), AddReferencedObject(), AddReferencedObject(), UE::MovieScene::AddReferencedObjectForComponent(), and UE::MovieScene::AddReferencedObjectForComponent().
AddReferencedObjects() [1/15]
void FReferenceCollector::AddReferencedObjects (const UScriptStruct *& ScriptStruct, void * Instance, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr)
Adds all strong property references from a UScriptStruct instance including the struct itself.
Only necessary to handle cases of an unreflected/non-UPROPERTY struct that wants to have references emitted.
Calls AddStructReferencedObjects() but not recursively on nested structs.
This and other AddPropertyReferences functions will hopefully merge into a single function in the future. They're kept separate initially to maintain exact semantics while replacing the much slower SerializeBin/TPropertyValueIterator/GetVerySlowReferenceCollectorArchive paths.
References AddReferencedObjects(), Instance, and ScriptStruct.
AddReferencedObjects() [2/15]
template<class UObjectType> void FReferenceCollector::AddReferencedObjects (TArray< const UObjectType * > & ObjectArray, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to an array of const objects, these objects can still be nulled out if forcefully collected.
Parameters
ObjectArray Referenced objects array.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2577 of file UObjectGlobals.h.
References AddReferencedObjects(), and FReferenceCollector::AROPrivate::AddReferencedObjects().
AddReferencedObjects() [3/15]
template<class UObjectType> void FReferenceCollector::AddReferencedObjects (TArray< TObjectPtr< const UObjectType > > & ObjectArray, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to an array of const objects, these objects can still be nulled out if forcefully collected.
Parameters
ObjectArray Referenced objects array.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2695 of file UObjectGlobals.h.
References HandleObjectReferences(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [4/15]
template<class UObjectType> void FReferenceCollector::AddReferencedObjects (TArray< TObjectPtr< UObjectType > > & ObjectArray, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to an array of objects.
Parameters
ObjectArray Referenced objects array.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2678 of file UObjectGlobals.h.
References HandleObjectReferences(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [5/15]
template<class UObjectType> void FReferenceCollector::AddReferencedObjects (TArray< UObjectType * > & ObjectArray, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to an array of objects.
Parameters
ObjectArray Referenced objects array.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2563 of file UObjectGlobals.h.
References AddReferencedObjects(), and FReferenceCollector::AROPrivate::AddReferencedObjects().
Referenced by AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), and AddReferencedObjects().
AddReferencedObjects() [6/15]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AddReferencedObjects (TMapBase< KeyType *, ValueType *, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Definition at line 2619 of file UObjectGlobals.h.
References AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), Allocator, and Map.
AddReferencedObjects() [7/15]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AddReferencedObjects (TMapBase< KeyType *, ValueType, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to a map of objects.
Parameters
Map Referenced objects map.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2605 of file UObjectGlobals.h.
References AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), Allocator, and Map.
AddReferencedObjects() [8/15]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AddReferencedObjects (TMapBase< KeyType, TObjectPtr< ValueType >, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Definition at line 2748 of file UObjectGlobals.h.
References Allocator, HandleObjectReference(), Map, UE_REFERENCE_COLLECTOR_REQUIRE_OBJECTPTR, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [9/15]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AddReferencedObjects (TMapBase< KeyType, ValueType *, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Definition at line 2612 of file UObjectGlobals.h.
References AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), Allocator, and Map.
AddReferencedObjects() [10/15]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AddReferencedObjects (TMapBase< TObjectPtr< KeyType >, TObjectPtr< ValueType >, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Definition at line 2763 of file UObjectGlobals.h.
References Allocator, HandleObjectReference(), Map, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [11/15]
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> void FReferenceCollector::AddReferencedObjects (TMapBase< TObjectPtr< KeyType >, ValueType, Allocator, KeyFuncs > & Map, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to a map of objects.
Parameters
ObjectArray Referenced objects map.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2733 of file UObjectGlobals.h.
References Allocator, HandleObjectReference(), Map, UE_REFERENCE_COLLECTOR_REQUIRE_OBJECTPTR, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [12/15]
void FReferenceCollector::AddReferencedObjects (TObjectPtr< const UScriptStruct > & ScriptStruct, void * Instance, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr)
References AddReferencedObjects(), Instance, and ScriptStruct.
AddReferencedObjects() [13/15]
template<class UObjectType> void FReferenceCollector::AddReferencedObjects (TSet< TObjectPtr< UObjectType > > & ObjectSet, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to a set of objects.
Parameters
ObjectSet Referenced objects set.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2712 of file UObjectGlobals.h.
References HandleObjectReference(), Object, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
AddReferencedObjects() [14/15]
template<class UObjectType> void FReferenceCollector::AddReferencedObjects (TSet< UObjectType * > & ObjectSet, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr) inline
Adds references to a set of objects.
Parameters
ObjectSet Referenced objects set.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Definition at line 2591 of file UObjectGlobals.h.
References AddReferencedObjects(), and FReferenceCollector::AROPrivate::AddReferencedObjects().
AddReferencedObjects() [15/15]
void FReferenceCollector::AddReferencedObjects (TWeakObjectPtr< const UScriptStruct > & ScriptStruct, void * Instance, const UObject * ReferencingObject = nullptr, const FProperty * ReferencingProperty = nullptr)
References AddReferencedObjects(), Instance, and ScriptStruct.
AddStableReference() [1/4]
virtual void FReferenceCollector::AddStableReference (TObjectPtr< UObject > * Object) virtual
Preferred way to add a reference that allows batching.
Object must outlive GC tracing, can't be used for temporary/stack references.
References Object.
Referenced by AddStableReference(), AddStableReference(), and AddStableReferenceMap().
AddStableReference() [2/4]
template<class UObjectType> FORCEINLINE void FReferenceCollector::AddStableReference (TObjectPtr< UObjectType > * Object) inline
Definition at line 2509 of file UObjectGlobals.h.
References AddStableReferenceFwd(), FORCEINLINE, and Object.
AddStableReference() [3/4]
virtual void FReferenceCollector::AddStableReference (UObject ** Object) virtual
Preferred way to add a reference that allows batching.
Object must outlive GC tracing, can't be used for temporary/stack references.
References AddStableReference(), Object, and UE_REFERENCE_COLLECTOR_REQUIRE_OBJECTPTR_DEPRECATED.
AddStableReference() [4/4]
template<class UObjectType> FORCEINLINE void FReferenceCollector::AddStableReference (UObjectType ** Object) inline
Definition at line 2483 of file UObjectGlobals.h.
References AddStableReference(), FORCEINLINE, and Object.
AddStableReferenceArray() [1/4]
virtual void FReferenceCollector::AddStableReferenceArray (TArray< TObjectPtr< UObject > > * Objects) virtual
Preferred way to add a reference array that allows batching.
Can't be used for temporary/stack array.
Referenced by AddStableReferenceArray(), and AddStableReferenceArray().
AddStableReferenceArray() [2/4]
template<class UObjectType> FORCEINLINE void FReferenceCollector::AddStableReferenceArray (TArray< TObjectPtr< UObjectType > > * Objects) inline
Definition at line 2515 of file UObjectGlobals.h.
References AddStableReferenceArrayFwd(), and FORCEINLINE.
AddStableReferenceArray() [3/4]
virtual void FReferenceCollector::AddStableReferenceArray (TArray< UObject * > * Objects) virtual
Preferred way to add a reference array that allows batching.
Can't be used for temporary/stack array.
References AddStableReferenceArray(), and UE_REFERENCE_COLLECTOR_REQUIRE_OBJECTPTR_DEPRECATED.
AddStableReferenceArray() [4/4]
template<class UObjectType> FORCEINLINE void FReferenceCollector::AddStableReferenceArray (TArray< UObjectType * > * Objects) inline
Definition at line 2492 of file UObjectGlobals.h.
References AddStableReferenceArray(), and FORCEINLINE.
AddStableReferenceArrayFwd()
void FReferenceCollector::AddStableReferenceArrayFwd (TArray< FObjectPtr > * Objects) private
Referenced by AddStableReferenceArray().
AddStableReferenceFwd()
void FReferenceCollector::AddStableReferenceFwd (FObjectPtr * Object) private
References Object.
Referenced by AddStableReference().
AddStableReferenceMap()
template<typename KeyType, typename ValueType, typename Allocator, typename KeyFuncs> FORCEINLINE_DEBUGGABLE void FReferenceCollector::AddStableReferenceMap (TMapBase< KeyType, ValueType, Allocator, KeyFuncs > & Map) inline
Definition at line 2442 of file UObjectGlobals.h.
References AddStableReference(), FORCEINLINE_DEBUGGABLE, Map, and TIsTObjectPtr< T >::Value.
AddStableReferenceSet() [1/4]
virtual void FReferenceCollector::AddStableReferenceSet (TSet< TObjectPtr< UObject > > * Objects) virtual
Preferred way to add a reference set that allows batching.
Can't be used for temporary/stack set.
Referenced by AddStableReferenceSet(), and AddStableReferenceSet().
AddStableReferenceSet() [2/4]
template<class UObjectType> FORCEINLINE void FReferenceCollector::AddStableReferenceSet (TSet< TObjectPtr< UObjectType > > * Objects) inline
Definition at line 2521 of file UObjectGlobals.h.
References AddStableReferenceSetFwd(), and FORCEINLINE.
AddStableReferenceSet() [3/4]
virtual void FReferenceCollector::AddStableReferenceSet (TSet< UObject * > * Objects) virtual
Preferred way to add a reference set that allows batching.
Can't be used for temporary/stack set.
References AddStableReferenceSet(), and UE_REFERENCE_COLLECTOR_REQUIRE_OBJECTPTR_DEPRECATED.
AddStableReferenceSet() [4/4]
template<class UObjectType> FORCEINLINE void FReferenceCollector::AddStableReferenceSet (TSet< UObjectType * > * Objects) inline
Definition at line 2501 of file UObjectGlobals.h.
References AddStableReferenceSet(), and FORCEINLINE.
AddStableReferenceSetFwd()
void FReferenceCollector::AddStableReferenceSetFwd (TSet< FObjectPtr > * Objects) private
Referenced by AddStableReferenceSet().
AllowEliminatingReferences()
virtual void FReferenceCollector::AllowEliminatingReferences (bool bAllow) inline virtual
Allows reference elimination by this collector.
Definition at line 2844 of file UObjectGlobals.h.
CreateVerySlowReferenceCollectorArchive()
void FReferenceCollector::CreateVerySlowReferenceCollectorArchive () private
Creates the proxy archive that uses serialization to add objects to this collector.
Referenced by GetVerySlowReferenceCollectorArchive().
GetSerializedProperty()
virtual class FProperty * FReferenceCollector::GetSerializedProperty () const inline virtual
Gets the property that is currently being serialized.
Reimplemented in FReferenceFinder.
Definition at line 2854 of file UObjectGlobals.h.
GetVerySlowReferenceCollectorArchive()
FReferenceCollectorArchive & FReferenceCollector::GetVerySlowReferenceCollectorArchive () inline
Get archive to collect references via SerializeBin / Serialize.
NOTE: Prefer using AddPropertyReferences or AddReferencedObjects(const UScriptStruct&) instead, they're much faster.
Definition at line 2877 of file UObjectGlobals.h.
References CreateVerySlowReferenceCollectorArchive(), and DefaultReferenceCollectorArchive.
HandleObjectReference()
virtual void FReferenceCollector::HandleObjectReference (UObject *& InObject, const UObject * InReferencingObject, const FProperty * InReferencingProperty) protected pure virtual
Handle object reference.
Called by AddReferencedObject.
Parameters
Object Referenced object.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Implemented in FPropertyReferenceCollector, FPurgingReferenceCollector, FReferenceFinder, FSlateObjectReferenceCollector, and UE::GC::TDefaultCollector< ProcessorType >.
Referenced by AddReferencedObject(), AddReferencedObject(), FReferenceCollector::AROPrivate::AddReferencedObject(), FReferenceCollector::AROPrivate::AddReferencedObject(), AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), and HandleObjectReferences().
HandleObjectReferences() [1/2]
virtual void FReferenceCollector::HandleObjectReferences (FObjectPtr * InObjects, const int32 ObjectNum, const UObject * InReferencingObject, const FProperty * InReferencingProperty) protected virtual
Handle multiple object references.
Called by AddReferencedObjects. DEFAULT IMPLEMENTATION IS SLOW as it calls HandleObjectReference multiple times. In order to optimize it, provide your own implementation.
Parameters
Object Referenced object.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
HandleObjectReferences() [2/2]
virtual void FReferenceCollector::HandleObjectReferences (UObject ** InObjects, const int32 ObjectNum, const UObject * InReferencingObject, const FProperty * InReferencingProperty) inline protected virtual
Handle multiple object references.
Called by AddReferencedObjects. DEFAULT IMPLEMENTATION IS SLOW as it calls HandleObjectReference multiple times. In order to optimize it, provide your own implementation.
Parameters
Object Referenced object.
ReferencingObject Referencing object (if available).
ReferencingProperty Referencing property (if available).
Reimplemented in FPurgingReferenceCollector, and UE::GC::TDefaultCollector< ProcessorType >.
Definition at line 3019 of file UObjectGlobals.h.
References HandleObjectReference(), and Object.
Referenced by AddReferencedObjects(), AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), and FReferenceCollector::AROPrivate::AddReferencedObjects().
IsIgnoringArchetypeRef()
virtual bool FReferenceCollector::IsIgnoringArchetypeRef () const pure virtual
If true archetype references should not be added to this collector.
Implemented in FPropertyReferenceCollector, FPurgingReferenceCollector, FReferenceFinder, FSlateObjectReferenceCollector, and UE::GC::TDefaultCollector< ProcessorType >.
IsIgnoringTransient()
virtual bool FReferenceCollector::IsIgnoringTransient () const pure virtual
If true transient objects should not be added to this collector.
Implemented in FPropertyReferenceCollector, FPurgingReferenceCollector, FReferenceFinder, FSlateObjectReferenceCollector, and UE::GC::TDefaultCollector< ProcessorType >.
IsProcessingNativeReferences()
virtual bool FReferenceCollector::IsProcessingNativeReferences () const inline virtual
If true, this collector is currently processing native references (true by default).
Definition at line 2867 of file UObjectGlobals.h.
MarkWeakObjectReferenceForClearing()
virtual bool FReferenceCollector::MarkWeakObjectReferenceForClearing (UObject ** WeakReference, UObject * ReferenceOwner) inline virtual
Marks a specific object reference as a weak reference.
This does not affect GC but will be freed at a later point The default behavior returns false as weak references must be explicitly supported
Definition at line 2859 of file UObjectGlobals.h.
NeedsInitialReferences()
virtual bool FReferenceCollector::NeedsInitialReferences () const inline virtual
Used by parallel reachability analysis to pre-collect and then exclude some initial FGCObject references.
Definition at line 2870 of file UObjectGlobals.h.
NeedsPropertyReferencer()
virtual bool FReferenceCollector::NeedsPropertyReferencer () const inline virtual
Make Add[OnlyObject]PropertyReference/AddReferencedObjects(UScriptStruct) use AddReferencedObjects(UObject*&) callbacks with ReferencingObject and ReferencingProperty context supplied and check for null references before making a callback.
Return false to use context free AddStableReference callbacks without null checks that avoid sync cache misses when batch processing references.
Definition at line 2831 of file UObjectGlobals.h.
References NeedsPropertyReferencer().
Referenced by NeedsPropertyReferencer().
SetIsProcessingNativeReferences()
virtual void FReferenceCollector::SetIsProcessingNativeReferences (bool bIsNative) inline virtual
Sets whether this collector is currently processing native references or not.
Definition at line 2863 of file UObjectGlobals.h.
SetSerializedProperty()
virtual void FReferenceCollector::SetSerializedProperty (class FProperty * Inproperty) inline virtual
Sets the property that is currently being serialized.
Reimplemented in FReferenceFinder.
Definition at line 2850 of file UObjectGlobals.h.
Field Documentation
DefaultReferenceCollectorArchive
TUniquePtr<FReferenceCollectorArchive> FReferenceCollector::DefaultReferenceCollectorArchive private
Default proxy archive that uses serialization to add objects to this collector.
Definition at line 3057 of file UObjectGlobals.h.
Referenced by GetVerySlowReferenceCollectorArchive().
The documentation for this class was generated from the following file:
UObjectGlobals.h