Unreal Engine 5.6 C++ API: TPropertyTrackExecutionToken< PropertyValueType, IntermediateType > Struct Template Reference
TPropertyTrackExecutionToken< PropertyValueType, IntermediateType > Struct Template Reference
Execution token that simple stores a value, and sets it when executed.
#include "MovieScenePropertyTemplate.h"
Public Member Functions
TPropertyTrackExecutionToken (IntermediateType InValue)
virtual void Execute (const FMovieSceneContext &Context, const FMovieSceneEvaluationOperand &Operand, FPersistentEvaluationData &PersistentData, IMovieScenePlayer &Player) override
Execute this token, operating on all objects referenced by 'Operand'.
Public Member Functions inherited from IMovieSceneExecutionToken
virtual ~IMovieSceneExecutionToken ()
Data Fields
IntermediateType Value
Detailed Description
template<typename PropertyValueType, typename IntermediateType = PropertyValueType>
struct TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >
Execution token that simple stores a value, and sets it when executed.
Definition at line 130 of file MovieScenePropertyTemplate.h.
Constructor & Destructor Documentation
TPropertyTrackExecutionToken()
template<typename PropertyValueType, typename IntermediateType = PropertyValueType> TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::TPropertyTrackExecutionToken (IntermediateType InValue) inline
Definition at line 132 of file MovieScenePropertyTemplate.h.
References MoveTemp(), and Value.
Member Function Documentation
Execute()
template<typename PropertyValueType, typename IntermediateType = PropertyValueType> virtual void TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute (const FMovieSceneContext & Context, const FMovieSceneEvaluationOperand & Operand, FPersistentEvaluationData & PersistentData, IMovieScenePlayer & Player) inline override virtual
Execute this token, operating on all objects referenced by 'Operand'.
Implements IMovieSceneExecutionToken.
Definition at line 137 of file MovieScenePropertyTemplate.h.
References PropertyTemplate::ConvertFromIntermediateType(), IMovieScenePlayer::FindBoundObjects(), TSharedPtr< ObjectType, InMode >::Get(), FPersistentEvaluationData::GetSectionData(), PropertyTemplate::IsValueValid(), MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER, PropertyTemplate::FSectionData::PropertyBindings, PropertyTemplate::FSectionData::PropertyID, IMovieScenePlayer::SavePreAnimatedState(), Value, and WeakObject.
Field Documentation
Value
template<typename PropertyValueType, typename IntermediateType = PropertyValueType> IntermediateType TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Value
Definition at line 163 of file MovieScenePropertyTemplate.h.
Referenced by TPropertyTrackExecutionToken(), and Execute().
The documentation for this struct was generated from the following file:
MovieScenePropertyTemplate.h