Unreal Engine 5.6 C++ API: UE::MovieScene::FPropertyRegistry Class Reference
UE::MovieScene::FPropertyRegistry Class Reference
Central registry of all property types animatable by sequencer.
#include "MovieScenePropertyRegistry.h"
Public Member Functions
FPropertyRegistry ()=default
FPropertyRegistry (const FPropertyRegistry &)=delete
FPropertyRegistry (FPropertyRegistry &&)=delete
template<typename PropertyTraits>
TCompositePropertyDefinitionBuilder< PropertyTraits > DefineCompositeProperty (TPropertyComponents< PropertyTraits > &InOutPropertyComponents, const TCHAR *InStatName)
Define a new animatable composite property type from its components.
template<typename PropertyTraits>
TPropertyDefinitionBuilder< PropertyTraits > DefineProperty (TPropertyComponents< PropertyTraits > &InOutPropertyComponents, const TCHAR *InStatName)
Define a new animatable property type from its components.
TArrayView< const FPropertyCompositeDefinition > GetComposites (const FPropertyDefinition &Property) const
Retrieve a generic representation of all the composites that contribute to a given property.
TArrayView< const FPropertyCompositeDefinition > GetComposites (FCompositePropertyTypeID PropertyID) const
Retrieve a generic representation of all the composites that contribute to a given property.
const FPropertyDefinition & GetDefinition (FCompositePropertyTypeID PropertyID) const
Retrieve a property definition from its ID.
TArrayView< const FPropertyDefinition > GetProperties () const
Access all the properties currently registered.
Static Public Member Functions
static MOVIESCENE_API TOptional< FResolvedFastProperty > ResolveFastProperty (UObject *Object, const FMovieScenePropertyBinding &PropertyBinding, FCustomAccessorView CustomAccessors)
Resolve a property to either a fast ptr offset, or a custom property accessor based on the specified array.
static MOVIESCENE_API TOptional< FResolvedProperty > ResolveProperty (UObject *Object, const FMovieScenePropertyBinding &PropertyBinding, FCustomAccessorView CustomAccessors)
Resolve a property to either a fast ptr offset, or a custom property accessor based on the specified array falling back to a slow instance binding if possible.
Private Member Functions
template<typename PropertyTraits>
void DefinePropertyImpl (TPropertyComponents< PropertyTraits > &InOutPropertyComponents, const TCHAR *InStatName)
Define a new animatable property type from its components.
Private Attributes
TArray< FPropertyCompositeDefinition > CompositeDefinitions
TArray< FPropertyDefinition > Properties
Friends
template<typename PropertyTraits, typename... Composites>
struct TCompositePropertyDefinitionBuilder
template<typename PropertyTraits>
struct TPropertyDefinitionBuilder
Detailed Description
Central registry of all property types animatable by sequencer.
Once registered, properties cannot be de-registered. This vastly simplifies the lifetime and ID management of the class
Definition at line 154 of file MovieScenePropertyRegistry.h.
Constructor & Destructor Documentation
FPropertyRegistry() [1/3]
UE::MovieScene::FPropertyRegistry::FPropertyRegistry () default
Referenced by FPropertyRegistry(), and FPropertyRegistry().
FPropertyRegistry() [2/3]
UE::MovieScene::FPropertyRegistry::FPropertyRegistry (FPropertyRegistry &&) delete
References FPropertyRegistry().
FPropertyRegistry() [3/3]
UE::MovieScene::FPropertyRegistry::FPropertyRegistry (const FPropertyRegistry &) delete
References FPropertyRegistry().
Member Function Documentation
DefineCompositeProperty()
template<typename PropertyTraits> TCompositePropertyDefinitionBuilder< PropertyTraits > UE::MovieScene::FPropertyRegistry::DefineCompositeProperty (TPropertyComponents< PropertyTraits > & InOutPropertyComponents, const TCHAR * InStatName) inline
Define a new animatable composite property type from its components.
Parameters
InOutPropertyComponents The property's components that are used for animating this property. TPropertyComponents::CompositeID is written to.
Returns
A builder class that should be used to define the composites that contribute to this property
Definition at line 190 of file MovieScenePropertyRegistry.h.
References UE::MovieScene::TPropertyComponents< PropertyTraits >::CompositeID, DefinePropertyImpl(), Properties, Property, and TCompositePropertyDefinitionBuilder.
DefineProperty()
template<typename PropertyTraits> TPropertyDefinitionBuilder< PropertyTraits > UE::MovieScene::FPropertyRegistry::DefineProperty (TPropertyComponents< PropertyTraits > & InOutPropertyComponents, const TCHAR * InStatName) inline
Define a new animatable property type from its components.
Parameters
InOutPropertyComponents The property's components that are used for animating this property. TPropertyComponents::CompositeID is written to.
Returns
A builder class that should be used to define the composites that contribute to this property
Definition at line 204 of file MovieScenePropertyRegistry.h.
References UE::MovieScene::TPropertyComponents< PropertyTraits >::CompositeID, DefinePropertyImpl(), Properties, Property, and TPropertyDefinitionBuilder.
DefinePropertyImpl()
template<typename PropertyTraits> void UE::MovieScene::FPropertyRegistry::DefinePropertyImpl (TPropertyComponents< PropertyTraits > & InOutPropertyComponents, const TCHAR * InStatName) inline private
Define a new animatable property type from its components.
Parameters
InOutPropertyComponents The property's components that are used for animating this property. TPropertyComponents::CompositeID is written to.
Returns
A builder class that should be used to define the composites that contribute to this property
Definition at line 260 of file MovieScenePropertyRegistry.h.
References checkf, CompositeDefinitions, UE::MovieScene::TPropertyComponents< PropertyTraits >::CompositeID, FDynamicStats::CreateStatId(), FName, UE::MovieScene::FCompositePropertyTypeID::FromIndex(), UE::MovieScene::TPropertyComponents< PropertyTraits >::InitialValue, MAX_uint16, FMemory::Memcpy(), UE::MovieScene::TPropertyComponents< PropertyTraits >::MetaDataComponents, UE::MovieScene::FPropertyDefinition::MetaDataTypes, MoveTemp(), Properties, UE::MovieScene::TPropertyComponents< PropertyTraits >::PropertyTag, UE::MovieScene::FPropertyDefinition::StatID, StringCast(), and TEXT.
Referenced by DefineCompositeProperty(), and DefineProperty().
GetComposites() [1/2]
TArrayView< const FPropertyCompositeDefinition > UE::MovieScene::FPropertyRegistry::GetComposites (const FPropertyDefinition & Property) const inline
Retrieve a generic representation of all the composites that contribute to a given property.
Definition at line 230 of file MovieScenePropertyRegistry.h.
References CompositeDefinitions, MakeArrayView(), and Property.
Referenced by GetComposites(), and UE::MovieScene::FPropertyRecomposerImpl::RecomposeBlendOperational().
GetComposites() [2/2]
TArrayView< const FPropertyCompositeDefinition > UE::MovieScene::FPropertyRegistry::GetComposites (FCompositePropertyTypeID PropertyID) const inline
Retrieve a generic representation of all the composites that contribute to a given property.
Definition at line 240 of file MovieScenePropertyRegistry.h.
References GetComposites(), and GetDefinition().
GetDefinition()
const FPropertyDefinition & UE::MovieScene::FPropertyRegistry::GetDefinition (FCompositePropertyTypeID PropertyID) const inline
Retrieve a property definition from its ID.
Definition at line 214 of file MovieScenePropertyRegistry.h.
References Properties, and UE::MovieScene::FCompositePropertyTypeID::TypeIndex.
Referenced by GetComposites(), and UE::MovieScene::FPropertyRecomposerImpl::RecomposeBlendOperational().
GetProperties()
TArrayView< const FPropertyDefinition > UE::MovieScene::FPropertyRegistry::GetProperties () const inline
Access all the properties currently registered.
Definition at line 222 of file MovieScenePropertyRegistry.h.
References Properties.
ResolveFastProperty()
MOVIESCENE_API TOptional< FResolvedFastProperty > UE::MovieScene::FPropertyRegistry::ResolveFastProperty (UObject * Object, const FMovieScenePropertyBinding & PropertyBinding, FCustomAccessorView CustomAccessors) static
Resolve a property to either a fast ptr offset, or a custom property accessor based on the specified array.
Parameters
Object The object to resolve the property for
PropertyBinding The property binding to resolve
CustomAccessors A view to an array of custom accessors (as retrieved from ICustomPropertyRegistration::GetAccessors)
Returns
An optional variant specifying the resolved property if it resolved successfully
Referenced by UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::VisitInterrogationAllocation().
ResolveProperty()
MOVIESCENE_API TOptional< FResolvedProperty > UE::MovieScene::FPropertyRegistry::ResolveProperty (UObject * Object, const FMovieScenePropertyBinding & PropertyBinding, FCustomAccessorView CustomAccessors) static
Resolve a property to either a fast ptr offset, or a custom property accessor based on the specified array falling back to a slow instance binding if possible.
Parameters
Object The object to resolve the property for
PropertyBinding The property binding to resolve
CustomAccessors A view to an array of custom accessors (as retrieved from ICustomPropertyRegistration::GetAccessors)
Returns
An optional variant specifying the resolved property if it resolved successfully
Friends And Related Symbol Documentation
TCompositePropertyDefinitionBuilder
template<typename PropertyTraits, typename... Composites> friend struct TCompositePropertyDefinitionBuilder friend
Definition at line 251 of file MovieScenePropertyRegistry.h.
References TCompositePropertyDefinitionBuilder.
Referenced by DefineCompositeProperty(), and TCompositePropertyDefinitionBuilder.
TPropertyDefinitionBuilder
template<typename PropertyTraits> friend struct TPropertyDefinitionBuilder friend
Definition at line 248 of file MovieScenePropertyRegistry.h.
References TPropertyDefinitionBuilder.
Referenced by DefineProperty(), and TPropertyDefinitionBuilder.
Field Documentation
CompositeDefinitions
TArray<FPropertyCompositeDefinition> UE::MovieScene::FPropertyRegistry::CompositeDefinitions private
Definition at line 307 of file MovieScenePropertyRegistry.h.
Referenced by DefinePropertyImpl(), and GetComposites().
Properties
TArray<FPropertyDefinition> UE::MovieScene::FPropertyRegistry::Properties private
Definition at line 305 of file MovieScenePropertyRegistry.h.
Referenced by DefineCompositeProperty(), DefineProperty(), DefinePropertyImpl(), GetDefinition(), and GetProperties().
The documentation for this class was generated from the following file:
MovieScenePropertyRegistry.h