Unreal Engine 5.6 C++ API: FDisplayClusterActorRef Class Reference
FDisplayClusterActorRef Class Reference
#include "DisplayClusterObjectRef.h"
Public Member Functions
FDisplayClusterActorRef ()
FDisplayClusterActorRef (const FDisplayClusterActorRef &InActorRef)
virtual ~FDisplayClusterActorRef ()
AActor * GetOrFindSceneActor () const
const TWeakObjectPtr< AActor > GetSceneActorWeakPtr () const
Returns the current weak ptr of the scene actor object.
bool IsDefinedSceneActor () const
void ResetSceneActor ()
bool SetSceneActor (const AActor *InActor)
Protected Attributes
FCriticalSection DataGuard
Private Member Functions
bool UpdateActorClassPtr () const
bool UpdateWorldPtr () const
Private Attributes
FString ActorClassName
TWeakObjectPtr< UClass > ActorClassPtr
FName ActorName
TWeakObjectPtr< AActor > ActorPtr
TWeakObjectPtr< UWorld > WorldPtr
Detailed Description
Definition at line 18 of file DisplayClusterObjectRef.h.
Constructor & Destructor Documentation
FDisplayClusterActorRef() [1/2]
FDisplayClusterActorRef::FDisplayClusterActorRef () inline
Definition at line 21 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterActorRef(), FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef(), and FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef().
FDisplayClusterActorRef() [2/2]
FDisplayClusterActorRef::FDisplayClusterActorRef (const FDisplayClusterActorRef & InActorRef) inline
Definition at line 24 of file DisplayClusterObjectRef.h.
References FDisplayClusterActorRef(), ActorClassName, ActorClassPtr, ActorName, ActorPtr, and WorldPtr.
~FDisplayClusterActorRef()
virtual FDisplayClusterActorRef::~FDisplayClusterActorRef () inline virtual
Definition at line 32 of file DisplayClusterObjectRef.h.
Member Function Documentation
GetOrFindSceneActor()
AActor * FDisplayClusterActorRef::GetOrFindSceneActor () const inline
Definition at line 55 of file DisplayClusterObjectRef.h.
References Actor, ActorClassPtr, ActorName, ActorPtr, DataGuard, IsDefinedSceneActor(), IsEngineExitRequested(), SkipPendingKill, UpdateActorClassPtr(), UpdateWorldPtr(), and WorldPtr.
GetSceneActorWeakPtr()
const TWeakObjectPtr< AActor > FDisplayClusterActorRef::GetSceneActorWeakPtr () const inline
Returns the current weak ptr of the scene actor object.
Definition at line 42 of file DisplayClusterObjectRef.h.
References ActorPtr, DataGuard, and IsDefinedSceneActor().
IsDefinedSceneActor()
bool FDisplayClusterActorRef::IsDefinedSceneActor () const inline
Definition at line 36 of file DisplayClusterObjectRef.h.
References ActorClassName, and ActorName.
Referenced by GetOrFindSceneActor(), GetSceneActorWeakPtr(), and FDisplayClusterSceneComponentRef::IsDefinedSceneComponent().
ResetSceneActor()
void FDisplayClusterActorRef::ResetSceneActor () inline
Definition at line 121 of file DisplayClusterObjectRef.h.
References ActorClassName, ActorClassPtr, ActorName, ActorPtr, DataGuard, FName, and WorldPtr.
Referenced by FDisplayClusterSceneComponentRef::ResetSceneComponent(), and SetSceneActor().
SetSceneActor()
bool FDisplayClusterActorRef::SetSceneActor (const AActor * InActor) inline
Definition at line 94 of file DisplayClusterObjectRef.h.
References ActorClassName, ActorClassPtr, ActorName, ActorPtr, DataGuard, UObjectBaseUtility::GetPathName(), ResetSceneActor(), and WorldPtr.
Referenced by FDisplayClusterSceneComponentRef::SetSceneComponent().
UpdateActorClassPtr()
bool FDisplayClusterActorRef::UpdateActorClassPtr () const inline private
Definition at line 168 of file DisplayClusterObjectRef.h.
References ActorClassName, ActorClassPtr, LOAD_None, and StaticLoadClass().
Referenced by GetOrFindSceneActor().
UpdateWorldPtr()
bool FDisplayClusterActorRef::UpdateWorldPtr () const inline private
Definition at line 135 of file DisplayClusterObjectRef.h.
References Cast(), GEditor, GEngine, GIsEditor, IsValid(), and WorldPtr.
Referenced by GetOrFindSceneActor().
Field Documentation
ActorClassName
FString FDisplayClusterActorRef::ActorClassName private
Definition at line 187 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterActorRef(), IsDefinedSceneActor(), ResetSceneActor(), SetSceneActor(), and UpdateActorClassPtr().
ActorClassPtr
TWeakObjectPtr<UClass> FDisplayClusterActorRef::ActorClassPtr mutable private
Definition at line 188 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterActorRef(), GetOrFindSceneActor(), ResetSceneActor(), SetSceneActor(), and UpdateActorClassPtr().
ActorName
FName FDisplayClusterActorRef::ActorName private
Definition at line 191 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterActorRef(), GetOrFindSceneActor(), IsDefinedSceneActor(), ResetSceneActor(), and SetSceneActor().
ActorPtr
TWeakObjectPtr<AActor> FDisplayClusterActorRef::ActorPtr mutable private
Definition at line 192 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterActorRef(), GetOrFindSceneActor(), GetSceneActorWeakPtr(), ResetSceneActor(), and SetSceneActor().
DataGuard
FCriticalSection FDisplayClusterActorRef::DataGuard mutable protected
Definition at line 196 of file DisplayClusterObjectRef.h.
Referenced by GetOrFindSceneActor(), GetSceneActorWeakPtr(), ResetSceneActor(), FDisplayClusterSceneComponentRef::ResetSceneComponent(), SetSceneActor(), and FDisplayClusterSceneComponentRef::SetSceneComponent().
WorldPtr
TWeakObjectPtr<UWorld> FDisplayClusterActorRef::WorldPtr mutable private
Definition at line 184 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterActorRef(), GetOrFindSceneActor(), ResetSceneActor(), SetSceneActor(), and UpdateWorldPtr().
The documentation for this class was generated from the following file:
DisplayClusterObjectRef.h