Unreal Engine 5.6 C++ API: FInstancedStaticMeshVertexFactory Struct Reference
FInstancedStaticMeshVertexFactory Struct Reference
A vertex factory for instanced static meshes.
#include "InstancedStaticMesh.h"
Public Member Functions
FInstancedStaticMeshVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
void Copy (const FInstancedStaticMeshVertexFactory &Other)
Copy the data from another vertex factory.
DECLARE_VERTEX_FACTORY_TYPE_API (FInstancedStaticMeshVertexFactory, 1)
FRHIShaderResourceView * GetInstanceCustomDataSRV () const
FRHIShaderResourceView * GetInstanceLightmapSRV () const
FRHIShaderResourceView * GetInstanceOriginSRV () const
FRHIShaderResourceView * GetInstanceTransformSRV () const
FRHIUniformBuffer * GetUniformBuffer () const
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void SetData (FRHICommandListBase &RHICmdList, const FDataType &InData, const FInstancedStaticMeshDataType *InInstanceData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
Public Member Functions inherited from FLocalVertexFactory
FLocalVertexFactory (ERHIFeatureLevel::Type InFeatureLevel, const char *InDebugName)
virtual ~FLocalVertexFactory ()
checkf (IsInitialized() &&EnumHasAnyFlags(EVertexStreamUsage::Overridden, Data.ColorComponent.VertexStreamUsage) &&ColorStreamIndex > 0, TEXT("Per-mesh colors with bad stream setup! Name %s"), *ColorVertexBuffer->GetFriendlyName())
void Copy (const FLocalVertexFactory &Other)
Copy the data from another vertex factory.
FRHIShaderResourceView * GetColorComponentsSRV () const
const uint32 GetColorIndexMask () const
void GetColorOverrideStream (const FVertexBuffer *ColorVertexBuffer, FVertexInputStreamArray &VertexStreams) const
const int GetLightMapCoordinateIndex () const
const int GetNumTexcoords () const
FRHIShaderResourceView * GetPositionsSRV () const
FRHIShaderResourceView * GetPreSkinPositionSRV () const
FRHIShaderResourceView * GetTangentsSRV () const
FRHIShaderResourceView * GetTextureCoordinatesSRV () const
virtual FShaderResourceViewRHIRef GetTriangleSortingPositionSRV () const override
FRHIUniformBuffer * GetUniformBuffer () const
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void SetData (FRHICommandListBase &RHICmdList, const FDataType &InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
RHICmdList SetStreamSource (ColorStreamIndex, ColorVertexBuffer->VertexBufferRHI, 0)
UE_DEPRECATED (5.4, "SetData requires a command list.") 1 void SetData(const FDataType &InData)
UE_DEPRECATED (5.5, "SetColorOverrideStream is no longer used") FORCEINLINE_DEBUGGABLE void SetColorOverrideStream(FRHICommandList &RHICmdList
Public Member Functions inherited from FVertexFactory
FVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
virtual RENDERCORE_API ~FVertexFactory ()
FVertexDeclarationRHIRef & GetDeclaration ()
const FVertexDeclarationRHIRef & GetDeclaration (EVertexInputStreamType InputStreamType) const
int32 GetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) const
RENDERCORE_API void GetStreams (ERHIFeatureLevel::Type InFeatureLevel, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &OutVertexStreams) const
virtual FVertexFactoryType * GetType () const
bool NeedsDeclaration () const
RENDERCORE_API void OffsetInstanceStreams (uint32 InstanceOffset, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &VertexStreams) const
virtual bool RendersPrimitivesAsCameraFacingSprites () const
void SetDeclaration (FVertexDeclarationRHIRef &NewDeclaration)
bool SupportsGPUScene (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsManualVertexFetch (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsNullPixelShader () const
Indicates whether the vertex factory supports a null pixel shader.
virtual bool SupportsPositionAndNormalOnlyStream () const
Indicates whether the vertex factory supports a position-and-normal-only stream.
virtual bool SupportsPositionOnlyStream () const
Indicates whether the vertex factory supports a position-only stream.
bool SupportsTriangleSorting () const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Get vertex elements used when during PSO precaching materials using this vertex factory type.
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType &Data, FInstancedStaticMeshDataType &InstanceData, FVertexDeclarationElementList &Elements)
static void InitInstancedStaticMeshVertexFactoryComponents (const FStaticMeshVertexBuffers &VertexBuffers, const FColorVertexBuffer *ColorVertexBuffer, const FStaticMeshInstanceBuffer *InstanceBuffer, const FInstancedStaticMeshVertexFactory *VertexFactory, int32 LightMapCoordinateIndex, bool bRHISupportsManualVertexFetch, FInstancedStaticMeshVertexFactory::FDataType &OutData, FInstancedStaticMeshDataType &OutInstanceData)
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Modify compile environment to enable instancing.
static constexpr uint32 NumBitsForVisibilityMask ()
Make sure we account for changes in the signature of GetStaticBatchElementVisibility()
static bool ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters &Parameters)
Should we cache the material's shadertype on this platform with this vertex factory?
Static Public Member Functions inherited from FLocalVertexFactory
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType &Data, FVertexDeclarationElementList &Elements)
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static bool ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters &Parameters)
Should we cache the material's shadertype on this platform with this vertex factory?
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Static Public Member Functions inherited from FVertexFactory
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Can be overridden by FVertexFactory subclasses which have EVertexFactoryFlags::SupportsPSOPrecaching set - this function will only be called when that flag is set.
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Can be overridden by FVertexFactory subclasses to modify their compile environment just before compilation occurs.
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Can be overridden by FVertexFactory subclasses to fail a compile based on compilation output.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Static Protected Member Functions
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType &Data, FInstancedStaticMeshDataType &InstanceData, FVertexDeclarationElementList &Elements, FVertexStreamList &Streams)
Static Protected Member Functions inherited from FLocalVertexFactory
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType &Data, FVertexDeclarationElementList &Elements, FVertexStreamList &InOutStreams, int32 &OutColorStreamIndex)
Static Protected Member Functions inherited from FVertexFactory
template<typename VertexStreamListType>
static FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, VertexStreamListType &InOutStreams)
Creates a vertex element for a vertex stream components.
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Private Attributes
FInstancedStaticMeshDataType InstanceData
TUniformBufferRef< FInstancedStaticMeshVertexFactoryUniformShaderParameters > UniformBuffer
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Data Fields inherited from FLocalVertexFactory
const FVertexBuffer *ColorVertexBuffer const
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Types inherited from FVertexFactory
typedef TArray< FVertexStream, TInlineAllocator< 8 > > FVertexStreamList
Protected Member Functions inherited from FLocalVertexFactory
const FDataType & GetData () const
Protected Member Functions inherited from FVertexFactory
FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex)
Creates a vertex element for a vertex stream components.
RENDERCORE_API FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, EVertexInputStreamType InputStreamType)
Creates a vertex element for a vertex stream component.
RENDERCORE_API bool AddPrimitiveIdStreamElement (EVertexInputStreamType InputStreamType, FVertexDeclarationElementList &Elements, uint8 AttributeIndex, uint8 AttributeIndex_Mobile)
RENDERCORE_API void InitDeclaration (const FVertexDeclarationElementList &Elements, EVertexInputStreamType StreamType=EVertexInputStreamType::Default)
Initializes the vertex declaration.
void SetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType, int32 StreamIndex)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Protected Attributes inherited from FLocalVertexFactory
bool bGPUSkinPassThrough = false
int32 ColorStreamIndex
FDataType Data
struct FLocalVertexFactory::FDebugName DebugName
TUniformBufferRef< FLocalVertexFactoryUniformShaderParameters > UniformBuffer
Protected Attributes inherited from FVertexFactory
bool bNeedsDeclaration = true
FVertexStreamList Streams
The vertex streams used to render the factory.
Detailed Description
A vertex factory for instanced static meshes.
Definition at line 261 of file InstancedStaticMesh.h.
Constructor & Destructor Documentation
FInstancedStaticMeshVertexFactory()
FInstancedStaticMeshVertexFactory::FInstancedStaticMeshVertexFactory (ERHIFeatureLevel::Type InFeatureLevel) inline
Definition at line 265 of file InstancedStaticMesh.h.
References FLocalVertexFactory::FLocalVertexFactory().
Referenced by Copy(), DECLARE_VERTEX_FACTORY_TYPE_API(), and InitInstancedStaticMeshVertexFactoryComponents().
Member Function Documentation
Copy()
void FInstancedStaticMeshVertexFactory::Copy (const FInstancedStaticMeshVertexFactory & Other)
Copy the data from another vertex factory.
Parameters
Other - factory to copy from
References FInstancedStaticMeshVertexFactory(), and Other.
DECLARE_VERTEX_FACTORY_TYPE_API()
FInstancedStaticMeshVertexFactory::DECLARE_VERTEX_FACTORY_TYPE_API (FInstancedStaticMeshVertexFactory , 1)
References FInstancedStaticMeshVertexFactory().
GetInstanceCustomDataSRV()
FRHIShaderResourceView * FInstancedStaticMeshVertexFactory::GetInstanceCustomDataSRV () const inline
Definition at line 340 of file InstancedStaticMesh.h.
References InstanceData.
GetInstanceLightmapSRV()
FRHIShaderResourceView * FInstancedStaticMeshVertexFactory::GetInstanceLightmapSRV () const inline
Definition at line 335 of file InstancedStaticMesh.h.
References InstanceData.
GetInstanceOriginSRV()
FRHIShaderResourceView * FInstancedStaticMeshVertexFactory::GetInstanceOriginSRV () const inline
Definition at line 325 of file InstancedStaticMesh.h.
References InstanceData.
GetInstanceTransformSRV()
FRHIShaderResourceView * FInstancedStaticMeshVertexFactory::GetInstanceTransformSRV () const inline
Definition at line 330 of file InstancedStaticMesh.h.
References InstanceData.
GetPSOPrecacheVertexFetchElements()
void FInstancedStaticMeshVertexFactory::GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList & Elements) static
Get vertex elements used when during PSO precaching materials using this vertex factory type.
GetUniformBuffer()
FRHIUniformBuffer * FInstancedStaticMeshVertexFactory::GetUniformBuffer () const inline
Definition at line 345 of file InstancedStaticMesh.h.
References UniformBuffer.
GetVertexElements() [1/2]
void FInstancedStaticMeshVertexFactory::GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType & Data, FInstancedStaticMeshDataType & InstanceData, FVertexDeclarationElementList & Elements) static
References FLocalVertexFactory::Data, FRenderResource::FeatureLevel, and InstanceData.
Referenced by FInstancedStaticMeshComponentHelper::CollectPSOPrecacheData().
GetVertexElements() [2/2]
void FInstancedStaticMeshVertexFactory::GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType & Data, FInstancedStaticMeshDataType & InstanceData, FVertexDeclarationElementList & Elements, FVertexStreamList & Streams) static protected
References FLocalVertexFactory::Data, FRenderResource::FeatureLevel, InstanceData, and FVertexFactory::Streams.
InitInstancedStaticMeshVertexFactoryComponents()
void FInstancedStaticMeshVertexFactory::InitInstancedStaticMeshVertexFactoryComponents (const FStaticMeshVertexBuffers & VertexBuffers, const FColorVertexBuffer * ColorVertexBuffer, const FStaticMeshInstanceBuffer * InstanceBuffer, const FInstancedStaticMeshVertexFactory * VertexFactory, int32 LightMapCoordinateIndex, bool bRHISupportsManualVertexFetch, FInstancedStaticMeshVertexFactory::FDataType & OutData, FInstancedStaticMeshDataType & OutInstanceData) static
References FInstancedStaticMeshVertexFactory(), LightMapCoordinateIndex, and VertexFactory.
Referenced by FInstancedStaticMeshComponentHelper::CollectPSOPrecacheData().
InitRHI()
virtual void FInstancedStaticMeshVertexFactory::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FLocalVertexFactory.
ModifyCompilationEnvironment()
void FInstancedStaticMeshVertexFactory::ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) static
Modify compile environment to enable instancing.
Parameters
OutEnvironment - shader compile environment to modify
NumBitsForVisibilityMask()
constexpr uint32 FInstancedStaticMeshVertexFactory::NumBitsForVisibilityMask () inline static constexpr
Make sure we account for changes in the signature of GetStaticBatchElementVisibility()
Definition at line 320 of file InstancedStaticMesh.h.
SetData()
void FInstancedStaticMeshVertexFactory::SetData (FRHICommandListBase & RHICmdList, const FDataType & InData, const FInstancedStaticMeshDataType * InInstanceData) inline
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
Definition at line 300 of file InstancedStaticMesh.h.
References FLocalVertexFactory::Data, InstanceData, and FRenderResource::UpdateRHI().
ShouldCompilePermutation()
bool FInstancedStaticMeshVertexFactory::ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters & Parameters) static
Should we cache the material's shadertype on this platform with this vertex factory?
Field Documentation
InstanceData
FInstancedStaticMeshDataType FInstancedStaticMeshVertexFactory::InstanceData private
Definition at line 353 of file InstancedStaticMesh.h.
Referenced by GetInstanceCustomDataSRV(), GetInstanceLightmapSRV(), GetInstanceOriginSRV(), GetInstanceTransformSRV(), GetVertexElements(), GetVertexElements(), and SetData().
UniformBuffer
TUniformBufferRef<FInstancedStaticMeshVertexFactoryUniformShaderParameters> FInstancedStaticMeshVertexFactory::UniformBuffer private
Definition at line 355 of file InstancedStaticMesh.h.
Referenced by GetUniformBuffer().
The documentation for this struct was generated from the following file:
InstancedStaticMesh.h