Unreal Engine 5.6 C++ API: UE::FIoFileBlockCache Class Reference
UE::FIoFileBlockCache Class Reference
#include "PlatformIoDispatcherBase.h"
Data Structures
struct FCachedBlock
Public Member Functions
FIoFileBlockCache (FPlatformIoDispatcherStats &Stats)
~FIoFileBlockCache ()
bool Get (FIoFileBlockRequest &FileBlockRequest)
void Initialize (uint64 CacheBlockSize, uint64 CacheSize)
void Put (FIoFileBlockRequest &FileBlockRequest)
Private Attributes
uint64 CacheBlockSize = 0
TMap< uint64, FCachedBlock * > CachedBlocks
FCachedBlock CacheLruHead
FCachedBlock CacheLruTail
TUniquePtr< uint8[]> CacheMemory
FPlatformIoDispatcherStats & Stats
Detailed Description
Definition at line 384 of file PlatformIoDispatcherBase.h.
Constructor & Destructor Documentation
FIoFileBlockCache()
UE::FIoFileBlockCache::FIoFileBlockCache (FPlatformIoDispatcherStats & Stats)
Definition at line 434 of file PlatformIoDispatcherBase.cpp.
References Stats.
~FIoFileBlockCache()
UE::FIoFileBlockCache::~FIoFileBlockCache ()
Definition at line 439 of file PlatformIoDispatcherBase.cpp.
Member Function Documentation
Get()
bool UE::FIoFileBlockCache::Get (FIoFileBlockRequest & FileBlockRequest)
Definition at line 467 of file PlatformIoDispatcherBase.cpp.
References UE::FIoFileBlockRequest::BlockKey, UE::FIoFileBlockCache::FCachedBlock::Buffer, UE::FIoFileBlockRequest::Buffer, UE::FIoFileBlockRequest::BufferHandle, CacheBlockSize, CachedBlocks, CacheLruHead, CacheMemory, check, UE::FIoBlockKey::GetHash(), UE::FIoBlockKey::IsValid(), UE::FIoBufferHandle::IsValid(), UE::FIoFileBlockCache::FCachedBlock::LruNext, UE::FIoFileBlockCache::FCachedBlock::LruPrev, FMemory::Memcpy(), and Stats.
Initialize()
void UE::FIoFileBlockCache::Initialize (uint64 CacheBlockSize, uint64 CacheSize)
Definition at line 443 of file PlatformIoDispatcherBase.cpp.
References UE::FIoFileBlockCache::FCachedBlock::Buffer, CacheBlockSize, CacheLruHead, CacheLruTail, CacheMemory, UE::FIoFileBlockCache::FCachedBlock::Key, UE::FIoFileBlockCache::FCachedBlock::LruNext, UE::FIoFileBlockCache::FCachedBlock::LruPrev, and MakeUnique().
Put()
void UE::FIoFileBlockCache::Put (FIoFileBlockRequest & FileBlockRequest)
Definition at line 500 of file PlatformIoDispatcherBase.cpp.
References UE::FIoFileBlockRequest::BlockKey, UE::FIoFileBlockCache::FCachedBlock::Buffer, UE::FIoFileBlockRequest::Buffer, UE::FIoFileBlockRequest::BufferHandle, CacheBlockSize, CachedBlocks, CacheLruHead, CacheLruTail, CacheMemory, check, UE::FIoBlockKey::GetHash(), UE::FIoBufferHandle::IsValid(), UE::FIoFileBlockCache::FCachedBlock::Key, UE::FIoFileBlockCache::FCachedBlock::LruNext, UE::FIoFileBlockCache::FCachedBlock::LruPrev, FMemory::Memcpy(), and Stats.
Field Documentation
CacheBlockSize
uint64 UE::FIoFileBlockCache::CacheBlockSize = 0 private
Definition at line 408 of file PlatformIoDispatcherBase.h.
Referenced by Get(), Initialize(), and Put().
CachedBlocks
TMap<uint64, FCachedBlock*> UE::FIoFileBlockCache::CachedBlocks private
Definition at line 405 of file PlatformIoDispatcherBase.h.
Referenced by Get(), and Put().
CacheLruHead
FCachedBlock UE::FIoFileBlockCache::CacheLruHead private
Definition at line 406 of file PlatformIoDispatcherBase.h.
Referenced by Get(), Initialize(), and Put().
CacheLruTail
FCachedBlock UE::FIoFileBlockCache::CacheLruTail private
Definition at line 407 of file PlatformIoDispatcherBase.h.
Referenced by Initialize(), and Put().
CacheMemory
TUniquePtr<uint8[]> UE::FIoFileBlockCache::CacheMemory private
Definition at line 404 of file PlatformIoDispatcherBase.h.
Referenced by Get(), Initialize(), and Put().
Stats
FPlatformIoDispatcherStats& UE::FIoFileBlockCache::Stats private
Definition at line 403 of file PlatformIoDispatcherBase.h.
Referenced by FIoFileBlockCache(), Get(), and Put().
The documentation for this class was generated from the following files:
PlatformIoDispatcherBase.h
PlatformIoDispatcherBase.cpp