Unreal Engine 5.6 C++ API: UE::AI Namespace Reference
UE::AI Namespace Reference
Functions
FVector Bilinear (const FVector2D UV, const FVector VertexA, const FVector VertexB, const FVector VertexC, const FVector VertexD)
Interpolates bilinear patch A,B,C,D.
FVector::FReal Cross2D (const FVector &A, const FVector &B)
FVector2D::FReal Cross2D (const FVector2D &A, const FVector2D &B)
bool IntersectLineLine2D (const FVector &StartA, const FVector &EndA, const FVector &StartB, const FVector &EndB, FVector2D::FReal &OutTA, FVector2D::FReal &OutTB)
Intersects infinite lines defined by segments A and B in 2D.
AIMODULE_API bool IntersectSegmentPoly2D (const FVector &Start, const FVector &End, TConstArrayView< FVector > Poly, FVector2D::FReal &OutTMin, FVector2D::FReal &OutTMax, int32 &OutSegMin, int32 &OutSegMax)
Calculates intersection of segment Start-End with convex polygon Poly in 2D.
AIMODULE_API FVector2D InvBilinear2D (const FVector Point, const FVector VertexA, const FVector VertexB, const FVector VertexC, const FVector VertexD)
Finds the UV coordinates of the 'Point' on bilinear patch A,B,C,D.
FVector2D InvBilinear2DClamped (const FVector Point, const FVector VertexA, const FVector VertexB, const FVector VertexC, const FVector VertexD)
Finds the UV coordinates of the 'Point' on bilinear patch A,B,C,D.
FVector::FReal ProjectPointOnLine2D (const FVector Point, const FVector Start, const FVector End)
FVector2D::FReal ProjectPointOnSegment2D (const FVector Point, const FVector Start, const FVector End)
FVector::FReal SignedDistancePointLine2D (const FVector Point, const FVector Start, const FVector End)
FVector::FReal TriArea2D (const FVector &A, const FVector &B, const FVector &C)
FVector2D::FReal TriArea2D (const FVector2D &A, const FVector2D &B, const FVector2D &C)
UE_DEPRECATED (5.2, "Deprecated as returning float instead of FVector::FReal. Use FQuat::Rotator()::Yaw etc.") extern AIMODULE_API TOptional< float > GetYawFromQuaternion(const FQuat &Quaternion)
This method will extract the yaw radian from the specified quaternion if it is not possible to compute yaw, the function will not return an invalid value.
UE_DEPRECATED (5.2, "Deprecated as returning float instead of FVector::FReal. Use FRotator::Yaw etc.") extern AIMODULE_API TOptional< float > GetYawFromRotator(const FRotator &Rotator)
This method will extract the yaw radian from the specified rotator if it is not possible to compute yaw, the function will not return an invalid value.
UE_DEPRECATED (5.2, "Deprecated as returning float instead of FVector::FReal. Use FVector::ToOrientationRotator()::Yaw etc.") extern AIMODULE_API TOptional< float > GetYawFromVector(const FVector &Vector)
This method will extract the yaw radian from the specified vector (The vector does not need to be normalized) if it is not possible to compute yaw, the function will return an invalid value *.
UE_DEPRECATED (5.3, "Please use UE::BlueprintTools::GetActorClassDefaultComponents() instead") extern AIMODULE_API void GetActorClassDefaultComponents(const TSubclassOf< AActor > &ActorClass
Variables
TArray< UActorComponent * > const TSubclassOf< UActorComponent > & InComponentClass = TSubclassOf<UActorComponent>())
TArray< UActorComponent * > & OutComponents
Function Documentation
Bilinear()
FVector UE::AI::Bilinear (const FVector2D UV, const FVector VertexA, const FVector VertexB, const FVector VertexC, const FVector VertexD) inline
Interpolates bilinear patch A,B,C,D.
U interpolates from A->B, and C->D, and V interpolates from AB->CD.
Parameters
UV interpolation coordinates [0..1] range
VertexA first corner
VertexB second corner
VertexC third corner
VertexD fourth corner
Returns
interpolated value.
Definition at line 142 of file GeomUtils.h.
References FVector, FMath::Lerp(), and UV.
Cross2D() [1/2]
FVector::FReal UE::AI::Cross2D (const FVector & A, const FVector & B) inline
Returns
2D cross product. Using X and Y components of 3D vectors.
Definition at line 13 of file GeomUtils.h.
References A, B, and FVector.
Referenced by IntersectLineLine2D(), and SignedDistancePointLine2D().
Cross2D() [2/2]
FVector2D::FReal UE::AI::Cross2D (const FVector2D & A, const FVector2D & B) inline
Returns
2D cross product.
Definition at line 19 of file GeomUtils.h.
References A, and B.
IntersectLineLine2D()
bool UE::AI::IntersectLineLine2D (const FVector & StartA, const FVector & EndA, const FVector & StartB, const FVector & EndB, FVector2D::FReal & OutTA, FVector2D::FReal & OutTB) inline
Intersects infinite lines defined by segments A and B in 2D.
Using X and Y components of 3D vectors.
Parameters
StartA start point of segment A
EndA end point of segment A
StartB start point of segment B
EndB end point of segment B
OutTA intersection value along segment A
OutTB intersection value along segment B
Returns
if segments A and B intersect in 2D
Definition at line 97 of file GeomUtils.h.
References Cross2D(), FVector, and UE_KINDA_SMALL_NUMBER.
IntersectSegmentPoly2D()
AIMODULE_API bool UE::AI::IntersectSegmentPoly2D (const FVector & Start, const FVector & End, TConstArrayView< FVector > Poly, FVector2D::FReal & OutTMin, FVector2D::FReal & OutTMax, int32 & OutSegMin, int32 & OutSegMax) extern
Calculates intersection of segment Start-End with convex polygon Poly in 2D.
Using X and Y components of 3D vectors.
Parameters
Start start point of the segment
End end point of the segment
Poly convex polygon
OutTMin value along the segment of the first intersection point [0..1]
OutTMax value along the segment of the second intersection point [0..1]
OutSegMin index of the polygon segment of the first intersection point
OutSegMax index of the polygon segment of the second intersection point
Returns
true if the segment inside or intersects with the polygon.
References End, and FVector.
InvBilinear2D()
AIMODULE_API FVector2D UE::AI::InvBilinear2D (const FVector Point, const FVector VertexA, const FVector VertexB, const FVector VertexC, const FVector VertexD) extern
Finds the UV coordinates of the 'Point' on bilinear patch A,B,C,D.
U interpolates from A->B, and C->D, and V interpolates from AB->CD.
Parameters
Point location inside or close to the bilinear patch
VertexA first corner
VertexB second corner
VertexC third corner
VertexD fourth corner
Returns
UV interpolation coordinates of the 'Point'.
References FVector, and Point.
Referenced by InvBilinear2DClamped().
InvBilinear2DClamped()
FVector2D UE::AI::InvBilinear2DClamped (const FVector Point, const FVector VertexA, const FVector VertexB, const FVector VertexC, const FVector VertexD) inline
Finds the UV coordinates of the 'Point' on bilinear patch A,B,C,D.
U interpolates from A->B, and C->D, and V interpolates from AB->CD. The UV coordinate is clamped to [0..1] range after inversion.
Parameters
Point location inside or close to the bilinear patch
VertexA first corner
VertexB second corner
VertexC third corner
VertexD fourth corner
Returns
UV interpolation coordinates of the 'Point' in [0..1] range.
Definition at line 170 of file GeomUtils.h.
References UE::Math::TVector2< T >::ClampAxes(), FVector, InvBilinear2D(), and Point.
ProjectPointOnLine2D()
FVector::FReal UE::AI::ProjectPointOnLine2D (const FVector Point, const FVector Start, const FVector End) inline
Returns
value of the 'Point' project on infinite line defined by segment 'Start-End'. Using X and Y components of 3D vectors.
Definition at line 63 of file GeomUtils.h.
References UE::Math::TVector2< double >::DotProduct(), End, FVector, Point, UE::Math::TVector2< T >::SquaredLength(), and UE_KINDA_SMALL_NUMBER.
ProjectPointOnSegment2D()
FVector2D::FReal UE::AI::ProjectPointOnSegment2D (const FVector Point, const FVector Start, const FVector End) inline
Returns
value in range [0..1] of the 'Point' project on segment 'Start-End'. Using X and Y components of 3D vectors.
Definition at line 41 of file GeomUtils.h.
References UE::Math::TVector2< double >::DotProduct(), End, FVector, Point, UE::Math::TVector2< T >::SquaredLength(), and UE_KINDA_SMALL_NUMBER.
SignedDistancePointLine2D()
FVector::FReal UE::AI::SignedDistancePointLine2D (const FVector Point, const FVector Start, const FVector End) inline
Returns
signed distance of the 'Point' to infinite line defined by segment 'Start-End'. Using X and Y components of 3D vectors.
Definition at line 75 of file GeomUtils.h.
References Cross2D(), End, FVector, Point, UE::Math::TVector2< T >::SquaredLength(), and UE_KINDA_SMALL_NUMBER.
TriArea2D() [1/2]
FVector::FReal UE::AI::TriArea2D (const FVector & A, const FVector & B, const FVector & C) inline
Returns
2D area of triangle. Using X and Y components of 3D vectors.
Definition at line 25 of file GeomUtils.h.
References A, B, FVector, UE::Math::TVector< T >::X, and UE::Math::TVector< T >::Y.
TriArea2D() [2/2]
FVector2D::FReal UE::AI::TriArea2D (const FVector2D & A, const FVector2D & B, const FVector2D & C) inline
Returns
2D area of triangle.
Definition at line 33 of file GeomUtils.h.
References A, B, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
UE_DEPRECATED() [1/4]
UE::AI::UE_DEPRECATED (5. 2, "Deprecated as returning float instead of FVector::FReal. Use FQuat::Rotator()::Yaw etc.") const &
This method will extract the yaw radian from the specified quaternion if it is not possible to compute yaw, the function will not return an invalid value.
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
UE::AI::UE_DEPRECATED (5. 2, "Deprecated as returning float instead of FVector::FReal. Use FRotator::Yaw etc.") const &
This method will extract the yaw radian from the specified rotator if it is not possible to compute yaw, the function will not return an invalid value.
References Rotator, and UE_DEPRECATED().
UE_DEPRECATED() [3/4]
UE::AI::UE_DEPRECATED (5. 2, "Deprecated as returning float instead of FVector::FReal. Use FVector::ToOrientationRotator()::Yaw etc.") const &
This method will extract the yaw radian from the specified vector (The vector does not need to be normalized) if it is not possible to compute yaw, the function will return an invalid value *.
References FVector, and Vector.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
UE::AI::UE_DEPRECATED (5. 3, "Please use UE::BlueprintTools::GetActorClassDefaultComponents() instead") const &
References UE_DEPRECATED().
Variable Documentation
InComponentClass
TArray<UActorComponent*> const TSubclassOf<UActorComponent>& UE::AI::InComponentClass = TSubclassOf<UActorComponent>())
Definition at line 79 of file AIHelpers.h.
OutComponents
TArray<UActorComponent*>& UE::AI::OutComponents
Definition at line 79 of file AIHelpers.h.