Unreal Engine 5.6 C++ API: UE::Core::Private::TVariantStorage< Ts > Struct Template Reference
UE::Core::Private::TVariantStorage< Ts > Struct Template Reference
Determine the max alignof and sizeof of all types in a template parameter pack and provide a type that is compatible with those sizes.
#include "TVariantMeta.h"
Public Member Functions
template<SIZE_T N>
auto & GetValueAsIndexedType () &
Interpret the underlying data as the type in the variant parameter pack at the compile-time index.
template<SIZE_T N>
auto && GetValueAsIndexedType () &&
Interpret the underlying data as the type in the variant parameter pack at the compile-time index.
template<SIZE_T N>
const auto & GetValueAsIndexedType () const &
Interpret the underlying data as the type in the variant parameter pack at the compile-time index.
Static Public Member Functions
static constexpr SIZE_T MaxAlignof ()
static constexpr SIZE_T MaxOf (const SIZE_T Sizes[])
static constexpr SIZE_T MaxSizeof ()
Data Fields
TAlignedBytes< SizeofValue, AlignofValue > Storage
uint8 TypeIndex
Index into the template parameter pack for the type held.
Static Public Attributes
static constexpr SIZE_T AlignofValue = MaxAlignof()
static constexpr SIZE_T SizeofValue = MaxSizeof()
Detailed Description
template<typename... Ts>
struct UE::Core::Private::TVariantStorage< Ts >
Determine the max alignof and sizeof of all types in a template parameter pack and provide a type that is compatible with those sizes.
Definition at line 117 of file TVariantMeta.h.
Member Function Documentation
GetValueAsIndexedType() [1/3]
template<typename... Ts> template<SIZE_T N> auto & UE::Core::Private::TVariantStorage< Ts >::GetValueAsIndexedType () & inline
Interpret the underlying data as the type in the variant parameter pack at the compile-time index.
This function is used to implement Visit and should not be used directly
Definition at line 149 of file TVariantMeta.h.
References Storage.
Referenced by GetValueAsIndexedType(), and GetValueAsIndexedType().
GetValueAsIndexedType() [2/3]
template<typename... Ts> template<SIZE_T N> auto && UE::Core::Private::TVariantStorage< Ts >::GetValueAsIndexedType () && inline
Interpret the underlying data as the type in the variant parameter pack at the compile-time index.
This function is used to implement Visit and should not be used directly
Definition at line 157 of file TVariantMeta.h.
References GetValueAsIndexedType().
GetValueAsIndexedType() [3/3]
template<typename... Ts> template<SIZE_T N> const auto & UE::Core::Private::TVariantStorage< Ts >::GetValueAsIndexedType () const & inline
Interpret the underlying data as the type in the variant parameter pack at the compile-time index.
This function is used to implement Visit and should not be used directly
Definition at line 165 of file TVariantMeta.h.
References GetValueAsIndexedType().
MaxAlignof()
template<typename... Ts> constexpr SIZE_T UE::Core::Private::TVariantStorage< Ts >::MaxAlignof () inline static constexpr
Definition at line 136 of file TVariantMeta.h.
References MaxOf().
MaxOf()
template<typename... Ts> constexpr SIZE_T UE::Core::Private::TVariantStorage< Ts >::MaxOf (const SIZE_T Sizes[]) inline static constexpr
Definition at line 119 of file TVariantMeta.h.
References MaxSize.
Referenced by MaxAlignof(), and MaxSizeof().
MaxSizeof()
template<typename... Ts> constexpr SIZE_T UE::Core::Private::TVariantStorage< Ts >::MaxSizeof () inline static constexpr
Definition at line 131 of file TVariantMeta.h.
References MaxOf().
Field Documentation
AlignofValue
template<typename... Ts> SIZE_T UE::Core::Private::TVariantStorage< Ts >::AlignofValue = MaxAlignof() inline static constexpr
Definition at line 143 of file TVariantMeta.h.
SizeofValue
template<typename... Ts> SIZE_T UE::Core::Private::TVariantStorage< Ts >::SizeofValue = MaxSizeof() inline static constexpr
Definition at line 142 of file TVariantMeta.h.
Storage
template<typename... Ts> TAlignedBytes<SizeofValue, AlignofValue> UE::Core::Private::TVariantStorage< Ts >::Storage
Definition at line 171 of file TVariantMeta.h.
Referenced by GetValueAsIndexedType().
TypeIndex
template<typename... Ts> uint8 UE::Core::Private::TVariantStorage< Ts >::TypeIndex
Index into the template parameter pack for the type held.
Definition at line 175 of file TVariantMeta.h.
The documentation for this struct was generated from the following file:
TVariantMeta.h