Unreal Engine 5.6 C++ API: FBlueprintEditorUtils Class Reference
FBlueprintEditorUtils Class Reference
#include "BlueprintEditorUtils.h"
Public Types
enum class EPropertyReadableState : uint8 { Readable , Private , NotBlueprintVisible }
Enumeration of whether a property is readable or if not, why.
enum class EPropertyWritableState : uint8 { Writable , Private , NotBlueprintVisible , BlueprintReadOnly }
Enumeration of whether a property is writable or if not, why.
using FOnNodeFoundOrUpdated = TFunction<void(UBlueprint*, UK2Node*)>
Callback for when a node has been found.
Public Member Functions
DECLARE_MULTICAST_DELEGATE_FourParams (FOnRenameFunctionReferences, UBlueprint *, UClass *, const FName &, const FName &)
Event fired after RenameFunctionReferences is called.
DECLARE_MULTICAST_DELEGATE_FourParams (FOnRenameVariableReferences, UBlueprint *, UClass *, const FName &, const FName &)
Event fired after RenameVariableReferences is called.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReconstructAllNodes, UBlueprint *)
Event fired after ReconstructAllNodes is called.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnRefreshAllNodes, UBlueprint *)
Event fired after RefreshAllNodes is called.
UE_DEPRECATED (5.0, "Blueprint Nativization has been removed as a supported feature. This API will eventually be removed.") static bool PropagateNativizationSetting(UBlueprint *Blueprint)
Takes the Blueprint's NativizedFlag property and applies it to the authoritative config (does the same for flagged dependencies)
UE_DEPRECATED (5.0, "Blueprint Nativization has been removed as a supported feature. This API will eventually be removed.") static void FindNativizationDependencies(UBlueprint *Blueprint
Retrieves all dependencies that need to be nativized for this to work as a nativized Blueprint.
UE_DEPRECATED (5.1, "Short class names are no longer supported. Use a version of this function that takes FTopLevelAssetPath.") static UNREALED_API bool ImplementNewInterface(UBlueprint *Blueprint
Add a new interface, and member function graphs to the blueprint.
UE_DEPRECATED (5.1, "Short class names are no longer supported. Use a version of this function that takes FTopLevelAssetPath.") static UNREALED_API void GetInterfaceGraphs(UBlueprint *Blueprint
Gets the graphs currently in the blueprint associated with the specified interface.
UE_DEPRECATED (5.1, "Short class names are no longer supported. Use a version of this function that takes FTopLevelAssetPath.") static UNREALED_API void RemoveInterface(UBlueprint *Blueprint
Remove an implemented interface, and its associated member function graphs.
UE_DEPRECATED (5.6, "Replace with IsCompileOnLoadDisabled, ShouldRegenerateBlueprint handles reentrancy which is no longer possible.") static UNREALED_API bool ShouldRegenerateBlueprint(UBlueprint *Blueprint)
Whether or not the blueprint should regenerate its class on load or not.
UE_DEPRECATED (5.6, "Use FLinkerLoad::PRIVATE_PatchNewObjectIntoExport instead, which handles the subobjects. And note the comment on that function: both this deprecated function and the LinkerLoad function are coupled to the linker in complicated ways and should only be used in cases of blueprint reinstancing.") static UNREALED_API void PatchCDOSubobjectsIntoExport(UObject *PreviousCDO
Static Public Member Functions
static UNREALED_API void AddDomainSpecificGraph (UBlueprint *Blueprint, class UEdGraph *Graph)
Adds a domain-specific graph to this blueprint.
template<typename SignatureType>
static void AddFunctionGraph (UBlueprint *Blueprint, class UEdGraph *Graph, bool bIsUserCreated, SignatureType *SignatureFromObject)
Adds a function graph to this blueprint.
static UNREALED_API void AddInterfaceGraph (UBlueprint *Blueprint, class UEdGraph *Graph, UClass *InterfaceClass)
Adds an interface graph to this blueprint.
static UNREALED_API bool AddLocalVariable (UBlueprint *Blueprint, UEdGraph *InTargetGraph, const FName InNewVarName, const FEdGraphPinType &InNewVarType, const FString &DefaultValue=FString())
Adds a local variable to the function graph.
static UNREALED_API void AddMacroGraph (UBlueprint *Blueprint, class UEdGraph *Graph, bool bIsUserCreated, UClass *SignatureFromClass)
Adds a macro graph to this blueprint.
static UNREALED_API bool AddMemberVariable (UBlueprint *Blueprint, const FName &NewVarName, const FEdGraphPinType &NewVarType, const FString &DefaultValue=FString())
Adds a member variable to the blueprint.
static UNREALED_API class UTimelineTemplate * AddNewTimeline (UBlueprint *Blueprint, const FName &TimelineVarName)
Add a new timeline with the supplied name to the blueprint.
static UNREALED_API void AddUbergraphPage (UBlueprint *Blueprint, class UEdGraph *Graph)
Adds an ubergraph page to this blueprint.
static UNREALED_API void AnalyticsTrackNewNode (UEdGraphNode *NewNode)
Records node create events for analytics.
static UNREALED_API void BuildComponentInstancingData (UActorComponent *ComponentTemplate, FBlueprintCookedComponentInstancingData &OutData, bool bUseTemplateArchetype=false)
Generate component instancing data (for cooked builds).
static UNREALED_API void BulkRemoveMemberVariables (UBlueprint *Blueprint, const TArray< FName > &VarNames)
Removes member variables if they were declared in this blueprint and not in a base class.
static UNREALED_API bool CanClassGenerateEvents (const UClass *Class)
Checks for events in the argument class.
static UNREALED_API bool CanCreateChildBlueprint (const UBlueprint *BP)
Returns true if this blueprint can have a child class created based on it.
static UNREALED_API void ChangeLocalVariableType (UBlueprint *InBlueprint, const UStruct *InScope, const FName InVariableName, const FEdGraphPinType &InNewPinType)
Changes the type of a local variable.
static UNREALED_API void ChangeMemberVariableType (UBlueprint *Blueprint, const FName VariableName, const FEdGraphPinType &NewPinType)
Changes the type of a member variable.
static UNREALED_API bool CheckIfGraphHasLatentFunctions (UEdGraph *InGraph)
Checks if a graph (or any sub-graphs or referenced graphs) have latent function nodes.
static UNREALED_API bool CheckIfSelectionIsCycling (const TSet< UEdGraphNode * > &InSelectionSet, FCompilerResultsLog &InMessageLog)
static UNREALED_API void ClearMacroCosmeticInfoCache (UBlueprint *Blueprint)
Updates the cosmetic information cache for macros.
static UNREALED_API void ConformAllowDeletionFlag (UBlueprint *Blueprint)
Makes sure that all function graphs are flagged as bAllowDeletion=true, except for construction script and animgraph:
static UNREALED_API void ConformCallsToParentFunctions (UBlueprint *Blueprint)
Makes sure that calls to parent functions are valid, and removes them if not.
static UNREALED_API void ConformDelegateSignatureGraphs (UBlueprint *Blueprint)
Makes sure that all delegate graphs have a corresponding variable declaration, removing the graph if not.
static UNREALED_API void ConformImplementedEvents (UBlueprint *Blueprint)
Makes sure that all events we handle exist, and replace with custom events if not.
static UNREALED_API void ConformImplementedInterfaces (UBlueprint *Blueprint)
Makes sure that all graphs for all interfaces we implement exist, and add if not.
static UNREALED_API TSharedRef< SWidget > ConstructBlueprintInterfaceClassPicker (const TArray< UBlueprint * > &Blueprints, const FOnClassPicked &OnPicked)
Constructs a class picker widget for adding interfaces for the specified blueprint(s)
static UNREALED_API TSharedRef< SWidget > ConstructBlueprintParentClassPicker (const TArray< UBlueprint * > &Blueprints, const FOnClassPicked &OnPicked)
Constructs a class picker widget for reparenting the specified blueprint(s)
template<typename SignatureType>
static void CreateFunctionGraph (UBlueprint *Blueprint, class UEdGraph *Graph, bool bIsUserCreated, SignatureType *SignatureFromObject)
Creates a function graph, but does not add it to the blueprint.
static UNREALED_API void CreateMatchingFunction (UK2Node_CallFunction *InNode, TSubclassOf< class UEdGraphSchema > InSchemaClass)
Creates a new function graph with a signature that matches InNode.
static UNREALED_API class UEdGraph * CreateNewGraph (UObject *ParentScope, const FName &GraphName, TSubclassOf< class UEdGraph > GraphClass, TSubclassOf< class UEdGraphSchema > SchemaClass)
Creates a new empty graph.
static UNREALED_API bool DoesBlueprintContainField (const UBlueprint *Blueprint, UField *TestField)
See if a field (property, function etc) is part of the blueprint chain, or.
static UNREALED_API bool DoesBlueprintDeriveFrom (const UBlueprint *Blueprint, UClass *TestClass)
See if a class is the one generated by this blueprint.
static UNREALED_API bool DoesSupportComponents (UBlueprint const *Blueprint)
Returns whether or not the blueprint supports components.
static UNREALED_API bool DoesSupportDefaults (UBlueprint const *Blueprint)
Returns whether or not the blueprint supports default values (IE has a CDO)
static UNREALED_API bool DoesSupportEventGraphs (const UBlueprint *Blueprint)
Returns whether or not the blueprint supports event graphs.
static UNREALED_API bool DoesSupportImplementingInterfaces (const UBlueprint *Blueprint)
Returns whether or not the blueprint supports implementing interfaces.
static UNREALED_API bool DoesSupportLocalVariables (UEdGraph const *InGraph)
Returns whether or not the blueprint graph supports local variables.
static UNREALED_API bool DoesSupportOverridingFunctions (const UBlueprint *Blueprint)
Returns whether or not the blueprint supports overriding functions.
static UNREALED_API bool DoesSupportTimelines (const UBlueprint *Blueprint)
Returns whether or not the blueprint supports timelines.
static UNREALED_API FName DuplicateMemberVariable (UBlueprint *InFromBlueprint, UBlueprint *InToBlueprint, FName InVariableToDuplicate)
Duplicates a variable from one Blueprint to another blueprint.
static UNREALED_API FName DuplicateVariable (UBlueprint *InBlueprint, const UStruct *InScope, FName InVariableToDuplicate)
Duplicates a variable given its name and Blueprint.
static UNREALED_API FBPVariableDescription DuplicateVariableDescription (UBlueprint *InBlueprint, FBPVariableDescription &InVariableDescription)
Internal function that deep copies a variable description.
static UNREALED_API void EnsureCachedDependenciesUpToDate (UBlueprint *Blueprint)
Ensures, that CachedDependencies in BP are up to date.
static UNREALED_API void FindActorsThatReferenceActor (AActor *InActor, TArray< UClass * > &InClassesToIgnore, TArray< AActor * > &OutReferencingActors)
Find how many actors reference the supplied actor.
static UNREALED_API void FindAndSetDebuggableBlueprintInstances ()
Searches the world for any blueprints that are open and do not have a debug instances set and sets one if possible.
static UNREALED_API UBlueprint * FindBlueprintForGraph (const UEdGraph *Graph)
Helper function to get the blueprint that ultimately owns a graph.
static UNREALED_API UBlueprint * FindBlueprintForGraphChecked (const UEdGraph *Graph)
Helper function to get the blueprint that ultimately owns a graph.
static UNREALED_API UBlueprint * FindBlueprintForNode (const UEdGraphNode *Node)
Helper function to get the blueprint that ultimately owns a node.
static UNREALED_API UBlueprint * FindBlueprintForNodeChecked (const UEdGraphNode *Node)
Helper function to get the blueprint that ultimately owns a node.
static UNREALED_API UK2Node_Event * FindCustomEventNode (const UBlueprint *Blueprint, FName const CustomName)
Find the Custom Event if it already exists in the Blueprint.
static UNREALED_API void FindDependentBlueprints (UBlueprint *Blueprint, TArray< UBlueprint * > &DependentBlueprints)
Searches the reference graph to find blueprints that are dependent on this BP.
static UNREALED_API void FindEnumsInNodes (const TSet< UEnum * > &UEnums, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated)
Search the blueprints looking for nodes that contain the given enumerations.
static UNREALED_API UEdGraph * FindEventGraph (const UBlueprint *Blueprint)
Returns the event graph, if any.
static UNREALED_API UEdGraphPin * FindFirstCompilerRelevantLinkedPin (UEdGraphPin *FromPin)
Finds the first compiler-relevant (i.e.
static UNREALED_API UK2Node * FindFirstCompilerRelevantNode (UEdGraphPin *FromPin)
Finds the first compiler-relevant (i.e.
static UNREALED_API const UClass * FindFirstNativeClass (const UClass *Class)
static UNREALED_API UClass * FindFirstNativeClass (UClass *Class)
return find first native class in the hierarchy
static UNREALED_API UFunction * FindFunctionInImplementedInterfaces (const UBlueprint *Blueprint, const FName &FunctionName, bool *bOutInvalidInterface=nullptr, bool bGetAllInterfaces=false)
Return the first function from implemented interface with given name.
static UNREALED_API void FindImplementedInterfaces (const UBlueprint *Blueprint, bool bGetAllInterfaces, TArray< UClass * > &ImplementedInterfaces)
Build a list of all interface classes either implemented by this blueprint or through inheritance.
static UNREALED_API int32 FindIndexOfGraphInParent (UEdGraph *Graph)
Finds the index of the specified graph (function or macro) in the parent (if it is not reorderable, then we will return INDEX_NONE)
static UNREALED_API FGuid FindInterfaceFunctionGuid (const UFunction *Function, const UClass *InterfaceClass)
Find the interface Guid for a function if it exists.
static UNREALED_API FBPVariableDescription * FindLocalVariable (const UBlueprint *InBlueprint, const UEdGraph *InScopeGraph, const FName InVariableName, class UK2Node_FunctionEntry **OutFunctionEntry=NULL)
Returns a local variable.
static UNREALED_API FBPVariableDescription * FindLocalVariable (const UBlueprint *InBlueprint, const UStruct *InScope, const FName InVariableName, class UK2Node_FunctionEntry **OutFunctionEntry=NULL)
Returns a local variable.
static UNREALED_API FBPVariableDescription * FindLocalVariable (UBlueprint *InBlueprint, const UStruct *InScope, const FName InVariableName)
Returns a local variable with the function entry it was found in.
static UNREALED_API FGuid FindLocalVariableGuidByName (UBlueprint *InBlueprint, const UEdGraph *InScopeGraph, const FName InVariableName)
Finds a local variable Guid using the variable's name.
static UNREALED_API FGuid FindLocalVariableGuidByName (UBlueprint *InBlueprint, const UStruct *InScope, const FName InVariableName)
Finds a local variable Guid using the variable's name.
static UNREALED_API int32 FindLocalVariableIndex (const UBlueprint *Blueprint, UStruct *VariableScope, const FName &InVariableName)
Find the index of a local variable declared in this blueprint.
static UNREALED_API FName FindLocalVariableNameByGuid (UBlueprint *InBlueprint, const FGuid &InVariableGuid)
Finds a local variable name using the variable's Guid.
static UNREALED_API FGuid FindMemberVariableGuidByName (UBlueprint *InBlueprint, const FName InVariableName)
Finds a member variable Guid using the variable's name.
static UNREALED_API FName FindMemberVariableNameByGuid (UBlueprint *InBlueprint, const FGuid &InVariableGuid)
Finds a member variable name using the variable's Guid.
static UNREALED_API int32 FindNewVariableIndex (const UBlueprint *Blueprint, const FName &InName)
Find the index of a variable first declared in this blueprint.
static UNREALED_API int32 FindNewVariableIndexAndBlueprint (UBlueprint *InBlueprint, FName InName, UBlueprint *&OutFoundBlueprint)
Find the index of a variable first declared in this blueprint or its parents.
static UNREALED_API class UK2Node_Timeline * FindNodeForTimeline (UBlueprint *Blueprint, UTimelineTemplate *Timeline)
Find the node that owns the supplied timeline template.
static UNREALED_API class UK2Node_FunctionResult * FindOrCreateFunctionResultNode (class UK2Node_EditablePinBase *InFunctionEntryNode)
Creates a function result node or returns the current one if one exists.
static UNREALED_API UK2Node_Event * FindOverrideForFunction (const UBlueprint *Blueprint, const UClass *SignatureClass, FName SignatureName)
Look to see if an event already exists to override a particular function.
static UNREALED_API bool FindReferencesToActorFromLevelScript (ULevelScriptBlueprint *LevelScriptBlueprint, AActor *InActor, TArray< UK2Node * > &ReferencedToActors)
Find how many nodes reference the supplied actor.
static UNREALED_API UEdGraph * FindScopeGraph (const UBlueprint *InBlueprint, const UStruct *InScope)
Finds the scope's associated graph for local variables (or any passed UFunction)
static UNREALED_API void FindScriptStructsInNodes (const TSet< UScriptStruct * > &Structs, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated)
Search the blueprints looking for nodes that contain the given script structs.
static UNREALED_API USCS_Node * FindSCS_Node (const UBlueprint *Blueprint, const FName InName)
Finds an SCSNode by variable name.
static UNREALED_API int32 FindTimelineIndex (const UBlueprint *Blueprint, const FName &InName)
Find the index of a timeline first declared in this blueprint.
static UNREALED_API UActorComponent * FindUCSComponentTemplate (const FComponentKey &ComponentKey, const FName &TemplateName)
Attempts to match up the FComponentKey with a ComponentTemplate from the Blueprint's UCS.
static UNREALED_API FName FindUniqueCustomEventName (const UBlueprint *Blueprint)
Finds a unique and valid name for a custom event.
static UNREALED_API FName FindUniqueKismetName (const UBlueprint *InBlueprint, const FString &InBaseName, UStruct *InScope=NULL)
Finds a unique name with a base of the passed in string, appending numbers as needed.
static UNREALED_API FName FindUniqueTimelineName (const UBlueprint *Blueprint)
Finds a name for a timeline that is not already in use.
static UNREALED_API UEdGraph * FindUserConstructionScript (const UBlueprint *Blueprint)
Returns the user construction script, if any.
static UNREALED_API void FixLevelScriptActorBindings (ALevelScriptActor *LevelScriptActor, const class ULevelScriptBlueprint *ScriptBlueprint)
Called after a level script blueprint is changed and nodes should be refreshed for it's new level script actor.
static UNREALED_API void FixupVariableDescription (UBlueprint *Blueprint, FBPVariableDescription &VarDesc)
Check blueprint variable metadata keys/values for validity and make adjustments if needed.
static UNREALED_API void GatherDependencies (const UBlueprint *Blueprint, TSet< TWeakObjectPtr< UBlueprint > > &OutDependencies, TSet< TWeakObjectPtr< UStruct > > &OutUDSDependencies)
Gather all bps that Blueprint depends on.
static UNREALED_API FName GenerateUniqueGraphName (UObject *const InOuter, FString const &ProposedName)
Generates a unique graph name for the supplied blueprint (guaranteed to not cause a naming conflict at the time of the call).
static UNREALED_API void GetActorReferenceMap (UWorld *InWorld, TArray< UClass * > &InClassesToIgnore, TMap< AActor *, TArray< AActor * > > &OutReferencingActors)
Go through the world and build a map of all actors that are referenced by other actors.
static UNREALED_API void GetAllGraphNames (const UBlueprint *Blueprint, TSet< FName > &GraphNames)
Gets the names of all graphs in the Blueprint.
template<class T>
static void GetAllNodesOfClass (const UBlueprint *Blueprint, TArray< T * > &OutNodes)
Returns all nodes in all graphs of the specified class.
template<class MinNodeType, class ArrayClassType>
static void GetAllNodesOfClassEx (const UBlueprint *Blueprint, TArray< ArrayClassType * > &OutNodes)
Returns all nodes in all graphs of at least the minimum node type.
static UNREALED_API UAnimGraphNode_Root * GetAnimGraphRoot (UEdGraph *InGraph)
Helper function to grab the root node from an anim graph.
static UNREALED_API FString GetBlueprintTypeDescription (const UBlueprint *Blueprint)
static UNREALED_API FText GetBlueprintVariableCategory (UBlueprint *Blueprint, const FName &VarName, const UStruct *InLocalVarScope)
Gets the custom category on the variable with the specified name.
static UNREALED_API bool GetBlueprintVariableMetaData (const UBlueprint *Blueprint, const FName &VarName, const UStruct *InLocalVarScope, const FName &MetaDataKey, FString &OutMetaDataValue)
Get a metadata key/value on the specified variable, or timeline if it exists, returning false if it does not exist.
static UNREALED_API uint64 * GetBlueprintVariablePropertyFlags (UBlueprint *Blueprint, const FName &VarName)
Gets pointer to PropertyFlags of variable.
static UNREALED_API FName GetBlueprintVariableRepNotifyFunc (UBlueprint *Blueprint, const FName &VarName)
Get RepNotify function name of variable.
static UNREALED_API int32 GetChildrenOfBlueprint (UBlueprint *InBlueprint, TArray< FAssetData > &OutChildren, bool bInRecursive=true)
Gets AssetData for all child classes of a given blueprint.
static UNREALED_API FString GetClassNameWithoutSuffix (const UClass *Class)
Returns a class name for the specified class that has no automatic suffixes, but is otherwise unmodified.
static UNREALED_API void GetClassVariableList (const UBlueprint *Blueprint, TSet< FName > &VisibleVariables, bool bIncludePrivateVars=false)
Gets the visible class variable list.
static UNREALED_API void GetCompilerRelevantNodeLinks (UEdGraphPin *FromPin, FCompilerRelevantNodeLinkArray &OutNodeLinks)
Gets the compiler-relevant (i.e.
static UNREALED_API FBlueprintMacroCosmeticInfo GetCosmeticInfoForMacro (UEdGraph *MacroGraph)
Returns the cosmetic information for the specified macro graph, caching it if necessary.
static UNREALED_API void GetDelegateNameList (const UBlueprint *Blueprint, TSet< FName > &DelegatesNames)
Gets a list of delegates names in the blueprint, based on the skeleton class.
static UNREALED_API UEdGraph * GetDelegateSignatureGraphByName (UBlueprint *Blueprint, FName DelegateName)
Get a graph for delegate signature with given name, from given blueprint.
static UNREALED_API void GetDependentBlueprints (UBlueprint *Blueprint, TArray< UBlueprint * > &DependentBlueprints)
Returns cached a list of loaded Blueprints that are dependent on the given Blueprint.
static UNREALED_API FText GetDeprecatedMemberMenuItemName (const FText &MemberName)
Returns a formatted menu item label for a deprecated variable or function member with the given name.
static UNREALED_API FText GetDeprecatedMemberUsageNodeWarning (const FText &MemberName, const FText &DetailedMessage)
Returns a formatted warning message regarding usage of a deprecated variable or function member with the given name.
static UNREALED_API EEdGraphNodeDeprecationMessageType GetDeprecatedMessageType (const FString &TypeString)
Returns the severity of a deprecation warning by parsing a string loaded from metadata like DeprecatedFunction="Note".
static UNREALED_API void GetEntryAndResultNodes (const UEdGraph *InGraph, TWeakObjectPtr< class UK2Node_EditablePinBase > &OutEntryNode, TWeakObjectPtr< class UK2Node_EditablePinBase > &OutResultNode)
Finds the entry and result nodes for a function or macro graph.
static UNREALED_API class UK2Node_EditablePinBase * GetEntryNode (const UEdGraph *InGraph)
Finds the entry node for a function or macro graph.
static UNREALED_API FText GetFriendlyClassDisplayName (const UClass *Class)
Returns a friendly class display name for the specified class (removing things like _C from the end, may localize the class name).
static UNREALED_API bool GetFunctionGuidFromClassByFieldName (const UClass *InClass, const FName FunctionName, FGuid &FunctionGuid)
static UNREALED_API FName GetFunctionNameFromClassByGuid (const UClass *InClass, const FGuid FunctionGuid)
static UNREALED_API void GetFunctionNameList (const UBlueprint *Blueprint, TSet< FName > &FunctionNames)
Gets a list of function names currently in use in the blueprint, based on the skeleton class.
static UNREALED_API FText GetGraphDescription (const UEdGraph *InGraph)
Returns the description of the graph from the metadata.
static UNREALED_API FKismetUserDeclaredFunctionMetadata * GetGraphFunctionMetaData (const UEdGraph *InGraph)
Returns the function meta data block for the graph entry node.
static UNREALED_API void GetHiddenPinsForFunction (UEdGraph const *Graph, UFunction const *Function, TSet< FName > &HiddenPins, TSet< FName > *OutInternalPins=nullptr)
Gets a list of pins that should hidden for a given function in a given graph.
static UNREALED_API const struct FSlateBrush * GetIconFromPin (const FEdGraphPinType &PinType, bool bIsLarge=false)
Determine the best icon to represent the given pin.
static UNREALED_API void GetImplementingBlueprintsFunctionNameList (const UBlueprint *Blueprint, TSet< FName > &FunctionNames)
Gets a list of function names in blueprints that implement the interface defined by the given blueprint.
static UNREALED_API UFunction * GetInterfaceFunction (UBlueprint *Blueprint, const FName FuncName)
Get the corresponding UFunction pointer to the name given on the blueprint.
static UNREALED_API void GetInterfaceGraphs (UBlueprint *Blueprint, FTopLevelAssetPath InterfaceClassPathName, TArray< UEdGraph * > &ChildGraphs)
Gets the graphs currently in the blueprint associated with the specified interface.
static UNREALED_API class ULevel * GetLevelFromBlueprint (const UBlueprint *Blueprint)
If a blueprint is directly tied to a level (level script and anonymous blueprints), this will return a pointer to that level.
static UNREALED_API void GetLocalVariablesOfType (const UEdGraph *Graph, const FEdGraphPinType &Type, TArray< FName > &OutVars)
Gets local variables of specified type.
static UNREALED_API const UClass * GetMostUpToDateClass (const UClass *FromClass)
static UNREALED_API UClass * GetMostUpToDateClass (UClass *FromClass)
Helper function to get the most up to date class , returns FromClass for native types, SkeletonClass for UBlueprint generated classes.
static UNREALED_API const UFunction * GetMostUpToDateFunction (const UFunction *Function)
static UNREALED_API UFunction * GetMostUpToDateFunction (UFunction *Function)
static UNREALED_API const FProperty * GetMostUpToDateProperty (const FProperty *Property)
static UNREALED_API FProperty * GetMostUpToDateProperty (FProperty *Property)
Returns the skeleton version of the property, skeleton classes are often more up to date than the authoritative GeneratedClass.
static UNREALED_API UClass * GetNativeParent (const UBlueprint *BP)
Returns the BPs most derived native parent type:
static UNREALED_API void GetNewVariablesOfType (const UBlueprint *Blueprint, const FEdGraphPinType &Type, TArray< FName > &OutVars)
Gets variables of specified type.
static UEdGraphNode * GetNodeByGUID (const UBlueprint *InBlueprint, const FGuid &InNodeGuid)
Searches all nodes in a Blueprint and checks for a matching Guid.
static UNREALED_API UClass *const GetOverrideFunctionClass (UBlueprint *Blueprint, const FName FuncName, UFunction **OutFunction=nullptr)
Get the override class of a given function from its name.
static UNREALED_API void GetSCSVariableNameList (const UBlueprint *Blueprint, TSet< FName > &VariableNames)
Gets a list of SCS node variable names for the given blueprint.
static UNREALED_API void GetSCSVariableNameList (const UBlueprintGeneratedClass *BPGC, TSet< FName > &VariableNames)
Gets a list of SCS node variable names for the given BPGC.
static UNREALED_API void GetSCSVariableNameList (const USimpleConstructionScript *SCS, TSet< FName > &VariableNames)
Gets a list of SCS node variable names for the given SCS.
static UNREALED_API const struct FSlateBrush * GetSecondaryIconFromPin (const FEdGraphPinType &PinType)
Determine the best secondary icon icon to represent the given pin.
static UNREALED_API const UClass * GetSkeletonClass (const UClass *FromClass)
static UNREALED_API UClass * GetSkeletonClass (UClass *FromClass)
Helper function to get the SkeletonClass, returns nullptr for UClasses that are not generated by a UBlueprint.
static UNREALED_API UEdGraph * GetTopLevelGraph (const UEdGraph *InGraph)
Returns the graph's top level graph (climbing up the hierarchy until there are no more graphs)
static UNREALED_API UClass * GetTypeForPin (const UEdGraphPin &Pin)
Returns the UClass type for an object pin, if any.
static UNREALED_API FName GetUbergraphFunctionName (const UBlueprint *ForBlueprint)
Returns the name of the Ubergraph Function that the provided blueprint uses.
static UNREALED_API void GetUsedAndUnusedVariables (UBlueprint *Blueprint, TArray< FProperty * > &OutUsedVariables, TArray< FProperty * > &OutUnusedVariables)
Removes all unused member variables.
static UNREALED_API FBPVariableDescription * GetVariableFromOnRepFunction (UBlueprint *Blueprint, FName FuncName)
Gets the variable linked to a RepNotify function, returns nullptr if not found.
static UNREALED_API void HandleDisableEditableWhenInherited (UObject *ModifiedObject, TArray< UObject * > &ArchetypeInstances)
Remove overridden component templates from instance component handlers when a parent class disables editable when inherited boolean.
static UNREALED_API bool HasFunctionBlueprintThreadSafeMetaData (const UFunction *InFunction)
static UNREALED_API bool HasGetTypeHash (const FEdGraphPinType &PinType)
Returns true if this terminal type can be hashed (native types need GetTypeHash, script types are always hashable).
static UNREALED_API bool ImplementNewInterface (UBlueprint *Blueprint, FTopLevelAssetPath InterfaceClassPathName)
Add a new interface, and member function graphs to the blueprint.
static UNREALED_API bool ImplementsGetWorld (const UBlueprint *BP)
Returns true if this BP is currently based on a type that returns true for the UObject::ImplementsGetWorld() call:
static UNREALED_API bool ImplementsInterface (const UBlueprint *Blueprint, bool bIncludeInherited, UClass *SomeInterface)
Returns true if the interfaces is implemented.
static UNREALED_API bool IsActorBased (const UBlueprint *Blueprint)
Whether or not this is an actor-based blueprint, and supports features like the uber-graph, components, etc.
static UNREALED_API bool IsAnonymousBlueprintClass (const UClass *Class)
Whether or not this class represents a class generated by an anonymous actor class stored in a level.
static UNREALED_API bool IsBlueprintConst (const UBlueprint *Blueprint)
Returns whether or not the blueprint is const during execution.
static UNREALED_API bool IsCompileOnLoadDisabled (UBlueprint *Blueprint)
Returns true if compilation for the given blueprint has been disabled.
static UNREALED_API bool IsComponentBased (const UBlueprint *Blueprint)
static UNREALED_API bool IsDataOnlyBlueprint (const UBlueprint *Blueprint)
static UNREALED_API bool IsDelegateSignatureGraph (const UEdGraph *Graph)
Checks if given graph contains a delegate signature.
static UNREALED_API bool IsEditorUtilityBlueprint (const UBlueprint *Blueprint)
Returns whether or not the blueprint is an editor utility blueprint or widget.
static UNREALED_API bool IsEventGraph (const UEdGraph *InGraph)
Checks if given graph is an event graph.
static UNREALED_API bool IsFunctionConvertableToEvent (UBlueprint *const BlueprintObj, UFunction *const Function)
Check if the blueprint and function are valid options for conversion to an event (BP is not a function library)
static UNREALED_API bool IsFunctionUsed (const UBlueprint *FunctionBlueprint, const FName &FunctionName, const UEdGraph *LocalGraphScope=nullptr)
Indicates if the function is used on any graphs in this Blueprint.
static UNREALED_API bool IsGraphIntermediate (const UEdGraph *Graph)
returns if a graph is an intermediate build product
static UNREALED_API bool IsGraphNameUnique (UObject *InOuter, const FName &InName)
See whether or not the specified graph name / entry point name is unique.
static UNREALED_API bool IsGraphReadOnly (UEdGraph *InGraph)
Determines if the graph is ReadOnly, this differs from editable in that it is never expected to be edited and is in a read-only state.
static UNREALED_API bool IsInterfaceBlueprint (const UBlueprint *Blueprint)
Whether or not this blueprint is an interface, used only for defining functions to implement.
static UNREALED_API bool IsInterfaceFunction (UBlueprint *Blueprint, UFunction *Function)
Checks if the given function is a part of an interface on this blueprint.
static UNREALED_API bool IsInterfaceGraph (const UEdGraph *Graph)
Whether or not this graph is an interface graph (i.e.
static UNREALED_API bool IsLevelScriptBlueprint (const UBlueprint *Blueprint)
Whether or not this blueprint is an interface, used only for defining functions to implement.
static UNREALED_API bool IsMathExpressionGraph (const UEdGraph *InGraph)
Checks if given graph is owned by a Math Expression node.
static UNREALED_API bool IsNativeSignature (const UFunction *Fn)
returns true if this blueprints signature (inc.
static UNREALED_API bool IsPaletteActionReadOnly (TSharedPtr< FEdGraphSchemaAction > ActionIn, TSharedPtr< class FBlueprintEditor > const BlueprintEditorIn)
A utility function intended to aid the construction of a specific blueprint palette item.
static UNREALED_API bool IsParentClassABlueprint (const UBlueprint *Blueprint)
Returns whether the parent class of the specified blueprint is also a blueprint.
static UNREALED_API bool IsParentClassAnEditableBlueprint (const UBlueprint *Blueprint)
Returns whether the parent class of the specified blueprint is an editable blueprint.
static UNREALED_API bool IsPinTypeValid (const FEdGraphPinType &Type)
Checks if pin type stores proper type for a variable or parameter.
static UNREALED_API bool IsPropertyPrivate (const FProperty *Property)
static UNREALED_API EPropertyReadableState IsPropertyReadableInBlueprint (const UBlueprint *Blueprint, const FProperty *Property)
Returns an enumeration indicating if the property can be read by the given Blueprint.
static UNREALED_API EPropertyWritableState IsPropertyWritableInBlueprint (const UBlueprint *Blueprint, const FProperty *Property)
Returns an enumeration indicating if the property can be written to by the given Blueprint.
static UNREALED_API bool IsSCSComponentProperty (FObjectProperty *MemberProperty)
Determines if this property is associated with a component that would be displayed in the SCS editor.
static UNREALED_API bool IsTunnelInstanceNode (const UEdGraphNode *InGraphNode)
Checks if given node is a tunnel instance node.
static UNREALED_API bool IsVariableComponent (const FBPVariableDescription &Variable)
Returns whether or not the specified member var is a component.
static UNREALED_API bool IsVariableCreatedByBlueprint (UBlueprint *InBlueprint, FProperty *InVariableProperty)
Returns TRUE if the variable was created by the Blueprint.
static UNREALED_API bool IsVariableUsed (const UBlueprint *VariableBlueprint, const FName &VariableName, const UEdGraph *LocalGraphScope=nullptr)
Indicates if the variable is used on any graphs in this Blueprint.
static UNREALED_API bool KismetDiagnosticExec (const TCHAR *Stream, FOutputDevice &Ar)
static UNREALED_API void LinkExternalDependencies (UBlueprint *Blueprint)
Links external dependencies.
static UNREALED_API void ListPackageContents (UPackage *Package, FOutputDevice &Ar)
static UNREALED_API void MarkBlueprintAsModified (UBlueprint *Blueprint, FPropertyChangedEvent PropertyChangedEvent=FPropertyChangedEvent(nullptr))
Blueprint has changed in some manner that invalidates the compiled data (link made/broken, default value changed, etc...)
static UNREALED_API void MarkBlueprintAsStructurallyModified (UBlueprint *Blueprint)
Blueprint has structurally changed (added/removed functions, graphs, etc...).
static UNREALED_API void MarkBlueprintChildrenAsModified (UBlueprint *InBlueprint)
Marks all children of a blueprint as modified.
static UNREALED_API void ModifyActorReferencedGraphNodes (ULevelScriptBlueprint *LevelScriptBlueprint, const AActor *InActor)
Function to call modify() on all graph nodes which reference this actor.
static UNREALED_API void ModifyFunctionMetaData (const UEdGraph *InGraph)
Modifies the graph entry node that contains the function metadata block, used in metadata transactions.
static UNREALED_API bool MoveGraphBeforeOtherGraph (UEdGraph *Graph, int32 NewIndex, bool bDontRecompile)
Reorders the specified graph (function or macro) to be at the new index in the parent (moving whatever was there to be after it), assuming it is reorderable and that is a valid index.
static UNREALED_API bool MoveVariableAfterVariable (UBlueprint *Blueprint, UStruct *VariableScope, FName VarNameToMove, FName TargetVarName, bool bDontRecompile)
Change the order of variables in the Blueprint by placing a variable after the target variable.
static UNREALED_API bool MoveVariableBeforeVariable (UBlueprint *Blueprint, UStruct *VariableScope, FName VarNameToMove, FName TargetVarName, bool bDontRecompile)
Change the order of variables in the Blueprint by placing a variable before the target variable.
static UNREALED_API void OpenReparentBlueprintMenu (const TArray< UBlueprint * > &Blueprints, const TSharedRef< SWidget > &ParentContent, const FOnClassPicked &OnPicked)
static UNREALED_API void OpenReparentBlueprintMenu (UBlueprint *Blueprint, const TSharedRef< SWidget > &ParentContent, const FOnClassPicked &OnPicked)
Try to open reparent menu for specified blueprint.
static UNREALED_API void PatchNewCDOIntoLinker (UObject *CDO, FLinkerLoad *Linker, int32 ExportIndex, FUObjectSerializeContext *InLoadContext)
Helper function to patch the new CDO into the linker where the old one existed.
static UNREALED_API void PostDuplicateBlueprint (UBlueprint *Blueprint, bool bDuplicateForPIE)
Called on a Blueprint after it has been duplicated.
static UNREALED_API void PostEditChangeBlueprintActors (UBlueprint *Blueprint, bool bComponentEditChange=false)
Call PostEditChange() on all Actors based on the given Blueprint.
static UNREALED_API void PreloadBlueprintSpecificData (UBlueprint *Blueprint)
Helper function to punch through and honor UAnimGraphNode_Base::PreloadRequiredAssets, which formerly relied on loading assets during compile.
static UNREALED_API void PreloadConstructionScript (UBlueprint *Blueprint)
Preloads the construction script, and all templates therein, for the given Blueprint object.
static UNREALED_API void PreloadConstructionScript (USimpleConstructionScript *SimpleConstructionScript)
Preloads the given construction script, and all templates therein.
static UNREALED_API void PreloadMembers (UObject *InObject)
Preloads the object and all the members it owns (nodes, pins, etc)
static UNREALED_API void PromoteGraphFromInterfaceOverride (UBlueprint *InBlueprint, UEdGraph *InInterfaceGraph)
Promotes a Graph from being an Interface Override to a full member function.
static UNREALED_API void PropagateParentBlueprintDefaults (UClass *ClassToPropagate)
Copies the default properties of all parent blueprint classes in the chain to the specified blueprint's skeleton CDO.
static UNREALED_API bool PropertyHasGetTypeHash (const FProperty *PropertyType)
Returns true if this type of FProperty can be hashed.
static UNREALED_API bool PropertyStillExists (FProperty *Property)
Looks at the most up to data class and returns whether the given property exists in it as well.
static UNREALED_API bool PropertyValueFromString (const FProperty *Property, const FString &StrValue, uint8 *Container, UObject *OwningObject=nullptr, int32 PortFlags=PPF_None)
Copies the value from the passed in string into a property.
static UNREALED_API bool PropertyValueFromString_Direct (const FProperty *Property, const FString &StrValue, uint8 *DirectValue, UObject *OwningObject=nullptr, int32 PortFlags=PPF_None)
Copies the value from the passed in string into a property.
static UNREALED_API bool PropertyValueToString (const FProperty *Property, const uint8 *Container, FString &OutForm, UObject *OwningObject=nullptr, int32 PortFlags=PPF_None)
Copies the value from a property into the string OutForm.
static UNREALED_API bool PropertyValueToString_Direct (const FProperty *Property, const uint8 *DirectValue, FString &OutForm, UObject *OwningObject=nullptr, int32 PortFlags=PPF_None)
Copies the value from a property into the string OutForm.
static UNREALED_API void PurgeNullGraphs (UBlueprint *Blueprint)
Makes sure that all NULL graph references are removed from SubGraphs and top-level graph arrays.
static UNREALED_API void RecombineNestedSubPins (UK2Node *Node)
Recombine any nested subpins on this node.
static UNREALED_API void ReconstructAllNodes (UBlueprint *Blueprint)
Reconstructs all nodes in the blueprint, node reconstruction order determined by FCompareNodePriority.
static UNREALED_API void RecreateClassMetaData (UBlueprint *Blueprint, UClass *Class, bool bRemoveExistingMetaData)
Recreates class meta data.
static UNREALED_API void RefreshAllNodes (UBlueprint *Blueprint)
Schedules and refreshes all nodes in the blueprint, making sure that nodes that affect function signatures get regenerated first.
static UNREALED_API void RefreshExternalBlueprintDependencyNodes (UBlueprint *Blueprint, UStruct *RefreshOnlyChild=NULL)
Optimized refresh of nodes that depend on external blueprints.
static UNREALED_API void RefreshGraphNodes (const UEdGraph *Graph)
Refresh the nodes of an individual graph.
static UNREALED_API void RefreshVariables (UBlueprint *Blueprint)
Synchronizes Blueprint's GeneratedClass's properties with the NewVariable declarations in the blueprint.
static UNREALED_API void RemoveAllLocalBookmarks (const UBlueprint *ForBlueprint)
Removes all local bookmarks that reference the given Blueprint asset.
static UNREALED_API void RemoveBlueprintVariableMetaData (UBlueprint *Blueprint, const FName &VarName, const UStruct *InLocalVarScope, const FName &MetaDataKey)
Clear metadata key on specified variable, or timeline.
static UNREALED_API void RemoveFieldNotifyFromAllMetadata (UBlueprint *Blueprint, const FName VarName)
Removes a field notify variable from the metadata of all other field notify variables and functions.
static UNREALED_API void RemoveGeneratedClasses (UBlueprint *Blueprint)
Consigns the blueprint's generated classes to oblivion.
static UNREALED_API void RemoveGraph (UBlueprint *Blueprint, class UEdGraph *GraphToRemove, EGraphRemoveFlags::Type Flags=EGraphRemoveFlags::Default)
Removes the supplied graph from the Blueprint.
static UNREALED_API void RemoveGraphs (UBlueprint *Blueprint, const TArray< class UEdGraph * > &GraphsToRemove)
Remove the supplied set of graphs from the Blueprint.
static UNREALED_API void RemoveInterface (UBlueprint *Blueprint, FTopLevelAssetPath InterfaceClassPathName, bool bPreserveFunctions=false)
Remove an implemented interface, and its associated member function graphs.
static UNREALED_API bool RemoveInterfaceFunction (UBlueprint *Blueprint, FBPInterfaceDescription &Interface, UFunction *Function, bool bPreserveFunction)
Attempt to remove a function from an interfaces list of function graphs.
static UNREALED_API void RemoveLocalVariable (UBlueprint *InBlueprint, const UStruct *InScope, const FName InVarName)
Removes a member variable if it was declared in this blueprint and not in a base class.
static UNREALED_API void RemoveMemberVariable (UBlueprint *Blueprint, const FName VarName)
Removes a member variable if it was declared in this blueprint and not in a base class.
static UNREALED_API void RemoveNode (UBlueprint *Blueprint, UEdGraphNode *Node, bool bDontRecompile=false)
Removes the supplied node from the Blueprint.
static UNREALED_API void RemoveStaleFunctions (UBlueprintGeneratedClass *Class, UBlueprint *Blueprint)
Procedure used to remove old function implementations and child properties from data only blueprints.
static UNREALED_API void RemoveTimeline (UBlueprint *Blueprint, class UTimelineTemplate *Timeline, bool bDontRecompile=false)
Remove the timeline from the blueprint.
static UNREALED_API void RemoveVariableNodes (UBlueprint *Blueprint, const FName VarName, bool const bForSelfOnly=true, UEdGraph *LocalGraphScope=nullptr)
Removes the variable nodes associated with the specified var name.
static UNREALED_API void RenameComponentMemberVariable (UBlueprint *Blueprint, USCS_Node *Node, const FName NewName)
Rename a member variable created by a SCS entry.
static UNREALED_API void RenameFunctionReferences (UBlueprint *Blueprint, UClass *FunctionClass, const FName &OldFuncName, const FName &NewFuncName)
Looks through the specified blueprint for any references to the specified function, and renames them accordingly.
static UNREALED_API void RenameGraph (class UEdGraph *Graph, const FString &NewName)
Tries to rename the supplied graph.
static UNREALED_API void RenameGraphWithSuggestion (class UEdGraph *Graph, TSharedPtr< class INameValidatorInterface > NameValidator, const FString &DesiredName)
Renames the graph of the supplied node with a valid name based off of the suggestion.
static UNREALED_API void RenameLocalVariable (UBlueprint *InBlueprint, const UStruct *InScope, const FName InOldName, const FName InNewName)
Rename a local variable.
static UNREALED_API void RenameMemberVariable (UBlueprint *Blueprint, const FName OldName, const FName NewName)
Rename a member variable.
static UNREALED_API bool RenameTimeline (UBlueprint *Blueprint, const FName OldVarName, const FName NewVarName)
Rename a Timeline.
static UNREALED_API void RenameVariableReferences (UBlueprint *Blueprint, UClass *VariableClass, const FName &OldVarName, const FName &NewVarName)
Looks through the specified blueprint for any references to the specified variable, and renames them accordingly.
static UNREALED_API void ReplaceAllActorRefrences (ULevelScriptBlueprint *InLevelScriptBlueprint, AActor *InOldActor, AActor *InNewActor)
Replace all references of the old actor with the new actor.
static UNREALED_API void ReplaceDeprecatedNodes (UBlueprint *Blueprint)
Replaces any deprecated nodes with new ones.
static UNREALED_API void ReplaceFunctionReferences (UBlueprint *Blueprint, const FName OldName, const FName NewName)
Replaces all function references in the specified blueprint.
static UNREALED_API void ReplaceInvalidBlueprintNameCharacters (FString &InBaseName)
Cleanses a name of invalid characters and replaces them with '_'.
static FString ReplaceInvalidBlueprintNameCharactersInline (FString InBaseName)
Util version of ReplaceInvalidBlueprintNameCharacters that performs the operation inline.
static UNREALED_API void ReplaceVariableReferences (UBlueprint *Blueprint, const FName OldName, const FName NewName)
Replaces all variable references in the specified blueprint.
static UNREALED_API void ReplaceVariableReferences (UBlueprint *Blueprint, const FProperty *OldVariable, const FProperty *NewVariable)
Replaces all variable references in the specified blueprint.
static UNREALED_API void SetAnimationGraphLayerGroup (UEdGraph *InGraph, const FText &InGroupName)
Sets the layer group on the anim graph.
static UNREALED_API void SetBlueprintFunctionOrMacroCategory (UEdGraph *Graph, const FText &NewCategory, bool bDontRecompile=false)
Sets the custom category on the function or macro.
static UNREALED_API void SetBlueprintOnlyEditableFlag (UBlueprint *Blueprint, const FName &VarName, const bool bNewBlueprintOnly)
Sets the Blueprint edit-only flag on the variable with the specified name.
static UNREALED_API void SetBlueprintPropertyReadOnlyFlag (UBlueprint *Blueprint, const FName &VarName, const bool bVariableReadOnly)
Sets the Blueprint read-only flag on the variable with the specified name.
static UNREALED_API void SetBlueprintVariableCategory (UBlueprint *Blueprint, const FName &VarName, const UStruct *InLocalVarScope, const FText &NewCategory, bool bDontRecompile=false)
Sets the custom category on the variable with the specified name.
static UNREALED_API void SetBlueprintVariableMetaData (UBlueprint *Blueprint, const FName &VarName, const UStruct *InLocalVarScope, const FName &MetaDataKey, const FString &MetaDataValue)
Sets a metadata key/value on the specified variable.
static UNREALED_API void SetBlueprintVariableRepNotifyFunc (UBlueprint *Blueprint, const FName &VarName, const FName &RepNotifyFunc)
Set RepNotify function of variable.
static UNREALED_API void SetInterpFlag (UBlueprint *Blueprint, const FName &VarName, const bool bInterp)
Sets the Interp flag on the variable with the specified name to make available to sequencer.
static UNREALED_API void SetVariableAdvancedDisplayFlag (UBlueprint *InBlueprint, const FName &InVarName, const bool bInIsAdvancedDisplay)
Sets the Advanced Display flag on the variable with the specified name.
static UNREALED_API void SetVariableDeprecatedFlag (UBlueprint *InBlueprint, const FName &InVarName, const bool bInIsDeprecated)
Sets the Deprecated flag on the variable with the specified name.
static UNREALED_API void SetVariableSaveGameFlag (UBlueprint *InBlueprint, const FName &InVarName, const bool bInIsSaveGame)
Sets the Save Game flag on the variable with the specified name.
static UNREALED_API void SetVariableTransientFlag (UBlueprint *InBlueprint, const FName &InVarName, const bool bInIsTransient)
Sets the Transient flag on the variable with the specified name.
static UNREALED_API bool ShouldOpenWithDataOnlyEditor (const UBlueprint *Blueprint)
static UNREALED_API bool StructHasGetTypeHash (const UScriptStruct *StructType)
Returns true if the StructType is native and has a GetTypeHash or is non-native and all of its member types are handled by UScriptStruct::GetStructTypeHash.
static UNREALED_API bool SupportsConstructionScript (const UBlueprint *Blueprint)
Do we support construction scripts.
static UNREALED_API void UpdateComponentTemplates (UBlueprint *Blueprint)
Handle stale components and ensure correct flags are set.
static UNREALED_API void UpdateDelegatesInBlueprint (UBlueprint *Blueprint)
Updates sources of delegates.
static UNREALED_API void UpdateEnumsInNodes (const TMap< UEnum *, UEnum * > &Structs, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated)
Search the blueprints looking for nodes that contain the given enumerations and replace the references.
static UNREALED_API void UpdateOutOfDateAnimBlueprints (UBlueprint *Blueprint)
Handle old AnimBlueprints (state machines in the wrong position, transition graphs with the wrong schema, etc...)
static UNREALED_API void UpdateOutOfDateCompositeNodes (UBlueprint *Blueprint)
Handle fixing up composite nodes within the blueprint.
static UNREALED_API void UpdateOutOfDateCompositeWithOuter (UBlueprint *Blueprint, UEdGraph *Outer)
Handle fixing up composite nodes within the specified Graph of Blueprint, and correctly setting the Outer.
static UNREALED_API void UpdateRootComponentReference (UBlueprint *Blueprint)
Ensures that the CDO root component reference is valid for Actor-based Blueprints.
static UNREALED_API void UpdateScriptStructsInNodes (const TMap< UScriptStruct *, UScriptStruct * > &Structs, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated)
Search the blueprints looking for nodes that contain the given script structs and replace the references.
static UNREALED_API void UpdateStalePinWatches (UBlueprint *Blueprint)
Handle stale pin watches.
static UNREALED_API void UpdateTransactionalFlags (UBlueprint *Blueprint)
Handle stale transactional flags on blueprints.
static UNREALED_API void ValidateBlueprintChildVariables (UBlueprint *InBlueprint, const FName InVariableName, TFunction< void(UBlueprint *InChildBP, const FName InVariableName, bool bValidatedVariable)> PostValidationCallback=TFunction< void(UBlueprint *, FName, bool)>())
Validate child blueprint component member variables, member variables, and timelines, and function graphs against the given variable name.
static UNREALED_API void ValidateEditorOnlyNodes (const UK2Node *Node, FCompilerResultsLog &MessageLog)
If the given node is from an editor only module but is placed in a runtime blueprint then place a warning in the message log that it will not be included in a cooked build.
static UNREALED_API void ValidatePinConnections (const UEdGraphNode *Node, FCompilerResultsLog &MessageLog)
Ensures the validity of each pin connection on the given node.
Data Fields
const FName bool bPreserveFunctions = false)
const FName TArray< UEdGraph * > & ChildGraphs
const FName & InterfaceClassName
TArray< UClass * > & NativizeDependenciesOut
UObject * NewCDO
Static Public Attributes
static UNREALED_API FOnReconstructAllNodes OnReconstructAllNodesEvent
static UNREALED_API FOnRefreshAllNodes OnRefreshAllNodesEvent
static UNREALED_API FOnRenameFunctionReferences OnRenameFunctionReferencesEvent
static UNREALED_API FOnRenameVariableReferences OnRenameVariableReferencesEvent
Static Protected Member Functions
static UNREALED_API bool CheckIfNodeConnectsToSelection (UEdGraphNode *InNode, const TSet< UEdGraphNode * > &InSelectionSet)
Checks if the passed node connects to the selection set.
static UNREALED_API void CleanNullGraphReferencesInArray (UBlueprint *Blueprint, TArray< UEdGraph * > &GraphArray)
static UNREALED_API void CleanNullGraphReferencesRecursive (UEdGraph *Graph)
static UNREALED_API void GetLoadedChildBlueprints (UBlueprint *InBlueprint, TArray< UBlueprint * > &OutBlueprints)
Helper function to get all loaded Blueprints that are children (or using as an interface) the passed Blueprint.
static UNREALED_API TArray< UK2Node * > GetNodesForVariable (const FName &InVarName, const UBlueprint *InBlueprint, const UStruct *InScope=nullptr)
Returns an array of variables Get/Set nodes of the current variable.
static UNREALED_API bool IsObjectADebugCandidate (AActor *InActorObject, UBlueprint *InBlueprint, bool bInDisallowDerivedBlueprints)
Checks that the actor type matches the blueprint type (or optionally is BASED on the same type.
static UNREALED_API void PostSetupObjectPinType (UBlueprint *InBlueprint, FBPVariableDescription &InOutVarDesc)
Validates flags and settings on object pins, keeping them from being given default values and from being in invalid states.
static UNREALED_API bool ValidateAllComponentMemberVariables (UBlueprint *InBlueprint, UBlueprint *InParentBlueprint, const FName &InVariableName)
Validate child blueprint component member variables against the given variable name.
static UNREALED_API bool ValidateAllFunctionGraphs (UBlueprint *InBlueprint, UBlueprint *InParentBlueprint, const FName &InVariableName)
Validates all function graphs of the passed blueprint against the given variable name.
static UNREALED_API bool ValidateAllMemberVariables (UBlueprint *InBlueprint, UBlueprint *InParentBlueprint, const FName InVariableName)
Validate child blueprint member variables against the given variable name.
static UNREALED_API bool ValidateAllTimelines (UBlueprint *InBlueprint, UBlueprint *InParentBlueprint, const FName &InVariableName)
Validates all timelines of the passed blueprint against the given variable name.
static UNREALED_API bool VerifyUserWantsRepNotifyVariableNameChanged (const FName &InVarName, const FName &InFuncName)
Helper function to warn user of the results of changing a RepNotify variable name by displaying a suppressible dialog.
static UNREALED_API bool VerifyUserWantsVariableTypeChanged (const FName &InVarName)
Helper function to warn user of the results of changing var type by displaying a suppressible dialog.
Detailed Description
Definition at line 140 of file BlueprintEditorUtils.h.
Member Typedef Documentation
FOnNodeFoundOrUpdated
using FBlueprintEditorUtils::FOnNodeFoundOrUpdated = TFunction<void(UBlueprint*, UK2Node*)>
Callback for when a node has been found.
Definition at line 1777 of file BlueprintEditorUtils.h.
Member Enumeration Documentation
EPropertyReadableState
enum class FBlueprintEditorUtils::EPropertyReadableState : uint8 strong
Enumeration of whether a property is readable or if not, why.
Enumerator
Readable
Private
NotBlueprintVisible
Definition at line 1384 of file BlueprintEditorUtils.h.
EPropertyWritableState
enum class FBlueprintEditorUtils::EPropertyWritableState : uint8 strong
Enumeration of whether a property is writable or if not, why.
Enumerator
Writable
Private
NotBlueprintVisible
BlueprintReadOnly
Definition at line 1372 of file BlueprintEditorUtils.h.
Member Function Documentation
AddDomainSpecificGraph()
UNREALED_API void FBlueprintEditorUtils::AddDomainSpecificGraph (UBlueprint * Blueprint, class UEdGraph * Graph) static
Adds a domain-specific graph to this blueprint.
AddFunctionGraph()
template<typename SignatureType> void FBlueprintEditorUtils::AddFunctionGraph (UBlueprint * Blueprint, class UEdGraph * Graph, bool bIsUserCreated, SignatureType * SignatureFromObject) inline static
Adds a function graph to this blueprint.
If bIsUserCreated is true, the entry/exit nodes will be editable. SignatureFromObject is used to find signature for entry/exit nodes if using an existing signature. The template argument SignatureType should be UClass or UFunction.
Definition at line 389 of file BlueprintEditorUtils.h.
References CreateFunctionGraph(), MarkBlueprintAsStructurallyModified(), and ValidateBlueprintChildVariables().
AddInterfaceGraph()
UNREALED_API void FBlueprintEditorUtils::AddInterfaceGraph (UBlueprint * Blueprint, class UEdGraph * Graph, UClass * InterfaceClass) static
Adds an interface graph to this blueprint.
AddLocalVariable()
UNREALED_API bool FBlueprintEditorUtils::AddLocalVariable (UBlueprint * Blueprint, UEdGraph * InTargetGraph, const FName InNewVarName, const FEdGraphPinType & InNewVarType, const FString & DefaultValue = FString()) static
Adds a local variable to the function graph.
It cannot mask a member variable or a variable in any superclass.
Parameters
NewVarName Name of the new variable.
NewVarType Type of the new variable.
DefaultValue Default value stored as string
Returns
true if it succeeds, false if it fails.
AddMacroGraph()
UNREALED_API void FBlueprintEditorUtils::AddMacroGraph (UBlueprint * Blueprint, class UEdGraph * Graph, bool bIsUserCreated, UClass * SignatureFromClass) static
Adds a macro graph to this blueprint.
If bIsUserCreated is true, the entry/exit nodes will be editable. SignatureFromClass is used to find signature for entry/exit nodes if using an existing signature.
AddMemberVariable()
UNREALED_API bool FBlueprintEditorUtils::AddMemberVariable (UBlueprint * Blueprint, const FName & NewVarName, const FEdGraphPinType & NewVarType, const FString & DefaultValue = FString()) static
Adds a member variable to the blueprint.
It cannot mask a variable in any superclass.
Parameters
NewVarName Name of the new variable.
NewVarType Type of the new variable.
DefaultValue Default value stored as string
Returns
true if it succeeds, false if it fails.
AddNewTimeline()
UNREALED_API class UTimelineTemplate * FBlueprintEditorUtils::AddNewTimeline (UBlueprint * Blueprint, const FName & TimelineVarName) static
Add a new timeline with the supplied name to the blueprint.
AddUbergraphPage()
UNREALED_API void FBlueprintEditorUtils::AddUbergraphPage (UBlueprint * Blueprint, class UEdGraph * Graph) static
Adds an ubergraph page to this blueprint.
AnalyticsTrackNewNode()
UNREALED_API void FBlueprintEditorUtils::AnalyticsTrackNewNode (UEdGraphNode * NewNode) static
Records node create events for analytics.
BuildComponentInstancingData()
UNREALED_API void FBlueprintEditorUtils::BuildComponentInstancingData (UActorComponent * ComponentTemplate, FBlueprintCookedComponentInstancingData & OutData, bool bUseTemplateArchetype = false) static
Generate component instancing data (for cooked builds).
Parameters
ComponentTemplate The component template to generate instancing data for.
OutData The generated component instancing data.
bUseTemplateArchetype Whether or not to use the template archetype or the template CDO for delta serialization (default is to use the template CDO).
Returns
TRUE if component instancing data was built, FALSE otherwise.
BulkRemoveMemberVariables()
UNREALED_API void FBlueprintEditorUtils::BulkRemoveMemberVariables (UBlueprint * Blueprint, const TArray< FName > & VarNames) static
Removes member variables if they were declared in this blueprint and not in a base class.
Parameters
VarNames Names of the variable to be removed.
CanClassGenerateEvents()
UNREALED_API bool FBlueprintEditorUtils::CanClassGenerateEvents (const UClass * Class) static
Checks for events in the argument class.
Parameters
Class The class to check for events.
References Class.
CanCreateChildBlueprint()
UNREALED_API bool FBlueprintEditorUtils::CanCreateChildBlueprint (const UBlueprint * BP) static
Returns true if this blueprint can have a child class created based on it.
ChangeLocalVariableType()
UNREALED_API void FBlueprintEditorUtils::ChangeLocalVariableType (UBlueprint * InBlueprint, const UStruct * InScope, const FName InVariableName, const FEdGraphPinType & InNewPinType) static
Changes the type of a local variable.
Parameters
InBlueprint Blueprint to search for the local variable
InScope Local variable's scope
InVariableName Name of the local variable to change the type of
InNewPinType The pin type to change the local variable type to
ChangeMemberVariableType()
UNREALED_API void FBlueprintEditorUtils::ChangeMemberVariableType (UBlueprint * Blueprint, const FName VariableName, const FEdGraphPinType & NewPinType) static
Changes the type of a member variable.
CheckIfGraphHasLatentFunctions()
UNREALED_API bool FBlueprintEditorUtils::CheckIfGraphHasLatentFunctions (UEdGraph * InGraph) static
Checks if a graph (or any sub-graphs or referenced graphs) have latent function nodes.
CheckIfNodeConnectsToSelection()
UNREALED_API bool FBlueprintEditorUtils::CheckIfNodeConnectsToSelection (UEdGraphNode * InNode, const TSet< UEdGraphNode * > & InSelectionSet) static protected
Checks if the passed node connects to the selection set.
Parameters
InNode The node to check
InSelectionSet The selection set to check for a connection to
Returns
Returns TRUE if the node does connect to the selection set
CheckIfSelectionIsCycling()
UNREALED_API bool FBlueprintEditorUtils::CheckIfSelectionIsCycling (const TSet< UEdGraphNode * > & InSelectionSet, FCompilerResultsLog & InMessageLog) static
CleanNullGraphReferencesInArray()
UNREALED_API void FBlueprintEditorUtils::CleanNullGraphReferencesInArray (UBlueprint * Blueprint, TArray< UEdGraph * > & GraphArray) static protected
CleanNullGraphReferencesRecursive()
UNREALED_API void FBlueprintEditorUtils::CleanNullGraphReferencesRecursive (UEdGraph * Graph) static protected
ClearMacroCosmeticInfoCache()
UNREALED_API void FBlueprintEditorUtils::ClearMacroCosmeticInfoCache (UBlueprint * Blueprint) static
Updates the cosmetic information cache for macros.
References ClearMacroCosmeticInfoCache().
Referenced by ClearMacroCosmeticInfoCache().
ConformAllowDeletionFlag()
UNREALED_API void FBlueprintEditorUtils::ConformAllowDeletionFlag (UBlueprint * Blueprint) static
Makes sure that all function graphs are flagged as bAllowDeletion=true, except for construction script and animgraph:
References ConformAllowDeletionFlag().
Referenced by ConformAllowDeletionFlag().
ConformCallsToParentFunctions()
UNREALED_API void FBlueprintEditorUtils::ConformCallsToParentFunctions (UBlueprint * Blueprint) static
Makes sure that calls to parent functions are valid, and removes them if not.
ConformDelegateSignatureGraphs()
UNREALED_API void FBlueprintEditorUtils::ConformDelegateSignatureGraphs (UBlueprint * Blueprint) static
Makes sure that all delegate graphs have a corresponding variable declaration, removing the graph if not.
References ConformDelegateSignatureGraphs().
Referenced by ConformDelegateSignatureGraphs().
ConformImplementedEvents()
UNREALED_API void FBlueprintEditorUtils::ConformImplementedEvents (UBlueprint * Blueprint) static
Makes sure that all events we handle exist, and replace with custom events if not.
ConformImplementedInterfaces()
UNREALED_API void FBlueprintEditorUtils::ConformImplementedInterfaces (UBlueprint * Blueprint) static
Makes sure that all graphs for all interfaces we implement exist, and add if not.
References ConformImplementedInterfaces().
Referenced by ConformImplementedInterfaces().
ConstructBlueprintInterfaceClassPicker()
UNREALED_API TSharedRef< SWidget > FBlueprintEditorUtils::ConstructBlueprintInterfaceClassPicker (const TArray< UBlueprint * > & Blueprints, const FOnClassPicked & OnPicked) static
Constructs a class picker widget for adding interfaces for the specified blueprint(s)
ConstructBlueprintParentClassPicker()
UNREALED_API TSharedRef< SWidget > FBlueprintEditorUtils::ConstructBlueprintParentClassPicker (const TArray< UBlueprint * > & Blueprints, const FOnClassPicked & OnPicked) static
Constructs a class picker widget for reparenting the specified blueprint(s)
CreateFunctionGraph()
template<typename SignatureType> void FBlueprintEditorUtils::CreateFunctionGraph (UBlueprint * Blueprint, class UEdGraph * Graph, bool bIsUserCreated, SignatureType * SignatureFromObject) inline static
Creates a function graph, but does not add it to the blueprint.
If bIsUserCreated is true, the entry/exit nodes will be editable. SignatureFromObject is used to find signature for entry/exit nodes if using an existing signature. The template argument SignatureType should be UClass or UFunction.
Definition at line 344 of file BlueprintEditorUtils.h.
References Cast(), CreateFunctionGraph(), FUNC_BlueprintCallable, FUNC_BlueprintEvent, FUNC_Const, FUNC_Public, FUNC_Static, GetGraphFunctionMetaData(), IsEditorUtilityBlueprint(), and MetaData.
Referenced by AddFunctionGraph(), and CreateFunctionGraph().
CreateMatchingFunction()
UNREALED_API void FBlueprintEditorUtils::CreateMatchingFunction (UK2Node_CallFunction * InNode, TSubclassOf< class UEdGraphSchema > InSchemaClass) static
Creates a new function graph with a signature that matches InNode.
Parameters
InNode Node to copy signature from
InSchemaClass The schema for the new graph
References CreateMatchingFunction().
Referenced by CreateMatchingFunction().
CreateNewGraph()
UNREALED_API class UEdGraph * FBlueprintEditorUtils::CreateNewGraph (UObject * ParentScope, const FName & GraphName, TSubclassOf< class UEdGraph > GraphClass, TSubclassOf< class UEdGraphSchema > SchemaClass) static
Creates a new empty graph.
Parameters
ParentScope The outer of the new graph (typically a blueprint).
GraphName Name of the graph to add.
SchemaClass Schema to use for the new graph.
Returns
null if it fails, else.
References CreateNewGraph().
Referenced by CreateNewGraph().
DECLARE_MULTICAST_DELEGATE_FourParams() [1/2]
FBlueprintEditorUtils::DECLARE_MULTICAST_DELEGATE_FourParams (FOnRenameFunctionReferences , UBlueprint * , UClass * , const FName & , const FName &)
Event fired after RenameFunctionReferences is called.
DECLARE_MULTICAST_DELEGATE_FourParams() [2/2]
FBlueprintEditorUtils::DECLARE_MULTICAST_DELEGATE_FourParams (FOnRenameVariableReferences , UBlueprint * , UClass * , const FName & , const FName &)
Event fired after RenameVariableReferences is called.
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
FBlueprintEditorUtils::DECLARE_MULTICAST_DELEGATE_OneParam (FOnReconstructAllNodes , UBlueprint *)
Event fired after ReconstructAllNodes is called.
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
FBlueprintEditorUtils::DECLARE_MULTICAST_DELEGATE_OneParam (FOnRefreshAllNodes , UBlueprint *)
Event fired after RefreshAllNodes is called.
DoesBlueprintContainField()
UNREALED_API bool FBlueprintEditorUtils::DoesBlueprintContainField (const UBlueprint * Blueprint, UField * TestField) static
See if a field (property, function etc) is part of the blueprint chain, or.
DoesBlueprintDeriveFrom()
UNREALED_API bool FBlueprintEditorUtils::DoesBlueprintDeriveFrom (const UBlueprint * Blueprint, UClass * TestClass) static
See if a class is the one generated by this blueprint.
DoesSupportComponents()
UNREALED_API bool FBlueprintEditorUtils::DoesSupportComponents (UBlueprint const * Blueprint) static
Returns whether or not the blueprint supports components.
DoesSupportDefaults()
UNREALED_API bool FBlueprintEditorUtils::DoesSupportDefaults (UBlueprint const * Blueprint) static
Returns whether or not the blueprint supports default values (IE has a CDO)
DoesSupportEventGraphs()
UNREALED_API bool FBlueprintEditorUtils::DoesSupportEventGraphs (const UBlueprint * Blueprint) static
Returns whether or not the blueprint supports event graphs.
DoesSupportImplementingInterfaces()
UNREALED_API bool FBlueprintEditorUtils::DoesSupportImplementingInterfaces (const UBlueprint * Blueprint) static
Returns whether or not the blueprint supports implementing interfaces.
DoesSupportLocalVariables()
UNREALED_API bool FBlueprintEditorUtils::DoesSupportLocalVariables (UEdGraph const * InGraph) static
Returns whether or not the blueprint graph supports local variables.
Referenced by SRigVMActionMenu::TryInsertPromoteToVariable().
DoesSupportOverridingFunctions()
UNREALED_API bool FBlueprintEditorUtils::DoesSupportOverridingFunctions (const UBlueprint * Blueprint) static
Returns whether or not the blueprint supports overriding functions.
DoesSupportTimelines()
UNREALED_API bool FBlueprintEditorUtils::DoesSupportTimelines (const UBlueprint * Blueprint) static
Returns whether or not the blueprint supports timelines.
DuplicateMemberVariable()
UNREALED_API FName FBlueprintEditorUtils::DuplicateMemberVariable (UBlueprint * InFromBlueprint, UBlueprint * InToBlueprint, FName InVariableToDuplicate) static
Duplicates a variable from one Blueprint to another blueprint.
Parameters
InFromBlueprint The Blueprint the variable can be found in
InToBlueprint The Blueprint the new variable should be added to (can be the same blueprint)
InVariableToDuplicate Variable name to be found and duplicated
Returns
Returns the name of the new variable or NAME_None if failed to duplicate
DuplicateVariable()
UNREALED_API FName FBlueprintEditorUtils::DuplicateVariable (UBlueprint * InBlueprint, const UStruct * InScope, FName InVariableToDuplicate) static
Duplicates a variable given its name and Blueprint.
Parameters
InBlueprint The Blueprint the variable can be found in @paramInScope Local variable's scope
InVariableToDuplicate Variable name to be found and duplicated
Returns
Returns the name of the new variable or NAME_None if failed to duplicate
DuplicateVariableDescription()
UNREALED_API FBPVariableDescription FBlueprintEditorUtils::DuplicateVariableDescription (UBlueprint * InBlueprint, FBPVariableDescription & InVariableDescription) static
Internal function that deep copies a variable description.
Parameters
InBlueprint The blueprint to ensure a uniquely named variable in
InVariableToDuplicate Variable description to duplicate
Returns
Returns a copy of the passed in variable description.
EnsureCachedDependenciesUpToDate()
UNREALED_API void FBlueprintEditorUtils::EnsureCachedDependenciesUpToDate (UBlueprint * Blueprint) static
Ensures, that CachedDependencies in BP are up to date.
FindActorsThatReferenceActor()
UNREALED_API void FBlueprintEditorUtils::FindActorsThatReferenceActor (AActor * InActor, TArray< UClass * > & InClassesToIgnore, TArray< AActor * > & OutReferencingActors) static
Find how many actors reference the supplied actor.
Parameters
InActor The Actor to count references to.
InClassesToIgnore An array of class types to ignore, even if there is an instance of one that references the InActor
OutReferencingActors An array of actors found that reference the specified InActor
FindAndSetDebuggableBlueprintInstances()
UNREALED_API void FBlueprintEditorUtils::FindAndSetDebuggableBlueprintInstances () static
Searches the world for any blueprints that are open and do not have a debug instances set and sets one if possible.
It will favor a selected instance over a non selected one
FindBlueprintForGraph()
UNREALED_API UBlueprint * FBlueprintEditorUtils::FindBlueprintForGraph (const UEdGraph * Graph) static
Helper function to get the blueprint that ultimately owns a graph.
Parameters
InGraph Graph to find the blueprint for.
Returns
The corresponding blueprint or NULL.
References FindBlueprintForGraph().
Referenced by FindBlueprintForGraph().
FindBlueprintForGraphChecked()
UNREALED_API UBlueprint * FBlueprintEditorUtils::FindBlueprintForGraphChecked (const UEdGraph * Graph) static
Helper function to get the blueprint that ultimately owns a graph.
Cannot fail.
Parameters
InGraph Graph to find the blueprint for.
Returns
The corresponding blueprint or NULL.
References FindBlueprintForGraphChecked().
Referenced by FindBlueprintForGraphChecked().
FindBlueprintForNode()
UNREALED_API UBlueprint * FBlueprintEditorUtils::FindBlueprintForNode (const UEdGraphNode * Node) static
Helper function to get the blueprint that ultimately owns a node.
Parameters
InNode Node to find the blueprint for.
Returns
The corresponding blueprint or NULL.
References FindBlueprintForNode().
Referenced by FindBlueprintForNode().
FindBlueprintForNodeChecked()
UNREALED_API UBlueprint * FBlueprintEditorUtils::FindBlueprintForNodeChecked (const UEdGraphNode * Node) static
Helper function to get the blueprint that ultimately owns a node.
Cannot fail.
Parameters
InNode Node to find the blueprint for.
Returns
The corresponding blueprint or NULL.
References FindBlueprintForNodeChecked().
Referenced by FindBlueprintForNodeChecked().
FindCustomEventNode()
UNREALED_API UK2Node_Event * FBlueprintEditorUtils::FindCustomEventNode (const UBlueprint * Blueprint, FName const CustomName) static
Find the Custom Event if it already exists in the Blueprint.
FindDependentBlueprints()
UNREALED_API void FBlueprintEditorUtils::FindDependentBlueprints (UBlueprint * Blueprint, TArray< UBlueprint * > & DependentBlueprints) static
Searches the reference graph to find blueprints that are dependent on this BP.
FindEnumsInNodes()
UNREALED_API void FBlueprintEditorUtils::FindEnumsInNodes (const TSet< UEnum * > & UEnums, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated) static
Search the blueprints looking for nodes that contain the given enumerations.
FindEventGraph()
UNREALED_API UEdGraph * FBlueprintEditorUtils::FindEventGraph (const UBlueprint * Blueprint) static
Returns the event graph, if any.
FindFirstCompilerRelevantLinkedPin()
UNREALED_API UEdGraphPin * FBlueprintEditorUtils::FindFirstCompilerRelevantLinkedPin (UEdGraphPin * FromPin) static
Finds the first compiler-relevant (i.e.
non-ignorable) node from the given pin and returns the owned pin that's linked.
Parameters
FromPin The pin to start searching from.
Returns
The given pin if its owning node is compiler-relevant, or the first pin linked to the owning node at the matching "pass-through" pin that is owned by a compiler-relevant node. May be NULL if no compiler-relevant nodes can be found from the given pin.
FindFirstCompilerRelevantNode()
UNREALED_API UK2Node * FBlueprintEditorUtils::FindFirstCompilerRelevantNode (UEdGraphPin * FromPin) static
Finds the first compiler-relevant (i.e.
non-ignorable) node from the given pin.
Parameters
FromPin The pin to start searching from.
Returns
The given pin's owning node if compiler-relevant, or the first node linked to the owning node at the matching "pass-through" pin that is compiler-relevant. May be NULL if no compiler-relevant nodes can be found from the given pin.
FindFirstNativeClass() [1/2]
UNREALED_API const UClass * FBlueprintEditorUtils::FindFirstNativeClass (const UClass * Class) static
References Class.
FindFirstNativeClass() [2/2]
UNREALED_API UClass * FBlueprintEditorUtils::FindFirstNativeClass (UClass * Class) static
return find first native class in the hierarchy
References Class.
FindFunctionInImplementedInterfaces()
UNREALED_API UFunction * FBlueprintEditorUtils::FindFunctionInImplementedInterfaces (const UBlueprint * Blueprint, const FName & FunctionName, bool * bOutInvalidInterface = nullptr, bool bGetAllInterfaces = false) static
Return the first function from implemented interface with given name.
References FindFunctionInImplementedInterfaces().
Referenced by FindFunctionInImplementedInterfaces().
FindImplementedInterfaces()
UNREALED_API void FBlueprintEditorUtils::FindImplementedInterfaces (const UBlueprint * Blueprint, bool bGetAllInterfaces, TArray< UClass * > & ImplementedInterfaces) static
Build a list of all interface classes either implemented by this blueprint or through inheritance.
Parameters
Blueprint The blueprint to find interfaces for
bGetAllInterfaces If true, get all the implemented and inherited. False, just gets the interfaces implemented directly.
[out] ImplementedInterfaces The interfaces implemented by this blueprint
References FindImplementedInterfaces().
Referenced by FindImplementedInterfaces().
FindIndexOfGraphInParent()
UNREALED_API int32 FBlueprintEditorUtils::FindIndexOfGraphInParent (UEdGraph * Graph) static
Finds the index of the specified graph (function or macro) in the parent (if it is not reorderable, then we will return INDEX_NONE)
FindInterfaceFunctionGuid()
UNREALED_API FGuid FBlueprintEditorUtils::FindInterfaceFunctionGuid (const UFunction * Function, const UClass * InterfaceClass) static
Find the interface Guid for a function if it exists.
Parameters
Function The function to find a graph for.
InterfaceClass The interface's generated class.
References Function.
FindLocalVariable() [1/3]
UNREALED_API FBPVariableDescription * FBlueprintEditorUtils::FindLocalVariable (const UBlueprint * InBlueprint, const UEdGraph * InScopeGraph, const FName InVariableName, class UK2Node_FunctionEntry ** OutFunctionEntry = NULL) static
Returns a local variable.
Parameters
InBlueprint Blueprint to search for the local variable
InScopeGraph Local variable's graph
InVariableName Name of the variable to search for
OutFunctionEntry Optional output parameter. If not null, the found function entry is returned.
Returns
The local variable description
FindLocalVariable() [2/3]
UNREALED_API FBPVariableDescription * FBlueprintEditorUtils::FindLocalVariable (const UBlueprint * InBlueprint, const UStruct * InScope, const FName InVariableName, class UK2Node_FunctionEntry ** OutFunctionEntry = NULL) static
Returns a local variable.
Parameters
InBlueprint Blueprint to search for the local variable
InScope Local variable's scope
InVariableName Name of the variable to search for
OutFunctionEntry Optional output parameter. If not null, the found function entry is returned.
Returns
The local variable description
FindLocalVariable() [3/3]
UNREALED_API FBPVariableDescription * FBlueprintEditorUtils::FindLocalVariable (UBlueprint * InBlueprint, const UStruct * InScope, const FName InVariableName) static
Returns a local variable with the function entry it was found in.
Parameters
InBlueprint Blueprint to search for the local variable
InVariableName Name of the variable to search for
Returns
The local variable description
FindLocalVariableGuidByName() [1/2]
UNREALED_API FGuid FBlueprintEditorUtils::FindLocalVariableGuidByName (UBlueprint * InBlueprint, const UEdGraph * InScopeGraph, const FName InVariableName) static
Finds a local variable Guid using the variable's name.
Parameters
InBlueprint Blueprint to search for the local variable
InScopeGraph Local variable's graph
InVariableGuid Local variable's name to search for
Returns
The Guid associated with the local variable
FindLocalVariableGuidByName() [2/2]
UNREALED_API FGuid FBlueprintEditorUtils::FindLocalVariableGuidByName (UBlueprint * InBlueprint, const UStruct * InScope, const FName InVariableName) static
Finds a local variable Guid using the variable's name.
Parameters
InBlueprint Blueprint to search for the local variable
InScope Local variable's scope
InVariableGuid Local variable's name to search for
Returns
The Guid associated with the local variable
FindLocalVariableIndex()
UNREALED_API int32 FBlueprintEditorUtils::FindLocalVariableIndex (const UBlueprint * Blueprint, UStruct * VariableScope, const FName & InVariableName) static
Find the index of a local variable declared in this blueprint.
Returns INDEX_NONE if not found.
Parameters
VariableScope Struct of owning function.
InVariableName Name of the variable to find.
Returns
The index of the variable, or INDEX_NONE if it wasn't introduced in this blueprint.
FindLocalVariableNameByGuid()
UNREALED_API FName FBlueprintEditorUtils::FindLocalVariableNameByGuid (UBlueprint * InBlueprint, const FGuid & InVariableGuid) static
Finds a local variable name using the variable's Guid.
Parameters
InBlueprint Blueprint to search for the local variable
InVariableGuid Guid to identify the local variable with
Returns
Local variable's name
FindMemberVariableGuidByName()
UNREALED_API FGuid FBlueprintEditorUtils::FindMemberVariableGuidByName (UBlueprint * InBlueprint, const FName InVariableName) static
Finds a member variable Guid using the variable's name.
Parameters
InBlueprint Blueprint to search for the local variable
InVariableGuid Local variable's name to search for
Returns
The Guid associated with the local variable
FindMemberVariableNameByGuid()
UNREALED_API FName FBlueprintEditorUtils::FindMemberVariableNameByGuid (UBlueprint * InBlueprint, const FGuid & InVariableGuid) static
Finds a member variable name using the variable's Guid.
Parameters
InBlueprint Blueprint to search for the local variable
InVariableGuid Guid to identify the local variable with
Returns
Local variable's name
FindNewVariableIndex()
UNREALED_API int32 FBlueprintEditorUtils::FindNewVariableIndex (const UBlueprint * Blueprint, const FName & InName) static
Find the index of a variable first declared in this blueprint.
Returns INDEX_NONE if not found.
Parameters
InName Name of the variable to find.
Returns
The index of the variable, or INDEX_NONE if it wasn't introduced in this blueprint.
References InName.
FindNewVariableIndexAndBlueprint()
UNREALED_API int32 FBlueprintEditorUtils::FindNewVariableIndexAndBlueprint (UBlueprint * InBlueprint, FName InName, UBlueprint *& OutFoundBlueprint) static
Find the index of a variable first declared in this blueprint or its parents.
Returns INDEX_NONE if not found.
Parameters
InBlueprint Blueprint to begin search in (will search parents as well)
InName Name of the variable to find.
OutFoundBlueprint Blueprint where the variable was eventually found
Returns
The index of the variable, or INDEX_NONE if it wasn't introduced in this blueprint.
References InName.
FindNodeForTimeline()
UNREALED_API class UK2Node_Timeline * FBlueprintEditorUtils::FindNodeForTimeline (UBlueprint * Blueprint, UTimelineTemplate * Timeline) static
Find the node that owns the supplied timeline template.
FindOrCreateFunctionResultNode()
UNREALED_API class UK2Node_FunctionResult * FBlueprintEditorUtils::FindOrCreateFunctionResultNode (class UK2Node_EditablePinBase * InFunctionEntryNode) static
Creates a function result node or returns the current one if one exists.
Parameters
InFunctionEntryNode The function entry node to spawn the result node for
Returns
Spawned result node
FindOverrideForFunction()
UNREALED_API UK2Node_Event * FBlueprintEditorUtils::FindOverrideForFunction (const UBlueprint * Blueprint, const UClass * SignatureClass, FName SignatureName) static
Look to see if an event already exists to override a particular function.
FindReferencesToActorFromLevelScript()
UNREALED_API bool FBlueprintEditorUtils::FindReferencesToActorFromLevelScript (ULevelScriptBlueprint * LevelScriptBlueprint, AActor * InActor, TArray< UK2Node * > & ReferencedToActors) static
Find how many nodes reference the supplied actor.
FindScopeGraph()
UNREALED_API UEdGraph * FBlueprintEditorUtils::FindScopeGraph (const UBlueprint * InBlueprint, const UStruct * InScope) static
Finds the scope's associated graph for local variables (or any passed UFunction)
Parameters
InBlueprint The Blueprint the local variable can be found in
InScope Local variable's scope
FindScriptStructsInNodes()
UNREALED_API void FBlueprintEditorUtils::FindScriptStructsInNodes (const TSet< UScriptStruct * > & Structs, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated) static
Search the blueprints looking for nodes that contain the given script structs.
FindSCS_Node()
UNREALED_API USCS_Node * FBlueprintEditorUtils::FindSCS_Node (const UBlueprint * Blueprint, const FName InName) static
Finds an SCSNode by variable name.
Parameters
InName Name of the variable to find.
Returns
The SCS Node that corresponds to the variable name or null if one is not found
References InName.
FindTimelineIndex()
UNREALED_API int32 FBlueprintEditorUtils::FindTimelineIndex (const UBlueprint * Blueprint, const FName & InName) static
Find the index of a timeline first declared in this blueprint.
Returns INDEX_NONE if not found.
Parameters
InName Name of the variable to find.
Returns
The index of the variable, or INDEX_NONE if it wasn't introduced in this blueprint.
References InName.
FindUCSComponentTemplate()
UNREALED_API UActorComponent * FBlueprintEditorUtils::FindUCSComponentTemplate (const FComponentKey & ComponentKey, const FName & TemplateName) static
Attempts to match up the FComponentKey with a ComponentTemplate from the Blueprint's UCS.
Will fall back to try matching the given template name if the key cannot be used.
References TemplateName.
FindUniqueCustomEventName()
UNREALED_API FName FBlueprintEditorUtils::FindUniqueCustomEventName (const UBlueprint * Blueprint) static
Finds a unique and valid name for a custom event.
FindUniqueKismetName()
UNREALED_API FName FBlueprintEditorUtils::FindUniqueKismetName (const UBlueprint * InBlueprint, const FString & InBaseName, UStruct * InScope = NULL) static
Finds a unique name with a base of the passed in string, appending numbers as needed.
Parameters
InBlueprint The blueprint the kismet object's name needs to be unique in
InBaseName The base name to use
InScope Scope, if any, of the unique kismet name to generate, used for locals
Returns
A unique name that will not conflict in the Blueprint
References FindUniqueKismetName().
Referenced by FindUniqueKismetName().
FindUniqueTimelineName()
UNREALED_API FName FBlueprintEditorUtils::FindUniqueTimelineName (const UBlueprint * Blueprint) static
Finds a name for a timeline that is not already in use.
FindUserConstructionScript()
UNREALED_API UEdGraph * FBlueprintEditorUtils::FindUserConstructionScript (const UBlueprint * Blueprint) static
Returns the user construction script, if any.
FixLevelScriptActorBindings()
UNREALED_API void FBlueprintEditorUtils::FixLevelScriptActorBindings (ALevelScriptActor * LevelScriptActor, const class ULevelScriptBlueprint * ScriptBlueprint) static
Called after a level script blueprint is changed and nodes should be refreshed for it's new level script actor.
Parameters
LevelScriptActor The newly-created level script actor that should be (re-)bound to
ScriptBlueprint The level scripting blueprint that contains the bound events to try and bind delegates to this actor for
FixupVariableDescription()
UNREALED_API void FBlueprintEditorUtils::FixupVariableDescription (UBlueprint * Blueprint, FBPVariableDescription & VarDesc) static
Check blueprint variable metadata keys/values for validity and make adjustments if needed.
GatherDependencies()
UNREALED_API void FBlueprintEditorUtils::GatherDependencies (const UBlueprint * Blueprint, TSet< TWeakObjectPtr< UBlueprint > > & OutDependencies, TSet< TWeakObjectPtr< UStruct > > & OutUDSDependencies) static
Gather all bps that Blueprint depends on.
GenerateUniqueGraphName()
UNREALED_API FName FBlueprintEditorUtils::GenerateUniqueGraphName (UObject *const InOuter, FString const & ProposedName) static
Generates a unique graph name for the supplied blueprint (guaranteed to not cause a naming conflict at the time of the call).
Parameters
InOuter The blueprint/object you want a unique graph name for.
ProposedName The name you want to give the graph (the result will be some permutation of this string).
Returns
A unique name intended for a new graph.
References InOuter.
GetActorReferenceMap()
UNREALED_API void FBlueprintEditorUtils::GetActorReferenceMap (UWorld * InWorld, TArray< UClass * > & InClassesToIgnore, TMap< AActor *, TArray< AActor * > > & OutReferencingActors) static
Go through the world and build a map of all actors that are referenced by other actors.
Parameters
InWorld The world to scan for Actors.
InClassesToIgnore An array of class types to ignore, even if there is an instance of one that references another Actor
OutReferencingActors A map of Actors that are referenced by a list of other Actors.
GetAllGraphNames()
UNREALED_API void FBlueprintEditorUtils::GetAllGraphNames (const UBlueprint * Blueprint, TSet< FName > & GraphNames) static
Gets the names of all graphs in the Blueprint.
Parameters
[in,out] GraphNames The graph names will be appended to this array.
GetAllNodesOfClass()
template<class T> void FBlueprintEditorUtils::GetAllNodesOfClass (const UBlueprint * Blueprint, TArray< T * > & OutNodes) inline static
Returns all nodes in all graphs of the specified class.
Definition at line 495 of file BlueprintEditorUtils.h.
References TArray< InElementType, InAllocatorType >::Append(), check, and TArray< InElementType, InAllocatorType >::Num().
Referenced by GetNodeByGUID().
GetAllNodesOfClassEx()
template<class MinNodeType, class ArrayClassType> void FBlueprintEditorUtils::GetAllNodesOfClassEx (const UBlueprint * Blueprint, TArray< ArrayClassType * > & OutNodes) inline static
Returns all nodes in all graphs of at least the minimum node type.
Definition at line 510 of file BlueprintEditorUtils.h.
References check.
GetAnimGraphRoot()
UNREALED_API UAnimGraphNode_Root * FBlueprintEditorUtils::GetAnimGraphRoot (UEdGraph * InGraph) static
Helper function to grab the root node from an anim graph.
Asserts if anything other than 1 node is found in an anim graph.
Parameters
InGraph The graph to check
Returns
the one and only root, if this is an anim graph, or null otherwise
GetBlueprintTypeDescription()
UNREALED_API FString FBlueprintEditorUtils::GetBlueprintTypeDescription (const UBlueprint * Blueprint) static
GetBlueprintVariableCategory()
UNREALED_API FText FBlueprintEditorUtils::GetBlueprintVariableCategory (UBlueprint * Blueprint, const FName & VarName, const UStruct * InLocalVarScope) static
Gets the custom category on the variable with the specified name.
Parameters
VarName Name of the variable
InLocalVarScope Local variable's scope, if looking to modify a local variable
Returns
The custom category (None indicates the name will be the same as the blueprint)
GetBlueprintVariableMetaData()
UNREALED_API bool FBlueprintEditorUtils::GetBlueprintVariableMetaData (const UBlueprint * Blueprint, const FName & VarName, const UStruct * InLocalVarScope, const FName & MetaDataKey, FString & OutMetaDataValue) static
Get a metadata key/value on the specified variable, or timeline if it exists, returning false if it does not exist.
Parameters
Blueprint The Blueprint to find the variable in
VarName Name of the variable
InLocalVarScope Local variable's scope, if looking to modify a local variable
MetaDataKey Key name for the metadata to change
OutMetaDataValue Value of the metadata
Returns
TRUE if finding the metadata was successful
GetBlueprintVariablePropertyFlags()
UNREALED_API uint64 * FBlueprintEditorUtils::GetBlueprintVariablePropertyFlags (UBlueprint * Blueprint, const FName & VarName) static
Gets pointer to PropertyFlags of variable.
GetBlueprintVariableRepNotifyFunc()
UNREALED_API FName FBlueprintEditorUtils::GetBlueprintVariableRepNotifyFunc (UBlueprint * Blueprint, const FName & VarName) static
Get RepNotify function name of variable.
GetChildrenOfBlueprint()
UNREALED_API int32 FBlueprintEditorUtils::GetChildrenOfBlueprint (UBlueprint * InBlueprint, TArray< FAssetData > & OutChildren, bool bInRecursive = true) static
Gets AssetData for all child classes of a given blueprint.
Parameters
InBlueprint Taget Blueprint
OutChildren AssetData representing the child blueprints
bInRecursive if true, will return classes derived from child classes as well
Returns
Number of child blueprints found
GetClassNameWithoutSuffix()
UNREALED_API FString FBlueprintEditorUtils::GetClassNameWithoutSuffix (const UClass * Class) static
Returns a class name for the specified class that has no automatic suffixes, but is otherwise unmodified.
Class can be nullptr.
References Class.
GetClassVariableList()
UNREALED_API void FBlueprintEditorUtils::GetClassVariableList (const UBlueprint * Blueprint, TSet< FName > & VisibleVariables, bool bIncludePrivateVars = false) static
Gets the visible class variable list.
This includes both variables introduced here and in all superclasses.
Parameters
[in,out] VisibleVariables The visible variables will be appended to this array.
GetCompilerRelevantNodeLinks()
UNREALED_API void FBlueprintEditorUtils::GetCompilerRelevantNodeLinks (UEdGraphPin * FromPin, FCompilerRelevantNodeLinkArray & OutNodeLinks) static
Gets the compiler-relevant (i.e.
non-ignorable) node links from the given pin.
Parameters
FromPin The pin to start searching from.
OutNodeLinks Will contain the given pin + owning node if compiler-relevant, or all nodes linked to the owning node at the matching "pass-through" pin that are compiler-relevant. Empty if no compiler-relevant node links can be found from the given pin.
GetCosmeticInfoForMacro()
UNREALED_API FBlueprintMacroCosmeticInfo FBlueprintEditorUtils::GetCosmeticInfoForMacro (UEdGraph * MacroGraph) static
Returns the cosmetic information for the specified macro graph, caching it if necessary.
References GetCosmeticInfoForMacro().
Referenced by GetCosmeticInfoForMacro().
GetDelegateNameList()
UNREALED_API void FBlueprintEditorUtils::GetDelegateNameList (const UBlueprint * Blueprint, TSet< FName > & DelegatesNames) static
Gets a list of delegates names in the blueprint, based on the skeleton class.
Parameters
Blueprint The blueprint to check
[in,out] DelegatesNames List of function names currently in use
GetDelegateSignatureGraphByName()
UNREALED_API UEdGraph * FBlueprintEditorUtils::GetDelegateSignatureGraphByName (UBlueprint * Blueprint, FName DelegateName) static
Get a graph for delegate signature with given name, from given blueprint.
Parameters
Blueprint Blueprint owning the delegate signature graph
DelegateName Name of delegate.
Returns
Graph of delegate-signature function.
GetDependentBlueprints()
UNREALED_API void FBlueprintEditorUtils::GetDependentBlueprints (UBlueprint * Blueprint, TArray< UBlueprint * > & DependentBlueprints) static
Returns cached a list of loaded Blueprints that are dependent on the given Blueprint.
GetDeprecatedMemberMenuItemName()
UNREALED_API FText FBlueprintEditorUtils::GetDeprecatedMemberMenuItemName (const FText & MemberName) static
Returns a formatted menu item label for a deprecated variable or function member with the given name.
Parameters
MemberName (Required) User-facing name of the deprecated variable or function.
GetDeprecatedMemberUsageNodeWarning()
UNREALED_API FText FBlueprintEditorUtils::GetDeprecatedMemberUsageNodeWarning (const FText & MemberName, const FText & DetailedMessage) static
Returns a formatted warning message regarding usage of a deprecated variable or function member with the given name.
Parameters
MemberName (Required) User-facing name of the deprecated variable or function.
DetailedMessage (Optional) Instructional text or other details from the owner. If empty, a default message will be used.
GetDeprecatedMessageType()
UNREALED_API EEdGraphNodeDeprecationMessageType FBlueprintEditorUtils::GetDeprecatedMessageType (const FString & TypeString) static
Returns the severity of a deprecation warning by parsing a string loaded from metadata like DeprecatedFunction="Note".
Parameters
TypeString (Required) String to parse for a message type
GetEntryAndResultNodes()
UNREALED_API void FBlueprintEditorUtils::GetEntryAndResultNodes (const UEdGraph * InGraph, TWeakObjectPtr< class UK2Node_EditablePinBase > & OutEntryNode, TWeakObjectPtr< class UK2Node_EditablePinBase > & OutResultNode) static
Finds the entry and result nodes for a function or macro graph.
Parameters
InGraph The graph to search through
OutEntryNode The found entry node for the graph
OutResultNode The found result node for the graph
GetEntryNode()
UNREALED_API class UK2Node_EditablePinBase * FBlueprintEditorUtils::GetEntryNode (const UEdGraph * InGraph) static
Finds the entry node for a function or macro graph.
Parameters
InGraph The graph to search through
Returns
The found entry node for the graph
GetFriendlyClassDisplayName()
UNREALED_API FText FBlueprintEditorUtils::GetFriendlyClassDisplayName (const UClass * Class) static
Returns a friendly class display name for the specified class (removing things like _C from the end, may localize the class name).
Class can be nullptr.
References Class.
GetFunctionGuidFromClassByFieldName()
UNREALED_API bool FBlueprintEditorUtils::GetFunctionGuidFromClassByFieldName (const UClass * InClass, const FName FunctionName, FGuid & FunctionGuid) static
GetFunctionNameFromClassByGuid()
UNREALED_API FName FBlueprintEditorUtils::GetFunctionNameFromClassByGuid (const UClass * InClass, const FGuid FunctionGuid) static
GetFunctionNameList()
UNREALED_API void FBlueprintEditorUtils::GetFunctionNameList (const UBlueprint * Blueprint, TSet< FName > & FunctionNames) static
Gets a list of function names currently in use in the blueprint, based on the skeleton class.
Parameters
Blueprint The blueprint to check
[in,out] FunctionNames List of function names currently in use
GetGraphDescription()
UNREALED_API FText FBlueprintEditorUtils::GetGraphDescription (const UEdGraph * InGraph) static
Returns the description of the graph from the metadata.
Parameters
InGraph Graph to find the description of
Returns
The description of the graph
GetGraphFunctionMetaData()
UNREALED_API FKismetUserDeclaredFunctionMetadata * FBlueprintEditorUtils::GetGraphFunctionMetaData (const UEdGraph * InGraph) static
Returns the function meta data block for the graph entry node.
Parameters
InGraph The graph to search through
Returns
If valid a pointer to the user declared function meta data structure otherwise nullptr.
Referenced by CreateFunctionGraph().
GetHiddenPinsForFunction()
UNREALED_API void FBlueprintEditorUtils::GetHiddenPinsForFunction (UEdGraph const * Graph, UFunction const * Function, TSet< FName > & HiddenPins, TSet< FName > * OutInternalPins = nullptr) static
Gets a list of pins that should hidden for a given function in a given graph.
Parameters
Graph The graph that you're looking to call the function from (some functions hide different pins depending on the graph they're in)
Function The function to consider
[out] HiddenPins Set of pins that should be hidden
[out] OutInternalPins Subset of hidden pins that are marked for internal use only rather than marked as hidden (optional)
References Function.
GetIconFromPin()
UNREALED_API const struct FSlateBrush * FBlueprintEditorUtils::GetIconFromPin (const FEdGraphPinType & PinType, bool bIsLarge = false) static
Determine the best icon to represent the given pin.
Parameters
PinType The pin get the icon for.
returns a brush that best represents the icon (or Kismet.VariableList.TypeIcon if none is available)
GetImplementingBlueprintsFunctionNameList()
UNREALED_API void FBlueprintEditorUtils::GetImplementingBlueprintsFunctionNameList (const UBlueprint * Blueprint, TSet< FName > & FunctionNames) static
Gets a list of function names in blueprints that implement the interface defined by the given blueprint.
Parameters
[in,out] Blueprint The interface blueprint to check.
[in,out] VariableNames The list of function names for implementing blueprints.
GetInterfaceFunction()
UNREALED_API UFunction * FBlueprintEditorUtils::GetInterfaceFunction (UBlueprint * Blueprint, const FName FuncName) static
Get the corresponding UFunction pointer to the name given on the blueprint.
Searches the given blueprints implemented interfaces first, and then looks in the parent.
Parameters
Blueprint The blueprint to consider
FuncName The name of the function to look for
Returns
Corresponding UFunction pointer to the name given; Nullptr if not part of any interfaces
References GetInterfaceFunction().
Referenced by GetInterfaceFunction().
GetInterfaceGraphs()
UNREALED_API void FBlueprintEditorUtils::GetInterfaceGraphs (UBlueprint * Blueprint, FTopLevelAssetPath InterfaceClassPathName, TArray< UEdGraph * > & ChildGraphs) static
Gets the graphs currently in the blueprint associated with the specified interface.
References ChildGraphs, and GetInterfaceGraphs().
Referenced by GetInterfaceGraphs().
GetLevelFromBlueprint()
UNREALED_API class ULevel * FBlueprintEditorUtils::GetLevelFromBlueprint (const UBlueprint * Blueprint) static
If a blueprint is directly tied to a level (level script and anonymous blueprints), this will return a pointer to that level.
Returns
The level, if any, tied to this blueprint
GetLoadedChildBlueprints()
UNREALED_API void FBlueprintEditorUtils::GetLoadedChildBlueprints (UBlueprint * InBlueprint, TArray< UBlueprint * > & OutBlueprints) static protected
Helper function to get all loaded Blueprints that are children (or using as an interface) the passed Blueprint.
Parameters
InBlueprint Blueprint to find children of
OutBlueprints Filled out with child Blueprints
GetLocalVariablesOfType()
UNREALED_API void FBlueprintEditorUtils::GetLocalVariablesOfType (const UEdGraph * Graph, const FEdGraphPinType & Type, TArray< FName > & OutVars) static
Gets local variables of specified type.
Parameters
FEdGraphPinType Type of variables to look for
[in,out] VisibleVariables The visible variables will be appended to this array.
GetMostUpToDateClass() [1/2]
UNREALED_API const UClass * FBlueprintEditorUtils::GetMostUpToDateClass (const UClass * FromClass) static
References GetMostUpToDateClass().
GetMostUpToDateClass() [2/2]
UNREALED_API UClass * FBlueprintEditorUtils::GetMostUpToDateClass (UClass * FromClass) static
Helper function to get the most up to date class , returns FromClass for native types, SkeletonClass for UBlueprint generated classes.
References GetMostUpToDateClass().
Referenced by GetMostUpToDateClass(), and GetMostUpToDateClass().
GetMostUpToDateFunction() [1/2]
UNREALED_API const UFunction * FBlueprintEditorUtils::GetMostUpToDateFunction (const UFunction * Function) static
References Function, and GetMostUpToDateFunction().
GetMostUpToDateFunction() [2/2]
UNREALED_API UFunction * FBlueprintEditorUtils::GetMostUpToDateFunction (UFunction * Function) static
References Function, and GetMostUpToDateFunction().
Referenced by GetMostUpToDateFunction(), and GetMostUpToDateFunction().
GetMostUpToDateProperty() [1/2]
UNREALED_API const FProperty * FBlueprintEditorUtils::GetMostUpToDateProperty (const FProperty * Property) static
References GetMostUpToDateProperty(), and Property.
GetMostUpToDateProperty() [2/2]
UNREALED_API FProperty * FBlueprintEditorUtils::GetMostUpToDateProperty (FProperty * Property) static
Returns the skeleton version of the property, skeleton classes are often more up to date than the authoritative GeneratedClass.
References GetMostUpToDateProperty(), and Property.
Referenced by GetMostUpToDateProperty(), and GetMostUpToDateProperty().
GetNativeParent()
UNREALED_API UClass * FBlueprintEditorUtils::GetNativeParent (const UBlueprint * BP) static
Returns the BPs most derived native parent type:
GetNewVariablesOfType()
UNREALED_API void FBlueprintEditorUtils::GetNewVariablesOfType (const UBlueprint * Blueprint, const FEdGraphPinType & Type, TArray< FName > & OutVars) static
Gets variables of specified type.
Parameters
FEdGraphPinType Type of variables to look for
[in,out] VisibleVariables The visible variables will be appended to this array.
GetNodeByGUID()
UEdGraphNode * FBlueprintEditorUtils::GetNodeByGUID (const UBlueprint * InBlueprint, const FGuid & InNodeGuid) inline static
Searches all nodes in a Blueprint and checks for a matching Guid.
Parameters
InBlueprint The Blueprint to search
InNodeGuid The Guid to check Blueprints against
Returns
Returns a Node with a matching Guid
Definition at line 529 of file BlueprintEditorUtils.h.
References GetAllNodesOfClass().
GetNodesForVariable()
UNREALED_API TArray< UK2Node * > FBlueprintEditorUtils::GetNodesForVariable (const FName & InVarName, const UBlueprint * InBlueprint, const UStruct * InScope = nullptr) static protected
Returns an array of variables Get/Set nodes of the current variable.
Parameters
InVarName Variable to check for being in use
InBlueprint Blueprint to check within
InScope Option scope for local variables
Returns
Array of variable nodes
GetOverrideFunctionClass()
UNREALED_API UClass *const FBlueprintEditorUtils::GetOverrideFunctionClass (UBlueprint * Blueprint, const FName FuncName, UFunction ** OutFunction = nullptr) static
Get the override class of a given function from its name.
Parameters
Blueprint Blueprint to check the function on
FuncName Name of the function
OutFunction The function that has this name
Returns
The override class of a given function
GetSCSVariableNameList() [1/3]
UNREALED_API void FBlueprintEditorUtils::GetSCSVariableNameList (const UBlueprint * Blueprint, TSet< FName > & VariableNames) static
Gets a list of SCS node variable names for the given blueprint.
Parameters
[in,out] VariableNames The list of variable names for the SCS node array.
GetSCSVariableNameList() [2/3]
UNREALED_API void FBlueprintEditorUtils::GetSCSVariableNameList (const UBlueprintGeneratedClass * BPGC, TSet< FName > & VariableNames) static
Gets a list of SCS node variable names for the given BPGC.
Parameters
[in,out] VariableNames The list of variable names for the SCS node array.
GetSCSVariableNameList() [3/3]
UNREALED_API void FBlueprintEditorUtils::GetSCSVariableNameList (const USimpleConstructionScript * SCS, TSet< FName > & VariableNames) static
Gets a list of SCS node variable names for the given SCS.
Parameters
[in,out] VariableNames The list of variable names for the SCS node array.
GetSecondaryIconFromPin()
UNREALED_API const struct FSlateBrush * FBlueprintEditorUtils::GetSecondaryIconFromPin (const FEdGraphPinType & PinType) static
Determine the best secondary icon icon to represent the given pin.
GetSkeletonClass() [1/2]
UNREALED_API const UClass * FBlueprintEditorUtils::GetSkeletonClass (const UClass * FromClass) static
References GetSkeletonClass().
GetSkeletonClass() [2/2]
UNREALED_API UClass * FBlueprintEditorUtils::GetSkeletonClass (UClass * FromClass) static
Helper function to get the SkeletonClass, returns nullptr for UClasses that are not generated by a UBlueprint.
References GetSkeletonClass().
Referenced by GetSkeletonClass(), and GetSkeletonClass().
GetTopLevelGraph()
UNREALED_API UEdGraph * FBlueprintEditorUtils::GetTopLevelGraph (const UEdGraph * InGraph) static
Returns the graph's top level graph (climbing up the hierarchy until there are no more graphs)
Parameters
InGraph The graph to find the parent of
Returns
The top level graph
GetTypeForPin()
UNREALED_API UClass * FBlueprintEditorUtils::GetTypeForPin (const UEdGraphPin & Pin) static
Returns the UClass type for an object pin, if any.
GetUbergraphFunctionName()
UNREALED_API FName FBlueprintEditorUtils::GetUbergraphFunctionName (const UBlueprint * ForBlueprint) static
Returns the name of the Ubergraph Function that the provided blueprint uses.
GetUsedAndUnusedVariables()
UNREALED_API void FBlueprintEditorUtils::GetUsedAndUnusedVariables (UBlueprint * Blueprint, TArray< FProperty * > & OutUsedVariables, TArray< FProperty * > & OutUnusedVariables) static
Removes all unused member variables.
Parameters
OutUsedProperties The list of used variables in the blueprint
OutUnusedProperties The list of unused variables in the blueprint
GetVariableFromOnRepFunction()
UNREALED_API FBPVariableDescription * FBlueprintEditorUtils::GetVariableFromOnRepFunction (UBlueprint * Blueprint, FName FuncName) static
Gets the variable linked to a RepNotify function, returns nullptr if not found.
HandleDisableEditableWhenInherited()
UNREALED_API void FBlueprintEditorUtils::HandleDisableEditableWhenInherited (UObject * ModifiedObject, TArray< UObject * > & ArchetypeInstances) static
Remove overridden component templates from instance component handlers when a parent class disables editable when inherited boolean.
HasFunctionBlueprintThreadSafeMetaData()
UNREALED_API bool FBlueprintEditorUtils::HasFunctionBlueprintThreadSafeMetaData (const UFunction * InFunction) static
HasGetTypeHash()
UNREALED_API bool FBlueprintEditorUtils::HasGetTypeHash (const FEdGraphPinType & PinType) static
Returns true if this terminal type can be hashed (native types need GetTypeHash, script types are always hashable).
ImplementNewInterface()
UNREALED_API bool FBlueprintEditorUtils::ImplementNewInterface (UBlueprint * Blueprint, FTopLevelAssetPath InterfaceClassPathName) static
Add a new interface, and member function graphs to the blueprint.
References ImplementNewInterface().
Referenced by ImplementNewInterface().
ImplementsGetWorld()
UNREALED_API bool FBlueprintEditorUtils::ImplementsGetWorld (const UBlueprint * BP) static
Returns true if this BP is currently based on a type that returns true for the UObject::ImplementsGetWorld() call:
ImplementsInterface()
UNREALED_API bool FBlueprintEditorUtils::ImplementsInterface (const UBlueprint * Blueprint, bool bIncludeInherited, UClass * SomeInterface) static
Returns true if the interfaces is implemented.
It can be implemented directly or inherited.
Parameters
Blueprint The blueprint to check interfaces for
bIncludeInherited If true, check in all the implemented and inherited interfaces. False, check in the interfaces implemented directly.
SomeInterface The interface to check.
References ImplementsInterface().
Referenced by ImplementsInterface().
IsActorBased()
UNREALED_API bool FBlueprintEditorUtils::IsActorBased (const UBlueprint * Blueprint) static
Whether or not this is an actor-based blueprint, and supports features like the uber-graph, components, etc.
Returns
Whether or not this is an actor based blueprint
IsAnonymousBlueprintClass()
UNREALED_API bool FBlueprintEditorUtils::IsAnonymousBlueprintClass (const UClass * Class) static
Whether or not this class represents a class generated by an anonymous actor class stored in a level.
Returns
Whether or not this is an anonymous blueprint
References Class.
IsBlueprintConst()
UNREALED_API bool FBlueprintEditorUtils::IsBlueprintConst (const UBlueprint * Blueprint) static
Returns whether or not the blueprint is const during execution.
IsCompileOnLoadDisabled()
UNREALED_API bool FBlueprintEditorUtils::IsCompileOnLoadDisabled (UBlueprint * Blueprint) static
Returns true if compilation for the given blueprint has been disabled.
References IsCompileOnLoadDisabled().
Referenced by IsCompileOnLoadDisabled().
IsComponentBased()
UNREALED_API bool FBlueprintEditorUtils::IsComponentBased (const UBlueprint * Blueprint) static
Returns
Whether or not this is a component-based blueprint
IsDataOnlyBlueprint()
UNREALED_API bool FBlueprintEditorUtils::IsDataOnlyBlueprint (const UBlueprint * Blueprint) static
Returns
true if the blueprint does not contain any special logic or variables or other elements that require a full compile.
IsDelegateSignatureGraph()
UNREALED_API bool FBlueprintEditorUtils::IsDelegateSignatureGraph (const UEdGraph * Graph) static
Checks if given graph contains a delegate signature.
IsEditorUtilityBlueprint()
UNREALED_API bool FBlueprintEditorUtils::IsEditorUtilityBlueprint (const UBlueprint * Blueprint) static
Returns whether or not the blueprint is an editor utility blueprint or widget.
Referenced by CreateFunctionGraph().
IsEventGraph()
UNREALED_API bool FBlueprintEditorUtils::IsEventGraph (const UEdGraph * InGraph) static
Checks if given graph is an event graph.
IsFunctionConvertableToEvent()
UNREALED_API bool FBlueprintEditorUtils::IsFunctionConvertableToEvent (UBlueprint *const BlueprintObj, UFunction *const Function) static
Check if the blueprint and function are valid options for conversion to an event (BP is not a function library)
Returns
True if this function can be converted to a custom event
References Function.
IsFunctionUsed()
UNREALED_API bool FBlueprintEditorUtils::IsFunctionUsed (const UBlueprint * FunctionBlueprint, const FName & FunctionName, const UEdGraph * LocalGraphScope = nullptr) static
Indicates if the function is used on any graphs in this Blueprint.
IsGraphIntermediate()
UNREALED_API bool FBlueprintEditorUtils::IsGraphIntermediate (const UEdGraph * Graph) static
returns if a graph is an intermediate build product
IsGraphNameUnique()
UNREALED_API bool FBlueprintEditorUtils::IsGraphNameUnique (UObject * InOuter, const FName & InName) static
See whether or not the specified graph name / entry point name is unique.
References InName, InOuter, and IsGraphNameUnique().
Referenced by IsGraphNameUnique().
IsGraphReadOnly()
UNREALED_API bool FBlueprintEditorUtils::IsGraphReadOnly (UEdGraph * InGraph) static
Determines if the graph is ReadOnly, this differs from editable in that it is never expected to be edited and is in a read-only state.
IsInterfaceBlueprint()
UNREALED_API bool FBlueprintEditorUtils::IsInterfaceBlueprint (const UBlueprint * Blueprint) static
Whether or not this blueprint is an interface, used only for defining functions to implement.
Returns
Whether or not this is an interface blueprint
IsInterfaceFunction()
UNREALED_API bool FBlueprintEditorUtils::IsInterfaceFunction (UBlueprint * Blueprint, UFunction * Function) static
Checks if the given function is a part of an interface on this blueprint.
Parameters
Blueprint The blueprint to consider
Function Function to check if it is an interface or not
Returns
True if the given function is implemented as part of an interface
References Function, and IsInterfaceFunction().
Referenced by IsInterfaceFunction().
IsInterfaceGraph()
UNREALED_API bool FBlueprintEditorUtils::IsInterfaceGraph (const UEdGraph * Graph) static
Whether or not this graph is an interface graph (i.e.
is from an interface blueprint)
Returns
Whether or not this is an interface graph
IsLevelScriptBlueprint()
UNREALED_API bool FBlueprintEditorUtils::IsLevelScriptBlueprint (const UBlueprint * Blueprint) static
Whether or not this blueprint is an interface, used only for defining functions to implement.
Returns
Whether or not this is a level script blueprint
IsMathExpressionGraph()
UNREALED_API bool FBlueprintEditorUtils::IsMathExpressionGraph (const UEdGraph * InGraph) static
Checks if given graph is owned by a Math Expression node.
IsNativeSignature()
UNREALED_API bool FBlueprintEditorUtils::IsNativeSignature (const UFunction * Fn) static
returns true if this blueprints signature (inc.
visibility) was determined by UHT, rather than the blueprint compiler
IsObjectADebugCandidate()
UNREALED_API bool FBlueprintEditorUtils::IsObjectADebugCandidate (AActor * InActorObject, UBlueprint * InBlueprint, bool bInDisallowDerivedBlueprints) static protected
Checks that the actor type matches the blueprint type (or optionally is BASED on the same type.
Parameters
InActorObject The object to check
InBlueprint The blueprint to check against
bInDisallowDerivedBlueprints if true will only allow exact type matches, if false derived types are allowed.
IsPaletteActionReadOnly()
UNREALED_API bool FBlueprintEditorUtils::IsPaletteActionReadOnly (TSharedPtr< FEdGraphSchemaAction > ActionIn, TSharedPtr< class FBlueprintEditor > const BlueprintEditorIn) static
A utility function intended to aid the construction of a specific blueprint palette item.
Some items can be renamed, so this method determines if that is allowed.
Parameters
ActionIn The action associated with the palette item you're querying for.
BlueprintEditorIn The blueprint editor owning the palette item you're querying for.
Returns
True is the item CANNOT be renamed, false if it can.
IsParentClassABlueprint()
UNREALED_API bool FBlueprintEditorUtils::IsParentClassABlueprint (const UBlueprint * Blueprint) static
Returns whether the parent class of the specified blueprint is also a blueprint.
IsParentClassAnEditableBlueprint()
UNREALED_API bool FBlueprintEditorUtils::IsParentClassAnEditableBlueprint (const UBlueprint * Blueprint) static
Returns whether the parent class of the specified blueprint is an editable blueprint.
IsPinTypeValid()
UNREALED_API bool FBlueprintEditorUtils::IsPinTypeValid (const FEdGraphPinType & Type) static
Checks if pin type stores proper type for a variable or parameter.
Especially if the UDStruct is valid.
Parameters
Type Checked pin type.
Returns
if type is valid
IsPropertyPrivate()
UNREALED_API bool FBlueprintEditorUtils::IsPropertyPrivate (const FProperty * Property) static
Returns
whether a property is private or not (whether native or via BP metadata)
References Property.
IsPropertyReadableInBlueprint()
UNREALED_API EPropertyReadableState FBlueprintEditorUtils::IsPropertyReadableInBlueprint (const UBlueprint * Blueprint, const FProperty * Property) static
Returns an enumeration indicating if the property can be read by the given Blueprint.
References Property.
IsPropertyWritableInBlueprint()
UNREALED_API EPropertyWritableState FBlueprintEditorUtils::IsPropertyWritableInBlueprint (const UBlueprint * Blueprint, const FProperty * Property) static
Returns an enumeration indicating if the property can be written to by the given Blueprint.
References Property.
IsSCSComponentProperty()
UNREALED_API bool FBlueprintEditorUtils::IsSCSComponentProperty (FObjectProperty * MemberProperty) static
Determines if this property is associated with a component that would be displayed in the SCS editor.
IsTunnelInstanceNode()
UNREALED_API bool FBlueprintEditorUtils::IsTunnelInstanceNode (const UEdGraphNode * InGraphNode) static
Checks if given node is a tunnel instance node.
IsVariableComponent()
UNREALED_API bool FBlueprintEditorUtils::IsVariableComponent (const FBPVariableDescription & Variable) static
Returns whether or not the specified member var is a component.
IsVariableCreatedByBlueprint()
UNREALED_API bool FBlueprintEditorUtils::IsVariableCreatedByBlueprint (UBlueprint * InBlueprint, FProperty * InVariableProperty) static
Returns TRUE if the variable was created by the Blueprint.
IsVariableUsed()
UNREALED_API bool FBlueprintEditorUtils::IsVariableUsed (const UBlueprint * VariableBlueprint, const FName & VariableName, const UEdGraph * LocalGraphScope = nullptr) static
Indicates if the variable is used on any graphs in this Blueprint.
KismetDiagnosticExec()
UNREALED_API bool FBlueprintEditorUtils::KismetDiagnosticExec (const TCHAR * Stream, FOutputDevice & Ar) static
References Ar, and Stream.
LinkExternalDependencies()
UNREALED_API void FBlueprintEditorUtils::LinkExternalDependencies (UBlueprint * Blueprint) static
Links external dependencies.
ListPackageContents()
UNREALED_API void FBlueprintEditorUtils::ListPackageContents (UPackage * Package, FOutputDevice & Ar) static
References Ar, and Package.
MarkBlueprintAsModified()
UNREALED_API void FBlueprintEditorUtils::MarkBlueprintAsModified (UBlueprint * Blueprint, FPropertyChangedEvent PropertyChangedEvent = FPropertyChangedEvent(nullptr)) static
Blueprint has changed in some manner that invalidates the compiled data (link made/broken, default value changed, etc...)
Marks the blueprint as status unknown
Marks the package as dirty
Parameters
Blueprint The Blueprint to mark as modified
PropertyChangedEvent Used when marking the blueprint as modified due to a changed property (optional)
References MarkBlueprintAsModified().
Referenced by MarkBlueprintAsModified(), and FGameModeInfoCustomizer::OnSetDefaultClass().
MarkBlueprintAsStructurallyModified()
UNREALED_API void FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified (UBlueprint * Blueprint) static
Blueprint has structurally changed (added/removed functions, graphs, etc...).
Performs the following actions:
Recompiles the skeleton class.
Notifies any observers.
Marks the package as dirty.
References MarkBlueprintAsStructurallyModified().
Referenced by AddFunctionGraph(), FAnimGraphNodeAlphaOptions::HandlePostEditChangeProperty(), and MarkBlueprintAsStructurallyModified().
MarkBlueprintChildrenAsModified()
UNREALED_API void FBlueprintEditorUtils::MarkBlueprintChildrenAsModified (UBlueprint * InBlueprint) static
Marks all children of a blueprint as modified.
ModifyActorReferencedGraphNodes()
UNREALED_API void FBlueprintEditorUtils::ModifyActorReferencedGraphNodes (ULevelScriptBlueprint * LevelScriptBlueprint, const AActor * InActor) static
Function to call modify() on all graph nodes which reference this actor.
ModifyFunctionMetaData()
UNREALED_API void FBlueprintEditorUtils::ModifyFunctionMetaData (const UEdGraph * InGraph) static
Modifies the graph entry node that contains the function metadata block, used in metadata transactions.
Parameters
InGraph The graph to modify
MoveGraphBeforeOtherGraph()
UNREALED_API bool FBlueprintEditorUtils::MoveGraphBeforeOtherGraph (UEdGraph * Graph, int32 NewIndex, bool bDontRecompile) static
Reorders the specified graph (function or macro) to be at the new index in the parent (moving whatever was there to be after it), assuming it is reorderable and that is a valid index.
MoveVariableAfterVariable()
UNREALED_API bool FBlueprintEditorUtils::MoveVariableAfterVariable (UBlueprint * Blueprint, UStruct * VariableScope, FName VarNameToMove, FName TargetVarName, bool bDontRecompile) static
Change the order of variables in the Blueprint by placing a variable after the target variable.
MoveVariableBeforeVariable()
UNREALED_API bool FBlueprintEditorUtils::MoveVariableBeforeVariable (UBlueprint * Blueprint, UStruct * VariableScope, FName VarNameToMove, FName TargetVarName, bool bDontRecompile) static
Change the order of variables in the Blueprint by placing a variable before the target variable.
OpenReparentBlueprintMenu() [1/2]
UNREALED_API void FBlueprintEditorUtils::OpenReparentBlueprintMenu (const TArray< UBlueprint * > & Blueprints, const TSharedRef< SWidget > & ParentContent, const FOnClassPicked & OnPicked) static
OpenReparentBlueprintMenu() [2/2]
UNREALED_API void FBlueprintEditorUtils::OpenReparentBlueprintMenu (UBlueprint * Blueprint, const TSharedRef< SWidget > & ParentContent, const FOnClassPicked & OnPicked) static
Try to open reparent menu for specified blueprint.
PatchNewCDOIntoLinker()
UNREALED_API void FBlueprintEditorUtils::PatchNewCDOIntoLinker (UObject * CDO, FLinkerLoad * Linker, int32 ExportIndex, FUObjectSerializeContext * InLoadContext) static
Helper function to patch the new CDO into the linker where the old one existed.
PostDuplicateBlueprint()
UNREALED_API void FBlueprintEditorUtils::PostDuplicateBlueprint (UBlueprint * Blueprint, bool bDuplicateForPIE) static
Called on a Blueprint after it has been duplicated.
References PostDuplicateBlueprint().
Referenced by PostDuplicateBlueprint().
PostEditChangeBlueprintActors()
UNREALED_API void FBlueprintEditorUtils::PostEditChangeBlueprintActors (UBlueprint * Blueprint, bool bComponentEditChange = false) static
Call PostEditChange() on all Actors based on the given Blueprint.
PostSetupObjectPinType()
UNREALED_API void FBlueprintEditorUtils::PostSetupObjectPinType (UBlueprint * InBlueprint, FBPVariableDescription & InOutVarDesc) static protected
Validates flags and settings on object pins, keeping them from being given default values and from being in invalid states.
Parameters
InOutVarDesc The variable description to validate
PreloadBlueprintSpecificData()
UNREALED_API void FBlueprintEditorUtils::PreloadBlueprintSpecificData (UBlueprint * Blueprint) static
Helper function to punch through and honor UAnimGraphNode_Base::PreloadRequiredAssets, which formerly relied on loading assets during compile.
PreloadConstructionScript() [1/2]
UNREALED_API void FBlueprintEditorUtils::PreloadConstructionScript (UBlueprint * Blueprint) static
Preloads the construction script, and all templates therein, for the given Blueprint object.
PreloadConstructionScript() [2/2]
UNREALED_API void FBlueprintEditorUtils::PreloadConstructionScript (USimpleConstructionScript * SimpleConstructionScript) static
Preloads the given construction script, and all templates therein.
PreloadMembers()
UNREALED_API void FBlueprintEditorUtils::PreloadMembers (UObject * InObject) static
Preloads the object and all the members it owns (nodes, pins, etc)
PromoteGraphFromInterfaceOverride()
UNREALED_API void FBlueprintEditorUtils::PromoteGraphFromInterfaceOverride (UBlueprint * InBlueprint, UEdGraph * InInterfaceGraph) static
Promotes a Graph from being an Interface Override to a full member function.
Parameters
InBlueprint Blueprint the graph is contained within
InInterfaceGraph The graph to promote
References PromoteGraphFromInterfaceOverride().
Referenced by PromoteGraphFromInterfaceOverride().
PropagateParentBlueprintDefaults()
UNREALED_API void FBlueprintEditorUtils::PropagateParentBlueprintDefaults (UClass * ClassToPropagate) static
Copies the default properties of all parent blueprint classes in the chain to the specified blueprint's skeleton CDO.
References PropagateParentBlueprintDefaults().
Referenced by PropagateParentBlueprintDefaults().
PropertyHasGetTypeHash()
UNREALED_API bool FBlueprintEditorUtils::PropertyHasGetTypeHash (const FProperty * PropertyType) static
Returns true if this type of FProperty can be hashed.
Matches native constructors of FNumericProperty, etc.
PropertyStillExists()
UNREALED_API bool FBlueprintEditorUtils::PropertyStillExists (FProperty * Property) static
Looks at the most up to data class and returns whether the given property exists in it as well.
References Property, and PropertyStillExists().
Referenced by PropertyStillExists().
PropertyValueFromString()
UNREALED_API bool FBlueprintEditorUtils::PropertyValueFromString (const FProperty * Property, const FString & StrValue, uint8 * Container, UObject * OwningObject = nullptr, int32 PortFlags = PPF_None) static
Copies the value from the passed in string into a property.
ContainerMem points to the Struct or Class containing Property NOTE: This function does not work correctly with static arrays.
References Container, PPF_None, and Property.
PropertyValueFromString_Direct()
UNREALED_API bool FBlueprintEditorUtils::PropertyValueFromString_Direct (const FProperty * Property, const FString & StrValue, uint8 * DirectValue, UObject * OwningObject = nullptr, int32 PortFlags = PPF_None) static
Copies the value from the passed in string into a property.
DirectValue is the raw memory address of the property value NOTE: This function does not work correctly with static arrays.
References PPF_None, and Property.
PropertyValueToString()
UNREALED_API bool FBlueprintEditorUtils::PropertyValueToString (const FProperty * Property, const uint8 * Container, FString & OutForm, UObject * OwningObject = nullptr, int32 PortFlags = PPF_None) static
Copies the value from a property into the string OutForm.
ContainerMem points to the Struct or Class containing Property NOTE: This function does not work correctly with static arrays.
References Container, PPF_None, and Property.
PropertyValueToString_Direct()
UNREALED_API bool FBlueprintEditorUtils::PropertyValueToString_Direct (const FProperty * Property, const uint8 * DirectValue, FString & OutForm, UObject * OwningObject = nullptr, int32 PortFlags = PPF_None) static
Copies the value from a property into the string OutForm.
DirectValue is the raw memory address of the property value NOTE: This function does not work correctly with static arrays.
References PPF_None, and Property.
PurgeNullGraphs()
UNREALED_API void FBlueprintEditorUtils::PurgeNullGraphs (UBlueprint * Blueprint) static
Makes sure that all NULL graph references are removed from SubGraphs and top-level graph arrays.
References PurgeNullGraphs().
Referenced by PurgeNullGraphs().
RecombineNestedSubPins()
UNREALED_API void FBlueprintEditorUtils::RecombineNestedSubPins (UK2Node * Node) static
Recombine any nested subpins on this node.
ReconstructAllNodes()
UNREALED_API void FBlueprintEditorUtils::ReconstructAllNodes (UBlueprint * Blueprint) static
Reconstructs all nodes in the blueprint, node reconstruction order determined by FCompareNodePriority.
RecreateClassMetaData()
UNREALED_API void FBlueprintEditorUtils::RecreateClassMetaData (UBlueprint * Blueprint, UClass * Class, bool bRemoveExistingMetaData) static
Recreates class meta data.
References Class, and RecreateClassMetaData().
Referenced by RecreateClassMetaData().
RefreshAllNodes()
UNREALED_API void FBlueprintEditorUtils::RefreshAllNodes (UBlueprint * Blueprint) static
Schedules and refreshes all nodes in the blueprint, making sure that nodes that affect function signatures get regenerated first.
RefreshExternalBlueprintDependencyNodes()
UNREALED_API void FBlueprintEditorUtils::RefreshExternalBlueprintDependencyNodes (UBlueprint * Blueprint, UStruct * RefreshOnlyChild = NULL) static
Optimized refresh of nodes that depend on external blueprints.
Refreshes the nodes, but does not recompile the skeleton class
RefreshGraphNodes()
UNREALED_API void FBlueprintEditorUtils::RefreshGraphNodes (const UEdGraph * Graph) static
Refresh the nodes of an individual graph.
Parameters
Graph The graph to refresh.
RefreshVariables()
UNREALED_API void FBlueprintEditorUtils::RefreshVariables (UBlueprint * Blueprint) static
Synchronizes Blueprint's GeneratedClass's properties with the NewVariable declarations in the blueprint.
RemoveAllLocalBookmarks()
UNREALED_API void FBlueprintEditorUtils::RemoveAllLocalBookmarks (const UBlueprint * ForBlueprint) static
Removes all local bookmarks that reference the given Blueprint asset.
Parameters
ForBlueprint The Blueprint asset for which to remove local Bookmarks.
RemoveBlueprintVariableMetaData()
UNREALED_API void FBlueprintEditorUtils::RemoveBlueprintVariableMetaData (UBlueprint * Blueprint, const FName & VarName, const UStruct * InLocalVarScope, const FName & MetaDataKey) static
Clear metadata key on specified variable, or timeline.
Parameters
Blueprint The Blueprint to find the variable in
VarName Name of the variable
InLocalVarScope Local variable's scope, if looking to modify a local variable
MetaDataKey Key name for the metadata to change
RemoveFieldNotifyFromAllMetadata()
UNREALED_API void FBlueprintEditorUtils::RemoveFieldNotifyFromAllMetadata (UBlueprint * Blueprint, const FName VarName) static
Removes a field notify variable from the metadata of all other field notify variables and functions.
Parameters
VarName Name of the variable to be removed.
RemoveGeneratedClasses()
UNREALED_API void FBlueprintEditorUtils::RemoveGeneratedClasses (UBlueprint * Blueprint) static
Consigns the blueprint's generated classes to oblivion.
References RemoveGeneratedClasses().
Referenced by RemoveGeneratedClasses().
RemoveGraph()
UNREALED_API void FBlueprintEditorUtils::RemoveGraph (UBlueprint * Blueprint, class UEdGraph * GraphToRemove, EGraphRemoveFlags::Type Flags = EGraphRemoveFlags::Default) static
Removes the supplied graph from the Blueprint.
Parameters
Blueprint The blueprint containing the graph
GraphToRemove The graph to remove.
Flags Options to control the removal process
References EGraphRemoveFlags::Default, and Flags.
RemoveGraphs()
UNREALED_API void FBlueprintEditorUtils::RemoveGraphs (UBlueprint * Blueprint, const TArray< class UEdGraph * > & GraphsToRemove) static
Remove the supplied set of graphs from the Blueprint.
Parameters
GraphsToRemove The graphs to remove.
RemoveInterface()
UNREALED_API void FBlueprintEditorUtils::RemoveInterface (UBlueprint * Blueprint, FTopLevelAssetPath InterfaceClassPathName, bool bPreserveFunctions = false) static
Remove an implemented interface, and its associated member function graphs.
If bPreserveFunctions is true, then the interface will move its functions to be normal implemented blueprint functions
References bPreserveFunctions, and RemoveInterface().
Referenced by RemoveInterface().
RemoveInterfaceFunction()
UNREALED_API bool FBlueprintEditorUtils::RemoveInterfaceFunction (UBlueprint * Blueprint, FBPInterfaceDescription & Interface, UFunction * Function, bool bPreserveFunction) static
Attempt to remove a function from an interfaces list of function graphs.
Note that this will NOT remove interface events (i.e. functions with no outputs)
Returns
True if the function was removed from the blueprint
References Function, Interface, and RemoveInterfaceFunction().
Referenced by RemoveInterfaceFunction().
RemoveLocalVariable()
UNREALED_API void FBlueprintEditorUtils::RemoveLocalVariable (UBlueprint * InBlueprint, const UStruct * InScope, const FName InVarName) static
Removes a member variable if it was declared in this blueprint and not in a base class.
Parameters
InBlueprint The Blueprint the local variable can be found in
InScope Local variable's scope
InVarName Name of the variable to be removed.
RemoveMemberVariable()
UNREALED_API void FBlueprintEditorUtils::RemoveMemberVariable (UBlueprint * Blueprint, const FName VarName) static
Removes a member variable if it was declared in this blueprint and not in a base class.
Parameters
VarName Name of the variable to be removed.
RemoveNode()
UNREALED_API void FBlueprintEditorUtils::RemoveNode (UBlueprint * Blueprint, UEdGraphNode * Node, bool bDontRecompile = false) static
Removes the supplied node from the Blueprint.
Parameters
Node The node to remove.
bDontRecompile If true, the blueprint will not be marked as modified, and will not be recompiled. Useful for if you are removing several node at once, and don't want to recompile each time
RemoveStaleFunctions()
UNREALED_API void FBlueprintEditorUtils::RemoveStaleFunctions (UBlueprintGeneratedClass * Class, UBlueprint * Blueprint) static
Procedure used to remove old function implementations and child properties from data only blueprints.
References Class.
RemoveTimeline()
UNREALED_API void FBlueprintEditorUtils::RemoveTimeline (UBlueprint * Blueprint, class UTimelineTemplate * Timeline, bool bDontRecompile = false) static
Remove the timeline from the blueprint.
Note
Just removes the timeline from the associated timelist in the Blueprint. Does not remove the node graph object representing the timeline itself.
Parameters
Timeline The timeline to remove
bDontRecompile If true, the blueprint will not be marked as modified, and will not be recompiled.
RemoveVariableNodes()
UNREALED_API void FBlueprintEditorUtils::RemoveVariableNodes (UBlueprint * Blueprint, const FName VarName, bool const bForSelfOnly = true, UEdGraph * LocalGraphScope = nullptr) static
Removes the variable nodes associated with the specified var name.
Parameters
Blueprint The blueprint you want variable nodes removed from.
VarName Name of the variable to be removed.
bForSelfOnly True if you only want to delete variable nodes that represent ones owned by this blueprint,
LocalGraphScope Local scope graph of variables false if you just want everything with the specified name removed (variables from other classes too).
RenameComponentMemberVariable()
UNREALED_API void FBlueprintEditorUtils::RenameComponentMemberVariable (UBlueprint * Blueprint, USCS_Node * Node, const FName NewName) static
Rename a member variable created by a SCS entry.
RenameFunctionReferences()
UNREALED_API void FBlueprintEditorUtils::RenameFunctionReferences (UBlueprint * Blueprint, UClass * FunctionClass, const FName & OldFuncName, const FName & NewFuncName) static
Looks through the specified blueprint for any references to the specified function, and renames them accordingly.
Parameters
Blueprint The blueprint that you want to search through.
FunctionClass The class that owns the function that we're renaming
OldFuncName The current name of the function we want to replace
NewFuncName The name that we wish to change all references to
RenameGraph()
UNREALED_API void FBlueprintEditorUtils::RenameGraph (class UEdGraph * Graph, const FString & NewName) static
Tries to rename the supplied graph.
Cleans up function entry node if one exists and marks objects for modification
Parameters
Graph The graph to rename.
NewName The new name for the graph
RenameGraphWithSuggestion()
UNREALED_API void FBlueprintEditorUtils::RenameGraphWithSuggestion (class UEdGraph * Graph, TSharedPtr< class INameValidatorInterface > NameValidator, const FString & DesiredName) static
Renames the graph of the supplied node with a valid name based off of the suggestion.
Parameters
GraphNode The node of the graph to rename.
DesiredName The initial form of the name to try
RenameLocalVariable()
UNREALED_API void FBlueprintEditorUtils::RenameLocalVariable (UBlueprint * InBlueprint, const UStruct * InScope, const FName InOldName, const FName InNewName) static
Rename a local variable.
Parameters
InBlueprint Blueprint to search for the local variable
InScope Local variable's scope
InOldName The name of the local variable to change
InNewName The new name of the local variable
RenameMemberVariable()
UNREALED_API void FBlueprintEditorUtils::RenameMemberVariable (UBlueprint * Blueprint, const FName OldName, const FName NewName) static
Rename a member variable.
RenameTimeline()
UNREALED_API bool FBlueprintEditorUtils::RenameTimeline (UBlueprint * Blueprint, const FName OldVarName, const FName NewVarName) static
Rename a Timeline.
If bRenameNodes is true, will also rename any timeline nodes associated with this timeline
RenameVariableReferences()
UNREALED_API void FBlueprintEditorUtils::RenameVariableReferences (UBlueprint * Blueprint, UClass * VariableClass, const FName & OldVarName, const FName & NewVarName) static
Looks through the specified blueprint for any references to the specified variable, and renames them accordingly.
Parameters
Blueprint The blueprint that you want to search through.
VariableClass The class that owns the variable that we're renaming
OldVarName The current name of the variable we want to replace
NewVarName The name that we wish to change all references to
ReplaceAllActorRefrences()
UNREALED_API void FBlueprintEditorUtils::ReplaceAllActorRefrences (ULevelScriptBlueprint * InLevelScriptBlueprint, AActor * InOldActor, AActor * InNewActor) static
Replace all references of the old actor with the new actor.
ReplaceDeprecatedNodes()
UNREALED_API void FBlueprintEditorUtils::ReplaceDeprecatedNodes (UBlueprint * Blueprint) static
Replaces any deprecated nodes with new ones.
ReplaceFunctionReferences()
UNREALED_API void FBlueprintEditorUtils::ReplaceFunctionReferences (UBlueprint * Blueprint, const FName OldName, const FName NewName) static
Replaces all function references in the specified blueprint.
ReplaceInvalidBlueprintNameCharacters()
UNREALED_API void FBlueprintEditorUtils::ReplaceInvalidBlueprintNameCharacters (FString & InBaseName) static
Cleanses a name of invalid characters and replaces them with '_'.
See UE_BLUEPRINT_INVALID_NAME_CHARACTERS for invalid characters.
Parameters
InBaseName The base name to assign
References ReplaceInvalidBlueprintNameCharacters().
Referenced by ReplaceInvalidBlueprintNameCharacters(), and ReplaceInvalidBlueprintNameCharactersInline().
ReplaceInvalidBlueprintNameCharactersInline()
FString FBlueprintEditorUtils::ReplaceInvalidBlueprintNameCharactersInline (FString InBaseName) inline static
Util version of ReplaceInvalidBlueprintNameCharacters that performs the operation inline.
Definition at line 1568 of file BlueprintEditorUtils.h.
References ReplaceInvalidBlueprintNameCharacters(), and ReplaceInvalidBlueprintNameCharactersInline().
Referenced by ReplaceInvalidBlueprintNameCharactersInline().
ReplaceVariableReferences() [1/2]
UNREALED_API void FBlueprintEditorUtils::ReplaceVariableReferences (UBlueprint * Blueprint, const FName OldName, const FName NewName) static
Replaces all variable references in the specified blueprint.
ReplaceVariableReferences() [2/2]
UNREALED_API void FBlueprintEditorUtils::ReplaceVariableReferences (UBlueprint * Blueprint, const FProperty * OldVariable, const FProperty * NewVariable) static
Replaces all variable references in the specified blueprint.
SetAnimationGraphLayerGroup()
UNREALED_API void FBlueprintEditorUtils::SetAnimationGraphLayerGroup (UEdGraph * InGraph, const FText & InGroupName) static
Sets the layer group on the anim graph.
Note
: Will not change the category for functions defined via native classes.
Parameters
InGraph Graph associated with the layer
InGroupName The new value of the group for the layer
SetBlueprintFunctionOrMacroCategory()
UNREALED_API void FBlueprintEditorUtils::SetBlueprintFunctionOrMacroCategory (UEdGraph * Graph, const FText & NewCategory, bool bDontRecompile = false) static
Sets the custom category on the function or macro.
Note
: Will not change the category for functions defined via native classes.
Parameters
Graph Graph associated with the function or macro
NewCategory The new value of the custom category for the function
bDontRecompile If true, the blueprint will not be marked as modified, and will not be recompiled.
SetBlueprintOnlyEditableFlag()
UNREALED_API void FBlueprintEditorUtils::SetBlueprintOnlyEditableFlag (UBlueprint * Blueprint, const FName & VarName, const bool bNewBlueprintOnly) static
Sets the Blueprint edit-only flag on the variable with the specified name.
Parameters
VarName Name of the var to set the flag on
bNewBlueprintOnly The new value to set the bitflag to
SetBlueprintPropertyReadOnlyFlag()
UNREALED_API void FBlueprintEditorUtils::SetBlueprintPropertyReadOnlyFlag (UBlueprint * Blueprint, const FName & VarName, const bool bVariableReadOnly) static
Sets the Blueprint read-only flag on the variable with the specified name.
Parameters
VarName Name of the var to set the flag on
bVariableReadOnly The new value to set the bitflag to
SetBlueprintVariableCategory()
UNREALED_API void FBlueprintEditorUtils::SetBlueprintVariableCategory (UBlueprint * Blueprint, const FName & VarName, const UStruct * InLocalVarScope, const FText & NewCategory, bool bDontRecompile = false) static
Sets the custom category on the variable with the specified name.
Note
: Will not change the category for variables defined via native classes.
Parameters
VarName Name of the variable
InLocalVarScope Local variable's scope, if looking to modify a local variable
VarCategory The new value of the custom category for the variable
bDontRecompile If true, the blueprint will not be marked as modified, and will not be recompiled.
SetBlueprintVariableMetaData()
UNREALED_API void FBlueprintEditorUtils::SetBlueprintVariableMetaData (UBlueprint * Blueprint, const FName & VarName, const UStruct * InLocalVarScope, const FName & MetaDataKey, const FString & MetaDataValue) static
Sets a metadata key/value on the specified variable.
Parameters
Blueprint The Blueprint to find the variable in
VarName Name of the variable
InLocalVarScope Local variable's scope, if looking to modify a local variable
MetaDataKey Key name for the metadata to change
MetaDataValue Value to change the metadata to
SetBlueprintVariableRepNotifyFunc()
UNREALED_API void FBlueprintEditorUtils::SetBlueprintVariableRepNotifyFunc (UBlueprint * Blueprint, const FName & VarName, const FName & RepNotifyFunc) static
Set RepNotify function of variable.
SetInterpFlag()
UNREALED_API void FBlueprintEditorUtils::SetInterpFlag (UBlueprint * Blueprint, const FName & VarName, const bool bInterp) static
Sets the Interp flag on the variable with the specified name to make available to sequencer.
Parameters
VarName Name of the var to set the flag on
bInterp true to make variable available to sequencer, false otherwise
SetVariableAdvancedDisplayFlag()
UNREALED_API void FBlueprintEditorUtils::SetVariableAdvancedDisplayFlag (UBlueprint * InBlueprint, const FName & InVarName, const bool bInIsAdvancedDisplay) static
Sets the Advanced Display flag on the variable with the specified name.
Parameters
InVarName Name of the var to set the flag on
bInIsAdvancedDisplay The new value to set the bitflag to
SetVariableDeprecatedFlag()
UNREALED_API void FBlueprintEditorUtils::SetVariableDeprecatedFlag (UBlueprint * InBlueprint, const FName & InVarName, const bool bInIsDeprecated) static
Sets the Deprecated flag on the variable with the specified name.
Parameters
InVarName Name of the var to set the flag on
bInIsDeprecated The new value to set the bitflag to
SetVariableSaveGameFlag()
UNREALED_API void FBlueprintEditorUtils::SetVariableSaveGameFlag (UBlueprint * InBlueprint, const FName & InVarName, const bool bInIsSaveGame) static
Sets the Save Game flag on the variable with the specified name.
Parameters
InVarName Name of the var to set the flag on
bInIsSaveGame The new value to set the bitflag to
SetVariableTransientFlag()
UNREALED_API void FBlueprintEditorUtils::SetVariableTransientFlag (UBlueprint * InBlueprint, const FName & InVarName, const bool bInIsTransient) static
Sets the Transient flag on the variable with the specified name.
Parameters
InVarName Name of the var to set the flag on
bInIsTransient The new value to set the bitflag to
ShouldOpenWithDataOnlyEditor()
UNREALED_API bool FBlueprintEditorUtils::ShouldOpenWithDataOnlyEditor (const UBlueprint * Blueprint) static
StructHasGetTypeHash()
UNREALED_API bool FBlueprintEditorUtils::StructHasGetTypeHash (const UScriptStruct * StructType) static
Returns true if the StructType is native and has a GetTypeHash or is non-native and all of its member types are handled by UScriptStruct::GetStructTypeHash.
SupportsConstructionScript()
UNREALED_API bool FBlueprintEditorUtils::SupportsConstructionScript (const UBlueprint * Blueprint) static
Do we support construction scripts.
UE_DEPRECATED() [1/7]
FBlueprintEditorUtils::UE_DEPRECATED (5. 0, "Blueprint Nativization has been removed as a supported feature. This API will eventually be removed.") inline
Takes the Blueprint's NativizedFlag property and applies it to the authoritative config (does the same for flagged dependencies)
Definition at line 1404 of file BlueprintEditorUtils.h.
UE_DEPRECATED() [2/7]
FBlueprintEditorUtils::UE_DEPRECATED (5. 0, "Blueprint Nativization has been removed as a supported feature. This API will eventually be removed.")
Retrieves all dependencies that need to be nativized for this to work as a nativized Blueprint.
UE_DEPRECATED() [3/7]
FBlueprintEditorUtils::UE_DEPRECATED (5. 1, "Short class names are no longer supported. Use a version of this function that takes FTopLevelAssetPath.")
Add a new interface, and member function graphs to the blueprint.
UE_DEPRECATED() [4/7]
FBlueprintEditorUtils::UE_DEPRECATED (5. 1, "Short class names are no longer supported. Use a version of this function that takes FTopLevelAssetPath.")
Gets the graphs currently in the blueprint associated with the specified interface.
References UE_DEPRECATED().
UE_DEPRECATED() [5/7]
FBlueprintEditorUtils::UE_DEPRECATED (5. 1, "Short class names are no longer supported. Use a version of this function that takes FTopLevelAssetPath.")
Remove an implemented interface, and its associated member function graphs.
If bPreserveFunctions is true, then the interface will move its functions to be normal implemented blueprint functions
References UE_DEPRECATED().
UE_DEPRECATED() [6/7]
FBlueprintEditorUtils::UE_DEPRECATED (5. 6, "Replace with IsCompileOnLoadDisabled, ShouldRegenerateBlueprint handles reentrancy which is no longer possible.")
Whether or not the blueprint should regenerate its class on load or not.
This prevents macros and other BP types not marked for reconstruction from being recompiled all the time
References UE_DEPRECATED().
UE_DEPRECATED() [7/7]
FBlueprintEditorUtils::UE_DEPRECATED (5. 6, "Use FLinkerLoad::PRIVATE_PatchNewObjectIntoExport instead, which handles the subobjects. And note the comment on that function:both this deprecated function and the LinkerLoad function are coupled to the linker in complicated ways and should only be used in cases of blueprint reinstancing.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UpdateComponentTemplates()
UNREALED_API void FBlueprintEditorUtils::UpdateComponentTemplates (UBlueprint * Blueprint) static
Handle stale components and ensure correct flags are set.
References UpdateComponentTemplates().
Referenced by UpdateComponentTemplates().
UpdateDelegatesInBlueprint()
UNREALED_API void FBlueprintEditorUtils::UpdateDelegatesInBlueprint (UBlueprint * Blueprint) static
Updates sources of delegates.
References UpdateDelegatesInBlueprint().
Referenced by UpdateDelegatesInBlueprint().
UpdateEnumsInNodes()
UNREALED_API void FBlueprintEditorUtils::UpdateEnumsInNodes (const TMap< UEnum *, UEnum * > & Structs, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated) static
Search the blueprints looking for nodes that contain the given enumerations and replace the references.
UpdateOutOfDateAnimBlueprints()
UNREALED_API void FBlueprintEditorUtils::UpdateOutOfDateAnimBlueprints (UBlueprint * Blueprint) static
Handle old AnimBlueprints (state machines in the wrong position, transition graphs with the wrong schema, etc...)
References UpdateOutOfDateAnimBlueprints().
Referenced by UpdateOutOfDateAnimBlueprints().
UpdateOutOfDateCompositeNodes()
UNREALED_API void FBlueprintEditorUtils::UpdateOutOfDateCompositeNodes (UBlueprint * Blueprint) static
Handle fixing up composite nodes within the blueprint.
References UpdateOutOfDateCompositeNodes().
Referenced by UpdateOutOfDateCompositeNodes().
UpdateOutOfDateCompositeWithOuter()
UNREALED_API void FBlueprintEditorUtils::UpdateOutOfDateCompositeWithOuter (UBlueprint * Blueprint, UEdGraph * Outer) static
Handle fixing up composite nodes within the specified Graph of Blueprint, and correctly setting the Outer.
References Outer, and UpdateOutOfDateCompositeWithOuter().
Referenced by UpdateOutOfDateCompositeWithOuter().
UpdateRootComponentReference()
UNREALED_API void FBlueprintEditorUtils::UpdateRootComponentReference (UBlueprint * Blueprint) static
Ensures that the CDO root component reference is valid for Actor-based Blueprints.
UpdateScriptStructsInNodes()
UNREALED_API void FBlueprintEditorUtils::UpdateScriptStructsInNodes (const TMap< UScriptStruct *, UScriptStruct * > & Structs, FOnNodeFoundOrUpdated InOnNodeFoundOrUpdated) static
Search the blueprints looking for nodes that contain the given script structs and replace the references.
UpdateStalePinWatches()
UNREALED_API void FBlueprintEditorUtils::UpdateStalePinWatches (UBlueprint * Blueprint) static
Handle stale pin watches.
References UpdateStalePinWatches().
Referenced by UpdateStalePinWatches().
UpdateTransactionalFlags()
UNREALED_API void FBlueprintEditorUtils::UpdateTransactionalFlags (UBlueprint * Blueprint) static
Handle stale transactional flags on blueprints.
References UpdateTransactionalFlags().
Referenced by UpdateTransactionalFlags().
ValidateAllComponentMemberVariables()
UNREALED_API bool FBlueprintEditorUtils::ValidateAllComponentMemberVariables (UBlueprint * InBlueprint, UBlueprint * InParentBlueprint, const FName & InVariableName) static protected
Validate child blueprint component member variables against the given variable name.
ValidateAllFunctionGraphs()
UNREALED_API bool FBlueprintEditorUtils::ValidateAllFunctionGraphs (UBlueprint * InBlueprint, UBlueprint * InParentBlueprint, const FName & InVariableName) static protected
Validates all function graphs of the passed blueprint against the given variable name.
ValidateAllMemberVariables()
UNREALED_API bool FBlueprintEditorUtils::ValidateAllMemberVariables (UBlueprint * InBlueprint, UBlueprint * InParentBlueprint, const FName InVariableName) static protected
Validate child blueprint member variables against the given variable name.
ValidateAllTimelines()
UNREALED_API bool FBlueprintEditorUtils::ValidateAllTimelines (UBlueprint * InBlueprint, UBlueprint * InParentBlueprint, const FName & InVariableName) static protected
Validates all timelines of the passed blueprint against the given variable name.
ValidateBlueprintChildVariables()
UNREALED_API void FBlueprintEditorUtils::ValidateBlueprintChildVariables (UBlueprint * InBlueprint, const FName InVariableName, TFunction< void(UBlueprint *InChildBP, const FName InVariableName, bool bValidatedVariable)> PostValidationCallback = TFunction< void(UBlueprint *, FName, bool)>()) static
Validate child blueprint component member variables, member variables, and timelines, and function graphs against the given variable name.
Parameters
InBlueprint Target blueprint.
InVariableName Variable or function name to validate child blueprints against.
CustomValidationCallback Optional callback that allows for doing any post-validation tasks.
Referenced by AddFunctionGraph().
ValidateEditorOnlyNodes()
UNREALED_API void FBlueprintEditorUtils::ValidateEditorOnlyNodes (const UK2Node * Node, FCompilerResultsLog & MessageLog) static
If the given node is from an editor only module but is placed in a runtime blueprint then place a warning in the message log that it will not be included in a cooked build.
Parameters
Node Node to check the outer package on
MessageLog BP Compiler results log to output messages to
ValidatePinConnections()
UNREALED_API void FBlueprintEditorUtils::ValidatePinConnections (const UEdGraphNode * Node, FCompilerResultsLog & MessageLog) static
Ensures the validity of each pin connection on the given node.
Outputs compiler error if invalid
Parameters
Node The node to check all linked pins on
MessageLog BP compiler results log to output any error messages to
VerifyUserWantsRepNotifyVariableNameChanged()
UNREALED_API bool FBlueprintEditorUtils::VerifyUserWantsRepNotifyVariableNameChanged (const FName & InVarName, const FName & InFuncName) static protected
Helper function to warn user of the results of changing a RepNotify variable name by displaying a suppressible dialog.
Parameters
InVarName Variable name to display in the dialog message
InFuncName Associated OnRep function name to display in the dialog message
Returns
TRUE if the user wants to change the variable name
VerifyUserWantsVariableTypeChanged()
UNREALED_API bool FBlueprintEditorUtils::VerifyUserWantsVariableTypeChanged (const FName & InVarName) static protected
Helper function to warn user of the results of changing var type by displaying a suppressible dialog.
Parameters
InVarName Variable name to display in the dialog message
Returns
TRUE if the user wants to change the variable type
Field Documentation
bPreserveFunctions
const FName bool FBlueprintEditorUtils::bPreserveFunctions = false)
Definition at line 1443 of file BlueprintEditorUtils.h.
Referenced by RemoveInterface().
ChildGraphs
const FName TArray<UEdGraph*>& FBlueprintEditorUtils::ChildGraphs
Definition at line 1466 of file BlueprintEditorUtils.h.
Referenced by GetInterfaceGraphs().
InterfaceClassName
const FName & FBlueprintEditorUtils::InterfaceClassName
Definition at line 1436 of file BlueprintEditorUtils.h.
NativizeDependenciesOut
TArray<UClass*>& FBlueprintEditorUtils::NativizeDependenciesOut
Initial value:
{}
    UE_DEPRECATED(5.0, "Blueprint Nativization has been removed as a supported feature. This API will eventually be removed.")
    static bool ShouldNativizeImplicitly(const UBlueprint* Blueprint) { return false; }
    static UNREALED_API FGuid FindInterfaceGraphGuid(const FName& GraphName, const UClass* InterfaceClass)
Definition at line 1409 of file BlueprintEditorUtils.h.
NewCDO
UObject* FBlueprintEditorUtils::NewCDO
Definition at line 218 of file BlueprintEditorUtils.h.
OnReconstructAllNodesEvent
UNREALED_API FOnReconstructAllNodes FBlueprintEditorUtils::OnReconstructAllNodesEvent static
Definition at line 160 of file BlueprintEditorUtils.h.
OnRefreshAllNodesEvent
UNREALED_API FOnRefreshAllNodes FBlueprintEditorUtils::OnRefreshAllNodesEvent static
Definition at line 151 of file BlueprintEditorUtils.h.
OnRenameFunctionReferencesEvent
UNREALED_API FOnRenameFunctionReferences FBlueprintEditorUtils::OnRenameFunctionReferencesEvent static
Definition at line 1902 of file BlueprintEditorUtils.h.
OnRenameVariableReferencesEvent
UNREALED_API FOnRenameVariableReferences FBlueprintEditorUtils::OnRenameVariableReferencesEvent static
Definition at line 1887 of file BlueprintEditorUtils.h.
The documentation for this class was generated from the following file:
BlueprintEditorUtils.h