Unreal Engine 5.6 C++ API: FShaderSource Class Reference
FShaderSource Class Reference
#include "ShaderSource.h"
Public Types
typedef ANSICHAR CharType
typedef FCStringAnsi FCStringType
typedef FAnsiString FStringType
typedef FAnsiStringView FViewType
template<int NumChars>
using TStringBuilder = TAnsiStringBuilder<NumChars>
Public Member Functions
FShaderSource ()
RENDERCORE_API FShaderSource (FViewType InSrc, int32 AdditionalSlack=0)
RENDERCORE_API void Compress ()
RENDERCORE_API void Decompress ()
CharType * GetData ()
int32 GetDecompressedSize () const
FViewType GetView () const
bool IsCompressed () const
bool IsEmpty () const
int32 Len () const
RENDERCORE_API FShaderSource & operator= (FStringType &&InSrc)
RENDERCORE_API void Set (FViewType InSrc, int32 AdditionalSlack=0)
void ShrinkToLen (int32 Num, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("ShrinkToLen") FORCEINLINE void ShrinkToLen(int32 Num
UE_DEPRECATED (5.6, "Shader code is always assumed to be ANSI") static const expr bool IsWide()
Constexpr predicate indicating whether wide or ansi chars are used.
UE_DEPRECATED (5.6, "Shader code is always assumed to be ANSI, so GetSimdCharCount() is always 16") static const expr int32 GetSimdCharCount()
Constexpr function returning the number of characters read in a single SIMD compare op.
UE_DEPRECATED (5.6, "Shader code is always assumed to be ANSI, so GetSingleCharMask() is always 1") static const expr int32 GetSingleCharMask()
Constexpr function returning a mask value for a single character.
Data Fields
bool bShrink
Private Member Functions
void SetLen (int32 Num, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Private Attributes
int32 DecompressedCharCount = 0
TArray< CharType > Source
TArray< uint8 > SourceCompressed
Static Private Attributes
static constexpr int32 ShaderSourceSimdPadding = 15
Friends
FArchive & operator<< (FArchive &Ar, FShaderSource &ShaderSource)
Detailed Description
Definition at line 18 of file ShaderSource.h.
Member Typedef Documentation
CharType
typedef ANSICHAR FShaderSource::CharType
Definition at line 31 of file ShaderSource.h.
FCStringType
typedef FCStringAnsi FShaderSource::FCStringType
Definition at line 34 of file ShaderSource.h.
FStringType
typedef FAnsiString FShaderSource::FStringType
Definition at line 33 of file ShaderSource.h.
FViewType
typedef FAnsiStringView FShaderSource::FViewType
Definition at line 32 of file ShaderSource.h.
TStringBuilder
template<int NumChars> using FShaderSource::TStringBuilder = TAnsiStringBuilder<NumChars>
Definition at line 37 of file ShaderSource.h.
Constructor & Destructor Documentation
FShaderSource() [1/2]
FShaderSource::FShaderSource () inline
Definition at line 50 of file ShaderSource.h.
References SetLen().
Referenced by operator<<, and operator=().
FShaderSource() [2/2]
RENDERCORE_API FShaderSource::FShaderSource (FViewType InSrc, int32 AdditionalSlack = 0) explicit
Member Function Documentation
Compress()
RENDERCORE_API void FShaderSource::Compress ()
Decompress()
RENDERCORE_API void FShaderSource::Decompress ()
GetData()
CharType * FShaderSource::GetData () inline
Definition at line 100 of file ShaderSource.h.
References checkf, IsCompressed(), Source, and TEXT.
GetDecompressedSize()
int32 FShaderSource::GetDecompressedSize () const inline
Definition at line 125 of file ShaderSource.h.
References DecompressedCharCount.
GetView()
FViewType FShaderSource::GetView () const inline
Definition at line 91 of file ShaderSource.h.
References checkf, IsCompressed(), Len(), Source, and TEXT.
IsCompressed()
bool FShaderSource::IsCompressed () const inline
Definition at line 120 of file ShaderSource.h.
References DecompressedCharCount.
Referenced by GetData(), GetView(), and Len().
IsEmpty()
bool FShaderSource::IsEmpty () const inline
Definition at line 109 of file ShaderSource.h.
References Len().
Len()
int32 FShaderSource::Len () const inline
Definition at line 114 of file ShaderSource.h.
References checkf, IsCompressed(), ShaderSourceSimdPadding, Source, and TEXT.
Referenced by GetView(), IsEmpty(), and ShrinkToLen().
operator=()
RENDERCORE_API FShaderSource & FShaderSource::operator= (FStringType && InSrc)
References FShaderSource().
Set()
RENDERCORE_API void FShaderSource::Set (FViewType InSrc, int32 AdditionalSlack = 0)
SetLen()
void FShaderSource::SetLen (int32 Num, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline private
Definition at line 21 of file ShaderSource.h.
References DecompressedCharCount, Default, FMemory::Memzero(), Num, ShaderSourceSimdPadding, Source, and SourceCompressed.
Referenced by FShaderSource(), and ShrinkToLen().
ShrinkToLen()
void FShaderSource::ShrinkToLen (int32 Num, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 77 of file ShaderSource.h.
References checkf, Default, Len(), Num, SetLen(), and TEXT.
UE_ALLOWSHRINKING_BOOL_DEPRECATED()
FShaderSource::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("ShrinkToLen")
UE_DEPRECATED() [1/3]
FShaderSource::UE_DEPRECATED (5. 6, "Shader code is always assumed to be ANSI") const inline
Constexpr predicate indicating whether wide or ansi chars are used.
Definition at line 40 of file ShaderSource.h.
UE_DEPRECATED() [2/3]
FShaderSource::UE_DEPRECATED (5. 6, "Shader code is always assumed to be ANSI, so GetSimdCharCount() is always 16") const inline
Constexpr function returning the number of characters read in a single SIMD compare op.
Definition at line 43 of file ShaderSource.h.
UE_DEPRECATED() [3/3]
FShaderSource::UE_DEPRECATED (5. 6, "Shader code is always assumed to be ANSI, so GetSingleCharMask() is always 1") const inline
Constexpr function returning a mask value for a single character.
Definition at line 46 of file ShaderSource.h.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FShaderSource & ShaderSource) friend
References FShaderSource(), and Ar.
Field Documentation
bShrink
bool FShaderSource::bShrink
Initial value:
{
        ShrinkToLen(Num, bShrink ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 83 of file ShaderSource.h.
DecompressedCharCount
int32 FShaderSource::DecompressedCharCount = 0 private
Definition at line 144 of file ShaderSource.h.
Referenced by GetDecompressedSize(), IsCompressed(), and SetLen().
ShaderSourceSimdPadding
int32 FShaderSource::ShaderSourceSimdPadding = 15 static constexpr private
Definition at line 141 of file ShaderSource.h.
Referenced by Len(), and SetLen().
Source
TArray<CharType> FShaderSource::Source private
Definition at line 142 of file ShaderSource.h.
Referenced by GetData(), GetView(), Len(), and SetLen().
SourceCompressed
TArray<uint8> FShaderSource::SourceCompressed private
Definition at line 143 of file ShaderSource.h.
Referenced by SetLen().
The documentation for this class was generated from the following file:
ShaderSource.h