Unreal Engine 5.6 C++ API: FLinker Class Reference
FLinker Class Reference
Manages the data associated with an Unreal package.
#include "Linker.h"
Public Member Functions
FLinker (ELinkerType::Type InType, UPackage *InRoot)
Constructor.
virtual ~FLinker ()
bool FilterExport (const FObjectExport &Export)
Test and object against the load flag filters.
virtual FString GetDebugName () const
Returns a descriptor of the PackagePath this Linker is reading from or writing to, usable for an identifier in warning and log messages.
FString GetExportFullName (FPackageIndex PackageIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified package index.
FString GetExportFullName (int32 ExportIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified export.
FString GetExportPathName (FPackageIndex PackageIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FString GetExportPathName (int32 ExportIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FString GetFullImpExpName (FPackageIndex PackageIndex)
Return the full name of the UObject represented by the specified export.
FString GetPathName (FPackageIndex PackageIndex)
Return the path name of the UObject represented by the specified import.
FORCEINLINE ELinkerType::Type GetType () const
void Serialize (FArchive &Ar)
I/O function.
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") class FSHA1 *ScriptSHA
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void GetScriptSHAKey(uint8 *OutKey)
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void StartScriptSHAGeneration()
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void UpdateScriptSHAKey(const TArray< uint8 > &ScriptCode)
Public Member Functions inherited from FLinkerTables
bool AnyExportIsInImport (int32 ImportIndex) const
Return if any export is in the import.
bool AnyExportShareOuterWithImport (int32 ImportIndex) const
Return if any export share an outer with the import.
bool DoResourcesShareOutermost (FPackageIndex LinkerIndexLHS, FPackageIndex LinkerIndexRHS) const
Return if two resources share the same outermost.
FORCEINLINE FObjectExport & Exp (FPackageIndex Index)
Check that this Index is non-null and an export and return an import.
FORCEINLINE FObjectExport const & Exp (FPackageIndex Index) const
FORCEINLINE FObjectExport * ExpPtr (FPackageIndex Index)
Return an export for this index.
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this container, not including sizeof(*this).
FName GetClassName (FPackageIndex PackageIndex)
Gets the class name for the specified PackageIndex.
FName GetExportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the export map.
FName GetExportClassName (int32 ExportIdx)
Gets the class name for the specified index in the export map.
FString GetExportFullName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified export.
FString GetExportPathName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FName GetImportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the import map.
FName GetImportClassName (int32 ImportIdx)
Gets the class name for the specified index in the import map.
FString GetImportFullName (FPackageIndex PackageIndex)
Return the full name of the UObject represented by the specified package index.
FString GetImportFullName (int32 ImportIndex)
Return the full name of the UObject represented by the specified import.
FString GetImportPathName (FPackageIndex PackageIndex)
Return the path name of the UObject represented by the specified import.
FString GetImportPathName (int32 ImportIndex)
Return the path name of the UObject represented by the specified import.
FORCEINLINE FObjectImport & Imp (FPackageIndex Index)
Check that this Index is non-null and an import and return an import.
FORCEINLINE FObjectImport const & Imp (FPackageIndex Index) const
FORCEINLINE FObjectResource & ImpExp (FPackageIndex Index)
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource const & ImpExp (FPackageIndex Index) const
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource * ImpExpPtr (FPackageIndex Index)
Return an import or export for this index.
bool ImportIsInAnyExport (int32 ImportIndex) const
Return if the import is in any export.
FORCEINLINE FObjectImport * ImpPtr (FPackageIndex Index)
Return an import for this index.
FPackageIndex ResourceGetOutermost (FPackageIndex LinkerIndex) const
Return the outermost resource package index of the resource pointed by LinkerIndex.
bool ResourceIsIn (FPackageIndex LinkerIndex, FPackageIndex OuterIndex) const
Return if a resource has the specified other resource in its outer chain.
void SerializeSearchableNamesMap (FArchive &Ar)
Serializes the searchable name map.
void SerializeSearchableNamesMap (FStructuredArchive::FSlot Slot)
Data Fields
TArray< FObjectDataResource > DataResourceMap
Raw/bulk data references.
bool FilterClientButNotServer
If true, filter out exports that are for clients but not servers.
bool FilterServerButNotClient
If true, filter out exports that are for servers but not clients.
TArray< FGatherableTextData > GatherableTextDataMap
Gatherable text data contained within this package.
UPackage * LinkerRoot
The top-level UPackage object for the package associated with this linker.
TArray< FNameEntryId > NameMap
Names used by objects contained within this package.
TArray< FSoftObjectPath > SoftObjectPathList
List of SoftObjectPath contained in this package,.
FPackageFileSummary Summary
Table of contents for this package's file.
Data Fields inherited from FLinkerTables
TArray< FCellExport > CellExportMap
The list of FCellExports found in the package.
TArray< FCellImport > CellImportMap
The list of FCellImports found in the package.
TArray< TArray< FPackageIndex > > DependsMap
List of dependency lists for each export.
TArray< FObjectExport > ExportMap
The list of FObjectExports found in the package.
TArray< FObjectImport > ImportMap
The list of FObjectImports found in the package.
TMap< FPackageIndex, TArray< FName > > SearchableNamesMap
List of Searchable Names, by object containing them.
TArray< FName > SoftPackageReferenceList
List of packages that are soft referenced by this package.
Private Attributes
ELinkerType::Type LinkerType
Detailed Description
Manages the data associated with an Unreal package.
Acts as the bridge between the file on disk and the UPackage object in memory for all Unreal package types.
Definition at line 396 of file Linker.h.
Constructor & Destructor Documentation
FLinker()
FLinker::FLinker (ELinkerType::Type InType, UPackage * InRoot)
Constructor.
References FLinker().
Referenced by FLinker(), ~FLinker(), FLinkerLoad::GetLinker(), FLinkerSave::GetLinker(), and FLinkerLoad::operator<<().
~FLinker()
virtual FLinker::~FLinker () virtual
References FLinker().
Member Function Documentation
FilterExport()
bool FLinker::FilterExport (const FObjectExport & Export) inline
Test and object against the load flag filters.
Returns
true if the object should be filtered and not loaded
Definition at line 568 of file Linker.h.
References FilterClientButNotServer, FilterExport(), and FilterServerButNotClient.
Referenced by FilterExport().
GetDebugName()
virtual FString FLinker::GetDebugName () const virtual
Returns a descriptor of the PackagePath this Linker is reading from or writing to, usable for an identifier in warning and log messages.
Reimplemented in FLinkerLoad, and FLinkerSave.
GetExportFullName() [1/2]
FString FLinker::GetExportFullName (FPackageIndex PackageIndex, const TCHAR * FakeRoot = nullptr, bool bResolveForcedExports = false) inline
Return the full name of the UObject represented by the specified package index.
Parameters
PackageIndex package index for the resource to get the name for
FakeRoot Optional name to replace use as the root package of this object instead of the linker
bResolveForcedExports if true, the package name part of the return value will be the export's original package, not the name of the package it's currently contained within.
Returns
the full name of the UObject represented by the resource at PackageIndex
Definition at line 527 of file Linker.h.
References GetExportFullName(), FPackageIndex::IsExport(), and FPackageIndex::ToExport().
GetExportFullName() [2/2]
FString FLinker::GetExportFullName (int32 ExportIndex, const TCHAR * FakeRoot = nullptr, bool bResolveForcedExports = false)
Return the full name of the UObject represented by the specified export.
Parameters
ExportIndex index into the ExportMap for the resource to get the name for
FakeRoot Optional name to replace use as the root package of this object instead of the linker
bResolveForcedExports if true, the package name part of the return value will be the export's original package, not the name of the package it's currently contained within.
Returns
the full name of the UObject represented by the resource at ExportIndex
Referenced by GetExportFullName(), and GetFullImpExpName().
GetExportPathName() [1/2]
FString FLinker::GetExportPathName (FPackageIndex PackageIndex, const TCHAR * FakeRoot = nullptr, bool bResolveForcedExports = false) inline
Return the path name of the UObject represented by the specified export.
(can be used with StaticFindObject)
Parameters
PackageIndex package index for the resource to get the name for
FakeRoot Optional name to replace use as the root package of this object instead of the linker
bResolveForcedExports if true, the package name part of the return value will be the export's original package, not the name of the package it's currently contained within.
Returns
the path name of the UObject represented by the resource at PackageIndex, or the empty string if this isn't an export
Definition at line 475 of file Linker.h.
References GetExportPathName(), FPackageIndex::IsExport(), and FPackageIndex::ToExport().
GetExportPathName() [2/2]
FString FLinker::GetExportPathName (int32 ExportIndex, const TCHAR * FakeRoot = nullptr, bool bResolveForcedExports = false)
Return the path name of the UObject represented by the specified export.
(can be used with StaticFindObject)
Parameters
ExportIndex index into the ExportMap for the resource to get the name for
FakeRoot Optional name to replace use as the root package of this object instead of the linker
bResolveForcedExports if true, the package name part of the return value will be the export's original package, not the name of the package it's currently contained within.
Returns
the path name of the UObject represented by the resource at ExportIndex
Referenced by GetExportPathName(), and GetPathName().
GetFullImpExpName()
FString FLinker::GetFullImpExpName (FPackageIndex PackageIndex) inline
Return the full name of the UObject represented by the specified export.
Parameters
PackageIndex package index
Returns
the path name of the UObject represented by the resource at PackageIndex, or the empty string if this is null
Definition at line 543 of file Linker.h.
References GetExportFullName(), FLinkerTables::GetImportFullName(), FPackageIndex::IsExport(), and FPackageIndex::IsImport().
GetPathName()
FString FLinker::GetPathName (FPackageIndex PackageIndex) inline
Return the path name of the UObject represented by the specified import.
(can be used with StaticFindObject)
Parameters
PackageIndex package index
Returns
the path name of the UObject represented by the resource at PackageIndex, or the empty string if this is null
Definition at line 492 of file Linker.h.
References GetExportPathName(), FLinkerTables::GetImportPathName(), FPackageIndex::IsExport(), and FPackageIndex::IsImport().
GetType()
FORCEINLINE ELinkerType::Type FLinker::GetType () const inline
Definition at line 436 of file Linker.h.
References FORCEINLINE, GetType(), and LinkerType.
Referenced by Cast(), CastChecked(), and GetType().
Serialize()
void FLinker::Serialize (FArchive & Ar)
I/O function.
Parameters
Ar the archive to read/write into
References Ar.
Referenced by FLinkerSave::Tell().
UE_DEPRECATED() [1/4]
FLinker::UE_DEPRECATED (5. 6, "No longer supported. Contact Epic if you need this functionality.")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FLinker::UE_DEPRECATED (5. 6, "No longer supported. Contact Epic if you need this functionality.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FLinker::UE_DEPRECATED (5. 6, "No longer supported. Contact Epic if you need this functionality.")
UE_DEPRECATED() [4/4]
FLinker::UE_DEPRECATED (5. 6, "No longer supported. Contact Epic if you need this functionality.") const &
References UE_DEPRECATED().
Field Documentation
DataResourceMap
TArray<FObjectDataResource> FLinker::DataResourceMap
Raw/bulk data references.
Definition at line 420 of file Linker.h.
FilterClientButNotServer
bool FLinker::FilterClientButNotServer
If true, filter out exports that are for clients but not servers.
Definition at line 423 of file Linker.h.
Referenced by FilterExport().
FilterServerButNotClient
bool FLinker::FilterServerButNotClient
If true, filter out exports that are for servers but not clients.
Definition at line 426 of file Linker.h.
Referenced by FilterExport().
GatherableTextDataMap
TArray<FGatherableTextData> FLinker::GatherableTextDataMap
Gatherable text data contained within this package.
Definition at line 417 of file Linker.h.
LinkerRoot
UPackage* FLinker::LinkerRoot
The top-level UPackage object for the package associated with this linker.
Definition at line 405 of file Linker.h.
LinkerType
ELinkerType::Type FLinker::LinkerType private
Definition at line 400 of file Linker.h.
Referenced by GetType().
NameMap
TArray<FNameEntryId> FLinker::NameMap
Names used by objects contained within this package.
Definition at line 411 of file Linker.h.
Referenced by FLinkerLoad::operator<<().
SoftObjectPathList
TArray<FSoftObjectPath> FLinker::SoftObjectPathList
List of SoftObjectPath contained in this package,.
Definition at line 414 of file Linker.h.
Summary
FPackageFileSummary FLinker::Summary
Table of contents for this package's file.
Definition at line 408 of file Linker.h.
The documentation for this class was generated from the following file:
Linker.h