Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicMeshOctree3 Class Reference
UE::Geometry::FDynamicMeshOctree3 Class Reference
FDynamicMeshOctree3 is an extension of FSparseDynamicOctree3 for the triangles of a FDynamicMesh3 instance.
#include "DynamicMeshOctree3.h"
Data Structures
struct FCellReference
FCellReference is a handle to an internal cell of the octree.
class FTreeCutSet
FTreeCutSet is a cut of the tree, ie a set of internal cells which are "parents" of separate branches.
Public Member Functions
FTreeCutSet BuildLevelCutSet (uint32 CutLevel=5) const
void CheckValidity (EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check, bool bVerbose=false, bool bFailOnMissingObjects=false) const
Check that the Octree is internally valid.
void CollectRootTriangles (const FTreeCutSet &CutSet, TFunctionRef< void(int)> TriangleFunc) const
Call TriangleFunc for all triangles in the octree "above" the CutSet (ie at tree cells that are not children of any cut cells)
void CollectSpillTriangles (TFunctionRef< void(int)> TriangleFunc) const
Call TriangleFunc for any triangles in the spill set (ie not contained in any Root cell)
void CollectTriangles (const FCellReference &CellRef, TFunctionRef< void(int)> TriangleFunc) const
Call TriangleFunc on any triangles in the branch of the tree starting at CellRef.
int32 FindNearestHitObject (const FRay3d &Ray, double MaxDistance=TNumericLimits< double >::Max()) const
Find the nearest triangle of the mesh that is hit by the ray.
int32 FindNearestHitObject (const FRay3d &Ray, TFunctionRef< bool(int)> IncludeTriangleIDFunc, double MaxDistance=TNumericLimits< double >::Max()) const
Find the nearest triangle of the mesh that is hit by the ray.
void Initialize (const FDynamicMesh3 *MeshIn)
Add all triangles of MeshIn to the octree.
void InsertTriangle (int32 TriangleID)
Insert a triangle into the tree.
void InsertTriangles (const TArray< int > &Triangles)
Insert a list of triangles into the tree.
void InsertTriangles (const TSet< int > &Triangles)
Insert a set of triangles into the tree.
template<typename EnumerableType>
void NotifyPendingModification (const EnumerableType &Triangles)
Include the current bounds of a set of triangles in the ModifiedBounds box.
void NotifyPendingModification (int TriangleID)
Include the current bounds of a triangle in the ModifiedBounds box.
template<typename EnumerableType>
void ReinsertTriangles (const EnumerableType &Triangles)
Reinsert a set of triangles into the tree.
void ReinsertTrianglesParallel (const TArray< int32 > &Triangles, TArray< uint32 > &TempBuffer, TArray< bool > &TempFlagBuffer)
Reinsert a set of triangles into the tree.
bool RemoveTriangle (int32 TriangleID)
Remove a triangle from the tree.
template<typename EnumerableType>
void RemoveTriangles (const EnumerableType &Triangles, bool bMarkModifiedBounds=true)
Remove a set of triangles into the tree.
void ResetModifiedBounds ()
Reset the internal ModifiedBounds box that tracks modified triangle bounds.
bool TestCellIntersection (const FCellReference &CellRef, const FAxisAlignedBox3d &Bounds) const
void UpdateLevelCutSet (FTreeCutSet &CutSet, TArray< FCellReference > &NewCutCellsOut) const
For a fixed-level cut set created by BuildLevelCutSet, check that all current cells at that level are in the cut set (call this after adding/removing to the tree to make sure the CutSet is up to date)
Public Member Functions inherited from UE::Geometry::FSparseDynamicOctree3
GEOMETRYCORE_API bool CheckIfObjectNeedsReinsert (int32 ObjectID, const FAxisAlignedBox3d &NewBounds, uint32 &CellIDOut) const
Check if the object needs to be reinserted, if it has NewBounds.
GEOMETRYCORE_API void CheckValidity (TFunctionRef< bool(int)> IsValidObjectIDFunc, TFunctionRef< FAxisAlignedBox3d(int)> GetObjectBoundsFunc, EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check, bool bVerbose=false, bool bFailOnMissingObjects=false) const
Check that the octree is internally valid.
GEOMETRYCORE_API void ComputeStatistics (FStatistics &StatsOut) const
Populate given FStatistics with info about the octree.
GEOMETRYCORE_API void ContainmentQuery (const FVector3d &Point, TFunctionRef< void(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that contain query point.
GEOMETRYCORE_API bool ContainmentQueryCancellable (const FVector3d &Point, TFunctionRef< bool(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that contain query point.
GEOMETRYCORE_API bool ContainsObject (int32 ObjectID) const
Test if an object is stored in the tree.
GEOMETRYCORE_API int32 FindNearestHitObject (const FRay3d &Ray, TFunctionRef< FAxisAlignedBox3d(int)> GetObjectBoundsFunc, TFunctionRef< double(int, const FRay3d &)> HitObjectDistFunc, double MaxDistance=TNumericLimits< double >::Max()) const
Find nearest ray-hit point with objects in tree.
int GetMaxTreeDepth ()
GEOMETRYCORE_API void InsertObject (int32 ObjectID, const FAxisAlignedBox3d &Bounds)
Insert ObjectID into the Octree.
int ParallelOverlapAnyQuery (const FAxisAlignedBox3d &ShapeBounds, TFunctionRef< bool(int32)> ObjectOverlapFn) const
Find any overlap between a caller-defined query and any object ID.
GEOMETRYCORE_API int ParallelOverlapAnyQuery (const FAxisAlignedBox3d &ShapeBounds, TFunctionRef< bool(int32)> ObjectOverlapFn, TFunctionRef< bool(const FAxisAlignedBox3d &)> BoundsOverlapFn) const
Find any overlap between a caller-defined query and any object ID.
GEOMETRYCORE_API void ParallelRangeQuery (const FAxisAlignedBox3d &Bounds, TArray< int > &ObjectIDsOut) const
Collect ObjectIDs from all the cells with bounding boxes that intersect Bounds.
GEOMETRYCORE_API void ParallelRangeQuery (const FAxisAlignedBox3d &RangeBoundsHint, TFunctionRef< bool(const FAxisAlignedBox3d &CellBounds)> BoundsOverlapFn, TArray< int32 > &ObjectIDs) const
Collect ObjectIDs from all the leaf cells that have bounding boxes that pass BoundsOverlapFn.
GEOMETRYCORE_API void RangeQuery (const FAxisAlignedBox3d &Bounds, TArray< int > &ObjectIDsOut) const
Collect ObjectIDs from all the cells with bounding boxes that intersect Bounds.
GEOMETRYCORE_API void RangeQuery (const FAxisAlignedBox3d &Bounds, TFunctionRef< void(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that intersect Bounds.
GEOMETRYCORE_API bool ReinsertObject (int32 ObjectID, const FAxisAlignedBox3d &NewBounds, uint32 CellIDHint=InvalidCellID)
Update the position of an object in the octree.
GEOMETRYCORE_API bool RemoveObject (int32 ObjectID)
Remove an object from the octree.
void SetMaxTreeDepth (int MaxTreeDepthIn)
Sets max tree depth w/ protection against setting beyond supported max.
Data Fields
const FDynamicMesh3 * Mesh
parent mesh
FAxisAlignedBox3d ModifiedBounds
bounding box of triangles that have been inserted/removed since last clear
Data Fields inherited from UE::Geometry::FSparseDynamicOctree3
double MaxExpandFactor = 0.25
Fraction we expand the dimension of any cell, to allow extra space to fit objects.
double RootDimension = 1000.0
Size of the Root cells of the octree.
Additional Inherited Members
Static Public Attributes inherited from UE::Geometry::FSparseDynamicOctree3
static constexpr uint32 MaxSupportedTreeDepth = 0x1F
Protected Member Functions inherited from UE::Geometry::FSparseDynamicOctree3
GEOMETRYCORE_API void BranchRangeQuery (const FSparseOctreeCell *ParentCell, const FAxisAlignedBox3d &Bounds, TArray< int > &ObjectIDs) const
bool CanFit (const FSparseOctreeCell &Cell, const FAxisAlignedBox3d &Bounds) const
GEOMETRYCORE_API FSparseOctreeCell FindCurrentContainingCell (const FAxisAlignedBox3d &Bounds) const
GEOMETRYCORE_API double FindNearestRayCellIntersection (const FSparseOctreeCell &Cell, const FRay3d &Ray) const
FAxisAlignedBox3d GetBox (uint32 Level, const FVector3i &Index, double ExpandFactor) const
FAxisAlignedBox3d GetCellBox (const FSparseOctreeCell &Cell, double ExpandFactor=0) const
FVector3d GetCellCenter (const FSparseOctreeCell &Cell) const
uint32 GetCellForObject (int32 ObjectID) const
double GetCellWidth (uint32 Level) const
GEOMETRYCORE_API void Insert_NewChildCell (int32 ObjectID, const FAxisAlignedBox3d &Bounds, int ParentCellID, FSparseOctreeCell NewChildCell, int ChildIdx)
GEOMETRYCORE_API void Insert_NewRoot (int32 ObjectID, const FAxisAlignedBox3d &Bounds, FSparseOctreeCell NewRootCell)
GEOMETRYCORE_API void Insert_Spill (int32 ObjectID, const FAxisAlignedBox3d &Bounds)
GEOMETRYCORE_API void Insert_ToCell (int32 ObjectID, const FAxisAlignedBox3d &Bounds, const FSparseOctreeCell &ExistingCell)
FVector3i PointToIndex (uint32 Level, const FVector3d &Position) const
int ToChildCellIndex (const FSparseOctreeCell &Cell, const FVector3d &Position) const
Protected Attributes inherited from UE::Geometry::FSparseDynamicOctree3
FSmallListSet CellObjectLists
FRefCountVector CellRefCounts
TDynamicVector< FSparseOctreeCell > Cells
int MaxTreeDepth = 10
Objects will not be inserted more than this many levels deep from a Root cell.
TDynamicVector< uint32 > ObjectIDToCellMap
TSparseGrid3< uint32 > RootCells
TSet< int32 > SpillObjectSet
FDynamicFlagArray ValidObjectIDs
Static Protected Attributes inherited from UE::Geometry::FSparseDynamicOctree3
static constexpr uint32 InvalidCellID = FSparseOctreeCell::InvalidID
static constexpr uint32 SpillCellID = InvalidCellID - 1
Detailed Description
FDynamicMeshOctree3 is an extension of FSparseDynamicOctree3 for the triangles of a FDynamicMesh3 instance.
This extension does several things: 1) provides a simplified API based on triangle IDs to various Octree functions 2) tracks ModifiedBounds box of modified areas 3) support for computing/updating/querying a "Cut" of the octree, ie a set of cells which are roots of sub-branches that partition the tree. This is useful for splitting up mesh processing/rendering into spatially-coherent chunks. (This functionality should probably be extracted into a separate class...)
Definition at line 27 of file DynamicMeshOctree3.h.
Member Function Documentation
BuildLevelCutSet()
FTreeCutSet UE::Geometry::FDynamicMeshOctree3::BuildLevelCutSet (uint32 CutLevel = 5) const inline
Returns
a cut of the tree at a fixed level
Definition at line 309 of file DynamicMeshOctree3.h.
References TSet< InElementType, KeyFuncs, Allocator >::Add(), Cell, UE::Geometry::FDynamicMeshOctree3::FCellReference::CellID, UE::Geometry::FSparseDynamicOctree3::Cells, UE::Geometry::FDynamicMeshOctree3::FTreeCutSet::CutCellIDs, UE::Geometry::FDynamicMeshOctree3::FTreeCutSet::CutCells, and UE::Geometry::FDynamicMeshOctree3::FTreeCutSet::FixedCutLevel.
CheckValidity()
void UE::Geometry::FDynamicMeshOctree3::CheckValidity (EValidityCheckFailMode FailMode = EValidityCheckFailMode::Check, bool bVerbose = false, bool bFailOnMissingObjects = false) const inline
Check that the Octree is internally valid.
Definition at line 264 of file DynamicMeshOctree3.h.
References UE::Geometry::Check, UE::Geometry::FSparseDynamicOctree3::CheckValidity(), and Mesh.
CollectRootTriangles()
void UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles (const FTreeCutSet & CutSet, TFunctionRef< void(int)> TriangleFunc) const inline
Call TriangleFunc for all triangles in the octree "above" the CutSet (ie at tree cells that are not children of any cut cells)
Definition at line 401 of file DynamicMeshOctree3.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FSparseOctreeCell::CellID, UE::Geometry::FSparseDynamicOctree3::CellObjectLists, UE::Geometry::FSparseDynamicOctree3::Cells, TSet< InElementType, KeyFuncs, Allocator >::Contains(), UE::Geometry::FDynamicMeshOctree3::FTreeCutSet::CutCellIDs, UE::Geometry::FSparseOctreeCell::GetChildCellID(), UE::Geometry::FSparseOctreeCell::HasChild(), No, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Pop(), and UE::Geometry::FSparseDynamicOctree3::RootCells.
CollectSpillTriangles()
void UE::Geometry::FDynamicMeshOctree3::CollectSpillTriangles (TFunctionRef< void(int)> TriangleFunc) const inline
Call TriangleFunc for any triangles in the spill set (ie not contained in any Root cell)
Definition at line 441 of file DynamicMeshOctree3.h.
References UE::Geometry::FSparseDynamicOctree3::SpillObjectSet.
CollectTriangles()
void UE::Geometry::FDynamicMeshOctree3::CollectTriangles (const FCellReference & CellRef, TFunctionRef< void(int)> TriangleFunc) const inline
Call TriangleFunc on any triangles in the branch of the tree starting at CellRef.
Definition at line 367 of file DynamicMeshOctree3.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FDynamicMeshOctree3::FCellReference::CellID, UE::Geometry::FSparseOctreeCell::CellID, UE::Geometry::FSparseDynamicOctree3::CellObjectLists, UE::Geometry::FSparseDynamicOctree3::CellRefCounts, UE::Geometry::FSparseDynamicOctree3::Cells, check, UE::Geometry::FSparseOctreeCell::GetChildCellID(), UE::Geometry::FSparseOctreeCell::HasChild(), No, TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::Pop().
FindNearestHitObject() [1/2]
int32 UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject (const FRay3d & Ray, double MaxDistance = TNumericLimits<double>::Max()) const inline
Find the nearest triangle of the mesh that is hit by the ray.
Definition at line 224 of file DynamicMeshOctree3.h.
References UE::Geometry::FSparseDynamicOctree3::FindNearestHitObject(), UE::Geometry::TIntrRay3Triangle3< Real, RayType >::IntersectionType, Mesh, Point, Ray, UE::Geometry::TIntrRay3Triangle3< Real, RayType >::RayParameter, and UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleIntersection().
FindNearestHitObject() [2/2]
int32 UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject (const FRay3d & Ray, TFunctionRef< bool(int)> IncludeTriangleIDFunc, double MaxDistance = TNumericLimits<double>::Max()) const inline
Find the nearest triangle of the mesh that is hit by the ray.
Parameters
IncludeTriangleIDFunc predicate function that must return true for given TriangleID for it to be considered
Definition at line 242 of file DynamicMeshOctree3.h.
References UE::Geometry::FSparseDynamicOctree3::FindNearestHitObject(), UE::Geometry::TIntrRay3Triangle3< Real, RayType >::IntersectionType, Mesh, Point, Ray, UE::Geometry::TIntrRay3Triangle3< Real, RayType >::RayParameter, and UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleIntersection().
Initialize()
void UE::Geometry::FDynamicMeshOctree3::Initialize (const FDynamicMesh3 * MeshIn) inline
Add all triangles of MeshIn to the octree.
Definition at line 44 of file DynamicMeshOctree3.h.
References InsertTriangle(), and Mesh.
InsertTriangle()
void UE::Geometry::FDynamicMeshOctree3::InsertTriangle (int32 TriangleID) inline
Insert a triangle into the tree.
Definition at line 65 of file DynamicMeshOctree3.h.
References UE::Geometry::FSparseDynamicOctree3::InsertObject(), Mesh, and ModifiedBounds.
Referenced by Initialize().
InsertTriangles() [1/2]
void UE::Geometry::FDynamicMeshOctree3::InsertTriangles (const TArray< int > & Triangles) inline
Insert a list of triangles into the tree.
Definition at line 78 of file DynamicMeshOctree3.h.
References UE::Geometry::FSparseDynamicOctree3::InsertObject(), Mesh, ModifiedBounds, and TArray< InElementType, InAllocatorType >::Num().
InsertTriangles() [2/2]
void UE::Geometry::FDynamicMeshOctree3::InsertTriangles (const TSet< int > & Triangles) inline
Insert a set of triangles into the tree.
Definition at line 95 of file DynamicMeshOctree3.h.
References UE::Geometry::FSparseDynamicOctree3::InsertObject(), Mesh, and ModifiedBounds.
NotifyPendingModification() [1/2]
template<typename EnumerableType> void UE::Geometry::FDynamicMeshOctree3::NotifyPendingModification (const EnumerableType & Triangles) inline
Include the current bounds of a set of triangles in the ModifiedBounds box.
Definition at line 208 of file DynamicMeshOctree3.h.
References Mesh, and ModifiedBounds.
NotifyPendingModification() [2/2]
void UE::Geometry::FDynamicMeshOctree3::NotifyPendingModification (int TriangleID) inline
Include the current bounds of a triangle in the ModifiedBounds box.
Definition at line 195 of file DynamicMeshOctree3.h.
References Mesh, and ModifiedBounds.
ReinsertTriangles()
template<typename EnumerableType> void UE::Geometry::FDynamicMeshOctree3::ReinsertTriangles (const EnumerableType & Triangles) inline
Reinsert a set of triangles into the tree.
Definition at line 144 of file DynamicMeshOctree3.h.
References Mesh, ModifiedBounds, UE::Geometry::FSparseDynamicOctree3::ReinsertObject(), and RemoveObject.
ReinsertTrianglesParallel()
void UE::Geometry::FDynamicMeshOctree3::ReinsertTrianglesParallel (const TArray< int32 > & Triangles, TArray< uint32 > & TempBuffer, TArray< bool > & TempFlagBuffer) inline
Reinsert a set of triangles into the tree.
Internally precomputes which triangles need re-inserting, which can be done in parallel and generally saves time as some triangles can be skipped.
Definition at line 166 of file DynamicMeshOctree3.h.
References UE::Geometry::FSparseDynamicOctree3::CheckIfObjectNeedsReinsert(), Mesh, No, TArray< InElementType, InAllocatorType >::Num(), ParallelFor(), UE::Geometry::FSparseDynamicOctree3::ReinsertObject(), and TArray< InElementType, InAllocatorType >::SetNum().
RemoveTriangle()
bool UE::Geometry::FDynamicMeshOctree3::RemoveTriangle (int32 TriangleID) inline
Remove a triangle from the tree.
Definition at line 112 of file DynamicMeshOctree3.h.
References Mesh, ModifiedBounds, and RemoveObject.
RemoveTriangles()
template<typename EnumerableType> void UE::Geometry::FDynamicMeshOctree3::RemoveTriangles (const EnumerableType & Triangles, bool bMarkModifiedBounds = true) inline
Remove a set of triangles into the tree.
Definition at line 127 of file DynamicMeshOctree3.h.
References Mesh, ModifiedBounds, and RemoveObject.
ResetModifiedBounds()
void UE::Geometry::FDynamicMeshOctree3::ResetModifiedBounds () inline
Reset the internal ModifiedBounds box that tracks modified triangle bounds.
Definition at line 57 of file DynamicMeshOctree3.h.
References UE::Geometry::TAxisAlignedBox3< double >::Empty(), and ModifiedBounds.
TestCellIntersection()
bool UE::Geometry::FDynamicMeshOctree3::TestCellIntersection (const FCellReference & CellRef, const FAxisAlignedBox3d & Bounds) const inline
Returns
true if the cell identified by CellRef intersects the Bounds box
Definition at line 357 of file DynamicMeshOctree3.h.
References Cell, UE::Geometry::FDynamicMeshOctree3::FCellReference::CellID, UE::Geometry::FSparseDynamicOctree3::CellRefCounts, UE::Geometry::FSparseDynamicOctree3::Cells, check, UE::Geometry::FSparseDynamicOctree3::GetCellBox(), UE::Geometry::TAxisAlignedBox3< RealType >::Intersects(), and UE::Geometry::FSparseDynamicOctree3::MaxExpandFactor.
UpdateLevelCutSet()
void UE::Geometry::FDynamicMeshOctree3::UpdateLevelCutSet (FTreeCutSet & CutSet, TArray< FCellReference > & NewCutCellsOut) const inline
For a fixed-level cut set created by BuildLevelCutSet, check that all current cells at that level are in the cut set (call this after adding/removing to the tree to make sure the CutSet is up to date)
Parameters
CutSet the tree cut set to check/update
NewCutCellsOut list of new cut cells added by the update
Definition at line 336 of file DynamicMeshOctree3.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), Cell, UE::Geometry::FDynamicMeshOctree3::FCellReference::CellID, UE::Geometry::FSparseDynamicOctree3::Cells, TSet< InElementType, KeyFuncs, Allocator >::Contains(), UE::Geometry::FDynamicMeshOctree3::FTreeCutSet::CutCellIDs, UE::Geometry::FDynamicMeshOctree3::FTreeCutSet::CutCells, and UE::Geometry::FDynamicMeshOctree3::FTreeCutSet::FixedCutLevel.
Field Documentation
Mesh
const FDynamicMesh3* UE::Geometry::FDynamicMeshOctree3::Mesh
parent mesh
Definition at line 36 of file DynamicMeshOctree3.h.
Referenced by CheckValidity(), FindNearestHitObject(), FindNearestHitObject(), Initialize(), InsertTriangle(), InsertTriangles(), InsertTriangles(), NotifyPendingModification(), NotifyPendingModification(), ReinsertTriangles(), ReinsertTrianglesParallel(), RemoveTriangle(), and RemoveTriangles().
ModifiedBounds
FAxisAlignedBox3d UE::Geometry::FDynamicMeshOctree3::ModifiedBounds
bounding box of triangles that have been inserted/removed since last clear
Definition at line 39 of file DynamicMeshOctree3.h.
Referenced by InsertTriangle(), InsertTriangles(), InsertTriangles(), NotifyPendingModification(), NotifyPendingModification(), ReinsertTriangles(), RemoveTriangle(), RemoveTriangles(), and ResetModifiedBounds().
The documentation for this class was generated from the following file:
DynamicMeshOctree3.h