Unreal Engine 5.6 C++ API: FInstanceDataManager Class Reference
FInstanceDataManager Class Reference
Manager class that tracks changes to instance data within the component, and is responsible for dispatching updates of the proxy.
#include "InstanceDataManager.h"
Public Types
enum class ETrackingState : uint8 { Initial , Tracked , Disabled , Optimized }
Current tracking state,.
Public Member Functions
FInstanceDataManager (UPrimitiveComponent *InPrimitiveComponent)
FPrimitiveInstanceId Add (int32 InInstanceAddAtIndex)
Tracking functions that mirror what is done to each instance in the source instance data array.
void BakedLightingDataChanged (int32 InstanceIndex)
void BakedLightingDataChangedAll ()
void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform, FInstanceDataManagerSourceDataDesc &&ComponentData)
void ClearChangeTracking ()
Clear all tracked changes (will result in a full update when next one is flushed)
void ClearInstances ()
void CustomDataChanged (int32 InstanceIndex)
void EditorDataChangedAll ()
bool FlushChanges (FInstanceDataManagerSourceDataDesc &&ComponentData)
Queries the tracker for changes and builds an update build command to enqueue to the render thread.
SIZE_T GetAllocatedSize () const
int32 GetMaxAllocatedInstanceId () const
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > GetOrCreateProxy ()
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > GetProxy ()
ETrackingState GetState () const
bool HasAnyChanges () const
Returns true if there are explicitly tracked instance changes, or the state is not tracked (because no proxy has been created yet), and the tracking state is not Disabled.
bool HasAnyInstanceChanges () const
void NumCustomDataChanged ()
TArray< int32 > Optimize (FInstanceDataManagerSourceDataDesc &&ComponentData, bool bShouldRetainIdMap)
Compute the instance order used to build the instance hierarchy (spatial hashes) and return the reordering needed for this.
void PrimitiveTransformChanged ()
void ReadCookedRenderData (FArchive &Ar)
void RemoveAt (int32 InstanceIndex)
void RemoveAtSwap (int32 InstanceIndex)
void Serialize (FArchive &Ar, bool bCooked)
void TransformChanged (FPrimitiveInstanceId InstanceId)
void TransformChanged (int32 InstanceIndex)
void TransformsChangedAll ()
FORCEINLINE void ValidateMapping () const
void WriteCookedRenderData (FArchive &Ar, FInstanceDataManagerSourceDataDesc &&ComponentData)
Public Member Functions inherited from FInstanceIdIndexMap
FInstanceIdIndexMap ()=default
void CreateExplicitIdentityMapping ()
Convert an implicit identity mapping to an explicit one, by filling in the mapping arrays.
FORCEINLINE int32 GetMaxInstanceId () const
Returms the upper bound on the instance ID represented as an integer, may be larger than the number of instances but is never larger than the max that has ever been allocated.
FORCEINLINE int32 GetMaxInstanceIndex () const
Returns the maximum instance index (or rather the maximum valid number plus one), AKA the number of instances represented.
FORCEINLINE int32 IdToIndex (FPrimitiveInstanceId InstanceId) const
Translate from FPrimitiveInstanceId to Index.
FORCEINLINE FPrimitiveInstanceId IndexToId (int32 InstanceIndex) const
Translate from Index to FPrimitiveInstanceId.
FORCEINLINE bool IsIdentity () const
Returns true if the mapping is an identity mapping.
FORCEINLINE bool IsValidId (FPrimitiveInstanceId InstanceId) const
Returns true if InstanceId is in the mapped range AND .
void RebuildFromIndexToIdMap (TArray< FPrimitiveInstanceId > &&InIndexToIdMap, int32 MaxInstanceId)
void Reset (int32 InNumInstances)
Reset the mapping to an identity map of size InNumInstances.
void ResizeExplicit (int32 InNumInstances, int32 MaxInstanceId)
Make sure the mapping is explicit and add enough space to accommodate the InNumInstances & MaxInstanceId.
void Serialize (FArchive &Ar)
FORCEINLINE void SetInvalid (FPrimitiveInstanceId InstanceId)
Set the index mapping for the given InstanceId to INDEX_NONE.
FORCEINLINE void Update (FPrimitiveInstanceId InstanceId, int32 InstanceIndex)
Update the mapping from ID to index (and vice versa).
Protected Types
using EChangeFlag = FInstanceAttributeTracker::EFlag
Protected Member Functions
void CreateExplicitIdentityMapping ()
void FreeInstanceId (FPrimitiveInstanceId InstanceId)
void GatherDefaultData (const FInstanceDataManagerSourceDataDesc &ComponentData, FInstanceUpdateChangeSet &ChangeSet) const
TSharedPtr< class FUpdatableInstanceDataSceneProxy, ESPMode::ThreadSafe > GetOrCreateProxyInternal ()
bool HasIdentityMapping () const
void InitChangeSet (const FInstanceDataManagerSourceDataDesc &ComponentData, FInstanceUpdateChangeSet &ChangeSet) const
Initialize a chage set from the component data & manager state but not using any delta information or updating tracked state.
void InitChangeSet (const struct FChangeDesc2 &ChangeDesc, const FInstanceDataManagerSourceDataDesc &ComponentData, FInstanceUpdateChangeSet &ChangeSet)
template<EChangeFlag Flag>
void MarkChangeHelper (FPrimitiveInstanceId InstanceId)
template<EChangeFlag Flag>
void MarkChangeHelper (int32 InstanceIndex)
void MarkComponentRenderInstancesDirty ()
FPrecomputedInstanceSpatialHashData PrecomputeOptimizationData (FInstanceDataManagerSourceDataDesc &&ComponentData)
Build precomputed data from the ComponentData.
bool ShouldWriteCookedData (const ITargetPlatform *TargetPlatform, int32 NumInstancesToBuildFor)
Protected Member Functions inherited from FInstanceIdIndexMap
void RebuildFromIndexToIdMap (int32 MaxInstanceId)
Static Protected Member Functions
static FPrecomputedInstanceSpatialHashData PrecomputeOptimizationData (FInstanceUpdateChangeSet &ChangeSet)
Build precomputed data from a ChangeSet.
static bool ShouldUsePrecomputed ()
Protected Attributes
float AbsMaxDisplacement = 0.0f
FInstanceDataFlags AllChangedFlags
uint8 bAnyInstanceChange: 1
uint8 bNumCustomDataChanged: 1
uint8 bPrimitiveTransformChanged: 1
uint8 bTransformChangedAllInstances: 1
FInstanceDataFlags Flags
int32 IdSearchStartIndex = 0
TSharedPtr< class FUpdatableInstanceDataSceneProxy, ESPMode::ThreadSafe > InstanceDataProxy
FInstanceAttributeTracker InstanceUpdateTracker
FRenderBounds MeshBounds
int32 NumCustomDataFloats = 0
FPrecomputedInstanceSpatialHashDataPtr PrecomputedOptimizationData
TWeakObjectPtr< UPrimitiveComponent > PrimitiveComponent = nullptr
ETrackingState TrackingState = ETrackingState::Initial
TBitArray ValidInstanceIdMask
Protected Attributes inherited from FInstanceIdIndexMap
TArray< int32 > IdToIndexMap
TArray< FPrimitiveInstanceId > IndexToIdMap
int32 NumInstances = 0
Detailed Description
Manager class that tracks changes to instance data within the component, and is responsible for dispatching updates of the proxy.
Tracks instance index changes to be able to maintain a persistent ID mapping for use on the render thread. The ID mapping is not serialized and will be reset when the proxy is recreated. Not responsible for storing the component representation of the instance data. NOTE/TODO: This is tied to the ISM use-case, mostly because of legacy (HISM) interactions. Will be refactored and sub-classed or something. Also: Still somewhat tied to the UComponent, which also can be refactored a bit to make it more general.
Definition at line 67 of file InstanceDataManager.h.
Member Typedef Documentation
EChangeFlag
using FInstanceDataManager::EChangeFlag = FInstanceAttributeTracker::EFlag protected
Definition at line 173 of file InstanceDataManager.h.
Member Enumeration Documentation
ETrackingState
enum class FInstanceDataManager::ETrackingState : uint8 strong
Current tracking state,.
Enumerator
Initial
Tracked
Disabled
Optimized
Definition at line 76 of file InstanceDataManager.h.
Constructor & Destructor Documentation
FInstanceDataManager()
FInstanceDataManager::FInstanceDataManager (UPrimitiveComponent * InPrimitiveComponent)
Member Function Documentation
Add()
FPrimitiveInstanceId FInstanceDataManager::Add (int32 InInstanceAddAtIndex)
Tracking functions that mirror what is done to each instance in the source instance data array.
BakedLightingDataChanged()
void FInstanceDataManager::BakedLightingDataChanged (int32 InstanceIndex)
BakedLightingDataChangedAll()
void FInstanceDataManager::BakedLightingDataChangedAll ()
BeginCacheForCookedPlatformData()
void FInstanceDataManager::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform, FInstanceDataManagerSourceDataDesc && ComponentData)
ClearChangeTracking()
void FInstanceDataManager::ClearChangeTracking ()
Clear all tracked changes (will result in a full update when next one is flushed)
ClearInstances()
void FInstanceDataManager::ClearInstances ()
CreateExplicitIdentityMapping()
void FInstanceDataManager::CreateExplicitIdentityMapping () protected
CustomDataChanged()
void FInstanceDataManager::CustomDataChanged (int32 InstanceIndex)
EditorDataChangedAll()
void FInstanceDataManager::EditorDataChangedAll ()
FlushChanges()
bool FInstanceDataManager::FlushChanges (FInstanceDataManagerSourceDataDesc && ComponentData)
Queries the tracker for changes and builds an update build command to enqueue to the render thread.
The ComponentData supplies source data through a callback as needed.
FreeInstanceId()
void FInstanceDataManager::FreeInstanceId (FPrimitiveInstanceId InstanceId) protected
GatherDefaultData()
void FInstanceDataManager::GatherDefaultData (const FInstanceDataManagerSourceDataDesc & ComponentData, FInstanceUpdateChangeSet & ChangeSet) const protected
GetAllocatedSize()
SIZE_T FInstanceDataManager::GetAllocatedSize () const
GetMaxAllocatedInstanceId()
int32 FInstanceDataManager::GetMaxAllocatedInstanceId () const
GetOrCreateProxy()
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > FInstanceDataManager::GetOrCreateProxy ()
GetOrCreateProxyInternal()
TSharedPtr< class FUpdatableInstanceDataSceneProxy, ESPMode::ThreadSafe > FInstanceDataManager::GetOrCreateProxyInternal () protected
GetProxy()
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > FInstanceDataManager::GetProxy ()
GetState()
ETrackingState FInstanceDataManager::GetState () const inline
Definition at line 136 of file InstanceDataManager.h.
References TrackingState.
Referenced by HasAnyChanges().
HasAnyChanges()
bool FInstanceDataManager::HasAnyChanges () const inline
Returns true if there are explicitly tracked instance changes, or the state is not tracked (because no proxy has been created yet), and the tracking state is not Disabled.
Definition at line 121 of file InstanceDataManager.h.
References Disabled, GetState(), HasAnyInstanceChanges(), and Tracked.
HasAnyInstanceChanges()
bool FInstanceDataManager::HasAnyInstanceChanges () const
Referenced by HasAnyChanges().
HasIdentityMapping()
bool FInstanceDataManager::HasIdentityMapping () const protected
InitChangeSet() [1/2]
void FInstanceDataManager::InitChangeSet (const FInstanceDataManagerSourceDataDesc & ComponentData, FInstanceUpdateChangeSet & ChangeSet) const protected
Initialize a chage set from the component data & manager state but not using any delta information or updating tracked state.
InitChangeSet() [2/2]
void FInstanceDataManager::InitChangeSet (const struct FChangeDesc2 & ChangeDesc, const FInstanceDataManagerSourceDataDesc & ComponentData, FInstanceUpdateChangeSet & ChangeSet) protected
MarkChangeHelper() [1/2]
template<EChangeFlag Flag> void FInstanceDataManager::MarkChangeHelper (FPrimitiveInstanceId InstanceId) inline protected
MarkChangeHelper() [2/2]
template<EChangeFlag Flag> void FInstanceDataManager::MarkChangeHelper (int32 InstanceIndex) inline protected
MarkComponentRenderInstancesDirty()
void FInstanceDataManager::MarkComponentRenderInstancesDirty () protected
NumCustomDataChanged()
void FInstanceDataManager::NumCustomDataChanged ()
Optimize()
TArray< int32 > FInstanceDataManager::Optimize (FInstanceDataManagerSourceDataDesc && ComponentData, bool bShouldRetainIdMap)
Compute the instance order used to build the instance hierarchy (spatial hashes) and return the reordering needed for this.
This should be used by the data source (i.e., UComponent etc) to reorder the source instance buffers. Returns a reordering table where each index stores the old index for the given new index.
PrecomputeOptimizationData() [1/2]
FPrecomputedInstanceSpatialHashData FInstanceDataManager::PrecomputeOptimizationData (FInstanceDataManagerSourceDataDesc && ComponentData) protected
Build precomputed data from the ComponentData.
PrecomputeOptimizationData() [2/2]
FPrecomputedInstanceSpatialHashData FInstanceDataManager::PrecomputeOptimizationData (FInstanceUpdateChangeSet & ChangeSet) static protected
Build precomputed data from a ChangeSet.
PrimitiveTransformChanged()
void FInstanceDataManager::PrimitiveTransformChanged ()
ReadCookedRenderData()
void FInstanceDataManager::ReadCookedRenderData (FArchive & Ar)
References Ar.
RemoveAt()
void FInstanceDataManager::RemoveAt (int32 InstanceIndex)
RemoveAtSwap()
void FInstanceDataManager::RemoveAtSwap (int32 InstanceIndex)
Serialize()
void FInstanceDataManager::Serialize (FArchive & Ar, bool bCooked)
References Ar.
ShouldUsePrecomputed()
bool FInstanceDataManager::ShouldUsePrecomputed () static protected
ShouldWriteCookedData()
bool FInstanceDataManager::ShouldWriteCookedData (const ITargetPlatform * TargetPlatform, int32 NumInstancesToBuildFor) protected
TransformChanged() [1/2]
void FInstanceDataManager::TransformChanged (FPrimitiveInstanceId InstanceId)
TransformChanged() [2/2]
void FInstanceDataManager::TransformChanged (int32 InstanceIndex)
TransformsChangedAll()
void FInstanceDataManager::TransformsChangedAll ()
ValidateMapping()
FORCEINLINE void FInstanceDataManager::ValidateMapping () const inline
Definition at line 144 of file InstanceDataManager.h.
References FORCEINLINE.
WriteCookedRenderData()
void FInstanceDataManager::WriteCookedRenderData (FArchive & Ar, FInstanceDataManagerSourceDataDesc && ComponentData)
References Ar.
Field Documentation
AbsMaxDisplacement
float FInstanceDataManager::AbsMaxDisplacement = 0.0f protected
Definition at line 235 of file InstanceDataManager.h.
AllChangedFlags
FInstanceDataFlags FInstanceDataManager::AllChangedFlags protected
Definition at line 221 of file InstanceDataManager.h.
bAnyInstanceChange
uint8 FInstanceDataManager::bAnyInstanceChange protected
Definition at line 225 of file InstanceDataManager.h.
bNumCustomDataChanged
uint8 FInstanceDataManager::bNumCustomDataChanged protected
Definition at line 222 of file InstanceDataManager.h.
bPrimitiveTransformChanged
uint8 FInstanceDataManager::bPrimitiveTransformChanged protected
Definition at line 224 of file InstanceDataManager.h.
bTransformChangedAllInstances
uint8 FInstanceDataManager::bTransformChangedAllInstances protected
Definition at line 223 of file InstanceDataManager.h.
Flags
FInstanceDataFlags FInstanceDataManager::Flags protected
Definition at line 233 of file InstanceDataManager.h.
IdSearchStartIndex
int32 FInstanceDataManager::IdSearchStartIndex = 0 protected
Definition at line 218 of file InstanceDataManager.h.
InstanceDataProxy
TSharedPtr<class FUpdatableInstanceDataSceneProxy, ESPMode::ThreadSafe> FInstanceDataManager::InstanceDataProxy protected
Definition at line 227 of file InstanceDataManager.h.
InstanceUpdateTracker
FInstanceAttributeTracker FInstanceDataManager::InstanceUpdateTracker protected
Definition at line 214 of file InstanceDataManager.h.
MeshBounds
FRenderBounds FInstanceDataManager::MeshBounds protected
Definition at line 236 of file InstanceDataManager.h.
NumCustomDataFloats
int32 FInstanceDataManager::NumCustomDataFloats = 0 protected
Definition at line 234 of file InstanceDataManager.h.
PrecomputedOptimizationData
FPrecomputedInstanceSpatialHashDataPtr FInstanceDataManager::PrecomputedOptimizationData protected
Definition at line 230 of file InstanceDataManager.h.
PrimitiveComponent
TWeakObjectPtr<UPrimitiveComponent> FInstanceDataManager::PrimitiveComponent = nullptr protected
Definition at line 228 of file InstanceDataManager.h.
TrackingState
ETrackingState FInstanceDataManager::TrackingState = ETrackingState::Initial protected
Definition at line 220 of file InstanceDataManager.h.
Referenced by GetState().
ValidInstanceIdMask
TBitArray FInstanceDataManager::ValidInstanceIdMask protected
Definition at line 217 of file InstanceDataManager.h.
The documentation for this class was generated from the following file:
InstanceDataManager.h