Unreal Engine 5.6 C++ API: FMultiBoxBuilder Class Reference
FMultiBoxBuilder Class Reference abstract
MultiBox builder.
#include "MultiBoxBuilder.h"
Public Member Functions
FMultiBoxBuilder (const EMultiBoxType InType, FMultiBoxCustomization InCustomization, const bool bInShouldCloseWindowAfterMenuSelection, const TSharedPtr< const FUICommandList > &InCommandList, TSharedPtr< FExtender > InExtender=TSharedPtr< FExtender >(), FName InTutorialHighlightName=NAME_None, FName InMenuName=NAME_None)
Constructor.
virtual ~FMultiBoxBuilder ()
void AddEditableText (const FText &InLabel, const FText &InToolTip, const FSlateIcon &InIcon, const TAttribute< FText > &InTextAttribute, const FOnTextCommitted &InOnTextCommitted=FOnTextCommitted(), const FOnTextChanged &InOnTextChanged=FOnTextChanged(), bool bInReadOnly=false)
Adds an editable text entry.
void AddVerifiedEditableText (const FText &InLabel, const FText &InToolTip, const FSlateIcon &InIcon, const TAttribute< FText > &InTextAttribute, const FOnVerifyTextChanged &InOnVerifyTextChanged, const FOnTextCommitted &InOnTextCommitted=FOnTextCommitted(), const FOnTextChanged &InOnTextChanged=FOnTextChanged(), bool bInReadOnly=false)
Adds an editable text entry with a VerifyTextChanged delegate.
bool ExtendersEnabled () const
FMultiBoxCustomization GetCustomization () const
TSharedRef< class FMultiBox > GetMultiBox ()
Get the multi-box being built.
const FName & GetStyleName () const
const ISlateStyle * GetStyleSet () const
TSharedPtr< const FUICommandList > GetTopCommandList ()
virtual TSharedRef< class SWidget > MakeWidget (FMultiBox::FOnMakeMultiBoxBuilderOverride *InMakeMultiBoxBuilderOverride=nullptr)
Creates a widget for this MultiBox.
void PopCommandList ()
Pops the current command list.
void PopExtender ()
Pops the current extender.
void PushCommandList (const TSharedRef< const FUICommandList > CommandList)
Pushes a new command list onto the stack.
void PushExtender (TSharedRef< FExtender > InExtender)
Pushes a new extender onto the stack.
void SetCheckBoxStyle (FName InCheckBoxStyle)
the override for the checkbox style
void SetExtendersEnabled (bool bEnabled)
Sets extender support.
void SetLastSelectedCommandIndex (int32 InLastSelectedCommandIndex)
void SetStyle (const ISlateStyle *InStyleSet, const FName &InStyleName)
Sets the style to use on the multibox widgets.
Protected Member Functions
virtual void ApplyHook (FName InExtensionHook, EExtensionHook::Position HookPosition)=0
Applies any potential extension hooks at the current place.
virtual void ApplySectionBeginning ()
Applies the beginning of a section, including the header and relevant separator.
Protected Attributes
bool bExtendersEnabled
If extenders are enabled.
FName CheckBoxStyle
the override for the checkbox style for this menu
TArray< TSharedPtr< const FUICommandList > > CommandListStack
A stack of command lists which map command infos to delegates that should be called.
TArray< TSharedPtr< class FExtender > > ExtenderStack
The extender stack holding all the possible extensions for this menu builder.
FName MenuName
Name of the menu.
TSharedRef< class FMultiBox > MultiBox
The MultiBox we're building up.
FName TutorialHighlightName
Name to identify this widget and highlight during tutorials.
Detailed Description
MultiBox builder.
Definition at line 33 of file MultiBoxBuilder.h.
Constructor & Destructor Documentation
FMultiBoxBuilder()
FMultiBoxBuilder::FMultiBoxBuilder (const EMultiBoxType InType, FMultiBoxCustomization InCustomization, const bool bInShouldCloseWindowAfterMenuSelection, const TSharedPtr< const FUICommandList > & InCommandList, TSharedPtr< FExtender > InExtender = TSharedPtr< FExtender >(), FName InTutorialHighlightName = NAME_None, FName InMenuName = NAME_None)
Constructor.
Parameters
InType Type of MultiBox
bInShouldCloseWindowAfterMenuSelection Sets whether or not the window that contains this multibox should be destroyed after the user clicks on a menu item in this box
InCommandList The action list that maps command infos to delegates that should be called for each command associated with a multiblock widget. This can be modified after the MultiBox is created by calling the PushCommandList() and PopCommandList() methods.
InTutorialHighlightName Optional name to identify this widget and highlight during tutorials
Referenced by FButtonRowBuilder::FButtonRowBuilder(), and FToolBarBuilder::FToolBarBuilder().
~FMultiBoxBuilder()
virtual FMultiBoxBuilder::~FMultiBoxBuilder () inline virtual
Definition at line 48 of file MultiBoxBuilder.h.
Member Function Documentation
AddEditableText()
void FMultiBoxBuilder::AddEditableText (const FText & InLabel, const FText & InToolTip, const FSlateIcon & InIcon, const TAttribute< FText > & InTextAttribute, const FOnTextCommitted & InOnTextCommitted = FOnTextCommitted(), const FOnTextChanged & InOnTextChanged = FOnTextChanged(), bool bInReadOnly = false)
Adds an editable text entry.
Parameters
InLabel The label to display in the menu
InToolTip The tool tip to display when the menu entry is hovered over
InIcon The icon to display to the left of the label
InTextAttribute The text string we're editing (often, a delegate will be bound to the attribute)
InOnTextCommitted Called when the user commits their change to the editable text control
InOnTextChanged Called when the text is changed interactively
bInReadOnly Whether or not the text block is read only
AddVerifiedEditableText()
void FMultiBoxBuilder::AddVerifiedEditableText (const FText & InLabel, const FText & InToolTip, const FSlateIcon & InIcon, const TAttribute< FText > & InTextAttribute, const FOnVerifyTextChanged & InOnVerifyTextChanged, const FOnTextCommitted & InOnTextCommitted = FOnTextCommitted(), const FOnTextChanged & InOnTextChanged = FOnTextChanged(), bool bInReadOnly = false)
Adds an editable text entry with a VerifyTextChanged delegate.
Parameters
InLabel The label to display in the menu
InToolTip The tool tip to display when the menu entry is hovered over
InIcon The icon to display to the left of the label
InTextAttribute The text string we're editing (often, a delegate will be bound to the attribute)
InOnVerifyTextChanged Called to verify when the text is changed interactively
InOnTextCommitted Called when the user commits their change to the editable text control
InOnTextChanged Called when the text is changed interactively
bInReadOnly Whether or not the text block is read only
ApplyHook()
virtual void FMultiBoxBuilder::ApplyHook (FName InExtensionHook, EExtensionHook::Position HookPosition) protected pure virtual
Applies any potential extension hooks at the current place.
Implemented in FButtonRowBuilder, FMenuBarBuilder, FMenuBuilder, and FToolBarBuilder.
ApplySectionBeginning()
virtual void FMultiBoxBuilder::ApplySectionBeginning () inline protected virtual
Applies the beginning of a section, including the header and relevant separator.
Reimplemented in FMenuBuilder, and FToolBarBuilder.
Definition at line 152 of file MultiBoxBuilder.h.
ExtendersEnabled()
bool FMultiBoxBuilder::ExtendersEnabled () const inline
Returns
True if extenders are enabled
Definition at line 145 of file MultiBoxBuilder.h.
References bExtendersEnabled.
GetCustomization()
FMultiBoxCustomization FMultiBoxBuilder::GetCustomization () const
Returns
The customization settings for the box being built
GetMultiBox()
TSharedRef< class FMultiBox > FMultiBoxBuilder::GetMultiBox ()
Get the multi-box being built.
Returns
The multi-box being built.
GetStyleName()
const FName & FMultiBoxBuilder::GetStyleName () const
Returns
The style name used by the multibox widgets
GetStyleSet()
const ISlateStyle * FMultiBoxBuilder::GetStyleSet () const
Returns
The style set used by the multibox widgets
GetTopCommandList()
TSharedPtr< const FUICommandList > FMultiBoxBuilder::GetTopCommandList ()
Returns
The top command list
MakeWidget()
virtual TSharedRef< class SWidget > FMultiBoxBuilder::MakeWidget (FMultiBox::FOnMakeMultiBoxBuilderOverride * InMakeMultiBoxBuilderOverride = nullptr) virtual
Creates a widget for this MultiBox.
Returns
New widget object
Reimplemented in FMenuBuilder.
PopCommandList()
void FMultiBoxBuilder::PopCommandList ()
Pops the current command list.
PopExtender()
void FMultiBoxBuilder::PopExtender ()
Pops the current extender.
PushCommandList()
void FMultiBoxBuilder::PushCommandList (const TSharedRef< const FUICommandList > CommandList)
Pushes a new command list onto the stack.
This command list will be used for all subsequently-added multiblocks, until the command-list is popped.
Parameters
CommandList The new command list to use
PushExtender()
void FMultiBoxBuilder::PushExtender (TSharedRef< FExtender > InExtender)
Pushes a new extender onto the stack.
This extender will be used for all subsequently-added multiblocks, until the extender is popped.
Parameters
InExtender The new extender to use
SetCheckBoxStyle()
void FMultiBoxBuilder::SetCheckBoxStyle (FName InCheckBoxStyle)
the override for the checkbox style
SetExtendersEnabled()
void FMultiBoxBuilder::SetExtendersEnabled (bool bEnabled) inline
Sets extender support.
Definition at line 142 of file MultiBoxBuilder.h.
References bExtendersEnabled.
SetLastSelectedCommandIndex()
void FMultiBoxBuilder::SetLastSelectedCommandIndex (int32 InLastSelectedCommandIndex)
SetStyle()
void FMultiBoxBuilder::SetStyle (const ISlateStyle * InStyleSet, const FName & InStyleName)
Sets the style to use on the multibox widgets.
Referenced by FVerticalToolBarBuilder::FVerticalToolBarBuilder().
Field Documentation
bExtendersEnabled
bool FMultiBoxBuilder::bExtendersEnabled protected
If extenders are enabled.
Definition at line 176 of file MultiBoxBuilder.h.
Referenced by ExtendersEnabled(), and SetExtendersEnabled().
CheckBoxStyle
FName FMultiBoxBuilder::CheckBoxStyle protected
the override for the checkbox style for this menu
Definition at line 173 of file MultiBoxBuilder.h.
CommandListStack
TArray< TSharedPtr< const FUICommandList > > FMultiBoxBuilder::CommandListStack protected
A stack of command lists which map command infos to delegates that should be called.
New multi blocks will always use the command-list at the top of the stack at the time they are added.
Definition at line 161 of file MultiBoxBuilder.h.
ExtenderStack
TArray< TSharedPtr<class FExtender> > FMultiBoxBuilder::ExtenderStack protected
The extender stack holding all the possible extensions for this menu builder.
Definition at line 164 of file MultiBoxBuilder.h.
MenuName
FName FMultiBoxBuilder::MenuName protected
Name of the menu.
Definition at line 170 of file MultiBoxBuilder.h.
MultiBox
TSharedRef< class FMultiBox > FMultiBoxBuilder::MultiBox protected
The MultiBox we're building up.
Definition at line 157 of file MultiBoxBuilder.h.
Referenced by FMenuBarBuilder::FMenuBarBuilder().
TutorialHighlightName
FName FMultiBoxBuilder::TutorialHighlightName protected
Name to identify this widget and highlight during tutorials.
Definition at line 167 of file MultiBoxBuilder.h.
The documentation for this class was generated from the following file:
MultiBoxBuilder.h