Unreal Engine 5.6 C++ API: UE::Geometry::FMeshPropertyMapEvaluator Class Reference
UE::Geometry::FMeshPropertyMapEvaluator Class Reference
A mesh evaluator for mesh properties as color data.
#include "MeshPropertyMapEvaluator.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FMeshPropertyMapEvaluator ()=default
FMeshPropertyMapEvaluator (const FMeshPropertyMapEvaluator &)=default
virtual DYNAMICMESH_API const TArray< EComponents > & DataLayout () const override
FMeshPropertyMapEvaluator & operator= (const FMeshPropertyMapEvaluator &)=default
DYNAMICMESH_API virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void Setup (const FMeshBaseBaker &Baker, FEvaluationContext &Context) override
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
virtual EMeshMapEvaluatorType Type () const override
Public Member Functions inherited from UE::Geometry::FMeshMapEvaluator
virtual ~FMeshMapEvaluator ()=default
Static Public Member Functions
static DYNAMICMESH_API void EvaluateChannel (const int DataIdx, float *&In, float &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateColor (const int DataIdx, float *&In, FVector4f &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateDefault (float *&Out, void *EvalData)
template<bool bUseDetailNormalMap>
static void EvaluateSample (float *&Out, const FCorrespondenceSample &Sample, void *EvalData)
Data Fields
EMeshPropertyMapType Property = EMeshPropertyMapType::Normal
Protected Types
using FNormalTexture = IMeshBakerDetailSampler::FBakeDetailNormalTexture
using FNormalTextureMap = TMap<const void*, FNormalTexture>
Protected Member Functions
DYNAMICMESH_API FVector4f GetDefaultValue (EMeshPropertyMapType InProperty) const
UE_DEPRECATED (5.6, "DefaultValue is deprecated. Please use GetDefaultValue() instead.") FVector3f DefaultValue
Protected Attributes
bool bHasDetailNormalTextures = false
FAxisAlignedBox3d Bounds
FNormalTextureMap DetailNormalMaps
const IMeshBakerDetailSampler * DetailSampler = nullptr
Private Member Functions
template<bool bUseDetailNormalMap>
FVector4f SampleFunction (const FCorrespondenceSample &SampleData) const
Static Private Member Functions
static FVector4f NormalToColor (const FVector3f Normal)
static FVector4f PositionToColor (const FVector3d Position, const FAxisAlignedBox3d SafeBounds)
static FVector4f UVToColor (const FVector2f UV)
Private Attributes
FVector4f DefaultValue4f = FVector4f()
Additional Inherited Members
Public Types inherited from UE::Geometry::FMeshMapEvaluator
enum class EAccumulateMode { Add , Overwrite , Last }
Accumulate mode informs the baker how samples should be accumulated into the buffer.
enum class EComponents { Float1 = 1 , Float2 = 2 , Float3 = 3 , Float4 = 4 }
The number of float components of an evaluator result/target.
Static Protected Member Functions inherited from UE::Geometry::FMeshMapEvaluator
static void WriteToBuffer (float *&Out, const float Data)
Write float data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector2f &Data)
Write FVector2f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector3f &Data)
Write FVector3f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector4f &Data)
Write FVector4f data to a float buffer and increment.
Detailed Description
A mesh evaluator for mesh properties as color data.
Definition at line 32 of file MeshPropertyMapEvaluator.h.
Member Typedef Documentation
FNormalTexture
using UE::Geometry::FMeshPropertyMapEvaluator::FNormalTexture = IMeshBakerDetailSampler::FBakeDetailNormalTexture protected
Definition at line 66 of file MeshPropertyMapEvaluator.h.
FNormalTextureMap
using UE::Geometry::FMeshPropertyMapEvaluator::FNormalTextureMap = TMap<const void*, FNormalTexture> protected
Definition at line 67 of file MeshPropertyMapEvaluator.h.
Constructor & Destructor Documentation
FMeshPropertyMapEvaluator() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FMeshPropertyMapEvaluator::FMeshPropertyMapEvaluator () default
Referenced by FMeshPropertyMapEvaluator(), and operator=().
FMeshPropertyMapEvaluator() [2/2]
UE::Geometry::FMeshPropertyMapEvaluator::FMeshPropertyMapEvaluator (const FMeshPropertyMapEvaluator &) default
References FMeshPropertyMapEvaluator().
Member Function Documentation
DataLayout()
virtual DYNAMICMESH_API const TArray< EComponents > & UE::Geometry::FMeshPropertyMapEvaluator::DataLayout () const override virtual
Returns
the data layout of the evaluator
Implements UE::Geometry::FMeshMapEvaluator.
References UE_API.
EvaluateChannel()
DYNAMICMESH_API void UE::Geometry::FMeshPropertyMapEvaluator::EvaluateChannel (const int DataIdx, float *& In, float & Out, void * EvalData) static
References UE_API.
EvaluateColor()
DYNAMICMESH_API void UE::Geometry::FMeshPropertyMapEvaluator::EvaluateColor (const int DataIdx, float *& In, FVector4f & Out, void * EvalData) static
References UE_API.
EvaluateDefault()
DYNAMICMESH_API void UE::Geometry::FMeshPropertyMapEvaluator::EvaluateDefault (float *& Out, void * EvalData) static
References UE_API.
EvaluateSample()
template<bool bUseDetailNormalMap> void UE::Geometry::FMeshPropertyMapEvaluator::EvaluateSample (float *& Out, const FCorrespondenceSample & Sample, void * EvalData) static
GetDefaultValue()
DYNAMICMESH_API FVector4f UE::Geometry::FMeshPropertyMapEvaluator::GetDefaultValue (EMeshPropertyMapType InProperty) const protected
References UE_API.
NormalToColor()
FVector4f UE::Geometry::FMeshPropertyMapEvaluator::NormalToColor (const FVector3f Normal) inline static private
Definition at line 77 of file MeshPropertyMapEvaluator.h.
References UE::Geometry::Normal, NormalToColor(), and UE::Math::TVector< float >::One().
Referenced by NormalToColor().
operator=()
FMeshPropertyMapEvaluator & UE::Geometry::FMeshPropertyMapEvaluator::operator= (const FMeshPropertyMapEvaluator &) default
References FMeshPropertyMapEvaluator(), PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_API.
PositionToColor()
FVector4f UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor (const FVector3d Position, const FAxisAlignedBox3d SafeBounds) inline static private
Definition at line 89 of file MeshPropertyMapEvaluator.h.
References UE::Geometry::TAxisAlignedBox3< RealType >::Depth(), UE::Geometry::TAxisAlignedBox3< RealType >::Height(), UE::Geometry::TAxisAlignedBox3< RealType >::Min, UE::Geometry::Position, UE::Geometry::TAxisAlignedBox3< RealType >::Width(), UE::Math::TVector< T >::X, X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
SampleFunction()
template<bool bUseDetailNormalMap> FVector4f UE::Geometry::FMeshPropertyMapEvaluator::SampleFunction (const FCorrespondenceSample & SampleData) const private
Setup()
DYNAMICMESH_API virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void UE::Geometry::FMeshPropertyMapEvaluator::Setup (const FMeshBaseBaker & Baker, FEvaluationContext & Context) override virtual
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
The evaluation context indicates to the baker how the evaluator should be invoked. See FEvaluationContext for more details.
Parameters
Baker the baker that owns this evaluator.
Context [out] the evaluation context.
Implements UE::Geometry::FMeshMapEvaluator.
Type()
virtual EMeshMapEvaluatorType UE::Geometry::FMeshPropertyMapEvaluator::Type () const inline override virtual
Returns
the type of evaluator.
Implements UE::Geometry::FMeshMapEvaluator.
Definition at line 49 of file MeshPropertyMapEvaluator.h.
References UE::Geometry::Property.
UE_DEPRECATED()
UE::Geometry::FMeshPropertyMapEvaluator::UE_DEPRECATED (5. 6, "DefaultValue is deprecated. Please use GetDefaultValue() instead.") protected
References Zero.
UVToColor()
FVector4f UE::Geometry::FMeshPropertyMapEvaluator::UVToColor (const FVector2f UV) inline static private
Definition at line 82 of file MeshPropertyMapEvaluator.h.
References TMathUtil< float >::Clamp(), UV, X, and Y.
Field Documentation
bHasDetailNormalTextures
bool UE::Geometry::FMeshPropertyMapEvaluator::bHasDetailNormalTextures = false protected
Definition at line 70 of file MeshPropertyMapEvaluator.h.
Bounds
FAxisAlignedBox3d UE::Geometry::FMeshPropertyMapEvaluator::Bounds protected
Definition at line 71 of file MeshPropertyMapEvaluator.h.
DefaultValue4f
FVector4f UE::Geometry::FMeshPropertyMapEvaluator::DefaultValue4f = FVector4f() private
Definition at line 100 of file MeshPropertyMapEvaluator.h.
DetailNormalMaps
FNormalTextureMap UE::Geometry::FMeshPropertyMapEvaluator::DetailNormalMaps protected
Definition at line 68 of file MeshPropertyMapEvaluator.h.
DetailSampler
const IMeshBakerDetailSampler* UE::Geometry::FMeshPropertyMapEvaluator::DetailSampler = nullptr protected
Definition at line 64 of file MeshPropertyMapEvaluator.h.
Property
EMeshPropertyMapType UE::Geometry::FMeshPropertyMapEvaluator::Property = EMeshPropertyMapType::Normal
Definition at line 35 of file MeshPropertyMapEvaluator.h.
The documentation for this class was generated from the following file:
MeshPropertyMapEvaluator.h