Unreal Engine 5.6 C++ API: UE::Geometry::TSparseGrid2< ElemType > Class Template Reference
UE::Geometry::TSparseGrid2< ElemType > Class Template Reference
Dynamic sparse 2D grid.
#include "SparseGrid2.h"
Public Member Functions
TSparseGrid2 ()
Create empty grid.
TSparseGrid2 (const TSparseGrid2 &Other)=delete
TSparseGrid2 (TSparseGrid2 &&Other) noexcept
~TSparseGrid2 ()
Deletes all grid elements.
template<typename Func>
void AllocatedIteration (Func ElementFunc) const
Iterate over existing elements and apply ElementFunc(ElementType) to each of them.
bool Free (const FVector2i &Index)
Delete an element in the grid.
void FreeAll ()
Delete all elements in the grid.
const ElemType * Get (const FVector2i &Index) const
Get the grid element at this index.
ElemType * Get (const FVector2i &Index, bool bAllocateIfMissing)
Get the grid element at this index, and optionally allocate it if it doesn't exist.
SIZE_T GetAllocatedSize () const
FAxisAlignedBox2i GetBoundsInclusive () const
int GetCount () const
float GetDensity () const
FVector2i GetDimensions () const
bool Has (const FVector2i &Index) const
TSparseGrid2 & operator= (const TSparseGrid2 &Other)=delete
TSparseGrid2 & operator= (TSparseGrid2 &&Other) noexcept
template<typename Func>
void RangeIteration (FVector2i MinIndex, FVector2i MaxIndex, Func ElementFunc) const
Iterate over existing allocated elements within the integer bounds defined by Min and Max (inclusive), and apply ElementFunc(ElementType) to each of them.
Protected Member Functions
ElemType * Allocate (const FVector2i &index)
Protected Attributes
FAxisAlignedBox2i Bounds
accumulated bounds of all indices inserted into Elements.
TMap< FVector2i, ElemType * > Elements
sparse grid of allocated elements
Detailed Description
template<typename ElemType>
class UE::Geometry::TSparseGrid2< ElemType >
Dynamic sparse 2D grid.
Useful in cases where we have grid of some type of non-trivial object and we don't want to pre-allocate full grid of them. So we allocate on-demand. This can be used to implement multi-grid schemes, eg for example the ElemType could be sub-grid of fixed dimension.
Todo
support pooling/re-use of allocated elements? currently not required by any use cases.
port AllocatedIndices() and Allocated() iterators
Definition at line 26 of file SparseGrid2.h.
Constructor & Destructor Documentation
TSparseGrid2() [1/3]
template<typename ElemType> UE::Geometry::TSparseGrid2< ElemType >::TSparseGrid2 () inline
Create empty grid.
Definition at line 39 of file SparseGrid2.h.
References Bounds, and UE::Geometry::FAxisAlignedBox2i::Empty().
Referenced by TSparseGrid2(), TSparseGrid2(), operator=(), and operator=().
~TSparseGrid2()
template<typename ElemType> UE::Geometry::TSparseGrid2< ElemType >::~TSparseGrid2 () inline
Deletes all grid elements.
Definition at line 47 of file SparseGrid2.h.
References FreeAll().
TSparseGrid2() [2/3]
template<typename ElemType> UE::Geometry::TSparseGrid2< ElemType >::TSparseGrid2 (const TSparseGrid2< ElemType > & Other) delete
References TSparseGrid2(), and Other.
TSparseGrid2() [3/3]
template<typename ElemType> UE::Geometry::TSparseGrid2< ElemType >::TSparseGrid2 (TSparseGrid2< ElemType > && Other) inline noexcept
Definition at line 55 of file SparseGrid2.h.
References TSparseGrid2(), and Other.
Member Function Documentation
Allocate()
template<typename ElemType> ElemType * UE::Geometry::TSparseGrid2< ElemType >::Allocate (const FVector2i & index) inline protected
Definition at line 212 of file SparseGrid2.h.
References Bounds, and Elements.
Referenced by Get().
AllocatedIteration()
template<typename ElemType> template<typename Func> void UE::Geometry::TSparseGrid2< ElemType >::AllocatedIteration (Func ElementFunc) const inline
Iterate over existing elements and apply ElementFunc(ElementType) to each of them.
Definition at line 176 of file SparseGrid2.h.
References Elements.
Free()
template<typename ElemType> bool UE::Geometry::TSparseGrid2< ElemType >::Free (const FVector2i & Index) inline
Delete an element in the grid.
Parameters
Index integer grid index
Returns
true if the element existed, false if it did not
Definition at line 116 of file SparseGrid2.h.
References Elements.
FreeAll()
template<typename ElemType> void UE::Geometry::TSparseGrid2< ElemType >::FreeAll () inline
Delete all elements in the grid.
Definition at line 130 of file SparseGrid2.h.
References Elements.
Referenced by ~TSparseGrid2().
Get() [1/2]
template<typename ElemType> const ElemType * UE::Geometry::TSparseGrid2< ElemType >::Get (const FVector2i & Index) const inline
Get the grid element at this index.
Parameters
Index integer grid index
Returns
pointer to ElemType instance, or nullptr if element doesn't exist
Definition at line 85 of file SparseGrid2.h.
References Elements.
Get() [2/2]
template<typename ElemType> ElemType * UE::Geometry::TSparseGrid2< ElemType >::Get (const FVector2i & Index, bool bAllocateIfMissing) inline
Get the grid element at this index, and optionally allocate it if it doesn't exist.
Parameters
Index integer grid index
bAllocateIfMissing if the element at this index is null, allocate a new one
Returns
pointer to ElemType instance, or nullptr if element doesn't exist
Definition at line 97 of file SparseGrid2.h.
References Allocate(), and Elements.
GetAllocatedSize()
template<typename ElemType> SIZE_T UE::Geometry::TSparseGrid2< ElemType >::GetAllocatedSize () const inline
Definition at line 205 of file SparseGrid2.h.
References Elements, and GetCount().
GetBoundsInclusive()
template<typename ElemType> FAxisAlignedBox2i UE::Geometry::TSparseGrid2< ElemType >::GetBoundsInclusive () const inline
Returns
integer range of valid grid indices [min,max] (inclusive)
Definition at line 158 of file SparseGrid2.h.
References Bounds.
GetCount()
template<typename ElemType> int UE::Geometry::TSparseGrid2< ElemType >::GetCount () const inline
Returns
number of allocated elements in the grid
Definition at line 142 of file SparseGrid2.h.
References Elements.
Referenced by GetAllocatedSize().
GetDensity()
template<typename ElemType> float UE::Geometry::TSparseGrid2< ElemType >::GetDensity () const inline
Returns
ratio of allocated elements to total number of possible cells for current bounds
Definition at line 150 of file SparseGrid2.h.
References Bounds, Elements, and float.
GetDimensions()
template<typename ElemType> FVector2i UE::Geometry::TSparseGrid2< ElemType >::GetDimensions () const inline
Returns
dimensions of grid along each axis
Definition at line 166 of file SparseGrid2.h.
References Bounds, and UE::Geometry::FVector2i::One().
Has()
template<typename ElemType> bool UE::Geometry::TSparseGrid2< ElemType >::Has (const FVector2i & Index) const inline
Parameters
Index an integer grid index
Returns
true if there is an allocated element at this index
Definition at line 74 of file SparseGrid2.h.
References Elements.
operator=() [1/2]
template<typename ElemType> TSparseGrid2 & UE::Geometry::TSparseGrid2< ElemType >::operator= (const TSparseGrid2< ElemType > & Other) delete
References TSparseGrid2(), and Other.
operator=() [2/2]
template<typename ElemType> TSparseGrid2 & UE::Geometry::TSparseGrid2< ElemType >::operator= (TSparseGrid2< ElemType > && Other) inline noexcept
Definition at line 59 of file SparseGrid2.h.
References TSparseGrid2(), Bounds, Elements, MoveTemp(), and Other.
RangeIteration()
template<typename ElemType> template<typename Func> void UE::Geometry::TSparseGrid2< ElemType >::RangeIteration (FVector2i MinIndex, FVector2i MaxIndex, Func ElementFunc) const inline
Iterate over existing allocated elements within the integer bounds defined by Min and Max (inclusive), and apply ElementFunc(ElementType) to each of them.
Definition at line 190 of file SparseGrid2.h.
References Elements, Found, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Field Documentation
Bounds
template<typename ElemType> FAxisAlignedBox2i UE::Geometry::TSparseGrid2< ElemType >::Bounds protected
accumulated bounds of all indices inserted into Elements.
Not currently used internally.
Definition at line 32 of file SparseGrid2.h.
Referenced by TSparseGrid2(), Allocate(), GetBoundsInclusive(), GetDensity(), GetDimensions(), and operator=().
Elements
template<typename ElemType> TMap<FVector2i, ElemType*> UE::Geometry::TSparseGrid2< ElemType >::Elements protected
sparse grid of allocated elements
Definition at line 30 of file SparseGrid2.h.
Referenced by Allocate(), AllocatedIteration(), Free(), FreeAll(), Get(), Get(), GetAllocatedSize(), GetCount(), GetDensity(), Has(), operator=(), and RangeIteration().
The documentation for this class was generated from the following file:
SparseGrid2.h