Unreal Engine 5.6 C++ API: FStructTypeBitSet::FBitSetContainer Struct Reference
FStructTypeBitSet::FBitSetContainer Struct Reference
A mutable extension of FConstBitSetContainer, adding methods for modifying bits.
#include "StructTypeBitSet.h"
Public Member Functions
FBitSetContainer ()=default
FBitSetContainer (const TBitArray<> &Source)
FBitSetContainer (TBitArray<> &&Source)
void AddAtIndex (const int32 Index)
Adds a bit at the specified index.
FConstBitSetContainer ()=default
FConstBitSetContainer (const TBitArray<> &Source)
Copy-constructor for creating a bitset from another bit array.
FConstBitSetContainer (TBitArray<> &&Source)
Move-constructor for creating a bitset from another bit array.
FORCEINLINE void operator-= (const TBitArray<> &Other)
Removes bits set in the Other bit array from this bitset.
FBitSetContainer & operator= (const TBitArray<> &Other)
void RemoveAtIndex (const int32 Index)
Removes a bit at the specified index.
void SetAll (const bool bValue, const int32 Count)
Initializes the bitset to a specified size and value.
Public Member Functions inherited from FStructTypeBitSet::FConstBitSetContainer
FConstBitSetContainer ()=default
bool Contains (const int32 Index) const
Checks if a specific bit is set in the bitset.
int32 CountStoredTypes () const
Counts the number of set bits in the bitset.
FORCEINLINE bool HasAll (const TBitArray<> &Other) const
Checks if all bits set in the Other bit array are also set in this bitset.
FORCEINLINE bool HasAny (const TBitArray<> &Other) const
Checks if any bits in the Other bit array are also set in this bitset.
FORCEINLINE bool IsEmpty () const
bool operator== (const FConstBitSetContainer &Other) const
Compares two bitsets for equality.
Public Member Functions inherited from TBitArray<>
TBitArray ()
FORCEINLINE TBitArray (bool bValue, int32 InNumBits)
Minimal initialization constructor.
FORCEINLINE TBitArray (const TBitArray &Copy)
Copy constructor.
FORCEINLINE TBitArray (const TBitArray< OtherAllocator > &Copy)
FORCEINLINE TBitArray (TBitArray &&Other)
Move constructor.
FORCEINLINE FBitReference AccessCorrespondingBit (const FRelativeBitReference &RelativeReference)
FORCEINLINE const FConstBitReference AccessCorrespondingBit (const FRelativeBitReference &RelativeReference) const
int32 Add (const bool Value)
Adds a bit to the array with the given value.
int32 Add (const bool Value, int32 NumBitsToAdd)
Adds multiple bits to the array with the given value.
int32 AddRange (const InWordType *ReadBits, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Adds multiple bits read from the given pointer.
int32 AddRange (const TBitArray< OtherAllocator > &ReadBits, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Adds multiple bits read from the given BitArray.
int32 AddUninitialized (int32 NumBitsToAdd)
Inserts space for multiple bits at the end of the array.
FORCEINLINE FIterator begin ()
Enables range-based for loops, DO NOT USE DIRECTLY.
FORCEINLINE FConstIterator begin () const
void BitwiseNOT ()
Perform a bitwise NOT on all the bits in this array.
void CheckInvariants () const
Checks the invariants of this class.
TBitArray & CombineWithBinaryOp (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags, BinaryOpType &&InBinaryOp)
Perform a custom bitwise operation on this bit array with another.
TBitArray & CombineWithBitwiseAND (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags)
Perform a bitwise AND on this bit array with another.
TBitArray & CombineWithBitwiseOR (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags)
Return the bitwise OR of two bit arrays.
TBitArray & CombineWithBitwiseXOR (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags)
Return the bitwise XOR of two bit arrays.
bool CompareSetBits (const TBitArray< OtherAllocator > &Other, const bool bMissingBitValue) const
Returns true if Other contains all the same set bits as this, accounting for differences in length.
FORCEINLINE bool Contains (bool bValue) const
Checks if the array contains the specified value (true/false).
void CountBytes (FArchive &Ar) const
Tracks the container's memory use through an archive.
int32 CountSetBits (int32 FromIndex=0, int32 ToIndex=INDEX_NONE) const
Count the number of set bits in this array FromIndex <= bit < ToIndex.
void Empty (int32 ExpectedNumBits=0)
Removes all bits from the array, potentially leaving space allocated for an expected number of bits about to be added.
FORCEINLINE FIterator end ()
FORCEINLINE FConstIterator end () const
int32 Find (bool bValue) const
Finds the first occurrence of the specified value (true/false) in the array, and returns the bit index.
int32 FindAndSetFirstZeroBit (int32 StartIndex=0)
Finds the first occurrence of a zero bit in the array and sets it to one, returning the bit index.
int32 FindAndSetLastZeroBit ()
Finds the last occurrence of a zero bit in the array and sets it to one, returning the bit index.
FORCEINLINE int32 FindFrom (bool bValue, IndexType StartIndex) const
Finds the first occurrence of the specified value (true/false) in the array, starting from the given bit index, and returns the bit index.
int32 FindLast (bool bValue) const
Finds the last occurrence of the specified value (true/false) in the array, and returns the bit index.
int32 FindLastFrom (bool bValue, IndexType EndIndexInclusive) const
Finds the last occurrence of the specified value (true/false) in the array starting the (reverse) search from the given bit index, and returns the bit index.
uint32 GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container.
FORCEINLINE uint32 * GetData ()
FORCEINLINE const uint32 * GetData () const
FORCEINLINE void GetRange (int32 Index, int32 NumBitsToGet, InWordType *WriteBits, int32 WriteOffsetBits=0) const
Reads a range of bits within the array and writes them to the given pointer.
FORCEINLINE void Init (bool bValue, int32 InNumBits)
Resets the array's contents.
void Insert (bool Value, int32 Index)
Adds a bit with the given value at the given index in the array.
void Insert (bool Value, int32 Index, int32 NumBitsToAdd)
Inserts multiple bits with the given value into the array, starting at the given Index.
void InsertRange (const InWordType *ReadBits, int32 Index, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Inserts multiple bits read from the given pointer, starting at the given index.
void InsertRange (const TBitArray< OtherAllocator > &ReadBits, int32 Index, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Inserts multiple bits read from the given BitArray into the array, starting at the given index.
void InsertUninitialized (int32 Index, int32 NumBitsToAdd)
Inserts space for multiple bits into the array, starting at the given index.
bool IsEmpty () const
Returns true if the bit array is empty and contains no elements.
FORCEINLINE bool IsValidIndex (int32 InIndex) const
FORCEINLINE int32 Max () const
FORCEINLINE int32 Num () const
FORCEINLINE bool operator!= (const TBitArray< Allocator > &Other) const
FORCEINLINE bool operator< (const TBitArray< Allocator > &Other) const
FORCEINLINE TBitArray & operator= (const TBitArray &Copy)
Assignment operator.
FORCEINLINE TBitArray & operator= (const TBitArray< OtherAllocator > &Copy)
FORCEINLINE TBitArray & operator= (TBitArray &&Other)
Move assignment.
FORCEINLINE bool operator== (const TBitArray< Allocator > &Other) const
FORCEINLINE FBitReference operator[] (int32 Index)
FORCEINLINE const FConstBitReference operator[] (int32 Index) const
int32 PadToNum (int32 DesiredNum, bool bPadValue)
Pad this bit array with the specified value to ensure that it is at least the specified length.
FORCEINLINE FReverseIterator rbegin ()
FORCEINLINE FConstReverseIterator rbegin () const
void RemoveAt (int32 BaseIndex, int32 NumBitsToRemove=1)
Removes bits from the array.
void RemoveAtSwap (int32 BaseIndex, int32 NumBitsToRemove=1)
FORCEINLINE FReverseIterator rend ()
FORCEINLINE FConstReverseIterator rend () const
void Reserve (int32 Number)
Reserves memory such that the array can contain at least Number bits.
void Reset ()
Removes all bits from the array retaining any space already allocated.
void Serialize (FArchive &Ar)
Serializer.
FORCENOINLINE void SetNum (int32 InNumBits, ValueType bValue)
Sets the number of bits, initializing any potentially added bits to the given value.
void SetNumUninitialized (int32 InNumBits)
Sets number of bits without initializing new bits.
FORCENOINLINE void SetRange (int32 Index, int32 NumBitsToSet, bool Value)
Sets or unsets a range of bits within the array.
void SetRangeFromRange (int32 Index, int32 NumBitsToSet, const InWordType *ReadBits, int32 ReadOffsetBits=0)
Sets range of bits within the TBitArray to the values read out of a pointer.
FORCEINLINE void SetRangeFromRange (int32 Index, int32 NumBitsToSet, const TBitArray< OtherAllocator > &ReadBits, int32 ReadOffsetBits=0)
Sets range of bits within this TBitArray to the values read out another TBitArray.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Protected Member Functions
void SetBitNoCheck (const int32 Index, const bool Value)
Directly sets a bit without boundary checks for improved performance.
Protected Member Functions inherited from FStructTypeBitSet::FConstBitSetContainer
FConstBitSetContainer (const TBitArray<> &Source)
Copy-constructor for creating a bitset from another bit array.
FConstBitSetContainer (TBitArray<> &&Source)
Move-constructor for creating a bitset from another bit array.
Additional Inherited Members
Public Types inherited from FStructTypeBitSet::FConstBitSetContainer
using Super = TBitArray<>
Public Types inherited from TBitArray<>
typedef Allocator::template ForElementType< uint32 > AllocatorType
Static Public Member Functions inherited from TBitArray<>
static TBitArray BitwiseAND (const TBitArray< AllocatorA > &A, const TBitArray< AllocatorB > &B, EBitwiseOperatorFlags InFlags)
Return the bitwise AND of two bit arrays.
static TBitArray BitwiseOR (const TBitArray< AllocatorA > &A, const TBitArray< AllocatorB > &B, EBitwiseOperatorFlags InFlags)
Return the bitwise OR of two bit arrays.
static TBitArray BitwiseXOR (const TBitArray< AllocatorA > &A, const TBitArray< AllocatorB > &B, EBitwiseOperatorFlags InFlags)
Return the bitwise XOR of two bit arrays.
Detailed Description
A mutable extension of FConstBitSetContainer, adding methods for modifying bits.
Definition at line 170 of file StructTypeBitSet.h.
Constructor & Destructor Documentation
FBitSetContainer() [1/3]
FStructTypeBitSet::FBitSetContainer::FBitSetContainer () default
Referenced by operator=().
FBitSetContainer() [2/3]
FStructTypeBitSet::FBitSetContainer::FBitSetContainer (const TBitArray<> & Source) inline explicit
Definition at line 176 of file StructTypeBitSet.h.
References FConstBitSetContainer(), and Source.
FBitSetContainer() [3/3]
FStructTypeBitSet::FBitSetContainer::FBitSetContainer (TBitArray<> && Source) inline explicit
Definition at line 180 of file StructTypeBitSet.h.
References TBitArray<>::TBitArray(), FConstBitSetContainer(), Forward(), and Source.
Member Function Documentation
AddAtIndex()
void FStructTypeBitSet::FBitSetContainer::AddAtIndex (const int32 Index) inline
Adds a bit at the specified index.
Parameters
Index - The index of the bit to add
Definition at line 226 of file StructTypeBitSet.h.
References check, TBitArray<>::PadToNum(), and SetBitNoCheck().
FConstBitSetContainer() [1/3]
FStructTypeBitSet::FConstBitSetContainer::FConstBitSetContainer () default
Referenced by FBitSetContainer(), and FBitSetContainer().
FConstBitSetContainer() [2/3]
FStructTypeBitSet::FConstBitSetContainer::FConstBitSetContainer (const TBitArray<> & Source) inline explicit
Copy-constructor for creating a bitset from another bit array.
Parameters
Source - The source bit array
Definition at line 152 of file StructTypeBitSet.h.
FConstBitSetContainer() [3/3]
FStructTypeBitSet::FConstBitSetContainer::FConstBitSetContainer (TBitArray<> && Source) inline explicit
Move-constructor for creating a bitset from another bit array.
Parameters
Source - The source bit array to move from
Definition at line 161 of file StructTypeBitSet.h.
operator-=()
FORCEINLINE void FStructTypeBitSet::FBitSetContainer::operator-= (const TBitArray<> & Other) inline
Removes bits set in the Other bit array from this bitset.
Parameters
Other - The bit array to remove
Definition at line 208 of file StructTypeBitSet.h.
References FORCEINLINE, and Other.
operator=()
FBitSetContainer & FStructTypeBitSet::FBitSetContainer::operator= (const TBitArray<> & Other) inline
Definition at line 185 of file StructTypeBitSet.h.
References FBitSetContainer(), and Other.
RemoveAtIndex()
void FStructTypeBitSet::FBitSetContainer::RemoveAtIndex (const int32 Index) inline
Removes a bit at the specified index.
Parameters
Index - The index of the bit to remove
Definition at line 237 of file StructTypeBitSet.h.
References check, TBitArray<>::Num(), and SetBitNoCheck().
SetAll()
void FStructTypeBitSet::FBitSetContainer::SetAll (const bool bValue, const int32 Count) inline
Initializes the bitset to a specified size and value.
Parameters
bValue - The value to set all bits to
Count - The number of bits to initialize
Definition at line 199 of file StructTypeBitSet.h.
References Count, and Init.
SetBitNoCheck()
void FStructTypeBitSet::FBitSetContainer::SetBitNoCheck (const int32 Index, const bool Value) inline protected
Directly sets a bit without boundary checks for improved performance.
Parameters
Index - The index of the bit to set.
Value - The value to set the bit to.
Definition at line 253 of file StructTypeBitSet.h.
References TBitArray<>::GetData(), NumBitsPerDWORD, Value, and Word.
Referenced by AddAtIndex(), and RemoveAtIndex().
The documentation for this struct was generated from the following file:
StructTypeBitSet.h