Unreal Engine 5.6 C++ API: SkeletalMeshComponent.h File Reference
SkeletalMeshComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "Engine/EngineBaseTypes.h"
#include "Components/SceneComponent.h"
#include "EngineDefines.h"
#include "CollisionQueryParams.h"
#include "Interfaces/Interface_CollisionDataProvider.h"
#include "Animation/AnimationAsset.h"
#include "Animation/AnimCurveTypes.h"
#include "Components/SkinnedMeshComponent.h"
#include "ClothSimData.h"
#include "SingleAnimationPlayData.h"
#include "Animation/PoseSnapshot.h"
#include "ClothingSystemRuntimeTypes.h"
#include "ClothingSimulationInterface.h"
#include "ClothingSimulationFactory.h"
#include "Animation/AttributesRuntime.h"
#include "Chaos/Serialization/SerializedDataBuffer.h"
#include "SkeletalMeshComponent.generated.h"
Data Structures
struct FAnimationEvaluationContext
Method used when retrieving a attribute value.
struct FClosestPointOnPhysicsAsset
struct FLinkedInstancesAdapter
struct FPoseWatchDynamicData
struct TStructOpsTypeTraits< FSkeletalMeshComponentClothTickFunction >
Tick function that prepares and simulates cloth.
struct TStructOpsTypeTraits< FSkeletalMeshComponentEndPhysicsTickFunction >
Tick function that does post physics work on skeletal mesh component.
class USkeletalMeshComponent
struct USkeletalMeshComponent::FPendingRadialForces
Namespaces
namespace Chaos
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::AnimNext
Synchronization Role.
Macros
#define WITH_CLOTH_COLLISION_DETECTION 1
Typedefs
typedef FOnLODRequiredBonesUpdateMulticast::FDelegate FOnLODRequiredBonesUpdate
typedef FOnSkelMeshPhysicsCreatedMultiCast::FDelegate FOnSkelMeshPhysicsCreated
typedef FOnSkelMeshTeleportedMultiCast::FDelegate FOnSkelMeshTeleported
Enumerations
enum class EAllowKinematicDeferral { AllowDeferral , DisallowDeferral }
Enum for indicating whether kinematic updates can be deferred.
Functions
DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnAnimInitialized)
DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnBoneTransformsFinalized)
DECLARE_MULTICAST_DELEGATE (FOnSkelMeshPhysicsCreatedMultiCast)
DECLARE_MULTICAST_DELEGATE (FOnSkelMeshTeleportedMultiCast)
DECLARE_TS_MULTICAST_DELEGATE_ThreeParams (FOnLODRequiredBonesUpdateMulticast, USkeletalMeshComponent *, int32, const TArray< FBoneIndexType > &)
UCLASS ()
SkeletalMeshComponent is used to create an instance of an animated SkeletalMesh asset.
class UE_DEPRECATED (5.5, "use FOnBoneTransformsFinalizedMultiCast instead (see SkinnedMeshComponent.h).") FOnBoneTransformsFinalized
UENUM () namespace EKinematicBonesUpdateToPhysics
This enum defines how you'd like to update bones to physics world.
Variables
config =Engine
editinlinenew
hidecategories =(Object, "Mesh|SkeletalAsset")
meta =(BlueprintSpawnableComponent)
Macro Definition Documentation
WITH_CLOTH_COLLISION_DETECTION
#define WITH_CLOTH_COLLISION_DETECTION 1
Definition at line 53 of file SkeletalMeshComponent.h.
Typedef Documentation
FOnLODRequiredBonesUpdate
typedef FOnLODRequiredBonesUpdateMulticast::FDelegate FOnLODRequiredBonesUpdate
Definition at line 68 of file SkeletalMeshComponent.h.
FOnSkelMeshPhysicsCreated
typedef FOnSkelMeshPhysicsCreatedMultiCast::FDelegate FOnSkelMeshPhysicsCreated
Definition at line 57 of file SkeletalMeshComponent.h.
FOnSkelMeshTeleported
typedef FOnSkelMeshTeleportedMultiCast::FDelegate FOnSkelMeshTeleported
Definition at line 62 of file SkeletalMeshComponent.h.
Enumeration Type Documentation
EAllowKinematicDeferral
enum class EAllowKinematicDeferral strong
Enum for indicating whether kinematic updates can be deferred.
Enumerator
AllowDeferral
DisallowDeferral
Definition at line 205 of file SkeletalMeshComponent.h.
Function Documentation
DECLARE_DYNAMIC_MULTICAST_DELEGATE() [1/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnAnimInitialized)
DECLARE_DYNAMIC_MULTICAST_DELEGATE() [2/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnBoneTransformsFinalized)
DECLARE_MULTICAST_DELEGATE() [1/2]
DECLARE_MULTICAST_DELEGATE (FOnSkelMeshPhysicsCreatedMultiCast)
DECLARE_MULTICAST_DELEGATE() [2/2]
DECLARE_MULTICAST_DELEGATE (FOnSkelMeshTeleportedMultiCast)
DECLARE_TS_MULTICAST_DELEGATE_ThreeParams()
DECLARE_TS_MULTICAST_DELEGATE_ThreeParams (FOnLODRequiredBonesUpdateMulticast , USkeletalMeshComponent * , int32 , const TArray< FBoneIndexType > &)
UCLASS()
UCLASS ()
SkeletalMeshComponent is used to create an instance of an animated SkeletalMesh asset.
See also
https://docs.unrealengine.com/latest/INT/Engine/Content/Types/SkeletalMeshes/
USkeletalMesh
UE_DEPRECATED()
class UE_DEPRECATED (5. 5, "use FOnBoneTransformsFinalizedMultiCast instead (see SkinnedMeshComponent.h).")
UENUM()
UENUM ()
This enum defines how you'd like to update bones to physics world.
If bone is simulating, you don't have to waste time on updating bone transform from kinematic. But also sometimes you don't like fixed bones to be updated by animation data.
Update any bones that are not simulating.
Skip physics update from kinematic changes.
Definition at line 170 of file SkeletalMeshComponent.h.
Variable Documentation
config
config =Engine
Definition at line 313 of file SkeletalMeshComponent.h.
editinlinenew
editinlinenew
Definition at line 313 of file SkeletalMeshComponent.h.
hidecategories
hidecategories =(Object, "Mesh|SkeletalAsset")
Definition at line 313 of file SkeletalMeshComponent.h.
meta
meta =(BlueprintSpawnableComponent)
Definition at line 313 of file SkeletalMeshComponent.h.
Referenced by USkeletalMeshComponent::GetSharedRequiredBones(), USkeletalMeshComponent::UE::AnimNext::FDataRegistry, USkeletalMeshComponent::UE_DEPRECATED(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UFUNCTION(), USkeletalMeshComponent::UPROPERTY(), USkeletalMeshComponent::UPROPERTY(), USkeletalMeshComponent::UPROPERTY(), USkeletalMeshComponent::UPROPERTY(), USkeletalMeshComponent::UPROPERTY(), USkeletalMeshComponent::UPROPERTY(), and USkeletalMeshComponent::UPROPERTY().