Unreal Engine 5.6 C++ API: FSlateTextBlockLayout Class Reference
FSlateTextBlockLayout Class Reference
Class to handle the cached layout of STextBlock/SRichTextBlock by proxying around a FTextLayout.
#include "SlateTextBlockLayout.h"
Data Structures
struct FWidgetDesiredSizeArgs
Public Member Functions
FSlateTextBlockLayout (SWidget *InOwner, FTextBlockStyle InDefaultTextStyle, const TOptional< ETextShapingMethod > InTextShapingMethod, const TOptional< ETextFlowDirection > InTextFlowDirection, const FCreateSlateTextLayout &InCreateSlateTextLayout, TSharedRef< ITextLayoutMarshaller > InMarshaller, TSharedPtr< IBreakIterator > InLineBreakPolicy)
Constructor.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const
Arrange any child widgets in this layout.
FVector2D ComputeDesiredSize (const FWidgetDesiredSizeArgs &InWidgetArgs, const float InScale)
Get the computed desired size for this layout, updating the internal cache as required.
FVector2D ComputeDesiredSize (const FWidgetDesiredSizeArgs &InWidgetArgs, const float InScale, const FTextBlockStyle &InTextStyle)
Get the computed desired size for this layout, updating the internal cache as required.
void ConditionallyUpdateTextStyle (const FTextBlockStyle &InTextStyle)
Conditionally update the text style if needed.
void ConditionallyUpdateTextStyle (const FTextBlockStyle::CompareParams &InNewStyleParams)
Conditionally update the text style if needed.
void DirtyContent ()
Force dirty the content due to an external change that can't be picked up automatically by this cache.
void DirtyLayout ()
Force dirty the layout due to an external change that can't be picked up automatically by this cache.
FChildren * GetChildren ()
Get the child widgets of this layout.
PRAGMA_ENABLE_DEPRECATION_WARNINGS FVector2D GetDesiredSize () const
Gets the last computed desired size.
float GetLayoutScale () const
Get the TextLayout scale.
int32 OnPaint (const FPaintArgs &InPaintArgs, const FGeometry &InAllottedGeometry, const FSlateRect &InClippingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled)
Paint this layout, updating the internal cache as required.
void OverrideTextStyle (const FTextBlockStyle &InTextStyle)
Override the text style used and immediately update the text layout (if required).
void SetDebugSourceInfo (const TAttribute< FString > &InDebugSourceInfo)
Set the information used to help identify who owns this text layout in the case of an error.
void SetTextFlowDirection (const TOptional< ETextFlowDirection > &InTextFlowDirection)
Set the text flow direction that the internal text layout should use.
void SetTextOverflowPolicy (const TOptional< ETextOverflowPolicy > InTextOverflowPolicy)
Set the text overflow policy that the internal text layout should use.
void SetTextShapingMethod (const TOptional< ETextShapingMethod > &InTextShapingMethod)
Set the text shaping method that the internal text layout should use.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.0, "FWidgetArgs is deprecated. Upgrade to FWidgetDesiredSizeArgs instead.") 1 FVector2D ComputeDesiredSize(const FWidgetArgs &InWidgetArgs
Get the computed desired size for this layout, updating the internal cache as required.
struct UE_DEPRECATED (5.0, "FWidgetArgs is deprecated. Upgrade to FWidgetDesiredSizeArgs instead.") FWidgetArgs
void UpdateTextStyle (const FTextBlockStyle &InTextStyle)
Update the text style.
void UpdateTextStyle (const FTextBlockStyle::CompareParams &InNewStyleParams)
Update the text style.
Data Fields
PRAGMA_DISABLE_DEPRECATION_WARNINGS const float InScale
PRAGMA_DISABLE_DEPRECATION_WARNINGS const float const FTextBlockStyle & InTextStyle
Private Member Functions
float CalculateWrappingWidth () const
Calculate the wrapping width based on the given fixed wrap width, and whether we're auto-wrapping.
bool IsStyleUpToDate (const FTextBlockStyle &NewStyle) const
Is the style used by the text marshaller up-to-date?
bool IsStyleUpToDate (const FTextBlockStyle::CompareParams &InNewStyleParams) const
Is the style used by the text marshaller up-to-date?
void UpdateTextHighlights (const FText &InHighlightText)
Update the text highlights.
void UpdateTextLayout (const FString &InText)
Updates the text layout to contain the given string.
void UpdateTextLayout (const FText &InText)
Updates the text layout to contain the given text.
Private Attributes
bool bCachedAutoWrapText
Cache the auto wrap text value.
FVector2f CachedSize
The last known size of the layout from the previous OnPaint, used to guess at an auto-wrapping width in ComputeDesiredSize.
float CachedWrapTextAt
Cache where to wrap text at?
FTextSnapshot HighlightTextLastUpdate
The state of the highlight text the last time it was updated (used to allow updates when the text is changed)
TSharedPtr< ITextLayoutMarshaller > Marshaller
The marshaller used to get/set the text to/from the text layout.
TSharedPtr< ISlateRunRenderer > TextHighlighter
Used to render the current highlights in the text layout.
FTextSnapshot TextLastUpdate
The state of the text the last time it was updated (used to allow updates when the text is changed)
TSharedPtr< FSlateTextLayout > TextLayout
In control of the layout and wrapping of the text.
Detailed Description
Class to handle the cached layout of STextBlock/SRichTextBlock by proxying around a FTextLayout.
Definition at line 20 of file SlateTextBlockLayout.h.
Constructor & Destructor Documentation
FSlateTextBlockLayout()
FSlateTextBlockLayout::FSlateTextBlockLayout (SWidget * InOwner, FTextBlockStyle InDefaultTextStyle, const TOptional< ETextShapingMethod > InTextShapingMethod, const TOptional< ETextFlowDirection > InTextFlowDirection, const FCreateSlateTextLayout & InCreateSlateTextLayout, TSharedRef< ITextLayoutMarshaller > InMarshaller, TSharedPtr< IBreakIterator > InLineBreakPolicy)
Constructor.
Member Function Documentation
ArrangeChildren()
void FSlateTextBlockLayout::ArrangeChildren (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren) const
Arrange any child widgets in this layout.
References ArrangeChildren().
Referenced by ArrangeChildren().
CalculateWrappingWidth()
float FSlateTextBlockLayout::CalculateWrappingWidth () const private
Calculate the wrapping width based on the given fixed wrap width, and whether we're auto-wrapping.
References CalculateWrappingWidth().
Referenced by CalculateWrappingWidth().
ComputeDesiredSize() [1/2]
FVector2D FSlateTextBlockLayout::ComputeDesiredSize (const FWidgetDesiredSizeArgs & InWidgetArgs, const float InScale)
Get the computed desired size for this layout, updating the internal cache as required.
References InScale.
ComputeDesiredSize() [2/2]
FVector2D FSlateTextBlockLayout::ComputeDesiredSize (const FWidgetDesiredSizeArgs & InWidgetArgs, const float InScale, const FTextBlockStyle & InTextStyle)
Get the computed desired size for this layout, updating the internal cache as required.
References InScale, InTextStyle, and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
ConditionallyUpdateTextStyle() [1/2]
void FSlateTextBlockLayout::ConditionallyUpdateTextStyle (const FTextBlockStyle & InTextStyle)
Conditionally update the text style if needed.
References InTextStyle.
ConditionallyUpdateTextStyle() [2/2]
void FSlateTextBlockLayout::ConditionallyUpdateTextStyle (const FTextBlockStyle::CompareParams & InNewStyleParams)
Conditionally update the text style if needed.
DirtyContent()
void FSlateTextBlockLayout::DirtyContent ()
Force dirty the content due to an external change that can't be picked up automatically by this cache.
Also force dirties the layout. Will cause the contained text to be re-parsed by the marshaller next frame.
References DirtyContent().
Referenced by DirtyContent().
DirtyLayout()
void FSlateTextBlockLayout::DirtyLayout ()
Force dirty the layout due to an external change that can't be picked up automatically by this cache.
References DirtyLayout().
Referenced by DirtyLayout().
GetChildren()
FChildren * FSlateTextBlockLayout::GetChildren ()
Get the child widgets of this layout.
References GetChildren().
Referenced by GetChildren().
GetDesiredSize()
PRAGMA_ENABLE_DEPRECATION_WARNINGS FVector2D FSlateTextBlockLayout::GetDesiredSize () const
Gets the last computed desired size.
References GetDesiredSize().
Referenced by GetDesiredSize().
GetLayoutScale()
float FSlateTextBlockLayout::GetLayoutScale () const
Get the TextLayout scale.
References GetLayoutScale().
Referenced by GetLayoutScale().
IsStyleUpToDate() [1/2]
bool FSlateTextBlockLayout::IsStyleUpToDate (const FTextBlockStyle & NewStyle) const private
Is the style used by the text marshaller up-to-date?
References IsStyleUpToDate().
Referenced by IsStyleUpToDate(), and IsStyleUpToDate().
IsStyleUpToDate() [2/2]
bool FSlateTextBlockLayout::IsStyleUpToDate (const FTextBlockStyle::CompareParams & InNewStyleParams) const private
Is the style used by the text marshaller up-to-date?
References IsStyleUpToDate().
OnPaint()
int32 FSlateTextBlockLayout::OnPaint (const FPaintArgs & InPaintArgs, const FGeometry & InAllottedGeometry, const FSlateRect & InClippingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled)
Paint this layout, updating the internal cache as required.
References OnPaint().
Referenced by OnPaint().
OverrideTextStyle()
void FSlateTextBlockLayout::OverrideTextStyle (const FTextBlockStyle & InTextStyle)
Override the text style used and immediately update the text layout (if required).
This can be used to override the text style after calling ComputeDesiredSize (eg, if you can only compute your text style in OnPaint) Please note that changing the size or font used by the text may causing clipping issues until the next call to ComputeDesiredSize
References InTextStyle, and OverrideTextStyle().
Referenced by OverrideTextStyle().
SetDebugSourceInfo()
void FSlateTextBlockLayout::SetDebugSourceInfo (const TAttribute< FString > & InDebugSourceInfo)
Set the information used to help identify who owns this text layout in the case of an error.
References SetDebugSourceInfo().
Referenced by SetDebugSourceInfo().
SetTextFlowDirection()
void FSlateTextBlockLayout::SetTextFlowDirection (const TOptional< ETextFlowDirection > & InTextFlowDirection)
Set the text flow direction that the internal text layout should use.
References SetTextFlowDirection().
Referenced by SetTextFlowDirection().
SetTextOverflowPolicy()
void FSlateTextBlockLayout::SetTextOverflowPolicy (const TOptional< ETextOverflowPolicy > InTextOverflowPolicy)
Set the text overflow policy that the internal text layout should use.
References SetTextOverflowPolicy().
Referenced by SetTextOverflowPolicy().
SetTextShapingMethod()
void FSlateTextBlockLayout::SetTextShapingMethod (const TOptional< ETextShapingMethod > & InTextShapingMethod)
Set the text shaping method that the internal text layout should use.
References SetTextShapingMethod().
Referenced by SetTextShapingMethod().
UE_DEPRECATED() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSlateTextBlockLayout::UE_DEPRECATED (5. 0, "FWidgetArgs is deprecated. Upgrade to FWidgetDesiredSizeArgs instead.") const &
Get the computed desired size for this layout, updating the internal cache as required.
UE_DEPRECATED() [2/2]
struct FSlateTextBlockLayout::UE_DEPRECATED (5. 0, "FWidgetArgs is deprecated. Upgrade to FWidgetDesiredSizeArgs instead.") inline
Definition at line 1 of file SlateTextBlockLayout.h.
UpdateTextHighlights()
void FSlateTextBlockLayout::UpdateTextHighlights (const FText & InHighlightText) private
Update the text highlights.
References UpdateTextHighlights().
Referenced by UpdateTextHighlights().
UpdateTextLayout() [1/2]
void FSlateTextBlockLayout::UpdateTextLayout (const FString & InText) private
Updates the text layout to contain the given string.
References UpdateTextLayout().
UpdateTextLayout() [2/2]
void FSlateTextBlockLayout::UpdateTextLayout (const FText & InText) private
Updates the text layout to contain the given text.
References UpdateTextLayout().
Referenced by UpdateTextLayout(), and UpdateTextLayout().
UpdateTextStyle() [1/2]
void FSlateTextBlockLayout::UpdateTextStyle (const FTextBlockStyle & InTextStyle)
Update the text style.
References InTextStyle.
UpdateTextStyle() [2/2]
void FSlateTextBlockLayout::UpdateTextStyle (const FTextBlockStyle::CompareParams & InNewStyleParams)
Update the text style.
Field Documentation
bCachedAutoWrapText
bool FSlateTextBlockLayout::bCachedAutoWrapText private
Cache the auto wrap text value.
Definition at line 268 of file SlateTextBlockLayout.h.
CachedSize
FVector2f FSlateTextBlockLayout::CachedSize private
The last known size of the layout from the previous OnPaint, used to guess at an auto-wrapping width in ComputeDesiredSize.
Definition at line 262 of file SlateTextBlockLayout.h.
CachedWrapTextAt
float FSlateTextBlockLayout::CachedWrapTextAt private
Cache where to wrap text at?
Definition at line 265 of file SlateTextBlockLayout.h.
HighlightTextLastUpdate
FTextSnapshot FSlateTextBlockLayout::HighlightTextLastUpdate private
The state of the highlight text the last time it was updated (used to allow updates when the text is changed)
Definition at line 274 of file SlateTextBlockLayout.h.
InScale
PRAGMA_DISABLE_DEPRECATION_WARNINGS const float FSlateTextBlockLayout::InScale
Definition at line 164 of file SlateTextBlockLayout.h.
Referenced by ComputeDesiredSize(), and ComputeDesiredSize().
InTextStyle
PRAGMA_DISABLE_DEPRECATION_WARNINGS const float const FTextBlockStyle& FSlateTextBlockLayout::InTextStyle
Definition at line 164 of file SlateTextBlockLayout.h.
Referenced by ComputeDesiredSize(), ConditionallyUpdateTextStyle(), OverrideTextStyle(), and UpdateTextStyle().
Marshaller
TSharedPtr<ITextLayoutMarshaller> FSlateTextBlockLayout::Marshaller private
The marshaller used to get/set the text to/from the text layout.
Definition at line 256 of file SlateTextBlockLayout.h.
TextHighlighter
TSharedPtr<ISlateRunRenderer> FSlateTextBlockLayout::TextHighlighter private
Used to render the current highlights in the text layout.
Definition at line 259 of file SlateTextBlockLayout.h.
TextLastUpdate
FTextSnapshot FSlateTextBlockLayout::TextLastUpdate private
The state of the text the last time it was updated (used to allow updates when the text is changed)
Definition at line 271 of file SlateTextBlockLayout.h.
TextLayout
TSharedPtr<FSlateTextLayout> FSlateTextBlockLayout::TextLayout private
In control of the layout and wrapping of the text.
Definition at line 253 of file SlateTextBlockLayout.h.
The documentation for this class was generated from the following file:
SlateTextBlockLayout.h