Unreal Engine 5.6 C++ API: TSlotlessChildren< ChildType > Class Template Reference
TSlotlessChildren< ChildType > Class Template Reference final
Some advanced widgets contain no layout information, and do not require slots.
#include "Children.h"
Public Member Functions
TSlotlessChildren (std::nullptr_t, bool InbChangesInvalidatePrepass=true)=delete
TSlotlessChildren (SWidget *InOwner, bool InbChangesInvalidatePrepass=true)
int32 Add (const TSharedRef< ChildType > &Child)
TArray< TSharedRef< ChildType > > AsArrayCopy () const
void Empty (int32 Slack=0)
int32 Find (const TSharedRef< ChildType > &Item) const
virtual TSharedRef< const SWidget > GetChildAt (int32 Index) const override
virtual TSharedRef< SWidget > GetChildAt (int32 Index) override
void Insert (const TSharedRef< ChildType > &Child, int32 Index)
virtual int32 Num () const override
TSharedRef< ChildType > & operator[] (int32 Index)
const TSharedRef< ChildType > & operator[] (int32 Index) const
int32 Remove (const TSharedRef< ChildType > &Child)
void RemoveAt (int32 Index)
void Reset (int32 NewSize=0)
template<class PREDICATE_CLASS>
void Sort (const PREDICATE_CLASS &Predicate)
void Swap (int32 IndexA, int32 IndexB)
Public Member Functions inherited from FChildren
FChildren (std::nullptr_t)=delete
FChildren (SWidget *InOwner)
FChildren (SWidget *InOwner, FName InName)
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred)
Applies the predicate to all the widgets contained by the FChildren.
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred) const
Applies the predicate to all the widgets contained by the FChildren.
FName GetName () const
Option to give a name to Children to SlotAttribute purposes or for debugging.
SWidget & GetOwner () const
void * operator new (size_t)=delete
void * operator new[] (size_t)=delete
virtual bool SupportSlotWithSlateAttribute () const
Private Member Functions
virtual FConstWidgetRef GetChildRefAt (int32 ChildIndex) const override
virtual FWidgetRef GetChildRefAt (int32 ChildIndex) override
virtual const FSlotBase & GetSlotAt (int32 ChildIndex) const override
virtual int32 NumSlot () const override
Private Attributes
bool bChangesInvalidatePrepass
TArray< TSharedRef< ChildType > > Children
Additional Inherited Members
Protected Types inherited from FChildren
enum ECopyConstruct { CopyConstruct }
enum ERefConstruct { ReferenceConstruct }
Protected Member Functions inherited from FChildren
virtual ~FChildren ()
void Debug_TestDestroyTag () const
Detailed Description
template<typename ChildType>
class TSlotlessChildren< ChildType >
Some advanced widgets contain no layout information, and do not require slots.
Those widgets may wish to store a specialized type of child widget. In those cases, using TSlotlessChildren is convenient.
TSlotlessChildren should not be used for general-purpose widgets.
Definition at line 835 of file Children.h.
Constructor & Destructor Documentation
TSlotlessChildren() [1/2]
template<typename ChildType> TSlotlessChildren< ChildType >::TSlotlessChildren (SWidget * InOwner, bool InbChangesInvalidatePrepass = true) inline
Definition at line 864 of file Children.h.
References FChildren::FChildren(), and bChangesInvalidatePrepass.
TSlotlessChildren() [2/2]
template<typename ChildType> TSlotlessChildren< ChildType >::TSlotlessChildren (std::nullptr_t , bool InbChangesInvalidatePrepass = true) delete
Member Function Documentation
Add()
template<typename ChildType> int32 TSlotlessChildren< ChildType >::Add (const TSharedRef< ChildType > & Child) inline
Definition at line 887 of file Children.h.
References bChangesInvalidatePrepass, Child, ChildOrder, Children, FChildren::GetOwner(), SWidget::Invalidate(), and SNullWidget::NullWidget.
AsArrayCopy()
template<typename ChildType> TArray< TSharedRef< ChildType > > TSlotlessChildren< ChildType >::AsArrayCopy () const inline
Definition at line 993 of file Children.h.
References Children.
Empty()
template<typename ChildType> void TSlotlessChildren< ChildType >::Empty (int32 Slack = 0) inline
Definition at line 928 of file Children.h.
References Child, Children, TArray< InElementType, InAllocatorType >::Empty(), GetChildAt(), FChildren::GetOwner(), MoveTemp(), and SNullWidget::NullWidget.
Find()
template<typename ChildType> int32 TSlotlessChildren< ChildType >::Find (const TSharedRef< ChildType > & Item) const inline
Definition at line 988 of file Children.h.
References Children, and Item.
GetChildAt() [1/2]
template<typename ChildType> virtual TSharedRef< const SWidget > TSlotlessChildren< ChildType >::GetChildAt (int32 Index) const inline override virtual
Returns
const pointer to the Widget at the specified Index.
Implements FChildren.
Definition at line 882 of file Children.h.
References Children.
GetChildAt() [2/2]
template<typename ChildType> virtual TSharedRef< SWidget > TSlotlessChildren< ChildType >::GetChildAt (int32 Index) inline override virtual
Returns
pointer to the Widget at the specified Index.
Implements FChildren.
Definition at line 877 of file Children.h.
References Children.
Referenced by Empty(), RemoveAt(), and Reset().
GetChildRefAt() [1/2]
template<typename ChildType> virtual FConstWidgetRef TSlotlessChildren< ChildType >::GetChildRefAt (int32 Index) const inline override private virtual
Returns
ref to the Widget at the specified Index.
Implements FChildren.
Definition at line 858 of file Children.h.
References Children, and FChildren::ReferenceConstruct.
GetChildRefAt() [2/2]
template<typename ChildType> virtual FWidgetRef TSlotlessChildren< ChildType >::GetChildRefAt (int32 Index) inline override private virtual
Returns
ref to the Widget at the specified Index.
Implements FChildren.
Definition at line 853 of file Children.h.
References Children, and FChildren::ReferenceConstruct.
GetSlotAt()
template<typename ChildType> virtual const FSlotBase & TSlotlessChildren< ChildType >::GetSlotAt (int32 ChildIndex) const inline override private virtual
Returns
the const reference to the slot at the specified Index
Implements FChildren.
Definition at line 845 of file Children.h.
References check.
Insert()
template<typename ChildType> void TSlotlessChildren< ChildType >::Insert (const TSharedRef< ChildType > & Child, int32 Index) inline
Definition at line 952 of file Children.h.
References bChangesInvalidatePrepass, Child, ChildOrder, Children, FChildren::GetOwner(), SWidget::Invalidate(), and SNullWidget::NullWidget.
Num()
template<typename ChildType> virtual int32 TSlotlessChildren< ChildType >::Num () const inline override virtual
Returns
the number of children
Implements FChildren.
Definition at line 872 of file Children.h.
References Children.
NumSlot()
template<typename ChildType> virtual int32 TSlotlessChildren< ChildType >::NumSlot () const inline override private virtual
Returns
the number of slot the children has.
Reimplemented from FChildren.
Definition at line 840 of file Children.h.
operator[]() [1/2]
template<typename ChildType> TSharedRef< ChildType > & TSlotlessChildren< ChildType >::operator[] (int32 Index) inline
Definition at line 999 of file Children.h.
References Children.
operator[]() [2/2]
template<typename ChildType> const TSharedRef< ChildType > & TSlotlessChildren< ChildType >::operator[] (int32 Index) const inline
Definition at line 998 of file Children.h.
References Children.
Remove()
template<typename ChildType> int32 TSlotlessChildren< ChildType >::Remove (const TSharedRef< ChildType > & Child) inline
Definition at line 966 of file Children.h.
References Child, Children, FChildren::GetOwner(), and SNullWidget::NullWidget.
RemoveAt()
template<typename ChildType> void TSlotlessChildren< ChildType >::RemoveAt (int32 Index) inline
Definition at line 976 of file Children.h.
References Child, Children, GetChildAt(), FChildren::GetOwner(), and SNullWidget::NullWidget.
Reset()
template<typename ChildType> void TSlotlessChildren< ChildType >::Reset (int32 NewSize = 0) inline
Definition at line 904 of file Children.h.
References Child, Children, GetChildAt(), FChildren::GetOwner(), MoveTemp(), SNullWidget::NullWidget, and TArray< InElementType, InAllocatorType >::Reset().
Sort()
template<typename ChildType> template<class PREDICATE_CLASS> void TSlotlessChildren< ChildType >::Sort (const PREDICATE_CLASS & Predicate) inline
Definition at line 1002 of file Children.h.
References bChangesInvalidatePrepass, ChildOrder, Children, FChildren::GetOwner(), SWidget::Invalidate(), and Predicate.
Swap()
template<typename ChildType> void TSlotlessChildren< ChildType >::Swap (int32 IndexA, int32 IndexB) inline
Definition at line 1011 of file Children.h.
References bChangesInvalidatePrepass, ChildOrder, Children, FChildren::GetOwner(), and SWidget::Invalidate().
Field Documentation
bChangesInvalidatePrepass
template<typename ChildType> bool TSlotlessChildren< ChildType >::bChangesInvalidatePrepass private
Definition at line 1021 of file Children.h.
Referenced by TSlotlessChildren(), Add(), Insert(), Sort(), and Swap().
Children
template<typename ChildType> TArray<TSharedRef<ChildType> > TSlotlessChildren< ChildType >::Children private
Definition at line 838 of file Children.h.
Referenced by Add(), AsArrayCopy(), Empty(), Find(), GetChildAt(), GetChildAt(), GetChildRefAt(), GetChildRefAt(), Insert(), Num(), operator[](), operator[](), Remove(), RemoveAt(), Reset(), Sort(), and Swap().
The documentation for this class was generated from the following file:
Children.h