Unreal Engine 5.6 C++ API: SRigVMGraphPinNameListValueWidget Class Reference
SRigVMGraphPinNameListValueWidget Class Reference
A searchable text combo box.
#include "SRigVMGraphPinNameListValueWidget.h"
Public Types
typedef TSlateDelegates< TSharedPtr< FRigVMStringWithTag > >::FOnGenerateWidget FOnGenerateWidget
Delegate type used to generate widgets that represent Options.
typedef TSlateDelegates< TSharedPtr< FRigVMStringWithTag > >::FOnSelectionChanged FOnSelectionChanged
typedef SListView< TSharedPtr< FRigVMStringWithTag > > SComboListType
Type of list used for showing menu options.
Public Member Functions
void ClearSelection ()
TSharedPtr< FRigVMStringWithTag > GetSelectedItem ()
void RefreshOptions ()
Requests a list refresh after updating options Call SetSelectedItem to update the selected item if required.
void SetOptionsSource (const TArray< TSharedPtr< FRigVMStringWithTag > > *InOptionsSource)
void SetSelectedItem (TSharedPtr< FRigVMStringWithTag > InSelectedItem)
ContentPadding OnSelectionChanged OnComboBoxOpening InitiallySelectedItem MaxListHeight SearchHintText SLATE_ARGUMENT (bool, AllowUserProvidedText) SLATE_END_ARGS() void Construct(const FArguments &InArgs)
Construct the widget from a declaration.
ContentPadding OnSelectionChanged OnComboBoxOpening InitiallySelectedItem MaxListHeight SLATE_ARGUMENT (bool, HasDownArrow) SLATE_ARGUMENT(FText
When false, the down arrow is not generated and it is up to the API consumer to make their own visual hint that this is a drop down.
ContentPadding SLATE_ARGUMENT (const TArray< TSharedPtr< FRigVMStringWithTag > > *, OptionsSource) SLATE_EVENT(FOnSelectionChanged
ContentPadding OnSelectionChanged OnComboBoxOpening InitiallySelectedItem SLATE_ARGUMENT (TOptional< EPopupMethod >, Method) SLATE_ARGUMENT(float
The max height of the combo box menu.
ContentPadding OnSelectionChanged OnComboBoxOpening SLATE_ARGUMENT (TSharedPtr< SScrollBar >, CustomScrollbar) SLATE_ARGUMENT(TSharedPtr< FRigVMStringWithTag >
The custom scrollbar to use in the ListView.
SLATE_BEGIN_ARGS (SRigVMGraphPinNameListValueWidget)
SLATE_DEFAULT_SLOT (FArguments, Content) SLATE_ATTRIBUTE(FMargin
Slot for this button's content (optional)
ContentPadding OnSelectionChanged SLATE_EVENT (FOnGenerateWidget, OnGenerateWidget) SLATE_EVENT(FOnComboBoxOpening
Called when combo box is opened, before list is actually created.
Public Member Functions inherited from SComboButton
void Construct (const FArguments &InArgs)
Construct the widget from a declaration.
void SetButtonContentPadding (FMargin InPadding)
See the padding for button content.
void SetHasDownArrow (bool InHasArrowDown)
add/remove the expanding arrow.
void SetMenuContentWidgetToFocus (TWeakPtr< SWidget > InWidgetToFocusPtr)
void SetOnGetMenuContent (FOnGetContent InOnGetMenuContent)
See the OnGetMenuContent event.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign Method SLATE_ARGUMENT (bool, CollapseMenuOnParentFocus) SLATE_END_ARGS() 1 virtual void SetMenuContent(TSharedRef< SWidget > InContent) override
True if this combo's menu should be collapsed when our parent receives focus, false (default) otherwise.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable SLATE_ARGUMENT (bool, HasDownArrow) SLATE_ATTRIBUTE(FSlateColor
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign SLATE_ARGUMENT (EVerticalAlignment, VAlign) SLATE_ARGUMENT(TOptional< EPopupMethod >
Spawn a new window or reuse current window for this combo.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding SLATE_ATTRIBUTE (EMenuPlacement, MenuPlacement) SLATE_ARGUMENT(EHorizontalAlignment
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor SLATE_ATTRIBUTE (FSlateColor, ButtonColorAndOpacity) SLATE_ATTRIBUTE(FMargin
SLATE_BEGIN_ARGS (SComboButton)
ButtonStyle MenuContent OnMenuOpenChanged SLATE_EVENT (FOnComboBoxOpened, OnComboBoxOpened) SLATE_ARGUMENT(bool
ButtonStyle MenuContent SLATE_EVENT (FOnGetContent, OnGetMenuContent) SLATE_EVENT(FOnIsOpenChanged
Sets an event handler to generate a widget dynamically when the menu is needed.
ButtonStyle SLATE_NAMED_SLOT (FArguments, ButtonContent) SLATE_NAMED_SLOT(FArguments
Optional static menu content.
SLATE_STYLE_ARGUMENT (FComboButtonStyle, ComboButtonStyle) SLATE_STYLE_ARGUMENT(FButtonStyle
The visual style of the button (overrides ComboButtonStyle)
Private Member Functions
TSharedRef< ITableRow > GenerateMenuItemRow (TSharedPtr< FRigVMStringWithTag > InItem, const TSharedRef< STableViewBase > &OwnerTable)
Generate a row for the InItem in the combo box's list (passed in as OwnerTable).
virtual FReply OnButtonClicked () override
Handle clicking on the content menu.
FReply OnComboListKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Special case handling for combo list key commands.
void OnMenuOpenChanged (bool bOpen)
void OnSearchTextChanged (const FText &ChangedText)
Invoked when the search text changes.
void OnSearchTextCommitted (const FText &ChangedText, ETextCommit::Type CommitType)
Invoked when the search is committed.
FReply OnSearchTextKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Special case handling for search box key commands.
void OnSelectionChanged_Internal (TSharedPtr< FRigVMStringWithTag > ProposedSelection, ESelectInfo::Type SelectInfo, bool bForce=false)
Invoked when the selection in the list changes.
EActiveTimerReturnType SetFocusPostConstruct (double InCurrentTime, float InDeltaTime)
Used to focus the name box immediately following construction.
Private Attributes
bool AllowUserProvidedText
TSharedPtr< SComboListType > ComboListView
The ListView that we pop up; visualized the available options.
TSharedPtr< SScrollBar > CustomScrollbar
The Scrollbar used in the ListView.
const FTableRowStyle * ItemStyle
The item style to use.
FOnComboBoxOpening OnComboBoxOpening
Delegate to invoke before the combo box is opening.
FOnGenerateWidget OnGenerateWidget
Delegate to invoke when we need to visualize an option as a widget.
FOnSelectionChanged OnSelectionChanged
Delegate that is invoked when the selected item in the combo box changes.
const TArray< TSharedPtr< FRigVMStringWithTag > > * OptionsSource
TSharedPtr< SEditableTextBox > SearchField
The search field used for the combox box's contents.
TSharedPtr< FRigVMStringWithTag > SelectedItem
The item currently selected in the combo box.
Additional Inherited Members
Protected Member Functions inherited from SComboButton
FText GetFilteredToolTipText (TAttribute< FText > ToolTipText) const
Called to query the tool tip text for this widget, but will return an empty text when the menu is already open.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Protected Attributes inherited from SComboButton
bool bIsFocusable
Can this button be focused?
SHorizontalBox::FSlot * ButtonContentSlot
Area where the button's content resides.
TWeakPtr< SWidget > ContentWidgetPtr
The content widget, if any, set by the user on creation.
const FSlateBrush * MenuBorderBrush
Brush to use to add a "menu border" around the drop-down content.
FMargin MenuBorderPadding
Padding to use to add a "menu border" around the drop-down content.
FOnComboBoxOpened OnComboBoxOpened
Delegate to execute when the combo list is opened.
TWeakPtr< SWidget > WidgetToFocusPtr
Detailed Description
A searchable text combo box.
Definition at line 17 of file SRigVMGraphPinNameListValueWidget.h.
Member Typedef Documentation
FOnGenerateWidget
typedef TSlateDelegates<TSharedPtr<FRigVMStringWithTag>>::FOnGenerateWidget SRigVMGraphPinNameListValueWidget::FOnGenerateWidget
Delegate type used to generate widgets that represent Options.
Definition at line 23 of file SRigVMGraphPinNameListValueWidget.h.
FOnSelectionChanged
typedef TSlateDelegates<TSharedPtr<FRigVMStringWithTag>>::FOnSelectionChanged SRigVMGraphPinNameListValueWidget::FOnSelectionChanged
Definition at line 24 of file SRigVMGraphPinNameListValueWidget.h.
SComboListType
typedef SListView< TSharedPtr<FRigVMStringWithTag> > SRigVMGraphPinNameListValueWidget::SComboListType
Type of list used for showing menu options.
Definition at line 21 of file SRigVMGraphPinNameListValueWidget.h.
Member Function Documentation
ClearSelection()
void SRigVMGraphPinNameListValueWidget::ClearSelection ()
References ClearSelection().
Referenced by ClearSelection().
GenerateMenuItemRow()
TSharedRef< ITableRow > SRigVMGraphPinNameListValueWidget::GenerateMenuItemRow (TSharedPtr< FRigVMStringWithTag > InItem, const TSharedRef< STableViewBase > & OwnerTable) private
Generate a row for the InItem in the combo box's list (passed in as OwnerTable).
Do this by calling the user-specified OnGenerateWidget
References GenerateMenuItemRow().
Referenced by GenerateMenuItemRow().
GetSelectedItem()
TSharedPtr< FRigVMStringWithTag > SRigVMGraphPinNameListValueWidget::GetSelectedItem ()
Returns
the item currently selected by the combo box.
References GetSelectedItem().
Referenced by GetSelectedItem().
OnButtonClicked()
virtual FReply SRigVMGraphPinNameListValueWidget::OnButtonClicked () override private virtual
Handle clicking on the content menu.
Reimplemented from SComboButton.
References OnButtonClicked().
Referenced by OnButtonClicked().
OnComboListKeyDown()
FReply SRigVMGraphPinNameListValueWidget::OnComboListKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) private
Special case handling for combo list key commands.
References OnComboListKeyDown().
Referenced by OnComboListKeyDown().
OnMenuOpenChanged()
void SRigVMGraphPinNameListValueWidget::OnMenuOpenChanged (bool bOpen) private
References OnMenuOpenChanged().
Referenced by OnMenuOpenChanged().
OnSearchTextChanged()
void SRigVMGraphPinNameListValueWidget::OnSearchTextChanged (const FText & ChangedText) private
Invoked when the search text changes.
References OnSearchTextChanged().
Referenced by OnSearchTextChanged().
OnSearchTextCommitted()
void SRigVMGraphPinNameListValueWidget::OnSearchTextCommitted (const FText & ChangedText, ETextCommit::Type CommitType) private
Invoked when the search is committed.
References OnSearchTextCommitted().
Referenced by OnSearchTextCommitted().
OnSearchTextKeyDown()
FReply SRigVMGraphPinNameListValueWidget::OnSearchTextKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) private
Special case handling for search box key commands.
References OnSearchTextKeyDown().
Referenced by OnSearchTextKeyDown().
OnSelectionChanged_Internal()
void SRigVMGraphPinNameListValueWidget::OnSelectionChanged_Internal (TSharedPtr< FRigVMStringWithTag > ProposedSelection, ESelectInfo::Type SelectInfo, bool bForce = false) private
Invoked when the selection in the list changes.
References OnSelectionChanged_Internal().
Referenced by OnSelectionChanged_Internal().
RefreshOptions()
void SRigVMGraphPinNameListValueWidget::RefreshOptions ()
Requests a list refresh after updating options Call SetSelectedItem to update the selected item if required.
See also
SetSelectedItem
References RefreshOptions().
Referenced by RefreshOptions().
SetFocusPostConstruct()
EActiveTimerReturnType SRigVMGraphPinNameListValueWidget::SetFocusPostConstruct (double InCurrentTime, float InDeltaTime) private
Used to focus the name box immediately following construction.
References SetFocusPostConstruct().
Referenced by SetFocusPostConstruct().
SetOptionsSource()
void SRigVMGraphPinNameListValueWidget::SetOptionsSource (const TArray< TSharedPtr< FRigVMStringWithTag > > * InOptionsSource)
References SetOptionsSource().
Referenced by SetOptionsSource().
SetSelectedItem()
void SRigVMGraphPinNameListValueWidget::SetSelectedItem (TSharedPtr< FRigVMStringWithTag > InSelectedItem)
References SetSelectedItem().
Referenced by SetSelectedItem().
SLATE_ARGUMENT() [1/5]
ContentPadding OnSelectionChanged OnComboBoxOpening InitiallySelectedItem MaxListHeight SearchHintText SRigVMGraphPinNameListValueWidget::SLATE_ARGUMENT (bool , AllowUserProvidedText) const &
Construct the widget from a declaration.
Parameters
InArgs Declaration from which to construct the combo box
References AllowUserProvidedText, SComboButton::Construct(), SLATE_ARGUMENT(), and SLATE_END_ARGS.
SLATE_ARGUMENT() [2/5]
ContentPadding OnSelectionChanged OnComboBoxOpening InitiallySelectedItem MaxListHeight SRigVMGraphPinNameListValueWidget::SLATE_ARGUMENT (bool , HasDownArrow)
When false, the down arrow is not generated and it is up to the API consumer to make their own visual hint that this is a drop down.
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [3/5]
ContentPadding SRigVMGraphPinNameListValueWidget::SLATE_ARGUMENT (const TArray< TSharedPtr< FRigVMStringWithTag > > * , OptionsSource)
References OnSelectionChanged, OptionsSource, SLATE_ARGUMENT(), and SLATE_EVENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_ARGUMENT().
SLATE_ARGUMENT() [4/5]
ContentPadding OnSelectionChanged OnComboBoxOpening InitiallySelectedItem SRigVMGraphPinNameListValueWidget::SLATE_ARGUMENT (TOptional< EPopupMethod > , Method)
The max height of the combo box menu.
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [5/5]
ContentPadding OnSelectionChanged OnComboBoxOpening SRigVMGraphPinNameListValueWidget::SLATE_ARGUMENT (TSharedPtr< SScrollBar > , CustomScrollbar)
The custom scrollbar to use in the ListView.
The option that should be selected when the combo box is first created
References CustomScrollbar, and SLATE_ARGUMENT().
SLATE_BEGIN_ARGS()
SRigVMGraphPinNameListValueWidget::SLATE_BEGIN_ARGS (SRigVMGraphPinNameListValueWidget) inline
Definition at line 26 of file SRigVMGraphPinNameListValueWidget.h.
References NSLOCTEXT.
SLATE_DEFAULT_SLOT()
SRigVMGraphPinNameListValueWidget::SLATE_DEFAULT_SLOT (FArguments , Content)
Slot for this button's content (optional)
SLATE_EVENT()
ContentPadding OnSelectionChanged SRigVMGraphPinNameListValueWidget::SLATE_EVENT (FOnGenerateWidget , OnGenerateWidget)
Called when combo box is opened, before list is actually created.
References OnComboBoxOpening, OnGenerateWidget, and SLATE_EVENT().
Referenced by SLATE_ARGUMENT(), and SLATE_EVENT().
Field Documentation
AllowUserProvidedText
bool SRigVMGraphPinNameListValueWidget::AllowUserProvidedText private
Definition at line 149 of file SRigVMGraphPinNameListValueWidget.h.
Referenced by SLATE_ARGUMENT().
ComboListView
TSharedPtr< SComboListType > SRigVMGraphPinNameListValueWidget::ComboListView private
The ListView that we pop up; visualized the available options.
Definition at line 140 of file SRigVMGraphPinNameListValueWidget.h.
CustomScrollbar
TSharedPtr< SScrollBar > SRigVMGraphPinNameListValueWidget::CustomScrollbar private
The Scrollbar used in the ListView.
Definition at line 142 of file SRigVMGraphPinNameListValueWidget.h.
Referenced by SLATE_ARGUMENT().
ItemStyle
const FTableRowStyle* SRigVMGraphPinNameListValueWidget::ItemStyle private
The item style to use.
Definition at line 130 of file SRigVMGraphPinNameListValueWidget.h.
OnComboBoxOpening
FOnComboBoxOpening SRigVMGraphPinNameListValueWidget::OnComboBoxOpening private
Delegate to invoke before the combo box is opening.
Definition at line 144 of file SRigVMGraphPinNameListValueWidget.h.
Referenced by SLATE_EVENT().
OnGenerateWidget
FOnGenerateWidget SRigVMGraphPinNameListValueWidget::OnGenerateWidget private
Delegate to invoke when we need to visualize an option as a widget.
Definition at line 146 of file SRigVMGraphPinNameListValueWidget.h.
Referenced by SLATE_EVENT().
OnSelectionChanged
FOnSelectionChanged SRigVMGraphPinNameListValueWidget::OnSelectionChanged private
Delegate that is invoked when the selected item in the combo box changes.
Definition at line 134 of file SRigVMGraphPinNameListValueWidget.h.
Referenced by SLATE_ARGUMENT().
OptionsSource
const TArray< TSharedPtr<FRigVMStringWithTag> >* SRigVMGraphPinNameListValueWidget::OptionsSource private
Definition at line 148 of file SRigVMGraphPinNameListValueWidget.h.
Referenced by SLATE_ARGUMENT().
SearchField
TSharedPtr< SEditableTextBox > SRigVMGraphPinNameListValueWidget::SearchField private
The search field used for the combox box's contents.
Definition at line 138 of file SRigVMGraphPinNameListValueWidget.h.
SelectedItem
TSharedPtr<FRigVMStringWithTag> SRigVMGraphPinNameListValueWidget::SelectedItem private
The item currently selected in the combo box.
Definition at line 136 of file SRigVMGraphPinNameListValueWidget.h.
The documentation for this class was generated from the following file:
SRigVMGraphPinNameListValueWidget.h