Unreal Engine 5.6 C++ API: TBaseBlendedCurve< InAllocatorType, InElementType > Struct Template Reference
TBaseBlendedCurve< InAllocatorType, InElementType > Struct Template Reference
This struct is used to create curve snap shot of current time when extracted.
#include "AnimCurveTypes.h"
Public Types
typedef InAllocatorType AllocatorType
typedef InElementType ElementType
typedef UE::Anim::TNamedValueArray< AllocatorType, ElementType > Super
Public Types inherited from UE::Anim::TNamedValueArray< FAnimStackAllocator, UE::Anim::FCurveElement >
typedef FAnimStackAllocator AllocatorType
typedef UE::Anim::FCurveElement ElementType
Public Member Functions
template<typename OtherAllocator, typename OtherElementType>
void Accumulate (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &AdditiveCurve, float Weight)
Accumulate the input curve with input Weight.
template<typename OtherAllocator, typename OtherElementType>
void Combine (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &CurveToCombine)
If CurveToCombine contains a valid element, then the value in 'this' is overridden, otherwise the value is not modified.
template<typename OtherAllocator, typename OtherElementType>
void CombinePreserved (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &CurveToCombine)
If 'this' does not contain a valid element, then the value in 'this' is set, otherwise the value is not modified.
template<typename OtherAllocator, typename OtherElementType>
void ConvertToAdditive (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &BaseCurve)
Convert current curves to Additive (this - BaseCurve) if overlapping entries are found.
template<typename OtherAllocator, typename OtherElementType>
void CopyFrom (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &InCurveToCopyFrom)
Copy elements between curves that have different allocators & element types.
const UE::Anim::FCurveFilter * GetFilter () const
Get the filter referenced by this curve.
template<typename OtherAllocator, typename OtherElementType>
void InitFrom (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &InCurveToInitFrom)
Initialize from another curve.
void InvalidateCurveWeight (FName InName)
Invalidate value of the named curve.
template<typename AllocatorA, typename ElementTypeA, typename AllocatorB, typename ElementTypeB>
void Lerp (const TBaseBlendedCurve< AllocatorA, ElementTypeA > &A, const TBaseBlendedCurve< AllocatorB, ElementTypeB > &B, float Alpha)
Blend (A, B) using Alpha.
template<typename OtherAllocator, typename OtherElementType>
void LerpTo (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &Other, float Alpha)
Blend with Other using Alpha.
template<typename OtherAllocator, typename OtherElementType>
void LerpToValid (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &Other, float Alpha)
Blend with Other using Alpha when both elements are valid, otherwise preserve valid element.
template<typename AllocatorA, typename ElementTypeA, typename AllocatorB, typename ElementTypeB>
void LerpValid (const TBaseBlendedCurve< AllocatorA, ElementTypeA > &A, const TBaseBlendedCurve< AllocatorB, ElementTypeB > &B, float Alpha)
Blend with Other using Alpha when both elements are valid, otherwise preserve valid element.
void MoveFrom (TBaseBlendedCurve &CurveToMoveFrom)
Once moved, source is invalid.
template<typename OtherAllocator, typename OtherElementType>
void Override (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &CurveToOverrideFrom)
Override with input curve.
template<typename OtherAllocator, typename OtherElementType>
void Override (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &CurveToOverrideFrom, float Weight)
Override with input curve * weight.
void OverrideMove (TBaseBlendedCurve &CurveToOverrideFrom)
Override with input curve, leaving input curve invalid.
void Reserve (int32 InNumElements)
Reserves memory for InNumElements.
void Set (FName InName, float InValue)
Set value of curve named InName to InValue.
void SetFilter (const UE::Anim::FCurveFilter *InFilter)
Set the filter referenced by this curve.
void SetFlags (FName InName, UE::Anim::ECurveElementFlags InFlags)
Set flags of curve named InName to InFlags.
UE_DEPRECATED (5.3, "Curves are now always valid.") bool IsValid() const
UE_DEPRECATED (5.3, "InitFrom can no longer be called with a LUT, please use another initialization method or just dont initialize the curve.") void InitFrom(TArray< uint16 > const *InUIDToArrayIndexLUT)
UE_DEPRECATED (5.3, "Please use Get with a curve name or consider using one of the bulk APIs (e.g. UE::Anim::FCurveUtils::BulkGet)") float Get(SmartName
Get value of curve element named InName.
UE_DEPRECATED (5.3, "Please use InvalidateCurveWeight with a curve name") void InvalidateCurveWeight(SmartName
UE_DEPRECATED (5.3, "Please use Num(). Element validity/enabled state is now handled via UE::Anim::FCurveFilter.") int32 NumValid() const
UE_DEPRECATED (5.3, "Please use Set with a curve name or consider using one of the bulk APIs (e.g. UE::Anim::FCurveUtils::BulkSet).") void Set(SmartName
UE_DEPRECATED (5.3, "This function has been removed.") int32 GetArrayIndexByUID(SmartName
template<typename OtherAllocator, typename OtherElementType>
void UseMaxValue (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &CurveToCombine)
This doesn't blend but combines MAX(current value, CurveToCombine value)
template<typename OtherAllocator, typename OtherElementType>
void UseMinValue (const TBaseBlendedCurve< OtherAllocator, OtherElementType > &CurveToCombine)
This doesn't blend but combines MIN(current weight, CurveToCombine weight)
Public Member Functions inherited from UE::Anim::TNamedValueArray< FAnimStackAllocator, UE::Anim::FCurveElement >
void Add (ArgTypes &&... Args)
Add a named element.
void AppendNames (TConstArrayView< FName > InNameArray)
Add an array of named elements.
void Empty ()
Reset the internal allocations.
void ForEachElement (PredicateType InPredicate) const
Iterate over each element calling InPredicate for each.
bool HasElement (FName InName) const
Check whether an element is present for the supplied name Note that this performs a binary search per-call.
int32 Max () const
int32 Num () const
void Reserve (int32 InNumElements)
Reserves memory for InNumElements.
void Shrink ()
Compacts the memory for the elements based on what was actually used.
Public Member Functions inherited from UE::Anim::FBaseBlendedCurve_DEPRECATED
UE_DEPRECATED (5.3, "Direct access to bInitialized is no longer allowed.") static 1 bool bInitialized
UE_DEPRECATED (5.3, "Direct access to CurveWeights is no longer allowed as it is no longer used.") static 1 TArray< float > CurveWeights
UE_DEPRECATED (5.3, "Direct access to NumValidCurveCount is no longer allowed as it is no longer used.") static 1 uint16 NumValidCurveCount
UE_DEPRECATED (5.3, "Direct access to UIDToArrayIndexLUT is no longer allowed as it is no longer used.") static 1 TArray< uint16 > const *UIDToArrayIndexLUT
UE_DEPRECATED (5.3, "Direct access to ValidCurveWeights is no longer allowed as it is no longer used.") static 1 TBitArray<> ValidCurveWeights
Private Attributes
const UE::Anim::FCurveFilter * Filter = nullptr
Friends
template<typename OtherAllocator, typename OtherElementType>
struct TBaseBlendedCurve
struct UE::Anim::FCurveUtils
Additional Inherited Members
Protected Member Functions inherited from UE::Anim::TNamedValueArray< FAnimStackAllocator, UE::Anim::FCurveElement >
void CheckDuplicates () const
void CheckSorted () const
const ElementType * Find (FName InName) const
Finds the element with the specified name (const)
int32 IndexOf (FName InName) const
Finds index of the element with the specified name, disregarding enabled state.
void SortElementsIfRequired () const
Protected Attributes inherited from UE::Anim::TNamedValueArray< FAnimStackAllocator, UE::Anim::FCurveElement >
bool bSorted
TArray< ElementType, AllocatorType > Elements
Detailed Description
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement>
struct TBaseBlendedCurve< InAllocatorType, InElementType >
This struct is used to create curve snap shot of current time when extracted.
Definition at line 486 of file AnimCurveTypes.h.
Member Typedef Documentation
AllocatorType
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> typedef InAllocatorType TBaseBlendedCurve< InAllocatorType, InElementType >::AllocatorType
Definition at line 489 of file AnimCurveTypes.h.
ElementType
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> typedef InElementType TBaseBlendedCurve< InAllocatorType, InElementType >::ElementType
Definition at line 490 of file AnimCurveTypes.h.
Super
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> typedef UE::Anim::TNamedValueArray<AllocatorType, ElementType> TBaseBlendedCurve< InAllocatorType, InElementType >::Super
Definition at line 497 of file AnimCurveTypes.h.
Member Function Documentation
Accumulate()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::Accumulate (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & AdditiveCurve, float Weight) inline
Accumulate the input curve with input Weight.
Definition at line 829 of file AnimCurveTypes.h.
References TBaseBlendedCurve, CURVE_PROFILE_CYCLE_COUNTER, FAnimWeight::IsRelevant(), UE::Anim::FNamedValueArrayUtils::Union(), and Weight.
Combine()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::Combine (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & CurveToCombine) inline
If CurveToCombine contains a valid element, then the value in 'this' is overridden, otherwise the value is not modified.
Definition at line 913 of file AnimCurveTypes.h.
References TBaseBlendedCurve, CURVE_PROFILE_CYCLE_COUNTER, EnumHasAnyFlags(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::ValidArg1.
CombinePreserved()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::CombinePreserved (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & CurveToCombine) inline
If 'this' does not contain a valid element, then the value in 'this' is set, otherwise the value is not modified.
Definition at line 894 of file AnimCurveTypes.h.
References TBaseBlendedCurve, CURVE_PROFILE_CYCLE_COUNTER, EnumHasAnyFlags(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::ValidArg0.
ConvertToAdditive()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::ConvertToAdditive (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & BaseCurve) inline
Convert current curves to Additive (this - BaseCurve) if overlapping entries are found.
Definition at line 814 of file AnimCurveTypes.h.
References TBaseBlendedCurve, CURVE_PROFILE_CYCLE_COUNTER, and UE::Anim::FNamedValueArrayUtils::Union().
CopyFrom()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::CopyFrom (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & InCurveToCopyFrom) inline
Copy elements between curves that have different allocators & element types.
Does not copy filter.
Definition at line 977 of file AnimCurveTypes.h.
References TBaseBlendedCurve, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::bSorted, CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements, and UE::Anim::FNamedValueArrayUtils::Union().
Referenced by Override(), and Override().
GetFilter()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> const UE::Anim::FCurveFilter * TBaseBlendedCurve< InAllocatorType, InElementType >::GetFilter () const inline
Get the filter referenced by this curve.
Definition at line 1029 of file AnimCurveTypes.h.
References Filter.
InitFrom()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::InitFrom (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & InCurveToInitFrom) inline
Initialize from another curve.
Just copies the filter and empties 'this'.
Definition at line 514 of file AnimCurveTypes.h.
References TBaseBlendedCurve, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::bSorted, CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements, ensure, and Filter.
Referenced by UE_DEPRECATED().
InvalidateCurveWeight()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> void TBaseBlendedCurve< InAllocatorType, InElementType >::InvalidateCurveWeight (FName InName) inline
Invalidate value of the named curve.
Definition at line 532 of file AnimCurveTypes.h.
References UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements, INDEX_NONE, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::IndexOf(), and InName.
Referenced by UE_DEPRECATED().
Lerp()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename AllocatorA, typename ElementTypeA, typename AllocatorB, typename ElementTypeB> void TBaseBlendedCurve< InAllocatorType, InElementType >::Lerp (const TBaseBlendedCurve< AllocatorA, ElementTypeA > & A, const TBaseBlendedCurve< AllocatorB, ElementTypeB > & B, float Alpha) inline
Blend (A, B) using Alpha.
Lone valid elements are not preserved.
Definition at line 704 of file AnimCurveTypes.h.
References TBaseBlendedCurve, A, Alpha, B, CURVE_PROFILE_CYCLE_COUNTER, FAnimWeight::IsRelevant(), FMath::Lerp(), Override, and UE::Anim::FNamedValueArrayUtils::Union().
LerpTo()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::LerpTo (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & Other, float Alpha) inline
Blend with Other using Alpha.
Lone valid elements are not preserved. Same as Lerp
Definition at line 733 of file AnimCurveTypes.h.
References TBaseBlendedCurve, Alpha, CURVE_PROFILE_CYCLE_COUNTER, FAnimWeight::IsRelevant(), FMath::Lerp(), Other, Override, and UE::Anim::FNamedValueArrayUtils::Union().
LerpToValid()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::LerpToValid (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & Other, float Alpha) inline
Blend with Other using Alpha when both elements are valid, otherwise preserve valid element.
Same as LerpValid
Definition at line 790 of file AnimCurveTypes.h.
References TBaseBlendedCurve, Alpha, UE::Anim::BothArgsValid, CURVE_PROFILE_CYCLE_COUNTER, EnumHasAllFlags(), FMath::Lerp(), Other, UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::ValidArg1.
LerpValid()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename AllocatorA, typename ElementTypeA, typename AllocatorB, typename ElementTypeB> void TBaseBlendedCurve< InAllocatorType, InElementType >::LerpValid (const TBaseBlendedCurve< AllocatorA, ElementTypeA > & A, const TBaseBlendedCurve< AllocatorB, ElementTypeB > & B, float Alpha) inline
Blend with Other using Alpha when both elements are valid, otherwise preserve valid element.
Definition at line 761 of file AnimCurveTypes.h.
References TBaseBlendedCurve, A, Alpha, B, UE::Anim::BothArgsValid, CURVE_PROFILE_CYCLE_COUNTER, EnumHasAllFlags(), UE::Anim::FCurveElement::Flags, FMath::Lerp(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::ValidArg0, UE::Anim::ValidArg1, and UE::Anim::FCurveElement::Value.
MoveFrom()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> void TBaseBlendedCurve< InAllocatorType, InElementType >::MoveFrom (TBaseBlendedCurve< InAllocatorType, InElementType > & CurveToMoveFrom) inline
Once moved, source is invalid.
Definition at line 1002 of file AnimCurveTypes.h.
References TBaseBlendedCurve, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::bSorted, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements, and MoveTemp().
Referenced by USTRUCT().
Override() [1/2]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::Override (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & CurveToOverrideFrom) inline
Override with input curve.
Definition at line 951 of file AnimCurveTypes.h.
References TBaseBlendedCurve, CopyFrom(), and CURVE_PROFILE_CYCLE_COUNTER.
Override() [2/2]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::Override (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & CurveToOverrideFrom, float Weight) inline
Override with input curve * weight.
Definition at line 931 of file AnimCurveTypes.h.
References TBaseBlendedCurve, CopyFrom(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements, FMath::IsNearlyEqual(), and Weight.
OverrideMove()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> void TBaseBlendedCurve< InAllocatorType, InElementType >::OverrideMove (TBaseBlendedCurve< InAllocatorType, InElementType > & CurveToOverrideFrom) inline
Override with input curve, leaving input curve invalid.
Definition at line 961 of file AnimCurveTypes.h.
References TBaseBlendedCurve, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::bSorted, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements, ensure, and MoveTemp().
Reserve()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> void TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve (int32 InNumElements) inline
Reserves memory for InNumElements.
Definition at line 1010 of file AnimCurveTypes.h.
References CURVE_PROFILE_CYCLE_COUNTER, and UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements.
Referenced by UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), and UE::Anim::FCurveUtils::BuildUnsorted().
Set()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> void TBaseBlendedCurve< InAllocatorType, InElementType >::Set (FName InName, float InValue) inline
Set value of curve named InName to InValue.
Inserts a new value if an element for InName does not already exist. Note that this performs a binary search per-call and can potentially cause a re-sort. Consider using a combiner operation to set multiple element's values.
Parameters
InName the name of the curve to set
InValue the value of the curve to set
Definition at line 553 of file AnimCurveTypes.h.
References UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Add(), UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Find(), and InName.
Referenced by UE_DEPRECATED().
SetFilter()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> void TBaseBlendedCurve< InAllocatorType, InElementType >::SetFilter (const UE::Anim::FCurveFilter * InFilter) inline
Set the filter referenced by this curve.
Definition at line 1023 of file AnimCurveTypes.h.
References Filter.
SetFlags()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> void TBaseBlendedCurve< InAllocatorType, InElementType >::SetFlags (FName InName, UE::Anim::ECurveElementFlags InFlags) inline
Set flags of curve named InName to InFlags.
Inserts a new default value if an element for InName does not already exist and then sets its flags to InFlags. Note that this performs a binary search per-call and can potentially cause a re-sort. Consider using a combiner operation to set multiple element's flags.
Parameters
InName the name of the curve to set
InFlags the flags of the curve to set
Definition at line 573 of file AnimCurveTypes.h.
References UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Add(), UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Find(), and InName.
UE_DEPRECATED() [1/7]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED (5. 3, "Curves are now always valid.") const inline
Definition at line 1016 of file AnimCurveTypes.h.
References bool, and IsValid().
UE_DEPRECATED() [2/7]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED (5. 3, "InitFrom can no longer be called with a LUT, please use another initialization method or just dont initialize the curve.") const inline
Definition at line 504 of file AnimCurveTypes.h.
References UE::Anim::TNamedValueArray< AllocatorType, ElementType >::bSorted, UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements, Filter, and InitFrom().
UE_DEPRECATED() [3/7]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED (5. 3, "Please use Get with a curve name or consider using one of the bulk APIs (e.g. UE::Anim::FCurveUtils::BulkGet)") inline
Get value of curve element named InName.
Note that this performs a binary search per-call. Consider using a ForEach* or a bulk API call (e.g. UE::Anim::FCurveUtils::BulkGet) to get multiple element's values.
Parameters
InName the name of the curve element to get
Returns
the value of the curve element. If this curve does not contain an element with the supplied name, returns 0.0 Get flags for curve element named InName Note that this performs a binary search per-call. Consider using a ForEach* call to get multiple element's flags.
Parameters
InName the name of the curve element to get
Returns
the flags of the curve element. If this curve does not contain an element with the supplied name, returns UE::Anim::ECurveElementFlags::None Get Value of curve named InName with validation and default value Note that this performs a binary search per-call. Consider using a ForEach* or one of the bulk APIs (e.g. UE::Anim::FCurveUtils::BulkGet) call to get multiple element's flags.
Parameters
InName the name of the curve element to get
HasElement whether this curve contains the supplied named element
InDefaultValue the default value to use in case the curve does not contain the supplied element
Returns
the value of the curve element. If this curve does not contain an element with the supplied name, returns InDefaultValue Mirror the values & flags of the two named curves if both exist. If only InName0 exists, InName0 will be renamed to InName1. If only InName1 exists, InName1 will be renamed to InName0.
Parameters
InName0 the name of first curve to mirror
InName1 the name of second curve to mirror
Definition at line 585 of file AnimCurveTypes.h.
References float.
UE_DEPRECATED() [4/7]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED (5. 3, "Please use InvalidateCurveWeight with a curve name") inline
Definition at line 526 of file AnimCurveTypes.h.
References InvalidateCurveWeight().
UE_DEPRECATED() [5/7]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED (5. 3, "Please use Num(). Element validity/enabled state is now handled via UE::Anim::FCurveFilter.") const inline
Definition at line 972 of file AnimCurveTypes.h.
References UE::Anim::TNamedValueArray< AllocatorType, ElementType >::Elements.
UE_DEPRECATED() [6/7]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED (5. 3, "Please use Set with a curve name or consider using one of the bulk APIs (e.g. UE::Anim::FCurveUtils::BulkSet).") inline
Definition at line 541 of file AnimCurveTypes.h.
References Set().
UE_DEPRECATED() [7/7]
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED (5. 3, "This function has been removed.") inline
Definition at line 681 of file AnimCurveTypes.h.
References INDEX_NONE.
UseMaxValue()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::UseMaxValue (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & CurveToCombine) inline
This doesn't blend but combines MAX(current value, CurveToCombine value)
Definition at line 847 of file AnimCurveTypes.h.
References TBaseBlendedCurve, UE::Anim::BothArgsValid, CURVE_PROFILE_CYCLE_COUNTER, EnumHasAllFlags(), FMath::Max, UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::ValidArg1.
UseMinValue()
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> void TBaseBlendedCurve< InAllocatorType, InElementType >::UseMinValue (const TBaseBlendedCurve< OtherAllocator, OtherElementType > & CurveToCombine) inline
This doesn't blend but combines MIN(current weight, CurveToCombine weight)
Definition at line 870 of file AnimCurveTypes.h.
References TBaseBlendedCurve, UE::Anim::BothArgsValid, CURVE_PROFILE_CYCLE_COUNTER, EnumHasAllFlags(), FMath::Min, UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::ValidArg1.
Friends And Related Symbol Documentation
TBaseBlendedCurve
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> template<typename OtherAllocator, typename OtherElementType> friend struct TBaseBlendedCurve friend
Definition at line 493 of file AnimCurveTypes.h.
References TBaseBlendedCurve.
Referenced by TBaseBlendedCurve, Accumulate(), Combine(), CombinePreserved(), ConvertToAdditive(), CopyFrom(), InitFrom(), Lerp(), LerpTo(), LerpToValid(), LerpValid(), MoveFrom(), Override(), Override(), OverrideMove(), UseMaxValue(), and UseMinValue().
UE::Anim::FCurveUtils
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> friend struct UE::Anim::FCurveUtils friend
Definition at line 495 of file AnimCurveTypes.h.
Field Documentation
Filter
template<typename InAllocatorType = FAnimStackAllocator, typename InElementType = UE::Anim::FCurveElement> const UE::Anim::FCurveFilter* TBaseBlendedCurve< InAllocatorType, InElementType >::Filter = nullptr private
Definition at line 501 of file AnimCurveTypes.h.
Referenced by GetFilter(), InitFrom(), SetFilter(), and UE_DEPRECATED().
The documentation for this struct was generated from the following file:
AnimCurveTypes.h