Unreal Engine 5.6 C++ API: TPackageWriterToSharedBuffer< BaseInterface > Class Template Reference
TPackageWriterToSharedBuffer< BaseInterface > Class Template Reference abstract
A base class for IPackageWriter subclasses that writes to records that are read in CommitPackage.
#include "PackageWriterToSharedBuffer.h"
Public Types
using FAdditionalFileRecord = FPackageWriterRecords::FAdditionalFile
using FBulkDataRecord = FPackageWriterRecords::FBulkData
using FLinkerAdditionalDataRecord = FPackageWriterRecords::FLinkerAdditionalData
using FPackageRecord = FPackageWriterRecords::FPackage
using FPackageTrailerRecord = FPackageWriterRecords::FPackageTrailer
using FWritePackageRecord = FPackageWriterRecords::FWritePackage
Public Member Functions
virtual void BeginPackage (const IPackageWriter::FBeginPackageInfo &Info) override
virtual void CommitPackage (IPackageWriter::FCommitPackageInfo &&Info) override
virtual void WriteAdditionalFile (const IPackageWriter::FAdditionalFileInfo &Info, const FIoBuffer &FileData) override
virtual void WriteBulkData (const IPackageWriter::FBulkDataInfo &Info, const FIoBuffer &BulkData, const TArray< FFileRegion > &FileRegions) override
virtual void WriteLinkerAdditionalData (const IPackageWriter::FLinkerAdditionalDataInfo &Info, const FIoBuffer &Data, const TArray< FFileRegion > &FileRegions) override
virtual void WritePackageData (const IPackageWriter::FPackageInfo &Info, FLargeMemoryWriter &ExportsArchive, const TArray< FFileRegion > &FileRegions) override
virtual void WritePackageTrailer (const IPackageWriter::FPackageTrailerInfo &Info, const FIoBuffer &Data) override
Protected Member Functions
virtual void CommitPackageInternal (FPackageRecord &&Record, const IPackageWriter::FCommitPackageInfo &Info)=0
virtual FPackageWriterRecords::FPackage * ConstructRecord ()
Construct a record for the package, called during BeginPackage.
FPackageRecord & FindRecordChecked (FName InPackageName)
Get the Record created by BeginPackage for the given PackageName; assert that it is valid.
void ValidateCommit (FPackageRecord &Record, const IPackageWriter::FCommitPackageInfo &Info)
Verify records from all Write functions are valid, and the required ones are present.
Protected Attributes
FPackageWriterRecords Records
Detailed Description
template<typename BaseInterface>
class TPackageWriterToSharedBuffer< BaseInterface >
A base class for IPackageWriter subclasses that writes to records that are read in CommitPackage.
To avoid diamond inheritance, this class specifies the interface it is implementing (either IPackageWriter or ICookedPackageWriter) by template. Subclasses should derive from one of TPackageWriterToSharedBuffer<IPackageWriter> TPackageWriterToSharedBuffer<ICookedPackageWriter>.
Definition at line 93 of file PackageWriterToSharedBuffer.h.
Member Typedef Documentation
FAdditionalFileRecord
template<typename BaseInterface> using TPackageWriterToSharedBuffer< BaseInterface >::FAdditionalFileRecord = FPackageWriterRecords::FAdditionalFile
Definition at line 98 of file PackageWriterToSharedBuffer.h.
FBulkDataRecord
template<typename BaseInterface> using TPackageWriterToSharedBuffer< BaseInterface >::FBulkDataRecord = FPackageWriterRecords::FBulkData
Definition at line 97 of file PackageWriterToSharedBuffer.h.
FLinkerAdditionalDataRecord
template<typename BaseInterface> using TPackageWriterToSharedBuffer< BaseInterface >::FLinkerAdditionalDataRecord = FPackageWriterRecords::FLinkerAdditionalData
Definition at line 99 of file PackageWriterToSharedBuffer.h.
FPackageRecord
template<typename BaseInterface> using TPackageWriterToSharedBuffer< BaseInterface >::FPackageRecord = FPackageWriterRecords::FPackage
Definition at line 101 of file PackageWriterToSharedBuffer.h.
FPackageTrailerRecord
template<typename BaseInterface> using TPackageWriterToSharedBuffer< BaseInterface >::FPackageTrailerRecord = FPackageWriterRecords::FPackageTrailer
Definition at line 100 of file PackageWriterToSharedBuffer.h.
FWritePackageRecord
template<typename BaseInterface> using TPackageWriterToSharedBuffer< BaseInterface >::FWritePackageRecord = FPackageWriterRecords::FWritePackage
Definition at line 96 of file PackageWriterToSharedBuffer.h.
Member Function Documentation
BeginPackage()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::BeginPackage (const IPackageWriter::FBeginPackageInfo & Info) inline override virtual
Definition at line 103 of file PackageWriterToSharedBuffer.h.
CommitPackage()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::CommitPackage (IPackageWriter::FCommitPackageInfo && Info) inline override virtual
Definition at line 131 of file PackageWriterToSharedBuffer.h.
CommitPackageInternal()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::CommitPackageInternal (FPackageRecord && Record, const IPackageWriter::FCommitPackageInfo & Info) protected pure virtual
Implemented in FDefaultCookedFilePackageWriter, and FPackageWriterToRecord.
Referenced by TPackageWriterToSharedBuffer< IPackageWriter >::CommitPackage().
ConstructRecord()
template<typename BaseInterface> virtual FPackageWriterRecords::FPackage * TPackageWriterToSharedBuffer< BaseInterface >::ConstructRecord () inline protected virtual
Construct a record for the package, called during BeginPackage.
Can be subclass of FPackage.
Reimplemented in FDefaultCookedFilePackageWriter.
Definition at line 144 of file PackageWriterToSharedBuffer.h.
Referenced by TPackageWriterToSharedBuffer< IPackageWriter >::BeginPackage().
FindRecordChecked()
template<typename BaseInterface> FPackageRecord & TPackageWriterToSharedBuffer< BaseInterface >::FindRecordChecked (FName InPackageName) inline protected
Get the Record created by BeginPackage for the given PackageName; assert that it is valid.
Definition at line 150 of file PackageWriterToSharedBuffer.h.
ValidateCommit()
template<typename BaseInterface> void TPackageWriterToSharedBuffer< BaseInterface >::ValidateCommit (FPackageRecord & Record, const IPackageWriter::FCommitPackageInfo & Info) inline protected
Verify records from all Write functions are valid, and the required ones are present.
Definition at line 155 of file PackageWriterToSharedBuffer.h.
Referenced by TPackageWriterToSharedBuffer< IPackageWriter >::CommitPackage().
WriteAdditionalFile()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::WriteAdditionalFile (const IPackageWriter::FAdditionalFileInfo & Info, const FIoBuffer & FileData) inline override virtual
Definition at line 117 of file PackageWriterToSharedBuffer.h.
WriteBulkData()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::WriteBulkData (const IPackageWriter::FBulkDataInfo & Info, const FIoBuffer & BulkData, const TArray< FFileRegion > & FileRegions) inline override virtual
Reimplemented in FDefaultCookedFilePackageWriter.
Definition at line 112 of file PackageWriterToSharedBuffer.h.
WriteLinkerAdditionalData()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::WriteLinkerAdditionalData (const IPackageWriter::FLinkerAdditionalDataInfo & Info, const FIoBuffer & Data, const TArray< FFileRegion > & FileRegions) inline override virtual
Definition at line 122 of file PackageWriterToSharedBuffer.h.
WritePackageData()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::WritePackageData (const IPackageWriter::FPackageInfo & Info, FLargeMemoryWriter & ExportsArchive, const TArray< FFileRegion > & FileRegions) inline override virtual
Reimplemented in FDefaultCookedFilePackageWriter.
Definition at line 107 of file PackageWriterToSharedBuffer.h.
WritePackageTrailer()
template<typename BaseInterface> virtual void TPackageWriterToSharedBuffer< BaseInterface >::WritePackageTrailer (const IPackageWriter::FPackageTrailerInfo & Info, const FIoBuffer & Data) inline override virtual
Definition at line 127 of file PackageWriterToSharedBuffer.h.
Field Documentation
Records
template<typename BaseInterface> FPackageWriterRecords TPackageWriterToSharedBuffer< BaseInterface >::Records protected
Definition at line 160 of file PackageWriterToSharedBuffer.h.
The documentation for this class was generated from the following file:
PackageWriterToSharedBuffer.h