Unreal Engine 5.6 C++ API: FPersonaModule Class Reference
FPersonaModule Class Reference
Persona module manages the lifetime of all instances of Persona editors.
#include "PersonaModule.h"
Data Structures
struct FCommonToolMenuExtensionArgs
Settings for AddCommonToolbarExtensions.
struct FNotifyHostAssetParameters
Public Types
typedef FCommonToolMenuExtensionArgs FCommonToolbarExtensionArgs
Public Member Functions
virtual void AddCommonMenuExtensions (UToolMenu *InToolMenu, const FCommonToolMenuExtensionArgs &InArgs=FCommonToolMenuExtensionArgs())
Add common menu extensions.
virtual void AddCommonToolbarExtensions (FToolBarBuilder &InToolbarBuilder, TSharedRef< IPersonaToolkit > PersonaToolkit, const FCommonToolbarExtensionArgs &InArgs=FCommonToolbarExtensionArgs())
Add common toobar extensions (legacy support) - DEPRECATED.
virtual void AddCommonToolbarExtensions (UToolMenu *InToolMenu, const FCommonToolMenuExtensionArgs &InArgs=FCommonToolMenuExtensionArgs())
Add common toolbar extensions.
virtual void AddLoopingInterpolation (TArray< TWeakObjectPtr< class UAnimSequence > > &AnimSequences)
Add looping interpolation to the list of animations.
virtual void ApplyCompression (TArray< TWeakObjectPtr< class UAnimSequence > > &AnimSequences, bool bPickBoneSettingsOverride)
Apply Compression to list of animations and optionally asks to pick an overrides to the bone compression settings.
virtual void BroadcastAssetFamilyChange () const
Broadcast event that all asset families need to change.
virtual TSharedRef< FWorkflowTabFactory > CreateAdvancedPreviewSceneTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< IPersonaPreviewScene > &InPreviewScene) const
Create a tab factory used to configure preview scene settings.
virtual TSharedRef< FWorkflowTabFactory > CreateAnimAssetFindReplaceTabFactory (const TSharedRef< FWorkflowCentricApplication > &InHostingApp, const FAnimAssetFindReplaceConfig &InConfig) const
Create a tab factory for finding and replacing in anim data.
virtual TSharedRef< FWorkflowTabFactory > CreateAnimationAssetBrowserTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< IPersonaToolkit > &InPersonaToolkit, FOnOpenNewAsset InOnOpenNewAsset, FOnAnimationSequenceBrowserCreated InOnAnimationSequenceBrowserCreated, bool bInShowHistory) const
Create a tab factory for the animation asset browser.
virtual TSharedRef< FWorkflowTabFactory > CreateAnimBlueprintAssetOverridesTabFactory (const TSharedRef< class FBlueprintEditor > &InBlueprintEditor, UAnimBlueprint *InAnimBlueprint, FSimpleMulticastDelegate &InOnPostUndo) const
Create a tab factory for editing anim blueprint parent overrides.
virtual TSharedRef< FWorkflowTabFactory > CreateAnimBlueprintPreviewTabFactory (const TSharedRef< class FBlueprintEditor > &InBlueprintEditor, const TSharedRef< IPersonaPreviewScene > &InPreviewScene) const
Create a tab factory for editing anim blueprint preview & defaults.
virtual TSharedRef< FWorkflowTabFactory > CreateAnimMontageSectionsTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< IPersonaToolkit > &InPersonaToolkit, FSimpleMulticastDelegate &InOnSectionsChanged) const
Create a tab factory for editing montage sections.
virtual TSharedRef< FWorkflowTabFactory > CreateAnimNotifiesTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< class IEditableSkeleton > &InEditableSkeleton, FOnObjectsSelected InOnObjectsSelected) const
Create an anim notifies tab factory.
virtual TSharedRef< FWorkflowTabFactory > CreateAssetDetailsTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, FOnGetAsset InOnGetAsset, FOnDetailsCreated InOnDetailsCreated) const
Create a tab factory for editing a single object (like an animation asset)
virtual TSharedRef< SWidget > CreateAssetFamilyShortcutWidget (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< class IAssetFamily > &InAssetFamily) const
Create a shortcut widget for an asset family.
virtual TSharedRef< FWorkflowTabFactory > CreateAttributeViewerTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< class IPersonaPreviewScene > &InPreviewScene) const
Create a attributes viewer tab factory.
virtual TSharedRef< SWidget > CreateBlendSpaceEditWidget (UBlendSpace *InBlendSpace, const FBlendSpaceEditorArgs &InArgs) const
Create a widget to edit a blendspace.
virtual TSharedRef< SWidget > CreateBlendSpacePreviewWidget (const FBlendSpacePreviewArgs &InArgs) const
Create a widget to preview a blendspace.
virtual TSharedRef< FWorkflowTabFactory > CreateCurveMetadataEditorTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, UObject *InMetadataHost, const TSharedRef< class IPersonaPreviewScene > &InPreviewScene, FOnObjectsSelected InOnObjectsSelected) const
Create a skeleton curve metadata editor tab factory.
virtual TSharedRef< SWidget > CreateCurvePicker (const USkeleton *InSkeleton, FOnCurvePicked InOnCurvePicked, FIsCurveNameMarkedForExclusion InIsCurveNameMarkedForExclusion=FIsCurveNameMarkedForExclusion())
Create a widget that can choose a curve name.
virtual TSharedRef< FWorkflowTabFactory > CreateCurveViewerTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedPtr< class IEditableSkeleton > &InEditableSkeleton, const TSharedRef< class IPersonaPreviewScene > &InPreviewScene, FOnObjectsSelected InOnObjectsSelected) const
Create a skeleton curve viewer tab factory.
virtual TSharedRef< IAnimSequenceCurveEditor > CreateCurveWidgetForAnimDocument (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< IPersonaPreviewScene > &InPreviewScene, UAnimSequenceBase *InAnimSequence, const TSharedPtr< ITimeSliderController > &InExternalTimeSliderController, const TSharedPtr< FTabManager > &InTabManager)
Create a widget that acts as a curve document for an animation asset.
virtual TSharedRef< IMorphTargetViewer > CreateDefaultMorphTargetViewerWidget (const TSharedRef< IPersonaPreviewScene > &InPreviewScene, FSimpleMulticastDelegate &OnPostUndo) const
Create the default morph target viewer widget.
virtual TSharedRef< FWorkflowTabFactory > CreateDetailsTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, FOnDetailsCreated InOnDetailsCreated) const
Create a details panel tab factory.
virtual TSharedRef< SWidget > CreateEditorWidgetForAnimDocument (const TSharedRef< IAnimationEditor > &InHostingApp, UObject *InAnimAsset, const FAnimDocumentArgs &InArgs, FString &OutDocumentLink)
Create a widget that acts as a document for an animation asset.
virtual TSharedRef< SWidget > CreateFindReplaceWidget (const FAnimAssetFindReplaceConfig &InConfig) const
Create a widget for finding and replacing in anim data.
virtual TSharedRef< FWorkflowTabFactory > CreateMorphTargetTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< IPersonaPreviewScene > &InPreviewScene, FSimpleMulticastDelegate &OnPostUndo) const
Create a tab factory for for previewing morph targets.
virtual TSharedRef< FWorkflowTabFactory > CreateMorphTargetTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, TSharedRef< IMorphTargetViewer > InViewerWidget) const
Create a tab factory for for previewing morph targets.
virtual TSharedRef< SWidget > CreateMultiCurvePicker (const USkeleton *InSkeleton, FOnCurvesPicked InOnCurvesPicked, FIsCurveNameMarkedForExclusion InIsCurveNameMarkedForExclusion=FIsCurveNameMarkedForExclusion())
Create a widget that can choose multiple curve names.
virtual TSharedRef< IAssetFamily > CreatePersonaAssetFamily (const UObject *InAsset) const
Create an asset family for the supplied persona asset.
virtual class IPersonaEditorModeManager * CreatePersonaEditorModeManager ()
Create a Persona editor mode manager.
virtual TSharedRef< FWorkflowTabFactory > CreatePersonaToolboxTabFactory (const TSharedRef< class FPersonaAssetEditorToolkit > &InHostingApp) const
Create a toolbox tab factory.
virtual TSharedRef< IPersonaToolkit > CreatePersonaToolkit (UAnimationAsset *InAnimationAsset, const FPersonaToolkitArgs &PersonaToolkitArgs) const
virtual TSharedRef< IPersonaToolkit > CreatePersonaToolkit (UAnimBlueprint *InAnimBlueprint, const FPersonaToolkitArgs &PersonaToolkitArgs) const
virtual TSharedRef< IPersonaToolkit > CreatePersonaToolkit (UObject *InAsset, const FPersonaToolkitArgs &PersonaToolkitArgs, USkeleton *InSkeleton=nullptr) const
Create a re-usable toolkit that multiple asset editors that are concerned with USkeleton-related data can use.
virtual TSharedRef< IPersonaToolkit > CreatePersonaToolkit (UPhysicsAsset *InPhysicsAsset, const FPersonaToolkitArgs &PersonaToolkitArgs) const
virtual TSharedRef< IPersonaToolkit > CreatePersonaToolkit (USkeletalMesh *InSkeletalMesh, const FPersonaToolkitArgs &PersonaToolkitArgs) const
virtual TSharedRef< IPersonaToolkit > CreatePersonaToolkit (USkeleton *InSkeleton, const FPersonaToolkitArgs &PersonaToolkitArgs) const
virtual TSharedRef< FWorkflowTabFactory > CreatePersonaViewportTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const FPersonaViewportArgs &InArgs) const
Create a persona viewport tab factory.
virtual TSharedRef< FWorkflowTabFactory > CreatePoseWatchTabFactory (const TSharedRef< class FBlueprintEditor > &InBlueprintEditor) const
Create a tab factory for the pose watch manager.
virtual TSharedRef< FWorkflowTabFactory > CreateRetargetSourcesTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< class IEditableSkeleton > &InEditableSkeleton, FSimpleMulticastDelegate &InOnPostUndo) const
Create a retarget sources tab factory.
virtual TSharedRef< SWidget > CreateSkeletonNotifyPicker (FOnNotifyPicked InOnNotifyPicked, TSharedPtr< IEditableSkeleton > InEditableSkeleton=nullptr, TSharedPtr< FAssetEditorToolkit > InHostingApp=nullptr, bool bInShowSyncMarkers=false, bool bInShowNotifies=true, bool bInShowCompatibleSkeletonAssets=true, bool bInShowOtherAssets=true)
Create a widget that can choose a notify name.
virtual TSharedRef< FWorkflowTabFactory > CreateSkeletonSlotNamesTabFactory (const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const TSharedRef< class IEditableSkeleton > &InEditableSkeleton, FOnObjectSelected InOnObjectSelected) const
Create a tab factory for editing slot names and groups.
virtual void CustomizeBlueprintEditorDetails (const TSharedRef< class IDetailsView > &InDetailsView, FOnInvokeTab InOnInvokeTab)
Customize the details of a slot node for the specified details view.
virtual void CustomizeMeshDetails (const TSharedRef< IDetailsView > &InDetailsView, const TSharedRef< IPersonaToolkit > &InPersonaToolkit)
Customize a skeletal mesh details panel.
DECLARE_DELEGATE_TwoParams (FOnCustomizeMeshDetails, IDetailLayoutBuilder &DetailLayout, TWeakObjectPtr< USkeletalMesh > SkeletalMesh)
Delegates that allow customizing the mesh details layout and are called from within PersonaMeshDetails' CustomizeDetails().
virtual bool ExportToFBX (TArray< TWeakObjectPtr< class UAnimSequence > > &AnimSequences, USkeletalMesh *SkeletalMesh)
Export to FBX files of the list of animations.
virtual const FNotifyHostAssetParameters * FindNotifyHostAsset (UObject *InAsset)
virtual TArray< FTopLevelAssetPath > GetAllNotifyHostAssetClassPaths () const
const TArray< TSharedPtr< IBlendProfilePickerExtender > > & GetCustomBlendProfiles () const
virtual TArray< FOnCustomizeMeshDetails > & GetCustomizeMeshDetailsDelegates ()
virtual TSharedPtr< FExtensibilityManager > GetMenuExtensibilityManager ()
Gets the extensibility managers for outside entities to extend persona editor's menus and toolbars.
virtual uint32 GetNotifyHostAssetVersion () const
virtual TSharedPtr< FExtensibilityManager > GetToolBarExtensibilityManager ()
virtual void ImportNewAsset (USkeleton *InSkeleton, EFBXImportType DefaultImportType)
Import a new asset using the supplied skeleton.
virtual FGetCurrentRecording & OnGetCurrentRecording ()
Delegate used to get the currently recording animation.
virtual FGetCurrentRecordingTime & OnGetCurrentRecordingTime ()
Delegate used to get the currently recording animation time.
virtual FIsRecordingActive & OnIsRecordingActive ()
Delegate used to query whether recording is active.
virtual FOnPreviewSceneCreated & OnPreviewSceneCreated ()
Delegate broadcast when a preview scene is created.
virtual FRecord & OnRecord ()
Delegate used to start recording animation.
virtual FOnRegisterLayoutExtensions & OnRegisterLayoutExtensions ()
Register common layout extensions.
virtual FOnRegisterTabs & OnRegisterTabs ()
Register common tabs.
virtual FStopRecording & OnStopRecording ()
Delegate used to stop recording animation.
virtual void RecordAssetOpened (const FAssetData &InAssetData) const
Record that an asset was opened (forward to relevant asset families)
PERSONA_API void RegisterBlendProfilePickerExtender (TSharedPtr< IBlendProfilePickerExtender > Extender)
virtual void RegisterNotifyHostAsset (const FTopLevelAssetPath &InAssetClassPath, const FNotifyHostAssetParameters &InParameters)
virtual void RegisterPersonaViewportTabFactories (FWorkflowAllowedTabSet &TabSet, const TSharedRef< class FWorkflowCentricApplication > &InHostingApp, const FPersonaViewportArgs &InArgs) const
Register 4 Persona viewport tab factories.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module's DLL has been loaded and the module object has been created.
virtual void TestSkeletonCurveMetaDataForUse (const TSharedRef< IEditableSkeleton > &InEditableSkeleton) const
Check all animations & skeletal meshes for curve metadata usage.
UE_DEPRECATED (4.24, "Function renamed, please use CustomizeBlueprintEditorDetails") virtual void CustomizeSlotNodeDetails(const TSharedRef< class IDetailsView > &InDetailsView
UE_DEPRECATED (5.0, "Please use the overload that does not take a post-undo delegate") virtual TSharedRef< FWorkflowTabFactory > CreateCurveViewerTabFactory(const TSharedRef< class FWorkflowCentricApplication > &InHostingApp
UE_DEPRECATED (5.0, "Please use the overload that does not take a post-undo delegate") virtual TSharedRef< FWorkflowTabFactory > CreateSkeletonSlotNamesTabFactory(const TSharedRef< class FWorkflowCentricApplication > &InHostingApp
UE_DEPRECATED (5.0, "Please use the overload that takes a FBlendSpacePreviewArgs struct") virtual TSharedRef< SWidget > CreateBlendSpacePreviewWidget(TAttribute< const UBlendSpace * > InBlendSpace
Deprecated.
UE_DEPRECATED (5.3, "Please use CreateCurvePicker that takes a const USkeleton*") virtual TSharedRef< SWidget > CreateCurvePicker(TSharedRef< IEditableSkeleton > InEditableSkeleton
UE_DEPRECATED (5.3, "Please use TestSkeletonCurveMetaDataForUse") virtual void TestSkeletonCurveNamesForUse(const TSharedRef< IEditableSkeleton > &InEditableSkeleton) const
PERSONA_API void UnregisterBlendProfilePickerExtender (const FName ExtenderId)
virtual void UnregisterNotifyHostAsset (const FTopLevelAssetPath &InAssetClassPath)
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Data Fields
const TSharedPtr< class IEditableSkeleton > const TSharedRef< class IPersonaPreviewScene > FSimpleMulticastDelegate FOnObjectsSelected InOnObjectsSelected const
const TSharedRef< class IEditableSkeleton > FSimpleMulticastDelegate FOnObjectSelected InOnObjectSelected const
TAttribute< FVector > TAttribute< FVector > InFilteredBlendPosition const
TAttribute< FVector > InBlendPosition
const TSharedPtr< class IEditableSkeleton > & InEditableSkeleton
const TSharedRef< class IEditableSkeleton > & InEditableSkeleton
FOnCurvePicked FIsCurveNameMarkedForExclusion InIsCurveNameMarkedForExclusion = FIsCurveNameMarkedForExclusion())
FOnCurvePicked InOnCurvePicked
FOnInvokeTab InOnInvokeTab { CustomizeBlueprintEditorDetails(InDetailsView, InOnInvokeTab)
const TSharedPtr< class IEditableSkeleton > const TSharedRef< class IPersonaPreviewScene > FSimpleMulticastDelegate & InOnPostUndo
const TSharedRef< class IEditableSkeleton > FSimpleMulticastDelegate & InOnPostUndo
const TSharedPtr< class IEditableSkeleton > const TSharedRef< class IPersonaPreviewScene > & InPreviewScene
Private Types
enum class EPoseSourceOption : uint8 {
ReferencePose , CurrentPose , CurrentAnimation_AnimData , CurrentAnimation_PreviewMesh ,
Max
}
Options for asset creation.
Private Member Functions
void HandleNewAnimNotifyBlueprintCreated (UBlueprint *InBlueprint)
When a new anim notify blueprint is created, this will handle post creation work such as adding non-event default nodes.
void HandleNewAnimNotifyStateBlueprintCreated (UBlueprint *InBlueprint)
When a new anim notify state blueprint is created, this will handle post creation work such as adding non-event default nodes.
void RegisterToolMenuExtensions ()
Static Private Member Functions
static bool CreateAnimation (const TArray< UObject * > NewAssets, const EPoseSourceOption Option, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
static bool CreatePoseAsset (const TArray< UObject * > NewAssets, const EPoseSourceOption Option, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
static void FillCreateAnimationFromCurrentAnimationMenu (FMenuBuilder &MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
static void FillCreateAnimationMenu (FMenuBuilder &MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
static void FillCreatePoseAssetMenu (FMenuBuilder &MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
static void FillInsertPoseMenu (FMenuBuilder &MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
static TSharedRef< SWidget > GenerateCreateAssetMenu (TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
static bool HandleAssetCreated (const TArray< UObject * > NewAssets)
static void InsertCurrentPoseToAsset (const FAssetData &NewPoseAssetData, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit)
Private Attributes
TArray< TSharedPtr< IBlendProfilePickerExtender > > CustomBlendProfiles
TArray< FOnCustomizeMeshDetails > CustomizeMeshDetailLayoutDelegates
FGetCurrentRecording GetCurrentRecordingDelegate
Delegate used to get the currently recording animation.
FGetCurrentRecordingTime GetCurrentRecordingTimeDelegate
Delegate used to get the currently recording animation time.
FIsRecordingActive IsRecordingActiveDelegate
Delegate used to query whether recording is active.
TSharedPtr< FExtensibilityManager > MenuExtensibilityManager
uint32 NotifyHostAssetVersion = 0
Version counter for NotifyHostParameters.
TMap< FTopLevelAssetPath, FNotifyHostAssetParameters > NotifyHostParameters
Parameters for notify hosts.
FOnPreviewSceneCreated OnPreviewSceneCreatedDelegate
Delegate broadcast when a preview scene is created.
FOnRegisterLayoutExtensions OnRegisterLayoutExtensionsDelegate
Delegate broadcast to register common layout extensions.
FOnRegisterTabs OnRegisterTabsDelegate
Delegate broadcast to register common tabs.
FRecord RecordDelegate
Delegate used to start recording animation.
FStopRecording StopRecordingDelegate
Delegate used to stop recording animation.
FTickRecording TickRecordingDelegate
Delegate used to tick the skelmesh component recording.
TSharedPtr< FExtensibilityManager > ToolBarExtensibilityManager
Detailed Description
Persona module manages the lifetime of all instances of Persona editors.
Definition at line 318 of file PersonaModule.h.
Member Typedef Documentation
FCommonToolbarExtensionArgs
typedef FCommonToolMenuExtensionArgs FPersonaModule::FCommonToolbarExtensionArgs
Definition at line 519 of file PersonaModule.h.
Member Enumeration Documentation
EPoseSourceOption
enum class FPersonaModule::EPoseSourceOption : uint8 strong private
Options for asset creation.
Enumerator
ReferencePose
CurrentPose
CurrentAnimation_AnimData
CurrentAnimation_PreviewMesh
Max
Definition at line 593 of file PersonaModule.h.
Member Function Documentation
AddCommonMenuExtensions()
virtual void FPersonaModule::AddCommonMenuExtensions (UToolMenu * InToolMenu, const FCommonToolMenuExtensionArgs & InArgs = FCommonToolMenuExtensionArgs()) virtual
Add common menu extensions.
AddCommonToolbarExtensions() [1/2]
virtual void FPersonaModule::AddCommonToolbarExtensions (FToolBarBuilder & InToolbarBuilder, TSharedRef< IPersonaToolkit > PersonaToolkit, const FCommonToolbarExtensionArgs & InArgs = FCommonToolbarExtensionArgs()) virtual
Add common toobar extensions (legacy support) - DEPRECATED.
AddCommonToolbarExtensions() [2/2]
virtual void FPersonaModule::AddCommonToolbarExtensions (UToolMenu * InToolMenu, const FCommonToolMenuExtensionArgs & InArgs = FCommonToolMenuExtensionArgs()) virtual
Add common toolbar extensions.
AddLoopingInterpolation()
virtual void FPersonaModule::AddLoopingInterpolation (TArray< TWeakObjectPtr< class UAnimSequence > > & AnimSequences) virtual
Add looping interpolation to the list of animations.
ApplyCompression()
virtual void FPersonaModule::ApplyCompression (TArray< TWeakObjectPtr< class UAnimSequence > > & AnimSequences, bool bPickBoneSettingsOverride) virtual
Apply Compression to list of animations and optionally asks to pick an overrides to the bone compression settings.
BroadcastAssetFamilyChange()
virtual void FPersonaModule::BroadcastAssetFamilyChange () const virtual
Broadcast event that all asset families need to change.
CreateAdvancedPreviewSceneTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAdvancedPreviewSceneTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< IPersonaPreviewScene > & InPreviewScene) const virtual
Create a tab factory used to configure preview scene settings.
References const, CreateAdvancedPreviewSceneTabFactory(), and InPreviewScene.
Referenced by CreateAdvancedPreviewSceneTabFactory().
CreateAnimAssetFindReplaceTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAnimAssetFindReplaceTabFactory (const TSharedRef< FWorkflowCentricApplication > & InHostingApp, const FAnimAssetFindReplaceConfig & InConfig) const virtual
Create a tab factory for finding and replacing in anim data.
References const, and CreateAnimAssetFindReplaceTabFactory().
Referenced by CreateAnimAssetFindReplaceTabFactory().
CreateAnimation()
bool FPersonaModule::CreateAnimation (const TArray< UObject * > NewAssets, const EPoseSourceOption Option, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
CreateAnimationAssetBrowserTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAnimationAssetBrowserTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< IPersonaToolkit > & InPersonaToolkit, FOnOpenNewAsset InOnOpenNewAsset, FOnAnimationSequenceBrowserCreated InOnAnimationSequenceBrowserCreated, bool bInShowHistory) const virtual
Create a tab factory for the animation asset browser.
References const, and CreateAnimationAssetBrowserTabFactory().
Referenced by CreateAnimationAssetBrowserTabFactory().
CreateAnimBlueprintAssetOverridesTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAnimBlueprintAssetOverridesTabFactory (const TSharedRef< class FBlueprintEditor > & InBlueprintEditor, UAnimBlueprint * InAnimBlueprint, FSimpleMulticastDelegate & InOnPostUndo) const virtual
Create a tab factory for editing anim blueprint parent overrides.
References const, CreateAnimBlueprintAssetOverridesTabFactory(), and InOnPostUndo.
Referenced by CreateAnimBlueprintAssetOverridesTabFactory().
CreateAnimBlueprintPreviewTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAnimBlueprintPreviewTabFactory (const TSharedRef< class FBlueprintEditor > & InBlueprintEditor, const TSharedRef< IPersonaPreviewScene > & InPreviewScene) const virtual
Create a tab factory for editing anim blueprint preview & defaults.
References const, CreateAnimBlueprintPreviewTabFactory(), and InPreviewScene.
Referenced by CreateAnimBlueprintPreviewTabFactory().
CreateAnimMontageSectionsTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAnimMontageSectionsTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< IPersonaToolkit > & InPersonaToolkit, FSimpleMulticastDelegate & InOnSectionsChanged) const virtual
Create a tab factory for editing montage sections.
References const, and CreateAnimMontageSectionsTabFactory().
Referenced by CreateAnimMontageSectionsTabFactory().
CreateAnimNotifiesTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAnimNotifiesTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< class IEditableSkeleton > & InEditableSkeleton, FOnObjectsSelected InOnObjectsSelected) const virtual
Create an anim notifies tab factory.
References InEditableSkeleton.
CreateAssetDetailsTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAssetDetailsTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, FOnGetAsset InOnGetAsset, FOnDetailsCreated InOnDetailsCreated) const virtual
Create a tab factory for editing a single object (like an animation asset)
References const, and CreateAssetDetailsTabFactory().
Referenced by CreateAssetDetailsTabFactory().
CreateAssetFamilyShortcutWidget()
virtual TSharedRef< SWidget > FPersonaModule::CreateAssetFamilyShortcutWidget (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< class IAssetFamily > & InAssetFamily) const virtual
Create a shortcut widget for an asset family.
CreateAttributeViewerTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateAttributeViewerTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< class IPersonaPreviewScene > & InPreviewScene) const virtual
Create a attributes viewer tab factory.
References const, CreateAttributeViewerTabFactory(), and InPreviewScene.
Referenced by CreateAttributeViewerTabFactory().
CreateBlendSpaceEditWidget()
virtual TSharedRef< SWidget > FPersonaModule::CreateBlendSpaceEditWidget (UBlendSpace * InBlendSpace, const FBlendSpaceEditorArgs & InArgs) const virtual
Create a widget to edit a blendspace.
References const, and CreateBlendSpaceEditWidget().
Referenced by CreateBlendSpaceEditWidget().
CreateBlendSpacePreviewWidget()
virtual TSharedRef< SWidget > FPersonaModule::CreateBlendSpacePreviewWidget (const FBlendSpacePreviewArgs & InArgs) const virtual
Create a widget to preview a blendspace.
References const, and CreateBlendSpacePreviewWidget().
Referenced by CreateBlendSpacePreviewWidget().
CreateCurveMetadataEditorTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateCurveMetadataEditorTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, UObject * InMetadataHost, const TSharedRef< class IPersonaPreviewScene > & InPreviewScene, FOnObjectsSelected InOnObjectsSelected) const virtual
Create a skeleton curve metadata editor tab factory.
References const, CreateCurveMetadataEditorTabFactory(), and InPreviewScene.
Referenced by CreateCurveMetadataEditorTabFactory().
CreateCurvePicker()
virtual TSharedRef< SWidget > FPersonaModule::CreateCurvePicker (const USkeleton * InSkeleton, FOnCurvePicked InOnCurvePicked, FIsCurveNameMarkedForExclusion InIsCurveNameMarkedForExclusion = FIsCurveNameMarkedForExclusion()) virtual
Create a widget that can choose a curve name.
Derives available names from the asset registry list of assets that use the specified skeleton.
References InIsCurveNameMarkedForExclusion, and InOnCurvePicked.
CreateCurveViewerTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateCurveViewerTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedPtr< class IEditableSkeleton > & InEditableSkeleton, const TSharedRef< class IPersonaPreviewScene > & InPreviewScene, FOnObjectsSelected InOnObjectsSelected) const virtual
Create a skeleton curve viewer tab factory.
References const, CreateCurveViewerTabFactory(), InEditableSkeleton, and InPreviewScene.
Referenced by CreateCurveViewerTabFactory().
CreateCurveWidgetForAnimDocument()
virtual TSharedRef< IAnimSequenceCurveEditor > FPersonaModule::CreateCurveWidgetForAnimDocument (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< IPersonaPreviewScene > & InPreviewScene, UAnimSequenceBase * InAnimSequence, const TSharedPtr< ITimeSliderController > & InExternalTimeSliderController, const TSharedPtr< FTabManager > & InTabManager) virtual
Create a widget that acts as a curve document for an animation asset.
References const, CreateCurveWidgetForAnimDocument(), and InPreviewScene.
Referenced by CreateCurveWidgetForAnimDocument().
CreateDefaultMorphTargetViewerWidget()
virtual TSharedRef< IMorphTargetViewer > FPersonaModule::CreateDefaultMorphTargetViewerWidget (const TSharedRef< IPersonaPreviewScene > & InPreviewScene, FSimpleMulticastDelegate & OnPostUndo) const virtual
Create the default morph target viewer widget.
References const, CreateDefaultMorphTargetViewerWidget(), and InPreviewScene.
Referenced by CreateDefaultMorphTargetViewerWidget().
CreateDetailsTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateDetailsTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, FOnDetailsCreated InOnDetailsCreated) const virtual
Create a details panel tab factory.
CreateEditorWidgetForAnimDocument()
virtual TSharedRef< SWidget > FPersonaModule::CreateEditorWidgetForAnimDocument (const TSharedRef< IAnimationEditor > & InHostingApp, UObject * InAnimAsset, const FAnimDocumentArgs & InArgs, FString & OutDocumentLink) virtual
Create a widget that acts as a document for an animation asset.
References const, and CreateEditorWidgetForAnimDocument().
Referenced by CreateEditorWidgetForAnimDocument().
CreateFindReplaceWidget()
virtual TSharedRef< SWidget > FPersonaModule::CreateFindReplaceWidget (const FAnimAssetFindReplaceConfig & InConfig) const virtual
Create a widget for finding and replacing in anim data.
References const, and CreateFindReplaceWidget().
Referenced by CreateFindReplaceWidget().
CreateMorphTargetTabFactory() [1/2]
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateMorphTargetTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< IPersonaPreviewScene > & InPreviewScene, FSimpleMulticastDelegate & OnPostUndo) const virtual
Create a tab factory for for previewing morph targets.
References const, CreateMorphTargetTabFactory(), and InPreviewScene.
Referenced by CreateMorphTargetTabFactory(), and CreateMorphTargetTabFactory().
CreateMorphTargetTabFactory() [2/2]
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateMorphTargetTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, TSharedRef< IMorphTargetViewer > InViewerWidget) const virtual
Create a tab factory for for previewing morph targets.
References const, and CreateMorphTargetTabFactory().
CreateMultiCurvePicker()
virtual TSharedRef< SWidget > FPersonaModule::CreateMultiCurvePicker (const USkeleton * InSkeleton, FOnCurvesPicked InOnCurvesPicked, FIsCurveNameMarkedForExclusion InIsCurveNameMarkedForExclusion = FIsCurveNameMarkedForExclusion()) virtual
Create a widget that can choose multiple curve names.
Derives available names from the asset registry list of assets that use the specified skeleton.
References InIsCurveNameMarkedForExclusion.
CreatePersonaAssetFamily()
virtual TSharedRef< IAssetFamily > FPersonaModule::CreatePersonaAssetFamily (const UObject * InAsset) const virtual
Create an asset family for the supplied persona asset.
CreatePersonaEditorModeManager()
virtual class IPersonaEditorModeManager * FPersonaModule::CreatePersonaEditorModeManager () virtual
Create a Persona editor mode manager.
Should be destroyed using plain ol' delete. Note: Only FPersonaEditMode-derived modes should be used with this manager!
CreatePersonaToolboxTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreatePersonaToolboxTabFactory (const TSharedRef< class FPersonaAssetEditorToolkit > & InHostingApp) const virtual
Create a toolbox tab factory.
References const, and CreatePersonaToolboxTabFactory().
Referenced by CreatePersonaToolboxTabFactory().
CreatePersonaToolkit() [1/6]
virtual TSharedRef< IPersonaToolkit > FPersonaModule::CreatePersonaToolkit (UAnimationAsset * InAnimationAsset, const FPersonaToolkitArgs & PersonaToolkitArgs) const virtual
CreatePersonaToolkit() [2/6]
virtual TSharedRef< IPersonaToolkit > FPersonaModule::CreatePersonaToolkit (UAnimBlueprint * InAnimBlueprint, const FPersonaToolkitArgs & PersonaToolkitArgs) const virtual
CreatePersonaToolkit() [3/6]
virtual TSharedRef< IPersonaToolkit > FPersonaModule::CreatePersonaToolkit (UObject * InAsset, const FPersonaToolkitArgs & PersonaToolkitArgs, USkeleton * InSkeleton = nullptr) const virtual
Create a re-usable toolkit that multiple asset editors that are concerned with USkeleton-related data can use.
CreatePersonaToolkit() [4/6]
virtual TSharedRef< IPersonaToolkit > FPersonaModule::CreatePersonaToolkit (UPhysicsAsset * InPhysicsAsset, const FPersonaToolkitArgs & PersonaToolkitArgs) const virtual
CreatePersonaToolkit() [5/6]
virtual TSharedRef< IPersonaToolkit > FPersonaModule::CreatePersonaToolkit (USkeletalMesh * InSkeletalMesh, const FPersonaToolkitArgs & PersonaToolkitArgs) const virtual
CreatePersonaToolkit() [6/6]
virtual TSharedRef< IPersonaToolkit > FPersonaModule::CreatePersonaToolkit (USkeleton * InSkeleton, const FPersonaToolkitArgs & PersonaToolkitArgs) const virtual
CreatePersonaViewportTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreatePersonaViewportTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const FPersonaViewportArgs & InArgs) const virtual
Create a persona viewport tab factory.
CreatePoseAsset()
bool FPersonaModule::CreatePoseAsset (const TArray< UObject * > NewAssets, const EPoseSourceOption Option, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
CreatePoseWatchTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreatePoseWatchTabFactory (const TSharedRef< class FBlueprintEditor > & InBlueprintEditor) const virtual
Create a tab factory for the pose watch manager.
References const, and CreatePoseWatchTabFactory().
Referenced by CreatePoseWatchTabFactory().
CreateRetargetSourcesTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateRetargetSourcesTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< class IEditableSkeleton > & InEditableSkeleton, FSimpleMulticastDelegate & InOnPostUndo) const virtual
Create a retarget sources tab factory.
References const, CreateRetargetSourcesTabFactory(), InEditableSkeleton, and InOnPostUndo.
Referenced by CreateRetargetSourcesTabFactory().
CreateSkeletonNotifyPicker()
virtual TSharedRef< SWidget > FPersonaModule::CreateSkeletonNotifyPicker (FOnNotifyPicked InOnNotifyPicked, TSharedPtr< IEditableSkeleton > InEditableSkeleton = nullptr, TSharedPtr< FAssetEditorToolkit > InHostingApp = nullptr, bool bInShowSyncMarkers = false, bool bInShowNotifies = true, bool bInShowCompatibleSkeletonAssets = true, bool bInShowOtherAssets = true) virtual
Create a widget that can choose a notify name.
See also
SSkeletonAnimNotifies.
References CreateSkeletonNotifyPicker(), and InEditableSkeleton.
Referenced by CreateSkeletonNotifyPicker().
CreateSkeletonSlotNamesTabFactory()
virtual TSharedRef< FWorkflowTabFactory > FPersonaModule::CreateSkeletonSlotNamesTabFactory (const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const TSharedRef< class IEditableSkeleton > & InEditableSkeleton, FOnObjectSelected InOnObjectSelected) const virtual
Create a tab factory for editing slot names and groups.
References const, CreateSkeletonSlotNamesTabFactory(), and InEditableSkeleton.
Referenced by CreateSkeletonSlotNamesTabFactory().
CustomizeBlueprintEditorDetails()
virtual void FPersonaModule::CustomizeBlueprintEditorDetails (const TSharedRef< class IDetailsView > & InDetailsView, FOnInvokeTab InOnInvokeTab) virtual
Customize the details of a slot node for the specified details view.
References InOnInvokeTab.
CustomizeMeshDetails()
virtual void FPersonaModule::CustomizeMeshDetails (const TSharedRef< IDetailsView > & InDetailsView, const TSharedRef< IPersonaToolkit > & InPersonaToolkit) virtual
Customize a skeletal mesh details panel.
References const, and CustomizeMeshDetails().
Referenced by CustomizeMeshDetails().
DECLARE_DELEGATE_TwoParams()
FPersonaModule::DECLARE_DELEGATE_TwoParams (FOnCustomizeMeshDetails , IDetailLayoutBuilder & DetailLayout, TWeakObjectPtr< USkeletalMesh > SkeletalMesh)
Delegates that allow customizing the mesh details layout and are called from within PersonaMeshDetails' CustomizeDetails().
References SkeletalMesh.
ExportToFBX()
virtual bool FPersonaModule::ExportToFBX (TArray< TWeakObjectPtr< class UAnimSequence > > & AnimSequences, USkeletalMesh * SkeletalMesh) virtual
Export to FBX files of the list of animations.
References SkeletalMesh.
FillCreateAnimationFromCurrentAnimationMenu()
void FPersonaModule::FillCreateAnimationFromCurrentAnimationMenu (FMenuBuilder & MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
FillCreateAnimationMenu()
void FPersonaModule::FillCreateAnimationMenu (FMenuBuilder & MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
FillCreatePoseAssetMenu()
void FPersonaModule::FillCreatePoseAssetMenu (FMenuBuilder & MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
FillInsertPoseMenu()
void FPersonaModule::FillInsertPoseMenu (FMenuBuilder & MenuBuilder, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
FindNotifyHostAsset()
virtual const FNotifyHostAssetParameters * FPersonaModule::FindNotifyHostAsset (UObject * InAsset) virtual
GenerateCreateAssetMenu()
TSharedRef< SWidget > FPersonaModule::GenerateCreateAssetMenu (TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
GetAllNotifyHostAssetClassPaths()
virtual TArray< FTopLevelAssetPath > FPersonaModule::GetAllNotifyHostAssetClassPaths () const virtual
GetCustomBlendProfiles()
const TArray< TSharedPtr< IBlendProfilePickerExtender > > & FPersonaModule::GetCustomBlendProfiles () const
GetCustomizeMeshDetailsDelegates()
virtual TArray< FOnCustomizeMeshDetails > & FPersonaModule::GetCustomizeMeshDetailsDelegates () inline virtual
Definition at line 494 of file PersonaModule.h.
References CustomizeMeshDetailLayoutDelegates.
GetMenuExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > FPersonaModule::GetMenuExtensibilityManager () inline virtual
Gets the extensibility managers for outside entities to extend persona editor's menus and toolbars.
Implements IHasMenuExtensibility.
Definition at line 444 of file PersonaModule.h.
References GetMenuExtensibilityManager(), and MenuExtensibilityManager.
Referenced by GetMenuExtensibilityManager().
GetNotifyHostAssetVersion()
virtual uint32 FPersonaModule::GetNotifyHostAssetVersion () const virtual
GetToolBarExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > FPersonaModule::GetToolBarExtensibilityManager () inline virtual
Definition at line 445 of file PersonaModule.h.
References ToolBarExtensibilityManager.
HandleAssetCreated()
bool FPersonaModule::HandleAssetCreated (const TArray< UObject * > NewAssets) static private
HandleNewAnimNotifyBlueprintCreated()
void FPersonaModule::HandleNewAnimNotifyBlueprintCreated (UBlueprint * InBlueprint) private
When a new anim notify blueprint is created, this will handle post creation work such as adding non-event default nodes.
HandleNewAnimNotifyStateBlueprintCreated()
void FPersonaModule::HandleNewAnimNotifyStateBlueprintCreated (UBlueprint * InBlueprint) private
When a new anim notify state blueprint is created, this will handle post creation work such as adding non-event default nodes.
ImportNewAsset()
virtual void FPersonaModule::ImportNewAsset (USkeleton * InSkeleton, EFBXImportType DefaultImportType) virtual
Import a new asset using the supplied skeleton.
InsertCurrentPoseToAsset()
void FPersonaModule::InsertCurrentPoseToAsset (const FAssetData & NewPoseAssetData, TWeakPtr< IPersonaToolkit > InWeakPersonaToolkit) static private
OnGetCurrentRecording()
virtual FGetCurrentRecording & FPersonaModule::OnGetCurrentRecording () inline virtual
Delegate used to get the currently recording animation.
Definition at line 484 of file PersonaModule.h.
References GetCurrentRecordingDelegate.
OnGetCurrentRecordingTime()
virtual FGetCurrentRecordingTime & FPersonaModule::OnGetCurrentRecordingTime () inline virtual
Delegate used to get the currently recording animation time.
Definition at line 487 of file PersonaModule.h.
References GetCurrentRecordingTimeDelegate.
OnIsRecordingActive()
virtual FIsRecordingActive & FPersonaModule::OnIsRecordingActive () inline virtual
Delegate used to query whether recording is active.
Definition at line 475 of file PersonaModule.h.
References IsRecordingActiveDelegate.
OnPreviewSceneCreated()
virtual FOnPreviewSceneCreated & FPersonaModule::OnPreviewSceneCreated () inline virtual
Delegate broadcast when a preview scene is created.
Definition at line 490 of file PersonaModule.h.
References OnPreviewSceneCreatedDelegate.
OnRecord()
virtual FRecord & FPersonaModule::OnRecord () inline virtual
Delegate used to start recording animation.
Definition at line 478 of file PersonaModule.h.
References RecordDelegate.
OnRegisterLayoutExtensions()
virtual FOnRegisterLayoutExtensions & FPersonaModule::OnRegisterLayoutExtensions () inline virtual
Register common layout extensions.
Definition at line 531 of file PersonaModule.h.
References OnRegisterLayoutExtensionsDelegate.
OnRegisterTabs()
virtual FOnRegisterTabs & FPersonaModule::OnRegisterTabs () inline virtual
Register common tabs.
Definition at line 534 of file PersonaModule.h.
References OnRegisterTabsDelegate.
OnStopRecording()
virtual FStopRecording & FPersonaModule::OnStopRecording () inline virtual
Delegate used to stop recording animation.
Definition at line 481 of file PersonaModule.h.
References StopRecordingDelegate.
RecordAssetOpened()
virtual void FPersonaModule::RecordAssetOpened (const FAssetData & InAssetData) const virtual
Record that an asset was opened (forward to relevant asset families)
RegisterBlendProfilePickerExtender()
PERSONA_API void FPersonaModule::RegisterBlendProfilePickerExtender (TSharedPtr< IBlendProfilePickerExtender > Extender)
RegisterNotifyHostAsset()
virtual void FPersonaModule::RegisterNotifyHostAsset (const FTopLevelAssetPath & InAssetClassPath, const FNotifyHostAssetParameters & InParameters) virtual
RegisterPersonaViewportTabFactories()
virtual void FPersonaModule::RegisterPersonaViewportTabFactories (FWorkflowAllowedTabSet & TabSet, const TSharedRef< class FWorkflowCentricApplication > & InHostingApp, const FPersonaViewportArgs & InArgs) const virtual
Register 4 Persona viewport tab factories.
RegisterToolMenuExtensions()
void FPersonaModule::RegisterToolMenuExtensions () private
ShutdownModule()
virtual void FPersonaModule::ShutdownModule () virtual
Called before the module is unloaded, right before the module object is destroyed.
Reimplemented from IModuleInterface.
StartupModule()
virtual void FPersonaModule::StartupModule () virtual
Called right after the module's DLL has been loaded and the module object has been created.
Reimplemented from IModuleInterface.
TestSkeletonCurveMetaDataForUse()
virtual void FPersonaModule::TestSkeletonCurveMetaDataForUse (const TSharedRef< IEditableSkeleton > & InEditableSkeleton) const virtual
Check all animations & skeletal meshes for curve metadata usage.
References InEditableSkeleton.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/6]
FPersonaModule::UE_DEPRECATED (4. 24, "Function renamed, please use CustomizeBlueprintEditorDetails") const &
UE_DEPRECATED() [2/6]
FPersonaModule::UE_DEPRECATED (5. 0, "Please use the overload that does not take a post-undo delegate") const &
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/6]
FPersonaModule::UE_DEPRECATED (5. 0, "Please use the overload that does not take a post-undo delegate") const &
References UE_DEPRECATED().
UE_DEPRECATED() [4/6]
FPersonaModule::UE_DEPRECATED (5. 0, "Please use the overload that takes a FBlendSpacePreviewArgs struct") const
Deprecated.
References UE_DEPRECATED().
UE_DEPRECATED() [5/6]
FPersonaModule::UE_DEPRECATED (5. 3, "Please use CreateCurvePicker that takes a const USkeleton*")
UE_DEPRECATED() [6/6]
FPersonaModule::UE_DEPRECATED (5. 3, "Please use TestSkeletonCurveMetaDataForUse") const & inline
Definition at line 450 of file PersonaModule.h.
References const, InEditableSkeleton, and TestSkeletonCurveMetaDataForUse().
UnregisterBlendProfilePickerExtender()
PERSONA_API void FPersonaModule::UnregisterBlendProfilePickerExtender (const FName ExtenderId)
UnregisterNotifyHostAsset()
virtual void FPersonaModule::UnregisterNotifyHostAsset (const FTopLevelAssetPath & InAssetClassPath) virtual
Field Documentation
const [1/3]
const TSharedPtr<class IEditableSkeleton> const TSharedRef<class IPersonaPreviewScene> FSimpleMulticastDelegate FOnObjectsSelected InOnObjectsSelected FPersonaModule::const
Definition at line 365 of file PersonaModule.h.
Referenced by CreateAdvancedPreviewSceneTabFactory(), CreateAnimAssetFindReplaceTabFactory(), CreateAnimationAssetBrowserTabFactory(), CreateAnimBlueprintAssetOverridesTabFactory(), CreateAnimBlueprintPreviewTabFactory(), CreateAnimMontageSectionsTabFactory(), CreateAssetDetailsTabFactory(), CreateAttributeViewerTabFactory(), CreateBlendSpaceEditWidget(), CreateBlendSpacePreviewWidget(), CreateCurveMetadataEditorTabFactory(), CreateCurveViewerTabFactory(), CreateCurveWidgetForAnimDocument(), CreateDefaultMorphTargetViewerWidget(), CreateEditorWidgetForAnimDocument(), CreateFindReplaceWidget(), CreateMorphTargetTabFactory(), CreateMorphTargetTabFactory(), CreatePersonaToolboxTabFactory(), CreatePoseWatchTabFactory(), CreateRetargetSourcesTabFactory(), CreateSkeletonSlotNamesTabFactory(), CustomizeMeshDetails(), and UE_DEPRECATED().
const [2/3]
const TSharedRef<class IEditableSkeleton> FSimpleMulticastDelegate FOnObjectSelected InOnObjectSelected FPersonaModule::const
Definition at line 404 of file PersonaModule.h.
const [3/3]
TAttribute<FVector> TAttribute<FVector> InFilteredBlendPosition FPersonaModule::const
Definition at line 417 of file PersonaModule.h.
CustomBlendProfiles
TArray<TSharedPtr<IBlendProfilePickerExtender> > FPersonaModule::CustomBlendProfiles private
Definition at line 584 of file PersonaModule.h.
CustomizeMeshDetailLayoutDelegates
TArray<FOnCustomizeMeshDetails> FPersonaModule::CustomizeMeshDetailLayoutDelegates private
Definition at line 624 of file PersonaModule.h.
Referenced by GetCustomizeMeshDetailsDelegates().
GetCurrentRecordingDelegate
FGetCurrentRecording FPersonaModule::GetCurrentRecordingDelegate private
Delegate used to get the currently recording animation.
Definition at line 636 of file PersonaModule.h.
Referenced by OnGetCurrentRecording().
GetCurrentRecordingTimeDelegate
FGetCurrentRecordingTime FPersonaModule::GetCurrentRecordingTimeDelegate private
Delegate used to get the currently recording animation time.
Definition at line 639 of file PersonaModule.h.
Referenced by OnGetCurrentRecordingTime().
InBlendPosition
TAttribute<FVector> FPersonaModule::InBlendPosition
Definition at line 417 of file PersonaModule.h.
InEditableSkeleton [1/2]
const TSharedPtr<class IEditableSkeleton>& FPersonaModule::InEditableSkeleton
Definition at line 365 of file PersonaModule.h.
Referenced by CreateAnimNotifiesTabFactory(), CreateCurveViewerTabFactory(), CreateRetargetSourcesTabFactory(), CreateSkeletonNotifyPicker(), CreateSkeletonSlotNamesTabFactory(), TestSkeletonCurveMetaDataForUse(), and UE_DEPRECATED().
InEditableSkeleton [2/2]
const TSharedRef<class IEditableSkeleton>& FPersonaModule::InEditableSkeleton
Definition at line 404 of file PersonaModule.h.
InIsCurveNameMarkedForExclusion
FOnCurvePicked FIsCurveNameMarkedForExclusion FPersonaModule::InIsCurveNameMarkedForExclusion = FIsCurveNameMarkedForExclusion())
Definition at line 543 of file PersonaModule.h.
Referenced by CreateCurvePicker(), and CreateMultiCurvePicker().
InOnCurvePicked
FOnCurvePicked FPersonaModule::InOnCurvePicked
Definition at line 543 of file PersonaModule.h.
Referenced by CreateCurvePicker().
InOnInvokeTab
FOnInvokeTab FPersonaModule::InOnInvokeTab { CustomizeBlueprintEditorDetails(InDetailsView, InOnInvokeTab)
Definition at line 466 of file PersonaModule.h.
Referenced by CustomizeBlueprintEditorDetails().
InOnPostUndo [1/2]
const TSharedPtr<class IEditableSkeleton> const TSharedRef<class IPersonaPreviewScene> FSimpleMulticastDelegate& FPersonaModule::InOnPostUndo
Definition at line 365 of file PersonaModule.h.
Referenced by CreateAnimBlueprintAssetOverridesTabFactory(), and CreateRetargetSourcesTabFactory().
InOnPostUndo [2/2]
const TSharedRef<class IEditableSkeleton> FSimpleMulticastDelegate& FPersonaModule::InOnPostUndo
Definition at line 404 of file PersonaModule.h.
InPreviewScene
const TSharedPtr<class IEditableSkeleton> const TSharedRef<class IPersonaPreviewScene>& FPersonaModule::InPreviewScene
Definition at line 365 of file PersonaModule.h.
Referenced by CreateAdvancedPreviewSceneTabFactory(), CreateAnimBlueprintPreviewTabFactory(), CreateAttributeViewerTabFactory(), CreateCurveMetadataEditorTabFactory(), CreateCurveViewerTabFactory(), CreateCurveWidgetForAnimDocument(), CreateDefaultMorphTargetViewerWidget(), and CreateMorphTargetTabFactory().
IsRecordingActiveDelegate
FIsRecordingActive FPersonaModule::IsRecordingActiveDelegate private
Delegate used to query whether recording is active.
Definition at line 627 of file PersonaModule.h.
Referenced by OnIsRecordingActive().
MenuExtensibilityManager
TSharedPtr<FExtensibilityManager> FPersonaModule::MenuExtensibilityManager private
Definition at line 622 of file PersonaModule.h.
Referenced by GetMenuExtensibilityManager().
NotifyHostAssetVersion
uint32 FPersonaModule::NotifyHostAssetVersion = 0 private
Version counter for NotifyHostParameters.
Definition at line 657 of file PersonaModule.h.
NotifyHostParameters
TMap<FTopLevelAssetPath, FNotifyHostAssetParameters> FPersonaModule::NotifyHostParameters private
Parameters for notify hosts.
Definition at line 654 of file PersonaModule.h.
OnPreviewSceneCreatedDelegate
FOnPreviewSceneCreated FPersonaModule::OnPreviewSceneCreatedDelegate private
Delegate broadcast when a preview scene is created.
Definition at line 645 of file PersonaModule.h.
Referenced by OnPreviewSceneCreated().
OnRegisterLayoutExtensionsDelegate
FOnRegisterLayoutExtensions FPersonaModule::OnRegisterLayoutExtensionsDelegate private
Delegate broadcast to register common layout extensions.
Definition at line 648 of file PersonaModule.h.
Referenced by OnRegisterLayoutExtensions().
OnRegisterTabsDelegate
FOnRegisterTabs FPersonaModule::OnRegisterTabsDelegate private
Delegate broadcast to register common tabs.
Definition at line 651 of file PersonaModule.h.
Referenced by OnRegisterTabs().
RecordDelegate
FRecord FPersonaModule::RecordDelegate private
Delegate used to start recording animation.
Definition at line 630 of file PersonaModule.h.
Referenced by OnRecord().
StopRecordingDelegate
FStopRecording FPersonaModule::StopRecordingDelegate private
Delegate used to stop recording animation.
Definition at line 633 of file PersonaModule.h.
Referenced by OnStopRecording().
TickRecordingDelegate
FTickRecording FPersonaModule::TickRecordingDelegate private
Delegate used to tick the skelmesh component recording.
Definition at line 642 of file PersonaModule.h.
ToolBarExtensibilityManager
TSharedPtr<FExtensibilityManager> FPersonaModule::ToolBarExtensibilityManager private
Definition at line 623 of file PersonaModule.h.
Referenced by GetToolBarExtensibilityManager().
The documentation for this class was generated from the following file:
PersonaModule.h