Unreal Engine 5.6 C++ API: SDataflowGraphEditor Class Reference
SDataflowGraphEditor Class Reference
The SDataflowGraphEditpr class is a specialization of SGraphEditor to display and manipulate the actions of a Dataflow asset.
#include "DataflowGraphEditor.h"
Public Member Functions
virtual ~SDataflowGraphEditor ()
void AddNewSubGraph () const
Add a new SubGraph for this dataflow graph.
void AddNewVariable () const
Add a new variable for this dataflow graph.
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
FGCObject interface.
void AlignBottom ()
void AlignCenter ()
void AlignLeft ()
void AlignMiddle ()
void AlignRight ()
void AlignTop ()
bool CanRenameNode () const
void Construct (const FArguments &InArgs, UObject *AssetOwner)
void CopySelectedNodes ()
void CreateComment ()
void CutSelectedNodes ()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnNodeDeletedMulticast, const FGraphPanelSelectionSet &) FOnNodeDeletedMulticast OnNodeDeletedMulticast
void DeleteNode ()
void DistributeHorizontally ()
void DistributeVertically ()
void DuplicateSelectedNodes ()
void EvaluateNode ()
void FreezeNodes ()
const TSharedPtr< FUICommandList > GetCommands () const
virtual TSharedPtr< UE::Dataflow::FContext > GetDataflowContext () const override
FDataflowSNodeInterface.
bool GetFilterActionMenyByAssetType () const
SGraphEditor * GetGraphEditor ()
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
bool IsAltDown () const
bool IsControlDown () const
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual void OnRenderToggleChanged () const override
void OnSelectedNodesChanged (const TSet< UObject * > &NewSelection)
void PasteSelectedNodes ()
void RenameNode ()
SLATE_ARGUMENT (FGraphEditorEvents, GraphEvents) SLATE_ARGUMENT(TSharedPtr< IStructureDetailsView >
SLATE_ARGUMENT (TSharedPtr< FUICommandList >, AdditionalCommands) SLATE_ATTRIBUTE(FGraphAppearanceInfo
Appearance SLATE_ARGUMENT_DEFAULT (UEdGraph *, GraphToEdit)
SLATE_BEGIN_ARGS (SDataflowGraphEditor)
DetailsView SLATE_ARGUMENT(FDataflowEditorCommands::FGraphEvaluationCallback, EvaluateGraph) SLATE_ARGUMENT(FDataflowEditorCommands SLATE_END_ARGS () DECLARE_MULTICAST_DELEGATE_OneParam(FOnSelectionChangedMulticast
void StraightenConnections ()
void ToggleEnabledState ()
void UnfreezeNodes ()
void ZoomToFitGraph ()
Public Member Functions inherited from SGraphEditor
virtual TSharedPtr< SNotificationItem > AddNotification (FNotificationInfo &Info)
virtual void AddNotification (FNotificationInfo &Info, bool bSuccess)
Show notification on graph.
virtual bool CanCollapseNodes () const
virtual bool CanExpandNodes () const
virtual void CaptureKeyboard ()
Capture keyboard.
virtual void ClearSelectionSet ()
Clear the selection.
DECLARE_DELEGATE (FActionMenuClosed)
DECLARE_DELEGATE (FOnDoubleClicked)
DECLARE_DELEGATE (FOnNodeSpawnedByKeymap)
DECLARE_DELEGATE_OneParam (FOnNodeSingleClicked, UObject *)
DECLARE_DELEGATE_OneParam (FOnSelectionChanged, const FGraphPanelSelectionSet &) DECLARE_DELEGATE_OneParam(FOnFocused
DECLARE_DELEGATE_RetVal_FiveParams (FActionMenuContent, FOnCreateActionMenuAtLocation, UEdGraph *, const FVector2f &, const TArray< UEdGraphPin * > &, bool, FActionMenuClosed)
DECLARE_DELEGATE_RetVal_FiveParams (FActionMenuContent, FOnCreateNodeOrPinMenu, UEdGraph *, const UEdGraphNode *, const UEdGraphPin *, FMenuBuilder *, bool)
DECLARE_DELEGATE_RetVal_TwoParams (FReply, FOnMouseButtonDown, const FGeometry &, const FPointerEvent &)
const FVector2D & DECLARE_DELEGATE_RetVal_TwoParams (FReply, FOnSpawnNodeByShortcutAtLocation, FInputChord, const FVector2f &)
const TSharedRef< SGraphEditor > const TArray< TWeakObjectPtr< class AActor > > class UEdGraph const FVector2D & DECLARE_DELEGATE_ThreeParams (FOnDropActors, const TArray< TWeakObjectPtr< class AActor > > &, class UEdGraph *, const FVector2f &)
const TArray< TWeakObjectPtr< class ULevelStreaming > > class UEdGraph const FVector2D & DECLARE_DELEGATE_ThreeParams (FOnDropStreamingLevels, const TArray< TWeakObjectPtr< class ULevelStreaming > > &, class UEdGraph *, const FVector2f &)
DECLARE_DELEGATE_TwoParams (FOnDisallowedPinConnection, const UEdGraphPin *, const UEdGraphPin *)
UNREALED_API void FocusCommentNodes (TArray< UEdGraphNode * > &CommentNodes, TArray< UEdGraphNode * > &RelatedNodes)
virtual bool GetBoundsForNode (const UEdGraphNode *InNode, class FSlateRect &Rect, float Padding) const
Get Bounds for the specified node, returns false on failure.
virtual bool GetBoundsForSelectedNodes (class FSlateRect &Rect, float Padding)
Get Bounds for selected nodes, false if nothing selected.
UEdGraph * GetCurrentGraph () const
virtual class UEdGraphNode * GetGraphNodeForMenu ()
virtual SGraphPanel * GetGraphPanel () const
Returns the graph panel used for this graph editor.
virtual class UEdGraphPin * GetGraphPinForMenu ()
virtual int32 GetNumberOfSelectedNodes () const
virtual UE::Slate::FDeprecateVector2DResult GetPasteLocation2f () const
virtual const FGraphPanelSelectionSet & GetSelectedNodes () const
virtual UEdGraphNode * GetSingleSelectedNode () const
Returns the currently selected node if there is a single node selected (if there are multiple nodes selected or none selected, it will return nullptr)
virtual TSharedPtr< SWidget > GetTitleBar () const
virtual void NotifyGraphChanged ()
Invoked when the Graph being edited changes in some way.
UNREALED_API void NotifyPostPropertyChange (const FPropertyChangedEvent &PropertyChangeEvent, const FString &PropertyName)
UNREALED_API void NotifyPrePropertyChange (const FString &PropertyName)
virtual void OnAlignBottom ()
virtual void OnAlignCenter ()
virtual void OnAlignLeft ()
virtual void OnAlignMiddle ()
virtual void OnAlignRight ()
virtual void OnAlignTop ()
virtual void OnCollapseNodes ()
virtual void OnDistributeNodesH ()
virtual void OnDistributeNodesV ()
virtual void OnExpandNodes ()
UNREALED_API void OnModuleReloaded ()
UNREALED_API void OnModuleUnloading ()
virtual void OnStackNodesH ()
virtual void OnStackNodesV ()
virtual void OnStraightenConnections ()
virtual void RefreshNode (UEdGraphNode &Node)
virtual TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Register an active timer on the graph editor.
UNREALED_API void ResetAllNodesUnrelatedStates ()
Common methods for MaterialEditor and BlueprintEditor's focusing related nodes feature.
virtual void SelectAllNodes ()
Select all nodes.
virtual void SetNodeFactory (const TSharedRef< class FGraphNodeFactory > &NewNodeFactory)
Sets the current node, pin and connection factory.
virtual void SetNodeSelection (UEdGraphNode *Node, bool bSelect)
Set the selection status of a node.
virtual void SetPinVisibility (EPinVisibility InVisibility)
IsEditable IsEmpty Appearance GraphToEdit PRAGMA_DISABLE_DEPRECATION_WARNINGS GraphToDiff PRAGMA_ENABLE_DEPRECATION_WARNINGS FocusedDiffResult PRAGMA_DISABLE_DEPRECATION_WARNINGS SLATE_ARGUMENT (FGraphEditorEvents, GraphEvents) PRAGMA_ENABLE_DEPRECATION_WARNINGS SLATE_ARGUMENT(bool
SLATE_ARGUMENT (TSharedPtr< FUICommandList >, AdditionalCommands) SLATE_ATTRIBUTE(bool
IsEditable IsEmpty SLATE_ARGUMENT (TSharedPtr< SWidget >, TitleBar) SLATE_ATTRIBUTE(FGraphAppearanceInfo
IsEditable IsEmpty Appearance GraphToEdit PRAGMA_DISABLE_DEPRECATION_WARNINGS GraphToDiff PRAGMA_ENABLE_DEPRECATION_WARNINGS SLATE_ARGUMENT (TSharedPtr< TArray< FDiffSingleResult > >, DiffResults) SLATE_ATTRIBUTE(int32
IsEditable IsEmpty Appearance GraphToEdit PRAGMA_DISABLE_DEPRECATION_WARNINGS GraphToDiff PRAGMA_ENABLE_DEPRECATION_WARNINGS FocusedDiffResult PRAGMA_DISABLE_DEPRECATION_WARNINGS AutoExpandActionMenu SLATE_ARGUMENT (TWeakPtr< FAssetEditorToolkit >, AssetEditorToolkit) SLATE_EVENT(FSimpleDelegate
IsEditable SLATE_ATTRIBUTE (bool, DisplayAsReadOnly) SLATE_ATTRIBUTE(bool
SLATE_BEGIN_ARGS (SGraphEditor)
IsEditable IsEmpty Appearance GraphToEdit PRAGMA_DISABLE_DEPRECATION_WARNINGS GraphToDiff PRAGMA_ENABLE_DEPRECATION_WARNINGS FocusedDiffResult PRAGMA_DISABLE_DEPRECATION_WARNINGS AutoExpandActionMenu OnNavigateHistoryBack ShowGraphStateOverlay SLATE_END_ARGS () UNREALED_API void Construct(const FArguments &InArgs)
Loads the GraphEditorModule and constructs a GraphEditor as a child of this widget.
IsEditable IsEmpty Appearance SLATE_EVENT (FEdGraphEvent, OnGraphModuleReloaded) SLATE_ARGUMENT(UEdGraph *
IsEditable IsEmpty Appearance GraphToEdit PRAGMA_DISABLE_DEPRECATION_WARNINGS GraphToDiff PRAGMA_ENABLE_DEPRECATION_WARNINGS FocusedDiffResult PRAGMA_DISABLE_DEPRECATION_WARNINGS AutoExpandActionMenu OnNavigateHistoryBack SLATE_EVENT (FSimpleDelegate, OnNavigateHistoryForward) SLATE_ATTRIBUTE(bool
Show overlay elements for the graph state such as the PIE and read-only borders and text.
virtual void StraightenConnections (UEdGraphPin *SourcePin, UEdGraphPin *PinToAlign=nullptr) const
IsEditable IsEmpty Appearance GraphToEdit PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.1, "GraphToDiff is no longer supported. Use DiffResults instead") SLATE_ARGUMENT(UEdGraph *
UE_DEPRECATED (5.6, "Please use the delegate accepting FVector2f.") DECLARE_DELEGATE_RetVal_FiveParams(FActionMenuContent
UE_DEPRECATED (5.6, "Please use the delegate accepting FVector2f.") DECLARE_DELEGATE_RetVal_TwoParams(FReply
const TSharedRef< SGraphEditor > & UE_DEPRECATED (5.6, "Please use the delegate accepting FVector2f.") DECLARE_DELEGATE_ThreeParams(FOnDropActor
UE_DEPRECATED (5.6, "Please use the delegate accepting FVector2f.") DECLARE_DELEGATE_ThreeParams(FOnDropStreamingLevel
UE_DEPRECATED (5.6, "Slate positions are represented in floats. Please use the function returning FVector2f.") virtual FVector2D GetPasteLocation() const UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
UE_DEPRECATED (5.6, "Slate positions are represented in floats. Please use the function returning FVector2f.") virtual void SetViewLocation(const FVector2D &Location
virtual void ZoomToFit (bool bOnlySelection)
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from FDataflowSEditorInterface
virtual bool NodesHaveFreezeWidget () const
virtual bool NodesHaveToggleWidget () const
Static Public Member Functions
static const TWeakPtr< SDataflowGraphEditor > & GetLastActionMenuGraphEditor ()
static const TWeakPtr< SDataflowGraphEditor > & GetSelectedGraphEditor ()
Return the currently selected editor.
Static Public Member Functions inherited from SGraphEditor
static UNREALED_API TSharedPtr< SGraphEditor > FindGraphEditorForGraph (const UEdGraph *Graph)
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Data Fields
DetailsView SLATE_ARGUMENT(FDataflowEditorCommands::FGraphEvaluationCallback, EvaluateGraph) SLATE_ARGUMENT(FDataflowEditorCommands const FGraphPanelSelectionSet &FOnSelectionChangedMulticast OnSelectionChangedMulticast
Data Fields inherited from SGraphEditor
float const FGuid & BookmarkId
UEdGraph const FVector2D const TArray< UEdGraphPin * > bool
UEdGraph const FVector2D const TArray< UEdGraphPin * > FActionMenuClosed
FInputChord
FOnCreateActionMenu
FOnSpawnNodeByShortcut
float ZoomAmount
Private Member Functions
bool CanAddOptionPin () const
Return whether all currently selected Dataflow nodes can execute the AddPin function.
bool CanRemoveOptionPin () const
Return whether all currently selected Dataflow nodes can execute the RemovePin function.
bool CanStartWatchingPin () const
bool CanStopWatchingPin () const
UDataflow * GetDataflowAsset () const
get the dataflow asset from the edGraph being edited
FText GetGraphEditorOverlayText () const
Text for overlay message in graph editor panel.
bool GetPinVisibility (SGraphEditor::EPinVisibility InVisibility) const
void InitEvaluationProgressBar ()
Create a widget to display teh progress of the evaluation of the graph.
void InitGraphEditorMessageBar ()
Create a widget to display an overlaid message in the graph editor panel.
ECheckBoxState IsActionMenuFilterByAssetTypeChecked () const
void OnActionMenuFilterByAssetTypeChanged (ECheckBoxState NewState, const TWeakPtr< SGraphEditorActionMenu > WeakActionMenu)
void OnAddOptionPin ()
Add an additional option pin to all selected Dataflow nodes for those that overrides the AddPin function.
FActionMenuContent OnCreateActionMenu (UEdGraph *Graph, const FVector2f &Position, const TArray< UEdGraphPin * > &DraggedPins, bool bAutoExpandActionMenu, SGraphEditor::FActionMenuClosed OnClosed)
void OnRemoveOptionPin ()
Remove an option pin from all selected Dataflow nodes for those that overrides the RemovePin function.
void OnStartWatchingPin ()
void OnStopWatchingPin ()
Private Attributes
TWeakObjectPtr< UObject > AssetOwner
The asset that ownes this dataflow graph.
bool bFilterActionMenyByAssetType = true
FDelegateHandle CVarChangedDelegateHandle
UDataflowEditor * DataflowEditor = nullptr
Editor for the content.
TSharedPtr< IStructureDetailsView > DetailsView
The details view that responds to this widget.
TWeakObjectPtr< UEdGraph > EdGraphWeakPtr
The dataflow asset associated with this graph.
FDataflowEditorCommands::FGraphEvaluationCallback EvaluateGraphCallback
TSharedPtr< SWidget > EvaluationProgressBar
TSharedPtr< FUICommandList > GraphEditorCommands
Command list associated with this graph editor.
bool LeftAltKeyDown = false
bool LeftControlKeyDown = false
TSharedPtr< SWidget > MessageBar
FText MessageBarText
FDataflowEditorCommands::FOnDragDropEventCallback OnDragDropEventCallback
bool RightAltKeyDown = false
bool RightControlKeyDown = false
bool VKeyDown = false
Static Private Attributes
static TWeakPtr< SDataflowGraphEditor > LastActionMenuGraphEditor
The last graph editor used when a action context menu was brough up in the graph.
static TSharedPtr< FDataflowGraphEditorNodeFactory > NodeFactory
Factory to create the associated SGraphNode classes for Dataprep graph's UEdGraph classes.
static TWeakPtr< SDataflowGraphEditor > SelectedGraphEditor
The current graph editor when the selection callback is invoked.
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Member Functions inherited from SGraphEditor
virtual void OnGraphChanged (const struct FEdGraphEditAction &InAction)
Invoked when the underlying Graph is being changed.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from FDataflowSEditorInterface
FDataflowSEditorInterface ()=default
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SGraphEditor
TWeakPtr< FAssetEditorToolkit > AssetEditorToolkit
UEdGraph * EdGraphObj
The Graph we are currently editing.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
The SDataflowGraphEditpr class is a specialization of SGraphEditor to display and manipulate the actions of a Dataflow asset.
see(SDataprepGraphEditor for reference)
Definition at line 39 of file DataflowGraphEditor.h.
Constructor & Destructor Documentation
~SDataflowGraphEditor()
virtual SDataflowGraphEditor::~SDataflowGraphEditor () virtual
Member Function Documentation
AddNewSubGraph()
void SDataflowGraphEditor::AddNewSubGraph () const
Add a new SubGraph for this dataflow graph.
References AddNewSubGraph().
Referenced by AddNewSubGraph().
AddNewVariable()
void SDataflowGraphEditor::AddNewVariable () const
Add a new variable for this dataflow graph.
References AddNewVariable().
Referenced by AddNewVariable().
AddReferencedObjects()
virtual void SDataflowGraphEditor::AddReferencedObjects (FReferenceCollector & Collector) override virtual
FGCObject interface.
Implements FGCObject.
AlignBottom()
void SDataflowGraphEditor::AlignBottom ()
References AlignBottom().
Referenced by AlignBottom().
AlignCenter()
void SDataflowGraphEditor::AlignCenter ()
References AlignCenter().
Referenced by AlignCenter().
AlignLeft()
void SDataflowGraphEditor::AlignLeft ()
References AlignLeft().
Referenced by AlignLeft().
AlignMiddle()
void SDataflowGraphEditor::AlignMiddle ()
References AlignMiddle().
Referenced by AlignMiddle().
AlignRight()
void SDataflowGraphEditor::AlignRight ()
References AlignRight().
Referenced by AlignRight().
AlignTop()
void SDataflowGraphEditor::AlignTop ()
References AlignTop().
Referenced by AlignTop().
CanAddOptionPin()
bool SDataflowGraphEditor::CanAddOptionPin () const private
Return whether all currently selected Dataflow nodes can execute the AddPin function.
CanRemoveOptionPin()
bool SDataflowGraphEditor::CanRemoveOptionPin () const private
Return whether all currently selected Dataflow nodes can execute the RemovePin function.
CanRenameNode()
bool SDataflowGraphEditor::CanRenameNode () const
References CanRenameNode().
Referenced by CanRenameNode().
CanStartWatchingPin()
bool SDataflowGraphEditor::CanStartWatchingPin () const private
CanStopWatchingPin()
bool SDataflowGraphEditor::CanStopWatchingPin () const private
Construct()
void SDataflowGraphEditor::Construct (const FArguments & InArgs, UObject * AssetOwner)
References AssetOwner, and Construct().
Referenced by Construct().
CopySelectedNodes()
void SDataflowGraphEditor::CopySelectedNodes ()
References CopySelectedNodes().
Referenced by CopySelectedNodes().
CreateComment()
void SDataflowGraphEditor::CreateComment ()
References CreateComment().
Referenced by CreateComment().
CutSelectedNodes()
void SDataflowGraphEditor::CutSelectedNodes ()
References CutSelectedNodes().
Referenced by CutSelectedNodes().
DECLARE_MULTICAST_DELEGATE_OneParam()
SDataflowGraphEditor::DECLARE_MULTICAST_DELEGATE_OneParam (FOnNodeDeletedMulticast , const FGraphPanelSelectionSet &)
References DECLARE_MULTICAST_DELEGATE_OneParam().
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), and SLATE_END_ARGS().
DeleteNode()
void SDataflowGraphEditor::DeleteNode ()
References DeleteNode().
Referenced by DeleteNode().
DistributeHorizontally()
void SDataflowGraphEditor::DistributeHorizontally ()
References DistributeHorizontally().
Referenced by DistributeHorizontally().
DistributeVertically()
void SDataflowGraphEditor::DistributeVertically ()
References DistributeVertically().
Referenced by DistributeVertically().
DuplicateSelectedNodes()
void SDataflowGraphEditor::DuplicateSelectedNodes ()
References DuplicateSelectedNodes().
Referenced by DuplicateSelectedNodes().
EvaluateNode()
void SDataflowGraphEditor::EvaluateNode ()
References EvaluateNode().
Referenced by EvaluateNode().
FreezeNodes()
void SDataflowGraphEditor::FreezeNodes ()
References FreezeNodes().
Referenced by FreezeNodes().
GetCommands()
const TSharedPtr< FUICommandList > SDataflowGraphEditor::GetCommands () const inline
Definition at line 165 of file DataflowGraphEditor.h.
References GraphEditorCommands.
GetDataflowAsset()
UDataflow * SDataflowGraphEditor::GetDataflowAsset () const private
get the dataflow asset from the edGraph being edited
GetDataflowContext()
virtual TSharedPtr< UE::Dataflow::FContext > SDataflowGraphEditor::GetDataflowContext () const override virtual
FDataflowSNodeInterface.
Implements FDataflowSEditorInterface.
GetFilterActionMenyByAssetType()
bool SDataflowGraphEditor::GetFilterActionMenyByAssetType () const inline
Definition at line 172 of file DataflowGraphEditor.h.
References bFilterActionMenyByAssetType.
GetGraphEditor()
SGraphEditor * SDataflowGraphEditor::GetGraphEditor () inline
Definition at line 155 of file DataflowGraphEditor.h.
References GetGraphEditor().
Referenced by GetGraphEditor().
GetGraphEditorOverlayText()
FText SDataflowGraphEditor::GetGraphEditorOverlayText () const private
Text for overlay message in graph editor panel.
GetLastActionMenuGraphEditor()
const TWeakPtr< SDataflowGraphEditor > & SDataflowGraphEditor::GetLastActionMenuGraphEditor () inline static
Definition at line 170 of file DataflowGraphEditor.h.
References LastActionMenuGraphEditor.
GetPinVisibility()
bool SDataflowGraphEditor::GetPinVisibility (SGraphEditor::EPinVisibility InVisibility) const private
GetReferencerName()
virtual FString SDataflowGraphEditor::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 159 of file DataflowGraphEditor.h.
References TEXT.
GetSelectedGraphEditor()
const TWeakPtr< SDataflowGraphEditor > & SDataflowGraphEditor::GetSelectedGraphEditor () inline static
Return the currently selected editor.
Only valid for the duration of the OnSelectedNodesChanged callback where the property editor is updated.
Definition at line 168 of file DataflowGraphEditor.h.
References SelectedGraphEditor.
InitEvaluationProgressBar()
void SDataflowGraphEditor::InitEvaluationProgressBar () private
Create a widget to display teh progress of the evaluation of the graph.
InitGraphEditorMessageBar()
void SDataflowGraphEditor::InitGraphEditorMessageBar () private
Create a widget to display an overlaid message in the graph editor panel.
IsActionMenuFilterByAssetTypeChecked()
ECheckBoxState SDataflowGraphEditor::IsActionMenuFilterByAssetTypeChecked () const private
IsAltDown()
bool SDataflowGraphEditor::IsAltDown () const
References IsAltDown().
Referenced by IsAltDown().
IsControlDown()
bool SDataflowGraphEditor::IsControlDown () const
References IsControlDown().
Referenced by IsControlDown().
OnActionMenuFilterByAssetTypeChanged()
void SDataflowGraphEditor::OnActionMenuFilterByAssetTypeChanged (ECheckBoxState NewState, const TWeakPtr< SGraphEditorActionMenu > WeakActionMenu) private
OnAddOptionPin()
void SDataflowGraphEditor::OnAddOptionPin () private
Add an additional option pin to all selected Dataflow nodes for those that overrides the AddPin function.
OnCreateActionMenu()
FActionMenuContent SDataflowGraphEditor::OnCreateActionMenu (UEdGraph * Graph, const FVector2f & Position, const TArray< UEdGraphPin * > & DraggedPins, bool bAutoExpandActionMenu, SGraphEditor::FActionMenuClosed OnClosed) private
References SGraphEditor::FActionMenuClosed, and Position.
OnDragOver()
virtual FReply SDataflowGraphEditor::OnDragOver (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the the mouse is being dragged over a widget.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
References OnDragOver().
Referenced by OnDragOver().
OnDrop()
virtual FReply SDataflowGraphEditor::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
References OnDrop().
Referenced by OnDrop().
OnKeyDown()
virtual FReply SDataflowGraphEditor::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
OnKeyUp()
virtual FReply SDataflowGraphEditor::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyUp().
Referenced by OnKeyUp().
OnRemoveOptionPin()
void SDataflowGraphEditor::OnRemoveOptionPin () private
Remove an option pin from all selected Dataflow nodes for those that overrides the RemovePin function.
OnRenderToggleChanged()
virtual void SDataflowGraphEditor::OnRenderToggleChanged () const override virtual
Reimplemented from FDataflowSEditorInterface.
OnSelectedNodesChanged()
void SDataflowGraphEditor::OnSelectedNodesChanged (const TSet< UObject * > & NewSelection)
References OnSelectedNodesChanged().
Referenced by OnSelectedNodesChanged().
OnStartWatchingPin()
void SDataflowGraphEditor::OnStartWatchingPin () private
OnStopWatchingPin()
void SDataflowGraphEditor::OnStopWatchingPin () private
PasteSelectedNodes()
void SDataflowGraphEditor::PasteSelectedNodes ()
References PasteSelectedNodes().
Referenced by PasteSelectedNodes().
RenameNode()
void SDataflowGraphEditor::RenameNode ()
References RenameNode().
Referenced by RenameNode().
SLATE_ARGUMENT() [1/2]
SDataflowGraphEditor::SLATE_ARGUMENT (FGraphEditorEvents , GraphEvents)
References DataflowEditor, DetailsView, SLATE_ARGUMENT(), and SLATE_ARGUMENT_DEFAULT().
SLATE_ARGUMENT() [2/2]
SDataflowGraphEditor::SLATE_ARGUMENT (TSharedPtr< FUICommandList > , AdditionalCommands)
Referenced by SLATE_ARGUMENT().
SLATE_ARGUMENT_DEFAULT()
Appearance SDataflowGraphEditor::SLATE_ARGUMENT_DEFAULT (UEdGraph * , GraphToEdit)
References SLATE_ARGUMENT_DEFAULT().
Referenced by SLATE_ARGUMENT(), and SLATE_ARGUMENT_DEFAULT().
SLATE_BEGIN_ARGS()
SDataflowGraphEditor::SLATE_BEGIN_ARGS (SDataflowGraphEditor) inline
Definition at line 43 of file DataflowGraphEditor.h.
SLATE_END_ARGS()
DetailsView SLATE_ARGUMENT(FDataflowEditorCommands::FGraphEvaluationCallback, EvaluateGraph) SLATE_ARGUMENT(FDataflowEditorCommands SDataflowGraphEditor::SLATE_END_ARGS ()
References DECLARE_MULTICAST_DELEGATE_OneParam(), and SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
StraightenConnections()
void SDataflowGraphEditor::StraightenConnections () virtual
Reimplemented from SGraphEditor.
References StraightenConnections().
Referenced by StraightenConnections().
ToggleEnabledState()
void SDataflowGraphEditor::ToggleEnabledState ()
References ToggleEnabledState().
Referenced by ToggleEnabledState().
UnfreezeNodes()
void SDataflowGraphEditor::UnfreezeNodes ()
References UnfreezeNodes().
Referenced by UnfreezeNodes().
ZoomToFitGraph()
void SDataflowGraphEditor::ZoomToFitGraph ()
References ZoomToFitGraph().
Referenced by ZoomToFitGraph().
Field Documentation
AssetOwner
TWeakObjectPtr<UObject> SDataflowGraphEditor::AssetOwner private
The asset that ownes this dataflow graph.
Definition at line 212 of file DataflowGraphEditor.h.
Referenced by Construct().
bFilterActionMenyByAssetType
bool SDataflowGraphEditor::bFilterActionMenyByAssetType = true private
Definition at line 241 of file DataflowGraphEditor.h.
Referenced by GetFilterActionMenyByAssetType().
CVarChangedDelegateHandle
FDelegateHandle SDataflowGraphEditor::CVarChangedDelegateHandle private
Definition at line 243 of file DataflowGraphEditor.h.
DataflowEditor
UDataflowEditor* SDataflowGraphEditor::DataflowEditor = nullptr private
Editor for the content.
Definition at line 233 of file DataflowGraphEditor.h.
Referenced by SLATE_ARGUMENT().
DetailsView
TSharedPtr<IStructureDetailsView> SDataflowGraphEditor::DetailsView private
The details view that responds to this widget.
Definition at line 221 of file DataflowGraphEditor.h.
Referenced by SLATE_ARGUMENT().
EdGraphWeakPtr
TWeakObjectPtr<UEdGraph> SDataflowGraphEditor::EdGraphWeakPtr private
The dataflow asset associated with this graph.
Definition at line 215 of file DataflowGraphEditor.h.
EvaluateGraphCallback
FDataflowEditorCommands::FGraphEvaluationCallback SDataflowGraphEditor::EvaluateGraphCallback private
Definition at line 205 of file DataflowGraphEditor.h.
EvaluationProgressBar
TSharedPtr<SWidget> SDataflowGraphEditor::EvaluationProgressBar private
Definition at line 245 of file DataflowGraphEditor.h.
GraphEditorCommands
TSharedPtr<FUICommandList> SDataflowGraphEditor::GraphEditorCommands private
Command list associated with this graph editor.
Definition at line 218 of file DataflowGraphEditor.h.
Referenced by GetCommands().
LastActionMenuGraphEditor
TWeakPtr<SDataflowGraphEditor> SDataflowGraphEditor::LastActionMenuGraphEditor static private
The last graph editor used when a action context menu was brough up in the graph.
Definition at line 230 of file DataflowGraphEditor.h.
Referenced by GetLastActionMenuGraphEditor().
LeftAltKeyDown
bool SDataflowGraphEditor::LeftAltKeyDown = false private
Definition at line 238 of file DataflowGraphEditor.h.
LeftControlKeyDown
bool SDataflowGraphEditor::LeftControlKeyDown = false private
Definition at line 236 of file DataflowGraphEditor.h.
MessageBar
TSharedPtr<SWidget> SDataflowGraphEditor::MessageBar private
Definition at line 244 of file DataflowGraphEditor.h.
MessageBarText
FText SDataflowGraphEditor::MessageBarText private
Definition at line 246 of file DataflowGraphEditor.h.
NodeFactory
TSharedPtr<FDataflowGraphEditorNodeFactory> SDataflowGraphEditor::NodeFactory static private
Factory to create the associated SGraphNode classes for Dataprep graph's UEdGraph classes.
Definition at line 224 of file DataflowGraphEditor.h.
OnDragDropEventCallback
FDataflowEditorCommands::FOnDragDropEventCallback SDataflowGraphEditor::OnDragDropEventCallback private
Definition at line 204 of file DataflowGraphEditor.h.
OnSelectionChangedMulticast
DetailsView SLATE_ARGUMENT(FDataflowEditorCommands::FGraphEvaluationCallback, EvaluateGraph) SLATE_ARGUMENT(FDataflowEditorCommands const FGraphPanelSelectionSet& FOnSelectionChangedMulticast SDataflowGraphEditor::OnSelectionChangedMulticast
Definition at line 61 of file DataflowGraphEditor.h.
RightAltKeyDown
bool SDataflowGraphEditor::RightAltKeyDown = false private
Definition at line 239 of file DataflowGraphEditor.h.
RightControlKeyDown
bool SDataflowGraphEditor::RightControlKeyDown = false private
Definition at line 237 of file DataflowGraphEditor.h.
SelectedGraphEditor
TWeakPtr<SDataflowGraphEditor> SDataflowGraphEditor::SelectedGraphEditor static private
The current graph editor when the selection callback is invoked.
Definition at line 227 of file DataflowGraphEditor.h.
Referenced by GetSelectedGraphEditor().
VKeyDown
bool SDataflowGraphEditor::VKeyDown = false private
Definition at line 235 of file DataflowGraphEditor.h.
The documentation for this class was generated from the following file:
DataflowGraphEditor.h