Unreal Engine 5.6 C++ API: IAndroidPlatformFile Class Reference
IAndroidPlatformFile Class Reference abstract
Android File I/O implementation with additional utilities to deal with Java side access.
#include "AndroidPlatformFile.h"
Public Member Functions
virtual FString ConvertToAbsolutePathForExternalAppForRead (const TCHAR *Filename) override
Converts passed in filename to use an absolute path (for reading).
virtual FString ConvertToAbsolutePathForExternalAppForWrite (const TCHAR *Filename) override
Converts passed in filename to use an absolute path (for writing)
virtual bool DirectoryExists (const TCHAR *Directory)=0
Return true if the directory exists.
virtual bool DirectoryExists (const TCHAR *Directory, bool bAllowAssets)=0
virtual bool FileExists (const TCHAR *Filename)=0
Return true if the file exists.
virtual bool FileExists (const TCHAR *Filename, bool bAllowAssets)=0
virtual FString FileRootPath (const TCHAR *Filename)=0
virtual int64 FileSize (const TCHAR *Filename)=0
Return the size of the file, or -1 if it doesn't exist.
virtual int64 FileSize (const TCHAR *Filename, bool bAllowAssets)=0
virtual int64 FileStartOffset (const TCHAR *Filename)=0
virtual FFileStatData GetStatData (const TCHAR *FilenameOrDirectory)=0
Return the stat data for the given file or directory.
virtual FFileStatData GetStatData (const TCHAR *FilenameOrDirectory, bool bAllowAssets)=0
virtual bool IsAsset (const TCHAR *Filename)=0
virtual bool IterateDirectory (const TCHAR *Directory, FDirectoryVisitor &Visitor)=0
Call the Visit function of the visitor once for each file or directory in a single directory.
virtual bool IterateDirectory (const TCHAR *Directory, FDirectoryVisitor &Visitor, bool bAllowAssets)=0
virtual bool IterateDirectory (const TCHAR *Directory, FDirectoryVisitorFunc Visitor)
Call the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryStat (const TCHAR *Directory, FDirectoryStatVisitor &Visitor)=0
Call the Visit function of the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryStat (const TCHAR *Directory, FDirectoryStatVisitor &Visitor, bool bAllowAssets)=0
virtual bool IterateDirectoryStat (const TCHAR *Directory, FDirectoryStatVisitorFunc Visitor)
Call the visitor once for each file or directory in a single directory.
Public Member Functions inherited from IPhysicalPlatformFile
virtual IPlatformFile * GetLowerLevel () override
Gets the platform file wrapped by this file.
virtual const TCHAR * GetName () const override
Gets this platform file type name.
virtual bool Initialize (IPlatformFile *Inner, const TCHAR *CmdLine) override
Initializes platform file.
virtual void SetLowerLevel (IPlatformFile *NewLowerLevel) override
Sets the platform file wrapped by this file.
virtual bool ShouldBeUsed (IPlatformFile *Inner, const TCHAR *CmdLine) const override
Checks if this platform file should be used even though it was not asked to be.
Public Member Functions inherited from IPlatformFile
IPlatformFile ()
Constructor/Destructor.
virtual ~IPlatformFile ()
virtual void AddLocalDirectories (TArray< FString > &LocalDirectories)
Identifies any platform specific paths that are guaranteed to be local (i.e.
virtual void BypassSecurity (bool bInBypass)
virtual bool CopyDirectoryTree (const TCHAR *DestinationDirectory, const TCHAR *Source, bool bOverwriteAllExisting)
Copy a file or a hierarchy of files (directory).
virtual bool CopyFile (const TCHAR *To, const TCHAR *From, EPlatformFileRead ReadFlags=EPlatformFileRead::None, EPlatformFileWrite WriteFlags=EPlatformFileWrite::None)
Copy a file.
virtual bool CreateDirectory (const TCHAR *Directory)=0
Create a directory and return true if the directory was created or already existed.
virtual bool CreateDirectoryTree (const TCHAR *Directory)
Create a directory, including any parent directories and return true if the directory was created or already existed.
virtual bool DeleteDirectory (const TCHAR *Directory)=0
Delete a directory and return true if the directory was deleted or otherwise does not exist.
virtual bool DeleteDirectoryRecursively (const TCHAR *Directory)
Delete all files and subdirectories in a directory, then delete the directory itself.
virtual bool DeleteFile (const TCHAR *Filename)=0
Delete a file and return true if the file exists.
virtual bool DeleteFiles (const TArrayView< const TCHAR * > &Filenames)
Delete an array of files and return true if ALL deletes are succeeded.
virtual bool DoesCreatePublicFiles ()
Checks to see if this file system creates publicly accessible files.
virtual FFileJournalData FileJournalGetFileData (const TCHAR *FilenameOrDirectory, FString *OutError=nullptr)
Return the data for the given path as with GetStatData, but report a FFileJournalData instead, which notably includes the FFileJournalFileHandle for the file/directory.
virtual EFileJournalResult FileJournalGetLatestEntry (const TCHAR *VolumeName, FFileJournalId &OutJournalId, FFileJournalEntryHandle &OutEntryHandle, FString *OutError=nullptr)
Report the current end of the journal for the given volume, to be used as the StartingJournalEntry in FileJournalGetModifiedDirectories.
virtual uint64 FileJournalGetMaximumSize (const TCHAR *VolumeOrPath=nullptr, ELogVerbosity::Type *OutErrorLevel=nullptr, FString *OutError=nullptr) const
Return the maximum size of the FileJournal for the specified VolumeName, if available, zero otherwise.
virtual FString FileJournalGetVolumeName (FStringView InPath)
Return the VolumeSpecifier present in the given path.
virtual bool FileJournalIsAvailable (const TCHAR *VolumeOrPath=nullptr, ELogVerbosity::Type *OutErrorLevel=nullptr, FString *OutError=nullptr)
Return whether FileJournal functionality is available on the current platform if VolumeName is nullptr or for the given Volume if VolumeName is non-null.
virtual bool FileJournalIterateDirectory (const TCHAR *Directory, FDirectoryJournalVisitorFunc Visitor, FString *OutError=nullptr)
Iterate the given directory as with IterateDirectoryStat, but report a FFileJournalData for each file and directory, which notably includes the FFileJournalFileHandle for the file/directory.
virtual EFileJournalResult FileJournalReadModified (const TCHAR *VolumeName, const FFileJournalId &JournalIdOfStartingEntry, const FFileJournalEntryHandle &StartingJournalEntry, TMap< FFileJournalFileHandle, FString > &KnownDirectories, TSet< FString > &OutModifiedDirectories, FFileJournalEntryHandle &OutNextJournalEntry, FString *OutError=nullptr)
Query the FileJournal to find a list of all directories on the given volume with files that have been added, deleted, or modified in the specified time range.
virtual void FindFiles (TArray< FString > &FoundFiles, const TCHAR *Directory, const TCHAR *FileExtension)
Finds all the files within the given directory, with optional file extension filter.
virtual void FindFilesRecursively (TArray< FString > &FoundFiles, const TCHAR *Directory, const TCHAR *FileExtension)
Finds all the files within the directory tree, with optional file extension filter.
virtual FDateTime GetAccessTimeStamp (const TCHAR *Filename)=0
Return the last access time of a file.
virtual int64 GetAllowedBytesToWriteThrottledStorage (const TCHAR *DestinationPath=nullptr)
Returns the number of bytes that are currently allowed to be written to throttled write storage (if the platform has such restrictions)
virtual FString GetFilenameOnDisk (const TCHAR *Filename)=0
For case insensitive filesystems, returns the full path of the file with the same case as in the filesystem.
virtual FDateTime GetTimeStamp (const TCHAR *Filename)=0
Return the modification time of a file.
virtual FDateTime GetTimeStampLocal (const TCHAR *Filename)
Return the modification time of a file in the local time of the calling code (GetTimeStamp returns UTC).
virtual void GetTimeStampPair (const TCHAR *PathA, const TCHAR *PathB, FDateTime &OutTimeStampA, FDateTime &OutTimeStampB)
virtual bool HasMarkOfTheWeb (FStringView Filename, FString *OutSourceURL=nullptr)
Determine if the file has been downloaded from a web browser, based on platform-specific metadata.
virtual void InitializeAfterProjectFilePath ()
Performs initialization of the platform file after the project path has been set.
virtual void InitializeAfterSetActive ()
Performs initialization of the platform file after it has become the active (FPlatformFileManager.GetPlatformFile() will return this.
virtual void InitializeNewAsyncIO ()
Performs initialization of the platform file after the new async IO has been enabled.
virtual bool IsReadOnly (const TCHAR *Filename)=0
Return true if the file is read only.
virtual bool IsSandboxEnabled () const
Returns whether the sandbox is enabled or not.
virtual ESymlinkResult IsSymlink (const TCHAR *Filename)
Return true if the file is a symbolic link.
virtual bool IterateDirectoryRecursively (const TCHAR *Directory, FDirectoryVisitor &Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryRecursively (const TCHAR *Directory, FDirectoryVisitorFunc Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryStatRecursively (const TCHAR *Directory, FDirectoryStatVisitor &Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryStatRecursively (const TCHAR *Directory, FDirectoryStatVisitorFunc Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual void MakeUniquePakFilesForTheseFiles (const TArray< TArray< FString > > &InFiles)
Build an in memory unique pak file from a subset of files in this pak file.
virtual bool MoveFile (const TCHAR *To, const TCHAR *From)=0
Attempt to move a file.
virtual IAsyncReadFileHandle * OpenAsyncRead (const TCHAR *Filename, bool bAllowWrite=false)
Open a file for async reading.
virtual FFileOpenAsyncResult OpenAsyncRead (const TCHAR *Filename, EOpenReadFlags Flags)
Open a file for async reading.
virtual FOpenMappedResult OpenMappedEx (const TCHAR *Filename, EOpenReadFlags OpenOptions=EOpenReadFlags::None, int64 MaximumSize=0)
Open a file for async reading.
virtual IFileHandle * OpenRead (const TCHAR *Filename, bool bAllowWrite=false)=0
Attempt to open a file for reading.
virtual FFileOpenResult OpenRead (const TCHAR *Filename, EOpenReadFlags Flags)
Open a file handle for reading.
virtual IFileHandle * OpenReadNoBuffering (const TCHAR *Filename, bool bAllowWrite=false)
virtual IFileHandle * OpenWrite (const TCHAR *Filename, bool bAppend=false, bool bAllowRead=false)=0
Attempt to open a file for writing.
virtual bool SendMessageToServer (const TCHAR *Message, IFileServerMessageHandler *Handler)
Sends a message to the file server, and will block until it's complete.
virtual void SetAsyncMinimumPriority (EAsyncIOPriorityAndFlags MinPriority)
Controls if the pak precacher should process precache requests.
virtual void SetCreatePublicFiles (bool bCreatePublicFiles)
Sets file system to create publicly accessible files or not.
virtual bool SetMarkOfTheWeb (FStringView Filename, bool bNewStatus, const FString *InSourceURL=nullptr)
Attempt to change the platform-specific metadata that indicates if the file has been downloaded from a web browser.
virtual bool SetReadOnly (const TCHAR *Filename, bool bNewReadOnlyValue)=0
Attempt to change the read only status of a file.
virtual void SetSandboxEnabled (bool bInEnabled)
Set whether the sandbox is enabled or not.
virtual void SetTimeStamp (const TCHAR *Filename, FDateTime DateTime)=0
Sets the modification time of a file.
virtual void Tick ()
Platform file can override this to get a regular tick from the engine.
UE_DEPRECATED (5.6, "Please use OpenMappedEx instead") 1 virtual IMappedFileHandle *OpenMapped(const TCHAR *Filename)
Open a file for async reading.
Static Public Member Functions
static IAndroidPlatformFile & GetPlatformPhysical ()
Static Public Member Functions inherited from IPlatformFile
static const TCHAR * GetPhysicalTypeName ()
Returns the name of the physical platform file type.
static IPlatformFile & GetPlatformPhysical ()
Physical file system of the platform, never wrapped.
Additional Inherited Members
Public Types inherited from IPlatformFile
enum class EOpenReadFlags : uint8 { None = 0 , AllowWrite = 1 << 0 , AllowDelete = 1 << 1 }
Flags to be used when opening a file for reading via IPlatformFile::OpenRead.
typedef TFunctionRef< bool(const TCHAR *, const FFileJournalData &)> FDirectoryJournalVisitorFunc
File and directory visitor function that takes FileJournal data.
typedef TFunctionRef< bool(const TCHAR *, const FFileStatData &)> FDirectoryStatVisitorFunc
File and directory visitor function that takes all the stat data.
typedef TFunctionRef< bool(const TCHAR *, bool)> FDirectoryVisitorFunc
File and directory visitor function that takes only the name.
Detailed Description
Android File I/O implementation with additional utilities to deal with Java side access.
Definition at line 18 of file AndroidPlatformFile.h.
Member Function Documentation
ConvertToAbsolutePathForExternalAppForRead()
virtual FString IAndroidPlatformFile::ConvertToAbsolutePathForExternalAppForRead (const TCHAR * Filename) override virtual
Converts passed in filename to use an absolute path (for reading).
Parameters
Filename filename to convert to use an absolute path, safe to pass in already using absolute path
Returns
filename using absolute path
Reimplemented from IPlatformFile.
References Filename.
ConvertToAbsolutePathForExternalAppForWrite()
virtual FString IAndroidPlatformFile::ConvertToAbsolutePathForExternalAppForWrite (const TCHAR * Filename) override virtual
Converts passed in filename to use an absolute path (for writing)
Parameters
Filename filename to convert to use an absolute path, safe to pass in already using absolute path
Returns
filename using absolute path
Reimplemented from IPlatformFile.
References Filename.
DirectoryExists() [1/2]
virtual bool IPlatformFile::DirectoryExists (const TCHAR * Directory) virtual
Return true if the directory exists.
Implements IPlatformFile.
DirectoryExists() [2/2]
virtual bool IAndroidPlatformFile::DirectoryExists (const TCHAR * Directory, bool bAllowAssets) pure virtual
FileExists() [1/2]
virtual bool IPlatformFile::FileExists (const TCHAR * Filename) virtual
Return true if the file exists.
Implements IPlatformFile.
FileExists() [2/2]
virtual bool IAndroidPlatformFile::FileExists (const TCHAR * Filename, bool bAllowAssets) pure virtual
References Filename.
FileRootPath()
virtual FString IAndroidPlatformFile::FileRootPath (const TCHAR * Filename) pure virtual
References Filename.
FileSize() [1/2]
virtual int64 IPlatformFile::FileSize (const TCHAR * Filename) virtual
Return the size of the file, or -1 if it doesn't exist.
Implements IPlatformFile.
FileSize() [2/2]
virtual int64 IAndroidPlatformFile::FileSize (const TCHAR * Filename, bool bAllowAssets) pure virtual
References Filename.
FileStartOffset()
virtual int64 IAndroidPlatformFile::FileStartOffset (const TCHAR * Filename) pure virtual
References Filename.
GetPlatformPhysical()
IAndroidPlatformFile & IAndroidPlatformFile::GetPlatformPhysical () static
GetStatData() [1/2]
virtual FFileStatData IPlatformFile::GetStatData (const TCHAR * FilenameOrDirectory) virtual
Return the stat data for the given file or directory.
Check the FFileStatData::bIsValid member before using the returned data
Implements IPlatformFile.
GetStatData() [2/2]
virtual FFileStatData IAndroidPlatformFile::GetStatData (const TCHAR * FilenameOrDirectory, bool bAllowAssets) pure virtual
IsAsset()
virtual bool IAndroidPlatformFile::IsAsset (const TCHAR * Filename) pure virtual
References Filename.
IterateDirectory() [1/3]
virtual bool IPlatformFile::IterateDirectory (const TCHAR * Directory, FDirectoryVisitor & Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implements IPlatformFile.
IterateDirectory() [2/3]
virtual bool IAndroidPlatformFile::IterateDirectory (const TCHAR * Directory, FDirectoryVisitor & Visitor, bool bAllowAssets) pure virtual
IterateDirectory() [3/3]
virtual bool IPlatformFile::IterateDirectory (const TCHAR * Directory, FDirectoryVisitorFunc Visitor) virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
IterateDirectoryStat() [1/3]
virtual bool IPlatformFile::IterateDirectoryStat (const TCHAR * Directory, FDirectoryStatVisitor & Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implements IPlatformFile.
IterateDirectoryStat() [2/3]
virtual bool IAndroidPlatformFile::IterateDirectoryStat (const TCHAR * Directory, FDirectoryStatVisitor & Visitor, bool bAllowAssets) pure virtual
References IPlatformFile::DirectoryExists(), IPlatformFile::FileExists(), IPlatformFile::FileSize(), IPlatformFile::GetStatData(), IPlatformFile::IterateDirectory(), and IPlatformFile::IterateDirectoryStat().
IterateDirectoryStat() [3/3]
virtual bool IPlatformFile::IterateDirectoryStat (const TCHAR * Directory, FDirectoryStatVisitorFunc Visitor) virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryStatVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
The documentation for this class was generated from the following file:
AndroidPlatformFile.h