Unreal Engine 5.6 C++ API: Audio Namespace Reference
Audio Namespace Reference
Defines how a sound changes volume with distance to the listener.
Namespaces
namespace Analytics
namespace AttenuationInterface
namespace ListenerOrientationInterface
namespace Quartz
namespace SourceOrientationInterface
namespace SpatializationInterface
Data Structures
class FAsyncSoundWavePCMWriteWorker
class FAudioFormatSettings
struct FAudioRecordingData
class FAudioSynesthesiaModule
class FAutoCorrelationPitchDetector
Pitch detector based on autocorrelation.
struct FAutoCorrelationPitchDetectorSettings
Settings for creating an autocorrelation pitch detector.
class FConstantQAnalyzer
FConstantQAnalyzer.
struct FConstantQAnalyzerSettings
FConstantQAnalyzerSettings.
class FConstantQFactory
FConstantQFactory.
struct FConstantQFrame
FConstantQFrame.
class FConstantQNRTFactory
FConstantQNRTFactory.
class FConstantQNRTResult
FConstantQNRTResult.
class FConstantQNRTSettings
FConstantQNRTSettings.
class FConstantQNRTWorker
FConstantQNRTWorker.
class FConstantQResult
FLoudnessResult contains the temporal evolution of loudness for the last buffer of audio analyzed.
struct FConstantQSettings
FConstantQSettings.
class FConstantQWorker
FConstantQWorker.
class FConvolutionReverb
FConvolutionReverb applies an impulse response to audio.
struct FConvolutionReverbGainEntry
Gain entry into convolution matrix.
struct FConvolutionReverbInitData
Data used to initialize the convolution algorithm.
struct FConvolutionReverbSettings
Runtime settings for convolution reverb.
class FEffectConvolutionReverb
class FEpicSynth1
class FEpicSynth1Voice
class FFFTPeakPitchDetector
FFT based pitch detector accel at detecting pitches at higher frequencies.
struct FFFTPeakPitchDetectorSettings
Settings for FFT base pitch detection.
class FFlexiverb
struct FFlexiverbSettings
class FLoudnessAnalyzer
FLoudnessAnalyzer.
struct FLoudnessAnalyzerSettings
Settings for FLoudnessAnalyzer.
struct FLoudnessDatum
Holds the loudness values per a time step.
struct FLoudnessEntry
Holds the loudness values per a time step.
class FLoudnessFactory
Defines the Loudness analyzer and creates related classes.
class FLoudnessNRTFactory
Defines the LoudnessNRT analyzer and creates related classes.
class FLoudnessNRTResult
FLoudnessNRTResult contains the temporal evolution of loudness.
class FLoudnessNRTSettings
Contains settings for loudness analyzer.
class FLoudnessNRTWorker
FLoudnessNRTWorker performs loudness analysis on input sample buffers.
class FLoudnessResult
FLoudnessResult contains the temporal evolution of loudness for the last buffer of audio analyzed.
class FLoudnessSettings
Contains settings for loudness analyzer.
class FLoudnessWorker
FLoudnessWorker performs loudness analysis on input sample buffers.
class FMaxStrengthPitchTracker
Track the maximum strength pitch.
struct FMaxStrengthPitchTrackerSettings
Settings for FMaxStrengthPitchTracker.
class FMeterAnalyzer
struct FMeterAnalyzerResults
struct FMeterAnalyzerSettings
struct FMeterEntry
Holds the meter results per a time step for each channel.
class FMeterFactory
Defines the meter analyzer and creates related classes.
class FMeterResult
FMeterResult contains the temporal evolution of loudness for the last buffer of audio analyzed.
class FMeterSettings
Contains settings for meter analyzer.
class FMeterWorker
FMeterWorker performs meter analysis on input sample buffers.
struct FModulationDestination
class FMonoWaveTable
class FMultichannelLoudnessAnalyzer
FMultichannelLoudnessAnalyzer.
struct FOnset
FOnset.
class FOnsetNRTFactory
FOnsetNRTFactory.
class FOnsetNRTResult
FOnsetNRTResult.
class FOnsetNRTSettings
FOnsetNRTSettings.
class FOnsetNRTWorker
FOnsetNRTWorker.
class FOnsetStrengthAnalyzer
FOnsetStrengthAnalyzer.
struct FOnsetStrengthSettings
Onset strength settings.
class FPeakPicker
struct FPeakPickerSettings
struct FPitchInfo
Contains information about a pitch observation.
struct FPitchTrackInfo
Contains information about a pitch track observation.
struct FQuartzClockTickRate
class FQuartzCrossThreadMessage
struct FQuartzGameThreadSubscriber
class FQuartzLatencyTimer
struct FQuartzMetronomeDelegateData
struct FQuartzOffset
struct FQuartzQuantizedCommandDelegateData
struct FQuartzQuantizedCommandHandle
struct FQuartzQuantizedCommandInitInfo
struct FQuartzQuantizedRequestData
struct FQuartzQueueCommandData
class FSimpleWaveReader
SimpleWaveReader class.
class FSimpleWaveWriter
class FSoundWavePCMLoader
class FSoundWavePCMWriter
class FSynesthesiaSpectrumAnalysisFactory
Defines the Spectrum analyzer and creates related classes.
class FSynesthesiaSpectrumAnalysisSettings
Contains settings for Spectrum analyzer.
class FSynesthesiaSpectrumAnalysisWorker
FSynesthesiaSpectrumWorker performs Spectrum analysis on input sample buffers.
class FSynesthesiaSpectrumAnalyzer
struct FSynesthesiaSpectrumAnalyzerSettings
struct FSynesthesiaSpectrumEntry
Holds the spectrum results per a time step for each channel.
class FSynesthesiaSpectrumResult
FSynesthesiaSpectrumResult contains the temporal evolution of loudness for the last buffer of audio analyzed.
class FTabularRenderHelper
class IAudioSynesthesiaCoreModule
class IPitchDetector
Pitch Detector Interface.
class IPitchTracker
Pitch Tracker Interface.
class IQuartzQuantizedCommand
class TSlidingBuffer
Typedefs
using AudioTaskQueueId = uint32
typedef int32 DefaultWaveTableIndexType
typedef FAsyncTask< FAsyncSoundWavePCMWriteWorker > FAsyncSoundWavePCMWriterTask
using FDeviceId = uint32
Typed identifier for Audio Device Id.
using FParameterInterfacePtr = TSharedPtr<FParameterInterface, ESPMode::ThreadSafe>
typedef TSharedPtr< FPatchOutput, ESPMode::ThreadSafe > FPatchOutputStrongPtr
using FSoundHandleID = uint32
Enumerations
enum class EConstantQScaling : uint8 { Linear , Decibel }
Denotes which magnitude scaling to apply to output.
enum class ELoudnessCurveType : uint8 {
A , B , C , D ,
K , None
}
Equal loudness curves from: ANSI Standards S1.4-1983 and S1.42-2001.
enum class EResult : uint8 { Success = 0 , Failure = 1 , NotImplemented = 2 }
enum class ESoundWavePCMWriterState : uint8 {
Idle , Generating , WritingToDisk , Suceeded ,
Failed , Cancelled
}
enum class ESoundWavePCMWriteTaskType : uint8 { GenerateSoundWave , GenerateAndWriteSoundWave , WriteSoundWave , WriteWavFile }
enum class ESynesthesiaSpectrumType : uint8 { MagnitudeSpectrum , PowerSpectrum , Decibel }
Functions
ICompressedAudioInfo * CreateSoundAssetDecoder (const FName &InRuntimeFormat)
Returns a decoder for the sound assets's given compression type.
FColor GetColorForSubmixType (const FName &InSubmixName)
FColor GetColorForSubmixType (const USoundSubmixBase *InSubmix)
AUDIOSYNESTHESIACORE_API float GetEqualLoudnessAWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve A.
AUDIOSYNESTHESIACORE_API float GetEqualLoudnessBWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve B.
AUDIOSYNESTHESIACORE_API float GetEqualLoudnessCWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve C.
AUDIOSYNESTHESIACORE_API float GetEqualLoudnessDWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve D.
AUDIOSYNESTHESIACORE_API float GetEqualLoudnessNoneWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve None.
template<typename ElementType>
void GetInterpolationParametersAtTimestamp (TArrayView< const ElementType > InArray, float InTimestamp, int32 &OutLowerIndex, int32 &OutUpperIndex, float &OutAlpha)
GetInterpolationParametersAtTimestamp.
FName GetNameForSubmixType (const USoundSubmixBase *InSubmix)
uint64 GetTransmitterID (uint64 ComponentID, UPTRINT WaveInstanceHash, uint32 PlayOrder)
Creates an ID for use by Parameter Transmitters that can differentiate between multiple voices playing on the same Audio Component.
const bool IsConnectionPerformingSoundfieldConversion (const USoundSubmixBase *InputSubmix, const USoundSubmixBase *OutputSubmix)
FORCEINLINE bool MatchesLogFilter (const FName &InName)
bool MatchesLogFilter (const TCHAR *InName)
AUDIOSYNESTHESIACORE_API void OnsetBacktrackIndices (TArrayView< const float > InOnsetEnvelope, TArrayView< const int32 > InOnsetIndices, TArray< int32 > &OutBacktrackedOnsetIndices)
Backtracks onset indices to the beginning of the onset attack.
AUDIOSYNESTHESIACORE_API void OnsetExtractIndices (const FPeakPickerSettings &InSettings, TArrayView< const float > InOnsetEnvelope, TArray< int32 > &OutOnsetIndices)
Extract onset indicies from an onset strength envelope.
AUDIOSYNESTHESIACORE_API FArchive & operator<< (FArchive &Ar, FConstantQFrame &Frame)
Serialize FConstantQFrame.
AUDIOSYNESTHESIACORE_API FArchive & operator<< (FArchive &Ar, FLoudnessDatum &Datum)
De/Serialize single loudness datum into archive.
AUDIOSYNESTHESIACORE_API FArchive & operator<< (FArchive &Ar, FOnset &Frame)
Serialize FOnset.
const TCHAR * ShortEnumString (const TCHAR *InString)
FName ToName (ESoundAssetCompressionType InDecoderType)
ESoundAssetCompressionType ToSoundAssetCompressionType (EDefaultAudioCompressionType InDefaultCompressionType)
template<class ListenerType>
class UE_DEPRECATED (5.5, "Message") TQuartzShareableCommandQueue
Variables
const FColor DefaultSubmixColor = FColor(143, 190, 0)
const FColor EndpointDefaultSubmixColor = FColor(249, 242, 231)
const FName EndpointSubmixName = TEXT("EndpointSubmix")
const FColor SoundfieldDefaultSubmixColor = FColor(0, 168, 198)
const FColor SoundfieldEndpointDefaultSubmixColor = FColor(64, 192, 203)
const FName SoundfieldEndpointSubmixName = TEXT("SoundfieldEndpointSubmix")
const FName SoundfieldSubmixName = TEXT("SoundfieldSubmix")
const FName SoundSubmixName = TEXT("SoundSubmix")
static const int32 WriterDefaultChunkSize = 8192
Detailed Description
Defines how a sound changes volume with distance to the listener.
Default parameter destination settings for source audio object.
Typedef Documentation
AudioTaskQueueId
using Audio::AudioTaskQueueId = uint32
Definition at line 12 of file Source/Runtime/Engine/Classes/Sound/SoundGenerator.h.
DefaultWaveTableIndexType
typedef int32 Audio::DefaultWaveTableIndexType
Definition at line 12 of file MonoWaveTable.h.
FAsyncSoundWavePCMWriterTask
typedef FAsyncTask<FAsyncSoundWavePCMWriteWorker> Audio::FAsyncSoundWavePCMWriterTask
Definition at line 141 of file SampleBufferIO.h.
FDeviceId
using Audio::FDeviceId = uint32
Typed identifier for Audio Device Id.
Definition at line 23 of file SoundBase.h.
FParameterInterfacePtr
using Audio::FParameterInterfacePtr = TSharedPtr<FParameterInterface, ESPMode::ThreadSafe>
Definition at line 24 of file SoundBase.h.
FPatchOutputStrongPtr
typedef TSharedPtr<FPatchOutput, ESPMode::ThreadSafe> Audio::FPatchOutputStrongPtr
Definition at line 68 of file AudioDevice.h.
FSoundHandleID
using Audio::FSoundHandleID = uint32
Definition at line 12 of file ISoundHandleSystem.h.
Enumeration Type Documentation
EConstantQScaling
enum class Audio::EConstantQScaling : uint8 strong
Denotes which magnitude scaling to apply to output.
Enumerator
Linear
CQT spectrum values conform to ESpectrumType, either magnitude or power.
Decibel
CQT spectrum values are in decibels.
Definition at line 15 of file ConstantQAnalyzer.h.
ELoudnessCurveType
enum class Audio::ELoudnessCurveType : uint8 strong
Equal loudness curves from: ANSI Standards S1.4-1983 and S1.42-2001.
Enumerator
A
B
C
D
K
None
Definition at line 14 of file LoudnessAnalyzer.h.
EResult
enum class Audio::EResult : uint8 strong
Enumerator
Success
Failure
NotImplemented
Definition at line 14 of file ISoundHandleSystem.h.
ESoundWavePCMWriterState
enum class Audio::ESoundWavePCMWriterState : uint8 strong
Enumerator
Idle
Generating
WritingToDisk
Suceeded
Failed
Cancelled
Definition at line 85 of file SampleBufferIO.h.
ESoundWavePCMWriteTaskType
enum class Audio::ESoundWavePCMWriteTaskType : uint8 strong
Enumerator
GenerateSoundWave
GenerateAndWriteSoundWave
WriteSoundWave
WriteWavFile
Definition at line 96 of file SampleBufferIO.h.
ESynesthesiaSpectrumType
enum class Audio::ESynesthesiaSpectrumType : uint8 strong
Enumerator
MagnitudeSpectrum
PowerSpectrum
Decibel
Definition at line 13 of file SynesthesiaSpectrumAnalyzer.h.
Function Documentation
CreateSoundAssetDecoder()
ICompressedAudioInfo * Audio::CreateSoundAssetDecoder (const FName & InRuntimeFormat)
Returns a decoder for the sound assets's given compression type.
Will return nullptr if the compression type is platform-dependent.
GetColorForSubmixType() [1/2]
FColor Audio::GetColorForSubmixType (const FName & InSubmixName)
GetColorForSubmixType() [2/2]
FColor Audio::GetColorForSubmixType (const USoundSubmixBase * InSubmix)
GetEqualLoudnessAWeigthForFrequency()
AUDIOSYNESTHESIACORE_API float Audio::GetEqualLoudnessAWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve A.
GetEqualLoudnessBWeigthForFrequency()
AUDIOSYNESTHESIACORE_API float Audio::GetEqualLoudnessBWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve B.
GetEqualLoudnessCWeigthForFrequency()
AUDIOSYNESTHESIACORE_API float Audio::GetEqualLoudnessCWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve C.
GetEqualLoudnessDWeigthForFrequency()
AUDIOSYNESTHESIACORE_API float Audio::GetEqualLoudnessDWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve D.
GetEqualLoudnessNoneWeigthForFrequency()
AUDIOSYNESTHESIACORE_API float Audio::GetEqualLoudnessNoneWeigthForFrequency (const float Freq)
Generate equal loudness weight for magnitude spectrum using curve None.
GetInterpolationParametersAtTimestamp()
template<typename ElementType> void Audio::GetInterpolationParametersAtTimestamp (TArrayView< const ElementType > InArray, float InTimestamp, int32 & OutLowerIndex, int32 & OutUpperIndex, float & OutAlpha)
GetInterpolationParametersAtTimestamp.
Calculates the indices and alpha parameter for interpolating between to elements in the array.
ElementType must be a type with a "float Timestamp;" member. InArray is a array of ElementTypes which are sorted in ascending order via the Timestamp member. InTimestamp is the query timestamp.
OutLowerIndex is populated with the index of the last element in InArray with a Timestamp less than or equal to InTimestamp. On error, this is set to INDEX_NONE OutUpperIndex is populated with the index of the first element in InArray with a Timestamp greater than InTimestamp. On error, this is set to INDEX_NONE OutAlpha is a number between 0.f and 1.f which describes the blending between the lower and upper indices. 0.f refers OutLowerIndex and 1.f to OutUpperIndex.
Definition at line 22 of file InterpolateSorted.h.
References FMath::Clamp(), INDEX_NONE, FMath::Max, TArrayView< InElementType, InSizeType >::Num(), SMALL_NUMBER, and Algo::UpperBoundBy().
GetNameForSubmixType()
FName Audio::GetNameForSubmixType (const USoundSubmixBase * InSubmix)
GetTransmitterID()
uint64 Audio::GetTransmitterID (uint64 ComponentID, UPTRINT WaveInstanceHash, uint32 PlayOrder)
Creates an ID for use by Parameter Transmitters that can differentiate between multiple voices playing on the same Audio Component.
IsConnectionPerformingSoundfieldConversion()
const bool Audio::IsConnectionPerformingSoundfieldConversion (const USoundSubmixBase * InputSubmix, const USoundSubmixBase * OutputSubmix)
MatchesLogFilter() [1/2]
FORCEINLINE bool Audio::MatchesLogFilter (const FName & InName)
Definition at line 27 of file AudioDebug.h.
References FORCEINLINE, InName, and MatchesLogFilter().
MatchesLogFilter() [2/2]
bool Audio::MatchesLogFilter (const TCHAR * InName)
References InName.
Referenced by MatchesLogFilter().
OnsetBacktrackIndices()
AUDIOSYNESTHESIACORE_API void Audio::OnsetBacktrackIndices (TArrayView< const float > InOnsetEnvelope, TArrayView< const int32 > InOnsetIndices, TArray< int32 > & OutBacktrackedOnsetIndices)
Backtracks onset indices to the beginning of the onset attack.
This is useful when generating splice points which retain the onset attack.
OnsetExtractIndices()
AUDIOSYNESTHESIACORE_API void Audio::OnsetExtractIndices (const FPeakPickerSettings & InSettings, TArrayView< const float > InOnsetEnvelope, TArray< int32 > & OutOnsetIndices)
Extract onset indicies from an onset strength envelope.
InSettings is the peak picker settings used to pick onset peaks from an onset strength envelope. InOnsetEnvelop is an onset strength envelope generated using the FOnsetStrengthAnalyzer. OutOnsetIndices contains the indices where onsets occur.
operator<<() [1/3]
AUDIOSYNESTHESIACORE_API FArchive & Audio::operator<< (FArchive & Ar, FConstantQFrame & Frame)
Serialize FConstantQFrame.
References Ar.
operator<<() [2/3]
AUDIOSYNESTHESIACORE_API FArchive & Audio::operator<< (FArchive & Ar, FLoudnessDatum & Datum)
De/Serialize single loudness datum into archive.
References Ar.
operator<<() [3/3]
AUDIOSYNESTHESIACORE_API FArchive & Audio::operator<< (FArchive & Ar, FOnset & Frame)
Serialize FOnset.
References Ar.
ShortEnumString()
const TCHAR * Audio::ShortEnumString (const TCHAR * InString) inline
Definition at line 12 of file AudioDebug.h.
References TCString< TCHAR >::Strstr(), and TEXT.
ToName()
FName Audio::ToName (ESoundAssetCompressionType InDecoderType) inline
Definition at line 371 of file SoundWave.h.
References ensure, TEXT, and ToName().
Referenced by ToName().
ToSoundAssetCompressionType()
ESoundAssetCompressionType Audio::ToSoundAssetCompressionType (EDefaultAudioCompressionType InDefaultCompressionType) inline
Definition at line 388 of file SoundWave.h.
References ensure, and ToSoundAssetCompressionType().
Referenced by ToSoundAssetCompressionType().
UE_DEPRECATED()
template<class ListenerType> class Audio::UE_DEPRECATED (5. 5, "Message")
Definition at line 1 of file QuartzSubscription.h.
Variable Documentation
DefaultSubmixColor
const FColor Audio::DefaultSubmixColor = FColor(143, 190, 0)
Definition at line 23 of file SoundSubmixDefaultColorPalette.h.
EndpointDefaultSubmixColor
const FColor Audio::EndpointDefaultSubmixColor = FColor(249, 242, 231)
Definition at line 25 of file SoundSubmixDefaultColorPalette.h.
EndpointSubmixName
const FName Audio::EndpointSubmixName = TEXT("EndpointSubmix")
Definition at line 31 of file SoundSubmixDefaultColorPalette.h.
SoundfieldDefaultSubmixColor
const FColor Audio::SoundfieldDefaultSubmixColor = FColor(0, 168, 198)
Definition at line 24 of file SoundSubmixDefaultColorPalette.h.
SoundfieldEndpointDefaultSubmixColor
const FColor Audio::SoundfieldEndpointDefaultSubmixColor = FColor(64, 192, 203)
Definition at line 26 of file SoundSubmixDefaultColorPalette.h.
SoundfieldEndpointSubmixName
const FName Audio::SoundfieldEndpointSubmixName = TEXT("SoundfieldEndpointSubmix")
Definition at line 32 of file SoundSubmixDefaultColorPalette.h.
SoundfieldSubmixName
const FName Audio::SoundfieldSubmixName = TEXT("SoundfieldSubmix")
Definition at line 30 of file SoundSubmixDefaultColorPalette.h.
SoundSubmixName
const FName Audio::SoundSubmixName = TEXT("SoundSubmix")
Definition at line 29 of file SoundSubmixDefaultColorPalette.h.
WriterDefaultChunkSize
const int32 Audio::WriterDefaultChunkSize = 8192 static
Definition at line 144 of file SampleBufferIO.h.
Referenced by Audio::FSoundWavePCMWriter::FSoundWavePCMWriter().