Unreal Engine 5.6 C++ API: FUpdatedComponentAsyncInput Struct Reference
FUpdatedComponentAsyncInput Struct Reference
#include "CharacterMovementComponentAsync.h"
Public Member Functions
virtual ~FUpdatedComponentAsyncInput ()
virtual bool AreSymmetricRotations (const FQuat &A, const FQuat &B, const FVector &Scale3D) const
FVector GetForwardVector () const
FVector GetPosition () const
FVector GetRightVector () const
FQuat GetRotation () const
FVector GetUpVector () const
virtual bool MoveComponent (const FVector &Delta, const FQuat &NewRotationQuat, bool bSweep, FHitResult *OutHit, EMoveComponentFlags MoveFlags, ETeleportType Teleport, const FCharacterMovementComponentAsyncInput &Input, FCharacterMovementComponentAsyncOutput &Output) const
void SetPosition (const FVector &Position) const
void SetRotation (const FQuat &Rotation) const
Static Public Member Functions
static void PullBackHit (FHitResult &Hit, const FVector &Start, const FVector &End, const float Dist)
static bool ShouldCheckOverlapFlagToQueueOverlaps (const UPrimitiveComponent &ThisComponent)
static bool ShouldIgnoreHitResult (const UWorld *InWorld, FHitResult const &TestHit, FVector const &MovementDirDenormalized, const AActor *MovingActor, EMoveComponentFlags MoveFlags)
static bool ShouldIgnoreOverlapResult (const UWorld *World, const AActor *ThisActor, const UPrimitiveComponent &ThisComponent, const AActor *OtherActor, const UPrimitiveComponent &OtherComponent)
Data Fields
bool bForceGatherOverlaps
bool bGatherOverlaps
bool bIsQueryCollisionEnabled
bool bIsSimulatingPhysics
FCollisionShape CollisionShape
FCollisionResponseParams MoveComponentCollisionResponseParams
FComponentQueryParams MoveComponentQueryParams
FPhysicsActorHandle PhysicsHandle
FVector Scale
UPrimitiveComponent * UpdatedComponent
Detailed Description
Definition at line 328 of file CharacterMovementComponentAsync.h.
Constructor & Destructor Documentation
~FUpdatedComponentAsyncInput()
virtual FUpdatedComponentAsyncInput::~FUpdatedComponentAsyncInput () inline virtual
Definition at line 330 of file CharacterMovementComponentAsync.h.
Member Function Documentation
AreSymmetricRotations()
virtual bool FUpdatedComponentAsyncInput::AreSymmetricRotations (const FQuat & A, const FQuat & B, const FVector & Scale3D) const virtual
References A, B, and FVector.
GetForwardVector()
FVector FUpdatedComponentAsyncInput::GetForwardVector () const inline
Definition at line 342 of file CharacterMovementComponentAsync.h.
References FVector, UE::Math::TQuat< T >::GetAxisX(), and GetRotation().
GetPosition()
FVector FUpdatedComponentAsyncInput::GetPosition () const
References FVector.
GetRightVector()
FVector FUpdatedComponentAsyncInput::GetRightVector () const inline
Definition at line 343 of file CharacterMovementComponentAsync.h.
References FVector, UE::Math::TQuat< T >::GetAxisY(), and GetRotation().
GetRotation()
FQuat FUpdatedComponentAsyncInput::GetRotation () const
Referenced by GetForwardVector(), GetRightVector(), and GetUpVector().
GetUpVector()
FVector FUpdatedComponentAsyncInput::GetUpVector () const inline
Definition at line 344 of file CharacterMovementComponentAsync.h.
References FVector, UE::Math::TQuat< T >::GetAxisZ(), and GetRotation().
MoveComponent()
virtual bool FUpdatedComponentAsyncInput::MoveComponent (const FVector & Delta, const FQuat & NewRotationQuat, bool bSweep, FHitResult * OutHit, EMoveComponentFlags MoveFlags, ETeleportType Teleport, const FCharacterMovementComponentAsyncInput & Input, FCharacterMovementComponentAsyncOutput & Output) const virtual
References FVector, and Input.
PullBackHit()
void FUpdatedComponentAsyncInput::PullBackHit (FHitResult & Hit, const FVector & Start, const FVector & End, const float Dist) static
References End, and FVector.
SetPosition()
void FUpdatedComponentAsyncInput::SetPosition (const FVector & Position) const
References FVector, and Position.
SetRotation()
void FUpdatedComponentAsyncInput::SetRotation (const FQuat & Rotation) const
References Rotation.
ShouldCheckOverlapFlagToQueueOverlaps()
bool FUpdatedComponentAsyncInput::ShouldCheckOverlapFlagToQueueOverlaps (const UPrimitiveComponent & ThisComponent) static
ShouldIgnoreHitResult()
bool FUpdatedComponentAsyncInput::ShouldIgnoreHitResult (const UWorld * InWorld, FHitResult const & TestHit, FVector const & MovementDirDenormalized, const AActor * MovingActor, EMoveComponentFlags MoveFlags) static
References FVector.
ShouldIgnoreOverlapResult()
bool FUpdatedComponentAsyncInput::ShouldIgnoreOverlapResult (const UWorld * World, const AActor * ThisActor, const UPrimitiveComponent & ThisComponent, const AActor * OtherActor, const UPrimitiveComponent & OtherComponent) static
Field Documentation
bForceGatherOverlaps
bool FUpdatedComponentAsyncInput::bForceGatherOverlaps
Definition at line 363 of file CharacterMovementComponentAsync.h.
bGatherOverlaps
bool FUpdatedComponentAsyncInput::bGatherOverlaps
Definition at line 364 of file CharacterMovementComponentAsync.h.
bIsQueryCollisionEnabled
bool FUpdatedComponentAsyncInput::bIsQueryCollisionEnabled
Definition at line 352 of file CharacterMovementComponentAsync.h.
bIsSimulatingPhysics
bool FUpdatedComponentAsyncInput::bIsSimulatingPhysics
Definition at line 353 of file CharacterMovementComponentAsync.h.
CollisionShape
FCollisionShape FUpdatedComponentAsyncInput::CollisionShape
Definition at line 362 of file CharacterMovementComponentAsync.h.
MoveComponentCollisionResponseParams
FCollisionResponseParams FUpdatedComponentAsyncInput::MoveComponentCollisionResponseParams
Definition at line 357 of file CharacterMovementComponentAsync.h.
MoveComponentQueryParams
FComponentQueryParams FUpdatedComponentAsyncInput::MoveComponentQueryParams
Definition at line 356 of file CharacterMovementComponentAsync.h.
PhysicsHandle
FPhysicsActorHandle FUpdatedComponentAsyncInput::PhysicsHandle
Definition at line 360 of file CharacterMovementComponentAsync.h.
Scale
FVector FUpdatedComponentAsyncInput::Scale
Definition at line 365 of file CharacterMovementComponentAsync.h.
UpdatedComponent
UPrimitiveComponent* FUpdatedComponentAsyncInput::UpdatedComponent
Definition at line 359 of file CharacterMovementComponentAsync.h.
The documentation for this struct was generated from the following file:
CharacterMovementComponentAsync.h