Unreal Engine 5.6 C++ API: AGameModeBase Class Reference
AGameModeBase Class Reference
#include "GameModeBase.h"
Public Member Functions
virtual bool AllowCheats (APlayerController *P)
Return true if player should be allowed to use cheats by default.
virtual bool IsHandlingReplays ()
Returns true if replays will start/stop during gameplay starting/stopping.
virtual void Logout (AController *Exiting)
Called when a Controller with a PlayerState leaves the game or is destroyed.
virtual void PreInitializeComponents () override
virtual void Reset () override
virtual void SetPlayerDefaults (APawn *PlayerPawn)
Initializes player pawn back to starting values, called from RestartPlayer.
virtual APlayerController * SpawnPlayerController (ENetRole InRemoteRole, const FString &Options)
Spawns the appropriate PlayerController for the given options; split out from Login() for easier overriding.
virtual bool SpawnPlayerFromSimulate (const FVector &NewLocation, const FRotator &NewRotation)
Used in the editor to spawn a PIE player after the game has already started.
UE_DEPRECATED (4.20, "SpawnPlayerController with Location and Rotation is deprecated, call or override the version that takes an Option string instead") 1 virtual APlayerController *SpawnPlayerController(ENetRole InRemoteRole
UE_DEPRECATED (4.20, "SpawnReplayPlayerController is deprecated, replay controller spawning is handled inside the new version of the SpawnPlayerController function") 1 virtual APlayerController *SpawnReplayPlayerController(ENetRole InRemoteRole
UFUNCTION () 1 AActor *ChoosePlayerStart(AController *Player)
Return the 'best' player start for this player to spawn from Default implementation looks for a random unoccupied spot.
UFUNCTION () 1 AActor *FindPlayerStart(AController *Player
Return the specific player start actor that should be used for the next spawn This will either use a previously saved startactor, or calls ChoosePlayerStart.
UFUNCTION () 1 APawn *SpawnDefaultPawnAtTransform(AController *NewPlayer
Called during RestartPlayer to actually spawn the player's pawn, when using a transform.
UFUNCTION () 1 APawn *SpawnDefaultPawnFor(AController *NewPlayer
Called during RestartPlayer to actually spawn the player's pawn, when using a start spot.
UFUNCTION () 1 bool CanSpectate(APlayerController *Viewer
Return whether Viewer is allowed to spectate from the point of view of ViewTarget.
UFUNCTION () 1 bool MustSpectate(APlayerController *NewPlayerController) const
Returns true if NewPlayerController may only join the server as a spectator.
UFUNCTION () 1 bool PlayerCanRestart(APlayerController *Player)
Returns true if it's valid to call RestartPlayer.
UFUNCTION () 1 virtual void ChangeName(AController *Controller
Sets the name for a controller.
UFUNCTION () 1 virtual void RestartPlayer(AController *NewPlayer)
Tries to spawn the player's pawn, at the location returned by FindPlayerStart.
UFUNCTION () 1 virtual void RestartPlayerAtPlayerStart(AController *NewPlayer
Tries to spawn the player's pawn at the specified actor's location.
UFUNCTION () 1 virtual void RestartPlayerAtTransform(AController *NewPlayer
Tries to spawn the player's pawn at a specific location.
UFUNCTION () 1 void HandleStartingNewPlayer(APlayerController *NewPlayer)
Signals that a player is ready to enter the game, which may start it up.
UFUNCTION () 1 void InitStartSpot(AActor *StartSpot
Called from RestartPlayerAtPlayerStart, can be used to initialize the start spawn actor.
UFUNCTION ()) 1 AActor *K2_FindPlayerStart(AController *Player
Return the specific player start actor that should be used for the next spawn This will either use a previously saved startactor, or calls ChoosePlayerStart.
UFUNCTION ()) 1 void K2_OnChangeName(AController *Other
Overridable event for GameMode blueprint to respond to a change name call.
UFUNCTION ()) 1 void K2_OnLogout(AController *ExitingController)
Implementable event when a Controller with a PlayerState leaves the game.
UFUNCTION ()) 1 void K2_OnRestartPlayer(AController *NewPlayer)
Implementable event called at the end of RestartPlayer.
UFUNCTION ()) 1 void K2_PostLogin(APlayerController *NewPlayer)
Notification that a player has successfully logged in, and has been given a player controller.
UPROPERTY () FText DefaultPlayerName
The default player name assigned to players that join with no name specified.
Data Fields
const FString bool bNameChange
const FString & IncomingName = TEXT(""))
const FString & NewName
AController * NewPlayer
FVector const & SpawnLocation
FVector const FRotator const & SpawnRotation
const FTransform & SpawnTransform
AActor * StartSpot
APlayerState * ViewTarget
Protected Member Functions
virtual void FailedToRestartPlayer (AController *NewPlayer)
Called in the event that we fail to spawn a controller's pawn, which maybe it didn't have one or maybe it tried to spawn and was destroyed due to collision.
virtual void FinishRestartPlayer (AController *NewPlayer, const FRotator &StartRotation)
Handles second half of RestartPlayer.
virtual void GenericPlayerInitialization (AController *C)
Handles all player initialization that is shared between the travel methods (i.e.
virtual FString InitNewPlayer (APlayerController *NewPlayerController, const FUniqueNetIdRepl &UniqueId, const FString &Options, const FString &Portal=TEXT(""))
Customize incoming player based on URL options.
virtual void InitSeamlessTravelPlayer (AController *NewController)
Handles initializing a seamless travel player, handles logic similar to InitNewPlayer.
virtual void OnPostLogin (AController *NewPlayer)
Called as part of the PostLogin process.
virtual APlayerController * ProcessClientTravel (FString &URL, bool bSeamless, bool bAbsolute)
Notifies all clients to travel to the specified URL.
virtual void ReplicateStreamingStatus (APlayerController *PC)
Replicates the current level streaming status to the given PlayerController.
virtual bool ShouldSpawnAtStartSpot (AController *Player)
Return true if FindPlayerStart should use the StartSpot stored on Player instead of calling ChoosePlayerStart.
virtual bool ShouldStartInCinematicMode (APlayerController *Player, bool &OutHidePlayer, bool &OutHideHud, bool &OutDisableMovement, bool &OutDisableTurning)
Check to see if we should start in cinematic mode.
virtual APlayerController * SpawnPlayerControllerCommon (ENetRole InRemoteRole, FVector const &SpawnLocation, FRotator const &SpawnRotation, TSubclassOf< APlayerController > InPlayerControllerClass)
Does the work of spawning a player controller of the given class at the given transform.
UFUNCTION () 1 void InitializeHUDForPlayer(APlayerController *NewPlayer)
Initialize the AHUD object for a player.
UFUNCTION ()) 1 void K2_OnSwapPlayerControllers(APlayerController *OldPC
Called when a PlayerController is swapped to a new one during seamless travel.
virtual void UpdateGameplayMuteList (APlayerController *aPlayer)
Used to notify the game type that it is ok to update a player's gameplay specific muting information now.
virtual bool UpdatePlayerStartSpot (AController *Player, const FString &Portal, FString &OutErrorMessage)
Attempts to initialize the 'StartSpot' of the Player.
UPROPERTY() uint32 bStartPlayersAsSpectators UPROPERTY() uint32 bPauseable UPROPERTY () EReplicationSystem GameNetDriverReplicationSystem
Whether the game perform map travels using SeamlessTravel() which loads in the background and doesn't disconnect clients.
Protected Attributes
APlayerController * NewPC
TArray< FCanUnpause > Pausers
The list of delegates to check before unpausing a game.
Private Member Functions
virtual bool AllowPausing (APlayerController *PC=nullptr)
Returns true if the player is allowed to pause the game.
virtual bool CanServerTravel (const FString &URL, bool bAbsolute)
Returns true if allowed to server travel.
virtual bool ClearPause ()
Checks the list of delegates to determine if the pausing can be cleared.
DECLARE_DELEGATE_OneParam (FOnPreLoginCompleteDelegate, const FString &)
void ForceClearUnpauseDelegates (AActor *PauseActor)
Forcibly removes an object's CanUnpause delegates from the list of pausers.
virtual void GameWelcomePlayer (UNetConnection *Connection, FString &RedirectURL)
Allows game to send network messages to provide more information to the client joining the game via NMT_GameSpecific (for example required DLC) the out string RedirectURL is built in and send automatically if only a simple URL is needed.
EReplicationSystem GetGameNetDriverReplicationSystem () const
Return if the game mode is requesting a specific replication system to be used for the GameNetDriver.
virtual TSubclassOf< AGameSession > GetGameSessionClass () const
Return GameSession class to use for this game.
template<class T>
T * GetGameState () const
Helper template to returns the current GameState casted to the desired type.
virtual TSubclassOf< APlayerController > GetPlayerControllerClassToSpawnForSeamlessTravel (APlayerController *PreviousPlayerController)
Gets the class that should be used for spawning a player controller during seamless travel.
virtual void GetSeamlessTravelActorList (bool bToTransition, TArray< AActor * > &ActorList)
called on server during seamless level transitions to get the list of Actors that should be moved into the new level PlayerControllers, Role < ROLE_Authority Actors, and any non-Actors that are inside an Actor that is in the list (i.e.
virtual void HandleSeamlessTravelPlayer (AController *&C)
Handles reinitializing players that remained through a seamless level transition called from C++ for players that finished loading after the server.
HIDE_ACTOR_TRANSFORM_FUNCTIONS ()
virtual GENERATED_UCLASS_BODY() public void InitGameState ()
Initialize the game.
virtual bool IsPaused () const
Returns true if the game is paused.
virtual APlayerController * Login (UPlayer *NewPlayer, ENetRole InRemoteRole, const FString &Portal, const FString &Options, const FUniqueNetIdRepl &UniqueId, FString &ErrorMessage)
Called to login new players by creating a player controller, overridable by the game.
virtual void PostLogin (APlayerController *NewPlayer)
Called after a successful login.
virtual void PostSeamlessTravel ()
Called after a seamless level transition has been completed on the new GameMode.
virtual void PreLogin (const FString &Options, const FString &Address, const FUniqueNetIdRepl &UniqueId, FString &ErrorMessage)
Accept or reject a player attempting to join the server.
virtual void PreLoginAsync (const FString &Options, const FString &Address, const FUniqueNetIdRepl &UniqueId, const FOnPreLoginCompleteDelegate &OnComplete)
Async version of PreLogin that MUST call OnComplete when done, otherwise incoming client connections will hang or timeout.
virtual void ProcessServerTravel (const FString &URL, bool bAbsolute=false)
Handles request for server to travel to a new URL, with all players.
virtual bool SetPause (APlayerController *PC, FCanUnpause CanUnpauseDelegate=FCanUnpause())
Adds the delegate to the list if the player Controller has the right to pause the game.
virtual void StartToLeaveMap ()
Start the transition out of the current map.
virtual void SwapPlayerControllers (APlayerController *OldPC, APlayerController *NewPC)
Used to swap a viewport/connection's PlayerControllers when seamless traveling and the new GameMode's controller class is different than the previous includes network handling.
UE_DEPRECATED (5.6, "This functionality has been moved into OnPostLogin. You cannot call that function directly, it is executed at the end of PostLogin.") 1 void DispatchPostLogin(AController *NewPlayer)
Called as part of the PostLogin process.
UFUNCTION () 1 bool ShouldReset(AActor *ActorToReset)
Overridable function to determine whether an Actor should have Reset called when the game has Reset called on it.
UFUNCTION () 1 UClass *GetDefaultPawnClassForController(AController *InController)
Returns default pawn class for given controller.
UFUNCTION () 1 virtual bool HasMatchEnded() const
Returns true if the match can be considered ended.
UFUNCTION () 1 virtual bool HasMatchStarted() const
Returns true if the match start callbacks have been called.
UFUNCTION () 1 virtual int32 GetNumPlayers()
Returns number of active human players, excluding spectators.
UFUNCTION () 1 virtual int32 GetNumSpectators()
Returns number of human players currently spectating.
UFUNCTION () 1 virtual void ResetLevel()
Overridable function called when resetting level.
UFUNCTION () 1 virtual void ReturnToMainMenuHost()
Return to main menu, and disconnect any players.
UFUNCTION () 1 virtual void StartPlay()
Transitions to calls BeginPlay on actors.
UPROPERTY () FString OptionsString
Save options string and parse it when needed.
UPROPERTY () TObjectPtr< AGameSession > GameSession
Game Session handles login approval, arbitration, online game interface.
UPROPERTY () TObjectPtr< AGameStateBase > GameState
GameState is used to replicate game state relevant properties to all clients.
UPROPERTY () TObjectPtr< AServerStatReplicator > ServerStatReplicator
UPROPERTY () TSubclassOf< AGameSession > GameSessionClass
Class of GameSession, which handles login approval and online game interface.
UPROPERTY () TSubclassOf< AGameStateBase > GameStateClass
Class of GameState associated with this GameMode.
UPROPERTY () TSubclassOf< APawn > DefaultPawnClass
The default pawn class used by players.
UPROPERTY () TSubclassOf< APlayerController > PlayerControllerClass
The class of PlayerController to spawn for players logging in.
UPROPERTY () TSubclassOf< APlayerController > ReplaySpectatorPlayerControllerClass
The PlayerController class used when spectating a network replay.
UPROPERTY () TSubclassOf< APlayerState > PlayerStateClass
A PlayerState of this class will be associated with every player to replicate relevant player information to all clients.
UPROPERTY () TSubclassOf< AServerStatReplicator > ServerStatReplicatorClass
UPROPERTY () TSubclassOf< ASpectatorPawn > SpectatorClass
The pawn class used by the PlayerController for players when spectating.
UPROPERTY ()) TSubclassOf< AHUD > HUDClass
HUD class this game uses.
Detailed Description
Definition at line 47 of file GameModeBase.h.
Member Function Documentation
AllowCheats()
virtual bool AGameModeBase::AllowCheats (APlayerController * P) virtual
Return true if player should be allowed to use cheats by default.
References AllowCheats().
Referenced by AllowCheats().
AllowPausing()
virtual bool AGameModeBase::AllowPausing (APlayerController * PC = nullptr) private virtual
Returns true if the player is allowed to pause the game.
CanServerTravel()
virtual bool AGameModeBase::CanServerTravel (const FString & URL, bool bAbsolute) private virtual
Returns true if allowed to server travel.
ClearPause()
virtual bool AGameModeBase::ClearPause () private virtual
Checks the list of delegates to determine if the pausing can be cleared.
If the delegate says it's ok to unpause, that delegate is removed from the list and the rest are checked. The game is considered unpaused when the list is empty.
DECLARE_DELEGATE_OneParam()
AGameModeBase::DECLARE_DELEGATE_OneParam (FOnPreLoginCompleteDelegate , const FString &) private
FailedToRestartPlayer()
virtual void AGameModeBase::FailedToRestartPlayer (AController * NewPlayer) protected virtual
Called in the event that we fail to spawn a controller's pawn, which maybe it didn't have one or maybe it tried to spawn and was destroyed due to collision.
References FailedToRestartPlayer(), and NewPlayer.
Referenced by FailedToRestartPlayer().
FinishRestartPlayer()
virtual void AGameModeBase::FinishRestartPlayer (AController * NewPlayer, const FRotator & StartRotation) protected virtual
Handles second half of RestartPlayer.
References FinishRestartPlayer(), and NewPlayer.
Referenced by FinishRestartPlayer().
ForceClearUnpauseDelegates()
void AGameModeBase::ForceClearUnpauseDelegates (AActor * PauseActor) private
Forcibly removes an object's CanUnpause delegates from the list of pausers.
If any of the object's CanUnpause delegate handlers were in the list, triggers a call to ClearPause().
Called when the player controller is being destroyed to prevent the game from being stuck in a paused state when a PC that paused the game is destroyed before the game is unpaused.
GameWelcomePlayer()
virtual void AGameModeBase::GameWelcomePlayer (UNetConnection * Connection, FString & RedirectURL) private virtual
Allows game to send network messages to provide more information to the client joining the game via NMT_GameSpecific (for example required DLC) the out string RedirectURL is built in and send automatically if only a simple URL is needed.
GenericPlayerInitialization()
virtual void AGameModeBase::GenericPlayerInitialization (AController * C) protected virtual
Handles all player initialization that is shared between the travel methods (i.e.
called from both PostLogin() and HandleSeamlessTravelPlayer())
References GenericPlayerInitialization().
Referenced by GenericPlayerInitialization().
GetGameNetDriverReplicationSystem()
EReplicationSystem AGameModeBase::GetGameNetDriverReplicationSystem () const inline private
Return if the game mode is requesting a specific replication system to be used for the GameNetDriver.
Definition at line 122 of file GameModeBase.h.
References GetGameNetDriverReplicationSystem().
Referenced by GetGameNetDriverReplicationSystem().
GetGameSessionClass()
virtual TSubclassOf< AGameSession > AGameModeBase::GetGameSessionClass () const private virtual
Return GameSession class to use for this game.
GetGameState()
template<class T> T * AGameModeBase::GetGameState () const inline private
Helper template to returns the current GameState casted to the desired type.
Definition at line 137 of file GameModeBase.h.
References Cast().
GetPlayerControllerClassToSpawnForSeamlessTravel()
virtual TSubclassOf< APlayerController > AGameModeBase::GetPlayerControllerClassToSpawnForSeamlessTravel (APlayerController * PreviousPlayerController) private virtual
Gets the class that should be used for spawning a player controller during seamless travel.
Parameters
PreviousPlayerController The player controller from the prior level
Returns
The class that should be used for spawning the player controller
GetSeamlessTravelActorList()
virtual void AGameModeBase::GetSeamlessTravelActorList (bool bToTransition, TArray< AActor * > & ActorList) private virtual
called on server during seamless level transitions to get the list of Actors that should be moved into the new level PlayerControllers, Role < ROLE_Authority Actors, and any non-Actors that are inside an Actor that is in the list (i.e.
Object.Outer == Actor in the list) are all automatically moved regardless of whether they're included here only dynamic actors in the PersistentLevel may be moved (this includes all actors spawned during gameplay) this is called for both parts of the transition because actors might change while in the middle (e.g. players might join or leave the game)
See also
also PlayerController::GetSeamlessTravelActorList() (the function that's called on clients)
Parameters
bToTransition true if we are going from old level to transition map, false if we are going from transition map to new level
ActorList (out) list of actors to maintain
HandleSeamlessTravelPlayer()
virtual void AGameModeBase::HandleSeamlessTravelPlayer (AController *& C) private virtual
Handles reinitializing players that remained through a seamless level transition called from C++ for players that finished loading after the server.
Parameters
C the Controller to handle
HIDE_ACTOR_TRANSFORM_FUNCTIONS()
AGameModeBase::HIDE_ACTOR_TRANSFORM_FUNCTIONS () private
References HIDE_ACTOR_TRANSFORM_FUNCTIONS().
Referenced by HIDE_ACTOR_TRANSFORM_FUNCTIONS().
InitGameState()
virtual GENERATED_UCLASS_BODY() public void AGameModeBase::InitGameState () private virtual
Initialize the game.
The GameMode's InitGame() event is called before any other functions (including PreInitializeComponents()) and is used by the GameMode to initialize parameters and spawn its helper classes.
Warning
: this is called before actors' PreInitializeComponents. Initialize the GameState actor with default settings called during PreInitializeComponents() of the GameMode after a GameState has been spawned as well as during Reset()
InitNewPlayer()
virtual FString AGameModeBase::InitNewPlayer (APlayerController * NewPlayerController, const FUniqueNetIdRepl & UniqueId, const FString & Options, const FString & Portal = TEXT("")) protected virtual
Customize incoming player based on URL options.
Parameters
NewPlayerController player logging in
UniqueId unique id for this player
Options URL options that came at login
References InitNewPlayer(), and TEXT.
Referenced by InitNewPlayer().
InitSeamlessTravelPlayer()
virtual void AGameModeBase::InitSeamlessTravelPlayer (AController * NewController) protected virtual
Handles initializing a seamless travel player, handles logic similar to InitNewPlayer.
References InitSeamlessTravelPlayer().
Referenced by InitSeamlessTravelPlayer().
IsHandlingReplays()
virtual bool AGameModeBase::IsHandlingReplays () virtual
Returns true if replays will start/stop during gameplay starting/stopping.
References IsHandlingReplays().
Referenced by IsHandlingReplays().
IsPaused()
virtual bool AGameModeBase::IsPaused () const private virtual
Returns true if the game is paused.
Login()
virtual APlayerController * AGameModeBase::Login (UPlayer * NewPlayer, ENetRole InRemoteRole, const FString & Portal, const FString & Options, const FUniqueNetIdRepl & UniqueId, FString & ErrorMessage) private virtual
Called to login new players by creating a player controller, overridable by the game.
Sets up basic properties of the player (name, unique id, registers with backend, etc) and should not be used to do more complicated game logic. The player controller is not fully initialized within this function as far as networking is concerned. Save "game logic" for PostLogin which is called shortly afterward.
Parameters
NewPlayer pointer to the UPlayer object that represents this player (either local or remote)
RemoteRole the remote role this controller has
Portal desired portal location specified by the client
Options game options passed in by the client at login
UniqueId platform specific unique identifier for the logging in player
ErrorMessage [out] error message, if any, why this login will be failing
If login is successful, returns a new PlayerController to associate with this player. Login fails if ErrorMessage string is set.
Returns
a new player controller for the logged in player, NULL if login failed for any reason
References NewPlayer.
Logout()
virtual void AGameModeBase::Logout (AController * Exiting) virtual
Called when a Controller with a PlayerState leaves the game or is destroyed.
References Logout().
Referenced by Logout().
OnPostLogin()
virtual void AGameModeBase::OnPostLogin (AController * NewPlayer) protected virtual
Called as part of the PostLogin process.
This is the last step before we spawn a new player.
References NewPlayer, and OnPostLogin().
Referenced by OnPostLogin().
PostLogin()
virtual void AGameModeBase::PostLogin (APlayerController * NewPlayer) private virtual
Called after a successful login.
This is the first place it is safe to call replicated functions on the PlayerController.
References NewPlayer.
PostSeamlessTravel()
virtual void AGameModeBase::PostSeamlessTravel () private virtual
Called after a seamless level transition has been completed on the new GameMode.
Used to reinitialize players already in the game as they won't have *Login() called on them
PreInitializeComponents()
virtual void AGameModeBase::PreInitializeComponents () override virtual
References PreInitializeComponents().
Referenced by PreInitializeComponents().
PreLogin()
virtual void AGameModeBase::PreLogin (const FString & Options, const FString & Address, const FUniqueNetIdRepl & UniqueId, FString & ErrorMessage) private virtual
Accept or reject a player attempting to join the server.
Fails login if you set the ErrorMessage to a non-empty string. PreLogin is called before Login. Significant game time may pass before Login is called
Parameters
Options The URL options (e.g. name/spectator) the player has passed
Address The network address of the player
UniqueId The unique id the player has passed to the server
ErrorMessage When set to a non-empty value, the player will be rejected using the error message set
PreLoginAsync()
virtual void AGameModeBase::PreLoginAsync (const FString & Options, const FString & Address, const FUniqueNetIdRepl & UniqueId, const FOnPreLoginCompleteDelegate & OnComplete) private virtual
Async version of PreLogin that MUST call OnComplete when done, otherwise incoming client connections will hang or timeout.
This allows servers to make requests to other services for verification of login credentials without blocking the game thread. By default, this calls PreLogin() and OnComplete immediately to not break backwards compatibility. When overriding this, be sure checks in PreLogin are also run, and that the GameModePreLoginEvent is broadcast.
ProcessClientTravel()
virtual APlayerController * AGameModeBase::ProcessClientTravel (FString & URL, bool bSeamless, bool bAbsolute) protected virtual
Notifies all clients to travel to the specified URL.
Parameters
URL a string containing the mapname (or IP address) to travel to, along with option key/value pairs
bSeamless indicates whether the travel should use seamless travel or not.
bAbsolute indicates which type of travel the server will perform (i.e. TRAVEL_Relative or TRAVEL_Absolute)
References ProcessClientTravel().
Referenced by ProcessClientTravel().
ProcessServerTravel()
virtual void AGameModeBase::ProcessServerTravel (const FString & URL, bool bAbsolute = false) private virtual
Handles request for server to travel to a new URL, with all players.
ReplicateStreamingStatus()
virtual void AGameModeBase::ReplicateStreamingStatus (APlayerController * PC) protected virtual
Replicates the current level streaming status to the given PlayerController.
References ReplicateStreamingStatus().
Referenced by ReplicateStreamingStatus().
Reset()
virtual void AGameModeBase::Reset () override virtual
References Reset().
Referenced by Reset().
SetPause()
virtual bool AGameModeBase::SetPause (APlayerController * PC, FCanUnpause CanUnpauseDelegate = FCanUnpause()) private virtual
Adds the delegate to the list if the player Controller has the right to pause the game.
The delegate is called to see if it is ok to unpause the game, e.g. the reason the game was paused has been cleared.
Parameters
PC the player Controller to check for admin privs
CanUnpauseDelegate the delegate to query when checking for unpause
SetPlayerDefaults()
virtual void AGameModeBase::SetPlayerDefaults (APawn * PlayerPawn) virtual
Initializes player pawn back to starting values, called from RestartPlayer.
References SetPlayerDefaults().
Referenced by SetPlayerDefaults().
ShouldSpawnAtStartSpot()
virtual bool AGameModeBase::ShouldSpawnAtStartSpot (AController * Player) protected virtual
Return true if FindPlayerStart should use the StartSpot stored on Player instead of calling ChoosePlayerStart.
References ShouldSpawnAtStartSpot().
Referenced by ShouldSpawnAtStartSpot().
ShouldStartInCinematicMode()
virtual bool AGameModeBase::ShouldStartInCinematicMode (APlayerController * Player, bool & OutHidePlayer, bool & OutHideHud, bool & OutDisableMovement, bool & OutDisableTurning) protected virtual
Check to see if we should start in cinematic mode.
Parameters
OutHidePlayer Whether to hide the player
OutHideHud Whether to hide the HUD
OutDisableMovement Whether to disable movement
OutDisableTurning Whether to disable turning
Returns
bool true if we should turn on cinematic mode, false if if we should not.
References ShouldStartInCinematicMode().
Referenced by ShouldStartInCinematicMode().
SpawnPlayerController()
virtual APlayerController * AGameModeBase::SpawnPlayerController (ENetRole InRemoteRole, const FString & Options) virtual
Spawns the appropriate PlayerController for the given options; split out from Login() for easier overriding.
Override this to conditionally spawn specialized PlayerControllers, for instance.
Parameters
RemoteRole the role this controller will play remotely
Options the options string from the new player's URL
Returns
PlayerController for the player, NULL if there is any reason this player shouldn't exist or due to some error
References SpawnPlayerController().
Referenced by SpawnPlayerController().
SpawnPlayerControllerCommon()
virtual APlayerController * AGameModeBase::SpawnPlayerControllerCommon (ENetRole InRemoteRole, FVector const & SpawnLocation, FRotator const & SpawnRotation, TSubclassOf< APlayerController > InPlayerControllerClass) protected virtual
Does the work of spawning a player controller of the given class at the given transform.
References Category, FVector, SpawnLocation, SpawnPlayerControllerCommon(), SpawnRotation, and UPROPERTY().
Referenced by SpawnPlayerControllerCommon().
SpawnPlayerFromSimulate()
virtual bool AGameModeBase::SpawnPlayerFromSimulate (const FVector & NewLocation, const FRotator & NewRotation) virtual
Used in the editor to spawn a PIE player after the game has already started.
References FVector, and SpawnPlayerFromSimulate().
Referenced by SpawnPlayerFromSimulate().
StartToLeaveMap()
virtual void AGameModeBase::StartToLeaveMap () private virtual
Start the transition out of the current map.
Called at start of seamless travel, or right before map change for hard travel.
SwapPlayerControllers()
virtual void AGameModeBase::SwapPlayerControllers (APlayerController * OldPC, APlayerController * NewPC) private virtual
Used to swap a viewport/connection's PlayerControllers when seamless traveling and the new GameMode's controller class is different than the previous includes network handling.
Parameters
OldPC - the old PC that should be discarded
NewPC - the new PC that should be used for the player
References NewPC.
UE_DEPRECATED() [1/3]
AGameModeBase::UE_DEPRECATED (4. 20, "SpawnPlayerController with Location and Rotation is deprecated, call or override the version that takes an Option string instead")
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
AGameModeBase::UE_DEPRECATED (4. 20, "SpawnReplayPlayerController is deprecated, replay controller spawning is handled inside the new version of the SpawnPlayerController function")
References FVector, SpawnLocation, SpawnRotation, and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
AGameModeBase::UE_DEPRECATED (5. 6, "This functionality has been moved into OnPostLogin. You cannot call that function directly, it is executed at the end of PostLogin.") private
Called as part of the PostLogin process.
This is the last step before we spawn a new player.
References NewPlayer.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UFUNCTION() [1/29]
AGameModeBase::UFUNCTION ()
Return the 'best' player start for this player to spawn from Default implementation looks for a random unoccupied spot.
Parameters
Player is the controller for whom we are choosing a playerstart
Returns
AActor chosen as player start (usually a PlayerStart)
References Category, Game, and UFUNCTION().
UFUNCTION() [2/29]
AGameModeBase::UFUNCTION ()
Return the specific player start actor that should be used for the next spawn This will either use a previously saved startactor, or calls ChoosePlayerStart.
Parameters
Player The AController for whom we are choosing a Player Start
IncomingName Specifies the tag of a Player Start to use
Returns
Actor chosen as player start (usually a PlayerStart)
References Category, Game, and UFUNCTION().
UFUNCTION() [3/29]
AGameModeBase::UFUNCTION ()
Called during RestartPlayer to actually spawn the player's pawn, when using a transform.
Parameters
NewPlayer - Controller for whom this pawn is spawned
SpawnTransform - Transform at which to spawn pawn
Returns
a pawn of the default pawn class
References Category, Game, NewPlayer, SpawnTransform, and UFUNCTION().
UFUNCTION() [4/29]
AGameModeBase::UFUNCTION ()
Called during RestartPlayer to actually spawn the player's pawn, when using a start spot.
Parameters
NewPlayer - Controller for whom this pawn is spawned
StartSpot - Actor at which to spawn pawn
Returns
a pawn of the default pawn class
References Category, Game, NewPlayer, StartSpot, and UFUNCTION().
UFUNCTION() [5/29]
AGameModeBase::UFUNCTION ()
Return whether Viewer is allowed to spectate from the point of view of ViewTarget.
References Category, Game, and UFUNCTION().
UFUNCTION() [6/29]
AGameModeBase::UFUNCTION () const
Returns true if NewPlayerController may only join the server as a spectator.
References Category, Game, and UFUNCTION().
UFUNCTION() [7/29]
AGameModeBase::UFUNCTION ()
Returns true if it's valid to call RestartPlayer.
By default will call Player->CanRestartPlayer
References Category, Game, and UFUNCTION().
UFUNCTION() [8/29]
AGameModeBase::UFUNCTION () private
Overridable function to determine whether an Actor should have Reset called when the game has Reset called on it.
Default implementation returns true
Parameters
ActorToReset The actor to make a determination for
Returns
true if ActorToReset should have Reset() called on it while restarting the game, false if the GameMode will manually reset it or if the actor does not need to be reset
References Category, and Game.
UFUNCTION() [9/29]
AGameModeBase::UFUNCTION () private
Returns default pawn class for given controller.
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [10/29]
AGameModeBase::UFUNCTION () const private
Returns true if the match can be considered ended.
References Category, and Game.
UFUNCTION() [11/29]
AGameModeBase::UFUNCTION () const private
Returns true if the match start callbacks have been called.
References Category, and Game.
UFUNCTION() [12/29]
AGameModeBase::UFUNCTION () private
Returns number of active human players, excluding spectators.
References Category, and Game.
UFUNCTION() [13/29]
AGameModeBase::UFUNCTION () private
Returns number of human players currently spectating.
References Category, and Game.
UFUNCTION() [14/29]
AGameModeBase::UFUNCTION ()
Sets the name for a controller.
Parameters
Controller The controller of the player to change the name of
NewName The name to set the player to
bNameChange Whether the name is changing or if this is the first time it has been set
References Category, Game, and UFUNCTION().
UFUNCTION() [15/29]
AGameModeBase::UFUNCTION () private
Overridable function called when resetting level.
This is used to reset the game state while staying in the same map Default implementation calls Reset() on all actors except GameMode and Controllers
References Category, and Game.
UFUNCTION() [16/29]
AGameModeBase::UFUNCTION ()
Tries to spawn the player's pawn, at the location returned by FindPlayerStart.
References Category, Game, NewPlayer, and UFUNCTION().
UFUNCTION() [17/29]
AGameModeBase::UFUNCTION ()
Tries to spawn the player's pawn at the specified actor's location.
References Category, Game, and UFUNCTION().
UFUNCTION() [18/29]
AGameModeBase::UFUNCTION ()
Tries to spawn the player's pawn at a specific location.
References Category, Game, and UFUNCTION().
UFUNCTION() [19/29]
AGameModeBase::UFUNCTION () private
Return to main menu, and disconnect any players.
References Category, and Game.
UFUNCTION() [20/29]
AGameModeBase::UFUNCTION () private
Transitions to calls BeginPlay on actors.
References Category, and Game.
UFUNCTION() [21/29]
AGameModeBase::UFUNCTION ()
Signals that a player is ready to enter the game, which may start it up.
References Category, Game, NewPlayer, and UFUNCTION().
UFUNCTION() [22/29]
AGameModeBase::UFUNCTION () protected
Initialize the AHUD object for a player.
Games can override this to do something different
References Category, Game, NewPlayer, and UFUNCTION().
UFUNCTION() [23/29]
AGameModeBase::UFUNCTION ()
Called from RestartPlayerAtPlayerStart, can be used to initialize the start spawn actor.
References Category, Game, and UFUNCTION().
UFUNCTION() [24/29]
AGameModeBase::UFUNCTION ()
Return the specific player start actor that should be used for the next spawn This will either use a previously saved startactor, or calls ChoosePlayerStart.
Parameters
Player The AController for whom we are choosing a Player Start
IncomingName Specifies the tag of a Player Start to use
Returns
Actor chosen as player start (usually a PlayerStart)
References Category, Game, IncomingName, meta, TEXT, and UFUNCTION().
UFUNCTION() [25/29]
AGameModeBase::UFUNCTION ()
Overridable event for GameMode blueprint to respond to a change name call.
Parameters
Controller The controller of the player to change the name of
NewName The name to set the player to
bNameChange Whether the name is changing or if this is the first time it has been set
References bNameChange, Category, Game, meta, NewName, Other, and UFUNCTION().
UFUNCTION() [26/29]
AGameModeBase::UFUNCTION ()
Implementable event when a Controller with a PlayerState leaves the game.
References Category, Game, meta, and UFUNCTION().
UFUNCTION() [27/29]
AGameModeBase::UFUNCTION ()
Implementable event called at the end of RestartPlayer.
References Category, Game, meta, NewPlayer, and UFUNCTION().
UFUNCTION() [28/29]
AGameModeBase::UFUNCTION () protected
Called when a PlayerController is swapped to a new one during seamless travel.
References Category, Game, meta, and UFUNCTION().
UFUNCTION() [29/29]
AGameModeBase::UFUNCTION ()
Notification that a player has successfully logged in, and has been given a player controller.
References Category, Game, meta, NewPlayer, and UFUNCTION().
UpdateGameplayMuteList()
virtual void AGameModeBase::UpdateGameplayMuteList (APlayerController * aPlayer) protected virtual
Used to notify the game type that it is ok to update a player's gameplay specific muting information now.
The playercontroller needs to notify the server when it is possible to do so or the unique net id will be incorrect and the muting not work.
Parameters
aPlayer the playercontroller that is ready for updates
References UpdateGameplayMuteList().
Referenced by UpdateGameplayMuteList().
UpdatePlayerStartSpot()
virtual bool AGameModeBase::UpdatePlayerStartSpot (AController * Player, const FString & Portal, FString & OutErrorMessage) protected virtual
Attempts to initialize the 'StartSpot' of the Player.
Parameters
Player The controller for the player.
OutErrorMessage Any error messages.
Returns
bool true if we updated the start spot, otherwise false.
References UpdatePlayerStartSpot().
Referenced by UpdatePlayerStartSpot().
UPROPERTY() [1/15]
UPROPERTY() uint32 bStartPlayersAsSpectators UPROPERTY() uint32 bPauseable AGameModeBase::UPROPERTY () protected
Whether the game perform map travels using SeamlessTravel() which loads in the background and doesn't disconnect clients.
Whether players should immediately spawn when logging in, or stay as spectators until they manually spawn Whether the game is pauseable. Can be used to request a specific replication system for a GameNetDriver that will replicate this game mode. Leave to Default to use the game engine's preferred system. Useful when migrating from one repsystem to another and a game mode does not fully support both repsystem yet.
References Category, Default, and UPROPERTY().
UPROPERTY() [2/15]
AGameModeBase::UPROPERTY () private
Save options string and parse it when needed.
References Category.
Referenced by SpawnPlayerControllerCommon(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/15]
AGameModeBase::UPROPERTY ()
The default player name assigned to players that join with no name specified.
References Category, Game, and UPROPERTY().
UPROPERTY() [4/15]
AGameModeBase::UPROPERTY () private
Game Session handles login approval, arbitration, online game interface.
References GameSession, and Transient.
UPROPERTY() [5/15]
AGameModeBase::UPROPERTY () private
GameState is used to replicate game state relevant properties to all clients.
References Transient.
UPROPERTY() [6/15]
AGameModeBase::UPROPERTY () private
References Transient.
UPROPERTY() [7/15]
AGameModeBase::UPROPERTY () private
Class of GameSession, which handles login approval and online game interface.
References Category.
UPROPERTY() [8/15]
AGameModeBase::UPROPERTY () private
Class of GameState associated with this GameMode.
References Category.
UPROPERTY() [9/15]
AGameModeBase::UPROPERTY () private
The default pawn class used by players.
References Category, and UPROPERTY().
UPROPERTY() [10/15]
AGameModeBase::UPROPERTY () private
The class of PlayerController to spawn for players logging in.
References Category.
UPROPERTY() [11/15]
AGameModeBase::UPROPERTY () private
The PlayerController class used when spectating a network replay.
References Category, and UPROPERTY().
UPROPERTY() [12/15]
AGameModeBase::UPROPERTY () private
A PlayerState of this class will be associated with every player to replicate relevant player information to all clients.
References Category.
UPROPERTY() [13/15]
AGameModeBase::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [14/15]
AGameModeBase::UPROPERTY () private
The pawn class used by the PlayerController for players when spectating.
References Category, and UPROPERTY().
UPROPERTY() [15/15]
AGameModeBase::UPROPERTY () private
HUD class this game uses.
References Category, and meta.
Field Documentation
bNameChange
const FString bool AGameModeBase::bNameChange
Definition at line 388 of file GameModeBase.h.
Referenced by UFUNCTION().
IncomingName
const FString & AGameModeBase::IncomingName = TEXT(""))
Definition at line 422 of file GameModeBase.h.
Referenced by UFUNCTION().
NewName
const FString & AGameModeBase::NewName
Definition at line 388 of file GameModeBase.h.
Referenced by UFUNCTION().
NewPC
APlayerController* AGameModeBase::NewPC protected
Definition at line 577 of file GameModeBase.h.
Referenced by SwapPlayerControllers().
NewPlayer
AController* AGameModeBase::NewPlayer
Definition at line 471 of file GameModeBase.h.
Referenced by FailedToRestartPlayer(), FinishRestartPlayer(), Login(), OnPostLogin(), PostLogin(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Pausers
TArray<FCanUnpause> AGameModeBase::Pausers protected
The list of delegates to check before unpausing a game.
Definition at line 605 of file GameModeBase.h.
SpawnLocation
FVector const & AGameModeBase::SpawnLocation
Definition at line 360 of file GameModeBase.h.
Referenced by SpawnPlayerControllerCommon(), and UE_DEPRECATED().
SpawnRotation
FVector const FRotator const & AGameModeBase::SpawnRotation
Definition at line 360 of file GameModeBase.h.
Referenced by SpawnPlayerControllerCommon(), and UE_DEPRECATED().
SpawnTransform
const FTransform & AGameModeBase::SpawnTransform
Definition at line 449 of file GameModeBase.h.
Referenced by UFUNCTION().
StartSpot
AActor * AGameModeBase::StartSpot
Definition at line 445 of file GameModeBase.h.
Referenced by UFUNCTION().
ViewTarget
APlayerState* AGameModeBase::ViewTarget
Definition at line 375 of file GameModeBase.h.
The documentation for this class was generated from the following file:
GameModeBase.h