Unreal Engine 5.6 C++ API: UE::Geometry::FVerticalCylinderGeneratorBase Class Reference
UE::Geometry::FVerticalCylinderGeneratorBase Class Reference
Generate a cylinder with optional end caps.
#include "SweepGenerator.h"
Public Member Functions
bool GenerateVerticalCircleSweep (const TArrayView< float > &Radii, const TArrayView< float > &Heights, const TArrayView< int > &SharpNormalsAlongLength)
Public Member Functions inherited from UE::Geometry::FSweepGeneratorBase
virtual ~FSweepGeneratorBase ()
Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
virtual ~FMeshShapeGenerator ()
int AppendNormal (const FVector3f &Normal, int ParentVertex)
int AppendTriangle (int A, int B, int C)
int AppendUV (const FVector2f &UV, int ParentVertex)
int AppendVertex (const FVector3d &Position)
Append a new vertex at the given Position.
void ExtendBufferSizes (int AddVertices, int AddTriangles, int AddUVs, int AddNormals)
Extends the various internal buffers to the correct sizes for the given additional element counts.
virtual FMeshShapeGenerator & Generate ()=0
Subclasses implement this to generate mesh.
bool HasAttributes () const
void Reset ()
clear arrays so that Generate() can be run again
void ResetAttributes (bool bResetPolygonIDs=false)
void SetBufferSizes (int NumVertices, int NumTriangles, int NumUVs, int NumNormals)
Set the various internal buffers to the correct sizes for the given element counts.
void SetNormal (int Index, const FVector3f &Normal, int ParentVertex)
Set Normal at Index to given value with given ParentVertex.
void SetTriangle (int Index, const FIndex3i &Tri)
void SetTriangle (int Index, int A, int B, int C)
void SetTriangle (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleNormals (int Index, const FIndex3i &Tri)
void SetTriangleNormals (int Index, int A, int B, int C)
void SetTriangleNormals (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTrianglePolygon (int Index, int PolygonID)
void SetTriangleUVs (int Index, const FIndex3i &Tri)
void SetTriangleUVs (int Index, int A, int B, int C)
void SetTriangleUVs (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleWithMatchedUVNormal (int Index, int A, int B, int C)
Set triangle and UVs and normals with matching indices Convenience function for shapes with no uv or normal seams.
void SetUV (int Index, const FVector2f &UV, int ParentVertex)
Set UV at Index to given value with given ParentVertex.
void SetVertex (int Index, const FVector3d &Position)
Set vertex at Index to given Position.
Static Public Member Functions
static float ComputeSegLengths (const TArrayView< float > &Radii, const TArrayView< float > &Heights, TArray< float > &AlongPercents)
Static Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
static FVector2d BilinearInterp (const FVector2d &v00, const FVector2d &v10, const FVector2d &v11, const FVector2d &v01, double tx, double ty)
static FVector2f BilinearInterp (const FVector2f &v00, const FVector2f &v10, const FVector2f &v11, const FVector2f &v01, float tx, float ty)
static FVector3d BilinearInterp (const FVector3d &v00, const FVector3d &v10, const FVector3d &v11, const FVector3d &v01, double tx, double ty)
static FVector3i LinearInterp (const FVector3i &a, const FVector3i &b, double t)
Data Fields
int AngleSamples = 16
bool bCapped = false
bool bUVScaleMatchSidesAndCaps = true
ECapType CapType = ECapType::FlatMidpointFan
Data Fields inherited from UE::Geometry::FSweepGeneratorBase
bool bPolygroupPerQuad = false
If true, each quad gets a separate polygroup.
bool bProfileCurveIsClosed = true
If true, the last point of the profile curve is considered to be connected to the first.
Data Fields inherited from UE::Geometry::FMeshShapeGenerator
bool bReverseOrientation = false
If true, reverse orientation of created mesh.
TArray< int > NormalParentVertex
Parent vertex index for each Normal.
TArray< FVector3f > Normals
Array of Normals.
TArray< FIndex3i > TriangleNormals
Array of triangle corner Normals, stored as tuples of indices into Normals array.
TArray< int > TrianglePolygonIDs
Array of per-triangle integer polygon IDs.
TArray< FIndex3i > Triangles
Array of triangle corner positions, stored as tuples of indices into Vertices array.
TArray< FIndex3i > TriangleUVs
Array of triangle corner UVs, stored as tuples of indices into UVs array.
TArray< int > UVParentVertex
Parent vertex index for each UV.
TArray< FVector2f > UVs
Array of UV positions.
TArray< FVector3d > Vertices
Array of vertex positions.
Additional Inherited Members
Protected Member Functions inherited from UE::Geometry::FSweepGeneratorBase
void ConstructMeshTopology (const FPolygon2d &CrossSection, const TArrayView< const int32 > &UVSections, const TArrayView< const int32 > &NormalSections, const TArrayView< const int32 > &SharpNormalsAlongLength, bool bEvenlySpaceUVs, const TArrayView< const FVector3d > &Path, int32 NumCrossSections, bool bLoop, const ECapType Caps[2], FVector2f SectionsUVScale, FVector2f CapUVScale, FVector2f CapUVOffset, const TArrayView< const float > &CustomCrossSectionTexCoord={}, const TArrayView< const float > &CustomPathTexCoord={})
Shared logic for creating vertex buffers and triangulations across all sweep primitives Note: Does not set vertex positions or normals; a separate call must do that.
Protected Attributes inherited from UE::Geometry::FSweepGeneratorBase
int32 CapNormalStart [2]
int32 CapPolygonStart [2]
int32 CapTriangleStart [2]
int32 CapUVStart [2]
int32 CapVertStart [2]
Detailed Description
Generate a cylinder with optional end caps.
Definition at line 440 of file SweepGenerator.h.
Member Function Documentation
ComputeSegLengths()
float UE::Geometry::FVerticalCylinderGeneratorBase::ComputeSegLengths (const TArrayView< float > & Radii, const TArrayView< float > & Heights, TArray< float > & AlongPercents) inline static
Definition at line 448 of file SweepGenerator.h.
References Distance, float, TArrayView< InElementType, InSizeType >::Num(), and TArray< InElementType, InAllocatorType >::SetNum().
Referenced by UE::Geometry::FArrowGenerator::DistributeAdditionalLengthSamples(), and GenerateVerticalCircleSweep().
GenerateVerticalCircleSweep()
bool UE::Geometry::FVerticalCylinderGeneratorBase::GenerateVerticalCircleSweep (const TArrayView< float > & Radii, const TArrayView< float > & Heights, const TArrayView< int > & SharpNormalsAlongLength) inline
Definition at line 467 of file SweepGenerator.h.
References TMathUtil< float >::Abs(), AngleSamples, bCapped, bUVScaleMatchSidesAndCaps, UE::Geometry::FSweepGeneratorBase::CapNormalStart, CapType, UE::Geometry::FSweepGeneratorBase::CapUVStart, UE::Geometry::FSweepGeneratorBase::CapVertStart, ComputeSegLengths(), UE::Geometry::FSweepGeneratorBase::ConstructMeshTopology(), ensure, UE::Geometry::FlatMidpointFan, TArray< InElementType, InAllocatorType >::Last(), UE::Geometry::TPolygon2< double >::MakeCircle(), TMathUtil< float >::Max(), TMathUtil< float >::Max3(), UE::Geometry::None, Normalized, UE::Geometry::FMeshShapeGenerator::Normals, TArrayView< InElementType, InSizeType >::Num(), UE::Geometry::PerpCW(), TArray< InElementType, InAllocatorType >::SetNum(), TMathUtilConstants< float >::TwoPi, UE::Math::TVector< double >::UnitZ(), UE::Geometry::FMeshShapeGenerator::UVs, UE::Geometry::FMeshShapeGenerator::Vertices, X, and Y.
Referenced by UE::Geometry::FArrowGenerator::Generate(), and UE::Geometry::FCylinderGenerator::Generate().
Field Documentation
AngleSamples
int UE::Geometry::FVerticalCylinderGeneratorBase::AngleSamples = 16
Definition at line 443 of file SweepGenerator.h.
Referenced by UE::Geometry::FCylinderGenerator::Generate(), and GenerateVerticalCircleSweep().
bCapped
bool UE::Geometry::FVerticalCylinderGeneratorBase::bCapped = false
Definition at line 444 of file SweepGenerator.h.
Referenced by UE::Geometry::FCylinderGenerator::Generate(), and GenerateVerticalCircleSweep().
bUVScaleMatchSidesAndCaps
bool UE::Geometry::FVerticalCylinderGeneratorBase::bUVScaleMatchSidesAndCaps = true
Definition at line 445 of file SweepGenerator.h.
Referenced by GenerateVerticalCircleSweep().
CapType
ECapType UE::Geometry::FVerticalCylinderGeneratorBase::CapType = ECapType::FlatMidpointFan
Definition at line 446 of file SweepGenerator.h.
Referenced by GenerateVerticalCircleSweep().
The documentation for this class was generated from the following file:
SweepGenerator.h