Unreal Engine 5.6 C++ API: UE::StateTree::TTasksCompletionStatus< T > Struct Template Reference
UE::StateTree::TTasksCompletionStatus< T > Struct Template Reference
#include "StateTreeTasksStatus.h"
Public Member Functions
TTasksCompletionStatus (TNotNull< T * > InFirstCompletionBits, TNotNull< T * > InSecondCompletionBits, T InCompletionMask, int32 InBitIndex, EStateTreeTaskCompletionType InTaskControl)
ETaskCompletionStatus GetCompletionStatus () const
The completion status of all tasks or any task, in priority order.
ETaskCompletionStatus GetStatus (int32 StateTaskIndex) const
bool HasAllCompleted () const
bool HasAnyCompleted () const
bool HasAnyFailed () const
bool HasFailed (int32 StateTaskIndex) const
bool IsCompleted () const
bool IsConsideredForCompletion (int32 StateTaskIndex) const
bool IsRunning (int32 StateTaskIndex) const
STATETREEMODULE_API void ResetStatus (int32 NumberOfTasksInTheCompletionMask)
Set the status of all tasks to running.
void SetCompletionStatus (ETaskCompletionStatus NewStatus)
Set the status of all tasks in the completion mask.
void SetStatus (int32 StateTaskIndex, ETaskCompletionStatus NewStatus)
Set the status of a task.
ETaskCompletionStatus SetStatusWithPriority (int32 StateTaskIndex, ETaskCompletionStatus NewStatus)
Set the status of a task respecting the previous status value.
Static Public Attributes
static constexpr int32 MaxNumTasks = sizeof(T)*8
Private Member Functions
uint8 GetStatusInternal (int32 Index) const
void SetStatusInternal (int32 Index, ETaskCompletionStatus NewStatus)
Private Attributes
int32 BitIndex
The offset, in bits, of the first task inside the mask.
T CompletionMask
The mask that represents each task considered by the state/frame for completion.
T * FirstCompletionBits
The first buffer.
T * SecondCompletionBits
The second buffer.
EStateTreeTaskCompletionType TaskControl
How the mask is tested to complete the state/frame.
Detailed Description
template<typename T>
struct UE::StateTree::TTasksCompletionStatus< T >
Definition at line 44 of file StateTreeTasksStatus.h.
Constructor & Destructor Documentation
TTasksCompletionStatus()
template<typename T> UE::StateTree::TTasksCompletionStatus< T >::TTasksCompletionStatus (TNotNull< T * > InFirstCompletionBits, TNotNull< T * > InSecondCompletionBits, T InCompletionMask, int32 InBitIndex, EStateTreeTaskCompletionType InTaskControl) inline
Definition at line 50 of file StateTreeTasksStatus.h.
Member Function Documentation
GetCompletionStatus()
template<typename T> ETaskCompletionStatus UE::StateTree::TTasksCompletionStatus< T >::GetCompletionStatus () const inline nodiscard
The completion status of all tasks or any task, in priority order.
If any of the tasks fail, the completion status will be Failed regardless of any other tasks. In case the type is Any, it will return Succeeded before Stopped and before Running.
Returns
the completion status of all tasks.
Definition at line 76 of file StateTreeTasksStatus.h.
GetStatus()
template<typename T> ETaskCompletionStatus UE::StateTree::TTasksCompletionStatus< T >::GetStatus (int32 StateTaskIndex) const inline nodiscard
Parameters
StateTaskIndex The index of the task in the state.
Returns
the status of a task.
Definition at line 63 of file StateTreeTasksStatus.h.
GetStatusInternal()
template<typename T> uint8 UE::StateTree::TTasksCompletionStatus< T >::GetStatusInternal (int32 Index) const inline private
Definition at line 218 of file StateTreeTasksStatus.h.
Referenced by UE::StateTree::TTasksCompletionStatus< uint32 >::GetStatus(), and UE::StateTree::TTasksCompletionStatus< uint32 >::SetStatusWithPriority().
HasAllCompleted()
template<typename T> bool UE::StateTree::TTasksCompletionStatus< T >::HasAllCompleted () const inline nodiscard
Returns
true when there's any failure or all tasks succeeded or stopped.
Definition at line 144 of file StateTreeTasksStatus.h.
Referenced by UE::StateTree::TTasksCompletionStatus< uint32 >::IsCompleted().
HasAnyCompleted()
template<typename T> bool UE::StateTree::TTasksCompletionStatus< T >::HasAnyCompleted () const inline nodiscard
Returns
true when there's any failure or any tasks succeeded or stopped.
Definition at line 152 of file StateTreeTasksStatus.h.
Referenced by UE::StateTree::TTasksCompletionStatus< uint32 >::IsCompleted().
HasAnyFailed()
template<typename T> bool UE::StateTree::TTasksCompletionStatus< T >::HasAnyFailed () const inline nodiscard
Returns
true when there's any failure.
Definition at line 158 of file StateTreeTasksStatus.h.
HasFailed()
template<typename T> bool UE::StateTree::TTasksCompletionStatus< T >::HasFailed (int32 StateTaskIndex) const inline nodiscard
Parameters
StateTaskIndex The index of the task in the state.
Returns
true when the task status is failed.
Definition at line 135 of file StateTreeTasksStatus.h.
IsCompleted()
template<typename T> bool UE::StateTree::TTasksCompletionStatus< T >::IsCompleted () const inline nodiscard
Returns
true when there's any failure or respect the task control.
Definition at line 164 of file StateTreeTasksStatus.h.
IsConsideredForCompletion()
template<typename T> bool UE::StateTree::TTasksCompletionStatus< T >::IsConsideredForCompletion (int32 StateTaskIndex) const inline nodiscard
Parameters
StateTaskIndex The index of the task in the state.
Returns
true when the task is considered for GetCompletionStatus, HasAllCompleted, HasAnyCompleted, HasAnyFailed, IsCompleted
Definition at line 111 of file StateTreeTasksStatus.h.
IsRunning()
template<typename T> bool UE::StateTree::TTasksCompletionStatus< T >::IsRunning (int32 StateTaskIndex) const inline nodiscard
Parameters
StateTaskIndex The index of the task in the state.
Returns
true when the task status is running.
Definition at line 123 of file StateTreeTasksStatus.h.
ResetStatus()
template<typename T> STATETREEMODULE_API void UE::StateTree::TTasksCompletionStatus< T >::ResetStatus (int32 NumberOfTasksInTheCompletionMask)
Set the status of all tasks to running.
SetCompletionStatus()
template<typename T> void UE::StateTree::TTasksCompletionStatus< T >::SetCompletionStatus (ETaskCompletionStatus NewStatus) inline
Set the status of all tasks in the completion mask.
Definition at line 199 of file StateTreeTasksStatus.h.
SetStatus()
template<typename T> void UE::StateTree::TTasksCompletionStatus< T >::SetStatus (int32 StateTaskIndex, ETaskCompletionStatus NewStatus) inline
Set the status of a task.
Parameters
StateTaskIndex The index of the task in the state.
Definition at line 173 of file StateTreeTasksStatus.h.
SetStatusInternal()
template<typename T> void UE::StateTree::TTasksCompletionStatus< T >::SetStatusInternal (int32 Index, ETaskCompletionStatus NewStatus) inline private
Definition at line 226 of file StateTreeTasksStatus.h.
Referenced by UE::StateTree::TTasksCompletionStatus< uint32 >::SetStatus(), and UE::StateTree::TTasksCompletionStatus< uint32 >::SetStatusWithPriority().
SetStatusWithPriority()
template<typename T> ETaskCompletionStatus UE::StateTree::TTasksCompletionStatus< T >::SetStatusWithPriority (int32 StateTaskIndex, ETaskCompletionStatus NewStatus) inline
Set the status of a task respecting the previous status value.
The priority is Failed, Succeeded, Stopped, Running.
Parameters
StateTaskIndex The index of the task in the state.
Definition at line 185 of file StateTreeTasksStatus.h.
Field Documentation
BitIndex
template<typename T> int32 UE::StateTree::TTasksCompletionStatus< T >::BitIndex private
The offset, in bits, of the first task inside the mask.
Definition at line 243 of file StateTreeTasksStatus.h.
CompletionMask
template<typename T> T UE::StateTree::TTasksCompletionStatus< T >::CompletionMask private
The mask that represents each task considered by the state/frame for completion.
Definition at line 241 of file StateTreeTasksStatus.h.
FirstCompletionBits
template<typename T> T* UE::StateTree::TTasksCompletionStatus< T >::FirstCompletionBits private
The first buffer.
00 is Running and 01 is Stopped.
Definition at line 237 of file StateTreeTasksStatus.h.
MaxNumTasks
template<typename T> int32 UE::StateTree::TTasksCompletionStatus< T >::MaxNumTasks = sizeof(T)*8 static constexpr
Definition at line 47 of file StateTreeTasksStatus.h.
SecondCompletionBits
template<typename T> T* UE::StateTree::TTasksCompletionStatus< T >::SecondCompletionBits private
The second buffer.
10 is Succeeded and 11 is Failed.
Definition at line 239 of file StateTreeTasksStatus.h.
TaskControl
template<typename T> EStateTreeTaskCompletionType UE::StateTree::TTasksCompletionStatus< T >::TaskControl private
How the mask is tested to complete the state/frame.
Definition at line 245 of file StateTreeTasksStatus.h.
The documentation for this struct was generated from the following file:
StateTreeTasksStatus.h