Unreal Engine 5.6 C++ API: Metasound::TReceiver< TDataType > Class Template Reference
Metasound::TReceiver< TDataType > Class Template Reference
#include "MetasoundRouter.h"
Public Member Functions
TReceiver (const FReceiverInitParams &InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel)
bool CanPop () const
bool Pop (TDataType &OutValue)
void PushPayload (int64 InPayloadID, const TDataType &InDataPayload)
Public Member Functions inherited from Metasound::IReceiver
IReceiver (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType)
virtual METASOUNDFRONTEND_API ~IReceiver ()
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Static Public Member Functions
static FName GetDataTypeName ()
Private Attributes
int64 LastPayloadID = INDEX_NONE
FOperatorSettings OperatorSettings
TUniquePtr< TDataType > Payload
Additional Inherited Members
Protected Attributes inherited from Metasound::IReceiver
TSharedPtr< IDataChannel, ESPMode::ThreadSafe > DataChannel
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
template<typename TDataType>
class Metasound::TReceiver< TDataType >
Definition at line 524 of file MetasoundRouter.h.
Constructor & Destructor Documentation
TReceiver()
template<typename TDataType> Metasound::TReceiver< TDataType >::TReceiver (const FReceiverInitParams & InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel) inline
Definition at line 559 of file MetasoundRouter.h.
References Metasound::IReceiver::IReceiver(), GetDataTypeName(), and OperatorSettings.
Member Function Documentation
CanPop()
template<typename TDataType> bool Metasound::TReceiver< TDataType >::CanPop () const inline
Definition at line 529 of file MetasoundRouter.h.
References Metasound::IReceiver::DataChannel, and LastPayloadID.
Referenced by Metasound::Frontend::FMetasoundAnalyzerView::TryGetOutputData().
GetDataTypeName()
template<typename TDataType> FName Metasound::TReceiver< TDataType >::GetDataTypeName () inline static
Definition at line 554 of file MetasoundRouter.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by TReceiver().
Pop()
template<typename TDataType> bool Metasound::TReceiver< TDataType >::Pop (TDataType & OutValue) inline
Definition at line 545 of file MetasoundRouter.h.
References check, Metasound::IReceiver::DataChannel, and Payload.
Referenced by Metasound::Frontend::FMetasoundAnalyzerView::TryGetOutputData().
PushPayload()
template<typename TDataType> void Metasound::TReceiver< TDataType >::PushPayload (int64 InPayloadID, const TDataType & InDataPayload) inline
Definition at line 565 of file MetasoundRouter.h.
References LastPayloadID, MakeUnique(), and Payload.
Referenced by Metasound::TCopyableDataChannel< TDataType >::PopOpaque().
Field Documentation
LastPayloadID
template<typename TDataType> int64 Metasound::TReceiver< TDataType >::LastPayloadID = INDEX_NONE private
Definition at line 585 of file MetasoundRouter.h.
Referenced by CanPop(), and PushPayload().
OperatorSettings
template<typename TDataType> FOperatorSettings Metasound::TReceiver< TDataType >::OperatorSettings private
Definition at line 587 of file MetasoundRouter.h.
Referenced by TReceiver().
Payload
template<typename TDataType> TUniquePtr<TDataType> Metasound::TReceiver< TDataType >::Payload private
Definition at line 586 of file MetasoundRouter.h.
Referenced by Pop(), and PushPayload().
The documentation for this class was generated from the following file:
MetasoundRouter.h