Unreal Engine 5.6 C++ API: UE::Tasks::TTask< void > Class Reference
UE::Tasks::TTask< void > Class Reference
#include "Task.h"
Public Member Functions
TTask ()=default
void GetResult ()
Public Member Functions inherited from UE::Tasks::Private::FTaskHandle
FTaskHandle ()=default
EExtendedTaskPriority GetExtendedPriority () const
ETaskPriority GetPriority () const
bool IsAwaitable () const
bool IsCompleted () const
bool IsValid () const
PrerequisitesCollectionType void Launch (const TCHAR *DebugName, TaskBodyType &&TaskBody, PrerequisitesCollectionType &&Prerequisites, ETaskPriority Priority=ETaskPriority::Normal, EExtendedTaskPriority ExtendedPriority=EExtendedTaskPriority::None, ETaskFlags Flags=ETaskFlags::None)
bool operator!= (const FTaskHandle &Other) const
bool operator== (const FTaskHandle &Other) const
UE_DEPRECATED (5.5, "Use Wait instead.") bool BusyWait(FTimespan Timeout
bool Wait () const
bool Wait (FTimespan Timeout) const
Private Member Functions
TTask (Private::FTaskBase *Other)
Private Attributes
friend FPipe
Additional Inherited Members
Public Types inherited from UE::Tasks::Private::FTaskHandle
using FTaskHandleId = void
Protected Member Functions inherited from UE::Tasks::Private::FTaskHandle
FTaskHandle (FTaskBase *Other)
Protected Attributes inherited from UE::Tasks::Private::FTaskHandle
TRefCountPtr< FTaskBase > Pimpl
Detailed Description
Definition at line 243 of file Tasks/Task.h.
Constructor & Destructor Documentation
TTask() [1/2]
UE::Tasks::TTask< void >::TTask () default
TTask() [2/2]
UE::Tasks::TTask< void >::TTask (Private::FTaskBase * Other) inline explicit private
Definition at line 258 of file Tasks/Task.h.
References UE::Tasks::Private::FTaskHandle::FTaskHandle(), and Other.
Member Function Documentation
GetResult()
void UE::Tasks::TTask< void >::GetResult () inline
Definition at line 248 of file Tasks/Task.h.
References check, UE::Tasks::Private::FTaskHandle::IsValid(), and UE::Tasks::Private::FTaskHandle::Wait().
Field Documentation
FPipe
friend UE::Tasks::TTask< void >::FPipe private
Definition at line 255 of file Tasks/Task.h.
The documentation for this class was generated from the following file:
Tasks/Task.h