Unreal Engine 5.6 C++ API: AxisDisplayInfo Namespace Reference
AxisDisplayInfo Namespace Reference
Functions
FLinearColor GetAxisColor (EAxisList::Type Axis)
Gets the color to use for the given axis.
EAxisList::Type GetAxisDisplayCoordinateSystem ()
Gets the axis display coordinate system to use.
FText GetAxisDisplayName (EAxisList::Type Axis)
Gets the display name to use for the given axis.
FText GetAxisDisplayNameShort (EAxisList::Type Axis)
Gets the short display name to use for the given axis.
FText GetAxisToolTip (EAxisList::Type Axis)
FText GetRotationAxisName (EAxisList::Type Axis)
FText GetRotationAxisNameShort (EAxisList::Type Axis)
FText GetRotationAxisToolTip (EAxisList::Type Axis)
FIntVector4 GetTransformAxisSwizzle ()
Default swizzle for displaying axis in transform displays Swizzle maps from the default X, Y, Z, W positions to new position { 1, 2, 0, 3 } would map position 0 to fetch Y, position 1 to fetch Z, etc.
bool UseForwardRightUpDisplayNames ()
Gets whether or not the engine uses forward/right/up nomenclature for display names.
Function Documentation
GetAxisColor()
FLinearColor AxisDisplayInfo::GetAxisColor (EAxisList::Type Axis)
Gets the color to use for the given axis.
The return value may be driven by the config system and therefore it should not be cached until the editor has finished loading.
Parameters
Axis The axis whose color you are requesting
Returns
The color corresponding to the given axis
References Axis.
Referenced by SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::FVectorXArguments(), SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorYArguments< ArgumentType >::FVectorYArguments(), SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::FVectorZArguments(), SNumericRotatorInputBox< float >::ConstructPitch(), SNumericRotatorInputBox< float >::ConstructRoll(), and SNumericRotatorInputBox< float >::ConstructYaw().
GetAxisDisplayCoordinateSystem()
EAxisList::Type AxisDisplayInfo::GetAxisDisplayCoordinateSystem ()
Gets the axis display coordinate system to use.
The return value may be driven by the config system and therefore it should not be cached until the editor has finished loading.
Returns
The display coordinate system, either EAxisList::XYZ or EAxisList::LeftUpForward
GetAxisDisplayName()
FText AxisDisplayInfo::GetAxisDisplayName (EAxisList::Type Axis)
Gets the display name to use for the given axis.
The return value may be driven by the config system and therefore it should not be cached until the editor has finished loading.
Parameters
Axis The axis whose display name you are requesting
Returns
The display name corresponding to the given axis
References Axis.
Referenced by SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::FVectorXArguments(), SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorYArguments< ArgumentType >::FVectorYArguments(), and SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::FVectorZArguments().
GetAxisDisplayNameShort()
FText AxisDisplayInfo::GetAxisDisplayNameShort (EAxisList::Type Axis)
Gets the short display name to use for the given axis.
The return value may be driven by the config system and therefore it should not be cached until the editor has finished loading.
Parameters
Axis The axis whose short display name you are requesting
Returns
The short display name corresponding to the given axis
References Axis.
GetAxisToolTip()
FText AxisDisplayInfo::GetAxisToolTip (EAxisList::Type Axis)
References Axis.
GetRotationAxisName()
FText AxisDisplayInfo::GetRotationAxisName (EAxisList::Type Axis)
References Axis.
GetRotationAxisNameShort()
FText AxisDisplayInfo::GetRotationAxisNameShort (EAxisList::Type Axis)
References Axis.
GetRotationAxisToolTip()
FText AxisDisplayInfo::GetRotationAxisToolTip (EAxisList::Type Axis)
References Axis.
GetTransformAxisSwizzle()
FIntVector4 AxisDisplayInfo::GetTransformAxisSwizzle ()
Default swizzle for displaying axis in transform displays Swizzle maps from the default X, Y, Z, W positions to new position { 1, 2, 0, 3 } would map position 0 to fetch Y, position 1 to fetch Z, etc.
UseForwardRightUpDisplayNames()
bool AxisDisplayInfo::UseForwardRightUpDisplayNames ()
Gets whether or not the engine uses forward/right/up nomenclature for display names.
The return value may be driven by the config system and therefore it should not be cached until the editor has finished loading.
Referenced by SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorXArguments< ArgumentType >::FVectorXArguments(), SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorYArguments< ArgumentType >::FVectorYArguments(), and SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::FVectorZArguments().