Unreal Engine 5.6 C++ API: Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType > Class Template Reference
Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType > Class Template Reference
#include "MetasoundInputNode.h"
Public Types
using FDataWriteReference = TDataWriteReference<DataType>
using FDataWriteReferenceFactory = TDataWriteReferenceLiteralFactory<DataType>
Public Types inherited from Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >
using FDataWriteReference = TDataWriteReference<DataType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TResetablePostExecutableInputOperator (const FVertexName &InDataReferenceName, const FOperatorSettings &InSettings, const FInputVertexInterfaceData &InData)
TResetablePostExecutableInputOperator (const FVertexName &InDataReferenceName, const FOperatorSettings &InSettings, const FLiteral &InLiteral)
virtual IOperator::FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >
TPostExecutableInputOperator (const FVertexName &InDataReferenceName, TDataWriteReference< DataType > InValue)
virtual void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Private Member Functions
static void Reset (IOperator *InOperator, const IOperator::FResetParams &InParams)
Private Attributes
FLiteral Literal
Additional Inherited Members
Static Protected Member Functions inherited from Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >
static void NoOpReset (IOperator *InOperator, const IOperator::FResetParams &InParams)
static void PostExecute (IOperator *InOperator)
Protected Attributes inherited from Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >
FAnyDataReference DataRef
FVertexName DataReferenceName
Detailed Description
template<typename DataType>
class Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >
Definition at line 172 of file MetasoundInputNode.h.
Member Typedef Documentation
FDataWriteReference
template<typename DataType> using Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::FDataWriteReference = TDataWriteReference<DataType>
Definition at line 175 of file MetasoundInputNode.h.
FDataWriteReferenceFactory
template<typename DataType> using Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::FDataWriteReferenceFactory = TDataWriteReferenceLiteralFactory<DataType>
Definition at line 176 of file MetasoundInputNode.h.
Constructor & Destructor Documentation
TResetablePostExecutableInputOperator() [1/2]
template<typename DataType> Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::TResetablePostExecutableInputOperator (const FVertexName & InDataReferenceName, const FOperatorSettings & InSettings, const FLiteral & InLiteral) inline
Definition at line 179 of file MetasoundInputNode.h.
References Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::TPostExecutableInputOperator(), and Literal.
Referenced by Reset().
TResetablePostExecutableInputOperator() [2/2]
template<typename DataType> Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::TResetablePostExecutableInputOperator (const FVertexName & InDataReferenceName, const FOperatorSettings & InSettings, const FInputVertexInterfaceData & InData) inline
Definition at line 185 of file MetasoundInputNode.h.
References Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::TPostExecutableInputOperator(), checkf, Literal, TEXT, and FName::ToString().
Member Function Documentation
GetResetFunction()
template<typename DataType> virtual IOperator::FResetFunction Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::GetResetFunction () inline override virtual
Return the reset function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be reset.
Reimplemented from Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >.
Definition at line 192 of file MetasoundInputNode.h.
References Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::DataRef, Reset(), and Metasound::Write.
Reset()
template<typename DataType> void Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::Reset (IOperator * InOperator, const IOperator::FResetParams & InParams) inline static private
Definition at line 207 of file MetasoundInputNode.h.
References TResetablePostExecutableInputOperator(), check, Metasound::TDataLiteralFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateExplicitArgs(), ensure, Metasound::IOperator::FResetParams::OperatorSettings, and Metasound::Value.
Referenced by GetResetFunction().
Field Documentation
Literal
template<typename DataType> FLiteral Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::Literal private
Definition at line 221 of file MetasoundInputNode.h.
Referenced by TResetablePostExecutableInputOperator(), and TResetablePostExecutableInputOperator().
The documentation for this class was generated from the following file:
MetasoundInputNode.h