Unreal Engine 5.6 C++ API: FSlowTask Struct Reference
FSlowTask Struct Reference
Data type used to store information about a currently running slow task.
#include "SlowTask.h"
Public Member Functions
FSlowTask (float InAmountOfWork, const FText &InDefaultMessage=FText(), bool bInEnabled=true, FFeedbackContext &InContext= *GWarn)
Construct this scope from an amount of work to do, and a message to display.
void Destroy ()
Function that finishes any remaining work and removes itself from the global scope stack.
void EnterProgressFrame (float ExpectedWorkThisFrame=1.f, const FText &Text=FText())
Indicate that we are to enter a frame that will take up the specified amount of work.
void ForceRefresh ()
Whenever we encounter edge condition requiring to force a UI refresh (Like if another popup would show when the slow task finishes and you want it to show 100%)
const FText & GetCurrentMessage () const
Get the frame message or default message if empty.
void Initialize ()
Function that initializes the scope by adding it to its context's stack.
void MakeDialog (bool bShowCancelButton=false, bool bAllowInPIE=false)
Creates a new dialog for this slow task, if there is currently not one open.
void MakeDialogDelayed (float Threshold, bool bShowCancelButton=false, bool bAllowInPIE=false)
Creates a new dialog for this slow task after the given time threshold.
bool ShouldCancel () const
True if the user has requested that the slow task be canceled.
void TickProgress ()
Let the UI refresh but doesn't advance progress.
Static Public Member Functions
static bool ShouldCreateThrottledSlowTask ()
True if a slow task should be created.
Data Fields
float CompletedWork
The amount of work we have already completed in this scope.
float CurrentFrameScope
The amount of work the current frame is responsible for.
FText DefaultMessage
Default message to display to the user when not overridden by a frame.
FText FrameMessage
Message pertaining to the current frame's work.
TOptional< float > OpenDialogThreshold
Threshold before dialog is opened.
double StartTime
The time that this scope was created.
float TotalAmountOfWork
The amount of work to do in this scope.
ESlowTaskVisibility Visibility
The visibility of this slow task.
Private Member Functions
FSlowTask (const FSlowTask &)
Prevent copying.
bool MakeDialogIfNeeded ()
Handle dialog and delayed dialog creation logic.
void MakeRecursiveDialogIfNeeded ()
Call MakeDialogIfNeeded on all scopes recursively to give them a chance to create a delayed dialog in the hierarchy.
Static Private Member Functions
static void ForceRefresh (FFeedbackContext &Context)
Whenever we encounter edge condition requiring to force a UI refresh.
Private Attributes
bool bCreatedDialog
Flag that specifies whether this feedback scope created a new slow task dialog.
bool bDelayedDialogAllowInPIE: 1
Specify whether the delayed dialog is allowed in PIE.
bool bDelayedDialogShowCancelButton: 1
Specify whether the delayed dialog should show a cancel button.
bool bEnabled
Boolean flag to control whether this scope actually does anything (unset for quiet operations etc)
bool bSkipRecursiveDialogCreation: 1
Avoid calling hierarchical dialog creation if not required.
FFeedbackContext & Context
The feedback context that we belong to.
uint64 RegionId
Id of the traced timing region.
Detailed Description
Data type used to store information about a currently running slow task.
Direct use is not advised, use FScopedSlowTask instead
Definition at line 28 of file SlowTask.h.
Constructor & Destructor Documentation
FSlowTask() [1/2]
FSlowTask::FSlowTask (const FSlowTask &) private
Prevent copying.
References FSlowTask().
Referenced by FScopedSlowTask::FScopedSlowTask(), and FSlowTask().
FSlowTask() [2/2]
FSlowTask::FSlowTask (float InAmountOfWork, const FText & InDefaultMessage = FText(), bool bInEnabled = true, FFeedbackContext & InContext = *GWarn)
Construct this scope from an amount of work to do, and a message to display.
Parameters
InAmountOfWork Arbitrary number of work units to perform (can be a percentage or number of steps). 0 indicates that no progress frames are to be entered in this scope (automatically enters a frame encompassing the entire scope)
InDefaultMessage A message to display to the user to describe the purpose of the scope
bInVisible When false, this scope will have no effect. Allows for proper scoped objects that are conditionally hidden.
References GWarn.
Member Function Documentation
Destroy()
void FSlowTask::Destroy ()
Function that finishes any remaining work and removes itself from the global scope stack.
Referenced by FScopedSlowTask::~FScopedSlowTask().
EnterProgressFrame()
void FSlowTask::EnterProgressFrame (float ExpectedWorkThisFrame = 1.f, const FText & Text = FText())
Indicate that we are to enter a frame that will take up the specified amount of work.
Completes any previous frames (potentially contributing to parent scopes' progress).
Parameters
ExpectedWorkThisFrame The amount of work that will happen between now and the next frame, as a numerator of TotalAmountOfWork.
Text Optional text to describe this frame's purpose.
References Text.
ForceRefresh() [1/2]
void FSlowTask::ForceRefresh ()
Whenever we encounter edge condition requiring to force a UI refresh (Like if another popup would show when the slow task finishes and you want it to show 100%)
ForceRefresh() [2/2]
void FSlowTask::ForceRefresh (FFeedbackContext & Context) static private
Whenever we encounter edge condition requiring to force a UI refresh.
References Context.
GetCurrentMessage()
const FText & FSlowTask::GetCurrentMessage () const
Get the frame message or default message if empty.
Initialize()
void FSlowTask::Initialize ()
Function that initializes the scope by adding it to its context's stack.
Referenced by FScopedSlowTask::FScopedSlowTask().
MakeDialog()
void FSlowTask::MakeDialog (bool bShowCancelButton = false, bool bAllowInPIE = false)
Creates a new dialog for this slow task, if there is currently not one open.
Parameters
bShowCancelButton Whether to show a cancel button on the dialog or not
bAllowInPIE Whether to allow this dialog in PIE. If false, this dialog will not appear during PIE sessions.
MakeDialogDelayed()
void FSlowTask::MakeDialogDelayed (float Threshold, bool bShowCancelButton = false, bool bAllowInPIE = false)
Creates a new dialog for this slow task after the given time threshold.
If the task completes before this time, no dialog will be shown.
Parameters
Threshold Time in seconds before dialog will be shown.
bShowCancelButton Whether to show a cancel button on the dialog or not
bAllowInPIE Whether to allow this dialog in PIE. If false, this dialog will not appear during PIE sessions.
MakeDialogIfNeeded()
bool FSlowTask::MakeDialogIfNeeded () private
Handle dialog and delayed dialog creation logic.
MakeRecursiveDialogIfNeeded()
void FSlowTask::MakeRecursiveDialogIfNeeded () private
Call MakeDialogIfNeeded on all scopes recursively to give them a chance to create a delayed dialog in the hierarchy.
ShouldCancel()
bool FSlowTask::ShouldCancel () const
True if the user has requested that the slow task be canceled.
ShouldCreateThrottledSlowTask()
bool FSlowTask::ShouldCreateThrottledSlowTask () static
True if a slow task should be created.
False if a slow task should not be created because another was created recently.
TickProgress()
void FSlowTask::TickProgress ()
Let the UI refresh but doesn't advance progress.
This should be called at regular intervals even when no progress is being made to keep the UI responsive.
Field Documentation
bCreatedDialog
bool FSlowTask::bCreatedDialog private
Flag that specifies whether this feedback scope created a new slow task dialog.
Definition at line 60 of file SlowTask.h.
bDelayedDialogAllowInPIE
bool FSlowTask::bDelayedDialogAllowInPIE private
Specify whether the delayed dialog is allowed in PIE.
Definition at line 69 of file SlowTask.h.
bDelayedDialogShowCancelButton
bool FSlowTask::bDelayedDialogShowCancelButton private
Specify whether the delayed dialog should show a cancel button.
Definition at line 66 of file SlowTask.h.
bEnabled
bool FSlowTask::bEnabled private
Boolean flag to control whether this scope actually does anything (unset for quiet operations etc)
Definition at line 57 of file SlowTask.h.
bSkipRecursiveDialogCreation
bool FSlowTask::bSkipRecursiveDialogCreation private
Avoid calling hierarchical dialog creation if not required.
Definition at line 72 of file SlowTask.h.
CompletedWork
float FSlowTask::CompletedWork
The amount of work we have already completed in this scope.
Definition at line 40 of file SlowTask.h.
Context
FFeedbackContext& FSlowTask::Context private
The feedback context that we belong to.
Definition at line 63 of file SlowTask.h.
Referenced by ForceRefresh().
CurrentFrameScope
float FSlowTask::CurrentFrameScope
The amount of work the current frame is responsible for.
Definition at line 43 of file SlowTask.h.
DefaultMessage
FText FSlowTask::DefaultMessage
Default message to display to the user when not overridden by a frame.
Definition at line 31 of file SlowTask.h.
FrameMessage
FText FSlowTask::FrameMessage
Message pertaining to the current frame's work.
Definition at line 34 of file SlowTask.h.
OpenDialogThreshold
TOptional<float> FSlowTask::OpenDialogThreshold
Threshold before dialog is opened.
Definition at line 52 of file SlowTask.h.
RegionId
uint64 FSlowTask::RegionId private
Id of the traced timing region.
Definition at line 75 of file SlowTask.h.
StartTime
double FSlowTask::StartTime
The time that this scope was created.
Definition at line 49 of file SlowTask.h.
TotalAmountOfWork
float FSlowTask::TotalAmountOfWork
The amount of work to do in this scope.
Definition at line 37 of file SlowTask.h.
Visibility
ESlowTaskVisibility FSlowTask::Visibility
The visibility of this slow task.
Definition at line 46 of file SlowTask.h.
The documentation for this struct was generated from the following file:
SlowTask.h