Unreal Engine 5.6 C++ API: LowLevelTasks::FOversubscriptionScope Class Reference
LowLevelTasks::FOversubscriptionScope Class Reference
#include "Scheduler.h"
Public Member Functions
FOversubscriptionScope (bool bCondition=true)
~FOversubscriptionScope ()
Private Member Functions
UE_NONCOPYABLE (FOversubscriptionScope)
Private Attributes
bool bCpuBeginEventEmitted = false
bool bIncrementOversubscriptionEmitted = false
Detailed Description
Definition at line 310 of file Scheduler.h.
Constructor & Destructor Documentation
FOversubscriptionScope()
LowLevelTasks::FOversubscriptionScope::FOversubscriptionScope (bool bCondition = true) inline
Definition at line 315 of file Scheduler.h.
References bCpuBeginEventEmitted, bIncrementOversubscriptionEmitted, LowLevelTasks::FScheduler::Get(), LowLevelTasks::FScheduler::IncrementOversubscription(), and LowLevelTasks::Private::FOversubscriptionTls::IsOversubscriptionAllowed().
Referenced by UE_NONCOPYABLE().
~FOversubscriptionScope()
LowLevelTasks::FOversubscriptionScope::~FOversubscriptionScope () inline
Definition at line 333 of file Scheduler.h.
References bCpuBeginEventEmitted, bIncrementOversubscriptionEmitted, LowLevelTasks::FScheduler::DecrementOversubscription(), and LowLevelTasks::FScheduler::Get().
Member Function Documentation
UE_NONCOPYABLE()
LowLevelTasks::FOversubscriptionScope::UE_NONCOPYABLE (FOversubscriptionScope) private
References FOversubscriptionScope().
Field Documentation
bCpuBeginEventEmitted
bool LowLevelTasks::FOversubscriptionScope::bCpuBeginEventEmitted = false private
Definition at line 350 of file Scheduler.h.
Referenced by FOversubscriptionScope(), and ~FOversubscriptionScope().
bIncrementOversubscriptionEmitted
bool LowLevelTasks::FOversubscriptionScope::bIncrementOversubscriptionEmitted = false private
Definition at line 349 of file Scheduler.h.
Referenced by FOversubscriptionScope(), and ~FOversubscriptionScope().
The documentation for this class was generated from the following file:
Scheduler.h