Unreal Engine 5.6 C++ API: ShaderCompilerCore.h File Reference
ShaderCompilerCore.h File Reference
#include "CoreMinimal.h"
#include "HAL/FileManager.h"
#include "Hash/Blake3.h"
#include "Hash/xxhash.h"
#include "Stats/Stats.h"
#include "Templates/RefCounting.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/SecureHash.h"
#include "Misc/Paths.h"
#include "Misc/PathViews.h"
#include "Misc/CoreStats.h"
#include "ShaderCore.h"
#include "ShaderParameterMetadata.h"
#include "ShaderCompilerFlags.inl"
Data Structures
struct FExtraShaderCompilerSettings
Additional compilation settings that can be configured by each FMaterial instance before compilation.
struct FSCWErrorCode
struct FShaderCompilerError
A shader compiler error or warning.
struct FShaderCompilerInput
Struct that gathers all readonly inputs needed for the compilation of a single shader.
struct FShaderCompilerOutput
The output of the shader compiler.
struct FShaderCompilerResourceTable
struct FShaderCompileWorkerDiagnostics
Serializable structure of diagnostic output from a SCW process.
struct FShaderPreprocessDependencies
struct FShaderPreprocessDependency
Namespaces
namespace FOodleDataCompression
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::ShaderCompiler
Macros
#define SHADER_COMPILER_FLAGS_ENTRY(Name)
#define SHADER_COMPILER_FLAGS_ENTRY_DEPRECATED(Name, Version, Message)
Typedefs
using FShaderCompilerInputHash = FBlake3Hash
typedef TSharedPtr< FShaderPreprocessDependencies, ESPMode::ThreadSafe > FShaderPreprocessDependenciesShared
typedef TSharedPtr< TArray< ANSICHAR >, ESPMode::ThreadSafe > FShaderSharedAnsiStringPtr
Enumerations
enum ECompilerFlags {
CFLAG_PreferFlowControl , CFLAG_Debug , CFLAG_AvoidFlowControl , CFLAG_SkipValidation ,
CFLAG_StandardOptimization , CFLAG_ForceOptimization , CFLAG_GenerateSymbols , CFLAG_ExtraShaderData ,
CFLAG_AllowUniqueSymbols , CFLAG_NoFastMath , CFLAG_ZeroInitialise , CFLAG_BoundsChecking ,
CFLAG_ForceRemoveUnusedInterpolators , CFLAG_VertexToGeometryShader , CFLAG_VertexToPrimitiveShader , CFLAG_VertexUseAutoCulling ,
CFLAG_Archive , CFLAG_UsesExternalTexture , CFLAG_UseEmulatedUB , CFLAG_WaveOperations ,
CFLAG_ForceDXC , CFLAG_SkipOptimizations , CFLAG_SkipOptimizationsDXC , CFLAG_AllowTypedUAVLoads ,
CFLAG_Wave32 , CFLAG_InlineRayTracing , CFLAG_AllowRealTypes , CFLAG_PrecompileWithDXC ,
CFLAG_HLSL2021 , CFLAG_WarningsAsErrors , CFLAG_BindlessResources , CFLAG_BindlessSamplers ,
CFLAG_ForceBindful , CFLAG_RemoveDeadCode , CFLAG_CullBeforeFetch , CFLAG_WarpCulling ,
CFLAG_GenerateSymbolsInfo , CFLAG_RootConstants , CFLAG_CheckForDerivativeOps , CFLAG_IndirectDraw ,
CFLAG_ShaderBundle , CFLAG_DisableSourceStripping , CFLAG_ShaderBindingLayout , CFLAG_OutputAnalysisArtifacts ,
CFLAG_ForceSpirvDebugInfo , CFLAG_Max
}
enum class EOfflineShaderCompilerType : uint8 { Mali , Adreno , Num }
enumeration of offline shader compiler for the material editor
enum class EShaderCompileJobType : uint8 { Single , Pipeline , Num }
enum class EShaderCompilerWorkerType : uint8 { None , LocalThread , Distributed }
enum class EShaderDebugInfoFlags : uint8 {
Default = 0 , DirectCompileCommandLine = 1 << 0 , InputHash = 1 << 1 , Diagnostics = 1 << 2 ,
ShaderCodeBinary = 1 << 3 , DetailedSource = 1 << 4 , CompileFromDebugUSF = 1 << 5 , ShaderCodePlatformHashes = 1 << 6
}
enum class EWriteShaderSymbols : uint8 { Disable = 0 , UnCompress = 1 , Compress = 2 }
Functions
RENDERCORE_API bool AllowGlobalShaderLoad ()
Returns true if the global shader cache should be loaded (and potentially compiled if allowed/needed.
RENDERCORE_API bool AllowShaderCompiling ()
Returns true is shader compiling is allowed.
RENDERCORE_API bool CheckVirtualShaderFilePath (FStringView VirtualPath, TArray< FShaderCompilerError > *CompileErrors=nullptr)
Validates the format of a virtual shader file path.
RENDERCORE_API void CompileShader (const TArray< const IShaderFormat * > &ShaderFormats, FShaderCompileJob &Job, const FString &WorkingDirectory, int32 *CompileCount=nullptr)
RENDERCORE_API void CompileShaderPipeline (const TArray< const IShaderFormat * > &ShaderFormats, FShaderPipelineCompileJob *PipelineJob, const FString &WorkingDirectory, int32 *CompileCount=nullptr)
RENDERCORE_API bool ConditionalPreprocessShader (FShaderCommonCompileJob *Job)
RENDERCORE_API const IShaderFormat * FindShaderFormat (FName Format, const TArray< const IShaderFormat * > &ShaderFormats)
RENDERCORE_API void FixupShaderFilePath (FString &VirtualFilePath, EShaderPlatform ShaderPlatform, const FName *ShaderPlatformName)
Fixes up the given virtual file path (substituting virtual platform path/autogen path for the given platform)
RENDERCORE_API ERHIBindlessConfiguration UE::ShaderCompiler::GetBindlessResourcesConfiguration (FName ShaderFormat)
RENDERCORE_API ERHIBindlessConfiguration UE::ShaderCompiler::GetBindlessSamplersConfiguration (FName ShaderFormat)
RENDERCORE_API const FString & GetBuildMachineArtifactBasePath ()
Returns the path where shader compilation related artifacts should be stored when running on a build machine.
RENDERCORE_API const FString & GetShaderDebugInfoPath ()
Returns the base path where any shader debug information should be written to.
RENDERCORE_API bool GetShaderPreprocessDependencies (const TCHAR *VirtualFilePath, EShaderPlatform ShaderPlatform, FShaderPreprocessDependenciesShared &OutDependencies)
Utility function that returns a root shader file plus all non-platform include dependencies in a single batch call, useful for preprocessing.
RENDERCORE_API bool GetShaderSymbolPathOverride (FString &OutPathOverride, FName ShaderFormat)
Returns true if the shader symbol path is overridden and OutPathOverride contains the override path.
RENDERCORE_API EWriteShaderSymbols GetWriteShaderSymbolsOptions (FName ShaderFormat)
Returns true if shaders should be combined into a single zip file instead of individual files.
RENDERCORE_API int HandleShaderCompileException (Windows::LPEXCEPTION_POINTERS Info, FString &OutExMsg, FString &OutCallStack)
RENDERCORE_API void LexFromString (ECompilerFlags &OutValue, const TCHAR *InString)
RENDERCORE_API const TCHAR * LexToString (ECompilerFlags InValue)
RENDERCORE_API bool LoadShaderSourceFile (const TCHAR *VirtualFilePath, EShaderPlatform ShaderPlatform, FString *OutFileContents, TArray< FShaderCompilerError > *OutCompileErrors, const FName *ShaderPlatformName=nullptr, FShaderSharedAnsiStringPtr *OutStrippedContents=nullptr)
Loads the shader file with the given name.
constexpr bool operator! (EShaderDebugInfoFlags E)
constexpr EShaderDebugInfoFlags operator& (EShaderDebugInfoFlags Lhs, EShaderDebugInfoFlags Rhs)
EShaderDebugInfoFlags & operator&= (EShaderDebugInfoFlags &Lhs, EShaderDebugInfoFlags Rhs)
constexpr EShaderDebugInfoFlags operator^ (EShaderDebugInfoFlags Lhs, EShaderDebugInfoFlags Rhs)
EShaderDebugInfoFlags & operator^= (EShaderDebugInfoFlags &Lhs, EShaderDebugInfoFlags Rhs)
constexpr EShaderDebugInfoFlags operator| (EShaderDebugInfoFlags Lhs, EShaderDebugInfoFlags Rhs)
EShaderDebugInfoFlags & operator|= (EShaderDebugInfoFlags &Lhs, EShaderDebugInfoFlags Rhs)
constexpr EShaderDebugInfoFlags operator~ (EShaderDebugInfoFlags E)
RENDERCORE_API bool PreprocessShader (FShaderCommonCompileJob *Job)
RENDERCORE_API void ShaderConvertAndStripComments (const FString &ShaderSource, TArray< ANSICHAR > &OutStripped)
Utility function to strip comments and convert source to ANSI, useful for preprocessing.
RENDERCORE_API bool ShouldAllowUniqueShaderSymbols (FName ShaderFormat)
Returns true if (external) shader symbols should be specific to each shader rather than be de-duplicated.
RENDERCORE_API bool ShouldEnableExtraShaderData (FName ShaderFormat)
Returns true if the user wants more runtime shader data (names, extra info)
RENDERCORE_API bool ShouldGenerateShaderSymbols (FName ShaderFormat)
Returns true if shader symbols should be kept for a given platform.
RENDERCORE_API bool ShouldGenerateShaderSymbolsInfo (FName ShaderFormat)
Returns true if shader symbol minimal info files should be generated for a given platform.
RENDERCORE_API bool ShouldOptimizeShaders (FName ShaderFormat)
RENDERCORE_API bool ShouldWriteShaderSymbols (FName ShaderFormat)
Returns true if shader symbols should be exported to separate files for a given platform.
Variables
constexpr int32 NumShaderCompileJobTypes = (int32)EShaderCompileJobType::Num
const int32 ShaderCompileWorkerInputVersion = 29
const int32 ShaderCompileWorkerOutputVersion = 28
const int32 ShaderCompileWorkerPipelineJobHeader = 'P'
const int32 ShaderCompileWorkerSingleJobHeader = 'S'
static const FGuid UE_SHADER_CACHE_VERSION = FGuid("B04528D6-1A2C-44C8-A742-E7D497D3562C")
Macro Definition Documentation
SHADER_COMPILER_FLAGS_ENTRY
#define SHADER_COMPILER_FLAGS_ENTRY (Name)
Value:
CFLAG_##Name,
Definition at line 94 of file ShaderCompilerCore.h.
SHADER_COMPILER_FLAGS_ENTRY_DEPRECATED
#define SHADER_COMPILER_FLAGS_ENTRY_DEPRECATED (Name, Version, Message)
Value:
CFLAG_##Name UE_DEPRECATED(Version, Message),
Definition at line 95 of file ShaderCompilerCore.h.
Typedef Documentation
FShaderCompilerInputHash
using FShaderCompilerInputHash = FBlake3Hash
Definition at line 185 of file ShaderCompilerCore.h.
FShaderPreprocessDependenciesShared
typedef TSharedPtr<FShaderPreprocessDependencies, ESPMode::ThreadSafe> FShaderPreprocessDependenciesShared
Definition at line 786 of file ShaderCompilerCore.h.
FShaderSharedAnsiStringPtr
typedef TSharedPtr<TArray<ANSICHAR>, ESPMode::ThreadSafe> FShaderSharedAnsiStringPtr
Definition at line 28 of file ShaderCompilerCore.h.
Enumeration Type Documentation
ECompilerFlags
enum ECompilerFlags
Enumerator
CFLAG_PreferFlowControl
CFLAG_Debug
CFLAG_AvoidFlowControl
CFLAG_SkipValidation
CFLAG_StandardOptimization
CFLAG_ForceOptimization
CFLAG_GenerateSymbols
CFLAG_ExtraShaderData
CFLAG_AllowUniqueSymbols
CFLAG_NoFastMath
CFLAG_ZeroInitialise
CFLAG_BoundsChecking
CFLAG_ForceRemoveUnusedInterpolators
CFLAG_VertexToGeometryShader
CFLAG_VertexToPrimitiveShader
CFLAG_VertexUseAutoCulling
CFLAG_Archive
CFLAG_UsesExternalTexture
CFLAG_UseEmulatedUB
CFLAG_WaveOperations
CFLAG_ForceDXC
CFLAG_SkipOptimizations
CFLAG_SkipOptimizationsDXC
CFLAG_AllowTypedUAVLoads
CFLAG_Wave32
CFLAG_InlineRayTracing
CFLAG_AllowRealTypes
CFLAG_PrecompileWithDXC
CFLAG_HLSL2021
CFLAG_WarningsAsErrors
CFLAG_BindlessResources
CFLAG_BindlessSamplers
CFLAG_ForceBindful
CFLAG_RemoveDeadCode
CFLAG_CullBeforeFetch
CFLAG_WarpCulling
CFLAG_GenerateSymbolsInfo
CFLAG_RootConstants
CFLAG_CheckForDerivativeOps
CFLAG_IndirectDraw
CFLAG_ShaderBundle
CFLAG_DisableSourceStripping
CFLAG_ShaderBindingLayout
CFLAG_OutputAnalysisArtifacts
CFLAG_ForceSpirvDebugInfo
CFLAG_Max
Definition at line 92 of file ShaderCompilerCore.h.
EOfflineShaderCompilerType
enum class EOfflineShaderCompilerType : uint8 strong
enumeration of offline shader compiler for the material editor
Enumerator
Mali
Adreno
Num
Definition at line 139 of file ShaderCompilerCore.h.
EShaderCompileJobType
enum class EShaderCompileJobType : uint8 strong
Enumerator
Single
Pipeline
Num
Definition at line 800 of file ShaderCompilerCore.h.
EShaderCompilerWorkerType
enum class EShaderCompilerWorkerType : uint8 strong
Enumerator
None
LocalThread
Distributed
Definition at line 793 of file ShaderCompilerCore.h.
EShaderDebugInfoFlags
enum class EShaderDebugInfoFlags : uint8 strong
Enumerator
Default
DirectCompileCommandLine
InputHash
Diagnostics
ShaderCodeBinary
DetailedSource
CompileFromDebugUSF
ShaderCodePlatformHashes
Definition at line 172 of file ShaderCompilerCore.h.
EWriteShaderSymbols
enum class EWriteShaderSymbols : uint8 strong
Enumerator
Disable
UnCompress
Compress
Definition at line 70 of file ShaderCompilerCore.h.
Function Documentation
AllowGlobalShaderLoad()
RENDERCORE_API bool AllowGlobalShaderLoad () extern
Returns true if the global shader cache should be loaded (and potentially compiled if allowed/needed.
AllowShaderCompiling()
RENDERCORE_API bool AllowShaderCompiling () extern
Returns true is shader compiling is allowed.
Referenced by FShaderCompilingManager::SkipShaderCompilation().
CheckVirtualShaderFilePath()
RENDERCORE_API bool CheckVirtualShaderFilePath (FStringView VirtualPath, TArray< FShaderCompilerError > * CompileErrors = nullptr) extern
Validates the format of a virtual shader file path.
Meant to be use as such: check(CheckVirtualShaderFilePath(VirtualFilePath)); CompileErrors output array is optional. If this is non-null, all validation errors are returned to this array instead of logging them to LogShaders.
References CheckVirtualShaderFilePath().
Referenced by CheckVirtualShaderFilePath().
CompileShader()
RENDERCORE_API void CompileShader (const TArray< const IShaderFormat * > & ShaderFormats, FShaderCompileJob & Job, const FString & WorkingDirectory, int32 * CompileCount = nullptr) extern
References CompileShader().
Referenced by CompileShader().
CompileShaderPipeline()
RENDERCORE_API void CompileShaderPipeline (const TArray< const IShaderFormat * > & ShaderFormats, FShaderPipelineCompileJob * PipelineJob, const FString & WorkingDirectory, int32 * CompileCount = nullptr) extern
References CompileShaderPipeline().
Referenced by CompileShaderPipeline().
ConditionalPreprocessShader()
RENDERCORE_API bool ConditionalPreprocessShader (FShaderCommonCompileJob * Job) extern
References ConditionalPreprocessShader().
Referenced by ConditionalPreprocessShader().
FindShaderFormat()
RENDERCORE_API const IShaderFormat * FindShaderFormat (FName Format, const TArray< const IShaderFormat * > & ShaderFormats) extern
References Format.
FixupShaderFilePath()
RENDERCORE_API void FixupShaderFilePath (FString & VirtualFilePath, EShaderPlatform ShaderPlatform, const FName * ShaderPlatformName) extern
Fixes up the given virtual file path (substituting virtual platform path/autogen path for the given platform)
References FixupShaderFilePath(), ShaderPlatform, and VirtualFilePath.
Referenced by FixupShaderFilePath().
GetBuildMachineArtifactBasePath()
RENDERCORE_API const FString & GetBuildMachineArtifactBasePath () extern
Returns the path where shader compilation related artifacts should be stored when running on a build machine.
GetShaderDebugInfoPath()
RENDERCORE_API const FString & GetShaderDebugInfoPath () extern
Returns the base path where any shader debug information should be written to.
Referenced by FShaderCompilingManager::GetAbsoluteShaderDebugInfoDirectory().
GetShaderPreprocessDependencies()
RENDERCORE_API bool GetShaderPreprocessDependencies (const TCHAR * VirtualFilePath, EShaderPlatform ShaderPlatform, FShaderPreprocessDependenciesShared & OutDependencies) extern
Utility function that returns a root shader file plus all non-platform include dependencies in a single batch call, useful for preprocessing.
References ShaderPlatform, and VirtualFilePath.
GetShaderSymbolPathOverride()
RENDERCORE_API bool GetShaderSymbolPathOverride (FString & OutPathOverride, FName ShaderFormat) extern
Returns true if the shader symbol path is overridden and OutPathOverride contains the override path.
GetWriteShaderSymbolsOptions()
RENDERCORE_API EWriteShaderSymbols GetWriteShaderSymbolsOptions (FName ShaderFormat) extern
Returns true if shaders should be combined into a single zip file instead of individual files.
HandleShaderCompileException()
RENDERCORE_API int HandleShaderCompileException (Windows::LPEXCEPTION_POINTERS Info, FString & OutExMsg, FString & OutCallStack) extern
References Info.
LexFromString()
RENDERCORE_API void LexFromString (ECompilerFlags & OutValue, const TCHAR * InString) extern
LexToString()
RENDERCORE_API const TCHAR * LexToString (ECompilerFlags InValue) extern
LoadShaderSourceFile()
RENDERCORE_API bool LoadShaderSourceFile (const TCHAR * VirtualFilePath, EShaderPlatform ShaderPlatform, FString * OutFileContents, TArray< FShaderCompilerError > * OutCompileErrors, const FName * ShaderPlatformName = nullptr, FShaderSharedAnsiStringPtr * OutStrippedContents = nullptr) extern
Loads the shader file with the given name.
Parameters
VirtualFilePath - The virtual path of shader file to load.
OutFileContents - If true is returned, will contain the contents of the shader file. Can be null.
Returns
True if the file was successfully loaded.
References LoadShaderSourceFile(), ShaderPlatform, and VirtualFilePath.
Referenced by LoadShaderSourceFile().
operator!()
bool operator! (EShaderDebugInfoFlags E) inline constexpr
Definition at line 183 of file ShaderCompilerCore.h.
operator&()
EShaderDebugInfoFlags operator& (EShaderDebugInfoFlags Lhs, EShaderDebugInfoFlags Rhs) inline constexpr
Definition at line 183 of file ShaderCompilerCore.h.
operator&=()
EShaderDebugInfoFlags & operator&= (EShaderDebugInfoFlags & Lhs, EShaderDebugInfoFlags Rhs) inline
Definition at line 183 of file ShaderCompilerCore.h.
operator^()
EShaderDebugInfoFlags operator^ (EShaderDebugInfoFlags Lhs, EShaderDebugInfoFlags Rhs) inline constexpr
Definition at line 183 of file ShaderCompilerCore.h.
operator^=()
EShaderDebugInfoFlags & operator^= (EShaderDebugInfoFlags & Lhs, EShaderDebugInfoFlags Rhs) inline
Definition at line 183 of file ShaderCompilerCore.h.
operator|()
EShaderDebugInfoFlags operator| (EShaderDebugInfoFlags Lhs, EShaderDebugInfoFlags Rhs) inline constexpr
Definition at line 183 of file ShaderCompilerCore.h.
operator|=()
EShaderDebugInfoFlags & operator|= (EShaderDebugInfoFlags & Lhs, EShaderDebugInfoFlags Rhs) inline
Definition at line 183 of file ShaderCompilerCore.h.
operator~()
EShaderDebugInfoFlags operator~ (EShaderDebugInfoFlags E) inline constexpr
Definition at line 183 of file ShaderCompilerCore.h.
PreprocessShader()
RENDERCORE_API bool PreprocessShader (FShaderCommonCompileJob * Job) extern
References PreprocessShader().
Referenced by PreprocessShader().
ShaderConvertAndStripComments()
RENDERCORE_API void ShaderConvertAndStripComments (const FString & ShaderSource, TArray< ANSICHAR > & OutStripped) extern
Utility function to strip comments and convert source to ANSI, useful for preprocessing.
References ShaderConvertAndStripComments().
Referenced by ShaderConvertAndStripComments().
ShouldAllowUniqueShaderSymbols()
RENDERCORE_API bool ShouldAllowUniqueShaderSymbols (FName ShaderFormat) extern
Returns true if (external) shader symbols should be specific to each shader rather than be de-duplicated.
ShouldEnableExtraShaderData()
RENDERCORE_API bool ShouldEnableExtraShaderData (FName ShaderFormat) extern
Returns true if the user wants more runtime shader data (names, extra info)
ShouldGenerateShaderSymbols()
RENDERCORE_API bool ShouldGenerateShaderSymbols (FName ShaderFormat) extern
Returns true if shader symbols should be kept for a given platform.
ShouldGenerateShaderSymbolsInfo()
RENDERCORE_API bool ShouldGenerateShaderSymbolsInfo (FName ShaderFormat) extern
Returns true if shader symbol minimal info files should be generated for a given platform.
ShouldOptimizeShaders()
RENDERCORE_API bool ShouldOptimizeShaders (FName ShaderFormat) extern
ShouldWriteShaderSymbols()
RENDERCORE_API bool ShouldWriteShaderSymbols (FName ShaderFormat) extern
Returns true if shader symbols should be exported to separate files for a given platform.
Variable Documentation
NumShaderCompileJobTypes
int32 NumShaderCompileJobTypes = (int32)EShaderCompileJobType::Num inline constexpr
Definition at line 806 of file ShaderCompilerCore.h.
ShaderCompileWorkerInputVersion
const int32 ShaderCompileWorkerInputVersion = 29 inline
Definition at line 31 of file ShaderCompilerCore.h.
ShaderCompileWorkerOutputVersion
const int32 ShaderCompileWorkerOutputVersion = 28 inline
Definition at line 33 of file ShaderCompilerCore.h.
ShaderCompileWorkerPipelineJobHeader
const int32 ShaderCompileWorkerPipelineJobHeader = 'P' inline
Definition at line 37 of file ShaderCompilerCore.h.
ShaderCompileWorkerSingleJobHeader
const int32 ShaderCompileWorkerSingleJobHeader = 'S' inline
Definition at line 35 of file ShaderCompilerCore.h.
UE_SHADER_CACHE_VERSION
const FGuid UE_SHADER_CACHE_VERSION = FGuid("B04528D6-1A2C-44C8-A742-E7D497D3562C") inline static
Definition at line 41 of file ShaderCompilerCore.h.