Unreal Engine 5.6 C++ API: UE::MovieScene::FPlaybackCapabilitiesImpl Struct Reference
UE::MovieScene::FPlaybackCapabilitiesImpl Struct Reference
Basic, mostly untyped, implementation of the capabilities buffer.
#include "MovieScenePlaybackCapabilities.h"
Protected Member Functions
FPlaybackCapabilitiesImpl ()=default
FPlaybackCapabilitiesImpl (const FPlaybackCapabilitiesImpl &)=delete
FPlaybackCapabilitiesImpl (FPlaybackCapabilitiesImpl &&)=delete
template<typename StorageType, typename CapabilityType, typename ... ArgTypes>
FPlaybackCapabilityPtr AddCapability (uint32 CapabilityBit, ArgTypes &&... InArgs)
Creates and stores a new capability object at the given bit.
FPlaybackCapabilityPtr FindCapability (uint32 CapabilityBit) const
FPlaybackCapabilityPtr GetCapabilityChecked (uint32 CapabilityBit) const
int32 GetCapabilityIndex (uint32 CapabilityBit) const
FPlaybackCapabilityHeader & GetHeader (uint8 Index)
const FPlaybackCapabilityHeader & GetHeader (uint8 Index) const
TArrayView< const FPlaybackCapabilityHeader > GetHeaders () const
bool HasCapability (uint32 CapabilityBit) const
FPlaybackCapabilitiesImpl & operator= (const FPlaybackCapabilitiesImpl &)=delete
FPlaybackCapabilitiesImpl & operator= (FPlaybackCapabilitiesImpl &&)=delete
template<typename StorageType, typename CapabilityType, typename ... ArgTypes>
bool OverwriteCapability (uint32 CapabilityBit, ArgTypes &&... InArgs)
Protected Attributes
uint16 Alignment = 0u
uint32 AllCapabilities = 0u
uint16 Capacity = 0u
TArray< FPlaybackCapabilityHelpers > Helpers
uint8 * Memory = nullptr
uint8 Num = 0u
Detailed Description
Basic, mostly untyped, implementation of the capabilities buffer.
Definition at line 231 of file MovieScenePlaybackCapabilities.h.
Constructor & Destructor Documentation
FPlaybackCapabilitiesImpl() [1/3]
UE::MovieScene::FPlaybackCapabilitiesImpl::FPlaybackCapabilitiesImpl () protected default
Referenced by FPlaybackCapabilitiesImpl(), FPlaybackCapabilitiesImpl(), operator=(), and operator=().
FPlaybackCapabilitiesImpl() [2/3]
UE::MovieScene::FPlaybackCapabilitiesImpl::FPlaybackCapabilitiesImpl (const FPlaybackCapabilitiesImpl &) protected delete
References FPlaybackCapabilitiesImpl().
FPlaybackCapabilitiesImpl() [3/3]
UE::MovieScene::FPlaybackCapabilitiesImpl::FPlaybackCapabilitiesImpl (FPlaybackCapabilitiesImpl &&) protected delete
References FPlaybackCapabilitiesImpl().
Member Function Documentation
AddCapability()
template<typename StorageType, typename CapabilityType, typename ... ArgTypes> FPlaybackCapabilityPtr UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability (uint32 CapabilityBit, ArgTypes &&... InArgs) inline protected
Creates and stores a new capability object at the given bit.
StorageType is what is actually constructed and stored in our memory buffer. It can be the same as CapabilityType, a subclass of it, a pointer to it, or a shared pointer to it.
CapabilityType is the base capability type, used onlyfor inline storage when the StorageType is a subclass and we need to compute the pointer offset.
Definition at line 277 of file MovieScenePlaybackCapabilities.h.
References Align, Alignment, UE::MovieScene::FPlaybackCapabilityHeader::Alignment, AllCapabilities, UE::MovieScene::FPlaybackCapabilityHeader::Capability, Capacity, check, checkf, Forward(), FMemory::Free(), UE::MovieScene::TPlaybackCapabilityHelpers< StorageType >::GetHelpers(), Helpers, FMath::Max, MAX_uint16, MAX_uint8, FMemory::Memmove(), Memory, Num, UE::MovieScene::FPlaybackCapabilityHeader::PointerOffset, TRelativePtr< T, OffsetType >::Reset(), TRelativePtr< T, OffsetType >::Resolve(), UE::MovieScene::FPlaybackCapabilityHeader::Resolve(), TArray< InElementType, InAllocatorType >::SetNum(), UE::MovieScene::FPlaybackCapabilityHeader::Sizeof, UE::MovieScene::FPlaybackCapabilityHeader::StorageMode, and TEXT.
Referenced by UE::MovieScene::FPlaybackCapabilities::DoAddCapability().
FindCapability()
FPlaybackCapabilityPtr UE::MovieScene::FPlaybackCapabilitiesImpl::FindCapability (uint32 CapabilityBit) const inline protected
Definition at line 248 of file MovieScenePlaybackCapabilities.h.
References check, GetCapabilityIndex(), GetHeader(), HasCapability(), Memory, and UE::MovieScene::FPlaybackCapabilityHeader::Resolve().
Referenced by UE::MovieScene::FPlaybackCapabilities::FindCapability().
GetCapabilityChecked()
FPlaybackCapabilityPtr UE::MovieScene::FPlaybackCapabilitiesImpl::GetCapabilityChecked (uint32 CapabilityBit) const inline protected
Definition at line 260 of file MovieScenePlaybackCapabilities.h.
References check, GetCapabilityIndex(), GetHeader(), Memory, and UE::MovieScene::FPlaybackCapabilityHeader::Resolve().
Referenced by UE::MovieScene::FPlaybackCapabilities::GetCapabilityChecked().
GetCapabilityIndex()
int32 UE::MovieScene::FPlaybackCapabilitiesImpl::GetCapabilityIndex (uint32 CapabilityBit) const inline protected
Definition at line 554 of file MovieScenePlaybackCapabilities.h.
References AllCapabilities, and INDEX_NONE.
Referenced by FindCapability(), GetCapabilityChecked(), and OverwriteCapability().
GetHeader() [1/2]
FPlaybackCapabilityHeader & UE::MovieScene::FPlaybackCapabilitiesImpl::GetHeader (uint8 Index) inline protected
Definition at line 543 of file MovieScenePlaybackCapabilities.h.
References check, Memory, and Num.
GetHeader() [2/2]
const FPlaybackCapabilityHeader & UE::MovieScene::FPlaybackCapabilitiesImpl::GetHeader (uint8 Index) const inline protected
Definition at line 537 of file MovieScenePlaybackCapabilities.h.
References check, Memory, and Num.
Referenced by FindCapability(), GetCapabilityChecked(), and OverwriteCapability().
GetHeaders()
TArrayView< const FPlaybackCapabilityHeader > UE::MovieScene::FPlaybackCapabilitiesImpl::GetHeaders () const inline protected
Definition at line 549 of file MovieScenePlaybackCapabilities.h.
References MakeArrayView(), Memory, and Num.
Referenced by UE::MovieScene::FPlaybackCapabilities::ForEachCapabilityInterface().
HasCapability()
bool UE::MovieScene::FPlaybackCapabilitiesImpl::HasCapability (uint32 CapabilityBit) const inline protected
Definition at line 243 of file MovieScenePlaybackCapabilities.h.
References AllCapabilities.
Referenced by FindCapability(), UE::MovieScene::FPlaybackCapabilities::HasCapability(), and OverwriteCapability().
operator=() [1/2]
FPlaybackCapabilitiesImpl & UE::MovieScene::FPlaybackCapabilitiesImpl::operator= (const FPlaybackCapabilitiesImpl &) protected delete
References FPlaybackCapabilitiesImpl().
operator=() [2/2]
FPlaybackCapabilitiesImpl & UE::MovieScene::FPlaybackCapabilitiesImpl::operator= (FPlaybackCapabilitiesImpl &&) protected delete
References FPlaybackCapabilitiesImpl().
OverwriteCapability()
template<typename StorageType, typename CapabilityType, typename ... ArgTypes> bool UE::MovieScene::FPlaybackCapabilitiesImpl::OverwriteCapability (uint32 CapabilityBit, ArgTypes &&... InArgs) inline protected
Definition at line 481 of file MovieScenePlaybackCapabilities.h.
References ensureMsgf, Forward(), GetCapabilityIndex(), GetHeader(), UE::MovieScene::TPlaybackCapabilityHelpers< StorageType >::GetHelpers(), HasCapability(), Header, Helpers, Memory, and TEXT.
Referenced by UE::MovieScene::FPlaybackCapabilities::DoOverwriteCapability().
Field Documentation
Alignment
uint16 UE::MovieScene::FPlaybackCapabilitiesImpl::Alignment = 0u protected
Definition at line 566 of file MovieScenePlaybackCapabilities.h.
Referenced by AddCapability().
AllCapabilities
uint32 UE::MovieScene::FPlaybackCapabilitiesImpl::AllCapabilities = 0u protected
Definition at line 569 of file MovieScenePlaybackCapabilities.h.
Referenced by AddCapability(), GetCapabilityIndex(), and HasCapability().
Capacity
uint16 UE::MovieScene::FPlaybackCapabilitiesImpl::Capacity = 0u protected
Definition at line 567 of file MovieScenePlaybackCapabilities.h.
Referenced by AddCapability().
Helpers
TArray<FPlaybackCapabilityHelpers> UE::MovieScene::FPlaybackCapabilitiesImpl::Helpers protected
Definition at line 572 of file MovieScenePlaybackCapabilities.h.
Referenced by AddCapability(), UE::MovieScene::FPlaybackCapabilities::ForEachCapabilityInterface(), and OverwriteCapability().
Memory
uint8* UE::MovieScene::FPlaybackCapabilitiesImpl::Memory = nullptr protected
Definition at line 565 of file MovieScenePlaybackCapabilities.h.
Referenced by AddCapability(), FindCapability(), UE::MovieScene::FPlaybackCapabilities::ForEachCapabilityInterface(), GetCapabilityChecked(), GetHeader(), GetHeader(), GetHeaders(), and OverwriteCapability().
Num
uint8 UE::MovieScene::FPlaybackCapabilitiesImpl::Num = 0u protected
Definition at line 568 of file MovieScenePlaybackCapabilities.h.
Referenced by AddCapability(), GetHeader(), GetHeader(), and GetHeaders().
The documentation for this struct was generated from the following file:
MovieScenePlaybackCapabilities.h