Unreal Engine 5.6 C++ API: Metasound::TAutoConverterNode< FromDataType, ToDataType > Class Template Reference
Metasound::TAutoConverterNode< FromDataType, ToDataType > Class Template Reference
#include "MetasoundAutoConverterNode.h"
Data Structures
class FConverterOperator
FConverterOperator converts from "FromDataType" to "ToDataType" using a implicit conversion operators.
class FCoverterOperatorFactory
FConverterOperatorFactory creates an operator which converts from "FromDataType" to "ToDataType".
Public Member Functions
TAutoConverterNode (const FNodeInitData &InInitData)
TAutoConverterNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
virtual ~TAutoConverterNode ()=default
virtual FOperatorFactorySharedRef GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
Public Member Functions inherited from Metasound::FBasicNode
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Static Public Member Functions
static FVertexInterface DeclareVertexInterface ()
static const FNodeClassMetadata & GetAutoConverterNodeMetadata ()
static const FVertexName & GetInputName ()
static const FVertexName & GetOutputName ()
Static Private Member Functions
static AutoConverterNodePrivate::FConvertDataTypeInfo GetConverterDataTypeInfo ()
Private Attributes
FOperatorFactorySharedRef Factory
Detailed Description
template<typename FromDataType, typename ToDataType>
class Metasound::TAutoConverterNode< FromDataType, ToDataType >
Definition at line 60 of file MetasoundAutoConverterNode.h.
Constructor & Destructor Documentation
TAutoConverterNode() [1/2]
template<typename FromDataType, typename ToDataType> Metasound::TAutoConverterNode< FromDataType, ToDataType >::TAutoConverterNode (const FNodeInitData & InInitData) inline
Definition at line 214 of file MetasoundAutoConverterNode.h.
References TAutoConverterNode(), DeclareVertexInterface(), GetAutoConverterNodeMetadata(), and MakeShared().
Referenced by TAutoConverterNode().
TAutoConverterNode() [2/2]
template<typename FromDataType, typename ToDataType> Metasound::TAutoConverterNode< FromDataType, ToDataType >::TAutoConverterNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata) inline
Definition at line 219 of file MetasoundAutoConverterNode.h.
References Metasound::FBasicNode::FBasicNode(), Factory, Metasound::MakeOperatorFactoryRef(), and MoveTemp().
~TAutoConverterNode()
template<typename FromDataType, typename ToDataType> virtual Metasound::TAutoConverterNode< FromDataType, ToDataType >::~TAutoConverterNode () virtual default
Member Function Documentation
DeclareVertexInterface()
template<typename FromDataType, typename ToDataType> FVertexInterface Metasound::TAutoConverterNode< FromDataType, ToDataType >::DeclareVertexInterface () inline static
Definition at line 91 of file MetasoundAutoConverterNode.h.
References GetConverterDataTypeInfo().
Referenced by TAutoConverterNode().
GetAutoConverterNodeMetadata()
template<typename FromDataType, typename ToDataType> const FNodeClassMetadata & Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetAutoConverterNodeMetadata () inline static
Definition at line 97 of file MetasoundAutoConverterNode.h.
References GetConverterDataTypeInfo(), and Info.
Referenced by TAutoConverterNode().
GetConverterDataTypeInfo()
template<typename FromDataType, typename ToDataType> AutoConverterNodePrivate::FConvertDataTypeInfo Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetConverterDataTypeInfo () inline static private
Definition at line 65 of file MetasoundAutoConverterNode.h.
References Metasound::TEnumTraits< T >::bIsEnum, Metasound::GetMetasoundDataTypeDisplayText(), and Metasound::GetMetasoundDataTypeName().
Referenced by DeclareVertexInterface(), and GetAutoConverterNodeMetadata().
GetDefaultOperatorFactory()
template<typename FromDataType, typename ToDataType> virtual FOperatorFactorySharedRef Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetDefaultOperatorFactory () const inline override virtual
Return a reference to the default operator factory.
Implements Metasound::INode.
Definition at line 227 of file MetasoundAutoConverterNode.h.
References Factory.
GetInputName()
template<typename FromDataType, typename ToDataType> const FVertexName & Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetInputName () inline static
Definition at line 79 of file MetasoundAutoConverterNode.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::BindInputs(), and Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory::CreateOperator().
GetOutputName()
template<typename FromDataType, typename ToDataType> const FVertexName & Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetOutputName () inline static
Definition at line 85 of file MetasoundAutoConverterNode.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::BindOutputs().
Field Documentation
Factory
template<typename FromDataType, typename ToDataType> FOperatorFactorySharedRef Metasound::TAutoConverterNode< FromDataType, ToDataType >::Factory private
Definition at line 233 of file MetasoundAutoConverterNode.h.
Referenced by TAutoConverterNode(), and GetDefaultOperatorFactory().
The documentation for this class was generated from the following file:
MetasoundAutoConverterNode.h