Unreal Engine 5.6 C++ API: FNameMap Class Reference
FNameMap Class Reference
#include "MappedName.h"
Public Types
using RangedForConstIteratorType = TArray<FDisplayNameEntryId>::RangedForConstIteratorType
Public Member Functions
RangedForConstIteratorType begin () const
RangedForConstIteratorType end () const
FMinimalName GetMinimalName (const FMappedName &MappedName) const
FName GetName (const FMappedName &MappedName) const
void Load (FArchive &Ar, FMappedName::EType NameMapType)
int32 Num () const
bool TryGetName (const FMappedName &MappedName, FName &OutName) const
Private Attributes
TArray< FDisplayNameEntryId > NameEntries
FMappedName::EType NameMapType = FMappedName::EType::Global
Detailed Description
Definition at line 116 of file MappedName.h.
Member Typedef Documentation
RangedForConstIteratorType
using FNameMap::RangedForConstIteratorType = TArray<FDisplayNameEntryId>::RangedForConstIteratorType
Definition at line 155 of file MappedName.h.
Member Function Documentation
begin()
RangedForConstIteratorType FNameMap::begin () const inline
Definition at line 156 of file MappedName.h.
References NameEntries.
end()
RangedForConstIteratorType FNameMap::end () const inline
Definition at line 157 of file MappedName.h.
References NameEntries.
GetMinimalName()
FMinimalName FNameMap::GetMinimalName (const FMappedName & MappedName) const inline
Definition at line 149 of file MappedName.h.
References GetName(), and NameToMinimalName().
GetName()
FName FNameMap::GetName (const FMappedName & MappedName) const inline
Definition at line 126 of file MappedName.h.
References check, FMappedName::GetIndex(), FMappedName::GetNumber(), FMappedName::GetType(), NameEntries, and NameMapType.
Referenced by GetMinimalName().
Load()
void FNameMap::Load (FArchive & Ar, FMappedName::EType NameMapType)
References Ar, and NameMapType.
Num()
int32 FNameMap::Num () const inline
Definition at line 119 of file MappedName.h.
References NameEntries.
TryGetName()
bool FNameMap::TryGetName (const FMappedName & MappedName, FName & OutName) const inline
Definition at line 134 of file MappedName.h.
References check, FMappedName::GetIndex(), FMappedName::GetNumber(), FMappedName::GetType(), NameEntries, and NameMapType.
Field Documentation
NameEntries
TArray<FDisplayNameEntryId> FNameMap::NameEntries private
Definition at line 160 of file MappedName.h.
Referenced by begin(), end(), GetName(), Num(), and TryGetName().
NameMapType
FMappedName::EType FNameMap::NameMapType = FMappedName::EType::Global private
Definition at line 161 of file MappedName.h.
Referenced by GetName(), Load(), and TryGetName().
The documentation for this class was generated from the following file:
MappedName.h