Unreal Engine 5.6 C++ API: UE::AccessDetection Namespace Reference
UE::AccessDetection Namespace Reference
Namespaces
namespace Private
Data Structures
class FScope
Detects access to global core systems while running deterministic code that should be isolated from the local environment.
Enumerations
enum class EType : uint32 { None = 0 , File = 1 << 0 , UE_DEPRECATED =(5.4, "Use FConfigAccessTracking in ConfigAccessTracking instead") = 1 << 1 , CVar = 1 << 2 }
Functions
ENUM_CLASS_FLAGS (EType)
FORCEINLINE void ReportAccess (EType Type)
Enumeration Type Documentation
EType
enum class UE::AccessDetection::EType : uint32 strong
Enumerator
None
File
UE_DEPRECATED
CVar
Definition at line 10 of file AccessDetection.h.
Function Documentation
ENUM_CLASS_FLAGS()
UE::AccessDetection::ENUM_CLASS_FLAGS (EType)
ReportAccess()
FORCEINLINE void UE::AccessDetection::ReportAccess (EType Type)
Definition at line 31 of file AccessDetection.h.
References FORCEINLINE, UE::AccessDetection::Private::GNumLiveScopes, and UE::AccessDetection::Private::ReportCurrentThreadAccess().
Referenced by TConsoleVariableData< T >::GetReferenceOnAnyThread(), TConsoleVariableData< T >::GetValueOnAnyThread(), TConsoleVariableData< T >::GetValueOnGameThread(), and TConsoleVariableData< T >::GetValueOnRenderThread().