Unreal Engine 5.6 C++ API: FTexture Class Reference
FTexture Class Reference
A textures resource.
#include "RenderResource.h"
Public Member Functions
RENDERCORE_API FTexture ()
RENDERCORE_API FTexture (const FTexture &)
RENDERCORE_API FTexture (FTexture &&)
virtual RENDERCORE_API ~FTexture ()
virtual RENDERCORE_API FString GetFriendlyName () const override
virtual RENDERCORE_API uint32 GetSizeX () const
Returns the width of the texture in pixels.
virtual RENDERCORE_API uint32 GetSizeY () const
Returns the height of the texture in pixels.
virtual RENDERCORE_API uint32 GetSizeZ () const
Returns the depth of the texture in pixels.
const FTextureRHIRef & GetTextureRHI ()
RENDERCORE_API FTexture & operator= (const FTexture &Other)
RENDERCORE_API FTexture & operator= (FTexture &&Other)
virtual RENDERCORE_API void ReleaseRHI () override
Releases the RHI resources used by this resource.
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
bool bGreyScaleFormat = false
bGreyScaleFormat indicates the texture is actually in R channel but should be read as Grey (replicate R to RGBA) this is set from CompressionSettings, not PixelFormat this is only used by Editor/Debug shaders, not real game materials, which use SamplerType from MaterialExpressions
bool bIgnoreGammaConversions = false
true if the texture is in the same gamma space as the intended rendertarget (e.g.
bool bSRGB = false
Is the pixel data in this texture sRGB?
FSamplerStateRHIRef DeferredPassSamplerStateRHI
Sampler state to be used in deferred passes when discontinuities in ddx / ddy would cause too blurry of a mip to be used.
double LastRenderTime = -FLT_MAX
The last time the texture has been bound.
FMipBiasFade MipBiasFade
Base values for fading in/out mip-levels.
FSamplerStateRHIRef SamplerStateRHI
The sampler state to use for the texture.
FTextureRHIRef TextureRHI
The texture's RHI resource.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Static Protected Member Functions
static RENDERCORE_API FRHISamplerState * GetOrCreateSamplerState (const FSamplerStateInitializerRHI &Initializer)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Detailed Description
A textures resource.
Definition at line 350 of file RenderResource.h.
Constructor & Destructor Documentation
FTexture() [1/3]
RENDERCORE_API FTexture::FTexture ()
Referenced by FTexture(), FTexture(), operator=(), and operator=().
~FTexture()
virtual RENDERCORE_API FTexture::~FTexture () virtual
FTexture() [2/3]
RENDERCORE_API FTexture::FTexture (const FTexture &)
References FTexture().
FTexture() [3/3]
RENDERCORE_API FTexture::FTexture (FTexture &&)
References FTexture().
Member Function Documentation
GetFriendlyName()
virtual RENDERCORE_API FString FTexture::GetFriendlyName () const override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FRenderResource.
Reimplemented in FPlanarReflectionRenderTarget.
GetOrCreateSamplerState()
RENDERCORE_API FRHISamplerState * FTexture::GetOrCreateSamplerState (const FSamplerStateInitializerRHI & Initializer) static protected
Referenced by FPlanarReflectionRenderTarget::InitRHI().
GetSizeX()
virtual RENDERCORE_API uint32 FTexture::GetSizeX () const virtual
Returns the width of the texture in pixels.
Reimplemented in FPlanarReflectionRenderTarget, FSkyTextureCubeResource, FSlateTextureRenderTarget2DResource, FStreamableTextureResource, FTexture2DDynamicResource, FTextureRenderTarget2DArrayResource, FTextureRenderTarget2DResource, FTextureRenderTargetCubeResource, FTextureRenderTargetResource, FTextureRenderTargetVolumeResource, and FVirtualTexture2DResource.
Referenced by UVolumeTexture::GetSurfaceWidth().
GetSizeY()
virtual RENDERCORE_API uint32 FTexture::GetSizeY () const virtual
Returns the height of the texture in pixels.
Reimplemented in FPlanarReflectionRenderTarget, FSkyTextureCubeResource, FSlateTextureRenderTarget2DResource, FStreamableTextureResource, FTexture2DDynamicResource, FTextureRenderTarget2DArrayResource, FTextureRenderTarget2DResource, FTextureRenderTargetCubeResource, FTextureRenderTargetResource, FTextureRenderTargetVolumeResource, and FVirtualTexture2DResource.
Referenced by UVolumeTexture::GetSurfaceHeight().
GetSizeZ()
virtual RENDERCORE_API uint32 FTexture::GetSizeZ () const virtual
Returns the depth of the texture in pixels.
Reimplemented in FStreamableTextureResource, and FTextureRenderTargetVolumeResource.
Referenced by UVolumeTexture::GetSurfaceDepth().
GetTextureRHI()
const FTextureRHIRef & FTexture::GetTextureRHI () inline
Definition at line 398 of file RenderResource.h.
References TextureRHI.
operator=() [1/2]
RENDERCORE_API FTexture & FTexture::operator= (const FTexture & Other)
References FTexture(), and Other.
operator=() [2/2]
RENDERCORE_API FTexture & FTexture::operator= (FTexture && Other)
References FTexture(), and Other.
ReleaseRHI()
virtual RENDERCORE_API void FTexture::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
Reimplemented in FSkyTextureCubeResource, FSlateTextureRenderTarget2DResource, FStreamableTextureResource, FTexture2DDynamicResource, FTextureRenderTarget2DArrayResource, FTextureRenderTarget2DResource, FTextureRenderTargetCubeResource, FTextureRenderTargetVolumeResource, FTextureWithSRV, and FVirtualTexture2DResource.
Referenced by FSkyTextureCubeResource::ReleaseRHI().
Field Documentation
bGreyScaleFormat
bool FTexture::bGreyScaleFormat = false
bGreyScaleFormat indicates the texture is actually in R channel but should be read as Grey (replicate R to RGBA) this is set from CompressionSettings, not PixelFormat this is only used by Editor/Debug shaders, not real game materials, which use SamplerType from MaterialExpressions
Definition at line 373 of file RenderResource.h.
bIgnoreGammaConversions
bool FTexture::bIgnoreGammaConversions = false
true if the texture is in the same gamma space as the intended rendertarget (e.g.
screenshots). The texture will have sRGB==false and bIgnoreGammaConversions==true, causing a non-sRGB texture lookup and no gamma-correction in the shader.
This was only ever checked in the Canvas renderer, not the standard Material shader path. It is no longer set or checked.
Definition at line 384 of file RenderResource.h.
bSRGB
bool FTexture::bSRGB = false
Is the pixel data in this texture sRGB?
Definition at line 389 of file RenderResource.h.
DeferredPassSamplerStateRHI
FSamplerStateRHIRef FTexture::DeferredPassSamplerStateRHI
Sampler state to be used in deferred passes when discontinuities in ddx / ddy would cause too blurry of a mip to be used.
Definition at line 361 of file RenderResource.h.
LastRenderTime
double FTexture::LastRenderTime = -FLT_MAX mutable
The last time the texture has been bound.
Definition at line 364 of file RenderResource.h.
MipBiasFade
FMipBiasFade FTexture::MipBiasFade
Base values for fading in/out mip-levels.
Definition at line 367 of file RenderResource.h.
SamplerStateRHI
FSamplerStateRHIRef FTexture::SamplerStateRHI
The sampler state to use for the texture.
Definition at line 358 of file RenderResource.h.
Referenced by FPlanarReflectionRenderTarget::InitRHI().
TextureRHI
FTextureRHIRef FTexture::TextureRHI
The texture's RHI resource.
Definition at line 355 of file RenderResource.h.
Referenced by FTextureResource::GetCurrentMipCount(), FTextureResource::GetTexture2DArrayRHI(), FTextureResource::GetTexture2DRHI(), FTextureResource::GetTexture3DRHI(), GetTextureRHI(), FPlanarReflectionRenderTarget::InitRHI(), and FTextureResource::IsTextureRHIPartiallyResident().
The documentation for this class was generated from the following file:
RenderResource.h