Unreal Engine 5.6 C++ API: UE::MovieScene::TTupleGroupingPolicy< ComponentTypes > Struct Template Reference
UE::MovieScene::TTupleGroupingPolicy< ComponentTypes > Struct Template Reference
A simple grouping policy that uses a tuple of component values as the group key.
#include "MovieSceneEntityGroupingSystem.h"
Public Types
using GroupKeyType = TTuple<ComponentTypes...>
Public Member Functions
bool GetGroupKey (ComponentTypes... InComponents, GroupKeyType &OutGroupKey)
bool OnObjectsReplaced (GroupKeyType &InOutKey, const TMap< UObject *, UObject * > &ReplacementMap)
Detailed Description
template<typename... ComponentTypes>
struct UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >
A simple grouping policy that uses a tuple of component values as the group key.
Definition at line 292 of file MovieSceneEntityGroupingSystem.h.
Member Typedef Documentation
GroupKeyType
template<typename... ComponentTypes> using UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >::GroupKeyType = TTuple<ComponentTypes...>
Definition at line 294 of file MovieSceneEntityGroupingSystem.h.
Member Function Documentation
GetGroupKey()
template<typename... ComponentTypes> bool UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >::GetGroupKey (ComponentTypes... InComponents, GroupKeyType & OutGroupKey) inline
Definition at line 296 of file MovieSceneEntityGroupingSystem.h.
References MakeTuple().
OnObjectsReplaced()
template<typename... ComponentTypes> bool UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >::OnObjectsReplaced (GroupKeyType & InOutKey, const TMap< UObject *, UObject * > & ReplacementMap) inline
Definition at line 302 of file MovieSceneEntityGroupingSystem.h.
References UE::MovieScene::Private::ReplaceGroupKeyObjectElement(), and VisitTupleElements().
The documentation for this struct was generated from the following file:
MovieSceneEntityGroupingSystem.h