Unreal Engine 5.6 C++ API: FSimpleDelegateGraphTask Class Reference
FSimpleDelegateGraphTask Class Reference
Task class for simple delegate based tasks.
#include "TaskGraphInterfaces.h"
Public Member Functions
FSimpleDelegateGraphTask (const FDelegate &InTaskDeletegate, const TStatId StatId, ENamedThreads::Type InDesiredThread)
Task constructor.
DECLARE_DELEGATE (FDelegate)
void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
ENamedThreads::Type GetDesiredThread ()
Public Member Functions inherited from FCustomStatIDGraphTaskBase
FCustomStatIDGraphTaskBase (const TStatId &StatId)
Constructor.
FORCEINLINE TStatId GetStatId () const
Gets stat id for this task.
Static Public Member Functions
static FGraphEventRef CreateAndDispatchWhenReady (const FDelegate &InTaskDeletegate, const TStatId &&InStatId, const FGraphEventRef &InPrerequisite, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Create a task and dispatch it when the prerequisites are complete.
static FGraphEventRef CreateAndDispatchWhenReady (const FDelegate &InTaskDeletegate, const TStatId InStatId, const FGraphEventArray *InPrerequisites=NULL, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Create a task and dispatch it when the prerequisites are complete.
static ESubsequentsMode::Type GetSubsequentsMode ()
Data Fields
const ENamedThreads::Type DesiredThread
Thread to run delegate on.
FDelegate TaskDelegate
Delegate to fire when task runs.
Detailed Description
Task class for simple delegate based tasks.
This is less efficient than a custom task, doesn't provide the task arguments, doesn't allow specification of the current thread, etc.
Definition at line 940 of file TaskGraphInterfaces.h.
Constructor & Destructor Documentation
FSimpleDelegateGraphTask()
FSimpleDelegateGraphTask::FSimpleDelegateGraphTask (const FDelegate & InTaskDeletegate, const TStatId StatId, ENamedThreads::Type InDesiredThread) inline
Task constructor.
Parameters
InTaskDelegate - delegate to execute when the prerequisites are complete
StatId The stat id for this task.
InDesiredThread - Thread to run on
Definition at line 966 of file TaskGraphInterfaces.h.
References FCustomStatIDGraphTaskBase::FCustomStatIDGraphTaskBase(), DesiredThread, and TaskDelegate.
Member Function Documentation
CreateAndDispatchWhenReady() [1/2]
FGraphEventRef FSimpleDelegateGraphTask::CreateAndDispatchWhenReady (const FDelegate & InTaskDeletegate, const TStatId && InStatId, const FGraphEventRef & InPrerequisite, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Create a task and dispatch it when the prerequisites are complete.
Parameters
InTaskDelegate - delegate to execute when the prerequisites are complete
InStatId - StatId of task for debugging or analysis tools
InPrerequisite - Handle for a single prerequisite for this task
InDesiredThread - Thread to run on
Returns
completion handle for the new task
Definition at line 993 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, check, CreateAndDispatchWhenReady(), and TRefCountPtr< ReferencedType >::GetReference().
CreateAndDispatchWhenReady() [2/2]
FGraphEventRef FSimpleDelegateGraphTask::CreateAndDispatchWhenReady (const FDelegate & InTaskDeletegate, const TStatId InStatId, const FGraphEventArray * InPrerequisites = NULL, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Create a task and dispatch it when the prerequisites are complete.
Parameters
InTaskDelegate - delegate to execute when the prerequisites are complete
InStatId - StatId of task for debugging or analysis tools
InPrerequisites - Handles for prerequisites for this task, can be NULL if there are no prerequisites
InDesiredThread - Thread to run on
Returns
completion handle for the new task
Definition at line 981 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, TGraphTask< TTask >::FConstructor::ConstructAndDispatchWhenReady(), and TGraphTask< TTask >::CreateTask().
Referenced by CreateAndDispatchWhenReady().
DECLARE_DELEGATE()
FSimpleDelegateGraphTask::DECLARE_DELEGATE (FDelegate)
DoTask()
void FSimpleDelegateGraphTask::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline
Definition at line 956 of file TaskGraphInterfaces.h.
References TaskDelegate.
GetDesiredThread()
ENamedThreads::Type FSimpleDelegateGraphTask::GetDesiredThread () inline
Definition at line 950 of file TaskGraphInterfaces.h.
References DesiredThread.
GetSubsequentsMode()
ESubsequentsMode::Type FSimpleDelegateGraphTask::GetSubsequentsMode () inline static
Definition at line 954 of file TaskGraphInterfaces.h.
References ESubsequentsMode::TrackSubsequents.
Field Documentation
DesiredThread
const ENamedThreads::Type FSimpleDelegateGraphTask::DesiredThread
Thread to run delegate on.
Definition at line 948 of file TaskGraphInterfaces.h.
Referenced by FSimpleDelegateGraphTask(), and GetDesiredThread().
TaskDelegate
FDelegate FSimpleDelegateGraphTask::TaskDelegate
Delegate to fire when task runs.
Definition at line 946 of file TaskGraphInterfaces.h.
Referenced by FSimpleDelegateGraphTask(), and DoTask().
The documentation for this class was generated from the following file:
TaskGraphInterfaces.h