Unreal Engine 5.6 C++ API: FPropertyPermissionList Class Reference
FPropertyPermissionList Class Reference
#include "PropertyPermissionList.h"
Data Structures
struct FPermissionListUpdate
Public Member Functions
void AddPermissionList (TSoftObjectPtr< const UStruct > Struct, const FNamePermissionList &PermissionList, const EPropertyPermissionListRules Rules, const TConstArrayView< FName > InAdditionalOwnerNames)
Add a set of rules for a specific base UStruct to determine which properties are visible in all details panels.
void AddToAllowList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Add a specific property to a UStruct's AllowList.
void AddToAllowList (TSoftObjectPtr< const UStruct > Struct, const TArray< FName > &PropertyNames, const FName Owner)
Add a list of properties to a UStruct's AllowList.
void AddToDenyList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Add a specific property to a UStruct's DenyList.
void ClearCache ()
Clear CachedPropertyPermissionList to cause the PermissionListed property list to be regenerated next time it's queried.
void ClearPermissionList ()
Remove all rules.
bool DoesDetailTreeNodePassFilter (const UStruct *ObjectStruct, TSharedRef< FDetailTreeNode > DetailTreeNode)
Checks if a given detail tree node passes the filters.
bool DoesPropertyPassFilter (const UStruct *ObjectStruct, FName PropertyName) const
Checks if a property passes the PermissionList/DenyList filtering specified by PropertyPermissionLists This should be relatively fast as it maintains a flattened cache of all inherited PermissionLists for every UStruct (which is generated lazily).
const TMap< TSoftObjectPtr< const UStruct >, FPropertyPermissionListEntry > & GetRawPermissionList () const
Gets a read-only copy of the original, un-flattened PermissionList.
bool HasFiltering (const UStruct *ObjectStruct) const
Checks if the provided struct has any entries in the allow, deny and deny all lists and returns true in that case.
bool HasSpecificList (const UStruct *ObjectStruct) const
bool IsEnabled () const
Controls whether DoesPropertyPassFilter always returns true or performs property-based filtering.
bool IsSpecificPropertyAllowListed (const UStruct *ObjectStruct, FName PropertyName) const
Check whether a property exists on the PermissionList for a specific Struct - this will return false if the property is AllowListed on a parent Struct.
bool IsSpecificPropertyDenyListed (const UStruct *ObjectStruct, FName PropertyName) const
Check whether a property exists on the DenyList for a specific Struct - this will return false if the property is DenyListed on a parent Struct.
void RegisterCustomDetailsTreeNodePermissionDelegate (TSoftObjectPtr< const UStruct > Struct, FCustomDetailTreeNodePermissionDelegate InDelegate)
Registers a delegate that is capable of handling more advanced use cases, such as details panel rows whose identifiers are created dynamically.
void RemoveFromAllowList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Remove a specific property from a UStruct's AllowList.
void RemoveFromDenyList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Remove a specific property from a UStruct's DenyList.
void RemovePermissionList (TSoftObjectPtr< const UStruct > Struct)
Remove a set of rules for a specific base UStruct to determine which properties are visible in all details panels.
void SetEnabled (bool bEnable, bool bAnnounce=true)
Turn on or off the property PermissionList.
UE_DEPRECATED (5.5, "Call AddPermissionList with additional required arguments instead.") void AddPermissionList(TSoftObjectPtr< const UStruct > Struct
Add a set of rules for a specific base UStruct to determine which properties are visible in all details panels.
void UnregisterCustomDetailsTreeNodePermissionDelegate (TSoftObjectPtr< const UStruct > Struct)
void UnregisterOwner (const FName Owner)
Unregister an owner from all permission lists currently stored.
Data Fields
bool bSuppressUpdateDelegate = false
If true, PermissionListUpdatedDelegate will not broadcast when modifying the permission lists.
const FNamePermissionList & PermissionList
FSimpleMulticastDelegate PermissionListEnabledDelegate
When the entire PermissionList is enabled or disabled.
FPermissionListUpdated PermissionListUpdatedDelegate
When the PermissionList or DenyList for any struct was added to or removed from.
const FNamePermissionList const EPropertyPermissionListRules Rules = EPropertyPermissionListRules::UseExistingPermissionList)
Protected Member Functions
FPropertyPermissionList ()
~FPropertyPermissionList ()
Private Member Functions
void ClearCacheAndBroadcast (TSoftObjectPtr< const UStruct > ObjectStruct=nullptr, FName OwnerName=NAME_None)
const FNamePermissionList & GetCachedPermissionListForStruct (const UStruct *Struct) const
Get or create the cached PermissionList for a specific UStruct.
const FNamePermissionList & GetCachedPermissionListForStructHelper (const UStruct *Struct, bool &bInOutShouldAllowListAllProperties) const
void RegisterOnBlueprintCompiled ()
bool Tick (float DeltaTime)
Private Attributes
bool bEnablePermissionList = false
Whether DoesPropertyPassFilter should perform its PermissionList check or always return true.
TMap< TWeakObjectPtr< const UStruct >, FPropertyPermissionListEntry > CachedPropertyPermissionList
Lazily-constructed combined cache of both the flattened class PermissionList and struct PermissionList.
TMap< TSoftObjectPtr< const UStruct >, FCustomDetailTreeNodePermissionDelegate > CustomDetailTreeNodePermissionDelegates
FTSTicker::FDelegateHandle OnTickHandle
Handle for our tick function.
TSet< FPermissionListUpdate > PendingUpdates
TMap< TSoftObjectPtr< const UStruct >, FPropertyPermissionListEntry > RawPropertyPermissionList
Stores assigned PermissionLists from AddPermissionList(), which are later flattened and stored in CachedPropertyPermissionList.
Friends
uint32 GetTypeHash (const FPermissionListUpdate &PermisisonList)
bool operator== (const FPermissionListUpdate &A, const FPermissionListUpdate &B)
Detailed Description
Definition at line 52 of file PropertyPermissionList.h.
Constructor & Destructor Documentation
FPropertyPermissionList()
FPropertyPermissionList::FPropertyPermissionList () protected
~FPropertyPermissionList()
FPropertyPermissionList::~FPropertyPermissionList () protected
Member Function Documentation
AddPermissionList()
void FPropertyPermissionList::AddPermissionList (TSoftObjectPtr< const UStruct > Struct, const FNamePermissionList & PermissionList, const EPropertyPermissionListRules Rules, const TConstArrayView< FName > InAdditionalOwnerNames)
Add a set of rules for a specific base UStruct to determine which properties are visible in all details panels.
References AddPermissionList(), PermissionList, Rules, and Struct.
Referenced by AddPermissionList().
AddToAllowList() [1/2]
void FPropertyPermissionList::AddToAllowList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Add a specific property to a UStruct's AllowList.
References AddToAllowList(), Owner, PropertyName, and Struct.
Referenced by AddToAllowList(), and AddToAllowList().
AddToAllowList() [2/2]
void FPropertyPermissionList::AddToAllowList (TSoftObjectPtr< const UStruct > Struct, const TArray< FName > & PropertyNames, const FName Owner)
Add a list of properties to a UStruct's AllowList.
References AddToAllowList(), Owner, and Struct.
AddToDenyList()
void FPropertyPermissionList::AddToDenyList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Add a specific property to a UStruct's DenyList.
References AddToDenyList(), Owner, PropertyName, and Struct.
Referenced by AddToDenyList().
ClearCache()
void FPropertyPermissionList::ClearCache ()
Clear CachedPropertyPermissionList to cause the PermissionListed property list to be regenerated next time it's queried.
ClearCacheAndBroadcast()
void FPropertyPermissionList::ClearCacheAndBroadcast (TSoftObjectPtr< const UStruct > ObjectStruct = nullptr, FName OwnerName = NAME_None) private
ClearPermissionList()
void FPropertyPermissionList::ClearPermissionList ()
Remove all rules.
References ClearPermissionList().
Referenced by ClearPermissionList().
DoesDetailTreeNodePassFilter()
bool FPropertyPermissionList::DoesDetailTreeNodePassFilter (const UStruct * ObjectStruct, TSharedRef< FDetailTreeNode > DetailTreeNode)
Checks if a given detail tree node passes the filters.
This is more flexible than the above function but should only be considered for advanced use cases, such as dynamically generated rows from customizations that don't fit the structure of simply checking against an FName.
DoesPropertyPassFilter()
bool FPropertyPermissionList::DoesPropertyPassFilter (const UStruct * ObjectStruct, FName PropertyName) const
Checks if a property passes the PermissionList/DenyList filtering specified by PropertyPermissionLists This should be relatively fast as it maintains a flattened cache of all inherited PermissionLists for every UStruct (which is generated lazily).
References PropertyName.
GetCachedPermissionListForStruct()
const FNamePermissionList & FPropertyPermissionList::GetCachedPermissionListForStruct (const UStruct * Struct) const private
Get or create the cached PermissionList for a specific UStruct.
References Struct.
GetCachedPermissionListForStructHelper()
const FNamePermissionList & FPropertyPermissionList::GetCachedPermissionListForStructHelper (const UStruct * Struct, bool & bInOutShouldAllowListAllProperties) const private
References Struct.
GetRawPermissionList()
const TMap< TSoftObjectPtr< const UStruct >, FPropertyPermissionListEntry > & FPropertyPermissionList::GetRawPermissionList () const inline
Gets a read-only copy of the original, un-flattened PermissionList.
Definition at line 118 of file PropertyPermissionList.h.
References RawPropertyPermissionList.
HasFiltering()
bool FPropertyPermissionList::HasFiltering (const UStruct * ObjectStruct) const
Checks if the provided struct has any entries in the allow, deny and deny all lists and returns true in that case.
HasSpecificList()
bool FPropertyPermissionList::HasSpecificList (const UStruct * ObjectStruct) const
IsEnabled()
bool FPropertyPermissionList::IsEnabled () const inline
Controls whether DoesPropertyPassFilter always returns true or performs property-based filtering.
Definition at line 89 of file PropertyPermissionList.h.
References bEnablePermissionList, and IsEnabled().
Referenced by IsEnabled().
IsSpecificPropertyAllowListed()
bool FPropertyPermissionList::IsSpecificPropertyAllowListed (const UStruct * ObjectStruct, FName PropertyName) const
Check whether a property exists on the PermissionList for a specific Struct - this will return false if the property is AllowListed on a parent Struct.
References PropertyName.
IsSpecificPropertyDenyListed()
bool FPropertyPermissionList::IsSpecificPropertyDenyListed (const UStruct * ObjectStruct, FName PropertyName) const
Check whether a property exists on the DenyList for a specific Struct - this will return false if the property is DenyListed on a parent Struct.
References PropertyName.
RegisterCustomDetailsTreeNodePermissionDelegate()
void FPropertyPermissionList::RegisterCustomDetailsTreeNodePermissionDelegate (TSoftObjectPtr< const UStruct > Struct, FCustomDetailTreeNodePermissionDelegate InDelegate)
Registers a delegate that is capable of handling more advanced use cases, such as details panel rows whose identifiers are created dynamically.
References RegisterCustomDetailsTreeNodePermissionDelegate(), and Struct.
Referenced by RegisterCustomDetailsTreeNodePermissionDelegate().
RegisterOnBlueprintCompiled()
void FPropertyPermissionList::RegisterOnBlueprintCompiled () private
RemoveFromAllowList()
void FPropertyPermissionList::RemoveFromAllowList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Remove a specific property from a UStruct's AllowList.
References Owner, PropertyName, RemoveFromAllowList(), and Struct.
Referenced by RemoveFromAllowList().
RemoveFromDenyList()
void FPropertyPermissionList::RemoveFromDenyList (TSoftObjectPtr< const UStruct > Struct, const FName PropertyName, const FName Owner)
Remove a specific property from a UStruct's DenyList.
References Owner, PropertyName, RemoveFromDenyList(), and Struct.
Referenced by RemoveFromDenyList().
RemovePermissionList()
void FPropertyPermissionList::RemovePermissionList (TSoftObjectPtr< const UStruct > Struct)
Remove a set of rules for a specific base UStruct to determine which properties are visible in all details panels.
References RemovePermissionList(), and Struct.
Referenced by RemovePermissionList().
SetEnabled()
void FPropertyPermissionList::SetEnabled (bool bEnable, bool bAnnounce = true)
Turn on or off the property PermissionList.
DoesPropertyPassFilter will always return true if disabled. Optionally the change can be announced through a broadcast, which is typically recommended, but may not be needed if the permission list is only temporary enabled, e.g. during saving.
Tick()
bool FPropertyPermissionList::Tick (float DeltaTime) private
References DeltaTime.
UE_DEPRECATED()
FPropertyPermissionList::UE_DEPRECATED (5. 5, "Call AddPermissionList with additional required arguments instead.") const
Add a set of rules for a specific base UStruct to determine which properties are visible in all details panels.
UnregisterCustomDetailsTreeNodePermissionDelegate()
void FPropertyPermissionList::UnregisterCustomDetailsTreeNodePermissionDelegate (TSoftObjectPtr< const UStruct > Struct)
References Struct, and UnregisterCustomDetailsTreeNodePermissionDelegate().
Referenced by UnregisterCustomDetailsTreeNodePermissionDelegate().
UnregisterOwner()
void FPropertyPermissionList::UnregisterOwner (const FName Owner)
Unregister an owner from all permission lists currently stored.
References Owner, and UnregisterOwner().
Referenced by UnregisterOwner().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPermissionListUpdate & PermisisonList) friend
operator==
bool operator== (const FPermissionListUpdate & A, const FPermissionListUpdate & B) friend
References A, and B.
Field Documentation
bEnablePermissionList
bool FPropertyPermissionList::bEnablePermissionList = false private
Whether DoesPropertyPassFilter should perform its PermissionList check or always return true.
Definition at line 136 of file PropertyPermissionList.h.
Referenced by IsEnabled().
bSuppressUpdateDelegate
bool FPropertyPermissionList::bSuppressUpdateDelegate = false
If true, PermissionListUpdatedDelegate will not broadcast when modifying the permission lists.
Definition at line 124 of file PropertyPermissionList.h.
CachedPropertyPermissionList
TMap<TWeakObjectPtr<const UStruct>, FPropertyPermissionListEntry> FPropertyPermissionList::CachedPropertyPermissionList mutable private
Lazily-constructed combined cache of both the flattened class PermissionList and struct PermissionList.
Definition at line 154 of file PropertyPermissionList.h.
CustomDetailTreeNodePermissionDelegates
TMap<TSoftObjectPtr<const UStruct>, FCustomDetailTreeNodePermissionDelegate> FPropertyPermissionList::CustomDetailTreeNodePermissionDelegates private
Definition at line 140 of file PropertyPermissionList.h.
OnTickHandle
FTSTicker::FDelegateHandle FPropertyPermissionList::OnTickHandle private
Handle for our tick function.
Definition at line 143 of file PropertyPermissionList.h.
PendingUpdates
TSet< FPermissionListUpdate > FPropertyPermissionList::PendingUpdates private
Definition at line 152 of file PropertyPermissionList.h.
PermissionList
const FNamePermissionList& FPropertyPermissionList::PermissionList
Definition at line 57 of file PropertyPermissionList.h.
Referenced by AddPermissionList(), FHiddenPropertyPermissionList::Get(), and FPropertyEditorPermissionList::Get().
PermissionListEnabledDelegate
FSimpleMulticastDelegate FPropertyPermissionList::PermissionListEnabledDelegate
When the entire PermissionList is enabled or disabled.
Definition at line 86 of file PropertyPermissionList.h.
PermissionListUpdatedDelegate
FPermissionListUpdated FPropertyPermissionList::PermissionListUpdatedDelegate
When the PermissionList or DenyList for any struct was added to or removed from.
Definition at line 83 of file PropertyPermissionList.h.
RawPropertyPermissionList
TMap<TSoftObjectPtr<const UStruct>, FPropertyPermissionListEntry> FPropertyPermissionList::RawPropertyPermissionList private
Stores assigned PermissionLists from AddPermissionList(), which are later flattened and stored in CachedPropertyPermissionList.
Definition at line 139 of file PropertyPermissionList.h.
Referenced by GetRawPermissionList().
Rules
const FNamePermissionList const EPropertyPermissionListRules FPropertyPermissionList::Rules = EPropertyPermissionListRules::UseExistingPermissionList)
Definition at line 57 of file PropertyPermissionList.h.
Referenced by AddPermissionList().
The documentation for this class was generated from the following file:
PropertyPermissionList.h