Unreal Engine 5.6 C++ API: FObjectSaveContextData Struct Reference
FObjectSaveContextData Struct Reference
Data used to provide information about the save parameters during PreSave/PostSave.
#include "ObjectSaveContext.h"
Public Member Functions
FObjectSaveContextData ()
FObjectSaveContextData (const FObjectSaveContextData &Other)
FObjectSaveContextData (FObjectSaveContextData &&Other)
FObjectSaveContextData (UPackage *Package, const ITargetPlatform *InTargetPlatform, const FPackagePath &TargetPath, uint32 InSaveFlags)
FObjectSaveContextData (UPackage *Package, const ITargetPlatform *InTargetPlatform, const TCHAR *InTargetFilename, uint32 InSaveFlags)
Standard constructor; calculates derived fields from the given externally-specified fields.
~FObjectSaveContextData ()
void AddSaveOverride (UObject *Target, FObjectSaveOverride InOverride)
Add a save override to specific object.
void Set (UPackage *Package, const ITargetPlatform *InTargetPlatform, const FPackagePath &TargetPath, uint32 InSaveFlags)
void Set (UPackage *Package, const ITargetPlatform *InTargetPlatform, const TCHAR *InTargetFilename, uint32 InSaveFlags)
Set the fields set by the standard constructor.
Data Fields
bool bBaseClassCalled = false
Call-site enforcement; records whether the base PreSave was called.
bool bCleanupRequired = false
A bool that can be set from PreSave to indicate PostSave needs to take some extra cleanup steps.
bool bDeterminismDebug = false
Applicable only to cook saves: True if the SavePackage call should write extra debug data for debugging cook determinism or incremental cook issues.
bool bOuterConcurrentSave = true
Always true normally.
bool bProceduralSave = false
Set to true when the package is being saved due to a procedural save.
bool bRequestPostSaveSerialization = false
Set to true when the current object being serialized needs to call serialize again in PostSave phase.
bool bSaveSucceeded = true
Set to false if the save failed, before calling any PostSaves.
UE_DEPRECATED(5.6, "Use BuildResultDependencies instead.") TArray< UE UE::Cook::FBuildResultDependenciesMap BuildResultDependencies
Output variable for BuildResult names and their dependencies, reported by AddBuildDependency functions.
bool bUpdatingLoadedPath = false
Set to true when the LoadedPath of the package being saved is being updated.
UE::Cook::ICookInfo * CookInfo = nullptr
The CookInfo providing extended information about the current cook.
UE::Cook::ECookingDLC CookingDLC = UE::Cook::ECookingDLC::Unknown
TArray< FSoftObjectPath > CookRuntimeDependencies
Output variable for runtime dependencies reported by AddRuntimeDependency functions.
UE::Cook::ECookType CookType = UE::Cook::ECookType::Unknown
int32 NumRefPasses = 0
PreSave contract enforcement; records whether PreSave is overridden.
UObject * Object = nullptr
The object the Save event is being called on, if known.
EObjectSaveContextPhase ObjectSaveContextPhase = EObjectSaveContextPhase::Invalid
Set to the appropriate phase when calling Serialize during SavePackage.
uint32 OriginalPackageFlags = 0
Package->GetPackageFlags before the save, or 0 if no package.
IPackageWriter * PackageWriter = nullptr
The PackageWriter passed to SavePackage, may be null.
uint32 SaveFlags = 0
The save flags (ESaveFlags) of the save.
TMap< UObject *, FObjectSaveOverride > SaveOverrides
List of property overrides per object to apply to during save.
FString TargetFilename
The target Filename being saved into (not the temporary file for saving).
const ITargetPlatform * TargetPlatform = nullptr
The target platform of the save, if cooking.
Detailed Description
Data used to provide information about the save parameters during PreSave/PostSave.
Definition at line 69 of file ObjectSaveContext.h.
Constructor & Destructor Documentation
FObjectSaveContextData() [1/5]
FObjectSaveContextData::FObjectSaveContextData ()
Referenced by FObjectSaveContextData(), and FObjectSaveContextData().
~FObjectSaveContextData()
FObjectSaveContextData::~FObjectSaveContextData ()
FObjectSaveContextData() [2/5]
FObjectSaveContextData::FObjectSaveContextData (const FObjectSaveContextData & Other)
References FObjectSaveContextData(), and Other.
FObjectSaveContextData() [3/5]
FObjectSaveContextData::FObjectSaveContextData (FObjectSaveContextData && Other)
References FObjectSaveContextData(), and Other.
FObjectSaveContextData() [4/5]
FObjectSaveContextData::FObjectSaveContextData (UPackage * Package, const ITargetPlatform * InTargetPlatform, const TCHAR * InTargetFilename, uint32 InSaveFlags)
Standard constructor; calculates derived fields from the given externally-specified fields.
References Package.
FObjectSaveContextData() [5/5]
FObjectSaveContextData::FObjectSaveContextData (UPackage * Package, const ITargetPlatform * InTargetPlatform, const FPackagePath & TargetPath, uint32 InSaveFlags)
References Package.
Member Function Documentation
AddSaveOverride()
void FObjectSaveContextData::AddSaveOverride (UObject * Target, FObjectSaveOverride InOverride) inline
Add a save override to specific object.
(i.e. mark certain objects or properties transient for this save)
Definition at line 87 of file ObjectSaveContext.h.
References MoveTemp(), SaveOverrides, and Target.
Set() [1/2]
void FObjectSaveContextData::Set (UPackage * Package, const ITargetPlatform * InTargetPlatform, const FPackagePath & TargetPath, uint32 InSaveFlags)
References Package.
Set() [2/2]
void FObjectSaveContextData::Set (UPackage * Package, const ITargetPlatform * InTargetPlatform, const TCHAR * InTargetFilename, uint32 InSaveFlags)
Set the fields set by the standard constructor.
References Package.
Field Documentation
bBaseClassCalled
bool FObjectSaveContextData::bBaseClassCalled = false
Call-site enforcement; records whether the base PreSave was called.
Definition at line 184 of file ObjectSaveContext.h.
bCleanupRequired
bool FObjectSaveContextData::bCleanupRequired = false
A bool that can be set from PreSave to indicate PostSave needs to take some extra cleanup steps.
Definition at line 177 of file ObjectSaveContext.h.
bDeterminismDebug
bool FObjectSaveContextData::bDeterminismDebug = false
Applicable only to cook saves: True if the SavePackage call should write extra debug data for debugging cook determinism or incremental cook issues.
Definition at line 159 of file ObjectSaveContext.h.
bOuterConcurrentSave
bool FObjectSaveContextData::bOuterConcurrentSave = true
Always true normally.
When a system is executing multiple PreSaves/PostSaves concurrently before a single save, all but the first PreSaves have this set to false. If there are PostSaves they are executed in reverse order, and all but the last PostSave have this set to false.
Definition at line 150 of file ObjectSaveContext.h.
bProceduralSave
bool FObjectSaveContextData::bProceduralSave = false
Set to true when the package is being saved due to a procedural save.
Any save without the possibility of user-generated edits to the package is a procedural save (Cooking, EditorDomain). This allows us to execute transforms that only need to be executed in response to new user data.
Definition at line 137 of file ObjectSaveContext.h.
bRequestPostSaveSerialization
bool FObjectSaveContextData::bRequestPostSaveSerialization = false
Set to true when the current object being serialized needs to call serialize again in PostSave phase.
Definition at line 187 of file ObjectSaveContext.h.
bSaveSucceeded
bool FObjectSaveContextData::bSaveSucceeded = true
Set to false if the save failed, before calling any PostSaves.
Definition at line 153 of file ObjectSaveContext.h.
BuildResultDependencies
UE_DEPRECATED (5.6, "Use BuildResultDependencies instead.") TArray<UE UE::Cook::FBuildResultDependenciesMap FObjectSaveContextData::BuildResultDependencies
Output variable for BuildResult names and their dependencies, reported by AddBuildDependency functions.
Definition at line 166 of file ObjectSaveContext.h.
bUpdatingLoadedPath
bool FObjectSaveContextData::bUpdatingLoadedPath = false
Set to true when the LoadedPath of the package being saved is being updated.
This allows us to update the in-memory package when it is saved in editor to match its new save file.
Definition at line 143 of file ObjectSaveContext.h.
CookInfo
UE::Cook::ICookInfo* FObjectSaveContextData::CookInfo = nullptr
The CookInfo providing extended information about the current cook.
Null if not cooking.
Definition at line 112 of file ObjectSaveContext.h.
CookingDLC
UE::Cook::ECookingDLC FObjectSaveContextData::CookingDLC = UE::Cook::ECookingDLC::Unknown
Definition at line 127 of file ObjectSaveContext.h.
CookRuntimeDependencies
TArray<FSoftObjectPath> FObjectSaveContextData::CookRuntimeDependencies
Output variable for runtime dependencies reported by AddRuntimeDependency functions.
Definition at line 168 of file ObjectSaveContext.h.
CookType
UE::Cook::ECookType FObjectSaveContextData::CookType = UE::Cook::ECookType::Unknown
Definition at line 126 of file ObjectSaveContext.h.
NumRefPasses
int32 FObjectSaveContextData::NumRefPasses = 0
PreSave contract enforcement; records whether PreSave is overridden.
Definition at line 181 of file ObjectSaveContext.h.
Object
UObject* FObjectSaveContextData::Object = nullptr
The object the Save event is being called on, if known.
Definition at line 118 of file ObjectSaveContext.h.
ObjectSaveContextPhase
EObjectSaveContextPhase FObjectSaveContextData::ObjectSaveContextPhase = EObjectSaveContextPhase::Invalid
Set to the appropriate phase when calling Serialize during SavePackage.
Definition at line 130 of file ObjectSaveContext.h.
OriginalPackageFlags
uint32 FObjectSaveContextData::OriginalPackageFlags = 0
Package->GetPackageFlags before the save, or 0 if no package.
Definition at line 124 of file ObjectSaveContext.h.
PackageWriter
IPackageWriter* FObjectSaveContextData::PackageWriter = nullptr
The PackageWriter passed to SavePackage, may be null.
Definition at line 115 of file ObjectSaveContext.h.
SaveFlags
uint32 FObjectSaveContextData::SaveFlags = 0
The save flags (ESaveFlags) of the save.
Definition at line 121 of file ObjectSaveContext.h.
SaveOverrides
TMap<UObject*, FObjectSaveOverride> FObjectSaveContextData::SaveOverrides
List of property overrides per object to apply to during save.
Definition at line 174 of file ObjectSaveContext.h.
Referenced by AddSaveOverride().
TargetFilename
FString FObjectSaveContextData::TargetFilename
The target Filename being saved into (not the temporary file for saving).
The path is in the standard UnrealEngine form - it is as a relative path from the process binary directory. Set to the empty string if the saved bytes are not being saved to a file.
Definition at line 106 of file ObjectSaveContext.h.
TargetPlatform
const ITargetPlatform* FObjectSaveContextData::TargetPlatform = nullptr
The target platform of the save, if cooking.
Null if not cooking.
Definition at line 109 of file ObjectSaveContext.h.
The documentation for this struct was generated from the following file:
ObjectSaveContext.h