Unreal Engine 5.6 C++ API: FLevelInstanceActorDesc Class Reference
FLevelInstanceActorDesc Class Reference
ActorDesc for Actors that are part of a LevelInstanceActor Level.
#include "LevelInstanceActorDesc.h"
Public Member Functions
FLevelInstanceActorDesc ()
virtual ~FLevelInstanceActorDesc () override
virtual void CheckForErrors (const IWorldPartitionActorDescInstanceView *InActorDescView, IStreamingGenerationErrorHandler *ErrorHandler) const override
virtual UActorDescContainer * GetChildContainer () const override
virtual const FWorldPartitionActorFilter * GetChildContainerFilter () const override
virtual EWorldPartitionActorFilterType GetChildContainerFilterType () const
virtual FString GetChildContainerName () const override
virtual FName GetChildContainerPackage () const override
virtual ELevelInstanceRuntimeBehavior GetDesiredRuntimeBehavior () const
virtual bool HasStandaloneHLOD () const override
virtual bool IsChildContainerInstance () const override
Public Member Functions inherited from FWorldPartitionActorDesc
virtual ~FWorldPartitionActorDesc ()
void AddProperty (FName PropertyName, FName PropertyValue=NAME_None)
bool GetActorIsEditorOnly () const
bool GetActorIsEditorOnlyLoadedInPIE () const
bool GetActorIsHLODRelevant () const
bool GetActorIsRuntimeOnly () const
FName GetActorLabel () const
FName GetActorLabelOrName () const
const FString & GetActorLabelString () const
FName GetActorName () const
const FString & GetActorNameString () const
UClass * GetActorNativeClass () const
FName GetActorPackage () const
FSoftObjectPath GetActorSoftPath () const
const FTransform & GetActorTransform () const
FTopLevelAssetPath GetBaseClass () const
FGuid GetContentBundleGuid () const
TArray< FName > GetDataLayers (bool bIncludeExternalDataLayer=true) const
FName GetDisplayClassName () const
const FString & GetDisplayClassNameString () const
FBox GetEditorBounds () const
FName GetExternalDataLayer () const
const FSoftObjectPath & GetExternalDataLayerAsset () const
const FGuid & GetFolderGuid () const
FName GetFolderPath () const
const FGuid & GetGuid () const
FSoftObjectPath GetHLODLayer () const
bool GetIsSpatiallyLoaded () const
bool GetIsSpatiallyLoadedRaw () const
FTopLevelAssetPath GetNativeClass () const
const FGuid & GetParentActor () const
bool GetProperty (FName PropertyName, FName *PropertyValue) const
FBox GetRuntimeBounds () const
FName GetRuntimeGrid () const
virtual const FGuid & GetSceneOutlinerParent () const
const TArray< FName > & GetTags () const
bool HasProperty (FName PropertyName) const
bool IsDefaultActorDesc () const
bool IsListedInSceneOutliner () const
bool IsMainWorldOnly () const
virtual bool IsResaveNeeded () const
bool IsUsingDataLayerAsset () const
bool operator== (const FWorldPartitionActorDesc &Other) const
void SerializeTo (TArray< uint8 > &OutData, FWorldPartitionActorDesc *BaseDesc=nullptr) const
virtual bool ShouldResave (const FWorldPartitionActorDesc *Other) const
Returns true if resaving this actor will have an impact on streaming generation.
FString ToString (EToStringMode Mode=EToStringMode::Compact) const
UE_DEPRECATED (5.1, "SetIsSpatiallyLoadedRaw is deprecated and should not be used.") inline void SetIsSpatiallyLoadedRaw(bool bNewIsSpatiallyLoaded)
UE_DEPRECATED (5.2, "GetBounds is deprecated, GetEditorBounds or GetRuntimeBounds should be used instead.") FBox GetBounds() const
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "GetOrigin is deprecated.") inline FVector GetOrigin() const
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "ShouldValidateRuntimeGrid is deprecated and should not be used") virtual bool ShouldValidateRuntimeGrid() const
UE_DEPRECATED (5.3, "GetLevelPackage is deprecated use GetChildContainerPackage instead") virtual FName GetLevelPackage() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::GetUnloadedReason") FText GetUnloadedReason() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::SetUnloadedReason") void SetUnloadedReason(FText *InUnloadedReason)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::GetDataLayerInstanceNames") TArray< FName > GetDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::HasResolvedDataLayerInstanceNames") inline bool HasResolvedDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsEditorRelevant instead") virtual bool IsEditorRelevant() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsRuntimeRelevant instead") virtual bool IsRuntimeRelevant(const FActorContainerID &InContainerID) const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::SetDataLayerInstanceNames") inline void SetDataLayerInstanceNames(const TArray< FName > &InDataLayerInstanceNames)
UE_DEPRECATED (5.4, "Use GetChildContainerFilter instead") virtual const FWorldPartitionActorFilter *GetContainerFilter() const
UE_DEPRECATED (5.4, "Use GetChildContainerFilterType instead") virtual EWorldPartitionActorFilterType GetContainerFilterType() const
UE_DEPRECATED (5.4, "Use GetChildContainerInstance instead") virtual bool GetContainerInstance(FContainerInstance &OutContainerInstance) const
UE_DEPRECATED (5.4, "Use GetChildContainerPackage instead") virtual FName GetContainerPackage() const
UE_DEPRECATED (5.4, "Use IsChildContainerInstance instead") virtual bool IsContainerInstance() const
UE_DEPRECATED (5.4, "Use SetContainer without World param") virtual void SetContainer(UActorDescContainer *InContainer
Protected Member Functions
virtual UActorDescContainerInstance * CreateChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance) const override
virtual bool Equals (const FWorldPartitionActorDesc *Other) const override
virtual bool GetChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance, FContainerInstance &OutContainerInstance) const override
FTransform GetChildContainerTransform () const
virtual UWorldPartition * GetLoadedChildWorldPartition (const FWorldPartitionActorDescInstance *InActorDescInstance) const override
FLevelInstancePropertyOverrideDesc * GetOverrideDesc () const
virtual uint32 GetSizeOf () const override
virtual void Init (const AActor *InActor) override
virtual void Init (const FWorldPartitionActorDescInitData &DescData) override
virtual void Serialize (FArchive &Ar) override
virtual void SetContainer (UActorDescContainer *InContainer) override
virtual void TransferFrom (const FWorldPartitionActorDesc *From) override
Protected Member Functions inherited from FWorldPartitionActorDesc
FWorldPartitionActorDesc ()
void InitTransientProperties (const FWorldPartitionActorDescInitData &DescData)
virtual bool IsEditorRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const
virtual bool IsRuntimeRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const
void SetEditorBounds (const FBox &InEditorBounds)
void SetRuntimeBounds (const FBox &InRuntimeBounds)
virtual void TransferWorldData (const FWorldPartitionActorDesc *From)
Static Protected Member Functions
static bool ValidateCircularReference (const UActorDescContainerInstance *InParentContainer, FName InChildContainerPackage)
Protected Attributes
bool bHasStandaloneHLOD
bool bIsChildContainerInstance
TWeakObjectPtr< UActorDescContainer > ChildContainer
ELevelInstanceRuntimeBehavior DesiredRuntimeBehavior
FWorldPartitionActorFilter Filter
FSoftObjectPath PropertyOverrideAsset
TSharedPtr< FLevelInstancePropertyOverrideDesc > PropertyOverrideDesc
FSoftObjectPath WorldAsset
Protected Attributes inherited from FWorldPartitionActorDesc
FString ActorDisplayClassNameString
FName ActorLabel
FString ActorLabelString
FName ActorName
FString ActorNameString
UClass * ActorNativeClass
FName ActorPackage
FSoftObjectPath ActorPath
FTransform ActorTransform
FTransform ActorTransformRelative
bool bActorIsEditorOnly
bool bActorIsHLODRelevant
bool bActorIsListedInSceneOutliner
bool bActorIsMainWorldOnly
bool bActorIsRuntimeOnly
FTopLevelAssetPath BaseClass
bool bHasValidRelativeBounds
bool bIsDefaultActorDesc
bool bIsSpatiallyLoaded
bool bIsUsingDataLayerAsset
UActorDescContainer * Container
FGuid ContentBundleGuid
TArray< FName > DataLayers
FBox EditorBounds
FWorldPartitionRelativeBounds EditorBoundsRelative
TArray< FGuid > EditorOnlyReferences
FSoftObjectPath ExternalDataLayerAsset
FGuid FolderGuid
FName FolderPath
FGuid Guid
FSoftObjectPath HLODLayer
FTopLevelAssetPath NativeClass
FGuid ParentActor
FPropertyPairsMap Properties
TArray< FGuid > References
FBox RuntimeBounds
FWorldPartitionRelativeBounds RuntimeBoundsRelative
FName RuntimeGrid
TArray< FName > Tags
Private Member Functions
bool IsChildContainerInstanceInternal () const
void RegisterChildContainer ()
void UnregisterChildContainer ()
void UpdateBounds ()
Additional Inherited Members
Public Types inherited from FWorldPartitionActorDesc
enum class EToStringMode : uint8 {
Guid , Compact , Full , Verbose ,
ForDiff
}
using FActorDescDeprecator = TFunction<void(FArchive&, FWorldPartitionActorDesc*)>
Static Public Member Functions inherited from FWorldPartitionActorDesc
static void Patch (const FWorldPartitionActorDescInitData &DescData, TArray< uint8 > &OutData, FWorldPartitionAssetDataPatcher *InAssetDataPatcher)
static void RegisterActorDescDeprecator (TSubclassOf< AActor > ActorClass, const FActorDescDeprecator &Deprecator)
Data Fields inherited from FWorldPartitionActorDesc
UWorld * InWorldContext
Static Protected Attributes inherited from FWorldPartitionActorDesc
static TMap< TSubclassOf< AActor >, FActorDescDeprecator > Deprecators
Detailed Description
ActorDesc for Actors that are part of a LevelInstanceActor Level.
Definition at line 26 of file LevelInstanceActorDesc.h.
Constructor & Destructor Documentation
FLevelInstanceActorDesc()
FLevelInstanceActorDesc::FLevelInstanceActorDesc ()
Referenced by GetSizeOf().
~FLevelInstanceActorDesc()
virtual FLevelInstanceActorDesc::~FLevelInstanceActorDesc () override virtual
Member Function Documentation
CheckForErrors()
virtual void FLevelInstanceActorDesc::CheckForErrors (const IWorldPartitionActorDescInstanceView * InActorDescView, IStreamingGenerationErrorHandler * ErrorHandler) const override virtual
Reimplemented from FWorldPartitionActorDesc.
CreateChildContainerInstance()
virtual UActorDescContainerInstance * FLevelInstanceActorDesc::CreateChildContainerInstance (const FWorldPartitionActorDescInstance * InActorDescInstance) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDescInstance.
Equals()
virtual bool FLevelInstanceActorDesc::Equals (const FWorldPartitionActorDesc * Other) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDesc(), and Other.
GetChildContainer()
virtual UActorDescContainer * FLevelInstanceActorDesc::GetChildContainer () const inline override virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 41 of file LevelInstanceActorDesc.h.
References check, ChildContainer, and IsChildContainerInstance().
GetChildContainerFilter()
virtual const FWorldPartitionActorFilter * FLevelInstanceActorDesc::GetChildContainerFilter () const inline override virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 37 of file LevelInstanceActorDesc.h.
References Filter.
GetChildContainerFilterType()
virtual EWorldPartitionActorFilterType FLevelInstanceActorDesc::GetChildContainerFilterType () const inline virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 34 of file LevelInstanceActorDesc.h.
References IsChildContainerInstance(), Loading, and None.
GetChildContainerInstance()
virtual bool FLevelInstanceActorDesc::GetChildContainerInstance (const FWorldPartitionActorDescInstance * InActorDescInstance, FContainerInstance & OutContainerInstance) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDescInstance.
GetChildContainerName()
virtual FString FLevelInstanceActorDesc::GetChildContainerName () const override virtual
Reimplemented from FWorldPartitionActorDesc.
GetChildContainerPackage()
virtual FName FLevelInstanceActorDesc::GetChildContainerPackage () const inline override virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 35 of file LevelInstanceActorDesc.h.
References WorldAsset.
GetChildContainerTransform()
FTransform FLevelInstanceActorDesc::GetChildContainerTransform () const protected
GetDesiredRuntimeBehavior()
virtual ELevelInstanceRuntimeBehavior FLevelInstanceActorDesc::GetDesiredRuntimeBehavior () const inline virtual
Definition at line 44 of file LevelInstanceActorDesc.h.
References DesiredRuntimeBehavior.
GetLoadedChildWorldPartition()
virtual UWorldPartition * FLevelInstanceActorDesc::GetLoadedChildWorldPartition (const FWorldPartitionActorDescInstance * InActorDescInstance) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDescInstance, and FWorldPartitionActorDesc::UWorldPartition.
GetOverrideDesc()
FLevelInstancePropertyOverrideDesc * FLevelInstanceActorDesc::GetOverrideDesc () const inline protected
Definition at line 58 of file LevelInstanceActorDesc.h.
References PropertyOverrideDesc.
GetSizeOf()
virtual uint32 FLevelInstanceActorDesc::GetSizeOf () const inline override protected virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 51 of file LevelInstanceActorDesc.h.
References FLevelInstanceActorDesc().
HasStandaloneHLOD()
virtual bool FLevelInstanceActorDesc::HasStandaloneHLOD () const inline override virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 43 of file LevelInstanceActorDesc.h.
References bHasStandaloneHLOD.
Init() [1/2]
virtual void FLevelInstanceActorDesc::Init (const AActor * InActor) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::AActor.
Init() [2/2]
virtual void FLevelInstanceActorDesc::Init (const FWorldPartitionActorDescInitData & DescData) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
IsChildContainerInstance()
virtual bool FLevelInstanceActorDesc::IsChildContainerInstance () const override virtual
Reimplemented from FWorldPartitionActorDesc.
Referenced by GetChildContainer(), and GetChildContainerFilterType().
IsChildContainerInstanceInternal()
bool FLevelInstanceActorDesc::IsChildContainerInstanceInternal () const private
RegisterChildContainer()
void FLevelInstanceActorDesc::RegisterChildContainer () private
Serialize()
virtual void FLevelInstanceActorDesc::Serialize (FArchive & Ar) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References Ar.
SetContainer()
virtual void FLevelInstanceActorDesc::SetContainer (UActorDescContainer * InContainer) override protected virtual
References InContainer.
TransferFrom()
virtual void FLevelInstanceActorDesc::TransferFrom (const FWorldPartitionActorDesc * From) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDesc().
UnregisterChildContainer()
void FLevelInstanceActorDesc::UnregisterChildContainer () private
UpdateBounds()
void FLevelInstanceActorDesc::UpdateBounds () private
ValidateCircularReference()
bool FLevelInstanceActorDesc::ValidateCircularReference (const UActorDescContainerInstance * InParentContainer, FName InChildContainerPackage) static protected
Field Documentation
bHasStandaloneHLOD
bool FLevelInstanceActorDesc::bHasStandaloneHLOD protected
Definition at line 68 of file LevelInstanceActorDesc.h.
Referenced by HasStandaloneHLOD().
bIsChildContainerInstance
bool FLevelInstanceActorDesc::bIsChildContainerInstance protected
Definition at line 67 of file LevelInstanceActorDesc.h.
ChildContainer
TWeakObjectPtr<UActorDescContainer> FLevelInstanceActorDesc::ChildContainer protected
Definition at line 64 of file LevelInstanceActorDesc.h.
Referenced by GetChildContainer().
DesiredRuntimeBehavior
ELevelInstanceRuntimeBehavior FLevelInstanceActorDesc::DesiredRuntimeBehavior protected
Definition at line 62 of file LevelInstanceActorDesc.h.
Referenced by GetDesiredRuntimeBehavior().
Filter
FWorldPartitionActorFilter FLevelInstanceActorDesc::Filter protected
Definition at line 66 of file LevelInstanceActorDesc.h.
Referenced by GetChildContainerFilter().
PropertyOverrideAsset
FSoftObjectPath FLevelInstanceActorDesc::PropertyOverrideAsset protected
Definition at line 70 of file LevelInstanceActorDesc.h.
PropertyOverrideDesc
TSharedPtr<FLevelInstancePropertyOverrideDesc> FLevelInstanceActorDesc::PropertyOverrideDesc protected
Definition at line 71 of file LevelInstanceActorDesc.h.
Referenced by GetOverrideDesc().
WorldAsset
FSoftObjectPath FLevelInstanceActorDesc::WorldAsset protected
Definition at line 61 of file LevelInstanceActorDesc.h.
Referenced by GetChildContainerPackage().
The documentation for this class was generated from the following file:
LevelInstanceActorDesc.h