Unreal Engine 5.6 C++ API: FIoBatch Class Reference
FIoBatch Class Reference final
I/O batch.
#include "IoDispatcher.h"
Public Member Functions
FIoBatch ()
FIoBatch (FIoBatch &&Other)
~FIoBatch ()
void Issue ()
void IssueAndDispatchSubsequents (FGraphEventRef Event)
void IssueAndTriggerEvent (FEvent *Event)
void IssueWithCallback (TFunction< void()> &&Callback)
FIoBatch & operator= (FIoBatch &&Other)
FIoRequest Read (const FIoChunkId &Chunk, FIoReadOptions Options, int32 Priority)
FIoRequest ReadWithCallback (const FIoChunkId &ChunkId, const FIoReadOptions &Options, int32 Priority, FIoReadCallback &&Callback)
Private Member Functions
FIoBatch (FIoDispatcherImpl &InDispatcher)
FIoRequestImpl * ReadInternal (const FIoChunkId &ChunkId, const FIoReadOptions &Options, int32 Priority)
Private Attributes
FIoDispatcherImpl * Dispatcher
FIoRequestImpl * HeadRequest = nullptr
FIoRequestImpl * TailRequest = nullptr
Friends
class FIoDispatcher
class FIoDispatcherImpl
class FIoRequestStats
Detailed Description
I/O batch.
This is a primitive used to group I/O requests for synchronization purposes
Definition at line 284 of file IoDispatcher.h.
Constructor & Destructor Documentation
FIoBatch() [1/3]
FIoBatch::FIoBatch ()
Referenced by FIoBatch(), and operator=().
FIoBatch() [2/3]
FIoBatch::FIoBatch (FIoBatch && Other)
References FIoBatch(), and Other.
~FIoBatch()
FIoBatch::~FIoBatch ()
FIoBatch() [3/3]
FIoBatch::FIoBatch (FIoDispatcherImpl & InDispatcher) private
References FIoDispatcherImpl.
Member Function Documentation
Issue()
void FIoBatch::Issue ()
IssueAndDispatchSubsequents()
void FIoBatch::IssueAndDispatchSubsequents (FGraphEventRef Event)
References Event.
IssueAndTriggerEvent()
void FIoBatch::IssueAndTriggerEvent (FEvent * Event)
References Event.
IssueWithCallback()
void FIoBatch::IssueWithCallback (TFunction< void()> && Callback)
operator=()
FIoBatch & FIoBatch::operator= (FIoBatch && Other)
References FIoBatch(), and Other.
Read()
FIoRequest FIoBatch::Read (const FIoChunkId & Chunk, FIoReadOptions Options, int32 Priority)
ReadInternal()
FIoRequestImpl * FIoBatch::ReadInternal (const FIoChunkId & ChunkId, const FIoReadOptions & Options, int32 Priority) private
ReadWithCallback()
FIoRequest FIoBatch::ReadWithCallback (const FIoChunkId & ChunkId, const FIoReadOptions & Options, int32 Priority, FIoReadCallback && Callback)
Friends And Related Symbol Documentation
FIoDispatcher
friend class FIoDispatcher friend
Definition at line 286 of file IoDispatcher.h.
References FIoDispatcher.
Referenced by FIoDispatcher.
FIoDispatcherImpl
friend class FIoDispatcherImpl friend
Definition at line 287 of file IoDispatcher.h.
References FIoDispatcherImpl.
Referenced by FIoBatch(), and FIoDispatcherImpl.
FIoRequestStats
friend class FIoRequestStats friend
Definition at line 288 of file IoDispatcher.h.
References FIoRequestStats.
Referenced by FIoRequestStats.
Field Documentation
Dispatcher
FIoDispatcherImpl* FIoBatch::Dispatcher private
Definition at line 307 of file IoDispatcher.h.
HeadRequest
FIoRequestImpl* FIoBatch::HeadRequest = nullptr private
Definition at line 308 of file IoDispatcher.h.
TailRequest
FIoRequestImpl* FIoBatch::TailRequest = nullptr private
Definition at line 309 of file IoDispatcher.h.
The documentation for this class was generated from the following file:
IoDispatcher.h