Unreal Engine 5.6 C++ API: UE::Math::TBox2< T > Struct Template Reference
UE::Math::TBox2< T > Struct Template Reference
#include "Box2D.h"
Public Types
using FReal = T
Public Member Functions
TBox2 ()=default
Default constructor (no initialization).
TBox2 (const TArray< TVector2< T > > &Points)
Creates and initializes a new box from an array of points.
template<typename FArg UE_REQUIRES>
TBox2 (const TBox2< FArg > &From)
TBox2 (const TVector2< T > &InMin, const TVector2< T > &InMax)
Creates and initializes a new box from the specified parameters.
TBox2 (const TVector2< T > *Points, const int32 Count)
Creates and initializes a new box from the given set of points.
TBox2 (EForceInit)
Creates and initializes a new box.
FORCEINLINE T ComputeSquaredDistanceToPoint (const TVector2< T > &Point) const
Calculates the distance of a point to this box.
bool Equals (const TBox2< T > &Other, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks for equality with error-tolerant comparison.
TBox2< T > ExpandBy (const T W) const
Increase the bounding box volume.
TBox2< T > ExpandBy (const TVector2< T > &V) const
Returns a box of increased size.
T GetArea () const
Gets the box area.
TVector2< T > GetCenter () const
Gets the box's center point.
void GetCenterAndExtents (TVector2< T > &center, TVector2< T > &Extents) const
Get the center and extents.
FORCEINLINE TVector2< T > GetClosestPointTo (const TVector2< T > &Point) const
Calculates the closest point on or inside the box to a given point in space.
TVector2< T > GetExtent () const
Gets the box extents around the center.
TVector2< T > GetSize () const
Gets the box size.
void Init ()
Set the initial values of the bounding box to Zero.
FORCEINLINE bool Intersect (const TBox2< T > &other) const
Checks whether the given box intersects this box.
bool IsInside (const TBox2< T > &Other) const
Checks whether the given box is fully encapsulated by this box.
bool IsInside (const TVector2< T > &TestPoint) const
Checks whether the given point is inside this box.
bool IsInsideOrOn (const TVector2< T > &TestPoint) const
Checks whether the given point is inside or on this box.
TBox2< T > MoveTo (const TVector2< T > &Destination) const
Returns a box with its center moved to the new destination.
bool operator!= (const TBox2< T > &Other) const
Compares two boxes for inequality.
TBox2< T > operator+ (const TBox2< T > &Other) const
Gets the result of addition to this bounding volume.
TBox2< T > operator+ (const TVector2< T > &Other) const
Gets the result of addition to this bounding volume.
FORCEINLINE TBox2< T > & operator+= (const TBox2< T > &Other)
Adds to this bounding box to include a new bounding volume.
FORCEINLINE TBox2< T > & operator+= (const TVector2< T > &Other)
Adds to this bounding box to include a given point.
bool operator== (const TBox2< T > &Other) const
Compares two boxes for equality.
TVector2< T > & operator[] (int32 Index)
Gets reference to the min or max of this bounding volume.
const TVector2< T > & operator[] (int32 Index) const
Gets reference to the min or max of this bounding volume.
TBox2< T > Overlap (const TBox2< T > &Other) const
Returns the overlap box of two boxes.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
TBox2< T > ShiftBy (const TVector2< T > &Offset) const
Shift bounding box position.
FString ToString () const
Get a textual representation of this box.
Static Public Member Functions
static TBox2< T > BuildAABB (const TVector2< T > &Origin, const TVector2< T > &Extent)
Utility function to build an AABB from Origin and Extent.
Data Fields
bool bIsValid
Holds a flag indicating whether this box is valid.
TVector2< T > Max
Holds the box's maximum point.
TVector2< T > Min
Holds the box's minimum point.
Friends
FArchive & operator<< (FArchive &Ar, TBox2< T > &Box)
Serializes the bounding box.
Detailed Description
template<typename T>
struct UE::Math::TBox2< T >
Definition at line 29 of file Box2D.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TBox2< T >::FReal = T
Definition at line 32 of file Box2D.h.
Constructor & Destructor Documentation
TBox2() [1/6]
template<typename T> UE::Math::TBox2< T >::TBox2 () nodiscard default
Default constructor (no initialization).
Referenced by UE::Math::TBox2< double >::ExpandBy(), UE::Math::TBox2< double >::ExpandBy(), Intersect(), UE::Math::TBox2< double >::MoveTo(), UE::Math::TBox2< double >::operator+(), UE::Math::TBox2< double >::operator+(), operator+=(), operator+=(), Overlap(), and UE::Math::TBox2< double >::ShiftBy().
TBox2() [2/6]
template<typename T> UE::Math::TBox2< T >::TBox2 (EForceInit) inline explicit nodiscard
Creates and initializes a new box.
The box extents are initialized to zero and the box is marked as invalid.
Parameters
EForceInit Force Init Enum.
Definition at line 46 of file Box2D.h.
TBox2() [3/6]
template<typename T> UE::Math::TBox2< T >::TBox2 (const TVector2< T > & InMin, const TVector2< T > & InMax) inline nodiscard
Creates and initializes a new box from the specified parameters.
Parameters
InMin The box's minimum point.
InMax The box's maximum point.
Definition at line 46 of file Box2D.h.
TBox2() [4/6]
template<typename T> UE::Math::TBox2< T >::TBox2 (const TVector2< T > * Points, const int32 Count) nodiscard
Creates and initializes a new box from the given set of points.
Parameters
Points Array of Points to create for the bounding volume.
Count The number of points.
Definition at line 482 of file Box2D.h.
References bIsValid, UE::Count, Max, Min, and Points.
TBox2() [5/6]
template<typename T> UE::Math::TBox2< T >::TBox2 (const TArray< TVector2< T > > & Points) nodiscard
Creates and initializes a new box from an array of points.
Parameters
Points Array of Points to create for the bounding volume.
Definition at line 494 of file Box2D.h.
References bIsValid, Max, Min, and Points.
TBox2() [6/6]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TBox2< T >::TBox2 (const TBox2< FArg > & From) inline explicit
Definition at line 469 of file Box2D.h.
Member Function Documentation
BuildAABB()
template<typename T> TBox2< T > UE::Math::TBox2< T >::BuildAABB (const TVector2< T > & Origin, const TVector2< T > & Extent) inline static nodiscard
Utility function to build an AABB from Origin and Extent.
Parameters
Origin The location of the bounding box.
Extent Half size of the bounding box.
Returns
A new axis-aligned bounding box.
Definition at line 417 of file Box2D.h.
ComputeSquaredDistanceToPoint()
template<typename T> FORCEINLINE T UE::Math::TBox2< T >::ComputeSquaredDistanceToPoint (const TVector2< T > & Point) const inline nodiscard
Calculates the distance of a point to this box.
Parameters
Point The point.
Returns
The distance.
Definition at line 206 of file Box2D.h.
Equals()
template<typename T> bool UE::Math::TBox2< T >::Equals (const TBox2< T > & Other, T Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Checks for equality with error-tolerant comparison.
Parameters
Other The box to compare.
Tolerance Error tolerance.
Returns
true if the boxes are equal within specified tolerance, otherwise false.
Definition at line 118 of file Box2D.h.
ExpandBy() [1/2]
template<typename T> TBox2< T > UE::Math::TBox2< T >::ExpandBy (const T W) const inline nodiscard
Increase the bounding box volume.
Parameters
W The size to increase volume by.
Returns
A new bounding box increased in size.
Definition at line 238 of file Box2D.h.
ExpandBy() [2/2]
template<typename T> TBox2< T > UE::Math::TBox2< T >::ExpandBy (const TVector2< T > & V) const inline nodiscard
Returns a box of increased size.
Parameters
V The size to increase the volume by.
Returns
A new bounding box.
Definition at line 249 of file Box2D.h.
GetArea()
template<typename T> T UE::Math::TBox2< T >::GetArea () const inline nodiscard
Gets the box area.
Returns
Box area.
See also
GetCenter, GetCenterAndExtents, GetExtent, GetSize
Definition at line 260 of file Box2D.h.
GetCenter()
template<typename T> TVector2< T > UE::Math::TBox2< T >::GetCenter () const inline nodiscard
Gets the box's center point.
Returns
Th center point.
See also
GetArea, GetCenterAndExtents, GetExtent, GetSize
Definition at line 271 of file Box2D.h.
Referenced by UE::Math::TBox2< double >::MoveTo().
GetCenterAndExtents()
template<typename T> void UE::Math::TBox2< T >::GetCenterAndExtents (TVector2< T > & center, TVector2< T > & Extents) const inline
Get the center and extents.
Parameters
center[out] reference to center point
Extents[out] reference to the extent around the center
See also
GetArea, GetCenter, GetExtent, GetSize
Definition at line 283 of file Box2D.h.
GetClosestPointTo()
template<typename T> FORCEINLINE TVector2< T > UE::Math::TBox2< T >::GetClosestPointTo (const TVector2< T > & Point) const nodiscard
Calculates the closest point on or inside the box to a given point in space.
Parameters
Point The point in space.
Returns
The closest point on or inside the box.
Definition at line 547 of file Box2D.h.
References FORCEINLINE, Max, Min, Point, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
GetExtent()
template<typename T> TVector2< T > UE::Math::TBox2< T >::GetExtent () const inline nodiscard
Gets the box extents around the center.
Returns
Box extents.
See also
GetArea, GetCenter, GetCenterAndExtents, GetSize
Definition at line 304 of file Box2D.h.
Referenced by UE::Math::TBox2< double >::GetCenterAndExtents().
GetSize()
template<typename T> TVector2< T > UE::Math::TBox2< T >::GetSize () const inline nodiscard
Gets the box size.
Returns
Box size.
See also
GetArea, GetCenter, GetCenterAndExtents, GetExtent
Definition at line 316 of file Box2D.h.
Init()
template<typename T> void UE::Math::TBox2< T >::Init () inline
Set the initial values of the bounding box to Zero.
Definition at line 324 of file Box2D.h.
Referenced by UE::Math::TBox2< double >::TBox2().
Intersect()
template<typename T> FORCEINLINE bool UE::Math::TBox2< T >::Intersect (const TBox2< T > & other) const nodiscard
Checks whether the given box intersects this box.
Parameters
other bounding box to test intersection
Returns
true if boxes intersect, false otherwise.
Definition at line 598 of file Box2D.h.
References TBox2(), FORCEINLINE, Max, Min, and Other.
Referenced by Overlap().
IsInside() [1/2]
template<typename T> bool UE::Math::TBox2< T >::IsInside (const TBox2< T > & Other) const inline nodiscard
Checks whether the given box is fully encapsulated by this box.
Parameters
Other The box to test for encapsulation within the bounding volume.
Returns
true if box is inside this volume, false otherwise.
Definition at line 375 of file Box2D.h.
IsInside() [2/2]
template<typename T> bool UE::Math::TBox2< T >::IsInside (const TVector2< T > & TestPoint) const inline nodiscard
Checks whether the given point is inside this box.
Parameters
Point The point to test.
Returns
true if the point is inside this box, otherwise false.
Definition at line 352 of file Box2D.h.
Referenced by UE::Math::TBox2< double >::IsInside().
IsInsideOrOn()
template<typename T> bool UE::Math::TBox2< T >::IsInsideOrOn (const TVector2< T > & TestPoint) const inline nodiscard
Checks whether the given point is inside or on this box.
Parameters
Point The point to test.
Returns
true if point is inside or on this box, otherwise false.
See also
IsInside
Definition at line 364 of file Box2D.h.
MoveTo()
template<typename T> TBox2< T > UE::Math::TBox2< T >::MoveTo (const TVector2< T > & Destination) const inline nodiscard
Returns a box with its center moved to the new destination.
Parameters
Destination The destination point to move center of box to.
Returns
A new bounding box.
Definition at line 397 of file Box2D.h.
operator!=()
template<typename T> bool UE::Math::TBox2< T >::operator!= (const TBox2< T > & Other) const inline nodiscard
Compares two boxes for inequality.
Parameters
Other The other box to compare with.
Returns
true if the boxes are not equal, false otherwise.
Definition at line 106 of file Box2D.h.
operator+() [1/2]
template<typename T> TBox2< T > UE::Math::TBox2< T >::operator+ (const TBox2< T > & Other) const inline nodiscard
Gets the result of addition to this bounding volume.
Parameters
Other The other volume to add to this.
Returns
A new bounding volume.
Definition at line 156 of file Box2D.h.
operator+() [2/2]
template<typename T> TBox2< T > UE::Math::TBox2< T >::operator+ (const TVector2< T > & Other) const inline nodiscard
Gets the result of addition to this bounding volume.
Parameters
Other The other point to add to this.
Returns
A new bounding volume.
Definition at line 137 of file Box2D.h.
operator+=() [1/2]
template<typename T> FORCEINLINE TBox2< T > & UE::Math::TBox2< T >::operator+= (const TBox2< T > & Other)
Adds to this bounding box to include a new bounding volume.
Parameters
Other The bounding volume to increase the bounding volume to.
Returns
Reference to this bounding volume after resizing to include the other bounding volume.
Definition at line 528 of file Box2D.h.
References TBox2(), bIsValid, FORCEINLINE, FMath::Max, Max, FMath::Min, Min, and Other.
operator+=() [2/2]
template<typename T> FORCEINLINE TBox2< T > & UE::Math::TBox2< T >::operator+= (const TVector2< T > & Other)
Adds to this bounding box to include a given point.
Parameters
Other The point to increase the bounding volume to.
Returns
Reference to this bounding box after resizing to include the other point.
Definition at line 507 of file Box2D.h.
References TBox2(), bIsValid, FORCEINLINE, FMath::Max, Max, FMath::Min, Min, and Other.
operator==()
template<typename T> bool UE::Math::TBox2< T >::operator== (const TBox2< T > & Other) const inline nodiscard
Compares two boxes for equality.
Parameters
Other The other box to compare with.
Returns
true if the boxes are equal, false otherwise.
Definition at line 95 of file Box2D.h.
operator[]() [1/2]
template<typename T> TVector2< T > & UE::Math::TBox2< T >::operator[] (int32 Index) inline nodiscard
Gets reference to the min or max of this bounding volume.
Parameters
Index The index into points of the bounding volume.
Returns
A reference to a point of the bounding volume.
Definition at line 167 of file Box2D.h.
operator[]() [2/2]
template<typename T> const TVector2< T > & UE::Math::TBox2< T >::operator[] (int32 Index) const inline nodiscard
Gets reference to the min or max of this bounding volume.
Parameters
Index The index into points of the bounding volume.
Returns
A const reference to a point of the bounding volume.
Definition at line 185 of file Box2D.h.
Overlap()
template<typename T> TBox2< T > UE::Math::TBox2< T >::Overlap (const TBox2< T > & Other) const nodiscard
Returns the overlap box of two boxes.
Parameters
Other The bounding box to test overlap
Returns
the overlap box. Result will be invalid if they don't overlap
Definition at line 576 of file Box2D.h.
References TBox2(), ForceInit, Intersect(), FMath::Max, Max, FMath::Min, Min, Other, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Serialize()
template<typename T> bool UE::Math::TBox2< T >::Serialize (FArchive & Ar) inline
Definition at line 440 of file Box2D.h.
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TBox2< T >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 450 of file Box2D.h.
ShiftBy()
template<typename T> TBox2< T > UE::Math::TBox2< T >::ShiftBy (const TVector2< T > & Offset) const inline nodiscard
Shift bounding box position.
Parameters
The offset vector to shift by.
Returns
A new shifted bounding box.
Definition at line 386 of file Box2D.h.
ToString()
template<typename T> FORCEINLINE FString UE::Math::TBox2< T >::ToString () const nodiscard
Get a textual representation of this box.
Returns
A string describing the box.
Definition at line 614 of file Box2D.h.
References bIsValid, FORCEINLINE, Max, Min, and TEXT.
Friends And Related Symbol Documentation
operator<<
template<typename T> FArchive & operator<< (FArchive & Ar, TBox2< T > & Box) friend
Serializes the bounding box.
Parameters
Ar The archive to serialize into.
Box The box to serialize.
Returns
Reference to the Archive after serialization.
Definition at line 434 of file Box2D.h.
Field Documentation
bIsValid
template<typename T> bool UE::Math::TBox2< T >::bIsValid
Holds a flag indicating whether this box is valid.
Definition at line 41 of file Box2D.h.
Referenced by TBox2(), TBox2(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::operator TBox2< OutRealType >(), operator+=(), operator+=(), and ToString().
Max
template<typename T> TVector2<T> UE::Math::TBox2< T >::Max
Holds the box's maximum point.
Definition at line 38 of file Box2D.h.
Referenced by TBox2(), TBox2(), FSquare2DGridHelper::FGrid2D::ForEachIntersectingCells(), FSquare2DGridHelper::FGrid2D::GetCellCoords(), GetClosestPointTo(), Intersect(), operator+=(), operator+=(), Overlap(), FStereoLayerVS::SetParameters(), and ToString().
Min
template<typename T> TVector2<T> UE::Math::TBox2< T >::Min
Holds the box's minimum point.
Definition at line 35 of file Box2D.h.
Referenced by TBox2(), TBox2(), FSquare2DGridHelper::FGrid2D::ForEachIntersectingCells(), FSquare2DGridHelper::FGrid2D::GetCellCoords(), GetClosestPointTo(), Intersect(), operator+=(), operator+=(), Overlap(), FStereoLayerVS::SetParameters(), and ToString().
The documentation for this struct was generated from the following file:
Box2D.h