Unreal Engine 5.6 C++ API: UAISenseConfig_Sight Class Reference
UAISenseConfig_Sight Class Reference
#include "AISenseConfig_Sight.h"
Private Member Functions
virtual AIMODULE_API TSubclassOf< UAISense > GetSenseImplementation () const override
virtual AIMODULE_API void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
UPROPERTY () FAISenseAffiliationFilter DetectionByAffiliation
UPROPERTY ()) float AutoSuccessRangeFromLastSeenLocation
If not an InvalidRange (which is the default), we will always be able to see the target that has already been seen if they are within this range of their last seen location.
UPROPERTY ()) float LoseSightRadius
Maximum sight distance to see target that has been already seen.
UPROPERTY ()) float NearClippingRadius
Near clipping distance, to be used with point of view backward offset.
UPROPERTY ()) float PeripheralVisionAngleDegrees
How far to the side AI can see, in degrees.
UPROPERTY ()) float PointOfViewBackwardOffset
Point of view move back distance for cone calculation.
GENERATED_UCLASS_BODY() public UPROPERTY ()) float SightRadius
Maximum sight distance to notice a target.
Detailed Description
Definition at line 18 of file AISenseConfig_Sight.h.
Member Function Documentation
GetSenseImplementation()
virtual AIMODULE_API TSubclassOf< UAISense > UAISenseConfig_Sight::GetSenseImplementation () const override private virtual
References GetSenseImplementation().
Referenced by GetSenseImplementation().
PostEditChangeChainProperty()
virtual AIMODULE_API void UAISenseConfig_Sight::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override private virtual
UPROPERTY() [1/7]
UAISenseConfig_Sight::UPROPERTY () private
References Category, config, and UPROPERTY().
UPROPERTY() [2/7]
UAISenseConfig_Sight::UPROPERTY () private
If not an InvalidRange (which is the default), we will always be able to see the target that has already been seen if they are within this range of their last seen location.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [3/7]
UAISenseConfig_Sight::UPROPERTY () private
Maximum sight distance to see target that has been already seen.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [4/7]
UAISenseConfig_Sight::UPROPERTY () private
Near clipping distance, to be used with point of view backward offset.
Will act as a close by awareness and peripheral vision
References Category, config, meta, and UPROPERTY().
UPROPERTY() [5/7]
UAISenseConfig_Sight::UPROPERTY () private
How far to the side AI can see, in degrees.
Use SetPeripheralVisionAngle to change the value at runtime. The value represents the angle measured in relation to the forward vector, not the whole range.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [6/7]
UAISenseConfig_Sight::UPROPERTY () private
Point of view move back distance for cone calculation.
In conjunction with near clipping distance, this will act as a close by awareness and peripheral vision.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [7/7]
GENERATED_UCLASS_BODY() public UAISenseConfig_Sight::UPROPERTY () private
Maximum sight distance to notice a target.
References Category, config, float, and meta.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
AISenseConfig_Sight.h