Unreal Engine 5.6 C++ API: MeshAdapterTransforms Namespace Reference
MeshAdapterTransforms Namespace Reference
A variant of DynamicMesh module's MeshTransforms that is generalized for MeshAdapter-based meshes Unlike a lot of MeshAdapter-based functions, most of these require Set* and *Normal functions to exist on the Adapter Specifically, these apply to any mesh class that implements GetVertex, SetVertex, GetNormal, SetNormal, IsVertex, IsNormal, MaxVertexID, MaxNormalID.
Typedefs
using FFrame3d = UE::Geometry::FFrame3d
Functions
template<class TriangleMeshType>
void ApplyTransform (TriangleMeshType &Mesh, const FTransformSRT3d &Transform)
Apply given Transform to a Mesh.
template<class TriangleMeshType>
void ApplyTransform (TriangleMeshType &Mesh, TFunctionRef< FVector3d(const FVector3d &)> PositionTransform, TFunctionRef< FVector3f(const FVector3f &)> NormalTransform)
Apply given Transform to a Mesh.
template<class TriangleMeshType>
void ApplyTransformInverse (TriangleMeshType &Mesh, const FTransformSRT3d &Transform)
Apply inverse of given Transform to a Mesh.
template<class TriangleMeshType>
void FrameCoordsToWorld (TriangleMeshType &Mesh, const FFrame3d &Frame)
Transform Mesh out of local coordinates of Frame.
template<class TriangleMeshType>
void Translate (TriangleMeshType &Mesh, const FVector3d &Translation)
Apply Translation to vertex positions of Mesh.
template<class TriangleMeshType>
void WorldToFrameCoords (TriangleMeshType &Mesh, const FFrame3d &Frame)
Transform Mesh into local coordinates of Frame.
Detailed Description
A variant of DynamicMesh module's MeshTransforms that is generalized for MeshAdapter-based meshes Unlike a lot of MeshAdapter-based functions, most of these require Set* and *Normal functions to exist on the Adapter Specifically, these apply to any mesh class that implements GetVertex, SetVertex, GetNormal, SetNormal, IsVertex, IsNormal, MaxVertexID, MaxNormalID.
Note that unlike a lot of MeshAdapter things, FDynamicMesh3 will need to be wrapped by an adapter too for anything that changes normals, because the FDynamicMesh3 interface for normals a little too involved to make it the access pattern for the adapter. For now, will leave the FDynamicMesh3 specific version inside the DynamicMesh module (TODO: consider reworking it to just create a tiny shim and call these functions?)
Typedef Documentation
FFrame3d
using MeshAdapterTransforms::FFrame3d = UE::Geometry::FFrame3d
Definition at line 25 of file MeshAdapterTransforms.h.
Function Documentation
ApplyTransform() [1/2]
template<class TriangleMeshType> void MeshAdapterTransforms::ApplyTransform (TriangleMeshType & Mesh, const FTransformSRT3d & Transform)
Apply given Transform to a Mesh.
Modifies Vertex Positions and Normals, and any Per-Triangle Normal Overlays
Definition at line 109 of file MeshAdapterTransforms.h.
References UE::Geometry::Mesh, UE::Geometry::Normal, ParallelFor(), UE::Geometry::Position, and UE::Geometry::Transform.
ApplyTransform() [2/2]
template<class TriangleMeshType> void MeshAdapterTransforms::ApplyTransform (TriangleMeshType & Mesh, TFunctionRef< FVector3d(const FVector3d &)> PositionTransform, TFunctionRef< FVector3f(const FVector3f &)> NormalTransform)
Apply given Transform to a Mesh.
Modifies Vertex Positions and Normals, and any Per-Triangle Normal Overlays
Definition at line 175 of file MeshAdapterTransforms.h.
References UE::Geometry::Mesh, UE::Geometry::Normal, UE::Geometry::Normalized(), ParallelFor(), and UE::Geometry::Position.
ApplyTransformInverse()
template<class TriangleMeshType> void MeshAdapterTransforms::ApplyTransformInverse (TriangleMeshType & Mesh, const FTransformSRT3d & Transform)
Apply inverse of given Transform to a Mesh.
Modifies Vertex Positions and Normals, and any Per-Triangle Normal Overlays
Definition at line 142 of file MeshAdapterTransforms.h.
References UE::Geometry::Mesh, UE::Geometry::Normal, ParallelFor(), UE::Geometry::Position, and UE::Geometry::Transform.
FrameCoordsToWorld()
template<class TriangleMeshType> void MeshAdapterTransforms::FrameCoordsToWorld (TriangleMeshType & Mesh, const FFrame3d & Frame)
Transform Mesh out of local coordinates of Frame.
Definition at line 77 of file MeshAdapterTransforms.h.
References UE::Geometry::Mesh, UE::Geometry::Normal, ParallelFor(), and UE::Geometry::Position.
Translate()
template<class TriangleMeshType> void MeshAdapterTransforms::Translate (TriangleMeshType & Mesh, const FVector3d & Translation)
Apply Translation to vertex positions of Mesh.
Does not modify any other attributes.
Definition at line 31 of file MeshAdapterTransforms.h.
References UE::Geometry::Mesh, ParallelFor(), and Translation.
WorldToFrameCoords()
template<class TriangleMeshType> void MeshAdapterTransforms::WorldToFrameCoords (TriangleMeshType & Mesh, const FFrame3d & Frame)
Transform Mesh into local coordinates of Frame.
Definition at line 47 of file MeshAdapterTransforms.h.
References UE::Geometry::Mesh, UE::Geometry::Normal, ParallelFor(), and UE::Geometry::Position.