Unreal Engine 5.6 C++ API: TWeakPtr< ObjectType, InMode > Class Template Reference
TWeakPtr< ObjectType, InMode > Class Template Reference
TWeakPtr is a non-intrusive reference-counted weak object pointer.
#include "SharedPointer.h"
Public Types
using ElementType = ObjectType
using IntrusiveUnsetOptionalStateType = TWeakPtr
Public Member Functions
TWeakPtr (FIntrusiveUnsetOptionalState)
FORCEINLINE TWeakPtr (SharedPointerInternals::FNullTag *=nullptr)
Constructs an empty TWeakPtr.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr (TSharedPtr< OtherType, Mode > const &InSharedPtr)
Constructs a weak pointer from a shared pointer.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr (TSharedRef< OtherType, Mode > const &InSharedRef)
Constructs a weak pointer from a shared reference.
FORCEINLINE TWeakPtr (TWeakPtr &&InWeakPtr)
FORCEINLINE TWeakPtr (TWeakPtr const &InWeakPtr)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr (TWeakPtr< OtherType, Mode > &&InWeakPtr)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr (TWeakPtr< OtherType, Mode > const &InWeakPtr)
Constructs a weak pointer from a weak pointer of another type.
template<typename OtherType>
FORCEINLINE TWeakPtr (TWeakPtr< OtherType, Mode > const &InWeakPtr, SharedPointerInternals::FConstCastTag)
Special constructor used internally to cast a 'const' weak pointer a 'mutable' pointer.
template<typename OtherType>
FORCEINLINE TWeakPtr (TWeakPtr< OtherType, Mode > const &InWeakPtr, SharedPointerInternals::FStaticCastTag)
Special constructor used internally to statically cast one weak pointer type to another.
FORCEINLINE uint32 GetWeakPtrTypeHash () const
FORCEINLINE bool HasSameObject (const void *InOtherPtr) const
Returns true if the object this weak pointer points to is the same as the specified object pointer.
FORCEINLINE bool IsValid () const
Checks to see if this weak pointer actually has a valid reference to an object.
FORCEINLINE TWeakPtr & operator= (SharedPointerInternals::FNullTag *)
Assignment to a nullptr pointer.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr & operator= (TSharedPtr< OtherType, Mode > const &InSharedPtr)
Assignment operator sets this weak pointer from a shared pointer.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr & operator= (TSharedRef< OtherType, Mode > const &InSharedRef)
Assignment operator sets this weak pointer from a shared reference.
FORCEINLINE TWeakPtr & operator= (TWeakPtr &&InWeakPtr)
FORCEINLINE TWeakPtr & operator= (TWeakPtr const &InWeakPtr)
Assignment operator adds a weak reference to the object referenced by the specified weak pointer.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr & operator= (TWeakPtr< OtherType, Mode > &&InWeakPtr)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TWeakPtr & operator= (TWeakPtr< OtherType, Mode > const &InWeakPtr)
Assignment operator adds a weak reference to the object referenced by the specified weak pointer.
bool operator== (FIntrusiveUnsetOptionalState) const
FORCEINLINE TSharedPtr< ObjectType, Mode > Pin () &&
Converts this weak pointer to a shared pointer that you can use to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the returned shared pointer will not be valid.
FORCEINLINE TSharedPtr< ObjectType, Mode > Pin () const &
Converts this weak pointer to a shared pointer that you can use to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the returned shared pointer will not be valid.
FORCEINLINE void Reset ()
Resets this weak pointer, removing a weak reference to the object.
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
static constexpr ESPMode Mode = InMode
Private Attributes
ObjectType * Object
The object we have a weak reference to.
SharedPointerInternals::FWeakReferencer< Mode > WeakReferenceCount
Interface to the reference counter for this object.
Friends
template<class OtherType, ESPMode OtherMode>
class TWeakPtr
template<class OtherType, ESPMode OtherMode>
class TSharedPtr
Detailed Description
template<class ObjectType, ESPMode InMode>
class TWeakPtr< ObjectType, InMode >
TWeakPtr is a non-intrusive reference-counted weak object pointer.
This weak pointer will be conditionally thread-safe when the optional Mode template argument is set to ThreadSafe.
Definition at line 1241 of file SharedPointer.h.
Member Typedef Documentation
ElementType
template<class ObjectType, ESPMode InMode> using TWeakPtr< ObjectType, InMode >::ElementType = ObjectType
Definition at line 1244 of file SharedPointer.h.
IntrusiveUnsetOptionalStateType
template<class ObjectType, ESPMode InMode> using TWeakPtr< ObjectType, InMode >::IntrusiveUnsetOptionalStateType = TWeakPtr
Definition at line 1513 of file SharedPointer.h.
Constructor & Destructor Documentation
TWeakPtr() [1/10]
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (SharedPointerInternals::FNullTag * = nullptr) inline
Constructs an empty TWeakPtr.
Definition at line 1249 of file SharedPointer.h.
TWeakPtr() [2/10]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TSharedRef< OtherType, Mode > const & InSharedRef) inline
Constructs a weak pointer from a shared reference.
Parameters
InSharedRef The shared reference to create a weak pointer from
Definition at line 1265 of file SharedPointer.h.
TWeakPtr() [3/10]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TSharedPtr< OtherType, Mode > const & InSharedPtr) inline
Constructs a weak pointer from a shared pointer.
Parameters
InSharedPtr The shared pointer to create a weak pointer from
Definition at line 1280 of file SharedPointer.h.
TWeakPtr() [4/10]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TWeakPtr< OtherType, Mode > const & InWeakPtr, SharedPointerInternals::FStaticCastTag) inline
Special constructor used internally to statically cast one weak pointer type to another.
You should never call this constructor directly. Instead, use the StaticCastWeakPtr() function. This constructor creates a weak pointer as a weak reference to an existing weak pointer after statically casting that pointer's object. This constructor is needed for static casts.
Parameters
InWeakPtr The weak pointer whose object we should create an additional reference to
Definition at line 1295 of file SharedPointer.h.
TWeakPtr() [5/10]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TWeakPtr< OtherType, Mode > const & InWeakPtr, SharedPointerInternals::FConstCastTag) inline
Special constructor used internally to cast a 'const' weak pointer a 'mutable' pointer.
You should never call this constructor directly. Instead, use the ConstCastWeakPtr() function. This constructor creates a weak pointer as a weak reference to an existing weak pointer after const casting that pointer's object. This constructor is needed for const casts.
Parameters
InWeakPtr The weak pointer whose object we should create an additional reference to
Definition at line 1310 of file SharedPointer.h.
TWeakPtr() [6/10]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TWeakPtr< OtherType, Mode > const & InWeakPtr) inline
Constructs a weak pointer from a weak pointer of another type.
This constructor is intended to allow derived-to-base conversions.
Parameters
InWeakPtr The weak pointer to create a weak pointer from
Definition at line 1326 of file SharedPointer.h.
TWeakPtr() [7/10]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TWeakPtr< OtherType, Mode > && InWeakPtr) inline
Definition at line 1336 of file SharedPointer.h.
TWeakPtr() [8/10]
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TWeakPtr< ObjectType, InMode > const & InWeakPtr) inline
Definition at line 1343 of file SharedPointer.h.
TWeakPtr() [9/10]
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr< ObjectType, InMode >::TWeakPtr (TWeakPtr< ObjectType, InMode > && InWeakPtr) inline
Definition at line 1349 of file SharedPointer.h.
TWeakPtr() [10/10]
template<class ObjectType, ESPMode InMode> TWeakPtr< ObjectType, InMode >::TWeakPtr (FIntrusiveUnsetOptionalState) inline explicit
Definition at line 1515 of file SharedPointer.h.
Member Function Documentation
GetWeakPtrTypeHash()
template<class ObjectType, ESPMode InMode> FORCEINLINE uint32 TWeakPtr< ObjectType, InMode >::GetWeakPtrTypeHash () const inline
Definition at line 1504 of file SharedPointer.h.
Referenced by GetTypeHash().
HasSameObject()
template<class ObjectType, ESPMode InMode> FORCEINLINE bool TWeakPtr< ObjectType, InMode >::HasSameObject (const void * InOtherPtr) const inline nodiscard
Returns true if the object this weak pointer points to is the same as the specified object pointer.
Definition at line 1499 of file SharedPointer.h.
IsValid()
template<class ObjectType, ESPMode InMode> FORCEINLINE bool TWeakPtr< ObjectType, InMode >::IsValid () const inline nodiscard
Checks to see if this weak pointer actually has a valid reference to an object.
Returns
True if the weak pointer is valid and a pin operator would have succeeded
Definition at line 1482 of file SharedPointer.h.
Referenced by Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr(), CleanupPointerMap(), TListTypeTraits< TWeakPtr< T, ESPMode::NotThreadSafe > >::DebugDump(), TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::DebugDump(), operator!=(), operator!=(), FGlobalTabmanager::FindByManager::operator()(), FGlobalTabmanager::FindByTab::operator()(), operator==(), and operator==().
operator=() [1/7]
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr & TWeakPtr< ObjectType, InMode >::operator= (SharedPointerInternals::FNullTag *) inline
Assignment to a nullptr pointer.
Clears this weak pointer's reference.
Definition at line 1360 of file SharedPointer.h.
operator=() [2/7]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr & TWeakPtr< ObjectType, InMode >::operator= (TSharedPtr< OtherType, Mode > const & InSharedPtr) inline
Assignment operator sets this weak pointer from a shared pointer.
Parameters
InSharedPtr The shared pointer used to assign to this weak pointer
Definition at line 1444 of file SharedPointer.h.
operator=() [3/7]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr & TWeakPtr< ObjectType, InMode >::operator= (TSharedRef< OtherType, Mode > const & InSharedRef) inline
Assignment operator sets this weak pointer from a shared reference.
Parameters
InSharedRef The shared reference used to assign to this weak pointer
Definition at line 1428 of file SharedPointer.h.
operator=() [4/7]
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr & TWeakPtr< ObjectType, InMode >::operator= (TWeakPtr< ObjectType, InMode > && InWeakPtr) inline
Definition at line 1378 of file SharedPointer.h.
operator=() [5/7]
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr & TWeakPtr< ObjectType, InMode >::operator= (TWeakPtr< ObjectType, InMode > const & InWeakPtr) inline
Assignment operator adds a weak reference to the object referenced by the specified weak pointer.
Parameters
InWeakPtr The weak pointer for the object to assign
Definition at line 1371 of file SharedPointer.h.
operator=() [6/7]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr & TWeakPtr< ObjectType, InMode >::operator= (TWeakPtr< OtherType, Mode > && InWeakPtr) inline
Definition at line 1410 of file SharedPointer.h.
operator=() [7/7]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TWeakPtr & TWeakPtr< ObjectType, InMode >::operator= (TWeakPtr< OtherType, Mode > const & InWeakPtr) inline
Assignment operator adds a weak reference to the object referenced by the specified weak pointer.
This assignment operator is intended to allow derived-to-base conversions.
Parameters
InWeakPtr The weak pointer for the object to assign
Definition at line 1399 of file SharedPointer.h.
operator==()
template<class ObjectType, ESPMode InMode> bool TWeakPtr< ObjectType, InMode >::operator== (FIntrusiveUnsetOptionalState) const inline
Definition at line 1519 of file SharedPointer.h.
Pin() [1/2]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr< ObjectType, Mode > TWeakPtr< ObjectType, InMode >::Pin () && inline nodiscard
Converts this weak pointer to a shared pointer that you can use to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the returned shared pointer will not be valid.
You should always check to make sure the returned pointer is valid before trying to dereference the shared pointer!
Returns
Shared pointer for this object (will only be valid if still referenced!)
Definition at line 1472 of file SharedPointer.h.
Pin() [2/2]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr< ObjectType, Mode > TWeakPtr< ObjectType, InMode >::Pin () const & inline nodiscard
Converts this weak pointer to a shared pointer that you can use to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the returned shared pointer will not be valid.
You should always check to make sure the returned pointer is valid before trying to dereference the shared pointer!
Returns
Shared pointer for this object (will only be valid if still referenced!)
Definition at line 1459 of file SharedPointer.h.
Referenced by FSlateCachedElementData::AddCachedElement(), UE::Sequencer::ICastable::CastWeakPtr(), UE::Sequencer::ICastable::CastWeakPtrShared(), TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::DebugDump(), TWeakPtr< INavigationToolItem >::HasSameObject(), TListTypeTraits< TWeakPtr< T, ESPMode::NotThreadSafe > >::IsPtrValid(), TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::IsPtrValid(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), FGlobalTabmanager::FindByManager::operator()(), FGlobalTabmanager::FindByTab::operator()(), UE::PixelStreaming2::TObserverVariant< T >::operator->(), TWeakPtr< INavigationToolItem >::operator=(), operator==(), operator==(), operator==(), operator==(), operator==(), and UE::Sequencer::FViewModelVariantIterator::ProjectWeak().
Reset()
template<class ObjectType, ESPMode InMode> FORCEINLINE void TWeakPtr< ObjectType, InMode >::Reset () inline
Resets this weak pointer, removing a weak reference to the object.
If there are no other shared or weak references to the object, then the tracking object will be destroyed.
Definition at line 1491 of file SharedPointer.h.
Referenced by TWeakPtr< INavigationToolItem >::operator=().
Friends And Related Symbol Documentation
TWeakPtr
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TWeakPtr friend
Definition at line 1529 of file SharedPointer.h.
TSharedPtr
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TSharedPtr friend
Definition at line 1532 of file SharedPointer.h.
Referenced by TWeakPtr< INavigationToolItem >::Pin(), and TWeakPtr< INavigationToolItem >::Pin().
Field Documentation
bHasIntrusiveUnsetOptionalState
template<class ObjectType, ESPMode InMode> bool TWeakPtr< ObjectType, InMode >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 1512 of file SharedPointer.h.
Mode
template<class ObjectType, ESPMode InMode> ESPMode TWeakPtr< ObjectType, InMode >::Mode = InMode static constexpr
Definition at line 1245 of file SharedPointer.h.
Object
template<class ObjectType, ESPMode InMode> ObjectType* TWeakPtr< ObjectType, InMode >::Object private
The object we have a weak reference to.
Can be nullptr. Also, it's important to note that because this is a weak reference, the object this pointer points to may have already been destroyed.
Definition at line 1538 of file SharedPointer.h.
WeakReferenceCount
template<class ObjectType, ESPMode InMode> SharedPointerInternals::FWeakReferencer< Mode > TWeakPtr< ObjectType, InMode >::WeakReferenceCount private
Interface to the reference counter for this object.
Note that the actual reference controller object is shared by all shared and weak pointers that refer to the object
Definition at line 1542 of file SharedPointer.h.
Referenced by TWeakPtr< INavigationToolItem >::operator=().
The documentation for this class was generated from the following file:
SharedPointer.h