Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams Struct Reference
UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams Struct Reference
#include "LandscapeEditLayerMergeRenderContext.h"
Public Member Functions
FOnRenderBatchTargetGroupDoneParams (FMergeRenderContext *InMergeRenderContext, const TArrayView< FName > &InTargetLayerGroupLayerNames, const TArrayView< ULandscapeLayerInfoObject * > &InTargetLayerGroupLayerInfos, const TArrayView< FComponentMergeRenderInfo > &InSortedComponentMergeRenderInfos)
UE_DEPRECATED (5.6, "Removed : use MergeRenderContext->GetCurrentRenderBatch()") const FMergeRenderBatch *RenderBatch
UE_DEPRECATED (5.6, "Renamed : use TargetLayerGroupLayerInfos") TArray< ULandscapeLayerInfoObject * > RenderGroupTargetLayerInfos
UE_DEPRECATED (5.6, "Renamed : use TargetLayerGroupLayerNames") TArray< FName > RenderGroupTargetLayerNames
Data Fields
FMergeRenderContext * MergeRenderContext = nullptr
Render context : this is still active in this step and can be used for doing additional renders in the blend render targets, etc.
const TArray< FComponentMergeRenderInfo > SortedComponentMergeRenderInfos
Additional info about the components that have been processed in this batch render.
TArray< ULandscapeLayerInfoObject * > TargetLayerGroupLayerInfos
List of target layer info objects being involved in this step (same size as TargetLayerGroupLayerNames)
TArray< FName > TargetLayerGroupLayerNames
List of target layers being involved in this step.
Detailed Description
Definition at line 320 of file LandscapeEditLayerMergeRenderContext.h.
Constructor & Destructor Documentation
FOnRenderBatchTargetGroupDoneParams()
UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::FOnRenderBatchTargetGroupDoneParams (FMergeRenderContext * InMergeRenderContext, const TArrayView< FName > & InTargetLayerGroupLayerNames, const TArrayView< ULandscapeLayerInfoObject * > & InTargetLayerGroupLayerInfos, const TArrayView< FComponentMergeRenderInfo > & InSortedComponentMergeRenderInfos) inline
Definition at line 322 of file LandscapeEditLayerMergeRenderContext.h.
References UE::Landscape::EditLayers::FMergeRenderContext::FMergeRenderContext(), MergeRenderContext, SortedComponentMergeRenderInfos, TargetLayerGroupLayerInfos, and TargetLayerGroupLayerNames.
Member Function Documentation
UE_DEPRECATED() [1/3]
UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::UE_DEPRECATED (5. 6, "Removed : use MergeRenderContext->GetCurrentRenderBatch()") const
References UE::Landscape::EditLayers::FMergeContext::const, and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::UE_DEPRECATED (5. 6, "Renamed : use TargetLayerGroupLayerInfos")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::UE_DEPRECATED (5. 6, "Renamed : use TargetLayerGroupLayerNames")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
MergeRenderContext
FMergeRenderContext* UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::MergeRenderContext = nullptr
Render context : this is still active in this step and can be used for doing additional renders in the blend render targets, etc.
Definition at line 333 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by FOnRenderBatchTargetGroupDoneParams().
SortedComponentMergeRenderInfos
const TArray<FComponentMergeRenderInfo> UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::SortedComponentMergeRenderInfos
Additional info about the components that have been processed in this batch render.
Definition at line 342 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by FOnRenderBatchTargetGroupDoneParams().
TargetLayerGroupLayerInfos
TArray<ULandscapeLayerInfoObject*> UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::TargetLayerGroupLayerInfos
List of target layer info objects being involved in this step (same size as TargetLayerGroupLayerNames)
Definition at line 339 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by FOnRenderBatchTargetGroupDoneParams().
TargetLayerGroupLayerNames
TArray<FName> UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::TargetLayerGroupLayerNames
List of target layers being involved in this step.
Definition at line 336 of file LandscapeEditLayerMergeRenderContext.h.
Referenced by FOnRenderBatchTargetGroupDoneParams().
The documentation for this struct was generated from the following file:
LandscapeEditLayerMergeRenderContext.h