Unreal Engine 5.6 C++ API: USplineMeshComponent Class Reference
USplineMeshComponent Class Reference abstract
#include "SplineMeshComponent.h"
Public Member Functions
virtual class FStaticMeshStaticLightingMesh * AllocateStaticLightingMesh (int32 LODIndex, const TArray< ULightComponent * > &InRelevantLights) override
Allocates an implementation of FStaticLightingMesh that will handle static lighting for this component.
void ApplyComponentInstanceData (struct FSplineMeshInstanceData *ComponentInstanceData)
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
FTransform CalcSliceTransform (const float DistanceAlong) const
Calculates the spline transform, including roll, scale, and offset along the spline at a specified distance.
FTransform CalcSliceTransformAtSplineOffset (const float Alpha, const float MinT=0.f, const float MaxT=1.0f) const
Calculates the spline transform, including roll, scale, and offset along the spline at a specified alpha interpolation parameter along the spline @Note: This is mirrored to Lightmass::CalcSliceTransform() and LocalVertexShader.usf.
FSplineMeshShaderParams CalculateShaderParams () const
Generates FSplineMeshShaderParams for the current state of the component.
virtual void CollectPSOPrecacheData (const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams) override
Collect all the PSO precache data used by the static mesh component.
virtual bool ContainsPhysicsTriMeshData (bool InUseAllTriData) const override
Interface for checking if the implementing objects contains triangle mesh collision data.
void DestroyBodySetup ()
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
bool GetbNeverNeedsCookedCollisionData () const
Getter for bNeverNeedsCookedCollisionData.
class UBodySetup * GetBodySetup () const
virtual class UBodySetup * GetBodySetup () override
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const override
void GetMeshId (FString &OutMeshId) const
virtual void GetMeshId (FString &OutMeshId) override
An optional string identifying the mesh data.
virtual FBox GetNavigationBounds () const override
virtual bool GetPhysicsTriMeshData (struct FTriMeshCollisionData *CollisionData, bool InUseAllTriData) override
virtual FTransform GetSocketTransform (FName InSocketName, ERelativeTransformSpace TransformSpace=RTS_World) const override
virtual float GetTextureStreamingTransformScale () const override
Get the scale comming form the component, when computing StreamingTexture data.
virtual bool GetTriMeshSizeEstimates (struct FTriMeshCollisionDataEstimates &OutTriMeshEstimates, bool bInUseAllTriData) const override
Returns an estimate of how much data would be retrieved by GetPhysicsTriMeshData.
virtual float GetVirtualTextureMainPassMaxDrawDistance () const override
void InitVertexFactory (int32 InLODIndex, FColorVertexBuffer *InOverrideColorVertexBuffer)
Chooses the forward axis for the spline mesh orientation.
virtual bool IsEditorOnly () const override
bool IsRelevantForSplinePartitioning () const
virtual bool Modify (bool bAlwaysMarkDirty=true) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
void RecreateCollision ()
virtual void Serialize (FArchive &Ar) override
void SetbNeverNeedsCookedCollisionData (bool bInValue)
Setter for bNeverNeedsCookedCollisionData.
virtual bool ShouldRenderSelected () const override
UFUNCTION () 1 float GetBoundaryMax() const
Get the boundary max.
UFUNCTION () 1 float GetBoundaryMin() const
Get the boundary min.
UFUNCTION () 1 float GetEndRoll() const
Get the end roll, in radians.
UFUNCTION () 1 float GetStartRoll() const
Get the start roll, in radians.
UFUNCTION () 1 FVector GetEndPosition() const
Get the end position of spline in local space.
UFUNCTION () 1 FVector GetEndTangent() const
Get the end tangent vector of spline in local space.
UFUNCTION() 1 ESplineMeshAxis UFUNCTION() 1 void SetForwardAxis(ESplineMeshAxis UFUNCTION () 1 FVector GetSplineUpDir() const
Get the forward axis.
UFUNCTION () 1 FVector GetStartPosition() const
Get the start position of spline in local space.
UFUNCTION () 1 FVector GetStartTangent() const
Get the start tangent vector of spline in local space.
UFUNCTION () 1 FVector2D GetEndOffset() const
Get the end offset.
UFUNCTION () 1 FVector2D GetEndScale() const
Get the end scaling.
UFUNCTION () 1 FVector2D GetStartOffset() const
Get the start offset.
UFUNCTION () 1 FVector2D GetStartScale() const
Get the start scaling.
UFUNCTION () 1 void SetBoundaryMax(float InBoundaryMax
Set the boundary max.
UFUNCTION () 1 void SetBoundaryMin(float InBoundaryMin
Set the boundary min.
UFUNCTION () 1 void SetEndOffset(FVector2D EndOffset
Set the end offset.
UFUNCTION () 1 void SetEndPosition(FVector EndPos
Set the end position of spline in local space.
UFUNCTION () 1 void SetEndRollDegrees(float EndRollDegrees
Set the end roll in degrees.
UFUNCTION () 1 void SetEndScale(FVector2D EndScale
Set the end scaling.
UFUNCTION () 1 void SetEndTangent(FVector EndTangent
Set the end tangent vector of spline in local space.
UFUNCTION () 1 void SetSplineUpDir(const FVector &InSplineUpDir
Set the spline up direction.
UFUNCTION () 1 void SetStartAndEnd(FVector StartPos
Set the start and end, position and tangent, all in local space.
UFUNCTION () 1 void SetStartOffset(FVector2D StartOffset
Set the start offset.
UFUNCTION () 1 void SetStartPosition(FVector StartPos
Set the start position of spline in local space.
UFUNCTION () 1 void SetStartRollDegrees(float StartRollDegrees
Set the start roll in degrees.
UFUNCTION () 1 void SetStartScale(FVector2D StartScale
Set the start scaling.
UFUNCTION () 1 void SetStartTangent(FVector StartTangent
Set the start tangent vector of spline in local space.
UFUNCTION () 1 void UpdateMesh()
Update the collision and render state on the spline mesh following changes to its geometry.
UFUNCTION ()) 1 void SetEndRoll(float EndRoll
Set the end roll, in radians.
UFUNCTION ()) 1 void SetStartRoll(float StartRoll
Set the start roll, in radians.
virtual void UpdateBounds () override
void UpdateMesh_Concurrent ()
Same as UpdateMesh, but does not wait until the end of frame and can be used in non-game threads.
void UpdateRenderStateAndCollision ()
Called to notify render thread and possibly collision of a change in spline params or mesh.
virtual bool WantsNegXTriMesh () override
Do we want to create a negative version of this mesh.
Public Member Functions inherited from UStaticMeshComponent
virtual ~UStaticMeshComponent ()
virtual UObject const * AdditionalStatObject () const override
virtual void AddMapBuildDataGUIDs (TSet< FGuid > &InGUIDs) const override
virtual bool AllowsAsyncPhysicsStateCreation () const override
virtual bool AllowsAsyncPhysicsStateDestruction () const override
void ApplyComponentInstanceData (struct FStaticMeshComponentInstanceData *ComponentInstanceData)
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const override
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform) override
virtual void BeginDestroy () override
virtual void BeginPlay () override
virtual bool BuildTextureStreamingDataImpl (ETextureStreamingBuildType BuildType, EMaterialQualityLevel::Type QualityLevel, ERHIFeatureLevel::Type FeatureLevel, TSet< FGuid > &DependentResources, bool &bOutSupportsBuildTextureStreamingData) override
Build the data to compute accuracte StreaminTexture data.
virtual bool CanEditChange (const FProperty *InProperty) const override
virtual bool CanEditSimulatePhysics () override
bool CanMeshPaintTextureColors () const
bool CanMeshPaintVertexColors () const
virtual void CheckForErrors () override
virtual bool ComponentIsTouchingSelectionBox (const FBox &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual bool ComponentIsTouchingSelectionFrustum (const FConvexVolume &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual uint32 ComputeHashTextureStreamingBuiltData () const override
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const override
virtual HHitProxy * CreateMeshHitProxy (int32 SectionIndex, int32 MaterialIndex) const override
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context) override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
DECLARE_DELEGATE_RetVal (const Nanite::FResources *, FOnGetNaniteResources)
Called during scene proxy creation to get the Nanite resource data.
DECLARE_EVENT_OneParam (UStaticMeshComponent, FOnStaticMeshChanged, UStaticMeshComponent *)
Called when the static mesh changes.
virtual bool DoesSocketExist (FName InSocketName) const override
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent) override
int32 GetBlueprintCreatedComponentIndex () const
Get this components index in its parents blueprint created components array (used for matching instance data)
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const override
Get all default LOD sections overlay materials used by a mesh.
virtual FString GetDetailedInfoInternal () const override
virtual float GetDiffuseBoost (int32 ElementIndex) const override
virtual UMaterialInterface * GetEditorMaterial (int32 MaterialIndex) const override
virtual float GetEmissiveBoost (int32 ElementIndex) const override
virtual bool GetEstimatedLightAndShadowMapMemoryUsage (int32 &TextureLightMapMemoryUsage, int32 &TextureShadowMapMemoryUsage, int32 &VertexLightMapMemoryUsage, int32 &VertexShadowMapMemoryUsage, int32 &StaticLightingResolution, bool &bIsUsingTextureMapping, bool &bHasLightmapTexCoords) const
Returns the light and shadow map memory for this primite in its out variables.
virtual void GetEstimatedLightMapResolution (int32 &Width, int32 &Height) const
Returns the lightmap resolution used for this primitive instance in the case of it supporting texture light/ shadow maps.
FORCEINLINE int32 GetForcedLodModel () const
FORCEINLINE bool GetForceNaniteForMasked () const
virtual void GetLightAndShadowMapMemoryUsage (int32 &LightMapMemoryUsage, int32 &ShadowMapMemoryUsage) const override
virtual bool GetLightMapResolution (int32 &Width, int32 &Height) const override
virtual UMaterialInterface * GetMaterial (int32 MaterialIndex) const final
virtual UMaterialInterface * GetMaterialFromCollisionFaceIndex (int32 FaceIndex, int32 &SectionIndex) const override
virtual int32 GetMaterialIndex (FName MaterialSlotName) const override
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty) override
virtual TArray< FName > GetMaterialSlotNames () const override
virtual bool GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo &MaterialData) const override
Get material, UV density and bounds for a given material index.
const FMeshMapBuildData * GetMeshMapBuildData (const FStaticMeshComponentLODInfo &LODInfo, bool bCheckForResourceCluster=true) const
virtual UTexture * GetMeshPaintTexture () const override
Get the mesh paint texture set on this component.
virtual int32 GetMeshPaintTextureCoordinateIndex () const override
Get the default coordinate index for painting to the mesh paint texture on this component.
int32 GetMeshPaintTextureResolution () const
Returns the size to use when creating a mesh paint texture on this component.
FORCEINLINE int32 GetMinLOD () const
UMaterialInterface * GetNaniteAuditMaterial (int32 MaterialIndex) const
virtual const Nanite::FResources * GetNaniteResources () const
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
virtual int32 GetNumMaterials () const override
FORCEINLINE bool GetOverrideMinLOD () const
virtual void GetPrimitiveStats (FPrimitiveStats &PrimitiveStats) const override
virtual bool GetShadowIndirectOnly () const override
class UStaticMeshSocket const * GetSocketByName (FName InSocketName) const
Returns the named socket on the static mesh component.
virtual void GetStaticLightingInfo (FStaticLightingPrimitiveInfo &OutPrimitiveInfo, const TArray< ULightComponent * > &InRelevantLights, const FLightingBuildOptions &Options) override
virtual ELightMapInteractionType GetStaticLightingType () const override
virtual int32 GetStaticLightMapResolution () const override
TObjectPtr< UStaticMesh > GetStaticMesh () const
Get the StaticMesh used by this instance.
virtual void GetStreamingRenderAssetInfo (FStreamingTextureLevelContext &LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > &OutStreamingRenderAssets) const override
Get the StreaminTexture data.
virtual float GetStreamingScale () const override
virtual void GetTextureLightAndShadowMapMemoryUsage (int32 InWidth, int32 InHeight, int32 &OutLightMapMemoryUsage, int32 &OutShadowMapMemoryUsage) const
Get the memory used for texture-based light and shadow maps of the given width and height.
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const final
virtual void GetUsedTextures (TArray< UTexture * > &OutTextures, EMaterialQualityLevel::Type QualityLevel) override
FColor GetWireframeColor () const
Returns the wireframe color to use for this component.
virtual bool HasAnySockets () const override
virtual bool HasLightmapTextureCoordinates () const
Returns true if the static mesh the component uses has valid lightmap texture coordinates.
virtual bool HasValidNaniteData () const
Returns true if the component has valid Nanite render data.
virtual bool HasValidSettingsForStaticLighting (bool bOverlookInvalidComponents) const override
Returns true if the component is static AND has the right static mesh setup to support lightmaps.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn) override
virtual void InitializeComponent () override
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly) override
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform) override
virtual bool IsCompiling () const override
FORCEINLINE bool IsDisallowNanite () const
FORCEINLINE bool IsForceDisableNanite () const
FORCEINLINE bool IsForceNaniteForMasked () const
virtual bool IsHLODRelevant () const override
virtual bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
virtual bool IsNavigationRelevant () const override
virtual bool IsPostLoadThreadSafe () const override
virtual bool IsPrecomputedLightingValid () const override
FORCEINLINE bool IsReverseCulling () const
virtual bool IsShown (const FEngineShowFlags &ShowFlags) const override
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
virtual void OnDestroyPhysicsState () override
virtual FOnGetNaniteResources & OnGetNaniteResources ()
virtual const FOnGetNaniteResources & OnGetNaniteResources () const
void OnMeshRebuild (bool bRenderDataChanged)
virtual FOnStaticMeshChanged & OnStaticMeshChanged ()
virtual UE_DECLARE_COMPONENT_ACTOR_INTERFACE(StaticMeshComponent) protected void OnUnregister () override
virtual void PostApplyToComponent () override
virtual void PostDuplicate (bool bDuplicateForPIE) override
virtual void PostEditImport () override
virtual void PostEditUndo () override
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PostReinitProperties () override
virtual void PostStaticMeshCompilation ()
virtual void PrecachePSOs () override
virtual void PreEditUndo () override
virtual void PreStaticMeshCompilation ()
virtual bool PrestreamMeshLODs (float Seconds) override
virtual void PropagateLightingScenarioChange () override
virtual void QuerySupportedSockets (TArray< FComponentSocketDescription > &OutSockets) const override
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&Callback, int32 LODIdx, float TimeoutSecs, bool bOnStreamIn) override
Register a one-time callback that will be called when criteria met.
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&CallbackStreamingStart, FLODStreamingCallback &&CallbackStreamingDone, float TimeoutStartSecs, float TimeoutDoneSecs) override
Register a one-time callback that will be called when streaming starts or ends.
void ReleaseResources ()
virtual bool RemapActorTextureStreamingBuiltDataToLevel (const class UActorTextureStreamingBuildDataComponent *InActorTextureBuildData) override
void RemoveInstanceVertexColorsFromLOD (int32 LODToRemoveColorsFrom)
Removes instance vertex colors from the specified LOD.
virtual bool RequiresGameThreadEndOfFrameRecreate () const override
virtual void SetCollisionProfileName (FName InCollisionProfileName, bool bUpdateOverlaps=true) override
bool SetLODDataCount (const uint32 MinSize, const uint32 MaxSize)
Add or remove elements to have the size in the specified range.
virtual void SetMeshPaintTexture (UTexture *Texture) override
Set the mesh paint texture on this component.
virtual void SetMeshPaintTextureOverride (UTexture *OverrideTexture) override
Set a transient override mesh paint texture on this component.
virtual bool SetStaticLightingMapping (bool bTextureMapping, int32 ResolutionToUse)
Switches the static mesh component to use either Texture or Vertex static lighting.
virtual bool ShouldCollideWhenPlacing () const override
virtual bool ShouldCreatePhysicsState () const override
virtual bool ShouldCreateRenderState () const override
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const override
virtual bool ShouldRecreateProxyOnUpdateTransform () const override
virtual bool SupportsDefaultCollision ()
Whether or not the component supports default collision from its static mesh asset.
virtual bool SupportsDitheredLODTransitions (ERHIFeatureLevel::Type FeatureLevel)
Whether we can support dithered LOD transitions (default behavior checks all materials).
virtual bool SupportsWorldPositionOffsetVelocity () const override
UE_DEPRECATED (5.6, "Use UPrimitiveComponent::IsFirstPersonRelevant() instead.") bool IsStaticMeshFirstPersonRelevant() const
UFUNCTION () 1 virtual bool SetStaticMesh(class UStaticMesh *NewMesh)
Change the StaticMesh used by this instance.
UFUNCTION () 1 void GetLocalBounds(FVector &Min
Get Local bounds.
UFUNCTION () 1 void OnRep_StaticMesh(class UStaticMesh *OldStaticMesh)
UFUNCTION () 1 void SetDistanceFieldSelfShadowBias(float NewValue)
Sets the component's DistanceFieldSelfShadowBias.
UFUNCTION () 1 void SetEvaluateWorldPositionOffset(bool NewValue)
UFUNCTION () 1 void SetEvaluateWorldPositionOffsetInRayTracing(bool NewValue)
UFUNCTION () 1 void SetForceDisableNanite(bool bInForceDisableNanite)
Force disabling of Nanite rendering.
UFUNCTION () 1 void SetForcedLodModel(int32 NewForcedLodModel)
UFUNCTION () 1 void SetReverseCulling(bool ReverseCulling)
Set forced reverse culling.
UFUNCTION () 1 void SetWorldPositionOffsetDisableDistance(int32 NewValue)
UFUNCTION () bool GetInitialEvaluateWorldPositionOffset()
Get the initial value of bEvaluateWorldPositionOffset.
UFUNCTION () void UpdateInitialEvaluateWorldPositionOffset()
This manually updates the initial value of bEvaluateWorldPositionOffset to be the current value.
void UpdateCollisionFromStaticMesh ()
Sets the BodyInstance to use the mesh's body setup for external collision information.
void UpdateMapBuildDataId ()
void UpdateStaticLightingData ()
UPROPERTY () float DistanceFieldSelfShadowBias
Useful for reducing self shadowing from distance field methods when using world position offset to animate the mesh's vertices.
UPROPERTY () float NanitePixelProgrammableDistance
Used to forcefully disable pixel programmable rasterization of Nanite when the mesh is further than a given distance from the camera.
UPROPERTY () struct FLightmassPrimitiveSettings LightmassSettings
The Lightmass settings for this object.
UPROPERTY () TArray< FStreamingTextureBuildInfo > StreamingTextureData
The list of texture, bounds and scales.
UPROPERTY () TArray< struct FStaticMeshComponentLODInfo > LODData
Static mesh LOD data.
UPROPERTY () TObjectPtr< UTexture > MaterialCacheTexture
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureCooked
Cooked pointer to texture containing mesh painting for this mesh component.
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureOverride
Set this to override the locally stored mesh paint texture.
UPROPERTY ()) float DistanceFieldIndirectShadowMinVisibility
Controls how dark the dynamic indirect shadow can be.
UPROPERTY ()) float StreamingDistanceMultiplier
Allows adjusting the desired streaming distance of streaming textures that uses UV 0.
UPROPERTY ()) int32 OverriddenLightMapRes
Light map resolution to use on this component, used if bOverrideLightMapRes is true and there is a valid StaticMesh.
UPROPERTY()) uint8 bOverrideWireframeColor UPROPERTY() uint8 bOverrideMinLOD UPROPERTY() uint8 bOverrideNavigationExport UPROPERTY() uint8 bForceNavigationObstacle UPROPERTY() uint8 bDisallowMeshPaintPerInstance_DEPRECATED UPROPERTY() uint8 bIgnoreInstanceForTextureStreaming UPROPERTY()) uint8 bOverrideLightMapRes UPROPERTY()) uint8 bCastDistanceFieldIndirectShadow UPROPERTY() uint8 bOverrideDistanceFieldSelfShadowBias UPROPERTY() uint8 bUseSubDivisions UPROPERTY() uint8 bUseDefaultCollision UPROPERTY()) uint8 bSortTriangles UPROPERTY() uint8 bReverseCulling UPROPERTY() uint8 bEnableVertexColorMeshPainting UPROPERTY() uint8 bEnableTextureColorMeshPainting UPROPERTY()) uint8 bOverrideMeshPaintTextureCoordinateIndex UPROPERTY()) uint8 bOverrideMeshPaintTextureResolution UPROPERTY ()) int32 OverriddenMeshPaintTextureCoordinateIndex
If true, WireframeColorOverride will be used.
UPROPERTY ()) int32 OverriddenMeshPaintTextureResolution
The overriden resolution of texture color mesh paint textures on this component.
virtual bool UseNaniteOverrideMaterials () const override
Determines if we use the nanite overrides from any materials.
virtual bool UsesOnlyUnlitMaterials () const override
virtual bool UsesTextureLightmaps (int32 InWidth, int32 InHeight) const
Returns true if the component uses texture lightmaps.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Static Public Member Functions
static FVector GetAxisMask (ESplineMeshAxis::Type InAxis)
Returns a vector which, when componentwise-multiplied by another vector, will zero all the components not corresponding to the supplied ESplineMeshAxis.
static const double & GetAxisValueRef (const FVector3d &InVector, ESplineMeshAxis::Type InAxis)
static const float & GetAxisValueRef (const FVector3f &InVector, ESplineMeshAxis::Type InAxis)
static double & GetAxisValueRef (FVector3d &InVector, ESplineMeshAxis::Type InAxis)
static float & GetAxisValueRef (FVector3f &InVector, ESplineMeshAxis::Type InAxis)
static bool ShouldRenderNaniteSplineMeshes ()
Static Public Member Functions inherited from UStaticMeshComponent
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static const FName GetMemberNameChecked_StaticMesh ()
Helper function to get the FName of the private static mesh member.
Data Fields
bool bUpdateMesh = true)
FVector FVector FVector bool bUpdateMesh = true)
FVector FVector EndPos
FVector FVector FVector EndTangent
FVector StartTangent
Data Fields inherited from UStaticMeshComponent
FVector &Max const
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Member Functions
FBox ComputeDistortedBounds (const FTransform &InLocalToWorld, const FBoxSphereBounds &InMeshBounds, const FBoxSphereBounds *InBoundsToDistort=nullptr) const
Computes the bounding box, in world space, for a given bounding box distorted by the spline in local space.
float ComputeRatioAlongSpline (float DistanceAlong) const
void ComputeVisualMeshSplineTRange (float &MinT, float &MaxT) const
Returns the normalized range on the spline where the visual mesh is located taking custom range into account.
virtual FPrimitiveSceneProxy * CreateStaticMeshSceneProxy (::Nanite::FMaterialAudit &NaniteMaterials, bool bCreateNanite) override
virtual void OnCreatePhysicsState () override
Protected Member Functions inherited from UStaticMeshComponent
void CollectPSOPrecacheDataImpl (const FVertexFactoryType *VFType, const FPSOPrecacheParams &BasePrecachePSOParams, GetPSOVertexElementsFn GetVertexElements, FMaterialInterfacePSOPrecacheParamsList &OutParams) const
virtual FPrimitiveSceneProxy * CreateStaticMeshSceneProxy (Nanite::FMaterialAudit &NaniteMaterials, bool bCreateNanite)
bool ShouldCreateNaniteProxy (Nanite::FMaterialAudit *OutNaniteMaterials=nullptr) const
bool ShouldExportAsObstacle (const UNavCollisionBase &InNavCollision) const
virtual bool SupportsStaticLighting () const override
Whether the component type supports static lighting.
Protected Member Functions inherited from UMeshComponent
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY()) FSplineMeshParams SplineParams
Spline that is used to deform mesh.
void UpdateRenderStateAndCollision_Internal (bool bConcurrent)
UPROPERTY () FGuid CachedMeshBodySetupGuid
Distance at which to disable World Position Offset for an entire instance (0 = Never disable WPO).
UPROPERTY () float SplineBoundaryMax
Maximum coordinate along the spline forward axis which corresponds to end of spline.
UPROPERTY () float SplineBoundaryMin
Minimum coordinate along the spline forward axis which corresponds to start of spline.
UPROPERTY () float VirtualTextureMainPassMaxDrawDistance=0.f
The max draw distance to use in the main pass when also rendering to a runtime virtual texture.
UPROPERTY () FVector SplineUpDir
Axis (in component space) that is used to determine X axis for co-ordinates along spline.
UPROPERTY () TObjectPtr< UBodySetup > BodySetup
Distance at which to disable World Position Offset for an entire instance (0 = Never disable WPO).
Private Attributes
FBox CachedNavigationBounds
Additional Inherited Members
Protected Types inherited from UStaticMeshComponent
using GetPSOVertexElementsFn = TFunctionRef<void(const FStaticMeshLODResources& LODRenderData, int32 LODIndex, bool bSupportsManualVertexFetch, FVertexDeclarationElementList& Elements)>
Shared implementation for all StaticMesh derived components.
Protected Attributes inherited from UStaticMeshComponent
uint8 bInitialEvaluateWorldPositionOffset: 1
Forces this component to always use Nanite for masked materials, even if FNaniteSettings::bAllowMaskedMaterials=false.
uint8 bMipLevelCallbackRegistered: 1
Whether mip callbacks have been registered and need to be removed on destroy.
uint8 bPrecachedPSOs: 1
Whether PrecachedPSOs was called.
uint8 bSupportMeshPainting: 1
Whether mesh painting is supported.
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Detailed Description
Definition at line 118 of file SplineMeshComponent.h.
Member Function Documentation
AllocateStaticLightingMesh()
virtual class FStaticMeshStaticLightingMesh * USplineMeshComponent::AllocateStaticLightingMesh (int32 LODIndex, const TArray< ULightComponent * > & InRelevantLights) override virtual
Allocates an implementation of FStaticLightingMesh that will handle static lighting for this component.
Reimplemented from UStaticMeshComponent.
ApplyComponentInstanceData()
void USplineMeshComponent::ApplyComponentInstanceData (struct FSplineMeshInstanceData * ComponentInstanceData)
CalcBounds()
virtual FBoxSphereBounds USplineMeshComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
Reimplemented from UStaticMeshComponent.
CalcSliceTransform()
FTransform USplineMeshComponent::CalcSliceTransform (const float DistanceAlong) const
Calculates the spline transform, including roll, scale, and offset along the spline at a specified distance.
CalcSliceTransformAtSplineOffset()
FTransform USplineMeshComponent::CalcSliceTransformAtSplineOffset (const float Alpha, const float MinT = 0.f, const float MaxT = 1.0f) const
Calculates the spline transform, including roll, scale, and offset along the spline at a specified alpha interpolation parameter along the spline @Note: This is mirrored to Lightmass::CalcSliceTransform() and LocalVertexShader.usf.
If you update one of these, please update them all!
References Alpha.
CalculateShaderParams()
FSplineMeshShaderParams USplineMeshComponent::CalculateShaderParams () const
Generates FSplineMeshShaderParams for the current state of the component.
CollectPSOPrecacheData()
virtual void USplineMeshComponent::CollectPSOPrecacheData (const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) override virtual
Collect all the PSO precache data used by the static mesh component.
Reimplemented from UStaticMeshComponent.
ComputeDistortedBounds()
FBox USplineMeshComponent::ComputeDistortedBounds (const FTransform & InLocalToWorld, const FBoxSphereBounds & InMeshBounds, const FBoxSphereBounds * InBoundsToDistort = nullptr) const protected
Computes the bounding box, in world space, for a given bounding box distorted by the spline in local space.
By default this method uses the provided mesh bounds that were used to define the spline range [0,1] so all points are expected to stay in that range. In case the bounds to deform are overriden by the optional parameter then linear extrapolation will be applied at the beginning and at the end of the spline for the exceeding part.
Parameters
InLocalToWorld Transformation to apply to the computed bounds to convert them from local space to world space.
InMeshBounds Bounds of the static mesh that get distorted by the spline.
InBoundsToDistort Optional bounds to distort instead of using the mesh bounds.
Returns
Bounds, in world space, of the provided bounds distorted by the spline.
ComputeRatioAlongSpline()
float USplineMeshComponent::ComputeRatioAlongSpline (float DistanceAlong) const protected
ComputeVisualMeshSplineTRange()
void USplineMeshComponent::ComputeVisualMeshSplineTRange (float & MinT, float & MaxT) const protected
Returns the normalized range on the spline where the visual mesh is located taking custom range into account.
ContainsPhysicsTriMeshData()
virtual bool USplineMeshComponent::ContainsPhysicsTriMeshData (bool InUseAllTriData) const override virtual
Interface for checking if the implementing objects contains triangle mesh collision data.
Returns
true if the implementing object contains triangle mesh data, false otherwise
Reimplemented from IInterface_CollisionDataProvider.
References IInterface_CollisionDataProvider::InUseAllTriData.
CreateStaticMeshSceneProxy()
virtual FPrimitiveSceneProxy * USplineMeshComponent::CreateStaticMeshSceneProxy (::Nanite::FMaterialAudit & NaniteMaterials, bool bCreateNanite) override protected virtual
DestroyBodySetup()
void USplineMeshComponent::DestroyBodySetup ()
DoCustomNavigableGeometryExport()
virtual bool USplineMeshComponent::DoCustomNavigableGeometryExport (FNavigableGeometryExport & GeomExport) const override virtual
Reimplemented from UStaticMeshComponent.
GENERATED_UCLASS_BODY()
USplineMeshComponent::GENERATED_UCLASS_BODY () private
Spline that is used to deform mesh.
References Category, meta, and UPROPERTY().
GetAxisMask()
FVector USplineMeshComponent::GetAxisMask (ESplineMeshAxis::Type InAxis) inline static
Returns a vector which, when componentwise-multiplied by another vector, will zero all the components not corresponding to the supplied ESplineMeshAxis.
Definition at line 543 of file SplineMeshComponent.h.
References check, FVector, and UE::Math::TVector< double >::ZeroVector.
Referenced by GetAxisValueRef().
GetAxisValueRef() [1/4]
const double & USplineMeshComponent::GetAxisValueRef (const FVector3d & InVector, ESplineMeshAxis::Type InAxis) inline static
References FVector, GetAxisMask(), and GetAxisValueRef().
Referenced by GetAxisValueRef().
GetAxisValueRef() [2/4]
const float & USplineMeshComponent::GetAxisValueRef (const FVector3f & InVector, ESplineMeshAxis::Type InAxis) inline static
Definition at line 511 of file SplineMeshComponent.h.
References check, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GetAxisValueRef() [3/4]
double & USplineMeshComponent::GetAxisValueRef (FVector3d & InVector, ESplineMeshAxis::Type InAxis) inline static
Definition at line 494 of file SplineMeshComponent.h.
References check, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GetAxisValueRef() [4/4]
float & USplineMeshComponent::GetAxisValueRef (FVector3f & InVector, ESplineMeshAxis::Type InAxis) inline static
Definition at line 527 of file SplineMeshComponent.h.
References check, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GetbNeverNeedsCookedCollisionData()
bool USplineMeshComponent::GetbNeverNeedsCookedCollisionData () const inline
Getter for bNeverNeedsCookedCollisionData.
Definition at line 407 of file SplineMeshComponent.h.
References GetbNeverNeedsCookedCollisionData().
Referenced by GetbNeverNeedsCookedCollisionData().
GetBodySetup() [1/2]
class UBodySetup * USplineMeshComponent::GetBodySetup () const
GetBodySetup() [2/2]
virtual class UBodySetup * USplineMeshComponent::GetBodySetup () override virtual
Reimplemented from UStaticMeshComponent.
GetComponentInstanceData()
virtual TStructOnScope< FActorComponentInstanceData > USplineMeshComponent::GetComponentInstanceData () const override virtual
Reimplemented from UStaticMeshComponent.
GetMeshId() [1/2]
void USplineMeshComponent::GetMeshId (FString & OutMeshId) const
GetMeshId() [2/2]
virtual void USplineMeshComponent::GetMeshId (FString & OutMeshId) override virtual
An optional string identifying the mesh data.
Reimplemented from IInterface_CollisionDataProvider.
GetNavigationBounds()
virtual FBox USplineMeshComponent::GetNavigationBounds () const override virtual
Reimplemented from UStaticMeshComponent.
GetPhysicsTriMeshData()
virtual bool USplineMeshComponent::GetPhysicsTriMeshData (struct FTriMeshCollisionData * CollisionData, bool InUseAllTriData) override virtual
References IInterface_CollisionDataProvider::InUseAllTriData.
GetSocketTransform()
virtual FTransform USplineMeshComponent::GetSocketTransform (FName InSocketName, ERelativeTransformSpace TransformSpace = RTS_World) const override virtual
Reimplemented from UStaticMeshComponent.
GetTextureStreamingTransformScale()
virtual float USplineMeshComponent::GetTextureStreamingTransformScale () const override virtual
Get the scale comming form the component, when computing StreamingTexture data.
Used to support instanced meshes.
Reimplemented from UStaticMeshComponent.
GetTriMeshSizeEstimates()
virtual bool USplineMeshComponent::GetTriMeshSizeEstimates (struct FTriMeshCollisionDataEstimates & OutTriMeshEstimates, bool bInUseAllTriData) const override virtual
Returns an estimate of how much data would be retrieved by GetPhysicsTriMeshData.
Parameters
OutTriMeshEstimates - structure given by the caller to be filled with tri mesh estimate data
Returns
true if successful, false if unable to successfully fill in data structure
Reimplemented from IInterface_CollisionDataProvider.
GetVirtualTextureMainPassMaxDrawDistance()
virtual float USplineMeshComponent::GetVirtualTextureMainPassMaxDrawDistance () const inline override virtual
Definition at line 242 of file SplineMeshComponent.h.
InitVertexFactory()
void USplineMeshComponent::InitVertexFactory (int32 InLODIndex, FColorVertexBuffer * InOverrideColorVertexBuffer)
Chooses the forward axis for the spline mesh orientation.
If true, spline mesh properties - StartPos, EndPos, StartTangent and EndTangent- may be edited per instance in the level viewport. Otherwise, the spline mesh should be initialized in the construction script. If true, will use smooth interpolation (ease in/out) for Scale, Roll, and Offset along this section of spline. If false, uses linear Indicates that we will never use convex or trimesh shapes. This is an optimization to skip checking for binary data. TODO Chaos this is to opt out of CreatePhysicsMeshes for certain meshes Better long term mesh is to not call CreatePhysicsMeshes until it is known there is a mesh instance that needs it.
IsEditorOnly()
virtual bool USplineMeshComponent::IsEditorOnly () const override virtual
IsRelevantForSplinePartitioning()
bool USplineMeshComponent::IsRelevantForSplinePartitioning () const
Modify()
virtual bool USplineMeshComponent::Modify (bool bAlwaysMarkDirty = true) override virtual
OnCreatePhysicsState()
virtual void USplineMeshComponent::OnCreatePhysicsState () override protected virtual
Reimplemented from UStaticMeshComponent.
PostEditChangeProperty()
virtual void USplineMeshComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented from UStaticMeshComponent.
RecreateCollision()
void USplineMeshComponent::RecreateCollision ()
Serialize()
virtual void USplineMeshComponent::Serialize (FArchive & Ar) override virtual
Reimplemented from UStaticMeshComponent.
References Ar.
SetbNeverNeedsCookedCollisionData()
void USplineMeshComponent::SetbNeverNeedsCookedCollisionData (bool bInValue)
Setter for bNeverNeedsCookedCollisionData.
References SetbNeverNeedsCookedCollisionData().
Referenced by SetbNeverNeedsCookedCollisionData().
ShouldRenderNaniteSplineMeshes()
bool USplineMeshComponent::ShouldRenderNaniteSplineMeshes () static
ShouldRenderSelected()
virtual bool USplineMeshComponent::ShouldRenderSelected () const inline override virtual
Reimplemented from UStaticMeshComponent.
Definition at line 236 of file SplineMeshComponent.h.
UFUNCTION() [1/30]
USplineMeshComponent::UFUNCTION () const
Get the boundary max.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [2/30]
USplineMeshComponent::UFUNCTION () const
Get the boundary min.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [3/30]
USplineMeshComponent::UFUNCTION () const
Get the end roll, in radians.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [4/30]
USplineMeshComponent::UFUNCTION () const
Get the start roll, in radians.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [5/30]
USplineMeshComponent::UFUNCTION () const
Get the end position of spline in local space.
References Category, UStaticMeshComponent::const, FVector, and UFUNCTION().
UFUNCTION() [6/30]
USplineMeshComponent::UFUNCTION () const
Get the end tangent vector of spline in local space.
References Category, UStaticMeshComponent::const, FVector, and UFUNCTION().
UFUNCTION() [7/30]
UFUNCTION() 1 ESplineMeshAxis UFUNCTION() 1 void SetForwardAxis(ESplineMeshAxis USplineMeshComponent::UFUNCTION () const
Get the forward axis.
Set the forward axis Get the spline up direction
References Category, UStaticMeshComponent::const, FVector, and UFUNCTION().
UFUNCTION() [8/30]
USplineMeshComponent::UFUNCTION () const
Get the start position of spline in local space.
References Category, and FVector.
UFUNCTION() [9/30]
USplineMeshComponent::UFUNCTION () const
Get the start tangent vector of spline in local space.
References Category, UStaticMeshComponent::const, FVector, and UFUNCTION().
UFUNCTION() [10/30]
USplineMeshComponent::UFUNCTION () const
Get the end offset.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [11/30]
USplineMeshComponent::UFUNCTION () const
Get the end scaling.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [12/30]
USplineMeshComponent::UFUNCTION () const
Get the start offset.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [13/30]
USplineMeshComponent::UFUNCTION () const
Get the start scaling.
References Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [14/30]
USplineMeshComponent::UFUNCTION ()
Set the boundary max.
References bUpdateMesh, Category, and UFUNCTION().
UFUNCTION() [15/30]
USplineMeshComponent::UFUNCTION ()
Set the boundary min.
References bUpdateMesh, Category, and UFUNCTION().
UFUNCTION() [16/30]
USplineMeshComponent::UFUNCTION ()
Set the end offset.
References bUpdateMesh, Category, UStaticMeshComponent::const, and UFUNCTION().
UFUNCTION() [17/30]
USplineMeshComponent::UFUNCTION ()
Set the end position of spline in local space.
References bUpdateMesh, Category, EndPos, FVector, and UFUNCTION().
UFUNCTION() [18/30]
USplineMeshComponent::UFUNCTION ()
Set the end roll in degrees.
References bUpdateMesh, Category, and UFUNCTION().
UFUNCTION() [19/30]
USplineMeshComponent::UFUNCTION ()
Set the end scaling.
References bUpdateMesh, Category, and UFUNCTION().
UFUNCTION() [20/30]
USplineMeshComponent::UFUNCTION ()
Set the end tangent vector of spline in local space.
References bUpdateMesh, Category, EndTangent, FVector, and UFUNCTION().
UFUNCTION() [21/30]
USplineMeshComponent::UFUNCTION () const &
Set the spline up direction.
References bUpdateMesh, Category, UStaticMeshComponent::const, FVector, and UFUNCTION().
UFUNCTION() [22/30]
USplineMeshComponent::UFUNCTION ()
Set the start and end, position and tangent, all in local space.
References Category, and UFUNCTION().
UFUNCTION() [23/30]
USplineMeshComponent::UFUNCTION ()
Set the start offset.
References bUpdateMesh, Category, and UFUNCTION().
UFUNCTION() [24/30]
USplineMeshComponent::UFUNCTION ()
Set the start position of spline in local space.
References Category.
UFUNCTION() [25/30]
USplineMeshComponent::UFUNCTION ()
Set the start roll in degrees.
References bUpdateMesh, Category, and UFUNCTION().
UFUNCTION() [26/30]
USplineMeshComponent::UFUNCTION ()
Set the start scaling.
References bUpdateMesh, Category, and UFUNCTION().
UFUNCTION() [27/30]
USplineMeshComponent::UFUNCTION ()
Set the start tangent vector of spline in local space.
References bUpdateMesh, Category, FVector, StartTangent, and UFUNCTION().
UFUNCTION() [28/30]
USplineMeshComponent::UFUNCTION ()
Update the collision and render state on the spline mesh following changes to its geometry.
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [29/30]
USplineMeshComponent::UFUNCTION ()
Set the end roll, in radians.
References bUpdateMesh, Category, meta, and UFUNCTION().
UFUNCTION() [30/30]
USplineMeshComponent::UFUNCTION ()
Set the start roll, in radians.
References bUpdateMesh, Category, meta, and UFUNCTION().
UpdateBounds()
virtual void USplineMeshComponent::UpdateBounds () override virtual
Reimplemented from UStaticMeshComponent.
UpdateMesh_Concurrent()
void USplineMeshComponent::UpdateMesh_Concurrent ()
Same as UpdateMesh, but does not wait until the end of frame and can be used in non-game threads.
UpdateRenderStateAndCollision()
void USplineMeshComponent::UpdateRenderStateAndCollision ()
Called to notify render thread and possibly collision of a change in spline params or mesh.
UpdateRenderStateAndCollision_Internal()
void USplineMeshComponent::UpdateRenderStateAndCollision_Internal (bool bConcurrent) private
UPROPERTY() [1/6]
USplineMeshComponent::UPROPERTY () private virtual
Distance at which to disable World Position Offset for an entire instance (0 = Never disable WPO).
Implements UStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [2/6]
USplineMeshComponent::UPROPERTY () private virtual
Maximum coordinate along the spline forward axis which corresponds to end of spline.
If set to 0.0, will use bounding box to determine bounds
Implements UStaticMeshComponent.
References Category, transient, and UPROPERTY().
UPROPERTY() [3/6]
USplineMeshComponent::UPROPERTY () private virtual
Minimum coordinate along the spline forward axis which corresponds to start of spline.
If set to 0.0, will use bounding box to determine bounds
Implements UStaticMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [4/6]
USplineMeshComponent::UPROPERTY () private pure virtual
The max draw distance to use in the main pass when also rendering to a runtime virtual texture.
This is only exposed to the user through the same setting on ULandscapeSplineSegment.
Implements UStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [5/6]
USplineMeshComponent::UPROPERTY () private virtual
Axis (in component space) that is used to determine X axis for co-ordinates along spline.
Implements UStaticMeshComponent.
References Category, FVector, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [6/6]
USplineMeshComponent::UPROPERTY () private virtual
Distance at which to disable World Position Offset for an entire instance (0 = Never disable WPO).
Implements UStaticMeshComponent.
References BodySetup, and UPROPERTY().
WantsNegXTriMesh()
virtual bool USplineMeshComponent::WantsNegXTriMesh () inline override virtual
Do we want to create a negative version of this mesh.
Reimplemented from IInterface_CollisionDataProvider.
Definition at line 256 of file SplineMeshComponent.h.
Field Documentation
bUpdateMesh [1/2]
bool USplineMeshComponent::bUpdateMesh = true)
Definition at line 285 of file SplineMeshComponent.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
bUpdateMesh [2/2]
FVector FVector FVector bool USplineMeshComponent::bUpdateMesh = true)
Definition at line 313 of file SplineMeshComponent.h.
CachedNavigationBounds
FBox USplineMeshComponent::CachedNavigationBounds private
Definition at line 146 of file SplineMeshComponent.h.
EndPos
FVector FVector USplineMeshComponent::EndPos
Definition at line 313 of file SplineMeshComponent.h.
Referenced by UFUNCTION().
EndTangent
FVector FVector FVector USplineMeshComponent::EndTangent
Definition at line 313 of file SplineMeshComponent.h.
Referenced by UFUNCTION().
StartTangent
FVector USplineMeshComponent::StartTangent
Definition at line 313 of file SplineMeshComponent.h.
Referenced by UFUNCTION().
The documentation for this class was generated from the following file:
SplineMeshComponent.h