Unreal Engine 5.6 C++ API: FWidgetBlueprintEditor Class Reference
FWidgetBlueprintEditor Class Reference
widget blueprint editor (extends Blueprint editor)
#include "WidgetBlueprintEditor.h"
Public Member Functions
FWidgetBlueprintEditor ()
virtual ~FWidgetBlueprintEditor ()
void AddExternalEditorWidget (FName ID, TSharedRef< SWidget > InExternalWidget)
Adds external widget whose lifetime should be managed by this editor.
void AddPostDesignerLayoutAction (TFunction< void()> Action)
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void ChangeViewedAnimation (UWidgetAnimation &InAnimationToView)
Changes the currently viewed animation in Sequencer to the new one.
void CleanSelection ()
Removes removed widgets from the selection set.
void ClearHoveredWidget ()
virtual void Compile () override
Called when Compile button is clicked.
void CreateEditorModeManager () override
TSharedRef< SWidget > CreateSequencerDrawerWidget ()
Creates a sequencer widget, for anim drawer.
TSharedRef< SWidget > CreateSequencerTabWidget ()
Creates a sequencer widget.
DECLARE_EVENT (FWidgetBlueprintEditor, FOnWidgetBlueprintTransaction) FOnWidgetBlueprintTransaction &GetOnWidgetBlueprintTransaction()
Event called when an undo/redo transaction occurs.
DECLARE_MULTICAST_DELEGATE (FOnSelectedWidgetsChanging) DECLARE_MULTICAST_DELEGATE(FOnSelectedWidgetsChanged) DECLARE_MULTICAST_DELEGATE(FOnWidgetPreviewUpdated) DECLARE_MULTICAST_DELEGATE(FOnWidgetAnimationsUpdated) DECLARE_MULTICAST_DELEGATE(FOnSelectedAnimationChanged) DECLARE_EVENT(FWidgetBlueprintEditor
Called after the widget preview has been updated.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnHoveredWidgetSet, const FWidgetReference &) DECLARE_MULTICAST_DELEGATE(FOnHoveredWidgetCleared)
void DockInLayoutClicked ()
Callback to dock anim tab into layout.
virtual FText GetBaseToolkitName () const override
UWidgetAnimation * GetCurrentAnimation ()
Get the current animation.
EWidgetDesignFlags GetCurrentDesignerFlags () const
Get the current designer flags that are in effect for the current user widget we're editing.
TSharedPtr< ISequencer > & GetDrawerSequencer ()
TSharedPtr< SWidget > GetExternalEditorWidget (FName ID)
Gets external widget whose lifetime should be managed by this editor, NullWidget if not found.
const FWidgetReference & GetHoveredWidget () const
bool GetIsRespectingLocks () const
TSharedPtr< FLibraryViewModel > GetLibraryViewModel ()
TSharedPtr< FPaletteViewModel > GetPaletteViewModel ()
UUserWidget * GetPreview () const
TSharedPtr< UE::UMG::Editor::FPreviewMode > GetPreviewMode () const
Get the relative info for the Debug mode.
FPreviewScene * GetPreviewScene ()
TArray< TFunction< void()> > & GetQueuedDesignerActions ()
FWidgetReference GetReferenceFromPreview (UWidget *PreviewWidget)
Creates a widget reference using the preview.
FWidgetReference GetReferenceFromTemplate (UWidget *TemplateWidget)
Creates a widget reference using the template.
TOptional< FNamedSlotSelection > GetSelectedNamedSlot () const
const TSet< TWeakObjectPtr< UObject > > & GetSelectedObjects () const
const TWeakObjectPtr< UClass > GetSelectedTemplate () const
const FAssetData GetSelectedUserWidget () const
const TSet< FWidgetReference > & GetSelectedWidgets () const
TSharedPtr< ISequencer > & GetSequencer ()
bool GetShowDashedOutlines () const
TSharedPtr< ISequencer > & GetTabSequencer ()
virtual FName GetToolkitContextFName () const override
virtual FName GetToolkitFName () const override
class UWidgetBlueprint * GetWidgetBlueprintObj () const
TSharedPtr< class FWidgetBlueprintEditorToolbar > GetWidgetToolbarBuilder ()
virtual FLinearColor GetWorldCentricTabColorScale () const override
virtual FString GetWorldCentricTabPrefix () const override
virtual void InitToolMenuContext (FToolMenuContext &MenuContext) override
Add context objects for menus and toolbars.
void InitWidgetBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const TArray< UBlueprint * > &InBlueprints, bool bShouldOpenInDefaultsMode)
void InvalidatePreview (bool bViewOnly=false)
Causes the preview to be destroyed and a new one to be created next tick.
bool IsBindingSelected (const FMovieSceneBinding &InBinding)
Called to determine whether a binding is selected in the tree view.
bool IsSimulating () const
void MigrateFromChain (FEditPropertyChain *PropertyThatChanged, bool bIsModify)
Migrate a property change from the preview GUI to the template GUI.
void NotifyWidgetAnimListChanged ()
Callback for when widget animation list has been updated.
void OnEnteringDesigner ()
TSharedRef< SWidget > OnGetWidgetAnimSequencer ()
Gets sequencer widget, for anim drawer.
virtual bool OnRequestClose (EAssetEditorCloseReason InCloseReason) override
Called when this toolkit is requested to close.
void OnToolkitHostingFinished (const TSharedRef< IToolkit > &Toolkit) override
void OnToolkitHostingStarted (const TSharedRef< IToolkit > &Toolkit) override
void OnWidgetAnimDrawerSequencerDismissed (const TSharedPtr< SWidget > &NewlyFocusedWidget)
Callback for anim drawer closing.
void OnWidgetAnimDrawerSequencerOpened (FName StatusBarWithDrawerName)
Callback for anim drawer opening.
void OnWidgetAnimTabSequencerClosed (TSharedRef< SDockTab > ClosedTab)
Callback for anim tab closing.
void OnWidgetAnimTabSequencerOpened ()
Callback for anim tab opening.
virtual void PostRedo (bool bSuccessful) override
Signal that client should run any PostRedo code.
virtual void PostUndo (bool bSuccessful) override
Signal that client should run any PostUndo code.
const UWidgetAnimation * RefreshCurrentAnimation ()
Updates the current animation if it is invalid.
void RefreshPreview ()
Immediately rebuilds the preview widget.
int32 RemoveExternalEditorWidget (FName ID)
Removes external widget whose lifetime should be managed by this editor.
void SelectObjects (const TSet< UObject * > &Objects)
Sets the currently selected set of objects.
void SelectWidgets (const TSet< FWidgetReference > &Widgets, bool bAppendOrToggle)
Sets the currently selected set of widgets.
void SetHoveredWidget (FWidgetReference &InHoveredWidget)
The widget we're now hovering over in any particular context, allows multiple views to synchronize feedback on where that widget is in their representation.
void SetIsRespectingLocks (bool Value)
void SetIsSimulating (bool bSimulating)
void SetSelectedNamedSlot (TOptional< FNamedSlotSelection > SelectedNamedSlot)
Sets the selected named slot.
void SetSelectedTemplate (TWeakObjectPtr< UClass > TemplateClass)
Set the selected template widget.
void SetSelectedUserWidget (FAssetData InSelectedUserWidget)
Set the selected user widget.
void SetShowDashedOutlines (bool Value)
virtual void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
void ToggleAnimDrawer ()
Toggles Anim Drawer, only used for keyboard shortcut.
UE_DEPRECATED (5.2, "OnWidgetAnimSequencerDismissed is deprecated, please use OnWidgetAnimDrawerSequencerDismissed instead.") void OnWidgetAnimSequencerDismissed(const TSharedPtr< SWidget > &NewlyFocusedWidget)
UE_DEPRECATED (5.2, "OnWidgetAnimSequencerOpened is deprecated, please use OnWidgetAnimDrawerSequencerOpened instead.") void OnWidgetAnimSequencerOpened(FName StatusBarWithDrawerName)
Public Member Functions inherited from FBlueprintEditor
FBlueprintEditor ()
virtual ~FBlueprintEditor ()
FBPEditorBookmarkNode * AddBookmark (const FText &DisplayName, const FEditedDocumentInfo &BookmarkInfo, bool bSharedBookmark=false)
Adds a new bookmark node to the Blueprint that's being edited.
bool AddNewDelegateIsVisible () const
virtual void AddNewFunctionVariant (const UEdGraph *InOriginalFunction)
Create a variant for a function.
virtual void AddToSelection (UEdGraphNode *InNode) override
void AnalyticsTrackCompileEvent (UBlueprint *Blueprint, int32 NumErrors, int32 NumWarnings) const
virtual void AnalyticsTrackNodeEvent (UBlueprint *Blueprint, UEdGraphNode *GraphNode, bool bNodeDelete=false) const override
Used to track node create/delete events for Analytics.
virtual bool AreDelegatesAllowed () const
Whether delegates are allowed to be displayed/created in a blueprint.
virtual bool AreEventGraphsAllowed () const
Whether event graphs are allowed to be displayed/created in a blueprint.
virtual bool AreMacrosAllowed () const
Whether macros are allowed to be displayed/created in a blueprint.
bool CanAccessComponentsMode () const
Returns whether the edited blueprint has components.
virtual bool CanAddNewLocalVariable () const
Checks if adding a local variable is allowed in the focused graph.
virtual void ClearSelectionStateFor (FName SelectionOwner)
void CloseDocumentTab (const UObject *DocumentID)
Finds the tab associated with the specified asset, and closes if it is open.
void CloseMergeTool ()
Closes the merge tool, rather than simply hiding it.
void CommonInitialization (const TArray< UBlueprint * > &InitBlueprints, bool bShouldOpenInDefaultsMode)
virtual FReply Compile_OnClickWithReply ()
Calls the above function, but returns an FReply::Handled().
bool ConvertEventIfValid (UK2Node_Event *EventToConv)
Converts the given event node to a function graph on this blueprint if it passes validation.
bool ConvertFunctionIfValid (UK2Node_FunctionEntry *FuncEntryNode)
Converts the given function entry node to an event if it passes validation.
void CreateMergeToolTab ()
Forces the merge tool to be shown.
void CreateMergeToolTab (const UBlueprint *BaseBlueprint, const UBlueprint *RemoteBlueprint, const FOnMergeResolved &ResolutionCallback)
TSharedPtr< class ISCSEditorCustomization > CustomizeSubobjectEditor (const USceneComponent *InComponentToCustomize) const
Check to see if we can customize the subobject editor for the passed-in scene component.
DECLARE_EVENT (FBlueprintEditor, FOnRefreshEvent)
Broadcasts a notification whenever the editor needs associated controls to refresh.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnModeSet, FName)
void DestroyPreview ()
Destroy the Blueprint preview.
void DoPromoteToVariable2f (UBlueprint *InBlueprint, UEdGraphPin *InTargetPin, bool bInToMemberVariable, TOptional< FVector2f > InOptionalLocation=TOptional< FVector2f >())
void DumpMessagesToCompilerLog (const TArray< TSharedRef< class FTokenizedMessage > > &Messages, bool bForceMessageDisplay)
Dumps messages to the compiler log, with an option to force it to display/come to front.
void EnableSubobjectPreview (bool bEnable)
Enable/disable the subobject editor preview viewport.
void EnsureBlueprintIsUpToDate (UBlueprint *BlueprintObj)
virtual TSharedPtr< FSubobjectEditorTreeNode > FindAndSelectSubobjectEditorTreeNode (const UActorComponent *InComponent, bool IsCntrlDown) override
bool FindOpenTabsContainingDocument (const UObject *DocumentID, TArray< TSharedPtr< SDockTab > > &Results)
virtual void FocusInspectorOnGraphSelection (const TSet< class UObject * > &NewSelection, bool bForceRefresh=false)
virtual UBlueprint * GetBlueprintObj () const
Returns a pointer to the Blueprint object we are currently editing, as long as we are editing exactly one.
TSharedRef< SBlueprintBookmarks > GetBookmarksWidget () const
void GetBoundsForNode (const UEdGraphNode *InNode, class FSlateRect &OutRect, float InPadding) const
Get the visible bounds of the given graph node.
TSharedRef< SWidget > GetCompilerResults () const
virtual FString GetCustomDebugObjectLabel (UObject *ObjectBeingDebugged) const
Can be overloaded to customize the labels in the debug filter.
virtual void GetCustomDebugObjects (TArray< FCustomDebugObject > &DebugList) const
Adds to a list of custom objects for debugging beyond what will automatically be found/used.
TSharedRef< SKismetInspector > GetDefaultEditor () const
TSubclassOf< UEdGraphSchema > GetDefaultSchema () const
Gets the default schema for this editor.
virtual FString GetDocumentationLink () const override
TSharedRef< SFindInBlueprints > GetFindResults () const
virtual UEdGraph * GetFocusedGraph () const override
Returns the currently focused graph context, or NULL if no graph is available.
virtual FText GetGraphDecorationString (UEdGraph *InGraph) const
Called by a graph title bar to get any extra information the editor would like to display.
virtual TSharedPtr< class IClassViewerFilter > GetImportedClassViewerFilter () const override
Return the class viewer filter associated with the current set of imported namespaces within this editor context.
TSharedRef< SKismetInspector > GetInspector () const
Getters for the various Kismet2 widgets.
float GetInstructionTextOpacity (UEdGraph *InGraph) const
Used to determine the visibility of the graph's instruction text.
bool & GetIsContextSensitive ()
Gets or sets the flag for context sensitivity in the graph action menu.
TSharedPtr< SMyBlueprint > GetMyBlueprintWidget () const
EVisibility GetNativeParentClassButtonsVisibility () const
Determines visibility of the native parent class manipulation buttons on the menu bar overlay.
virtual int32 GetNumberOfSelectedNodes () const override
Get number of currently selected nodes in the SCS editor tree.
TSharedRef< SBlueprintPalette > GetPalette ()
EVisibility GetParentClassNameVisibility () const
Determines visibility of the standard parent class label on the menu bar overlay.
FText GetPIEStatus () const
Returns our PIE Status - SIMULATING / SERVER / CLIENT.
virtual void GetPinTypeSelectorFilters (TArray< TSharedPtr< class IPinTypeSelectorFilter > > &OutFilters) const override
Get all the the pin type selector filters within this editor context.
bool GetPinVisibility (SGraphEditor::EPinVisibility Visibility) const
AActor * GetPreviewActor () const
Provides access to the preview actor.
FPreviewScene * GetPreviewScene ()
Provides access to the preview scene.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
TSharedPtr< SReplaceNodeReferences > GetReplaceReferencesWidget () const
FGraphPanelSelectionSet GetSelectedNodes () const
Get the currently selected set of nodes.
virtual TArray< TSharedPtr< FSubobjectEditorTreeNode > > GetSelectedSubobjectEditorTreeNodes () const override
Util to get the currently selected Subobject editor tree Nodes.
UEdGraphNode * GetSingleSelectedNode () const
Returns the currently selected node if there is a single node selected (if there are multiple nodes selected or none selected, it will return nullptr)
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
TSharedPtr< SSubobjectEditor > GetSubobjectEditor () const
UObject * GetSubobjectEditorObjectContext () const
Delegate invoked when the Subobject editor needs to obtain the object context for editing.
TSharedPtr< SSCSEditorViewport > GetSubobjectViewport () const
FText GetTextForNativeParentClassHeaderLink () const
Returns: "(<NativeParentClass>.h)".
virtual ETickableTickType GetTickableTickType () const override
Virtual that can be overloaded by the inheriting class and is called before first tick.
TSharedPtr< class FBlueprintEditorToolbar > GetToolbarBuilder ()
virtual FText GetToolkitName () const override
virtual FText GetToolkitToolTipText () const override
FName GetUISelectionState () const
Gets the UI selection state of this editor.
void GetViewBookmark (FGuid &BookmarkId)
Gets the focused graph current view bookmark ID.
void GetViewLocation (FVector2D &Location, float &ZoomAmount)
Gets the focused graph view location/zoom amount.
FEditorViewportSelectabilityBridge * GetViewportSelectabilityBridge ()
virtual void HandleSetObjectBeingDebugged (UObject *InObject)
Handle when the debug object is changed in the UI.
void HandleUnrelatedNodesOpacityBoxChanged (float NewOpacity)
TOptional< float > HandleUnrelatedNodesOpacityBoxValue () const
void ImportNamespace (const FString &InNamespace)
Imports the given namespace into the editor.
void ImportNamespaceEx (const FImportNamespaceExParameters &InParams)
Imports a set of namespace(s) into the editor.
virtual bool InEditingMode () const
Returns true if in editing mode.
void InitBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< class IToolkitHost > &InitToolkitHost, const TArray< class UBlueprint * > &InBlueprints, bool bShouldOpenInDefaultsMode)
Edits the specified blueprint.
virtual bool IsBlueprintEditor () const override
virtual bool IsCompilingEnabled () const
Returns true if able to compile.
EVisibility IsDebuggerVisible () const
virtual bool IsEditable (UEdGraph *InGraph) const
Returns whether a graph is editable or not.
bool IsEditingSingleBlueprint () const
Returns whether the editor is currently editing a single blueprint object.
bool IsEditorClosing () const
Returns if we are currently closing the editor.
bool IsGraphInCurrentBlueprint (const UEdGraph *InGraph) const
Checks to see if the provided graph is contained within the current blueprint.
bool IsGraphReadOnly (UEdGraph *InGraph) const
Determines if the graph is ReadOnly, this differs from editable in that it is never expected to be edited and is in a read-only state.
virtual bool IsInAScriptingMode () const
Overridable function for determining if the current mode can script.
virtual bool IsNativeParentClassCodeLinkEnabled () const
Returns true if the parent class is native and the link to it's header can be shown.
bool IsNodeTitleVisible (const UEdGraphNode *Node, bool bRequestRename)
Check the Node Title is visible.
virtual bool IsNonImportedObject (const FSoftObjectPath &InObject) const
Return whether the given object (referenced by path) falls outside the scope of the current set of imported namespaces within this editor context.
virtual bool IsNonImportedObject (const UObject *InObject) const
Return whether the given object falls outside the scope of the current set of imported namespaces within this editor context.
bool IsParentClassABlueprint () const
Returns true if the parent class of the Blueprint being edited is also a Blueprint.
bool IsParentClassAnEditableBlueprint () const
Returns true if the parent class of the Blueprint being edited is an editable Blueprint.
bool IsParentClassNative () const
Returns true if the parent class of the Blueprint being edited is native.
bool IsPlayInEditorActive () const
Returns true if PIE is active.
bool IsSaveOnCompileEnabled () const
Helper functions used to construct/operate-on the "Save on Compile" command.
virtual bool IsSectionVisible (NodeSectionID::Type InSectionID) const
bool IsToggleHideUnrelatedNodesChecked () const
virtual void JumpToHyperlink (const UObject *ObjectReference, bool bRequestRename=false) override
void JumpToNode (const class UEdGraphNode *Node, bool bRequestRename=false)
Pan the view to center on a particular node.
virtual void JumpToPin (const class UEdGraphPin *Pin) override
void LogSimpleMessage (const FText &MessageText)
Throw a simple message into the log.
void LogToken_OnClicked (const class IMessageToken &Token)
Called when a token in a log message is clicked.
TSharedRef< SWidget > MakeHideUnrelatedNodesOptionsMenu ()
Make a drop down menu to control the opacity of unrelated nodes.
EVisibility NewDocument_GetVisibilityForType (ECreatedDocumentType GraphType) const
virtual bool NewDocument_IsVisibleForType (ECreatedDocumentType GraphType) const
FReply NewDocument_OnClick (ECreatedDocumentType GraphType)
virtual void NewDocument_OnClicked (ECreatedDocumentType GraphType)
Called when New Function button is clicked.
virtual bool OnActionMatchesName (FEdGraphSchemaAction *InAction, const FName &InName) const
function used by the SMyBlueprint to determine if an action matches a name.
virtual void OnActiveTabChanged (TSharedPtr< SDockTab > PreviouslyActive, TSharedPtr< SDockTab > NewlyActivated)
void OnAddNewDelegate ()
Called when New Delegate button is clicked.
virtual void OnAddNewLocalVariable ()
Adds a new local variable to the focused function graph.
void OnAddNewVariable ()
Adds a new variable to this blueprint.
FReply OnAddNewVariable_OnClick ()
virtual void OnClose () override
Called when this toolkit is being closed.
virtual void OnComponentAddedToBlueprint (const FSubobjectData &NewSubobjectData)
Delegate invoked when a new subobject is added in the subobject editor widget.
virtual void OnComponentDoubleClicked (TSharedPtr< class FSubobjectEditorTreeNode > Node)
Delegate invoked when an item is double clicked in the subobject editor widget.
void OnDumpCachedIndexDataForBlueprint ()
Dumps the currently-cached index data for the blueprint to a file for debugging.
void OnEditParentClassNativeCodeClicked ()
Handles opening the header file of native parent class.
void OnGenerateSearchIndexForDebugging ()
Dumps the current blueprint search index to a JSON file for debugging purposes.
virtual void OnGraphEditorBackgrounded (const TSharedRef< SGraphEditor > &InGraphEditor)
Called when the graph editor tab is backgrounded.
virtual void OnGraphEditorFocused (const TSharedRef< class SGraphEditor > &InGraphEditor)
Called when graph editor focus is changed.
void OnLockNodeStateCheckStateChanged (ECheckBoxState NewCheckedState)
virtual bool OnlyShowCustomDebugObjects () const
If returns true only the custom debug list will be used.
FOnModeSet & OnModeSet ()
void OnNodeSpawnedByKeymap ()
Called when node is spawned by keymap.
void OnNodeTitleCommitted (const FText &NewText, ETextCommit::Type CommitInfo, UEdGraphNode *NodeBeingChanged)
Called when a node's title is committed for a rename.
virtual void OnPasteNewLocalVariable (const FBPVariableDescription &VariableDescription)
Pastes a new local variable to the focused function graph.
FOnRefreshEvent & OnRefresh ()
virtual void OnSelectionUpdated (const TArray< TSharedPtr< class FSubobjectEditorTreeNode > > &SelectedNodes)
Delegate invoked when the selection is changed in the subobject editor widget.
virtual FReply OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f &InPosition, UEdGraph *InGraph)
TSharedPtr< SDockTab > OpenDocument (const UObject *DocumentID, FDocumentTracker::EOpenDocumentCause Cause)
virtual TSharedPtr< SGraphEditor > OpenGraphAndBringToFront (UEdGraph *Graph, bool bSetFocus=true) override
Tries to open the specified graph and bring it's document to the front (note: this can return NULL)
void PostLayoutBlueprintEditorInitialization ()
void RefreshAllNodes_OnClicked ()
Called when the refresh all nodes button is clicked.
virtual void RefreshEditors (ERefreshBlueprintEditorReason::Type Reason=ERefreshBlueprintEditorReason::UnknownReason) override
virtual void RefreshInspector ()
virtual void RefreshMyBlueprint ()
void RegisterSCSEditorCustomization (const FName &InComponentName, TSharedPtr< class ISCSEditorCustomization > InCustomization)
Register a customization for interacting with the subobject editor.
virtual void RegisterTabSpawners (const TSharedRef< class FTabManager > &TabManager) override
IToolkit interface.
void RegisterToolbarTab (const TSharedRef< class FTabManager > &TabManager)
void RemoveBookmark (const FGuid &BookmarkNodeId, bool bRefreshUI=true)
Removes the bookmark node with the given ID.
void RemoveNamespace (const FString &InNamespace)
Removes the given namespace from the editor's current import context.
void RenameBookmark (const FGuid &BookmarkNodeId, const FText &NewName)
Renames the bookmark node with the given ID.
void RenameNewlyAddedAction (FName InActionName)
Utility function to handle all steps required to rename a newly added action.
void ReparentBlueprint_Clicked ()
Reparent the current blueprint.
virtual bool ReparentBlueprint_IsVisible () const
void ReparentBlueprint_NewParentChosen (UClass *ChosenClass)
void RequestSaveEditedObjectState ()
void RestoreEditedObjectState ()
Create new tab for each element of LastEditedObjects array.
void SaveEditedObjectState ()
Save the current set of edited objects in the LastEditedObjects array so it will be opened next time we open K2.
void SelectAndDuplicateNode (UEdGraphNode *InNode)
Duplicates an EdGraphNode using selection and copy / paste functionality.
void SelectGraphActionItemByName (const FName &ItemName, ESelectInfo::Type SelectInfo=ESelectInfo::Direct, int32 SectionId=INDEX_NONE, bool bIsCategory=false)
virtual bool SelectLocalVariable (const UEdGraph *Graph, const FName &VariableName)
Selects a local variable to load in the details panel.
virtual void SetCurrentMode (FName NewMode) override
void SetDetailsCustomization (TSharedPtr< class FDetailsViewObjectFilter > DetailsObjectFilter, TSharedPtr< class IDetailRootObjectCustomization > DetailsRootCustomization)
Sets customizations for the BP editor details panel.
void SetKeyboardFocus ()
Ensures the blueprint has keyboard focus.
void SetPinVisibility (SGraphEditor::EPinVisibility Visibility)
Pin visibility accessors.
void SetSubobjectEditorUICustomization (TSharedPtr< class ISCSEditorUICustomization > SCSEditorUICustomization)
Sets subobject editor UI customization.
void SetUISelectionState (FName SelectionOwner)
void SetupViewForBlueprintEditingMode ()
void SetViewLocation (const FVector2D &Location, float ZoomAmount, const FGuid &BookmarkId=FGuid())
Sets the focused graph view location/zoom amount.
virtual bool ShouldLoadBPLibrariesFromAssetRegistry ()
virtual void StartEditingDefaults (bool bAutoFocus=true, bool bForceRefresh=false)
Virtual override point for editing defaults; allowing more derived editors to edit something else.
virtual void SummonFindAndReplaceUI () override
Invokes the Find and Replace UI.
virtual void SummonSearchUI (bool bSetFindWithinBlueprint, FString NewSearchTerms=FString(), bool bSelectFirstResult=false) override
Invokes the search UI and sets the mode and search terms optionally.
void ToggleHideUnrelatedNodes ()
Make nodes which are unrelated to the selected nodes fade out.
virtual bool TransactionObjectAffectsBlueprint (UObject *InTransactedObject)
UE_DEPRECATED (5.0, "CustomizeSCSEditor has been deprecated. Use CustomizeSubobjectEditor instead.") TSharedPtr< class ISCSEditorCustomization > CustomizeSCSEditor(USceneComponent *InComponentToCustomize) const
UE_DEPRECATED (5.0, "FindAndSelectSCSEditorTreeNode has been deprecated. Use FindAndSelectSubobjectEditorTreeNode instead.") virtual TSharedPtr< class FSCSEditorTreeNode > FindAndSelectSCSEditorTreeNode(const UActorComponent *InComponent
UE_DEPRECATED (5.0, "GetSCSEditor has been deprecated. Use GetSubobjectEditor instead.") TSharedPtr< SSCSEditor > GetSCSEditor() const
Getters for the various optional Kismet2 widgets.
UE_DEPRECATED (5.0, "GetSelectedSCSEditorTreeNodes has been deprecated. Use GetSelectedSubobjectEditorTreeNodes instead.") virtual TArray< TSharedPtr< class FSCSEditorTreeNode > > GetSelectedSCSEditorTreeNodes() const override
UE_DEPRECATED (5.0, "OnComponentDoubleClicked(TSharedPtr<class FSCSEditorTreeNode>) has been deprecated. Use OnComponentDoubleClicked(TSharedPtr<class FSubobjectEditorTreeNode>) instead.") virtual void OnComponentDoubleClicked(TSharedPtr< class FSCSEditorTreeNode > Node)
Delegate invoked when an item is double clicked in the subobject editor widget.
UE_DEPRECATED (5.0, "OnSelectionUpdated(const TArray<TSharedPtr<class FSCSEditorTreeNode>>&) has been deprecated. Use OnSelectionUpdated(const TArray<TSharedPtr<class FSubobjectEditorTreeNode>>&) instead.") virtual void OnSelectionUpdated(const TArray< TSharedPtr< class FSCSEditorTreeNode > > &SelectedNodes)
Delegate invoked when the selection is changed in the subobject editor widget.
UE_DEPRECATED (5.0, "SetSCSEditorUICustomization has been deprecated. Use SetSubobjectEditorUICustomization instead.") void SetSCSEditorUICustomization(TSharedPtr< class ISCSEditorUICustomization > SCSEditorUICustomization)
UE_DEPRECATED (5.0, "The Toggle Hide Unrelated Nodes button is always shown now") bool ShouldShowToggleHideUnrelatedNodes(bool bIsToolbar) const
UE_DEPRECATED (5.1, "Please use GetPinTypeSelectorFilters") virtual TSharedPtr< class IPinTypeSelectorFilter > GetImportedPinTypeSelectorFilter() const override
UE_DEPRECATED (5.6, "Please use the version of the function accepting FVector2f.") virtual FReply OnSpawnGraphNodeByShortcut(FInputChord InChord
Handles spawning a graph node in the current graph using the passed in chord.
UE_DEPRECATED (5.6, "Use the version of this function accepting a TOptional") void DoPromoteToVariable(UBlueprint *InBlueprint
Perform the actual promote to variable action on the given pin in the given blueprint.
void UnregisterSCSEditorCustomization (const FName &InComponentName)
Unregister a previously registered customization for interacting with the subobject editor.
void UpdateNodeCreationStats (const ENodeCreateAction::Type CreateAction)
Update Node Creation mechanisms for analytics.
void UpdateNodesUnrelatedStatesAfterGraphChange ()
Update all nodes' unrelated states when the graph has changed.
void UpdatePreviewActor (UBlueprint *InBlueprint, bool bInForceFullUpdate=false)
Creates/updates the preview actor for the given blueprint.
void UpdateSubobjectPreview (bool bUpdateNow=false)
Refresh the preview viewport to reflect changes in the subobject.
void VariableListWasUpdated ()
Variable list window calls this after it is updated.
Public Member Functions inherited from IBlueprintEditor
virtual TSharedPtr< FSubobjectEditorTreeNode > FindAndSelectSubobjectEditorTreeNode (const class UActorComponent *InComponent, bool IsCntrlDown)=0
Find and select a specific SCS editor tree node associated with the given component.
virtual void JumpToPin (const UEdGraphPin *PinToFocusOn)=0
UE_DEPRECATED (5.0, "FindAndSelectSCSEditorTreeNode has been deprecated. Use FindAndSelectSubobjectEditorTreeNode instead.") virtual TSharedPtr< class FSCSEditorTreeNode > FindAndSelectSCSEditorTreeNode(const class UActorComponent *InComponent
UE_DEPRECATED (5.1, "Please use GetPinTypeSelectorFilters") virtual TSharedPtr< class IPinTypeSelectorFilter > GetImportedPinTypeSelectorFilter() const
Return the pin type selector filter associated with the current set of imported namespaces within this editor context.
UE_DEPRECATED (5.6, "Slate positions are represented in FVector2f. Please update to use the function acceping FVector2f.") virtual void PasteNodesHere(class UEdGraph *Graph
Public Member Functions inherited from FWorkflowCentricApplication
UNREALED_API FName GetCurrentMode () const
TSharedPtr< FApplicationMode > GetCurrentModePtr () const
virtual UNREALED_API FName GetToolMenuToolbarName (FName &OutParentName) const override
Get name used by tool menu.
UNREALED_API FName GetToolMenuToolbarNameForMode (const FName InModeName, FName &OutParentName) const
bool IsModeCurrent (FName ModeToCheck) const
UNREALED_API void PushTabFactories (FWorkflowAllowedTabSet &FactorySetToPush) const
virtual UNREALED_API UToolMenu * RegisterModeToolbarIfUnregistered (const FName InModeName)
Registers toolbar for a mode if not already registered.
virtual UNREALED_API void UnregisterTabSpawners (const TSharedRef< class FTabManager > &TabManager) override
Public Member Functions inherited from FAssetEditorToolkit
UNREALED_API FAssetEditorToolkit ()
Default constructor.
FAssetEditorToolkit (const FAssetEditorToolkit &)=delete
virtual UNREALED_API ~FAssetEditorToolkit ()
Virtual destructor, so that we can clean up our app when destroyed.
virtual void AddGraphEditorPinActionsToContextMenu (FToolMenuSection &InSection) const
UNREALED_API void AddMenuExtender (TSharedPtr< FExtender > Extender)
Adds or removes extenders to the default menu or the toolbar menu this asset editor.
UNREALED_API void AddToolbarExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void AddToolbarWidget (TSharedRef< SWidget > Widget)
Adds or removes widgets from the default toolbar in this asset editor.
virtual void AddViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget, int32 ZOrder=INDEX_NONE)
virtual UNREALED_API bool CloseWindow (EAssetEditorCloseReason InCloseReason) override
virtual UNREALED_API TSharedPtr< SWidget > CreateMenuBar (const TSharedPtr< FTabManager > &InTabManager, const FName InMenuName, FToolMenuContext &InToolMenuContext)
Method that can be overriden by derived classes to provide a custom MenuBar to the Standalone Toolkit Host.
UNREALED_API void FillDefaultAssetMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for modifying this asset that are generally common to most asset editors.
UNREALED_API void FillDefaultFileMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultFileMenuOpenCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultHelpMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for the help menu.
virtual UNREALED_API void FocusWindow (UObject *ObjectToFocusOn=nullptr) override
UNREALED_API void GenerateToolbar ()
Makes a default asset editing toolbar.
virtual UNREALED_API TSharedPtr< FTabManager > GetAssociatedTabManager () override
virtual UNREALED_API FName GetEditingAssetTypeName () const override
virtual UNREALED_API FEditorModeTools & GetEditorModeManager () const final
virtual UNREALED_API FName GetEditorName () const override
IAssetEditorInstance interface.
virtual UNREALED_API double GetLastActivationTime () override
virtual UNREALED_API const TArray< UObject * > * GetObjectsCurrentlyBeingEdited () const override
virtual UNREALED_API EAssetOpenMethod GetOpenMethod () const override
UNREALED_API TSharedPtr< IToolkitHost > GetPreviousWorldCentricToolkitHost ()
virtual UNREALED_API UE::Editor::Toolbars::ECreateStatusBarOptions GetStatusBarCreationOptions () const
Called by StandaloneAssetEditorToolkitHost to determine what sections of the StatusBar should be created.
TSharedPtr< FTabManager > GetTabManager ()
virtual UNREALED_API FText GetTabSuffix () const override
UNREALED_API FName GetToolMenuAppName () const
UNREALED_API FName GetToolMenuName () const
UNREALED_API FName GetToolMenuToolbarName () const
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > &ObjectsToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
Initializes this asset editor.
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, UObject *ObjectToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
virtual UNREALED_API void InvokeTab (const FTabId &TabId) override
UNREALED_API bool IsActuallyAnAsset () const
True if this actually is editing an asset.
virtual UNREALED_API bool IsAssetEditor () const override
virtual bool IsPrimaryEditor () const override
virtual void OnViewportDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
React to a Drag&Drop events from the viewport.
virtual void OnViewportDragLeave (const FDragDropEvent &DragDropEvent)
virtual FReply OnViewportDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
FAssetEditorToolkit & operator= (const FAssetEditorToolkit &)=delete
UNREALED_API void RegenerateMenusAndToolbars ()
Regenerates the menubar and toolbar widgets.
UNREALED_API void RegisterDrawer (struct FWidgetDrawerConfig &&Drawer, int32 SlotIndex=INDEX_NONE)
Registers a drawer for the asset editor status bar.
UNREALED_API void RemoveAllToolbarWidgets ()
virtual UNREALED_API void RemoveEditingAsset (UObject *Asset) override
UNREALED_API void RemoveMenuExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void RemoveToolbarExtender (TSharedPtr< FExtender > Extender)
virtual void RemoveViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget)
Called when a toolkit requests the overlay widget to be removed.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout)
Applies the passed in layout (or the saved user-modified version if available).
UNREALED_API void SetMenuOverlay (TSharedRef< SWidget > Widget)
Allows the caller to set a menu overlay, displayed to the far right of the editor's menu bar.
UE_DEPRECATED (4.26, "Override CreateEditorModeManager on the toolkit class instead.") UNREALED_API void SetAssetEditorModeManager(class FAssetEditorModeManager *InModeManager)
Set the asset editor mode manager we are using.
UE_DEPRECATED (4.26, "Use GetEditorModeManager instead.") UNREALED_API class FAssetEditorModeManager *GetAssetEditorModeManager() const
Get the asset editor mode manager we are using.
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") UNREALED_API virtual bool CloseWindow() override
Public Member Functions inherited from IAssetEditorInstance
virtual bool IncludeAssetInRestoreOpenAssetsPrompt (UObject *Asset) const
virtual void InvokeTab (const struct FTabId &TabId)=0
UE_DEPRECATED (5.0, "Toolbar tab no longer exists and tab ID will return None; do not add it to layouts") virtual FName GetToolbarTabId() const
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") virtual bool CloseWindow()
UE_DEPRECATED (5.4, "Use the override that takes in an UObject instead") virtual bool IncludeAssetInRestoreOpenAssetsPrompt() const
If false, the asset being edited will not be included in reopen assets prompt on restart.
Public Member Functions inherited from FBaseToolkit
UNREALED_API FBaseToolkit ()
FBaseToolkit constructor.
virtual UNREALED_API ~FBaseToolkit ()
Virtual destructor.
virtual UNREALED_API void BringToolkitToFront () override
virtual UNREALED_API TSharedPtr< SWidget > GetInlineContent () const override
const TSharedRef< FUICommandList > GetToolkitCommands () const
virtual UNREALED_API const TSharedRef< IToolkitHost > GetToolkitHost () const override
virtual TSharedRef< FWorkspaceItem > GetWorkspaceMenuCategory () const override
virtual UNREALED_API bool IsHosted () const override
UNREALED_API bool IsWorldCentricAssetEditor () const
virtual UNREALED_API bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const override
Public Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedRef< FAssetEditorToolkit, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAssetEditorToolkit, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from FNotifyHook
virtual void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, class FEditPropertyChain *PropertyThatChanged)
virtual void NotifyPreChange (class FEditPropertyChain *PropertyAboutToChange)
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Public Member Functions inherited from FEditorUndoClient
virtual UNREALED_API ~FEditorUndoClient ()
Always unregister for undo on destruction, just in case.
virtual FString GetTransactionContext () const
Return the transaction context for this client.
virtual bool MatchesContext (const FTransactionContext &InContext, const TArray< TPair< UObject *, FTransactionObjectEvent > > &TransactionObjectContexts) const
Called to see if the context of the current undo/redo operation is a match for the client Default state matching old context-less undo is Context="" and PrimaryObject=NULL.
Data Fields
TSharedPtr< FUICommandList > DesignerCommandList
Command list for handling widget actions in the WidgetBlueprintEditor.
FOnEnterWidgetDesigner OnEnterWidgetDesigner
Fires after the mode change to Designer.
FOnHoveredWidgetCleared OnHoveredWidgetCleared
Fires when there is no longer any widget being hovered over.
FOnHoveredWidgetSet OnHoveredWidgetSet
Fires whenever a new widget is being hovered over.
FOnSelectedAnimationChanged OnSelectedAnimationChanged
Fires whenever the selected animation changes.
FOnSelectedWidgetsChanged OnSelectedWidgetsChanged
Fires whenever the selected set of widgets changes.
FOnSelectedWidgetsChanged OnSelectedWidgetsChanging
Fires whenever the selected set of widgets changing.
FOnWidgetAnimationsUpdated OnWidgetAnimationsUpdated
Notification for when the preview widget has been updated.
FOnWidgetPreviewUpdated OnWidgetPreviewUpdated
Notification for when the preview widget has been updated.
FVector2D PasteDropLocation
Paste Metadata.
TArray< TSharedPtr< FUICommandInfo > > ToolPaletteCommands
Commands for switching between tool palettes.
Data Fields inherited from FBlueprintEditor
UEdGraphPin bool bInToMemberVariable
TSharedPtr< FDocumentTracker > DocumentManager
UEdGraphPin bool const FVector2D * InOptionalLocation = nullptr)
const FVector2D & InPosition
UEdGraphPin * InTargetPin
bool IsCntrlDown override { return nullptr
const FVector2D UEdGraph *InGraph UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Data Fields inherited from IBlueprintEditor
bool IsCntrlDown = 0
const FVector2D &Location UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION { PasteNodesHere(Graph, UE::Slate::CastToVector2f(Location))
Protected Member Functions
void BindToolkitCommands ()
void CaptureThumbnail ()
void ClearThumbnail ()
TSharedPtr< FExtender > CreateMenuExtender ()
TSharedPtr< ISequencer > CreateSequencerWidgetInternal ()
void CustomizeWidgetCompileOptions (FMenuBuilder &InMenuBuilder)
void FillAssetMenu (FMenuBuilder &MenuBuilder)
void FillFileMenu (FMenuBuilder &MenuBuilder)
virtual TSubclassOf< UEdGraphSchema > GetDefaultSchemaClass () const override
Whenever new graphs need to be created it will use this schema by default.
virtual FGraphAppearanceInfo GetGraphAppearance (class UEdGraph *InGraph) const override
Get the graph appearance of a specific graph, GetCurrentGraphAppearance() uses the currently focused graph.
virtual void InitalizeExtenders () override
Called during initialization of the blueprint editor to register commands and extenders.
bool IsImageUsedAsThumbnail ()
bool IsPreviewWidgetInitialized ()
void OnCreateNativeBaseClassSuccessfully (const FString &InClassName, const FString &InClassPath, const FString &InModuleName)
void OpenCreateNativeBaseClassDialog ()
virtual void RegisterApplicationModes (const TArray< UBlueprint * > &InBlueprints, bool bShouldOpenInDefaultsMode, bool bNewlyCreated=false) override
Called during initialization of the blueprint editor to register any application modes.
void TakeSnapshot ()
Protected Member Functions inherited from FBlueprintEditor
bool CanAddBreakpoint () const
bool CanAddExecutionPin () const
bool CanAddOptionPin () const
bool CanAddParentNode () const
bool CanAssignReferencedActor () const
bool CanChangePinType () const
bool CanCollapseNodes () const
bool CanCollapseSelectionToFunction () const
bool CanCollapseSelectionToFunction (TSet< class UEdGraphNode * > &InSelection) const
Called when a selection of nodes is being collapsed into a function.
bool CanCollapseSelectionToMacro () const
bool CanCollapseSelectionToMacro (TSet< class UEdGraphNode * > &InSelection) const
Called when a selection of nodes is being collapsed into a macro.
bool CanConvertEventToFunction () const
bool CanConvertFunctionToEvent () const
Callback function for the context menu on a node to determine if a function could possibly be converted to an event.
virtual bool CanCopyNodes () const
bool CanCreateMatchingFunction () const
virtual bool CanCutNodes () const
virtual bool CanDeleteNodes () const
bool CanDisableBreakpoint () const
bool CanDuplicateNodes () const
bool CanEnableBreakpoint () const
bool CanExpandNodes () const
bool CanInsertExecutionPin () const
bool CanNavigateToChildGraph () const
bool CanNavigateToParentGraph () const
bool CanOpenBlueprintDebugger () const
virtual bool CanPasteGeneric () const
virtual bool CanPasteNodes () const override
bool CanPromoteSelectionToFunction () const
bool CanPromoteSelectionToMacro () const
bool CanPromoteToVariable (bool bInToMemberVariable) const
bool CanRecombineStructPin () const
bool CanRedoGraphAction () const
Whether or not we can redo an undone action.
bool CanRemoveBreakpoint () const
bool CanRemoveExecutionPin () const
bool CanRemoveOptionPin () const
bool CanRemoveOtherStructVarPins () const
bool CanRemoveThisStructVarPin () const
bool CanRenameNodes () const
bool CanResetPinToDefaultValue () const
bool CanRestoreAllStructVarPins () const
bool CanSelectAllNodes () const
bool CanSelectReferenceInLevel () const
bool CanSplitStructPin () const
virtual bool CanStartWatchingPin () const
virtual bool CanStopWatchingPin () const
bool CanToggleBreakpoint () const
bool CanUndoGraphAction () const
Whether or not we can perform an undo of the last transacted action.
bool CanZoomToSelection () const
bool CanZoomToWindow () const
void ClearAllBreakpoints ()
Deletes all breakpoints for the blueprint being edited.
void ClearAllGraphEditorQuickJumps ()
Unbinds all graph editor "quick jump" commands.
void ClearAllWatches ()
Clears all watches associated with the blueprint being edited.
void ClearGraphEditorQuickJump (int32 BookmarkIndex)
Unbinds a graph editor "quick jump" from the command at the given index.
void CollapseNodes (TSet< class UEdGraphNode * > &InCollapsableNodes)
Called when a selection of nodes are being collapsed into a sub-graph.
void CollapseNodesIntoGraph (UEdGraphNode *InGatewayNode, class UK2Node_EditablePinBase *InEntryNode, class UK2Node_EditablePinBase *InResultNode, UEdGraph *InSourceGraph, UEdGraph *InDestinationGraph, TSet< UEdGraphNode * > &InCollapsableNodes, bool bCanDiscardEmptyReturnNode, bool bCanHaveWeakObjPtrParam)
Collapses a selection of nodes into a graph for composite, function, or macro nodes.
UEdGraph * CollapseSelectionToFunction (TSharedPtr< SGraphEditor > InRootGraph, TSet< class UEdGraphNode * > &InCollapsableNodes, UEdGraphNode *&OutFunctionNode)
Called when a selection of nodes are being collapsed into a function.
UEdGraph * CollapseSelectionToMacro (TSharedPtr< SGraphEditor > InRootGraph, TSet< class UEdGraphNode * > &InCollapsableNodes, UEdGraphNode *&OutMacroNode)
Called when a selection of nodes are being collapsed into a macro.
void CollectExecDownstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void CollectExecUpstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void CollectPureDownstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void CollectPureUpstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void ConvertEventToFunction (UK2Node_Event *SelectedEventNode)
void ConvertFunctionToEvent (UK2Node_FunctionEntry *SelectedCallFunctionNode)
virtual void CopySelectedNodes ()
virtual void CreateDefaultCommands ()
Create Default Commands.
virtual void CreateDefaultTabContents (const TArray< UBlueprint * > &InBlueprints)
Creates the widgets that go into the tabs (note: does not create the tabs themselves)
virtual TSharedRef< SGraphEditor > CreateGraphEditorWidget (TSharedRef< class FTabInfo > InTabInfo, class UEdGraph *InGraph)
TSharedRef< SWidget > CreateGraphTitleBarWidget (TSharedRef< FTabInfo > InTabInfo, UEdGraph *InGraph)
Create a graph title bar widget.
virtual void CutSelectedNodes ()
void DeleteSelectedDuplicatableNodes ()
virtual void DeleteSelectedNodes ()
void DeleteUnusedVariables_OnClicked ()
Called when DeleteUnusedVariables button is clicked.
void DisableAllBreakpoints ()
Disables all breakpoints for the blueprint being edited.
void DuplicateNodes ()
void EditClassDefaults_Clicked ()
Edit the class defaults.
void EditGlobalOptions_Clicked ()
Edit the class settings aka Blueprint global options.
void EnableAllBreakpoints ()
Enables all breakpoints for the blueprint being edited.
void ExtractEventTemplateForFunction (class UK2Node_CustomEvent *InCustomEvent, UEdGraphNode *InGatewayNode, class UK2Node_EditablePinBase *InEntryNode, class UK2Node_EditablePinBase *InResultNode, TSet< UEdGraphNode * > &InCollapsableNodes)
Pulls out the pins to use as a template when collapsing a selection to a function with a custom event involved.
void FindInBlueprint_Clicked ()
Called to start a quick find (focus the search box in the explorer tab)
void FindInBlueprints_OnClicked ()
Called when Find In Blueprints menu is opened is clicked.
TArray< UEdGraphNode * > GetAllConnectedNodes (UEdGraphNode *const Node) const
Get all connected nodes and add them to a set of out nodes.
virtual bool GetBoundsForSelectedNodes (class FSlateRect &Rect, float Padding) override
FGraphAppearanceInfo GetCurrentGraphAppearance () const
Get the graph appearance of the currently focused graph.
UEdGraphPin * GetCurrentlySelectedPin () const
EVisibility GetEditParentClassVisibility () const
Determines visibility of the edit parent class button on the menu bar overlay.
EVisibility GetFindParentClassVisibility () const
Determines visibility of the find parent class in content browser button on the menu bar overlay.
FText GetParentClassNameText () const
Returns the name of the Blueprint's parent class.
bool GetSaveIntermediateBuildProducts () const
bool HasAnyBreakpoints () const
bool HasAnyDisabledBreakpoints () const
bool HasAnyEnabledBreakpoints () const
bool HasAnyWatches () const
void HideUnrelatedNodes ()
bool IsDetailsPanelEditingClassDefaults () const
bool IsDetailsPanelEditingGlobalOptions () const
void LoadLibrariesFromAssetRegistry ()
Load macro & function blueprint libraries from asset registry.
void MoveNodesToAveragePos (TSet< UEdGraphNode * > &AverageNodes, FVector2D SourcePos, bool bExpandedNodesNeedUniqueGuid=false) const
Move the given set of nodes to an average spot near the Source position.
void NavigateToChildGraph ()
void NavigateToParentGraph ()
void NavigateToParentGraphByDoubleClick ()
virtual void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, FProperty *PropertyThatChanged) override
virtual void NotifyPreChange (FProperty *PropertyAboutToChange) override
void OnAddBreakpoint ()
void OnAddExecutionPin ()
void OnAddOptionPin ()
void OnAddParentNode ()
void OnAlignBottom ()
void OnAlignCenter ()
void OnAlignLeft ()
void OnAlignMiddle ()
void OnAlignRight ()
void OnAlignTop ()
void OnAssignReferencedActor ()
void OnBlueprintChanged (UBlueprint *InBlueprint)
Called when the Blueprint we are editing has changed, forwards to impl.
void OnBlueprintCompiled (UBlueprint *InBlueprint)
void OnBlueprintUnloaded (UBlueprint *InBlueprint)
Handles the unloading of Blueprints (by closing the editor, if it operating on the Blueprint being unloaded)
void OnChangePinType ()
void OnChangePinTypeFinished (const FEdGraphPinType &PinType, UEdGraphPin *SelectedPin)
void OnCollapseNodes ()
void OnCollapseSelectionToFunction ()
void OnCollapseSelectionToMacro ()
void OnConvertEventToFunction ()
void OnConvertFunctionToEvent ()
virtual void OnCreateComment ()
virtual void OnCreateCustomEvent ()
Create custom event node on graph.
FActionMenuContent OnCreateGraphActionMenu (UEdGraph *InGraph, const FVector2f &InNodePosition, const TArray< UEdGraphPin * > &InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed)
void OnCreateMatchingFunction ()
void OnDisableBreakpoint ()
void OnDistributeNodesH ()
void OnDistributeNodesV ()
FReply OnEditParentClassClicked ()
Handler for "Edit parent class" button.
virtual void OnEditTabClosed (TSharedRef< SDockTab > Tab)
void OnEnableBreakpoint ()
void OnExpandNodes ()
FReply OnFindParentClassInContentBrowserClicked ()
Handler for "Find parent class in CB" button.
virtual void OnFinishedChangingProperties (const FPropertyChangedEvent &PropertyChangedEvent)
Callback when properties have finished being handled.
FEdGraphPinType OnGetPinType (UEdGraphPin *SelectedPin) const
Functions for handling the changing of the pin's type (PinCategory, PinSubCategory, etc)
void OnGraphActionMenuClosed (bool bActionExecuted, bool bContextSensitiveChecked, bool bGraphPinContext)
Called from graph context menus when they close to tell the editor why they closed.
void OnGraphEditorDropActor (const TArray< TWeakObjectPtr< AActor > > &Actors, UEdGraph *Graph, const FVector2f &DropLocation)
Called when an actor is dropped onto the graph editor.
void OnGraphEditorDropStreamingLevel (const TArray< TWeakObjectPtr< ULevelStreaming > > &Levels, UEdGraph *Graph, const FVector2f &DropLocation)
Called when a streaming level is dropped onto the graph editor.
void OnGraphEditorQuickJump (int32 BookmarkIndex)
Handles activation of a graph editor "quick jump" command.
void OnInsertExecutionPin (EPinInsertPosition Position)
void OnInsertExecutionPinAfter ()
void OnInsertExecutionPinBefore ()
void OnListObjectsReferencedByBlueprint ()
void OnListObjectsReferencedByClass ()
void OnNodeDoubleClicked (UEdGraphNode *Node)
bool OnNodeVerifyTitleCommit (const FText &NewText, UEdGraphNode *NodeBeingChanged, FText &OutErrorMessage)
Called when a node's title is being committed for a rename so it can be verified.
void OnPostObjectPropertyChanged (UObject *InObject, FPropertyChangedEvent &PropertyChangedEvent)
Called after a property change has been propagated to instances of the Blueprint.
void OnPreObjectPropertyChanged (UObject *InObject, const FEditPropertyChain &EditPropertyChain)
Called when a property change is about to be propagated to instances of the Blueprint.
void OnPromoteSelectionToFunction ()
void OnPromoteSelectionToMacro ()
void OnPromoteToVariable (bool bInToMemberVariable)
void OnRecombineStructPin ()
void OnRemoveBreakpoint ()
void OnRemoveExecutionPin ()
void OnRemoveOptionPin ()
void OnRemoveOtherStructVarPins ()
void OnRemoveThisStructVarPin ()
void OnRenameNode ()
On starting to rename node.
void OnRepairCorruptedBlueprint ()
void OnResetPinToDefaultValue ()
void OnRestoreAllStructVarPins ()
void OnSelectedNodesChanged (const TSet< class UObject * > &NewSelection)
Called when the selection changes in the GraphEditor.
virtual void OnSelectedNodesChangedImpl (const TSet< class UObject * > &NewSelection)
Called when the selection changes in the GraphEditor.
void OnSelectReferenceInLevel ()
void OnSplitStructPin ()
void OnStackNodesH ()
void OnStackNodesV ()
void OnStartEditingDefaultsClicked ()
Start editing the defaults for this blueprint.
virtual void OnStartWatchingPin ()
virtual void OnStopWatchingPin ()
void OnStraightenConnections ()
void OnToggleBreakpoint ()
void OpenBlueprintDebugger ()
Spawns a new blueprint debugger tab.
virtual void PasteGeneric ()
Paste Variable Definition or Nodes.
virtual void PasteNodes ()
virtual void PasteNodesHere (class UEdGraph *DestinationGraph, const FVector2f &GraphLocation) override
Paste on graph at specific location.
virtual void PostRegenerateMenusAndToolbars () override
Recreates the overlay on the menu bar.
void ReconnectExecPins (class UK2Node *Node)
Given a node, make connections from anything connected to it's input pin to anything connected to it's "then" pins.
void RedoGraphAction ()
Called to redo the last undone action.
void RefreshStandAloneDefaultsEditor ()
void RegisterMenus ()
Register Menus.
void ResetAllNodesUnrelatedStates ()
Focus nodes which are related to the selected nodes.
void SelectAllNodes ()
void SetGraphEditorQuickJump (int32 BookmarkIndex)
Binds a graph editor "quick jump" to the command at the given index.
virtual void SetupGraphEditorEvents (UEdGraph *InGraph, SGraphEditor::FGraphEditorEvents &InEvents)
Setup all the events that the graph editor can handle.
bool ShouldShowPublicViewControl () const
Callback to determine visibility of the public view checkbox in the Defaults editor.
void ToggleSaveIntermediateBuildProducts ()
void TryInvokingDetailsTab (bool bFlash=true)
Attempts to invoke the details tab if it's currently possible to.
UE_DEPRECATED (5.6, "Please use the version of the function taking FVector2f.") FActionMenuContent OnCreateGraphActionMenu(UEdGraph *InGraph
Called to create context menu when right-clicking on graph.
void UndoGraphAction ()
Called to undo the last action.
void ZoomToSelection_Clicked ()
void ZoomToWindow_Clicked ()
Protected Member Functions inherited from FWorkflowCentricApplication
virtual UNREALED_API void AddApplicationMode (FName ModeName, TSharedRef< FApplicationMode > Mode)
virtual UNREALED_API const TMap< FName, TSharedPtr< FApplicationMode > > & GetApplicationModeList () const
virtual UNREALED_API void RemoveAllApplicationModes ()
virtual UNREALED_API bool RemoveApplicationMode (FName ModeName)
Protected Member Functions inherited from FAssetEditorToolkit
virtual UNREALED_API void AddEditingObject (UObject *Object)
Adds an item to the Editing Objects list.
virtual UNREALED_API void BrowseDocumentation_Execute () const
Called when "Browse Documentation" is clicked for this asset.
virtual bool CanFindInContentBrowser () const
Called to test if "Find in Content Browser" should be enabled for this asset.
virtual UNREALED_API bool CanReimport () const
Called to check to see if there's an asset capable of being reimported.
virtual UNREALED_API bool CanReimport (UObject *EditingObject) const
bool CanReimport_Internal () const
Internal function to check if the asset can be reimported that calls CanReimport.
virtual bool CanSaveAsset () const
Called to test if "Save" should be enabled for this asset.
bool CanSaveAsset_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAsset.
virtual bool CanSaveAssetAs () const
Called to test if "Save As" should be enabled for this asset.
bool CanSaveAssetAs_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAssetAs.
virtual UNREALED_API void FindInContentBrowser_Execute ()
Called when "Find in Content Browser" is clicked for this asset.
virtual UNREALED_API UToolMenu * GenerateCommonActionsToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for common asset actions like Save.
UToolMenu * GenerateReadOnlyToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for read only mode specific content.
virtual UNREALED_API FLinearColor GetDefaultTabColor () const
virtual UNREALED_API const FSlateBrush * GetDefaultTabIcon () const
UNREALED_API UObject * GetEditingObject () const
Returns the single object currently being edited.
UNREALED_API TArray< TObjectPtr< UObject > > & GetEditingObjectPtrs ()
UNREALED_API const TArray< UObject * > & GetEditingObjects () const
Returns an array of all the objects currently being edited.
virtual UNREALED_API FName GetReadOnlyMenuProfileName ()
Get the name of the profile registered with UToolMenus for read only menu customizations.
virtual UNREALED_API void GetSaveableObjects (TArray< UObject * > &OutObjects) const
Get the collection of edited objects that can be saved.
virtual UNREALED_API EVisibility GetVisibilityWhileAssetCompiling () const
Called to get the desired visibility when the asset is compiling.
bool HasEditingObject () const
Returns true if this toolkit has any objects being edited.
virtual bool IsFindInContentBrowserButtonVisible () const
Called to test if "Find in Content Browser" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetAsVisible () const
Called to test if "Save As" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetVisible () const
Called to test if "Save" should be visible for this asset.
virtual UNREALED_API void MapToolkitCommands ()
Can be overriden to prevent registering the default commands.
virtual void OnAssetsSaved (const TArray< UObject * > &SavedObjects)
Called from SaveAsset_Execute when assets have been saved.
virtual void OnAssetsSavedAs (const TArray< UObject * > &SavedObjects)
Called from SaveAssetAs_Execute when assets have been saved.
virtual void PostInitAssetEditor ()
Perform any initialization that should happen after the basic toolkit needs are created for the asset editor.
virtual UNREALED_API void Reimport_Execute ()
Called when "Reimport" is clicked for this asset.
virtual UNREALED_API void Reimport_Execute (UObject *EditingObject)
virtual UNREALED_API void RemoveEditingObject (UObject *Object)
Removes an item from the Editing Objects list.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout, bool bLoadUserLayout)
Applies the passed in layout.
virtual UNREALED_API void SaveAsset_Execute ()
Called when "Save" is clicked for this asset.
virtual UNREALED_API void SaveAssetAs_Execute ()
Called when "Save As" is clicked for this asset.
virtual UNREALED_API void SetupReadOnlyMenuProfiles (FReadOnlyAssetEditorCustomization &OutReadOnlyCustomization)
Specify the permission lists to use in read only mode.
virtual UNREALED_API bool ShouldPromptForNewFilesOnReload (const UObject &object) const
Called to determine if the user should be prompted for a new file if one is missing during an asset reload.
virtual bool ShouldReopenEditorForSavedAsset (const UObject *Asset) const
Whether to open a new asset editor for the newly-saved Asset.
UE_DEPRECATED (4.26, "Use EditorModeManager instead.") FAssetEditorModeManager *AssetEditorModeManager
UE_DEPRECATED (5.3, "Use OnRequestClose that takes in an EAssetEditorCloseReason instead") virtual bool OnRequestClose()
Called when this toolkit is requested to close.
Protected Member Functions inherited from FBaseToolkit
UNREALED_API FLinearColor GetTabColorScale () const
UNREALED_API FString GetTabPrefix () const
Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Static Protected Member Functions
static void AddCreateCompileTabSubMenu (FMenuBuilder &InMenuBuilder)
static void AddDismissCompileTabSubMenu (FMenuBuilder &InMenuBuilder)
static bool IsCreateOnCompileSet (EDisplayOnCompile InCreateOnCompile)
static bool IsDismissOnCompileSet (EDisplayOnCompile InDismissOnCompile)
static void SetCreateOnCompileSetting (EDisplayOnCompile InCreateOnCompile)
static void SetDismissOnCompileSetting (EDisplayOnCompile InDismissOnCompile)
Static Protected Member Functions inherited from FBlueprintEditor
static void ExpandNode (UEdGraphNode *InNodeToExpand, UEdGraph *InSourceGraph, TSet< UEdGraphNode * > &OutExpandedNodes)
Expands passed in node.
static void MoveNodesToGraph (TArray< UEdGraphNode * > &SourceNodes, UEdGraph *DestinationGraph, TSet< UEdGraphNode * > &OutExpandedNodes, UEdGraphNode **OutEntry, UEdGraphNode **OutResult, const bool bIsCollapsedGraph=false)
Move every node from the source graph to the destination graph.
Static Protected Member Functions inherited from FAssetEditorToolkit
static UNREALED_API void SwitchToStandaloneEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to Standalone Editor" is clicked for the asset editor.
static UNREALED_API void SwitchToWorldCentricEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to World-Centric Editor" is clicked for the asset editor.
Static Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Private Types
using Super = FBlueprintEditor
Private Member Functions
void AddDynamicPossessionMenu (FMenuBuilder &MenuBuilder, FGuid ObjectId)
Dynamic binding.
void AddMaterialTrack (UWidget *Widget, TArray< FProperty * > MaterialPropertyPath, FText MaterialPropertyDisplayName)
Add an animation track for the supplied material property path to the current animation.
void AddObjectToAnimation (UObject *ObjectToAnimate)
Adds the supplied UObject to the current animation.
void AddSlotTrack (TObjectPtr< UPanelSlot > Slot)
Add an animation track for the supplied slot to the current animation.
void AddSlotTrack (UPanelSlot *Slot)
Add an animation track for the supplied slot to the current animation.
void AddWidgetsToTrack (const TArray< FWidgetReference > Widgets, FGuid ObjectId)
Binds additional widgets to a track of the same type.
bool CanCopySelectedWidgets ()
bool CanCreateNativeBaseClass () const
Is creating a native base class for the current widget blueprint allowed.
bool CanCutSelectedWidgets ()
bool CanDeleteSelectedWidgets ()
bool CanDuplicateSelectedWidgets ()
bool CanFindWidgetReferences () const
bool CanPasteWidgets ()
void CopySelectedWidgets ()
void CutSelectedWidgets ()
void DeleteSelectedWidgets ()
void DestroyPreview ()
Destroy the current preview GUI object.
void DuplicateSelectedWidgets ()
void ExtendSequencerAddTrackMenu (FMenuBuilder &AddTrackMenuBuilder, const TArray< UObject * > ContextObjects)
Extends the sequencer add track menu.
TSharedRef< FExtender > GetAddTrackSequencerExtender (const TSharedRef< FUICommandList > CommandList, const TArray< UObject * > ContextSensitiveObjects)
Gets the extender to use for sequencers context sensitive menus and toolbars.
TArray< UObject * > GetAnimationEventContexts () const
Get the animation playback event contexts.
UObject * GetAnimationPlaybackContext () const
Get the animation playback context.
bool IsCreateNativeBaseClassVisible () const
Whether menu to create a native base class is visible.
virtual void OnBlueprintChangedImpl (UBlueprint *InBlueprint, bool bIsJustBeingCompiled=false) override
Called whenever the blueprint is structurally changed.
void OnBuildCustomContextMenuForGuid (FMenuBuilder &MenuBuilder, FGuid ObjectBinding)
Populates sequencer menu when added with objects.
void OnFindWidgetReferences (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags)
void OnFinishedChangingDynamicBindingProperties (const FPropertyChangedEvent &ChangeEvent, TSharedPtr< FStructOnScope > ValueStruct, FGuid ObjectId)
void OnGetAnimationAddMenuContent (FMenuBuilder &MenuBuilder, TSharedRef< ISequencer > Sequencer)
Populates the sequencer add menu.
void OnGetAnimationAddMenuContentAllWidgets (FMenuBuilder &MenuBuilder)
Populates the sequencer add submenu for the big list of widgets.
void OnMovieSceneBindingsPasted (const TArray< FMovieSceneBinding > &BindingsPasted)
Handler which is called whenever sequencer binding is pasted.
void OnMovieSceneDataChanged (EMovieSceneDataChangeType DataChangeType)
Handler which is called whenever sequencer movie scene data changes.
void OnObjectsReplaced (const TMap< UObject *, UObject * > &ReplacementMap)
Called when objects need to be swapped out for new versions, like after a blueprint recompile.
void PasteWidgets ()
void RemoveAllWidgetsFromTrack (FGuid ObjectId)
Remove all bindings from a track.
void RemoveMissingWidgetsFromTrack (FGuid ObjectId)
Remove any missing bindings from a track.
void RemoveWidgetsFromTrack (const TArray< FWidgetReference > Widgets, FGuid ObjectId)
Unbind widgets from a track.
void ReplaceTrackWithWidgets (const TArray< FWidgetReference > Widgets, FGuid ObjectId)
Replace current widget bindings on a track with new widget bindings.
void SyncSelectedWidgetsWithSequencerSelection (TArray< FGuid > ObjectGuids)
Fire off when sequencer selection changed.
void SyncSequencerSelectionToSelectedWidgets ()
Tell sequencer the selected widgets changed.
void SyncSequencersMovieSceneData ()
Tell sequencers movie data changed.
void UpdatePreview (UBlueprint *InBlueprint, bool bInForceFullUpdate)
Tick the current preview GUI object.
void UpdateTrackName (FGuid ObjectId)
Update the name of a track to reflect changes in bindings.
Private Attributes
TSharedPtr< SWidget > AnimDrawerWidget
Widget created for anim drawer.
bool bIsPreviewWidgetSelected
True when the selected object is the preview widget.
bool bIsRealTime
bool bIsSequencerDrawerOpen
True if sequencer drawer is open.
bool bIsSimulateEnabled
bool bPreviewInvalidated
The preview becomes invalid and needs to be rebuilt on the next tick.
bool bRefreshGeneratedClassAnimations
When true the animation data in the generated class should be replaced with the current animation data.
bool bRespectLocks
bool bShowDashedOutlines
Should the designer show outlines when it creates widgets?
bool bUpdatingExternalSelection
When true the external selection is being updated from changes to the sequencer selection.
bool bUpdatingSequencerSelection
When true the sequencer selection is being updated from changes to the external selection.
TWeakObjectPtr< UWidgetAnimation > CurrentAnimation
The currently viewed animation, if any.
TSharedPtr< ISequencer > DrawerSequencer
Sequencer for creating and previewing widget animations in drawer.
TWeakPtr< SOverlay > DrawerSequencerOverlay
Overlay used to display UI on top of drawer sequencer.
TMap< FName, TSharedPtr< SWidget > > ExternalEditorWidgets
For external widgets to have lifetimes bound to this editor instance.
FWidgetReference HoveredWidget
The widget currently being hovered over.
TSharedPtr< FLibraryViewModel > LibraryViewModel
ViewModel used by the Library View.
TSharedPtr< class FWidgetEditorModeUILayer > ModeUILayer
Used to spawn sidebar tool palette.
TWeakPtr< STextBlock > NoAnimationTextBlockDrawer
A text block which is displayed in the overlay when no animation is selected in drawer.
TWeakPtr< STextBlock > NoAnimationTextBlockTab
A text block which is displayed in the overlay when no animation is selected.
FOnWidgetBlueprintTransaction OnWidgetBlueprintTransaction
Delegate called when a undo/redo transaction happens.
TSharedPtr< FPaletteViewModel > PaletteViewModel
ViewModel used by the Palette and Palette Favorite Views.
UWidgetBlueprint * PreviewBlueprint
The Blueprint associated with the current preview.
TSharedPtr< UE::UMG::Editor::FPreviewMode > PreviewMode
FPreviewScene PreviewScene
The preview scene that owns the preview GUI.
TWeakObjectPtr< UUserWidget > PreviewWidgetPtr
The preview GUI object.
TArray< TFunction< void()> > QueuedDesignerActions
TOptional< FNamedSlotSelection > SelectedNamedSlot
The currently selected named slot.
TSet< TWeakObjectPtr< UObject > > SelectedObjects
The currently selected objects in the designer.
TWeakObjectPtr< UClass > SelectedTemplate
The last selected template widget in the palette view.
FAssetData SelectedUserWidget
AssetData of Selected UserWidget.
TSet< FWidgetReference > SelectedWidgets
The currently selected preview widgets in the preview GUI.
FDelegateHandle SequencerAddTrackExtenderHandle
TArray< TWeakPtr< ISequencer > > Sequencers
List of created sequencers.
TSharedPtr< ISequencer > TabSequencer
Sequencer for creating and previewing widget animations in tabs.
TWeakPtr< SOverlay > TabSequencerOverlay
Overlay used to display UI on top of tab sequencer.
TArray< TWeakPtr< FWidgetHandle > > WidgetHandlePool
The widget references out in the ether that may need to be updated after being issued.
TSharedPtr< class FWidgetBlueprintEditorToolbar > WidgetToolbar
The toolbar builder associated with this editor.
Additional Inherited Members
Public Types inherited from FBlueprintEditor
enum ECreatedDocumentType {
CGT_NewVariable , CGT_NewFunctionGraph , CGT_NewMacroGraph , CGT_NewAnimationLayer ,
CGT_NewEventGraph , CGT_NewLocalVariable
}
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FBlueprintEditor
static FName GetContextFromBlueprintType (EBlueprintType InType)
Get the context to use from the Blueprint type.
static const FSlateBrush * GetGlyphForGraph (const UEdGraph *Graph, bool bInLargeIcon=false)
Util for finding a glyph for a graph.
static FText GetGraphDisplayName (const UEdGraph *Graph)
Gets the display name of a graph.
static FSlateBrush const * GetVarIconAndColor (const UStruct *VarScope, FName VarName, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
static FSlateBrush const * GetVarIconAndColorFromPinType (const FEdGraphPinType &PinType, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
static FSlateBrush const * GetVarIconAndColorFromProperty (const FProperty *Property, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
Static Public Member Functions inherited from FWorkflowCentricApplication
static TArray< FWorkflowApplicationModeExtender > & GetModeExtenderList ()
Static Public Member Functions inherited from FAssetEditorToolkit
static UNREALED_API FText GetLabelForObject (const UObject *InObject)
Gets the text to display in a toolkit titlebar for an object.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedMenuExtensibilityManager ()
Returns the default extensibility managers, these are applied for all asset types.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedToolBarExtensibilityManager ()
static UNREALED_API FText GetToolTipTextForObject (const UObject *InObject)
Gets the text to display in a toolkit tooltip for an object.
static UNREALED_API void RegisterDefaultToolBar ()
Registers default tool bar.
static UNREALED_API void SetPreviousWorldCentricToolkitHostForNewAssetEditor (TSharedRef< IToolkitHost > ToolkitHost)
Static: Used internally to set the world-centric toolkit host for a newly-created standalone asset editing toolkit.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Static Public Attributes inherited from FBlueprintEditor
static FName SelectionState_ClassDefaults
static FName SelectionState_ClassSettings
static FName SelectionState_Components
static FName SelectionState_Graph
static FName SelectionState_MyBlueprint
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Attributes inherited from FBlueprintEditor
const FVector2D const TArray< UEdGraphPin * > bool bAutoExpand
bool bBlueprintModifiedOnOpen
Did we update the blueprint when it opened.
bool bEditorMarkedAsClosed
Whether we are already in the process of closing this editor.
bool bHideUnrelatedNodes
If true, fade out nodes which are unrelated to the selected nodes automatically.
bool bIsActionMenuContextSensitive
Whether the graph action menu should be sensitive to the pins dragged off of.
bool bIsReparentingBlueprint
True if the current blueprint is in the process of being reparented.
bool bLockNodeFadeState
Lock the current fade state of each node.
TSharedPtr< class SBlueprintBookmarks > BookmarksWidget
Blueprint bookmark editing widget.
bool bPendingDeferredClose
Flags if this blueprint editor should close on its next tick.
bool bRequestedSavingOpenDocumentState
Has someone requested a deferred update of the saved document state?
bool bSaveIntermediateBuildProducts
Should intermediate build products be saved when recompiling?
bool bSelectRegularNode
If a regular node (not a comment node) has been selected.
bool bWasOpenedInDefaultsMode
True if the editor was opened in defaults mode.
int32 CachedNumErrors
int32 CachedNumWarnings
Limited cache of last compile results.
TSharedPtr< class SWidget > CompilerResults
Compiler results log, with the log listing that it reflects.
TSharedPtr< class IMessageLogListing > CompilerResultsListing
TSharedPtr< class IPinTypeSelectorFilter > CompositePinTypeSelectorFilter
Filter used to compose multiple pin type filters together.
FName CurrentUISelection
The current UI selection state of this editor.
TSharedPtr< class SKismetInspector > DefaultEditor
defaults inspector widget
TSet< FString > DeferredNamespaceImports
Pending set of namespaces to be auto-imported on the next tick.
TSharedPtr< class SFindInBlueprints > FindResults
Find results log as well as the search filter.
TWeakPtr< class SGraphEditor > FocusedGraphEdPtr
Currently focused graph editor.
TWeakPtr< FDocumentTabFactory > GraphEditorTabFactoryPtr
Factory that spawns graph editors; used to look up all tabs spawned by it.
TSharedPtr< class IClassViewerFilter > ImportedClassViewerFilter
Filter used to restrict class viewer widgets in the editor context to imported namespaces only.
TSharedPtr< FBlueprintNamespaceHelper > ImportedNamespaceHelper
Imported namespace helper utility object.
TSharedPtr< class IPinTypeSelectorFilter > ImportedPinTypeSelectorFilter
Filter used to restrict pin type selector widgets in the editor context to imported namespaces only.
const FVector2D const TArray< UEdGraphPin * > & InDraggedPins
const FVector2D & InNodePosition
const FVector2D const TArray< UEdGraphPin * > bool SGraphEditor::FActionMenuClosed InOnMenuClosed
TSharedPtr< class SKismetInspector > Inspector
Node inspector widget.
TWeakPtr< class SDockTab > MergeTool
Merge tool - WeakPtr because it's owned by the GlobalTabManager.
TSharedPtr< class SMyBlueprint > MyBlueprintWidget
All of this blueprints' functions and variables.
TWeakPtr< class SWindow > NameEntryPopupWindow
Reference to owner of the current popup.
TSharedPtr< class INameValidatorInterface > NameEntryValidator
Reference to helper object to validate names in popup.
FOnMergeResolved OnMergeResolved
Merge tool - Delegate to call when the merge tool is closed.
FOnSetPinVisibility OnSetPinVisibility
TSharedPtr< class SBlueprintPalette > Palette
Palette of all classes with funcs/vars.
TSharedPtr< class IPinTypeSelectorFilter > PermissionsPinTypeSelectorFilter
Filter used to restrict pin type selector widgets to those which permissions allow.
TWeakPtr< class IMenu > PinTypeChangeMenu
Reference to owner of the pin type change popup.
SGraphEditor::EPinVisibility PinVisibility
Whether to hide unused pins or not.
TWeakObjectPtr< AActor > PreviewActorPtr
The preview actor representing the current preview.
FPreviewScene PreviewScene
Blueprint preview scene.
TSharedPtr< class SReplaceNodeReferences > ReplaceReferencesWidget
Widget for replacing node references.
TArray< TObjectPtr< UBlueprint > > StandardLibraries
Macro/function libraries to keep loaded.
TSharedPtr< SSubobjectEditor > SubobjectEditor
Subobject Editor.
TSharedPtr< SSCSEditorViewport > SubobjectViewport
Viewport widget.
TSharedPtr< class FBlueprintEditorToolbar > Toolbar
The toolbar builder class.
TSet< TWeakObjectPtr< UUserDefinedEnum > > UserDefinedEnumerators
User-defined enumerators to keep loaded.
TSet< TWeakObjectPtr< UUserDefinedStruct > > UserDefinedStructures
User-defined structures to keep loaded.
Protected Attributes inherited from FWorkflowCentricApplication
TSharedPtr< FApplicationMode > CurrentAppModePtr
Protected Attributes inherited from FAssetEditorToolkit
TSharedPtr< FWorkspaceItem > AssetEditorTabsCategory
The base category that tabs are registered to, allows for child classes to register to the same point.
bool bCheckDirtyOnAssetSave
Whether only dirty assets should be prompted about on save - otherwise all edited assets will be prompted to the user for save/check-out.
TSharedPtr< FEditorModeTools > EditorModeManager
The editor mode manager.
TArray< TSharedPtr< FLayoutExtender > > LayoutExtenders
Array of layout extenders.
FString LayoutIni = GEditorLayoutIni
What ini file should be used to persist and restore the user's layout.
TWeakPtr< IToolkitHost > PreviousWorldCentricToolkitHost
For standalone asset editing tool-kits that were switched from world-centric mode on the fly, this stores the toolkit host (level editor) that hosted this toolkit last.
TSharedPtr< FTabManager > TabManager
Controls our internal layout.
Protected Attributes inherited from FBaseToolkit
TSharedRef< FUICommandList > ToolkitCommands
List of UI commands for this toolkit.
TWeakPtr< IToolkitHost > ToolkitHost
The host application for this editor.
EToolkitMode::Type ToolkitMode
Asset editing mode, set at creation-time and never changes.
TSharedPtr< FWorkspaceItem > WorkspaceMenuCategory
The workspace menu category of this toolkit.
Detailed Description
widget blueprint editor (extends Blueprint editor)
Definition at line 39 of file WidgetBlueprintEditor.h.
Member Typedef Documentation
Super
using FWidgetBlueprintEditor::Super = FBlueprintEditor private
Definition at line 42 of file WidgetBlueprintEditor.h.
Constructor & Destructor Documentation
FWidgetBlueprintEditor()
FWidgetBlueprintEditor::FWidgetBlueprintEditor ()
Referenced by DECLARE_EVENT(), and DECLARE_MULTICAST_DELEGATE().
~FWidgetBlueprintEditor()
virtual FWidgetBlueprintEditor::~FWidgetBlueprintEditor () virtual
Member Function Documentation
AddCreateCompileTabSubMenu()
void FWidgetBlueprintEditor::AddCreateCompileTabSubMenu (FMenuBuilder & InMenuBuilder) static protected
AddDismissCompileTabSubMenu()
void FWidgetBlueprintEditor::AddDismissCompileTabSubMenu (FMenuBuilder & InMenuBuilder) static protected
AddDynamicPossessionMenu()
void FWidgetBlueprintEditor::AddDynamicPossessionMenu (FMenuBuilder & MenuBuilder, FGuid ObjectId) private
Dynamic binding.
References ObjectId.
AddExternalEditorWidget()
void FWidgetBlueprintEditor::AddExternalEditorWidget (FName ID, TSharedRef< SWidget > InExternalWidget)
Adds external widget whose lifetime should be managed by this editor.
References ID.
AddMaterialTrack()
void FWidgetBlueprintEditor::AddMaterialTrack (UWidget * Widget, TArray< FProperty * > MaterialPropertyPath, FText MaterialPropertyDisplayName) private
Add an animation track for the supplied material property path to the current animation.
AddObjectToAnimation()
void FWidgetBlueprintEditor::AddObjectToAnimation (UObject * ObjectToAnimate) private
Adds the supplied UObject to the current animation.
AddPostDesignerLayoutAction()
void FWidgetBlueprintEditor::AddPostDesignerLayoutAction (TFunction< void()> Action)
References AddPostDesignerLayoutAction().
Referenced by AddPostDesignerLayoutAction().
AddReferencedObjects()
virtual void FWidgetBlueprintEditor::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Reimplemented from FBlueprintEditor.
AddSlotTrack() [1/2]
void FWidgetBlueprintEditor::AddSlotTrack (TObjectPtr< UPanelSlot > Slot) inline private
Add an animation track for the supplied slot to the current animation.
Definition at line 409 of file WidgetBlueprintEditor.h.
References AddSlotTrack(), and TObjectPtr< T >::Get().
Referenced by AddSlotTrack().
AddSlotTrack() [2/2]
void FWidgetBlueprintEditor::AddSlotTrack (UPanelSlot * Slot) private
Add an animation track for the supplied slot to the current animation.
AddWidgetsToTrack()
void FWidgetBlueprintEditor::AddWidgetsToTrack (const TArray< FWidgetReference > Widgets, FGuid ObjectId) private
Binds additional widgets to a track of the same type.
References ObjectId, and Widgets.
BindToolkitCommands()
void FWidgetBlueprintEditor::BindToolkitCommands () protected
CanCopySelectedWidgets()
bool FWidgetBlueprintEditor::CanCopySelectedWidgets () private
CanCreateNativeBaseClass()
bool FWidgetBlueprintEditor::CanCreateNativeBaseClass () const private
Is creating a native base class for the current widget blueprint allowed.
CanCutSelectedWidgets()
bool FWidgetBlueprintEditor::CanCutSelectedWidgets () private
CanDeleteSelectedWidgets()
bool FWidgetBlueprintEditor::CanDeleteSelectedWidgets () private
CanDuplicateSelectedWidgets()
bool FWidgetBlueprintEditor::CanDuplicateSelectedWidgets () private
CanFindWidgetReferences()
bool FWidgetBlueprintEditor::CanFindWidgetReferences () const private
CanPasteWidgets()
bool FWidgetBlueprintEditor::CanPasteWidgets () private
CaptureThumbnail()
void FWidgetBlueprintEditor::CaptureThumbnail () protected
ChangeViewedAnimation()
void FWidgetBlueprintEditor::ChangeViewedAnimation (UWidgetAnimation & InAnimationToView)
Changes the currently viewed animation in Sequencer to the new one.
CleanSelection()
void FWidgetBlueprintEditor::CleanSelection ()
Removes removed widgets from the selection set.
ClearHoveredWidget()
void FWidgetBlueprintEditor::ClearHoveredWidget ()
References ClearHoveredWidget().
Referenced by ClearHoveredWidget().
ClearThumbnail()
void FWidgetBlueprintEditor::ClearThumbnail () protected
Compile()
virtual void FWidgetBlueprintEditor::Compile () override virtual
Called when Compile button is clicked.
Reimplemented from FBlueprintEditor.
CopySelectedWidgets()
void FWidgetBlueprintEditor::CopySelectedWidgets () private
CreateEditorModeManager()
void FWidgetBlueprintEditor::CreateEditorModeManager () override virtual
Reimplemented from FAssetEditorToolkit.
CreateMenuExtender()
TSharedPtr< FExtender > FWidgetBlueprintEditor::CreateMenuExtender () protected
CreateSequencerDrawerWidget()
TSharedRef< SWidget > FWidgetBlueprintEditor::CreateSequencerDrawerWidget ()
Creates a sequencer widget, for anim drawer.
CreateSequencerTabWidget()
TSharedRef< SWidget > FWidgetBlueprintEditor::CreateSequencerTabWidget ()
Creates a sequencer widget.
CreateSequencerWidgetInternal()
TSharedPtr< ISequencer > FWidgetBlueprintEditor::CreateSequencerWidgetInternal () protected
CustomizeWidgetCompileOptions()
void FWidgetBlueprintEditor::CustomizeWidgetCompileOptions (FMenuBuilder & InMenuBuilder) protected
CutSelectedWidgets()
void FWidgetBlueprintEditor::CutSelectedWidgets () private
DECLARE_EVENT()
FWidgetBlueprintEditor::DECLARE_EVENT (FWidgetBlueprintEditor , FOnWidgetBlueprintTransaction) & inline
Event called when an undo/redo transaction occurs.
Definition at line 185 of file WidgetBlueprintEditor.h.
References FWidgetBlueprintEditor(), and OnWidgetBlueprintTransaction.
DECLARE_MULTICAST_DELEGATE()
FWidgetBlueprintEditor::DECLARE_MULTICAST_DELEGATE (FOnSelectedWidgetsChanging)
Called after the widget preview has been updated.
Called when animation list changes Called when animation selection changes
References FWidgetBlueprintEditor().
DECLARE_MULTICAST_DELEGATE_OneParam()
FWidgetBlueprintEditor::DECLARE_MULTICAST_DELEGATE_OneParam (FOnHoveredWidgetSet , const FWidgetReference &)
DeleteSelectedWidgets()
void FWidgetBlueprintEditor::DeleteSelectedWidgets () private
DestroyPreview()
void FWidgetBlueprintEditor::DestroyPreview () private
Destroy the current preview GUI object.
DockInLayoutClicked()
void FWidgetBlueprintEditor::DockInLayoutClicked ()
Callback to dock anim tab into layout.
DuplicateSelectedWidgets()
void FWidgetBlueprintEditor::DuplicateSelectedWidgets () private
ExtendSequencerAddTrackMenu()
void FWidgetBlueprintEditor::ExtendSequencerAddTrackMenu (FMenuBuilder & AddTrackMenuBuilder, const TArray< UObject * > ContextObjects) private
Extends the sequencer add track menu.
FillAssetMenu()
void FWidgetBlueprintEditor::FillAssetMenu (FMenuBuilder & MenuBuilder) protected
FillFileMenu()
void FWidgetBlueprintEditor::FillFileMenu (FMenuBuilder & MenuBuilder) protected
GetAddTrackSequencerExtender()
TSharedRef< FExtender > FWidgetBlueprintEditor::GetAddTrackSequencerExtender (const TSharedRef< FUICommandList > CommandList, const TArray< UObject * > ContextSensitiveObjects) private
Gets the extender to use for sequencers context sensitive menus and toolbars.
GetAnimationEventContexts()
TArray< UObject * > FWidgetBlueprintEditor::GetAnimationEventContexts () const inline private
Get the animation playback event contexts.
Definition at line 433 of file WidgetBlueprintEditor.h.
References TArray< InElementType, InAllocatorType >::Add(), and GetPreview().
GetAnimationPlaybackContext()
UObject * FWidgetBlueprintEditor::GetAnimationPlaybackContext () const inline private
Get the animation playback context.
Definition at line 430 of file WidgetBlueprintEditor.h.
References GetPreview().
GetBaseToolkitName()
virtual FText FWidgetBlueprintEditor::GetBaseToolkitName () const override virtual
Reimplemented from FBlueprintEditor.
GetCurrentAnimation()
UWidgetAnimation * FWidgetBlueprintEditor::GetCurrentAnimation () inline
Get the current animation.
Definition at line 138 of file WidgetBlueprintEditor.h.
References CurrentAnimation.
GetCurrentDesignerFlags()
EWidgetDesignFlags FWidgetBlueprintEditor::GetCurrentDesignerFlags () const
Get the current designer flags that are in effect for the current user widget we're editing.
References GetCurrentDesignerFlags().
Referenced by GetCurrentDesignerFlags().
GetDefaultSchemaClass()
virtual TSubclassOf< UEdGraphSchema > FWidgetBlueprintEditor::GetDefaultSchemaClass () const override protected virtual
Whenever new graphs need to be created it will use this schema by default.
Reimplemented from FBlueprintEditor.
GetDrawerSequencer()
TSharedPtr< ISequencer > & FWidgetBlueprintEditor::GetDrawerSequencer ()
Returns
The sequencer used to create widget animations in drawer
GetExternalEditorWidget()
TSharedPtr< SWidget > FWidgetBlueprintEditor::GetExternalEditorWidget (FName ID)
Gets external widget whose lifetime should be managed by this editor, NullWidget if not found.
References ID.
GetGraphAppearance()
virtual FGraphAppearanceInfo FWidgetBlueprintEditor::GetGraphAppearance (class UEdGraph * InGraph) const override protected virtual
Get the graph appearance of a specific graph, GetCurrentGraphAppearance() uses the currently focused graph.
Reimplemented from FBlueprintEditor.
GetHoveredWidget()
const FWidgetReference & FWidgetBlueprintEditor::GetHoveredWidget () const
Returns
The widget that is currently being hovered over (either in the designer or hierarchy)
References GetHoveredWidget().
Referenced by GetHoveredWidget().
GetIsRespectingLocks()
bool FWidgetBlueprintEditor::GetIsRespectingLocks () const
References GetIsRespectingLocks().
Referenced by GetIsRespectingLocks().
GetLibraryViewModel()
TSharedPtr< FLibraryViewModel > FWidgetBlueprintEditor::GetLibraryViewModel () inline
Definition at line 257 of file WidgetBlueprintEditor.h.
References LibraryViewModel.
GetPaletteViewModel()
TSharedPtr< FPaletteViewModel > FWidgetBlueprintEditor::GetPaletteViewModel () inline
Definition at line 256 of file WidgetBlueprintEditor.h.
References GetPaletteViewModel(), and PaletteViewModel.
Referenced by GetPaletteViewModel().
GetPreview()
UUserWidget * FWidgetBlueprintEditor::GetPreview () const
Returns
The preview widget.
Referenced by GetAnimationEventContexts(), and GetAnimationPlaybackContext().
GetPreviewMode()
TSharedPtr< UE::UMG::Editor::FPreviewMode > FWidgetBlueprintEditor::GetPreviewMode () const inline
Get the relative info for the Debug mode.
Definition at line 262 of file WidgetBlueprintEditor.h.
References PreviewMode.
GetPreviewScene()
FPreviewScene * FWidgetBlueprintEditor::GetPreviewScene ()
Returns
The preview scene that owns the preview widget.
GetQueuedDesignerActions()
TArray< TFunction< void()> > & FWidgetBlueprintEditor::GetQueuedDesignerActions ()
References GetQueuedDesignerActions().
Referenced by GetQueuedDesignerActions().
GetReferenceFromPreview()
FWidgetReference FWidgetBlueprintEditor::GetReferenceFromPreview (UWidget * PreviewWidget)
Creates a widget reference using the preview.
Which is used to lookup the stable template pointer.
GetReferenceFromTemplate()
FWidgetReference FWidgetBlueprintEditor::GetReferenceFromTemplate (UWidget * TemplateWidget)
Creates a widget reference using the template.
GetSelectedNamedSlot()
TOptional< FNamedSlotSelection > FWidgetBlueprintEditor::GetSelectedNamedSlot () const
Returns
The selected named slot
GetSelectedObjects()
const TSet< TWeakObjectPtr< UObject > > & FWidgetBlueprintEditor::GetSelectedObjects () const
Returns
The selected set of Objects
GetSelectedTemplate()
const TWeakObjectPtr< UClass > FWidgetBlueprintEditor::GetSelectedTemplate () const inline
Returns
the selected template widget
Definition at line 168 of file WidgetBlueprintEditor.h.
References SelectedTemplate.
GetSelectedUserWidget()
const FAssetData FWidgetBlueprintEditor::GetSelectedUserWidget () const inline
Returns
the selected user widget
Definition at line 171 of file WidgetBlueprintEditor.h.
References SelectedUserWidget.
GetSelectedWidgets()
const TSet< FWidgetReference > & FWidgetBlueprintEditor::GetSelectedWidgets () const
Returns
The selected set of widgets
GetSequencer()
TSharedPtr< ISequencer > & FWidgetBlueprintEditor::GetSequencer ()
Returns
The currently active sequencer used to create widget animations
GetShowDashedOutlines()
bool FWidgetBlueprintEditor::GetShowDashedOutlines () const
References GetShowDashedOutlines().
Referenced by GetShowDashedOutlines().
GetTabSequencer()
TSharedPtr< ISequencer > & FWidgetBlueprintEditor::GetTabSequencer ()
Returns
The sequencer used to create widget animations
GetToolkitContextFName()
virtual FName FWidgetBlueprintEditor::GetToolkitContextFName () const override virtual
Reimplemented from FBlueprintEditor.
GetToolkitFName()
virtual FName FWidgetBlueprintEditor::GetToolkitFName () const override virtual
Reimplemented from FBlueprintEditor.
GetWidgetBlueprintObj()
class UWidgetBlueprint * FWidgetBlueprintEditor::GetWidgetBlueprintObj () const
Returns
The widget blueprint currently being edited in this editor
GetWidgetToolbarBuilder()
TSharedPtr< class FWidgetBlueprintEditorToolbar > FWidgetBlueprintEditor::GetWidgetToolbarBuilder () inline
Definition at line 179 of file WidgetBlueprintEditor.h.
References WidgetToolbar.
GetWorldCentricTabColorScale()
virtual FLinearColor FWidgetBlueprintEditor::GetWorldCentricTabColorScale () const override virtual
Reimplemented from FBlueprintEditor.
GetWorldCentricTabPrefix()
virtual FString FWidgetBlueprintEditor::GetWorldCentricTabPrefix () const override virtual
Reimplemented from FBlueprintEditor.
InitalizeExtenders()
virtual void FWidgetBlueprintEditor::InitalizeExtenders () override protected virtual
Called during initialization of the blueprint editor to register commands and extenders.
Reimplemented from FBlueprintEditor.
InitToolMenuContext()
virtual void FWidgetBlueprintEditor::InitToolMenuContext (FToolMenuContext & MenuContext) override virtual
Add context objects for menus and toolbars.
Reimplemented from FBlueprintEditor.
InitWidgetBlueprintEditor()
void FWidgetBlueprintEditor::InitWidgetBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, const TArray< UBlueprint * > & InBlueprints, bool bShouldOpenInDefaultsMode)
InvalidatePreview()
void FWidgetBlueprintEditor::InvalidatePreview (bool bViewOnly = false)
Causes the preview to be destroyed and a new one to be created next tick.
IsBindingSelected()
bool FWidgetBlueprintEditor::IsBindingSelected (const FMovieSceneBinding & InBinding)
Called to determine whether a binding is selected in the tree view.
IsCreateNativeBaseClassVisible()
bool FWidgetBlueprintEditor::IsCreateNativeBaseClassVisible () const private
Whether menu to create a native base class is visible.
IsCreateOnCompileSet()
bool FWidgetBlueprintEditor::IsCreateOnCompileSet (EDisplayOnCompile InCreateOnCompile) static protected
IsDismissOnCompileSet()
bool FWidgetBlueprintEditor::IsDismissOnCompileSet (EDisplayOnCompile InDismissOnCompile) static protected
IsImageUsedAsThumbnail()
bool FWidgetBlueprintEditor::IsImageUsedAsThumbnail () protected
IsPreviewWidgetInitialized()
bool FWidgetBlueprintEditor::IsPreviewWidgetInitialized () protected
IsSimulating()
bool FWidgetBlueprintEditor::IsSimulating () const
MigrateFromChain()
void FWidgetBlueprintEditor::MigrateFromChain (FEditPropertyChain * PropertyThatChanged, bool bIsModify)
Migrate a property change from the preview GUI to the template GUI.
NotifyWidgetAnimListChanged()
void FWidgetBlueprintEditor::NotifyWidgetAnimListChanged ()
Callback for when widget animation list has been updated.
OnBlueprintChangedImpl()
virtual void FWidgetBlueprintEditor::OnBlueprintChangedImpl (UBlueprint * InBlueprint, bool bIsJustBeingCompiled = false) override private virtual
Called whenever the blueprint is structurally changed.
Reimplemented from FBlueprintEditor.
OnBuildCustomContextMenuForGuid()
void FWidgetBlueprintEditor::OnBuildCustomContextMenuForGuid (FMenuBuilder & MenuBuilder, FGuid ObjectBinding) private
Populates sequencer menu when added with objects.
Used to handle case where widget is deleted so it's Object * is null.
OnCreateNativeBaseClassSuccessfully()
void FWidgetBlueprintEditor::OnCreateNativeBaseClassSuccessfully (const FString & InClassName, const FString & InClassPath, const FString & InModuleName) protected
OnEnteringDesigner()
void FWidgetBlueprintEditor::OnEnteringDesigner ()
References OnEnteringDesigner().
Referenced by OnEnteringDesigner().
OnFindWidgetReferences()
void FWidgetBlueprintEditor::OnFindWidgetReferences (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags) private
References Flags.
OnFinishedChangingDynamicBindingProperties()
void FWidgetBlueprintEditor::OnFinishedChangingDynamicBindingProperties (const FPropertyChangedEvent & ChangeEvent, TSharedPtr< FStructOnScope > ValueStruct, FGuid ObjectId) private
References ObjectId.
OnGetAnimationAddMenuContent()
void FWidgetBlueprintEditor::OnGetAnimationAddMenuContent (FMenuBuilder & MenuBuilder, TSharedRef< ISequencer > Sequencer) private
Populates the sequencer add menu.
OnGetAnimationAddMenuContentAllWidgets()
void FWidgetBlueprintEditor::OnGetAnimationAddMenuContentAllWidgets (FMenuBuilder & MenuBuilder) private
Populates the sequencer add submenu for the big list of widgets.
OnGetWidgetAnimSequencer()
TSharedRef< SWidget > FWidgetBlueprintEditor::OnGetWidgetAnimSequencer ()
Gets sequencer widget, for anim drawer.
OnMovieSceneBindingsPasted()
void FWidgetBlueprintEditor::OnMovieSceneBindingsPasted (const TArray< FMovieSceneBinding > & BindingsPasted) private
Handler which is called whenever sequencer binding is pasted.
OnMovieSceneDataChanged()
void FWidgetBlueprintEditor::OnMovieSceneDataChanged (EMovieSceneDataChangeType DataChangeType) private
Handler which is called whenever sequencer movie scene data changes.
OnObjectsReplaced()
void FWidgetBlueprintEditor::OnObjectsReplaced (const TMap< UObject *, UObject * > & ReplacementMap) private
Called when objects need to be swapped out for new versions, like after a blueprint recompile.
OnRequestClose()
virtual bool FWidgetBlueprintEditor::OnRequestClose (EAssetEditorCloseReason InCloseReason) override virtual
Called when this toolkit is requested to close.
Returns false if closing should be prevented.
Reimplemented from FBlueprintEditor.
OnToolkitHostingFinished()
void FWidgetBlueprintEditor::OnToolkitHostingFinished (const TSharedRef< IToolkit > & Toolkit) override virtual
Reimplemented from FAssetEditorToolkit.
OnToolkitHostingStarted()
void FWidgetBlueprintEditor::OnToolkitHostingStarted (const TSharedRef< IToolkit > & Toolkit) override virtual
Reimplemented from FAssetEditorToolkit.
OnWidgetAnimDrawerSequencerDismissed()
void FWidgetBlueprintEditor::OnWidgetAnimDrawerSequencerDismissed (const TSharedPtr< SWidget > & NewlyFocusedWidget)
Callback for anim drawer closing.
References OnWidgetAnimDrawerSequencerDismissed().
Referenced by OnWidgetAnimDrawerSequencerDismissed().
OnWidgetAnimDrawerSequencerOpened()
void FWidgetBlueprintEditor::OnWidgetAnimDrawerSequencerOpened (FName StatusBarWithDrawerName)
Callback for anim drawer opening.
References OnWidgetAnimDrawerSequencerOpened().
Referenced by OnWidgetAnimDrawerSequencerOpened().
OnWidgetAnimTabSequencerClosed()
void FWidgetBlueprintEditor::OnWidgetAnimTabSequencerClosed (TSharedRef< SDockTab > ClosedTab)
Callback for anim tab closing.
References OnWidgetAnimTabSequencerClosed().
Referenced by OnWidgetAnimTabSequencerClosed().
OnWidgetAnimTabSequencerOpened()
void FWidgetBlueprintEditor::OnWidgetAnimTabSequencerOpened ()
Callback for anim tab opening.
References OnWidgetAnimTabSequencerOpened().
Referenced by OnWidgetAnimTabSequencerOpened().
OpenCreateNativeBaseClassDialog()
void FWidgetBlueprintEditor::OpenCreateNativeBaseClassDialog () protected
PasteWidgets()
void FWidgetBlueprintEditor::PasteWidgets () private
PostRedo()
virtual void FWidgetBlueprintEditor::PostRedo (bool bSuccess) override virtual
Signal that client should run any PostRedo code.
Parameters
bSuccess If true than redo succeeded, false if redo failed
Reimplemented from FBlueprintEditor.
PostUndo()
virtual void FWidgetBlueprintEditor::PostUndo (bool bSuccess) override virtual
Signal that client should run any PostUndo code.
Parameters
bSuccess If true than undo succeeded, false if undo failed
Reimplemented from FBlueprintEditor.
RefreshCurrentAnimation()
const UWidgetAnimation * FWidgetBlueprintEditor::RefreshCurrentAnimation ()
Updates the current animation if it is invalid.
RefreshPreview()
void FWidgetBlueprintEditor::RefreshPreview ()
Immediately rebuilds the preview widget.
RegisterApplicationModes()
virtual void FWidgetBlueprintEditor::RegisterApplicationModes (const TArray< UBlueprint * > & InBlueprints, bool bShouldOpenInDefaultsMode, bool bNewlyCreated = false) override protected virtual
Called during initialization of the blueprint editor to register any application modes.
Reimplemented from FBlueprintEditor.
RemoveAllWidgetsFromTrack()
void FWidgetBlueprintEditor::RemoveAllWidgetsFromTrack (FGuid ObjectId) private
Remove all bindings from a track.
References ObjectId.
RemoveExternalEditorWidget()
int32 FWidgetBlueprintEditor::RemoveExternalEditorWidget (FName ID)
Removes external widget whose lifetime should be managed by this editor.
References ID.
RemoveMissingWidgetsFromTrack()
void FWidgetBlueprintEditor::RemoveMissingWidgetsFromTrack (FGuid ObjectId) private
Remove any missing bindings from a track.
References ObjectId.
RemoveWidgetsFromTrack()
void FWidgetBlueprintEditor::RemoveWidgetsFromTrack (const TArray< FWidgetReference > Widgets, FGuid ObjectId) private
Unbind widgets from a track.
References ObjectId, and Widgets.
ReplaceTrackWithWidgets()
void FWidgetBlueprintEditor::ReplaceTrackWithWidgets (const TArray< FWidgetReference > Widgets, FGuid ObjectId) private
Replace current widget bindings on a track with new widget bindings.
References ObjectId, and Widgets.
SelectObjects()
void FWidgetBlueprintEditor::SelectObjects (const TSet< UObject * > & Objects)
Sets the currently selected set of objects.
SelectWidgets()
void FWidgetBlueprintEditor::SelectWidgets (const TSet< FWidgetReference > & Widgets, bool bAppendOrToggle)
Sets the currently selected set of widgets.
References Widgets.
SetCreateOnCompileSetting()
void FWidgetBlueprintEditor::SetCreateOnCompileSetting (EDisplayOnCompile InCreateOnCompile) static protected
SetDismissOnCompileSetting()
void FWidgetBlueprintEditor::SetDismissOnCompileSetting (EDisplayOnCompile InDismissOnCompile) static protected
SetHoveredWidget()
void FWidgetBlueprintEditor::SetHoveredWidget (FWidgetReference & InHoveredWidget)
The widget we're now hovering over in any particular context, allows multiple views to synchronize feedback on where that widget is in their representation.
References SetHoveredWidget().
Referenced by SetHoveredWidget().
SetIsRespectingLocks()
void FWidgetBlueprintEditor::SetIsRespectingLocks (bool Value)
References SetIsRespectingLocks(), and Value.
Referenced by SetIsRespectingLocks().
SetIsSimulating()
void FWidgetBlueprintEditor::SetIsSimulating (bool bSimulating)
SetSelectedNamedSlot()
void FWidgetBlueprintEditor::SetSelectedNamedSlot (TOptional< FNamedSlotSelection > SelectedNamedSlot)
Sets the selected named slot.
References SelectedNamedSlot.
SetSelectedTemplate()
void FWidgetBlueprintEditor::SetSelectedTemplate (TWeakObjectPtr< UClass > TemplateClass) inline
Set the selected template widget.
Definition at line 174 of file WidgetBlueprintEditor.h.
References SelectedTemplate.
SetSelectedUserWidget()
void FWidgetBlueprintEditor::SetSelectedUserWidget (FAssetData InSelectedUserWidget) inline
Set the selected user widget.
Definition at line 177 of file WidgetBlueprintEditor.h.
References SelectedUserWidget.
SetShowDashedOutlines()
void FWidgetBlueprintEditor::SetShowDashedOutlines (bool Value)
References SetShowDashedOutlines(), and Value.
Referenced by SetShowDashedOutlines().
SyncSelectedWidgetsWithSequencerSelection()
void FWidgetBlueprintEditor::SyncSelectedWidgetsWithSequencerSelection (TArray< FGuid > ObjectGuids) private
Fire off when sequencer selection changed.
SyncSequencerSelectionToSelectedWidgets()
void FWidgetBlueprintEditor::SyncSequencerSelectionToSelectedWidgets () private
Tell sequencer the selected widgets changed.
SyncSequencersMovieSceneData()
void FWidgetBlueprintEditor::SyncSequencersMovieSceneData () private
Tell sequencers movie data changed.
TakeSnapshot()
void FWidgetBlueprintEditor::TakeSnapshot () protected
Tick()
virtual void FWidgetBlueprintEditor::Tick (float DeltaTime) override virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Reimplemented from FBlueprintEditor.
References DeltaTime.
ToggleAnimDrawer()
void FWidgetBlueprintEditor::ToggleAnimDrawer ()
Toggles Anim Drawer, only used for keyboard shortcut.
UE_DEPRECATED() [1/2]
FWidgetBlueprintEditor::UE_DEPRECATED (5. 2, "OnWidgetAnimSequencerDismissed is deprecated, please use OnWidgetAnimDrawerSequencerDismissed instead.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FWidgetBlueprintEditor::UE_DEPRECATED (5. 2, "OnWidgetAnimSequencerOpened is deprecated, please use OnWidgetAnimDrawerSequencerOpened instead.")
Referenced by UE_DEPRECATED().
UpdatePreview()
void FWidgetBlueprintEditor::UpdatePreview (UBlueprint * InBlueprint, bool bInForceFullUpdate) private
Tick the current preview GUI object.
UpdateTrackName()
void FWidgetBlueprintEditor::UpdateTrackName (FGuid ObjectId) private
Update the name of a track to reflect changes in bindings.
References ObjectId.
Field Documentation
AnimDrawerWidget
TSharedPtr<SWidget> FWidgetBlueprintEditor::AnimDrawerWidget private
Widget created for anim drawer.
Definition at line 464 of file WidgetBlueprintEditor.h.
bIsPreviewWidgetSelected
bool FWidgetBlueprintEditor::bIsPreviewWidgetSelected private
True when the selected object is the preview widget.
Used to restore selection after refreshing the preview.
Definition at line 551 of file WidgetBlueprintEditor.h.
bIsRealTime
bool FWidgetBlueprintEditor::bIsRealTime private
Definition at line 515 of file WidgetBlueprintEditor.h.
bIsSequencerDrawerOpen
bool FWidgetBlueprintEditor::bIsSequencerDrawerOpen private
True if sequencer drawer is open.
Definition at line 531 of file WidgetBlueprintEditor.h.
bIsSimulateEnabled
bool FWidgetBlueprintEditor::bIsSimulateEnabled private
Definition at line 512 of file WidgetBlueprintEditor.h.
bPreviewInvalidated
bool FWidgetBlueprintEditor::bPreviewInvalidated private
The preview becomes invalid and needs to be rebuilt on the next tick.
Definition at line 509 of file WidgetBlueprintEditor.h.
bRefreshGeneratedClassAnimations
bool FWidgetBlueprintEditor::bRefreshGeneratedClassAnimations private
When true the animation data in the generated class should be replaced with the current animation data.
Definition at line 534 of file WidgetBlueprintEditor.h.
bRespectLocks
bool FWidgetBlueprintEditor::bRespectLocks private
Definition at line 521 of file WidgetBlueprintEditor.h.
bShowDashedOutlines
bool FWidgetBlueprintEditor::bShowDashedOutlines private
Should the designer show outlines when it creates widgets?
Definition at line 518 of file WidgetBlueprintEditor.h.
bUpdatingExternalSelection
bool FWidgetBlueprintEditor::bUpdatingExternalSelection private
When true the external selection is being updated from changes to the sequencer selection.
Definition at line 548 of file WidgetBlueprintEditor.h.
bUpdatingSequencerSelection
bool FWidgetBlueprintEditor::bUpdatingSequencerSelection private
When true the sequencer selection is being updated from changes to the external selection.
Definition at line 545 of file WidgetBlueprintEditor.h.
CurrentAnimation
TWeakObjectPtr<UWidgetAnimation> FWidgetBlueprintEditor::CurrentAnimation private
The currently viewed animation, if any.
Definition at line 526 of file WidgetBlueprintEditor.h.
Referenced by GetCurrentAnimation().
DesignerCommandList
TSharedPtr< FUICommandList > FWidgetBlueprintEditor::DesignerCommandList
Command list for handling widget actions in the WidgetBlueprintEditor.
Definition at line 290 of file WidgetBlueprintEditor.h.
DrawerSequencer
TSharedPtr<ISequencer> FWidgetBlueprintEditor::DrawerSequencer private
Sequencer for creating and previewing widget animations in drawer.
Definition at line 458 of file WidgetBlueprintEditor.h.
DrawerSequencerOverlay
TWeakPtr<SOverlay> FWidgetBlueprintEditor::DrawerSequencerOverlay private
Overlay used to display UI on top of drawer sequencer.
Definition at line 461 of file WidgetBlueprintEditor.h.
ExternalEditorWidgets
TMap<FName, TSharedPtr<SWidget> > FWidgetBlueprintEditor::ExternalEditorWidgets private
For external widgets to have lifetimes bound to this editor instance.
Definition at line 446 of file WidgetBlueprintEditor.h.
HoveredWidget
FWidgetReference FWidgetBlueprintEditor::HoveredWidget private
The widget currently being hovered over.
Definition at line 506 of file WidgetBlueprintEditor.h.
LibraryViewModel
TSharedPtr<FLibraryViewModel> FWidgetBlueprintEditor::LibraryViewModel private
ViewModel used by the Library View.
Definition at line 540 of file WidgetBlueprintEditor.h.
Referenced by GetLibraryViewModel().
ModeUILayer
TSharedPtr<class FWidgetEditorModeUILayer> FWidgetBlueprintEditor::ModeUILayer private
Used to spawn sidebar tool palette.
Definition at line 500 of file WidgetBlueprintEditor.h.
NoAnimationTextBlockDrawer
TWeakPtr<STextBlock> FWidgetBlueprintEditor::NoAnimationTextBlockDrawer private
A text block which is displayed in the overlay when no animation is selected in drawer.
Definition at line 470 of file WidgetBlueprintEditor.h.
NoAnimationTextBlockTab
TWeakPtr<STextBlock> FWidgetBlueprintEditor::NoAnimationTextBlockTab private
A text block which is displayed in the overlay when no animation is selected.
Definition at line 467 of file WidgetBlueprintEditor.h.
OnEnterWidgetDesigner
FOnEnterWidgetDesigner FWidgetBlueprintEditor::OnEnterWidgetDesigner
Fires after the mode change to Designer.
Definition at line 287 of file WidgetBlueprintEditor.h.
OnHoveredWidgetCleared
FOnHoveredWidgetCleared FWidgetBlueprintEditor::OnHoveredWidgetCleared
Fires when there is no longer any widget being hovered over.
Definition at line 269 of file WidgetBlueprintEditor.h.
OnHoveredWidgetSet
FOnHoveredWidgetSet FWidgetBlueprintEditor::OnHoveredWidgetSet
Fires whenever a new widget is being hovered over.
Definition at line 266 of file WidgetBlueprintEditor.h.
OnSelectedAnimationChanged
FOnSelectedAnimationChanged FWidgetBlueprintEditor::OnSelectedAnimationChanged
Fires whenever the selected animation changes.
Definition at line 278 of file WidgetBlueprintEditor.h.
OnSelectedWidgetsChanged
FOnSelectedWidgetsChanged FWidgetBlueprintEditor::OnSelectedWidgetsChanged
Fires whenever the selected set of widgets changes.
Definition at line 275 of file WidgetBlueprintEditor.h.
OnSelectedWidgetsChanging
FOnSelectedWidgetsChanged FWidgetBlueprintEditor::OnSelectedWidgetsChanging
Fires whenever the selected set of widgets changing.
Definition at line 272 of file WidgetBlueprintEditor.h.
OnWidgetAnimationsUpdated
FOnWidgetAnimationsUpdated FWidgetBlueprintEditor::OnWidgetAnimationsUpdated
Notification for when the preview widget has been updated.
Definition at line 284 of file WidgetBlueprintEditor.h.
OnWidgetBlueprintTransaction
FOnWidgetBlueprintTransaction FWidgetBlueprintEditor::OnWidgetBlueprintTransaction private
Delegate called when a undo/redo transaction happens.
Definition at line 494 of file WidgetBlueprintEditor.h.
Referenced by DECLARE_EVENT().
OnWidgetPreviewUpdated
FOnWidgetPreviewUpdated FWidgetBlueprintEditor::OnWidgetPreviewUpdated
Notification for when the preview widget has been updated.
Definition at line 281 of file WidgetBlueprintEditor.h.
PaletteViewModel
TSharedPtr<FPaletteViewModel> FWidgetBlueprintEditor::PaletteViewModel private
ViewModel used by the Palette and Palette Favorite Views.
Definition at line 537 of file WidgetBlueprintEditor.h.
Referenced by GetPaletteViewModel().
PasteDropLocation
FVector2D FWidgetBlueprintEditor::PasteDropLocation
Paste Metadata.
Definition at line 296 of file WidgetBlueprintEditor.h.
PreviewBlueprint
UWidgetBlueprint* FWidgetBlueprintEditor::PreviewBlueprint private
The Blueprint associated with the current preview.
Definition at line 473 of file WidgetBlueprintEditor.h.
PreviewMode
TSharedPtr<UE::UMG::Editor::FPreviewMode> FWidgetBlueprintEditor::PreviewMode private
Definition at line 542 of file WidgetBlueprintEditor.h.
Referenced by GetPreviewMode().
PreviewScene
FPreviewScene FWidgetBlueprintEditor::PreviewScene private
The preview scene that owns the preview GUI.
Definition at line 443 of file WidgetBlueprintEditor.h.
PreviewWidgetPtr
TWeakObjectPtr<UUserWidget> FWidgetBlueprintEditor::PreviewWidgetPtr mutable private
The preview GUI object.
Definition at line 491 of file WidgetBlueprintEditor.h.
QueuedDesignerActions
TArray< TFunction<void()> > FWidgetBlueprintEditor::QueuedDesignerActions private
Definition at line 523 of file WidgetBlueprintEditor.h.
SelectedNamedSlot
TOptional<FNamedSlotSelection> FWidgetBlueprintEditor::SelectedNamedSlot private
The currently selected named slot.
Definition at line 488 of file WidgetBlueprintEditor.h.
Referenced by SetSelectedNamedSlot().
SelectedObjects
TSet< TWeakObjectPtr<UObject> > FWidgetBlueprintEditor::SelectedObjects private
The currently selected objects in the designer.
Definition at line 479 of file WidgetBlueprintEditor.h.
SelectedTemplate
TWeakObjectPtr<UClass> FWidgetBlueprintEditor::SelectedTemplate private
The last selected template widget in the palette view.
Definition at line 482 of file WidgetBlueprintEditor.h.
Referenced by GetSelectedTemplate(), and SetSelectedTemplate().
SelectedUserWidget
FAssetData FWidgetBlueprintEditor::SelectedUserWidget private
AssetData of Selected UserWidget.
Definition at line 485 of file WidgetBlueprintEditor.h.
Referenced by GetSelectedUserWidget(), and SetSelectedUserWidget().
SelectedWidgets
TSet< FWidgetReference > FWidgetBlueprintEditor::SelectedWidgets private
The currently selected preview widgets in the preview GUI.
Definition at line 476 of file WidgetBlueprintEditor.h.
SequencerAddTrackExtenderHandle
FDelegateHandle FWidgetBlueprintEditor::SequencerAddTrackExtenderHandle private
Definition at line 528 of file WidgetBlueprintEditor.h.
Sequencers
TArray<TWeakPtr<ISequencer> > FWidgetBlueprintEditor::Sequencers private
List of created sequencers.
Definition at line 449 of file WidgetBlueprintEditor.h.
TabSequencer
TSharedPtr<ISequencer> FWidgetBlueprintEditor::TabSequencer private
Sequencer for creating and previewing widget animations in tabs.
Definition at line 452 of file WidgetBlueprintEditor.h.
TabSequencerOverlay
TWeakPtr<SOverlay> FWidgetBlueprintEditor::TabSequencerOverlay private
Overlay used to display UI on top of tab sequencer.
Definition at line 455 of file WidgetBlueprintEditor.h.
ToolPaletteCommands
TArray< TSharedPtr<FUICommandInfo> > FWidgetBlueprintEditor::ToolPaletteCommands
Commands for switching between tool palettes.
Definition at line 293 of file WidgetBlueprintEditor.h.
WidgetHandlePool
TArray< TWeakPtr<FWidgetHandle> > FWidgetBlueprintEditor::WidgetHandlePool private
The widget references out in the ether that may need to be updated after being issued.
Definition at line 503 of file WidgetBlueprintEditor.h.
WidgetToolbar
TSharedPtr<class FWidgetBlueprintEditorToolbar> FWidgetBlueprintEditor::WidgetToolbar private
The toolbar builder associated with this editor.
Definition at line 497 of file WidgetBlueprintEditor.h.
Referenced by GetWidgetToolbarBuilder().
The documentation for this class was generated from the following file:
WidgetBlueprintEditor.h