Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FEditLayerRendererState Class Reference
UE::Landscape::EditLayers::FEditLayerRendererState Class Reference
FEditLayerRendererState describes the entire state of an edit layer renderer : what it is capable of doing (SupportedTargetTypeState, immutable) and what it is currently doing (EnabledTargetTypeState, mutable) These states are provided by IEditLayerRendererProvider in order to describe both what the renderer can do and what it currently does by default.
#include "LandscapeEditLayerRendererState.h"
Public Member Functions
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const FEditLayerTargetTypeState &GetEnabledTargetTypeState() const
Returns a mask of all target types / weightmaps enabled on this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const FEditLayerTargetTypeState &GetSupportedTargetTypeState() const
Returns a mask of all target types / weightmaps supported by this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") FEditLayerTargetTypeState GetActiveTargetTypeState() const
Returns a mask of all target types / weightmaps supported and enabled on this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API bool IsTargetActive(ELandscapeToolTargetType InTargetType
Indicates whether a given target type and weightmap layer name is currently supported and enabled by this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API bool IsTargetActive(ELandscapeToolTargetType InTargetType
Indicates whether a given target type and weightmap layer name is currently supported and enabled by this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API bool IsTargetActiveChecked(ELandscapeToolTargetType InTargetType
Indicates whether a given target type and weightmap layer name is currently supported and enabled by this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ELandscapeToolTargetTypeFlags GetActiveTargetTypeMask() const
Returns the mask of target types that are both supported and enabled by this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API explicit FEditLayerRendererState(const FMergeContext *InMergeContext
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API explicit FEditLayerRendererState(const FMergeContext *InMergeContext)
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TArray< FName > GetActiveTargetWeightmaps() const
Returns a list of all weightmaps supported and enabled by this renderer (only relevant for ELandscapeToolTargetType::Weightmap (and ELandscapeToolTargetType::Visibility))
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> GetActiveTargetWeightmapBitIndices() const
Returns a list of all weightmaps supported and enabled by this renderer (only relevant for ELandscapeToolTargetType::Weightmap (and ELandscapeToolTargetType::Visibility))
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void DisableTargetType(ELandscapeToolTargetType InTargetType)
Mutates the EnabledTargetTypeState by removing the target type in parameter from the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void DisableTargetTypeMask(ELandscapeToolTargetTypeFlags InTargetTypeMask)
Mutates the EnabledTargetTypeState by removing the target type mask in parameter from the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void DisableWeightmap(const FName &InWeightmapLayerName)
Mutates the EnabledTargetTypeState by removing the weightmap in parameter from the list of enabled weightmaps, if it is known to the merge context.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void DisableWeightmap(int32 InWeightmapLayerIndex)
Mutates the EnabledTargetTypeState by removing the weightmap in parameter from the list of enabled weightmaps.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void DisableWeightmapChecked(const FName &InWeightmapLayerName)
Mutates the EnabledTargetTypeState by removing the weightmap in parameter from the list of enabled weightmaps.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void EnableTargetType(ELandscapeToolTargetType InTargetType)
Mutates the EnabledTargetTypeState by adding the target type in parameter to the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void EnableTargetTypeMask(ELandscapeToolTargetTypeFlags InTargetTypeMask)
Mutates the EnabledTargetTypeState by adding the target type mask in parameter to the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void EnableWeightmap(ELandscapeToolTargetType InTargetType
Mutates the EnabledTargetTypeState by adding the weightmap in parameter to the list of enabled weightmaps, if it is known to the merge context.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void EnableWeightmap(ELandscapeToolTargetType InTargetType
Mutates the EnabledTargetTypeState by adding the weightmap in parameter to the list of enabled weightmaps.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void EnableWeightmapChecked(ELandscapeToolTargetType InTargetType
Mutates the EnabledTargetTypeState by adding the weightmap in parameter to the list of enabled weightmaps.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") static const FEditLayerRendererState &GetDummyRendererState()
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") TArray< TBitArray<> > GetTargetLayerGroups() const
Returns the target layer groups associated with this renderer.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") TScriptInterface< ILandscapeEditLayerRenderer > GetRenderer() const
Returns the edit layer renderer which this state relates to.
Data Fields
TScriptInterface< ILandscapeEditLayerRenderer > InRenderer
int32 InWeightmapLayerIndex = INDEX_NONE) const
const FName & InWeightmapLayerName = NAME_None) const
Private Member Functions
FEditLayerRendererState ()=default
void UpdateActiveTargetTypeState ()
Private Attributes
FEditLayerTargetTypeState ActiveTargetTypeState = FEditLayerTargetTypeState::GetDummyTargetTypeState()
Intersection of SupportedTargetTypeState and EnabledTargetTypeState (defines what is both supported and enabled on this renderer)
FString DebugName
For debug purposes : this is the same as Renderer->GetEditLayerRendererDebugName() but having a member makes it easier to debug in the watch window.
FEditLayerTargetTypeState EnabledTargetTypeState = FEditLayerTargetTypeState::GetDummyTargetTypeState()
Struct that contains the enabled target types and the which weightmap are currently enabled by this renderer.
const FMergeContext * MergeContext = nullptr
Global context being used for this merge : contains generic information about the landscape, its available layer names, etc.
TScriptInterface< ILandscapeEditLayerRenderer > Renderer
Renderer associated with this state.
PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS FEditLayerTargetTypeState SupportedTargetTypeState = FEditLayerTargetTypeState::GetDummyTargetTypeState()
Struct that contains the supported target types and the which weightmap are supported by this renderer.
PRAGMA_ENABLE_EXPERIMENTAL_WARNINGS TArray< TBitArray<> > TargetLayerGroups
Detailed Description
FEditLayerRendererState describes the entire state of an edit layer renderer : what it is capable of doing (SupportedTargetTypeState, immutable) and what it is currently doing (EnabledTargetTypeState, mutable) These states are provided by IEditLayerRendererProvider in order to describe both what the renderer can do and what it currently does by default.
e.g. a disabled edit layer supports rendering heightmaps but its enabled state for the heightmap target type is false. This way, the user can selectively enable it at merge time without altering the entire landscape's state (i.e. just for the purpose of a specific merge render) A target type must be both supported and enabled on a given edit layer renderer in order for this renderer to render anything. It also describes the target layer groups this renderer needs when rendering its weightmap (i.e. which weightmap needs to be rendered with which weightmaps : e.g. for weight blending)
Definition at line 31 of file LandscapeEditLayerRendererState.h.
Constructor & Destructor Documentation
FEditLayerRendererState()
UE::Landscape::EditLayers::FEditLayerRendererState::FEditLayerRendererState () private default
Referenced by UE_EXPERIMENTAL().
Member Function Documentation
UE_EXPERIMENTAL() [1/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const & inline
Returns a mask of all target types / weightmaps enabled on this renderer.
Definition at line 55 of file LandscapeEditLayerRendererState.h.
References EnabledTargetTypeState, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [2/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const & inline
Returns a mask of all target types / weightmaps supported by this renderer.
Definition at line 51 of file LandscapeEditLayerRendererState.h.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and SupportedTargetTypeState.
UE_EXPERIMENTAL() [3/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Returns a mask of all target types / weightmaps supported and enabled on this renderer.
Definition at line 59 of file LandscapeEditLayerRendererState.h.
References ActiveTargetTypeState, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [4/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Indicates whether a given target type and weightmap layer name is currently supported and enabled by this renderer.
Parameters
InTargetType the requested target type (heightmap/weightmap/visibility)
InWeightmapLayerName (optional) is the requested weightmap, only relevant for the ELandscapeToolTargetType::Weightmap case
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [5/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Indicates whether a given target type and weightmap layer name is currently supported and enabled by this renderer.
Asserts if the layer index isn't known to the merge context (except if INDEX_NONE)
Parameters
InTargetType the requested target type (heightmap/weightmap/visibility)
InWeightmapLayerIndex (optional) is the requested weightmap's index in the merge index, only relevant for the ELandscapeToolTargetType::Weightmap case
References INDEX_NONE, InWeightmapLayerIndex, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [6/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Indicates whether a given target type and weightmap layer name is currently supported and enabled by this renderer.
Asserts if the layer name isn't known to the merge context (except if NAME_None)
Parameters
InTargetType the requested target type (heightmap/weightmap/visibility)
InWeightmapLayerName (optional) is the requested weightmap, only relevant for the ELandscapeToolTargetType::Weightmap case
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [7/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns the mask of target types that are both supported and enabled by this renderer.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [8/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [9/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [10/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns a list of all weightmaps supported and enabled by this renderer (only relevant for ELandscapeToolTargetType::Weightmap (and ELandscapeToolTargetType::Visibility))
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [11/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns a list of all weightmaps supported and enabled by this renderer (only relevant for ELandscapeToolTargetType::Weightmap (and ELandscapeToolTargetType::Visibility))
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [12/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by removing the target type in parameter from the mask of active target types.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [13/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by removing the target type mask in parameter from the mask of active target types.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [14/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Mutates the EnabledTargetTypeState by removing the weightmap in parameter from the list of enabled weightmaps, if it is known to the merge context.
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [15/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by removing the weightmap in parameter from the list of enabled weightmaps.
Asserts if the layer index isn't known to the merge context
References InWeightmapLayerIndex, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [16/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Mutates the EnabledTargetTypeState by removing the weightmap in parameter from the list of enabled weightmaps.
Asserts if the layer index isn't known to the merge context
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [17/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by adding the target type in parameter to the mask of active target types.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [18/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by adding the target type mask in parameter to the mask of active target types.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [19/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by adding the weightmap in parameter to the list of enabled weightmaps, if it is known to the merge context.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [20/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by adding the weightmap in parameter to the list of enabled weightmaps.
Asserts if the layer index isn't known to the merge context
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [21/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Mutates the EnabledTargetTypeState by adding the weightmap in parameter to the list of enabled weightmaps.
Asserts if the layer name isn't known to the merge context
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [22/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
References FEditLayerRendererState(), and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [23/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Returns the target layer groups associated with this renderer.
A target layer group is a set of target layers (weightmaps) that depend on one another in order to produce the output target layers. This allows to implement "horizontal blending", where weightmaps can be blended with one another at each step of the landscape edit layers merge algorithm
Definition at line 157 of file LandscapeEditLayerRendererState.h.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and TargetLayerGroups.
UE_EXPERIMENTAL() [24/24]
UE::Landscape::EditLayers::FEditLayerRendererState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Returns the edit layer renderer which this state relates to.
Definition at line 47 of file LandscapeEditLayerRendererState.h.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and Renderer.
UpdateActiveTargetTypeState()
void UE::Landscape::EditLayers::FEditLayerRendererState::UpdateActiveTargetTypeState () private
Field Documentation
ActiveTargetTypeState
FEditLayerTargetTypeState UE::Landscape::EditLayers::FEditLayerRendererState::ActiveTargetTypeState = FEditLayerTargetTypeState::GetDummyTargetTypeState() private
Intersection of SupportedTargetTypeState and EnabledTargetTypeState (defines what is both supported and enabled on this renderer)
Definition at line 181 of file LandscapeEditLayerRendererState.h.
Referenced by UE_EXPERIMENTAL().
DebugName
FString UE::Landscape::EditLayers::FEditLayerRendererState::DebugName private
For debug purposes : this is the same as Renderer->GetEditLayerRendererDebugName() but having a member makes it easier to debug in the watch window.
Definition at line 171 of file LandscapeEditLayerRendererState.h.
EnabledTargetTypeState
FEditLayerTargetTypeState UE::Landscape::EditLayers::FEditLayerRendererState::EnabledTargetTypeState = FEditLayerTargetTypeState::GetDummyTargetTypeState() private
Struct that contains the enabled target types and the which weightmap are currently enabled by this renderer.
Can be set by the user using EnableTargetType.
Definition at line 178 of file LandscapeEditLayerRendererState.h.
Referenced by UE_EXPERIMENTAL().
InRenderer
TScriptInterface<ILandscapeEditLayerRenderer> UE::Landscape::EditLayers::FEditLayerRendererState::InRenderer
Definition at line 44 of file LandscapeEditLayerRendererState.h.
InWeightmapLayerIndex
int32 UE::Landscape::EditLayers::FEditLayerRendererState::InWeightmapLayerIndex = INDEX_NONE) const
Definition at line 94 of file LandscapeEditLayerRendererState.h.
Referenced by UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
InWeightmapLayerName
const FName & UE::Landscape::EditLayers::FEditLayerRendererState::InWeightmapLayerName = NAME_None) const
Definition at line 82 of file LandscapeEditLayerRendererState.h.
Referenced by UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
MergeContext
const FMergeContext* UE::Landscape::EditLayers::FEditLayerRendererState::MergeContext = nullptr private
Global context being used for this merge : contains generic information about the landscape, its available layer names, etc.
Definition at line 165 of file LandscapeEditLayerRendererState.h.
Renderer
TScriptInterface<ILandscapeEditLayerRenderer> UE::Landscape::EditLayers::FEditLayerRendererState::Renderer private
Renderer associated with this state.
Definition at line 168 of file LandscapeEditLayerRendererState.h.
Referenced by UE_EXPERIMENTAL().
SupportedTargetTypeState
PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS FEditLayerTargetTypeState UE::Landscape::EditLayers::FEditLayerRendererState::SupportedTargetTypeState = FEditLayerTargetTypeState::GetDummyTargetTypeState() private
Struct that contains the supported target types and the which weightmap are supported by this renderer.
Immutable.
Definition at line 175 of file LandscapeEditLayerRendererState.h.
Referenced by UE_EXPERIMENTAL().
TargetLayerGroups
PRAGMA_ENABLE_EXPERIMENTAL_WARNINGS TArray<TBitArray<> > UE::Landscape::EditLayers::FEditLayerRendererState::TargetLayerGroups private
Definition at line 187 of file LandscapeEditLayerRendererState.h.
Referenced by UE_EXPERIMENTAL().
The documentation for this class was generated from the following file:
LandscapeEditLayerRendererState.h