Unreal Engine 5.6 C++ API: UE::Chaos::OutfitAsset::FCollectionOutfitFacade Class Reference
UE::Chaos::OutfitAsset::FCollectionOutfitFacade Class Reference final
Cloth outfit collection facade.
#include "CollectionOutfitFacade.h"
Public Member Functions
FCollectionOutfitFacade ()=delete
FCollectionOutfitFacade (const FCollectionOutfitFacade &)=delete
CHAOSOUTFITASSETENGINE_API FCollectionOutfitFacade (const TSharedRef< FManagedArrayCollection > &InManagedArrayCollection)
FCollectionOutfitFacade (FCollectionOutfitFacade &&)=default
CHAOSOUTFITASSETENGINE_API FCollectionOutfitFacade (FManagedArrayCollection &InManagedArrayCollection)
virtual CHAOSOUTFITASSETENGINE_API ~FCollectionOutfitFacade () override
CHAOSOUTFITASSETENGINE_API int32 AddBodySize (const FString &Name, const TConstArrayView< FString > BodyPartsSkeletalMeshes, const TMap< FString, float > &Measurements, const FRBFInterpolationDataWrapper &InterpolationData)
Add a new body size and returns its index.
CHAOSOUTFITASSETENGINE_API void AddOutfit (const FGuid &Guid, const int32 BodySize, const UChaosClothAssetBase &ClothAssetBase)
Add a new sized outfit under the specified outfit GUID.
CHAOSOUTFITASSETENGINE_API void Append (const FCollectionOutfitConstFacade &Other, int32 SelectedBodySize=INDEX_NONE)
Append an existing outfit facade to this collection.
void Append (const FManagedArrayCollection &InManagedArrayCollection)
Append an existing outfit facade to this collection.
CHAOSOUTFITASSETENGINE_API void DefineSchema ()
Add the Selection attributes to the underlying collection.
int32 FindOrAddBodySize (const FString &Name)
Find or add a new body size and returns its index.
FCollectionOutfitFacade & operator= (const FCollectionOutfitFacade &)=delete
FCollectionOutfitFacade & operator= (FCollectionOutfitFacade &&)=default
CHAOSOUTFITASSETENGINE_API void Reset ()
Remove all outfit and size information from this collection.
Public Member Functions inherited from UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade
FCollectionOutfitConstFacade ()=delete
FCollectionOutfitConstFacade (const FCollectionOutfitConstFacade &)=delete
CHAOSOUTFITASSETENGINE_API FCollectionOutfitConstFacade (const FManagedArrayCollection &InManagedArrayCollection)
CHAOSOUTFITASSETENGINE_API FCollectionOutfitConstFacade (const TSharedRef< const FManagedArrayCollection > &InManagedArrayCollection)
FCollectionOutfitConstFacade (FCollectionOutfitConstFacade &&)=default
virtual CHAOSOUTFITASSETENGINE_API ~FCollectionOutfitConstFacade ()
CHAOSOUTFITASSETENGINE_API int32 FindBodySize (const FString &Name) const
Return the body size index for the specified name, or INDEX_NONE if it doesn't exist in this outfit.
CHAOSOUTFITASSETENGINE_API int32 FindClosestBodySize (const TMap< FString, float > &Measurements) const
Return the closest size to the specified measurements, or INDEX_NONE if this outfit has no sizes or the measurements are incomplete.
CHAOSOUTFITASSETENGINE_API int32 FindClosestBodySize (const USkeletalMesh &BodyPart) const
Return the closest size to the specified body, or INDEX_NONE if this outfit has no sizes or the body has no measurement data.
CHAOSOUTFITASSETENGINE_API int32 GetBodySizeBodyPartCount (const int32 BodySize) const
Return the body size body part count.
CHAOSOUTFITASSETENGINE_API int32 GetBodySizeBodyPartOffset (const int32 BodySize) const
Return the body size body part offset (to index into the global body part array).
CHAOSOUTFITASSETENGINE_API TConstArrayView< FString > GetBodySizeBodyPartsSkeletalMeshes (const int32 BodySize) const
Return the body part skeletal meshes path name for the specified body size.
CHAOSOUTFITASSETENGINE_API FRBFInterpolationDataWrapper GetBodySizeInterpolationData (const int32 BodySize) const
Return for the specified body size.
CHAOSOUTFITASSETENGINE_API TMap< FString, float > GetBodySizeMeasurements (const int32 BodySize) const
Return the body measurements stored for this specified body size.
CHAOSOUTFITASSETENGINE_API const FString & GetBodySizeName (const int32 BodySize) const
Return the specified body size name which is unique.
CHAOSOUTFITASSETENGINE_API int32 GetNumBodySizes () const
Return the number of body sizes.
CHAOSOUTFITASSETENGINE_API TArray< FString > GetOutfitBodyPartsSkeletalMeshes () const
Return all unique body part skeletal meshes used by this outfit.
CHAOSOUTFITASSETENGINE_API TArray< int32 > GetOutfitBodySizes (const FGuid &Guid) const
Return the body size available for the specified outfit GUID.
CHAOSOUTFITASSETENGINE_API TArray< FGuid > GetOutfitGuids () const
Return the sized outfits GUID, one per sized outfit which can contain different sized outfits.
CHAOSOUTFITASSETENGINE_API const FString & GetOutfitName (const FGuid &Guid, const int32 BodySize) const
Return the name of the original asset making up the specified outfit body size.
CHAOSOUTFITASSETENGINE_API TMap< FGuid, FString > GetOutfitPieces (const FGuid &Guid, const int32 BodySize) const
Return the outfit pieces making up the specified outfit body size.
CHAOSOUTFITASSETENGINE_API TConstArrayView< FGuid > GetOutfitPiecesGuids () const
Return all outfit pieces asset GUIDs.
bool HasBodySize (const FString &Name) const
Return whether this body size already exist.
CHAOSOUTFITASSETENGINE_API bool HasValidBodySize (bool bBodyPartMustExist=false, bool bMeasurementsMustExist=false, bool bInterpolationDataMustExist=false) const
Return whether this outfit has at least one valid body size.
CHAOSOUTFITASSETENGINE_API bool IsValid () const
Return whether the facade is defined on the collection.
FCollectionOutfitConstFacade & operator= (const FCollectionOutfitConstFacade &)=delete
FCollectionOutfitConstFacade & operator= (FCollectionOutfitConstFacade &&)=default
Private Member Functions
void AddOutfit (const FGuid &Guid, const int32 BodySize, const FString &Name, const TMap< FGuid, FString > &Pieces)
Private::FOutfitCollection * GetOutfitCollection ()
Additional Inherited Members
Protected Member Functions inherited from UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade
const Private::FOutfitCollection * GetOutfitCollection () const
Protected Attributes inherited from UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade
TSharedPtr< const FManagedArrayCollection > ManagedArrayCollection
TUniquePtr< const Private::FOutfitCollection > OutfitCollection
Detailed Description
Cloth outfit collection facade.
Non-const access (read/write) version.
Definition at line 119 of file CollectionOutfitFacade.h.
Constructor & Destructor Documentation
FCollectionOutfitFacade() [1/5]
CHAOSOUTFITASSETENGINE_API UE::Chaos::OutfitAsset::FCollectionOutfitFacade::FCollectionOutfitFacade (const TSharedRef< FManagedArrayCollection > & InManagedArrayCollection) explicit
References UE_API.
Referenced by FCollectionOutfitFacade(), FCollectionOutfitFacade(), operator=(), and operator=().
FCollectionOutfitFacade() [2/5]
CHAOSOUTFITASSETENGINE_API UE::Chaos::OutfitAsset::FCollectionOutfitFacade::FCollectionOutfitFacade (FManagedArrayCollection & InManagedArrayCollection) explicit
References UE_API.
FCollectionOutfitFacade() [3/5]
UE::Chaos::OutfitAsset::FCollectionOutfitFacade::FCollectionOutfitFacade () delete
FCollectionOutfitFacade() [4/5]
UE::Chaos::OutfitAsset::FCollectionOutfitFacade::FCollectionOutfitFacade (const FCollectionOutfitFacade &) delete
References FCollectionOutfitFacade().
FCollectionOutfitFacade() [5/5]
UE::Chaos::OutfitAsset::FCollectionOutfitFacade::FCollectionOutfitFacade (FCollectionOutfitFacade &&) default
References FCollectionOutfitFacade().
~FCollectionOutfitFacade()
virtual CHAOSOUTFITASSETENGINE_API UE::Chaos::OutfitAsset::FCollectionOutfitFacade::~FCollectionOutfitFacade () override virtual
References UE_API.
Member Function Documentation
AddBodySize()
CHAOSOUTFITASSETENGINE_API int32 UE::Chaos::OutfitAsset::FCollectionOutfitFacade::AddBodySize (const FString & Name, const TConstArrayView< FString > BodyPartsSkeletalMeshes, const TMap< FString, float > & Measurements, const FRBFInterpolationDataWrapper & InterpolationData)
Add a new body size and returns its index.
Any pre-existing sizes data will be replaced.
References Name, and UE_API.
Referenced by FindOrAddBodySize().
AddOutfit() [1/2]
void UE::Chaos::OutfitAsset::FCollectionOutfitFacade::AddOutfit (const FGuid & Guid, const int32 BodySize, const FString & Name, const TMap< FGuid, FString > & Pieces) private
References Guid, and Name.
AddOutfit() [2/2]
CHAOSOUTFITASSETENGINE_API void UE::Chaos::OutfitAsset::FCollectionOutfitFacade::AddOutfit (const FGuid & Guid, const int32 BodySize, const UChaosClothAssetBase & ClothAssetBase)
Add a new sized outfit under the specified outfit GUID.
Any pre-existing sizes data will be replaced.
References Guid, and UE_API.
Append() [1/2]
CHAOSOUTFITASSETENGINE_API void UE::Chaos::OutfitAsset::FCollectionOutfitFacade::Append (const FCollectionOutfitConstFacade & Other, int32 SelectedBodySize = INDEX_NONE)
Append an existing outfit facade to this collection.
Any pre-existing sizes data will be replaced.
Parameters
Other The source outfit collection to get the data from.
SelectedBodySize The body size of the source outfit to append, or INDEX_NONE to append all sizes.
References UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FCollectionOutfitConstFacade(), INDEX_NONE, Other, and UE_API.
Referenced by Append().
Append() [2/2]
void UE::Chaos::OutfitAsset::FCollectionOutfitFacade::Append (const FManagedArrayCollection & InManagedArrayCollection) inline
Append an existing outfit facade to this collection.
Any pre-existing sizes data will be replaced.
Definition at line 177 of file CollectionOutfitFacade.h.
References UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FCollectionOutfitConstFacade(), Append(), and Other.
DefineSchema()
CHAOSOUTFITASSETENGINE_API void UE::Chaos::OutfitAsset::FCollectionOutfitFacade::DefineSchema ()
Add the Selection attributes to the underlying collection.
References UE_API.
FindOrAddBodySize()
int32 UE::Chaos::OutfitAsset::FCollectionOutfitFacade::FindOrAddBodySize (const FString & Name) inline
Find or add a new body size and returns its index.
Definition at line 149 of file CollectionOutfitFacade.h.
References AddBodySize(), UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FindBodySize(), INDEX_NONE, and Name.
GetOutfitCollection()
Private::FOutfitCollection * UE::Chaos::OutfitAsset::FCollectionOutfitFacade::GetOutfitCollection () inline private
Definition at line 190 of file CollectionOutfitFacade.h.
References UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::OutfitCollection.
operator=() [1/2]
FCollectionOutfitFacade & UE::Chaos::OutfitAsset::FCollectionOutfitFacade::operator= (const FCollectionOutfitFacade &) delete
References FCollectionOutfitFacade().
operator=() [2/2]
FCollectionOutfitFacade & UE::Chaos::OutfitAsset::FCollectionOutfitFacade::operator= (FCollectionOutfitFacade &&) default
References FCollectionOutfitFacade().
Reset()
CHAOSOUTFITASSETENGINE_API void UE::Chaos::OutfitAsset::FCollectionOutfitFacade::Reset ()
Remove all outfit and size information from this collection.
References UE_API.
The documentation for this class was generated from the following file:
CollectionOutfitFacade.h