Unreal Engine 5.6 C++ API: UE::Geometry::FTriangleLinearization Class Reference
UE::Geometry::FTriangleLinearization Class Reference
Used linearize the TriIds in a mesh as a single array and allow mapping from array offset to mesh TriId.
#include "MeshLinearization.h"
Public Member Functions
FTriangleLinearization ()=default
FTriangleLinearization (const FDynamicMesh3 &DynamicMesh)
int32 NumTris () const
void Reset (const FDynamicMesh3 &DynamicMesh)
Public Member Functions inherited from UE::Geometry::FElementLinearization
FElementLinearization ()=default
void Empty ()
int32 GetId (int32 Index) const
int32 GetIndex (int32 Id) const
bool IsValidId (int32 Id) const
bool IsValidIndex (int32 Index) const
int32 MaxId () const
int32 NumIds () const
int32 NumIndices () const
template<typename IterableType>
void Populate (const int32 MaxId, const int32 Count, IterableType Iterable)
const TArray< int32 > & ToId () const
const TArray< int32 > & ToIndex () const
Private Member Functions
FTriangleLinearization (const FTriangleLinearization &)
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::FElementLinearization
TArray< int32 > ToIdMap
TArray< int32 > ToIndexMap
Detailed Description
Used linearize the TriIds in a mesh as a single array and allow mapping from array offset to mesh TriId.
Definition at line 118 of file MeshLinearization.h.
Constructor & Destructor Documentation
FTriangleLinearization() [1/3]
UE::Geometry::FTriangleLinearization::FTriangleLinearization () default
Referenced by FTriangleLinearization().
FTriangleLinearization() [2/3]
UE::Geometry::FTriangleLinearization::FTriangleLinearization (const FDynamicMesh3 & DynamicMesh) inline
Definition at line 123 of file MeshLinearization.h.
References Reset.
FTriangleLinearization() [3/3]
UE::Geometry::FTriangleLinearization::FTriangleLinearization (const FTriangleLinearization &) private
References FTriangleLinearization().
Member Function Documentation
NumTris()
int32 UE::Geometry::FTriangleLinearization::NumTris () const inline
Definition at line 134 of file MeshLinearization.h.
References UE::Geometry::FElementLinearization::NumIds().
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructMeanValueWeightLaplacian(), and UE::MeshDeformation::ConstructTriangleDataArray().
Reset()
void UE::Geometry::FTriangleLinearization::Reset (const FDynamicMesh3 & DynamicMesh) inline
Definition at line 128 of file MeshLinearization.h.
References UE::Geometry::FElementLinearization::Empty(), UE::Geometry::FDynamicMesh3::MaxTriangleID(), UE::Geometry::FElementLinearization::Populate(), UE::Geometry::FDynamicMesh3::TriangleCount(), and UE::Geometry::FDynamicMesh3::TriangleIndicesItr().
The documentation for this class was generated from the following file:
MeshLinearization.h