Unreal Engine 5.6 C++ API: FSlateAttributeMetaData::FGetterItem Struct Reference
FSlateAttributeMetaData::FGetterItem Struct Reference
Public Member Functions
FGetterItem (const FGetterItem &)=delete
FGetterItem (FGetterItem &&)=default
FGetterItem (FSlateAttributeBase *InAttribute, uint32 InSortOrder, TUniquePtr< SlateAttributePrivate::ISlateAttributeGetter > &&InGetter)
FGetterItem (FSlateAttributeBase *InAttribute, uint32 InSortOrder, TUniquePtr< SlateAttributePrivate::ISlateAttributeGetter > &&InGetter, const FSlateAttributeDescriptor::FAttribute *InAttributeDescriptor)
const SlateAttributePrivate::ISlateAttributeContainer * GetAttributeContainer () const
FName GetAttributeName (const SWidget &OwningWidget) const
If available, return the name of the attribute.
bool operator< (const FGetterItem &Other) const
FGetterItem & operator= (const FGetterItem &)=delete
Data Fields
FSlateAttributeBase * Attribute
int32 AttributeContainerOffset
const FSlateAttributeDescriptor::FAttribute * CachedAttributeDescriptor
TUniquePtr< SlateAttributePrivate::ISlateAttributeGetter > Getter
uint32 SortOrder
Detailed Description
Definition at line 135 of file SlateAttributeMetaData.h.
Constructor & Destructor Documentation
FGetterItem() [1/4]
FSlateAttributeMetaData::FGetterItem::FGetterItem (const FGetterItem &) delete
References FGetterItem().
Referenced by FGetterItem(), FGetterItem(), operator<(), and operator=().
FGetterItem() [2/4]
FSlateAttributeMetaData::FGetterItem::FGetterItem (FGetterItem &&) default
References FGetterItem().
FGetterItem() [3/4]
FSlateAttributeMetaData::FGetterItem::FGetterItem (FSlateAttributeBase * InAttribute, uint32 InSortOrder, TUniquePtr< SlateAttributePrivate::ISlateAttributeGetter > && InGetter) inline
Definition at line 140 of file SlateAttributeMetaData.h.
References Attribute, AttributeContainerOffset, CachedAttributeDescriptor, Getter, MoveTemp(), and SortOrder.
FGetterItem() [4/4]
FSlateAttributeMetaData::FGetterItem::FGetterItem (FSlateAttributeBase * InAttribute, uint32 InSortOrder, TUniquePtr< SlateAttributePrivate::ISlateAttributeGetter > && InGetter, const FSlateAttributeDescriptor::FAttribute * InAttributeDescriptor) inline
Definition at line 147 of file SlateAttributeMetaData.h.
References Attribute, AttributeContainerOffset, CachedAttributeDescriptor, Getter, MoveTemp(), and SortOrder.
Member Function Documentation
GetAttributeContainer()
const SlateAttributePrivate::ISlateAttributeContainer * FSlateAttributeMetaData::FGetterItem::GetAttributeContainer () const
Returns
a pointer to the attribute container if the SlateAttribute type is Contained.
Referenced by operator<().
GetAttributeName()
FName FSlateAttributeMetaData::FGetterItem::GetAttributeName (const SWidget & OwningWidget) const
If available, return the name of the attribute.
operator<()
bool FSlateAttributeMetaData::FGetterItem::operator< (const FGetterItem & Other) const inline
Definition at line 161 of file SlateAttributeMetaData.h.
References FGetterItem(), AttributeContainerOffset, Container, GetAttributeContainer(), Other, and SortOrder.
operator=()
FGetterItem & FSlateAttributeMetaData::FGetterItem::operator= (const FGetterItem &) delete
References FGetterItem().
Field Documentation
Attribute
FSlateAttributeBase* FSlateAttributeMetaData::FGetterItem::Attribute
Definition at line 155 of file SlateAttributeMetaData.h.
Referenced by FGetterItem(), and FGetterItem().
AttributeContainerOffset
int32 FSlateAttributeMetaData::FGetterItem::AttributeContainerOffset
Definition at line 159 of file SlateAttributeMetaData.h.
Referenced by FGetterItem(), FGetterItem(), and operator<().
CachedAttributeDescriptor
const FSlateAttributeDescriptor::FAttribute* FSlateAttributeMetaData::FGetterItem::CachedAttributeDescriptor
Definition at line 157 of file SlateAttributeMetaData.h.
Referenced by FGetterItem(), and FGetterItem().
Getter
TUniquePtr<SlateAttributePrivate::ISlateAttributeGetter> FSlateAttributeMetaData::FGetterItem::Getter
Definition at line 156 of file SlateAttributeMetaData.h.
Referenced by FGetterItem(), and FGetterItem().
SortOrder
uint32 FSlateAttributeMetaData::FGetterItem::SortOrder
Definition at line 158 of file SlateAttributeMetaData.h.
Referenced by FGetterItem(), FGetterItem(), and operator<().
The documentation for this struct was generated from the following file:
SlateAttributeMetaData.h