Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize > Class Template Reference
UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize > Class Template Reference
TDynamicMeshOverlay is an add-on to a FDynamicMesh3 that allows for per-triangle storage of an "element" (eg like a per-triangle UV or normal).
#include "DynamicMeshOverlay.h"
Public Types
typedef FRefCountVector::IndexEnumerable element_iterator
Public Member Functions
TDynamicMeshOverlay ()
Create an empty overlay.
TDynamicMeshOverlay (FDynamicMesh3 *ParentMeshIn)
Create an overlay for the given parent mesh.
void Append (const TDynamicMeshOverlay &ToAppend, const FDynamicMesh3::FAppendInfo &AppendInfo)
void AppendDefaulted (const FDynamicMesh3::FAppendInfo &AppendInfo)
int AppendElement (const RealType *Value)
Allocate a new element with the given value.
int AppendElement (RealType ConstantValue)
Allocate a new element with the given constant value.
bool AreTrianglesConnected (int TriangleID0, int TriangleID1) const
void BeginUnsafeElementsInsert ()
Call this before a set of unsafe InsertVertex() calls.
bool CheckValidity (bool bAllowNonManifoldVertices=true, EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check) const
Checks that the overlay mesh is well-formed, ie all internal data structures are consistent.
void ClearElements ()
Discard all elements.
template<typename EnumerableIntType>
void ClearElements (const EnumerableIntType &Triangles)
Discard elements for given triangles.
void CompactCopy (const FCompactMaps &CompactMaps, const TDynamicMeshOverlay< RealType, ElementSize > &Copy)
Copy the Copy overlay to a compact rep, also updating parent references based on the CompactMaps.
void CompactInPlace (const FCompactMaps &CompactMaps)
Compact overlay and update links to parent based on CompactMaps.
void Copy (const TDynamicMeshOverlay< RealType, ElementSize > &Copy)
Set this overlay to contain the same arrays as the copy overlay.
int CountVertexElements (int VertexID, bool bBruteForce=false) const
Count the number of unique elements for a given parent-mesh vertex.
void CreateFromPredicate (TFunctionRef< bool(int ParentVertexIdx, int TriIDA, int TriIDB)> TrisCanShareVertexPredicate, RealType InitElementValue)
Build overlay topology from a predicate function, e.g.
int ElementCount () const
element_iterator ElementIndicesItr () const
void EndUnsafeElementsInsert ()
Call after a set of unsafe InsertVertex() calls to rebuild free list.
void FreeUnusedElements (const TSet< int > *ElementsToCheck=nullptr)
Goes through elements and frees any whose reference counts indicate that they are not being used.
SIZE_T GetByteCount () const
template<typename AsType>
void GetElement (int ElementID, AsType &Data) const
Get the element at a given index.
void GetElement (int ElementID, RealType *Data) const
Get the element at a given index.
template<typename AsType>
void GetElementAtVertex (int TriangleID, int VertexID, AsType &Data) const
Get the Element value associated with a vertex of a triangle.
int GetElementIDAtVertex (int TriangleID, int VertexID) const
Find the element ID at a vertex of a triangle.
void GetElementTriangles (int ElementID, TArray< int > &OutTriangles) const
find the triangles connected to an element
FDynamicMesh3 * GetParentMesh ()
const FDynamicMesh3 * GetParentMesh () const
int GetParentVertex (int ElementID) const
Get the parent vertex id for the element at a given index.
FIndex3i GetTriangle (int TriangleID) const
Get the element index tuple for a triangle.
bool GetTriangleIfValid (int TriangleID, FIndex3i &TriangleOut) const
If the triangle is set to valid element indices, return the indices in TriangleOut and return true, otherwise return false.
template<typename AsType>
void GetTriBaryInterpolate (int32 TriangleID, const AsType *BaryCoords, AsType *DataOut) const
Compute interpolated parameter value inside triangle using barycentric coordinates.
void GetVertexElements (int VertexID, TArray< int > &OutElements) const
find the elements associated with a given parent-mesh vertex
bool HasInteriorSeamEdges () const
void InitializeNewTriangle (int TriangleID)
Set a triangle's element indices to InvalidID.
void InitializeTriangles (int MaxTriangleID)
Initialize the triangle list to the given size, and set all triangles to InvalidID.
EMeshResult InsertElement (int ElementID, const RealType *Value, bool bUnsafe=false)
Insert element at given index, assuming it is unused.
bool IsBowtieInOverlay (int32 VertexID) const
Determines whether the base-mesh vertex has "bowtie" topology in the Overlay.
bool IsCompact () const
bool IsElement (int vID) const
bool IsSameAs (const TDynamicMeshOverlay< RealType, ElementSize > &Other, bool bIgnoreDataLayout) const
Returns true if this overlay is the same as Other.
bool IsSeamEdge (int EdgeID, bool *bIsNonIntersectingOut=nullptr) const
Returns true if the parent-mesh edge is a "Seam" in this overlay.
bool IsSeamEndEdge (int EdgeID) const
Returns true if the parent-mesh edge is a "Seam End" in this overlay, meaning the adjacent element triangles share one element, not two.
bool IsSeamIntersectionVertex (int32 VertexID) const
Returns true if the parent-mesh vertex is at a seam 'intersection' – i.e., the end of a seam, or the intersection w/ another seam.
bool IsSeamVertex (int VertexID, bool bBoundaryIsSeam=true) const
Returns true if the parent-mesh vertex is connected to any seam edges.
bool IsSetTriangle (int TID) const
int MaxElementID () const
bool MergeElement (int SourceElementID, int TargetElementID)
Collapse SourceElementID into TargetElementID, resulting in connecting any containing triangles and reducing the total elements in the overlay.
void OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo &CollapseInfo)
Update the overlay to reflect an edge collapse in the parent mesh.
void OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo &FlipInfo)
Update the overlay to reflect an edge flip in the parent mesh.
void OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo &MergeInfo)
Update the overlay to reflect an edge merge in the parent mesh.
void OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo &MergeInfo)
Update the overlay to reflect a vertex merge in the parent mesh.
void OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo &PokeInfo)
Update the overlay to reflect a face poke in the parent mesh.
void OnRemoveTriangle (int TriangleID)
Remove a triangle from the overlay.
void OnReverseTriOrientation (int TriangleID)
Reverse the orientation of a triangle's elements.
void OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo &SplitInfo)
Update the overlay to reflect an edge split in the parent mesh.
void OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo &SplitInfo, const TArrayView< const int > &TrianglesToUpdate)
Update the overlay to reflect a vertex split in the parent mesh.
void Serialize (FArchive &Ar, const FCompactMaps *CompactMaps, bool bUseCompression)
Serialize to and from an archive.
template<typename AsType>
void SetElement (int ElementID, const AsType &Data)
Set the element at a given index.
void SetElement (int ElementID, const RealType *Data)
Set the element at a given index.
void SetParentVertex (int ElementIndex, int ParentVertexIndex)
EMeshResult SetTriangle (int TriangleID, const FIndex3i &TriElements, bool bAllowElementFreeing=true)
Set the triangle to the given Element index tuple, and increment element reference counts.
void SplitBowties ()
Refine an existing overlay topology by splitting any bow ties.
void SplitBowtiesAtVertex (int32 Vid, TArray< int32 > *NewElementIDs=nullptr)
Split any bowties at given vertex.
int SplitElement (int ElementID, const TArrayView< const int > &TrianglesToUpdate)
Create a new copy of ElementID, and update connected triangles in the TrianglesToUpdate array to reference the copy of ElementID where they used to reference ElementID (Note: This just calls "SplitElementWithNewParent" with the existing element's parent id.)
int SplitElementWithNewParent (int ElementID, int SplitParentVertexID, const TArrayView< const int > &TrianglesToUpdate)
Create a new copy of ElementID, and update connected triangles in the TrianglesToUpdate array to reference the copy of ElementID where they used to reference ElementID.
void SplitVerticesWithPredicate (TFunctionRef< bool(int ElementIdx, int TriID)> ShouldSplitOutVertex, TFunctionRef< void(int ElementIdx, int TriID, RealType *FillVect)> GetNewElementValue)
Refine an existing overlay topology.
bool TriangleHasElement (int TriangleID, int ElementID) const
void UnsetTriangle (int TriangleID, bool bAllowElementFreeing=true)
Set the triangle to have InvalidID element IDs, decrementing element reference counts if needed.
Protected Member Functions
void InternalSetTriangle (int TriangleID, const FIndex3i &TriElements, bool bUpdateRefCounts, bool bAllowElementFreeing=true)
updates the triangles array and optionally the element reference counts
void SetElementFromBary (int SetElement, int ElementA, int ElementB, int ElementC, const FVector3d &BaryCoords)
Set the value at an Element to be a barycentric interpolation of three other Elements.
void SetElementFromLerp (int SetElement, int ElementA, int ElementB, double Alpha)
Set the value at an Element to be a linear interpolation of two other Elements.
Protected Attributes
TDynamicVector< RealType > Elements
List of element values.
FRefCountVector ElementsRefCounts
Reference counts of element indices.
TDynamicVector< int > ElementTriangles
List of triangle element-index triplets [Elem0 Elem1 Elem2].
FDynamicMesh3 * ParentMesh
The parent mesh this overlay belongs to.
TDynamicVector< int > ParentVertices
List of parent vertex indices, one per element.
Private Member Functions
void Reparent (FDynamicMesh3 *ParentMeshIn)
@set the parent mesh for this overlay.
Friends
class FDynamicMesh3
class FDynamicMeshAttributeSet
FArchive & operator<< (FArchive &Ar, TDynamicMeshOverlay< RealType, ElementSize > &Overlay)
Serialization operator for FDynamicMeshOverlay.
Detailed Description
template<typename RealType, int ElementSize>
class UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >
TDynamicMeshOverlay is an add-on to a FDynamicMesh3 that allows for per-triangle storage of an "element" (eg like a per-triangle UV or normal).
However the elements can be shared between triangles at shared vertices because the elements are stored in a separate indexable list.
Each element has one vertex in the parent mesh as its parent, whereas each vertex may be the parent of multiple elements in cases where neighboring triangles are not sharing a single element for that vertex. This means that there may be "seam" boundary edges in the overlay topology that are not mesh boundary edges in the associated/parent mesh, but the overlay topology will not connect triangles that were not connected in the parent mesh or create any topologically degenerate triangles, since the parent vids of the elements of a triangle will have to match up to the vids of the triangle.
A "seam" edge is one where at least one of the elements of the triangles on either side of the edge is not shared between the two triangles.
The FDynamicMesh3 mesh topology operations (eg split/flip/collapse edge, poke face, etc) can be mirrored to the overlay via OnSplitEdge(), etc.
Note that although this is a template, many of the functions are defined in the .cpp file. As a result you need to explicitly instantiate and export the instance of the template that you wish to use in the block at the top of DynamicMeshOverlay.cpp
Definition at line 67 of file DynamicMeshOverlay.h.
Member Typedef Documentation
element_iterator
template<typename RealType, int ElementSize> typedef FRefCountVector::IndexEnumerable UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::element_iterator
Definition at line 315 of file DynamicMeshOverlay.h.
Constructor & Destructor Documentation
TDynamicMeshOverlay() [1/2]
template<typename RealType, int ElementSize> UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::TDynamicMeshOverlay () inline
Create an empty overlay.
Definition at line 89 of file DynamicMeshOverlay.h.
References ParentMesh.
Referenced by UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::TDynamicMeshVectorOverlay(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::TDynamicMeshVectorOverlay(), Append(), CompactCopy(), Copy(), IsSameAs(), and operator<<.
TDynamicMeshOverlay() [2/2]
template<typename RealType, int ElementSize> UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::TDynamicMeshOverlay (FDynamicMesh3 * ParentMeshIn) inline
Create an overlay for the given parent mesh.
Definition at line 95 of file DynamicMeshOverlay.h.
References FDynamicMesh3, and ParentMesh.
Member Function Documentation
Append()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::Append (const TDynamicMeshOverlay< RealType, ElementSize > & ToAppend, const FDynamicMesh3::FAppendInfo & AppendInfo) inline
Definition at line 250 of file DynamicMeshOverlay.h.
References TDynamicMeshOverlay(), check, checkSlow, Elements, ElementsRefCounts, ElementTriangles, ensure, IndexConstants::InvalidID, UE::Geometry::TDynamicVector< Type, BlockSize >::Num(), UE::Geometry::FDynamicMesh3::FAppendInfo::NumTriangle, Parent, ParentVertices, UE::Geometry::FDynamicMesh3::FAppendInfo::TriangleOffset, and UE::Geometry::FDynamicMesh3::FAppendInfo::VertexOffset.
AppendDefaulted()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::AppendDefaulted (const FDynamicMesh3::FAppendInfo & AppendInfo) inline
Definition at line 284 of file DynamicMeshOverlay.h.
References checkSlow, ElementTriangles, IndexConstants::InvalidID, UE::Geometry::FDynamicMesh3::FAppendInfo::NumTriangle, and UE::Geometry::FDynamicMesh3::FAppendInfo::TriangleOffset.
AppendElement() [1/2]
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::AppendElement (const RealType * Value)
Allocate a new element with the given value.
References Value.
AppendElement() [2/2]
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::AppendElement (RealType ConstantValue)
Allocate a new element with the given constant value.
Referenced by UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::AppendElement(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::AppendElement(), and CompactCopy().
AreTrianglesConnected()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::AreTrianglesConnected (int TriangleID0, int TriangleID1) const
Returns
true if the two triangles are connected, ie shared edge exists and is not a seam edge
BeginUnsafeElementsInsert()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::BeginUnsafeElementsInsert () inline
Call this before a set of unsafe InsertVertex() calls.
Definition at line 444 of file DynamicMeshOverlay.h.
CheckValidity()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CheckValidity (bool bAllowNonManifoldVertices = true, EValidityCheckFailMode FailMode = EValidityCheckFailMode::Check) const
Checks that the overlay mesh is well-formed, ie all internal data structures are consistent.
References UE::Geometry::Check.
ClearElements() [1/2]
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ClearElements ()
Discard all elements.
Referenced by CompactCopy().
ClearElements() [2/2]
template<typename RealType, int ElementSize> template<typename EnumerableIntType> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ClearElements (const EnumerableIntType & Triangles) inline
Discard elements for given triangles.
Definition at line 296 of file DynamicMeshOverlay.h.
References UnsetTriangle().
CompactCopy()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactCopy (const FCompactMaps & CompactMaps, const TDynamicMeshOverlay< RealType, ElementSize > & Copy) inline
Copy the Copy overlay to a compact rep, also updating parent references based on the CompactMaps.
Definition at line 121 of file DynamicMeshOverlay.h.
References TDynamicMeshOverlay(), UE::Geometry::FIndex3i::A, AppendElement(), UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, check, ClearElements(), Copy(), UE::Geometry::FCompactMaps::GetTriangleMapping(), UE::Geometry::FCompactMaps::NumTriangleMappings(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and SetTriangle().
CompactInPlace()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactInPlace (const FCompactMaps & CompactMaps) inline
Compact overlay and update links to parent based on CompactMaps.
Definition at line 158 of file DynamicMeshOverlay.h.
References checkSlow, ElementCount(), Elements, ElementsRefCounts, ElementTriangles, GetElement(), UE::Geometry::FCompactMaps::GetTriangleMapping(), UE::Geometry::FCompactMaps::GetVertexMapping(), ID, UE::Geometry::FRefCountVector::INVALID_REF_COUNT, IndexConstants::InvalidID, IsCompact(), FMath::Max, MaxElementID(), TArray< InElementType, InAllocatorType >::Num(), ParentVertices, SetElement(), and TArray< InElementType, InAllocatorType >::SetNumUninitialized().
Copy()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::Copy (const TDynamicMeshOverlay< RealType, ElementSize > & Copy) inline
Set this overlay to contain the same arrays as the copy overlay.
Definition at line 112 of file DynamicMeshOverlay.h.
References TDynamicMeshOverlay(), Copy(), Elements, ElementsRefCounts, ElementTriangles, and ParentVertices.
Referenced by CompactCopy(), and Copy().
CountVertexElements()
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CountVertexElements (int VertexID, bool bBruteForce = false) const
Count the number of unique elements for a given parent-mesh vertex.
CreateFromPredicate()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CreateFromPredicate (TFunctionRef< bool(int ParentVertexIdx, int TriIDA, int TriIDB)> TrisCanShareVertexPredicate, RealType InitElementValue)
Build overlay topology from a predicate function, e.g.
to build topology for sharp normals
Parameters
TrisCanShareVertexPredicate Indicator function returns true if the given vertex can be shared for the given pair of triangles Note if a vertex can be shared between tris A and B, and B and C, it will be shared between all three
InitElementValue Initial element value, copied into all created elements
ElementCount()
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ElementCount () const inline
Returns
the number of in-use Elements in the overlay
Definition at line 305 of file DynamicMeshOverlay.h.
References ElementsRefCounts.
Referenced by CompactInPlace().
ElementIndicesItr()
template<typename RealType, int ElementSize> element_iterator UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ElementIndicesItr () const inline
Returns
enumerator for valid element indices suitable for use with range-based for
Definition at line 318 of file DynamicMeshOverlay.h.
References ElementsRefCounts.
EndUnsafeElementsInsert()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::EndUnsafeElementsInsert () inline
Call after a set of unsafe InsertVertex() calls to rebuild free list.
Definition at line 450 of file DynamicMeshOverlay.h.
References ElementsRefCounts.
FreeUnusedElements()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::FreeUnusedElements (const TSet< int > * ElementsToCheck = nullptr)
Goes through elements and frees any whose reference counts indicate that they are not being used.
This is usually not necessary since most operations that remove references will go ahead and do this, but it may be used, for instance, after SetTriangle is called with bAllowElementFreeing set to false.
Parameters
ElementsToCheck If provided, only these element ID's will be checked.
GetByteCount()
template<typename RealType, int ElementSize> SIZE_T UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetByteCount () const inline
Definition at line 657 of file DynamicMeshOverlay.h.
References Elements, ElementsRefCounts, ElementTriangles, and ParentVertices.
GetElement() [1/2]
template<typename RealType, int ElementSize> template<typename AsType> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetElement (int ElementID, AsType & Data) const inline
Get the element at a given index.
Definition at line 480 of file DynamicMeshOverlay.h.
References Elements.
GetElement() [2/2]
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetElement (int ElementID, RealType * Data) const inline
Get the element at a given index.
Definition at line 469 of file DynamicMeshOverlay.h.
References Elements.
Referenced by CompactInPlace(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetElement(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetElement(), and GetElementAtVertex().
GetElementAtVertex()
template<typename RealType, int ElementSize> template<typename AsType> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetElementAtVertex (int TriangleID, int VertexID, AsType & Data) const inline
Get the Element value associated with a vertex of a triangle.
Parameters
TriangleID ID of a triangle containing the Element
VertexID ID of the Element's parent vertex
Data Value contained at the Element
Definition at line 497 of file DynamicMeshOverlay.h.
References checkSlow, GetElement(), GetElementIDAtVertex(), and IndexConstants::InvalidID.
Referenced by UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetElementAtVertex(), and UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetElementAtVertex().
GetElementIDAtVertex()
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetElementIDAtVertex (int TriangleID, int VertexID) const
Find the element ID at a vertex of a triangle.
Returns
Returns the element ID or FDynamicMesh3::InvalidID if the vertex is not a parent of any element contained in the triangle.
Referenced by GetElementAtVertex().
GetElementTriangles()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetElementTriangles (int ElementID, TArray< int > & OutTriangles) const
find the triangles connected to an element
GetParentMesh() [1/2]
template<typename RealType, int ElementSize> FDynamicMesh3 * UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetParentMesh () inline
Returns
the parent mesh for this overlay
Definition at line 109 of file DynamicMeshOverlay.h.
References FDynamicMesh3, and ParentMesh.
GetParentMesh() [2/2]
template<typename RealType, int ElementSize> const FDynamicMesh3 * UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetParentMesh () const inline
Returns
the parent mesh for this overlay
Definition at line 107 of file DynamicMeshOverlay.h.
References FDynamicMesh3, and ParentMesh.
GetParentVertex()
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetParentVertex (int ElementID) const inline
Get the parent vertex id for the element at a given index.
Definition at line 509 of file DynamicMeshOverlay.h.
References ParentVertices.
GetTriangle()
template<typename RealType, int ElementSize> FIndex3i UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetTriangle (int TriangleID) const inline
Get the element index tuple for a triangle.
Definition at line 516 of file DynamicMeshOverlay.h.
References ElementTriangles.
Referenced by FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays().
GetTriangleIfValid()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetTriangleIfValid (int TriangleID, FIndex3i & TriangleOut) const inline
If the triangle is set to valid element indices, return the indices in TriangleOut and return true, otherwise return false.
Definition at line 523 of file DynamicMeshOverlay.h.
References UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, checkSlow, and ElementTriangles.
GetTriBaryInterpolate()
template<typename RealType, int ElementSize> template<typename AsType> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetTriBaryInterpolate (int32 TriangleID, const AsType * BaryCoords, AsType * DataOut) const inline
Compute interpolated parameter value inside triangle using barycentric coordinates.
Parameters
TriangleID index of triangle
BaryCoords 3 barycentric coordinates inside triangle
DataOut resulting interpolated overlay parameter value (of size ElementSize)
Definition at line 612 of file DynamicMeshOverlay.h.
References Elements, and ElementTriangles.
GetVertexElements()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::GetVertexElements (int VertexID, TArray< int > & OutElements) const
find the elements associated with a given parent-mesh vertex
HasInteriorSeamEdges()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::HasInteriorSeamEdges () const
Returns
true if overlay has any interior seam edges. This requires an O(N) search unless it early-outs.
InitializeNewTriangle()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::InitializeNewTriangle (int TriangleID)
Set a triangle's element indices to InvalidID.
InitializeTriangles()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::InitializeTriangles (int MaxTriangleID)
Initialize the triangle list to the given size, and set all triangles to InvalidID.
InsertElement()
template<typename RealType, int ElementSize> EMeshResult UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::InsertElement (int ElementID, const RealType * Value, bool bUnsafe = false)
Insert element at given index, assuming it is unused.
If bUnsafe, we use fast id allocation that does not update free list. You should only be using this between BeginUnsafeElementsInsert() / EndUnsafeElementsInsert() calls
References Value.
InternalSetTriangle()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::InternalSetTriangle (int TriangleID, const FIndex3i & TriElements, bool bUpdateRefCounts, bool bAllowElementFreeing = true) protected
updates the triangles array and optionally the element reference counts
IsBowtieInOverlay()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsBowtieInOverlay (int32 VertexID) const
Determines whether the base-mesh vertex has "bowtie" topology in the Overlay.
Bowtie topology means that one or more elements at the vertex are shared across disconnected UV-components.
Returns
true if the base-mesh vertex has "bowtie" topology in the overlay
IsCompact()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsCompact () const inline
Returns
true if the elements are compact
Definition at line 312 of file DynamicMeshOverlay.h.
References ElementsRefCounts.
Referenced by CompactInPlace().
IsElement()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsElement (int vID) const inline
Returns
true if this element index is in use
Definition at line 309 of file DynamicMeshOverlay.h.
References ElementsRefCounts.
IsSameAs()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsSameAs (const TDynamicMeshOverlay< RealType, ElementSize > & Other, bool bIgnoreDataLayout) const
Returns true if this overlay is the same as Other.
References TDynamicMeshOverlay(), and Other.
IsSeamEdge()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsSeamEdge (int EdgeID, bool * bIsNonIntersectingOut = nullptr) const
Returns true if the parent-mesh edge is a "Seam" in this overlay.
If present, bIsNonIntersectingOut will be true only if this is a seam edge that does not intersect with another seam or the end of the seam.
Referenced by UE::Geometry::FMeshConstraintsUtil::ConstrainSeams().
IsSeamEndEdge()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsSeamEndEdge (int EdgeID) const
Returns true if the parent-mesh edge is a "Seam End" in this overlay, meaning the adjacent element triangles share one element, not two.
IsSeamIntersectionVertex()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsSeamIntersectionVertex (int32 VertexID) const
Returns true if the parent-mesh vertex is at a seam 'intersection' – i.e., the end of a seam, or the intersection w/ another seam.
IsSeamVertex()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsSeamVertex (int VertexID, bool bBoundaryIsSeam = true) const
Returns true if the parent-mesh vertex is connected to any seam edges.
IsSetTriangle()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsSetTriangle (int TID) const inline
Returns
true if this triangle was set
Definition at line 363 of file DynamicMeshOverlay.h.
References checkSlow, and ElementTriangles.
MaxElementID()
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::MaxElementID () const inline
Returns
the maximum element index in the overlay. This may be larger than the count if Elements have been deleted.
Definition at line 307 of file DynamicMeshOverlay.h.
References ElementsRefCounts.
Referenced by CompactInPlace().
MergeElement()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::MergeElement (int SourceElementID, int TargetElementID)
Collapse SourceElementID into TargetElementID, resulting in connecting any containing triangles and reducing the total elements in the overlay.
Parameters
SourceElementID the element to merge away
TargetElementID the element to merge into
Returns
If the operation completed successfully, returns true
OnCollapseEdge()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo & CollapseInfo)
Update the overlay to reflect an edge collapse in the parent mesh.
OnFlipEdge()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo & FlipInfo)
Update the overlay to reflect an edge flip in the parent mesh.
OnMergeEdges()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo & MergeInfo)
Update the overlay to reflect an edge merge in the parent mesh.
OnMergeVertices()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo & MergeInfo)
Update the overlay to reflect a vertex merge in the parent mesh.
OnPokeTriangle()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo & PokeInfo)
Update the overlay to reflect a face poke in the parent mesh.
OnRemoveTriangle()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnRemoveTriangle (int TriangleID)
Remove a triangle from the overlay.
OnReverseTriOrientation()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnReverseTriOrientation (int TriangleID)
Reverse the orientation of a triangle's elements.
OnSplitEdge()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo & SplitInfo)
Update the overlay to reflect an edge split in the parent mesh.
OnSplitVertex()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo & SplitInfo, const TArrayView< const int > & TrianglesToUpdate)
Update the overlay to reflect a vertex split in the parent mesh.
Reparent()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::Reparent (FDynamicMesh3 * ParentMeshIn) inline private
@set the parent mesh for this overlay.
Only safe for use during FDynamicMesh move
Definition at line 101 of file DynamicMeshOverlay.h.
References FDynamicMesh3, and ParentMesh.
Serialize()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::Serialize (FArchive & Ar, const FCompactMaps * CompactMaps, bool bUseCompression)
Serialize to and from an archive.
Parameters
Ar Archive to serialize with.
CompactMaps If this is not a null pointer, the mesh serialization compacted the vertex and/or triangle data using the provided mapping.
bUseCompression Use compression for serializing bulk data.
References Ar.
Referenced by operator<<.
SetElement() [1/2]
template<typename RealType, int ElementSize> template<typename AsType> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SetElement (int ElementID, const AsType & Data) inline
Set the element at a given index.
Definition at line 548 of file DynamicMeshOverlay.h.
References Elements.
SetElement() [2/2]
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SetElement (int ElementID, const RealType * Data) inline
Set the element at a given index.
Definition at line 537 of file DynamicMeshOverlay.h.
References Elements.
Referenced by CompactInPlace(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::SetElement(), SetElementFromBary(), and SetElementFromLerp().
SetElementFromBary()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SetElementFromBary (int SetElement, int ElementA, int ElementB, int ElementC, const FVector3d & BaryCoords) protected
Set the value at an Element to be a barycentric interpolation of three other Elements.
References SetElement().
SetElementFromLerp()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SetElementFromLerp (int SetElement, int ElementA, int ElementB, double Alpha) protected
Set the value at an Element to be a linear interpolation of two other Elements.
References Alpha, and SetElement().
SetParentVertex()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SetParentVertex (int ElementIndex, int ParentVertexIndex) inline
Definition at line 326 of file DynamicMeshOverlay.h.
References ParentVertices.
SetTriangle()
template<typename RealType, int ElementSize> EMeshResult UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SetTriangle (int TriangleID, const FIndex3i & TriElements, bool bAllowElementFreeing = true)
Set the triangle to the given Element index tuple, and increment element reference counts.
Parameters
bAllowElementFreeing If true, then any elements that were only referenced by this triangle become immediately unallocated if the triangle no longer references them. This can be set to false when remeshing across existing elements to avoid them being freed while temporarily unreferenced, but then it should eventually be followed by a call to FreeUnusedElements().
Referenced by CompactCopy().
SplitBowties()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SplitBowties ()
Refine an existing overlay topology by splitting any bow ties.
SplitBowtiesAtVertex()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SplitBowtiesAtVertex (int32 Vid, TArray< int32 > * NewElementIDs = nullptr)
Split any bowties at given vertex.
Parameters
NewElementIDs If not null, newly created element IDs are placed here. Note that this array is intentionally not cleared before appending to it.
SplitElement()
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SplitElement (int ElementID, const TArrayView< const int > & TrianglesToUpdate)
Create a new copy of ElementID, and update connected triangles in the TrianglesToUpdate array to reference the copy of ElementID where they used to reference ElementID (Note: This just calls "SplitElementWithNewParent" with the existing element's parent id.)
Parameters
ElementID the element to copy
TrianglesToUpdate the triangles that should now reference the new element
Returns
the ID of the newly created element
SplitElementWithNewParent()
template<typename RealType, int ElementSize> int UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SplitElementWithNewParent (int ElementID, int SplitParentVertexID, const TArrayView< const int > & TrianglesToUpdate)
Create a new copy of ElementID, and update connected triangles in the TrianglesToUpdate array to reference the copy of ElementID where they used to reference ElementID.
The new element will have the given parent vertex ID. Deletes any elements that are no longer used after the triangles are changed.
Parameters
ElementID the element to copy
SplitParentVertexID the new parent vertex for copied elements
TrianglesToUpdate the triangles that should now reference the new element. Note: this is allowed to include triangles that do not have the element at all; sometimes you may want to do so to avoid creating a new array for each call.
Returns
the ID of the newly created element
SplitVerticesWithPredicate()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::SplitVerticesWithPredicate (TFunctionRef< bool(int ElementIdx, int TriID)> ShouldSplitOutVertex, TFunctionRef< void(int ElementIdx, int TriID, RealType *FillVect)> GetNewElementValue)
Refine an existing overlay topology.
For any element on a given triangle, if the predicate returns true, it gets topologically split out so it isn't shared by any other triangle. Used for creating sharp vertices in the normals overlay.
Parameters
ShouldSplitOutVertex predicate returns true of the element should be split out and not shared w/ any other triangle
GetNewElementValue function to assign a new value to any element that is split out
TriangleHasElement()
template<typename RealType, int ElementSize> bool UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::TriangleHasElement (int TriangleID, int ElementID) const inline
Returns
true if triangle contains element
Definition at line 558 of file DynamicMeshOverlay.h.
References ElementTriangles.
UnsetTriangle()
template<typename RealType, int ElementSize> void UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::UnsetTriangle (int TriangleID, bool bAllowElementFreeing = true)
Set the triangle to have InvalidID element IDs, decrementing element reference counts if needed.
Parameters
bAllowElementFreeing If true, then any elements that were only referenced by this triangle become immediately unallocated. This can be set to false as part of a remeshing, but then it should eventually be followed by a call to FreeUnusedElements().
Referenced by ClearElements().
Friends And Related Symbol Documentation
FDynamicMesh3
template<typename RealType, int ElementSize> friend class FDynamicMesh3 friend
Definition at line 84 of file DynamicMeshOverlay.h.
References FDynamicMesh3.
Referenced by TDynamicMeshOverlay(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::TDynamicMeshVectorOverlay(), FDynamicMesh3, GetParentMesh(), GetParentMesh(), and Reparent().
FDynamicMeshAttributeSet
template<typename RealType, int ElementSize> friend class FDynamicMeshAttributeSet friend
Definition at line 85 of file DynamicMeshOverlay.h.
References FDynamicMeshAttributeSet.
Referenced by FDynamicMeshAttributeSet.
operator<<
template<typename RealType, int ElementSize> FArchive & operator<< (FArchive & Ar, TDynamicMeshOverlay< RealType, ElementSize > & Overlay) friend
Serialization operator for FDynamicMeshOverlay.
Parameters
Ar Archive to serialize with.
Overlay Mesh overlay to serialize.
Returns
Passing down serializing archive.
Definition at line 642 of file DynamicMeshOverlay.h.
References TDynamicMeshOverlay(), Ar, and Serialize().
Field Documentation
Elements
template<typename RealType, int ElementSize> TDynamicVector<RealType> UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::Elements protected
List of element values.
Definition at line 77 of file DynamicMeshOverlay.h.
Referenced by Append(), CompactInPlace(), Copy(), GetByteCount(), GetElement(), GetElement(), GetTriBaryInterpolate(), SetElement(), and SetElement().
ElementsRefCounts
template<typename RealType, int ElementSize> FRefCountVector UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ElementsRefCounts protected
Reference counts of element indices.
Iterate over this to find out which elements are valid.
Definition at line 75 of file DynamicMeshOverlay.h.
Referenced by Append(), CompactInPlace(), Copy(), ElementCount(), ElementIndicesItr(), EndUnsafeElementsInsert(), GetByteCount(), IsCompact(), IsElement(), and MaxElementID().
ElementTriangles
template<typename RealType, int ElementSize> TDynamicVector<int> UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ElementTriangles protected
List of triangle element-index triplets [Elem0 Elem1 Elem2].
Definition at line 82 of file DynamicMeshOverlay.h.
Referenced by Append(), AppendDefaulted(), CompactInPlace(), Copy(), GetByteCount(), GetTriangle(), GetTriangleIfValid(), GetTriBaryInterpolate(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetTriElement(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetTriElements(), IsSetTriangle(), and TriangleHasElement().
ParentMesh
template<typename RealType, int ElementSize> FDynamicMesh3* UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ParentMesh protected
The parent mesh this overlay belongs to.
Definition at line 72 of file DynamicMeshOverlay.h.
Referenced by TDynamicMeshOverlay(), TDynamicMeshOverlay(), GetParentMesh(), GetParentMesh(), and Reparent().
ParentVertices
template<typename RealType, int ElementSize> TDynamicVector<int> UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::ParentVertices protected
List of parent vertex indices, one per element.
Definition at line 79 of file DynamicMeshOverlay.h.
Referenced by Append(), CompactInPlace(), Copy(), GetByteCount(), GetParentVertex(), and SetParentVertex().
The documentation for this class was generated from the following files:
AverageOverlayToVertices.h
DynamicMeshOverlay.h