Unreal Engine 5.6 C++ API: FWorldPartitionLevelHelper::FLoadActorsParams Struct Reference
FWorldPartitionLevelHelper::FLoadActorsParams Struct Reference
#include "WorldPartitionLevelHelper.h"
Public Member Functions
FLoadActorsParams ()
FLoadActorsParams & SetActorPackages (TArrayView< FWorldPartitionRuntimeCellObjectMapping > InActorPackages)
FLoadActorsParams & SetCompletionCallback (TFunction< void(bool)> InCompletionCallback)
FLoadActorsParams & SetDestLevel (ULevel *InDestLevel)
FLoadActorsParams & SetInstancingContext (FLinkerInstancingContext InInstancingContext)
FLoadActorsParams & SetLoadAsync (bool bInLoadAsync, TArray< int32 > *OutAsyncRequestIDs=nullptr)
FLoadActorsParams & SetOuterWorld (UWorld *InOuterWorld)
FLoadActorsParams & SetPackageReferencer (FPackageReferencer *InPackageReferencer)
Data Fields
TArrayView< FWorldPartitionRuntimeCellObjectMapping > ActorPackages
TArray< int32 > * AsyncRequestIDs
bool bLoadAsync
TFunction< void(bool)> CompletionCallback
ULevel * DestLevel
FLinkerInstancingContext InstancingContext
UWorld * OuterWorld
FPackageReferencer * PackageReferencer
Detailed Description
Definition at line 48 of file WorldPartitionLevelHelper.h.
Constructor & Destructor Documentation
FLoadActorsParams()
FWorldPartitionLevelHelper::FLoadActorsParams::FLoadActorsParams () inline
Definition at line 50 of file WorldPartitionLevelHelper.h.
References AsyncRequestIDs, bLoadAsync, DestLevel, OuterWorld, and PackageReferencer.
Referenced by SetActorPackages(), SetCompletionCallback(), SetDestLevel(), SetInstancingContext(), SetLoadAsync(), SetOuterWorld(), and SetPackageReferencer().
Member Function Documentation
SetActorPackages()
FLoadActorsParams & FWorldPartitionLevelHelper::FLoadActorsParams::SetActorPackages (TArrayView< FWorldPartitionRuntimeCellObjectMapping > InActorPackages) inline
Definition at line 69 of file WorldPartitionLevelHelper.h.
References FLoadActorsParams(), ActorPackages, and FWorldPartitionLevelHelper::InActorPackages.
SetCompletionCallback()
FLoadActorsParams & FWorldPartitionLevelHelper::FLoadActorsParams::SetCompletionCallback (TFunction< void(bool)> InCompletionCallback) inline
Definition at line 71 of file WorldPartitionLevelHelper.h.
References FLoadActorsParams(), CompletionCallback, and FWorldPartitionLevelHelper::InCompletionCallback.
SetDestLevel()
FLoadActorsParams & FWorldPartitionLevelHelper::FLoadActorsParams::SetDestLevel (ULevel * InDestLevel) inline
Definition at line 68 of file WorldPartitionLevelHelper.h.
References FLoadActorsParams(), DestLevel, and FWorldPartitionLevelHelper::InDestLevel.
SetInstancingContext()
FLoadActorsParams & FWorldPartitionLevelHelper::FLoadActorsParams::SetInstancingContext (FLinkerInstancingContext InInstancingContext) inline
Definition at line 78 of file WorldPartitionLevelHelper.h.
References FLoadActorsParams(), FWorldPartitionLevelHelper::InInstancingContext, and InstancingContext.
SetLoadAsync()
FLoadActorsParams & FWorldPartitionLevelHelper::FLoadActorsParams::SetLoadAsync (bool bInLoadAsync, TArray< int32 > * OutAsyncRequestIDs = nullptr) inline
Definition at line 72 of file WorldPartitionLevelHelper.h.
References FLoadActorsParams(), AsyncRequestIDs, FWorldPartitionLevelHelper::bInLoadAsync, and bLoadAsync.
SetOuterWorld()
FLoadActorsParams & FWorldPartitionLevelHelper::FLoadActorsParams::SetOuterWorld (UWorld * InOuterWorld) inline
Definition at line 67 of file WorldPartitionLevelHelper.h.
References FLoadActorsParams(), and OuterWorld.
SetPackageReferencer()
FLoadActorsParams & FWorldPartitionLevelHelper::FLoadActorsParams::SetPackageReferencer (FPackageReferencer * InPackageReferencer) inline
Definition at line 70 of file WorldPartitionLevelHelper.h.
References FLoadActorsParams(), FWorldPartitionLevelHelper::InPackageReferencer, and PackageReferencer.
Field Documentation
ActorPackages
TArrayView<FWorldPartitionRuntimeCellObjectMapping> FWorldPartitionLevelHelper::FLoadActorsParams::ActorPackages
Definition at line 60 of file WorldPartitionLevelHelper.h.
Referenced by SetActorPackages().
AsyncRequestIDs
TArray<int32>* FWorldPartitionLevelHelper::FLoadActorsParams::AsyncRequestIDs
Definition at line 64 of file WorldPartitionLevelHelper.h.
Referenced by FLoadActorsParams(), and SetLoadAsync().
bLoadAsync
bool FWorldPartitionLevelHelper::FLoadActorsParams::bLoadAsync
Definition at line 63 of file WorldPartitionLevelHelper.h.
Referenced by FLoadActorsParams(), and SetLoadAsync().
CompletionCallback
TFunction<void(bool)> FWorldPartitionLevelHelper::FLoadActorsParams::CompletionCallback
Definition at line 62 of file WorldPartitionLevelHelper.h.
Referenced by SetCompletionCallback().
DestLevel
ULevel* FWorldPartitionLevelHelper::FLoadActorsParams::DestLevel
Definition at line 59 of file WorldPartitionLevelHelper.h.
Referenced by FLoadActorsParams(), and SetDestLevel().
InstancingContext
FLinkerInstancingContext FWorldPartitionLevelHelper::FLoadActorsParams::InstancingContext mutable
Definition at line 65 of file WorldPartitionLevelHelper.h.
Referenced by SetInstancingContext().
OuterWorld
UWorld* FWorldPartitionLevelHelper::FLoadActorsParams::OuterWorld
Definition at line 58 of file WorldPartitionLevelHelper.h.
Referenced by FLoadActorsParams(), and SetOuterWorld().
PackageReferencer
FPackageReferencer* FWorldPartitionLevelHelper::FLoadActorsParams::PackageReferencer
Definition at line 61 of file WorldPartitionLevelHelper.h.
Referenced by FLoadActorsParams(), and SetPackageReferencer().
The documentation for this struct was generated from the following file:
WorldPartitionLevelHelper.h