Unreal Engine 5.6 C++ API: UE::PixelStreaming2::FStat Class Reference
UE::PixelStreaming2::FStat Class Reference
#include "RTCStatsCollector.h"
Public Member Functions
FStat ()=default
FStat (const FStat &Other)
FStat (FStatConfig Config, bool bInitialValue)
FStat (FStatConfig Config, double InitialValue, int NDecimalPlacesToPrint=0, bool bSmooth=false)
FStat (FStatConfig Config, FString InitialValue)
FName GetDisplayName () const
FName GetName () const
template<typename T>
T GetPrevValue ()
template<>
FString GetPrevValue ()
template<>
double GetPrevValue ()
template<>
bool GetPrevValue ()
template<typename T>
T GetValue ()
template<>
FString GetValue ()
template<>
double GetValue ()
template<>
bool GetValue ()
bool IsBoolean () const
bool IsHidden ()
bool IsNumeric () const
bool IsTextual () const
bool operator== (const FStat &Other) const
bool SetValue (FStatVariant ValueVariant)
bool ShouldDisplayText ()
bool ShouldGraph ()
FString ToString ()
Protected Attributes
TOptional< FName > Alias
bool bSmooth = false
EDisplayFlags DisplayFlags = EDisplayFlags::TEXT
FName Name
int NDecimalPlacesToPrint = 0
int NumSamples = 0
FStatVariant PrevStatVariant
FStatVariant StatVariant
Private Member Functions
double CalcEMA (double InPrevAvg, int InNumSamples, double InValue)
double CalcMA (double InPrevAvg, int InNumSamples, double InValue)
Detailed Description
Definition at line 48 of file RTCStatsCollector.h.
Constructor & Destructor Documentation
FStat() [1/5]
UE::PixelStreaming2::FStat::FStat () default
Referenced by FStat(), and operator==().
FStat() [2/5]
UE::PixelStreaming2::FStat::FStat (FStatConfig Config, double InitialValue, int NDecimalPlacesToPrint = 0, bool bSmooth = false)
References bSmooth, and NDecimalPlacesToPrint.
FStat() [3/5]
UE::PixelStreaming2::FStat::FStat (FStatConfig Config, FString InitialValue)
FStat() [4/5]
UE::PixelStreaming2::FStat::FStat (FStatConfig Config, bool bInitialValue)
FStat() [5/5]
UE::PixelStreaming2::FStat::FStat (const FStat & Other)
References FStat(), and Other.
Member Function Documentation
CalcEMA()
double UE::PixelStreaming2::FStat::CalcEMA (double InPrevAvg, int InNumSamples, double InValue) private
CalcMA()
double UE::PixelStreaming2::FStat::CalcMA (double InPrevAvg, int InNumSamples, double InValue) private
GetDisplayName()
FName UE::PixelStreaming2::FStat::GetDisplayName () const
GetName()
FName UE::PixelStreaming2::FStat::GetName () const
Referenced by UE::PixelStreaming2::GetTypeHash().
GetPrevValue() [1/4]
template<typename T> T UE::PixelStreaming2::FStat::GetPrevValue () inline
Definition at line 84 of file RTCStatsCollector.h.
References checkf, and TEXT.
GetPrevValue() [2/4]
template<> FString UE::PixelStreaming2::FStat::GetPrevValue ()
GetPrevValue() [3/4]
template<> double UE::PixelStreaming2::FStat::GetPrevValue ()
GetPrevValue() [4/4]
template<> bool UE::PixelStreaming2::FStat::GetPrevValue ()
GetValue() [1/4]
template<typename T> T UE::PixelStreaming2::FStat::GetValue () inline
Definition at line 69 of file RTCStatsCollector.h.
References checkf, and TEXT.
GetValue() [2/4]
template<> FString UE::PixelStreaming2::FStat::GetValue ()
GetValue() [3/4]
template<> double UE::PixelStreaming2::FStat::GetValue ()
GetValue() [4/4]
template<> bool UE::PixelStreaming2::FStat::GetValue ()
IsBoolean()
bool UE::PixelStreaming2::FStat::IsBoolean () const
IsHidden()
bool UE::PixelStreaming2::FStat::IsHidden ()
IsNumeric()
bool UE::PixelStreaming2::FStat::IsNumeric () const
IsTextual()
bool UE::PixelStreaming2::FStat::IsTextual () const
operator==()
bool UE::PixelStreaming2::FStat::operator== (const FStat & Other) const
References FStat(), and Other.
SetValue()
bool UE::PixelStreaming2::FStat::SetValue (FStatVariant ValueVariant)
ShouldDisplayText()
bool UE::PixelStreaming2::FStat::ShouldDisplayText ()
ShouldGraph()
bool UE::PixelStreaming2::FStat::ShouldGraph ()
ToString()
FString UE::PixelStreaming2::FStat::ToString ()
Field Documentation
Alias
TOptional<FName> UE::PixelStreaming2::FStat::Alias protected
Definition at line 117 of file RTCStatsCollector.h.
bSmooth
bool UE::PixelStreaming2::FStat::bSmooth = false protected
Definition at line 121 of file RTCStatsCollector.h.
Referenced by FStat().
DisplayFlags
EDisplayFlags UE::PixelStreaming2::FStat::DisplayFlags = EDisplayFlags::TEXT protected
Definition at line 116 of file RTCStatsCollector.h.
Name
FName UE::PixelStreaming2::FStat::Name protected
Definition at line 115 of file RTCStatsCollector.h.
NDecimalPlacesToPrint
int UE::PixelStreaming2::FStat::NDecimalPlacesToPrint = 0 protected
Definition at line 120 of file RTCStatsCollector.h.
Referenced by FStat().
NumSamples
int UE::PixelStreaming2::FStat::NumSamples = 0 protected
Definition at line 122 of file RTCStatsCollector.h.
PrevStatVariant
FStatVariant UE::PixelStreaming2::FStat::PrevStatVariant protected
Definition at line 125 of file RTCStatsCollector.h.
StatVariant
FStatVariant UE::PixelStreaming2::FStat::StatVariant protected
Definition at line 124 of file RTCStatsCollector.h.
The documentation for this class was generated from the following file:
RTCStatsCollector.h