Unreal Engine 5.6 C++ API: UE::Insights::FTreeNodeGrouping Class Reference
UE::Insights::FTreeNodeGrouping Class Reference
#include "TreeNodeGrouping.h"
Protected Member Functions
UE_DEPRECATED (5.6, "BrushName is not used") FName BrushName
Protected Attributes
FText Description
const FSlateBrush * Icon
FText ShortName
FText TitleName
Private Member Functions
FTreeNodeGrouping (const FText &InShortName, const FText &InTitleName, const FText &InDescription, const FSlateBrush *InIcon)
FTreeNodeGrouping (const FTreeNodeGrouping &)=delete
virtual ~FTreeNodeGrouping ()
virtual FName GetColumnId () const override
virtual FText GetDescription () const override
virtual FTreeNodeGroupInfo GetGroupForNode (const FBaseTreeNodePtr InNode) const
virtual const FSlateBrush * GetIcon () const override
virtual FText GetShortName () const override
virtual FText GetTitleName () const override
virtual void GroupNodes (const TArray< FTableTreeNodePtr > &Nodes, FTableTreeNode &ParentGroup, TWeakPtr< FTable > InParentTable, IAsyncOperationProgress &InAsyncOperationProgress) const
INSIGHTS_DECLARE_RTTI (FTreeNodeGrouping, ITreeNodeGrouping) public
FTreeNodeGrouping & operator= (FTreeNodeGrouping &)=delete
UE_DEPRECATED (5.6, "BrushName is not used") FTreeNodeGrouping(const FText &InShortName
UE_DEPRECATED (5.6, "GetBrushName() is not used") virtual FName GetBrushName() const override
Private Attributes
const FText const FText const FName InBrushName
const FText const FText & InDescription
const FText const FText const FName const FSlateBrush * InIcon
const FText & InTitleName
Detailed Description
Definition at line 59 of file TreeNodeGrouping.h.
Constructor & Destructor Documentation
FTreeNodeGrouping() [1/2]
UE::Insights::FTreeNodeGrouping::FTreeNodeGrouping (const FText & InShortName, const FText & InTitleName, const FText & InDescription, const FSlateBrush * InIcon) private
References InDescription, InIcon, and InTitleName.
Referenced by FTreeNodeGrouping(), ~FTreeNodeGrouping(), INSIGHTS_DECLARE_RTTI(), UE::Insights::FTreeNodeGroupingByNameFirstLetter::INSIGHTS_DECLARE_RTTI(), UE::Insights::FTreeNodeGroupingByPathBreakdown::INSIGHTS_DECLARE_RTTI(), UE::Insights::FTreeNodeGroupingByType::INSIGHTS_DECLARE_RTTI(), UE::Insights::FTreeNodeGroupingByUniqueValue::INSIGHTS_DECLARE_RTTI(), and operator=().
FTreeNodeGrouping() [2/2]
UE::Insights::FTreeNodeGrouping::FTreeNodeGrouping (const FTreeNodeGrouping &) private delete
References FTreeNodeGrouping().
~FTreeNodeGrouping()
virtual UE::Insights::FTreeNodeGrouping::~FTreeNodeGrouping () inline private virtual
Definition at line 73 of file TreeNodeGrouping.h.
References FTreeNodeGrouping().
Member Function Documentation
GetColumnId()
virtual FName UE::Insights::FTreeNodeGrouping::GetColumnId () const inline override private virtual
Implements UE::Insights::ITreeNodeGrouping.
Reimplemented in UE::Insights::FTreeNodeGroupingByPathBreakdown, and UE::Insights::FTreeNodeGroupingByUniqueValue.
Definition at line 84 of file TreeNodeGrouping.h.
GetDescription()
virtual FText UE::Insights::FTreeNodeGrouping::GetDescription () const inline override private virtual
Implements UE::Insights::ITreeNodeGrouping.
Definition at line 77 of file TreeNodeGrouping.h.
References Description.
GetGroupForNode()
virtual FTreeNodeGroupInfo UE::Insights::FTreeNodeGrouping::GetGroupForNode (const FBaseTreeNodePtr InNode) const inline private virtual
Reimplemented in UE::Insights::FTreeNodeGroupingByNameFirstLetter, UE::Insights::FTreeNodeGroupingByType, and UE::Insights::FTreeNodeGroupingByUniqueValue.
Definition at line 86 of file TreeNodeGrouping.h.
References FName.
GetIcon()
virtual const FSlateBrush * UE::Insights::FTreeNodeGrouping::GetIcon () const inline override private virtual
Implements UE::Insights::ITreeNodeGrouping.
Definition at line 82 of file TreeNodeGrouping.h.
References GetIcon(), and Icon.
Referenced by GetIcon().
GetShortName()
virtual FText UE::Insights::FTreeNodeGrouping::GetShortName () const inline override private virtual
Definition at line 75 of file TreeNodeGrouping.h.
References ShortName.
GetTitleName()
virtual FText UE::Insights::FTreeNodeGrouping::GetTitleName () const inline override private virtual
Implements UE::Insights::ITreeNodeGrouping.
Definition at line 76 of file TreeNodeGrouping.h.
References TitleName.
GroupNodes()
virtual void UE::Insights::FTreeNodeGrouping::GroupNodes (const TArray< FTableTreeNodePtr > & Nodes, FTableTreeNode & ParentGroup, TWeakPtr< FTable > InParentTable, IAsyncOperationProgress & InAsyncOperationProgress) const private virtual
Reimplemented in UE::Insights::FTreeNodeGroupingByPathBreakdown, UE::Insights::FTreeNodeGroupingByUniqueValueCString, UE::Insights::FTreeNodeGroupingFlat, UE::Insights::TTreeNodeGroupingByUniqueValue< Type >, UE::Insights::TTreeNodeGroupingByUniqueValue< bool >, UE::Insights::TTreeNodeGroupingByUniqueValue< double >, UE::Insights::TTreeNodeGroupingByUniqueValue< float >, and UE::Insights::TTreeNodeGroupingByUniqueValue< int64 >.
INSIGHTS_DECLARE_RTTI()
UE::Insights::FTreeNodeGrouping::INSIGHTS_DECLARE_RTTI (FTreeNodeGrouping , ITreeNodeGrouping) inline private
Definition at line 61 of file TreeNodeGrouping.h.
References FTreeNodeGrouping(), and Icon.
operator=()
FTreeNodeGrouping & UE::Insights::FTreeNodeGrouping::operator= (FTreeNodeGrouping &) private delete
References FTreeNodeGrouping().
UE_DEPRECATED() [1/3]
UE::Insights::FTreeNodeGrouping::UE_DEPRECATED (5. 6, "BrushName is not used") protected
UE_DEPRECATED() [2/3]
UE::Insights::FTreeNodeGrouping::UE_DEPRECATED (5. 6, "BrushName is not used") const & private
UE_DEPRECATED() [3/3]
UE::Insights::FTreeNodeGrouping::UE_DEPRECATED (5. 6, "GetBrushName() is not used") const override private
Field Documentation
Description
FText UE::Insights::FTreeNodeGrouping::Description protected
Definition at line 92 of file TreeNodeGrouping.h.
Referenced by GetDescription().
Icon
const FSlateBrush* UE::Insights::FTreeNodeGrouping::Icon protected
Definition at line 95 of file TreeNodeGrouping.h.
Referenced by GetIcon(), and INSIGHTS_DECLARE_RTTI().
InBrushName
const FText const FText const FName UE::Insights::FTreeNodeGrouping::InBrushName private
Definition at line 68 of file TreeNodeGrouping.h.
InDescription
const FText const FText& UE::Insights::FTreeNodeGrouping::InDescription private
Definition at line 68 of file TreeNodeGrouping.h.
Referenced by FTreeNodeGrouping().
InIcon
const FText const FText const FName const FSlateBrush* UE::Insights::FTreeNodeGrouping::InIcon private
Definition at line 68 of file TreeNodeGrouping.h.
Referenced by FTreeNodeGrouping().
InTitleName
const FText& UE::Insights::FTreeNodeGrouping::InTitleName private
Definition at line 68 of file TreeNodeGrouping.h.
Referenced by FTreeNodeGrouping().
ShortName
FText UE::Insights::FTreeNodeGrouping::ShortName protected
Definition at line 90 of file TreeNodeGrouping.h.
Referenced by GetShortName().
TitleName
FText UE::Insights::FTreeNodeGrouping::TitleName protected
Definition at line 91 of file TreeNodeGrouping.h.
Referenced by GetTitleName().
The documentation for this class was generated from the following file:
TreeNodeGrouping.h