Unreal Engine 5.6 C++ API: Metasound::FAddressRouter::FTransmissionAddressKey Class Reference
Metasound::FAddressRouter::FTransmissionAddressKey Class Reference
Public Member Functions
FTransmissionAddressKey (const FTransmissionAddress &InCopy)
FTransmissionAddressKey (const FTransmissionAddressKey &InCopy)
FTransmissionAddressKey (TUniquePtr< FTransmissionAddress > &&InImpl)
virtual ~FTransmissionAddressKey ()=default
virtual TUniquePtr< FTransmissionAddress > Clone () const override
Clone the address.
virtual FName GetAddressType () const override
Return the type of address.
virtual FName GetDataType () const override
Return the data type.
FTransmissionAddressKey & operator= (const FTransmissionAddress &InOther)
virtual FString ToString () const override
Return a string representation of the address for debugging.
Public Member Functions inherited from Metasound::FTransmissionAddress
FTransmissionAddress ()=default
virtual ~FTransmissionAddress ()=default
METASOUNDFRONTEND_API bool operator!= (const FTransmissionAddress &InOther) const
METASOUNDFRONTEND_API bool operator== (const FTransmissionAddress &InOther) const
Private Member Functions
virtual uint32 GetHash () const override
Create a hash of the address.
virtual bool IsEqual (const FTransmissionAddress &InOther) const override
Determine if the given address is equal to this address.
Private Attributes
TUniquePtr< FTransmissionAddress > PImpl
Detailed Description
Definition at line 1060 of file MetasoundRouter.h.
Constructor & Destructor Documentation
FTransmissionAddressKey() [1/3]
Metasound::FAddressRouter::FTransmissionAddressKey::FTransmissionAddressKey (const FTransmissionAddress & InCopy)
References Metasound::FTransmissionAddress::FTransmissionAddress().
Referenced by FTransmissionAddressKey(), and operator=().
FTransmissionAddressKey() [2/3]
Metasound::FAddressRouter::FTransmissionAddressKey::FTransmissionAddressKey (const FTransmissionAddressKey & InCopy)
References FTransmissionAddressKey().
FTransmissionAddressKey() [3/3]
Metasound::FAddressRouter::FTransmissionAddressKey::FTransmissionAddressKey (TUniquePtr< FTransmissionAddress > && InImpl)
~FTransmissionAddressKey()
virtual Metasound::FAddressRouter::FTransmissionAddressKey::~FTransmissionAddressKey () virtual default
Member Function Documentation
Clone()
virtual TUniquePtr< FTransmissionAddress > Metasound::FAddressRouter::FTransmissionAddressKey::Clone () const override virtual
Clone the address.
Implements Metasound::FTransmissionAddress.
GetAddressType()
virtual FName Metasound::FAddressRouter::FTransmissionAddressKey::GetAddressType () const override virtual
Return the type of address.
The AddressType must be unique per a subclass of FTransmissionAddress as it is used to determine the validity of a static_cast from FTransmissionAddress to the derived address type.
Implements Metasound::FTransmissionAddress.
GetDataType()
virtual FName Metasound::FAddressRouter::FTransmissionAddressKey::GetDataType () const override virtual
Return the data type.
Implements Metasound::FTransmissionAddress.
GetHash()
virtual uint32 Metasound::FAddressRouter::FTransmissionAddressKey::GetHash () const override private virtual
Create a hash of the address.
Implements Metasound::FTransmissionAddress.
IsEqual()
virtual bool Metasound::FAddressRouter::FTransmissionAddressKey::IsEqual (const FTransmissionAddress & InOther) const override private virtual
Determine if the given address is equal to this address.
Implements Metasound::FTransmissionAddress.
References Metasound::FTransmissionAddress::FTransmissionAddress().
operator=()
FTransmissionAddressKey & Metasound::FAddressRouter::FTransmissionAddressKey::operator= (const FTransmissionAddress & InOther)
References Metasound::FTransmissionAddress::FTransmissionAddress(), and FTransmissionAddressKey().
ToString()
virtual FString Metasound::FAddressRouter::FTransmissionAddressKey::ToString () const override virtual
Return a string representation of the address for debugging.
Implements Metasound::FTransmissionAddress.
Field Documentation
PImpl
TUniquePtr<FTransmissionAddress> Metasound::FAddressRouter::FTransmissionAddressKey::PImpl private
Definition at line 1078 of file MetasoundRouter.h.
The documentation for this class was generated from the following file:
MetasoundRouter.h