Unreal Engine 5.6 C++ API: FWindowsPlatformTime Struct Reference
FWindowsPlatformTime Struct Reference
Windows implementation of the Time OS functions.
#include "WindowsPlatformTime.h"
Static Public Member Functions
static void AutoUpdateGameThreadCPUTime (double UpdateInterval)
static FORCEINLINE uint32 Cycles ()
static FORCEINLINE uint64 Cycles64 ()
static FCPUTime GetCPUTime ()
static double GetLastIntervalThreadCPUTimeInSeconds ()
static FCPUTime GetThreadCPUTime ()
static double InitTiming ()
static FORCEINLINE double Seconds ()
static void SystemTime (int32 &Year, int32 &Month, int32 &DayOfWeek, int32 &Day, int32 &Hour, int32 &Min, int32 &Sec, int32 &MSec)
static bool UpdateCPUTime (float DeltaTime)
static bool UpdateThreadCPUTime (float=0.0)
static void UtcTime (int32 &Year, int32 &Month, int32 &DayOfWeek, int32 &Day, int32 &Hour, int32 &Min, int32 &Sec, int32 &MSec)
Static Public Member Functions inherited from FGenericPlatformTime
static void AutoUpdateGameThreadCPUTime (double UpdateInterval)
Registers automatic updates of Game Thread CPU utilization.
static FCPUTime GetCPUTime ()
static double GetLastIntervalCPUTimeInSeconds ()
static double GetLastIntervalThreadCPUTimeInSeconds ()
Gets the per-thread CPU processing time (kernel + user) from the last update.
static double GetSecondsPerCycle ()
Each platform implements these two functions, which return the current time in platform-specific cpu cycles.
static double GetSecondsPerCycle64 ()
Returns seconds per cycle, to pair with Cycles64().
static FCPUTime GetThreadCPUTime ()
Gets current threads CPU Utilization.
static FString PrettyTime (double Seconds)
Returns a pretty-string for a time given in seconds.
static uint64 SecondsToCycles64 (double Seconds)
Convert seconds to cycles, can be added to Cycles64 to set a high resolution timeout.
static TCHAR * StrDate (TCHAR *Dest, SIZE_T DestSize)
Get the system date.
static TCHAR * StrTime (TCHAR *Dest, SIZE_T DestSize)
Get the system time.
static const TCHAR * StrTimestamp ()
Returns a timestamp string built from the current date and time.
static float ToMilliseconds (const uint32 Cycles)
Converts cycles to milliseconds.
static double ToMilliseconds64 (const uint64 Cycles)
Converts 64 bit cycles to milliseconds.
static float ToSeconds (const uint32 Cycles)
Converts cycles to seconds.
static double ToSeconds64 (const uint64 Cycles)
Converts 64 bit cycles to seconds.
static bool UpdateCPUTime (float DeltaTime)
Updates CPU utilization, called through a delegate from the Core ticker.
static bool UpdateThreadCPUTime (float=0.0)
Updates current thread CPU utilization, calling is user defined per-thread (unused float parameter, is for FTicker compatibility).
Static Protected Attributes
static float CPUTimePctRelative
Percentage CPU utilization for the last interval relative to one core.
Static Protected Attributes inherited from FGenericPlatformTime
static double LastIntervalCPUTimeInSeconds
static double SecondsPerCycle
static double SecondsPerCycle64
Detailed Description
Windows implementation of the Time OS functions.
Please see following UDN post about using rdtsc on processors that support result being invariant across cores.
https://udn.epicgames.com/lists/showpost.php?id=46794&list=unprog3
Definition at line 18 of file WindowsPlatformTime.h.
Member Function Documentation
AutoUpdateGameThreadCPUTime()
void FWindowsPlatformTime::AutoUpdateGameThreadCPUTime (double UpdateInterval) static
Cycles()
FORCEINLINE uint32 FWindowsPlatformTime::Cycles () inline static
Definition at line 32 of file WindowsPlatformTime.h.
References Cycles(), FORCEINLINE, and Windows::QueryPerformanceCounter().
Referenced by Cycles(), Cycles64(), and Seconds().
Cycles64()
FORCEINLINE uint64 FWindowsPlatformTime::Cycles64 () inline static
Definition at line 39 of file WindowsPlatformTime.h.
References Cycles(), and FORCEINLINE.
GetCPUTime()
FCPUTime FWindowsPlatformTime::GetCPUTime () static
GetLastIntervalThreadCPUTimeInSeconds()
double FWindowsPlatformTime::GetLastIntervalThreadCPUTimeInSeconds () static
GetThreadCPUTime()
FCPUTime FWindowsPlatformTime::GetThreadCPUTime () static
InitTiming()
double FWindowsPlatformTime::InitTiming () static
Seconds()
FORCEINLINE double FWindowsPlatformTime::Seconds () inline static
Definition at line 23 of file WindowsPlatformTime.h.
References Cycles(), FORCEINLINE, FGenericPlatformTime::GetSecondsPerCycle(), and Windows::QueryPerformanceCounter().
SystemTime()
void FWindowsPlatformTime::SystemTime (int32 & Year, int32 & Month, int32 & DayOfWeek, int32 & Day, int32 & Hour, int32 & Min, int32 & Sec, int32 & MSec) static
UpdateCPUTime()
bool FWindowsPlatformTime::UpdateCPUTime (float DeltaTime) static
References DeltaTime.
UpdateThreadCPUTime()
bool FWindowsPlatformTime::UpdateThreadCPUTime (float = 0.0) static
UtcTime()
void FWindowsPlatformTime::UtcTime (int32 & Year, int32 & Month, int32 & DayOfWeek, int32 & Day, int32 & Hour, int32 & Min, int32 & Sec, int32 & MSec) static
Field Documentation
CPUTimePctRelative
float FWindowsPlatformTime::CPUTimePctRelative static protected
Percentage CPU utilization for the last interval relative to one core.
Definition at line 60 of file WindowsPlatformTime.h.
The documentation for this struct was generated from the following file:
WindowsPlatformTime.h