Unreal Engine 5.6 C++ API: UReimportTextureFactory Class Reference
UReimportTextureFactory Class Reference
#include "ReimportTextureFactory.h"
Private Member Functions
virtual bool CanReimport (UObject *Obj, TArray< FString > &OutFilenames) override
Check to see if the handler is capable of reimporting the object.
virtual UTexture2D * CreateTexture2D (UObject *InParent, FName Name, EObjectFlags Flags) override
virtual UTextureCube * CreateTextureCube (UObject *InParent, FName Name, EObjectFlags Flags) override
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UTexture > pOriginalTex
virtual int32 GetPriority () const override
Get the import priority for this handler.
virtual bool IsAutomatedImport () const override
virtual EReimportResult::Type Reimport (UObject *Obj) override
Attempt to reimport the specified object from its source.
virtual void SetReimportPaths (UObject *Obj, const TArray< FString > &NewReimportPaths) override
Sets the reimport path(s) for the specified object.
Additional Inherited Members
Public Member Functions inherited from FReimportHandler
FReimportHandler ()
Constructor.
virtual ~FReimportHandler ()
Destructor.
virtual TObjectPtr< UObject > * GetFactoryObject () const
Returns the UFactory object associated with this reimport handler.
virtual bool IsAutomatedReimport () const
When True dialog prompts should not appear.
virtual bool IsForceShowDialog () const
When True dialog prompts will prompts even if the show dialog setting is false.
virtual bool IsInterchangeFactory () const
virtual void PostImportCleanUp ()
Call after multiple import happen.
virtual EReimportResult::Type Reimport (UObject *Obj, int32 SourceFileIndex)
Attempt to reimport the specified object from its source.
virtual void SetAutomatedReimport (const bool InAutomatedReimport)
Sets automated, when True dialog prompts should not appear.
virtual void SetForceShowDialog (const bool InbForceShowDialog)
Sets force show dialog, when True dialog will prompts even if the show dialog setting is false.
void SetPreferredReimportPath (const FString &Path)
Sets the preferred reimport path, for aiding in resolving reimporting objects where the object path differs from the new path (ex.
virtual void SetReimportPaths (UObject *Obj, const FString &NewReimportPath, const int32 SourceIndex)
Sets the reimport path(s) for the specified object at the specified index.
virtual void SetReimportSourceIndex (UObject *Obj, const int32 SourceIndex)
If we want to import a specific source index and there is some settings to update in the asset import data before starting the re-import.
Protected Attributes inherited from FReimportHandler
bool bAutomatedReimport
bool bForceShowDialog = false
FString PreferredReimportPath
Detailed Description
Definition at line 19 of file ReimportTextureFactory.h.
Member Function Documentation
CanReimport()
virtual bool UReimportTextureFactory::CanReimport (UObject * Obj, TArray< FString > & OutFilenames) override private virtual
Check to see if the handler is capable of reimporting the object.
Parameters
Obj Object to attempt to reimport
OutFilenames The filename(s) of the source art for the specified object
Returns
true if this handler is capable of reimporting the provided object
Implements FReimportHandler.
References CanReimport().
Referenced by CanReimport().
CreateTexture2D()
virtual UTexture2D * UReimportTextureFactory::CreateTexture2D (UObject * InParent, FName Name, EObjectFlags Flags) override private virtual
References CreateTexture2D(), Flags, and Name.
Referenced by CreateTexture2D().
CreateTextureCube()
virtual UTextureCube * UReimportTextureFactory::CreateTextureCube (UObject * InParent, FName Name, EObjectFlags Flags) override private virtual
References CreateTextureCube(), Flags, and Name.
Referenced by CreateTextureCube().
GENERATED_UCLASS_BODY()
UReimportTextureFactory::GENERATED_UCLASS_BODY () private
References UPROPERTY.
GetPriority()
virtual int32 UReimportTextureFactory::GetPriority () const override private virtual
Get the import priority for this handler.
Import handlers with higher priority values will take precedent over lower priorities.
Reimplemented from FReimportHandler.
References GetPriority().
Referenced by GetPriority().
IsAutomatedImport()
virtual bool UReimportTextureFactory::IsAutomatedImport () const override private virtual
References IsAutomatedImport().
Referenced by IsAutomatedImport().
Reimport()
virtual EReimportResult::Type UReimportTextureFactory::Reimport (UObject * Obj) override private virtual
Attempt to reimport the specified object from its source.
Parameters
Obj Object to attempt to reimport
Returns
EReimportResult::Succeeded if this handler was able to handle reimporting the provided object, EReimportResult::Failed if this handler was unable to handle reimporting the provided object or EReimportResult::Cancelled if the handler was cancelled part-way through re-importing the provided object.
Implements FReimportHandler.
References Reimport().
Referenced by Reimport().
SetReimportPaths()
virtual void UReimportTextureFactory::SetReimportPaths (UObject * Obj, const TArray< FString > & NewReimportPaths) override private virtual
Sets the reimport path(s) for the specified object.
Parameters
Obj Object for which to change the reimport path(s)
NewReimportPaths The new path(s) to set on the object
Implements FReimportHandler.
References SetReimportPaths().
Referenced by SetReimportPaths().
The documentation for this class was generated from the following file:
ReimportTextureFactory.h