Unreal Engine 5.6 C++ API: FAcquiredResources Class Reference
FAcquiredResources Class Reference
Helper class that automates releasing of acquired resources.
#include "AcquiredResources.h"
Data Structures
struct FReleaser
Private array of releaser data.
Public Member Functions
FAcquiredResources ()=default
Default construction.
FAcquiredResources (const FAcquiredResources &)=delete
Copy construction is disabled.
FAcquiredResources (FAcquiredResources &&)=default
Move construction/assignment implies a transfer of ownership of the acquired resources.
~FAcquiredResources ()
Destructor that releases any acquired resources.
template<typename T>
void Add (FName InIdentifier, T &&InReleaser)
Add a named resource to this container by providing its releaser function.
template<typename T>
void Add (T &&InReleaser)
Add an acquired resource to this container by providing its releaser function.
FAcquiredResources & operator= (const FAcquiredResources &)=delete
FAcquiredResources & operator= (FAcquiredResources &&)=default
void Release ()
Release all acquired resources in reverse order.
void Release (FName InIdentifier)
Release the resource(s) that correspond to the specified identifier.
Private Attributes
TArray< FReleaser > Releasers
Detailed Description
Helper class that automates releasing of acquired resources.
Definition at line 9 of file AcquiredResources.h.
Constructor & Destructor Documentation
FAcquiredResources() [1/3]
FAcquiredResources::FAcquiredResources () default
Default construction.
Referenced by FAcquiredResources(), FAcquiredResources(), operator=(), and operator=().
FAcquiredResources() [2/3]
FAcquiredResources::FAcquiredResources (const FAcquiredResources &) delete
Copy construction is disabled.
References FAcquiredResources().
FAcquiredResources() [3/3]
FAcquiredResources::FAcquiredResources (FAcquiredResources &&) default
Move construction/assignment implies a transfer of ownership of the acquired resources.
References FAcquiredResources().
~FAcquiredResources()
FAcquiredResources::~FAcquiredResources () inline
Destructor that releases any acquired resources.
Definition at line 27 of file AcquiredResources.h.
References Release().
Member Function Documentation
Add() [1/2]
template<typename T> void FAcquiredResources::Add (FName InIdentifier, T && InReleaser) inline
Add a named resource to this container by providing its releaser function.
Parameters
InIdentifier Identifier for this resource
InReleaser A releaser function of the signature void() that defines how to release the resource
Definition at line 50 of file AcquiredResources.h.
References MoveTemp(), and Releasers.
Add() [2/2]
template<typename T> void FAcquiredResources::Add (T && InReleaser) inline
Add an acquired resource to this container by providing its releaser function.
Parameters
InReleaser A releaser function of the signature void() that defines how to release the resource
Definition at line 38 of file AcquiredResources.h.
References MoveTemp(), and Releasers.
operator=() [1/2]
FAcquiredResources & FAcquiredResources::operator= (const FAcquiredResources &) delete
References FAcquiredResources().
operator=() [2/2]
FAcquiredResources & FAcquiredResources::operator= (FAcquiredResources &&) default
References FAcquiredResources().
Release() [1/2]
void FAcquiredResources::Release () inline
Release all acquired resources in reverse order.
Definition at line 58 of file AcquiredResources.h.
References Releasers.
Referenced by ~FAcquiredResources().
Release() [2/2]
void FAcquiredResources::Release (FName InIdentifier) inline
Release the resource(s) that correspond to the specified identifier.
Parameters
InIdentifier The identifier of the resource(s) to release
Definition at line 73 of file AcquiredResources.h.
References check, No, and Releasers.
Field Documentation
Releasers
TArray<FReleaser> FAcquiredResources::Releasers private
Definition at line 94 of file AcquiredResources.h.
Referenced by Add(), Add(), Release(), and Release().
The documentation for this class was generated from the following file:
AcquiredResources.h