Unreal Engine 5.6 C++ API: FClipSMTriangle Struct Reference
FClipSMTriangle Struct Reference
Properties of a clipped static mesh triangle.
#include "GeomTools.h"
Public Member Functions
FClipSMTriangle (int32 Init)
void ComputeGradientsAndNormal ()
Compute the triangle's normal, and the gradients of the triangle's vertex attributes over XYZ.
Public Member Functions inherited from FClipSMFace
void CopyFace (const FClipSMFace &OtherFace)
Data Fields
FClipSMVertex Vertices [3]
Data Fields inherited from FClipSMFace
bool bOverrideTangentBasis
FMatrix ColorGradient
FVector FaceNormal
int32 MaterialIndex
int32 NumUVs
uint32 SmoothingMask
FMatrix TangentXGradient
FMatrix TangentYGradient
FMatrix TangentZGradient
FMatrix UVGradient [8]
Detailed Description
Properties of a clipped static mesh triangle.
Definition at line 100 of file GeomTools.h.
Constructor & Destructor Documentation
FClipSMTriangle()
FClipSMTriangle::FClipSMTriangle (int32 Init) inline
Definition at line 107 of file GeomTools.h.
References FClipSMTriangle(), Init, and FMemory::Memzero().
Referenced by FClipSMTriangle().
Member Function Documentation
ComputeGradientsAndNormal()
void FClipSMTriangle::ComputeGradientsAndNormal ()
Compute the triangle's normal, and the gradients of the triangle's vertex attributes over XYZ.
Field Documentation
Vertices
FClipSMVertex FClipSMTriangle::Vertices[3]
Definition at line 102 of file GeomTools.h.
The documentation for this struct was generated from the following file:
GeomTools.h