Unreal Engine 5.6 C++ API: UE::AnimNext::FConstExprUID Struct Reference
UE::AnimNext::FConstExprUID Struct Reference final
A constexpr safe UID.
#include "ConstExprUID.h"
Public Member Functions
constexpr FConstExprUID () noexcept
constexpr FConstExprUID (FFConstExprUIDRaw InUID, const TCHAR *InDebugName=TEXT("<Unknown ConstExprUID Name>")) noexcept
constexpr const TCHAR * GetDebugName () const noexcept
constexpr FFConstExprUIDRaw GetUID () const noexcept
constexpr bool IsValid () const noexcept
Static Public Member Functions
static constexpr FConstExprUID MakeFromString (const TCHAR *InName) noexcept
Private Attributes
const TCHAR * DebugName
FFConstExprUIDRaw UID
Static Private Attributes
static constexpr FFConstExprUIDRaw INVALID_UID = 0
Detailed Description
A constexpr safe UID.
Encapsulates an constexpr UID. The string is exposed in non-shipping builds for logging and debugging purposes. The UID should be generated from the provided string using FNV1a with 32 bits.
The whole struct is meant to be 'constexpr' to allow inlining.
Definition at line 22 of file ConstExprUID.h.
Constructor & Destructor Documentation
FConstExprUID() [1/2]
UE::AnimNext::FConstExprUID::FConstExprUID () inline constexpr noexcept
Definition at line 25 of file ConstExprUID.h.
References INVALID_UID, and UID.
Referenced by MakeFromString().
FConstExprUID() [2/2]
UE::AnimNext::FConstExprUID::FConstExprUID (FFConstExprUIDRaw InUID, const TCHAR * InDebugName = TEXT("<Unknown ConstExprUID Name>")) inline explicit constexpr noexcept
Definition at line 34 of file ConstExprUID.h.
References UID.
Member Function Documentation
GetDebugName()
const TCHAR * UE::AnimNext::FConstExprUID::GetDebugName () const inline constexpr noexcept
Definition at line 50 of file ConstExprUID.h.
References DebugName.
GetUID()
FFConstExprUIDRaw UE::AnimNext::FConstExprUID::GetUID () const inline constexpr noexcept
Definition at line 54 of file ConstExprUID.h.
References UID.
Referenced by UE::AnimNext::operator<().
IsValid()
bool UE::AnimNext::FConstExprUID::IsValid () const inline constexpr noexcept
Definition at line 57 of file ConstExprUID.h.
References INVALID_UID, and UID.
MakeFromString()
constexpr FConstExprUID UE::AnimNext::FConstExprUID::MakeFromString (const TCHAR * InName) inline static constexpr noexcept
Definition at line 43 of file ConstExprUID.h.
References FConstExprUID(), UE::HashStringFNV1a32(), InName, and MakeStringView().
Field Documentation
DebugName
const TCHAR* UE::AnimNext::FConstExprUID::DebugName private
Definition at line 65 of file ConstExprUID.h.
Referenced by GetDebugName().
INVALID_UID
FFConstExprUIDRaw UE::AnimNext::FConstExprUID::INVALID_UID = 0 static constexpr private
Definition at line 60 of file ConstExprUID.h.
Referenced by FConstExprUID(), and IsValid().
UID
FFConstExprUIDRaw UE::AnimNext::FConstExprUID::UID private
Definition at line 62 of file ConstExprUID.h.
Referenced by FConstExprUID(), FConstExprUID(), GetUID(), and IsValid().
The documentation for this struct was generated from the following file:
ConstExprUID.h