Unreal Engine 5.6 C++ API: Metasound::TDataWriteReference< DataType > Class Template Reference
Metasound::TDataWriteReference< DataType > Class Template Reference
TDataWriteReference provides write access to a shared parameter reference.
#include "MetasoundDataReference.h"
Public Member Functions
TDataWriteReference (const TDataWriteReference< DataType > &Other)=default
Enable copy constructor.
TDataWriteReference (TDataWriteReference< DataType > &&Other)=default
Enable move constructor.
virtual TUniquePtr< IDataReference > Clone () const override
Create a clone of this parameter reference.
FORCEINLINE DataType * Get () const
Non-const access to the underlying parameter object.
operator TDataReadReference< DataType > () const
Implicit conversion to a readable parameter.
FORCEINLINE DataType & operator* () const
Non-const access to the underlying parameter object.
FORCEINLINE DataType * operator-> () const
Non-const access to the underlying parameter object.
TDataWriteReference< DataType > & operator= (const TDataWriteReference< DataType > &Other)=default
Enable assignment operator.
TDataWriteReference< DataType > & operator= (TDataWriteReference< DataType > &&Other)=default
Enable move operator.
Public Member Functions inherited from Metasound::TDataReference< DataType >
TDataReference (const TDataReference< DataType > &Other)=default
Enable copy constructor.
TDataReference (TDataReference< DataType > &&Other)=default
Enable move constructor.
virtual const void *const GetDataTypeId () const override
Return the ID of the underlying type.
virtual const FName & GetDataTypeName () const override
Return the name of the underlying type.
virtual void * GetRaw () const override
Return a raw pointer to the data.
TDataReference< DataType > & operator= (const TDataReference< DataType > &Other)=default
Enable copy operator.
TDataReference< DataType > & operator= (TDataReference< DataType > &&Other)=default
Enable move operator.
Public Member Functions inherited from Metasound::IDataReference
virtual ~IDataReference ()=default
Static Public Member Functions
template<typename... ArgTypes>
static TDataWriteReference< DataType > CreateNew (ArgTypes &&... Args)
This should be used to construct a new DataType object and return this TDataWriteReference as a wrapper around it.
Static Public Member Functions inherited from Metasound::TDataReference< DataType >
template<typename... ArgTypes>
static TDataReference< DataType > CreateNew (ArgTypes &&... Args)
This should be used to construct a new DataType object and return this TDataReference as a wrapper around it.
Private Member Functions
TDataWriteReference (const TDataReference< DataType > &InDataReference)
Create a writable ref from a blank parameter ref.
template<typename... ArgTypes>
TDataWriteReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args)
Friends
class TDataReadReference< DataType >
template<typename T>
TDataWriteReference< T > WriteCast (const TDataReadReference< T > &InReadableRef)
Additional Inherited Members
Public Types inherited from Metasound::TDataReference< DataType >
typedef TDataReferenceTypeInfo< DataType > FInfoType
Static Public Attributes inherited from Metasound::IDataReference
static METASOUNDGRAPHCORE_API const FName RouterName
Protected Types inherited from Metasound::TDataReference< DataType >
typedef TSharedRef< DataType, ESPMode::NotThreadSafe > FRefType
Protected Member Functions inherited from Metasound::TDataReference< DataType >
template<typename... ArgTypes>
TDataReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args)
This constructor forwards arguments to an underlying constructor.
Protected Attributes inherited from Metasound::TDataReference< DataType >
FRefType ObjectReference
Detailed Description
template<typename DataType>
class Metasound::TDataWriteReference< DataType >
TDataWriteReference provides write access to a shared parameter reference.
Definition at line 352 of file MetasoundDataReference.h.
Constructor & Destructor Documentation
TDataWriteReference() [1/4]
template<typename DataType> template<typename... ArgTypes> Metasound::TDataWriteReference< DataType >::TDataWriteReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args) inline private
Definition at line 356 of file MetasoundDataReference.h.
Referenced by Metasound::TDataWriteReference< FMidiClockSongPosition >::CreateNew().
TDataWriteReference() [2/4]
template<typename DataType> Metasound::TDataWriteReference< DataType >::TDataWriteReference (const TDataReference< DataType > & InDataReference) inline private
Create a writable ref from a blank parameter ref.
Should be done with care and understanding of side-effects of converting a ref to a writable ref.
Definition at line 356 of file MetasoundDataReference.h.
TDataWriteReference() [3/4]
template<typename DataType> Metasound::TDataWriteReference< DataType >::TDataWriteReference (const TDataWriteReference< DataType > & Other) default
Enable copy constructor.
TDataWriteReference() [4/4]
template<typename DataType> Metasound::TDataWriteReference< DataType >::TDataWriteReference (TDataWriteReference< DataType > && Other) default
Enable move constructor.
Member Function Documentation
Clone()
template<typename DataType> virtual TUniquePtr< IDataReference > Metasound::TDataWriteReference< DataType >::Clone () const inline override virtual
Create a clone of this parameter reference.
Implements Metasound::IDataReference.
Definition at line 419 of file MetasoundDataReference.h.
CreateNew()
template<typename DataType> template<typename... ArgTypes> TDataWriteReference< DataType > Metasound::TDataWriteReference< DataType >::CreateNew (ArgTypes &&... Args) inline static
This should be used to construct a new DataType object and return this TDataWriteReference as a wrapper around it.
Definition at line 376 of file MetasoundDataReference.h.
Referenced by Metasound::VertexDataPrivate::TFactoryFacade< TDataWriteReference< DataType > >::CreateWithArgs(), Metasound::FOutputVertexInterfaceData::GetOrConstructDataWriteReference(), and Metasound::FInputVertexInterfaceData::UE_DEPRECATED().
Get()
template<typename DataType> FORCEINLINE DataType * Metasound::TDataWriteReference< DataType >::Get () const inline
Non-const access to the underlying parameter object.
Definition at line 413 of file MetasoundDataReference.h.
Referenced by Metasound::FAnyDataReference::GetWritableValue().
operator TDataReadReference< DataType >()
template<typename DataType> Metasound::TDataWriteReference< DataType >::operator TDataReadReference< DataType > () const inline
Implicit conversion to a readable parameter.
Definition at line 395 of file MetasoundDataReference.h.
operator*()
template<typename DataType> FORCEINLINE DataType & Metasound::TDataWriteReference< DataType >::operator* () const inline
Non-const access to the underlying parameter object.
Definition at line 401 of file MetasoundDataReference.h.
operator->()
template<typename DataType> FORCEINLINE DataType * Metasound::TDataWriteReference< DataType >::operator-> () const inline
Non-const access to the underlying parameter object.
Definition at line 407 of file MetasoundDataReference.h.
operator=() [1/2]
template<typename DataType> TDataWriteReference< DataType > & Metasound::TDataWriteReference< DataType >::operator= (const TDataWriteReference< DataType > & Other) default
Enable assignment operator.
operator=() [2/2]
template<typename DataType> TDataWriteReference< DataType > & Metasound::TDataWriteReference< DataType >::operator= (TDataWriteReference< DataType > && Other) default
Enable move operator.
Friends And Related Symbol Documentation
TDataReadReference< DataType >
template<typename DataType> friend class TDataReadReference< DataType > friend
Definition at line 419 of file MetasoundDataReference.h.
Referenced by Metasound::TDataWriteReference< ArrayType >::operator TDataReadReference< ArrayType >().
WriteCast
template<typename DataType> template<typename T> TDataWriteReference< T > WriteCast (const TDataReadReference< T > & InReadableRef) friend
The documentation for this class was generated from the following file:
MetasoundDataReference.h