Unreal Engine 5.6 C++ API: FSkeletalMeshStreamIn Class Reference
FSkeletalMeshStreamIn Class Reference
#include "SkeletalMeshUpdate.h"
Data Structures
struct FIntermediateBuffers
Correspond to the buffers in FSkeletalMeshLODRenderData.
Public Member Functions
FSkeletalMeshStreamIn (const USkeletalMesh *InMesh, EThreadType CreateResourcesThread)
virtual ~FSkeletalMeshStreamIn ()
Public Member Functions inherited from FSkeletalMeshUpdate
FSkeletalMeshUpdate (const USkeletalMesh *InMesh)
virtual ~FSkeletalMeshUpdate ()
virtual void Abort ()
Cancel the current update.
Public Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
TRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
EThreadType GetRelevantThread () const final override
Return the thread relevant to the next step of execution.
void PushTask (const FContext &Context, EThreadType InTaskThread, const FCallback &InTaskCallback, EThreadType InCancelationThread, const FCallback &InCancelationCallback)
Defines the next step to be executed.
Public Member Functions inherited from FRenderAssetUpdate
FRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
FReturnedRefCountValue AddRef () const final override
ETaskState DoLock ()
Perform a lock on the object, preventing any other thread from processing a pending task in Tick().
void DoUnlock (ETaskState PreviousTaskState)
Release any lock on the object, allowing other thread to modify it.
uint32 GetRefCount () const final override
bool IsCancelled () const
Returns whether the task was aborted through Abort() or cancelled.
bool IsCompleted () const
Returns whether the task has finished executing and there is no other thread possibly accessing it.
bool IsLocked () const
bool IsSuccessfullyFinished () const
Returns whether this update has finished successfully.
uint32 Release () const final override
void Tick (EThreadType InCurrentThread)
Do or schedule any pending work for a given texture.
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Protected Member Functions
void CreateBuffers (const FContext &Context)
Create buffers with new LOD data.
void DiscardNewLODs (const FContext &Context)
Discard newly streamed-in CPU data.
void DoCancel (const FContext &Context)
Discard streamed-in CPU data and intermediate RHI buffers.
void DoFinishUpdate (const FContext &Context)
Apply the new buffers (if not cancelled) and finish the update process.
Protected Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
void ClearCallbacks ()
ETaskState TickInternal (EThreadType InCurrentThread, bool bCheckForSuspension) final override
Protected Member Functions inherited from FRenderAssetUpdate
virtual ~FRenderAssetUpdate ()
void MarkAsCancelled ()
Set the task state as cancelled.
void MarkAsSuccessfullyFinished ()
void ScheduleAsyncTask ()
void ScheduleGTTask ()
void ScheduleRenderTask ()
Protected Attributes
const EThreadType CreateResourcesThread
The thread to use for recording the above command list.
FIntermediateBuffers IntermediateBuffersArray [MAX_MESH_LOD_COUNT]
The intermediate buffers created in the update process.
FRHICommandList * StreamingRHICmdList = nullptr
RHI command list used for creating buffers and replacing the streaming placeholders.
Protected Attributes inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
FCallback CancelationCallback
The callback handling the cancellation of the update (only if the update gets cancelled).
EThreadType CancelationThread
The thread on which to call the cancellation of the update (only if the update gets cancelled).
FCallback TaskCallback
The callback that will perform the next step of the update.
EThreadType TaskThread
The thread on which to call the next step of the update, being TaskCallback.
Protected Attributes inherited from FRenderAssetUpdate
bool bDeferExecution
Defer execution even if a task pushes a new task on the same thread.
bool bIsCancelled
Whether the task has been cancelled because the update could not proceed or because the user called Abort().
bool bSuccess
Whether this update finished successfully.
FCriticalSection CS
Critical Section.
const int32 CurrentFirstLODIdx = INDEX_NONE
const int32 PendingFirstLODIdx = INDEX_NONE
const FStreamableRenderResourceState ResourceState
The streamable state requested.
int32 ScheduledAsyncTasks
Number of Ticks scheduled on async tasks.
int32 ScheduledGTTasks
Number of Ticks scheduled on the game thread.
int32 ScheduledRenderTasks
Number of Ticks scheduled on the render thread.
const UStreamableRenderAsset * StreamableAsset = nullptr
The asset updated.
volatile ETaskState TaskState
The state of the work yet to be performed to complete the update or cancelation.
FThreadSafeCounter TaskSynchronization
Synchronization used for trigger the task next step execution.
Additional Inherited Members
Public Types inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
typedef TFunction< void(const FContext &Context)> FCallback
A callback used to perform a task in the update process.
typedef FSkelMeshUpdateContext FContext
Public Types inherited from FRenderAssetUpdate
enum ETaskState {
TS_Done , TS_Suspended , TS_InProgress , TS_Locked ,
TS_Init
}
The state of scheduled work for the update process.
enum EThreadType {
TT_None , TT_Render , TT_Async , TT_GameThread ,
TT_GameRunningAsync
}
A thread type used for doing a part of the update process.
Protected Types inherited from FRenderAssetUpdate
typedef FAutoDeleteAsyncTask< FMipUpdateTask > FAsyncMipUpdateTask
The async task to update this object, only one can be active at anytime.
Detailed Description
Definition at line 74 of file SkeletalMeshUpdate.h.
Constructor & Destructor Documentation
FSkeletalMeshStreamIn()
FSkeletalMeshStreamIn::FSkeletalMeshStreamIn (const USkeletalMesh * InMesh, EThreadType CreateResourcesThread)
Definition at line 117 of file SkeletalMeshUpdate.cpp.
References FSkeletalMeshUpdate::FSkeletalMeshUpdate(), FRenderAssetUpdate::bIsCancelled, CreateResourcesThread, FRenderAssetUpdate::CurrentFirstLODIdx, ensure, and FRenderAssetUpdate::PendingFirstLODIdx.
Referenced by FSkeletalMeshStreamIn_DDC::FSkeletalMeshStreamIn_DDC(), and FSkeletalMeshStreamIn_IO::FSkeletalMeshStreamIn_IO().
~FSkeletalMeshStreamIn()
FSkeletalMeshStreamIn::~FSkeletalMeshStreamIn () virtual
Definition at line 127 of file SkeletalMeshUpdate.cpp.
References check, and StreamingRHICmdList.
Member Function Documentation
CreateBuffers()
void FSkeletalMeshStreamIn::CreateBuffers (const FContext & Context) protected
Create buffers with new LOD data.
Definition at line 132 of file SkeletalMeshUpdate.cpp.
References check, FRenderAssetUpdate::CurrentFirstLODIdx, FSkeletalMeshLODRenderData::GetNumVertices(), GSkelMeshMaxNumResourceUpdatesPerBatch, FSkeletalMeshLODRenderData::IncrementMemoryStats(), FSkeletalMeshLODRenderData::InitMorphResources(), IntermediateBuffersArray, IsRayTracingEnabled(), LLM_SCOPE, FRenderAssetUpdate::PendingFirstLODIdx, SCOPED_DRAW_EVENTF, StreamingRHICmdList, and TEXT.
Referenced by FSkeletalMeshStreamIn_DDC::DoCreateBuffers(), and FSkeletalMeshStreamIn_IO::DoCreateBuffers().
DiscardNewLODs()
void FSkeletalMeshStreamIn::DiscardNewLODs (const FContext & Context) protected
Discard newly streamed-in CPU data.
Definition at line 174 of file SkeletalMeshUpdate.cpp.
References FRenderAssetUpdate::CurrentFirstLODIdx, FRenderAssetUpdate::PendingFirstLODIdx, and FSkeletalMeshLODRenderData::ReleaseCPUResources().
Referenced by DoCancel().
DoCancel()
void FSkeletalMeshStreamIn::DoCancel (const FContext & Context) protected
Discard streamed-in CPU data and intermediate RHI buffers.
Definition at line 248 of file SkeletalMeshUpdate.cpp.
References check, DiscardNewLODs(), GIsEditor, and StreamingRHICmdList.
Referenced by FSkeletalMeshStreamIn_IO::Cancel(), and FSkeletalMeshStreamIn_DDC::DoLoadNewLODsFromDDC().
DoFinishUpdate()
void FSkeletalMeshStreamIn::DoFinishUpdate (const FContext & Context) protected
Apply the new buffers (if not cancelled) and finish the update process.
When cancelled, the intermediate buffers simply gets discarded.
Definition at line 186 of file SkeletalMeshUpdate.cpp.
References check, FRenderAssetUpdate::CurrentFirstLODIdx, ensure, FSkeletalMeshLODRenderData::GetNumVertices(), GSkelMeshMaxNumResourceUpdatesPerBatch, IsInRenderingThread(), IsRayTracingAllowed(), IsRayTracingEnabled(), FRenderAssetUpdate::MarkAsSuccessfullyFinished(), Normal, FRenderAssetUpdate::PendingFirstLODIdx, FRenderAssetUpdate::ResourceState, StreamingRHICmdList, and FRenderAssetUpdate::TT_Render.
Referenced by FSkeletalMeshStreamIn_DDC::DoCreateBuffers(), and FSkeletalMeshStreamIn_IO::DoCreateBuffers().
Field Documentation
CreateResourcesThread
const EThreadType FSkeletalMeshStreamIn::CreateResourcesThread protected
The thread to use for recording the above command list.
Definition at line 141 of file SkeletalMeshUpdate.h.
Referenced by FSkeletalMeshStreamIn(), FSkeletalMeshStreamIn_DDC::FSkeletalMeshStreamIn_DDC(), FSkeletalMeshStreamIn_IO::FSkeletalMeshStreamIn_IO(), FSkeletalMeshStreamIn_DDC::DoLoadNewLODsFromDDC(), and FSkeletalMeshStreamIn_IO::DoSerializeLODData().
IntermediateBuffersArray
FIntermediateBuffers FSkeletalMeshStreamIn::IntermediateBuffersArray[MAX_MESH_LOD_COUNT] protected
The intermediate buffers created in the update process.
Definition at line 131 of file SkeletalMeshUpdate.h.
Referenced by CreateBuffers().
StreamingRHICmdList
FRHICommandList* FSkeletalMeshStreamIn::StreamingRHICmdList = nullptr protected
RHI command list used for creating buffers and replacing the streaming placeholders.
Submitted in DoFinishUpdate
Definition at line 138 of file SkeletalMeshUpdate.h.
Referenced by ~FSkeletalMeshStreamIn(), CreateBuffers(), DoCancel(), and DoFinishUpdate().
The documentation for this class was generated from the following files:
SkeletalMeshUpdate.h
SkeletalMeshUpdate.cpp