Unreal Engine 5.6 C++ API: FTopLevelAssetPath Struct Reference
FTopLevelAssetPath Struct Reference
#include "TopLevelAssetPath.h"
Public Member Functions
FTopLevelAssetPath ()
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type>
FTopLevelAssetPath (const CharType *Path)
FTopLevelAssetPath (const FString &Path)
Construct from string / string view / raw string of a supported character type.
FTopLevelAssetPath (const UObject *InObject)
Construct from an existing object.
FTopLevelAssetPath (FName InPackageName, FName InAssetName)
Construct directly from components.
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type>
FTopLevelAssetPath (TStringView< CharType > Path)
FTopLevelAssetPath (TYPE_OF_NULLPTR)
void AppendString (FString &OutString) const
Append the full asset path (e.g.
void AppendString (FUtf8StringBuilderBase &Builder) const
void AppendString (FWideStringBuilderBase &Builder) const
Append the full asset path (e.g.
int32 Compare (const FTopLevelAssetPath &Other) const
Lexically compares two paths.
int32 CompareFast (const FTopLevelAssetPath &Other) const
Compares two paths in a fast non-lexical order that is only valid for process lifetime.
bool ExportTextItem (FString &ValueStr, FTopLevelAssetPath const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
FName GetAssetName () const
Return the asset name part e.g.
FName GetPackageName () const
Return the package name part e.g.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText, FArchive *InSerializingArchive=nullptr)
bool IsNull () const
Checks to see if this is initialized to null.
bool IsValid () const
Check if this could possibly refer to a real object.
bool operator!= (FTopLevelAssetPath const &Other) const
Compares two paths for non-case-sensitive inequality.
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type>
FTopLevelAssetPath & operator= (const CharType *Path)
FTopLevelAssetPath & operator= (const FString &Path)
Assign from the same types we can construct from.
template<typename CharType>
FTopLevelAssetPath & operator= (TStringView< CharType > Path)
FTopLevelAssetPath & operator= (TYPE_OF_NULLPTR)
bool operator== (FTopLevelAssetPath const &Other) const
Compares two paths for non-case-sensitive equality.
bool RemapPackage (FName OldPackageName, FName NewPackageName)
Remap the package to handle renames.
void Reset ()
Resets reference to point to null.
bool SerializeFromMismatchedTag (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot)
FString ToString () const
Return the full asset path (e.g.
void ToString (FString &OutString) const
Copy the full asset path (e.g.
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type>
bool TrySetPath (const CharType *Path)
bool TrySetPath (const FString &Path)
bool TrySetPath (const UObject *InObject)
Sets asset path to path of existing object.
bool TrySetPath (FAnsiStringView Path)
bool TrySetPath (FName InPackageName, FName InAssetName)
Sets asset path of this reference based on components.
bool TrySetPath (FUtf8StringView Path)
bool TrySetPath (FWideStringView Path)
Sets asset path of this reference based on a string path.
UE_DEPRECATED (5.0, "FNames containing full asset paths have been replaced by FTopLevelAssetPath/FSoftLevelObjectPath." "This function is only for temporary use interfacing with APIs that still produce an FName." "Those APIS should be updated to use FTopLevelAssetPath or FSoftLevelObjectPath.") explicit FTopLevelAssetPath(FName InPath)
UE_DEPRECATED (5.1, "FNames containing full asset paths have been replaced by FTopLevelAssetPath/FSoftLevelObjectPath." "This function is only for temporary use interfacing with APIs that still expect an FName." "Those APIS should be updated to use FTopLevelAssetPath or FSoftLevelObjectPath.") FName ToFName() const
void WriteCompactBinary (FCbWriter &Writer) const
Private Attributes
FName AssetName
Name of the asset within the package e.g.
FName PackageName
Name of the package containing the asset e.g.
Friends
uint32 GetTypeHash (FTopLevelAssetPath const &This)
bool LoadFromCompactBinary (FCbFieldView Field, FTopLevelAssetPath &OutPath)
FArchive & operator<< (FArchive &Ar, FTopLevelAssetPath &Path)
Serializes the internal path.
FCbWriter & operator<< (FCbWriter &Writer, const FTopLevelAssetPath &Path)
void operator<< (FStructuredArchive::FSlot Slot, FTopLevelAssetPath &Path)
Serializes the internal path.
void SerializeForLog (FCbWriter &Writer, const FTopLevelAssetPath &Value)
Detailed Description
Definition at line 34 of file TopLevelAssetPath.h.
Constructor & Destructor Documentation
FTopLevelAssetPath() [1/7]
FTopLevelAssetPath::FTopLevelAssetPath () inline
Definition at line 36 of file TopLevelAssetPath.h.
Referenced by Compare(), CompareFast(), ExportTextItem(), GetTypeHash, LoadFromCompactBinary, operator!=(), operator<<, operator<<, operator<<, operator=(), operator=(), operator=(), operator=(), operator==(), SerializeForLog, and UE_DEPRECATED().
FTopLevelAssetPath() [2/7]
FTopLevelAssetPath::FTopLevelAssetPath (TYPE_OF_NULLPTR) inline
Definition at line 37 of file TopLevelAssetPath.h.
FTopLevelAssetPath() [3/7]
FTopLevelAssetPath::FTopLevelAssetPath (FName InPackageName, FName InAssetName) inline
Construct directly from components.
Definition at line 40 of file TopLevelAssetPath.h.
References TrySetPath().
FTopLevelAssetPath() [4/7]
FTopLevelAssetPath::FTopLevelAssetPath (const FString & Path) inline explicit
Construct from string / string view / raw string of a supported character type.
Definition at line 54 of file TopLevelAssetPath.h.
References Path, and TrySetPath().
FTopLevelAssetPath() [5/7]
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type> FTopLevelAssetPath::FTopLevelAssetPath (TStringView< CharType > Path) inline explicit
Definition at line 56 of file TopLevelAssetPath.h.
References Path, and TrySetPath().
FTopLevelAssetPath() [6/7]
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type> FTopLevelAssetPath::FTopLevelAssetPath (const CharType * Path) inline explicit
Definition at line 58 of file TopLevelAssetPath.h.
References Path, and TrySetPath().
FTopLevelAssetPath() [7/7]
FTopLevelAssetPath::FTopLevelAssetPath (const UObject * InObject) inline explicit
Construct from an existing object.
Creates an empty path if the object is not a package or the direct inner of a package.
Definition at line 61 of file TopLevelAssetPath.h.
References TrySetPath().
Member Function Documentation
AppendString() [1/3]
void FTopLevelAssetPath::AppendString (FString & OutString) const
Append the full asset path (e.g.
'/Path/To/Package.AssetName') to the string.
AppendString() [2/3]
void FTopLevelAssetPath::AppendString (FUtf8StringBuilderBase & Builder) const
AppendString() [3/3]
void FTopLevelAssetPath::AppendString (FWideStringBuilderBase & Builder) const
Append the full asset path (e.g.
'/Path/To/Package.AssetName') to the string builder.
Compare()
int32 FTopLevelAssetPath::Compare (const FTopLevelAssetPath & Other) const inline
Lexically compares two paths.
Definition at line 152 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), AssetName, Other, and PackageName.
CompareFast()
int32 FTopLevelAssetPath::CompareFast (const FTopLevelAssetPath & Other) const inline
Compares two paths in a fast non-lexical order that is only valid for process lifetime.
Definition at line 162 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), AssetName, Other, and PackageName.
ExportTextItem()
bool FTopLevelAssetPath::ExportTextItem (FString & ValueStr, FTopLevelAssetPath const & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
References FTopLevelAssetPath(), and Parent.
GetAssetName()
FName FTopLevelAssetPath::GetAssetName () const inline
Return the asset name part e.g.
AssetName as an FName.
Definition at line 90 of file TopLevelAssetPath.h.
References AssetName.
Referenced by FSoftObjectPath::GetAssetFName(), and FSoftObjectPath::GetAssetName().
GetPackageName()
FName FTopLevelAssetPath::GetPackageName () const inline
Return the package name part e.g.
/Path/To/Package as an FName.
Definition at line 87 of file TopLevelAssetPath.h.
References PackageName.
Referenced by FSoftObjectPath::GetLongPackageFName(), and FSoftObjectPath::GetLongPackageName().
ImportTextItem()
bool FTopLevelAssetPath::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText, FArchive * InSerializingArchive = nullptr)
References Buffer, and Parent.
IsNull()
bool FTopLevelAssetPath::IsNull () const inline
Checks to see if this is initialized to null.
Definition at line 116 of file TopLevelAssetPath.h.
References PackageName.
IsValid()
bool FTopLevelAssetPath::IsValid () const inline
Check if this could possibly refer to a real object.
Definition at line 110 of file TopLevelAssetPath.h.
References PackageName.
operator!=()
bool FTopLevelAssetPath::operator!= (FTopLevelAssetPath const & Other) const inline
Compares two paths for non-case-sensitive inequality.
Definition at line 133 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), and Other.
operator=() [1/4]
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type> FTopLevelAssetPath & FTopLevelAssetPath::operator= (const CharType * Path) inline
Definition at line 68 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), Path, and TrySetPath().
operator=() [2/4]
FTopLevelAssetPath & FTopLevelAssetPath::operator= (const FString & Path) inline
Assign from the same types we can construct from.
Definition at line 64 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), Path, and TrySetPath().
operator=() [3/4]
template<typename CharType> FTopLevelAssetPath & FTopLevelAssetPath::operator= (TStringView< CharType > Path) inline
Definition at line 66 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), Path, and TrySetPath().
operator=() [4/4]
FTopLevelAssetPath & FTopLevelAssetPath::operator= (TYPE_OF_NULLPTR) inline
Definition at line 69 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), and Reset().
operator==()
bool FTopLevelAssetPath::operator== (FTopLevelAssetPath const & Other) const inline
Compares two paths for non-case-sensitive equality.
Definition at line 127 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), AssetName, Other, and PackageName.
RemapPackage()
bool FTopLevelAssetPath::RemapPackage (FName OldPackageName, FName NewPackageName)
Remap the package to handle renames.
Reset()
void FTopLevelAssetPath::Reset () inline
Resets reference to point to null.
Definition at line 122 of file TopLevelAssetPath.h.
References AssetName, FName, and PackageName.
Referenced by operator=().
SerializeFromMismatchedTag()
bool FTopLevelAssetPath::SerializeFromMismatchedTag (const FPropertyTag & Tag, FStructuredArchive::FSlot Slot)
ToString() [1/2]
FString FTopLevelAssetPath::ToString () const
Return the full asset path (e.g.
'/Path/To/Package.AssetName') as a string.
Referenced by UE_DEPRECATED().
ToString() [2/2]
void FTopLevelAssetPath::ToString (FString & OutString) const
Copy the full asset path (e.g.
'/Path/To/Package.AssetName') into the provided string.
TrySetPath() [1/7]
template<typename CharType, typename = typename std::enable_if<TIsCharType<CharType>::Value>::type> bool FTopLevelAssetPath::TrySetPath (const CharType * Path) inline
Definition at line 80 of file TopLevelAssetPath.h.
References Path, and TrySetPath().
Referenced by TrySetPath().
TrySetPath() [2/7]
bool FTopLevelAssetPath::TrySetPath (const FString & Path) inline
Definition at line 81 of file TopLevelAssetPath.h.
References Path, and TrySetPath().
Referenced by TrySetPath().
TrySetPath() [3/7]
bool FTopLevelAssetPath::TrySetPath (const UObject * InObject)
Sets asset path to path of existing object.
Sets an empty path and returns false if the object is not a package or the direct inner of a package.
TrySetPath() [4/7]
bool FTopLevelAssetPath::TrySetPath (FAnsiStringView Path)
References Path.
TrySetPath() [5/7]
bool FTopLevelAssetPath::TrySetPath (FName InPackageName, FName InAssetName)
Sets asset path of this reference based on components.
Referenced by FTopLevelAssetPath(), FTopLevelAssetPath(), FTopLevelAssetPath(), FTopLevelAssetPath(), FTopLevelAssetPath(), operator=(), operator=(), operator=(), and UE_DEPRECATED().
TrySetPath() [6/7]
bool FTopLevelAssetPath::TrySetPath (FUtf8StringView Path)
References Path.
TrySetPath() [7/7]
bool FTopLevelAssetPath::TrySetPath (FWideStringView Path)
Sets asset path of this reference based on a string path.
Resets this object and returns false if the string is empty or does not represent a top level asset path.
References Path.
UE_DEPRECATED() [1/2]
FTopLevelAssetPath::UE_DEPRECATED (5. 0, "FNames containing full asset paths have been replaced by FTopLevelAssetPath/FSoftLevelObjectPath." "This function is only for temporary use interfacing with APIs that still produce an FName." "Those APIS should be updated to use FTopLevelAssetPath or FSoftLevelObjectPath.") inline
Definition at line 45 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), and TrySetPath().
UE_DEPRECATED() [2/2]
FTopLevelAssetPath::UE_DEPRECATED (5. 1, "FNames containing full asset paths have been replaced by FTopLevelAssetPath/FSoftLevelObjectPath." "This function is only for temporary use interfacing with APIs that still expect an FName." "Those APIS should be updated to use FTopLevelAssetPath or FSoftLevelObjectPath.") const inline
Definition at line 104 of file TopLevelAssetPath.h.
References ToString().
WriteCompactBinary()
void FTopLevelAssetPath::WriteCompactBinary (FCbWriter & Writer) const
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FTopLevelAssetPath const & This) friend
Definition at line 171 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), GetTypeHash, and HashCombineFast().
Referenced by GetTypeHash.
LoadFromCompactBinary
bool LoadFromCompactBinary (FCbFieldView Field, FTopLevelAssetPath & OutPath) friend
References FTopLevelAssetPath().
operator<< [1/3]
FArchive & operator<< (FArchive & Ar, FTopLevelAssetPath & Path) friend
Serializes the internal path.
Unlike FSoftObjectPath, does not handle any PIE or redirector fixups.
Definition at line 139 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), Ar, and Path.
operator<< [2/3]
FCbWriter & operator<< (FCbWriter & Writer, const FTopLevelAssetPath & Path) friend
Definition at line 182 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), and Path.
operator<< [3/3]
void operator<< (FStructuredArchive::FSlot Slot, FTopLevelAssetPath & Path) friend
Serializes the internal path.
Unlike FSoftObjectPath, does not handle any PIE or redirector fixups.
Definition at line 145 of file TopLevelAssetPath.h.
References FTopLevelAssetPath(), FStructuredArchiveSlot::EnterRecord(), Path, Record, SA_VALUE, and TEXT.
SerializeForLog
void SerializeForLog (FCbWriter & Writer, const FTopLevelAssetPath & Value) friend
References FTopLevelAssetPath(), and Value.
Field Documentation
AssetName
FName FTopLevelAssetPath::AssetName private
Name of the asset within the package e.g.
'AssetName'
Definition at line 192 of file TopLevelAssetPath.h.
Referenced by Compare(), CompareFast(), GetAssetName(), operator==(), and Reset().
PackageName
FName FTopLevelAssetPath::PackageName private
Name of the package containing the asset e.g.
/Path/To/Package
Definition at line 190 of file TopLevelAssetPath.h.
Referenced by Compare(), CompareFast(), GetPackageName(), IsNull(), IsValid(), operator==(), and Reset().
The documentation for this struct was generated from the following file:
TopLevelAssetPath.h