Unreal Engine 5.6 C++ API: SGraphNodePromotableOperator Class Reference
SGraphNodePromotableOperator Class Reference
A custom slate node for the promotable operator (K2Node_PromotableOperator) These nodes include common math operations like Add, Subtract, Multiply, etc.
#include "SGraphNodePromotableOperator.h"
Public Member Functions
virtual void CreatePinWidgets () override
SLATE_BEGIN_ARGS (SGraphNodePromotableOperator)
SLATE_END_ARGS () void Construct(const FArguments &InArgs
Data Fields
UK2Node_PromotableOperator * InNode
Protected Member Functions
void LoadCachedIcons ()
Protected Attributes
const FSlateBrush * CachedInnerIcon
const FSlateBrush * CachedOuterIcon
Detailed Description
A custom slate node for the promotable operator (K2Node_PromotableOperator) These nodes include common math operations like Add, Subtract, Multiply, etc.
This custom node will provide a neat little secondary icon to visually show that promotable operator pins can be converted to other types.
Definition at line 20 of file SGraphNodePromotableOperator.h.
Member Function Documentation
CreatePinWidgets()
virtual void SGraphNodePromotableOperator::CreatePinWidgets () override virtual
References CreatePinWidgets().
Referenced by CreatePinWidgets().
LoadCachedIcons()
void SGraphNodePromotableOperator::LoadCachedIcons () protected
References LoadCachedIcons().
Referenced by LoadCachedIcons().
SLATE_BEGIN_ARGS()
SGraphNodePromotableOperator::SLATE_BEGIN_ARGS (SGraphNodePromotableOperator) inline
Definition at line 24 of file SGraphNodePromotableOperator.h.
SLATE_END_ARGS()
SGraphNodePromotableOperator::SLATE_END_ARGS () const &
Field Documentation
CachedInnerIcon
const FSlateBrush* SGraphNodePromotableOperator::CachedInnerIcon protected
Definition at line 38 of file SGraphNodePromotableOperator.h.
CachedOuterIcon
const FSlateBrush* SGraphNodePromotableOperator::CachedOuterIcon protected
Definition at line 37 of file SGraphNodePromotableOperator.h.
InNode
UK2Node_PromotableOperator* SGraphNodePromotableOperator::InNode
Definition at line 27 of file SGraphNodePromotableOperator.h.
The documentation for this class was generated from the following file:
SGraphNodePromotableOperator.h