Unreal Engine 5.6 C++ API: FDataDrivenPlatformInfoRegistry Struct Reference
FDataDrivenPlatformInfoRegistry Struct Reference
#include "DataDrivenPlatformInfoRegistry.h"
Public Types
enum class EPlatformNameType { UBT , Ini , TargetPlatform }
Checks for the existence of compiled modules for a given (usually another, target, platform) Since there are different types of platform names, it is necessary pass in the type of name.
Public Member Functions
UE_DEPRECATED (5.1, "Use GetSoprtedPlatformNames that takes a PlatformType parameter") static const TArray< FName > GetSortedPlatformNames()
UE_DEPRECATED (5.1, "Use GetSortedPlatformInfos that takes a PlatformType parameter") static const TArray< const FDataDrivenPlatformInfo * > &GetSortedPlatformInfos()
Static Public Member Functions
static void ClearDeviceStatus (FName PlatformName)
Wipes out cached device status for all devices in a platform (or all platforms if PlatformName is empty)
static FDataDrivenPlatformInfo & DeviceIdToInfo (FString DeviceId, FString *OutDeviceName=nullptr)
static const TMap< FName, FDataDrivenPlatformInfo > & GetAllPlatformInfos ()
Get the global set of data driven platform information.
static const TArray< struct FPreviewPlatformMenuItem > & GetAllPreviewPlatformMenuItems ()
Retrieve the full list of all known preview platforms from all DDPIs.
static const TArray< FName > & GetConfidentialPlatforms ()
Gets a list of all known confidential platforms (note these are just the platforms you have access to, so, for example PS4 won't be returned if you are not a PS4 licensee)
static int32 GetNumDataDrivenIniFiles ()
Returns the number of discovered ini files that can be loaded with LoadDataDrivenIniFile.
static const TArray< FString > & GetPlatformDirectoryNames (bool bCheckValid)
Gets a set of platform names based on GetAllPlatformInfos, their AdditionalRestrictedFolders This is not necessarily the same as IniParents, although there is overlap - IniParents come from chaining DDPIs, so those will be in GetAllPlatformInfos already to be checked.
static const FDataDrivenPlatformInfo & GetPlatformInfo (const char *PlatformName)
static const FDataDrivenPlatformInfo & GetPlatformInfo (const FString &PlatformName)
Get the data driven platform info for a given platform.
static const FDataDrivenPlatformInfo & GetPlatformInfo (FName PlatformName)
static const TArray< const FDataDrivenPlatformInfo * > & GetSortedPlatformInfos (EPlatformInfoType PlatformType)
static const TArray< FName > GetSortedPlatformNames (EPlatformInfoType PlatformType)
Get sorted platorm infos or names.
static const TArray< FString > & GetValidPlatformDirectoryNames ()
Gets a set of platform names based on GetAllPlatformInfos, their AdditionalRestrictedFolders, and possibly filtered based on what editor has support compiled for This is not necessarily the same as IniParents, although there is overlap - IniParents come from chaining DDPIs, so those will be in GetAllPlatformInfos already to be checked.
static bool HasCompiledSupportForPlatform (FName PlatformName, EPlatformNameType PlatformNameType)
static bool IsPlatformHiddenFromUI (FName PlatformName)
Option to hide a platform from the user interface at runtime.
static bool LoadDataDrivenIniFile (int32 Index, FConfigFile &IniFile, FString &PlatformName)
Load the given ini file, and.
static void SetPlatformHiddenFromUI (FName PlatformName)
Static Private Member Functions
static FDataDrivenPlatformInfo & GetMutablePlatformInfo (FName PlatformName)
static TMap< FName, FDataDrivenPlatformInfo > & GetMutablePlatformInfos ()
Friends
class FTurkeySupportModule
Get a modifiable DDPI object, for Turnkey to update it's info.
Detailed Description
Definition at line 266 of file DataDrivenPlatformInfoRegistry.h.
Member Enumeration Documentation
EPlatformNameType
enum class FDataDrivenPlatformInfoRegistry::EPlatformNameType strong
Checks for the existence of compiled modules for a given (usually another, target, platform) Since there are different types of platform names, it is necessary pass in the type of name.
Enumerator
UBT
Ini
TargetPlatform
Definition at line 336 of file DataDrivenPlatformInfoRegistry.h.
Member Function Documentation
ClearDeviceStatus()
void FDataDrivenPlatformInfoRegistry::ClearDeviceStatus (FName PlatformName) static
Wipes out cached device status for all devices in a platform (or all platforms if PlatformName is empty)
DeviceIdToInfo()
FDataDrivenPlatformInfo & FDataDrivenPlatformInfoRegistry::DeviceIdToInfo (FString DeviceId, FString * OutDeviceName = nullptr) static
GetAllPlatformInfos()
const TMap< FName, FDataDrivenPlatformInfo > & FDataDrivenPlatformInfoRegistry::GetAllPlatformInfos () static
Get the global set of data driven platform information.
GetAllPreviewPlatformMenuItems()
const TArray< struct FPreviewPlatformMenuItem > & FDataDrivenPlatformInfoRegistry::GetAllPreviewPlatformMenuItems () static
Retrieve the full list of all known preview platforms from all DDPIs.
GetConfidentialPlatforms()
const TArray< FName > & FDataDrivenPlatformInfoRegistry::GetConfidentialPlatforms () static
Gets a list of all known confidential platforms (note these are just the platforms you have access to, so, for example PS4 won't be returned if you are not a PS4 licensee)
GetMutablePlatformInfo()
FDataDrivenPlatformInfo & FDataDrivenPlatformInfoRegistry::GetMutablePlatformInfo (FName PlatformName) static private
GetMutablePlatformInfos()
TMap< FName, FDataDrivenPlatformInfo > & FDataDrivenPlatformInfoRegistry::GetMutablePlatformInfos () static private
GetNumDataDrivenIniFiles()
int32 FDataDrivenPlatformInfoRegistry::GetNumDataDrivenIniFiles () static
Returns the number of discovered ini files that can be loaded with LoadDataDrivenIniFile.
GetPlatformDirectoryNames()
const TArray< FString > & FDataDrivenPlatformInfoRegistry::GetPlatformDirectoryNames (bool bCheckValid) static
Gets a set of platform names based on GetAllPlatformInfos, their AdditionalRestrictedFolders This is not necessarily the same as IniParents, although there is overlap - IniParents come from chaining DDPIs, so those will be in GetAllPlatformInfos already to be checked.
Parameters
bCheckValid If true, the result is filtered based on what editor has support compiled for
Referenced by GetValidPlatformDirectoryNames().
GetPlatformInfo() [1/3]
const FDataDrivenPlatformInfo & FDataDrivenPlatformInfoRegistry::GetPlatformInfo (const char * PlatformName) static
GetPlatformInfo() [2/3]
const FDataDrivenPlatformInfo & FDataDrivenPlatformInfoRegistry::GetPlatformInfo (const FString & PlatformName) static
Get the data driven platform info for a given platform.
If the platform doesn't have any on disk, this will return a default constructed FConfigDataDrivenPlatformInfo
Referenced by TPerPlatformProperty< _StructType, _ValueType, _BasePropertyName >::GetValueForPlatform().
GetPlatformInfo() [3/3]
const FDataDrivenPlatformInfo & FDataDrivenPlatformInfoRegistry::GetPlatformInfo (FName PlatformName) static
GetSortedPlatformInfos()
const TArray< const FDataDrivenPlatformInfo * > & FDataDrivenPlatformInfoRegistry::GetSortedPlatformInfos (EPlatformInfoType PlatformType) static
Referenced by UE_DEPRECATED().
GetSortedPlatformNames()
const TArray< FName > FDataDrivenPlatformInfoRegistry::GetSortedPlatformNames (EPlatformInfoType PlatformType) static
Get sorted platorm infos or names.
PlatformType is used to choose between true platforms and platform groups (or other fake platforms)
Referenced by UE_DEPRECATED().
GetValidPlatformDirectoryNames()
const TArray< FString > & FDataDrivenPlatformInfoRegistry::GetValidPlatformDirectoryNames () inline static
Gets a set of platform names based on GetAllPlatformInfos, their AdditionalRestrictedFolders, and possibly filtered based on what editor has support compiled for This is not necessarily the same as IniParents, although there is overlap - IniParents come from chaining DDPIs, so those will be in GetAllPlatformInfos already to be checked.
Definition at line 286 of file DataDrivenPlatformInfoRegistry.h.
References GetPlatformDirectoryNames().
HasCompiledSupportForPlatform()
bool FDataDrivenPlatformInfoRegistry::HasCompiledSupportForPlatform (FName PlatformName, EPlatformNameType PlatformNameType) static
IsPlatformHiddenFromUI()
bool FDataDrivenPlatformInfoRegistry::IsPlatformHiddenFromUI (FName PlatformName) static
Option to hide a platform from the user interface at runtime.
LoadDataDrivenIniFile()
bool FDataDrivenPlatformInfoRegistry::LoadDataDrivenIniFile (int32 Index, FConfigFile & IniFile, FString & PlatformName) static
Load the given ini file, and.
SetPlatformHiddenFromUI()
void FDataDrivenPlatformInfoRegistry::SetPlatformHiddenFromUI (FName PlatformName) static
UE_DEPRECATED() [1/2]
FDataDrivenPlatformInfoRegistry::UE_DEPRECATED (5. 1, "Use GetSoprtedPlatformNames that takes a PlatformType parameter") const inline
Definition at line 303 of file DataDrivenPlatformInfoRegistry.h.
References AllPlatformInfos, and GetSortedPlatformNames().
UE_DEPRECATED() [2/2]
FDataDrivenPlatformInfoRegistry::UE_DEPRECATED (5. 1, "Use GetSortedPlatformInfos that takes a PlatformType parameter") const & inline
Definition at line 308 of file DataDrivenPlatformInfoRegistry.h.
References AllPlatformInfos, and GetSortedPlatformInfos().
Friends And Related Symbol Documentation
FTurkeySupportModule
friend class FTurkeySupportModule friend
Get a modifiable DDPI object, for Turnkey to update it's info.
Definition at line 367 of file DataDrivenPlatformInfoRegistry.h.
References FTurkeySupportModule.
Referenced by FTurkeySupportModule.
The documentation for this struct was generated from the following file:
DataDrivenPlatformInfoRegistry.h