Unreal Engine 5.6 C++ API: FRigVMUserDefinedTypeResolver Struct Reference
FRigVMUserDefinedTypeResolver Struct Reference
#include "RigVMTypeUtils.h"
Public Member Functions
FRigVMUserDefinedTypeResolver ()=default
FRigVMUserDefinedTypeResolver (const TFunction< UObject *(const FString &)> &InResolver)
FRigVMUserDefinedTypeResolver (TMap< FString, FSoftObjectPath > &&InObjectMap)
UObject * GetTypeObjectByName (const FString &InTypeName) const
bool IsValid () const
Private Attributes
TMap< FString, FSoftObjectPath > ObjectMap
TFunction< UObject *(const FString &)> Resolver
Detailed Description
Definition at line 20 of file RigVMTypeUtils.h.
Constructor & Destructor Documentation
FRigVMUserDefinedTypeResolver() [1/3]
FRigVMUserDefinedTypeResolver::FRigVMUserDefinedTypeResolver () default
FRigVMUserDefinedTypeResolver() [2/3]
FRigVMUserDefinedTypeResolver::FRigVMUserDefinedTypeResolver (const TFunction< UObject *(const FString &)> & InResolver) inline explicit
Definition at line 23 of file RigVMTypeUtils.h.
References Resolver.
FRigVMUserDefinedTypeResolver() [3/3]
FRigVMUserDefinedTypeResolver::FRigVMUserDefinedTypeResolver (TMap< FString, FSoftObjectPath > && InObjectMap) inline explicit
Definition at line 24 of file RigVMTypeUtils.h.
References ObjectMap.
Member Function Documentation
GetTypeObjectByName()
UObject * FRigVMUserDefinedTypeResolver::GetTypeObjectByName (const FString & InTypeName) const inline
Definition at line 26 of file RigVMTypeUtils.h.
References ObjectMap, and Resolver.
IsValid()
bool FRigVMUserDefinedTypeResolver::IsValid () const inline
Definition at line 40 of file RigVMTypeUtils.h.
References ObjectMap, and Resolver.
Field Documentation
ObjectMap
TMap<FString, FSoftObjectPath> FRigVMUserDefinedTypeResolver::ObjectMap private
Definition at line 47 of file RigVMTypeUtils.h.
Referenced by FRigVMUserDefinedTypeResolver(), GetTypeObjectByName(), and IsValid().
Resolver
TFunction<UObject*(const FString&)> FRigVMUserDefinedTypeResolver::Resolver private
Definition at line 46 of file RigVMTypeUtils.h.
Referenced by FRigVMUserDefinedTypeResolver(), GetTypeObjectByName(), and IsValid().
The documentation for this struct was generated from the following file:
RigVMTypeUtils.h