Unreal Engine 5.6 C++ API: UE::MovieScene::FInstanceRegistry Struct Reference
UE::MovieScene::FInstanceRegistry Struct Reference
Core concept that is required by all entities and systems - should be located on the core system manager itself.
#include "MovieSceneInstanceRegistry.h"
Public Member Functions
FInstanceRegistry (const FInstanceRegistry &)=delete
MOVIESCENE_API FInstanceRegistry (UMovieSceneEntitySystemLinker *InLinker)
MOVIESCENE_API ~FInstanceRegistry ()
MOVIESCENE_API FRootInstanceHandle AllocateRootInstance (UMovieSceneSequence &InRootSequence, UObject *InPlaybackContext=nullptr, UMovieSceneCompiledDataManager *InCompiledDataManager=nullptr)
MOVIESCENE_API FInstanceHandle AllocateSubInstance (FMovieSceneSequenceID SequenceID, FRootInstanceHandle RootInstance, FInstanceHandle ParentInstanceHandle)
MOVIESCENE_API void CleanupLinkerEntities (const TSet< FMovieSceneEntityID > &LinkerEntities)
MOVIESCENE_API void DestroyInstance (FInstanceHandle InstanceHandle)
MOVIESCENE_API FInstanceHandle FindRelatedInstanceHandle (FInstanceHandle InstanceHandle, FMovieSceneSequenceID SequenceID) const
Finds a (sub)sequence with the given ID somewhere in the hierarchy of the given reference instance.
const FMovieSceneContext & GetContext (FInstanceHandle InstanceHandle) const
const FSequenceInstance & GetInstance (FInstanceHandle InstanceHandle) const
UMovieSceneEntitySystemLinker * GetLinker () const
const TSparseArray< FSequenceInstance > & GetSparseInstances () const
bool HasInvalidatedBindings () const
void InvalidateObjectBinding (const FGuid &ObjectBindingID, FInstanceHandle InstanceHandle)
bool IsBindingInvalidated (const FGuid &ObjectBindingID, FInstanceHandle InstanceHandle) const
bool IsHandleValid (FInstanceHandle InstanceHandle) const
FSequenceInstance & MutateInstance (FInstanceHandle InstanceHandle)
void operator= (const FInstanceRegistry &)=delete
void PostInstantation ()
void TagGarbage ()
Private Attributes
TSparseArray< FSequenceInstance > Instances
Authoritate array of unique instance combinations.
uint16 InstanceSerialNumber
TSet< TTuple< FGuid, FInstanceHandle > > InvalidatedObjectBindings
Set of invalidated object bindings by their instance handle.
UMovieSceneEntitySystemLinker * Linker
Detailed Description
Core concept that is required by all entities and systems - should be located on the core system manager itself.
Definition at line 38 of file MovieSceneInstanceRegistry.h.
Constructor & Destructor Documentation
FInstanceRegistry() [1/2]
MOVIESCENE_API UE::MovieScene::FInstanceRegistry::FInstanceRegistry (UMovieSceneEntitySystemLinker * InLinker)
Referenced by FInstanceRegistry(), and operator=().
~FInstanceRegistry()
MOVIESCENE_API UE::MovieScene::FInstanceRegistry::~FInstanceRegistry ()
FInstanceRegistry() [2/2]
UE::MovieScene::FInstanceRegistry::FInstanceRegistry (const FInstanceRegistry &) delete
References FInstanceRegistry().
Member Function Documentation
AllocateRootInstance()
MOVIESCENE_API FRootInstanceHandle UE::MovieScene::FInstanceRegistry::AllocateRootInstance (UMovieSceneSequence & InRootSequence, UObject * InPlaybackContext = nullptr, UMovieSceneCompiledDataManager * InCompiledDataManager = nullptr)
AllocateSubInstance()
MOVIESCENE_API FInstanceHandle UE::MovieScene::FInstanceRegistry::AllocateSubInstance (FMovieSceneSequenceID SequenceID, FRootInstanceHandle RootInstance, FInstanceHandle ParentInstanceHandle)
CleanupLinkerEntities()
MOVIESCENE_API void UE::MovieScene::FInstanceRegistry::CleanupLinkerEntities (const TSet< FMovieSceneEntityID > & LinkerEntities)
DestroyInstance()
MOVIESCENE_API void UE::MovieScene::FInstanceRegistry::DestroyInstance (FInstanceHandle InstanceHandle)
FindRelatedInstanceHandle()
MOVIESCENE_API FInstanceHandle UE::MovieScene::FInstanceRegistry::FindRelatedInstanceHandle (FInstanceHandle InstanceHandle, FMovieSceneSequenceID SequenceID) const
Finds a (sub)sequence with the given ID somewhere in the hierarchy of the given reference instance.
This method will look up the hierarchy root from the given instance handle, and then look for the appropriate sub-instance with the given sequence ID.
Parameters
InstanceHandle The reference instance handle used to locate the relevant sequence hierarchy to explore. Does not have to be a root instance.
SequenceID An absolute (accumulated) sequence ID to look for in the hierarchy.
GetContext()
const FMovieSceneContext & UE::MovieScene::FInstanceRegistry::GetContext (FInstanceHandle InstanceHandle) const inline
Definition at line 85 of file MovieSceneInstanceRegistry.h.
References UE::MovieScene::FSequenceInstance::GetContext(), and GetInstance().
GetInstance()
const FSequenceInstance & UE::MovieScene::FInstanceRegistry::GetInstance (FInstanceHandle InstanceHandle) const inline
Definition at line 62 of file MovieSceneInstanceRegistry.h.
References checkfSlow, UE::MovieScene::FInstanceHandle::InstanceID, Instances, IsHandleValid(), and TEXT.
Referenced by GetContext().
GetLinker()
UMovieSceneEntitySystemLinker * UE::MovieScene::FInstanceRegistry::GetLinker () const inline
Definition at line 52 of file MovieSceneInstanceRegistry.h.
References Linker.
GetSparseInstances()
const TSparseArray< FSequenceInstance > & UE::MovieScene::FInstanceRegistry::GetSparseInstances () const inline
Definition at line 47 of file MovieSceneInstanceRegistry.h.
References Instances.
HasInvalidatedBindings()
bool UE::MovieScene::FInstanceRegistry::HasInvalidatedBindings () const inline
Definition at line 113 of file MovieSceneInstanceRegistry.h.
References InvalidatedObjectBindings.
InvalidateObjectBinding()
void UE::MovieScene::FInstanceRegistry::InvalidateObjectBinding (const FGuid & ObjectBindingID, FInstanceHandle InstanceHandle) inline
Definition at line 102 of file MovieSceneInstanceRegistry.h.
References InvalidatedObjectBindings, and MakeTuple().
IsBindingInvalidated()
bool UE::MovieScene::FInstanceRegistry::IsBindingInvalidated (const FGuid & ObjectBindingID, FInstanceHandle InstanceHandle) const inline
Definition at line 107 of file MovieSceneInstanceRegistry.h.
References InvalidatedObjectBindings, and MakeTuple().
IsHandleValid()
bool UE::MovieScene::FInstanceRegistry::IsHandleValid (FInstanceHandle InstanceHandle) const inline
Definition at line 57 of file MovieSceneInstanceRegistry.h.
References UE::MovieScene::FInstanceHandle::InstanceID, Instances, and UE::MovieScene::FInstanceHandle::InstanceSerial.
Referenced by GetInstance(), and MutateInstance().
MutateInstance()
FSequenceInstance & UE::MovieScene::FInstanceRegistry::MutateInstance (FInstanceHandle InstanceHandle) inline
Definition at line 68 of file MovieSceneInstanceRegistry.h.
References checkfSlow, UE::MovieScene::FInstanceHandle::InstanceID, Instances, IsHandleValid(), and TEXT.
operator=()
void UE::MovieScene::FInstanceRegistry::operator= (const FInstanceRegistry &) delete
References FInstanceRegistry().
PostInstantation()
void UE::MovieScene::FInstanceRegistry::PostInstantation ()
TagGarbage()
void UE::MovieScene::FInstanceRegistry::TagGarbage ()
Field Documentation
Instances
TSparseArray<FSequenceInstance> UE::MovieScene::FInstanceRegistry::Instances private
Authoritate array of unique instance combinations.
Definition at line 127 of file MovieSceneInstanceRegistry.h.
Referenced by GetInstance(), GetSparseInstances(), IsHandleValid(), and MutateInstance().
InstanceSerialNumber
uint16 UE::MovieScene::FInstanceRegistry::InstanceSerialNumber private
Definition at line 128 of file MovieSceneInstanceRegistry.h.
InvalidatedObjectBindings
TSet<TTuple<FGuid, FInstanceHandle> > UE::MovieScene::FInstanceRegistry::InvalidatedObjectBindings private
Set of invalidated object bindings by their instance handle.
Empty guids indicate that all bindings for that instance handle are invalid
Definition at line 131 of file MovieSceneInstanceRegistry.h.
Referenced by HasInvalidatedBindings(), InvalidateObjectBinding(), and IsBindingInvalidated().
Linker
UMovieSceneEntitySystemLinker* UE::MovieScene::FInstanceRegistry::Linker private
Definition at line 124 of file MovieSceneInstanceRegistry.h.
Referenced by GetLinker().
The documentation for this struct was generated from the following file:
MovieSceneInstanceRegistry.h