Unreal Engine 5.6 C++ API: TextNamespaceUtil Namespace Reference
TextNamespaceUtil Namespace Reference
Enumerations
enum class ETextCopyMethod : uint8 { NewKey , PreserveKey , Verbatim }
enum class ETextEditAction : uint8 { Namespace , Key , SourceString }
Functions
FString BuildFullNamespace (const FString &InTextNamespace, const FString &InPackageNamespace, const bool bAlwaysApplyPackageNamespace=false)
Given a text and package namespace, build the full version that should be used by the localization system.
FText CopyTextToPackage (const FText &InText, const FString &InPackageNamespace, const ETextCopyMethod InCopyMethod=ETextCopyMethod::NewKey, const bool bAlwaysApplyPackageNamespace=false)
Make a copy of the given text that's valid to use with the given package namespace, optionally preserving its existing key.
FText CopyTextToPackage (const FText &InText, UObject *InObject, const ETextCopyMethod InCopyMethod=ETextCopyMethod::NewKey, const bool bAlwaysApplyPackageNamespace=false)
FText CopyTextToPackage (const FText &InText, UPackage *InPackage, const ETextCopyMethod InCopyMethod=ETextCopyMethod::NewKey, const bool bAlwaysApplyPackageNamespace=false)
Make a copy of the given text that's valid to use with the given package, optionally preserving its existing key.
bool EditTextProperty (UObject *InTextOwner, const FTextProperty *InTextProperty, const ETextEditAction InEditAction, const FString &InEditValue, TFunctionRef< FString()> InTextKeyGenerator=&GenerateRandomTextKey, const bool bApplyPackageNamespace=true)
Edit an attribute of the given text property, akin to what happens when editing a text property in a details panel.
bool EditTextProperty_Direct (UPackage *InPackage, void *InTextValue, const FTextProperty *InTextProperty, const ETextEditAction InEditAction, const FString &InEditValue, TFunctionRef< FString()> InTextKeyGenerator=&GenerateRandomTextKey, const bool bApplyPackageNamespace=true)
Edit an attribute of the given text property, akin to what happens when editing a text property in a details panel.
FString ExtractPackageNamespace (const FString &InTextNamespace)
Given a text namespace, extract any package namespace that may currently be present.
FString GenerateDeterministicTextKey (UObject *InTextOwner, const FName InTextPropertyName, const bool bApplyPackageNamespace=true)
FString GenerateDeterministicTextKey (UObject *InTextOwner, const FTextProperty *InTextProperty, const bool bApplyPackageNamespace=true)
Generate a deterministic text key based on the given object and property info.
FString GenerateRandomTextKey ()
Generate a random text key.
void GetTextIdForEdit (UPackage *InPackage, const ETextEditAction InEditAction, const FString &InTextSource, const FString &InProposedNamespace, const FString &InProposedKey, FString &OutStableNamespace, FString &OutStableKey, TFunctionRef< FString()> InTextKeyGenerator=&GenerateRandomTextKey, const bool bApplyPackageNamespace=true)
Called when editing a text property to determine the new ID for the text, ideally using the proposed text ID when possible (and when USE_STABLE_LOCALIZATION_KEYS is true).
FString StripPackageNamespace (const FString &InTextNamespace)
Given a text namespace, strip any package namespace that may currently be present.
void StripPackageNamespaceInline (FString &InOutTextNamespace)
Variables
constexpr TCHAR PackageNamespaceEndMarker = TEXT(']')
constexpr TCHAR PackageNamespaceStartMarker = TEXT('[')
Enumeration Type Documentation
ETextCopyMethod
enum class TextNamespaceUtil::ETextCopyMethod : uint8 strong
Enumerator
NewKey
Give the text a new key if the full namespace changes.
PreserveKey
Keep the existing key if the full namespace changes.
Verbatim
Copy the text verbatim, disregarding any full namespace changes.
Definition at line 51 of file TextNamespaceUtil.h.
ETextEditAction
enum class TextNamespaceUtil::ETextEditAction : uint8 strong
Enumerator
Namespace
Key
SourceString
Definition at line 130 of file TextPackageNamespaceUtil.h.
Function Documentation
BuildFullNamespace()
FString TextNamespaceUtil::BuildFullNamespace (const FString & InTextNamespace, const FString & InPackageNamespace, const bool bAlwaysApplyPackageNamespace = false)
Given a text and package namespace, build the full version that should be used by the localization system.
This can also be used to "zero-out" the package namespace used by a text namespace (by passing an empty package namespace) while still leaving the package namespace markers in place.
Parameters
InTextNamespace The namespace currently used by the FText instance.
InPackageNamespace The namespace of the package owning the FText instance.
bAlwaysApplyPackageNamespace If true, this will always apply the package namespace to the text namespace. If false, this will only apply the package namespace if the text namespace already contains package namespace markers.
Returns
The full namespace that should be used by the localization system.
CopyTextToPackage() [1/3]
FText TextNamespaceUtil::CopyTextToPackage (const FText & InText, const FString & InPackageNamespace, const ETextCopyMethod InCopyMethod = ETextCopyMethod::NewKey, const bool bAlwaysApplyPackageNamespace = false)
Make a copy of the given text that's valid to use with the given package namespace, optionally preserving its existing key.
Note
Returns the result verbatim if the given package namespace is empty, or if there is no change when applying the package namespace to the text.
Parameters
InText The current FText instance.
InPackageNamespace The namespace of the destination package of the FText instance.
InCopyMethod The method that should be used to copy the FText instance.
bAlwaysApplyPackageNamespace If true, this will always apply the package namespace to the text namespace (always treated as ETextCopyMethod::Verbatim when USE_STABLE_LOCALIZATION_KEYS is false). If false, this will only apply the package namespace if the text namespace already contains package namespace markers.
Returns
A copy of the given text that's valid to use with the given package namespace.
References NewKey.
CopyTextToPackage() [2/3]
FText TextNamespaceUtil::CopyTextToPackage (const FText & InText, UObject * InObject, const ETextCopyMethod InCopyMethod = ETextCopyMethod::NewKey, const bool bAlwaysApplyPackageNamespace = false)
References NewKey.
CopyTextToPackage() [3/3]
FText TextNamespaceUtil::CopyTextToPackage (const FText & InText, UPackage * InPackage, const ETextCopyMethod InCopyMethod = ETextCopyMethod::NewKey, const bool bAlwaysApplyPackageNamespace = false)
Make a copy of the given text that's valid to use with the given package, optionally preserving its existing key.
Note
Returns the result verbatim if there is no change when applying the package namespace to the text.
Parameters
InText The current FText instance.
InPackage/InObject The package (or object to get the owner package from) to get the namespace for (will call EnsurePackageNamespace).
InCopyMethod The method that should be used to copy the FText instance.
bAlwaysApplyPackageNamespace If true, this will always apply the package namespace to the text namespace (always treated as ETextCopyMethod::Verbatim when USE_STABLE_LOCALIZATION_KEYS is false). If false, this will only apply the package namespace if the text namespace already contains package namespace markers.
Returns
A copy of the given text that's valid to use with the given package.
References NewKey.
EditTextProperty()
bool TextNamespaceUtil::EditTextProperty (UObject * InTextOwner, const FTextProperty * InTextProperty, const ETextEditAction InEditAction, const FString & InEditValue, TFunctionRef< FString()> InTextKeyGenerator = &GenerateRandomTextKey, const bool bApplyPackageNamespace = true)
Edit an attribute of the given text property, akin to what happens when editing a text property in a details panel.
Parameters
InTextOwner The object that owns the given TextProperty to be edited.
InTextProperty The text property to edit. This must be a property that exists on TextOwner.
InEditAction How has the given text been edited?
InEditValue The new value of the attribute that was edited.
InTextKeyGenerator Generator for the new text key. Will generate a random key by default.
bApplyPackageNamespace If true, apply the package namespace to the generated text ID (when USE_STABLE_LOCALIZATION_KEYS is true).
Returns
True if edit was possible, or false if not.
References GenerateRandomTextKey().
EditTextProperty_Direct()
bool TextNamespaceUtil::EditTextProperty_Direct (UPackage * InPackage, void * InTextValue, const FTextProperty * InTextProperty, const ETextEditAction InEditAction, const FString & InEditValue, TFunctionRef< FString()> InTextKeyGenerator = &GenerateRandomTextKey, const bool bApplyPackageNamespace = true)
Edit an attribute of the given text property, akin to what happens when editing a text property in a details panel.
Parameters
InPackage The package that hosts the text value.
InTextValue The raw value of the TextProperty to be edited.
InTextProperty The text property to edit.
InEditAction How has the given text been edited?
InEditValue The new value of the attribute that was edited.
InTextKeyGenerator Generator for the new text key. Will generate a random key by default.
bApplyPackageNamespace If true, apply the package namespace to the generated text ID (when USE_STABLE_LOCALIZATION_KEYS is true).
Returns
True if edit was possible, or false if not.
References GenerateRandomTextKey().
ExtractPackageNamespace()
FString TextNamespaceUtil::ExtractPackageNamespace (const FString & InTextNamespace)
Given a text namespace, extract any package namespace that may currently be present.
Parameters
InTextNamespace The namespace currently used by the FText instance.
Returns
The extracted package namespace component, or an empty string if there was no package namespace component.
GenerateDeterministicTextKey() [1/2]
FString TextNamespaceUtil::GenerateDeterministicTextKey (UObject * InTextOwner, const FName InTextPropertyName, const bool bApplyPackageNamespace = true)
GenerateDeterministicTextKey() [2/2]
FString TextNamespaceUtil::GenerateDeterministicTextKey (UObject * InTextOwner, const FTextProperty * InTextProperty, const bool bApplyPackageNamespace = true)
Generate a deterministic text key based on the given object and property info.
Note
This key will be formatted like a GUID, but the value will actually be based on deterministic hashes.
Parameters
InTextOwner The object that owns the given TextProperty.
InTextProperty The text property to generate the key for.
bApplyPackageNamespace If true, apply the package namespace to the generated key hash (when USE_STABLE_LOCALIZATION_KEYS is true).
GenerateRandomTextKey()
FString TextNamespaceUtil::GenerateRandomTextKey ()
Generate a random text key.
Note
This key will be a GUID.
Referenced by EditTextProperty(), EditTextProperty_Direct(), and GetTextIdForEdit().
GetTextIdForEdit()
void TextNamespaceUtil::GetTextIdForEdit (UPackage * InPackage, const ETextEditAction InEditAction, const FString & InTextSource, const FString & InProposedNamespace, const FString & InProposedKey, FString & OutStableNamespace, FString & OutStableKey, TFunctionRef< FString()> InTextKeyGenerator = &GenerateRandomTextKey, const bool bApplyPackageNamespace = true)
Called when editing a text property to determine the new ID for the text, ideally using the proposed text ID when possible (and when USE_STABLE_LOCALIZATION_KEYS is true).
Parameters
InPackage The package to query the namespace for.
InEditAction How has the given text been edited?
InTextSource The current source string for the text being edited. Can be empty when InEditAction is ETextEditAction::SourceString.
InProposedNamespace The namespace we'd like to assign to the edited text.
InProposedKey The key we'd like to assign to the edited text.
OutStableNamespace The namespace that should be assigned to the edited text.
OutStableKey The key that should be assigned to the edited text.
InTextKeyGenerator Generator for the new text key. Will generate a random key by default.
bApplyPackageNamespace If true, apply the package namespace to the generated text ID (when USE_STABLE_LOCALIZATION_KEYS is true).
References GenerateRandomTextKey().
StripPackageNamespace()
FString TextNamespaceUtil::StripPackageNamespace (const FString & InTextNamespace)
Given a text namespace, strip any package namespace that may currently be present.
This is similar to calling BuildFullNamespace with an empty package namespace, however this version will also remove the package namespace markers.
Parameters
InTextNamespace The namespace currently used by the FText instance.
Returns
The namespace stripped of any package namespace component.
StripPackageNamespaceInline()
void TextNamespaceUtil::StripPackageNamespaceInline (FString & InOutTextNamespace)
Variable Documentation
PackageNamespaceEndMarker
TCHAR TextNamespaceUtil::PackageNamespaceEndMarker = TEXT(']') inline constexpr
Definition at line 16 of file TextNamespaceUtil.h.
PackageNamespaceStartMarker
TCHAR TextNamespaceUtil::PackageNamespaceStartMarker = TEXT('[') inline constexpr
Definition at line 15 of file TextNamespaceUtil.h.