Unreal Engine 5.6 C++ API: UE::Sequencer::FCreateBindingParams Struct Reference
UE::Sequencer::FCreateBindingParams Struct Reference
#include "SequencerUtilities.h"
Public Member Functions
FCreateBindingParams ()
FCreateBindingParams & Folder (const FName &InFolder)
FCreateBindingParams & Name (FString &&InName)
UE_DEPRECATED (5.4, "Please use FSequencerUtilitiesCreateBindingParams directly.") FCreateBindingParams(const FString &InBindingNameOverride)
Data Fields
TObjectPtr< UActorFactory > ActorFactory = nullptr
bool bAllowCustomBinding = true
bool bAllowEmptyBinding = false
int32 BindingIndex = 0
FString BindingNameOverride
bool bReplaceable = false
bool bSetupDefaults = true
bool bSpawnable = false
TObjectPtr< UMovieSceneCustomBinding > CustomBinding = nullptr
FName DesiredFolder
FGuid ReplacementGuid
Detailed Description
Definition at line 38 of file SequencerUtilities.h.
Constructor & Destructor Documentation
FCreateBindingParams()
UE::Sequencer::FCreateBindingParams::FCreateBindingParams () inline
Definition at line 45 of file SequencerUtilities.h.
Referenced by Folder(), Name(), and UE_DEPRECATED().
Member Function Documentation
Folder()
FCreateBindingParams & UE::Sequencer::FCreateBindingParams::Folder (const FName & InFolder) inline
Definition at line 53 of file SequencerUtilities.h.
References FCreateBindingParams(), and DesiredFolder.
Name()
FCreateBindingParams & UE::Sequencer::FCreateBindingParams::Name (FString && InName) inline
Definition at line 48 of file SequencerUtilities.h.
References FCreateBindingParams(), BindingNameOverride, InName, and MoveTemp().
UE_DEPRECATED()
UE::Sequencer::FCreateBindingParams::UE_DEPRECATED (5. 4, "Please use FSequencerUtilitiesCreateBindingParams directly.") const & inline
Definition at line 40 of file SequencerUtilities.h.
References FCreateBindingParams(), and BindingNameOverride.
Field Documentation
ActorFactory
TObjectPtr<UActorFactory> UE::Sequencer::FCreateBindingParams::ActorFactory = nullptr
Definition at line 78 of file SequencerUtilities.h.
bAllowCustomBinding
bool UE::Sequencer::FCreateBindingParams::bAllowCustomBinding = true
Definition at line 68 of file SequencerUtilities.h.
bAllowEmptyBinding
bool UE::Sequencer::FCreateBindingParams::bAllowEmptyBinding = false
Definition at line 70 of file SequencerUtilities.h.
BindingIndex
int32 UE::Sequencer::FCreateBindingParams::BindingIndex = 0
Definition at line 74 of file SequencerUtilities.h.
BindingNameOverride
FString UE::Sequencer::FCreateBindingParams::BindingNameOverride
Definition at line 59 of file SequencerUtilities.h.
Referenced by Name(), and UE_DEPRECATED().
bReplaceable
bool UE::Sequencer::FCreateBindingParams::bReplaceable = false
Definition at line 66 of file SequencerUtilities.h.
bSetupDefaults
bool UE::Sequencer::FCreateBindingParams::bSetupDefaults = true
Definition at line 80 of file SequencerUtilities.h.
bSpawnable
bool UE::Sequencer::FCreateBindingParams::bSpawnable = false
Definition at line 64 of file SequencerUtilities.h.
CustomBinding
TObjectPtr<UMovieSceneCustomBinding> UE::Sequencer::FCreateBindingParams::CustomBinding = nullptr
Definition at line 76 of file SequencerUtilities.h.
DesiredFolder
FName UE::Sequencer::FCreateBindingParams::DesiredFolder
Definition at line 61 of file SequencerUtilities.h.
Referenced by Folder().
ReplacementGuid
FGuid UE::Sequencer::FCreateBindingParams::ReplacementGuid
Definition at line 72 of file SequencerUtilities.h.
The documentation for this struct was generated from the following file:
SequencerUtilities.h