Unreal Engine 5.6 C++ API: FStreamableManager Struct Reference
FStreamableManager Struct Reference
A native class for managing streaming assets in and keeping them in memory.
#include "StreamableManager.h"
Data Structures
struct FRedirectedPath
Map of redirected paths.
Public Member Functions
FStreamableManager ()
FStreamableManager (const FStreamableManager &)=delete
Not safe to copy or duplicate.
~FStreamableManager ()
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Add referenced objects to stop them from GCing.
bool AreAllAsyncLoadsComplete () const
Returns true if all pending async loads have finished for all targets.
TSharedPtr< FStreamableHandle > CreateCombinedHandle (TConstArrayView< TSharedPtr< FStreamableHandle > > ChildHandles, FString DebugName=FStreamableHandle::HandleDebugName_CombinedHandle, EStreamableManagerCombinedHandleOptions Options=EStreamableManagerCombinedHandleOptions::None, FStreamableAsyncLoadParams &&Params=FStreamableAsyncLoadParams{}, UE::FSourceLocation Location=UE::FSourceLocation::Current())
Creates a combined handle, which will wait for other handles to complete before completing.
TSharedPtr< FStreamableHandle > CreateErrorHandle (UE::UnifiedError::FError &&Error, FStreamableAsyncLoadParams &&Params, FString DebugName=FStreamableHandle::HandleDebugName_CombinedHandle, UE::FSourceLocation Location=UE::FSourceLocation::Current())
Creates a canceled handle with an error set.
bool GetActiveHandles (const FSoftObjectPath &Target, TArray< TSharedRef< FStreamableHandle > > &HandleList, bool bOnlyManagedHandles=false) const
Gets list of handles that are directly referencing this asset, returns true if any found.
const FString & GetManagerName () const
Returns the debug name for this manager.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const override
Overload this method to report how the specified object is referenced, if necessary.
bool IsAsyncLoadComplete (const FSoftObjectPath &Target) const
Returns true if all pending async loads have finished for this target.
UObject * LoadSynchronous (const FSoftObjectPath &Target, bool bManageActiveHandle=false, TSharedPtr< FStreamableHandle > *RequestHandlePointer=nullptr, UE::FSourceLocation Location=UE::FSourceLocation::Current())
Synchronously load the referred asset and return the loaded object, or nullptr if it can't be found.
template<typename T>
T * LoadSynchronous (const FSoftObjectPath &Target, bool bManageActiveHandle=false, TSharedPtr< FStreamableHandle > *RequestHandlePointer=nullptr, UE::FSourceLocation Location=UE::FSourceLocation::Current())
Typed wrappers.
template<typename T>
TSubclassOf< T > LoadSynchronous (const TSoftClassPtr< T > &Target, bool bManageActiveHandle=false, TSharedPtr< FStreamableHandle > *RequestHandlePointer=nullptr, UE::FSourceLocation Location=UE::FSourceLocation::Current())
template<typename T>
T * LoadSynchronous (const TSoftObjectPtr< T > &Target, bool bManageActiveHandle=false, TSharedPtr< FStreamableHandle > *RequestHandlePointer=nullptr, UE::FSourceLocation Location=UE::FSourceLocation::Current())
FStreamableManager & operator= (const FStreamableManager &)=delete
TSharedPtr< FStreamableHandle > RequestAsyncLoad (FStreamableAsyncLoadParams &&Params, FString DebugName=FString(), UE::FSourceLocation Location=UE::FSourceLocation::Current())
This is the primary streamable operation.
template<typename PathContainerType = TArray<FSoftObjectPath>, typename FuncType = FStreamableDelegateWithHandle, typename = std::enable_if_t<!std::is_same_v<std::decay_t<PathContainerType>, FStreamableAsyncLoadParams>, void>>
TSharedPtr< FStreamableHandle > RequestAsyncLoad (PathContainerType &&TargetsToStream, FuncType &&DelegateToCall=FStreamableDelegateWithHandle(), TAsyncLoadPriority Priority=DefaultAsyncLoadPriority, bool bManageActiveHandle=false, bool bStartStalled=false, FString DebugName=FString(), UE::FSourceLocation Location=UE::FSourceLocation::Current())
This is the primary streamable operation.
template<typename PathContainerType = TArray<FSoftObjectPath>>
TSharedPtr< FStreamableHandle > RequestSyncLoad (PathContainerType &&TargetsToStream, bool bManageActiveHandle=false, FString DebugName=FString(), UE::FSourceLocation Location=UE::FSourceLocation::Current())
Synchronously load a set of assets, and return a handle.
FSoftObjectPath ResolveRedirects (const FSoftObjectPath &Target) const
Checks for any redirectors that were previously loaded, and returns the redirected target if found.
void SetManagerName (FString InName)
Modifies the debug name of this manager, used for debugging GC references.
void Unload (const FSoftObjectPath &Target)
This will release any managed active handles pointing to the target soft object path, even if they include other requested assets in the same load.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Attributes
static constexpr TAsyncLoadPriority AsyncLoadHighPriority = UE::StreamableManager::Private::AsyncLoadHighPriority
static constexpr TAsyncLoadPriority DefaultAsyncLoadPriority = UE::StreamableManager::Private::DefaultAsyncLoadPriority
static constexpr FStreamableDownloadPriority DownloadDefaultPriority = UE::StreamableManager::Private::DownloadDefaultPriority
static constexpr FStreamableDownloadPriority DownloadHighPriority = UE::StreamableManager::Private::DownloadHighPriority
static constexpr FStreamableDownloadPriority DownloadLowPriority = UE::StreamableManager::Private::DownloadLowPriority
static constexpr FStreamableDownloadPriority DownloadVeryHighPriority = UE::StreamableManager::Private::DownloadVeryHighPriority
static constexpr FStreamableDownloadPriority DownloadVeryLowPriority = UE::StreamableManager::Private::DownloadVeryLowPriority
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Private Types
typedef TMap< FSoftObjectPath, struct FStreamable * > TStreamableMap
Map of paths to streamable objects, this will be the post-redirector name.
typedef TMap< FSoftObjectPath, FRedirectedPath > TStreamableRedirects
Private Member Functions
void AsyncLoadCallback (FSoftObjectPath Request, UPackage *Package, const TOptional< UE::UnifiedError::FError > AsyncLoadError)
void CheckCompletedRequests (const FSoftObjectPath &Target, struct FStreamable *Existing)
void FindInMemory (FSoftObjectPath &InOutTarget, struct FStreamable *Existing, UPackage *Package=nullptr)
struct FStreamable * FindStreamable (const FSoftObjectPath &Target) const
TArray< int32 > GetAsyncLoadRequestIds (TSharedRef< FStreamableHandle > Handle)
UObject * GetStreamed (const FSoftObjectPath &Target) const
FSoftObjectPath HandleLoadedRedirector (UObjectRedirector *LoadedRedirector, FSoftObjectPath RequestedPath, struct FStreamable *RequestedStreamable)
void OnPreGarbageCollect ()
void RemoveReferencedAsset (const FSoftObjectPath &Target, TSharedRef< FStreamableHandle > Handle)
TSharedPtr< FStreamableHandle > RequestSyncLoadInternal (TArray< FSoftObjectPath > &&TargetsToStream, bool bManageActiveHandle, FString &&DebugName, UE::FSourceLocation &&Location)
void StartHandleRequests (TSharedRef< FStreamableHandle > Handle)
struct FStreamable * StreamInternal (const FSoftObjectPath &Target, TAsyncLoadPriority Priority, TSharedRef< FStreamableHandle > Handle)
Static Private Member Functions
static bool ShouldStripDebugName ()
Private Attributes
bool bForceSynchronousLoads
If True, temporarily force synchronous loading.
friend FStreamableHandle
TArray< TSharedRef< FStreamableHandle > > ManagedActiveHandles
List of explicitly held handles.
FString ManagerName
Debug name of this manager.
TArray< TSharedRef< FStreamableHandle > > PendingCombinedHandles
List of combined handles that are still loading, these need to be here to avoid them being deleted.
TStreamableMap StreamableItems
TStreamableRedirects StreamableRedirects
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Detailed Description
A native class for managing streaming assets in and keeping them in memory.
AssetManager is the global singleton version of this with blueprint access
Definition at line 702 of file StreamableManager.h.
Member Typedef Documentation
TStreamableMap
typedef TMap<FSoftObjectPath, struct FStreamable*> FStreamableManager::TStreamableMap private
Map of paths to streamable objects, this will be the post-redirector name.
Definition at line 904 of file StreamableManager.h.
TStreamableRedirects
typedef TMap<FSoftObjectPath, FRedirectedPath> FStreamableManager::TStreamableRedirects private
Definition at line 919 of file StreamableManager.h.
Constructor & Destructor Documentation
FStreamableManager() [1/2]
FStreamableManager::FStreamableManager ()
Referenced by FStreamableManager(), and operator=().
~FStreamableManager()
FStreamableManager::~FStreamableManager ()
FStreamableManager() [2/2]
FStreamableManager::FStreamableManager (const FStreamableManager &) delete
Not safe to copy or duplicate.
References FStreamableManager().
Member Function Documentation
AddReferencedObjects()
virtual void FStreamableManager::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Add referenced objects to stop them from GCing.
Implements FGCObject.
AreAllAsyncLoadsComplete()
bool FStreamableManager::AreAllAsyncLoadsComplete () const
Returns true if all pending async loads have finished for all targets.
AsyncLoadCallback()
void FStreamableManager::AsyncLoadCallback (FSoftObjectPath Request, UPackage * Package, const TOptional< UE::UnifiedError::FError > AsyncLoadError) private
References Package.
CheckCompletedRequests()
void FStreamableManager::CheckCompletedRequests (const FSoftObjectPath & Target, struct FStreamable * Existing) private
References Target.
CreateCombinedHandle()
TSharedPtr< FStreamableHandle > FStreamableManager::CreateCombinedHandle (TConstArrayView< TSharedPtr< FStreamableHandle > > ChildHandles, FString DebugName = FStreamableHandle::HandleDebugName_CombinedHandle, EStreamableManagerCombinedHandleOptions Options = EStreamableManagerCombinedHandleOptions::None, FStreamableAsyncLoadParams && Params = FStreamableAsyncLoadParams{}, UE::FSourceLocation Location = UE::FSourceLocation::Current())
Creates a combined handle, which will wait for other handles to complete before completing.
The child handles will be held as hard references as long as this handle is active.
Parameters
ChildHandles List of handles to wrap into this one
DebugName [optional] Name of this handle, will be reported in debug tools
Options [optional] Additional flags that let you specify how the combined handle will be constructed
Params [optional] Load Parameters. TargetsToStream, Priority, bManageActiveHandle, bStartStalled and DownloadParams are ignored
Location [optional] Is not intended for direct use, the parameter catches call site source location. That location is used for debug tools output.
References FStreamableHandle::HandleDebugName_CombinedHandle, None, and Params.
CreateErrorHandle()
TSharedPtr< FStreamableHandle > FStreamableManager::CreateErrorHandle (UE::UnifiedError::FError && Error, FStreamableAsyncLoadParams && Params, FString DebugName = FStreamableHandle::HandleDebugName_CombinedHandle, UE::FSourceLocation Location = UE::FSourceLocation::Current())
Creates a canceled handle with an error set.
Does not do any loading. Does not manage the handle. Useful in situations where a handle needs to be returned with an error without starting an actual load occuring.
Parameters
Error The error to set on the handle
Params Load Parameters
DownloadParams Additional Parameters to control downloading
DebugName [optional] Name of this handle, will be reported in debug tools
Location [optional] Is not intended for direct use, the parameter catches call site source location. That location is used for debug tools output.
References UE::FSourceLocation::Current(), Error, FStreamableHandle::HandleDebugName_CombinedHandle, Location, and Params.
FindInMemory()
void FStreamableManager::FindInMemory (FSoftObjectPath & InOutTarget, struct FStreamable * Existing, UPackage * Package = nullptr) private
References Package.
FindStreamable()
struct FStreamable * FStreamableManager::FindStreamable (const FSoftObjectPath & Target) const private
References Target.
GetActiveHandles()
bool FStreamableManager::GetActiveHandles (const FSoftObjectPath & Target, TArray< TSharedRef< FStreamableHandle > > & HandleList, bool bOnlyManagedHandles = false) const
Gets list of handles that are directly referencing this asset, returns true if any found.
Combined Handles will not be returned by this function.
Parameters
Target Asset to get active handles for
HandleList Fill in list of active handles
bOnlyManagedHandles If true, only return handles that are managed by this manager, other active handles are skipped
References Target.
GetAsyncLoadRequestIds()
TArray< int32 > FStreamableManager::GetAsyncLoadRequestIds (TSharedRef< FStreamableHandle > Handle) private
References Handle.
GetManagerName()
const FString & FStreamableManager::GetManagerName () const
Returns the debug name for this manager.
GetReferencerName()
virtual FString FStreamableManager::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 874 of file StreamableManager.h.
References ManagerName.
GetReferencerPropertyName()
virtual bool FStreamableManager::GetReferencerPropertyName (UObject * Object, FString & OutPropertyName) const override virtual
Overload this method to report how the specified object is referenced, if necessary.
Reimplemented from FGCObject.
References Object.
GetStreamed()
UObject * FStreamableManager::GetStreamed (const FSoftObjectPath & Target) const private
References Target.
HandleLoadedRedirector()
FSoftObjectPath FStreamableManager::HandleLoadedRedirector (UObjectRedirector * LoadedRedirector, FSoftObjectPath RequestedPath, struct FStreamable * RequestedStreamable) private
IsAsyncLoadComplete()
bool FStreamableManager::IsAsyncLoadComplete (const FSoftObjectPath & Target) const
Returns true if all pending async loads have finished for this target.
References Target.
LoadSynchronous() [1/4]
UObject * FStreamableManager::LoadSynchronous (const FSoftObjectPath & Target, bool bManageActiveHandle = false, TSharedPtr< FStreamableHandle > * RequestHandlePointer = nullptr, UE::FSourceLocation Location = UE::FSourceLocation::Current())
Synchronously load the referred asset and return the loaded object, or nullptr if it can't be found.
This can be very slow and may stall the game thread for several seconds.
Parameters
Target Specific asset to load off disk
bManageActiveHandle [optional] If true, the manager will keep the streamable handle active until explicitly released
RequestHandlePointer [optional] If non-null, this will set the handle to the handle used to make this request. This useful for later releasing the handle
Location [optional] Is not intended for direct use, the parameter catches call site source location. That location is used for debug tools output.
References UE::FSourceLocation::Current(), Location, and Target.
Referenced by LoadSynchronous(), LoadSynchronous(), and LoadSynchronous().
LoadSynchronous() [2/4]
template<typename T> T * FStreamableManager::LoadSynchronous (const FSoftObjectPath & Target, bool bManageActiveHandle = false, TSharedPtr< FStreamableHandle > * RequestHandlePointer = nullptr, UE::FSourceLocation Location = UE::FSourceLocation::Current()) inline
Typed wrappers.
Definition at line 779 of file StreamableManager.h.
References Cast(), UE::FSourceLocation::Current(), LoadSynchronous(), Location, MoveTemp(), and Target.
LoadSynchronous() [3/4]
template<typename T> TSubclassOf< T > FStreamableManager::LoadSynchronous (const TSoftClassPtr< T > & Target, bool bManageActiveHandle = false, TSharedPtr< FStreamableHandle > * RequestHandlePointer = nullptr, UE::FSourceLocation Location = UE::FSourceLocation::Current()) inline
Definition at line 799 of file StreamableManager.h.
References Cast(), UE::FSourceLocation::Current(), LoadSynchronous(), Location, MoveTemp(), and Target.
LoadSynchronous() [4/4]
template<typename T> T * FStreamableManager::LoadSynchronous (const TSoftObjectPtr< T > & Target, bool bManageActiveHandle = false, TSharedPtr< FStreamableHandle > * RequestHandlePointer = nullptr, UE::FSourceLocation Location = UE::FSourceLocation::Current()) inline
Definition at line 789 of file StreamableManager.h.
References Cast(), UE::FSourceLocation::Current(), LoadSynchronous(), Location, MoveTemp(), and Target.
OnPreGarbageCollect()
void FStreamableManager::OnPreGarbageCollect () private
operator=()
FStreamableManager & FStreamableManager::operator= (const FStreamableManager &) delete
References FStreamableManager().
RemoveReferencedAsset()
void FStreamableManager::RemoveReferencedAsset (const FSoftObjectPath & Target, TSharedRef< FStreamableHandle > Handle) private
References Handle, and Target.
RequestAsyncLoad() [1/2]
TSharedPtr< FStreamableHandle > FStreamableManager::RequestAsyncLoad (FStreamableAsyncLoadParams && Params, FString DebugName = FString(), UE::FSourceLocation Location = UE::FSourceLocation::Current())
This is the primary streamable operation.
Requests streaming of one or more target objects. When complete, a delegate function is called. Returns a Streamable Handle.
Parameters
Params Load Parameters
DebugName [optional] Name of this handle, either FString or anything that can construct FString, will be reported in debug tools
Location [optional] Is not intended for direct use, the parameter catches call site source location. That location is used for debug tools output.
References UE::FSourceLocation::Current(), Location, and Params.
RequestAsyncLoad() [2/2]
template<typename PathContainerType, typename FuncType, typename> TSharedPtr< FStreamableHandle > FStreamableManager::RequestAsyncLoad (PathContainerType && TargetsToStream, FuncType && DelegateToCall = FStreamableDelegateWithHandle(), TAsyncLoadPriority Priority = DefaultAsyncLoadPriority, bool bManageActiveHandle = false, bool bStartStalled = false, FString DebugName = FString(), UE::FSourceLocation Location = UE::FSourceLocation::Current())
This is the primary streamable operation.
Requests streaming of one or more target objects. When complete, a delegate function is called. Returns a Streamable Handle.
Parameters
TargetsToStream Assets to load off disk
DelegateToCall [optional] Delegate to call when load finishes. Will be called on the next tick if asset is already loaded, or many seconds later
Priority [optional] Priority to pass to the streaming system, higher priority will be loaded first
bManageActiveHandle [optional] If true, the manager will keep the streamable handle active until explicitly released
bStartStalled [optional] If true, the handle will start in a stalled state and will not attempt to actually async load until StartStalledHandle is called on it
DebugName [optional] Name of this handle, either FString or anything that can construct FString
Location [optional] Is not intended for direct use, the parameter catches call site source location. That location is used for debug tools output.
Definition at line 973 of file StreamableManager.h.
References UE::StreamableManager::Private::always_false_v, Forward(), Location, MoveTemp(), Params, RequestAsyncLoad(), and UE::StreamableManager::Private::WrapDelegate().
Referenced by RequestAsyncLoad().
RequestSyncLoad()
template<typename PathContainerType> TSharedPtr< FStreamableHandle > FStreamableManager::RequestSyncLoad (PathContainerType && TargetsToStream, bool bManageActiveHandle = false, FString DebugName = FString(), UE::FSourceLocation Location = UE::FSourceLocation::Current())
Synchronously load a set of assets, and return a handle.
This can be very slow and may stall the game thread for several seconds.
Parameters
TargetsToStream Assets to load off disk
bManageActiveHandle [optional] If true, the manager will keep the streamable handle active until explicitly released
DebugName [optional] Name of this handle, either FString or anything that can construct FString
Location [optional] Is not intended for direct use, the parameter catches call site source location. That location is used for debug tools output.
Definition at line 1020 of file StreamableManager.h.
References Forward(), Location, MoveTemp(), and RequestSyncLoadInternal().
RequestSyncLoadInternal()
TSharedPtr< FStreamableHandle > FStreamableManager::RequestSyncLoadInternal (TArray< FSoftObjectPath > && TargetsToStream, bool bManageActiveHandle, FString && DebugName, UE::FSourceLocation && Location) private
References Location.
Referenced by RequestSyncLoad().
ResolveRedirects()
FSoftObjectPath FStreamableManager::ResolveRedirects (const FSoftObjectPath & Target) const
Checks for any redirectors that were previously loaded, and returns the redirected target if found.
This will not handle redirects that it doesn't yet know about
References Target.
SetManagerName()
void FStreamableManager::SetManagerName (FString InName)
Modifies the debug name of this manager, used for debugging GC references.
References InName.
ShouldStripDebugName()
bool FStreamableManager::ShouldStripDebugName () static private
StartHandleRequests()
void FStreamableManager::StartHandleRequests (TSharedRef< FStreamableHandle > Handle) private
References Handle.
StreamInternal()
struct FStreamable * FStreamableManager::StreamInternal (const FSoftObjectPath & Target, TAsyncLoadPriority Priority, TSharedRef< FStreamableHandle > Handle) private
References Handle, and Target.
Unload()
void FStreamableManager::Unload (const FSoftObjectPath & Target)
This will release any managed active handles pointing to the target soft object path, even if they include other requested assets in the same load.
References Target.
Field Documentation
AsyncLoadHighPriority
TAsyncLoadPriority FStreamableManager::AsyncLoadHighPriority = UE::StreamableManager::Private::AsyncLoadHighPriority static constexpr
Definition at line 707 of file StreamableManager.h.
bForceSynchronousLoads
bool FStreamableManager::bForceSynchronousLoads private
If True, temporarily force synchronous loading.
Definition at line 929 of file StreamableManager.h.
DefaultAsyncLoadPriority
TAsyncLoadPriority FStreamableManager::DefaultAsyncLoadPriority = UE::StreamableManager::Private::DefaultAsyncLoadPriority static constexpr
Definition at line 705 of file StreamableManager.h.
DownloadDefaultPriority
FStreamableDownloadPriority FStreamableManager::DownloadDefaultPriority = UE::StreamableManager::Private::DownloadDefaultPriority static constexpr
Definition at line 711 of file StreamableManager.h.
DownloadHighPriority
FStreamableDownloadPriority FStreamableManager::DownloadHighPriority = UE::StreamableManager::Private::DownloadHighPriority static constexpr
Definition at line 712 of file StreamableManager.h.
DownloadLowPriority
FStreamableDownloadPriority FStreamableManager::DownloadLowPriority = UE::StreamableManager::Private::DownloadLowPriority static constexpr
Definition at line 710 of file StreamableManager.h.
DownloadVeryHighPriority
FStreamableDownloadPriority FStreamableManager::DownloadVeryHighPriority = UE::StreamableManager::Private::DownloadVeryHighPriority static constexpr
Definition at line 713 of file StreamableManager.h.
DownloadVeryLowPriority
FStreamableDownloadPriority FStreamableManager::DownloadVeryLowPriority = UE::StreamableManager::Private::DownloadVeryLowPriority static constexpr
Definition at line 709 of file StreamableManager.h.
FStreamableHandle
friend FStreamableManager::FStreamableHandle private
Definition at line 884 of file StreamableManager.h.
ManagedActiveHandles
TArray<TSharedRef<FStreamableHandle> > FStreamableManager::ManagedActiveHandles private
List of explicitly held handles.
Definition at line 923 of file StreamableManager.h.
ManagerName
FString FStreamableManager::ManagerName private
Debug name of this manager.
Definition at line 932 of file StreamableManager.h.
Referenced by GetReferencerName().
PendingCombinedHandles
TArray<TSharedRef<FStreamableHandle> > FStreamableManager::PendingCombinedHandles private
List of combined handles that are still loading, these need to be here to avoid them being deleted.
Definition at line 926 of file StreamableManager.h.
StreamableItems
TStreamableMap FStreamableManager::StreamableItems private
Definition at line 905 of file StreamableManager.h.
StreamableRedirects
TStreamableRedirects FStreamableManager::StreamableRedirects private
Definition at line 920 of file StreamableManager.h.
The documentation for this struct was generated from the following file:
StreamableManager.h