Unreal Engine 5.6 C++ API: UE::Slate::FDeprecateVector2DParameter Struct Reference
UE::Slate::FDeprecateVector2DParameter Struct Reference
Defines a Slate vector used as a function parameter that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
#include "SlateVector2.h"
Public Member Functions
FDeprecateVector2DParameter (const FDeprecateVector2DResult &InValue)
FDeprecateVector2DParameter (const FIntPoint &InValue)
FDeprecateVector2DParameter (const FVector2d &InValue)
FDeprecateVector2DParameter (const FVector2f &InValue)
FDeprecateVector2DParameter (double InX, double InY)
FDeprecateVector2DParameter (float InX, float InY)
Public Member Functions inherited from UE::Math::TVector2< float >
TVector2 ()=default
Default constructor (no initialization).
TVector2 (const TVector2< FArg > &From)
FORCEINLINE TVector2 (const TVector4< float > &V)
Constructs a vector from an FVector4.
FORCEINLINE TVector2 (const TVector< float > &V)
Constructs a vector from an FVector.
FORCEINLINE TVector2 (EForceInit)
Constructor which initializes all components to zero.
FORCEINLINE TVector2 (ENoInit)
Constructor that does not initialize.
FORCEINLINE TVector2 (float InF)
Constructor initializing both components to a single T value.
FORCEINLINE TVector2 (float InX, float InY)
Constructor using initial values for each component.
FORCEINLINE TVector2 (TIntPoint< IntType > InPos)
Constructs a vector from an FIntPoint.
TVector2 (TIntVector2< IntType > V)
FORCEINLINE TVector2 (TIntVector2< IntType > V)
TVector2< float > ClampAxes (float MinAxisVal, float MaxAxisVal) const
Creates a copy of this vector with both axes clamped to the given range.
float & Component (int32 Index)
Gets a specific component of the vector.
float Component (int32 Index) const
Gets a specific component of the vector.
TVector2< float > ComponentMax (const TVector2< float > &Other) const
Gets the component-wise max of two vectors.
TVector2< float > ComponentMin (const TVector2< float > &Other) const
Gets the component-wise min of two vectors.
bool ComponentwiseAllGreaterOrEqual (const TVector2< float > &Other) const
Checks whether both components of this vector are greater than or equal to another.
bool ComponentwiseAllGreaterThan (const TVector2< float > &Other) const
Checks whether both components of this vector are greater than another.
bool ComponentwiseAllLessOrEqual (const TVector2< float > &Other) const
Checks whether both components of this vector are less than or equal to another.
FORCEINLINE bool ContainsNaN () const
Utility to check if there are any non-finite values (NaN or Inf) in this vector.
FORCEINLINE void DiagnosticCheckNaN ()
float Dot (const TVector2< float > &V2) const
Get the dot product of this vector against another.
bool Equals (const TVector2< float > &V, float Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks for equality with error-tolerant comparison.
FORCEINLINE TVector2< float > GetAbs () const
Get a copy of this vector with absolute value of each component.
float GetAbsMax () const
Get the maximum absolute value of the vector's components.
TVector2< float > GetClampedToMaxSize (float MaxSize) const
Create a copy of this vector, with its maximum magnitude clamped to MaxSize.
TVector2< float > GetClampedToSize (float Min, float Max) const
Create a copy of this vector, with its magnitude clamped between Min and Max.
float GetMax () const
Get the maximum value of the vector's components.
float GetMin () const
Get the minimum value of the vector's components.
TVector2< float > GetRotated (float AngleDeg) const
Rotates around axis (0,0,1)
TVector2< float > GetSafeNormal (float Tolerance=UE_SMALL_NUMBER) const
Gets a normalized copy of the vector, checking it is safe to do so based on the length.
FORCEINLINE TVector2< float > GetSignVector () const
Get a copy of the vector as sign only.
bool InitFromString (const FString &InSourceString)
Initialize this Vector based on an FString.
FIntPoint IntPoint () const
Get this vector as an Int Point.
bool IsNearlyZero (float Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether vector is near to zero within a specified tolerance.
bool IsValidIndex (int32 Index) const
Tests if index is valid, i.e.
bool IsZero () const
Checks whether all components of the vector are exactly zero.
FORCEINLINE float Length () const
Get the length (magnitude) of this vector.
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess)
Network serialization function.
bool Normalize (float Tolerance=UE_SMALL_NUMBER)
Normalize this vector in-place if it is large enough, set it to (0,0) otherwise.
bool operator!= (const TVector2< float > &V) const
Compares this vector against another for inequality.
FORCEINLINE TVector2< float > operator* (const TVector2< float > &V) const
Gets the result of component-wise multiplication of this vector by another.
FORCEINLINE TVector2< float > operator* (float Scale) const
Gets the result of scaling the vector (multiplying each component by a value).
TVector2< float > operator*= (const TVector2< float > &V)
Multiplies this vector with another vector, using component-wise multiplication.
FORCEINLINE TVector2< float > operator*= (float Scale)
Scales this vector.
FORCEINLINE TVector2< float > operator+ (const TVector2< float > &V) const
Gets the result of adding two vectors together.
FORCEINLINE TVector2< float > operator+ (float A) const
Gets the result of adding A to each component of the vector.
FORCEINLINE TVector2< float > operator+= (const TVector2< float > &V)
Adds another vector to this.
FORCEINLINE TVector2< float > operator- () const
Gets a negated copy of the vector.
FORCEINLINE TVector2< float > operator- (const TVector2< float > &V) const
Gets the result of subtracting a vector from this one.
FORCEINLINE TVector2< float > operator- (float A) const
Gets the result of subtracting A from each component of the vector.
FORCEINLINE TVector2< float > operator-= (const TVector2< float > &V)
Subtracts another vector from this.
TVector2< float > operator/ (const TVector2< float > &V) const
Gets the result of component-wise division of this vector by another.
TVector2< float > operator/ (float Scale) const
Gets the result of dividing each component of the vector by a value.
TVector2< float > operator/= (const TVector2< float > &V)
Divides this vector by another vector, using component-wise division.
TVector2< float > operator/= (float V)
Divides this vector.
bool operator== (const TVector2< float > &V) const
Compares this vector against another for equality.
float & operator[] (int32 Index)
Gets specific component of the vector.
float operator[] (int32 Index) const
Gets specific component of the vector.
FORCEINLINE float operator^ (const TVector2< float > &V) const
Calculates cross product of this vector and another.
FORCEINLINE float operator| (const TVector2< float > &V) const
Calculates dot product of this vector and another.
TVector2< float > RoundToVector () const
Get this vector as a vector where each component has been rounded to the nearest int.
bool Serialize (FArchive &Ar)
bool Serialize (FStructuredArchive::FSlot Slot)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
void Set (float InX, float InY)
Set the values of the vector directly.
float Size () const
Get the length (magnitude) of this vector.
float SizeSquared () const
Get the squared length of this vector.
TVector< float > SphericalToUnitCartesian () const
Converts spherical coordinates on the unit sphere into a Cartesian unit length vector.
FORCEINLINE float SquaredLength () const
Get the squared length of this vector.
void ToDirectionAndLength (TVector2< float > &OutDir, FArg &OutLength) const
void ToDirectionAndLength (TVector2< float > &OutDir, float &OutLength) const
Util to convert this vector into a unit direction vector and its original length.
FString ToString () const
Get a textual representation of the vector.
UE_DEPRECATED (5.1, "TVector2 comparison operators are deprecated. Use ComponentwiseAllGreaterThan. For componentwise min/max/abs/clamp, use TVector2::{Min,Max,GetAbs,Clamp}, FMath::{Min,Max,Abs,Clamp} compute something different.") bool operator>(const TVector2< float > &Other) const
Deprecated comparison operator.
UE_DEPRECATED (5.1, "TVector2 comparison operators are deprecated. Use ComponentwiseAllLessOrEqual. For componentwise min/max/abs/clamp, use TVector2::{Min,Max,GetAbs,Clamp}, FMath::{Min,Max,Abs,Clamp} compute something different.") bool operator<
Deprecated comparison operator.
UE_DEPRECATED (5.1, "TVector2 comparison operators are deprecated. Use ComponentwiseAllLessThan. For componentwise min/max/abs/clamp, use TVector2::{Min,Max,GetAbs,Clamp}, FMath::{Min,Max,Abs,Clamp} compute something different.") bool operator<(const TVector2< float > &Other) const
Deprecated comparison operator.
Additional Inherited Members
Public Types inherited from UE::Math::TVector2< float >
using FReal
Static Public Member Functions inherited from UE::Math::TVector2< float >
static FORCEINLINE TVector2< float > Clamp (const TVector2< float > &V, const TVector2< float > &MinValue, const TVector2< float > &MaxValue)
Returns a vector with each component clamped between a minimum and a maximum.
static FORCEINLINE float CrossProduct (const TVector2< float > &A, const TVector2< float > &B)
Calculate the cross product of two vectors.
static FORCEINLINE float Distance (const TVector2< float > &V1, const TVector2< float > &V2)
Distance between two 2D points.
static FORCEINLINE float DistSquared (const TVector2< float > &V1, const TVector2< float > &V2)
Squared distance between two 2D points.
static FORCEINLINE float DotProduct (const TVector2< float > &A, const TVector2< float > &B)
Calculates the dot product of two vectors.
static FORCEINLINE TVector2< float > Max (const TVector2< float > &A, const TVector2< float > &B)
Returns a vector with the maximum component for each dimension from the pair of vectors.
static FORCEINLINE TVector2< float > Min (const TVector2< float > &A, const TVector2< float > &B)
Returns a vector with the minimum component for each dimension from the pair of vectors.
static TVector2< float > One ()
static TVector2< float > UnitX ()
static TVector2< float > UnitY ()
static TVector2< float > Zero ()
Data Fields inherited from UE::Math::TVector2< float >
union {
struct {
T X
Vector's X component.
T Y
Vector's Y component.
}
};
float X
Vector's X component.
float Y
Vector's Y component.
Static Public Attributes inherited from UE::Math::TVector2< float >
static constexpr int32 NumComponents
The number of components this vector type has.
static const TVector2< float > Unit45Deg
Global 2D unit vector constant along the 45 degree angle or symmetrical positive axes (sqrt(.5),sqrt(.5)) or (.707,.707).
static const TVector2< float > UnitVector
Global 2D one vector (poorly named) constant (1,1).
static const TVector2< float > ZeroVector
Global 2D zero vector constant (0,0)
Detailed Description
Defines a Slate vector used as a function parameter that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
Once deprecated completely, usages will be converted to using FVector2f directly.
This type is implicitly constructible from both single and double precision vectors and scalars but will emit deprecation warnings for double-precision types where UE_REPORT_SLATE_VECTOR_DEPRECATION is enabled. It is not (and will never be) convertible to double precision types.
This type should only be used as a parameter (not a return type), where FDeprecateVector2DResult is preferred so it can interop with legacy code that still requires conversion to FVector2d.
NOTE: DO NOT USE THIS TYPE DIRECTLY IN CLIENT CODE - ALL USAGES SHOULD USE FVector2f or float
Definition at line 484 of file SlateVector2.h.
Constructor & Destructor Documentation
FDeprecateVector2DParameter() [1/6]
UE::Slate::FDeprecateVector2DParameter::FDeprecateVector2DParameter (float InX, float InY) inline
Definition at line 486 of file SlateVector2.h.
Referenced by FDeprecateVector2DParameter(), FDeprecateVector2DParameter(), and FDeprecateVector2DParameter().
FDeprecateVector2DParameter() [2/6]
UE::Slate::FDeprecateVector2DParameter::FDeprecateVector2DParameter (const FVector2f & InValue) inline
Definition at line 490 of file SlateVector2.h.
FDeprecateVector2DParameter() [3/6]
UE::Slate::FDeprecateVector2DParameter::FDeprecateVector2DParameter (const FDeprecateVector2DResult & InValue) inline
Definition at line 494 of file SlateVector2.h.
FDeprecateVector2DParameter() [4/6]
UE::Slate::FDeprecateVector2DParameter::FDeprecateVector2DParameter (double InX, double InY) inline
Definition at line 499 of file SlateVector2.h.
References FDeprecateVector2DParameter(), and UE_REAL_TO_FLOAT.
FDeprecateVector2DParameter() [5/6]
UE::Slate::FDeprecateVector2DParameter::FDeprecateVector2DParameter (const FVector2d & InValue) inline
Definition at line 504 of file SlateVector2.h.
References FDeprecateVector2DParameter(), UE_REAL_TO_FLOAT, UE::Math::TVector2< float >::X, and UE::Math::TVector2< float >::Y.
FDeprecateVector2DParameter() [6/6]
UE::Slate::FDeprecateVector2DParameter::FDeprecateVector2DParameter (const FIntPoint & InValue) inline
Definition at line 509 of file SlateVector2.h.
References FDeprecateVector2DParameter(), FloatCastChecked(), UE::Math::TVector2< float >::X, and UE::Math::TVector2< float >::Y.
The documentation for this struct was generated from the following file:
SlateVector2.h