Unreal Engine 5.6 C++ API: FXxHash64 Struct Reference
FXxHash64 Struct Reference
A 64-bit hash from XXH3.
#include "xxhash.h"
Public Member Functions
bool IsZero () const
bool operator!= (const FXxHash64 &B) const
bool operator< (const FXxHash64 &B) const
bool operator== (const FXxHash64 &B) const
void ToByteArray (uint8(&Bytes)[sizeof(uint64)]) const
Store the hash to its canonical (big-endian) representation.
Static Public Member Functions
static FXxHash64 FromByteArray (const uint8(&Bytes)[sizeof(uint64)])
Load the hash from its canonical (big-endian) representation.
static FXxHash64 HashBuffer (const FCompositeBuffer &Buffer)
static FXxHash64 HashBuffer (const void *Data, uint64 Size)
static FXxHash64 HashBuffer (FMemoryView View)
static FXxHash64 HashBufferChunked (const void *Data, uint64 Size, uint64 ChunkSize)
static FXxHash64 HashBufferChunked (FMemoryView View, uint64 ChunkSize)
Hash the buffer in parallel in independent chunks, and hash those hashes.
Data Fields
uint64 Hash {}
The hash in its native representation.
Friends
uint32 GetTypeHash (const FXxHash64 &InHash)
FArchive & operator<< (FArchive &Ar, FXxHash64 &InHash)
template<typename CharType>
TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > &Builder, const FXxHash64 &InHash)
Detailed Description
A 64-bit hash from XXH3.
Definition at line 18 of file xxhash.h.
Member Function Documentation
FromByteArray()
FXxHash64 FXxHash64::FromByteArray (const uint8(&) Bytes[sizeof(uint64)]) inline static
Load the hash from its canonical (big-endian) representation.
Definition at line 41 of file xxhash.h.
References Bytes, FMemory::Memcpy(), and NETWORK_ORDER64.
HashBuffer() [1/3]
FXxHash64 FXxHash64::HashBuffer (const FCompositeBuffer & Buffer) static nodiscard
References Buffer.
HashBuffer() [2/3]
FXxHash64 FXxHash64::HashBuffer (const void * Data, uint64 Size) static nodiscard
References TSequenceHistory< HistorySize >::Size.
HashBuffer() [3/3]
FXxHash64 FXxHash64::HashBuffer (FMemoryView View) static nodiscard
HashBufferChunked() [1/2]
FXxHash64 FXxHash64::HashBufferChunked (const void * Data, uint64 Size, uint64 ChunkSize) static nodiscard
References TSequenceHistory< HistorySize >::Size.
HashBufferChunked() [2/2]
FXxHash64 FXxHash64::HashBufferChunked (FMemoryView View, uint64 ChunkSize) static nodiscard
Hash the buffer in parallel in independent chunks, and hash those hashes.
Use a ChunkSize large enough to cover task overhead, e.g., 256+ KiB. Hashing the same buffer with different chunk sizes produces a different output hash.
IsZero()
bool FXxHash64::IsZero () const inline
Definition at line 70 of file xxhash.h.
References Hash.
operator!=()
bool FXxHash64::operator!= (const FXxHash64 & B) const inline
Definition at line 60 of file xxhash.h.
References B, and Hash.
operator<()
bool FXxHash64::operator< (const FXxHash64 & B) const inline
Definition at line 65 of file xxhash.h.
References B, and Hash.
operator==()
bool FXxHash64::operator== (const FXxHash64 & B) const inline
Definition at line 55 of file xxhash.h.
References B, and Hash.
ToByteArray()
void FXxHash64::ToByteArray (uint8(&) Bytes[sizeof(uint64)]) const inline
Store the hash to its canonical (big-endian) representation.
Definition at line 49 of file xxhash.h.
References Bytes, Hash, FMemory::Memcpy(), and NETWORK_ORDER64.
Referenced by operator<<.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FXxHash64 & InHash) friend
Definition at line 75 of file xxhash.h.
References Hash.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FXxHash64 & InHash) friend
Definition at line 80 of file xxhash.h.
References Ar, and Hash.
operator<< [2/2]
template<typename CharType> TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > & Builder, const FXxHash64 & InHash) friend
Definition at line 86 of file xxhash.h.
References Bytes, UE::String::BytesToHexLower(), MakeArrayView(), and ToByteArray().
Field Documentation
Hash
uint64 FXxHash64::Hash {}
The hash in its native representation.
Use the canonical representation from ToByteArray to serialize or display the hash.
Definition at line 25 of file xxhash.h.
Referenced by GetTypeHash, IsZero(), operator!=(), operator<(), operator<<, operator==(), and ToByteArray().
The documentation for this struct was generated from the following file:
xxhash.h