Unreal Engine 5.6 C++ API: FFullBlueprintEditorCommands Class Reference
FFullBlueprintEditorCommands Class Reference
#include "SBlueprintEditorToolbar.h"
Public Member Functions
FFullBlueprintEditorCommands ()
Constructor.
virtual void RegisterCommands () override
Initialize commands.
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TSharedPtr< FUICommandInfo > Compile
Compile the blueprint.
TSharedPtr< FUICommandInfo > EditClassDefaults
TSharedPtr< FUICommandInfo > EditGlobalOptions
Edit Blueprint global options.
TSharedPtr< FUICommandInfo > JumpToErrorNode
TSharedPtr< FUICommandInfo > SaveOnCompile_Always
TSharedPtr< FUICommandInfo > SaveOnCompile_Never
TSharedPtr< FUICommandInfo > SaveOnCompile_SuccessOnly
TSharedPtr< FUICommandInfo > SwitchToBlueprintDefaultsMode
TSharedPtr< FUICommandInfo > SwitchToComponentsMode
TSharedPtr< FUICommandInfo > SwitchToScriptingMode
Switch between modes in the blueprint editor.
Additional Inherited Members
Static Public Member Functions inherited from TCommands< FFullBlueprintEditorCommands >
static FFullBlueprintEditorCommands & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Protected Member Functions inherited from TCommands< FFullBlueprintEditorCommands >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TCommands< FFullBlueprintEditorCommands >
static TWeakPtr< FFullBlueprintEditorCommands > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 50 of file SBlueprintEditorToolbar.h.
Constructor & Destructor Documentation
FFullBlueprintEditorCommands()
FFullBlueprintEditorCommands::FFullBlueprintEditorCommands () inline
Constructor.
Definition at line 54 of file SBlueprintEditorToolbar.h.
References FFullBlueprintEditorCommands(), TCommands< FFullBlueprintEditorCommands >::TCommands(), and NSLOCTEXT.
Referenced by FFullBlueprintEditorCommands().
Member Function Documentation
RegisterCommands()
virtual void FFullBlueprintEditorCommands::RegisterCommands () override virtual
Initialize commands.
Implements TCommands< FFullBlueprintEditorCommands >.
Field Documentation
Compile
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::Compile
Compile the blueprint.
Definition at line 60 of file SBlueprintEditorToolbar.h.
EditClassDefaults
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::EditClassDefaults
Definition at line 73 of file SBlueprintEditorToolbar.h.
EditGlobalOptions
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::EditGlobalOptions
Edit Blueprint global options.
Definition at line 72 of file SBlueprintEditorToolbar.h.
JumpToErrorNode
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::JumpToErrorNode
Definition at line 64 of file SBlueprintEditorToolbar.h.
SaveOnCompile_Always
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::SaveOnCompile_Always
Definition at line 63 of file SBlueprintEditorToolbar.h.
SaveOnCompile_Never
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::SaveOnCompile_Never
Definition at line 61 of file SBlueprintEditorToolbar.h.
SaveOnCompile_SuccessOnly
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::SaveOnCompile_SuccessOnly
Definition at line 62 of file SBlueprintEditorToolbar.h.
SwitchToBlueprintDefaultsMode
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::SwitchToBlueprintDefaultsMode
Definition at line 68 of file SBlueprintEditorToolbar.h.
SwitchToComponentsMode
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::SwitchToComponentsMode
Definition at line 69 of file SBlueprintEditorToolbar.h.
SwitchToScriptingMode
TSharedPtr<FUICommandInfo> FFullBlueprintEditorCommands::SwitchToScriptingMode
Switch between modes in the blueprint editor.
Definition at line 67 of file SBlueprintEditorToolbar.h.
The documentation for this class was generated from the following file:
SBlueprintEditorToolbar.h