Unreal Engine 5.6 C++ API: FStateTreeLinker Struct Reference
FStateTreeLinker Struct Reference
The StateTree linker is used to resolved references to various StateTree data at load time.
#include "StateTreeLinker.h"
Public Member Functions
FStateTreeLinker (const UStateTreeSchema *InSchema)
const TArrayView< const FStateTreeExternalDataDesc > GetExternalDataDescs () const
EStateTreeLinkerStatus GetStatus () const
void LinkExternalData (FStateTreeExternalDataHandle &Handle, const UStruct *Struct, const EStateTreeExternalDataRequirement Requirement)
Links reference to an external Object or Struct.
template<typename T>
TEnableIf< TIsDerivedFrom< typenameT::DataType, UObject >::IsDerived, void >::Type LinkExternalData (T &Handle)
Links reference to an external UObject.
template<typename T>
TEnableIf<!TIsDerivedFrom< typenameT::DataType, UObject >::IsDerived &&!TIsIInterface< typenameT::DataType >::Value, void >::Type LinkExternalData (T &Handle)
Links reference to an external UStruct.
template<typename T>
TEnableIf< TIsIInterface< typenameT::DataType >::Value, void >::Type LinkExternalData (T &Handle)
Links reference to an external IInterface.
Protected Attributes
TArray< FStateTreeExternalDataDesc > ExternalDataDescs
TStrongObjectPtr< const UStateTreeSchema > Schema
EStateTreeLinkerStatus Status = EStateTreeLinkerStatus::Succeeded
Detailed Description
The StateTree linker is used to resolved references to various StateTree data at load time.
See also
TStateTreeExternalDataHandle<> for example usage.
Definition at line 21 of file StateTreeLinker.h.
Constructor & Destructor Documentation
FStateTreeLinker()
FStateTreeLinker::FStateTreeLinker (const UStateTreeSchema * InSchema) inline explicit
Definition at line 23 of file StateTreeLinker.h.
References Schema.
Member Function Documentation
GetExternalDataDescs()
const TArrayView< const FStateTreeExternalDataDesc > FStateTreeLinker::GetExternalDataDescs () const inline
Returns
linked external data descriptors.
Definition at line 92 of file StateTreeLinker.h.
References ExternalDataDescs.
GetStatus()
EStateTreeLinkerStatus FStateTreeLinker::GetStatus () const inline
Returns
the linking status.
Definition at line 26 of file StateTreeLinker.h.
References Status.
LinkExternalData() [1/4]
void FStateTreeLinker::LinkExternalData (FStateTreeExternalDataHandle & Handle, const UStruct * Struct, const EStateTreeExternalDataRequirement Requirement) inline
Links reference to an external Object or Struct.
This function should only be used when TStateTreeExternalDataHandle<> cannot be used, i.e. the Struct is based on some data.
Parameters
Handle Reference to link to.
Struct Expected type of the Object or Struct to link to.
Requirement Describes if the external data is expected to be required or optional.
Definition at line 65 of file StateTreeLinker.h.
References Error, ExternalDataDescs, Handle, INDEX_NONE, Schema, Status, Struct, TEXT, and UE_LOG.
LinkExternalData() [2/4]
template<typename T> TEnableIf< TIsDerivedFrom< typenameT::DataType, UObject >::IsDerived, void >::Type FStateTreeLinker::LinkExternalData (T & Handle) inline
Links reference to an external UObject.
Parameters
Handle Reference to TStateTreeExternalDataHandle<> with UOBJECT type to link to.
Definition at line 33 of file StateTreeLinker.h.
References Handle, and LinkExternalData().
Referenced by LinkExternalData().
LinkExternalData() [3/4]
template<typename T> TEnableIf<!TIsDerivedFrom< typenameT::DataType, UObject >::IsDerived &&!TIsIInterface< typenameT::DataType >::Value, void >::Type FStateTreeLinker::LinkExternalData (T & Handle) inline
Links reference to an external UStruct.
Parameters
Handle Reference to TStateTreeExternalDataHandle<> with USTRUCT type to link to.
Definition at line 43 of file StateTreeLinker.h.
References Handle, LinkExternalData(), and TIsIInterface< T, bIsAUObject_IMPL >::Value.
LinkExternalData() [4/4]
template<typename T> TEnableIf< TIsIInterface< typenameT::DataType >::Value, void >::Type FStateTreeLinker::LinkExternalData (T & Handle) inline
Links reference to an external IInterface.
Parameters
Handle Reference to TStateTreeExternalDataHandle<> with IINTERFACE type to link to.
Definition at line 53 of file StateTreeLinker.h.
References Handle, and LinkExternalData().
Field Documentation
ExternalDataDescs
TArray<FStateTreeExternalDataDesc> FStateTreeLinker::ExternalDataDescs protected
Definition at line 100 of file StateTreeLinker.h.
Referenced by GetExternalDataDescs(), and LinkExternalData().
Schema
TStrongObjectPtr<const UStateTreeSchema> FStateTreeLinker::Schema protected
Definition at line 98 of file StateTreeLinker.h.
Referenced by FStateTreeLinker(), and LinkExternalData().
Status
EStateTreeLinkerStatus FStateTreeLinker::Status = EStateTreeLinkerStatus::Succeeded protected
Definition at line 99 of file StateTreeLinker.h.
Referenced by GetStatus(), and LinkExternalData().
The documentation for this struct was generated from the following file:
StateTreeLinker.h