Unreal Engine 5.6 C++ API: FIoBuffer::BufCore Struct Reference
FIoBuffer::BufCore Struct Reference
Core buffer object.
Public Member Functions
BufCore ()
BufCore (const BufCore &Rhs)=delete
BufCore (const uint8 *InData, uint64 InSize, bool InOwnsMemory)
BufCore (const uint8 *InData, uint64 InSize, const BufCore *InOuter)
BufCore (ECloneTag, uint8 *InData, uint64 InSize)
BufCore (uint64 InSize)
~BufCore ()
uint32 AddRef () const
uint8 * Data ()
uint64 DataSize () const
uint32 GetRefCount () const
bool IsMemoryOwned () const
void MakeOwned ()
BufCore & operator= (const BufCore &Rhs)=delete
uint32 Release () const
TIoStatusOr< uint8 * > ReleaseMemory ()
void SetDataAndSize (const uint8 *InData, uint64 InSize)
void SetIsOwned (bool InOwnsMemory)
void SetSize (uint64 InSize)
Private Types
enum { OwnsMemory = 1 << 0 , ReadOnlyBuffer = 1 << 1 , FlagsMask = (1 << 2) - 1 }
Private Member Functions
void CheckRefCount () const
void ClearFlags ()
void EnsureDataIsResident ()
Private Attributes
uint8 * DataPtr = nullptr
uint8 DataSizeHigh = 0
uint32 DataSizeLow = 0
uint8 Flags = 0
int32 NumRefs = 0
TRefCountPtr< const BufCore > OuterCore
Detailed Description
Core buffer object.
For internal use only, used by FIoBuffer
Contains all state pertaining to a buffer.
Definition at line 74 of file IoBuffer.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
OwnsMemory
ReadOnlyBuffer
FlagsMask
Definition at line 156 of file IoBuffer.h.
Constructor & Destructor Documentation
BufCore() [1/6]
FIoBuffer::BufCore::BufCore ()
Referenced by BufCore(), BufCore(), and operator=().
~BufCore()
FIoBuffer::BufCore::~BufCore ()
BufCore() [2/6]
FIoBuffer::BufCore::BufCore (uint64 InSize) explicit
BufCore() [3/6]
FIoBuffer::BufCore::BufCore (const uint8 * InData, uint64 InSize, bool InOwnsMemory)
BufCore() [4/6]
FIoBuffer::BufCore::BufCore (const uint8 * InData, uint64 InSize, const BufCore * InOuter)
References BufCore(), and InOuter.
BufCore() [5/6]
FIoBuffer::BufCore::BufCore (ECloneTag , uint8 * InData, uint64 InSize)
BufCore() [6/6]
FIoBuffer::BufCore::BufCore (const BufCore & Rhs) delete
References BufCore().
Member Function Documentation
AddRef()
uint32 FIoBuffer::BufCore::AddRef () const inline
Definition at line 112 of file IoBuffer.h.
References NumRefs.
CheckRefCount()
void FIoBuffer::BufCore::CheckRefCount () const private
Referenced by Release().
ClearFlags()
void FIoBuffer::BufCore::ClearFlags () inline private
Definition at line 166 of file IoBuffer.h.
References Flags.
Data()
uint8 * FIoBuffer::BufCore::Data () inline
Definition at line 88 of file IoBuffer.h.
References DataPtr.
DataSize()
uint64 FIoBuffer::BufCore::DataSize () const inline
Definition at line 89 of file IoBuffer.h.
References DataSizeHigh, and DataSizeLow.
EnsureDataIsResident()
void FIoBuffer::BufCore::EnsureDataIsResident () inline private
Definition at line 164 of file IoBuffer.h.
GetRefCount()
uint32 FIoBuffer::BufCore::GetRefCount () const inline
Definition at line 132 of file IoBuffer.h.
References NumRefs.
IsMemoryOwned()
bool FIoBuffer::BufCore::IsMemoryOwned () const inline
Definition at line 137 of file IoBuffer.h.
References Flags, and OwnsMemory.
MakeOwned()
void FIoBuffer::BufCore::MakeOwned ()
operator=()
BufCore & FIoBuffer::BufCore::operator= (const BufCore & Rhs) delete
References BufCore().
Release()
uint32 FIoBuffer::BufCore::Release () const inline
Definition at line 117 of file IoBuffer.h.
References CheckRefCount(), and NumRefs.
ReleaseMemory()
TIoStatusOr< uint8 * > FIoBuffer::BufCore::ReleaseMemory ()
SetDataAndSize()
void FIoBuffer::BufCore::SetDataAndSize (const uint8 * InData, uint64 InSize)
SetIsOwned()
void FIoBuffer::BufCore::SetIsOwned (bool InOwnsMemory) inline
Definition at line 100 of file IoBuffer.h.
References Flags, and OwnsMemory.
SetSize()
void FIoBuffer::BufCore::SetSize (uint64 InSize)
Field Documentation
DataPtr
uint8* FIoBuffer::BufCore::DataPtr = nullptr private
Definition at line 142 of file IoBuffer.h.
Referenced by Data().
DataSizeHigh
uint8 FIoBuffer::BufCore::DataSizeHigh = 0 private
Definition at line 153 of file IoBuffer.h.
Referenced by DataSize().
DataSizeLow
uint32 FIoBuffer::BufCore::DataSizeLow = 0 private
Definition at line 144 of file IoBuffer.h.
Referenced by DataSize().
Flags
uint8 FIoBuffer::BufCore::Flags = 0 private
Definition at line 154 of file IoBuffer.h.
Referenced by ClearFlags(), IsMemoryOwned(), and SetIsOwned().
NumRefs
int32 FIoBuffer::BufCore::NumRefs = 0 mutable private
Definition at line 145 of file IoBuffer.h.
Referenced by AddRef(), GetRefCount(), and Release().
OuterCore
TRefCountPtr<const BufCore> FIoBuffer::BufCore::OuterCore private
Definition at line 150 of file IoBuffer.h.
The documentation for this struct was generated from the following file:
IoBuffer.h