Unreal Engine 5.6 C++ API: FAutoDeleteAsyncTask< TTask > Class Template Reference
FAutoDeleteAsyncTask< TTask > Class Template Reference
#include "AsyncWork.h"
Public Member Functions
template<typename... T>
FAutoDeleteAsyncTask (T &&... Args)
Forwarding constructor.
void StartBackgroundTask (FQueuedThreadPool *InQueuedPool=GThreadPool, EQueuedWorkPriority InPriority=EQueuedWorkPriority::Normal)
Run this task on the lo priority thread pool.
void StartSynchronousTask ()
Run this task on this thread, now.
Private Member Functions
virtual void Abandon (void)
Always called from the thread pool.
virtual void DoThreadedWork ()
Always called from the thread pool.
void DoWork ()
Tells the user job to do the work, sometimes called synchronously, sometimes from the thread pool.
void Start (bool bForceSynchronous, FQueuedThreadPool *InQueuedPool, EQueuedWorkPriority InPriority=EQueuedWorkPriority::Normal)
Private Member Functions inherited from UE::FInheritedContextBase
void CaptureInheritedContext ()
FInheritedContextScope RestoreInheritedContext ()
Private Member Functions inherited from IQueuedWork
virtual ~IQueuedWork ()
Virtual destructor so that child implementations are guaranteed a chance to clean up any resources they allocated.
virtual const TCHAR * GetDebugName () const
Returns text to identify the Work, for debug/log purposes only.
virtual EQueuedWorkFlags GetQueuedWorkFlags () const
Returns any special work flags.
virtual int64 GetRequiredMemory () const
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
Private Attributes
TTask Task
User job embedded in this task.
Private Attributes inherited from IQueuedWork
IInternalDataType InternalData
Additional Inherited Members
Private Types inherited from IQueuedWork
using IInternalDataType = TRefCountPtr<IQueuedWorkInternalData>
Internal data can be used by the pool.
Detailed Description
template<typename TTask>
class FAutoDeleteAsyncTask< TTask >
FAutoDeleteAsyncTask - template task for jobs that delete themselves when complete
Sample code:
class ExampleAutoDeleteAsyncTask : public FNonAbandonableTask
{
    friend class FAutoDeleteAsyncTask<ExampleAutoDeleteAsyncTask>;
    int32 ExampleData;
    ExampleAutoDeleteAsyncTask(int32 InExampleData)
     : ExampleData(InExampleData)
    {
    }
    void DoWork()
    {
        ... do the work here
    }
    FORCEINLINE TStatId GetStatId() const
    {
        RETURN_QUICK_DECLARE_CYCLE_STAT(ExampleAutoDeleteAsyncTask, STATGROUP_ThreadPoolAsyncTasks);
    }
};
void Example()
{
start an example job (new FAutoDeleteAsyncTask<ExampleAutoDeleteAsyncTask>(5)->StartBackgroundTask();
do an example job now, on this thread (new FAutoDeleteAsyncTask<ExampleAutoDeleteAsyncTask>(5)->StartSynchronousTask(); }
Definition at line 60 of file AsyncWork.h.
Constructor & Destructor Documentation
FAutoDeleteAsyncTask()
template<typename TTask> template<typename... T> FAutoDeleteAsyncTask< TTask >::FAutoDeleteAsyncTask (T &&... Args) inline explicit
Forwarding constructor.
Definition at line 130 of file AsyncWork.h.
Member Function Documentation
Abandon()
template<typename TTask> virtual void FAutoDeleteAsyncTask< TTask >::Abandon (void) inline private virtual
Always called from the thread pool.
Called if the task is removed from queue before it has started which might happen at exit. If the user job can abandon, we do that, otherwise we force the work to be done now (doing nothing would not be safe).
Implements IQueuedWork.
Definition at line 114 of file AsyncWork.h.
DoThreadedWork()
template<typename TTask> virtual void FAutoDeleteAsyncTask< TTask >::DoThreadedWork () inline private virtual
Always called from the thread pool.
Just passes off to DoWork
Implements IQueuedWork.
Definition at line 105 of file AsyncWork.h.
DoWork()
template<typename TTask> void FAutoDeleteAsyncTask< TTask >::DoWork () inline private
Tells the user job to do the work, sometimes called synchronously, sometimes from the thread pool.
Calls the event tracker.
Definition at line 93 of file AsyncWork.h.
Referenced by FAutoDeleteAsyncTask< FCancelIORequestsTask >::Abandon(), FAutoDeleteAsyncTask< FCancelIORequestsTask >::DoThreadedWork(), and FAutoDeleteAsyncTask< FCancelIORequestsTask >::Start().
Start()
template<typename TTask> void FAutoDeleteAsyncTask< TTask >::Start (bool bForceSynchronous, FQueuedThreadPool * InQueuedPool, EQueuedWorkPriority InPriority = EQueuedWorkPriority::Normal) inline private
Definition at line 70 of file AsyncWork.h.
Referenced by FAutoDeleteAsyncTask< FCancelIORequestsTask >::StartBackgroundTask(), and FAutoDeleteAsyncTask< FCancelIORequestsTask >::StartSynchronousTask().
StartBackgroundTask()
template<typename TTask> void FAutoDeleteAsyncTask< TTask >::StartBackgroundTask (FQueuedThreadPool * InQueuedPool = GThreadPool, EQueuedWorkPriority InPriority = EQueuedWorkPriority::Normal) inline
Run this task on the lo priority thread pool.
It is not safe to use this object after this call.
Definition at line 145 of file AsyncWork.h.
StartSynchronousTask()
template<typename TTask> void FAutoDeleteAsyncTask< TTask >::StartSynchronousTask () inline
Run this task on this thread, now.
Will end up destroying myself, so it is not safe to use this object after this call.
Definition at line 137 of file AsyncWork.h.
Field Documentation
Task
template<typename TTask> TTask FAutoDeleteAsyncTask< TTask >::Task private
User job embedded in this task.
Definition at line 65 of file AsyncWork.h.
The documentation for this class was generated from the following file:
AsyncWork.h