Unreal Engine 5.6 C++ API: UE::Geometry::TMatrix2< RealType > Struct Template Reference
UE::Geometry::TMatrix2< RealType > Struct Template Reference
#include "MatrixTypes.h"
Public Member Functions
TMatrix2 ()
TMatrix2 (const TVector2< RealType > &U, const TVector2< RealType > &V)
Construct outer-product of U*transpose(V) of U and V result is that Mij = u_i * v_j.
TMatrix2 (const TVector2< RealType > &V1, const TVector2< RealType > &V2, bool bRows)
TMatrix2 (RealType ConstantValue)
TMatrix2 (RealType Diag0, RealType Diag1)
TMatrix2 (RealType M00, RealType M01, RealType M10, RealType M11)
RealType Determinant () const
bool EpsilonEqual (const TMatrix2< RealType > &Mat2, RealType Epsilon) const
RealType GetAngleRad ()
Assumes we have a rotation matrix (uniform scale ok)
RealType InnerProduct (const TMatrix2< RealType > &Mat2) const
TMatrix2< RealType > Inverse () const
RealType operator() (int Row, int Col) const
TMatrix2< RealType > operator* (const TMatrix2< RealType > &Mat2) const
TVector2< RealType > operator* (const TVector2< RealType > &V) const
TMatrix2< RealType > operator* (RealType Scale) const
TMatrix2< RealType > & operator*= (const RealType &Scalar)
TMatrix2< RealType > operator+ (const TMatrix2< RealType > &Mat2)
TMatrix2< RealType > & operator+= (const TMatrix2< RealType > &Mat2)
TMatrix2< RealType > operator- (const TMatrix2< RealType > &Mat2)
RealType Trace () const
TMatrix2< RealType > Transpose () const
Static Public Member Functions
static TMatrix2< RealType > AxisScale (TVector2< RealType > Axis, RealType Scale, bool bNormalizeAxis=true)
static TMatrix2< RealType > Identity ()
static TMatrix2< RealType > RotationDeg (RealType AngleDeg)
static TMatrix2< RealType > RotationRad (RealType AngleRad)
static TMatrix2< RealType > Zero ()
Data Fields
TVector2< RealType > Row0
TVector2< RealType > Row1
Detailed Description
template<typename RealType>
struct UE::Geometry::TMatrix2< RealType >
Definition at line 282 of file MatrixTypes.h.
Constructor & Destructor Documentation
TMatrix2() [1/6]
template<typename RealType> UE::Geometry::TMatrix2< RealType >::TMatrix2 () inline
Definition at line 287 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix2< float >::AxisScale(), UE::Geometry::TMatrix2< float >::Identity(), UE::Geometry::TMatrix2< float >::Inverse(), UE::Geometry::TMatrix2< float >::operator*(), UE::Geometry::TMatrix2< float >::operator*(), UE::Geometry::TMatrix2< float >::operator+(), UE::Geometry::TMatrix2< float >::operator-(), UE::Geometry::TMatrix2< float >::RotationRad(), UE::Geometry::TMatrix2< float >::Transpose(), and UE::Geometry::TMatrix2< float >::Zero().
TMatrix2() [2/6]
template<typename RealType> UE::Geometry::TMatrix2< RealType >::TMatrix2 (RealType ConstantValue) inline
Definition at line 291 of file MatrixTypes.h.
TMatrix2() [3/6]
template<typename RealType> UE::Geometry::TMatrix2< RealType >::TMatrix2 (RealType Diag0, RealType Diag1) inline
Definition at line 296 of file MatrixTypes.h.
TMatrix2() [4/6]
template<typename RealType> UE::Geometry::TMatrix2< RealType >::TMatrix2 (const TVector2< RealType > & U, const TVector2< RealType > & V) inline
Construct outer-product of U*transpose(V) of U and V result is that Mij = u_i * v_j.
Definition at line 296 of file MatrixTypes.h.
TMatrix2() [5/6]
template<typename RealType> UE::Geometry::TMatrix2< RealType >::TMatrix2 (RealType M00, RealType M01, RealType M10, RealType M11) inline
Definition at line 312 of file MatrixTypes.h.
TMatrix2() [6/6]
template<typename RealType> UE::Geometry::TMatrix2< RealType >::TMatrix2 (const TVector2< RealType > & V1, const TVector2< RealType > & V2, bool bRows) inline
Definition at line 318 of file MatrixTypes.h.
Member Function Documentation
AxisScale()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::AxisScale (TVector2< RealType > Axis, RealType Scale, bool bNormalizeAxis = true) inline static
Definition at line 455 of file MatrixTypes.h.
Determinant()
template<typename RealType> RealType UE::Geometry::TMatrix2< RealType >::Determinant () const inline
Definition at line 413 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix2< float >::Inverse().
EpsilonEqual()
template<typename RealType> bool UE::Geometry::TMatrix2< RealType >::EpsilonEqual (const TMatrix2< RealType > & Mat2, RealType Epsilon) const inline
Definition at line 433 of file MatrixTypes.h.
GetAngleRad()
template<typename RealType> RealType UE::Geometry::TMatrix2< RealType >::GetAngleRad () inline
Assumes we have a rotation matrix (uniform scale ok)
Definition at line 472 of file MatrixTypes.h.
Identity()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::Identity () inline static
Definition at line 336 of file MatrixTypes.h.
InnerProduct()
template<typename RealType> RealType UE::Geometry::TMatrix2< RealType >::InnerProduct (const TMatrix2< RealType > & Mat2) const inline
Definition at line 403 of file MatrixTypes.h.
Inverse()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::Inverse () const inline
Definition at line 418 of file MatrixTypes.h.
operator()()
template<typename RealType> RealType UE::Geometry::TMatrix2< RealType >::operator() (int Row, int Col) const inline
Definition at line 341 of file MatrixTypes.h.
operator*() [1/3]
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::operator* (const TMatrix2< RealType > & Mat2) const inline
Definition at line 368 of file MatrixTypes.h.
operator*() [2/3]
template<typename RealType> TVector2< RealType > UE::Geometry::TMatrix2< RealType >::operator* (const TVector2< RealType > & V) const inline
Definition at line 361 of file MatrixTypes.h.
operator*() [3/3]
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::operator* (RealType Scale) const inline
Definition at line 354 of file MatrixTypes.h.
operator*=()
template<typename RealType> TMatrix2< RealType > & UE::Geometry::TMatrix2< RealType >::operator*= (const RealType & Scalar) inline
Definition at line 389 of file MatrixTypes.h.
operator+()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::operator+ (const TMatrix2< RealType > & Mat2) inline
Definition at line 379 of file MatrixTypes.h.
operator+=()
template<typename RealType> TMatrix2< RealType > & UE::Geometry::TMatrix2< RealType >::operator+= (const TMatrix2< RealType > & Mat2) inline
Definition at line 396 of file MatrixTypes.h.
operator-()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::operator- (const TMatrix2< RealType > & Mat2) inline
Definition at line 384 of file MatrixTypes.h.
RotationDeg()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::RotationDeg (RealType AngleDeg) inline static
Definition at line 446 of file MatrixTypes.h.
RotationRad()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::RotationRad (RealType AngleRad) inline static
Definition at line 439 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix2< float >::RotationDeg().
Trace()
template<typename RealType> RealType UE::Geometry::TMatrix2< RealType >::Trace () const inline
Definition at line 408 of file MatrixTypes.h.
Transpose()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::Transpose () const inline
Definition at line 426 of file MatrixTypes.h.
Zero()
template<typename RealType> TMatrix2< RealType > UE::Geometry::TMatrix2< RealType >::Zero () inline static
Definition at line 332 of file MatrixTypes.h.
Field Documentation
Row0
template<typename RealType> TVector2<RealType> UE::Geometry::TMatrix2< RealType >::Row0
Definition at line 284 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix2< float >::EpsilonEqual(), UE::Geometry::TMatrix2< float >::InnerProduct(), UE::Geometry::operator*(), UE::Geometry::TMatrix2< float >::operator*(), UE::Geometry::TMatrix2< float >::operator+(), UE::Geometry::TMatrix2< float >::operator+=(), and UE::Geometry::TMatrix2< float >::operator-().
Row1
template<typename RealType> TVector2<RealType> UE::Geometry::TMatrix2< RealType >::Row1
Definition at line 285 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix2< float >::EpsilonEqual(), UE::Geometry::TMatrix2< float >::InnerProduct(), UE::Geometry::operator*(), UE::Geometry::TMatrix2< float >::operator*(), UE::Geometry::TMatrix2< float >::operator+(), UE::Geometry::TMatrix2< float >::operator+=(), and UE::Geometry::TMatrix2< float >::operator-().
The documentation for this struct was generated from the following file:
MatrixTypes.h