Unreal Engine 5.6 C++ API: TCFRef< CFRefType > Class Template Reference
TCFRef< CFRefType > Class Template Reference
#include "CFRef.h"
Public Member Functions
TCFRef ()
Default constructor (initialized to null).
TCFRef (CFRefType InRef)
Take ownership of a Core Foundation Ref without increasing its reference count.
TCFRef (const TCFRef &Other)
Copy constructor.
TCFRef (TCFRef &&Other)
Move constructor.
~TCFRef ()
Destructor.
CFRefType * GetForAssignment ()
Return a pointer to the Core Foundation Ref to allow it to be passed into a function that will reassign it.
operator bool () const
Check to see if the Ref is non-null.
operator CFRefType () const
Core Foundation Type conversion operator.
template<typename T = CFRefType, typename = typename UE4CFRef_Private::TTollFreeBridgeType<T>::Type>
operator typename UE4CFRef_Private::TTollFreeBridgeType< T >::Type () const
Foundation Type conversion operator if toll-free bridging exists for the Core Foundation Type.
TCFRef & operator= (const TCFRef &Other)
Copy assignment operator.
TCFRef & operator= (TCFRef &&Other)
Move assignment operator.
Private Attributes
CFRefType Ref
Detailed Description
template<class CFRefType>
class TCFRef< CFRefType >
Definition at line 41 of file CFRef.h.
Constructor & Destructor Documentation
TCFRef() [1/4]
template<class CFRefType> TCFRef< CFRefType >::TCFRef () inline
Default constructor (initialized to null).
Definition at line 48 of file CFRef.h.
References Ref.
Referenced by TCFRef(), TCFRef(), operator=(), and operator=().
TCFRef() [2/4]
template<class CFRefType> TCFRef< CFRefType >::TCFRef (CFRefType InRef) inline
Take ownership of a Core Foundation Ref without increasing its reference count.
Parameters
InRef The Ref to take ownership of.
Definition at line 58 of file CFRef.h.
References Ref.
TCFRef() [3/4]
template<class CFRefType> TCFRef< CFRefType >::TCFRef (const TCFRef< CFRefType > & Other) inline
Copy constructor.
Parameters
Other The instance to copy.
Definition at line 68 of file CFRef.h.
References TCFRef(), Other, and Ref.
TCFRef() [4/4]
template<class CFRefType> TCFRef< CFRefType >::TCFRef (TCFRef< CFRefType > && Other) inline
Move constructor.
Parameters
Other The instance to move.
Definition at line 79 of file CFRef.h.
References TCFRef(), Other, and Ref.
~TCFRef()
template<class CFRefType> TCFRef< CFRefType >::~TCFRef () inline
Destructor.
Definition at line 88 of file CFRef.h.
References Ref.
Member Function Documentation
GetForAssignment()
template<class CFRefType> CFRefType * TCFRef< CFRefType >::GetForAssignment () inline
Return a pointer to the Core Foundation Ref to allow it to be passed into a function that will reassign it.
Returns
A pointer to the Core Foundation Ref.
Definition at line 140 of file CFRef.h.
References Ref.
operator bool()
template<class CFRefType> TCFRef< CFRefType >::operator bool () const inline explicit
Check to see if the Ref is non-null.
Returns
True if the Ref is non-null.
Definition at line 155 of file CFRef.h.
References Ref.
operator CFRefType()
template<class CFRefType> TCFRef< CFRefType >::operator CFRefType () const inline
Core Foundation Type conversion operator.
Returns
The Core Foundation Ref.
Definition at line 165 of file CFRef.h.
References Ref.
operator typename UE4CFRef_Private::TTollFreeBridgeType< T >::Type()
template<class CFRefType> template<typename T = CFRefType, typename = typename UE4CFRef_Private::TTollFreeBridgeType<T>::Type> TCFRef< CFRefType >::operator typename UE4CFRef_Private::TTollFreeBridgeType< T >::Type () const inline
Foundation Type conversion operator if toll-free bridging exists for the Core Foundation Type.
Returns
The Core Foundation Ref cast to its Foundation equivalent.
Definition at line 177 of file CFRef.h.
References Ref.
operator=() [1/2]
template<class CFRefType> TCFRef & TCFRef< CFRefType >::operator= (const TCFRef< CFRefType > & Other) inline
Copy assignment operator.
Parameters
Other The instance to copy.
Definition at line 101 of file CFRef.h.
References TCFRef(), Other, and Ref.
operator=() [2/2]
template<class CFRefType> TCFRef & TCFRef< CFRefType >::operator= (TCFRef< CFRefType > && Other) inline
Move assignment operator.
Parameters
Other The instance to move.
Definition at line 120 of file CFRef.h.
References TCFRef(), Other, and Ref.
Field Documentation
Ref
template<class CFRefType> CFRefType TCFRef< CFRefType >::Ref private
Definition at line 184 of file CFRef.h.
Referenced by TCFRef(), TCFRef(), TCFRef(), TCFRef(), ~TCFRef(), GetForAssignment(), operator bool(), operator CFRefType(), operator typename UE4CFRef_Private::TTollFreeBridgeType< T >::Type(), operator=(), and operator=().
The documentation for this class was generated from the following file:
CFRef.h