Unreal Engine 5.6 C++ API: UE::Geometry::TDistLine2AxisAlignedBox2< Real > Class Template Reference
UE::Geometry::TDistLine2AxisAlignedBox2< Real > Class Template Reference
Compute unsigned distance between 2D line and 2D axis aligned box.
#include "DistLine2AxisAlignedBox2.h"
Public Member Functions
TDistLine2AxisAlignedBox2 (const TLine2< Real > LineIn, const TBox2< Real > &AxisAlignedBoxIn)
Real ComputeResult ()
Real Get ()
Real GetSquared ()
Data Fields
TBox2< Real > AxisAlignedBox
TVector2< Real > BoxClosest
TLine2< Real > Line
TVector2< Real > LineClosest
Real LineParameter
Real ResultDistanceSquared = -1.0
Static Private Member Functions
static void DoQuery (TVector2< Real > origin, TVector2< Real > direction, const TVector2< Real > &boxExtent, TVector2< Real > &BoxClosest, TVector2< Real > &LineClosest, Real &LineParameter)
static void DoQuery0D (TVector2< Real > const &origin, TVector2< Real > const &extent, TVector2< Real > &BoxClosest, TVector2< Real > &LineClosest, Real &LineParameter)
static void DoQuery1D (int32_t i0, int32_t i1, TVector2< Real > const &origin, TVector2< Real > const &direction, TVector2< Real > const &extent, TVector2< Real > &BoxClosest, TVector2< Real > &LineClosest, Real &LineParameter)
static void DoQuery2D (TVector2< Real > const &origin, TVector2< Real > const &direction, TVector2< Real > const &extent, TVector2< Real > &BoxClosest, TVector2< Real > &LineClosest, Real &LineParameter)
Detailed Description
template<typename Real>
class UE::Geometry::TDistLine2AxisAlignedBox2< Real >
Compute unsigned distance between 2D line and 2D axis aligned box.
Definition at line 23 of file DistLine2AxisAlignedBox2.h.
Constructor & Destructor Documentation
TDistLine2AxisAlignedBox2()
template<typename Real> UE::Geometry::TDistLine2AxisAlignedBox2< Real >::TDistLine2AxisAlignedBox2 (const TLine2< Real > LineIn, const TBox2< Real > & AxisAlignedBoxIn) inline
Definition at line 35 of file DistLine2AxisAlignedBox2.h.
Member Function Documentation
ComputeResult()
template<typename Real> Real UE::Geometry::TDistLine2AxisAlignedBox2< Real >::ComputeResult () inline
Definition at line 48 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistLine2AxisAlignedBox2< float >::Get(), and UE::Geometry::TDistLine2AxisAlignedBox2< float >::GetSquared().
DoQuery()
template<typename Real> void UE::Geometry::TDistLine2AxisAlignedBox2< Real >::DoQuery (TVector2< Real > origin, TVector2< Real > direction, const TVector2< Real > & boxExtent, TVector2< Real > & BoxClosest, TVector2< Real > & LineClosest, Real & LineParameter) inline static private
Definition at line 76 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistLine2AxisAlignedBox2< float >::ComputeResult().
DoQuery0D()
template<typename Real> void UE::Geometry::TDistLine2AxisAlignedBox2< Real >::DoQuery0D (TVector2< Real > const & origin, TVector2< Real > const & extent, TVector2< Real > & BoxClosest, TVector2< Real > & LineClosest, Real & LineParameter) inline static private
Definition at line 215 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistLine2AxisAlignedBox2< float >::DoQuery().
DoQuery1D()
template<typename Real> void UE::Geometry::TDistLine2AxisAlignedBox2< Real >::DoQuery1D (int32_t i0, int32_t i1, TVector2< Real > const & origin, TVector2< Real > const & direction, TVector2< Real > const & extent, TVector2< Real > & BoxClosest, TVector2< Real > & LineClosest, Real & LineParameter) inline static private
Definition at line 207 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistLine2AxisAlignedBox2< float >::DoQuery().
DoQuery2D()
template<typename Real> void UE::Geometry::TDistLine2AxisAlignedBox2< Real >::DoQuery2D (TVector2< Real > const & origin, TVector2< Real > const & direction, TVector2< Real > const & extent, TVector2< Real > & BoxClosest, TVector2< Real > & LineClosest, Real & LineParameter) inline static private
Definition at line 161 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistLine2AxisAlignedBox2< float >::DoQuery().
Get()
template<typename Real> Real UE::Geometry::TDistLine2AxisAlignedBox2< Real >::Get () inline
Definition at line 39 of file DistLine2AxisAlignedBox2.h.
GetSquared()
template<typename Real> Real UE::Geometry::TDistLine2AxisAlignedBox2< Real >::GetSquared () inline
Definition at line 43 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistSegment2AxisAlignedBox2< float >::ComputeResult().
Field Documentation
AxisAlignedBox
template<typename Real> TBox2<Real> UE::Geometry::TDistLine2AxisAlignedBox2< Real >::AxisAlignedBox
Definition at line 28 of file DistLine2AxisAlignedBox2.h.
BoxClosest
template<typename Real> TVector2<Real> UE::Geometry::TDistLine2AxisAlignedBox2< Real >::BoxClosest
Definition at line 32 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistSegment2AxisAlignedBox2< float >::ComputeResult().
Line
template<typename Real> TLine2<Real> UE::Geometry::TDistLine2AxisAlignedBox2< Real >::Line
Definition at line 27 of file DistLine2AxisAlignedBox2.h.
LineClosest
template<typename Real> TVector2<Real> UE::Geometry::TDistLine2AxisAlignedBox2< Real >::LineClosest
Definition at line 32 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistSegment2AxisAlignedBox2< float >::ComputeResult().
LineParameter
template<typename Real> Real UE::Geometry::TDistLine2AxisAlignedBox2< Real >::LineParameter
Definition at line 33 of file DistLine2AxisAlignedBox2.h.
Referenced by UE::Geometry::TDistSegment2AxisAlignedBox2< float >::ComputeResult().
ResultDistanceSquared
template<typename Real> Real UE::Geometry::TDistLine2AxisAlignedBox2< Real >::ResultDistanceSquared = -1.0
Definition at line 31 of file DistLine2AxisAlignedBox2.h.
The documentation for this class was generated from the following file:
DistLine2AxisAlignedBox2.h