Unreal Engine 5.6 C++ API: UE::Geometry::FMeshBevel::FBevelVertex Struct Reference
UE::Geometry::FMeshBevel::FBevelVertex Struct Reference
#include "MeshBevel.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FBevelVertex ()=default
FBevelVertex (const FBevelVertex &)=default
FBevelVertex (FBevelVertex &&)=default
UE_DEPRECATED (5.5, "Mapping back to source topology is not used.") int32 CornerID
UE_DEPRECATED (5.5, "Mapping back to source topology is not used.") TArray< int32 > IncomingBevelTopoEdges
Data Fields
int32 ConnectedBevelVertex = -1
TArray< int32 > IncomingBevelEdgeIndices
TArray< int32 > IncomingBevelMeshEdges
TArray< int32 > InteriorBorderLoop
TArray< FBevelVertex_InteriorVertex > InteriorVertices
int32 NewGroupID
TArray< int32 > NewTriangles
TArray< int32 > SortedTriangles
FIndex2i TerminatorInfo
PRAGMA_ENABLE_DEPRECATION_WARNINGS int32 VertexID
EBevelVertexType VertexType = EBevelVertexType::Unknown
TArray< FOneRingWedge > Wedges
Detailed Description
Definition at line 257 of file MeshBevel.h.
Constructor & Destructor Documentation
FBevelVertex() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FMeshBevel::FBevelVertex::FBevelVertex () default
Referenced by FBevelVertex(), and FBevelVertex().
FBevelVertex() [2/3]
UE::Geometry::FMeshBevel::FBevelVertex::FBevelVertex (const FBevelVertex &) default
References FBevelVertex().
FBevelVertex() [3/3]
UE::Geometry::FMeshBevel::FBevelVertex::FBevelVertex (FBevelVertex &&) default
References FBevelVertex(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Member Function Documentation
UE_DEPRECATED() [1/2]
UE::Geometry::FMeshBevel::FBevelVertex::UE_DEPRECATED (5. 5, "Mapping back to source topology is not used.")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Geometry::FMeshBevel::FBevelVertex::UE_DEPRECATED (5. 5, "Mapping back to source topology is not used.")
References UE_DEPRECATED().
Field Documentation
ConnectedBevelVertex
int32 UE::Geometry::FMeshBevel::FBevelVertex::ConnectedBevelVertex = -1
Definition at line 282 of file MeshBevel.h.
IncomingBevelEdgeIndices
TArray<int32> UE::Geometry::FMeshBevel::FBevelVertex::IncomingBevelEdgeIndices
Definition at line 273 of file MeshBevel.h.
IncomingBevelMeshEdges
TArray<int32> UE::Geometry::FMeshBevel::FBevelVertex::IncomingBevelMeshEdges
Definition at line 270 of file MeshBevel.h.
InteriorBorderLoop
TArray<int32> UE::Geometry::FMeshBevel::FBevelVertex::InteriorBorderLoop
Definition at line 286 of file MeshBevel.h.
InteriorVertices
TArray<FBevelVertex_InteriorVertex> UE::Geometry::FMeshBevel::FBevelVertex::InteriorVertices
Definition at line 285 of file MeshBevel.h.
NewGroupID
int32 UE::Geometry::FMeshBevel::FBevelVertex::NewGroupID
Definition at line 278 of file MeshBevel.h.
NewTriangles
TArray<int32> UE::Geometry::FMeshBevel::FBevelVertex::NewTriangles
Definition at line 279 of file MeshBevel.h.
SortedTriangles
TArray<int32> UE::Geometry::FMeshBevel::FBevelVertex::SortedTriangles
Definition at line 275 of file MeshBevel.h.
TerminatorInfo
FIndex2i UE::Geometry::FMeshBevel::FBevelVertex::TerminatorInfo
Definition at line 281 of file MeshBevel.h.
VertexID
PRAGMA_ENABLE_DEPRECATION_WARNINGS int32 UE::Geometry::FMeshBevel::FBevelVertex::VertexID
Definition at line 265 of file MeshBevel.h.
VertexType
EBevelVertexType UE::Geometry::FMeshBevel::FBevelVertex::VertexType = EBevelVertexType::Unknown
Definition at line 268 of file MeshBevel.h.
Wedges
TArray<FOneRingWedge> UE::Geometry::FMeshBevel::FBevelVertex::Wedges
Definition at line 276 of file MeshBevel.h.
The documentation for this struct was generated from the following file:
MeshBevel.h