Unreal Engine 5.6 C++ API: UE::Tasks::FPipe Class Reference
UE::Tasks::FPipe Class Reference
#include "Pipe.h"
Public Member Functions
FPipe (const TCHAR *InDebugName)
~FPipe ()
FORCENOINLINE const TCHAR * GetDebugName () const
bool HasWork () const
bool IsInContext () const
template<typename TaskBodyType>
TTask< TInvokeResult_T< TaskBodyType > > Launch (const TCHAR *InDebugName, TaskBodyType &&TaskBody, ETaskPriority Priority=ETaskPriority::Default, EExtendedTaskPriority ExtendedPriority=EExtendedTaskPriority::None, ETaskFlags Flags=ETaskFlags::None)
template<typename TaskBodyType, typename PrerequisitesCollectionType>
TTask< TInvokeResult_T< TaskBodyType > > Launch (const TCHAR *InDebugName, TaskBodyType &&TaskBody, PrerequisitesCollectionType &&Prerequisites, ETaskPriority Priority=ETaskPriority::Default, EExtendedTaskPriority ExtendedPriority=EExtendedTaskPriority::None, ETaskFlags Flags=ETaskFlags::None)
UE_NONCOPYABLE (FPipe)
bool WaitUntilEmpty (FTimespan Timeout=FTimespan::MaxValue())
Private Member Functions
void ClearTask (Private::FTaskBase &Task)
void ExecutionFinished ()
void ExecutionStarted ()
Private::FTaskBase * PushIntoPipe (Private::FTaskBase &Task)
Private Attributes
const TCHAR *const DebugName
TSharedRef< UE::FEventCount > EmptyEventRef
std::atomic< Private::FTaskBase * > LastTask { nullptr }
std::atomic< uint64 > TaskCount { 0 }
Friends
class Private::FTaskBase
Detailed Description
Definition at line 28 of file Pipe.h.
Constructor & Destructor Documentation
FPipe()
UE::Tasks::FPipe::FPipe (const TCHAR * InDebugName) inline explicit
Definition at line 35 of file Pipe.h.
References DebugName, EmptyEventRef, and MakeShared().
Referenced by UE_NONCOPYABLE().
~FPipe()
UE::Tasks::FPipe::~FPipe () inline
Definition at line 40 of file Pipe.h.
References check, and HasWork().
Member Function Documentation
ClearTask()
void UE::Tasks::FPipe::ClearTask (Private::FTaskBase & Task) private
ExecutionFinished()
void UE::Tasks::FPipe::ExecutionFinished () private
ExecutionStarted()
void UE::Tasks::FPipe::ExecutionStarted () private
GetDebugName()
FORCENOINLINE const TCHAR * UE::Tasks::FPipe::GetDebugName () const inline
Definition at line 140 of file Pipe.h.
References DebugName, and FORCENOINLINE.
HasWork()
bool UE::Tasks::FPipe::HasWork () const inline
Definition at line 46 of file Pipe.h.
References TaskCount.
Referenced by ~FPipe().
IsInContext()
bool UE::Tasks::FPipe::IsInContext () const
Launch() [1/2]
template<typename TaskBodyType> TTask< TInvokeResult_T< TaskBodyType > > UE::Tasks::FPipe::Launch (const TCHAR * InDebugName, TaskBodyType && TaskBody, ETaskPriority Priority = ETaskPriority::Default, EExtendedTaskPriority ExtendedPriority = EExtendedTaskPriority::None, ETaskFlags Flags = ETaskFlags::None) inline
Definition at line 63 of file Pipe.h.
References Flags, Forward(), UE::Tasks::None, and TaskCount.
Launch() [2/2]
template<typename TaskBodyType, typename PrerequisitesCollectionType> TTask< TInvokeResult_T< TaskBodyType > > UE::Tasks::FPipe::Launch (const TCHAR * InDebugName, TaskBodyType && TaskBody, PrerequisitesCollectionType && Prerequisites, ETaskPriority Priority = ETaskPriority::Default, EExtendedTaskPriority ExtendedPriority = EExtendedTaskPriority::None, ETaskFlags Flags = ETaskFlags::None) inline
Definition at line 90 of file Pipe.h.
References Flags, Forward(), UE::Tasks::None, UE::Tasks::Prerequisites(), and TaskCount.
PushIntoPipe()
Private::FTaskBase * UE::Tasks::FPipe::PushIntoPipe (Private::FTaskBase & Task) nodiscard private
UE_NONCOPYABLE()
UE::Tasks::FPipe::UE_NONCOPYABLE (FPipe)
References FPipe().
WaitUntilEmpty()
bool UE::Tasks::FPipe::WaitUntilEmpty (FTimespan Timeout = FTimespan::MaxValue())
References FTimespan::MaxValue(), and UE::Tasks::Timeout.
Friends And Related Symbol Documentation
Private::FTaskBase
friend class Private::FTaskBase friend
Definition at line 120 of file Pipe.h.
Field Documentation
DebugName
const TCHAR* const UE::Tasks::FPipe::DebugName private
Definition at line 146 of file Pipe.h.
Referenced by FPipe(), and GetDebugName().
EmptyEventRef
TSharedRef<UE::FEventCount> UE::Tasks::FPipe::EmptyEventRef private
Definition at line 138 of file Pipe.h.
Referenced by FPipe().
LastTask
std::atomic<Private::FTaskBase*> UE::Tasks::FPipe::LastTask { nullptr } private
Definition at line 136 of file Pipe.h.
TaskCount
std::atomic<uint64> UE::Tasks::FPipe::TaskCount { 0 } private
Definition at line 137 of file Pipe.h.
Referenced by HasWork(), Launch(), and Launch().
The documentation for this class was generated from the following file:
Pipe.h