Unreal Engine 5.6 C++ API: SDetailsDiff Class Reference
SDetailsDiff Class Reference
#include "SDetailsDiff.h"
Data Structures
struct FDiffControl
Public Member Functions
Use NewAsset instead NewAsset NewRevision ParentWindow OnCustomizeDetailsWidget virtual SLATE_EVENT(DiffUtils::FOnGenerateCustomDiffEntries, OnGenerateCustomDiffEntries) SLATE_EVENT(DiffUtils ~SDetailsDiff ()
DECLARE_DELEGATE_OneParam (FOnCustomizeDetailsWidget, const TSharedRef< IDetailsView > &) DECLARE_DELEGATE_RetVal_OneParam(FLinearColor
const TUniquePtr< FAsyncDetailViewDiff::DiffNodeType > & DECLARE_DELEGATE_RetVal_OneParam (bool, FShouldHighlightRow, const TUniquePtr< FAsyncDetailViewDiff::DiffNodeType > &) SLATE_BEGIN_ARGS(SDetailsDiff)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnWindowClosedEvent, TSharedRef< SDetailsDiff >) FOnWindowClosedEvent OnWindowClosedEvent
UObject * GetOutputObject () const
Return a serialized buffer of change requests made by the user.
bool IsOutputEnabled () const
Returns whether SetOutputObject was called with a valid object.
void OnDiffListSelectionChanged (TSharedPtr< struct FDiffResultItem > TheDiff)
Called when user clicks on an entry in the listview of differences.
void ReportMergeConflicts (const TMap< FString, TMap< FPropertySoftPath, ETreeDiffResult > > &Conflicts)
void SetOutputObject (UObject *OutputObject)
Enables actions like "Choose Left" and "Choose Right" which will modify the OutputObject.
Use NewAsset instead NewAsset NewRevision SLATE_ARGUMENT (bool, ShowAssetNames) SLATE_ARGUMENT(TSharedPtr< SWindow >
Use NewAsset instead SLATE_ARGUMENT (const class UObject *, OldAsset) SLATE_ARGUMENT(const class UObject *
Use NewAsset instead NewAsset SLATE_ARGUMENT (struct FRevisionInfo, OldRevision) SLATE_ARGUMENT(struct FRevisionInfo
Use NewAsset instead NewAsset NewRevision ParentWindow SLATE_ARGUMENT (TSharedPtr< IDetailPropertyExtensionHandler >, ExtensionHandler) SLATE_EVENT(FOnCustomizeDetailsWidget
SLATE_ARGUMENT_DEPRECATED (const class UObject *, AssetOld, 5.5, "Use OldAsset instead") SLATE_ARGUMENT_DEPRECATED(const class UObject *
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< SDetailsDiff > CreateDiffWindow (const UObject *OldObject, const UObject *NewObject, const FRevisionInfo &OldRevision, const FRevisionInfo &NewRevision, const UClass *ObjectClass)
Helper function to create a window that holds a diff widget (default window title)
static TSharedRef< SDetailsDiff > CreateDiffWindow (FText WindowTitle, const UObject *OldObject, const UObject *NewObject, const struct FRevisionInfo &OldRevision, const struct FRevisionInfo &NewRevision)
Helper function to create a window that holds a diff widget.
static TSharedRef< SWidget > DefaultEmptyPanel ()
Helper function for generating an empty widget.
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Data Fields
AssetNew
FRowHighlightColor
Protected Member Functions
DECLARE_MULTICAST_DELEGATE (FOnSetOutputObjectEvent) FOnSetOutputObjectEvent OnOutputObjectSetEvent
FDiffControl GenerateDetailsPanel (const TFunction< const UObject *(const UObject *)> &Redirector=nullptr)
void GenerateDifferencesList ()
Function used to generate the list of differences and the widgets needed to calculate that list.
TSharedRef< SBox > GenerateRevisionInfoWidgetForPanel (TSharedPtr< SWidget > &OutGeneratedWidget, const FText &InRevisionText) const
FName GetCurrentMode () const
bool HasNextDiff () const
Called to determine whether we have a list of differences to cycle through.
bool HasPrevDiff () const
void NextDiff ()
Called when user clicks button to go to next difference.
void OnCloseAssetEditor (UObject *Asset, EAssetEditorCloseReason CloseReason)
Called when editor may need to be closed.
void OnModeChanged (const FName &InNewViewMode) const
void OnObjectReplaced (const FCoreUObjectDelegates::FReplacementObjectMap &Replacements)
void PrevDiff ()
Called when user clicks button to go to prev difference.
void RefreshCurrentModePanel ()
void SetCurrentMode (FName NewMode)
Accessor and event handler for toggling between diff view modes (defaults, components, graph view, interface, macro):
void UpdateTopSectionVisibility (const FName &InNewViewMode) const
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
FDelegateHandle AssetEditorCloseDelegate
FName CurrentMode
TSharedPtr< STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > > > DifferencesTreeView
Tree view that displays the differences, cached for the buttons that iterate the differences:
TMap< FString, TMap< FPropertySoftPath, ETreeDiffResult > > MergeConflicts
TSharedPtr< SBox > ModeContents
Contents widget that we swap when mode changes (defaults, components, etc)
TMap< FName, FDiffControl > ModePanels
Stored references to widgets used to display various parts of an object, from the mode name.
FOnCustomizeDetailsWidget OnCustomizeDetailsWidget
DiffUtils::FOnGenerateCustomDiffEntries OnGenerateCustomDiffEntries
DiffUtils::FOnGenerateCustomDiffEntryWidget OnGenerateCustomDiffEntryWidget
DiffUtils::FOnOrganizeDiffEntries OnOrganizeDiffEntries
UObject * OutputObject = nullptr
If set, actions like "Choose Left" and "Choose Right" will be enabled and modify the OutputObject.
FDetailsDiffPanel PanelNew
FDetailsDiffPanel PanelOld
The two panels used to show the old & new revision.
TArray< TSharedPtr< class FBlueprintDifferenceTreeEntry > > PrimaryDifferencesList
Tree of differences collected across all panels:
TArray< TSharedPtr< class FBlueprintDifferenceTreeEntry > > RealDifferences
List of all differences, cached so that we can iterate only the differences and not labels, etc:
FRowHighlightColor RowHighlightColor
FShouldHighlightRow ShouldHighlightRow
TSharedPtr< FTabManager > TabManager
We can't use the global tab manager because we need to instance the diff control, so we have our own tab manager:
TSharedPtr< SSplitter > TopRevisionInfoWidget
TWeakPtr< SWindow > WeakParentWindow
A pointer to the window holding this.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Additional Inherited Members
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 43 of file SDetailsDiff.h.
Constructor & Destructor Documentation
~SDetailsDiff()
Use NewAsset instead NewAsset NewRevision ParentWindow OnCustomizeDetailsWidget virtual SLATE_EVENT(DiffUtils::FOnGenerateCustomDiffEntries, OnGenerateCustomDiffEntries) SLATE_EVENT(DiffUtils SDetailsDiff::~SDetailsDiff () virtual
Member Function Documentation
CreateDiffWindow() [1/2]
TSharedRef< SDetailsDiff > SDetailsDiff::CreateDiffWindow (const UObject * OldObject, const UObject * NewObject, const FRevisionInfo & OldRevision, const FRevisionInfo & NewRevision, const UClass * ObjectClass) static
Helper function to create a window that holds a diff widget (default window title)
References CreateDiffWindow(), and NewObject().
CreateDiffWindow() [2/2]
TSharedRef< SDetailsDiff > SDetailsDiff::CreateDiffWindow (FText WindowTitle, const UObject * OldObject, const UObject * NewObject, const struct FRevisionInfo & OldRevision, const struct FRevisionInfo & NewRevision) static
Helper function to create a window that holds a diff widget.
References CreateDiffWindow(), and NewObject().
Referenced by CreateDiffWindow(), and CreateDiffWindow().
DECLARE_DELEGATE_OneParam()
SDetailsDiff::DECLARE_DELEGATE_OneParam (FOnCustomizeDetailsWidget , const TSharedRef< IDetailsView > &)
DECLARE_DELEGATE_RetVal_OneParam()
const TUniquePtr< FAsyncDetailViewDiff::DiffNodeType > & SDetailsDiff::DECLARE_DELEGATE_RetVal_OneParam (bool , FShouldHighlightRow , const TUniquePtr< FAsyncDetailViewDiff::DiffNodeType > &) inline
Definition at line 49 of file SDetailsDiff.h.
References DECLARE_DELEGATE_RetVal_OneParam(), and SLATE_BEGIN_ARGS.
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_MULTICAST_DELEGATE()
SDetailsDiff::DECLARE_MULTICAST_DELEGATE (FOnSetOutputObjectEvent) protected
DECLARE_MULTICAST_DELEGATE_OneParam()
SDetailsDiff::DECLARE_MULTICAST_DELEGATE_OneParam (FOnWindowClosedEvent , TSharedRef< SDetailsDiff >)
References DECLARE_MULTICAST_DELEGATE_OneParam().
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
DefaultEmptyPanel()
TSharedRef< SWidget > SDetailsDiff::DefaultEmptyPanel () static
Helper function for generating an empty widget.
References SWidget::SWidget(), and DefaultEmptyPanel().
Referenced by DefaultEmptyPanel().
GenerateDetailsPanel()
FDiffControl SDetailsDiff::GenerateDetailsPanel (const TFunction< const UObject *(const UObject *)> & Redirector = nullptr) protected
GenerateDifferencesList()
void SDetailsDiff::GenerateDifferencesList () protected
Function used to generate the list of differences and the widgets needed to calculate that list.
References GenerateDifferencesList().
Referenced by GenerateDifferencesList().
GenerateRevisionInfoWidgetForPanel()
TSharedRef< SBox > SDetailsDiff::GenerateRevisionInfoWidgetForPanel (TSharedPtr< SWidget > & OutGeneratedWidget, const FText & InRevisionText) const protected
GetCurrentMode()
FName SDetailsDiff::GetCurrentMode () const inline protected
Definition at line 138 of file SDetailsDiff.h.
References CurrentMode.
GetOutputObject()
UObject * SDetailsDiff::GetOutputObject () const
Return a serialized buffer of change requests made by the user.
References GetOutputObject().
Referenced by GetOutputObject().
HasNextDiff()
bool SDetailsDiff::HasNextDiff () const protected
Called to determine whether we have a list of differences to cycle through.
References HasNextDiff().
Referenced by HasNextDiff().
HasPrevDiff()
bool SDetailsDiff::HasPrevDiff () const protected
References HasPrevDiff().
Referenced by HasPrevDiff().
IsOutputEnabled()
bool SDetailsDiff::IsOutputEnabled () const
Returns whether SetOutputObject was called with a valid object.
References IsOutputEnabled().
Referenced by IsOutputEnabled().
NextDiff()
void SDetailsDiff::NextDiff () protected
Called when user clicks button to go to next difference.
References NextDiff().
Referenced by NextDiff().
OnCloseAssetEditor()
void SDetailsDiff::OnCloseAssetEditor (UObject * Asset, EAssetEditorCloseReason CloseReason) protected
Called when editor may need to be closed.
References Asset, and OnCloseAssetEditor().
Referenced by OnCloseAssetEditor().
OnDiffListSelectionChanged()
void SDetailsDiff::OnDiffListSelectionChanged (TSharedPtr< struct FDiffResultItem > TheDiff)
Called when user clicks on an entry in the listview of differences.
References OnDiffListSelectionChanged().
Referenced by OnDiffListSelectionChanged().
OnModeChanged()
void SDetailsDiff::OnModeChanged (const FName & InNewViewMode) const protected
OnObjectReplaced()
void SDetailsDiff::OnObjectReplaced (const FCoreUObjectDelegates::FReplacementObjectMap & Replacements) protected
References OnObjectReplaced().
Referenced by OnObjectReplaced().
PrevDiff()
void SDetailsDiff::PrevDiff () protected
Called when user clicks button to go to prev difference.
References PrevDiff().
Referenced by PrevDiff().
RefreshCurrentModePanel()
void SDetailsDiff::RefreshCurrentModePanel () protected
ReportMergeConflicts()
void SDetailsDiff::ReportMergeConflicts (const TMap< FString, TMap< FPropertySoftPath, ETreeDiffResult > > & Conflicts)
References ReportMergeConflicts().
Referenced by ReportMergeConflicts().
SetCurrentMode()
void SDetailsDiff::SetCurrentMode (FName NewMode) protected
Accessor and event handler for toggling between diff view modes (defaults, components, graph view, interface, macro):
SetOutputObject()
void SDetailsDiff::SetOutputObject (UObject * OutputObject)
Enables actions like "Choose Left" and "Choose Right" which will modify the OutputObject.
References OutputObject, and SetOutputObject().
Referenced by SetOutputObject().
SLATE_ARGUMENT() [1/4]
Use NewAsset instead NewAsset NewRevision SDetailsDiff::SLATE_ARGUMENT (bool , ShowAssetNames)
References SLATE_ARGUMENT(), and SWidget::SWindow.
SLATE_ARGUMENT() [2/4]
Use NewAsset instead SDetailsDiff::SLATE_ARGUMENT (const class UObject * , OldAsset) const
References SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_ARGUMENT().
SLATE_ARGUMENT() [3/4]
Use NewAsset instead NewAsset SDetailsDiff::SLATE_ARGUMENT (struct FRevisionInfo , OldRevision)
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [4/4]
Use NewAsset instead NewAsset NewRevision ParentWindow SDetailsDiff::SLATE_ARGUMENT (TSharedPtr< IDetailPropertyExtensionHandler > , ExtensionHandler)
References FRowHighlightColor, OnCustomizeDetailsWidget, OnGenerateCustomDiffEntries, OnGenerateCustomDiffEntryWidget, OnOrganizeDiffEntries, RowHighlightColor, ShouldHighlightRow, SLATE_ARGUMENT(), SLATE_END_ARGS, and SLATE_EVENT.
SLATE_ARGUMENT_DEPRECATED()
SDetailsDiff::SLATE_ARGUMENT_DEPRECATED (const class UObject * , AssetOld , 5. 5, "Use OldAsset instead") const
Tick()
virtual void SDetailsDiff::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
References Tick().
Referenced by Tick().
UpdateTopSectionVisibility()
void SDetailsDiff::UpdateTopSectionVisibility (const FName & InNewViewMode) const protected
Field Documentation
AssetEditorCloseDelegate
FDelegateHandle SDetailsDiff::AssetEditorCloseDelegate protected
Definition at line 185 of file SDetailsDiff.h.
AssetNew
SDetailsDiff::AssetNew
Definition at line 53 of file SDetailsDiff.h.
CurrentMode
FName SDetailsDiff::CurrentMode protected
Definition at line 143 of file SDetailsDiff.h.
Referenced by GetCurrentMode().
DifferencesTreeView
TSharedPtr< STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > > > SDetailsDiff::DifferencesTreeView protected
Tree view that displays the differences, cached for the buttons that iterate the differences:
Definition at line 177 of file SDetailsDiff.h.
FRowHighlightColor
SDetailsDiff::FRowHighlightColor
Definition at line 48 of file SDetailsDiff.h.
Referenced by SLATE_ARGUMENT().
MergeConflicts
TMap<FString, TMap<FPropertySoftPath, ETreeDiffResult> > SDetailsDiff::MergeConflicts protected
Definition at line 187 of file SDetailsDiff.h.
ModeContents
TSharedPtr<SBox> SDetailsDiff::ModeContents protected
Contents widget that we swap when mode changes (defaults, components, etc)
Definition at line 163 of file SDetailsDiff.h.
ModePanels
TMap<FName, FDiffControl> SDetailsDiff::ModePanels protected
Stored references to widgets used to display various parts of an object, from the mode name.
Definition at line 180 of file SDetailsDiff.h.
OnCustomizeDetailsWidget
FOnCustomizeDetailsWidget SDetailsDiff::OnCustomizeDetailsWidget protected
Definition at line 155 of file SDetailsDiff.h.
Referenced by SLATE_ARGUMENT().
OnGenerateCustomDiffEntries
DiffUtils::FOnGenerateCustomDiffEntries SDetailsDiff::OnGenerateCustomDiffEntries protected
Definition at line 156 of file SDetailsDiff.h.
Referenced by SLATE_ARGUMENT().
OnGenerateCustomDiffEntryWidget
DiffUtils::FOnGenerateCustomDiffEntryWidget SDetailsDiff::OnGenerateCustomDiffEntryWidget protected
Definition at line 157 of file SDetailsDiff.h.
Referenced by SLATE_ARGUMENT().
OnOrganizeDiffEntries
DiffUtils::FOnOrganizeDiffEntries SDetailsDiff::OnOrganizeDiffEntries protected
Definition at line 158 of file SDetailsDiff.h.
Referenced by SLATE_ARGUMENT().
OutputObject
UObject* SDetailsDiff::OutputObject = nullptr protected
If set, actions like "Choose Left" and "Choose Right" will be enabled and modify the OutputObject.
Definition at line 150 of file SDetailsDiff.h.
Referenced by SetOutputObject().
PanelNew
FDetailsDiffPanel SDetailsDiff::PanelNew protected
Definition at line 147 of file SDetailsDiff.h.
PanelOld
FDetailsDiffPanel SDetailsDiff::PanelOld protected
The two panels used to show the old & new revision.
Definition at line 146 of file SDetailsDiff.h.
PrimaryDifferencesList
TArray< TSharedPtr<class FBlueprintDifferenceTreeEntry> > SDetailsDiff::PrimaryDifferencesList protected
Tree of differences collected across all panels:
Definition at line 171 of file SDetailsDiff.h.
RealDifferences
TArray< TSharedPtr<class FBlueprintDifferenceTreeEntry> > SDetailsDiff::RealDifferences protected
List of all differences, cached so that we can iterate only the differences and not labels, etc:
Definition at line 174 of file SDetailsDiff.h.
RowHighlightColor
FRowHighlightColor SDetailsDiff::RowHighlightColor protected
Definition at line 160 of file SDetailsDiff.h.
Referenced by SLATE_ARGUMENT().
ShouldHighlightRow
FShouldHighlightRow SDetailsDiff::ShouldHighlightRow protected
Definition at line 159 of file SDetailsDiff.h.
Referenced by SLATE_ARGUMENT().
TabManager
TSharedPtr<FTabManager> SDetailsDiff::TabManager protected
We can't use the global tab manager because we need to instance the diff control, so we have our own tab manager:
Definition at line 168 of file SDetailsDiff.h.
TopRevisionInfoWidget
TSharedPtr<SSplitter> SDetailsDiff::TopRevisionInfoWidget protected
Definition at line 165 of file SDetailsDiff.h.
WeakParentWindow
TWeakPtr<SWindow> SDetailsDiff::WeakParentWindow protected
A pointer to the window holding this.
Definition at line 183 of file SDetailsDiff.h.
The documentation for this class was generated from the following file:
SDetailsDiff.h