Unreal Engine 5.6 C++ API: VirtualTextureScalability Namespace Reference
VirtualTextureScalability Namespace Reference
Functions
uint32 GetKeepDirtyPageMappedFrameThreshold ()
Get the number of frames a page must be unused, before it is unmapped instead of updated during RVT page invalidation.
int32 GetMaxAllocatedVTReleasedPerFrame ()
Get max allocated virtual textures to release per frame.
int32 GetMaxAnisotropy ()
Get maximum anisotropy when virtual texture sampling.
int32 GetMaxContinuousUpdatesPerFrame ()
Get max update rate of already mapped virtual texture pages.
int32 GetMaxPagesProducedPerFrame ()
Get max produce rate to virtual textures.
int32 GetMaxUploadsPerFrame ()
Get max upload rate to virtual textures.
int32 GetMaxUploadsPerFrameForStreamingVT ()
Get max upload rate to streaming virtual textures.
uint32 GetPageFreeThreshold ()
Get the number of frames a page must be unused, before it's considered free.
int32 GetRuntimeVirtualTextureSizeBias ()
Get resolution bias for runtime virtual textures.
int32 GetRuntimeVirtualTextureSizeBias (uint32 GroupIndex)
Get resolution bias for runtime virtual textures.
uint32 GetVirtualTextureFeedbackFactor ()
Get the size of the virtual texture feedback tiles.
bool IsAnisotropicFilteringEnabled ()
Is HW Anisotropic filtering enabled for VT.
UE_DEPRECATED (5.4, "Use VirtualTexturePool::GetConfigHash() instead.") 1 uint32 GetPhysicalPoolSettingsHash()
UE_DEPRECATED (5.4, "Use VirtualTexturePool::GetPoolSizeScale() instead.") 1 float GetPoolSizeScale()
UE_DEPRECATED (5.4, "Use VirtualTexturePool::GetSplitPhysicalPoolSize() instead.") 1 int32 GetSplitPhysicalPoolSize()
Function Documentation
GetKeepDirtyPageMappedFrameThreshold()
uint32 VirtualTextureScalability::GetKeepDirtyPageMappedFrameThreshold ()
Get the number of frames a page must be unused, before it is unmapped instead of updated during RVT page invalidation.
GetMaxAllocatedVTReleasedPerFrame()
int32 VirtualTextureScalability::GetMaxAllocatedVTReleasedPerFrame ()
Get max allocated virtual textures to release per frame.
GetMaxAnisotropy()
int32 VirtualTextureScalability::GetMaxAnisotropy ()
Get maximum anisotropy when virtual texture sampling.
This is also clamped per virtual texture according to the tile border size.
GetMaxContinuousUpdatesPerFrame()
int32 VirtualTextureScalability::GetMaxContinuousUpdatesPerFrame ()
Get max update rate of already mapped virtual texture pages.
GetMaxPagesProducedPerFrame()
int32 VirtualTextureScalability::GetMaxPagesProducedPerFrame ()
Get max produce rate to virtual textures.
GetMaxUploadsPerFrame()
int32 VirtualTextureScalability::GetMaxUploadsPerFrame ()
Get max upload rate to virtual textures.
GetMaxUploadsPerFrameForStreamingVT()
int32 VirtualTextureScalability::GetMaxUploadsPerFrameForStreamingVT ()
Get max upload rate to streaming virtual textures.
May return 0 which means SVTs aren't budgeted separately.
GetPageFreeThreshold()
uint32 VirtualTextureScalability::GetPageFreeThreshold ()
Get the number of frames a page must be unused, before it's considered free.
GetRuntimeVirtualTextureSizeBias() [1/2]
int32 VirtualTextureScalability::GetRuntimeVirtualTextureSizeBias ()
Get resolution bias for runtime virtual textures.
GetRuntimeVirtualTextureSizeBias() [2/2]
int32 VirtualTextureScalability::GetRuntimeVirtualTextureSizeBias (uint32 GroupIndex)
Get resolution bias for runtime virtual textures.
GetVirtualTextureFeedbackFactor()
uint32 VirtualTextureScalability::GetVirtualTextureFeedbackFactor ()
Get the size of the virtual texture feedback tiles.
IsAnisotropicFilteringEnabled()
bool VirtualTextureScalability::IsAnisotropicFilteringEnabled ()
Is HW Anisotropic filtering enabled for VT.
UE_DEPRECATED() [1/3]
VirtualTextureScalability::UE_DEPRECATED (5. 4, "Use VirtualTexturePool::GetConfigHash() instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
VirtualTextureScalability::UE_DEPRECATED (5. 4, "Use VirtualTexturePool::GetPoolSizeScale() instead.")
References UE_DEPRECATED().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
VirtualTextureScalability::UE_DEPRECATED (5. 4, "Use VirtualTexturePool::GetSplitPhysicalPoolSize() instead.")
References UE_DEPRECATED().