Unreal Engine 5.6 C++ API: FStructuredArchiveSlot Class Reference
FStructuredArchiveSlot Class Reference final
Contains a value in the archive; either a field or array/map element.
#include "StructuredArchiveSlots.h"
Public Member Functions
FORCEINLINE FStructuredArchiveArray EnterArray (int32 &Num)
FORCEINLINE FStructuredArchiveSlot EnterAttribute (FArchiveFieldName AttributeName)
FORCEINLINE FStructuredArchiveMap EnterMap (int32 &Num)
FORCEINLINE FStructuredArchiveRecord EnterRecord ()
FORCEINLINE FStructuredArchiveStream EnterStream ()
bool IsFilled () const
FORCEINLINE void operator<< (bool &Value)
FORCEINLINE void operator<< (double &Value)
template<typename EnumType, std::enable_if_t< TIsEnumClass< EnumType >::Value, int > = 0>
FORCEINLINE void operator<< (EnumType &Value)
FORCEINLINE void operator<< (FLazyObjectPtr &Value)
FORCEINLINE void operator<< (float &Value)
FORCEINLINE void operator<< (FName &Value)
FORCEINLINE void operator<< (FObjectPtr &Value)
FORCEINLINE void operator<< (FSoftObjectPath &Value)
FORCEINLINE void operator<< (FSoftObjectPtr &Value)
FORCEINLINE void operator<< (FString &Value)
FORCEINLINE void operator<< (FText &Value)
FORCEINLINE void operator<< (FWeakObjectPtr &Value)
FORCEINLINE void operator<< (int16 &Value)
FORCEINLINE void operator<< (int32 &Value)
FORCEINLINE void operator<< (int64 &Value)
FORCEINLINE void operator<< (int8 &Value)
template<typename T>
FORCEINLINE void operator<< (TEnumAsByte< T > &Value)
template<typename T>
FORCEINLINE void operator<< (UE::StructuredArchive::Private::TNamedAttribute< T > Item)
template<typename T>
FORCEINLINE void operator<< (UE::StructuredArchive::Private::TOptionalNamedAttribute< T > Item)
FORCEINLINE void operator<< (uint16 &Value)
FORCEINLINE void operator<< (uint32 &Value)
FORCEINLINE void operator<< (uint64 &Value)
FORCEINLINE void operator<< (uint8 &Value)
FORCEINLINE void operator<< (UObject *&Value)
FORCEINLINE void operator<< (UTF32CHAR &Value)
FORCEINLINE void Serialize (TArray< uint8 > &Data)
FORCEINLINE void Serialize (void *Data, uint64 DataSize)
FORCEINLINE TOptional< FStructuredArchiveSlot > TryEnterAttribute (FArchiveFieldName AttributeName, bool bEnterWhenWriting)
Public Member Functions inherited from UE::StructuredArchive::Private::FSlotBase
FORCEINLINE FSlotBase (EPrivateToken, FStructuredArchive &InStructuredArchive)
const FArchiveState & GetArchiveState () const
FArchive & GetUnderlyingArchive () const
Private Member Functions
FORCEINLINE FSlotBase (EPrivateToken, FStructuredArchive &InStructuredArchive)
Private Attributes
friend FStructuredArchiveSlot
friend FStructuredArchive
friend FStructuredArchiveArray
friend FStructuredArchiveChildReader
friend FStructuredArchiveMap
friend FStructuredArchiveRecord
friend FStructuredArchiveStream
Additional Inherited Members
Protected Types inherited from UE::StructuredArchive::Private::FSlotBase
enum class EPrivateToken
Protected Attributes inherited from UE::StructuredArchive::Private::FSlotBase
FStructuredArchive & StructuredArchive
Detailed Description
Contains a value in the archive; either a field or array/map element.
A slot does not know it's name or location, and can merely have a value serialized into it. That value may be a literal (eg. int, float) or compound object (eg. object, array, map).
Definition at line 51 of file StructuredArchiveSlots.h.
Member Function Documentation
EnterArray()
FORCEINLINE FStructuredArchiveArray FStructuredArchiveSlot::EnterArray (int32 & Num)
Definition at line 257 of file StructuredArchiveSlots.h.
References FORCEINLINE, FStructuredArchiveArray, UE::StructuredArchive::Private::GetFormatterImpl(), Num, and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by FStructuredArchiveRecord::EnterArray(), operator<<(), operator<<(), and UE::Core::PagedArray::Private::SerializeStructured().
EnterAttribute()
FORCEINLINE FStructuredArchiveSlot FStructuredArchiveSlot::EnterAttribute (FArchiveFieldName AttributeName)
Definition at line 274 of file StructuredArchiveSlots.h.
References FStructuredArchiveSlot, FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by operator<<().
EnterMap()
FORCEINLINE FStructuredArchiveMap FStructuredArchiveSlot::EnterMap (int32 & Num)
Definition at line 268 of file StructuredArchiveSlots.h.
References FORCEINLINE, FStructuredArchiveMap, UE::StructuredArchive::Private::GetFormatterImpl(), Num, and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by FStructuredArchiveRecord::EnterMap().
EnterRecord()
FORCEINLINE FStructuredArchiveRecord FStructuredArchiveSlot::EnterRecord ()
Definition at line 252 of file StructuredArchiveSlots.h.
References FORCEINLINE, FStructuredArchiveRecord, and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by FStructuredArchiveRecord::EnterRecord(), FLinearColor::operator<<, FTopLevelAssetPath::operator<<, TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::operator<<, UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::TBox< double >::operator<<, UE::Math::TIntPoint< IntType >::operator<<, UE::Math::TIntVector2< int32 >::operator<<, UE::Math::TIntVector3< int32 >::operator<<, UE::Math::TIntVector4< int32 >::operator<<, FTextId::SerializeAsString(), FTextId::SerializeDiscardHash(), and FTextId::SerializeWithHash().
EnterStream()
FORCEINLINE FStructuredArchiveStream FStructuredArchiveSlot::EnterStream ()
Definition at line 263 of file StructuredArchiveSlots.h.
References FORCEINLINE, FStructuredArchiveStream, and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by FStructuredArchiveRecord::EnterStream(), UE::Math::operator<<(), UE::Math::operator<<(), FProperty::SerializeBinProperty(), FProperty::SerializeNonMatchingBinProperty(), and UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::SerializeStructured().
FSlotBase()
FORCEINLINE UE::StructuredArchive::Private::FSlotBase::FSlotBase (EPrivateToken , FStructuredArchive & InStructuredArchive) inline explicit private
Definition at line 83 of file StructuredArchiveSlotBase.h.
IsFilled()
bool FStructuredArchiveSlot::IsFilled () const
operator<<() [1/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (bool & Value)
Definition at line 347 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [2/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (double & Value)
Definition at line 342 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [3/25]
template<typename EnumType, std::enable_if_t< TIsEnumClass< EnumType >::Value, int > = 0> FORCEINLINE void FStructuredArchiveSlot::operator<< (EnumType & Value) inline
Definition at line 99 of file StructuredArchiveSlots.h.
References FORCEINLINE, and Value.
operator<<() [4/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FLazyObjectPtr & Value)
Definition at line 394 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [5/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (float & Value)
Definition at line 337 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [6/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FName & Value)
Definition at line 357 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [7/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FObjectPtr & Value)
Definition at line 399 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [8/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FSoftObjectPath & Value)
Definition at line 384 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [9/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FSoftObjectPtr & Value)
Definition at line 389 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [10/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FString & Value)
Definition at line 352 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [11/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FText & Value)
Definition at line 374 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [12/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (FWeakObjectPtr & Value)
Definition at line 379 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [13/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (int16 & Value)
Definition at line 322 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [14/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (int32 & Value)
Definition at line 327 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [15/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (int64 & Value)
Definition at line 332 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [16/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (int8 & Value)
Definition at line 317 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [17/25]
template<typename T> FORCEINLINE void FStructuredArchiveSlot::operator<< (TEnumAsByte< T > & Value) inline
Definition at line 88 of file StructuredArchiveSlots.h.
References FORCEINLINE, and Value.
operator<<() [18/25]
template<typename T> FORCEINLINE void FStructuredArchiveSlot::operator<< (UE::StructuredArchive::Private::TNamedAttribute< T > Item) inline
Definition at line 105 of file StructuredArchiveSlots.h.
References EnterAttribute(), FORCEINLINE, and Item.
operator<<() [19/25]
template<typename T> FORCEINLINE void FStructuredArchiveSlot::operator<< (UE::StructuredArchive::Private::TOptionalNamedAttribute< T > Item) inline
Definition at line 111 of file StructuredArchiveSlots.h.
References Attribute, FORCEINLINE, Item, and TryEnterAttribute().
operator<<() [20/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (uint16 & Value)
Definition at line 297 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [21/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (uint32 & Value)
Definition at line 302 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [22/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (uint64 & Value)
Definition at line 312 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [23/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (uint8 & Value)
Definition at line 292 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [24/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (UObject *& Value)
Definition at line 362 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
operator<<() [25/25]
FORCEINLINE void FStructuredArchiveSlot::operator<< (UTF32CHAR & Value)
Definition at line 307 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and Value.
Serialize() [1/2]
FORCEINLINE void FStructuredArchiveSlot::Serialize (TArray< uint8 > & Data)
Definition at line 404 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by operator<<().
Serialize() [2/2]
FORCEINLINE void FStructuredArchiveSlot::Serialize (void * Data, uint64 DataSize)
Definition at line 409 of file StructuredArchiveSlots.h.
References DataSize, FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
TryEnterAttribute()
FORCEINLINE TOptional< FStructuredArchiveSlot > FStructuredArchiveSlot::TryEnterAttribute (FArchiveFieldName AttributeName, bool bEnterWhenWriting)
Definition at line 280 of file StructuredArchiveSlots.h.
References FORCEINLINE, UE::StructuredArchive::Private::GetFormatterImpl(), InPlace, UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and TryEnterAttribute().
Referenced by operator<<(), and TryEnterAttribute().
Field Documentation
FStructuredArchiveSlot
friend FStructuredArchiveSlot::FStructuredArchiveSlot private
Definition at line 130 of file StructuredArchiveSlots.h.
References FStructuredArchiveSlot.
Referenced by FStructuredArchiveSlot, and EnterAttribute().
FStructuredArchive
friend FStructuredArchiveSlot::FStructuredArchive private
Definition at line 128 of file StructuredArchiveSlots.h.
FStructuredArchiveArray
friend FStructuredArchiveSlot::FStructuredArchiveArray private
Definition at line 132 of file StructuredArchiveSlots.h.
Referenced by EnterArray().
FStructuredArchiveChildReader
friend FStructuredArchiveSlot::FStructuredArchiveChildReader private
Definition at line 129 of file StructuredArchiveSlots.h.
FStructuredArchiveMap
friend FStructuredArchiveSlot::FStructuredArchiveMap private
Definition at line 134 of file StructuredArchiveSlots.h.
Referenced by EnterMap().
FStructuredArchiveRecord
friend FStructuredArchiveSlot::FStructuredArchiveRecord private
Definition at line 131 of file StructuredArchiveSlots.h.
Referenced by EnterRecord().
FStructuredArchiveStream
friend FStructuredArchiveSlot::FStructuredArchiveStream private
Definition at line 133 of file StructuredArchiveSlots.h.
Referenced by EnterStream().
The documentation for this class was generated from the following file:
StructuredArchiveSlots.h