Unreal Engine 5.6 C++ API: Metasound::TDataFactory< DataType, CreatorType > Struct Template Reference
Metasound::TDataFactory< DataType, CreatorType > Struct Template Reference
A base factory type for creating objects related to Metasound DataTypes.
#include "MetasoundDataFactory.h"
Public Types
using FInternalFactory = DataFactoryPrivate::TDataFactoryInternal<DataType, CreatorType>
Static Public Member Functions
template<typename... ArgTypes>
static auto CreateAny (const FOperatorSettings &InSettings, ArgTypes &&... Args)
Create the object using any supported constructor.
template<typename... ArgTypes>
static auto CreateExplicit (const FOperatorSettings &InSettings, ArgTypes &&... Args)
Create the object using only a constructor which exactly matches the arguments to this factory method.
template<typename... ArgTypes>
static auto CreateExplicitArgs (const FOperatorSettings &InSettings, ArgTypes &&... Args)
Create the object using only constructors which utilize all arguments in the parameter pack (ArgTypes...).
Detailed Description
template<typename DataType, typename CreatorType>
struct Metasound::TDataFactory< DataType, CreatorType >
A base factory type for creating objects related to Metasound DataTypes.
TDataFactory provides a unified interface for constructing objects using a FOperatorSettings and a parameter pack of arguments. The various factory methods determine how strictly the DataType constructors must match the arguments to the factory method.
Template Parameters
DataType - The registered metasound data type which defines the supported constructors.
CreatorType - A class providing a static "CreateNew(...)" function which accepts the forwarded arguments and returns an object.
Definition at line 883 of file MetasoundDataFactory.h.
Member Typedef Documentation
FInternalFactory
template<typename DataType, typename CreatorType> using Metasound::TDataFactory< DataType, CreatorType >::FInternalFactory = DataFactoryPrivate::TDataFactoryInternal<DataType, CreatorType>
Definition at line 885 of file MetasoundDataFactory.h.
Member Function Documentation
CreateAny()
template<typename DataType, typename CreatorType> template<typename... ArgTypes> auto Metasound::TDataFactory< DataType, CreatorType >::CreateAny (const FOperatorSettings & InSettings, ArgTypes &&... Args) inline static
Create the object using any supported constructor.
Definition at line 889 of file MetasoundDataFactory.h.
References Forward().
CreateExplicit()
template<typename DataType, typename CreatorType> template<typename... ArgTypes> auto Metasound::TDataFactory< DataType, CreatorType >::CreateExplicit (const FOperatorSettings & InSettings, ArgTypes &&... Args) inline static
Create the object using only a constructor which exactly matches the arguments to this factory method.
Definition at line 911 of file MetasoundDataFactory.h.
References Forward().
CreateExplicitArgs()
template<typename DataType, typename CreatorType> template<typename... ArgTypes> auto Metasound::TDataFactory< DataType, CreatorType >::CreateExplicitArgs (const FOperatorSettings & InSettings, ArgTypes &&... Args) inline static
Create the object using only constructors which utilize all arguments in the parameter pack (ArgTypes...).
Definition at line 930 of file MetasoundDataFactory.h.
References Forward().
The documentation for this struct was generated from the following file:
MetasoundDataFactory.h