Unreal Engine 5.6 C++ API: LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false > Struct Template Reference
LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false > Struct Template Reference final
Public Member Functions
template<typename CallableT>
TTaskDelegateImpl (CallableT &&Callable, void *InlineData)
ReturnType Call (void *InlineData, ParamTypes... Params) const override
ReturnType CallAndMove (ThisClass &Destination, void *InlineData, uint32 DestInlineSize, ParamTypes... Params) override
uint32 DelegateSize () const override
void Destroy (void *InlineData) override
bool IsHeapAllocated () const override
bool IsSet () const override
void Move (TTaskDelegateBase &DstWrapper, void *DstData, void *SrcData, uint32 DestInlineSize) override
Detailed Description
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes>
template<typename TCallableType>
struct LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >
Definition at line 134 of file TaskDelegate.h.
Constructor & Destructor Documentation
TTaskDelegateImpl()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> template<typename CallableT> LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::TTaskDelegateImpl (CallableT && Callable, void * InlineData) inline
Definition at line 137 of file TaskDelegate.h.
References TTaskDelegateImpl(), Forward(), and Value.
Referenced by TTaskDelegateImpl(), and Move().
Member Function Documentation
Call()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> ReturnType LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::Call (void * InlineData, ParamTypes... Params) const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 159 of file TaskDelegate.h.
References Invoke(), and Params.
Referenced by CallAndMove().
CallAndMove()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> ReturnType LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::CallAndMove (ThisClass & Destination, void * InlineData, uint32 DestInlineSize, ParamTypes... Params) inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 165 of file TaskDelegate.h.
References Call(), Move, ON_SCOPE_EXIT, and Params.
DelegateSize()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> uint32 LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::DelegateSize () const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 190 of file TaskDelegate.h.
Destroy()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> void LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::Destroy (void * InlineData) inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 174 of file TaskDelegate.h.
IsHeapAllocated()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> bool LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::IsHeapAllocated () const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 180 of file TaskDelegate.h.
IsSet()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> bool LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::IsSet () const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 185 of file TaskDelegate.h.
Move()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> void LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::Move (TTaskDelegateBase & DstWrapper, void * DstData, void * SrcData, uint32 DestInlineSize) inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 145 of file TaskDelegate.h.
References TTaskDelegateImpl(), and MoveTemp().
The documentation for this struct was generated from the following file:
TaskDelegate.h