Unreal Engine 5.6 C++ API: UObject Class Reference
UObject Class Reference
The base class of all UE objects.
#include "Object.h"
Data Structures
struct FAssetRegistryTag
Struct used by GetAssetRegistryTags() to return tag info.
struct FAssetRegistryTagMetadata
Additional data pertaining to asset registry tags used by the editor.
struct Object_eventExecuteUbergraph_Parms
Wrapper struct to hold the entrypoint in the right memory address.
Public Types
enum class ENetFields_Private { NETFIELD_REP_START = 0 , NETFIELD_REP_END = -1 }
using FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Public Member Functions
void AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const
Returns whether native properties are identical to the one of the passed in component.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform)
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
virtual void BeginDestroy ()
Called before destroying the object.
virtual void BuildSubobjectMapping (UObject *OtherObject, TMap< UObject *, UObject * > &ObjectMapping) const
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
void CallAddReferencedObjects (FReferenceCollector &Collector)
Helper function to call AddReferencedObjects for this object's class.
void CallFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
Internal VM method for executing a function.
bool CallFunctionByNameWithArguments (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor, bool bForceCallWithNonExec=false)
Handle calling a function by name when executed from the console or a command line.
virtual bool CallRemoteFunction (UFunction *Function, void *Parms, struct FOutParmRec *OutParms, FFrame *Stack)
Call the actor's function remotely.
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain) const
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
virtual bool CanEditChange (const FProperty *InProperty) const
Called by the editor to query whether a property of this object is allowed to be modified.
bool CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
bool CheckDefaultSubobjects (bool bForceCheck=false) const
Checks default sub-object assumptions.
virtual void ClearAllCachedCookedPlatformData ()
Clear all cached cooked platform data.
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform)
Clears cached cooked platform data for specific platform.
virtual void CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext)
Collect any save override state.
bool ConditionalBeginDestroy ()
Called before destroying the object.
bool ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
void ConditionalPostLoad ()
PostLoad if needed.
void ConditionalPostLoadSubobjects (struct FObjectInstancingGraph *OuterInstanceGraph=NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
virtual bool ConformSparseClassDataStruct (UScriptStruct *SourceSparseClassDataStruct, void *SourceSparseClassData) const
void CookAdditionalFiles (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
TSharedPtr< ITransactionObjectAnnotation > CreateAndRestoreTransactionAnnotation (FArchive &Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetPreviewPlatform, FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
void DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
void ExecuteUbergraph (int32 EntryPoint)
Execute the ubergraph from a specific entry point.
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent)
Exports the property values for the specified object as text to the output device.
UFunction * FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
UFunction * FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
TSharedPtr< ITransactionObjectAnnotation > FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
virtual void FinishDestroy ()
Called to finish destroying the object.
virtual void GetAdditionalAssetDataObjectsForCook (FArchiveCookContext &CookContext, TArray< UObject * > &OutObjects) const
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
UObject * GetArchetype () const
Return the template this object is based on.
void GetArchetypeInstances (TArray< UObject * > &Instances)
Builds a list of objects which have this object in their archetype chain.
virtual void GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > &OutMetadata) const
Gathers a collection of asset registry tag metadata.
void GetAssetRegistryTags (FAssetData &Out) const
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
void GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData &Out) const
Gathers a list of asset registry tags for an FAssetData.
virtual const TCHAR * GetConfigOverridePlatform () const
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
FString GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
virtual FString GetDesc ()
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
FString GetDetailedInfo () const
This will return detail info about this specific object.
virtual FName GetExporterName (void)
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
virtual void GetExtendedAssetRegistryTagsForSave (const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &OutTags) const
Temporary interim solution to gather asset registry data at save time only.
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack)
Return the space this function should be called.
FString GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
virtual void GetLifetimeReplicatedProps (TArray< class FLifetimeProperty > &OutLifetimeProps) const
Returns properties that are replicated for the lifetime of the actor channel.
virtual bool GetNativePropertyValues (TMap< FString, FString > &out_PropertyValues, uint32 ExportFlags=0) const
Callback for retrieving a textual representation of natively serialized properties.
virtual uint64 GetNetPushIdDynamic () const
Should only ever be used by internal systems.
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
Called during cooking.
virtual void GetPrestreamPackages (TArray< UObject * > &OutPrestream)
Called during cooking.
virtual FPrimaryAssetId GetPrimaryAssetId () const
Returns an Type:Name pair representing the PrimaryAssetId for this object.
FString GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const
Called when this object begins replicating to initialize the state of custom property conditions.
SIZE_T GetResourceSizeBytes (EResourceSizeMode::Type Mode)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
virtual FRestoreForUObjectOverwrite * GetRestoreForUObjectOverwrite ()
Save information for StaticAllocateObject in the case of overwriting an existing object.
UScriptStruct * GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
virtual void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &ObjList)
Returns a list of sub-objects that have stable names for networking.
virtual bool HasNonEditorOnlyReferences () const
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
template<class T>
FORCEINLINE bool Implements () const
Returns true if this object implements the interface T, false otherwise.
template<class T>
bool Implements () const
Returns true if this object implements the interface T, false otherwise.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn)
Exports the property values for the specified object as text to the output device.
void InstanceSubobjectTemplates (struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
virtual bool IsAsset () const
Returns true if this object is considered an asset.
bool IsBasedOnArchetype (const UObject *const SomeObject) const
Determine if this object has SomeObject in its archetype chain.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform)
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
virtual bool IsCapturingAsRootObjectForTransaction () const
Method to disable the sub object special handling in the transaction buffer for this object.
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const
Generic function to validate objects during changelist validations, etc.
virtual bool IsEditorOnly () const
Called during saving to determine if the object is forced to be editor only or not.
virtual bool IsFullNameStableForNetworking () const
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
bool IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
virtual bool IsLocalizedResource () const
Returns true if this object is considered a localized resource.
virtual bool IsNameStableForNetworking () const
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsPostLoadThreadSafe () const
Called during async load to determine if PostLoad can be called on the loading thread.
virtual bool IsReadyForAsyncPostLoad () const
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
virtual bool IsReadyForFinishDestroy ()
Called to check if the object is ready for FinishDestroy.
virtual bool IsSafeForRootSet () const
Returns true if this object is safe to add to the root set.
bool IsSelected () const
Test the selection state of a UObject.
virtual bool IsSupportedForNetworking () const
IsSupportedForNetworking means an object can be referenced over the network.
void LoadConfig (UClass *ConfigClass=nullptr, const TCHAR *Filename=nullptr, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > *OutAccessedKeys=nullptr)
Imports property values from an .ini file.
virtual void LoadedFromAnotherClass (const FName &OldClassName)
Called when the object was loaded from another class via active class redirects.
virtual void MarkAsEditorOnlySubobject ()
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
virtual bool Modify (bool bAlwaysMarkDirty=true)
Note that the object will be modified.
virtual void MoveDataToSparseClassDataStruct () const
virtual bool NeedsLoadForClient () const
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForEditorGame () const
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
virtual bool NeedsLoadForServer () const
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForTargetPlatform (const class ITargetPlatform *TargetPlatform) const
Called during saving to determine the load flags to save with the object.
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &Context)
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
void OutputReferencers (FOutputDevice &Ar, FReferencerInformationList *Referencers=NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
virtual void OverrideConfigSection (FString &SectionName)
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
virtual void OverridePerObjectConfigSection (FString &SectionName)
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
void ParseParms (const TCHAR *Parms)
Import an object from a file.
virtual void PostCDOCompiled (const FPostCDOCompiledContext &Context)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
virtual void PostCDOContruct ()
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
virtual void PostDuplicate (bool bDuplicateForPIE)
Called after duplication & serialization and before PostLoad.
virtual void PostDuplicate (EDuplicateMode::Type DuplicateMode)
void PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
virtual void PostEditChangeChainProperty (struct FPropertyChangedChainEvent &PropertyChangedEvent)
This alternate version of PostEditChange is called when properties inside structs are modified.
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent)
Called when a property on this object has been modified externally.
virtual void PostEditImport ()
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
virtual void PostEditUndo ()
Called after applying a transaction to the object.
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation)
Called after applying a transaction to the object in cases where transaction annotation was provided.
virtual void PostInitProperties ()
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
virtual void PostLinkerChange ()
Called in response to the linker changing, this can only happen in the editor.
virtual void PostLoad ()
Do any object-specific cleanup required immediately after loading an object.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph)
Instances components for objects being loaded from disk, if necessary.
virtual void PostNetReceive ()
Called right after receiving a bunch.
virtual void PostReinitProperties ()
Called after properties are overwritten, including after subobjects initialization from a CDO.
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded)
Called from ReloadConfig after the object has reloaded its configuration data.
virtual void PostRename (UObject *OldOuter, const FName OldName)
Called at the end of Rename(), but only if the rename was actually carried out.
virtual void PostRepNotifies ()
Called right after calling all OnRep notifies (called even when there are no notifies)
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent)
Called after the object has been transacted in some way.
virtual void PreDestroyFromReplication ()
Called right before being marked for destruction due to network replication.
virtual void PreDuplicate (FObjectDuplicationParameters &DupParams)
Called before duplication.
virtual void PreEditChange (class FEditPropertyChain &PropertyAboutToChange)
This alternate version of PreEditChange is called when properties inside structs are modified.
virtual void PreEditChange (FProperty *PropertyAboutToChange)
This is called when a property is about to be modified externally.
virtual void PreEditUndo ()
Called before applying a transaction to the object.
virtual void PreNetReceive ()
Called right before receiving a bunch.
virtual void PreSave (FObjectPreSaveContext SaveContext)
Presave function.
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual bool ProcessConsoleExec (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor)
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
virtual void ProcessEvent (UFunction *Function, void *Parms)
Called by VM to execute a UFunction with a filled in UStruct of parameters.
void PropagatePostEditChange (TArray< UObject * > &AffectedObjects, FPropertyChangedChainEvent &PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
void PropagatePreEditChange (TArray< UObject * > &AffectedObjects, FEditPropertyChain &PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
virtual UClass * RegenerateClass (UClass *ClassToRegenerate, UObject *PreviousCDO)
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
void ReinitializeProperties (UObject *SourceObject=NULL, struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
void ReloadConfig (UClass *ConfigClass=NULL, const TCHAR *Filename=NULL, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
virtual bool Rename (const TCHAR *NewName=nullptr, UObject *NewOuter=nullptr, ERenameFlags Flags=REN_None)
Rename this object to a unique name, or change its outer.
virtual bool ResolveSubobject (const TCHAR *SubObjectPath, UObject *&OutObject, bool bLoadIfExists)
Called to defer loading a subobject to its top-level container object.
void RetrieveReferencers (TArray< FReferencerInformation > *OutInternalReferencers, TArray< FReferencerInformation > *OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
void SaveConfig (uint64 RequiredPropertyFlags=CPF_Config, const TCHAR *Filename=nullptr, FConfigCacheIni *Config=GConfig, bool bAllowCopyToDefaultObject=true)
Save configuration out to ini files.
virtual void Serialize (FArchive &Ar)
Handles reading, writing, and reference collecting using FArchive.
virtual void Serialize (FStructuredArchive::FRecord Record)
void SerializeScriptProperties (FArchive &Ar) const
Serializes the script property data located at Data.
void SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
void SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
void SetLinker (FLinkerLoad *LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting=true)
Changes the linker and linker index to the passed in one.
virtual void ShutdownAfterError ()
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
void SkipFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
virtual void TagSubobjects (EObjectFlags NewFlags)
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
void ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext &Context) const
Internal use function for the AssetRegistry.
bool TryUpdateDefaultConfigFile (const FString &SpecificFileLocation="", bool bWarnIfFail=true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") 1 void UpdateDefaultConfigFile(const FString &SpecificFileLocation
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.1, "Use version that takes FPostCDOCompiledContext instead.") virtual void PostCDOCompiled()
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
UE_DEPRECATED (5.3, "Matinee has been removed in 5.0, nothing is calling PostInterpChange anymore") virtual void PostInterpChange(FProperty *PropertyThatChanged)
UE_DEPRECATED (5.3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") 1 virtual EDataValidationResult IsDataValid(TArray< FText > &ValidationErrors)
Generic function to validate objects during changelist validations, etc.
UE_DEPRECATED (5.3, "Please use the the const version of IsDataValid(FDataValidationContext&)") 1 virtual EDataValidationResult IsDataValid(class FDataValidationContext &Context)
UE_DEPRECATED (5.4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") 1 void CollectDefaultSubobjects(TArray< UObject * > &OutDefaultSubobjects
Gets all subobjects inside this object that return true for IsDefaultSubobject.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const
UE_DEPRECATED (5.5, "Multithreaded destruction of UObjects is no longer supported.") 1 virtual bool IsDestructionThreadSafe() const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
UE_DEPRECATED (5.5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \ Note that this function MUST be safe to call on a background thread. If you have functionality that doesn't meet that requirement, \ consider using the AssetRegistry's AssetAddedEvent which fires on the game thread.") virtual void PostLoadAssetRegistryTags(const FAssetData &InAssetData
void UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
void UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
void UpdateSinglePropertyInConfigFile (const FProperty *InProperty, const FString &InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
virtual void ValidateGeneratedRepEnums (const TArray< struct FRepRecord > &ClassReps) const
virtual void WillNeverCacheCookedPlatformDataAgain ()
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Public Member Functions inherited from UObjectBaseUtility
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Static Public Member Functions
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Callback used to allow object register its direct object references that are not already covered by the token stream.
static bool CanCreateInCurrentContext (UObject *Template)
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
static UObject * GetArchetypeFromRequiredInfo (const UClass *Class, const UObject *Outer, FName Name, EObjectFlags ObjectFlags)
Return the template that an object with this class, outer and name would be.
static TSet< FName > & GetMetaDataTagsForAssetRegistry ()
The metadata tags to be transferred from the FMetaData to the Asset Registry.
static const FName & SourceFileTagName ()
Get the common tag name used for all asset source file import paths.
static void UpdateClassesExcludedFromDedicatedClient (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated client builds.
static void UpdateClassesExcludedFromDedicatedServer (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated server builds.
Static Public Member Functions inherited from UObjectBaseUtility
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Data Fields
bool bIncludeNestedSubobjects =false) const
TArray< FAssetRegistryTag > &OutTagsAndValuesToUpdate const final
Static Public Attributes
static FOnGetPreviewPlatform OnGetPreviewPlatform
Protected Types
enum class ETransactionAnnotationCreationMode : uint8 { DefaultInstance , FindOrCreate }
Factory a new annotation object and optionally populate it with data.
Protected Member Functions
bool CanCheckDefaultSubObjects (bool bForceCheck, bool &bResult) const
Checks it's ok to perform subobjects check at this time.
virtual bool CheckDefaultSubobjectsInternal () const
Checks default sub-object assumptions.
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const
virtual FString GetDetailedInfoInternal () const
This function actually does the work for the GetDetailedInfo() and is virtual.
virtual bool IsSelectedInEditor () const
Test the selection state of a UObject.
virtual void ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext &Context) const
Performs fixup on loaded asset registry data.
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Private Member Functions
UObject ()
Default constructor.
UObject (const FObjectInitializer &ObjectInitializer)
Constructor that takes an ObjectInitializer.
UObject (EStaticConstructor, EObjectFlags InFlags)
DO NOT USE.
UObject (FVTableHelper &Helper)
DO NOT USE.
virtual void CookAdditionalFilesOverride (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
UObject * CreateDefaultSubobject (FName SubobjectFName, UClass *ReturnType, UClass *ClassToCreateByDefault, bool bIsRequired, bool bIsTransient)
Utility function for templates below.
template<class TReturnType>
TReturnType * CreateDefaultSubobject (FName SubobjectName, bool bTransient=false)
Create a component or subobject that will be instanced inside all instances of this class.
template<class TReturnType, class TClassToConstructByDefault>
TReturnType * CreateDefaultSubobject (FName SubobjectName, bool bTransient=false)
Create a component or subobject, allows creating a child class and returning the parent class.
template<class TReturnType>
TReturnType * CreateEditorOnlyDefaultSubobject (FName SubobjectName, bool bTransient=false)
Create a component or subobject only to be used with the editor.
UObject * CreateEditorOnlyDefaultSubobjectImpl (FName SubobjectName, UClass *ReturnType, bool bTransient=false)
Create a component or subobject only to be used with the editor.
template<class TReturnType>
TReturnType * CreateOptionalDefaultSubobject (FName SubobjectName, bool bTransient=false)
Create an optional component or subobject.Optional subobjects will not get created.
template<class TReturnType, class TClassToConstructByDefault>
TReturnType * CreateOptionalDefaultSubobject (FName SubobjectName, bool bTransient=false)
Create an optional component or subobject.
DECLARE_CLASS (UObject, UObject, CLASS_Abstract|CLASS_Intrinsic|CLASS_MatchedSerializers, CASTCLASS_None, TEXT("/Script/CoreUObject"), 1) DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UObject) typedef UObject WithinClass
void EnsureNotRetrievingVTablePtr () const
Ensures that current thread is NOT during vtable ptr retrieval process of some UClass.
UObject * GetDefaultSubobjectByName (FName ToFind)
Finds a default subobject associated with this object instance by its name.
void GetDefaultSubobjects (TArray< UObject * > &OutDefaultSubobjects)
Gets all directly nested default subobjects that are associated with this object instance.
void ProcessContextOpcode (FFrame &Stack, RESULT_DECL, bool bCanFailSilent)
virtual void SetNetPushIdDynamic (const uint64 NewNetPushId)
void UpdateSingleSectionOfConfigFile (const FString &ConfigIniName)
Saves just the section(s) for this class into the given ini file for the class (with just the changes from base)
Static Private Member Functions
static UObject * __VTableCtorCaller (FVTableHelper &Helper)
static const TCHAR * StaticConfigName ()
static void StaticRegisterNativesUObject ()
Friends
struct FObjectNetPushIdHelper
UClass * Z_Construct_UClass_UObject_NoRegister ()
Additional Inherited Members
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Detailed Description
The base class of all UE objects.
The type of an object is defined by its UClass. This provides support functions for creating and using objects, and virtual functions that should be overridden in child classes.
See also
https://docs.unrealengine.com/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/Objects
Definition at line 93 of file Object.h.
Member Typedef Documentation
FPostCDOCompiledContext
using UObject::FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Definition at line 242 of file Object.h.
Member Enumeration Documentation
ENetFields_Private
enum class UObject::ENetFields_Private strong
Enumerator
NETFIELD_REP_START
NETFIELD_REP_END
Definition at line 1780 of file Object.h.
ETransactionAnnotationCreationMode
enum class UObject::ETransactionAnnotationCreationMode : uint8 strong protected
Factory a new annotation object and optionally populate it with data.
Enumerator
DefaultInstance
FindOrCreate
Definition at line 510 of file Object.h.
Constructor & Destructor Documentation
UObject() [1/4]
UObject::UObject () private
Default constructor.
Referenced by UScriptStruct::TCppStructOps< CPPSTRUCT >::TCppStructOps(), __VTableCtorCaller(), UClass::AddDefaultSubobject(), UActorComponent::AdditionalStatObject(), UAudioComponent::AdditionalStatObject(), UDecalComponent::AdditionalStatObject(), UForceFeedbackComponent::AdditionalStatObject(), UActorComponent::AddReferencedObjects(), UArrayProperty::AddReferencedObjects(), UChildActorComponent::AddReferencedObjects(), UClass::AddReferencedObjects(), UEnumProperty::AddReferencedObjects(), UGCObjectReferencer::AddReferencedObjects(), UInterfaceProperty::AddReferencedObjects(), UMapProperty::AddReferencedObjects(), UModel::AddReferencedObjects(), AddReferencedObjects(), UObjectPropertyBase::AddReferencedObjects(), UPackage::AddReferencedObjects(), USceneCaptureComponent::AddReferencedObjects(), USetProperty::AddReferencedObjects(), UStruct::AddReferencedObjects(), UStructProperty::AddReferencedObjects(), UActorComponent::AddReplicatedSubObject(), AreNativePropertiesIdenticalTo(), BuildSubobjectMapping(), UClass::CallAddReferencedObjects(), CallFunctionByNameWithArguments(), CanCreateInCurrentContext(), UInputComponent::ClearBindingsForObject(), UProperty::ContainerPtrToValuePtr(), UProperty::ContainerPtrToValuePtr(), UProperty::ContainerUObjectPtrToValuePtrInternal(), UGameplayTask::ConvertToTaskOwner(), UClass::CreateDefaultObject(), CreateDefaultSubobject(), CreateEditorOnlyDefaultSubobjectImpl(), UWorldPartitionRuntimeHash::CreateExternalStreamingObject(), UClass::CreatePersistentUberGraphFrame(), UWorldPartitionRuntimeHash::CreateRuntimeCell(), UModel::DECLARE_CASTED_CLASS_INTRINSIC_NO_CTOR_NO_VTABLE_CTOR(), UPackage::DECLARE_CASTED_CLASS_INTRINSIC_NO_CTOR_NO_VTABLE_CTOR(), UField::DECLARE_CASTED_CLASS_INTRINSIC_WITH_API(), UObjectRedirector::DECLARE_CASTED_CLASS_INTRINSIC_WITH_API(), UPackageMap::DECLARE_CASTED_CLASS_INTRINSIC_WITH_API(), UGCObjectReferencer::DECLARE_CASTED_CLASS_INTRINSIC_WITH_API_NO_CTOR(), DECLARE_CLASS(), UPropertyWrapper::DECLARE_CLASS_INTRINSIC_API(), UPackage::DECLARE_MULTICAST_DELEGATE_TwoParams(), UObject::FAssetRegistryTag::DECLARE_TS_MULTICAST_DELEGATE_ThreeParams(), UObject::FAssetRegistryTag::DECLARE_TS_MULTICAST_DELEGATE_TwoParams(), UClass::DestroyPersistentUberGraphFrame(), UActorComponent::DestroyReplicatedSubObjectOnRemotePeers(), UScriptStruct::ExportText(), UScriptStruct::ICppStructOps::ExportTextItem(), UScriptStruct::TCppStructOps< CPPSTRUCT >::ExportTextItem(), UClass::FindArchetype(), UPackage::FindAssetInPackage(), UBlackboardKeyType_Object::GENERATED_UCLASS_BODY(), GetArchetype(), UClass::GetArchetypeForCDO(), GetArchetypeFromRequiredInfo(), UActorComponent::GetAsyncPhysicsStateObject(), UAnimNotifyState::GetContainingAsset(), UClass::GetDefaultObject(), UClass::GetDefaultObject(), UClass::GetDefaultObjectPreloadDependencies(), UClass::GetDefaultSubobjectByName(), GetDefaultSubobjectByName(), UCameraComponent::GetEditorPreviewInfo(), UDecalComponent::GetMaterialPropertyPath(), USceneComponent::GetMaterialPropertyPath(), UPackageMap::GetNetGUIDFromObject(), UPackageMap::GetObjectFromNetGUID(), UClass::GetPersistentUberGraphFrame(), GetPreloadDependencies(), GetPrestreamPackages(), UGCObjectReferencer::GetReferencerName(), UWorldPartitionStreamingSourceComponent::GetStreamingSourceOwner(), UAbilitySystemComponent::GetSubobjectsWithStableNamesForNetworking(), UBlackboardKeyType_Object::GetValue(), UScriptStruct::ImportText(), UScriptStruct::ImportText(), UScriptStruct::ICppStructOps::ImportTextItem(), UScriptStruct::TCppStructOps< CPPSTRUCT >::ImportTextItem(), UFunction::Invoke(), IsBasedOnArchetype(), UPackage::IsEmptyPackage(), UActorComponent::IsReplicatedSubObjectRegistered(), UFbxImportUI::LoadOptions(), UStruct::LoadTaggedPropertiesFromText(), UGameplayTask::NewTask(), UGameplayTask::NewTask(), UPackageMap::NotifyStreamingLevelUnload(), UAudioComponent::PlayQueuedQuantizedInternal(), UClass::PostInitInstance(), UClass::PostLoadDefaultObject(), UClass::PostLoadInstance(), UActorComponent::PostRename(), PostRename(), ProcessConsoleExec(), RegenerateClass(), ReinitializeProperties(), UActorComponent::RemoveReplicatedSubObject(), UActorComponent::Rename(), UClass::Rename(), UModel::Rename(), Rename(), UPackage::Rename(), UPackageMap::ReportSyncLoadsForProperty(), UPackageMap::ResolvePathAndAssignNetGUID(), ResolveSubobject(), UPackage::Save(), UPackage::Save2(), UFbxImportUI::SaveOptions(), UPackage::SavePackage(), USceneComponent::Serialize(), UClass::SerializeDefaultObject(), UClass::SerializeDefaultObject(), UPackageMap::SerializeObject(), UStruct::SerializeTaggedProperties(), UStruct::SerializeTaggedProperties(), UStruct::SerializeVersionedTaggedProperties(), UClass::SetDefaultObject(), UEnvQueryInstanceBlueprintWrapper::SetInstigator(), UBlackboardKeyType_Object::SetValue(), UActorComponent::TearOffReplicatedSubObjectOnRemotePeers(), UClass::UE_DEPRECATED(), UActorComponent::UFUNCTION(), UAudioComponent::UFUNCTION(), UBlackboardKeyType_Object::UPROPERTY(), and UPackageMap::WriteObject().
UObject() [2/4]
UObject::UObject (const FObjectInitializer & ObjectInitializer) private
Constructor that takes an ObjectInitializer.
Typically not needed, but can be useful for class hierarchies that support optional subobjects or subobject class overriding
UObject() [3/4]
UObject::UObject (EStaticConstructor , EObjectFlags InFlags) private
DO NOT USE.
This constructor is for internal usage only for statically-created objects.
UObject() [4/4]
UObject::UObject (FVTableHelper & Helper) private
DO NOT USE.
This constructor is for internal usage only for hot-reload purposes.
Member Function Documentation
__VTableCtorCaller()
UObject * UObject::__VTableCtorCaller (FVTableHelper & Helper) inline static private
Definition at line 99 of file Object.h.
References UObject(), EC_InternalUseOnlyConstructor, GetTransientPackage(), RF_ClassDefaultObject, RF_NeedLoad, and RF_TagGarbageTemp.
AbortInsideMemberFunction()
void UObject::AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
AddReferencedObjects()
void UObject::AddReferencedObjects (UObject * InThis, FReferenceCollector & Collector) static
Callback used to allow object register its direct object references that are not already covered by the token stream.
Parameters
InThis Object to collect references from.
Collector FReferenceCollector objects to be used to collect references.
References UObject().
Referenced by UCLASS().
AreNativePropertiesIdenticalTo()
virtual bool UObject::AreNativePropertiesIdenticalTo (UObject * Other) const inline virtual
Returns whether native properties are identical to the one of the passed in component.
Parameters
Other Other component to compare against
Returns
true if native properties are identical, false otherwise
Definition at line 822 of file Object.h.
References UObject(), and Other.
BeginCacheForCookedPlatformData()
virtual void UObject::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform) inline virtual
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
Parameters
TargetPlatform target platform to cache platform specific data for
Definition at line 1199 of file Object.h.
BeginDestroy()
virtual void UObject::BeginDestroy () virtual
Called before destroying the object.
This is called immediately upon deciding to destroy the object, to allow the object to begin an asynchronous cleanup process.
Reimplemented in UActorComponent, UAIPerceptionComponent, UAudioBus, UAudioComponent, UChildActorComponent, UClassProperty, UDelegateProperty, UGroomAsset, UInterfaceProperty, ULightComponent, UModel, UMulticastDelegateProperty, UObjectPropertyBase, UPhysicalAnimationComponent, UPhysicsConstraintComponent, URectLightComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneComponent, USkyLightComponent, USoftClassProperty, and UVPScoutingSubsystemGestureManagerBase.
Referenced by UCLASS().
BuildSubobjectMapping()
virtual void UObject::BuildSubobjectMapping (UObject * OtherObject, TMap< UObject *, UObject * > & ObjectMapping) const virtual
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
Parameters
OtherObject The to find matching sub-objects within.
ObjectMapping The complete mapping between this object hierarchy and the other object hierarchy.
References UObject().
CallAddReferencedObjects()
void UObject::CallAddReferencedObjects (FReferenceCollector & Collector)
Helper function to call AddReferencedObjects for this object's class.
Parameters
Collector FReferenceCollector objects to be used to collect references.
CallFunction()
void UObject::CallFunction (FFrame & Stack, RESULT_DECL , UFunction * Function)
Internal VM method for executing a function.
References Function, and RESULT_DECL.
CallFunctionByNameWithArguments()
bool UObject::CallFunctionByNameWithArguments (const TCHAR * Cmd, FOutputDevice & Ar, UObject * Executor, bool bForceCallWithNonExec = false)
Handle calling a function by name when executed from the console or a command line.
References UObject(), Ar, and Cmd.
Referenced by ProcessConsoleExec().
CallRemoteFunction()
virtual bool UObject::CallRemoteFunction (UFunction * Function, void * Parms, struct FOutParmRec * OutParms, FFrame * Stack) inline virtual
Call the actor's function remotely.
Parameters
Function function to call
Parms arguments to the function call
OutParms out parameter information (irrelevant for RPC's)
Stack stack frame for the function call
Returns
returns true if the function was processed by a NetDriver
Reimplemented in UActorComponent.
Definition at line 1497 of file Object.h.
References Function.
CanCheckDefaultSubObjects()
bool UObject::CanCheckDefaultSubObjects (bool bForceCheck, bool & bResult) const protected
Checks it's ok to perform subobjects check at this time.
CanCreateInCurrentContext()
bool UObject::CanCreateInCurrentContext (UObject * Template) static
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
References UObject().
CanEditChange() [1/2]
virtual bool UObject::CanEditChange (const FEditPropertyChain & PropertyChain) const virtual
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
The head of the chain is the FStructProperty member variable that contains the property that was modified. The active property in the chain is the specific FProperty in question (the one given to the other signature of CanEditChange)
Parameters
PropertyChain The chain to the property in question. The ActiveNode of the chain corresponds to the specific property in question.
Returns
true if the property can be modified in the editor, otherwise false
CanEditChange() [2/2]
virtual bool UObject::CanEditChange (const FProperty * InProperty) const virtual
Called by the editor to query whether a property of this object is allowed to be modified.
The property editor uses this to disable controls for properties that should not be changed. When overriding this function you should always call the parent implementation first.
Parameters
InProperty The property to query
Returns
true if the property can be modified in the editor, otherwise false
Reimplemented in UActorComponent, UDataLayerInstance, UDataLayerInstancePrivate, UDirectionalLightComponent, UExponentialHeightFogComponent, UFbxImportUI, ULightComponent, ULightComponentBase, ULocalFogVolumeComponent, ULocalLightComponent, UPointLightComponent, URectLightComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneComponent, and USkyLightComponent.
Referenced by UCLASS().
CanModify()
bool UObject::CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
References FORCEINLINE.
CheckDefaultSubobjects()
bool UObject::CheckDefaultSubobjects (bool bForceCheck = false) const
Checks default sub-object assumptions.
Parameters
bForceCheck Force checks even if not enabled globally.
Returns
true if the assumptions are met, false otherwise.
References CheckDefaultSubobjects().
Referenced by CheckDefaultSubobjects().
CheckDefaultSubobjectsInternal()
virtual bool UObject::CheckDefaultSubobjectsInternal () const protected virtual
Checks default sub-object assumptions.
Returns
true if the assumptions are met, false otherwise.
ClearAllCachedCookedPlatformData()
virtual void UObject::ClearAllCachedCookedPlatformData () inline virtual
Clear all cached cooked platform data.
Parameters
TargetPlatform target platform to cache platform specific data for
Definition at line 1225 of file Object.h.
ClearCachedCookedPlatformData()
virtual void UObject::ClearCachedCookedPlatformData (const ITargetPlatform * TargetPlatform) inline virtual
Clears cached cooked platform data for specific platform.
Parameters
TargetPlatform target platform to cache platform specific data for
Definition at line 1218 of file Object.h.
CollectSaveOverrides()
virtual void UObject::CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext) virtual
Collect any save override state.
ConditionalBeginDestroy()
bool UObject::ConditionalBeginDestroy ()
Called before destroying the object.
This is called immediately upon deciding to destroy the object, to allow the object to begin an asynchronous cleanup process.
ConditionalFinishDestroy()
bool UObject::ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
ConditionalPostLoad()
void UObject::ConditionalPostLoad ()
PostLoad if needed.
ConditionalPostLoadSubobjects()
void UObject::ConditionalPostLoadSubobjects (struct FObjectInstancingGraph * OuterInstanceGraph = NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
Ensures that references between nested components are fixed up correctly.
Parameters
OuterInstanceGraph when calling this method on subobjects, specifies the instancing graph which contains all instanced subobjects and components for a subobject root.
ConformSparseClassDataStruct()
virtual bool UObject::ConformSparseClassDataStruct (UScriptStruct * SourceSparseClassDataStruct, void * SourceSparseClassData) const inline virtual
Definition at line 713 of file Object.h.
CookAdditionalFiles()
void UObject::CookAdditionalFiles (const TCHAR * PackageFilename, const ITargetPlatform * TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile) inline
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
Note
Implement CookAdditionalFilesOverride to define sub class behavior.
Parameters
PackageFilename full path to the package that this object is being saved to on disk
TargetPlatform target platform to cook additional files for
WriteAdditionalFile function for writing the additional files
Definition at line 1235 of file Object.h.
References CookAdditionalFilesOverride(), Filename, and TSequenceHistory< HistorySize >::Size.
CookAdditionalFilesOverride()
virtual void UObject::CookAdditionalFilesOverride (const TCHAR * PackageFilename, const ITargetPlatform * TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile) inline private virtual
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
Files written using the provided function will be handled as part of the saved cooked package and contribute to package total file size, and package hash when enabled.
Note
These should typically match the name of the package, but with a different extension.
Parameters
PackageFilename full path to the package that this object is being saved to on disk
TargetPlatform target platform to cook additional files for
WriteAdditionalFile function for writing the additional files
Definition at line 1252 of file Object.h.
References Filename, and TSequenceHistory< HistorySize >::Size.
Referenced by CookAdditionalFiles().
CreateAndRestoreTransactionAnnotation()
TSharedPtr< ITransactionObjectAnnotation > UObject::CreateAndRestoreTransactionAnnotation (FArchive & Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
References Ar.
CreateDefaultSubobject() [1/3]
UObject * UObject::CreateDefaultSubobject (FName SubobjectFName, UClass * ReturnType, UClass * ClassToCreateByDefault, bool bIsRequired, bool bIsTransient) private
Utility function for templates below.
References UObject().
Referenced by CreateDefaultSubobject(), and CreateOptionalDefaultSubobject().
CreateDefaultSubobject() [2/3]
template<class TReturnType> TReturnType * UObject::CreateDefaultSubobject (FName SubobjectName, bool bTransient = false) inline private
Create a component or subobject that will be instanced inside all instances of this class.
Parameters
TReturnType Class of return type, all overrides must be of this type
SubobjectName Name of the new component
bTransient True if the component is being assigned to a transient property. This does not make the component itself transient, but does stop it from inheriting parent defaults
Definition at line 150 of file Object.h.
References CreateDefaultSubobject().
CreateDefaultSubobject() [3/3]
template<class TReturnType, class TClassToConstructByDefault> TReturnType * UObject::CreateDefaultSubobject (FName SubobjectName, bool bTransient = false) inline private
Create a component or subobject, allows creating a child class and returning the parent class.
Parameters
TReturnType Class of return type, all overrides must be of this type
TClassToConstructByDefault Class of object to actually construct, must be a subclass of TReturnType
SubobjectName Name of the new component
bTransient True if the component is being assigned to a transient property. This does not make the component itself transient, but does stop it from inheriting parent defaults
Definition at line 164 of file Object.h.
References CreateDefaultSubobject().
CreateEditorOnlyDefaultSubobject()
template<class TReturnType> TReturnType * UObject::CreateEditorOnlyDefaultSubobject (FName SubobjectName, bool bTransient = false) inline private
Create a component or subobject only to be used with the editor.
They will be stripped out in packaged builds.
Parameters
TReturnType Class of return type, all overrides must be of this type
SubobjectName Name of the new component
bTransient True if the component is being assigned to a transient property. This does not make the component itself transient, but does stop it from inheriting parent defaults
Definition at line 137 of file Object.h.
References CreateEditorOnlyDefaultSubobjectImpl().
CreateEditorOnlyDefaultSubobjectImpl()
UObject * UObject::CreateEditorOnlyDefaultSubobjectImpl (FName SubobjectName, UClass * ReturnType, bool bTransient = false) private
Create a component or subobject only to be used with the editor.
Parameters
Outer outer to construct the subobject in
ReturnType type of the new component
SubobjectName name of the new component
bTransient true if the component is being assigned to a transient property
References UObject().
Referenced by CreateEditorOnlyDefaultSubobject().
CreateOptionalDefaultSubobject() [1/2]
template<class TReturnType> TReturnType * UObject::CreateOptionalDefaultSubobject (FName SubobjectName, bool bTransient = false) inline private
Create an optional component or subobject.Optional subobjects will not get created.
if a derived class specifies DoNotCreateDefaultSubobject with the subobject name.
Parameters
TReturnType Class of return type, all overrides must be of this type
SubobjectName Name of the new component
bTransient True if the component is being assigned to a transient property. This does not make the component itself transient, but does stop it from inheriting parent defaults
Definition at line 177 of file Object.h.
References CreateDefaultSubobject().
CreateOptionalDefaultSubobject() [2/2]
template<class TReturnType, class TClassToConstructByDefault> TReturnType * UObject::CreateOptionalDefaultSubobject (FName SubobjectName, bool bTransient = false) inline private
Create an optional component or subobject.
Optional subobjects will not get created. if a derived class specifies DoNotCreateDefaultSubobject with the subobject name.
Parameters
TReturnType Class of return type, all overrides must be of this type
TClassToConstructByDefault Class of object to actually construct, must be a subclass of TReturnType
SubobjectName Name of the new component
bTransient True if the component is being assigned to a transient property. This does not make the component itself transient, but does stop it from inheriting parent defaults
Definition at line 192 of file Object.h.
References CreateDefaultSubobject().
DECLARE_CLASS()
UObject::DECLARE_CLASS (UObject , UObject , CLASS_Abstract|CLASS_Intrinsic| CLASS_MatchedSerializers, CASTCLASS_None , TEXT("/Script/CoreUObject") , 1) private
References UObject(), CASTCLASS_None, CLASS_Abstract, CLASS_Intrinsic, and CLASS_MatchedSerializers.
DECLARE_DELEGATE_RetVal_OneParam()
UObject::DECLARE_DELEGATE_RetVal_OneParam (bool , FOnGetPreviewPlatform , FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
Used by LoadConfig for CLASS_PerPlatformConfig objects.
DECLARE_FUNCTION() [1/126]
UObject::DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION() [2/126]
UObject::DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION() [3/126]
UObject::DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION() [4/126]
UObject::DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION() [5/126]
UObject::DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION() [6/126]
UObject::DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION() [7/126]
UObject::DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION() [8/126]
UObject::DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION() [9/126]
UObject::DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION() [10/126]
UObject::DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION() [11/126]
UObject::DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION() [12/126]
UObject::DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION() [13/126]
UObject::DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION() [14/126]
UObject::DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION() [15/126]
UObject::DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION() [16/126]
UObject::DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION() [17/126]
UObject::DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION() [18/126]
UObject::DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION() [19/126]
UObject::DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION() [20/126]
UObject::DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION() [21/126]
UObject::DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION() [22/126]
UObject::DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION() [23/126]
UObject::DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION() [24/126]
UObject::DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION() [25/126]
UObject::DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION() [26/126]
UObject::DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION() [27/126]
UObject::DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION() [28/126]
UObject::DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION() [29/126]
UObject::DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION() [30/126]
UObject::DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION() [31/126]
UObject::DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION() [32/126]
UObject::DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION() [33/126]
UObject::DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION() [34/126]
UObject::DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION() [35/126]
UObject::DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION() [36/126]
UObject::DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION() [37/126]
UObject::DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION() [38/126]
UObject::DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION() [39/126]
UObject::DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION() [40/126]
UObject::DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION() [41/126]
UObject::DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION() [42/126]
UObject::DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION() [43/126]
UObject::DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION() [44/126]
UObject::DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION() [45/126]
UObject::DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION() [46/126]
UObject::DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION() [47/126]
UObject::DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION() [48/126]
UObject::DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION() [49/126]
UObject::DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION() [50/126]
UObject::DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION() [51/126]
UObject::DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION() [52/126]
UObject::DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION() [53/126]
UObject::DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION() [54/126]
UObject::DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION() [55/126]
UObject::DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION() [56/126]
UObject::DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION() [57/126]
UObject::DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION() [58/126]
UObject::DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION() [59/126]
UObject::DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION() [60/126]
UObject::DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION() [61/126]
UObject::DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION() [62/126]
UObject::DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION() [63/126]
UObject::DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION() [64/126]
UObject::DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION() [65/126]
UObject::DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION() [66/126]
UObject::DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION() [67/126]
UObject::DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION() [68/126]
UObject::DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION() [69/126]
UObject::DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION() [70/126]
UObject::DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION() [71/126]
UObject::DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION() [72/126]
UObject::DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION() [73/126]
UObject::DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION() [74/126]
UObject::DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION() [75/126]
UObject::DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION() [76/126]
UObject::DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION() [77/126]
UObject::DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION() [78/126]
UObject::DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION() [79/126]
UObject::DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION() [80/126]
UObject::DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION() [81/126]
UObject::DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION() [82/126]
UObject::DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION() [83/126]
UObject::DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION() [84/126]
UObject::DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION() [85/126]
UObject::DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION() [86/126]
UObject::DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION() [87/126]
UObject::DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION() [88/126]
UObject::DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION() [89/126]
UObject::DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION() [90/126]
UObject::DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION() [91/126]
UObject::DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION() [92/126]
UObject::DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
If there are no stack entries left, it is treated as an execution error.
DECLARE_FUNCTION() [93/126]
UObject::DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
If there are no stack entries left, it is treated as an execution error.
DECLARE_FUNCTION() [94/126]
UObject::DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION() [95/126]
UObject::DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
Current execution continues to the next instruction after the push one.
DECLARE_FUNCTION() [96/126]
UObject::DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION() [97/126]
UObject::DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION() [98/126]
UObject::DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION() [99/126]
UObject::DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION() [100/126]
UObject::DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION() [101/126]
UObject::DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION() [102/126]
UObject::DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION() [103/126]
UObject::DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION() [104/126]
UObject::DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION() [105/126]
UObject::DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION() [106/126]
UObject::DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION() [107/126]
UObject::DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION() [108/126]
UObject::DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION() [109/126]
UObject::DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION() [110/126]
UObject::DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION() [111/126]
UObject::DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION() [112/126]
UObject::DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION() [113/126]
UObject::DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION() [114/126]
UObject::DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION() [115/126]
UObject::DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION() [116/126]
UObject::DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION() [117/126]
UObject::DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION() [118/126]
UObject::DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION() [119/126]
UObject::DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION() [120/126]
UObject::DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION() [121/126]
UObject::DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION() [122/126]
UObject::DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION() [123/126]
UObject::DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION() [124/126]
UObject::DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION() [125/126]
UObject::DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION() [126/126]
UObject::DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
Warning
: might not write anything to Result if proper type isn't returned.
DestroyNonNativeProperties()
void UObject::DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
EnsureNotRetrievingVTablePtr()
void UObject::EnsureNotRetrievingVTablePtr () const private
Ensures that current thread is NOT during vtable ptr retrieval process of some UClass.
References EnsureNotRetrievingVTablePtr().
Referenced by EnsureNotRetrievingVTablePtr().
ExecuteUbergraph()
void UObject::ExecuteUbergraph (int32 EntryPoint) inline
Execute the ubergraph from a specific entry point.
Definition at line 1748 of file Object.h.
References EntryPoint, UObject::Object_eventExecuteUbergraph_Parms::EntryPoint, FindFunctionChecked(), and ProcessEvent().
ExportCustomProperties()
virtual void UObject::ExportCustomProperties (FOutputDevice & Out, uint32 Indent) inline virtual
Exports the property values for the specified object as text to the output device.
Override this if you need custom support for copy/paste.
Parameters
Out The output device to send the exported text to
Indent Number of spaces to prepend to each line of output
See also
ImportCustomProperties()
Definition at line 670 of file Object.h.
FactoryTransactionAnnotation()
virtual TSharedPtr< ITransactionObjectAnnotation > UObject::FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const inline protected virtual
Definition at line 511 of file Object.h.
FindFunction()
UFunction * UObject::FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
References InName.
Referenced by UClass::FindFunction().
FindFunctionChecked()
UFunction * UObject::FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
References InName.
Referenced by ExecuteUbergraph(), and UClass::FindFunctionChecked().
FindOrCreateTransactionAnnotation()
TSharedPtr< ITransactionObjectAnnotation > UObject::FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
Referenced by FTransaction::FObjectRecord::FSerializedObject::SetObject().
FinishDestroy()
virtual void UObject::FinishDestroy () virtual
Called to finish destroying the object.
After UObject::FinishDestroy is called, the object's memory should no longer be accessed.
Warning
Because properties are destroyed here, Super::FinishDestroy() should always be called at the end of your child class's FinishDestroy() method, rather than at the beginning.
Reimplemented in UClass, UGCObjectReferencer, UPackage, UReflectionCaptureComponent, and UStruct.
GetAdditionalAssetDataObjectsForCook()
virtual void UObject::GetAdditionalAssetDataObjectsForCook (FArchiveCookContext & CookContext, TArray< UObject * > & OutObjects) const virtual
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
e.g. UBlueprintGeneratedClass returns its UBlueprint.
GetArchetype()
UObject * UObject::GetArchetype () const
Return the template this object is based on.
Returns
the archetype for this object
References UObject().
Referenced by IsBasedOnArchetype(), and UE::Transaction::FDiffableObject::SetObject().
GetArchetypeFromRequiredInfo()
UObject * UObject::GetArchetypeFromRequiredInfo (const UClass * Class, const UObject * Outer, FName Name, EObjectFlags ObjectFlags) static
Return the template that an object with this class, outer and name would be.
Returns
the archetype for this object
References UObject(), Class, UObjectBase::Name, UObjectBase::ObjectFlags, and Outer.
GetArchetypeInstances()
void UObject::GetArchetypeInstances (TArray< UObject * > & Instances)
Builds a list of objects which have this object in their archetype chain.
Parameters
Instances receives the list of objects which have this one in their archetype chain
Referenced by FComponentEditorUtils::PropagateDefaultValueChange().
GetAssetRegistryTagMetadata()
virtual void UObject::GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > & OutMetadata) const virtual
Gathers a collection of asset registry tag metadata.
GetAssetRegistryTags() [1/3]
void UObject::GetAssetRegistryTags (FAssetData & Out) const
GetAssetRegistryTags() [2/3]
virtual void UObject::GetAssetRegistryTags (FAssetRegistryTagsContext Context) const virtual
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
Parameters
OutTags A list of key-value pairs associated with this object and their types
Reimplemented in UClass, UDataLayerInstance, and UObjectRedirector.
Referenced by UGroomAsset::PostEditChangeProperty(), and UE_DEPRECATED().
GetAssetRegistryTags() [3/3]
void UObject::GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData & Out) const
Gathers a list of asset registry tags for an FAssetData.
Output data will be removed from the Context and moved onto the Out FAssetData.
GetConfigOverridePlatform()
virtual const TCHAR * UObject::GetConfigOverridePlatform () const inline virtual
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
Definition at line 1370 of file Object.h.
GetDefaultConfigFilename()
FString UObject::GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
References GetDefaultConfigFilename().
Referenced by GetDefaultConfigFilename().
GetDefaultSubobjectByName()
UObject * UObject::GetDefaultSubobjectByName (FName ToFind) private
Finds a default subobject associated with this object instance by its name.
Parameters
Name Object name to look for matching the SubobjectName used to create the default subobject
References UObject().
GetDefaultSubobjects()
void UObject::GetDefaultSubobjects (TArray< UObject * > & OutDefaultSubobjects) private
Gets all directly nested default subobjects that are associated with this object instance.
Parameters
OutDefaultSubobjects Array containing the directly nested default subobjects of this object.
GetDesc()
virtual FString UObject::GetDesc () inline virtual
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
Reimplemented in UClass.
Definition at line 706 of file Object.h.
References TEXT.
GetDetailedInfo()
FString UObject::GetDetailedInfo () const
This will return detail info about this specific object.
(e.g. AudioComponent will return the name of the cue, ParticleSystemComponent will return the name of the ParticleSystem) The idea here is that in many places you have a component of interest but what you really want is some characteristic that you can use to track down where it came from.
Note
safe to call on NULL object pointers!
GetDetailedInfoInternal()
virtual FString UObject::GetDetailedInfoInternal () const inline protected virtual
This function actually does the work for the GetDetailedInfo() and is virtual.
It should only be called from GetDetailedInfo as GetDetailedInfo is safe to call on NULL object pointers
Reimplemented in UAudioComponent.
Definition at line 218 of file Object.h.
References TEXT.
GetExporterName()
virtual FName UObject::GetExporterName (void) inline virtual
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
Definition at line 776 of file Object.h.
References FName, and TEXT.
GetExtendedAssetRegistryTagsForSave()
virtual void UObject::GetExtendedAssetRegistryTagsForSave (const ITargetPlatform * TargetPlatform, TArray< FAssetRegistryTag > & OutTags) const virtual
Temporary interim solution to gather asset registry data at save time only.
Can depend on the target platform being saved for.
Parameters
TargetPlatform The platform that this object is being saved for.
OutTags A list of key-value pairs associated with this object and their types
GetFunctionCallspace()
virtual int32 UObject::GetFunctionCallspace (UFunction * Function, FFrame * Stack) inline virtual
Return the space this function should be called.
Checks to see if this function should be called locally, remotely, or simply absorbed under the given conditions
Parameters
Function function to call
Stack stack frame for the function call
Returns
bitmask representing all callspaces that apply to this UFunction in the given context
Reimplemented in UActorComponent.
Definition at line 1483 of file Object.h.
References Function, and FunctionCallspace::Local.
GetGlobalUserConfigFilename()
FString UObject::GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
References GetGlobalUserConfigFilename().
Referenced by GetGlobalUserConfigFilename().
GetLifetimeReplicatedProps()
virtual void UObject::GetLifetimeReplicatedProps (TArray< class FLifetimeProperty > & OutLifetimeProps) const virtual
Returns properties that are replicated for the lifetime of the actor channel.
Reimplemented in UAbilitySystemComponent, UActorComponent, UChildActorComponent, and UGameplayTasksComponent.
GetMetaDataTagsForAssetRegistry()
TSet< FName > & UObject::GetMetaDataTagsForAssetRegistry () static
The metadata tags to be transferred from the FMetaData to the Asset Registry.
GetNativePropertyValues()
virtual bool UObject::GetNativePropertyValues (TMap< FString, FString > & out_PropertyValues, uint32 ExportFlags = 0) const inline virtual
Callback for retrieving a textual representation of natively serialized properties.
Child classes should implement this method if they wish to have natively serialized property values included in things like diffcommandlet output.
Parameters
out_PropertyValues receives the property names and values which should be reported for this object. The map's key should be the name of the property and the map's value should be the textual representation of the property's value. The property value should be formatted the same way that FProperty::ExportText formats property values (i.e. for arrays, wrap in quotes and use a comma as the delimiter between elements, etc.)
ExportFlags bitmask of EPropertyPortFlags used for modifying the format of the property values
Returns
true if property values were added to the map.
Reimplemented in UObjectRedirector.
Definition at line 745 of file Object.h.
GetNetPushIdDynamic()
virtual uint64 UObject::GetNetPushIdDynamic () const inline virtual
Should only ever be used by internal systems.
Definition at line 1804 of file Object.h.
References INDEX_NONE.
GetPreloadDependencies()
virtual void UObject::GetPreloadDependencies (TArray< UObject * > & OutDeps) virtual
Called during cooking.
Must return all objects that will be Preload()ed when this is serialized at load time. Only used by the EDL.
Parameters
OutDeps all objects that will be preloaded when this is serialized at load time
Reimplemented in UClass, and UStruct.
References UObject(), and GetPreloadDependencies().
Referenced by GetPreloadDependencies().
GetPrestreamPackages()
virtual void UObject::GetPrestreamPackages (TArray< UObject * > & OutPrestream) inline virtual
Called during cooking.
Returns a list of objects. The packages containing those objects will be prestreamed, when the package containing this is loaded. Only used by the EDL.
Parameters
OutPrestream all objects that will be prestreamed when this packages is streamed
Definition at line 641 of file Object.h.
References UObject(), and GetPrestreamPackages().
Referenced by GetPrestreamPackages().
GetPrimaryAssetId()
virtual FPrimaryAssetId UObject::GetPrimaryAssetId () const virtual
Returns an Type:Name pair representing the PrimaryAssetId for this object.
Assets that need to be globally referenced at runtime should return a valid Identifier. If this is valid, the object can be referenced by identifier using the AssetManager
GetProjectUserConfigFilename()
FString UObject::GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
References GetProjectUserConfigFilename().
Referenced by GetProjectUserConfigFilename().
GetReplicatedCustomConditionState()
virtual void UObject::GetReplicatedCustomConditionState (FCustomPropertyConditionState & OutActiveState) const virtual
Called when this object begins replicating to initialize the state of custom property conditions.
Reimplemented in UAbilitySystemComponent.
GetResourceSizeBytes()
SIZE_T UObject::GetResourceSizeBytes (EResourceSizeMode::Type Mode) inline
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
Parameters
Mode Indicates which resource size should be returned.
Returns
The cumulative size of this object in memory
Definition at line 765 of file Object.h.
References GetResourceSizeEx(), and FResourceSizeEx::GetTotalMemoryBytes().
GetResourceSizeEx()
virtual void UObject::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) virtual
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
Parameters
CumulativeResourceSize Struct used to count up the cumulative size of the resource as to be displayed to artists/LDs in the Editor.
Reimplemented in UGroomAsset, and UModel.
Referenced by GetResourceSizeBytes().
GetRestoreForUObjectOverwrite()
virtual FRestoreForUObjectOverwrite * UObject::GetRestoreForUObjectOverwrite () inline virtual
Save information for StaticAllocateObject in the case of overwriting an existing object.
StaticAllocateObject will call delete on the result after calling Restore()
Returns
An FRestoreForUObjectOverwrite that can restore the object or NULL if this is not necessary.
Reimplemented in UClass.
Definition at line 810 of file Object.h.
GetSparseClassDataStruct()
UScriptStruct * UObject::GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
GetSubobjectsWithStableNamesForNetworking()
virtual void UObject::GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > & ObjList) inline virtual
Returns a list of sub-objects that have stable names for networking.
Reimplemented in UAbilitySystemComponent.
Definition at line 1067 of file Object.h.
HasNonEditorOnlyReferences()
virtual bool UObject::HasNonEditorOnlyReferences () const inline virtual
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
its references are followed during cooking)
Returns
true if this object's references should be marked as used in game even when the object is editoronly
Reimplemented in UObjectRedirector.
Definition at line 606 of file Object.h.
Implements() [1/2]
template<class T> FORCEINLINE bool UObject::Implements () const
Returns true if this object implements the interface T, false otherwise.
Definition at line 4276 of file Class.h.
References FORCEINLINE, UObjectBase::GetClass(), and UClass::ImplementsInterface().
Implements() [2/2]
template<class T> bool UObject::Implements () const
Returns true if this object implements the interface T, false otherwise.
Referenced by UClass::Implements().
ImportCustomProperties()
virtual void UObject::ImportCustomProperties (const TCHAR * SourceText, FFeedbackContext * Warn) inline virtual
Exports the property values for the specified object as text to the output device.
Required for Copy&Paste Override this if you need custom support for copy/paste.
Parameters
SourceText The input data (zero terminated), will never be null
Warn For error reporting, will never be null
See also
ExportCustomProperties()
Definition at line 681 of file Object.h.
References Warn.
InstanceSubobjectTemplates()
void UObject::InstanceSubobjectTemplates (struct FObjectInstancingGraph * InstanceGraph = NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
IsAsset()
virtual bool UObject::IsAsset () const virtual
Returns true if this object is considered an asset.
Reimplemented in UClass, UDataLayerInstance, UModel, and UPackage.
Referenced by FCookTagList::Add(), and FExclusiveLoadPackageTimeTracker::PushPostLoad().
IsBasedOnArchetype()
bool UObject::IsBasedOnArchetype (const UObject *const SomeObject) const inline
Determine if this object has SomeObject in its archetype chain.
Definition at line 7266 of file UnrealType.h.
References UObject(), checkfSlow, GetArchetype(), and TEXT.
IsCachedCookedPlatformDataLoaded()
virtual bool UObject::IsCachedCookedPlatformDataLoaded (const ITargetPlatform * TargetPlatform) inline virtual
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
Parameters
TargetPlatform target platform to check for cooked platform data
Definition at line 1206 of file Object.h.
IsCapturingAsRootObjectForTransaction()
virtual bool UObject::IsCapturingAsRootObjectForTransaction () const virtual
Method to disable the sub object special handling in the transaction buffer for this object.
IsDataValid()
virtual EDataValidationResult UObject::IsDataValid (class FDataValidationContext & Context) const virtual
Generic function to validate objects during changelist validations, etc.
Parameters
Context the context holding validation warnings/errors.
Returns
Valid if this object has data validation rules set up for it and the data for this object is valid. Returns Invalid if it does not pass the rules. Returns NotValidated if no rules are set for this object.
Reimplemented in UChildActorComponent, UGameplayCueNotify_Burst, and USceneComponent.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
IsEditorOnly()
virtual bool UObject::IsEditorOnly () const inline virtual
Called during saving to determine if the object is forced to be editor only or not.
Returns
true if this object should never be loaded outside the editor
Reimplemented in UAnimDataModel, and UBoundsCopyComponent.
Definition at line 595 of file Object.h.
IsFullNameStableForNetworking()
virtual bool UObject::IsFullNameStableForNetworking () const virtual
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
IsInBlueprint()
bool UObject::IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
IsLocalizedResource()
virtual bool UObject::IsLocalizedResource () const virtual
Returns true if this object is considered a localized resource.
IsNameStableForNetworking()
virtual bool UObject::IsNameStableForNetworking () const virtual
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
Reimplemented in UActorComponent, UClass, and UPackage.
IsPostLoadThreadSafe()
virtual bool UObject::IsPostLoadThreadSafe () const inline virtual
Called during async load to determine if PostLoad can be called on the loading thread.
Returns
true if this object's PostLoad is thread safe
Reimplemented in UDecalComponent, UPackage, and USceneComponent.
Definition at line 616 of file Object.h.
IsReadyForAsyncPostLoad()
virtual bool UObject::IsReadyForAsyncPostLoad () const inline virtual
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
This is the safeguard to prevent PostLoad() from stalling the main thread.
Definition at line 347 of file Object.h.
IsReadyForFinishDestroy()
virtual bool UObject::IsReadyForFinishDestroy () inline virtual
Called to check if the object is ready for FinishDestroy.
This is called after BeginDestroy to check the completion of the potentially asynchronous object cleanup.
Returns
True if the object's asynchronous cleanup has completed and it is ready for FinishDestroy to be called.
Reimplemented in ULightComponent, UModel, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, and USkyLightComponent.
Definition at line 375 of file Object.h.
IsSafeForRootSet()
virtual bool UObject::IsSafeForRootSet () const virtual
Returns true if this object is safe to add to the root set.
IsSelected()
bool UObject::IsSelected () const
Test the selection state of a UObject.
Returns
true if the object is selected, false otherwise.
Todo
UE this doesn't belong here, but it doesn't belong anywhere else any better
IsSelectedInEditor()
virtual bool UObject::IsSelectedInEditor () const protected virtual
Test the selection state of a UObject.
Returns
true if the object is selected, false otherwise.
Todo
UE this doesn't belong here, but it doesn't belong anywhere else any better
Reimplemented in UActorComponent.
IsSupportedForNetworking()
virtual bool UObject::IsSupportedForNetworking () const virtual
IsSupportedForNetworking means an object can be referenced over the network.
Reimplemented in UActorComponent, UEnvQueryInstanceBlueprintWrapper, and UGameplayTask.
LoadConfig()
void UObject::LoadConfig (UClass * ConfigClass = nullptr, const TCHAR * Filename = nullptr, uint32 PropagationFlags = UE::LCPF_None, class FProperty * PropertyToLoad = nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > * OutAccessedKeys = nullptr)
Imports property values from an .ini file.
Parameters
Class the class to use for determining which section of the ini to retrieve text values from
Filename indicates the filename to load values from; if not specified, uses ConfigClass's ClassConfigName
PropagationFlags indicates how this call to LoadConfig should be propagated; expects a bitmask of UE::ELoadConfigPropagationFlags values.
PropertyToLoad if specified, only the ini value for the specified property will be imported.
OutAccessedKeys if specified the object is not modified and (EditorOnly) all the config keys it would read are added to OutAccessedKeys. In non-editor, function returns with no action.
References Filename, and UE::LCPF_None.
LoadedFromAnotherClass()
virtual void UObject::LoadedFromAnotherClass (const FName & OldClassName) inline virtual
Called when the object was loaded from another class via active class redirects.
Definition at line 327 of file Object.h.
MarkAsEditorOnlySubobject()
virtual void UObject::MarkAsEditorOnlySubobject () inline virtual
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
Definition at line 1547 of file Object.h.
Modify()
virtual bool UObject::Modify (bool bAlwaysMarkDirty = true) virtual
Note that the object will be modified.
If we are currently recording into the transaction buffer (undo/redo), save a copy of this object into the buffer and marks the package as needing to be saved.
Parameters
bAlwaysMarkDirty if true, marks the package dirty even if we aren't currently recording an active undo/redo transaction
Returns
true if the object was saved to the transaction buffer
Reimplemented in UActorComponent, UGroomAsset, and UModel.
Referenced by UPackage::SetAssetAccessSpecifier().
MoveDataToSparseClassDataStruct()
virtual void UObject::MoveDataToSparseClassDataStruct () const inline virtual
Definition at line 712 of file Object.h.
NeedsLoadForClient()
virtual bool UObject::NeedsLoadForClient () const virtual
Called during saving to determine the load flags to save with the object.
If false, this object will be discarded on clients
Returns
true if this object should be loaded on clients
Reimplemented in UActorComponent, UField, and UPackage.
NeedsLoadForEditorGame()
virtual bool UObject::NeedsLoadForEditorGame () const inline virtual
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
If false, this object will still get loaded if NeedsLoadForServer/Client are true
Returns
true if this object should always be loaded for games running in editor builds
Reimplemented in UActorComponent, and UObjectRedirector.
Definition at line 585 of file Object.h.
NeedsLoadForServer()
virtual bool UObject::NeedsLoadForServer () const virtual
Called during saving to determine the load flags to save with the object.
If false, this object will be discarded on servers
Returns
true if this object should be loaded on servers
Reimplemented in UActorComponent, UField, and UPackage.
NeedsLoadForTargetPlatform()
virtual bool UObject::NeedsLoadForTargetPlatform (const class ITargetPlatform * TargetPlatform) const virtual
Called during saving to determine the load flags to save with the object.
If false, this object will be discarded on the target platform
Returns
true if this object should be loaded on the target platform
OnCookEvent()
virtual void UObject::OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext & Context) inline virtual
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
See also
UE::Cook::ECookEvent for the possible events.
Reimplemented in UVolumetricCloudComponent.
Definition at line 298 of file Object.h.
Referenced by UCLASS().
OutputReferencers()
void UObject::OutputReferencers (FOutputDevice & Ar, FReferencerInformationList * Referencers = NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
Parameters
Ar the output device to send output to
Referencers optionally allows the caller to specify the list of references to output.
References Ar.
OverrideConfigSection()
virtual void UObject::OverrideConfigSection (FString & SectionName) inline virtual
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
Parameters
SectionName Reference to the unmodified config section name, that can be altered/modified
Definition at line 1377 of file Object.h.
OverridePerObjectConfigSection()
virtual void UObject::OverridePerObjectConfigSection (FString & SectionName) inline virtual
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
Parameters
SectionName Reference to the unmodified config section name, that can be altered/modified
Definition at line 1384 of file Object.h.
ParseParms()
void UObject::ParseParms (const TCHAR * Parms)
Import an object from a file.
PostCDOCompiled()
virtual void UObject::PostCDOCompiled (const FPostCDOCompiledContext & Context) inline virtual
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
This can only happen in the editor. This is called when the CDO and its associated class structure have been fully generated and populated, and allows the assignment of cached/derived data, eg) caching the name/count of properties of a certain type, or inspecting the properties on the class and using their meta-data and CDO default values to derive game data.
Definition at line 249 of file Object.h.
Referenced by UE_DEPRECATED().
PostCDOContruct()
virtual void UObject::PostCDOContruct () inline virtual
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
This is an obscure routine used to deal with the recursion in the construction of the default materials
Definition at line 237 of file Object.h.
PostDuplicate() [1/2]
virtual void UObject::PostDuplicate (bool bDuplicateForPIE) inline virtual
Called after duplication & serialization and before PostLoad.
Used to e.g. make sure UStaticMesh's UModel gets copied as well. Note: NOT called on components on actor duplication (alt-drag or copy-paste). Use PostEditImport as well to cover that case.
Reimplemented in UAnimDataModel, ULandscapeSplineSegment, and UModel.
Definition at line 540 of file Object.h.
Referenced by PostDuplicate(), and UCLASS().
PostDuplicate() [2/2]
virtual void UObject::PostDuplicate (EDuplicateMode::Type DuplicateMode) inline virtual
Reimplemented in ULightComponentBase.
Definition at line 541 of file Object.h.
References EDuplicateMode::PIE, and PostDuplicate().
PostEditChange()
void UObject::PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
PostEditChangeChainProperty()
virtual void UObject::PostEditChangeChainProperty (struct FPropertyChangedChainEvent & PropertyChangedEvent) virtual
This alternate version of PostEditChange is called when properties inside structs are modified.
The property that was actually modified is located at the tail of the list. The head of the list of the FStructProperty member variable that contains the property that was modified.
Reimplemented in UActorComponent, UChildActorComponent, UInputDeviceProperty, UPhysicsConstraintComponent, and USceneComponent.
Referenced by UCLASS().
PostEditChangeProperty()
virtual void UObject::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) virtual
Called when a property on this object has been modified externally.
Parameters
PropertyThatChanged the property that was modified
Reimplemented in UActorComponent, UAIPerceptionStimuliSourceComponent, UAudioBus, UAudioComponent, UBlackboardKeyType_Enum, UBoxReflectionCaptureComponent, UCameraShakeSourceComponent, UChildActorComponent, UDataLayerInstanceWithAsset, UDirectionalLightComponent, UExponentialHeightFogComponent, UGameplayCueNotify_Static, UGroomAsset, ULandscapeSplineSegment, ULightComponent, ULightComponentBase, ULocalFogVolumeComponent, ULocalLightComponent, UPhysicsConstraintComponent, UPointLightComponent, URadialForceComponent, URectLightComponent, UReflectionCaptureComponent, USceneCaptureComponent, USceneCaptureComponentCube, USceneComponent, USkyAtmosphereComponent, USkyLightComponent, USphereReflectionCaptureComponent, USpotLightComponent, and UVolumetricCloudComponent.
PostEditImport()
virtual void UObject::PostEditImport () inline virtual
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
Reimplemented in UChildActorComponent, ULandscapeSplineSegment, and ULightComponentBase.
Definition at line 688 of file Object.h.
PostEditUndo() [1/2]
virtual void UObject::PostEditUndo () virtual
Called after applying a transaction to the object.
Default implementation simply calls PostEditChange.
Reimplemented in UActorComponent, UChildActorComponent, UDataLayerInstance, UDataLayerInstanceWithAsset, ULandscapeSplineSegment, and UModel.
PostEditUndo() [2/2]
virtual void UObject::PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation) virtual
Called after applying a transaction to the object in cases where transaction annotation was provided.
Default implementation simply calls PostEditChange.
References TransactionAnnotation.
PostInitProperties()
virtual void UObject::PostInitProperties () virtual
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
This is called before any serialization or other setup has happened.
Reimplemented in UActorComponent, UAIPerceptionComponent, UClass, UGameplayCueNotify_Static, ULandscapeSplineSegment, UPackage, UReflectionCaptureComponent, and USkyLightComponent.
Referenced by UGroomAsset::PostEditChangeProperty().
PostLinkerChange()
virtual void UObject::PostLinkerChange () inline virtual
Called in response to the linker changing, this can only happen in the editor.
Definition at line 381 of file Object.h.
PostLoad()
virtual void UObject::PostLoad () virtual
Do any object-specific cleanup required immediately after loading an object.
This is not called for newly-created objects, and by default will always execute on the game thread.
Reimplemented in UActorComponent, UAnimNotifyState, UAudioComponent, UChildActorComponent, UClass, UDataLayerInstance, UDecalComponent, UField, UFunction, UGroomAsset, ULandscapeSplineSegment, ULightComponent, ULightComponentBase, UModel, UPhysicsConstraintComponent, URadialForceComponent, USceneCaptureComponent, USkyLightComponent, USpringArmComponent, UStruct, and UWorldPartitionStreamingSourceComponent.
PostLoadSubobjects()
virtual void UObject::PostLoadSubobjects (FObjectInstancingGraph * OuterInstanceGraph) virtual
Instances components for objects being loaded from disk, if necessary.
Ensures that component references between nested components are fixed up correctly.
Parameters
OuterInstanceGraph when calling this method on subobjects, specifies the instancing graph which contains all instanced subobjects and components for a subobject root.
PostNetReceive()
virtual void UObject::PostNetReceive () virtual
Called right after receiving a bunch.
Reimplemented in UAbilitySystemComponent, and USceneComponent.
PostReinitProperties()
virtual void UObject::PostReinitProperties () virtual
Called after properties are overwritten, including after subobjects initialization from a CDO.
This could be called multiple times during an object lifetime, which is not the case for PostInitProperties which is expected to be called only once.
PostReloadConfig()
virtual void UObject::PostReloadConfig (class FProperty * PropertyThatWasLoaded) inline virtual
Called from ReloadConfig after the object has reloaded its configuration data.
Definition at line 693 of file Object.h.
PostRename()
virtual void UObject::PostRename (UObject * OldOuter, const FName OldName) virtual
Called at the end of Rename(), but only if the rename was actually carried out.
Reimplemented in UActorComponent.
References UObject().
PostRepNotifies()
virtual void UObject::PostRepNotifies () inline virtual
Called right after calling all OnRep notifies (called even when there are no notifies)
Reimplemented in UChildActorComponent, and USceneComponent.
Definition at line 1076 of file Object.h.
PostSaveRoot()
virtual void UObject::PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext) virtual
Called from within SavePackage on the passed in base/root object.
This function is called after the package has been saved and can perform cleanup.
Parameters
ObjectSaveContext Context providing access to parameters of the save and to values from PreSaveRoot
PostTransacted()
virtual void UObject::PostTransacted (const FTransactionObjectEvent & TransactionEvent) virtual
Called after the object has been transacted in some way.
TransactionEvent describes what actually happened.
Note
Unlike PostEditUndo (which is called for any object in the transaction), this is only called on objects that are actually changed by the transaction.
PreDestroyFromReplication()
virtual void UObject::PreDestroyFromReplication () virtual
Called right before being marked for destruction due to network replication.
PreDuplicate()
virtual void UObject::PreDuplicate (FObjectDuplicationParameters & DupParams) inline virtual
Called before duplication.
Parameters
DupParams the full parameters the object will be duplicated with. Allows access to modify params such as the duplication seed for example for pre-filling the dup-source => dup-target map used by StaticDuplicateObject.
See also
FObjectDuplicationParameters
Definition at line 534 of file Object.h.
PreEditChange() [1/2]
virtual void UObject::PreEditChange (class FEditPropertyChain & PropertyAboutToChange) virtual
This alternate version of PreEditChange is called when properties inside structs are modified.
The property that was actually modified is located at the tail of the list. The head of the list of the FStructProperty member variable that contains the property that was modified.
Parameters
PropertyAboutToChange the property that is about to be modified
PreEditChange() [2/2]
virtual void UObject::PreEditChange (FProperty * PropertyAboutToChange) virtual
This is called when a property is about to be modified externally.
Parameters
PropertyThatWillChange Property that will be changed
Reimplemented in UActorComponent, UAnimNotifyState_TimedParticleEffect, UCameraShakeSourceComponent, and USkyLightComponent.
PreEditUndo()
virtual void UObject::PreEditUndo () virtual
Called before applying a transaction to the object.
Default implementation simply calls PreEditChange.
Reimplemented in UActorComponent, UDataLayerInstance, and UDataLayerInstanceWithAsset.
PreNetReceive()
virtual void UObject::PreNetReceive () virtual
Called right before receiving a bunch.
Reimplemented in UAbilitySystemComponent, and USceneComponent.
PreSave()
virtual void UObject::PreSave (FObjectPreSaveContext SaveContext) virtual
Presave function.
Gets called once before an object gets serialized for saving. This function is necessary for save time computation as Serialize gets called three times per object from within SavePackage.
Warning
: Objects created from within PreSave will NOT have PreSave called on them!!!
Reimplemented in UAnimNotifyState, ULightComponent, UModel, and UObjectRedirector.
PreSaveRoot()
virtual void UObject::PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext) virtual
Called from within SavePackage on the passed in base/root object.
The return value of this function will be passed to PostSaveRoot. This is used to allow objects used as a base to perform required actions before saving and cleanup afterwards.
Parameters
ObjectSaveContext Context providing access to parameters of the save, Also allows storage of variables like bCleanupIsRequired for use in PostSaveRoot
ProcessConsoleExec()
virtual bool UObject::ProcessConsoleExec (const TCHAR * Cmd, FOutputDevice & Ar, UObject * Executor) inline virtual
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
Definition at line 1518 of file Object.h.
References UObject(), Ar, CallFunctionByNameWithArguments(), and Cmd.
ProcessContextOpcode()
void UObject::ProcessContextOpcode (FFrame & Stack, RESULT_DECL , bool bCanFailSilent) private
References RESULT_DECL.
ProcessEvent()
virtual void UObject::ProcessEvent (UFunction * Function, void * Parms) virtual
Called by VM to execute a UFunction with a filled in UStruct of parameters.
References Function.
Referenced by FTrackInstancePropertyBindings::CallFunction(), ExecuteUbergraph(), and FTrackInstancePropertyBindings::InvokeSetterFunction().
PropagatePostEditChange()
void UObject::PropagatePostEditChange (TArray< UObject * > & AffectedObjects, FPropertyChangedChainEvent & PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
Recurses on any instances.
Parameters
AffectedObjects the array of objects which have this object in their ObjectArchetype chain and will be affected by the change. Objects which have this object as their direct ObjectArchetype are removed from the list once they're processed.
PropagatePreEditChange()
void UObject::PropagatePreEditChange (TArray< UObject * > & AffectedObjects, FEditPropertyChain & PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
Recurses on any instances.
Parameters
AffectedObjects the array of objects which have this object in their ObjectArchetype chain and will be affected by the change. Objects which have this object as their direct ObjectArchetype are removed from the list once they're processed.
RegenerateClass()
virtual UClass * UObject::RegenerateClass (UClass * ClassToRegenerate, UObject * PreviousCDO) inline virtual
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
Should regenerate the class if needed, and return the updated class
Returns
Updated instance of the class, if needed, or NULL if no regeneration was necessary
Definition at line 1534 of file Object.h.
References UObject().
ReinitializeProperties()
void UObject::ReinitializeProperties (UObject * SourceObject = NULL, struct FObjectInstancingGraph * InstanceGraph = NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
Parameters
SourceObject the object to use for initializing property values in this object. If not specified, uses this object's archetype.
InstanceGraph contains the mappings of instanced objects and components to their templates
References UObject().
ReloadConfig()
void UObject::ReloadConfig (UClass * ConfigClass = NULL, const TCHAR * Filename = NULL, uint32 PropagationFlags = UE::LCPF_None, class FProperty * PropertyToLoad = NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
Allows the objects the receive a callback that its configuration data has been reloaded.
Parameters
Class the class to use for determining which section of the ini to retrieve text values from
Filename indicates the filename to load values from; if not specified, uses ConfigClass's ClassConfigName
PropagationFlags indicates how this call to LoadConfig should be propagated; expects a bitmask of UE::ELoadConfigPropagationFlags values.
PropertyToLoad if specified, only the ini value for the specified property will be imported
References Filename, and UE::LCPF_None.
Rename()
virtual bool UObject::Rename (const TCHAR * NewName = nullptr, UObject * NewOuter = nullptr, ERenameFlags Flags = REN_None) virtual
Rename this object to a unique name, or change its outer.
Remarks
A unique name will be generated if NewName is null and if either is true: NewOuter is null or NewOuter equals the current outer.
Parameters
NewName The new name of the object, if null then NewOuter should be set
NewOuter New Outer this object will be placed within, if null it will use the current outer
Flags Flags to specify what happens during the rename
Reimplemented in UActorComponent, UClass, UModel, and UPackage.
References UObject(), Flags, and REN_None.
ResolveSubobject()
virtual bool UObject::ResolveSubobject (const TCHAR * SubObjectPath, UObject *& OutObject, bool bLoadIfExists) inline virtual
Called to defer loading a subobject to its top-level container object.
Useful with the package override feature, where an object might not be saved in the same package as its outer, especially if the the top-level object does lazy loading of these objects.
Parameters
SubObjectPath object path to handle, relative to the current implementer
OutObject receives the loaded object, or existing loaded object if bOnlyTestExistence is true and object is already loaded
bLoadIfExists if true, load the object if it exists
Returns
true if the object loaded or exists, depending on bLoadIfExists
Definition at line 342 of file Object.h.
References UObject().
Referenced by UCLASS().
RetrieveReferencers()
void UObject::RetrieveReferencers (TArray< FReferencerInformation > * OutInternalReferencers, TArray< FReferencerInformation > * OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
SaveConfig()
void UObject::SaveConfig (uint64 RequiredPropertyFlags = CPF_Config, const TCHAR * Filename = nullptr, FConfigCacheIni * Config = GConfig, bool bAllowCopyToDefaultObject = true)
Save configuration out to ini files.
Warning
Must be safe to call on class-default object
References Filename, GConfig, and SaveConfig().
Referenced by SaveConfig().
Serialize() [1/2]
virtual void UObject::Serialize (FArchive & Ar) virtual
Handles reading, writing, and reference collecting using FArchive.
This implementation handles all FProperty serialization, but can be overridden for native variables.
Reimplemented in UActorComponent, UArrayProperty, UAudioComponent, UBoolProperty, UByteProperty, UChildActorComponent, UClass, UClassProperty, UDecalComponent, UDelegateProperty, UDirectionalLightComponent, UEnumProperty, UExponentialHeightFogComponent, UField, UFunction, UGameplayCueNotify_Static, UGroomAsset, UInterfaceProperty, ULandscapeSplineSegment, ULightComponent, ULightComponentBase, ULocalLightComponent, UMapProperty, UModel, UMulticastDelegateProperty, UObjectPropertyBase, UObjectRedirector, UPackage, UPackageMap, UPointLightComponent, UPostProcessComponent, UProperty, URectLightComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneCaptureComponentCube, USceneComponent, UScriptStruct, USetProperty, USkyAtmosphereComponent, USkyLightComponent, USoftClassProperty, USparseDelegateFunction, UStruct, UStructProperty, UTextBuffer, UVolumetricCloudComponent, and UWorldPartitionStreamingSourceComponent.
References Ar.
Referenced by FArchiveCountMem::FArchiveCountMem(), FObjectReader::FObjectReader(), FObjectWriter::FObjectWriter(), and UCLASS().
Serialize() [2/2]
virtual void UObject::Serialize (FStructuredArchive::FRecord Record) virtual
Reimplemented in UObjectRedirector, UScriptStruct, UStruct, and UTextBuffer.
References Ar, and Record.
SerializeScriptProperties() [1/2]
void UObject::SerializeScriptProperties (FArchive & Ar) const
Serializes the script property data located at Data.
When saving, only saves those properties which differ from the corresponding value in the specified 'DiffObject' (usually the object's archetype).
Parameters
Ar the archive to use for serialization
References Ar.
SerializeScriptProperties() [2/2]
void UObject::SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
When saving, only saves those properties which differ from the corresponding value in the specified 'DiffObject' (usually the object's archetype).
Parameters
Slot the archive slot to serialize to
SetEditChangePropagationFlags()
void UObject::SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
SetLinker()
void UObject::SetLinker (FLinkerLoad * LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting = true)
Changes the linker and linker index to the passed in one.
A linker of NULL and linker index of INDEX_NONE indicates that the object is without a linker.
Parameters
LinkerLoad New LinkerLoad object to set
LinkerIndex New LinkerIndex to set
bShouldDetachExisting If true, detach existing linker and call PostLinkerChange
SetNetPushIdDynamic()
virtual void UObject::SetNetPushIdDynamic (const uint64 NewNetPushId) inline private virtual
Definition at line 1791 of file Object.h.
References checkf, UObjectBaseUtility::GetFullName(), and TEXT.
ShutdownAfterError()
virtual void UObject::ShutdownAfterError () inline virtual
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
Definition at line 422 of file Object.h.
SkipFunction()
void UObject::SkipFunction (FFrame & Stack, RESULT_DECL , UFunction * Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
Parameters
Stack the script stack frame
Result pointer to where the return value should be written
Function the function being called
References Function, and RESULT_DECL.
SourceFileTagName()
const FName & UObject::SourceFileTagName () static
Get the common tag name used for all asset source file import paths.
StaticConfigName()
const TCHAR * UObject::StaticConfigName () inline static private
Definition at line 103 of file Object.h.
References TEXT.
StaticRegisterNativesUObject()
void UObject::StaticRegisterNativesUObject () inline static private
Definition at line 107 of file Object.h.
TagSubobjects()
virtual void UObject::TagSubobjects (EObjectFlags NewFlags) virtual
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
Parameters
ObjectFlags Object Flags to enable on the related objects
Reimplemented in UClass, and UStruct.
ThreadedPostLoadAssetRegistryTags()
void UObject::ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext & Context) const
Internal use function for the AssetRegistry.
Performs general fixup required by UObject and invokes ThreadedPostLoadAssetRegistryTagsOverride
ThreadedPostLoadAssetRegistryTagsOverride()
virtual void UObject::ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext & Context) const inline protected virtual
Performs fixup on loaded asset registry data.
DO NOT CALL ASSETREGISTRY FUNCTIONS FROM THIS FUNCTION, IT WILL DEADLOCK because this function is called from inside the AssetRegistry CriticalSection. IT MUST BE SAFE TO CALL IN MULTITHREADED BACKGROUND THREADS because the AssetRegistry can call this function from a background thread.
Note that this function is only called on Class Default Objects where the actual object instance data used to generate the asset data is not available.
Parameters
Context Contains input and receives output from the function.
See also
FPostloadAssetRegistryTagsContext
Reimplemented in UClass.
Definition at line 964 of file Object.h.
TryUpdateDefaultConfigFile()
bool UObject::TryUpdateDefaultConfigFile (const FString & SpecificFileLocation = "", bool bWarnIfFail = true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
Parameters
SpecificFileLocation The Ini file or if Empty the default ini file for the call
bWarnIfFail If true and unable to update the Ini file due to being read only log a warning
Returns
true if it was able to write false otherwise
References TryUpdateDefaultConfigFile().
Referenced by TryUpdateDefaultConfigFile().
UE_DEPRECATED() [1/9]
UObject::UE_DEPRECATED (5. 0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") const &
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
References UE_DEPRECATED().
UE_DEPRECATED() [2/9]
UObject::UE_DEPRECATED (5. 1, "Use version that takes FPostCDOCompiledContext instead.") inline
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
This can only happen in the editor.
Note
This version is deprecated as it wasn't called for skeleton-only compilation. Use the version taking FPostCDOCompiledContext instead.
Definition at line 257 of file Object.h.
References PostCDOCompiled().
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/9]
UObject::UE_DEPRECATED (5. 3, "Matinee has been removed in 5. 0, nothing is calling PostInterpChange anymore") inline
Definition at line 424 of file Object.h.
UE_DEPRECATED() [4/9]
UObject::UE_DEPRECATED (5. 3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") &
Generic function to validate objects during changelist validations, etc.
Parameters
ValidationErrors the array of validation errors.
Returns
Valid if this object has data validation rules set up for it and the data for this object is valid. Returns Invalid if it does not pass the rules. Returns NotValidated if no rules are set for this object.
References IsDataValid(), and UE_DEPRECATED().
UE_DEPRECATED() [5/9]
UObject::UE_DEPRECATED (5. 3, "Please use the the const version of IsDataValid(FDataValidationContext&)") &
References IsDataValid().
UE_DEPRECATED() [6/9]
UObject::UE_DEPRECATED (5. 4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") &
Gets all subobjects inside this object that return true for IsDefaultSubobject.
The nested behavior is inconsistent because IsDefaultSubobject does not work reliably for nested subobjects and it is less efficient than GetDefaultSubobjects
UE_DEPRECATED() [7/9]
UObject::UE_DEPRECATED (5. 4, "Implement the version that takes FAssetRegistryTagsContext instead.") const &
References GetAssetRegistryTags().
UE_DEPRECATED() [8/9]
UObject::UE_DEPRECATED (5. 5, "Multithreaded destruction of UObjects is no longer supported.") const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
Returns
true if this object's destructor is thread safe
UE_DEPRECATED() [9/9]
UObject::UE_DEPRECATED (5. 5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \Note that this function MUST be safe to call on a background thread. If you have functionality that doesn 't meet that requirement, \consider using the AssetRegistry 's AssetAddedEvent which fires on the game thread.") const &
UpdateClassesExcludedFromDedicatedClient()
void UObject::UpdateClassesExcludedFromDedicatedClient (const TArray< FString > & InClassNames, const TArray< FString > & InModulesNames) static
Update the list of classes that we should exclude from dedicated client builds.
UpdateClassesExcludedFromDedicatedServer()
void UObject::UpdateClassesExcludedFromDedicatedServer (const TArray< FString > & InClassNames, const TArray< FString > & InModulesNames) static
Update the list of classes that we should exclude from dedicated server builds.
UpdateGlobalUserConfigFile()
void UObject::UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
References UpdateGlobalUserConfigFile().
Referenced by UpdateGlobalUserConfigFile().
UpdateProjectUserConfigFile()
void UObject::UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
References UpdateProjectUserConfigFile().
Referenced by UpdateProjectUserConfigFile().
UpdateSinglePropertyInConfigFile()
void UObject::UpdateSinglePropertyInConfigFile (const FProperty * InProperty, const FString & InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
References UpdateSinglePropertyInConfigFile().
Referenced by UpdateSinglePropertyInConfigFile().
UpdateSingleSectionOfConfigFile()
void UObject::UpdateSingleSectionOfConfigFile (const FString & ConfigIniName) private
Saves just the section(s) for this class into the given ini file for the class (with just the changes from base)
References UpdateSingleSectionOfConfigFile().
Referenced by UpdateSingleSectionOfConfigFile().
ValidateGeneratedRepEnums()
virtual void UObject::ValidateGeneratedRepEnums (const TArray< struct FRepRecord > & ClassReps) const inline virtual
Definition at line 1786 of file Object.h.
WillNeverCacheCookedPlatformDataAgain()
virtual void UObject::WillNeverCacheCookedPlatformDataAgain () inline virtual
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Definition at line 1211 of file Object.h.
Friends And Related Symbol Documentation
FObjectNetPushIdHelper
friend struct FObjectNetPushIdHelper friend
Definition at line 1790 of file Object.h.
References FObjectNetPushIdHelper.
Referenced by FObjectNetPushIdHelper.
Z_Construct_UClass_UObject_NoRegister
UClass * Z_Construct_UClass_UObject_NoRegister () friend
Field Documentation
bIncludeNestedSubobjects
bool UObject::bIncludeNestedSubobjects =false) const
Definition at line 1283 of file Object.h.
final
TArray<FAssetRegistryTag>& OutTagsAndValuesToUpdate const UObject::final
Initial value:
{}
    struct FPostLoadAssetRegistryTagsContext
    {
        FPostLoadAssetRegistryTagsContext(const FAssetData& InAssetData, TArray<FAssetRegistryTag>& InTagsAndValuesToUpdate)
        : AssetData(InAssetData), TagsAndValuesToUpdate(InTagsAndValuesToUpdate) {}
        const FAssetData& GetAssetData() const { return AssetData; }
        void AddTagToUpdate(const FAssetRegistryTag& Tag) { TagsAndValuesToUpdate.Add(Tag); }
    private:
        const FAssetData& AssetData;
        TArray<FAssetRegistryTag>& TagsAndValuesToUpdate;
    }
Definition at line 935 of file Object.h.
Referenced by UActorComponent::GetAsyncPhysicsStateObject(), UAnimDataModel::GetPopulationFlag(), UActorComponent::GetWorld(), UActorComponent::IsAsyncPhysicsStateCreated(), UAnimDataModel::LockEvaluationAndModification(), UStruct::SerializeTaggedProperties(), UAnimDataModel::TryLockEvaluationAndModification(), and UAnimDataModel::UnlockEvaluationAndModification().
OnGetPreviewPlatform
FOnGetPreviewPlatform UObject::OnGetPreviewPlatform static
Definition at line 1364 of file Object.h.
Referenced by TPerPlatformProperty< _StructType, _ValueType, _BasePropertyName >::GetValue().
The documentation for this class was generated from the following files:
Object.h
Class.h
UnrealType.h