Unreal Engine 5.6 C++ API: UE::Geometry::FMeshProjectionTarget Class Reference
UE::Geometry::FMeshProjectionTarget Class Reference
FMeshProjectionTarget provides an IProjectionTarget interface to a FDynamicMesh + FDynamicMeshAABBTree3 Use to project points to mesh surface.
#include "ProjectionTargets.h"
Public Member Functions
FMeshProjectionTarget ()=default
FMeshProjectionTarget (const FDynamicMesh3 *MeshIn, FDynamicMeshAABBTree3 *SpatialIn)
virtual ~FMeshProjectionTarget ()=default
virtual DYNAMICMESH_API FVector3d Project (const FVector3d &Point, FVector3d &ProjectNormalOut, int Identifier=-1) override
virtual DYNAMICMESH_API FVector3d Project (const FVector3d &Point, int Identifier=-1) override
Public Member Functions inherited from UE::Geometry::IOrientedProjectionTarget
virtual ~IOrientedProjectionTarget ()
Public Member Functions inherited from UE::Geometry::IProjectionTarget
virtual ~IProjectionTarget ()
Data Fields
const FDynamicMesh3 * Mesh = nullptr
The mesh to project onto.
FDynamicMeshAABBTree3 * Spatial = nullptr
An AABBTree for Mesh.
Detailed Description
FMeshProjectionTarget provides an IProjectionTarget interface to a FDynamicMesh + FDynamicMeshAABBTree3 Use to project points to mesh surface.
Definition at line 20 of file ProjectionTargets.h.
Constructor & Destructor Documentation
~FMeshProjectionTarget()
virtual UE::Geometry::FMeshProjectionTarget::~FMeshProjectionTarget () virtual default
FMeshProjectionTarget() [1/2]
UE::Geometry::FMeshProjectionTarget::FMeshProjectionTarget () default
Referenced by UE::Geometry::FWorldSpaceProjectionTarget::FWorldSpaceProjectionTarget().
FMeshProjectionTarget() [2/2]
UE::Geometry::FMeshProjectionTarget::FMeshProjectionTarget (const FDynamicMesh3 * MeshIn, FDynamicMeshAABBTree3 * SpatialIn) inline
Definition at line 31 of file ProjectionTargets.h.
References Mesh, and Spatial.
Member Function Documentation
Project() [1/2]
virtual DYNAMICMESH_API FVector3d UE::Geometry::FMeshProjectionTarget::Project (const FVector3d & Point, FVector3d & ProjectNormalOut, int Identifier = -1) override virtual
Returns
Projection of Point onto this target, and set ProjectNormalOut to the triangle normal at the returned point (not interpolated vertex normal)
Implements UE::Geometry::IOrientedProjectionTarget.
Reimplemented in UE::Geometry::FWorldSpaceProjectionTarget.
References Point.
Project() [2/2]
virtual DYNAMICMESH_API FVector3d UE::Geometry::FMeshProjectionTarget::Project (const FVector3d & Point, int Identifier = -1) override virtual
Returns
Projection of Point onto this target
Implements UE::Geometry::IOrientedProjectionTarget.
Reimplemented in UE::Geometry::FWorldSpaceProjectionTarget.
References Point.
Referenced by UE::Geometry::FWorldSpaceProjectionTarget::Project(), and UE::Geometry::FWorldSpaceProjectionTarget::Project().
Field Documentation
Mesh
const FDynamicMesh3* UE::Geometry::FMeshProjectionTarget::Mesh = nullptr
The mesh to project onto.
Definition at line 24 of file ProjectionTargets.h.
Referenced by FMeshProjectionTarget().
Spatial
FDynamicMeshAABBTree3* UE::Geometry::FMeshProjectionTarget::Spatial = nullptr
An AABBTree for Mesh.
Definition at line 26 of file ProjectionTargets.h.
Referenced by FMeshProjectionTarget().
The documentation for this class was generated from the following file:
ProjectionTargets.h