Unreal Engine 5.6 C++ API: TAddKeyImpl< FMovieSceneIntegerChannel, int32 > Struct Reference
TAddKeyImpl< FMovieSceneIntegerChannel, int32 > Struct Reference
#include "KeyframeTrackEditor.h"
Public Member Functions
TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const int32 &InValue)
virtual bool Apply (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const override
virtual void ApplyDefault (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const override
virtual bool ModifyByCurrentAndWeight (FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, void *VCurrentValue, float Weight) override
Public Member Functions inherited from IImpl
virtual ~IImpl ()
Data Fields
bool bAddKey
int32 ChannelIndex
int32 ValueToSet
Detailed Description
Definition at line 333 of file KeyframeTrackEditor.h.
Constructor & Destructor Documentation
TAddKeyImpl()
TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const int32 & InValue) inline
Definition at line 339 of file KeyframeTrackEditor.h.
References bAddKey, ChannelIndex, and ValueToSet.
Member Function Documentation
Apply()
virtual bool TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::Apply (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const inline override virtual
Reimplemented from IImpl.
Definition at line 343 of file KeyframeTrackEditor.h.
References AddKeyToChannel(), bAddKey, ChannelIndex, FMovieSceneChannelProxy::GetChannel(), GetInterpolationMode(), InTime, ValueExistsAtTime(), and ValueToSet.
ApplyDefault()
virtual void TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ApplyDefault (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const inline override virtual
Reimplemented from IImpl.
Definition at line 374 of file KeyframeTrackEditor.h.
References bAddKey, ChannelIndex, FMovieSceneChannelProxy::GetChannel(), UE::MovieScene::SetChannelDefault(), SetDefault, SetDefaultOnAddKeys, and ValueToSet.
ModifyByCurrentAndWeight()
virtual bool TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ModifyByCurrentAndWeight (FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, void * VCurrentValue, float Weight) inline override virtual
Reimplemented from IImpl.
Definition at line 390 of file KeyframeTrackEditor.h.
References ChannelIndex, EvaluateChannel(), FMovieSceneChannelProxy::GetChannel(), TOptional< OptionalType >::GetValue(), InTime, TOptional< OptionalType >::IsSet(), ValueToSet, and Weight.
Field Documentation
bAddKey
bool TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::bAddKey
Definition at line 336 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), and ApplyDefault().
ChannelIndex
int32 TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ChannelIndex
Definition at line 335 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), ApplyDefault(), and ModifyByCurrentAndWeight().
ValueToSet
int32 TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ValueToSet
Definition at line 337 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), ApplyDefault(), and ModifyByCurrentAndWeight().
The documentation for this struct was generated from the following file:
KeyframeTrackEditor.h