Unreal Engine 5.6 C++ API: UE::MovieScene::FPreAnimatedEntityCaptureSource Struct Reference
UE::MovieScene::FPreAnimatedEntityCaptureSource Struct Reference
Structure responsible for tracking contributions to pre-animated state entries that originate from ECS data (ie, from FMovieSceneEntityIDs)
#include "MovieScenePreAnimatedCaptureSources.h"
Public Member Functions
MOVIESCENE_API FPreAnimatedEntityCaptureSource (FPreAnimatedStateExtension *InOwner)
MOVIESCENE_API void BeginTrackingEntity (const FPreAnimatedStateEntry &Entry, FMovieSceneEntityID EntityID, FRootInstanceHandle RootInstanceHandle, bool bWantsRestoreState)
void StopTrackingEntity (FMovieSceneEntityID EntityID)
void StopTrackingEntity (FMovieSceneEntityID EntityID, FPreAnimatedStorageID StorageID)
Public Member Functions inherited from UE::MovieScene::TPreAnimatedCaptureSources< FMovieSceneEntityID >
TPreAnimatedCaptureSources (FPreAnimatedStateExtension *InOwner)
MOVIESCENE_API EPreAnimatedCaptureSourceState BeginTrackingCaptureSource (const FMovieSceneEntityID &InKey, const FPreAnimatedStateMetaData &MetaData)
Make an association for the specified evaluation key to the value specified by Entry, along with an indication of whether it should be restored on completion.
MOVIESCENE_API bool ContainsInstanceHandle (FRootInstanceHandle RootInstanceHandle) const override
MOVIESCENE_API void GatherAndRemoveExpiredMetaData (const FRestoreStateParams &Params, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void GatherAndRemoveMetaDataForGroup (FPreAnimatedStorageGroupHandle Group, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void GatherAndRemoveMetaDataForRootInstance (FRootInstanceHandle InstanceHandle, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void GatherAndRemoveMetaDataForStorage (FPreAnimatedStorageID StorageID, FPreAnimatedStorageIndex StorageIndex, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void Reset () override
MOVIESCENE_API void StopTrackingCaptureSource (const FMovieSceneEntityID &InKey, FPreAnimatedStorageID InStorageID)
Stop tracking the evaluation key in question, where associated with the given storage value ID This restores the value if it was captured with bWantsRestoreState.
Public Member Functions inherited from UE::MovieScene::IPreAnimatedCaptureSource
virtual ~IPreAnimatedCaptureSource ()
Detailed Description
Structure responsible for tracking contributions to pre-animated state entries that originate from ECS data (ie, from FMovieSceneEntityIDs)
Definition at line 114 of file MovieScenePreAnimatedCaptureSources.h.
Constructor & Destructor Documentation
FPreAnimatedEntityCaptureSource()
MOVIESCENE_API UE::MovieScene::FPreAnimatedEntityCaptureSource::FPreAnimatedEntityCaptureSource (FPreAnimatedStateExtension * InOwner)
Member Function Documentation
BeginTrackingEntity()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedEntityCaptureSource::BeginTrackingEntity (const FPreAnimatedStateEntry & Entry, FMovieSceneEntityID EntityID, FRootInstanceHandle RootInstanceHandle, bool bWantsRestoreState)
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), UE::MovieScene::TPreAnimatedPropertyStorageImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::BeginTrackingEntities(), UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::BeginTrackingEntities(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntity(), and UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::BeginTrackingEntity().
StopTrackingEntity() [1/2]
void UE::MovieScene::FPreAnimatedEntityCaptureSource::StopTrackingEntity (FMovieSceneEntityID EntityID) inline
Definition at line 125 of file MovieScenePreAnimatedCaptureSources.h.
References UE::MovieScene::TPreAnimatedCaptureSources< FMovieSceneEntityID >::StopTrackingCaptureSource().
StopTrackingEntity() [2/2]
void UE::MovieScene::FPreAnimatedEntityCaptureSource::StopTrackingEntity (FMovieSceneEntityID EntityID, FPreAnimatedStorageID StorageID) inline
Definition at line 120 of file MovieScenePreAnimatedCaptureSources.h.
References UE::MovieScene::TPreAnimatedCaptureSources< FMovieSceneEntityID >::StopTrackingCaptureSource().
The documentation for this struct was generated from the following file:
MovieScenePreAnimatedCaptureSources.h