Unreal Engine 5.6 C++ API: UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator Struct Reference
UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator Struct Reference
Utility class that generates a type table used for dynamic casting and instance of an ICastable object.
Public Member Functions
template<typename StartClass, typename T, typename U = decltype(T::ID)>
void AddStaticType (T *, int16 StartOffset)
template<typename StartClass>
constexpr void AddStaticType (void *, int16 StartOffset)
uint32 ByteSize () const
SEQUENCERCORE_API FCastableTypeTable * Commit (uint32 TypeID, FName InName)
Commit this generator to its final form.
template<typename StartClass>
void ConsumeImplements (...)
template<typename StartClass, typename T, typename U = typename T::Implements>
void ConsumeImplements (T *, int16 StartOffset)
template<typename StartClass, typename T>
void ConsumeImplements (void *, int16 StartOffset)
template<typename StartClass, typename ... Types>
void ConsumeImplementsImpl (TImplements< Types... > *, int16 StartOffset)
template<typename T>
void Generate ()
Generate the type table from a template type.
Static Public Member Functions
template<typename FromType, typename ToType>
static int16 ClassOffsetFrom ()
Compute the ptr offset from one class to another in an inheritance hierarchy.
template<typename T>
static int16 ComputeStartOffset (const ICastable *)
Compute the start offset from an ICastable type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an ICastable* to the concrete types.
template<typename T>
static int16 ComputeStartOffset (const IDynamicExtension *)
Compute the start offset from an IDynamicExtension type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an IDynamicExtension* to the concrete types.
Private Attributes
TArray< int16 > StaticTypeOffsets
MovieScene::TFixedSparseBitSet< uint32 > TypeMask
Detailed Description
Utility class that generates a type table used for dynamic casting and instance of an ICastable object.
Definition at line 123 of file CastableTypeTable.h.
Member Function Documentation
AddStaticType() [1/2]
template<typename StartClass, typename T, typename U = decltype(T::ID)> void UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::AddStaticType (T * , int16 StartOffset) inline
Definition at line 210 of file CastableTypeTable.h.
References ClassOffsetFrom(), ID, UE::MovieScene::NewlySet, StaticTypeOffsets, and TypeMask.
Referenced by ConsumeImplementsImpl(), and Generate().
AddStaticType() [2/2]
template<typename StartClass> void UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::AddStaticType (void * , int16 StartOffset) inline constexpr
Definition at line 225 of file CastableTypeTable.h.
ByteSize()
uint32 UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ByteSize () const inline
Definition at line 181 of file CastableTypeTable.h.
References UE::Sequencer::FCastableTypeTable::FCastableTypeTable(), and StaticTypeOffsets.
ClassOffsetFrom()
template<typename FromType, typename ToType> int16 UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ClassOffsetFrom () inline static
Compute the ptr offset from one class to another in an inheritance hierarchy.
Note
: This can be negative for situations where multiple inheritance would put the FromType class after the ToType in memory.
Definition at line 147 of file CastableTypeTable.h.
References Buffer, checkf, and TEXT.
Referenced by AddStaticType(), ComputeStartOffset(), and ComputeStartOffset().
Commit()
SEQUENCERCORE_API FCastableTypeTable * UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::Commit (uint32 TypeID, FName InName)
Commit this generator to its final form.
References UE::Sequencer::FCastableTypeTable::FCastableTypeTable(), and InName.
Referenced by UE::Sequencer::FCastableTypeTable::MakeTypeTable(), and UE::Sequencer::FCastableTypeTable::MakeTypeTable().
ComputeStartOffset() [1/2]
template<typename T> int16 UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ComputeStartOffset (const ICastable *) inline static
Compute the start offset from an ICastable type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an ICastable* to the concrete types.
Definition at line 165 of file CastableTypeTable.h.
References ClassOffsetFrom().
Referenced by Generate().
ComputeStartOffset() [2/2]
template<typename T> int16 UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ComputeStartOffset (const IDynamicExtension *) inline static
Compute the start offset from an IDynamicExtension type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an IDynamicExtension* to the concrete types.
Definition at line 176 of file CastableTypeTable.h.
References ClassOffsetFrom().
ConsumeImplements() [1/3]
template<typename StartClass> void UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ConsumeImplements (...) inline
Definition at line 193 of file CastableTypeTable.h.
ConsumeImplements() [2/3]
template<typename StartClass, typename T, typename U = typename T::Implements> void UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ConsumeImplements (T * , int16 StartOffset) inline
Definition at line 187 of file CastableTypeTable.h.
References ConsumeImplementsImpl().
Referenced by ConsumeImplementsImpl(), and Generate().
ConsumeImplements() [3/3]
template<typename StartClass, typename T> void UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ConsumeImplements (void * , int16 StartOffset) inline
Definition at line 205 of file CastableTypeTable.h.
ConsumeImplementsImpl()
template<typename StartClass, typename ... Types> void UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ConsumeImplementsImpl (TImplements< Types... > * , int16 StartOffset) inline
Definition at line 198 of file CastableTypeTable.h.
References AddStaticType(), and ConsumeImplements().
Referenced by ConsumeImplements().
Generate()
template<typename T> void UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::Generate () inline
Generate the type table from a template type.
Definition at line 129 of file CastableTypeTable.h.
References AddStaticType(), ComputeStartOffset(), and ConsumeImplements().
Referenced by UE::Sequencer::FCastableTypeTable::MakeTypeTable(), and UE::Sequencer::FCastableTypeTable::MakeTypeTable().
Field Documentation
StaticTypeOffsets
TArray<int16> UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::StaticTypeOffsets private
Definition at line 234 of file CastableTypeTable.h.
Referenced by AddStaticType(), and ByteSize().
TypeMask
MovieScene::TFixedSparseBitSet<uint32> UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::TypeMask private
Definition at line 232 of file CastableTypeTable.h.
Referenced by AddStaticType().
The documentation for this struct was generated from the following file:
CastableTypeTable.h