Unreal Engine 5.6 C++ API: CoreGlobals.h File Reference
CoreGlobals.h File Reference
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "HAL/PlatformTLS.h"
#include "Logging/LogMacros.h"
#include "Misc/Build.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/OutputDevice.h"
#include "ProfilingDebugging/CpuProfilerTrace.h"
#include "Templates/Atomic.h"
#include "UObject/NameTypes.h"
#include <atomic>
Data Structures
struct FCoreTexts
struct FEngineTrackedActivityScope
class FIsDuplicatingClassForReinstancing
class FIsEditorLoadingPackage
struct FLogCategoryLogContentComparisonCommandlet
struct FLogCategoryLogCore
struct FLogCategoryLogExec
struct FLogCategoryLogExit
struct FLogCategoryLogHAL
struct FLogCategoryLogInit
struct FLogCategoryLogLoad
struct FLogCategoryLogLocalization
struct FLogCategoryLogLongPackageNames
struct FLogCategoryLogMemory
struct FLogCategoryLogNetPackageMap
struct FLogCategoryLogNetSerialization
struct FLogCategoryLogOutputDevice
struct FLogCategoryLogProcess
struct FLogCategoryLogProfilingDebugging
struct FLogCategoryLogScript
struct FLogCategoryLogSerialization
struct FLogCategoryLogSHA
struct FLogCategoryLogStats
struct FLogCategoryLogStreaming
struct FLogCategoryLogTemp
struct FLogCategoryLogUnrealMath
struct FLogCategoryLogUnrealMatrix
struct FLogCategoryLogVirtualization
class FOptionalTaskTagScope
This class can be used to Tag an execution context but only in case it has not already been tagged It is usually used for the IsInRendering/GamethreadFunctions.
class FPlayInEditorID
struct FScopedBootTiming
struct FScopedLoadingState
class FTaskTagScope
This class can be used to Tag an execution context aka Thead or Job and allows us to later query the state when we are in the callstack It is usually used for the IsInRendering/GamethreadFunctions.
struct FUELibraryOverrideSettings
The settings used by the UE-as-a-library feature.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::CoreUObject
namespace UE::CoreUObject::Private
namespace UE::Private
The global memory allocator.
Macros
#define DECLARE_LOG_CATEGORY_EXTERN_HELPER(A, B, C)
#define GFirstFrameIntraFrameDebugging false
#define GIntraFrameDebuggingGameThread false
#define GIsEditor false
#define GLog GetGlobalLogSingleton()
#define SCOPED_BOOT_TIMING(x)
#define UE_SCOPED_ENGINE_ACTIVITY(Fmt, ...)
#define UE_SET_REQUEST_EXIT_ON_TICK_ONLY 0
Set this to true to only allow setting RequestingExit at the start of the Engine tick This will remove the chance for undefined behaviour when setting RequestExit.
Enumerations
enum class ELoaderType : uint8 { NotInitialized , LegacyLoader , EditorPackageLoader , ZenLoader }
enum class ETaskTag : int32 {
ENone = 0 << 0 , EStaticInit = 1 << 0 , EGameThread = 1 << 1 , ESlateThread = 1 << 2 ,
EAudioThread = 1 << 3 , ERenderingThread = 1 << 4 , ERhiThread = 1 << 5 , EAsyncLoadingThread = 1 << 6 ,
EEventThread = 1 << 7 , ENamedThreadBits = (EEventThread << 1) - 1 , EParallelThread = 1 << 30 , EWorkerThread = 1 << 29 | EParallelThread ,
EParallelRenderingThread = ERenderingThread | EParallelThread , EParallelGameThread = EGameThread | EParallelThread , EParallelRhiThread = ERhiThread | EParallelThread
}
Functions
void BeginExitIfRequested ()
This will check if a RequestExit has come in, if it has will set GIsRequestingExit.
void BootTimingPoint (const ANSICHAR *Message)
void DumpBootTiming ()
void EnsureRetrievingVTablePtrDuringCtor (const TCHAR *CtorSignature)
Ensures that current thread is during retrieval of vtable ptr of some UClass.
FString GetCommandletNameFromCmdline ()
Returns the name of the commandlet that was set on the command line by the arg '-Run=<CommandletName>'.
bool GetEmitDrawEvents ()
FOutputDeviceRedirector * GetGlobalLogSingleton ()
bool UE::GetIsEditorLoadingPackage ()
int32 UE::GetMultiprocessId ()
If multiple copies of the process are running and communicating together, the director process has MultiprocessId 0 and the worker processes have MultiprocessId > 0.
int32 UE::GetPlayInEditorID ()
UClass * GetRunningCommandletClass ()
Returns the UClass of the currently running commandlet.
bool IsAllowCommandletAudio ()
bool IsAllowCommandletRendering ()
Check to see if we should initialise RHI and set up scene for rendering even when running a commandlet.
bool IsAudioThreadRunning ()
bool IsEngineExitRequested ()
bool IsEngineStartupModuleLoadingComplete ()
Returns true after all initial modules have finished all of their loading phases during Engine startup: Corresponds to the event FCoreDelegates::OnAllModuleLoadingPhasesComplete.
bool IsInActualRenderingThread ()
bool IsInAnyRenderingThread ()
bool IsInAudioThread ()
bool IsInGameThread ()
bool IsInParallelGameThread ()
bool IsInParallelRenderingThread ()
bool IsInParallelRHIThread ()
bool IsInRenderingThread ()
bool IsInRHIThread ()
bool IsInSlateThread ()
bool IsRHIThreadRunning ()
bool IsRunningCommandlet ()
Check to see if this executable is running a commandlet (custom command-line processing code in an editor-like environment)
bool IsRunningCookCommandlet ()
Check to see if this executable is running the cookcommandlet.
bool IsRunningCookOnTheFly ()
bool IsRunningDLCCookCommandlet ()
Check to see if this executable is running the cookcommandlet.
bool IsThisNotNull (const void *This, const ANSICHAR *Function)
bool UE::IsUsingZenPakFileStreaming ()
const TCHAR * LexToString (ELoaderType Type)
void NotifyLoadingStateChanged (bool bState, const TCHAR *Message)
Boot loading timers.
constexpr bool operator! (ETaskTag E)
constexpr ETaskTag operator& (ETaskTag Lhs, ETaskTag Rhs)
ETaskTag & operator&= (ETaskTag &Lhs, ETaskTag Rhs)
constexpr ETaskTag operator^ (ETaskTag Lhs, ETaskTag Rhs)
ETaskTag & operator^= (ETaskTag &Lhs, ETaskTag Rhs)
constexpr ETaskTag operator| (ETaskTag Lhs, ETaskTag Rhs)
ETaskTag & operator|= (ETaskTag &Lhs, ETaskTag Rhs)
constexpr ETaskTag operator~ (ETaskTag E)
void RequestEngineExit (const FString &ReasonString)
void RequestEngineExit (const TCHAR *ReasonString)
void SetEmitDrawEvents (bool EmitDrawEvents)
void SetEngineStartupModuleLoadingComplete ()
void UE::SetIsEditorLoadingPackage (bool InValue)
void UE::Private::SetMultiprocessId (int32 MultiprocessId)
void UE::SetPlayInEditorID (int32 InPlayInEditorID)
Variables
bool GAllowActorScriptExecutionInEditor
allow AActor object to execute script in the editor from specific entry points, such as when running a construction script
bool GAreScreenMessagesEnabled
Global value indicating on-screen warnings/message should be displayed.
FString GCompatIni
bool GCompilingBlueprint
Forces use of template names for newly instanced components in a CDO.
FConfigCacheIni * GConfig
UE::CoreUObject::Private::FStoredObjectPathDebug * GCoreComplexObjectPathDebug
UE::Core::FVisualizerDebuggingState * GCoreDebuggingState
FChunkedFixedUObjectArray * GCoreObjectArrayForDebugVisualizers
UE::CoreUObject::Private::FObjectHandlePackageDebugData * GCoreObjectHandlePackageDebug
FLazyName GCurrentTraceName
Determines what kind of trace should occur, NAME_None for none.
int32 GCycleStatsShouldEmitNamedEvents
Whether stats should emit named events for e.g.
FExec * GDebugToolExec
Exec handler for game debugging tool, allowing commands like "editactor".
FString GDeviceProfilesIni
FString GEditorIni
Editor per-project ini files - stored per project.
FString GEditorKeyBindingsIni
FString GEditorLayoutIni
Editor ini file locations - stored per engine version (shared across all projects).
FString GEditorPerProjectIni
FString GEditorSettingsIni
bool GEdSelectionLock
bool GEnableVREditorHacks
Enables various editor and HMD hacks that allow the experimental VR editor feature to work, perhaps at the expense of other systems.
FString GEngineIni
class FOutputDeviceError * GError
TCHAR GErrorExceptionDescription [4096]
TCHAR GErrorHist [16384]
ELoaderType(* GetLoaderType)()
Returns the type of the currently active loader, if any.
bool GEventDrivenLoaderEnabled
bool GExitPurge
const FText GFalse
bool GFastPathUniqueNameGeneration
when constructing objects, use the fast path on consoles...
void(* GFlushStreamingFunc)(void)
Helper function to flush resource streaming.
bool GForceLoadEditorOnly
When saving out of the game, this override allows the game to load editor only properties.
const TCHAR * GForeignEngineDir
uint64 GFrameCounter
Steadily increasing frame counter.
uint64 GFrameCounterRenderThread
uint32 GFrameNumber
Incremented once per frame before the scene is being rendered.
uint32 GFrameNumberRenderThread
NEED TO RENAME, for RT version of GFrameTime use View.ViewFamily->FrameNumber or pass down from RT from GFrameTime).
FString GGameIni
FString GGameplayTagsIni
uint32 GGameThreadId
Thread ID of the main/game thread.
FString GGameUserSettingsIni
FString GHardwareIni
float GHitchThresholdMS
Threshold for a frame to be considered a hitch (in milliseconds).
bool GIgnoreDebugger
Whether we should ignore the attached debugger.
FString GInputIni
uint64 GInputTime
The time input was sampled, in cycles.
FString GInstallBundleIni
TCHAR GInternalProjectName [64]
bool GIsAutomationTesting
Whether or not a unit test is currently being run.
bool GIsBuildMachine
These are set when the engine first starts up.
bool GIsClient
bool GIsCookerLoadingPackage
Whether the cooker is currently loading a package or not.
bool GIsCriticalError
bool GIsDemoMode
Disables some warnings and minor features that would interrupt a demo presentation.
int32 GIsDumpingMovie
FIsDuplicatingClassForReinstancing GIsDuplicatingClassForReinstancing
FIsEditorLoadingPackage GIsEditorLoadingPackage
Whether the editor is currently loading a package or not.
bool GIsFirstInstance
Whether we are the first instance of the game running.
bool GIsGameAgnosticExe
If true, this executable is able to run all games (which are loaded as DLL's).
bool GIsGameThreadIdInitialized
Has GGameThreadId been set yet?
bool GIsGCingAfterBlueprintCompile
True if we're garbage collecting after a blueprint compilation.
bool GIsGuarded
bool GIsHighResScreenshot
bool GIsInitialLoad
Whether we are still in the initial loading process.
bool GIsPIEUsingPlayerStart
Whether or not PIE was attempting to play from PlayerStart.
bool GIsPlayInEditorWorld
Whether GWorld points to the play in editor world.
bool GIsReconstructingBlueprintInstances
True if we're reconstructing blueprint instances.
std::atomic< bool > GIsReinstancing
True if actors and objects are being re-instanced.
bool GIsRequestingExit
bool GIsRetrievingVTablePtr
true when we are retrieving VTablePtr from UClass
bool GIsRunning
bool GIsRunningRHIInDedicatedThread_InternalUseOnly
bool GIsRunningRHIInSeparateThread_InternalUseOnly
bool GIsRunningRHIInTaskThread_InternalUseOnly
bool GIsRunningUnattendedScript
bool GIsServer
bool GIsSilent
This determines if we should output any log text.
bool GIsSlowTask
uint64 GLastGCFrame
GFrameCounter the last time GC was run.
FString GLightmassIni
FOutputDeviceConsole * GLogConsole
FLazyName GLongCorePackageName
Name of the core package.
FLazyName GLongCoreUObjectPackageName
uint64 GMakeCacheIDIndex
float GNearClippingPlane
float GNearClippingPlane_RenderThread
const FText GNo
const FText GNone
bool GPlatformNeedsPowerOfTwoTextures
true if the runtime needs textures to be powers of two
FPlayInEditorID GPlayInEditorID
In the editor, this is set to the specific world context PIEInstance that is being currently processed.
bool GPrintLogCategory
How to print the category in log output.
ELogTimes::Type GPrintLogTimes
How to print the time in log output.
bool GPrintLogVerbosity
How to print the verbosity in log output.
bool GPumpingMessages
Whether or not messages are being pumped.
bool GPumpingMessagesOutsideOfMainLoop
Whether or not messages are being pumped outside of main loop.
FRunnableThread * GRenderingThread
Thread used for rendering.
uint32 GRenderThreadId
Thread ID of the render thread, if any.
FString GRuntimeOptionsIni
int32 GSavingCompressionChunkSize
Size to break up data into when saving compressed data.
FString GScalabilityIni
bool GScreenMessagesRestoreState
uint32 GScreenshotResolutionX
uint32 GScreenshotResolutionY
bool GShouldEmitVerboseNamedEvents
Whether verbose stats should be also generate external profiler named events.
uint32 GSlateLoadingThreadId
Thread ID of the slate thread, if any.
bool GSlowTaskOccurred
double GStartTime
Time at which FPlatformTime::Seconds() was first initialized (very early on)
FString GSystemStartTime
System time at engine init.
const FText GTrue
FUELibraryOverrideSettings GUELibraryOverrideSettings
Settings for when using UE as a library.
ITransaction * GUndo
bool GVerifyObjectReferencesOnly
Disable loading of objects not contained within script files; used during script compilation.
class FFeedbackContext * GWarn
const FText GYes
bool(* IsAsyncLoading)()
Whether we're currently in the async loading code path or not.
bool(* IsAsyncLoadingMultithreaded)()
Returns true if async loading is using the async loading thread.
bool(* IsAsyncLoadingSuspended)()
Suspends async package loading.
bool(* IsInAsyncLoadingThread)()
FLogCategoryLogContentComparisonCommandlet LogContentComparisonCommandlet
FLogCategoryLogCore LogCore
FLogCategoryLogExec LogExec
FLogCategoryLogExit LogExit
FLogCategoryLogHAL LogHAL
FLogCategoryLogInit LogInit
FLogCategoryLogLoad LogLoad
FLogCategoryLogLocalization LogLocalization
FLogCategoryLogLongPackageNames LogLongPackageNames
FLogCategoryLogMemory LogMemory
FLogCategoryLogNetPackageMap LogNetPackageMap
FLogCategoryLogNetSerialization LogNetSerialization
FLogCategoryLogOutputDevice LogOutputDevice
FLogCategoryLogProcess LogProcess
FLogCategoryLogProfilingDebugging LogProfilingDebugging
FLogCategoryLogScript LogScript
FLogCategoryLogSerialization LogSerialization
FLogCategoryLogSHA LogSHA
FLogCategoryLogStats LogStats
FLogCategoryLogStreaming LogStreaming
FLogCategoryLogTemp LogTemp
FLogCategoryLogUnrealMath LogUnrealMath
FLogCategoryLogUnrealMatrix LogUnrealMatrix
FLogCategoryLogVirtualization LogVirtualization
bool PRIVATE_GIsRunningCookCommandlet
bool PRIVATE_GIsRunningDLCCookCommandlet
void(* ResumeAsyncLoading)()
Resumes async package loading.
void(* ResumeTextureStreamingRenderTasks)()
Resume texture updates caused by completed async IOs.
void(* SuspendAsyncLoading)()
Suspends async package loading.
void(* SuspendTextureStreamingRenderTasks)()
Suspends texture updates caused by completed async IOs.
Macro Definition Documentation
DECLARE_LOG_CATEGORY_EXTERN_HELPER
#define DECLARE_LOG_CATEGORY_EXTERN_HELPER (A, B, C)
Value:
DECLARE_LOG_CATEGORY_EXTERN(A,B,C)
Definition at line 59 of file CoreGlobals.h.
GFirstFrameIntraFrameDebugging
#define GFirstFrameIntraFrameDebugging false
Definition at line 235 of file CoreGlobals.h.
GIntraFrameDebuggingGameThread
#define GIntraFrameDebuggingGameThread false
Definition at line 234 of file CoreGlobals.h.
Referenced by FSlateApplication::InKismetDebuggingMode(), and FSlateApplication::IsNormalExecution().
GIsEditor
#define GIsEditor false
Definition at line 233 of file CoreGlobals.h.
Referenced by FObjectReader::FObjectReader(), FObjectWriter::FObjectWriter(), IWaterBrushActorInterface::BroadcastWaterBrushActorChangedEvent(), FSkeletalMeshStreamIn::DoCancel(), FInstancedSkinnedMeshComponentHelper::GetComponentDesc(), FProperty::GetRepOwner(), FApp::IsGame(), FViewportClient::IsInPermanentCapture(), FReflectionCaptureData::OnDataUploadedToGPUFinal(), ILocalizedTextSource::ShouldLoadNativeGameData(), UCLASS(), MaterialInstance_Private::UpdateParameterSet_FullTraversal(), MaterialInstance_Private::UpdateParameterSet_WithCachedData(), and FDisplayClusterActorRef::UpdateWorldPtr().
GLog
#define GLog GetGlobalLogSingleton()
Definition at line 95 of file CoreGlobals.h.
Referenced by FScopedDurationTimeLogger::FScopedDurationTimeLogger(), DECLARE_MULTICAST_DELEGATE_OneParam(), FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState(), FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState(), UE::MediaIO::LogThrottle(), FNetworkPredictionDriverBase< ModelDef >::LogUserState(), FNetworkPredictionDriverBase< ModelDef >::LogUserStates(), FSkeletalMeshStreamIn_IO::SerializeLODData(), and StaticExec().
SCOPED_BOOT_TIMING
#define SCOPED_BOOT_TIMING (x)
Value:
TRACE_CPUPROFILER_EVENT_SCOPE_STR(x); FScopedBootTiming ANONYMOUS_VARIABLE(BootTiming_)(x);
Definition at line 91 of file CoreGlobals.h.
UE_SCOPED_ENGINE_ACTIVITY
#define UE_SCOPED_ENGINE_ACTIVITY (Fmt, ...)
Value:
FEngineTrackedActivityScope ANONYMOUS_VARIABLE(EngineActivity_)(Fmt, ## __VA_ARGS__);
Definition at line 92 of file CoreGlobals.h.
UE_SET_REQUEST_EXIT_ON_TICK_ONLY
#define UE_SET_REQUEST_EXIT_ON_TICK_ONLY 0
Set this to true to only allow setting RequestingExit at the start of the Engine tick This will remove the chance for undefined behaviour when setting RequestExit.
This needs to proved out on all platforms/use cases before this can moved to default
Definition at line 383 of file CoreGlobals.h.
Enumeration Type Documentation
ELoaderType
enum class ELoaderType : uint8 strong
Enumerator
NotInitialized
LegacyLoader
EditorPackageLoader
ZenLoader
Definition at line 477 of file CoreGlobals.h.
ETaskTag
enum class ETaskTag : int32 strong
Enumerator
ENone
EStaticInit
EGameThread
ESlateThread
EAudioThread
ERenderingThread
ERhiThread
EAsyncLoadingThread
EEventThread
ENamedThreadBits
EParallelThread
EWorkerThread
EParallelRenderingThread
EParallelGameThread
EParallelRhiThread
Definition at line 656 of file CoreGlobals.h.
Function Documentation
BeginExitIfRequested()
void BeginExitIfRequested () extern
This will check if a RequestExit has come in, if it has will set GIsRequestingExit.
References BeginExitIfRequested().
Referenced by BeginExitIfRequested().
BootTimingPoint()
void BootTimingPoint (const ANSICHAR * Message)
DumpBootTiming()
void DumpBootTiming ()
EnsureRetrievingVTablePtrDuringCtor()
void EnsureRetrievingVTablePtrDuringCtor (const TCHAR * CtorSignature)
Ensures that current thread is during retrieval of vtable ptr of some UClass.
Parameters
CtorSignature The signature of the ctor currently running to construct proper error message.
Referenced by FVTableHelper::FVTableHelper(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::TOctree_DEPRECATED(), TQuadTree< ElementType, NodeCapacity >::TQuadTree(), and TSharedRef< INavigationToolItem >::TSharedRef().
GetCommandletNameFromCmdline()
FString GetCommandletNameFromCmdline ()
Returns the name of the commandlet that was set on the command line by the arg '-Run=<CommandletName>'.
This should be used by code that needs to know the commandlet name early on during engine startup, before the commandlet has been initialized. If possible, code should prefer calling GetRunningCommandletClass()->GetName() instead.
Returns
The name of the commandlet that will end up running. If there is no commandlet then an empty string will be returned.
GetEmitDrawEvents()
bool GetEmitDrawEvents ()
GetGlobalLogSingleton()
FOutputDeviceRedirector * GetGlobalLogSingleton ()
GetRunningCommandletClass()
UClass * GetRunningCommandletClass ()
Returns the UClass of the currently running commandlet.
Definition at line 283 of file CoreGlobals.h.
References FORCEINLINE.
IsAllowCommandletAudio()
bool IsAllowCommandletAudio ()
Definition at line 318 of file CoreGlobals.h.
References FORCEINLINE.
Referenced by FApp::CanEverRenderAudio().
IsAllowCommandletRendering()
bool IsAllowCommandletRendering ()
Check to see if we should initialise RHI and set up scene for rendering even when running a commandlet.
Definition at line 309 of file CoreGlobals.h.
References FORCEINLINE.
Referenced by FApp::CanEverRender(), and UE::PixelStreaming2::IsStreamingSupported().
IsAudioThreadRunning()
bool IsAudioThreadRunning () extern
IsEngineExitRequested()
bool IsEngineExitRequested ()
Definition at line 401 of file CoreGlobals.h.
References FORCEINLINE, GIsRequestingExit, IsEngineExitRequested(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by FDisplayClusterActorRef::GetOrFindSceneActor(), IsEngineExitRequested(), TWidgetFactory< UUserWidget >::Reset(), FGlobalCueTypeTable::UnregisterCueType(), and FGlobalCueTypeTable::UnregisterDispatchTableCallback().
IsEngineStartupModuleLoadingComplete()
bool IsEngineStartupModuleLoadingComplete () extern
Returns true after all initial modules have finished all of their loading phases during Engine startup: Corresponds to the event FCoreDelegates::OnAllModuleLoadingPhasesComplete.
IsInActualRenderingThread()
bool IsInActualRenderingThread () extern
Returns
True if called from the rendering thread.
References GRenderingThread, and IsInAsyncLoadingThread.
Referenced by ENUM_CLASS_FLAGS(), and TConsoleVariableData< T >::GetShadowIndex().
IsInAnyRenderingThread()
bool IsInAnyRenderingThread () extern
Returns
True if called from any of the rendering thread. Can be called from any thread without asserting.
IsInAudioThread()
bool IsInAudioThread () extern
Returns
True if called from the audio thread, and not merely a thread calling audio functions.
Referenced by FAudioDevice::GetActiveSounds(), FAudioDevice::GetEffects(), FAudioDevice::GetEffects(), FAudioDevice::GetGlobalPitchScale(), FAudioDevice::GetListeners(), FAudioDevice::GetPlatformAudioHeadroom(), FAudioDevice::GetSoundClassPropertyMap(), FAudioDevice::GetTransientPrimaryVolume(), and FAudioDevice::UE_DEPRECATED().
IsInGameThread()
bool IsInGameThread () extern
Returns
True if called from the game thread.
Referenced by FActorIteratorState::FActorIteratorState(), FCookStats::FScopedStatsCounter::FScopedStatsCounter(), FTickableCookObject::FTickableCookObject(), FTickableEditorObject::FTickableEditorObject(), FTickableCookObject::~FTickableCookObject(), FTickableEditorObject::~FTickableEditorObject(), UE::MovieScene::FSharedPlaybackState::AddCapability(), UE::MovieScene::FSharedPlaybackState::AddCapabilityRaw(), UE::MovieScene::FSharedPlaybackState::AddCapabilityShared(), FMaterialShaderMap::AddCompilingMaterialExternalDependency(), FLightMap::AddRef(), FShadowMap::AddRef(), FSkyTextureCubeResource::AddRef(), FInGameCycleCounter::Begin(), CheckNotBlockedOnRenderThread(), FQuartLatencyTracker::DigestQueue(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity(), UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerEntity(), UE::PixelStreaming2::DoOnGameThread(), UE::PixelStreaming2::DoOnGameThreadAndWait(), FInGameCycleCounter::End(), TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe(), TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe(), TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ExecuteIfSafe(), UE::MovieScene::FSharedPlaybackState::FindCapability(), FSlateApplication::Get(), UParticleSystemComponent::GetAsyncBounds(), UParticleSystemComponent::GetAsyncComponentToWorld(), UParticleSystemComponent::GetAsyncInstanceParameters(), UParticleSystemComponent::GetAsyncPartSysVelocity(), UE::MovieScene::FSharedPlaybackState::GetCapabilities(), UE::MovieScene::FSharedPlaybackState::GetCapabilities(), FUObjectMigrationContext::GetCurrentMigrationContext(), FAudioDevice::GetCurrentReverbEffect(), ICommonUIModule::GetEditorSettings(), FMaterial::GetGameThreadShaderMap(), SVirtualKeyboardEntry::GetHintText(), FQuartLatencyTracker::GetLifetimeAverageLatency(), FQuartLatencyTracker::GetMaxLatency(), FQuartLatencyTracker::GetMinLatency(), FSlateWindowElementList::GetPaintWindow(), FStreamableTextureResource::GetPostInitState(), UWorldProxy::GetReference(), FSlateWindowElementList::GetRenderWindow(), FDynamicResolutionHeuristicProxy::GetResolutionFractionsApproximation_GameThread(), ICommonUIModule::GetSettings(), TConsoleVariableData< T >::GetShadowIndex(), SVirtualKeyboardEntry::GetText(), SVirtualKeyboardEntry::GetVirtualKeyboardOptions(), SVirtualKeyboardEntry::GetVirtualKeyboardType(), UE::MovieScene::FSharedPlaybackState::HasCapability(), FMaterial::IsGameThreadShaderMapComplete(), SVirtualKeyboardEntry::IsIntegratedKeyboardEnabled(), SVirtualKeyboardEntry::IsMultilineEntry(), FUObjectArray::LockInternalArray(), UWorldProxy::operator UWorld *(), UWorldProxy::operator*(), UWorldProxy::operator*(), UWorldProxy::operator->(), UWorldProxy::operator->(), FQuartLatencyTracker::PushLatencyTrackerResult(), FLightMap::Release(), FShadowMap::Release(), FMaterialShaderMap::RemoveCompilingMaterialExternalDependency(), FUObjectMigrationContext::SetCurrentMigrationContext(), FRenderCommandPipe::SetEnabled(), UE::MovieScene::FSharedPlaybackState::SetOrAddCapability(), UE::MovieScene::FSharedPlaybackState::SetOrAddCapabilityRaw(), UE::MovieScene::FSharedPlaybackState::SetOrAddCapabilityShared(), and USTRUCT().
IsInParallelGameThread()
bool IsInParallelGameThread () extern
Returns
True if called from the game thread in a parallel for.
Referenced by FMaterial::GetGameThreadShaderMap(), TConsoleVariableData< T >::GetShadowIndex(), and FMaterial::IsGameThreadShaderMapComplete().
IsInParallelRenderingThread()
bool IsInParallelRenderingThread () extern
Returns
True if called from the rendering thread, or if called from ANY thread that isn't the game thread, except that during single threaded rendering the game thread is ok too.
Referenced by UE::SVT::FTextureRenderResources::GetFrameIndex(), UE::SVT::FTextureRenderResources::GetHeader(), UE::SVT::FTextureRenderResources::GetNumLogicalMipLevels(), UE::SVT::FTextureRenderResources::GetPageTableTexture(), UE::SVT::FTextureRenderResources::GetPhysicalTileDataATexture(), UE::SVT::FTextureRenderResources::GetPhysicalTileDataBTexture(), UE::SVT::FTextureRenderResources::GetTileDataTextureResolution(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::GetUniformBufferRHI(), TConsoleVariableData< T >::GetValueOnRenderThread(), FMaterial::IsRenderingThreadShaderMapComplete(), FRenderCommandPipe::IsReplaying(), and FDynamicResolutionHeuristicProxy::QueryCurrentFrameResolutionFractions().
IsInParallelRHIThread()
bool IsInParallelRHIThread () extern
Returns
True if called from a thread tagged as an RHI task.
References GIsRunningRHIInDedicatedThread_InternalUseOnly, GIsRunningRHIInSeparateThread_InternalUseOnly, GIsRunningRHIInTaskThread_InternalUseOnly, and IsInParallelRHIThread().
Referenced by IsInParallelRHIThread().
IsInRenderingThread()
bool IsInRenderingThread () extern
Returns
True if called from the rendering thread, or if called from ANY thread during single threaded rendering
Referenced by FSkelMeshUpdateContext::FSkelMeshUpdateContext(), FDummyViewport::BeginRenderFrame(), FSkeletalMeshStreamIn::DoFinishUpdate(), FDummyViewport::EndRenderFrame(), FRenderCommandPipe::Enqueue(), EnqueueUniqueRenderCommand(), FStreamableTextureResource::GetState(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::GetUniformBufferRHI(), TGlobalResource< FGlobalBoundShaderStateResource >::InitGlobalResource(), FTickableObjectRenderThread::Register(), FSkeletalMeshStreamOut::ReleaseBuffers(), TGlobalResource< FGlobalBoundShaderStateResource >::ReleaseGlobalResource(), FPlanarReflectionRenderTarget::SetActiveGPUMask(), FTextureRenderTargetResource::SetActiveGPUMask(), FTextureRenderTargetResource::SetGPUMask(), TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::Tick(), and FTickableObjectRenderThread::Unregister().
IsInRHIThread()
bool IsInRHIThread () extern
Returns
True if called from the RHI thread, or if called from ANY thread during single threaded rendering
References IsInRHIThread().
Referenced by IsInRHIThread().
IsInSlateThread()
bool IsInSlateThread () extern
Returns
True if called from the slate thread, and not merely a thread calling slate functions.
Referenced by FSlateApplication::Get(), FSlateWindowElementList::GetPaintWindow(), and FSlateWindowElementList::GetRenderWindow().
IsRHIThreadRunning()
bool IsRHIThreadRunning () extern
Returns
True if RHI thread is running
References IsRHIThreadRunning().
Referenced by IsRHIThreadRunning().
IsRunningCommandlet()
bool IsRunningCommandlet ()
Check to see if this executable is running a commandlet (custom command-line processing code in an editor-like environment)
Definition at line 247 of file CoreGlobals.h.
References FORCEINLINE.
Referenced by FApp::CanEverRender(), FApp::CanEverRenderAudio(), TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >::Discard(), and UE::PixelStreaming2::IsStreamingSupported().
IsRunningCookCommandlet()
bool IsRunningCookCommandlet ()
Check to see if this executable is running the cookcommandlet.
Definition at line 259 of file CoreGlobals.h.
References FORCEINLINE, and PRIVATE_GIsRunningCookCommandlet.
Referenced by ISoundWaveLoadingBehaviorUtil::Get().
IsRunningCookOnTheFly()
bool IsRunningCookOnTheFly ()
Returns
True if running cook-on-the-fly.
IsRunningDLCCookCommandlet()
bool IsRunningDLCCookCommandlet ()
Check to see if this executable is running the cookcommandlet.
Definition at line 271 of file CoreGlobals.h.
References FORCEINLINE, and PRIVATE_GIsRunningDLCCookCommandlet.
IsThisNotNull()
bool IsThisNotNull (const void * This, const ANSICHAR * Function)
References FORCENOINLINE, Function, and IsThisNotNull().
Referenced by FField::GetFName(), FField::GetName(), FField::GetName(), and IsThisNotNull().
LexToString()
const TCHAR * LexToString (ELoaderType Type)
References GetLoaderType, ResumeTextureStreamingRenderTasks, and SuspendTextureStreamingRenderTasks.
NotifyLoadingStateChanged()
void NotifyLoadingStateChanged (bool bState, const TCHAR * Message)
Boot loading timers.
Referenced by FScopedLoadingState::FScopedLoadingState(), and FScopedLoadingState::~FScopedLoadingState().
operator!()
bool operator! (ETaskTag E) inline constexpr
Definition at line 676 of file CoreGlobals.h.
operator&()
ETaskTag operator& (ETaskTag Lhs, ETaskTag Rhs) inline constexpr
Definition at line 676 of file CoreGlobals.h.
operator&=()
ETaskTag & operator&= (ETaskTag & Lhs, ETaskTag Rhs) inline
Definition at line 676 of file CoreGlobals.h.
operator^()
ETaskTag operator^ (ETaskTag Lhs, ETaskTag Rhs) inline constexpr
Definition at line 676 of file CoreGlobals.h.
operator^=()
ETaskTag & operator^= (ETaskTag & Lhs, ETaskTag Rhs) inline
Definition at line 676 of file CoreGlobals.h.
operator|()
ETaskTag operator| (ETaskTag Lhs, ETaskTag Rhs) inline constexpr
Definition at line 676 of file CoreGlobals.h.
operator|=()
ETaskTag & operator|= (ETaskTag & Lhs, ETaskTag Rhs) inline
Definition at line 676 of file CoreGlobals.h.
operator~()
ETaskTag operator~ (ETaskTag E) inline constexpr
Definition at line 676 of file CoreGlobals.h.
RequestEngineExit() [1/2]
void RequestEngineExit (const FString & ReasonString)
References GAreScreenMessagesEnabled, GCompatIni, GDebugToolExec, GDeviceProfilesIni, GEditorIni, GEditorKeyBindingsIni, GEditorLayoutIni, GEditorPerProjectIni, GEditorSettingsIni, GEngineIni, GExitPurge, GForeignEngineDir, GGameIni, GGameplayTagsIni, GGameUserSettingsIni, GHardwareIni, GInputIni, GInstallBundleIni, GInternalProjectName, GIsDumpingMovie, GIsHighResScreenshot, GLightmassIni, GMakeCacheIDIndex, GNearClippingPlane, GNearClippingPlane_RenderThread, GRuntimeOptionsIni, GScalabilityIni, GScreenMessagesRestoreState, GScreenshotResolutionX, GScreenshotResolutionY, IsAsyncLoading, IsAsyncLoadingMultithreaded, IsAsyncLoadingSuspended, ResumeAsyncLoading, and SuspendAsyncLoading.
RequestEngineExit() [2/2]
void RequestEngineExit (const TCHAR * ReasonString)
SetEmitDrawEvents()
void SetEmitDrawEvents (bool EmitDrawEvents)
References GCoreObjectArrayForDebugVisualizers.
SetEngineStartupModuleLoadingComplete()
void SetEngineStartupModuleLoadingComplete () extern
References GIsRequestingExit.
Variable Documentation
GAllowActorScriptExecutionInEditor
bool GAllowActorScriptExecutionInEditor extern
allow AActor object to execute script in the editor from specific entry points, such as when running a construction script
GAreScreenMessagesEnabled
bool GAreScreenMessagesEnabled extern
Global value indicating on-screen warnings/message should be displayed.
Disabled via console command "DISABLEALLSCREENMESSAGES" Enabled via console command "ENABLEALLSCREENMESSAGES" Toggled via console command "TOGGLEALLSCREENMESSAGES"
Referenced by RequestEngineExit().
GCompatIni
FString GCompatIni extern
Referenced by RequestEngineExit().
GCompilingBlueprint
bool GCompilingBlueprint extern
Forces use of template names for newly instanced components in a CDO.
GConfig
FConfigCacheIni* GConfig extern
Referenced by FConfigContext::FixupBranchAfterBinaryConfig(), FConfigContext::ForceReloadIntoGConfig(), FGPUDriverHelper::GetBestConfigEntry(), FPersistentStorageManager::IsReady(), FConfigCacheIni::LoadGlobalIniFile(), FConfigContext::ReadIntoGConfig(), FConfigContext::ReadSingleIntoConfigSystem(), FConfigContext::ReadSingleIntoGConfig(), UObject::SaveConfig(), and FNodeTextCache::UpdateCacheIternal().
GCoreComplexObjectPathDebug
UE::CoreUObject::Private::FStoredObjectPathDebug* GCoreComplexObjectPathDebug extern
GCoreDebuggingState
UE::Core::FVisualizerDebuggingState* GCoreDebuggingState extern
GCoreObjectArrayForDebugVisualizers
FChunkedFixedUObjectArray* GCoreObjectArrayForDebugVisualizers extern
Referenced by SetEmitDrawEvents().
GCoreObjectHandlePackageDebug
UE::CoreUObject::Private::FObjectHandlePackageDebugData* GCoreObjectHandlePackageDebug extern
GCurrentTraceName
FLazyName GCurrentTraceName extern
Determines what kind of trace should occur, NAME_None for none.
GCycleStatsShouldEmitNamedEvents
int32 GCycleStatsShouldEmitNamedEvents extern
Whether stats should emit named events for e.g.
PIX.
Referenced by SWidget::GetStatID(), and UObjectBaseUtility::GetStatID().
GDebugToolExec
FExec* GDebugToolExec extern
Exec handler for game debugging tool, allowing commands like "editactor".
Referenced by RequestEngineExit().
GDeviceProfilesIni
FString GDeviceProfilesIni extern
Referenced by RequestEngineExit().
GEditorIni
FString GEditorIni extern
Editor per-project ini files - stored per project.
Referenced by FBoolConfigValueHelper::FBoolConfigValueHelper(), and RequestEngineExit().
GEditorKeyBindingsIni
FString GEditorKeyBindingsIni extern
Referenced by RequestEngineExit().
GEditorLayoutIni
FString GEditorLayoutIni extern
Editor ini file locations - stored per engine version (shared across all projects).
Migrated between versions on first run.
Referenced by FAssetEditorToolkit::HandleTabManagerPersistLayout(), and RequestEngineExit().
GEditorPerProjectIni
FString GEditorPerProjectIni extern
Referenced by FSuppressableWarningDialog::FSetupInfo::FSetupInfo(), and RequestEngineExit().
GEditorSettingsIni
FString GEditorSettingsIni extern
Referenced by RequestEngineExit(), and FNodeTextCache::UpdateCacheIternal().
GEdSelectionLock
bool GEdSelectionLock extern
GEnableVREditorHacks
bool GEnableVREditorHacks extern
Enables various editor and HMD hacks that allow the experimental VR editor feature to work, perhaps at the expense of other systems.
GEngineIni
FString GEngineIni extern
Referenced by FSystemSettingsData::LoadFromIni(), and RequestEngineExit().
GError
class FOutputDeviceError* GError extern
GErrorExceptionDescription
TCHAR GErrorExceptionDescription[4096] extern
GErrorHist
TCHAR GErrorHist[16384] extern
GetLoaderType
ELoaderType(* GetLoaderType) () () extern
Returns the type of the currently active loader, if any.
Referenced by LexToString().
GEventDrivenLoaderEnabled
bool GEventDrivenLoaderEnabled extern
GExitPurge
bool GExitPurge extern
Referenced by RequestEngineExit().
GFalse
const FText GFalse extern
GFastPathUniqueNameGeneration
bool GFastPathUniqueNameGeneration extern
when constructing objects, use the fast path on consoles...
GFlushStreamingFunc
void(* GFlushStreamingFunc) (void) (void) extern
Helper function to flush resource streaming.
GForceLoadEditorOnly
bool GForceLoadEditorOnly extern
When saving out of the game, this override allows the game to load editor only properties.
GForeignEngineDir
const TCHAR* GForeignEngineDir extern
Referenced by RequestEngineExit().
GFrameCounter
uint64 GFrameCounter extern
Steadily increasing frame counter.
Referenced by FAISightQuery::FAISightQuery(), FDelayUntilNextTickAction::FDelayUntilNextTickAction(), TFrameValue< ValueType >::TFrameValue(), TFrameValue< ValueType >::TFrameValue(), TFrameValue< ValueType >::TFrameValue(), TFrameValue< ValueType >::TFrameValue(), TFrameValue< ValueType >::TFrameValue(), FAISightQuery::GetAge(), FLinkedBoxManager::GetUniformCellSize(), TFrameValue< ValueType >::GetValue(), FTimerManager::HasBeenTickedThisFrame(), FGraphTraversalCounter::Increment(), FEditorViewportClient::IsRealtime(), TFrameValue< ValueType >::IsSet(), FAISightQuery::OnProcessed(), TFrameValue< ValueType >::operator=(), TFrameValue< ValueType >::operator=(), TFrameValue< ValueType >::operator=(), TFrameValue< ValueType >::operator=(), FEditorViewportClient::RequestRealTimeFrames(), FDelayUntilNextTickAction::UpdateOperation(), and FGraphTraversalCounter::WasSynchronizedLastFrame().
GFrameCounterRenderThread
uint64 GFrameCounterRenderThread extern
GFrameNumber
uint32 GFrameNumber extern
Incremented once per frame before the scene is being rendered.
In split screen mode this is incremented once for all views (not for each view).
Referenced by USkeletalMeshComponent::FPendingRadialForces::FPendingRadialForces(), ENUM_CLASS_FLAGS(), and FCachedLandscapeFoliage::FGrassComp::Touch().
GFrameNumberRenderThread
uint32 GFrameNumberRenderThread extern
NEED TO RENAME, for RT version of GFrameTime use View.ViewFamily->FrameNumber or pass down from RT from GFrameTime).
Referenced by FFoliageOcclusionResults::FFoliageOcclusionResults(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::DrainPool(), TAllocRecordingLog< FModifier, FAllocOp >::RecordAlloc(), TAllocRecordingLog< FModifier, FAllocOp >::RecordFree(), and TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleasePooledResource().
GGameIni
FString GGameIni extern
Referenced by RequestEngineExit().
GGameplayTagsIni
FString GGameplayTagsIni extern
Referenced by RequestEngineExit().
GGameThreadId
uint32 GGameThreadId extern
Thread ID of the main/game thread.
Referenced by FThreadManager::GetThreadName().
GGameUserSettingsIni
FString GGameUserSettingsIni extern
Referenced by RequestEngineExit().
GHardwareIni
FString GHardwareIni extern
Referenced by FGPUDriverHelper::GetBestConfigEntry(), and RequestEngineExit().
GHitchThresholdMS
float GHitchThresholdMS extern
Threshold for a frame to be considered a hitch (in milliseconds).
GIgnoreDebugger
bool GIgnoreDebugger extern
Whether we should ignore the attached debugger.
GInputIni
FString GInputIni extern
Referenced by RequestEngineExit().
GInputTime
uint64 GInputTime extern
The time input was sampled, in cycles.
GInstallBundleIni
FString GInstallBundleIni extern
Referenced by RequestEngineExit().
GInternalProjectName
TCHAR GInternalProjectName[64] extern
Referenced by FApp::GetProjectName(), FApp::HasProjectName(), FApp::IsProjectNameEmpty(), RequestEngineExit(), and FApp::SetProjectName().
GIsAutomationTesting
bool GIsAutomationTesting extern
Whether or not a unit test is currently being run.
GIsBuildMachine
bool GIsBuildMachine extern
These are set when the engine first starts up.
This specifies whether the engine was launched as a build machine process.
GIsClient
bool GIsClient extern
GIsCookerLoadingPackage
bool GIsCookerLoadingPackage extern
Whether the cooker is currently loading a package or not.
GIsCriticalError
bool GIsCriticalError extern
Referenced by FMemStackBase::~FMemStackBase(), TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::~TAllocatorFixedSizeFreeList(), FMallocDebug::Free(), FPersistentStorageManager::IsReady(), FMallocDebug::Malloc(), FMallocDebug::Realloc(), and FMallocDebug::ValidateHeap().
GIsDemoMode
bool GIsDemoMode extern
Disables some warnings and minor features that would interrupt a demo presentation.
Referenced by UCLASS().
GIsDumpingMovie
int32 GIsDumpingMovie extern
Referenced by RequestEngineExit().
GIsDuplicatingClassForReinstancing
FIsDuplicatingClassForReinstancing GIsDuplicatingClassForReinstancing extern
GIsEditorLoadingPackage
FIsEditorLoadingPackage GIsEditorLoadingPackage extern
Whether the editor is currently loading a package or not.
GIsFirstInstance
bool GIsFirstInstance extern
Whether we are the first instance of the game running.
GIsGameAgnosticExe
bool GIsGameAgnosticExe extern
If true, this executable is able to run all games (which are loaded as DLL's).
GIsGameThreadIdInitialized
bool GIsGameThreadIdInitialized extern
Has GGameThreadId been set yet?
GIsGCingAfterBlueprintCompile
bool GIsGCingAfterBlueprintCompile extern
True if we're garbage collecting after a blueprint compilation.
GIsGuarded
bool GIsGuarded extern
GIsHighResScreenshot
bool GIsHighResScreenshot extern
Referenced by RequestEngineExit().
GIsInitialLoad
bool GIsInitialLoad extern
Whether we are still in the initial loading process.
GIsPIEUsingPlayerStart
bool GIsPIEUsingPlayerStart extern
Whether or not PIE was attempting to play from PlayerStart.
GIsPlayInEditorWorld
bool GIsPlayInEditorWorld extern
Whether GWorld points to the play in editor world.
Referenced by FApp::IsGame().
GIsReconstructingBlueprintInstances
bool GIsReconstructingBlueprintInstances extern
True if we're reconstructing blueprint instances.
Should never be true on cooked builds
GIsReinstancing
std::atomic<bool> GIsReinstancing extern
True if actors and objects are being re-instanced.
GIsRequestingExit
bool GIsRequestingExit extern
Referenced by IsEngineExitRequested(), and SetEngineStartupModuleLoadingComplete().
GIsRetrievingVTablePtr
bool GIsRetrievingVTablePtr extern
true when we are retrieving VTablePtr from UClass
GIsRunning
bool GIsRunning extern
GIsRunningRHIInDedicatedThread_InternalUseOnly
bool GIsRunningRHIInDedicatedThread_InternalUseOnly extern
Referenced by IsInParallelRHIThread().
GIsRunningRHIInSeparateThread_InternalUseOnly
bool GIsRunningRHIInSeparateThread_InternalUseOnly extern
Referenced by IsInParallelRHIThread().
GIsRunningRHIInTaskThread_InternalUseOnly
bool GIsRunningRHIInTaskThread_InternalUseOnly extern
Referenced by IsInParallelRHIThread().
GIsRunningUnattendedScript
bool GIsRunningUnattendedScript extern
GIsServer
bool GIsServer extern
GIsSilent
bool GIsSilent extern
This determines if we should output any log text.
If Yes then no log text should be emitted.
GIsSlowTask
bool GIsSlowTask extern
Referenced by FUnixFeedbackContext::BeginSlowTask(), FUnixFeedbackContext::EndSlowTask(), FFeedbackContext::FinalizeSlowTask(), and FFeedbackContext::StartSlowTask().
GLastGCFrame
uint64 GLastGCFrame extern
GFrameCounter the last time GC was run.
GLightmassIni
FString GLightmassIni extern
Referenced by RequestEngineExit().
GLogConsole
FOutputDeviceConsole* GLogConsole extern
GLongCorePackageName
FLazyName GLongCorePackageName extern
Name of the core package.
GLongCoreUObjectPackageName
FLazyName GLongCoreUObjectPackageName extern
GMakeCacheIDIndex
uint64 GMakeCacheIDIndex extern
Referenced by RequestEngineExit().
GNearClippingPlane
float GNearClippingPlane extern
Referenced by FDisplayClusterLightCardEditorHelper::GetSceneViewInitOptions(), RequestEngineExit(), and USTRUCT().
GNearClippingPlane_RenderThread
float GNearClippingPlane_RenderThread extern
Referenced by RequestEngineExit().
GNo
const FText GNo extern
GNone
const FText GNone extern
GPlatformNeedsPowerOfTwoTextures
bool GPlatformNeedsPowerOfTwoTextures extern
true if the runtime needs textures to be powers of two
GPlayInEditorID
FPlayInEditorID GPlayInEditorID extern
In the editor, this is set to the specific world context PIEInstance that is being currently processed.
GPrintLogCategory
bool GPrintLogCategory extern
How to print the category in log output.
GPrintLogTimes
ELogTimes::Type GPrintLogTimes extern
How to print the time in log output.
GPrintLogVerbosity
bool GPrintLogVerbosity extern
How to print the verbosity in log output.
GPumpingMessages
bool GPumpingMessages extern
Whether or not messages are being pumped.
GPumpingMessagesOutsideOfMainLoop
bool GPumpingMessagesOutsideOfMainLoop extern
Whether or not messages are being pumped outside of main loop.
GRenderingThread
FRunnableThread* GRenderingThread extern
Thread used for rendering.
Referenced by IsInActualRenderingThread().
GRenderThreadId
uint32 GRenderThreadId extern
Thread ID of the render thread, if any.
Referenced by FThreadManager::GetThreadName().
GRuntimeOptionsIni
FString GRuntimeOptionsIni extern
Referenced by RequestEngineExit().
GSavingCompressionChunkSize
int32 GSavingCompressionChunkSize extern
Size to break up data into when saving compressed data.
GScalabilityIni
FString GScalabilityIni extern
Referenced by RequestEngineExit().
GScreenMessagesRestoreState
bool GScreenMessagesRestoreState extern
Referenced by RequestEngineExit().
GScreenshotResolutionX
uint32 GScreenshotResolutionX extern
Referenced by RequestEngineExit().
GScreenshotResolutionY
uint32 GScreenshotResolutionY extern
Referenced by RequestEngineExit().
GShouldEmitVerboseNamedEvents
bool GShouldEmitVerboseNamedEvents extern
Whether verbose stats should be also generate external profiler named events.
Thread sleep/wait stats or extremely high frequency cycle counting stats are disabled by default. Has no effect if GCycleStatsShouldEmitNamedEvents is 0.
GSlateLoadingThreadId
uint32 GSlateLoadingThreadId extern
Thread ID of the slate thread, if any.
GSlowTaskOccurred
bool GSlowTaskOccurred extern
GStartTime
double GStartTime extern
Time at which FPlatformTime::Seconds() was first initialized (very early on)
GSystemStartTime
FString GSystemStartTime extern
System time at engine init.
GTrue
const FText GTrue extern
GUELibraryOverrideSettings
FUELibraryOverrideSettings GUELibraryOverrideSettings extern
Settings for when using UE as a library.
GUndo
ITransaction* GUndo extern
GVerifyObjectReferencesOnly
bool GVerifyObjectReferencesOnly extern
Disable loading of objects not contained within script files; used during script compilation.
GWarn
class FFeedbackContext* GWarn extern
Referenced by FBodySetupObjectTextFactory::FBodySetupObjectTextFactory(), FMorphTargetBinaryImport::FMorphTargetBinaryImport(), FMorphTargetBinaryImport::FMorphTargetBinaryImport(), FScopedSlowTask::FScopedSlowTask(), FSlowTask::FSlowTask(), FPkgInfoReporter_Log::GeneratePackageReport(), PropertyAccessUtil::ImportDefaultPropertyValue(), ImportObject(), FProperty::ImportText_Direct(), FProperty::ImportText_InContainer(), FArrayProperty::ImportTextInnerItem(), and SavePackageHelper().
GYes
const FText GYes extern
IsAsyncLoading
bool(* IsAsyncLoading) () () extern
Whether we're currently in the async loading code path or not.
Referenced by RequestEngineExit(), and FLinkerLoad::ShouldReportProgress().
IsAsyncLoadingMultithreaded
bool(* IsAsyncLoadingMultithreaded) () () extern
Returns true if async loading is using the async loading thread.
Referenced by RequestEngineExit().
IsAsyncLoadingSuspended
bool(* IsAsyncLoadingSuspended) () () extern
Suspends async package loading.
Referenced by RequestEngineExit().
IsInAsyncLoadingThread
bool(* IsInAsyncLoadingThread) () () extern
Returns
True if called from the async loading thread if it's enabled, otherwise if called from game thread while is async loading code.
Referenced by FTickableCookObject::FTickableCookObject(), FTickableEditorObject::FTickableEditorObject(), FTickableCookObject::~FTickableCookObject(), FTickableEditorObject::~FTickableEditorObject(), FLightMap::AddRef(), FShadowMap::AddRef(), TPersistentObjectPtr< FUniqueObjectGuid >::CanCacheObjectPointer(), FSlateApplication::Get(), FMaterial::GetGameThreadShaderMap(), IsInActualRenderingThread(), TObjectIterator< UObject >::operator++(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::operator++(), FLightMap::Release(), and FShadowMap::Release().
LogContentComparisonCommandlet
FLogCategoryLogContentComparisonCommandlet LogContentComparisonCommandlet
Referenced by FLogCategoryLogContentComparisonCommandlet::FLogCategoryLogContentComparisonCommandlet().
LogCore
FLogCategoryLogCore LogCore
Referenced by FLogCategoryLogCore::FLogCategoryLogCore(), TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::Free(), TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >::GetResourceDataSize(), TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::OutOfMemory(), and FTraceAuxiliary::Start().
LogExec
FLogCategoryLogExec LogExec
Referenced by FLogCategoryLogExec::FLogCategoryLogExec().
LogExit
FLogCategoryLogExit LogExit
Referenced by FLogCategoryLogExit::FLogCategoryLogExit().
LogHAL
FLogCategoryLogHAL LogHAL
Referenced by FLogCategoryLogHAL::FLogCategoryLogHAL(), IAsyncReadRequest::~IAsyncReadRequest(), and FRunnableThreadApple::TranslateThreadPriority().
LogInit
FLogCategoryLogInit LogInit
Referenced by FLogCategoryLogInit::FLogCategoryLogInit().
LogLoad
FLogCategoryLogLoad LogLoad
Referenced by FLogCategoryLogLoad::FLogCategoryLogLoad().
LogLocalization
FLogCategoryLogLocalization LogLocalization
Referenced by FLogCategoryLogLocalization::FLogCategoryLogLocalization().
LogLongPackageNames
FLogCategoryLogLongPackageNames LogLongPackageNames
Referenced by FLogCategoryLogLongPackageNames::FLogCategoryLogLongPackageNames().
LogMemory
FLogCategoryLogMemory LogMemory
Referenced by FLogCategoryLogMemory::FLogCategoryLogMemory(), FMallocBinnedCommonUtils::FlushCurrentThreadCache(), and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::GetAllocationSizeExternal().
LogNetPackageMap
FLogCategoryLogNetPackageMap LogNetPackageMap
Referenced by FLogCategoryLogNetPackageMap::FLogCategoryLogNetPackageMap().
LogNetSerialization
FLogCategoryLogNetSerialization LogNetSerialization
Referenced by FLogCategoryLogNetSerialization::FLogCategoryLogNetSerialization().
LogOutputDevice
FLogCategoryLogOutputDevice LogOutputDevice
Referenced by FLogCategoryLogOutputDevice::FLogCategoryLogOutputDevice().
LogProcess
FLogCategoryLogProcess LogProcess
Referenced by FLogCategoryLogProcess::FLogCategoryLogProcess().
LogProfilingDebugging
FLogCategoryLogProfilingDebugging LogProfilingDebugging
Referenced by FLogCategoryLogProfilingDebugging::FLogCategoryLogProfilingDebugging().
LogScript
FLogCategoryLogScript LogScript
Referenced by FLogCategoryLogScript::FLogCategoryLogScript().
LogSerialization
FLogCategoryLogSerialization LogSerialization
Referenced by FLogCategoryLogSerialization::FLogCategoryLogSerialization(), FBufferWriter::Serialize(), and TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >< 32 >::Serialize().
LogSHA
FLogCategoryLogSHA LogSHA
Referenced by FLogCategoryLogSHA::FLogCategoryLogSHA().
LogStats
FLogCategoryLogStats LogStats
Referenced by FLogCategoryLogStats::FLogCategoryLogStats().
LogStreaming
FLogCategoryLogStreaming LogStreaming
Referenced by FLogCategoryLogStreaming::FLogCategoryLogStreaming().
LogTemp
FLogCategoryLogTemp LogTemp
Referenced by FLogCategoryLogTemp::FLogCategoryLogTemp(), TNumericPropertyParams< NumericType >::TNumericPropertyParams(), TNetRewindHistory< DataType >::NetSerialize(), TNetRewindHistory< DataType >::NetSerializeData(), and RegisterConversionNode().
LogUnrealMath
FLogCategoryLogUnrealMath LogUnrealMath
Referenced by FLogCategoryLogUnrealMath::FLogCategoryLogUnrealMath(), UE::Math::TMatrix< double >::DebugPrint(), and UE::Math::TMatrix< double >::ErrorEnsure().
LogUnrealMatrix
FLogCategoryLogUnrealMatrix LogUnrealMatrix
Referenced by FLogCategoryLogUnrealMatrix::FLogCategoryLogUnrealMatrix().
LogVirtualization
FLogCategoryLogVirtualization LogVirtualization
Referenced by FLogCategoryLogVirtualization::FLogCategoryLogVirtualization().
PRIVATE_GIsRunningCookCommandlet
bool PRIVATE_GIsRunningCookCommandlet extern
Referenced by IsRunningCookCommandlet().
PRIVATE_GIsRunningDLCCookCommandlet
bool PRIVATE_GIsRunningDLCCookCommandlet extern
Referenced by IsRunningDLCCookCommandlet().
ResumeAsyncLoading
void(* ResumeAsyncLoading) () () extern
Resumes async package loading.
Referenced by RequestEngineExit().
ResumeTextureStreamingRenderTasks
void(* ResumeTextureStreamingRenderTasks) () () extern
Resume texture updates caused by completed async IOs.
Referenced by LexToString().
SuspendAsyncLoading
void(* SuspendAsyncLoading) () () extern
Suspends async package loading.
Referenced by RequestEngineExit().
SuspendTextureStreamingRenderTasks
void(* SuspendTextureStreamingRenderTasks) () () extern
Suspends texture updates caused by completed async IOs.
Referenced by LexToString().