Unreal Engine 5.6 C++ API: UE::FPlatformSystemWideMutexNotImplemented Class Reference
UE::FPlatformSystemWideMutexNotImplemented Class Reference
Platforms that don't need a working FPlatformSystemWideMutex can alias this one.
#include "GenericPlatformMutex.h"
Public Member Functions
FPlatformSystemWideMutexNotImplemented (const FPlatformSystemWideMutexNotImplemented &)=delete
FPlatformSystemWideMutexNotImplemented (const FString &Name, FTimespan Timeout=FTimespan::Zero())
Construct a named, system-wide mutex and attempt to get access/ownership of it.
~FPlatformSystemWideMutexNotImplemented ()=default
Destructor releases system-wide mutex if it is currently owned.
bool IsValid () const
Does the calling thread have ownership of the system-wide mutex?
FPlatformSystemWideMutexNotImplemented & operator= (const FPlatformSystemWideMutexNotImplemented &)=delete
void Release ()
Releases system-wide mutex if it is currently owned.
Detailed Description
Platforms that don't need a working FPlatformSystemWideMutex can alias this one.
Definition at line 61 of file GenericPlatformMutex.h.
Constructor & Destructor Documentation
FPlatformSystemWideMutexNotImplemented() [1/2]
UE::FPlatformSystemWideMutexNotImplemented::FPlatformSystemWideMutexNotImplemented (const FPlatformSystemWideMutexNotImplemented &) delete
References FPlatformSystemWideMutexNotImplemented().
Referenced by FPlatformSystemWideMutexNotImplemented(), and operator=().
FPlatformSystemWideMutexNotImplemented() [2/2]
UE::FPlatformSystemWideMutexNotImplemented::FPlatformSystemWideMutexNotImplemented (const FString & Name, FTimespan Timeout = FTimespan::Zero()) explicit
Construct a named, system-wide mutex and attempt to get access/ownership of it.
References Name, Timeout, and FTimespan::Zero().
~FPlatformSystemWideMutexNotImplemented()
UE::FPlatformSystemWideMutexNotImplemented::~FPlatformSystemWideMutexNotImplemented () default
Destructor releases system-wide mutex if it is currently owned.
Member Function Documentation
IsValid()
bool UE::FPlatformSystemWideMutexNotImplemented::IsValid () const inline
Does the calling thread have ownership of the system-wide mutex?
Returns
True if obtained. WARNING: Returns true for an owned but previously abandoned locks so shared resources can be in undetermined states. You must handle shared data robustly.
Definition at line 78 of file GenericPlatformMutex.h.
operator=()
FPlatformSystemWideMutexNotImplemented & UE::FPlatformSystemWideMutexNotImplemented::operator= (const FPlatformSystemWideMutexNotImplemented &) delete
References FPlatformSystemWideMutexNotImplemented().
Release()
void UE::FPlatformSystemWideMutexNotImplemented::Release () inline
Releases system-wide mutex if it is currently owned.
Definition at line 84 of file GenericPlatformMutex.h.
The documentation for this class was generated from the following file:
GenericPlatformMutex.h