Unreal Engine 5.6 C++ API: FAttributesSetBase Class Reference
FAttributesSetBase Class Reference
This is the container for all attributes and their arrays.
#include "MeshAttributeArray.h"
Public Member Functions
FAttributesSetBase ()
Constructor.
void AppendAttributesFrom (const FAttributesSetBase &OtherAttributesSet)
bool DoesAttributeHaveAllFlags (const FName AttributeName, EMeshAttributeFlags AttributeFlags) const
Determine whether an attribute has all of the given flags.
bool DoesAttributeHaveAnyFlags (const FName AttributeName, EMeshAttributeFlags AttributeFlags) const
Determine whether an attribute has any of the given flags.
template<typename Allocator>
void GetAttributeNames (TArray< FName, Allocator > &OutAttributeNames) const
Returns an array of all the attribute names registered.
template<typename T>
TMeshAttributesRef< int32, typename TMeshAttributesRefType< T >::RefType > GetAttributesRef (const FName AttributeName)
template<typename T>
TMeshAttributesConstRef< int32, typename TMeshAttributesRefType< T >::ConstRefType > GetAttributesRef (const FName AttributeName) const
Get an attribute array with the given type and name.
uint32 GetHash (const FName AttributeName) const
int32 GetNumElements () const
Gets the number of elements in the attribute set.
bool HasAttribute (const FName AttributeName) const
Determines whether an attribute exists with the given name.
template<typename T>
bool HasAttributeOfType (const FName AttributeName) const
Determines whether an attribute of the given type exists with the given name.
void Initialize (const int32 Count)
Initializes all attributes to have the given number of elements with the default value.
void Insert (const int32 Index)
Insert a new element at the given index.
template<typename T, typename TEnableIf<!TIsArray< T >::Value, int >::Type = 0>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterAttribute (const FName AttributeName, const int32 NumberOfChannels=1, const T &Default=T(), const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new simple attribute.
template<typename T, typename TEnableIf< TIsArray< T >::Value, int >::Type = 0>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterAttribute (const FName AttributeName, const int32 NumberOfChannels=1, const typename TMeshAttributesRegisterType< T >::RealAttributeType &Default=typename TMeshAttributesRegisterType< T >::RealAttributeType(), const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new fixed array attribute.
template<typename T>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterAttributeInternal (const FName AttributeName, const int32 NumberOfChannels=1, const typename TMeshAttributesRegisterType< T >::RealAttributeType &Default=typename TMeshAttributesRegisterType< T >::RealAttributeType(), const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new attribute name with the given type (must be a member of the AttributeTypes tuple).
template<typename T, typename TEnableIf< std::is_same_v< typename TMeshAttributesRegisterType< T >::RealAttributeType, int >, int >::Type = 0>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterIndexAttribute (const FName AttributeName, const int32 NumberOfChannels=1, const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new unbounded array attribute.
void Remap (const TSparseArray< int32 > &IndexRemap)
Applies the given remapping to the attributes set.
void Remove (const int32 Index)
Remove an element at the given index.
void SetNumElements (const int32 Count)
Sets all attributes to have the given number of elements, preserving existing values and filling extra elements with the default value.
void UnregisterAttribute (const FName AttributeName)
Unregister an attribute with the given name.
Protected Attributes
TMap< FName, FAttributesSetEntry > Map
The actual container.
int32 NumElements
The number of elements in each attribute array.
Friends
MESHDESCRIPTION_API FArchive & operator<< (FArchive &Ar, FAttributesSetBase &AttributesSet)
Serialization.
template<typename T>
void SerializeLegacy (FArchive &Ar, FAttributesSetBase &AttributesSet)
Detailed Description
This is the container for all attributes and their arrays.
It wraps a TMap, mapping from attribute name to attribute array. An attribute may be of any arbitrary type; we use a mixture of polymorphism and compile-time templates to handle the different types.
Definition at line 1555 of file MeshAttributeArray.h.
Constructor & Destructor Documentation
FAttributesSetBase()
FAttributesSetBase::FAttributesSetBase () inline
Constructor.
Definition at line 1559 of file MeshAttributeArray.h.
References NumElements.
Referenced by AppendAttributesFrom(), operator<<, and SerializeLegacy.
Member Function Documentation
AppendAttributesFrom()
void FAttributesSetBase::AppendAttributesFrom (const FAttributesSetBase & OtherAttributesSet)
References FAttributesSetBase().
DoesAttributeHaveAllFlags()
bool FAttributesSetBase::DoesAttributeHaveAllFlags (const FName AttributeName, EMeshAttributeFlags AttributeFlags) const inline
Determine whether an attribute has all of the given flags.
Definition at line 1735 of file MeshAttributeArray.h.
References EnumHasAllFlags(), and Map.
DoesAttributeHaveAnyFlags()
bool FAttributesSetBase::DoesAttributeHaveAnyFlags (const FName AttributeName, EMeshAttributeFlags AttributeFlags) const inline
Determine whether an attribute has any of the given flags.
Definition at line 1724 of file MeshAttributeArray.h.
References EnumHasAnyFlags(), and Map.
GetAttributeNames()
template<typename Allocator> void FAttributesSetBase::GetAttributeNames (TArray< FName, Allocator > & OutAttributeNames) const inline
Returns an array of all the attribute names registered.
Definition at line 1718 of file MeshAttributeArray.h.
References Map.
GetAttributesRef() [1/2]
template<typename T> TMeshAttributesRef< int32, typename TMeshAttributesRefType< T >::RefType > FAttributesSetBase::GetAttributesRef (const FName AttributeName) inline
Definition at line 1809 of file MeshAttributeArray.h.
References Map, TMeshAttributesRefType< T >::MaxExpectedExtent, and TMeshAttributesRefType< T >::MinExpectedExtent.
GetAttributesRef() [2/2]
template<typename T> TMeshAttributesConstRef< int32, typename TMeshAttributesRefType< T >::ConstRefType > FAttributesSetBase::GetAttributesRef (const FName AttributeName) const inline
Get an attribute array with the given type and name.
The attribute type must correspond to the type passed as the template parameter.
Definition at line 1786 of file MeshAttributeArray.h.
References Map, TMeshAttributesRefType< T >::MaxExpectedExtent, and TMeshAttributesRefType< T >::MinExpectedExtent.
GetHash()
uint32 FAttributesSetBase::GetHash (const FName AttributeName) const inline
Definition at line 1745 of file MeshAttributeArray.h.
References Map.
GetNumElements()
int32 FAttributesSetBase::GetNumElements () const inline
Gets the number of elements in the attribute set.
Definition at line 1708 of file MeshAttributeArray.h.
References NumElements.
HasAttribute()
bool FAttributesSetBase::HasAttribute (const FName AttributeName) const inline
Determines whether an attribute exists with the given name.
Definition at line 1664 of file MeshAttributeArray.h.
References Map.
HasAttributeOfType()
template<typename T> bool FAttributesSetBase::HasAttributeOfType (const FName AttributeName) const inline
Determines whether an attribute of the given type exists with the given name.
Definition at line 1673 of file MeshAttributeArray.h.
References Map, TMeshAttributesRefType< T >::MaxExpectedExtent, and TMeshAttributesRefType< T >::MinExpectedExtent.
Initialize()
void FAttributesSetBase::Initialize (const int32 Count) inline
Initializes all attributes to have the given number of elements with the default value.
Definition at line 1688 of file MeshAttributeArray.h.
References Count, Map, and NumElements.
Insert()
void FAttributesSetBase::Insert (const int32 Index) inline
Insert a new element at the given index.
The public API version of this function takes an ID of ElementIDType instead of a typeless index.
Definition at line 1758 of file MeshAttributeArray.h.
References check, Map, FMath::Max, and NumElements.
RegisterAttribute() [1/2]
template<typename T, typename TEnableIf<!TIsArray< T >::Value, int >::Type = 0> TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > FAttributesSetBase::RegisterAttribute (const FName AttributeName, const int32 NumberOfChannels = 1, const T & Default = T(), const EMeshAttributeFlags Flags = EMeshAttributeFlags::None) inline
Register a new simple attribute.
e.g. RegisterAttribute<float>(...)
Obtain a reference to this with GetAttributesRef<float>(...)
Definition at line 1613 of file MeshAttributeArray.h.
References Default, Flags, None, and RegisterAttributeInternal().
Referenced by SetGroomAttribute(), SetHairStrandAttribute(), and SetHairVertexAttribute().
RegisterAttribute() [2/2]
template<typename T, typename TEnableIf< TIsArray< T >::Value, int >::Type = 0> TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > FAttributesSetBase::RegisterAttribute (const FName AttributeName, const int32 NumberOfChannels = 1, const typename TMeshAttributesRegisterType< T >::RealAttributeType & Default = typename TMeshAttributesRegisterType<T>::RealAttributeType(), const EMeshAttributeFlags Flags = EMeshAttributeFlags::None) inline
Register a new fixed array attribute.
e.g. RegisterAttribute<float[3]>(...)
Obtain a reference to this with GetAttributesRef<TArrayView<float>>(...)
Definition at line 1630 of file MeshAttributeArray.h.
References Default, Flags, None, and RegisterAttributeInternal().
RegisterAttributeInternal()
template<typename T> TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > FAttributesSetBase::RegisterAttributeInternal (const FName AttributeName, const int32 NumberOfChannels = 1, const typename TMeshAttributesRegisterType< T >::RealAttributeType & Default = typename TMeshAttributesRegisterType<T>::RealAttributeType(), const EMeshAttributeFlags Flags = EMeshAttributeFlags::None) inline
Register a new attribute name with the given type (must be a member of the AttributeTypes tuple).
If the attribute name is already registered, it will update it to use the new type, number of channels and flags.
Example of use:
VertexInstanceAttributes().RegisterAttribute<FVector2f>("UV", 8);
                   . . .
TVertexInstanceAttributeArray<FVector2f>& UV0 = VertexInstanceAttributes().GetAttributes<FVector2f>("UV", 0);
UV0[ VertexInstanceID ] = FVector2f(1.0f, 1.0f);
Definition at line 1576 of file MeshAttributeArray.h.
References Default, TMeshAttributesRegisterType< T >::Extent, Flags, FAttributesSetEntry::Get(), Map, None, and NumElements.
Referenced by RegisterAttribute(), RegisterAttribute(), and RegisterIndexAttribute().
RegisterIndexAttribute()
template<typename T, typename TEnableIf< std::is_same_v< typename TMeshAttributesRegisterType< T >::RealAttributeType, int >, int >::Type = 0> TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > FAttributesSetBase::RegisterIndexAttribute (const FName AttributeName, const int32 NumberOfChannels = 1, const EMeshAttributeFlags Flags = EMeshAttributeFlags::None) inline
Register a new unbounded array attribute.
e.g. RegisterAttribute<float[]>(...)
Obtain a reference to this with GetAttributesRef<TArrayAttribute<float>>(...)
Definition at line 1647 of file MeshAttributeArray.h.
References Flags, INDEX_NONE, IndexReference, None, and RegisterAttributeInternal().
Remap()
void FAttributesSetBase::Remap (const TSparseArray< int32 > & IndexRemap)
Applies the given remapping to the attributes set.
Remove()
void FAttributesSetBase::Remove (const int32 Index) inline
Remove an element at the given index.
The public API version of this function takes an ID of ElementIDType instead of a typeless index.
Definition at line 1773 of file MeshAttributeArray.h.
References Map.
SetNumElements()
void FAttributesSetBase::SetNumElements (const int32 Count) inline
Sets all attributes to have the given number of elements, preserving existing values and filling extra elements with the default value.
Definition at line 1698 of file MeshAttributeArray.h.
References Count, Map, and NumElements.
UnregisterAttribute()
void FAttributesSetBase::UnregisterAttribute (const FName AttributeName) inline
Unregister an attribute with the given name.
Definition at line 1658 of file MeshAttributeArray.h.
References Map.
Friends And Related Symbol Documentation
operator<<
MESHDESCRIPTION_API FArchive & operator<< (FArchive & Ar, FAttributesSetBase & AttributesSet) friend
Serialization.
References FAttributesSetBase(), and Ar.
SerializeLegacy
template<typename T> void SerializeLegacy (FArchive & Ar, FAttributesSetBase & AttributesSet) friend
References FAttributesSetBase(), and Ar.
Field Documentation
Map
TMap<FName, FAttributesSetEntry> FAttributesSetBase::Map protected
The actual container.
Definition at line 1841 of file MeshAttributeArray.h.
Referenced by DoesAttributeHaveAllFlags(), DoesAttributeHaveAnyFlags(), TAttributesSet< ElementIDType >::ForEach(), TAttributesSet< FVertexID >::ForEach(), TAttributesSet< ElementIDType >::ForEachByType(), TAttributesSet< ElementIDType >::ForEachByType(), TAttributesSet< ElementIDType >::GetAttributeChannelCount(), GetAttributeNames(), GetAttributesRef(), GetAttributesRef(), TAttributesSet< ElementIDType >::GetAttributesRef(), TAttributesSet< ElementIDType >::GetAttributesRef(), GetHash(), HasAttribute(), HasAttributeOfType(), Initialize(), Insert(), RegisterAttributeInternal(), Remove(), TAttributesSet< ElementIDType >::SetAttributeChannelCount(), SetNumElements(), TAttributesSet< ElementIDType >::UE_DEPRECATED(), and UnregisterAttribute().
NumElements
int32 FAttributesSetBase::NumElements protected
The number of elements in each attribute array.
Definition at line 1844 of file MeshAttributeArray.h.
Referenced by FAttributesSetBase(), GetNumElements(), Initialize(), Insert(), RegisterAttributeInternal(), and SetNumElements().
The documentation for this class was generated from the following file:
MeshAttributeArray.h