Unreal Engine 5.6 C++ API: FTabManager::FStack Class Reference
FTabManager::FStack Class Reference
#include "TabManager.h"
Public Member Functions
virtual ~FStack ()
TSharedRef< FStack > AddTab (const FName TabType, ETabState::Type InTabState)
TSharedRef< FStack > AddTab (const FName TabType, ETabState::Type InTabState, ESidebarLocation InSidebarLocation, float SidebarSizeCoefficient, bool bPinnedInSidebar=false)
TSharedRef< FStack > AddTab (const FTab &Tab)
TSharedRef< FStack > AddTab (const FTabId TabId, ETabState::Type InTabState)
TSharedRef< FStack > AddTab (const FTabId TabId, ETabState::Type InTabState, ESidebarLocation InSidebarLocation, float SidebarSizeCoefficient, bool bPinnedInSidebar=false)
virtual TSharedPtr< FStack > AsStack () override
FName GetExtensionId () const
TSharedRef< FStack > SetExtensionId (FName InExtensionId)
TSharedRef< FStack > SetForegroundTab (const FTabId &TabId)
TSharedRef< FStack > SetHideTabWell (const bool InHideTabWell)
TSharedRef< FStack > SetSizeCoefficient (const float InSizeCoefficient)
Public Member Functions inherited from FTabManager::FLayoutNode
virtual ~FLayoutNode ()
virtual TSharedPtr< FArea > AsArea ()
virtual TSharedPtr< FSplitter > AsSplitter ()
float GetSizeCoefficient () const
Public Member Functions inherited from TSharedFromThis< FLayoutNode >
TSharedRef< FLayoutNode, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FLayoutNode, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
FStack ()
Protected Member Functions inherited from FTabManager::FLayoutNode
FLayoutNode ()
Protected Member Functions inherited from TSharedFromThis< FLayoutNode >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bHideTabWell
FName ExtensionId
FTabId ForegroundTabId
TArray< FTab > Tabs
Protected Attributes inherited from FTabManager::FLayoutNode
float SizeCoefficient
Friends
class FLayout
class FTabManager
class SDockingTabStack
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FLayoutNode >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 457 of file TabManager.h.
Constructor & Destructor Documentation
~FStack()
virtual FTabManager::FStack::~FStack () inline virtual
Definition at line 525 of file TabManager.h.
FStack()
FTabManager::FStack::FStack () inline protected
Definition at line 542 of file TabManager.h.
References bHideTabWell, ForegroundTabId, and Tabs.
Member Function Documentation
AddTab() [1/5]
TSharedRef< FStack > FTabManager::FStack::AddTab (const FName TabType, ETabState::Type InTabState) inline
Definition at line 464 of file TabManager.h.
References check, TSharedFromThis< FLayoutNode >::SharedThis(), ETabState::SidebarTab, and Tabs.
AddTab() [2/5]
TSharedRef< FStack > FTabManager::FStack::AddTab (const FName TabType, ETabState::Type InTabState, ESidebarLocation InSidebarLocation, float SidebarSizeCoefficient, bool bPinnedInSidebar = false) inline
Definition at line 480 of file TabManager.h.
References check, None, TSharedFromThis< FLayoutNode >::SharedThis(), ETabState::SidebarTab, and Tabs.
AddTab() [3/5]
TSharedRef< FStack > FTabManager::FStack::AddTab (const FTab & Tab) inline
Definition at line 496 of file TabManager.h.
References TSharedFromThis< FLayoutNode >::SharedThis(), and Tabs.
AddTab() [4/5]
TSharedRef< FStack > FTabManager::FStack::AddTab (const FTabId TabId, ETabState::Type InTabState) inline
Definition at line 471 of file TabManager.h.
References check, TSharedFromThis< FLayoutNode >::SharedThis(), ETabState::SidebarTab, and Tabs.
AddTab() [5/5]
TSharedRef< FStack > FTabManager::FStack::AddTab (const FTabId TabId, ETabState::Type InTabState, ESidebarLocation InSidebarLocation, float SidebarSizeCoefficient, bool bPinnedInSidebar = false) inline
Definition at line 487 of file TabManager.h.
References check, None, TSharedFromThis< FLayoutNode >::SharedThis(), ETabState::SidebarTab, and Tabs.
AsStack()
virtual TSharedPtr< FStack > FTabManager::FStack::AsStack () inline override virtual
Reimplemented from FTabManager::FLayoutNode.
Definition at line 520 of file TabManager.h.
References TSharedFromThis< FLayoutNode >::SharedThis().
GetExtensionId()
FName FTabManager::FStack::GetExtensionId () const inline
Definition at line 535 of file TabManager.h.
References ExtensionId.
SetExtensionId()
TSharedRef< FStack > FTabManager::FStack::SetExtensionId (FName InExtensionId) inline
Definition at line 529 of file TabManager.h.
References ExtensionId, and TSharedFromThis< FLayoutNode >::SharedThis().
SetForegroundTab()
TSharedRef< FStack > FTabManager::FStack::SetForegroundTab (const FTabId & TabId) inline
Definition at line 514 of file TabManager.h.
References ForegroundTabId, and TSharedFromThis< FLayoutNode >::SharedThis().
SetHideTabWell()
TSharedRef< FStack > FTabManager::FStack::SetHideTabWell (const bool InHideTabWell) inline
Definition at line 508 of file TabManager.h.
References bHideTabWell, and TSharedFromThis< FLayoutNode >::SharedThis().
SetSizeCoefficient()
TSharedRef< FStack > FTabManager::FStack::SetSizeCoefficient (const float InSizeCoefficient) inline
Definition at line 502 of file TabManager.h.
References TSharedFromThis< FLayoutNode >::SharedThis(), and FTabManager::FLayoutNode::SizeCoefficient.
Friends And Related Symbol Documentation
FLayout
friend class FLayout friend
Definition at line 460 of file TabManager.h.
References FLayout.
Referenced by FLayout.
FTabManager
friend class FTabManager friend
Definition at line 459 of file TabManager.h.
References FTabManager.
Referenced by FTabManager.
SDockingTabStack
friend class SDockingTabStack friend
Definition at line 461 of file TabManager.h.
References SDockingTabStack.
Referenced by SDockingTabStack.
Field Documentation
bHideTabWell
bool FTabManager::FStack::bHideTabWell protected
Definition at line 550 of file TabManager.h.
Referenced by FStack(), and SetHideTabWell().
ExtensionId
FName FTabManager::FStack::ExtensionId protected
Definition at line 552 of file TabManager.h.
Referenced by GetExtensionId(), and SetExtensionId().
ForegroundTabId
FTabId FTabManager::FStack::ForegroundTabId protected
Definition at line 551 of file TabManager.h.
Referenced by FStack(), and SetForegroundTab().
Tabs
TArray<FTab> FTabManager::FStack::Tabs protected
Definition at line 549 of file TabManager.h.
Referenced by FStack(), AddTab(), AddTab(), AddTab(), AddTab(), and AddTab().
The documentation for this class was generated from the following file:
TabManager.h