Unreal Engine 5.6 C++ API: FMovieSceneClipboard Class Reference
FMovieSceneClipboard Class Reference
A clipboard representing serializable copied data for a movie scene.
#include "MovieSceneClipboard.h"
Public Member Functions
MOVIESCENE_API FMovieSceneClipboard ()
Default Constructor.
MOVIESCENE_API FMovieSceneClipboard (const FMovieSceneClipboard &In)
Copy construction/assignment.
MOVIESCENE_API FMovieSceneClipboard (FMovieSceneClipboard &&In)
Move construction/assignment.
MOVIESCENE_API FText GetDisplayText () const
Get a text description of this clipboard for display on UI.
MOVIESCENE_API FMovieSceneClipboardEnvironment & GetEnvironment ()
Get the environment to which this clipboard relates.
MOVIESCENE_API const FMovieSceneClipboardEnvironment & GetEnvironment () const
Get the environment to which this clipboard relates.
MOVIESCENE_API const TArray< TArray< FMovieSceneClipboardKeyTrack > > & GetKeyTrackGroups () const
Get the key track groups that were copied.
MOVIESCENE_API FMovieSceneClipboard & operator= (const FMovieSceneClipboard &In)
MOVIESCENE_API FMovieSceneClipboard & operator= (FMovieSceneClipboard &&In)
Private Attributes
FMovieSceneClipboardEnvironment Environment
The environment to which this clipboard relates.
TArray< TArray< FMovieSceneClipboardKeyTrack > > KeyTrackGroups
Collection of groups of key tracks that have been copied.
Friends
class FMovieSceneClipboardBuilder
Detailed Description
A clipboard representing serializable copied data for a movie scene.
Definition at line 302 of file MovieSceneClipboard.h.
Constructor & Destructor Documentation
FMovieSceneClipboard() [1/3]
MOVIESCENE_API FMovieSceneClipboard::FMovieSceneClipboard ()
Default Constructor.
Referenced by FMovieSceneClipboard(), FMovieSceneClipboard(), operator=(), and operator=().
FMovieSceneClipboard() [2/3]
MOVIESCENE_API FMovieSceneClipboard::FMovieSceneClipboard (FMovieSceneClipboard && In)
Move construction/assignment.
References FMovieSceneClipboard().
FMovieSceneClipboard() [3/3]
MOVIESCENE_API FMovieSceneClipboard::FMovieSceneClipboard (const FMovieSceneClipboard & In)
Copy construction/assignment.
References FMovieSceneClipboard().
Member Function Documentation
GetDisplayText()
MOVIESCENE_API FText FMovieSceneClipboard::GetDisplayText () const
Get a text description of this clipboard for display on UI.
GetEnvironment() [1/2]
MOVIESCENE_API FMovieSceneClipboardEnvironment & FMovieSceneClipboard::GetEnvironment ()
Get the environment to which this clipboard relates.
GetEnvironment() [2/2]
MOVIESCENE_API const FMovieSceneClipboardEnvironment & FMovieSceneClipboard::GetEnvironment () const
Get the environment to which this clipboard relates.
GetKeyTrackGroups()
MOVIESCENE_API const TArray< TArray< FMovieSceneClipboardKeyTrack > > & FMovieSceneClipboard::GetKeyTrackGroups () const
Get the key track groups that were copied.
operator=() [1/2]
MOVIESCENE_API FMovieSceneClipboard & FMovieSceneClipboard::operator= (const FMovieSceneClipboard & In)
References FMovieSceneClipboard().
operator=() [2/2]
MOVIESCENE_API FMovieSceneClipboard & FMovieSceneClipboard::operator= (FMovieSceneClipboard && In)
References FMovieSceneClipboard().
Friends And Related Symbol Documentation
FMovieSceneClipboardBuilder
friend class FMovieSceneClipboardBuilder friend
Definition at line 329 of file MovieSceneClipboard.h.
References FMovieSceneClipboardBuilder.
Referenced by FMovieSceneClipboardBuilder.
Field Documentation
Environment
FMovieSceneClipboardEnvironment FMovieSceneClipboard::Environment private
The environment to which this clipboard relates.
Definition at line 332 of file MovieSceneClipboard.h.
KeyTrackGroups
TArray<TArray<FMovieSceneClipboardKeyTrack> > FMovieSceneClipboard::KeyTrackGroups private
Collection of groups of key tracks that have been copied.
Definition at line 335 of file MovieSceneClipboard.h.
The documentation for this class was generated from the following file:
MovieSceneClipboard.h