Unreal Engine 5.6 C++ API: FSkeletalMeshMerge Class Reference
FSkeletalMeshMerge Class Reference
Utility for merging a list of skeletal meshes into a single mesh.
#include "SkeletalMeshMerge.h"
Data Structures
struct FMergeMeshInfo
Info about source mesh used in merge.
struct FMergeSectionInfo
keeps track of an existing section that need to be merged with another
struct FNewSectionInfo
info needed to create a new merged section
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSkeletalMeshMerge (const FSkeletalMeshMerge &)=default
FSkeletalMeshMerge (USkeletalMesh *InMergeMesh, const TArray< USkeletalMesh * > &InSrcMeshList, const TArray< FSkelMeshMergeSectionMapping > &InForceSectionMapping, int32 StripTopLODs, EMeshBufferAccess MeshBufferAccess=EMeshBufferAccess::Default, const FSkelMeshMergeUVTransformMapping *InSectionUVTransforms=nullptr)
Constructor.
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool DoMerge (TArray< FRefPoseOverride > *RefPoseOverrides=nullptr)
Merge/Composite skeleton and meshes together from the list of source meshes.
bool FinalizeMesh ()
Creates the merged mesh from the 'SrcMeshList' (note, this should only be called after MergeSkeleton()).
void MergeSkeleton (const TArray< FRefPoseOverride > *RefPoseOverrides=nullptr)
Create the 'MergedMesh' reference skeleton from the skeletons in the 'SrcMeshList'.
UE_DEPRECATED (5.0, "FSkelMeshMergeUVTransforms has been replaced with FSkelMeshMergeMeshUVTransforms, use different signature") 1 FSkeletalMeshMerge(USkeletalMesh *InMergeMesh
Data Fields
const TArray< USkeletalMesh * > const TArray< FSkelMeshMergeSectionMapping > & InForceSectionMapping
const TArray< USkeletalMesh * > & InSrcMeshList
const TArray< USkeletalMesh * > const TArray< FSkelMeshMergeSectionMapping > int32 EMeshBufferAccess MeshBufferAccess
const TArray< USkeletalMesh * > const TArray< FSkelMeshMergeSectionMapping > int32 EMeshBufferAccess PRAGMA_DISABLE_DEPRECATION_WARNINGS FSkelMeshMergeUVTransforms *InSectionUVTransforms PRAGMA_ENABLE_DEPRECATION_WARNINGS
const TArray< USkeletalMesh * > const TArray< FSkelMeshMergeSectionMapping > int32 StripTopLODs
Private Member Functions
bool AddSocket (const USkeletalMeshSocket *NewSocket, bool bIsSkeletonSocket)
Copies and adds the 'NewSocket' to the MergeMesh's MeshOnlySocketList only if the socket does not already exist.
void AddSockets (const TArray< USkeletalMeshSocket * > &NewSockets, bool bAreSkeletonSockets)
Adds only the new sockets from the 'NewSockets' array to the 'ExistingSocketList'.
void BuildSockets (const TArray< USkeletalMesh * > &SourceMeshList)
Builds a new 'SocketList' from the sockets in the 'SourceMeshList'.
int32 CalculateLodCount (const TArray< USkeletalMesh * > &SourceMeshList) const
Returns the number of LODs that can be supported by the meshes in 'SourceMeshList'.
template<typename VertexDataType>
void CopyVertexFromSource (VertexDataType &DestVert, const FSkeletalMeshLODRenderData &SrcLODData, int32 SourceVertIdx, const FMergeSectionInfo &MergeSectionInfo)
template<typename VertexDataType>
void GenerateLODModel (int32 LODIdx)
Creates a new LOD model and adds the new merged sections to it.
void GenerateNewSectionArray (TArray< FNewSectionInfo > &NewSectionArray, int32 LODIdx)
Generate the list of sections that need to be created along with info needed to merge sections.
void MergeBoneMap (TArray< FBoneIndexType > &MergedBoneMap, TArray< FBoneIndexType > &BoneMapToMergedBoneMap, const TArray< FBoneIndexType > &BoneMap)
Merge a bonemap with an existing bonemap and keep track of remapping (a bonemap is a list of indices of bones in the USkeletalMesh::RefSkeleton array)
void OverrideBoneSockets (const FName &BoneName, const TArray< USkeletalMeshSocket * > &SourceSocketList)
Overrides the sockets attached to 'BoneName' with the corresponding socket in the 'SourceSocketList'.
void OverrideMergedSockets (const TArray< FRefPoseOverride > &PoseOverrides)
Overrides the sockets of overridden bones.
void OverrideSocket (const USkeletalMeshSocket *SourceSocket)
Override the corresponding 'MergeMesh' socket with 'SourceSocket'.
bool ProcessMergeMesh ()
(Re)initialize and merge skeletal mesh info from the list of source meshes to the merge mesh
void ReleaseResources (int32 Slack=0)
Releases any resources the 'MergeMesh' is currently holding.
UE_DEPRECATED (5.0, "Used to facilitate backwards compatibility with old constructor") FSkelMeshMergeUVTransformMapping DummySectionUVTransforms
Static Private Member Functions
static void BuildReferenceSkeleton (const TArray< USkeletalMesh * > &SourceMeshList, FReferenceSkeleton &RefSkeleton, const USkeleton *SkeletonAsset)
Builds a new 'RefSkeleton' from the reference skeletons in the 'SourceMeshList'.
static bool OverrideReferenceBonePose (int32 SourceBoneIndex, const FReferenceSkeleton &SourceSkeleton, FReferenceSkeletonModifier &TargetSkeleton)
Override the 'TargetSkeleton' bone pose with the pose from from the 'SourceSkeleton'.
static void OverrideReferenceSkeletonPose (const TArray< FRefPoseOverride > &PoseOverrides, FReferenceSkeleton &TargetSkeleton, const USkeleton *SkeletonAsset)
Overrides the 'TargetSkeleton' bone poses with the bone poses specified in the 'PoseOverrides' array.
Private Attributes
const TArray< FSkelMeshMergeSectionMapping > & ForceSectionMapping
array to map sections from the source meshes to merged section entries
TArray< int32 > MaterialIds
Matches the Materials array in the final mesh - used for creating the right number of Material slots.
USkeletalMesh * MergeMesh
Destination merged mesh.
EMeshBufferAccess MeshBufferAccess
Whether or not the resulting mesh needs to be accessed by the CPU (e.g.
FReferenceSkeleton NewRefSkeleton
New reference skeleton, made from creating union of each part's skeleton.
const FSkelMeshMergeUVTransformMapping * SectionUVTransforms
optional array to transform UVs in each source mesh
TArray< FMergeMeshInfo > SrcMeshInfo
Array of source mesh info structs.
TArray< USkeletalMesh * > SrcMeshList
Array of source skeletal meshes.
int32 StripTopLODs
Number of high LODs to remove from input meshes.
Detailed Description
Utility for merging a list of skeletal meshes into a single mesh.
Definition at line 128 of file SkeletalMeshMerge.h.
Constructor & Destructor Documentation
FSkeletalMeshMerge() [1/2]
FSkeletalMeshMerge::FSkeletalMeshMerge (USkeletalMesh * InMergeMesh, const TArray< USkeletalMesh * > & InSrcMeshList, const TArray< FSkelMeshMergeSectionMapping > & InForceSectionMapping, int32 StripTopLODs, EMeshBufferAccess MeshBufferAccess = EMeshBufferAccess::Default, const FSkelMeshMergeUVTransformMapping * InSectionUVTransforms = nullptr)
Constructor.
Parameters
InMergeMesh - destination mesh to merge to
InSrcMeshList - array of source meshes to merge
InForceSectionMapping - optional array to map sections from the source meshes to merged section entries
StripTopLODs - number of high LODs to remove from input meshes
bMeshNeedsCPUAccess - (optional) if the resulting mesh needs to be accessed by the CPU for any reason (e.g. for spawning particle effects).
UVTransforms - optional array to transform the UVs in each mesh
References InForceSectionMapping, InSrcMeshList, MeshBufferAccess, and StripTopLODs.
Referenced by FSkeletalMeshMerge(), and UE_DEPRECATED().
FSkeletalMeshMerge() [2/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSkeletalMeshMerge::FSkeletalMeshMerge (const FSkeletalMeshMerge &) default
References FSkeletalMeshMerge(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Member Function Documentation
AddSocket()
bool FSkeletalMeshMerge::AddSocket (const USkeletalMeshSocket * NewSocket, bool bIsSkeletonSocket) private
Copies and adds the 'NewSocket' to the MergeMesh's MeshOnlySocketList only if the socket does not already exist.
Returns
'true' if the socket is added; 'false' otherwise.
AddSockets()
void FSkeletalMeshMerge::AddSockets (const TArray< USkeletalMeshSocket * > & NewSockets, bool bAreSkeletonSockets) private
Adds only the new sockets from the 'NewSockets' array to the 'ExistingSocketList'.
BuildReferenceSkeleton()
void FSkeletalMeshMerge::BuildReferenceSkeleton (const TArray< USkeletalMesh * > & SourceMeshList, FReferenceSkeleton & RefSkeleton, const USkeleton * SkeletonAsset) static private
Builds a new 'RefSkeleton' from the reference skeletons in the 'SourceMeshList'.
BuildSockets()
void FSkeletalMeshMerge::BuildSockets (const TArray< USkeletalMesh * > & SourceMeshList) private
Builds a new 'SocketList' from the sockets in the 'SourceMeshList'.
CalculateLodCount()
int32 FSkeletalMeshMerge::CalculateLodCount (const TArray< USkeletalMesh * > & SourceMeshList) const private
Returns the number of LODs that can be supported by the meshes in 'SourceMeshList'.
CopyVertexFromSource()
template<typename VertexDataType> void FSkeletalMeshMerge::CopyVertexFromSource (VertexDataType & DestVert, const FSkeletalMeshLODRenderData & SrcLODData, int32 SourceVertIdx, const FMergeSectionInfo & MergeSectionInfo) private
DoMerge()
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool FSkeletalMeshMerge::DoMerge (TArray< FRefPoseOverride > * RefPoseOverrides = nullptr)
Merge/Composite skeleton and meshes together from the list of source meshes.
Parameters
RefPoseOverrides - An optional override for the merged skeleton's reference pose.
Returns
true if succeeded
References DoMerge().
Referenced by DoMerge().
FinalizeMesh()
bool FSkeletalMeshMerge::FinalizeMesh ()
Creates the merged mesh from the 'SrcMeshList' (note, this should only be called after MergeSkeleton()).
Use when the reference skeleton is needed prior to finalizing the merged meshes (do not use with DoMerge()).
Returns
'true' if successful; 'false' otherwise.
References FinalizeMesh().
Referenced by FinalizeMesh().
GenerateLODModel()
template<typename VertexDataType> void FSkeletalMeshMerge::GenerateLODModel (int32 LODIdx) private
Creates a new LOD model and adds the new merged sections to it.
Modifies the MergedMesh.
Parameters
LODIdx - current LOD to process
GenerateNewSectionArray()
void FSkeletalMeshMerge::GenerateNewSectionArray (TArray< FNewSectionInfo > & NewSectionArray, int32 LODIdx) private
Generate the list of sections that need to be created along with info needed to merge sections.
Parameters
NewSectionArray - out array to populate
LODIdx - current LOD to process
MergeBoneMap()
void FSkeletalMeshMerge::MergeBoneMap (TArray< FBoneIndexType > & MergedBoneMap, TArray< FBoneIndexType > & BoneMapToMergedBoneMap, const TArray< FBoneIndexType > & BoneMap) private
Merge a bonemap with an existing bonemap and keep track of remapping (a bonemap is a list of indices of bones in the USkeletalMesh::RefSkeleton array)
Parameters
MergedBoneMap - out merged bonemap
BoneMapToMergedBoneMap - out of mapping from original bonemap to new merged bonemap
BoneMap - input bonemap to merge
MergeSkeleton()
void FSkeletalMeshMerge::MergeSkeleton (const TArray< FRefPoseOverride > * RefPoseOverrides = nullptr)
Create the 'MergedMesh' reference skeleton from the skeletons in the 'SrcMeshList'.
Use when the reference skeleton is needed prior to finalizing the merged meshes (do not use with DoMerge()).
Parameters
RefPoseOverrides - An optional override for the merged skeleton's reference pose.
References MergeSkeleton().
Referenced by MergeSkeleton().
OverrideBoneSockets()
void FSkeletalMeshMerge::OverrideBoneSockets (const FName & BoneName, const TArray< USkeletalMeshSocket * > & SourceSocketList) private
Overrides the sockets attached to 'BoneName' with the corresponding socket in the 'SourceSocketList'.
OverrideMergedSockets()
void FSkeletalMeshMerge::OverrideMergedSockets (const TArray< FRefPoseOverride > & PoseOverrides) private
Overrides the sockets of overridden bones.
OverrideReferenceBonePose()
bool FSkeletalMeshMerge::OverrideReferenceBonePose (int32 SourceBoneIndex, const FReferenceSkeleton & SourceSkeleton, FReferenceSkeletonModifier & TargetSkeleton) static private
Override the 'TargetSkeleton' bone pose with the pose from from the 'SourceSkeleton'.
Returns
'true' if the override was successful; 'false' otherwise.
References SourceSkeleton.
OverrideReferenceSkeletonPose()
void FSkeletalMeshMerge::OverrideReferenceSkeletonPose (const TArray< FRefPoseOverride > & PoseOverrides, FReferenceSkeleton & TargetSkeleton, const USkeleton * SkeletonAsset) static private
Overrides the 'TargetSkeleton' bone poses with the bone poses specified in the 'PoseOverrides' array.
OverrideSocket()
void FSkeletalMeshMerge::OverrideSocket (const USkeletalMeshSocket * SourceSocket) private
Override the corresponding 'MergeMesh' socket with 'SourceSocket'.
ProcessMergeMesh()
bool FSkeletalMeshMerge::ProcessMergeMesh () private
(Re)initialize and merge skeletal mesh info from the list of source meshes to the merge mesh
Returns
true if succeeded
ReleaseResources()
void FSkeletalMeshMerge::ReleaseResources (int32 Slack = 0) private
Releases any resources the 'MergeMesh' is currently holding.
UE_DEPRECATED() [1/2]
FSkeletalMeshMerge::UE_DEPRECATED (5. 0, "FSkelMeshMergeUVTransforms has been replaced with FSkelMeshMergeMeshUVTransforms, use different signature")
References FSkeletalMeshMerge().
UE_DEPRECATED() [2/2]
FSkeletalMeshMerge::UE_DEPRECATED (5. 0, "Used to facilitate backwards compatibility with old constructor") private
Field Documentation
ForceSectionMapping
const TArray<FSkelMeshMergeSectionMapping>& FSkeletalMeshMerge::ForceSectionMapping private
array to map sections from the source meshes to merged section entries
Definition at line 213 of file SkeletalMeshMerge.h.
InForceSectionMapping
const TArray<USkeletalMesh*> const TArray<FSkelMeshMergeSectionMapping>& FSkeletalMeshMerge::InForceSectionMapping
Definition at line 153 of file SkeletalMeshMerge.h.
Referenced by FSkeletalMeshMerge().
InSrcMeshList
const TArray<USkeletalMesh*>& FSkeletalMeshMerge::InSrcMeshList
Definition at line 152 of file SkeletalMeshMerge.h.
Referenced by FSkeletalMeshMerge().
MaterialIds
TArray<int32> FSkeletalMeshMerge::MaterialIds private
Matches the Materials array in the final mesh - used for creating the right number of Material slots.
Definition at line 222 of file SkeletalMeshMerge.h.
MergeMesh
USkeletalMesh* FSkeletalMeshMerge::MergeMesh private
Destination merged mesh.
Definition at line 188 of file SkeletalMeshMerge.h.
MeshBufferAccess [1/2]
const TArray<USkeletalMesh*> const TArray<FSkelMeshMergeSectionMapping> int32 EMeshBufferAccess FSkeletalMeshMerge::MeshBufferAccess
Definition at line 155 of file SkeletalMeshMerge.h.
Referenced by FSkeletalMeshMerge().
MeshBufferAccess [2/2]
EMeshBufferAccess FSkeletalMeshMerge::MeshBufferAccess private
Whether or not the resulting mesh needs to be accessed by the CPU (e.g.
for particle spawning).
Definition at line 197 of file SkeletalMeshMerge.h.
NewRefSkeleton
FReferenceSkeleton FSkeletalMeshMerge::NewRefSkeleton private
New reference skeleton, made from creating union of each part's skeleton.
Definition at line 210 of file SkeletalMeshMerge.h.
PRAGMA_ENABLE_DEPRECATION_WARNINGS
const TArray<USkeletalMesh*> const TArray<FSkelMeshMergeSectionMapping> int32 EMeshBufferAccess PRAGMA_DISABLE_DEPRECATION_WARNINGS FSkelMeshMergeUVTransforms* InSectionUVTransforms FSkeletalMeshMerge::PRAGMA_ENABLE_DEPRECATION_WARNINGS
Definition at line 158 of file SkeletalMeshMerge.h.
Referenced by FSkeletalMeshMerge().
SectionUVTransforms
const FSkelMeshMergeUVTransformMapping* FSkeletalMeshMerge::SectionUVTransforms private
optional array to transform UVs in each source mesh
Definition at line 216 of file SkeletalMeshMerge.h.
SrcMeshInfo
TArray<FMergeMeshInfo> FSkeletalMeshMerge::SrcMeshInfo private
Array of source mesh info structs.
Definition at line 207 of file SkeletalMeshMerge.h.
SrcMeshList
TArray<USkeletalMesh*> FSkeletalMeshMerge::SrcMeshList private
Array of source skeletal meshes.
Definition at line 191 of file SkeletalMeshMerge.h.
StripTopLODs [1/2]
const TArray<USkeletalMesh*> const TArray<FSkelMeshMergeSectionMapping> int32 FSkeletalMeshMerge::StripTopLODs
Definition at line 154 of file SkeletalMeshMerge.h.
Referenced by FSkeletalMeshMerge().
StripTopLODs [2/2]
int32 FSkeletalMeshMerge::StripTopLODs private
Number of high LODs to remove from input meshes.
Definition at line 194 of file SkeletalMeshMerge.h.
The documentation for this class was generated from the following file:
SkeletalMeshMerge.h