Unreal Engine 5.6 C++ API: UE::Core::Private::PimplPtr Namespace Reference
UE::Core::Private::PimplPtr Namespace Reference
Data Structures
struct TPimplHeapObjectImpl
Typedefs
using FCopyFunc = void*(*)(void*)
using FDeleteFunc = void(*)(void*)
Functions
FORCEINLINE void * CallCopier (void *Ptr)
FORCEINLINE void CallDeleter (void *Ptr)
template<typename T>
static void * CopyFunc (void *A)
template<typename T>
void DeleterFunc (void *Ptr)
Variables
constexpr SIZE_T RequiredAlignment = 16
Typedef Documentation
FCopyFunc
using UE::Core::Private::PimplPtr::FCopyFunc = void*(*)(void*)
Definition at line 81 of file PimplPtr.h.
FDeleteFunc
using UE::Core::Private::PimplPtr::FDeleteFunc = void(*)(void*)
Definition at line 80 of file PimplPtr.h.
Function Documentation
CallCopier()
FORCEINLINE void * UE::Core::Private::PimplPtr::CallCopier (void * Ptr)
Definition at line 132 of file PimplPtr.h.
References FORCEINLINE, and RequiredAlignment.
Referenced by TPimplPtr< T, EPimplPtrMode::DeepCopy >::TPimplPtr(), and TPimplPtr< T, EPimplPtrMode::DeepCopy >::operator=().
CallDeleter()
FORCEINLINE void UE::Core::Private::PimplPtr::CallDeleter (void * Ptr)
Definition at line 121 of file PimplPtr.h.
References FORCEINLINE, and RequiredAlignment.
CopyFunc()
template<typename T> void * UE::Core::Private::PimplPtr::CopyFunc (void * A) static
Definition at line 71 of file PimplPtr.h.
References A.
Referenced by UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl(), and UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl().
DeleterFunc()
template<typename T> void UE::Core::Private::PimplPtr::DeleterFunc (void * Ptr)
Definition at line 62 of file PimplPtr.h.
References UE_ASSUME.
Variable Documentation
RequiredAlignment
SIZE_T UE::Core::Private::PimplPtr::RequiredAlignment = 16 inline constexpr
Definition at line 55 of file PimplPtr.h.
Referenced by UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl(), UE::Core::Private::PimplPtr::TPimplHeapObjectImpl< T >::TPimplHeapObjectImpl(), CallCopier(), CallDeleter(), and TPimplPtr< T, EPimplPtrMode::DeepCopy >::MakePimpl.