Unreal Engine 5.6 C++ API: FNameEntryId Struct Reference
FNameEntryId Struct Reference
Opaque id to a deduplicated name.
#include "NameTypes.h"
Public Types
using IntrusiveUnsetOptionalStateType = FNameEntryId
Public Member Functions
FNameEntryId ()
FNameEntryId (ENoInit)
FNameEntryId (FIntrusiveUnsetOptionalState)
int32 CompareFast (FNameEntryId Rhs) const
Fast non-alphabetical order that is only stable during this process' lifetime.
int32 CompareLexical (FNameEntryId Rhs) const
Slow alphabetical order that is stable / deterministic over process runs, ignores case.
int32 CompareLexicalSensitive (FNameEntryId Rhs) const
Slow alphabetical order that is stable / deterministic over process runs, case-sensitive.
bool FastLess (FNameEntryId Rhs) const
bool IsNone () const
bool LexicalLess (FNameEntryId Rhs) const
bool LexicalSensitiveLess (FNameEntryId Rhs) const
operator bool () const
bool operator!= (FNameEntryId Rhs) const
bool operator< (FNameEntryId Rhs) const
Fast non-alphabetical order that is only stable during this process' lifetime.
bool operator== (FIntrusiveUnsetOptionalState) const
Comparison against special type for checking TOptional<FName>:IsSet.
bool operator== (FNameEntryId Rhs) const
bool operator> (FNameEntryId Rhs) const
Fast non-alphabetical order that is only stable during this process' lifetime.
uint32 ToUnstableInt () const
Get process specific integer.
Static Public Member Functions
static FORCEINLINE FNameEntryId FromEName (EName Ename)
static FNameEntryId FromUnstableInt (uint32 UnstableInt)
Create from unstable int produced by this process.
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Static Private Member Functions
static FNameEntryId FromValidEName (EName Ename)
static FNameEntryId FromValidENamePostInit (EName Ename)
Private Attributes
uint32 Value
Friends
uint32 GetTypeHash (FNameEntryId Id)
bool operator!= (EName Ename, FNameEntryId Id)
bool operator!= (FNameEntryId Id, EName Ename)
FArchive & operator<< (FArchive &Ar, FNameEntryId &InId)
Serialize as process specific unstable int.
bool operator== (EName Ename, FNameEntryId Id)
bool operator== (FNameEntryId Id, EName Ename)
Detailed Description
Opaque id to a deduplicated name.
Definition at line 55 of file NameTypes.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
using FNameEntryId::IntrusiveUnsetOptionalStateType = FNameEntryId
Definition at line 58 of file NameTypes.h.
Constructor & Destructor Documentation
FNameEntryId() [1/3]
FNameEntryId::FNameEntryId () inline
Definition at line 61 of file NameTypes.h.
References Value.
Referenced by CompareFast(), CompareLexical(), CompareLexicalSensitive(), FastLess(), FromEName(), FromUnstableInt(), FromValidEName(), FromValidENamePostInit(), GetTypeHash, LexicalLess(), LexicalSensitiveLess(), operator!=, operator!=, operator!=(), operator<(), operator<<, operator==, operator==, operator==(), and operator>().
FNameEntryId() [2/3]
FNameEntryId::FNameEntryId (ENoInit) inline
Definition at line 62 of file NameTypes.h.
FNameEntryId() [3/3]
FNameEntryId::FNameEntryId (FIntrusiveUnsetOptionalState) inline explicit
Definition at line 63 of file NameTypes.h.
References Value.
Member Function Documentation
CompareFast()
int32 FNameEntryId::CompareFast (FNameEntryId Rhs) const inline
Fast non-alphabetical order that is only stable during this process' lifetime.
Definition at line 79 of file NameTypes.h.
References FNameEntryId(), and Value.
Referenced by FastLess().
CompareLexical()
int32 FNameEntryId::CompareLexical (FNameEntryId Rhs) const
Slow alphabetical order that is stable / deterministic over process runs, ignores case.
References FNameEntryId().
Referenced by LexicalLess().
CompareLexicalSensitive()
int32 FNameEntryId::CompareLexicalSensitive (FNameEntryId Rhs) const
Slow alphabetical order that is stable / deterministic over process runs, case-sensitive.
References FNameEntryId().
Referenced by LexicalSensitiveLess().
FastLess()
bool FNameEntryId::FastLess (FNameEntryId Rhs) const inline
Definition at line 80 of file NameTypes.h.
References FNameEntryId(), and CompareFast().
FromEName()
FORCEINLINE FNameEntryId FNameEntryId::FromEName (EName Ename) inline static
Definition at line 110 of file NameTypes.h.
References FNameEntryId(), FORCEINLINE, and FromValidEName().
FromUnstableInt()
FNameEntryId FNameEntryId::FromUnstableInt (uint32 UnstableInt) inline static
Create from unstable int produced by this process.
Definition at line 103 of file NameTypes.h.
References FNameEntryId(), and Value.
Referenced by FLazyName::FLiteralOrName::GetComparisionId(), and FLazyName::FLiteralOrName::GetDisplayId().
FromValidEName()
FNameEntryId FNameEntryId::FromValidEName (EName Ename) static private
References FNameEntryId().
Referenced by FromEName().
FromValidENamePostInit()
FNameEntryId FNameEntryId::FromValidENamePostInit (EName Ename) static private
References FNameEntryId().
Referenced by operator==.
IsNone()
bool FNameEntryId::IsNone () const inline
Definition at line 65 of file NameTypes.h.
References Value.
LexicalLess()
bool FNameEntryId::LexicalLess (FNameEntryId Rhs) const inline
Definition at line 72 of file NameTypes.h.
References FNameEntryId(), and CompareLexical().
LexicalSensitiveLess()
bool FNameEntryId::LexicalSensitiveLess (FNameEntryId Rhs) const inline
Definition at line 76 of file NameTypes.h.
References FNameEntryId(), and CompareLexicalSensitive().
operator bool()
FNameEntryId::operator bool () const inline explicit
Definition at line 97 of file NameTypes.h.
References Value.
operator!=()
bool FNameEntryId::operator!= (FNameEntryId Rhs) const inline
Definition at line 88 of file NameTypes.h.
References FNameEntryId(), and Value.
operator<()
bool FNameEntryId::operator< (FNameEntryId Rhs) const inline
Fast non-alphabetical order that is only stable during this process' lifetime.
Definition at line 83 of file NameTypes.h.
References FNameEntryId(), and Value.
operator==() [1/2]
bool FNameEntryId::operator== (FIntrusiveUnsetOptionalState) const inline
Comparison against special type for checking TOptional<FName>:IsSet.
Definition at line 91 of file NameTypes.h.
References Value.
operator==() [2/2]
bool FNameEntryId::operator== (FNameEntryId Rhs) const inline
Definition at line 87 of file NameTypes.h.
References FNameEntryId(), and Value.
operator>()
bool FNameEntryId::operator> (FNameEntryId Rhs) const inline
Fast non-alphabetical order that is only stable during this process' lifetime.
Definition at line 86 of file NameTypes.h.
References FNameEntryId(), and Value.
ToUnstableInt()
uint32 FNameEntryId::ToUnstableInt () const inline
Get process specific integer.
Definition at line 100 of file NameTypes.h.
References Value.
Referenced by UE::ConfigAccessTracking::FConfigAccessData::GetTypeHash.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FNameEntryId Id) friend
References FNameEntryId().
operator!= [1/2]
bool operator!= (EName Ename, FNameEntryId Id) friend
Definition at line 128 of file NameTypes.h.
References FNameEntryId().
operator!= [2/2]
bool operator!= (FNameEntryId Id, EName Ename) friend
Definition at line 129 of file NameTypes.h.
References FNameEntryId().
operator<<
FArchive & operator<< (FArchive & Ar, FNameEntryId & InId) friend
Serialize as process specific unstable int.
References FNameEntryId(), and Ar.
operator== [1/2]
bool operator== (EName Ename, FNameEntryId Id) friend
Definition at line 127 of file NameTypes.h.
References FNameEntryId().
operator== [2/2]
bool operator== (FNameEntryId Id, EName Ename) friend
Definition at line 115 of file NameTypes.h.
References FNameEntryId(), and FromValidENamePostInit().
Field Documentation
bHasIntrusiveUnsetOptionalState
bool FNameEntryId::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 57 of file NameTypes.h.
Value
uint32 FNameEntryId::Value private
Definition at line 121 of file NameTypes.h.
Referenced by FNameEntryId(), FNameEntryId(), CompareFast(), FromUnstableInt(), IsNone(), operator bool(), operator!=(), operator<(), operator==(), operator==(), operator>(), and ToUnstableInt().
The documentation for this struct was generated from the following file:
NameTypes.h