Unreal Engine 5.6 C++ API: UE::MovieScene::FPlaybackCapabilities Struct Reference
UE::MovieScene::FPlaybackCapabilities Struct Reference
Actual playback capabilities container.
#include "MovieScenePlaybackCapabilities.h"
Public Member Functions
FPlaybackCapabilities ()=default
FPlaybackCapabilities (const FPlaybackCapabilities &)=delete
MOVIESCENE_API FPlaybackCapabilities (FPlaybackCapabilities &&)
MOVIESCENE_API ~FPlaybackCapabilities ()
template<typename T, typename ... ArgTypes>
T & AddCapability (ArgTypes &&... InArgs)
Adds the specified capability to the container, using the supplied arguments to construct it.
template<typename T, typename U, typename ... ArgTypes>
T & AddCapability (const TPlaybackCapabilityID< U > CapabilityID, ArgTypes &&... InArgs)
As per AsCapability, but with an explicit capability ID.
template<typename T>
T & AddCapabilityRaw (T *InPointer)
Adds the specified capability to the container, as a simple raw pointer Ownership of the capability object being pointed to is the caller's responsability.
template<typename T>
T & AddCapabilityShared (TSharedRef< T > InSharedRef)
Adds the specified capability to the container, as a shared pointer Ownership of the capability object being pointed to respects classic shared pointer semantics.
template<typename T>
T * FindCapability () const
Finds the specified capability within the container, if present.
template<typename T>
T & GetCapabilityChecked () const
Returns the specified capability within the container, asserts if not found.
template<typename T>
bool HasCapability () const
Checks whether this container has the given capability.
void InvalidateCachedData (UMovieSceneEntitySystemLinker *Linker)
Calls InvalidateCacheData on any capability that implements the IPlaybackCapability interface.
void OnSubInstanceCreated (TSharedRef< const FSharedPlaybackState > Owner, const FInstanceHandle InstanceHandle)
Calls OnSubInstanceCreated on any capability that implements the IPlaybackCapability interface.
FPlaybackCapabilities & operator= (const FPlaybackCapabilities &)=delete
MOVIESCENE_API FPlaybackCapabilities & operator= (FPlaybackCapabilities &&)
template<typename T, typename ... ArgTypes>
T & OverwriteCapability (ArgTypes &&... InArgs)
Overwrites an existing capability, stored inline and owned by this container.
template<typename T>
T & OverwriteCapabilityRaw (T *InPointer)
Overwrites an existing capability, stored as a raw pointer on the container.
template<typename T>
T & OverwriteCapabilityShared (TSharedRef< T > InSharedRef)
Overwrites an existing capability, stored as a shared pointer on the container.
Private Member Functions
void Destroy ()
template<typename Impl, typename T, typename ... ArgTypes>
T & DoAddCapability (TPlaybackCapabilityID< T > CapabilityID, ArgTypes &&... InArgs)
template<typename Impl, typename T, typename ... ArgTypes>
T & DoOverwriteCapability (TPlaybackCapabilityID< T > CapabilityID, ArgTypes &&... InArgs)
template<typename Callback, typename ... ArgTypes>
void ForEachCapabilityInterface (Callback &&InCallback, ArgTypes &&... InArgs)
Additional Inherited Members
Protected Member Functions inherited from UE::MovieScene::FPlaybackCapabilitiesImpl
FPlaybackCapabilitiesImpl ()=default
FPlaybackCapabilitiesImpl (const FPlaybackCapabilitiesImpl &)=delete
FPlaybackCapabilitiesImpl (FPlaybackCapabilitiesImpl &&)=delete
template<typename StorageType, typename CapabilityType, typename ... ArgTypes>
FPlaybackCapabilityPtr AddCapability (uint32 CapabilityBit, ArgTypes &&... InArgs)
Creates and stores a new capability object at the given bit.
FPlaybackCapabilityPtr FindCapability (uint32 CapabilityBit) const
FPlaybackCapabilityPtr GetCapabilityChecked (uint32 CapabilityBit) const
int32 GetCapabilityIndex (uint32 CapabilityBit) const
FPlaybackCapabilityHeader & GetHeader (uint8 Index)
const FPlaybackCapabilityHeader & GetHeader (uint8 Index) const
TArrayView< const FPlaybackCapabilityHeader > GetHeaders () const
bool HasCapability (uint32 CapabilityBit) const
FPlaybackCapabilitiesImpl & operator= (const FPlaybackCapabilitiesImpl &)=delete
FPlaybackCapabilitiesImpl & operator= (FPlaybackCapabilitiesImpl &&)=delete
template<typename StorageType, typename CapabilityType, typename ... ArgTypes>
bool OverwriteCapability (uint32 CapabilityBit, ArgTypes &&... InArgs)
Protected Attributes inherited from UE::MovieScene::FPlaybackCapabilitiesImpl
uint16 Alignment = 0u
uint32 AllCapabilities = 0u
uint16 Capacity = 0u
TArray< FPlaybackCapabilityHelpers > Helpers
uint8 * Memory = nullptr
uint8 Num = 0u
Detailed Description
Actual playback capabilities container.
Definition at line 613 of file MovieScenePlaybackCapabilities.h.
Constructor & Destructor Documentation
FPlaybackCapabilities() [1/3]
UE::MovieScene::FPlaybackCapabilities::FPlaybackCapabilities () default
Referenced by FPlaybackCapabilities(), FPlaybackCapabilities(), operator=(), and operator=().
FPlaybackCapabilities() [2/3]
UE::MovieScene::FPlaybackCapabilities::FPlaybackCapabilities (const FPlaybackCapabilities &) delete
References FPlaybackCapabilities().
FPlaybackCapabilities() [3/3]
MOVIESCENE_API UE::MovieScene::FPlaybackCapabilities::FPlaybackCapabilities (FPlaybackCapabilities &&)
References FPlaybackCapabilities().
~FPlaybackCapabilities()
MOVIESCENE_API UE::MovieScene::FPlaybackCapabilities::~FPlaybackCapabilities ()
Member Function Documentation
AddCapability() [1/2]
template<typename T, typename ... ArgTypes> T & UE::MovieScene::FPlaybackCapabilities::AddCapability (ArgTypes &&... InArgs) inline
Adds the specified capability to the container, using the supplied arguments to construct it.
The capability object will be stored inline and owned by this container. It will be destroyed when the container itself is destroyed. If the template parameter is a sub-class of the playback capability class, that sub-class will be created and stored inline.
Definition at line 671 of file MovieScenePlaybackCapabilities.h.
References DoAddCapability(), and Forward().
AddCapability() [2/2]
template<typename T, typename U, typename ... ArgTypes> T & UE::MovieScene::FPlaybackCapabilities::AddCapability (const TPlaybackCapabilityID< U > CapabilityID, ArgTypes &&... InArgs) inline
As per AsCapability, but with an explicit capability ID.
This is useful when the first template parameter doesn't have a single static member called ID providing the capability ID.
Definition at line 685 of file MovieScenePlaybackCapabilities.h.
References DoAddCapability(), and Forward().
AddCapabilityRaw()
template<typename T> T & UE::MovieScene::FPlaybackCapabilities::AddCapabilityRaw (T * InPointer) inline
Adds the specified capability to the container, as a simple raw pointer Ownership of the capability object being pointed to is the caller's responsability.
This container will only store a raw pointer.
Definition at line 697 of file MovieScenePlaybackCapabilities.h.
References DoAddCapability().
AddCapabilityShared()
template<typename T> T & UE::MovieScene::FPlaybackCapabilities::AddCapabilityShared (TSharedRef< T > InSharedRef) inline
Adds the specified capability to the container, as a shared pointer Ownership of the capability object being pointed to respects classic shared pointer semantics.
This container only maintains one such shared pointer until the container is destroyed.
Definition at line 712 of file MovieScenePlaybackCapabilities.h.
References DoAddCapability(), and StaticCastSharedRef().
Destroy()
void UE::MovieScene::FPlaybackCapabilities::Destroy () private
DoAddCapability()
template<typename Impl, typename T, typename ... ArgTypes> T & UE::MovieScene::FPlaybackCapabilities::DoAddCapability (TPlaybackCapabilityID< T > CapabilityID, ArgTypes &&... InArgs) inline private
Definition at line 800 of file MovieScenePlaybackCapabilities.h.
References UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), Forward(), UE::MovieScene::FPlaybackCapabilityID::Index, and UE::MovieScene::FPlaybackCapabilityPtr::ResolveChecked().
Referenced by AddCapability(), AddCapability(), AddCapabilityRaw(), and AddCapabilityShared().
DoOverwriteCapability()
template<typename Impl, typename T, typename ... ArgTypes> T & UE::MovieScene::FPlaybackCapabilities::DoOverwriteCapability (TPlaybackCapabilityID< T > CapabilityID, ArgTypes &&... InArgs) inline private
Definition at line 808 of file MovieScenePlaybackCapabilities.h.
References Forward(), GetCapabilityChecked(), UE::MovieScene::FPlaybackCapabilityID::Index, and UE::MovieScene::FPlaybackCapabilitiesImpl::OverwriteCapability().
Referenced by OverwriteCapability(), OverwriteCapabilityRaw(), and OverwriteCapabilityShared().
FindCapability()
template<typename T> T * UE::MovieScene::FPlaybackCapabilities::FindCapability () const inline
Finds the specified capability within the container, if present.
Definition at line 635 of file MovieScenePlaybackCapabilities.h.
References UE::MovieScene::FPlaybackCapabilitiesImpl::FindCapability(), UE::MovieScene::FPlaybackCapabilityID::Index, and UE::MovieScene::FPlaybackCapabilityPtr::ResolveOptional().
ForEachCapabilityInterface()
template<typename Callback, typename ... ArgTypes> void UE::MovieScene::FPlaybackCapabilities::ForEachCapabilityInterface (Callback && InCallback, ArgTypes &&... InArgs) inline private
Definition at line 781 of file MovieScenePlaybackCapabilities.h.
References check, Forward(), UE::MovieScene::FPlaybackCapabilitiesImpl::GetHeaders(), Header, UE::MovieScene::FPlaybackCapabilitiesImpl::Helpers, Interface, UE::MovieScene::FPlaybackCapabilityHelpers::InterfaceCast, UE::MovieScene::FPlaybackCapabilitiesImpl::Memory, and TArrayView< InElementType, InSizeType >::Num().
GetCapabilityChecked()
template<typename T> T & UE::MovieScene::FPlaybackCapabilities::GetCapabilityChecked () const inline
Returns the specified capability within the container, asserts if not found.
Definition at line 650 of file MovieScenePlaybackCapabilities.h.
References UE::MovieScene::FPlaybackCapabilitiesImpl::GetCapabilityChecked(), UE::MovieScene::FPlaybackCapabilityID::Index, and UE::MovieScene::FPlaybackCapabilityPtr::ResolveChecked().
Referenced by DoOverwriteCapability().
HasCapability()
template<typename T> bool UE::MovieScene::FPlaybackCapabilities::HasCapability () const inline
Checks whether this container has the given capability.
Definition at line 627 of file MovieScenePlaybackCapabilities.h.
References UE::MovieScene::FPlaybackCapabilitiesImpl::HasCapability().
InvalidateCachedData()
void UE::MovieScene::FPlaybackCapabilities::InvalidateCachedData (UMovieSceneEntitySystemLinker * Linker)
Calls InvalidateCacheData on any capability that implements the IPlaybackCapability interface.
OnSubInstanceCreated()
void UE::MovieScene::FPlaybackCapabilities::OnSubInstanceCreated (TSharedRef< const FSharedPlaybackState > Owner, const FInstanceHandle InstanceHandle)
Calls OnSubInstanceCreated on any capability that implements the IPlaybackCapability interface.
References Owner.
operator=() [1/2]
FPlaybackCapabilities & UE::MovieScene::FPlaybackCapabilities::operator= (const FPlaybackCapabilities &) delete
References FPlaybackCapabilities().
operator=() [2/2]
MOVIESCENE_API FPlaybackCapabilities & UE::MovieScene::FPlaybackCapabilities::operator= (FPlaybackCapabilities &&)
References FPlaybackCapabilities().
OverwriteCapability()
template<typename T, typename ... ArgTypes> T & UE::MovieScene::FPlaybackCapabilities::OverwriteCapability (ArgTypes &&... InArgs) inline
Overwrites an existing capability, stored inline and owned by this container.
The previous storage mode of the capability must also be inline. If the template parameter is a sub-class of the playback capability, the previously stored playback capability must not only have been stored inline, but must have been of the same sub-class (or a sub-class with the exact same size and alignment).
Definition at line 729 of file MovieScenePlaybackCapabilities.h.
References DoOverwriteCapability(), and Forward().
OverwriteCapabilityRaw()
template<typename T> T & UE::MovieScene::FPlaybackCapabilities::OverwriteCapabilityRaw (T * InPointer) inline
Overwrites an existing capability, stored as a raw pointer on the container.
The previous storage mode of the capability must also be a raw pointer.
Definition at line 743 of file MovieScenePlaybackCapabilities.h.
References DoOverwriteCapability().
OverwriteCapabilityShared()
template<typename T> T & UE::MovieScene::FPlaybackCapabilities::OverwriteCapabilityShared (TSharedRef< T > InSharedRef) inline
Overwrites an existing capability, stored as a shared pointer on the container.
The previous storage mode of the capability must also be a shared pointer.
Definition at line 757 of file MovieScenePlaybackCapabilities.h.
References DoOverwriteCapability(), and StaticCastSharedRef().
The documentation for this struct was generated from the following file:
MovieScenePlaybackCapabilities.h