Unreal Engine 5.6 C++ API: UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy Struct Reference
UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy Struct Reference
#include "MovieSceneMaterialSystem.h"
Public Types
using GroupKeyType = TTuple<RequiredComponents..., FMaterialParameterInfo>
Public Member Functions
void InitializeGroupKeys (TEntityGroupingHandlerBase< FMaterialGroupingPolicy > &Handler, FEntityGroupBuilder *Builder, FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, TRead< RequiredComponents >... Components)
bool OnObjectsReplaced (GroupKeyType &InOutKey, const TMap< UObject *, UObject * > &ReplacementMap)
Detailed Description
template<typename AccessorType, typename... RequiredComponents>
struct UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy
Definition at line 108 of file MovieSceneMaterialSystem.h.
Member Typedef Documentation
GroupKeyType
template<typename AccessorType, typename... RequiredComponents> using UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::GroupKeyType = TTuple<RequiredComponents..., FMaterialParameterInfo>
Definition at line 110 of file MovieSceneMaterialSystem.h.
Member Function Documentation
InitializeGroupKeys()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys (TEntityGroupingHandlerBase< FMaterialGroupingPolicy > & Handler, FEntityGroupBuilder * Builder, FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, TRead< RequiredComponents >... Components) inline
Definition at line 112 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::FEntityGroupBuilder::AddEntityToGroup(), UE::MovieScene::FMovieSceneTracksComponentTypes::ColorMaterialParameterInfo, UE::MovieScene::FMovieSceneTracksComponentTypes::ColorParameterName, Components, UE::MovieScene::FComponentMask::Contains(), UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >::GetOrAllocateGroupIndex(), Item, Key, UE::MovieScene::FEntityGroupBuilder::MakeGroupID(), MakeTuple(), Num, UE::MovieScene::FMovieSceneTracksComponentTypes::ScalarMaterialParameterInfo, UE::MovieScene::FMovieSceneTracksComponentTypes::ScalarParameterName, UE::MovieScene::FMovieSceneTracksComponentTypes::VectorMaterialParameterInfo, and UE::MovieScene::FMovieSceneTracksComponentTypes::VectorParameterName.
OnObjectsReplaced()
template<typename AccessorType, typename... RequiredComponents> bool UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::OnObjectsReplaced (GroupKeyType & InOutKey, const TMap< UObject *, UObject * > & ReplacementMap) inline
Definition at line 177 of file MovieSceneMaterialSystem.h.
The documentation for this struct was generated from the following file:
MovieSceneMaterialSystem.h