Unreal Engine 5.6 C++ API: THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType > Class Template Reference
THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType > Class Template Reference
Hierarchical Hash Grid in 2D.
#include "HierarchicalHashGrid2D.h"
Data Structures
struct FCell
Ratio in cells between consecutive levels.
struct FCellLocation
Specifies cell location within the grid at specific level.
struct FCellRect
Rectangle bounds, coordinates inclusive.
struct FCellRectIterator
Iterator state over a rectangle.
struct FItem
Item stored in a grid cell.
Public Types
typedef InItemIDType ItemIDType
Public Member Functions
THierarchicalHashGrid2D (const float InCellSize=500.f)
Constructor, initializes the grid for specific cell size.
FCellLocation Add (const ItemIDType ID, const FBox &Bounds)
Adds item to the grid.
void Add (const ItemIDType ID, const FCellLocation &Location)
Adds item to the grid.
FBox CalcCellBounds (const FCellLocation &CellLocation) const
Finds the world box from a cell.
FCellLocation CalcCellLocation (const FBox &Bounds) const
Finds grid level where the bounds fit inside a cell.
FCellRect CalcQueryBounds (const FBox &Bounds, const int32 Level) const
Calculates cell based query rectangle.
const FCell * FindCell (const int X, const int Y, const int Level) const
Returns a cell for specific location and level.
FCell * FindCellMutable (const int X, const int Y, const int Level)
Returns a cell for specific location and level.
FCell & FindOrAddCell (const int X, const int Y, const int Level)
Returns a cell for specific location and level, creates new cell if it does not exist.
const TSet< FCell > & GetCells () const
float GetCellSize (const int32 Level) const
int32 GetFirstSpillListItem () const
float GetInvCellSize (const int32 Level) const
const TSparseArray< FItem > & GetItems () const
int32 GetLevelItemCount (const int32 Level) const
void Initialize (const float InCellSize)
Resets and initializes the grid for specific cell size.
FCellRect IntersectRect (const FCellRect &Left, const FCellRect &Right) const
Returns intersection of the two cell bounding rectangles.
FCellLocation Move (const ItemIDType ID, const FBox &OldBounds, const FBox &NewBounds)
Moves item based on previous bounding box and new bounding box.
FCellLocation Move (const ItemIDType ID, const FCellLocation &OldLocation, const FBox &NewBounds)
Moves item based on previous cell location and new bounding box.
template<typename OutT>
void Query (const FBox &Bounds, OutT &OutResults) const
Returns items that potentially touch the bounds.
template<typename OutT>
void QuerySmall (const FBox &Bounds, OutT &OutResults) const
Returns items that potentially touch the bounds.
void Remove (const ItemIDType ID, const FBox &OldBounds)
Removes item based on the bounding box it was added with.
void Remove (const ItemIDType ID, const FCellLocation &OldLocation)
Removes item based on the cell location it was added with.
void Reset ()
Reset the grid to empty.
Static Public Member Functions
static int32 LevelDown (int32 X)
Levels down a coordinate using floor rounding.
Static Public Attributes
static const int32 LevelRatio = InLevelRatio
Number of grid levels in the grid.
static const int32 NumLevels = InNumLevels
Static Protected Member Functions
static constexpr int32 ClampInt32 (const int64 Value)
Protected Attributes
TSet< FCell > Cells
Number items per level, can be used to skip certain levels.
TStaticArray< float, NumLevels > CellSize
TStaticArray< float, NumLevels > InvCellSize
Lowest level cell size.
TSparseArray< FItem > Items
TSet uses hash buckets to locate items.
TStaticArray< int32, NumLevels > LevelItemCount
1 / CellSize
int32 SpillList = INDEX_NONE
TSparseArray uses freelist to recycled used items.
Detailed Description
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32>
class THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >
Hierarchical Hash Grid in 2D.
Items are added to the "infinite" grid at specific level based on their size. The grid size, and size ratio between levels are defined as the template parameter. This allows some computation to be optimized based on the values.
Items that cannot be fitted in the grid are added to a spill list, which contents are included in all queries. Each item is added to just one grid cell and thus can overlap some neighbour cells up to half cell size at that grid level. This is compensated during the query by expanding the query box.
Potential optimizations:
(X, Y, Level) could probably be int16.
Level ratio could be a shift so LevelDown() could become just shift.
FloorToInt ends up calling floorf, which will be a function call. int FloorToInt(float a) { return (int)a + ((int)a > a ? -1 : 0); } auto vectorizes nicely on clang, but not on VC.
Add helper function to allow to tweak the cell size to reset the grid when spill list gets too large
Definition at line 35 of file HierarchicalHashGrid2D.h.
Member Typedef Documentation
ItemIDType
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> typedef InItemIDType THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::ItemIDType
Definition at line 39 of file HierarchicalHashGrid2D.h.
Constructor & Destructor Documentation
THierarchicalHashGrid2D()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::THierarchicalHashGrid2D (const float InCellSize = 500.f) inline
Constructor, initializes the grid for specific cell size.
Parameters
InCellSize - new finest level cell size of the grid
Definition at line 124 of file HierarchicalHashGrid2D.h.
Member Function Documentation
Add() [1/2]
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCellLocation THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Add (const ItemIDType ID, const FBox & Bounds) inline
Adds item to the grid.
Parameters
ID - External ID used to identify the item.
Bounds - Bounding box of the item.
Returns
Cell location of the item, can be used later to remove the item.
Definition at line 179 of file HierarchicalHashGrid2D.h.
Add() [2/2]
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> void THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Add (const ItemIDType ID, const FCellLocation & Location) inline
Adds item to the grid.
Parameters
ID - External ID used to identify the item.
Location - Cell location where the item should be added.
Returns
Cell location of the item, can be used later to remove the item.
Definition at line 191 of file HierarchicalHashGrid2D.h.
CalcCellBounds()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FBox THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::CalcCellBounds (const FCellLocation & CellLocation) const inline
Finds the world box from a cell.
@params CellLocation - Cell location.
Returns
Returns the bounds of the cell.
Definition at line 542 of file HierarchicalHashGrid2D.h.
CalcCellLocation()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCellLocation THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::CalcCellLocation (const FBox & Bounds) const inline
Finds grid level where the bounds fit inside a cell.
Parameters
Bounds - Bounding box of the item.
Returns
Returns cell location of the item, or location at Level == INDEX_NONE if the item cannot fit in the grid.
Definition at line 509 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Add(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Move(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Move(), and THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Remove().
CalcQueryBounds()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCellRect THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::CalcQueryBounds (const FBox & Bounds, const int32 Level) const inline
Calculates cell based query rectangle.
The bounds are expanded by half grid cell size because the items are stored for only one cell based on their center and side. For that reason the items can overlap the neighbor cells by half the cell size.
Parameters
Bounds - Query bounding box to quantize.
Level - Which level of the tree the to calculate the bounds for
Returns
Quantized rectangle representing the cell bounds at specific level of the tree, coordinates inclusive.
Definition at line 470 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Query(), and THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::QuerySmall().
ClampInt32()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> constexpr int32 THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::ClampInt32 (const int64 Value) inline static constexpr protected
Returns
given int64 clamped in int32 range.
Definition at line 616 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcCellLocation(), and THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcQueryBounds().
FindCell()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> const FCell * THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::FindCell (const int X, const int Y, const int Level) const inline
Returns a cell for specific location and level.
Parameters
X - Cell X coordinate.
Y - Cell Y coordinate.
Level - Grid Level.
Returns
Pointer to cell at specified location, or return nullptr if the cell does not exist.
Definition at line 588 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Query(), and THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::QuerySmall().
FindCellMutable()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCell * THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::FindCellMutable (const int X, const int Y, const int Level) inline
Returns a cell for specific location and level.
Parameters
X - Cell X coordinate.
Y - Cell Y coordinate.
Level - Grid Level.
Returns
Pointer to cell at specified location, or return nullptr if the cell does not exist.
Definition at line 575 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Remove().
FindOrAddCell()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCell & THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::FindOrAddCell (const int X, const int Y, const int Level) inline
Returns a cell for specific location and level, creates new cell if it does not exist.
Parameters
X - Cell X coordinate.
Y - Cell Y coordinate.
Level - Grid Level.
Returns
Reference to cell at specified location.
Definition at line 556 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Add().
GetCells()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> const TSet< FCell > & THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::GetCells () const inline
Returns
Set containing all the cells.
Definition at line 605 of file HierarchicalHashGrid2D.h.
GetCellSize()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> float THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::GetCellSize (const int32 Level) const inline
Returns
Cell size at specific grid level.
Definition at line 596 of file HierarchicalHashGrid2D.h.
GetFirstSpillListItem()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> int32 THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::GetFirstSpillListItem () const inline
Returns
Index in items of the first item on the spill list.
Definition at line 611 of file HierarchicalHashGrid2D.h.
GetInvCellSize()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> float THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::GetInvCellSize (const int32 Level) const inline
Returns
1/cellSize at specific grid level.
Definition at line 599 of file HierarchicalHashGrid2D.h.
GetItems()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> const TSparseArray< FItem > & THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::GetItems () const inline
Returns
Sparse array containing all the items.
Definition at line 608 of file HierarchicalHashGrid2D.h.
GetLevelItemCount()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> int32 THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::GetLevelItemCount (const int32 Level) const inline
Returns
Array containing all the items.
Definition at line 602 of file HierarchicalHashGrid2D.h.
Initialize()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> void THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Initialize (const float InCellSize) inline
Resets and initializes the grid for specific cell size.
Parameters
InCellSize - new finest level cell size of the grid
Definition at line 146 of file HierarchicalHashGrid2D.h.
IntersectRect()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCellRect THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::IntersectRect (const FCellRect & Left, const FCellRect & Right) const inline
Returns intersection of the two cell bounding rectangles.
Parameters
Left - left hand side rectangle
Right - right hand side rectangle
Returns
Intersecting are between left and right.
Definition at line 485 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Query().
LevelDown()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> int32 THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::LevelDown (int32 X) inline static
Levels down a coordinate using floor rounding.
Parameters
X - Coordinate to level down
Returns
Coordinate at coarser level.
Definition at line 499 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Add(), and THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Remove().
Move() [1/2]
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCellLocation THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Move (const ItemIDType ID, const FBox & OldBounds, const FBox & NewBounds) inline
Moves item based on previous bounding box and new bounding box.
Parameters
ID - External ID used to identify the item.
OldBounds - The same bounding box the item was previously added or moved with.
NewBounds - New bounds of the item
Returns
The cell location where the item was added to.
Definition at line 312 of file HierarchicalHashGrid2D.h.
Move() [2/2]
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> FCellLocation THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Move (const ItemIDType ID, const FCellLocation & OldLocation, const FBox & NewBounds) inline
Moves item based on previous cell location and new bounding box.
Parameters
ID - External ID used to identify the item.
OldLocation - The same cell location the item was previously added or moved with.
NewBounds - New bounds of the item
Returns
The cell location where the item was added to.
Definition at line 324 of file HierarchicalHashGrid2D.h.
Query()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> template<typename OutT> void THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Query (const FBox & Bounds, OutT & OutResults) const inline
Returns items that potentially touch the bounds.
Operates on grid level, can have false positives.
Parameters
Bounds - Query bounding box.
OutResults - Result of the query, IDs of potentially overlapping items.
Definition at line 382 of file HierarchicalHashGrid2D.h.
QuerySmall()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> template<typename OutT> void THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::QuerySmall (const FBox & Bounds, OutT & OutResults) const inline
Returns items that potentially touch the bounds.
Operates on grid level, can have false positives. This can be faster than Query() for small query box sizes (i.e. max dimension CellSize*4) due to simpler logic.
Parameters
Bounds - Query bounding box.
OutResults - Result of the query, IDs of potentially overlapping items.
Definition at line 341 of file HierarchicalHashGrid2D.h.
Remove() [1/2]
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> void THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Remove (const ItemIDType ID, const FBox & OldBounds) inline
Removes item based on the bounding box it was added with.
Parameters
ID - External ID used to identify the item.
OldBounds - The same bounding box the item was previously added or moved with.
Definition at line 230 of file HierarchicalHashGrid2D.h.
Remove() [2/2]
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> void THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Remove (const ItemIDType ID, const FCellLocation & OldLocation) inline
Removes item based on the cell location it was added with.
Parameters
ID - External ID used to identify the item.
OldLocation - The same cell location the item was previously added or moved with.
Definition at line 240 of file HierarchicalHashGrid2D.h.
Reset()
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> void THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Reset () inline
Reset the grid to empty.
Definition at line 162 of file HierarchicalHashGrid2D.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::Initialize().
Field Documentation
Cells
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> TSet<FCell> THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Cells protected
Number items per level, can be used to skip certain levels.
Definition at line 627 of file HierarchicalHashGrid2D.h.
CellSize
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> TStaticArray<float, NumLevels> THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::CellSize protected
Definition at line 624 of file HierarchicalHashGrid2D.h.
InvCellSize
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> TStaticArray<float, NumLevels> THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::InvCellSize protected
Lowest level cell size.
Definition at line 625 of file HierarchicalHashGrid2D.h.
Items
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> TSparseArray<FItem> THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::Items protected
TSet uses hash buckets to locate items.
Definition at line 628 of file HierarchicalHashGrid2D.h.
LevelItemCount
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> TStaticArray<int32, NumLevels> THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::LevelItemCount protected
1 / CellSize
Definition at line 626 of file HierarchicalHashGrid2D.h.
LevelRatio
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> const int32 THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::LevelRatio = InLevelRatio static
Number of grid levels in the grid.
Definition at line 41 of file HierarchicalHashGrid2D.h.
NumLevels
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> const int32 THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::NumLevels = InNumLevels static
Definition at line 40 of file HierarchicalHashGrid2D.h.
SpillList
template<int32 InNumLevels = 3, int32 InLevelRatio = 4, typename InItemIDType = uint32> int32 THierarchicalHashGrid2D< InNumLevels, InLevelRatio, InItemIDType >::SpillList = INDEX_NONE protected
TSparseArray uses freelist to recycled used items.
Definition at line 629 of file HierarchicalHashGrid2D.h.
The documentation for this class was generated from the following file:
HierarchicalHashGrid2D.h