Unreal Engine 5.6 C++ API: SConstraintCanvas::FSlot Class Reference
SConstraintCanvas::FSlot Class Reference
ConstraintCanvas slots allow child widgets to be positioned and sized.
#include "SConstraintCanvas.h"
Public Member Functions
FSlot ()
Default values for a slot.
FVector2D GetAlignment () const
FAnchors GetAnchors () const
bool GetAutoSize () const
FMargin GetOffset () const
float GetZOrder () const
void SetAlignment (const TAttribute< FVector2D > &InAlignment)
void SetAnchors (const TAttribute< FAnchors > &InAnchors)
void SetAutoSize (const TAttribute< bool > &InAutoSize)
void SetOffset (const TAttribute< FMargin > &InOffset)
void SetZOrder (float InZOrder)
Offset Alignment SLATE_ATTRIBUTE (bool, AutoSize) SLATE_ARGUMENT(TOptional< float >
Offset SLATE_ATTRIBUTE (FAnchors, Anchors) SLATE_ATTRIBUTE(FVector2D
SLATE_SLOT_BEGIN_ARGS (FSlot, TSlotBase< FSlot >) SLATE_ATTRIBUTE(FMargin
Offset Alignment ZOrder SLATE_SLOT_END_ARGS () 1 void Construct(const FChildren &SlotOwner
Public Member Functions inherited from TSlotBase< FSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlot & Expose (FSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Data Fields
Offset Alignment ZOrder FSlotArguments && InArgs
Private Attributes
TAttribute< FVector2D > AlignmentAttr
Size.
TAttribute< FAnchors > AnchorsAttr
Anchors.
TAttribute< bool > AutoSizeAttr
Auto-Size.
TAttribute< FMargin > OffsetAttr
Offset.
float ZOrder
Z-Order.
Additional Inherited Members
Public Types inherited from TSlotBase< FSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Detailed Description
ConstraintCanvas slots allow child widgets to be positioned and sized.
Definition at line 34 of file SConstraintCanvas.h.
Constructor & Destructor Documentation
FSlot()
SConstraintCanvas::FSlot::FSlot () inline
Default values for a slot.
Definition at line 38 of file SConstraintCanvas.h.
References FSlot(), AlignmentAttr, AnchorsAttr, AutoSizeAttr, OffsetAttr, and ZOrder.
Referenced by FSlot(), and SLATE_SLOT_BEGIN_ARGS().
Member Function Documentation
GetAlignment()
FVector2D SConstraintCanvas::FSlot::GetAlignment () const inline
Definition at line 82 of file SConstraintCanvas.h.
References AlignmentAttr.
GetAnchors()
FAnchors SConstraintCanvas::FSlot::GetAnchors () const inline
Definition at line 72 of file SConstraintCanvas.h.
References AnchorsAttr.
GetAutoSize()
bool SConstraintCanvas::FSlot::GetAutoSize () const inline
Definition at line 92 of file SConstraintCanvas.h.
References AutoSizeAttr.
GetOffset()
FMargin SConstraintCanvas::FSlot::GetOffset () const inline
Definition at line 62 of file SConstraintCanvas.h.
References OffsetAttr.
GetZOrder()
float SConstraintCanvas::FSlot::GetZOrder () const inline
Definition at line 99 of file SConstraintCanvas.h.
References ZOrder.
SetAlignment()
void SConstraintCanvas::FSlot::SetAlignment (const TAttribute< FVector2D > & InAlignment) inline
Definition at line 77 of file SConstraintCanvas.h.
References AlignmentAttr, Layout, and FSlotBase::SetAttribute().
SetAnchors()
void SConstraintCanvas::FSlot::SetAnchors (const TAttribute< FAnchors > & InAnchors) inline
Definition at line 67 of file SConstraintCanvas.h.
References AnchorsAttr, Layout, and FSlotBase::SetAttribute().
SetAutoSize()
void SConstraintCanvas::FSlot::SetAutoSize (const TAttribute< bool > & InAutoSize) inline
Definition at line 87 of file SConstraintCanvas.h.
References AutoSizeAttr, Layout, and FSlotBase::SetAttribute().
SetOffset()
void SConstraintCanvas::FSlot::SetOffset (const TAttribute< FMargin > & InOffset) inline
Definition at line 57 of file SConstraintCanvas.h.
References Layout, OffsetAttr, FSlotBase::SetAttribute(), and SetOffset().
Referenced by SetOffset().
SetZOrder()
void SConstraintCanvas::FSlot::SetZOrder (float InZOrder)
References UE_API.
SLATE_ATTRIBUTE() [1/2]
Offset Alignment SConstraintCanvas::FSlot::SLATE_ATTRIBUTE (bool , AutoSize)
References SLATE_ARGUMENT, SLATE_ATTRIBUTE(), and ZOrder.
SLATE_ATTRIBUTE() [2/2]
Offset SConstraintCanvas::FSlot::SLATE_ATTRIBUTE (FAnchors , Anchors)
References SLATE_ATTRIBUTE().
Referenced by SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_SLOT_BEGIN_ARGS()
SConstraintCanvas::FSlot::SLATE_SLOT_BEGIN_ARGS (FSlot , TSlotBase< FSlot >)
References FSlot().
SLATE_SLOT_END_ARGS()
Offset Alignment ZOrder SConstraintCanvas::FSlot::SLATE_SLOT_END_ARGS () const &
References SLATE_SLOT_END_ARGS().
Referenced by SLATE_SLOT_END_ARGS().
Field Documentation
AlignmentAttr
TAttribute<FVector2D> SConstraintCanvas::FSlot::AlignmentAttr private
Size.
Definition at line 110 of file SConstraintCanvas.h.
Referenced by FSlot(), GetAlignment(), and SetAlignment().
AnchorsAttr
TAttribute<FAnchors> SConstraintCanvas::FSlot::AnchorsAttr private
Anchors.
Definition at line 108 of file SConstraintCanvas.h.
Referenced by FSlot(), GetAnchors(), and SetAnchors().
AutoSizeAttr
TAttribute<bool> SConstraintCanvas::FSlot::AutoSizeAttr private
Auto-Size.
Definition at line 112 of file SConstraintCanvas.h.
Referenced by FSlot(), GetAutoSize(), and SetAutoSize().
InArgs
Offset Alignment ZOrder FSlotArguments&& SConstraintCanvas::FSlot::InArgs
Definition at line 55 of file SConstraintCanvas.h.
OffsetAttr
TAttribute<FMargin> SConstraintCanvas::FSlot::OffsetAttr private
Offset.
Definition at line 106 of file SConstraintCanvas.h.
Referenced by FSlot(), GetOffset(), and SetOffset().
ZOrder
float SConstraintCanvas::FSlot::ZOrder private
Z-Order.
Definition at line 115 of file SConstraintCanvas.h.
Referenced by FSlot(), GetZOrder(), and SLATE_ATTRIBUTE().
The documentation for this class was generated from the following file:
SConstraintCanvas.h