Unreal Engine 5.6 C++ API: FWeakGraphPinPtr Struct Reference
FWeakGraphPinPtr Struct Reference
A weak reference to a UEdGraphPin object that can remain valid through pin connection state changes that might trigger owner node reconstruction.
#include "EdGraphUtilities.h"
Public Member Functions
FORCEINLINE FWeakGraphPinPtr ()
Default constructor.
FORCEINLINE FWeakGraphPinPtr (const class UEdGraphPin *Pin)
Construct from a UEdGraphPin object pointer.
FORCEINLINE FWeakGraphPinPtr (const FWeakGraphPinPtr &OtherPinPtr)
Construct from another weak pointer.
UNREALED_API class UEdGraphPin * Get ()
Method to obtain the actual object reference from the weak pointer.
FORCEINLINE bool IsValid ()
Test for validity.
FORCEINLINE operator class UEdGraphPin * ()
Cast to object pointer type.
FORCEINLINE bool operator!= (const FWeakGraphPinPtr &OtherPinPtr) const
Compare weak pointers for inequality.
FORCEINLINE class UEdGraphPin * operator-> ()
Arrow operator.
UNREALED_API void operator= (const class UEdGraphPin *Pin)
Assign from a UEdGraphPin object pointer.
FORCEINLINE void operator= (const FWeakGraphPinPtr &OtherPinPtr)
Assign from another weak pointer.
FORCEINLINE bool operator== (const FWeakGraphPinPtr &OtherPinPtr) const
Compare weak pointers for equality.
FORCEINLINE void Reset ()
Reset the weak pointer back to NULL state.
Private Attributes
TWeakObjectPtr< class UEdGraphNode > NodeObjectPtr
Weak reference to the UEdGraphNode object that owns the pin object.
FName PinName
Pin name string.
FEdGraphPinReference PinReference
Weak reference to the UEdGraphPin object.
Detailed Description
A weak reference to a UEdGraphPin object that can remain valid through pin connection state changes that might trigger owner node reconstruction.
Definition at line 202 of file EdGraphUtilities.h.
Constructor & Destructor Documentation
FWeakGraphPinPtr() [1/3]
FORCEINLINE FWeakGraphPinPtr::FWeakGraphPinPtr () inline
Default constructor.
Definition at line 205 of file EdGraphUtilities.h.
References FORCEINLINE, and Reset().
Referenced by FWeakGraphPinPtr(), operator!=(), operator=(), and operator==().
FWeakGraphPinPtr() [2/3]
FORCEINLINE FWeakGraphPinPtr::FWeakGraphPinPtr (const FWeakGraphPinPtr & OtherPinPtr) inline
Construct from another weak pointer.
Definition at line 211 of file EdGraphUtilities.h.
References FWeakGraphPinPtr(), and FORCEINLINE.
FWeakGraphPinPtr() [3/3]
FORCEINLINE FWeakGraphPinPtr::FWeakGraphPinPtr (const class UEdGraphPin * Pin) inline
Construct from a UEdGraphPin object pointer.
Definition at line 217 of file EdGraphUtilities.h.
References FORCEINLINE.
Member Function Documentation
Get()
UNREALED_API class UEdGraphPin * FWeakGraphPinPtr::Get ()
Method to obtain the actual object reference from the weak pointer.
Will attempt to fix up the pin object reference if it's no longer valid, otherwise returns NULL
Referenced by IsValid(), operator class UEdGraphPin *(), and operator->().
IsValid()
FORCEINLINE bool FWeakGraphPinPtr::IsValid () inline
Test for validity.
Definition at line 273 of file EdGraphUtilities.h.
References FORCEINLINE, and Get().
operator class UEdGraphPin *()
FORCEINLINE FWeakGraphPinPtr::operator class UEdGraphPin * () inline
Cast to object pointer type.
Definition at line 261 of file EdGraphUtilities.h.
References FORCEINLINE, and Get().
operator!=()
FORCEINLINE bool FWeakGraphPinPtr::operator!= (const FWeakGraphPinPtr & OtherPinPtr) const inline
Compare weak pointers for inequality.
Definition at line 250 of file EdGraphUtilities.h.
References FWeakGraphPinPtr(), FORCEINLINE, NodeObjectPtr, PinName, and PinReference.
operator->()
FORCEINLINE class UEdGraphPin * FWeakGraphPinPtr::operator-> () inline
Arrow operator.
Definition at line 267 of file EdGraphUtilities.h.
References FORCEINLINE, and Get().
operator=() [1/2]
UNREALED_API void FWeakGraphPinPtr::operator= (const class UEdGraphPin * Pin)
Assign from a UEdGraphPin object pointer.
operator=() [2/2]
FORCEINLINE void FWeakGraphPinPtr::operator= (const FWeakGraphPinPtr & OtherPinPtr) inline
Assign from another weak pointer.
Definition at line 231 of file EdGraphUtilities.h.
References FWeakGraphPinPtr(), FORCEINLINE, NodeObjectPtr, PinName, and PinReference.
operator==()
FORCEINLINE bool FWeakGraphPinPtr::operator== (const FWeakGraphPinPtr & OtherPinPtr) const inline
Compare weak pointers for equality.
Definition at line 242 of file EdGraphUtilities.h.
References FWeakGraphPinPtr(), FORCEINLINE, NodeObjectPtr, PinName, and PinReference.
Reset()
FORCEINLINE void FWeakGraphPinPtr::Reset () inline
Reset the weak pointer back to NULL state.
Definition at line 223 of file EdGraphUtilities.h.
References FORCEINLINE, NodeObjectPtr, PinName, PinReference, and TEXT.
Referenced by FWeakGraphPinPtr().
Field Documentation
NodeObjectPtr
TWeakObjectPtr<class UEdGraphNode> FWeakGraphPinPtr::NodeObjectPtr private
Weak reference to the UEdGraphNode object that owns the pin object.
Definition at line 286 of file EdGraphUtilities.h.
Referenced by operator!=(), operator=(), operator==(), and Reset().
PinName
FName FWeakGraphPinPtr::PinName private
Pin name string.
Definition at line 280 of file EdGraphUtilities.h.
Referenced by operator!=(), operator=(), operator==(), and Reset().
PinReference
FEdGraphPinReference FWeakGraphPinPtr::PinReference private
Weak reference to the UEdGraphPin object.
Definition at line 283 of file EdGraphUtilities.h.
Referenced by operator!=(), operator=(), operator==(), and Reset().
The documentation for this struct was generated from the following file:
EdGraphUtilities.h