Unreal Engine 5.6 C++ API: ISoundWaveLoadingBehaviorUtil Class Reference
ISoundWaveLoadingBehaviorUtil Class Reference abstract
#include "SoundWaveLoadingBehavior.h"
Data Structures
struct FClassData
Public Member Functions
virtual ~ISoundWaveLoadingBehaviorUtil ()=default
virtual FClassData FindOwningLoadingBehavior (const USoundWave *, const ITargetPlatform *) const =0
Static Public Member Functions
static ISoundWaveLoadingBehaviorUtil * Get ()
Detailed Description
Definition at line 48 of file SoundWaveLoadingBehavior.h.
Constructor & Destructor Documentation
~ISoundWaveLoadingBehaviorUtil()
virtual ISoundWaveLoadingBehaviorUtil::~ISoundWaveLoadingBehaviorUtil () virtual default
Member Function Documentation
FindOwningLoadingBehavior()
virtual FClassData ISoundWaveLoadingBehaviorUtil::FindOwningLoadingBehavior (const USoundWave * , const ITargetPlatform *) const pure virtual
Implemented in FSoundWaveLoadingBehaviorUtil.
Get()
ISoundWaveLoadingBehaviorUtil * ISoundWaveLoadingBehaviorUtil::Get () static
Definition at line 379 of file SoundWaveLoadingBehavior.cpp.
References Instance, IsRunningCookCommandlet(), and SoundWaveLoadingBehaviorUtil_Enable.
Referenced by FSoundWaveLoadingBehaviorUtil::FSoundWaveLoadingBehaviorUtil(), UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook(), and UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
The documentation for this class was generated from the following files:
SoundWaveLoadingBehavior.h
SoundWaveLoadingBehavior.cpp