Unreal Engine 5.6 C++ API: FStructOnScopeStructureDataProvider Class Reference
FStructOnScopeStructureDataProvider Class Reference
#include "IStructureDataProvider.h"
Public Member Functions
FStructOnScopeStructureDataProvider ()=default
FStructOnScopeStructureDataProvider (const TArray< TSharedPtr< FStructOnScope > > &InStructDataInstances)
FStructOnScopeStructureDataProvider (const TSharedPtr< FStructOnScope > &InStructData)
virtual const UStruct * GetBaseStructure () const override
virtual void GetInstances (TArray< TSharedPtr< FStructOnScope > > &OutInstances, const UStruct *ExpectedBaseStructure) const override
Returns instances to edit.
virtual bool IsValid () const override
void SetStructData (const TArray< TSharedPtr< FStructOnScope > > &InStructData)
void SetStructData (const TSharedPtr< FStructOnScope > &InStructData)
Public Member Functions inherited from IStructureDataProvider
virtual ~IStructureDataProvider ()
virtual uint8 * GetValueBaseAddress (uint8 *ParentValueAddress, const UStruct *ExpectedBaseStructure) const
Returns base address of provided struct based on parent property nodes value.
virtual bool IsPropertyIndirection () const
UE_DEPRECATED (5.4, "Please use and override GetInstances() with ExpectedType instead.") virtual void GetInstances(TArray< TSharedPtr< FStructOnScope > > &OutInstances) const final
Static Public Member Functions
template<typename ContainerType>
static const UStruct * FindBaseStructure (const TArray< TSharedPtr< ContainerType > > &StructDataInstances)
Protected Attributes
TArray< TSharedPtr< FStructOnScope > > StructDataInstances
Detailed Description
Definition at line 99 of file IStructureDataProvider.h.
Constructor & Destructor Documentation
FStructOnScopeStructureDataProvider() [1/3]
FStructOnScopeStructureDataProvider::FStructOnScopeStructureDataProvider () default
FStructOnScopeStructureDataProvider() [2/3]
FStructOnScopeStructureDataProvider::FStructOnScopeStructureDataProvider (const TSharedPtr< FStructOnScope > & InStructData) inline explicit
Definition at line 103 of file IStructureDataProvider.h.
References StructDataInstances.
FStructOnScopeStructureDataProvider() [3/3]
FStructOnScopeStructureDataProvider::FStructOnScopeStructureDataProvider (const TArray< TSharedPtr< FStructOnScope > > & InStructDataInstances) inline explicit
Definition at line 108 of file IStructureDataProvider.h.
References StructDataInstances.
Member Function Documentation
FindBaseStructure()
template<typename ContainerType> const UStruct * FStructOnScopeStructureDataProvider::FindBaseStructure (const TArray< TSharedPtr< ContainerType > > & StructDataInstances) inline static
Definition at line 167 of file IStructureDataProvider.h.
References Cast(), UStruct::GetSuperStruct(), IsValid(), TSharedPtr< ObjectType, InMode >::IsValid(), ScriptStruct, and StructDataInstances.
Referenced by GetBaseStructure().
GetBaseStructure()
virtual const UStruct * FStructOnScopeStructureDataProvider::GetBaseStructure () const inline override virtual
Returns
the most common struct of the instance data. This struct will be used to build the UI for the instances.
Implements IStructureDataProvider.
Definition at line 143 of file IStructureDataProvider.h.
References FindBaseStructure(), and StructDataInstances.
Referenced by IsValid().
GetInstances()
virtual void FStructOnScopeStructureDataProvider::GetInstances (TArray< TSharedPtr< FStructOnScope > > & OutInstances, const UStruct * ExpectedBaseStructure) const inline override virtual
Returns instances to edit.
Each provided struct should be compatible with ExpectedType.
Parameters
OutInstances returned instances
ExpectedBaseStructure the base type of struct that is expected to be returned (see the documentation above about ExpectedType)
Implements IStructureDataProvider.
Definition at line 148 of file IStructureDataProvider.h.
References Struct, and StructDataInstances.
IsValid()
virtual bool FStructOnScopeStructureDataProvider::IsValid () const inline override virtual
Returns
true if we have any data instances.
Implements IStructureDataProvider.
Definition at line 125 of file IStructureDataProvider.h.
References GetBaseStructure(), Struct, and StructDataInstances.
Referenced by FindBaseStructure().
SetStructData() [1/2]
void FStructOnScopeStructureDataProvider::SetStructData (const TArray< TSharedPtr< FStructOnScope > > & InStructData) inline
Definition at line 118 of file IStructureDataProvider.h.
References StructDataInstances.
SetStructData() [2/2]
void FStructOnScopeStructureDataProvider::SetStructData (const TSharedPtr< FStructOnScope > & InStructData) inline
Definition at line 113 of file IStructureDataProvider.h.
References StructDataInstances.
Field Documentation
StructDataInstances
TArray<TSharedPtr<FStructOnScope> > FStructOnScopeStructureDataProvider::StructDataInstances protected
Definition at line 210 of file IStructureDataProvider.h.
Referenced by FStructOnScopeStructureDataProvider(), FStructOnScopeStructureDataProvider(), FindBaseStructure(), GetBaseStructure(), GetInstances(), IsValid(), SetStructData(), and SetStructData().
The documentation for this class was generated from the following file:
IStructureDataProvider.h