Unreal Engine 5.6 C++ API: WorldPartitionCommandletHelpers Namespace Reference
WorldPartitionCommandletHelpers Namespace Reference
Functions
bool AddToSourceControl (const TArray< UPackage * > &PackagesToAdd, FPackageSourceControlHelper &SCHelper)
bool AddToSourceControl (UPackage *PackageToAdd, FPackageSourceControlHelper &SCHelper)
bool Checkout (const TArray< UPackage * > &PackagesToCheckout, FPackageSourceControlHelper &SCHelper)
bool Checkout (UPackage *PackagesToCheckout, FPackageSourceControlHelper &SCHelper)
template<class T>
bool CheckoutSaveAdd (T &&ToSave, FPackageSourceControlHelper &SCHelper)
UNREALED_API DECLARE_LOG_CATEGORY_EXTERN (LogWorldPartitionCommandletUtils, Log, All)
bool Delete (const TArray< UPackage * > &PackagesToDelete, FPackageSourceControlHelper &SCHelper)
bool Delete (UPackage *PackagesToDelete, FPackageSourceControlHelper &SCHelper)
ULevel * InitLevel (UWorld *World)
UWorld * LoadAndInitWorld (const FString &LevelToLoad)
UWorld * LoadWorld (const FString &LevelToLoad)
bool Save (const TArray< UPackage * > &PackagesToSave)
bool Save (UPackage *PackagesToSave)
Function Documentation
AddToSourceControl() [1/2]
bool WorldPartitionCommandletHelpers::AddToSourceControl (const TArray< UPackage * > & PackagesToAdd, FPackageSourceControlHelper & SCHelper)
Referenced by CheckoutSaveAdd().
AddToSourceControl() [2/2]
bool WorldPartitionCommandletHelpers::AddToSourceControl (UPackage * PackageToAdd, FPackageSourceControlHelper & SCHelper)
Checkout() [1/2]
bool WorldPartitionCommandletHelpers::Checkout (const TArray< UPackage * > & PackagesToCheckout, FPackageSourceControlHelper & SCHelper)
Referenced by CheckoutSaveAdd().
Checkout() [2/2]
bool WorldPartitionCommandletHelpers::Checkout (UPackage * PackagesToCheckout, FPackageSourceControlHelper & SCHelper)
CheckoutSaveAdd()
template<class T> bool WorldPartitionCommandletHelpers::CheckoutSaveAdd (T && ToSave, FPackageSourceControlHelper & SCHelper)
Definition at line 31 of file WorldPartitionCommandletHelpers.h.
References AddToSourceControl(), Checkout(), and Save.
DECLARE_LOG_CATEGORY_EXTERN()
UNREALED_API WorldPartitionCommandletHelpers::DECLARE_LOG_CATEGORY_EXTERN (LogWorldPartitionCommandletUtils , Log , All)
References All, and Log.
Delete() [1/2]
bool WorldPartitionCommandletHelpers::Delete (const TArray< UPackage * > & PackagesToDelete, FPackageSourceControlHelper & SCHelper)
Delete() [2/2]
bool WorldPartitionCommandletHelpers::Delete (UPackage * PackagesToDelete, FPackageSourceControlHelper & SCHelper)
InitLevel()
ULevel * WorldPartitionCommandletHelpers::InitLevel (UWorld * World)
LoadAndInitWorld()
UWorld * WorldPartitionCommandletHelpers::LoadAndInitWorld (const FString & LevelToLoad)
LoadWorld()
UWorld * WorldPartitionCommandletHelpers::LoadWorld (const FString & LevelToLoad)
Save() [1/2]
bool WorldPartitionCommandletHelpers::Save (const TArray< UPackage * > & PackagesToSave)
Save() [2/2]
bool WorldPartitionCommandletHelpers::Save (UPackage * PackagesToSave)