Unreal Engine 5.6 C++ API: TraitEvent.h File Reference
TraitEvent.h File Reference
#include "CoreMinimal.h"
#include "ConstExprUID.h"
#include "TraitCore/TraitEventLifetime.h"
#include "TraitEvent.generated.h"
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::AnimNext
Synchronization Role.
Macros
#define DECLARE_ANIM_TRAIT_EVENT(EventName, SuperEventName)
Typedefs
using FAnimNextTraitEventPtr = TSharedPtr<FAnimNextTraitEvent, ESPMode::ThreadSafe>
using UE::AnimNext::FTraitEventUID = UE::AnimNext::FConstExprUID
Functions
template<class EventType, typename... TArgs>
TSharedPtr< EventType, ESPMode::ThreadSafe > MakeTraitEvent (TArgs &&... Args)
USTRUCT () struct FAnimNextTraitEvent
Trait Event.
Macro Definition Documentation
DECLARE_ANIM_TRAIT_EVENT
#define DECLARE_ANIM_TRAIT_EVENT (EventName, SuperEventName)
Value:
    /* FAnimNextTraitEvent impl */ \
    static constexpr UE::AnimNext::FTraitEventUID TypeUID = UE::AnimNext::FTraitEventUID::MakeFromString(TEXT(#EventName)); \
    virtual UE::AnimNext::FTraitEventUID GetTypeUID() const override { return TypeUID; } \
    virtual bool IsA(UE::AnimNext::FTraitEventUID InTypeUID) const override { return InTypeUID == TypeUID ? true : SuperEventName::IsA(InTypeUID); } \
Definition at line 22 of file TraitEvent.h.
Typedef Documentation
FAnimNextTraitEventPtr
using FAnimNextTraitEventPtr = TSharedPtr<FAnimNextTraitEvent, ESPMode::ThreadSafe>
Definition at line 126 of file TraitEvent.h.
Function Documentation
MakeTraitEvent()
template<class EventType, typename... TArgs> TSharedPtr< EventType, ESPMode::ThreadSafe > MakeTraitEvent (TArgs &&... Args) inline
Definition at line 129 of file TraitEvent.h.
References Forward(), and MakeShared().
USTRUCT()
USTRUCT ()
Trait Event.
Encapsulates an event in the trait system. Events can be marked as handled to signal to future handlers that no further action needs to be taken. Consuming an event prevents it from propagating to other handlers.
Definition at line 36 of file TraitEvent.h.
References BlueprintType, GENERATED_BODY, UE::AnimNext::FTraitEventLifetime::IsExpired(), IsValid(), and UE::AnimNext::FTraitEventLifetime::MakeTransient().