Unreal Engine 5.6 C++ API: FVertexFactory Class Reference
FVertexFactory Class Reference
Encapsulates a vertex data source which can be linked into a vertex shader.
#include "VertexFactory.h"
Data Structures
struct FVertexStream
Information needed to set a vertex stream.
Public Member Functions
FVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
virtual RENDERCORE_API ~FVertexFactory ()
FVertexDeclarationRHIRef & GetDeclaration ()
const FVertexDeclarationRHIRef & GetDeclaration (EVertexInputStreamType InputStreamType) const
int32 GetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) const
RENDERCORE_API void GetStreams (ERHIFeatureLevel::Type InFeatureLevel, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &OutVertexStreams) const
virtual FShaderResourceViewRHIRef GetTriangleSortingPositionSRV () const
virtual FVertexFactoryType * GetType () const
bool NeedsDeclaration () const
RENDERCORE_API void OffsetInstanceStreams (uint32 InstanceOffset, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &VertexStreams) const
virtual RENDERCORE_API void ReleaseRHI ()
Releases the RHI resources used by this resource.
virtual bool RendersPrimitivesAsCameraFacingSprites () const
void SetDeclaration (FVertexDeclarationRHIRef &NewDeclaration)
bool SupportsGPUScene (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsManualVertexFetch (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsNullPixelShader () const
Indicates whether the vertex factory supports a null pixel shader.
virtual bool SupportsPositionAndNormalOnlyStream () const
Indicates whether the vertex factory supports a position-and-normal-only stream.
virtual bool SupportsPositionOnlyStream () const
Indicates whether the vertex factory supports a position-only stream.
bool SupportsTriangleSorting () const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Can be overridden by FVertexFactory subclasses which have EVertexFactoryFlags::SupportsPSOPrecaching set - this function will only be called when that flag is set.
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Can be overridden by FVertexFactory subclasses to modify their compile environment just before compilation occurs.
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Can be overridden by FVertexFactory subclasses to fail a compile based on compilation output.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Types
typedef TArray< FVertexStream, TInlineAllocator< 8 > > FVertexStreamList
Protected Member Functions
FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex)
Creates a vertex element for a vertex stream components.
RENDERCORE_API FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, EVertexInputStreamType InputStreamType)
Creates a vertex element for a vertex stream component.
RENDERCORE_API bool AddPrimitiveIdStreamElement (EVertexInputStreamType InputStreamType, FVertexDeclarationElementList &Elements, uint8 AttributeIndex, uint8 AttributeIndex_Mobile)
RENDERCORE_API void InitDeclaration (const FVertexDeclarationElementList &Elements, EVertexInputStreamType StreamType=EVertexInputStreamType::Default)
Initializes the vertex declaration.
void SetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType, int32 StreamIndex)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions
template<typename VertexStreamListType>
static FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, VertexStreamListType &InOutStreams)
Creates a vertex element for a vertex stream components.
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes
bool bNeedsDeclaration = true
FVertexStreamList Streams
The vertex streams used to render the factory.
Static Private Member Functions
static int32 TranslatePrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType)
Private Attributes
FVertexDeclarationRHIRef Declaration
The RHI vertex declaration used to render the factory normally.
FVertexDeclarationRHIRef PositionAndNormalDeclaration
TArray< FVertexStream, TInlineAllocator< 3 > > PositionAndNormalStream
FVertexDeclarationRHIRef PositionDeclaration
The RHI vertex declaration used to render the factory during depth only passes.
TArray< FVertexStream, TInlineAllocator< 2 > > PositionStream
The position only vertex stream used to render the factory during depth only passes.
int8 PrimitiveIdStreamIndex [(int32) EVertexInputStreamType::Count *2]
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Detailed Description
Encapsulates a vertex data source which can be linked into a vertex shader.
Definition at line 660 of file VertexFactory.h.
Member Typedef Documentation
FVertexStreamList
typedef TArray<FVertexStream, TInlineAllocator<8> > FVertexFactory::FVertexStreamList protected
Definition at line 834 of file VertexFactory.h.
Constructor & Destructor Documentation
FVertexFactory()
FVertexFactory::FVertexFactory (ERHIFeatureLevel::Type InFeatureLevel) inline
Definition at line 663 of file VertexFactory.h.
References FRenderResource::FRenderResource(), INDEX_NONE, PrimitiveIdStreamIndex, and UE_ARRAY_COUNT.
Referenced by FGeometryCacheVertexVertexFactory::FGeometryCacheVertexVertexFactory(), FGeometryCollectionVertexFactory::FGeometryCollectionVertexFactory(), FHairStrandsVertexFactory::FHairStrandsVertexFactory(), FParticleVertexFactoryBase::FParticleVertexFactoryBase(), and FParticleVertexFactoryBase::FParticleVertexFactoryBase().
~FVertexFactory()
virtual RENDERCORE_API FVertexFactory::~FVertexFactory () virtual
Member Function Documentation
AccessStreamComponent() [1/3]
FVertexElement FVertexFactory::AccessStreamComponent (const FVertexStreamComponent & Component, uint8 AttributeIndex) inline protected
Creates a vertex element for a vertex stream components.
Adds a unique stream index for the vertex buffer used by the component.
Parameters
Component - The vertex stream component.
AttributeIndex - The attribute index to which the stream component is bound.
Returns
The vertex element which corresponds to Component.
Definition at line 774 of file VertexFactory.h.
References AccessStreamComponent(), Component, and Streams.
Referenced by AccessStreamComponent().
AccessStreamComponent() [2/3]
RENDERCORE_API FVertexElement FVertexFactory::AccessStreamComponent (const FVertexStreamComponent & Component, uint8 AttributeIndex, EVertexInputStreamType InputStreamType) protected
Creates a vertex element for a vertex stream component.
Adds a unique position stream index for the vertex buffer used by the component.
Parameters
Component - The vertex stream component.
Usage - The vertex element usage semantics.
AttributeIndex - The attribute index to which the stream component is bound.
Returns
The vertex element which corresponds to Component.
References Component.
AccessStreamComponent() [3/3]
template<typename VertexStreamListType> FVertexElement FVertexFactory::AccessStreamComponent (const FVertexStreamComponent & Component, uint8 AttributeIndex, VertexStreamListType & InOutStreams) inline static protected
Creates a vertex element for a vertex stream components.
Adds a unique stream index for the vertex buffer used by the component.
Parameters
Component - The vertex stream component.
AttributeIndex - The attribute index to which the stream component is bound.
AttributeIndex - Stream array where to add the new streams.
Returns
The vertex element which corresponds to Component.
Definition at line 796 of file VertexFactory.h.
References Component, EnumHasAnyFlags(), Instancing, FVertexFactory::FVertexStream::Offset, FVertexFactory::FVertexStream::Stride, FVertexFactory::FVertexStream::VertexBuffer, and FVertexFactory::FVertexStream::VertexStreamUsage.
AddPrimitiveIdStreamElement()
RENDERCORE_API bool FVertexFactory::AddPrimitiveIdStreamElement (EVertexInputStreamType InputStreamType, FVertexDeclarationElementList & Elements, uint8 AttributeIndex, uint8 AttributeIndex_Mobile) protected
GetDeclaration() [1/2]
FVertexDeclarationRHIRef & FVertexFactory::GetDeclaration () inline
Definition at line 699 of file VertexFactory.h.
References Declaration.
GetDeclaration() [2/2]
const FVertexDeclarationRHIRef & FVertexFactory::GetDeclaration (EVertexInputStreamType InputStreamType) const inline
Definition at line 702 of file VertexFactory.h.
References Declaration, Default, PositionAndNormalDeclaration, PositionAndNormalOnly, PositionDeclaration, and PositionOnly.
GetPrimitiveIdStreamIndex()
int32 FVertexFactory::GetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) const inline
Definition at line 749 of file VertexFactory.h.
References PrimitiveIdStreamIndex, and TranslatePrimitiveIdStreamIndex().
Referenced by SupportsGPUScene().
GetPSOPrecacheVertexFetchElements()
void FVertexFactory::GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList & Elements) inline static
Can be overridden by FVertexFactory subclasses which have EVertexFactoryFlags::SupportsPSOPrecaching set - this function will only be called when that flag is set.
Definition at line 693 of file VertexFactory.h.
References checkNoEntry.
GetStreams()
RENDERCORE_API void FVertexFactory::GetStreams (ERHIFeatureLevel::Type InFeatureLevel, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray & OutVertexStreams) const
GetTriangleSortingPositionSRV()
virtual FShaderResourceViewRHIRef FVertexFactory::GetTriangleSortingPositionSRV () const inline virtual
Reimplemented in FGPUBaseSkinVertexFactory, and FLocalVertexFactory.
Definition at line 731 of file VertexFactory.h.
GetType()
virtual FVertexFactoryType * FVertexFactory::GetType () const inline virtual
Reimplemented in FGeometryCacheVertexVertexFactory, FGeometryCollectionVertexFactory, FNaniteVertexFactory, FSplineMeshVertexFactory, TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >, and TGPUSkinVertexFactory< BoneInfluenceType >.
Definition at line 674 of file VertexFactory.h.
Referenced by SupportsGPUScene(), SupportsManualVertexFetch(), SupportsNullPixelShader(), and SupportsTriangleSorting().
InitDeclaration()
RENDERCORE_API void FVertexFactory::InitDeclaration (const FVertexDeclarationElementList & Elements, EVertexInputStreamType StreamType = EVertexInputStreamType::Default) protected
Initializes the vertex declaration.
Parameters
Elements - The elements of the vertex declaration.
References Default.
ModifyCompilationEnvironment()
void FVertexFactory::ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) inline static
Can be overridden by FVertexFactory subclasses to modify their compile environment just before compilation occurs.
Definition at line 683 of file VertexFactory.h.
Referenced by FParticleVertexFactoryBase::ModifyCompilationEnvironment().
NeedsDeclaration()
bool FVertexFactory::NeedsDeclaration () const inline
Definition at line 742 of file VertexFactory.h.
References bNeedsDeclaration.
OffsetInstanceStreams()
RENDERCORE_API void FVertexFactory::OffsetInstanceStreams (uint32 InstanceOffset, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray & VertexStreams) const
ReleaseRHI()
virtual RENDERCORE_API void FVertexFactory::ReleaseRHI () virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
Reimplemented in FGeometryCollectionVertexFactory, FGPUBaseSkinVertexFactory, FGPUSkinPassthroughVertexFactory, FHairCardsVertexFactory, FHairStrandsVertexFactory, FLocalVertexFactory, TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >, TGPUSkinVertexFactory< BoneInfluenceType >, TWaterVertexFactory< bWithWaterSelectionSupport, DrawMode >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::Indirect >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::IndirectInstancedStereo >, and TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::NonIndirect >.
Referenced by FLocalVertexFactory::ReleaseRHI().
RendersPrimitivesAsCameraFacingSprites()
virtual bool FVertexFactory::RendersPrimitivesAsCameraFacingSprites () const inline virtual
Reimplemented in FParticleSpriteVertexFactory.
Definition at line 740 of file VertexFactory.h.
SetDeclaration()
void FVertexFactory::SetDeclaration (FVertexDeclarationRHIRef & NewDeclaration) inline
Definition at line 700 of file VertexFactory.h.
References Declaration.
SetPrimitiveIdStreamIndex()
void FVertexFactory::SetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType, int32 StreamIndex) inline protected
Definition at line 760 of file VertexFactory.h.
References check, PrimitiveIdStreamIndex, and TranslatePrimitiveIdStreamIndex().
SupportsGPUScene()
bool FVertexFactory::SupportsGPUScene (const FStaticFeatureLevel InFeatureLevel) const inline
Definition at line 754 of file VertexFactory.h.
References Default, GetPrimitiveIdStreamIndex(), GetType(), INDEX_NONE, and FVertexFactoryType::SupportsPrimitiveIdStream().
SupportsManualVertexFetch()
bool FVertexFactory::SupportsManualVertexFetch (const FStaticFeatureLevel InFeatureLevel) const inline
Definition at line 744 of file VertexFactory.h.
References GetType(), and FVertexFactoryType::SupportsManualVertexFetch().
SupportsNullPixelShader()
bool FVertexFactory::SupportsNullPixelShader () const inline
Indicates whether the vertex factory supports a null pixel shader.
Definition at line 721 of file VertexFactory.h.
References GetType(), and FVertexFactoryType::SupportsNullPixelShader().
SupportsPositionAndNormalOnlyStream()
virtual bool FVertexFactory::SupportsPositionAndNormalOnlyStream () const inline virtual
Indicates whether the vertex factory supports a position-and-normal-only stream.
Reimplemented in FGPUSkinPassthroughVertexFactory.
Definition at line 718 of file VertexFactory.h.
References PositionAndNormalStream.
SupportsPositionOnlyStream()
virtual bool FVertexFactory::SupportsPositionOnlyStream () const inline virtual
Indicates whether the vertex factory supports a position-only stream.
Reimplemented in FGPUSkinPassthroughVertexFactory.
Definition at line 715 of file VertexFactory.h.
References PositionStream.
SupportsTriangleSorting()
bool FVertexFactory::SupportsTriangleSorting () const inline
Definition at line 726 of file VertexFactory.h.
References GetType(), and FVertexFactoryType::SupportsTriangleSorting().
TranslatePrimitiveIdStreamIndex()
int32 FVertexFactory::TranslatePrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) inline static private
Definition at line 864 of file VertexFactory.h.
References Count.
Referenced by GetPrimitiveIdStreamIndex(), and SetPrimitiveIdStreamIndex().
ValidateCompiledResult()
void FVertexFactory::ValidateCompiledResult (const FVertexFactoryType * Type, EShaderPlatform Platform, const FShaderParameterMap & ParameterMap, TArray< FString > & OutErrors) inline static
Can be overridden by FVertexFactory subclasses to fail a compile based on compilation output.
Definition at line 688 of file VertexFactory.h.
References Platform.
Field Documentation
bNeedsDeclaration
bool FVertexFactory::bNeedsDeclaration = true protected
Definition at line 861 of file VertexFactory.h.
Referenced by NeedsDeclaration().
Declaration
FVertexDeclarationRHIRef FVertexFactory::Declaration private
The RHI vertex declaration used to render the factory normally.
Definition at line 846 of file VertexFactory.h.
Referenced by GetDeclaration(), GetDeclaration(), and SetDeclaration().
PositionAndNormalDeclaration
FVertexDeclarationRHIRef FVertexFactory::PositionAndNormalDeclaration private
Definition at line 850 of file VertexFactory.h.
Referenced by GetDeclaration().
PositionAndNormalStream
TArray<FVertexStream, TInlineAllocator<3> > FVertexFactory::PositionAndNormalStream private
Definition at line 843 of file VertexFactory.h.
Referenced by SupportsPositionAndNormalOnlyStream().
PositionDeclaration
FVertexDeclarationRHIRef FVertexFactory::PositionDeclaration private
The RHI vertex declaration used to render the factory during depth only passes.
Definition at line 849 of file VertexFactory.h.
Referenced by GetDeclaration().
PositionStream
TArray<FVertexStream,TInlineAllocator<2> > FVertexFactory::PositionStream private
The position only vertex stream used to render the factory during depth only passes.
Definition at line 842 of file VertexFactory.h.
Referenced by SupportsPositionOnlyStream().
PrimitiveIdStreamIndex
int8 FVertexFactory::PrimitiveIdStreamIndex[(int32) EVertexInputStreamType::Count *2] private
Definition at line 854 of file VertexFactory.h.
Referenced by FVertexFactory(), GetPrimitiveIdStreamIndex(), and SetPrimitiveIdStreamIndex().
Streams
FVertexStreamList FVertexFactory::Streams protected
The vertex streams used to render the factory.
Definition at line 837 of file VertexFactory.h.
Referenced by AccessStreamComponent(), and FInstancedStaticMeshVertexFactory::GetVertexElements().
The documentation for this class was generated from the following file:
VertexFactory.h