Unreal Engine 5.6 C++ API: TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason > Class Template Reference
TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason > Class Template Reference
Mixin to add the padding functionality to a base slot that is also a single children.
#include "BasicLayoutWidgetSlot.h"
Data Structures
struct FSlotArgumentsMixin
Public Types
using SlotPaddingAttributeRefType = SlateAttributePrivate::TSlateMemberAttributeRef<SlotPaddingAttributeType>
using SlotPaddingAttributeType = SlateAttributePrivate::TSlateMemberAttribute<FMargin, SlotPaddingInvalidationType, TSlateAttributeComparePredicate<>>
using SlotPaddingInvalidationType = typename std::conditional<InPaddingInvalidationReason == EInvalidateWidgetReason::None, ::SlateAttributePrivate::FSlateAttributeNoInvalidationReason, TSlateAttributeInvalidationReason<InPaddingInvalidationReason>>::type
Public Member Functions
template<typename WidgetType, typename V = typename std::enable_if<std::is_base_of<SWidget, WidgetType>::value>::type>
TPaddingSingleWidgetSlotMixin (WidgetType &InParent)
template<typename WidgetType, typename V = typename std::enable_if<std::is_base_of<SWidget, WidgetType>::value>::type>
TPaddingSingleWidgetSlotMixin (WidgetType &InParent, const FMargin &Margin)
FMargin GetPadding () const
template<typename WidgetType, typename V = typename std::enable_if<std::is_base_of<SWidget, WidgetType>::value>::type>
SlotPaddingAttributeRefType GetSlotPaddingAttribute () const
MixedIntoType & Padding (float Horizontal, float Vertical)
MixedIntoType & Padding (float Left, float Top, float Right, float Bottom)
MixedIntoType & Padding (float Uniform)
MixedIntoType & Padding (TAttribute< FMargin > InPadding)
void SetPadding (TAttribute< FMargin > InPadding)
Protected Member Functions
void ConstructMixin (FSlotArgumentsMixin &&InArgs)
Protected Attributes
SlotPaddingAttributeType SlotPaddingAttribute
Detailed Description
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout>
class TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >
Mixin to add the padding functionality to a base slot that is also a single children.
Definition at line 278 of file BasicLayoutWidgetSlot.h.
Member Typedef Documentation
SlotPaddingAttributeRefType
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> using TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::SlotPaddingAttributeRefType = SlateAttributePrivate::TSlateMemberAttributeRef<SlotPaddingAttributeType>
Definition at line 380 of file BasicLayoutWidgetSlot.h.
SlotPaddingAttributeType
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> using TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::SlotPaddingAttributeType = SlateAttributePrivate::TSlateMemberAttribute<FMargin, SlotPaddingInvalidationType, TSlateAttributeComparePredicate<>>
Definition at line 379 of file BasicLayoutWidgetSlot.h.
SlotPaddingInvalidationType
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> using TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::SlotPaddingInvalidationType = typename std::conditional<InPaddingInvalidationReason == EInvalidateWidgetReason::None, ::SlateAttributePrivate::FSlateAttributeNoInvalidationReason, TSlateAttributeInvalidationReason<InPaddingInvalidationReason>>::type
Definition at line 378 of file BasicLayoutWidgetSlot.h.
Constructor & Destructor Documentation
TPaddingSingleWidgetSlotMixin() [1/2]
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> template<typename WidgetType, typename V = typename std::enable_if<std::is_base_of<SWidget, WidgetType>::value>::type> TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::TPaddingSingleWidgetSlotMixin (WidgetType & InParent) inline
Definition at line 282 of file BasicLayoutWidgetSlot.h.
TPaddingSingleWidgetSlotMixin() [2/2]
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> template<typename WidgetType, typename V = typename std::enable_if<std::is_base_of<SWidget, WidgetType>::value>::type> TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::TPaddingSingleWidgetSlotMixin (WidgetType & InParent, const FMargin & Margin) inline
Definition at line 287 of file BasicLayoutWidgetSlot.h.
Member Function Documentation
ConstructMixin()
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> void TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::ConstructMixin (FSlotArgumentsMixin && InArgs) inline protected
Definition at line 325 of file BasicLayoutWidgetSlot.h.
GetPadding()
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> FMargin TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::GetPadding () const inline
Definition at line 372 of file BasicLayoutWidgetSlot.h.
GetSlotPaddingAttribute()
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> template<typename WidgetType, typename V = typename std::enable_if<std::is_base_of<SWidget, WidgetType>::value>::type> SlotPaddingAttributeRefType TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::GetSlotPaddingAttribute () const inline
Definition at line 383 of file BasicLayoutWidgetSlot.h.
Padding() [1/4]
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> MixedIntoType & TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::Padding (float Horizontal, float Vertical) inline
Definition at line 351 of file BasicLayoutWidgetSlot.h.
Padding() [2/4]
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> MixedIntoType & TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::Padding (float Left, float Top, float Right, float Bottom) inline
Definition at line 358 of file BasicLayoutWidgetSlot.h.
Padding() [3/4]
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> MixedIntoType & TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::Padding (float Uniform) inline
Definition at line 344 of file BasicLayoutWidgetSlot.h.
Padding() [4/4]
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> MixedIntoType & TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::Padding (TAttribute< FMargin > InPadding) inline
Definition at line 337 of file BasicLayoutWidgetSlot.h.
SetPadding()
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> void TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::SetPadding (TAttribute< FMargin > InPadding) inline
Definition at line 365 of file BasicLayoutWidgetSlot.h.
Referenced by TPaddingSingleWidgetSlotMixin< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >, InPaddingInvalidationReason >::Padding(), TPaddingSingleWidgetSlotMixin< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >, InPaddingInvalidationReason >::Padding(), TPaddingSingleWidgetSlotMixin< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >, InPaddingInvalidationReason >::Padding(), and TPaddingSingleWidgetSlotMixin< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason >, InPaddingInvalidationReason >::Padding().
Field Documentation
SlotPaddingAttribute
template<typename MixedIntoType, EInvalidateWidgetReason InPaddingInvalidationReason = EInvalidateWidgetReason::Layout> SlotPaddingAttributeType TPaddingSingleWidgetSlotMixin< MixedIntoType, InPaddingInvalidationReason >::SlotPaddingAttribute protected
Definition at line 391 of file BasicLayoutWidgetSlot.h.
The documentation for this class was generated from the following file:
BasicLayoutWidgetSlot.h