Unreal Engine 5.6 C++ API: TraceServices::IDefinitionProvider Class Reference
TraceServices::IDefinitionProvider Class Reference abstract
Allows users to publish "definitions", structs representing a definition event.
#include "Definitions.h"
Public Member Functions
virtual ~IDefinitionProvider ()=default
template<typename T>
T * Create ()
Allocates memory for the definition.
template<typename T, typename DefinitionType>
const T * Get (const UE::Trace::TEventRef< DefinitionType > &Reference) const
Attempts to retrieve a previously registered instance of a definition using a reference.
template<typename DefinitionType>
FString GetAsString (const UE::Trace::TEventRef< DefinitionType > &Reference) const
Gets the definition as a owned string.
template<typename T, typename DefinitionType>
void Register (const T *Instance, const UE::Trace::TEventRef< DefinitionType > &Id)
Makes the instance of a definition visible to queries.
Public Member Functions inherited from TraceServices::IProvider
virtual ~IProvider ()=default
virtual void BeginRead () const
virtual void EndRead () const
virtual void ReadAccessCheck () const
Public Member Functions inherited from TraceServices::IEditableProvider
virtual ~IEditableProvider ()=default
virtual void BeginEdit () const
virtual void EditAccessCheck () const
virtual void EndEdit () const
Protected Types
using StringifierFn = TFunction<FString (const void*)>
Protected Member Functions
virtual void AddEntry (uint64 Hash, const void *Ptr)=0
virtual void * Allocate (uint32 Size, uint32 Alignment)=0
virtual const void * FindEntry (uint64 Hash) const =0
Protected Attributes
TMap< uint32, StringifierFn > Stringifiers
Detailed Description
Allows users to publish "definitions", structs representing a definition event.
This data can then be queried when resolving a reference field in another event.
Note
If your definition type reference other definitions it is encouraged to resolve those during analysis to avoid having to resolve complex chains on every lookup.
Example usage: This code creates a definition, initializes the instance, resolves a reference and finally registers it.
FMyDefinitionClass* Instance = DefinitionProvider->Create<FMyDefinitionClass>();
Instance->SomeValue = EventData.GetValue<uint32>("SomeValue");
const FEventRef Reference = EventData.GetReferenceValue("SomeString");
Instance->SomeString = DefinitionProvider->Get<FStringDefinition>(Reference)->Display;
...
const UE::Trace::FEventRef Id(EventData.GetDefinitionId(), EventData.GetTypeInfo().GetId());
DefinitionProvider->Register<FMyDefinitionClass>(Instance, Id);
Definition at line 35 of file Definitions.h.
Member Typedef Documentation
StringifierFn
using TraceServices::IDefinitionProvider::StringifierFn = TFunction<FString (const void*)> protected
Definition at line 109 of file Definitions.h.
Constructor & Destructor Documentation
~IDefinitionProvider()
virtual TraceServices::IDefinitionProvider::~IDefinitionProvider () virtual default
Member Function Documentation
AddEntry()
virtual void TraceServices::IDefinitionProvider::AddEntry (uint64 Hash, const void * Ptr) protected pure virtual
References Hash.
Referenced by Register().
Allocate()
virtual void * TraceServices::IDefinitionProvider::Allocate (uint32 Size, uint32 Alignment) protected pure virtual
References TSequenceHistory< HistorySize >::Size.
Referenced by Create().
Create()
template<typename T> T * TraceServices::IDefinitionProvider::Create () inline
Allocates memory for the definition.
The memory is guaranteed to be valid during the lifetime of the analysis session.
Returns
Pointer to zeroed memory enough to hold an instance of T.
Definition at line 51 of file Definitions.h.
References Allocate(), and TSequenceHistory< HistorySize >::Size.
FindEntry()
virtual const void * TraceServices::IDefinitionProvider::FindEntry (uint64 Hash) const protected pure virtual
References Hash.
Referenced by Get(), and GetAsString().
Get()
template<typename T, typename DefinitionType> const T * TraceServices::IDefinitionProvider::Get (const UE::Trace::TEventRef< DefinitionType > & Reference) const inline
Attempts to retrieve a previously registered instance of a definition using a reference.
Parameters
Reference Id used to uniquely identify the definition.
Returns
Pointer to the definition or null if the id was not found.
Definition at line 80 of file Definitions.h.
References FindEntry(), and Value.
GetAsString()
template<typename DefinitionType> FString TraceServices::IDefinitionProvider::GetAsString (const UE::Trace::TEventRef< DefinitionType > & Reference) const inline
Gets the definition as a owned string.
Parameters
Reference Id used to uniquely identify the definition.
Returns
A string describing the referenced value
Definition at line 92 of file Definitions.h.
References FindEntry(), and Stringifiers.
Register()
template<typename T, typename DefinitionType> void TraceServices::IDefinitionProvider::Register (const T * Instance, const UE::Trace::TEventRef< DefinitionType > & Id) inline
Makes the instance of a definition visible to queries.
Parameters
Instance Pointer to the instance
Id Id that should be used to reference the definition.
Definition at line 65 of file Definitions.h.
References AddEntry(), Instance, and Stringifiers.
Field Documentation
Stringifiers
TMap<uint32, StringifierFn> TraceServices::IDefinitionProvider::Stringifiers protected
Definition at line 110 of file Definitions.h.
Referenced by GetAsString(), and Register().
The documentation for this class was generated from the following file:
Definitions.h