Unreal Engine 5.6 C++ API: FAutoConsoleTaskPriority Class Reference
FAutoConsoleTaskPriority Class Reference
#include "TaskGraphInterfaces.h"
Public Member Functions
FAutoConsoleTaskPriority (const TCHAR *Name, const TCHAR *Help, ENamedThreads::Type DefaultThreadPriority, ENamedThreads::Type DefaultTaskPriority, ENamedThreads::Type DefaultTaskPriorityIfForcedToNormalThreadPriority=ENamedThreads::UnusedAnchor)
FORCEINLINE ENamedThreads::Type Get (ENamedThreads::Type Thread=ENamedThreads::AnyThread)
Private Member Functions
void OnSettingChanged (IConsoleVariable *Variable)
Static Private Member Functions
static FString ConfigStringFromPriorities (ENamedThreads::Type InThreadPriority, ENamedThreads::Type InTaskPriority, ENamedThreads::Type InTaskPriorityBackup)
static FString CreateFullHelpText (const TCHAR *Name, const TCHAR *OriginalHelp)
Private Attributes
FString FullHelpText
FString RawSetting
ENamedThreads::Type TaskPriority
ENamedThreads::Type TaskPriorityIfForcedToNormalThreadPriority
ENamedThreads::Type ThreadPriority
FAutoConsoleVariableRef Variable
Detailed Description
Definition at line 212 of file TaskGraphInterfaces.h.
Constructor & Destructor Documentation
FAutoConsoleTaskPriority()
FAutoConsoleTaskPriority::FAutoConsoleTaskPriority (const TCHAR * Name, const TCHAR * Help, ENamedThreads::Type DefaultThreadPriority, ENamedThreads::Type DefaultTaskPriority, ENamedThreads::Type DefaultTaskPriorityIfForcedToNormalThreadPriority = ENamedThreads::UnusedAnchor) inline
Definition at line 226 of file TaskGraphInterfaces.h.
References FAutoConsoleTaskPriority(), check, ConfigStringFromPriorities(), CreateFullHelpText(), ECVF_Default, FullHelpText, Name, ENamedThreads::NormalThreadPriority, OnSettingChanged(), RawSetting, TaskPriority, TaskPriorityIfForcedToNormalThreadPriority, ThreadPriority, ENamedThreads::UnusedAnchor, and Variable.
Referenced by FAutoConsoleTaskPriority().
Member Function Documentation
ConfigStringFromPriorities()
FString FAutoConsoleTaskPriority::ConfigStringFromPriorities (ENamedThreads::Type InThreadPriority, ENamedThreads::Type InTaskPriority, ENamedThreads::Type InTaskPriorityBackup) static private
Referenced by FAutoConsoleTaskPriority().
CreateFullHelpText()
FString FAutoConsoleTaskPriority::CreateFullHelpText (const TCHAR * Name, const TCHAR * OriginalHelp) static private
References Name.
Referenced by FAutoConsoleTaskPriority().
Get()
FORCEINLINE ENamedThreads::Type FAutoConsoleTaskPriority::Get (ENamedThreads::Type Thread = ENamedThreads::AnyThread) inline
Definition at line 238 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, ENamedThreads::BackgroundThreadPriority, ENamedThreads::bHasBackgroundThreads, ENamedThreads::bHasHighPriorityThreads, FORCEINLINE, ENamedThreads::HighThreadPriority, ENamedThreads::SetPriorities(), ENamedThreads::SetTaskPriority(), TaskPriority, TaskPriorityIfForcedToNormalThreadPriority, Thread, and ThreadPriority.
OnSettingChanged()
void FAutoConsoleTaskPriority::OnSettingChanged (IConsoleVariable * Variable) private
References Variable.
Referenced by FAutoConsoleTaskPriority().
Field Documentation
FullHelpText
FString FAutoConsoleTaskPriority::FullHelpText private
Definition at line 215 of file TaskGraphInterfaces.h.
Referenced by FAutoConsoleTaskPriority().
RawSetting
FString FAutoConsoleTaskPriority::RawSetting private
Definition at line 214 of file TaskGraphInterfaces.h.
Referenced by FAutoConsoleTaskPriority().
TaskPriority
ENamedThreads::Type FAutoConsoleTaskPriority::TaskPriority private
Definition at line 218 of file TaskGraphInterfaces.h.
Referenced by FAutoConsoleTaskPriority(), and Get().
TaskPriorityIfForcedToNormalThreadPriority
ENamedThreads::Type FAutoConsoleTaskPriority::TaskPriorityIfForcedToNormalThreadPriority private
Definition at line 219 of file TaskGraphInterfaces.h.
Referenced by FAutoConsoleTaskPriority(), and Get().
ThreadPriority
ENamedThreads::Type FAutoConsoleTaskPriority::ThreadPriority private
Definition at line 217 of file TaskGraphInterfaces.h.
Referenced by FAutoConsoleTaskPriority(), and Get().
Variable
FAutoConsoleVariableRef FAutoConsoleTaskPriority::Variable private
Definition at line 216 of file TaskGraphInterfaces.h.
Referenced by FAutoConsoleTaskPriority(), and OnSettingChanged().
The documentation for this class was generated from the following file:
TaskGraphInterfaces.h