Unreal Engine 5.6 C++ API: FCachedSystemScalabilityCVars Struct Reference
FCachedSystemScalabilityCVars Struct Reference
Cache some of the scalability CVars to avoid some virtual function calls (no longer the case with the new console variable system, but we only have 1 render thread) and to detect changes and act accordingly if needed.
#include "UnrealEngine.h"
Public Member Functions
FCachedSystemScalabilityCVars ()
float CalculateFieldOfViewDistanceScale (const float FieldOfView) const
bool operator== (const FCachedSystemScalabilityCVars &Other) const
Data Fields
bool bInitialized
int32 CookOutUnusedDetailModeComponents
int32 DetailMode
int32 FieldOfViewAffectsHLOD
EMaterialQualityLevel::Type MaterialQualityLevel
int32 MaxCSMShadowResolution
int32 MaxShadowResolution
float SkeletalMeshOverlayDistanceScale
float StaticMeshLODDistanceScale
float ViewDistanceScale
float ViewDistanceScaleSquared
Protected Attributes
float FieldOfViewMaxAngle
float FieldOfViewMaxAngleScale
float FieldOfViewMinAngle
float FieldOfViewMinAngleScale
int32 MaxAnisotropy
Friends
void ScalabilityCVarsSinkCallback ()
Detailed Description
Cache some of the scalability CVars to avoid some virtual function calls (no longer the case with the new console variable system, but we only have 1 render thread) and to detect changes and act accordingly if needed.
read by rendering thread[s], written by main thread, uses FlushRenderingCommands() to avoid conflict
Definition at line 400 of file UnrealEngine.h.
Constructor & Destructor Documentation
FCachedSystemScalabilityCVars()
FCachedSystemScalabilityCVars::FCachedSystemScalabilityCVars ()
Referenced by operator==().
Member Function Documentation
CalculateFieldOfViewDistanceScale()
float FCachedSystemScalabilityCVars::CalculateFieldOfViewDistanceScale (const float FieldOfView) const inline
Definition at line 414 of file UnrealEngine.h.
References FMath::Clamp(), FieldOfViewMaxAngle, FieldOfViewMaxAngleScale, FieldOfViewMinAngle, FieldOfViewMinAngleScale, FMath::IsNearlyEqual(), and FMath::Lerp().
operator==()
bool FCachedSystemScalabilityCVars::operator== (const FCachedSystemScalabilityCVars & Other) const
References FCachedSystemScalabilityCVars(), and Other.
Friends And Related Symbol Documentation
ScalabilityCVarsSinkCallback
void ScalabilityCVarsSinkCallback () friend
Field Documentation
bInitialized
bool FCachedSystemScalabilityCVars::bInitialized
Definition at line 402 of file UnrealEngine.h.
CookOutUnusedDetailModeComponents
int32 FCachedSystemScalabilityCVars::CookOutUnusedDetailModeComponents
Definition at line 404 of file UnrealEngine.h.
DetailMode
int32 FCachedSystemScalabilityCVars::DetailMode
Definition at line 403 of file UnrealEngine.h.
FieldOfViewAffectsHLOD
int32 FCachedSystemScalabilityCVars::FieldOfViewAffectsHLOD
Definition at line 410 of file UnrealEngine.h.
FieldOfViewMaxAngle
float FCachedSystemScalabilityCVars::FieldOfViewMaxAngle protected
Definition at line 437 of file UnrealEngine.h.
Referenced by CalculateFieldOfViewDistanceScale().
FieldOfViewMaxAngleScale
float FCachedSystemScalabilityCVars::FieldOfViewMaxAngleScale protected
Definition at line 438 of file UnrealEngine.h.
Referenced by CalculateFieldOfViewDistanceScale().
FieldOfViewMinAngle
float FCachedSystemScalabilityCVars::FieldOfViewMinAngle protected
Definition at line 435 of file UnrealEngine.h.
Referenced by CalculateFieldOfViewDistanceScale().
FieldOfViewMinAngleScale
float FCachedSystemScalabilityCVars::FieldOfViewMinAngleScale protected
Definition at line 436 of file UnrealEngine.h.
Referenced by CalculateFieldOfViewDistanceScale().
MaterialQualityLevel
EMaterialQualityLevel::Type FCachedSystemScalabilityCVars::MaterialQualityLevel
Definition at line 405 of file UnrealEngine.h.
MaxAnisotropy
int32 FCachedSystemScalabilityCVars::MaxAnisotropy protected
Definition at line 432 of file UnrealEngine.h.
MaxCSMShadowResolution
int32 FCachedSystemScalabilityCVars::MaxCSMShadowResolution
Definition at line 407 of file UnrealEngine.h.
MaxShadowResolution
int32 FCachedSystemScalabilityCVars::MaxShadowResolution
Definition at line 406 of file UnrealEngine.h.
SkeletalMeshOverlayDistanceScale
float FCachedSystemScalabilityCVars::SkeletalMeshOverlayDistanceScale
Definition at line 412 of file UnrealEngine.h.
StaticMeshLODDistanceScale
float FCachedSystemScalabilityCVars::StaticMeshLODDistanceScale
Definition at line 411 of file UnrealEngine.h.
ViewDistanceScale
float FCachedSystemScalabilityCVars::ViewDistanceScale
Definition at line 408 of file UnrealEngine.h.
ViewDistanceScaleSquared
float FCachedSystemScalabilityCVars::ViewDistanceScaleSquared
Definition at line 409 of file UnrealEngine.h.
The documentation for this struct was generated from the following file:
UnrealEngine.h