Unreal Engine 5.6 C++ API: FGenericApplicationMessageHandler Class Reference
FGenericApplicationMessageHandler Class Reference
Interface that defines how to handle interaction with a user via hardware input and output.
#include "GenericApplicationMessageHandler.h"
Public Member Functions
virtual ~FGenericApplicationMessageHandler ()
virtual bool BeginReshapingWindow (const TSharedRef< FGenericWindow > &Window)
virtual void FinishedReshapingWindow (const TSharedRef< FGenericWindow > &Window)
virtual FWindowSizeLimits GetSizeLimitsForWindow (const TSharedRef< FGenericWindow > &Window) const
virtual EWindowZone::Type GetWindowZoneForPoint (const TSharedRef< FGenericWindow > &Window, const int32 X, const int32 Y)
virtual void HandleDPIScaleChanged (const TSharedRef< FGenericWindow > &Window)
virtual bool OnApplicationActivationChanged (const bool IsActive)
virtual void OnBeginGesture ()
virtual bool OnControllerAnalog (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, float AnalogValue)
virtual bool OnControllerButtonPressed (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat)
virtual bool OnControllerButtonReleased (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat)
virtual bool OnConvertibleLaptopModeChanged ()
virtual bool OnCursorSet ()
virtual EDropEffect::Type OnDragDrop (const TSharedPtr< FGenericWindow > &Window)
virtual EDropEffect::Type OnDragEnterExternal (const TSharedRef< FGenericWindow > &Window, const FString &Text, const TArray< FString > &Files)
virtual EDropEffect::Type OnDragEnterFiles (const TSharedRef< FGenericWindow > &Window, const TArray< FString > &Files)
virtual EDropEffect::Type OnDragEnterText (const TSharedRef< FGenericWindow > &Window, const FString &Text)
virtual void OnDragLeave (const TSharedPtr< FGenericWindow > &Window)
virtual EDropEffect::Type OnDragOver (const TSharedPtr< FGenericWindow > &Window)
virtual void OnEndGesture ()
virtual void OnInputLanguageChanged ()
virtual bool OnKeyChar (const TCHAR Character, const bool IsRepeat)
virtual bool OnKeyDown (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat)
virtual bool OnKeyUp (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat)
virtual bool OnMotionDetected (const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId)
virtual bool OnMotionDetected (const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration, int32 ControllerId)
virtual bool OnMouseDoubleClick (const TSharedPtr< FGenericWindow > &Window, const EMouseButtons::Type Button)
virtual bool OnMouseDoubleClick (const TSharedPtr< FGenericWindow > &Window, const EMouseButtons::Type Button, const FVector2D CursorPos)
virtual bool OnMouseDown (const TSharedPtr< FGenericWindow > &Window, const EMouseButtons::Type Button)
virtual bool OnMouseDown (const TSharedPtr< FGenericWindow > &Window, const EMouseButtons::Type Button, const FVector2D CursorPos)
virtual bool OnMouseMove ()
virtual bool OnMouseUp (const EMouseButtons::Type Button)
virtual bool OnMouseUp (const EMouseButtons::Type Button, const FVector2D CursorPos)
virtual bool OnMouseWheel (const float Delta)
virtual bool OnMouseWheel (const float Delta, const FVector2D CursorPos)
virtual void OnMovedWindow (const TSharedRef< FGenericWindow > &Window, const int32 X, const int32 Y)
virtual void OnOSPaint (const TSharedRef< FGenericWindow > &Window)
virtual bool OnRawMouseMove (const int32 X, const int32 Y)
virtual void OnResizingWindow (const TSharedRef< FGenericWindow > &Window)
virtual bool OnSizeChanged (const TSharedRef< FGenericWindow > &Window, const int32 Width, const int32 Height, bool bWasMinimized=false)
virtual bool OnTouchEnded (const FVector2D &Location, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID)
virtual bool OnTouchEnded (const FVector2D &Location, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchFirstMove (const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID)
virtual bool OnTouchFirstMove (const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchForceChanged (const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID)
virtual bool OnTouchForceChanged (const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchGesture (EGestureEvent GestureType, const FVector2D &Delta, float WheelDelta, bool bIsDirectionInvertedFromDevice)
virtual bool OnTouchMoved (const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID)
virtual bool OnTouchMoved (const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchStarted (const TSharedPtr< FGenericWindow > &Window, const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceId)
virtual bool OnTouchStarted (const TSharedPtr< FGenericWindow > &Window, const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool OnWindowAction (const TSharedRef< FGenericWindow > &Window, const EWindowAction::Type InActionType)
virtual bool OnWindowActivationChanged (const TSharedRef< FGenericWindow > &Window, const EWindowActivation ActivationType)
virtual void OnWindowClose (const TSharedRef< FGenericWindow > &Window)
virtual void SetCursorPos (const FVector2D &MouseCoordinate)
virtual bool ShouldProcessUserInputMessages (const TSharedPtr< FGenericWindow > &PlatformWindow) const
virtual void ShouldSimulateGesture (EGestureEvent Gesture, bool bEnable)
virtual bool ShouldUsePlatformUserId () const
Return true if this message handler expects FPlatformUserIds.
virtual void SignalSystemDPIChanged (const TSharedRef< FGenericWindow > &Window)
Detailed Description
Interface that defines how to handle interaction with a user via hardware input and output.
Definition at line 208 of file GenericApplicationMessageHandler.h.
Constructor & Destructor Documentation
~FGenericApplicationMessageHandler()
virtual FGenericApplicationMessageHandler::~FGenericApplicationMessageHandler () inline virtual
Definition at line 212 of file GenericApplicationMessageHandler.h.
Member Function Documentation
BeginReshapingWindow()
virtual bool FGenericApplicationMessageHandler::BeginReshapingWindow (const TSharedRef< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 410 of file GenericApplicationMessageHandler.h.
FinishedReshapingWindow()
virtual void FGenericApplicationMessageHandler::FinishedReshapingWindow (const TSharedRef< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 415 of file GenericApplicationMessageHandler.h.
GetSizeLimitsForWindow()
virtual FWindowSizeLimits FGenericApplicationMessageHandler::GetSizeLimitsForWindow (const TSharedRef< FGenericWindow > & Window) const inline virtual
Reimplemented in FSlateApplication.
Definition at line 400 of file GenericApplicationMessageHandler.h.
GetWindowZoneForPoint()
virtual EWindowZone::Type FGenericApplicationMessageHandler::GetWindowZoneForPoint (const TSharedRef< FGenericWindow > & Window, const int32 X, const int32 Y) inline virtual
Reimplemented in FSlateApplication.
Definition at line 450 of file GenericApplicationMessageHandler.h.
References EWindowZone::NotInWindow, X, and Y.
HandleDPIScaleChanged()
virtual void FGenericApplicationMessageHandler::HandleDPIScaleChanged (const TSharedRef< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 420 of file GenericApplicationMessageHandler.h.
OnApplicationActivationChanged()
virtual bool FGenericApplicationMessageHandler::OnApplicationActivationChanged (const bool IsActive) inline virtual
Reimplemented in FSlateApplication.
Definition at line 440 of file GenericApplicationMessageHandler.h.
OnBeginGesture()
virtual void FGenericApplicationMessageHandler::OnBeginGesture () inline virtual
Definition at line 318 of file GenericApplicationMessageHandler.h.
OnControllerAnalog()
virtual bool FGenericApplicationMessageHandler::OnControllerAnalog (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, float AnalogValue) inline virtual
Reimplemented in FSlateApplication.
Definition at line 303 of file GenericApplicationMessageHandler.h.
OnControllerButtonPressed()
virtual bool FGenericApplicationMessageHandler::OnControllerButtonPressed (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat) inline virtual
Reimplemented in FSlateApplication.
Definition at line 308 of file GenericApplicationMessageHandler.h.
OnControllerButtonReleased()
virtual bool FGenericApplicationMessageHandler::OnControllerButtonReleased (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat) inline virtual
Reimplemented in FSlateApplication.
Definition at line 313 of file GenericApplicationMessageHandler.h.
OnConvertibleLaptopModeChanged()
virtual bool FGenericApplicationMessageHandler::OnConvertibleLaptopModeChanged () inline virtual
Reimplemented in FSlateApplication.
Definition at line 445 of file GenericApplicationMessageHandler.h.
OnCursorSet()
virtual bool FGenericApplicationMessageHandler::OnCursorSet () inline virtual
Reimplemented in FSlateApplication.
Definition at line 288 of file GenericApplicationMessageHandler.h.
OnDragDrop()
virtual EDropEffect::Type FGenericApplicationMessageHandler::OnDragDrop (const TSharedPtr< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 485 of file GenericApplicationMessageHandler.h.
References EDropEffect::None.
OnDragEnterExternal()
virtual EDropEffect::Type FGenericApplicationMessageHandler::OnDragEnterExternal (const TSharedRef< FGenericWindow > & Window, const FString & Text, const TArray< FString > & Files) inline virtual
Reimplemented in FSlateApplication.
Definition at line 470 of file GenericApplicationMessageHandler.h.
References EDropEffect::None, and Text.
OnDragEnterFiles()
virtual EDropEffect::Type FGenericApplicationMessageHandler::OnDragEnterFiles (const TSharedRef< FGenericWindow > & Window, const TArray< FString > & Files) inline virtual
Reimplemented in FSlateApplication.
Definition at line 465 of file GenericApplicationMessageHandler.h.
References EDropEffect::None.
OnDragEnterText()
virtual EDropEffect::Type FGenericApplicationMessageHandler::OnDragEnterText (const TSharedRef< FGenericWindow > & Window, const FString & Text) inline virtual
Reimplemented in FSlateApplication.
Definition at line 460 of file GenericApplicationMessageHandler.h.
References EDropEffect::None, and Text.
OnDragLeave()
virtual void FGenericApplicationMessageHandler::OnDragLeave (const TSharedPtr< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 480 of file GenericApplicationMessageHandler.h.
OnDragOver()
virtual EDropEffect::Type FGenericApplicationMessageHandler::OnDragOver (const TSharedPtr< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 475 of file GenericApplicationMessageHandler.h.
References EDropEffect::None.
OnEndGesture()
virtual void FGenericApplicationMessageHandler::OnEndGesture () inline virtual
Definition at line 327 of file GenericApplicationMessageHandler.h.
OnInputLanguageChanged()
virtual void FGenericApplicationMessageHandler::OnInputLanguageChanged () inline virtual
Reimplemented in FSlateApplication.
Definition at line 234 of file GenericApplicationMessageHandler.h.
OnKeyChar()
virtual bool FGenericApplicationMessageHandler::OnKeyChar (const TCHAR Character, const bool IsRepeat) inline virtual
Reimplemented in FSlateApplication.
Definition at line 219 of file GenericApplicationMessageHandler.h.
References Character.
OnKeyDown()
virtual bool FGenericApplicationMessageHandler::OnKeyDown (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat) inline virtual
Reimplemented in FSlateApplication.
Definition at line 224 of file GenericApplicationMessageHandler.h.
OnKeyUp()
virtual bool FGenericApplicationMessageHandler::OnKeyUp (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat) inline virtual
Reimplemented in FSlateApplication.
Definition at line 229 of file GenericApplicationMessageHandler.h.
OnMotionDetected() [1/2]
virtual bool FGenericApplicationMessageHandler::OnMotionDetected (const FVector & Tilt, const FVector & RotationRate, const FVector & Gravity, const FVector & Acceleration, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId) inline virtual
Reimplemented in FSlateApplication.
Definition at line 381 of file GenericApplicationMessageHandler.h.
References Acceleration, FVector, FPlatformUserId::GetInternalId(), OnMotionDetected(), and ShouldUsePlatformUserId().
Referenced by OnMotionDetected(), and OnMotionDetected().
OnMotionDetected() [2/2]
virtual bool FGenericApplicationMessageHandler::OnMotionDetected (const FVector & Tilt, const FVector & RotationRate, const FVector & Gravity, const FVector & Acceleration, int32 ControllerId) inline virtual
Definition at line 560 of file GenericApplicationMessageHandler.h.
References Acceleration, FVector, IPlatformInputDeviceMapper::Get(), FGenericPlatformMisc::GetPlatformUserForUserIndex(), INPUTDEVICEID_NONE, OnMotionDetected(), IPlatformInputDeviceMapper::RemapControllerIdToPlatformUserAndDevice(), and ShouldUsePlatformUserId().
OnMouseDoubleClick() [1/2]
virtual bool FGenericApplicationMessageHandler::OnMouseDoubleClick (const TSharedPtr< FGenericWindow > & Window, const EMouseButtons::Type Button) inline virtual
Reimplemented in FSlateApplication.
Definition at line 258 of file GenericApplicationMessageHandler.h.
OnMouseDoubleClick() [2/2]
virtual bool FGenericApplicationMessageHandler::OnMouseDoubleClick (const TSharedPtr< FGenericWindow > & Window, const EMouseButtons::Type Button, const FVector2D CursorPos) inline virtual
Reimplemented in FSlateApplication.
Definition at line 263 of file GenericApplicationMessageHandler.h.
OnMouseDown() [1/2]
virtual bool FGenericApplicationMessageHandler::OnMouseDown (const TSharedPtr< FGenericWindow > & Window, const EMouseButtons::Type Button) inline virtual
Reimplemented in FSlateApplication.
Definition at line 238 of file GenericApplicationMessageHandler.h.
OnMouseDown() [2/2]
virtual bool FGenericApplicationMessageHandler::OnMouseDown (const TSharedPtr< FGenericWindow > & Window, const EMouseButtons::Type Button, const FVector2D CursorPos) inline virtual
Reimplemented in FSlateApplication.
Definition at line 243 of file GenericApplicationMessageHandler.h.
OnMouseMove()
virtual bool FGenericApplicationMessageHandler::OnMouseMove () inline virtual
Reimplemented in FSlateApplication.
Definition at line 278 of file GenericApplicationMessageHandler.h.
OnMouseUp() [1/2]
virtual bool FGenericApplicationMessageHandler::OnMouseUp (const EMouseButtons::Type Button) inline virtual
Reimplemented in FSlateApplication.
Definition at line 248 of file GenericApplicationMessageHandler.h.
OnMouseUp() [2/2]
virtual bool FGenericApplicationMessageHandler::OnMouseUp (const EMouseButtons::Type Button, const FVector2D CursorPos) inline virtual
Reimplemented in FSlateApplication.
Definition at line 253 of file GenericApplicationMessageHandler.h.
OnMouseWheel() [1/2]
virtual bool FGenericApplicationMessageHandler::OnMouseWheel (const float Delta) inline virtual
Reimplemented in FSlateApplication.
Definition at line 268 of file GenericApplicationMessageHandler.h.
OnMouseWheel() [2/2]
virtual bool FGenericApplicationMessageHandler::OnMouseWheel (const float Delta, const FVector2D CursorPos) inline virtual
Reimplemented in FSlateApplication.
Definition at line 273 of file GenericApplicationMessageHandler.h.
OnMovedWindow()
virtual void FGenericApplicationMessageHandler::OnMovedWindow (const TSharedRef< FGenericWindow > & Window, const int32 X, const int32 Y) inline virtual
Reimplemented in FSlateApplication.
Definition at line 430 of file GenericApplicationMessageHandler.h.
References X, and Y.
OnOSPaint()
virtual void FGenericApplicationMessageHandler::OnOSPaint (const TSharedRef< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 395 of file GenericApplicationMessageHandler.h.
OnRawMouseMove()
virtual bool FGenericApplicationMessageHandler::OnRawMouseMove (const int32 X, const int32 Y) inline virtual
Reimplemented in FSlateApplication.
Definition at line 283 of file GenericApplicationMessageHandler.h.
References X, and Y.
OnResizingWindow()
virtual void FGenericApplicationMessageHandler::OnResizingWindow (const TSharedRef< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 405 of file GenericApplicationMessageHandler.h.
OnSizeChanged()
virtual bool FGenericApplicationMessageHandler::OnSizeChanged (const TSharedRef< FGenericWindow > & Window, const int32 Width, const int32 Height, bool bWasMinimized = false) inline virtual
Reimplemented in FSlateApplication.
Definition at line 390 of file GenericApplicationMessageHandler.h.
References Width.
OnTouchEnded() [1/2]
virtual bool FGenericApplicationMessageHandler::OnTouchEnded (const FVector2D & Location, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) inline virtual
Reimplemented in FSlateApplication.
Definition at line 349 of file GenericApplicationMessageHandler.h.
References DeviceID, FPlatformUserId::GetInternalId(), Location, OnTouchEnded(), and ShouldUsePlatformUserId().
Referenced by OnTouchEnded(), and OnTouchEnded().
OnTouchEnded() [2/2]
virtual bool FGenericApplicationMessageHandler::OnTouchEnded (const FVector2D & Location, int32 TouchIndex, int32 ControllerId) inline virtual
Definition at line 524 of file GenericApplicationMessageHandler.h.
References IPlatformInputDeviceMapper::Get(), FGenericPlatformMisc::GetPlatformUserForUserIndex(), INPUTDEVICEID_NONE, Location, OnTouchEnded(), IPlatformInputDeviceMapper::RemapControllerIdToPlatformUserAndDevice(), and ShouldUsePlatformUserId().
OnTouchFirstMove() [1/2]
virtual bool FGenericApplicationMessageHandler::OnTouchFirstMove (const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) inline virtual
Reimplemented in FSlateApplication.
Definition at line 367 of file GenericApplicationMessageHandler.h.
References DeviceID, Force, FPlatformUserId::GetInternalId(), Location, OnTouchFirstMove(), and ShouldUsePlatformUserId().
Referenced by OnTouchFirstMove(), and OnTouchFirstMove().
OnTouchFirstMove() [2/2]
virtual bool FGenericApplicationMessageHandler::OnTouchFirstMove (const FVector2D & Location, float Force, int32 TouchIndex, int32 ControllerId) inline virtual
Definition at line 548 of file GenericApplicationMessageHandler.h.
References Force, IPlatformInputDeviceMapper::Get(), FGenericPlatformMisc::GetPlatformUserForUserIndex(), INPUTDEVICEID_NONE, Location, OnTouchFirstMove(), IPlatformInputDeviceMapper::RemapControllerIdToPlatformUserAndDevice(), and ShouldUsePlatformUserId().
OnTouchForceChanged() [1/2]
virtual bool FGenericApplicationMessageHandler::OnTouchForceChanged (const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) inline virtual
Reimplemented in FSlateApplication.
Definition at line 358 of file GenericApplicationMessageHandler.h.
References DeviceID, Force, FPlatformUserId::GetInternalId(), Location, OnTouchForceChanged(), and ShouldUsePlatformUserId().
Referenced by OnTouchForceChanged(), and OnTouchForceChanged().
OnTouchForceChanged() [2/2]
virtual bool FGenericApplicationMessageHandler::OnTouchForceChanged (const FVector2D & Location, float Force, int32 TouchIndex, int32 ControllerId) inline virtual
Definition at line 536 of file GenericApplicationMessageHandler.h.
References Force, IPlatformInputDeviceMapper::Get(), FGenericPlatformMisc::GetPlatformUserForUserIndex(), INPUTDEVICEID_NONE, Location, OnTouchForceChanged(), IPlatformInputDeviceMapper::RemapControllerIdToPlatformUserAndDevice(), and ShouldUsePlatformUserId().
OnTouchGesture()
virtual bool FGenericApplicationMessageHandler::OnTouchGesture (EGestureEvent GestureType, const FVector2D & Delta, float WheelDelta, bool bIsDirectionInvertedFromDevice) inline virtual
Reimplemented in FSlateApplication.
Definition at line 322 of file GenericApplicationMessageHandler.h.
OnTouchMoved() [1/2]
virtual bool FGenericApplicationMessageHandler::OnTouchMoved (const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) inline virtual
Reimplemented in FSlateApplication.
Definition at line 340 of file GenericApplicationMessageHandler.h.
References DeviceID, Force, FPlatformUserId::GetInternalId(), Location, OnTouchMoved(), and ShouldUsePlatformUserId().
Referenced by OnTouchMoved(), and OnTouchMoved().
OnTouchMoved() [2/2]
virtual bool FGenericApplicationMessageHandler::OnTouchMoved (const FVector2D & Location, float Force, int32 TouchIndex, int32 ControllerId) inline virtual
Definition at line 512 of file GenericApplicationMessageHandler.h.
References Force, IPlatformInputDeviceMapper::Get(), FGenericPlatformMisc::GetPlatformUserForUserIndex(), INPUTDEVICEID_NONE, Location, OnTouchMoved(), IPlatformInputDeviceMapper::RemapControllerIdToPlatformUserAndDevice(), and ShouldUsePlatformUserId().
OnTouchStarted() [1/2]
virtual bool FGenericApplicationMessageHandler::OnTouchStarted (const TSharedPtr< FGenericWindow > & Window, const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceId) inline virtual
Reimplemented in FSlateApplication.
Definition at line 331 of file GenericApplicationMessageHandler.h.
References Force, FPlatformUserId::GetInternalId(), Location, OnTouchStarted(), and ShouldUsePlatformUserId().
Referenced by OnTouchStarted(), and OnTouchStarted().
OnTouchStarted() [2/2]
virtual bool FGenericApplicationMessageHandler::OnTouchStarted (const TSharedPtr< FGenericWindow > & Window, const FVector2D & Location, float Force, int32 TouchIndex, int32 ControllerId) inline virtual
Definition at line 500 of file GenericApplicationMessageHandler.h.
References Force, IPlatformInputDeviceMapper::Get(), FGenericPlatformMisc::GetPlatformUserForUserIndex(), INPUTDEVICEID_NONE, Location, OnTouchStarted(), IPlatformInputDeviceMapper::RemapControllerIdToPlatformUserAndDevice(), and ShouldUsePlatformUserId().
OnWindowAction()
virtual bool FGenericApplicationMessageHandler::OnWindowAction (const TSharedRef< FGenericWindow > & Window, const EWindowAction::Type InActionType) inline virtual
Reimplemented in FSlateApplication.
Definition at line 490 of file GenericApplicationMessageHandler.h.
OnWindowActivationChanged()
virtual bool FGenericApplicationMessageHandler::OnWindowActivationChanged (const TSharedRef< FGenericWindow > & Window, const EWindowActivation ActivationType) inline virtual
Reimplemented in FSlateApplication.
Definition at line 435 of file GenericApplicationMessageHandler.h.
OnWindowClose()
virtual void FGenericApplicationMessageHandler::OnWindowClose (const TSharedRef< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 455 of file GenericApplicationMessageHandler.h.
SetCursorPos()
virtual void FGenericApplicationMessageHandler::SetCursorPos (const FVector2D & MouseCoordinate) inline virtual
Reimplemented in FSlateApplication.
Definition at line 495 of file GenericApplicationMessageHandler.h.
ShouldProcessUserInputMessages()
virtual bool FGenericApplicationMessageHandler::ShouldProcessUserInputMessages (const TSharedPtr< FGenericWindow > & PlatformWindow) const inline virtual
Reimplemented in FSlateApplication.
Definition at line 214 of file GenericApplicationMessageHandler.h.
ShouldSimulateGesture()
virtual void FGenericApplicationMessageHandler::ShouldSimulateGesture (EGestureEvent Gesture, bool bEnable) inline virtual
Reimplemented in FSlateApplication.
Definition at line 376 of file GenericApplicationMessageHandler.h.
ShouldUsePlatformUserId()
virtual bool FGenericApplicationMessageHandler::ShouldUsePlatformUserId () const inline virtual
Return true if this message handler expects FPlatformUserIds.
This base class will convert both directions. As part of a larger fixup to allow mapping of multiple input devices to the same player, physical device id will be passed as part of the InputScope above and used to compute a logical input user.
Definition at line 298 of file GenericApplicationMessageHandler.h.
Referenced by OnMotionDetected(), OnMotionDetected(), OnTouchEnded(), OnTouchEnded(), OnTouchFirstMove(), OnTouchFirstMove(), OnTouchForceChanged(), OnTouchForceChanged(), OnTouchMoved(), OnTouchMoved(), OnTouchStarted(), and OnTouchStarted().
SignalSystemDPIChanged()
virtual void FGenericApplicationMessageHandler::SignalSystemDPIChanged (const TSharedRef< FGenericWindow > & Window) inline virtual
Reimplemented in FSlateApplication.
Definition at line 425 of file GenericApplicationMessageHandler.h.
The documentation for this class was generated from the following file:
GenericApplicationMessageHandler.h