Unreal Engine 5.6 C++ API: Geometry.h File Reference
Geometry.h File Reference
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "Layout/Margin.h"
#include "Layout/PaintGeometry.h"
#include "Layout/SlateRect.h"
#include "Layout/SlateRotatedRect.h"
#include "Math/TransformCalculus.h"
#include "Math/TransformCalculus2D.h"
#include "Math/UnrealMathSSE.h"
#include "Math/Vector2D.h"
#include "Rendering/SlateLayoutTransform.h"
#include "Rendering/SlateRenderTransform.h"
#include "Templates/SharedPointer.h"
#include "UObject/ObjectMacros.h"
#include "Types/SlateVector2.h"
#include "Geometry.generated.h"
Data Structures
struct TIsPODType< FGeometry >
Functions
USTRUCT () struct FGeometry
Represents the position, size, and absolute position of a Widget in Slate.
Function Documentation
USTRUCT()
USTRUCT ()
Represents the position, size, and absolute position of a Widget in Slate.
The absolute location of a geometry is usually screen space or window space depending on where the geometry originated. Geometries are usually paired with a SWidget pointer in order to provide information about a specific widget (see FArrangedWidget). A Geometry's parent is generally thought to be the Geometry of the the corresponding parent widget.
Default constructor. Creates a geometry with identity transforms.
Copy constructor.
!!! HACK!!! We're keeping members of FGeometry const to prevent mutability without making them private, for backward compatibility. But this means the assignment operator no longer works. We implement one ourselves now and force a memcpy.
!!! DEPRECATED FUNCTION !!! Use MakeChild taking a layout transform instead! Construct a new geometry given the following parameters:
Parameters
OffsetFromParent Local position of this geometry within its parent geometry.
ParentAbsolutePosition The absolute position of the parent geometry containing this geometry.
InSize The size of this geometry.
InScale The scale of this geometry with respect to Normal Slate Coordinates.
Construct a new geometry with a given size in LocalSpace that is attached to a parent geometry with the given layout and render transform.
Parameters
InLocalSize The size of the geometry in Local Space.
InLocalLayoutTransform A layout transform from local space to the parent geoemtry's local space.
InLocalRenderTransform A render-only transform in local space that will be prepended to the LocalLayoutTransform when rendering.
InLocalRenderTransformPivot Pivot in normalizes local space for the local render transform.
ParentAccumulatedLayoutTransform The accumulated layout transform of the parent widget. AccumulatedLayoutTransform = Concat(LocalLayoutTransform, ParentAccumulatedLayoutTransform).
ParentAccumulatedRenderTransform The accumulated render transform of the parent widget. AccumulatedRenderTransform = Concat(LocalRenderTransform, LocalLayoutTransform, ParentAccumulatedRenderTransform).
Construct a new geometry with a given size in LocalSpace (and identity render transform) that is attached to a parent geometry with the given layout and render transform.
Parameters
InLocalSize The size of the geometry in Local Space.
InLocalLayoutTransform A layout transform from local space to the parent geoemtry's local space.
ParentAccumulatedLayoutTransform The accumulated layout transform of the parent widget. AccumulatedLayoutTransform = Concat(LocalLayoutTransform, ParentAccumulatedLayoutTransform).
ParentAccumulatedRenderTransform The accumulated render transform of the parent widget. AccumulatedRenderTransform = Concat(LocalRenderTransform, LocalLayoutTransform, ParentAccumulatedRenderTransform).
Test geometries for strict equality (i.e. exact float equality).
Parameters
Other A geometry to compare to.
Returns
true if this is equal to other, false otherwise.
Test geometries for strict inequality (i.e. exact float equality negated).
Parameters
Other A geometry to compare to.
Returns
false if this is equal to other, true otherwise.
Makes a new geometry that is essentially the root of a hierarchy (has no parent transforms to inherit). For a root Widget, the LayoutTransform is often the window DPI scale + window offset.
Parameters
LocalSize Size of the geometry in Local Space.
LayoutTransform Layout transform of the geometry.
Returns
The new root geometry
Makes a new geometry that is essentially the root of a hierarchy (has no parent transforms to inherit). For a root Widget, the LayoutTransform is often the window DPI scale + window offset.
Parameters
LocalSize Size of the geometry in Local Space.
LayoutTransform Layout transform of the geometry.
Returns
The new root geometry
Create a child geometry relative to this one with a given local space size, layout transform, and render transform. For example, a widget with a 5x5 margin will create a geometry for it's child contents having a LayoutTransform of Translate(5,5) and a LocalSize 10 units smaller than it's own.
Parameters
LocalSize The size of the child geometry in local space.
LayoutTransform Layout transform of the new child relative to this Geometry. Goes from the child's layout space to the this widget's layout space.
RenderTransform Render-only transform of the new child that is applied before the layout transform for rendering purposes only.
RenderTransformPivot Pivot in normalized local space of the Render transform.
Returns
The new child geometry.
Create a child geometry relative to this one with a given local space size, layout transform, and identity render transform. For example, a widget with a 5x5 margin will create a geometry for it's child contents having a LayoutTransform of Translate(5,5) and a LocalSize 10 units smaller than it's own.
Parameters
LocalSize The size of the child geometry in local space.
LayoutTransform Layout transform of the new child relative to this Geometry. Goes from the child's layout space to the this widget's layout space.
Returns
The new child geometry.
Create a child geometry+widget relative to this one using the given LayoutGeometry.
Parameters
ChildWidget The child widget this geometry is being created for.
LayoutGeometry Layout geometry of the child.
Returns
The new child geometry.
Create a child geometry+widget relative to this one with a given local space size and layout transform. The Geometry inherits the child widget's render transform. For example, a widget with a 5x5 margin will create a geometry for it's child contents having a LayoutTransform of Translate(5,5) and a LocalSize 10 units smaller than it's own.
Parameters
ChildWidget The child widget this geometry is being created for.
LocalSize The size of the child geometry in local space.
LayoutTransform Layout transform of the new child relative to this Geometry.
Returns
The new child geometry+widget.
!!! DEPRECATED FUNCTION !!! Use MakeChild taking a layout transform instead! Create a child geometry+widget relative to this one with a given local space size and layout transform given by a scale+offset. The Geometry inherits the child widget's render transform.
Parameters
ChildWidget The child widget this geometry is being created for.
ChildOffset Offset of the child relative to the parent. Scale+Offset effectively define the layout transform.
LocalSize The size of the child geometry in local space.
ChildScale Scale of the child relative to the parent. Scale+Offset effectively define the layout transform.
Returns
The new child geometry+widget.
Create a paint geometry that represents this geometry.
Returns
The new paint geometry.
Create a paint geometry relative to this one with a given local space size and layout transform. The paint geometry inherits the widget's render transform.
Parameters
LocalSize The size of the child geometry in local space.
LayoutTransform Layout transform of the paint geometry relative to this Geometry.
Returns
The new paint geometry derived from this one.
Create a paint geometry relative to this one with a given local space size and layout transform. The paint geometry inherits the widget's render transform.
Parameters
LocalSize The size of the child geometry in local space.
LayoutTransform Layout transform of the paint geometry relative to this Geometry.
Returns
The new paint geometry derived from this one.
Create a paint geometry with the same size as this geometry with a given layout transform. The paint geometry inherits the widget's render transform.
Parameters
LayoutTransform Layout transform of the paint geometry relative to this Geometry.
Returns
The new paint geometry derived from this one.
!!! DEPRECATED FUNCTION !!! Use ToPaintGeometry taking a layout transform instead! Create a paint geometry relative to this one with the same size size and a given local space offset. The paint geometry inherits the widget's render transform.
Parameters
LocalOffset Offset of the paint geometry relative to the parent. Effectively defines the layout transform.
Returns
The new paint geometry derived from this one.
Create a paint geometry relative to this one that whose local space is "inflated" by the specified amount in each direction. The paint geometry inherits the widget's render transform.
Parameters
InflateAmount Amount by which to "inflate" the geometry in each direction around the center point. Effectively defines a layout transform offset and an inflation of the LocalSize.
Returns
The new paint geometry derived from this one.
Absolute coordinates could be either desktop or window space depending on what space the root of the widget hierarchy is in.
Returns
true if the provided location in absolute coordinates is within the bounds of this geometry.
Absolute coordinates could be either desktop or window space depending on what space the root of the widget hierarchy is in.
Returns
Transforms AbsoluteCoordinate into the local space of this Geometry.
Translates local coordinates into absolute coordinates
Absolute coordinates could be either desktop or window space depending on what space the root of the widget hierarchy is in.
Returns
Absolute coordinates
Translates the local coordinates into local coordinates that after being transformed into absolute space will be rounded to a whole number or approximately a whole number. This is important for cases where you want to show a popup or a tooltip and not have the window start on a half pixel, which can cause the contents to jitter in relation to each other as the tooltip or popup moves around.
Returns
A String representation of this Geometry
!!! DEPRECATED !!! This legacy function does not account for render transforms.
Absolute coordinates could be either desktop or window space depending on what space the root of the widget hierarchy is in.
Returns
the size of the geometry in absolute space
the size of the geometry in local space.
the accumulated render transform. Shouldn't be needed in general.
the accumulated layout transform. Shouldn't be needed in general.
Special case method to append a layout transform to a geometry. This is used in cases where the FGeometry was arranged in window space and we need to add the root desktop translation. If you find yourself wanting to use this function, ask someone if there's a better way.
Parameters
LayoutTransform An additional layout transform to append to this geometry.
Get the absolute position in render space.
Get the absolute size of the geometry in render space.
Get the absolute position on the surface of the geometry using normalized coordinates. (0,0) - upper left (1,1) - bottom right
Example: Say you wanted to know the center of the widget in absolute space, GetAbsolutePositionAtCoordinates(FVector2f(0.5f, 0.5f));
Get the local position on the surface of the geometry using normalized coordinates. (0,0) - upper left (1,1) - bottom right
Example: Say you wanted to know the center of the widget in local space, GetLocalPositionAtCoordinates(FVector2f(0.5f, 0.5f));
!!! DEPRECATED !!! Use GetLocalSize() accessor instead of directly accessing public members.
This member has been made const to prevent mutation.
There is no way to easily detect mutation of public members, thus no way to update the render transforms when they are modified.
Size of the geometry in local space.
!!! DEPRECATED !!! These legacy public members should ideally not be referenced, as they do not account for the render transform. FGeometry manipulation should be done in local space as much as possible so logic can be done in aligned local space, but still support arbitrary render transforms.
This member has been made const to prevent mutation, which would also break render transforms, which are computed during construction. There is no way to easily detect mutation of public members, thus no way to update the render transforms when they are modified.
Scale in absolute space. Equivalent to the scale of the accumulated layout transform.
Absolute coordinates could be either desktop or window space depending on what space the root of the widget hierarchy is in.
!!! DEPRECATED !!! These legacy public members should ideally not be referenced, as they do not account for the render transform. FGeometry manipulation should be done in local space as much as possible so logic can be done in aligned local space, but still support arbitrary render transforms.
This member has been made const to prevent mutation, which would also break render transforms, which are computed during construction. There is no way to easily detect mutation of public members, thus no way to update the render transforms when they are modified.
Position in absolute space. Equivalent to the translation of the accumulated layout transform.
Absolute coordinates could be either desktop or window space depending on what space the root of the widget hierarchy is in.
!!! DEPRECATED !!!
Position of the geometry with respect to its parent in local space. Equivalent to the translation portion of the Local->Parent layout transform. If you know your children have no additional scale applied to them, you can use this as the Local->Parent layout transform. If your children DO have additional scale applied, there is no way to determine the actual Local->Parent layout transform, since the scale is accumulated.
Concatenated Render Transform. Actual transform used for rendering. Formed as: Concat(LocalRenderTransform, LocalLayoutTransform, Parent->AccumulatedRenderTransform)
For rendering, absolute coordinates will always be in window space (relative to the root window).
Definition at line 38 of file Geometry.h.
References BlueprintType, UE::Slate::CastToVector2f(), Concatenate(), FORCEINLINE, FORCEINLINE_DEBUGGABLE, GENERATED_USTRUCT_BODY, FSlateLayoutTransform::GetScale(), FSlateLayoutTransform::GetTranslation(), Inverse(), FSlateRotatedRect::IsUnderLocation(), operator!=(), operator=(), operator==(), Other, Position, RenderTransform, Scale, ToString(), TransformCast(), TransformPoint(), TransformRect(), TransformVector(), TSequenceHistory< HistorySize >::Size, UE_DEPRECATED, UE::Math::TVector2< T >::X, UE::Math::TVector2< T >::Y, and UE::Math::TVector2< float >::ZeroVector.