Unreal Engine 5.6 C++ API: THazardPointer< H, Cached > Class Template Reference
THazardPointer< H, Cached > Class Template Reference
THazardPointer is used to keep an allocation alive until all threads that referenced it finished their access.
#include "HazardPointer.h"
Public Member Functions
THazardPointer ()=default
THazardPointer (std::atomic< H * > &InHazard, FHazardPointerCollection &Collection)
THazardPointer (THazardPointer &&Other)
~THazardPointer ()
void Destroy ()
H * Get () const
bool IsValid ()
THazardPointer & operator= (THazardPointer &&Other)
void Retire ()
Private Member Functions
THazardPointer (const THazardPointer &)=delete
THazardPointer & operator= (const THazardPointer &)=delete
Private Attributes
std::atomic< H * > * Hazard = nullptr
FHazardPointerCollection::FHazardRecord * Record = nullptr
Detailed Description
template<typename H, bool Cached = false>
class THazardPointer< H, Cached >
THazardPointer is used to keep an allocation alive until all threads that referenced it finished their access.
Definition at line 244 of file HazardPointer.h.
Constructor & Destructor Documentation
THazardPointer() [1/4]
template<typename H, bool Cached = false> THazardPointer< H, Cached >::THazardPointer (const THazardPointer< H, Cached > &) private delete
References THazardPointer().
Referenced by THazardPointer(), THazardPointer(), operator=(), and operator=().
THazardPointer() [2/4]
template<typename H, bool Cached = false> THazardPointer< H, Cached >::THazardPointer (THazardPointer< H, Cached > && Other) inline
Definition at line 253 of file HazardPointer.h.
References THazardPointer(), Hazard, Other, and Record.
THazardPointer() [3/4]
template<typename H, bool Cached = false> THazardPointer< H, Cached >::THazardPointer () default
THazardPointer() [4/4]
template<typename H, bool Cached = false> THazardPointer< H, Cached >::THazardPointer (std::atomic< H * > & InHazard, FHazardPointerCollection & Collection) inline
Definition at line 279 of file HazardPointer.h.
References checkSlow, Hazard, and Record.
~THazardPointer()
template<typename H, bool Cached = false> THazardPointer< H, Cached >::~THazardPointer () inline
Definition at line 285 of file HazardPointer.h.
References Record.
Member Function Documentation
Destroy()
template<typename H, bool Cached = false> void THazardPointer< H, Cached >::Destroy () inline
Definition at line 301 of file HazardPointer.h.
References checkSlow, Hazard, and Record.
Get()
template<typename H, bool Cached = false> H * THazardPointer< H, Cached >::Get () const inline
Definition at line 309 of file HazardPointer.h.
References checkSlow, Hazard, and Record.
IsValid()
template<typename H, bool Cached = false> bool THazardPointer< H, Cached >::IsValid () inline
Definition at line 320 of file HazardPointer.h.
References Hazard, and Record.
operator=() [1/2]
template<typename H, bool Cached = false> THazardPointer & THazardPointer< H, Cached >::operator= (const THazardPointer< H, Cached > &) private delete
References THazardPointer().
operator=() [2/2]
template<typename H, bool Cached = false> THazardPointer & THazardPointer< H, Cached >::operator= (THazardPointer< H, Cached > && Other) inline
Definition at line 263 of file HazardPointer.h.
References THazardPointer(), Hazard, Other, and Record.
Retire()
template<typename H, bool Cached = false> void THazardPointer< H, Cached >::Retire () inline
Definition at line 294 of file HazardPointer.h.
References checkSlow, and Record.
Field Documentation
Hazard
template<typename H, bool Cached = false> std::atomic<H*>* THazardPointer< H, Cached >::Hazard = nullptr private
Definition at line 249 of file HazardPointer.h.
Referenced by THazardPointer(), THazardPointer(), Destroy(), Get(), IsValid(), and operator=().
Record
template<typename H, bool Cached = false> FHazardPointerCollection::FHazardRecord* THazardPointer< H, Cached >::Record = nullptr private
Definition at line 250 of file HazardPointer.h.
Referenced by THazardPointer(), THazardPointer(), ~THazardPointer(), Destroy(), Get(), IsValid(), operator=(), and Retire().
The documentation for this class was generated from the following file:
HazardPointer.h