Unreal Engine 5.6 C++ API: UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize > Class Template Reference
UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize > Class Template Reference
Tri-linear interpolant for a 3D dense Grid.
#include "GridInterpolant.h"
Public Types
using CellSizeType = std::conditional_t<bScalarCellSize, RealType, TVector<RealType>>
Public Member Functions
TTriLinearGridInterpolant (GridType *Grid, TVector< RealType > GridOrigin, CellSizeType CellSize, FVector3i Dimensions)
TAxisAlignedBox3< RealType > Bounds () const
FVector3i Cell (const TVector< RealType > &Pt) const
TVector< RealType > Gradient (const TVector< RealType > &Pt) const
template<bool bClamped = false>
RealType Value (const TVector< RealType > &Pt) const
Data Fields
CellSizeType CellSize
FVector3i Dimensions
GridType * Grid
TVector< RealType > GridOrigin
RealType Outside = TMathUtil<RealType>::SafeLargeValue
Protected Member Functions
void get_value_pair (int I, int J, int K, RealType &A, RealType &B) const
Static Private Member Functions
static FORCEINLINE RealType GetDim (CellSizeType CellSize, int32 Axis)
Detailed Description
template<class GridType, typename RealType = double, bool bScalarCellSize = true>
class UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >
Tri-linear interpolant for a 3D dense Grid.
Supports Grid translation via GridOrigin, but does not support scaling or rotation. If you need those, you can wrap this in something that does the xform.
GridType must have a GetValue() that returns a value to interpolate at a given FVector3i location – (w/ locations ranging from [0,0,0] to Dimensions (exclusive))
Definition at line 28 of file GridInterpolant.h.
Member Typedef Documentation
CellSizeType
template<class GridType, typename RealType = double, bool bScalarCellSize = true> using UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::CellSizeType = std::conditional_t<bScalarCellSize, RealType, TVector<RealType>>
Definition at line 34 of file GridInterpolant.h.
Constructor & Destructor Documentation
TTriLinearGridInterpolant()
template<class GridType, typename RealType = double, bool bScalarCellSize = true> UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::TTriLinearGridInterpolant (GridType * Grid, TVector< RealType > GridOrigin, CellSizeType CellSize, FVector3i Dimensions) inline
Definition at line 46 of file GridInterpolant.h.
References CellSize, Dimensions, Grid, and GridOrigin.
Member Function Documentation
Bounds()
template<class GridType, typename RealType = double, bool bScalarCellSize = true> TAxisAlignedBox3< RealType > UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Bounds () const inline
Definition at line 50 of file GridInterpolant.h.
References CellSize, Dimensions, GetDim(), and GridOrigin.
Referenced by UE::Geometry::IsInside(), UE::Geometry::IsInside(), UE::Geometry::IsInside(), UE::Geometry::IsInside(), and UE::Geometry::IsInsideHull().
Cell()
template<class GridType, typename RealType = double, bool bScalarCellSize = true> FVector3i UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Cell (const TVector< RealType > & Pt) const inline
Definition at line 59 of file GridInterpolant.h.
References CellSize, GetDim(), GridOrigin, UE::Geometry::FVector3i::X, UE::Math::TVector< T >::X, UE::Geometry::FVector3i::Y, UE::Math::TVector< T >::Y, UE::Geometry::FVector3i::Z, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::IsInside().
get_value_pair()
template<class GridType, typename RealType = double, bool bScalarCellSize = true> void UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::get_value_pair (int I, int J, int K, RealType & A, RealType & B) const inline protected
Definition at line 144 of file GridInterpolant.h.
References A, B, and Grid.
Referenced by Gradient(), and Value().
GetDim()
template<class GridType, typename RealType = double, bool bScalarCellSize = true> FORCEINLINE RealType UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::GetDim (CellSizeType CellSize, int32 Axis) inline static private
Definition at line 221 of file GridInterpolant.h.
References Axis, CellSize, and FORCEINLINE.
Referenced by Bounds(), Cell(), Gradient(), and Value().
Gradient()
template<class GridType, typename RealType = double, bool bScalarCellSize = true> TVector< RealType > UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Gradient (const TVector< RealType > & Pt) const inline
Definition at line 152 of file GridInterpolant.h.
References CellSize, Dimensions, get_value_pair(), GetDim(), GridOrigin, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, UE::Math::TVector< T >::Z, and UE::Math::TVector< T >::Zero().
Value()
template<class GridType, typename RealType = double, bool bScalarCellSize = true> template<bool bClamped = false> RealType UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Value (const TVector< RealType > & Pt) const inline
Definition at line 71 of file GridInterpolant.h.
References CellSize, FMath::Clamp(), Dimensions, TMathUtilConstants< double >::Epsilon, get_value_pair(), GetDim(), GridOrigin, Outside, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeFirstPass(), and UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeSecondPass().
Field Documentation
CellSize
template<class GridType, typename RealType = double, bool bScalarCellSize = true> CellSizeType UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::CellSize
Definition at line 38 of file GridInterpolant.h.
Referenced by TTriLinearGridInterpolant(), Bounds(), Cell(), GetDim(), Gradient(), and Value().
Dimensions
template<class GridType, typename RealType = double, bool bScalarCellSize = true> FVector3i UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Dimensions
Definition at line 39 of file GridInterpolant.h.
Referenced by TTriLinearGridInterpolant(), Bounds(), Gradient(), UE::Geometry::IsInside(), and Value().
Grid
template<class GridType, typename RealType = double, bool bScalarCellSize = true> GridType* UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Grid
Definition at line 36 of file GridInterpolant.h.
Referenced by TTriLinearGridInterpolant(), get_value_pair(), and UE::Geometry::IsInside().
GridOrigin
template<class GridType, typename RealType = double, bool bScalarCellSize = true> TVector<RealType> UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::GridOrigin
Definition at line 37 of file GridInterpolant.h.
Referenced by TTriLinearGridInterpolant(), Bounds(), Cell(), Gradient(), and Value().
Outside
template<class GridType, typename RealType = double, bool bScalarCellSize = true> RealType UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Outside = TMathUtil<RealType>::SafeLargeValue
Definition at line 44 of file GridInterpolant.h.
Referenced by Value().
The documentation for this class was generated from the following file:
GridInterpolant.h