Unreal Engine 5.6 C++ API: FActorFolders Struct Reference
FActorFolders Struct Reference
Class responsible for managing an in-memory representation of actor folders in the editor.
#include "EditorActorFolders.h"
Public Member Functions
UNREALED_API FActorFolders ()
UNREALED_API ~FActorFolders ()
virtual UNREALED_API void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
virtual bool CanResetContext (UWorld *InWorld) const override
virtual void CaptureActorEditorContextState (UWorld *InWorld, UActorEditorContextStateCollection *InStateCollection) const override
UNREALED_API bool ContainsFolder (UWorld &InWorld, const FFolder &InFolder)
Return if folder exists.
UNREALED_API bool CreateFolder (UWorld &InWorld, const FFolder &InFolder)
Create a new folder in the specified world, of the specified path.
UNREALED_API void CreateFolderContainingSelection (UWorld &InWorld, const FFolder &InFolder)
Same as CreateFolder, but moves the current actor selection into the new folder as well.
UNREALED_API void DeleteFolder (UWorld &InWorld, const FFolder &InFolderToDelete)
Delete the specified folder in the world.
UNREALED_API void ForEachFolder (UWorld &InWorld, TFunctionRef< bool(const FFolder &)> Operation)
Iterate on all folders of a world and pass it to the provided operation.
UNREALED_API void ForEachFolderWithRootObject (UWorld &InWorld, const FFolder::FRootObject &InFolderRootObject, TFunctionRef< bool(const FFolder &)> Operation)
Iterate on all world's folders with the given root object and pass it to the provided operation.
virtual bool GetActorEditorContextDisplayInfo (UWorld *InWorld, FActorEditorContextClientDisplayInfo &OutDiplayInfo) const override
UNREALED_API FFolder GetActorEditorContextFolder (UWorld &InWorld, bool bMustMatchCurrentLevel=true) const
virtual TSharedRef< SWidget > GetActorEditorContextWidget (UWorld *InWorld) const override
UNREALED_API FFolder GetDefaultFolderForSelection (UWorld &InWorld, TArray< FFolder > *InSelectedFolders=nullptr)
Get a new default folder name that would apply to the current selection.
UNREALED_API FFolder GetDefaultFolderName (UWorld &InWorld, const FFolder &InParentFolder)
Get a default folder name under the specified parent path.
UNREALED_API FFolder GetFolderName (UWorld &InWorld, const FFolder &InParentFolder, const FName &InLeafName)
Get folder name that is unique under specified parent path.
UNREALED_API FActorFolderProps * GetFolderProperties (UWorld &InWorld, const FFolder &InFolder)
Get the folder properties for the specified path.
virtual FOnActorEditorContextClientChanged & GetOnActorEditorContextClientChanged () override
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
UNREALED_API bool IsFolderExpanded (UWorld &InWorld, const FFolder &InFolder)
Return the folder expansion state.
UNREALED_API bool IsInitializedForWorld (UWorld &InWorld) const
Tests whether a folder container exists for the specified world.
virtual void OnExecuteActorEditorContextAction (UWorld *InWorld, const EActorEditorContextAction &InType, class AActor *InActor=nullptr) override
UNREALED_API void OnFolderRootObjectRemoved (UWorld &InWorld, const FFolder::FRootObject &InFolderRootObject)
Notify that a root object has been removed.
UNREALED_API bool RenameFolderInWorld (UWorld &InWorld, const FFolder &OldPath, const FFolder &NewPath)
Rename the specified path to a new name.
virtual void RestoreActorEditorContextState (UWorld *InWorld, const UActorEditorContextStateCollection *InStateCollection) override
UNREALED_API void SetActorEditorContextFolder (UWorld &InWorld, const FFolder &InFolder)
UNREALED_API void SetIsFolderExpanded (UWorld &InWorld, const FFolder &InFolder, bool bIsExpanded)
Set the folder expansion state.
UNREALED_API void SetSelectedFolderPath (const FFolder &InFolder) const
Sets the folder path for all the selected actors.
UE_DEPRECATED (5.0, "CreateFolder using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API void CreateFolder(UWorld &InWorld
UE_DEPRECATED (5.0, "CreateFolderContainingSelection using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API void CreateFolderContainingSelection(UWorld &InWorld
UE_DEPRECATED (5.0, "DeleteFolder using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API void DeleteFolder(UWorld &InWorld
UE_DEPRECATED (5.0, "GetDefaultFolderName using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API FName GetDefaultFolderName(UWorld &InWorld
UE_DEPRECATED (5.0, "GetDefaultFolderNameForSelection using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API FName GetDefaultFolderNameForSelection(UWorld &InWorld)
UE_DEPRECATED (5.0, "GetFolderName using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API FName GetFolderName(UWorld &InWorld
UE_DEPRECATED (5.0, "GetFolderProperties using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API FActorFolderProps *GetFolderProperties(UWorld &InWorld
UE_DEPRECATED (5.0, "OnFolderCreate has been deprecated. Please use OnFolderCreated.") static UNREALED_API FOnActorFolderCreate OnFolderCreate
UE_DEPRECATED (5.0, "OnFolderDelete has been deprecated. Please use OnFolderDeleted.") static UNREALED_API FOnActorFolderDelete OnFolderDelete
UE_DEPRECATED (5.0, "OnFolderMove has been deprecated. Please use OnFolderMoved.") static UNREALED_API FOnActorFolderMove OnFolderMove
UE_DEPRECATED (5.0, "RenameFolderInWorld using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API bool RenameFolderInWorld(UWorld &World
UE_DEPRECATED (5.0, "SetSelectedFolderPath using FName has been deprecated. Please use new interface using FFolder.") UNREALED_API void SetSelectedFolderPath(FName Path) const
UE_DEPRECATED (5.4, "Please use ForEachActorDescInstanceInFolders") static UNREALED_API void ForEachActorDescInFolders(UWorld &InWorld
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Member Functions
static UNREALED_API void ForEachActorDescInstanceInFolders (UWorld &InWorld, const TSet< FName > &InPaths, TFunctionRef< bool(const FWorldPartitionActorDescInstance *)> Operation, const FFolder::FRootObject &InFolderRootObject=FFolder::GetInvalidRootObject())
Apply an operation to each actor desc in the given list of folders.
static UNREALED_API void ForEachActorInFolders (UWorld &InWorld, const TArray< FName > &InPaths, TFunctionRef< bool(AActor *)> Operation, const FFolder::FRootObject &InFolderRootObject=FFolder::GetInvalidRootObject())
Apply an operation to each actor in the given list of folders.
static UNREALED_API void ForEachActorInFolders (UWorld &InWorld, const TSet< FName > &InPaths, TFunctionRef< bool(AActor *)> Operation, const FFolder::FRootObject &InFolderRootObject=FFolder::GetInvalidRootObject())
static UNREALED_API FActorFolders & Get ()
Singleton access.
static UNREALED_API void GetActorsFromFolders (UWorld &InWorld, const TArray< FName > &InPaths, TArray< AActor * > &OutActors, const FFolder::FRootObject &InFolderRootObject=FFolder::GetInvalidRootObject())
Get an array of actors from a list of folders.
static UNREALED_API void GetActorsFromFolders (UWorld &InWorld, const TSet< FName > &InPaths, TArray< AActor * > &OutActors, const FFolder::FRootObject &InFolderRootObject=FFolder::GetInvalidRootObject())
static UNREALED_API void GetWeakActorsFromFolders (UWorld &InWorld, const TArray< FName > &InPaths, TArray< TWeakObjectPtr< AActor > > &OutActors, const FFolder::FRootObject &InFolderRootObject=FFolder::GetInvalidRootObject())
Get an array of weak actor pointers from a list of folders.
static UNREALED_API void GetWeakActorsFromFolders (UWorld &InWorld, const TSet< FName > &InPaths, TArray< TWeakObjectPtr< AActor > > &OutActors, const FFolder::FRootObject &InFolderRootObject=FFolder::GetInvalidRootObject())
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Data Fields
FName FName FolderName
FName FolderToDelete
const TSet< FName > TFunctionRef< bool(const FWorldPartitionActorDesc *)> const FFolder::FRootObject & InFolderRootObject
FName InPath
const TSet< FName > & InPaths
FName FName NewPath
FName OldPath
const TSet< FName > TFunctionRef< bool(const FWorldPartitionActorDesc *)> Operation
FName ParentPath = FName())
FName Path
Static Public Attributes
static UNREALED_API FOnActorFolderCreated OnFolderCreated
Folder creation and deletion events.
static UNREALED_API FOnActorFolderDeleted OnFolderDeleted
static UNREALED_API FOnActorFolderMoved OnFolderMoved
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Private Member Functions
UNREALED_API bool AddFolderToWorld (UWorld &InWorld, const FFolder &InFolder)
Add a folder to the folder map for the specified world.
UNREALED_API void BroadcastOnActorEditorContextClientChanged (UWorld &InWorld)
Called when ActorEditorContextClient changed.
UNREALED_API void BroadcastOnActorFolderCreated (UWorld &InWorld, const FFolder &InFolder)
Broadcast when actor folder is created.
UNREALED_API void BroadcastOnActorFolderDeleted (UWorld &InWorld, const FFolder &InFolder)
Broadcast when actor folder is deleted.
UNREALED_API void BroadcastOnActorFolderMoved (UWorld &InWorld, const FFolder &InSrcFolder, const FFolder &InDstFolder)
Broadcast when actor folder has moved.
UNREALED_API UWorldFolders & CreateWorldFolders (UWorld &InWorld)
Create and update a folder container for the specified world.
UNREALED_API UWorldFolders & GetOrCreateWorldFolders (UWorld &InWorld)
Get or create a folder container for the specified world.
UNREALED_API void Housekeeping ()
Remove any references to folder arrays for dead worlds.
UNREALED_API void OnActorFolderAdded (UActorFolder *InActorFolder)
Called when an actor folder is added.
UNREALED_API void OnActorFolderChanged (const AActor *InActor, FName OldPath)
Called when an actor's folder has changed.
UNREALED_API void OnAllLevelsChanged ()
Called when all the levels have been changed.
UNREALED_API void OnLevelActorListChanged ()
Called when the actor list of the current world has changed.
UNREALED_API void OnMapChange (uint32 MapChangeFlags)
Called when the global map in the editor has changed.
UNREALED_API void OnWorldSaved (UWorld *World, FObjectPostSaveContext ObjectSaveContext)
Called after a world has been saved.
UNREALED_API void RebuildFolderListForWorld (UWorld &InWorld)
Rebuild the folder list for the specified world.
UNREALED_API void RemoveFoldersFromWorld (UWorld &InWorld, const TArray< FFolder > &InFolders, bool bBroadcastDelete)
Removed folders from specified world.
UNREALED_API void SaveWorldFoldersState (UWorld *World)
Attempt to save the folders state.
Static Private Member Functions
static UNREALED_API FFolder::FRootObject GetWorldFolderRootObject (UWorld &InWorld)
Private Attributes
FOnActorEditorContextClientChanged ActorEditorContextClientChanged
Delegate used to notify changes to ActorEditorContextSubsystem.
bool bAnyLevelsChanged
friend UWorldFolders
TMap< TWeakObjectPtr< UWorld >, TObjectPtr< UWorldFolders > > WorldFolders
Transient map of folders, keyed on world pointer.
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Detailed Description
Class responsible for managing an in-memory representation of actor folders in the editor.
Definition at line 46 of file EditorActorFolders.h.
Constructor & Destructor Documentation
FActorFolders()
UNREALED_API FActorFolders::FActorFolders ()
Referenced by Get().
~FActorFolders()
UNREALED_API FActorFolders::~FActorFolders ()
Member Function Documentation
AddFolderToWorld()
UNREALED_API bool FActorFolders::AddFolderToWorld (UWorld & InWorld, const FFolder & InFolder) private
Add a folder to the folder map for the specified world.
Does not trigger any events.
AddReferencedObjects()
virtual UNREALED_API void FActorFolders::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
BroadcastOnActorEditorContextClientChanged()
UNREALED_API void FActorFolders::BroadcastOnActorEditorContextClientChanged (UWorld & InWorld) private
Called when ActorEditorContextClient changed.
BroadcastOnActorFolderCreated()
UNREALED_API void FActorFolders::BroadcastOnActorFolderCreated (UWorld & InWorld, const FFolder & InFolder) private
Broadcast when actor folder is created.
BroadcastOnActorFolderDeleted()
UNREALED_API void FActorFolders::BroadcastOnActorFolderDeleted (UWorld & InWorld, const FFolder & InFolder) private
Broadcast when actor folder is deleted.
BroadcastOnActorFolderMoved()
UNREALED_API void FActorFolders::BroadcastOnActorFolderMoved (UWorld & InWorld, const FFolder & InSrcFolder, const FFolder & InDstFolder) private
Broadcast when actor folder has moved.
CanResetContext()
virtual bool FActorFolders::CanResetContext (UWorld * InWorld) const inline override virtual
Implements IActorEditorContextClient.
Definition at line 182 of file EditorActorFolders.h.
CaptureActorEditorContextState()
virtual void FActorFolders::CaptureActorEditorContextState (UWorld * InWorld, UActorEditorContextStateCollection * InStateCollection) const override virtual
Implements IActorEditorContextClient.
ContainsFolder()
UNREALED_API bool FActorFolders::ContainsFolder (UWorld & InWorld, const FFolder & InFolder)
Return if folder exists.
CreateFolder()
UNREALED_API bool FActorFolders::CreateFolder (UWorld & InWorld, const FFolder & InFolder)
Create a new folder in the specified world, of the specified path.
CreateFolderContainingSelection()
UNREALED_API void FActorFolders::CreateFolderContainingSelection (UWorld & InWorld, const FFolder & InFolder)
Same as CreateFolder, but moves the current actor selection into the new folder as well.
Referenced by UE_DEPRECATED().
CreateWorldFolders()
UNREALED_API UWorldFolders & FActorFolders::CreateWorldFolders (UWorld & InWorld) private
Create and update a folder container for the specified world.
References UWorldFolders.
DeleteFolder()
UNREALED_API void FActorFolders::DeleteFolder (UWorld & InWorld, const FFolder & InFolderToDelete)
Delete the specified folder in the world.
ForEachActorDescInstanceInFolders()
UNREALED_API void FActorFolders::ForEachActorDescInstanceInFolders (UWorld & InWorld, const TSet< FName > & InPaths, TFunctionRef< bool(const FWorldPartitionActorDescInstance *)> Operation, const FFolder::FRootObject & InFolderRootObject = FFolder::GetInvalidRootObject()) static
Apply an operation to each actor desc in the given list of folders.
References FFolder::GetInvalidRootObject(), InFolderRootObject, InPaths, and Operation.
ForEachActorInFolders() [1/2]
UNREALED_API void FActorFolders::ForEachActorInFolders (UWorld & InWorld, const TArray< FName > & InPaths, TFunctionRef< bool(AActor *)> Operation, const FFolder::FRootObject & InFolderRootObject = FFolder::GetInvalidRootObject()) static
Apply an operation to each actor in the given list of folders.
Will stop when operation returns false.
References FFolder::GetInvalidRootObject(), InFolderRootObject, InPaths, and Operation.
ForEachActorInFolders() [2/2]
UNREALED_API void FActorFolders::ForEachActorInFolders (UWorld & InWorld, const TSet< FName > & InPaths, TFunctionRef< bool(AActor *)> Operation, const FFolder::FRootObject & InFolderRootObject = FFolder::GetInvalidRootObject()) static
References FFolder::GetInvalidRootObject(), InFolderRootObject, InPaths, and Operation.
ForEachFolder()
UNREALED_API void FActorFolders::ForEachFolder (UWorld & InWorld, TFunctionRef< bool(const FFolder &)> Operation)
Iterate on all folders of a world and pass it to the provided operation.
References Operation.
ForEachFolderWithRootObject()
UNREALED_API void FActorFolders::ForEachFolderWithRootObject (UWorld & InWorld, const FFolder::FRootObject & InFolderRootObject, TFunctionRef< bool(const FFolder &)> Operation)
Iterate on all world's folders with the given root object and pass it to the provided operation.
References InFolderRootObject, and Operation.
Get()
UNREALED_API FActorFolders & FActorFolders::Get () static
Singleton access.
References FActorFolders().
GetActorEditorContextDisplayInfo()
virtual bool FActorFolders::GetActorEditorContextDisplayInfo (UWorld * InWorld, FActorEditorContextClientDisplayInfo & OutDiplayInfo) const override virtual
Implements IActorEditorContextClient.
GetActorEditorContextFolder()
UNREALED_API FFolder FActorFolders::GetActorEditorContextFolder (UWorld & InWorld, bool bMustMatchCurrentLevel = true) const
GetActorEditorContextWidget()
virtual TSharedRef< SWidget > FActorFolders::GetActorEditorContextWidget (UWorld * InWorld) const override virtual
Implements IActorEditorContextClient.
GetActorsFromFolders() [1/2]
UNREALED_API void FActorFolders::GetActorsFromFolders (UWorld & InWorld, const TArray< FName > & InPaths, TArray< AActor * > & OutActors, const FFolder::FRootObject & InFolderRootObject = FFolder::GetInvalidRootObject()) static
Get an array of actors from a list of folders.
References FFolder::GetInvalidRootObject(), InFolderRootObject, and InPaths.
GetActorsFromFolders() [2/2]
UNREALED_API void FActorFolders::GetActorsFromFolders (UWorld & InWorld, const TSet< FName > & InPaths, TArray< AActor * > & OutActors, const FFolder::FRootObject & InFolderRootObject = FFolder::GetInvalidRootObject()) static
References FFolder::GetInvalidRootObject(), InFolderRootObject, and InPaths.
GetDefaultFolderForSelection()
UNREALED_API FFolder FActorFolders::GetDefaultFolderForSelection (UWorld & InWorld, TArray< FFolder > * InSelectedFolders = nullptr)
Get a new default folder name that would apply to the current selection.
GetDefaultFolderName()
UNREALED_API FFolder FActorFolders::GetDefaultFolderName (UWorld & InWorld, const FFolder & InParentFolder)
Get a default folder name under the specified parent path.
GetFolderName()
UNREALED_API FFolder FActorFolders::GetFolderName (UWorld & InWorld, const FFolder & InParentFolder, const FName & InLeafName)
Get folder name that is unique under specified parent path.
GetFolderProperties()
UNREALED_API FActorFolderProps * FActorFolders::GetFolderProperties (UWorld & InWorld, const FFolder & InFolder)
Get the folder properties for the specified path.
Returns nullptr if no properties exist
GetOnActorEditorContextClientChanged()
virtual FOnActorEditorContextClientChanged & FActorFolders::GetOnActorEditorContextClientChanged () inline override virtual
Implements IActorEditorContextClient.
Definition at line 184 of file EditorActorFolders.h.
References ActorEditorContextClientChanged.
GetOrCreateWorldFolders()
UNREALED_API UWorldFolders & FActorFolders::GetOrCreateWorldFolders (UWorld & InWorld) private
Get or create a folder container for the specified world.
References UWorldFolders.
GetReferencerName()
virtual FString FActorFolders::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 53 of file EditorActorFolders.h.
GetWeakActorsFromFolders() [1/2]
UNREALED_API void FActorFolders::GetWeakActorsFromFolders (UWorld & InWorld, const TArray< FName > & InPaths, TArray< TWeakObjectPtr< AActor > > & OutActors, const FFolder::FRootObject & InFolderRootObject = FFolder::GetInvalidRootObject()) static
Get an array of weak actor pointers from a list of folders.
References FFolder::GetInvalidRootObject(), InFolderRootObject, and InPaths.
GetWeakActorsFromFolders() [2/2]
UNREALED_API void FActorFolders::GetWeakActorsFromFolders (UWorld & InWorld, const TSet< FName > & InPaths, TArray< TWeakObjectPtr< AActor > > & OutActors, const FFolder::FRootObject & InFolderRootObject = FFolder::GetInvalidRootObject()) static
References FFolder::GetInvalidRootObject(), InFolderRootObject, and InPaths.
GetWorldFolderRootObject()
UNREALED_API FFolder::FRootObject FActorFolders::GetWorldFolderRootObject (UWorld & InWorld) static private
Housekeeping()
UNREALED_API void FActorFolders::Housekeeping () private
Remove any references to folder arrays for dead worlds.
IsFolderExpanded()
UNREALED_API bool FActorFolders::IsFolderExpanded (UWorld & InWorld, const FFolder & InFolder)
Return the folder expansion state.
IsInitializedForWorld()
UNREALED_API bool FActorFolders::IsInitializedForWorld (UWorld & InWorld) const
Tests whether a folder container exists for the specified world.
OnActorFolderAdded()
UNREALED_API void FActorFolders::OnActorFolderAdded (UActorFolder * InActorFolder) private
Called when an actor folder is added.
OnActorFolderChanged()
UNREALED_API void FActorFolders::OnActorFolderChanged (const AActor * InActor, FName OldPath) private
Called when an actor's folder has changed.
References OldPath.
OnAllLevelsChanged()
UNREALED_API void FActorFolders::OnAllLevelsChanged () private
Called when all the levels have been changed.
OnExecuteActorEditorContextAction()
virtual void FActorFolders::OnExecuteActorEditorContextAction (UWorld * InWorld, const EActorEditorContextAction & InType, class AActor * InActor = nullptr) override virtual
Implements IActorEditorContextClient.
OnFolderRootObjectRemoved()
UNREALED_API void FActorFolders::OnFolderRootObjectRemoved (UWorld & InWorld, const FFolder::FRootObject & InFolderRootObject)
Notify that a root object has been removed.
Cleanup of existing folders with with root object.
References InFolderRootObject.
OnLevelActorListChanged()
UNREALED_API void FActorFolders::OnLevelActorListChanged () private
Called when the actor list of the current world has changed.
OnMapChange()
UNREALED_API void FActorFolders::OnMapChange (uint32 MapChangeFlags) private
Called when the global map in the editor has changed.
OnWorldSaved()
UNREALED_API void FActorFolders::OnWorldSaved (UWorld * World, FObjectPostSaveContext ObjectSaveContext) private
Called after a world has been saved.
RebuildFolderListForWorld()
UNREALED_API void FActorFolders::RebuildFolderListForWorld (UWorld & InWorld) private
Rebuild the folder list for the specified world.
This can be very slow as it iterates all actors in memory to rebuild the array of actors for this world
RemoveFoldersFromWorld()
UNREALED_API void FActorFolders::RemoveFoldersFromWorld (UWorld & InWorld, const TArray< FFolder > & InFolders, bool bBroadcastDelete) private
Removed folders from specified world.
Can optionally trigger delete events.
RenameFolderInWorld()
UNREALED_API bool FActorFolders::RenameFolderInWorld (UWorld & InWorld, const FFolder & OldPath, const FFolder & NewPath)
Rename the specified path to a new name.
References NewPath, and OldPath.
RestoreActorEditorContextState()
virtual void FActorFolders::RestoreActorEditorContextState (UWorld * InWorld, const UActorEditorContextStateCollection * InStateCollection) override virtual
Implements IActorEditorContextClient.
SaveWorldFoldersState()
UNREALED_API void FActorFolders::SaveWorldFoldersState (UWorld * World) private
Attempt to save the folders state.
SetActorEditorContextFolder()
UNREALED_API void FActorFolders::SetActorEditorContextFolder (UWorld & InWorld, const FFolder & InFolder)
SetIsFolderExpanded()
UNREALED_API void FActorFolders::SetIsFolderExpanded (UWorld & InWorld, const FFolder & InFolder, bool bIsExpanded)
Set the folder expansion state.
SetSelectedFolderPath()
UNREALED_API void FActorFolders::SetSelectedFolderPath (const FFolder & InFolder) const
Sets the folder path for all the selected actors.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/13]
FActorFolders::UE_DEPRECATED (5. 0, "CreateFolder using FName has been deprecated. Please use new interface using FFolder.") &
References UE_DEPRECATED().
UE_DEPRECATED() [2/13]
FActorFolders::UE_DEPRECATED (5. 0, "CreateFolderContainingSelection using FName has been deprecated. Please use new interface using FFolder.") &
References CreateFolderContainingSelection(), Path, and UE_DEPRECATED().
UE_DEPRECATED() [3/13]
FActorFolders::UE_DEPRECATED (5. 0, "DeleteFolder using FName has been deprecated. Please use new interface using FFolder.") &
References UE_DEPRECATED().
UE_DEPRECATED() [4/13]
FActorFolders::UE_DEPRECATED (5. 0, "GetDefaultFolderName using FName has been deprecated. Please use new interface using FFolder.") &
References UE_DEPRECATED().
UE_DEPRECATED() [5/13]
FActorFolders::UE_DEPRECATED (5. 0, "GetDefaultFolderNameForSelection using FName has been deprecated. Please use new interface using FFolder.") &
References UE_DEPRECATED().
UE_DEPRECATED() [6/13]
FActorFolders::UE_DEPRECATED (5. 0, "GetFolderName using FName has been deprecated. Please use new interface using FFolder.") &
References UE_DEPRECATED().
UE_DEPRECATED() [7/13]
FActorFolders::UE_DEPRECATED (5. 0, "GetFolderProperties using FName has been deprecated. Please use new interface using FFolder.") &
References UE_DEPRECATED().
UE_DEPRECATED() [8/13]
FActorFolders::UE_DEPRECATED (5. 0, "OnFolderCreate has been deprecated. Please use OnFolderCreated.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [9/13]
FActorFolders::UE_DEPRECATED (5. 0, "OnFolderDelete has been deprecated. Please use OnFolderDeleted.")
References UE_DEPRECATED().
UE_DEPRECATED() [10/13]
FActorFolders::UE_DEPRECATED (5. 0, "OnFolderMove has been deprecated. Please use OnFolderMoved.")
References UE_DEPRECATED().
UE_DEPRECATED() [11/13]
FActorFolders::UE_DEPRECATED (5. 0, "RenameFolderInWorld using FName has been deprecated. Please use new interface using FFolder.") &
References UE_DEPRECATED().
UE_DEPRECATED() [12/13]
FActorFolders::UE_DEPRECATED (5. 0, "SetSelectedFolderPath using FName has been deprecated. Please use new interface using FFolder.") const
References Path, SetSelectedFolderPath(), and UE_DEPRECATED().
UE_DEPRECATED() [13/13]
FActorFolders::UE_DEPRECATED (5. 4, "Please use ForEachActorDescInstanceInFolders") &
References UE_DEPRECATED().
Field Documentation
ActorEditorContextClientChanged
FOnActorEditorContextClientChanged FActorFolders::ActorEditorContextClientChanged private
Delegate used to notify changes to ActorEditorContextSubsystem.
Definition at line 249 of file EditorActorFolders.h.
Referenced by GetOnActorEditorContextClientChanged().
bAnyLevelsChanged
bool FActorFolders::bAnyLevelsChanged private
Definition at line 251 of file EditorActorFolders.h.
FolderName
FName FName FActorFolders::FolderName
Definition at line 88 of file EditorActorFolders.h.
FolderToDelete
FName FActorFolders::FolderToDelete
Definition at line 100 of file EditorActorFolders.h.
InFolderRootObject
const TSet<FName> TFunctionRef<bool(const FWorldPartitionActorDesc*)> const FFolder::FRootObject& FActorFolders::InFolderRootObject
Initial value:
= FFolder::GetInvalidRootObject()) {}
    UE_DEPRECATED(5.4, "Please use GetActorDescInstanceFolder")
    static UNREALED_API FFolder GetActorDescFolder(UWorld& InWorld, const FWorldPartitionActorDesc* InActorDesc) { return FFolder::GetInvalidFolder(); }
    static UNREALED_API FFolder GetActorDescInstanceFolder(UWorld& InWorld, const FWorldPartitionActorDescInstance* InActorDescInstance)
Definition at line 106 of file EditorActorFolders.h.
Referenced by ForEachActorDescInstanceInFolders(), ForEachActorInFolders(), ForEachActorInFolders(), ForEachFolderWithRootObject(), GetActorsFromFolders(), GetActorsFromFolders(), GetWeakActorsFromFolders(), GetWeakActorsFromFolders(), and OnFolderRootObjectRemoved().
InPath
FName FActorFolders::InPath
Definition at line 79 of file EditorActorFolders.h.
InPaths
const TSet<FName>& FActorFolders::InPaths
Definition at line 106 of file EditorActorFolders.h.
Referenced by ForEachActorDescInstanceInFolders(), ForEachActorInFolders(), ForEachActorInFolders(), GetActorsFromFolders(), GetActorsFromFolders(), GetWeakActorsFromFolders(), and GetWeakActorsFromFolders().
NewPath
FName FName FActorFolders::NewPath
Definition at line 103 of file EditorActorFolders.h.
Referenced by RenameFolderInWorld().
OldPath
FName FActorFolders::OldPath
Definition at line 103 of file EditorActorFolders.h.
Referenced by OnActorFolderChanged(), and RenameFolderInWorld().
OnFolderCreated
UNREALED_API FOnActorFolderCreated FActorFolders::OnFolderCreated static
Folder creation and deletion events.
Called whenever a folder is created or deleted in a world.
Definition at line 63 of file EditorActorFolders.h.
OnFolderDeleted
UNREALED_API FOnActorFolderDeleted FActorFolders::OnFolderDeleted static
Definition at line 65 of file EditorActorFolders.h.
OnFolderMoved
UNREALED_API FOnActorFolderMoved FActorFolders::OnFolderMoved static
Definition at line 64 of file EditorActorFolders.h.
Operation
const TSet<FName> TFunctionRef<bool(const FWorldPartitionActorDesc*)> FActorFolders::Operation
Definition at line 106 of file EditorActorFolders.h.
Referenced by ForEachActorDescInstanceInFolders(), ForEachActorInFolders(), ForEachActorInFolders(), ForEachFolder(), and ForEachFolderWithRootObject().
ParentPath
FName FActorFolders::ParentPath = FName())
Definition at line 82 of file EditorActorFolders.h.
Path
FName FActorFolders::Path
Definition at line 91 of file EditorActorFolders.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UWorldFolders
friend FActorFolders::UWorldFolders private
Definition at line 253 of file EditorActorFolders.h.
Referenced by CreateWorldFolders(), and GetOrCreateWorldFolders().
WorldFolders
TMap<TWeakObjectPtr<UWorld>, TObjectPtr<UWorldFolders> > FActorFolders::WorldFolders private
Transient map of folders, keyed on world pointer.
Definition at line 243 of file EditorActorFolders.h.
The documentation for this struct was generated from the following file:
EditorActorFolders.h