Unreal Engine 5.6 C++ API: FStructuredArchiveFromArchive Class Reference
FStructuredArchiveFromArchive Class Reference
#include "StructuredArchiveAdapters.h"
Public Member Functions
FStructuredArchiveFromArchive (FArchive &Ar)
~FStructuredArchiveFromArchive ()
FStructuredArchiveSlot GetSlot ()
Private Member Functions
UE_NONCOPYABLE (FStructuredArchiveFromArchive) static const expr inline uint32 ImplSize
Private Attributes
uint8 ImplStorage [ImplSize]
Static Private Attributes
static constexpr uint32 ImplAlignment = 8
Detailed Description
Definition at line 12 of file StructuredArchiveAdapters.h.
Constructor & Destructor Documentation
FStructuredArchiveFromArchive()
FStructuredArchiveFromArchive::FStructuredArchiveFromArchive (FArchive & Ar) explicit
References Ar.
Referenced by UE_NONCOPYABLE().
~FStructuredArchiveFromArchive()
FStructuredArchiveFromArchive::~FStructuredArchiveFromArchive ()
Member Function Documentation
GetSlot()
FStructuredArchiveSlot FStructuredArchiveFromArchive::GetSlot ()
Referenced by FConfigValue::operator<<, FPackageIndex::operator<<, and operator<<().
UE_NONCOPYABLE()
FStructuredArchiveFromArchive::UE_NONCOPYABLE (FStructuredArchiveFromArchive) const private
References FStructuredArchiveFromArchive().
Field Documentation
ImplAlignment
uint32 FStructuredArchiveFromArchive::ImplAlignment = 8 inline static constexpr private
Definition at line 17 of file StructuredArchiveAdapters.h.
ImplStorage
uint8 FStructuredArchiveFromArchive::ImplStorage[ImplSize] private
Definition at line 29 of file StructuredArchiveAdapters.h.
The documentation for this class was generated from the following file:
StructuredArchiveAdapters.h