Unreal Engine 5.6 C++ API: TLockFreePointerListLIFOPad< T, TPaddingForCacheContention > Class Template Reference
TLockFreePointerListLIFOPad< T, TPaddingForCacheContention > Class Template Reference
#include "LockFreeList.h"
Public Member Functions
FORCEINLINE bool IsEmpty () const
Check if the list is empty.
T * Pop ()
Pop an item from the list or return NULL if the list is empty.
template<typename ContainerType>
void PopAll (ContainerType &Output)
Pop all items from the list.
template<typename FunctorType>
void PopAllAndApply (FunctorType InFunctor)
Pop all items from the list and call a functor for each of them.
void Push (T *NewItem)
Push an item onto the head of the list.
Additional Inherited Members
Private Member Functions inherited from FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >
FLockFreePointerListLIFOBase ()=default
~FLockFreePointerListLIFOBase ()
FORCEINLINE uint64 GetState () const
FORCEINLINE bool IsEmpty () const
T * Pop ()
template<typename ContainerType>
void PopAll (ContainerType &OutContainer)
template<typename FunctorType>
void PopAllAndApply (FunctorType InFunctor)
template<typename ContainerType>
void PopAllAndChangeState (ContainerType &OutContainer, TFunctionRef< uint64(uint64)> StateChange)
void Push (T *InPayload)
bool PushIf (T *InPayload, TFunctionRef< bool(uint64)> OkToPush)
void Reset ()
Detailed Description
template<class T, int TPaddingForCacheContention>
class TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >
Definition at line 840 of file LockFreeList.h.
Member Function Documentation
IsEmpty()
template<class T, int TPaddingForCacheContention> FORCEINLINE bool TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::IsEmpty () const inline nodiscard
Check if the list is empty.
Returns
true if the list is empty. CAUTION: This methods safety depends on external assumptions. For example, if another thread could add to the list at any time, the return value is no better than a best guess. As typically used, the list is not being access concurrently when this is called.
Definition at line 890 of file LockFreeList.h.
References FORCEINLINE, and FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::IsEmpty().
Pop()
template<class T, int TPaddingForCacheContention> T * TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::Pop () inline nodiscard
Pop an item from the list or return NULL if the list is empty.
Returns
The popped item, if any.
Definition at line 858 of file LockFreeList.h.
References FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop().
PopAll()
template<class T, int TPaddingForCacheContention> template<typename ContainerType> void TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::PopAll (ContainerType & Output) inline
Pop all items from the list.
Parameters
Output The array to hold the returned items. Must be empty.
Definition at line 869 of file LockFreeList.h.
References FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAll().
PopAllAndApply()
template<class T, int TPaddingForCacheContention> template<typename FunctorType> void TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::PopAllAndApply (FunctorType InFunctor) inline
Pop all items from the list and call a functor for each of them.
Definition at line 878 of file LockFreeList.h.
References FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndApply().
Push()
template<class T, int TPaddingForCacheContention> void TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::Push (T * NewItem) inline
Push an item onto the head of the list.
Parameters
NewItem,the new item to push on the list, cannot be NULL.
Definition at line 849 of file LockFreeList.h.
References FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Push().
The documentation for this class was generated from the following file:
LockFreeList.h