Unreal Engine 5.6 C++ API: UE::Logging::Private::FLogContext Struct Reference
UE::Logging::Private::FLogContext Struct Reference
#include "StructuredLog.h"
Public Member Functions
FLogContext (const ANSICHAR *Name)
template<typename ValueType>
FLogContext (const ANSICHAR *Name, const ValueType &Value)
FLogContext (const FLogContext &)=delete
FLogContext (const FLogField &Field)
~FLogContext ()
FLogContext & operator= (const FLogContext &)=delete
Data Fields
bool bDisabledByNewerContext = false
bool bDisabledOlderContext = false
FCbField Field
FLogContext * Next = nullptr
FLogContext * Prev = nullptr
Detailed Description
Definition at line 503 of file StructuredLog.h.
Constructor & Destructor Documentation
FLogContext() [1/4]
UE::Logging::Private::FLogContext::FLogContext (const ANSICHAR * Name) inline explicit
Definition at line 505 of file StructuredLog.h.
References FLogContext(), and Name.
Referenced by FLogContext(), FLogContext(), FLogContext(), and operator=().
FLogContext() [2/4]
template<typename ValueType> UE::Logging::Private::FLogContext::FLogContext (const ANSICHAR * Name, const ValueType & Value) inline explicit
Definition at line 511 of file StructuredLog.h.
References FLogContext(), Name, Value, and UE::Logging::Private::FLogField::Write().
FLogContext() [3/4]
UE::Logging::Private::FLogContext::FLogContext (const FLogField & Field) explicit
References Field, and UE_API.
~FLogContext()
UE::Logging::Private::FLogContext::~FLogContext ()
References UE_API.
FLogContext() [4/4]
UE::Logging::Private::FLogContext::FLogContext (const FLogContext &) delete
References FLogContext().
Member Function Documentation
operator=()
FLogContext & UE::Logging::Private::FLogContext::operator= (const FLogContext &) delete
References FLogContext().
Field Documentation
bDisabledByNewerContext
bool UE::Logging::Private::FLogContext::bDisabledByNewerContext = false
Definition at line 525 of file StructuredLog.h.
bDisabledOlderContext
bool UE::Logging::Private::FLogContext::bDisabledOlderContext = false
Definition at line 526 of file StructuredLog.h.
Field
FCbField UE::Logging::Private::FLogContext::Field
Definition at line 522 of file StructuredLog.h.
Referenced by FLogContext().
Next
FLogContext* UE::Logging::Private::FLogContext::Next = nullptr
Definition at line 523 of file StructuredLog.h.
Prev
FLogContext* UE::Logging::Private::FLogContext::Prev = nullptr
Definition at line 524 of file StructuredLog.h.
The documentation for this struct was generated from the following file:
StructuredLog.h