Unreal Engine 5.6 C++ API: TIndependentTickReplicator_Server< InModelDef > Class Template Reference
TIndependentTickReplicator_Server< InModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Public Types
using InputType = typename StateTypes::InputType
using ModelDef = InModelDef
using StateTypes = typename ModelDef::StateTypes
Static Public Member Functions
static void NetRecv (const FNetSerializeParams &P, TServerRecvData_Independent< ModelDef > &ServerRecvData, TModelDataStore< ModelDef > *DataStore)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, FVariableTickState *TickState)
static void SetNumInputsPerSend (int32 NumToSend)
Static Private Member Functions
static void EatCmd (const FNetSerializeParams &P)
Static Private Attributes
static int32 NumInputsPerSend = 6
Detailed Description
template<typename InModelDef>
class TIndependentTickReplicator_Server< InModelDef >
Definition at line 215 of file NetworkPredictionSerialization.h.
Member Typedef Documentation
InputType
template<typename InModelDef> using TIndependentTickReplicator_Server< InModelDef >::InputType = typename StateTypes::InputType
Definition at line 222 of file NetworkPredictionSerialization.h.
ModelDef
template<typename InModelDef> using TIndependentTickReplicator_Server< InModelDef >::ModelDef = InModelDef
Definition at line 219 of file NetworkPredictionSerialization.h.
StateTypes
template<typename InModelDef> using TIndependentTickReplicator_Server< InModelDef >::StateTypes = typename ModelDef::StateTypes
Definition at line 221 of file NetworkPredictionSerialization.h.
Member Function Documentation
EatCmd()
template<typename InModelDef> void TIndependentTickReplicator_Server< InModelDef >::EatCmd (const FNetSerializeParams & P) inline static private
Definition at line 333 of file NetworkPredictionSerialization.h.
References FNetSerializeParams::Ar, Empty, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), and FNetworkPredictionSerialization::SerializeDeltaMS().
Referenced by NetRecv(), and NetSend().
NetRecv()
template<typename InModelDef> void TIndependentTickReplicator_Server< InModelDef >::NetRecv (const FNetSerializeParams & P, TServerRecvData_Independent< ModelDef > & ServerRecvData, TModelDataStore< ModelDef > * DataStore) inline static
Definition at line 232 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, TServerRecvData_Independent< ModelDef >::FFrame::DeltaTimeMS, EatCmd(), EndFrame, TServerRecvData_Independent< ModelDef >::InputBuffer, TServerRecvData_Independent< ModelDef >::FFrame::InputCmd, TServerRecvData_Independent< ModelDef >::LastConsumedFrame, TServerRecvData_Independent< ModelDef >::LastRecvFrame, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, npEnsure, NumInputsPerSend, TServerRecvData_Independent< ModelDef >::PendingFrame, FNetworkPredictionSerialization::ReadCompressedFrame(), FNetworkPredictionSerialization::SerializeDeltaMS(), TServerRecvData_Independent< ModelDef >::TotalSimTimeMS, UE_NP_TRACE_NET_RECV, UE_NP_TRACE_SYSTEM_FAULT, and UE_NP_TRACE_USER_STATE_INPUT.
NetSend()
template<typename InModelDef> void TIndependentTickReplicator_Server< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, FVariableTickState * TickState) inline static
Definition at line 294 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, TInstanceFrameState< ModelDef >::Buffer, EatCmd(), EndFrame, NetworkPredictionCVars::ForceSendDefaultInputCommands(), FVariableTickState::Frames, TModelDataStore< ModelDef >::Frames, ID, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, npCheckSlow, NumInputsPerSend, FVariableTickState::PendingFrame, FNetworkPredictionSerialization::SerializeDeltaMS(), and FNetworkPredictionSerialization::WriteCompressedFrame().
SetNumInputsPerSend()
template<typename InModelDef> void TIndependentTickReplicator_Server< InModelDef >::SetNumInputsPerSend (int32 NumToSend) inline static
Definition at line 224 of file NetworkPredictionSerialization.h.
References NumInputsPerSend.
Field Documentation
NumInputsPerSend
template<typename InModelDef> int32 TIndependentTickReplicator_Server< InModelDef >::NumInputsPerSend = 6 inline static private
Definition at line 342 of file NetworkPredictionSerialization.h.
Referenced by NetRecv(), NetSend(), and SetNumInputsPerSend().
The documentation for this class was generated from the following file:
NetworkPredictionSerialization.h