Unreal Engine 5.6 C++ API: UE::MovieScene::FBoolPropertyTraits Struct Reference
UE::MovieScene::FBoolPropertyTraits Struct Reference
#include "MovieSceneTracksComponentTypes.h"
Data Structures
struct FBoolMetaData
Public Types
using MetaDataType = TPropertyMetaData<FBoolMetaData>
using ParamType = bool
using StorageType = bool
using TraitsType = TDirectPropertyTraits<bool>
Static Public Member Functions
static void GetObjectPropertyValue (const UObject *InObject, FBoolMetaData MetaData, const FCustomPropertyAccessor &BaseCustomAccessor, bool &OutValue)
Property Value Getters.
static void GetObjectPropertyValue (const UObject *InObject, FBoolMetaData MetaData, const FName &PropertyPath, bool &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FBoolMetaData MetaData, FTrackInstancePropertyBindings *PropertyBindings, bool &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FBoolMetaData MetaData, uint16 PropertyOffset, bool &OutValue)
static void SetObjectPropertyValue (UObject *InObject, FBoolMetaData MetaData, const FCustomPropertyAccessor &BaseCustomAccessor, bool InValue)
Property Value Setters.
static void SetObjectPropertyValue (UObject *InObject, FBoolMetaData MetaData, FTrackInstancePropertyBindings *PropertyBindings, bool InValue)
static void SetObjectPropertyValue (UObject *InObject, FBoolMetaData MetaData, uint16 PropertyOffset, bool InValue)
Static Public Attributes
static constexpr bool bIsComposite = false
Detailed Description
Definition at line 502 of file MovieSceneTracksComponentTypes.h.
Member Typedef Documentation
MetaDataType
using UE::MovieScene::FBoolPropertyTraits::MetaDataType = TPropertyMetaData<FBoolMetaData>
Definition at line 513 of file MovieSceneTracksComponentTypes.h.
ParamType
using UE::MovieScene::FBoolPropertyTraits::ParamType = bool
Definition at line 515 of file MovieSceneTracksComponentTypes.h.
StorageType
using UE::MovieScene::FBoolPropertyTraits::StorageType = bool
Definition at line 512 of file MovieSceneTracksComponentTypes.h.
TraitsType
using UE::MovieScene::FBoolPropertyTraits::TraitsType = TDirectPropertyTraits<bool>
Definition at line 514 of file MovieSceneTracksComponentTypes.h.
Member Function Documentation
GetObjectPropertyValue() [1/4]
void UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FBoolMetaData MetaData, const FCustomPropertyAccessor & BaseCustomAccessor, bool & OutValue) inline static
Property Value Getters.
Definition at line 518 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions, and MetaData.
GetObjectPropertyValue() [2/4]
void UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FBoolMetaData MetaData, const FName & PropertyPath, bool & OutValue) inline static
Definition at line 539 of file MovieSceneTracksComponentTypes.h.
References MetaData, MoveTemp(), Property, FTrackInstancePropertyBindings::StaticValue(), and FName::ToString().
GetObjectPropertyValue() [3/4]
void UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FBoolMetaData MetaData, FTrackInstancePropertyBindings * PropertyBindings, bool & OutValue) inline static
Definition at line 535 of file MovieSceneTracksComponentTypes.h.
References FTrackInstancePropertyBindings::GetCurrentValue(), and MetaData.
GetObjectPropertyValue() [4/4]
void UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FBoolMetaData MetaData, uint16 PropertyOffset, bool & OutValue) inline static
Definition at line 523 of file MovieSceneTracksComponentTypes.h.
References MetaData.
SetObjectPropertyValue() [1/3]
void UE::MovieScene::FBoolPropertyTraits::SetObjectPropertyValue (UObject * InObject, FBoolMetaData MetaData, const FCustomPropertyAccessor & BaseCustomAccessor, bool InValue) inline static
Property Value Setters.
Definition at line 549 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions, and MetaData.
SetObjectPropertyValue() [2/3]
void UE::MovieScene::FBoolPropertyTraits::SetObjectPropertyValue (UObject * InObject, FBoolMetaData MetaData, FTrackInstancePropertyBindings * PropertyBindings, bool InValue) inline static
Definition at line 571 of file MovieSceneTracksComponentTypes.h.
References FTrackInstancePropertyBindings::CallFunction(), and MetaData.
SetObjectPropertyValue() [3/3]
void UE::MovieScene::FBoolPropertyTraits::SetObjectPropertyValue (UObject * InObject, FBoolMetaData MetaData, uint16 PropertyOffset, bool InValue) inline static
Definition at line 554 of file MovieSceneTracksComponentTypes.h.
References MetaData.
Field Documentation
bIsComposite
bool UE::MovieScene::FBoolPropertyTraits::bIsComposite = false static constexpr
Definition at line 504 of file MovieSceneTracksComponentTypes.h.
The documentation for this struct was generated from the following file:
MovieSceneTracksComponentTypes.h