Unreal Engine 5.6 C++ API: FCurveEditorScreenSpaceH Struct Reference
FCurveEditorScreenSpaceH Struct Reference
Utility struct used for converting to/from curve editor screen space.
#include "CurveEditorScreenSpace.h"
Public Member Functions
FCurveEditorScreenSpaceH (double InPixelWidth, double InInputMin, double InInputMax)
Construction from a physical size, and input/output range.
FORCEINLINE double GetInputMax () const
Get the maximum input value displayed on the screen.
FORCEINLINE double GetInputMin () const
Get the minimum input value displayed on the screen.
FORCEINLINE double GetPhysicalWidth () const
Get the physical width of the screen.
FORCEINLINE double PixelsPerInput () const
Retrieve the number of slate units per input value.
FORCEINLINE double ScreenToSeconds (double ScreenPosition) const
Convert a horizontal screen position in slate units to a value in seconds.
FORCEINLINE double SecondsToScreen (double InSeconds) const
Convert a value in seconds to a horizontal screen position in slate units.
FCurveEditorScreenSpaceH ToCurveSpace (const FTransform2d &CurveTransform) const
Transform this screen space into a curve space using the specified transform.
Private Attributes
double InputMax
double InputMin
double PixelWidth
Detailed Description
Utility struct used for converting to/from curve editor screen space.
Definition at line 17 of file CurveEditorScreenSpace.h.
Constructor & Destructor Documentation
FCurveEditorScreenSpaceH()
FCurveEditorScreenSpaceH::FCurveEditorScreenSpaceH (double InPixelWidth, double InInputMin, double InInputMax) inline
Construction from a physical size, and input/output range.
Definition at line 22 of file CurveEditorScreenSpace.h.
References InputMax, InputMin, KINDA_SMALL_NUMBER, Max, and PixelWidth.
Referenced by FCurveEditorScreenSpace::FCurveEditorScreenSpace(), FCurveEditorScreenSpace::ToCurveSpace(), and ToCurveSpace().
Member Function Documentation
GetInputMax()
FORCEINLINE double FCurveEditorScreenSpaceH::GetInputMax () const inline
Get the maximum input value displayed on the screen.
Definition at line 60 of file CurveEditorScreenSpace.h.
References FORCEINLINE, and InputMax.
Referenced by FCurveEditorScreenSpace::operator==().
GetInputMin()
FORCEINLINE double FCurveEditorScreenSpaceH::GetInputMin () const inline
Get the minimum input value displayed on the screen.
Definition at line 58 of file CurveEditorScreenSpace.h.
References FORCEINLINE, and InputMin.
GetPhysicalWidth()
FORCEINLINE double FCurveEditorScreenSpaceH::GetPhysicalWidth () const inline
Get the physical width of the screen.
Definition at line 62 of file CurveEditorScreenSpace.h.
References FORCEINLINE, and PixelWidth.
Referenced by FCurveEditorScreenSpace::GetPhysicalSize(), and FCurveEditorScreenSpace::operator==().
PixelsPerInput()
FORCEINLINE double FCurveEditorScreenSpaceH::PixelsPerInput () const inline
Retrieve the number of slate units per input value.
Definition at line 49 of file CurveEditorScreenSpace.h.
References FORCEINLINE, InputMax, InputMin, FMath::Max, and PixelWidth.
Referenced by ScreenToSeconds(), and SecondsToScreen().
ScreenToSeconds()
FORCEINLINE double FCurveEditorScreenSpaceH::ScreenToSeconds (double ScreenPosition) const inline
Convert a horizontal screen position in slate units to a value in seconds.
Definition at line 35 of file CurveEditorScreenSpace.h.
References FORCEINLINE, InputMin, PixelsPerInput(), and ScreenPosition.
SecondsToScreen()
FORCEINLINE double FCurveEditorScreenSpaceH::SecondsToScreen (double InSeconds) const inline
Convert a value in seconds to a horizontal screen position in slate units.
Definition at line 41 of file CurveEditorScreenSpace.h.
References FORCEINLINE, InputMin, and PixelsPerInput().
ToCurveSpace()
FCurveEditorScreenSpaceH FCurveEditorScreenSpaceH::ToCurveSpace (const FTransform2d & CurveTransform) const inline
Transform this screen space into a curve space using the specified transform.
Definition at line 69 of file CurveEditorScreenSpace.h.
References FCurveEditorScreenSpaceH(), TMatrix2x2< T >::GetMatrix(), TTransform2< T >::GetMatrix(), TTransform2< T >::GetTranslation(), InputMax, InputMin, and PixelWidth.
Referenced by FCurveEditorScreenSpace::ToCurveSpace().
Field Documentation
InputMax
double FCurveEditorScreenSpaceH::InputMax private
Definition at line 85 of file CurveEditorScreenSpace.h.
Referenced by FCurveEditorScreenSpaceH(), GetInputMax(), PixelsPerInput(), and ToCurveSpace().
InputMin
double FCurveEditorScreenSpaceH::InputMin private
Definition at line 85 of file CurveEditorScreenSpace.h.
Referenced by FCurveEditorScreenSpaceH(), GetInputMin(), PixelsPerInput(), ScreenToSeconds(), SecondsToScreen(), and ToCurveSpace().
PixelWidth
double FCurveEditorScreenSpaceH::PixelWidth private
Definition at line 84 of file CurveEditorScreenSpace.h.
Referenced by FCurveEditorScreenSpaceH(), GetPhysicalWidth(), PixelsPerInput(), and ToCurveSpace().
The documentation for this struct was generated from the following file:
CurveEditorScreenSpace.h