Unreal Engine 5.6 C++ API: TSplineMeshSceneProxyCommon< TDerived > Class Template Reference
TSplineMeshSceneProxyCommon< TDerived > Class Template Reference abstract
This interface ties common functionality to the two different spline mesh scene proxies without duplicating code or introducing diamond inheritance.
#include "SplineMeshSceneProxy.h"
Public Member Functions
TSplineMeshSceneProxyCommon ()
virtual ~TSplineMeshSceneProxyCommon ()
const FSplineMeshShaderParams & GetSplineMeshParams () const
void SetSplineTextureCoord_RenderThread (uint32 SplineIndex, FUintVector2 TexCoord)
void UpdateSplineMeshParams_RenderThread (const FSplineMeshShaderParams &Params)
Protected Member Functions
void RepackSplineMeshParams (bool bUpdateGPUScene=true)
Protected Attributes
bool bUpdateRayTracingGeometry = true
FRWBuffer RayTracingDynamicVertexBuffer
FSplineMeshSceneInstanceDataBuffers SplineMeshInstanceData
FSplineMeshShaderParams SplineParams
Parameters that define the spline, used to deform mesh.
Private Member Functions
virtual TDerived & Downcast ()=0
implemented by derived to provide access by parent
Detailed Description
template<typename TDerived>
class TSplineMeshSceneProxyCommon< TDerived >
This interface ties common functionality to the two different spline mesh scene proxies without duplicating code or introducing diamond inheritance.
Definition at line 96 of file SplineMeshSceneProxy.h.
Constructor & Destructor Documentation
TSplineMeshSceneProxyCommon()
template<typename TDerived> TSplineMeshSceneProxyCommon< TDerived >::TSplineMeshSceneProxyCommon () inline
Definition at line 99 of file SplineMeshSceneProxy.h.
References INDEX_NONE, FMemory::Memzero(), and SplineParams.
~TSplineMeshSceneProxyCommon()
template<typename TDerived> virtual TSplineMeshSceneProxyCommon< TDerived >::~TSplineMeshSceneProxyCommon () inline virtual
Definition at line 104 of file SplineMeshSceneProxy.h.
Member Function Documentation
Downcast()
template<typename TDerived> virtual TDerived & TSplineMeshSceneProxyCommon< TDerived >::Downcast () private pure virtual
implemented by derived to provide access by parent
Implemented in FNaniteSplineMeshSceneProxy, and FSplineMeshSceneProxy.
Referenced by RepackSplineMeshParams().
GetSplineMeshParams()
template<typename TDerived> const FSplineMeshShaderParams & TSplineMeshSceneProxyCommon< TDerived >::GetSplineMeshParams () const inline
Definition at line 106 of file SplineMeshSceneProxy.h.
References SplineParams.
RepackSplineMeshParams()
template<typename TDerived> void TSplineMeshSceneProxyCommon< TDerived >::RepackSplineMeshParams (bool bUpdateGPUScene = true) inline protected
Definition at line 125 of file SplineMeshSceneProxy.h.
References bUpdateRayTracingGeometry, ChangedOther, Downcast(), SplineMeshInstanceData, and SplineParams.
Referenced by SetSplineTextureCoord_RenderThread(), and UpdateSplineMeshParams_RenderThread().
SetSplineTextureCoord_RenderThread()
template<typename TDerived> void TSplineMeshSceneProxyCommon< TDerived >::SetSplineTextureCoord_RenderThread (uint32 SplineIndex, FUintVector2 TexCoord) inline
Definition at line 108 of file SplineMeshSceneProxy.h.
References check, RepackSplineMeshParams(), and SplineParams.
UpdateSplineMeshParams_RenderThread()
template<typename TDerived> void TSplineMeshSceneProxyCommon< TDerived >::UpdateSplineMeshParams_RenderThread (const FSplineMeshShaderParams & Params) inline
Definition at line 115 of file SplineMeshSceneProxy.h.
References Params, RepackSplineMeshParams(), and SplineParams.
Field Documentation
bUpdateRayTracingGeometry
template<typename TDerived> bool TSplineMeshSceneProxyCommon< TDerived >::bUpdateRayTracingGeometry = true protected
Definition at line 151 of file SplineMeshSceneProxy.h.
Referenced by RepackSplineMeshParams().
RayTracingDynamicVertexBuffer
template<typename TDerived> FRWBuffer TSplineMeshSceneProxyCommon< TDerived >::RayTracingDynamicVertexBuffer protected
Definition at line 152 of file SplineMeshSceneProxy.h.
SplineMeshInstanceData
template<typename TDerived> FSplineMeshSceneInstanceDataBuffers TSplineMeshSceneProxyCommon< TDerived >::SplineMeshInstanceData protected
Definition at line 149 of file SplineMeshSceneProxy.h.
Referenced by RepackSplineMeshParams().
SplineParams
template<typename TDerived> FSplineMeshShaderParams TSplineMeshSceneProxyCommon< TDerived >::SplineParams protected
Parameters that define the spline, used to deform mesh.
Definition at line 147 of file SplineMeshSceneProxy.h.
Referenced by TSplineMeshSceneProxyCommon(), GetSplineMeshParams(), RepackSplineMeshParams(), SetSplineTextureCoord_RenderThread(), and UpdateSplineMeshParams_RenderThread().
The documentation for this class was generated from the following file:
SplineMeshSceneProxy.h