Unreal Engine 5.6 C++ API: FPaths Class Reference
FPaths Class Reference
Path helpers for retrieving game dir, engine dir, etc.
#include "Paths.h"
Public Types
enum class EPathConversion : uint8 {
Engine_PlatformExtension , Engine_NotForLicensees , Engine_NoRedist , Engine_LimitedAccess ,
Project_First , Project_PlatformExtension = Project_First , Project_NotForLicensees , Project_NoRedist ,
Project_LimitedAccess
}
Public Member Functions
UE_DEPRECATED (5.4, "Use EnginePlatformExtensionDir(Platform) instead - ProjectPlatformExtensionsDir did not handle programs properly, so for consistency this is being removed as well") static 1 FString EnginePlatformExtensionsDir()
Returns the directory where engine platform extensions reside.
UE_DEPRECATED (5.4, "Use ProjectPlatformExtensionDir(Platform) instead - this function does not handle Programs properly") static 1 FString ProjectPlatformExtensionsDir()
Returns the directory where the project's platform extensions reside.
UE_DEPRECATED (5.5, "Cooked editor localization path no longer exist. Cooked editors now load game localization paths.") static TArray< FString > GetCookedEditorLocalizationPaths()
Returns a list of cooked editor-specific localization paths.
Static Public Member Functions
static FString AudioCaptureDir ()
Returns the directory the engine uses to output user requested audio capture files.
static FString AutomationDir ()
Returns the directory for automation save files.
static FString AutomationLogDir ()
Returns the directory for automation log files.
static FString AutomationReportsDir ()
Returns the directory for results of automation tests.
static FString AutomationTransientDir ()
Returns the directory for automation save files that are meant to be deleted every run.
static FString BugItDir ()
Returns the directory the engine uses to output BugIt files.
static bool CanGetProjectDir ()
static FString ChangeExtension (const FString &InPath, const FString &InNewExtension)
Changes the extension of the given filename (does nothing if the file has no extension)
static FString CloudDir ()
Returns the directory for local files used in cloud emulation or support.
static bool CollapseRelativeDirectories (FString &InPath)
Takes a fully pathed string and eliminates relative pathing (eg: annihilates ".." with the adjacent directory).
template<typename... PathTypes>
static FORCEINLINE FString Combine (PathTypes &&... InPaths)
static FString ConvertFromSandboxPath (const FString &InPath, const TCHAR *InSandboxName)
Converts a sandbox (in Saved/Sandboxes) path to a normal path.
static FString ConvertPath (const FString &Path, EPathConversion Method, const TCHAR *ExtraData=nullptr, const TCHAR *OverrideProjectDir=nullptr)
Converts a path with the given method.
static FString ConvertRelativePathToFull (const FString &BasePath, const FString &InPath)
Converts a relative path name to a fully qualified name relative to the specified BasePath.
static FString ConvertRelativePathToFull (const FString &BasePath, FString &&InPath)
Converts a relative path name to a fully qualified name relative to the specified BasePath.
static FString ConvertRelativePathToFull (const FString &InPath)
Converts a relative path name to a fully qualified name relative to the process BaseDir().
static FString ConvertRelativePathToFull (FString &&BasePath, const FString &InPath)
Converts a relative path name to a fully qualified name relative to the specified BasePath.
static FString ConvertRelativePathToFull (FString &&BasePath, FString &&InPath)
Converts a relative path name to a fully qualified name relative to the specified BasePath.
static FString ConvertRelativePathToFull (FString &&InPath)
Converts a relative path name to a fully qualified name relative to the process BaseDir().
static FString ConvertToSandboxPath (const FString &InPath, const TCHAR *InSandboxName)
Converts a normal path to a sandbox path (in Saved/Sandboxes).
static FString CreateStandardFilename (const FString &InPath)
Make fully standard "Unreal" pathname:
static FString CreateTempFilename (const TCHAR *Path, const TCHAR *Prefix=TEXT(""), const TCHAR *Extension=TEXT(".tmp"))
Creates a temporary filename with the specified prefix.
static FStringView DevelopersFolderName ()
Returns the name of the subfolder for developer-specific content Example: "Developers".
static FString DiffDir ()
Returns the directory for temp files used for diffing.
static bool DirectoryExists (const FString &InPath)
Returns true if this directory was found, false otherwise.
static FString EngineConfigDir ()
Returns the directory the root configuration files are located.
static FString EngineContentDir ()
Returns the content directory of the "core" engine that can be shared across several games or across games & mods.
static FString EngineDefaultLayoutDir ()
Returns the directory for default Editor UI Layout files of the engine.
static FString EngineDir ()
Returns the base directory of the "core" engine that can be shared across several games or across games & mods.
static FString EngineEditorSettingsDir ()
Returns the Editor Settings directory of the engine.
static FString EngineIntermediateDir ()
Returns the intermediate directory of the engine.
static FString EnginePlatformExtensionDir (const TCHAR *Platform)
Returns the directory where the engine's platform extensions resides for the given platform.
static FString EnginePluginsDir ()
Returns the plugins directory of the engine.
static FString EngineProjectLayoutDir ()
Returns the directory for project Editor UI Layout files of the engine.
static FString EngineSavedDir ()
Returns the saved directory of the engine.
static FString EngineSourceDir ()
Returns the directory where engine source code files are kept.
static FString EngineUserDir ()
Returns the root directory for user-specific engine files.
static FString EngineUserLayoutDir ()
Returns the directory for user-generated Editor UI Layout files of the engine.
static FString EngineVersionAgnosticUserDir ()
Returns the root directory for user-specific engine files which can be shared between versions.
static FString EnterpriseDir ()
Returns the base directory enterprise directory.
static FString EnterpriseFeaturePackDir ()
Returns the enterprise FeaturePack directory.
static FString EnterprisePluginsDir ()
Returns the enterprise plugins directory.
static FString FeaturePackDir ()
Returns the directory where feature packs are kept.
static bool FileExists (const FString &InPath)
Returns true if this file was found, false otherwise.
static FString FindCorrectCase (const FString &Path)
Converts the path casing to match the casing found on disk without resolving directory junctions.
static FString GameAgnosticSavedDir ()
Returns the saved directory that is not game specific.
static FString GameDevelopersDir ()
Returns the directory that contains subfolders for developer-specific content Example: "../../../ProjectName/Content/Developers.
static const TCHAR * GameFeatureRootPrefix ()
Returns the special path used when mounting FeaturePaks in editor.
static FString GameSourceDir ()
Returns the directory where game source code files are kept.
static FString GameUserDeveloperDir ()
Returns The directory that contains developer-specific content for the current user.
static FString GameUserDeveloperFolderName ()
Returns The folder name for the developer-specific directory for the current user.
static FString GeneratedConfigDir ()
Returns the directory the engine saves generated config files.
static FString GetBaseFilename (const FString &InPath, bool bRemovePath=true)
static FString GetBaseFilename (FString &&InPath, bool bRemovePath=true)
static FString GetCleanFilename (const FString &InPath)
static FString GetCleanFilename (FString &&InPath)
static const TArray< FString > & GetEditorLocalizationPaths ()
Returns a list of editor-specific localization paths.
static const TArray< FString > & GetEngineLocalizationPaths ()
Returns a list of engine-specific localization paths.
static FString GetExtension (const FString &InPath, bool bIncludeDot=false)
Gets the extension for this filename.
static TArray< FString > GetExtensionDirs (const FString &BaseDir, const FString &SubDir=FString(), bool bCheckValid=true)
Returns platform and restricted extensions that are present and if bCheckValid is set, valid (for platforms, it uses FDataDrivePlatformInfo to determine valid platforms, it doesn't just use what's present)
static const TArray< FString > & GetGameLocalizationPaths ()
Returns a list of game-specific localization paths.
static FString GetInvalidFileSystemChars ()
Returns a string containing all invalid characters as dictated by the operating system.
static FString GetPath (const FString &InPath)
static FString GetPath (FString &&InPath)
static FString GetPathLeaf (const FString &InPath)
static FString GetPathLeaf (FString &&InPath)
static FString GetPlatformLocalizationFolderName ()
Get the name of the platform-specific localization sub-folder.
static FString GetProjectFilePath ()
Gets the path to the project file.
static const TArray< FString > & GetPropertyNameLocalizationPaths ()
Returns a list of property name localization paths.
static const FString & GetRelativePathToRoot ()
Gets the relative path to get from BaseDir to RootDirectory.
static const TArray< FString > & GetRestrictedFolderNames ()
Returns a list of restricted/internal folder names (without any slashes) which may be tested against full paths to determine if a path is restricted or not.
static const TArray< FString > & GetToolTipLocalizationPaths ()
Returns a list of tool tip localization paths.
static bool HasProjectPersistentDownloadDir ()
static bool IsDrive (const FString &InPath)
Returns true if this path represents a root drive or volume.
static bool IsProjectFilePathSet ()
Checks whether the path to the project file, if any, is set.
static bool IsRelative (const FString &InPath)
Returns true if this path is relative to another path.
static bool IsRestrictedPath (const FString &InPath)
Determines if supplied path uses a restricted/internal subdirectory.
static bool IsSamePath (const FString &PathA, const FString &PathB)
Checks if two paths are the same.
static bool IsStaged ()
static bool IsUnderDirectory (const FString &InPath, const FString &InDirectory)
Determines if a path is under a given directory.
static FString LaunchDir ()
Returns the directory the application was launched from (useful for commandline utilities)
static bool MakePathRelativeTo (FString &InPath, const TCHAR *InRelativeTo)
Assuming both paths (or filenames) are relative to the same base dir, modifies InPath to be relative to InRelativeTo.
static void MakePlatformFilename (FString &InPath)
Takes an "Unreal" pathname and converts it to a platform filename.
static void MakeStandardFilename (FString &InPath)
static FString MakeValidFileName (const FString &InString, const TCHAR InReplacementChar=TEXT('\0'))
Returns a string that is safe to use as a filename because all items in GetInvalidFileSystemChars() are removed.
static void NormalizeDirectoryName (FString &InPath)
Normalize all / and \ to TEXT("/") and remove any trailing TEXT("/") if the character before that is not a TEXT("/") or a colon.
static void NormalizeFilename (FString &InPath)
Convert all / and \ to TEXT("/")
static FString ProfilingDir ()
Returns the directory the engine uses to output profiling files.
static FString ProjectConfigDir ()
Returns the directory the root configuration files are located.
static FString ProjectContentDir ()
Returns the content directory of the current game by looking at FApp::GetProjectName().
static FString ProjectDir ()
Returns the base directory of the current project by looking at FApp::GetProjectName().
static FString ProjectIntermediateDir ()
Returns the intermediate directory of the current game by looking at FApp::GetProjectName().
static FString ProjectLogDir ()
Returns the directory the engine uses to output logs.
static FString ProjectModsDir ()
Returns the mods directory of the current project by looking at FApp::GetProjectName().
static FString ProjectPersistentDownloadDir ()
static FString ProjectPlatformExtensionDir (const TCHAR *Platform)
Returns the directory where the project's platform extensions resides for the given platform.
static FString ProjectPluginsDir ()
Returns the plugins directory of the current game by looking at FApp::GetProjectName().
static const FString & ProjectSavedDir ()
Returns the saved directory of the current game by looking at FApp::GetProjectName().
static FString ProjectUserDir ()
Returns the root directory for user-specific game files.
static FString RemoveDuplicateSlashes (const FString &InPath)
Returns a copy of the given path on which duplicate slashes were removed (see the inplace version for more details).
static void RemoveDuplicateSlashes (FString &InPath)
Removes duplicate slashes in paths.
static FString RootDir ()
Returns the root directory of the engine directory tree.
static FString SandboxesDir ()
Returns the directory the engine stores sandbox output.
static FString ScreenShotDir ()
Returns the directory the engine uses to output screenshot files.
static FString SetExtension (const FString &InPath, const FString &InNewExtension)
Sets the extension of the given filename (like ChangeExtension, but also applies the extension if the file doesn't have one)
static void SetProjectFilePath (const FString &NewGameProjectFilePath)
Sets the path to the project file.
static FString ShaderWorkingDir ()
static bool ShouldSaveToUserDir ()
Should the "saved" directory structures be rooted in the user dir or relative to the "engine/game".
static FString SourceConfigDir ()
Returns the directory the engine uses to look for the source leaf ini files.
static void Split (const FString &InPath, FString &PathPart, FString &FilenamePart, FString &ExtensionPart)
Parses a fully qualified or relative filename into its components (filename, path, extension).
static void TearDown ()
Frees any memory retained by FPaths.
static bool ValidatePath (const FString &InPath, FText *OutReason=nullptr)
Validates that the parts that make up the path contain no invalid characters as dictated by the operating system Note that this is a different set of restrictions to those imposed by FPackageName.
static FString VideoCaptureDir ()
Returns the directory the engine uses to output user requested video capture files.
Static Protected Member Functions
static FString CombineInternal (const FStringView *Paths, int32 NumPaths)
Static Private Member Functions
template<typename... PathTypes>
static FORCEINLINE FString CombineImpl (UE::Core::Private::TToStringType_T< std::decay_t< PathTypes > >... InPaths)
static const FString & CustomShaderDirArgument ()
Returns, if any, the value of the -shaderworkingdir command line argument.
static const FString & CustomUserDirArgument ()
Returns, if any, the value of the -userdir command line argument.
Detailed Description
Path helpers for retrieving game dir, engine dir, etc.
Definition at line 35 of file Paths.h.
Member Enumeration Documentation
EPathConversion
enum class FPaths::EPathConversion : uint8 strong
Enumerator
Engine_PlatformExtension
Engine_NotForLicensees
Engine_NoRedist
Engine_LimitedAccess
Project_First
Project_PlatformExtension
Project_NotForLicensees
Project_NoRedist
Project_LimitedAccess
Definition at line 202 of file Paths.h.
Member Function Documentation
AudioCaptureDir()
FString FPaths::AudioCaptureDir () static
Returns the directory the engine uses to output user requested audio capture files.
Returns
Audio capture directory
AutomationDir()
FString FPaths::AutomationDir () static
Returns the directory for automation save files.
AutomationLogDir()
FString FPaths::AutomationLogDir () static
Returns the directory for automation log files.
AutomationReportsDir()
FString FPaths::AutomationReportsDir () static
Returns the directory for results of automation tests.
May be deleted every run.
AutomationTransientDir()
FString FPaths::AutomationTransientDir () static
Returns the directory for automation save files that are meant to be deleted every run.
BugItDir()
FString FPaths::BugItDir () static
Returns the directory the engine uses to output BugIt files.
Returns
screenshot directory
CanGetProjectDir()
bool FPaths::CanGetProjectDir () static
Returns
true if ProjectDir() is allowed to be called
ChangeExtension()
FString FPaths::ChangeExtension (const FString & InPath, const FString & InNewExtension) static
Changes the extension of the given filename (does nothing if the file has no extension)
CloudDir()
FString FPaths::CloudDir () static
Returns the directory for local files used in cloud emulation or support.
CollapseRelativeDirectories()
bool FPaths::CollapseRelativeDirectories (FString & InPath) static
Takes a fully pathed string and eliminates relative pathing (eg: annihilates ".." with the adjacent directory).
Assumes all slashes have been converted to TEXT('/'). For example, takes the string: BaseDirectory/SomeDirectory/../SomeOtherDirectory/Filename.ext and converts it to: BaseDirectory/SomeOtherDirectory/Filename.ext
Combine()
template<typename... PathTypes> FORCEINLINE FString FPaths::Combine (PathTypes &&... InPaths) inline static
Definition at line 706 of file Paths.h.
References CombineImpl(), FORCEINLINE, and Forward().
Referenced by DisplayClusterHelpers::filesystem::GetFullPathForThirdPartyDLL().
CombineImpl()
template<typename... PathTypes> FORCEINLINE FString FPaths::CombineImpl (UE::Core::Private::TToStringType_T< std::decay_t< PathTypes > >... InPaths) inline static private
Definition at line 724 of file Paths.h.
References CombineInternal(), FORCEINLINE, and UE_ARRAY_COUNT.
Referenced by Combine().
CombineInternal()
FString FPaths::CombineInternal (const FStringView * Paths, int32 NumPaths) static protected
Referenced by CombineImpl().
ConvertFromSandboxPath()
FString FPaths::ConvertFromSandboxPath (const FString & InPath, const TCHAR * InSandboxName) static
Converts a sandbox (in Saved/Sandboxes) path to a normal path.
Parameters
InSandboxName The name of the sandbox.
ConvertPath()
FString FPaths::ConvertPath (const FString & Path, EPathConversion Method, const TCHAR * ExtraData = nullptr, const TCHAR * OverrideProjectDir = nullptr) static
Converts a path with the given method.
Initially used for converting from normal paths to platform extensions (programs make it confusing, so haveing one source of truth is a good idea)
References Path.
Referenced by EnginePlatformExtensionDir(), and ProjectPlatformExtensionDir().
ConvertRelativePathToFull() [1/6]
FString FPaths::ConvertRelativePathToFull (const FString & BasePath, const FString & InPath) static
Converts a relative path name to a fully qualified name relative to the specified BasePath.
ConvertRelativePathToFull() [2/6]
FString FPaths::ConvertRelativePathToFull (const FString & BasePath, FString && InPath) static
Converts a relative path name to a fully qualified name relative to the specified BasePath.
ConvertRelativePathToFull() [3/6]
FString FPaths::ConvertRelativePathToFull (const FString & InPath) static
Converts a relative path name to a fully qualified name relative to the process BaseDir().
Referenced by DisplayClusterHelpers::filesystem::GetFullPathForConfig(), DisplayClusterHelpers::filesystem::GetFullPathForConfigResource(), DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs(), FPersistentStorageManager::GetPersistentStorageUsage(), TManagedStoragePlatformFile< BaseClass >::OpenWrite(), FPersistentStorageManager::TryManageFile(), and FPersistentStorageManager::TryManageFile().
ConvertRelativePathToFull() [4/6]
FString FPaths::ConvertRelativePathToFull (FString && BasePath, const FString & InPath) static
Converts a relative path name to a fully qualified name relative to the specified BasePath.
ConvertRelativePathToFull() [5/6]
FString FPaths::ConvertRelativePathToFull (FString && BasePath, FString && InPath) static
Converts a relative path name to a fully qualified name relative to the specified BasePath.
ConvertRelativePathToFull() [6/6]
FString FPaths::ConvertRelativePathToFull (FString && InPath) static
Converts a relative path name to a fully qualified name relative to the process BaseDir().
ConvertToSandboxPath()
FString FPaths::ConvertToSandboxPath (const FString & InPath, const TCHAR * InSandboxName) static
Converts a normal path to a sandbox path (in Saved/Sandboxes).
Parameters
InSandboxName The name of the sandbox.
CreateStandardFilename()
FString FPaths::CreateStandardFilename (const FString & InPath) static
Make fully standard "Unreal" pathname:
Normalizes path separators [NormalizeFilename]
Removes extraneous separators [NormalizeDirectoryName, as well removing adjacent separators]
Collapses internal ..'s
Makes relative to Engine\Binaries<Platform> (will ALWAYS start with ......)
CreateTempFilename()
FString FPaths::CreateTempFilename (const TCHAR * Path, const TCHAR * Prefix = TEXT(""), const TCHAR * Extension = TEXT(".tmp")) static
Creates a temporary filename with the specified prefix.
Parameters
Path The file pathname.
Prefix The file prefix.
Extension File extension ('.' required).
References Path.
CustomShaderDirArgument()
const FString & FPaths::CustomShaderDirArgument () static private
Returns, if any, the value of the -shaderworkingdir command line argument.
This can be used to sandbox shader working files to a desired location
CustomUserDirArgument()
const FString & FPaths::CustomUserDirArgument () static private
Returns, if any, the value of the -userdir command line argument.
This can be used to sandbox artifacts to a desired location
DevelopersFolderName()
FStringView FPaths::DevelopersFolderName () static
Returns the name of the subfolder for developer-specific content Example: "Developers".
DiffDir()
FString FPaths::DiffDir () static
Returns the directory for temp files used for diffing.
DirectoryExists()
bool FPaths::DirectoryExists (const FString & InPath) static
Returns true if this directory was found, false otherwise.
EngineConfigDir()
FString FPaths::EngineConfigDir () static
Returns the directory the root configuration files are located.
Returns
root config directory
EngineContentDir()
FString FPaths::EngineContentDir () static
Returns the content directory of the "core" engine that can be shared across several games or across games & mods.
Returns
engine content directory
Referenced by FRigVMEditorStyle::FRigVMEditorStyle(), and Audio::FSoundWavePCMWriter::SaveFinishedSoundWaveToPath().
EngineDefaultLayoutDir()
FString FPaths::EngineDefaultLayoutDir () static
Returns the directory for default Editor UI Layout files of the engine.
Returns
Directory for default Editor UI Layout files.
EngineDir()
FString FPaths::EngineDir () static
Returns the base directory of the "core" engine that can be shared across several games or across games & mods.
Shaders and base localization files e.g. reside in the engine directory.
Returns
engine directory
Referenced by EnginePlatformExtensionDir().
EngineEditorSettingsDir()
FString FPaths::EngineEditorSettingsDir () static
Returns the Editor Settings directory of the engine.
Returns
Editor Settings directory.
EngineIntermediateDir()
FString FPaths::EngineIntermediateDir () static
Returns the intermediate directory of the engine.
Returns
content directory
EnginePlatformExtensionDir()
FString FPaths::EnginePlatformExtensionDir (const TCHAR * Platform) inline static
Returns the directory where the engine's platform extensions resides for the given platform.
Parameters
Platform the platform to get the extension directory for
Returns
engine's platform extension directory
Definition at line 178 of file Paths.h.
References ConvertPath(), Engine_PlatformExtension, EngineDir(), EnginePlatformExtensionDir(), and Platform.
Referenced by EnginePlatformExtensionDir().
EnginePluginsDir()
FString FPaths::EnginePluginsDir () static
Returns the plugins directory of the engine.
Returns
Plugins directory.
Referenced by FRigVMEditorStyle::FRigVMEditorStyle().
EngineProjectLayoutDir()
FString FPaths::EngineProjectLayoutDir () static
Returns the directory for project Editor UI Layout files of the engine.
Returns
Directory for project Editor UI Layout files.
EngineSavedDir()
FString FPaths::EngineSavedDir () static
Returns the saved directory of the engine.
Returns
Saved directory.
EngineSourceDir()
FString FPaths::EngineSourceDir () static
Returns the directory where engine source code files are kept.
EngineUserDir()
FString FPaths::EngineUserDir () static
Returns the root directory for user-specific engine files.
Always writable.
Returns
root user directory
EngineUserLayoutDir()
FString FPaths::EngineUserLayoutDir () static
Returns the directory for user-generated Editor UI Layout files of the engine.
Returns
Directory for user-generated Editor UI Layout files.
EngineVersionAgnosticUserDir()
FString FPaths::EngineVersionAgnosticUserDir () static
Returns the root directory for user-specific engine files which can be shared between versions.
Always writable.
Returns
root user directory
EnterpriseDir()
FString FPaths::EnterpriseDir () static
Returns the base directory enterprise directory.
Returns
enterprise directory
EnterpriseFeaturePackDir()
FString FPaths::EnterpriseFeaturePackDir () static
Returns the enterprise FeaturePack directory.
Returns
FeaturePack directory.
EnterprisePluginsDir()
FString FPaths::EnterprisePluginsDir () static
Returns the enterprise plugins directory.
Returns
Plugins directory.
FeaturePackDir()
FString FPaths::FeaturePackDir () static
Returns the directory where feature packs are kept.
FileExists()
bool FPaths::FileExists (const FString & InPath) static
Returns true if this file was found, false otherwise.
Referenced by DisplayClusterHelpers::filesystem::GetFullPathForConfig(), DisplayClusterHelpers::filesystem::GetFullPathForConfigResource(), and DisplayClusterHelpers::filesystem::GetFullPathForThirdPartyDLL().
FindCorrectCase()
FString FPaths::FindCorrectCase (const FString & Path) static
Converts the path casing to match the casing found on disk without resolving directory junctions.
References Path.
GameAgnosticSavedDir()
FString FPaths::GameAgnosticSavedDir () static
Returns the saved directory that is not game specific.
This is usually the same as EngineSavedDir().
Returns
saved directory
GameDevelopersDir()
FString FPaths::GameDevelopersDir () static
Returns the directory that contains subfolders for developer-specific content Example: "../../../ProjectName/Content/Developers.
GameFeatureRootPrefix()
const TCHAR * FPaths::GameFeatureRootPrefix () static
Returns the special path used when mounting FeaturePaks in editor.
GameSourceDir()
FString FPaths::GameSourceDir () static
Returns the directory where game source code files are kept.
GameUserDeveloperDir()
FString FPaths::GameUserDeveloperDir () static
Returns The directory that contains developer-specific content for the current user.
GameUserDeveloperFolderName()
FString FPaths::GameUserDeveloperFolderName () static
Returns The folder name for the developer-specific directory for the current user.
GeneratedConfigDir()
FString FPaths::GeneratedConfigDir () static
Returns the directory the engine saves generated config files.
Returns
config directory
Referenced by FConfigCacheIni::LoadExternalIniFile(), and FConfigCacheIni::LoadGlobalIniFile().
GetBaseFilename() [1/2]
FString FPaths::GetBaseFilename (const FString & InPath, bool bRemovePath = true) static
Referenced by FGenericSaveGameSystem::GetSaveGameNames().
GetBaseFilename() [2/2]
FString FPaths::GetBaseFilename (FString && InPath, bool bRemovePath = true) static
GetCleanFilename() [1/2]
FString FPaths::GetCleanFilename (const FString & InPath) static
Referenced by FShaderCompilerInput::GetSourceFilename().
GetCleanFilename() [2/2]
FString FPaths::GetCleanFilename (FString && InPath) static
GetEditorLocalizationPaths()
const TArray< FString > & FPaths::GetEditorLocalizationPaths () static
Returns a list of editor-specific localization paths.
GetEngineLocalizationPaths()
const TArray< FString > & FPaths::GetEngineLocalizationPaths () static
Returns a list of engine-specific localization paths.
GetExtension()
FString FPaths::GetExtension (const FString & InPath, bool bIncludeDot = false) static
Gets the extension for this filename.
Parameters
bIncludeDot if true, includes the leading dot in the result
Returns
the extension of this filename, or an empty string if the filename doesn't have an extension.
Referenced by DoActionToAllPackages().
GetExtensionDirs()
TArray< FString > FPaths::GetExtensionDirs (const FString & BaseDir, const FString & SubDir = FString(), bool bCheckValid = true) static
Returns platform and restricted extensions that are present and if bCheckValid is set, valid (for platforms, it uses FDataDrivePlatformInfo to determine valid platforms, it doesn't just use what's present)
Returns
BaseDir and usable extension directories under BaseDir (either Engine or Project)
GetGameLocalizationPaths()
const TArray< FString > & FPaths::GetGameLocalizationPaths () static
Returns a list of game-specific localization paths.
GetInvalidFileSystemChars()
FString FPaths::GetInvalidFileSystemChars () static
Returns a string containing all invalid characters as dictated by the operating system.
GetPath() [1/2]
FString FPaths::GetPath (const FString & InPath) static
Referenced by DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs(), and FEditorFolderUtils::GetParentPath().
GetPath() [2/2]
FString FPaths::GetPath (FString && InPath) static
GetPathLeaf() [1/2]
FString FPaths::GetPathLeaf (const FString & InPath) static
GetPathLeaf() [2/2]
FString FPaths::GetPathLeaf (FString && InPath) static
GetPlatformLocalizationFolderName()
FString FPaths::GetPlatformLocalizationFolderName () static
Get the name of the platform-specific localization sub-folder.
GetProjectFilePath()
FString FPaths::GetProjectFilePath () static
Gets the path to the project file.
Returns
Project file path.
GetPropertyNameLocalizationPaths()
const TArray< FString > & FPaths::GetPropertyNameLocalizationPaths () static
Returns a list of property name localization paths.
GetRelativePathToRoot()
const FString & FPaths::GetRelativePathToRoot () static
Gets the relative path to get from BaseDir to RootDirectory.
GetRestrictedFolderNames()
const TArray< FString > & FPaths::GetRestrictedFolderNames () static
Returns a list of restricted/internal folder names (without any slashes) which may be tested against full paths to determine if a path is restricted or not.
GetToolTipLocalizationPaths()
const TArray< FString > & FPaths::GetToolTipLocalizationPaths () static
Returns a list of tool tip localization paths.
HasProjectPersistentDownloadDir()
bool FPaths::HasProjectPersistentDownloadDir () static
IsDrive()
bool FPaths::IsDrive (const FString & InPath) static
Returns true if this path represents a root drive or volume.
IsProjectFilePathSet()
bool FPaths::IsProjectFilePathSet () static
Checks whether the path to the project file, if any, is set.
Returns
true if the path is set, false otherwise.
IsRelative()
bool FPaths::IsRelative (const FString & InPath) static
Returns true if this path is relative to another path.
Referenced by DisplayClusterHelpers::filesystem::GetFullPathForConfig(), and DisplayClusterHelpers::filesystem::GetFullPathForConfigResource().
IsRestrictedPath()
bool FPaths::IsRestrictedPath (const FString & InPath) static
Determines if supplied path uses a restricted/internal subdirectory.
Note that slashes are normalized and character case is ignored for the comparison.
IsSamePath()
bool FPaths::IsSamePath (const FString & PathA, const FString & PathB) static
Checks if two paths are the same.
Parameters
PathA First path to check.
PathB Second path to check.
Returns
True if both paths are the same. False otherwise.
IsStaged()
bool FPaths::IsStaged () static
Returns
true if the build has been staged and uses the simplified remapped directory structure made when staging
IsUnderDirectory()
bool FPaths::IsUnderDirectory (const FString & InPath, const FString & InDirectory) static
Determines if a path is under a given directory.
LaunchDir()
FString FPaths::LaunchDir () static
Returns the directory the application was launched from (useful for commandline utilities)
Referenced by DisplayClusterHelpers::filesystem::GetFullPathForConfig().
MakePathRelativeTo()
bool FPaths::MakePathRelativeTo (FString & InPath, const TCHAR * InRelativeTo) static
Assuming both paths (or filenames) are relative to the same base dir, modifies InPath to be relative to InRelativeTo.
Parameters
InPath Path to change to be relative to InRelativeTo
InRelativeTo Path to use as the new relative base
Returns
true if InPath was changed to be relative
MakePlatformFilename()
void FPaths::MakePlatformFilename (FString & InPath) static
Takes an "Unreal" pathname and converts it to a platform filename.
MakeStandardFilename()
void FPaths::MakeStandardFilename (FString & InPath) static
MakeValidFileName()
FString FPaths::MakeValidFileName (const FString & InString, const TCHAR InReplacementChar = TEXT('\0')) static
Returns a string that is safe to use as a filename because all items in GetInvalidFileSystemChars() are removed.
NormalizeDirectoryName()
void FPaths::NormalizeDirectoryName (FString & InPath) static
Normalize all / and \ to TEXT("/") and remove any trailing TEXT("/") if the character before that is not a TEXT("/") or a colon.
NormalizeFilename()
void FPaths::NormalizeFilename (FString & InPath) static
Convert all / and \ to TEXT("/")
Referenced by DisplayClusterHelpers::filesystem::GetFullPathForConfigResource(), and DisplayClusterHelpers::filesystem::GetRelativePathForConfigResource().
ProfilingDir()
FString FPaths::ProfilingDir () static
Returns the directory the engine uses to output profiling files.
Returns
log directory
ProjectConfigDir()
FString FPaths::ProjectConfigDir () static
Returns the directory the root configuration files are located.
Returns
root config directory
ProjectContentDir()
FString FPaths::ProjectContentDir () static
Returns the content directory of the current game by looking at FApp::GetProjectName().
Returns
content directory
ProjectDir()
FString FPaths::ProjectDir () static
Returns the base directory of the current project by looking at FApp::GetProjectName().
This is usually a subdirectory of the installation root directory and can be overridden on the command line to allow self contained mod support.
Returns
base directory
Referenced by DisplayClusterHelpers::filesystem::GetFullPathForConfig(), DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs(), and ProjectPlatformExtensionDir().
ProjectIntermediateDir()
FString FPaths::ProjectIntermediateDir () static
Returns the intermediate directory of the current game by looking at FApp::GetProjectName().
Returns
intermediate directory
ProjectLogDir()
FString FPaths::ProjectLogDir () static
Returns the directory the engine uses to output logs.
This currently can't be an .ini setting as the game starts logging before it can read from .ini files.
Returns
log directory
ProjectModsDir()
FString FPaths::ProjectModsDir () static
Returns the mods directory of the current project by looking at FApp::GetProjectName().
Returns
mods directory
ProjectPersistentDownloadDir()
FString FPaths::ProjectPersistentDownloadDir () static
ProjectPlatformExtensionDir()
FString FPaths::ProjectPlatformExtensionDir (const TCHAR * Platform) inline static
Returns the directory where the project's platform extensions resides for the given platform.
Parameters
Platform the platform to get the extension directory for
Returns
project's platform extension directory
Definition at line 197 of file Paths.h.
References ConvertPath(), Platform, Project_PlatformExtension, ProjectDir(), and ProjectPlatformExtensionDir().
Referenced by ProjectPlatformExtensionDir().
ProjectPluginsDir()
FString FPaths::ProjectPluginsDir () static
Returns the plugins directory of the current game by looking at FApp::GetProjectName().
Returns
plugins directory
ProjectSavedDir()
const FString & FPaths::ProjectSavedDir () static
Returns the saved directory of the current game by looking at FApp::GetProjectName().
Returns
saved directory
Referenced by FGenericSaveGameSystem::GetSaveGameNames(), and FGenericSaveGameSystem::GetSaveGamePath().
ProjectUserDir()
FString FPaths::ProjectUserDir () static
Returns the root directory for user-specific game files.
Returns
game user directory
RemoveDuplicateSlashes() [1/2]
FString FPaths::RemoveDuplicateSlashes (const FString & InPath) static
Returns a copy of the given path on which duplicate slashes were removed (see the inplace version for more details).
RemoveDuplicateSlashes() [2/2]
void FPaths::RemoveDuplicateSlashes (FString & InPath) static
Removes duplicate slashes in paths.
Assumes all slashes have been converted to TEXT('/'). For example, takes the string: BaseDirectory/SomeDirectory//SomeOtherDirectory////Filename.ext and converts it to: BaseDirectory/SomeDirectory/SomeOtherDirectory/Filename.ext
Referenced by FWorldPartitionCookPackage::MakeGeneratedFullPath(), and FWorldPartitionCookPackage::SanitizePathComponent().
RootDir()
FString FPaths::RootDir () static
Returns the root directory of the engine directory tree.
Returns
Root directory.
Referenced by DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs().
SandboxesDir()
FString FPaths::SandboxesDir () static
Returns the directory the engine stores sandbox output.
Returns
sandbox directory
ScreenShotDir()
FString FPaths::ScreenShotDir () static
Returns the directory the engine uses to output screenshot files.
Returns
screenshot directory
SetExtension()
FString FPaths::SetExtension (const FString & InPath, const FString & InNewExtension) static
Sets the extension of the given filename (like ChangeExtension, but also applies the extension if the file doesn't have one)
SetProjectFilePath()
void FPaths::SetProjectFilePath (const FString & NewGameProjectFilePath) static
Sets the path to the project file.
Parameters
NewGameProjectFilePath - The project file path to set.
ShaderWorkingDir()
FString FPaths::ShaderWorkingDir () static
ShouldSaveToUserDir()
bool FPaths::ShouldSaveToUserDir () static
Should the "saved" directory structures be rooted in the user dir or relative to the "engine/game".
SourceConfigDir()
FString FPaths::SourceConfigDir () static
Returns the directory the engine uses to look for the source leaf ini files.
This can't be an .ini variable for obvious reasons.
Returns
source config directory
Split()
void FPaths::Split (const FString & InPath, FString & PathPart, FString & FilenamePart, FString & ExtensionPart) static
Parses a fully qualified or relative filename into its components (filename, path, extension).
Parameters
InPath [in] Full filename path
PathPart [out] receives the value of the path portion of the input string
FilenamePart [out] receives the value of the filename portion of the input string
ExtensionPart [out] receives the value of the extension portion of the input string
TearDown()
void FPaths::TearDown () static
Frees any memory retained by FPaths.
UE_DEPRECATED() [1/3]
FPaths::UE_DEPRECATED (5. 4, "Use EnginePlatformExtensionDir(Platform) instead - ProjectPlatformExtensionsDir did not handle programs properly, so for consistency this is being removed as well")
Returns the directory where engine platform extensions reside.
Returns
engine platform extensions directory
UE_DEPRECATED() [2/3]
FPaths::UE_DEPRECATED (5. 4, "Use ProjectPlatformExtensionDir(Platform) instead - this function does not handle Programs properly")
Returns the directory where the project's platform extensions reside.
Returns
project platform extensions directory
UE_DEPRECATED() [3/3]
FPaths::UE_DEPRECATED (5. 5, "Cooked editor localization path no longer exist. Cooked editors now load game localization paths.") inline
Returns a list of cooked editor-specific localization paths.
Definition at line 429 of file Paths.h.
ValidatePath()
bool FPaths::ValidatePath (const FString & InPath, FText * OutReason = nullptr) static
Validates that the parts that make up the path contain no invalid characters as dictated by the operating system Note that this is a different set of restrictions to those imposed by FPackageName.
Parameters
InPath - path to validate
OutReason - optional parameter to fill with the failure reason
VideoCaptureDir()
FString FPaths::VideoCaptureDir () static
Returns the directory the engine uses to output user requested video capture files.
Returns
Video capture directory
The documentation for this class was generated from the following file:
Paths.h