Unreal Engine 5.6 C++ API: UE::MovieScene::FComponentRegistry Struct Reference
UE::MovieScene::FComponentRegistry Struct Reference
#include "MovieSceneComponentRegistry.h"
Public Member Functions
FComponentRegistry ()=default
FComponentRegistry (const FComponentRegistry &)=delete
FComponentRegistry (FComponentRegistry &&)=delete
MOVIESCENE_API void DestroyComponentTypeSafe (FComponentTypeID ComponentTypeID)
Destroy a component type by first removing it from all existing entities.
MOVIESCENE_API void DestroyComponentUnsafeFast (FComponentTypeID ComponentTypeID)
Destroy a component type that definitely does not exist on any entities or is cached elsewhere.
MOVIESCENE_API const FComponentTypeInfo & GetComponentTypeChecked (FComponentTypeID ComponentTypeID) const
const FComponentMask & GetCopyAndMigrationMask () const
Retrive a mask of all components to be copied or migrated to outputs.
const FComponentMask & GetDataComponentTypes () const
Retrieve a mask of all data component types (ie all components that are not tags).
const FComponentMask & GetMigrationMask () const
Retrieve a mask of all components that are to be migrated to outputs if there are multiple entities animating the same thing.
const FComponentMask & GetPreservationMask () const
Retrieve a mask of all components that are to be preserved.
template<typename T>
TComponentTypeID< T > NewComponentType (const TCHAR *const DebugName, const FNewComponentTypeParams &Params=FNewComponentTypeParams())
Define a new transient tag type using the specified information.
template<typename T>
void NewComponentType (TComponentTypeID< T > *Ref, const TCHAR *const DebugName, const FNewComponentTypeParams &Params=FNewComponentTypeParams())
template<typename T>
TComponentTypeID< T > NewComponentTypeNoAddReferencedObjects (const TCHAR *const DebugName, const FNewComponentTypeParams &Params=FNewComponentTypeParams())
Same as NewComponentType but specifically does not expose the component type to the reference graph.
template<typename T>
void NewComponentTypeNoAddReferencedObjects (TComponentTypeID< T > *Ref, const TCHAR *const DebugName, const FNewComponentTypeParams &Params=FNewComponentTypeParams())
template<typename PropertyTraits>
void NewPropertyType (TPropertyComponents< PropertyTraits > &OutComponents, const TCHAR *DebugName)
MOVIESCENE_API FComponentTypeID NewTag (const TCHAR *const DebugName, EComponentTypeFlags Flags=EComponentTypeFlags::None)
Define a new tag type using the specified information.
FComponentRegistry & operator= (const FComponentRegistry &)=delete
FComponentRegistry & operator= (FComponentRegistry &&)=delete
Data Fields
FEntityFactories Factories
Private Member Functions
template<typename T>
FComponentTypeInfo MakeComponentTypeInfoWithoutComponentOps (const TCHAR *const DebugName, const FNewComponentTypeParams &Params)
MOVIESCENE_API FComponentTypeID NewComponentTypeInternal (FComponentTypeInfo &&TypeInfo)
Private Attributes
TSparseArray< UScriptStruct * > ComponentStructs
TSparseArray< FComponentTypeInfo > ComponentTypes
FComponentMask CopyAndMigrationMask
Mask containing all components that have the EComponentTypeFlags::CopyToOutput and EComponentTypeFlags::MigrateToOutput.
FComponentMask MigrationMask
Mask containing all components that have the flag EComponentTypeFlags::MigrateToOutput.
FComponentMask NonTagComponentMask
A component mask for all component types that are NOT tags, cached and updated when ComponentTypes is modified.
FComponentMask PreservationMask
Mask containing all components that have the flag EComponentTypeFlags::Preserved.
Detailed Description
Definition at line 45 of file MovieSceneComponentRegistry.h.
Constructor & Destructor Documentation
FComponentRegistry() [1/3]
UE::MovieScene::FComponentRegistry::FComponentRegistry () default
Referenced by FComponentRegistry(), FComponentRegistry(), operator=(), and operator=().
FComponentRegistry() [2/3]
UE::MovieScene::FComponentRegistry::FComponentRegistry (const FComponentRegistry &) delete
References FComponentRegistry().
FComponentRegistry() [3/3]
UE::MovieScene::FComponentRegistry::FComponentRegistry (FComponentRegistry &&) delete
References FComponentRegistry().
Member Function Documentation
DestroyComponentTypeSafe()
MOVIESCENE_API void UE::MovieScene::FComponentRegistry::DestroyComponentTypeSafe (FComponentTypeID ComponentTypeID)
Destroy a component type by first removing it from all existing entities.
Note
Will not invalidate any cached FComponentTypeID or TComponentTypeID structures
Parameters
ComponentTypeID The component type to destroy
DestroyComponentUnsafeFast()
MOVIESCENE_API void UE::MovieScene::FComponentRegistry::DestroyComponentUnsafeFast (FComponentTypeID ComponentTypeID)
Destroy a component type that definitely does not exist on any entities or is cached elsewhere.
Note
Will not invalidate any cached FComponentTypeID or TComponentTypeID structures
Parameters
ComponentTypeID The component type to destroy
GetComponentTypeChecked()
MOVIESCENE_API const FComponentTypeInfo & UE::MovieScene::FComponentRegistry::GetComponentTypeChecked (FComponentTypeID ComponentTypeID) const
GetCopyAndMigrationMask()
const FComponentMask & UE::MovieScene::FComponentRegistry::GetCopyAndMigrationMask () const inline
Retrive a mask of all components to be copied or migrated to outputs.
Definition at line 165 of file MovieSceneComponentRegistry.h.
References CopyAndMigrationMask.
GetDataComponentTypes()
const FComponentMask & UE::MovieScene::FComponentRegistry::GetDataComponentTypes () const inline
Retrieve a mask of all data component types (ie all components that are not tags).
Definition at line 141 of file MovieSceneComponentRegistry.h.
References NonTagComponentMask.
GetMigrationMask()
const FComponentMask & UE::MovieScene::FComponentRegistry::GetMigrationMask () const inline
Retrieve a mask of all components that are to be migrated to outputs if there are multiple entities animating the same thing.
Definition at line 157 of file MovieSceneComponentRegistry.h.
References MigrationMask.
GetPreservationMask()
const FComponentMask & UE::MovieScene::FComponentRegistry::GetPreservationMask () const inline
Retrieve a mask of all components that are to be preserved.
Definition at line 149 of file MovieSceneComponentRegistry.h.
References PreservationMask.
MakeComponentTypeInfoWithoutComponentOps()
template<typename T> FComponentTypeInfo UE::MovieScene::FComponentRegistry::MakeComponentTypeInfoWithoutComponentOps (const TCHAR *const DebugName, const FNewComponentTypeParams & Params) private
Definition at line 196 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FComponentTypeInfo::Alignment, UE::MovieScene::FComponentTypeInfo::bHasReferencedObjects, UE::MovieScene::FComponentTypeInfo::bIsCopiedToOutput, UE::MovieScene::FComponentTypeInfo::bIsMigratedToOutput, UE::MovieScene::FComponentTypeInfo::bIsPreserved, UE::MovieScene::FComponentTypeInfo::bIsTriviallyCopyAssignable, UE::MovieScene::FComponentTypeInfo::bIsTriviallyDestructable, UE::MovieScene::FComponentTypeInfo::bIsZeroConstructType, EnumHasAnyFlags(), GetGeneratedTypeName(), MakeUnique(), UE::Max, Params, UE::MovieScene::FComponentTypeInfo::Sizeof, TIsTriviallyCopyAssignable< T >::Value, and TIsZeroConstructType< T >::Value.
Referenced by NewComponentType(), and NewComponentTypeNoAddReferencedObjects().
NewComponentType() [1/2]
template<typename T> TComponentTypeID< T > UE::MovieScene::FComponentRegistry::NewComponentType (const TCHAR *const DebugName, const FNewComponentTypeParams & Params = FNewComponentTypeParams())
Define a new transient tag type using the specified information.
Tags have 0 memory overhead.
Note
Transitory tag types must be unregistered when no longer required by calling DestroyComponentTypeSafe or Unsafe to prevent leaking component type IDs
Parameters
DebugName A developer friendly name that accompanies this component type for debugging purposes
Params (Optional) Parameters for the type including component flags
Returns
A new component type identifier for the tag
Definition at line 226 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FComponentTypeInfo::bHasReferencedObjects, UE::MovieScene::FComponentTypeInfo::bIsTriviallyCopyAssignable, UE::MovieScene::FComponentTypeInfo::bIsTriviallyDestructable, UE::MovieScene::FComponentTypeInfo::bIsZeroConstructType, EnumHasAnyFlags(), Factories, UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOps(), MakeComponentTypeInfoWithoutComponentOps(), MoveTemp(), NewComponentTypeInternal(), Params, UE::MovieScene::FComponentTypeID::ReinterpretCast(), and UE::MovieScene::THasAddReferencedObjectForComponent< T >::Value.
Referenced by NewComponentType(), and NewPropertyType().
NewComponentType() [2/2]
template<typename T> void UE::MovieScene::FComponentRegistry::NewComponentType (TComponentTypeID< T > * Ref, const TCHAR *const DebugName, const FNewComponentTypeParams & Params = FNewComponentTypeParams()) inline
Definition at line 89 of file MovieSceneComponentRegistry.h.
References NewComponentType(), and Params.
NewComponentTypeInternal()
MOVIESCENE_API FComponentTypeID UE::MovieScene::FComponentRegistry::NewComponentTypeInternal (FComponentTypeInfo && TypeInfo) private
References Params.
Referenced by NewComponentType(), and NewComponentTypeNoAddReferencedObjects().
NewComponentTypeNoAddReferencedObjects() [1/2]
template<typename T> TComponentTypeID< T > UE::MovieScene::FComponentRegistry::NewComponentTypeNoAddReferencedObjects (const TCHAR *const DebugName, const FNewComponentTypeParams & Params = FNewComponentTypeParams())
Same as NewComponentType but specifically does not expose the component type to the reference graph.
Use with caution!
Definition at line 253 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FComponentTypeInfo::bHasReferencedObjects, UE::MovieScene::FComponentTypeInfo::bIsTriviallyCopyAssignable, UE::MovieScene::FComponentTypeInfo::bIsTriviallyDestructable, UE::MovieScene::FComponentTypeInfo::bIsZeroConstructType, EnumHasAnyFlags(), Factories, UE::MovieScene::FComponentTypeInfo::MakeComplexComponentOpsNoAddReferencedObjects(), MakeComponentTypeInfoWithoutComponentOps(), MoveTemp(), NewComponentTypeInternal(), Params, and UE::MovieScene::FComponentTypeID::ReinterpretCast().
Referenced by NewComponentTypeNoAddReferencedObjects().
NewComponentTypeNoAddReferencedObjects() [2/2]
template<typename T> void UE::MovieScene::FComponentRegistry::NewComponentTypeNoAddReferencedObjects (TComponentTypeID< T > * Ref, const TCHAR *const DebugName, const FNewComponentTypeParams & Params = FNewComponentTypeParams()) inline
Definition at line 95 of file MovieSceneComponentRegistry.h.
References NewComponentTypeNoAddReferencedObjects(), and Params.
NewPropertyType()
template<typename PropertyTraits> void UE::MovieScene::FComponentRegistry::NewPropertyType (TPropertyComponents< PropertyTraits > & OutComponents, const TCHAR * DebugName) inline
Definition at line 101 of file MovieSceneComponentRegistry.h.
References NewComponentType(), NewTag(), and TEXT.
NewTag()
MOVIESCENE_API FComponentTypeID UE::MovieScene::FComponentRegistry::NewTag (const TCHAR *const DebugName, EComponentTypeFlags Flags = EComponentTypeFlags::None)
Define a new tag type using the specified information.
Tags have 0 memory overhead.
Note
Transitory tag types must be unregistered when no longer required by calling DestroyComponentTypeSafe or Unsafe to prevent leaking component type IDs
Parameters
DebugName A developer friendly name that accompanies this component type for debugging purposes
Flags Flags relating to the new component type
Returns
A new component type identifier for the tag
References Flags, and Params.
Referenced by NewPropertyType().
operator=() [1/2]
FComponentRegistry & UE::MovieScene::FComponentRegistry::operator= (const FComponentRegistry &) delete
References FComponentRegistry().
operator=() [2/2]
FComponentRegistry & UE::MovieScene::FComponentRegistry::operator= (FComponentRegistry &&) delete
References FComponentRegistry().
Field Documentation
ComponentStructs
TSparseArray<UScriptStruct*> UE::MovieScene::FComponentRegistry::ComponentStructs private
Definition at line 180 of file MovieSceneComponentRegistry.h.
ComponentTypes
TSparseArray<FComponentTypeInfo> UE::MovieScene::FComponentRegistry::ComponentTypes private
Definition at line 179 of file MovieSceneComponentRegistry.h.
CopyAndMigrationMask
FComponentMask UE::MovieScene::FComponentRegistry::CopyAndMigrationMask private
Mask containing all components that have the EComponentTypeFlags::CopyToOutput and EComponentTypeFlags::MigrateToOutput.
Definition at line 192 of file MovieSceneComponentRegistry.h.
Referenced by GetCopyAndMigrationMask().
Factories
FEntityFactories UE::MovieScene::FComponentRegistry::Factories
Definition at line 48 of file MovieSceneComponentRegistry.h.
Referenced by NewComponentType(), and NewComponentTypeNoAddReferencedObjects().
MigrationMask
FComponentMask UE::MovieScene::FComponentRegistry::MigrationMask private
Mask containing all components that have the flag EComponentTypeFlags::MigrateToOutput.
Definition at line 189 of file MovieSceneComponentRegistry.h.
Referenced by GetMigrationMask().
NonTagComponentMask
FComponentMask UE::MovieScene::FComponentRegistry::NonTagComponentMask private
A component mask for all component types that are NOT tags, cached and updated when ComponentTypes is modified.
Definition at line 183 of file MovieSceneComponentRegistry.h.
Referenced by GetDataComponentTypes().
PreservationMask
FComponentMask UE::MovieScene::FComponentRegistry::PreservationMask private
Mask containing all components that have the flag EComponentTypeFlags::Preserved.
Definition at line 186 of file MovieSceneComponentRegistry.h.
Referenced by GetPreservationMask().
The documentation for this struct was generated from the following files:
MovieSceneComponentRegistry.h
MovieSceneEntityFactoryTemplates.h