Unreal Engine 5.6 C++ API: FSkinnedAssetCompilingManager Class Reference
FSkinnedAssetCompilingManager Class Reference
#include "SkinnedAssetCompiler.h"
Public Member Functions
void AddSkinnedAssets (TArrayView< USkinnedAsset *const > InSkinnedAssets)
Adds skinned assets compiled asynchronously so they are monitored.
void FinishAllCompilation () override
Blocks until completion of all async skinned asset compilation.
void FinishCompilation (TArrayView< USkinnedAsset *const > InSkinnedAssets)
Blocks until completion of the requested skinned assets.
EQueuedWorkPriority GetBasePriority (USkinnedAsset *InSkinnedAsset) const
Returns the priority at which the given skinned asset should be scheduled.
int32 GetNumRemainingJobs () const
Returns the number of outstanding compilations.
FQueuedThreadPool * GetThreadPool () const
Returns the threadpool where skinned asset compilation should be scheduled.
bool IsAsyncCompilationAllowed (USkinnedAsset *InSkinnedAsset) const
Returns if asynchronous compilation is allowed for this skinned asset.
bool IsAsyncCompilationEnabled () const
Returns true if the feature is currently activated.
void Shutdown () override
Cancel any pending work and blocks until it is safe to shut down.
UE_DEPRECATED (5.1, "Use AddSkinnedAssets instead.") 1 void AddSkeletalMeshes(TArrayView< class USkeletalMesh *const > InSkeletalMeshes)
Adds skeletal meshes compiled asynchronously so they are monitored.
Static Public Member Functions
static FSkinnedAssetCompilingManager & Get ()
static FName GetStaticAssetTypeName ()
Get the name of the asset type this compiler handles.
Private Member Functions
FSkinnedAssetCompilingManager ()
void FinishCompilationForObjects (TArrayView< UObject *const > InObjects) override
Blocks until completion of the requested objects.
void FinishCompilationsForGame ()
FTextFormat GetAssetNameFormat () const override
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
FName GetAssetTypeName () const override
A unique name among all asset compiling manager to identify the type of asset this manager handles.
TArrayView< FName > GetDependentTypeNames () const override
Return other asset types that should preferably be handled before this one.
int32 GetNumRemainingAssets () const override
Returns the number of remaining compilations.
void OnPostReachabilityAnalysis ()
void OnPreGarbageCollect ()
void PostCompilation (TArrayView< USkinnedAsset *const > InSkinnedAssets)
void PostCompilation (USkinnedAsset *SkinnedAsset)
void ProcessAsyncTasks (bool bLimitExecutionTime=false) override
Called once per frame, fetches completed tasks and applies them to the scene.
void ProcessSkinnedAssets (bool bLimitExecutionTime, int32 MinBatchSize=1)
void Reschedule ()
void UpdateCompilationNotification ()
Private Member Functions inherited from IAssetCompilingManager
virtual void MarkCompilationAsCanceled (TArrayView< UObject *const > InObjects)
Mark compilation of the provided objects as canceled.
virtual ~IAssetCompilingManager ()
virtual void ProcessAsyncTasks (const AssetCompilation::FProcessAsyncTaskParams &Params)
Called once per frame, fetches completed tasks and applies them to the scene.
Private Attributes
bool bHasShutdown = false
TUniquePtr< FAsyncCompilationNotification > Notification
FDelegateHandle PostReachabilityAnalysisHandle
FDelegateHandle PreGarbageCollectHandle
TSet< TWeakObjectPtr< USkinnedAsset > > RegisteredSkinnedAsset
Friends
class FAssetCompilingManager
Detailed Description
Definition at line 19 of file SkinnedAssetCompiler.h.
Constructor & Destructor Documentation
FSkinnedAssetCompilingManager()
FSkinnedAssetCompilingManager::FSkinnedAssetCompilingManager () private
References FSkinnedAssetCompilingManager().
Referenced by FSkinnedAssetCompilingManager(), and Get().
Member Function Documentation
AddSkinnedAssets()
void FSkinnedAssetCompilingManager::AddSkinnedAssets (TArrayView< USkinnedAsset *const > InSkinnedAssets)
Adds skinned assets compiled asynchronously so they are monitored.
References AddSkinnedAssets().
Referenced by AddSkinnedAssets().
FinishAllCompilation()
void FSkinnedAssetCompilingManager::FinishAllCompilation () override virtual
Blocks until completion of all async skinned asset compilation.
Implements IAssetCompilingManager.
References FinishAllCompilation().
Referenced by FinishAllCompilation().
FinishCompilation()
void FSkinnedAssetCompilingManager::FinishCompilation (TArrayView< USkinnedAsset *const > InSkinnedAssets)
Blocks until completion of the requested skinned assets.
References FinishCompilation().
Referenced by FinishCompilation().
FinishCompilationForObjects()
void FSkinnedAssetCompilingManager::FinishCompilationForObjects (TArrayView< UObject *const > InObjects) override private virtual
Blocks until completion of the requested objects.
Reimplemented from IAssetCompilingManager.
References FinishCompilationForObjects().
Referenced by FinishCompilationForObjects().
FinishCompilationsForGame()
void FSkinnedAssetCompilingManager::FinishCompilationsForGame () private
References FinishCompilationsForGame().
Referenced by FinishCompilationsForGame().
Get()
FSkinnedAssetCompilingManager & FSkinnedAssetCompilingManager::Get () static
References FSkinnedAssetCompilingManager().
GetAssetNameFormat()
FTextFormat FSkinnedAssetCompilingManager::GetAssetNameFormat () const override private virtual
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
Note: Should be in a similar form as "{0}|plural(one=Singular Name,other=Plural Name)"
Implements IAssetCompilingManager.
References GetAssetNameFormat().
Referenced by GetAssetNameFormat().
GetAssetTypeName()
FName FSkinnedAssetCompilingManager::GetAssetTypeName () const override private virtual
A unique name among all asset compiling manager to identify the type of asset this manager handles.
Implements IAssetCompilingManager.
References GetAssetTypeName().
Referenced by GetAssetTypeName().
GetBasePriority()
EQueuedWorkPriority FSkinnedAssetCompilingManager::GetBasePriority (USkinnedAsset * InSkinnedAsset) const
Returns the priority at which the given skinned asset should be scheduled.
References GetBasePriority().
Referenced by GetBasePriority().
GetDependentTypeNames()
TArrayView< FName > FSkinnedAssetCompilingManager::GetDependentTypeNames () const override private virtual
Return other asset types that should preferably be handled before this one.
Implements IAssetCompilingManager.
References GetDependentTypeNames().
Referenced by GetDependentTypeNames().
GetNumRemainingAssets()
int32 FSkinnedAssetCompilingManager::GetNumRemainingAssets () const override private virtual
Returns the number of remaining compilations.
Implements IAssetCompilingManager.
References GetNumRemainingAssets().
Referenced by GetNumRemainingAssets().
GetNumRemainingJobs()
int32 FSkinnedAssetCompilingManager::GetNumRemainingJobs () const
Returns the number of outstanding compilations.
GetStaticAssetTypeName()
FName FSkinnedAssetCompilingManager::GetStaticAssetTypeName () static
Get the name of the asset type this compiler handles.
References GetStaticAssetTypeName().
Referenced by GetStaticAssetTypeName().
GetThreadPool()
FQueuedThreadPool * FSkinnedAssetCompilingManager::GetThreadPool () const
Returns the threadpool where skinned asset compilation should be scheduled.
References GetThreadPool().
Referenced by GetThreadPool().
IsAsyncCompilationAllowed()
bool FSkinnedAssetCompilingManager::IsAsyncCompilationAllowed (USkinnedAsset * InSkinnedAsset) const
Returns if asynchronous compilation is allowed for this skinned asset.
References IsAsyncCompilationAllowed().
Referenced by IsAsyncCompilationAllowed().
IsAsyncCompilationEnabled()
bool FSkinnedAssetCompilingManager::IsAsyncCompilationEnabled () const
Returns true if the feature is currently activated.
OnPostReachabilityAnalysis()
void FSkinnedAssetCompilingManager::OnPostReachabilityAnalysis () private
References OnPostReachabilityAnalysis().
Referenced by OnPostReachabilityAnalysis().
OnPreGarbageCollect()
void FSkinnedAssetCompilingManager::OnPreGarbageCollect () private
References OnPreGarbageCollect().
Referenced by OnPreGarbageCollect().
PostCompilation() [1/2]
void FSkinnedAssetCompilingManager::PostCompilation (TArrayView< USkinnedAsset *const > InSkinnedAssets) private
References PostCompilation().
PostCompilation() [2/2]
void FSkinnedAssetCompilingManager::PostCompilation (USkinnedAsset * SkinnedAsset) private
References PostCompilation().
Referenced by PostCompilation(), and PostCompilation().
ProcessAsyncTasks()
void FSkinnedAssetCompilingManager::ProcessAsyncTasks (bool bLimitExecutionTime = false) override private virtual
Called once per frame, fetches completed tasks and applies them to the scene.
Implements IAssetCompilingManager.
References ProcessAsyncTasks().
Referenced by ProcessAsyncTasks().
ProcessSkinnedAssets()
void FSkinnedAssetCompilingManager::ProcessSkinnedAssets (bool bLimitExecutionTime, int32 MinBatchSize = 1) private
References ProcessSkinnedAssets().
Referenced by ProcessSkinnedAssets().
Reschedule()
void FSkinnedAssetCompilingManager::Reschedule () private
References Reschedule().
Referenced by Reschedule().
Shutdown()
void FSkinnedAssetCompilingManager::Shutdown () override virtual
Cancel any pending work and blocks until it is safe to shut down.
Implements IAssetCompilingManager.
References Shutdown().
Referenced by Shutdown().
UE_DEPRECATED()
FSkinnedAssetCompilingManager::UE_DEPRECATED (5. 1, "Use AddSkinnedAssets instead.") const
Adds skeletal meshes compiled asynchronously so they are monitored.
UpdateCompilationNotification()
void FSkinnedAssetCompilingManager::UpdateCompilationNotification () private
References UpdateCompilationNotification().
Referenced by UpdateCompilationNotification().
Friends And Related Symbol Documentation
FAssetCompilingManager
friend class FAssetCompilingManager friend
Definition at line 89 of file SkinnedAssetCompiler.h.
References FAssetCompilingManager.
Referenced by FAssetCompilingManager.
Field Documentation
bHasShutdown
bool FSkinnedAssetCompilingManager::bHasShutdown = false private
Definition at line 91 of file SkinnedAssetCompiler.h.
Notification
TUniquePtr<FAsyncCompilationNotification> FSkinnedAssetCompilingManager::Notification private
Definition at line 93 of file SkinnedAssetCompiler.h.
PostReachabilityAnalysisHandle
FDelegateHandle FSkinnedAssetCompilingManager::PostReachabilityAnalysisHandle private
Definition at line 103 of file SkinnedAssetCompiler.h.
PreGarbageCollectHandle
FDelegateHandle FSkinnedAssetCompilingManager::PreGarbageCollectHandle private
Definition at line 106 of file SkinnedAssetCompiler.h.
RegisteredSkinnedAsset
TSet<TWeakObjectPtr<USkinnedAsset> > FSkinnedAssetCompilingManager::RegisteredSkinnedAsset private
Definition at line 92 of file SkinnedAssetCompiler.h.
The documentation for this class was generated from the following file:
SkinnedAssetCompiler.h