Unreal Engine 5.6 C++ API: FIoStoreTocChunkInfo Struct Reference
FIoStoreTocChunkInfo Struct Reference
#include "IoDispatcher.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FIoStoreTocChunkInfo ()=default
FIoStoreTocChunkInfo (const FIoStoreTocChunkInfo &)=default
FIoStoreTocChunkInfo (FIoStoreTocChunkInfo &&)=default
FIoStoreTocChunkInfo & operator= (FIoStoreTocChunkInfo &&)=default
FIoStoreTocChunkInfo & operator= (FIoStoreTocChunkInfo &)=default
UE_DEPRECATED (5.5, "Hash of type FIoChunkHash is deprecated. Use ChunkHash of type FIoHash instead.") PRAGMA_DISABLE_DEPRECATION_WARNINGS FIoChunkHash Hash
Data Fields
bool bForceUncompressed
bool bHasValidFileName
bool bIsCompressed
bool bIsMemoryMapped
FIoHash ChunkHash
EIoChunkType ChunkType
uint64 CompressedSize
PRAGMA_ENABLE_DEPRECATION_WARNINGS FString FileName
FIoChunkId Id
uint32 NumCompressedBlocks
uint64 Offset
uint64 OffsetOnDisk
int32 PartitionIndex
uint64 Size
Detailed Description
Definition at line 525 of file IoDispatcher.h.
Constructor & Destructor Documentation
FIoStoreTocChunkInfo() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FIoStoreTocChunkInfo::FIoStoreTocChunkInfo () default
References FIoStoreTocChunkInfo().
Referenced by FIoStoreTocChunkInfo(), FIoStoreTocChunkInfo(), FIoStoreTocChunkInfo(), operator=(), and operator=().
FIoStoreTocChunkInfo() [2/3]
FIoStoreTocChunkInfo::FIoStoreTocChunkInfo (const FIoStoreTocChunkInfo &) default
References FIoStoreTocChunkInfo().
FIoStoreTocChunkInfo() [3/3]
FIoStoreTocChunkInfo::FIoStoreTocChunkInfo (FIoStoreTocChunkInfo &&) default
References FIoStoreTocChunkInfo().
Member Function Documentation
operator=() [1/2]
FIoStoreTocChunkInfo & FIoStoreTocChunkInfo::operator= (FIoStoreTocChunkInfo &&) default
References FIoStoreTocChunkInfo(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FIoStoreTocChunkInfo & FIoStoreTocChunkInfo::operator= (FIoStoreTocChunkInfo &) default
References FIoStoreTocChunkInfo().
UE_DEPRECATED()
FIoStoreTocChunkInfo::UE_DEPRECATED (5. 5, "Hash of type FIoChunkHash is deprecated. Use ChunkHash of type FIoHash instead.")
References Hash, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Field Documentation
bForceUncompressed
bool FIoStoreTocChunkInfo::bForceUncompressed
Definition at line 542 of file IoDispatcher.h.
bHasValidFileName
bool FIoStoreTocChunkInfo::bHasValidFileName
Definition at line 541 of file IoDispatcher.h.
bIsCompressed
bool FIoStoreTocChunkInfo::bIsCompressed
Definition at line 544 of file IoDispatcher.h.
bIsMemoryMapped
bool FIoStoreTocChunkInfo::bIsMemoryMapped
Definition at line 543 of file IoDispatcher.h.
ChunkHash
FIoHash FIoStoreTocChunkInfo::ChunkHash
Definition at line 528 of file IoDispatcher.h.
ChunkType
EIoChunkType FIoStoreTocChunkInfo::ChunkType
Definition at line 540 of file IoDispatcher.h.
CompressedSize
uint64 FIoStoreTocChunkInfo::CompressedSize
Definition at line 537 of file IoDispatcher.h.
FileName
PRAGMA_ENABLE_DEPRECATION_WARNINGS FString FIoStoreTocChunkInfo::FileName
Definition at line 533 of file IoDispatcher.h.
Id
FIoChunkId FIoStoreTocChunkInfo::Id
Definition at line 527 of file IoDispatcher.h.
NumCompressedBlocks
uint32 FIoStoreTocChunkInfo::NumCompressedBlocks
Definition at line 538 of file IoDispatcher.h.
Offset
uint64 FIoStoreTocChunkInfo::Offset
Definition at line 534 of file IoDispatcher.h.
OffsetOnDisk
uint64 FIoStoreTocChunkInfo::OffsetOnDisk
Definition at line 535 of file IoDispatcher.h.
PartitionIndex
int32 FIoStoreTocChunkInfo::PartitionIndex
Definition at line 539 of file IoDispatcher.h.
Size
uint64 FIoStoreTocChunkInfo::Size
Definition at line 536 of file IoDispatcher.h.
The documentation for this struct was generated from the following file:
IoDispatcher.h