Unreal Engine 5.6 C++ API: UE::String Namespace Reference
UE::String Namespace Reference
Namespaces
namespace Private
Enumerations
enum class EParseLinesOptions : uint32 { None = 0 , SkipEmpty = 1 << 0 , Trim = 1 << 1 }
enum class EParseTokensOptions : uint32 { None = 0 , IgnoreCase = 1 << 0 , SkipEmpty = 1 << 1 , Trim = 1 << 2 }
Functions
void BytesToHex (TConstArrayView< uint8 > Bytes, ANSICHAR *OutHex)
Convert an array of bytes to a non-null-terminated string of hex digits.
void BytesToHex (TConstArrayView< uint8 > Bytes, FAnsiStringBuilderBase &Builder)
Append an array of bytes to a string builder as hex digits.
void BytesToHex (TConstArrayView< uint8 > Bytes, FUtf8StringBuilderBase &Builder)
void BytesToHex (TConstArrayView< uint8 > Bytes, FWideStringBuilderBase &Builder)
void BytesToHex (TConstArrayView< uint8 > Bytes, UTF8CHAR *OutHex)
void BytesToHex (TConstArrayView< uint8 > Bytes, WIDECHAR *OutHex)
void BytesToHexLower (TConstArrayView< uint8 > Bytes, ANSICHAR *OutHex)
void BytesToHexLower (TConstArrayView< uint8 > Bytes, FAnsiStringBuilderBase &Builder)
void BytesToHexLower (TConstArrayView< uint8 > Bytes, FUtf8StringBuilderBase &Builder)
void BytesToHexLower (TConstArrayView< uint8 > Bytes, FWideStringBuilderBase &Builder)
void BytesToHexLower (TConstArrayView< uint8 > Bytes, UTF8CHAR *OutHex)
void BytesToHexLower (TConstArrayView< uint8 > Bytes, WIDECHAR *OutHex)
ENUM_CLASS_FLAGS (EParseLinesOptions)
ENUM_CLASS_FLAGS (EParseTokensOptions)
Private::FEscape Escape (FStringView Input)
Escape the string when appended to a string builder.
void EscapeTo (FStringView Input, FStringBuilderBase &Output)
Escape the string into the string builder.
int32 FindFirst (FUtf8StringView View, FUtf8StringView Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Search the view for the first occurrence of the search string.
int32 FindFirst (FWideStringView View, FWideStringView Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
int32 FindFirstChar (FUtf8StringView View, ANSICHAR Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Search the view for the first occurrence of the search character.
int32 FindFirstChar (FUtf8StringView View, UTF8CHAR Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
int32 FindFirstChar (FWideStringView View, WIDECHAR Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
int32 FindFirstOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Search the view for the first occurrence of any search string.
int32 FindFirstOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
int32 FindFirstOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
int32 FindFirstOfAnyChar (FUtf8StringView View, TConstArrayView< ANSICHAR > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Search the view for the first occurrence of any search character.
int32 FindFirstOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
int32 FindFirstOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
int32 FindLast (FUtf8StringView View, FUtf8StringView Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Search the view for the last occurrence of the search string.
int32 FindLast (FWideStringView View, FWideStringView Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
int32 FindLastChar (FUtf8StringView View, ANSICHAR Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Search the view for the last occurrence of the search character.
int32 FindLastChar (FUtf8StringView View, UTF8CHAR Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
int32 FindLastChar (FWideStringView View, WIDECHAR Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
int32 FindLastOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Search the view for the last occurrence of any search string.
int32 FindLastOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
int32 FindLastOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
int32 FindLastOfAnyChar (FUtf8StringView View, TConstArrayView< ANSICHAR > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Search the view for the last occurrence of any search character.
int32 FindLastOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
int32 FindLastOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
FString FromHostLineEndings (const FString &InString)
Replaces all Line Endings with "\n" line terminator.
FString FromHostLineEndings (FString &&InString)
void FromHostLineEndingsInline (FString &InString)
int32 HexToBytes (FUtf8StringView Hex, uint8 *OutBytes)
int32 HexToBytes (FWideStringView Hex, uint8 *OutBytes)
Convert an array of hex digits into an array of bytes.
bool IsNumeric (FUtf8StringView View)
bool IsNumeric (FWideStringView View)
Checks if the passed in string contains only digits, at most one dot, and optionally a +/- sign at the start.
bool IsNumericOnlyDigits (FUtf8StringView View)
bool IsNumericOnlyDigits (FWideStringView View)
Checks if the passed in string contains only digits.
template<typename RangeType, typename DelimiterType>
auto Join (RangeType &&Range, DelimiterType &&Delimiter) -> Private::TJoinBy< RangeType, FIdentityFunctor, DelimiterType >
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter.
template<typename RangeType, typename ProjectionType, typename DelimiterType>
auto JoinBy (RangeType &&Range, ProjectionType Projection, DelimiterType &&Delimiter) -> Private::TJoinBy< RangeType, ProjectionType, DelimiterType >
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter.
template<typename RangeType, typename ProjectionType, typename DelimiterType, typename CharType>
TStringBuilderBase< CharType > & JoinByTo (RangeType &&Range, ProjectionType Projection, DelimiterType &&Delimiter, TStringBuilderBase< CharType > &Builder)
Append every element of the range to the builder, separating the elements by the delimiter.
template<typename RangeType, typename DelimiterType, typename QuoteType>
auto JoinQuoted (RangeType &&Range, DelimiterType &&Delimiter, QuoteType &&Quote) -> Private::TJoinQuotedBy< RangeType, FIdentityFunctor, DelimiterType, QuoteType >
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
template<typename RangeType, typename ProjectionType, typename DelimiterType, typename QuoteType>
auto JoinQuotedBy (RangeType &&Range, ProjectionType Projection, DelimiterType &&Delimiter, QuoteType &&Quote) -> Private::TJoinQuotedBy< RangeType, ProjectionType, DelimiterType, QuoteType >
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
template<typename RangeType, typename ProjectionType, typename DelimiterType, typename QuoteType, typename CharType>
TStringBuilderBase< CharType > & JoinQuotedByTo (RangeType &&Range, ProjectionType Projection, DelimiterType &&Delimiter, QuoteType &&Quote, TStringBuilderBase< CharType > &Builder)
Append every element of the range to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
template<typename RangeType, typename DelimiterType, typename QuoteType, typename CharType>
TStringBuilderBase< CharType > & JoinQuotedTo (RangeType &&Range, DelimiterType &&Delimiter, QuoteType &&Quote, TStringBuilderBase< CharType > &Builder)
Append every element of the range to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
template<typename RangeType, typename DelimiterType, typename CharType>
TStringBuilderBase< CharType > & JoinTo (RangeType &&Range, DelimiterType &&Delimiter, TStringBuilderBase< CharType > &Builder)
Append every element of the range to the builder, separating the elements by the delimiter.
template<typename TupleType, typename DelimiterType>
auto JoinTuple (TupleType &&Tuple, DelimiterType &&Delimiter) -> Private::TJoinTupleBy< TupleType, FIdentityFunctor, DelimiterType >
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter.
template<typename TupleType, typename ProjectionType, typename DelimiterType>
auto JoinTupleBy (TupleType &&Tuple, ProjectionType Projection, DelimiterType &&Delimiter) -> Private::TJoinTupleBy< TupleType, ProjectionType, DelimiterType >
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter.
template<typename TupleType, typename ProjectionType, typename DelimiterType, typename CharType UE_REQUIRES>
TStringBuilderBase< CharType > & JoinTupleByTo (TupleType &&Tuple, ProjectionType Projection, DelimiterType &&Delimiter, TStringBuilderBase< CharType > &Builder)
Append every element of the tuple to the builder, separating the elements by the delimiter.
template<typename TupleType, typename DelimiterType, typename QuoteType>
auto JoinTupleQuoted (TupleType &&Tuple, DelimiterType &&Delimiter, QuoteType &&Quote) -> Private::TJoinTupleQuotedBy< TupleType, FIdentityFunctor, DelimiterType, QuoteType >
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
template<typename TupleType, typename ProjectionType, typename DelimiterType, typename QuoteType>
auto JoinTupleQuotedBy (TupleType &&Tuple, ProjectionType Projection, DelimiterType &&Delimiter, QuoteType &&Quote) -> Private::TJoinTupleQuotedBy< TupleType, ProjectionType, DelimiterType, QuoteType >
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
template<typename TupleType, typename ProjectionType, typename DelimiterType, typename QuoteType, typename CharType UE_REQUIRES>
TStringBuilderBase< CharType > & JoinTupleQuotedByTo (TupleType &&Tuple, ProjectionType Projection, DelimiterType &&Delimiter, QuoteType &&Quote, TStringBuilderBase< CharType > &Builder)
Append every element of the tuple to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
template<typename TupleType, typename DelimiterType, typename QuoteType, typename CharType>
TStringBuilderBase< CharType > & JoinTupleQuotedTo (TupleType &&Tuple, DelimiterType &&Delimiter, QuoteType &&Quote, TStringBuilderBase< CharType > &Builder)
Append every element of the tuple to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
template<typename TupleType, typename DelimiterType, typename CharType>
TStringBuilderBase< CharType > & JoinTupleTo (TupleType &&Tuple, DelimiterType &&Delimiter, TStringBuilderBase< CharType > &Builder)
Append every element of the tuple to the builder, separating the elements by the delimiter.
Private::TLowerCase< ANSICHAR > LowerCase (FAnsiStringView Input)
Convert the string to lowercase when appended to a string builder.
Private::TLowerCase< UTF8CHAR > LowerCase (FUtf8StringView Input)
Private::TLowerCase< WIDECHAR > LowerCase (FWideStringView Input)
void LowerCaseTo (FAnsiStringView Input, FAnsiStringBuilderBase &Output)
Convert the string to lowercase and append to the string builder.
void LowerCaseTo (FUtf8StringView Input, FUtf8StringBuilderBase &Output)
void LowerCaseTo (FWideStringView Input, FWideStringBuilderBase &Output)
template<typename OutputType, typename StringViewType>
void ParseLines (const StringViewType View, OutputType &Output, const EParseLinesOptions Options=EParseLinesOptions::None)
Parse lines in the input string as terminated by any of CRLF, CR, LF.
void ParseLines (FStringView View, TFunctionRef< void(FStringView)> Visitor, EParseLinesOptions Options=EParseLinesOptions::None)
Visit every line in the input string as terminated by any of CRLF, CR, LF.
void ParseLines (FUtf8StringView View, TFunctionRef< void(FUtf8StringView)> Visitor, EParseLinesOptions Options=EParseLinesOptions::None)
template<typename OutputType>
void ParseTokens (const FAnsiStringView View, const ANSICHAR Delimiter, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
Parses every token in the input string, as separated by the delimiter.
template<typename OutputType>
void ParseTokens (const FAnsiStringView View, const FAnsiStringView Delimiter, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
Parses every token in the input string, as separated by the delimiter.
template<typename OutputType>
void ParseTokens (const FUtf8StringView View, const FUtf8StringView Delimiter, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
template<typename OutputType>
void ParseTokens (const FUtf8StringView View, const UTF8CHAR Delimiter, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
template<typename OutputType>
void ParseTokens (const FWideStringView View, const FWideStringView Delimiter, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
template<typename OutputType>
void ParseTokens (const FWideStringView View, const WIDECHAR Delimiter, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokens (FAnsiStringView View, ANSICHAR Delimiter, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
Visit every token in the input string, as separated by the delimiter.
void ParseTokens (FAnsiStringView View, FAnsiStringView Delimiter, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
Visit every token in the input string, as separated by the delimiter.
void ParseTokens (FUtf8StringView View, FUtf8StringView Delimiter, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokens (FUtf8StringView View, UTF8CHAR Delimiter, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokens (FWideStringView View, FWideStringView Delimiter, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokens (FWideStringView View, WIDECHAR Delimiter, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
template<typename OutputType>
void ParseTokensMultiple (const FAnsiStringView View, const TConstArrayView< ANSICHAR > Delimiters, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
Parses every token in the input string, as separated by any of the delimiters.
template<typename OutputType>
void ParseTokensMultiple (const FAnsiStringView View, const TConstArrayView< FAnsiStringView > Delimiters, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
Parses every token in the input string, as separated by any of the delimiters.
template<typename OutputType>
void ParseTokensMultiple (const FUtf8StringView View, const TConstArrayView< FUtf8StringView > Delimiters, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
template<typename OutputType>
void ParseTokensMultiple (const FUtf8StringView View, const TConstArrayView< UTF8CHAR > Delimiters, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
template<typename OutputType>
void ParseTokensMultiple (const FWideStringView View, const TConstArrayView< FWideStringView > Delimiters, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
template<typename OutputType>
void ParseTokensMultiple (const FWideStringView View, const TConstArrayView< WIDECHAR > Delimiters, OutputType &Output, const EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokensMultiple (FAnsiStringView View, TConstArrayView< ANSICHAR > Delimiters, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
Visit every token in the input string, as separated by any of the delimiters.
void ParseTokensMultiple (FAnsiStringView View, TConstArrayView< FAnsiStringView > Delimiters, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
Visit every token in the input string, as separated by any of the delimiters.
void ParseTokensMultiple (FUtf8StringView View, TConstArrayView< FUtf8StringView > Delimiters, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokensMultiple (FUtf8StringView View, TConstArrayView< UTF8CHAR > Delimiters, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokensMultiple (FWideStringView View, TConstArrayView< FWideStringView > Delimiters, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
void ParseTokensMultiple (FWideStringView View, TConstArrayView< WIDECHAR > Delimiters, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options=EParseTokensOptions::None)
Private::TPascalCase< TCHAR > PascalCase (FStringView Input)
Convert the string to PascalCase when appended to a string builder.
void PascalCaseTo (FStringView Input, FStringBuilderBase &Output)
Convert the string to PascalCase and append to the string builder.
Private::FQuoteEscape QuoteEscape (FStringView Input)
Quote and escape the string when appended to a string builder.
void QuoteEscapeTo (FStringView Input, FStringBuilderBase &Output)
Quote and escape the string into the string builder.
template<typename CharType>
TStringView< CharType > RemoveFromEnd (const TStringView< CharType > View, const TStringView< CharType > Prefix, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
template<typename CharType>
TStringView< CharType > RemoveFromStart (const TStringView< CharType > View, const TStringView< CharType > Prefix, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitFirst (FAnsiStringView View, FAnsiStringView Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Split the view on the first occurrence of the search string.
bool SplitFirst (FUtf8StringView View, FUtf8StringView Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitFirst (FWideStringView View, FWideStringView Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitFirstChar (FAnsiStringView View, ANSICHAR Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Split the view on the first occurrence of the search character.
bool SplitFirstChar (FUtf8StringView View, UTF8CHAR Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitFirstChar (FWideStringView View, WIDECHAR Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitFirstOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Split the view on the first occurrence of any search string.
bool SplitFirstOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
bool SplitFirstOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
bool SplitFirstOfAnyChar (FAnsiStringView View, TConstArrayView< ANSICHAR > Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Split the view on the first occurrence of any search character.
bool SplitFirstOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
bool SplitFirstOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
bool SplitLast (FAnsiStringView View, FAnsiStringView Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Split the view on the last occurrence of the search string.
bool SplitLast (FUtf8StringView View, FUtf8StringView Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitLast (FWideStringView View, FWideStringView Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitLastChar (FAnsiStringView View, ANSICHAR Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
Split the view on the last occurrence of the search character.
bool SplitLastChar (FUtf8StringView View, UTF8CHAR Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitLastChar (FWideStringView View, WIDECHAR Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
bool SplitLastOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Split the view on the last occurrence of any search string.
bool SplitLastOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
bool SplitLastOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
bool SplitLastOfAnyChar (FAnsiStringView View, TConstArrayView< ANSICHAR > Search, FAnsiStringView &OutLeft, FAnsiStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
Split the view on the last occurrence of any search character.
bool SplitLastOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, FUtf8StringView &OutLeft, FUtf8StringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
bool SplitLastOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, FWideStringView &OutLeft, FWideStringView &OutRight, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive, int32 *OutMatchIndex=nullptr)
FString ToHostLineEndings (const FString &InString)
Replaces all Line Endings with the host platform line terminator.
FString ToHostLineEndings (FString &&InString)
void ToHostLineEndingsInline (FString &InString)
Private::TUpperCase< ANSICHAR > UpperCase (FAnsiStringView Input)
Convert the string to uppercase when appended to a string builder.
Private::TUpperCase< UTF8CHAR > UpperCase (FUtf8StringView Input)
Private::TUpperCase< WIDECHAR > UpperCase (FWideStringView Input)
void UpperCaseTo (FAnsiStringView Input, FAnsiStringBuilderBase &Output)
Convert the string to uppercase and append to the string builder.
void UpperCaseTo (FUtf8StringView Input, FUtf8StringBuilderBase &Output)
void UpperCaseTo (FWideStringView Input, FWideStringBuilderBase &Output)
Enumeration Type Documentation
EParseLinesOptions
enum class UE::String::EParseLinesOptions : uint32 strong
Enumerator
None
Use the default options when parsing lines.
SkipEmpty
Skip lines that are empty or, if trimming, only whitespace.
Trim
Trim whitespace from each parsed line.
Definition at line 16 of file ParseLines.h.
EParseTokensOptions
enum class UE::String::EParseTokensOptions : uint32 strong
Enumerator
None
Use the default options when parsing tokens.
IgnoreCase
Ignore case when comparing delimiters against the string.
SkipEmpty
Skip tokens that are empty or, if trimming, only whitespace.
Trim
Trim whitespace from each parsed token.
Definition at line 18 of file ParseTokens.h.
Function Documentation
BytesToHex() [1/6]
void UE::String::BytesToHex (TConstArrayView< uint8 > Bytes, ANSICHAR * OutHex)
Convert an array of bytes to a non-null-terminated string of hex digits.
Parameters
Bytes Array of bytes to convert.
OutHex [out] Array of at least 2*Bytes.Len() output characters.
References Bytes.
Referenced by FSHAHash::operator<<, FSHAHash::operator<<, and UE::Anim::DataModel::FHasherCopyToText::UpdateBytes().
BytesToHex() [2/6]
void UE::String::BytesToHex (TConstArrayView< uint8 > Bytes, FAnsiStringBuilderBase & Builder)
Append an array of bytes to a string builder as hex digits.
Parameters
Bytes Array of bytes to convert.
Builder Builder to append the converted string to.
References Bytes.
BytesToHex() [3/6]
void UE::String::BytesToHex (TConstArrayView< uint8 > Bytes, FUtf8StringBuilderBase & Builder)
References Bytes.
BytesToHex() [4/6]
void UE::String::BytesToHex (TConstArrayView< uint8 > Bytes, FWideStringBuilderBase & Builder)
References Bytes.
BytesToHex() [5/6]
void UE::String::BytesToHex (TConstArrayView< uint8 > Bytes, UTF8CHAR * OutHex)
References Bytes.
BytesToHex() [6/6]
void UE::String::BytesToHex (TConstArrayView< uint8 > Bytes, WIDECHAR * OutHex)
References Bytes.
BytesToHexLower() [1/6]
void UE::String::BytesToHexLower (TConstArrayView< uint8 > Bytes, ANSICHAR * OutHex)
References Bytes.
Referenced by FCbObjectId::operator<<, FIoChunkId::operator<<, FXxHash128::operator<<, and FXxHash64::operator<<.
BytesToHexLower() [2/6]
void UE::String::BytesToHexLower (TConstArrayView< uint8 > Bytes, FAnsiStringBuilderBase & Builder)
References Bytes.
BytesToHexLower() [3/6]
void UE::String::BytesToHexLower (TConstArrayView< uint8 > Bytes, FUtf8StringBuilderBase & Builder)
References Bytes.
BytesToHexLower() [4/6]
void UE::String::BytesToHexLower (TConstArrayView< uint8 > Bytes, FWideStringBuilderBase & Builder)
References Bytes.
BytesToHexLower() [5/6]
void UE::String::BytesToHexLower (TConstArrayView< uint8 > Bytes, UTF8CHAR * OutHex)
References Bytes.
BytesToHexLower() [6/6]
void UE::String::BytesToHexLower (TConstArrayView< uint8 > Bytes, WIDECHAR * OutHex)
References Bytes.
ENUM_CLASS_FLAGS() [1/2]
UE::String::ENUM_CLASS_FLAGS (EParseLinesOptions)
ENUM_CLASS_FLAGS() [2/2]
UE::String::ENUM_CLASS_FLAGS (EParseTokensOptions)
Escape()
Private::FEscape UE::String::Escape (FStringView Input) inline
Escape the string when appended to a string builder.
Example: Builder << String::Escape(Value);
Definition at line 32 of file Escape.h.
References Input.
EscapeTo()
void UE::String::EscapeTo (FStringView Input, FStringBuilderBase & Output)
Escape the string into the string builder.
Example: Escape("Tab is \t and \" is a quote.", Output) -> "Tab is \\t and \\\" is a quote."
References Input.
Referenced by UE::String::Private::operator<<().
FindFirst() [1/2]
int32 UE::String::FindFirst (FUtf8StringView View, FUtf8StringView Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Search the view for the first occurrence of the search string.
Parameters
View The string to search within.
Search The string to search for.
SearchCase Whether the comparison should ignore case.
Returns
The position at which the search string was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
Referenced by TStringView< CharType >::Find().
FindFirst() [2/2]
int32 UE::String::FindFirst (FWideStringView View, FWideStringView Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
FindFirstChar() [1/3]
int32 UE::String::FindFirstChar (FUtf8StringView View, ANSICHAR Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Search the view for the first occurrence of the search character.
Parameters
View The string to search within.
Search The character to search for.
SearchCase Whether the comparison should ignore case.
Returns
The position at which the search character was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
Referenced by TStringView< CharType >::FindChar().
FindFirstChar() [2/3]
int32 UE::String::FindFirstChar (FUtf8StringView View, UTF8CHAR Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
FindFirstChar() [3/3]
int32 UE::String::FindFirstChar (FWideStringView View, WIDECHAR Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
FindFirstOfAny() [1/3]
int32 UE::String::FindFirstOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Search the view for the first occurrence of any search string.
Parameters
View The string to search within.
Search The strings to search for.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search string that matched.
Returns
The position at which any search string was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
FindFirstOfAny() [2/3]
int32 UE::String::FindFirstOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FindFirstOfAny() [3/3]
int32 UE::String::FindFirstOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FindFirstOfAnyChar() [1/3]
int32 UE::String::FindFirstOfAnyChar (FUtf8StringView View, TConstArrayView< ANSICHAR > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Search the view for the first occurrence of any search character.
Parameters
View The string to search within.
Search The characters to search for.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search character that matched.
Returns
The position at which any search character was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
FindFirstOfAnyChar() [2/3]
int32 UE::String::FindFirstOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FindFirstOfAnyChar() [3/3]
int32 UE::String::FindFirstOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FindLast() [1/2]
int32 UE::String::FindLast (FUtf8StringView View, FUtf8StringView Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Search the view for the last occurrence of the search string.
Parameters
View The string to search within.
Search The string to search for.
SearchCase Whether the comparison should ignore case.
Returns
The position at which the search string was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
FindLast() [2/2]
int32 UE::String::FindLast (FWideStringView View, FWideStringView Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
FindLastChar() [1/3]
int32 UE::String::FindLastChar (FUtf8StringView View, ANSICHAR Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Search the view for the last occurrence of the search character.
Parameters
View The string to search within.
Search The character to search for.
SearchCase Whether the comparison should ignore case.
Returns
The position at which the search character was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
Referenced by TStringView< CharType >::FindLastChar().
FindLastChar() [2/3]
int32 UE::String::FindLastChar (FUtf8StringView View, UTF8CHAR Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
FindLastChar() [3/3]
int32 UE::String::FindLastChar (FWideStringView View, WIDECHAR Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
FindLastOfAny() [1/3]
int32 UE::String::FindLastOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Search the view for the last occurrence of any search string.
Parameters
View The string to search within.
Search The strings to search for.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search string that matched.
Returns
The position at which any search string was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
FindLastOfAny() [2/3]
int32 UE::String::FindLastOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FindLastOfAny() [3/3]
int32 UE::String::FindLastOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FindLastOfAnyChar() [1/3]
int32 UE::String::FindLastOfAnyChar (FUtf8StringView View, TConstArrayView< ANSICHAR > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Search the view for the last occurrence of any search character.
Parameters
View The string to search within.
Search The characters to search for.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search character that matched.
Returns
The position at which any search character was found, or INDEX_NONE if not found.
References ESearchCase::CaseSensitive.
FindLastOfAnyChar() [2/3]
int32 UE::String::FindLastOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FindLastOfAnyChar() [3/3]
int32 UE::String::FindLastOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
FromHostLineEndings() [1/2]
FString UE::String::FromHostLineEndings (const FString & InString)
Replaces all Line Endings with "\n" line terminator.
FromHostLineEndings() [2/2]
FString UE::String::FromHostLineEndings (FString && InString)
FromHostLineEndingsInline()
void UE::String::FromHostLineEndingsInline (FString & InString)
HexToBytes() [1/2]
int32 UE::String::HexToBytes (FUtf8StringView Hex, uint8 * OutBytes)
HexToBytes() [2/2]
int32 UE::String::HexToBytes (FWideStringView Hex, uint8 * OutBytes)
Convert an array of hex digits into an array of bytes.
Parameters
Hex Array of hex digits to convert.
OutBytes [out] Array of at least (Hex.Len()+1)/2 output bytes.
Returns
Number of bytes written to the output.
Referenced by FBlake3Hash::FBlake3Hash(), FBlake3Hash::FBlake3Hash(), FBlake3Hash::FBlake3Hash(), FIoHash::FIoHash(), FIoHash::FIoHash(), FIoHash::FIoHash(), and FSHAHash::FromString().
IsNumeric() [1/2]
bool UE::String::IsNumeric (FUtf8StringView View)
IsNumeric() [2/2]
bool UE::String::IsNumeric (FWideStringView View)
Checks if the passed in string contains only digits, at most one dot, and optionally a +/- sign at the start.
Parameters
View The string to check.
Returns
True if the string looks like a valid floating point number.
IsNumericOnlyDigits() [1/2]
bool UE::String::IsNumericOnlyDigits (FUtf8StringView View)
IsNumericOnlyDigits() [2/2]
bool UE::String::IsNumericOnlyDigits (FWideStringView View)
Checks if the passed in string contains only digits.
Parameters
View The string to check.
Returns
True if the string only contains numeric characters.
Referenced by FBulkDataCookedIndex::ParseFromPath().
Join()
template<typename RangeType, typename DelimiterType> auto UE::String::Join (RangeType && Range, DelimiterType && Delimiter) -> Private::TJoinBy<RangeType, FIdentityFunctor, DelimiterType> inline
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter.
Parameters
Range The range of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Returns
An anonymous object to append to a string builder.
Definition at line 208 of file Join.h.
References Forward().
JoinBy()
template<typename RangeType, typename ProjectionType, typename DelimiterType> auto UE::String::JoinBy (RangeType && Range, ProjectionType Projection, DelimiterType && Delimiter) -> Private::TJoinBy<RangeType, ProjectionType, DelimiterType> inline
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter.
Parameters
Range The range of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Returns
An anonymous object to append to a string builder.
Definition at line 159 of file Join.h.
References Forward(), MoveTemp(), and Projection().
Referenced by FSkinWeightProfileStack::GetUniqueId().
JoinByTo()
template<typename RangeType, typename ProjectionType, typename DelimiterType, typename CharType> TStringBuilderBase< CharType > & UE::String::JoinByTo (RangeType && Range, ProjectionType Projection, DelimiterType && Delimiter, TStringBuilderBase< CharType > & Builder) inline
Append every element of the range to the builder, separating the elements by the delimiter.
Parameters
Range The range of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 176 of file Join.h.
References Forward(), Invoke(), and Projection().
Referenced by JoinTo().
JoinQuoted()
template<typename RangeType, typename DelimiterType, typename QuoteType> auto UE::String::JoinQuoted (RangeType && Range, DelimiterType && Delimiter, QuoteType && Quote) -> Private::TJoinQuotedBy<RangeType, FIdentityFunctor, DelimiterType, QuoteType> inline
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
Parameters
Range The range of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Returns
An anonymous object to append to a string builder.
Definition at line 121 of file Join.h.
References Forward().
JoinQuotedBy()
template<typename RangeType, typename ProjectionType, typename DelimiterType, typename QuoteType> auto UE::String::JoinQuotedBy (RangeType && Range, ProjectionType Projection, DelimiterType && Delimiter, QuoteType && Quote) -> Private::TJoinQuotedBy<RangeType, ProjectionType, DelimiterType, QuoteType> inline
Create an object that can be appended to a string builder to append every element of the range to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
Parameters
Range The range of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Returns
An anonymous object to append to a string builder.
Definition at line 67 of file Join.h.
References Forward(), MoveTemp(), and Projection().
JoinQuotedByTo()
template<typename RangeType, typename ProjectionType, typename DelimiterType, typename QuoteType, typename CharType> TStringBuilderBase< CharType > & UE::String::JoinQuotedByTo (RangeType && Range, ProjectionType Projection, DelimiterType && Delimiter, QuoteType && Quote, TStringBuilderBase< CharType > & Builder) inline
Append every element of the range to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
Parameters
Range The range of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 86 of file Join.h.
References Forward(), Invoke(), and Projection().
Referenced by JoinQuotedTo().
JoinQuotedTo()
template<typename RangeType, typename DelimiterType, typename QuoteType, typename CharType> TStringBuilderBase< CharType > & UE::String::JoinQuotedTo (RangeType && Range, DelimiterType && Delimiter, QuoteType && Quote, TStringBuilderBase< CharType > & Builder) inline
Append every element of the range to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
Parameters
Range The range of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 139 of file Join.h.
References Forward(), and JoinQuotedByTo().
JoinTo()
template<typename RangeType, typename DelimiterType, typename CharType> TStringBuilderBase< CharType > & UE::String::JoinTo (RangeType && Range, DelimiterType && Delimiter, TStringBuilderBase< CharType > & Builder) inline
Append every element of the range to the builder, separating the elements by the delimiter.
Parameters
Range The range of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 224 of file Join.h.
References Forward(), and JoinByTo().
JoinTuple()
template<typename TupleType, typename DelimiterType> auto UE::String::JoinTuple (TupleType && Tuple, DelimiterType && Delimiter) -> Private::TJoinTupleBy<TupleType, FIdentityFunctor, DelimiterType> inline
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter.
Parameters
Tuple The tuple of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Returns
An anonymous object to append to a string builder.
Definition at line 385 of file Join.h.
References Forward().
JoinTupleBy()
template<typename TupleType, typename ProjectionType, typename DelimiterType> auto UE::String::JoinTupleBy (TupleType && Tuple, ProjectionType Projection, DelimiterType && Delimiter) -> Private::TJoinTupleBy<TupleType, ProjectionType, DelimiterType> inline
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter.
Parameters
Tuple The tuple of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Returns
An anonymous object to append to a string builder.
Definition at line 335 of file Join.h.
References Forward(), MoveTemp(), and Projection().
JoinTupleByTo()
template<typename TupleType, typename ProjectionType, typename DelimiterType, typename CharType UE_REQUIRES> TStringBuilderBase< CharType > & UE::String::JoinTupleByTo (TupleType && Tuple, ProjectionType Projection, DelimiterType && Delimiter, TStringBuilderBase< CharType > & Builder) inline
Append every element of the tuple to the builder, separating the elements by the delimiter.
Parameters
Tuple The tuple of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 353 of file Join.h.
References Invoke(), Projection(), and VisitTupleElements().
Referenced by JoinTupleTo().
JoinTupleQuoted()
template<typename TupleType, typename DelimiterType, typename QuoteType> auto UE::String::JoinTupleQuoted (TupleType && Tuple, DelimiterType && Delimiter, QuoteType && Quote) -> Private::TJoinTupleQuotedBy<TupleType, FIdentityFunctor, DelimiterType, QuoteType> inline
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
Parameters
Tuple The tuple of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Returns
An anonymous object to append to a string builder.
Definition at line 297 of file Join.h.
References Forward().
JoinTupleQuotedBy()
template<typename TupleType, typename ProjectionType, typename DelimiterType, typename QuoteType> auto UE::String::JoinTupleQuotedBy (TupleType && Tuple, ProjectionType Projection, DelimiterType && Delimiter, QuoteType && Quote) -> Private::TJoinTupleQuotedBy<TupleType, ProjectionType, DelimiterType, QuoteType> inline
Create an object that can be appended to a string builder to append every element of the tuple to the builder, separating the elements by the delimiter and surrounding every element on both sides with a quote.
Parameters
Tuple The tuple of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Returns
An anonymous object to append to a string builder.
Definition at line 242 of file Join.h.
References Forward(), MoveTemp(), and Projection().
JoinTupleQuotedByTo()
template<typename TupleType, typename ProjectionType, typename DelimiterType, typename QuoteType, typename CharType UE_REQUIRES> TStringBuilderBase< CharType > & UE::String::JoinTupleQuotedByTo (TupleType && Tuple, ProjectionType Projection, DelimiterType && Delimiter, QuoteType && Quote, TStringBuilderBase< CharType > & Builder) inline
Append every element of the tuple to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
Parameters
Tuple The tuple of elements to join and append.
Projection The projection to apply to the elements before appending them.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 262 of file Join.h.
References Invoke(), Projection(), and VisitTupleElements().
Referenced by JoinTupleQuotedTo().
JoinTupleQuotedTo()
template<typename TupleType, typename DelimiterType, typename QuoteType, typename CharType> TStringBuilderBase< CharType > & UE::String::JoinTupleQuotedTo (TupleType && Tuple, DelimiterType && Delimiter, QuoteType && Quote, TStringBuilderBase< CharType > & Builder) inline
Append every element of the tuple to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
Parameters
Tuple The tuple of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Quote The quote to append on both sides of each element.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 315 of file Join.h.
References Forward(), and JoinTupleQuotedByTo().
JoinTupleTo()
template<typename TupleType, typename DelimiterType, typename CharType> TStringBuilderBase< CharType > & UE::String::JoinTupleTo (TupleType && Tuple, DelimiterType && Delimiter, TStringBuilderBase< CharType > & Builder) inline
Append every element of the tuple to the builder, separating the elements by the delimiter.
Parameters
Tuple The tuple of elements to join and append.
Delimiter The delimiter to append as a separator for the elements.
Builder The builder to append to.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 401 of file Join.h.
References Forward(), and JoinTupleByTo().
LowerCase() [1/3]
Private::TLowerCase< ANSICHAR > UE::String::LowerCase (FAnsiStringView Input) inline
Convert the string to lowercase when appended to a string builder.
Note
Only ASCII characters will be converted, similar to CRT to[w]upper() with the standard C locale.
Parameters
Input The string to convert to lowercase.
Returns
An anonymous object to append to a string builder.
Builder << String::LowerCase(TEXTVIEW("EXAMPLE")); // Builder now contains "example"
Definition at line 105 of file CaseConversion.h.
References Input.
LowerCase() [2/3]
Private::TLowerCase< UTF8CHAR > UE::String::LowerCase (FUtf8StringView Input) inline
Definition at line 109 of file CaseConversion.h.
References Input.
LowerCase() [3/3]
Private::TLowerCase< WIDECHAR > UE::String::LowerCase (FWideStringView Input) inline
Definition at line 113 of file CaseConversion.h.
References Input.
LowerCaseTo() [1/3]
void UE::String::LowerCaseTo (FAnsiStringView Input, FAnsiStringBuilderBase & Output)
Convert the string to lowercase and append to the string builder.
Note
Only ASCII characters will be converted, similar to CRT to[w]upper() with the standard C locale.
Parameters
Input The string to convert to lowercase.
Output The string builder to append the converted string to.
LowerCaseTo(TEXTVIEW("EXAMPLE"), Output); // Output now contains "example"
References Input.
LowerCaseTo() [2/3]
void UE::String::LowerCaseTo (FUtf8StringView Input, FUtf8StringBuilderBase & Output)
References Input.
LowerCaseTo() [3/3]
void UE::String::LowerCaseTo (FWideStringView Input, FWideStringBuilderBase & Output)
References Input.
ParseLines() [1/3]
template<typename OutputType, typename StringViewType> void UE::String::ParseLines (const StringViewType View, OutputType & Output, const EParseLinesOptions Options = EParseLinesOptions::None) inline
Parse lines in the input string as terminated by any of CRLF, CR, LF.
Output strings are sub-views of the input view and have the same lifetime as the input view. By default, empty lines are collected.
Parameters
View A view of the string to split into lines.
Output The output to add parsed lines to by calling Output.Add(FStringView).
Options Flags to modify the default behavior.
Definition at line 57 of file ParseLines.h.
References Line, None, UE::Options, and ParseLines().
ParseLines() [2/3]
void UE::String::ParseLines (FStringView View, TFunctionRef< void(FStringView)> Visitor, EParseLinesOptions Options = EParseLinesOptions::None)
Visit every line in the input string as terminated by any of CRLF, CR, LF.
By default, empty lines are visited.
Parameters
View A view of the string to split into lines.
Visitor A function that is called for each line.
Options Flags to modify the default behavior.
References None, and UE::Options.
Referenced by ParseLines().
ParseLines() [3/3]
void UE::String::ParseLines (FUtf8StringView View, TFunctionRef< void(FUtf8StringView)> Visitor, EParseLinesOptions Options = EParseLinesOptions::None)
References None, and UE::Options.
ParseTokens() [1/12]
template<typename OutputType> void UE::String::ParseTokens (const FAnsiStringView View, const ANSICHAR Delimiter, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Parses every token in the input string, as separated by the delimiter.
Output strings are sub-views of the input view and have the same lifetime as the input view. By default, comparisons with the delimiter are case-sensitive and empty tokens are visited.
Parameters
View A view of the string to split into tokens.
Delimiter A delimiter character to split on.
Output The output to add parsed tokens to by calling Output.Add(FStringView).
Options Flags to modify the default behavior.
Definition at line 70 of file ParseTokens.h.
References None, UE::Options, and ParseTokens().
ParseTokens() [2/12]
template<typename OutputType> void UE::String::ParseTokens (const FAnsiStringView View, const FAnsiStringView Delimiter, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Parses every token in the input string, as separated by the delimiter.
Output strings are sub-views of the input view and have the same lifetime as the input view. By default, comparisons with the delimiter are case-sensitive and empty tokens are visited.
Parameters
View A view of the string to split into tokens.
Delimiter A non-empty delimiter to split on.
Output The output to add parsed tokens to by calling Output.Add(FStringView).
Options Flags to modify the default behavior.
Definition at line 135 of file ParseTokens.h.
References None, UE::Options, and ParseTokens().
ParseTokens() [3/12]
template<typename OutputType> void UE::String::ParseTokens (const FUtf8StringView View, const FUtf8StringView Delimiter, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 153 of file ParseTokens.h.
References None, UE::Options, and ParseTokens().
ParseTokens() [4/12]
template<typename OutputType> void UE::String::ParseTokens (const FUtf8StringView View, const UTF8CHAR Delimiter, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 88 of file ParseTokens.h.
References None, UE::Options, and ParseTokens().
ParseTokens() [5/12]
template<typename OutputType> void UE::String::ParseTokens (const FWideStringView View, const FWideStringView Delimiter, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 144 of file ParseTokens.h.
References None, UE::Options, and ParseTokens().
ParseTokens() [6/12]
template<typename OutputType> void UE::String::ParseTokens (const FWideStringView View, const WIDECHAR Delimiter, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 79 of file ParseTokens.h.
References None, UE::Options, and ParseTokens().
ParseTokens() [7/12]
void UE::String::ParseTokens (FAnsiStringView View, ANSICHAR Delimiter, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
Visit every token in the input string, as separated by the delimiter.
By default, comparisons with the delimiter are case-sensitive and empty tokens are visited.
Parameters
View A view of the string to split into tokens.
Delimiter A delimiter character to split on.
Visitor A function that is called for each token.
Options Flags to modify the default behavior.
References None, and UE::Options.
Referenced by ParseTokens(), ParseTokens(), ParseTokens(), ParseTokens(), ParseTokens(), and ParseTokens().
ParseTokens() [8/12]
void UE::String::ParseTokens (FAnsiStringView View, FAnsiStringView Delimiter, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
Visit every token in the input string, as separated by the delimiter.
By default, comparisons with the delimiter are case-sensitive and empty tokens are visited.
Parameters
View A view of the string to split into tokens.
Delimiter A non-empty delimiter to split on.
Visitor A function that is called for each token.
Options Flags to modify the default behavior.
References None, and UE::Options.
ParseTokens() [9/12]
void UE::String::ParseTokens (FUtf8StringView View, FUtf8StringView Delimiter, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
ParseTokens() [10/12]
void UE::String::ParseTokens (FUtf8StringView View, UTF8CHAR Delimiter, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
ParseTokens() [11/12]
void UE::String::ParseTokens (FWideStringView View, FWideStringView Delimiter, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
ParseTokens() [12/12]
void UE::String::ParseTokens (FWideStringView View, WIDECHAR Delimiter, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
ParseTokensMultiple() [1/12]
template<typename OutputType> void UE::String::ParseTokensMultiple (const FAnsiStringView View, const TConstArrayView< ANSICHAR > Delimiters, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Parses every token in the input string, as separated by any of the delimiters.
Output strings are sub-views of the input view and have the same lifetime as the input view. By default, comparisons with delimiters are case-sensitive and empty tokens are visited.
Parameters
View A view of the string to split into tokens.
Delimiters An array of delimiter characters to split on.
Output The output to add parsed tokens to by calling Output.Add(FStringView).
Options Flags to modify the default behavior.
Definition at line 200 of file ParseTokens.h.
References None, UE::Options, and ParseTokensMultiple().
ParseTokensMultiple() [2/12]
template<typename OutputType> void UE::String::ParseTokensMultiple (const FAnsiStringView View, const TConstArrayView< FAnsiStringView > Delimiters, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Parses every token in the input string, as separated by any of the delimiters.
Output strings are sub-views of the input view and have the same lifetime as the input view. By default, comparisons with delimiters are case-sensitive and empty tokens are visited. Behavior is undefined when delimiters overlap each other, such as the delimiters ("AB, "BC") and the input string "1ABC2".
Parameters
View A view of the string to split into tokens.
Delimiters An array of non-overlapping non-empty delimiters to split on.
Output The output to add parsed tokens to by calling Output.Add(FStringView).
Options Flags to modify the default behavior.
Definition at line 269 of file ParseTokens.h.
References None, UE::Options, and ParseTokensMultiple().
ParseTokensMultiple() [3/12]
template<typename OutputType> void UE::String::ParseTokensMultiple (const FUtf8StringView View, const TConstArrayView< FUtf8StringView > Delimiters, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 287 of file ParseTokens.h.
References None, UE::Options, and ParseTokensMultiple().
ParseTokensMultiple() [4/12]
template<typename OutputType> void UE::String::ParseTokensMultiple (const FUtf8StringView View, const TConstArrayView< UTF8CHAR > Delimiters, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 218 of file ParseTokens.h.
References None, UE::Options, and ParseTokensMultiple().
ParseTokensMultiple() [5/12]
template<typename OutputType> void UE::String::ParseTokensMultiple (const FWideStringView View, const TConstArrayView< FWideStringView > Delimiters, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 278 of file ParseTokens.h.
References None, UE::Options, and ParseTokensMultiple().
ParseTokensMultiple() [6/12]
template<typename OutputType> void UE::String::ParseTokensMultiple (const FWideStringView View, const TConstArrayView< WIDECHAR > Delimiters, OutputType & Output, const EParseTokensOptions Options = EParseTokensOptions::None) inline
Definition at line 209 of file ParseTokens.h.
References None, UE::Options, and ParseTokensMultiple().
ParseTokensMultiple() [7/12]
void UE::String::ParseTokensMultiple (FAnsiStringView View, TConstArrayView< ANSICHAR > Delimiters, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
Visit every token in the input string, as separated by any of the delimiters.
By default, comparisons with delimiters are case-sensitive and empty tokens are visited.
Parameters
View A view of the string to split into tokens.
Delimiters An array of delimiter characters to split on.
Visitor A function that is called for each token.
Options Flags to modify the default behavior.
References None, and UE::Options.
Referenced by ParseTokensMultiple(), ParseTokensMultiple(), ParseTokensMultiple(), ParseTokensMultiple(), ParseTokensMultiple(), and ParseTokensMultiple().
ParseTokensMultiple() [8/12]
void UE::String::ParseTokensMultiple (FAnsiStringView View, TConstArrayView< FAnsiStringView > Delimiters, TFunctionRef< void(FAnsiStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
Visit every token in the input string, as separated by any of the delimiters.
By default, comparisons with delimiters are case-sensitive and empty tokens are visited. Behavior is undefined when delimiters overlap each other, such as the delimiters ("AB, "BC") and the input string "1ABC2".
Parameters
View A view of the string to split into tokens.
Delimiters An array of non-overlapping non-empty delimiters to split on.
Visitor A function that is called for each token.
Options Flags to modify the default behavior.
References None, and UE::Options.
ParseTokensMultiple() [9/12]
void UE::String::ParseTokensMultiple (FUtf8StringView View, TConstArrayView< FUtf8StringView > Delimiters, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
ParseTokensMultiple() [10/12]
void UE::String::ParseTokensMultiple (FUtf8StringView View, TConstArrayView< UTF8CHAR > Delimiters, TFunctionRef< void(FUtf8StringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
ParseTokensMultiple() [11/12]
void UE::String::ParseTokensMultiple (FWideStringView View, TConstArrayView< FWideStringView > Delimiters, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
ParseTokensMultiple() [12/12]
void UE::String::ParseTokensMultiple (FWideStringView View, TConstArrayView< WIDECHAR > Delimiters, TFunctionRef< void(FWideStringView)> Visitor, EParseTokensOptions Options = EParseTokensOptions::None)
References None, and UE::Options.
PascalCase()
Private::TPascalCase< TCHAR > UE::String::PascalCase (FStringView Input) inline
Convert the string to PascalCase when appended to a string builder.
Note
Only ASCII characters will be converted.
Parameters
Input The string to convert to PascalCase.
Returns
An anonymous object to append to a string builder.
Builder << String::PascalCase(TEXTVIEW("EXAMPLE TEXT")); // Builder now contains "ExampleText"
Definition at line 129 of file CaseConversion.h.
PascalCaseTo()
void UE::String::PascalCaseTo (FStringView Input, FStringBuilderBase & Output)
Convert the string to PascalCase and append to the string builder.
Note
Only ASCII characters will be converted.
Parameters
Input The string to convert to PascalCase.
Output The string builder to append the converted string to.
PascalCaseTo(TEXTVIEW("EXAMPLE TEXT"), Output); // Output now contains "ExampleText"
References Input.
QuoteEscape()
Private::FQuoteEscape UE::String::QuoteEscape (FStringView Input) inline
Quote and escape the string when appended to a string builder.
Example: Builder << String::QuoteEscape(Value);
Definition at line 46 of file Escape.h.
References Input.
QuoteEscapeTo()
void UE::String::QuoteEscapeTo (FStringView Input, FStringBuilderBase & Output)
Quote and escape the string into the string builder.
Example: QuoteEscape("Tab is \t and \" is a quote.", Output) -> "\"Tab is \\t and \\\" is a quote.\""
References Input.
Referenced by UE::String::Private::operator<<().
RemoveFromEnd()
template<typename CharType> TStringView< CharType > UE::String::RemoveFromEnd (const TStringView< CharType > View, const TStringView< CharType > Prefix, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) inline nodiscard
Definition at line 18 of file RemoveFrom.h.
References ESearchCase::CaseSensitive, TStringView< CharType >::EndsWith(), TStringView< CharType >::LeftChop(), and TStringView< CharType >::Len().
RemoveFromStart()
template<typename CharType> TStringView< CharType > UE::String::RemoveFromStart (const TStringView< CharType > View, const TStringView< CharType > Prefix, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) inline nodiscard
Definition at line 12 of file RemoveFrom.h.
References ESearchCase::CaseSensitive, TStringView< CharType >::Len(), TStringView< CharType >::RightChop(), and TStringView< CharType >::StartsWith().
SplitFirst() [1/3]
bool UE::String::SplitFirst (FAnsiStringView View, FAnsiStringView Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Split the view on the first occurrence of the search string.
Parameters
View The string to split.
Search The string to search for and split on.
OutLeft Receives the part of the view to the left of the search string if it is found.
OutRight Receives the part of the view to the right of the search string if it is found.
SearchCase Whether the comparison should ignore case.
Returns
true if the search string was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitFirst() [2/3]
bool UE::String::SplitFirst (FUtf8StringView View, FUtf8StringView Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitFirst() [3/3]
bool UE::String::SplitFirst (FWideStringView View, FWideStringView Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitFirstChar() [1/3]
bool UE::String::SplitFirstChar (FAnsiStringView View, ANSICHAR Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Split the view on the first occurrence of the search character.
Parameters
View The string to split.
Search The character to search for and split on.
OutLeft Receives the part of the view to the left of the search character if it is found.
OutRight Receives the part of the view to the right of the search character if it is found.
SearchCase Whether the comparison should ignore case.
Returns
true if the search character was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitFirstChar() [2/3]
bool UE::String::SplitFirstChar (FUtf8StringView View, UTF8CHAR Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitFirstChar() [3/3]
bool UE::String::SplitFirstChar (FWideStringView View, WIDECHAR Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitFirstOfAny() [1/3]
bool UE::String::SplitFirstOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Split the view on the first occurrence of any search string.
Parameters
View The string to split.
Search The strings to search for and split on.
OutLeft Receives the part of the view to the left of the search string if it is found.
OutRight Receives the part of the view to the right of the search string if it is found.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search string that matched.
Returns
true if the search string was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitFirstOfAny() [2/3]
bool UE::String::SplitFirstOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
SplitFirstOfAny() [3/3]
bool UE::String::SplitFirstOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
SplitFirstOfAnyChar() [1/3]
bool UE::String::SplitFirstOfAnyChar (FAnsiStringView View, TConstArrayView< ANSICHAR > Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Split the view on the first occurrence of any search character.
Parameters
View The string to split.
Search The characters to search for and split on.
OutLeft Receives the part of the view to the left of the search character if it is found.
OutRight Receives the part of the view to the right of the search character if it is found.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search character that matched.
Returns
true if the search character was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitFirstOfAnyChar() [2/3]
bool UE::String::SplitFirstOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
SplitFirstOfAnyChar() [3/3]
bool UE::String::SplitFirstOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
SplitLast() [1/3]
bool UE::String::SplitLast (FAnsiStringView View, FAnsiStringView Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Split the view on the last occurrence of the search string.
Parameters
View The string to split.
Search The string to search for and split on.
OutLeft Receives the part of the view to the left of the search string if it is found.
OutRight Receives the part of the view to the right of the search string if it is found.
SearchCase Whether the comparison should ignore case.
Returns
true if the search string was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitLast() [2/3]
bool UE::String::SplitLast (FUtf8StringView View, FUtf8StringView Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitLast() [3/3]
bool UE::String::SplitLast (FWideStringView View, FWideStringView Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitLastChar() [1/3]
bool UE::String::SplitLastChar (FAnsiStringView View, ANSICHAR Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
Split the view on the last occurrence of the search character.
Parameters
View The string to split.
Search The character to search for and split on.
OutLeft Receives the part of the view to the left of the search character if it is found.
OutRight Receives the part of the view to the right of the search character if it is found.
SearchCase Whether the comparison should ignore case.
Returns
true if the search character was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitLastChar() [2/3]
bool UE::String::SplitLastChar (FUtf8StringView View, UTF8CHAR Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitLastChar() [3/3]
bool UE::String::SplitLastChar (FWideStringView View, WIDECHAR Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive)
References ESearchCase::CaseSensitive.
SplitLastOfAny() [1/3]
bool UE::String::SplitLastOfAny (FAnsiStringView View, TConstArrayView< FAnsiStringView > Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Split the view on the last occurrence of any search string.
Parameters
View The string to split.
Search The strings to search for and split on.
OutLeft Receives the part of the view to the left of the search string if it is found.
OutRight Receives the part of the view to the right of the search string if it is found.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search string that matched.
Returns
true if the search string was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitLastOfAny() [2/3]
bool UE::String::SplitLastOfAny (FUtf8StringView View, TConstArrayView< FUtf8StringView > Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
SplitLastOfAny() [3/3]
bool UE::String::SplitLastOfAny (FWideStringView View, TConstArrayView< FWideStringView > Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
SplitLastOfAnyChar() [1/3]
bool UE::String::SplitLastOfAnyChar (FAnsiStringView View, TConstArrayView< ANSICHAR > Search, FAnsiStringView & OutLeft, FAnsiStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
Split the view on the last occurrence of any search character.
Parameters
View The string to split.
Search The characters to search for and split on.
OutLeft Receives the part of the view to the left of the search character if it is found.
OutRight Receives the part of the view to the right of the search character if it is found.
SearchCase Whether the comparison should ignore case.
OutMatchIndex Receives the index of the search character that matched.
Returns
true if the search character was found and the outputs were written, otherwise false.
References ESearchCase::CaseSensitive.
SplitLastOfAnyChar() [2/3]
bool UE::String::SplitLastOfAnyChar (FUtf8StringView View, TConstArrayView< UTF8CHAR > Search, FUtf8StringView & OutLeft, FUtf8StringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
SplitLastOfAnyChar() [3/3]
bool UE::String::SplitLastOfAnyChar (FWideStringView View, TConstArrayView< WIDECHAR > Search, FWideStringView & OutLeft, FWideStringView & OutRight, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive, int32 * OutMatchIndex = nullptr)
References ESearchCase::CaseSensitive.
ToHostLineEndings() [1/2]
FString UE::String::ToHostLineEndings (const FString & InString)
Replaces all Line Endings with the host platform line terminator.
ToHostLineEndings() [2/2]
FString UE::String::ToHostLineEndings (FString && InString)
ToHostLineEndingsInline()
void UE::String::ToHostLineEndingsInline (FString & InString)
UpperCase() [1/3]
Private::TUpperCase< ANSICHAR > UE::String::UpperCase (FAnsiStringView Input) inline
Convert the string to uppercase when appended to a string builder.
Note
Only ASCII characters will be converted, similar to CRT to[w]upper() with the standard C locale.
Parameters
Input The string to convert to uppercase.
Returns
An anonymous object to append to a string builder.
Builder << String::UpperCase(TEXTVIEW("example")); // Builder now contains "EXAMPLE"
Definition at line 81 of file CaseConversion.h.
References Input.
UpperCase() [2/3]
Private::TUpperCase< UTF8CHAR > UE::String::UpperCase (FUtf8StringView Input) inline
Definition at line 85 of file CaseConversion.h.
References Input.
UpperCase() [3/3]
Private::TUpperCase< WIDECHAR > UE::String::UpperCase (FWideStringView Input) inline
Definition at line 89 of file CaseConversion.h.
References Input.
UpperCaseTo() [1/3]
void UE::String::UpperCaseTo (FAnsiStringView Input, FAnsiStringBuilderBase & Output)
Convert the string to uppercase and append to the string builder.
Note
Only ASCII characters will be converted, similar to CRT to[w]upper() with the standard C locale.
Parameters
Input The string to convert to uppercase.
Output The string builder to append the converted string to.
UpperCaseTo(TEXTVIEW("example"), Output); // Output now contains "EXAMPLE"
References Input.
UpperCaseTo() [2/3]
void UE::String::UpperCaseTo (FUtf8StringView Input, FUtf8StringBuilderBase & Output)
References Input.
UpperCaseTo() [3/3]
void UE::String::UpperCaseTo (FWideStringView Input, FWideStringBuilderBase & Output)
References Input.