Unreal Engine 5.6 C++ API: FSlateRoundedBoxBrush Struct Reference
FSlateRoundedBoxBrush Struct Reference
#include "SlateRoundedBoxBrush.h"
Public Member Functions
template<typename FillColorType>
FORCENOINLINE FSlateRoundedBoxBrush (const FillColorType &InColor, const FVector2f &InImageSize)
template<typename FillColorType, typename OutlineColorType>
FORCENOINLINE FSlateRoundedBoxBrush (const FillColorType &InColor, const OutlineColorType &InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector)
Creates and initializes a new instance with the specified color and rounds based on height.
template<typename FillColorType>
FORCENOINLINE FSlateRoundedBoxBrush (const FillColorType &InColor, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector)
Creates and initializes a new instance with the specified color and rounds based on height.
template<typename FillColorType>
FORCENOINLINE FSlateRoundedBoxBrush (const FillColorType &InColor, const UE::Slate::FDeprecateVector2DResult &InImageSize)
template<typename FillColorType, typename OutlineColorType, typename RadiusType>
FORCENOINLINE FSlateRoundedBoxBrush (const FillColorType &InColor, RadiusType InRadius, const OutlineColorType &InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector)
Creates and initializes a new instance with the specified color and corner radius.
template<typename FillColorType, typename RadiusType>
FORCENOINLINE FSlateRoundedBoxBrush (const FillColorType &InColor, RadiusType InRadius, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector)
Creates and initializes a new instance with the specified color and corner radius.
template<typename FillColorType, typename OutlineColorType>
FORCENOINLINE FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType &FillColorTint, const OutlineColorType &InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType=ESlateBrushTileType::NoTile)
Creates and initializes a new instance with the specified color and rounds based on height.
template<typename FillColorType>
FORCENOINLINE FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType &FillColorTint, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType=ESlateBrushTileType::NoTile)
template<typename FillColorType, typename OutlineColorType, typename RadiusType>
FORCENOINLINE FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType &FillColorTint, RadiusType InRadius, const OutlineColorType &InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType=ESlateBrushTileType::NoTile)
Creates and initializes a new instance with the specified color and corner radius.
template<typename FillColorType, typename RadiusType>
FORCENOINLINE FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType &FillColorTint, RadiusType InRadius, const UE::Slate::FDeprecateVector2DParameter &InImageSize=FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType=ESlateBrushTileType::NoTile)
Detailed Description
Definition at line 9 of file SlateRoundedBoxBrush.h.
Constructor & Destructor Documentation
FSlateRoundedBoxBrush() [1/10]
template<typename FillColorType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FillColorType & InColor, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector) inline
Creates and initializes a new instance with the specified color and rounds based on height.
Parameters
InColor Linear Fill Color
Definition at line 19 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
Referenced by FSlateRoundedBoxBrush(), and FSlateRoundedBoxBrush().
FSlateRoundedBoxBrush() [2/10]
template<typename FillColorType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FillColorType & InColor, const UE::Slate::FDeprecateVector2DResult & InImageSize) inline
Definition at line 34 of file SlateRoundedBoxBrush.h.
References FSlateRoundedBoxBrush(), and FORCENOINLINE.
FSlateRoundedBoxBrush() [3/10]
template<typename FillColorType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FillColorType & InColor, const FVector2f & InImageSize) inline
Definition at line 47 of file SlateRoundedBoxBrush.h.
References FSlateRoundedBoxBrush(), and FORCENOINLINE.
FSlateRoundedBoxBrush() [4/10]
template<typename FillColorType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType & FillColorTint, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType = ESlateBrushTileType::NoTile) inline
Definition at line 53 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
FSlateRoundedBoxBrush() [5/10]
template<typename FillColorType, typename RadiusType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FillColorType & InColor, RadiusType InRadius, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector) inline
Creates and initializes a new instance with the specified color and corner radius.
Parameters
InColor Linear Fill Color
InRadius Corner Radius in Slate Units applied to the outline at each corner. X = Top Left, Y = Top Right, Z = Bottom Right, W = Bottom Left
Definition at line 75 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
FSlateRoundedBoxBrush() [6/10]
template<typename FillColorType, typename RadiusType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType & FillColorTint, RadiusType InRadius, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType = ESlateBrushTileType::NoTile) inline
Definition at line 92 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
FSlateRoundedBoxBrush() [7/10]
template<typename FillColorType, typename OutlineColorType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FillColorType & InColor, const OutlineColorType & InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector) inline
Creates and initializes a new instance with the specified color and rounds based on height.
Parameters
InColor Linear Fill Color
InOutlineColor Outline Color
InOutlineWidth Outline Width or Thickness
Definition at line 116 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
FSlateRoundedBoxBrush() [8/10]
template<typename FillColorType, typename OutlineColorType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType & FillColorTint, const OutlineColorType & InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType = ESlateBrushTileType::NoTile) inline
Creates and initializes a new instance with the specified color and rounds based on height.
Parameters
InColor Linear Fill Color
InOutlineColor Outline Color
InOutlineWidth Outline Width or Thickness
Definition at line 139 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
FSlateRoundedBoxBrush() [9/10]
template<typename FillColorType, typename OutlineColorType, typename RadiusType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FillColorType & InColor, RadiusType InRadius, const OutlineColorType & InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector) inline
Creates and initializes a new instance with the specified color and corner radius.
Parameters
InColor Linear Fill Color
InRadius Corner Radius in Slate Units applied to the outline at each corner. X = Top Left, Y = Top Right, Z = Bottom Right, W = Bottom Left
InOutlineColor Outline Color
InOutlineWidth Outline Width or Thickness
Definition at line 165 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
FSlateRoundedBoxBrush() [10/10]
template<typename FillColorType, typename OutlineColorType, typename RadiusType> FORCENOINLINE FSlateRoundedBoxBrush::FSlateRoundedBoxBrush (const FName InFillResourceName, const FillColorType & FillColorTint, RadiusType InRadius, const OutlineColorType & InOutlineColor, float InOutlineWidth, const UE::Slate::FDeprecateVector2DParameter & InImageSize = FVector2f::ZeroVector, ESlateBrushTileType::Type InTileType = ESlateBrushTileType::NoTile) inline
Creates and initializes a new instance with the specified color and corner radius.
Parameters
InColor Linear Fill Color
InRadius Corner Radius in Slate Units applied to the outline at each corner. X = Top Left, Y = Top Right, Z = Bottom Right, W = Bottom Left
InOutlineColor Outline Color
InOutlineWidth Outline Width or Thickness
Definition at line 189 of file SlateRoundedBoxBrush.h.
References FORCENOINLINE, RoundedBox, and UE::Math::TVector2< float >::ZeroVector.
The documentation for this struct was generated from the following file:
SlateRoundedBoxBrush.h