Unreal Engine 5.6 C++ API: FPropertyBagSetRef Class Reference
FPropertyBagSetRef Class Reference
A reference to a set in FInstancedPropertyBag Contains helper methods to get and set properties.
#include "PropertyBag.h"
Public Member Functions
FORCEINLINE FPropertyBagSetRef (const FPropertyBagPropertyDesc &InDesc, const void *InSet)
EPropertyBagResult AddValueBool (const bool bInValue)
Add value to set.
EPropertyBagResult AddValueByte (const uint8 InValue)
EPropertyBagResult AddValueClass (UClass *InValue)
EPropertyBagResult AddValueDouble (const double InValue)
EPropertyBagResult AddValueEnum (const int64 InValue, const UEnum *Enum)
template<typename T>
EPropertyBagResult AddValueEnum (const T InValue)
Adds enum value specified type.
EPropertyBagResult AddValueFloat (const float InValue)
EPropertyBagResult AddValueInt32 (const int32 InValue)
EPropertyBagResult AddValueInt64 (const int64 InValue)
EPropertyBagResult AddValueName (const FName InValue)
template<typename T>
EPropertyBagResult AddValueObject (T *InValue)
Adds object pointer value specified type.
EPropertyBagResult AddValueObject (UObject *InValue)
EPropertyBagResult AddValueSoftPath (const FSoftObjectPath &InValue)
EPropertyBagResult AddValueString (const FString &InValue)
template<typename T>
EPropertyBagResult AddValueStruct (const T &InValue)
Adds struct value specified type.
EPropertyBagResult AddValueStruct (FConstStructView InValue)
EPropertyBagResult AddValueText (const FText &InValue)
EPropertyBagResult AddValueUInt32 (const uint32 InValue)
EPropertyBagResult AddValueUInt64 (const uint64 InValue)
template<typename T>
TValueOrError< bool, EPropertyBagResult > Contains (const T &Value) const
Returns a bool specifying if the element was found or not.
FORCEINLINE int32 Num () const
Returns number of elements in set.
template<typename T>
EPropertyBagResult Remove (const T &Value)
Removes value from set if found.
Private Member Functions
template<typename T>
EPropertyBagResult Add (const T &Value)
Private Member Functions inherited from FScriptSetHelper
FScriptSetHelper (const FSetProperty *InProperty, const void *InSet)
Constructor, brings together a property and an instance of the property located in memory.
FScriptSetHelper (FProperty *InElementProp, const void *InSet, const FScriptSetLayout &InLayout)
int32 AddDefaultValue_Invalid_NeedsRehash ()
Adds a blank, constructed value to a given size.
void AddElement (const void *ElementToAdd)
Adds the element to the set, returning true if the element was added, or false if the element was already present.
FORCEINLINE int32 AddUninitializedValue ()
Add an uninitialized value to the end of the set.
FIterator CreateIterator () const
FIterator CreateIterator (const int32 InLogicalIndex) const
void EmptyElements (int32 Slack=0)
Remove all values from the set, calling destructors, etc as appropriate.
int32 FindElementIndex (const void *ElementToFind, int32 IndexHint=0) const
Finds the index of an element in a set.
FORCEINLINE int32 FindElementIndexFromHash (const void *ElementToFind) const
Finds element index from hash, rather than linearly searching.
FORCEINLINE uint8 * FindElementPtr (const void *ElementToFind, int32 IndexHint=0)
Finds the pair in a map which matches the key in another pair.
FORCEINLINE uint8 * FindElementPtrFromHash (const void *ElementToFind)
Finds element pointer from hash, rather than linearly searching.
int32 FindInternalIndex (int32 LogicalIdx) const
Sets have gaps in their indices, so this function translates a logical index (ie.
int32 FindLogicalIndex (int32 InternalIdx) const
Sets have gaps in their indices, so this function translates a internal index to an logical index (ie.
uint8 * FindNthElementPtr (int32 N)
Returns a uint8 pointer to the the Nth valid element in the set (skipping invalid entries).
const uint8 * FindNthElementPtr (int32 N) const
Returns a uint8 pointer to the the Nth valid element in the set (skipping invalid entries).
FProperty * GetElementProperty () const
Returns the property representing the element of the set.
FORCEINLINE uint8 * GetElementPtr (const FIterator Iterator)
Returns a uint8 pointer to the element in the set.
FORCEINLINE const uint8 * GetElementPtr (const FIterator Iterator) const
Returns a uint8 pointer to the element in the set.
FORCEINLINE uint8 * GetElementPtr (int32 InternalIndex)
Returns a uint8 pointer to the element in the set.
FORCEINLINE const uint8 * GetElementPtr (int32 InternalIndex) const
Returns a uint8 pointer to the element in the set.
FORCEINLINE int32 GetMaxIndex () const
Returns the (non-inclusive) maximum index of elements in the set.
FORCEINLINE bool IsValidIndex (int32 InternalIndex) const
Index range check.
void MoveAssign (void *InOtherSet)
Move the allocation from another set and make it our own.
FORCEINLINE int32 Num () const
Returns the number of elements in the set.
FORCEINLINE int32 NumUnchecked () const
Returns the number of elements in the set.
void Rehash ()
Rehashes the keys in the set.
void RemoveAt (int32 InternalIndex, int32 Count=1)
Removes an element at the specified index, destroying it.
bool RemoveElement (const void *ElementToRemove)
Removes the element from the set.
Private Attributes
FPropertyBagPropertyDesc ValueDesc
Private Attributes inherited from FScriptSetHelper
FProperty * ElementProp
FScriptSet * Set
FScriptSetLayout SetLayout
Additional Inherited Members
Private Types inherited from FScriptSetHelper
using FIterator = TScriptContainerIterator<FScriptSetHelper>
Static Private Member Functions inherited from FScriptSetHelper
static FScriptSetHelper CreateHelperFormElementProperty (FProperty *InElementProperty, const void *InSet)
static FORCEINLINE int32 Num (const void *Target)
Static version of Num() used when you don't need to bother to construct a FScriptSetHelper.
Detailed Description
A reference to a set in FInstancedPropertyBag Contains helper methods to get and set properties.
FInstancedPropertyBag Bag;
Bag.AddProperties({
    { SetName, EPropertyBagContainerType::Set, EPropertyBagPropertyType::Float }
});
if (auto FloatSetRes = Bag.GetSetRef(ArrayName); FloatSetRes.IsValid())
{
    FPropertyBagSetRef& FloatSet = FloatSetRes.GetValue();
    FloatSet.AddValueFloat(123.f);
}
Note: The set reference is not valid after the layout of the referenced property bag has changed!
Definition at line 1127 of file StructUtils/PropertyBag.h.
Constructor & Destructor Documentation
FPropertyBagSetRef()
FORCEINLINE FPropertyBagSetRef::FPropertyBagSetRef (const FPropertyBagPropertyDesc & InDesc, const void * InSet) inline
Definition at line 1130 of file StructUtils/PropertyBag.h.
References FScriptSetHelper::FScriptSetHelper(), CastField(), check, FORCEINLINE, FScriptSetHelper::FSetProperty, SetProperty, and ValueDesc.
Member Function Documentation
Add()
template<typename T> EPropertyBagResult FPropertyBagSetRef::Add (const T & Value) inline private
Definition at line 1224 of file StructUtils/PropertyBag.h.
References FScriptSetHelper::AddElement(), FScriptSetHelper::FindElementIndex(), INDEX_NONE, Value, and ValueDesc.
AddValueBool()
EPropertyBagResult FPropertyBagSetRef::AddValueBool (const bool bInValue)
Add value to set.
If value is already present, it will not be added
References UE_API.
AddValueByte()
EPropertyBagResult FPropertyBagSetRef::AddValueByte (const uint8 InValue)
References UE_API.
AddValueClass()
EPropertyBagResult FPropertyBagSetRef::AddValueClass (UClass * InValue)
References UE_API.
AddValueDouble()
EPropertyBagResult FPropertyBagSetRef::AddValueDouble (const double InValue)
References UE_API.
AddValueEnum() [1/2]
EPropertyBagResult FPropertyBagSetRef::AddValueEnum (const int64 InValue, const UEnum * Enum)
References Enum, and UE_API.
Referenced by AddValueEnum().
AddValueEnum() [2/2]
template<typename T> EPropertyBagResult FPropertyBagSetRef::AddValueEnum (const T InValue) inline
Adds enum value specified type.
Definition at line 1164 of file StructUtils/PropertyBag.h.
References AddValueEnum(), StaticEnum(), and TIsEnum< T >::Value.
AddValueFloat()
EPropertyBagResult FPropertyBagSetRef::AddValueFloat (const float InValue)
References UE_API.
AddValueInt32()
EPropertyBagResult FPropertyBagSetRef::AddValueInt32 (const int32 InValue)
References UE_API.
AddValueInt64()
EPropertyBagResult FPropertyBagSetRef::AddValueInt64 (const int64 InValue)
References UE_API.
AddValueName()
EPropertyBagResult FPropertyBagSetRef::AddValueName (const FName InValue)
References UE_API.
AddValueObject() [1/2]
template<typename T> EPropertyBagResult FPropertyBagSetRef::AddValueObject (T * InValue) inline
Adds object pointer value specified type.
Definition at line 1179 of file StructUtils/PropertyBag.h.
References AddValueObject(), and TIsDerivedFrom< DerivedType, BaseType >::Value.
AddValueObject() [2/2]
EPropertyBagResult FPropertyBagSetRef::AddValueObject (UObject * InValue)
References UE_API.
Referenced by AddValueObject().
AddValueSoftPath()
EPropertyBagResult FPropertyBagSetRef::AddValueSoftPath (const FSoftObjectPath & InValue)
References UE_API.
AddValueString()
EPropertyBagResult FPropertyBagSetRef::AddValueString (const FString & InValue)
References UE_API.
AddValueStruct() [1/2]
template<typename T> EPropertyBagResult FPropertyBagSetRef::AddValueStruct (const T & InValue) inline
Adds struct value specified type.
Definition at line 1172 of file StructUtils/PropertyBag.h.
References AddValueStruct(), and FConstStructView::Make().
AddValueStruct() [2/2]
EPropertyBagResult FPropertyBagSetRef::AddValueStruct (FConstStructView InValue)
References UE_API.
Referenced by AddValueStruct().
AddValueText()
EPropertyBagResult FPropertyBagSetRef::AddValueText (const FText & InValue)
References UE_API.
AddValueUInt32()
EPropertyBagResult FPropertyBagSetRef::AddValueUInt32 (const uint32 InValue)
References UE_API.
AddValueUInt64()
EPropertyBagResult FPropertyBagSetRef::AddValueUInt64 (const uint64 InValue)
References UE_API.
Contains()
template<typename T> TValueOrError< bool, EPropertyBagResult > FPropertyBagSetRef::Contains (const T & Value) const inline
Returns a bool specifying if the element was found or not.
Definition at line 1203 of file StructUtils/PropertyBag.h.
References FScriptSetHelper::FindElementIndex(), INDEX_NONE, MakeError(), MakeValue(), Value, and ValueDesc.
Num()
FORCEINLINE int32 FPropertyBagSetRef::Num () const inline
Returns number of elements in set.
Definition at line 1214 of file StructUtils/PropertyBag.h.
References FORCEINLINE, and FScriptSetHelper::Num().
Remove()
template<typename T> EPropertyBagResult FPropertyBagSetRef::Remove (const T & Value) inline
Removes value from set if found.
Definition at line 1188 of file StructUtils/PropertyBag.h.
References FScriptSetHelper::FindElementIndex(), INDEX_NONE, FScriptSetHelper::RemoveAt(), and Value.
Field Documentation
ValueDesc
FPropertyBagPropertyDesc FPropertyBagSetRef::ValueDesc private
Definition at line 1221 of file StructUtils/PropertyBag.h.
Referenced by FPropertyBagSetRef(), Add(), and Contains().
The documentation for this class was generated from the following file:
StructUtils/PropertyBag.h