Unreal Engine 5.6 C++ API: TResizingWidgetSlotMixin< MixedIntoType > Class Template Reference
TResizingWidgetSlotMixin< MixedIntoType > Class Template Reference
Mixin to add resizing functionality to a base slot.
#include "BasicLayoutWidgetSlot.h"
Data Structures
struct FSlotArgumentsMixin
Public Member Functions
TResizingWidgetSlotMixin ()
float GetMaxSize () const
Get the max size the slot can be.
float GetMinSize () const
Get the min size the slot can be.
float GetShrinkSizeValue () const
Get the size parameter for the space rule, used when the slot size is shrinking below desired size.
FSizeParam::ESizeRule GetSizeRule () const
Get the space rule this slot should occupy along panel's direction.
float GetSizeValue () const
Get the size parameter for the space rule.
void SetMaxSize (TAttribute< float > InMaxSize)
Set the max size in SlateUnit this slot can be.
void SetMinSize (TAttribute< float > InMinSize)
Set the min size in SlateUnit this slot can be.
void SetSizeParam (FSizeParam InSizeParam)
Set the size Param of the slot, It could be a FStretch, FStretchContent, or a FAuto.
void SetSizeToAuto ()
The widget's DesiredSize will be used as the space required.
void SetSizeToStretch (TAttribute< float > InStretchCoefficient)
The available space will be distributed proportionately to each slots stretch coefficient.
void SetSizeToStretchContent (TAttribute< float > InStretchCoefficient, TAttribute< float > InShrinkStretchCoefficient=TAttribute< float >())
The widget's content size is adjusted proportionally to fit the available space.
Protected Types
template<typename InObjectType>
using TSlateSlotAttribute = ::SlateAttributePrivate::TSlateContainedAttribute<InObjectType, ::SlateAttributePrivate::FSlateAttributeNoInvalidationReason, TSlateAttributeComparePredicate<>>
Protected Member Functions
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Static Protected Member Functions
static void RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Protected Attributes
TSlateSlotAttribute< float > MaxSize
The max size that this slot can be (0 if no max)
TSlateSlotAttribute< float > MinSize
The min size that this slot can be.
TSlateSlotAttribute< float > ShrinkSizeValue
The actual value this size parameter stores, used for shrinking (negative if not defined, use SizeValue).
FSizeParam::ESizeRule SizeRule
The sizing rule to use, see ESizeRule for more info how the different rules work.
TSlateSlotAttribute< float > SizeValue
The actual value this size parameter stores.
Detailed Description
template<typename MixedIntoType>
class TResizingWidgetSlotMixin< MixedIntoType >
Mixin to add resizing functionality to a base slot.
Definition at line 397 of file BasicLayoutWidgetSlot.h.
Member Typedef Documentation
TSlateSlotAttribute
template<typename MixedIntoType> template<typename InObjectType> using TResizingWidgetSlotMixin< MixedIntoType >::TSlateSlotAttribute = ::SlateAttributePrivate::TSlateContainedAttribute<InObjectType, ::SlateAttributePrivate::FSlateAttributeNoInvalidationReason, TSlateAttributeComparePredicate<>> protected
Definition at line 578 of file BasicLayoutWidgetSlot.h.
Constructor & Destructor Documentation
TResizingWidgetSlotMixin()
template<typename MixedIntoType> TResizingWidgetSlotMixin< MixedIntoType >::TResizingWidgetSlotMixin () inline
Definition at line 400 of file BasicLayoutWidgetSlot.h.
References MaxSize, MinSize, ShrinkSizeValue, SizeRule, and SizeValue.
Member Function Documentation
ConstructMixin()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::ConstructMixin (const FChildren & SlotOwner, FSlotArgumentsMixin && InArgs) inline protected
Definition at line 439 of file BasicLayoutWidgetSlot.h.
References MoveTemp(), SetMaxSize(), SetMinSize(), and SetSizeParam().
GetMaxSize()
template<typename MixedIntoType> float TResizingWidgetSlotMixin< MixedIntoType >::GetMaxSize () const inline
Get the max size the slot can be.
Definition at line 562 of file BasicLayoutWidgetSlot.h.
References MaxSize.
GetMinSize()
template<typename MixedIntoType> float TResizingWidgetSlotMixin< MixedIntoType >::GetMinSize () const inline
Get the min size the slot can be.
Definition at line 550 of file BasicLayoutWidgetSlot.h.
References MinSize.
GetShrinkSizeValue()
template<typename MixedIntoType> float TResizingWidgetSlotMixin< MixedIntoType >::GetShrinkSizeValue () const inline
Get the size parameter for the space rule, used when the slot size is shrinking below desired size.
Used for size rule SizeRule_StretchContent.
Definition at line 489 of file BasicLayoutWidgetSlot.h.
References ShrinkSizeValue.
GetSizeRule()
template<typename MixedIntoType> FSizeParam::ESizeRule TResizingWidgetSlotMixin< MixedIntoType >::GetSizeRule () const inline
Get the space rule this slot should occupy along panel's direction.
Definition at line 471 of file BasicLayoutWidgetSlot.h.
References SizeRule.
GetSizeValue()
template<typename MixedIntoType> float TResizingWidgetSlotMixin< MixedIntoType >::GetSizeValue () const inline
Get the size parameter for the space rule.
Used for size rule SizeRule_Stretch and SizeRule_StretchContent.
Definition at line 480 of file BasicLayoutWidgetSlot.h.
References SizeValue.
RegisterAttributesMixin()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer & AttributeInitializer) inline static protected
Definition at line 457 of file BasicLayoutWidgetSlot.h.
References Layout, MaxSize, MinSize, ShrinkSizeValue, SizeValue, and SLATE_ADD_SLOT_ATTRIBUTE_DEFINITION_WITH_NAME.
SetMaxSize()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::SetMaxSize (TAttribute< float > InMaxSize) inline
Set the max size in SlateUnit this slot can be.
Definition at line 568 of file BasicLayoutWidgetSlot.h.
References MaxSize, and MoveTemp().
Referenced by ConstructMixin().
SetMinSize()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::SetMinSize (TAttribute< float > InMinSize) inline
Set the min size in SlateUnit this slot can be.
Definition at line 556 of file BasicLayoutWidgetSlot.h.
References MinSize, and MoveTemp().
Referenced by ConstructMixin().
SetSizeParam()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::SetSizeParam (FSizeParam InSizeParam) inline
Set the size Param of the slot, It could be a FStretch, FStretchContent, or a FAuto.
Definition at line 495 of file BasicLayoutWidgetSlot.h.
References TAttribute< ObjectType >::IsSet(), MoveTemp(), ShrinkSizeValue, FSizeParam::ShrinkValue, FSizeParam::SizeRule, SizeRule, FSizeParam::SizeRule_StretchContent, SizeValue, and FSizeParam::Value.
Referenced by ConstructMixin(), SetSizeToAuto(), SetSizeToStretch(), and SetSizeToStretchContent().
SetSizeToAuto()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::SetSizeToAuto () inline
The widget's DesiredSize will be used as the space required.
Definition at line 523 of file BasicLayoutWidgetSlot.h.
References SetSizeParam().
SetSizeToStretch()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::SetSizeToStretch (TAttribute< float > InStretchCoefficient) inline
The available space will be distributed proportionately to each slots stretch coefficient.
A slot with coefficient of 2 will get assigned twice as much available space as slot with coefficient 1.
Parameters
InStretchCoefficient Stretch coefficient for this slot.
Definition at line 533 of file BasicLayoutWidgetSlot.h.
References MoveTemp(), and SetSizeParam().
SetSizeToStretchContent()
template<typename MixedIntoType> void TResizingWidgetSlotMixin< MixedIntoType >::SetSizeToStretchContent (TAttribute< float > InStretchCoefficient, TAttribute< float > InShrinkStretchCoefficient = TAttribute<float>()) inline
The widget's content size is adjusted proportionally to fit the available space.
The slots size starts at DesiredSize, and a slot with coefficient of 2 will get adjusted twice as much as slot with coefficient 1 to fit the available space.
Parameters
InStretchCoefficient Stretch coefficient for this slot.
InShrinkStretchCoefficient If specified, this stretch coefficient is used when the slots is shrinking below desired size. Otherwise InStretchCoefficient is used for both shrink and grow.
Definition at line 544 of file BasicLayoutWidgetSlot.h.
References MoveTemp(), and SetSizeParam().
Field Documentation
MaxSize
template<typename MixedIntoType> TSlateSlotAttribute<float> TResizingWidgetSlotMixin< MixedIntoType >::MaxSize protected
The max size that this slot can be (0 if no max)
Definition at line 590 of file BasicLayoutWidgetSlot.h.
Referenced by TResizingWidgetSlotMixin(), GetMaxSize(), RegisterAttributesMixin(), and SetMaxSize().
MinSize
template<typename MixedIntoType> TSlateSlotAttribute<float> TResizingWidgetSlotMixin< MixedIntoType >::MinSize protected
The min size that this slot can be.
Definition at line 587 of file BasicLayoutWidgetSlot.h.
Referenced by TResizingWidgetSlotMixin(), GetMinSize(), RegisterAttributesMixin(), and SetMinSize().
ShrinkSizeValue
template<typename MixedIntoType> TSlateSlotAttribute<float> TResizingWidgetSlotMixin< MixedIntoType >::ShrinkSizeValue protected
The actual value this size parameter stores, used for shrinking (negative if not defined, use SizeValue).
Definition at line 584 of file BasicLayoutWidgetSlot.h.
Referenced by TResizingWidgetSlotMixin(), GetShrinkSizeValue(), RegisterAttributesMixin(), and SetSizeParam().
SizeRule
template<typename MixedIntoType> FSizeParam::ESizeRule TResizingWidgetSlotMixin< MixedIntoType >::SizeRule protected
The sizing rule to use, see ESizeRule for more info how the different rules work.
Definition at line 575 of file BasicLayoutWidgetSlot.h.
Referenced by TResizingWidgetSlotMixin(), GetSizeRule(), and SetSizeParam().
SizeValue
template<typename MixedIntoType> TSlateSlotAttribute<float> TResizingWidgetSlotMixin< MixedIntoType >::SizeValue protected
The actual value this size parameter stores.
Definition at line 581 of file BasicLayoutWidgetSlot.h.
Referenced by TResizingWidgetSlotMixin(), GetSizeValue(), RegisterAttributesMixin(), and SetSizeParam().
The documentation for this class was generated from the following file:
BasicLayoutWidgetSlot.h