Unreal Engine 5.6 C++ API: TScriptArray< AllocatorType > Class Template Reference
TScriptArray< AllocatorType > Class Template Reference
Base dynamic array.
#include "ScriptArray.h"
Public Types
using IntrusiveUnsetOptionalStateType = TScriptArray
Public Member Functions
TScriptArray ()
TScriptArray (const TScriptArray &)
TScriptArray (FIntrusiveUnsetOptionalState Tag)
int32 Add (int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
int32 AddZeroed (int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCEINLINE void CheckAddress (const void *Addr, int32 NumBytesPerElement) const
void CountBytes (FArchive &Ar, int32 NumBytesPerElement) const
void Empty (int32 Slack, int32 NumBytesPerElement, uint32 AlignmentOfElement)
SIZE_T GetAllocatedSize (int32 NumBytesPerElement) const
FORCEINLINE void * GetData ()
FORCEINLINE const void * GetData () const
FORCEINLINE int32 GetSlack () const
Returns the amount of slack in this array in elements.
void Insert (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
void InsertZeroed (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
bool IsEmpty () const
FORCEINLINE bool IsValidIndex (int32 i) const
void MoveAssign (TScriptArray &Other, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCEINLINE int32 Num () const
FORCEINLINE int32 NumUnchecked () const
void operator= (const TScriptArray &)
bool operator== (FIntrusiveUnsetOptionalState Tag) const
void Remove (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void Reset (int32 NewSize, int32 NumBytesPerElement, uint32 AlignmentOfElement)
void SetNumUninitialized (int32 NewNum, int32 NumBytesPerElement, uint32 AlignmentOfElement, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void Shrink (int32 NumBytesPerElement, uint32 AlignmentOfElement)
void SwapMemory (int32 A, int32 B, int32 NumBytesPerElement)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Remove") FORCEINLINE void Remove(int32 Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized") FORCEINLINE void SetNumUninitialized(int32 NewNum
Data Fields
int32 uint32 AlignmentOfElement
int32 int32 uint32 AlignmentOfElement
int32 uint32 bool bAllowShrinking
int32 int32 uint32 bool bAllowShrinking
int32 Count
int32 NumBytesPerElement
int32 int32 NumBytesPerElement
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Protected Member Functions
TScriptArray (int32 InNum, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeGrow (int32 OldNum, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeInit (int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeShrink (int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeTo (int32 NewMax, int32 NumBytesPerElement, uint32 AlignmentOfElement)
Protected Attributes
int32 ArrayMax
int32 ArrayNum
Private Member Functions
FORCEINLINE void SlackTrackerNumChanged ()
Detailed Description
template<typename AllocatorType>
class TScriptArray< AllocatorType >
Base dynamic array.
An untyped data array; mirrors a TArray's members, but doesn't need an exact C++ type for its elements.
Definition at line 19 of file ScriptArray.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
template<typename AllocatorType> using TScriptArray< AllocatorType >::IntrusiveUnsetOptionalStateType = TScriptArray
Definition at line 298 of file ScriptArray.h.
Constructor & Destructor Documentation
TScriptArray() [1/4]
template<typename AllocatorType> TScriptArray< AllocatorType >::TScriptArray () inline
Definition at line 170 of file ScriptArray.h.
TScriptArray() [2/4]
template<typename AllocatorType> TScriptArray< AllocatorType >::TScriptArray (int32 InNum, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline nodiscard protected
Definition at line 235 of file ScriptArray.h.
TScriptArray() [3/4]
template<typename AllocatorType> TScriptArray< AllocatorType >::TScriptArray (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 300 of file ScriptArray.h.
TScriptArray() [4/4]
template<typename AllocatorType> TScriptArray< AllocatorType >::TScriptArray (const TScriptArray< AllocatorType > &) inline
Definition at line 316 of file ScriptArray.h.
Member Function Documentation
Add()
template<typename AllocatorType> int32 TScriptArray< AllocatorType >::Add (int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 77 of file ScriptArray.h.
AddZeroed()
template<typename AllocatorType> int32 TScriptArray< AllocatorType >::AddZeroed (int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 93 of file ScriptArray.h.
CheckAddress()
template<typename AllocatorType> FORCEINLINE void TScriptArray< AllocatorType >::CheckAddress (const void * Addr, int32 NumBytesPerElement) const inline
Definition at line 179 of file ScriptArray.h.
CountBytes()
template<typename AllocatorType> void TScriptArray< AllocatorType >::CountBytes (FArchive & Ar, int32 NumBytesPerElement) const inline
Definition at line 175 of file ScriptArray.h.
Empty()
template<typename AllocatorType> void TScriptArray< AllocatorType >::Empty (int32 Slack, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 137 of file ScriptArray.h.
GetAllocatedSize()
template<typename AllocatorType> SIZE_T TScriptArray< AllocatorType >::GetAllocatedSize (int32 NumBytesPerElement) const inline nodiscard
Definition at line 228 of file ScriptArray.h.
GetData() [1/2]
template<typename AllocatorType> FORCEINLINE void * TScriptArray< AllocatorType >::GetData () inline nodiscard
Definition at line 24 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::CheckAddress(), and UE::GC::Private::ToView().
GetData() [2/2]
template<typename AllocatorType> FORCEINLINE const void * TScriptArray< AllocatorType >::GetData () const inline nodiscard
Definition at line 28 of file ScriptArray.h.
GetSlack()
template<typename AllocatorType> FORCEINLINE int32 TScriptArray< AllocatorType >::GetSlack () const inline nodiscard
Returns the amount of slack in this array in elements.
Definition at line 186 of file ScriptArray.h.
Insert()
template<typename AllocatorType> void TScriptArray< AllocatorType >::Insert (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 55 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::InsertZeroed().
InsertZeroed()
template<typename AllocatorType> void TScriptArray< AllocatorType >::InsertZeroed (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 50 of file ScriptArray.h.
IsEmpty()
template<typename AllocatorType> bool TScriptArray< AllocatorType >::IsEmpty () const inline nodiscard
Definition at line 36 of file ScriptArray.h.
IsValidIndex()
template<typename AllocatorType> FORCEINLINE bool TScriptArray< AllocatorType >::IsValidIndex (int32 i) const inline nodiscard
Definition at line 32 of file ScriptArray.h.
MoveAssign()
template<typename AllocatorType> void TScriptArray< AllocatorType >::MoveAssign (TScriptArray< AllocatorType > & Other, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 126 of file ScriptArray.h.
Num()
template<typename AllocatorType> FORCEINLINE int32 TScriptArray< AllocatorType >::Num () const inline nodiscard
Definition at line 40 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::SetNumUninitialized(), and UE::GC::Private::ToView().
NumUnchecked()
template<typename AllocatorType> FORCEINLINE int32 TScriptArray< AllocatorType >::NumUnchecked () const inline nodiscard
Definition at line 46 of file ScriptArray.h.
operator=()
template<typename AllocatorType> void TScriptArray< AllocatorType >::operator= (const TScriptArray< AllocatorType > &) inline
Definition at line 317 of file ScriptArray.h.
operator==()
template<typename AllocatorType> bool TScriptArray< AllocatorType >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 306 of file ScriptArray.h.
Remove()
template<typename AllocatorType> void TScriptArray< AllocatorType >::Remove (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 191 of file ScriptArray.h.
Reset()
template<typename AllocatorType> void TScriptArray< AllocatorType >::Reset (int32 NewSize, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 149 of file ScriptArray.h.
ResizeGrow()
template<typename AllocatorType> FORCENOINLINE void TScriptArray< AllocatorType >::ResizeGrow (int32 OldNum, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline protected
Definition at line 255 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::Add(), and TScriptArray< FHeapAllocator >::Insert().
ResizeInit()
template<typename AllocatorType> FORCENOINLINE void TScriptArray< AllocatorType >::ResizeInit (int32 NumBytesPerElement, uint32 AlignmentOfElement) inline protected
Definition at line 250 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::TScriptArray().
ResizeShrink()
template<typename AllocatorType> FORCENOINLINE void TScriptArray< AllocatorType >::ResizeShrink (int32 NumBytesPerElement, uint32 AlignmentOfElement) inline protected
Definition at line 260 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::Remove().
ResizeTo()
template<typename AllocatorType> FORCENOINLINE void TScriptArray< AllocatorType >::ResizeTo (int32 NewMax, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline protected
Definition at line 269 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::Empty(), and TScriptArray< FHeapAllocator >::Shrink().
SetNumUninitialized()
template<typename AllocatorType> void TScriptArray< AllocatorType >::SetNumUninitialized (int32 NewNum, int32 NumBytesPerElement, uint32 AlignmentOfElement, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 108 of file ScriptArray.h.
Shrink()
template<typename AllocatorType> void TScriptArray< AllocatorType >::Shrink (int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 99 of file ScriptArray.h.
SlackTrackerNumChanged()
template<typename AllocatorType> FORCEINLINE void TScriptArray< AllocatorType >::SlackTrackerNumChanged () inline private
Definition at line 283 of file ScriptArray.h.
Referenced by TScriptArray< FHeapAllocator >::TScriptArray(), TScriptArray< FHeapAllocator >::Add(), TScriptArray< FHeapAllocator >::Empty(), TScriptArray< FHeapAllocator >::Insert(), TScriptArray< FHeapAllocator >::MoveAssign(), TScriptArray< FHeapAllocator >::Remove(), and TScriptArray< FHeapAllocator >::Reset().
SwapMemory()
template<typename AllocatorType> void TScriptArray< AllocatorType >::SwapMemory (int32 A, int32 B, int32 NumBytesPerElement) inline
Definition at line 162 of file ScriptArray.h.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [1/2]
template<typename AllocatorType> TScriptArray< AllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Remove")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [2/2]
template<typename AllocatorType> TScriptArray< AllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized")
Field Documentation
AlignmentOfElement [1/2]
template<typename AllocatorType> int32 uint32 TScriptArray< AllocatorType >::AlignmentOfElement
Definition at line 122 of file ScriptArray.h.
AlignmentOfElement [2/2]
template<typename AllocatorType> int32 int32 uint32 TScriptArray< AllocatorType >::AlignmentOfElement
Definition at line 224 of file ScriptArray.h.
ArrayMax
template<typename AllocatorType> int32 TScriptArray< AllocatorType >::ArrayMax protected
Definition at line 248 of file ScriptArray.h.
ArrayNum
template<typename AllocatorType> int32 TScriptArray< AllocatorType >::ArrayNum protected
Definition at line 247 of file ScriptArray.h.
bAllowShrinking [1/2]
template<typename AllocatorType> int32 uint32 bool TScriptArray< AllocatorType >::bAllowShrinking
Initial value:
{
        SetNumUninitialized(NewNum, NumBytesPerElement, AlignmentOfElement, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 122 of file ScriptArray.h.
bAllowShrinking [2/2]
template<typename AllocatorType> int32 int32 uint32 bool TScriptArray< AllocatorType >::bAllowShrinking
Initial value:
{
        Remove(Index, Count, NumBytesPerElement, AlignmentOfElement, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 224 of file ScriptArray.h.
bHasIntrusiveUnsetOptionalState
template<typename AllocatorType> bool TScriptArray< AllocatorType >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 297 of file ScriptArray.h.
Count
template<typename AllocatorType> int32 TScriptArray< AllocatorType >::Count
Definition at line 224 of file ScriptArray.h.
NumBytesPerElement [1/2]
template<typename AllocatorType> int32 TScriptArray< AllocatorType >::NumBytesPerElement
Definition at line 122 of file ScriptArray.h.
NumBytesPerElement [2/2]
template<typename AllocatorType> int32 int32 TScriptArray< AllocatorType >::NumBytesPerElement
Definition at line 224 of file ScriptArray.h.
The documentation for this class was generated from the following file:
ScriptArray.h