Unreal Engine 5.6 C++ API: FSlateAttributeDescriptor::FContainerInitializer Struct Reference
FSlateAttributeDescriptor::FContainerInitializer Struct Reference
Internal class to initialize the SlateAttributeDescriptor::FContainer attributes (Add attributes or modify existing attributes).
#include "SlateAttributeDescriptor.h"
Data Structures
struct FAttributeEntry
Public Member Functions
FContainerInitializer ()=delete
FContainerInitializer (const FContainerInitializer &)=delete
FAttributeEntry AddContainedAttribute (FName AttributeName, OffsetType Offset, const FInvalidateWidgetReasonAttribute &ReasonGetter)
FAttributeEntry AddContainedAttribute (FName AttributeName, OffsetType Offset, FInvalidateWidgetReasonAttribute &&ReasonGetter)
FContainerInitializer & operator= (const FContainerInitializer &)=delete
void OverrideInvalidationReason (FName AttributeName, const FInvalidateWidgetReasonAttribute &Reason)
Change the InvalidationReason of an attribute defined in a base class.
void OverrideInvalidationReason (FName AttributeName, FInvalidateWidgetReasonAttribute &&Reason)
Change the InvalidationReason of an attribute defined in a base class.
void OverrideOnValueChanged (FName AttributeName, ECallbackOverrideType OverrideType, FAttributeValueChangedDelegate Callback)
Change the FAttributeValueChangedDelegate of an attribute defined in a base class.
Private Member Functions
FContainerInitializer (FSlateAttributeDescriptor &InDescriptor, const FSlateAttributeDescriptor &ParentDescriptor, FName ContainerName)
FContainerInitializer (FSlateAttributeDescriptor &InDescriptor, FName ContainerName)
Private Attributes
FName ContainerName
FSlateAttributeDescriptor & Descriptor
friend FSlateAttributeDescriptor
Detailed Description
Internal class to initialize the SlateAttributeDescriptor::FContainer attributes (Add attributes or modify existing attributes).
Definition at line 204 of file SlateAttributeDescriptor.h.
Constructor & Destructor Documentation
FContainerInitializer() [1/4]
FSlateAttributeDescriptor::FContainerInitializer::FContainerInitializer (FSlateAttributeDescriptor & InDescriptor, FName ContainerName) private
References ContainerName, and FSlateAttributeDescriptor.
Referenced by FContainerInitializer(), and operator=().
FContainerInitializer() [2/4]
FSlateAttributeDescriptor::FContainerInitializer::FContainerInitializer (FSlateAttributeDescriptor & InDescriptor, const FSlateAttributeDescriptor & ParentDescriptor, FName ContainerName) private
References ContainerName, and FSlateAttributeDescriptor.
FContainerInitializer() [3/4]
FSlateAttributeDescriptor::FContainerInitializer::FContainerInitializer () delete
FContainerInitializer() [4/4]
FSlateAttributeDescriptor::FContainerInitializer::FContainerInitializer (const FContainerInitializer &) delete
References FContainerInitializer().
Member Function Documentation
AddContainedAttribute() [1/2]
FAttributeEntry FSlateAttributeDescriptor::FContainerInitializer::AddContainedAttribute (FName AttributeName, OffsetType Offset, const FInvalidateWidgetReasonAttribute & ReasonGetter)
AddContainedAttribute() [2/2]
FAttributeEntry FSlateAttributeDescriptor::FContainerInitializer::AddContainedAttribute (FName AttributeName, OffsetType Offset, FInvalidateWidgetReasonAttribute && ReasonGetter)
operator=()
FContainerInitializer & FSlateAttributeDescriptor::FContainerInitializer::operator= (const FContainerInitializer &) delete
References FContainerInitializer().
OverrideInvalidationReason() [1/2]
void FSlateAttributeDescriptor::FContainerInitializer::OverrideInvalidationReason (FName AttributeName, const FInvalidateWidgetReasonAttribute & Reason)
Change the InvalidationReason of an attribute defined in a base class.
OverrideInvalidationReason() [2/2]
void FSlateAttributeDescriptor::FContainerInitializer::OverrideInvalidationReason (FName AttributeName, FInvalidateWidgetReasonAttribute && Reason)
Change the InvalidationReason of an attribute defined in a base class.
OverrideOnValueChanged()
void FSlateAttributeDescriptor::FContainerInitializer::OverrideOnValueChanged (FName AttributeName, ECallbackOverrideType OverrideType, FAttributeValueChangedDelegate Callback)
Change the FAttributeValueChangedDelegate of an attribute defined in a base class.
Field Documentation
ContainerName
FName FSlateAttributeDescriptor::FContainerInitializer::ContainerName private
Definition at line 256 of file SlateAttributeDescriptor.h.
Referenced by FContainerInitializer(), and FContainerInitializer().
Descriptor
FSlateAttributeDescriptor& FSlateAttributeDescriptor::FContainerInitializer::Descriptor private
Definition at line 255 of file SlateAttributeDescriptor.h.
FSlateAttributeDescriptor
friend FSlateAttributeDescriptor::FContainerInitializer::FSlateAttributeDescriptor private
Definition at line 207 of file SlateAttributeDescriptor.h.
Referenced by FSlateAttributeDescriptor::FContainerInitializer::FAttributeEntry::FAttributeEntry(), FContainerInitializer(), and FContainerInitializer().
The documentation for this struct was generated from the following file:
SlateAttributeDescriptor.h