Unreal Engine 5.6 C++ API: UE::RemoteObject::Transfer Namespace Reference
UE::RemoteObject::Transfer Namespace Reference
Data Structures
struct FMigrateSendParams
Information for performing a migration (send) an object to a remote server.
Functions
void GetAllBorrowedObjects (TArray< FRemoteObjectId > &OutBorrowedObjectIds)
Returns the list of all object IDs currently borrowed from another server.
void InitRemoteObjectTransfer ()
void MigrateObjectFromRemoteServer (FRemoteObjectId ObjectId, FRemoteServerId CurrentOwnerServerId, UObject *DestinationOuter=nullptr)
Migrates an object from a remote server (temp function)
void MigrateObjectToRemoteServer (FRemoteObjectId ObjectId, FRemoteServerId DestinationServerId)
Migrates an object to a remote server without changing ownership.
void MigrateObjectToRemoteServerWithExplicitPriority (FRemoteWorkPriority RequestPriority, FRemoteObjectId Id, FRemoteServerId DestinationServerId)
void OnObjectDataDenied (FRemoteObjectId ObjectId, FRemoteServerId RemoteServerId)
Called when a remote object request was denied by a remote server.
void OnObjectDataReceived (FRemoteServerId OwnerServerId, FRemoteServerId PhysicsId, FRemoteObjectId ObjectId, FRemoteServerId RemoteServerId, FRemoteObjectData &Data)
Called when remote object data has been received from a remote server.
void PrefetchRemoteObject (FRemoteObjectId ObjectId, UObject *DestinationOuter)
(Advanced API) Adds the remote object to the current transaction's requested object list, causing the object to be migrated to this server.
void RegisterRemoteObjectId (FRemoteObjectId Id, FRemoteServerId ResidentServerId)
Registers object ID as known to be owned by another server, without migrating it.
void RegisterSharedObject (UObject *Object)
Registers object for sharing, marking it as owned by the current server.
void TouchResidentObject (UObject *Object)
Reports code that touches a resident object.
void TransferObjectOwnershipToRemoteServer (UObject *Object, FRemoteServerId DestinationServerId)
Migrates and transfers ownership of an object to a remote server.
UE_DEPRECATED (5.6, "RemoteObjectIdToObjectPtr is deprecated use FObjectPtr(FRemoteObjectId) instead.") FORCEINLINE FObjectPtr RemoteObjectIdToObjectPtr(FRemoteObjectId RemoteId)
Utility that converts FRemoteObjectId to TObjectPtr of a given type.
Variables
const FRemoteServerId DatabaseId
TMulticastDelegate< void(const FRemoteObjectData &, const FUObjectMigrationContext &)> OnObjectDataReceivedDelegate
Delegate executed when objects have been migrated from another server.
TMulticastDelegate< void(const FRemoteObjectData &, const FUObjectMigrationContext &)> OnObjectDataSentDelegate
Delegate executed when object data has been migrated to another server.
TMulticastDelegate< void(const TArray< UObject * > &, const FUObjectMigrationContext &)> OnObjectsReceivedDelegate
Delegate executed when objects have been migrated from another server.
TMulticastDelegate< void(const TSet< UObject * > &, const FUObjectMigrationContext &)> OnObjectsSentDelegate
Delegate executed when objects have been migrated to another server.
TMulticastDelegate< void(FRemoteTransactionId, FRemoteObjectId)> OnObjectTouchedDelegate
Delegate executed when an object has been accessed by a transaction.
TDelegate< void(FRemoteObjectId, FRemoteServerId)> RemoteObjectDeniedTransferDelegate
Delegate that handles an object request being denied.
TDelegate< void(const FMigrateSendParams &)> RemoteObjectTransferDelegate
Delegate that transfers object data to another server.
TDelegate< void(FRemoteWorkPriority, FRemoteObjectId, FRemoteServerId, FRemoteServerId)> RequestRemoteObjectDelegate
Delegate that requests remote object data from LastKnownResidentServerId to be transferred to DestinationServerId.
TDelegate< void(const FUObjectMigrationContext &)> RestoreRemoteObjectDataDelegate
Delegate that restores object data from a database.
TDelegate< void(const FMigrateSendParams &)> StoreRemoteObjectDataDelegate
Delegate that stores locally unrachable object data into a database.
Function Documentation
GetAllBorrowedObjects()
void UE::RemoteObject::Transfer::GetAllBorrowedObjects (TArray< FRemoteObjectId > & OutBorrowedObjectIds)
Returns the list of all object IDs currently borrowed from another server.
InitRemoteObjectTransfer()
void UE::RemoteObject::Transfer::InitRemoteObjectTransfer ()
References OnObjectDataReceivedDelegate, OnObjectDataSentDelegate, OnObjectsReceivedDelegate, OnObjectsSentDelegate, OnObjectTouchedDelegate, RemoteObjectDeniedTransferDelegate, RemoteObjectTransferDelegate, RequestRemoteObjectDelegate, RestoreRemoteObjectDataDelegate, and StoreRemoteObjectDataDelegate.
MigrateObjectFromRemoteServer()
void UE::RemoteObject::Transfer::MigrateObjectFromRemoteServer (FRemoteObjectId ObjectId, FRemoteServerId CurrentOwnerServerId, UObject * DestinationOuter = nullptr)
Migrates an object from a remote server (temp function)
Parameters
ObjectId Remote object id
CurrentOwnerServerId Id of a remote server that currently owns the object
DestinationOuter Optional outer the migrated object should be reparented to
Returns
Migrated object
References ObjectId.
MigrateObjectToRemoteServer()
void UE::RemoteObject::Transfer::MigrateObjectToRemoteServer (FRemoteObjectId ObjectId, FRemoteServerId DestinationServerId)
Migrates an object to a remote server without changing ownership.
Parameters
ObjectId Remote object id
DestinationServerId Id of a remote server to receive the object
References ObjectId.
MigrateObjectToRemoteServerWithExplicitPriority()
void UE::RemoteObject::Transfer::MigrateObjectToRemoteServerWithExplicitPriority (FRemoteWorkPriority RequestPriority, FRemoteObjectId Id, FRemoteServerId DestinationServerId)
OnObjectDataDenied()
void UE::RemoteObject::Transfer::OnObjectDataDenied (FRemoteObjectId ObjectId, FRemoteServerId RemoteServerId)
Called when a remote object request was denied by a remote server.
Parameters
ObjectId Remote object id
RemoteServerId Server that owns the object data
References ObjectId.
OnObjectDataReceived()
void UE::RemoteObject::Transfer::OnObjectDataReceived (FRemoteServerId OwnerServerId, FRemoteServerId PhysicsId, FRemoteObjectId ObjectId, FRemoteServerId RemoteServerId, FRemoteObjectData & Data)
Called when remote object data has been received from a remote server.
Parameters
ObjectId Remote object id
RemoteServerId Server that sent object data
Data Remote object data. Data ownership is transferred to the remote object queue
References ObjectId.
PrefetchRemoteObject()
void UE::RemoteObject::Transfer::PrefetchRemoteObject (FRemoteObjectId ObjectId, UObject * DestinationOuter)
(Advanced API) Adds the remote object to the current transaction's requested object list, causing the object to be migrated to this server.
Does not abort the transaction if the object isn't yet local
References ObjectId.
RegisterRemoteObjectId()
void UE::RemoteObject::Transfer::RegisterRemoteObjectId (FRemoteObjectId Id, FRemoteServerId ResidentServerId)
Registers object ID as known to be owned by another server, without migrating it.
Parameters
ObjectId Remote object id
OwnerServerId Id of a remote server that currently owns the object
RegisterSharedObject()
void UE::RemoteObject::Transfer::RegisterSharedObject (UObject * Object)
Registers object for sharing, marking it as owned by the current server.
Parameters
Object to make shareable
References DatabaseId.
TouchResidentObject()
void UE::RemoteObject::Transfer::TouchResidentObject (UObject * Object)
Reports code that touches a resident object.
TransferObjectOwnershipToRemoteServer()
void UE::RemoteObject::Transfer::TransferObjectOwnershipToRemoteServer (UObject * Object, FRemoteServerId DestinationServerId)
Migrates and transfers ownership of an object to a remote server.
Parameters
Object Local object to migrate
DestinationServerId Id of a remote server to receive the object and assume ownership
UE_DEPRECATED()
UE::RemoteObject::Transfer::UE_DEPRECATED (5. 6, "RemoteObjectIdToObjectPtr is deprecated use FObjectPtr(FRemoteObjectId) instead.")
Utility that converts FRemoteObjectId to TObjectPtr of a given type.
Will not resolve the object if it's not local.
Definition at line 111 of file RemoteObjectTransfer.h.
References FORCEINLINE.
Variable Documentation
DatabaseId
const FRemoteServerId UE::RemoteObject::Transfer::DatabaseId extern
Referenced by RegisterSharedObject().
OnObjectDataReceivedDelegate
TMulticastDelegate<void(const FRemoteObjectData& , const FUObjectMigrationContext&)> UE::RemoteObject::Transfer::OnObjectDataReceivedDelegate extern
Delegate executed when objects have been migrated from another server.
Referenced by InitRemoteObjectTransfer().
OnObjectDataSentDelegate
TMulticastDelegate<void(const FRemoteObjectData& , const FUObjectMigrationContext&)> UE::RemoteObject::Transfer::OnObjectDataSentDelegate extern
Delegate executed when object data has been migrated to another server.
Referenced by InitRemoteObjectTransfer().
OnObjectsReceivedDelegate
TMulticastDelegate<void(const TArray<UObject*>& , const FUObjectMigrationContext&)> UE::RemoteObject::Transfer::OnObjectsReceivedDelegate extern
Delegate executed when objects have been migrated from another server.
Referenced by InitRemoteObjectTransfer().
OnObjectsSentDelegate
TMulticastDelegate<void(const TSet<UObject*>& , const FUObjectMigrationContext&)> UE::RemoteObject::Transfer::OnObjectsSentDelegate extern
Delegate executed when objects have been migrated to another server.
Migrated objects can still be resolved with weak pointers but at this point any changes to their internal state won't be migrated across to the remote server
Referenced by InitRemoteObjectTransfer().
OnObjectTouchedDelegate
TMulticastDelegate<void(FRemoteTransactionId , FRemoteObjectId)> UE::RemoteObject::Transfer::OnObjectTouchedDelegate extern
Delegate executed when an object has been accessed by a transaction.
Referenced by InitRemoteObjectTransfer().
RemoteObjectDeniedTransferDelegate
TDelegate<void(FRemoteObjectId , FRemoteServerId)> UE::RemoteObject::Transfer::RemoteObjectDeniedTransferDelegate extern
Delegate that handles an object request being denied.
Referenced by InitRemoteObjectTransfer().
RemoteObjectTransferDelegate
TDelegate<void(const FMigrateSendParams&)> UE::RemoteObject::Transfer::RemoteObjectTransferDelegate extern
Delegate that transfers object data to another server.
Referenced by InitRemoteObjectTransfer().
RequestRemoteObjectDelegate
TDelegate<void(FRemoteWorkPriority , FRemoteObjectId , FRemoteServerId , FRemoteServerId)> UE::RemoteObject::Transfer::RequestRemoteObjectDelegate extern
Delegate that requests remote object data from LastKnownResidentServerId to be transferred to DestinationServerId.
Allows requests to be forwarded if ObjectId does not reside on LastKnownResidentServerId.
Referenced by InitRemoteObjectTransfer().
RestoreRemoteObjectDataDelegate
TDelegate<void(const FUObjectMigrationContext&)> UE::RemoteObject::Transfer::RestoreRemoteObjectDataDelegate extern
Delegate that restores object data from a database.
Referenced by InitRemoteObjectTransfer().
StoreRemoteObjectDataDelegate
TDelegate<void(const FMigrateSendParams&)> UE::RemoteObject::Transfer::StoreRemoteObjectDataDelegate extern
Delegate that stores locally unrachable object data into a database.
Referenced by InitRemoteObjectTransfer().