Unreal Engine 5.6 C++ API: FInputDeviceLightColorProperty Struct Reference
FInputDeviceLightColorProperty Struct Reference
A generic light color property for input devices that have lights on them.
#include "IInputInterface.h"
Public Member Functions
FInputDeviceLightColorProperty ()
FInputDeviceLightColorProperty (bool bInEnable, FColor InColor)
Static Public Member Functions
static FName PropertyName ()
Data Fields
bool bEnable = true
If the light should be enabled or not.
FColor Color = FColor::White
The color to set the light.
Detailed Description
A generic light color property for input devices that have lights on them.
Definition at line 147 of file IInputInterface.h.
Constructor & Destructor Documentation
FInputDeviceLightColorProperty() [1/2]
FInputDeviceLightColorProperty::FInputDeviceLightColorProperty () inline
Definition at line 149 of file IInputInterface.h.
References PropertyName().
FInputDeviceLightColorProperty() [2/2]
FInputDeviceLightColorProperty::FInputDeviceLightColorProperty (bool bInEnable, FColor InColor) inline
Definition at line 153 of file IInputInterface.h.
References bEnable, Color, and PropertyName().
Member Function Documentation
PropertyName()
FName FInputDeviceLightColorProperty::PropertyName () inline static
Definition at line 159 of file IInputInterface.h.
References FName.
Referenced by FInputDeviceLightColorProperty(), and FInputDeviceLightColorProperty().
Field Documentation
bEnable
bool FInputDeviceLightColorProperty::bEnable = true
If the light should be enabled or not.
Definition at line 162 of file IInputInterface.h.
Referenced by FInputDeviceLightColorProperty().
Color
FColor FInputDeviceLightColorProperty::Color = FColor::White
The color to set the light.
Definition at line 165 of file IInputInterface.h.
Referenced by FInputDeviceLightColorProperty().
The documentation for this struct was generated from the following file:
IInputInterface.h