Unreal Engine 5.6 C++ API: UE::StateTree::DescHelpers Namespace Reference
UE::StateTree::DescHelpers Namespace Reference
Functions
STATETREEMODULE_API FText GetBoolText (bool bValue, EStateTreeNodeFormatting Formatting)
template<typename TInstanceDataType>
FText GetDescriptionForMathOperation (FText OperationText, const FGuid &ID, FStateTreeDataView InstanceDataView, const IStateTreeBindingLookup &BindingLookup, EStateTreeNodeFormatting Formatting)
template<typename TInstanceDataType>
FText GetDescriptionForSingleParameterFunc (FText OperationText, const FGuid &ID, FStateTreeDataView InstanceDataView, const IStateTreeBindingLookup &BindingLookup, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetExactMatchText (bool bExactMatch, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetGameplayTagContainerAsText (const FGameplayTagContainer &TagContainer, const int ApproxMaxLength=60)
STATETREEMODULE_API FText GetGameplayTagQueryAsText (const FGameplayTagQuery &TagQuery, const int ApproxMaxLength=120)
STATETREEMODULE_API FText GetIntervalText (const FFloatInterval &Interval, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetIntervalText (const FText &MinValueText, const FText &MaxValueText, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetIntervalText (float Min, float Max, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetInvertText (bool bInvert, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetMathOperationText (const FText &OperationText, const FText &LeftText, const FText &RightText, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetOperatorText (const EGenericAICheck Operator, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetSingleParamFunctionText (const FText &FunctionText, const FText &ParamText, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetText (const FVector &Value, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetText (const UObject *Value, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetText (float Value, EStateTreeNodeFormatting Formatting)
STATETREEMODULE_API FText GetText (int32 Value, EStateTreeNodeFormatting Formatting)
Function Documentation
GetBoolText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetBoolText (bool bValue, EStateTreeNodeFormatting Formatting) extern
Returns
description of a boolean value.
GetDescriptionForMathOperation()
template<typename TInstanceDataType> FText UE::StateTree::DescHelpers::GetDescriptionForMathOperation (FText OperationText, const FGuid & ID, FStateTreeDataView InstanceDataView, const IStateTreeBindingLookup & BindingLookup, EStateTreeNodeFormatting Formatting)
Returns
description in the form of (Left OperationText Right). Expect TInstanceDataType to have a member Left and Right whose types have an overloaded UE::StateTree::DescHelpers::GetText function.
Definition at line 69 of file StateTreeNodeDescriptionHelpers.h.
References GET_MEMBER_NAME_CHECKED, IStateTreeBindingLookup::GetBindingSourceDisplayName(), GetMathOperationText(), GetText(), ID, FText::IsEmpty(), Left, and Right.
GetDescriptionForSingleParameterFunc()
template<typename TInstanceDataType> FText UE::StateTree::DescHelpers::GetDescriptionForSingleParameterFunc (FText OperationText, const FGuid & ID, FStateTreeDataView InstanceDataView, const IStateTreeBindingLookup & BindingLookup, EStateTreeNodeFormatting Formatting)
Returns
description in the form of OperationText(Input). Expect TInstanceDataType to have a member input whose type has an overloaded UE::StateTree::DescHelpers::GetText function.
Definition at line 92 of file StateTreeNodeDescriptionHelpers.h.
References GET_MEMBER_NAME_CHECKED, IStateTreeBindingLookup::GetBindingSourceDisplayName(), GetSingleParamFunctionText(), GetText(), ID, and Input.
GetExactMatchText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetExactMatchText (bool bExactMatch, EStateTreeNodeFormatting Formatting) extern
Returns
description for exact match, used for Gameplay Tag matching functions (returns "Exactly" plus space).
GetGameplayTagContainerAsText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetGameplayTagContainerAsText (const FGameplayTagContainer & TagContainer, const int ApproxMaxLength = 60) extern
Returns
description for a Gameplay Tag Container. If the length of container description is longer than ApproxMaxLength, the it truncated and ... as added to the end.
GetGameplayTagQueryAsText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetGameplayTagQueryAsText (const FGameplayTagQuery & TagQuery, const int ApproxMaxLength = 120) extern
Returns
description for a Gameplay Tag Query. If the query description is longer than ApproxMaxLength, the it truncated and ... as added to the end.
GetIntervalText() [1/3]
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetIntervalText (const FFloatInterval & Interval, EStateTreeNodeFormatting Formatting) extern
Returns
description of a float interval.
GetIntervalText() [2/3]
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetIntervalText (const FText & MinValueText, const FText & MaxValueText, EStateTreeNodeFormatting Formatting) extern
Returns
description of a float interval.
GetIntervalText() [3/3]
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetIntervalText (float Min, float Max, EStateTreeNodeFormatting Formatting) extern
Returns
description of a float interval.
References UE::Max, and UE::Min.
GetInvertText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetInvertText (bool bInvert, EStateTreeNodeFormatting Formatting) extern
Returns
description for condition inversion (returns "Not" plus a space).
GetMathOperationText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetMathOperationText (const FText & OperationText, const FText & LeftText, const FText & RightText, EStateTreeNodeFormatting Formatting) extern
Referenced by GetDescriptionForMathOperation().
GetOperatorText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetOperatorText (const EGenericAICheck Operator, EStateTreeNodeFormatting Formatting) extern
Returns
description for a EGenericAICheck.
GetSingleParamFunctionText()
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetSingleParamFunctionText (const FText & FunctionText, const FText & ParamText, EStateTreeNodeFormatting Formatting) extern
Referenced by GetDescriptionForSingleParameterFunc().
GetText() [1/4]
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetText (const FVector & Value, EStateTreeNodeFormatting Formatting) extern
Returns
description of a vector value.
References FVector, and Value.
Referenced by GetDescriptionForMathOperation(), and GetDescriptionForSingleParameterFunc().
GetText() [2/4]
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetText (const UObject * Value, EStateTreeNodeFormatting Formatting) extern
Returns
description of a UObject value.
References Value.
GetText() [3/4]
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetText (float Value, EStateTreeNodeFormatting Formatting) extern
Returns
description of a float value.
References Value.
GetText() [4/4]
STATETREEMODULE_API FText UE::StateTree::DescHelpers::GetText (int32 Value, EStateTreeNodeFormatting Formatting) extern
Returns
description of an int value.
References Value.