Unreal Engine 5.6 C++ API: Metasound::FSharedStateRandomGetManager Class Reference
Metasound::FSharedStateRandomGetManager Class Reference
#include "MetasoundArrayRandomNode.h"
Public Member Functions
METASOUNDFRONTEND_API void InitOrUpdate (InitSharedStateArgs &InStateArgs)
METASOUNDFRONTEND_API void InitSharedState (InitSharedStateArgs &InArgs)
METASOUNDFRONTEND_API int32 NextValue (const FGuid &InSharedStateId)
METASOUNDFRONTEND_API int32 NextValue (const FGuid &InSharedStateId, InitSharedStateArgs &InStateArgs)
METASOUNDFRONTEND_API void ResetSeed (const FGuid &InSharedStateId)
METASOUNDFRONTEND_API void ResetSeed (const FGuid &InSharedStateId, InitSharedStateArgs &InStateArgs)
METASOUNDFRONTEND_API void SetNoRepeatOrder (const FGuid &InSharedStateId, int32 InNoRepeatOrder)
METASOUNDFRONTEND_API void SetRandomWeights (const FGuid &InSharedStateId, const TArray< float > &InRandomWeights)
METASOUNDFRONTEND_API void SetSeed (const FGuid &InSharedStateId, int32 InSeed)
Static Public Member Functions
static METASOUNDFRONTEND_API FSharedStateRandomGetManager & Get ()
Private Member Functions
FSharedStateRandomGetManager ()=default
~FSharedStateRandomGetManager ()=default
Private Attributes
FCriticalSection CritSect
TMap< FGuid, TUniquePtr< FArrayRandomGet > > RandomGets
Detailed Description
Definition at line 134 of file MetasoundArrayRandomNode.h.
Constructor & Destructor Documentation
FSharedStateRandomGetManager()
Metasound::FSharedStateRandomGetManager::FSharedStateRandomGetManager () private default
Referenced by Get().
~FSharedStateRandomGetManager()
Metasound::FSharedStateRandomGetManager::~FSharedStateRandomGetManager () private default
Member Function Documentation
Get()
METASOUNDFRONTEND_API FSharedStateRandomGetManager & Metasound::FSharedStateRandomGetManager::Get () static
References FSharedStateRandomGetManager(), and UE_API.
Referenced by Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerNext(), and Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerReset().
InitOrUpdate()
METASOUNDFRONTEND_API void Metasound::FSharedStateRandomGetManager::InitOrUpdate (InitSharedStateArgs & InStateArgs)
References UE_API.
InitSharedState()
METASOUNDFRONTEND_API void Metasound::FSharedStateRandomGetManager::InitSharedState (InitSharedStateArgs & InArgs)
References UE_API.
NextValue() [1/2]
METASOUNDFRONTEND_API int32 Metasound::FSharedStateRandomGetManager::NextValue (const FGuid & InSharedStateId)
References UE_API.
NextValue() [2/2]
METASOUNDFRONTEND_API int32 Metasound::FSharedStateRandomGetManager::NextValue (const FGuid & InSharedStateId, InitSharedStateArgs & InStateArgs)
References UE_API.
Referenced by Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerNext().
ResetSeed() [1/2]
METASOUNDFRONTEND_API void Metasound::FSharedStateRandomGetManager::ResetSeed (const FGuid & InSharedStateId)
References UE_API.
ResetSeed() [2/2]
METASOUNDFRONTEND_API void Metasound::FSharedStateRandomGetManager::ResetSeed (const FGuid & InSharedStateId, InitSharedStateArgs & InStateArgs)
References UE_API.
Referenced by Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerReset().
SetNoRepeatOrder()
METASOUNDFRONTEND_API void Metasound::FSharedStateRandomGetManager::SetNoRepeatOrder (const FGuid & InSharedStateId, int32 InNoRepeatOrder)
References UE_API.
SetRandomWeights()
METASOUNDFRONTEND_API void Metasound::FSharedStateRandomGetManager::SetRandomWeights (const FGuid & InSharedStateId, const TArray< float > & InRandomWeights)
References UE_API.
SetSeed()
METASOUNDFRONTEND_API void Metasound::FSharedStateRandomGetManager::SetSeed (const FGuid & InSharedStateId, int32 InSeed)
References UE_API.
Field Documentation
CritSect
FCriticalSection Metasound::FSharedStateRandomGetManager::CritSect private
Definition at line 161 of file MetasoundArrayRandomNode.h.
RandomGets
TMap<FGuid, TUniquePtr<FArrayRandomGet> > Metasound::FSharedStateRandomGetManager::RandomGets private
Definition at line 163 of file MetasoundArrayRandomNode.h.
The documentation for this class was generated from the following file:
MetasoundArrayRandomNode.h