Unreal Engine 5.6 C++ API: UE::Anim::TScopedGraphMessage< TGraphMessageType > Struct Template Reference
UE::Anim::TScopedGraphMessage< TGraphMessageType > Struct Template Reference
#include "AnimNodeMessages.h"
Public Member Functions
template<typename... TArgs>
TScopedGraphMessage (const FAnimationBaseContext &InContext, TArgs &&... Args)
~TScopedGraphMessage ()
Additional Inherited Members
Protected Member Functions inherited from UE::Anim::FScopedGraphMessage
FScopedGraphMessage (const FAnimationBaseContext &InContext)
void PopMessage ()
void PushMessage (const FAnimationBaseContext &InContext, TSharedRef< IGraphMessage > InMessage, FName InMessageType)
Protected Attributes inherited from UE::Anim::FScopedGraphMessage
FName MessageType
FAnimationUpdateSharedContext * SharedContext
Detailed Description
template<typename TGraphMessageType>
struct UE::Anim::TScopedGraphMessage< TGraphMessageType >
Definition at line 161 of file AnimNodeMessages.h.
Constructor & Destructor Documentation
TScopedGraphMessage()
template<typename TGraphMessageType> template<typename... TArgs> UE::Anim::TScopedGraphMessage< TGraphMessageType >::TScopedGraphMessage (const FAnimationBaseContext & InContext, TArgs &&... Args) inline
Definition at line 164 of file AnimNodeMessages.h.
References UE::Anim::FScopedGraphMessage::FScopedGraphMessage(), Forward(), TIsDerivedFrom< DerivedType, BaseType >::IsDerived, MakeShared(), and UE::Anim::FScopedGraphMessage::PushMessage().
~TScopedGraphMessage()
template<typename TGraphMessageType> UE::Anim::TScopedGraphMessage< TGraphMessageType >::~TScopedGraphMessage () inline
Definition at line 174 of file AnimNodeMessages.h.
References UE::Anim::FScopedGraphMessage::PopMessage().
The documentation for this struct was generated from the following file:
AnimNodeMessages.h