Unreal Engine 5.6 C++ API: FBulkDataBatchRequest::FScatterGatherBuilder Class Reference
FBulkDataBatchRequest::FScatterGatherBuilder Class Reference
Reads one or more bulk data and copies the result into a single I/O buffer.
#include "BulkData.h"
Data Structures
struct FRequest
Public Member Functions
FScatterGatherBuilder (int32 MaxCount)
void Issue (FIoBuffer &Dst, EAsyncIOPriorityAndFlags Priority, FCompletionCallback &&Callback, FBulkDataBatchRequest &OutRequest)
Issue the batch.
FScatterGatherBuilder & Read (const FBulkData &BulkData, uint64 Offset=0, uint64 Size=MAX_uint64)
Read the bulk data from the specified offset and size.
Public Member Functions inherited from FBulkDataBatchRequest::FBuilder
FBuilder (const FBuilder &)=delete
~FBuilder ()
FBuilder & operator= (const FBuilder &)=delete
Private Attributes
TArray< FRequest, TInlineAllocator< 8 > > Requests
Additional Inherited Members
Protected Member Functions inherited from FBulkDataBatchRequest::FBuilder
FBuilder (int32 MaxCount)
FBulkDataBatchRequest::FBatchHandle & GetBatch ()
void IssueBatch (FBulkDataBatchRequest *OutRequest, FCompletionCallback &&Callback)
Protected Attributes inherited from FBulkDataBatchRequest::FBuilder
int32 BatchCount = 0
int32 NumLoaded = 0
Detailed Description
Reads one or more bulk data and copies the result into a single I/O buffer.
Definition at line 1401 of file BulkData.h.
Constructor & Destructor Documentation
FScatterGatherBuilder()
FBulkDataBatchRequest::FScatterGatherBuilder::FScatterGatherBuilder (int32 MaxCount)
Referenced by Read().
Member Function Documentation
Issue()
void FBulkDataBatchRequest::FScatterGatherBuilder::Issue (FIoBuffer & Dst, EAsyncIOPriorityAndFlags Priority, FCompletionCallback && Callback, FBulkDataBatchRequest & OutRequest)
Issue the batch.
Parameters
Dst An empty or preallocated I/O buffer.
Priority The I/O priority.
Callback A callback triggered when the operation is completed.
OutRequest A handle to the batch request.
Note
Assumes one or more handle(s) has been passed into any of the read operations.
References FBulkDataRequest::FBulkDataBatchRequest.
Referenced by FSkeletalMeshStreamIn_IO::SetIORequest().
Read()
FScatterGatherBuilder & FBulkDataBatchRequest::FScatterGatherBuilder::Read (const FBulkData & BulkData, uint64 Offset = 0, uint64 Size = MAX_uint64)
Read the bulk data from the specified offset and size.
References FScatterGatherBuilder(), BulkData, MAX_uint64, and TSequenceHistory< HistorySize >::Size.
Referenced by FSkeletalMeshStreamIn_IO::SetIORequest().
Field Documentation
Requests
TArray<FRequest, TInlineAllocator<8> > FBulkDataBatchRequest::FScatterGatherBuilder::Requests private
Definition at line 1426 of file BulkData.h.
The documentation for this class was generated from the following file:
BulkData.h