Unreal Engine 5.6 C++ API: FAssetEditorViewportLayout Class Reference
FAssetEditorViewportLayout Class Reference
Base class for viewport layout configurations Handles maximizing and restoring well as visibility of specific viewports.
#include "AssetEditorViewportLayout.h"
Public Member Functions
UNREALED_API FAssetEditorViewportLayout ()
Constructor.
virtual UNREALED_API ~FAssetEditorViewportLayout ()
Destructor.
virtual UNREALED_API TSharedRef< SWidget > BuildViewportLayout (TSharedPtr< SDockTab > InParentDockTab, TSharedPtr< FEditorViewportTabContent > InParentTab, const FString &LayoutString)
Builds a viewport layout and returns the widget containing the layout.
virtual UNREALED_API void FactoryPaneConfigurationFromTypeName (const FName &InLayoutConfigTypeName) override
virtual UNREALED_API TSharedRef< SWidget > FactoryViewport (FName InTypeName, const FAssetEditorViewportConstructionArgs &ConstructionArgs)
Create an instance of a custom viewport from the specified viewport type name.
virtual UNREALED_API const FName GetActivePaneConfigurationTypeName () const override
TWeakPtr< FEditorViewportTabContent > GetParentTabContent () const
Returns the parent tab content object.
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
virtual bool IsTickable () const override
Virtual that can be overloaded by the inheriting class.
virtual UNREALED_API void LoadConfig (const FString &LayoutString)
virtual UNREALED_API void SaveConfig (const FString &LayoutString) const
virtual void Tick (float DeltaTime) override
FTickableEditorObject interface.
UE_DEPRECATED (5.0, "This functionality has moved to the layout configurations. Use BuildViewportLayout.") UNREALED_API virtual TSharedRef< SWidget > MakeViewportLayout(const FString &LayoutString) final
Sets up the layout based on the specific layout configuration implementation.
Public Member Functions inherited from TSharedFromThis< FAssetEditorViewportLayout >
TSharedRef< FAssetEditorViewportLayout, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAssetEditorViewportLayout, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Protected Member Functions
virtual UNREALED_API EVisibility OnGetNonMaximizedVisibility () const
Delegate called to get the visibility of the non-maximized viewports The non-maximized viewports are not visible if there is a maximized viewport on top of them.
Protected Member Functions inherited from TSharedFromThis< FAssetEditorViewportLayout >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TSharedPtr< FAssetEditorViewportPaneLayout > LayoutConfiguration
TWeakPtr< SDockTab > ParentTab
The parent tab where this layout resides.
TWeakPtr< FEditorViewportTabContent > ParentTabContent
The parent tab content object where this layout resides.
TWeakPtr< SAssetEditorViewportsOverlay > ViewportsOverlayPtr
The overlay widget that handles what viewports should be on top (non-maximized or maximized)
Additional Inherited Members
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Static Protected Member Functions inherited from TSharedFromThis< FAssetEditorViewportLayout >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Base class for viewport layout configurations Handles maximizing and restoring well as visibility of specific viewports.
Definition at line 153 of file AssetEditorViewportLayout.h.
Constructor & Destructor Documentation
FAssetEditorViewportLayout()
UNREALED_API FAssetEditorViewportLayout::FAssetEditorViewportLayout ()
Constructor.
~FAssetEditorViewportLayout()
virtual UNREALED_API FAssetEditorViewportLayout::~FAssetEditorViewportLayout () virtual
Destructor.
Member Function Documentation
BuildViewportLayout()
virtual UNREALED_API TSharedRef< SWidget > FAssetEditorViewportLayout::BuildViewportLayout (TSharedPtr< SDockTab > InParentDockTab, TSharedPtr< FEditorViewportTabContent > InParentTab, const FString & LayoutString) virtual
Builds a viewport layout and returns the widget containing the layout.
Parameters
InParentDockTab The parent dock tab widget of this viewport configuration
InParentTab The parent tab object
LayoutString The layout string loaded from file to custom build the layout with
FactoryPaneConfigurationFromTypeName()
virtual UNREALED_API void FAssetEditorViewportLayout::FactoryPaneConfigurationFromTypeName (const FName & InLayoutConfigTypeName) override virtual
FactoryViewport()
virtual UNREALED_API TSharedRef< SWidget > FAssetEditorViewportLayout::FactoryViewport (FName InTypeName, const FAssetEditorViewportConstructionArgs & ConstructionArgs) virtual
Create an instance of a custom viewport from the specified viewport type name.
GetActivePaneConfigurationTypeName()
virtual UNREALED_API const FName FAssetEditorViewportLayout::GetActivePaneConfigurationTypeName () const override virtual
GetParentTabContent()
TWeakPtr< FEditorViewportTabContent > FAssetEditorViewportLayout::GetParentTabContent () const inline
Returns the parent tab content object.
Definition at line 187 of file AssetEditorViewportLayout.h.
References ParentTabContent.
GetStatId()
virtual TStatId FAssetEditorViewportLayout::GetStatId () const inline override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
Definition at line 172 of file AssetEditorViewportLayout.h.
IsTickable()
virtual bool FAssetEditorViewportLayout::IsTickable () const inline override virtual
Virtual that can be overloaded by the inheriting class.
It is used to determine whether an object should be conditionally ticked.
Returns
true if object is ready to be ticked, false otherwise.
Reimplemented from FTickableObjectBase.
Definition at line 171 of file AssetEditorViewportLayout.h.
LoadConfig()
virtual UNREALED_API void FAssetEditorViewportLayout::LoadConfig (const FString & LayoutString) virtual
References LoadConfig().
Referenced by LoadConfig().
OnGetNonMaximizedVisibility()
virtual UNREALED_API EVisibility FAssetEditorViewportLayout::OnGetNonMaximizedVisibility () const protected virtual
Delegate called to get the visibility of the non-maximized viewports The non-maximized viewports are not visible if there is a maximized viewport on top of them.
Parameters
EVisibility::Visible when visible, EVisibility::Collapsed otherwise
References OnGetNonMaximizedVisibility().
Referenced by OnGetNonMaximizedVisibility().
SaveConfig()
virtual UNREALED_API void FAssetEditorViewportLayout::SaveConfig (const FString & LayoutString) const virtual
References SaveConfig().
Referenced by SaveConfig().
Tick()
virtual void FAssetEditorViewportLayout::Tick (float DeltaTime) inline override virtual
FTickableEditorObject interface.
Implements FTickableObjectBase.
Definition at line 170 of file AssetEditorViewportLayout.h.
References DeltaTime.
UE_DEPRECATED()
FAssetEditorViewportLayout::UE_DEPRECATED (5. 0, "This functionality has moved to the layout configurations. Use BuildViewportLayout.") const & final
Sets up the layout based on the specific layout configuration implementation.
Parameters
LayoutString The layout string loaded from a file.
Returns
The base widget representing the layout. This is commonly a splitter.
Field Documentation
LayoutConfiguration
TSharedPtr<FAssetEditorViewportPaneLayout> FAssetEditorViewportLayout::LayoutConfiguration protected
Definition at line 219 of file AssetEditorViewportLayout.h.
ParentTab
TWeakPtr< SDockTab > FAssetEditorViewportLayout::ParentTab protected
The parent tab where this layout resides.
Definition at line 217 of file AssetEditorViewportLayout.h.
ParentTabContent
TWeakPtr< FEditorViewportTabContent > FAssetEditorViewportLayout::ParentTabContent protected
The parent tab content object where this layout resides.
Definition at line 214 of file AssetEditorViewportLayout.h.
Referenced by GetParentTabContent().
ViewportsOverlayPtr
TWeakPtr< SAssetEditorViewportsOverlay > FAssetEditorViewportLayout::ViewportsOverlayPtr protected
The overlay widget that handles what viewports should be on top (non-maximized or maximized)
Definition at line 211 of file AssetEditorViewportLayout.h.
The documentation for this class was generated from the following file:
AssetEditorViewportLayout.h