Unreal Engine 5.6 C++ API: FGenericPlatformProcess Struct Reference
FGenericPlatformProcess Struct Reference
Generic implementation for most platforms, these tend to be unused and unimplemented.
#include "GenericPlatformProcess.h"
Data Structures
struct ApplicationSettingsContext
struct FSemaphore
Generic representation of a interprocess semaphore.
Public Types
enum class EWaitAndForkResult : uint8 { Error , Parent , Child }
Public Member Functions
UE_DEPRECATED (5.0, "Please use GetSynchEventFromPool to create a new event, and ReturnSynchEventToPool to release the event.") static 1 class FEvent *CreateSynchEvent(bool bIsManualReset
Creates a new event.
Static Public Member Functions
static FORCEINLINE void AddDllDirectory (const TCHAR *Directory)
Adds a directory to search in when resolving implicitly loaded or filename-only DLLs.
static const TCHAR * ApplicationSettingsDir ()
Get application settings directory.
static const TCHAR * BaseDir ()
Get startup directory.
static bool CanLaunchURL (const TCHAR *URL)
Checks if the platform can launch a uniform resource locator (i.e.
static void CleanShaderWorkingDir ()
Clean the shader working directory.
static void ClosePipe (void *ReadPipe, void *WritePipe)
Closes an anonymous pipe.
static void CloseProc (FProcHandle &ProcessHandle)
Cleans up FProcHandle after we're done with it.
static const TCHAR * ComputerName ()
Get computer name.
static void ConditionalSleep (TFunctionRef< bool()> Condition, float SleepTime=0.0f)
Sleep thread until condition is satisfied.
static bool CreatePipe (void *&ReadPipe, void *&WritePipe, bool bWritePipeLocal=false)
Creates a writable anonymous pipe.
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild, void *PipeStdErrChild)
Creates a new process and its primary thread, with separate std pipes.
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild=nullptr)
Creates a new process and its primary thread.
static class FRunnableThread * CreateRunnableThread ()
Creates the platform-specific runnable thread.
static bool Daemonize ()
Makes process run as a system service (daemon), i.e.
static bool DeleteInterprocessSynchObject (FSemaphore *Object)
Deletes an interprocess synchronization object.
static void DumpThreadInfo (const TCHAR *MarkerName)
Output information about the currently active thread.
static bool ExecElevatedProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode)
Executes a process as administrator, requesting elevation as necessary.
static bool ExecProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode, FString *OutStdOut, FString *OutStdErr, const TCHAR *OptionalWorkingDirectory=NULL, bool bShouldEndWithParentProcess=false)
Executes a process, returning the return code, stdout, and stderr.
static const TCHAR * ExecutableName (bool bRemoveExtension=true)
Return the name of the currently running executable.
static const TCHAR * ExecutablePath ()
Return the path to the currently running executable.
static void ExploreFolder (const TCHAR *FilePath)
Attempt to "explore" the folder specified by the provided file path.
static void FlushPoolSyncEvents ()
Deletes all the recycled sync events contained by the pools.
static void FreeDllHandle (void *DllHandle)
Free a DLL.
static FString GenerateApplicationPath (const FString &AppName, EBuildConfiguration BuildConfiguration)
Generates the path to the specified application or game.
static bool GetApplicationMemoryUsage (uint32 ProcessId, SIZE_T *OutMemoryUsage)
Outputs the virtual memory usage, of the process with the specified PID.
static FString GetApplicationName (uint32 ProcessId)
Returns the Name of process given by the PID.
static FString GetApplicationSettingsDir (const ApplicationSettingsContext &Settings)
Get application settings directory for a given context.
static const TCHAR * GetArchitectureSuffix ()
Get the architecture suffix, if any.
static const TCHAR * GetBinariesSubdirectory ()
Used only by platforms with DLLs, this gives the subdirectory from binaries to find the executables.
static uint32 GetCurrentCoreNumber ()
Retrieves the current hardware CPU core.
static uint32 GetCurrentProcessId ()
Retrieves the ProcessId of this process.
static FString GetCurrentWorkingDirectory ()
Get the current working directory (only really makes sense on desktop platforms)
static ENamedThreads::Type GetDesiredThreadForUObjectReferenceCollector ()
specifies the thread to use for UObject reference collection
static FORCEINLINE void GetDllDirectories (TArray< FString > &OutDllDirectories)
Get the list of registered directories to search in when resolving implicitly loaded or filename-only DLLs.
static void * GetDllExport (void *DllHandle, const TCHAR *ProcName)
Lookup the address of a DLL function.
static void * GetDllHandle (const TCHAR *Filename)
Load a DLL.
static FString GetGameBundleId ()
Retrieves the platform-specific bundle identifier or package name of the game.
static const TCHAR * GetModuleExtension ()
Return the extension of dynamic library.
static const TCHAR * GetModulePrefix ()
Return the prefix of dynamic library (e.g.
static const FString GetModulesDirectory ()
Used only by platforms with DLLs, this gives the full path to the main directory containing modules.
static bool GetPerFrameProcessorUsage (uint32 ProcessId, float &ProcessUsageFraction, float &IdleUsageFraction)
Retrieves the current CPU Utilization for the current process in terms of percentage of all capacity.
static bool GetProcReturnCode (FProcHandle &ProcHandle, int32 *ReturnCode)
Retrieves the termination status of the specified process.
static uint32 GetStackSize ()
Get the active stack size for the currently running thread.
static class FEvent * GetSynchEventFromPool (bool bIsManualReset=false)
Gets an event from the pool or creates a new one if necessary.
static bool IsApplicationRunning (const TCHAR *ProcName)
Returns true if the specified application is running.
static bool IsApplicationRunning (uint32 ProcessId)
Returns true if the specified application is running.
static bool IsFirstInstance ()
Checks if we're the first instance.
static bool IsProcRunning (FProcHandle &ProcessHandle)
Returns true if the specified process is running.
static bool LaunchFileInDefaultExternalApplication (const TCHAR *FileName, const TCHAR *Parms=NULL, ELaunchVerb::Type Verb=ELaunchVerb::Open, bool bPromptToOpenOnFailure=true)
Attempt to launch the provided file name in its default external application.
static void LaunchURL (const TCHAR *URL, const TCHAR *Parms, FString *Error)
Launch a uniform resource locator (i.e.
static bool LaunchURLFiltered (const TCHAR *URL, const TCHAR *Parms, FString *Error, const UE::Core::FURLRequestFilter &Filter)
Launch a uniform resource locator (i.e.
static void ModifyThreadAssignmentForUObjectReferenceCollector (int32 &NumThreads, int32 &NumBackgroundThreads, ENamedThreads::Type &NormalThreadName, ENamedThreads::Type &BackgroundThreadName)
allows a platform to override the threading configuration for reference collection
static bool ModuleExists (const FString &Filename)
Used only by platforms with DLLs, this confirms the existence of a given module.
static FSemaphore * NewInterprocessSynchObject (const FString &Name, bool bCreate, uint32 MaxLocks=1)
Creates or opens an interprocess synchronization object.
static FSemaphore * NewInterprocessSynchObject (const TCHAR *Name, bool bCreate, uint32 MaxLocks=1)
Creates or opens an interprocess synchronization object.
static FProcHandle OpenProcess (uint32 ProcessID)
Opens an existing process.
static FORCEINLINE void PopDllDirectory (const TCHAR *Directory)
Unsets a directory to look for DLL files.
static FORCEINLINE void PushDllDirectory (const TCHAR *Directory)
Set a directory to look for DLL files.
static FString ReadPipe (void *ReadPipe)
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
static bool ReadPipeToArray (void *ReadPipe, TArray< uint8 > &Output)
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
static void ReturnSynchEventToPool (FEvent *Event)
Returns an event to the pool.
static void SetCurrentWorkingDirectoryToBaseDir ()
static bool SetProcessLimits (EProcessResource::Type Resource, uint64 Limit)
Sets the process limits.
static void SetShaderDir (const TCHAR *Where)
static void SetThreadAffinityMask (uint64 AffinityMask)
Change the thread processor affinity.
static void SetThreadName (const TCHAR *ThreadName)
Helper function to set thread name of the current thread.
static void SetThreadPriority (EThreadPriority NewPriority)
Change the thread processor priority.
static void SetupAudioThread ()
Allow the platform to do anything it needs for audio thread.
static void SetupGameThread ()
Allow the platform to do anything it needs for game thread.
static void SetupRenderThread ()
Allow the platform to do anything it needs for render thread.
static const TCHAR * ShaderDir ()
static const FString ShaderWorkingDir ()
Get the shader working directory.
static bool ShouldSaveToUserDir ()
Content saved to the game or engine directories should be rerouted to user directories instead.
static bool SkipWaitForStats ()
force skip calling FThreadStats::WaitForStats()
static bool SupportsMultithreading ()
Gets whether this platform can use multiple threads.
static void TearDown ()
Tears down allocated process resources.
static void TeardownAudioThread ()
Allow the platform to tear down the audio thread.
static void TerminateProc (FProcHandle &ProcessHandle, bool KillTree=false)
Terminates a process.
static void TerminateProcTreeWithPredicate (FProcHandle &ProcessHandle, TFunctionRef< bool(uint32 ProcessId, const TCHAR *ApplicationName)> Predicate)
Terminates a process tree.
static bool TryGetMemoryUsage (FProcHandle &ProcessHandle, FPlatformProcessMemoryStats &OutStats)
Queries the memory usage of the process.
static const TCHAR * UserDir ()
Get user directory.
static const TCHAR * UserHomeDir ()
Get the user home directory.
static const TCHAR * UserName (bool bOnlyAlphaNumeric=true)
Get user name.
static const TCHAR * UserSettingsDir ()
Get the user settings directory.
static const TCHAR * UserTempDir ()
Get the user temporary directory.
static EWaitAndForkResult WaitAndFork ()
Waits for process signals and forks child processes.
static void WaitForProc (FProcHandle &ProcessHandle)
Waits for a process to stop.
static bool WritePipe (void *WritePipe, const FString &Message, FString *OutWritten=nullptr)
Sends the message to process through pipe.
static bool WritePipe (void *WritePipe, const uint8 *Data, const int32 DataLength, int32 *OutDataLength=nullptr)
Sends data to process through pipe.
static FORCEINLINE void Yield ()
Tells the processor to pause for implementation-specific amount of time.
static FORCEINLINE void YieldCycles (uint64 Cycles)
Tells the processor to pause for at least the amount of cycles given.
Detailed Description
Generic implementation for most platforms, these tend to be unused and unimplemented.
Definition at line 175 of file GenericPlatformProcess.h.
Member Enumeration Documentation
EWaitAndForkResult
enum class FGenericPlatformProcess::EWaitAndForkResult : uint8 strong
Enumerator
Error
Parent
Child
Definition at line 585 of file GenericPlatformProcess.h.
Member Function Documentation
AddDllDirectory()
FORCEINLINE void FGenericPlatformProcess::AddDllDirectory (const TCHAR * Directory) inline static
Adds a directory to search in when resolving implicitly loaded or filename-only DLLs.
Definition at line 240 of file GenericPlatformProcess.h.
References FORCEINLINE.
ApplicationSettingsDir()
const TCHAR * FGenericPlatformProcess::ApplicationSettingsDir () static
Get application settings directory.
NOTE: Only one return value is valid at a time!
BaseDir()
const TCHAR * FGenericPlatformProcess::BaseDir () static
Get startup directory.
NOTE: Only one return value is valid at a time!
CanLaunchURL()
bool FGenericPlatformProcess::CanLaunchURL (const TCHAR * URL) static
Checks if the platform can launch a uniform resource locator (i.e.
http://www.epicgames.com/unreal).
CleanShaderWorkingDir()
void FGenericPlatformProcess::CleanShaderWorkingDir () static
Clean the shader working directory.
ClosePipe()
void FGenericPlatformProcess::ClosePipe (void * ReadPipe, void * WritePipe) static
Closes an anonymous pipe.
Parameters
ReadPipe The handle to the read end of the pipe.
WritePipe The handle to the write end of the pipe.
See also
CreatePipe, ReadPipe
References ClosePipe(), ReadPipe(), and WritePipe().
Referenced by ClosePipe().
CloseProc()
void FGenericPlatformProcess::CloseProc (FProcHandle & ProcessHandle) static
Cleans up FProcHandle after we're done with it.
Parameters
ProcessHandle handle returned from FPlatformProcess::CreateProc.
ComputerName()
const TCHAR * FGenericPlatformProcess::ComputerName () static
Get computer name.
NOTE: Only one return value is valid at a time!
ConditionalSleep()
void FGenericPlatformProcess::ConditionalSleep (TFunctionRef< bool()> Condition, float SleepTime = 0.0f) static
Sleep thread until condition is satisfied.
Parameters
Condition Condition to evaluate.
SleepTime Time to sleep
CreatePipe()
bool FGenericPlatformProcess::CreatePipe (void *& ReadPipe, void *& WritePipe, bool bWritePipeLocal = false) static
Creates a writable anonymous pipe.
Anonymous pipes can be used to capture and/or redirect STDOUT and STDERROR of a process. The pipe created by this method can be passed into CreateProc as Write
Parameters
ReadPipe Will hold the handle to the read end of the pipe.
WritePipe Will hold the handle to the write end of the pipe. @parm bWritePipeLocal indicates that the write pipe end will be used locally, instead of the read pipe
Returns
true on success, false otherwise.
See also
ClosePipe, ReadPipe
References CreatePipe(), ReadPipe(), and WritePipe().
Referenced by CreatePipe().
CreateProc() [1/2]
FProcHandle FGenericPlatformProcess::CreateProc (const TCHAR * URL, const TCHAR * Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 * OutProcessID, int32 PriorityModifier, const TCHAR * OptionalWorkingDirectory, void * PipeWriteChild, void * PipeReadChild, void * PipeStdErrChild) static
Creates a new process and its primary thread, with separate std pipes.
The new process runs the specified executable file in the security context of the calling process.
Parameters
URL executable name
Parms command line arguments
bLaunchDetached if true, the new process will have its own window
bLaunchHidden if true, the new process will be minimized in the task bar
bLaunchReallyHidden if true, the new process will not have a window or be in the task bar
OutProcessId if non-NULL, this will be filled in with the ProcessId
PriorityModifier -2 idle, -1 low, 0 normal, 1 high, 2 higher
OptionalWorkingDirectory Directory to start in when running the program, or NULL to use the current working directory
PipeWriteChild Optional HANDLE to pipe for redirecting stdout
PipeReadChild Optional HANDLE to pipe for redirecting stdin
PipeStdErrChild Optional HANDLE to pipe for redirecting stderr
Returns
The process handle for use in other process functions
CreateProc() [2/2]
FProcHandle FGenericPlatformProcess::CreateProc (const TCHAR * URL, const TCHAR * Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 * OutProcessID, int32 PriorityModifier, const TCHAR * OptionalWorkingDirectory, void * PipeWriteChild, void * PipeReadChild = nullptr) static
Creates a new process and its primary thread.
The new process runs the specified executable file in the security context of the calling process.
Parameters
URL executable name
Parms command line arguments
bLaunchDetached if true, the new process will have its own window
bLaunchHidden if true, the new process will be minimized in the task bar
bLaunchReallyHidden if true, the new process will not have a window or be in the task bar
OutProcessId if non-NULL, this will be filled in with the ProcessId
PriorityModifier -2 idle, -1 low, 0 normal, 1 high, 2 higher
OptionalWorkingDirectory Directory to start in when running the program, or NULL to use the current working directory
PipeWriteChild Optional HANDLE to pipe for redirecting output
PipeReadChild Optional HANDLE to pipe for redirecting input
Returns
The process handle for use in other process functions
CreateRunnableThread()
class FRunnableThread * FGenericPlatformProcess::CreateRunnableThread () static
Creates the platform-specific runnable thread.
This should only be called from FRunnableThread::Create.
Returns
The newly created thread
References CreateRunnableThread().
Referenced by CreateRunnableThread().
Daemonize()
bool FGenericPlatformProcess::Daemonize () static
Makes process run as a system service (daemon), i.e.
detaches it from whatever user session it was initially run from.
Returns
true if successful, false otherwise.
References Daemonize().
Referenced by Daemonize().
DeleteInterprocessSynchObject()
bool FGenericPlatformProcess::DeleteInterprocessSynchObject (FSemaphore * Object) static
Deletes an interprocess synchronization object.
Parameters
Object object to destroy.
References DeleteInterprocessSynchObject(), and Object.
Referenced by DeleteInterprocessSynchObject().
DumpThreadInfo()
void FGenericPlatformProcess::DumpThreadInfo (const TCHAR * MarkerName) inline static
Output information about the currently active thread.
Definition at line 308 of file GenericPlatformProcess.h.
ExecElevatedProcess()
bool FGenericPlatformProcess::ExecElevatedProcess (const TCHAR * URL, const TCHAR * Params, int32 * OutReturnCode) static
Executes a process as administrator, requesting elevation as necessary.
This call blocks until the process has returned.
References Params.
ExecProcess()
bool FGenericPlatformProcess::ExecProcess (const TCHAR * URL, const TCHAR * Params, int32 * OutReturnCode, FString * OutStdOut, FString * OutStdErr, const TCHAR * OptionalWorkingDirectory = NULL, bool bShouldEndWithParentProcess = false) static
Executes a process, returning the return code, stdout, and stderr.
This call blocks until the process has returned.
Parameters
OutReturnCode may be 0
OutStdOut may be 0
OutStdErr may be 0 @OptionalWorkingDirectory may be 0 @OptionalbShouldEndWithParentProcess false by default. True to make sure the process is killed with the parent processor (Not Supported on all Platforms)
References Params.
ExecutableName()
const TCHAR * FGenericPlatformProcess::ExecutableName (bool bRemoveExtension = true) static
Return the name of the currently running executable.
Parameters
bRemoveExtension true to remove the extension of the executable name, false to leave it intact
Returns
Name of the currently running executable
ExecutablePath()
const TCHAR * FGenericPlatformProcess::ExecutablePath () static
Return the path to the currently running executable.
Returns
Path of the currently running executable
ExploreFolder()
void FGenericPlatformProcess::ExploreFolder (const TCHAR * FilePath) static
Attempt to "explore" the folder specified by the provided file path.
Parameters
FilePath File path specifying a folder to explore
References Seconds.
FlushPoolSyncEvents()
void FGenericPlatformProcess::FlushPoolSyncEvents () static
Deletes all the recycled sync events contained by the pools.
References FlushPoolSyncEvents().
Referenced by FlushPoolSyncEvents().
FreeDllHandle()
void FGenericPlatformProcess::FreeDllHandle (void * DllHandle) static
Free a DLL.
GenerateApplicationPath()
FString FGenericPlatformProcess::GenerateApplicationPath (const FString & AppName, EBuildConfiguration BuildConfiguration) static
Generates the path to the specified application or game.
The application must reside in the Engine's binaries directory. The returned path is relative to this executable's directory.For example, calling this method with "UE4" and EBuildConfiguration::Debug on Windows 64-bit will generate the path "../Win64/UnrealEditor-Win64-Debug.exe"
Parameters
AppName The name of the application or game.
BuildConfiguration The build configuration of the game.
Returns
The generated application path.
GetApplicationMemoryUsage()
bool FGenericPlatformProcess::GetApplicationMemoryUsage (uint32 ProcessId, SIZE_T * OutMemoryUsage) static
Outputs the virtual memory usage, of the process with the specified PID.
GetApplicationName()
FString FGenericPlatformProcess::GetApplicationName (uint32 ProcessId) static
Returns the Name of process given by the PID.
Returns Empty string "" if PID not found.
GetApplicationSettingsDir()
FString FGenericPlatformProcess::GetApplicationSettingsDir (const ApplicationSettingsContext & Settings) static
Get application settings directory for a given context.
Parameters
Settings The context in which the application settings should be stored for.
Returns
A string to the appropriate directory.
GetArchitectureSuffix()
const TCHAR * FGenericPlatformProcess::GetArchitectureSuffix () static
Get the architecture suffix, if any.
Relates to UnrealArchitectureConfig.RequiresArchitectureFilenames in UnrealBuildTool
Returns
The platform's architecture suffix, or null if it isn't required
GetBinariesSubdirectory()
const TCHAR * FGenericPlatformProcess::GetBinariesSubdirectory () static
Used only by platforms with DLLs, this gives the subdirectory from binaries to find the executables.
GetCurrentCoreNumber()
uint32 FGenericPlatformProcess::GetCurrentCoreNumber () static
Retrieves the current hardware CPU core.
Returns
the current hardware core.
GetCurrentProcessId()
uint32 FGenericPlatformProcess::GetCurrentProcessId () static
Retrieves the ProcessId of this process.
Returns
the ProcessId of this process.
GetCurrentWorkingDirectory()
FString FGenericPlatformProcess::GetCurrentWorkingDirectory () static
Get the current working directory (only really makes sense on desktop platforms)
GetDesiredThreadForUObjectReferenceCollector()
ENamedThreads::Type FGenericPlatformProcess::GetDesiredThreadForUObjectReferenceCollector () static
specifies the thread to use for UObject reference collection
GetDllDirectories()
FORCEINLINE void FGenericPlatformProcess::GetDllDirectories (TArray< FString > & OutDllDirectories) inline static
Get the list of registered directories to search in when resolving implicitly loaded or filename-only DLLs.
Definition at line 258 of file GenericPlatformProcess.h.
References FORCEINLINE.
GetDllExport()
void * FGenericPlatformProcess::GetDllExport (void * DllHandle, const TCHAR * ProcName) static
Lookup the address of a DLL function.
GetDllHandle()
void * FGenericPlatformProcess::GetDllHandle (const TCHAR * Filename) static
Load a DLL.
References Filename.
GetGameBundleId()
FString FGenericPlatformProcess::GetGameBundleId () static
Retrieves the platform-specific bundle identifier or package name of the game.
Returns
The game's bundle identifier or package name.
GetModuleExtension()
const TCHAR * FGenericPlatformProcess::GetModuleExtension () static
Return the extension of dynamic library.
Returns
Extension of dynamic library.
See also
GetModulePrefix, GetModulesDirectory
GetModulePrefix()
const TCHAR * FGenericPlatformProcess::GetModulePrefix () static
Return the prefix of dynamic library (e.g.
lib)
Returns
The prefix string.
See also
GetModuleExtension, GetModulesDirectory
GetModulesDirectory()
const FString FGenericPlatformProcess::GetModulesDirectory () static
Used only by platforms with DLLs, this gives the full path to the main directory containing modules.
Returns
The path to the directory.
See also
GetModulePrefix, GetModuleExtension
GetPerFrameProcessorUsage()
bool FGenericPlatformProcess::GetPerFrameProcessorUsage (uint32 ProcessId, float & ProcessUsageFraction, float & IdleUsageFraction) inline static
Retrieves the current CPU Utilization for the current process in terms of percentage of all capacity.
Returns
the current hardware core.
Definition at line 282 of file GenericPlatformProcess.h.
GetProcReturnCode()
bool FGenericPlatformProcess::GetProcReturnCode (FProcHandle & ProcHandle, int32 * ReturnCode) static
Retrieves the termination status of the specified process.
GetStackSize()
uint32 FGenericPlatformProcess::GetStackSize () static
Get the active stack size for the currently running thread.
GetSynchEventFromPool()
class FEvent * FGenericPlatformProcess::GetSynchEventFromPool (bool bIsManualReset = false) static
Gets an event from the pool or creates a new one if necessary.
Parameters
bIsManualReset Whether the event requires manual reseting or not.
Returns
An event, or nullptr none could be created.
See also
CreateSynchEvent, ReturnSynchEventToPool
References GetSynchEventFromPool().
Referenced by FPooledSyncEvent::FPooledSyncEvent(), UE::PixelStreaming2::DoOnGameThreadAndWait(), GetSynchEventFromPool(), and FAsyncTaskBase::Start().
IsApplicationRunning() [1/2]
bool FGenericPlatformProcess::IsApplicationRunning (const TCHAR * ProcName) static
Returns true if the specified application is running.
IsApplicationRunning() [2/2]
bool FGenericPlatformProcess::IsApplicationRunning (uint32 ProcessId) static
Returns true if the specified application is running.
IsFirstInstance()
bool FGenericPlatformProcess::IsFirstInstance () static
Checks if we're the first instance.
An instance can become first if the previous first instance quits before it.
References IsFirstInstance().
Referenced by IsFirstInstance().
IsProcRunning()
bool FGenericPlatformProcess::IsProcRunning (FProcHandle & ProcessHandle) static
Returns true if the specified process is running.
Parameters
ProcessHandle handle returned from FPlatformProcess::CreateProc
Returns
true if the process is still running
LaunchFileInDefaultExternalApplication()
bool FGenericPlatformProcess::LaunchFileInDefaultExternalApplication (const TCHAR * FileName, const TCHAR * Parms = NULL, ELaunchVerb::Type Verb = ELaunchVerb::Open, bool bPromptToOpenOnFailure = true) static
Attempt to launch the provided file name in its default external application.
Similar to FPlatformProcess::LaunchURL, with the exception that if a default application isn't found for the file, the user will be prompted with an "Open With..." dialog.
Parameters
FileName Name of the file to attempt to launch in its default external application
Parms Optional parameters to the default application
Verb Optional verb to use when opening the file, if it applies for the platform.
Returns
true if the file is launched successfully, false otherwise.
References ELaunchVerb::Open.
LaunchURL()
void FGenericPlatformProcess::LaunchURL (const TCHAR * URL, const TCHAR * Parms, FString * Error) static
Launch a uniform resource locator (i.e.
http://www.epicgames.com/unreal). This is expected to return immediately as the URL is launched by another task. The URL param must already be a valid URL. If you're looking for code to properly escape a URL fragment, use FGenericPlatformHttp::UrlEncode.
References Error.
LaunchURLFiltered()
bool FGenericPlatformProcess::LaunchURLFiltered (const TCHAR * URL, const TCHAR * Parms, FString * Error, const UE::Core::FURLRequestFilter & Filter) static
Launch a uniform resource locator (i.e.
http://www.epicgames.com/unreal). This is expected to return immediately as the URL is launched by another task. The URL param must already be a valid URL. The URL is passed through the filter parameter for an added measure of security if the URL is from and untrusted source. If you're looking for code to properly escape a URL fragment, use FGenericPlatformHttp::UrlEncode.
Returns
true if URL passed the filter and was launched, false if it was rejected by the filter.
References Error, and Filter.
ModifyThreadAssignmentForUObjectReferenceCollector()
void FGenericPlatformProcess::ModifyThreadAssignmentForUObjectReferenceCollector (int32 & NumThreads, int32 & NumBackgroundThreads, ENamedThreads::Type & NormalThreadName, ENamedThreads::Type & BackgroundThreadName) static
allows a platform to override the threading configuration for reference collection
ModuleExists()
bool FGenericPlatformProcess::ModuleExists (const FString & Filename) static
Used only by platforms with DLLs, this confirms the existence of a given module.
This should be called with the proper extension for modules. Returning true should ensure that GetDllHandle() will find the same file.
References Filename.
NewInterprocessSynchObject() [1/2]
FSemaphore * FGenericPlatformProcess::NewInterprocessSynchObject (const FString & Name, bool bCreate, uint32 MaxLocks = 1) static
Creates or opens an interprocess synchronization object.
Parameters
Name name (so we can use it across processes).
bCreate If true, the function will try to create, otherwise will try to open existing.
MaxLocks Maximum amount of locks that the semaphore can have (pass 1 to make it act as mutex).
Returns
Pointer to heap allocated semaphore object. Caller is responsible for deletion.
References Name, and NewInterprocessSynchObject().
Referenced by NewInterprocessSynchObject(), and NewInterprocessSynchObject().
NewInterprocessSynchObject() [2/2]
FSemaphore * FGenericPlatformProcess::NewInterprocessSynchObject (const TCHAR * Name, bool bCreate, uint32 MaxLocks = 1) static
Creates or opens an interprocess synchronization object.
Parameters
Name name (so we can use it across processes).
bCreate If true, the function will try to create, otherwise will try to open existing.
MaxLocks Maximum amount of locks that the semaphore can have (pass 1 to make it act as mutex).
Returns
Pointer to heap allocated semaphore object. Caller is responsible for deletion.
References Name, and NewInterprocessSynchObject().
OpenProcess()
FProcHandle FGenericPlatformProcess::OpenProcess (uint32 ProcessID) static
Opens an existing process.
Parameters
ProcessID The process id of the process for which we want to obtain a handle.
Returns
The process handle for use in other process functions
PopDllDirectory()
FORCEINLINE void FGenericPlatformProcess::PopDllDirectory (const TCHAR * Directory) inline static
Unsets a directory to look for DLL files.
The same directory must be passed in as the Push call to validate
Definition at line 252 of file GenericPlatformProcess.h.
References FORCEINLINE.
PushDllDirectory()
FORCEINLINE void FGenericPlatformProcess::PushDllDirectory (const TCHAR * Directory) inline static
Set a directory to look for DLL files.
NEEDS to have a Pop call when complete
Definition at line 246 of file GenericPlatformProcess.h.
References FORCEINLINE.
ReadPipe()
FString FGenericPlatformProcess::ReadPipe (void * ReadPipe) static
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
Parameters
Pipe The handle to the pipe to read from.
Returns
A string containing the read data.
See also
ClosePipe, CreatePipe
References ReadPipe().
Referenced by ClosePipe(), CreatePipe(), ReadPipe(), and ReadPipeToArray().
ReadPipeToArray()
bool FGenericPlatformProcess::ReadPipeToArray (void * ReadPipe, TArray< uint8 > & Output) static
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
Parameters
Pipe The handle to the pipe to read from.
Output The data read.
Returns
true if successful (i.e. any data was read)
See also
ClosePipe, CreatePipe
References ReadPipe(), and ReadPipeToArray().
Referenced by ReadPipeToArray().
ReturnSynchEventToPool()
void FGenericPlatformProcess::ReturnSynchEventToPool (FEvent * Event) static
Returns an event to the pool.
Parameters
Event The event to return.
See also
CreateSynchEvent, GetSynchEventFromPool
References Event, and ReturnSynchEventToPool().
Referenced by FAsyncTaskBase::DestroyEvent(), UE::PixelStreaming2::DoOnGameThreadAndWait(), FPooledSyncEvent::operator=(), and ReturnSynchEventToPool().
SetCurrentWorkingDirectoryToBaseDir()
void FGenericPlatformProcess::SetCurrentWorkingDirectoryToBaseDir () static
SetProcessLimits()
bool FGenericPlatformProcess::SetProcessLimits (EProcessResource::Type Resource, uint64 Limit) inline static
Sets the process limits.
Parameters
Resource one of process resources.
Limit the maximum amount of the resource (for some OS, this means both hard and soft limits).
Returns
true on success, false otherwise.
Definition at line 383 of file GenericPlatformProcess.h.
SetShaderDir()
void FGenericPlatformProcess::SetShaderDir (const TCHAR * Where) static
SetThreadAffinityMask()
void FGenericPlatformProcess::SetThreadAffinityMask (uint64 AffinityMask) static
Change the thread processor affinity.
Parameters
AffinityMask A bitfield indicating what processors the thread is allowed to run on.
SetThreadName()
void FGenericPlatformProcess::SetThreadName (const TCHAR * ThreadName) inline static
Helper function to set thread name of the current thread.
Parameters
ThreadName Name to set
Definition at line 302 of file GenericPlatformProcess.h.
SetThreadPriority()
void FGenericPlatformProcess::SetThreadPriority (EThreadPriority NewPriority) static
Change the thread processor priority.
Parameters
NewPriority an EThreadPriority indicating what priority the thread is to run at.
SetupAudioThread()
void FGenericPlatformProcess::SetupAudioThread () inline static
Allow the platform to do anything it needs for audio thread.
Definition at line 317 of file GenericPlatformProcess.h.
SetupGameThread()
void FGenericPlatformProcess::SetupGameThread () inline static
Allow the platform to do anything it needs for game thread.
Definition at line 311 of file GenericPlatformProcess.h.
SetupRenderThread()
void FGenericPlatformProcess::SetupRenderThread () inline static
Allow the platform to do anything it needs for render thread.
Definition at line 314 of file GenericPlatformProcess.h.
ShaderDir()
const TCHAR * FGenericPlatformProcess::ShaderDir () static
ShaderWorkingDir()
const FString FGenericPlatformProcess::ShaderWorkingDir () static
Get the shader working directory.
Returns
The path to the directory.
ShouldSaveToUserDir()
bool FGenericPlatformProcess::ShouldSaveToUserDir () static
Content saved to the game or engine directories should be rerouted to user directories instead.
SkipWaitForStats()
bool FGenericPlatformProcess::SkipWaitForStats () inline static
force skip calling FThreadStats::WaitForStats()
Definition at line 834 of file GenericPlatformProcess.h.
References SkipWaitForStats().
Referenced by SkipWaitForStats().
SupportsMultithreading()
bool FGenericPlatformProcess::SupportsMultithreading () static
Gets whether this platform can use multiple threads.
Returns
true if the platform can use multiple threads, false otherwise.
References SupportsMultithreading().
Referenced by Async(), AsyncThread(), PhysSingleThreadedMode(), FStallingTaskQueue< T, TPaddingForCacheContention, NumPriorities >::Pop(), SupportsMultithreading(), and FMallocBinnedCommonUtils::Trim().
TearDown()
void FGenericPlatformProcess::TearDown () static
Tears down allocated process resources.
References TearDown().
Referenced by TearDown().
TeardownAudioThread()
void FGenericPlatformProcess::TeardownAudioThread () inline static
Allow the platform to tear down the audio thread.
Definition at line 320 of file GenericPlatformProcess.h.
TerminateProc()
void FGenericPlatformProcess::TerminateProc (FProcHandle & ProcessHandle, bool KillTree = false) static
Terminates a process.
Parameters
ProcessHandle handle returned from FPlatformProcess::CreateProc
KillTree Whether the entire process tree should be terminated.
TerminateProcTreeWithPredicate()
void FGenericPlatformProcess::TerminateProcTreeWithPredicate (FProcHandle & ProcessHandle, TFunctionRef< bool(uint32 ProcessId, const TCHAR *ApplicationName)> Predicate) static
Terminates a process tree.
Parameters
ProcessHandle handle returned from FPlatformProcess::CreateProc
Predicate that returns true if the process identified by ProcessId and ApplicationName should be terminated with its children, else that process and its children will be kept alive
References Predicate.
TryGetMemoryUsage()
bool FGenericPlatformProcess::TryGetMemoryUsage (FProcHandle & ProcessHandle, FPlatformProcessMemoryStats & OutStats) inline static
Queries the memory usage of the process.
Returns whether the operation is supported and succeeded.
Definition at line 839 of file GenericPlatformProcess.h.
UE_DEPRECATED()
FGenericPlatformProcess::UE_DEPRECATED (5. 0, "Please use GetSynchEventFromPool to create a new event, and ReturnSynchEventToPool to release the event.")
Creates a new event.
Parameters
bIsManualReset Whether the event requires manual reseting or not.
Returns
A new event, or nullptr none could be created.
See also
GetSynchEventFromPool, ReturnSynchEventToPool
UserDir()
const TCHAR * FGenericPlatformProcess::UserDir () static
Get user directory.
NOTE: Only one return value is valid at a time!
UserHomeDir()
const TCHAR * FGenericPlatformProcess::UserHomeDir () static
Get the user home directory.
NOTE: Only one return value is valid at a time!
UserName()
const TCHAR * FGenericPlatformProcess::UserName (bool bOnlyAlphaNumeric = true) static
Get user name.
NOTE: Only one return value is valid at a time!
Referenced by FApp::IsAuthorizedUser().
UserSettingsDir()
const TCHAR * FGenericPlatformProcess::UserSettingsDir () static
Get the user settings directory.
NOTE: Only one return value is valid at a time!
UserTempDir()
const TCHAR * FGenericPlatformProcess::UserTempDir () static
Get the user temporary directory.
NOTE: Only one return value is valid at a time!
WaitAndFork()
EWaitAndForkResult FGenericPlatformProcess::WaitAndFork () static
Waits for process signals and forks child processes.
WaitAndFork stalls the invoking process and forks child processes when signals are sent to it from an external source. Forked child processes will provide a return value of EWaitAndForkResult::Child, while the parent process will not return until IsEngineExitRequested() is true (EWaitAndForkResult::Parent) or there was an error (EWaitAndForkResult::Error) The signal the parent process expects is platform-specific (i.e. SIGRTMIN+1 on Linux).
WaitForProc()
void FGenericPlatformProcess::WaitForProc (FProcHandle & ProcessHandle) static
Waits for a process to stop.
Parameters
ProcessHandle handle returned from FPlatformProcess::CreateProc
WritePipe() [1/2]
bool FGenericPlatformProcess::WritePipe (void * WritePipe, const FString & Message, FString * OutWritten = nullptr) static
Sends the message to process through pipe.
Parameters
WritePipe Pipe for writing.
Message The message to be written.
OutWritten Optional parameter to know how much of the string written.
Returns
True if all bytes written successfully.
See also
CreatePipe, ClosePipe, ReadPipe
References WritePipe().
Referenced by ClosePipe(), CreatePipe(), WritePipe(), and WritePipe().
WritePipe() [2/2]
bool FGenericPlatformProcess::WritePipe (void * WritePipe, const uint8 * Data, const int32 DataLength, int32 * OutDataLength = nullptr) static
Sends data to process through pipe.
Parameters
WritePipe Pipe for writing.
Data The data to be written.
DataLength how many bytes to write.
OutDataLength Optional parameter to know how many bytes had been written.
Returns
True if all bytes written successfully.
See also
CreatePipe, ClosePipe, ReadPipe
References WritePipe().
Yield()
FORCEINLINE void FGenericPlatformProcess::Yield () inline static
Tells the processor to pause for implementation-specific amount of time.
Is used for spin-loops to improve the speed at which the code detects the release of the lock and power-consumption.
Definition at line 855 of file GenericPlatformProcess.h.
References FORCEINLINE, and unimplemented.
Referenced by FAAArrayQueue< FTask >::dequeueInternal(), UE::FSpinLock::Lock(), UE::TRWSpinLock< uint32 >::ReadLock(), UE::TRWSpinLock< uint32 >::WriteLock(), and YieldCycles().
YieldCycles()
FORCEINLINE void FGenericPlatformProcess::YieldCycles (uint64 Cycles) inline static
Tells the processor to pause for at least the amount of cycles given.
Is used for spin-loops to improve the speed at which the code detects the release of the lock and power-consumption.
Definition at line 875 of file GenericPlatformProcess.h.
References FORCEINLINE, unimplemented, and Yield().
The documentation for this struct was generated from the following file:
GenericPlatformProcess.h