Unreal Engine 5.6 C++ API: TTripleBuffer< BufferType > Class Template Reference
TTripleBuffer< BufferType > Class Template Reference
Template for triple buffers.
#include "TripleBuffer.h"
Public Member Functions
TTripleBuffer ()
Default constructor.
TTripleBuffer (BufferType(&InBuffers)[3])
Create and initialize a new instance using provided buffers.
TTripleBuffer (const BufferType &InValue)
Create and initialize a new instance with a given buffer value.
TTripleBuffer (ENoInit)
Default constructor (no initialization).
~TTripleBuffer ()
Destructor.
BufferType & GetWriteBuffer ()
Get the current write buffer.
bool IsDirty () const
Check whether a new value is available for reading.
BufferType & Read ()
Read a value from the current read buffer.
void Reset ()
Reset the buffer.
const BufferType & SwapAndRead ()
Convenience method for fetching and reading the latest buffer.
void SwapReadBuffers ()
Swap the latest read buffer, if available.
void SwapWriteBuffers ()
Swap a new write buffer (makes current write buffer available for reading).
void Write (const BufferType Value)
Write a value to the current write buffer.
void WriteAndSwap (const BufferType Value)
Convenience method for writing the latest buffer and fetching a new one.
Protected Member Functions
void Initialize ()
Initialize the triple buffer.
Private Types
enum EBufferFlag {
Dirty = 0x40 , Initial = 0x06 , ReaderMask = 0x03 , TempMask = 0x30 ,
TempShift = 4 , WriterMask = 0x0c , WriterShift = 2
}
Enumerates human readable bit values for accessing the Flags field.
Private Member Functions
TTripleBuffer (const TTripleBuffer &)
Hidden copy constructor (triple buffers cannot be copied).
MS_ALIGN (16) int32 volatile Flags GCC_ALIGN(16)
Buffer access flags.
TTripleBuffer & operator= (const TTripleBuffer &)
Hidden copy assignment (triple buffers cannot be copied).
Static Private Member Functions
static FORCEINLINE int32 SwapReadWithTempFlags (int32 Flags)
Swaps the read and temp buffer indices in the Flags field.
static FORCEINLINE int32 SwapWriteWithTempFlags (int32 Flags)
Swaps the write and temp buffer indices in the Flags field, and sets the dirty bit.
Private Attributes
BufferType * Buffers
The three buffers.
bool OwnsMemory
Whether this instance owns the buffer memory.
Detailed Description
template<typename BufferType>
class TTripleBuffer< BufferType >
Template for triple buffers.
This template implements a lock-free triple buffer that can be used to exchange data between two threads that are producing and consuming at different rates. Instead of atomically exchanging pointers to the buffers, we atomically update a Flags register that holds the indices into a 3-element buffer array.
The three buffers are named as follows:
Read buffer: This is where Read() will read the latest value from
Write buffer: This is where Write() will write a new value to
Temp buffer: This is the second back-buffer currently not used for reading or writing
Please note that reading and writing to the buffer does not automatically swap the back-buffers. Instead, two separate methods, SwapReadBuffers() and SwapWriteBuffers() are provided. For convenience, we also provide SwapAndRead() and WriteAndSwap() to update and swap the buffers using a single method call.
A dirty flag indicates whether a new value has been written and swapped into the second back-buffer and is available for reading. It can be checked using the IsDirtyMethod(). As an optimization, SwapReadBuffers() and SwapAndRead() will not perform a back-buffer swap if no new data is available.
This class is thread-safe in single-producer, single-consumer scenarios.
Based on ideas and C code in "Triple Buffering as a Concurrency Mechanism" (Reddit.com)
Parameters
BufferType The type of buffered items.
Definition at line 39 of file TripleBuffer.h.
Member Enumeration Documentation
EBufferFlag
template<typename BufferType> enum TTripleBuffer::EBufferFlag private
Enumerates human readable bit values for accessing the Flags field.
Enumerator
Dirty
Indicates whether a new buffer is available for reading.
Initial
Initial flags value (0dttwwrr; dirty = false, temp index = 0, write index = 1, read index = 2)
ReaderMask
Bit mask for accessing the read buffer index (bit 0-1).
TempMask
Bit mask for the index of the unused/clean/empty buffer (bit 4-5).
TempShift
Bit shift for accessing the temp buffer index.
WriterMask
Bit mask for accessing the write buffer index (bit 2-3).
WriterShift
Bit shift for accessing the write buffer index.
Definition at line 42 of file TripleBuffer.h.
Constructor & Destructor Documentation
TTripleBuffer() [1/5]
template<typename BufferType> TTripleBuffer< BufferType >::TTripleBuffer () inline nodiscard
Default constructor.
Definition at line 69 of file TripleBuffer.h.
References Buffers, and Initialize().
Referenced by TTripleBuffer(), and operator=().
TTripleBuffer() [2/5]
template<typename BufferType> TTripleBuffer< BufferType >::TTripleBuffer (ENoInit) inline explicit nodiscard
Default constructor (no initialization).
Definition at line 76 of file TripleBuffer.h.
References Initialize().
TTripleBuffer() [3/5]
template<typename BufferType> TTripleBuffer< BufferType >::TTripleBuffer (const BufferType & InValue) inline explicit nodiscard
Create and initialize a new instance with a given buffer value.
Parameters
InValue The initial value of all three buffers.
Definition at line 86 of file TripleBuffer.h.
References Buffers, and Initialize().
TTripleBuffer() [4/5]
template<typename BufferType> TTripleBuffer< BufferType >::TTripleBuffer (BufferType(&) InBuffers[3]) inline nodiscard
Create and initialize a new instance using provided buffers.
The elements of the provided items array are expected to have the following initial contents: 0 = Temp 1 = Write 2 = Read
Parameters
InBuffers The buffer memory to use.
Definition at line 103 of file TripleBuffer.h.
References Buffers, Dirty, Flags, Initial, and OwnsMemory.
~TTripleBuffer()
template<typename BufferType> TTripleBuffer< BufferType >::~TTripleBuffer () inline
Destructor.
Definition at line 111 of file TripleBuffer.h.
References Buffers, and OwnsMemory.
TTripleBuffer() [5/5]
template<typename BufferType> TTripleBuffer< BufferType >::TTripleBuffer (const TTripleBuffer< BufferType > &) private
Hidden copy constructor (triple buffers cannot be copied).
References TTripleBuffer().
Member Function Documentation
GetWriteBuffer()
template<typename BufferType> BufferType & TTripleBuffer< BufferType >::GetWriteBuffer () inline nodiscard
Get the current write buffer.
Returns
Reference to write buffer.
Definition at line 172 of file TripleBuffer.h.
References Buffers, Flags, WriterMask, and WriterShift.
Initialize()
template<typename BufferType> void TTripleBuffer< BufferType >::Initialize () inline protected
Initialize the triple buffer.
Definition at line 240 of file TripleBuffer.h.
References Buffers, Flags, Initial, and OwnsMemory.
Referenced by TTripleBuffer(), TTripleBuffer(), and TTripleBuffer().
IsDirty()
template<typename BufferType> bool TTripleBuffer< BufferType >::IsDirty () const inline nodiscard
Check whether a new value is available for reading.
Returns
true if a new value is available, false otherwise.
Definition at line 126 of file TripleBuffer.h.
References Dirty, and Flags.
Referenced by SwapReadBuffers().
MS_ALIGN()
template<typename BufferType> TTripleBuffer< BufferType >::MS_ALIGN (16) volatile private
Buffer access flags.
References Flags, and GCC_ALIGN.
operator=()
template<typename BufferType> TTripleBuffer & TTripleBuffer< BufferType >::operator= (const TTripleBuffer< BufferType > &) private
Hidden copy assignment (triple buffers cannot be copied).
References TTripleBuffer().
Read()
template<typename BufferType> BufferType & TTripleBuffer< BufferType >::Read () inline nodiscard
Read a value from the current read buffer.
Returns
Reference to the read buffer's value.
See also
SwapRead, Write
Definition at line 137 of file TripleBuffer.h.
References Buffers, Flags, and ReaderMask.
Referenced by SwapAndRead().
Reset()
template<typename BufferType> void TTripleBuffer< BufferType >::Reset () inline
Reset the buffer.
Definition at line 207 of file TripleBuffer.h.
References Flags, Initial, and FAndroidMisc::MemoryBarrier().
SwapAndRead()
template<typename BufferType> const BufferType & TTripleBuffer< BufferType >::SwapAndRead () inline nodiscard
Convenience method for fetching and reading the latest buffer.
Returns
Reference to the buffer.
See also
SwapRead, Read, WriteAndSwap
Definition at line 219 of file TripleBuffer.h.
References Read(), and SwapReadBuffers().
SwapReadBuffers()
template<typename BufferType> void TTripleBuffer< BufferType >::SwapReadBuffers () inline
Swap the latest read buffer, if available.
Will not perform a back-buffer swap if no new data is available (dirty flag = false).
See also
SwapWrite, Read
Definition at line 149 of file TripleBuffer.h.
References Flags, IsDirty(), and SwapReadWithTempFlags().
Referenced by SwapAndRead().
SwapReadWithTempFlags()
template<typename BufferType> FORCEINLINE int32 TTripleBuffer< BufferType >::SwapReadWithTempFlags (int32 Flags) inline static nodiscard private
Swaps the read and temp buffer indices in the Flags field.
Definition at line 250 of file TripleBuffer.h.
References Flags, FORCEINLINE, ReaderMask, TempMask, and WriterMask.
Referenced by SwapReadBuffers().
SwapWriteBuffers()
template<typename BufferType> void TTripleBuffer< BufferType >::SwapWriteBuffers () inline
Swap a new write buffer (makes current write buffer available for reading).
See also
SwapRead, Write
Definition at line 182 of file TripleBuffer.h.
References Flags, and SwapWriteWithTempFlags().
Referenced by WriteAndSwap().
SwapWriteWithTempFlags()
template<typename BufferType> FORCEINLINE int32 TTripleBuffer< BufferType >::SwapWriteWithTempFlags (int32 Flags) inline static nodiscard private
Swaps the write and temp buffer indices in the Flags field, and sets the dirty bit.
Definition at line 256 of file TripleBuffer.h.
References Dirty, Flags, FORCEINLINE, ReaderMask, TempMask, and WriterMask.
Referenced by SwapWriteBuffers().
Write()
template<typename BufferType> void TTripleBuffer< BufferType >::Write (const BufferType Value) inline
Write a value to the current write buffer.
Parameters
Value The value to write.
See also
SwapWrite, Read
Definition at line 199 of file TripleBuffer.h.
References Buffers, Flags, Value, WriterMask, and WriterShift.
WriteAndSwap()
template<typename BufferType> void TTripleBuffer< BufferType >::WriteAndSwap (const BufferType Value) inline
Convenience method for writing the latest buffer and fetching a new one.
Parameters
Value The value to write into the buffer.
See also
SwapAndRead, SwapWrite, Write
Definition at line 231 of file TripleBuffer.h.
References SwapWriteBuffers(), Value, and Write.
Field Documentation
Buffers
template<typename BufferType> BufferType* TTripleBuffer< BufferType >::Buffers private
The three buffers.
Definition at line 272 of file TripleBuffer.h.
Referenced by TTripleBuffer(), TTripleBuffer(), TTripleBuffer(), ~TTripleBuffer(), GetWriteBuffer(), Initialize(), Read(), and Write().
OwnsMemory
template<typename BufferType> bool TTripleBuffer< BufferType >::OwnsMemory private
Whether this instance owns the buffer memory.
Definition at line 278 of file TripleBuffer.h.
Referenced by TTripleBuffer(), ~TTripleBuffer(), and Initialize().
The documentation for this class was generated from the following file:
TripleBuffer.h