Unreal Engine 5.6 C++ API: FKeyChain Struct Reference
FKeyChain Struct Reference
#include "KeyChainUtilities.h"
Public Member Functions
FKeyChain ()=default
FKeyChain (const FKeyChain &Other)
FKeyChain (FKeyChain &&Other)
TMap< FGuid, FNamedAESKey > & GetEncryptionKeys ()
const TMap< FGuid, FNamedAESKey > & GetEncryptionKeys () const
const FNamedAESKey * GetPrincipalEncryptionKey () const
PRAGMA_DISABLE_DEPRECATION_WARNINGS FRSAKeyHandle GetSigningKey () const
FKeyChain & operator= (const FKeyChain &Other)
FKeyChain & operator= (FKeyChain &&Other)
void SetEncryptionKeys (const TMap< FGuid, FNamedAESKey > &keys)
void SetPrincipalEncryptionKey (const FNamedAESKey *key)
void SetSigningKey (FRSAKeyHandle key)
UE_DEPRECATED (5.1, "Use Get/SetPrincipalEncryptionKey instead") const FNamedAESKey *MasterEncryptionKey
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.1, "Use Get/SetSigningKey instead") FRSAKeyHandle SigningKey
UE_DEPRECATED (5.1, "Use GetEncryptionKeys instead") TMap< FGuid
Data Fields
FNamedAESKey EncryptionKeys
Detailed Description
Definition at line 16 of file KeyChainUtilities.h.
Constructor & Destructor Documentation
FKeyChain() [1/3]
FKeyChain::FKeyChain () default
Referenced by FKeyChain(), FKeyChain(), operator=(), and operator=().
FKeyChain() [2/3]
FKeyChain::FKeyChain (const FKeyChain & Other) inline
Definition at line 22 of file KeyChainUtilities.h.
References FKeyChain(), Find, GetEncryptionKeys(), Other, SetEncryptionKeys(), SetPrincipalEncryptionKey(), and SetSigningKey().
FKeyChain() [3/3]
FKeyChain::FKeyChain (FKeyChain && Other) inline
Definition at line 33 of file KeyChainUtilities.h.
References FKeyChain(), Find, GetEncryptionKeys(), InvalidRSAKeyHandle, MoveTemp(), Other, SetEncryptionKeys(), SetPrincipalEncryptionKey(), and SetSigningKey().
Member Function Documentation
GetEncryptionKeys() [1/2]
TMap< FGuid, FNamedAESKey > & FKeyChain::GetEncryptionKeys () inline
Definition at line 94 of file KeyChainUtilities.h.
References EncryptionKeys.
GetEncryptionKeys() [2/2]
const TMap< FGuid, FNamedAESKey > & FKeyChain::GetEncryptionKeys () const inline
Definition at line 93 of file KeyChainUtilities.h.
References EncryptionKeys.
Referenced by FKeyChain(), FKeyChain(), KeyChainUtilities::ApplyEncryptionKeys(), KeyChainUtilities::LoadKeyChainFromFile(), operator=(), and operator=().
GetPrincipalEncryptionKey()
const FNamedAESKey * FKeyChain::GetPrincipalEncryptionKey () const inline
Definition at line 90 of file KeyChainUtilities.h.
GetSigningKey()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FRSAKeyHandle FKeyChain::GetSigningKey () const inline
Definition at line 87 of file KeyChainUtilities.h.
operator=() [1/2]
FKeyChain & FKeyChain::operator= (const FKeyChain & Other) inline
Definition at line 48 of file KeyChainUtilities.h.
References FKeyChain(), Find, GetEncryptionKeys(), Other, SetEncryptionKeys(), SetPrincipalEncryptionKey(), and SetSigningKey().
operator=() [2/2]
FKeyChain & FKeyChain::operator= (FKeyChain && Other) inline
Definition at line 65 of file KeyChainUtilities.h.
References FKeyChain(), Find, GetEncryptionKeys(), InvalidRSAKeyHandle, MoveTemp(), Other, SetEncryptionKeys(), SetPrincipalEncryptionKey(), and SetSigningKey().
SetEncryptionKeys()
void FKeyChain::SetEncryptionKeys (const TMap< FGuid, FNamedAESKey > & keys) inline
Definition at line 96 of file KeyChainUtilities.h.
References EncryptionKeys.
Referenced by FKeyChain(), FKeyChain(), operator=(), and operator=().
SetPrincipalEncryptionKey()
void FKeyChain::SetPrincipalEncryptionKey (const FNamedAESKey * key) inline
Definition at line 91 of file KeyChainUtilities.h.
Referenced by FKeyChain(), FKeyChain(), KeyChainUtilities::LoadKeyChainFromFile(), operator=(), and operator=().
SetSigningKey()
void FKeyChain::SetSigningKey (FRSAKeyHandle key) inline
Definition at line 88 of file KeyChainUtilities.h.
Referenced by FKeyChain(), FKeyChain(), KeyChainUtilities::LoadKeyChainFromFile(), operator=(), and operator=().
UE_DEPRECATED() [1/3]
FKeyChain::UE_DEPRECATED (5. 1, "Use Get/SetPrincipalEncryptionKey instead") const
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FKeyChain::UE_DEPRECATED (5. 1, "Use Get/SetSigningKey instead")
References InvalidRSAKeyHandle.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FKeyChain::UE_DEPRECATED (5. 1, "Use GetEncryptionKeys instead")
References UE_DEPRECATED().
Field Documentation
EncryptionKeys
FNamedAESKey FKeyChain::EncryptionKeys
Definition at line 103 of file KeyChainUtilities.h.
Referenced by GetEncryptionKeys(), GetEncryptionKeys(), and SetEncryptionKeys().
The documentation for this struct was generated from the following file:
KeyChainUtilities.h