Unreal Engine 5.6 C++ API: FAttenuationListenerData Struct Reference
FAttenuationListenerData Struct Reference
Struct used to cache listener attenuation vector math results.
#include "AudioDevice.h"
Public Member Functions
UE_DEPRECATED (4.25, "Use FAttenuationListenerData::Create that passes a ListenerIndex") static FAttenuationListenerData Create(const FAudioDevice &AudioDevice
Computes and returns some geometry related to the listener and the given sound transform.
Static Public Member Functions
static FAttenuationListenerData Create (const FAudioDevice &AudioDevice, int32 ListenerIndex, const FTransform &InSoundTransform, const FSoundAttenuationSettings &InAttenuationSettings)
Computes and returns some geometry related to the listener and the given sound transform.
Data Fields
FVector::FReal AttenuationDistance
const FSoundAttenuationSettings * AttenuationSettings
const FTransform const FTransform const FSoundAttenuationSettings & InAttenuationSettings
const FTransform & InListenerTransform
const FTransform const FTransform & InSoundTransform
FVector ListenerToSoundDir
FVector::FReal ListenerToSoundDistance
FVector::FReal ListenerToSoundDistanceForPanning
FTransform ListenerTransform
const FTransform SoundTransform
Private Member Functions
FAttenuationListenerData (const FTransform &InListenerTransform, const FTransform &InSoundTransform, const FSoundAttenuationSettings &InAttenuationSettings)
Detailed Description
Struct used to cache listener attenuation vector math results.
Definition at line 342 of file AudioDevice.h.
Constructor & Destructor Documentation
FAttenuationListenerData()
FAttenuationListenerData::FAttenuationListenerData (const FTransform & InListenerTransform, const FTransform & InSoundTransform, const FSoundAttenuationSettings & InAttenuationSettings) inline private
Definition at line 364 of file AudioDevice.h.
References FAttenuationListenerData(), AttenuationDistance, AttenuationSettings, FVector, InAttenuationSettings, InListenerTransform, InSoundTransform, ListenerToSoundDir, ListenerToSoundDistance, ListenerToSoundDistanceForPanning, ListenerTransform, and SoundTransform.
Referenced by FAttenuationListenerData(), and Create().
Member Function Documentation
Create()
FAttenuationListenerData FAttenuationListenerData::Create (const FAudioDevice & AudioDevice, int32 ListenerIndex, const FTransform & InSoundTransform, const FSoundAttenuationSettings & InAttenuationSettings) static
Computes and returns some geometry related to the listener and the given sound transform.
References FAttenuationListenerData(), Create(), InAttenuationSettings, and InSoundTransform.
Referenced by Create().
UE_DEPRECATED()
FAttenuationListenerData::UE_DEPRECATED (4. 25, "Use FAttenuationListenerData::Create that passes a ListenerIndex") const &
Computes and returns some geometry related to the listener and the given sound transform.
Field Documentation
AttenuationDistance
FVector::FReal FAttenuationListenerData::AttenuationDistance
Definition at line 345 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
AttenuationSettings
const FSoundAttenuationSettings* FAttenuationListenerData::AttenuationSettings
Definition at line 354 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
InAttenuationSettings
const FTransform const FTransform const FSoundAttenuationSettings& FAttenuationListenerData::InAttenuationSettings
Definition at line 358 of file AudioDevice.h.
Referenced by FAttenuationListenerData(), and Create().
InListenerTransform
const FTransform& FAttenuationListenerData::InListenerTransform
Definition at line 358 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
InSoundTransform
const FTransform const FTransform& FAttenuationListenerData::InSoundTransform
Definition at line 358 of file AudioDevice.h.
Referenced by FAttenuationListenerData(), and Create().
ListenerToSoundDir
FVector FAttenuationListenerData::ListenerToSoundDir
Definition at line 344 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
ListenerToSoundDistance
FVector::FReal FAttenuationListenerData::ListenerToSoundDistance
Definition at line 346 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
ListenerToSoundDistanceForPanning
FVector::FReal FAttenuationListenerData::ListenerToSoundDistanceForPanning
Definition at line 350 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
ListenerTransform
FTransform FAttenuationListenerData::ListenerTransform
Definition at line 352 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
SoundTransform
const FTransform FAttenuationListenerData::SoundTransform
Definition at line 353 of file AudioDevice.h.
Referenced by FAttenuationListenerData().
The documentation for this struct was generated from the following file:
AudioDevice.h