Unreal Engine 5.6 C++ API: TStaticMeshVertexData< VertexDataType > Class Template Reference
TStaticMeshVertexData< VertexDataType > Class Template Reference
The implementation of the static mesh vertex data storage type.
#include "StaticMeshVertexData.h"
Public Member Functions
TStaticMeshVertexData (bool InNeedsCPUAccess=false)
Constructor.
void Assign (const TArray< VertexDataType > &Other)
Assignment.
void Empty (uint32 NumVertices) override
bool GetAllowCPUAccess () const override
uint8 * GetDataPointer () override
const FResourceArrayInterface * GetResourceArray () const
FResourceArrayInterface * GetResourceArray () override
SIZE_T GetResourceSize () const override
Helper function to return the amount of memory allocated by this container.
uint32 GetStride () const override
bool IsValidIndex (uint32 Index) override
virtual int32 Num () const override
Helper function to return the number of elements by this container.
void OverrideFreezeSizeAndAlignment (int64 &Size, int32 &Alignment) const override
void ResizeBuffer (uint32 NumVertices, EResizeBufferFlags BufferFlags=EResizeBufferFlags::None) override
Resizes the vertex data buffer, discarding any data which no longer fits.
void Serialize (FArchive &Ar, bool bForcePerElementSerialization=false) override
Serializer for this class.
Public Member Functions inherited from FStaticMeshVertexDataInterface
virtual ~FStaticMeshVertexDataInterface ()
Virtual destructor.
Private Types
using FVertexResourceArray = TResourceArray<VertexDataType, VERTEXBUFFER_ALIGNMENT>
Private Attributes
FVertexResourceArray Data
Detailed Description
template<typename VertexDataType>
class TStaticMeshVertexData< VertexDataType >
The implementation of the static mesh vertex data storage type.
Definition at line 11 of file StaticMeshVertexData.h.
Member Typedef Documentation
FVertexResourceArray
template<typename VertexDataType> using TStaticMeshVertexData< VertexDataType >::FVertexResourceArray = TResourceArray<VertexDataType, VERTEXBUFFER_ALIGNMENT> private
Definition at line 14 of file StaticMeshVertexData.h.
Constructor & Destructor Documentation
TStaticMeshVertexData()
template<typename VertexDataType> TStaticMeshVertexData< VertexDataType >::TStaticMeshVertexData (bool InNeedsCPUAccess = false) inline
Constructor.
Parameters
InNeedsCPUAccess - true if resource array data should be CPU accessible
Definition at line 22 of file StaticMeshVertexData.h.
References Data.
Referenced by FSkinWeightVertexData< VertexDataType >::FSkinWeightVertexData().
Member Function Documentation
Assign()
template<typename VertexDataType> void TStaticMeshVertexData< VertexDataType >::Assign (const TArray< VertexDataType > & Other) inline
Assignment.
This is currently the only method which allows for modifying an existing resource array
Definition at line 105 of file StaticMeshVertexData.h.
References GetDataPointer(), Other, and ResizeBuffer().
Empty()
template<typename VertexDataType> void TStaticMeshVertexData< VertexDataType >::Empty (uint32 NumVertices) inline override virtual
Implements FStaticMeshVertexDataInterface.
Definition at line 53 of file StaticMeshVertexData.h.
References Data.
GetAllowCPUAccess()
template<typename VertexDataType> bool TStaticMeshVertexData< VertexDataType >::GetAllowCPUAccess () const inline override virtual
Implements FStaticMeshVertexDataInterface.
Definition at line 136 of file StaticMeshVertexData.h.
References Data.
GetDataPointer()
template<typename VertexDataType> uint8 * TStaticMeshVertexData< VertexDataType >::GetDataPointer () inline override virtual
Returns
uint8 pointer to the resource data array
Implements FStaticMeshVertexDataInterface.
Definition at line 73 of file StaticMeshVertexData.h.
References Data.
Referenced by Assign().
GetResourceArray() [1/2]
template<typename VertexDataType> const FResourceArrayInterface * TStaticMeshVertexData< VertexDataType >::GetResourceArray () const inline
Definition at line 86 of file StaticMeshVertexData.h.
References Data.
GetResourceArray() [2/2]
template<typename VertexDataType> FResourceArrayInterface * TStaticMeshVertexData< VertexDataType >::GetResourceArray () inline override virtual
Returns
resource array interface access
Implements FStaticMeshVertexDataInterface.
Definition at line 81 of file StaticMeshVertexData.h.
References Data.
GetResourceSize()
template<typename VertexDataType> SIZE_T TStaticMeshVertexData< VertexDataType >::GetResourceSize () const inline override virtual
Helper function to return the amount of memory allocated by this container.
Returns
Number of bytes allocated by this container.
Implements FStaticMeshVertexDataInterface.
Definition at line 120 of file StaticMeshVertexData.h.
References Data.
GetStride()
template<typename VertexDataType> uint32 TStaticMeshVertexData< VertexDataType >::GetStride () const inline override virtual
Returns
stride of the vertex type stored in the resource data array
Implements FStaticMeshVertexDataInterface.
Definition at line 66 of file StaticMeshVertexData.h.
IsValidIndex()
template<typename VertexDataType> bool TStaticMeshVertexData< VertexDataType >::IsValidIndex (uint32 Index) inline override virtual
Implements FStaticMeshVertexDataInterface.
Definition at line 58 of file StaticMeshVertexData.h.
References Data.
Num()
template<typename VertexDataType> virtual int32 TStaticMeshVertexData< VertexDataType >::Num () const inline override virtual
Helper function to return the number of elements by this container.
Returns
Number of elements allocated by this container.
Implements FStaticMeshVertexDataInterface.
Definition at line 131 of file StaticMeshVertexData.h.
References Data.
OverrideFreezeSizeAndAlignment()
template<typename VertexDataType> void TStaticMeshVertexData< VertexDataType >::OverrideFreezeSizeAndAlignment (int64 & Size, int32 & Alignment) const inline override virtual
Implements FStaticMeshVertexDataInterface.
Definition at line 141 of file StaticMeshVertexData.h.
References TSequenceHistory< HistorySize >::Size.
ResizeBuffer()
template<typename VertexDataType> void TStaticMeshVertexData< VertexDataType >::ResizeBuffer (uint32 NumVertices, EResizeBufferFlags BufferFlags = EResizeBufferFlags::None) inline override virtual
Resizes the vertex data buffer, discarding any data which no longer fits.
Parameters
NumVertices - The number of vertices to allocate the buffer for.
BufferFlags - Flags to define the expected behavior of the buffer
Implements FStaticMeshVertexDataInterface.
Definition at line 33 of file StaticMeshVertexData.h.
References AllowSlackOnGrow, AllowSlackOnReduce, Data, EnumHasAnyFlags(), No, None, and Yes.
Referenced by Assign().
Serialize()
template<typename VertexDataType> void TStaticMeshVertexData< VertexDataType >::Serialize (FArchive & Ar, bool bForcePerElementSerialization = false) inline override virtual
Serializer for this class.
Parameters
Ar - archive to serialize to
B - data to serialize
Implements FStaticMeshVertexDataInterface.
Definition at line 97 of file StaticMeshVertexData.h.
References Ar, and Data.
Field Documentation
Data
template<typename VertexDataType> FVertexResourceArray TStaticMeshVertexData< VertexDataType >::Data private
Definition at line 15 of file StaticMeshVertexData.h.
Referenced by TStaticMeshVertexData(), Empty(), GetAllowCPUAccess(), GetDataPointer(), GetResourceArray(), GetResourceArray(), GetResourceSize(), IsValidIndex(), Num(), ResizeBuffer(), and Serialize().
The documentation for this class was generated from the following file:
StaticMeshVertexData.h