Unreal Engine 5.6 C++ Documentation: MovementBaseUtility Namespace Reference
MovementBaseUtility Namespace Reference
MovementBaseUtility provides utilities for working with movement bases, for which we may need relative positioning info.
Functions
bool IsDynamicBase (const UPrimitiveComponent *MovementBase)
Determine whether MovementBase can possibly move.
bool IsSimulatedBase (const UPrimitiveComponent *MovementBase)
Determine whether MovementBase is simulating or attached to a simulating object.
bool UseRelativeLocation (const UPrimitiveComponent *MovementBase)
Determine if we should use relative positioning when based on a component (because it may move).
void AddTickDependency (FTickFunction &BasedObjectTick, UPrimitiveComponent *NewBase)
Ensure that BasedObjectTick ticks after NewBase.
void RemoveTickDependency (FTickFunction &BasedObjectTick, UPrimitiveComponent *OldBase)
Remove tick dependency of BasedObjectTick on OldBase.
FVector GetMovementBaseVelocity (const UPrimitiveComponent *MovementBase, const FName BoneName)
Get the velocity of the given component, first checking the ComponentVelocity and falling back to the physics velocity if necessary.
FVector GetMovementBaseTangentialVelocity (const UPrimitiveComponent *MovementBase, const FName BoneName, const FVector &WorldLocation)
Get the tangential velocity at WorldLocation for the given component.
bool GetMovementBaseTransform (const UPrimitiveComponent *MovementBase, const FName BoneName, FVector &OutLocation, FQuat &OutQuat)
Get the transform (local-to-world) for the given MovementBase, optionally at the location of a bone.
bool TransformLocationToWorld (const UPrimitiveComponent *MovementBase, const FName BoneName, const FVector &LocalLocation, FVector &OutLocationWorldSpace)
Convert a local location to a world location for a given MovementBase.
bool TransformLocationToLocal (const UPrimitiveComponent *MovementBase, const FName BoneName, const FVector &WorldSpaceLocation, FVector &OutLocalLocation)
Convert a world location to a local location for a given MovementBase, optionally at the location of a bone.
bool TransformDirectionToWorld (const UPrimitiveComponent *MovementBase, const FName BoneName, const FVector &LocalDirection, FVector &OutDirectionWorldSpace)
Convert a local direction to a world direction for a given MovementBase.
bool TransformDirectionToLocal (const UPrimitiveComponent *MovementBase, const FName BoneName, const FVector &WorldSpaceDirection, FVector &OutLocalDirection)
Convert a world direction to a local direction for a given MovementBase, optionally relative to the orientation of a bone.
Detailed Description
MovementBaseUtility provides utilities for working with movement bases, for which we may need relative positioning info.
Function Documentation
AddTickDependency()
void MovementBaseUtility::AddTickDependency (FTickFunction & BasedObjectTick, UPrimitiveComponent * NewBase)
Ensure that BasedObjectTick ticks after NewBase.
References AddTickDependency().
GetMovementBaseTangentialVelocity()
FVector MovementBaseUtility::GetMovementBaseTangentialVelocity (const UPrimitiveComponent * MovementBase, const FName BoneName, const FVector & WorldLocation)
Get the tangential velocity at WorldLocation for the given component.
References GetMovementBaseTangentialVelocity().
GetMovementBaseTransform()
bool MovementBaseUtility::GetMovementBaseTransform (const UPrimitiveComponent * MovementBase, const FName BoneName, FVector & OutLocation, FQuat & OutQuat)
Get the transform (local-to-world) for the given MovementBase, optionally at the location of a bone.
Returns false if MovementBase is nullptr, or if BoneName is not a valid bone.
References GetMovementBaseTransform().
GetMovementBaseVelocity()
FVector MovementBaseUtility::GetMovementBaseVelocity (const UPrimitiveComponent * MovementBase, const FName BoneName)
Get the velocity of the given component, first checking the ComponentVelocity and falling back to the physics velocity if necessary.
References GetMovementBaseVelocity().
IsDynamicBase()
bool MovementBaseUtility::IsDynamicBase (const UPrimitiveComponent * MovementBase)
Determine whether MovementBase can possibly move.
References IsDynamicBase().
IsSimulatedBase()
bool MovementBaseUtility::IsSimulatedBase (const UPrimitiveComponent * MovementBase)
Determine whether MovementBase is simulating or attached to a simulating object.
References IsSimulatedBase().
RemoveTickDependency()
void MovementBaseUtility::RemoveTickDependency (FTickFunction & BasedObjectTick, UPrimitiveComponent * OldBase)
Remove tick dependency of BasedObjectTick on OldBase.
References RemoveTickDependency().
TransformDirectionToLocal()
bool MovementBaseUtility::TransformDirectionToLocal (const UPrimitiveComponent * MovementBase, const FName BoneName, const FVector & WorldSpaceDirection, FVector & OutLocalDirection)
Convert a world direction to a local direction for a given MovementBase, optionally relative to the orientation of a bone.
Returns false if MovementBase is nullptr, or if BoneName is not a valid bone. Scaling is ignored.
References TransformDirectionToLocal().
TransformDirectionToWorld()
bool MovementBaseUtility::TransformDirectionToWorld (const UPrimitiveComponent * MovementBase, const FName BoneName, const FVector & LocalDirection, FVector & OutDirectionWorldSpace)
Convert a local direction to a world direction for a given MovementBase.
Returns false if MovementBase is nullptr, or if BoneName is not a valid bone. Scaling is ignored.
References TransformDirectionToWorld().
TransformLocationToLocal()
bool MovementBaseUtility::TransformLocationToLocal (const UPrimitiveComponent * MovementBase, const FName BoneName, const FVector & WorldSpaceLocation, FVector & OutLocalLocation)
Convert a world location to a local location for a given MovementBase, optionally at the location of a bone.
Returns false if MovementBase is nullptr, or if BoneName is not a valid bone. Scaling is ignored.
References TransformLocationToLocal().
TransformLocationToWorld()
bool MovementBaseUtility::TransformLocationToWorld (const UPrimitiveComponent * MovementBase, const FName BoneName, const FVector & LocalLocation, FVector & OutLocationWorldSpace)
Convert a local location to a world location for a given MovementBase.
Returns false if MovementBase is nullptr, or if BoneName is not a valid bone. Scaling is ignored.
References TransformLocationToWorld().
UseRelativeLocation()
bool MovementBaseUtility::UseRelativeLocation (const UPrimitiveComponent * MovementBase) inline
Determine if we should use relative positioning when based on a component (because it may move).
Definition at line 141 of file Character.h.
References IsDynamicBase(), and UseRelativeLocation().