Unreal Engine 5.6 C++ API: UE::Geometry::TSparseListSet< ElementType > Struct Template Reference
UE::Geometry::TSparseListSet< ElementType > Struct Template Reference
TSparseListSet stores a sparse set of indexed variable-size lists.
#include "SparseListSet.h"
Data Structures
struct FChunk
struct FList
struct FListHandle
Public Member Functions
TSparseListSet ()
TSparseListSet (int BlockSizeIn, int BlocksPerChunkIn)
FListHandle AllocateAt (int32 ListIndex)
Create a list at the given ListIndex.
void Clear (int32 ListIndex)
Remove all elements from the list at ListIndex.
bool Contains (int32 ListIndex, ElementType Value) const
Search for the given Value in list at ListIndex.
template<typename FuncType>
void Enumerate (int32 ListIndex, FuncType Func) const
Call ApplyFunc on each element of the list at ListIndex.
template<typename FuncType>
bool EnumerateEarlyOut (int32 ListIndex, FuncType ApplyFunc) const
Call ApplyFunc on each element of the list at ListIndex, until ApplyFunc returns false.
int32 GetCount (int32 ListIndex) const
void Insert (FListHandle ListHandle, ElementType Value)
Insert Value into List identified by ListHandle.
void Insert (int32 ListIndex, ElementType Value)
Insert Value into List at ListIndex.
bool IsAllocated (int32 ListIndex) const
bool Remove (int32 ListIndex, ElementType Value)
remove first occurrence of Value from the list at ListIndex
void SetValues (FListHandle ListHandle, const TArray< ElementType > &Values)
Set the values of the List identified by ListHandle.
void SetValues (int32 ListIndex, const TArray< ElementType > &Values)
Set the values of the List at ListIndex.
Private Member Functions
ElementType * AllocateNewBlockMemory ()
void Clear_Internal (FList &List)
void FreeBlockMemory (ElementType *Block)
void Insert_Internal (FList &List, ElementType Value)
void SetValues_Internal (FList &List, const TArray< ElementType > &Values)
Private Attributes
FCriticalSection AllocationLock
int BlockSize = 32
int BlocksPerChunk = 256
TArray< TUniquePtr< FChunk > > ChunkList
TArray< ElementType * > FreeList
TDynamicVector< FList > Lists
Detailed Description
template<typename ElementType>
struct UE::Geometry::TSparseListSet< ElementType >
TSparseListSet stores a sparse set of indexed variable-size lists.
This is useful in cases where many relatively small lists that have a 1-1 correspondence with a bounded index space are needed, eg for per-vertex lists for a mesh, per-cell lists for an octree, etc.
The interface is compatible with FSmallListSet, which may be more effective for very small lists (optimized for ~8 elements), but does not scale very well to larger lists (10s-to-100s).
Internally, TSparseListSet uses a strategy where the small lists are stored in sequences of fixed-size blocks, similar to FDynamicVector, but the block size is configurable. The blocks are allocated from larger "chunks" of blocks (also of configurable size). These parameters can be set on construction to values appropriate for particular use cases.
TSparseListSet can support parallel insertion into the lists. Note however that lists cannot be added (via AllocateAt) while parallel insertion occurs via Insert(Index). To allow for this type of usage, AllocateAt() returns a FListHandle which can then be used with Insert() or SetValues() even while other AllocateAt() calls occur (within a lock).
Definition at line 38 of file SparseListSet.h.
Constructor & Destructor Documentation
TSparseListSet() [1/2]
template<typename ElementType> UE::Geometry::TSparseListSet< ElementType >::TSparseListSet () inline
Definition at line 42 of file SparseListSet.h.
References BlockSize, BlocksPerChunk, ChunkList, and MakeUnique().
TSparseListSet() [2/2]
template<typename ElementType> UE::Geometry::TSparseListSet< ElementType >::TSparseListSet (int BlockSizeIn, int BlocksPerChunkIn) inline
Parameters
BlockSizeIn defines size of small blocks that each list is made up of
BlocksPerChunkIn defines size of large chunks that small blocks are allocated from
Definition at line 52 of file SparseListSet.h.
References BlockSize, BlocksPerChunk, ChunkList, FMath::Clamp(), and MakeUnique().
Member Function Documentation
AllocateAt()
template<typename ElementType> FListHandle UE::Geometry::TSparseListSet< ElementType >::AllocateAt (int32 ListIndex) inline
Create a list at the given ListIndex.
Returns
Handle to allocted list that can be used with Insert and SetValues in multi-threaded contexts
Definition at line 79 of file SparseListSet.h.
References AllocateNewBlockMemory(), UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, UE::Geometry::TSparseListSet< ElementType >::FList::CurBlock, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, and Lists.
AllocateNewBlockMemory()
template<typename ElementType> ElementType * UE::Geometry::TSparseListSet< ElementType >::AllocateNewBlockMemory () inline private
Definition at line 291 of file SparseListSet.h.
References AllocationLock, UE::Geometry::TSparseListSet< ElementType >::FChunk::BlocksAllocated, BlockSize, BlocksPerChunk, ChunkList, FreeList, UE::Geometry::TSparseListSet< ElementType >::FChunk::GetBlockBufferPtr(), UE::Geometry::TSparseListSet< ElementType >::FChunk::Initialize(), and MakeUnique().
Referenced by AllocateAt(), Insert_Internal(), and SetValues_Internal().
Clear()
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::Clear (int32 ListIndex) inline
Remove all elements from the list at ListIndex.
Definition at line 138 of file SparseListSet.h.
References checkSlow, Clear_Internal(), IsAllocated(), and Lists.
Clear_Internal()
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::Clear_Internal (FList & List) inline private
Definition at line 279 of file SparseListSet.h.
References UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, UE::Geometry::TSparseListSet< ElementType >::FList::CurBlock, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, and FreeBlockMemory().
Referenced by Clear(), and SetValues_Internal().
Contains()
template<typename ElementType> bool UE::Geometry::TSparseListSet< ElementType >::Contains (int32 ListIndex, ElementType Value) const
Search for the given Value in list at ListIndex.
Returns
true if found
Definition at line 386 of file SparseListSet.h.
References UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, BlockSize, checkSlow, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, IsAllocated(), Lists, and Value.
Enumerate()
template<typename ElementType> template<typename FuncType> void UE::Geometry::TSparseListSet< ElementType >::Enumerate (int32 ListIndex, FuncType Func) const inline
Call ApplyFunc on each element of the list at ListIndex.
Definition at line 168 of file SparseListSet.h.
References UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, BlockSize, checkSlow, UE::Geometry::TSparseListSet< ElementType >::FList::CurBlock, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, IsAllocated(), and Lists.
EnumerateEarlyOut()
template<typename ElementType> template<typename FuncType> bool UE::Geometry::TSparseListSet< ElementType >::EnumerateEarlyOut (int32 ListIndex, FuncType ApplyFunc) const inline
Call ApplyFunc on each element of the list at ListIndex, until ApplyFunc returns false.
Returns
true if all elements were processed and ApplyFunc never returned false
Definition at line 192 of file SparseListSet.h.
References UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, BlockSize, checkSlow, UE::Geometry::TSparseListSet< ElementType >::FList::CurBlock, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, IsAllocated(), and Lists.
FreeBlockMemory()
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::FreeBlockMemory (ElementType * Block) inline private
Definition at line 314 of file SparseListSet.h.
References AllocationLock, and FreeList.
Referenced by Clear_Internal(), and Remove().
GetCount()
template<typename ElementType> int32 UE::Geometry::TSparseListSet< ElementType >::GetCount (int32 ListIndex) const inline
Returns
the size of the list at ListIndex
Definition at line 149 of file SparseListSet.h.
References UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, BlockSize, checkSlow, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, IsAllocated(), Lists, and FMath::Max.
Insert() [1/2]
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::Insert (FListHandle ListHandle, ElementType Value) inline
Insert Value into List identified by ListHandle.
Definition at line 101 of file SparseListSet.h.
References Insert_Internal(), UE::Geometry::TSparseListSet< ElementType >::FListHandle::ListRef, and Value.
Insert() [2/2]
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::Insert (int32 ListIndex, ElementType Value) inline
Insert Value into List at ListIndex.
Definition at line 92 of file SparseListSet.h.
References checkSlow, Insert_Internal(), IsAllocated(), Lists, and Value.
Insert_Internal()
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::Insert_Internal (FList & List, ElementType Value) inline private
Definition at line 247 of file SparseListSet.h.
References AllocateNewBlockMemory(), UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, BlockSize, UE::Geometry::TSparseListSet< ElementType >::FList::CurBlock, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, and Value.
Referenced by Insert(), and Insert().
IsAllocated()
template<typename ElementType> bool UE::Geometry::TSparseListSet< ElementType >::IsAllocated (int32 ListIndex) const inline
Returns
true if a list has been allocated at the given ListIndex
Definition at line 64 of file SparseListSet.h.
References Lists.
Referenced by Clear(), Contains(), Enumerate(), EnumerateEarlyOut(), GetCount(), Insert(), Remove(), and SetValues().
Remove()
template<typename ElementType> bool UE::Geometry::TSparseListSet< ElementType >::Remove (int32 ListIndex, ElementType Value) inline
remove first occurrence of Value from the list at ListIndex
Returns
false if Value was not in this list
Definition at line 325 of file SparseListSet.h.
References UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, BlockSize, check, checkSlow, UE::Geometry::TSparseListSet< ElementType >::FList::CurBlock, UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex, FreeBlockMemory(), IsAllocated(), Lists, Stop, Swap, and Value.
SetValues() [1/2]
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::SetValues (FListHandle ListHandle, const TArray< ElementType > & Values) inline
Set the values of the List identified by ListHandle.
Definition at line 121 of file SparseListSet.h.
References UE::Geometry::TSparseListSet< ElementType >::FListHandle::ListRef, and SetValues_Internal().
SetValues() [2/2]
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::SetValues (int32 ListIndex, const TArray< ElementType > & Values) inline
Set the values of the List at ListIndex.
Definition at line 111 of file SparseListSet.h.
References checkSlow, IsAllocated(), Lists, and SetValues_Internal().
SetValues_Internal()
template<typename ElementType> void UE::Geometry::TSparseListSet< ElementType >::SetValues_Internal (FList & List, const TArray< ElementType > & Values) inline private
Definition at line 258 of file SparseListSet.h.
References AllocateNewBlockMemory(), UE::Geometry::TSparseListSet< ElementType >::FList::Blocks, BlockSize, Clear_Internal(), UE::Geometry::TSparseListSet< ElementType >::FList::CurBlock, and UE::Geometry::TSparseListSet< ElementType >::FList::CurIndex.
Referenced by SetValues(), and SetValues().
Field Documentation
AllocationLock
template<typename ElementType> FCriticalSection UE::Geometry::TSparseListSet< ElementType >::AllocationLock private
Definition at line 235 of file SparseListSet.h.
Referenced by AllocateNewBlockMemory(), and FreeBlockMemory().
BlockSize
template<typename ElementType> int UE::Geometry::TSparseListSet< ElementType >::BlockSize = 32 private
Definition at line 220 of file SparseListSet.h.
Referenced by TSparseListSet(), TSparseListSet(), AllocateNewBlockMemory(), Contains(), Enumerate(), EnumerateEarlyOut(), GetCount(), Insert_Internal(), Remove(), and SetValues_Internal().
BlocksPerChunk
template<typename ElementType> int UE::Geometry::TSparseListSet< ElementType >::BlocksPerChunk = 256 private
Definition at line 222 of file SparseListSet.h.
Referenced by TSparseListSet(), TSparseListSet(), and AllocateNewBlockMemory().
ChunkList
template<typename ElementType> TArray<TUniquePtr<FChunk> > UE::Geometry::TSparseListSet< ElementType >::ChunkList private
Definition at line 233 of file SparseListSet.h.
Referenced by TSparseListSet(), TSparseListSet(), and AllocateNewBlockMemory().
FreeList
template<typename ElementType> TArray<ElementType*> UE::Geometry::TSparseListSet< ElementType >::FreeList private
Definition at line 234 of file SparseListSet.h.
Referenced by AllocateNewBlockMemory(), and FreeBlockMemory().
Lists
template<typename ElementType> TDynamicVector<FList> UE::Geometry::TSparseListSet< ElementType >::Lists private
Definition at line 244 of file SparseListSet.h.
Referenced by AllocateAt(), Clear(), Contains(), Enumerate(), EnumerateEarlyOut(), GetCount(), Insert(), IsAllocated(), Remove(), and SetValues().
The documentation for this struct was generated from the following file:
SparseListSet.h