Unreal Engine 5.6 C++ API: TListTypeTraits< TFieldPath< T > > Struct Template Reference
TListTypeTraits< TFieldPath< T > > Struct Template Reference
Pointer-related functionality (e.g.
#include "TableViewTypeTraits.h"
Data Structures
class SerializerType
Public Types
using MapKeyFuncs = TDefaultMapHashableKeyFuncs<TFieldPath<T>, TSharedRef<ITableRow>, false>
using MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TFieldPath<T>, FSparseItemInfo, false>
typedef TFieldPath< T > NullableType
using SetKeyFuncs = DefaultKeyFuncs< TFieldPath<T> >
Static Public Member Functions
template<typename U>
static void AddReferencedObjects (FReferenceCollector &Collector, TArray< TFieldPath< T > > &ItemsWithGeneratedWidgets, TSet< TFieldPath< T > > &SelectedItems, TMap< const U *, TFieldPath< T > > &WidgetToItemMap)
static FString DebugDump (TFieldPath< T > InPtr)
static bool IsPtrValid (const TFieldPath< T > &InPtr)
static TFieldPath< T > MakeNullPtr ()
static TFieldPath< T > NullableItemTypeConvertToItemType (const TFieldPath< T > &InPtr)
static void ResetPtr (TFieldPath< T > &InPtr)
Detailed Description
template<typename T>
struct TListTypeTraits< TFieldPath< T > >
Pointer-related functionality (e.g.
setting to nullptr, testing for nullptr) specialized for TFieldPaths.
Definition at line 615 of file TableViewTypeTraits.h.
Member Typedef Documentation
MapKeyFuncs
template<typename T> using TListTypeTraits< TFieldPath< T > >::MapKeyFuncs = TDefaultMapHashableKeyFuncs<TFieldPath<T>, TSharedRef<ITableRow>, false>
Definition at line 620 of file TableViewTypeTraits.h.
MapKeyFuncsSparse
template<typename T> using TListTypeTraits< TFieldPath< T > >::MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TFieldPath<T>, FSparseItemInfo, false>
Definition at line 621 of file TableViewTypeTraits.h.
NullableType
template<typename T> typedef TFieldPath<T> TListTypeTraits< TFieldPath< T > >::NullableType
Definition at line 618 of file TableViewTypeTraits.h.
SetKeyFuncs
template<typename T> using TListTypeTraits< TFieldPath< T > >::SetKeyFuncs = DefaultKeyFuncs< TFieldPath<T> >
Definition at line 622 of file TableViewTypeTraits.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> template<typename U> void TListTypeTraits< TFieldPath< T > >::AddReferencedObjects (FReferenceCollector & Collector, TArray< TFieldPath< T > > & ItemsWithGeneratedWidgets, TSet< TFieldPath< T > > & SelectedItems, TMap< const U *, TFieldPath< T > > & WidgetToItemMap) inline static
Definition at line 625 of file TableViewTypeTraits.h.
References Item.
DebugDump()
template<typename T> FString TListTypeTraits< TFieldPath< T > >::DebugDump (TFieldPath< T > InPtr) inline static
Definition at line 678 of file TableViewTypeTraits.h.
References TFieldPath< PropertyType >::Get(), TEXT, and UPTRINT_x_FMT.
IsPtrValid()
template<typename T> bool TListTypeTraits< TFieldPath< T > >::IsPtrValid (const TFieldPath< T > & InPtr) inline static
Definition at line 658 of file TableViewTypeTraits.h.
References TFieldPath< PropertyType >::Get().
MakeNullPtr()
template<typename T> TFieldPath< T > TListTypeTraits< TFieldPath< T > >::MakeNullPtr () inline static
Definition at line 668 of file TableViewTypeTraits.h.
NullableItemTypeConvertToItemType()
template<typename T> TFieldPath< T > TListTypeTraits< TFieldPath< T > >::NullableItemTypeConvertToItemType (const TFieldPath< T > & InPtr) inline static
Definition at line 673 of file TableViewTypeTraits.h.
ResetPtr()
template<typename T> void TListTypeTraits< TFieldPath< T > >::ResetPtr (TFieldPath< T > & InPtr) inline static
Definition at line 663 of file TableViewTypeTraits.h.
References FFieldPath::Reset().
The documentation for this struct was generated from the following file:
TableViewTypeTraits.h