Unreal Engine 5.6 C++ API: UE::Geometry::FCubeGrid::FCubeFace Class Reference
UE::Geometry::FCubeGrid::FCubeFace Class Reference
A face always refers to coordinates in the grid space.
#include "CubeGrid.h"
Public Member Functions
FCubeFace ()
MODELINGCOMPONENTS_API FCubeFace (const FVector3d &PointOnFace, EFaceDirection Direction, uint8 SourceCubeGridPower)
const FVector3d & GetCenter () const
EFaceDirection GetDirection () const
MODELINGCOMPONENTS_API FVector3d GetMaxCorner () const
MODELINGCOMPONENTS_API FVector3d GetMinCorner () const
FVector3d GetNormal () const
uint8 GetSourceCubeGridPower () const
bool operator!= (const FCubeFace &Other) const
bool operator== (const FCubeFace &Other) const
Private Attributes
FVector3d Center
uint8 CubeGridPower
EFaceDirection Direction
Detailed Description
A face always refers to coordinates in the grid space.
It is always on grid, and tied to a particular grid power.
Definition at line 73 of file CubeGrid.h.
Constructor & Destructor Documentation
FCubeFace() [1/2]
MODELINGCOMPONENTS_API UE::Geometry::FCubeGrid::FCubeFace::FCubeFace (const FVector3d & PointOnFace, EFaceDirection Direction, uint8 SourceCubeGridPower)
References Direction, and UE_API.
Referenced by FCubeFace(), operator!=(), and operator==().
FCubeFace() [2/2]
UE::Geometry::FCubeGrid::FCubeFace::FCubeFace () inline
Definition at line 78 of file CubeGrid.h.
References FCubeFace(), UE::Geometry::FCubeGrid::PositiveZ, and Zero.
Member Function Documentation
GetCenter()
const FVector3d & UE::Geometry::FCubeGrid::FCubeFace::GetCenter () const inline
Definition at line 84 of file CubeGrid.h.
References Center.
GetDirection()
EFaceDirection UE::Geometry::FCubeGrid::FCubeFace::GetDirection () const inline
Definition at line 85 of file CubeGrid.h.
References Direction.
GetMaxCorner()
MODELINGCOMPONENTS_API FVector3d UE::Geometry::FCubeGrid::FCubeFace::GetMaxCorner () const
References UE_API.
GetMinCorner()
MODELINGCOMPONENTS_API FVector3d UE::Geometry::FCubeGrid::FCubeFace::GetMinCorner () const
References UE_API.
GetNormal()
FVector3d UE::Geometry::FCubeGrid::FCubeFace::GetNormal () const inline
Definition at line 87 of file CubeGrid.h.
References Direction, and UE::Geometry::FCubeGrid::DirToNormal().
GetSourceCubeGridPower()
uint8 UE::Geometry::FCubeGrid::FCubeFace::GetSourceCubeGridPower () const inline
Definition at line 93 of file CubeGrid.h.
References CubeGridPower.
operator!=()
bool UE::Geometry::FCubeGrid::FCubeFace::operator!= (const FCubeFace & Other) const inline
Definition at line 99 of file CubeGrid.h.
References FCubeFace(), and Other.
operator==()
bool UE::Geometry::FCubeGrid::FCubeFace::operator== (const FCubeFace & Other) const inline
Definition at line 95 of file CubeGrid.h.
References FCubeFace(), Center, Direction, and Other.
Field Documentation
Center
FVector3d UE::Geometry::FCubeGrid::FCubeFace::Center private
Definition at line 106 of file CubeGrid.h.
Referenced by GetCenter(), and operator==().
CubeGridPower
uint8 UE::Geometry::FCubeGrid::FCubeFace::CubeGridPower private
Definition at line 109 of file CubeGrid.h.
Referenced by GetSourceCubeGridPower().
Direction
EFaceDirection UE::Geometry::FCubeGrid::FCubeFace::Direction private
Definition at line 108 of file CubeGrid.h.
Referenced by FCubeFace(), GetDirection(), GetNormal(), and operator==().
The documentation for this class was generated from the following file:
CubeGrid.h