Unreal Engine 5.6 C++ API: FQuartzTickableObject Class Reference
FQuartzTickableObject Class Reference
#include "QuartzSubscription.h"
Data Structures
struct FCommandDelegateGameThreadData
struct FMetronomeDelegateGameThreadData
Public Member Functions
FQuartzTickableObject ()
FQuartzTickableObject (const FQuartzTickableObject &Other)=default
virtual ~FQuartzTickableObject () override
int32 AddCommandDelegate (const FOnQuartzCommandEventBP &InDelegate)
void AddMetronomeBpDelegate (EQuartzCommandQuantization InQuantizationBoundary, const FOnQuartzMetronomeEventBP &OnQuantizationEvent)
const Audio::FQuartzOffset & GetQuartzOffset () const
Audio::FQuartzGameThreadSubscriber GetQuartzSubscriber ()
FQuartzTickableObject * Init (UWorld *InWorldPtr)
bool IsInitialized () const
virtual void OnCommandEvent (const Audio::FQuartzQuantizedCommandDelegateData &Data) override
virtual void OnMetronomeEvent (const Audio::FQuartzMetronomeDelegateData &Data) override
virtual void OnQueueCommandEvent (const Audio::FQuartzQueueCommandData &Data) override
FQuartzTickableObject & operator= (const FQuartzTickableObject &)=default
virtual void ProcessCommand (const Audio::FQuartzMetronomeDelegateData &Data)
virtual void ProcessCommand (const Audio::FQuartzQuantizedCommandDelegateData &Data)
virtual void ProcessCommand (const Audio::FQuartzQueueCommandData &Data)
bool QuartzIsTickable () const
void QuartzTick (float DeltaTime)
UE_DEPRECATED (5.5, "This should not be called directly, use the ICommandListener interface instead.") void ExecCommand(const Audio
UE_DEPRECATED (5.5, "This should not be called directly, use the IMetronomeEventListener interface instead.") void ExecCommand(const Audio
UE_DEPRECATED (5.5, "This should not be called directly, use the IQueueCommandListener interface instead.") void ExecCommand(const Audio
Protected Member Functions
void QuartzUnsubscribe ()
void SetNotificationAnticipationAmountMilliseconds (const double Milliseconds)
void SetNotificationAnticipationAmountMusicalDuration (const EQuartzCommandQuantization Duration, const double Multiplier)
virtual bool ShouldUnsubscribe ()
Private Attributes
FQuartzGameThreadCommandQueuePtr CommandQueuePtr
FMetronomeDelegateGameThreadData MetronomeDelegates [static_cast< int32 >(EQuartzCommandQuantization::Count)]
Audio::FQuartzOffset NotificationOffset
TArray< FCommandDelegateGameThreadData > QuantizedCommandDelegates
FQuartzSubscriptionToken QuartzSubscriptionToken
TArray< TFunction< void(FQuartzTickableObject *)> > TempCommandQueue
Detailed Description
Definition at line 43 of file QuartzSubscription.h.
Constructor & Destructor Documentation
FQuartzTickableObject() [1/2]
FQuartzTickableObject::FQuartzTickableObject ()
Definition at line 17 of file QuartzSubscription.cpp.
Referenced by FQuartzTickableObject(), Init(), and operator=().
FQuartzTickableObject() [2/2]
FQuartzTickableObject::FQuartzTickableObject (const FQuartzTickableObject & Other) default
References FQuartzTickableObject(), and Other.
~FQuartzTickableObject()
FQuartzTickableObject::~FQuartzTickableObject () override virtual
Definition at line 20 of file QuartzSubscription.cpp.
References QuartzUnsubscribe().
Member Function Documentation
AddCommandDelegate()
int32 FQuartzTickableObject::AddCommandDelegate (const FOnQuartzCommandEventBP & InDelegate)
Definition at line 49 of file QuartzSubscription.cpp.
References Num, and QuantizedCommandDelegates.
AddMetronomeBpDelegate()
void FQuartzTickableObject::AddMetronomeBpDelegate (EQuartzCommandQuantization InQuantizationBoundary, const FOnQuartzMetronomeEventBP & OnQuantizationEvent)
Definition at line 169 of file QuartzSubscription.cpp.
References MetronomeDelegates.
GetQuartzOffset()
const Audio::FQuartzOffset & FQuartzTickableObject::GetQuartzOffset () const inline
Definition at line 95 of file QuartzSubscription.h.
References NotificationOffset.
GetQuartzSubscriber()
Audio::FQuartzGameThreadSubscriber FQuartzTickableObject::GetQuartzSubscriber ()
Definition at line 144 of file QuartzSubscription.cpp.
References CommandQueuePtr, MakeShared(), and NotificationOffset.
Init()
FQuartzTickableObject * FQuartzTickableObject::Init (UWorld * InWorldPtr)
Definition at line 25 of file QuartzSubscription.cpp.
References FQuartzTickableObject(), CommandQueuePtr, ensure, MakeShared(), and QuartzSubscriptionToken.
IsInitialized()
bool FQuartzTickableObject::IsInitialized () const inline
Definition at line 69 of file QuartzSubscription.h.
References QuartzSubscriptionToken.
OnCommandEvent()
void FQuartzTickableObject::OnCommandEvent (const Audio::FQuartzQuantizedCommandDelegateData & Data) override virtual
Definition at line 68 of file QuartzSubscription.cpp.
References checkSlow, FThreadSafeCounter::Decrement(), DecrementSlotIndexOnStartedCvar, Audio::FQuartzQuantizedCommandDelegateData::DelegateID, Audio::FQuartzQuantizedCommandDelegateData::DelegateSubType, FThreadSafeCounter::Increment(), FQuartzTickableObject::FCommandDelegateGameThreadData::MulticastDelegate, ProcessCommand(), QuantizedCommandDelegates, QuartzSubscriptionToken, FQuartzTickableObject::FCommandDelegateGameThreadData::RefCount, Audio::FQuartzCrossThreadMessage::RequestReceived(), and FThreadSafeCounter::Reset().
Referenced by UE_DEPRECATED().
OnMetronomeEvent()
void FQuartzTickableObject::OnMetronomeEvent (const Audio::FQuartzMetronomeDelegateData & Data) override virtual
Definition at line 112 of file QuartzSubscription.cpp.
References Audio::FQuartzMetronomeDelegateData::Bar, Audio::FQuartzMetronomeDelegateData::Beat, Audio::FQuartzMetronomeDelegateData::BeatFraction, Audio::FQuartzMetronomeDelegateData::ClockName, MetronomeDelegates, ProcessCommand(), Audio::FQuartzMetronomeDelegateData::Quantization, QuartzSubscriptionToken, and Audio::FQuartzCrossThreadMessage::RequestReceived().
Referenced by UE_DEPRECATED().
OnQueueCommandEvent()
void FQuartzTickableObject::OnQueueCommandEvent (const Audio::FQuartzQueueCommandData & Data) override virtual
Definition at line 126 of file QuartzSubscription.cpp.
References ProcessCommand().
Referenced by UE_DEPRECATED().
operator=()
FQuartzTickableObject & FQuartzTickableObject::operator= (const FQuartzTickableObject &) default
References FQuartzTickableObject(), DeltaTime, and UE_API.
ProcessCommand() [1/3]
virtual void FQuartzTickableObject::ProcessCommand (const Audio::FQuartzMetronomeDelegateData & Data) inline virtual
Definition at line 91 of file QuartzSubscription.h.
ProcessCommand() [2/3]
virtual void FQuartzTickableObject::ProcessCommand (const Audio::FQuartzQuantizedCommandDelegateData & Data) inline virtual
Definition at line 90 of file QuartzSubscription.h.
Referenced by OnCommandEvent(), OnMetronomeEvent(), and OnQueueCommandEvent().
ProcessCommand() [3/3]
virtual void FQuartzTickableObject::ProcessCommand (const Audio::FQuartzQueueCommandData & Data) inline virtual
Reimplemented in UAudioComponent.
Definition at line 92 of file QuartzSubscription.h.
QuartzIsTickable()
bool FQuartzTickableObject::QuartzIsTickable () const
Definition at line 164 of file QuartzSubscription.cpp.
References CommandQueuePtr.
QuartzTick()
void FQuartzTickableObject::QuartzTick (float DeltaTime)
Definition at line 154 of file QuartzSubscription.cpp.
References CommandQueuePtr, DeltaTime, QuartzUnsubscribe(), and ShouldUnsubscribe().
QuartzUnsubscribe()
void FQuartzTickableObject::QuartzUnsubscribe () protected
Definition at line 44 of file QuartzSubscription.cpp.
References QuartzSubscriptionToken.
Referenced by ~FQuartzTickableObject(), and QuartzTick().
SetNotificationAnticipationAmountMilliseconds()
void FQuartzTickableObject::SetNotificationAnticipationAmountMilliseconds (const double Milliseconds) protected
Definition at line 132 of file QuartzSubscription.cpp.
References Milliseconds, and NotificationOffset.
SetNotificationAnticipationAmountMusicalDuration()
void FQuartzTickableObject::SetNotificationAnticipationAmountMusicalDuration (const EQuartzCommandQuantization Duration, const double Multiplier) protected
Definition at line 138 of file QuartzSubscription.cpp.
References Duration, Multiplier, and NotificationOffset.
ShouldUnsubscribe()
virtual bool FQuartzTickableObject::ShouldUnsubscribe () inline protected virtual
Definition at line 102 of file QuartzSubscription.h.
Referenced by QuartzTick().
UE_DEPRECATED() [1/3]
FQuartzTickableObject::UE_DEPRECATED (5. 5, "This should not be called directly, use the ICommandListener interface instead.") const inline
Definition at line 75 of file QuartzSubscription.h.
References OnCommandEvent().
UE_DEPRECATED() [2/3]
FQuartzTickableObject::UE_DEPRECATED (5. 5, "This should not be called directly, use the IMetronomeEventListener interface instead.") const inline
Definition at line 78 of file QuartzSubscription.h.
References OnMetronomeEvent().
UE_DEPRECATED() [3/3]
FQuartzTickableObject::UE_DEPRECATED (5. 5, "This should not be called directly, use the IQueueCommandListener interface instead.") const inline
Definition at line 81 of file QuartzSubscription.h.
References OnQueueCommandEvent().
Field Documentation
CommandQueuePtr
FQuartzGameThreadCommandQueuePtr FQuartzTickableObject::CommandQueuePtr private
Definition at line 124 of file QuartzSubscription.h.
Referenced by GetQuartzSubscriber(), Init(), QuartzIsTickable(), and QuartzTick().
MetronomeDelegates
FMetronomeDelegateGameThreadData FQuartzTickableObject::MetronomeDelegates[static_cast< int32 >(EQuartzCommandQuantization::Count)] private
Definition at line 117 of file QuartzSubscription.h.
Referenced by AddMetronomeBpDelegate(), and OnMetronomeEvent().
NotificationOffset
Audio::FQuartzOffset FQuartzTickableObject::NotificationOffset private
Definition at line 123 of file QuartzSubscription.h.
Referenced by GetQuartzOffset(), GetQuartzSubscriber(), SetNotificationAnticipationAmountMilliseconds(), and SetNotificationAnticipationAmountMusicalDuration().
QuantizedCommandDelegates
TArray<FCommandDelegateGameThreadData> FQuartzTickableObject::QuantizedCommandDelegates private
Definition at line 118 of file QuartzSubscription.h.
Referenced by AddCommandDelegate(), and OnCommandEvent().
QuartzSubscriptionToken
FQuartzSubscriptionToken FQuartzTickableObject::QuartzSubscriptionToken private
Definition at line 125 of file QuartzSubscription.h.
Referenced by Init(), IsInitialized(), OnCommandEvent(), OnMetronomeEvent(), and QuartzUnsubscribe().
TempCommandQueue
TArray<TFunction<void(FQuartzTickableObject*)> > FQuartzTickableObject::TempCommandQueue private
Definition at line 120 of file QuartzSubscription.h.
The documentation for this class was generated from the following files:
QuartzSubscription.h
QuartzSubscription.cpp