Unreal Engine 5.6 C++ API: FSHAHash Class Reference
FSHAHash Class Reference
Stores an SHA hash generated by FSHA1.
#include "SecureHash.h"
Public Member Functions
FSHAHash ()
void AppendString (FString &Out) const
void FromString (const FStringView &Src)
bool LoadFromCompactBinary (const FCbFieldView &Field)
FString ToString () const
void ToString (TCHAR *Dest, bool bNullTerminate) const
FCbWriter & WriteCompactBinary (FCbWriter &Writer) const
Static Public Member Functions
static constexpr int32 GetStringLen ()
Data Fields
uint8 Hash [20]
Friends
uint32 GetTypeHash (const FSHAHash &InKey)
void LexFromString (FSHAHash &InHash, const TCHAR *InString)
FString LexToString (const FSHAHash &InHash)
bool LoadFromCompactBinary (const FCbFieldView &Field, FSHAHash &OutHash)
bool operator!= (const FSHAHash &X, const FSHAHash &Y)
bool operator< (const FSHAHash &X, const FSHAHash &Y)
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase &Builder, const FSHAHash &InHash)
FArchive & operator<< (FArchive &Ar, FSHAHash &G)
FCbWriter & operator<< (FCbWriter &Writer, const FSHAHash &InHash)
FStringBuilderBase & operator<< (FStringBuilderBase &Builder, const FSHAHash &InHash)
bool operator== (const FSHAHash &X, const FSHAHash &Y)
Detailed Description
Stores an SHA hash generated by FSHA1.
Definition at line 225 of file SecureHash.h.
Constructor & Destructor Documentation
FSHAHash()
FSHAHash::FSHAHash () inline
Definition at line 230 of file SecureHash.h.
References Hash, and FMemory::Memset().
Referenced by GetTypeHash, LexFromString, LexToString, LoadFromCompactBinary, operator!=, operator<, operator<<, operator<<, operator<<, operator<<, and operator==.
Member Function Documentation
AppendString()
void FSHAHash::AppendString (FString & Out) const inline
Definition at line 237 of file SecureHash.h.
References BytesToHex(), and Hash.
FromString()
void FSHAHash::FromString (const FStringView & Src) inline
Definition at line 263 of file SecureHash.h.
References check, GetStringLen(), Hash, UE::String::HexToBytes(), and TStringView< CharType >::Len().
Referenced by LexFromString.
GetStringLen()
constexpr int32 FSHAHash::GetStringLen () inline static constexpr
Definition at line 235 of file SecureHash.h.
References Hash, and UE_ARRAY_COUNT.
Referenced by FromString().
LoadFromCompactBinary()
bool FSHAHash::LoadFromCompactBinary (const FCbFieldView & Field)
ToString() [1/2]
FString FSHAHash::ToString () const inline
Definition at line 242 of file SecureHash.h.
References BytesToHex(), and Hash.
Referenced by FShaderCode::GetFinalizedResource(), and LexToString.
ToString() [2/2]
void FSHAHash::ToString (TCHAR * Dest, bool bNullTerminate) const inline
Definition at line 247 of file SecureHash.h.
References Count, Hash, NibbleToTChar(), TEXT, and UE_ARRAY_COUNT.
WriteCompactBinary()
FCbWriter & FSHAHash::WriteCompactBinary (FCbWriter & Writer) const
Referenced by operator<<.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSHAHash & InKey) friend
Definition at line 290 of file SecureHash.h.
References FSHAHash(), and Hash.
LexFromString
void LexFromString (FSHAHash & InHash, const TCHAR * InString) friend
Definition at line 296 of file SecureHash.h.
References FSHAHash(), and FromString().
LexToString
FString LexToString (const FSHAHash & InHash) friend
Definition at line 295 of file SecureHash.h.
References FSHAHash(), and ToString().
LoadFromCompactBinary
bool LoadFromCompactBinary (const FCbFieldView & Field, FSHAHash & OutHash) friend
Definition at line 300 of file SecureHash.h.
References FSHAHash(), and LoadFromCompactBinary.
Referenced by LoadFromCompactBinary.
operator!=
bool operator!= (const FSHAHash & X, const FSHAHash & Y) friend
Definition at line 274 of file SecureHash.h.
References FSHAHash(), FMemory::Memcmp(), X, and Y.
operator<
bool operator< (const FSHAHash & X, const FSHAHash & Y) friend
Definition at line 279 of file SecureHash.h.
References FSHAHash(), FMemory::Memcmp(), X, and Y.
operator<< [1/4]
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase & Builder, const FSHAHash & InHash) friend
Definition at line 298 of file SecureHash.h.
References FSHAHash(), UE::String::BytesToHex(), and Hash.
operator<< [2/4]
FArchive & operator<< (FArchive & Ar, FSHAHash & G) friend
Definition at line 284 of file SecureHash.h.
References FSHAHash(), Ar, and G.
operator<< [3/4]
FCbWriter & operator<< (FCbWriter & Writer, const FSHAHash & InHash) friend
Definition at line 299 of file SecureHash.h.
References FSHAHash(), and WriteCompactBinary().
operator<< [4/4]
FStringBuilderBase & operator<< (FStringBuilderBase & Builder, const FSHAHash & InHash) friend
Definition at line 297 of file SecureHash.h.
References FSHAHash(), UE::String::BytesToHex(), and Hash.
operator==
bool operator== (const FSHAHash & X, const FSHAHash & Y) friend
Definition at line 269 of file SecureHash.h.
References FSHAHash(), FMemory::Memcmp(), X, and Y.
Field Documentation
Hash
uint8 FSHAHash::Hash[20]
Definition at line 228 of file SecureHash.h.
Referenced by FSHAHash(), AppendString(), FromString(), GetStringLen(), GetTypeHash, operator<<, operator<<, ToString(), and ToString().
The documentation for this class was generated from the following file:
SecureHash.h