Unreal Engine 5.6 C++ API: FSkinnedMeshSceneProxyDesc Struct Reference
FSkinnedMeshSceneProxyDesc Struct Reference
#include "SkinnedMeshSceneProxyDesc.h"
Public Member Functions
FSkinnedMeshSceneProxyDesc ()=default
FSkinnedMeshSceneProxyDesc (const USkinnedMeshComponent *Component)
int32 GetBoneIndex (FName BoneName) const
FVector GetComponentScale () const
const TOptional< FLinearColor > & GetDebugDrawColor () const
UMaterialInterface * GetMaterial (int32 MaterialIndex) const
FMaterialRelevance GetMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const
void GetMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotsOverlayMaterial) const
float GetMaxDistanceFactor () const
UMeshDeformerInstance * GetMeshDeformerInstance () const
UMeshDeformerInstance * GetMeshDeformerInstanceForLOD (int32 LODIndex) const
UMaterialInterface * GetOverlayMaterial () const
float GetOverlayMaterialMaxDrawDistance () const
UPhysicsAsset * GetPhysicsAsset () const
int32 GetPredictedLODLevel () const
void GetPreSkinnedLocalBounds (FBoxSphereBounds &OutBounds) const
USkinnedAsset * GetSkinnedAsset () const
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
bool HasValidNaniteData () const
void InitializeFromSkinnedMeshComponent (const USkinnedMeshComponent *)
bool IsSkinCacheAllowed (int32 LodIdx) const
void SetLODInfo (TArrayView< const FSkelMeshComponentLODInfo > InLODInfo)
bool ShouldCPUSkin () const
bool ShouldDrawDebugSkeleton () const
bool ShouldNaniteSkin () const
UE_DEPRECATED (5.5, "Use InitializeFromSkinnedMeshComponent instead.") void InitializeFrom(const USkinnedMeshComponent *InComponent)
Public Member Functions inherited from FPrimitiveSceneProxyDesc
FPrimitiveSceneProxyDesc ()
FPrimitiveSceneProxyDesc (const UPrimitiveComponent *)
virtual ~FPrimitiveSceneProxyDesc ()=default
const UObject * AdditionalStatObject () const
const FCustomPrimitiveData & GetCustomPrimitiveData () const
MESH_DRAW_COMMAND_STATS.
uint64 GetHiddenEditorViews () const
ULevel * GetLevel () const
bool GetLevelInstanceEditingState () const
FName GetMeshDrawCommandStatsCategory () const
UObject * GetOwner () const
template<class T>
T * GetOwner () const
FString GetPathName () const
IPrimitiveComponent * GetPrimitiveComponentInterface () const
FPrimitiveComponentId GetPrimitiveSceneId () const
int32 GetRayTracingGroupId () const
TArrayView< URuntimeVirtualTexture * > const & GetRuntimeVirtualTextures () const
FSceneInterface * GetScene () const
bool GetShadowIndirectOnly () const
ESceneDepthPriorityGroup GetStaticDepthPriorityGroup () const
TStatId GetStatID (bool bForDeferredUse=false) const
float GetVirtualTextureMainPassMaxDrawDistance () const
ERuntimeVirtualTextureMainPassType GetVirtualTextureRenderPassType () const
UWorld * GetWorld () const
bool HasStaticLighting () const
bool HasValidSettingsForStaticLighting () const
void InitializeFromPrimitiveComponent (const UPrimitiveComponent *)
bool IsCollisionEnabled () const
bool IsComponentIndividuallySelected () const
bool IsFirstPersonRelevant () const
bool IsHidden () const
bool IsHiddenEd () const
bool IsOwnedByFoliage () const
bool IsOwnerEditorOnly () const
bool IsPrecomputedLightingValid () const
bool IsVisible () const
bool IsVisibleEditor () const
bool ShouldRenderProxyFallbackToDefaultMaterial () const
bool ShouldRenderSelected () const
bool SupportsWorldPositionOffsetVelocity () const
UE_DEPRECATED (5.5, "Use InitializeFromPrimitiveComponent instead.") void InitializeFrom(const UPrimitiveComponent *InComponent)
UE_DEPRECATED (5.6, "Use FPrimitiveSceneProxyDesc::IsFirstPersonRelevant() instead.") bool IsStaticMeshFirstPersonRelevant() const
UE_DEPRECATED (5.6, "Use GetLevel instead.") ULevel *GetComponentLevel() const
Static Public Member Functions
static FSkeletalMeshObject * CreateMeshObject (const FSkinnedMeshSceneProxyDesc &Desc)
static FPrimitiveSceneProxy * CreateSceneProxy (const FSkinnedMeshSceneProxyDesc &Desc, bool bHideSkin, int32 MinLODIndex)
Data Fields
uint8 bCanHighlightSelectedSections: 1 = false
uint8 bCastCapsuleDirectShadow: 1 = false
uint8 bCastCapsuleIndirectShadow: 1 = false
uint8 bCPUSkinning: 1 = false
uint8 bDrawDebugSkeleton: 1 = false
uint8 bForceWireframe: 1 = false
uint8 bPerBoneMotionBlur: 1 = false
uint8 bRenderStatic: 1 = false
uint32 bSortTriangles:1 = false
float CapsuleIndirectShadowMinVisibility = 0.0f
FVector ComponentScale = FVector::OneVector
TOptional< FLinearColor > DebugDrawColor
TArrayView< const FSkelMeshComponentLODInfo > LODInfo
FMaterialRelevance MaterialRelevance {}
TArray< TObjectPtr< UMaterialInterface > > MaterialSlotsOverlayMaterial
float MaxDistanceFactor = 1.0f
const FMeshDeformerInstanceSet * MeshDeformerInstances = nullptr
FSkeletalMeshObject * MeshObject = nullptr
UMaterialInterface * OverlayMaterial = nullptr
float OverlayMaterialMaxDrawDistance = 0.0f
TArrayView< const TObjectPtr< UMaterialInterface > > OverrideMaterials
UPhysicsAsset * PhysicsAsset = nullptr
int32 PredictedLODLevel = 0
FSkeletalMeshObject * PreviousMeshObject = nullptr
TArrayView< const ESkinCacheUsage > SkinCacheUsage {}
USkinnedAsset * SkinnedAsset = nullptr
float StreamingDistanceMultiplier = 1.0f
Data Fields inherited from FPrimitiveSceneProxyDesc
TArray< uint32 > ActorOwners
const UObject * AdditionalStatObjectPtr = nullptr
uint32 bAffectDistanceFieldLighting: 1
uint32 bAffectDynamicIndirectLighting: 1
uint32 bAffectIndirectLightingWhileHidden: 1
uint32 bCastCinematicShadow: 1
uint32 bCastContactShadow: 1
uint32 bCastDynamicShadow: 1
uint32 bCastFarShadow: 1
uint32 bCastHiddenShadow: 1
uint32 bCastInsetShadow: 1
uint32 bCastShadowAsTwoSided: 1
uint32 bCastStaticShadow: 1
uint32 bCastVolumetricTranslucentShadow: 1
uint32 bCollisionEnabled: 1
uint32 bEmissiveLightSource: 1
uint32 bForceMipStreaming: 1
uint32 bHasPerInstanceHitProxies: 1
uint32 bHasStaticLighting: 1
uint32 bHasValidSettingsForStaticLighting: 1
uint32 bHiddenInSceneCapture: 1
uint32 bHoldout: 1
uint32 bIndividuallySelected: 1
uint32 bIsBeingMovedByEditor: 1
uint32 bIsFirstPerson: 1
uint32 bIsFirstPersonWorldSpaceRepresentation: 1
uint32 bIsHidden: 1
uint32 bIsHiddenEd: 1
uint32 bIsInstancedStaticMesh: 1
uint32 bIsOwnedByFoliage:1
uint32 bIsOwnerEditorOnly: 1
uint32 bIsPrecomputedLightingValid: 1
uint32 bIsVisible: 1
uint32 bIsVisibleEditor: 1
uint32 bLevelInstanceEditingState: 1
uint32 bLightAttachmentsAsGroup: 1
uint32 bOnlyOwnerSee: 1
float BoundsScale = 1.0f
uint32 bOwnerNoSee: 1
uint32 bRayTracingFarField: 1
uint32 bReceiveMobileCSMShadows: 1
uint32 bReceivesDecals: 1
uint32 bRenderCustomDepth: 1
uint32 bRenderInDepthPass: 1
uint32 bRenderInMainPass: 1
uint32 bSelectable: 1
uint32 bSelected: 1
uint32 bSelfShadowOnly: 1
uint32 bShadowIndirectOnly: 1
uint32 bShouldRenderProxyFallbackToDefaultMaterial:1
uint32 bShouldRenderSelected: 1
uint32 bSingleSampleShadowFromStationaryLights: 1
uint32 bSupportsWorldPositionOffsetVelocity: 1
uint32 bTreatAsBackgroundForOcclusion: 1
uint32 bUseAsOccluder: 1
uint32 bUseEditorCompositing: 1
uint32 bUseViewOwnerDepthPriorityGroup: 1
uint32 bVisibleInRayTracing: 1
uint32 bVisibleInRealTimeSkyCaptures: 1
uint32 bVisibleInReflectionCaptures: 1
uint32 bVisibleInSceneCaptureOnly: 1
uint32 bWantsEditorEffects: 1
float CachedMaxDrawDistance = 0.0f
uint32 CastShadow: 1
UObject * Component = nullptr
FPrimitiveComponentId ComponentId
int32 CustomDepthStencilValue = 0
ERendererStencilMask CustomDepthStencilWriteMask = ERendererStencilMask::ERSM_Default
const FCustomPrimitiveData * CustomPrimitiveData = nullptr
TEnumAsByte< enum ESceneDepthPriorityGroup > DepthPriorityGroup = ESceneDepthPriorityGroup::SDPG_World
ERHIFeatureLevel::Type FeatureLevel
uint64 HiddenEditorViews = 0
TEnumAsByte< EIndirectLightingCacheQuality > IndirectLightingCacheQuality = EIndirectLightingCacheQuality::ILCQ_Point
FLightingChannels LightingChannels
ELightmapType LightmapType = ELightmapType::Default
FName MeshDrawCommandStatsCategory
float MinDrawDistance = 0.0f
TEnumAsByte< EComponentMobility::Type > Mobility = EComponentMobility::Movable
FColor OverlayColor = FColor(EForceInit::ForceInitToZero)
UObject * Owner = nullptr
IPrimitiveComponent * PrimitiveComponentInterface = nullptr
ERayTracingGroupCullingPriority RayTracingGroupCullingPriority = ERayTracingGroupCullingPriority::CP_4_DEFAULT
int32 RayTracingGroupId = FPrimitiveSceneProxy::InvalidRayTracingGroupId
TArrayView< URuntimeVirtualTexture * > RuntimeVirtualTextures
FSceneInterface * Scene = nullptr
EShadowCacheInvalidationBehavior ShadowCacheInvalidationBehavior = EShadowCacheInvalidationBehavior::Auto
TStatId StatId
float TranslucencySortDistanceOffset = 0.0f
int32 TranslucencySortPriority = 0
TEnumAsByte< enum ESceneDepthPriorityGroup > ViewOwnerDepthPriorityGroup = ESceneDepthPriorityGroup::SDPG_World
int32 VirtualTextureCullMips = 0
int8 VirtualTextureLodBias = 0
float VirtualTextureMainPassMaxDrawDistance = 0.0f
int8 VirtualTextureMinCoverage = 0
ERuntimeVirtualTextureMainPassType VirtualTextureRenderPassType = ERuntimeVirtualTextureMainPassType::Exclusive
int32 VisibilityId = 0
UWorld * World = nullptr
Detailed Description
Definition at line 20 of file SkinnedMeshSceneProxyDesc.h.
Constructor & Destructor Documentation
FSkinnedMeshSceneProxyDesc() [1/2]
FSkinnedMeshSceneProxyDesc::FSkinnedMeshSceneProxyDesc () default
Referenced by CreateMeshObject(), and CreateSceneProxy().
FSkinnedMeshSceneProxyDesc() [2/2]
FSkinnedMeshSceneProxyDesc::FSkinnedMeshSceneProxyDesc (const USkinnedMeshComponent * Component)
References FPrimitiveSceneProxyDesc::Component.
Member Function Documentation
CreateMeshObject()
FSkeletalMeshObject * FSkinnedMeshSceneProxyDesc::CreateMeshObject (const FSkinnedMeshSceneProxyDesc & Desc) static
References FSkinnedMeshSceneProxyDesc().
CreateSceneProxy()
FPrimitiveSceneProxy * FSkinnedMeshSceneProxyDesc::CreateSceneProxy (const FSkinnedMeshSceneProxyDesc & Desc, bool bHideSkin, int32 MinLODIndex) static
References FSkinnedMeshSceneProxyDesc().
GetBoneIndex()
int32 FSkinnedMeshSceneProxyDesc::GetBoneIndex (FName BoneName) const
GetComponentScale()
FVector FSkinnedMeshSceneProxyDesc::GetComponentScale () const inline
Definition at line 43 of file SkinnedMeshSceneProxyDesc.h.
References ComponentScale, and FVector.
GetDebugDrawColor()
const TOptional< FLinearColor > & FSkinnedMeshSceneProxyDesc::GetDebugDrawColor () const
GetMaterial()
UMaterialInterface * FSkinnedMeshSceneProxyDesc::GetMaterial (int32 MaterialIndex) const
GetMaterialRelevance()
FMaterialRelevance FSkinnedMeshSceneProxyDesc::GetMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const
GetMaterialSlotsOverlayMaterial()
void FSkinnedMeshSceneProxyDesc::GetMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > & OutMaterialSlotsOverlayMaterial) const inline
Definition at line 39 of file SkinnedMeshSceneProxyDesc.h.
References MaterialSlotsOverlayMaterial.
GetMaxDistanceFactor()
float FSkinnedMeshSceneProxyDesc::GetMaxDistanceFactor () const inline
Definition at line 45 of file SkinnedMeshSceneProxyDesc.h.
References MaxDistanceFactor.
GetMeshDeformerInstance()
UMeshDeformerInstance * FSkinnedMeshSceneProxyDesc::GetMeshDeformerInstance () const
GetMeshDeformerInstanceForLOD()
UMeshDeformerInstance * FSkinnedMeshSceneProxyDesc::GetMeshDeformerInstanceForLOD (int32 LODIndex) const
GetOverlayMaterial()
UMaterialInterface * FSkinnedMeshSceneProxyDesc::GetOverlayMaterial () const
GetOverlayMaterialMaxDrawDistance()
float FSkinnedMeshSceneProxyDesc::GetOverlayMaterialMaxDrawDistance () const
GetPhysicsAsset()
UPhysicsAsset * FSkinnedMeshSceneProxyDesc::GetPhysicsAsset () const
GetPredictedLODLevel()
int32 FSkinnedMeshSceneProxyDesc::GetPredictedLODLevel () const inline
Definition at line 44 of file SkinnedMeshSceneProxyDesc.h.
References PredictedLODLevel.
GetPreSkinnedLocalBounds()
void FSkinnedMeshSceneProxyDesc::GetPreSkinnedLocalBounds (FBoxSphereBounds & OutBounds) const
GetSkinnedAsset()
USkinnedAsset * FSkinnedMeshSceneProxyDesc::GetSkinnedAsset () const
GetUsedMaterials()
virtual void FSkinnedMeshSceneProxyDesc::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override virtual
Reimplemented from FPrimitiveSceneProxyDesc.
HasValidNaniteData()
bool FSkinnedMeshSceneProxyDesc::HasValidNaniteData () const
InitializeFromSkinnedMeshComponent()
void FSkinnedMeshSceneProxyDesc::InitializeFromSkinnedMeshComponent (const USkinnedMeshComponent *)
Referenced by UE_DEPRECATED().
IsSkinCacheAllowed()
bool FSkinnedMeshSceneProxyDesc::IsSkinCacheAllowed (int32 LodIdx) const
SetLODInfo()
void FSkinnedMeshSceneProxyDesc::SetLODInfo (TArrayView< const FSkelMeshComponentLODInfo > InLODInfo) inline
Definition at line 47 of file SkinnedMeshSceneProxyDesc.h.
References LODInfo.
ShouldCPUSkin()
bool FSkinnedMeshSceneProxyDesc::ShouldCPUSkin () const inline
Definition at line 49 of file SkinnedMeshSceneProxyDesc.h.
References bCPUSkinning.
ShouldDrawDebugSkeleton()
bool FSkinnedMeshSceneProxyDesc::ShouldDrawDebugSkeleton () const
ShouldNaniteSkin()
bool FSkinnedMeshSceneProxyDesc::ShouldNaniteSkin () const
UE_DEPRECATED()
FSkinnedMeshSceneProxyDesc::UE_DEPRECATED (5. 5, "Use InitializeFromSkinnedMeshComponent instead.") const inline
Definition at line 57 of file SkinnedMeshSceneProxyDesc.h.
References InitializeFromSkinnedMeshComponent().
Field Documentation
bCanHighlightSelectedSections
uint8 FSkinnedMeshSceneProxyDesc::bCanHighlightSelectedSections
Definition at line 84 of file SkinnedMeshSceneProxyDesc.h.
bCastCapsuleDirectShadow
uint8 FSkinnedMeshSceneProxyDesc::bCastCapsuleDirectShadow
Definition at line 87 of file SkinnedMeshSceneProxyDesc.h.
bCastCapsuleIndirectShadow
uint8 FSkinnedMeshSceneProxyDesc::bCastCapsuleIndirectShadow
Definition at line 88 of file SkinnedMeshSceneProxyDesc.h.
bCPUSkinning
uint8 FSkinnedMeshSceneProxyDesc::bCPUSkinning
Definition at line 90 of file SkinnedMeshSceneProxyDesc.h.
Referenced by ShouldCPUSkin().
bDrawDebugSkeleton
uint8 FSkinnedMeshSceneProxyDesc::bDrawDebugSkeleton
Definition at line 89 of file SkinnedMeshSceneProxyDesc.h.
bForceWireframe
uint8 FSkinnedMeshSceneProxyDesc::bForceWireframe
Definition at line 83 of file SkinnedMeshSceneProxyDesc.h.
bPerBoneMotionBlur
uint8 FSkinnedMeshSceneProxyDesc::bPerBoneMotionBlur
Definition at line 86 of file SkinnedMeshSceneProxyDesc.h.
bRenderStatic
uint8 FSkinnedMeshSceneProxyDesc::bRenderStatic
Definition at line 85 of file SkinnedMeshSceneProxyDesc.h.
bSortTriangles
uint32 FSkinnedMeshSceneProxyDesc::bSortTriangles
Definition at line 94 of file SkinnedMeshSceneProxyDesc.h.
CapsuleIndirectShadowMinVisibility
float FSkinnedMeshSceneProxyDesc::CapsuleIndirectShadowMinVisibility = 0.0f
Definition at line 80 of file SkinnedMeshSceneProxyDesc.h.
ComponentScale
FVector FSkinnedMeshSceneProxyDesc::ComponentScale = FVector::OneVector
Definition at line 78 of file SkinnedMeshSceneProxyDesc.h.
Referenced by GetComponentScale().
DebugDrawColor
TOptional<FLinearColor> FSkinnedMeshSceneProxyDesc::DebugDrawColor
Definition at line 60 of file SkinnedMeshSceneProxyDesc.h.
LODInfo
TArrayView<const FSkelMeshComponentLODInfo> FSkinnedMeshSceneProxyDesc::LODInfo
Definition at line 62 of file SkinnedMeshSceneProxyDesc.h.
Referenced by SetLODInfo().
MaterialRelevance
FMaterialRelevance FSkinnedMeshSceneProxyDesc::MaterialRelevance {}
Definition at line 61 of file SkinnedMeshSceneProxyDesc.h.
MaterialSlotsOverlayMaterial
TArray<TObjectPtr<UMaterialInterface> > FSkinnedMeshSceneProxyDesc::MaterialSlotsOverlayMaterial
Definition at line 70 of file SkinnedMeshSceneProxyDesc.h.
Referenced by GetMaterialSlotsOverlayMaterial().
MaxDistanceFactor
float FSkinnedMeshSceneProxyDesc::MaxDistanceFactor = 1.0f
Definition at line 75 of file SkinnedMeshSceneProxyDesc.h.
Referenced by GetMaxDistanceFactor().
MeshDeformerInstances
const FMeshDeformerInstanceSet* FSkinnedMeshSceneProxyDesc::MeshDeformerInstances = nullptr
Definition at line 71 of file SkinnedMeshSceneProxyDesc.h.
MeshObject
FSkeletalMeshObject* FSkinnedMeshSceneProxyDesc::MeshObject = nullptr
Definition at line 64 of file SkinnedMeshSceneProxyDesc.h.
OverlayMaterial
UMaterialInterface* FSkinnedMeshSceneProxyDesc::OverlayMaterial = nullptr
Definition at line 69 of file SkinnedMeshSceneProxyDesc.h.
OverlayMaterialMaxDrawDistance
float FSkinnedMeshSceneProxyDesc::OverlayMaterialMaxDrawDistance = 0.0f
Definition at line 81 of file SkinnedMeshSceneProxyDesc.h.
OverrideMaterials
TArrayView<const TObjectPtr<UMaterialInterface> > FSkinnedMeshSceneProxyDesc::OverrideMaterials
Definition at line 72 of file SkinnedMeshSceneProxyDesc.h.
PhysicsAsset
UPhysicsAsset* FSkinnedMeshSceneProxyDesc::PhysicsAsset = nullptr
Definition at line 68 of file SkinnedMeshSceneProxyDesc.h.
PredictedLODLevel
int32 FSkinnedMeshSceneProxyDesc::PredictedLODLevel = 0
Definition at line 74 of file SkinnedMeshSceneProxyDesc.h.
Referenced by GetPredictedLODLevel().
PreviousMeshObject
FSkeletalMeshObject* FSkinnedMeshSceneProxyDesc::PreviousMeshObject = nullptr
Definition at line 65 of file SkinnedMeshSceneProxyDesc.h.
SkinCacheUsage
TArrayView<const ESkinCacheUsage> FSkinnedMeshSceneProxyDesc::SkinCacheUsage {}
Definition at line 73 of file SkinnedMeshSceneProxyDesc.h.
SkinnedAsset
USkinnedAsset* FSkinnedMeshSceneProxyDesc::SkinnedAsset = nullptr
Definition at line 67 of file SkinnedMeshSceneProxyDesc.h.
StreamingDistanceMultiplier
float FSkinnedMeshSceneProxyDesc::StreamingDistanceMultiplier = 1.0f
Definition at line 79 of file SkinnedMeshSceneProxyDesc.h.
The documentation for this struct was generated from the following file:
SkinnedMeshSceneProxyDesc.h