Unreal Engine 5.6 C++ API: TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType > Class Template Reference
TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType > Class Template Reference
Allocator that will grow as needed with direct mapped memory for a given memory type.
#include "GenericGrowableAllocator.h"
Data Structures
struct AllocationInfo
struct AllocFreeCounts
Public Member Functions
TGenericGrowableAllocator (uint64 InitialSize, uint32 InType, uint32 InSubAllocationAlignment, FName InStatRegionName, const FName *InOwnerTypeToStatIdMap, void *InUserData)
Constructor Internally allocates address space for use only by this allocator.
virtual ~TGenericGrowableAllocator ()
Destructor.
bool DoesAllocatorContainAddress (const void *Address)
void DumpMemoryInfo ()
bool Free (GrowableAllocationBaseType *Memory)
void GetAllocationInfo (uint32 &Chunks, uint64 &Used, uint64 &Free)
GrowableAllocationBaseType * Malloc (uint32 Size, uint32 Alignment, int32 OwnerType)
void ShowAllocationInfo ()
void ShowFullAllocationInfo ()
Public Member Functions inherited from FGrowableMallocBase
FGrowableMallocBase ()
Constructor.
virtual ~FGrowableMallocBase ()
virtual uint64 GetWasteApproximation ()
Returns approximated amount of memory wasted due to allocations' alignment.
Private Member Functions
ChunkAllocatorType * CreateAllocChunk (uint64 Size)
Create a new allocation chunk to fit the requested size.
void OutOfMemory (uint32 Size)
triggered during out of memory failure for this allocator
void RemoveAllocChunk (ChunkAllocatorType *Chunk)
Removes an existing allocated chunk.
void UpdateMemoryStatMaxSizes ()
Updates the memory stat max sizes when chunks are added/removed.
Private Attributes
TArray< ChunkAllocatorType * > AllocChunks
list of currently allocated chunks
FCriticalSection CriticalSection
uint64 CurSizeAllocated
total currently allocated from OS
uint32 MemoryType
The type of memory this allocator allocates from the kernel.
uint64 NumAllocations
TMap< uint64, uint32 > OutstandingAllocationsHistogram
const FName * OwnerTypeToStatIdMap
For stats/dumping, we use this to convert OwnerType of an allocation to a printable name.
TMap< uint64, uint32 > PeakAllocationsHistogram
TMap< int32, AllocationInfo > PerTypeAllocationInfo
FName StatRegionName
The stat memory region to update max size.
const uint32 SubAllocationAlignment
TMap< uint64, uint32 > TotalAllocationsHistogram
uint64 TotalAllocationSize
Just stat tracking.
void * UserData
Additional Inherited Members
Protected Attributes inherited from FGrowableMallocBase
uint64 CurrentAllocs
The current number of allocations.
uint64 TotalAllocated
Total amount ever allocated.
uint64 TotalAllocs
The total number of allocations.
uint64 TotalWaste
The total amount of memory wasted due to allocations' alignment.
Detailed Description
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType>
class TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >
Allocator that will grow as needed with direct mapped memory for a given memory type.
Definition at line 512 of file GenericGrowableAllocator.h.
Constructor & Destructor Documentation
TGenericGrowableAllocator()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::TGenericGrowableAllocator (uint64 InitialSize, uint32 InType, uint32 InSubAllocationAlignment, FName InStatRegionName, const FName * InOwnerTypeToStatIdMap, void * InUserData) inline
Constructor Internally allocates address space for use only by this allocator.
Parameters
Type - The templated memory type to allocate with this allocator
StatRegion - The region of memory this is responsible for, for updating the region max sizes
Definition at line 523 of file GenericGrowableAllocator.h.
References CreateAllocChunk(), MemoryType, OwnerTypeToStatIdMap, StatRegionName, SubAllocationAlignment, and UserData.
~TGenericGrowableAllocator()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> virtual TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::~TGenericGrowableAllocator () inline virtual
Destructor.
Definition at line 541 of file GenericGrowableAllocator.h.
References AllocChunks, DumpMemoryInfo(), FGenericPlatformMisc::LowLevelOutputDebugStringf(), RemoveAllocChunk(), and TEXT.
Member Function Documentation
CreateAllocChunk()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> ChunkAllocatorType * TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::CreateAllocChunk (uint64 Size) inline private
Create a new allocation chunk to fit the requested size.
All chunks are aligned to MIN_CHUNK_ALIGNMENT
Parameters
Size - size of chunk
Definition at line 804 of file GenericGrowableAllocator.h.
References AllocChunks, CriticalSection, INC_MEMORY_STAT_BY_FName, INDEX_NONE, MemoryType, StatRegionName, TSequenceHistory< HistorySize >::Size, UpdateMemoryStatMaxSizes(), and UserData.
Referenced by TGenericGrowableAllocator(), and Malloc().
DoesAllocatorContainAddress()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> bool TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::DoesAllocatorContainAddress (const void * Address) inline
Definition at line 716 of file GenericGrowableAllocator.h.
References AllocChunks, and CriticalSection.
DumpMemoryInfo()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::DumpMemoryInfo () inline
Definition at line 766 of file GenericGrowableAllocator.h.
References Info, FGenericPlatformMisc::LowLevelOutputDebugStringf(), OwnerTypeToStatIdMap, PerTypeAllocationInfo, and TEXT.
Referenced by ~TGenericGrowableAllocator().
Free()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> bool TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::Free (GrowableAllocationBaseType * Memory) inline
Definition at line 637 of file GenericGrowableAllocator.h.
References AllocChunks, TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::AllocationInfo::Counts, CriticalSection, FGrowableMallocBase::CurrentAllocs, DEC_MEMORY_STAT_BY_FName, Fatal, TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::AllocFreeCounts::Frees, LogCore, Memory, OwnerTypeToStatIdMap, PeakAllocationsHistogram, PerTypeAllocationInfo, RemoveAllocChunk(), TEXT, TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::AllocationInfo::TotalAllocated, and UE_LOG.
Referenced by GetAllocationInfo().
GetAllocationInfo()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::GetAllocationInfo (uint32 & Chunks, uint64 & Used, uint64 & Free) inline
Definition at line 694 of file GenericGrowableAllocator.h.
References AllocChunks, CriticalSection, and Free().
Malloc()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> GrowableAllocationBaseType * TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::Malloc (uint32 Size, uint32 Alignment, int32 OwnerType) inline
Definition at line 563 of file GenericGrowableAllocator.h.
References Align, TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::AllocFreeCounts::Allocations, AllocChunks, TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::AllocationInfo::Counts, CreateAllocChunk(), CriticalSection, FGrowableMallocBase::CurrentAllocs, INC_MEMORY_STAT_BY_FName, OutOfMemory, OwnerTypeToStatIdMap, PeakAllocationsHistogram, PerTypeAllocationInfo, SubAllocationAlignment, FGrowableMallocBase::TotalAllocated, TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::AllocationInfo::TotalAllocated, TotalAllocationsHistogram, FGrowableMallocBase::TotalAllocs, FGrowableMallocBase::TotalWaste, and TSequenceHistory< HistorySize >::Size.
OutOfMemory()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::OutOfMemory (uint32 Size) inline private
triggered during out of memory failure for this allocator
Definition at line 855 of file GenericGrowableAllocator.h.
References Fatal, LogCore, FGenericPlatformMisc::LowLevelOutputDebugStringf(), TEXT, TSequenceHistory< HistorySize >::Size, and UE_LOG.
RemoveAllocChunk()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::RemoveAllocChunk (ChunkAllocatorType * Chunk) inline private
Removes an existing allocated chunk.
Unmaps its memory, decommits physical memory back to OS, flushes address entries associated with it, and deletes it
Parameters
Chunk - existing chunk to remove
Definition at line 835 of file GenericGrowableAllocator.h.
References AllocChunks, check, checkSlow, DEC_MEMORY_STAT_BY_FName, StatRegionName, and UpdateMemoryStatMaxSizes().
Referenced by ~TGenericGrowableAllocator(), and Free().
ShowAllocationInfo()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::ShowAllocationInfo () inline
Definition at line 733 of file GenericGrowableAllocator.h.
References AllocChunks, FGenericPlatformMisc::LowLevelOutputDebugStringf(), TEXT, FGrowableMallocBase::TotalAllocated, FGrowableMallocBase::TotalAllocs, and FGrowableMallocBase::TotalWaste.
ShowFullAllocationInfo()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::ShowFullAllocationInfo () inline
Definition at line 740 of file GenericGrowableAllocator.h.
References AllocChunks, CriticalSection, FGenericPlatformMisc::LowLevelOutputDebugStringf(), TEXT, and TotalAllocationsHistogram.
UpdateMemoryStatMaxSizes()
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::UpdateMemoryStatMaxSizes () inline private
Updates the memory stat max sizes when chunks are added/removed.
Definition at line 795 of file GenericGrowableAllocator.h.
Referenced by CreateAllocChunk(), and RemoveAllocChunk().
Field Documentation
AllocChunks
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> TArray<ChunkAllocatorType*> TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::AllocChunks private
list of currently allocated chunks
Definition at line 883 of file GenericGrowableAllocator.h.
Referenced by ~TGenericGrowableAllocator(), CreateAllocChunk(), DoesAllocatorContainAddress(), Free(), GetAllocationInfo(), Malloc(), RemoveAllocChunk(), ShowAllocationInfo(), and ShowFullAllocationInfo().
CriticalSection
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> FCriticalSection TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::CriticalSection private
Definition at line 889 of file GenericGrowableAllocator.h.
Referenced by CreateAllocChunk(), DoesAllocatorContainAddress(), Free(), GetAllocationInfo(), Malloc(), and ShowFullAllocationInfo().
CurSizeAllocated
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> uint64 TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::CurSizeAllocated private
total currently allocated from OS
Definition at line 867 of file GenericGrowableAllocator.h.
MemoryType
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> uint32 TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::MemoryType private
The type of memory this allocator allocates from the kernel.
Definition at line 874 of file GenericGrowableAllocator.h.
Referenced by TGenericGrowableAllocator(), and CreateAllocChunk().
NumAllocations
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> uint64 TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::NumAllocations private
Definition at line 871 of file GenericGrowableAllocator.h.
OutstandingAllocationsHistogram
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> TMap<uint64, uint32> TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::OutstandingAllocationsHistogram private
Definition at line 909 of file GenericGrowableAllocator.h.
OwnerTypeToStatIdMap
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> const FName* TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::OwnerTypeToStatIdMap private
For stats/dumping, we use this to convert OwnerType of an allocation to a printable name.
Definition at line 880 of file GenericGrowableAllocator.h.
Referenced by TGenericGrowableAllocator(), DumpMemoryInfo(), Free(), and Malloc().
PeakAllocationsHistogram
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> TMap<uint64, uint32> TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::PeakAllocationsHistogram private
Definition at line 910 of file GenericGrowableAllocator.h.
Referenced by Free(), and Malloc().
PerTypeAllocationInfo
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> TMap<int32, AllocationInfo> TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::PerTypeAllocationInfo private
Definition at line 906 of file GenericGrowableAllocator.h.
Referenced by DumpMemoryInfo(), Free(), and Malloc().
StatRegionName
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> FName TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::StatRegionName private
The stat memory region to update max size.
Definition at line 877 of file GenericGrowableAllocator.h.
Referenced by TGenericGrowableAllocator(), CreateAllocChunk(), and RemoveAllocChunk().
SubAllocationAlignment
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> const uint32 TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::SubAllocationAlignment private
Definition at line 864 of file GenericGrowableAllocator.h.
Referenced by TGenericGrowableAllocator(), and Malloc().
TotalAllocationsHistogram
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> TMap<uint64, uint32> TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::TotalAllocationsHistogram private
Definition at line 908 of file GenericGrowableAllocator.h.
Referenced by Malloc(), and ShowFullAllocationInfo().
TotalAllocationSize
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> uint64 TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::TotalAllocationSize private
Just stat tracking.
Definition at line 870 of file GenericGrowableAllocator.h.
UserData
template<typename ChunkAllocatorType, typename GrowableAllocationBaseType> void* TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::UserData private
Definition at line 886 of file GenericGrowableAllocator.h.
Referenced by TGenericGrowableAllocator(), and CreateAllocChunk().
The documentation for this class was generated from the following file:
GenericGrowableAllocator.h