Unreal Engine 5.6 C++ API: UE::Geometry::FAxisAlignedBox3i Struct Reference
UE::Geometry::FAxisAlignedBox3i Struct Reference
#include "IntBoxTypes.h"
Public Member Functions
FAxisAlignedBox3i ()
FAxisAlignedBox3i (const FVector3i &Min, const FVector3i &Max)
void Contain (const FVector3i &V)
bool Contains (const FVector3i &V) const
int32 Depth () const
FVector3i Diagonal () const
FVector3i GetCorner (int Index) const
int32 Height () const
bool operator!= (const FAxisAlignedBox3i &Other) const
bool operator== (const FAxisAlignedBox3i &Other) const
int32 Volume () const
int32 Width () const
Static Public Member Functions
static FAxisAlignedBox3i Empty ()
static FAxisAlignedBox3i Infinite ()
Data Fields
FVector3i Max
FVector3i Min
Detailed Description
Definition at line 183 of file IntBoxTypes.h.
Constructor & Destructor Documentation
FAxisAlignedBox3i() [1/2]
UE::Geometry::FAxisAlignedBox3i::FAxisAlignedBox3i () inline
Definition at line 188 of file IntBoxTypes.h.
References FAxisAlignedBox3i(), and Empty().
Referenced by FAxisAlignedBox3i(), Empty(), Infinite(), operator!=(), and operator==().
FAxisAlignedBox3i() [2/2]
UE::Geometry::FAxisAlignedBox3i::FAxisAlignedBox3i (const FVector3i & Min, const FVector3i & Max) inline
Definition at line 193 of file IntBoxTypes.h.
References Max, and Min.
Member Function Documentation
Contain()
void UE::Geometry::FAxisAlignedBox3i::Contain (const FVector3i & V) inline
Definition at line 238 of file IntBoxTypes.h.
References Max, Min, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Contains()
bool UE::Geometry::FAxisAlignedBox3i::Contains (const FVector3i & V) const inline
Definition at line 233 of file IntBoxTypes.h.
References Max, Min, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid().
Depth()
int32 UE::Geometry::FAxisAlignedBox3i::Depth () const inline
Definition at line 218 of file IntBoxTypes.h.
References TMathUtil< RealType >::Max(), Max, and Min.
Referenced by Volume().
Diagonal()
FVector3i UE::Geometry::FAxisAlignedBox3i::Diagonal () const inline
Definition at line 228 of file IntBoxTypes.h.
References Max, and Min.
Empty()
FAxisAlignedBox3i UE::Geometry::FAxisAlignedBox3i::Empty () inline static
Definition at line 279 of file IntBoxTypes.h.
References FAxisAlignedBox3i().
Referenced by FAxisAlignedBox3i(), and UE::Geometry::TSparseGrid3< ElemType >::TSparseGrid3().
GetCorner()
FVector3i UE::Geometry::FAxisAlignedBox3i::GetCorner (int Index) const inline
Parameters
Index corner index in range 0-7
Returns
Corner point on the box identified by the given index. See diagram in OrientedBoxTypes.h for index/corner mapping.
Definition at line 270 of file IntBoxTypes.h.
References check, Max, Min, X, Y, and Z.
Height()
int32 UE::Geometry::FAxisAlignedBox3i::Height () const inline
Definition at line 213 of file IntBoxTypes.h.
References TMathUtil< RealType >::Max(), Max, and Min.
Referenced by Volume().
Infinite()
FAxisAlignedBox3i UE::Geometry::FAxisAlignedBox3i::Infinite () inline static
Definition at line 286 of file IntBoxTypes.h.
References FAxisAlignedBox3i().
operator!=()
bool UE::Geometry::FAxisAlignedBox3i::operator!= (const FAxisAlignedBox3i & Other) const inline
Definition at line 203 of file IntBoxTypes.h.
References FAxisAlignedBox3i(), Max, Min, and Other.
operator==()
bool UE::Geometry::FAxisAlignedBox3i::operator== (const FAxisAlignedBox3i & Other) const inline
Definition at line 199 of file IntBoxTypes.h.
References FAxisAlignedBox3i(), Max, Min, and Other.
Volume()
int32 UE::Geometry::FAxisAlignedBox3i::Volume () const inline
Definition at line 223 of file IntBoxTypes.h.
References Depth(), Height(), and Width().
Width()
int32 UE::Geometry::FAxisAlignedBox3i::Width () const inline
Definition at line 208 of file IntBoxTypes.h.
References TMathUtil< RealType >::Max(), Max, and Min.
Referenced by Volume().
Field Documentation
Max
FVector3i UE::Geometry::FAxisAlignedBox3i::Max
Definition at line 186 of file IntBoxTypes.h.
Referenced by FAxisAlignedBox3i(), Contain(), Contains(), Depth(), Diagonal(), GetCorner(), Height(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), operator!=(), operator==(), and Width().
Min
FVector3i UE::Geometry::FAxisAlignedBox3i::Min
Definition at line 185 of file IntBoxTypes.h.
Referenced by FAxisAlignedBox3i(), Contain(), Contains(), Depth(), Diagonal(), GetCorner(), Height(), operator!=(), operator==(), and Width().
The documentation for this struct was generated from the following file:
IntBoxTypes.h