Unreal Engine 5.6 C++ API: UE::Insights::FFilter Class Reference
UE::Insights::FFilter Class Reference
#include "Filters.h"
Public Member Functions
FFilter (int32 InKey, FText InName, FText InDesc, EFilterDataType InDataType, TSharedPtr< IFilterValueConverter > InConverter, SupportedOperatorsArrayPtr InSupportedOperators)
virtual ~FFilter ()
template<typename Type>
Type & As ()
template<typename Type>
const Type & As () const
virtual TSharedRef< FFilterState > BuildFilterState ()
virtual TSharedRef< FFilterState > BuildFilterState (const FFilterState &Other)
const TSharedPtr< IFilterValueConverter > & GetConverter () const
EFilterDataType GetDataType () const
const FText & GetDesc () const
int32 GetKey () const
const FText & GetName () const
SupportedOperatorsArrayConstPtr GetSupportedOperators () const
virtual const FName & GetTypeName () const
template<typename Type>
bool Is () const
virtual bool IsKindOf (const FName &InTypeName) const
Public Member Functions inherited from TSharedFromThis< FFilter >
TSharedRef< FFilter, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FFilter, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static const FName & GetStaticTypeName ()
Protected Attributes
TSharedPtr< IFilterValueConverter > Converter
EFilterDataType DataType
FText Desc
int32 Key
FText Name
SupportedOperatorsArrayPtr SupportedOperators
Static Private Attributes
static const FName TypeName
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FFilter >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FFilter >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 234 of file Filters.h.
Constructor & Destructor Documentation
FFilter()
UE::Insights::FFilter::FFilter (int32 InKey, FText InName, FText InDesc, EFilterDataType InDataType, TSharedPtr< IFilterValueConverter > InConverter, SupportedOperatorsArrayPtr InSupportedOperators) inline
Definition at line 239 of file Filters.h.
References Converter, DataType, Desc, InName, Key, Name, and SupportedOperators.
Referenced by UE::Insights::FFilterWithSuggestions::FFilterWithSuggestions(), As(), and UE::Insights::FFilterWithSuggestions::GetStaticTypeName().
~FFilter()
virtual UE::Insights::FFilter::~FFilter () inline virtual
Definition at line 249 of file Filters.h.
Member Function Documentation
As() [1/2]
template<typename Type> Type & UE::Insights::FFilter::As () inline
Definition at line 236 of file Filters.h.
As() [2/2]
template<typename Type> const Type & UE::Insights::FFilter::As () const inline
Definition at line 236 of file Filters.h.
References FFilter().
BuildFilterState() [1/2]
virtual TSharedRef< FFilterState > UE::Insights::FFilter::BuildFilterState () inline virtual
Definition at line 260 of file Filters.h.
References MakeShared(), and TSharedFromThis< FFilter >::SharedThis().
BuildFilterState() [2/2]
virtual TSharedRef< FFilterState > UE::Insights::FFilter::BuildFilterState (const FFilterState & Other) inline virtual
Definition at line 261 of file Filters.h.
References MakeShared(), and Other.
GetConverter()
const TSharedPtr< IFilterValueConverter > & UE::Insights::FFilter::GetConverter () const inline
Definition at line 257 of file Filters.h.
References Converter.
GetDataType()
EFilterDataType UE::Insights::FFilter::GetDataType () const inline
Definition at line 256 of file Filters.h.
References DataType.
GetDesc()
const FText & UE::Insights::FFilter::GetDesc () const inline
Definition at line 255 of file Filters.h.
References Desc.
GetKey()
int32 UE::Insights::FFilter::GetKey () const inline
Definition at line 253 of file Filters.h.
References Key.
GetName()
const FText & UE::Insights::FFilter::GetName () const inline
Definition at line 254 of file Filters.h.
References Name.
GetStaticTypeName()
const FName & UE::Insights::FFilter::GetStaticTypeName () inline static
Definition at line 236 of file Filters.h.
GetSupportedOperators()
SupportedOperatorsArrayConstPtr UE::Insights::FFilter::GetSupportedOperators () const inline
Definition at line 258 of file Filters.h.
References SupportedOperators.
GetTypeName()
virtual const FName & UE::Insights::FFilter::GetTypeName () const inline virtual
Reimplemented in UE::Insights::FFilterWithSuggestions.
Definition at line 236 of file Filters.h.
Is()
template<typename Type> bool UE::Insights::FFilter::Is () const inline
Definition at line 236 of file Filters.h.
IsKindOf()
virtual bool UE::Insights::FFilter::IsKindOf (const FName & InTypeName) const inline virtual
Reimplemented in UE::Insights::FFilterWithSuggestions.
Definition at line 236 of file Filters.h.
Field Documentation
Converter
TSharedPtr<IFilterValueConverter> UE::Insights::FFilter::Converter protected
Definition at line 268 of file Filters.h.
Referenced by FFilter(), and GetConverter().
DataType
EFilterDataType UE::Insights::FFilter::DataType protected
Definition at line 267 of file Filters.h.
Referenced by FFilter(), and GetDataType().
Desc
FText UE::Insights::FFilter::Desc protected
Definition at line 266 of file Filters.h.
Referenced by FFilter(), and GetDesc().
Key
int32 UE::Insights::FFilter::Key protected
Definition at line 264 of file Filters.h.
Referenced by FFilter(), and GetKey().
Name
FText UE::Insights::FFilter::Name protected
Definition at line 265 of file Filters.h.
Referenced by FFilter(), and GetName().
SupportedOperators
SupportedOperatorsArrayPtr UE::Insights::FFilter::SupportedOperators protected
Definition at line 269 of file Filters.h.
Referenced by FFilter(), and GetSupportedOperators().
TypeName
const FName UE::Insights::FFilter::TypeName static private
Definition at line 236 of file Filters.h.
The documentation for this class was generated from the following file:
Filters.h