Unreal Engine 5.6 C++ API: UE::Anim::TAttributeBlendOperator< AttributeType > Class Template Reference
UE::Anim::TAttributeBlendOperator< AttributeType > Class Template Reference
Default blend operator used for any registered attribute type, when no user-defined operator has been specified Using TEnableIf to select appropriate behaviour according to TAttributeTypeTraits<Type>::IsBlendable value for AttributeType template.
#include "AttributeBlendOperator.h"
Public Member Functions
virtual void Accumulate (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Begin IAttributeBlendOperator overrides.
virtual void Blend (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Invoked when two or multiple sets of attribute container inputs are to be blended together.
virtual void BlendPerBone (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Invoked when two or multiple sets of attribute container inputs are to be blended together, using individual bone weights.
virtual void ConvertToAdditive (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAdditiveAttributes) const final
Invoked when an attribute container is supposed to be made additive with regards to container B.
virtual void Interpolate (const void *FromData, const void *ToData, float Alpha, void *InOutData) const final
Invoked to interpolate between two individual attribute type values, according to the provided alpha.
virtual void Override (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Invoked when an attribute container A is expected to override attributes in container B.
Public Member Functions inherited from UE::Anim::IAttributeBlendOperator
virtual ~IAttributeBlendOperator ()
Protected Member Functions
template<typename Type>
FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type Accumulate_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
template<typename Type>
FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type Accumulate_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
template<typename Type>
FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type Blend_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
End IAttributeBlendOperator overrides.
template<typename Type>
FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type Blend_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
Blend operation for non-blendable attribute types.
template<typename Type>
FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type BlendPerBone_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
template<typename Type>
FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type BlendPerBone_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
template<typename Type>
FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type ConvertToAdditive_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAdditiveAttributes) const
template<typename Type>
FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type ConvertToAdditive_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAdditiveAttributes) const
template<typename Type>
FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable &&!TAttributeTypeTraits< AttributeType >::StepInterpolate, void >::Type Interpolate_Internal (const void *FromData, const void *ToData, float Alpha, void *InOutData) const
template<typename Type>
FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable||TAttributeTypeTraits< AttributeType >::StepInterpolate, void >::Type Interpolate_Internal (const void *FromData, const void *ToData, float Alpha, void *InOutData) const
template<typename Type>
FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type Override_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
template<typename Type>
FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type Override_Internal (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const
Detailed Description
template<typename AttributeType>
class UE::Anim::TAttributeBlendOperator< AttributeType >
Default blend operator used for any registered attribute type, when no user-defined operator has been specified Using TEnableIf to select appropriate behaviour according to TAttributeTypeTraits<Type>::IsBlendable value for AttributeType template.
Definition at line 20 of file AttributeBlendOperator.h.
Member Function Documentation
Accumulate()
template<typename AttributeType> virtual void UE::Anim::TAttributeBlendOperator< AttributeType >::Accumulate (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Begin IAttributeBlendOperator overrides.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 24 of file AttributeBlendOperator.h.
References Accumulate_Internal().
Accumulate_Internal() [1/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Accumulate_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
Definition at line 296 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), INDEX_NONE, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::RequiresNormalization.
Referenced by Accumulate().
Accumulate_Internal() [2/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Accumulate_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
Definition at line 329 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), INDEX_NONE, and UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey().
Blend()
template<typename AttributeType> virtual void UE::Anim::TAttributeBlendOperator< AttributeType >::Blend (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Invoked when two or multiple sets of attribute container inputs are to be blended together.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 27 of file AttributeBlendOperator.h.
References Blend_Internal().
Blend_Internal() [1/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Blend_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
End IAttributeBlendOperator overrides.
Blend operation for blendable attribute types
Definition at line 35 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachAttributeSet(), UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), UE::Anim::Attributes::GetAttributeBlendType(), and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::RequiresNormalization.
Referenced by Blend().
Blend_Internal() [2/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Blend_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
Blend operation for non-blendable attribute types.
Definition at line 108 of file AttributeBlendOperator.h.
References UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Add(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachAttributeSet(), UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), and UE::Anim::Attributes::GetAttributeBlendType().
BlendPerBone()
template<typename AttributeType> virtual void UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Invoked when two or multiple sets of attribute container inputs are to be blended together, using individual bone weights.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 28 of file AttributeBlendOperator.h.
References BlendPerBone_Internal().
BlendPerBone_Internal() [1/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
Definition at line 131 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachAttributeSet(), UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), UE::Anim::Attributes::GetAttributeBlendType(), INDEX_NONE, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), FAnimWeight::IsFullWeight(), and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::RequiresNormalization.
Referenced by BlendPerBone().
BlendPerBone_Internal() [2/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
Definition at line 217 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachAttributeSet(), UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), INDEX_NONE, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), and FAnimWeight::IsRelevant().
ConvertToAdditive()
template<typename AttributeType> virtual void UE::Anim::TAttributeBlendOperator< AttributeType >::ConvertToAdditive (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAdditiveAttributes) const inline final virtual
Invoked when an attribute container is supposed to be made additive with regards to container B.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 29 of file AttributeBlendOperator.h.
References ConvertToAdditive_Internal().
ConvertToAdditive_Internal() [1/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::ConvertToAdditive_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAdditiveAttributes) const inline protected
Definition at line 353 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::RequiresNormalization.
Referenced by ConvertToAdditive().
ConvertToAdditive_Internal() [2/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::ConvertToAdditive_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAdditiveAttributes) const inline protected
Definition at line 377 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), INDEX_NONE, and UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey().
Interpolate()
template<typename AttributeType> virtual void UE::Anim::TAttributeBlendOperator< AttributeType >::Interpolate (const void * FromData, const void * ToData, float Alpha, void * InOutData) const inline final virtual
Invoked to interpolate between two individual attribute type values, according to the provided alpha.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 25 of file AttributeBlendOperator.h.
References Alpha, and Interpolate_Internal().
Interpolate_Internal() [1/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable &&!TAttributeTypeTraits< AttributeType >::StepInterpolate, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Interpolate_Internal (const void * FromData, const void * ToData, float Alpha, void * InOutData) const inline protected
Definition at line 401 of file AttributeBlendOperator.h.
References Alpha, FORCEINLINE, UE::Anim::TAttributeTypeTraitsBase< AttributeType >::RequiresNormalization, and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::StepInterpolate.
Referenced by Interpolate().
Interpolate_Internal() [2/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable||TAttributeTypeTraits< AttributeType >::StepInterpolate, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Interpolate_Internal (const void * FromData, const void * ToData, float Alpha, void * InOutData) const inline protected
Definition at line 418 of file AttributeBlendOperator.h.
References Alpha, FORCEINLINE, and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::StepInterpolate.
Override()
template<typename AttributeType> virtual void UE::Anim::TAttributeBlendOperator< AttributeType >::Override (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Invoked when an attribute container A is expected to override attributes in container B.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 26 of file AttributeBlendOperator.h.
References Override_Internal().
Override_Internal() [1/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf< TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Override_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
Definition at line 253 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, UE::Anim::FAttributeBlendData::ForEachUniqueAttribute(), and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::RequiresNormalization.
Referenced by Override().
Override_Internal() [2/2]
template<typename AttributeType> template<typename Type> FORCEINLINE TEnableIf<!TAttributeTypeTraits< Type >::IsBlendable, void >::Type UE::Anim::TAttributeBlendOperator< AttributeType >::Override_Internal (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline protected
Definition at line 278 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), FORCEINLINE, and UE::Anim::FAttributeBlendData::ForEachUniqueAttribute().
The documentation for this class was generated from the following file:
AttributeBlendOperator.h