Unreal Engine 5.6 C++ API: FTextureRenderTargetCubeResource Class Reference
FTextureRenderTargetCubeResource Class Reference
FTextureResource type for cube render target textures.
#include "TextureResource.h"
Public Member Functions
FTextureRenderTargetCubeResource (const class UTextureRenderTargetCube *InOwner)
Constructor.
float GetDisplayGamma () const override
Render target resource should be sampled in linear color space.
virtual uint32 GetSizeX () const override
virtual FIntPoint GetSizeXY () const override
virtual uint32 GetSizeY () const override
virtual class FTextureRenderTargetCubeResource * GetTextureRenderTargetCubeResource ()
Cube texture RT resource interface.
FUnorderedAccessViewRHIRef GetUnorderedAccessViewRHI ()
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the dynamic RHI resource and/or RHI render target used by this resource.
virtual void ReleaseRHI () override
Releases the dynamic RHI resource and/or RHI render target resources used by this resource.
UE_DEPRECATED (5.4, "Use FRenderTarget's ReadFloat16Pixels, which is functionally equivalent") 1 bool ReadPixels(TArray< FFloat16Color > &OutImageData
Copy the texels of a single face of the cube into an array.
UE_DEPRECATED (5.4, "Use FRenderTarget's ReadPixels, which is functionally equivalent") 1 bool ReadPixels(TArray< FColor > &OutImageData
Copy the texels of a single face of the cube into an array.
Public Member Functions inherited from FTextureRenderTargetResource
FTextureRenderTargetResource ()
Constructor, initializing ClearLink.
virtual void ClampSize (int32 SizeX, int32 SizeY)
virtual FRHIGPUMask GetGPUMask (FRHICommandListImmediate &RHICmdList) const final override
Returns the GPU nodes on which to render this render target.
virtual const FTextureRHIRef & GetShaderResourceTexture () const override
Accessor for the surface RHI to use when reading the reading target (may differ from GetRenderTargetTexture() for some implementations like cubemaps)
virtual class FTextureRenderTarget2DArrayResource * GetTextureRenderTarget2DArrayResource ()
virtual class FTextureRenderTarget2DResource * GetTextureRenderTarget2DResource ()
virtual class FTextureRenderTargetVolumeResource * GetTextureRenderTargetVolumeResource ()
void SetActiveGPUMask (FRHIGPUMask InGPUMask)
Public Member Functions inherited from FTextureResource
FTextureResource ()
virtual ~FTextureResource ()
FORCEINLINE int32 GetCurrentMipCount () const
virtual FStreamableTextureResource * GetStreamableTextureResource ()
virtual const FStreamableTextureResource * GetStreamableTextureResource () const
virtual FTexture2DArrayResource * GetTexture2DArrayResource ()
virtual const FTexture2DArrayResource * GetTexture2DArrayResource () const
FORCEINLINE FRHITexture * GetTexture2DArrayRHI () const
virtual FTexture2DResource * GetTexture2DResource ()
virtual const FTexture2DResource * GetTexture2DResource () const
FORCEINLINE FRHITexture * GetTexture2DRHI () const
virtual FTexture3DResource * GetTexture3DResource ()
virtual const FTexture3DResource * GetTexture3DResource () const
FORCEINLINE FRHITexture * GetTexture3DRHI () const
FRHITextureReference * GetTextureReference () const
virtual FVirtualTexture2DResource * GetVirtualTexture2DResource ()
virtual const FVirtualTexture2DResource * GetVirtualTexture2DResource () const
virtual bool IsProxy () const
Returns true if the resource is proxying another one.
FORCEINLINE bool IsTextureRHIPartiallyResident () const
void SetTextureReference (FRHITextureReference *TextureReference)
Public Member Functions inherited from FTexture
RENDERCORE_API FTexture ()
RENDERCORE_API FTexture (const FTexture &)
RENDERCORE_API FTexture (FTexture &&)
virtual RENDERCORE_API ~FTexture ()
virtual RENDERCORE_API FString GetFriendlyName () const override
virtual RENDERCORE_API uint32 GetSizeZ () const
Returns the depth of the texture in pixels.
const FTextureRHIRef & GetTextureRHI ()
RENDERCORE_API FTexture & operator= (const FTexture &Other)
RENDERCORE_API FTexture & operator= (FTexture &&Other)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Public Member Functions inherited from FRenderTarget
FRenderTarget ()
Default constructor.
virtual ~FRenderTarget ()
Destructor.
virtual EDisplayColorGamut GetDisplayColorGamut () const
virtual EDisplayOutputFormat GetDisplayOutputFormat () const
virtual const FTextureRHIRef & GetRenderTargetTexture () const
Accessor for the surface RHI when setting this render target.
virtual FRDGTextureRef GetRenderTargetTexture (FRDGBuilder &GraphBuilder) const
Returns a valid RDG texture for this render target.
virtual FUnorderedAccessViewRHIRef GetRenderTargetUAV () const
virtual bool GetSceneHDREnabled () const
virtual bool HasToggleFreezeCommand ()
Returns if there is a command to toggle freezerendering.
virtual void ProcessToggleFreezeCommand ()
Handles freezing/unfreezing of rendering.
virtual bool ReadFloat16Pixels (TArray< FFloat16Color > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadLinearColorPixels (TArray< FLinearColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
bool ReadLinearColorPixelsPtr (FLinearColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadPixels (TArray< FColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
bool ReadPixelsPtr (FColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
UE_DEPRECATED (5.4, "Use the other ReadFloat16Pixels variant (ECubeFace can be set in FReadSurfaceDataFlags)") 1 bool ReadFloat16Pixels(TArray< FFloat16Color > &OutImageData
Reads the render target's displayed pixels into the given color buffer.
Public Member Functions inherited from FDeferredUpdateResource
FDeferredUpdateResource ()
Constructor, initializing UpdateListLink.
void FlushDeferredResourceUpdate (FRHICommandListImmediate &RHICmdList)
Performs a deferred resource update on this resource if it exists in the UpdateList.
void ResetSceneTextureExtentsHistory ()
Data Fields
FReadSurfaceDataFlags InFlags
FReadSurfaceDataFlags FIntRect InRect = FIntRect(0, 0, 0, 0))
Data Fields inherited from FTexture
bool bGreyScaleFormat = false
bGreyScaleFormat indicates the texture is actually in R channel but should be read as Grey (replicate R to RGBA) this is set from CompressionSettings, not PixelFormat this is only used by Editor/Debug shaders, not real game materials, which use SamplerType from MaterialExpressions
bool bIgnoreGammaConversions = false
true if the texture is in the same gamma space as the intended rendertarget (e.g.
bool bSRGB = false
Is the pixel data in this texture sRGB?
FSamplerStateRHIRef DeferredPassSamplerStateRHI
Sampler state to be used in deferred passes when discontinuities in ddx / ddy would cause too blurry of a mip to be used.
double LastRenderTime = -FLT_MAX
The last time the texture has been bound.
FMipBiasFade MipBiasFade
Base values for fading in/out mip-levels.
FSamplerStateRHIRef SamplerStateRHI
The sampler state to use for the texture.
FTextureRHIRef TextureRHI
The texture's RHI resource.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Data Fields inherited from FRenderTarget
ECubeFace CubeFace
Protected Member Functions
virtual void UpdateDeferredResource (FRHICommandListImmediate &RHICmdList, bool bClearRenderTarget=true) override
Updates (resolves) the render target texture.
Protected Member Functions inherited from FTextureRenderTargetResource
void SetGPUMask (FRHIGPUMask InGPUMask)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Protected Member Functions inherited from FDeferredUpdateResource
void AddToDeferredUpdateList (bool OnlyUpdateOnce)
Add this resource to deferred update list.
void RemoveFromDeferredUpdateList ()
Remove this resource from deferred update list.
Private Member Functions
UE_DEPRECATED (5.1, "CubeFaceSurfaceRHI is deprecated. Use TextureRHI instead.") FTextureRHIRef CubeFaceSurfaceRHI
UE_DEPRECATED (5.1, "RenderTargetCubeRHI is deprecated. Use TextureRHI instead.") FTextureRHIRef RenderTargetCubeRHI
UE_DEPRECATED (5.1, "TextureCubeRHI is deprecated. Use TextureRHI instead.") FTextureRHIRef TextureCubeRHI
Private Attributes
ECubeFace CurrentTargetFace
Face currently used for target surface.
const class UTextureRenderTargetCube * Owner
The UTextureRenderTargetCube which this resource represents.
FUnorderedAccessViewRHIRef UnorderedAccessViewRHI
Optional Unordered Access View for the resource, automatically created if bCanCreateUAV is true.
Friends
class UTextureRenderTargetCube
Updates (resolves) the render target texture.
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FTextureRenderTargetResource
static bool IsSupportedFormat (EPixelFormat Format)
Return true if a render target of the given format is allowed for creation.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Static Public Member Functions inherited from FRenderTarget
static float GetEngineDisplayGamma ()
Static Public Member Functions inherited from FDeferredUpdateResource
static bool IsUpdateNeeded ()
static void ResetNeedsUpdate ()
This is reset after all viewports have been rendered.
static void UpdateResources (FRHICommandListImmediate &RHICmdList)
Iterate over the global list of resources that need to be updated and call UpdateResource on each one.
Static Protected Member Functions inherited from FTexture
static RENDERCORE_API FRHISamplerState * GetOrCreateSamplerState (const FSamplerStateInitializerRHI &Initializer)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes inherited from FTextureResource
FTextureReferenceRHIRef TextureReferenceRHI
Protected Attributes inherited from FRenderTarget
FTextureRHIRef RenderTargetTextureRHI
Detailed Description
FTextureResource type for cube render target textures.
Definition at line 563 of file TextureResource.h.
Constructor & Destructor Documentation
FTextureRenderTargetCubeResource()
FTextureRenderTargetCubeResource::FTextureRenderTargetCubeResource (const class UTextureRenderTargetCube * InOwner) inline
Constructor.
Parameters
InOwner - cube texture object to create a resource for
Definition at line 571 of file TextureResource.h.
References Owner, and UTextureRenderTargetCube.
Referenced by GetTextureRenderTargetCubeResource().
Member Function Documentation
GetDisplayGamma()
float FTextureRenderTargetCubeResource::GetDisplayGamma () const override virtual
Render target resource should be sampled in linear color space.
Returns
display gamma expected for rendering to this render target
Reimplemented from FTextureRenderTargetResource.
GetSizeX()
virtual uint32 FTextureRenderTargetCubeResource::GetSizeX () const override virtual
Returns
width of the target
Implements FTextureRenderTargetResource.
GetSizeXY()
virtual FIntPoint FTextureRenderTargetCubeResource::GetSizeXY () const override virtual
Returns
dimensions of the target
Implements FRenderTarget.
GetSizeY()
virtual uint32 FTextureRenderTargetCubeResource::GetSizeY () const override virtual
Returns
height of the target
Implements FTextureRenderTargetResource.
GetTextureRenderTargetCubeResource()
virtual class FTextureRenderTargetCubeResource * FTextureRenderTargetCubeResource::GetTextureRenderTargetCubeResource () inline virtual
Cube texture RT resource interface.
Reimplemented from FTextureRenderTargetResource.
Definition at line 579 of file TextureResource.h.
References FTextureRenderTargetCubeResource().
GetUnorderedAccessViewRHI()
FUnorderedAccessViewRHIRef FTextureRenderTargetCubeResource::GetUnorderedAccessViewRHI () inline
Returns
UnorderedAccessView for rendering
Definition at line 620 of file TextureResource.h.
References UnorderedAccessViewRHI.
InitRHI()
virtual void FTextureRenderTargetCubeResource::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the dynamic RHI resource and/or RHI render target used by this resource.
Called when the resource is initialized, or when reseting all RHI resources. Resources that need to initialize after a D3D device reset must implement this function. This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseRHI()
virtual void FTextureRenderTargetCubeResource::ReleaseRHI () override virtual
Releases the dynamic RHI resource and/or RHI render target resources used by this resource.
Called when the resource is released, or when reseting all RHI resources. Resources that need to release before a D3D device reset must implement this function. This is only called by the rendering thread.
Reimplemented from FTexture.
UE_DEPRECATED() [1/5]
FTextureRenderTargetCubeResource::UE_DEPRECATED (5. 1, "CubeFaceSurfaceRHI is deprecated. Use TextureRHI instead.") private
References UE_DEPRECATED().
UE_DEPRECATED() [2/5]
FTextureRenderTargetCubeResource::UE_DEPRECATED (5. 1, "RenderTargetCubeRHI is deprecated. Use TextureRHI instead.") private
References UE_DEPRECATED().
UE_DEPRECATED() [3/5]
FTextureRenderTargetCubeResource::UE_DEPRECATED (5. 1, "TextureCubeRHI is deprecated. Use TextureRHI instead.") private
References UE_DEPRECATED().
UE_DEPRECATED() [4/5]
FTextureRenderTargetCubeResource::UE_DEPRECATED (5. 4, "Use FRenderTarget's ReadFloat16Pixels, which is functionally equivalent") &
Copy the texels of a single face of the cube into an array.
Parameters
OutImageData - float16 values will be stored in this array.
InFlags - read flags. ensure cubeface member has been set.
InRect - Rectangle of texels to copy.
Returns
true if the read succeeded.
References InFlags, InRect, FRenderTarget::ReadPixels(), and UE_DEPRECATED().
UE_DEPRECATED() [5/5]
FTextureRenderTargetCubeResource::UE_DEPRECATED (5. 4, "Use FRenderTarget's ReadPixels, which is functionally equivalent") &
Copy the texels of a single face of the cube into an array.
Parameters
OutImageData - float16 values will be stored in this array.
InFlags - read flags. ensure cubeface member has been set.
InRect - Rectangle of texels to copy.
Returns
true if the read succeeded.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UpdateDeferredResource()
virtual void FTextureRenderTargetCubeResource::UpdateDeferredResource (FRHICommandListImmediate & RHICmdList, bool bClearRenderTarget = true) override protected virtual
Updates (resolves) the render target texture.
Optionally clears the contents of the render target to green. This is only called by the rendering thread.
Implements FDeferredUpdateResource.
References UpdateDeferredResource().
Referenced by UpdateDeferredResource().
Friends And Related Symbol Documentation
UTextureRenderTargetCube
friend class UTextureRenderTargetCube friend
Updates (resolves) the render target texture.
Optionally clears each face of the render target to green. This is only called by the rendering thread.
Definition at line 655 of file TextureResource.h.
References UTextureRenderTargetCube.
Referenced by FTextureRenderTargetCubeResource(), and UTextureRenderTargetCube.
Field Documentation
CurrentTargetFace
ECubeFace FTextureRenderTargetCubeResource::CurrentTargetFace private
Face currently used for target surface.
Definition at line 675 of file TextureResource.h.
InFlags
FReadSurfaceDataFlags FTextureRenderTargetCubeResource::InFlags
Definition at line 637 of file TextureResource.h.
Referenced by UE_DEPRECATED().
InRect
FReadSurfaceDataFlags FIntRect FTextureRenderTargetCubeResource::InRect = FIntRect(0, 0, 0, 0))
Definition at line 637 of file TextureResource.h.
Referenced by UE_DEPRECATED().
Owner
const class UTextureRenderTargetCube* FTextureRenderTargetCubeResource::Owner private
The UTextureRenderTargetCube which this resource represents.
Definition at line 660 of file TextureResource.h.
Referenced by FTextureRenderTargetCubeResource().
UnorderedAccessViewRHI
FUnorderedAccessViewRHIRef FTextureRenderTargetCubeResource::UnorderedAccessViewRHI private
Optional Unordered Access View for the resource, automatically created if bCanCreateUAV is true.
Definition at line 672 of file TextureResource.h.
Referenced by GetUnorderedAccessViewRHI().
The documentation for this class was generated from the following file:
TextureResource.h