Unreal Engine 5.6 C++ API: UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs > Class Template Reference
UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs > Class Template Reference
A TThreadSafeMapBase specialization that only allows a single value associated with each key whilst being thread safe.
#include "ThreadSafeMap.h"
Public Types
typedef Super::KeyConstPointerType KeyConstPointerType
typedef KeyFuncs KeyFuncsType
typedef Super::KeyInitType KeyInitType
typedef InKeyType KeyType
typedef SetAllocator SetAllocatorType
typedef TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Super
typedef InValueType ValueType
Public Member Functions
TThreadSafeMap ()=default
TThreadSafeMap (const TThreadSafeMap &)=default
template<typename OtherSetAllocator>
TThreadSafeMap (const TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TThreadSafeMap with a different SetAllocator.
TThreadSafeMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Constructor which gets its elements from a native initializer list.
TThreadSafeMap (TThreadSafeMap &&)=default
template<typename OtherSetAllocator>
TThreadSafeMap (TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TThreadSafeMap with a different SetAllocator.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
template<typename OtherSetAllocator>
void Append (const TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &OtherMap)
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
template<typename OtherSetAllocator>
void Append (TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&OtherMap)
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
template<typename T>
void Apply (T &&Visitor)
template<typename T>
void ApplyUntil (T &&Visitor)
FORCEINLINE bool Contains (KeyConstPointerType Key)
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
FORCEINLINE ValueType * Find (KeyInitType Key)
FORCEINLINE ValueType FindAndRemoveChecked (KeyConstPointerType Key)
Find a pair with the specified key, removes it from the map, and returns the value part of the pair.
FORCEINLINE ValueType & FindOrAdd (KeyInitType Key)
FORCEINLINE ValueType FindRef (KeyInitType Key)
template<typename InSetKeyFuncs, typename InSetAllocator>
int32 GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > &OutKeys)
FORCEINLINE bool IsEmpty ()
TThreadSafeMap & operator= (const TThreadSafeMap &)=default
template<typename OtherSetAllocator>
TThreadSafeMap & operator= (const TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TThreadSafeMap with a different SetAllocator.
TThreadSafeMap & operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Assignment operator which gets its elements from a native initializer list.
TThreadSafeMap & operator= (TThreadSafeMap &&)=default
template<typename OtherSetAllocator>
TThreadSafeMap & operator= (TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TThreadSafeMap with a different SetAllocator.
FORCEINLINE ValueType & operator[] (KeyConstPointerType Key)
FORCEINLINE const ValueType & operator[] (KeyConstPointerType Key) const
FORCEINLINE int32 Remove (KeyConstPointerType Key)
FORCEINLINE bool RemoveAndCopyValue (KeyInitType Key, ValueType &OutRemovedValue)
Remove the pair with the specified key and copies the value that was removed to the ref parameter.
template<typename ComparableKey>
FORCEINLINE bool RemoveAndCopyValueByHash (uint32 KeyHash, const ComparableKey &Key, ValueType &OutRemovedValue)
See RemoveAndCopyValue() and class documentation section on ByHash() functions.
Private Attributes
FCriticalSection Mutex
Friends
template<typename, typename>
class TScriptThreadSafeMap
Additional Inherited Members
Protected Types inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
using IntrusiveUnsetOptionalStateType = TSortableMapBase
typedef TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Super
Protected Types inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
typedef TSet< ElementType, KeyFuncs, SetAllocator > ElementSetType
using IntrusiveUnsetOptionalStateType = TMapBase
typedef TPair< KeyType, ValueType > ElementType
typedef TTypeTraits< KeyType >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< KeyType >::ConstInitType KeyInitType
using TRangedForConstIterator = TBaseIterator<true, true>
using TRangedForIterator = TBaseIterator<false, true>
typedef TTypeTraits< ValueType >::ConstInitType ValueInitType
Protected Member Functions inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
TSortableMapBase ()=default
TSortableMapBase (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TSortableMapBase (FIntrusiveUnsetOptionalState Tag)
TSortableMapBase (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
template<typename PREDICATE_CLASS>
FORCEINLINE void KeySort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void KeyStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
void SortFreeList ()
Sort the free element list so that subsequent additions will occur in the lowest available TSet index resulting in tighter packing without moving any existing items.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueSort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
Protected Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
TMapBase ()=default
TMapBase (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TMapBase (FIntrusiveUnsetOptionalState Tag)
TMapBase (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TMapBase & operator= (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase & operator= (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TMapBase & operator= (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase & operator= (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
FORCEINLINE ValueType & Add (const KeyType &InKey)
Set a default value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (const TTuple< KeyType, ValueType > &InKeyValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (KeyType &&InKey)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (TTuple< KeyType, ValueType > &&InKeyValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, const ValueType &InValue)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, ValueType &&InValue)
TArray< ElementType > Array () const
Copy the key/value pairs in this map into an array.
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TRangedForConstIterator begin () const
FORCEINLINE void Compact ()
Compacts the pair set to remove holes.
FORCEINLINE void CompactStable ()
Compacts the pair set to remove holes.
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Check if map contains the specified key.
template<typename ComparableKey>
FORCEINLINE bool ContainsByHash (uint32 KeyHash, const ComparableKey &Key) const
See Contains() and class documentation section on ByHash() functions.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
FORCEINLINE void CountBytes (FArchive &Ar) const
Track the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (typename TConstKeyIterator::KeyArgumentType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (typename TKeyIterator::KeyArgumentType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
template<typename InitKeyType = KeyType>
ValueType & Emplace (InitKeyType &&InKey)
Set a default value associated with a key.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
template<typename InitKeyType = KeyType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey)
See Emplace() and class documentation section on ByHash() functions.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey, InitValueType &&InValue)
See Emplace() and class documentation section on ByHash() functions.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map.
FORCEINLINE TRangedForIterator end ()
FORCEINLINE TRangedForConstIterator end () const
template<typename Predicate>
TMap< KeyType, ValueType, SetAllocator, KeyFuncs > FilterByPredicate (Predicate Pred) const
Filters the elements in the map based on a predicate functor.
FORCEINLINE ValueType * Find (KeyConstPointerType Key)
Find the value associated with a specified key.
FORCEINLINE const ValueType * Find (KeyConstPointerType Key) const
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
const ElementType * FindArbitraryElement () const
template<typename ComparableKey>
FORCEINLINE ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key)
See Find() and class documentation section on ByHash() functions.
template<typename ComparableKey>
FORCEINLINE const ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key) const
template<typename ComparableKey>
FORCEINLINE ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key)
template<typename ComparableKey>
FORCEINLINE const ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key) const
FORCEINLINE ValueType & FindChecked (KeyConstPointerType Key)
Find a reference to the value associated with a specified key.
FORCEINLINE const ValueType & FindChecked (KeyConstPointerType Key) const
Find a reference to the value associated with a specified key.
FORCEINLINE FSetElementId FindId (KeyInitType Key) const
Finds the index of the first element that is assigned to the specified key.
template<typename ComparableKey>
FORCEINLINE FSetElementId FindIdByHash (uint32 KeyHash, const ComparableKey &Key) const
See FindId() and class documentation section on ByHash() functions.
const KeyType * FindKey (ValueInitType Value) const
Find the key associated with the specified value.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, const ValueType &Value)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, const ValueType &Value)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType FindRef (KeyConstPointerType Key) const
Find the value associated with a specified key.
FORCEINLINE ValueType FindRef (KeyConstPointerType Key, ValueType DefaultValue) const
Find the value associated with a specified key.
template<typename Allocator>
void GenerateKeyArray (TArray< KeyType, Allocator > &OutArray) const
Generate an array from the keys in this map.
template<typename Allocator>
void GenerateValueArray (TArray< ValueType, Allocator > &OutArray) const
Generate an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container .
template<typename Allocator>
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Get the unique keys contained within this map.
template<typename InSetKeyFuncs, typename InSetAllocator>
int32 GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > &OutKeys) const
Get the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
bool OrderIndependentCompareEqual (const TMapBase &Other) const
Compare this map with another for equality.
FORCEINLINE void Remove (FSetElementId Id)
Removes the element at the specified index.
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
template<typename ComparableKey>
FORCEINLINE int32 RemoveByHash (uint32 KeyHash, const ComparableKey &Key)
See Remove() and class documentation section on ByHash() functions.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Static Protected Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Protected Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
ElementSetType Pairs
A set of the key-value pairs in the map.
Static Protected Attributes inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Static Protected Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Detailed Description
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>>
class UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >
A TThreadSafeMapBase specialization that only allows a single value associated with each key whilst being thread safe.
Definition at line 13 of file ThreadSafeMap.h.
Member Typedef Documentation
KeyConstPointerType
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> typedef Super::KeyConstPointerType UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::KeyConstPointerType
Definition at line 28 of file ThreadSafeMap.h.
KeyFuncsType
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> typedef KeyFuncs UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::KeyFuncsType
Definition at line 24 of file ThreadSafeMap.h.
KeyInitType
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> typedef Super::KeyInitType UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::KeyInitType
Definition at line 27 of file ThreadSafeMap.h.
KeyType
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> typedef InKeyType UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::KeyType
Definition at line 21 of file ThreadSafeMap.h.
SetAllocatorType
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> typedef SetAllocator UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::SetAllocatorType
Definition at line 23 of file ThreadSafeMap.h.
Super
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> typedef TSortableMapBase<KeyType, ValueType, SetAllocator, KeyFuncs> UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Super
Definition at line 26 of file ThreadSafeMap.h.
ValueType
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> typedef InValueType UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::ValueType
Definition at line 22 of file ThreadSafeMap.h.
Constructor & Destructor Documentation
TThreadSafeMap() [1/6]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap () default
Referenced by TThreadSafeMap(), TThreadSafeMap(), TThreadSafeMap(), TThreadSafeMap(), Append(), Append(), operator=(), operator=(), operator=(), operator=(), and operator=().
TThreadSafeMap() [2/6]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap (TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs > &&) default
References TThreadSafeMap().
TThreadSafeMap() [3/6]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap (const TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs > &) default
References TThreadSafeMap().
TThreadSafeMap() [4/6]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename OtherSetAllocator> UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap (TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline
Constructor for moving elements from a TThreadSafeMap with a different SetAllocator.
Definition at line 38 of file ThreadSafeMap.h.
References TThreadSafeMap(), MoveTemp(), and Other.
TThreadSafeMap() [5/6]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename OtherSetAllocator> UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap (const TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline
Constructor for copying elements from a TThreadSafeMap with a different SetAllocator.
Definition at line 45 of file ThreadSafeMap.h.
References TThreadSafeMap(), and Other.
TThreadSafeMap() [6/6]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList) inline
Constructor which gets its elements from a native initializer list.
Definition at line 51 of file ThreadSafeMap.h.
References Add, Mutex, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reserve().
Member Function Documentation
Add() [1/4]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add (const KeyType & InKey, const ValueType & InValue) inline
Definition at line 304 of file ThreadSafeMap.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace(), FORCEINLINE, and Mutex.
Add() [2/4]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add (const KeyType & InKey, ValueType && InValue) inline
Definition at line 311 of file ThreadSafeMap.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace(), FORCEINLINE, MoveTempIfPossible(), and Mutex.
Add() [3/4]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add (KeyType && InKey, const ValueType & InValue) inline
Definition at line 318 of file ThreadSafeMap.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace(), FORCEINLINE, MoveTempIfPossible(), and Mutex.
Add() [4/4]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add (KeyType && InKey, ValueType && InValue) inline
Definition at line 325 of file ThreadSafeMap.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace(), FORCEINLINE, MoveTempIfPossible(), and Mutex.
Append() [1/2]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename OtherSetAllocator> void UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Append (const TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & OtherMap) inline
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
Parameters
OtherMap The other map of items to add.
Definition at line 193 of file ThreadSafeMap.h.
References TThreadSafeMap(), Add, Mutex, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Num(), and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reserve().
Append() [2/2]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename OtherSetAllocator> void UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Append (TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && OtherMap) inline
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
Parameters
OtherMap The other map of items to move the elements from.
Definition at line 173 of file ThreadSafeMap.h.
References TThreadSafeMap(), Add, MoveTempIfPossible(), Mutex, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Num(), and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reserve().
Apply()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename T> void UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Apply (T && Visitor) inline
Definition at line 220 of file ThreadSafeMap.h.
References Mutex, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
ApplyUntil()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename T> void UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::ApplyUntil (T && Visitor) inline
Definition at line 231 of file ThreadSafeMap.h.
References Mutex, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
Contains()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE bool UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Contains (KeyConstPointerType Key) inline nodiscard
Definition at line 297 of file ThreadSafeMap.h.
References Contains(), FORCEINLINE, Key, and Mutex.
Referenced by Contains().
Empty()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE void UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Empty (int32 ExpectedNumElements = 0) inline
Definition at line 278 of file ThreadSafeMap.h.
References TSet< InElementType, KeyFuncs, Allocator >::Empty(), FORCEINLINE, MoveTemp(), Mutex, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
Find()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType * UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Find (KeyInitType Key) inline
Definition at line 250 of file ThreadSafeMap.h.
References Find, FORCEINLINE, Key, and Mutex.
FindAndRemoveChecked()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::FindAndRemoveChecked (KeyConstPointerType Key) inline
Find a pair with the specified key, removes it from the map, and returns the value part of the pair.
If no pair was found, an exception is thrown.
Parameters
Key the key to search for
Returns
whether or not the key was found
Definition at line 155 of file ThreadSafeMap.h.
References check, FORCEINLINE, FSetElementId::IsValidId(), Key, MoveTempIfPossible(), Mutex, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs, and Value.
FindOrAdd()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::FindOrAdd (KeyInitType Key) inline
Definition at line 243 of file ThreadSafeMap.h.
References FindOrAdd(), FORCEINLINE, Key, and Mutex.
Referenced by FindOrAdd().
FindRef()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::FindRef (KeyInitType Key) inline
Definition at line 257 of file ThreadSafeMap.h.
References FindRef(), FORCEINLINE, Key, and Mutex.
Referenced by FindRef().
GetKeys()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename InSetKeyFuncs, typename InSetAllocator> int32 UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > & OutKeys) inline
Definition at line 290 of file ThreadSafeMap.h.
References GetKeys(), and Mutex.
Referenced by GetKeys().
IsEmpty()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE bool UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::IsEmpty () inline
Definition at line 271 of file ThreadSafeMap.h.
References FORCEINLINE, IsEmpty(), and Mutex.
Referenced by IsEmpty().
operator=() [1/5]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> TThreadSafeMap & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator= (const TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs > &) default
References TThreadSafeMap().
operator=() [2/5]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename OtherSetAllocator> TThreadSafeMap & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator= (const TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline
Assignment operator for copying elements from a TThreadSafeMap with a different SetAllocator.
Definition at line 80 of file ThreadSafeMap.h.
References TThreadSafeMap(), TSet< InElementType, KeyFuncs, Allocator >::Empty(), MoveTemp(), Mutex, Other, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
operator=() [3/5]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> TThreadSafeMap & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList) inline
Assignment operator which gets its elements from a native initializer list.
Definition at line 95 of file ThreadSafeMap.h.
References TThreadSafeMap(), Add, Mutex, and UE::TSharedString< CharType >::Empty.
operator=() [4/5]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> TThreadSafeMap & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator= (TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs > &&) default
References TThreadSafeMap().
operator=() [5/5]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename OtherSetAllocator> TThreadSafeMap & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator= (TThreadSafeMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline
Assignment operator for moving elements from a TThreadSafeMap with a different SetAllocator.
Definition at line 64 of file ThreadSafeMap.h.
References TThreadSafeMap(), TSet< InElementType, KeyFuncs, Allocator >::Empty(), MoveTemp(), Mutex, Other, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
operator[]() [1/2]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE ValueType & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator[] (KeyConstPointerType Key) inline
Definition at line 204 of file ThreadSafeMap.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindChecked(), FORCEINLINE, Key, and Mutex.
operator[]() [2/2]
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE const ValueType & UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator[] (KeyConstPointerType Key) const inline
Definition at line 211 of file ThreadSafeMap.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindChecked(), FORCEINLINE, Key, and Mutex.
Remove()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE int32 UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Remove (KeyConstPointerType Key) inline
Definition at line 264 of file ThreadSafeMap.h.
References FORCEINLINE, Key, Mutex, and Remove.
RemoveAndCopyValue()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FORCEINLINE bool UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValue (KeyInitType Key, ValueType & OutRemovedValue) inline
Remove the pair with the specified key and copies the value that was removed to the ref parameter.
Parameters
Key The key to search for
OutRemovedValue If found, the value that was removed (not modified if the key was not found)
Returns
whether or not the key was found
Definition at line 115 of file ThreadSafeMap.h.
References FORCEINLINE, FSetElementId::IsValidId(), Key, MoveTempIfPossible(), Mutex, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs, and Value.
RemoveAndCopyValueByHash()
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename ComparableKey> FORCEINLINE bool UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValueByHash (uint32 KeyHash, const ComparableKey & Key, ValueType & OutRemovedValue) inline
See RemoveAndCopyValue() and class documentation section on ByHash() functions.
Definition at line 132 of file ThreadSafeMap.h.
References FORCEINLINE, FSetElementId::IsValidId(), Key, MoveTempIfPossible(), Mutex, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs, and Value.
Friends And Related Symbol Documentation
TScriptThreadSafeMap
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> template<typename, typename> friend class TScriptThreadSafeMap friend
Definition at line 16 of file ThreadSafeMap.h.
References TScriptThreadSafeMap.
Referenced by TScriptThreadSafeMap.
Field Documentation
Mutex
template<typename InKeyType, typename InValueType, typename SetAllocator = FDefaultSetAllocator, typename KeyFuncs = TDefaultMapHashableKeyFuncs<InKeyType, InValueType, false>> FCriticalSection UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Mutex mutable private
Definition at line 333 of file ThreadSafeMap.h.
Referenced by TThreadSafeMap(), Add(), Add(), Add(), Add(), Append(), Append(), Apply(), ApplyUntil(), Contains(), Empty(), Find(), FindAndRemoveChecked(), FindOrAdd(), FindRef(), GetKeys(), IsEmpty(), operator=(), operator=(), operator=(), operator[](), operator[](), Remove(), RemoveAndCopyValue(), and RemoveAndCopyValueByHash().
The documentation for this class was generated from the following file:
ThreadSafeMap.h