Unreal Engine 5.6 C++ API: FTrackInstancePropertyBindings Class Reference
FTrackInstancePropertyBindings Class Reference
Manages bindings to keyed properties for a track instance.
#include "MovieSceneCommonHelpers.h"
Data Structures
struct FResolvedProperty
struct FResolvedPropertyAndFunction
Public Member Functions
MOVIESCENE_API FTrackInstancePropertyBindings (FName InPropertyName, const FString &InPropertyPath)
MOVIESCENE_API void CacheBinding (const UObject &InRuntimeObject)
Rebuilds the property and function mappings for a single runtime object, and adds them to the cache.
template<>
MOVIESCENE_API void CallFunction (UObject &InRuntimeObject, TCallTraits< bool >::ParamType PropertyValue)
Explicit specializations for bools.
template<typename ValueType>
void CallFunction (UObject &InRuntimeObject, typename TCallTraits< ValueType >::ParamType PropertyValue)
Calls the setter function for a specific runtime object or if the setter function does not exist, the property is set directly.
template<>
MOVIESCENE_API void CallFunction (UObject &InRuntimeObject, UObject *PropertyValue)
Explicit specializations for object pointers.
MOVIESCENE_API void CallFunctionForEnum (UObject &InRuntimeObject, int64 PropertyValue)
Calls the setter function for a specific runtime object or if the setter function does not exist, the property is set directly.
template<typename ValueType>
ValueType GetCurrentValue (const UObject &Object)
Gets the current value of a property on an object.
MOVIESCENE_API int64 GetCurrentValueForEnum (const UObject &Object)
Gets the current value of a property on an object.
template<typename ValueType>
TOptional< ValueType > GetOptionalValue (const UObject &Object)
Optionally gets the current value of a property on an object.
MOVIESCENE_API FProperty * GetProperty (const UObject &Object)
Gets the FProperty that is bound to the track instance.
const FName & GetPropertyName () const
const FString & GetPropertyPath () const
MOVIESCENE_API const UStruct * GetPropertyStruct (const UObject &Object)
Gets the structure type of the bound property if it is a property of that type.
MOVIESCENE_API bool HasValidBinding (const UObject &Object)
Returns whether this binding is valid for the given object.
template<>
MOVIESCENE_API void SetCurrentValue (UObject &Object, TCallTraits< bool >::ParamType InValue)
template<typename ValueType>
void SetCurrentValue (UObject &Object, typename TCallTraits< ValueType >::ParamType InValue)
Sets the current value of a property on an object.
template<>
MOVIESCENE_API void SetCurrentValue (UObject &Object, UObject *InValue)
Static Public Member Functions
static MOVIESCENE_API FProperty * FindProperty (const UObject *Object, const FString &InPropertyPath)
template<typename ValueType>
static TOptional< ValueType > StaticValue (const UObject *Object, const FString &InPropertyPath)
Static function for accessing a property value on an object without caching its address.
Private Member Functions
MOVIESCENE_API FResolvedPropertyAndFunction FindOrAdd (const UObject &InObject)
Find or add the FResolvedPropertyAndFunction for the specified object.
Static Private Member Functions
static MOVIESCENE_API void FindProperty (FTrackInstancePropertyBindings &Bindings, void *BasePointer, UStruct *InStruct, const FString &InPropertyName, FResolvedProperty &OutResolvedProperty)
static MOVIESCENE_API FResolvedProperty FindPropertyAndArrayIndex (FTrackInstancePropertyBindings &Bindings, void *BasePointer, UStruct *InStruct, const FString &PropertyName)
template<typename T>
static void InvokeSetterFunction (UObject *InRuntimeObject, UFunction *Setter, T &&InPropertyValue)
Wrapper for UObject::ProcessEvent that attempts to pass the new property value directly to the function as a parameter, but handles cases where multiple parameters or a return value exists.
static MOVIESCENE_API FResolvedProperty ResolveProperty (FTrackInstancePropertyBindings &Bindings, const UObject &Object)
static MOVIESCENE_API FResolvedProperty ResolvePropertyRecursive (FTrackInstancePropertyBindings &Bindings, void *BasePointer, UStruct *InStruct, TArray< FString > &InPropertyNames, uint32 Index)
template<>
MOVIESCENE_API bool TryGetPropertyValue (const FResolvedProperty &ResolvedProperty, bool &OutValue)
template<>
MOVIESCENE_API bool TryGetPropertyValue (const FResolvedProperty &ResolvedProperty, UObject *&OutValue)
template<typename ValueType>
static bool TryGetPropertyValue (const FResolvedProperty &ResolvedProperty, ValueType &OutValue)
Private Attributes
FName FunctionName
Name of the function to call to set values.
FName NotifyFunctionName
Name of a function to call when a value has been set.
FName PropertyName
Actual name of the property we are bound to.
FString PropertyPath
Path to the property we are bound to.
TMap< FObjectKey, FResolvedPropertyAndFunction > RuntimeObjectToFunctionMap
Mapping of objects to bound functions that will be called to update data on the track.
Detailed Description
Manages bindings to keyed properties for a track instance.
Calls UFunctions to set the value on runtime objects
Definition at line 299 of file MovieSceneCommonHelpers.h.
Constructor & Destructor Documentation
FTrackInstancePropertyBindings()
MOVIESCENE_API FTrackInstancePropertyBindings::FTrackInstancePropertyBindings (FName InPropertyName, const FString & InPropertyPath)
Referenced by FindProperty(), FindPropertyAndArrayIndex(), ResolveProperty(), ResolvePropertyRecursive(), and StaticValue().
Member Function Documentation
CacheBinding()
MOVIESCENE_API void FTrackInstancePropertyBindings::CacheBinding (const UObject & InRuntimeObject)
Rebuilds the property and function mappings for a single runtime object, and adds them to the cache.
Parameters
InRuntimeObject The object to cache mappings for
CallFunction() [1/3]
template<> MOVIESCENE_API void FTrackInstancePropertyBindings::CallFunction (UObject & InRuntimeObject, TCallTraits< bool >::ParamType PropertyValue)
Explicit specializations for bools.
CallFunction() [2/3]
template<typename ValueType> void FTrackInstancePropertyBindings::CallFunction (UObject & InRuntimeObject, typename TCallTraits< ValueType >::ParamType PropertyValue) inline
Calls the setter function for a specific runtime object or if the setter function does not exist, the property is set directly.
Parameters
InRuntimeObject The runtime object whose function to call
PropertyValue The new value to assign to the property
Definition at line 312 of file MovieSceneCommonHelpers.h.
References FindOrAdd(), TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::GetPropertyAddress(), FTrackInstancePropertyBindings::FResolvedProperty::GetValidProperty(), InvokeSetterFunction(), MoveTempIfPossible(), FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::NotifyFunction, UObject::ProcessEvent(), Property, FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::ResolvedProperty, and FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::SetterFunction.
Referenced by UE::MovieScene::FBoolPropertyTraits::SetObjectPropertyValue(), UE::MovieScene::TDirectPropertyTraits< float >::SetObjectPropertyValue(), and UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::SetObjectPropertyValue().
CallFunction() [3/3]
template<> MOVIESCENE_API void FTrackInstancePropertyBindings::CallFunction (UObject & InRuntimeObject, UObject * PropertyValue)
Explicit specializations for object pointers.
CallFunctionForEnum()
MOVIESCENE_API void FTrackInstancePropertyBindings::CallFunctionForEnum (UObject & InRuntimeObject, int64 PropertyValue)
Calls the setter function for a specific runtime object or if the setter function does not exist, the property is set directly.
Parameters
InRuntimeObject The runtime object whose function to call
PropertyValue The new value to assign to the property
FindOrAdd()
MOVIESCENE_API FResolvedPropertyAndFunction FTrackInstancePropertyBindings::FindOrAdd (const UObject & InObject) private
Find or add the FResolvedPropertyAndFunction for the specified object.
Referenced by CallFunction(), GetCurrentValue(), GetOptionalValue(), and SetCurrentValue().
FindProperty() [1/2]
MOVIESCENE_API FProperty * FTrackInstancePropertyBindings::FindProperty (const UObject * Object, const FString & InPropertyPath) static
References Object.
FindProperty() [2/2]
MOVIESCENE_API void FTrackInstancePropertyBindings::FindProperty (FTrackInstancePropertyBindings & Bindings, void * BasePointer, UStruct * InStruct, const FString & InPropertyName, FResolvedProperty & OutResolvedProperty) static private
References FTrackInstancePropertyBindings().
FindPropertyAndArrayIndex()
MOVIESCENE_API FResolvedProperty FTrackInstancePropertyBindings::FindPropertyAndArrayIndex (FTrackInstancePropertyBindings & Bindings, void * BasePointer, UStruct * InStruct, const FString & PropertyName) static private
References FTrackInstancePropertyBindings(), and PropertyName.
GetCurrentValue()
template<typename ValueType> ValueType FTrackInstancePropertyBindings::GetCurrentValue (const UObject & Object) inline
Gets the current value of a property on an object.
Parameters
Object The object to get the property from
Returns
ValueType The current value
Definition at line 382 of file MovieSceneCommonHelpers.h.
References FindOrAdd(), Object, FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::ResolvedProperty, TryGetPropertyValue(), and Value.
Referenced by PropertyTemplate::CacheExistingState(), UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::TDirectPropertyTraits< float >::GetObjectPropertyValue(), UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue(), and TMovieSceneExternalValue< uint8 >::GetValue().
GetCurrentValueForEnum()
MOVIESCENE_API int64 FTrackInstancePropertyBindings::GetCurrentValueForEnum (const UObject & Object)
Gets the current value of a property on an object.
Parameters
Object The object to get the property from
Returns
ValueType The current value
References Object.
GetOptionalValue()
template<typename ValueType> TOptional< ValueType > FTrackInstancePropertyBindings::GetOptionalValue (const UObject & Object) inline
Optionally gets the current value of a property on an object.
Parameters
Object The object to get the property from
Returns
(Optional) The current value of the property on the object
Definition at line 399 of file MovieSceneCommonHelpers.h.
References FindOrAdd(), Object, FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::ResolvedProperty, TryGetPropertyValue(), and Value.
GetProperty()
MOVIESCENE_API FProperty * FTrackInstancePropertyBindings::GetProperty (const UObject & Object)
Gets the FProperty that is bound to the track instance.
Parameters
Object The Object that owns the property
Returns
The property on the object if it exists
References Object.
GetPropertyName()
const FName & FTrackInstancePropertyBindings::GetPropertyName () const inline
Returns
the property name that this binding was initialized from
Definition at line 473 of file MovieSceneCommonHelpers.h.
References PropertyName.
GetPropertyPath()
const FString & FTrackInstancePropertyBindings::GetPropertyPath () const inline
Returns
the property path that this binding was initialized from
Definition at line 467 of file MovieSceneCommonHelpers.h.
References PropertyPath.
Referenced by UE::MovieScene::TPropertyValueStorage< PropertyTraits >::AddInitialValue().
GetPropertyStruct()
MOVIESCENE_API const UStruct * FTrackInstancePropertyBindings::GetPropertyStruct (const UObject & Object)
Gets the structure type of the bound property if it is a property of that type.
Parameters
Object The Object that owns the property
Returns
The structure type
References Object.
HasValidBinding()
MOVIESCENE_API bool FTrackInstancePropertyBindings::HasValidBinding (const UObject & Object)
Returns whether this binding is valid for the given object.
Parameters
Object The Object that owns the property
Returns
Whether the property binding is valid
References Object.
InvokeSetterFunction()
template<typename T> void FTrackInstancePropertyBindings::InvokeSetterFunction (UObject * InRuntimeObject, UFunction * Setter, T && InPropertyValue) static private
Wrapper for UObject::ProcessEvent that attempts to pass the new property value directly to the function as a parameter, but handles cases where multiple parameters or a return value exists.
The setter parameter must be the first in the list, any other parameters will be default constructed.
Definition at line 601 of file MovieSceneCommonHelpers.h.
References check, ensureMsgf, FMemory_Alloca, UObjectBaseUtility::GetName(), MAX_uint16, UFunction::NumParms, Params, UFunction::ParmsSize, UObject::ProcessEvent(), Property, UStruct::PropertyLink, UFunction::ReturnValueOffset, SIZE_T_FMT, and TEXT.
Referenced by CallFunction().
ResolveProperty()
MOVIESCENE_API FResolvedProperty FTrackInstancePropertyBindings::ResolveProperty (FTrackInstancePropertyBindings & Bindings, const UObject & Object) static private
References FTrackInstancePropertyBindings(), and Object.
Referenced by StaticValue().
ResolvePropertyRecursive()
MOVIESCENE_API FResolvedProperty FTrackInstancePropertyBindings::ResolvePropertyRecursive (FTrackInstancePropertyBindings & Bindings, void * BasePointer, UStruct * InStruct, TArray< FString > & InPropertyNames, uint32 Index) static private
References FTrackInstancePropertyBindings().
SetCurrentValue() [1/3]
template<> MOVIESCENE_API void FTrackInstancePropertyBindings::SetCurrentValue (UObject & Object, TCallTraits< bool >::ParamType InValue)
References Object.
SetCurrentValue() [2/3]
template<typename ValueType> void FTrackInstancePropertyBindings::SetCurrentValue (UObject & Object, typename TCallTraits< ValueType >::ParamType InValue) inline
Sets the current value of a property on an object.
Parameters
Object The object to set the property on
InValue The value to set
Definition at line 451 of file MovieSceneCommonHelpers.h.
References FindOrAdd(), TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::GetPropertyAddress(), FTrackInstancePropertyBindings::FResolvedPropertyAndFunction::NotifyFunction, and Object.
SetCurrentValue() [3/3]
template<> MOVIESCENE_API void FTrackInstancePropertyBindings::SetCurrentValue (UObject & Object, UObject * InValue)
References Object.
StaticValue()
template<typename ValueType> TOptional< ValueType > FTrackInstancePropertyBindings::StaticValue (const UObject * Object, const FString & InPropertyPath) inline static
Static function for accessing a property value on an object without caching its address.
Parameters
Object The object to get the property from
InPropertyPath The path to the property to retrieve
Returns
(Optional) The current value of the property on the object
Definition at line 420 of file MovieSceneCommonHelpers.h.
References FTrackInstancePropertyBindings(), checkf, Object, ResolveProperty(), TEXT, TryGetPropertyValue(), and Value.
Referenced by UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::TDirectPropertyTraits< float >::GetObjectPropertyValue(), and UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue().
TryGetPropertyValue() [1/3]
template<> MOVIESCENE_API bool FTrackInstancePropertyBindings::TryGetPropertyValue (const FResolvedProperty & ResolvedProperty, bool & OutValue) static private
TryGetPropertyValue() [2/3]
template<> MOVIESCENE_API bool FTrackInstancePropertyBindings::TryGetPropertyValue (const FResolvedProperty & ResolvedProperty, UObject *& OutValue) static private
TryGetPropertyValue() [3/3]
template<typename ValueType> bool FTrackInstancePropertyBindings::TryGetPropertyValue (const FResolvedProperty & ResolvedProperty, ValueType & OutValue) inline static private
Definition at line 553 of file MovieSceneCommonHelpers.h.
References FTrackInstancePropertyBindings::FResolvedProperty::GetPropertyAddress(), and Value.
Referenced by GetCurrentValue(), GetOptionalValue(), and StaticValue().
Field Documentation
FunctionName
FName FTrackInstancePropertyBindings::FunctionName private
Name of the function to call to set values.
Definition at line 581 of file MovieSceneCommonHelpers.h.
NotifyFunctionName
FName FTrackInstancePropertyBindings::NotifyFunctionName private
Name of a function to call when a value has been set.
Definition at line 584 of file MovieSceneCommonHelpers.h.
PropertyName
FName FTrackInstancePropertyBindings::PropertyName private
Actual name of the property we are bound to.
Definition at line 587 of file MovieSceneCommonHelpers.h.
Referenced by FindPropertyAndArrayIndex(), and GetPropertyName().
PropertyPath
FString FTrackInstancePropertyBindings::PropertyPath private
Path to the property we are bound to.
Definition at line 578 of file MovieSceneCommonHelpers.h.
Referenced by GetPropertyPath().
RuntimeObjectToFunctionMap
TMap< FObjectKey, FResolvedPropertyAndFunction > FTrackInstancePropertyBindings::RuntimeObjectToFunctionMap private
Mapping of objects to bound functions that will be called to update data on the track.
Definition at line 575 of file MovieSceneCommonHelpers.h.
The documentation for this class was generated from the following file:
MovieSceneCommonHelpers.h