Unreal Engine 5.6 C++ API: FTextureLayout Class Reference
FTextureLayout Class Reference
An incremental texture space allocator.
#include "TextureLayout.h"
Data Structures
struct FTextureLayoutNode
Public Member Functions
FTextureLayout (uint32 InMinSizeX, uint32 InMinSizeY, uint32 MaxSizeX, uint32 MaxSizeY, bool bInPowerOfTwoSize=false, ETextureLayoutAspectRatio InAspect=ETextureLayoutAspectRatio::None, bool bInAlignByFour=true)
Minimal initialization constructor.
bool AddElement (uint32 &OutBaseX, uint32 &OutBaseY, uint32 ElementSizeX, uint32 ElementSizeY)
Finds a free area in the texture large enough to contain a surface with the given size.
uint32 GetSizeX () const
Returns the minimum texture width which will contain the allocated surfaces.
uint32 GetSizeY () const
Returns the minimum texture height which will contain the allocated surfaces.
bool RemoveElement (uint32 ElementBaseX, uint32 ElementBaseY, uint32 ElementSizeX, uint32 ElementSizeY)
Removes a previously allocated element from the layout and collapses the tree as much as possible, In order to create the largest free block possible and return the tree to its state before the element was added.
Private Member Functions
int32 AddSurfaceInner (int32 NodeIndex, uint32 ElementSizeX, uint32 ElementSizeY, bool bAllowTextureEnlargement)
Recursively traverses the tree depth first and searches for a large enough leaf node to contain the requested allocation.
int32 FindParentNode (int32 SearchNodeIndex)
Returns the index into Nodes of the parent node of SearchNode.
bool IsNodeUsed (int32 NodeIndex)
Returns true if the node or any of its children are marked used.
void RemoveChildren (int32 NodeIndex)
Recursively removes the children of a given node from the Nodes array and adjusts existing indices to compensate.
void UpdateSize (uint32 ElementMaxX, uint32 ElementMaxY)
Private Attributes
ETextureLayoutAspectRatio AspectRatio
bool bAlignByFour
bool bPowerOfTwoSize
uint32 MinSizeX
uint32 MinSizeY
TArray< FTextureLayoutNode, TInlineAllocator< 5 > > Nodes
uint32 SizeX
uint32 SizeY
Detailed Description
An incremental texture space allocator.
For best results, add the elements ordered descending in size.
Definition at line 23 of file TextureLayout.h.
Constructor & Destructor Documentation
FTextureLayout()
FTextureLayout::FTextureLayout (uint32 InMinSizeX, uint32 InMinSizeY, uint32 MaxSizeX, uint32 MaxSizeY, bool bInPowerOfTwoSize = false, ETextureLayoutAspectRatio InAspect = ETextureLayoutAspectRatio::None, bool bInAlignByFour = true) inline
Minimal initialization constructor.
Parameters
MinSizeX - The minimum width of the texture.
MinSizeY - The minimum height of the texture.
MaxSizeX - The maximum width of the texture.
MaxSizeY - The maximum height of the texture.
InPowerOfTwoSize - True if the texture size must be a power of two.
bInForce2To1Aspect - True if the texture size must have a 2:1 aspect.
bInAlignByFour - True if the texture size must be a multiple of 4..
Definition at line 37 of file TextureLayout.h.
References AspectRatio, bAlignByFour, bPowerOfTwoSize, IntCastChecked(), MinSizeX, MinSizeY, Nodes, None, SizeX, and SizeY.
Member Function Documentation
AddElement()
bool FTextureLayout::AddElement (uint32 & OutBaseX, uint32 & OutBaseY, uint32 ElementSizeX, uint32 ElementSizeY) inline
Finds a free area in the texture large enough to contain a surface with the given size.
If a large enough area is found, it is marked as in use, the output parameters OutBaseX and OutBaseY are set to the coordinates of the upper left corner of the free area and the function return true. Otherwise, the function returns false and OutBaseX and OutBaseY remain uninitialized.
Parameters
OutBaseX - If the function succeeds, contains the X coordinate of the upper left corner of the free area on return.
OutBaseY - If the function succeeds, contains the Y coordinate of the upper left corner of the free area on return.
ElementSizeX - The size of the surface to allocate in horizontal pixels.
ElementSizeY - The size of the surface to allocate in vertical pixels.
Returns
True if succeeded, false otherwise.
Definition at line 60 of file TextureLayout.h.
References AddSurfaceInner(), bAlignByFour, FTextureLayout::FTextureLayoutNode::bUsed, INDEX_NONE, FTextureLayout::FTextureLayoutNode::MinX, FTextureLayout::FTextureLayoutNode::MinY, Nodes, and UpdateSize().
AddSurfaceInner()
int32 FTextureLayout::AddSurfaceInner (int32 NodeIndex, uint32 ElementSizeX, uint32 ElementSizeY, bool bAllowTextureEnlargement) inline private
Recursively traverses the tree depth first and searches for a large enough leaf node to contain the requested allocation.
Definition at line 223 of file TextureLayout.h.
References AddSurfaceInner(), AspectRatio, bPowerOfTwoSize, FTextureLayout::FTextureLayoutNode::bUsed, checkNoEntry, checkSlow, FTextureLayout::FTextureLayoutNode::ChildA, FTextureLayout::FTextureLayoutNode::ChildB, Force2To1, ForceSquare, INDEX_NONE, IntCastChecked(), FMath::Max, FTextureLayout::FTextureLayoutNode::MinX, FTextureLayout::FTextureLayoutNode::MinY, Nodes, None, FTextureLayout::FTextureLayoutNode::SizeX, SizeX, FTextureLayout::FTextureLayoutNode::SizeY, and SizeY.
Referenced by AddElement(), and AddSurfaceInner().
FindParentNode()
int32 FTextureLayout::FindParentNode (int32 SearchNodeIndex) inline private
Returns the index into Nodes of the parent node of SearchNode.
Definition at line 399 of file TextureLayout.h.
References FTextureLayout::FTextureLayoutNode::ChildA, FTextureLayout::FTextureLayoutNode::ChildB, INDEX_NONE, and Nodes.
Referenced by RemoveElement().
GetSizeX()
uint32 FTextureLayout::GetSizeX () const inline
Returns the minimum texture width which will contain the allocated surfaces.
Definition at line 181 of file TextureLayout.h.
References SizeX.
GetSizeY()
uint32 FTextureLayout::GetSizeY () const inline
Returns the minimum texture height which will contain the allocated surfaces.
Definition at line 186 of file TextureLayout.h.
References SizeY.
IsNodeUsed()
bool FTextureLayout::IsNodeUsed (int32 NodeIndex) inline private
Returns true if the node or any of its children are marked used.
Definition at line 414 of file TextureLayout.h.
References checkSlow, INDEX_NONE, IsNodeUsed(), and Nodes.
Referenced by IsNodeUsed(), and RemoveElement().
RemoveChildren()
void FTextureLayout::RemoveChildren (int32 NodeIndex) inline private
Recursively removes the children of a given node from the Nodes array and adjusts existing indices to compensate.
Definition at line 426 of file TextureLayout.h.
References INDEX_NONE, Nodes, and RemoveChildren().
Referenced by RemoveChildren(), and RemoveElement().
RemoveElement()
bool FTextureLayout::RemoveElement (uint32 ElementBaseX, uint32 ElementBaseY, uint32 ElementSizeX, uint32 ElementSizeY) inline
Removes a previously allocated element from the layout and collapses the tree as much as possible, In order to create the largest free block possible and return the tree to its state before the element was added.
Returns
True if the element specified by the input parameters existed in the layout.
Definition at line 105 of file TextureLayout.h.
References bAlignByFour, FTextureLayout::FTextureLayoutNode::bUsed, FindParentNode(), INDEX_NONE, IsNodeUsed(), MinSizeX, MinSizeY, FTextureLayout::FTextureLayoutNode::MinX, FTextureLayout::FTextureLayoutNode::MinY, Nodes, RemoveChildren(), FTextureLayout::FTextureLayoutNode::SizeX, SizeX, FTextureLayout::FTextureLayoutNode::SizeY, SizeY, and UpdateSize().
UpdateSize()
void FTextureLayout::UpdateSize (uint32 ElementMaxX, uint32 ElementMaxY) inline private
Definition at line 367 of file TextureLayout.h.
References AspectRatio, bPowerOfTwoSize, checkNoEntry, Force2To1, ForceSquare, FMath::Max, None, SizeX, and SizeY.
Referenced by AddElement(), and RemoveElement().
Field Documentation
AspectRatio
ETextureLayoutAspectRatio FTextureLayout::AspectRatio private
Definition at line 217 of file TextureLayout.h.
Referenced by FTextureLayout(), AddSurfaceInner(), and UpdateSize().
bAlignByFour
bool FTextureLayout::bAlignByFour private
Definition at line 219 of file TextureLayout.h.
Referenced by FTextureLayout(), AddElement(), and RemoveElement().
bPowerOfTwoSize
bool FTextureLayout::bPowerOfTwoSize private
Definition at line 218 of file TextureLayout.h.
Referenced by FTextureLayout(), AddSurfaceInner(), and UpdateSize().
MinSizeX
uint32 FTextureLayout::MinSizeX private
Definition at line 213 of file TextureLayout.h.
Referenced by FTextureLayout(), and RemoveElement().
MinSizeY
uint32 FTextureLayout::MinSizeY private
Definition at line 214 of file TextureLayout.h.
Referenced by FTextureLayout(), and RemoveElement().
Nodes
TArray<FTextureLayoutNode,TInlineAllocator<5> > FTextureLayout::Nodes private
Definition at line 220 of file TextureLayout.h.
Referenced by FTextureLayout(), AddElement(), AddSurfaceInner(), FindParentNode(), IsNodeUsed(), RemoveChildren(), and RemoveElement().
SizeX
uint32 FTextureLayout::SizeX private
Definition at line 215 of file TextureLayout.h.
Referenced by FTextureLayout(), AddSurfaceInner(), GetSizeX(), RemoveElement(), and UpdateSize().
SizeY
uint32 FTextureLayout::SizeY private
Definition at line 216 of file TextureLayout.h.
Referenced by FTextureLayout(), AddSurfaceInner(), GetSizeY(), RemoveElement(), and UpdateSize().
The documentation for this class was generated from the following file:
TextureLayout.h