Unreal Engine 5.6 C++ Documentation: FHardwareDeviceIdentifier Struct Reference
FHardwareDeviceIdentifier Struct Reference
An identifier that can be used to determine what input devices are available based on the FInputDeviceScope.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputSettings.h>
Public Member Functions
FHardwareDeviceIdentifier ()
FHardwareDeviceIdentifier (const FName InClassName, const FName InHardwareDeviceIdentifier, EHardwareDevicePrimaryType InPrimaryType=EHardwareDevicePrimaryType::Unspecified, EHardwareDeviceSupportedFeatures::Type Flags=EHardwareDeviceSupportedFeatures::Unspecified)
bool HasAnySupportedFeatures (const EHardwareDeviceSupportedFeatures::Type FlagsToCheck) const
Returns true if this hardware device has ANY of the given supported feature flags.
bool HasAllSupportedFeatures (const EHardwareDeviceSupportedFeatures::Type FlagsToCheck) const
Returns true if this hardware device has ALL of the given supported feature flags.
bool IsValid () const
Returns true if this hardware device Identifier has valid names.
FString ToString () const
Returns a string containing the Input Class Name and HardwareDeviceIdentifier properties concatenated together.
bool operator== (const FHardwareDeviceIdentifier &Other) const
bool operator!= (const FHardwareDeviceIdentifier &Other) const
Public Attributes
FName InputClassName
The name of the Input Class that uses this hardware device.
FName HardwareDeviceIdentifier
The name of this hardware device.
EHardwareDevicePrimaryType PrimaryDeviceType
The generic type that this hardware identifies as.
int32 SupportedFeaturesMask
Flags that represent this hardware device's traits.
Static Public Attributes
static FHardwareDeviceIdentifier Invalid
An Invalid Hardware Device Identifier.
static FHardwareDeviceIdentifier DefaultKeyboardAndMouse
Hardware device ID that represents a keyboard and mouse.
static FHardwareDeviceIdentifier DefaultGamepad
Hardware device ID that represents a default, generic, gamepad.
static FHardwareDeviceIdentifier DefaultMobileTouch
Hardware device id that represents a default, generic, mobile touch input (tablet, phone, etc)
Friends
uint32 GetTypeHash (const FHardwareDeviceIdentifier &InDevice)
FArchive & operator<< (FArchive &Ar, FHardwareDeviceIdentifier &InDevice)
Detailed Description
An identifier that can be used to determine what input devices are available based on the FInputDeviceScope.
These mappings should match a FInputDeviceScope that is used by an IInputDevice
Definition at line 412 of file InputSettings.h.
Constructor & Destructor Documentation
FHardwareDeviceIdentifier() [1/2]
FHardwareDeviceIdentifier::FHardwareDeviceIdentifier ()
References FHardwareDeviceIdentifier().
FHardwareDeviceIdentifier() [2/2]
FHardwareDeviceIdentifier::FHardwareDeviceIdentifier (const FName InClassName, const FName InHardwareDeviceIdentifier, EHardwareDevicePrimaryType InPrimaryType = EHardwareDevicePrimaryType::Unspecified, EHardwareDeviceSupportedFeatures::Type Flags = EHardwareDeviceSupportedFeatures::Unspecified)
References EHardwareDevicePrimaryType, EHardwareDeviceSupportedFeatures, FHardwareDeviceIdentifier(), and Unspecified.
Member Function Documentation
HasAllSupportedFeatures()
bool FHardwareDeviceIdentifier::HasAllSupportedFeatures (const EHardwareDeviceSupportedFeatures::Type FlagsToCheck) const
Returns true if this hardware device has ALL of the given supported feature flags.
References EHardwareDeviceSupportedFeatures, and HasAllSupportedFeatures().
HasAnySupportedFeatures()
bool FHardwareDeviceIdentifier::HasAnySupportedFeatures (const EHardwareDeviceSupportedFeatures::Type FlagsToCheck) const
Returns true if this hardware device has ANY of the given supported feature flags.
References EHardwareDeviceSupportedFeatures, and HasAnySupportedFeatures().
IsValid()
bool FHardwareDeviceIdentifier::IsValid () const
Returns true if this hardware device Identifier has valid names.
References IsValid().
operator!=()
bool FHardwareDeviceIdentifier::operator!= (const FHardwareDeviceIdentifier & Other) const
References FHardwareDeviceIdentifier().
operator==()
bool FHardwareDeviceIdentifier::operator== (const FHardwareDeviceIdentifier & Other) const
References FHardwareDeviceIdentifier().
ToString()
FString FHardwareDeviceIdentifier::ToString () const
Returns a string containing the Input Class Name and HardwareDeviceIdentifier properties concatenated together.
References ToString().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FHardwareDeviceIdentifier & InDevice) friend
References FHardwareDeviceIdentifier(), and GetTypeHash.
operator<<
FArchive & operator<< (FArchive & Ar, FHardwareDeviceIdentifier & InDevice) friend
References FHardwareDeviceIdentifier().
Member Data Documentation
DefaultGamepad
FHardwareDeviceIdentifier FHardwareDeviceIdentifier::DefaultGamepad static
Hardware device ID that represents a default, generic, gamepad.
Definition at line 469 of file InputSettings.h.
DefaultKeyboardAndMouse
FHardwareDeviceIdentifier FHardwareDeviceIdentifier::DefaultKeyboardAndMouse static
Hardware device ID that represents a keyboard and mouse.
This is what will be set when an Input Event's FKey is not a gamepad key.
Definition at line 466 of file InputSettings.h.
DefaultMobileTouch
FHardwareDeviceIdentifier FHardwareDeviceIdentifier::DefaultMobileTouch static
Hardware device id that represents a default, generic, mobile touch input (tablet, phone, etc)
Definition at line 472 of file InputSettings.h.
HardwareDeviceIdentifier
FName FHardwareDeviceIdentifier::HardwareDeviceIdentifier
The name of this hardware device.
This should correspond with a FInputDeviceScope that is used by an IInputDevice
Definition at line 437 of file InputSettings.h.
InputClassName
FName FHardwareDeviceIdentifier::InputClassName
The name of the Input Class that uses this hardware device.
This should correspond with a FInputDeviceScope that is used by an IInputDevice
Definition at line 430 of file InputSettings.h.
Invalid
FHardwareDeviceIdentifier FHardwareDeviceIdentifier::Invalid static
An Invalid Hardware Device Identifier.
Definition at line 463 of file InputSettings.h.
PrimaryDeviceType
EHardwareDevicePrimaryType FHardwareDeviceIdentifier::PrimaryDeviceType
The generic type that this hardware identifies as.
This can be used to easily determine behaviors
Definition at line 441 of file InputSettings.h.
SupportedFeaturesMask
int32 FHardwareDeviceIdentifier::SupportedFeaturesMask
Flags that represent this hardware device's traits.
Definition at line 445 of file InputSettings.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputSettings.h