Unreal Engine 5.6 C++ API: TIndexedValuesChangeBuilder< ValueType, ChangeClassType > Class Template Reference
TIndexedValuesChangeBuilder< ValueType, ChangeClassType > Class Template Reference
TIndexedValuesChangeBuilder incrementally builds up a TIndexedValuesChange instance/subclass.
#include "IndexedAttributeChange.h"
Public Member Functions
TIndexedValuesChangeBuilder ()
void BeginNewChange ()
Allocate a new change and start tracking.
TUniquePtr< ChangeClassType > ExtractResult ()
Complete the change construction and return it.
void UpdateValue (int32 Index, const ValueType &OldValue, const ValueType &NewValue)
Modify the value at an Index.
void UpdateValues (const TArray< int32 > &Indices, const TArray< ValueType > &OldValues, const TArray< ValueType > &NewValues)
Modify a set of values.
Data Fields
TUniquePtr< ChangeClassType > Change
TMap< int32, int32 > SavedIndices
Detailed Description
template<typename ValueType, typename ChangeClassType>
class TIndexedValuesChangeBuilder< ValueType, ChangeClassType >
TIndexedValuesChangeBuilder incrementally builds up a TIndexedValuesChange instance/subclass.
The ChangeClassType template parameter should be the name of the TIndexedValuesChange-derived class.
Definition at line 40 of file IndexedAttributeChange.h.
Constructor & Destructor Documentation
TIndexedValuesChangeBuilder()
template<typename ValueType, typename ChangeClassType> TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::TIndexedValuesChangeBuilder () inline
Definition at line 46 of file IndexedAttributeChange.h.
Member Function Documentation
BeginNewChange()
template<typename ValueType, typename ChangeClassType> void TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::BeginNewChange () inline
Allocate a new change and start tracking.
Definition at line 51 of file IndexedAttributeChange.h.
References Change, MakeUnique(), and SavedIndices.
ExtractResult()
template<typename ValueType, typename ChangeClassType> TUniquePtr< ChangeClassType > TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::ExtractResult () inline
Complete the change construction and return it.
Definition at line 87 of file IndexedAttributeChange.h.
References Change, and MoveTemp().
UpdateValue()
template<typename ValueType, typename ChangeClassType> void TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::UpdateValue (int32 Index, const ValueType & OldValue, const ValueType & NewValue) inline
Modify the value at an Index.
Changes will be tracked as necessary.
Definition at line 58 of file IndexedAttributeChange.h.
References Change, check, and SavedIndices.
Referenced by UpdateValues().
UpdateValues()
template<typename ValueType, typename ChangeClassType> void TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::UpdateValues (const TArray< int32 > & Indices, const TArray< ValueType > & OldValues, const TArray< ValueType > & NewValues) inline
Modify a set of values.
Definition at line 77 of file IndexedAttributeChange.h.
References TArray< InElementType, InAllocatorType >::Num(), and UpdateValue().
Field Documentation
Change
template<typename ValueType, typename ChangeClassType> TUniquePtr<ChangeClassType> TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::Change
Definition at line 43 of file IndexedAttributeChange.h.
Referenced by BeginNewChange(), ExtractResult(), and UpdateValue().
SavedIndices
template<typename ValueType, typename ChangeClassType> TMap<int32, int32> TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::SavedIndices
Definition at line 44 of file IndexedAttributeChange.h.
Referenced by BeginNewChange(), and UpdateValue().
The documentation for this class was generated from the following file:
IndexedAttributeChange.h