Unreal Engine 5.6 C++ API: UE::MovieScene::FEntityFactories Struct Reference
UE::MovieScene::FEntityFactories Struct Reference
A class that contains all the component factory relationships.
#include "MovieSceneEntityFactory.h"
Public Member Functions
MOVIESCENE_API int32 ComputeChildComponents (const FComponentMask &ParentComponentMask, FComponentMask &ChildComponentMask)
Given a set of components on a parent entity, compute what components should exist on a child entity.
MOVIESCENE_API int32 ComputeMutuallyInclusiveComponents (EMutuallyInclusiveComponentType MutualTypes, FComponentMask &ComponentMask, FMutualComponentInitializers &OutInitializers)
Given a set of components on an entity, computes what other components should also exist on this entity.
template<typename ComponentType>
void ConditionallyDuplicateChildComponent (TComponentTypeID< ComponentType > InComponent, FComponentMask InParentComponentMask)
Makes the given component automatically copied from a parent entity to all its children entities, but only if the parent entity passes the given InParentComponentMask.
void DefineChildComponent (FComponentTypeID InChildComponent)
Defines a component as something that should always be created on every child entity.
void DefineChildComponent (FComponentTypeID InParentComponent, FComponentTypeID InChildComponent)
Specifies that if a component is present on a parent entity, the given child component should be created on any child entity.
template<typename ParentComponent, typename ChildComponent, typename InitializerCallback>
void DefineChildComponent (TComponentTypeID< ParentComponent > InParentType, TComponentTypeID< ChildComponent > InChildType, InitializerCallback &&InInitializer)
Specifies that if a component is present on a parent entity, the given child component should be created on any child entity, and initialized with the given initializer.
MOVIESCENE_API void DefineChildComponent (TInlineValue< FChildEntityInitializer > &&InInitializer)
Adds the definition for a child component.
MOVIESCENE_API void DefineComplexInclusiveComponents (const FComplexInclusivityFilter &InFilter, FComponentTypeID InComponent)
Specifies that if an entity matches the given filter, the specified component should be created on it.
MOVIESCENE_API void DefineComplexInclusiveComponents (const FComplexInclusivityFilter &InFilter, std::initializer_list< FComponentTypeID > InComponents, FMutuallyInclusiveComponentParams &&Params)
Specifies that if an entity matches the given filter, the specified components should be created on it.
void DefineMutuallyInclusiveComponent (FComponentTypeID InComponentA, FComponentTypeID InComponentB)
Indicates that if the first component exists on an entity, the second component should be created on that entity too.
MOVIESCENE_API void DefineMutuallyInclusiveComponents (FComponentTypeID InComponentA, std::initializer_list< FComponentTypeID > InMutualComponents)
Indicates that if the first component exists on an entity, the specified components should be created on that entity too.
MOVIESCENE_API void DefineMutuallyInclusiveComponents (FComponentTypeID InComponentA, std::initializer_list< FComponentTypeID > InMutualComponents, FMutuallyInclusiveComponentParams &&Params)
Specifies a mutual inclusivity relationship along with a custom initializer for initializing the mutual component(s)
template<typename ComponentType>
void DuplicateChildComponent (TComponentTypeID< ComponentType > InComponent)
Makes the given component automatically copied from a parent entity to all its children entities.
MOVIESCENE_API void RunInitializers (const FComponentMask &ParentType, const FComponentMask &ChildType, const FEntityAllocation *ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets, const FEntityRange &InChildEntityRange)
Private Attributes
TArray< TInlineValue< FChildEntityInitializer > > ChildInitializers
UE::MovieScene::FMutualInclusivityGraph MutualInclusivityGraph
TMultiMap< FComponentTypeID, FComponentTypeID > ParentToChildComponentTypes
Detailed Description
A class that contains all the component factory relationships.
A source component (imported from an entity provider) can trigger the creation of other components on the same entity or on children entities of its entity.
Definition at line 39 of file MovieSceneEntityFactory.h.
Member Function Documentation
ComputeChildComponents()
MOVIESCENE_API int32 UE::MovieScene::FEntityFactories::ComputeChildComponents (const FComponentMask & ParentComponentMask, FComponentMask & ChildComponentMask)
Given a set of components on a parent entity, compute what components should exist on a child entity.
This resolves all the parent-to-child relationships.
ComputeMutuallyInclusiveComponents()
MOVIESCENE_API int32 UE::MovieScene::FEntityFactories::ComputeMutuallyInclusiveComponents (EMutuallyInclusiveComponentType MutualTypes, FComponentMask & ComponentMask, FMutualComponentInitializers & OutInitializers)
Given a set of components on an entity, computes what other components should also exist on this entity.
This resolves all the mutual and complex inclusivity relationships.
ConditionallyDuplicateChildComponent()
template<typename ComponentType> void UE::MovieScene::FEntityFactories::ConditionallyDuplicateChildComponent (TComponentTypeID< ComponentType > InComponent, FComponentMask InParentComponentMask) inline
Makes the given component automatically copied from a parent entity to all its children entities, but only if the parent entity passes the given InParentComponentMask.
Note
: include "EntitySystem/MovieSceneEntityFactoryTemplates.h" for definition
Definition at line 181 of file MovieSceneEntityFactoryTemplates.h.
References DefineChildComponent().
DefineChildComponent() [1/4]
void UE::MovieScene::FEntityFactories::DefineChildComponent (FComponentTypeID InChildComponent) inline
Defines a component as something that should always be created on every child entity.
Definition at line 44 of file MovieSceneEntityFactory.h.
References UE::MovieScene::FComponentTypeID::Invalid(), and ParentToChildComponentTypes.
Referenced by ConditionallyDuplicateChildComponent(), DefineChildComponent(), and DuplicateChildComponent().
DefineChildComponent() [2/4]
void UE::MovieScene::FEntityFactories::DefineChildComponent (FComponentTypeID InParentComponent, FComponentTypeID InChildComponent) inline
Specifies that if a component is present on a parent entity, the given child component should be created on any child entity.
Definition at line 53 of file MovieSceneEntityFactory.h.
References ParentToChildComponentTypes.
DefineChildComponent() [3/4]
template<typename ParentComponent, typename ChildComponent, typename InitializerCallback> void UE::MovieScene::FEntityFactories::DefineChildComponent (TComponentTypeID< ParentComponent > InParentType, TComponentTypeID< ChildComponent > InChildType, InitializerCallback && InInitializer) inline
Specifies that if a component is present on a parent entity, the given child component should be created on any child entity, and initialized with the given initializer.
Note
: include "EntitySystem/MovieSceneEntityFactoryTemplates.h" for definition
Definition at line 187 of file MovieSceneEntityFactoryTemplates.h.
References ChildInitializers, DefineChildComponent(), and Forward().
DefineChildComponent() [4/4]
MOVIESCENE_API void UE::MovieScene::FEntityFactories::DefineChildComponent (TInlineValue< FChildEntityInitializer > && InInitializer)
Adds the definition for a child component.
The helper methods above are easier and preferrable.
DefineComplexInclusiveComponents() [1/2]
MOVIESCENE_API void UE::MovieScene::FEntityFactories::DefineComplexInclusiveComponents (const FComplexInclusivityFilter & InFilter, FComponentTypeID InComponent)
Specifies that if an entity matches the given filter, the specified component should be created on it.
DefineComplexInclusiveComponents() [2/2]
MOVIESCENE_API void UE::MovieScene::FEntityFactories::DefineComplexInclusiveComponents (const FComplexInclusivityFilter & InFilter, std::initializer_list< FComponentTypeID > InComponents, FMutuallyInclusiveComponentParams && Params)
Specifies that if an entity matches the given filter, the specified components should be created on it.
References Params.
DefineMutuallyInclusiveComponent()
void UE::MovieScene::FEntityFactories::DefineMutuallyInclusiveComponent (FComponentTypeID InComponentA, FComponentTypeID InComponentB) inline
Indicates that if the first component exists on an entity, the second component should be created on that entity too.
Note
: the inverse is not implied (ie B can still exist without A)
Definition at line 92 of file MovieSceneEntityFactory.h.
References DefineMutuallyInclusiveComponents().
DefineMutuallyInclusiveComponents() [1/2]
MOVIESCENE_API void UE::MovieScene::FEntityFactories::DefineMutuallyInclusiveComponents (FComponentTypeID InComponentA, std::initializer_list< FComponentTypeID > InMutualComponents)
Indicates that if the first component exists on an entity, the specified components should be created on that entity too.
Note
: the inverse is not implied (ie B can still exist without A)
Referenced by DefineMutuallyInclusiveComponent().
DefineMutuallyInclusiveComponents() [2/2]
MOVIESCENE_API void UE::MovieScene::FEntityFactories::DefineMutuallyInclusiveComponents (FComponentTypeID InComponentA, std::initializer_list< FComponentTypeID > InMutualComponents, FMutuallyInclusiveComponentParams && Params)
Specifies a mutual inclusivity relationship along with a custom initializer for initializing the mutual component(s)
References Params.
DuplicateChildComponent()
template<typename ComponentType> void UE::MovieScene::FEntityFactories::DuplicateChildComponent (TComponentTypeID< ComponentType > InComponent) inline
Makes the given component automatically copied from a parent entity to all its children entities.
Note
: include "EntitySystem/MovieSceneEntityFactoryTemplates.h" for definition
Definition at line 175 of file MovieSceneEntityFactoryTemplates.h.
References DefineChildComponent().
RunInitializers()
MOVIESCENE_API void UE::MovieScene::FEntityFactories::RunInitializers (const FComponentMask & ParentType, const FComponentMask & ChildType, const FEntityAllocation * ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets, const FEntityRange & InChildEntityRange)
Field Documentation
ChildInitializers
TArray<TInlineValue<FChildEntityInitializer> > UE::MovieScene::FEntityFactories::ChildInitializers private
Definition at line 138 of file MovieSceneEntityFactory.h.
Referenced by DefineChildComponent().
MutualInclusivityGraph
UE::MovieScene::FMutualInclusivityGraph UE::MovieScene::FEntityFactories::MutualInclusivityGraph private
Definition at line 140 of file MovieSceneEntityFactory.h.
ParentToChildComponentTypes
TMultiMap<FComponentTypeID, FComponentTypeID> UE::MovieScene::FEntityFactories::ParentToChildComponentTypes private
Definition at line 139 of file MovieSceneEntityFactory.h.
Referenced by DefineChildComponent(), and DefineChildComponent().
The documentation for this struct was generated from the following files:
MovieSceneEntityFactory.h
MovieSceneEntityFactoryTemplates.h