Unreal Engine 5.6 C++ API: GameplayCue_Types.h File Reference
GameplayCue_Types.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "GameplayTagContainer.h"
#include "GameplayEffectTypes.h"
#include "GameplayPrediction.h"
#include "UObject/ObjectKey.h"
#include "GameplayEffect.h"
#include "GameplayCue_Types.generated.h"
Data Structures
struct FScopedGameplayCueSendContext
FScopedGameplayCueSendContext Add this around code that sends multiple gameplay cues to allow grouping them into a smalkler number of cues for more efficient networking.
Functions
DECLARE_MULTICAST_DELEGATE (FOnGameplayCueNotifyChange)
Delegate for when GC notifies are added or removed from manager.
PRAGMA_DISABLE_DEPRECATION_WARNINGS FORCEINLINE uint32 GetTypeHash (const FGCNotifyActorKey &Key)
struct UE_DEPRECATED (5.3, "Look at FGCNotifyActorKey constructor notes for upgrade steps.") FGCNotifyActorKey
Struct that is used by the gameplaycue manager to tie an instanced gameplaycue to the calling gamecode.
UENUM() enum class EGameplayCuePayloadType USTRUCT () struct FGameplayCuePendingExecute
Describes what type of payload is attached to a cue execution, we only replicate what is needed.
Function Documentation
DECLARE_MULTICAST_DELEGATE()
DECLARE_MULTICAST_DELEGATE (FOnGameplayCueNotifyChange)
Delegate for when GC notifies are added or removed from manager.
GetTypeHash()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FORCEINLINE uint32 GetTypeHash (const FGCNotifyActorKey & Key)
Definition at line 127 of file GameplayCue_Types.h.
References FORCEINLINE, GetTypeHash(), and Key.
Referenced by UE::AnimNext::FEvaluationVMStackName::FEvaluationVMStackName(), TraceServices::TCachedStringStore< WIDECHAR >::TCachedStringStore(), FPersistentStorageCategory::AddOrUpdateFile(), FHashBuilder::Append(), FHashBuilder::AppendRaw(), FShaderCompilerDefinitions::Contains(), RigVMTypeUtils::CPPTypeFromEnum(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_STATS_GROUP(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::FindCell(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::FindCellMutable(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::FindOrAddCell(), FShaderCompilerDefinitions::FindOrAddMapIndex(), FShaderCompilerDefinitions::FindOrAddMapIndex(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), UE::AnimNext::FExecutionContext::GetComponent(), FRigVMCallstack::GetEntryTypeHash(), FLinkerLoad::GetHashBucket(), FShaderCompilerDefinitions::GetIntegerValue(), FShaderCompilerDefinitions::GetIntegerValue(), DefaultKeyComparer< KeyType >::GetKeyHash(), DefaultKeyFuncs< FCurveEditorTreeItemID >::GetKeyHash(), DefaultKeyFuncs< FCurveEditorTreeItemID >::GetKeyHash(), Experimental::TSherwoodHashKeyFuncs< KeyType, ValueType >::GetKeyHash(), FApplePlatformSymbolDatabaseKeyFuncs::GetKeyHash(), FCachedLandscapeFoliage::FGrassCompKeyFuncs::GetKeyHash(), FDelinquencyKeyFuncs::GetKeyHash(), FGenericPlatformSymbolDatabaseKeyFuncs::GetKeyHash(), FMovieSceneEvaluationFieldEntityKeyFuncs::GetKeyHash(), FNetworkObjectInfo::FNetConnectionKeyFuncs::GetKeyHash(), FNetworkObjectKeyFuncs::GetKeyHash(), FNetworkObjectList::FSubObjectChannelRefKeyFuncs::GetKeyHash(), FSlateFontKeyFuncs< ValueType >::GetKeyHash(), KeyInitType< KeyType, ValueType, bInAllowDuplicateKeys >::GetKeyHash(), KeyInitType< KeyType, ValueType, bInAllowDuplicateKeys >::GetKeyHash(), TPropertyPathMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::GetKeyHash(), TWeakFieldPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::GetKeyHash(), FManagedStorageFileLockRegistry::GetLock(), ObjectPtr_Private::Friend::GetPtrTypeHash(), FAssetThumbnailPool::FThumbId::GetTypeHash, FCurveEditorToolID::GetTypeHash, FCurveModelID::GetTypeHash, FEdGraphNodeHandle::GetTypeHash, FEdGraphPinHandle::GetTypeHash, FGraphPinHandle::GetTypeHash, FRigVMASTProxy::GetTypeHash, FRigVMCompilerWorkData::FFunctionRegisterData::GetTypeHash, GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), GetTypeHash(), Metasound::Frontend::FGraphClassRegistryKey::GetTypeHash, UE::MovieScene::FEntityGroupID::GetTypeHash, UE::MovieScene::FEntityGroupingPolicyKey::GetTypeHash, UE::MovieScene::FObjectComponent::GetTypeHash, UE::Tick::FSyncPointId::GetTypeHash, TProperty_Numeric< InTCppType >::GetValueTypeHashInternal(), FRandomStream::Initialize(), UE::MediaIO::LogThrottle(), FShaderCompileJobKey::MakeHash(), FShaderPipelineCompileJobKey::MakeHash(), UE::UnifiedError::FErrorRegistry::RegisterModule(), FManagedStorageFileLockRegistry::ReleaseLock(), SHADER_PARAMETER_TEXTURE(), TraceServices::TCachedStringStore< WIDECHAR >::StoreInternal(), UE::AnimNext::FExecutionContext::TryGetComponent(), UE_DEPRECATED(), UE_DEPRECATED(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
UE_DEPRECATED()
struct UE_DEPRECATED (5. 3, "Look at FGCNotifyActorKey constructor notes for upgrade steps.")
Struct that is used by the gameplaycue manager to tie an instanced gameplaycue to the calling gamecode.
Usually this is just the target actor, but can also be unique per instigator/sourceobject
Definition at line 72 of file GameplayCue_Types.h.
References GENERATED_USTRUCT_BODY, transient, UPROPERTY, and USTRUCT.
USTRUCT()
UENUM() enum class EGameplayCuePayloadType USTRUCT ()
Describes what type of payload is attached to a cue execution, we only replicate what is needed.
Struct for pooling and preallocating gameplaycuenotify_actor classes.
Structure to keep track of pending gameplay cues that haven't been applied yet.
This data is per world and used to track what actors are available to recycle and which classes need to preallocate instances of those actors
List of tags, we allocate one as there is almost always exactly one tag
Prediction key that spawned this cue
What type of payload is attached to this cue
What component to send the cue on
If this cue is from a spec, here's the copy of that spec
Store the full cue parameters or just the effect context depending on type
Raw list of pooled instances. This relies on NotifyGameplayCueActorEndPlay always being called when actor is destroyed
List of classes that will be pooled
World that owns this list
Definition at line 31 of file GameplayCue_Types.h.
References GENERATED_USTRUCT_BODY, and UPROPERTY.