Unreal Engine 5.6 C++ API: FAsyncBufferFillData Struct Reference
FAsyncBufferFillData Struct Reference
#include "ParticleHelper.h"
Public Member Functions
FAsyncBufferFillData ()
Constructor, just zeros everything.
~FAsyncBufferFillData ()
Destructor, frees memory and zeros everything.
Data Fields
void * DynamicParameterData
Pointer to dynamic parameter data.
int32 IndexCount
Number of indices in IndexData.
void * IndexData
Pointer to index data.
FMatrix LocalToWorld
Local to world transform.
int32 OutTriangleCount
Number of triangles filled in.
int32 VertexCount
Number of verts in VertexData.
void * VertexData
Pointer to vertex data.
int32 VertexSize
Stride of verts, used only for error checking.
const FSceneView * View
View for this buffer fill task.
FMatrix WorldToLocal
World to local transform.
Detailed Description
Definition at line 1069 of file ParticleHelper.h.
Constructor & Destructor Documentation
FAsyncBufferFillData()
FAsyncBufferFillData::FAsyncBufferFillData () inline
Constructor, just zeros everything.
Definition at line 1093 of file ParticleHelper.h.
References FAsyncBufferFillData(), and FMemory::Memzero().
Referenced by FAsyncBufferFillData(), and ~FAsyncBufferFillData().
~FAsyncBufferFillData()
FAsyncBufferFillData::~FAsyncBufferFillData () inline
Destructor, frees memory and zeros everything.
Definition at line 1099 of file ParticleHelper.h.
References FAsyncBufferFillData(), and FMemory::Memzero().
Field Documentation
DynamicParameterData
void* FAsyncBufferFillData::DynamicParameterData
Pointer to dynamic parameter data.
Definition at line 1090 of file ParticleHelper.h.
IndexCount
int32 FAsyncBufferFillData::IndexCount
Number of indices in IndexData.
Definition at line 1084 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData::DoBufferFill().
IndexData
void* FAsyncBufferFillData::IndexData
Pointer to index data.
Definition at line 1086 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData::DoBufferFill().
LocalToWorld
FMatrix FAsyncBufferFillData::LocalToWorld
Local to world transform.
Definition at line 1072 of file ParticleHelper.h.
OutTriangleCount
int32 FAsyncBufferFillData::OutTriangleCount
Number of triangles filled in.
Definition at line 1088 of file ParticleHelper.h.
VertexCount
int32 FAsyncBufferFillData::VertexCount
Number of verts in VertexData.
Definition at line 1078 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData::DoBufferFill().
VertexData
void* FAsyncBufferFillData::VertexData
Pointer to vertex data.
Definition at line 1082 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData::DoBufferFill().
VertexSize
int32 FAsyncBufferFillData::VertexSize
Stride of verts, used only for error checking.
Definition at line 1080 of file ParticleHelper.h.
View
const FSceneView* FAsyncBufferFillData::View
View for this buffer fill task.
Definition at line 1076 of file ParticleHelper.h.
WorldToLocal
FMatrix FAsyncBufferFillData::WorldToLocal
World to local transform.
Definition at line 1074 of file ParticleHelper.h.
The documentation for this struct was generated from the following file:
ParticleHelper.h