Unreal Engine 5.6 C++ API: FInstanceSceneShaderData Struct Reference
FInstanceSceneShaderData Struct Reference
#include "InstanceUniformShaderParameters.h"
Public Member Functions
FInstanceSceneShaderData ()
void Build (uint32 PrimitiveId, uint32 RelativeId, uint32 InstanceFlags, uint32 LastUpdateFrame, uint32 CustomDataCount, float RandomID, bool bIsVisible=true)
void Build (uint32 PrimitiveId, uint32 RelativeId, uint32 InstanceFlags, uint32 LastUpdateFrame, uint32 CustomDataCount, float RandomID, const FRenderTransform &LocalToPrimitive, const FRenderTransform &PrimitiveToWorld, bool bIsVisible=true)
FORCEINLINE void BuildInternal (uint32 PrimitiveId, uint32 RelativeId, uint32 InstanceFlags, uint32 LastUpdateFrame, uint32 CustomDataCount, float RandomID, const FRenderTransform &LocalToWorld, bool bIsVisible, bool bSupportsCompressedTransforms)
Static Public Member Functions
static uint32 GetDataStrideInFloat4s ()
static uint32 GetEffectiveNumBytes ()
static bool SupportsCompressedTransforms ()
Data Fields
TStaticArray< FVector4f, UnCompressedTransformDataStrideInFloat4s > Data
Static Private Attributes
static constexpr uint32 CompressedTransformDataStrideInFloat4s = 3
static constexpr uint32 UnCompressedTransformDataStrideInFloat4s = 4
Detailed Description
Definition at line 69 of file InstanceUniformShaderParameters.h.
Constructor & Destructor Documentation
FInstanceSceneShaderData()
FInstanceSceneShaderData::FInstanceSceneShaderData () inline
Definition at line 87 of file InstanceUniformShaderParameters.h.
References Data, InPlace, and NoInit.
Member Function Documentation
Build() [1/2]
void FInstanceSceneShaderData::Build (uint32 PrimitiveId, uint32 RelativeId, uint32 InstanceFlags, uint32 LastUpdateFrame, uint32 CustomDataCount, float RandomID, bool bIsVisible = true)
Build() [2/2]
void FInstanceSceneShaderData::Build (uint32 PrimitiveId, uint32 RelativeId, uint32 InstanceFlags, uint32 LastUpdateFrame, uint32 CustomDataCount, float RandomID, const FRenderTransform & LocalToPrimitive, const FRenderTransform & PrimitiveToWorld, bool bIsVisible = true)
BuildInternal()
FORCEINLINE void FInstanceSceneShaderData::BuildInternal (uint32 PrimitiveId, uint32 RelativeId, uint32 InstanceFlags, uint32 LastUpdateFrame, uint32 CustomDataCount, float RandomID, const FRenderTransform & LocalToWorld, bool bIsVisible, bool bSupportsCompressedTransforms) inline
Definition at line 115 of file InstanceUniformShaderParameters.h.
References checkSlow, Data, FORCEINLINE, FCompressedTransform::Rotation, FRenderTransform::RotDeterminant(), FRenderTransform::To3x4MatrixTranspose(), and FCompressedTransform::Translation.
GetDataStrideInFloat4s()
uint32 FInstanceSceneShaderData::GetDataStrideInFloat4s () static
Referenced by GetEffectiveNumBytes().
GetEffectiveNumBytes()
uint32 FInstanceSceneShaderData::GetEffectiveNumBytes () inline static
Definition at line 82 of file InstanceUniformShaderParameters.h.
References GetDataStrideInFloat4s().
SupportsCompressedTransforms()
bool FInstanceSceneShaderData::SupportsCompressedTransforms () static
Field Documentation
CompressedTransformDataStrideInFloat4s
uint32 FInstanceSceneShaderData::CompressedTransformDataStrideInFloat4s = 3 static constexpr private
Definition at line 74 of file InstanceUniformShaderParameters.h.
Data
TStaticArray<FVector4f, UnCompressedTransformDataStrideInFloat4s> FInstanceSceneShaderData::Data
Definition at line 172 of file InstanceUniformShaderParameters.h.
Referenced by FInstanceSceneShaderData(), and BuildInternal().
UnCompressedTransformDataStrideInFloat4s
uint32 FInstanceSceneShaderData::UnCompressedTransformDataStrideInFloat4s = 4 static constexpr private
Definition at line 75 of file InstanceUniformShaderParameters.h.
The documentation for this struct was generated from the following file:
InstanceUniformShaderParameters.h