Unreal Engine 5.6 C++ API: TTypeContainer< Mode >::TThreadInstanceProvider< T > Struct Template Reference
TTypeContainer< Mode >::TThreadInstanceProvider< T > Struct Template Reference
Implements an instance provider that returns the same instance per thread.
Public Types
typedef TTlsAutoCleanupValue< TSharedPtr< T, Mode > > TlsValueType
Public Member Functions
TThreadInstanceProvider (TFunction< TSharedPtr< void, Mode >()> &&InCreateFunc)
virtual ~TThreadInstanceProvider () override
virtual TSharedPtr< void, Mode > GetInstance () override
Gets an instance of a class.
Public Member Functions inherited from TTypeContainer< Mode >::FThreadInstanceProvider
FThreadInstanceProvider (TFunction< TSharedPtr< void, Mode >()> &&InCreateFunc)
virtual ~FThreadInstanceProvider () override
Public Member Functions inherited from TTypeContainer< Mode >::IInstanceProvider
virtual ~IInstanceProvider ()
Virtual destructor.
Additional Inherited Members
Data Fields inherited from TTypeContainer< Mode >::FThreadInstanceProvider
TFunction< TSharedPtr< void, Mode >()> CreateFunc
uint32 TlsSlot
Detailed Description
template<ESPMode Mode = ESPMode::ThreadSafe>
template<class T>
struct TTypeContainer< Mode >::TThreadInstanceProvider< T >
Implements an instance provider that returns the same instance per thread.
Definition at line 145 of file TypeContainer.h.
Member Typedef Documentation
TlsValueType
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> typedef TTlsAutoCleanupValue<TSharedPtr<T, Mode> > TTypeContainer< Mode >::TThreadInstanceProvider< T >::TlsValueType
Definition at line 148 of file TypeContainer.h.
Constructor & Destructor Documentation
TThreadInstanceProvider()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> TTypeContainer< Mode >::TThreadInstanceProvider< T >::TThreadInstanceProvider (TFunction< TSharedPtr< void, Mode >()> && InCreateFunc) inline
Definition at line 150 of file TypeContainer.h.
References TTypeContainer< Mode >::FThreadInstanceProvider::FThreadInstanceProvider(), and MoveTemp().
~TThreadInstanceProvider()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> virtual TTypeContainer< Mode >::TThreadInstanceProvider< T >::~TThreadInstanceProvider () inline override virtual
Definition at line 154 of file TypeContainer.h.
Member Function Documentation
GetInstance()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class T> virtual TSharedPtr< void, Mode > TTypeContainer< Mode >::TThreadInstanceProvider< T >::GetInstance () inline override virtual
Gets an instance of a class.
Returns
Shared pointer to the instance (must be cast to TSharedPtr<R, Mode>).
Implements TTypeContainer< Mode >::IInstanceProvider.
Definition at line 156 of file TypeContainer.h.
References TTypeContainer< Mode >::FThreadInstanceProvider::CreateFunc, FAndroidTLS::GetTlsValue(), FAndroidTLS::SetTlsValue(), StaticCastSharedPtr(), and TTypeContainer< Mode >::FThreadInstanceProvider::TlsSlot.
The documentation for this struct was generated from the following file:
TypeContainer.h