Unreal Engine 5.6 C++ API: MIR::FEmitter Class Reference
MIR::FEmitter Class Reference
#include "MaterialIREmitter.h"
Data Structures
struct FValueKeyFuncs
Public Member Functions
FValueRef Abs (FValueRef A)
FValueRef ACos (FValueRef A)
FValueRef ACosh (FValueRef A)
FValueRef Add (FValueRef A, FValueRef B)
FValueRef AnalyticalPartialDerivative (FValueRef Value, EDerivativeAxis Axis)
FValueRef And (FValueRef A, FValueRef B)
FValueRef ASin (FValueRef A)
FValueRef ASinh (FValueRef A)
FValueRef ATan (FValueRef A)
FValueRef ATanh (FValueRef A)
FValueRef BitShiftLeft (FValueRef A, FValueRef B)
FValueRef BitShiftRight (FValueRef A, FValueRef B)
FValueRef BitwiseAnd (FValueRef A, FValueRef B)
FValueRef BitwiseNot (FValueRef A)
FValueRef BitwiseOr (FValueRef A, FValueRef B)
FValueRef Branch (FValueRef Condition, FValueRef True, FValueRef False)
FValueRef Cast (FValueRef Value, const FType *TargetType)
FValueRef CastToBool (FValueRef Value, int NumRows)
FValueRef CastToFloat (FValueRef Value, int NumRows)
FValueRef CastToInt (FValueRef Value, int NumRows)
FValueRef CastToScalar (FValueRef Value)
FValueRef Ceil (FValueRef A)
FValueRef CheckIsArithmetic (FValueRef Value)
FValueRef CheckIsInteger (FValueRef Value)
FValueRef CheckIsPrimitive (FValueRef Value)
FValueRef CheckIsScalar (FValueRef Value)
FValueRef CheckIsScalarOrVector (FValueRef Value)
FValueRef CheckIsTexture (FValueRef Value)
FValueRef CheckTypeIsKind (FValueRef Value, ETypeKind Kind)
FValueRef Clamp (FValueRef A, FValueRef B, FValueRef C)
FValueRef ConstantBool (bool InX)
FValueRef ConstantFalse ()
FValueRef ConstantFloat (TFloat InX)
FValueRef ConstantFloat2 (UE::Math::TVector2< TFloat > InValue)
FValueRef ConstantFloat3 (UE::Math::TVector< TFloat > InValue)
FValueRef ConstantFloat4 (UE::Math::TVector4< TFloat > InValue)
FValueRef ConstantFromShaderValue (const UE::Shader::FValue &InValue)
FValueRef ConstantInt (TInteger InX)
FValueRef ConstantInt2 (UE::Math::TIntVector2< TInteger > InValue)
FValueRef ConstantInt3 (UE::Math::TIntVector3< TInteger > InValue)
FValueRef ConstantInt4 (UE::Math::TIntVector4< TInteger > InValue)
FValueRef ConstantOne (EScalarKind Kind)
FValueRef ConstantScalar (EScalarKind Kind, TFloat FromFloat)
FValueRef ConstantTrue ()
FValueRef ConstantZero (EScalarKind Kind)
FValueRef Cos (FValueRef A)
FValueRef Cosh (FValueRef A)
FValueRef Cross (FValueRef A, FValueRef B)
bool CurrentExpressionHasErrors () const
FValueRef CustomPrimitiveData (uint32 PrimitiveDataIndex)
FValueRef Divide (FValueRef A, FValueRef B)
FValueRef Dot (FValueRef A, FValueRef B)
FValueRef Equals (FValueRef A, FValueRef B)
void Error (FStringView Message)
void Error (FValueRef Source, FStringView Message)
template<typename... TArgs>
void Errorf (FValueRef Source, UE::Core::TCheckedFormatString< FString::FmtCharType, TArgs... > Format, TArgs... Args)
template<typename... TArgs>
void Errorf (UE::Core::TCheckedFormatString< FString::FmtCharType, TArgs... > Format, TArgs... Args)
FValueRef Exponential (FValueRef A)
FValueRef Exponential2 (FValueRef A)
FValueRef ExternalInput (EExternalInput Id)
FValueRef Floor (FValueRef A)
FValueRef Fmod (FValueRef A, FValueRef B)
FValueRef Frac (FValueRef A)
const FType * GetCommonType (const FType *A, const FType *B)
FValueRef GreaterThan (FValueRef A, FValueRef B)
FValueRef GreaterThanOrEquals (FValueRef A, FValueRef B)
FValueRef InlineHLSL (const FMaterialExternalCodeDeclaration *InExternalCodeDeclaration, TConstArrayView< FValueRef > InputValues, EValueFlags ValueFlags=EValueFlags::None, EGraphProperties UsedGraphProperties=EGraphProperties::None)
FValueRef InlineHLSL (const FType *Type, FString Code, TConstArrayView< FValueRef > InputValues, EValueFlags ValueFlags=EValueFlags::None, EGraphProperties UsedGraphProperties=EGraphProperties::None)
FValueRef Input (const FExpressionInput *Input)
FValueRef InputDefaultBool (const FExpressionInput *Input, bool Default)
FValueRef InputDefaultFloat (const FExpressionInput *Input, TFloat Default)
FValueRef InputDefaultFloat2 (const FExpressionInput *Input, UE::Math::TVector2< TFloat > Default)
FValueRef InputDefaultFloat3 (const FExpressionInput *Input, UE::Math::TVector< TFloat > Default)
FValueRef InputDefaultFloat4 (const FExpressionInput *Input, UE::Math::TVector4< TFloat > Default)
FValueRef InputDefaultInt (const FExpressionInput *Input, TInteger Default)
FValueRef InputDefaultInt2 (const FExpressionInput *Input, UE::Math::TIntVector2< TInteger > Default)
FValueRef InputDefaultInt3 (const FExpressionInput *Input, UE::Math::TIntVector3< TInteger > Default)
FValueRef InputDefaultInt4 (const FExpressionInput *Input, UE::Math::TIntVector4< TInteger > Default)
FValueRef Length (FValueRef A)
FValueRef Lerp (FValueRef A, FValueRef B, FValueRef C)
FValueRef LessThan (FValueRef A, FValueRef B)
FValueRef LessThanOrEquals (FValueRef A, FValueRef B)
FValueRef Logarithm (FValueRef A)
FValueRef Logarithm10 (FValueRef A)
FValueRef Logarithm2 (FValueRef A)
FValueRef Max (FValueRef A, FValueRef B)
FValueRef Min (FValueRef A, FValueRef B)
FValueRef Multiply (FValueRef A, FValueRef B)
FValueRef Negate (FValueRef A)
FValueRef Not (FValueRef A)
FValueRef NotEquals (FValueRef A, FValueRef B)
FValueRef Operator (EOperator Operator, FValueRef A, FValueRef B={}, FValueRef C={})
FValueRef Or (FValueRef A, FValueRef B)
FEmitter & Output (const FExpressionOutput *Output, FValueRef Value)
FEmitter & Output (int32 OutputIndex, FValueRef Value)
FValueRef Parameter (FName Name, FMaterialParameterMetadata &Metadata, EMaterialSamplerType SamplerType=SAMPLERTYPE_Color)
FValueRef PartialDerivative (FValueRef Value, EDerivativeAxis Axis)
FValueRef Poison ()
FValueRef Round (FValueRef A)
FValueRef Saturate (FValueRef A)
FValueRef Select (FValueRef A, FValueRef B, FValueRef C)
FSetMaterialOutput * SetMaterialOutput (EMaterialProperty InProperty, FValue *Arg)
FValueRef Sin (FValueRef A)
FValueRef Sinh (FValueRef A)
FValueRef Smoothstep (FValueRef A, FValueRef B, FValueRef C)
FValueRef Sqrt (FValueRef A)
FValueRef StageSwitch (const FType *Type, TConstArrayView< FValueRef > ValuePerStage)
FValueRef Subscript (FValueRef Value, int32 Index)
FValueRef Subtract (FValueRef A, FValueRef B)
FValueRef Swizzle (FValueRef Value, FSwizzleMask Mask)
FValueRef Tan (FValueRef A)
FValueRef TextureGather (FValueRef Texture, FValueRef TexCoord, ETextureReadMode GatherMode, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
FValueRef TextureObject (UTexture *Texture, EMaterialSamplerType SamplerType)
FValueRef TextureSample (FValueRef Texture, FValueRef TexCoord, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
FValueRef TextureSampleBias (FValueRef Texture, FValueRef TexCoord, FValueRef MipBias, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
FValueRef TextureSampleGrad (FValueRef Texture, FValueRef TexCoord, FValueRef TexCoordDdx, FValueRef TexCoordDdy, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
FValueRef TextureSampleLevel (FValueRef Texture, FValueRef TexCoord, FValueRef MipLevel, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
bool ToConstantBool (FValueRef Value)
FValueRef Truncate (FValueRef A)
const FType * TryGetCommonType (const FType *A, const FType *B)
FValueRef TryInput (const FExpressionInput *Input)
FValueRef Vector2 (FValueRef InX, FValueRef InY)
FValueRef Vector3 (FValueRef InX, FValueRef InY, FValueRef InZ)
FValueRef Vector4 (FValueRef InX, FValueRef InY, FValueRef InZ, FValueRef InW)
Private Member Functions
FEmitter ()
void Initialize ()
Private Attributes
bool bCurrentExpressionHasErrors = false
FMaterialIRModuleBuilderImpl * BuilderImpl {}
UMaterialExpression * Expression {}
FValue * FalseConstant {}
friend FMaterialIRModuleBuilder
friend FMaterialIRModuleBuilderImpl
UMaterial * Material {}
FMaterialIRModule * Module {}
const FStaticParameterSet * StaticParameterSet {}
FValue * TrueConstant {}
TSet< FValue *, FValueKeyFuncs > ValueSet {}
Detailed Description
Definition at line 130 of file MaterialIREmitter.h.
Constructor & Destructor Documentation
FEmitter()
MIR::FEmitter::FEmitter () inline private
Definition at line 517 of file MaterialIREmitter.h.
Referenced by Output(), and Output().
Member Function Documentation
Abs()
FValueRef MIR::FEmitter::Abs (FValueRef A) inline
Definition at line 449 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Abs.
ACos()
FValueRef MIR::FEmitter::ACos (FValueRef A) inline
Definition at line 450 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_ACos.
ACosh()
FValueRef MIR::FEmitter::ACosh (FValueRef A) inline
Definition at line 451 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_ACosh.
Add()
FValueRef MIR::FEmitter::Add (FValueRef A, FValueRef B) inline
Definition at line 485 of file MaterialIREmitter.h.
References A, B, MIR::BO_Add, and Operator().
AnalyticalPartialDerivative()
FValueRef MIR::FEmitter::AnalyticalPartialDerivative (FValueRef Value, EDerivativeAxis Axis)
References Axis, and Value.
And()
FValueRef MIR::FEmitter::And (FValueRef A, FValueRef B) inline
Definition at line 483 of file MaterialIREmitter.h.
References A, B, MIR::BO_And, and Operator().
ASin()
FValueRef MIR::FEmitter::ASin (FValueRef A) inline
Definition at line 452 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_ASin.
ASinh()
FValueRef MIR::FEmitter::ASinh (FValueRef A) inline
Definition at line 453 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_ASinh.
ATan()
FValueRef MIR::FEmitter::ATan (FValueRef A) inline
Definition at line 454 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_ATan.
ATanh()
FValueRef MIR::FEmitter::ATanh (FValueRef A) inline
Definition at line 455 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_ATan.
BitShiftLeft()
FValueRef MIR::FEmitter::BitShiftLeft (FValueRef A, FValueRef B) inline
Definition at line 491 of file MaterialIREmitter.h.
References A, B, MIR::BO_BitShiftLeft, and Operator().
BitShiftRight()
FValueRef MIR::FEmitter::BitShiftRight (FValueRef A, FValueRef B) inline
Definition at line 492 of file MaterialIREmitter.h.
References A, B, MIR::BO_BitShiftRight, and Operator().
BitwiseAnd()
FValueRef MIR::FEmitter::BitwiseAnd (FValueRef A, FValueRef B) inline
Definition at line 489 of file MaterialIREmitter.h.
References A, B, MIR::BO_BitwiseAnd, and Operator().
BitwiseNot()
FValueRef MIR::FEmitter::BitwiseNot (FValueRef A) inline
Definition at line 446 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_BitwiseNot.
BitwiseOr()
FValueRef MIR::FEmitter::BitwiseOr (FValueRef A, FValueRef B) inline
Definition at line 490 of file MaterialIREmitter.h.
References A, B, MIR::BO_BitwiseOr, and Operator().
Branch()
FValueRef MIR::FEmitter::Branch (FValueRef Condition, FValueRef True, FValueRef False)
Cast()
FValueRef MIR::FEmitter::Cast (FValueRef Value, const FType * TargetType)
References Value.
CastToBool()
FValueRef MIR::FEmitter::CastToBool (FValueRef Value, int NumRows)
References Value.
CastToFloat()
FValueRef MIR::FEmitter::CastToFloat (FValueRef Value, int NumRows)
References Value.
CastToInt()
FValueRef MIR::FEmitter::CastToInt (FValueRef Value, int NumRows)
References Value.
CastToScalar()
FValueRef MIR::FEmitter::CastToScalar (FValueRef Value)
References Value.
Ceil()
FValueRef MIR::FEmitter::Ceil (FValueRef A) inline
Definition at line 456 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Ceil.
CheckIsArithmetic()
FValueRef MIR::FEmitter::CheckIsArithmetic (FValueRef Value)
References Value.
CheckIsInteger()
FValueRef MIR::FEmitter::CheckIsInteger (FValueRef Value)
References Value.
CheckIsPrimitive()
FValueRef MIR::FEmitter::CheckIsPrimitive (FValueRef Value)
References Value.
CheckIsScalar()
FValueRef MIR::FEmitter::CheckIsScalar (FValueRef Value)
References Value.
CheckIsScalarOrVector()
FValueRef MIR::FEmitter::CheckIsScalarOrVector (FValueRef Value)
References Value.
CheckIsTexture()
FValueRef MIR::FEmitter::CheckIsTexture (FValueRef Value)
References Value.
CheckTypeIsKind()
FValueRef MIR::FEmitter::CheckTypeIsKind (FValueRef Value, ETypeKind Kind)
References Value.
Clamp()
FValueRef MIR::FEmitter::Clamp (FValueRef A, FValueRef B, FValueRef C) inline
Definition at line 501 of file MaterialIREmitter.h.
References A, B, Operator(), and MIR::TO_Clamp.
ConstantBool()
FValueRef MIR::FEmitter::ConstantBool (bool InX)
ConstantFalse()
FValueRef MIR::FEmitter::ConstantFalse ()
ConstantFloat()
FValueRef MIR::FEmitter::ConstantFloat (TFloat InX)
ConstantFloat2()
FValueRef MIR::FEmitter::ConstantFloat2 (UE::Math::TVector2< TFloat > InValue)
ConstantFloat3()
FValueRef MIR::FEmitter::ConstantFloat3 (UE::Math::TVector< TFloat > InValue)
ConstantFloat4()
FValueRef MIR::FEmitter::ConstantFloat4 (UE::Math::TVector4< TFloat > InValue)
ConstantFromShaderValue()
FValueRef MIR::FEmitter::ConstantFromShaderValue (const UE::Shader::FValue & InValue)
ConstantInt()
FValueRef MIR::FEmitter::ConstantInt (TInteger InX)
ConstantInt2()
FValueRef MIR::FEmitter::ConstantInt2 (UE::Math::TIntVector2< TInteger > InValue)
ConstantInt3()
FValueRef MIR::FEmitter::ConstantInt3 (UE::Math::TIntVector3< TInteger > InValue)
ConstantInt4()
FValueRef MIR::FEmitter::ConstantInt4 (UE::Math::TIntVector4< TInteger > InValue)
ConstantOne()
FValueRef MIR::FEmitter::ConstantOne (EScalarKind Kind)
ConstantScalar()
FValueRef MIR::FEmitter::ConstantScalar (EScalarKind Kind, TFloat FromFloat)
ConstantTrue()
FValueRef MIR::FEmitter::ConstantTrue ()
ConstantZero()
FValueRef MIR::FEmitter::ConstantZero (EScalarKind Kind)
Cos()
FValueRef MIR::FEmitter::Cos (FValueRef A) inline
Definition at line 457 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Cos.
Cosh()
FValueRef MIR::FEmitter::Cosh (FValueRef A) inline
Definition at line 458 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Cosh.
Cross()
FValueRef MIR::FEmitter::Cross (FValueRef A, FValueRef B) inline
Definition at line 497 of file MaterialIREmitter.h.
References A, B, MIR::BO_Cross, and Operator().
CurrentExpressionHasErrors()
bool MIR::FEmitter::CurrentExpressionHasErrors () const inline
Definition at line 137 of file MaterialIREmitter.h.
References bCurrentExpressionHasErrors.
CustomPrimitiveData()
FValueRef MIR::FEmitter::CustomPrimitiveData (uint32 PrimitiveDataIndex)
Divide()
FValueRef MIR::FEmitter::Divide (FValueRef A, FValueRef B) inline
Definition at line 488 of file MaterialIREmitter.h.
References A, B, MIR::BO_Divide, and Operator().
Dot()
FValueRef MIR::FEmitter::Dot (FValueRef A, FValueRef B) inline
Definition at line 496 of file MaterialIREmitter.h.
References A, B, MIR::BO_Dot, and Operator().
Equals()
FValueRef MIR::FEmitter::Equals (FValueRef A, FValueRef B) inline
Definition at line 481 of file MaterialIREmitter.h.
References A, B, MIR::BO_Equals, and Operator().
Error() [1/2]
void MIR::FEmitter::Error (FStringView Message)
Error() [2/2]
void MIR::FEmitter::Error (FValueRef Source, FStringView Message)
References Source.
Errorf() [1/2]
template<typename... TArgs> void MIR::FEmitter::Errorf (FValueRef Source, UE::Core::TCheckedFormatString< FString::FmtCharType, TArgs... > Format, TArgs... Args) inline
Definition at line 141 of file MaterialIREmitter.h.
References Error, Format, and Source.
Errorf() [2/2]
template<typename... TArgs> void MIR::FEmitter::Errorf (UE::Core::TCheckedFormatString< FString::FmtCharType, TArgs... > Format, TArgs... Args) inline
Definition at line 148 of file MaterialIREmitter.h.
References Error, and Format.
Exponential()
FValueRef MIR::FEmitter::Exponential (FValueRef A) inline
Definition at line 459 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Exponential.
Exponential2()
FValueRef MIR::FEmitter::Exponential2 (FValueRef A) inline
Definition at line 460 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Exponential2.
ExternalInput()
FValueRef MIR::FEmitter::ExternalInput (EExternalInput Id)
Floor()
FValueRef MIR::FEmitter::Floor (FValueRef A) inline
Definition at line 461 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Floor.
Fmod()
FValueRef MIR::FEmitter::Fmod (FValueRef A, FValueRef B) inline
Definition at line 493 of file MaterialIREmitter.h.
References A, B, MIR::BO_Fmod, and Operator().
Frac()
FValueRef MIR::FEmitter::Frac (FValueRef A) inline
Definition at line 462 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Frac.
GetCommonType()
const FType * MIR::FEmitter::GetCommonType (const FType * A, const FType * B)
References A, and B.
GreaterThan()
FValueRef MIR::FEmitter::GreaterThan (FValueRef A, FValueRef B) inline
Definition at line 477 of file MaterialIREmitter.h.
References A, B, MIR::BO_GreaterThan, and Operator().
GreaterThanOrEquals()
FValueRef MIR::FEmitter::GreaterThanOrEquals (FValueRef A, FValueRef B) inline
Definition at line 478 of file MaterialIREmitter.h.
References A, B, MIR::BO_GreaterThanOrEquals, and Operator().
Initialize()
void MIR::FEmitter::Initialize () private
InlineHLSL() [1/2]
FValueRef MIR::FEmitter::InlineHLSL (const FMaterialExternalCodeDeclaration * InExternalCodeDeclaration, TConstArrayView< FValueRef > InputValues, EValueFlags ValueFlags = EValueFlags::None, EGraphProperties UsedGraphProperties = EGraphProperties::None)
References MIR::None.
InlineHLSL() [2/2]
FValueRef MIR::FEmitter::InlineHLSL (const FType * Type, FString Code, TConstArrayView< FValueRef > InputValues, EValueFlags ValueFlags = EValueFlags::None, EGraphProperties UsedGraphProperties = EGraphProperties::None)
References MIR::None.
Input()
FValueRef MIR::FEmitter::Input (const FExpressionInput * Input)
References Input().
Referenced by Input(), InputDefaultBool(), InputDefaultFloat(), InputDefaultFloat2(), InputDefaultFloat3(), InputDefaultFloat4(), InputDefaultInt(), InputDefaultInt2(), InputDefaultInt3(), InputDefaultInt4(), and TryInput().
InputDefaultBool()
FValueRef MIR::FEmitter::InputDefaultBool (const FExpressionInput * Input, bool Default)
References Default, and Input().
InputDefaultFloat()
FValueRef MIR::FEmitter::InputDefaultFloat (const FExpressionInput * Input, TFloat Default)
References Default, and Input().
InputDefaultFloat2()
FValueRef MIR::FEmitter::InputDefaultFloat2 (const FExpressionInput * Input, UE::Math::TVector2< TFloat > Default)
References Default, and Input().
InputDefaultFloat3()
FValueRef MIR::FEmitter::InputDefaultFloat3 (const FExpressionInput * Input, UE::Math::TVector< TFloat > Default)
References Default, and Input().
InputDefaultFloat4()
FValueRef MIR::FEmitter::InputDefaultFloat4 (const FExpressionInput * Input, UE::Math::TVector4< TFloat > Default)
References Default, and Input().
InputDefaultInt()
FValueRef MIR::FEmitter::InputDefaultInt (const FExpressionInput * Input, TInteger Default)
References Default, and Input().
InputDefaultInt2()
FValueRef MIR::FEmitter::InputDefaultInt2 (const FExpressionInput * Input, UE::Math::TIntVector2< TInteger > Default)
References Default, and Input().
InputDefaultInt3()
FValueRef MIR::FEmitter::InputDefaultInt3 (const FExpressionInput * Input, UE::Math::TIntVector3< TInteger > Default)
References Default, and Input().
InputDefaultInt4()
FValueRef MIR::FEmitter::InputDefaultInt4 (const FExpressionInput * Input, UE::Math::TIntVector4< TInteger > Default)
References Default, and Input().
Length()
FValueRef MIR::FEmitter::Length (FValueRef A) inline
Definition at line 463 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Length.
Lerp()
FValueRef MIR::FEmitter::Lerp (FValueRef A, FValueRef B, FValueRef C) inline
Definition at line 502 of file MaterialIREmitter.h.
References A, B, Operator(), and MIR::TO_Lerp.
LessThan()
FValueRef MIR::FEmitter::LessThan (FValueRef A, FValueRef B) inline
Definition at line 479 of file MaterialIREmitter.h.
References A, B, MIR::BO_LessThan, and Operator().
LessThanOrEquals()
FValueRef MIR::FEmitter::LessThanOrEquals (FValueRef A, FValueRef B) inline
Definition at line 480 of file MaterialIREmitter.h.
References A, B, MIR::BO_LessThanOrEquals, and Operator().
Logarithm()
FValueRef MIR::FEmitter::Logarithm (FValueRef A) inline
Definition at line 464 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Logarithm.
Logarithm10()
FValueRef MIR::FEmitter::Logarithm10 (FValueRef A) inline
Definition at line 466 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Logarithm10.
Logarithm2()
FValueRef MIR::FEmitter::Logarithm2 (FValueRef A) inline
Definition at line 465 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Logarithm2.
Max()
FValueRef MIR::FEmitter::Max (FValueRef A, FValueRef B) inline
Definition at line 494 of file MaterialIREmitter.h.
References A, B, MIR::BO_Max, and Operator().
Min()
FValueRef MIR::FEmitter::Min (FValueRef A, FValueRef B) inline
Definition at line 495 of file MaterialIREmitter.h.
References A, B, MIR::BO_Min, and Operator().
Multiply()
FValueRef MIR::FEmitter::Multiply (FValueRef A, FValueRef B) inline
Definition at line 487 of file MaterialIREmitter.h.
References A, B, MIR::BO_Multiply, and Operator().
Negate()
FValueRef MIR::FEmitter::Negate (FValueRef A) inline
Definition at line 447 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Negate.
Not()
FValueRef MIR::FEmitter::Not (FValueRef A) inline
Definition at line 448 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Not.
NotEquals()
FValueRef MIR::FEmitter::NotEquals (FValueRef A, FValueRef B) inline
Definition at line 482 of file MaterialIREmitter.h.
References A, B, MIR::BO_NotEquals, and Operator().
Operator()
FValueRef MIR::FEmitter::Operator (EOperator Operator, FValueRef A, FValueRef B = {}, FValueRef C = {})
References A, B, and Operator().
Referenced by Abs(), ACos(), ACosh(), Add(), And(), ASin(), ASinh(), ATan(), ATanh(), BitShiftLeft(), BitShiftRight(), BitwiseAnd(), BitwiseNot(), BitwiseOr(), Ceil(), Clamp(), Cos(), Cosh(), Cross(), Divide(), Dot(), Equals(), Exponential(), Exponential2(), Floor(), Fmod(), Frac(), GreaterThan(), GreaterThanOrEquals(), Length(), Lerp(), LessThan(), LessThanOrEquals(), Logarithm(), Logarithm10(), Logarithm2(), Max(), Min(), Multiply(), Negate(), Not(), NotEquals(), Operator(), Or(), Round(), Saturate(), Select(), Sin(), Sinh(), Smoothstep(), Sqrt(), Subtract(), Tan(), and Truncate().
Or()
FValueRef MIR::FEmitter::Or (FValueRef A, FValueRef B) inline
Definition at line 484 of file MaterialIREmitter.h.
References A, B, MIR::BO_Or, and Operator().
Output() [1/2]
FEmitter & MIR::FEmitter::Output (const FExpressionOutput * Output, FValueRef Value)
References FEmitter(), Output(), and Value.
Output() [2/2]
FEmitter & MIR::FEmitter::Output (int32 OutputIndex, FValueRef Value)
References FEmitter(), and Value.
Referenced by Output().
Parameter()
FValueRef MIR::FEmitter::Parameter (FName Name, FMaterialParameterMetadata & Metadata, EMaterialSamplerType SamplerType = SAMPLERTYPE_Color)
References Metadata, and Name.
PartialDerivative()
FValueRef MIR::FEmitter::PartialDerivative (FValueRef Value, EDerivativeAxis Axis)
References Axis, and Value.
Poison()
FValueRef MIR::FEmitter::Poison ()
Round()
FValueRef MIR::FEmitter::Round (FValueRef A) inline
Definition at line 467 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Round.
Saturate()
FValueRef MIR::FEmitter::Saturate (FValueRef A) inline
Definition at line 468 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Saturate.
Select()
FValueRef MIR::FEmitter::Select (FValueRef A, FValueRef B, FValueRef C) inline
Definition at line 503 of file MaterialIREmitter.h.
References A, B, Operator(), and MIR::TO_Select.
SetMaterialOutput()
FSetMaterialOutput * MIR::FEmitter::SetMaterialOutput (EMaterialProperty InProperty, FValue * Arg)
Sin()
FValueRef MIR::FEmitter::Sin (FValueRef A) inline
Definition at line 469 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Sin.
Sinh()
FValueRef MIR::FEmitter::Sinh (FValueRef A) inline
Definition at line 470 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Sinh.
Smoothstep()
FValueRef MIR::FEmitter::Smoothstep (FValueRef A, FValueRef B, FValueRef C) inline
Definition at line 504 of file MaterialIREmitter.h.
References A, B, Operator(), and MIR::TO_Smoothstep.
Sqrt()
FValueRef MIR::FEmitter::Sqrt (FValueRef A) inline
Definition at line 471 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Sqrt.
StageSwitch()
FValueRef MIR::FEmitter::StageSwitch (const FType * Type, TConstArrayView< FValueRef > ValuePerStage)
Subscript()
FValueRef MIR::FEmitter::Subscript (FValueRef Value, int32 Index)
References Value.
Subtract()
FValueRef MIR::FEmitter::Subtract (FValueRef A, FValueRef B) inline
Definition at line 486 of file MaterialIREmitter.h.
References A, B, MIR::BO_Subtract, and Operator().
Swizzle()
FValueRef MIR::FEmitter::Swizzle (FValueRef Value, FSwizzleMask Mask)
References Mask, and Value.
Tan()
FValueRef MIR::FEmitter::Tan (FValueRef A) inline
Definition at line 472 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Tan.
TextureGather()
FValueRef MIR::FEmitter::TextureGather (FValueRef Texture, FValueRef TexCoord, ETextureReadMode GatherMode, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
References Texture.
TextureObject()
FValueRef MIR::FEmitter::TextureObject (UTexture * Texture, EMaterialSamplerType SamplerType)
References Texture.
TextureSample()
FValueRef MIR::FEmitter::TextureSample (FValueRef Texture, FValueRef TexCoord, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
References Texture.
TextureSampleBias()
FValueRef MIR::FEmitter::TextureSampleBias (FValueRef Texture, FValueRef TexCoord, FValueRef MipBias, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
References MIR::MipBias, and Texture.
TextureSampleGrad()
FValueRef MIR::FEmitter::TextureSampleGrad (FValueRef Texture, FValueRef TexCoord, FValueRef TexCoordDdx, FValueRef TexCoordDdy, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
References Texture.
TextureSampleLevel()
FValueRef MIR::FEmitter::TextureSampleLevel (FValueRef Texture, FValueRef TexCoord, FValueRef MipLevel, bool bAddViewMaterialMipBias, ESamplerSourceMode SamplerSourceMode, EMaterialSamplerType SamplerType)
References MIR::MipLevel, and Texture.
ToConstantBool()
bool MIR::FEmitter::ToConstantBool (FValueRef Value)
References Value.
Truncate()
FValueRef MIR::FEmitter::Truncate (FValueRef A) inline
Definition at line 473 of file MaterialIREmitter.h.
References A, Operator(), and MIR::UO_Truncate.
TryGetCommonType()
const FType * MIR::FEmitter::TryGetCommonType (const FType * A, const FType * B)
References A, and B.
TryInput()
FValueRef MIR::FEmitter::TryInput (const FExpressionInput * Input)
References Input().
Vector2()
FValueRef MIR::FEmitter::Vector2 (FValueRef InX, FValueRef InY)
Vector3()
FValueRef MIR::FEmitter::Vector3 (FValueRef InX, FValueRef InY, FValueRef InZ)
Vector4()
FValueRef MIR::FEmitter::Vector4 (FValueRef InX, FValueRef InY, FValueRef InZ, FValueRef InW)
Field Documentation
bCurrentExpressionHasErrors
bool MIR::FEmitter::bCurrentExpressionHasErrors = false private
Definition at line 539 of file MaterialIREmitter.h.
Referenced by CurrentExpressionHasErrors().
BuilderImpl
FMaterialIRModuleBuilderImpl* MIR::FEmitter::BuilderImpl {} private
Definition at line 524 of file MaterialIREmitter.h.
Expression
UMaterialExpression* MIR::FEmitter::Expression {} private
Definition at line 536 of file MaterialIREmitter.h.
FalseConstant
FValue* MIR::FEmitter::FalseConstant {} private
Definition at line 545 of file MaterialIREmitter.h.
FMaterialIRModuleBuilder
friend MIR::FEmitter::FMaterialIRModuleBuilder private
Definition at line 552 of file MaterialIREmitter.h.
FMaterialIRModuleBuilderImpl
friend MIR::FEmitter::FMaterialIRModuleBuilderImpl private
Definition at line 553 of file MaterialIREmitter.h.
Material
UMaterial* MIR::FEmitter::Material {} private
Definition at line 527 of file MaterialIREmitter.h.
Module
FMaterialIRModule* MIR::FEmitter::Module {} private
Definition at line 530 of file MaterialIREmitter.h.
StaticParameterSet
const FStaticParameterSet* MIR::FEmitter::StaticParameterSet {} private
Definition at line 533 of file MaterialIREmitter.h.
TrueConstant
FValue* MIR::FEmitter::TrueConstant {} private
Definition at line 542 of file MaterialIREmitter.h.
ValueSet
TSet<FValue*, FValueKeyFuncs> MIR::FEmitter::ValueSet {} private
Definition at line 550 of file MaterialIREmitter.h.
The documentation for this class was generated from the following file:
MaterialIREmitter.h