Unreal Engine 5.6 C++ API: FIoDirectoryIndexReader Class Reference
FIoDirectoryIndexReader Class Reference
#include "IoDispatcher.h"
Public Member Functions
FIoDirectoryIndexReader ()
~FIoDirectoryIndexReader ()
FIoDirectoryIndexHandle GetChildDirectory (FIoDirectoryIndexHandle Directory) const
FStringView GetDirectoryName (FIoDirectoryIndexHandle Directory) const
FIoDirectoryIndexHandle GetFile (FIoDirectoryIndexHandle Directory) const
uint32 GetFileData (FIoDirectoryIndexHandle File) const
FStringView GetFileName (FIoDirectoryIndexHandle File) const
const FString & GetMountPoint () const
FIoDirectoryIndexHandle GetNextDirectory (FIoDirectoryIndexHandle Directory) const
FIoDirectoryIndexHandle GetNextFile (FIoDirectoryIndexHandle File) const
FIoStatus Initialize (TConstArrayView< uint8 > InBuffer, FAES::FAESKey InDecryptionKey)
bool IterateDirectoryIndex (FIoDirectoryIndexHandle Directory, FStringView Path, FDirectoryIndexVisitorFunction Visit) const
Private Member Functions
UE_NONCOPYABLE (FIoDirectoryIndexReader)
Private Attributes
FIoDirectoryIndexReaderImpl * Impl
Detailed Description
Definition at line 453 of file IoDispatcher.h.
Constructor & Destructor Documentation
FIoDirectoryIndexReader()
FIoDirectoryIndexReader::FIoDirectoryIndexReader ()
Referenced by UE_NONCOPYABLE().
~FIoDirectoryIndexReader()
FIoDirectoryIndexReader::~FIoDirectoryIndexReader ()
Member Function Documentation
GetChildDirectory()
FIoDirectoryIndexHandle FIoDirectoryIndexReader::GetChildDirectory (FIoDirectoryIndexHandle Directory) const
GetDirectoryName()
FStringView FIoDirectoryIndexReader::GetDirectoryName (FIoDirectoryIndexHandle Directory) const
GetFile()
FIoDirectoryIndexHandle FIoDirectoryIndexReader::GetFile (FIoDirectoryIndexHandle Directory) const
GetFileData()
uint32 FIoDirectoryIndexReader::GetFileData (FIoDirectoryIndexHandle File) const
GetFileName()
FStringView FIoDirectoryIndexReader::GetFileName (FIoDirectoryIndexHandle File) const
GetMountPoint()
const FString & FIoDirectoryIndexReader::GetMountPoint () const
GetNextDirectory()
FIoDirectoryIndexHandle FIoDirectoryIndexReader::GetNextDirectory (FIoDirectoryIndexHandle Directory) const
GetNextFile()
FIoDirectoryIndexHandle FIoDirectoryIndexReader::GetNextFile (FIoDirectoryIndexHandle File) const
Initialize()
FIoStatus FIoDirectoryIndexReader::Initialize (TConstArrayView< uint8 > InBuffer, FAES::FAESKey InDecryptionKey)
IterateDirectoryIndex()
bool FIoDirectoryIndexReader::IterateDirectoryIndex (FIoDirectoryIndexHandle Directory, FStringView Path, FDirectoryIndexVisitorFunction Visit) const
References Path, and Visit().
UE_NONCOPYABLE()
FIoDirectoryIndexReader::UE_NONCOPYABLE (FIoDirectoryIndexReader) private
References FIoDirectoryIndexReader().
Field Documentation
Impl
FIoDirectoryIndexReaderImpl* FIoDirectoryIndexReader::Impl private
Definition at line 474 of file IoDispatcher.h.
The documentation for this class was generated from the following file:
IoDispatcher.h