Unreal Engine 5.6 C++ API: FStaticSpatialIndex::TListImpl< Profile > Class Template Reference
FStaticSpatialIndex::TListImpl< Profile > Class Template Reference
#include "StaticSpatialIndex.h"
Public Member Functions
TListImpl (const TStaticSpatialIndexDataInterface< Profile > &InDataInterface)
bool ForEachElement (TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElement (const FBox &InBox, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElement (const FStaticSpatialIndex::FCone &InCone, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElement (const FStaticSpatialIndex::FSphere &InSphere, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
uint32 GetAllocatedSize () const
void Init ()
Public Member Functions inherited from FStaticSpatialIndex::TImpl< Profile >
TImpl (const TStaticSpatialIndexDataInterface< Profile > &InDataInterface)
Private Types
using FBox = typename Profile::FBox
using FVector = typename Profile::FVector
Additional Inherited Members
Protected Attributes inherited from FStaticSpatialIndex::TImpl< Profile >
const TStaticSpatialIndexDataInterface< Profile > & DataInterface
Detailed Description
template<typename Profile>
class FStaticSpatialIndex::TListImpl< Profile >
Definition at line 308 of file StaticSpatialIndex.h.
Member Typedef Documentation
FBox
template<typename Profile> using FStaticSpatialIndex::TListImpl< Profile >::FBox = typename Profile::FBox private
Definition at line 311 of file StaticSpatialIndex.h.
FVector
template<typename Profile> using FStaticSpatialIndex::TListImpl< Profile >::FVector = typename Profile::FVector private
Definition at line 310 of file StaticSpatialIndex.h.
Constructor & Destructor Documentation
TListImpl()
template<typename Profile> FStaticSpatialIndex::TListImpl< Profile >::TListImpl (const TStaticSpatialIndexDataInterface< Profile > & InDataInterface) inline
Definition at line 314 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::TImpl< Profile >::TImpl().
Member Function Documentation
ForEachElement()
template<typename Profile> bool FStaticSpatialIndex::TListImpl< Profile >::ForEachElement (TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 320 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::TImpl< Profile >::DataInterface.
ForEachIntersectingElement() [1/3]
template<typename Profile> bool FStaticSpatialIndex::TListImpl< Profile >::ForEachIntersectingElement (const FBox & InBox, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 332 of file StaticSpatialIndex.h.
References Box, and FStaticSpatialIndex::TImpl< Profile >::DataInterface.
ForEachIntersectingElement() [2/3]
template<typename Profile> bool FStaticSpatialIndex::TListImpl< Profile >::ForEachIntersectingElement (const FStaticSpatialIndex::FCone & InCone, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 369 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::FCone::Angle, FStaticSpatialIndex::FCone::Axis, Box, FStaticSpatialIndex::FSphere::Center, FStaticSpatialIndex::TImpl< Profile >::DataInterface, FStaticSpatialIndex::FastConeAABBIntersection(), FStaticSpatialIndex::FSphere::Radius, FMath::Square(), and UE_PI.
ForEachIntersectingElement() [3/3]
template<typename Profile> bool FStaticSpatialIndex::TListImpl< Profile >::ForEachIntersectingElement (const FStaticSpatialIndex::FSphere & InSphere, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 350 of file StaticSpatialIndex.h.
References Box, FStaticSpatialIndex::TImpl< Profile >::DataInterface, FStaticSpatialIndex::FastSphereAABBIntersection(), and FMath::Square().
GetAllocatedSize()
template<typename Profile> uint32 FStaticSpatialIndex::TListImpl< Profile >::GetAllocatedSize () const inline
Definition at line 390 of file StaticSpatialIndex.h.
Init()
template<typename Profile> void FStaticSpatialIndex::TListImpl< Profile >::Init () inline
Definition at line 318 of file StaticSpatialIndex.h.
The documentation for this class was generated from the following file:
StaticSpatialIndex.h