Unreal Engine 5.6 C++ API: FComposableDistribution Class Reference
FComposableDistribution Class Reference
Base class for composable distributions.
#include "Distributions.h"
Static Public Member Functions
static void BuildFloat (class FFloatDistribution &OutDistribution, const class FComposableFloatDistribution &X)
Constructs a type-safe floating point distribution.
static void BuildVector (class FVectorDistribution &OutDistribution, const class FComposableVectorDistribution &XYZ)
Constructs a type-safe vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableFloatDistribution &X, const class FComposableFloatDistribution &Y, const class FComposableFloatDistribution &Z, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableVectorDistribution &XY, const class FComposableFloatDistribution &Z, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableVectorDistribution &XYZ, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void QuantizeVector4 (TArray< FColor > &OutQuantizedSamples, FVector4 &OutScale, FVector4 &OutBias, const class FVector4Distribution &Distribution)
Quantizes a 4-component vector distribution.
Protected Member Functions
FComposableDistribution ()
Constructor.
FComposableDistribution (const FComposableDistribution &Other)
Copy constructor.
~FComposableDistribution ()
Destructor.
const FComposableDistribution & operator= (const FComposableDistribution &Other)
Assignment operator.
Protected Attributes
FDistributionLookupTable LookupTable
The lookup table.
Detailed Description
Base class for composable distributions.
Responsible for building the final distributions that can be sampled.
Definition at line 518 of file Distributions.h.
Constructor & Destructor Documentation
FComposableDistribution() [1/2]
FComposableDistribution::FComposableDistribution () inline protected
Constructor.
Protected to prevent instantiating the base class.
Definition at line 588 of file Distributions.h.
Referenced by FComposableDistribution(), FComposableFloatDistribution::FComposableFloatDistribution(), FComposableVectorDistribution::FComposableVectorDistribution(), and operator=().
~FComposableDistribution()
FComposableDistribution::~FComposableDistribution () inline protected
Destructor.
Definition at line 591 of file Distributions.h.
FComposableDistribution() [2/2]
FComposableDistribution::FComposableDistribution (const FComposableDistribution & Other) inline protected
Copy constructor.
Protected to only allow type-safe copying.
Definition at line 594 of file Distributions.h.
References FComposableDistribution(), LookupTable, and Other.
Member Function Documentation
BuildFloat()
void FComposableDistribution::BuildFloat (class FFloatDistribution & OutDistribution, const class FComposableFloatDistribution & X) static
Constructs a type-safe floating point distribution.
Parameters
OutDistribution - The distribution to build.
X - The source distribution.
References X.
BuildVector()
void FComposableDistribution::BuildVector (class FVectorDistribution & OutDistribution, const class FComposableVectorDistribution & XYZ) static
Constructs a type-safe vector distribution.
Parameters
OutDistribution - The distribution to build.
XYZ - The source distribution.
BuildVector4() [1/3]
void FComposableDistribution::BuildVector4 (class FVector4Distribution & OutDistribution, const class FComposableFloatDistribution & X, const class FComposableFloatDistribution & Y, const class FComposableFloatDistribution & Z, const class FComposableFloatDistribution & W) static
Constructs a type-safe 4-vector distribution.
Parameters
OutDistribution - The distribution to build.
X - The source distribution for the X component.
Y - The source distribution for the Y component.
Z - The source distribution for the Z component.
W - The source distribution for the W component.
References X, Y, and Z.
BuildVector4() [2/3]
void FComposableDistribution::BuildVector4 (class FVector4Distribution & OutDistribution, const class FComposableVectorDistribution & XY, const class FComposableFloatDistribution & Z, const class FComposableFloatDistribution & W) static
Constructs a type-safe 4-vector distribution.
Parameters
OutDistribution - The distribution to build.
XY - The source distribution for the X and Y components.
Z - The source distribution for the Z component.
W - The source distribution for the W component.
References Z.
BuildVector4() [3/3]
void FComposableDistribution::BuildVector4 (class FVector4Distribution & OutDistribution, const class FComposableVectorDistribution & XYZ, const class FComposableFloatDistribution & W) static
Constructs a type-safe 4-vector distribution.
Parameters
OutDistribution - The distribution to build.
XYZ - The source distribution for the X, Y, and Z components.
W - The source distribution for the W component.
operator=()
const FComposableDistribution & FComposableDistribution::operator= (const FComposableDistribution & Other) inline protected
Assignment operator.
Protected to only allow type-safe copying.
Definition at line 600 of file Distributions.h.
References FComposableDistribution(), LookupTable, and Other.
Referenced by FComposableFloatDistribution::operator=(), and FComposableVectorDistribution::operator=().
QuantizeVector4()
void FComposableDistribution::QuantizeVector4 (TArray< FColor > & OutQuantizedSamples, FVector4 & OutScale, FVector4 & OutBias, const class FVector4Distribution & Distribution) static
Quantizes a 4-component vector distribution.
Parameters
OutQuantizedSamples - The quantized samples in the distribution.
OutScale - Scale to apply to quantized samples.
OutBias - Bias to apply to quantized samples.
Field Documentation
LookupTable
FDistributionLookupTable FComposableDistribution::LookupTable protected
The lookup table.
Definition at line 585 of file Distributions.h.
Referenced by FComposableDistribution(), and operator=().
The documentation for this class was generated from the following file:
Distributions.h