Unreal Engine 5.6 C++ API: UScriptStruct::TCppStructOps< CPPSTRUCT > Struct Template Reference
UScriptStruct::TCppStructOps< CPPSTRUCT > Struct Template Reference final
Template to manage dynamic access to C++ struct construction and destruction.
#include "Class.h"
Public Types
typedef TStructOpsTypeTraits< CPPSTRUCT > TTraits
Public Types inherited from UScriptStruct::ICppStructOps
typedef void(* TPointerToAddStructReferencedObjects) (void *A, class FReferenceCollector &Collector)
return a pointer to a function that can add referenced objects
Public Member Functions
TCppStructOps ()
virtual TPointerToAddStructReferencedObjects AddStructReferencedObjects () override
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain, const void *Data) const override
Returns true if this struct would allow the given property to be edited in the details panel.
virtual void ClearIntrusiveOptionalValue (void *Data) const override
Reset an optional value to its unset state.
virtual void Construct (void *Dest) override
Call the C++ constructor.
virtual void ConstructForTests (void *Dest) override
Call the C++ constructor without value-init (new T instead of new T())
virtual bool Copy (void *Dest, void const *Src, int32 ArrayDim) override
Copy this structure.
virtual void Destruct (void *Dest) override
Call the C++ destructor.
virtual bool ExportTextItem (FString &ValueStr, const void *PropertyValue, const void *DefaultValue, class UObject *Parent, int32 PortFlags, class UObject *ExportRootScope) override
export this structure
virtual bool FindInnerPropertyInstance (FName PropertyName, const void *Data, const FProperty *&OutProp, const void *&OutData) const override
virtual FCapabilities GetCapabilities () const override
returns struct capabilities
virtual void GetPreloadDependencies (void *Data, TArray< UObject * > &OutDeps) override
Call PreloadDependencies on this structure.
uint32 GetStructTypeHash (const void *Src) override
Calls GetTypeHash if enabled.
virtual bool Identical (const void *A, const void *B, uint32 PortFlags, bool &bOutResult) override
Compare this structure.
virtual bool ImportTextItem (const TCHAR *&Buffer, void *Data, int32 PortFlags, class UObject *OwnerObject, FOutputDevice *ErrorText) override
import this structure
virtual void InitializeIntrusiveUnsetOptionalValue (void *Data) const override
Construct an unset optional value.
virtual bool IsIntrusiveOptionalSafeForGC () const
Used for assertions only: confirms that this type has certified that its object reference fields are safe for the GC to visit while the struct is in its intrusive unset optional state.
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const override
Return true if the optional value at Data is in an unset state.
virtual bool NetDeltaSerialize (FNetDeltaSerializeInfo &DeltaParms, void *Data) override
Net serialize delta this structure.
virtual bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess, void *Data) override
Net serialize this structure.
virtual void PostScriptConstruct (void *Data) override
Call PostScriptConstruct on this structure.
virtual void PostSerialize (const FArchive &Ar, void *Data) override
Call PostSerialize on this structure.
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const override
virtual bool Serialize (FArchive &Ar, void *Data, UStruct *DefaultsStruct, const void *Defaults) override
Serialize this structure.
virtual bool Serialize (FStructuredArchive::FSlot Slot, void *Data, UStruct *DefaultsStruct, const void *Defaults) override
virtual bool SerializeFromMismatchedTag (struct FPropertyTag const &Tag, FArchive &Ar, void *Data) override
Serialize this structure, from some other tag.
virtual bool StructuredSerializeFromMismatchedTag (struct FPropertyTag const &Tag, FStructuredArchive::FSlot Slot, void *Data) override
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &Context)> InFunc) const override
Public Member Functions inherited from UScriptStruct::ICppStructOps
ICppStructOps (int32 InSize, int32 InAlignment)
Constructor.
virtual ~ICppStructOps ()
FORCEINLINE int32 GetAlignment () const
return the alignof() of this structure
EPropertyFlags GetComputedPropertyFlags () const
Returns property flag values that can be computed at compile time.
FORCEINLINE int32 GetSize () const
return the sizeof() of this structure
bool HasAddStructReferencedObjects () const
return true if this struct has custom GC code
bool HasCanEditChange () const
Returns true if this struct wants to indicate whether a property can be edited in the details panel.
bool HasClearOnFinishDestroy () const
return true if this struct has a ClearOnFinishDestroy
bool HasCopy () const
return true if this struct can copy
bool HasDestructor () const
return false if this destructor can be skipped
bool HasExportTextItem () const
return true if this struct can export
bool HasFindInnerPropertyInstance () const
bool HasGetTypeHash () const
return true if this struct has a GetTypeHash
bool HasIdentical () const
return true if this struct can compare
bool HasImportTextItem () const
return true if this struct can import
bool HasIntrusiveUnsetOptionalState () const
Return true if this type can be constructed with FIntrusiveUnsetOptionalState for TOptional.
bool HasNetDeltaSerializer () const
return true if this struct can net delta serialize delta (serialize a network delta from a base state)
bool HasNetSerializer () const
return true if this struct can net serialize
bool HasNetSharedSerialization () const
return true if this can share net serialization across connections
bool HasNoopConstructor () const
return true if this class has a no-op constructor and takes EForceInit to init
bool HasPostScriptConstruct () const
return true if this class implements a post script construct call
bool HasPostSerialize () const
return true if this class implements a post serialize call
bool HasSerializeFromMismatchedTag () const
return true if this class wants to serialize from some other tag (usually for conversion purposes)
bool HasSerializer () const
return true if this class can serialize
bool HasSerializerObjectReferences (EPropertyObjectReferenceType Type) const
returns true if the native serialize functions may serialize object references of the given type
bool HasStructuredSerializeFromMismatchedTag () const
bool HasStructuredSerializer () const
return true if this class can serialize to a structured archive
bool HasVisitor () const
Returns true if this struct wants to indicate whether it has a custom impl for visiting properties.
bool HasZeroConstructor () const
return true if memset can be used instead of the constructor
bool IsAbstract () const
return true if this struct is abstract
bool IsPlainOldData () const
return true if this struct should be memcopied
bool IsUECoreType () const
return true if this struct is one of the UE Core types (and is include in CoreMinimal.h)
bool IsUECoreVariant () const
return true if this struct is one of the UE Core types (and is include in CoreMinimal.h)
UE_DEPRECATED (5.6, "Use the overload of Serialize with defaults.") virtual bool Serialize(FArchive &Ar
UE_DEPRECATED (5.6, "Use the overload of Serialize with defaults.") virtual bool Serialize(FStructuredArchive
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const =0
Structs property visitor signature.
Additional Inherited Members
Data Fields inherited from UScriptStruct::ICppStructOps
void * Data
Detailed Description
template<class CPPSTRUCT>
struct UScriptStruct::TCppStructOps< CPPSTRUCT >
Template to manage dynamic access to C++ struct construction and destruction.
Definition at line 1345 of file Class.h.
Member Typedef Documentation
TTraits
template<class CPPSTRUCT> typedef TStructOpsTypeTraits<CPPSTRUCT> UScriptStruct::TCppStructOps< CPPSTRUCT >::TTraits
Definition at line 1347 of file Class.h.
Constructor & Destructor Documentation
TCppStructOps()
template<class CPPSTRUCT> UScriptStruct::TCppStructOps< CPPSTRUCT >::TCppStructOps () inline
Definition at line 1348 of file Class.h.
References UScriptStruct::ICppStructOps::ICppStructOps(), UObject::UObject(), and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithAddStructReferencedObjects.
Member Function Documentation
AddStructReferencedObjects()
template<class CPPSTRUCT> virtual TPointerToAddStructReferencedObjects UScriptStruct::TCppStructOps< CPPSTRUCT >::AddStructReferencedObjects () inline override virtual
Implements UScriptStruct::ICppStructOps.
Definition at line 1622 of file Class.h.
References AddStructReferencedObjectsOrNot(), check, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithAddStructReferencedObjects.
CanEditChange()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::CanEditChange (const FEditPropertyChain & PropertyChain, const void * Data) const inline override virtual
Returns true if this struct would allow the given property to be edited in the details panel.
Implements UScriptStruct::ICppStructOps.
Definition at line 1723 of file Class.h.
References UScriptStruct::ICppStructOps::Data, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithCanEditChange.
ClearIntrusiveOptionalValue()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::ClearIntrusiveOptionalValue (void * Data) const inline override virtual
Reset an optional value to its unset state.
Implements UScriptStruct::ICppStructOps.
Definition at line 1707 of file Class.h.
References UScriptStruct::ICppStructOps::Data, and Reset.
Construct()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::Construct (void * Dest) inline override virtual
Call the C++ constructor.
Implements UScriptStruct::ICppStructOps.
Definition at line 1394 of file Class.h.
References check, ForceInit, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNoInitConstructor, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithPureVirtual, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithZeroConstructor.
Referenced by ExportTextItem().
ConstructForTests()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::ConstructForTests (void * Dest) inline override virtual
Call the C++ constructor without value-init (new T instead of new T())
Implements UScriptStruct::ICppStructOps.
Definition at line 1413 of file Class.h.
References check, ForceInit, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNoInitConstructor, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithPureVirtual, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithZeroConstructor.
Copy()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::Copy (void * Dest, void const * Src, int32 ArrayDim) inline override virtual
Copy this structure.
Returns
true if the copy was handled, otherwise it will fall back to CopySingleValue
Implements UScriptStruct::ICppStructOps.
Definition at line 1522 of file Class.h.
References TIsPODType< T >::Value, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithCopy.
Destruct()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::Destruct (void * Dest) inline override virtual
Call the C++ destructor.
Implements UScriptStruct::ICppStructOps.
Definition at line 1432 of file Class.h.
References check, DestructItem(), TIsPODType< T >::Value, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNoDestructor.
Referenced by ExportTextItem().
ExportTextItem()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::ExportTextItem (FString & ValueStr, const void * PropertyValue, const void * DefaultValue, class UObject * Parent, int32 PortFlags, class UObject * ExportRootScope) inline override virtual
export this structure
Returns
true if the copy was exported, otherwise it will fall back to FStructProperty::ExportTextItem
Implements UScriptStruct::ICppStructOps.
Definition at line 1563 of file Class.h.
References UObject::UObject(), check, Construct(), Destruct(), TTypeCompatibleBytes< ElementType >::GetTypedPtr(), UScriptStruct::ICppStructOps::HasDestructor(), UScriptStruct::ICppStructOps::HasZeroConstructor(), FMemory::Memzero(), Parent, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithExportTextItem.
FindInnerPropertyInstance()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::FindInnerPropertyInstance (FName PropertyName, const void * Data, const FProperty *& OutProp, const void *& OutData) const inline override virtual
Implements UScriptStruct::ICppStructOps.
Definition at line 1609 of file Class.h.
References check, UScriptStruct::ICppStructOps::Data, PropertyName, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithFindInnerPropertyInstance.
GetCapabilities()
template<class CPPSTRUCT> virtual FCapabilities UScriptStruct::TCppStructOps< CPPSTRUCT >::GetCapabilities () const inline override virtual
returns struct capabilities
Implements UScriptStruct::ICppStructOps.
Definition at line 1354 of file Class.h.
References UScriptStruct::ICppStructOps::HasIntrusiveUnsetOptionalState(), TModels_V, TIsAbstract< T >::Value, TIsPODType< T >::Value, TIsUECoreType< T >::Value, TIsUECoreVariant< T, typename, typename >::Value, TIsZeroConstructType< T >::Value, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithAddStructReferencedObjects, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithCanEditChange, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithClearOnFinishDestroy, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithCopy, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithExportTextItem, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithFindInnerPropertyInstance, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithIdentical, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithIdenticalViaEquality, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithImportTextItem, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNetDeltaSerializer, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNetSerializer, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNetSharedSerialization, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNoDestructor, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNoInitConstructor, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithPostScriptConstruct, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithPostSerialize, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithSerializeFromMismatchedTag, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithSerializer, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithSerializerObjectReferences, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithStructuredSerializeFromMismatchedTag, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithStructuredSerializer, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithVisitor, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithZeroConstructor.
GetPreloadDependencies()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::GetPreloadDependencies (void * Data, TArray< UObject * > & OutDeps) inline override virtual
Call PreloadDependencies on this structure.
Implements UScriptStruct::ICppStructOps.
Definition at line 1515 of file Class.h.
References UScriptStruct::ICppStructOps::Data, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithGetPreloadDependencies.
GetStructTypeHash()
template<class CPPSTRUCT> uint32 UScriptStruct::TCppStructOps< CPPSTRUCT >::GetStructTypeHash (const void * Src) inline override virtual
Calls GetTypeHash if enabled.
Implements UScriptStruct::ICppStructOps.
Definition at line 1680 of file Class.h.
References ensure, GetTypeHashHelper(), UScriptStruct::ICppStructOps::HasGetTypeHash(), and TModels_V.
Identical()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::Identical (const void * A, const void * B, uint32 PortFlags, bool & bOutResult) inline override virtual
Compare this structure.
Returns
true if the comparison was performed. bOutResult contains the result of the comparison.
Implements UScriptStruct::ICppStructOps.
Definition at line 1542 of file Class.h.
References A, B, check, TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithIdentical, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithIdenticalViaEquality.
ImportTextItem()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::ImportTextItem (const TCHAR *& Buffer, void * Data, int32 PortFlags, class UObject * OwnerObject, FOutputDevice * ErrorText) inline override virtual
import this structure
Returns
true if the copy was imported, otherwise it will fall back to FStructProperty::ImportText
Implements UScriptStruct::ICppStructOps.
Definition at line 1596 of file Class.h.
References UObject::UObject(), Buffer, check, UScriptStruct::ICppStructOps::Data, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithImportTextItem.
InitializeIntrusiveUnsetOptionalValue()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::InitializeIntrusiveUnsetOptionalValue (void * Data) const inline override virtual
Construct an unset optional value.
Implements UScriptStruct::ICppStructOps.
Definition at line 1695 of file Class.h.
References UScriptStruct::ICppStructOps::Data.
IsIntrusiveOptionalSafeForGC()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::IsIntrusiveOptionalSafeForGC () const inline virtual
Used for assertions only: confirms that this type has certified that its object reference fields are safe for the GC to visit while the struct is in its intrusive unset optional state.
Implements UScriptStruct::ICppStructOps.
Definition at line 1716 of file Class.h.
References TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithIntrusiveOptionalSafeForGC.
IsIntrusiveOptionalValueSet()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::IsIntrusiveOptionalValueSet (const void * Data) const inline override virtual
Return true if the optional value at Data is in an unset state.
Implements UScriptStruct::ICppStructOps.
Definition at line 1701 of file Class.h.
References UScriptStruct::ICppStructOps::Data.
NetDeltaSerialize()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::NetDeltaSerialize (FNetDeltaSerializeInfo & DeltaParms, void * Data) inline override virtual
Net serialize delta this structure.
Serialize a network delta from a base state
Returns
true if the struct was serialized, otherwise it will fall back to ordinary script struct net delta serialization
Implements UScriptStruct::ICppStructOps.
Definition at line 1496 of file Class.h.
References UScriptStruct::ICppStructOps::Data, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNetDeltaSerializer.
NetSerialize()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess, void * Data) inline override virtual
Net serialize this structure.
Returns
true if the struct was serialized, otherwise it will fall back to ordinary script struct net serialization
Implements UScriptStruct::ICppStructOps.
Definition at line 1485 of file Class.h.
References Ar, UScriptStruct::ICppStructOps::Data, Map, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithNetSerializer.
PostScriptConstruct()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::PostScriptConstruct (void * Data) inline override virtual
Call PostScriptConstruct on this structure.
Implements UScriptStruct::ICppStructOps.
Definition at line 1507 of file Class.h.
References check, UScriptStruct::ICppStructOps::Data, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithPostScriptConstruct.
PostSerialize()
template<class CPPSTRUCT> virtual void UScriptStruct::TCppStructOps< CPPSTRUCT >::PostSerialize (const FArchive & Ar, void * Data) inline override virtual
Call PostSerialize on this structure.
Implements UScriptStruct::ICppStructOps.
Definition at line 1477 of file Class.h.
References Ar, check, UScriptStruct::ICppStructOps::Data, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithPostSerialize.
ResolveVisitedPathInfo()
template<class CPPSTRUCT> virtual void * UScriptStruct::TCppStructOps< CPPSTRUCT >::ResolveVisitedPathInfo (void * Data, const FPropertyVisitorInfo & Info) const inline override virtual
Implements UScriptStruct::ICppStructOps.
Definition at line 1749 of file Class.h.
References UScriptStruct::ICppStructOps::Data, Info, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithVisitor.
Serialize() [1/2]
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::Serialize (FArchive & Ar, void * Data, UStruct * DefaultsStruct, const void * Defaults) inline override virtual
Serialize this structure.
Returns
true if serialization was handled, false to fall back to standard script struct serialization.
Implements UScriptStruct::ICppStructOps.
Definition at line 1439 of file Class.h.
References UStruct::UStruct(), Ar, check, UScriptStruct::ICppStructOps::Data, TModels_V, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithSerializer.
Serialize() [2/2]
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::Serialize (FStructuredArchive::FSlot Slot, void * Data, UStruct * DefaultsStruct, const void * Defaults) inline override virtual
Implements UScriptStruct::ICppStructOps.
Definition at line 1458 of file Class.h.
References UStruct::UStruct(), check, UScriptStruct::ICppStructOps::Data, TModels_V, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithStructuredSerializer.
SerializeFromMismatchedTag()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::SerializeFromMismatchedTag (struct FPropertyTag const & Tag, FArchive & Ar, void * Data) inline override virtual
Serialize this structure, from some other tag.
Returns
true if this succeeded, false will trigger a warning and not serialize at all
Implements UScriptStruct::ICppStructOps.
Definition at line 1627 of file Class.h.
References Ar, check, UScriptStruct::ICppStructOps::Data, UE::FPropertyTypeName::GetName(), UE::FPropertyTypeName::GetParameterCount(), UE::FPropertyTypeName::GetParameterName(), FPropertyTag::GetType(), TIsUECoreType< T >::Value, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithSerializeFromMismatchedTag.
StructuredSerializeFromMismatchedTag()
template<class CPPSTRUCT> virtual bool UScriptStruct::TCppStructOps< CPPSTRUCT >::StructuredSerializeFromMismatchedTag (struct FPropertyTag const & Tag, FStructuredArchive::FSlot Slot, void * Data) inline override virtual
Implements UScriptStruct::ICppStructOps.
Definition at line 1652 of file Class.h.
References check, UScriptStruct::ICppStructOps::Data, UE::FPropertyTypeName::GetName(), UE::FPropertyTypeName::GetParameterCount(), UE::FPropertyTypeName::GetParameterName(), FPropertyTag::GetType(), TIsUECoreType< T >::Value, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithStructuredSerializeFromMismatchedTag.
Visit()
template<class CPPSTRUCT> virtual EPropertyVisitorControlFlow UScriptStruct::TCppStructOps< CPPSTRUCT >::Visit (FPropertyVisitorContext & Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &Context)> InFunc) const inline override virtual
Definition at line 1736 of file Class.h.
References StepOver, Struct, and TStructOpsTypeTraitsBase2< CPPSTRUCT >::WithVisitor.
The documentation for this struct was generated from the following file:
Class.h