Unreal Engine 5.6 C++ API: TBitArray< Allocator >::FIterator Class Reference
TBitArray< Allocator >::FIterator Class Reference
BitArray iterator.
#include "BitArray.h"
Public Member Functions
FORCEINLINE FIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 StartIndex=0)
FORCEINLINE int32 GetIndex () const
FORCEINLINE FBitReference GetValue () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE FBitReference operator* () const
FORCEINLINE FIterator & operator++ ()
Public Member Functions inherited from FRelativeBitReference
FORCEINLINE FRelativeBitReference (int32 BitIndex)
FORCEINLINE bool operator!= (FRelativeBitReference Other) const
FORCEINLINE bool operator== (FRelativeBitReference Other) const
Private Attributes
TBitArray< Allocator > & Array
int32 Index
Additional Inherited Members
Data Fields inherited from FRelativeBitReference
uint32 Mask
int32 WordIndex
Detailed Description
template<typename Allocator>
class TBitArray< Allocator >::FIterator
BitArray iterator.
Definition at line 1478 of file BitArray.h.
Constructor & Destructor Documentation
FIterator()
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::FIterator::FIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 StartIndex = 0) inline explicit nodiscard
Definition at line 1481 of file BitArray.h.
References FRelativeBitReference::FRelativeBitReference(), TBitArray< Allocator >::TBitArray(), Array, FORCEINLINE, Index, and UE_LIFETIMEBOUND.
Referenced by operator++().
Member Function Documentation
GetIndex()
template<typename Allocator> FORCEINLINE int32 TBitArray< Allocator >::FIterator::GetIndex () const inline nodiscard
Definition at line 1518 of file BitArray.h.
References FORCEINLINE, and Index.
GetValue()
template<typename Allocator> FORCEINLINE FBitReference TBitArray< Allocator >::FIterator::GetValue () const inline nodiscard
Definition at line 1517 of file BitArray.h.
References Array, and FORCEINLINE.
Referenced by operator*().
operator bool()
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::FIterator::operator bool () const inline explicit nodiscard
conversion to "bool" returning true if the iterator is valid.
Definition at line 1506 of file BitArray.h.
References Array, FORCEINLINE, and Index.
operator!()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::FIterator::operator! () const inline nodiscard
inverse of the "bool" operator
Definition at line 1512 of file BitArray.h.
References bool, and FORCEINLINE.
operator*()
template<typename Allocator> FORCEINLINE FBitReference TBitArray< Allocator >::FIterator::operator* () const inline nodiscard
Definition at line 1500 of file BitArray.h.
References FORCEINLINE, and GetValue().
operator++()
template<typename Allocator> FORCEINLINE FIterator & TBitArray< Allocator >::FIterator::operator++ () inline
Definition at line 1487 of file BitArray.h.
References FIterator(), FORCEINLINE, Index, and FRelativeBitReference::WordIndex.
Field Documentation
Array
template<typename Allocator> TBitArray<Allocator>& TBitArray< Allocator >::FIterator::Array private
Definition at line 1520 of file BitArray.h.
Referenced by FIterator(), GetValue(), and operator bool().
Index
template<typename Allocator> int32 TBitArray< Allocator >::FIterator::Index private
Definition at line 1521 of file BitArray.h.
Referenced by FIterator(), GetIndex(), operator bool(), and operator++().
The documentation for this class was generated from the following file:
BitArray.h