Unreal Engine 5.6 C++ API: TSetPrivateFriend Struct Reference
TSetPrivateFriend Struct Reference
#include "Set.h"
Static Public Member Functions
template<typename ElementType, typename KeyFuncs, typename Allocator>
static bool LegacyCompareEqual (const TSet< ElementType, KeyFuncs, Allocator > &A, const TSet< ElementType, KeyFuncs, Allocator > &B)
template<typename ElementType, typename KeyFuncs, typename Allocator>
static FArchive & Serialize (FArchive &Ar, TSet< ElementType, KeyFuncs, Allocator > &Set)
Serializer.
template<typename ElementType, typename KeyFuncs, typename Allocator>
static void SerializeStructured (FStructuredArchive::FSlot Slot, TSet< ElementType, KeyFuncs, Allocator > &Set)
Structured archive serializer.
Detailed Description
Definition at line 2131 of file Set.h.
Member Function Documentation
LegacyCompareEqual()
template<typename ElementType, typename KeyFuncs, typename Allocator> bool TSetPrivateFriend::LegacyCompareEqual (const TSet< ElementType, KeyFuncs, Allocator > & A, const TSet< ElementType, KeyFuncs, Allocator > & B) inline static nodiscard
Definition at line 2172 of file Set.h.
References A, and B.
Referenced by LegacyCompareEqual(), TMapPrivateFriend::LegacyCompareEqual(), and LegacyCompareNotEqual().
Serialize()
template<typename ElementType, typename KeyFuncs, typename Allocator> FArchive & TSetPrivateFriend::Serialize (FArchive & Ar, TSet< ElementType, KeyFuncs, Allocator > & Set) inline static
Serializer.
Definition at line 2135 of file Set.h.
References Ar, and No.
Referenced by operator<<().
SerializeStructured()
template<typename ElementType, typename KeyFuncs, typename Allocator> void TSetPrivateFriend::SerializeStructured (FStructuredArchive::FSlot Slot, TSet< ElementType, KeyFuncs, Allocator > & Set) inline static
Structured archive serializer.
Definition at line 2155 of file Set.h.
References UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), FArchive::IsLoading(), FArchive::IsModifyingWeakAndStrongReferences(), FArchive::IsSaving(), and No.
Referenced by operator<<().
The documentation for this struct was generated from the following file:
Set.h