Unreal Engine 5.6 C++ API: UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails Class Reference
UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails Class Reference
#include "StreamableManagerError.h"
Public Member Functions
FStreamableManagerErrorDetails (const FString &InSoftObjectPath)
virtual const FText GetErrorFormatString (const FError &Error) const override
GetErrorFormatString; Pass through to the InnerErrorDetails.
virtual void GetErrorProperties (const FError &Error, IErrorPropertyExtractor &OutProperties) const override
GetErrorProperties; by default pass through to the InnerErrorDetails.
const FString & GetSoftObjectPath () const
Public Member Functions inherited from UE::UnifiedError::FDynamicErrorDetails
FDynamicErrorDetails (TRefCountPtr< const IErrorDetails > InInnerErrorDetails=nullptr)
virtual ~FDynamicErrorDetails ()
virtual uint32 GetErrorDetailsTypeId () const
GetErrorDetialsTypeId; Simple type information for error details, generated using hash of details name See also: #define FERROR_DETAILS.
virtual const FAnsiStringView GetErrorDetailsTypeName () const override
virtual TRefCountPtr< const IErrorDetails > GetInnerErrorDetails () const
GetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
virtual void SetInnerErrorDetails (TRefCountPtr< const IErrorDetails > InInnerErrorDetails)
SetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
Public Member Functions inherited from UE::UnifiedError::FRefCountedErrorDetails
virtual ~FRefCountedErrorDetails ()
virtual FReturnedRefCountValue AddRef () const final
virtual uint32 GetRefCount () const final
virtual uint32 Release () const final
Public Member Functions inherited from UE::UnifiedError::IErrorDetails
virtual ~IErrorDetails ()=default
virtual void SerializeForLog (FCbWriter &Writer) const
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Public Member Functions inherited from FRefCountBase
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Private Member Functions
FStreamableManagerErrorDetails ()=default
DECLARE_FERROR_DETAILS (StreamableManager, FStreamableManagerErrorDetails)
Private Attributes
FText ErrorFormatString
FString SoftObjectPath
Additional Inherited Members
Static Public Member Functions inherited from UE::UnifiedError::FDynamicErrorDetails
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Member Functions inherited from UE::UnifiedError::FRefCountedErrorDetails
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Attributes inherited from UE::UnifiedError::FDynamicErrorDetails
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FDynamicErrorDetails"), nullptr)
Static Public Attributes inherited from UE::UnifiedError::FRefCountedErrorDetails
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FRefCountedErrorDetails"), nullptr)
Detailed Description
Definition at line 29 of file StreamableManagerError.h.
Constructor & Destructor Documentation
FStreamableManagerErrorDetails() [1/2]
UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::FStreamableManagerErrorDetails () private default
Referenced by DECLARE_FERROR_DETAILS().
FStreamableManagerErrorDetails() [2/2]
UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::FStreamableManagerErrorDetails (const FString & InSoftObjectPath) inline
Definition at line 38 of file StreamableManagerError.h.
References ErrorFormatString, NSLOCTEXT, and SoftObjectPath.
Member Function Documentation
DECLARE_FERROR_DETAILS()
UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::DECLARE_FERROR_DETAILS (StreamableManager , FStreamableManagerErrorDetails) private
References FStreamableManagerErrorDetails().
GetErrorFormatString()
virtual const FText UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorFormatString (const FError & Error) const inline override virtual
GetErrorFormatString; Pass through to the InnerErrorDetails.
Parameters
Error
Returns
Reimplemented from UE::UnifiedError::FDynamicErrorDetails.
Definition at line 56 of file StreamableManagerError.h.
References UE::Error, UE::UnifiedError::FDynamicErrorDetails::GetInnerErrorDetails(), FText::Join(), and NSLOCTEXT.
GetErrorProperties()
virtual void UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorProperties (const FError & Error, IErrorPropertyExtractor & OutProperties) const inline override virtual
GetErrorProperties; by default pass through to the InnerErrorDetails.
It's expected FDynamicErrorDetails will be derived from and implement GetErrorProperties.
Parameters
Error
OutProperties
Reimplemented from UE::UnifiedError::FDynamicErrorDetails.
Definition at line 44 of file StreamableManagerError.h.
References UE::UnifiedError::IErrorPropertyExtractor::AddProperty(), UE::Error, FText::Format(), UE::UnifiedError::FDynamicErrorDetails::GetErrorProperties(), UE::UnifiedError::FDynamicErrorDetails::GetInnerErrorDetails(), SoftObjectPath, and UTF8TEXTVIEW.
GetSoftObjectPath()
const FString & UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetSoftObjectPath () const inline
Definition at line 65 of file StreamableManagerError.h.
References SoftObjectPath.
Field Documentation
ErrorFormatString
FText UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::ErrorFormatString private
Definition at line 34 of file StreamableManagerError.h.
Referenced by FStreamableManagerErrorDetails().
SoftObjectPath
FString UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::SoftObjectPath private
Definition at line 33 of file StreamableManagerError.h.
Referenced by FStreamableManagerErrorDetails(), GetErrorProperties(), and GetSoftObjectPath().
The documentation for this class was generated from the following file:
StreamableManagerError.h