Unreal Engine 5.6 C++ API: UE::AnimNext Namespace Reference
UE::AnimNext Namespace Reference
Synchronization Role.
Namespaces
namespace AnimGraph
namespace Debug
namespace Editor
namespace Graph
namespace Private
namespace Tests
namespace UncookedOnly
Data Structures
struct FAdditiveTrait
class FAnimNextModuleImpl
struct FBaseTrait
struct FBlendSmootherCoreTrait
FBlendSmootherCoreTrait.
struct FBlendSmootherTrait
FBlendSmootherTrait.
struct FBlendStackCoreTrait
FBlendStackCoreTrait.
struct FBlendStackRequesterTrait
FBlendStackRequesterTrait.
struct FBlendStackTrait
FBlendStackTrait.
struct FCallFunctionTrait
FCallFunctionTrait.
struct FConstExprUID
A constexpr safe UID.
struct FDataHandle
struct FDataInterfaceStructAdapter
class FDataRegistry
struct FDeadBlendingState
FDeadBlendingState.
struct FDeadBlendTransitionTaskParameters
FDeadBlendTransitionTaskParameters.
class FDecompressionTools
struct FEvaluateGraphContext
FEvaluateGraphContext.
struct FEvaluateTraversalContext
FEvaluateTraversalContext.
struct FEvaluationProgram
struct FEvaluationVM
struct FEvaluationVMStack
struct FEvaluationVMStackEntry
struct FEvaluationVMStackName
struct FExecutionContext
Execution Context.
struct FGenerationLODData
class FGenerationTools
struct FGraphInstanceComponent
FGraphInstanceComponent.
struct FInertializationRequest
FInertializationRequest.
struct FInjectionLifetimeEvents
struct FInjectionRequest
Injection Request.
struct FInjectionUtils
struct FKeyframeState
struct FLatentPropertiesHeader
Latent Properties Header Holds metadata about the stored latent properties.
struct FLatentPropertyHandle
Latent Property Handle A latent property handle represents:
struct FLatentPropertyMetadata
Latent Property Metadata.
struct FLODPose
struct FModuleDependencyContext
struct FModuleEventTickFunction
struct FModulePendingAction
struct FModuleTaskContext
struct FModuleWriteGuard
struct FNodeDescription
Node Description A node description represents a unique instance in the authored static graph.
struct FNodeHandle
Node Handle A node handle represents a reference to a specific node instance in the shared/read-only portion of a sub-graph.
struct FNodeID
Node ID.
struct FNodeInstance
Node Instance A node instance represents allocated data for specific node.
struct FNodeTemplate
Node Template A node template represents a specific combination and ordering of traits on a node.
struct FNodeTemplateBuilder
FNodeTemplateBuilder.
struct FNodeTemplateRegistry
FNodeTemplateRegistry.
struct FNodeTemplateRegistryHandle
FNodeTemplateRegistryHandle.
struct FParamCompatibility
struct FParamUtils
struct FPlayAnimArgs
struct FPoseBoneControlAttributeMapping
struct FProxyVariablesContext
struct FPublicVariablesTraitToDataInterfaceHostAdapter
struct FRigLogicAnimNextInstanceData
struct FRigLogicBoneMapping
class FRigLogicInstanceDataPool
struct FRigLogicTrait
FRigLogicTrait.
struct FRigVMRuntimeData
struct FRigVMRuntimeDataRegistry
RigVMRuntimeDataRegistry.
struct FScopedExecuteContextData
struct FSyncGroupParameters
struct FTickFunctionBindingContext
struct FTimelineDelta
Timeline Delta.
struct FTimelineState
Timeline State.
struct FTimelineSyncMarker
struct FTrait
FTrait.
struct FTraitBinding
FTraitBinding.
struct FTraitEventLifetime
Trait Event Lifetime.
struct FTraitEventList
Trait Event List.
struct FTraitInstanceData
FTraitInstanceData A trait instance represents allocated data for specific trait instance.
struct FTraitInterfaceRegistry
FTraitInterfaceRegistry.
struct FTraitInterfaceStaticInitHook
FTraitInterfaceStaticInitHook.
struct FTraitInterfaceUID
FTraitInterfaceUID.
struct FTraitLatentPropertyMemoryLayout
FTraitLatentPropertyMemoryLayout.
struct FTraitMemoryLayout
FTraitMemoryLayout.
struct FTraitPtr
Trait Pointer A trait pointer represents a shared pointer to allocated instance data.
class FTraitReader
FTraitReader.
struct FTraitRegistry
FTraitRegistry.
struct FTraitRegistryHandle
FTraitRegistryHandle.
struct FTraitStackBinding
FTraitStackBinding.
struct FTraitStaticInitHook
FTraitStaticInitHook.
struct FTraitTemplate
Trait Template A trait template represents a specific trait within a FNodeTemplate.
struct FTraitUID
FTraitUID.
struct FTraitUpdateState
FTraitUpdateState.
class FTraitWriter
FTraitWriter.
struct FTransformArraySoAConstView
struct FTransformArraySoAView
struct FUpdateGraphContext
FUpdateGraphContext.
struct FUpdateTraversalContext
FUpdateTraversalContext.
struct FUpdateTraversalQueue
FUpdateTraversalQueue.
struct FWeakTraitPtr
Weak Trait Pointer Same as a FTraitPtr but is strongly typed to be weak.
struct IAlphaInputArgs
IAlphaInputArgs.
struct IAttributeProvider
IAttributeProvider.
struct IBlendStack
IBlendStack.
struct IContinuousBlend
IContinuousBlend.
class IDataInterfaceHost
struct IDiscreteBlend
IDiscreteBlend.
struct IEvaluate
IEvaluate.
struct IEvaluationModifier
struct IGarbageCollection
IGarbageCollection.
struct IGraphFactory
IGraphFactory.
struct IGroupSynchronization
IGroupSynchronization.
struct IHierarchy
IHierarchy.
struct IInertializerBlend
IInertializerBlend.
struct INotifySource
INotifySource.
struct IScopedTraitInterface
IScopedTraitInterface.
struct ISmoothBlend
ISmoothBlend.
struct ISmoothBlendPerBone
ISmoothBlendPerBone.
struct ITimeline
ITimeline.
struct ITimelinePlayer
ITimelinePlayer.
struct ITraitInterface
ITraitInterface.
struct IUpdate
IUpdate.
struct IUpdateTraversal
IUpdateTraversal.
struct TLODPose
class TPool
struct TPoolHandle
struct TReferencePose
struct TTraitBinding
TTraitBinding.
struct TTraitBinding< IAlphaInputArgs >
Specialization for trait binding.
struct TTraitBinding< IAttributeProvider >
Specialization for trait binding.
struct TTraitBinding< IBlendStack >
Specialization for trait binding.
struct TTraitBinding< IContinuousBlend >
Specialization for trait binding.
struct TTraitBinding< IDiscreteBlend >
Specialization for trait binding.
struct TTraitBinding< IEvaluate >
Specialization for trait binding.
struct TTraitBinding< IGarbageCollection >
Specialization for trait binding.
struct TTraitBinding< IGraphFactory >
Specialization for trait binding.
struct TTraitBinding< IGroupSynchronization >
Specialization for trait binding.
struct TTraitBinding< IHierarchy >
Specialization for trait binding.
struct TTraitBinding< IInertializerBlend >
Specialization for trait binding.
struct TTraitBinding< INotifySource >
Specialization for trait binding.
struct TTraitBinding< ISmoothBlend >
Specialization for trait binding.
struct TTraitBinding< ISmoothBlendPerBone >
Specialization for trait binding.
struct TTraitBinding< ITimeline >
Specialization for trait binding.
struct TTraitBinding< ITimelinePlayer >
Specialization for trait binding.
struct TTraitBinding< IUpdate >
Specialization for trait binding.
struct TTraitBinding< IUpdateTraversal >
Specialization for trait binding.
struct TTransformArrayAoS
struct TTransformArraySoA
Transform Array Test using StructOfArrays model.
struct TTransformSoAAdapter
Typedefs
using EInjectionBlendMode = EAnimNextInjectionBlendMode
using EInjectionStatus = EAnimNextInjectionStatus
using FChildrenArray = TArray<FWeakTraitPtr, TInlineAllocator<8, TMemStackAllocator<>>>
using FFConstExprUIDRaw = uint32
using FInjectionBlendSettings = FAnimNextInjectionBlendSettings
using FInjectionRequestArgs = FAnimNextInjectionRequestArgs
using FInjectionRequestPtr = TSharedPtr<FInjectionRequest, ESPMode::ThreadSafe>
using FInjectionSite = FAnimNextInjectionSite
using FLODPoseHeap = TLODPose<FDefaultAllocator>
using FLODPoseStack = TLODPose<FAnimStackAllocator>
using FModuleEventBindingFunction = TFunction<void(const FTickFunctionBindingContext& InContext, FTickFunction& InTickFunction)>
using FModuleHandle = TPoolHandle<FAnimNextModuleInstance>
using FOnPreModuleEvent = TTSMulticastDelegate<void(const FModuleTaskContext& InContext)>
using FReferencePose = TReferencePose<FDefaultAllocator, FDefaultSetAllocator>
Hide the allocator usage.
using FRigVMRuntimeDataID = TObjectKey<URigVM>
using FTimelineSyncMarkerArray = TArray<FTimelineSyncMarker, TInlineAllocator<8, TMemStackAllocator<>>>
using FTraitEventUID = UE::AnimNext::FConstExprUID
using FTraitInterfaceUIDRaw = uint32
using FTraitUIDRaw = uint32
using FTransformArray = FTransformArraySoAHeap
using FTransformArrayAoSConstView = TArrayView<const FTransform>
using FTransformArrayAoSHeap = TTransformArrayAoS<FDefaultAllocator>
Transform Array using ArrayOfStructs model.
using FTransformArrayAoSStack = TTransformArrayAoS<FAnimStackAllocator>
using FTransformArrayAoSView = TArrayView<FTransform>
using FTransformArrayConstView = FTransformArraySoAConstView
using FTransformArrayHeap = FTransformArraySoAHeap
using FTransformArraySoAHeap = TTransformArraySoA<FDefaultAllocator>
Transform Array using StructsOfArrays model.
using FTransformArraySoAStack = TTransformArraySoA<FAnimStackAllocator>
using FTransformArrayStack = FTransformArraySoAStack
using FTransformArrayView = FTransformArraySoAView
using FTransformSoAAdapter = TTransformSoAAdapter<FQuat, FVector, FVector>
using FTransformSoAAdapterConst = TTransformSoAAdapter<const FQuat, const FVector, const FVector>
using ModuleInstanceComponentMapType = TMap<FName, TInstancedStruct<FAnimNextModuleInstanceComponent>>
using TraitConstructorFunc = FTrait * (*)(void* DestPtr, FTraitMemoryLayout& MemoryDesc)
template<typename AllocatorType>
using TTransformArray = TTransformArraySoA<AllocatorType>
Enumerations
enum class EEvaluationFlags {
None = 0x00 , Trajectory = 0x01 , Bones = 0x02 , Curves = 0x04 ,
Attributes = 0x08 , All = 0xff
}
enum class ELODPoseFlags : uint8 {
None = 0 , Additive = 1 << 0 , DisableRetargeting = 1 << 1 , UseRawData = 1 << 2 ,
UseSourceData = 1 << 3 , MeshSpaceAdditive = 1 << 4 , LocalSpaceAdditive = 1 << 5
}
enum class ELoopMode : uint8 { Auto , ForceLoop , ForceNonLoop }
enum class EModuleEventPhase : uint8 { PreExecute , Execute }
enum class EParamCompatibility : int32 {
Incompatible , Incompatible_DataLoss , Compatible_Promotion , Compatible_Cast ,
Compatible_Equal
}
enum class EReferencePoseGenerationFlags : uint8 { None = 0 , FastPath = 1 << 0 }
enum class ETaskRunLocation : int32 { Before , After }
enum class ETraitMode { Invalid = 0 , Base , Additive , Num = Additive }
ETraitMode.
enum class ETraitStackPropagation { Continue , Stop }
Trait Stack Propagation.
enum class ETransformFlags : uint8 { None = 0 , ComponentSpaceSet = 1 << 0 }
Functions
ANIMNEXT_API void BlendAddPerBoneWithScale (const FTransformArrayAoSView &Dest, const FTransformArrayAoSConstView &Source, const TArrayView< const int32 > &LODBoneIndexToWeightIndexMap, const TArrayView< const float > &BoneWeights, const float DefaultScaleWeight)
ANIMNEXT_API void BlendAddPerBoneWithScale (const FTransformArraySoAView &Dest, const FTransformArraySoAConstView &Source, const TArrayView< const int32 > &LODBoneIndexToWeightIndexMap, const TArrayView< const float > &BoneWeights, const float DefaultScaleWeight)
ANIMNEXT_API void BlendAddWithScale (const FTransformArrayAoSView &Dest, const FTransformArrayAoSConstView &Source, const float ScaleWeight)
ANIMNEXT_API void BlendAddWithScale (const FTransformArraySoAView &Dest, const FTransformArraySoAConstView &Source, const float ScaleWeight)
ANIMNEXT_API void BlendOverwritePerBoneWithScale (const FTransformArrayAoSView &Dest, const FTransformArrayAoSConstView &Source, const TArrayView< const int32 > &LODBoneIndexToWeightIndexMap, const TArrayView< const float > &BoneWeights, const float DefaultScaleWeight, const bool bInvert=false)
ANIMNEXT_API void BlendOverwritePerBoneWithScale (const FTransformArraySoAView &Dest, const FTransformArraySoAConstView &Source, const TArrayView< const int32 > &LODBoneIndexToWeightIndexMap, const TArrayView< const float > &BoneWeights, const float DefaultScaleWeight, const bool bInvert=false)
ANIMNEXT_API void BlendOverwriteWithScale (const FTransformArrayAoSView &Dest, const FTransformArrayAoSConstView &Source, const float ScaleWeight)
ANIMNEXT_API void BlendOverwriteWithScale (const FTransformArraySoAView &Dest, const FTransformArraySoAConstView &Source, const float ScaleWeight)
ANIMNEXT_API void BlendWithIdentityAndAccumulate (const FTransformArrayAoSView &Base, const FTransformArrayAoSConstView &Additive, const float BlendWeight)
ANIMNEXT_API void BlendWithIdentityAndAccumulate (const FTransformArraySoAView &Base, const FTransformArraySoAConstView &Additive, const float BlendWeight)
ANIMNEXT_API void BlendWithIdentityAndAccumulateMesh (const FTransformArrayAoSView &Base, const FTransformArrayAoSConstView &Additive, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap, const float BlendWeight)
ANIMNEXT_API void BlendWithIdentityAndAccumulateMesh (const FTransformArraySoAView &Base, const FTransformArraySoAConstView &Additive, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap, const float BlendWeight)
ANIMNEXT_API void ConvertPoseLocalToMeshRotation (const FTransformArrayAoSView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void ConvertPoseLocalToMeshRotation (const FTransformArraySoAView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void ConvertPoseLocalToMeshRotationTranslation (const FTransformArrayAoSView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void ConvertPoseLocalToMeshRotationTranslation (const FTransformArraySoAView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void ConvertPoseMeshToLocalRotation (const FTransformArrayAoSView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void ConvertPoseMeshToLocalRotation (const FTransformArraySoAView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void ConvertPoseMeshToLocalRotationTranslation (const FTransformArrayAoSView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void ConvertPoseMeshToLocalRotationTranslation (const FTransformArraySoAView &Input, const TArrayView< const FBoneIndexType > &LODBoneIndexToParentLODBoneIndexMap)
ANIMNEXT_API void CopyTransforms (const FTransformArrayAoSView &Dest, const FTransformArrayAoSConstView &Source, int32 StartIndex=0, int32 NumToCopy=-1)
ANIMNEXT_API void CopyTransforms (const FTransformArraySoAView &Dest, const FTransformArraySoAConstView &Source, int32 StartIndex=0, int32 NumToCopy=-1)
const FInjectionRequest & DECLARE_DELEGATE_OneParam (FAnimNextOnInjectionInterrupted, const FInjectionRequest &) DECLARE_DELEGATE_OneParam(FAnimNextOnInjectionBlendingOut
DECLARE_DELEGATE_OneParam (FAnimNextOnInjectionStarted, const FInjectionRequest &) DECLARE_DELEGATE_OneParam(FAnimNextOnInjectionCompleted
DECLARE_DELEGATE_RetVal_ThreeParams (FTransform, FOnExtractRootMotionAttribute, float, float, bool)
Root motion attribute sampling may occur during execution (Ex: Conditionally sampling attributes based on active root motion).
ANIMNEXT_API void DecrementLifetimeAndPurgeExpired (FTraitEventList &EventList, FTraitEventList &OutputEventList)
template<typename Type>
void DestructType (void *Ptr)
ENUM_CLASS_FLAGS (ELODPoseFlags)
ENUM_CLASS_FLAGS (EReferencePoseGenerationFlags)
ANIMNEXTANIMGRAPH_API FEvaluationProgram EvaluateGraph (const FEvaluateGraphContext &EvaluateGraphContext)
Evaluates a sub-graph starting at its root and produces an evaluation program.
ANIMNEXTANIMGRAPH_API FEvaluationProgram EvaluateGraph (const FEvaluateGraphContext &EvaluateGraphContext, const FWeakTraitPtr &GraphRootPtr)
Evaluates a sub-graph starting at its root and produces an evaluation program.
ANIMNEXTANIMGRAPH_API void EvaluateGraph (const FEvaluateGraphContext &EvaluateGraphContext, FAnimNextGraphLODPose &OutputPose)
Evaluates a sub-graph starting at its root and produces an output pose.
template<typename Type>
TFunction< void(void *)> GetTypeDestructor ()
template<typename Type>
constexpr uint32 GetTypeID ()
template<>
constexpr uint32 GetTypeID< TUniquePtr< FKeyframeState > > ()
template<>
constexpr uint32 GetTypeID< TUniquePtr< UE::PoseSearch::FPoseHistoryEvaluationHelper > > ()
FInjectionRequestPtr MakeInjectionRequest ()
ANIMNEXT_API void NormalizeRotations (const FTransformArrayAoSView &Input)
ANIMNEXT_API void NormalizeRotations (const FTransformArraySoAView &Input)
constexpr bool operator!= (FConstExprUID LHS, FConstExprUID RHS) noexcept
constexpr bool operator!= (FConstExprUID LHS, FFConstExprUIDRaw RHS) noexcept
constexpr bool operator!= (FFConstExprUIDRaw LHS, FConstExprUID RHS) noexcept
constexpr bool operator!= (FTraitInterfaceUID LHS, FTraitInterfaceUID RHS)
constexpr bool operator!= (FTraitUID LHS, FTraitUID RHS) noexcept
constexpr bool operator!= (FTraitUID LHS, FTraitUIDRaw RHS) noexcept
constexpr bool operator!= (FTraitUIDRaw LHS, FTraitUID RHS) noexcept
constexpr bool operator< (FConstExprUID LHS, FConstExprUID RHS)
constexpr bool operator< (FTraitInterfaceUID LHS, FTraitInterfaceUID RHS)
FArchive & operator<< (FArchive &Ar, FLatentPropertyHandle &Handle)
FArchive & operator<< (FArchive &Ar, FLatentPropertyMetadata &Metadata)
constexpr bool operator== (FConstExprUID LHS, FConstExprUID RHS) noexcept
constexpr bool operator== (FConstExprUID LHS, FFConstExprUIDRaw RHS) noexcept
constexpr bool operator== (FFConstExprUIDRaw LHS, FConstExprUID RHS) noexcept
constexpr bool operator== (FTraitInterfaceUID LHS, FTraitInterfaceUID RHS)
constexpr bool operator== (FTraitUID LHS, FTraitUID RHS) noexcept
constexpr bool operator== (FTraitUID LHS, FTraitUIDRaw RHS) noexcept
constexpr bool operator== (FTraitUIDRaw LHS, FTraitUID RHS) noexcept
ANIMNEXTANIMGRAPH_API void RaiseTraitEvent (FExecutionContext &Context, const FTraitStackBinding &StackBinding, FAnimNextTraitEvent &Event)
ANIMNEXTANIMGRAPH_API void RaiseTraitEvents (FExecutionContext &Context, const FTraitStackBinding &StackBinding, const FTraitEventList &EventList)
ANIMNEXTANIMGRAPH_API void RaiseTraitEvents (FExecutionContext &Context, FGraphInstanceComponent &Component, const FTraitEventList &EventList)
ANIMNEXT_API void SetIdentity (const FTransformArrayAoSView &Dest, bool bIsAdditive)
ANIMNEXT_API void SetIdentity (const FTransformArrayAoSView &Dest, bool bIsAdditive, int32 StartIndex, int32 NumTransformsToSet)
ANIMNEXT_API void SetIdentity (const FTransformArraySoAView &Dest, bool bIsAdditive)
ANIMNEXT_API void SetIdentity (const FTransformArraySoAView &Dest, bool bIsAdditive, int32 StartIndex, int32 NumTransformsToSet)
ANIMNEXTANIMGRAPH_API void UpdateGraph (FUpdateGraphContext &UpdateGraphContext)
Updates a sub-graph starting at its root.
Variables
ANIMNEXTANIMGRAPH_API const FEvaluationVMStackName KEYFRAME_STACK_NAME
const FTransform ANIMNEXT_API TransformAdditiveIdentity
Detailed Description
Synchronization Role.
Timelines part of a named group will synchronize together. To do so, a leader is first identified. The remaining members of the group will be followers. The synchronization role for a member of the group determines which role it can play within that group. Synchronization Mode
Timelines part of a named group can be synchronized together. When synchronization is enabled, two options are presented:
A user specified group name can be used
A uniquely generated group name can be used
Having an explicitly specified group name is useful to synchronize different things together (e.g. two anim sequences). However, sometimes we want certain things to synchronize only within themselves (e.g. blend space). This is called self-synchronization. This arises when we want to specify the synchronization behavior at a higher level than individual timelines. In such cases, we cannot use a user supplied group because every instance would then attempt to use the same group name, which can be problematic. Consider a blend space embedded within a sub-graph that can blend with itself (e.g. is re-entrant). This commonly occurs when blend stacks are used (e.g. through motion matching). We would like the anim sequences within the blend space to self-synchronize but we do not want those to synchronize with other instances of the same blend space. To solve this, every instance of the blend space needs a unique group name.
Typedef Documentation
EInjectionBlendMode
using UE::AnimNext::EInjectionBlendMode = EAnimNextInjectionBlendMode
Definition at line 154 of file InjectionRequest.h.
EInjectionStatus
using UE::AnimNext::EInjectionStatus = EAnimNextInjectionStatus
Definition at line 50 of file InjectionStatus.h.
FChildrenArray
using UE::AnimNext::FChildrenArray = TArray<FWeakTraitPtr, TInlineAllocator<8, TMemStackAllocator<>>>
Definition at line 15 of file IHierarchy.h.
FFConstExprUIDRaw
using UE::AnimNext::FFConstExprUIDRaw = uint32
Definition at line 11 of file ConstExprUID.h.
FInjectionBlendSettings
using UE::AnimNext::FInjectionBlendSettings = FAnimNextInjectionBlendSettings
Definition at line 155 of file InjectionRequest.h.
FInjectionRequestArgs
using UE::AnimNext::FInjectionRequestArgs = FAnimNextInjectionRequestArgs
Definition at line 156 of file InjectionRequest.h.
FInjectionRequestPtr
using UE::AnimNext::FInjectionRequestPtr = TSharedPtr<FInjectionRequest, ESPMode::ThreadSafe>
Definition at line 285 of file InjectionRequest.h.
FInjectionSite
using UE::AnimNext::FInjectionSite = FAnimNextInjectionSite
Definition at line 43 of file InjectionSite.h.
FLODPoseHeap
using UE::AnimNext::FLODPoseHeap = TLODPose<FDefaultAllocator>
Definition at line 374 of file LODPose.h.
FLODPoseStack
using UE::AnimNext::FLODPoseStack = TLODPose<FAnimStackAllocator>
Definition at line 375 of file LODPose.h.
FModuleEventBindingFunction
using UE::AnimNext::FModuleEventBindingFunction = TFunction<void(const FTickFunctionBindingContext& InContext, FTickFunction& InTickFunction)>
Definition at line 34 of file ModuleEventTickFunctionBindings.h.
FModuleHandle
using UE::AnimNext::FModuleHandle = TPoolHandle<FAnimNextModuleInstance>
Definition at line 15 of file ModuleHandle.h.
FOnPreModuleEvent
using UE::AnimNext::FOnPreModuleEvent = TTSMulticastDelegate<void(const FModuleTaskContext& InContext)>
Definition at line 21 of file ModuleTickFunction.h.
FReferencePose
using UE::AnimNext::FReferencePose = TReferencePose<FDefaultAllocator, FDefaultSetAllocator>
Hide the allocator usage.
Definition at line 330 of file ReferencePose.h.
FRigVMRuntimeDataID
using UE::AnimNext::FRigVMRuntimeDataID = TObjectKey<URigVM>
Definition at line 14 of file RigVMRuntimeDataRegistry.h.
FTimelineSyncMarkerArray
using UE::AnimNext::FTimelineSyncMarkerArray = TArray<FTimelineSyncMarker, TInlineAllocator<8, TMemStackAllocator<>>>
Definition at line 43 of file ITimeline.h.
FTraitEventUID
using UE::AnimNext::FTraitEventUID = UE::AnimNext::FConstExprUID
Definition at line 17 of file TraitEvent.h.
FTraitInterfaceUIDRaw
using UE::AnimNext::FTraitInterfaceUIDRaw = uint32
Definition at line 11 of file TraitInterfaceUID.h.
FTraitUIDRaw
using UE::AnimNext::FTraitUIDRaw = uint32
Definition at line 11 of file TraitUID.h.
FTransformArray
using UE::AnimNext::FTransformArray = FTransformArraySoAHeap
Definition at line 677 of file TransformArray.h.
FTransformArrayAoSConstView
using UE::AnimNext::FTransformArrayAoSConstView = TArrayView<const FTransform>
Definition at line 88 of file TransformArrayView.h.
FTransformArrayAoSHeap
using UE::AnimNext::FTransformArrayAoSHeap = TTransformArrayAoS<FDefaultAllocator>
Transform Array using ArrayOfStructs model.
Definition at line 270 of file TransformArray.h.
FTransformArrayAoSStack
using UE::AnimNext::FTransformArrayAoSStack = TTransformArrayAoS<FAnimStackAllocator>
Definition at line 271 of file TransformArray.h.
FTransformArrayAoSView
using UE::AnimNext::FTransformArrayAoSView = TArrayView<FTransform>
Definition at line 87 of file TransformArrayView.h.
FTransformArrayConstView
using UE::AnimNext::FTransformArrayConstView = FTransformArraySoAConstView
Definition at line 193 of file TransformArrayView.h.
FTransformArrayHeap
using UE::AnimNext::FTransformArrayHeap = FTransformArraySoAHeap
Definition at line 674 of file TransformArray.h.
FTransformArraySoAHeap
using UE::AnimNext::FTransformArraySoAHeap = TTransformArraySoA<FDefaultAllocator>
Transform Array using StructsOfArrays model.
Definition at line 663 of file TransformArray.h.
FTransformArraySoAStack
using UE::AnimNext::FTransformArraySoAStack = TTransformArraySoA<FAnimStackAllocator>
Definition at line 664 of file TransformArray.h.
FTransformArrayStack
using UE::AnimNext::FTransformArrayStack = FTransformArraySoAStack
Definition at line 675 of file TransformArray.h.
FTransformArrayView
using UE::AnimNext::FTransformArrayView = FTransformArraySoAView
Definition at line 192 of file TransformArrayView.h.
FTransformSoAAdapter
using UE::AnimNext::FTransformSoAAdapter = TTransformSoAAdapter<FQuat, FVector, FVector>
Definition at line 84 of file TransformArrayView.h.
FTransformSoAAdapterConst
using UE::AnimNext::FTransformSoAAdapterConst = TTransformSoAAdapter<const FQuat, const FVector, const FVector>
Definition at line 85 of file TransformArrayView.h.
ModuleInstanceComponentMapType
using UE::AnimNext::ModuleInstanceComponentMapType = TMap<FName, TInstancedStruct<FAnimNextModuleInstanceComponent>>
Definition at line 46 of file AnimNextModuleInstance.h.
TraitConstructorFunc
using UE::AnimNext::TraitConstructorFunc = FTrait * (*)(void* DestPtr, FTraitMemoryLayout& MemoryDesc)
Definition at line 301 of file Trait.h.
TTransformArray
template<typename AllocatorType> using UE::AnimNext::TTransformArray = TTransformArraySoA<AllocatorType>
Definition at line 672 of file TransformArray.h.
Enumeration Type Documentation
EEvaluationFlags
enum class UE::AnimNext::EEvaluationFlags strong
Enumerator
None
Trajectory
Bones
Curves
Attributes
All
Definition at line 10 of file EvaluationFlags.h.
ELODPoseFlags
enum class UE::AnimNext::ELODPoseFlags : uint8 strong
Enumerator
None
Additive
DisableRetargeting
UseRawData
UseSourceData
MeshSpaceAdditive
LocalSpaceAdditive
Definition at line 18 of file LODPose.h.
ELoopMode
enum class UE::AnimNext::ELoopMode : uint8 strong
Enumerator
Auto
ForceLoop
ForceNonLoop
Definition at line 20 of file InjectionUtils.h.
EModuleEventPhase
enum class UE::AnimNext::EModuleEventPhase : uint8 strong
Enumerator
PreExecute
Execute
Definition at line 16 of file RigUnit_AnimNextModuleEvents.h.
EParamCompatibility
enum class UE::AnimNext::EParamCompatibility : int32 strong
Enumerator
Incompatible
Incompatible_DataLoss
Compatible_Promotion
Compatible_Cast
Compatible_Equal
Definition at line 10 of file ParamCompatibility.h.
EReferencePoseGenerationFlags
enum class UE::AnimNext::EReferencePoseGenerationFlags : uint8 strong
Enumerator
None
FastPath
Definition at line 23 of file ReferencePose.h.
ETaskRunLocation
enum class UE::AnimNext::ETaskRunLocation : int32 strong
Enumerator
Before
After
Definition at line 10 of file TaskRunLocation.h.
ETraitMode
enum class UE::AnimNext::ETraitMode strong
ETraitMode.
Describes how a trait behaves once attached to an animation node.
Enumerator
Invalid
Invalid value is used for default variable initialization.
Base
Base traits can live on their own in an animation node and have no 'Super'.
As a result, calls to GetInterface() do not forward to other traits below them on the node stack. Multiple base traits can exist in a single animation node but they behave as independent nodes (functionally speaking).
Additive
Additive traits override or augment behavior on prior traits on the node stack.
At least one base trait must be present for an additive trait to be added on top. Calls to GetInterface() will pass-through to other traits below on the stack until a base trait is found.
Num
Max value is used for iteration / static checks.
Definition at line 14 of file TraitMode.h.
ETraitStackPropagation
enum class UE::AnimNext::ETraitStackPropagation strong
Trait Stack Propagation.
This enum can be used to signal whether an interface call should be forwarded to its parent on the trait stack or not.
Enumerator
Continue
Stop
Definition at line 68 of file ITraitInterface.h.
ETransformFlags
enum class UE::AnimNext::ETransformFlags : uint8 strong
Enumerator
None
ComponentSpaceSet
Definition at line 166 of file DataRegistryTypes.h.
Function Documentation
BlendAddPerBoneWithScale() [1/2]
ANIMNEXT_API void UE::AnimNext::BlendAddPerBoneWithScale (const FTransformArrayAoSView & Dest, const FTransformArrayAoSConstView & Source, const TArrayView< const int32 > & LODBoneIndexToWeightIndexMap, const TArrayView< const float > & BoneWeights, const float DefaultScaleWeight)
References Source.
BlendAddPerBoneWithScale() [2/2]
ANIMNEXT_API void UE::AnimNext::BlendAddPerBoneWithScale (const FTransformArraySoAView & Dest, const FTransformArraySoAConstView & Source, const TArrayView< const int32 > & LODBoneIndexToWeightIndexMap, const TArrayView< const float > & BoneWeights, const float DefaultScaleWeight)
References Source.
BlendAddWithScale() [1/2]
ANIMNEXT_API void UE::AnimNext::BlendAddWithScale (const FTransformArrayAoSView & Dest, const FTransformArrayAoSConstView & Source, const float ScaleWeight)
References Source.
BlendAddWithScale() [2/2]
ANIMNEXT_API void UE::AnimNext::BlendAddWithScale (const FTransformArraySoAView & Dest, const FTransformArraySoAConstView & Source, const float ScaleWeight)
References Source.
BlendOverwritePerBoneWithScale() [1/2]
ANIMNEXT_API void UE::AnimNext::BlendOverwritePerBoneWithScale (const FTransformArrayAoSView & Dest, const FTransformArrayAoSConstView & Source, const TArrayView< const int32 > & LODBoneIndexToWeightIndexMap, const TArrayView< const float > & BoneWeights, const float DefaultScaleWeight, const bool bInvert = false)
References Source.
BlendOverwritePerBoneWithScale() [2/2]
ANIMNEXT_API void UE::AnimNext::BlendOverwritePerBoneWithScale (const FTransformArraySoAView & Dest, const FTransformArraySoAConstView & Source, const TArrayView< const int32 > & LODBoneIndexToWeightIndexMap, const TArrayView< const float > & BoneWeights, const float DefaultScaleWeight, const bool bInvert = false)
References Source.
BlendOverwriteWithScale() [1/2]
ANIMNEXT_API void UE::AnimNext::BlendOverwriteWithScale (const FTransformArrayAoSView & Dest, const FTransformArrayAoSConstView & Source, const float ScaleWeight)
References Source.
BlendOverwriteWithScale() [2/2]
ANIMNEXT_API void UE::AnimNext::BlendOverwriteWithScale (const FTransformArraySoAView & Dest, const FTransformArraySoAConstView & Source, const float ScaleWeight)
References Source.
BlendWithIdentityAndAccumulate() [1/2]
ANIMNEXT_API void UE::AnimNext::BlendWithIdentityAndAccumulate (const FTransformArrayAoSView & Base, const FTransformArrayAoSConstView & Additive, const float BlendWeight)
References Additive, and Base.
BlendWithIdentityAndAccumulate() [2/2]
ANIMNEXT_API void UE::AnimNext::BlendWithIdentityAndAccumulate (const FTransformArraySoAView & Base, const FTransformArraySoAConstView & Additive, const float BlendWeight)
References Additive, and Base.
BlendWithIdentityAndAccumulateMesh() [1/2]
ANIMNEXT_API void UE::AnimNext::BlendWithIdentityAndAccumulateMesh (const FTransformArrayAoSView & Base, const FTransformArrayAoSConstView & Additive, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap, const float BlendWeight)
References Additive, and Base.
BlendWithIdentityAndAccumulateMesh() [2/2]
ANIMNEXT_API void UE::AnimNext::BlendWithIdentityAndAccumulateMesh (const FTransformArraySoAView & Base, const FTransformArraySoAConstView & Additive, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap, const float BlendWeight)
References Additive, and Base.
ConvertPoseLocalToMeshRotation() [1/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseLocalToMeshRotation (const FTransformArrayAoSView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
ConvertPoseLocalToMeshRotation() [2/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseLocalToMeshRotation (const FTransformArraySoAView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
ConvertPoseLocalToMeshRotationTranslation() [1/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseLocalToMeshRotationTranslation (const FTransformArrayAoSView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
ConvertPoseLocalToMeshRotationTranslation() [2/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseLocalToMeshRotationTranslation (const FTransformArraySoAView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
ConvertPoseMeshToLocalRotation() [1/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseMeshToLocalRotation (const FTransformArrayAoSView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
ConvertPoseMeshToLocalRotation() [2/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseMeshToLocalRotation (const FTransformArraySoAView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
ConvertPoseMeshToLocalRotationTranslation() [1/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseMeshToLocalRotationTranslation (const FTransformArrayAoSView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
ConvertPoseMeshToLocalRotationTranslation() [2/2]
ANIMNEXT_API void UE::AnimNext::ConvertPoseMeshToLocalRotationTranslation (const FTransformArraySoAView & Input, const TArrayView< const FBoneIndexType > & LODBoneIndexToParentLODBoneIndexMap)
References Input.
CopyTransforms() [1/2]
ANIMNEXT_API void UE::AnimNext::CopyTransforms (const FTransformArrayAoSView & Dest, const FTransformArrayAoSConstView & Source, int32 StartIndex = 0, int32 NumToCopy = -1)
References Source.
Referenced by UE::AnimNext::FLODPose::CopyFrom(), and UE::AnimNext::FLODPose::SetRefPose().
CopyTransforms() [2/2]
ANIMNEXT_API void UE::AnimNext::CopyTransforms (const FTransformArraySoAView & Dest, const FTransformArraySoAConstView & Source, int32 StartIndex = 0, int32 NumToCopy = -1)
References Source.
DECLARE_DELEGATE_OneParam() [1/2]
const FInjectionRequest & UE::AnimNext::DECLARE_DELEGATE_OneParam (FAnimNextOnInjectionInterrupted , const FInjectionRequest &)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [2/2]
UE::AnimNext::DECLARE_DELEGATE_OneParam (FAnimNextOnInjectionStarted , const FInjectionRequest &)
Referenced by DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_RetVal_ThreeParams()
UE::AnimNext::DECLARE_DELEGATE_RetVal_ThreeParams (FTransform , FOnExtractRootMotionAttribute , float , float , bool)
Root motion attribute sampling may occur during execution (Ex: Conditionally sampling attributes based on active root motion).
This signature is used to support that deferred execution, each implementing trait is responsible for ensuring callback lifetimes.
DecrementLifetimeAndPurgeExpired()
ANIMNEXT_API void UE::AnimNext::DecrementLifetimeAndPurgeExpired (FTraitEventList & EventList, FTraitEventList & OutputEventList)
DestructType()
template<typename Type> void UE::AnimNext::DestructType (void * Ptr) inline
Definition at line 41 of file EvaluationVM.h.
Referenced by GetTypeDestructor().
ENUM_CLASS_FLAGS() [1/2]
UE::AnimNext::ENUM_CLASS_FLAGS (ELODPoseFlags)
ENUM_CLASS_FLAGS() [2/2]
UE::AnimNext::ENUM_CLASS_FLAGS (EReferencePoseGenerationFlags)
EvaluateGraph() [1/3]
ANIMNEXTANIMGRAPH_API FEvaluationProgram UE::AnimNext::EvaluateGraph (const FEvaluateGraphContext & EvaluateGraphContext) nodiscard
Evaluates a sub-graph starting at its root and produces an evaluation program.
Evaluation should be deterministic and repeated calls should yield the same evaluation program.
For each node:
We call PreEvaluate on all its traits
We call GetChildren on all its traits
We evaluate all children found
We call PostEvaluate on all its traits
See also
IEvaluate::PreEvaluate, IEvaluate::PostEvaluate, IHierarchy::GetChildren
EvaluateGraph() [2/3]
ANIMNEXTANIMGRAPH_API FEvaluationProgram UE::AnimNext::EvaluateGraph (const FEvaluateGraphContext & EvaluateGraphContext, const FWeakTraitPtr & GraphRootPtr) nodiscard
Evaluates a sub-graph starting at its root and produces an evaluation program.
Evaluation starts at the top of the stack that includes the graph root trait. Evaluation should be deterministic and repeated calls should yield the same evaluation program.
For each node:
We call PreEvaluate on all its traits
We call GetChildren on all its traits
We evaluate all children found
We call PostEvaluate on all its traits
See also
IEvaluate::PreEvaluate, IEvaluate::PostEvaluate, IHierarchy::GetChildren
EvaluateGraph() [3/3]
ANIMNEXTANIMGRAPH_API void UE::AnimNext::EvaluateGraph (const FEvaluateGraphContext & EvaluateGraphContext, FAnimNextGraphLODPose & OutputPose)
Evaluates a sub-graph starting at its root and produces an output pose.
GetTypeDestructor()
template<typename Type> TFunction< void(void *)> UE::AnimNext::GetTypeDestructor () inline
Definition at line 47 of file EvaluationVM.h.
References DestructType().
Referenced by UE::AnimNext::FEvaluationVM::PushValue().
GetTypeID()
template<typename Type> uint32 UE::AnimNext::GetTypeID () constexpr
Definition at line 32 of file EvaluationVM.h.
Referenced by UE::AnimNext::FEvaluationVM::PeekValue(), UE::AnimNext::FEvaluationVM::PeekValueMutable(), UE::AnimNext::FEvaluationVM::PopValue(), and UE::AnimNext::FEvaluationVM::PushValue().
GetTypeID< TUniquePtr< FKeyframeState > >()
template<> uint32 UE::AnimNext::GetTypeID< TUniquePtr< FKeyframeState > > () constexpr
Definition at line 308 of file EvaluationVM.h.
GetTypeID< TUniquePtr< UE::PoseSearch::FPoseHistoryEvaluationHelper > >()
template<> uint32 UE::AnimNext::GetTypeID< TUniquePtr< UE::PoseSearch::FPoseHistoryEvaluationHelper > > () constexpr
Definition at line 20 of file PoseHistoryEvaluation.h.
MakeInjectionRequest()
FInjectionRequestPtr UE::AnimNext::MakeInjectionRequest () inline
Definition at line 288 of file InjectionRequest.h.
References MakeInjectionRequest(), and MakeShared().
Referenced by MakeInjectionRequest().
NormalizeRotations() [1/2]
ANIMNEXT_API void UE::AnimNext::NormalizeRotations (const FTransformArrayAoSView & Input)
References Input.
NormalizeRotations() [2/2]
ANIMNEXT_API void UE::AnimNext::NormalizeRotations (const FTransformArraySoAView & Input)
References Input.
operator!=() [1/7]
bool UE::AnimNext::operator!= (FConstExprUID LHS, FConstExprUID RHS) constexpr noexcept
Definition at line 71 of file ConstExprUID.h.
operator!=() [2/7]
bool UE::AnimNext::operator!= (FConstExprUID LHS, FFConstExprUIDRaw RHS) constexpr noexcept
Definition at line 73 of file ConstExprUID.h.
operator!=() [3/7]
bool UE::AnimNext::operator!= (FFConstExprUIDRaw LHS, FConstExprUID RHS) constexpr noexcept
Definition at line 75 of file ConstExprUID.h.
operator!=() [4/7]
bool UE::AnimNext::operator!= (FTraitInterfaceUID LHS, FTraitInterfaceUID RHS) constexpr
Definition at line 78 of file TraitInterfaceUID.h.
References UE::AnimNext::FTraitInterfaceUID::GetUID().
operator!=() [5/7]
bool UE::AnimNext::operator!= (FTraitUID LHS, FTraitUID RHS) constexpr noexcept
Definition at line 79 of file TraitUID.h.
operator!=() [6/7]
bool UE::AnimNext::operator!= (FTraitUID LHS, FTraitUIDRaw RHS) constexpr noexcept
Definition at line 81 of file TraitUID.h.
operator!=() [7/7]
bool UE::AnimNext::operator!= (FTraitUIDRaw LHS, FTraitUID RHS) constexpr noexcept
Definition at line 83 of file TraitUID.h.
operator<() [1/2]
bool UE::AnimNext::operator< (FConstExprUID LHS, FConstExprUID RHS) constexpr
Definition at line 78 of file ConstExprUID.h.
References UE::AnimNext::FConstExprUID::GetUID().
operator<() [2/2]
bool UE::AnimNext::operator< (FTraitInterfaceUID LHS, FTraitInterfaceUID RHS) constexpr
Definition at line 81 of file TraitInterfaceUID.h.
References UE::AnimNext::FTraitInterfaceUID::GetUID().
operator<<() [1/2]
FArchive & UE::AnimNext::operator<< (FArchive & Ar, FLatentPropertyHandle & Handle) inline
Definition at line 133 of file LatentPropertyHandle.h.
operator<<() [2/2]
FArchive & UE::AnimNext::operator<< (FArchive & Ar, FLatentPropertyMetadata & Metadata) inline
Definition at line 31 of file LatentPropertyHandle.h.
References Ar, and Metadata.
operator==() [1/7]
bool UE::AnimNext::operator== (FConstExprUID LHS, FConstExprUID RHS) constexpr noexcept
Definition at line 70 of file ConstExprUID.h.
operator==() [2/7]
bool UE::AnimNext::operator== (FConstExprUID LHS, FFConstExprUIDRaw RHS) constexpr noexcept
Definition at line 72 of file ConstExprUID.h.
operator==() [3/7]
bool UE::AnimNext::operator== (FFConstExprUIDRaw LHS, FConstExprUID RHS) constexpr noexcept
Definition at line 74 of file ConstExprUID.h.
operator==() [4/7]
bool UE::AnimNext::operator== (FTraitInterfaceUID LHS, FTraitInterfaceUID RHS) constexpr
Definition at line 77 of file TraitInterfaceUID.h.
References UE::AnimNext::FTraitInterfaceUID::GetUID().
operator==() [5/7]
bool UE::AnimNext::operator== (FTraitUID LHS, FTraitUID RHS) constexpr noexcept
Definition at line 78 of file TraitUID.h.
operator==() [6/7]
bool UE::AnimNext::operator== (FTraitUID LHS, FTraitUIDRaw RHS) constexpr noexcept
Definition at line 80 of file TraitUID.h.
operator==() [7/7]
bool UE::AnimNext::operator== (FTraitUIDRaw LHS, FTraitUID RHS) constexpr noexcept
Definition at line 82 of file TraitUID.h.
RaiseTraitEvent()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::RaiseTraitEvent (FExecutionContext & Context, const FTraitStackBinding & StackBinding, FAnimNextTraitEvent & Event)
References Event.
RaiseTraitEvents() [1/2]
ANIMNEXTANIMGRAPH_API void UE::AnimNext::RaiseTraitEvents (FExecutionContext & Context, const FTraitStackBinding & StackBinding, const FTraitEventList & EventList)
RaiseTraitEvents() [2/2]
ANIMNEXTANIMGRAPH_API void UE::AnimNext::RaiseTraitEvents (FExecutionContext & Context, FGraphInstanceComponent & Component, const FTraitEventList & EventList)
References Component.
SetIdentity() [1/4]
ANIMNEXT_API void UE::AnimNext::SetIdentity (const FTransformArrayAoSView & Dest, bool bIsAdditive)
Referenced by UE::AnimNext::FLODPose::SetIdentity().
SetIdentity() [2/4]
ANIMNEXT_API void UE::AnimNext::SetIdentity (const FTransformArrayAoSView & Dest, bool bIsAdditive, int32 StartIndex, int32 NumTransformsToSet)
SetIdentity() [3/4]
ANIMNEXT_API void UE::AnimNext::SetIdentity (const FTransformArraySoAView & Dest, bool bIsAdditive)
SetIdentity() [4/4]
ANIMNEXT_API void UE::AnimNext::SetIdentity (const FTransformArraySoAView & Dest, bool bIsAdditive, int32 StartIndex, int32 NumTransformsToSet)
UpdateGraph()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::UpdateGraph (FUpdateGraphContext & UpdateGraphContext)
Updates a sub-graph starting at its root.
For each node:
We call PreUpdate on all its traits
We update all children
We call PostUpdate on all its traits
During our update, we can append new input/output events.
See also
IUpdate::PreUpdate, IUpdate::PostUpdate, IHierarchy::GetChildren
Variable Documentation
KEYFRAME_STACK_NAME
ANIMNEXTANIMGRAPH_API const FEvaluationVMStackName UE::AnimNext::KEYFRAME_STACK_NAME extern
TransformAdditiveIdentity
const FTransform ANIMNEXT_API UE::AnimNext::TransformAdditiveIdentity extern
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::SetIdentity().