Unreal Engine 5.6 C++ API: UE::Geometry::VectorUtil Namespace Reference
UE::Geometry::VectorUtil Namespace Reference
Functions
template<typename RealType>
RealType Area (const TVector2< RealType > &V0, const TVector2< RealType > &V1, const TVector2< RealType > &V2)
template<typename RealType>
RealType Area (const TVector< RealType > &V0, const TVector< RealType > &V1, const TVector< RealType > &V2)
double AspectRatio (const FVector3d &v1, const FVector3d &v2, const FVector3d &v3)
template<typename RealType>
TVector< RealType > BarycentricCoords (const TVector2< RealType > &Point, const TVector2< RealType > &V0, const TVector2< RealType > &V1, const TVector2< RealType > &V2)
Compute barycentric coordinates/weights of vPoint inside 2D triangle (V0,V1,V2).
template<typename RealType>
TVector< RealType > BarycentricCoords (const TVector< RealType > &Point, const TVector< RealType > &V0, const TVector< RealType > &V1, const TVector< RealType > &V2)
Compute barycentric coordinates/weights of vPoint inside 3D triangle (V0,V1,V2).
template<typename RealType>
TVector< RealType > Bitangent (const TVector< RealType > &NormalIn, const TVector< RealType > &TangentIn, RealType BitangentSign)
template<typename RealType>
TVector< RealType > BitangentFromTangent (const TVector< RealType > &NormalIn, const TVector< RealType > &TangentIn)
template<typename RealType>
RealType BitangentSign (const TVector< RealType > &NormalIn, const TVector< RealType > &TangentIn, const TVector< RealType > &BitangentIn)
template<typename RealType>
TVector2< RealType > Circumcenter (TVector2< RealType > A, TVector2< RealType > B, const TVector2< RealType > &C, RealType Epsilon=TMathUtilConstants< RealType >::Epsilon)
template<typename RealType>
RealType Clamp (RealType Value, RealType MinValue, RealType MaxValue)
template<typename RealType>
bool EpsilonEqual (const TVector2< RealType > &V0, const TVector2< RealType > &V1, RealType Epsilon)
template<typename RealType>
bool EpsilonEqual (const TVector4< RealType > &V0, const TVector4< RealType > &V1, RealType Epsilon)
template<typename RealType>
bool EpsilonEqual (const TVector< RealType > &V0, const TVector< RealType > &V1, RealType Epsilon)
template<typename RealType>
bool EpsilonEqual (RealType A, RealType B, RealType Epsilon)
template<typename RealType>
TVector< RealType > InverseTransformNormal (const TTransform< RealType > &Transform, const TVector< RealType > &Normal)
template<typename RealType>
bool IsFinite (const TVector2< RealType > &V)
template<typename RealType>
bool IsFinite (const TVector< RealType > &V)
template<typename RealType>
bool IsObtuse (const TVector< RealType > &V1, const TVector< RealType > &V2, const TVector< RealType > &V3)
template<typename RealType>
TVector< RealType > MakePerpVector (const TVector< RealType > &Normal)
Calculates one vector perpendicular to input Normal, as efficiently as possible.
template<typename RealType>
void MakePerpVector (const TVector< RealType > &Normal, TVector< RealType > &OutPerp1)
Calculates one vector perpendicular to input Normal, as efficiently as possible.
template<typename RealType>
void MakePerpVectors (const TVector< RealType > &Normal, TVector< RealType > &OutPerp1, TVector< RealType > &OutPerp2)
Calculates two vectors perpendicular to input Normal, as efficiently as possible.
template<typename ValueVecType>
int Max3Index (const ValueVecType &Vector3)
template<typename ValueVecType>
int Min3Index (const ValueVecType &Vector3)
template<typename RealType>
TVector< RealType > Normal (const TVector< RealType > &V0, const TVector< RealType > &V1, const TVector< RealType > &V2)
template<typename RealType>
TVector< RealType > NormalArea (const TVector< RealType > &V0, const TVector< RealType > &V1, const TVector< RealType > &V2, RealType &AreaOut)
Calculate Normal and Area of triangle V0,V1,V2.
template<typename RealType>
TVector< RealType > NormalDirection (const TVector< RealType > &V0, const TVector< RealType > &V1, const TVector< RealType > &V2)
template<typename RealType>
RealType OpeningAngleD (TVector< RealType > A, TVector< RealType > B, const TVector< RealType > &P)
template<typename RealType>
RealType PlaneAngleSignedD (const TVector< RealType > &VFrom, const TVector< RealType > &VTo, const TVector< RealType > &PlaneN)
Calculates angle between VFrom and VTo after projection onto plane with normal defined by PlaneN.
template<typename RealType>
RealType PlaneAngleSignedR (const TVector< RealType > &VFrom, const TVector< RealType > &VTo, const TVector< RealType > &PlaneN)
Calculates angle between VFrom and VTo after projection onto plane with normal defined by PlaneN.
template<typename RealType>
RealType SignedArea (const TVector2< RealType > &V0, const TVector2< RealType > &V1, const TVector2< RealType > &V2)
template<typename RealType>
TVector< RealType > TangentFromBitangent (const TVector< RealType > &NormalIn, const TVector< RealType > &BitangentIn)
template<typename RealType>
TVector< RealType > TransformNormal (const TTransform< RealType > &Transform, const TVector< RealType > &Normal)
template<typename RealType>
TVector< RealType > TriGradient (TVector< RealType > Vi, TVector< RealType > Vj, TVector< RealType > Vk, RealType fi, RealType fj, RealType fk)
Calculate gradient of scalar field values fi,fj,fk defined at corners of triangle Vi,Vj,Vk and interpolated across triangle using linear basis functions.
template<typename RealType>
RealType TriSolidAngle (TVector< RealType > A, TVector< RealType > B, TVector< RealType > C, const TVector< RealType > &P)
template<typename RealType>
TVector< RealType > UniformSampleTriangleBarycentricCoords (RealType R1, RealType R2)
Sample uniform random barycentric coordinates on a triangle The inputs should be two random floating point numbers in the [0,1] range (See eq.
template<typename RealType>
TVector2< RealType > UniformSampleTrianglePoint (RealType R1, RealType R2, const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &C)
Sample a uniform random point on a 2D triangle The inputs should be two random floating point numbers in the [0,1] range, and the triangle coordinates ref: http://mathworld.wolfram.com/TrianglePointPicking.html Note the sample positions will not match those of UniformSampleTriangleBarycentricCoords for the same R1, R2 values.
template<typename RealType>
TVector< RealType > UniformSampleTrianglePoint (RealType R1, RealType R2, const TVector< RealType > &A, const TVector< RealType > &B, const TVector< RealType > &C)
Sample a uniform random point on a triangle The inputs should be two random floating point numbers in the [0,1] range, and the triangle coordinates ref: http://mathworld.wolfram.com/TrianglePointPicking.html Note the sample positions will not match those of UniformSampleTriangleBarycentricCoords for the same R1, R2 values.
template<typename RealType>
RealType VectorCot (const TVector< RealType > &V1, const TVector< RealType > &V2)
Fast cotangent of angle between two vectors (do not have to be normalized unit vectors).
template<typename RealType>
RealType VectorTanHalfAngle (const TVector2< RealType > &A, const TVector2< RealType > &B)
tan(theta/2) = +/- sqrt((1-cos(theta)) / (1+cos(theta)))
template<typename RealType>
RealType VectorTanHalfAngle (const TVector< RealType > &A, const TVector< RealType > &B)
tan(theta/2) = +/- sqrt((1-cos(theta)) / (1+cos(theta)))
Function Documentation
Area() [1/2]
template<typename RealType> RealType UE::Geometry::VectorUtil::Area (const TVector2< RealType > & V0, const TVector2< RealType > & V1, const TVector2< RealType > & V2) inline
Returns
area of 2D triangle V0,V1,V2
Definition at line 109 of file VectorUtil.h.
References TMathUtil< RealType >::Abs(), and UE::Geometry::DotPerp().
Area() [2/2]
template<typename RealType> RealType UE::Geometry::VectorUtil::Area (const TVector< RealType > & V0, const TVector< RealType > & V1, const TVector< RealType > & V2) inline
Returns
area of 3D triangle V0,V1,V2
Definition at line 97 of file VectorUtil.h.
References UE::Geometry::Cross(), and UE::Math::TVector< T >::Cross().
Referenced by UE::Geometry::FSegmentTree3::FindNearestVisibleSegmentHitByRayInternal(), UE::Geometry::TMeshUniformSurfaceSampling< FDynamicMesh3, double >::Init(), and TriGradient().
AspectRatio()
double UE::Geometry::VectorUtil::AspectRatio (const FVector3d & v1, const FVector3d & v2, const FVector3d & v3) inline
Returns
Aspect ratio of triangle
Definition at line 600 of file VectorUtil.h.
References Distance.
BarycentricCoords() [1/2]
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::BarycentricCoords (const TVector2< RealType > & Point, const TVector2< RealType > & V0, const TVector2< RealType > & V1, const TVector2< RealType > & V2)
Compute barycentric coordinates/weights of vPoint inside 2D triangle (V0,V1,V2).
If point is inside triangle, coords will be positive and sum to 1. ie if result is a, then vPoint = a.x*V0 + a.y*V1 + a.z*V2. TODO: make robust to degenerate triangles?
Definition at line 401 of file VectorUtil.h.
References UE::Math::TVector2< T >::Dot(), and Point.
BarycentricCoords() [2/2]
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::BarycentricCoords (const TVector< RealType > & Point, const TVector< RealType > & V0, const TVector< RealType > & V1, const TVector< RealType > & V2)
Compute barycentric coordinates/weights of vPoint inside 3D triangle (V0,V1,V2).
If point is in triangle plane and inside triangle, coords will be positive and sum to 1. ie if result is a, then vPoint = a.x*V0 + a.y*V1 + a.z*V2. TODO: make robust to degenerate triangles?
Definition at line 376 of file VectorUtil.h.
References UE::Math::TVector< T >::Dot(), and Point.
Referenced by UE::Geometry::TTriangle2< float >::GetBarycentricCoords(), and UE::Geometry::TTriangle3< float >::GetBarycentricCoords().
Bitangent()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::Bitangent (const TVector< RealType > & NormalIn, const TVector< RealType > & TangentIn, RealType BitangentSign) inline
Returns
Bitangent vector based on given Normal, Tangent, and Sign value (+1/-1)
Definition at line 573 of file VectorUtil.h.
References BitangentSign(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
BitangentFromTangent()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::BitangentFromTangent (const TVector< RealType > & NormalIn, const TVector< RealType > & TangentIn) inline
Returns
Bitangent vector based on given Normal and Tangent
Definition at line 594 of file VectorUtil.h.
References UE::Math::TVector< T >::Cross().
BitangentSign()
template<typename RealType> RealType UE::Geometry::VectorUtil::BitangentSign (const TVector< RealType > & NormalIn, const TVector< RealType > & TangentIn, const TVector< RealType > & BitangentIn) inline
Returns
sign of Bitangent relative to Normal and Tangent
Definition at line 559 of file VectorUtil.h.
References UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by Bitangent().
Circumcenter()
template<typename RealType> TVector2< RealType > UE::Geometry::VectorUtil::Circumcenter (TVector2< RealType > A, TVector2< RealType > B, const TVector2< RealType > & C, RealType Epsilon = TMathUtilConstants<RealType>::Epsilon) inline
Returns
circumcenter of triangle ABC
Definition at line 533 of file VectorUtil.h.
References A, B, UE::Geometry::DotPerp(), UE::Math::TVector2< T >::SquaredLength(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Clamp()
template<typename RealType> RealType UE::Geometry::VectorUtil::Clamp (RealType Value, RealType MinValue, RealType MaxValue) inline
Returns
input Value clamped to range [MinValue, MaxValue]
Definition at line 61 of file VectorUtil.h.
References Value.
Referenced by UE::Geometry::FMeshRefinerBase::SetEdgeFlipTolerance().
EpsilonEqual() [1/4]
template<typename RealType> bool UE::Geometry::VectorUtil::EpsilonEqual (const TVector2< RealType > & V0, const TVector2< RealType > & V1, RealType Epsilon) inline
Returns
true if all coordinates of V0 and V1 are within Epsilon of eachother
Definition at line 163 of file VectorUtil.h.
References EpsilonEqual(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
EpsilonEqual() [2/4]
template<typename RealType> bool UE::Geometry::VectorUtil::EpsilonEqual (const TVector4< RealType > & V0, const TVector4< RealType > & V1, RealType Epsilon) inline
Returns
true if all coordinates of V0 and V1 are within Epsilon of each other
Definition at line 177 of file VectorUtil.h.
References EpsilonEqual(), UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
EpsilonEqual() [3/4]
template<typename RealType> bool UE::Geometry::VectorUtil::EpsilonEqual (const TVector< RealType > & V0, const TVector< RealType > & V1, RealType Epsilon) inline
Returns
true if all coordinates of V0 and V1 are within Epsilon of eachother
Definition at line 170 of file VectorUtil.h.
References EpsilonEqual(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
EpsilonEqual() [4/4]
template<typename RealType> bool UE::Geometry::VectorUtil::EpsilonEqual (RealType A, RealType B, RealType Epsilon) inline
Returns
true if Abs(A-B) is less than Epsilon
Definition at line 156 of file VectorUtil.h.
References A, TMathUtil< RealType >::Abs(), and B.
Referenced by UE::Geometry::TMatrix2< float >::EpsilonEqual(), UE::Geometry::TMatrix3< float >::EpsilonEqual(), EpsilonEqual(), EpsilonEqual(), EpsilonEqual(), and UE::Geometry::TFrame3< float >::RayPlaneIntersection().
InverseTransformNormal()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::InverseTransformNormal (const TTransform< RealType > & Transform, const TVector< RealType > & Normal) inline
Definition at line 619 of file VectorUtil.h.
References Normal(), Normalized, and UE::Geometry::Transform.
Referenced by UE::Geometry::TPlane3< FVector::FReal >::InverseTransform().
IsFinite() [1/2]
template<typename RealType> bool UE::Geometry::VectorUtil::IsFinite (const TVector2< RealType > & V) inline
Returns
true if all components of V are finite
Definition at line 42 of file VectorUtil.h.
References TMathUtil< RealType >::IsFinite(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by UE::Geometry::FDynamicGraph2< double >::SetVertex(), UE::Geometry::FDynamicGraph3< double >::SetVertex(), UE::Geometry::FDynamicMesh3::SetVertex(), UE::Geometry::FDynamicGraph2< double >::subclass_validity_checks(), and UE::Geometry::FDynamicGraph3< double >::subclass_validity_checks().
IsFinite() [2/2]
template<typename RealType> bool UE::Geometry::VectorUtil::IsFinite (const TVector< RealType > & V) inline
Returns
true if all components of V are finite
Definition at line 51 of file VectorUtil.h.
References TMathUtil< RealType >::IsFinite(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
IsObtuse()
template<typename RealType> bool UE::Geometry::VectorUtil::IsObtuse (const TVector< RealType > & V1, const TVector< RealType > & V2, const TVector< RealType > & V3) inline
Returns
true if triangle V1,V2,V3 is obtuse
Definition at line 130 of file VectorUtil.h.
References UE::Geometry::DistanceSquared().
MakePerpVector() [1/2]
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::MakePerpVector (const TVector< RealType > & Normal) inline
Calculates one vector perpendicular to input Normal, as efficiently as possible.
Definition at line 247 of file VectorUtil.h.
References A, B, Normal(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by MakePerpVector().
MakePerpVector() [2/2]
template<typename RealType> void UE::Geometry::VectorUtil::MakePerpVector (const TVector< RealType > & Normal, TVector< RealType > & OutPerp1) inline
Calculates one vector perpendicular to input Normal, as efficiently as possible.
Definition at line 274 of file VectorUtil.h.
References MakePerpVector(), and Normal().
MakePerpVectors()
template<typename RealType> void UE::Geometry::VectorUtil::MakePerpVectors (const TVector< RealType > & Normal, TVector< RealType > & OutPerp1, TVector< RealType > & OutPerp2) inline
Calculates two vectors perpendicular to input Normal, as efficiently as possible.
Definition at line 216 of file VectorUtil.h.
References A, B, Normal(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TDistLine3Triangle3< float >::ComputeResult(), UE::Geometry::TIntrTriangle3Triangle3< float >::ContainsPoint(), and TriGradient().
Max3Index()
template<typename ValueVecType> int UE::Geometry::VectorUtil::Max3Index (const ValueVecType & Vector3) inline
Returns
0/1/2 index of largest value in Vector3
Definition at line 199 of file VectorUtil.h.
Referenced by UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), and UE::Geometry::TWatertightRay3< float >::Init().
Min3Index()
template<typename ValueVecType> int UE::Geometry::VectorUtil::Min3Index (const ValueVecType & Vector3) inline
Returns
0/1/2 index of smallest value in Vector3
Definition at line 185 of file VectorUtil.h.
Normal()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::Normal (const TVector< RealType > & V0, const TVector< RealType > & V1, const TVector< RealType > & V2) inline
Returns
normalized vector that is perpendicular to triangle V0,V1,V2 (triangle normal)
Definition at line 70 of file VectorUtil.h.
References UE::Math::TVector< T >::Cross(), UE::Geometry::Normalize, and Normalized.
Referenced by UE::Geometry::THalfspace3< float >::THalfspace3(), UE::Geometry::TPlane3< FVector::FReal >::TPlane3(), UE::Geometry::FColliderMesh::GetTriNormal(), InverseTransformNormal(), MakePerpVector(), MakePerpVector(), MakePerpVectors(), UE::Geometry::TTriangle3< float >::Normal(), TransformNormal(), and TriGradient().
NormalArea()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::NormalArea (const TVector< RealType > & V0, const TVector< RealType > & V1, const TVector< RealType > & V2, RealType & AreaOut) inline
Calculate Normal and Area of triangle V0,V1,V2.
Returns
triangle normal
Definition at line 143 of file VectorUtil.h.
References UE::Math::TVector< T >::Cross(), and UE::Geometry::Normalize.
Referenced by UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriNormalAreaCentroid().
NormalDirection()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::NormalDirection (const TVector< RealType > & V0, const TVector< RealType > & V1, const TVector< RealType > & V2) inline
Returns
un-normalized direction that is parallel to normal of triangle V0,V1,V2
Definition at line 86 of file VectorUtil.h.
References UE::Math::TVector< T >::Cross().
Referenced by UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), and UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindOrTestWithoutCoplanar().
OpeningAngleD()
template<typename RealType> RealType UE::Geometry::VectorUtil::OpeningAngleD (TVector< RealType > A, TVector< RealType > B, const TVector< RealType > & P) inline
Returns
angle between vectors (A-CornerPt) and (B-CornerPt)
Definition at line 519 of file VectorUtil.h.
References A, UE::Geometry::AngleD(), B, and UE::Geometry::Normalize.
PlaneAngleSignedD()
template<typename RealType> RealType UE::Geometry::VectorUtil::PlaneAngleSignedD (const TVector< RealType > & VFrom, const TVector< RealType > & VTo, const TVector< RealType > & PlaneN) inline
Calculates angle between VFrom and VTo after projection onto plane with normal defined by PlaneN.
Returns
angle in degrees
Definition at line 285 of file VectorUtil.h.
References UE::Geometry::AngleD(), UE::Math::TVector< T >::Cross(), UE::Math::TVector< T >::Dot(), and UE::Geometry::Normalize.
Referenced by UE::Geometry::TFrame3< float >::ConstrainedAlignAxis().
PlaneAngleSignedR()
template<typename RealType> RealType UE::Geometry::VectorUtil::PlaneAngleSignedR (const TVector< RealType > & VFrom, const TVector< RealType > & VTo, const TVector< RealType > & PlaneN) inline
Calculates angle between VFrom and VTo after projection onto plane with normal defined by PlaneN.
Returns
angle in radians
Definition at line 305 of file VectorUtil.h.
References UE::Geometry::AngleR(), UE::Math::TVector< T >::Cross(), UE::Math::TVector< T >::Dot(), and UE::Geometry::Normalize.
SignedArea()
template<typename RealType> RealType UE::Geometry::VectorUtil::SignedArea (const TVector2< RealType > & V0, const TVector2< RealType > & V1, const TVector2< RealType > & V2) inline
Returns
signed area of 2D triangle V0,V1,V2
Definition at line 121 of file VectorUtil.h.
References UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
TangentFromBitangent()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::TangentFromBitangent (const TVector< RealType > & NormalIn, const TVector< RealType > & BitangentIn) inline
Returns
Tangent-Space vector based on given Normal and Bitangent
Definition at line 585 of file VectorUtil.h.
References UE::Math::TVector< T >::Cross().
TransformNormal()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::TransformNormal (const TTransform< RealType > & Transform, const TVector< RealType > & Normal) inline
Definition at line 609 of file VectorUtil.h.
References Normal(), Normalized, TMathUtil< double >::SignNonZero(), UE::Geometry::Transform, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TPlane3< FVector::FReal >::Transform().
TriGradient()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::TriGradient (TVector< RealType > Vi, TVector< RealType > Vj, TVector< RealType > Vk, RealType fi, RealType fj, RealType fk) inline
Calculate gradient of scalar field values fi,fj,fk defined at corners of triangle Vi,Vj,Vk and interpolated across triangle using linear basis functions.
This gradient is a 3D vector lying in the plane of the triangle (or zero if field is constant).
Returns
gradient (3D vector) lying in plane of triangle.
Definition at line 493 of file VectorUtil.h.
References Area(), UE::Math::TVector< T >::Dot(), MakePerpVectors(), Normal(), UE::Geometry::PerpCW(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
TriSolidAngle()
template<typename RealType> RealType UE::Geometry::VectorUtil::TriSolidAngle (TVector< RealType > A, TVector< RealType > B, TVector< RealType > C, const TVector< RealType > & P) inline
Returns
solid angle at point P for triangle A,B,C
Definition at line 473 of file VectorUtil.h.
References A, and B.
Referenced by UE::Geometry::TFastWindingTree< TriangleMeshType >::branch_fast_winding_num().
UniformSampleTriangleBarycentricCoords()
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::UniformSampleTriangleBarycentricCoords (RealType R1, RealType R2)
Sample uniform random barycentric coordinates on a triangle The inputs should be two random floating point numbers in the [0,1] range (See eq.
1 of 'Shape Distributions' by Osada, Funkhouser, Chazelle and Dobkin) Note the sample positions will not match those of UniformSampleTrianglePoint for the same R1, R2 values
Definition at line 426 of file VectorUtil.h.
References checkSlow.
UniformSampleTrianglePoint() [1/2]
template<typename RealType> TVector2< RealType > UE::Geometry::VectorUtil::UniformSampleTrianglePoint (RealType R1, RealType R2, const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & C)
Sample a uniform random point on a 2D triangle The inputs should be two random floating point numbers in the [0,1] range, and the triangle coordinates ref: http://mathworld.wolfram.com/TrianglePointPicking.html Note the sample positions will not match those of UniformSampleTriangleBarycentricCoords for the same R1, R2 values.
Definition at line 458 of file VectorUtil.h.
References A, and B.
UniformSampleTrianglePoint() [2/2]
template<typename RealType> TVector< RealType > UE::Geometry::VectorUtil::UniformSampleTrianglePoint (RealType R1, RealType R2, const TVector< RealType > & A, const TVector< RealType > & B, const TVector< RealType > & C)
Sample a uniform random point on a triangle The inputs should be two random floating point numbers in the [0,1] range, and the triangle coordinates ref: http://mathworld.wolfram.com/TrianglePointPicking.html Note the sample positions will not match those of UniformSampleTriangleBarycentricCoords for the same R1, R2 values.
Definition at line 440 of file VectorUtil.h.
References A, and B.
VectorCot()
template<typename RealType> RealType UE::Geometry::VectorUtil::VectorCot (const TVector< RealType > & V1, const TVector< RealType > & V2)
Fast cotangent of angle between two vectors (do not have to be normalized unit vectors).
cot = cos/sin, both of which can be computed from vector identities
Returns
cotangent of angle between V1 and V2, or zero if result would be unstable (eg infinity)
Definition at line 352 of file VectorUtil.h.
References UE::Geometry::Clamp, UE::Math::TVector< T >::Dot(), TMathUtil< RealType >::Sqrt(), and UE::Math::TVector< T >::SquaredLength().
VectorTanHalfAngle() [1/2]
template<typename RealType> RealType UE::Geometry::VectorUtil::VectorTanHalfAngle (const TVector2< RealType > & A, const TVector2< RealType > & B)
tan(theta/2) = +/- sqrt((1-cos(theta)) / (1+cos(theta)))
Returns
positive value of tan(theta/2) where theta is angle between normalized vectors A and B
Definition at line 338 of file VectorUtil.h.
References A, B, UE::Geometry::Clamp, and TMathUtil< RealType >::Sqrt().
VectorTanHalfAngle() [2/2]
template<typename RealType> RealType UE::Geometry::VectorUtil::VectorTanHalfAngle (const TVector< RealType > & A, const TVector< RealType > & B)
tan(theta/2) = +/- sqrt((1-cos(theta)) / (1+cos(theta)))
Returns
positive value of tan(theta/2) where theta is angle between normalized vectors A and B
Definition at line 325 of file VectorUtil.h.
References A, B, UE::Geometry::Clamp, and TMathUtil< RealType >::Sqrt().