Unreal Engine 5.6 C++ API: UE::Math::TBox< T > Struct Template Reference
UE::Math::TBox< T > Struct Template Reference
#include "Box.h"
Public Types
using FReal = T
Public Member Functions
constexpr TBox ()
Default constructor.
TBox (const TArray< TVector< T > > &Points)
Creates and initializes a new box from an array of points.
template<typename FArg UE_REQUIRES>
TBox (const TBox< FArg > &From)
TBox (const TSphere< T > &Sphere)
Creates and initializes a box that tightly encloses the given sphere.
TBox (const TVector4< T > &InMin, const TVector4< T > &InMax)
template<typename FArg>
TBox (const TVector< FArg > &InMin, const TVector< FArg > &InMax)
Creates and initializes a new box from the specified extents.
TBox (const TVector< T > *Points, const int32 Count)
Creates and initializes a new box from the given set of points.
constexpr TBox (EForceInit)
Creates and initializes a new box with zero extent and marks it as invalid.
constexpr TBox (EForceInit, TBoxConstInit)
constexpr TBox (ENoInit)
Creates a new box without initialization.
FORCEINLINE T ComputeSquaredDistanceToBox (const TBox< T > &Box) const
Calculates squared distance between two boxes.
FORCEINLINE T ComputeSquaredDistanceToPoint (const TVector< T > &Point) const
Calculates the distance of a point to this box.
bool ContainsNaN () const
FORCEINLINE void DiagnosticCheck () const
bool Equals (const TBox< T > &Other, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Check against another box for equality, within specified error limits.
TBox< T > ExpandBy (const TVector< T > &Neg, const TVector< T > &Pos) const
Returns a box of increased size.
FORCEINLINE TBox< T > ExpandBy (const TVector< T > &V) const
Returns a box of increased size.
FORCEINLINE TBox< T > ExpandBy (T W) const
Returns a box of increased size.
FORCEINLINE TVector< T > GetCenter () const
Gets the center point of this box.
FORCEINLINE void GetCenterAndExtents (TVector< T > &Center, TVector< T > &Extents) const
Gets the center and extents of this box.
FORCEINLINE TVector< T > GetClosestPointTo (const TVector< T > &Point) const
Calculates the closest point on or inside the box to a given point in space.
FORCEINLINE TVector< T > GetExtent () const
Gets the extents of this box.
FORCEINLINE TVector< T > GetSize () const
Gets the size of this box.
void GetVertices (TVector< T >(&Vertices)[8]) const
Get the vertices that make up this box.
FORCEINLINE T GetVolume () const
Gets the volume of this box.
FORCEINLINE void Init ()
Set the initial values of the bounding box to Zero.
FORCEINLINE bool Intersect (const TBox< T > &Other) const
Checks whether the given bounding box intersects this bounding box.
FORCEINLINE bool IntersectXY (const TBox< T > &Other) const
Checks whether the given bounding box intersects this bounding box in the XY plane.
TBox< T > InverseTransformBy (const TTransform< T > &M) const
Gets a bounding volume transformed by an inverted TTransform<T> object.
FORCEINLINE bool IsInside (const TBox< T > &Other) const
Checks whether a given box is fully encapsulated by this box.
FORCEINLINE bool IsInside (const TVector< T > &In) const
Checks whether the given location is inside this box.
FORCEINLINE bool IsInsideOrOn (const TBox< T > &Other) const
Checks whether a given box is fully encapsulated by this box.
FORCEINLINE bool IsInsideOrOn (const TVector< T > &In) const
Checks whether the given location is inside or on this box.
FORCEINLINE bool IsInsideOrOnXY (const TVector< T > &In) const
Checks whether the given location is inside or on this box in the XY plane.
FORCEINLINE bool IsInsideXY (const TBox< T > &Other) const
Checks whether the given box is fully encapsulated by this box in the XY plane.
FORCEINLINE bool IsInsideXY (const TVector< T > &In) const
Checks whether the given location is inside this box in the XY plane.
FORCEINLINE TBox< T > MoveTo (const TVector< T > &Destination) const
Returns a box with its center moved to the new destination.
FORCEINLINE bool operator!= (const TBox< T > &Other) const
Compares two boxes for inequality.
FORCEINLINE TBox< T > operator+ (const TBox< T > &Other) const
Gets the result of addition to this bounding volume.
FORCEINLINE TBox< T > operator+ (const TVector< T > &Other) const
Gets the result of addition to this bounding volume.
FORCEINLINE TBox< T > & operator+= (const TBox< T > &Other)
Adds to this bounding box to include a new bounding volume.
FORCEINLINE TBox< T > & operator+= (const TVector< T > &Other)
Adds to this bounding box to include a given point.
FORCEINLINE bool operator== (const TBox< T > &Other) const
Compares two boxes for equality.
FORCEINLINE TVector< T > & operator[] (int32 Index)
Gets reference to the min or max of this bounding volume.
FORCEINLINE const TVector< T > & operator[] (int32 Index) const
TBox< T > Overlap (const TBox< T > &Other) const
Returns the overlap TBox<T> of two box.
bool Serialize (FArchive &Ar)
bool Serialize (FStructuredArchive::FSlot Slot)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
FORCEINLINE TBox< T > ShiftBy (const TVector< T > &Offset) const
Returns a box with its position shifted.
FString ToCompactString () const
Get a textual representation of this box, without min/max values if invalid.
FString ToString () const
Get a textual representation of this box.
TBox< T > TransformBy (const TMatrix< T > &M) const
Gets a bounding volume transformed by a matrix.
TBox< T > TransformBy (const TTransform< T > &M) const
Gets a bounding volume transformed by a TTransform<T> object.
TBox< T > TransformProjectBy (const TMatrix< T > &ProjM) const
Returns the current world bounding box transformed and projected to screen space.
Static Public Member Functions
static TBox< T > BuildAABB (const TVector< T > &Origin, const TVector< T > &Extent)
Utility function to build an AABB from Origin and Extent.
Data Fields
uint8 IsValid
Holds a flag indicating whether this box is valid.
TVector< T > Max
Holds the box's maximum point.
TVector< T > Min
Holds the box's minimum point.
Friends
FArchive & operator<< (FArchive &Ar, TBox< T > &Box)
Serializes the bounding box.
void operator<< (FStructuredArchive::FSlot Slot, TBox< T > &Box)
Serializes the bounding box.
Detailed Description
template<typename T>
struct UE::Math::TBox< T >
Definition at line 34 of file Box.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TBox< T >::FReal = T
Definition at line 37 of file Box.h.
Constructor & Destructor Documentation
TBox() [1/10]
template<typename T> UE::Math::TBox< T >::TBox () inline nodiscard constexpr
Default constructor.
Creates a new box with uninitialized extents and marks it as invalid.
NOTE: This default constructor is unlike TVector, TMatrix etc. in that it actually initializes the instance. Ideally it should be = default; in the same way, but this would break backwards compatibility. It might be possible if the questionable IsValid field ever gets removed.
Definition at line 59 of file Box.h.
Referenced by UE::Math::TBox< double >::ExpandBy(), UE::Math::TBox< double >::ExpandBy(), UE::Math::TBox< double >::ExpandBy(), Intersect(), IntersectXY(), InverseTransformBy(), UE::Math::TBox< double >::MoveTo(), UE::Math::TBox< double >::operator+(), UE::Math::TBox< double >::operator+(), operator+=(), operator+=(), Overlap(), UE::Math::TBox< double >::ShiftBy(), TransformBy(), TransformBy(), and TransformProjectBy().
TBox() [2/10]
template<typename T> UE::Math::TBox< T >::TBox (ENoInit) inline explicit nodiscard constexpr
Creates a new box without initialization.
Definition at line 73 of file Box.h.
TBox() [3/10]
template<typename T> UE::Math::TBox< T >::TBox (EForceInit) inline explicit nodiscard constexpr
Creates and initializes a new box with zero extent and marks it as invalid.
Definition at line 78 of file Box.h.
TBox() [4/10]
template<typename T> UE::Math::TBox< T >::TBox (EForceInit , TBoxConstInit) inline nodiscard constexpr
Definition at line 85 of file Box.h.
TBox() [5/10]
template<typename T> template<typename FArg> UE::Math::TBox< T >::TBox (const TVector< FArg > & InMin, const TVector< FArg > & InMax) inline
Creates and initializes a new box from the specified extents.
Parameters
InMin The box's minimum point.
InMax The box's maximum point.
Definition at line 121 of file Box.h.
TBox() [6/10]
template<typename T> UE::Math::TBox< T >::TBox (const TVector4< T > & InMin, const TVector4< T > & InMax) inline
Definition at line 132 of file Box.h.
TBox() [7/10]
template<typename T> UE::Math::TBox< T >::TBox (const TVector< T > * Points, const int32 Count) inline
Creates and initializes a new box from the given set of points.
Parameters
Points Array of Points to create for the bounding volume.
Count The number of points.
Definition at line 146 of file Box.h.
TBox() [8/10]
template<typename T> UE::Math::TBox< T >::TBox (const TArray< TVector< T > > & Points) inline explicit
Creates and initializes a new box from an array of points.
Parameters
Points Array of Points to create for the bounding volume.
Definition at line 159 of file Box.h.
TBox() [9/10]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TBox< T >::TBox (const TBox< FArg > & From) inline explicit
Definition at line 163 of file Box.h.
TBox() [10/10]
template<typename T> UE::Math::TBox< T >::TBox (const TSphere< T > & Sphere) inline explicit
Creates and initializes a box that tightly encloses the given sphere.
Parameters
Sphere The sphere being enclosed.
Definition at line 173 of file Box.h.
Member Function Documentation
BuildAABB()
template<typename T> TBox< T > UE::Math::TBox< T >::BuildAABB (const TVector< T > & Origin, const TVector< T > & Extent) inline static
Utility function to build an AABB from Origin and Extent.
Parameters
Origin The location of the bounding box.
Extent Half size of the bounding box.
Returns
A new axis-aligned bounding box.
Definition at line 648 of file Box.h.
ComputeSquaredDistanceToBox()
template<typename T> FORCEINLINE T UE::Math::TBox< T >::ComputeSquaredDistanceToBox (const TBox< T > & Box) const inline nodiscard
Calculates squared distance between two boxes.
Definition at line 302 of file Box.h.
ComputeSquaredDistanceToPoint()
template<typename T> FORCEINLINE T UE::Math::TBox< T >::ComputeSquaredDistanceToPoint (const TVector< T > & Point) const inline nodiscard
Calculates the distance of a point to this box.
Parameters
Point The point.
Returns
The distance.
Definition at line 294 of file Box.h.
ContainsNaN()
template<typename T> bool UE::Math::TBox< T >::ContainsNaN () const inline nodiscard
Definition at line 109 of file Box.h.
DiagnosticCheck()
template<typename T> FORCEINLINE void UE::Math::TBox< T >::DiagnosticCheck () const inline
Definition at line 106 of file Box.h.
Referenced by UE::Math::TBox< double >::TBox(), UE::Math::TBox< double >::TBox(), UE::Math::TBox< double >::GetCenter(), GetClosestPointTo(), UE::Math::TBox< double >::GetExtent(), UE::Math::TBox< double >::GetSize(), GetVertices(), UE::Math::TBox< double >::GetVolume(), Intersect(), IntersectXY(), UE::Math::TBox< double >::IsInside(), UE::Math::TBox< double >::IsInsideOrOn(), UE::Math::TBox< double >::IsInsideOrOnXY(), UE::Math::TBox< double >::IsInsideXY(), operator+=(), operator+=(), and TransformBy().
Equals()
template<typename T> bool UE::Math::TBox< T >::Equals (const TBox< T > & Other, T Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Check against another box for equality, within specified error limits.
Returns true if both bounding boxes are invalid. Returns false if one of the bounding boxes is invalid.
Parameters
Other The box to check against.
Tolerance Error tolerance.
Returns
true if the boxes are equal within tolerance limits, false otherwise.
Definition at line 208 of file Box.h.
ExpandBy() [1/3]
template<typename T> TBox< T > UE::Math::TBox< T >::ExpandBy (const TVector< T > & Neg, const TVector< T > & Pos) const inline nodiscard
Returns a box of increased size.
Parameters
Neg The size to increase the volume by in the negative direction (positive values move the bounds outwards)
Pos The size to increase the volume by in the positive direction (positive values move the bounds outwards)
Returns
A new bounding box.
Definition at line 338 of file Box.h.
ExpandBy() [2/3]
template<typename T> FORCEINLINE TBox< T > UE::Math::TBox< T >::ExpandBy (const TVector< T > & V) const inline nodiscard
Returns a box of increased size.
Parameters
V The size to increase the volume by.
Returns
A new bounding box.
Definition at line 326 of file Box.h.
ExpandBy() [3/3]
template<typename T> FORCEINLINE TBox< T > UE::Math::TBox< T >::ExpandBy (T W) const inline nodiscard
Returns a box of increased size.
Parameters
W The size to increase the volume by.
Returns
A new bounding box.
Definition at line 315 of file Box.h.
GetCenter()
template<typename T> FORCEINLINE TVector< T > UE::Math::TBox< T >::GetCenter () const inline
Gets the center point of this box.
Returns
The center point.
See also
GetCenterAndExtents, GetExtent, GetSize, GetVolume
Definition at line 372 of file Box.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcCellLocation(), UE::Math::TBox< double >::ComputeSquaredDistanceToBox(), and UE::Math::TBox< double >::MoveTo().
GetCenterAndExtents()
template<typename T> FORCEINLINE void UE::Math::TBox< T >::GetCenterAndExtents (TVector< T > & Center, TVector< T > & Extents) const inline
Gets the center and extents of this box.
Parameters
Center [out] Will contain the box center point.
Extents [out] Will contain the extent around the center.
See also
GetCenter, GetExtent, GetSize, GetVolume
Definition at line 385 of file Box.h.
GetClosestPointTo()
template<typename T> FORCEINLINE TVector< T > UE::Math::TBox< T >::GetClosestPointTo (const TVector< T > & Point) const
Calculates the closest point on or inside the box to a given point in space.
Parameters
Point The point in space.
Returns
The closest point on or inside the box.
Definition at line 766 of file Box.h.
References DiagnosticCheck(), FORCEINLINE, Max, Min, Point, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GetExtent()
template<typename T> FORCEINLINE TVector< T > UE::Math::TBox< T >::GetExtent () const inline
Gets the extents of this box.
Returns
The box extents.
See also
GetCenter, GetCenterAndExtents, GetSize, GetVolume
Definition at line 405 of file Box.h.
Referenced by UE::Math::TBox< double >::ComputeSquaredDistanceToBox(), and UE::Math::TBox< double >::GetCenterAndExtents().
GetSize()
template<typename T> FORCEINLINE TVector< T > UE::Math::TBox< T >::GetSize () const inline
Gets the size of this box.
Returns
The box size.
See also
GetCenter, GetCenterAndExtents, GetExtent, GetVolume
Definition at line 417 of file Box.h.
Referenced by TSimpleCellGrid< CellType, InvalidCellValue >::Init().
GetVertices()
template<typename T> void UE::Math::TBox< T >::GetVertices (TVector< T >(&) Vertices[8]) const
Get the vertices that make up this box.
Definition at line 919 of file Box.h.
References DiagnosticCheck(), Max, and Min.
Referenced by InverseTransformBy(), and TransformProjectBy().
GetVolume()
template<typename T> FORCEINLINE T UE::Math::TBox< T >::GetVolume () const inline
Gets the volume of this box.
Returns
The box volume.
See also
GetCenter, GetCenterAndExtents, GetExtent, GetSize
Definition at line 429 of file Box.h.
Init()
template<typename T> FORCEINLINE void UE::Math::TBox< T >::Init () inline
Set the initial values of the bounding box to Zero.
Definition at line 438 of file Box.h.
Intersect()
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::Intersect (const TBox< T > & Other) const
Checks whether the given bounding box intersects this bounding box.
Parameters
Other The bounding box to intersect with.
Returns
true if the boxes intersect, false otherwise.
Note
This function assumes boxes have closed bounds, i.e. boxes with coincident borders on any edge will overlap.
Definition at line 808 of file Box.h.
References TBox(), DiagnosticCheck(), FORCEINLINE, Max, Min, and Other.
Referenced by FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms(), and Overlap().
IntersectXY()
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IntersectXY (const TBox< T > & Other) const
Checks whether the given bounding box intersects this bounding box in the XY plane.
Parameters
Other The bounding box to test intersection.
Returns
true if the boxes intersect in the XY Plane, false otherwise.
Note
This function assumes boxes have closed bounds, i.e. boxes with coincident borders on any edge will overlap.
Definition at line 834 of file Box.h.
References TBox(), DiagnosticCheck(), FORCEINLINE, Max, Min, and Other.
InverseTransformBy()
template<typename T> TBox< T > UE::Math::TBox< T >::InverseTransformBy (const TTransform< T > & M) const nodiscard
Gets a bounding volume transformed by an inverted TTransform<T> object.
Parameters
M The transformation object to perform the inversely transform this box with.
Returns
The transformed box.
Definition at line 934 of file Box.h.
References TBox(), ForceInit, GetVertices(), UE::Math::TTransform< T >::InverseTransformPosition(), and UE_ARRAY_COUNT.
Referenced by FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms().
IsInside() [1/2]
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IsInside (const TBox< T > & Other) const inline
Checks whether a given box is fully encapsulated by this box.
Parameters
Other The box to test for encapsulation within the bounding volume.
Returns
true if box is inside this volume.
See also
IsInsideXY
Note
This function assumes boxes have open bounds, i.e. boxes with coincident borders on any edge are not encapsulated.
Definition at line 524 of file Box.h.
IsInside() [2/2]
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IsInside (const TVector< T > & In) const inline
Checks whether the given location is inside this box.
Parameters
In The location to test for inside the bounding volume.
Returns
true if location is inside this volume.
See also
IsInsideXY
Note
This function assumes boxes have open bounds, i.e. points lying on the border of the box are not inside. Use IsInsideOrOn to include borders in the test.
Definition at line 492 of file Box.h.
Referenced by UE::Math::TBox< double >::IsInside().
IsInsideOrOn() [1/2]
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IsInsideOrOn (const TBox< T > & Other) const inline
Checks whether a given box is fully encapsulated by this box.
Parameters
Other The box to test for encapsulation within the bounding volume.
Returns
true if box is inside this volume.
See also
IsInsideXY
Note
This function assumes boxes have closed bounds, i.e. boxes with coincident borders on any edge are encapsulated.
Definition at line 539 of file Box.h.
IsInsideOrOn() [2/2]
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IsInsideOrOn (const TVector< T > & In) const inline
Checks whether the given location is inside or on this box.
Parameters
In The location to test for inside or on the bounding volume.
Returns
true if location is inside or on this volume.
See also
IsInsideOrOnXY
Note
This function assumes boxes have closed bounds, i.e. points lying on the border of the box are inside. Use IsInside to exclude borders from the test.
Definition at line 508 of file Box.h.
Referenced by UE::Math::TBox< double >::IsInsideOrOn().
IsInsideOrOnXY()
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IsInsideOrOnXY (const TVector< T > & In) const inline
Checks whether the given location is inside or on this box in the XY plane.
Parameters
In The location to test for inside or on the bounding volume.
Returns
true if location is inside or on this box in the XY plane.
See also
IsInsideOrOn
Note
This function assumes boxes have closed bounds, i.e. points lying on the border of the box are not inside. Use IsInsideXY to exclude borders from the test.
Definition at line 570 of file Box.h.
IsInsideXY() [1/2]
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IsInsideXY (const TBox< T > & Other) const inline
Checks whether the given box is fully encapsulated by this box in the XY plane.
Parameters
Other The box to test for encapsulation within the bounding box.
Returns
true if box is inside this box in the XY plane.
See also
IsInside
Note
This function assumes boxes have open bounds, i.e. boxes with coincident borders on any edge are not encapsulated.
Definition at line 586 of file Box.h.
IsInsideXY() [2/2]
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::IsInsideXY (const TVector< T > & In) const inline
Checks whether the given location is inside this box in the XY plane.
Parameters
In The location to test for inside the bounding box.
Returns
true if location is inside this box in the XY plane.
See also
IsInside
Note
This function assumes boxes have open bounds, i.e. points lying on the border of the box are not inside. Use IsInsideOrOnXY to include borders in the test.
Definition at line 554 of file Box.h.
Referenced by UE::Math::TBox< double >::IsInsideXY().
MoveTo()
template<typename T> FORCEINLINE TBox< T > UE::Math::TBox< T >::MoveTo (const TVector< T > & Destination) const inline nodiscard
Returns a box with its center moved to the new destination.
Parameters
Destination The destination point to move center of box to.
Returns
A new bounding box.
Definition at line 360 of file Box.h.
operator!=()
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::operator!= (const TBox< T > & Other) const inline nodiscard
Compares two boxes for inequality.
Returns
false if the boxes are equal, true otherwise.
Definition at line 194 of file Box.h.
operator+() [1/2]
template<typename T> FORCEINLINE TBox< T > UE::Math::TBox< T >::operator+ (const TBox< T > & Other) const inline nodiscard
Gets the result of addition to this bounding volume.
Parameters
Other The other volume to add to this.
Returns
A new bounding volume.
Definition at line 246 of file Box.h.
operator+() [2/2]
template<typename T> FORCEINLINE TBox< T > UE::Math::TBox< T >::operator+ (const TVector< T > & Other) const inline nodiscard
Gets the result of addition to this bounding volume.
Parameters
Other The other point to add to this.
Returns
A new bounding volume.
Definition at line 227 of file Box.h.
operator+=() [1/2]
template<typename T> FORCEINLINE TBox< T > & UE::Math::TBox< T >::operator+= (const TBox< T > & Other)
Adds to this bounding box to include a new bounding volume.
Parameters
Other the bounding volume to increase the bounding volume to.
Returns
Reference to this bounding volume after resizing to include the other bounding volume.
Definition at line 741 of file Box.h.
References TBox(), DiagnosticCheck(), FORCEINLINE, IsValid, FMath::Max, Max, FMath::Min, Min, and Other.
operator+=() [2/2]
template<typename T> FORCEINLINE TBox< T > & UE::Math::TBox< T >::operator+= (const TVector< T > & Other)
Adds to this bounding box to include a given point.
Parameters
Other the point to increase the bounding volume to.
Returns
Reference to this bounding box after resizing to include the other point.
Definition at line 715 of file Box.h.
References TBox(), DiagnosticCheck(), FORCEINLINE, IsValid, FMath::Max, Max, FMath::Min, Min, and Other.
operator==()
template<typename T> FORCEINLINE bool UE::Math::TBox< T >::operator== (const TBox< T > & Other) const inline nodiscard
Compares two boxes for equality.
Returns true if both bounding boxes are invalid. Returns false if one of the bounding boxes is invalid.
Returns
true if the boxes are equal, false otherwise.
Definition at line 184 of file Box.h.
operator[]() [1/2]
template<typename T> FORCEINLINE TVector< T > & UE::Math::TBox< T >::operator[] (int32 Index) inline nodiscard
Gets reference to the min or max of this bounding volume.
Parameters
Index the index into points of the bounding volume.
Returns
a reference to a point of the bounding volume.
Definition at line 257 of file Box.h.
operator[]() [2/2]
template<typename T> FORCEINLINE const TVector< T > & UE::Math::TBox< T >::operator[] (int32 Index) const inline nodiscard
Definition at line 274 of file Box.h.
Overlap()
template<typename T> TBox< T > UE::Math::TBox< T >::Overlap (const TBox< T > & Other) const nodiscard
Returns the overlap TBox<T> of two box.
Parameters
Other The bounding box to test overlap
Returns
the overlap box. It can be 0 if they don't overlap
Definition at line 968 of file Box.h.
References TBox(), ForceInit, Intersect(), FMath::Max, Max, FMath::Min, Min, Other, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Serialize() [1/2]
template<typename T> bool UE::Math::TBox< T >::Serialize (FArchive & Ar) inline
Definition at line 681 of file Box.h.
Serialize() [2/2]
template<typename T> bool UE::Math::TBox< T >::Serialize (FStructuredArchive::FSlot Slot) inline
Definition at line 687 of file Box.h.
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TBox< T >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 693 of file Box.h.
ShiftBy()
template<typename T> FORCEINLINE TBox< T > UE::Math::TBox< T >::ShiftBy (const TVector< T > & Offset) const inline nodiscard
Returns a box with its position shifted.
Parameters
Offset The vector to shift the box by.
Returns
A new bounding box.
Definition at line 349 of file Box.h.
ToCompactString()
template<typename T> FORCEINLINE FString UE::Math::TBox< T >::ToCompactString () const
Get a textual representation of this box, without min/max values if invalid.
Returns
A string describing the box.
Definition at line 861 of file Box.h.
References FORCEINLINE, IsValid, Max, Min, and TEXT.
ToString()
template<typename T> FORCEINLINE FString UE::Math::TBox< T >::ToString () const
Get a textual representation of this box.
Returns
A string describing the box.
Definition at line 855 of file Box.h.
References FORCEINLINE, IsValid, Max, Min, and TEXT.
TransformBy() [1/2]
template<typename T> TBox< T > UE::Math::TBox< T >::TransformBy (const TMatrix< T > & M) const nodiscard
Gets a bounding volume transformed by a matrix.
Parameters
M The matrix to transform by.
Returns
The transformed box.
See also
TransformProjectBy
Definition at line 868 of file Box.h.
References TBox(), DiagnosticCheck(), ForceInit, IsValid, UE::Math::TMatrix< T >::M, Max, Min, Origin, VectorAbs(), VectorAdd(), VectorLoadAligned(), VectorMultiply(), VectorMultiplyAdd(), VectorReplicate, VectorSetFloat1(), VectorStoreFloat3(), and VectorSubtract().
Referenced by FInstancedSkinnedMeshComponentHelper::CalcBounds(), FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms(), and TransformBy().
TransformBy() [2/2]
template<typename T> TBox< T > UE::Math::TBox< T >::TransformBy (const TTransform< T > & M) const nodiscard
Gets a bounding volume transformed by a TTransform<T> object.
Parameters
M The transformation object.
Returns
The transformed box.
See also
TransformProjectBy
Definition at line 913 of file Box.h.
References TBox(), UE::Math::TTransform< T >::ToMatrixWithScale(), and TransformBy().
TransformProjectBy()
template<typename T> TBox< T > UE::Math::TBox< T >::TransformProjectBy (const TMatrix< T > & ProjM) const nodiscard
Returns the current world bounding box transformed and projected to screen space.
Parameters
ProjM The projection matrix.
Returns
The transformed box.
See also
TransformBy
Definition at line 951 of file Box.h.
References TBox(), ForceInit, GetVertices(), UE::Math::TMatrix< T >::TransformPosition(), UE_ARRAY_COUNT, and UE::Math::TVector4< T >::W.
Friends And Related Symbol Documentation
operator<< [1/2]
template<typename T> FArchive & operator<< (FArchive & Ar, TBox< T > & Box) friend
Serializes the bounding box.
Parameters
Ar The archive to serialize into.
Box The box to serialize.
Returns
Reference to the Archive after serialization.
Definition at line 664 of file Box.h.
operator<< [2/2]
template<typename T> void operator<< (FStructuredArchive::FSlot Slot, TBox< T > & Box) friend
Serializes the bounding box.
Parameters
Slot The structured archive slot to serialize into.
Box The box to serialize.
Definition at line 675 of file Box.h.
Field Documentation
IsValid
template<typename T> uint8 UE::Math::TBox< T >::IsValid
Holds a flag indicating whether this box is valid.
Definition at line 46 of file Box.h.
Referenced by FWorldPartitionRelativeBounds::FWorldPartitionRelativeBounds(), FInstancedSkinnedMeshComponentHelper::CalcBounds(), TSimpleCellGrid< CellType, InvalidCellValue >::GetCellRectangleFromBox(), FInstancedStaticMeshComponentHelper::GetInstanceNavigationBounds(), FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), UE::Geometry::TAxisAlignedBox3< float >::operator TBox< OutRealType >(), operator+=(), operator+=(), ToCompactString(), ToString(), TransformBy(), and UCLASS().
Max
template<typename T> TVector<T> UE::Math::TBox< T >::Max
Holds the box's maximum point.
Definition at line 43 of file Box.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcCellLocation(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcQueryBounds(), FSquare2DGridHelper::FGrid2D::ForEachIntersectingCellsBreakable(), TSimpleCellGrid< CellType, InvalidCellValue >::GetCellRectangleFromBox(), GetClosestPointTo(), TBVTree< InElementType, InAllocator >::GetLongestAxis(), FSquare2DGridHelper::FGrid2D::GetNumIntersectingCells(), GetVertices(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), Intersect(), IntersectXY(), operator+=(), operator+=(), FWorldTileInfo::operator==(), Overlap(), ToCompactString(), ToString(), and TransformBy().
Min
template<typename T> TVector<T> UE::Math::TBox< T >::Min
Holds the box's minimum point.
Definition at line 40 of file Box.h.
Referenced by THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcCellLocation(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcQueryBounds(), FSquare2DGridHelper::FGrid2D::ForEachIntersectingCellsBreakable(), TSimpleCellGrid< CellType, InvalidCellValue >::GetCellRectangleFromBox(), GetClosestPointTo(), TBVTree< InElementType, InAllocator >::GetLongestAxis(), FSquare2DGridHelper::FGrid2D::GetNumIntersectingCells(), GetVertices(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), Intersect(), IntersectXY(), operator+=(), operator+=(), FWorldTileInfo::operator==(), Overlap(), ToCompactString(), ToString(), and TransformBy().
The documentation for this struct was generated from the following file:
Box.h