Unreal Engine 5.6 C++ API: TSlotBase< SlotType >::FSlotArguments Struct Reference
TSlotBase< SlotType >::FSlotArguments Struct Reference
Struct to construct a slot.
#include "SlotBase.h"
Public Member Functions
FSlotArguments (const FSlotArguments &)=delete
FSlotArguments (EConstructSlotIsFChildren)
FSlotArguments (FSlotArguments &&)=default
FSlotArguments (TUniquePtr< SlotType > InSlot)
void AttachWidget (const TSharedRef< SWidget > &InChildWidget)
Attach the child widget the slot will own.
SlotType::FSlotArguments & Expose (SlotType *&OutVarToInit)
Initialize OutVarToInit with the slot that is being constructed.
const TSharedPtr< SWidget > & GetAttachedWidget () const
SlotType * GetSlot () const
SlotType::FSlotArguments & Me ()
Used by the named argument pattern as a safe way to 'return *this' for call-chaining purposes.
FSlotArguments & operator= (const FSlotArguments &)=delete
FSlotArguments & operator= (FSlotArguments &&)=default
SlotType::FSlotArguments & operator[] (const TSharedRef< SWidget > &InChildWidget)
SlotType::FSlotArguments & operator[] (TSharedRef< SWidget > &&InChildWidget)
Attach the child widget the slot will own.
TUniquePtr< SlotType > StealSlot ()
Steal the slot that is being constructed from the FSlotArguments.
Private Attributes
TSharedPtr< SWidget > ChildWidget
TUniquePtr< SlotType > Slot
Detailed Description
template<typename SlotType>
struct TSlotBase< SlotType >::FSlotArguments
Struct to construct a slot.
Definition at line 148 of file SlotBase.h.
Constructor & Destructor Documentation
FSlotArguments() [1/4]
template<typename SlotType> TSlotBase< SlotType >::FSlotArguments::FSlotArguments (EConstructSlotIsFChildren) inline
Definition at line 151 of file SlotBase.h.
Referenced by FSlotArguments(), FSlotArguments(), operator=(), and operator=().
FSlotArguments() [2/4]
template<typename SlotType> TSlotBase< SlotType >::FSlotArguments::FSlotArguments (TUniquePtr< SlotType > InSlot) inline
Definition at line 152 of file SlotBase.h.
References check, MoveTemp(), and Slot.
FSlotArguments() [3/4]
template<typename SlotType> TSlotBase< SlotType >::FSlotArguments::FSlotArguments (const FSlotArguments &) delete
References FSlotArguments().
FSlotArguments() [4/4]
template<typename SlotType> TSlotBase< SlotType >::FSlotArguments::FSlotArguments (FSlotArguments &&) default
References FSlotArguments().
Member Function Documentation
AttachWidget()
template<typename SlotType> void TSlotBase< SlotType >::FSlotArguments::AttachWidget (const TSharedRef< SWidget > & InChildWidget) inline
Attach the child widget the slot will own.
Definition at line 184 of file SlotBase.h.
References ChildWidget.
Referenced by TSingleWidgetChildrenWithSlot< SlotType >::FSlotArguments::operator[]().
Expose()
template<typename SlotType> SlotType::FSlotArguments & TSlotBase< SlotType >::FSlotArguments::Expose (SlotType *& OutVarToInit) inline
Initialize OutVarToInit with the slot that is being constructed.
Definition at line 177 of file SlotBase.h.
References Me(), and Slot.
GetAttachedWidget()
template<typename SlotType> const TSharedPtr< SWidget > & TSlotBase< SlotType >::FSlotArguments::GetAttachedWidget () const inline
Returns
the child widget that will be owned by the slot.
Definition at line 190 of file SlotBase.h.
References ChildWidget.
GetSlot()
template<typename SlotType> SlotType * TSlotBase< SlotType >::FSlotArguments::GetSlot () const inline
Returns
the slot that is being constructed.
Definition at line 193 of file SlotBase.h.
References Slot.
Me()
template<typename SlotType> SlotType::FSlotArguments & TSlotBase< SlotType >::FSlotArguments::Me () inline
Used by the named argument pattern as a safe way to 'return *this' for call-chaining purposes.
Definition at line 202 of file SlotBase.h.
Referenced by Expose(), operator[](), and operator[]().
operator=() [1/2]
template<typename SlotType> FSlotArguments & TSlotBase< SlotType >::FSlotArguments::operator= (const FSlotArguments &) delete
References FSlotArguments().
operator=() [2/2]
template<typename SlotType> FSlotArguments & TSlotBase< SlotType >::FSlotArguments::operator= (FSlotArguments &&) default
References FSlotArguments().
operator[]() [1/2]
template<typename SlotType> SlotType::FSlotArguments & TSlotBase< SlotType >::FSlotArguments::operator[] (const TSharedRef< SWidget > & InChildWidget) inline
Definition at line 170 of file SlotBase.h.
References ChildWidget, and Me().
operator[]() [2/2]
template<typename SlotType> SlotType::FSlotArguments & TSlotBase< SlotType >::FSlotArguments::operator[] (TSharedRef< SWidget > && InChildWidget) inline
Attach the child widget the slot will own.
Definition at line 165 of file SlotBase.h.
References ChildWidget, Me(), and MoveTemp().
StealSlot()
template<typename SlotType> TUniquePtr< SlotType > TSlotBase< SlotType >::FSlotArguments::StealSlot () inline
Steal the slot that is being constructed from the FSlotArguments.
Definition at line 196 of file SlotBase.h.
References MoveTemp(), and Slot.
Field Documentation
ChildWidget
template<typename SlotType> TSharedPtr<SWidget> TSlotBase< SlotType >::FSlotArguments::ChildWidget private
Definition at line 209 of file SlotBase.h.
Referenced by AttachWidget(), GetAttachedWidget(), operator[](), and operator[]().
Slot
template<typename SlotType> TUniquePtr<SlotType> TSlotBase< SlotType >::FSlotArguments::Slot private
Definition at line 208 of file SlotBase.h.
Referenced by FSlotArguments(), Expose(), GetSlot(), and StealSlot().
The documentation for this struct was generated from the following file:
SlotBase.h