Unreal Engine 5.6 C++ API: FCurveEditorCommands Class Reference
FCurveEditorCommands Class Reference
Defines commands for SCurveEditorPanel (and UnrealEd::SCurveEditor)
#include "CurveEditorCommands.h"
Public Member Functions
FCurveEditorCommands ()
virtual void RegisterCommands () override
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TSharedPtr< FUICommandInfo > AddKeyHovered
TSharedPtr< FUICommandInfo > AddKeyToAllCurves
TSharedPtr< FUICommandInfo > ApplyBufferedCurves
TSharedPtr< FUICommandInfo > BakeCurve
TSharedPtr< FUICommandInfo > BufferVisibleCurves
TSharedPtr< FUICommandInfo > ClearSelectionRange
TSharedPtr< FUICommandInfo > DeactivateCurrentTool
TSharedPtr< FUICommandInfo > DeselectAllKeys
TSharedPtr< FUICommandInfo > FlattenTangents
TSharedPtr< FUICommandInfo > FlipCurveHorizontal
TSharedPtr< FUICommandInfo > FlipCurveVertical
TSharedPtr< FUICommandInfo > InterpolationConstant
TSharedPtr< FUICommandInfo > InterpolationCubicAuto
TSharedPtr< FUICommandInfo > InterpolationCubicBreak
TSharedPtr< FUICommandInfo > InterpolationCubicSmartAuto
TSharedPtr< FUICommandInfo > InterpolationCubicUser
TSharedPtr< FUICommandInfo > InterpolationLinear
TSharedPtr< FUICommandInfo > InterpolationToggleWeighted
TSharedPtr< FUICommandInfo > InvertSelection
TSharedPtr< FUICommandInfo > JumpToEnd
TSharedPtr< FUICommandInfo > JumpToStart
TSharedPtr< FUICommandInfo > MatchFirstTangentToLast
TSharedPtr< FUICommandInfo > MatchLastTangentToFirst
TSharedPtr< FUICommandInfo > OpenUserImplementableFilterWindow
TSharedPtr< FUICommandInfo > PasteAndMerge
TSharedPtr< FUICommandInfo > PasteKeysHovered
TSharedPtr< FUICommandInfo > PasteRelative
TSharedPtr< FUICommandInfo > ReduceCurve
TSharedPtr< FUICommandInfo > ScrubTime
TSharedPtr< FUICommandInfo > SelectAllKeys
TSharedPtr< FUICommandInfo > SelectBackward
TSharedPtr< FUICommandInfo > SelectForward
TSharedPtr< FUICommandInfo > SelectNone
TSharedPtr< FUICommandInfo > SetAllTangentsVisibility
TSharedPtr< FUICommandInfo > SetAxisSnappingHorizontal
TSharedPtr< FUICommandInfo > SetAxisSnappingNone
TSharedPtr< FUICommandInfo > SetAxisSnappingVertical
TSharedPtr< FUICommandInfo > SetCurveColorsForSelected
TSharedPtr< FUICommandInfo > SetNoTangentsVisibility
TSharedPtr< FUICommandInfo > SetPostInfinityExtrapConstant
TSharedPtr< FUICommandInfo > SetPostInfinityExtrapCycle
TSharedPtr< FUICommandInfo > SetPostInfinityExtrapCycleWithOffset
TSharedPtr< FUICommandInfo > SetPostInfinityExtrapLinear
TSharedPtr< FUICommandInfo > SetPostInfinityExtrapOscillate
TSharedPtr< FUICommandInfo > SetPreInfinityExtrapConstant
TSharedPtr< FUICommandInfo > SetPreInfinityExtrapCycle
TSharedPtr< FUICommandInfo > SetPreInfinityExtrapCycleWithOffset
TSharedPtr< FUICommandInfo > SetPreInfinityExtrapLinear
TSharedPtr< FUICommandInfo > SetPreInfinityExtrapOscillate
TSharedPtr< FUICommandInfo > SetRandomCurveColorsForSelected
TSharedPtr< FUICommandInfo > SetSelectedKeysTangentVisibility
TSharedPtr< FUICommandInfo > SetSelectionRangeEnd
TSharedPtr< FUICommandInfo > SetSelectionRangeStart
TSharedPtr< FUICommandInfo > SetViewModeAbsolute
TSharedPtr< FUICommandInfo > SetViewModeNormalized
TSharedPtr< FUICommandInfo > SetViewModeStacked
TSharedPtr< FUICommandInfo > SmartSnapKeys
TSharedPtr< FUICommandInfo > StepBackward
TSharedPtr< FUICommandInfo > StepForward
TSharedPtr< FUICommandInfo > StepToNextKey
TSharedPtr< FUICommandInfo > StepToPreviousKey
TSharedPtr< FUICommandInfo > StraightenTangents
TSharedPtr< FUICommandInfo > SwapBufferedCurves
TSharedPtr< FUICommandInfo > ToggleAutoFrameCurveEditor
TSharedPtr< FUICommandInfo > ToggleExpandCollapseNodes
TSharedPtr< FUICommandInfo > ToggleExpandCollapseNodesAndDescendants
TSharedPtr< FUICommandInfo > ToggleInputSnapping
TSharedPtr< FUICommandInfo > ToggleOutputSnapping
TSharedPtr< FUICommandInfo > ToggleShowBars
TSharedPtr< FUICommandInfo > ToggleShowBufferedCurves
TSharedPtr< FUICommandInfo > ToggleShowCurveEditorCurveToolTips
TSharedPtr< FUICommandInfo > ToggleShowValueIndicatorLines
TSharedPtr< FUICommandInfo > ToggleSnapTimeToSelection
TSharedPtr< FUICommandInfo > TranslateSelectedKeysLeft
TSharedPtr< FUICommandInfo > TranslateSelectedKeysRight
TSharedPtr< FUICommandInfo > ZoomToFit
TSharedPtr< FUICommandInfo > ZoomToFitAll
TSharedPtr< FUICommandInfo > ZoomToFitHorizontal
TSharedPtr< FUICommandInfo > ZoomToFitVertical
Additional Inherited Members
Static Public Member Functions inherited from TCommands< FCurveEditorCommands >
static FCurveEditorCommands & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Protected Member Functions inherited from TCommands< FCurveEditorCommands >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TCommands< FCurveEditorCommands >
static TWeakPtr< FCurveEditorCommands > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Defines commands for SCurveEditorPanel (and UnrealEd::SCurveEditor)
Definition at line 18 of file CurveEditorCommands.h.
Constructor & Destructor Documentation
FCurveEditorCommands()
FCurveEditorCommands::FCurveEditorCommands () inline
Definition at line 21 of file CurveEditorCommands.h.
References FCurveEditorCommands(), TCommands< FCurveEditorCommands >::TCommands(), NSLOCTEXT, and TEXT.
Referenced by FCurveEditorCommands().
Member Function Documentation
RegisterCommands()
virtual void FCurveEditorCommands::RegisterCommands () override virtual
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Implements TCommands< FCurveEditorCommands >.
Field Documentation
AddKeyHovered
TSharedPtr<FUICommandInfo> FCurveEditorCommands::AddKeyHovered
Definition at line 91 of file CurveEditorCommands.h.
AddKeyToAllCurves
TSharedPtr<FUICommandInfo> FCurveEditorCommands::AddKeyToAllCurves
Definition at line 96 of file CurveEditorCommands.h.
ApplyBufferedCurves
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ApplyBufferedCurves
Definition at line 114 of file CurveEditorCommands.h.
BakeCurve
TSharedPtr<FUICommandInfo> FCurveEditorCommands::BakeCurve
Definition at line 62 of file CurveEditorCommands.h.
BufferVisibleCurves
TSharedPtr<FUICommandInfo> FCurveEditorCommands::BufferVisibleCurves
Definition at line 112 of file CurveEditorCommands.h.
ClearSelectionRange
TSharedPtr< FUICommandInfo > FCurveEditorCommands::ClearSelectionRange
Definition at line 140 of file CurveEditorCommands.h.
DeactivateCurrentTool
TSharedPtr<FUICommandInfo> FCurveEditorCommands::DeactivateCurrentTool
Definition at line 102 of file CurveEditorCommands.h.
DeselectAllKeys
TSharedPtr<FUICommandInfo> FCurveEditorCommands::DeselectAllKeys
Definition at line 105 of file CurveEditorCommands.h.
FlattenTangents
TSharedPtr<FUICommandInfo> FCurveEditorCommands::FlattenTangents
Definition at line 54 of file CurveEditorCommands.h.
FlipCurveHorizontal
TSharedPtr<FUICommandInfo> FCurveEditorCommands::FlipCurveHorizontal
Definition at line 39 of file CurveEditorCommands.h.
FlipCurveVertical
TSharedPtr<FUICommandInfo> FCurveEditorCommands::FlipCurveVertical
Definition at line 40 of file CurveEditorCommands.h.
InterpolationConstant
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InterpolationConstant
Definition at line 45 of file CurveEditorCommands.h.
InterpolationCubicAuto
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InterpolationCubicAuto
Definition at line 47 of file CurveEditorCommands.h.
InterpolationCubicBreak
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InterpolationCubicBreak
Definition at line 50 of file CurveEditorCommands.h.
InterpolationCubicSmartAuto
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InterpolationCubicSmartAuto
Definition at line 48 of file CurveEditorCommands.h.
InterpolationCubicUser
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InterpolationCubicUser
Definition at line 49 of file CurveEditorCommands.h.
InterpolationLinear
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InterpolationLinear
Definition at line 46 of file CurveEditorCommands.h.
InterpolationToggleWeighted
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InterpolationToggleWeighted
Definition at line 51 of file CurveEditorCommands.h.
InvertSelection
TSharedPtr<FUICommandInfo> FCurveEditorCommands::InvertSelection
Definition at line 110 of file CurveEditorCommands.h.
JumpToEnd
TSharedPtr<FUICommandInfo> FCurveEditorCommands::JumpToEnd
Definition at line 134 of file CurveEditorCommands.h.
JumpToStart
TSharedPtr<FUICommandInfo> FCurveEditorCommands::JumpToStart
Definition at line 133 of file CurveEditorCommands.h.
MatchFirstTangentToLast
TSharedPtr< FUICommandInfo > FCurveEditorCommands::MatchFirstTangentToLast
Definition at line 60 of file CurveEditorCommands.h.
MatchLastTangentToFirst
TSharedPtr< FUICommandInfo > FCurveEditorCommands::MatchLastTangentToFirst
Definition at line 59 of file CurveEditorCommands.h.
OpenUserImplementableFilterWindow
TSharedPtr<FUICommandInfo> FCurveEditorCommands::OpenUserImplementableFilterWindow
Definition at line 117 of file CurveEditorCommands.h.
PasteAndMerge
TSharedPtr<FUICommandInfo> FCurveEditorCommands::PasteAndMerge
Definition at line 93 of file CurveEditorCommands.h.
PasteKeysHovered
TSharedPtr<FUICommandInfo> FCurveEditorCommands::PasteKeysHovered
Definition at line 92 of file CurveEditorCommands.h.
PasteRelative
TSharedPtr<FUICommandInfo> FCurveEditorCommands::PasteRelative
Definition at line 94 of file CurveEditorCommands.h.
ReduceCurve
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ReduceCurve
Definition at line 63 of file CurveEditorCommands.h.
ScrubTime
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ScrubTime
Definition at line 135 of file CurveEditorCommands.h.
SelectAllKeys
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SelectAllKeys
Definition at line 104 of file CurveEditorCommands.h.
SelectBackward
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SelectBackward
Definition at line 108 of file CurveEditorCommands.h.
SelectForward
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SelectForward
Definition at line 107 of file CurveEditorCommands.h.
SelectNone
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SelectNone
Definition at line 109 of file CurveEditorCommands.h.
SetAllTangentsVisibility
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetAllTangentsVisibility
Definition at line 77 of file CurveEditorCommands.h.
SetAxisSnappingHorizontal
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetAxisSnappingHorizontal
Definition at line 121 of file CurveEditorCommands.h.
SetAxisSnappingNone
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetAxisSnappingNone
Definition at line 120 of file CurveEditorCommands.h.
SetAxisSnappingVertical
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetAxisSnappingVertical
Definition at line 122 of file CurveEditorCommands.h.
SetCurveColorsForSelected
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetCurveColorsForSelected
Definition at line 89 of file CurveEditorCommands.h.
SetNoTangentsVisibility
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetNoTangentsVisibility
Definition at line 79 of file CurveEditorCommands.h.
SetPostInfinityExtrapConstant
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPostInfinityExtrapConstant
Definition at line 75 of file CurveEditorCommands.h.
SetPostInfinityExtrapCycle
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPostInfinityExtrapCycle
Definition at line 71 of file CurveEditorCommands.h.
SetPostInfinityExtrapCycleWithOffset
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPostInfinityExtrapCycleWithOffset
Definition at line 72 of file CurveEditorCommands.h.
SetPostInfinityExtrapLinear
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPostInfinityExtrapLinear
Definition at line 74 of file CurveEditorCommands.h.
SetPostInfinityExtrapOscillate
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPostInfinityExtrapOscillate
Definition at line 73 of file CurveEditorCommands.h.
SetPreInfinityExtrapConstant
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPreInfinityExtrapConstant
Definition at line 69 of file CurveEditorCommands.h.
SetPreInfinityExtrapCycle
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPreInfinityExtrapCycle
Definition at line 65 of file CurveEditorCommands.h.
SetPreInfinityExtrapCycleWithOffset
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPreInfinityExtrapCycleWithOffset
Definition at line 66 of file CurveEditorCommands.h.
SetPreInfinityExtrapLinear
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPreInfinityExtrapLinear
Definition at line 68 of file CurveEditorCommands.h.
SetPreInfinityExtrapOscillate
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetPreInfinityExtrapOscillate
Definition at line 67 of file CurveEditorCommands.h.
SetRandomCurveColorsForSelected
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetRandomCurveColorsForSelected
Definition at line 88 of file CurveEditorCommands.h.
SetSelectedKeysTangentVisibility
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetSelectedKeysTangentVisibility
Definition at line 78 of file CurveEditorCommands.h.
SetSelectionRangeEnd
TSharedPtr< FUICommandInfo > FCurveEditorCommands::SetSelectionRangeEnd
Definition at line 139 of file CurveEditorCommands.h.
SetSelectionRangeStart
TSharedPtr< FUICommandInfo > FCurveEditorCommands::SetSelectionRangeStart
Definition at line 138 of file CurveEditorCommands.h.
SetViewModeAbsolute
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetViewModeAbsolute
Definition at line 98 of file CurveEditorCommands.h.
SetViewModeNormalized
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetViewModeNormalized
Definition at line 100 of file CurveEditorCommands.h.
SetViewModeStacked
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SetViewModeStacked
Definition at line 99 of file CurveEditorCommands.h.
SmartSnapKeys
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SmartSnapKeys
Definition at line 57 of file CurveEditorCommands.h.
StepBackward
TSharedPtr<FUICommandInfo> FCurveEditorCommands::StepBackward
Definition at line 132 of file CurveEditorCommands.h.
StepForward
TSharedPtr<FUICommandInfo> FCurveEditorCommands::StepForward
Definition at line 131 of file CurveEditorCommands.h.
StepToNextKey
TSharedPtr<FUICommandInfo> FCurveEditorCommands::StepToNextKey
Definition at line 129 of file CurveEditorCommands.h.
StepToPreviousKey
TSharedPtr<FUICommandInfo> FCurveEditorCommands::StepToPreviousKey
Definition at line 130 of file CurveEditorCommands.h.
StraightenTangents
TSharedPtr<FUICommandInfo> FCurveEditorCommands::StraightenTangents
Definition at line 55 of file CurveEditorCommands.h.
SwapBufferedCurves
TSharedPtr<FUICommandInfo> FCurveEditorCommands::SwapBufferedCurves
Definition at line 113 of file CurveEditorCommands.h.
ToggleAutoFrameCurveEditor
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleAutoFrameCurveEditor
Definition at line 81 of file CurveEditorCommands.h.
ToggleExpandCollapseNodes
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleExpandCollapseNodes
Definition at line 42 of file CurveEditorCommands.h.
ToggleExpandCollapseNodesAndDescendants
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleExpandCollapseNodesAndDescendants
Definition at line 43 of file CurveEditorCommands.h.
ToggleInputSnapping
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleInputSnapping
Definition at line 36 of file CurveEditorCommands.h.
ToggleOutputSnapping
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleOutputSnapping
Definition at line 37 of file CurveEditorCommands.h.
ToggleShowBars
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleShowBars
Definition at line 85 of file CurveEditorCommands.h.
ToggleShowBufferedCurves
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleShowBufferedCurves
Definition at line 83 of file CurveEditorCommands.h.
ToggleShowCurveEditorCurveToolTips
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleShowCurveEditorCurveToolTips
Definition at line 84 of file CurveEditorCommands.h.
ToggleShowValueIndicatorLines
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleShowValueIndicatorLines
Definition at line 86 of file CurveEditorCommands.h.
ToggleSnapTimeToSelection
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ToggleSnapTimeToSelection
Definition at line 82 of file CurveEditorCommands.h.
TranslateSelectedKeysLeft
TSharedPtr<FUICommandInfo> FCurveEditorCommands::TranslateSelectedKeysLeft
Definition at line 125 of file CurveEditorCommands.h.
TranslateSelectedKeysRight
TSharedPtr<FUICommandInfo> FCurveEditorCommands::TranslateSelectedKeysRight
Definition at line 126 of file CurveEditorCommands.h.
ZoomToFit
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ZoomToFit
Definition at line 34 of file CurveEditorCommands.h.
ZoomToFitAll
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ZoomToFitAll
Definition at line 35 of file CurveEditorCommands.h.
ZoomToFitHorizontal
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ZoomToFitHorizontal
Definition at line 32 of file CurveEditorCommands.h.
ZoomToFitVertical
TSharedPtr<FUICommandInfo> FCurveEditorCommands::ZoomToFitVertical
Definition at line 33 of file CurveEditorCommands.h.
The documentation for this class was generated from the following file:
CurveEditorCommands.h