Unreal Engine 5.6 C++ API: LazyObjectPtr.h File Reference
LazyObjectPtr.h File Reference
#include "Containers/UnrealString.h"
#include "CoreGlobals.h"
#include "HAL/Platform.h"
#include "HAL/ThreadSafeCounter.h"
#include "Misc/Guid.h"
#include "Serialization/Archive.h"
#include "Serialization/StructuredArchive.h"
#include "Templates/Casts.h"
#include "Templates/Requires.h"
#include "Templates/UnrealTemplate.h"
#include "UObject/Object.h"
#include "UObject/PersistentObjectPtr.h"
#include <type_traits>
Data Structures
struct FLazyObjectPtr
FLazyObjectPtr is a type of weak pointer to a UObject that uses a GUID created at save time.
struct FUniqueObjectGuid
Wrapper structure for a GUID that uniquely identifies registered UObjects.
struct TIsPODType< FLazyObjectPtr >
struct TIsPODType< FUniqueObjectGuid >
struct TIsPODType< TLazyObjectPtr< T > >
struct TIsWeakPointerType< FLazyObjectPtr >
struct TIsWeakPointerType< TLazyObjectPtr< T > >
struct TLazyObjectPtr< T >
TLazyObjectPtr is the templatized version of the generic FLazyObjectPtr.
Functions
template<typename T>
FORCEINLINE uint32 GetTypeHash (const TLazyObjectPtr< T > &LazyObjectPtr)
Hash function.
template<typename T, typename U, typename = decltype((T*)nullptr != (U*)nullptr)>
FORCEINLINE bool operator!= (const U *Lhs, const TLazyObjectPtr< T > &Rhs)
Compare for inequality with a raw pointer.
template<typename T>
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR, const TLazyObjectPtr< T > &Rhs)
Compare for inequality with null.
template<typename T>
FArchive & operator<< (FArchive &Ar, TLazyObjectPtr< T > &LazyObjectPtr)
template<typename T, typename U, typename = decltype((T*)nullptr == (U*)nullptr)>
FORCEINLINE bool operator== (const U *Lhs, const TLazyObjectPtr< T > &Rhs)
Compare for equality with a raw pointer.
template<typename T>
FORCEINLINE bool operator== (TYPE_OF_NULLPTR, const TLazyObjectPtr< T > &Rhs)
Compare to null.
Function Documentation
GetTypeHash()
template<typename T> FORCEINLINE uint32 GetTypeHash (const TLazyObjectPtr< T > & LazyObjectPtr)
Hash function.
Definition at line 420 of file LazyObjectPtr.h.
References FORCEINLINE, and LazyObjectPtr.
Referenced by TLazyObjectPtr< T >::GetLazyObjecPtrTypeHash().
operator!=() [1/2]
template<typename T, typename U, typename = decltype((T*)nullptr != (U*)nullptr)> FORCEINLINE bool operator!= (const U * Lhs, const TLazyObjectPtr< T > & Rhs)
Compare for inequality with a raw pointer.
Definition at line 448 of file LazyObjectPtr.h.
References FORCEINLINE, and TLazyObjectPtr< T >::Get().
operator!=() [2/2]
template<typename T> FORCEINLINE bool operator!= (TYPE_OF_NULLPTR , const TLazyObjectPtr< T > & Rhs)
Compare for inequality with null.
Definition at line 455 of file LazyObjectPtr.h.
References FORCEINLINE, and TLazyObjectPtr< T >::IsValid().
operator<<()
template<typename T> FArchive & operator<< (FArchive & Ar, TLazyObjectPtr< T > & LazyObjectPtr)
Definition at line 426 of file LazyObjectPtr.h.
References Ar, and LazyObjectPtr.
operator==() [1/2]
template<typename T, typename U, typename = decltype((T*)nullptr == (U*)nullptr)> FORCEINLINE bool operator== (const U * Lhs, const TLazyObjectPtr< T > & Rhs)
Compare for equality with a raw pointer.
Definition at line 434 of file LazyObjectPtr.h.
References FORCEINLINE, and TLazyObjectPtr< T >::Get().
operator==() [2/2]
template<typename T> FORCEINLINE bool operator== (TYPE_OF_NULLPTR , const TLazyObjectPtr< T > & Rhs)
Compare to null.
Definition at line 441 of file LazyObjectPtr.h.
References FORCEINLINE, and TLazyObjectPtr< T >::IsValid().