Unreal Engine 5.6 C++ API: UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites > Struct Template Reference
UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites > Struct Template Reference
#include "MovieScenePropertyComponentHandler.h"
Public Types
using StorageType = typename PropertyTraits::StorageType
Public Member Functions
TCompositePropertyDefinitionBuilder (FPropertyDefinition *InDefinition, FPropertyRegistry *InRegistry)
TCompositePropertyDefinitionBuilder< PropertyTraits, Composites..., double > AddComposite (TComponentTypeID< double > InComponent, double StorageType::*DataPtr)
template<typename T>
TCompositePropertyDefinitionBuilder< PropertyTraits, Composites..., T > AddComposite (TComponentTypeID< T > InComponent, T StorageType::*DataPtr)
void Commit ()
template<typename HandlerType>
void Commit (HandlerType &&InHandler)
template<typename BlenderSystemType>
TCompositePropertyDefinitionBuilder< PropertyTraits, Composites... > & SetBlenderSystem ()
TCompositePropertyDefinitionBuilder< PropertyTraits, Composites... > & SetBlenderSystem (UClass *BlenderSystemClass)
template<int InlineSize>
TCompositePropertyDefinitionBuilder< PropertyTraits, Composites... > & SetCustomAccessors (TCustomPropertyRegistration< PropertyTraits, InlineSize > *InCustomAccessors)
Private Attributes
FPropertyDefinition * Definition
FPropertyRegistry * Registry
Detailed Description
template<typename PropertyTraits, typename... Composites>
struct UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >
Definition at line 711 of file MovieScenePropertyComponentHandler.h.
Member Typedef Documentation
StorageType
template<typename PropertyTraits, typename... Composites> using UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::StorageType = typename PropertyTraits::StorageType
Definition at line 713 of file MovieScenePropertyComponentHandler.h.
Constructor & Destructor Documentation
TCompositePropertyDefinitionBuilder()
template<typename PropertyTraits, typename... Composites> UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::TCompositePropertyDefinitionBuilder (FPropertyDefinition * InDefinition, FPropertyRegistry * InRegistry) inline
Definition at line 717 of file MovieScenePropertyComponentHandler.h.
References Definition, and Registry.
Referenced by AddComposite(), AddComposite(), SetBlenderSystem(), SetBlenderSystem(), and SetCustomAccessors().
Member Function Documentation
AddComposite() [1/2]
template<typename PropertyTraits, typename... Composites> TCompositePropertyDefinitionBuilder< PropertyTraits, Composites..., double > UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::AddComposite (TComponentTypeID< double > InComponent, double StorageType::* DataPtr) inline
Definition at line 742 of file MovieScenePropertyComponentHandler.h.
References TCompositePropertyDefinitionBuilder(), checkf, Definition, Registry, and TEXT.
AddComposite() [2/2]
template<typename PropertyTraits, typename... Composites> template<typename T> TCompositePropertyDefinitionBuilder< PropertyTraits, Composites..., T > UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::AddComposite (TComponentTypeID< T > InComponent, T StorageType::* DataPtr) inline
Definition at line 722 of file MovieScenePropertyComponentHandler.h.
References TCompositePropertyDefinitionBuilder(), checkf, Definition, Registry, and TEXT.
Commit() [1/2]
template<typename PropertyTraits, typename... Composites> void UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::Commit () inline
Definition at line 777 of file MovieScenePropertyComponentHandler.h.
References Definition.
Commit() [2/2]
template<typename PropertyTraits, typename... Composites> template<typename HandlerType> void UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::Commit (HandlerType && InHandler) inline
Definition at line 784 of file MovieScenePropertyComponentHandler.h.
References Definition, and Forward().
SetBlenderSystem() [1/2]
template<typename PropertyTraits, typename... Composites> template<typename BlenderSystemType> TCompositePropertyDefinitionBuilder< PropertyTraits, Composites... > & UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::SetBlenderSystem () inline
Definition at line 765 of file MovieScenePropertyComponentHandler.h.
References TCompositePropertyDefinitionBuilder(), and Definition.
SetBlenderSystem() [2/2]
template<typename PropertyTraits, typename... Composites> TCompositePropertyDefinitionBuilder< PropertyTraits, Composites... > & UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::SetBlenderSystem (UClass * BlenderSystemClass) inline
Definition at line 771 of file MovieScenePropertyComponentHandler.h.
References TCompositePropertyDefinitionBuilder(), and Definition.
SetCustomAccessors()
template<typename PropertyTraits, typename... Composites> template<int InlineSize> TCompositePropertyDefinitionBuilder< PropertyTraits, Composites... > & UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::SetCustomAccessors (TCustomPropertyRegistration< PropertyTraits, InlineSize > * InCustomAccessors) inline
Definition at line 758 of file MovieScenePropertyComponentHandler.h.
References TCompositePropertyDefinitionBuilder(), and Definition.
Field Documentation
Definition
template<typename PropertyTraits, typename... Composites> FPropertyDefinition* UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::Definition private
Definition at line 792 of file MovieScenePropertyComponentHandler.h.
Referenced by TCompositePropertyDefinitionBuilder(), AddComposite(), AddComposite(), Commit(), Commit(), SetBlenderSystem(), SetBlenderSystem(), and SetCustomAccessors().
Registry
template<typename PropertyTraits, typename... Composites> FPropertyRegistry* UE::MovieScene::TCompositePropertyDefinitionBuilder< PropertyTraits, Composites >::Registry private
Definition at line 793 of file MovieScenePropertyComponentHandler.h.
Referenced by TCompositePropertyDefinitionBuilder(), AddComposite(), and AddComposite().
The documentation for this struct was generated from the following file:
MovieScenePropertyComponentHandler.h