Unreal Engine 5.6 C++ API: UBasic2DLineSetComponent Class Reference
UBasic2DLineSetComponent Class Reference final
Instantiation of a basic line set component in 2D using FVector2f for line positions.
#include "BasicLineSetComponent.h"
Public Member Functions
void Clear ()
Clear all lines and component state.
Public Member Functions inherited from UBasicLineSetComponentBase
UBasicLineSetComponentBase ()
void ClearComponent ()
Clears the component state and marks component as dirty.
void SetColor (FColor InColor)
Set per line material Line Color parameter that is uniform for all lines.
void SetLineMaterial (UMaterialInterface *InLineMaterial)
Specify material that handles lines.
void SetLineSetParameters (FColor InColor, float InSize, float InDepthBias)
Set per line material parameters that are uniform for all lines.
void SetLineThickness (float InSize)
Set per line material Line Size/Thickness parameter that is uniform for all lines.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Public Member Functions inherited from TBasicElementSet< FVector2f, 2 >
void AddElement (Targs... ElementPoints)
Add a point to be rendered using the component.
void ClearElements ()
int32 NumElements () const
Current number of points.
FVector2f & operator[] (int32 Index)
void ReserveAdditionalElements (const int32 AdditionalNum)
Reserve enough memory for an additional number of points over the existing number already reserved.
void ReserveElements (const int32 MaxNum)
Reserve enough memory for up to the given maximum number of points.
Private Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Friends
class FBasicLineSetSceneProxy
Additional Inherited Members
Public Types inherited from TBasicElementSet< FVector2f, 2 >
using GeometryType
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Static Public Attributes inherited from TBasicElementSet< FVector2f, 2 >
static const int32 ElementSize
Protected Member Functions inherited from UBasicLineSetComponentBase
virtual int32 GetNumMaterials () const override
template<typename CalcLineBoxFn>
FBoxSphereBounds UpdateComponentBounds (const FTransform &LocalToWorld, bool bLinesDirty, CalcLineBoxFn &&CalcLineBox) const
Update component bounds using a provided function that determines the box around all line positions.
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Member Functions inherited from TBasicElementSet< FVector2f, 2 >
void AddElementInternal (const T &ElementPoint, Targs... ElementPoints)
FBox CalcElementsBox () const
Protected Attributes inherited from UBasicLineSetComponentBase
bool bBoundsDirty = true
FBoxSphereBounds Bounds
FColor Color
float DepthBias = 0.0f
TObjectPtr< const UMaterialInterface > LineMaterial
float Size = 1.0f
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Protected Attributes inherited from TBasicElementSet< FVector2f, 2 >
bool bElementsDirty
TArray< FVector2f > Elements
int32 Num
Detailed Description
Instantiation of a basic line set component in 2D using FVector2f for line positions.
Definition at line 109 of file BasicLineSetComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UBasic2DLineSetComponent::CalcBounds (const FTransform & LocalToWorld) const inline override private virtual
Definition at line 127 of file BasicLineSetComponent.h.
References TBasicElementSet< FVector2f, 2 >::bElementsDirty, TBasicElementSet< FVector2f, 2 >::CalcElementsBox(), and UBasicLineSetComponentBase::UpdateComponentBounds().
Clear()
void UBasic2DLineSetComponent::Clear () inline
Clear all lines and component state.
Definition at line 115 of file BasicLineSetComponent.h.
References Clear(), UBasicLineSetComponentBase::ClearComponent(), and TBasicElementSet< FVector2f, 2 >::ClearElements().
Referenced by Clear().
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UBasic2DLineSetComponent::CreateSceneProxy () override private virtual
Friends And Related Symbol Documentation
FBasicLineSetSceneProxy
friend class FBasicLineSetSceneProxy friend
Definition at line 133 of file BasicLineSetComponent.h.
References FBasicLineSetSceneProxy.
Referenced by FBasicLineSetSceneProxy.
Field Documentation
CURRENT_FILE_ID___LINE___GENERATED_BODY
UBasic2DLineSetComponent::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 111 of file BasicLineSetComponent.h.
The documentation for this class was generated from the following file:
BasicLineSetComponent.h