Unreal Engine 5.6 C++ API: FResourceBulkDataArrayView Struct Reference
FResourceBulkDataArrayView Struct Reference
Utility to do a simple upload of data from an array managed by the caller.
#include "ResourceArray.h"
Public Member Functions
FResourceBulkDataArrayView ()=delete
template<typename ElementType, typename AllocatorType>
FResourceBulkDataArrayView (const TArray< ElementType, AllocatorType > &InArray)
FResourceBulkDataArrayView (const void *InData, uint32 InSizeInBytes)
template<typename ElementType>
FResourceBulkDataArrayView (TConstArrayView< ElementType > View)
virtual void Discard () final
Free memory after it has been used to initialize RHI resource.
virtual const void * GetResourceBulkData () const final
virtual uint32 GetResourceBulkDataSize () const final
Public Member Functions inherited from FResourceBulkDataInterface
virtual ~FResourceBulkDataInterface ()
template<typename TElement>
TConstArrayView< TElement > GetBulkDataView () const
virtual EBulkDataType GetResourceType () const
Data Fields
const void *const Data
const uint32 SizeInBytes
Additional Inherited Members
Public Types inherited from FResourceBulkDataInterface
enum class EBulkDataType { Default , MediaTexture , VREyeBuffer }
Detailed Description
Utility to do a simple upload of data from an array managed by the caller.
Definition at line 145 of file ResourceArray.h.
Constructor & Destructor Documentation
FResourceBulkDataArrayView() [1/4]
FResourceBulkDataArrayView::FResourceBulkDataArrayView () delete
Referenced by FResourceBulkDataArrayView().
FResourceBulkDataArrayView() [2/4]
FResourceBulkDataArrayView::FResourceBulkDataArrayView (const void * InData, uint32 InSizeInBytes) inline explicit nodiscard
Definition at line 152 of file ResourceArray.h.
References Data, and SizeInBytes.
FResourceBulkDataArrayView() [3/4]
template<typename ElementType> FResourceBulkDataArrayView::FResourceBulkDataArrayView (TConstArrayView< ElementType > View) inline explicit nodiscard
Definition at line 159 of file ResourceArray.h.
References Data, GetData(), Num, and SizeInBytes.
FResourceBulkDataArrayView() [4/4]
template<typename ElementType, typename AllocatorType> FResourceBulkDataArrayView::FResourceBulkDataArrayView (const TArray< ElementType, AllocatorType > & InArray) inline explicit nodiscard
Definition at line 166 of file ResourceArray.h.
References FResourceBulkDataArrayView(), and MakeArrayView().
Member Function Documentation
Discard()
virtual void FResourceBulkDataArrayView::Discard () inline final virtual
Free memory after it has been used to initialize RHI resource.
Implements FResourceBulkDataInterface.
Definition at line 182 of file ResourceArray.h.
GetResourceBulkData()
virtual const void * FResourceBulkDataArrayView::GetResourceBulkData () const inline nodiscard final virtual
Returns
ptr to the resource memory which has been preallocated
Implements FResourceBulkDataInterface.
Definition at line 172 of file ResourceArray.h.
References Data.
GetResourceBulkDataSize()
virtual uint32 FResourceBulkDataArrayView::GetResourceBulkDataSize () const inline nodiscard final virtual
Returns
size of resource memory
Implements FResourceBulkDataInterface.
Definition at line 177 of file ResourceArray.h.
References SizeInBytes.
Field Documentation
Data
const void* const FResourceBulkDataArrayView::Data
Definition at line 147 of file ResourceArray.h.
Referenced by FResourceBulkDataArrayView(), FResourceBulkDataArrayView(), and GetResourceBulkData().
SizeInBytes
const uint32 FResourceBulkDataArrayView::SizeInBytes
Definition at line 148 of file ResourceArray.h.
Referenced by FResourceBulkDataArrayView(), FResourceBulkDataArrayView(), and GetResourceBulkDataSize().
The documentation for this struct was generated from the following file:
ResourceArray.h