Unreal Engine 5.6 C++ API: FNetworkPredictionPhysicsState Struct Reference
FNetworkPredictionPhysicsState Struct Reference
#include "NetworkPredictionPhysics.h"
Public Member Functions
bool ContainsNaN () const
Static Public Member Functions
static NETWORKPREDICTION_API void BeginInterpolation (UPrimitiveComponent *Driver)
static NETWORKPREDICTION_API void EndInterpolation (UPrimitiveComponent *Driver)
static NETWORKPREDICTION_API void FinalizeInterpolatedPhysics (UPrimitiveComponent *Driver, FNetworkPredictionPhysicsState *InterpolatedState)
static void Interpolate (const FNetworkPredictionPhysicsState *From, const FNetworkPredictionPhysicsState *To, const float PCT, FNetworkPredictionPhysicsState *Out)
static void MarshalPhysicsToComponent (UPrimitiveComponent *PrimitiveComponent, const FBodyInstance *BodyInstance)
static void NetRecv (const FNetSerializeParams &P, FNetworkPredictionPhysicsState *RecvState)
static NETWORKPREDICTION_API void NetSend (const FNetSerializeParams &P, FBodyInstance *BodyInstance)
static NETWORKPREDICTION_API void PerformRollback (FBodyInstance *BodyInstance, FNetworkPredictionPhysicsState *RecvState)
static void PerformRollback (UPrimitiveComponent *PrimitiveComponent, FNetworkPredictionPhysicsState *RecvState)
static void PostResimulate (UPrimitiveComponent *PrimitiveComponent, const FBodyInstance *BodyInstance)
static NETWORKPREDICTION_API bool ShouldReconcile (int32 PhysicsFrame, Chaos::FRewindData *RewindData, FBodyInstance *BodyInstance, FNetworkPredictionPhysicsState *RecvState)
static bool StateIsConsistent (UPrimitiveComponent *PrimitiveComponent, FBodyInstance *BodyInstance)
static void ToString (const FNetworkPredictionPhysicsState *RecvState, FAnsiStringBuilderBase &Builder)
static NETWORKPREDICTION_API void ToString (FBodyInstance *BodyInstance, FAnsiStringBuilderBase &Builder)
static NETWORKPREDICTION_API void ToString (int32 PhysicsFrame, Chaos::FRewindData *RewindData, FBodyInstance *BodyInstance, FAnsiStringBuilderBase &Builder)
Data Fields
Chaos::FVec3 AngularVelocity
Chaos::FVec3 LinearVelocity
Chaos::FVec3 Location
Chaos::FRotation3 Rotation
Static Private Member Functions
static void ToStringInternal (const Chaos::FVec3 &Location, const Chaos::FRotation3 &Rotation, const Chaos::FVec3 &LinearVelocity, const Chaos::FVec3 &AngularVelocity, FAnsiStringBuilderBase &Builder)
Detailed Description
Definition at line 30 of file NetworkPredictionPhysics.h.
Member Function Documentation
BeginInterpolation()
NETWORKPREDICTION_API void FNetworkPredictionPhysicsState::BeginInterpolation (UPrimitiveComponent * Driver) static
References UE_API.
ContainsNaN()
bool FNetworkPredictionPhysicsState::ContainsNaN () const inline
Definition at line 140 of file NetworkPredictionPhysics.h.
References AngularVelocity, LinearVelocity, Location, and Rotation.
Referenced by Interpolate(), and NetRecv().
EndInterpolation()
NETWORKPREDICTION_API void FNetworkPredictionPhysicsState::EndInterpolation (UPrimitiveComponent * Driver) static
References UE_API.
FinalizeInterpolatedPhysics()
NETWORKPREDICTION_API void FNetworkPredictionPhysicsState::FinalizeInterpolatedPhysics (UPrimitiveComponent * Driver, FNetworkPredictionPhysicsState * InterpolatedState) static
References UE_API.
Interpolate()
void FNetworkPredictionPhysicsState::Interpolate (const FNetworkPredictionPhysicsState * From, const FNetworkPredictionPhysicsState * To, const float PCT, FNetworkPredictionPhysicsState * Out) inline static
Definition at line 65 of file NetworkPredictionPhysics.h.
References AngularVelocity, ContainsNaN(), UE::Math::TQuat< double >::FastLerp(), FMath::Lerp(), LinearVelocity, Location, npCheckSlow, npEnsureMsgfSlow, Rotation, and TEXT.
MarshalPhysicsToComponent()
void FNetworkPredictionPhysicsState::MarshalPhysicsToComponent (UPrimitiveComponent * PrimitiveComponent, const FBodyInstance * BodyInstance) inline static
Definition at line 97 of file NetworkPredictionPhysics.h.
References FVector, UE::Math::TTransform< T >::GetLocation(), UE::Math::TTransform< T >::GetRotation(), and MOVECOMP_SkipPhysicsMove.
Referenced by PerformRollback(), and PostResimulate().
NetRecv()
void FNetworkPredictionPhysicsState::NetRecv (const FNetSerializeParams & P, FNetworkPredictionPhysicsState * RecvState) inline static
Definition at line 40 of file NetworkPredictionPhysics.h.
References AngularVelocity, FNetSerializeParams::Ar, ContainsNaN(), NetworkPredictionPhysicsCvars::FullPrecision(), LinearVelocity, Location, npCheckSlow, npEnsureSlow, Rotation, and SerializePackedVector().
NetSend()
NETWORKPREDICTION_API void FNetworkPredictionPhysicsState::NetSend (const FNetSerializeParams & P, FBodyInstance * BodyInstance) static
References UE_API.
PerformRollback() [1/2]
NETWORKPREDICTION_API void FNetworkPredictionPhysicsState::PerformRollback (FBodyInstance * BodyInstance, FNetworkPredictionPhysicsState * RecvState) static
References UE_API.
PerformRollback() [2/2]
void FNetworkPredictionPhysicsState::PerformRollback (UPrimitiveComponent * PrimitiveComponent, FNetworkPredictionPhysicsState * RecvState) inline static
Definition at line 83 of file NetworkPredictionPhysics.h.
References MarshalPhysicsToComponent(), npCheckSlow, and PerformRollback().
Referenced by PerformRollback().
PostResimulate()
void FNetworkPredictionPhysicsState::PostResimulate (UPrimitiveComponent * PrimitiveComponent, const FBodyInstance * BodyInstance) inline static
Definition at line 104 of file NetworkPredictionPhysics.h.
References MarshalPhysicsToComponent().
ShouldReconcile()
NETWORKPREDICTION_API bool FNetworkPredictionPhysicsState::ShouldReconcile (int32 PhysicsFrame, Chaos::FRewindData * RewindData, FBodyInstance * BodyInstance, FNetworkPredictionPhysicsState * RecvState) static
References UE_API.
StateIsConsistent()
bool FNetworkPredictionPhysicsState::StateIsConsistent (UPrimitiveComponent * PrimitiveComponent, FBodyInstance * BodyInstance) inline static
Definition at line 117 of file NetworkPredictionPhysics.h.
References UE::Math::TTransform< T >::EqualsNoScale().
ToString() [1/3]
void FNetworkPredictionPhysicsState::ToString (const FNetworkPredictionPhysicsState * RecvState, FAnsiStringBuilderBase & Builder) inline static
Definition at line 129 of file NetworkPredictionPhysics.h.
References AngularVelocity, LinearVelocity, Location, Rotation, and ToStringInternal().
ToString() [2/3]
NETWORKPREDICTION_API void FNetworkPredictionPhysicsState::ToString (FBodyInstance * BodyInstance, FAnsiStringBuilderBase & Builder) static
References UE_API.
ToString() [3/3]
NETWORKPREDICTION_API void FNetworkPredictionPhysicsState::ToString (int32 PhysicsFrame, Chaos::FRewindData * RewindData, FBodyInstance * BodyInstance, FAnsiStringBuilderBase & Builder) static
References UE_API.
ToStringInternal()
void FNetworkPredictionPhysicsState::ToStringInternal (const Chaos::FVec3 & Location, const Chaos::FRotation3 & Rotation, const Chaos::FVec3 & LinearVelocity, const Chaos::FVec3 & AngularVelocity, FAnsiStringBuilderBase & Builder) inline static private
Definition at line 147 of file NetworkPredictionPhysics.h.
References AngularVelocity, TStringBuilderBase< CharType >::Appendf(), LinearVelocity, Location, and Rotation.
Referenced by ToString().
Field Documentation
AngularVelocity
Chaos::FVec3 FNetworkPredictionPhysicsState::AngularVelocity
Definition at line 35 of file NetworkPredictionPhysics.h.
Referenced by ContainsNaN(), Interpolate(), NetRecv(), ToString(), and ToStringInternal().
LinearVelocity
Chaos::FVec3 FNetworkPredictionPhysicsState::LinearVelocity
Definition at line 34 of file NetworkPredictionPhysics.h.
Referenced by ContainsNaN(), Interpolate(), NetRecv(), ToString(), and ToStringInternal().
Location
Chaos::FVec3 FNetworkPredictionPhysicsState::Location
Definition at line 32 of file NetworkPredictionPhysics.h.
Referenced by ContainsNaN(), Interpolate(), NetRecv(), ToString(), and ToStringInternal().
Rotation
Chaos::FRotation3 FNetworkPredictionPhysicsState::Rotation
Definition at line 33 of file NetworkPredictionPhysics.h.
Referenced by ContainsNaN(), Interpolate(), NetRecv(), ToString(), and ToStringInternal().
The documentation for this struct was generated from the following file:
NetworkPredictionPhysics.h