Unreal Engine 5.6 C++ API: TScriptBitArray< Allocator, InDerivedType > Class Template Reference
TScriptBitArray< Allocator, InDerivedType > Class Template Reference
#include "BitArray.h"
Public Member Functions
TScriptBitArray ()
Minimal initialization constructor.
TScriptBitArray (const TScriptBitArray &)
int32 Add (const bool Value)
void Empty (int32 Slack=0)
bool IsValidIndex (int32 Index) const
void MoveAssign (DerivedType &Other)
void operator= (const TScriptBitArray &)
FBitReference operator[] (int32 Index)
FConstBitReference operator[] (int32 Index) const
Private Types
typedef Allocator::template ForElementType< uint32 > AllocatorType
using DerivedType = std::conditional_t<std::is_void_v<InDerivedType>, TScriptBitArray, InDerivedType>
Private Member Functions
FORCEINLINE uint32 * GetData ()
FORCEINLINE const uint32 * GetData () const
FORCENOINLINE void Realloc (int32 PreviousNumBits)
FORCENOINLINE void ReallocGrow (int32 PreviousNumBits)
Static Private Member Functions
static void CheckConstraints ()
Private Attributes
AllocatorType AllocatorInstance
int32 MaxBits
int32 NumBits
Detailed Description
template<typename Allocator, typename InDerivedType>
class TScriptBitArray< Allocator, InDerivedType >
Definition at line 2187 of file BitArray.h.
Member Typedef Documentation
AllocatorType
template<typename Allocator, typename InDerivedType> typedef Allocator::template ForElementType<uint32> TScriptBitArray< Allocator, InDerivedType >::AllocatorType private
Definition at line 2260 of file BitArray.h.
DerivedType
template<typename Allocator, typename InDerivedType> using TScriptBitArray< Allocator, InDerivedType >::DerivedType = std::conditional_t<std::is_void_v<InDerivedType>, TScriptBitArray, InDerivedType> private
Definition at line 2189 of file BitArray.h.
Constructor & Destructor Documentation
TScriptBitArray() [1/2]
template<typename Allocator, typename InDerivedType> TScriptBitArray< Allocator, InDerivedType >::TScriptBitArray () inline nodiscard
Minimal initialization constructor.
Parameters
Value - The value to initial the bits to.
InNumBits - The initial number of bits in the array.
Definition at line 2197 of file BitArray.h.
TScriptBitArray() [2/2]
template<typename Allocator, typename InDerivedType> TScriptBitArray< Allocator, InDerivedType >::TScriptBitArray (const TScriptBitArray< Allocator, InDerivedType > &) inline nodiscard
Definition at line 2335 of file BitArray.h.
Member Function Documentation
Add()
template<typename Allocator, typename InDerivedType> int32 TScriptBitArray< Allocator, InDerivedType >::Add (const bool Value) inline
Definition at line 2242 of file BitArray.h.
CheckConstraints()
template<typename Allocator, typename InDerivedType> void TScriptBitArray< Allocator, InDerivedType >::CheckConstraints () inline static private
Definition at line 2267 of file BitArray.h.
Empty()
template<typename Allocator, typename InDerivedType> void TScriptBitArray< Allocator, InDerivedType >::Empty (int32 Slack = 0) inline
Definition at line 2229 of file BitArray.h.
GetData() [1/2]
template<typename Allocator, typename InDerivedType> FORCEINLINE uint32 * TScriptBitArray< Allocator, InDerivedType >::GetData () inline nodiscard private
Definition at line 2287 of file BitArray.h.
Referenced by TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Add(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::operator[](), and TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::operator[]().
GetData() [2/2]
template<typename Allocator, typename InDerivedType> FORCEINLINE const uint32 * TScriptBitArray< Allocator, InDerivedType >::GetData () const inline nodiscard private
Definition at line 2292 of file BitArray.h.
IsValidIndex()
template<typename Allocator, typename InDerivedType> bool TScriptBitArray< Allocator, InDerivedType >::IsValidIndex (int32 Index) const inline nodiscard
Definition at line 2203 of file BitArray.h.
Referenced by TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::operator[](), and TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::operator[]().
MoveAssign()
template<typename Allocator, typename InDerivedType> void TScriptBitArray< Allocator, InDerivedType >::MoveAssign (DerivedType & Other) inline
Definition at line 2220 of file BitArray.h.
operator=()
template<typename Allocator, typename InDerivedType> void TScriptBitArray< Allocator, InDerivedType >::operator= (const TScriptBitArray< Allocator, InDerivedType > &) inline
Definition at line 2336 of file BitArray.h.
operator[]() [1/2]
template<typename Allocator, typename InDerivedType> FBitReference TScriptBitArray< Allocator, InDerivedType >::operator[] (int32 Index) inline nodiscard
Definition at line 2208 of file BitArray.h.
operator[]() [2/2]
template<typename Allocator, typename InDerivedType> FConstBitReference TScriptBitArray< Allocator, InDerivedType >::operator[] (int32 Index) const inline nodiscard
Definition at line 2214 of file BitArray.h.
Realloc()
template<typename Allocator, typename InDerivedType> FORCENOINLINE void TScriptBitArray< Allocator, InDerivedType >::Realloc (int32 PreviousNumBits) inline private
Definition at line 2297 of file BitArray.h.
Referenced by TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Empty().
ReallocGrow()
template<typename Allocator, typename InDerivedType> FORCENOINLINE void TScriptBitArray< Allocator, InDerivedType >::ReallocGrow (int32 PreviousNumBits) inline private
Definition at line 2314 of file BitArray.h.
Referenced by TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Add().
Field Documentation
AllocatorInstance
template<typename Allocator, typename InDerivedType> AllocatorType TScriptBitArray< Allocator, InDerivedType >::AllocatorInstance private
Definition at line 2262 of file BitArray.h.
MaxBits
template<typename Allocator, typename InDerivedType> int32 TScriptBitArray< Allocator, InDerivedType >::MaxBits private
Definition at line 2264 of file BitArray.h.
NumBits
template<typename Allocator, typename InDerivedType> int32 TScriptBitArray< Allocator, InDerivedType >::NumBits private
Definition at line 2263 of file BitArray.h.
The documentation for this class was generated from the following file:
BitArray.h