Unreal Engine 5.6 C++ API: MaterialInstance_Private Namespace Reference
MaterialInstance_Private Namespace Reference
Functions
template<typename ExpressionType>
void FindClosestExpressionByGUIDRecursive (const FName &InName, const FGuid &InGUID, TConstArrayView< TObjectPtr< UMaterialExpression > > InMaterialExpression, ExpressionType *&OutExpression)
Workaround - Similar to base call but evaluates all expressions found, not just the first.
template<typename ParameterType, typename ExpressionType>
bool UpdateParameter_FullTraversal (ParameterType &Parameter, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet_FullTraversal (TArray< ParameterType > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet_WithCachedData (EMaterialParameterType ParamTypeEnum, TArray< ParameterType > &Parameters, UMaterial *ParentMaterial)
Function Documentation
FindClosestExpressionByGUIDRecursive()
template<typename ExpressionType> void MaterialInstance_Private::FindClosestExpressionByGUIDRecursive (const FName & InName, const FGuid & InGUID, TConstArrayView< TObjectPtr< UMaterialExpression > > InMaterialExpression, ExpressionType *& OutExpression)
Workaround - Similar to base call but evaluates all expressions found, not just the first.
Definition at line 18 of file MaterialInstanceUpdateParameterSet.h.
References Cast(), check, FindClosestExpressionByGUIDRecursive(), and InName.
Referenced by FindClosestExpressionByGUIDRecursive(), and UpdateParameterSet_FullTraversal().
UpdateParameter_FullTraversal()
template<typename ParameterType, typename ExpressionType> bool MaterialInstance_Private::UpdateParameter_FullTraversal (ParameterType & Parameter, UMaterial * ParentMaterial)
Definition at line 75 of file MaterialInstanceUpdateParameterSet.h.
References Cast(), and CastChecked().
Referenced by UpdateParameterSet_FullTraversal(), and UpdateParameterSet_WithCachedData().
UpdateParameterSet_FullTraversal()
template<typename ParameterType, typename ExpressionType> bool MaterialInstance_Private::UpdateParameterSet_FullTraversal (TArray< ParameterType > & Parameters, UMaterial * ParentMaterial)
Definition at line 121 of file MaterialInstanceUpdateParameterSet.h.
References FindClosestExpressionByGUIDRecursive(), GIsEditor, FApp::IsGame(), TArray< InElementType, InAllocatorType >::Num(), and UpdateParameter_FullTraversal().
Referenced by UpdateParameterSet().
UpdateParameterSet_WithCachedData()
template<typename ParameterType, typename ExpressionType> bool MaterialInstance_Private::UpdateParameterSet_WithCachedData (EMaterialParameterType ParamTypeEnum, TArray< ParameterType > & Parameters, UMaterial * ParentMaterial)
Definition at line 166 of file MaterialInstanceUpdateParameterSet.h.
References check, GIsEditor, INDEX_NONE, FApp::IsGame(), TArray< InElementType, InAllocatorType >::Num(), and UpdateParameter_FullTraversal().
Referenced by UpdateParameterSet(), UpdateParameterSet(), UpdateParameterSet(), UpdateParameterSet(), UpdateParameterSet(), UpdateParameterSet(), UpdateParameterSet(), UpdateParameterSet(), UpdateParameterSet(), and UpdateParameterSet().