Unreal Engine 5.6 C++ API: ModularVehicleDebug.h File Reference
ModularVehicleDebug.h File Reference
#include "Containers/StringConv.h"
#include "HAL/FileManager.h"
Functions
static bool WriteCustomReport (FString FileName, TArray< FString > &FileLines)
static bool WriteNetReport (bool IsServer, const FString &FileLine)
Function Documentation
WriteCustomReport()
bool WriteCustomReport (FString FileName, TArray< FString > & FileLines) static
Definition at line 9 of file ModularVehicleDebug.h.
References FArchive::Close(), IFileManager::CreateFileWriter(), FILEWRITE_Append, FILEWRITE_NoReplaceExisting, IFileManager::Get(), LINE_TERMINATOR, TArray< InElementType, InAllocatorType >::Num(), FArchive::Serialize(), TCHAR_TO_ANSI, and TEXT.
Referenced by WriteNetReport().
WriteNetReport()
bool WriteNetReport (bool IsServer, const FString & FileLine) static
Definition at line 44 of file ModularVehicleDebug.h.
References TArray< InElementType, InAllocatorType >::Add(), and WriteCustomReport().