Unreal Engine 5.6 C++ API: UE::Geometry::FEdgeConstraint Struct Reference
UE::Geometry::FEdgeConstraint Struct Reference
FEdgeConstraint is a constraint on a triangle mesh edge.
#include "MeshConstraints.h"
Public Member Functions
FEdgeConstraint ()
FEdgeConstraint (EEdgeRefineFlags ConstraintFlags)
FEdgeConstraint (EEdgeRefineFlags ConstraintFlags, IProjectionTarget *TargetIn)
bool CanCollapse () const
bool CanFlip () const
bool CanSplit () const
bool IsUnconstrained () const
bool NoModifications () const
Static Public Member Functions
static bool CanCollapse (const EEdgeRefineFlags Flags)
static bool CanFlip (const EEdgeRefineFlags Flags)
static bool CanSplit (const EEdgeRefineFlags Flags)
static FEdgeConstraint FullyConstrained ()
static FEdgeConstraint NoFlips ()
static bool NoModifications (const EEdgeRefineFlags Flags)
static FEdgeConstraint SplitsOnly ()
static FEdgeConstraint Unconstrained ()
Data Fields
EEdgeRefineFlags RefineFlags
Constraint flags on this edge.
IProjectionTarget * Target
Edge is associated with this projection target.
int TrackingSetID
This ID is not a constraint, but can be used to find descendants of a constrained input edge after splits.
Detailed Description
FEdgeConstraint is a constraint on a triangle mesh edge.
Definition at line 42 of file MeshConstraints.h.
Constructor & Destructor Documentation
FEdgeConstraint() [1/3]
UE::Geometry::FEdgeConstraint::FEdgeConstraint () inline
Definition at line 53 of file MeshConstraints.h.
References UE::Geometry::NoConstraint, RefineFlags, Target, and TrackingSetID.
Referenced by FullyConstrained(), NoFlips(), SplitsOnly(), and Unconstrained().
FEdgeConstraint() [2/3]
UE::Geometry::FEdgeConstraint::FEdgeConstraint (EEdgeRefineFlags ConstraintFlags) inline explicit
Definition at line 60 of file MeshConstraints.h.
References RefineFlags, Target, and TrackingSetID.
FEdgeConstraint() [3/3]
UE::Geometry::FEdgeConstraint::FEdgeConstraint (EEdgeRefineFlags ConstraintFlags, IProjectionTarget * TargetIn) inline explicit
Definition at line 67 of file MeshConstraints.h.
References RefineFlags, Target, and TrackingSetID.
Member Function Documentation
CanCollapse() [1/2]
bool UE::Geometry::FEdgeConstraint::CanCollapse () const inline
Returns
true if edge can be collapsed
Definition at line 87 of file MeshConstraints.h.
References CanCollapse(), and RefineFlags.
Referenced by CanCollapse().
CanCollapse() [2/2]
bool UE::Geometry::FEdgeConstraint::CanCollapse (const EEdgeRefineFlags Flags) inline static
Returns
true if flags permit collapsed
Definition at line 129 of file MeshConstraints.h.
References Flags, and UE::Geometry::NoCollapse.
CanFlip() [1/2]
bool UE::Geometry::FEdgeConstraint::CanFlip () const inline
Returns
true if edge can be flipped
Definition at line 75 of file MeshConstraints.h.
References UE::Geometry::NoFlip, and RefineFlags.
CanFlip() [2/2]
bool UE::Geometry::FEdgeConstraint::CanFlip (const EEdgeRefineFlags Flags) inline static
Returns
true if flags permit flip
Definition at line 117 of file MeshConstraints.h.
References Flags, and UE::Geometry::NoFlip.
CanSplit() [1/2]
bool UE::Geometry::FEdgeConstraint::CanSplit () const inline
Returns
true if edge can be split
Definition at line 81 of file MeshConstraints.h.
References CanSplit(), and RefineFlags.
Referenced by CanSplit().
CanSplit() [2/2]
bool UE::Geometry::FEdgeConstraint::CanSplit (const EEdgeRefineFlags Flags) inline static
Returns
true if flags permit split
Definition at line 123 of file MeshConstraints.h.
References Flags, and UE::Geometry::NoSplit.
FullyConstrained()
FEdgeConstraint UE::Geometry::FEdgeConstraint::FullyConstrained () inline static
Returns
a fully constrained edge constraint
Definition at line 114 of file MeshConstraints.h.
References FEdgeConstraint(), and UE::Geometry::FullyConstrained.
Referenced by UE::Geometry::FMeshConstraintsUtil::ConstrainSeams(), UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges(), and UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges().
IsUnconstrained()
bool UE::Geometry::FEdgeConstraint::IsUnconstrained () const inline
Returns
true if edge is unconstrained
Definition at line 99 of file MeshConstraints.h.
References UE::Geometry::NoConstraint, RefineFlags, and Target.
NoFlips()
FEdgeConstraint UE::Geometry::FEdgeConstraint::NoFlips () inline static
Returns
a no-flip edge constraint
Definition at line 108 of file MeshConstraints.h.
References FEdgeConstraint(), and UE::Geometry::NoFlip.
NoModifications() [1/2]
bool UE::Geometry::FEdgeConstraint::NoModifications () const inline
Returns
true if edge cannot be modified at all
Definition at line 93 of file MeshConstraints.h.
References NoModifications(), and RefineFlags.
Referenced by NoModifications().
NoModifications() [2/2]
bool UE::Geometry::FEdgeConstraint::NoModifications (const EEdgeRefineFlags Flags) inline static
Returns
true if flags permit no edge modification
Definition at line 135 of file MeshConstraints.h.
References Flags, and UE::Geometry::FullyConstrained.
SplitsOnly()
FEdgeConstraint UE::Geometry::FEdgeConstraint::SplitsOnly () inline static
Returns
a splits-only edge constraint
Definition at line 111 of file MeshConstraints.h.
References FEdgeConstraint(), and UE::Geometry::SplitsOnly.
Unconstrained()
FEdgeConstraint UE::Geometry::FEdgeConstraint::Unconstrained () inline static
Returns
an unconstrained edge constraint (ie not constrained at all)
Definition at line 105 of file MeshConstraints.h.
References FEdgeConstraint(), and UE::Geometry::NoConstraint.
Referenced by UE::Geometry::FMeshConstraints::GetEdgeConstraint().
Field Documentation
RefineFlags
EEdgeRefineFlags UE::Geometry::FEdgeConstraint::RefineFlags
Constraint flags on this edge.
Definition at line 46 of file MeshConstraints.h.
Referenced by FEdgeConstraint(), FEdgeConstraint(), FEdgeConstraint(), CanCollapse(), CanFlip(), CanSplit(), IsUnconstrained(), and NoModifications().
Target
IProjectionTarget* UE::Geometry::FEdgeConstraint::Target
Edge is associated with this projection target.
Definition at line 48 of file MeshConstraints.h.
Referenced by FEdgeConstraint(), FEdgeConstraint(), FEdgeConstraint(), and IsUnconstrained().
TrackingSetID
int UE::Geometry::FEdgeConstraint::TrackingSetID
This ID is not a constraint, but can be used to find descendants of a constrained input edge after splits.
Definition at line 51 of file MeshConstraints.h.
Referenced by FEdgeConstraint(), FEdgeConstraint(), and FEdgeConstraint().
The documentation for this struct was generated from the following file:
MeshConstraints.h