Unreal Engine 5.6 C++ API: UParticleModuleLocation Class Reference
UParticleModuleLocation Class Reference
#include "ParticleModuleLocation.h"
Public Member Functions
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void Render3DPreview (const FPreviewContext &Context) override
virtual void Spawn (const FSpawnContext &Context) override
Protected Member Functions
virtual void SpawnEx (const FSpawnContext &Context, struct FRandomStream *InRandomStream)
Extended version of spawn, allows for using a random stream for distribution value retrieval.
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() struct FRawDistributionVector StartLocation
The location the particle should be emitted.
void InitializeDefaults ()
Initializes the default values for this property.
UPROPERTY () float DistributeOverNPoints
When set to a non-zero value this will force the particles to only spawn on evenly distributed positions between the two points specified.
UPROPERTY () float DistributeThreshold
When DistributeOverNPoints is set to a non-zero value, this specifies the ratio of particles spawned that should use the distribution.
Detailed Description
Definition at line 15 of file ParticleModuleLocation.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UParticleModuleLocation::GENERATED_UCLASS_BODY () private
The location the particle should be emitted.
Relative in local space to the emitter by default. Relative in world space as a WorldOffset module or when the emitter's UseLocalSpace is off. Retrieved using the EmitterTime at the spawn of the particle.
References Category, Location, and UPROPERTY().
InitializeDefaults()
void UParticleModuleLocation::InitializeDefaults () private
Initializes the default values for this property.
References InitializeDefaults().
Referenced by InitializeDefaults().
PostEditChangeProperty()
virtual void UParticleModuleLocation::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void UParticleModuleLocation::PostInitProperties () override virtual
Render3DPreview()
virtual void UParticleModuleLocation::Render3DPreview (const FPreviewContext & Context) override virtual
Spawn()
virtual void UParticleModuleLocation::Spawn (const FSpawnContext & Context) override virtual
SpawnEx()
virtual void UParticleModuleLocation::SpawnEx (const FSpawnContext & Context, struct FRandomStream * InRandomStream) protected virtual
Extended version of spawn, allows for using a random stream for distribution value retrieval.
Parameters
Owner The particle emitter instance that is spawning
Offset The offset to the modules payload data
SpawnTime The time of the spawn
InRandomStream The random stream to use for retrieving random values
References SpawnEx().
Referenced by SpawnEx().
UPROPERTY() [1/2]
UParticleModuleLocation::UPROPERTY () private
When set to a non-zero value this will force the particles to only spawn on evenly distributed positions between the two points specified.
References Category, Location, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UParticleModuleLocation_Seeded::GENERATED_UCLASS_BODY(), UParticleModuleLocationWorldOffset_Seeded::GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/2]
UParticleModuleLocation::UPROPERTY () private
When DistributeOverNPoints is set to a non-zero value, this specifies the ratio of particles spawned that should use the distribution.
(For example setting this to 1 will cause all the particles to be distributed evenly whereas .75 would cause 1/4 of the particles to be randomly placed).
References Category, Location, and UPROPERTY().
The documentation for this class was generated from the following file:
ParticleModuleLocation.h