Unreal Engine 5.6 C++ API: UE::ParkingLot Namespace Reference
UE::ParkingLot Namespace Reference
ParkingLot is a global table of queues of waiting threads keyed by memory address.
Namespaces
namespace Private
Data Structures
struct FWaitState
struct FWakeState
Functions
template<typename CanWaitType, typename BeforeWaitType>
FWaitState Wait (const void *Address, CanWaitType &&CanWait, BeforeWaitType &&BeforeWait)
Queue the calling thread to wait if CanWait returns true.
template<typename CanWaitType, typename BeforeWaitType>
FWaitState WaitFor (const void *Address, CanWaitType &&CanWait, BeforeWaitType &&BeforeWait, FMonotonicTimeSpan WaitTime)
Queue the calling thread to wait if CanWait returns true.
template<typename CanWaitType, typename BeforeWaitType>
FWaitState WaitUntil (const void *Address, CanWaitType &&CanWait, BeforeWaitType &&BeforeWait, FMonotonicTimePoint WaitTime)
Queue the calling thread to wait if CanWait returns true.
uint32 WakeAll (const void *Address)
Wake all threads from the queue of threads waiting on the address.
uint32 WakeMultiple (const void *Address, uint32 WakeCount)
Wake up to WakeCount threads from the queue of threads waiting on the address.
FWakeState WakeOne (const void *Address)
Wake one thread from the queue of threads waiting on the address.
template<typename OnWakeStateType>
void WakeOne (const void *Address, OnWakeStateType &&OnWakeState)
Wake one thread from the queue of threads waiting on the address.
Detailed Description
ParkingLot is a global table of queues of waiting threads keyed by memory address.
Function Documentation
Wait()
template<typename CanWaitType, typename BeforeWaitType> FWaitState UE::ParkingLot::Wait (const void * Address, CanWaitType && CanWait, BeforeWaitType && BeforeWait) inline
Queue the calling thread to wait if CanWait returns true.
BeforeWait is only called if CanWait returns true.
Parameters
Address Address to use as the key for the queue. The same address is used to wake the thread.
CanWait Function called while the queue is locked. A return of false cancels the wait.
BeforeWait Function called after the queue is unlocked and before the thread waits.
Definition at line 51 of file ParkingLot.h.
References Forward(), and UE::ParkingLot::Private::Wait().
Referenced by UE::FConditionVariable::Wait(), and UE::TEventCount< uint32 >::Wait().
WaitFor()
template<typename CanWaitType, typename BeforeWaitType> FWaitState UE::ParkingLot::WaitFor (const void * Address, CanWaitType && CanWait, BeforeWaitType && BeforeWait, FMonotonicTimeSpan WaitTime) inline
Queue the calling thread to wait if CanWait returns true.
BeforeWait is only called if CanWait returns true.
Parameters
Address Address to use as the key for the queue. The same address is used to wake the thread.
CanWait Function called while the queue is locked. A return of false cancels the wait.
BeforeWait Function called after the queue is unlocked and before the thread waits.
WaitTime Relative time after which waiting is automatically canceled and the thread wakes.
Definition at line 65 of file ParkingLot.h.
References Forward(), and UE::ParkingLot::Private::WaitFor().
Referenced by UE::TEventCount< uint32 >::WaitFor().
WaitUntil()
template<typename CanWaitType, typename BeforeWaitType> FWaitState UE::ParkingLot::WaitUntil (const void * Address, CanWaitType && CanWait, BeforeWaitType && BeforeWait, FMonotonicTimePoint WaitTime) inline
Queue the calling thread to wait if CanWait returns true.
BeforeWait is only called if CanWait returns true.
Parameters
Address Address to use as the key for the queue. The same address is used to wake the thread.
CanWait Function called while the queue is locked. A return of false cancels the wait.
BeforeWait Function called after the queue is unlocked and before the thread waits.
WaitTime Absolute time after which waiting is automatically canceled and the thread wakes.
Definition at line 79 of file ParkingLot.h.
References Forward(), and UE::ParkingLot::Private::WaitUntil().
Referenced by UE::FManualResetEvent::WaitUntil(), and UE::TEventCount< uint32 >::WaitUntil().
WakeAll()
uint32 UE::ParkingLot::WakeAll (const void * Address)
Wake all threads from the queue of threads waiting on the address.
Parameters
Address Address to use as the key for the queue. Must match the address used in Wait.
Returns
The number of threads that this call woke up.
References UE_API.
Referenced by UE::FManualResetEvent::Notify(), UE::TEventCount< uint32 >::Notify(), and UE::FConditionVariable::NotifyAll().
WakeMultiple()
uint32 UE::ParkingLot::WakeMultiple (const void * Address, uint32 WakeCount)
Wake up to WakeCount threads from the queue of threads waiting on the address.
Parameters
Address Address to use as the key for the queue. Must match the address used in Wait.
WakeCount The maximum number of threads to wake.
Returns
The number of threads that this call woke up.
References UE_API.
WakeOne() [1/2]
FWakeState UE::ParkingLot::WakeOne (const void * Address)
Wake one thread from the queue of threads waiting on the address.
Parameters
Address Address to use as the key for the queue. Must match the address used in Wait.
Returns
The wake state, which includes whether a thread woke up and whether there are more queued.
References UE_API.
WakeOne() [2/2]
template<typename OnWakeStateType> void UE::ParkingLot::WakeOne (const void * Address, OnWakeStateType && OnWakeState) inline
Wake one thread from the queue of threads waiting on the address.
Parameters
Address Address to use as the key for the queue. Must match the address used in Wait.
OnWakeState Function called while the queue is locked. Receives the wake state. Returns WakeToken.
Definition at line 91 of file ParkingLot.h.
References Forward(), and UE::ParkingLot::Private::WakeOne().
Referenced by UE::FConditionVariable::NotifyOne().