Unreal Engine 5.6 C++ API: SSegmentedControl< OptionType >::FSlot Struct Reference
SSegmentedControl< OptionType >::FSlot Struct Reference
Stores the per-child info for this panel type.
#include "SSegmentedControl.h"
Public Member Functions
FSlot (const OptionType &InValue)
const FSlateBrush * GetIcon () const
FText GetText () const
FText GetToolTip () const
if (InArgs._Icon.IsSet())
if (InArgs._Text.IsSet())
if (InArgs._ToolTip.IsSet())
if (InArgs._ToolTipWidget.IsSet())
if (InArgs._Value.IsSet())
void SetIcon (TAttribute< const FSlateBrush * > InBrush)
void SetText (TAttribute< FText > InText)
void SetToolTip (TAttribute< FText > InTooltip)
Text ToolTipWidget SLATE_ATTRIBUTE (const FSlateBrush *, Icon) SLATE_ARGUMENT(TOptional< OptionType >
Text SLATE_ATTRIBUTE (FText, ToolTip) SLATE_ATTRIBUTE(TSharedPtr< IToolTip >
SLATE_SLOT_BEGIN_ARGS_OneMixin (FSlot, TSlotBase< FSlot >, TAlignmentWidgetSlotMixin< FSlot >) SLATE_ATTRIBUTE(FText
Text ToolTipWidget Value SLATE_SLOT_END_ARGS () void Construct(const FChildren &SlotOwner
TAlignmentWidgetSlotMixin (SlotOwner, MoveTemp(InArgs))
Public Member Functions inherited from TSlotBase< FSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlot & Expose (FSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Public Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
TAlignmentWidgetSlotMixin ()
EHorizontalAlignment GetHorizontalAlignment () const
EVerticalAlignment GetVerticalAlignment () const
void SetHorizontalAlignment (EHorizontalAlignment Alignment)
void SetVerticalAlignment (EVerticalAlignment Alignment)
Data Fields
Text ToolTipWidget Value FSlotArguments && InArgs
friend SSegmentedControl< OptionType >
Private Attributes
TWeakPtr< SCheckBox > _CheckBox
TAttribute< const FSlateBrush * > _Icon
TAttribute< FText > _Text
TAttribute< FText > _Tooltip
TAttribute< TSharedPtr< IToolTip > > _ToolTipWidget
OptionType _Value
Additional Inherited Members
Public Types inherited from TSlotBase< FSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Protected Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Detailed Description
template<typename OptionType>
struct SSegmentedControl< OptionType >::FSlot
Stores the per-child info for this panel type.
Definition at line 33 of file SSegmentedControl.h.
Constructor & Destructor Documentation
FSlot()
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::FSlot (const OptionType & InValue) inline
Definition at line 35 of file SSegmentedControl.h.
References FSlot(), _Icon, _Text, _Tooltip, _Value, and TAlignmentWidgetSlotMixin().
Referenced by FSlot(), and SLATE_SLOT_BEGIN_ARGS_OneMixin().
Member Function Documentation
GetIcon()
template<typename OptionType> const FSlateBrush * SSegmentedControl< OptionType >::FSlot::GetIcon () const inline
Definition at line 93 of file SSegmentedControl.h.
References _Icon.
GetText()
template<typename OptionType> FText SSegmentedControl< OptionType >::FSlot::GetText () const inline
Definition at line 83 of file SSegmentedControl.h.
References _Text.
GetToolTip()
template<typename OptionType> FText SSegmentedControl< OptionType >::FSlot::GetToolTip () const inline
Definition at line 103 of file SSegmentedControl.h.
References _Tooltip.
if() [1/5]
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::if (InArgs._Icon. IsSet()) inline
Definition at line 68 of file SSegmentedControl.h.
References _Icon, InArgs, and MoveTemp().
if() [2/5]
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::if (InArgs._Text. IsSet()) inline
Definition at line 56 of file SSegmentedControl.h.
References _Text, InArgs, and MoveTemp().
if() [3/5]
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::if (InArgs._ToolTip. IsSet()) inline
Definition at line 60 of file SSegmentedControl.h.
References _Tooltip, InArgs, and MoveTemp().
if() [4/5]
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::if (InArgs._ToolTipWidget. IsSet()) inline
Definition at line 64 of file SSegmentedControl.h.
References _ToolTipWidget, InArgs, and MoveTemp().
if() [5/5]
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::if (InArgs._Value. IsSet()) inline
Definition at line 72 of file SSegmentedControl.h.
References _Value, InArgs, and MoveTemp().
SetIcon()
template<typename OptionType> void SSegmentedControl< OptionType >::FSlot::SetIcon (TAttribute< const FSlateBrush * > InBrush) inline
Definition at line 88 of file SSegmentedControl.h.
References _Icon, and MoveTemp().
SetText()
template<typename OptionType> void SSegmentedControl< OptionType >::FSlot::SetText (TAttribute< FText > InText) inline
Definition at line 78 of file SSegmentedControl.h.
References _Text, and MoveTemp().
SetToolTip()
template<typename OptionType> void SSegmentedControl< OptionType >::FSlot::SetToolTip (TAttribute< FText > InTooltip) inline
Definition at line 98 of file SSegmentedControl.h.
References _Tooltip, and MoveTemp().
SLATE_ATTRIBUTE() [1/2]
template<typename OptionType> Text ToolTipWidget SSegmentedControl< OptionType >::FSlot::SLATE_ATTRIBUTE (const FSlateBrush * , Icon)
References Icon, SSegmentedControl< OptionType >::SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and Value.
SLATE_ATTRIBUTE() [2/2]
template<typename OptionType> Text SSegmentedControl< OptionType >::FSlot::SLATE_ATTRIBUTE (FText , ToolTip)
References SLATE_ATTRIBUTE(), and ToolTip.
Referenced by SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_SLOT_BEGIN_ARGS_OneMixin()
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::SLATE_SLOT_BEGIN_ARGS_OneMixin (FSlot , TSlotBase< FSlot > , TAlignmentWidgetSlotMixin< FSlot >)
References FSlot(), TAlignmentWidgetSlotMixin(), and Text.
SLATE_SLOT_END_ARGS()
template<typename OptionType> Text ToolTipWidget Value SSegmentedControl< OptionType >::FSlot::SLATE_SLOT_END_ARGS () const &
References SLATE_SLOT_END_ARGS().
Referenced by SLATE_SLOT_END_ARGS().
TAlignmentWidgetSlotMixin()
template<typename OptionType> SSegmentedControl< OptionType >::FSlot::TAlignmentWidgetSlotMixin (SlotOwner , MoveTemp(InArgs))
References InArgs.
Referenced by FSlot(), and SLATE_SLOT_BEGIN_ARGS_OneMixin().
Field Documentation
_CheckBox
template<typename OptionType> TWeakPtr<SCheckBox> SSegmentedControl< OptionType >::FSlot::_CheckBox private
Definition at line 117 of file SSegmentedControl.h.
Referenced by SSegmentedControl< OptionType >::RebuildChildren().
_Icon
template<typename OptionType> TAttribute<const FSlateBrush*> SSegmentedControl< OptionType >::FSlot::_Icon private
Definition at line 114 of file SSegmentedControl.h.
Referenced by FSlot(), GetIcon(), if(), SSegmentedControl< OptionType >::RebuildChildren(), and SetIcon().
_Text
template<typename OptionType> TAttribute<FText> SSegmentedControl< OptionType >::FSlot::_Text private
Definition at line 111 of file SSegmentedControl.h.
Referenced by FSlot(), GetText(), if(), SSegmentedControl< OptionType >::RebuildChildren(), and SetText().
_Tooltip
template<typename OptionType> TAttribute<FText> SSegmentedControl< OptionType >::FSlot::_Tooltip private
Definition at line 112 of file SSegmentedControl.h.
Referenced by FSlot(), GetToolTip(), if(), SSegmentedControl< OptionType >::RebuildChildren(), and SetToolTip().
_ToolTipWidget
template<typename OptionType> TAttribute<TSharedPtr<IToolTip> > SSegmentedControl< OptionType >::FSlot::_ToolTipWidget private
Definition at line 113 of file SSegmentedControl.h.
Referenced by if(), and SSegmentedControl< OptionType >::RebuildChildren().
_Value
template<typename OptionType> OptionType SSegmentedControl< OptionType >::FSlot::_Value private
Definition at line 116 of file SSegmentedControl.h.
Referenced by FSlot(), if(), and SSegmentedControl< OptionType >::RebuildChildren().
InArgs
template<typename OptionType> Text ToolTipWidget Value FSlotArguments&& SSegmentedControl< OptionType >::FSlot::InArgs
Initial value:
{
            TSlotBase<FSlot>::Construct(SlotOwner, MoveTemp(InArgs))
Definition at line 52 of file SSegmentedControl.h.
Referenced by if(), if(), if(), if(), if(), and TAlignmentWidgetSlotMixin().
SSegmentedControl< OptionType >
template<typename OptionType> friend SSegmentedControl< OptionType >::FSlot::SSegmentedControl< OptionType >
Definition at line 108 of file SSegmentedControl.h.
The documentation for this struct was generated from the following file:
SSegmentedControl.h