Unreal Engine 5.6 C++ API: FRenderThreadCommandPipe::FCommand Struct Reference
FRenderThreadCommandPipe::FCommand Struct Reference
Public Member Functions
FCommand (const TCHAR *InName, uint32 &OutSpecId, TStatId InStatId, TUniqueFunction< void(FRHICommandListImmediate &)> &&InFunction)
Public Member Functions inherited from UE::FInheritedContextBase
void CaptureInheritedContext ()
FInheritedContextScope RestoreInheritedContext ()
Data Fields
TUniqueFunction< void(FRHICommandListImmediate &)> Function
const TCHAR * Name
uint32 * SpecId
TStatId StatId
Detailed Description
Definition at line 355 of file RenderingThread.h.
Constructor & Destructor Documentation
FCommand()
FRenderThreadCommandPipe::FCommand::FCommand (const TCHAR * InName, uint32 & OutSpecId, TStatId InStatId, TUniqueFunction< void(FRHICommandListImmediate &)> && InFunction) inline
Definition at line 357 of file RenderingThread.h.
References UE::FInheritedContextBase::CaptureInheritedContext(), Function, InName, MoveTemp(), Name, SpecId, and StatId.
Field Documentation
Function
TUniqueFunction<void(FRHICommandListImmediate&)> FRenderThreadCommandPipe::FCommand::Function
Definition at line 369 of file RenderingThread.h.
Referenced by FCommand().
Name
const TCHAR* FRenderThreadCommandPipe::FCommand::Name
Definition at line 366 of file RenderingThread.h.
Referenced by FCommand().
SpecId
uint32* FRenderThreadCommandPipe::FCommand::SpecId
Definition at line 367 of file RenderingThread.h.
Referenced by FCommand().
StatId
TStatId FRenderThreadCommandPipe::FCommand::StatId
Definition at line 368 of file RenderingThread.h.
Referenced by FCommand().
The documentation for this struct was generated from the following file:
RenderingThread.h