Unreal Engine 5.6 C++ API: FUECompressedAnimData Struct Reference
FUECompressedAnimData Struct Reference
#include "AnimCompressionTypes.h"
Public Member Functions
FUECompressedAnimData ()=default
FUECompressedAnimData (FUECompressedAnimDataMutable &InCompressedData)
virtual void Bind (const TArrayView< uint8 > BulkData) override
template<typename TArchive>
void ByteSwapData (TArrayView< uint8 > CompresedData, TArchive &MemoryStream)
void ByteSwapIn (TArrayView< uint8 > CompressedData, FMemoryReader &MemoryStream)
void ByteSwapOut (TArrayView< uint8 > CompressedData, FMemoryWriter &MemoryStream)
virtual int64 GetApproxCompressedSize () const override
virtual FString GetDebugString () const override
void InitViewsFromBuffer (const TArrayView< uint8 > BulkData)
virtual bool IsValid () const override
virtual void SerializeCompressedData (class FArchive &Ar) override
Public Member Functions inherited from ICompressedAnimData
ICompressedAnimData ()=default
ICompressedAnimData (const ICompressedAnimData &)
virtual ~ICompressedAnimData ()
ICompressedAnimData & operator= (const ICompressedAnimData &)
virtual void SerializeCompressedData (UObject *DataOwner, class FArchive &Ar)
UE_DEPRECATED (5.5, "SerializeCompressedData now accepts the DataOwner as an argument") 1 virtual void SerializeCompressedData(class FArchive &Ar)
Public Member Functions inherited from FCompressedAnimDataBase< TNonConstArrayViewMaker >
FCompressedAnimDataBase (FCompressedAnimDataBase< OtherContainerMaker > &InCompressedData)
Additional Inherited Members
Data Fields inherited from ICompressedAnimData
int32 CompressedNumberOfKeys
Data Fields inherited from FCompressedAnimDataBase< TNonConstArrayViewMaker >
TNonConstArrayViewMaker< uint8 >::Type CompressedByteStream
FCompressedOffsetDataBase< typename TNonConstArrayViewMaker< int32 >::Type > CompressedScaleOffsets
An array of 2*NumTrack ints, arranged as follows: if identity, it is offset if not, it is num of keys [0] Scale0.Offset or NumKeys [1] Scale1.Offset or NumKeys.
TNonConstArrayViewMaker< int32 >::Type CompressedTrackOffsets
An array of 4*NumTrack ints, arranged as follows: - PerTrack is 2*NumTrack, so this isn't true any more [0] Trans0.Offset [1] Trans0.NumKeys [2] Rot0.Offset [3] Rot0.NumKeys [4] Trans1.Offset
enum AnimationKeyFormat KeyEncodingFormat
class AnimEncoding * RotationCodec
AnimationCompressionFormat RotationCompressionFormat
class AnimEncoding * ScaleCodec
AnimationCompressionFormat ScaleCompressionFormat
class AnimEncoding * TranslationCodec
The runtime interface to decode and byte swap the compressed animation May be NULL.
AnimationCompressionFormat TranslationCompressionFormat
The compression format that was used to compress tracks parts.
Detailed Description
Definition at line 504 of file AnimCompressionTypes.h.
Constructor & Destructor Documentation
FUECompressedAnimData() [1/2]
FUECompressedAnimData::FUECompressedAnimData () default
FUECompressedAnimData() [2/2]
FUECompressedAnimData::FUECompressedAnimData (FUECompressedAnimDataMutable & InCompressedData) inline explicit
Definition at line 508 of file AnimCompressionTypes.h.
References FCompressedAnimDataBase< TNonConstArrayViewMaker >::FCompressedAnimDataBase(), and ICompressedAnimData::ICompressedAnimData().
Member Function Documentation
Bind()
virtual void FUECompressedAnimData::Bind (const TArrayView< uint8 > BulkData) inline override virtual
Implements ICompressedAnimData.
Definition at line 523 of file AnimCompressionTypes.h.
References BulkData, and InitViewsFromBuffer().
ByteSwapData()
template<typename TArchive> void FUECompressedAnimData::ByteSwapData (TArrayView< uint8 > CompresedData, TArchive & MemoryStream)
Referenced by ByteSwapIn(), and ByteSwapOut().
ByteSwapIn()
void FUECompressedAnimData::ByteSwapIn (TArrayView< uint8 > CompressedData, FMemoryReader & MemoryStream) inline
Definition at line 518 of file AnimCompressionTypes.h.
References ByteSwapData(), and CompressedData.
ByteSwapOut()
void FUECompressedAnimData::ByteSwapOut (TArrayView< uint8 > CompressedData, FMemoryWriter & MemoryStream) inline
Definition at line 519 of file AnimCompressionTypes.h.
References ByteSwapData(), and CompressedData.
GetApproxCompressedSize()
virtual int64 FUECompressedAnimData::GetApproxCompressedSize () const inline override virtual
Implements ICompressedAnimData.
Definition at line 525 of file AnimCompressionTypes.h.
References FCompressedAnimDataBase< TNonConstArrayViewMaker >::CompressedByteStream, FCompressedAnimDataBase< TNonConstArrayViewMaker >::CompressedScaleOffsets, and FCompressedAnimDataBase< TNonConstArrayViewMaker >::CompressedTrackOffsets.
GetDebugString()
virtual FString FUECompressedAnimData::GetDebugString () const override virtual
Reimplemented from ICompressedAnimData.
InitViewsFromBuffer()
void FUECompressedAnimData::InitViewsFromBuffer (const TArrayView< uint8 > BulkData)
References BulkData.
Referenced by Bind().
IsValid()
virtual bool FUECompressedAnimData::IsValid () const inline override virtual
Implements ICompressedAnimData.
Definition at line 527 of file AnimCompressionTypes.h.
References FCompressedAnimDataBase< TNonConstArrayViewMaker >::CompressedByteStream, FCompressedAnimDataBase< TNonConstArrayViewMaker >::RotationCompressionFormat, FCompressedAnimDataBase< TNonConstArrayViewMaker >::ScaleCompressionFormat, and FCompressedAnimDataBase< TNonConstArrayViewMaker >::TranslationCompressionFormat.
SerializeCompressedData()
virtual void FUECompressedAnimData::SerializeCompressedData (class FArchive & Ar) override virtual
References Ar.
The documentation for this struct was generated from the following file:
AnimCompressionTypes.h