Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicGraph Class Reference
UE::Geometry::FDynamicGraph Class Reference
#include "DynamicGraph.h"
Data Structures
struct FEdge
struct FEdgeCollapseInfo
struct FEdgeSplitInfo
Public Types
typedef FRefCountVector::IndexEnumerable edge_iterator
template<typename T>
using value_iteration = FRefCountVector::MappedEnumerable<T>
typedef FRefCountVector::IndexEnumerable vertex_iterator
Public Member Functions
FDynamicGraph ()
virtual ~FDynamicGraph ()
int AllocateEdgeGroup ()
int AppendEdge (const FEdge &E)
int AppendEdge (const FIndex2i &ev, int GID=-1)
int AppendEdge (int v0, int v1, int GID=-1)
virtual bool CheckValidity (EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check) const
This function checks that the graph is well-formed, ie all internal data structures are consistent.
EMeshResult CollapseEdge (int VKeep, int VRemove, FEdgeCollapseInfo &Collapse)
int EdgeCount () const
edge_iterator EdgeIndices () const
value_iteration< FEdge > Edges () const
Enumerate edges.
int FindEdge (int VA, int VB) const
FEdge GetEdge (int EID) const
int GetEdgeGroup (int EID) const
FIndex2i GetEdgeV (int EID) const
int GetMaxVtxEdgeCount () const
int GetVtxEdgeCount (int VID) const
bool IsBoundaryVertex (int VID) const
bool IsCompact () const
bool IsCompactV () const
bool IsEdge (int EID) const
bool IsJunctionVertex (int VID) const
bool IsRegularVertex (int VID) const
bool IsVertex (int VID) const
int MaxEdgeID () const
int MaxGroupID () const
int MaxVertexID () const
EMeshResult RemoveEdge (int EID, bool bRemoveIsolatedVertices)
EMeshResult RemoveVertex (int VID, bool bRemoveIsolatedVertices)
void SetEdgeGroup (int EID, int GroupID)
int ShapeTimestamp () const
EMeshResult SplitEdge (int EAB, FEdgeSplitInfo &Split)
EMeshResult SplitEdge (int VA, int VB, FEdgeSplitInfo &Split)
EMeshResult SplitEdgeWithExistingVertex (int EAB, int ExistingMidVert, FEdgeSplitInfo &Split)
int Timestamp () const
int VertexCount () const
vertex_iterator VertexIndices () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int VID) const
Enumerate edge ids connected to vertex (i.e.
FSmallListSet::MappedValueEnumerable VtxVerticesItr (int VID) const
Enumerate "other" vertices of edges connected to vertex (i.e.
Static Public Member Functions
static FEdge InvalidEdge3 ()
static FIndex2i InvalidEdgeV ()
Static Public Attributes
static constexpr int DuplicateEdgeID = -2
static constexpr int InvalidID = IndexConstants::InvalidID
Protected Member Functions
int add_edge (int A, int B, int GID)
virtual int append_new_split_vertex (int A, int B)
int append_vertex_internal ()
void debug_check_is_edge (int E) const
void debug_check_is_vertex (int V) const
bool edge_has_v (int EID, int VID) const
int edge_other_v (int EID, int VID) const
bool insert_vertex_internal (int32 Vid)
int replace_edge_vertex (int EID, int VOld, int VNew)
virtual void subclass_validity_checks (TFunction< void(bool)> CheckOrFailF) const
void updateTimeStamp (bool bShapeChange)
Protected Attributes
TDynamicVector< FEdge > edges
FRefCountVector edges_refcount
int max_group_id = 0
int shape_timestamp = 0
int timestamp = 0
FSmallListSet vertex_edges
FRefCountVector vertices_refcount
Private Member Functions
void allocate_edges_list (int VID)
Detailed Description
Definition at line 24 of file DynamicGraph.h.
Member Typedef Documentation
edge_iterator
typedef FRefCountVector::IndexEnumerable UE::Geometry::FDynamicGraph::edge_iterator
Definition at line 280 of file DynamicGraph.h.
value_iteration
template<typename T> using UE::Geometry::FDynamicGraph::value_iteration = FRefCountVector::MappedEnumerable<T>
Definition at line 287 of file DynamicGraph.h.
vertex_iterator
typedef FRefCountVector::IndexEnumerable UE::Geometry::FDynamicGraph::vertex_iterator
Definition at line 274 of file DynamicGraph.h.
Constructor & Destructor Documentation
FDynamicGraph()
UE::Geometry::FDynamicGraph::FDynamicGraph () inline
Definition at line 58 of file DynamicGraph.h.
References max_group_id.
~FDynamicGraph()
virtual UE::Geometry::FDynamicGraph::~FDynamicGraph () inline virtual
Definition at line 63 of file DynamicGraph.h.
Member Function Documentation
add_edge()
int UE::Geometry::FDynamicGraph::add_edge (int A, int B, int GID) inline protected
Definition at line 251 of file DynamicGraph.h.
References A, B, edges, edges_refcount, and vertex_edges.
Referenced by AppendEdge(), SplitEdge(), and SplitEdgeWithExistingVertex().
allocate_edges_list()
void UE::Geometry::FDynamicGraph::allocate_edges_list (int VID) inline private
Definition at line 204 of file DynamicGraph.h.
References vertex_edges.
Referenced by append_vertex_internal(), and insert_vertex_internal().
AllocateEdgeGroup()
int UE::Geometry::FDynamicGraph::AllocateEdgeGroup () inline
Definition at line 173 of file DynamicGraph.h.
References max_group_id.
append_new_split_vertex()
virtual int UE::Geometry::FDynamicGraph::append_new_split_vertex (int A, int B) inline protected virtual
Reimplemented in UE::Geometry::FDynamicGraph2< T >, UE::Geometry::FDynamicGraph2< double >, UE::Geometry::FDynamicGraph3< T >, UE::Geometry::FDynamicGraph3< double >, and UE::Geometry::FDynamicGraphN.
Definition at line 471 of file DynamicGraph.h.
References A, B, InvalidID, and unimplemented.
Referenced by SplitEdge().
append_vertex_internal()
int UE::Geometry::FDynamicGraph::append_vertex_internal () inline protected
Definition at line 184 of file DynamicGraph.h.
References allocate_edges_list(), updateTimeStamp(), and vertices_refcount.
Referenced by UE::Geometry::FDynamicGraph2< double >::AppendVertex(), UE::Geometry::FDynamicGraph3< double >::AppendVertex(), and UE::Geometry::FDynamicGraphN::AppendVertex().
AppendEdge() [1/3]
int UE::Geometry::FDynamicGraph::AppendEdge (const FEdge & E) inline
Definition at line 214 of file DynamicGraph.h.
References UE::Geometry::FDynamicGraph::FEdge::A, AppendEdge(), UE::Geometry::FDynamicGraph::FEdge::B, and UE::Geometry::FDynamicGraph::FEdge::Group.
Referenced by AppendEdge(), and AppendEdge().
AppendEdge() [2/3]
int UE::Geometry::FDynamicGraph::AppendEdge (const FIndex2i & ev, int GID = -1) inline
Definition at line 218 of file DynamicGraph.h.
References AppendEdge().
AppendEdge() [3/3]
int UE::Geometry::FDynamicGraph::AppendEdge (int v0, int v1, int GID = -1) inline
Definition at line 222 of file DynamicGraph.h.
References add_edge(), check, DuplicateEdgeID, FindEdge(), InvalidID, IsVertex(), FMath::Max, max_group_id, updateTimeStamp(), and vertices_refcount.
CheckValidity()
virtual bool UE::Geometry::FDynamicGraph::CheckValidity (EValidityCheckFailMode FailMode = EValidityCheckFailMode::Check) const inline virtual
This function checks that the graph is well-formed, ie all internal data structures are consistent.
Definition at line 613 of file DynamicGraph.h.
References UE::Geometry::Check, checkf, edge_has_v(), edge_other_v(), EdgeIndices(), edges_refcount, UE::Geometry::Ensure, ensureMsgf, FindEdge(), GetEdgeV(), InvalidID, IsEdge(), IsVertex(), subclass_validity_checks(), TEXT, vertex_edges, VertexCount(), VertexIndices(), and vertices_refcount.
CollapseEdge()
EMeshResult UE::Geometry::FDynamicGraph::CollapseEdge (int VKeep, int VRemove, FEdgeCollapseInfo & Collapse) inline
Definition at line 486 of file DynamicGraph.h.
References A, B, check, UE::Geometry::FDynamicGraph::FEdgeCollapseInfo::ECollapsed, edge_other_v(), edges_refcount, UE::Geometry::Failed_NotAnEdge, FindEdge(), InvalidID, IsVertex(), UE::Geometry::Ok, RemoveEdge(), replace_edge_vertex(), updateTimeStamp(), vertex_edges, vertices_refcount, UE::Geometry::FDynamicGraph::FEdgeCollapseInfo::VKept, and UE::Geometry::FDynamicGraph::FEdgeCollapseInfo::VRemoved.
debug_check_is_edge()
void UE::Geometry::FDynamicGraph::debug_check_is_edge (int E) const inline protected
Definition at line 699 of file DynamicGraph.h.
References check, and IsEdge().
debug_check_is_vertex()
void UE::Geometry::FDynamicGraph::debug_check_is_vertex (int V) const inline protected
Definition at line 694 of file DynamicGraph.h.
References check, and IsVertex().
edge_has_v()
bool UE::Geometry::FDynamicGraph::edge_has_v (int EID, int VID) const inline protected
Definition at line 555 of file DynamicGraph.h.
References A, and edges.
Referenced by CheckValidity().
edge_other_v()
int UE::Geometry::FDynamicGraph::edge_other_v (int EID, int VID) const inline protected
Definition at line 559 of file DynamicGraph.h.
References edges, and InvalidID.
Referenced by CheckValidity(), CollapseEdge(), UE::Geometry::FDynamicGraph2< double >::OpeningAngle(), UE::Geometry::FDynamicGraph2< double >::SortedVtxEdges(), and VtxVerticesItr().
EdgeCount()
int UE::Geometry::FDynamicGraph::EdgeCount () const inline
Definition at line 91 of file DynamicGraph.h.
References edges_refcount.
EdgeIndices()
edge_iterator UE::Geometry::FDynamicGraph::EdgeIndices () const inline
Definition at line 281 of file DynamicGraph.h.
References edges_refcount.
Referenced by CheckValidity().
Edges()
value_iteration< FEdge > UE::Geometry::FDynamicGraph::Edges () const inline
Enumerate edges.
Definition at line 292 of file DynamicGraph.h.
References edges, and edges_refcount.
FindEdge()
int UE::Geometry::FDynamicGraph::FindEdge (int VA, int VB) const inline
Definition at line 299 of file DynamicGraph.h.
References B, edges, InvalidID, FMath::Max, FMath::Min, and vertex_edges.
Referenced by AppendEdge(), CheckValidity(), CollapseEdge(), SplitEdge(), and SplitEdgeWithExistingVertex().
GetEdge()
FEdge UE::Geometry::FDynamicGraph::GetEdge (int EID) const inline
Definition at line 178 of file DynamicGraph.h.
References edges, edges_refcount, and InvalidEdge3().
GetEdgeGroup()
int UE::Geometry::FDynamicGraph::GetEdgeGroup (int EID) const inline
Definition at line 157 of file DynamicGraph.h.
References edges, and edges_refcount.
GetEdgeV()
FIndex2i UE::Geometry::FDynamicGraph::GetEdgeV (int EID) const inline
Definition at line 152 of file DynamicGraph.h.
References A, B, edges, edges_refcount, and InvalidEdgeV().
Referenced by CheckValidity().
GetMaxVtxEdgeCount()
int UE::Geometry::FDynamicGraph::GetMaxVtxEdgeCount () const inline
Definition at line 142 of file DynamicGraph.h.
References FMath::Max, vertex_edges, and vertices_refcount.
GetVtxEdgeCount()
int UE::Geometry::FDynamicGraph::GetVtxEdgeCount (int VID) const inline
Definition at line 137 of file DynamicGraph.h.
References vertex_edges, and vertices_refcount.
insert_vertex_internal()
bool UE::Geometry::FDynamicGraph::insert_vertex_internal (int32 Vid) inline protected
Definition at line 192 of file DynamicGraph.h.
References allocate_edges_list(), updateTimeStamp(), and vertices_refcount.
Referenced by UE::Geometry::FDynamicGraph3< double >::InsertVertex().
InvalidEdge3()
FEdge UE::Geometry::FDynamicGraph::InvalidEdge3 () inline static
Definition at line 39 of file DynamicGraph.h.
References InvalidID.
Referenced by GetEdge().
InvalidEdgeV()
FIndex2i UE::Geometry::FDynamicGraph::InvalidEdgeV () inline static
Definition at line 35 of file DynamicGraph.h.
References InvalidID.
Referenced by GetEdgeV().
IsBoundaryVertex()
bool UE::Geometry::FDynamicGraph::IsBoundaryVertex (int VID) const inline
Definition at line 593 of file DynamicGraph.h.
References vertex_edges, and vertices_refcount.
IsCompact()
bool UE::Geometry::FDynamicGraph::IsCompact () const inline
Definition at line 584 of file DynamicGraph.h.
References edges_refcount, and vertices_refcount.
IsCompactV()
bool UE::Geometry::FDynamicGraph::IsCompactV () const inline
Definition at line 588 of file DynamicGraph.h.
References vertices_refcount.
IsEdge()
bool UE::Geometry::FDynamicGraph::IsEdge (int EID) const inline
Definition at line 114 of file DynamicGraph.h.
References edges_refcount.
Referenced by CheckValidity(), debug_check_is_edge(), SplitEdge(), and SplitEdgeWithExistingVertex().
IsJunctionVertex()
bool UE::Geometry::FDynamicGraph::IsJunctionVertex (int VID) const inline
Definition at line 598 of file DynamicGraph.h.
References vertex_edges, and vertices_refcount.
IsRegularVertex()
bool UE::Geometry::FDynamicGraph::IsRegularVertex (int VID) const inline
Definition at line 603 of file DynamicGraph.h.
References vertex_edges, and vertices_refcount.
IsVertex()
bool UE::Geometry::FDynamicGraph::IsVertex (int VID) const inline
Definition at line 110 of file DynamicGraph.h.
References vertices_refcount.
Referenced by AppendEdge(), CheckValidity(), CollapseEdge(), debug_check_is_vertex(), and SplitEdgeWithExistingVertex().
MaxEdgeID()
int UE::Geometry::FDynamicGraph::MaxEdgeID () const inline
Definition at line 101 of file DynamicGraph.h.
References edges_refcount.
MaxGroupID()
int UE::Geometry::FDynamicGraph::MaxGroupID () const inline
Definition at line 105 of file DynamicGraph.h.
References max_group_id.
MaxVertexID()
int UE::Geometry::FDynamicGraph::MaxVertexID () const inline
Definition at line 97 of file DynamicGraph.h.
References vertices_refcount.
RemoveEdge()
EMeshResult UE::Geometry::FDynamicGraph::RemoveEdge (int EID, bool bRemoveIsolatedVertices) inline
Definition at line 313 of file DynamicGraph.h.
References A, UE::Geometry::FIndex2i::A, B, UE::Geometry::FIndex2i::B, check, edges, edges_refcount, UE::Geometry::Failed_NotAnEdge, UE::Geometry::Ok, updateTimeStamp(), vertex_edges, and vertices_refcount.
Referenced by CollapseEdge(), RemoveVertex(), and SplitEdgeWithExistingVertex().
RemoveVertex()
EMeshResult UE::Geometry::FDynamicGraph::RemoveVertex (int VID, bool bRemoveIsolatedVertices) inline
Definition at line 345 of file DynamicGraph.h.
References UE::Geometry::Ok, RemoveEdge(), and VtxEdgesItr().
replace_edge_vertex()
int UE::Geometry::FDynamicGraph::replace_edge_vertex (int EID, int VOld, int VNew) inline protected
Definition at line 564 of file DynamicGraph.h.
References A, B, edges, FMath::Max, and FMath::Min.
Referenced by CollapseEdge(), SplitEdge(), and SplitEdgeWithExistingVertex().
SetEdgeGroup()
void UE::Geometry::FDynamicGraph::SetEdgeGroup (int EID, int GroupID) inline
Definition at line 162 of file DynamicGraph.h.
References check, edges, edges_refcount, FMath::Max, max_group_id, and updateTimeStamp().
ShapeTimestamp()
int UE::Geometry::FDynamicGraph::ShapeTimestamp () const inline
Definition at line 82 of file DynamicGraph.h.
References shape_timestamp.
SplitEdge() [1/2]
EMeshResult UE::Geometry::FDynamicGraph::SplitEdge (int EAB, FEdgeSplitInfo & Split) inline
Definition at line 370 of file DynamicGraph.h.
References A, add_edge(), append_new_split_vertex(), B, edges, UE::Geometry::FDynamicGraph::FEdgeSplitInfo::ENewBN, UE::Geometry::Failed_NotAnEdge, IsEdge(), UE::Geometry::Ok, replace_edge_vertex(), updateTimeStamp(), vertex_edges, vertices_refcount, and UE::Geometry::FDynamicGraph::FEdgeSplitInfo::VNew.
SplitEdge() [2/2]
EMeshResult UE::Geometry::FDynamicGraph::SplitEdge (int VA, int VB, FEdgeSplitInfo & Split) inline
Definition at line 361 of file DynamicGraph.h.
References UE::Geometry::Failed_NotAnEdge, FindEdge(), InvalidID, and SplitEdge().
Referenced by SplitEdge().
SplitEdgeWithExistingVertex()
EMeshResult UE::Geometry::FDynamicGraph::SplitEdgeWithExistingVertex (int EAB, int ExistingMidVert, FEdgeSplitInfo & Split) inline
Definition at line 402 of file DynamicGraph.h.
References A, add_edge(), B, edges, UE::Geometry::FDynamicGraph::FEdgeSplitInfo::ENewBN, UE::Geometry::Failed_NotAnEdge, UE::Geometry::Failed_NotAVertex, FindEdge(), InvalidID, IsEdge(), IsVertex(), UE::Geometry::Ok, RemoveEdge(), replace_edge_vertex(), updateTimeStamp(), vertex_edges, vertices_refcount, and UE::Geometry::FDynamicGraph::FEdgeSplitInfo::VNew.
subclass_validity_checks()
virtual void UE::Geometry::FDynamicGraph::subclass_validity_checks (TFunction< void(bool)> CheckOrFailF) const inline protected virtual
Reimplemented in UE::Geometry::FDynamicGraph2< T >, UE::Geometry::FDynamicGraph2< double >, UE::Geometry::FDynamicGraph3< T >, and UE::Geometry::FDynamicGraph3< double >.
Definition at line 690 of file DynamicGraph.h.
Referenced by CheckValidity().
Timestamp()
int UE::Geometry::FDynamicGraph::Timestamp () const inline
Definition at line 78 of file DynamicGraph.h.
References timestamp.
Referenced by UE::Geometry::FDynamicGraph2< double >::CachedBounds().
updateTimeStamp()
void UE::Geometry::FDynamicGraph::updateTimeStamp (bool bShapeChange) inline protected
Definition at line 68 of file DynamicGraph.h.
References shape_timestamp, and timestamp.
Referenced by append_vertex_internal(), AppendEdge(), CollapseEdge(), insert_vertex_internal(), RemoveEdge(), SetEdgeGroup(), UE::Geometry::FDynamicGraph2< double >::SetVertex(), UE::Geometry::FDynamicGraph3< double >::SetVertex(), SplitEdge(), and SplitEdgeWithExistingVertex().
VertexCount()
int UE::Geometry::FDynamicGraph::VertexCount () const inline
Definition at line 87 of file DynamicGraph.h.
References vertices_refcount.
Referenced by CheckValidity().
VertexIndices()
vertex_iterator UE::Geometry::FDynamicGraph::VertexIndices () const inline
Definition at line 275 of file DynamicGraph.h.
References vertices_refcount.
Referenced by CheckValidity(), UE::Geometry::FDynamicGraph2< double >::subclass_validity_checks(), and UE::Geometry::FDynamicGraph3< double >::subclass_validity_checks().
VtxEdgesItr()
FSmallListSet::ValueEnumerable UE::Geometry::FDynamicGraph::VtxEdgesItr (int VID) const inline
Enumerate edge ids connected to vertex (i.e.
edge one-ring)
Definition at line 131 of file DynamicGraph.h.
References check, vertex_edges, and vertices_refcount.
Referenced by RemoveVertex().
VtxVerticesItr()
FSmallListSet::MappedValueEnumerable UE::Geometry::FDynamicGraph::VtxVerticesItr (int VID) const inline
Enumerate "other" vertices of edges connected to vertex (i.e.
vertex one-ring)
Definition at line 122 of file DynamicGraph.h.
References check, edge_other_v(), vertex_edges, and vertices_refcount.
Field Documentation
DuplicateEdgeID
int UE::Geometry::FDynamicGraph::DuplicateEdgeID = -2 static constexpr
Definition at line 28 of file DynamicGraph.h.
Referenced by AppendEdge().
edges
TDynamicVector<FEdge> UE::Geometry::FDynamicGraph::edges protected
Definition at line 50 of file DynamicGraph.h.
Referenced by add_edge(), edge_has_v(), edge_other_v(), Edges(), FindEdge(), GetEdge(), UE::Geometry::FDynamicGraph2< double >::GetEdgeCenter(), UE::Geometry::FDynamicGraph3< double >::GetEdgeCenter(), GetEdgeGroup(), UE::Geometry::FDynamicGraph2< double >::GetEdgeSegment(), UE::Geometry::FDynamicGraph3< double >::GetEdgeSegment(), UE::Geometry::FDynamicGraph2< double >::GetEdgeV(), UE::Geometry::FDynamicGraph3< double >::GetEdgeV(), GetEdgeV(), RemoveEdge(), replace_edge_vertex(), SetEdgeGroup(), SplitEdge(), and SplitEdgeWithExistingVertex().
edges_refcount
FRefCountVector UE::Geometry::FDynamicGraph::edges_refcount protected
Definition at line 49 of file DynamicGraph.h.
Referenced by add_edge(), CheckValidity(), CollapseEdge(), EdgeCount(), EdgeIndices(), Edges(), GetEdge(), UE::Geometry::FDynamicGraph2< double >::GetEdgeCenter(), UE::Geometry::FDynamicGraph3< double >::GetEdgeCenter(), GetEdgeGroup(), UE::Geometry::FDynamicGraph2< double >::GetEdgeSegment(), UE::Geometry::FDynamicGraph3< double >::GetEdgeSegment(), UE::Geometry::FDynamicGraph2< double >::GetEdgeV(), UE::Geometry::FDynamicGraph3< double >::GetEdgeV(), GetEdgeV(), IsCompact(), IsEdge(), MaxEdgeID(), RemoveEdge(), and SetEdgeGroup().
InvalidID
int UE::Geometry::FDynamicGraph::InvalidID = IndexConstants::InvalidID static constexpr
Definition at line 27 of file DynamicGraph.h.
Referenced by append_new_split_vertex(), AppendEdge(), CheckValidity(), CollapseEdge(), edge_other_v(), FindEdge(), UE::Geometry::FArrangement2d::insert_segment(), InvalidEdge3(), InvalidEdgeV(), SplitEdge(), and SplitEdgeWithExistingVertex().
max_group_id
int UE::Geometry::FDynamicGraph::max_group_id = 0 protected
Definition at line 55 of file DynamicGraph.h.
Referenced by FDynamicGraph(), AllocateEdgeGroup(), AppendEdge(), MaxGroupID(), and SetEdgeGroup().
shape_timestamp
int UE::Geometry::FDynamicGraph::shape_timestamp = 0 protected
Definition at line 53 of file DynamicGraph.h.
Referenced by ShapeTimestamp(), and updateTimeStamp().
timestamp
int UE::Geometry::FDynamicGraph::timestamp = 0 protected
Definition at line 52 of file DynamicGraph.h.
Referenced by Timestamp(), and updateTimeStamp().
vertex_edges
FSmallListSet UE::Geometry::FDynamicGraph::vertex_edges protected
Definition at line 47 of file DynamicGraph.h.
Referenced by add_edge(), allocate_edges_list(), CheckValidity(), CollapseEdge(), FindEdge(), GetMaxVtxEdgeCount(), GetVtxEdgeCount(), IsBoundaryVertex(), IsJunctionVertex(), IsRegularVertex(), UE::Geometry::FDynamicGraph2< double >::OpeningAngle(), RemoveEdge(), UE::Geometry::FDynamicGraph2< double >::SortedVtxEdges(), SplitEdge(), SplitEdgeWithExistingVertex(), VtxEdgesItr(), and VtxVerticesItr().
vertices_refcount
FRefCountVector UE::Geometry::FDynamicGraph::vertices_refcount protected
Definition at line 45 of file DynamicGraph.h.
Referenced by append_vertex_internal(), AppendEdge(), CheckValidity(), CollapseEdge(), GetMaxVtxEdgeCount(), UE::Geometry::FDynamicGraph2< double >::GetVertex(), UE::Geometry::FDynamicGraph3< double >::GetVertex(), GetVtxEdgeCount(), insert_vertex_internal(), IsBoundaryVertex(), IsCompact(), IsCompactV(), IsJunctionVertex(), IsRegularVertex(), IsVertex(), MaxVertexID(), UE::Geometry::FDynamicGraph2< double >::OpeningAngle(), RemoveEdge(), UE::Geometry::FDynamicGraph2< double >::SetVertex(), UE::Geometry::FDynamicGraph3< double >::SetVertex(), UE::Geometry::FDynamicGraph2< double >::SortedVtxEdges(), SplitEdge(), SplitEdgeWithExistingVertex(), VertexCount(), VertexIndices(), UE::Geometry::FDynamicGraph3< double >::VertexIndicesItr(), UE::Geometry::FDynamicGraph2< double >::Vertices(), UE::Geometry::FDynamicGraph3< double >::VerticesItr(), VtxEdgesItr(), and VtxVerticesItr().
The documentation for this class was generated from the following file:
DynamicGraph.h