Unreal Engine 5.6 C++ API: FLoadPackageAsyncProgressDelegate Class Reference
FLoadPackageAsyncProgressDelegate Class Reference
Thread-safe delegate called on progress of async package loading.
#include "UObjectGlobals.h"
Public Types
using DelegateType = TTSDelegate<void(FLoadPackageAsyncProgressParams& Params)>
Public Member Functions
FLoadPackageAsyncProgressDelegate (DelegateType &&InDelegate, uint32 InMask=MAX_uint32)
void Invoke (FLoadPackageAsyncProgressParams &Params)
Static Public Member Functions
static constexpr uint32 BuildMask (auto... Types)
static constexpr uint32 BuildMask (EAsyncLoadingProgress Progress)
Private Attributes
TTSDelegate< void(FLoadPackageAsyncProgressParams &Params)> Delegate
const uint32 Mask { MAX_uint32 }
Detailed Description
Thread-safe delegate called on progress of async package loading.
Definition at line 723 of file UObjectGlobals.h.
Member Typedef Documentation
DelegateType
using FLoadPackageAsyncProgressDelegate::DelegateType = TTSDelegate<void(FLoadPackageAsyncProgressParams& Params)>
Definition at line 726 of file UObjectGlobals.h.
Constructor & Destructor Documentation
FLoadPackageAsyncProgressDelegate()
FLoadPackageAsyncProgressDelegate::FLoadPackageAsyncProgressDelegate (DelegateType && InDelegate, uint32 InMask = MAX_uint32) inline
Definition at line 728 of file UObjectGlobals.h.
References Delegate, Mask, and MAX_uint32.
Member Function Documentation
BuildMask() [1/2]
constexpr uint32 FLoadPackageAsyncProgressDelegate::BuildMask (auto... Types) inline static constexpr
Definition at line 738 of file UObjectGlobals.h.
References BuildMask().
BuildMask() [2/2]
constexpr uint32 FLoadPackageAsyncProgressDelegate::BuildMask (EAsyncLoadingProgress Progress) inline static constexpr
Definition at line 733 of file UObjectGlobals.h.
Referenced by BuildMask(), and Invoke().
Invoke()
void FLoadPackageAsyncProgressDelegate::Invoke (FLoadPackageAsyncProgressParams & Params) inline
Definition at line 743 of file UObjectGlobals.h.
References BuildMask(), Delegate, Mask, and Params.
Field Documentation
Delegate
TTSDelegate<void(FLoadPackageAsyncProgressParams& Params)> FLoadPackageAsyncProgressDelegate::Delegate private
Definition at line 752 of file UObjectGlobals.h.
Referenced by FLoadPackageAsyncProgressDelegate(), and Invoke().
Mask
const uint32 FLoadPackageAsyncProgressDelegate::Mask { MAX_uint32 } private
Definition at line 753 of file UObjectGlobals.h.
Referenced by FLoadPackageAsyncProgressDelegate(), and Invoke().
The documentation for this class was generated from the following file:
UObjectGlobals.h