Unreal Engine 5.6 C++ API: IGameplayTagAssetInterface Class Reference
IGameplayTagAssetInterface Class Reference abstract
Interface for assets which contain gameplay tags.
#include "GameplayTagAssetInterface.h"
Protected Member Functions
UFUNCTION ()) GAMEPLAYTAGS_API virtual UPARAM(DisplayName
Gets the owned gameplay tags for the asset.
Private Member Functions
GENERATED_IINTERFACE_BODY () virtual void GetOwnedGameplayTags(FGameplayTagContainer &TagContainer) const =0
Get any owned gameplay tags on the asset.
UFUNCTION () GAMEPLAYTAGS_API virtual bool HasAllMatchingGameplayTags(const FGameplayTagContainer &TagContainer) const
Check if the asset has gameplay tags that matches against all of the specified tags (expands to include parents of asset tags)
UFUNCTION () GAMEPLAYTAGS_API virtual bool HasAnyMatchingGameplayTags(const FGameplayTagContainer &TagContainer) const
Check if the asset has gameplay tags that matches against any of the specified tags (expands to include parents of asset tags)
UFUNCTION () GAMEPLAYTAGS_API virtual bool HasMatchingGameplayTag(FGameplayTag TagToCheck) const
Check if the asset has a gameplay tag that matches against the specified tag (expands to include parents of asset tags)
Detailed Description
Interface for assets which contain gameplay tags.
Definition at line 19 of file GameplayTagAssetInterface.h.
Member Function Documentation
GENERATED_IINTERFACE_BODY()
IGameplayTagAssetInterface::GENERATED_IINTERFACE_BODY () const & private pure virtual
Get any owned gameplay tags on the asset.
Parameters
OutTags [OUT] Set of tags on the asset
UFUNCTION() [1/4]
IGameplayTagAssetInterface::UFUNCTION () const & private
Check if the asset has gameplay tags that matches against all of the specified tags (expands to include parents of asset tags)
Parameters
TagContainer Tag container to check for a match
Returns
True if the asset has matches all of the gameplay tags, will be true if container is empty
References Category, GameplayTags, and UFUNCTION().
UFUNCTION() [2/4]
IGameplayTagAssetInterface::UFUNCTION () const & private
Check if the asset has gameplay tags that matches against any of the specified tags (expands to include parents of asset tags)
Parameters
TagContainer Tag container to check for a match
Returns
True if the asset has matches any of the gameplay tags, will be false if container is empty
References Category, GameplayTags, and UFUNCTION().
UFUNCTION() [3/4]
IGameplayTagAssetInterface::UFUNCTION () const private
Check if the asset has a gameplay tag that matches against the specified tag (expands to include parents of asset tags)
Parameters
TagToCheck Tag to check for a match
Returns
True if the asset has a gameplay tag that matches, false if not
References Category, GameplayTags, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/4]
IGameplayTagAssetInterface::UFUNCTION () protected
Gets the owned gameplay tags for the asset.
Exposed to allow redirects of existing GetOwnedGameplayTags calls. In Blueprints, new nodes will use BlueprintGameplayTagLibrary's version.
References Category, GameplayTags, meta, UFUNCTION(), and UPARAM.
The documentation for this class was generated from the following file:
GameplayTagAssetInterface.h