Unreal Engine 5.6 C++ API: Metasound::FFrontendGraph Class Reference
Metasound::FFrontendGraph Class Reference
FFrontendGraph is a utility graph for use in the frontend.
#include "MetasoundFrontendGraph.h"
Public Member Functions
METASOUNDFRONTEND_API FFrontendGraph (const FString &InInstanceName, const FGuid &InInstanceID)
FFrontendGraph constructor.
virtual ~FFrontendGraph ()=default
METASOUNDGRAPHCORE_API void AddInputNode (FGuid InNodeID, const FVertexName &InVertexName, TUniquePtr< INode > InNode)
Add an input node to this graph.
METASOUNDGRAPHCORE_API void AddOutputNode (FGuid InNodeID, const FVertexName &InVertexName, TUniquePtr< INode > InNode)
Add an output node to this graph.
UE_DEPRECATED (5.6, "Retrieving input nodes nodes by index will no longer supported on this object") METASOUNDFRONTEND_API const INode *FindInputNode(int32 InIndex) const
Retrieve node by input index.
UE_DEPRECATED (5.6, "Retrieving output nodes nodes by index will no longer supported on this object") METASOUNDFRONTEND_API const INode *FindOutputNode(int32 InIndex) const
Retrieve node by output index.
UE_DEPRECATED (5.6, "Use AddInputNode(...) version which does not take an InIndex") METASOUNDFRONTEND_API void AddInputNode(FGuid InNodeID
Add an input node to this graph.
UE_DEPRECATED (5.6, "Use AddOutputNode(...) version which does not take an InIndex") METASOUNDFRONTEND_API void AddOutputNode(FGuid InNodeID
Add an output node to this graph.
Public Member Functions inherited from Metasound::FGraph
METASOUNDGRAPHCORE_API FGraph (const FString &InInstanceName, const FGuid &InInstanceID, TSharedPtr< const IOperatorData > InNodeConfig={})
virtual ~FGraph ()=default
METASOUNDGRAPHCORE_API void AddDataEdge (const FDataEdge &InEdge)
Add an edge to the graph.
METASOUNDGRAPHCORE_API bool AddDataEdge (const INode &FromNode, const FVertexName &FromVertexKey, const INode &ToNode, const FVertexName &ToVertexKey)
Add an edge to the graph, connecting two vertices from two nodes.
METASOUNDGRAPHCORE_API void AddInputDataDestination (const FInputDataDestination &InDestination)
Add an input data destination to describe how data provided outside this graph should be routed internally.
METASOUNDGRAPHCORE_API bool AddInputDataDestination (const INode &InNode, const FVertexName &InVertexName)
Add an input data destination to describe how data provided outside this graph should be routed internally.
METASOUNDGRAPHCORE_API void AddInputNode (FGuid InNodeID, const FVertexName &InVertexName, TUniquePtr< INode > InNode)
Add an input node to this graph.
METASOUNDGRAPHCORE_API void AddNode (const FGuid &InNodeID, TUniquePtr< INode > InNode)
Store a node on this graph.
METASOUNDGRAPHCORE_API void AddOutputDataSource (const FOutputDataSource &InSource)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
METASOUNDGRAPHCORE_API bool AddOutputDataSource (const INode &InNode, const FVertexName &InVertexName)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
METASOUNDGRAPHCORE_API void AddOutputNode (FGuid InNodeID, const FVertexName &InVertexName, TUniquePtr< INode > InNode)
Add an output node to this graph.
METASOUNDGRAPHCORE_API const INode * FindNode (const FGuid &InNodeID) const
Retrieve node by node ID.
METASOUNDGRAPHCORE_API int32 FindUnconnectedNodes (TArray< TPair< FGuid, const INode * > > &OutUnconnectedNodes) const
Populates an array with all nodes which exist in the graph but do not have any connections.
virtual METASOUNDGRAPHCORE_API const TArray< FDataEdge > & GetDataEdges () const override
Retrieve all the edges associated with a graph.
virtual METASOUNDGRAPHCORE_API FOperatorFactorySharedRef GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
virtual METASOUNDGRAPHCORE_API const FInputDataDestinationCollection & GetInputDataDestinations () const override
Get vertices which contain input parameters.
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FVertexName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata about this graph.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this graph.
virtual METASOUNDGRAPHCORE_API const FOutputDataSourceCollection & GetOutputDataSources () const override
Get vertices which contain output parameters.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the current vertex interface.
METASOUNDGRAPHCORE_API bool RemoveDataEdge (const INode &FromNode, const FVertexName &FromVertexKey, const INode &ToNode, const FVertexName &ToVertexKey)
Remove the given data edge.
METASOUNDGRAPHCORE_API void RemoveDataEdgesWithNode (const INode &InNode)
Removes all edges with connected to the node.
METASOUNDGRAPHCORE_API bool RemoveInputDataDestination (const FVertexName &InVertexName)
Remove an input data destination by vertex name.
METASOUNDGRAPHCORE_API bool RemoveNode (const FGuid &InNodeID, bool bInRemoveDataEdgesWithNode=true)
Removes node from graph.
METASOUNDGRAPHCORE_API bool RemoveOutputDataSource (const FVertexName &InVertexName)
Remove an output data source by vertex name.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default value associated with an input vertex.
METASOUNDGRAPHCORE_API void SetNodeDefaultInput (const FGuid &InNodeID, const FVertexName &InVertexName, const FLiteral &InLiteral)
Set the input default literal for a node that exists in the graph.
template<typename PredicateType>
UE_DEPRECATED (5.3, "Removing data edges by predicate is no longer supported") void RemoveDataEdgeByPredicate(const PredicateType &Predicate)
Removes all edges for which that predicate returns true.
UE_DEPRECATED (5.6, "FGraphs can only set their interface by adding inputs and outputs.") METASOUNDGRAPHCORE_API virtual bool SetVertexInterface(const FVertexInterface &InInterface) override
Set the vertex interface.
UE_DEPRECATED (5.6, "This function no longer serves a purpose.") METASOUNDGRAPHCORE_API virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const override
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "Use AddInputNode(...) which accepts a unique ptr") METASOUNDGRAPHCORE_API void AddInputNode(FGuid InNodeID
Add an input node to this graph.
UE_DEPRECATED (5.6, "Use AddNode(...) which accepts a unique ptr") METASOUNDGRAPHCORE_API void AddNode(const FGuid &InNodeID
UE_DEPRECATED (5.6, "Use AddOutputNode(...) which accepts a unique ptr") METASOUNDGRAPHCORE_API void AddOutputNode(FGuid InNodeID
Add an output node to this graph.
Public Member Functions inherited from Metasound::IGraph
virtual ~IGraph ()
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Data Fields
int32 InIndex
int32 const FVertexName TSharedPtr< const INode > InNode
int32 const FVertexName & InVertexName
Data Fields inherited from Metasound::FGraph
TSharedPtr< const INode > InNode
const FVertexName TSharedPtr< const INode > InNode
const FVertexName & InVertexName
Private Attributes
TMap< int32, const INode * > InputNodes
TMap< int32, const INode * > OutputNodes
Detailed Description
FFrontendGraph is a utility graph for use in the frontend.
It can own nodes that live within the graph and provides query interfaces for finding nodes by dependency ID or input/output index.
Definition at line 28 of file MetasoundFrontendGraph.h.
Constructor & Destructor Documentation
FFrontendGraph()
METASOUNDFRONTEND_API Metasound::FFrontendGraph::FFrontendGraph (const FString & InInstanceName, const FGuid & InInstanceID)
FFrontendGraph constructor.
@parma InInstanceName - Name of this graph. @parma InInstanceID - ID of this graph.
References UE_API.
~FFrontendGraph()
virtual Metasound::FFrontendGraph::~FFrontendGraph () virtual default
Member Function Documentation
AddInputNode()
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddInputNode (FGuid InNodeID, const FVertexName & InVertexName, TUniquePtr< INode > InNode)
Add an input node to this graph.
Parameters
InNodeID - A unique ID associated with the node.
InVertexName - The key for the graph input vertex.
InNode - A unique pointer to an input node.
AddOutputNode()
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddOutputNode (FGuid InNodeID, const FVertexName & InVertexName, TUniquePtr< INode > InNode)
Add an output node to this graph.
Parameters
InNodeID - A unique ID associated with the node.
InVertexName - The key for the graph output vertex.
InNode - A shared pointer to an output node.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/4]
Metasound::FFrontendGraph::UE_DEPRECATED (5. 6, "Retrieving input nodes nodes by index will no longer supported on this object") const
Retrieve node by input index.
Parameters
InIndex - The index of the requested input.
Returns
Pointer to the Node if it is stored on this graph. nullptr otherwise.
References InIndex, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [2/4]
Metasound::FFrontendGraph::UE_DEPRECATED (5. 6, "Retrieving output nodes nodes by index will no longer supported on this object") const
Retrieve node by output index.
Parameters
InIndex - The index of the requested output.
Returns
Pointer to the Node if it is stored on this graph. nullptr otherwise.
References InIndex, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [3/4]
Metasound::FFrontendGraph::UE_DEPRECATED (5. 6, "Use AddInputNode(...) version which does not take an InIndex")
Add an input node to this graph.
Parameters
InNodeID - The NodeID related to the parent FMetasoundFrontendClass.
InIndex - The positional index for the input.
InVertexName - The key for the graph input vertex.
InNode - A shared pointer to an input node.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
Metasound::FFrontendGraph::UE_DEPRECATED (5. 6, "Use AddOutputNode(...) version which does not take an InIndex")
Add an output node to this graph.
Parameters
InNodeID - The NodeID related to the parent FMetasoundFrontendClass.
InIndex - The positional index for the output.
InVertexName - The key for the graph output vertex.
InNode - A shared pointer to an output node.
References Metasound::FGraph::FGraph(), AddOutputNode(), InIndex, InNode, InVertexName, UE_API, and UE_DEPRECATED().
Field Documentation
InIndex
int32 Metasound::FFrontendGraph::InIndex
Definition at line 48 of file MetasoundFrontendGraph.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
InNode
int32 const FVertexName TSharedPtr< const INode > Metasound::FFrontendGraph::InNode
Definition at line 48 of file MetasoundFrontendGraph.h.
Referenced by UE_DEPRECATED().
InputNodes
TMap<int32, const INode*> Metasound::FFrontendGraph::InputNodes private
Definition at line 86 of file MetasoundFrontendGraph.h.
InVertexName
int32 const FVertexName & Metasound::FFrontendGraph::InVertexName
Definition at line 48 of file MetasoundFrontendGraph.h.
Referenced by UE_DEPRECATED().
OutputNodes
TMap<int32, const INode*> Metasound::FFrontendGraph::OutputNodes private
Definition at line 87 of file MetasoundFrontendGraph.h.
The documentation for this class was generated from the following file:
MetasoundFrontendGraph.h