Unreal Engine 5.6 C++ API: UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree > Struct Template Reference
UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree > Struct Template Reference
Find roots of a polynomial of a specified degree.
#include "PolynomialRootSolver.h"
Public Member Functions
TPolynomialRootSolver ()=default
TPolynomialRootSolver (TArrayView< const RealType > PolyCoeffs, RealType RangeStart, RealType RangeEnd, RealType Tolerance=(RealType) UE_SMALL_NUMBER, int32 MaxNewtonIterations=20, RealType NearRootTolerance=(RealType) UE_SMALL_NUMBER)
Find roots within the specified open interval (RangeStart, RangeEnd) (i.e.
int32 FindRootsInRange (TArrayView< const RealType > PolyCoeffs, RealType RangeStart, RealType RangeEnd, RealType Tolerance=(RealType) UE_SMALL_NUMBER, int32 MaxNewtonIterations=20, RealType NearRootTolerance=(RealType) UE_SMALL_NUMBER)
Find roots within the specified open interval (RangeStart, RangeEnd) (i.e.
Data Fields
TArray< RealType, TInlineAllocator< PolynomialDegree > > Roots
Detailed Description
template<typename RealType, int32 PolynomialDegree>
struct UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree >
Find roots of a polynomial of a specified degree.
Definition at line 17 of file PolynomialRootSolver.h.
Constructor & Destructor Documentation
TPolynomialRootSolver() [1/2]
template<typename RealType, int32 PolynomialDegree> UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree >::TPolynomialRootSolver () default
TPolynomialRootSolver() [2/2]
template<typename RealType, int32 PolynomialDegree> UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree >::TPolynomialRootSolver (TArrayView< const RealType > PolyCoeffs, RealType RangeStart, RealType RangeEnd, RealType Tolerance = (RealType)UE_SMALL_NUMBER, int32 MaxNewtonIterations = 20, RealType NearRootTolerance = (RealType)UE_SMALL_NUMBER) inline
Find roots within the specified open interval (RangeStart, RangeEnd) (i.e.
roots at either extreme are not returned)
Parameters
PolyCoeffs The coefficients of the polynomial such that PolyCoeffs[i] is the coefficient of the x^i term. Must have at least PolynomialDegree + 1 elements.
RangeStart Start of the open range to search for roots
RangeEnd End of the open range to search for roots
Tolerance Absolute tolerance for the returned root
MaxNewtonIterations Maximum number of newton/bisection iterations to perform internally when finding a root
NearRootTolerance Tolerance for finding almost-roots, i.e. cases where the polynomial just grazes 0 without crossing
Definition at line 36 of file PolynomialRootSolver.h.
References FindRootsInRange(), and UE_SMALL_NUMBER.
Member Function Documentation
FindRootsInRange()
template<typename RealType, int32 PolynomialDegree> int32 UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree >::FindRootsInRange (TArrayView< const RealType > PolyCoeffs, RealType RangeStart, RealType RangeEnd, RealType Tolerance = (RealType)UE_SMALL_NUMBER, int32 MaxNewtonIterations = 20, RealType NearRootTolerance = (RealType)UE_SMALL_NUMBER) inline
Find roots within the specified open interval (RangeStart, RangeEnd) (i.e.
roots at either extreme are not returned)
Parameters
PolyCoeffs The coefficients of the polynomial such that PolyCoeffs[i] is the coefficient of the x^i term. Must have at least PolynomialDegree + 1 elements.
RangeStart Start of the open range to search for roots
RangeEnd End of the open range to search for roots
Tolerance Absolute tolerance for the returned roots
MaxNewtonIterations Maximum number of newton/bisection iterations to perform internally when finding a root
NearRootTolerance Tolerance for finding almost-roots, i.e. cases where the polynomial just grazes 0 without crossing
Returns
Number of roots found
Definition at line 53 of file PolynomialRootSolver.h.
References checkSlow, ensure, TStaticArray< InElementType, NumElements, Alignment >::GetData(), TArrayView< InElementType, InSizeType >::Num(), Roots, Swap, UE_SMALL_NUMBER, and Value.
Referenced by TPolynomialRootSolver().
Field Documentation
Roots
template<typename RealType, int32 PolynomialDegree> TArray<RealType, TInlineAllocator<PolynomialDegree> > UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree >::Roots
Definition at line 22 of file PolynomialRootSolver.h.
Referenced by FInterpCurve< T >::FindNearestOnSegment(), and FindRootsInRange().
The documentation for this struct was generated from the following file:
PolynomialRootSolver.h