Unreal Engine 5.6 C++ API: TMovieSceneEvaluationTreeDataIterator< DataType > Struct Template Reference
TMovieSceneEvaluationTreeDataIterator< DataType > Struct Template Reference
An iterator type that is iterates all the data associated with a given node and its parents.
#include "MovieSceneEvaluationTree.h"
Public Member Functions
TMovieSceneEvaluationTreeDataIterator (const TMovieSceneEvaluationTree< DataType > &InTree, FMovieSceneEvaluationTreeNodeHandle StartNode)
Construction from a tree and a node.
bool IsValid () const
Check the iterator for validity.
operator bool () const
Check the iterator for validity.
const DataType & operator* () const
Dereference the data for the current iteration.
TMovieSceneEvaluationTreeDataIterator & operator++ ()
Move on to the next piece of data.
const DataType * operator-> () const
Access the data for the current iteration.
Private Attributes
const FMovieSceneEvaluationTreeNode * CurrentNode
The current node of the iteration (nullptr for invalid iterators)
int32 DataIndex
The current data index within CurrentNode's data.
const TMovieSceneEvaluationTree< DataType > * Tree
The tree we're reading.
Friends
TMovieSceneEvaluationTreeDataIterator< DataType > begin (const TMovieSceneEvaluationTreeDataIterator< DataType > &In)
Range-for support.
TMovieSceneEvaluationTreeDataIterator< DataType > end (const TMovieSceneEvaluationTreeDataIterator< DataType > &In)
bool operator!= (const TMovieSceneEvaluationTreeDataIterator< DataType > &A, const TMovieSceneEvaluationTreeDataIterator< DataType > &B)
bool operator== (const TMovieSceneEvaluationTreeDataIterator< DataType > &A, const TMovieSceneEvaluationTreeDataIterator< DataType > &B)
(In)Equality operators
Detailed Description
template<typename DataType>
struct TMovieSceneEvaluationTreeDataIterator< DataType >
An iterator type that is iterates all the data associated with a given node and its parents.
Definition at line 804 of file MovieSceneEvaluationTree.h.
Constructor & Destructor Documentation
TMovieSceneEvaluationTreeDataIterator()
template<typename DataType> TMovieSceneEvaluationTreeDataIterator< DataType >::TMovieSceneEvaluationTreeDataIterator (const TMovieSceneEvaluationTree< DataType > & InTree, FMovieSceneEvaluationTreeNodeHandle StartNode) inline
Construction from a tree and a node.
Definition at line 807 of file MovieSceneEvaluationTree.h.
References CurrentNode, DataIndex, TMovieSceneEvaluationTree< DataType >::GetDataForSingleNode(), IsValid(), and Tree.
Referenced by begin, end, operator!=, operator++(), and operator==.
Member Function Documentation
IsValid()
template<typename DataType> bool TMovieSceneEvaluationTreeDataIterator< DataType >::IsValid () const inline
Check the iterator for validity.
Definition at line 833 of file MovieSceneEvaluationTree.h.
References CurrentNode, DataIndex, and Tree.
Referenced by TMovieSceneEvaluationTreeDataIterator(), and operator bool().
operator bool()
template<typename DataType> TMovieSceneEvaluationTreeDataIterator< DataType >::operator bool () const inline explicit
Check the iterator for validity.
Definition at line 839 of file MovieSceneEvaluationTree.h.
References IsValid().
operator*()
template<typename DataType> const DataType & TMovieSceneEvaluationTreeDataIterator< DataType >::operator* () const inline
Dereference the data for the current iteration.
Definition at line 821 of file MovieSceneEvaluationTree.h.
References CurrentNode, DataIndex, and Tree.
operator++()
template<typename DataType> TMovieSceneEvaluationTreeDataIterator & TMovieSceneEvaluationTreeDataIterator< DataType >::operator++ () inline
Move on to the next piece of data.
Definition at line 845 of file MovieSceneEvaluationTree.h.
References TMovieSceneEvaluationTreeDataIterator(), CurrentNode, DataIndex, and Tree.
operator->()
template<typename DataType> const DataType * TMovieSceneEvaluationTreeDataIterator< DataType >::operator-> () const inline
Access the data for the current iteration.
Definition at line 827 of file MovieSceneEvaluationTree.h.
References CurrentNode, DataIndex, and Tree.
Friends And Related Symbol Documentation
begin
template<typename DataType> TMovieSceneEvaluationTreeDataIterator< DataType > begin (const TMovieSceneEvaluationTreeDataIterator< DataType > & In) friend
Range-for support.
Definition at line 859 of file MovieSceneEvaluationTree.h.
References TMovieSceneEvaluationTreeDataIterator().
end
template<typename DataType> TMovieSceneEvaluationTreeDataIterator< DataType > end (const TMovieSceneEvaluationTreeDataIterator< DataType > & In) friend
Definition at line 860 of file MovieSceneEvaluationTree.h.
References TMovieSceneEvaluationTreeDataIterator(), FMovieSceneEvaluationTreeNodeHandle::Invalid(), and Tree.
operator!=
template<typename DataType> bool operator!= (const TMovieSceneEvaluationTreeDataIterator< DataType > & A, const TMovieSceneEvaluationTreeDataIterator< DataType > & B) friend
Definition at line 863 of file MovieSceneEvaluationTree.h.
References TMovieSceneEvaluationTreeDataIterator(), A, and B.
operator==
template<typename DataType> bool operator== (const TMovieSceneEvaluationTreeDataIterator< DataType > & A, const TMovieSceneEvaluationTreeDataIterator< DataType > & B) friend
(In)Equality operators
Definition at line 862 of file MovieSceneEvaluationTree.h.
References TMovieSceneEvaluationTreeDataIterator(), A, and B.
Field Documentation
CurrentNode
template<typename DataType> const FMovieSceneEvaluationTreeNode* TMovieSceneEvaluationTreeDataIterator< DataType >::CurrentNode private
The current node of the iteration (nullptr for invalid iterators)
Definition at line 869 of file MovieSceneEvaluationTree.h.
Referenced by TMovieSceneEvaluationTreeDataIterator(), IsValid(), operator*(), operator++(), and operator->().
DataIndex
template<typename DataType> int32 TMovieSceneEvaluationTreeDataIterator< DataType >::DataIndex private
The current data index within CurrentNode's data.
Definition at line 871 of file MovieSceneEvaluationTree.h.
Referenced by TMovieSceneEvaluationTreeDataIterator(), IsValid(), operator*(), operator++(), and operator->().
Tree
template<typename DataType> const TMovieSceneEvaluationTree<DataType>* TMovieSceneEvaluationTreeDataIterator< DataType >::Tree private
The tree we're reading.
Definition at line 867 of file MovieSceneEvaluationTree.h.
Referenced by TMovieSceneEvaluationTreeDataIterator(), end, IsValid(), operator*(), operator++(), and operator->().
The documentation for this struct was generated from the following files:
MovieSceneCompiledDataManager.h
MovieSceneEvaluationTree.h