Unreal Engine 5.6 C++ API: FWorldInitializationValues Struct Reference
FWorldInitializationValues Struct Reference
Struct containing a collection of optional parameters for initialization of a World.
#include "WorldInitializationValues.h"
Public Member Functions
FWorldInitializationValues ()
FWorldInitializationValues & AllowAudioPlayback (const bool bAllow)
FWorldInitializationValues & CreateAISystem (const bool bCreate)
FWorldInitializationValues & CreateFXSystem (const bool bCreate)
FWorldInitializationValues & CreateNavigation (const bool bCreate)
FWorldInitializationValues & CreatePhysicsScene (const bool bCreate)
FWorldInitializationValues & CreateWorldPartition (const bool bCreate)
FWorldInitializationValues & EnableTraceCollision (const bool bInEnableTraceCollision)
FWorldInitializationValues & EnableWorldPartitionStreaming (const bool bEnableStreaming)
FWorldInitializationValues & ForceUseMovementComponentInNonGameWorld (const bool bInForceUseMovementComponentInNonGameWorld)
FWorldInitializationValues & InitializeScenes (const bool bInitialize)
FWorldInitializationValues & RequiresHitProxies (const bool bRequires)
FWorldInitializationValues & SetDefaultGameMode (TSubclassOf< class AGameModeBase > GameMode)
FWorldInitializationValues & SetTransactional (const bool bInTransactional)
FWorldInitializationValues & ShouldSimulatePhysics (const bool bInShouldSimulatePhysics)
Data Fields
uint32 bAllowAudioPlayback:1
Are sounds allowed to be generated from this world.
uint32 bCreateAISystem:1
Should the AI system be created for this world.
uint32 bCreateFXSystem:1
Should the FX system be created for this world.
uint32 bCreateNavigation:1
Should the navigation system be created for this world.
uint32 bCreatePhysicsScene:1
Should the physics scene be created.
uint32 bCreateWorldPartition:1
Should the world be partitioned.
uint32 bEnableTraceCollision:1
Are collision trace calls valid within this world.
uint32 bEnableWorldPartitionStreaming:1
If bCreateWorldPartition is set to true, this flag will init the streaming mode for the WorldPartition object (default to true to preserve previous behavior)
uint32 bForceUseMovementComponentInNonGameWorld:1
Special flag to enable movement component in non game worlds (see UMovementComponent::OnRegister)
uint32 bInitializeScenes:1
Should the scenes (physics, rendering) be created.
uint32 bRequiresHitProxies:1
Should the render scene create hit proxies.
uint32 bShouldSimulatePhysics:1
Should physics be simulated in this world.
uint32 bTransactional:1
Should actions performed to objects in this world be saved to the transaction buffer.
TSubclassOf< class AGameModeBase > DefaultGameMode
The default game mode for this world (if any)
Detailed Description
Struct containing a collection of optional parameters for initialization of a World.
Definition at line 8 of file WorldInitializationValues.h.
Constructor & Destructor Documentation
FWorldInitializationValues()
FWorldInitializationValues::FWorldInitializationValues () inline
Definition at line 10 of file WorldInitializationValues.h.
References bAllowAudioPlayback, bCreateAISystem, bCreateFXSystem, bCreateNavigation, bCreatePhysicsScene, bCreateWorldPartition, bEnableTraceCollision, bEnableWorldPartitionStreaming, bForceUseMovementComponentInNonGameWorld, bInitializeScenes, bRequiresHitProxies, bShouldSimulatePhysics, and bTransactional.
Referenced by AllowAudioPlayback(), CreateAISystem(), CreateFXSystem(), CreateNavigation(), CreatePhysicsScene(), CreateWorldPartition(), EnableTraceCollision(), EnableWorldPartitionStreaming(), ForceUseMovementComponentInNonGameWorld(), InitializeScenes(), RequiresHitProxies(), SetDefaultGameMode(), SetTransactional(), and ShouldSimulatePhysics().
Member Function Documentation
AllowAudioPlayback()
FWorldInitializationValues & FWorldInitializationValues::AllowAudioPlayback (const bool bAllow) inline
Definition at line 70 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bAllowAudioPlayback.
CreateAISystem()
FWorldInitializationValues & FWorldInitializationValues::CreateAISystem (const bool bCreate) inline
Definition at line 74 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bCreateAISystem.
CreateFXSystem()
FWorldInitializationValues & FWorldInitializationValues::CreateFXSystem (const bool bCreate) inline
Definition at line 79 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bCreateFXSystem.
CreateNavigation()
FWorldInitializationValues & FWorldInitializationValues::CreateNavigation (const bool bCreate) inline
Definition at line 73 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bCreateNavigation.
CreatePhysicsScene()
FWorldInitializationValues & FWorldInitializationValues::CreatePhysicsScene (const bool bCreate) inline
Definition at line 72 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bCreatePhysicsScene.
CreateWorldPartition()
FWorldInitializationValues & FWorldInitializationValues::CreateWorldPartition (const bool bCreate) inline
Definition at line 80 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bCreateWorldPartition.
EnableTraceCollision()
FWorldInitializationValues & FWorldInitializationValues::EnableTraceCollision (const bool bInEnableTraceCollision) inline
Definition at line 76 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bEnableTraceCollision.
EnableWorldPartitionStreaming()
FWorldInitializationValues & FWorldInitializationValues::EnableWorldPartitionStreaming (const bool bEnableStreaming) inline
Definition at line 81 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bEnableWorldPartitionStreaming.
ForceUseMovementComponentInNonGameWorld()
FWorldInitializationValues & FWorldInitializationValues::ForceUseMovementComponentInNonGameWorld (const bool bInForceUseMovementComponentInNonGameWorld) inline
Definition at line 77 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bForceUseMovementComponentInNonGameWorld.
InitializeScenes()
FWorldInitializationValues & FWorldInitializationValues::InitializeScenes (const bool bInitialize) inline
Definition at line 69 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bInitializeScenes.
RequiresHitProxies()
FWorldInitializationValues & FWorldInitializationValues::RequiresHitProxies (const bool bRequires) inline
Definition at line 71 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bRequiresHitProxies.
SetDefaultGameMode()
FWorldInitializationValues & FWorldInitializationValues::SetDefaultGameMode (TSubclassOf< class AGameModeBase > GameMode) inline
Definition at line 82 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and DefaultGameMode.
SetTransactional()
FWorldInitializationValues & FWorldInitializationValues::SetTransactional (const bool bInTransactional) inline
Definition at line 78 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bTransactional.
ShouldSimulatePhysics()
FWorldInitializationValues & FWorldInitializationValues::ShouldSimulatePhysics (const bool bInShouldSimulatePhysics) inline
Definition at line 75 of file WorldInitializationValues.h.
References FWorldInitializationValues(), and bShouldSimulatePhysics.
Field Documentation
bAllowAudioPlayback
uint32 FWorldInitializationValues::bAllowAudioPlayback
Are sounds allowed to be generated from this world.
Definition at line 31 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and AllowAudioPlayback().
bCreateAISystem
uint32 FWorldInitializationValues::bCreateAISystem
Should the AI system be created for this world.
Definition at line 43 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and CreateAISystem().
bCreateFXSystem
uint32 FWorldInitializationValues::bCreateFXSystem
Should the FX system be created for this world.
Definition at line 58 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and CreateFXSystem().
bCreateNavigation
uint32 FWorldInitializationValues::bCreateNavigation
Should the navigation system be created for this world.
Definition at line 40 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and CreateNavigation().
bCreatePhysicsScene
uint32 FWorldInitializationValues::bCreatePhysicsScene
Should the physics scene be created.
bInitializeScenes must be true for this to be considered.
Definition at line 37 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and CreatePhysicsScene().
bCreateWorldPartition
uint32 FWorldInitializationValues::bCreateWorldPartition
Should the world be partitioned.
Definition at line 61 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and CreateWorldPartition().
bEnableTraceCollision
uint32 FWorldInitializationValues::bEnableTraceCollision
Are collision trace calls valid within this world.
Definition at line 49 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and EnableTraceCollision().
bEnableWorldPartitionStreaming
uint32 FWorldInitializationValues::bEnableWorldPartitionStreaming
If bCreateWorldPartition is set to true, this flag will init the streaming mode for the WorldPartition object (default to true to preserve previous behavior)
Definition at line 64 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and EnableWorldPartitionStreaming().
bForceUseMovementComponentInNonGameWorld
uint32 FWorldInitializationValues::bForceUseMovementComponentInNonGameWorld
Special flag to enable movement component in non game worlds (see UMovementComponent::OnRegister)
Definition at line 52 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and ForceUseMovementComponentInNonGameWorld().
bInitializeScenes
uint32 FWorldInitializationValues::bInitializeScenes
Should the scenes (physics, rendering) be created.
Definition at line 28 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and InitializeScenes().
bRequiresHitProxies
uint32 FWorldInitializationValues::bRequiresHitProxies
Should the render scene create hit proxies.
Definition at line 34 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and RequiresHitProxies().
bShouldSimulatePhysics
uint32 FWorldInitializationValues::bShouldSimulatePhysics
Should physics be simulated in this world.
Definition at line 46 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and ShouldSimulatePhysics().
bTransactional
uint32 FWorldInitializationValues::bTransactional
Should actions performed to objects in this world be saved to the transaction buffer.
Definition at line 55 of file WorldInitializationValues.h.
Referenced by FWorldInitializationValues(), and SetTransactional().
DefaultGameMode
TSubclassOf<class AGameModeBase> FWorldInitializationValues::DefaultGameMode
The default game mode for this world (if any)
Definition at line 67 of file WorldInitializationValues.h.
Referenced by SetDefaultGameMode().
The documentation for this struct was generated from the following file:
WorldInitializationValues.h