Unreal Engine 5.6 C++ API: StatelessConnectHandlerComponent Class Reference
StatelessConnectHandlerComponent Class Reference
PacketHandler component for implementing a stateless (non-memory-consuming) connection handshake.
#include "StatelessConnectHandlerComponent.h"
Data Structures
struct FCommonSendToClientParams
Common parameters for all 'Send*' functions which send packets to clients.
struct FParsedHandshakeData
Handshake data parsed from a packet.
Public Member Functions
StatelessConnectHandlerComponent ()
Base constructor.
virtual void CountBytes (FArchive &Ar) const override
FORCEINLINE bool DoesRestartedHandshakeMatch (StatelessConnectHandlerComponent &NetConnComponent) const
When a restarted handshake is completed, this is used to match it up with the existing NetConnection.
FORCEINLINE void GetChallengeSequence (int32 &OutServerSequence, int32 &OutClientSequence) const
Used for retrieving the initial packet sequence values from the handshake data, after a successful challenge.
FORCEINLINE bool HasPassedChallenge (const TSharedPtr< const FInternetAddr > &Address, bool &bOutRestartedHandshake) const
Whether or not the specified connection address, has just passed the connection handshake challenge.
void InitFromConnectionless (StatelessConnectHandlerComponent *InConnectionlessHandler)
Initializes a serverside UNetConnection-associated StatelessConnect, from the connectionless StatelessConnect that negotiated the handshake.
virtual bool IsValid () const override
virtual void NotifyHandshakeBegin () override
FORCEINLINE void ResetChallengeData ()
Used to reset cached handshake success/fail state, when done processing it.
void SetDriver (UNetDriver *InDriver)
Sets the net driver this handler is associated with.
void SetHandshakeFailureCallback (FHandshakeFailureFunc &&InHandshakeFailureFunc)
Set a callback for notifying of handshake failure (clientside only).
Protected Member Functions
virtual bool CanReadUnaligned () const override
virtual int32 GetReservedPacketBits () const override
virtual void Incoming (FBitReader &Packet) override
virtual void IncomingConnectionless (FIncomingPacketRef PacketRef) override
virtual void Initialize () override
virtual void Outgoing (FBitWriter &Packet, FOutPacketTraits &Traits) override
virtual void Tick (float DeltaTime) override
Private Types
using EHandshakePacketModifier = UE::Net::EHandshakePacketModifier
using EHandshakePacketType = UE::Net::EHandshakePacketType
using EHandshakeVersion = UE::Net::EHandshakeVersion
using FHandshakeFailureFunc = UE::Net::FHandshakeFailureFunc
Private Member Functions
void BeginHandshakePacket (FBitWriter &HandshakePacket, EHandshakePacketType HandshakePacketType, EHandshakeVersion HandshakeVersion, uint8 SentHandshakePacketCount_LocalOrRemote, uint32 ClientID, EHandshakePacketModifier HandshakePacketModifier=EHandshakePacketModifier::None)
Writes out the base/common parameters for all handshake packets, both to server and client.
void CapHandshakePacket (FBitWriter &HandshakePacket, EHandshakeVersion HandshakeVersion)
Pads the handshake packet, to match the PacketBitAlignment of the PacketHandler, so that it will parse correctly.
bool CheckVersion (const FParsedHandshakeData &HandshakeData, EHandshakeVersion &OutTargetVersion) const
Checks the handshake protocol version and Network CL version for incoming handshake packets, serverside.
void GenerateCookie (const TSharedPtr< const FInternetAddr > &ClientAddress, uint8 SecretId, double Timestamp, uint8(&OutCookie)[20]) const
Takes the client address plus server timestamp, and outputs a deterministic cookie value.
int32 GetAdjustedSizeBits (int32 InSizeBits, EHandshakeVersion HandshakeVersion) const
Calculate the adjusted predefined packet size, based on MagicHeader.
bool ParseHandshakePacket (FBitReader &Packet, FParsedHandshakeData &OutResult) const
Parses an incoming handshake packet (does not parse the handshake bit though)
bool ParseHandshakePacketOriginal (FBitReader &Packet, FParsedHandshakeData &OutResult) const
void SendChallengeAck (FCommonSendToClientParams CommonParams, uint8 ClientSentHandshakePacketCount, uint8 InCookie[20])
Constructs and sends the server ack to a successful challenge response, from the server to the client.
void SendChallengeResponse (EHandshakeVersion HandshakeVersion, uint8 InSecretId, double InTimestamp, uint8 InCookie[20])
Constructs and sends the handshake challenge response packet, from the client to the server.
void SendConnectChallenge (FCommonSendToClientParams CommonParams, uint8 ClientSentHandshakePacketCount)
Constructs and sends the server response to the initial connect packet, from the server to the client.
void SendInitialPacket (EHandshakeVersion HandshakeVersion)
Constructs and sends the initial handshake packet, from the client to the server.
void SendRestartHandshakeRequest (FCommonSendToClientParams CommonParams)
Constructs and sends a request to resend the cookie, from the server to the client.
void SendToClient (FCommonSendToClientParams CommonParams, EHandshakePacketType PacketType, FBitWriter &Packet)
Sends a packet from the server to a client.
void SendToServer (EHandshakeVersion HandshakeVersion, EHandshakePacketType PacketType, FBitWriter &Packet)
Sends a packet from the client to the server.
void SendVersionUpgradeMessage (FCommonSendToClientParams CommonParams)
Constructs and sends a stateless handshake level NMT_Upgrade message.
bool TrackValidationLogs ()
Tracks logs for invalid Session ID's, Connection ID's or Magic Header's, and limits the number of these logs.
void UpdateSecret ()
Generates a new HandshakeSecret value.
Private Attributes
uint8 ActiveSecret
Which of the two secret values above is active (values are changed frequently, to limit replay attacks)
uint8 AuthorisedCookie [20]
The cookie which completed the connection handshake.
bool bRestartedHandshake
Both Serverside and Clientside variables.
uint32 CachedClientID = 0
Cached version of the clientside per-NetDriverDefinition 'ClientID' value, for writing client connection id's.
uint32 CachedGlobalNetTravelCount = 0
Cached version of the serverside UEngine.GlobalNetTravelCount value, for writing session id's.
UNetDriver * Driver
The net driver associated with this handler - for performing connectionless sends.
FHandshakeFailureFunc HandshakeFailureCallback
Callback for processing handshake failures.
TArray< uint8 > HandshakeSecret [2]
Serverside variables.
TSharedPtr< const FInternetAddr > LastChallengeSuccessAddress
The last address to successfully complete the handshake challenge.
double LastChallengeTimestamp
The local (client) time at which the challenge was last updated.
double LastClientSendTimestamp
Clientside variables.
int32 LastClientSequence
The initial client sequence value, from the last successful handshake.
uint8 LastCookie [20]
The Cookie value of the last challenge response sent.
double LastInitTimestamp = 0.0
The time of the last post-handshake initialization.
EHandshakeVersion LastRemoteHandshakeVersion
The last remote handshake version sent by the client/server.
double LastRestartPacketTimestamp
The local (client) time at which the last restart handshake request was received.
uint8 LastSecretId
The SecretId value of the last challenge response sent.
double LastSecretUpdateTimestamp
The time of the last secret value update.
int32 LastServerSequence
The initial server sequence value, from the last successful handshake.
double LastTimestamp
The Timestamp value of the last challenge response sent.
double LastUpgradeMessagePeriodStart = 0.0
The last time an 'upgrade message' send period began.
double LastValidationLogPeriodStart = 0.0
The last time an 'invalid SessionId/ClientId/MagicHeader' log period began.
TBitArray MagicHeader
The magic header which is prepended to all packets.
uint32 MagicHeaderUint = 0
Integer representation of the magic header, for direct comparison.
EHandshakeVersion MinClientHandshakeVersion
The minimum supported client version, for all connections - for setting minimum bounds for the restart handshake (not aware of version)
FBitWriter OldPacket
Cache memory of previously used packets to avoid memory allocations.
uint8 SentHandshakePacketCount = 0
The number of sent handshake packets, added to packets to aid packet dump debugging (may roll over)
uint32 UpgradeMessageCounter = 0
The number of upgrade messages sent in the current send period (for rate limiting)
uint32 ValidationLogCounter = 0
The number of 'invalid SessionId/ClientId/MagicHeader' logs in the current log period (for logspam limiting)
Static Private Attributes
static constexpr uint32 ClientIDSizeBits = 3
The size of the connection id in packets (WARNING: Adjusting this is a net compatibility break)
static constexpr uint32 SessionIDSizeBits = 2
The size of the session id in packets (WARNING: Adjusting this is a net compatibility break)
Detailed Description
PacketHandler component for implementing a stateless (non-memory-consuming) connection handshake.
Partially based on the Datagram Transport Layer Security protocol.
Definition at line 118 of file StatelessConnectHandlerComponent.h.
Member Typedef Documentation
EHandshakePacketModifier
using StatelessConnectHandlerComponent::EHandshakePacketModifier = UE::Net::EHandshakePacketModifier private
Definition at line 122 of file StatelessConnectHandlerComponent.h.
EHandshakePacketType
using StatelessConnectHandlerComponent::EHandshakePacketType = UE::Net::EHandshakePacketType private
Definition at line 121 of file StatelessConnectHandlerComponent.h.
EHandshakeVersion
using StatelessConnectHandlerComponent::EHandshakeVersion = UE::Net::EHandshakeVersion private
Definition at line 120 of file StatelessConnectHandlerComponent.h.
FHandshakeFailureFunc
using StatelessConnectHandlerComponent::FHandshakeFailureFunc = UE::Net::FHandshakeFailureFunc private
Definition at line 123 of file StatelessConnectHandlerComponent.h.
Constructor & Destructor Documentation
StatelessConnectHandlerComponent()
StatelessConnectHandlerComponent::StatelessConnectHandlerComponent ()
Base constructor.
Referenced by DoesRestartedHandshakeMatch(), and InitFromConnectionless().
Member Function Documentation
BeginHandshakePacket()
void StatelessConnectHandlerComponent::BeginHandshakePacket (FBitWriter & HandshakePacket, EHandshakePacketType HandshakePacketType, EHandshakeVersion HandshakeVersion, uint8 SentHandshakePacketCount_LocalOrRemote, uint32 ClientID, EHandshakePacketModifier HandshakePacketModifier = EHandshakePacketModifier::None) private
Writes out the base/common parameters for all handshake packets, both to server and client.
Parameters
HandshakePacket The handshake packet being written.
HandshakePacketType The type of handshake packet.
HandshakeVersion The handshake format version to use when sending.
SentHandshakePacketCount_LocalOrRemote The number of handshake packets sent (for debugging/packet-analysis).
ClientID The client-specified connection id.
HandshakePacketModifier Flags/modifiers affecting how the packet will be handled.
CanReadUnaligned()
virtual bool StatelessConnectHandlerComponent::CanReadUnaligned () const inline override protected virtual
Definition at line 330 of file StatelessConnectHandlerComponent.h.
CapHandshakePacket()
void StatelessConnectHandlerComponent::CapHandshakePacket (FBitWriter & HandshakePacket, EHandshakeVersion HandshakeVersion) private
Pads the handshake packet, to match the PacketBitAlignment of the PacketHandler, so that it will parse correctly.
Parameters
HandshakePacket The handshake packet to be aligned.
HandshakeVersion The handshake format version to use when sending
CheckVersion()
bool StatelessConnectHandlerComponent::CheckVersion (const FParsedHandshakeData & HandshakeData, EHandshakeVersion & OutTargetVersion) const private
Checks the handshake protocol version and Network CL version for incoming handshake packets, serverside.
Parameters
HandshakeData The packet handshake data
OutTargetVersion The target handshake protocol version to use, for the new connection
Returns
Whether or not the checks successfully validated that the version is correct, and that communication can continue
CountBytes()
virtual void StatelessConnectHandlerComponent::CountBytes (FArchive & Ar) const override virtual
References Ar.
DoesRestartedHandshakeMatch()
FORCEINLINE bool StatelessConnectHandlerComponent::DoesRestartedHandshakeMatch (StatelessConnectHandlerComponent & NetConnComponent) const inline
When a restarted handshake is completed, this is used to match it up with the existing NetConnection.
Parameters
NetConnComponent The NetConnection StatelessConnectHandlerComponent, which is being checked for a match
Returns
Whether or not the specified component, belongs to the client which restarted the handshake
Definition at line 295 of file StatelessConnectHandlerComponent.h.
References StatelessConnectHandlerComponent(), AuthorisedCookie, COOKIE_BYTE_SIZE, FORCEINLINE, and FMemory::Memcmp().
GenerateCookie()
void StatelessConnectHandlerComponent::GenerateCookie (const TSharedPtr< const FInternetAddr > & ClientAddress, uint8 SecretId, double Timestamp, uint8(&) OutCookie[20]) const private
Takes the client address plus server timestamp, and outputs a deterministic cookie value.
Parameters
ClientAddress The address of the client, including port
SecretId Which of the two HandshakeSecret values the cookie will be based on
TimeStamp The serverside timestamp
OutCookie Outputs the generated cookie value.
References COOKIE_BYTE_SIZE.
GetAdjustedSizeBits()
int32 StatelessConnectHandlerComponent::GetAdjustedSizeBits (int32 InSizeBits, EHandshakeVersion HandshakeVersion) const private
Calculate the adjusted predefined packet size, based on MagicHeader.
GetChallengeSequence()
FORCEINLINE void StatelessConnectHandlerComponent::GetChallengeSequence (int32 & OutServerSequence, int32 & OutClientSequence) const inline
Used for retrieving the initial packet sequence values from the handshake data, after a successful challenge.
Parameters
OutServerSequence Outputs the initial sequence for the server
OutClientSequence Outputs the initial sequence for the client
Definition at line 283 of file StatelessConnectHandlerComponent.h.
References FORCEINLINE, LastClientSequence, and LastServerSequence.
GetReservedPacketBits()
virtual int32 StatelessConnectHandlerComponent::GetReservedPacketBits () const override protected virtual
HasPassedChallenge()
FORCEINLINE bool StatelessConnectHandlerComponent::HasPassedChallenge (const TSharedPtr< const FInternetAddr > & Address, bool & bOutRestartedHandshake) const inline
Whether or not the specified connection address, has just passed the connection handshake challenge.
Parameters
Address The address (including port, for UIpNetDriver) being checked
bOutRestartedHandshake Whether or not the passed challenge, was a restarted handshake for an existing NetConnection
Definition at line 269 of file StatelessConnectHandlerComponent.h.
References bRestartedHandshake, FORCEINLINE, TSharedPtr< ObjectType, InMode >::IsValid(), and LastChallengeSuccessAddress.
Incoming()
virtual void StatelessConnectHandlerComponent::Incoming (FBitReader & Packet) override protected virtual
IncomingConnectionless()
virtual void StatelessConnectHandlerComponent::IncomingConnectionless (FIncomingPacketRef PacketRef) override protected virtual
InitFromConnectionless()
void StatelessConnectHandlerComponent::InitFromConnectionless (StatelessConnectHandlerComponent * InConnectionlessHandler)
Initializes a serverside UNetConnection-associated StatelessConnect, from the connectionless StatelessConnect that negotiated the handshake.
Parameters
InConnectionlessHandler The connectionless StatelessConnect we're initializing from
References StatelessConnectHandlerComponent().
Initialize()
virtual void StatelessConnectHandlerComponent::Initialize () override protected virtual
IsValid()
virtual bool StatelessConnectHandlerComponent::IsValid () const inline override virtual
Definition at line 151 of file StatelessConnectHandlerComponent.h.
NotifyHandshakeBegin()
virtual void StatelessConnectHandlerComponent::NotifyHandshakeBegin () override virtual
Outgoing()
virtual void StatelessConnectHandlerComponent::Outgoing (FBitWriter & Packet, FOutPacketTraits & Traits) override protected virtual
ParseHandshakePacket()
bool StatelessConnectHandlerComponent::ParseHandshakePacket (FBitReader & Packet, FParsedHandshakeData & OutResult) const private
Parses an incoming handshake packet (does not parse the handshake bit though)
Parameters
Packet The packet the handshake is being parsed from
OutResult The parsed handshake data, if successful
Returns
Whether or not the handshake packet was parsed successfully
ParseHandshakePacketOriginal()
bool StatelessConnectHandlerComponent::ParseHandshakePacketOriginal (FBitReader & Packet, FParsedHandshakeData & OutResult) const private
ResetChallengeData()
FORCEINLINE void StatelessConnectHandlerComponent::ResetChallengeData () inline
Used to reset cached handshake success/fail state, when done processing it.
Definition at line 303 of file StatelessConnectHandlerComponent.h.
References AuthorisedCookie, bRestartedHandshake, COOKIE_BYTE_SIZE, FORCEINLINE, LastChallengeSuccessAddress, LastClientSequence, LastServerSequence, and FMemory::Memzero().
SendChallengeAck()
void StatelessConnectHandlerComponent::SendChallengeAck (FCommonSendToClientParams CommonParams, uint8 ClientSentHandshakePacketCount, uint8 InCookie[20]) private
Constructs and sends the server ack to a successful challenge response, from the server to the client.
Parameters
CommonParams Common parameters for 'Send*' functions to clients
ClientSentHandshakePacketCount The number of handshake packets the client has sent (for debugging/packet-analysis)
InCookie The cookie value to send
References COOKIE_BYTE_SIZE.
SendChallengeResponse()
void StatelessConnectHandlerComponent::SendChallengeResponse (EHandshakeVersion HandshakeVersion, uint8 InSecretId, double InTimestamp, uint8 InCookie[20]) private
Constructs and sends the handshake challenge response packet, from the client to the server.
Parameters
HandshakeVersion The handshake format version to use when sending
InSecretId Which of the two server HandshakeSecret values this uses
InTimestamp The timestamp value to send
InCookie The cookie value to send
References COOKIE_BYTE_SIZE.
SendConnectChallenge()
void StatelessConnectHandlerComponent::SendConnectChallenge (FCommonSendToClientParams CommonParams, uint8 ClientSentHandshakePacketCount) private
Constructs and sends the server response to the initial connect packet, from the server to the client.
Parameters
CommonParams Common parameters for 'Send*' functions to clients
ClientSentHandshakePacketCount The number of handshake packets the client has sent (for debugging/packet-analysis)
SendInitialPacket()
void StatelessConnectHandlerComponent::SendInitialPacket (EHandshakeVersion HandshakeVersion) private
Constructs and sends the initial handshake packet, from the client to the server.
Parameters
HandshakeVersion The handshake format version to use when sending
SendRestartHandshakeRequest()
void StatelessConnectHandlerComponent::SendRestartHandshakeRequest (FCommonSendToClientParams CommonParams) private
Constructs and sends a request to resend the cookie, from the server to the client.
Parameters
CommonParams Common parameters for 'Send*' functions to clients
SendToClient()
void StatelessConnectHandlerComponent::SendToClient (FCommonSendToClientParams CommonParams, EHandshakePacketType PacketType, FBitWriter & Packet) private
Sends a packet from the server to a client.
Parameters
CommonParams Common parameters for 'Send*' functions to clients.
PacketType The type of handshake packet.
Packet The handshake packet being written.
SendToServer()
void StatelessConnectHandlerComponent::SendToServer (EHandshakeVersion HandshakeVersion, EHandshakePacketType PacketType, FBitWriter & Packet) private
Sends a packet from the client to the server.
Parameters
HandshakeVersion The handshake format version to use when sending.
PacketType The type of handshake packet.
Packet The handshake packet being written.
SendVersionUpgradeMessage()
void StatelessConnectHandlerComponent::SendVersionUpgradeMessage (FCommonSendToClientParams CommonParams) private
Constructs and sends a stateless handshake level NMT_Upgrade message.
Parameters
CommonParams Common parameters for 'Send*' functions to clients
SetDriver()
void StatelessConnectHandlerComponent::SetDriver (UNetDriver * InDriver)
Sets the net driver this handler is associated with.
Parameters
InDriver The net driver to set
SetHandshakeFailureCallback()
void StatelessConnectHandlerComponent::SetHandshakeFailureCallback (FHandshakeFailureFunc && InHandshakeFailureFunc)
Set a callback for notifying of handshake failure (clientside only).
Parameters
InHandshakeFailureFunc The callback to use for notification.
Tick()
virtual void StatelessConnectHandlerComponent::Tick (float DeltaTime) override protected virtual
References DeltaTime.
TrackValidationLogs()
bool StatelessConnectHandlerComponent::TrackValidationLogs () private
Tracks logs for invalid Session ID's, Connection ID's or Magic Header's, and limits the number of these logs.
Returns
Whether or not logging is currently allowed
UpdateSecret()
void StatelessConnectHandlerComponent::UpdateSecret () private
Generates a new HandshakeSecret value.
Field Documentation
ActiveSecret
uint8 StatelessConnectHandlerComponent::ActiveSecret private
Which of the two secret values above is active (values are changed frequently, to limit replay attacks)
Definition at line 448 of file StatelessConnectHandlerComponent.h.
AuthorisedCookie
uint8 StatelessConnectHandlerComponent::AuthorisedCookie[20] private
The cookie which completed the connection handshake.
Definition at line 514 of file StatelessConnectHandlerComponent.h.
Referenced by DoesRestartedHandshakeMatch(), and ResetChallengeData().
bRestartedHandshake
bool StatelessConnectHandlerComponent::bRestartedHandshake private
Both Serverside and Clientside variables.
Client: Whether or not we are in the middle of a restarted handshake. Server: Whether or not the last handshake was a restarted handshake.
Definition at line 511 of file StatelessConnectHandlerComponent.h.
Referenced by HasPassedChallenge(), and ResetChallengeData().
CachedClientID
uint32 StatelessConnectHandlerComponent::CachedClientID = 0 private
Cached version of the clientside per-NetDriverDefinition 'ClientID' value, for writing client connection id's.
Definition at line 532 of file StatelessConnectHandlerComponent.h.
CachedGlobalNetTravelCount
uint32 StatelessConnectHandlerComponent::CachedGlobalNetTravelCount = 0 private
Cached version of the serverside UEngine.GlobalNetTravelCount value, for writing session id's.
Definition at line 529 of file StatelessConnectHandlerComponent.h.
ClientIDSizeBits
uint32 StatelessConnectHandlerComponent::ClientIDSizeBits = 3 static constexpr private
The size of the connection id in packets (WARNING: Adjusting this is a net compatibility break)
Definition at line 538 of file StatelessConnectHandlerComponent.h.
Driver
UNetDriver* StatelessConnectHandlerComponent::Driver private
The net driver associated with this handler - for performing connectionless sends.
Definition at line 437 of file StatelessConnectHandlerComponent.h.
HandshakeFailureCallback
FHandshakeFailureFunc StatelessConnectHandlerComponent::HandshakeFailureCallback private
Callback for processing handshake failures.
Definition at line 483 of file StatelessConnectHandlerComponent.h.
HandshakeSecret
TArray<uint8> StatelessConnectHandlerComponent::HandshakeSecret[2] private
Serverside variables.
The serverside-only 'secret' value, used to help with generating cookies.
Definition at line 445 of file StatelessConnectHandlerComponent.h.
LastChallengeSuccessAddress
TSharedPtr<const FInternetAddr> StatelessConnectHandlerComponent::LastChallengeSuccessAddress private
The last address to successfully complete the handshake challenge.
Definition at line 457 of file StatelessConnectHandlerComponent.h.
Referenced by HasPassedChallenge(), and ResetChallengeData().
LastChallengeTimestamp
double StatelessConnectHandlerComponent::LastChallengeTimestamp private
The local (client) time at which the challenge was last updated.
Definition at line 493 of file StatelessConnectHandlerComponent.h.
LastClientSendTimestamp
double StatelessConnectHandlerComponent::LastClientSendTimestamp private
Clientside variables.
The last time a handshake packet was sent - used for detecting failed sends.
Definition at line 489 of file StatelessConnectHandlerComponent.h.
LastClientSequence
int32 StatelessConnectHandlerComponent::LastClientSequence private
The initial client sequence value, from the last successful handshake.
Definition at line 463 of file StatelessConnectHandlerComponent.h.
Referenced by GetChallengeSequence(), and ResetChallengeData().
LastCookie
uint8 StatelessConnectHandlerComponent::LastCookie[20] private
The Cookie value of the last challenge response sent.
Will differ from AuthorisedCookie, if a handshake retry is triggered.
Definition at line 505 of file StatelessConnectHandlerComponent.h.
LastInitTimestamp
double StatelessConnectHandlerComponent::LastInitTimestamp = 0.0 private
The time of the last post-handshake initialization.
Definition at line 454 of file StatelessConnectHandlerComponent.h.
LastRemoteHandshakeVersion
EHandshakeVersion StatelessConnectHandlerComponent::LastRemoteHandshakeVersion private
The last remote handshake version sent by the client/server.
Definition at line 526 of file StatelessConnectHandlerComponent.h.
LastRestartPacketTimestamp
double StatelessConnectHandlerComponent::LastRestartPacketTimestamp private
The local (client) time at which the last restart handshake request was received.
Definition at line 496 of file StatelessConnectHandlerComponent.h.
LastSecretId
uint8 StatelessConnectHandlerComponent::LastSecretId private
The SecretId value of the last challenge response sent.
Definition at line 499 of file StatelessConnectHandlerComponent.h.
LastSecretUpdateTimestamp
double StatelessConnectHandlerComponent::LastSecretUpdateTimestamp private
The time of the last secret value update.
Definition at line 451 of file StatelessConnectHandlerComponent.h.
LastServerSequence
int32 StatelessConnectHandlerComponent::LastServerSequence private
The initial server sequence value, from the last successful handshake.
Definition at line 460 of file StatelessConnectHandlerComponent.h.
Referenced by GetChallengeSequence(), and ResetChallengeData().
LastTimestamp
double StatelessConnectHandlerComponent::LastTimestamp private
The Timestamp value of the last challenge response sent.
Definition at line 502 of file StatelessConnectHandlerComponent.h.
LastUpgradeMessagePeriodStart
double StatelessConnectHandlerComponent::LastUpgradeMessagePeriodStart = 0.0 private
The last time an 'upgrade message' send period began.
Definition at line 477 of file StatelessConnectHandlerComponent.h.
LastValidationLogPeriodStart
double StatelessConnectHandlerComponent::LastValidationLogPeriodStart = 0.0 private
The last time an 'invalid SessionId/ClientId/MagicHeader' log period began.
Definition at line 470 of file StatelessConnectHandlerComponent.h.
MagicHeader
TBitArray StatelessConnectHandlerComponent::MagicHeader private
The magic header which is prepended to all packets.
Definition at line 517 of file StatelessConnectHandlerComponent.h.
MagicHeaderUint
uint32 StatelessConnectHandlerComponent::MagicHeaderUint = 0 private
Integer representation of the magic header, for direct comparison.
Definition at line 520 of file StatelessConnectHandlerComponent.h.
MinClientHandshakeVersion
EHandshakeVersion StatelessConnectHandlerComponent::MinClientHandshakeVersion private
The minimum supported client version, for all connections - for setting minimum bounds for the restart handshake (not aware of version)
Definition at line 466 of file StatelessConnectHandlerComponent.h.
OldPacket
FBitWriter StatelessConnectHandlerComponent::OldPacket private
Cache memory of previously used packets to avoid memory allocations.
Definition at line 440 of file StatelessConnectHandlerComponent.h.
SentHandshakePacketCount
uint8 StatelessConnectHandlerComponent::SentHandshakePacketCount = 0 private
The number of sent handshake packets, added to packets to aid packet dump debugging (may roll over)
Definition at line 523 of file StatelessConnectHandlerComponent.h.
SessionIDSizeBits
uint32 StatelessConnectHandlerComponent::SessionIDSizeBits = 2 static constexpr private
The size of the session id in packets (WARNING: Adjusting this is a net compatibility break)
Definition at line 535 of file StatelessConnectHandlerComponent.h.
UpgradeMessageCounter
uint32 StatelessConnectHandlerComponent::UpgradeMessageCounter = 0 private
The number of upgrade messages sent in the current send period (for rate limiting)
Definition at line 480 of file StatelessConnectHandlerComponent.h.
ValidationLogCounter
uint32 StatelessConnectHandlerComponent::ValidationLogCounter = 0 private
The number of 'invalid SessionId/ClientId/MagicHeader' logs in the current log period (for logspam limiting)
Definition at line 473 of file StatelessConnectHandlerComponent.h.
The documentation for this class was generated from the following file:
StatelessConnectHandlerComponent.h