Unreal Engine 5.6 C++ API: Metasound::FSharedStateShuffleManager Class Reference
Metasound::FSharedStateShuffleManager Class Reference
#include "MetasoundArrayShuffleNode.h"
Public Member Functions
void InitSharedState (uint32 InSharedStateId, int32 InSeed, int32 InNumElements)
bool NextValue (uint32 InSharedStateId, bool bAutoShuffle, int32 &OutIndex)
void ResetSeed (uint32 InSharedStateId)
void SetSeed (uint32 InSharedStateId, int32 InSeed)
void ShuffleArray (uint32 InSharedStateId)
Static Public Member Functions
static FSharedStateShuffleManager & Get ()
Private Member Functions
FSharedStateShuffleManager ()=default
~FSharedStateShuffleManager ()=default
Private Attributes
FCriticalSection CritSect
TMap< uint32, TUniquePtr< FArrayIndexShuffler > > Shufflers
Detailed Description
Definition at line 80 of file MetasoundArrayShuffleNode.h.
Constructor & Destructor Documentation
FSharedStateShuffleManager()
Metasound::FSharedStateShuffleManager::FSharedStateShuffleManager () private default
Referenced by Get().
~FSharedStateShuffleManager()
Metasound::FSharedStateShuffleManager::~FSharedStateShuffleManager () private default
Member Function Documentation
Get()
FSharedStateShuffleManager & Metasound::FSharedStateShuffleManager::Get () inline static
Definition at line 83 of file MetasoundArrayShuffleNode.h.
References FSharedStateShuffleManager().
Referenced by Metasound::TArrayShuffleOperator< ArrayType >::GetNextIndex(), Metasound::TArrayShuffleOperator< ArrayType >::InitializeShufflers(), Metasound::TArrayShuffleOperator< ArrayType >::Reset(), Metasound::TArrayShuffleOperator< ArrayType >::Seed(), and Metasound::TArrayShuffleOperator< ArrayType >::Shuffle().
InitSharedState()
void Metasound::FSharedStateShuffleManager::InitSharedState (uint32 InSharedStateId, int32 InSeed, int32 InNumElements) inline
Definition at line 89 of file MetasoundArrayShuffleNode.h.
References CritSect, MakeUnique(), and Shufflers.
Referenced by Metasound::TArrayShuffleOperator< ArrayType >::InitializeShufflers().
NextValue()
bool Metasound::FSharedStateShuffleManager::NextValue (uint32 InSharedStateId, bool bAutoShuffle, int32 & OutIndex) inline
Definition at line 99 of file MetasoundArrayShuffleNode.h.
References CritSect, and Shufflers.
Referenced by Metasound::TArrayShuffleOperator< ArrayType >::GetNextIndex().
ResetSeed()
void Metasound::FSharedStateShuffleManager::ResetSeed (uint32 InSharedStateId) inline
Definition at line 113 of file MetasoundArrayShuffleNode.h.
References CritSect, and Shufflers.
Referenced by Metasound::TArrayShuffleOperator< ArrayType >::Reset().
SetSeed()
void Metasound::FSharedStateShuffleManager::SetSeed (uint32 InSharedStateId, int32 InSeed) inline
Definition at line 106 of file MetasoundArrayShuffleNode.h.
References CritSect, and Shufflers.
Referenced by Metasound::TArrayShuffleOperator< ArrayType >::Seed().
ShuffleArray()
void Metasound::FSharedStateShuffleManager::ShuffleArray (uint32 InSharedStateId) inline
Definition at line 120 of file MetasoundArrayShuffleNode.h.
References CritSect, and Shufflers.
Referenced by Metasound::TArrayShuffleOperator< ArrayType >::Shuffle().
Field Documentation
CritSect
FCriticalSection Metasound::FSharedStateShuffleManager::CritSect private
Definition at line 131 of file MetasoundArrayShuffleNode.h.
Referenced by InitSharedState(), NextValue(), ResetSeed(), SetSeed(), and ShuffleArray().
Shufflers
TMap<uint32, TUniquePtr<FArrayIndexShuffler> > Metasound::FSharedStateShuffleManager::Shufflers private
Definition at line 133 of file MetasoundArrayShuffleNode.h.
Referenced by InitSharedState(), NextValue(), ResetSeed(), SetSeed(), and ShuffleArray().
The documentation for this class was generated from the following file:
MetasoundArrayShuffleNode.h