Unreal Engine 5.6 C++ API: FCbAttachment Class Reference
FCbAttachment Class Reference
An attachment is either null, raw binary, compressed binary, or an object.
#include "CompactBinaryPackage.h"
Data Structures
struct FBinaryValue
struct FCompressedBinaryValue
struct FObjectValue
Public Member Functions
FCbAttachment ()=default
Construct a null attachment.
template<typename BufferType, decltype(FBinaryValue(DeclVal< BufferType >().MakeOwned())) * = nullptr>
FCbAttachment (BufferType &&InValue)
Construct a raw binary attachment from a shared/composite buffer.
template<typename BufferType, decltype(FBinaryValue(DeclVal< BufferType >().MakeOwned())) * = nullptr>
FCbAttachment (BufferType &&InValue, const FIoHash &InHash)
FCbAttachment (const FCbObject &InValue)
Construct an object attachment.
FCbAttachment (const FCbObject &InValue, const FIoHash &Hash)
FCbAttachment (const FCompressedBuffer &InValue)
Construct a compressed binary attachment.
UE_INTERNAL FCbAttachment (const FCompressedBuffer &InValue, const FIoHash &Hash)
FCbAttachment (FCbObject &&InValue)
FCbAttachment (FCbObject &&InValue, const FIoHash &Hash)
FCbAttachment (FCompressedBuffer &&InValue)
UE_INTERNAL FCbAttachment (FCompressedBuffer &&InValue, const FIoHash &Hash)
FSharedBuffer AsBinary () const
Access the attachment as raw binary in a single contiguous buffer.
const FCompositeBuffer & AsCompositeBinary () const
Access the attachment as raw binary.
const FCompressedBuffer & AsCompressedBinary () const
Access the attachment as compressed binary.
FCbObject AsObject () const
Access the attachment as an object.
FIoHash GetHash () const
Returns the hash of the attachment value.
bool IsBinary () const
Returns whether the attachment is raw binary.
bool IsCompressedBinary () const
Returns whether the attachment is compressed binary.
bool IsNull () const
Whether the attachment has a null value.
bool IsObject () const
Returns whether the attachment is an object.
operator bool () const
Whether the attachment has a non-null value.
bool operator!= (const FCbAttachment &Attachment) const
bool operator< (const FCbAttachment &Attachment) const
bool operator== (const FCbAttachment &Attachment) const
Compares attachments by their hash.
void Reset ()
Reset this to a null attachment.
void Save (FArchive &Ar) const
Save the attachment into the archive as a stream of compact binary fields.
void Save (FCbWriter &Writer) const
Save the attachment into the writer as a stream of compact binary fields.
bool TryLoad (FArchive &Ar, FCbBufferAllocator Allocator=FUniqueBuffer::Alloc)
Load the attachment from compact binary as written by Save.
bool TryLoad (FCbFieldIterator &Fields)
Load the attachment from compact binary as written by Save.
Private Member Functions
template<typename... ArgTypes, decltype(FBinaryValue(DeclVal< ArgTypes >()...)) * = nullptr>
FCbAttachment (TInPlaceType< FBinaryValue >, ArgTypes &&... Args)
Private Attributes
TVariant< TYPE_OF_NULLPTR, FObjectValue, FBinaryValue, FCompressedBinaryValue > Value
Detailed Description
An attachment is either null, raw binary, compressed binary, or an object.
Attachments are always identified by their raw hash, even when stored compressed.
An attachment is serialized as a sequence of compact binary fields with no name. It is invalid to serialize a null attachment. A raw binary attachment is serialized as an empty Binary field when empty, and otherwise as a BinaryAttachment field containing the raw hash, followed by the raw binary data in a Binary field. A compressed binary attachment is serialized as Binary with a compressed buffer as the value. An object is serialized as an empty Object field when empty, and otherwise as an ObjectAttachment field containing the hash, followed by the object data in an Object field.
Definition at line 37 of file CompactBinaryPackage.h.
Constructor & Destructor Documentation
FCbAttachment() [1/12]
template<typename... ArgTypes, decltype(FBinaryValue(DeclVal< ArgTypes >()...)) * = nullptr> FCbAttachment::FCbAttachment (TInPlaceType< FBinaryValue > , ArgTypes &&... Args) inline private
Definition at line 89 of file CompactBinaryPackage.h.
References FCbAttachment::FBinaryValue::Buffer, Forward(), FCompositeBuffer::IsNull(), and Value.
Referenced by FCbAttachment(), FCbAttachment(), operator!=(), operator<(), and operator==().
FCbAttachment() [2/12]
FCbAttachment::FCbAttachment () default
Construct a null attachment.
Referenced by Reset().
FCbAttachment() [3/12]
FCbAttachment::FCbAttachment (const FCbObject & InValue) inline explicit
Construct an object attachment.
Value is cloned if not owned.
Definition at line 103 of file CompactBinaryPackage.h.
References Value.
FCbAttachment() [4/12]
FCbAttachment::FCbAttachment (FCbObject && InValue) inline explicit
Definition at line 105 of file CompactBinaryPackage.h.
References MoveTemp(), and Value.
FCbAttachment() [5/12]
FCbAttachment::FCbAttachment (const FCbObject & InValue, const FIoHash & Hash) inline explicit
Definition at line 107 of file CompactBinaryPackage.h.
References Hash, and Value.
FCbAttachment() [6/12]
FCbAttachment::FCbAttachment (FCbObject && InValue, const FIoHash & Hash) inline explicit
Definition at line 109 of file CompactBinaryPackage.h.
References Hash, MoveTemp(), and Value.
FCbAttachment() [7/12]
template<typename BufferType, decltype(FBinaryValue(DeclVal< BufferType >().MakeOwned())) * = nullptr> FCbAttachment::FCbAttachment (BufferType && InValue) inline explicit
Construct a raw binary attachment from a shared/composite buffer.
Value is cloned if not owned.
Definition at line 114 of file CompactBinaryPackage.h.
References FCbAttachment(), and Forward().
FCbAttachment() [8/12]
template<typename BufferType, decltype(FBinaryValue(DeclVal< BufferType >().MakeOwned())) * = nullptr> FCbAttachment::FCbAttachment (BufferType && InValue, const FIoHash & InHash) inline explicit
Definition at line 117 of file CompactBinaryPackage.h.
References FCbAttachment(), and Forward().
FCbAttachment() [9/12]
FCbAttachment::FCbAttachment (const FCompressedBuffer & InValue) inline explicit
Construct a compressed binary attachment.
Value is cloned if not owned.
Definition at line 121 of file CompactBinaryPackage.h.
References FCbAttachment::FCompressedBinaryValue::Buffer, FCompressedBuffer::IsNull(), and Value.
FCbAttachment() [10/12]
UE_INTERNAL FCbAttachment::FCbAttachment (const FCompressedBuffer & InValue, const FIoHash & Hash) inline explicit
Definition at line 130 of file CompactBinaryPackage.h.
References FCbAttachment::FCompressedBinaryValue::Buffer, Hash, FCompressedBuffer::IsNull(), UE_INTERNAL, and Value.
FCbAttachment() [11/12]
FCbAttachment::FCbAttachment (FCompressedBuffer && InValue) inline explicit
Definition at line 139 of file CompactBinaryPackage.h.
References FCbAttachment::FCompressedBinaryValue::Buffer, FCompressedBuffer::IsNull(), and Value.
FCbAttachment() [12/12]
UE_INTERNAL FCbAttachment::FCbAttachment (FCompressedBuffer && InValue, const FIoHash & Hash) inline explicit
Definition at line 148 of file CompactBinaryPackage.h.
References FCbAttachment::FCompressedBinaryValue::Buffer, Hash, FCompressedBuffer::IsNull(), UE_INTERNAL, and Value.
Member Function Documentation
AsBinary()
FSharedBuffer FCbAttachment::AsBinary () const inline
Access the attachment as raw binary in a single contiguous buffer.
Defaults to a null buffer on error.
Definition at line 463 of file CompactBinaryPackage.h.
References Value.
AsCompositeBinary()
const FCompositeBuffer & FCbAttachment::AsCompositeBinary () const inline
Access the attachment as raw binary.
Defaults to a null buffer on error.
Definition at line 472 of file CompactBinaryPackage.h.
References FCompositeBuffer::Null, and Value.
AsCompressedBinary()
const FCompressedBuffer & FCbAttachment::AsCompressedBinary () const inline
Access the attachment as compressed binary.
Defaults to a null buffer on error.
Definition at line 481 of file CompactBinaryPackage.h.
References FCompressedBuffer::Null, and Value.
AsObject()
FCbObject FCbAttachment::AsObject () const inline
Access the attachment as an object.
Defaults to an empty object on error.
Definition at line 454 of file CompactBinaryPackage.h.
References Value.
GetHash()
FIoHash FCbAttachment::GetHash () const
Returns the hash of the attachment value.
Referenced by FCbPackage::FindAttachment(), GetTypeHash(), operator!=(), operator<(), operator==(), and FCbPackage::RemoveAttachment().
IsBinary()
bool FCbAttachment::IsBinary () const inline
Returns whether the attachment is raw binary.
Definition at line 182 of file CompactBinaryPackage.h.
References Value.
IsCompressedBinary()
bool FCbAttachment::IsCompressedBinary () const inline
Returns whether the attachment is compressed binary.
Definition at line 185 of file CompactBinaryPackage.h.
References Value.
IsNull()
bool FCbAttachment::IsNull () const inline
Whether the attachment has a null value.
Definition at line 176 of file CompactBinaryPackage.h.
References Value.
Referenced by operator bool().
IsObject()
bool FCbAttachment::IsObject () const inline
Returns whether the attachment is an object.
Definition at line 179 of file CompactBinaryPackage.h.
References Value.
operator bool()
FCbAttachment::operator bool () const inline explicit
Whether the attachment has a non-null value.
Definition at line 173 of file CompactBinaryPackage.h.
References IsNull().
operator!=()
bool FCbAttachment::operator!= (const FCbAttachment & Attachment) const inline
Definition at line 192 of file CompactBinaryPackage.h.
References FCbAttachment(), and GetHash().
operator<()
bool FCbAttachment::operator< (const FCbAttachment & Attachment) const inline
Definition at line 193 of file CompactBinaryPackage.h.
References FCbAttachment(), and GetHash().
operator==()
bool FCbAttachment::operator== (const FCbAttachment & Attachment) const inline
Compares attachments by their hash.
Any discrepancy in type must be handled externally.
Definition at line 191 of file CompactBinaryPackage.h.
References FCbAttachment(), and GetHash().
Reset()
void FCbAttachment::Reset () inline
Reset this to a null attachment.
Definition at line 158 of file CompactBinaryPackage.h.
References FCbAttachment().
Save() [1/2]
void FCbAttachment::Save (FArchive & Ar) const
Save the attachment into the archive as a stream of compact binary fields.
References Ar.
Save() [2/2]
void FCbAttachment::Save (FCbWriter & Writer) const
Save the attachment into the writer as a stream of compact binary fields.
TryLoad() [1/2]
bool FCbAttachment::TryLoad (FArchive & Ar, FCbBufferAllocator Allocator = FUniqueBuffer::Alloc)
Load the attachment from compact binary as written by Save.
The attachments value will be loaded into an owned buffer.
Parameters
Ar Archive to read the attachment from. An error state is set on failure.
Allocator Allocator for the attachment value buffer.
Note
Allocated buffers will be cloned if they are not owned.
References FUniqueBuffer::Alloc(), Allocator, and Ar.
TryLoad() [2/2]
bool FCbAttachment::TryLoad (FCbFieldIterator & Fields)
Load the attachment from compact binary as written by Save.
The attachment references the input iterator if it is owned, and otherwise clones the value.
The iterator is advanced as attachment fields are consumed from it.
Field Documentation
Value
TVariant<TYPE_OF_NULLPTR, FObjectValue, FBinaryValue, FCompressedBinaryValue> FCbAttachment::Value private
Definition at line 222 of file CompactBinaryPackage.h.
Referenced by FCbAttachment(), FCbAttachment(), FCbAttachment(), FCbAttachment(), FCbAttachment(), FCbAttachment(), FCbAttachment(), FCbAttachment(), FCbAttachment(), AsBinary(), AsCompositeBinary(), AsCompressedBinary(), AsObject(), IsBinary(), IsCompressedBinary(), IsNull(), and IsObject().
The documentation for this class was generated from the following file:
CompactBinaryPackage.h