Unreal Engine 5.6 C++ API: UE::Slate Namespace Reference
UE::Slate Namespace Reference
Namespaces
namespace Containers
namespace ItemsSource
namespace PrioritizedWrapBox
Types specific to SlimWrappingToolBar (and it's variants).
namespace Private
Data Structures
struct FDeprecateBox2D
Structure for deprecating FBox2D to FBox2f.
struct FDeprecateOptionalVector2DParameter
Defines an optional Slate vector parameter in a similar vein to FDeprecateVector2DParameter NOTE: DO NOT USE THIS TYPE DIRECTLY IN CLIENT CODE - ALL USAGES SHOULD USE FVector2f or float.
struct FDeprecateSlateVectorPtrVariant
struct FDeprecateVector2DParameter
Defines a Slate vector used as a function parameter that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
struct TSlotAccessor
A wrapper for accessing slot parameters for a given SlotType.
struct TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >
Specialization for FSlotProxy (and derived).
struct TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< TBasicLayoutWidgetSlot< SlotType >, std::decay_t< SlotType > > &&std::is_base_of_v< TResizingWidgetSlotMixin< SlotType >, std::decay_t< SlotType > > > >
struct TSlotIterator
struct TSlotIterator< SlotType, std::enable_if_t< std::is_base_of_v< FSlotBase, std::decay_t< SlotType > > > >
struct TSlotIterator< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >
Typedefs
using FDeprecateVector2DResult = FDeprecateSlateVector2D
Defines a return value or persistent member variable that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
Functions
static FORCEINLINE FBox2f CastToBox2f (const FBox2d &InValue)
const FVector2f & CastToVector2f (const FDeprecateSlateVector2D &InValue)
const FVector2f & CastToVector2f (const FDeprecateVector2DParameter &InValue)
FVector2f CastToVector2f (const FIntPoint &InValue)
FVector2f CastToVector2f (const FVector2d &InValue)
const FVector2f & CastToVector2f (const FVector2f &InValue)
CastToVector2f allows supported types to be explicitly coerced to an FVector2f or const FVector2f& This allows generic programming patterns that must operate on FVector2f given many input types.
template<typename IndexType, std::size_t Num, typename Indices = std::make_integer_sequence<IndexType, Num>>
auto MakeTupleIndicies ()
template<typename IndexType, IndexType... Indices>
auto MakeTupleIndiciesInner (std::integer_sequence< IndexType, Indices... >)
Typedef Documentation
FDeprecateVector2DResult
using UE::Slate::FDeprecateVector2DResult = FDeprecateSlateVector2D
Defines a return value or persistent member variable that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
Once deprecated completely, usages will be converted to using FVector2f directly. It is not (and will never be) constructible from double precision types.
This type is implicitly convertible to FVector2D, and can be operated on as if it were an FVector2D, but will emit deprecation warnings under these situations where UE_REPORT_SLATE_VECTOR_DEPRECATION is enabled.
This type should not be used as a parameter, where FDeprecateVector2DParameter is preferred due to its implicit conversion from many types, and separate deprecation mechanisms.
NOTE: DO NOT USE THIS TYPE DIRECTLY IN CLIENT CODE - ALL USAGES SHOULD USE FVector2f or float
Definition at line 469 of file SlateVector2.h.
Function Documentation
CastToBox2f()
FORCEINLINE FBox2f UE::Slate::CastToBox2f (const FBox2d & InValue) static
Definition at line 10 of file SlateBox2.h.
References FORCEINLINE.
Referenced by UE::Slate::FDeprecateBox2D::operator!=(), and UE::Slate::FDeprecateBox2D::operator==().
CastToVector2f() [1/5]
const FVector2f & UE::Slate::CastToVector2f (const FDeprecateSlateVector2D & InValue) inline
Definition at line 552 of file SlateVector2.h.
CastToVector2f() [2/5]
const FVector2f & UE::Slate::CastToVector2f (const FDeprecateVector2DParameter & InValue) inline
Definition at line 557 of file SlateVector2.h.
CastToVector2f() [3/5]
FVector2f UE::Slate::CastToVector2f (const FIntPoint & InValue) inline
Definition at line 547 of file SlateVector2.h.
CastToVector2f() [4/5]
FVector2f UE::Slate::CastToVector2f (const FVector2d & InValue) inline
Definition at line 595 of file SlateVector2.h.
References ensureAlways, FMath::IsNearlyEqual(), UE_REAL_TO_FLOAT, UE::Math::TVector2< T >::X, X, Y, and UE::Math::TVector2< T >::Y.
CastToVector2f() [5/5]
const FVector2f & UE::Slate::CastToVector2f (const FVector2f & InValue) inline
CastToVector2f allows supported types to be explicitly coerced to an FVector2f or const FVector2f& This allows generic programming patterns that must operate on FVector2f given many input types.
Definition at line 591 of file SlateVector2.h.
Referenced by UE::Slate::FDeprecateOptionalVector2DParameter::FDeprecateOptionalVector2DParameter(), FSlateStyleSet::Add(), SNodePanel::SNode::GetDesiredSizeForMarquee2f(), SGraphEditor::GetPasteLocation2f(), SWidget::GetRenderTransformPivot(), SWidget::GetRenderTransformPivotWithRespectToFlowDirection(), SNodePanel::SNode::FNodeSlot::UE_DEPRECATED(), SNodePanel::SNode::FNodeSlot::UE_DEPRECATED(), SNodePanel::SNode::UE_DEPRECATED(), USTRUCT(), and USTRUCT().
MakeTupleIndicies()
template<typename IndexType, std::size_t Num, typename Indices = std::make_integer_sequence<IndexType, Num>> auto UE::Slate::MakeTupleIndicies ()
Definition at line 445 of file RenderingCommon.h.
References MakeTupleIndiciesInner().
MakeTupleIndiciesInner()
template<typename IndexType, IndexType... Indices> auto UE::Slate::MakeTupleIndiciesInner (std::integer_sequence< IndexType, Indices... >)
Definition at line 439 of file RenderingCommon.h.
References MakeTuple().
Referenced by MakeTupleIndicies().