Unreal Engine 5.6 C++ API: FLandscapeTextureStorageMipProvider Class Reference
FLandscapeTextureStorageMipProvider Class Reference
#include "LandscapeTextureStorageProvider.h"
Data Structures
struct FIORequest
Public Member Functions
FLandscapeTextureStorageMipProvider (ULandscapeTextureStorageProviderFactory *InFactory)
~FLandscapeTextureStorageMipProvider ()
void AbortPollMips () final override
Abort anything that could be stalling the update in PollMips().
void Cancel (const FTextureUpdateSyncOptions &SyncOptions) final override
Cancel the progression and release any temporary resources.
void CleanUp (const FTextureUpdateSyncOptions &SyncOptions) final override
Release any temporary data and objects that where used for the update.
ETickThread GetCancelThread () const final override
int32 GetMips (const FTextureUpdateContext &Context, int32 StartingMipIndex, const FTextureMipInfoArray &MipInfos, const FTextureUpdateSyncOptions &SyncOptions) final override
Acquire the mips this provider will handle.
void Init (const FTextureUpdateContext &Context, const FTextureUpdateSyncOptions &SyncOptions) final override
Initialize data prelimary to the GetMips() step.
bool PollMips (const FTextureUpdateSyncOptions &SyncOptions) final override
Check if each mip handled by this mip data provider have been updated correctly.
Public Member Functions inherited from FTextureMipDataProvider
FTextureMipDataProvider (const UTexture *Texture, ETickState InTickState, ETickThread InTickThread)
virtual ~FTextureMipDataProvider ()
virtual void AbortPostprocessGPUMipData ()
Abort anything that could be stalling the update in PostprocessGPUMipData().
FORCEINLINE ETickState GetNextTickState () const
FORCEINLINE ETickThread GetNextTickThread () const
virtual bool PostprocessGPUMipData (const FTextureUpdateContext &Context, const FTextureRHIRef &TextureRHI, int32 FirstMip, int32 NumMips, const FTextureUpdateSyncOptions &SyncOptions)
UE_DEPRECATED (5.7, "Implement the version that takes FirstMip and NumMips.") virtual bool PostprocessGPUMipData(const FTextureUpdateContext &Context
Private Member Functions
void ClearIORequests ()
void CreateAsyncFileCallback (const FTextureUpdateSyncOptions &SyncOptions)
Private Attributes
FBulkDataIORequestCallBack AsyncFileCallBack
bool bIORequestAborted = false
bool bIORequestCancelled = false
bool bPrioritizedIORequest = false
FTextureMipInfoArray DestMipInfos
ULandscapeTextureStorageProviderFactory * Factory = nullptr
int32 FirstRequestedMipIndex = INDEX_NONE
TArray< FIORequest, TInlineAllocator< MAX_TEXTURE_MIP_COUNT > > IORequests
FName TextureName
Additional Inherited Members
Public Types inherited from FTextureMipDataProvider
enum class ETickState : uint32 {
Init , GetMips , PollMips , PostprocessGPUMipData ,
CleanUp , Done
}
enum class ETickThread : uint32 { Async , Render , None }
Data Fields inherited from FTextureMipDataProvider
const FTextureRHIRef & NewTextureRHI
const FTextureRHIRef const FTextureUpdateSyncOptions & SyncOptions { return true
Protected Member Functions inherited from FTextureMipDataProvider
FORCEINLINE void AdvanceTo (ETickState InState, ETickThread InThread)
Protected Attributes inherited from FTextureMipDataProvider
const int32 CurrentFirstLODIdx = INDEX_NONE
const int32 PendingFirstLODIdx = INDEX_NONE
const FStreamableRenderResourceState ResourceState
The streamable state requested.
Detailed Description
Definition at line 39 of file LandscapeTextureStorageProvider.h.
Constructor & Destructor Documentation
FLandscapeTextureStorageMipProvider()
FLandscapeTextureStorageMipProvider::FLandscapeTextureStorageMipProvider (ULandscapeTextureStorageProviderFactory * InFactory)
~FLandscapeTextureStorageMipProvider()
FLandscapeTextureStorageMipProvider::~FLandscapeTextureStorageMipProvider ()
Member Function Documentation
AbortPollMips()
void FLandscapeTextureStorageMipProvider::AbortPollMips () final override virtual
Abort anything that could be stalling the update in PollMips().
Called from an async task. Expected behavior is to cancel any pending IO operations. Called when the FTextureStreamIn update is canceled and the current step is to be waiting on upon PollMips(). This is because Cancel() can only be executed when any pending operations are completed (see FTextureUpdateSyncOptions). Will be used if executing PollMips
Reimplemented from FTextureMipDataProvider.
Cancel()
void FLandscapeTextureStorageMipProvider::Cancel (const FTextureUpdateSyncOptions & SyncOptions) final override virtual
Cancel the progression and release any temporary resources.
Called within the FTextureStreamIn update when the stream in request is aborted or cannot complete correctly The Cancel() function is called on the thread returned by GetCancelThread().
Parameters
SyncOptions - Different sync options to control when the next tick of FTextureStreamIn can be scheduled.
Implements FTextureMipDataProvider.
References Cancel(), and FTextureMipDataProvider::SyncOptions.
Referenced by Cancel().
CleanUp()
void FLandscapeTextureStorageMipProvider::CleanUp (const FTextureUpdateSyncOptions & SyncOptions) final override virtual
Release any temporary data and objects that where used for the update.
Final step executed after the texture has been updated correctly.
Parameters
SyncOptions - Different sync options to control when the next tick of FTextureStreamIn can be scheduled.
Implements FTextureMipDataProvider.
References CleanUp(), and FTextureMipDataProvider::SyncOptions.
Referenced by CleanUp().
ClearIORequests()
void FLandscapeTextureStorageMipProvider::ClearIORequests () private
CreateAsyncFileCallback()
void FLandscapeTextureStorageMipProvider::CreateAsyncFileCallback (const FTextureUpdateSyncOptions & SyncOptions) private
References FTextureMipDataProvider::SyncOptions.
GetCancelThread()
ETickThread FLandscapeTextureStorageMipProvider::GetCancelThread () const final override virtual
Implements FTextureMipDataProvider.
References GetCancelThread().
Referenced by GetCancelThread().
GetMips()
int32 FLandscapeTextureStorageMipProvider::GetMips (const FTextureUpdateContext & Context, int32 StartingMipIndex, const FTextureMipInfoArray & MipInfos, const FTextureUpdateSyncOptions & SyncOptions) final override virtual
Acquire the mips this provider will handle.
Non handled mips must be handled by the next mip data provider or the update will be cancelled altogether. GetMips() must typically advance to PollMips() if it wants to be able to notify FTextureStreamIn that something went wrong and that the update must be cancelled.
Parameters
Context - An update context constant throughout the FTextureStreamIn update. Gives things like which texture asset is updated and what mips are streamed in.
StartingMipIndex - The current starting mip index, somewhere between FTextureUpdateContext::PendingFirstMipIndex and FTextureUpdateContext::CurrentFirstMipIndex inclusively.
MipInfos - The array of FTextureMipInfo that hold the information relative to each mip for which data must be provided.
SyncOptions - Different sync options to control when the next tick of FTextureStreamIn can be scheduled.
Return the next value StartingMipIndex (for the next provider). Must be FTextureUpdateContext::CurrentFirstMipIndex to indicate that all mips have been handled.
Implements FTextureMipDataProvider.
References FTextureMipDataProvider::SyncOptions.
Init()
void FLandscapeTextureStorageMipProvider::Init (const FTextureUpdateContext & Context, const FTextureUpdateSyncOptions & SyncOptions) final override virtual
Initialize data prelimary to the GetMips() step.
Can be called several time (it does not have to advance to GetMips immediately). Mostly useful to simplify the logic in GetMips(). This is because GetMips is a chained call between all mip data providers, each taking some mips to handle, and is not compatible with multi step process. This means that GetMips() must return immediately and can not postpone or delay return by not advancing to the next steps.
Parameters
Context - An update context constant throughout the FTextureStreamIn update. Gives things like which texture asset is updated and what mips are streamed in.
SyncOptions - Different sync options to control when the next tick of FTextureStreamIn can be scheduled.
Implements FTextureMipDataProvider.
References FTextureMipDataProvider::SyncOptions.
PollMips()
bool FLandscapeTextureStorageMipProvider::PollMips (const FTextureUpdateSyncOptions & SyncOptions) final override virtual
Check if each mip handled by this mip data provider have been updated correctly.
Must move to CleanUp() or Done() when done.
Parameters
SyncOptions - Different sync options to control when the next tick of FTextureStreamIn can be scheduled.
Return true unless the texture update needs to be aborted because the mip won't be updated correctly (for example IO error).
Implements FTextureMipDataProvider.
References FTextureMipDataProvider::SyncOptions.
Field Documentation
AsyncFileCallBack
FBulkDataIORequestCallBack FLandscapeTextureStorageMipProvider::AsyncFileCallBack private
Definition at line 87 of file LandscapeTextureStorageProvider.h.
bIORequestAborted
bool FLandscapeTextureStorageMipProvider::bIORequestAborted = false private
Definition at line 84 of file LandscapeTextureStorageProvider.h.
bIORequestCancelled
bool FLandscapeTextureStorageMipProvider::bIORequestCancelled = false private
Definition at line 82 of file LandscapeTextureStorageProvider.h.
bPrioritizedIORequest
bool FLandscapeTextureStorageMipProvider::bPrioritizedIORequest = false private
Definition at line 80 of file LandscapeTextureStorageProvider.h.
DestMipInfos
FTextureMipInfoArray FLandscapeTextureStorageMipProvider::DestMipInfos private
Definition at line 73 of file LandscapeTextureStorageProvider.h.
Factory
ULandscapeTextureStorageProviderFactory* FLandscapeTextureStorageMipProvider::Factory = nullptr private
Definition at line 59 of file LandscapeTextureStorageProvider.h.
FirstRequestedMipIndex
int32 FLandscapeTextureStorageMipProvider::FirstRequestedMipIndex = INDEX_NONE private
Definition at line 75 of file LandscapeTextureStorageProvider.h.
IORequests
TArray<FIORequest, TInlineAllocator<MAX_TEXTURE_MIP_COUNT> > FLandscapeTextureStorageMipProvider::IORequests private
Definition at line 70 of file LandscapeTextureStorageProvider.h.
TextureName
FName FLandscapeTextureStorageMipProvider::TextureName private
Definition at line 78 of file LandscapeTextureStorageProvider.h.
The documentation for this class was generated from the following file:
LandscapeTextureStorageProvider.h