Unreal Engine 5.6 C++ API: UActorComponent Class Reference
UActorComponent Class Reference
#include "ActorComponent.h"
Public Member Functions
virtual void AddAssetUserData (UAssetUserData *InUserData) override
virtual UObject const * AdditionalStatObject () const
Give a readable name for this component, including asset name if applicable.
void AddReplicatedSubObject (UObject *SubObject, ELifetimeCondition NetCondition=COND_None)
Register a SubObject that will get replicated along with the actor component.
FORCEINLINE bool AllowReregistration () const
Check whether the component class allows reregistration during ReregisterAllComponents.
virtual bool AllowsAsyncPhysicsStateCreation () const
Returns whether this component allows having its physics state being created asynchronously (outside of the GameThread).
virtual bool AllowsAsyncPhysicsStateDestruction () const
Returns whether this component allows having its physics state being destroyed asynchronously (outside of the GameThread).
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift)
Called by owner actor on position shifting Component should update all relevant data structures to reflect new actor location.
virtual void AsyncPhysicsTickComponent (float DeltaTime, float SimTime)
Override this function to implement custom logic to be executed every physics step.
virtual void BeginDestroy () override
Called before destroying the object.
virtual void BeginPlay ()
Begins Play for the component.
virtual bool CallRemoteFunction (UFunction *Function, void *Parameters, FOutParmRec *OutParms, FFrame *Stack) override
Call the actor's function remotely.
virtual bool CanEditChange (const FProperty *InProperty) const override
Called by the editor to query whether a property of this object is allowed to be modified.
bool CanEverAffectNavigation () const
Can this component potentially influence navigation.
virtual void CheckForErrors ()
Function that gets called from within Map_Check to allow this actor component to check itself for any potential errors and register them with map check dialog.
void ClearNeedEndOfFrameUpdate ()
If we belong to a world, clear the request to do a deferred update.
void ClearUCSModifiedProperties ()
Clears the component's UCS modified properties.
bool ComponentIsInLevel (const class ULevel *TestLevel) const
Returns true if this actor is contained by TestLevel.
bool ComponentIsInPersistentLevel (bool bIncludeLevelStreamingPersistent) const
See if this component is in the persistent level.
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const
Override to allow a component subclass to compute an hash for the purpose of HLOD generation.
void CreatePhysicsState (bool bAllowDeferral=false)
Create any physics engine information for this component.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMarkRenderStateDirty, UActorComponent &)
virtual void DestroyComponent (bool bPromoteChildren=false)
Unregister the component, remove it from its outer Actor's Components array and mark for pending kill.
void DestroyPhysicsState ()
Shut down any physics engine structure for this component.
void DestroyReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels to delete the replica of this subobject next time the Actor gets replicated Note it is up to the caller to delete the local object on the authority.
void DetermineUCSModifiedProperties ()
Initializes the list of properties that are modified by the UserConstructionScript.
void DoDeferredRenderUpdates_Concurrent ()
Uses the bRenderStateDirty/bRenderTransformDirty/bRenderInstancesDirty to perform any necessary work on this component.
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason)
Ends gameplay for this component.
virtual bool ForceActorNoDataLayers () const
virtual bool ForceActorNonSpatiallyLoaded () const
virtual void GetActorDescProperties (FPropertyPairsMap &PropertyPairsMap) const
Add properties to the component owner's actor desc.
virtual const TArray< UAssetUserData * > * GetAssetUserDataArray () const override
virtual UAssetUserData * GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual UObject * GetAsyncPhysicsStateObject () const override final
Returns the associated UObject for this processor.
virtual void GetComponentChildElements (TArray< FTypedElementHandle > &OutElementHandles, const bool bAllowCreate=true)
Get the logical child elements of this component, if any.
virtual bool GetComponentClassCanReplicate () const
Returns true if this type of component can ever replicate, override to disable the default behavior.
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const
Called before we throw away components during RerunConstructionScripts, to cache any data we wish to persist across that operation.
ULevel * GetComponentLevel () const
Return the ULevel that this Component is part of.
virtual TSharedPtr< SWidget > GetCustomEditorPreviewWidget ()
If this component is set up to provide a preview window in editor (see GetEditorPreviewInfo), you can use this to customize the preview (to be something other than a world viewport).
virtual TSubclassOf< class UHLODBuilder > GetCustomHLODBuilderClass () const
Return the custom HLODBuilder class that should be used to generate HLODs for components of this type.
virtual bool GetEditorPreviewInfo (float DeltaTime, FMinimalViewInfo &ViewOut)
Supplies the editor with a view specific to this component (think a view from a camera components POV, a render, etc.).
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack) override
Return the space this function should be called.
virtual TArray< UActorComponent * > GetHLODProxyComponents () const
Override to provide a custom set of components to be used in place of the current component for the HLOD generation.
FORCEINLINE bool GetIsReplicated () const
Returns whether replication is enabled or not.
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
Returns properties that are replicated for the lifetime of the actor channel.
uint32 GetMarkedForEndOfFrameUpdateState () const
Tracks whether the component has been added to one of the world's end of frame update lists.
uint32 GetMarkedForPreEndOfFrameSync () const
Tracks whether the component has been added to one of the world's end of frame update lists.
ENetMode GetNetMode () const
Get the network mode (dedicated server, client, standalone, etc) for this component.
template<class T>
T * GetOwner () const
Templated version of GetOwner(), will return nullptr if cast fails.
ENetRole GetOwnerRole () const
Get the network role of the Owner, or ROLE_None if there is no owner.
virtual FString GetReadableName () const
Returns a readable name for this component, including the asset name if applicable By default this appends a space plus AdditionalStatObject()
virtual ELifetimeCondition GetReplicationCondition () const
Returns the replication condition for the component.
class FSceneInterface * GetScene () const
Returns the rendering scene associated with this component.
virtual FBox GetStreamingBounds () const
virtual FBox GetStreamingBoundsEditor () const
void GetUCSModifiedProperties (TSet< const FProperty * > &ModifiedProperties) const
Returns the list of properties that are modified by the UserConstructionScript.
int32 GetUCSSerializationIndex () const
Returns the UCS serialization index.
virtual UWorld * GetWorld () const override final
Getter for the cached world pointer, will return null if the component is not actually spawned in a level.
bool HasBeenCreated () const
Indicates that OnCreatedComponent has been called, but OnDestroyedComponent has not yet.
bool HasBeenInitialized () const
Indicates that InitializeComponent has been called, but UninitializeComponent has not yet.
bool HasBegunPlay () const
Indicates that BeginPlay has been called, but EndPlay has not yet.
virtual void InitializeComponent ()
Initializes the component.
void InvalidateLightingCache ()
Invalidate lighting cache with default options.
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly)
Called when this actor component has moved, allowing it to discard statically cached lighting information.
bool IsAsyncCreatePhysicsStateRunning () const
Whether asynchronous physics state creation is running or not.
bool IsAsyncDestroyPhysicsStateRunning () const
Whether asynchronous physics state destruction is running or not.
virtual bool IsAsyncPhysicsStateCreated () const override final
Returns whether the physics state is created.
bool IsCreatedByConstructionScript () const
Returns true if instances of this component are created by either the user or simple construction script.
bool IsEditableWhenInherited () const
True if this component can be modified when it was inherited from a parent actor class.
virtual bool IsHLODRelevant () const
Override to specify that a component is relevant to the HLOD generation.
virtual bool IsNameStableForNetworking () const override
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsNavigationRelevant () const
Override to specify that a component is relevant to the navigation system.
bool IsNetMode (ENetMode Mode) const
Test whether net mode is the given mode.
bool IsNetSimulating () const
Returns true if we are replicating and this client is not authoritative.
bool IsNetStartupComponent () const
Returns true if this component was owned by a net startup actor during level load.
bool IsOwnerRunningUserConstructionScript () const
See if the owning Actor is currently running the UCS.
bool IsOwnerSelected () const
Returns whether the component's owner is selected in the editor.
bool IsPhysicsStateCreated () const
Returns true if the physics 'state' (e.g.
FORCEINLINE bool IsPreRegistered () const
See if this component is currently pre-registered.
FORCEINLINE bool IsPreRegistering () const
See if this component is currently pre-registering.
FORCEINLINE bool IsPreUnregistered () const
See if this component is currently pre-unregistered.
FORCEINLINE bool IsPreUnregistering () const
See if this component is currently pre-unregistering.
virtual bool IsReadyForOwnerToAutoDestroy () const
Overridable check for a component to indicate to its Owner that it should prevent the Actor from auto destroying when finished.
bool IsReadyForReplication () const
Indicates that ReadyForReplication has been called.
FORCEINLINE bool IsRegistered () const
See if this component is currently registered.
bool IsRenderInstancesDirty () const
Is this component's instance data in need of sending to the renderer?
bool IsRenderStateCreated () const
Returns true if the render 'state' (e.g.
bool IsRenderStateDirty () const
Is this component in need of its whole state being sent to the renderer?
bool IsRenderStateRecreating () const
Returns true if the render 'state' is being recreated for this component (see additional comments on variable above)
bool IsRenderTransformDirty () const
Is this component's transform in need of sending to the renderer?
bool IsReplicatedSubObjectRegistered (const UObject *SubObject) const
Tells if the object is registered to be replicated by this actor component.
virtual bool IsSelectedInEditor () const override
Test the selection state of a UObject.
virtual bool IsSupportedForNetworking () const override
IsSupportedForNetworking means an object can be referenced over the network.
bool IsUsingRegisteredSubObjectList () const
Returns if this component is replicating subobjects via the registration list or via the virtual ReplicateSubObjects method.
void MarkForNeededEndOfFrameRecreate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkForNeededEndOfFrameUpdate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkRenderDynamicDataDirty ()
Indicate that dynamic data for this component needs to be sent at the end of the frame.
void MarkRenderInstancesDirty ()
Marks the instances as dirty - changes to instance transforms/custom data will be sent to the render thread at the end of the frame.
void MarkRenderStateDirty ()
Mark the render state as dirty - will be sent to the render thread at the end of the frame.
void MarkRenderTransformDirty ()
Marks the transform as dirty - will be sent to the render thread at the end of the frame.
virtual bool Modify (bool bAlwaysMarkDirty=true) override
Note that the object will be modified.
virtual bool NeedsLoadForClient () const override
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForEditorGame () const override
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
virtual bool NeedsLoadForServer () const override
Called during saving to determine the load flags to save with the object.
virtual void OnActorEnableCollisionChanged ()
Called on each component when the Actor's bEnableCollisionChanged flag changes.
virtual void OnActorVisibilityChanged ()
Called on each component when the Actor's visibility state changes.
virtual bool OnAsyncCreatePhysicsState (const UE::FTimeout &Timeout) override
Used to create any physics engine information for this component outside of the GameThread.
virtual void OnAsyncCreatePhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is created.
virtual bool OnAsyncDestroyPhysicsState (const UE::FTimeout &Timeout) override
Used to destroy any physics engine information for this component outside of the GameThread.
virtual void OnAsyncDestroyPhysicsStateBegin_GameThread () override
Called on the GameThread before the component's physic engine information is destroyed.
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is destroyed.
virtual void OnComponentCreated ()
Called when a component is created (not loaded).
virtual void OnComponentDestroyed (bool bDestroyingHierarchy)
Called when a component is destroyed.
void OnCreatedFromReplication ()
void OnDestroyedFromReplication ()
virtual void OnEndOfFrameUpdateDuringTick ()
Allows components to handle an EOF update happening mid tick.
virtual void OnPreEndOfFrameSync ()
Allows components to wait on outstanding tasks prior to sending EOF update data.
virtual void PostApplyToComponent ()
Called after ApplyToComponent has run.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
This alternate version of PostEditChange is called when properties inside structs are modified.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
Called when a property on this object has been modified externally.
virtual void PostEditUndo () override
Called after applying a transaction to the object.
virtual void PostInitProperties () override
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
virtual void PostLoad () override
Do any object-specific cleanup required immediately after loading an object.
virtual void PostRename (UObject *OldOuter, const FName OldName) override
Called at the end of Rename(), but only if the rename was actually carried out.
virtual void PreEditChange (FProperty *PropertyThatWillChange) override
This is called when a property is about to be modified externally.
virtual void PreEditUndo () override
Called before applying a transaction to the object.
void PreRegisterComponentWithWorld (UWorld *InWorld)
Pre-registers a component with a specific world.
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker)
Called on the component right before replication occurs.
void PreUnregisterComponentFromWorld ()
Pre-unregisters a component from a specific world.
virtual void ReadyForReplication ()
ReadyForReplication gets called on replicated components when their owning actor is officially ready for replication.
void RecreatePhysicsState ()
Recreate the physics state right way.
void RecreateRenderState_Concurrent ()
Recreate the render state right away.
UFUNCTION()) 1 void ReceiveEndPlay(EEndPlayReason void RegisterAllComponentTickFunctions (bool bRegister)
Blueprint implementable event for when the component ends play, generally via destruction or its Actor's EndPlay.
void RegisterComponent ()
Register this component, creating any rendering/physics state.
void RegisterComponentWithWorld (UWorld *InWorld, FRegisterComponentContext *Context=nullptr)
Registers a component with a specific world, which creates any visual/physical state.
void RemoveReplicatedSubObject (UObject *SubObject)
Unregister a SubObject to stop replicating it's properties to clients.
void RemoveUCSModifiedProperties (const TArray< FProperty * > &Properties)
Removes specified properties from the list of UCS-modified properties.
virtual void RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual bool Rename (const TCHAR *NewName=NULL, UObject *NewOuter=NULL, ERenameFlags Flags=REN_None) override
Rename this object to a unique name, or change its outer.
virtual bool ReplicateSubobjects (class UActorChannel *Channel, class FOutBunch *Bunch, FReplicationFlags *RepFlags)
Allows a component to replicate other subobject on the actor.
virtual bool RequiresGameThreadEndOfFrameRecreate () const
return true if this component requires end of frame recreates to happen from the game thread.
virtual bool RequiresGameThreadEndOfFrameUpdates () const
return true if this component requires end of frame updates to happen from the game thread.
virtual bool RequiresPreEndOfFrameSync () const
return true if this component needs to sync to tasks before end of frame updates are executed
void ReregisterComponent ()
Unregisters and immediately re-registers component.
virtual void Serialize (FArchive &Ar) override
Handles reading, writing, and reference collecting using FArchive.
void SetActiveFlag (const bool bNewIsActive)
Sets the value of bIsActive without causing other side effects to this instance.
void SetCanEverAffectNavigation (bool bRelevant)
Sets value of bCanEverAffectNavigation flag and update navigation octree if needed.
virtual void SetComponentTickEnabledAsync (bool bEnabled)
Spawns a task on GameThread that will call SetComponentTickEnabled.
void SetIsNetStartupComponent (const bool bInIsNetStartupComponent)
This should only be called by the engine in ULevel::InitializeNetworkActors to initialize bIsNetStartupComponent.
void SetNetAddressable ()
This signifies the component can be ID'd by name over the network.
virtual void SetPackageExternal (bool bExternal, bool bShouldDirty)
bool SetupActorComponentTickFunction (struct FTickFunction *TickFunction)
Set up a tick function for a component in the standard way.
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const
Returns whether PreRegisterComponentWithWorld should be called for this component when its Level is being added to the world.
virtual bool ShouldIncrementalPreUnregister () const
Returns whether PreUnregisterComponentFromWorld should be called for this component when its Level is being removed from the world.
void TearOffReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels who spawned a replica of this subobject to release ownership over it.
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction)
Function called every frame on this ActorComponent.
UFUNCTION () 1 bool ComponentHasTag(FName Tag) const
See if this component contains the supplied tag.
UFUNCTION () 1 float GetComponentTickInterval() const
Returns the tick interval for this component's primary tick function, which is the frequency in seconds at which it will be executed.
UFUNCTION () 1 virtual bool IsComponentTickEnabled() const
Returns whether this component has tick enabled or not.
UFUNCTION () 1 virtual void OnRep_IsActive()
Handles replication of active state, handles ticking by default but should be overridden as needed.
UFUNCTION () 1 virtual void SetAutoActivate(bool bNewAutoActivate)
Sets whether the component should be auto activate or not.
UFUNCTION () 1 virtual void SetComponentTickEnabled(bool bEnabled)
Set this component's tick functions to be enabled or disabled.
UFUNCTION () 1 void SetComponentTickInterval(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetComponentTickIntervalAndCooldown(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetIsReplicated(bool ShouldReplicate)
Enable or disable replication.
UFUNCTION () 1 void SetTickableWhenPaused(bool bTickableWhenPaused)
Sets whether this component can tick when paused.
UFUNCTION ()) 1 virtual void Activate(bool bReset
Activates the SceneComponent, should be overridden by native child classes.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteActor(AActor *PrerequisiteActor)
Make this component tick after PrerequisiteActor.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Make this component tick after PrerequisiteComponent.
UFUNCTION ()) 1 virtual void Deactivate()
Deactivates the SceneComponent.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteActor(AActor *PrerequisiteActor)
Remove tick dependency on PrerequisiteActor.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Remove tick dependency on PrerequisiteComponent.
UFUNCTION ()) 1 virtual void SetActive(bool bNewActive
Sets whether the component is active or not.
UFUNCTION ()) 1 virtual void ToggleActive()
Toggles the active state of the component.
UFUNCTION ()) 1 void K2_DestroyComponent(UObject *Object)
Unregister and mark for pending kill a component.
UFUNCTION ()) 1 void ReceiveAsyncPhysicsTick(float DeltaSeconds
Event called every async physics tick if bAsyncPhysicsTickEnabled is true.
UFUNCTION ()) 1 void ReceiveBeginPlay()
Blueprint implementable event for when the component is beginning play, called before its owning actor's BeginPlay or when the component is dynamically created if the Actor has already BegunPlay.
UFUNCTION ()) 1 void ReceiveTick(float DeltaSeconds)
Event called every frame if tick is enabled.
UFUNCTION ()) 1 void SetTickGroup(ETickingGroup NewTickGroup)
Changes the ticking group for this component.
UFUNCTION ()) AActor *GetOwner() const
Follow the Outer chain to get the AActor that 'Owns' this component.
UFUNCTION ()) bool IsActive() const
Returns whether the component is active or not.
UFUNCTION ()) bool IsBeingDestroyed() const
Returns whether the component is in the process of being destroyed.
virtual void UninitializeComponent ()
Handle this component being Uninitialized.
void UnregisterComponent ()
Unregister this component, destroying any rendering/physics state.
virtual void UpdateComponentToWorld (EUpdateTransformFlags UpdateTransformFlags=EUpdateTransformFlags::None, ETeleportType Teleport=ETeleportType::None)
Recalculate the value of our component to world transform.
UPROPERTY () EComponentCreationMethod CreationMethod
Describes how a component instance will be created.
UPROPERTY () FActorComponentActivatedSignature OnComponentActivated
Called when the component has been activated, with parameter indicating if it was from a reset.
UPROPERTY () FActorComponentDeactivateSignature OnComponentDeactivated
Called when the component has been deactivated.
Public Member Functions inherited from UObject
void AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const
Returns whether native properties are identical to the one of the passed in component.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform)
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
virtual void BuildSubobjectMapping (UObject *OtherObject, TMap< UObject *, UObject * > &ObjectMapping) const
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
void CallAddReferencedObjects (FReferenceCollector &Collector)
Helper function to call AddReferencedObjects for this object's class.
void CallFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
Internal VM method for executing a function.
bool CallFunctionByNameWithArguments (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor, bool bForceCallWithNonExec=false)
Handle calling a function by name when executed from the console or a command line.
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain) const
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
bool CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
bool CheckDefaultSubobjects (bool bForceCheck=false) const
Checks default sub-object assumptions.
virtual void ClearAllCachedCookedPlatformData ()
Clear all cached cooked platform data.
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform)
Clears cached cooked platform data for specific platform.
virtual void CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext)
Collect any save override state.
bool ConditionalBeginDestroy ()
Called before destroying the object.
bool ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
void ConditionalPostLoad ()
PostLoad if needed.
void ConditionalPostLoadSubobjects (struct FObjectInstancingGraph *OuterInstanceGraph=NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
virtual bool ConformSparseClassDataStruct (UScriptStruct *SourceSparseClassDataStruct, void *SourceSparseClassData) const
void CookAdditionalFiles (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
TSharedPtr< ITransactionObjectAnnotation > CreateAndRestoreTransactionAnnotation (FArchive &Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetPreviewPlatform, FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
void DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
void ExecuteUbergraph (int32 EntryPoint)
Execute the ubergraph from a specific entry point.
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent)
Exports the property values for the specified object as text to the output device.
UFunction * FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
UFunction * FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
TSharedPtr< ITransactionObjectAnnotation > FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
virtual void FinishDestroy ()
Called to finish destroying the object.
virtual void GetAdditionalAssetDataObjectsForCook (FArchiveCookContext &CookContext, TArray< UObject * > &OutObjects) const
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
UObject * GetArchetype () const
Return the template this object is based on.
void GetArchetypeInstances (TArray< UObject * > &Instances)
Builds a list of objects which have this object in their archetype chain.
virtual void GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > &OutMetadata) const
Gathers a collection of asset registry tag metadata.
void GetAssetRegistryTags (FAssetData &Out) const
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
void GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData &Out) const
Gathers a list of asset registry tags for an FAssetData.
virtual const TCHAR * GetConfigOverridePlatform () const
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
FString GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
virtual FString GetDesc ()
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
FString GetDetailedInfo () const
This will return detail info about this specific object.
virtual FName GetExporterName (void)
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
virtual void GetExtendedAssetRegistryTagsForSave (const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &OutTags) const
Temporary interim solution to gather asset registry data at save time only.
FString GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
virtual bool GetNativePropertyValues (TMap< FString, FString > &out_PropertyValues, uint32 ExportFlags=0) const
Callback for retrieving a textual representation of natively serialized properties.
virtual uint64 GetNetPushIdDynamic () const
Should only ever be used by internal systems.
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
Called during cooking.
virtual void GetPrestreamPackages (TArray< UObject * > &OutPrestream)
Called during cooking.
virtual FPrimaryAssetId GetPrimaryAssetId () const
Returns an Type:Name pair representing the PrimaryAssetId for this object.
FString GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const
Called when this object begins replicating to initialize the state of custom property conditions.
SIZE_T GetResourceSizeBytes (EResourceSizeMode::Type Mode)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
virtual FRestoreForUObjectOverwrite * GetRestoreForUObjectOverwrite ()
Save information for StaticAllocateObject in the case of overwriting an existing object.
UScriptStruct * GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
virtual void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &ObjList)
Returns a list of sub-objects that have stable names for networking.
virtual bool HasNonEditorOnlyReferences () const
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
template<class T>
FORCEINLINE bool Implements () const
Returns true if this object implements the interface T, false otherwise.
template<class T>
bool Implements () const
Returns true if this object implements the interface T, false otherwise.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn)
Exports the property values for the specified object as text to the output device.
void InstanceSubobjectTemplates (struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
virtual bool IsAsset () const
Returns true if this object is considered an asset.
bool IsBasedOnArchetype (const UObject *const SomeObject) const
Determine if this object has SomeObject in its archetype chain.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform)
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
virtual bool IsCapturingAsRootObjectForTransaction () const
Method to disable the sub object special handling in the transaction buffer for this object.
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const
Generic function to validate objects during changelist validations, etc.
virtual bool IsEditorOnly () const
Called during saving to determine if the object is forced to be editor only or not.
virtual bool IsFullNameStableForNetworking () const
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
bool IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
virtual bool IsLocalizedResource () const
Returns true if this object is considered a localized resource.
virtual bool IsPostLoadThreadSafe () const
Called during async load to determine if PostLoad can be called on the loading thread.
virtual bool IsReadyForAsyncPostLoad () const
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
virtual bool IsReadyForFinishDestroy ()
Called to check if the object is ready for FinishDestroy.
virtual bool IsSafeForRootSet () const
Returns true if this object is safe to add to the root set.
bool IsSelected () const
Test the selection state of a UObject.
void LoadConfig (UClass *ConfigClass=nullptr, const TCHAR *Filename=nullptr, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > *OutAccessedKeys=nullptr)
Imports property values from an .ini file.
virtual void LoadedFromAnotherClass (const FName &OldClassName)
Called when the object was loaded from another class via active class redirects.
virtual void MarkAsEditorOnlySubobject ()
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
virtual void MoveDataToSparseClassDataStruct () const
virtual bool NeedsLoadForTargetPlatform (const class ITargetPlatform *TargetPlatform) const
Called during saving to determine the load flags to save with the object.
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &Context)
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
void OutputReferencers (FOutputDevice &Ar, FReferencerInformationList *Referencers=NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
virtual void OverrideConfigSection (FString &SectionName)
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
virtual void OverridePerObjectConfigSection (FString &SectionName)
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
void ParseParms (const TCHAR *Parms)
Import an object from a file.
virtual void PostCDOCompiled (const FPostCDOCompiledContext &Context)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
virtual void PostCDOContruct ()
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
virtual void PostDuplicate (bool bDuplicateForPIE)
Called after duplication & serialization and before PostLoad.
virtual void PostDuplicate (EDuplicateMode::Type DuplicateMode)
void PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
virtual void PostEditImport ()
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation)
Called after applying a transaction to the object in cases where transaction annotation was provided.
virtual void PostLinkerChange ()
Called in response to the linker changing, this can only happen in the editor.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph)
Instances components for objects being loaded from disk, if necessary.
virtual void PostNetReceive ()
Called right after receiving a bunch.
virtual void PostReinitProperties ()
Called after properties are overwritten, including after subobjects initialization from a CDO.
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded)
Called from ReloadConfig after the object has reloaded its configuration data.
virtual void PostRepNotifies ()
Called right after calling all OnRep notifies (called even when there are no notifies)
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent)
Called after the object has been transacted in some way.
virtual void PreDestroyFromReplication ()
Called right before being marked for destruction due to network replication.
virtual void PreDuplicate (FObjectDuplicationParameters &DupParams)
Called before duplication.
virtual void PreEditChange (class FEditPropertyChain &PropertyAboutToChange)
This alternate version of PreEditChange is called when properties inside structs are modified.
virtual void PreNetReceive ()
Called right before receiving a bunch.
virtual void PreSave (FObjectPreSaveContext SaveContext)
Presave function.
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual bool ProcessConsoleExec (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor)
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
virtual void ProcessEvent (UFunction *Function, void *Parms)
Called by VM to execute a UFunction with a filled in UStruct of parameters.
void PropagatePostEditChange (TArray< UObject * > &AffectedObjects, FPropertyChangedChainEvent &PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
void PropagatePreEditChange (TArray< UObject * > &AffectedObjects, FEditPropertyChain &PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
virtual UClass * RegenerateClass (UClass *ClassToRegenerate, UObject *PreviousCDO)
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
void ReinitializeProperties (UObject *SourceObject=NULL, struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
void ReloadConfig (UClass *ConfigClass=NULL, const TCHAR *Filename=NULL, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
virtual bool ResolveSubobject (const TCHAR *SubObjectPath, UObject *&OutObject, bool bLoadIfExists)
Called to defer loading a subobject to its top-level container object.
void RetrieveReferencers (TArray< FReferencerInformation > *OutInternalReferencers, TArray< FReferencerInformation > *OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
void SaveConfig (uint64 RequiredPropertyFlags=CPF_Config, const TCHAR *Filename=nullptr, FConfigCacheIni *Config=GConfig, bool bAllowCopyToDefaultObject=true)
Save configuration out to ini files.
virtual void Serialize (FStructuredArchive::FRecord Record)
void SerializeScriptProperties (FArchive &Ar) const
Serializes the script property data located at Data.
void SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
void SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
void SetLinker (FLinkerLoad *LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting=true)
Changes the linker and linker index to the passed in one.
virtual void ShutdownAfterError ()
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
void SkipFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
virtual void TagSubobjects (EObjectFlags NewFlags)
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
void ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext &Context) const
Internal use function for the AssetRegistry.
bool TryUpdateDefaultConfigFile (const FString &SpecificFileLocation="", bool bWarnIfFail=true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") 1 void UpdateDefaultConfigFile(const FString &SpecificFileLocation
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.1, "Use version that takes FPostCDOCompiledContext instead.") virtual void PostCDOCompiled()
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
UE_DEPRECATED (5.3, "Matinee has been removed in 5.0, nothing is calling PostInterpChange anymore") virtual void PostInterpChange(FProperty *PropertyThatChanged)
UE_DEPRECATED (5.3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") 1 virtual EDataValidationResult IsDataValid(TArray< FText > &ValidationErrors)
Generic function to validate objects during changelist validations, etc.
UE_DEPRECATED (5.3, "Please use the the const version of IsDataValid(FDataValidationContext&)") 1 virtual EDataValidationResult IsDataValid(class FDataValidationContext &Context)
UE_DEPRECATED (5.4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") 1 void CollectDefaultSubobjects(TArray< UObject * > &OutDefaultSubobjects
Gets all subobjects inside this object that return true for IsDefaultSubobject.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const
UE_DEPRECATED (5.5, "Multithreaded destruction of UObjects is no longer supported.") 1 virtual bool IsDestructionThreadSafe() const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
UE_DEPRECATED (5.5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \ Note that this function MUST be safe to call on a background thread. If you have functionality that doesn't meet that requirement, \ consider using the AssetRegistry's AssetAddedEvent which fires on the game thread.") virtual void PostLoadAssetRegistryTags(const FAssetData &InAssetData
void UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
void UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
void UpdateSinglePropertyInConfigFile (const FProperty *InProperty, const FString &InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
virtual void ValidateGeneratedRepEnums (const TArray< struct FRepRecord > &ClassReps) const
virtual void WillNeverCacheCookedPlatformDataAgain ()
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Public Member Functions inherited from UObjectBaseUtility
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Public Member Functions inherited from IAsyncPhysicsStateProcessor
virtual void CollectBodySetupsWithPhysicsMeshesToCreate (TSet< UBodySetup * > &OutBodySetups) const
Returns body setups that needs to create their physics meshes before physics state asynchronous creation.
Static Public Member Functions
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Static Public Member Functions inherited from UObject
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Callback used to allow object register its direct object references that are not already covered by the token stream.
static bool CanCreateInCurrentContext (UObject *Template)
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
static UObject * GetArchetypeFromRequiredInfo (const UClass *Class, const UObject *Outer, FName Name, EObjectFlags ObjectFlags)
Return the template that an object with this class, outer and name would be.
static TSet< FName > & GetMetaDataTagsForAssetRegistry ()
The metadata tags to be transferred from the FMetaData to the Asset Registry.
static const FName & SourceFileTagName ()
Get the common tag name used for all asset source file import paths.
static void UpdateClassesExcludedFromDedicatedClient (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated client builds.
static void UpdateClassesExcludedFromDedicatedServer (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated server builds.
Static Public Member Functions inherited from UObjectBaseUtility
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Data Fields
uint8 bAllowAnyoneToDestroyMe:1
Can this component be destroyed (via K2_DestroyComponent) by any parent.
uint8 bAllowConcurrentTick:1
Can we tick this concurrently on other threads?
uint8 bAutoRegister:1
Does this component automatically register with its owner.
UPROPERTY() uint8 bEditableWhenInherited uint8 bNavigationRelevant: 1
Whether the component is activated at creation or must be explicitly activated.
uint8 bNeverNeedsRenderUpdate:1
If true, this component never needs a render update.
bool bReset =false)
uint8 bTickInEditor:1
Should this component be ticked in the editor.
uint8 bWantsInitializeComponent:1
Whether this component can potentially influence navigation.
float SimSeconds
Data Fields inherited from UObject
bool bIncludeNestedSubobjects =false) const
TArray< FAssetRegistryTag > &OutTagsAndValuesToUpdate const final
Static Public Attributes
static TMap< UActorComponent *, TArray< FSimpleMemberReference > > AllUCSModifiedProperties
static FTransactionallySafeRWLock AllUCSModifiedPropertiesLock
static const FString ComponentTemplateNameSuffix
Suffix used to identify template component instances.
static FOnMarkRenderStateDirty MarkRenderStateDirtyEvent
Called When render state is marked dirty.
Static Public Attributes inherited from UObject
static FOnGetPreviewPlatform OnGetPreviewPlatform
Protected Types
enum class EComponentRegistrationState {
None , PreRegistering , PreRegistered , PreUnregistering ,
PreUnregistered
}
Protected Types inherited from UObject
enum class ETransactionAnnotationCreationMode : uint8 { DefaultInstance , FindOrCreate }
Factory a new annotation object and optionally populate it with data.
Protected Member Functions
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context)
Used to create any rendering thread information for this component.
void DeferRemoveAsyncPhysicsTick ()
Defers the call to SetAsyncPhysicsTickEnabled(false) to the next async tick.
virtual void DestroyRenderState_Concurrent ()
Used to shut down any rendering thread structure for this component.
void HandleCanEverAffectNavigationChange (bool bForceUpdate=false)
Makes sure navigation system has up to date information regarding component's navigation relevancy and if it can affect navigation at all.
virtual bool HasValidPhysicsState () const
Used to check that DestroyPhysicsState() is working correctly.
bool NeedsInitialization () const
Convenience method for testing whether or not we are still be constructed / initialized.
virtual void OnCreatePhysicsState ()
Used to create any physics engine information for this component.
virtual void OnDestroyPhysicsState ()
Used to shut down and physics engine structure for this component.
virtual void OnPreRegister ()
Called by PreRegisterComponentWithWorld when the component is being pre-registered.
virtual void OnPreRegistered ()
Called once the component is pre-registered.
virtual void OnPreUnregister ()
Called by PreUnregisterComponentFromWorld when the component is being pre-unregistered.
virtual void OnPreUnregistered ()
Called once the component is pre-unregistered.
virtual void OnRegister ()
Called when a component is registered, after Scene is set, but before CreateRenderState_Concurrent or OnCreatePhysicsState are called.
virtual void OnUnregister ()
Called when a component is unregistered.
bool OwnerNeedsInitialization () const
Convenience method for testing whether or not our owner is still being constructed / initialized.
virtual void PrecachePSOs ()
Precache all PSOs which can be used by the actor component.
virtual void RegisterComponentTickFunctions (bool bRegister)
Virtual call chain to register all tick functions.
virtual void SendRenderDynamicData_Concurrent ()
Called to send dynamic data for this component to the rendering thread.
virtual void SendRenderInstanceData_Concurrent ()
Called to send instance data for this component to the rendering thread.
virtual void SendRenderTransform_Concurrent ()
Called to send a transform update for this component to the rendering thread.
void SetAsyncPhysicsTickEnabled (bool bEnabled)
Sets bAsyncPhysicsTickEnabled which determines whether to use use the async physics tick with this component.
void SetIsReplicatedByDefault (const bool bNewReplicates)
Sets the value of bReplicates without causing other side effects to this instance.
virtual bool ShouldActivate () const
Return true if this component is in a state where it can be activated normally.
virtual bool ShouldAsyncCreatePhysicsState (UWorld *WorldContext) const
Returns whether this component should create its physics state asynchronously.
virtual bool ShouldAsyncDestroyPhysicsState () const
Returns whether this component should destroy its physics state asynchronously.
virtual bool ShouldCreatePhysicsState () const
Return true if CreatePhysicsState() should be called.
virtual bool ShouldCreateRenderState () const
Return true if CreateRenderState() should be called.
UPROPERTY () TArray< TObjectPtr< UAssetUserData > > AssetUserData
Array of user data stored with the component.
Protected Member Functions inherited from UObject
bool CanCheckDefaultSubObjects (bool bForceCheck, bool &bResult) const
Checks it's ok to perform subobjects check at this time.
virtual bool CheckDefaultSubobjectsInternal () const
Checks default sub-object assumptions.
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const
virtual FString GetDetailedInfoInternal () const
This function actually does the work for the GetDetailedInfo() and is virtual.
virtual void ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext &Context) const
Performs fixup on loaded asset registry data.
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Static Protected Member Functions
static bool CanBeHLODRelevant (const UActorComponent *ActorComponent)
Utility method used by subclasses to test basic conditions a component must fulfill to be considered HLOD relevant.
static const FName GetReplicatesPropertyName ()
Gets the property name for bReplicates.
Protected Attributes
uint8 bAllowReregistration:1
Check whether the component class allows reregistration during ReregisterAllComponents.
uint8 bCallAsyncPhysicsStateCreatedDelegate:1
If the physics state was created while component was pre-registering, notification to GameThread is deferred next time CreatePhysicsState is called.
uint8 bPhysicsStateCreated:1
If the physics state is currently created for this component.
uint8 bRegistered:1
Indicates if this ActorComponent is currently registered with a scene.
uint8 bRenderStateCreated:1
If the render state is currently created for this component.
uint8 bRenderStateRecreating:1
Render state is being recreated for this component.
EComponentRegistrationState RegistrationState
Indicates if this ActorComponent is currently pre-registering or pre-registered with a scene.
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Private Types
enum struct EPhysicsStateAsyncCreationState : uint8 { None , Creating , Destroying }
Private Member Functions
UActorComponent (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
Default UObject constructor that takes an optional ObjectInitializer.
void ClearNeedEndOfFrameUpdate_Internal ()
void ConsolidatedPostEditChange (const FPropertyChangedEvent &PropertyChangedEvent)
Utility function for each of the PostEditChange variations to call for the same behavior.
void DetermineUCSSerializationIndexForLegacyComponent ()
Calculate the UCS serialization index for a component that was saved before we started saving this data.
void ExecuteRegisterEvents (FRegisterComponentContext *Context=nullptr)
Calls OnRegister, CreateRenderState_Concurrent and OnCreatePhysicsState.
void ExecuteUnregisterEvents ()
Calls OnUnregister, DestroyRenderState_Concurrent and OnDestroyPhysicsState.
AActor * GetActorOwnerNoninline () const
UWorld * GetWorld_Uncached () const
If WorldPrivate isn't set this will determine the world from outers.
ENetMode InternalGetNetMode () const
Private version without inlining that does not check Dedicated server build flags (which should already have been done).
void RegisterAsyncPhysicsTickEnabled (bool bRegister)
virtual void Tick (float DeltaTime) final
This is the old name of the tick function.
UPROPERTY () int32 UCSSerializationIndex
Populated when the component is created and tracks the often used order of creation on a per archetype/per actor basis.
UPROPERTY () struct FActorComponentTickFunction PrimaryComponentTick
Main tick function for the Component.
UPROPERTY () TArray< FName > ComponentTags
Array of tags that can be used for grouping and categorizing.
Private Attributes
uint8 bAsyncPhysicsTickEnabled: 1
Whether to use use the async physics tick with this component.
uint8 bCanUseCachedOwner:1
During undo/redo it isn't safe to cache owner.
uint8 bHasBeenCreated:1
If true, the component will be excluded from non-editor builds.
uint8 bHasBeenInitialized:1
Indicates that InitializeComponent has been called, but UninitializeComponent has not yet.
uint8 bHasBegunPlay:1
Indicates that BeginPlay has been called, but EndPlay has not yet.
uint8 bIsBeingDestroyed:1
Indicates the the destruction process has begun for this component to avoid recursion.
uint8 bIsNetStartupComponent: 1
True if this component was owned by a net startup actor during level load.
uint8 bIsReadyForReplication:1
Indicates that ReadyForReplication has been called.
uint8 bMarkedForPreEndOfFrameSync: 1
Tracks whether the component has been added to the world's pre end of frame sync list.
uint8 bMarkPendingKillOnPostLoad: 1
Marks this component pending kill once PostLoad occurs.
uint8 bRenderDynamicDataDirty:1
Is this component's dynamic data in need of sending to the renderer?
uint8 bRenderInstancesDirty:1
Is this component's instanced data in need of sending to the renderer?
UPROPERTY()) uint8 bReplicates uint8 bRenderStateDirty:1
Is this component safe to ID over the network by name?
uint8 bRenderTransformDirty:1
Is this component's transform in need of sending to the renderer?
uint8 bRoutedPostRename:1
Used to ensure that any subclass of UActorComponent that overrides PostRename calls up to the Super to make OwnedComponents arrays get updated correctly.
uint8 bTickFunctionsRegistered:1
Whether we've tried to register tick functions.
int32 MarkedForEndOfFrameUpdateArrayIndex
Used for fast removal of end of frame update.
uint8 MarkedForEndOfFrameUpdateState:2
Tracks whether the component has been added to one of the world's end of frame update lists.
AActor * OwnerPrivate
Cached pointer to owning actor.
FPhysScene * PhysicsStateAsyncCreationScene
If non-null, physics state creation/destruction is done asynchronously by FPhysScene_Chaos::ProcessAsyncPhysicsStateJobs.
EPhysicsStateAsyncCreationState PhysicsStateAsyncCreationState: 2
Whether the component is creating/destroying its physics state asynchronously (or not)
UWorld * WorldPrivate
Pointer to the world that this component is currently registered with.
Static Private Attributes
static GENERATED_BODY() public FActorComponentGlobalDestroyPhysicsSignature GlobalDestroyPhysicsDelegate
Create component physics state global delegate.
Friends
class FActorComponentDetails
struct FActorComponentTickFunction
class FComponentRecreateRenderStateContext
class FComponentReregisterContextBase
struct FMarkComponentEndOfFrameUpdateState
struct FSetUCSSerializationIndex
struct SkeletalMeshUCSModifiedDataCleanupHelper
Additional Inherited Members
Public Types inherited from UObject
enum class ENetFields_Private { NETFIELD_REP_START = 0 , NETFIELD_REP_END = -1 }
using FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Detailed Description
Definition at line 145 of file ActorComponent.h.
Member Enumeration Documentation
EComponentRegistrationState
enum class UActorComponent::EComponentRegistrationState strong protected
Enumerator
None
Component is not in any of the listed states, code should rely on bRegistered to determine if component is registered or not.
PreRegistering
Component is pre-registering (not registered)
PreRegistered
Component is pre-registered (not registered)
PreUnregistering
Component is pre-unregistering (registered)
PreUnregistered
Component is pre-unregistered (registered)
Definition at line 190 of file ActorComponent.h.
EPhysicsStateAsyncCreationState
enum struct UActorComponent::EPhysicsStateAsyncCreationState : uint8 strong private
Enumerator
None
Creating
Destroying
Definition at line 384 of file ActorComponent.h.
Constructor & Destructor Documentation
UActorComponent()
UActorComponent::UActorComponent (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get()) private
Default UObject constructor that takes an optional ObjectInitializer.
References FObjectInitializer::Get().
Referenced by CanBeHLODRelevant(), DECLARE_MULTICAST_DELEGATE_OneParam(), GetReplicatesPropertyName(), GetUCSSerializationIndex(), UFUNCTION(), and UFUNCTION().
Member Function Documentation
AddAssetUserData()
virtual void UActorComponent::AddAssetUserData (UAssetUserData * InUserData) override virtual
AdditionalStatObject()
virtual UObject const * UActorComponent::AdditionalStatObject () const inline virtual
Give a readable name for this component, including asset name if applicable.
Reimplemented in UAudioComponent, UDecalComponent, and UForceFeedbackComponent.
Definition at line 1149 of file ActorComponent.h.
References UObject::UObject().
AddReferencedObjects()
void UActorComponent::AddReferencedObjects (UObject * InThis, FReferenceCollector & Collector) static
References UObject::UObject().
Referenced by USceneComponent::Serialize().
AddReplicatedSubObject()
void UActorComponent::AddReplicatedSubObject (UObject * SubObject, ELifetimeCondition NetCondition = COND_None)
Register a SubObject that will get replicated along with the actor component.
The subobject needs to be manually removed from the list before it gets deleted.
Parameters
SubObject The subobject to replicate
NetCondition Optional condition to select which type of connection we will replicate the object to.
References UObject::UObject().
AllowReregistration()
FORCEINLINE bool UActorComponent::AllowReregistration () const inline
Check whether the component class allows reregistration during ReregisterAllComponents.
Definition at line 1246 of file ActorComponent.h.
References bAllowReregistration, and FORCEINLINE.
Referenced by FComponentEditorUtils::ApplyDefaultValueChange().
AllowsAsyncPhysicsStateCreation()
virtual bool UActorComponent::AllowsAsyncPhysicsStateCreation () const inline virtual
Returns whether this component allows having its physics state being created asynchronously (outside of the GameThread).
Reimplemented from IAsyncPhysicsStateProcessor.
Definition at line 838 of file ActorComponent.h.
AllowsAsyncPhysicsStateDestruction()
virtual bool UActorComponent::AllowsAsyncPhysicsStateDestruction () const inline virtual
Returns whether this component allows having its physics state being destroyed asynchronously (outside of the GameThread).
Reimplemented from IAsyncPhysicsStateProcessor.
Definition at line 842 of file ActorComponent.h.
ApplyWorldOffset()
virtual void UActorComponent::ApplyWorldOffset (const FVector & InOffset, bool bWorldShift) inline virtual
Called by owner actor on position shifting Component should update all relevant data structures to reflect new actor location.
Parameters
InWorldOffset Offset vector the actor shifted by
bWorldShift Whether this call is part of whole world shifting
Reimplemented in URuntimeVirtualTextureComponent, USceneComponent, and USpringArmComponent.
Definition at line 1311 of file ActorComponent.h.
References ApplyWorldOffset(), and FVector.
Referenced by ApplyWorldOffset().
AsyncPhysicsTickComponent()
virtual void UActorComponent::AsyncPhysicsTickComponent (float DeltaTime, float SimTime) inline virtual
Override this function to implement custom logic to be executed every physics step.
Only executes if the component is registered, and also bAsyncPhysicsTick must be set to true.
Parameters
DeltaTime - The sim time associated with each step
SimTime - This is the total sim time since the sim began
Definition at line 925 of file ActorComponent.h.
References AsyncPhysicsTickComponent(), and DeltaTime.
Referenced by AsyncPhysicsTickComponent().
BeginDestroy()
virtual void UActorComponent::BeginDestroy () override virtual
Called before destroying the object.
This is called immediately upon deciding to destroy the object, to allow the object to begin an asynchronous cleanup process.
Reimplemented from UObject.
Reimplemented in UAIPerceptionComponent, UAudioComponent, UChildActorComponent, ULightComponent, UPhysicalAnimationComponent, UPhysicsConstraintComponent, URectLightComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneComponent, and USkyLightComponent.
BeginPlay()
virtual void UActorComponent::BeginPlay () virtual
Begins Play for the component.
Called when the owning Actor begins play or when the component is created if the Actor has already begun play. Actor BeginPlay normally happens right after PostInitializeComponents but can be delayed for networked or child actors. Requires component to be registered and initialized.
Reimplemented in UAbilitySystemComponent, UCameraShakeSourceComponent, UChildActorComponent, UDecalComponent, and URadialForceComponent.
CallRemoteFunction()
virtual bool UActorComponent::CallRemoteFunction (UFunction * Function, void * Parms, FOutParmRec * OutParms, FFrame * Stack) override virtual
Call the actor's function remotely.
Parameters
Function function to call
Parms arguments to the function call
OutParms out parameter information (irrelevant for RPC's)
Stack stack frame for the function call
Returns
returns true if the function was processed by a NetDriver
Reimplemented from UObject.
References Function.
CanBeHLODRelevant()
bool UActorComponent::CanBeHLODRelevant (const UActorComponent * ActorComponent) static protected
Utility method used by subclasses to test basic conditions a component must fulfill to be considered HLOD relevant.
References UActorComponent().
CanEditChange()
virtual bool UActorComponent::CanEditChange (const FProperty * InProperty) const override virtual
Called by the editor to query whether a property of this object is allowed to be modified.
The property editor uses this to disable controls for properties that should not be changed. When overriding this function you should always call the parent implementation first.
Parameters
InProperty The property to query
Returns
true if the property can be modified in the editor, otherwise false
Reimplemented from UObject.
Reimplemented in UDirectionalLightComponent, UExponentialHeightFogComponent, ULightComponent, ULightComponentBase, ULocalFogVolumeComponent, ULocalLightComponent, UPointLightComponent, URectLightComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneComponent, and USkyLightComponent.
CanEverAffectNavigation()
FORCEINLINE bool UActorComponent::CanEverAffectNavigation () const
Can this component potentially influence navigation.
Definition at line 1430 of file ActorComponent.h.
References FORCEINLINE.
CheckForErrors()
virtual void UActorComponent::CheckForErrors () virtual
Function that gets called from within Map_Check to allow this actor component to check itself for any potential errors and register them with map check dialog.
Note
Derived class implementations should call up to their parents.
Reimplemented in UCameraComponent, UDecalComponent, ULightComponent, UPhysicsConstraintComponent, URuntimeVirtualTextureComponent, USkyAtmosphereComponent, USkyLightComponent, and UVolumetricCloudComponent.
ClearNeedEndOfFrameUpdate()
FORCEINLINE void UActorComponent::ClearNeedEndOfFrameUpdate ()
If we belong to a world, clear the request to do a deferred update.
Definition at line 1469 of file ActorComponent.h.
References ClearNeedEndOfFrameUpdate_Internal(), FORCEINLINE, and MarkedForEndOfFrameUpdateState.
ClearNeedEndOfFrameUpdate_Internal()
void UActorComponent::ClearNeedEndOfFrameUpdate_Internal () private
Referenced by ClearNeedEndOfFrameUpdate().
ClearUCSModifiedProperties()
void UActorComponent::ClearUCSModifiedProperties ()
Clears the component's UCS modified properties.
ComponentIsInLevel()
bool UActorComponent::ComponentIsInLevel (const class ULevel * TestLevel) const
Returns true if this actor is contained by TestLevel.
ComponentIsInPersistentLevel()
bool UActorComponent::ComponentIsInPersistentLevel (bool bIncludeLevelStreamingPersistent) const
See if this component is in the persistent level.
ComputeHLODHash()
virtual void UActorComponent::ComputeHLODHash (class FHLODHashBuilder & HashBuilder) const inline virtual
Override to allow a component subclass to compute an hash for the purpose of HLOD generation.
Definition at line 1336 of file ActorComponent.h.
ConsolidatedPostEditChange()
void UActorComponent::ConsolidatedPostEditChange (const FPropertyChangedEvent & PropertyChangedEvent) private
Utility function for each of the PostEditChange variations to call for the same behavior.
CreatePhysicsState()
void UActorComponent::CreatePhysicsState (bool bAllowDeferral = false)
Create any physics engine information for this component.
References CreatePhysicsState().
Referenced by CreatePhysicsState().
CreateRenderState_Concurrent()
virtual void UActorComponent::CreateRenderState_Concurrent (FRegisterComponentContext * Context) protected virtual
Used to create any rendering thread information for this component.
Warning
This is called concurrently on multiple threads (but never the same component concurrently)
Reimplemented in UDecalComponent, UExponentialHeightFogComponent, ULightComponent, ULightmassPortalComponent, ULocalFogVolumeComponent, UPhysicsFieldComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USkyAtmosphereComponent, USkyLightComponent, UVolumetricCloudComponent, and UWindDirectionalSourceComponent.
DECLARE_MULTICAST_DELEGATE_OneParam()
UActorComponent::DECLARE_MULTICAST_DELEGATE_OneParam (FOnMarkRenderStateDirty , UActorComponent &)
References UActorComponent().
DeferRemoveAsyncPhysicsTick()
void UActorComponent::DeferRemoveAsyncPhysicsTick () protected
Defers the call to SetAsyncPhysicsTickEnabled(false) to the next async tick.
This allows you to remove the async physics tick callback within the async physics tick safely.
DestroyComponent()
virtual void UActorComponent::DestroyComponent (bool bPromoteChildren = false) virtual
Unregister the component, remove it from its outer Actor's Components array and mark for pending kill.
Reimplemented in USceneComponent.
DestroyPhysicsState()
void UActorComponent::DestroyPhysicsState ()
Shut down any physics engine structure for this component.
References DestroyPhysicsState().
Referenced by DestroyPhysicsState().
DestroyRenderState_Concurrent()
virtual void UActorComponent::DestroyRenderState_Concurrent () protected virtual
Used to shut down any rendering thread structure for this component.
Warning
This is called concurrently on multiple threads (but never the same component concurrently)
Reimplemented in UDecalComponent, UExponentialHeightFogComponent, ULightComponent, ULocalFogVolumeComponent, UPhysicsFieldComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USkyAtmosphereComponent, USkyLightComponent, UVolumetricCloudComponent, and UWindDirectionalSourceComponent.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
DestroyReplicatedSubObjectOnRemotePeers()
void UActorComponent::DestroyReplicatedSubObjectOnRemotePeers (UObject * SubObject)
Stop replicating a subobject and tell actor channels to delete the replica of this subobject next time the Actor gets replicated Note it is up to the caller to delete the local object on the authority.
If you are using the legacy subobject replication method (ReplicateSubObjects() aka bReplicateUsingRegisteredSubObjectList=false) make sure the subobject doesn't get replicated there either.
Parameters
SubObject THe SubObject to delete
References UObject::UObject().
DetermineUCSModifiedProperties()
void UActorComponent::DetermineUCSModifiedProperties ()
Initializes the list of properties that are modified by the UserConstructionScript.
DetermineUCSSerializationIndexForLegacyComponent()
void UActorComponent::DetermineUCSSerializationIndexForLegacyComponent () private
Calculate the UCS serialization index for a component that was saved before we started saving this data.
Referenced by GetUCSSerializationIndex().
DoDeferredRenderUpdates_Concurrent()
void UActorComponent::DoDeferredRenderUpdates_Concurrent ()
Uses the bRenderStateDirty/bRenderTransformDirty/bRenderInstancesDirty to perform any necessary work on this component.
Do not call this directly, call MarkRenderStateDirty, MarkRenderDynamicDataDirty, MarkRenderInstancesDataDirty,
Warning
This is called concurrently on multiple threads (but never the same component concurrently)
EndPlay()
virtual void UActorComponent::EndPlay (const EEndPlayReason::Type EndPlayReason) virtual
Ends gameplay for this component.
Called from AActor::EndPlay only if bHasBegunPlay is true
Reimplemented in UAudioComponent, UCameraShakeSourceComponent, UPhysicsConstraintComponent, and USceneComponent.
References EndPlay().
Referenced by EndPlay().
ExecuteRegisterEvents()
void UActorComponent::ExecuteRegisterEvents (FRegisterComponentContext * Context = nullptr) private
Calls OnRegister, CreateRenderState_Concurrent and OnCreatePhysicsState.
ExecuteUnregisterEvents()
void UActorComponent::ExecuteUnregisterEvents () private
Calls OnUnregister, DestroyRenderState_Concurrent and OnDestroyPhysicsState.
ForceActorNoDataLayers()
virtual bool UActorComponent::ForceActorNoDataLayers () const inline virtual
Definition at line 1198 of file ActorComponent.h.
ForceActorNonSpatiallyLoaded()
virtual bool UActorComponent::ForceActorNonSpatiallyLoaded () const inline virtual
Reimplemented in UDirectionalLightComponent.
Definition at line 1197 of file ActorComponent.h.
GetActorDescProperties()
virtual void UActorComponent::GetActorDescProperties (FPropertyPairsMap & PropertyPairsMap) const inline virtual
Add properties to the component owner's actor desc.
Definition at line 1053 of file ActorComponent.h.
GetActorOwnerNoninline()
AActor * UActorComponent::GetActorOwnerNoninline () const private
References GetActorOwnerNoninline().
Referenced by GetActorOwnerNoninline().
GetAssetUserDataArray()
virtual const TArray< UAssetUserData * > * UActorComponent::GetAssetUserDataArray () const override virtual
Reimplemented from IInterface_AssetUserData.
GetAssetUserDataOfClass()
virtual UAssetUserData * UActorComponent::GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override virtual
GetAsyncPhysicsStateObject()
virtual UObject * UActorComponent::GetAsyncPhysicsStateObject () const final override virtual
Returns the associated UObject for this processor.
Reimplemented from IAsyncPhysicsStateProcessor.
References UObject::UObject(), UObject::final, and GetAsyncPhysicsStateObject().
Referenced by GetAsyncPhysicsStateObject().
GetComponentChildElements()
virtual void UActorComponent::GetComponentChildElements (TArray< FTypedElementHandle > & OutElementHandles, const bool bAllowCreate = true) inline virtual
Get the logical child elements of this component, if any.
See also
UTypedElementHierarchyInterface.
Definition at line 1164 of file ActorComponent.h.
GetComponentClassCanReplicate()
virtual bool UActorComponent::GetComponentClassCanReplicate () const virtual
Returns true if this type of component can ever replicate, override to disable the default behavior.
GetComponentInstanceData()
virtual TStructOnScope< FActorComponentInstanceData > UActorComponent::GetComponentInstanceData () const virtual
Called before we throw away components during RerunConstructionScripts, to cache any data we wish to persist across that operation.
Reimplemented in UChildActorComponent, ULightComponent, USceneComponent, and USkyLightComponent.
GetComponentLevel()
ULevel * UActorComponent::GetComponentLevel () const
Return the ULevel that this Component is part of.
GetCustomEditorPreviewWidget()
virtual TSharedPtr< SWidget > UActorComponent::GetCustomEditorPreviewWidget () inline virtual
If this component is set up to provide a preview window in editor (see GetEditorPreviewInfo), you can use this to customize the preview (to be something other than a world viewport).
If this returns an empty pointer, then the preview will default to a viewport using the FMinimalViewInfo data from GetEditorPreviewInfo().
Definition at line 1039 of file ActorComponent.h.
GetCustomHLODBuilderClass()
virtual TSubclassOf< class UHLODBuilder > UActorComponent::GetCustomHLODBuilderClass () const inline virtual
Return the custom HLODBuilder class that should be used to generate HLODs for components of this type.
Allows the HLOD system to include whatever is needed to represent a component at a distance. For example, this is currently used to build custom HLODs for landscape streaming proxies. This could be used to generate fake lights, represent custom FX at a distance, or even to insert externally generated HLODs.
Reimplemented in UChildActorComponent.
Definition at line 1048 of file ActorComponent.h.
GetEditorPreviewInfo()
virtual bool UActorComponent::GetEditorPreviewInfo (float DeltaTime, FMinimalViewInfo & ViewOut) inline virtual
Supplies the editor with a view specific to this component (think a view from a camera components POV, a render, etc.).
Used for PIP preview windows.
Returns
True if the component overrides this, and fills out the view info output.
Reimplemented in UCameraComponent.
Definition at line 1031 of file ActorComponent.h.
References DeltaTime.
GetFunctionCallspace()
virtual int32 UActorComponent::GetFunctionCallspace (UFunction * Function, FFrame * Stack) override virtual
Return the space this function should be called.
Checks to see if this function should be called locally, remotely, or simply absorbed under the given conditions
Parameters
Function function to call
Stack stack frame for the function call
Returns
bitmask representing all callspaces that apply to this UFunction in the given context
Reimplemented from UObject.
References Function.
GetHLODProxyComponents()
virtual TArray< UActorComponent * > UActorComponent::GetHLODProxyComponents () const inline virtual
Override to provide a custom set of components to be used in place of the current component for the HLOD generation.
Definition at line 1333 of file ActorComponent.h.
GetIsReplicated()
FORCEINLINE bool UActorComponent::GetIsReplicated () const inline
Returns whether replication is enabled or not.
Definition at line 590 of file ActorComponent.h.
References FORCEINLINE, and GetIsReplicated().
Referenced by GetIsReplicated(), GetReplicationCondition(), and IsNetSimulating().
GetLifetimeReplicatedProps()
virtual void UActorComponent::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
Returns properties that are replicated for the lifetime of the actor channel.
Reimplemented from UObject.
Reimplemented in UAbilitySystemComponent, UChildActorComponent, and UGameplayTasksComponent.
GetMarkedForEndOfFrameUpdateState()
uint32 UActorComponent::GetMarkedForEndOfFrameUpdateState () const inline
Tracks whether the component has been added to one of the world's end of frame update lists.
Definition at line 437 of file ActorComponent.h.
References MarkedForEndOfFrameUpdateState.
GetMarkedForPreEndOfFrameSync()
uint32 UActorComponent::GetMarkedForPreEndOfFrameSync () const inline
Tracks whether the component has been added to one of the world's end of frame update lists.
Definition at line 440 of file ActorComponent.h.
References bMarkedForPreEndOfFrameSync.
GetNetMode()
FORCEINLINE_DEBUGGABLE ENetMode UActorComponent::GetNetMode () const
Get the network mode (dedicated server, client, standalone, etc) for this component.
See also
IsNetMode()
Definition at line 1440 of file ActorComponent.h.
References FORCEINLINE_DEBUGGABLE, InternalGetNetMode(), and IsRunningDedicatedServer().
Referenced by IsNetMode().
GetOwner()
template<class T> FORCEINLINE_DEBUGGABLE AActor * UActorComponent::GetOwner () const inline
Templated version of GetOwner(), will return nullptr if cast fails.
Definition at line 495 of file ActorComponent.h.
References Cast(), and GetOwner().
Referenced by FComponentEditorUtils::ApplyDefaultValueChange(), FNetworkPredictionDriverBase< ModelDef >::CallSetHiddenForInterpolationFallback(), FNetworkPredictionDriverBase< ModelDef >::GetDebugBoundingBox(), FNetworkPredictionDriverBase< ModelDef >::GetDebugWorldTransform(), UGameplayTasksComponent::GetGameplayTaskAvatar(), UGameplayTasksComponent::GetGameplayTaskOwner(), FReferenceGraphNode::GetObjectToDisplay(), GetOwner(), UE::DisplayClusterViewportHelpers::GetOwnerRootActorComponentByName(), FNetworkPredictionDriverBase< ModelDef >::GetTraceString(), FDisplayClusterSceneComponentRef::SetSceneComponent(), and UFUNCTION().
GetOwnerRole()
ENetRole UActorComponent::GetOwnerRole () const
Get the network role of the Owner, or ROLE_None if there is no owner.
Referenced by FNetworkPredictionDriverBase< ModelDef >::GetDebugString(), FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull(), and IsNetSimulating().
GetReadableName()
virtual FString UActorComponent::GetReadableName () const virtual
Returns a readable name for this component, including the asset name if applicable By default this appends a space plus AdditionalStatObject()
GetReplicatesPropertyName()
const FName UActorComponent::GetReplicatesPropertyName () inline static protected
Gets the property name for bReplicates.
This exists so subclasses don't need to have direct access to the bReplicates property so it can be made private later.
Definition at line 1402 of file ActorComponent.h.
References UActorComponent(), and GET_MEMBER_NAME_CHECKED.
GetReplicationCondition()
virtual ELifetimeCondition UActorComponent::GetReplicationCondition () const inline virtual
Returns the replication condition for the component.
Only works if the actor owning the component has bReplicateUsingRegisteredSubObjectList enabled.
Definition at line 610 of file ActorComponent.h.
References GetIsReplicated().
GetScene()
class FSceneInterface * UActorComponent::GetScene () const
Returns the rendering scene associated with this component.
GetStreamingBounds()
virtual FBox UActorComponent::GetStreamingBounds () const inline virtual
Reimplemented in ULightComponent, USceneComponent, and USpotLightComponent.
Definition at line 1195 of file ActorComponent.h.
References ForceInit.
Referenced by GetStreamingBoundsEditor().
GetStreamingBoundsEditor()
virtual FBox UActorComponent::GetStreamingBoundsEditor () const inline virtual
Definition at line 1196 of file ActorComponent.h.
References GetStreamingBounds().
GetUCSModifiedProperties()
void UActorComponent::GetUCSModifiedProperties (TSet< const FProperty * > & ModifiedProperties) const
Returns the list of properties that are modified by the UserConstructionScript.
GetUCSSerializationIndex()
int32 UActorComponent::GetUCSSerializationIndex () const inline
Returns the UCS serialization index.
This can be an expensive operation in the editor if you are dealing with a component that was saved before this information was present and it needs to be calculated.
Definition at line 406 of file ActorComponent.h.
References UActorComponent(), DetermineUCSSerializationIndexForLegacyComponent(), and GetUCSSerializationIndex().
Referenced by GetUCSSerializationIndex().
GetWorld()
virtual UWorld * UActorComponent::GetWorld () const inline final override virtual
Getter for the cached world pointer, will return null if the component is not actually spawned in a level.
Definition at line 501 of file ActorComponent.h.
References UObject::final, GetWorld_Uncached(), and WorldPrivate.
GetWorld_Uncached()
UWorld * UActorComponent::GetWorld_Uncached () const private
If WorldPrivate isn't set this will determine the world from outers.
Referenced by GetWorld().
HandleCanEverAffectNavigationChange()
void UActorComponent::HandleCanEverAffectNavigationChange (bool bForceUpdate = false) protected
Makes sure navigation system has up to date information regarding component's navigation relevancy and if it can affect navigation at all.
Parameters
bForceUpdate by default updating navigation system will take place only if the component has already been registered. Setting bForceUpdate to true overrides that check
HasBeenCreated()
bool UActorComponent::HasBeenCreated () const inline
Indicates that OnCreatedComponent has been called, but OnDestroyedComponent has not yet.
Definition at line 458 of file ActorComponent.h.
References bHasBeenCreated.
HasBeenInitialized()
bool UActorComponent::HasBeenInitialized () const inline
Indicates that InitializeComponent has been called, but UninitializeComponent has not yet.
Definition at line 461 of file ActorComponent.h.
References bHasBeenInitialized.
HasBegunPlay()
bool UActorComponent::HasBegunPlay () const inline
Indicates that BeginPlay has been called, but EndPlay has not yet.
Definition at line 467 of file ActorComponent.h.
References bHasBegunPlay.
HasValidPhysicsState()
virtual bool UActorComponent::HasValidPhysicsState () const inline protected virtual
Used to check that DestroyPhysicsState() is working correctly.
Definition at line 821 of file ActorComponent.h.
InitializeComponent()
virtual void UActorComponent::InitializeComponent () virtual
Initializes the component.
Occurs at level startup or actor spawn. This is before BeginPlay (Actor or Component).
All Components in the level will be Initialized on load before any Actor/Component gets BeginPlay Requires component to be registered, and bWantsInitializeComponent to be true.
Reimplemented in UAbilitySystemComponent, UBrainComponent, UPawnSensingComponent, UPhysicalAnimationComponent, and UPhysicsConstraintComponent.
InternalGetNetMode()
ENetMode UActorComponent::InternalGetNetMode () const private
Private version without inlining that does not check Dedicated server build flags (which should already have been done).
Referenced by GetNetMode(), and IsNetMode().
InvalidateLightingCache()
void UActorComponent::InvalidateLightingCache () inline
Invalidate lighting cache with default options.
Definition at line 1008 of file ActorComponent.h.
References InvalidateLightingCacheDetailed().
InvalidateLightingCacheDetailed()
virtual void UActorComponent::InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly) inline virtual
Called when this actor component has moved, allowing it to discard statically cached lighting information.
Reimplemented in UDirectionalLightComponent, ULightComponent, and UReflectionCaptureComponent.
Definition at line 1016 of file ActorComponent.h.
Referenced by InvalidateLightingCache().
IsAsyncCreatePhysicsStateRunning()
bool UActorComponent::IsAsyncCreatePhysicsStateRunning () const inline
Whether asynchronous physics state creation is running or not.
Definition at line 425 of file ActorComponent.h.
References Creating, PhysicsStateAsyncCreationScene, and PhysicsStateAsyncCreationState.
IsAsyncDestroyPhysicsStateRunning()
bool UActorComponent::IsAsyncDestroyPhysicsStateRunning () const inline
Whether asynchronous physics state destruction is running or not.
Definition at line 431 of file ActorComponent.h.
References Destroying, PhysicsStateAsyncCreationScene, and PhysicsStateAsyncCreationState.
IsAsyncPhysicsStateCreated()
virtual bool UActorComponent::IsAsyncPhysicsStateCreated () const final override virtual
Returns whether the physics state is created.
Reimplemented from IAsyncPhysicsStateProcessor.
References UObject::final.
IsCreatedByConstructionScript()
bool UActorComponent::IsCreatedByConstructionScript () const
Returns true if instances of this component are created by either the user or simple construction script.
Referenced by FComponentEditorUtils::ApplyDefaultValueChange().
IsEditableWhenInherited()
bool UActorComponent::IsEditableWhenInherited () const
True if this component can be modified when it was inherited from a parent actor class.
IsHLODRelevant()
virtual bool UActorComponent::IsHLODRelevant () const inline virtual
Override to specify that a component is relevant to the HLOD generation.
Reimplemented in UChildActorComponent.
Definition at line 1329 of file ActorComponent.h.
IsNameStableForNetworking()
virtual bool UActorComponent::IsNameStableForNetworking () const override virtual
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
Reimplemented from UObject.
IsNavigationRelevant()
virtual bool UActorComponent::IsNavigationRelevant () const inline virtual
Override to specify that a component is relevant to the navigation system.
Definition at line 1326 of file ActorComponent.h.
IsNetMode()
FORCEINLINE_DEBUGGABLE bool UActorComponent::IsNetMode (ENetMode Mode) const
Test whether net mode is the given mode.
In optimized non-editor builds this can be more efficient than GetNetMode() because it can check the static build flags without considering PIE.
Definition at line 1451 of file ActorComponent.h.
References FORCEINLINE_DEBUGGABLE, GetNetMode(), InternalGetNetMode(), and IsRunningDedicatedServer().
IsNetSimulating()
FORCEINLINE_DEBUGGABLE bool UActorComponent::IsNetSimulating () const
Returns true if we are replicating and this client is not authoritative.
Definition at line 1435 of file ActorComponent.h.
References FORCEINLINE_DEBUGGABLE, GetIsReplicated(), and GetOwnerRole().
IsNetStartupComponent()
bool UActorComponent::IsNetStartupComponent () const inline
Returns true if this component was owned by a net startup actor during level load.
Definition at line 706 of file ActorComponent.h.
References bIsNetStartupComponent.
IsOwnerRunningUserConstructionScript()
bool UActorComponent::IsOwnerRunningUserConstructionScript () const
See if the owning Actor is currently running the UCS.
Referenced by USceneComponent::AreDynamicDataChangesAllowed().
IsOwnerSelected()
bool UActorComponent::IsOwnerSelected () const
Returns whether the component's owner is selected in the editor.
IsPhysicsStateCreated()
bool UActorComponent::IsPhysicsStateCreated () const inline
Returns true if the physics 'state' (e.g.
physx bodies) are created for this component
Definition at line 1119 of file ActorComponent.h.
References bPhysicsStateCreated.
IsPreRegistered()
FORCEINLINE bool UActorComponent::IsPreRegistered () const inline
See if this component is currently pre-registered.
Definition at line 1225 of file ActorComponent.h.
References FORCEINLINE, PreRegistered, and RegistrationState.
IsPreRegistering()
FORCEINLINE bool UActorComponent::IsPreRegistering () const inline
See if this component is currently pre-registering.
Definition at line 1219 of file ActorComponent.h.
References FORCEINLINE, PreRegistering, and RegistrationState.
IsPreUnregistered()
FORCEINLINE bool UActorComponent::IsPreUnregistered () const inline
See if this component is currently pre-unregistered.
Definition at line 1237 of file ActorComponent.h.
References FORCEINLINE, PreUnregistered, and RegistrationState.
IsPreUnregistering()
FORCEINLINE bool UActorComponent::IsPreUnregistering () const inline
See if this component is currently pre-unregistering.
Definition at line 1231 of file ActorComponent.h.
References FORCEINLINE, PreUnregistering, and RegistrationState.
IsReadyForOwnerToAutoDestroy()
virtual bool UActorComponent::IsReadyForOwnerToAutoDestroy () const inline virtual
Overridable check for a component to indicate to its Owner that it should prevent the Actor from auto destroying when finished.
Reimplemented in UAudioComponent, and UForceFeedbackComponent.
Definition at line 993 of file ActorComponent.h.
References IsReadyForOwnerToAutoDestroy().
Referenced by IsReadyForOwnerToAutoDestroy().
IsReadyForReplication()
bool UActorComponent::IsReadyForReplication () const inline
Indicates that ReadyForReplication has been called.
Definition at line 464 of file ActorComponent.h.
References bIsReadyForReplication.
IsRegistered()
FORCEINLINE bool UActorComponent::IsRegistered () const inline
See if this component is currently registered.
Definition at line 1243 of file ActorComponent.h.
References bRegistered, and FORCEINLINE.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext(), and FComponentEditorUtils::ApplyDefaultValueChange().
IsRenderInstancesDirty()
bool UActorComponent::IsRenderInstancesDirty () const inline
Is this component's instance data in need of sending to the renderer?
Definition at line 1002 of file ActorComponent.h.
References bRenderInstancesDirty.
IsRenderStateCreated()
bool UActorComponent::IsRenderStateCreated () const inline
Returns true if the render 'state' (e.g.
scene proxy) is created for this component
Definition at line 1107 of file ActorComponent.h.
References bRenderStateCreated.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
IsRenderStateDirty()
bool UActorComponent::IsRenderStateDirty () const inline
Is this component in need of its whole state being sent to the renderer?
Definition at line 1005 of file ActorComponent.h.
References bRenderStateDirty.
IsRenderStateRecreating()
bool UActorComponent::IsRenderStateRecreating () const inline
Returns true if the render 'state' is being recreated for this component (see additional comments on variable above)
Definition at line 1113 of file ActorComponent.h.
References bRenderStateRecreating.
IsRenderTransformDirty()
bool UActorComponent::IsRenderTransformDirty () const inline
Is this component's transform in need of sending to the renderer?
Definition at line 999 of file ActorComponent.h.
References bRenderTransformDirty.
IsReplicatedSubObjectRegistered()
bool UActorComponent::IsReplicatedSubObjectRegistered (const UObject * SubObject) const
Tells if the object is registered to be replicated by this actor component.
References UObject::UObject().
IsSelectedInEditor()
virtual bool UActorComponent::IsSelectedInEditor () const override virtual
Test the selection state of a UObject.
Returns
true if the object is selected, false otherwise.
Todo
UE this doesn't belong here, but it doesn't belong anywhere else any better
Reimplemented from UObject.
IsSupportedForNetworking()
virtual bool UActorComponent::IsSupportedForNetworking () const override virtual
IsSupportedForNetworking means an object can be referenced over the network.
Reimplemented from UObject.
IsUsingRegisteredSubObjectList()
bool UActorComponent::IsUsingRegisteredSubObjectList () const inline
Returns if this component is replicating subobjects via the registration list or via the virtual ReplicateSubObjects method.
Note: the owning actor of this component must also have it's bReplicateUsingRegisteredSubObjectList flag set to true.
Definition at line 607 of file ActorComponent.h.
MarkForNeededEndOfFrameRecreate()
void UActorComponent::MarkForNeededEndOfFrameRecreate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
MarkForNeededEndOfFrameUpdate()
void UActorComponent::MarkForNeededEndOfFrameUpdate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
MarkRenderDynamicDataDirty()
void UActorComponent::MarkRenderDynamicDataDirty ()
Indicate that dynamic data for this component needs to be sent at the end of the frame.
MarkRenderInstancesDirty()
void UActorComponent::MarkRenderInstancesDirty ()
Marks the instances as dirty - changes to instance transforms/custom data will be sent to the render thread at the end of the frame.
MarkRenderStateDirty()
void UActorComponent::MarkRenderStateDirty ()
Mark the render state as dirty - will be sent to the render thread at the end of the frame.
Referenced by OnActorVisibilityChanged().
MarkRenderTransformDirty()
void UActorComponent::MarkRenderTransformDirty ()
Marks the transform as dirty - will be sent to the render thread at the end of the frame.
Modify()
virtual bool UActorComponent::Modify (bool bAlwaysMarkDirty = true) override virtual
Note that the object will be modified.
If we are currently recording into the transaction buffer (undo/redo), save a copy of this object into the buffer and marks the package as needing to be saved.
Parameters
bAlwaysMarkDirty if true, marks the package dirty even if we aren't currently recording an active undo/redo transaction
Returns
true if the object was saved to the transaction buffer
Reimplemented from UObject.
Referenced by FComponentEditorUtils::ApplyDefaultValueChange().
NeedsInitialization()
bool UActorComponent::NeedsInitialization () const protected
Convenience method for testing whether or not we are still be constructed / initialized.
NeedsLoadForClient()
virtual bool UActorComponent::NeedsLoadForClient () const override virtual
Called during saving to determine the load flags to save with the object.
If false, this object will be discarded on clients
Returns
true if this object should be loaded on clients
Reimplemented from UObject.
NeedsLoadForEditorGame()
virtual bool UActorComponent::NeedsLoadForEditorGame () const override virtual
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
If false, this object will still get loaded if NeedsLoadForServer/Client are true
Returns
true if this object should always be loaded for games running in editor builds
Reimplemented from UObject.
NeedsLoadForServer()
virtual bool UActorComponent::NeedsLoadForServer () const override virtual
Called during saving to determine the load flags to save with the object.
If false, this object will be discarded on servers
Returns
true if this object should be loaded on servers
Reimplemented from UObject.
OnActorEnableCollisionChanged()
virtual void UActorComponent::OnActorEnableCollisionChanged () inline virtual
Called on each component when the Actor's bEnableCollisionChanged flag changes.
Definition at line 1140 of file ActorComponent.h.
OnActorVisibilityChanged()
virtual void UActorComponent::OnActorVisibilityChanged () inline virtual
Called on each component when the Actor's visibility state changes.
Definition at line 1137 of file ActorComponent.h.
References MarkRenderStateDirty().
OnAsyncCreatePhysicsState()
virtual bool UActorComponent::OnAsyncCreatePhysicsState (const UE::FTimeout & TimeOut) override virtual
Used to create any physics engine information for this component outside of the GameThread.
Reimplemented from IAsyncPhysicsStateProcessor.
References OnAsyncCreatePhysicsState(), and Timeout.
Referenced by OnAsyncCreatePhysicsState().
OnAsyncCreatePhysicsStateEnd_GameThread()
virtual void UActorComponent::OnAsyncCreatePhysicsStateEnd_GameThread () override virtual
Called on the GameThread once the component's physic engine information is created.
Reimplemented from IAsyncPhysicsStateProcessor.
References OnAsyncCreatePhysicsStateEnd_GameThread().
Referenced by OnAsyncCreatePhysicsStateEnd_GameThread().
OnAsyncDestroyPhysicsState()
virtual bool UActorComponent::OnAsyncDestroyPhysicsState (const UE::FTimeout & TimeOut) inline override virtual
Used to destroy any physics engine information for this component outside of the GameThread.
Reimplemented from IAsyncPhysicsStateProcessor.
Definition at line 850 of file ActorComponent.h.
References OnAsyncDestroyPhysicsState(), and Timeout.
Referenced by OnAsyncDestroyPhysicsState().
OnAsyncDestroyPhysicsStateBegin_GameThread()
virtual void UActorComponent::OnAsyncDestroyPhysicsStateBegin_GameThread () override virtual
Called on the GameThread before the component's physic engine information is destroyed.
Reimplemented from IAsyncPhysicsStateProcessor.
OnAsyncDestroyPhysicsStateEnd_GameThread()
virtual void UActorComponent::OnAsyncDestroyPhysicsStateEnd_GameThread () override virtual
Called on the GameThread once the component's physic engine information is destroyed.
Reimplemented from IAsyncPhysicsStateProcessor.
OnComponentCreated()
virtual void UActorComponent::OnComponentCreated () virtual
Called when a component is created (not loaded).
This can happen in the editor or during gameplay
OnComponentDestroyed()
virtual void UActorComponent::OnComponentDestroyed (bool bDestroyingHierarchy) virtual
Called when a component is destroyed.
Parameters
bDestroyingHierarchy - True if the entire component hierarchy is being torn down, allows avoiding expensive operations
Reimplemented in UAbilitySystemComponent, UCameraComponent, UChildActorComponent, USceneCaptureComponent, USceneCaptureComponentCube, USceneComponent, and UVOIPTalker.
OnCreatedFromReplication()
void UActorComponent::OnCreatedFromReplication ()
OnCreatePhysicsState()
virtual void UActorComponent::OnCreatePhysicsState () protected virtual
Used to create any physics engine information for this component.
OnDestroyedFromReplication()
void UActorComponent::OnDestroyedFromReplication ()
OnDestroyPhysicsState()
virtual void UActorComponent::OnDestroyPhysicsState () protected virtual
Used to shut down and physics engine structure for this component.
OnEndOfFrameUpdateDuringTick()
virtual void UActorComponent::OnEndOfFrameUpdateDuringTick () inline virtual
Allows components to handle an EOF update happening mid tick.
Can be used to block on in-flight async tasks etc. This should ensure the the component's tick is complete so that it's render update is correct.
Definition at line 712 of file ActorComponent.h.
OnPreEndOfFrameSync()
virtual void UActorComponent::OnPreEndOfFrameSync () inline virtual
Allows components to wait on outstanding tasks prior to sending EOF update data.
Executed on Game Thread and may await tasks.
Definition at line 715 of file ActorComponent.h.
OnPreRegister()
virtual void UActorComponent::OnPreRegister () protected virtual
Called by PreRegisterComponentWithWorld when the component is being pre-registered.
Reimplemented in USceneComponent.
OnPreRegistered()
virtual void UActorComponent::OnPreRegistered () protected virtual
Called once the component is pre-registered.
OnPreUnregister()
virtual void UActorComponent::OnPreUnregister () protected virtual
Called by PreUnregisterComponentFromWorld when the component is being pre-unregistered.
OnPreUnregistered()
virtual void UActorComponent::OnPreUnregistered () protected virtual
Called once the component is pre-unregistered.
OnRegister()
virtual void UActorComponent::OnRegister () protected virtual
Called when a component is registered, after Scene is set, but before CreateRenderState_Concurrent or OnCreatePhysicsState are called.
Reimplemented in UAbilitySystemComponent, UAIPerceptionComponent, UAIPerceptionStimuliSourceComponent, UApplicationLifecycleComponent, UAudioComponent, UBrainComponent, UCameraComponent, UCameraShakeSourceComponent, UChildActorComponent, UDecalComponent, ULightComponent, ULightComponentBase, ULODSyncComponent, UPhysicsConstraintComponent, UPhysicsFieldComponent, UPlatformEventsComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneCaptureComponentCube, USceneComponent, USpringArmComponent, and UVolumetricCloudComponent.
Referenced by UWorldPartitionStreamingSourceComponent::GENERATED_UCLASS_BODY().
OnUnregister()
virtual void UActorComponent::OnUnregister () protected virtual
Called when a component is unregistered.
Called after DestroyRenderState_Concurrent and OnDestroyPhysicsState are called.
Reimplemented in UAbilitySystemComponent, UAIPerceptionComponent, UApplicationLifecycleComponent, UAudioComponent, UChildActorComponent, UForceFeedbackComponent, ULightComponentBase, ULODSyncComponent, UPhysicsConstraintComponent, UPhysicsFieldComponent, UPhysicsHandleComponent, UPlatformEventsComponent, UPostProcessComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneComponent, and UWorldPartitionStreamingSourceComponent.
OwnerNeedsInitialization()
bool UActorComponent::OwnerNeedsInitialization () const protected
Convenience method for testing whether or not our owner is still being constructed / initialized.
PostApplyToComponent()
virtual void UActorComponent::PostApplyToComponent () virtual
Called after ApplyToComponent has run.
PostEditChangeChainProperty()
virtual void UActorComponent::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
This alternate version of PostEditChange is called when properties inside structs are modified.
The property that was actually modified is located at the tail of the list. The head of the list of the FStructProperty member variable that contains the property that was modified.
Reimplemented from UObject.
Reimplemented in UChildActorComponent, UPhysicsConstraintComponent, and USceneComponent.
PostEditChangeProperty()
virtual void UActorComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Called when a property on this object has been modified externally.
Parameters
PropertyThatChanged the property that was modified
Reimplemented from UObject.
Reimplemented in UAIPerceptionStimuliSourceComponent, UAudioComponent, UBoxReflectionCaptureComponent, UCameraShakeSourceComponent, UChildActorComponent, UDirectionalLightComponent, UExponentialHeightFogComponent, ULightComponent, ULightComponentBase, ULocalFogVolumeComponent, ULocalLightComponent, UPhysicsConstraintComponent, UPointLightComponent, URadialForceComponent, URectLightComponent, UReflectionCaptureComponent, USceneCaptureComponent, USceneCaptureComponentCube, USceneComponent, USkyAtmosphereComponent, USkyLightComponent, USphereReflectionCaptureComponent, USpotLightComponent, and UVolumetricCloudComponent.
PostEditUndo()
virtual void UActorComponent::PostEditUndo () override virtual
Called after applying a transaction to the object.
Default implementation simply calls PostEditChange.
Reimplemented from UObject.
Reimplemented in UChildActorComponent.
PostInitProperties()
virtual void UActorComponent::PostInitProperties () override virtual
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
This is called before any serialization or other setup has happened.
Reimplemented from UObject.
Reimplemented in UAIPerceptionComponent, UReflectionCaptureComponent, and USkyLightComponent.
PostLoad()
virtual void UActorComponent::PostLoad () override virtual
Do any object-specific cleanup required immediately after loading an object.
This is not called for newly-created objects, and by default will always execute on the game thread.
Reimplemented from UObject.
Reimplemented in UAudioComponent, UChildActorComponent, UDecalComponent, ULightComponent, ULightComponentBase, UPhysicsConstraintComponent, URadialForceComponent, USceneCaptureComponent, USkyLightComponent, USpringArmComponent, and UWorldPartitionStreamingSourceComponent.
PostRename()
virtual void UActorComponent::PostRename (UObject * OldOuter, const FName OldName) override virtual
Called at the end of Rename(), but only if the rename was actually carried out.
Reimplemented from UObject.
References UObject::UObject().
PrecachePSOs()
virtual void UActorComponent::PrecachePSOs () inline protected virtual
Precache all PSOs which can be used by the actor component.
Reimplemented in UDecalComponent.
Definition at line 778 of file ActorComponent.h.
PreEditChange()
virtual void UActorComponent::PreEditChange (FProperty * PropertyAboutToChange) override virtual
This is called when a property is about to be modified externally.
Parameters
PropertyThatWillChange Property that will be changed
Reimplemented from UObject.
Reimplemented in UCameraShakeSourceComponent, and USkyLightComponent.
PreEditUndo()
virtual void UActorComponent::PreEditUndo () override virtual
Called before applying a transaction to the object.
Default implementation simply calls PreEditChange.
Reimplemented from UObject.
PreRegisterComponentWithWorld()
void UActorComponent::PreRegisterComponentWithWorld (UWorld * InWorld)
Pre-registers a component with a specific world.
Only called on components that return ShouldIncrementalPreRegister(). Will initialize the necessary before calling OnPreRegister().
Parameters
InWorld - The world to pre-register the component with.
References PreRegisterComponentWithWorld().
Referenced by PreRegisterComponentWithWorld().
PreReplication()
virtual void UActorComponent::PreReplication (IRepChangedPropertyTracker & ChangedPropertyTracker) inline virtual
Called on the component right before replication occurs.
Definition at line 613 of file ActorComponent.h.
PreUnregisterComponentFromWorld()
void UActorComponent::PreUnregisterComponentFromWorld ()
Pre-unregisters a component from a specific world.
Only called on components that return ShouldIncrementalPreUnregister().
References PreUnregisterComponentFromWorld().
Referenced by PreUnregisterComponentFromWorld().
ReadyForReplication()
virtual void UActorComponent::ReadyForReplication () virtual
ReadyForReplication gets called on replicated components when their owning actor is officially ready for replication.
Called after InitializeComponent but before BeginPlay. From there it will only be set false when the component is destroyed. This is where you want to register your replicated subobjects if you already possess some. A component can get replicated before HasBegunPlay() is true if inside a tick or in BeginPlay() an RPC is called on it. Requires component to be registered, initialized and set to replicate.
Reimplemented in UAbilitySystemComponent, and UGameplayTasksComponent.
RecreatePhysicsState()
void UActorComponent::RecreatePhysicsState ()
Recreate the physics state right way.
RecreateRenderState_Concurrent()
void UActorComponent::RecreateRenderState_Concurrent ()
Recreate the render state right away.
Generally you always want to call MarkRenderStateDirty instead.
Warning
This is called concurrently on multiple threads (but never the same component concurrently)
RegisterAllComponentTickFunctions()
UFUNCTION()) 1 void ReceiveEndPlay(EEndPlayReason void UActorComponent::RegisterAllComponentTickFunctions (bool bRegister)
Blueprint implementable event for when the component ends play, generally via destruction or its Actor's EndPlay.
When called, will call the virtual call chain to register all of the tick functions Do not override this function or make it virtual
Parameters
bRegister - true to register, false, to unregister
References RegisterAllComponentTickFunctions().
Referenced by RegisterAllComponentTickFunctions().
RegisterAsyncPhysicsTickEnabled()
void UActorComponent::RegisterAsyncPhysicsTickEnabled (bool bRegister) private
RegisterComponent()
void UActorComponent::RegisterComponent ()
Register this component, creating any rendering/physics state.
Will also add itself to the outer Actor's Components array, if not already present.
RegisterComponentTickFunctions()
virtual void UActorComponent::RegisterComponentTickFunctions (bool bRegister) protected virtual
Virtual call chain to register all tick functions.
Parameters
bRegister - true to register, false, to unregister
Referenced by UBehaviorTreeComponent::GENERATED_UCLASS_BODY().
RegisterComponentWithWorld()
void UActorComponent::RegisterComponentWithWorld (UWorld * InWorld, FRegisterComponentContext * Context = nullptr)
Registers a component with a specific world, which creates any visual/physical state.
Parameters
InWorld - The world to register the component with.
References RegisterComponentWithWorld().
Referenced by RegisterComponentWithWorld().
RemoveReplicatedSubObject()
void UActorComponent::RemoveReplicatedSubObject (UObject * SubObject)
Unregister a SubObject to stop replicating it's properties to clients.
This does not remove or delete it from connections where it was already replicated. By default a replicated subobject gets deleted on clients when the original pointer on the authority gets invalidated. If you want to immediately remove it from client use the DestroyReplicatedSubObjectOnRemotePeers or TearOffReplicatedSubObject functions instead of this one.
Parameters
SubObject The SubObject to remove
References UObject::UObject().
RemoveUCSModifiedProperties()
void UActorComponent::RemoveUCSModifiedProperties (const TArray< FProperty * > & Properties)
Removes specified properties from the list of UCS-modified properties.
RemoveUserDataOfClass()
virtual void UActorComponent::RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override virtual
Reimplemented from IInterface_AssetUserData.
Rename()
virtual bool UActorComponent::Rename (const TCHAR * NewName = NULL, UObject * NewOuter = NULL, ERenameFlags Flags = REN_None) override virtual
Rename this object to a unique name, or change its outer.
Remarks
A unique name will be generated if NewName is null and if either is true: NewOuter is null or NewOuter equals the current outer.
Parameters
NewName The new name of the object, if null then NewOuter should be set
NewOuter New Outer this object will be placed within, if null it will use the current outer
Flags Flags to specify what happens during the rename
Reimplemented from UObject.
References UObject::UObject(), Flags, and REN_None.
ReplicateSubobjects()
virtual bool UActorComponent::ReplicateSubobjects (class UActorChannel * Channel, class FOutBunch * Bunch, FReplicationFlags * RepFlags) virtual
Allows a component to replicate other subobject on the actor.
Must return true if any data gets serialized into the bunch. This method is used only when bReplicateUsingRegisteredSubObjectList is false. Otherwise this function is not called and only the ReplicatedSubObjects list is used.
Reimplemented in UAbilitySystemComponent, and UGameplayTasksComponent.
RequiresGameThreadEndOfFrameRecreate()
virtual bool UActorComponent::RequiresGameThreadEndOfFrameRecreate () const virtual
return true if this component requires end of frame recreates to happen from the game thread.
RequiresGameThreadEndOfFrameUpdates()
virtual bool UActorComponent::RequiresGameThreadEndOfFrameUpdates () const virtual
return true if this component requires end of frame updates to happen from the game thread.
RequiresPreEndOfFrameSync()
virtual bool UActorComponent::RequiresPreEndOfFrameSync () const virtual
return true if this component needs to sync to tasks before end of frame updates are executed
ReregisterComponent()
void UActorComponent::ReregisterComponent ()
Unregisters and immediately re-registers component.
References ReregisterComponent().
Referenced by FComponentEditorUtils::ApplyDefaultValueChange(), FComponentEditorUtils::ApplyDefaultValueChange(), and ReregisterComponent().
SendRenderDynamicData_Concurrent()
virtual void UActorComponent::SendRenderDynamicData_Concurrent () protected virtual
Called to send dynamic data for this component to the rendering thread.
Reimplemented in UPhysicsFieldComponent, and UWindDirectionalSourceComponent.
SendRenderInstanceData_Concurrent()
virtual void UActorComponent::SendRenderInstanceData_Concurrent () protected virtual
Called to send instance data for this component to the rendering thread.
SendRenderTransform_Concurrent()
virtual void UActorComponent::SendRenderTransform_Concurrent () protected virtual
Called to send a transform update for this component to the rendering thread.
Warning
This is called concurrently on multiple threads (but never the same component concurrently)
Reimplemented in UDecalComponent, UExponentialHeightFogComponent, ULightComponent, ULightmassPortalComponent, ULocalFogVolumeComponent, ULocalLightComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponentCube, USkyAtmosphereComponent, USkyLightComponent, and UWindDirectionalSourceComponent.
Serialize()
virtual void UActorComponent::Serialize (FArchive & Ar) override virtual
Handles reading, writing, and reference collecting using FArchive.
This implementation handles all FProperty serialization, but can be overridden for native variables.
Reimplemented from UObject.
Reimplemented in UAudioComponent, UChildActorComponent, UDecalComponent, UDirectionalLightComponent, UExponentialHeightFogComponent, ULightComponent, ULightComponentBase, ULocalLightComponent, UPointLightComponent, UPostProcessComponent, URectLightComponent, UReflectionCaptureComponent, URuntimeVirtualTextureComponent, USceneCaptureComponent, USceneCaptureComponentCube, USceneComponent, USkyAtmosphereComponent, USkyLightComponent, UVolumetricCloudComponent, and UWorldPartitionStreamingSourceComponent.
References Ar.
SetActiveFlag()
void UActorComponent::SetActiveFlag (const bool bNewIsActive)
Sets the value of bIsActive without causing other side effects to this instance.
Activate, Deactivate, and SetActive are preferred in most cases because they respect virtual behavior.
SetAsyncPhysicsTickEnabled()
void UActorComponent::SetAsyncPhysicsTickEnabled (bool bEnabled) protected
Sets bAsyncPhysicsTickEnabled which determines whether to use use the async physics tick with this component.
SetCanEverAffectNavigation()
void UActorComponent::SetCanEverAffectNavigation (bool bRelevant)
Sets value of bCanEverAffectNavigation flag and update navigation octree if needed.
Note
This flag influences the required updates when setting other properties associated to the navigation data (e.g., transform, primitive, mesh, etc.). So when setting it to 'true' it is more efficient to set the other properties first, otherwise ('false') it is more efficient to set this one first, then the other properties.
SetComponentTickEnabledAsync()
virtual void UActorComponent::SetComponentTickEnabledAsync (bool bEnabled) virtual
Spawns a task on GameThread that will call SetComponentTickEnabled.
Parameters
bEnabled - Whether it should be enabled or not
References SetComponentTickEnabledAsync().
Referenced by SetComponentTickEnabledAsync().
SetIsNetStartupComponent()
void UActorComponent::SetIsNetStartupComponent (const bool bInIsNetStartupComponent) inline
This should only be called by the engine in ULevel::InitializeNetworkActors to initialize bIsNetStartupComponent.
Definition at line 709 of file ActorComponent.h.
References bIsNetStartupComponent.
SetIsReplicatedByDefault()
void UActorComponent::SetIsReplicatedByDefault (const bool bNewReplicates) protected
Sets the value of bReplicates without causing other side effects to this instance.
This should only be called during component construction.
This method exists only to allow code to directly modify bReplicates to maintain existing behavior.
SetNetAddressable()
void UActorComponent::SetNetAddressable ()
This signifies the component can be ID'd by name over the network.
This only needs to be called by engine code when constructing blueprint components.
References SetNetAddressable().
Referenced by SetNetAddressable().
SetPackageExternal()
virtual void UActorComponent::SetPackageExternal (bool bExternal, bool bShouldDirty) inline virtual
Reimplemented in UChildActorComponent.
Definition at line 1194 of file ActorComponent.h.
SetupActorComponentTickFunction()
bool UActorComponent::SetupActorComponentTickFunction (struct FTickFunction * TickFunction)
Set up a tick function for a component in the standard way.
Tick after the actor. Don't tick if the actor is static, or if the actor is a template or if this is a "NeverTick" component. I tick while paused if only if my owner does.
Parameters
TickFunction - structure holding the specific tick function
Returns
true if this component met the criteria for actually being ticked.
ShouldActivate()
virtual bool UActorComponent::ShouldActivate () const protected virtual
Return true if this component is in a state where it can be activated normally.
ShouldAsyncCreatePhysicsState()
virtual bool UActorComponent::ShouldAsyncCreatePhysicsState (UWorld * WorldContext) const protected virtual
Returns whether this component should create its physics state asynchronously.
ShouldAsyncDestroyPhysicsState()
virtual bool UActorComponent::ShouldAsyncDestroyPhysicsState () const protected virtual
Returns whether this component should destroy its physics state asynchronously.
ShouldCreatePhysicsState()
virtual bool UActorComponent::ShouldCreatePhysicsState () const inline protected virtual
Return true if CreatePhysicsState() should be called.
Ideally CreatePhysicsState() should always succeed if this returns true, but this isn't currently the case
Definition at line 818 of file ActorComponent.h.
ShouldCreateRenderState()
virtual bool UActorComponent::ShouldCreateRenderState () const inline protected virtual
Return true if CreateRenderState() should be called.
Reimplemented in URuntimeVirtualTextureComponent, and USceneComponent.
Definition at line 781 of file ActorComponent.h.
ShouldIncrementalPreRegister()
virtual bool UActorComponent::ShouldIncrementalPreRegister (UWorld * WorldContext) const virtual
Returns whether PreRegisterComponentWithWorld should be called for this component when its Level is being added to the world.
ShouldIncrementalPreUnregister()
virtual bool UActorComponent::ShouldIncrementalPreUnregister () const virtual
Returns whether PreUnregisterComponentFromWorld should be called for this component when its Level is being removed from the world.
TearOffReplicatedSubObjectOnRemotePeers()
void UActorComponent::TearOffReplicatedSubObjectOnRemotePeers (UObject * SubObject)
Stop replicating a subobject and tell actor channels who spawned a replica of this subobject to release ownership over it.
This means that on the remote connection the network engine will stop holding a reference to the subobject and it's up to other systems to keep that reference active or the subobject will get garbage collected. If you are using the legacy subobject replication method (ReplicateSubObjects() aka bReplicateUsingRegisteredSubObjectList=false) make sure the subobject doesn't get replicated there either.
Parameters
SubObject The SubObject to tear off
References UObject::UObject().
Tick()
virtual void UActorComponent::Tick (float DeltaTime) inline final private virtual
This is the old name of the tick function.
We just want to avoid mistakes with an attempt to override this
Definition at line 1367 of file ActorComponent.h.
References check, and DeltaTime.
TickComponent()
virtual void UActorComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) virtual
Function called every frame on this ActorComponent.
Override this function to implement custom logic to be executed every frame. Only executes if the component is registered, and also PrimaryComponentTick.bCanEverTick must be set to true.
Parameters
DeltaTime - The time since the last tick.
TickType - The kind of tick this is, for example, are we paused, or 'simulating' in the editor
ThisTickFunction - Internal tick function struct that caused this to run
Reimplemented in UAbilitySystemComponent, UBehaviorTreeComponent, UBrainComponent, UCameraComponent, UGameplayTasksComponent, ULODSyncComponent, UPhysicalAnimationComponent, UPhysicsFieldComponent, UPhysicsHandleComponent, UPhysicsSpringComponent, URadialForceComponent, USceneCaptureComponentCube, and USpringArmComponent.
References DeltaTime, FActorComponentTickFunction, and TickComponent().
Referenced by TickComponent().
UFUNCTION() [1/26]
UActorComponent::UFUNCTION () const
See if this component contains the supplied tag.
References Category.
UFUNCTION() [2/26]
UActorComponent::UFUNCTION () const
Returns the tick interval for this component's primary tick function, which is the frequency in seconds at which it will be executed.
References Category, and UFUNCTION().
UFUNCTION() [3/26]
UActorComponent::UFUNCTION () const
Returns whether this component has tick enabled or not.
References Category, and UFUNCTION().
UFUNCTION() [4/26]
UActorComponent::UFUNCTION ()
Handles replication of active state, handles ticking by default but should be overridden as needed.
UFUNCTION() [5/26]
UActorComponent::UFUNCTION ()
Sets whether the component should be auto activate or not.
Only safe during construction scripts.
Parameters
bNewAutoActivate - The new auto activate state of the component
References Category.
UFUNCTION() [6/26]
UActorComponent::UFUNCTION ()
Set this component's tick functions to be enabled or disabled.
Only has an effect if the function is registered
Parameters
bEnabled - Whether it should be enabled or not
References Category.
UFUNCTION() [7/26]
UActorComponent::UFUNCTION ()
Sets the tick interval for this component's primary tick function.
Does not enable the tick interval. Takes effect on next tick.
Parameters
TickInterval The duration between ticks for this component's primary tick function
References Category, and UFUNCTION().
UFUNCTION() [8/26]
UActorComponent::UFUNCTION ()
Sets the tick interval for this component's primary tick function.
Does not enable the tick interval. Takes effect imediately.
Parameters
TickInterval The duration between ticks for this component's primary tick function
References Category, and UFUNCTION().
UFUNCTION() [9/26]
UActorComponent::UFUNCTION ()
Enable or disable replication.
This is the equivalent of RemoteRole for actors (only a bool is required for components)
References Category, and UFUNCTION().
UFUNCTION() [10/26]
UActorComponent::UFUNCTION ()
Sets whether this component can tick when paused.
References Category, and UFUNCTION().
UFUNCTION() [11/26]
UActorComponent::UFUNCTION ()
Activates the SceneComponent, should be overridden by native child classes.
Parameters
bReset - Whether the activation should happen even if ShouldActivate returns false.
References Activate, bReset, Category, and meta.
UFUNCTION() [12/26]
UActorComponent::UFUNCTION ()
Make this component tick after PrerequisiteActor.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [13/26]
UActorComponent::UFUNCTION ()
Make this component tick after PrerequisiteComponent.
References UActorComponent(), Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [14/26]
UActorComponent::UFUNCTION ()
Deactivates the SceneComponent.
References Category, Deactivate, meta, and UFUNCTION().
UFUNCTION() [15/26]
UActorComponent::UFUNCTION ()
Remove tick dependency on PrerequisiteActor.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [16/26]
UActorComponent::UFUNCTION ()
Remove tick dependency on PrerequisiteComponent.
References UActorComponent(), Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [17/26]
UActorComponent::UFUNCTION ()
Sets whether the component is active or not.
Parameters
bNewActive - The new active state of the component
bReset - Whether the activation should happen even if ShouldActivate returns false.
References Category, meta, and UFUNCTION().
UFUNCTION() [18/26]
UActorComponent::UFUNCTION ()
Toggles the active state of the component.
References Category, meta, and UFUNCTION().
UFUNCTION() [19/26]
UActorComponent::UFUNCTION ()
Unregister and mark for pending kill a component.
This may not be used to destroy a component that is owned by an actor unless the owning actor is calling the function.
References UObject::UObject(), Category, Keywords, meta, and Object.
UFUNCTION() [20/26]
UActorComponent::UFUNCTION ()
Event called every async physics tick if bAsyncPhysicsTickEnabled is true.
References meta, and UFUNCTION().
UFUNCTION() [21/26]
UActorComponent::UFUNCTION ()
Blueprint implementable event for when the component is beginning play, called before its owning actor's BeginPlay or when the component is dynamically created if the Actor has already BegunPlay.
References meta.
UFUNCTION() [22/26]
UActorComponent::UFUNCTION ()
Event called every frame if tick is enabled.
References meta, and UFUNCTION().
UFUNCTION() [23/26]
UActorComponent::UFUNCTION ()
Changes the ticking group for this component.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [24/26]
UActorComponent::UFUNCTION () const
Follow the Outer chain to get the AActor that 'Owns' this component.
References Category, GetOwner(), Keywords, meta, and UFUNCTION().
UFUNCTION() [25/26]
UActorComponent::UFUNCTION () const inline
Returns whether the component is active or not.
Returns
- The active state of the component.
Definition at line 559 of file ActorComponent.h.
References Category, meta, and UFUNCTION().
UFUNCTION() [26/26]
UActorComponent::UFUNCTION () const inline
Returns whether the component is in the process of being destroyed.
Definition at line 472 of file ActorComponent.h.
References bIsBeingDestroyed, bool, Category, and meta.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UninitializeComponent().
UninitializeComponent()
virtual void UActorComponent::UninitializeComponent () virtual
Handle this component being Uninitialized.
Called from AActor::EndPlay only if bHasBeenInitialized is true
Reimplemented in UAbilitySystemComponent, and UBehaviorTreeComponent.
References Keywords, meta, UFUNCTION(), and UninitializeComponent().
Referenced by UninitializeComponent().
UnregisterComponent()
void UActorComponent::UnregisterComponent ()
Unregister this component, destroying any rendering/physics state.
UpdateComponentToWorld()
virtual void UActorComponent::UpdateComponentToWorld (EUpdateTransformFlags UpdateTransformFlags = EUpdateTransformFlags::None, ETeleportType Teleport = ETeleportType::None) inline virtual
Recalculate the value of our component to world transform.
Reimplemented in USceneComponent.
Definition at line 1065 of file ActorComponent.h.
References None.
UPROPERTY() [1/7]
UActorComponent::UPROPERTY ()
Describes how a component instance will be created.
UPROPERTY() [2/7]
UActorComponent::UPROPERTY ()
Called when the component has been activated, with parameter indicating if it was from a reset.
References Category, and UPROPERTY().
UPROPERTY() [3/7]
UActorComponent::UPROPERTY ()
Called when the component has been deactivated.
References Category, and UPROPERTY().
UPROPERTY() [4/7]
UActorComponent::UPROPERTY () private
Populated when the component is created and tracks the often used order of creation on a per archetype/per actor basis.
UPROPERTY() [5/7]
UActorComponent::UPROPERTY () private
Main tick function for the Component.
References Category, and FActorComponentTickFunction.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [6/7]
UActorComponent::UPROPERTY () private
Array of tags that can be used for grouping and categorizing.
Can also be accessed from scripting.
References Category, Tags, and UPROPERTY().
UPROPERTY() [7/7]
UActorComponent::UPROPERTY () protected
Array of user data stored with the component.
References Category, and UPROPERTY().
Friends And Related Symbol Documentation
FActorComponentDetails
friend class FActorComponentDetails friend
Definition at line 1376 of file ActorComponent.h.
References FActorComponentDetails.
Referenced by FActorComponentDetails.
FActorComponentTickFunction
friend struct FActorComponentTickFunction friend
Definition at line 1379 of file ActorComponent.h.
References FActorComponentTickFunction.
Referenced by FActorComponentTickFunction, UAbilitySystemComponent::TickComponent(), TickComponent(), UBehaviorTreeComponent::TickComponent(), UBrainComponent::TickComponent(), UCameraComponent::TickComponent(), UGameplayTasksComponent::TickComponent(), ULODSyncComponent::TickComponent(), UPhysicalAnimationComponent::TickComponent(), UPhysicsFieldComponent::TickComponent(), UPhysicsHandleComponent::TickComponent(), UPhysicsSpringComponent::TickComponent(), URadialForceComponent::TickComponent(), USceneCaptureComponentCube::TickComponent(), USpringArmComponent::TickComponent(), and UPROPERTY().
FComponentRecreateRenderStateContext
friend class FComponentRecreateRenderStateContext friend
Definition at line 1378 of file ActorComponent.h.
References FComponentRecreateRenderStateContext.
Referenced by FComponentRecreateRenderStateContext.
FComponentReregisterContextBase
friend class FComponentReregisterContextBase friend
Definition at line 1377 of file ActorComponent.h.
References FComponentReregisterContextBase.
Referenced by FComponentReregisterContextBase.
FMarkComponentEndOfFrameUpdateState
friend struct FMarkComponentEndOfFrameUpdateState friend
Definition at line 1374 of file ActorComponent.h.
References FMarkComponentEndOfFrameUpdateState.
Referenced by FMarkComponentEndOfFrameUpdateState.
FSetUCSSerializationIndex
friend struct FSetUCSSerializationIndex friend
Definition at line 1375 of file ActorComponent.h.
References FSetUCSSerializationIndex.
Referenced by FSetUCSSerializationIndex.
SkeletalMeshUCSModifiedDataCleanupHelper
friend struct SkeletalMeshUCSModifiedDataCleanupHelper friend
Definition at line 1381 of file ActorComponent.h.
References SkeletalMeshUCSModifiedDataCleanupHelper.
Referenced by SkeletalMeshUCSModifiedDataCleanupHelper.
Field Documentation
AllUCSModifiedProperties
TMap<UActorComponent*, TArray<FSimpleMemberReference> > UActorComponent::AllUCSModifiedProperties static
Definition at line 525 of file ActorComponent.h.
AllUCSModifiedPropertiesLock
FTransactionallySafeRWLock UActorComponent::AllUCSModifiedPropertiesLock static
Definition at line 524 of file ActorComponent.h.
bAllowAnyoneToDestroyMe
uint8 UActorComponent::bAllowAnyoneToDestroyMe
Can this component be destroyed (via K2_DestroyComponent) by any parent.
Definition at line 279 of file ActorComponent.h.
bAllowConcurrentTick
uint8 UActorComponent::bAllowConcurrentTick
Can we tick this concurrently on other threads?
Definition at line 276 of file ActorComponent.h.
bAllowReregistration
uint8 UActorComponent::bAllowReregistration protected
Check whether the component class allows reregistration during ReregisterAllComponents.
Definition at line 266 of file ActorComponent.h.
Referenced by AllowReregistration().
bAsyncPhysicsTickEnabled
uint8 UActorComponent::bAsyncPhysicsTickEnabled private
Whether to use use the async physics tick with this component.
Definition at line 382 of file ActorComponent.h.
bAutoRegister
uint8 UActorComponent::bAutoRegister
Does this component automatically register with its owner.
Definition at line 262 of file ActorComponent.h.
bCallAsyncPhysicsStateCreatedDelegate
uint8 UActorComponent::bCallAsyncPhysicsStateCreatedDelegate protected
If the physics state was created while component was pre-registering, notification to GameThread is deferred next time CreatePhysicsState is called.
Definition at line 227 of file ActorComponent.h.
bCanUseCachedOwner
uint8 UActorComponent::bCanUseCachedOwner private
During undo/redo it isn't safe to cache owner.
Definition at line 366 of file ActorComponent.h.
bHasBeenCreated
uint8 UActorComponent::bHasBeenCreated private
If true, the component will be excluded from non-editor builds.
Indicates that OnCreatedComponent has been called, but OnDestroyedComponent has not yet
Definition at line 335 of file ActorComponent.h.
Referenced by HasBeenCreated().
bHasBeenInitialized
uint8 UActorComponent::bHasBeenInitialized private
Indicates that InitializeComponent has been called, but UninitializeComponent has not yet.
Definition at line 338 of file ActorComponent.h.
Referenced by HasBeenInitialized().
bHasBegunPlay
uint8 UActorComponent::bHasBegunPlay private
Indicates that BeginPlay has been called, but EndPlay has not yet.
Definition at line 344 of file ActorComponent.h.
Referenced by HasBegunPlay().
bIsBeingDestroyed
uint8 UActorComponent::bIsBeingDestroyed private
Indicates the the destruction process has begun for this component to avoid recursion.
Definition at line 347 of file ActorComponent.h.
Referenced by UFUNCTION().
bIsNetStartupComponent
uint8 UActorComponent::bIsNetStartupComponent private
True if this component was owned by a net startup actor during level load.
Definition at line 373 of file ActorComponent.h.
Referenced by IsNetStartupComponent(), and SetIsNetStartupComponent().
bIsReadyForReplication
uint8 UActorComponent::bIsReadyForReplication private
Indicates that ReadyForReplication has been called.
Definition at line 341 of file ActorComponent.h.
Referenced by IsReadyForReplication().
bMarkedForPreEndOfFrameSync
uint8 UActorComponent::bMarkedForPreEndOfFrameSync private
Tracks whether the component has been added to the world's pre end of frame sync list.
Definition at line 379 of file ActorComponent.h.
Referenced by GetMarkedForPreEndOfFrameSync().
bMarkPendingKillOnPostLoad
uint8 UActorComponent::bMarkPendingKillOnPostLoad private
Marks this component pending kill once PostLoad occurs.
Used to clean up old native default subobjects that were removed from code
Definition at line 369 of file ActorComponent.h.
bNavigationRelevant
UPROPERTY () uint8 bEditableWhenInherited uint8 UActorComponent::bNavigationRelevant
Whether the component is activated at creation or must be explicitly activated.
Whether the component is currently active. True if this component can be modified when it was inherited from a parent actor class Cached navigation relevancy flag for collision updates
Definition at line 307 of file ActorComponent.h.
bNeverNeedsRenderUpdate
uint8 UActorComponent::bNeverNeedsRenderUpdate
If true, this component never needs a render update.
Definition at line 273 of file ActorComponent.h.
bPhysicsStateCreated
uint8 UActorComponent::bPhysicsStateCreated protected
If the physics state is currently created for this component.
Definition at line 224 of file ActorComponent.h.
Referenced by IsPhysicsStateCreated().
bRegistered
uint8 UActorComponent::bRegistered protected
Indicates if this ActorComponent is currently registered with a scene.
Definition at line 210 of file ActorComponent.h.
Referenced by IsRegistered().
bRenderDynamicDataDirty
uint8 UActorComponent::bRenderDynamicDataDirty private
Is this component's dynamic data in need of sending to the renderer?
Definition at line 252 of file ActorComponent.h.
bRenderInstancesDirty
uint8 UActorComponent::bRenderInstancesDirty private
Is this component's instanced data in need of sending to the renderer?
Definition at line 255 of file ActorComponent.h.
Referenced by IsRenderInstancesDirty().
bRenderStateCreated
uint8 UActorComponent::bRenderStateCreated protected
If the render state is currently created for this component.
Definition at line 213 of file ActorComponent.h.
Referenced by IsRenderStateCreated().
bRenderStateDirty
UPROPERTY ()) uint8 bReplicates uint8 UActorComponent::bRenderStateDirty private
Is this component safe to ID over the network by name?
When true the replication system will only replicate the registered subobjects list When false the replication system will instead call the virtual ReplicateSubObjects() function where the subobjects need to be manually replicated. Is this component currently replicating? Should the network code consider it for replication? Owning Actor must be replicating first! Is this component in need of its whole state being sent to the renderer?
Definition at line 246 of file ActorComponent.h.
Referenced by IsRenderStateDirty().
bRenderStateRecreating
uint8 UActorComponent::bRenderStateRecreating protected
Render state is being recreated for this component.
Useful if a component wants to preserve certain render state across recreate – set before a call to DestroyRenderState_Concurrent and cleared after the corresponding call to CreateRenderState_Concurrent. By design, only set for re-creation due to MarkRenderStateDirty, not RecreateRenderStateContext variations. The latter are used for editor operations, file loads, or bulk setting changes, which are assumed to potentially change render data in a way that could make preserved render state incompatible.
Definition at line 221 of file ActorComponent.h.
Referenced by IsRenderStateRecreating().
bRenderTransformDirty
uint8 UActorComponent::bRenderTransformDirty private
Is this component's transform in need of sending to the renderer?
Definition at line 249 of file ActorComponent.h.
Referenced by IsRenderTransformDirty().
bReset
bool UActorComponent::bReset =false)
Definition at line 547 of file ActorComponent.h.
Referenced by UAudioComponent::Activate(), UForceFeedbackComponent::Activate(), UWindDirectionalSourceComponent::Activate(), and UFUNCTION().
bRoutedPostRename
uint8 UActorComponent::bRoutedPostRename private
Used to ensure that any subclass of UActorComponent that overrides PostRename calls up to the Super to make OwnedComponents arrays get updated correctly.
Definition at line 258 of file ActorComponent.h.
bTickFunctionsRegistered
uint8 UActorComponent::bTickFunctionsRegistered private
Whether we've tried to register tick functions.
Reset when they are unregistered.
Definition at line 350 of file ActorComponent.h.
bTickInEditor
uint8 UActorComponent::bTickInEditor
Should this component be ticked in the editor.
Definition at line 270 of file ActorComponent.h.
bWantsInitializeComponent
uint8 UActorComponent::bWantsInitializeComponent
Whether this component can potentially influence navigation.
If true, we call the virtual InitializeComponent
Definition at line 316 of file ActorComponent.h.
ComponentTemplateNameSuffix
const FString UActorComponent::ComponentTemplateNameSuffix static
Suffix used to identify template component instances.
Definition at line 1340 of file ActorComponent.h.
GlobalDestroyPhysicsDelegate
GENERATED_BODY () public FActorComponentGlobalDestroyPhysicsSignature UActorComponent::GlobalDestroyPhysicsDelegate static private
Create component physics state global delegate.
Destroy component physics state global delegate.
Definition at line 153 of file ActorComponent.h.
MarkedForEndOfFrameUpdateArrayIndex
int32 UActorComponent::MarkedForEndOfFrameUpdateArrayIndex private
Used for fast removal of end of frame update.
Definition at line 182 of file ActorComponent.h.
MarkedForEndOfFrameUpdateState
uint8 UActorComponent::MarkedForEndOfFrameUpdateState private
Tracks whether the component has been added to one of the world's end of frame update lists.
Definition at line 376 of file ActorComponent.h.
Referenced by ClearNeedEndOfFrameUpdate(), and GetMarkedForEndOfFrameUpdateState().
MarkRenderStateDirtyEvent
FOnMarkRenderStateDirty UActorComponent::MarkRenderStateDirtyEvent static
Called When render state is marked dirty.
Definition at line 1345 of file ActorComponent.h.
OwnerPrivate
AActor* UActorComponent::OwnerPrivate mutable private
Cached pointer to owning actor.
Definition at line 356 of file ActorComponent.h.
PhysicsStateAsyncCreationScene
FPhysScene* UActorComponent::PhysicsStateAsyncCreationScene private
If non-null, physics state creation/destruction is done asynchronously by FPhysScene_Chaos::ProcessAsyncPhysicsStateJobs.
Definition at line 353 of file ActorComponent.h.
Referenced by IsAsyncCreatePhysicsStateRunning(), and IsAsyncDestroyPhysicsStateRunning().
PhysicsStateAsyncCreationState
EPhysicsStateAsyncCreationState UActorComponent::PhysicsStateAsyncCreationState private
Whether the component is creating/destroying its physics state asynchronously (or not)
Definition at line 392 of file ActorComponent.h.
Referenced by IsAsyncCreatePhysicsStateRunning(), and IsAsyncDestroyPhysicsStateRunning().
RegistrationState
EComponentRegistrationState UActorComponent::RegistrationState protected
Indicates if this ActorComponent is currently pre-registering or pre-registered with a scene.
Definition at line 205 of file ActorComponent.h.
Referenced by IsPreRegistered(), IsPreRegistering(), IsPreUnregistered(), and IsPreUnregistering().
SimSeconds
float UActorComponent::SimSeconds
Definition at line 1302 of file ActorComponent.h.
WorldPrivate
UWorld* UActorComponent::WorldPrivate private
Pointer to the world that this component is currently registered with.
This is only non-NULL when the component is registered.
Definition at line 362 of file ActorComponent.h.
Referenced by GetWorld().
The documentation for this class was generated from the following file:
ActorComponent.h