Unreal Engine 5.6 C++ API: UE::Geometry::FSparseDynamicOctree3 Class Reference
UE::Geometry::FSparseDynamicOctree3 Class Reference
FSparseDynamicOctree3 sorts objects with axis-aligned bounding boxes into a dynamic sparse octree of axis-aligned uniform grid cells.
#include "SparseDynamicOctree3.h"
Data Structures
struct FStatistics
statistics about internal structure of the octree
Public Member Functions
GEOMETRYCORE_API bool CheckIfObjectNeedsReinsert (int32 ObjectID, const FAxisAlignedBox3d &NewBounds, uint32 &CellIDOut) const
Check if the object needs to be reinserted, if it has NewBounds.
GEOMETRYCORE_API void CheckValidity (TFunctionRef< bool(int)> IsValidObjectIDFunc, TFunctionRef< FAxisAlignedBox3d(int)> GetObjectBoundsFunc, EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check, bool bVerbose=false, bool bFailOnMissingObjects=false) const
Check that the octree is internally valid.
GEOMETRYCORE_API void ComputeStatistics (FStatistics &StatsOut) const
Populate given FStatistics with info about the octree.
GEOMETRYCORE_API void ContainmentQuery (const FVector3d &Point, TFunctionRef< void(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that contain query point.
GEOMETRYCORE_API bool ContainmentQueryCancellable (const FVector3d &Point, TFunctionRef< bool(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that contain query point.
GEOMETRYCORE_API bool ContainsObject (int32 ObjectID) const
Test if an object is stored in the tree.
GEOMETRYCORE_API int32 FindNearestHitObject (const FRay3d &Ray, TFunctionRef< FAxisAlignedBox3d(int)> GetObjectBoundsFunc, TFunctionRef< double(int, const FRay3d &)> HitObjectDistFunc, double MaxDistance=TNumericLimits< double >::Max()) const
Find nearest ray-hit point with objects in tree.
int GetMaxTreeDepth ()
GEOMETRYCORE_API void InsertObject (int32 ObjectID, const FAxisAlignedBox3d &Bounds)
Insert ObjectID into the Octree.
int ParallelOverlapAnyQuery (const FAxisAlignedBox3d &ShapeBounds, TFunctionRef< bool(int32)> ObjectOverlapFn) const
Find any overlap between a caller-defined query and any object ID.
GEOMETRYCORE_API int ParallelOverlapAnyQuery (const FAxisAlignedBox3d &ShapeBounds, TFunctionRef< bool(int32)> ObjectOverlapFn, TFunctionRef< bool(const FAxisAlignedBox3d &)> BoundsOverlapFn) const
Find any overlap between a caller-defined query and any object ID.
GEOMETRYCORE_API void ParallelRangeQuery (const FAxisAlignedBox3d &Bounds, TArray< int > &ObjectIDsOut) const
Collect ObjectIDs from all the cells with bounding boxes that intersect Bounds.
GEOMETRYCORE_API void ParallelRangeQuery (const FAxisAlignedBox3d &RangeBoundsHint, TFunctionRef< bool(const FAxisAlignedBox3d &CellBounds)> BoundsOverlapFn, TArray< int32 > &ObjectIDs) const
Collect ObjectIDs from all the leaf cells that have bounding boxes that pass BoundsOverlapFn.
GEOMETRYCORE_API void RangeQuery (const FAxisAlignedBox3d &Bounds, TArray< int > &ObjectIDsOut) const
Collect ObjectIDs from all the cells with bounding boxes that intersect Bounds.
GEOMETRYCORE_API void RangeQuery (const FAxisAlignedBox3d &Bounds, TFunctionRef< void(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that intersect Bounds.
GEOMETRYCORE_API bool ReinsertObject (int32 ObjectID, const FAxisAlignedBox3d &NewBounds, uint32 CellIDHint=InvalidCellID)
Update the position of an object in the octree.
GEOMETRYCORE_API bool RemoveObject (int32 ObjectID)
Remove an object from the octree.
void SetMaxTreeDepth (int MaxTreeDepthIn)
Sets max tree depth w/ protection against setting beyond supported max.
Data Fields
double MaxExpandFactor = 0.25
Fraction we expand the dimension of any cell, to allow extra space to fit objects.
double RootDimension = 1000.0
Size of the Root cells of the octree.
Static Public Attributes
static constexpr uint32 MaxSupportedTreeDepth = 0x1F
Protected Member Functions
GEOMETRYCORE_API void BranchRangeQuery (const FSparseOctreeCell *ParentCell, const FAxisAlignedBox3d &Bounds, TArray< int > &ObjectIDs) const
bool CanFit (const FSparseOctreeCell &Cell, const FAxisAlignedBox3d &Bounds) const
GEOMETRYCORE_API FSparseOctreeCell FindCurrentContainingCell (const FAxisAlignedBox3d &Bounds) const
GEOMETRYCORE_API double FindNearestRayCellIntersection (const FSparseOctreeCell &Cell, const FRay3d &Ray) const
FAxisAlignedBox3d GetBox (uint32 Level, const FVector3i &Index, double ExpandFactor) const
FAxisAlignedBox3d GetCellBox (const FSparseOctreeCell &Cell, double ExpandFactor=0) const
FVector3d GetCellCenter (const FSparseOctreeCell &Cell) const
uint32 GetCellForObject (int32 ObjectID) const
double GetCellWidth (uint32 Level) const
GEOMETRYCORE_API void Insert_NewChildCell (int32 ObjectID, const FAxisAlignedBox3d &Bounds, int ParentCellID, FSparseOctreeCell NewChildCell, int ChildIdx)
GEOMETRYCORE_API void Insert_NewRoot (int32 ObjectID, const FAxisAlignedBox3d &Bounds, FSparseOctreeCell NewRootCell)
GEOMETRYCORE_API void Insert_Spill (int32 ObjectID, const FAxisAlignedBox3d &Bounds)
GEOMETRYCORE_API void Insert_ToCell (int32 ObjectID, const FAxisAlignedBox3d &Bounds, const FSparseOctreeCell &ExistingCell)
FVector3i PointToIndex (uint32 Level, const FVector3d &Position) const
int ToChildCellIndex (const FSparseOctreeCell &Cell, const FVector3d &Position) const
Protected Attributes
FSmallListSet CellObjectLists
FRefCountVector CellRefCounts
TDynamicVector< FSparseOctreeCell > Cells
int MaxTreeDepth = 10
Objects will not be inserted more than this many levels deep from a Root cell.
TDynamicVector< uint32 > ObjectIDToCellMap
TSparseGrid3< uint32 > RootCells
TSet< int32 > SpillObjectSet
FDynamicFlagArray ValidObjectIDs
Static Protected Attributes
static constexpr uint32 InvalidCellID = FSparseOctreeCell::InvalidID
static constexpr uint32 SpillCellID = InvalidCellID - 1
Private Member Functions
int BranchCustomOverlapAnyQuery (const FSparseOctreeCell *ParentCell, const FAxisAlignedBox3d &Bounds, TFunctionRef< bool(int32)> ObjectOverlapFn, TFunctionRef< bool(const FAxisAlignedBox3d &)> BoundsOverlapFn) const
void BranchRangeQuery (const FSparseOctreeCell *ParentCell, TFunctionRef< bool(const FAxisAlignedBox3d &)> BoundsOverlapFn, TArray< int > &ObjectIDs) const
TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > InitializeQueryQueue (const FAxisAlignedBox3d &Bounds) const
TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > InitializeQueryQueue (const FAxisAlignedBox3d &RangeBounds, TFunctionRef< bool(const FAxisAlignedBox3d &CellBounds)> BoundsOverlapFn, bool bCheckOverlapFnInRangeBounds=true) const
Helper to find root-level cells that satisfy BoundsOverlapFn.
TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > InitializeQueryQueue (const FVector3d &Point) const
void ParallelCollectObjectsInOverlappingCells (TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > RelevantRootCells, TFunctionRef< bool(const FAxisAlignedBox3d &CellBounds)> BoundsOverlapFn, TArray< int32 > &ObjectIDs) const
Detailed Description
FSparseDynamicOctree3 sorts objects with axis-aligned bounding boxes into a dynamic sparse octree of axis-aligned uniform grid cells.
At the top level we have an infinite grid of "root cells" of size RootDimension, which then contain 8 children, and so on. (So in fact each cell is a separate octree, and we have a uniform grid of octrees)
The objects and their bounding-boxes are not stored in the tree. You must have an integer identifier (ObjectID) for each object, and call Insert(ObjectID, BoundingBox). Some query functions will require you to provide a lambda/etc that can be called to retrieve the bounding box for a given ObjectID.
Objects are currently inserted at the maximum possible depth, ie smallest cell that will contain them, or MaxTreeDepth. The tree boxes are expanded by MaxExpandFactor to allow for deeper insertion. If MaxExpandFactor > 0 then the tree does not strictly partition space, IE adjacent cells overlap.
The octree is dynamic. Objects can be removed and re-inserted.
Definition at line 164 of file SparseDynamicOctree3.h.
Member Function Documentation
BranchCustomOverlapAnyQuery()
int UE::Geometry::FSparseDynamicOctree3::BranchCustomOverlapAnyQuery (const FSparseOctreeCell * ParentCell, const FAxisAlignedBox3d & Bounds, TFunctionRef< bool(int32)> ObjectOverlapFn, TFunctionRef< bool(const FAxisAlignedBox3d &)> BoundsOverlapFn) const private
BranchRangeQuery() [1/2]
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::BranchRangeQuery (const FSparseOctreeCell * ParentCell, const FAxisAlignedBox3d & Bounds, TArray< int > & ObjectIDs) const protected
BranchRangeQuery() [2/2]
void UE::Geometry::FSparseDynamicOctree3::BranchRangeQuery (const FSparseOctreeCell * ParentCell, TFunctionRef< bool(const FAxisAlignedBox3d &)> BoundsOverlapFn, TArray< int > & ObjectIDs) const private
CanFit()
bool UE::Geometry::FSparseDynamicOctree3::CanFit (const FSparseOctreeCell & Cell, const FAxisAlignedBox3d & Bounds) const inline protected
Definition at line 487 of file SparseDynamicOctree3.h.
References Cell, UE::Geometry::TAxisAlignedBox3< RealType >::Contains(), GetCellBox(), and MaxExpandFactor.
CheckIfObjectNeedsReinsert()
GEOMETRYCORE_API bool UE::Geometry::FSparseDynamicOctree3::CheckIfObjectNeedsReinsert (int32 ObjectID, const FAxisAlignedBox3d & NewBounds, uint32 & CellIDOut) const
Check if the object needs to be reinserted, if it has NewBounds.
Parameters
ObjectID ID of the object
NewBounds new bounding box of the object
CellIDOut returned CellID of the object, if it is in the tree. This can be passed to ReinsertObject() to save some computation.
Returns
false if ObjectID is already in the tree, and NewBounds fits within the cell that currently contains ObjectID
Referenced by UE::Geometry::FDynamicMeshOctree3::ReinsertTrianglesParallel().
CheckValidity()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::CheckValidity (TFunctionRef< bool(int)> IsValidObjectIDFunc, TFunctionRef< FAxisAlignedBox3d(int)> GetObjectBoundsFunc, EValidityCheckFailMode FailMode = EValidityCheckFailMode::Check, bool bVerbose = false, bool bFailOnMissingObjects = false) const
Check that the octree is internally valid.
Parameters
IsValidObjectIDFunc function that returns true if given ObjectID is valid
GetObjectBoundSFunc function that returns bounding box of object identified by ObjectID
FailMode how should validity checks fail
bVerbose if true, print some debug info via UE_LOG
bFailOnMissingObjects if true, assume ObjectIDs are dense and that all ObjectIDs must be in the tree
References UE::Geometry::Check.
Referenced by UE::Geometry::FDynamicMeshOctree3::CheckValidity().
ComputeStatistics()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::ComputeStatistics (FStatistics & StatsOut) const
Populate given FStatistics with info about the octree.
ContainmentQuery()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::ContainmentQuery (const FVector3d & Point, TFunctionRef< void(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that contain query point.
Parameters
Point query point
ObjectIDFunc this function is called for each ObjectID
References Point.
ContainmentQueryCancellable()
GEOMETRYCORE_API bool UE::Geometry::FSparseDynamicOctree3::ContainmentQueryCancellable (const FVector3d & Point, TFunctionRef< bool(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that contain query point.
Parameters
Point query point
ObjectIDFunc this function is called for each ObjectID. Returns true to continue query and false to abort
Returns
true if query finished, false if it exited
References Point.
ContainsObject()
GEOMETRYCORE_API bool UE::Geometry::FSparseDynamicOctree3::ContainsObject (int32 ObjectID) const
Test if an object is stored in the tree.
Parameters
ObjectID ID of the object
Returns
true if ObjectID is stored in this octree
FindCurrentContainingCell()
GEOMETRYCORE_API FSparseOctreeCell UE::Geometry::FSparseDynamicOctree3::FindCurrentContainingCell (const FAxisAlignedBox3d & Bounds) const protected
FindNearestHitObject()
GEOMETRYCORE_API int32 UE::Geometry::FSparseDynamicOctree3::FindNearestHitObject (const FRay3d & Ray, TFunctionRef< FAxisAlignedBox3d(int)> GetObjectBoundsFunc, TFunctionRef< double(int, const FRay3d &)> HitObjectDistFunc, double MaxDistance = TNumericLimits< double >::Max()) const
Find nearest ray-hit point with objects in tree.
Parameters
Ray the ray
GetObjectBoundsFunc function that returns bounding box of object identified by ObjectID
HitObjectDistFunc function that returns distance along ray to hit-point on object identified by ObjectID (or TNumericLimits<double>::Max() on miss)
MaxDistance maximum hit distance
Returns
ObjectID of hit object, or -1 on miss
References Ray.
Referenced by UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject(), and UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject().
FindNearestRayCellIntersection()
GEOMETRYCORE_API double UE::Geometry::FSparseDynamicOctree3::FindNearestRayCellIntersection (const FSparseOctreeCell & Cell, const FRay3d & Ray) const protected
References Cell, and Ray.
GetBox()
FAxisAlignedBox3d UE::Geometry::FSparseDynamicOctree3::GetBox (uint32 Level, const FVector3i & Index, double ExpandFactor) const inline protected
Definition at line 427 of file SparseDynamicOctree3.h.
References GetCellWidth().
Referenced by GetCellBox().
GetCellBox()
FAxisAlignedBox3d UE::Geometry::FSparseDynamicOctree3::GetCellBox (const FSparseOctreeCell & Cell, double ExpandFactor = 0) const inline protected
Definition at line 439 of file SparseDynamicOctree3.h.
References Cell, and GetBox().
Referenced by CanFit(), and UE::Geometry::FDynamicMeshOctree3::TestCellIntersection().
GetCellCenter()
FVector3d UE::Geometry::FSparseDynamicOctree3::GetCellCenter (const FSparseOctreeCell & Cell) const inline protected
Definition at line 443 of file SparseDynamicOctree3.h.
References Cell, and GetCellWidth().
Referenced by ToChildCellIndex().
GetCellForObject()
uint32 UE::Geometry::FSparseDynamicOctree3::GetCellForObject (int32 ObjectID) const inline protected
Definition at line 493 of file SparseDynamicOctree3.h.
References InvalidCellID, and ObjectIDToCellMap.
GetCellWidth()
double UE::Geometry::FSparseDynamicOctree3::GetCellWidth (uint32 Level) const inline protected
Definition at line 418 of file SparseDynamicOctree3.h.
References checkSlow, MaxSupportedTreeDepth, and RootDimension.
Referenced by GetBox(), GetCellCenter(), and PointToIndex().
GetMaxTreeDepth()
int UE::Geometry::FSparseDynamicOctree3::GetMaxTreeDepth () inline
Definition at line 196 of file SparseDynamicOctree3.h.
References MaxTreeDepth.
InitializeQueryQueue() [1/3]
TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > UE::Geometry::FSparseDynamicOctree3::InitializeQueryQueue (const FAxisAlignedBox3d & Bounds) const inline private
Definition at line 557 of file SparseDynamicOctree3.h.
References InitializeQueryQueue(), and UE::Geometry::TAxisAlignedBox3< RealType >::Intersects().
InitializeQueryQueue() [2/3]
TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > UE::Geometry::FSparseDynamicOctree3::InitializeQueryQueue (const FAxisAlignedBox3d & RangeBounds, TFunctionRef< bool(const FAxisAlignedBox3d &CellBounds)> BoundsOverlapFn, bool bCheckOverlapFnInRangeBounds = true) const private
Helper to find root-level cells that satisfy BoundsOverlapFn.
Parameters
RangeBounds If the allocation of cells is such that it is worth doing, only cells in these bounds are looked for and iterated over. May be ignored if the allocation is such that it is faster to iterate over all allocated root cells than to check for allocation in a big range.
BoundsOverlapFn Function for determining whether cell should be included in output queue
bCheckOverlapFnInRangeBounds If true, then BoundsOverlapFn is still checked when iterating over RangeBounds (i.e., RangeBounds is an optimization hint, but not sufficient for determining actual overlap).
Referenced by InitializeQueryQueue(), and InitializeQueryQueue().
InitializeQueryQueue() [3/3]
TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > UE::Geometry::FSparseDynamicOctree3::InitializeQueryQueue (const FVector3d & Point) const inline private
Definition at line 549 of file SparseDynamicOctree3.h.
References UE::Geometry::TAxisAlignedBox3< RealType >::Contains(), InitializeQueryQueue(), and Point.
Insert_NewChildCell()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::Insert_NewChildCell (int32 ObjectID, const FAxisAlignedBox3d & Bounds, int ParentCellID, FSparseOctreeCell NewChildCell, int ChildIdx) protected
Insert_NewRoot()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::Insert_NewRoot (int32 ObjectID, const FAxisAlignedBox3d & Bounds, FSparseOctreeCell NewRootCell) protected
Insert_Spill()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::Insert_Spill (int32 ObjectID, const FAxisAlignedBox3d & Bounds) protected
Insert_ToCell()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::Insert_ToCell (int32 ObjectID, const FAxisAlignedBox3d & Bounds, const FSparseOctreeCell & ExistingCell) protected
InsertObject()
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::InsertObject (int32 ObjectID, const FAxisAlignedBox3d & Bounds)
Insert ObjectID into the Octree.
Parameters
ObjectID ID of the object to insert
Bounds bounding box of the object
Referenced by UE::Geometry::FDynamicMeshOctree3::InsertTriangle(), UE::Geometry::FDynamicMeshOctree3::InsertTriangles(), and UE::Geometry::FDynamicMeshOctree3::InsertTriangles().
ParallelCollectObjectsInOverlappingCells()
void UE::Geometry::FSparseDynamicOctree3::ParallelCollectObjectsInOverlappingCells (TArray< const FSparseOctreeCell *, TInlineAllocator< 32 > > RelevantRootCells, TFunctionRef< bool(const FAxisAlignedBox3d &CellBounds)> BoundsOverlapFn, TArray< int32 > & ObjectIDs) const private
ParallelOverlapAnyQuery() [1/2]
int UE::Geometry::FSparseDynamicOctree3::ParallelOverlapAnyQuery (const FAxisAlignedBox3d & ShapeBounds, TFunctionRef< bool(int32)> ObjectOverlapFn) const inline
Find any overlap between a caller-defined query and any object ID.
Returns the first overlap it finds.
Parameters
ShapeBounds Overall bounds of the custom query shape
ObjectOverlapFn Custom function that indicates if the given ObjectID overlaps the query shape
Returns
index of overlapping ObjectID or INDEX_NONE if no overlaps are found
Definition at line 348 of file SparseDynamicOctree3.h.
References ParallelOverlapAnyQuery().
ParallelOverlapAnyQuery() [2/2]
GEOMETRYCORE_API int UE::Geometry::FSparseDynamicOctree3::ParallelOverlapAnyQuery (const FAxisAlignedBox3d & ShapeBounds, TFunctionRef< bool(int32)> ObjectOverlapFn, TFunctionRef< bool(const FAxisAlignedBox3d &)> BoundsOverlapFn) const
Find any overlap between a caller-defined query and any object ID.
Returns the first overlap it finds.
Parameters
ShapeBounds Overall bounds of the custom query shape
ObjectOverlapFn Custom function that indicates if the given ObjectID overlaps the query shape
BoundsOverlapFn Optional custom function that indicates if the given bounding box overlaps the query shape, used to filter the octree search. Note the bounds overlap with ShapeBounds will already be called before calling this; only provide this if a more accurate overlap can be quickly checked.
Returns
index of overlapping ObjectID or INDEX_NONE if no overlaps are found
Referenced by ParallelOverlapAnyQuery().
ParallelRangeQuery() [1/2]
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::ParallelRangeQuery (const FAxisAlignedBox3d & Bounds, TArray< int > & ObjectIDsOut) const
Collect ObjectIDs from all the cells with bounding boxes that intersect Bounds.
Current implementation creates a separate TArray for each thread.
Parameters
Bounds query box
ObjectIDsOut collected ObjectIDs are stored here
ParallelRangeQuery() [2/2]
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::ParallelRangeQuery (const FAxisAlignedBox3d & RangeBoundsHint, TFunctionRef< bool(const FAxisAlignedBox3d &CellBounds)> BoundsOverlapFn, TArray< int32 > & ObjectIDs) const
Collect ObjectIDs from all the leaf cells that have bounding boxes that pass BoundsOverlapFn.
Parameters
RangeBoundsHint A box to potentially limit the iteration range across cells. Note that this might be ignored if the allocation of cells is such that trying to check for cells in that range would take more time than just iterating over all allocated cells.
BoundsOverlapFn Must be thread-safe. Used to determine if the cell is part of the desired range.
ObjectIDsOut collected ObjectIDs are stored here
PointToIndex()
FVector3i UE::Geometry::FSparseDynamicOctree3::PointToIndex (uint32 Level, const FVector3d & Position) const inline protected
Definition at line 456 of file SparseDynamicOctree3.h.
References FMath::Clamp(), TMathUtil< double >::Floor(), GetCellWidth(), UE::Geometry::Position, and Value.
RangeQuery() [1/2]
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::RangeQuery (const FAxisAlignedBox3d & Bounds, TArray< int > & ObjectIDsOut) const
Collect ObjectIDs from all the cells with bounding boxes that intersect Bounds.
Parameters
Bounds query box
ObjectIDsOut collected ObjectIDs are stored here
RangeQuery() [2/2]
GEOMETRYCORE_API void UE::Geometry::FSparseDynamicOctree3::RangeQuery (const FAxisAlignedBox3d & Bounds, TFunctionRef< void(int)> ObjectIDFunc) const
Process ObjectIDs from all the cells with bounding boxes that intersect Bounds.
Parameters
Bounds query box
ObjectIDFunc this function is called for each ObjectID
ReinsertObject()
GEOMETRYCORE_API bool UE::Geometry::FSparseDynamicOctree3::ReinsertObject (int32 ObjectID, const FAxisAlignedBox3d & NewBounds, uint32 CellIDHint = InvalidCellID)
Update the position of an object in the octree.
This is more efficient than doing a remove+insert
Parameters
ObjectID ID of the object
NewBounds new bounding box of the object
Returns
true if object was reinserted, false if the object was fine in it's existing cell
References InvalidCellID.
Referenced by UE::Geometry::FDynamicMeshOctree3::ReinsertTriangles(), and UE::Geometry::FDynamicMeshOctree3::ReinsertTrianglesParallel().
RemoveObject()
GEOMETRYCORE_API bool UE::Geometry::FSparseDynamicOctree3::RemoveObject (int32 ObjectID)
Remove an object from the octree.
Parameters
ObjectID ID of the object
Returns
true if the object was in the tree and removed
SetMaxTreeDepth()
void UE::Geometry::FSparseDynamicOctree3::SetMaxTreeDepth (int MaxTreeDepthIn) inline
Sets max tree depth w/ protection against setting beyond supported max.
Definition at line 203 of file SparseDynamicOctree3.h.
References ensure, MaxSupportedTreeDepth, and MaxTreeDepth.
ToChildCellIndex()
int UE::Geometry::FSparseDynamicOctree3::ToChildCellIndex (const FSparseOctreeCell & Cell, const FVector3d & Position) const inline protected
Definition at line 477 of file SparseDynamicOctree3.h.
References Cell, GetCellCenter(), and UE::Geometry::Position.
Field Documentation
CellObjectLists
FSmallListSet UE::Geometry::FSparseDynamicOctree3::CellObjectLists protected
Definition at line 406 of file SparseDynamicOctree3.h.
Referenced by UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), and UE::Geometry::FDynamicMeshOctree3::CollectTriangles().
CellRefCounts
FRefCountVector UE::Geometry::FSparseDynamicOctree3::CellRefCounts protected
Definition at line 400 of file SparseDynamicOctree3.h.
Referenced by UE::Geometry::FDynamicMeshOctree3::CollectTriangles(), and UE::Geometry::FDynamicMeshOctree3::TestCellIntersection().
Cells
TDynamicVector<FSparseOctreeCell> UE::Geometry::FSparseDynamicOctree3::Cells protected
Definition at line 403 of file SparseDynamicOctree3.h.
Referenced by UE::Geometry::FDynamicMeshOctree3::BuildLevelCutSet(), UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), UE::Geometry::FDynamicMeshOctree3::CollectTriangles(), UE::Geometry::FDynamicMeshOctree3::TestCellIntersection(), and UE::Geometry::FDynamicMeshOctree3::UpdateLevelCutSet().
InvalidCellID
uint32 UE::Geometry::FSparseDynamicOctree3::InvalidCellID = FSparseOctreeCell::InvalidID static constexpr protected
Definition at line 393 of file SparseDynamicOctree3.h.
Referenced by GetCellForObject(), and ReinsertObject().
MaxExpandFactor
double UE::Geometry::FSparseDynamicOctree3::MaxExpandFactor = 0.25
Fraction we expand the dimension of any cell, to allow extra space to fit objects.
Definition at line 192 of file SparseDynamicOctree3.h.
Referenced by CanFit(), and UE::Geometry::FDynamicMeshOctree3::TestCellIntersection().
MaxSupportedTreeDepth
uint32 UE::Geometry::FSparseDynamicOctree3::MaxSupportedTreeDepth = 0x1F static constexpr
Definition at line 194 of file SparseDynamicOctree3.h.
Referenced by GetCellWidth(), and SetMaxTreeDepth().
MaxTreeDepth
int UE::Geometry::FSparseDynamicOctree3::MaxTreeDepth = 10 protected
Objects will not be inserted more than this many levels deep from a Root cell.
Definition at line 216 of file SparseDynamicOctree3.h.
Referenced by GetMaxTreeDepth(), and SetMaxTreeDepth().
ObjectIDToCellMap
TDynamicVector<uint32> UE::Geometry::FSparseDynamicOctree3::ObjectIDToCellMap protected
Definition at line 409 of file SparseDynamicOctree3.h.
Referenced by GetCellForObject().
RootCells
TSparseGrid3<uint32> UE::Geometry::FSparseDynamicOctree3::RootCells protected
Definition at line 414 of file SparseDynamicOctree3.h.
Referenced by UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles().
RootDimension
double UE::Geometry::FSparseDynamicOctree3::RootDimension = 1000.0
Size of the Root cells of the octree.
Objects that don't fit in a Root cell are added to a "Spill set"
Definition at line 187 of file SparseDynamicOctree3.h.
Referenced by GetCellWidth().
SpillCellID
uint32 UE::Geometry::FSparseDynamicOctree3::SpillCellID = InvalidCellID - 1 static constexpr protected
Definition at line 396 of file SparseDynamicOctree3.h.
SpillObjectSet
TSet<int32> UE::Geometry::FSparseDynamicOctree3::SpillObjectSet protected
Definition at line 407 of file SparseDynamicOctree3.h.
Referenced by UE::Geometry::FDynamicMeshOctree3::CollectSpillTriangles().
ValidObjectIDs
FDynamicFlagArray UE::Geometry::FSparseDynamicOctree3::ValidObjectIDs protected
Definition at line 410 of file SparseDynamicOctree3.h.
The documentation for this class was generated from the following file:
SparseDynamicOctree3.h