Unreal Engine 5.6 C++ API: FAssetReferenceFilterContext Struct Reference
FAssetReferenceFilterContext Struct Reference
Struct used in filtering allowed references between assets.
#include "EditorEngine.h"
Public Member Functions
UNREALED_API void AddReferencingAsset (const FAssetData &InReferencingAsset, EAssetReferenceFilterProperties InProperties=EAssetReferenceFilterProperties::None)
UNREALED_API void AddReferencingAssets (const TArray< FAssetData > &InReferencingAssets, EAssetReferenceFilterProperties InProperties=EAssetReferenceFilterProperties::None)
UNREALED_API void AddReferencingAssetsFromPropertyHandle (const TSharedPtr< class IPropertyHandle > &PropertyHandle)
void AddRole (const EAssetReferenceFilterRole InRole)
const TArray< FAssetReferenceFilterReferencerInfo > & GetReferencingAssets () const
EAssetReferenceFilterRole GetRole () const
bool HasRole (const EAssetReferenceFilterRole InRole) const
void RemoveRole (const EAssetReferenceFilterRole InRole)
UE_DEPRECATED (5.5, "ReferencingAssets is deprecated. Use the AddReferencingAsset functions to add referencers and GetReferencingAssets to get them.") TArray< FAssetData > ReferencingAssets
Private Attributes
TArray< FAssetReferenceFilterReferencerInfo > ReferencingAssetInfo
EAssetReferenceFilterRole Role = EAssetReferenceFilterRole::None
Detailed Description
Struct used in filtering allowed references between assets.
Passes context about the referencers to game-level filters
Definition at line 354 of file EditorEngine.h.
Member Function Documentation
AddReferencingAsset()
UNREALED_API void FAssetReferenceFilterContext::AddReferencingAsset (const FAssetData & InReferencingAsset, EAssetReferenceFilterProperties InProperties = EAssetReferenceFilterProperties::None)
References None.
AddReferencingAssets()
UNREALED_API void FAssetReferenceFilterContext::AddReferencingAssets (const TArray< FAssetData > & InReferencingAssets, EAssetReferenceFilterProperties InProperties = EAssetReferenceFilterProperties::None)
References None.
AddReferencingAssetsFromPropertyHandle()
UNREALED_API void FAssetReferenceFilterContext::AddReferencingAssetsFromPropertyHandle (const TSharedPtr< class IPropertyHandle > & PropertyHandle)
AddRole()
void FAssetReferenceFilterContext::AddRole (const EAssetReferenceFilterRole InRole) inline
Definition at line 365 of file EditorEngine.h.
References AddRole(), EnumAddFlags(), and Role.
Referenced by AddRole().
GetReferencingAssets()
const TArray< FAssetReferenceFilterReferencerInfo > & FAssetReferenceFilterContext::GetReferencingAssets () const inline
Definition at line 360 of file EditorEngine.h.
References ReferencingAssetInfo.
GetRole()
EAssetReferenceFilterRole FAssetReferenceFilterContext::GetRole () const inline
Definition at line 380 of file EditorEngine.h.
References Role.
HasRole()
bool FAssetReferenceFilterContext::HasRole (const EAssetReferenceFilterRole InRole) const inline
Definition at line 375 of file EditorEngine.h.
References EnumHasAnyFlags(), and Role.
RemoveRole()
void FAssetReferenceFilterContext::RemoveRole (const EAssetReferenceFilterRole InRole) inline
Definition at line 370 of file EditorEngine.h.
References EnumRemoveFlags(), and Role.
UE_DEPRECATED()
FAssetReferenceFilterContext::UE_DEPRECATED (5. 5, "ReferencingAssets is deprecated. Use the AddReferencingAsset functions to add referencers and GetReferencingAssets to get them.")
Field Documentation
ReferencingAssetInfo
TArray<FAssetReferenceFilterReferencerInfo> FAssetReferenceFilterContext::ReferencingAssetInfo private
Definition at line 386 of file EditorEngine.h.
Referenced by GetReferencingAssets().
Role
EAssetReferenceFilterRole FAssetReferenceFilterContext::Role = EAssetReferenceFilterRole::None private
Definition at line 387 of file EditorEngine.h.
Referenced by AddRole(), GetRole(), HasRole(), and RemoveRole().
The documentation for this struct was generated from the following file:
EditorEngine.h