Unreal Engine 5.6 C++ API: UE::AnimNext::TTransformArraySoA< AllocatorType > Struct Template Reference
UE::AnimNext::TTransformArraySoA< AllocatorType > Struct Template Reference
Transform Array Test using StructOfArrays model.
#include "TransformArray.h"
Public Member Functions
TTransformArraySoA ()
TTransformArraySoA (const TTransformArraySoA &Other)
TTransformArraySoA (int NumTransforms, bool bSetIdentity=true, bool bAdditiveIdentity=false)
TTransformArraySoA (TTransformArraySoA &&Other)
~TTransformArraySoA ()=default
void Blend (const TTransformArraySoA &AtomArray1, const TTransformArraySoA &AtomArray2, float BlendWeight)
Set this transform array to the weighted blend of the supplied two transforms.
bool ContainsNaN () const
void CopyTransforms (const FTransformArraySoAConstView &Other, int32 Index, int32 NumTransforms)
void CopyTransforms (const TTransformArraySoA &Other, int32 Index, int32 NumTransforms)
void DebugFill ()
void Empty (int32 Slack=0)
FTransformArraySoAConstView GetConstView () const
FTransformArraySoAView GetView ()
bool IsEmpty () const
bool IsValid () const
FORCEINLINE int32 Num () const
TTransformArraySoA & operator= (const TTransformArraySoA &Other)
TTransformArraySoA & operator= (TTransformArraySoA &&Other)
FTransformSoAAdapter operator[] (int Index)
const FTransformSoAAdapterConst operator[] (int Index) const
void Reset (int32 NumTransforms)
void SetIdentity (bool bAdditiveIdentity=false)
void SetNum (int32 NumTransforms, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void SetNumUninitialized (int32 NumTransforms, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Data Fields
TArrayView< FQuat > Rotations
TArrayView< FVector > Scales3D
TArrayView< FVector > Translations
Static Public Attributes
static constexpr int32 PaddingSize = sizeof(double)
static constexpr int32 TransformSize = sizeof(FVector) + sizeof(FQuat) + sizeof(FVector)
Private Member Functions
FORCEINLINE void DiagnosticCheck_IsValid () const
FORCEINLINE void DiagnosticCheckNaN_All () const
void UpdateViews (uint8 *Memory, int32 NumTransforms)
Static Private Member Functions
static FORCEINLINE void DiagnosticCheckNaN_Rotate (const FQuat &Rotation)
static FORCEINLINE void DiagnosticCheckNaN_Scale3D (const FVector &Scale3D)
static FORCEINLINE void DiagnosticCheckNaN_Translate (const FVector &Translation)
Private Attributes
TArray< uint8, AllocatorType > AllocatedMemory
Detailed Description
template<typename AllocatorType>
struct UE::AnimNext::TTransformArraySoA< AllocatorType >
Transform Array Test using StructOfArrays model.
Definition at line 277 of file TransformArray.h.
Constructor & Destructor Documentation
TTransformArraySoA() [1/4]
template<typename AllocatorType> UE::AnimNext::TTransformArraySoA< AllocatorType >::TTransformArraySoA () inline
Definition at line 289 of file TransformArray.h.
TTransformArraySoA() [2/4]
template<typename AllocatorType> UE::AnimNext::TTransformArraySoA< AllocatorType >::TTransformArraySoA (int NumTransforms, bool bSetIdentity = true, bool bAdditiveIdentity = false) inline explicit
Definition at line 295 of file TransformArray.h.
~TTransformArraySoA()
template<typename AllocatorType> UE::AnimNext::TTransformArraySoA< AllocatorType >::~TTransformArraySoA () default
TTransformArraySoA() [3/4]
template<typename AllocatorType> UE::AnimNext::TTransformArraySoA< AllocatorType >::TTransformArraySoA (const TTransformArraySoA< AllocatorType > & Other) inline
Definition at line 307 of file TransformArray.h.
TTransformArraySoA() [4/4]
template<typename AllocatorType> UE::AnimNext::TTransformArraySoA< AllocatorType >::TTransformArraySoA (TTransformArraySoA< AllocatorType > && Other) inline
Definition at line 327 of file TransformArray.h.
Member Function Documentation
Blend()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::Blend (const TTransformArraySoA< AllocatorType > & AtomArray1, const TTransformArraySoA< AllocatorType > & AtomArray2, float BlendWeight) inline
Set this transform array to the weighted blend of the supplied two transforms.
Definition at line 404 of file TransformArray.h.
ContainsNaN()
template<typename AllocatorType> bool UE::AnimNext::TTransformArraySoA< AllocatorType >::ContainsNaN () const inline
Definition at line 526 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::IsValid().
CopyTransforms() [1/2]
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::CopyTransforms (const FTransformArraySoAConstView & Other, int32 Index, int32 NumTransforms) inline
Definition at line 391 of file TransformArray.h.
CopyTransforms() [2/2]
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::CopyTransforms (const TTransformArraySoA< AllocatorType > & Other, int32 Index, int32 NumTransforms) inline
Definition at line 379 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend().
DebugFill()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::DebugFill () inline
Definition at line 572 of file TransformArray.h.
DiagnosticCheck_IsValid()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArraySoA< AllocatorType >::DiagnosticCheck_IsValid () const inline private
Definition at line 655 of file TransformArray.h.
DiagnosticCheckNaN_All()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArraySoA< AllocatorType >::DiagnosticCheckNaN_All () const inline private
Definition at line 654 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend().
DiagnosticCheckNaN_Rotate()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArraySoA< AllocatorType >::DiagnosticCheckNaN_Rotate (const FQuat & Rotation) inline static private
Definition at line 652 of file TransformArray.h.
DiagnosticCheckNaN_Scale3D()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArraySoA< AllocatorType >::DiagnosticCheckNaN_Scale3D (const FVector & Scale3D) inline static private
Definition at line 653 of file TransformArray.h.
DiagnosticCheckNaN_Translate()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArraySoA< AllocatorType >::DiagnosticCheckNaN_Translate (const FVector & Translation) inline static private
Definition at line 651 of file TransformArray.h.
Empty()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::Empty (int32 Slack = 0) inline
Definition at line 343 of file TransformArray.h.
GetConstView()
template<typename AllocatorType> FTransformArraySoAConstView UE::AnimNext::TTransformArraySoA< AllocatorType >::GetConstView () const inline
Definition at line 517 of file TransformArray.h.
GetView()
template<typename AllocatorType> FTransformArraySoAView UE::AnimNext::TTransformArraySoA< AllocatorType >::GetView () inline
Definition at line 508 of file TransformArray.h.
IsEmpty()
template<typename AllocatorType> bool UE::AnimNext::TTransformArraySoA< AllocatorType >::IsEmpty () const inline
Definition at line 338 of file TransformArray.h.
IsValid()
template<typename AllocatorType> bool UE::AnimNext::TTransformArraySoA< AllocatorType >::IsValid () const inline
Definition at line 553 of file TransformArray.h.
Num()
template<typename AllocatorType> FORCEINLINE int32 UE::AnimNext::TTransformArraySoA< AllocatorType >::Num () const inline
Definition at line 493 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::CopyTransforms(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::CopyTransforms(), and UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::IsEmpty().
operator=() [1/2]
template<typename AllocatorType> TTransformArraySoA & UE::AnimNext::TTransformArraySoA< AllocatorType >::operator= (const TTransformArraySoA< AllocatorType > & Other) inline
Definition at line 316 of file TransformArray.h.
operator=() [2/2]
template<typename AllocatorType> TTransformArraySoA & UE::AnimNext::TTransformArraySoA< AllocatorType >::operator= (TTransformArraySoA< AllocatorType > && Other) inline
Definition at line 332 of file TransformArray.h.
operator[]() [1/2]
template<typename AllocatorType> FTransformSoAAdapter UE::AnimNext::TTransformArraySoA< AllocatorType >::operator[] (int Index) inline
Definition at line 498 of file TransformArray.h.
operator[]() [2/2]
template<typename AllocatorType> const FTransformSoAAdapterConst UE::AnimNext::TTransformArraySoA< AllocatorType >::operator[] (int Index) const inline
Definition at line 503 of file TransformArray.h.
Reset()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::Reset (int32 NumTransforms) inline
Definition at line 350 of file TransformArray.h.
SetIdentity()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::SetIdentity (bool bAdditiveIdentity = false) inline
Definition at line 372 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::TTransformArraySoA().
SetNum()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::SetNum (int32 NumTransforms, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 356 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::TTransformArraySoA().
SetNumUninitialized()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::SetNumUninitialized (int32 NumTransforms, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 364 of file TransformArray.h.
UpdateViews()
template<typename AllocatorType> void UE::AnimNext::TTransformArraySoA< AllocatorType >::UpdateViews (uint8 * Memory, int32 NumTransforms) inline private
Definition at line 580 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::TTransformArraySoA(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::TTransformArraySoA(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Empty(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::operator=(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::SetNum(), and UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::SetNumUninitialized().
Field Documentation
AllocatedMemory
template<typename AllocatorType> TArray<uint8, AllocatorType> UE::AnimNext::TTransformArraySoA< AllocatorType >::AllocatedMemory private
Definition at line 578 of file TransformArray.h.
PaddingSize
template<typename AllocatorType> int32 UE::AnimNext::TTransformArraySoA< AllocatorType >::PaddingSize = sizeof(double) static constexpr
Definition at line 281 of file TransformArray.h.
Rotations
template<typename AllocatorType> TArrayView<FQuat> UE::AnimNext::TTransformArraySoA< AllocatorType >::Rotations
Definition at line 285 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend().
Scales3D
template<typename AllocatorType> TArrayView<FVector> UE::AnimNext::TTransformArraySoA< AllocatorType >::Scales3D
Definition at line 286 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend().
TransformSize
template<typename AllocatorType> int32 UE::AnimNext::TTransformArraySoA< AllocatorType >::TransformSize = sizeof(FVector) + sizeof(FQuat) + sizeof(FVector) static constexpr
Definition at line 282 of file TransformArray.h.
Translations
template<typename AllocatorType> TArrayView<FVector> UE::AnimNext::TTransformArraySoA< AllocatorType >::Translations
Definition at line 284 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend().
The documentation for this struct was generated from the following file:
TransformArray.h