Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolItemTypeId Class Reference
UE::SequenceNavigator::FNavigationToolItemTypeId Class Reference
#include "NavigationToolItemTypeId.h"
Public Member Functions
FNavigationToolItemTypeId (FName InTypeName)
bool IsValid () const
bool operator== (FNavigationToolItemTypeId InOther) const
FName ToName () const
FString ToString () const
Static Public Member Functions
static FNavigationToolItemTypeId Invalid ()
Private Attributes
FName Name
Friends
uint32 GetTypeHash (FNavigationToolItemTypeId InTypeId)
Detailed Description
Definition at line 11 of file NavigationToolItemTypeId.h.
Constructor & Destructor Documentation
FNavigationToolItemTypeId()
UE::SequenceNavigator::FNavigationToolItemTypeId::FNavigationToolItemTypeId (FName InTypeName) inline explicit
Definition at line 19 of file NavigationToolItemTypeId.h.
References Name.
Referenced by GetTypeHash, Invalid(), and operator==().
Member Function Documentation
Invalid()
FNavigationToolItemTypeId UE::SequenceNavigator::FNavigationToolItemTypeId::Invalid () inline static
Definition at line 14 of file NavigationToolItemTypeId.h.
References FNavigationToolItemTypeId().
Referenced by UE::SequenceNavigator::TNavigationToolItemType< T, bool >::GetTypeId().
IsValid()
bool UE::SequenceNavigator::FNavigationToolItemTypeId::IsValid () const inline
Definition at line 33 of file NavigationToolItemTypeId.h.
References Name.
Referenced by UE::SequenceNavigator::TNavigationToolItemInherits< FNavigationToolColorColumn, FNavigationToolColumn >::Cast().
operator==()
bool UE::SequenceNavigator::FNavigationToolItemTypeId::operator== (FNavigationToolItemTypeId InOther) const inline
Definition at line 28 of file NavigationToolItemTypeId.h.
References FNavigationToolItemTypeId(), and Name.
ToName()
FName UE::SequenceNavigator::FNavigationToolItemTypeId::ToName () const inline
Definition at line 38 of file NavigationToolItemTypeId.h.
References Name.
Referenced by UE::SequenceNavigator::INavigationToolColumn::GetColumnId(), and UE::SequenceNavigator::TNavigationToolItemProxyDefaultFactoryBase< InItemProxyType, InItemProxyPriority, typename >::GetItemProxyTypeName().
ToString()
FString UE::SequenceNavigator::FNavigationToolItemTypeId::ToString () const inline
Definition at line 43 of file NavigationToolItemTypeId.h.
References Name.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FNavigationToolItemTypeId InTypeId) friend
Definition at line 23 of file NavigationToolItemTypeId.h.
References FNavigationToolItemTypeId(), GetTypeHash, and Name.
Referenced by GetTypeHash.
Field Documentation
Name
FName UE::SequenceNavigator::FNavigationToolItemTypeId::Name private
Definition at line 49 of file NavigationToolItemTypeId.h.
Referenced by FNavigationToolItemTypeId(), GetTypeHash, IsValid(), operator==(), ToName(), and ToString().
The documentation for this class was generated from the following file:
NavigationToolItemTypeId.h