Unreal Engine 5.6 C++ API: FMovieSceneClipboardBuilder Class Reference
FMovieSceneClipboardBuilder Class Reference
Class responsible for building a clipboard for a movie scene.
#include "MovieSceneClipboard.h"
Public Member Functions
MOVIESCENE_API FMovieSceneClipboard Commit (TOptional< FFrameNumber > CopyRelativeTo)
Generate a clipboard for the current state of this builder, resetting the builder back to its default state.
template<typename KeyType>
FMovieSceneClipboardKeyTrack & FindOrAddKeyTrack (FName InName, UMovieSceneTrack &ParentTrack)
Find or add a key track.
Data Fields
FFrameNumber KeyOffset
Optional key offset that is applied to all keys added to the clipboard.
Private Attributes
TMap< UMovieSceneTrack *, TArray< FMovieSceneClipboardKeyTrack > > TrackIndex
Map of key tracks for a given moviescene track ptr.
Detailed Description
Class responsible for building a clipboard for a movie scene.
Definition at line 339 of file MovieSceneClipboard.h.
Member Function Documentation
Commit()
MOVIESCENE_API FMovieSceneClipboard FMovieSceneClipboardBuilder::Commit (TOptional< FFrameNumber > CopyRelativeTo)
Generate a clipboard for the current state of this builder, resetting the builder back to its default state.
FindOrAddKeyTrack()
template<typename KeyType> FMovieSceneClipboardKeyTrack & FMovieSceneClipboardBuilder::FindOrAddKeyTrack (FName InName, UMovieSceneTrack & ParentTrack) inline
Find or add a key track.
Key tracks are group primarily by MovieSceneTrack instance, then by name
Parameters
InName The name of this track (e.g. 'R', 'Location.X', etc)
ParentTrack The parent track within which this track resides
Returns
A key track which can be populated with keys
Definition at line 357 of file MovieSceneClipboard.h.
References check, FMovieSceneClipboardKeyTrack::Create(), FMovieSceneClipboardKeyTrack::GetName(), InName, IsValid(), MoveTemp(), TrackIndex, and Tracks.
Referenced by Sequencer::CopyKeys().
Field Documentation
KeyOffset
FFrameNumber FMovieSceneClipboardBuilder::KeyOffset
Optional key offset that is applied to all keys added to the clipboard.
Definition at line 344 of file MovieSceneClipboard.h.
TrackIndex
TMap<UMovieSceneTrack*, TArray<FMovieSceneClipboardKeyTrack> > FMovieSceneClipboardBuilder::TrackIndex private
Map of key tracks for a given moviescene track ptr.
Definition at line 379 of file MovieSceneClipboard.h.
Referenced by FindOrAddKeyTrack().
The documentation for this class was generated from the following file:
MovieSceneClipboard.h