Unreal Engine 5.6 C++ API: UAnimSequence Class Reference
UAnimSequence Class Reference
#include "AnimSequence.h"
Data Structures
struct FCompressedAnimationDataReadScope
Helper struct to enter/leave compressed data lock in read-mode.
struct FCompressedAnimationDataWriteScope
Helper struct to enter/leave compressed data lock in write-mode.
struct FScopedCompressedAnimSequence
Public Member Functions
void AddKeyToSequence (float Time, const FName &BoneName, const FTransform &AdditiveTransform)
Add Key to Transform Curves.
virtual void AdvanceMarkerPhaseAsFollower (const FMarkerTickContext &Context, float DeltaRemaining, bool bLooping, float &CurrentTime, FMarkerPair &PreviousMarker, FMarkerPair &NextMarker, const UMirrorDataTable *MirrorTable) const
virtual void AdvanceMarkerPhaseAsLeader (bool bLooping, float MoveDelta, const TArray< FName > &ValidMarkerNames, float &CurrentTime, FMarkerPair &PrevMarker, FMarkerPair &NextMarker, TArray< FPassedMarker > &MarkersPassed, const UMirrorDataTable *MirrorTable) const
void BeginCacheDerivedDataForCurrentPlatform ()
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform) override
virtual void BeginDestroy () override
void CacheDerivedDataForCurrentPlatform ()
void CacheDerivedDataForPlatform (const ITargetPlatform *TargetPlatform)
bool CanBakeAdditive () const
bool CanBeCompressed () const
virtual void ClearAllCachedCookedPlatformData () override
bool CreateAnimation (class UAnimSequence *Sequence)
Create Animation Sequence from the given animation.
bool CreateAnimation (class USkeletalMesh *Mesh)
Create Animation Sequence from Reference Pose of the Mesh.
bool CreateAnimation (class USkeletalMeshComponent *MeshComponent)
Create Animation Sequence from the Mesh Component's current bone transform.
void DeleteNotifyTrackData ()
bool DoesSequenceContainZeroScale () const
virtual void EnableRootMotionSettingFromMontage (bool bInEnableRootMotion, const ERootMotionRootLock::Type InRootMotionRootLock) override
void EvaluateAttributes (FAnimationPoseData &OutAnimationPoseData, const FAnimExtractContext &ExtractionContext, bool bUseRawData) const
virtual void EvaluateCurveData (FBlendedCurve &OutCurve, const FAnimExtractContext &AnimExtractContext, bool bForceUseRawData=false) const override
virtual float EvaluateCurveData (FName CurveName, const FAnimExtractContext &AnimExtractContext, bool bForceUseRawData=false) const override
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS FTransform ExtractRootMotion (const FAnimExtractContext &ExtractionContext) const override final
virtual FTransform ExtractRootMotionFromRange (double StartTime, double EndTime, const FAnimExtractContext &ExtractionContext) const override final
virtual FTransform ExtractRootTrackTransform (const FAnimExtractContext &ExtractionContext, const FBoneContainer *RequiredBones) const override final
uint8 * FindSyncMarkerPropertyData (int32 SyncMarkerIndex, FArrayProperty *&ArrayProperty)
void FlagDependentAnimationsAsRawDataOnly () const
virtual EAdditiveAnimationType GetAdditiveAnimType () const override
virtual class UAnimSequence * GetAdditiveBasePose () const override
void GetAdditiveBasePose (FAnimationPoseData &OutAnimationPoseData, const FAnimExtractContext &ExtractionContext) const
Get Bone Transform of the base (reference) pose of the additive animation for the Time given, relative to Parent for all RequiredBones.
virtual bool GetAllAnimationSequencesReferred (TArray< UAnimationAsset * > &AnimationAssets, bool bRecursive=true) override
virtual void GetAnimationPose (FAnimationPoseData &OutAnimationPoseData, const FAnimExtractContext &ExtractionContext) const override
int32 GetApproxBoneCompressedSize () const
int64 GetApproxBoneRawSize () const
int32 GetApproxCompressedSize () const
int64 GetApproxCurveRawSize () const
int64 GetApproxRawSize () const
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override
void GetBonePose (struct FAnimationPoseData &OutAnimationPoseData, const FAnimExtractContext &ExtractionContext, bool bForceUseRawData=false) const
Get Bone Transform of the Time given, relative to Parent for all RequiredBones This returns different transform based on additive or not.
void GetBonePose_Additive (FAnimationPoseData &OutAnimationPoseData, const FAnimExtractContext &ExtractionContext) const
Get Bone Transform of the additive animation for the Time given, relative to Parent for all RequiredBones.
FScopedCompressedAnimSequence GetCompressedData () const
FScopedCompressedAnimSequence GetCompressedData (const FAnimExtractContext &AnimExtractContext) const
FScopedCompressedAnimSequence GetCompressedData (const ITargetPlatform *InTargetPlatform) const
float GetCurrentTimeFromMarkers (FMarkerPair &PrevMarker, FMarkerPair &NextMarker, float PositionBetweenMarkers) const
FIoHash GetDerivedDataKeyHash (const ITargetPlatform *TargetPlatform) const
virtual bool GetEnableRootMotionSettingFromMontage () const override
virtual float GetFirstMatchingPosFromMarkerSyncPos (const FMarkerSyncAnimPosition &InMarkerSyncGroupPosition) const override
virtual void GetMarkerIndicesForPosition (const FMarkerSyncAnimPosition &SyncPosition, bool bLooping, FMarkerPair &OutPrevMarker, FMarkerPair &OutNextMarker, float &CurrentTime, const UMirrorDataTable *MirrorTable) const
virtual void GetMarkerIndicesForTime (float CurrentTime, bool bLooping, const TArray< FName > &ValidMarkerNames, FMarkerPair &OutPrevMarker, FMarkerPair &OutNextMarker) const
virtual FMarkerSyncAnimPosition GetMarkerSyncPositionFromMarkerIndicies (int32 PrevMarker, int32 NextMarker, float CurrentTime, const UMirrorDataTable *MirrorTable) const
virtual int32 GetMarkerUpdateCounter () const
virtual float GetNextMatchingPosFromMarkerSyncPos (const FMarkerSyncAnimPosition &InMarkerSyncGroupPosition, const float &StartingPosition) const override
virtual int32 GetNumberOfSampledKeys () const override
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps) override
virtual float GetPrevMatchingPosFromMarkerSyncPos (const FMarkerSyncAnimPosition &InMarkerSyncGroupPosition, const float &StartingPosition) const override
const TArray< FTransform > & GetRetargetTransforms () const
FName GetRetargetTransformsSourceName () const
virtual FFrameRate GetSamplingFrameRate () const override
FFrameRate GetTargetSamplingFrameRate (const ITargetPlatform *InPlatform) const
int64 GetUncompressedRawSize () const
virtual TArray< FName > * GetUniqueMarkerNames ()
virtual void HandleAssetPlayerTickedInternal (FAnimAssetTickContext &Context, const float PreviousTime, const float MoveDelta, const FAnimTickRecord &Instance, struct FAnimNotifyQueue &NotifyQueue) const override
bool HasCompressedDataForPlatform (const ITargetPlatform *InPlatform) const
virtual bool HasCurveData (FName CurveName, bool bForceUseRawData) const override
bool HasResidency (const ITargetPlatform *InPlatform) const
bool HasResidency (uint32 InReferencerHash) const
virtual bool HasRootMotion () const override
bool IsBoneCompressedDataValid () const
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform) override
bool IsCompressedDataOutOfDate () const
Return true if compressed data is invalid or if it is not in sync with the skeleton.
bool IsCompressedDataValid () const
bool IsCurveCompressedDataValid () const
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const override
virtual bool IsReadyForFinishDestroy () override
virtual bool IsValidAdditive () const override
virtual bool IsValidToPlay () const override
Add validation check to see if it's being ready to play or not.
virtual void OnSetSkeleton (USkeleton *NewSkeleton) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PreSave (FObjectPreSaveContext ObjectSaveContext) override
virtual void RefreshCacheData () override
void RefreshSyncMarkerDataFromAuthored ()
Refresh sync marker data.
void ReleaseResidency (const ITargetPlatform *InPlatform, uint32 InReferencerHash)
bool RemoveSyncMarkers (const TArray< FName > &MarkersToRemove)
Remove all markers with the specified names.
bool RenameSyncMarkers (FName InOldName, FName InNewName)
Rename the markers with the specified name.
virtual void ReplaceReferredAnimations (const TMap< UAnimationAsset *, UAnimationAsset * > &ReplacementMap) override
void RequestResidency (const ITargetPlatform *InPlatform, uint32 InReferencerHash)
void ResetAnimation ()
Resets Bone Animation, Curve data and Notify tracks.
void ResetCompressionSettings ()
void RetargetBoneTransform (FTransform &BoneTransform, const int32 SkeletonBoneIndex, const FCompactPoseBoneIndex &BoneIndex, const FBoneContainer &RequiredBones, const bool bIsBakedAdditive) const
Retarget a single bone transform, to apply right after extraction.
virtual void Serialize (FArchive &Ar) override
void SortSyncMarkers ()
Sort the sync markers array by time, earliest first.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const override
UE_DEPRECATED (5.6, "CacheDerivedData returning FCompressedAnimSequence reference has been deprecated, use CacheDerivedDataForPlatform") 1 FCompressedAnimSequence &CacheDerivedData(const ITargetPlatform *TargetPlatform)
UE_DEPRECATED (5.6, "DoesNeedRecompress has been renamed to IsCompressedDataOutOfDate") bool DoesNeedRecompress() const
UE_DEPRECATED (5.6, "GetCompressedCurveIndexedNames has been deprecated. Use GetCompressedData().IndexedCurveNames instead") const TArray< FAnimCompressedCurveIndexedName > &GetCompressedCurveIndexedNames() const
UE_DEPRECATED (5.6, "GetCompressedTrackToSkeletonMapTable has been deprecated. Use GetCompressedData().CompressedTrackToSkeletonMapTable instead") const TArray< FTrackToSkeletonMap > &GetCompressedTrackToSkeletonMapTable() const
UE_DEPRECATED (5.6, "Please use ExtractRootMotion with FAnimExtractContext") virtual FTransform ExtractRootMotion(float StartTime
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Please use ExtractRootMotionFromRange with FAnimExtractContext") virtual FTransform ExtractRootMotionFromRange(float StartTrackPosition
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Please use ExtractRootTrackTransform with FAnimExtractContext") virtual FTransform ExtractRootTrackTransform(float Time
UE_DEPRECATED (5.6, "Please use GetBoneTransform with FAnimExtractContext") 1 void GetBoneTransform(FTransform &OutAtom
Get Bone Transform of the Time given, relative to Parent for the Track Given.
UE_DEPRECATED (5.6, "Please use GetBoneTransform with FAnimExtractContext") void GetBoneTransform(FTransform &OutAtom
UE_DEPRECATED (5.6, "Public access to UseRawDataForPoseExtraction has been deprecated") 1 bool UseRawDataForPoseExtraction(const FBoneContainer &RequiredBones) const
UFUNCTION () 1 const TSoftObjectPtr< USkeletalMesh > &GetRetargetSourceAsset() const
UFUNCTION () 1 void ClearRetargetSourceAsset()
UFUNCTION () 1 void SetRetargetSourceAsset(USkeletalMesh *InRetargetSourceAsset)
UFUNCTION () 1 void UpdateRetargetSourceAssetData()
void UpdateDependentStreamingAnimations () const
UPROPERTY () TArray< FAnimSyncMarker > AuthoredSyncMarkers
Authored Sync markers.
void ValidateCurrentPosition (const FMarkerSyncAnimPosition &Position, bool bPlayingForwards, bool bLooping, float &CurrentTime, FMarkerPair &PreviousMarker, FMarkerPair &NextMarker, const UMirrorDataTable *MirrorTable=nullptr) const
Take a set of marker positions and validates them against a requested start position, updating them as desired.
void WaitOnExistingCompression (const bool bWantResults=true)
virtual void WillNeverCacheCookedPlatformDataAgain () override
Static Public Member Functions
static void AddReferencedObjects (UObject *This, FReferenceCollector &Collector)
Data Fields
FSkeletonPoseBoneIndex BoneIndex
FSkeletonPoseBoneIndex double bool bUseRawData
FSkeletonPoseBoneIndex FAnimSequenceDecompressionContext bool bUseRawData const
FSkeletonPoseBoneIndex FAnimSequenceDecompressionContext & DecompContext
float DeltaTime
float bool bAllowLooping const override final { PRAGMA_DISABLE_DEPRECATION_WARNINGS return UAnimSequenceBase::ExtractRootMotion(StartTime, DeltaTime, bAllowLooping)
PRAGMA_ENABLE_DEPRECATION_WARNINGS float EndTrackPosition const override final { PRAGMA_DISABLE_DEPRECATION_WARNINGS return UAnimSequenceBase::ExtractRootMotionFromRange(StartTrackPosition, EndTrackPosition)
PRAGMA_ENABLE_DEPRECATION_WARNINGS const FBoneContainer *RequiredBones const override final { PRAGMA_DISABLE_DEPRECATION_WARNINGS return UAnimSequenceBase::ExtractRootTrackTransform(Time, RequiredBones)
FSkeletonPoseBoneIndex double bool TOptional< EAnimInterpolationType > InterpolationOverride
FSkeletonPoseBoneIndex double Time
TArray< FName > UniqueMarkerNames
List of Unique marker names in this animation sequence.
Protected Member Functions
FIoHash BeginCacheDerivedData (const ITargetPlatform *TargetPlatform)
void CalculateNumberOfSampledKeys ()
virtual bool CanEvaluateRawAnimationData () const
Returns whether or not evaluation of the raw (source) animation data is possible according to whether or not the (editor only) data has been stripped.
void ClearAllCompressionData ()
void ClearCompressionData (const FIoHash &InKeyHash)
FIoHash CreateDerivedDataKeyHash (const ITargetPlatform *TargetPlatform) const
FString CreateDerivedDataKeyString (const ITargetPlatform *TargetPlatform) const
void DeleteBoneAnimationData ()
void DeleteDeprecatedRawAnimationData ()
void EndCacheDerivedData (const FIoHash &KeyHash)
void EnsureValidRawDataGuid ()
void EvaluateCurveData_Lockless (FBlendedCurve &OutCurve, const FAnimExtractContext &AnimExtractContext, bool bForceUseRawData=false) const
float EvaluateCurveData_Lockless (FName CurveName, const FAnimExtractContext &AnimExtractContext, bool bForceUseRawData=false) const
FTransform ExtractRootTrackTransform_Lockless (const FAnimExtractContext &ExtractionContext, const FBoneContainer *RequiredBones) const
void FinishAsyncTasks ()
int32 GetApproxBoneCompressedSize_Lockless () const
int32 GetApproxCompressedSize_Lockless () const
void GetBoneTransform_Lockless (FTransform &OutAtom, FSkeletonPoseBoneIndex BoneIndex, const FAnimExtractContext &ExtractionContext, bool bForceUseRawData) const
const FCompressedAnimSequence & GetPlatformCompressedData (const ITargetPlatform *InTargetPlatform) const
bool HasCompressedDataForHash (const FIoHash &InKeyHash) const
bool IsAsyncTaskComplete () const
bool IsCompiling () const
void MoveAttributesToModel ()
virtual void OnAnimModelLoaded () override
virtual void OnModelModified (const EAnimDataModelNotifyType &NotifyType, IAnimationDataModel *Model, const FAnimDataModelNotifPayload &Payload) override
bool PollCacheDerivedData (const FIoHash &KeyHash) const
virtual void PopulateModel () override
bool RequiresResidency (const FIoHash &InKeyHash) const
void Reschedule (FQueuedThreadPool *InThreadPool, EQueuedWorkPriority InPriority)
void SerializeCompressedData (FArchive &Ar, bool bDDCData)
void SerializeCompressedData (FArchive &Ar, FCompressedAnimSequence &CompressedData)
bool ShouldPerformStripping (const bool bPerformFrameStripping, const bool bPerformStrippingOnOddFramedAnims) const
bool ShouldUseRawDataForPoseExtraction (const FBoneContainer &RequiredBones, const FAnimExtractContext &ExtractionContext) const
bool ShouldUseRawDataForPoseExtraction_Lockless (const FAnimExtractContext &ExtractionContext) const
bool ShouldUseRawDataForPoseExtraction_Lockless (const FBoneContainer &RequiredBones, const FAnimExtractContext &ExtractionContext) const
void SynchronousAnimatedBoneAttributesCompression ()
bool TryCancelAsyncTasks ()
UE_DEPRECATED (5.6, "ClearCompressedBoneData will be removed") void ClearCompressedBoneData()
UE_DEPRECATED (5.6, "ClearCompressedCurveData will be removed") void ClearCompressedCurveData()
UPROPERTY () FPerPlatformFrameRate PlatformTargetFrameRate
UPROPERTY () TMap< FAnimationAttributeIdentifier
void ValidateCompressionSettings ()
bool WaitForAsyncTasks (float TimeLimitSeconds)
Protected Attributes
FAttributeCurve AttributeCurves
TAtomic< bool > bShouldClearCompressedData = false
TMap< FIoHash, TPimplPtr< UE::Anim::FAnimationSequenceAsyncCacheTask > > CacheTasksByKeyHash
FCompressedAnimSequence * CurrentPlatformData = nullptr
TMap< FIoHash, TUniquePtr< FCompressedAnimSequence > > DataByPlatformKeyHash
FRWLock HashCacheLock
TMap< uint32, FIoHash > PlatformHashToKeyHash
TMultiMap< FIoHash, uint32 > PlatformHashToReferencers
FRWLock ResidencyLock
TMultiMap< uint32, FIoHash > ResidencyReferencerHashes
UE::FSharedRecursiveMutex SharedCompressedDataMutex
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY()) TObjectPtr< class UAnimBoneCompressionSettings > BoneCompressionSettings
The bone compression settings used to compress bones in this sequence.
void GetBonePose_AdditiveMeshRotationOnly (FAnimationPoseData &OutAnimationPoseData, const FAnimExtractContext &ExtractionContext) const
Get Bone Transform of the animation for the Time given, relative to Parent for all RequiredBones This return mesh rotation only additive pose.
FCompressedAnimSequence & GetCompressedData_Internal ()
const FCompressedAnimSequence & GetCompressedData_Internal () const
FCompressedAnimSequence & GetPlatformCompressedData (const FAnimExtractContext &AnimExtractContext)
const FCompressedAnimSequence & GetPlatformCompressedData (const FAnimExtractContext &AnimExtractContext) const
FCompressedAnimSequence & GetPlatformCompressedData (const ITargetPlatform *InTargetPlatform)
int32 GetSpaceBasedAnimationData (TArray< TArray< FTransform > > &AnimationDataInComponentSpace) const
Retargeting functions.
virtual void RemapTracksToNewSkeleton (USkeleton *NewSkeleton, bool bConvertSpaces) override
Remap Tracks to New Skeleton.
UE_DEPRECATED (5.6, "CompressedData public access will be removed") FCompressedAnimSequence CompressedData
UPROPERTY () bool bEnableRootMotion
If this is on, it will allow extracting of root motion.
UPROPERTY() TEnumAsByte< ERootMotionRootLock UPROPERTY () bool bForceRootLock
Root Bone will be locked to that position when extracting root motion.
UPROPERTY () bool bRootMotionSettingsCopiedFromMontage
Have we copied root motion settings from an owning montage.
UPROPERTY () bool bUseNormalizedRootMotionScale
If this is on, it will use a normalized scale value for the root motion extracted: FVector(1.0, 1.0, 1.0)
UPROPERTY () EAnimInterpolationType Interpolation
This defines how values between keys are calculated.
UPROPERTY () EStripAnimDataOnDedicatedServerSettings StripAnimDataOnDedicatedServer
Enum used to decide whether we should strip animation data on dedicated server.
UPROPERTY () FName RetargetSource
Base pose to use when retargeting.
UPROPERTY () int32 RefFrameIndex
UPROPERTY () TArray< FTransform > RetargetSourceAssetReferencePose
When using RetargetSourceAsset, use the post stored here.
UPROPERTY () TEnumAsByte< enum EAdditiveAnimationType > AdditiveAnimType
Additive animation type.
UPROPERTY ()) TEnumAsByte< enum EAdditiveBasePoseType > RefPoseType
UPROPERTY ()) TObjectPtr< class UAnimCurveCompressionSettings > CurveCompressionSettings
The curve compression settings used to compress curves in this sequence.
UPROPERTY ()) TObjectPtr< class UAnimSequence > RefPoseSeq
UPROPERTY ()) TObjectPtr< class UVariableFrameStrippingSettings > VariableFrameStrippingSettings
Friends
class FAnimBankBuildAsyncCacheTask
struct FAnimCurveBufferAccess
class FAnimDataControllerTestBase
class FAnimSequenceDetails
class FAnimSequenceDeterminismHelper
class FAnimSequenceTestBase
class FCompressedAnimationDataNodeBuilder
class FCustomAttributeCustomization
struct FScopedAnimSequenceRawDataCache
class UAnimationAsset
class UAnimationBlueprintLibrary
class UAnimBank
class UAnimBoneCompressionSettings
struct UE::Anim::Compression::FScopedCompressionGuard
class UE::Anim::FAnimationSequenceAsyncCacheTask
class UE::Anim::FAnimSequenceCompilingManager
Detailed Description
Definition at line 202 of file AnimSequence.h.
Member Function Documentation
AddKeyToSequence()
void UAnimSequence::AddKeyToSequence (float Time, const FName & BoneName, const FTransform & AdditiveTransform)
Add Key to Transform Curves.
References Time.
AddReferencedObjects()
void UAnimSequence::AddReferencedObjects (UObject * This, FReferenceCollector & Collector) static
References AddReferencedObjects().
Referenced by AddReferencedObjects().
AdvanceMarkerPhaseAsFollower()
virtual void UAnimSequence::AdvanceMarkerPhaseAsFollower (const FMarkerTickContext & Context, float DeltaRemaining, bool bLooping, float & CurrentTime, FMarkerPair & PreviousMarker, FMarkerPair & NextMarker, const UMirrorDataTable * MirrorTable) const virtual
AdvanceMarkerPhaseAsLeader()
virtual void UAnimSequence::AdvanceMarkerPhaseAsLeader (bool bLooping, float MoveDelta, const TArray< FName > & ValidMarkerNames, float & CurrentTime, FMarkerPair & PrevMarker, FMarkerPair & NextMarker, TArray< FPassedMarker > & MarkersPassed, const UMirrorDataTable * MirrorTable) const virtual
BeginCacheDerivedData()
FIoHash UAnimSequence::BeginCacheDerivedData (const ITargetPlatform * TargetPlatform) protected
BeginCacheDerivedDataForCurrentPlatform()
void UAnimSequence::BeginCacheDerivedDataForCurrentPlatform ()
BeginCacheForCookedPlatformData()
virtual void UAnimSequence::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform) override virtual
BeginDestroy()
virtual void UAnimSequence::BeginDestroy () override virtual
CacheDerivedDataForCurrentPlatform()
void UAnimSequence::CacheDerivedDataForCurrentPlatform ()
CacheDerivedDataForPlatform()
void UAnimSequence::CacheDerivedDataForPlatform (const ITargetPlatform * TargetPlatform)
CalculateNumberOfSampledKeys()
void UAnimSequence::CalculateNumberOfSampledKeys () protected
CanBakeAdditive()
bool UAnimSequence::CanBakeAdditive () const
CanBeCompressed()
bool UAnimSequence::CanBeCompressed () const
CanEvaluateRawAnimationData()
virtual bool UAnimSequence::CanEvaluateRawAnimationData () const protected virtual
Returns whether or not evaluation of the raw (source) animation data is possible according to whether or not the (editor only) data has been stripped.
ClearAllCachedCookedPlatformData()
virtual void UAnimSequence::ClearAllCachedCookedPlatformData () override virtual
ClearAllCompressionData()
void UAnimSequence::ClearAllCompressionData () protected
ClearCompressionData()
void UAnimSequence::ClearCompressionData (const FIoHash & InKeyHash) protected
CreateAnimation() [1/3]
bool UAnimSequence::CreateAnimation (class UAnimSequence * Sequence)
Create Animation Sequence from the given animation.
CreateAnimation() [2/3]
bool UAnimSequence::CreateAnimation (class USkeletalMesh * Mesh)
Create Animation Sequence from Reference Pose of the Mesh.
References Mesh.
CreateAnimation() [3/3]
bool UAnimSequence::CreateAnimation (class USkeletalMeshComponent * MeshComponent)
Create Animation Sequence from the Mesh Component's current bone transform.
CreateDerivedDataKeyHash()
FIoHash UAnimSequence::CreateDerivedDataKeyHash (const ITargetPlatform * TargetPlatform) const protected
CreateDerivedDataKeyString()
FString UAnimSequence::CreateDerivedDataKeyString (const ITargetPlatform * TargetPlatform) const protected
DeleteBoneAnimationData()
void UAnimSequence::DeleteBoneAnimationData () protected
DeleteDeprecatedRawAnimationData()
void UAnimSequence::DeleteDeprecatedRawAnimationData () protected
DeleteNotifyTrackData()
void UAnimSequence::DeleteNotifyTrackData ()
DoesSequenceContainZeroScale()
bool UAnimSequence::DoesSequenceContainZeroScale () const
EnableRootMotionSettingFromMontage()
virtual void UAnimSequence::EnableRootMotionSettingFromMontage (bool bInEnableRootMotion, const ERootMotionRootLock::Type InRootMotionRootLock) override virtual
EndCacheDerivedData()
void UAnimSequence::EndCacheDerivedData (const FIoHash & KeyHash) protected
EnsureValidRawDataGuid()
void UAnimSequence::EnsureValidRawDataGuid () protected
EvaluateAttributes()
void UAnimSequence::EvaluateAttributes (FAnimationPoseData & OutAnimationPoseData, const FAnimExtractContext & ExtractionContext, bool bUseRawData) const
References bUseRawData, const, EvaluateAttributes(), and ExtractionContext.
Referenced by EvaluateAttributes().
EvaluateCurveData() [1/2]
virtual void UAnimSequence::EvaluateCurveData (FBlendedCurve & OutCurve, const FAnimExtractContext & AnimExtractContext, bool bForceUseRawData = false) const override virtual
EvaluateCurveData() [2/2]
virtual float UAnimSequence::EvaluateCurveData (FName CurveName, const FAnimExtractContext & AnimExtractContext, bool bForceUseRawData = false) const override virtual
EvaluateCurveData_Lockless() [1/2]
void UAnimSequence::EvaluateCurveData_Lockless (FBlendedCurve & OutCurve, const FAnimExtractContext & AnimExtractContext, bool bForceUseRawData = false) const protected
EvaluateCurveData_Lockless() [2/2]
float UAnimSequence::EvaluateCurveData_Lockless (FName CurveName, const FAnimExtractContext & AnimExtractContext, bool bForceUseRawData = false) const protected
ExtractRootMotion()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS FTransform UAnimSequence::ExtractRootMotion (const FAnimExtractContext & ExtractionContext) const final override virtual
References ExtractionContext.
ExtractRootMotionFromRange()
virtual FTransform UAnimSequence::ExtractRootMotionFromRange (double StartTime, double EndTime, const FAnimExtractContext & ExtractionContext) const final override virtual
References ExtractionContext.
ExtractRootTrackTransform()
virtual FTransform UAnimSequence::ExtractRootTrackTransform (const FAnimExtractContext & ExtractionContext, const FBoneContainer * RequiredBones) const final override virtual
References ExtractionContext.
ExtractRootTrackTransform_Lockless()
FTransform UAnimSequence::ExtractRootTrackTransform_Lockless (const FAnimExtractContext & ExtractionContext, const FBoneContainer * RequiredBones) const protected
References ExtractionContext.
FindSyncMarkerPropertyData()
uint8 * UAnimSequence::FindSyncMarkerPropertyData (int32 SyncMarkerIndex, FArrayProperty *& ArrayProperty)
References ArrayProperty.
FinishAsyncTasks()
void UAnimSequence::FinishAsyncTasks () protected
FlagDependentAnimationsAsRawDataOnly()
void UAnimSequence::FlagDependentAnimationsAsRawDataOnly () const
GENERATED_UCLASS_BODY()
UAnimSequence::GENERATED_UCLASS_BODY () private
The bone compression settings used to compress bones in this sequence.
References Category, float, meta, NumFrames, UE_DEPRECATED(), and UPROPERTY().
GetAdditiveAnimType()
virtual EAdditiveAnimationType UAnimSequence::GetAdditiveAnimType () const inline override virtual
Definition at line 408 of file AnimSequence.h.
GetAdditiveBasePose() [1/2]
virtual class UAnimSequence * UAnimSequence::GetAdditiveBasePose () const inline override virtual
Definition at line 683 of file AnimSequence.h.
References IsValidAdditive().
GetAdditiveBasePose() [2/2]
void UAnimSequence::GetAdditiveBasePose (FAnimationPoseData & OutAnimationPoseData, const FAnimExtractContext & ExtractionContext) const
Get Bone Transform of the base (reference) pose of the additive animation for the Time given, relative to Parent for all RequiredBones.
Parameters
OutAnimationPoseData [out] Output pose data
ExtractionContext Extraction Context (position, looping, root motion, etc.)
References ExtractionContext.
GetAllAnimationSequencesReferred()
virtual bool UAnimSequence::GetAllAnimationSequencesReferred (TArray< UAnimationAsset * > & AnimationAssets, bool bRecursive = true) override virtual
GetAnimationPose()
virtual void UAnimSequence::GetAnimationPose (FAnimationPoseData & OutAnimationPoseData, const FAnimExtractContext & ExtractionContext) const override virtual
References ExtractionContext.
GetApproxBoneCompressedSize()
int32 UAnimSequence::GetApproxBoneCompressedSize () const
Returns
The approximate size of compressed animation data for only bones.
GetApproxBoneCompressedSize_Lockless()
int32 UAnimSequence::GetApproxBoneCompressedSize_Lockless () const protected
Returns
The approximate size of compressed animation data for only bones.
GetApproxBoneRawSize()
int64 UAnimSequence::GetApproxBoneRawSize () const
Returns
The approximate size of raw bone animation data.
GetApproxCompressedSize()
int32 UAnimSequence::GetApproxCompressedSize () const
Returns
The approximate size of compressed animation data.
GetApproxCompressedSize_Lockless()
int32 UAnimSequence::GetApproxCompressedSize_Lockless () const protected
Returns
The approximate size of compressed animation data.
GetApproxCurveRawSize()
int64 UAnimSequence::GetApproxCurveRawSize () const
Returns
The approximate size of raw curve animation data.
GetApproxRawSize()
int64 UAnimSequence::GetApproxRawSize () const
Returns
The approximate size of raw animation data.
GetAssetRegistryTags()
virtual void UAnimSequence::GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override virtual
Referenced by UE_DEPRECATED().
GetBonePose()
void UAnimSequence::GetBonePose (struct FAnimationPoseData & OutAnimationPoseData, const FAnimExtractContext & ExtractionContext, bool bForceUseRawData = false) const
Get Bone Transform of the Time given, relative to Parent for all RequiredBones This returns different transform based on additive or not.
Or what kind of additive.
Parameters
OutAnimationPoseData [out] Animation Pose related data to populate
ExtractionContext Extraction Context (position, looping, root motion, etc.)
bForceUseRawData Whether or not to forcefully try to sample the animation data model
References ExtractionContext.
GetBonePose_Additive()
void UAnimSequence::GetBonePose_Additive (FAnimationPoseData & OutAnimationPoseData, const FAnimExtractContext & ExtractionContext) const
Get Bone Transform of the additive animation for the Time given, relative to Parent for all RequiredBones.
Parameters
OutAnimationPoseData [out] Output pose data
ExtractionContext Extraction Context (position, looping, root motion, etc.)
References ExtractionContext.
GetBonePose_AdditiveMeshRotationOnly()
void UAnimSequence::GetBonePose_AdditiveMeshRotationOnly (FAnimationPoseData & OutAnimationPoseData, const FAnimExtractContext & ExtractionContext) const private
Get Bone Transform of the animation for the Time given, relative to Parent for all RequiredBones This return mesh rotation only additive pose.
Parameters
OutAnimationPoseData [out] Output pose data
ExtractionContext Extraction Context (position, looping, root motion, etc.)
References ExtractionContext.
GetBoneTransform_Lockless()
void UAnimSequence::GetBoneTransform_Lockless (FTransform & OutAtom, FSkeletonPoseBoneIndex BoneIndex, const FAnimExtractContext & ExtractionContext, bool bForceUseRawData) const protected
References BoneIndex, and ExtractionContext.
GetCompressedData() [1/3]
FScopedCompressedAnimSequence UAnimSequence::GetCompressedData () const
GetCompressedData() [2/3]
FScopedCompressedAnimSequence UAnimSequence::GetCompressedData (const FAnimExtractContext & AnimExtractContext) const
GetCompressedData() [3/3]
FScopedCompressedAnimSequence UAnimSequence::GetCompressedData (const ITargetPlatform * InTargetPlatform) const
GetCompressedData_Internal() [1/2]
FCompressedAnimSequence & UAnimSequence::GetCompressedData_Internal () private
GetCompressedData_Internal() [2/2]
const FCompressedAnimSequence & UAnimSequence::GetCompressedData_Internal () const private
GetCurrentTimeFromMarkers()
float UAnimSequence::GetCurrentTimeFromMarkers (FMarkerPair & PrevMarker, FMarkerPair & NextMarker, float PositionBetweenMarkers) const
GetDerivedDataKeyHash()
FIoHash UAnimSequence::GetDerivedDataKeyHash (const ITargetPlatform * TargetPlatform) const
GetEnableRootMotionSettingFromMontage()
virtual bool UAnimSequence::GetEnableRootMotionSettingFromMontage () const override virtual
GetFirstMatchingPosFromMarkerSyncPos()
virtual float UAnimSequence::GetFirstMatchingPosFromMarkerSyncPos (const FMarkerSyncAnimPosition & InMarkerSyncGroupPosition) const override virtual
GetMarkerIndicesForPosition()
virtual void UAnimSequence::GetMarkerIndicesForPosition (const FMarkerSyncAnimPosition & SyncPosition, bool bLooping, FMarkerPair & OutPrevMarker, FMarkerPair & OutNextMarker, float & CurrentTime, const UMirrorDataTable * MirrorTable) const virtual
GetMarkerIndicesForTime()
virtual void UAnimSequence::GetMarkerIndicesForTime (float CurrentTime, bool bLooping, const TArray< FName > & ValidMarkerNames, FMarkerPair & OutPrevMarker, FMarkerPair & OutNextMarker) const virtual
GetMarkerSyncPositionFromMarkerIndicies()
virtual FMarkerSyncAnimPosition UAnimSequence::GetMarkerSyncPositionFromMarkerIndicies (int32 PrevMarker, int32 NextMarker, float CurrentTime, const UMirrorDataTable * MirrorTable) const virtual
GetMarkerUpdateCounter()
virtual int32 UAnimSequence::GetMarkerUpdateCounter () const inline virtual
Definition at line 651 of file AnimSequence.h.
GetNextMatchingPosFromMarkerSyncPos()
virtual float UAnimSequence::GetNextMatchingPosFromMarkerSyncPos (const FMarkerSyncAnimPosition & InMarkerSyncGroupPosition, const float & StartingPosition) const override virtual
GetNumberOfSampledKeys()
virtual int32 UAnimSequence::GetNumberOfSampledKeys () const override virtual
GetPlatformCompressedData() [1/4]
FCompressedAnimSequence & UAnimSequence::GetPlatformCompressedData (const FAnimExtractContext & AnimExtractContext) private
GetPlatformCompressedData() [2/4]
const FCompressedAnimSequence & UAnimSequence::GetPlatformCompressedData (const FAnimExtractContext & AnimExtractContext) const private
GetPlatformCompressedData() [3/4]
FCompressedAnimSequence & UAnimSequence::GetPlatformCompressedData (const ITargetPlatform * InTargetPlatform) private
GetPlatformCompressedData() [4/4]
const FCompressedAnimSequence & UAnimSequence::GetPlatformCompressedData (const ITargetPlatform * InTargetPlatform) const protected
GetPreloadDependencies()
virtual void UAnimSequence::GetPreloadDependencies (TArray< UObject * > & OutDeps) override virtual
GetPrevMatchingPosFromMarkerSyncPos()
virtual float UAnimSequence::GetPrevMatchingPosFromMarkerSyncPos (const FMarkerSyncAnimPosition & InMarkerSyncGroupPosition, const float & StartingPosition) const override virtual
GetRetargetTransforms()
const TArray< FTransform > & UAnimSequence::GetRetargetTransforms () const
GetRetargetTransformsSourceName()
FName UAnimSequence::GetRetargetTransformsSourceName () const
GetSamplingFrameRate()
virtual FFrameRate UAnimSequence::GetSamplingFrameRate () const inline override virtual
Definition at line 410 of file AnimSequence.h.
GetSpaceBasedAnimationData()
int32 UAnimSequence::GetSpaceBasedAnimationData (TArray< TArray< FTransform > > & AnimationDataInComponentSpace) const private
Retargeting functions.
GetTargetSamplingFrameRate()
FFrameRate UAnimSequence::GetTargetSamplingFrameRate (const ITargetPlatform * InPlatform) const
References const, and GetTargetSamplingFrameRate().
Referenced by GetTargetSamplingFrameRate().
GetUncompressedRawSize()
int64 UAnimSequence::GetUncompressedRawSize () const
Returns
estimate uncompressed raw size. This is not the real raw size. Here we estimate what it would be with no trivial compression.
GetUniqueMarkerNames()
virtual TArray< FName > * UAnimSequence::GetUniqueMarkerNames () inline virtual
Definition at line 396 of file AnimSequence.h.
References GetUniqueMarkerNames(), and UniqueMarkerNames.
Referenced by GetUniqueMarkerNames().
HandleAssetPlayerTickedInternal()
virtual void UAnimSequence::HandleAssetPlayerTickedInternal (FAnimAssetTickContext & Context, const float PreviousTime, const float MoveDelta, const FAnimTickRecord & Instance, struct FAnimNotifyQueue & NotifyQueue) const override virtual
References Instance.
HasCompressedDataForHash()
bool UAnimSequence::HasCompressedDataForHash (const FIoHash & InKeyHash) const protected
HasCompressedDataForPlatform()
bool UAnimSequence::HasCompressedDataForPlatform (const ITargetPlatform * InPlatform) const
HasCurveData()
virtual bool UAnimSequence::HasCurveData (FName CurveName, bool bForceUseRawData) const override virtual
HasResidency() [1/2]
bool UAnimSequence::HasResidency (const ITargetPlatform * InPlatform) const
HasResidency() [2/2]
bool UAnimSequence::HasResidency (uint32 InReferencerHash) const
HasRootMotion()
virtual bool UAnimSequence::HasRootMotion () const inline override virtual
Definition at line 406 of file AnimSequence.h.
IsAsyncTaskComplete()
bool UAnimSequence::IsAsyncTaskComplete () const protected
IsBoneCompressedDataValid()
bool UAnimSequence::IsBoneCompressedDataValid () const
IsCachedCookedPlatformDataLoaded()
virtual bool UAnimSequence::IsCachedCookedPlatformDataLoaded (const ITargetPlatform * TargetPlatform) override virtual
IsCompiling()
bool UAnimSequence::IsCompiling () const protected
IsCompressedDataOutOfDate()
bool UAnimSequence::IsCompressedDataOutOfDate () const
Return true if compressed data is invalid or if it is not in sync with the skeleton.
Referenced by UE_DEPRECATED().
IsCompressedDataValid()
bool UAnimSequence::IsCompressedDataValid () const
IsCurveCompressedDataValid()
bool UAnimSequence::IsCurveCompressedDataValid () const
IsDataValid()
virtual EDataValidationResult UAnimSequence::IsDataValid (class FDataValidationContext & Context) const override virtual
IsReadyForFinishDestroy()
virtual bool UAnimSequence::IsReadyForFinishDestroy () override virtual
IsValidAdditive()
virtual bool UAnimSequence::IsValidAdditive () const override virtual
References const, and IsValidAdditive().
Referenced by GetAdditiveBasePose(), and IsValidAdditive().
IsValidToPlay()
virtual bool UAnimSequence::IsValidToPlay () const override virtual
Add validation check to see if it's being ready to play or not.
MoveAttributesToModel()
void UAnimSequence::MoveAttributesToModel () protected
OnAnimModelLoaded()
virtual void UAnimSequence::OnAnimModelLoaded () override protected virtual
OnModelModified()
virtual void UAnimSequence::OnModelModified (const EAnimDataModelNotifyType & NotifyType, IAnimationDataModel * Model, const FAnimDataModelNotifPayload & Payload) override protected virtual
OnSetSkeleton()
virtual void UAnimSequence::OnSetSkeleton (USkeleton * NewSkeleton) override virtual
PollCacheDerivedData()
bool UAnimSequence::PollCacheDerivedData (const FIoHash & KeyHash) const protected
PopulateModel()
virtual void UAnimSequence::PopulateModel () override protected virtual
PostEditChangeProperty()
virtual void UAnimSequence::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void UAnimSequence::PostInitProperties () override virtual
PostLoad()
virtual void UAnimSequence::PostLoad () override virtual
PreSave()
virtual void UAnimSequence::PreSave (FObjectPreSaveContext ObjectSaveContext) override virtual
RefreshCacheData()
virtual void UAnimSequence::RefreshCacheData () override virtual
RefreshSyncMarkerDataFromAuthored()
void UAnimSequence::RefreshSyncMarkerDataFromAuthored ()
Refresh sync marker data.
ReleaseResidency()
void UAnimSequence::ReleaseResidency (const ITargetPlatform * InPlatform, uint32 InReferencerHash)
RemapTracksToNewSkeleton()
virtual void UAnimSequence::RemapTracksToNewSkeleton (USkeleton * NewSkeleton, bool bConvertSpaces) override private virtual
Remap Tracks to New Skeleton.
RemoveSyncMarkers()
bool UAnimSequence::RemoveSyncMarkers (const TArray< FName > & MarkersToRemove)
Remove all markers with the specified names.
RenameSyncMarkers()
bool UAnimSequence::RenameSyncMarkers (FName InOldName, FName InNewName)
Rename the markers with the specified name.
ReplaceReferredAnimations()
virtual void UAnimSequence::ReplaceReferredAnimations (const TMap< UAnimationAsset *, UAnimationAsset * > & ReplacementMap) override virtual
RequestResidency()
void UAnimSequence::RequestResidency (const ITargetPlatform * InPlatform, uint32 InReferencerHash)
RequiresResidency()
bool UAnimSequence::RequiresResidency (const FIoHash & InKeyHash) const protected
Reschedule()
void UAnimSequence::Reschedule (FQueuedThreadPool * InThreadPool, EQueuedWorkPriority InPriority) protected
ResetAnimation()
void UAnimSequence::ResetAnimation ()
Resets Bone Animation, Curve data and Notify tracks.
ResetCompressionSettings()
void UAnimSequence::ResetCompressionSettings ()
RetargetBoneTransform()
void UAnimSequence::RetargetBoneTransform (FTransform & BoneTransform, const int32 SkeletonBoneIndex, const FCompactPoseBoneIndex & BoneIndex, const FBoneContainer & RequiredBones, const bool bIsBakedAdditive) const
Retarget a single bone transform, to apply right after extraction.
Parameters
BoneTransform BoneTransform to read/write from.
SkeletonBoneIndex Bone Index in USkeleton.
BoneIndex Bone Index in Bone Transform array.
RequiredBones BoneContainer
References bIsBakedAdditive, and BoneIndex.
Serialize()
virtual void UAnimSequence::Serialize (FArchive & Ar) override virtual
References Ar.
SerializeCompressedData() [1/2]
void UAnimSequence::SerializeCompressedData (FArchive & Ar, bool bDDCData) protected
References Ar.
SerializeCompressedData() [2/2]
void UAnimSequence::SerializeCompressedData (FArchive & Ar, FCompressedAnimSequence & CompressedData) protected
References Ar, and CompressedData.
ShouldPerformStripping()
bool UAnimSequence::ShouldPerformStripping (const bool bPerformFrameStripping, const bool bPerformStrippingOnOddFramedAnims) const protected
ShouldUseRawDataForPoseExtraction()
bool UAnimSequence::ShouldUseRawDataForPoseExtraction (const FBoneContainer & RequiredBones, const FAnimExtractContext & ExtractionContext) const protected
References ExtractionContext.
ShouldUseRawDataForPoseExtraction_Lockless() [1/2]
bool UAnimSequence::ShouldUseRawDataForPoseExtraction_Lockless (const FAnimExtractContext & ExtractionContext) const protected
References ExtractionContext.
ShouldUseRawDataForPoseExtraction_Lockless() [2/2]
bool UAnimSequence::ShouldUseRawDataForPoseExtraction_Lockless (const FBoneContainer & RequiredBones, const FAnimExtractContext & ExtractionContext) const protected
References ExtractionContext.
SortSyncMarkers()
void UAnimSequence::SortSyncMarkers ()
Sort the sync markers array by time, earliest first.
SynchronousAnimatedBoneAttributesCompression()
void UAnimSequence::SynchronousAnimatedBoneAttributesCompression () protected
TryCancelAsyncTasks()
bool UAnimSequence::TryCancelAsyncTasks () protected
UE_DEPRECATED() [1/14]
UAnimSequence::UE_DEPRECATED (5. 4, "Implement the version that takes FAssetRegistryTagsContext instead.") const & override
References const, and GetAssetRegistryTags().
UE_DEPRECATED() [2/14]
UAnimSequence::UE_DEPRECATED (5. 6, "CacheDerivedData returning FCompressedAnimSequence reference has been deprecated, use CacheDerivedDataForPlatform") const &
References const.
UE_DEPRECATED() [3/14]
UAnimSequence::UE_DEPRECATED (5. 6, "ClearCompressedBoneData will be removed") inline protected
Definition at line 601 of file AnimSequence.h.
UE_DEPRECATED() [4/14]
UAnimSequence::UE_DEPRECATED (5. 6, "ClearCompressedCurveData will be removed") inline protected
Definition at line 603 of file AnimSequence.h.
UE_DEPRECATED() [5/14]
UAnimSequence::UE_DEPRECATED (5. 6, "CompressedData public access will be removed") private
References CompressedData.
Referenced by GENERATED_UCLASS_BODY(), and UPROPERTY().
UE_DEPRECATED() [6/14]
UAnimSequence::UE_DEPRECATED (5. 6, "DoesNeedRecompress has been renamed to IsCompressedDataOutOfDate") const inline
Definition at line 622 of file AnimSequence.h.
References bool, and IsCompressedDataOutOfDate().
UE_DEPRECATED() [7/14]
UAnimSequence::UE_DEPRECATED (5. 6, "GetCompressedCurveIndexedNames has been deprecated. Use GetCompressedData().IndexedCurveNames instead") const & inline
Definition at line 452 of file AnimSequence.h.
References const.
UE_DEPRECATED() [8/14]
UAnimSequence::UE_DEPRECATED (5. 6, "GetCompressedTrackToSkeletonMapTable has been deprecated. Use GetCompressedData().CompressedTrackToSkeletonMapTable instead") const & inline
Definition at line 445 of file AnimSequence.h.
References const.
UE_DEPRECATED() [9/14]
UAnimSequence::UE_DEPRECATED (5. 6, "Please use ExtractRootMotion with FAnimExtractContext")
UE_DEPRECATED() [10/14]
PRAGMA_ENABLE_DEPRECATION_WARNINGS UAnimSequence::UE_DEPRECATED (5. 6, "Please use ExtractRootMotionFromRange with FAnimExtractContext")
UE_DEPRECATED() [11/14]
PRAGMA_ENABLE_DEPRECATION_WARNINGS UAnimSequence::UE_DEPRECATED (5. 6, "Please use ExtractRootTrackTransform with FAnimExtractContext")
UE_DEPRECATED() [12/14]
UAnimSequence::UE_DEPRECATED (5. 6, "Please use GetBoneTransform with FAnimExtractContext") &
Get Bone Transform of the Time given, relative to Parent for the Track Given.
This will sample the compressed data for the current platform only. (if available)
Parameters
OutAtom [out] Output bone transform.
BoneIndex Index of bone to evaluate.
DecompContext Decompression context to use.
bUseRawData If true, use raw animation data instead of compressed data.
UE_DEPRECATED() [13/14]
UAnimSequence::UE_DEPRECATED (5. 6, "Please use GetBoneTransform with FAnimExtractContext") &
UE_DEPRECATED() [14/14]
UAnimSequence::UE_DEPRECATED (5. 6, "Public access to UseRawDataForPoseExtraction has been deprecated") const &
References const.
UFUNCTION() [1/4]
UAnimSequence::UFUNCTION () const &
References Category, const, and UFUNCTION().
UFUNCTION() [2/4]
UAnimSequence::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [3/4]
UAnimSequence::UFUNCTION ()
References Category.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/4]
UAnimSequence::UFUNCTION ()
References Category, and UFUNCTION().
UpdateDependentStreamingAnimations()
void UAnimSequence::UpdateDependentStreamingAnimations () const
UPROPERTY() [1/17]
UAnimSequence::UPROPERTY () private
If this is on, it will allow extracting of root motion.
References Category, and UPROPERTY().
UPROPERTY() [2/17]
UPROPERTY() TEnumAsByte< ERootMotionRootLock UAnimSequence::UPROPERTY () private
Root Bone will be locked to that position when extracting root motion.
Force Root Bone Lock even if Root Motion is not enabled
References Category, and UPROPERTY().
UPROPERTY() [3/17]
UAnimSequence::UPROPERTY () private
Have we copied root motion settings from an owning montage.
References Category, and UPROPERTY().
UPROPERTY() [4/17]
UAnimSequence::UPROPERTY () private
If this is on, it will use a normalized scale value for the root motion extracted: FVector(1.0, 1.0, 1.0)
References Category, and UPROPERTY().
UPROPERTY() [5/17]
UAnimSequence::UPROPERTY () private
This defines how values between keys are calculated.
References Animation, Category, Interpolation, and UPROPERTY().
UPROPERTY() [6/17]
UAnimSequence::UPROPERTY () private
Enum used to decide whether we should strip animation data on dedicated server.
References Category.
UPROPERTY() [7/17]
UAnimSequence::UPROPERTY () private
Base pose to use when retargeting.
References Animation, Category, meta, RetargetSource, and UPROPERTY().
UPROPERTY() [8/17]
UAnimSequence::UPROPERTY () protected
References Category, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, Transient, UE_DEPRECATED(), and UPROPERTY().
UPROPERTY() [9/17]
UAnimSequence::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [10/17]
UAnimSequence::UPROPERTY ()
Authored Sync markers.
References UPROPERTY().
UPROPERTY() [11/17]
UAnimSequence::UPROPERTY () private
When using RetargetSourceAsset, use the post stored here.
UPROPERTY() [12/17]
UAnimSequence::UPROPERTY () private
Additive animation type.
References Category, and UPROPERTY().
UPROPERTY() [13/17]
UAnimSequence::UPROPERTY () protected
UPROPERTY() [14/17]
UAnimSequence::UPROPERTY () private
References Category, meta, and UPROPERTY().
UPROPERTY() [15/17]
UAnimSequence::UPROPERTY () private
The curve compression settings used to compress curves in this sequence.
References Category, and meta.
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [16/17]
UAnimSequence::UPROPERTY () private
References Category, meta, and UPROPERTY().
UPROPERTY() [17/17]
UAnimSequence::UPROPERTY () private
References Category, meta, and UPROPERTY().
ValidateCompressionSettings()
void UAnimSequence::ValidateCompressionSettings () protected
ValidateCurrentPosition()
void UAnimSequence::ValidateCurrentPosition (const FMarkerSyncAnimPosition & Position, bool bPlayingForwards, bool bLooping, float & CurrentTime, FMarkerPair & PreviousMarker, FMarkerPair & NextMarker, const UMirrorDataTable * MirrorTable = nullptr) const
Take a set of marker positions and validates them against a requested start position, updating them as desired.
References Position.
WaitForAsyncTasks()
bool UAnimSequence::WaitForAsyncTasks (float TimeLimitSeconds) protected
WaitOnExistingCompression()
void UAnimSequence::WaitOnExistingCompression (const bool bWantResults = true)
WillNeverCacheCookedPlatformDataAgain()
virtual void UAnimSequence::WillNeverCacheCookedPlatformDataAgain () override virtual
Friends And Related Symbol Documentation
FAnimBankBuildAsyncCacheTask
friend class FAnimBankBuildAsyncCacheTask friend
Definition at line 980 of file AnimSequence.h.
References FAnimBankBuildAsyncCacheTask.
Referenced by FAnimBankBuildAsyncCacheTask.
FAnimCurveBufferAccess
friend struct FAnimCurveBufferAccess friend
Definition at line 981 of file AnimSequence.h.
References FAnimCurveBufferAccess.
Referenced by FAnimCurveBufferAccess.
FAnimDataControllerTestBase
friend class FAnimDataControllerTestBase friend
Definition at line 974 of file AnimSequence.h.
References FAnimDataControllerTestBase.
Referenced by FAnimDataControllerTestBase.
FAnimSequenceDetails
friend class FAnimSequenceDetails friend
Definition at line 977 of file AnimSequence.h.
References FAnimSequenceDetails.
Referenced by FAnimSequenceDetails.
FAnimSequenceDeterminismHelper
friend class FAnimSequenceDeterminismHelper friend
Definition at line 971 of file AnimSequence.h.
References FAnimSequenceDeterminismHelper.
Referenced by FAnimSequenceDeterminismHelper.
FAnimSequenceTestBase
friend class FAnimSequenceTestBase friend
Definition at line 972 of file AnimSequence.h.
References FAnimSequenceTestBase.
Referenced by FAnimSequenceTestBase.
FCompressedAnimationDataNodeBuilder
friend class FCompressedAnimationDataNodeBuilder friend
Definition at line 978 of file AnimSequence.h.
References FCompressedAnimationDataNodeBuilder.
Referenced by FCompressedAnimationDataNodeBuilder.
FCustomAttributeCustomization
friend class FCustomAttributeCustomization friend
Definition at line 970 of file AnimSequence.h.
References FCustomAttributeCustomization.
Referenced by FCustomAttributeCustomization.
FScopedAnimSequenceRawDataCache
friend struct FScopedAnimSequenceRawDataCache friend
Definition at line 967 of file AnimSequence.h.
References FScopedAnimSequenceRawDataCache.
Referenced by FScopedAnimSequenceRawDataCache.
UAnimationAsset
friend class UAnimationAsset friend
Definition at line 966 of file AnimSequence.h.
References UAnimationAsset.
Referenced by UAnimationAsset.
UAnimationBlueprintLibrary
friend class UAnimationBlueprintLibrary friend
Definition at line 968 of file AnimSequence.h.
References UAnimationBlueprintLibrary.
Referenced by UAnimationBlueprintLibrary.
UAnimBank
friend class UAnimBank friend
Definition at line 979 of file AnimSequence.h.
References UAnimBank.
Referenced by UAnimBank.
UAnimBoneCompressionSettings
friend class UAnimBoneCompressionSettings friend
Definition at line 969 of file AnimSequence.h.
References UAnimBoneCompressionSettings.
Referenced by UAnimBoneCompressionSettings.
UE::Anim::Compression::FScopedCompressionGuard
friend struct UE::Anim::Compression::FScopedCompressionGuard friend
Definition at line 973 of file AnimSequence.h.
UE::Anim::FAnimationSequenceAsyncCacheTask
friend class UE::Anim::FAnimationSequenceAsyncCacheTask friend
Definition at line 982 of file AnimSequence.h.
UE::Anim::FAnimSequenceCompilingManager
friend class UE::Anim::FAnimSequenceCompilingManager friend
Definition at line 975 of file AnimSequence.h.
Field Documentation
AttributeCurves
FAttributeCurve UAnimSequence::AttributeCurves protected
Definition at line 799 of file AnimSequence.h.
BoneIndex
FSkeletonPoseBoneIndex UAnimSequence::BoneIndex
Definition at line 522 of file AnimSequence.h.
Referenced by GetBoneTransform_Lockless(), and RetargetBoneTransform().
bShouldClearCompressedData
TAtomic<bool> UAnimSequence::bShouldClearCompressedData = false protected
Definition at line 818 of file AnimSequence.h.
bUseRawData
FSkeletonPoseBoneIndex double bool UAnimSequence::bUseRawData
Definition at line 522 of file AnimSequence.h.
Referenced by EvaluateAttributes().
CacheTasksByKeyHash
TMap<FIoHash, TPimplPtr<UE::Anim::FAnimationSequenceAsyncCacheTask> > UAnimSequence::CacheTasksByKeyHash protected
Definition at line 811 of file AnimSequence.h.
const
FSkeletonPoseBoneIndex FAnimSequenceDecompressionContext bool bUseRawData UAnimSequence::const
Definition at line 543 of file AnimSequence.h.
Referenced by EvaluateAttributes(), GetTargetSamplingFrameRate(), IsValidAdditive(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UFUNCTION().
CurrentPlatformData
FCompressedAnimSequence* UAnimSequence::CurrentPlatformData = nullptr mutable protected
Definition at line 809 of file AnimSequence.h.
DataByPlatformKeyHash
TMap<FIoHash, TUniquePtr<FCompressedAnimSequence> > UAnimSequence::DataByPlatformKeyHash protected
Definition at line 810 of file AnimSequence.h.
DecompContext
FSkeletonPoseBoneIndex FAnimSequenceDecompressionContext& UAnimSequence::DecompContext
Definition at line 543 of file AnimSequence.h.
DeltaTime
float UAnimSequence::DeltaTime
Definition at line 419 of file AnimSequence.h.
final [1/3]
float bool bAllowLooping const override UAnimSequence::final { PRAGMA_DISABLE_DEPRECATION_WARNINGS return UAnimSequenceBase::ExtractRootMotion(StartTime, DeltaTime, bAllowLooping)
Definition at line 419 of file AnimSequence.h.
final [2/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS float EndTrackPosition const override UAnimSequence::final { PRAGMA_DISABLE_DEPRECATION_WARNINGS return UAnimSequenceBase::ExtractRootMotionFromRange(StartTrackPosition, EndTrackPosition)
Definition at line 421 of file AnimSequence.h.
final [3/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS const FBoneContainer* RequiredBones const override UAnimSequence::final { PRAGMA_DISABLE_DEPRECATION_WARNINGS return UAnimSequenceBase::ExtractRootTrackTransform(Time, RequiredBones)
Definition at line 423 of file AnimSequence.h.
HashCacheLock
FRWLock UAnimSequence::HashCacheLock mutable protected
Definition at line 816 of file AnimSequence.h.
InterpolationOverride
FSkeletonPoseBoneIndex double bool TOptional<EAnimInterpolationType> UAnimSequence::InterpolationOverride
Initial value:
=TOptional<EAnimInterpolationType>()) const { FAnimExtractContext ExtractionContext(Time); ExtractionContext.InterpolationOverride = InterpolationOverride; return GetBoneTransform(OutAtom, BoneIndex, ExtractionContext, bUseRawData); }
    1 void GetBoneTransform(FTransform& OutAtom, FSkeletonPoseBoneIndex BoneIndex, const FAnimExtractContext& ExtractionContext, bool bUseRawData) const
Definition at line 522 of file AnimSequence.h.
PlatformHashToKeyHash
TMap<uint32, FIoHash> UAnimSequence::PlatformHashToKeyHash mutable protected
Definition at line 815 of file AnimSequence.h.
PlatformHashToReferencers
TMultiMap<FIoHash, uint32> UAnimSequence::PlatformHashToReferencers protected
Definition at line 822 of file AnimSequence.h.
ResidencyLock
FRWLock UAnimSequence::ResidencyLock mutable protected
Definition at line 824 of file AnimSequence.h.
ResidencyReferencerHashes
TMultiMap<uint32, FIoHash> UAnimSequence::ResidencyReferencerHashes protected
Definition at line 821 of file AnimSequence.h.
SharedCompressedDataMutex
UE::FSharedRecursiveMutex UAnimSequence::SharedCompressedDataMutex mutable protected
Definition at line 812 of file AnimSequence.h.
Referenced by UAnimSequence::FCompressedAnimationDataReadScope::FCompressedAnimationDataReadScope(), UAnimSequence::FCompressedAnimationDataWriteScope::FCompressedAnimationDataWriteScope(), and UAnimSequence::FScopedCompressedAnimSequence::FScopedCompressedAnimSequence().
Time
FSkeletonPoseBoneIndex double UAnimSequence::Time
Definition at line 522 of file AnimSequence.h.
Referenced by AddKeyToSequence().
UniqueMarkerNames
TArray<FName> UAnimSequence::UniqueMarkerNames
List of Unique marker names in this animation sequence.
Definition at line 750 of file AnimSequence.h.
Referenced by GetUniqueMarkerNames().
The documentation for this class was generated from the following file:
AnimSequence.h