Unreal Engine 5.6 C++ API: FCbFieldType Class Reference
FCbFieldType Class Reference
Functions that operate on ECbFieldType.
#include "CompactBinary.h"
Static Public Member Functions
static constexpr ECbFieldType GetSerializedType (ECbFieldType Type)
The type with transient flags removed.
static constexpr ECbFieldType GetType (ECbFieldType Type)
The type with flags removed.
static constexpr bool HasFieldName (ECbFieldType Type)
static constexpr bool HasFields (ECbFieldType Type)
static constexpr bool HasFieldType (ECbFieldType Type)
static constexpr bool HasUniformFields (ECbFieldType Type)
static constexpr bool IsArray (ECbFieldType Type)
static constexpr bool IsAttachment (ECbFieldType Type)
static constexpr bool IsBinary (ECbFieldType Type)
static constexpr bool IsBinaryAttachment (ECbFieldType Type)
static constexpr bool IsBool (ECbFieldType Type)
static constexpr bool IsCustomById (ECbFieldType Type)
static constexpr bool IsCustomByName (ECbFieldType Type)
static constexpr bool IsDateTime (ECbFieldType Type)
static constexpr bool IsFloat (ECbFieldType Type)
Whether the field is a float, or integer due to implicit conversion.
static constexpr bool IsHash (ECbFieldType Type)
static constexpr bool IsInteger (ECbFieldType Type)
static constexpr bool IsNone (ECbFieldType Type)
static constexpr bool IsNull (ECbFieldType Type)
static constexpr bool IsObject (ECbFieldType Type)
static constexpr bool IsObjectAttachment (ECbFieldType Type)
static constexpr bool IsObjectId (ECbFieldType Type)
static constexpr bool IsString (ECbFieldType Type)
static constexpr bool IsTimeSpan (ECbFieldType Type)
static constexpr bool IsUuid (ECbFieldType Type)
static constexpr bool MayContainAttachments (ECbFieldType Type)
Whether the type is or may contain fields of any attachment type.
Static Private Member Functions
static void StaticAssertTypeConstants ()
Static Private Attributes
static constexpr ECbFieldType ArrayBase = ECbFieldType(0b0000'0100)
static constexpr ECbFieldType ArrayMask = ECbFieldType(0b0001'1110)
static constexpr ECbFieldType AttachmentBase = ECbFieldType(0b0000'1110)
static constexpr ECbFieldType AttachmentMask = ECbFieldType(0b0001'1110)
static constexpr ECbFieldType BoolBase = ECbFieldType(0b0000'1100)
static constexpr ECbFieldType BoolMask = ECbFieldType(0b0001'1110)
static constexpr ECbFieldType FloatBase = ECbFieldType(0b0000'1000)
static constexpr ECbFieldType FloatMask = ECbFieldType(0b0001'1100)
static constexpr ECbFieldType IntegerBase = ECbFieldType(0b0000'1000)
static constexpr ECbFieldType IntegerMask = ECbFieldType(0b0001'1110)
static constexpr ECbFieldType ObjectBase = ECbFieldType(0b0000'0010)
static constexpr ECbFieldType ObjectMask = ECbFieldType(0b0001'1110)
static constexpr ECbFieldType SerializedTypeMask = ECbFieldType(0b1001'1111)
static constexpr ECbFieldType TypeMask = ECbFieldType(0b0001'1111)
Detailed Description
Functions that operate on ECbFieldType.
Definition at line 239 of file CompactBinary.h.
Member Function Documentation
GetSerializedType()
constexpr ECbFieldType FCbFieldType::GetSerializedType (ECbFieldType Type) inline static constexpr
The type with transient flags removed.
Definition at line 268 of file CompactBinary.h.
References SerializedTypeMask.
GetType()
constexpr ECbFieldType FCbFieldType::GetType (ECbFieldType Type) inline static constexpr
The type with flags removed.
Definition at line 266 of file CompactBinary.h.
References TypeMask.
Referenced by FCbFieldView::GetType(), FCbFieldView::GetValue(), HasFields(), HasUniformFields(), IsBinary(), IsBinaryAttachment(), IsCustomById(), IsCustomByName(), IsDateTime(), IsHash(), IsNone(), IsNull(), IsObjectAttachment(), IsObjectId(), IsString(), IsTimeSpan(), and IsUuid().
HasFieldName()
constexpr bool FCbFieldType::HasFieldName (ECbFieldType Type) inline static constexpr
Definition at line 271 of file CompactBinary.h.
References EnumHasAnyFlags(), and HasFieldName.
Referenced by FCbFieldView::HasName().
HasFields()
constexpr bool FCbFieldType::HasFields (ECbFieldType Type) inline static constexpr
Definition at line 302 of file CompactBinary.h.
References GetType(), Object, and UniformArray.
HasFieldType()
constexpr bool FCbFieldType::HasFieldType (ECbFieldType Type) inline static constexpr
Definition at line 270 of file CompactBinary.h.
References EnumHasAnyFlags(), and HasFieldType.
Referenced by FCbFieldView::TryGetView().
HasUniformFields()
constexpr bool FCbFieldType::HasUniformFields (ECbFieldType Type) inline static constexpr
Definition at line 307 of file CompactBinary.h.
References GetType(), UniformArray, and UniformObject.
IsArray()
constexpr bool FCbFieldType::IsArray (ECbFieldType Type) inline static constexpr
Definition at line 277 of file CompactBinary.h.
References ArrayBase, and ArrayMask.
Referenced by FCbFieldView::IsArray(), and MayContainAttachments().
IsAttachment()
constexpr bool FCbFieldType::IsAttachment (ECbFieldType Type) inline static constexpr
Definition at line 289 of file CompactBinary.h.
References AttachmentBase, and AttachmentMask.
Referenced by FCbFieldView::IsAttachment(), IsHash(), and MayContainAttachments().
IsBinary()
constexpr bool FCbFieldType::IsBinary (ECbFieldType Type) inline static constexpr
Definition at line 279 of file CompactBinary.h.
References Binary, and GetType().
Referenced by FCbFieldView::IsBinary().
IsBinaryAttachment()
constexpr bool FCbFieldType::IsBinaryAttachment (ECbFieldType Type) inline static constexpr
Definition at line 288 of file CompactBinary.h.
References BinaryAttachment, and GetType().
Referenced by FCbFieldView::IsBinaryAttachment().
IsBool()
constexpr bool FCbFieldType::IsBool (ECbFieldType Type) inline static constexpr
Definition at line 285 of file CompactBinary.h.
References BoolBase, and BoolMask.
Referenced by FCbFieldView::IsBool().
IsCustomById()
constexpr bool FCbFieldType::IsCustomById (ECbFieldType Type) inline static constexpr
Definition at line 299 of file CompactBinary.h.
References CustomById, and GetType().
Referenced by FCbFieldView::IsCustomById().
IsCustomByName()
constexpr bool FCbFieldType::IsCustomByName (ECbFieldType Type) inline static constexpr
Definition at line 300 of file CompactBinary.h.
References CustomByName, and GetType().
Referenced by FCbFieldView::IsCustomByName().
IsDateTime()
constexpr bool FCbFieldType::IsDateTime (ECbFieldType Type) inline static constexpr
Definition at line 294 of file CompactBinary.h.
References DateTime, and GetType().
Referenced by FCbFieldView::IsDateTime().
IsFloat()
constexpr bool FCbFieldType::IsFloat (ECbFieldType Type) inline static constexpr
Whether the field is a float, or integer due to implicit conversion.
Definition at line 284 of file CompactBinary.h.
References FloatBase, and FloatMask.
Referenced by FCbFieldView::IsFloat().
IsHash()
constexpr bool FCbFieldType::IsHash (ECbFieldType Type) inline static constexpr
Definition at line 291 of file CompactBinary.h.
References GetType(), Hash, and IsAttachment().
Referenced by FCbFieldView::IsHash().
IsInteger()
constexpr bool FCbFieldType::IsInteger (ECbFieldType Type) inline static constexpr
Definition at line 282 of file CompactBinary.h.
References IntegerBase, and IntegerMask.
Referenced by FCbFieldView::IsInteger().
IsNone()
constexpr bool FCbFieldType::IsNone (ECbFieldType Type) inline static constexpr
Definition at line 273 of file CompactBinary.h.
References GetType(), and None.
Referenced by FCbFieldView::HasValue().
IsNull()
constexpr bool FCbFieldType::IsNull (ECbFieldType Type) inline static constexpr
Definition at line 274 of file CompactBinary.h.
References GetType(), and Null.
Referenced by FCbFieldView::IsNull().
IsObject()
constexpr bool FCbFieldType::IsObject (ECbFieldType Type) inline static constexpr
Definition at line 276 of file CompactBinary.h.
References ObjectBase, and ObjectMask.
Referenced by FCbFieldView::IsObject(), and MayContainAttachments().
IsObjectAttachment()
constexpr bool FCbFieldType::IsObjectAttachment (ECbFieldType Type) inline static constexpr
Definition at line 287 of file CompactBinary.h.
References GetType(), and ObjectAttachment.
Referenced by FCbFieldView::IsObjectAttachment().
IsObjectId()
constexpr bool FCbFieldType::IsObjectId (ECbFieldType Type) inline static constexpr
Definition at line 297 of file CompactBinary.h.
References GetType(), and ObjectId.
Referenced by FCbFieldView::IsObjectId().
IsString()
constexpr bool FCbFieldType::IsString (ECbFieldType Type) inline static constexpr
Definition at line 280 of file CompactBinary.h.
References GetType(), and String.
Referenced by FCbFieldView::IsString().
IsTimeSpan()
constexpr bool FCbFieldType::IsTimeSpan (ECbFieldType Type) inline static constexpr
Definition at line 295 of file CompactBinary.h.
References GetType(), and TimeSpan.
Referenced by FCbFieldView::IsTimeSpan().
IsUuid()
constexpr bool FCbFieldType::IsUuid (ECbFieldType Type) inline static constexpr
Definition at line 292 of file CompactBinary.h.
References GetType(), and Uuid.
Referenced by FCbFieldView::IsUuid().
MayContainAttachments()
constexpr bool FCbFieldType::MayContainAttachments (ECbFieldType Type) inline static constexpr
Whether the type is or may contain fields of any attachment type.
Definition at line 313 of file CompactBinary.h.
References IsArray(), IsAttachment(), and IsObject().
StaticAssertTypeConstants()
void FCbFieldType::StaticAssertTypeConstants () static private
Field Documentation
ArrayBase
ECbFieldType FCbFieldType::ArrayBase = ECbFieldType(0b0000'0100) static constexpr private
Definition at line 248 of file CompactBinary.h.
Referenced by IsArray().
ArrayMask
ECbFieldType FCbFieldType::ArrayMask = ECbFieldType(0b0001'1110) static constexpr private
Definition at line 247 of file CompactBinary.h.
Referenced by IsArray().
AttachmentBase
ECbFieldType FCbFieldType::AttachmentBase = ECbFieldType(0b0000'1110) static constexpr private
Definition at line 260 of file CompactBinary.h.
Referenced by IsAttachment().
AttachmentMask
ECbFieldType FCbFieldType::AttachmentMask = ECbFieldType(0b0001'1110) static constexpr private
Definition at line 259 of file CompactBinary.h.
Referenced by IsAttachment().
BoolBase
ECbFieldType FCbFieldType::BoolBase = ECbFieldType(0b0000'1100) static constexpr private
Definition at line 257 of file CompactBinary.h.
Referenced by IsBool().
BoolMask
ECbFieldType FCbFieldType::BoolMask = ECbFieldType(0b0001'1110) static constexpr private
Definition at line 256 of file CompactBinary.h.
Referenced by IsBool().
FloatBase
ECbFieldType FCbFieldType::FloatBase = ECbFieldType(0b0000'1000) static constexpr private
Definition at line 254 of file CompactBinary.h.
Referenced by IsFloat().
FloatMask
ECbFieldType FCbFieldType::FloatMask = ECbFieldType(0b0001'1100) static constexpr private
Definition at line 253 of file CompactBinary.h.
Referenced by IsFloat().
IntegerBase
ECbFieldType FCbFieldType::IntegerBase = ECbFieldType(0b0000'1000) static constexpr private
Definition at line 251 of file CompactBinary.h.
Referenced by IsInteger().
IntegerMask
ECbFieldType FCbFieldType::IntegerMask = ECbFieldType(0b0001'1110) static constexpr private
Definition at line 250 of file CompactBinary.h.
Referenced by IsInteger().
ObjectBase
ECbFieldType FCbFieldType::ObjectBase = ECbFieldType(0b0000'0010) static constexpr private
Definition at line 245 of file CompactBinary.h.
Referenced by IsObject().
ObjectMask
ECbFieldType FCbFieldType::ObjectMask = ECbFieldType(0b0001'1110) static constexpr private
Definition at line 244 of file CompactBinary.h.
Referenced by IsObject().
SerializedTypeMask
ECbFieldType FCbFieldType::SerializedTypeMask = ECbFieldType(0b1001'1111) static constexpr private
Definition at line 241 of file CompactBinary.h.
Referenced by GetSerializedType().
TypeMask
ECbFieldType FCbFieldType::TypeMask = ECbFieldType(0b0001'1111) static constexpr private
Definition at line 242 of file CompactBinary.h.
Referenced by GetType().
The documentation for this class was generated from the following file:
CompactBinary.h