Unreal Engine 5.6 C++ API: FInstanceUpdateChangeSet Class Reference
FInstanceUpdateChangeSet Class Reference
Collects changed instance data (and what else is needed to update the instance data proxy) from the source and.
#include "InstanceUpdateChangeSet.h"
Public Member Functions
FInstanceUpdateChangeSet (bool bInNeedFullUpdate, FInstanceAttributeTracker &&InInstanceAttributeTracker, int32 InNumSourceInstances)
Cosntruct a delta change set, but which can be forced to full using bInNeedFullUpdate.
FInstanceUpdateChangeSet (int32 InNumSourceInstances, FInstanceDataFlags InFlags)
Cosntruct a full change set, with no delta (which will collect all enabled data).
auto GetCustomDataReader ()
auto GetCustomDataSetup ()
auto GetCustomDataWriter ()
template<FInstanceAttributeTracker::EFlag Flag>
FInstanceAttributeTracker::FDeltaRange< Flag > GetDelta (bool bForceEmpty, bool bForceFull=false) const
auto GetEditorDataReader ()
FInstanceAttributeTracker::FDeltaRange< FInstanceAttributeTracker::EFlag::IndexChanged > GetIndexChangedDelta () const
auto GetLightShadowUVBiasReader ()
auto GetLocalBoundsReader ()
auto GetLocalBoundsSetup ()
auto GetLocalBoundsWriter ()
auto GetPrevTransformReader ()
auto GetPrevTransformSetup ()
auto GetPrevTransformWriter ()
template<FInstanceAttributeTracker::EFlag DeltaFlag, typename ElementType>
TDeltaSetup< ElementType, FInstanceAttributeTracker::FDeltaRange< DeltaFlag > > GetSetup (bool bEnabledFlag, bool bForceFullFlag, TArray< ElementType > &DataArray, int32 ElementStride=1)
template<typename ElementType>
TDeltaSetup< ElementType, FIdentityDeltaRange > GetSetup (bool bEnabledFlag, TArray< ElementType > &DataArray, int32 ElementStride=1)
auto GetSkinningDataReader ()
auto GetSkinningDataSetup ()
auto GetSkinningDataWriter ()
FInstanceAttributeTracker::FDeltaRange< FInstanceAttributeTracker::EFlag::TransformChanged > GetTransformDelta () const
auto GetTransformReader ()
auto GetTransformSetup ()
auto GetTransformWriter ()
bool IsFullUpdate () const
void SetEditorData (const TArray< TRefCountPtr< HHitProxy > > &HitProxies, const TBitArray<> &SelectedInstances)
void SetSharedLocalBounds (const FRenderBounds &Bounds)
Used to set a single, shared, instance local bounds, only allowed when Flags.bHasPerInstanceLocalBounds is false.
Data Fields
float AbsMaxDisplacement = 0.0f
bool bIdentityIdMap = false
bool bNeedFullUpdate = false
bool bUpdateAllInstanceTransforms = false
FInstanceDataFlags Flags
Flags that dictate what attributes will be gathered from the source (and deposited at the destination).
FInstanceDataFlags ForceFullFlags
Flags that can be set to force individual attributes to use a full update has effect IFF Flags is set for the given attribute.
TFunction< void(TArray< float > &InstanceRandomIDs)> GeneratePerInstanceRandomIds
TPimplPtr< FOpaqueHitProxyContainer > HitProxyContainer
TArray< FPrimitiveInstanceId > IndexToIdMapDeltaData
FInstanceAttributeTracker InstanceAttributeTracker
TArray< uint32 > InstanceEditorData
TArray< FVector4f > InstanceLightShadowUVBias
TArray< FRenderBounds > InstanceLocalBounds
TArray< uint32 > InstanceSkinningData
int32 MaxInstanceId = 0
int32 NumCustomDataFloats = 0
int32 NumSourceInstances = 0
TArray< float > PerInstanceCustomData
FPrecomputedInstanceSpatialHashDataPtr PrecomputedOptimizationData
Describes precomputed spatial hashes and the instance reordering that is needed to use these.
TOptional< FRenderTransform > PreviousPrimitiveToRelativeWorld
TArray< FRenderTransform > PrevTransforms
FRenderTransform PrimitiveToRelativeWorld
FVector PrimitiveWorldSpaceOffset
TBitArray SelectedInstances
TArray< FRenderTransform > Transforms
Detailed Description
Collects changed instance data (and what else is needed to update the instance data proxy) from the source and.
Definition at line 261 of file InstanceUpdateChangeSet.h.
Constructor & Destructor Documentation
FInstanceUpdateChangeSet() [1/2]
FInstanceUpdateChangeSet::FInstanceUpdateChangeSet (int32 InNumSourceInstances, FInstanceDataFlags InFlags) inline
Cosntruct a full change set, with no delta (which will collect all enabled data).
Definition at line 267 of file InstanceUpdateChangeSet.h.
References bNeedFullUpdate, Flags, and NumSourceInstances.
FInstanceUpdateChangeSet() [2/2]
FInstanceUpdateChangeSet::FInstanceUpdateChangeSet (bool bInNeedFullUpdate, FInstanceAttributeTracker && InInstanceAttributeTracker, int32 InNumSourceInstances) inline
Cosntruct a delta change set, but which can be forced to full using bInNeedFullUpdate.
Definition at line 277 of file InstanceUpdateChangeSet.h.
References bNeedFullUpdate, InstanceAttributeTracker, MoveTemp(), and NumSourceInstances.
Member Function Documentation
GetCustomDataReader()
auto FInstanceUpdateChangeSet::GetCustomDataReader () inline
Definition at line 336 of file InstanceUpdateChangeSet.h.
References GetCustomDataSetup().
GetCustomDataSetup()
auto FInstanceUpdateChangeSet::GetCustomDataSetup () inline
Definition at line 322 of file InstanceUpdateChangeSet.h.
References Flags, ForceFullFlags, GetSetup(), NumCustomDataFloats, and PerInstanceCustomData.
Referenced by GetCustomDataReader(), and GetCustomDataWriter().
GetCustomDataWriter()
auto FInstanceUpdateChangeSet::GetCustomDataWriter () inline
Definition at line 330 of file InstanceUpdateChangeSet.h.
References GetCustomDataSetup().
GetDelta()
template<FInstanceAttributeTracker::EFlag Flag> FInstanceAttributeTracker::FDeltaRange< Flag > FInstanceUpdateChangeSet::GetDelta (bool bForceEmpty, bool bForceFull = false) const inline
Definition at line 285 of file InstanceUpdateChangeSet.h.
References InstanceAttributeTracker, IsFullUpdate(), and NumSourceInstances.
Referenced by FISMInstanceUpdateChangeSet::GetCustomDataDelta(), GetIndexChangedDelta(), GetSetup(), and GetTransformDelta().
GetEditorDataReader()
auto FInstanceUpdateChangeSet::GetEditorDataReader () inline
Definition at line 343 of file InstanceUpdateChangeSet.h.
References Flags, GetSetup(), and InstanceEditorData.
GetIndexChangedDelta()
FInstanceAttributeTracker::FDeltaRange< FInstanceAttributeTracker::EFlag::IndexChanged > FInstanceUpdateChangeSet::GetIndexChangedDelta () const inline
Definition at line 299 of file InstanceUpdateChangeSet.h.
References GetDelta().
GetLightShadowUVBiasReader()
auto FInstanceUpdateChangeSet::GetLightShadowUVBiasReader () inline
Definition at line 340 of file InstanceUpdateChangeSet.h.
References Flags, GetSetup(), and InstanceLightShadowUVBias.
GetLocalBoundsReader()
auto FInstanceUpdateChangeSet::GetLocalBoundsReader () inline
Definition at line 337 of file InstanceUpdateChangeSet.h.
References GetLocalBoundsSetup().
GetLocalBoundsSetup()
auto FInstanceUpdateChangeSet::GetLocalBoundsSetup () inline
Definition at line 324 of file InstanceUpdateChangeSet.h.
References Flags, GetSetup(), and InstanceLocalBounds.
Referenced by GetLocalBoundsReader(), and GetLocalBoundsWriter().
GetLocalBoundsWriter()
auto FInstanceUpdateChangeSet::GetLocalBoundsWriter () inline
Definition at line 331 of file InstanceUpdateChangeSet.h.
References GetLocalBoundsSetup().
GetPrevTransformReader()
auto FInstanceUpdateChangeSet::GetPrevTransformReader () inline
Definition at line 335 of file InstanceUpdateChangeSet.h.
References GetPrevTransformSetup().
GetPrevTransformSetup()
auto FInstanceUpdateChangeSet::GetPrevTransformSetup () inline
Definition at line 321 of file InstanceUpdateChangeSet.h.
References Flags, ForceFullFlags, GetSetup(), and PrevTransforms.
Referenced by GetPrevTransformReader(), and GetPrevTransformWriter().
GetPrevTransformWriter()
auto FInstanceUpdateChangeSet::GetPrevTransformWriter () inline
Definition at line 329 of file InstanceUpdateChangeSet.h.
References GetPrevTransformSetup().
GetSetup() [1/2]
template<FInstanceAttributeTracker::EFlag DeltaFlag, typename ElementType> TDeltaSetup< ElementType, FInstanceAttributeTracker::FDeltaRange< DeltaFlag > > FInstanceUpdateChangeSet::GetSetup (bool bEnabledFlag, bool bForceFullFlag, TArray< ElementType > & DataArray, int32 ElementStride = 1) inline
Definition at line 305 of file InstanceUpdateChangeSet.h.
References GetDelta(), and NumSourceInstances.
Referenced by GetCustomDataSetup(), GetEditorDataReader(), GetLightShadowUVBiasReader(), GetLocalBoundsSetup(), GetPrevTransformSetup(), GetSkinningDataSetup(), and GetTransformSetup().
GetSetup() [2/2]
template<typename ElementType> TDeltaSetup< ElementType, FIdentityDeltaRange > FInstanceUpdateChangeSet::GetSetup (bool bEnabledFlag, TArray< ElementType > & DataArray, int32 ElementStride = 1) inline
Definition at line 312 of file InstanceUpdateChangeSet.h.
References NumSourceInstances.
GetSkinningDataReader()
auto FInstanceUpdateChangeSet::GetSkinningDataReader () inline
Definition at line 338 of file InstanceUpdateChangeSet.h.
References GetSkinningDataSetup().
GetSkinningDataSetup()
auto FInstanceUpdateChangeSet::GetSkinningDataSetup () inline
Definition at line 325 of file InstanceUpdateChangeSet.h.
References Flags, GetSetup(), and InstanceSkinningData.
Referenced by GetSkinningDataReader(), and GetSkinningDataWriter().
GetSkinningDataWriter()
auto FInstanceUpdateChangeSet::GetSkinningDataWriter () inline
Definition at line 332 of file InstanceUpdateChangeSet.h.
References GetSkinningDataSetup().
GetTransformDelta()
FInstanceAttributeTracker::FDeltaRange< FInstanceAttributeTracker::EFlag::TransformChanged > FInstanceUpdateChangeSet::GetTransformDelta () const inline
Definition at line 294 of file InstanceUpdateChangeSet.h.
References bUpdateAllInstanceTransforms, and GetDelta().
GetTransformReader()
auto FInstanceUpdateChangeSet::GetTransformReader () inline
Definition at line 334 of file InstanceUpdateChangeSet.h.
References GetTransformSetup().
GetTransformSetup()
auto FInstanceUpdateChangeSet::GetTransformSetup () inline
Definition at line 320 of file InstanceUpdateChangeSet.h.
References bUpdateAllInstanceTransforms, GetSetup(), and Transforms.
Referenced by GetTransformReader(), and GetTransformWriter().
GetTransformWriter()
auto FInstanceUpdateChangeSet::GetTransformWriter () inline
Definition at line 328 of file InstanceUpdateChangeSet.h.
References GetTransformSetup().
IsFullUpdate()
bool FInstanceUpdateChangeSet::IsFullUpdate () const inline
Definition at line 353 of file InstanceUpdateChangeSet.h.
References bNeedFullUpdate.
Referenced by GetDelta().
SetEditorData()
void FInstanceUpdateChangeSet::SetEditorData (const TArray< TRefCountPtr< HHitProxy > > & HitProxies, const TBitArray<> & SelectedInstances)
References SelectedInstances.
SetSharedLocalBounds()
void FInstanceUpdateChangeSet::SetSharedLocalBounds (const FRenderBounds & Bounds)
Used to set a single, shared, instance local bounds, only allowed when Flags.bHasPerInstanceLocalBounds is false.
Referenced by FISMInstanceUpdateChangeSet::UE_DEPRECATED().
Field Documentation
AbsMaxDisplacement
float FInstanceUpdateChangeSet::AbsMaxDisplacement = 0.0f
Definition at line 398 of file InstanceUpdateChangeSet.h.
bIdentityIdMap
bool FInstanceUpdateChangeSet::bIdentityIdMap = false
Definition at line 375 of file InstanceUpdateChangeSet.h.
bNeedFullUpdate
bool FInstanceUpdateChangeSet::bNeedFullUpdate = false
Definition at line 359 of file InstanceUpdateChangeSet.h.
Referenced by FInstanceUpdateChangeSet(), FInstanceUpdateChangeSet(), and IsFullUpdate().
bUpdateAllInstanceTransforms
bool FInstanceUpdateChangeSet::bUpdateAllInstanceTransforms = false
Definition at line 374 of file InstanceUpdateChangeSet.h.
Referenced by GetTransformDelta(), and GetTransformSetup().
Flags
FInstanceDataFlags FInstanceUpdateChangeSet::Flags
Flags that dictate what attributes will be gathered from the source (and deposited at the destination).
These must be present during gather (or they should have been disabled earlier). Constructed as the intersection of the flags indicated by the component & what is supported by the proxy(?).
Definition at line 365 of file InstanceUpdateChangeSet.h.
Referenced by FInstanceUpdateChangeSet(), FISMInstanceUpdateChangeSet::GetCustomDataDelta(), GetCustomDataSetup(), GetEditorDataReader(), GetLightShadowUVBiasReader(), GetLocalBoundsSetup(), GetPrevTransformSetup(), and GetSkinningDataSetup().
ForceFullFlags
FInstanceDataFlags FInstanceUpdateChangeSet::ForceFullFlags
Flags that can be set to force individual attributes to use a full update has effect IFF Flags is set for the given attribute.
If an attribute was enabled after not being used (e.g., on a material change, perhaps) a full update must be sent.
Definition at line 371 of file InstanceUpdateChangeSet.h.
Referenced by GetCustomDataSetup(), and GetPrevTransformSetup().
GeneratePerInstanceRandomIds
TFunction<void(TArray<float> &InstanceRandomIDs)> FInstanceUpdateChangeSet::GeneratePerInstanceRandomIds
Definition at line 393 of file InstanceUpdateChangeSet.h.
HitProxyContainer
TPimplPtr<FOpaqueHitProxyContainer> FInstanceUpdateChangeSet::HitProxyContainer
Definition at line 389 of file InstanceUpdateChangeSet.h.
IndexToIdMapDeltaData
TArray<FPrimitiveInstanceId> FInstanceUpdateChangeSet::IndexToIdMapDeltaData
Definition at line 376 of file InstanceUpdateChangeSet.h.
InstanceAttributeTracker
FInstanceAttributeTracker FInstanceUpdateChangeSet::InstanceAttributeTracker
Definition at line 358 of file InstanceUpdateChangeSet.h.
Referenced by FInstanceUpdateChangeSet(), and GetDelta().
InstanceEditorData
TArray<uint32> FInstanceUpdateChangeSet::InstanceEditorData
Definition at line 387 of file InstanceUpdateChangeSet.h.
Referenced by GetEditorDataReader(), and FISMInstanceUpdateChangeSet::GetInstanceEditorDataDelta().
InstanceLightShadowUVBias
TArray<FVector4f> FInstanceUpdateChangeSet::InstanceLightShadowUVBias
Definition at line 383 of file InstanceUpdateChangeSet.h.
Referenced by FISMInstanceUpdateChangeSet::AddInstanceLightShadowUVBias(), FISMInstanceUpdateChangeSet::GetInstanceLightShadowUVBiasDelta(), and GetLightShadowUVBiasReader().
InstanceLocalBounds
TArray<FRenderBounds> FInstanceUpdateChangeSet::InstanceLocalBounds
Definition at line 384 of file InstanceUpdateChangeSet.h.
Referenced by GetLocalBoundsSetup().
InstanceSkinningData
TArray<uint32> FInstanceUpdateChangeSet::InstanceSkinningData
Definition at line 382 of file InstanceUpdateChangeSet.h.
Referenced by GetSkinningDataSetup().
MaxInstanceId
int32 FInstanceUpdateChangeSet::MaxInstanceId = 0
Definition at line 400 of file InstanceUpdateChangeSet.h.
NumCustomDataFloats
int32 FInstanceUpdateChangeSet::NumCustomDataFloats = 0
Definition at line 378 of file InstanceUpdateChangeSet.h.
Referenced by FISMInstanceUpdateChangeSet::GetCustomDataDelta(), and GetCustomDataSetup().
NumSourceInstances
int32 FInstanceUpdateChangeSet::NumSourceInstances = 0
Definition at line 399 of file InstanceUpdateChangeSet.h.
Referenced by FInstanceUpdateChangeSet(), FInstanceUpdateChangeSet(), GetDelta(), GetSetup(), and GetSetup().
PerInstanceCustomData
TArray<float> FInstanceUpdateChangeSet::PerInstanceCustomData
Definition at line 381 of file InstanceUpdateChangeSet.h.
Referenced by GetCustomDataSetup().
PrecomputedOptimizationData
FPrecomputedInstanceSpatialHashDataPtr FInstanceUpdateChangeSet::PrecomputedOptimizationData
Describes precomputed spatial hashes and the instance reordering that is needed to use these.
If set, the update must reorder the data appropriately. Should only ever be used together with a full rebuild.
Definition at line 407 of file InstanceUpdateChangeSet.h.
PreviousPrimitiveToRelativeWorld
TOptional<FRenderTransform> FInstanceUpdateChangeSet::PreviousPrimitiveToRelativeWorld
Definition at line 397 of file InstanceUpdateChangeSet.h.
PrevTransforms
TArray<FRenderTransform> FInstanceUpdateChangeSet::PrevTransforms
Definition at line 380 of file InstanceUpdateChangeSet.h.
Referenced by GetPrevTransformSetup().
PrimitiveToRelativeWorld
FRenderTransform FInstanceUpdateChangeSet::PrimitiveToRelativeWorld
Definition at line 395 of file InstanceUpdateChangeSet.h.
PrimitiveWorldSpaceOffset
FVector FInstanceUpdateChangeSet::PrimitiveWorldSpaceOffset
Definition at line 396 of file InstanceUpdateChangeSet.h.
SelectedInstances
TBitArray FInstanceUpdateChangeSet::SelectedInstances
Definition at line 388 of file InstanceUpdateChangeSet.h.
Referenced by SetEditorData().
Transforms
TArray<FRenderTransform> FInstanceUpdateChangeSet::Transforms
Definition at line 379 of file InstanceUpdateChangeSet.h.
Referenced by GetTransformSetup().
The documentation for this class was generated from the following file:
InstanceUpdateChangeSet.h