Unreal Engine 5.6 C++ API: FRegexMatcher Class Reference
FRegexMatcher Class Reference
Implements a regular expression pattern matcher.
#include "Regex.h"
Public Member Functions
FRegexMatcher (const FRegexMatcher &)=delete
FRegexMatcher (const FRegexPattern &SourcePattern, const FString &Input)
FRegexMatcher (FRegexMatcher &&)=default
FRegexMatcher (FRegexPattern &&SourcePattern, const FString &Input)
bool FindNext ()
int32 GetBeginLimit ()
FString GetCaptureGroup (const int32 Index)
int32 GetCaptureGroupBeginning (const int32 Index)
int32 GetCaptureGroupEnding (const int32 Index)
int32 GetEndLimit ()
int32 GetMatchBeginning ()
int32 GetMatchEnding ()
FRegexMatcher & operator= (const FRegexMatcher &)=delete
FRegexMatcher & operator= (FRegexMatcher &&)=default
void SetLimits (const int32 BeginIndex, const int32 EndIndex)
Private Attributes
TSharedRef< FRegexMatcherImplementation > Implementation
FRegexPattern Pattern
Detailed Description
Implements a regular expression pattern matcher.
Note
DO NOT use this class as a file-level variable as its construction relies on the internationalization system being initialized!
Definition at line 43 of file Regex.h.
Constructor & Destructor Documentation
FRegexMatcher() [1/4]
FRegexMatcher::FRegexMatcher (const FRegexPattern & SourcePattern, const FString & Input)
References Input.
Referenced by FRegexMatcher(), FRegexMatcher(), operator=(), and operator=().
FRegexMatcher() [2/4]
FRegexMatcher::FRegexMatcher (FRegexPattern && SourcePattern, const FString & Input)
References Input.
FRegexMatcher() [3/4]
FRegexMatcher::FRegexMatcher (const FRegexMatcher &) delete
References FRegexMatcher().
FRegexMatcher() [4/4]
FRegexMatcher::FRegexMatcher (FRegexMatcher &&) default
References FRegexMatcher().
Member Function Documentation
FindNext()
bool FRegexMatcher::FindNext ()
Referenced by FDriverConfigEntryConstraints::AreConstraintsSatisfied().
GetBeginLimit()
int32 FRegexMatcher::GetBeginLimit ()
GetCaptureGroup()
FString FRegexMatcher::GetCaptureGroup (const int32 Index)
GetCaptureGroupBeginning()
int32 FRegexMatcher::GetCaptureGroupBeginning (const int32 Index)
GetCaptureGroupEnding()
int32 FRegexMatcher::GetCaptureGroupEnding (const int32 Index)
GetEndLimit()
int32 FRegexMatcher::GetEndLimit ()
GetMatchBeginning()
int32 FRegexMatcher::GetMatchBeginning ()
GetMatchEnding()
int32 FRegexMatcher::GetMatchEnding ()
operator=() [1/2]
FRegexMatcher & FRegexMatcher::operator= (const FRegexMatcher &) delete
References FRegexMatcher().
operator=() [2/2]
FRegexMatcher & FRegexMatcher::operator= (FRegexMatcher &&) default
References FRegexMatcher().
SetLimits()
void FRegexMatcher::SetLimits (const int32 BeginIndex, const int32 EndIndex)
Field Documentation
Implementation
TSharedRef<FRegexMatcherImplementation> FRegexMatcher::Implementation private
Definition at line 70 of file Regex.h.
Pattern
FRegexPattern FRegexMatcher::Pattern private
Definition at line 69 of file Regex.h.
The documentation for this class was generated from the following file:
Regex.h