Unreal Engine 5.6 C++ API: FExternalDragOperation Class Reference
FExternalDragOperation Class Reference
An external drag and drop operation that originates outside of slate.
#include "DragAndDrop.h"
Public Member Functions
const TArray< FString > & GetFiles () const
const FString & GetText () const
bool HasFiles () const
bool HasText () const
virtual bool IsOfTypeImpl (const FString &Type) const override
Checks whether this drag and drop operation can cast safely to the specified type.
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const
Gets the widget that will serve as the decorator unless overridden.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static const FString & GetTypeId ()
static TSharedRef< FExternalDragOperation > NewFiles (TArray< FString > InFileNames)
Creates a new external file drag operation.
static TSharedRef< FExternalDragOperation > NewOperation (FString InText, TArray< FString > InFileNames)
Creates a new external combined drag operation.
static TSharedRef< FExternalDragOperation > NewText (FString InText)
Creates a new external text drag operation.
Private Types
enum EExternalDragType { DragText = 1<<0 , DragFiles = 1<<1 }
Private Member Functions
FExternalDragOperation ()
A private constructor to ensure that the appropriate "New" factory method is used below.
virtual bool IsExternalOperation () const override
Is this drag Drop operation going to interact with applications outside of Slate.
Private Attributes
TArray< FString > DraggedFileNames
FString DraggedText
uint8 DragType
Additional Inherited Members
Protected Member Functions inherited from FDragDropOperation
virtual void Construct ()
Constructs the window and widget if applicable.
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Detailed Description
An external drag and drop operation that originates outside of slate.
E.g. an OLE drag and drop.
Definition at line 216 of file DragAndDrop.h.
Member Enumeration Documentation
EExternalDragType
enum FExternalDragOperation::EExternalDragType private
Enumerator
DragText
DragFiles
Definition at line 248 of file DragAndDrop.h.
Constructor & Destructor Documentation
FExternalDragOperation()
FExternalDragOperation::FExternalDragOperation () inline private
A private constructor to ensure that the appropriate "New" factory method is used below.
Definition at line 220 of file DragAndDrop.h.
Referenced by GetTypeId(), NewFiles(), NewOperation(), and NewText().
Member Function Documentation
GetFiles()
const TArray< FString > & FExternalDragOperation::GetFiles () const inline
Returns
the filenames from this drag operation
Definition at line 242 of file DragAndDrop.h.
References DraggedFileNames, ensure, and HasFiles().
GetText()
const FString & FExternalDragOperation::GetText () const inline
Returns
the text from this drag operation
Definition at line 240 of file DragAndDrop.h.
References DraggedText, ensure, and HasText().
GetTypeId()
const FString & FExternalDragOperation::GetTypeId () inline static
Definition at line 225 of file DragAndDrop.h.
References FDragDropOperation::FDragDropOperation(), and FExternalDragOperation().
HasFiles()
bool FExternalDragOperation::HasFiles () const inline
Returns
true if this is a file drag operation
Definition at line 237 of file DragAndDrop.h.
References DragFiles, and DragType.
Referenced by GetFiles().
HasText()
bool FExternalDragOperation::HasText () const inline
Returns
true if this is a text drag operation
Definition at line 235 of file DragAndDrop.h.
References DragText, DragType, and HasText().
Referenced by GetText(), and HasText().
IsExternalOperation()
virtual bool FExternalDragOperation::IsExternalOperation () const inline override private virtual
Is this drag Drop operation going to interact with applications outside of Slate.
Reimplemented from FDragDropOperation.
Definition at line 222 of file DragAndDrop.h.
IsOfTypeImpl()
virtual bool FExternalDragOperation::IsOfTypeImpl (const FString & Type) const inline override virtual
Checks whether this drag and drop operation can cast safely to the specified type.
Reimplemented from FDragDropOperation.
Definition at line 225 of file DragAndDrop.h.
NewFiles()
TSharedRef< FExternalDragOperation > FExternalDragOperation::NewFiles (TArray< FString > InFileNames) static
Creates a new external file drag operation.
References FExternalDragOperation(), and NewFiles().
Referenced by NewFiles().
NewOperation()
TSharedRef< FExternalDragOperation > FExternalDragOperation::NewOperation (FString InText, TArray< FString > InFileNames) static
Creates a new external combined drag operation.
References FExternalDragOperation(), and NewOperation().
Referenced by NewOperation().
NewText()
TSharedRef< FExternalDragOperation > FExternalDragOperation::NewText (FString InText) static
Creates a new external text drag operation.
References FExternalDragOperation(), and NewText().
Referenced by NewText().
Field Documentation
DraggedFileNames
TArray<FString> FExternalDragOperation::DraggedFileNames private
Definition at line 246 of file DragAndDrop.h.
Referenced by GetFiles().
DraggedText
FString FExternalDragOperation::DraggedText private
Definition at line 245 of file DragAndDrop.h.
Referenced by GetText().
DragType
uint8 FExternalDragOperation::DragType private
Definition at line 253 of file DragAndDrop.h.
Referenced by HasFiles(), and HasText().
The documentation for this class was generated from the following file:
DragAndDrop.h