Unreal Engine 5.6 C++ API: UEditorProjectAppearanceSettings Class Reference
UEditorProjectAppearanceSettings Class Reference
#include "EditorProjectSettings.h"
Public Member Functions
GENERATED_BODY () UNREALED_API UEditorProjectAppearanceSettings(const FObjectInitializer &)
UPROPERTY () EDefaultLocationUnit DefaultInputUnits_DEPRECATED
UPROPERTY () EReferenceViewerSettingMode ShowSearchableNames
UPROPERTY () EUnitDisplay UnitDisplay_DEPRECATED
Deprecated properties that didn't live very long.
UPROPERTY ()) bool bDisplayUnits
UPROPERTY ()) bool bDisplayUnitsOnComponentTransforms
UPROPERTY ()) EUnit AccelerationUnits
UPROPERTY ()) EUnit AngleUnits
UPROPERTY ()) EUnit AngularSpeedUnits
UPROPERTY ()) EUnit ForceUnits
UPROPERTY ()) EUnit ImpulseUnits
UPROPERTY ()) EUnit PositionalImpulseUnits
UPROPERTY ()) EUnit SpeedUnits
UPROPERTY ()) EUnit TemperatureUnits
UPROPERTY ()) EUnit TorqueUnits
UPROPERTY ()) int32 ReferenceViewerDefaultMaxSearchBreadth
UPROPERTY ()) TArray< EUnit > DistanceUnits
UPROPERTY ()) TArray< EUnit > MassUnits
UPROPERTY ()) TArray< EUnit > TimeUnits
Protected Member Functions
virtual UNREALED_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
Called when a property on this object is changed.
virtual UNREALED_API void PostInitProperties () override
Detailed Description
Definition at line 58 of file EditorProjectSettings.h.
Member Function Documentation
GENERATED_BODY()
UEditorProjectAppearanceSettings::GENERATED_BODY () const &
PostEditChangeProperty()
virtual UNREALED_API void UEditorProjectAppearanceSettings::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override protected virtual
Called when a property on this object is changed.
References PostEditChangeProperty().
Referenced by PostEditChangeProperty().
PostInitProperties()
virtual UNREALED_API void UEditorProjectAppearanceSettings::PostInitProperties () override protected virtual
References PostInitProperties().
Referenced by PostInitProperties().
UPROPERTY() [1/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References config, and UPROPERTY().
UPROPERTY() [2/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, and UPROPERTY().
UPROPERTY() [3/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
Deprecated properties that didn't live very long.
References config, and UPROPERTY().
UPROPERTY() [4/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [5/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [6/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [7/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [8/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [9/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [10/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [11/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [12/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [13/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [14/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [15/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [16/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [17/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [18/18]
UEditorProjectAppearanceSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
EditorProjectSettings.h