Unreal Engine 5.6 C++ API: FConfigFile Class Reference
FConfigFile Class Reference
#include "ConfigCacheIni.h"
Public Types
using SectionType = FConfigSection
Public Member Functions
FConfigFile ()
FConfigFile (const FConfigFile &Other)
FConfigFile (FConfigFile &&Other)
FConfigFile (int32)
~FConfigFile ()
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
void AddDynamicLayerToHierarchy (const FString &Filename)
Appends a new INI file to the SourceIniHierarchy and combines it with the current contents.
void AddMissingProperties (const FConfigFile &InSourceFile)
Adds any properties that exist in InSourceFile that this config file is missing.
bool AddToSection (const TCHAR *Section, FName Key, const FString &Value)
Adds the given key/value pair to the Section.
bool AddUniqueToSection (const TCHAR *Section, FName Key, const FString &Value)
Adds the given key/value pair to the Section, if the pair didn't already exist This is equivalent to the + operator in .ini files.
FORCEINLINE void Append (TMap< FString, FConfigSection > Other)
bool ApplyFile (const FConfigCommandStream *File)
Apply the contents of the given file (which must have non-Combined ValueTypes stored in it, it is a logic error otherwise and will assert) The values in this file will be Combined type.
FORCEINLINE TRangedForConstIterator begin () const
bool Combine (const FString &Filename)
void CombineFromBuffer (const FString &Buffer, const FString &FileHint)
FORCEINLINE bool Contains (const FString &SectionName) const
bool DoesSectionExist (const TCHAR *Section) const
void Dump (FOutputDevice &Ar)
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
FORCEINLINE TRangedForConstIterator end () const
const FConfigSection * FindOrAddConfigSection (const FString &Name)
FORCEINLINE const FConfigSection * FindSection (const FString &SectionName) const
int32 GetArray (const TCHAR *Section, const TCHAR *Key, TArray< FString > &Value) const
bool GetBool (const TCHAR *Section, const TCHAR *Key, bool &Value) const
bool GetDouble (const TCHAR *Section, const TCHAR *Key, double &Value) const
bool GetFloat (const TCHAR *Section, const TCHAR *Key, float &Value) const
bool GetInt (const TCHAR *Section, const TCHAR *Key, int32 &Value) const
bool GetInt64 (const TCHAR *Section, const TCHAR *Key, int64 &Value) const
FORCEINLINE int32 GetKeys (TArray< FString > &Keys) const
FORCEINLINE int32 GetKeys (TSet< FString > &Keys) const
bool GetString (const TCHAR *Section, const TCHAR *Key, FString &Value) const
bool GetText (const TCHAR *Section, const TCHAR *Key, FText &Value) const
bool GetValue (const TCHAR *Section, const TCHAR *Key, bool &Value) const
bool GetValue (const TCHAR *Section, const TCHAR *Key, double &Value) const
bool GetValue (const TCHAR *Section, const TCHAR *Key, float &Value) const
bool GetValue (const TCHAR *Section, const TCHAR *Key, FString &Value) const
bool GetValue (const TCHAR *Section, const TCHAR *Key, FText &Value) const
bool GetValue (const TCHAR *Section, const TCHAR *Key, int32 &Value) const
bool GetValue (const TCHAR *Section, const TCHAR *Key, int64 &Value) const
int32 GetValue (const TCHAR *Section, const TCHAR *Key, TArray< FString > &Value) const
FORCEINLINE bool IsEmpty () const
FORCEINLINE int32 Num () const
bool operator!= (const FConfigFile &Other) const
FConfigFile & operator= (const FConfigFile &Other)
FConfigFile & operator= (FConfigFile &&Other)
bool operator== (const FConfigFile &Other) const
void ProcessInputFileContents (FStringView Contents, const FString &FileHint)
Process the contents of an .ini file that has been read into an FString.
void ProcessSourceAndCheckAgainstBackup ()
Check the source hierarchy which was loaded without any user changes from the Config/Saved dir.
void Read (const FString &Filename)
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
bool RemoveFromSection (const TCHAR *Section, FName Key, const FString &Value)
Removes every entry in the Section that has the Key/Value pair This is equivalent to the - operator in .ini files (although it will remove all instances of the pair, not just a single one)
bool RemoveKeyFromSection (const TCHAR *Section, FName Key)
Removes every entry in the Section that has Key, no matter what the Value is This is equivalent to the !
FORCEINLINE void Reset ()
bool ResetKeyInSection (const TCHAR *Section, FName Key)
Similar to RemvoeKeyFromSection, but if this File's changes are being tracked, then we remove all changes to the the key that have been tracked.
void SetArray (const TCHAR *Section, const TCHAR *Key, const TArray< FString > &Value)
void SetBool (const TCHAR *Section, const TCHAR *Key, bool Value)
void SetDouble (const TCHAR *Section, const TCHAR *Key, double Value)
void SetFloat (const TCHAR *Section, const TCHAR *Key, float Value)
void SetInt64 (const TCHAR *Section, const TCHAR *Key, const int64 Value)
void SetString (const TCHAR *Section, const TCHAR *Key, const TCHAR *Value)
void SetText (const TCHAR *Section, const TCHAR *Key, const FText &Value)
UE_DEPRECATED (5.4, "Use const ranged for iterators, (wrap your FConfigFile variable in AsConst to force the const iterator). See top of ConfigCacheIni.h for more info.") FORCEINLINE TRangedForIterator begin()
UE_DEPRECATED (5.4, "Use const ranged for iterators, (wrap your FConfigFile variable in AsConst to force the const iterator). See top of ConfigCacheIni.h for more info.") FORCEINLINE TRangedForIterator end()
UE_DEPRECATED (5.4, "Use FindOrAddConfigSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") 1 FConfigSection *FindOrAddSection(const FString &Name)
UE_DEPRECATED (5.4, "Use FindOrAddConfigSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") FORCEINLINE ValueType &FindOrAdd(const FString &Key)
UE_DEPRECATED (5.4, "Use FindSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") FORCEINLINE const FConfigSection *Find(const FString &SectionName) const
UE_DEPRECATED (5.4, "Use FindSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") FORCEINLINE FConfigSection *Find(const FString &SectionName)
void UpdateSections (const TCHAR *DiskFilename, const TCHAR *IniRootName=nullptr, const TCHAR *OverridePlatform=nullptr)
Saves only the sections in this FConfigFile into the given file.
bool UpdateSinglePropertyInSection (const TCHAR *DiskFilename, const TCHAR *PropertyName, const TCHAR *SectionName)
Update a single property in the config file, for the section that is specified.
bool Write (const FString &Filename, bool bDoRemoteWrite=true, const FString &PrefixText=FString())
Write this ConfigFile to the given Filename, constructed the text from the config sections in *this, prepended by the optional PrefixText.
void WriteToString (FString &InOutText, const FString &SimulatedFilename=FString(), const FString &PrefixText=FString())
Write this ConfigFile to the given string, constructed the text from the config sections in *this, prepended by the optional PrefixText.
Static Public Member Functions
static void AppendExportedPropertyLine (FString &Out, const FString &PropertyName, const FString &PropertyValue)
Append a correctly escaped line to add to the config file for the given property.
static FString GenerateExportedPropertyLine (const FString &PropertyName, const FString &PropertyValue)
Generate a correctly escaped line to add to the config file for the given property.
static bool OverrideFileFromCommandline (FString &Filename)
Checks the command line for any overridden config file settings.
static void OverrideFromCommandline (FConfigCommandStream *File, const FString &Filename)
static void OverrideFromCommandline (FConfigFile *File, const FString &Filename)
Checks the command line for any overridden config settings.
static bool ShouldExportQuotedString (const FString &PropertyValue)
Checks if the PropertyValue should be exported in quotes when writing the ini to disk.
static bool WriteTempFileThenMove ()
Whether to write a temp file then move it to it's destination when saving.
Data Fields
bool bCanSaveAllSections: 1
bool bHasPlatformName: 1
bool bPythonConfigParserMode: 1
class FConfigBranch * Branch = nullptr
TArray< FConfigCommandlineOverride > CommandlineOptions
The collection of overrides which stemmed from the commandline.
bool Dirty: 1
FName Name
The name of this config file.
bool NoSave: 1
FString PlatformName
FName Tag
Private Member Functions
void AddStaticLayersToHierarchy (const TCHAR *InBaseIniName, const TCHAR *InPlatformName, const TCHAR *EngineConfigDir, const TCHAR *SourceConfigDir)
Creates a chain of ini filenames to load and combine.
void Cleanup ()
Delete all of the inner ConfigFiles, for destruction or preparing to re-read.
void FillFileFromBuffer (FStringView Buffer, bool bHandleSymbolCommands, const FString &FileHint)
bool FillFileFromDisk (const FString &Filename, bool bHandleSymbolCommands)
FORCEINLINE FConfigSection * FindInternal (const FString &SectionName)
FConfigSection * FindOrAddSectionInternal (const FString &SectionName)
bool IsADefaultIniWrite (const FString &Filename, int32 &OutIniCombineThreshold) const
Determine if writing a default hierarchal ini, and deduce position in the hierarchy.
void ProcessCommand (FConfigSection *Section, FStringView SectionName, FConfigValue::EValueType Command, FName Key, FString &&Value)
void ProcessPropertyAndWriteForDefaults (int32 IniCombineThreshold, const TArray< const FConfigValue * > &InCompletePropertyToProcess, FString &OutText, const FString &SectionName, const FString &PropertyName)
Process the property for Writing to a default file.
void SaveSourceToBackupFile ()
Save the source hierarchy which was loaded out to a backup file so we can check future changes in the base/default configs.
void Shrink ()
bool WriteInternal (const FString &Filename, bool bDoRemoteWrite, TMap< FString, FString > &InOutSectionTexts, const TArray< FString > &InSectionOrder)
Write a ConfigFile to the given Filename, constructed from the given SectionTexts, in the given order, with sections in *this overriding sections in SectionTexts.
void WriteToStringInternal (FString &InOutText, bool bIsADefaultIniWrite, int32 IniCombineThreshold, TMap< FString, FString > &InOutSectionTexts, const TArray< FString > &InSectionOrder)
Write a ConfigFile to InOutText, constructed from the given SectionTexts, in the given order, with sections in *this overriding sections in SectionTexts.
Private Member Functions inherited from TMap< FString, FConfigSection >
TMap ()=default
TMap (const TMap &)=default
TMap (const TMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TMap (FIntrusiveUnsetOptionalState Tag)
TMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Constructor which gets its elements from a native initializer list.
TMap (TMap &&)=default
TMap (TMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
void Append (const TMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &OtherMap)
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
void Append (TMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&OtherMap)
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
FORCEINLINE ValueType FindAndRemoveChecked (KeyConstPointerType Key)
Find a pair with the specified key, removes it from the map, and returns the value part of the pair.
TMap & operator= (const TMap &)=default
TMap & operator= (const TMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TMap & operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Assignment operator which gets its elements from a native initializer list.
TMap & operator= (TMap &&)=default
TMap & operator= (TMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
FORCEINLINE ValueType & operator[] (KeyConstPointerType Key)
FORCEINLINE const ValueType & operator[] (KeyConstPointerType Key) const
FORCEINLINE bool RemoveAndCopyValue (KeyInitType Key, ValueType &OutRemovedValue)
Remove the pair with the specified key and copies the value that was removed to the ref parameter.
FORCEINLINE bool RemoveAndCopyValueByHash (uint32 KeyHash, const ComparableKey &Key, ValueType &OutRemovedValue)
See RemoveAndCopyValue() and class documentation section on ByHash() functions.
Private Member Functions inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
template<typename PREDICATE_CLASS>
FORCEINLINE void KeySort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void KeyStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
void SortFreeList ()
Sort the free element list so that subsequent additions will occur in the lowest available TSet index resulting in tighter packing without moving any existing items.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueSort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
TSortableMapBase ()=default
TSortableMapBase (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TSortableMapBase (FIntrusiveUnsetOptionalState Tag)
TSortableMapBase (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Private Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
FORCEINLINE ValueType & Add (const KeyType &InKey)
Set a default value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (const TTuple< KeyType, ValueType > &InKeyValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (KeyType &&InKey)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (TTuple< KeyType, ValueType > &&InKeyValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, const ValueType &InValue)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, ValueType &&InValue)
TArray< ElementType > Array () const
Copy the key/value pairs in this map into an array.
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TRangedForConstIterator begin () const
FORCEINLINE void Compact ()
Compacts the pair set to remove holes.
FORCEINLINE void CompactStable ()
Compacts the pair set to remove holes.
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Check if map contains the specified key.
template<typename ComparableKey>
FORCEINLINE bool ContainsByHash (uint32 KeyHash, const ComparableKey &Key) const
See Contains() and class documentation section on ByHash() functions.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
FORCEINLINE void CountBytes (FArchive &Ar) const
Track the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (typename TConstKeyIterator::KeyArgumentType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (typename TKeyIterator::KeyArgumentType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
template<typename InitKeyType = KeyType>
ValueType & Emplace (InitKeyType &&InKey)
Set a default value associated with a key.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
template<typename InitKeyType = KeyType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey)
See Emplace() and class documentation section on ByHash() functions.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey, InitValueType &&InValue)
See Emplace() and class documentation section on ByHash() functions.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map.
FORCEINLINE TRangedForIterator end ()
FORCEINLINE TRangedForConstIterator end () const
template<typename Predicate>
TMap< KeyType, ValueType, SetAllocator, KeyFuncs > FilterByPredicate (Predicate Pred) const
Filters the elements in the map based on a predicate functor.
FORCEINLINE ValueType * Find (KeyConstPointerType Key)
Find the value associated with a specified key.
FORCEINLINE const ValueType * Find (KeyConstPointerType Key) const
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
const ElementType * FindArbitraryElement () const
template<typename ComparableKey>
FORCEINLINE ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key)
See Find() and class documentation section on ByHash() functions.
template<typename ComparableKey>
FORCEINLINE const ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key) const
template<typename ComparableKey>
FORCEINLINE ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key)
template<typename ComparableKey>
FORCEINLINE const ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key) const
FORCEINLINE ValueType & FindChecked (KeyConstPointerType Key)
Find a reference to the value associated with a specified key.
FORCEINLINE const ValueType & FindChecked (KeyConstPointerType Key) const
Find a reference to the value associated with a specified key.
FORCEINLINE FSetElementId FindId (KeyInitType Key) const
Finds the index of the first element that is assigned to the specified key.
template<typename ComparableKey>
FORCEINLINE FSetElementId FindIdByHash (uint32 KeyHash, const ComparableKey &Key) const
See FindId() and class documentation section on ByHash() functions.
const KeyType * FindKey (ValueInitType Value) const
Find the key associated with the specified value.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, const ValueType &Value)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, const ValueType &Value)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType FindRef (KeyConstPointerType Key) const
Find the value associated with a specified key.
FORCEINLINE ValueType FindRef (KeyConstPointerType Key, ValueType DefaultValue) const
Find the value associated with a specified key.
template<typename Allocator>
void GenerateKeyArray (TArray< KeyType, Allocator > &OutArray) const
Generate an array from the keys in this map.
template<typename Allocator>
void GenerateValueArray (TArray< ValueType, Allocator > &OutArray) const
Generate an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container .
template<typename Allocator>
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Get the unique keys contained within this map.
template<typename InSetKeyFuncs, typename InSetAllocator>
int32 GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > &OutKeys) const
Get the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
bool OrderIndependentCompareEqual (const TMapBase &Other) const
Compare this map with another for equality.
FORCEINLINE void Remove (FSetElementId Id)
Removes the element at the specified index.
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
template<typename ComparableKey>
FORCEINLINE int32 RemoveByHash (uint32 KeyHash, const ComparableKey &Key)
See Remove() and class documentation section on ByHash() functions.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
TMapBase ()=default
TMapBase (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TMapBase (FIntrusiveUnsetOptionalState Tag)
TMapBase (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TMapBase & operator= (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase & operator= (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TMapBase & operator= (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase & operator= (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Static Private Member Functions
static void AddStaticLayersToHierarchy (FConfigContext &Context)
Static Private Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Private Attributes
FConfigCommandStream * ChangeTracker = nullptr
friend FConfigContext
TMap< FString, TMap< FName, FString > > PerObjectConfigArrayOfStructKeys
Private Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
ElementSetType Pairs
A set of the key-value pairs in the map.
Static Private Attributes
static FTransactionallySafeRWLock ConfigFileMapLock
Static Private Attributes inherited from TMap< FString, FConfigSection >
static constexpr bool bHasIntrusiveUnsetOptionalState
Static Private Attributes inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Static Private Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Friends
class FConfigBranch
class FConfigCacheIni
template<typename FileType>
void FillFileFromBuffer (FileType *File, FStringView Buffer, bool bHandleSymbolCommands, const FString &FileHint)
FArchive & operator<< (FArchive &Ar, FConfigFile &ConfigFile)
Additional Inherited Members
Private Types inherited from TMap< FString, FConfigSection >
using IntrusiveUnsetOptionalStateType
typedef Super::KeyConstPointerType KeyConstPointerType
typedef KeyFuncs KeyFuncsType
typedef Super::KeyInitType KeyInitType
typedef FString KeyType
typedef SetAllocator SetAllocatorType
typedef TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Super
typedef FConfigSection ValueType
Private Types inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
using IntrusiveUnsetOptionalStateType = TSortableMapBase
typedef TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Super
Private Types inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
typedef TPair< KeyType, ValueType > ElementType
typedef TTypeTraits< KeyType >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< KeyType >::ConstInitType KeyInitType
using TRangedForConstIterator = TBaseIterator<true, true>
using TRangedForIterator = TBaseIterator<false, true>
typedef TTypeTraits< ValueType >::ConstInitType ValueInitType
typedef TSet< ElementType, KeyFuncs, SetAllocator > ElementSetType
using IntrusiveUnsetOptionalStateType = TMapBase
Detailed Description
Definition at line 566 of file ConfigCacheIni.h.
Member Typedef Documentation
SectionType
using FConfigFile::SectionType = FConfigSection
Definition at line 569 of file ConfigCacheIni.h.
Constructor & Destructor Documentation
FConfigFile() [1/4]
FConfigFile::FConfigFile ()
Referenced by FConfigFile(), FConfigFile(), AddMissingProperties(), operator!=(), operator<<, operator=(), operator=(), operator==(), and OverrideFromCommandline().
FConfigFile() [2/4]
FConfigFile::FConfigFile (int32) inline
Definition at line 613 of file ConfigCacheIni.h.
~FConfigFile()
FConfigFile::~FConfigFile ()
FConfigFile() [3/4]
FConfigFile::FConfigFile (const FConfigFile & Other)
References FConfigFile(), and Other.
FConfigFile() [4/4]
FConfigFile::FConfigFile (FConfigFile && Other)
References FConfigFile(), and Other.
Member Function Documentation
Add() [1/4]
FORCEINLINE ValueType & FConfigFile::Add (const KeyType & InKey, const ValueType & InValue) inline
Definition at line 689 of file ConfigCacheIni.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), ConfigFileMapLock, and FORCEINLINE.
Add() [2/4]
FORCEINLINE ValueType & FConfigFile::Add (const KeyType & InKey, ValueType && InValue) inline
Definition at line 695 of file ConfigCacheIni.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), ConfigFileMapLock, FORCEINLINE, and MoveTempIfPossible().
Add() [3/4]
FORCEINLINE ValueType & FConfigFile::Add (KeyType && InKey, const ValueType & InValue) inline
Definition at line 701 of file ConfigCacheIni.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), ConfigFileMapLock, FORCEINLINE, and MoveTempIfPossible().
Add() [4/4]
FORCEINLINE ValueType & FConfigFile::Add (KeyType && InKey, ValueType && InValue) inline
Definition at line 707 of file ConfigCacheIni.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), ConfigFileMapLock, FORCEINLINE, and MoveTempIfPossible().
AddDynamicLayerToHierarchy()
void FConfigFile::AddDynamicLayerToHierarchy (const FString & Filename)
Appends a new INI file to the SourceIniHierarchy and combines it with the current contents.
References Filename.
AddMissingProperties()
void FConfigFile::AddMissingProperties (const FConfigFile & InSourceFile)
Adds any properties that exist in InSourceFile that this config file is missing.
References FConfigFile().
AddStaticLayersToHierarchy() [1/2]
void FConfigFile::AddStaticLayersToHierarchy (const TCHAR * InBaseIniName, const TCHAR * InPlatformName, const TCHAR * EngineConfigDir, const TCHAR * SourceConfigDir) private
Creates a chain of ini filenames to load and combine.
Parameters
InBaseIniName Ini name.
InPlatformName Platform name, nullptr means to use the current platform
OutHierarchy An array which is to receive the generated hierachy of ini filenames.
AddStaticLayersToHierarchy() [2/2]
void FConfigFile::AddStaticLayersToHierarchy (FConfigContext & Context) static private
References FConfigContext.
AddToSection()
bool FConfigFile::AddToSection (const TCHAR * Section, FName Key, const FString & Value)
Adds the given key/value pair to the Section.
This will always add this pair to the section, even if the pair already exists. This is equivalent to the . operator in .ini files
Returns
true if the section was modified
References Key, and Value.
AddUniqueToSection()
bool FConfigFile::AddUniqueToSection (const TCHAR * Section, FName Key, const FString & Value)
Adds the given key/value pair to the Section, if the pair didn't already exist This is equivalent to the + operator in .ini files.
Returns
true if the section was modified
References Key, and Value.
Append()
FORCEINLINE void FConfigFile::Append (TMap< FString, FConfigSection > Other) inline
Definition at line 713 of file ConfigCacheIni.h.
References TMap< FString, FConfigSection >::TMap(), TMap< FString, FConfigSection >::Append(), ConfigFileMapLock, FORCEINLINE, MoveTemp(), and Other.
AppendExportedPropertyLine()
void FConfigFile::AppendExportedPropertyLine (FString & Out, const FString & PropertyName, const FString & PropertyValue) static
Append a correctly escaped line to add to the config file for the given property.
References PropertyName.
ApplyFile()
bool FConfigFile::ApplyFile (const FConfigCommandStream * File)
Apply the contents of the given file (which must have non-Combined ValueTypes stored in it, it is a logic error otherwise and will assert) The values in this file will be Combined type.
begin()
FORCEINLINE TRangedForConstIterator FConfigFile::begin () const inline
Definition at line 739 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
Referenced by UE_DEPRECATED().
Cleanup()
void FConfigFile::Cleanup () private
Delete all of the inner ConfigFiles, for destruction or preparing to re-read.
Combine()
bool FConfigFile::Combine (const FString & Filename)
References Filename.
CombineFromBuffer()
void FConfigFile::CombineFromBuffer (const FString & Buffer, const FString & FileHint)
References Buffer.
Contains()
FORCEINLINE bool FConfigFile::Contains (const FString & SectionName) const inline
Definition at line 665 of file ConfigCacheIni.h.
References ConfigFileMapLock, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Contains(), and FORCEINLINE.
DoesSectionExist()
bool FConfigFile::DoesSectionExist (const TCHAR * Section) const
Dump()
void FConfigFile::Dump (FOutputDevice & Ar)
References Ar.
Empty()
FORCEINLINE void FConfigFile::Empty (int32 ExpectedNumElements = 0) inline
Definition at line 659 of file ConfigCacheIni.h.
References ConfigFileMapLock, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Empty(), and FORCEINLINE.
end()
FORCEINLINE TRangedForConstIterator FConfigFile::end () const inline
Definition at line 752 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
Referenced by UE_DEPRECATED().
FillFileFromBuffer()
void FConfigFile::FillFileFromBuffer (FStringView Buffer, bool bHandleSymbolCommands, const FString & FileHint) private
References Buffer.
FillFileFromDisk()
bool FConfigFile::FillFileFromDisk (const FString & Filename, bool bHandleSymbolCommands) private
References Filename.
FindInternal()
FORCEINLINE FConfigSection * FConfigFile::FindInternal (const FString & SectionName) inline private
Definition at line 829 of file ConfigCacheIni.h.
References ConfigFileMapLock, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), and FORCEINLINE.
FindOrAddConfigSection()
const FConfigSection * FConfigFile::FindOrAddConfigSection (const FString & Name)
References FindOrAddConfigSection(), and Name.
Referenced by FindOrAddConfigSection().
FindOrAddSectionInternal()
FConfigSection * FConfigFile::FindOrAddSectionInternal (const FString & SectionName) private
FindSection()
FORCEINLINE const FConfigSection * FConfigFile::FindSection (const FString & SectionName) const inline
Definition at line 641 of file ConfigCacheIni.h.
References ConfigFileMapLock, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), and FORCEINLINE.
GenerateExportedPropertyLine()
FString FConfigFile::GenerateExportedPropertyLine (const FString & PropertyName, const FString & PropertyValue) static
Generate a correctly escaped line to add to the config file for the given property.
References PropertyName.
GetArray()
int32 FConfigFile::GetArray (const TCHAR * Section, const TCHAR * Key, TArray< FString > & Value) const
References Key, and Value.
Referenced by GetValue().
GetBool()
bool FConfigFile::GetBool (const TCHAR * Section, const TCHAR * Key, bool & Value) const
References Key, and Value.
Referenced by GetValue().
GetDouble()
bool FConfigFile::GetDouble (const TCHAR * Section, const TCHAR * Key, double & Value) const
References Key, and Value.
Referenced by GetValue().
GetFloat()
bool FConfigFile::GetFloat (const TCHAR * Section, const TCHAR * Key, float & Value) const
References Key, and Value.
Referenced by GetValue().
GetInt()
bool FConfigFile::GetInt (const TCHAR * Section, const TCHAR * Key, int32 & Value) const
References Key, and Value.
Referenced by GetValue().
GetInt64()
bool FConfigFile::GetInt64 (const TCHAR * Section, const TCHAR * Key, int64 & Value) const
References Key, and Value.
Referenced by GetValue().
GetKeys() [1/2]
FORCEINLINE int32 FConfigFile::GetKeys (TArray< FString > & Keys) const inline
Definition at line 671 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys().
GetKeys() [2/2]
FORCEINLINE int32 FConfigFile::GetKeys (TSet< FString > & Keys) const inline
Definition at line 677 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys().
GetString()
bool FConfigFile::GetString (const TCHAR * Section, const TCHAR * Key, FString & Value) const
References Key, and Value.
Referenced by GetValue().
GetText()
bool FConfigFile::GetText (const TCHAR * Section, const TCHAR * Key, FText & Value) const
References Key, and Value.
Referenced by GetValue().
GetValue() [1/8]
bool FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, bool & Value) const inline
Definition at line 876 of file ConfigCacheIni.h.
References GetBool(), Key, and Value.
GetValue() [2/8]
bool FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, double & Value) const inline
Definition at line 868 of file ConfigCacheIni.h.
References GetDouble(), Key, and Value.
GetValue() [3/8]
bool FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, float & Value) const inline
Definition at line 864 of file ConfigCacheIni.h.
References GetFloat(), Key, and Value.
GetValue() [4/8]
bool FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, FString & Value) const inline
Definition at line 852 of file ConfigCacheIni.h.
References GetString(), Key, and Value.
GetValue() [5/8]
bool FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, FText & Value) const inline
Definition at line 856 of file ConfigCacheIni.h.
References GetText(), Key, and Value.
GetValue() [6/8]
bool FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, int32 & Value) const inline
Definition at line 860 of file ConfigCacheIni.h.
References GetInt(), Key, and Value.
GetValue() [7/8]
bool FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, int64 & Value) const inline
Definition at line 872 of file ConfigCacheIni.h.
References GetInt64(), Key, and Value.
GetValue() [8/8]
int32 FConfigFile::GetValue (const TCHAR * Section, const TCHAR * Key, TArray< FString > & Value) const inline
Definition at line 880 of file ConfigCacheIni.h.
References GetArray(), Key, and Value.
IsADefaultIniWrite()
bool FConfigFile::IsADefaultIniWrite (const FString & Filename, int32 & OutIniCombineThreshold) const private
Determine if writing a default hierarchal ini, and deduce position in the hierarchy.
References Filename.
IsEmpty()
FORCEINLINE bool FConfigFile::IsEmpty () const inline
Definition at line 653 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::IsEmpty().
Num()
FORCEINLINE int32 FConfigFile::Num () const inline
Definition at line 647 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Num().
operator!=()
bool FConfigFile::operator!= (const FConfigFile & Other) const
References FConfigFile(), and Other.
operator=() [1/2]
FConfigFile & FConfigFile::operator= (const FConfigFile & Other)
References FConfigFile(), and Other.
operator=() [2/2]
FConfigFile & FConfigFile::operator= (FConfigFile && Other)
References FConfigFile(), and Other.
operator==()
bool FConfigFile::operator== (const FConfigFile & Other) const
References FConfigFile(), and Other.
OverrideFileFromCommandline()
bool FConfigFile::OverrideFileFromCommandline (FString & Filename) static
Checks the command line for any overridden config file settings.
References Filename.
OverrideFromCommandline() [1/2]
void FConfigFile::OverrideFromCommandline (FConfigCommandStream * File, const FString & Filename) static
References Filename.
OverrideFromCommandline() [2/2]
void FConfigFile::OverrideFromCommandline (FConfigFile * File, const FString & Filename) static
Checks the command line for any overridden config settings.
References FConfigFile(), and Filename.
ProcessCommand()
void FConfigFile::ProcessCommand (FConfigSection * Section, FStringView SectionName, FConfigValue::EValueType Command, FName Key, FString && Value) private
References Key, and Value.
ProcessInputFileContents()
void FConfigFile::ProcessInputFileContents (FStringView Contents, const FString & FileHint)
Process the contents of an .ini file that has been read into an FString.
Parameters
Filename Name of the .ini file the contents came from
Contents Contents of the .ini file
ProcessPropertyAndWriteForDefaults()
void FConfigFile::ProcessPropertyAndWriteForDefaults (int32 IniCombineThreshold, const TArray< const FConfigValue * > & InCompletePropertyToProcess, FString & OutText, const FString & SectionName, const FString & PropertyName) private
Process the property for Writing to a default file.
We will need to check for array operations, as default ini's rely on this being correct to function properly
Parameters
IniCombineThreshold - Cutoff level for combining ini (to prevent applying changes from the same ini that we're writing)
InCompletePropertyToProcess - The complete property which we need to process for saving.
OutText - The stream we are processing the array to
SectionName - The section name the array property is being written to
PropertyName - The property name of the array
References PropertyName.
ProcessSourceAndCheckAgainstBackup()
void FConfigFile::ProcessSourceAndCheckAgainstBackup ()
Check the source hierarchy which was loaded without any user changes from the Config/Saved dir.
If anything in the default/base options have changed, we need to ensure that these propagate through to the final config so they are not potentially ignored
Read()
void FConfigFile::Read (const FString & Filename)
References Filename.
Remove()
FORCEINLINE int32 FConfigFile::Remove (KeyConstPointerType InKey) inline
Definition at line 683 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Remove().
RemoveFromSection()
bool FConfigFile::RemoveFromSection (const TCHAR * Section, FName Key, const FString & Value)
Removes every entry in the Section that has the Key/Value pair This is equivalent to the - operator in .ini files (although it will remove all instances of the pair, not just a single one)
Returns
true if the section was modified
References Key, and Value.
RemoveKeyFromSection()
bool FConfigFile::RemoveKeyFromSection (const TCHAR * Section, FName Key)
Removes every entry in the Section that has Key, no matter what the Value is This is equivalent to the !
operator in .ini files
Returns
true if the section was modified
References Key.
Reset()
FORCEINLINE void FConfigFile::Reset () inline
Definition at line 719 of file ConfigCacheIni.h.
References ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reset().
ResetKeyInSection()
bool FConfigFile::ResetKeyInSection (const TCHAR * Section, FName Key)
Similar to RemvoeKeyFromSection, but if this File's changes are being tracked, then we remove all changes to the the key that have been tracked.
This would be used to remove enries in a layer so that the values from previous layers are used, unmodified. "Reset To Defaults" This is equivalent to deleting the keys from a .ini file
Returns
true if the section was modified
References Key.
SaveSourceToBackupFile()
void FConfigFile::SaveSourceToBackupFile () private
Save the source hierarchy which was loaded out to a backup file so we can check future changes in the base/default configs.
SetArray()
void FConfigFile::SetArray (const TCHAR * Section, const TCHAR * Key, const TArray< FString > & Value)
References Key, and Value.
SetBool()
void FConfigFile::SetBool (const TCHAR * Section, const TCHAR * Key, bool Value)
References Key, and Value.
SetDouble()
void FConfigFile::SetDouble (const TCHAR * Section, const TCHAR * Key, double Value)
References Key, and Value.
SetFloat()
void FConfigFile::SetFloat (const TCHAR * Section, const TCHAR * Key, float Value)
References Key, and Value.
SetInt64()
void FConfigFile::SetInt64 (const TCHAR * Section, const TCHAR * Key, const int64 Value)
References Key, and Value.
SetString()
void FConfigFile::SetString (const TCHAR * Section, const TCHAR * Key, const TCHAR * Value)
References Key, and Value.
SetText()
void FConfigFile::SetText (const TCHAR * Section, const TCHAR * Key, const FText & Value)
References Key, and Value.
ShouldExportQuotedString()
bool FConfigFile::ShouldExportQuotedString (const FString & PropertyValue) static
Checks if the PropertyValue should be exported in quotes when writing the ini to disk.
Shrink()
void FConfigFile::Shrink () private
UE_DEPRECATED() [1/6]
FConfigFile::UE_DEPRECATED (5. 4, "Use const ranged for iterators, (wrap your FConfigFile variable in AsConst to force the const iterator). See top of ConfigCacheIni.h for more info.") inline
Definition at line 732 of file ConfigCacheIni.h.
References begin(), ConfigFileMapLock, FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
UE_DEPRECATED() [2/6]
FConfigFile::UE_DEPRECATED (5. 4, "Use const ranged for iterators, (wrap your FConfigFile variable in AsConst to force the const iterator). See top of ConfigCacheIni.h for more info.") inline
Definition at line 745 of file ConfigCacheIni.h.
References ConfigFileMapLock, end(), FORCEINLINE, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
UE_DEPRECATED() [3/6]
FConfigFile::UE_DEPRECATED (5. 4, "Use FindOrAddConfigSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") const &
References Name.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [4/6]
FConfigFile::UE_DEPRECATED (5. 4, "Use FindOrAddConfigSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") const & inline
Definition at line 725 of file ConfigCacheIni.h.
References ConfigFileMapLock, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd(), FORCEINLINE, and Key.
UE_DEPRECATED() [5/6]
FConfigFile::UE_DEPRECATED (5. 4, "Use FindSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") const & inline
Definition at line 627 of file ConfigCacheIni.h.
References ConfigFileMapLock, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), FORCEINLINE, and UE_DEPRECATED().
UE_DEPRECATED() [6/6]
FConfigFile::UE_DEPRECATED (5. 4, "Use FindSection, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") const & inline
Definition at line 634 of file ConfigCacheIni.h.
References ConfigFileMapLock, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), and FORCEINLINE.
UpdateSections()
void FConfigFile::UpdateSections (const TCHAR * DiskFilename, const TCHAR * IniRootName = nullptr, const TCHAR * OverridePlatform = nullptr)
Saves only the sections in this FConfigFile into the given file.
All other sections in the file are left alone. The sections in this file are completely replaced. If IniRootName is specified, the current section settings are diffed against the file in the hierarchy up to right before this file (so, if you are saving DefaultEngine.ini, and IniRootName is "Engine", then Base.ini and BaseEngine.ini will be loaded, and only differences against that will be saved into DefaultEngine.ini)
autotoc_md23
Todo
: This currently doesn't work with array properties!! It will output the entire array, and without + notation!!
Parameters
IniRootName the name (like "Engine") to use to load a .ini hierarchy to diff against
UpdateSinglePropertyInSection()
bool FConfigFile::UpdateSinglePropertyInSection (const TCHAR * DiskFilename, const TCHAR * PropertyName, const TCHAR * SectionName)
Update a single property in the config file, for the section that is specified.
References PropertyName.
Write()
bool FConfigFile::Write (const FString & Filename, bool bDoRemoteWrite = true, const FString & PrefixText = FString())
Write this ConfigFile to the given Filename, constructed the text from the config sections in *this, prepended by the optional PrefixText.
References Filename.
WriteInternal()
bool FConfigFile::WriteInternal (const FString & Filename, bool bDoRemoteWrite, TMap< FString, FString > & InOutSectionTexts, const TArray< FString > & InSectionOrder) private
Write a ConfigFile to the given Filename, constructed from the given SectionTexts, in the given order, with sections in *this overriding sections in SectionTexts.
Parameters
Filename - The file to write to
bDoRemoteWrite - If true, also write the file to FRemoteConfig::Get()
InOutSectionTexts - A map from section name to existing text for that section; text does not include the name of the section. Entries in the TMap that also exist in *this will be updated. If the empty string is present, it will be written out first (it is interpreted as a prefix before the first section)
InSectionOrder - List of section names in the order in which each section should be written to disk, from e.g. the existing file. Any section in this array that is not found in InOutSectionTexts will be ignored. Any section in InOutSectionTexts that is not in this array will be appended to the end. Duplicate entries are ignored; the first found index is used.
Returns
TRUE if the write was successful
References TMap< FString, FConfigSection >::TMap(), and Filename.
WriteTempFileThenMove()
bool FConfigFile::WriteTempFileThenMove () static
Whether to write a temp file then move it to it's destination when saving.
WriteToString()
void FConfigFile::WriteToString (FString & InOutText, const FString & SimulatedFilename = FString(), const FString & PrefixText = FString())
Write this ConfigFile to the given string, constructed the text from the config sections in *this, prepended by the optional PrefixText.
Parameters
SimulatedFilename - If writing a default hierarchal ini, can be used to correctly deduce position in the hierarchy
WriteToStringInternal()
void FConfigFile::WriteToStringInternal (FString & InOutText, bool bIsADefaultIniWrite, int32 IniCombineThreshold, TMap< FString, FString > & InOutSectionTexts, const TArray< FString > & InSectionOrder) private
Write a ConfigFile to InOutText, constructed from the given SectionTexts, in the given order, with sections in *this overriding sections in SectionTexts.
Parameters
InOutText - The string to write to
bIsADefaultIniWrite - If true, force all properties to be written
IniCombineThreshold - Cutoff level for combining ini (to prevent applying changes from the same ini that we're writing)
InOutSectionTexts - A map from section name to existing text for that section; text does not include the name of the section. Entries in the TMap that also exist in *this will be updated. If the empty string is present, it will be written out first (it is interpreted as a prefix before the first section)
InSectionOrder - List of section names in the order in which each section should be written to disk, from e.g. the existing file. Any section in this array that is not found in InOutSectionTexts will be ignored. Any section in InOutSectionTexts that is not in this array will be appended to the end. Duplicate entries are ignored; the first found index is used.
Returns
TRUE if the write was successful
References TMap< FString, FConfigSection >::TMap().
Friends And Related Symbol Documentation
FConfigBranch
friend class FConfigBranch friend
Definition at line 591 of file ConfigCacheIni.h.
References FConfigBranch.
Referenced by FConfigBranch.
FConfigCacheIni
friend class FConfigCacheIni friend
Definition at line 1027 of file ConfigCacheIni.h.
References FConfigCacheIni.
Referenced by FConfigCacheIni.
FillFileFromBuffer
template<typename FileType> void FillFileFromBuffer (FileType * File, FStringView Buffer, bool bHandleSymbolCommands, const FString & FileHint) friend
References Buffer.
operator<<
FArchive & operator<< (FArchive & Ar, FConfigFile & ConfigFile) friend
References FConfigFile(), and Ar.
Field Documentation
bCanSaveAllSections
bool FConfigFile::bCanSaveAllSections
Definition at line 578 of file ConfigCacheIni.h.
bHasPlatformName
bool FConfigFile::bHasPlatformName
Definition at line 573 of file ConfigCacheIni.h.
bPythonConfigParserMode
bool FConfigFile::bPythonConfigParserMode
Definition at line 574 of file ConfigCacheIni.h.
Branch
class FConfigBranch* FConfigFile::Branch = nullptr
Definition at line 592 of file ConfigCacheIni.h.
ChangeTracker
FConfigCommandStream* FConfigFile::ChangeTracker = nullptr private
Definition at line 605 of file ConfigCacheIni.h.
CommandlineOptions
TArray<FConfigCommandlineOverride> FConfigFile::CommandlineOptions
The collection of overrides which stemmed from the commandline.
Definition at line 596 of file ConfigCacheIni.h.
ConfigFileMapLock
FTransactionallySafeRWLock FConfigFile::ConfigFileMapLock static private
Definition at line 1030 of file ConfigCacheIni.h.
Referenced by Add(), Add(), Add(), Add(), Append(), begin(), Contains(), Empty(), end(), FindInternal(), FindSection(), GetKeys(), GetKeys(), IsEmpty(), Num(), Remove(), Reset(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Dirty
bool FConfigFile::Dirty
Definition at line 571 of file ConfigCacheIni.h.
FConfigContext
friend FConfigFile::FConfigContext private
Definition at line 1028 of file ConfigCacheIni.h.
Referenced by AddStaticLayersToHierarchy().
Name
FName FConfigFile::Name
The name of this config file.
Definition at line 584 of file ConfigCacheIni.h.
Referenced by FindOrAddConfigSection(), and UE_DEPRECATED().
NoSave
bool FConfigFile::NoSave
Definition at line 572 of file ConfigCacheIni.h.
PerObjectConfigArrayOfStructKeys
TMap<FString, TMap<FName, FString> > FConfigFile::PerObjectConfigArrayOfStructKeys private
Definition at line 602 of file ConfigCacheIni.h.
PlatformName
FString FConfigFile::PlatformName
Definition at line 585 of file ConfigCacheIni.h.
Tag
FName FConfigFile::Tag
Definition at line 588 of file ConfigCacheIni.h.
The documentation for this class was generated from the following file:
ConfigCacheIni.h