Unreal Engine 5.6 C++ API: StructuredLog.h File Reference
StructuredLog.h File Reference
#include "Concepts/Insertable.h"
#include "Containers/StringFwd.h"
#include "Logging/LogCategory.h"
#include "Logging/LogMacros.h"
#include "Logging/LogVerbosity.h"
#include "Misc/OptionalFwd.h"
#include "Serialization/CompactBinary.h"
#include "Serialization/CompactBinaryWriter.h"
#include "Templates/IsArrayOrRefOfType.h"
#include "Templates/Models.h"
#include "Templates/Requires.h"
#include "Templates/UnrealTypeTraits.h"
#include <atomic>
#include <type_traits>
Data Structures
struct UE::CSerializableForLog
Describes a type that can be serialized for use in a log message.
class UE::FLogRecord
Record of a log event.
class UE::FLogTime
Time that a log event occurred.
struct UE::Logging::Private::FLogContext
struct UE::Logging::Private::FLogField
struct UE::Logging::Private::FLogFieldCreator
Create log fields from values optionally preceded by names.
struct UE::Logging::Private::FStaticLocalizedLogRecord
Data about a static localized log that is constant for every occurrence.
struct UE::Logging::Private::FStaticLogDynamicData
Data about a static log that is created on-demand.
struct UE::Logging::Private::FStaticLogRecord
Data about a static log that is constant for every occurrence.
struct UE::Logging::Private::TLogFieldName< NameType >
Wrapper to identify field names interleaved with field values.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Logging
namespace UE::Logging::Private
Macros
#define UE_API CORE_API
#define UE_CLOGFMT(Condition, CategoryName, Verbosity, Format, ...)
Conditional UE_LOGFMT.
#define UE_CLOGFMT_EX(Condition, CategoryName, Verbosity, Format, ...)
Conditional UE_LOGFMT_EX.
#define UE_CLOGFMT_LOC(Condition, CategoryName, Verbosity, Key, Format, ...)
Conditional UE_LOGFMT_LOC.
#define UE_CLOGFMT_LOC_EX(Condition, CategoryName, Verbosity, Key, Format, ...)
Conditional UE_LOGFMT_LOC_EX.
#define UE_CLOGFMT_NSLOC(Condition, CategoryName, Verbosity, Namespace, Key, Format, ...)
#define UE_CLOGFMT_NSLOC_EX(Condition, CategoryName, Verbosity, Namespace, Key, Format, ...)
#define UE_LOG_CONTEXT(Name, ...)
Registers a context on the calling thread, by name, with an optional value.
#define UE_LOGFMT(CategoryName, Verbosity, Format, ...)
Records a structured log event if this category is active at this level of verbosity.
#define UE_LOGFMT_EX(CategoryName, Verbosity, Format, ...)
Records a structured log event if this category is active at this level of verbosity.
#define UE_LOGFMT_FIELD(Name, Value)
Expands to a named structured log field.
#define UE_LOGFMT_LOC(CategoryName, Verbosity, Key, Format, ...)
Records a localized structured log event if this category is active at this level of verbosity.
#define UE_LOGFMT_LOC_EX(CategoryName, Verbosity, Key, Format, ...)
Records a localized structured log event if this category is active at this level of verbosity.
#define UE_LOGFMT_NSLOC(CategoryName, Verbosity, Namespace, Key, Format, ...)
#define UE_LOGFMT_NSLOC_EX(CategoryName, Verbosity, Namespace, Key, Format, ...)
#define UE_LOGFMT_VALUE(Value)
Expands to a structured log value.
#define UE_PRIVATE_LOG_CATEGORY(CategoryName)
#define UE_PRIVATE_LOGFMT(Condition, CategoryName, Verbosity, Format, ...)
#define UE_PRIVATE_LOGFMT_AGGREGATE(...)
#define UE_PRIVATE_LOGFMT_CALL(F, A)
#define UE_PRIVATE_LOGFMT_COUNT(...)
#define UE_PRIVATE_LOGFMT_COUNT_IMPL(_, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Count, ...)
#define UE_PRIVATE_LOGFMT_EXPAND(X)
#define UE_PRIVATE_LOGFMT_FIELD(Field)
#define UE_PRIVATE_LOGFMT_FIELD_EXPAND(...)
#define UE_PRIVATE_LOGFMT_FIELD_EXPAND_INNER(...)
#define UE_PRIVATE_LOGFMT_FIELDS(...)
#define UE_PRIVATE_LOGFMT_FIELDS_0()
#define UE_PRIVATE_LOGFMT_FIELDS_1(A)
#define UE_PRIVATE_LOGFMT_FIELDS_10(A, B, C, D, E, F, G, H, I, J)
#define UE_PRIVATE_LOGFMT_FIELDS_11(A, B, C, D, E, F, G, H, I, J, K)
#define UE_PRIVATE_LOGFMT_FIELDS_12(A, B, C, D, E, F, G, H, I, J, K, L)
#define UE_PRIVATE_LOGFMT_FIELDS_13(A, B, C, D, E, F, G, H, I, J, K, L, M)
#define UE_PRIVATE_LOGFMT_FIELDS_14(A, B, C, D, E, F, G, H, I, J, K, L, M, N)
#define UE_PRIVATE_LOGFMT_FIELDS_15(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O)
#define UE_PRIVATE_LOGFMT_FIELDS_16(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P)
#define UE_PRIVATE_LOGFMT_FIELDS_2(A, B)
#define UE_PRIVATE_LOGFMT_FIELDS_3(A, B, C)
#define UE_PRIVATE_LOGFMT_FIELDS_4(A, B, C, D)
#define UE_PRIVATE_LOGFMT_FIELDS_5(A, B, C, D, E)
#define UE_PRIVATE_LOGFMT_FIELDS_6(A, B, C, D, E, F)
#define UE_PRIVATE_LOGFMT_FIELDS_7(A, B, C, D, E, F, G)
#define UE_PRIVATE_LOGFMT_FIELDS_8(A, B, C, D, E, F, G, H)
#define UE_PRIVATE_LOGFMT_FIELDS_9(A, B, C, D, E, F, G, H, I)
#define UE_PRIVATE_LOGFMT_LOC(Condition, CategoryName, Verbosity, Namespace, Key, Format, ...)
#define UE_PRIVATE_LOGFMT_LOG_IF_ACTIVE(Condition, CategoryName, Verbosity, Log, ...)
#define UE_PRIVATE_LOGFMT_NAMED_FIELD(Name, ...)
#define UE_PRIVATE_LOGFMT_STRIP_UE_PRIVATE_LOGFMT_NAMED_FIELD
Functions
template<typename ValueType UE_REQUIRES>
void UE::CallSerializeForLog (FCbWriter &Writer, ValueType &&Value)
Wrapper to support calling SerializeForLog with ADL from within an overload of SerializeForLog.
template<typename NameType>
constexpr TLogFieldName< NameType > UE::Logging::Private::CheckFieldName (NameType &&Name)
Verify that the name is likely a string literal and forward it on.
void UE::DispatchDynamicLogRecord (const FLogRecord &Record)
Advanced function to dispatch a log record to active output devices.
void UE::Logging::Private::FatalLogWithFieldArray (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log, const FLogField *Fields, int32 FieldCount)
void UE::Logging::Private::FatalLogWithFieldArray (const FLogCategoryBase &Category, const FStaticLogRecord &Log, const FLogField *Fields, int32 FieldCount)
template<typename LogType, typename... FieldArgTypes>
UE_COLD UE_DEBUG_SECTION void UE::Logging::Private::FatalLogWithFields (const FLogCategoryBase &Category, const LogType &Log, FieldArgTypes &&... FieldArgs)
Fatal log with fields created from the arguments, which may be values or pairs of name/value.
void UE::Logging::Private::FatalLogWithNoFields (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log)
void UE::Logging::Private::FatalLogWithNoFields (const FLogCategoryBase &Category, const FStaticLogRecord &Log)
void UE::Logging::Private::LogWithFieldArray (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log, const FLogField *Fields, int32 FieldCount)
void UE::Logging::Private::LogWithFieldArray (const FLogCategoryBase &Category, const FStaticLogRecord &Log, const FLogField *Fields, int32 FieldCount)
template<typename LogType, typename... FieldArgTypes>
UE_COLD UE_DEBUG_SECTION void UE::Logging::Private::LogWithFields (const FLogCategoryBase &Category, const LogType &Log, FieldArgTypes &&... FieldArgs)
Log with fields created from the arguments, which may be values or pairs of name/value.
void UE::Logging::Private::LogWithNoFields (const FLogCategoryBase &Category, const FStaticLocalizedLogRecord &Log)
void UE::Logging::Private::LogWithNoFields (const FLogCategoryBase &Category, const FStaticLogRecord &Log)
template<typename ValueType UE_REQUIRES>
void SerializeForLog (FCbWriter &Writer, const TOptional< ValueType > &Optional)
template<typename ValueType UE_REQUIRES>
void UE::SerializeForLog (FCbWriter &Writer, ValueType &&Value)
Serializes the value to be used in a log message.
void UE::VisitLogContext (TFunctionRef< void(const FCbField &)> Visitor)
Advanced function to visit the log contexts for the calling thread.
Macro Definition Documentation
UE_API
#define UE_API CORE_API
Definition at line 24 of file StructuredLog.h.
UE_CLOGFMT
#define UE_CLOGFMT (Condition, CategoryName, Verbosity, Format, ...)
Value:
UE_PRIVATE_LOGFMT_CALL(UE_CLOGFMT_EX, (Condition, CategoryName, Verbosity, Format UE_PRIVATE_LOGFMT_FIELDS(__VA_ARGS__)))
Conditional UE_LOGFMT.
Definition at line 49 of file StructuredLog.h.
UE_CLOGFMT_EX
#define UE_CLOGFMT_EX (Condition, CategoryName, Verbosity, Format, ...)
Value:
UE_PRIVATE_LOGFMT(if (Condition), CategoryName, Verbosity, Format, ##__VA_ARGS__)
Conditional UE_LOGFMT_EX.
Definition at line 67 of file StructuredLog.h.
UE_CLOGFMT_LOC
#define UE_CLOGFMT_LOC (Condition, CategoryName, Verbosity, Key, Format, ...)
Value:
    UE_CLOGFMT_NSLOC(Condition, CategoryName, Verbosity, LOCTEXT_NAMESPACE, Key, Format, ##__VA_ARGS__)
Conditional UE_LOGFMT_LOC.
Definition at line 93 of file StructuredLog.h.
UE_CLOGFMT_LOC_EX
#define UE_CLOGFMT_LOC_EX (Condition, CategoryName, Verbosity, Key, Format, ...)
Value:
    UE_CLOGFMT_NSLOC_EX(Condition, CategoryName, Verbosity, LOCTEXT_NAMESPACE, Key, Format, ##__VA_ARGS__)
Conditional UE_LOGFMT_LOC_EX.
Definition at line 114 of file StructuredLog.h.
UE_CLOGFMT_NSLOC
#define UE_CLOGFMT_NSLOC (Condition, CategoryName, Verbosity, Namespace, Key, Format, ...)
Value:
    UE_PRIVATE_LOGFMT_CALL(UE_CLOGFMT_NSLOC_EX, (Condition, CategoryName, Verbosity, Namespace, Key, Format UE_PRIVATE_LOGFMT_FIELDS(__VA_ARGS__)))
Definition at line 95 of file StructuredLog.h.
UE_CLOGFMT_NSLOC_EX
#define UE_CLOGFMT_NSLOC_EX (Condition, CategoryName, Verbosity, Namespace, Key, Format, ...)
Value:
    UE_PRIVATE_LOGFMT_LOC(if (Condition), CategoryName, Verbosity, Namespace, Key, Format, ##__VA_ARGS__)
Definition at line 116 of file StructuredLog.h.
UE_LOG_CONTEXT
#define UE_LOG_CONTEXT (Name, ...)
Value:
::UE::Logging::Private::FLogContext ANONYMOUS_VARIABLE(LogContext_)(Name, ##__VA_ARGS__)
Registers a context on the calling thread, by name, with an optional value.
The optional value can be anything that serializes to compact binary using FCbWriter or SerializeForLog. Context is unregistered when it goes out of scope. Context is overridden by a newer context with the same name. Context is overridden by a field of the same name in the log record. Context is copied to FLogRecord::Fields for every log record created in the lifetime of the context. Context names are written to FLogRecord::Fields in an array named $Context. Contexts can be visited by calling VisitLogContext.
Examples: UE_LOG_CONTEXT("Loading"); UE_LOG_CONTEXT("Count", 123.0); UE_LOG_CONTEXT("Asset", FAssetLog(AssetPath));
Definition at line 143 of file StructuredLog.h.
UE_LOGFMT
#define UE_LOGFMT (CategoryName, Verbosity, Format, ...)
Value:
UE_PRIVATE_LOGFMT_CALL(UE_LOGFMT_EX, (CategoryName, Verbosity, Format UE_PRIVATE_LOGFMT_FIELDS(__VA_ARGS__)))
Records a structured log event if this category is active at this level of verbosity.
Supports either positional or named parameters, but not a mix of these styles.
Positional: The field values must exactly match the fields referenced by Format. UE_LOGFMT(LogCore, Warning, "Loading '{Name}' failed with error {Error}", Package->GetName(), ErrorCode);
Named: The fields must contain every field referenced by Format. Order is irrelevant and extra fields are permitted. UE_LOGFMT(LogCore, Warning, "Loading '{Name}' failed with error {Error}", ("Name", Package->GetName()), ("Error", ErrorCode), ("Flags", LoadFlags));
Field names must match "[A-Za-z0-9_]+" and must be unique within this log event. Field values will be serialized using SerializeForLog or operator<<(FCbWriter&, FieldType).
Parameters
CategoryName Name of a log category declared by DECLARE_LOG_CATEGORY_*.
Verbosity Name of a log verbosity level from ELogVerbosity.
Format Format string in the style of FLogTemplate.
Fields[0-16] Zero to sixteen fields or field values.
Definition at line 46 of file StructuredLog.h.
UE_LOGFMT_EX
#define UE_LOGFMT_EX (CategoryName, Verbosity, Format, ...)
Value:
UE_PRIVATE_LOGFMT(UE_EMPTY, CategoryName, Verbosity, Format, ##__VA_ARGS__)
Records a structured log event if this category is active at this level of verbosity.
This has the same functionality as UE_LOGFMT but removes the limit on field count.
Positional: Values must be wrapped in UE_LOGFMT_VALUE. UE_LOGFMT_EX(LogCore, Warning, "Loading '{Name}' failed with error {Error}", UE_LOGFMT_VALUE(Package->GetName()), UE_LOGFMT_VALUE(ErrorCode));
Named: Fields must be wrapped in UE_LOGFMT_FIELD. UE_LOGFMT_EX(LogCore, Warning, "Loading '{Name}' failed with error {Error}", UE_LOGFMT_FIELD("Name", Package->GetName()), UE_LOGFMT_FIELD("Error", ErrorCode), UE_LOGFMT_FIELD("Flags", LoadFlags));
Definition at line 64 of file StructuredLog.h.
UE_LOGFMT_FIELD
#define UE_LOGFMT_FIELD (Name, Value)
Value:
UE_PRIVATE_LOGFMT_FIELD((Name, Value))
Expands to a named structured log field.
UE_LOGFMT_FIELD("Name", Value)
Definition at line 120 of file StructuredLog.h.
UE_LOGFMT_LOC
#define UE_LOGFMT_LOC (CategoryName, Verbosity, Key, Format, ...)
Value:
    UE_LOGFMT_NSLOC(CategoryName, Verbosity, LOCTEXT_NAMESPACE, Key, Format, ##__VA_ARGS__)
Records a localized structured log event if this category is active at this level of verbosity.
Example: UE_LOGFMT_LOC(LogCore, Warning, "LoadingFailed", "Loading '{Name}' failed with error {Error}", ("Name", Package->GetName()), ("Error", ErrorCode), ("Flags", LoadFlags));
Field names must match "[A-Za-z0-9_]+" and must be unique within this log event. Field values will be serialized using SerializeForLog or operator<<(FCbWriter&, FieldType). The fields must contain every field referenced by Format. Order is irrelevant and extra fields are permitted.
Parameters
CategoryName Name of a log category declared by DECLARE_LOG_CATEGORY_*.
Verbosity Name of a log verbosity level from ELogVerbosity.
Namespace Namespace for the format FText, or LOCTEXT_NAMESPACE for the non-NS macro.
Key Key for the format FText that is unique within the namespace.
Format Format string in the style of FTextFormat.
Fields[0-16] Zero to sixteen fields in the format ("Name", Value).
Definition at line 87 of file StructuredLog.h.
UE_LOGFMT_LOC_EX
#define UE_LOGFMT_LOC_EX (CategoryName, Verbosity, Key, Format, ...)
Value:
    UE_LOGFMT_NSLOC_EX(CategoryName, Verbosity, LOCTEXT_NAMESPACE, Key, Format, ##__VA_ARGS__)
Records a localized structured log event if this category is active at this level of verbosity.
Example: UE_LOGFMT_LOC_EX(LogCore, Warning, "LoadingFailed", "Loading '{PackageName}' failed with error {Error}", UE_LOGFMT_FIELD("Name", Package->GetName()), UE_LOGFMT_FIELD("Error", ErrorCode), UE_LOGFMT_FIELD("Flags", LoadFlags));
Same as UE_LOGFMT_LOC and works for any number of fields. Fields must be written as UE_LOGFMT_FIELD("Name", Value).
Definition at line 108 of file StructuredLog.h.
UE_LOGFMT_NSLOC
#define UE_LOGFMT_NSLOC (CategoryName, Verbosity, Namespace, Key, Format, ...)
Value:
    UE_PRIVATE_LOGFMT_CALL(UE_LOGFMT_NSLOC_EX, (CategoryName, Verbosity, Namespace, Key, Format UE_PRIVATE_LOGFMT_FIELDS(__VA_ARGS__)))
Definition at line 89 of file StructuredLog.h.
UE_LOGFMT_NSLOC_EX
#define UE_LOGFMT_NSLOC_EX (CategoryName, Verbosity, Namespace, Key, Format, ...)
Value:
    UE_PRIVATE_LOGFMT_LOC(UE_EMPTY, CategoryName, Verbosity, Namespace, Key, Format, ##__VA_ARGS__)
Definition at line 110 of file StructuredLog.h.
UE_LOGFMT_VALUE
#define UE_LOGFMT_VALUE (Value)
Value:
Value
Expands to a structured log value.
UE_LOGFMT_VALUE(Value)
Definition at line 123 of file StructuredLog.h.
UE_PRIVATE_LOG_CATEGORY
#define UE_PRIVATE_LOG_CATEGORY (CategoryName)
Value:
CategoryName
Definition at line 532 of file StructuredLog.h.
UE_PRIVATE_LOGFMT
#define UE_PRIVATE_LOGFMT (Condition, CategoryName, Verbosity, Format, ...)
Value:
    do \
    { \
        if constexpr ((::ELogVerbosity::Verbosity & ::ELogVerbosity::VerbosityMask) == ::ELogVerbosity::Fatal || \
            ((::ELogVerbosity::Verbosity & ::ELogVerbosity::VerbosityMask) <= ::ELogVerbosity::COMPILED_IN_MINIMUM_VERBOSITY && \
             (::ELogVerbosity::Verbosity & ::ELogVerbosity::VerbosityMask) <= UE_PRIVATE_LOG_CATEGORY(CategoryName).CompileTimeVerbosity)) \
        { \
            static ::UE::Logging::Private::FStaticLogDynamicData LOG_Dynamic; \
            static constexpr ::UE::Logging::Private::FStaticLogRecord LOG_Static UE_PRIVATE_LOGFMT_AGGREGATE(TEXT(Format), __builtin_FILE(), __builtin_LINE(), ::ELogVerbosity::Verbosity, LOG_Dynamic); \
            UE_PRIVATE_LOGFMT_LOG_IF_ACTIVE(Condition, CategoryName, Verbosity, LOG_Static, ##__VA_ARGS__); \
        } \
    } \
    while (false)
Definition at line 537 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_AGGREGATE
#define UE_PRIVATE_LOGFMT_AGGREGATE (...)
Value:
{__VA_ARGS__}
Definition at line 583 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_CALL
#define UE_PRIVATE_LOGFMT_CALL (F, A)
Value:
UE_PRIVATE_LOGFMT_EXPAND(F A)
Definition at line 622 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_COUNT
#define UE_PRIVATE_LOGFMT_COUNT (...)
Value:
UE_PRIVATE_LOGFMT_CALL(UE_PRIVATE_LOGFMT_COUNT_IMPL, (_, ##__VA_ARGS__, 16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0))
Definition at line 619 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_COUNT_IMPL
#define UE_PRIVATE_LOGFMT_COUNT_IMPL (_, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Count, ...)
Value:
Count
Definition at line 620 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_EXPAND
#define UE_PRIVATE_LOGFMT_EXPAND (X)
Value:
X
Definition at line 623 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELD
#define UE_PRIVATE_LOGFMT_FIELD (Field)
Value:
UE_PRIVATE_LOGFMT_FIELD_EXPAND(UE_PRIVATE_LOGFMT_NAMED_FIELD Field)
Definition at line 588 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELD_EXPAND
#define UE_PRIVATE_LOGFMT_FIELD_EXPAND (...)
Value:
UE_PRIVATE_LOGFMT_FIELD_EXPAND_INNER(__VA_ARGS__)
Definition at line 592 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELD_EXPAND_INNER
#define UE_PRIVATE_LOGFMT_FIELD_EXPAND_INNER (...)
Value:
UE_PRIVATE_LOGFMT_STRIP_ ## __VA_ARGS__
Definition at line 593 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS
#define UE_PRIVATE_LOGFMT_FIELDS (...)
Value:
UE_PRIVATE_LOGFMT_CALL(PREPROCESSOR_JOIN(UE_PRIVATE_LOGFMT_FIELDS_, UE_PRIVATE_LOGFMT_COUNT(__VA_ARGS__)), (__VA_ARGS__))
Definition at line 598 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_0
#define UE_PRIVATE_LOGFMT_FIELDS_0 ()
Definition at line 600 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_1
#define UE_PRIVATE_LOGFMT_FIELDS_1 (A)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A)
Definition at line 601 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_10
#define UE_PRIVATE_LOGFMT_FIELDS_10 (A, B, C, D, E, F, G, H, I, J)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I), UE_PRIVATE_LOGFMT_FIELD(J)
Definition at line 611 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_11
#define UE_PRIVATE_LOGFMT_FIELDS_11 (A, B, C, D, E, F, G, H, I, J, K)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I), UE_PRIVATE_LOGFMT_FIELD(J), UE_PRIVATE_LOGFMT_FIELD(K)
Definition at line 612 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_12
#define UE_PRIVATE_LOGFMT_FIELDS_12 (A, B, C, D, E, F, G, H, I, J, K, L)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I), UE_PRIVATE_LOGFMT_FIELD(J), UE_PRIVATE_LOGFMT_FIELD(K), UE_PRIVATE_LOGFMT_FIELD(L)
Definition at line 613 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_13
#define UE_PRIVATE_LOGFMT_FIELDS_13 (A, B, C, D, E, F, G, H, I, J, K, L, M)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I), UE_PRIVATE_LOGFMT_FIELD(J), UE_PRIVATE_LOGFMT_FIELD(K), UE_PRIVATE_LOGFMT_FIELD(L), UE_PRIVATE_LOGFMT_FIELD(M)
Definition at line 614 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_14
#define UE_PRIVATE_LOGFMT_FIELDS_14 (A, B, C, D, E, F, G, H, I, J, K, L, M, N)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I), UE_PRIVATE_LOGFMT_FIELD(J), UE_PRIVATE_LOGFMT_FIELD(K), UE_PRIVATE_LOGFMT_FIELD(L), UE_PRIVATE_LOGFMT_FIELD(M), UE_PRIVATE_LOGFMT_FIELD(N)
Definition at line 615 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_15
#define UE_PRIVATE_LOGFMT_FIELDS_15 (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I), UE_PRIVATE_LOGFMT_FIELD(J), UE_PRIVATE_LOGFMT_FIELD(K), UE_PRIVATE_LOGFMT_FIELD(L), UE_PRIVATE_LOGFMT_FIELD(M), UE_PRIVATE_LOGFMT_FIELD(N), UE_PRIVATE_LOGFMT_FIELD(O)
Definition at line 616 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_16
#define UE_PRIVATE_LOGFMT_FIELDS_16 (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I), UE_PRIVATE_LOGFMT_FIELD(J), UE_PRIVATE_LOGFMT_FIELD(K), UE_PRIVATE_LOGFMT_FIELD(L), UE_PRIVATE_LOGFMT_FIELD(M), UE_PRIVATE_LOGFMT_FIELD(N), UE_PRIVATE_LOGFMT_FIELD(O), UE_PRIVATE_LOGFMT_FIELD(P)
Definition at line 617 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_2
#define UE_PRIVATE_LOGFMT_FIELDS_2 (A, B)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B)
Definition at line 602 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_3
#define UE_PRIVATE_LOGFMT_FIELDS_3 (A, B, C)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C)
Definition at line 603 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_4
#define UE_PRIVATE_LOGFMT_FIELDS_4 (A, B, C, D)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D)
Definition at line 604 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_5
#define UE_PRIVATE_LOGFMT_FIELDS_5 (A, B, C, D, E)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E)
Definition at line 605 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_6
#define UE_PRIVATE_LOGFMT_FIELDS_6 (A, B, C, D, E, F)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F)
Definition at line 606 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_7
#define UE_PRIVATE_LOGFMT_FIELDS_7 (A, B, C, D, E, F, G)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G)
Definition at line 607 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_8
#define UE_PRIVATE_LOGFMT_FIELDS_8 (A, B, C, D, E, F, G, H)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H)
Definition at line 608 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_FIELDS_9
#define UE_PRIVATE_LOGFMT_FIELDS_9 (A, B, C, D, E, F, G, H, I)
Value:
, UE_PRIVATE_LOGFMT_FIELD(A), UE_PRIVATE_LOGFMT_FIELD(B), UE_PRIVATE_LOGFMT_FIELD(C), UE_PRIVATE_LOGFMT_FIELD(D), UE_PRIVATE_LOGFMT_FIELD(E), UE_PRIVATE_LOGFMT_FIELD(F), UE_PRIVATE_LOGFMT_FIELD(G), UE_PRIVATE_LOGFMT_FIELD(H), UE_PRIVATE_LOGFMT_FIELD(I)
Definition at line 609 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_LOC
#define UE_PRIVATE_LOGFMT_LOC (Condition, CategoryName, Verbosity, Namespace, Key, Format, ...)
Value:
    do \
    { \
        if constexpr ((::ELogVerbosity::Verbosity & ::ELogVerbosity::VerbosityMask) == ::ELogVerbosity::Fatal || \
            ((::ELogVerbosity::Verbosity & ::ELogVerbosity::VerbosityMask) <= ::ELogVerbosity::COMPILED_IN_MINIMUM_VERBOSITY && \
             (::ELogVerbosity::Verbosity & ::ELogVerbosity::VerbosityMask) <= UE_PRIVATE_LOG_CATEGORY(CategoryName).CompileTimeVerbosity)) \
        { \
            static ::UE::Logging::Private::FStaticLogDynamicData LOG_Dynamic; \
            static constexpr ::UE::Logging::Private::FStaticLocalizedLogRecord LOG_Static UE_PRIVATE_LOGFMT_AGGREGATE(TEXT(Namespace), TEXT(Key), TEXT(Format), __builtin_FILE(), __builtin_LINE(), ::ELogVerbosity::Verbosity, LOG_Dynamic); \
            UE_PRIVATE_LOGFMT_LOG_IF_ACTIVE(Condition, CategoryName, Verbosity, LOG_Static, ##__VA_ARGS__); \
        } \
    } \
    while (false)
Definition at line 551 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_LOG_IF_ACTIVE
#define UE_PRIVATE_LOGFMT_LOG_IF_ACTIVE (Condition, CategoryName, Verbosity, Log, ...)
Value:
    if constexpr ((::ELogVerbosity::Verbosity & ::ELogVerbosity::VerbosityMask) == ::ELogVerbosity::Fatal) \
    { \
        Condition \
        { \
            ::UE::Logging::Private::FatalLogWithFields(UE_PRIVATE_LOG_CATEGORY(CategoryName), LOG_Static, ##__VA_ARGS__); \
        } \
    } \
    else if (!UE_PRIVATE_LOG_CATEGORY(CategoryName).IsSuppressed(::ELogVerbosity::Verbosity)) \
    { \
        Condition \
        { \
            ::UE::Logging::Private::LogWithFields(UE_PRIVATE_LOG_CATEGORY(CategoryName), LOG_Static, ##__VA_ARGS__); \
        } \
    }
Definition at line 565 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_NAMED_FIELD
#define UE_PRIVATE_LOGFMT_NAMED_FIELD (Name, ...)
Value:
UE_PRIVATE_LOGFMT_NAMED_FIELD ::UE::Logging::Private::CheckFieldName(Name), __VA_ARGS__
Definition at line 590 of file StructuredLog.h.
UE_PRIVATE_LOGFMT_STRIP_UE_PRIVATE_LOGFMT_NAMED_FIELD
#define UE_PRIVATE_LOGFMT_STRIP_UE_PRIVATE_LOGFMT_NAMED_FIELD
Definition at line 594 of file StructuredLog.h.
Function Documentation
SerializeForLog()
template<typename ValueType UE_REQUIRES> void SerializeForLog (FCbWriter & Writer, const TOptional< ValueType > & Optional) inline
Definition at line 314 of file StructuredLog.h.
References FCbWriter::BeginArray(), UE::CallSerializeForLog(), FCbWriter::EndArray(), and Optional.