Unreal Engine 5.6 C++ API: UE::Geometry::TSparseGrid3< ElemType > Class Template Reference
UE::Geometry::TSparseGrid3< ElemType > Class Template Reference
Dynamic sparse 3D grid.
#include "SparseGrid3.h"
Public Member Functions
TSparseGrid3 ()
Create empty grid.
TSparseGrid3 (const TSparseGrid3 &Other)=delete
TSparseGrid3 (TSparseGrid3 &&Other) noexcept
~TSparseGrid3 ()
Deletes all grid elements.
template<typename Func>
void AllocatedIteration (Func ElementFunc) const
Iterate over existing elements and apply ElementFunc(ElementType) to each of them.
bool Free (const FVector3i &Index)
Delete an element in the grid.
void FreeAll ()
Delete all elements in the grid.
const ElemType * Get (const FVector3i &Index) const
Get the grid element at this index.
ElemType * Get (const FVector3i &Index, bool bAllocateIfMissing)
Get the grid element at this index, and optionally allocate it if it doesn't exist.
FAxisAlignedBox3i GetBoundsInclusive () const
int GetCount () const
float GetDensity () const
FVector3i GetDimensions () const
bool Has (const FVector3i &Index) const
TSparseGrid3 & operator= (const TSparseGrid3 &Other)=delete
TSparseGrid3 & operator= (TSparseGrid3 &&Other) noexcept
template<typename Func>
void RangeIteration (FVector3i MinIndex, FVector3i MaxIndex, Func ElementFunc) const
Iterate over existing allocated elements within the integer bounds defined by Min and Max (inclusive), and apply ElementFunc(ElementType) to each of them.
Protected Member Functions
ElemType * Allocate (const FVector3i &index)
Protected Attributes
FAxisAlignedBox3i Bounds
accumulated bounds of all indices inserted into Elements.
TMap< FVector3i, ElemType * > Elements
sparse grid of allocated elements
Detailed Description
template<typename ElemType>
class UE::Geometry::TSparseGrid3< ElemType >
Dynamic sparse 3D grid.
Useful in cases where we have grid of some type of non-trivial object and we don't want to pre-allocate full grid of them. So we allocate on-demand. This can be used to implement multi-grid schemes, eg for example the ElemType could be sub-grid of fixed dimension.
Todo
support pooling/re-use of allocated elements? currently not required by any use cases.
port AllocatedIndices() and Allocated() iterators
Definition at line 26 of file SparseGrid3.h.
Constructor & Destructor Documentation
TSparseGrid3() [1/3]
template<typename ElemType> UE::Geometry::TSparseGrid3< ElemType >::TSparseGrid3 () inline
Create empty grid.
Definition at line 39 of file SparseGrid3.h.
References Bounds, and UE::Geometry::FAxisAlignedBox3i::Empty().
Referenced by TSparseGrid3(), TSparseGrid3(), operator=(), and operator=().
~TSparseGrid3()
template<typename ElemType> UE::Geometry::TSparseGrid3< ElemType >::~TSparseGrid3 () inline
Deletes all grid elements.
Definition at line 47 of file SparseGrid3.h.
References FreeAll().
TSparseGrid3() [2/3]
template<typename ElemType> UE::Geometry::TSparseGrid3< ElemType >::TSparseGrid3 (const TSparseGrid3< ElemType > & Other) delete
References TSparseGrid3(), and Other.
TSparseGrid3() [3/3]
template<typename ElemType> UE::Geometry::TSparseGrid3< ElemType >::TSparseGrid3 (TSparseGrid3< ElemType > && Other) inline noexcept
Definition at line 55 of file SparseGrid3.h.
References TSparseGrid3(), and Other.
Member Function Documentation
Allocate()
template<typename ElemType> ElemType * UE::Geometry::TSparseGrid3< ElemType >::Allocate (const FVector3i & index) inline protected
Definition at line 212 of file SparseGrid3.h.
References Bounds, and Elements.
Referenced by Get().
AllocatedIteration()
template<typename ElemType> template<typename Func> void UE::Geometry::TSparseGrid3< ElemType >::AllocatedIteration (Func ElementFunc) const inline
Iterate over existing elements and apply ElementFunc(ElementType) to each of them.
Definition at line 176 of file SparseGrid3.h.
References Elements.
Free()
template<typename ElemType> bool UE::Geometry::TSparseGrid3< ElemType >::Free (const FVector3i & Index) inline
Delete an element in the grid.
Parameters
Index integer grid index
Returns
true if the element existed, false if it did not
Definition at line 116 of file SparseGrid3.h.
References Elements.
FreeAll()
template<typename ElemType> void UE::Geometry::TSparseGrid3< ElemType >::FreeAll () inline
Delete all elements in the grid.
Definition at line 130 of file SparseGrid3.h.
References Elements.
Referenced by ~TSparseGrid3().
Get() [1/2]
template<typename ElemType> const ElemType * UE::Geometry::TSparseGrid3< ElemType >::Get (const FVector3i & Index) const inline
Get the grid element at this index.
Parameters
Index integer grid index
Returns
pointer to ElemType instance, or nullptr if element doesn't exist
Definition at line 85 of file SparseGrid3.h.
References Elements.
Get() [2/2]
template<typename ElemType> ElemType * UE::Geometry::TSparseGrid3< ElemType >::Get (const FVector3i & Index, bool bAllocateIfMissing) inline
Get the grid element at this index, and optionally allocate it if it doesn't exist.
Parameters
Index integer grid index
bAllocateIfMissing if the element at this index is null, allocate a new one
Returns
pointer to ElemType instance, or nullptr if element doesn't exist
Definition at line 97 of file SparseGrid3.h.
References Allocate(), and Elements.
GetBoundsInclusive()
template<typename ElemType> FAxisAlignedBox3i UE::Geometry::TSparseGrid3< ElemType >::GetBoundsInclusive () const inline
Returns
integer range of valid grid indices [min,max] (inclusive)
Definition at line 158 of file SparseGrid3.h.
References Bounds.
GetCount()
template<typename ElemType> int UE::Geometry::TSparseGrid3< ElemType >::GetCount () const inline
Returns
number of allocated elements in the grid
Definition at line 142 of file SparseGrid3.h.
References Elements.
GetDensity()
template<typename ElemType> float UE::Geometry::TSparseGrid3< ElemType >::GetDensity () const inline
Returns
ratio of allocated elements to total number of possible cells for current bounds
Definition at line 150 of file SparseGrid3.h.
References Bounds, Elements, and float.
GetDimensions()
template<typename ElemType> FVector3i UE::Geometry::TSparseGrid3< ElemType >::GetDimensions () const inline
Returns
dimensions of grid along each axis
Definition at line 166 of file SparseGrid3.h.
References Bounds, and UE::Geometry::FVector3i::One().
Has()
template<typename ElemType> bool UE::Geometry::TSparseGrid3< ElemType >::Has (const FVector3i & Index) const inline
Parameters
Index an integer grid index
Returns
true if there is an allocated element at this index
Definition at line 74 of file SparseGrid3.h.
References Elements.
operator=() [1/2]
template<typename ElemType> TSparseGrid3 & UE::Geometry::TSparseGrid3< ElemType >::operator= (const TSparseGrid3< ElemType > & Other) delete
References TSparseGrid3(), and Other.
operator=() [2/2]
template<typename ElemType> TSparseGrid3 & UE::Geometry::TSparseGrid3< ElemType >::operator= (TSparseGrid3< ElemType > && Other) inline noexcept
Definition at line 59 of file SparseGrid3.h.
References TSparseGrid3(), Bounds, Elements, MoveTemp(), and Other.
RangeIteration()
template<typename ElemType> template<typename Func> void UE::Geometry::TSparseGrid3< ElemType >::RangeIteration (FVector3i MinIndex, FVector3i MaxIndex, Func ElementFunc) const inline
Iterate over existing allocated elements within the integer bounds defined by Min and Max (inclusive), and apply ElementFunc(ElementType) to each of them.
Definition at line 190 of file SparseGrid3.h.
References Elements, Found, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Field Documentation
Bounds
template<typename ElemType> FAxisAlignedBox3i UE::Geometry::TSparseGrid3< ElemType >::Bounds protected
accumulated bounds of all indices inserted into Elements.
Not currently used internally.
Definition at line 32 of file SparseGrid3.h.
Referenced by TSparseGrid3(), Allocate(), GetBoundsInclusive(), GetDensity(), GetDimensions(), and operator=().
Elements
template<typename ElemType> TMap<FVector3i, ElemType*> UE::Geometry::TSparseGrid3< ElemType >::Elements protected
sparse grid of allocated elements
Definition at line 30 of file SparseGrid3.h.
Referenced by Allocate(), AllocatedIteration(), Free(), FreeAll(), Get(), Get(), GetCount(), GetDensity(), Has(), operator=(), and RangeIteration().
The documentation for this class was generated from the following file:
SparseGrid3.h