Unreal Engine 5.6 C++ API: IDisplayClusterScenePreview Class Reference
IDisplayClusterScenePreview Class Reference abstract
Interface for module containing tools for generation Display Cluster scene previews.
#include "IDisplayClusterScenePreview.h"
Public Member Functions
virtual ~IDisplayClusterScenePreview ()=default
virtual bool AddActorToRenderer (int32 RendererId, AActor *Actor)=0
Add an actor to the preview scene for a renderer.
virtual bool AddActorToRenderer (int32 RendererId, AActor *Actor, const TFunctionRef< bool(const UPrimitiveComponent *)> &PrimitiveFilter)=0
Add an actor to the preview scene for a renderer.
virtual bool ClearRendererScene (int32 RendererId)=0
Clear the scene of a renderer.
virtual int32 CreateRenderer ()=0
Create a preview renderer.
virtual bool DestroyRenderer (int32 RendererId)=0
Destroy a renderer, cleaning up all of its resources.
virtual bool GetActorsInRendererScene (int32 RendererId, bool bIncludeRoot, TArray< AActor * > &OutActors)=0
Get a list of all actors that have been added to a renderer's scene.
virtual ADisplayClusterRootActor * GetRendererRootActor (int32 RendererId)=0
Get the root actor of a renderer.
virtual ADisplayClusterRootActor * GetRendererRootActorOrProxy (int32 RendererId)=0
Get the root actor (or its proxy) of a renderer.
virtual bool IsRealTimePreviewEnabled () const =0
Check whether nDisplay preview textures are being updated in real time.
virtual bool RemoveActorFromRenderer (int32 RendererId, AActor *Actor)=0
Removes an actor from the preview scene for a renderer.
virtual bool Render (int32 RendererId, FDisplayClusterMeshProjectionRenderSettings &RenderSettings, FCanvas &Canvas)=0
Immediately render a preview.
virtual bool RenderQueued (int32 RendererId, FDisplayClusterMeshProjectionRenderSettings &RenderSettings, const FIntPoint &Size, FRenderResultDelegate ResultDelegate)=0
Queue a preview to be rendered in the future, automatically creating a canvas and render target.
virtual bool RenderQueued (int32 RendererId, FDisplayClusterMeshProjectionRenderSettings &RenderSettings, TWeakPtr< FCanvas > Canvas, FRenderResultDelegate ResultDelegate)=0
Queue a preview to be rendered in the future using an existing canvas.
virtual bool SetRendererActorSelectedDelegate (int32 RendererId, FDisplayClusterMeshProjectionRenderer::FSelection ActorSelectedDelegate)=0
Set the ActorSelectedDelegate of a renderer.
virtual bool SetRendererRenderSimpleElementsDelegate (int32 RendererId, FDisplayClusterMeshProjectionRenderer::FSimpleElementPass RenderSimpleElementsDelegate)=0
Set the RenderSimpleElementsDelegate of a renderer.
virtual bool SetRendererRootActor (int32 RendererId, ADisplayClusterRootActor *Actor, const FDisplayClusterRootActorPropertyOverrides &InPropertyOverrides, const EDisplayClusterScenePreviewFlags PreviewFlags=EDisplayClusterScenePreviewFlags::None)=0
Set the root DisplayCluster actor for the renderer with the given ID, which will be added to the preview scene and used to determine the render world.
virtual bool SetRendererRootActorPath (int32 RendererId, const FString &ActorPath, const FDisplayClusterRootActorPropertyOverrides &InPropertyOverrides, const EDisplayClusterScenePreviewFlags PreviewFlags=EDisplayClusterScenePreviewFlags::None)=0
Set the path of the ADisplayClusterRootActor actor for a renderer, which will be added to the preview scene and used to determine the render world.
UE_DEPRECATED (5.5, "This function has been deprecated. Use EDisplayClusterScenePreviewFlags.") virtual bool SetRendererRootActorPath(int32 RendererId
Set the path of the ADisplayClusterRootActor actor for a renderer, which will be added to the preview scene and used to determine the render world.
UE_DEPRECATED (5.5, "This function has been deprecated.") virtual bool SetRendererRootActor(int32 RendererId
Set the root DisplayCluster actor for the renderer with the given ID, which will be added to the preview scene and used to determine the render world.
UE_DEPRECATED (5.5, "This function has been deprecated.") virtual bool SetRendererUsePostProcessTexture(int32 RendererId
Set whether the renderer should use post-processed nDisplay preview textures.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayClusterScenePreview & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Data Fields
ADisplayClusterRootActor * Actor
const FString & ActorPath
const FString bool bAutoUpdateLightcards
ADisplayClusterRootActor bool bAutoUpdateLightcards
bool bUsePostProcessTexture
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayClusterScenePreview")
Detailed Description
Interface for module containing tools for generation Display Cluster scene previews.
Definition at line 21 of file IDisplayClusterScenePreview.h.
Constructor & Destructor Documentation
~IDisplayClusterScenePreview()
virtual IDisplayClusterScenePreview::~IDisplayClusterScenePreview () virtual default
Member Function Documentation
AddActorToRenderer() [1/2]
virtual bool IDisplayClusterScenePreview::AddActorToRenderer (int32 RendererId, AActor * Actor) pure virtual
Add an actor to the preview scene for a renderer.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
Actor The actor to add to the renderer's scene.
References Actor.
AddActorToRenderer() [2/2]
virtual bool IDisplayClusterScenePreview::AddActorToRenderer (int32 RendererId, AActor * Actor, const TFunctionRef< bool(const UPrimitiveComponent *)> & PrimitiveFilter) pure virtual
Add an actor to the preview scene for a renderer.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
Actor The actor to add to the renderer's scene.
PrimitiveFilter A custom filter used to determine which of the actor's primitives are added to the renderer's scene.
References Actor.
ClearRendererScene()
virtual bool IDisplayClusterScenePreview::ClearRendererScene (int32 RendererId) pure virtual
Clear the scene of a renderer.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
CreateRenderer()
virtual int32 IDisplayClusterScenePreview::CreateRenderer () pure virtual
Create a preview renderer.
Returns an index used to refer to this renderer in future API calls.
DestroyRenderer()
virtual bool IDisplayClusterScenePreview::DestroyRenderer (int32 RendererId) pure virtual
Destroy a renderer, cleaning up all of its resources.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
Get()
IDisplayClusterScenePreview & IDisplayClusterScenePreview::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 35 of file IDisplayClusterScenePreview.h.
References FModuleManager::GetModuleChecked(), and ModuleName.
GetActorsInRendererScene()
virtual bool IDisplayClusterScenePreview::GetActorsInRendererScene (int32 RendererId, bool bIncludeRoot, TArray< AActor * > & OutActors) pure virtual
Get a list of all actors that have been added to a renderer's scene.
This includes any actors that the renderer automatically added to itself.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
bIncludeRoot If true, include the renderer's root actor.
OutActors The array to fill with actors.
GetRendererRootActor()
virtual ADisplayClusterRootActor * IDisplayClusterScenePreview::GetRendererRootActor (int32 RendererId) pure virtual
Get the root actor of a renderer.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
GetRendererRootActorOrProxy()
virtual ADisplayClusterRootActor * IDisplayClusterScenePreview::GetRendererRootActorOrProxy (int32 RendererId) pure virtual
Get the root actor (or its proxy) of a renderer.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
IsAvailable()
bool IDisplayClusterScenePreview::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 45 of file IDisplayClusterScenePreview.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
IsRealTimePreviewEnabled()
virtual bool IDisplayClusterScenePreview::IsRealTimePreviewEnabled () const pure virtual
Check whether nDisplay preview textures are being updated in real time.
RemoveActorFromRenderer()
virtual bool IDisplayClusterScenePreview::RemoveActorFromRenderer (int32 RendererId, AActor * Actor) pure virtual
Removes an actor from the preview scene for a renderer.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
Actor The actor to remove to the renderer's scene.
References Actor.
Render()
virtual bool IDisplayClusterScenePreview::Render (int32 RendererId, FDisplayClusterMeshProjectionRenderSettings & RenderSettings, FCanvas & Canvas) pure virtual
Immediately render a preview.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
RenderSettings Settings controlling how the scene will be rendered.
Canvas The canvas to render to.
RenderQueued() [1/2]
virtual bool IDisplayClusterScenePreview::RenderQueued (int32 RendererId, FDisplayClusterMeshProjectionRenderSettings & RenderSettings, const FIntPoint & Size, FRenderResultDelegate ResultDelegate) pure virtual
Queue a preview to be rendered in the future, automatically creating a canvas and render target.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
RenderSettings Settings controlling how the scene will be rendered.
Size The size of the image to produce. Note that whenever this changes for a given renderer, the underlying RenderTarget will be resized, which has a performance cost.
ResultDelegate The delegate to call when the render is complete. It will be passed a FRenderTarget containing the rendered preview, or null if the render failed.
References TSequenceHistory< HistorySize >::Size.
RenderQueued() [2/2]
virtual bool IDisplayClusterScenePreview::RenderQueued (int32 RendererId, FDisplayClusterMeshProjectionRenderSettings & RenderSettings, TWeakPtr< FCanvas > Canvas, FRenderResultDelegate ResultDelegate) pure virtual
Queue a preview to be rendered in the future using an existing canvas.
The canvas must have a valid render target assigned.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
RenderSettings Settings controlling how the scene will be rendered.
Canvas The canvas to draw to. If this is invalid when the render is ready to start, the render will be skipped.
ResultDelegate The delegate to call when the render is complete. It will be passed a FRenderTarget containing the rendered preview, or null if the render failed.
SetRendererActorSelectedDelegate()
virtual bool IDisplayClusterScenePreview::SetRendererActorSelectedDelegate (int32 RendererId, FDisplayClusterMeshProjectionRenderer::FSelection ActorSelectedDelegate) pure virtual
Set the ActorSelectedDelegate of a renderer.
See FDisplayClusterMeshProjectionRenderer::ActorSelectedDelegate for more info.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
ActorSelectedDelegate The delegate to set on the renderer.
SetRendererRenderSimpleElementsDelegate()
virtual bool IDisplayClusterScenePreview::SetRendererRenderSimpleElementsDelegate (int32 RendererId, FDisplayClusterMeshProjectionRenderer::FSimpleElementPass RenderSimpleElementsDelegate) pure virtual
Set the RenderSimpleElementsDelegate of a renderer.
See FDisplayClusterMeshProjectionRenderer::RenderSimpleElementsDelegate for more info.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
RenderSimpleElementsDelegate The delegate to set on the renderer.
SetRendererRootActor()
virtual bool IDisplayClusterScenePreview::SetRendererRootActor (int32 RendererId, ADisplayClusterRootActor * Actor, const FDisplayClusterRootActorPropertyOverrides & InPropertyOverrides, const EDisplayClusterScenePreviewFlags PreviewFlags = EDisplayClusterScenePreviewFlags::None) pure virtual
Set the root DisplayCluster actor for the renderer with the given ID, which will be added to the preview scene and used to determine the render world.
Note that if the actor is destroyed (including by a recompile, reload, etc.), you will need to call this again to update the actor. This will also clear the path set by SetRendererRootActorPath.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
Actor The actor to preview.
InPropertyOverrides optional overrides for root actor
PreviewFlags Special flags that control the behavior of the renderer.
References Actor, and None.
SetRendererRootActorPath()
virtual bool IDisplayClusterScenePreview::SetRendererRootActorPath (int32 RendererId, const FString & ActorPath, const FDisplayClusterRootActorPropertyOverrides & InPropertyOverrides, const EDisplayClusterScenePreviewFlags PreviewFlags = EDisplayClusterScenePreviewFlags::None) pure virtual
Set the path of the ADisplayClusterRootActor actor for a renderer, which will be added to the preview scene and used to determine the render world.
Whenever a render is performed with this renderer, it will try to find the actor at that path and use it as the root.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
ActorPath The path of the ADisplayClusterRootActor actor to preview.
InPropertyOverrides optional overrides for root actor
PreviewFlags Special flags that control the behavior of the renderer.
References ActorPath, and None.
UE_DEPRECATED() [1/3]
IDisplayClusterScenePreview::UE_DEPRECATED (5. 5, "This function has been deprecated. Use EDisplayClusterScenePreviewFlags.")
Set the path of the ADisplayClusterRootActor actor for a renderer, which will be added to the preview scene and used to determine the render world.
Whenever a render is performed with this renderer, it will try to find the actor at that path and use it as the root.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
ActorPath The path of the ADisplayClusterRootActor actor to preview.
bAutoUpdateLightcards If true, the renderer scene will also be automatically populated with the actor's associated lightcards, including future changes to them.
UE_DEPRECATED() [2/3]
IDisplayClusterScenePreview::UE_DEPRECATED (5. 5, "This function has been deprecated.")
Set the root DisplayCluster actor for the renderer with the given ID, which will be added to the preview scene and used to determine the render world.
Note that if the actor is destroyed (including by a recompile, reload, etc.), you will need to call this again to update the actor. This will also clear the path set by SetRendererRootActorPath.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
Actor The actor to preview.
bAutoUpdateLightcards If true, the renderer scene will also be automatically populated with the actor's associated lightcards, including future changes to them.
UE_DEPRECATED() [3/3]
IDisplayClusterScenePreview::UE_DEPRECATED (5. 5, "This function has been deprecated.")
Set whether the renderer should use post-processed nDisplay preview textures.
Parameters
RendererId The ID of the renderer as returned from CreateRenderer.
bUsePostProcessTexture Whether to use post-processed nDisplay preview texture for future renders.
Field Documentation
Actor
ADisplayClusterRootActor* IDisplayClusterScenePreview::Actor
Definition at line 217 of file IDisplayClusterScenePreview.h.
Referenced by AddActorToRenderer(), AddActorToRenderer(), RemoveActorFromRenderer(), and SetRendererRootActor().
ActorPath
const FString& IDisplayClusterScenePreview::ActorPath
Definition at line 202 of file IDisplayClusterScenePreview.h.
Referenced by SetRendererRootActorPath().
bAutoUpdateLightcards [1/2]
const FString bool IDisplayClusterScenePreview::bAutoUpdateLightcards
Initial value:
= false)
    {
        return false;
    }
Definition at line 202 of file IDisplayClusterScenePreview.h.
bAutoUpdateLightcards [2/2]
ADisplayClusterRootActor bool IDisplayClusterScenePreview::bAutoUpdateLightcards
Initial value:
= false)
    {
        return false;
    }
Definition at line 217 of file IDisplayClusterScenePreview.h.
bUsePostProcessTexture
bool IDisplayClusterScenePreview::bUsePostProcessTexture
Initial value:
{
        return false
Definition at line 229 of file IDisplayClusterScenePreview.h.
ModuleName
const TCHAR* IDisplayClusterScenePreview::ModuleName = TEXT("DisplayClusterScenePreview") static constexpr
Definition at line 24 of file IDisplayClusterScenePreview.h.
Referenced by Get(), and IsAvailable().
The documentation for this class was generated from the following file:
IDisplayClusterScenePreview.h