Unreal Engine 5.6 C++ API: UEnvQueryGenerator_OnCircle Class Reference
UEnvQueryGenerator_OnCircle Class Reference
#include "EnvQueryGenerator_OnCircle.h"
Protected Member Functions
virtual AIMODULE_API void AddItemDataForCircle (uint8 *ContextRawData, UEnvQueryItemType *ContextItemType, const TArray< FNavLocation > &Locations, FEnvQueryInstance &OutQueryInstance) const
AIMODULE_API FVector CalcDirection (FEnvQueryInstance &QueryInstance) const
AIMODULE_API void GenerateItemsForCircle (uint8 *ContextRawData, UEnvQueryItemType *ContextItemType, const FVector &CenterLocation, const FVector &StartDirection, const TArray< AActor * > &IgnoredActors, int32 StepsCount, float AngleStep, FEnvQueryInstance &OutQueryInstance) const
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() FAIDataProviderFloatValue CircleRadius
max distance of path between point and context
virtual AIMODULE_API void GenerateItems (FEnvQueryInstance &QueryInstance) const override
virtual AIMODULE_API FText GetDescriptionDetails () const override
virtual AIMODULE_API FText GetDescriptionTitle () const override
virtual AIMODULE_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
UPROPERTY()) uint32 bDefineArc virtual AIMODULE_API void PostLoad () override
UPROPERTY () bool bIgnoreAnyContextActorsWhenGeneratingCircle
ignore tracing into context actors when generating the circle
UPROPERTY () EPointOnCircleSpacingMethod PointOnCircleSpacingMethod
how we are choosing where the points are in the circle
UPROPERTY () FAIDataProviderFloatValue ArcAngle
If you generate items on a piece of circle you define angle of Arc cut here.
UPROPERTY () FAIDataProviderFloatValue ArcDirectionOffsetDegrees
Offsets the ArcDirection and starts generating points this many degrees clock-wise around the vertical axis.
UPROPERTY () FAIDataProviderFloatValue CircleCenterZOffset
context offset
UPROPERTY () FEnvTraceData TraceData
horizontal trace for nearest obstacle
UPROPERTY () TSubclassOf< class UEnvQueryContext > CircleCenter
context
UPROPERTY ()) FAIDataProviderFloatValue SpaceBetween
items will be generated on a circle this much apart
UPROPERTY ()) FAIDataProviderIntValue NumberOfPoints
this many items will be generated on a circle
UPROPERTY ()) FEnvDirection ArcDirection
If you generate items on a piece of circle you define direction of Arc cut here.
Detailed Description
Definition at line 25 of file EnvQueryGenerator_OnCircle.h.
Member Function Documentation
AddItemDataForCircle()
virtual AIMODULE_API void UEnvQueryGenerator_OnCircle::AddItemDataForCircle (uint8 * ContextRawData, UEnvQueryItemType * ContextItemType, const TArray< FNavLocation > & Locations, FEnvQueryInstance & OutQueryInstance) const protected virtual
CalcDirection()
AIMODULE_API FVector UEnvQueryGenerator_OnCircle::CalcDirection (FEnvQueryInstance & QueryInstance) const protected
References FVector.
GENERATED_UCLASS_BODY()
UEnvQueryGenerator_OnCircle::GENERATED_UCLASS_BODY () private
max distance of path between point and context
References Category, and UPROPERTY().
GenerateItems()
virtual AIMODULE_API void UEnvQueryGenerator_OnCircle::GenerateItems (FEnvQueryInstance & QueryInstance) const override private virtual
References GenerateItems().
Referenced by GenerateItems().
GenerateItemsForCircle()
AIMODULE_API void UEnvQueryGenerator_OnCircle::GenerateItemsForCircle (uint8 * ContextRawData, UEnvQueryItemType * ContextItemType, const FVector & CenterLocation, const FVector & StartDirection, const TArray< AActor * > & IgnoredActors, int32 StepsCount, float AngleStep, FEnvQueryInstance & OutQueryInstance) const protected
References FVector.
GetDescriptionDetails()
virtual AIMODULE_API FText UEnvQueryGenerator_OnCircle::GetDescriptionDetails () const override private virtual
References GetDescriptionDetails().
Referenced by GetDescriptionDetails().
GetDescriptionTitle()
virtual AIMODULE_API FText UEnvQueryGenerator_OnCircle::GetDescriptionTitle () const override private virtual
References GetDescriptionTitle().
Referenced by GetDescriptionTitle().
PostEditChangeProperty()
virtual AIMODULE_API void UEnvQueryGenerator_OnCircle::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostLoad()
UPROPERTY()) uint32 bDefineArc virtual AIMODULE_API void UEnvQueryGenerator_OnCircle::PostLoad () override private virtual
References PostLoad().
Referenced by PostLoad().
UPROPERTY() [1/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
ignore tracing into context actors when generating the circle
References Category, and UPROPERTY().
UPROPERTY() [2/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
how we are choosing where the points are in the circle
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
If you generate items on a piece of circle you define angle of Arc cut here.
References Category, and UPROPERTY().
UPROPERTY() [4/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
Offsets the ArcDirection and starts generating points this many degrees clock-wise around the vertical axis.
References Category, and UPROPERTY().
UPROPERTY() [5/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
context offset
References Category, and UPROPERTY().
UPROPERTY() [6/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
horizontal trace for nearest obstacle
References Category, meta, and UPROPERTY().
UPROPERTY() [7/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
context
References Category, and UPROPERTY().
UPROPERTY() [8/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
items will be generated on a circle this much apart
References Category, meta, and UPROPERTY().
UPROPERTY() [9/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
this many items will be generated on a circle
References Category, meta, and UPROPERTY().
UPROPERTY() [10/10]
UEnvQueryGenerator_OnCircle::UPROPERTY () private
If you generate items on a piece of circle you define direction of Arc cut here.
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
EnvQueryGenerator_OnCircle.h