Unreal Engine 5.6 C++ API: FixedTagPrivate Namespace Reference
FixedTagPrivate Namespace Reference
Data Structures
class FAsyncStoreLoader
Loads tag store with async creation of expensive tag values.
struct FLegacyAssetRegistryExportPath
struct FMapHandle
class FMarshalledText
The AssetRegistry's representation of an FText AssetData Tag value.
struct FNumberedPair
struct FNumberlessExportPath
struct FNumberlessPair
struct FOptions
struct FPartialMapHandle
struct FStore
Stores a fixed set of values and all the key-values maps used for lookup.
class FStoreBuilder
struct FStoreData
struct FValueHandle
struct FValueId
Enumerations
enum class ELoadOrder { Member , TextFirst }
Functions
uint32 GetTypeHash (const FNumberlessExportPath &Export)
uint32 HashCaseSensitive (const TCHAR *Str, int32 Len)
uint32 HashCaseSensitive (const UTF8CHAR *Str, int32 Len)
uint32 HashCombineQuick (uint32 A, uint32 B)
uint32 HashCombineQuick (uint32 A, uint32 B, uint32 C)
TRefCountPtr< const FStore > LoadStore (FArchive &Ar, FAssetRegistryVersion::Type Version=FAssetRegistryVersion::LatestVersion)
bool operator== (const FNumberlessExportPath &A, const FNumberlessExportPath &B)
void SaveStore (const FStoreData &Store, FArchive &Ar)
Enumeration Type Documentation
ELoadOrder
enum class FixedTagPrivate::ELoadOrder strong
Enumerator
Member
TextFirst
Definition at line 255 of file AssetDataTagMapSerializationDetails.h.
Function Documentation
GetTypeHash()
uint32 FixedTagPrivate::GetTypeHash (const FNumberlessExportPath & Export)
Referenced by FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash(), and FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash().
HashCaseSensitive() [1/2]
uint32 FixedTagPrivate::HashCaseSensitive (const TCHAR * Str, int32 Len)
Referenced by FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash(), and FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash().
HashCaseSensitive() [2/2]
uint32 FixedTagPrivate::HashCaseSensitive (const UTF8CHAR * Str, int32 Len)
HashCombineQuick() [1/2]
uint32 FixedTagPrivate::HashCombineQuick (uint32 A, uint32 B)
References A, and B.
Referenced by FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash(), FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash(), and FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash().
HashCombineQuick() [2/2]
uint32 FixedTagPrivate::HashCombineQuick (uint32 A, uint32 B, uint32 C)
References A, and B.
LoadStore()
TRefCountPtr< const FStore > FixedTagPrivate::LoadStore (FArchive & Ar, FAssetRegistryVersion::Type Version = FAssetRegistryVersion::LatestVersion)
References Ar, and FAssetRegistryVersion::LatestVersion.
operator==()
bool FixedTagPrivate::operator== (const FNumberlessExportPath & A, const FNumberlessExportPath & B)
References A, and B.
SaveStore()
void FixedTagPrivate::SaveStore (const FStoreData & Store, FArchive & Ar)
References Ar.