Unreal Engine 5.6 C++ API: UBillboardComponent Class Reference
UBillboardComponent Class Reference
#include "BillboardComponent.h"
Private Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual bool ComponentIsTouchingSelectionBox (const FBox &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual bool ComponentIsTouchingSelectionFrustum (const FConvexVolume &InFrustum, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UTexture2D > Sprite
virtual bool IsShown (const FEngineShowFlags &ShowFlags) const override
UFUNCTION () 1 virtual void SetSprite(class UTexture2D *NewSprite)
Change the sprite texture used by this component.
UFUNCTION () 1 virtual void SetSpriteAndUV(class UTexture2D *NewSprite
Change the sprite texture and the UV's used by this component.
UFUNCTION () 1 virtual void SetUV(int32 NewU
Change the sprite's UVs.
UFUNCTION () 1 void SetOpacityMaskRefVal(float RefVal)
Changed the opacity masked used by this component.
UPROPERTY () float OpacityMaskRefVal
The billboard is not rendered where texture opacity < OpacityMaskRefVal.
UPROPERTY() uint32 bIsScreenSizeScaled UPROPERTY () float ScreenSize
UPROPERTY () float U
UPROPERTY () float UL
UPROPERTY () float V
UPROPERTY () float VL
Private Attributes
int32 NewU
int32 NewUL
int32 int32 NewUL
int32 int32 NewV
int32 int32 int32 NewV
int32 int32 int32 NewVL
int32 int32 int32 int32 NewVL
Detailed Description
Definition at line 19 of file BillboardComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UBillboardComponent::CalcBounds (const FTransform & LocalToWorld) const override private virtual
References CalcBounds().
Referenced by CalcBounds().
ComponentIsTouchingSelectionBox()
virtual bool UBillboardComponent::ComponentIsTouchingSelectionBox (const FBox & InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override private virtual
ComponentIsTouchingSelectionFrustum()
virtual bool UBillboardComponent::ComponentIsTouchingSelectionFrustum (const FConvexVolume & InFrustum, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override private virtual
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UBillboardComponent::CreateSceneProxy () override private virtual
References CreateSceneProxy().
Referenced by CreateSceneProxy().
GENERATED_UCLASS_BODY()
UBillboardComponent::GENERATED_UCLASS_BODY () private
References Category, and UPROPERTY().
IsShown()
virtual bool UBillboardComponent::IsShown (const FEngineShowFlags & ShowFlags) const override private virtual
References IsShown().
Referenced by IsShown().
UFUNCTION() [1/4]
UBillboardComponent::UFUNCTION () private
Change the sprite texture used by this component.
References Category.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/4]
UBillboardComponent::UFUNCTION () private
Change the sprite texture and the UV's used by this component.
References Category, and UFUNCTION().
UFUNCTION() [3/4]
UBillboardComponent::UFUNCTION () private
Change the sprite's UVs.
References Category, and UFUNCTION().
UFUNCTION() [4/4]
UBillboardComponent::UFUNCTION () private
Changed the opacity masked used by this component.
References Category, and UFUNCTION().
UPROPERTY() [1/6]
UBillboardComponent::UPROPERTY () private
The billboard is not rendered where texture opacity < OpacityMaskRefVal.
References Category, and UPROPERTY().
UPROPERTY() [2/6]
UPROPERTY() uint32 bIsScreenSizeScaled UBillboardComponent::UPROPERTY () private
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/6]
UBillboardComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [4/6]
UBillboardComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [5/6]
UBillboardComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [6/6]
UBillboardComponent::UPROPERTY () private
References Category, and UPROPERTY().
Field Documentation
NewU
int32 UBillboardComponent::NewU private
Definition at line 74 of file BillboardComponent.h.
NewUL [1/2]
int32 UBillboardComponent::NewUL private
Definition at line 70 of file BillboardComponent.h.
NewUL [2/2]
int32 int32 UBillboardComponent::NewUL private
Definition at line 74 of file BillboardComponent.h.
NewV [1/2]
int32 int32 UBillboardComponent::NewV private
Definition at line 70 of file BillboardComponent.h.
NewV [2/2]
int32 int32 int32 UBillboardComponent::NewV private
Definition at line 74 of file BillboardComponent.h.
NewVL [1/2]
int32 int32 int32 UBillboardComponent::NewVL private
Definition at line 70 of file BillboardComponent.h.
NewVL [2/2]
int32 int32 int32 int32 UBillboardComponent::NewVL private
Definition at line 74 of file BillboardComponent.h.
The documentation for this class was generated from the following file:
BillboardComponent.h