Unreal Engine 5.6 C++ API: UE::Geometry::TSphere3< T > Struct Template Reference
UE::Geometry::TSphere3< T > Struct Template Reference
#include "SphereTypes.h"
Public Member Functions
TSphere3 ()=default
TSphere3 (const TVector< T > &CenterIn, T RadiusIn)
T Area () const
T Circumference () const
bool Contains (const TSphere3< T > &OtherSphere) const
bool Contains (const TVector< T > &Point) const
T Diameter () const
T DistanceSquared (const TVector< T > &Point) const
T SignedDistance (const TVector< T > &Point) const
T Volume () const
Static Public Member Functions
static T Area (T Radius)
static T Volume (T Radius)
Data Fields
TVector< T > Center = TVector<T>::Zero()
Center of the sphere.
T Radius = (T)0
Radius of the sphere.
Detailed Description
template<typename T>
struct UE::Geometry::TSphere3< T >
Definition at line 19 of file SphereTypes.h.
Constructor & Destructor Documentation
TSphere3() [1/2]
template<typename T> UE::Geometry::TSphere3< T >::TSphere3 () default
TSphere3() [2/2]
template<typename T> UE::Geometry::TSphere3< T >::TSphere3 (const TVector< T > & CenterIn, T RadiusIn) inline
Definition at line 29 of file SphereTypes.h.
Member Function Documentation
Area() [1/2]
template<typename T> T UE::Geometry::TSphere3< T >::Area () const inline
Returns
Area of sphere
Definition at line 45 of file SphereTypes.h.
Referenced by UE::Geometry::TSphere3< float >::Area().
Area() [2/2]
template<typename T> T UE::Geometry::TSphere3< T >::Area (T Radius) inline static
Returns
Area of sphere with given Radius
Definition at line 94 of file SphereTypes.h.
Circumference()
template<typename T> T UE::Geometry::TSphere3< T >::Circumference () const inline
Returns
Circumference of sphere
Definition at line 39 of file SphereTypes.h.
Contains() [1/2]
template<typename T> bool UE::Geometry::TSphere3< T >::Contains (const TSphere3< T > & OtherSphere) const inline
Returns
true if Sphere contains given OtherSphere
Definition at line 64 of file SphereTypes.h.
Contains() [2/2]
template<typename T> bool UE::Geometry::TSphere3< T >::Contains (const TVector< T > & Point) const inline
Returns
true if Sphere contains given Point
Definition at line 57 of file SphereTypes.h.
Referenced by UE::Geometry::IsInside().
Diameter()
template<typename T> T UE::Geometry::TSphere3< T >::Diameter () const inline
Returns
Diameter of sphere
Definition at line 33 of file SphereTypes.h.
DistanceSquared()
template<typename T> T UE::Geometry::TSphere3< T >::DistanceSquared (const TVector< T > & Point) const inline
Returns
minimum squared distance from Point to Sphere surface for points outside sphere, 0 for points inside
Definition at line 74 of file SphereTypes.h.
SignedDistance()
template<typename T> T UE::Geometry::TSphere3< T >::SignedDistance (const TVector< T > & Point) const inline
Returns
signed distance from Point to Sphere surface. Points inside sphere return negative distance.
Definition at line 83 of file SphereTypes.h.
Referenced by UE::Geometry::TSphere3< float >::DistanceSquared().
Volume() [1/2]
template<typename T> T UE::Geometry::TSphere3< T >::Volume () const inline
Returns
Volume of sphere
Definition at line 51 of file SphereTypes.h.
Referenced by UE::Geometry::TSphere3< float >::Volume().
Volume() [2/2]
template<typename T> T UE::Geometry::TSphere3< T >::Volume (T Radius) inline static
Returns
Volume of sphere with given Radius
Definition at line 100 of file SphereTypes.h.
Field Documentation
Center
template<typename T> TVector<T> UE::Geometry::TSphere3< T >::Center = TVector<T>::Zero()
Center of the sphere.
Definition at line 23 of file SphereTypes.h.
Referenced by UE::Geometry::TSphere3< float >::Contains(), UE::Geometry::GetShape(), and UE::Geometry::IsInside().
Radius
template<typename T> T UE::Geometry::TSphere3< T >::Radius = (T)0
Radius of the sphere.
Definition at line 25 of file SphereTypes.h.
Referenced by UE::Geometry::TSphere3< float >::Contains(), UE::Geometry::GetShape(), and UE::Geometry::IsInside().
The documentation for this struct was generated from the following files:
ContainmentQueries3.h
SphereTypes.h