Unreal Engine 5.6 C++ API: FSuspensionSimModule Class Reference
FSuspensionSimModule Class Reference
#include "SuspensionSimModule.h"
Public Member Functions
CHAOSMODULARVEHICLEENGINE_API FSuspensionSimModule (const FSuspensionSettings &Settings)
virtual CHAOSMODULARVEHICLEENGINE_API ~FSuspensionSimModule () override
virtual CHAOSMODULARVEHICLEENGINE_API void Animate () override
DEFINE_CHAOSSIMTYPENAME (FSuspensionSimModule)
virtual TSharedPtr< Chaos::FModuleNetData > GenerateNetData (const int32 SimArrayIndex) const override
virtual Chaos::FSimOutputData * GenerateOutputData () const override
virtual const FString GetDebugName () const
virtual float GetMaxSpringLength () const override
const FVector & GetRestLocation () const
virtual CHAOSMODULARVEHICLEENGINE_API float GetSpringLength () const override
virtual CHAOSMODULARVEHICLEENGINE_API void GetWorldRaycastLocation (const FTransform &BodyTransform, float WheelRadius, Chaos::FSpringTrace &OutTrace) override
virtual CHAOSMODULARVEHICLEENGINE_API void OnConstruction_External (const Chaos::FPhysicsObjectHandle &PhysicsObject) override
virtual CHAOSMODULARVEHICLEENGINE_API void OnTermination_External () override
virtual CHAOSMODULARVEHICLEENGINE_API void SetSpringLength (float InLength, float WheelRadius) override
virtual CHAOSMODULARVEHICLEENGINE_API void Simulate (float DeltaTime, const Chaos::FAllInputs &Inputs, Chaos::FSimModuleTree &VehicleModuleSystem) override
CHAOSMODULARVEHICLEENGINE_API void UpdateConstraint ()
Protected Member Functions
CHAOSMODULARVEHICLEENGINE_API void CreateConstraint (const Chaos::FPhysicsObjectHandle &PhysicsObject)
CHAOSMODULARVEHICLEENGINE_API void DestroyConstraint ()
Private Attributes
FPhysicsConstraintHandle ConstraintHandle
friend FSuspensionOutputData
friend FSuspensionSimModuleData
float LastDisplacement
float SpringDisplacement
float SpringSpeed
Detailed Description
Definition at line 113 of file SuspensionSimModule.h.
Constructor & Destructor Documentation
FSuspensionSimModule()
CHAOSMODULARVEHICLEENGINE_API FSuspensionSimModule::FSuspensionSimModule (const FSuspensionSettings & Settings)
References UE_API.
Referenced by DEFINE_CHAOSSIMTYPENAME().
~FSuspensionSimModule()
virtual CHAOSMODULARVEHICLEENGINE_API FSuspensionSimModule::~FSuspensionSimModule () override virtual
References UE_API.
Member Function Documentation
Animate()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::Animate () override virtual
References UE_API.
CreateConstraint()
CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::CreateConstraint (const Chaos::FPhysicsObjectHandle & PhysicsObject) protected
References UE_API.
DEFINE_CHAOSSIMTYPENAME()
FSuspensionSimModule::DEFINE_CHAOSSIMTYPENAME (FSuspensionSimModule)
References FSuspensionSimModule().
DestroyConstraint()
CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::DestroyConstraint () protected
References UE_API.
GenerateNetData()
virtual TSharedPtr< Chaos::FModuleNetData > FSuspensionSimModule::GenerateNetData (const int32 SimArrayIndex) const inline override virtual
Definition at line 125 of file SuspensionSimModule.h.
References GetDebugName(), MakeShared(), and UE_BUILD_TEST.
GenerateOutputData()
virtual Chaos::FSimOutputData * FSuspensionSimModule::GenerateOutputData () const inline override virtual
Definition at line 137 of file SuspensionSimModule.h.
References FSuspensionOutputData::MakeNew().
GetDebugName()
virtual const FString FSuspensionSimModule::GetDebugName () const inline virtual
Definition at line 142 of file SuspensionSimModule.h.
References TEXT.
Referenced by GenerateNetData().
GetMaxSpringLength()
virtual float FSuspensionSimModule::GetMaxSpringLength () const inline override virtual
Definition at line 144 of file SuspensionSimModule.h.
GetRestLocation()
const FVector & FSuspensionSimModule::GetRestLocation () const inline
Definition at line 156 of file SuspensionSimModule.h.
References FVector.
GetSpringLength()
virtual CHAOSMODULARVEHICLEENGINE_API float FSuspensionSimModule::GetSpringLength () const override virtual
References UE_API.
GetWorldRaycastLocation()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::GetWorldRaycastLocation (const FTransform & BodyTransform, float WheelRadius, Chaos::FSpringTrace & OutTrace) override virtual
References UE_API.
OnConstruction_External()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::OnConstruction_External (const Chaos::FPhysicsObjectHandle & PhysicsObject) override virtual
References UE_API.
OnTermination_External()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::OnTermination_External () override virtual
References UE_API.
SetSpringLength()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::SetSpringLength (float InLength, float WheelRadius) override virtual
References UE_API.
Simulate()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::Simulate (float DeltaTime, const Chaos::FAllInputs & Inputs, Chaos::FSimModuleTree & VehicleModuleSystem) override virtual
References DeltaTime, and UE_API.
UpdateConstraint()
CHAOSMODULARVEHICLEENGINE_API void FSuspensionSimModule::UpdateConstraint ()
References UE_API.
Field Documentation
ConstraintHandle
FPhysicsConstraintHandle FSuspensionSimModule::ConstraintHandle private
Definition at line 170 of file SuspensionSimModule.h.
FSuspensionOutputData
friend FSuspensionSimModule::FSuspensionOutputData private
Definition at line 119 of file SuspensionSimModule.h.
FSuspensionSimModuleData
friend FSuspensionSimModule::FSuspensionSimModuleData private
Definition at line 118 of file SuspensionSimModule.h.
LastDisplacement
float FSuspensionSimModule::LastDisplacement private
Definition at line 167 of file SuspensionSimModule.h.
SpringDisplacement
float FSuspensionSimModule::SpringDisplacement private
Definition at line 166 of file SuspensionSimModule.h.
SpringSpeed
float FSuspensionSimModule::SpringSpeed private
Definition at line 168 of file SuspensionSimModule.h.
The documentation for this class was generated from the following file:
SuspensionSimModule.h