Unreal Engine 5.6 C++ API: FSCSEditorTreeNode Class Reference
FSCSEditorTreeNode Class Reference abstract
FSCSEditorTreeNode.
#include "SSCSEditor.h"
Public Types
enum ENodeType { ComponentNode , RootActorNode , SeparatorNode , ChildActorNode }
Public Member Functions
FSCSEditorTreeNode (FSCSEditorTreeNode::ENodeType InNodeType)
Constructs an empty tree node.
virtual ~FSCSEditorTreeNode ()
virtual void AddChild (FSCSEditorTreeNodePtrType InChildNodePtr)
Adds the given node as a child node.
FSCSEditorTreeNodePtrType AddChild (USCS_Node *InSCSNode, bool bIsInheritedSCS)
Adds a child node for the given SCS node.
FSCSEditorTreeNodePtrType AddChildFromComponent (UActorComponent *InComponentTemplate)
Adds a child node for the given component template.
virtual bool CanDelete () const
virtual bool CanEdit () const
virtual bool CanRename () const
virtual bool CanReparent () const
void CloseOngoingCreateTransaction ()
Ends the 'Create + enter initial name' transaction of this node.
DECLARE_DELEGATE (FOnRenameRequested)
Delegate for when the context menu requests a rename.
FSCSEditorTreeNodePtrType FindChild (const FName &InVariableOrInstanceName, bool bRecursiveSearch=false, uint32 *OutDepth=NULL) const
Attempts to find a reference to the child node that matches the given component variable or instance name.
FSCSEditorTreeNodePtrType FindChild (const UActorComponent *InComponentTemplate, bool bRecursiveSearch=false, uint32 *OutDepth=NULL) const
Attempts to find a reference to the child node that matches the given component template.
FSCSEditorTreeNodePtrType FindChild (const USCS_Node *InSCSNode, bool bRecursiveSearch=false, uint32 *OutDepth=NULL) const
Attempts to find a reference to the child node that matches the given SCS node.
FSCSEditorTreeNodePtrType FindClosestParent (TArray< FSCSEditorTreeNodePtrType > InNodes)
Finds the closest ancestor node in the given node set.
virtual UActorComponent * FindComponentInstanceInActor (const AActor *InActor) const
Finds the component instance represented by this node contained within a given Actor instance.
FSCSEditorActorNodePtrType GetActorRootNode () const
virtual UBlueprint * GetBlueprint () const =0
virtual FSCSEditorChildActorNodePtrType GetChildActorNode ()
Returns the associated child actor node if applicable to this node type.
const TArray< FSCSEditorTreeNodePtrType > & GetChildren () const
UActorComponent * GetComponentTemplate (bool bEvenIfPendingKill=false) const
virtual FText GetDisplayName () const
virtual FString GetDisplayString () const
template<class T>
T * GetEditableObjectForBlueprint (UBlueprint *InBlueprint) const
virtual FName GetNodeID () const
ENodeType GetNodeType () const
template<class T>
const T * GetObject (bool bEvenIfPendingKill=false) const
UActorComponent * GetOrCreateEditableComponentTemplate (UBlueprint *ActualEditedBlueprint) const
FSCSEditorTreeNodePtrType GetParent () const
virtual class USCS_Node * GetSCSNode () const
virtual FName GetVariableName () const
bool IsActorNode () const
bool IsAttachedTo (FSCSEditorTreeNodePtrType InNodePtr) const
bool IsBlueprintComponent () const
bool IsComponentNode () const
virtual bool IsDefaultSceneRoot () const
bool IsDirectlyAttachedTo (FSCSEditorTreeNodePtrType InNodePtr) const
virtual bool IsFlaggedForFiltration () const
Query that determines if this item should be filtered out or not.
virtual bool IsInheritedComponent () const
virtual bool IsInheritedSCSNode () const
virtual bool IsInstanced () const
bool IsInstancedActor () const
bool IsInstancedComponent () const
virtual bool IsNativeComponent () const
virtual bool IsRootComponent () const
bool IsSceneComponent () const
virtual bool IsUserInstancedComponent () const
virtual bool MatchesFilterType (const UClass *InFilterType) const
Returns whether the node will match the given type (for filtering)
virtual void OnCompleteRename (const FText &InNewName)
Renames the object or variable represented by this node.
void OnRequestRename (TUniquePtr< FScopedTransaction > OngoingCreateTransaction)
Requests a rename on the node.
virtual bool RefreshFilteredState (const UClass *InFilterType, const TArray< FString > &InFilterTerms, bool bRecursive)
Refreshes this item's filtration state.
virtual void RemoveChild (FSCSEditorTreeNodePtrType InChildNodePtr)
Removes the given node from the list of child nodes.
void SetActorRootNode (FSCSEditorActorNodePtrType InActorNode)
Sets the actor root to the given node for this node along with any children.
void SetObject (UObject *InObject)
Sets the internal object instance represented by this node.
void SetRenameRequestedDelegate (FOnRenameRequested InRenameRequested)
Sets up the delegate for a rename operation.
Public Member Functions inherited from TSharedFromThis< FSCSEditorTreeNode >
TSharedRef< FSCSEditorTreeNode, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FSCSEditorTreeNode, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static FSCSEditorTreeNodePtrType FactoryNodeFromComponent (UActorComponent *InComponent)
Creates the correct type of node based on the component (instanced or not, etc...)
static USCS_Node * FindSCSNodeForInstance (const UActorComponent *InstanceComponent, UClass *ClassToSearch)
Protected Member Functions
void ApplyFilteredStateToParent ()
Used to update the EFilteredState::ChildMatches flag for parent nodes, when this item's filtration state has changed.
template<class T>
T * GetMutableObject () const
virtual UObject * GetOrCreateEditableObjectForBlueprint (UBlueprint *InBlueprint) const
void RefreshCachedChildFilterState (bool bUpdateParent)
Updates the EFilteredState::ChildMatches flag, based off of children's current state.
virtual void RemoveMeAsChild ()
void SetCachedFilterState (bool bMatchesFilter, bool bUpdateParent)
Sets this item's filtration state.
Protected Member Functions inherited from TSharedFromThis< FSCSEditorTreeNode >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TUniquePtr< FScopedTransaction > OngoingCreateTransaction
Private Types
enum EFilteredState {
FilteredOut = 0x00 , MatchesFilter = (1 << 0) , ChildMatches = (1 << 1) , FilteredInMask = (MatchesFilter | ChildMatches) ,
Unknown = 0xFC
}
Private Attributes
FSCSEditorActorNodePtrType ActorRootNodePtr
TArray< FSCSEditorTreeNodePtrType > Children
uint8 FilterFlags
ENodeType NodeType
FSCSEditorTreeNodePtrType ParentNodePtr
FOnRenameRequested RenameRequestedDelegate
Handles rename requests.
TWeakObjectPtr< UObject > WeakObjectPtr
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FSCSEditorTreeNode >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
FSCSEditorTreeNode.
Wrapper class for nodes displayed in the SCS (Simple Construction Script) editor tree widget.
Definition at line 96 of file SSCSEditor.h.
Member Enumeration Documentation
EFilteredState
enum FSCSEditorTreeNode::EFilteredState private
Enumerator
FilteredOut
MatchesFilter
ChildMatches
FilteredInMask
Unknown
Definition at line 489 of file SSCSEditor.h.
ENodeType
enum FSCSEditorTreeNode::ENodeType
Enumerator
ComponentNode
RootActorNode
SeparatorNode
ChildActorNode
Definition at line 102 of file SSCSEditor.h.
Constructor & Destructor Documentation
FSCSEditorTreeNode()
FSCSEditorTreeNode::FSCSEditorTreeNode (FSCSEditorTreeNode::ENodeType InNodeType)
Constructs an empty tree node.
Referenced by FSCSEditorTreeNodeActorBase::FSCSEditorTreeNodeActorBase(), FSCSEditorTreeNodeComponentBase::FSCSEditorTreeNodeComponentBase(), and FSCSEditorTreeNodeSeparator::FSCSEditorTreeNodeSeparator().
~FSCSEditorTreeNode()
virtual FSCSEditorTreeNode::~FSCSEditorTreeNode () inline virtual
Definition at line 327 of file SSCSEditor.h.
Member Function Documentation
AddChild() [1/2]
virtual void FSCSEditorTreeNode::AddChild (FSCSEditorTreeNodePtrType InChildNodePtr) virtual
Adds the given node as a child node.
Parameters
InChildNodePtr The node to add as a child node.
Reimplemented in FSCSEditorTreeNodeActorBase, and FSCSEditorTreeNodeRootActor.
AddChild() [2/2]
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::AddChild (USCS_Node * InSCSNode, bool bIsInheritedSCS)
Adds a child node for the given SCS node.
Parameters
InSCSNode The SCS node to for which to create a child node.
bIsInheritedSCS Whether or not the given SCS node is inherited from a parent.
Returns
A reference to the new child node or the existing child node if a match is found.
AddChildFromComponent()
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::AddChildFromComponent (UActorComponent * InComponentTemplate)
Adds a child node for the given component template.
Parameters
InComponentTemplate The component template for which to create a child node.
Returns
A reference to the new child node or the existing child node if a match is found.
ApplyFilteredStateToParent()
void FSCSEditorTreeNode::ApplyFilteredStateToParent () protected
Used to update the EFilteredState::ChildMatches flag for parent nodes, when this item's filtration state has changed.
CanDelete()
virtual bool FSCSEditorTreeNode::CanDelete () const inline virtual
Returns
Whether or not this object represents a node that can be deleted from the SCS tree.
Reimplemented in FSCSEditorTreeNodeComponentBase.
Definition at line 421 of file SSCSEditor.h.
CanEdit()
virtual bool FSCSEditorTreeNode::CanEdit () const inline virtual
Returns
Whether or not we can edit properties for the object represented by this node.
Reimplemented in FSCSEditorTreeNodeActorBase, FSCSEditorTreeNodeComponent, FSCSEditorTreeNodeInstanceAddedComponent, and FSCSEditorTreeNodeInstancedInheritedComponent.
Definition at line 431 of file SSCSEditor.h.
CanRename()
virtual bool FSCSEditorTreeNode::CanRename () const inline virtual
Returns
Whether or not we can rename the object or variable represented by this node.
Reimplemented in FSCSEditorTreeNodeComponentBase, and FSCSEditorTreeNodeRootActor.
Definition at line 436 of file SSCSEditor.h.
CanReparent()
virtual bool FSCSEditorTreeNode::CanReparent () const inline virtual
Returns
Whether or not this object represents a node that can be reparented to other nodes based on its context.
Reimplemented in FSCSEditorTreeNodeComponentBase.
Definition at line 426 of file SSCSEditor.h.
CloseOngoingCreateTransaction()
void FSCSEditorTreeNode::CloseOngoingCreateTransaction ()
Ends the 'Create + enter initial name' transaction of this node.
The creation of a node is 'ongoing' as long as the initial name of the node is in edition mode. When the text is not in edit mode anymore, the ongoing create transaction ends and the node is considered fully created.
DECLARE_DELEGATE()
FSCSEditorTreeNode::DECLARE_DELEGATE (FOnRenameRequested)
Delegate for when the context menu requests a rename.
FactoryNodeFromComponent()
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::FactoryNodeFromComponent (UActorComponent * InComponent) static
Creates the correct type of node based on the component (instanced or not, etc...)
FindChild() [1/3]
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::FindChild (const FName & InVariableOrInstanceName, bool bRecursiveSearch = false, uint32 * OutDepth = NULL) const
Attempts to find a reference to the child node that matches the given component variable or instance name.
Parameters
InVariableOrInstanceName The component variable or instance name to match.
bRecursiveSearch Whether or not to recursively search child nodes (default == false).
OutDepth If non-NULL, the depth of the child node will be returned in this parameter on success (default == NULL).
Returns
The child node with a component variable or instance name that matches the given name, or an invalid node reference if no match was found.
FindChild() [2/3]
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::FindChild (const UActorComponent * InComponentTemplate, bool bRecursiveSearch = false, uint32 * OutDepth = NULL) const
Attempts to find a reference to the child node that matches the given component template.
Parameters
InComponentTemplate The component template instance to match.
bRecursiveSearch Whether or not to recursively search child nodes (default == false).
OutDepth If non-NULL, the depth of the child node will be returned in this parameter on success (default == NULL).
Returns
The child node with a component template that matches the given component template instance, or an invalid node reference if no match was found.
FindChild() [3/3]
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::FindChild (const USCS_Node * InSCSNode, bool bRecursiveSearch = false, uint32 * OutDepth = NULL) const
Attempts to find a reference to the child node that matches the given SCS node.
Parameters
InSCSNode The SCS node to match.
bRecursiveSearch Whether or not to recursively search child nodes (default == false).
OutDepth If non-NULL, the depth of the child node will be returned in this parameter on success (default == NULL).
Returns
The child node that matches the given SCS node, or an invalid node reference if no match was found.
FindClosestParent()
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::FindClosestParent (TArray< FSCSEditorTreeNodePtrType > InNodes)
Finds the closest ancestor node in the given node set.
Parameters
InNodes The given node set.
Returns
One of the nodes from the set, or an invalid node reference if the set does not contain any ancestor nodes.
FindComponentInstanceInActor()
virtual UActorComponent * FSCSEditorTreeNode::FindComponentInstanceInActor (const AActor * InActor) const virtual
Finds the component instance represented by this node contained within a given Actor instance.
Parameters
InActor The Actor instance to use as the container object for finding the component instance.
Returns
The component instance represented by this node and contained within the given Actor instance, or NULL if not found.
FindSCSNodeForInstance()
USCS_Node * FSCSEditorTreeNode::FindSCSNodeForInstance (const UActorComponent * InstanceComponent, UClass * ClassToSearch) static
GetActorRootNode()
FSCSEditorActorNodePtrType FSCSEditorTreeNode::GetActorRootNode () const inline
Returns
The root of the actor subtree to which this node belongs.
Definition at line 164 of file SSCSEditor.h.
References ActorRootNodePtr.
GetBlueprint()
virtual UBlueprint * FSCSEditorTreeNode::GetBlueprint () const pure virtual
Returns
The Blueprint to which the object represented by this node belongs (requires implementation in subclass).
Implemented in FSCSEditorTreeNodeActorBase, FSCSEditorTreeNodeComponentBase, and FSCSEditorTreeNodeSeparator.
GetChildActorNode()
virtual FSCSEditorChildActorNodePtrType FSCSEditorTreeNode::GetChildActorNode () inline virtual
Returns the associated child actor node if applicable to this node type.
Reimplemented in FSCSEditorTreeNodeComponentBase.
Definition at line 316 of file SSCSEditor.h.
GetChildren()
const TArray< FSCSEditorTreeNodePtrType > & FSCSEditorTreeNode::GetChildren () const inline
Returns
The set of nodes which are parented to this node (read-only).
Definition at line 160 of file SSCSEditor.h.
References Children.
GetComponentTemplate()
UActorComponent * FSCSEditorTreeNode::GetComponentTemplate (bool bEvenIfPendingKill = false) const inline
Parameters
bEvenIfPendingKill If false, nullptr will be returned if the cached component template is pending kill. If true, it will be returned regardless (this is used for recaching the component template if the objects have been reinstanced following construction script execution).
Note
Deliberately non-virtual, for performance reasons.
Warning
This will not return the right component for components overridden by the inherited component handler, you need to call GetOrCreateEditableComponentTemplate instead
Returns
The component template or instance represented by this node, if it's a component node.
Definition at line 196 of file SSCSEditor.h.
References Cast(), and WeakObjectPtr.
Referenced by IsSceneComponent().
GetDisplayName()
virtual FText FSCSEditorTreeNode::GetDisplayName () const virtual
Returns
The name of this node in text.
Reimplemented in FSCSEditorTreeNodeComponent, FSCSEditorTreeNodeInstanceAddedComponent, and FSCSEditorTreeNodeInstancedInheritedComponent.
GetDisplayString()
virtual FString FSCSEditorTreeNode::GetDisplayString () const virtual
Returns
The string to be used in the tree display.
Reimplemented in FSCSEditorTreeNodeComponentBase, and FSCSEditorTreeNodeInstanceAddedComponent.
GetEditableObjectForBlueprint()
template<class T> T * FSCSEditorTreeNode::GetEditableObjectForBlueprint (UBlueprint * InBlueprint) const inline
Parameters
InBlueprint The Blueprint in which the object will be edited.
Note
May not be the same as the value returned by GetObject().
Returns
A reference to the object represented by this node that can be modified within the given Blueprint.
Definition at line 221 of file SSCSEditor.h.
References Cast(), and GetOrCreateEditableObjectForBlueprint().
GetMutableObject()
template<class T> T * FSCSEditorTreeNode::GetMutableObject () const inline protected
Definition at line 342 of file SSCSEditor.h.
References Cast(), and WeakObjectPtr.
GetNodeID()
virtual FName FSCSEditorTreeNode::GetNodeID () const virtual
Returns
The name to identify this node.
Reimplemented in FSCSEditorTreeNodeActorBase.
GetNodeType()
ENodeType FSCSEditorTreeNode::GetNodeType () const
Returns
Type of node
GetObject()
template<class T> const T * FSCSEditorTreeNode::GetObject (bool bEvenIfPendingKill = false) const inline
Parameters
bEvenIfPendingKill If false, nullptr will be returned if the cached object instance is pending kill. If true, it will be returned regardless (this is used for recaching the object if the objects have been reinstanced following construction script execution).
Note
Deliberately non-virtual, for performance reasons.
Returns
A read-only reference to the object represented by this node.
Definition at line 210 of file SSCSEditor.h.
References Cast(), and WeakObjectPtr.
GetOrCreateEditableComponentTemplate()
UActorComponent * FSCSEditorTreeNode::GetOrCreateEditableComponentTemplate (UBlueprint * ActualEditedBlueprint) const inline
Parameters
ActualEditedBlueprint currently edited blueprint
Note
Derived classes should override GetOrCreateEditableObjectForBlueprint().
Returns
The component template that can be editable for actual class.
Definition at line 141 of file SSCSEditor.h.
References Cast(), and GetOrCreateEditableObjectForBlueprint().
GetOrCreateEditableObjectForBlueprint()
virtual UObject * FSCSEditorTreeNode::GetOrCreateEditableObjectForBlueprint (UBlueprint * InBlueprint) const protected virtual
Reimplemented in FSCSEditorTreeNodeComponent.
Referenced by GetEditableObjectForBlueprint(), and GetOrCreateEditableComponentTemplate().
GetParent()
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::GetParent () const inline
Returns
This object's parent node (or an invalid reference if no parent is assigned).
Definition at line 156 of file SSCSEditor.h.
References ParentNodePtr.
GetSCSNode()
virtual class USCS_Node * FSCSEditorTreeNode::GetSCSNode () const virtual
Returns
The SCS node that is represented by this object, or NULL if there is no associated SCS node.
Reimplemented in FSCSEditorTreeNodeComponent.
GetVariableName()
virtual FName FSCSEditorTreeNode::GetVariableName () const virtual
Returns
The name of the variable represented by this node.
Reimplemented in FSCSEditorTreeNodeComponentBase, and FSCSEditorTreeNodeInstanceAddedComponent.
IsActorNode()
bool FSCSEditorTreeNode::IsActorNode () const inline
Returns
True if this represents an actor node type
Definition at line 176 of file SSCSEditor.h.
References ChildActorNode, NodeType, and RootActorNode.
Referenced by IsInstancedActor().
IsAttachedTo()
bool FSCSEditorTreeNode::IsAttachedTo (FSCSEditorTreeNodePtrType InNodePtr) const
Returns
Whether or not this node is a child (direct or indirect) of the given node.
IsBlueprintComponent()
bool FSCSEditorTreeNode::IsBlueprintComponent () const inline
Returns
Whether or not this node represents a Blueprint (i.e. non-native) component object.
Definition at line 403 of file SSCSEditor.h.
References IsComponentNode(), and IsNativeComponent().
IsComponentNode()
bool FSCSEditorTreeNode::IsComponentNode () const inline
Returns
True if this represents a component node type
Definition at line 183 of file SSCSEditor.h.
References ComponentNode, and NodeType.
Referenced by IsBlueprintComponent(), and IsInstancedComponent().
IsDefaultSceneRoot()
virtual bool FSCSEditorTreeNode::IsDefaultSceneRoot () const inline virtual
Returns
Whether or not this object represents the default SCS scene root component.
Reimplemented in FSCSEditorTreeNodeComponent, FSCSEditorTreeNodeInstanceAddedComponent, and FSCSEditorTreeNodeInstancedInheritedComponent.
Definition at line 416 of file SSCSEditor.h.
Referenced by FSCSEditorTreeNodeComponentBase::CanDelete(), and FSCSEditorTreeNodeComponentBase::CanRename().
IsDirectlyAttachedTo()
bool FSCSEditorTreeNode::IsDirectlyAttachedTo (FSCSEditorTreeNodePtrType InNodePtr) const inline
Returns
Whether or not this node is a direct child of the given node.
Definition at line 235 of file SSCSEditor.h.
References ParentNodePtr.
IsFlaggedForFiltration()
virtual bool FSCSEditorTreeNode::IsFlaggedForFiltration () const inline virtual
Query that determines if this item should be filtered out or not.
Reimplemented in FSCSEditorTreeNodeChildActor.
Definition at line 451 of file SSCSEditor.h.
References ensureMsgf, FilteredInMask, FilterFlags, TEXT, and Unknown.
IsInheritedComponent()
virtual bool FSCSEditorTreeNode::IsInheritedComponent () const inline virtual
Returns
Whether or not this object was declared in the current class (or instance). Anything inherited cannot be reorganized (renamed, reparented, etc...).
Reimplemented in FSCSEditorTreeNodeInstancedInheritedComponent.
Definition at line 374 of file SSCSEditor.h.
References IsInheritedSCSNode(), and IsNativeComponent().
Referenced by FSCSEditorTreeNodeComponentBase::CanDelete(), and FSCSEditorTreeNodeComponentBase::CanRename().
IsInheritedSCSNode()
virtual bool FSCSEditorTreeNode::IsInheritedSCSNode () const inline virtual
Returns
Whether or not this object represents an inherited SCS node (one from a SCS node in a parent Blueprint).
Reimplemented in FSCSEditorTreeNodeComponent, and FSCSEditorTreeNodeInstancedInheritedComponent.
Definition at line 369 of file SSCSEditor.h.
Referenced by IsInheritedComponent().
IsInstanced()
virtual bool FSCSEditorTreeNode::IsInstanced () const inline virtual
Returns
Whether or not this node represents an instanced object (i.e. not a template).
Reimplemented in FSCSEditorTreeNodeActorBase, FSCSEditorTreeNodeInstanceAddedComponent, and FSCSEditorTreeNodeInstancedInheritedComponent.
Definition at line 382 of file SSCSEditor.h.
Referenced by IsInstancedActor(), and IsInstancedComponent().
IsInstancedActor()
bool FSCSEditorTreeNode::IsInstancedActor () const inline
Returns
Whether or not this node represents an instanced actor object.
Definition at line 387 of file SSCSEditor.h.
References IsActorNode(), and IsInstanced().
IsInstancedComponent()
bool FSCSEditorTreeNode::IsInstancedComponent () const inline
Returns
Whether or not this node represents an instanced component object.
Definition at line 395 of file SSCSEditor.h.
References IsComponentNode(), and IsInstanced().
IsNativeComponent()
virtual bool FSCSEditorTreeNode::IsNativeComponent () const inline virtual
Returns
Whether or not this object represents a "native" component template (i.e. one that is not found in the SCS tree).
Reimplemented in FSCSEditorTreeNodeComponent, and FSCSEditorTreeNodeInstancedInheritedComponent.
Definition at line 359 of file SSCSEditor.h.
Referenced by IsBlueprintComponent(), and IsInheritedComponent().
IsRootComponent()
virtual bool FSCSEditorTreeNode::IsRootComponent () const inline virtual
Returns
Whether or not this object represents a root component.
Reimplemented in FSCSEditorTreeNodeComponent, FSCSEditorTreeNodeInstanceAddedComponent, and FSCSEditorTreeNodeInstancedInheritedComponent.
Definition at line 364 of file SSCSEditor.h.
IsSceneComponent()
bool FSCSEditorTreeNode::IsSceneComponent () const inline
Definition at line 310 of file SSCSEditor.h.
References Cast(), and GetComponentTemplate().
IsUserInstancedComponent()
virtual bool FSCSEditorTreeNode::IsUserInstancedComponent () const inline virtual
Returns
Whether or not this object represents a component instance that was created by the user and not by a native or Blueprint-generated class.
Reimplemented in FSCSEditorTreeNodeInstanceAddedComponent.
Definition at line 411 of file SSCSEditor.h.
MatchesFilterType()
virtual bool FSCSEditorTreeNode::MatchesFilterType (const UClass * InFilterType) const virtual
Returns whether the node will match the given type (for filtering)
Reimplemented in FSCSEditorTreeNodeComponentBase, and FSCSEditorTreeNodeSeparator.
OnCompleteRename()
virtual void FSCSEditorTreeNode::OnCompleteRename (const FText & InNewName) virtual
Renames the object or variable represented by this node.
Reimplemented in FSCSEditorTreeNodeComponent, FSCSEditorTreeNodeInstanceAddedComponent, and FSCSEditorTreeNodeRootActor.
OnRequestRename()
void FSCSEditorTreeNode::OnRequestRename (TUniquePtr< FScopedTransaction > OngoingCreateTransaction)
Requests a rename on the node.
Parameters
OngoingCreateTransaction The transaction scoping the node creation which will end once the node is named by the user or null if the rename is not part of a the creation process.
References OngoingCreateTransaction.
RefreshCachedChildFilterState()
void FSCSEditorTreeNode::RefreshCachedChildFilterState (bool bUpdateParent) protected
Updates the EFilteredState::ChildMatches flag, based off of children's current state.
RefreshFilteredState()
virtual bool FSCSEditorTreeNode::RefreshFilteredState (const UClass * InFilterType, const TArray< FString > & InFilterTerms, bool bRecursive) virtual
Refreshes this item's filtration state.
Set bRecursive to 'true' to refresh any child nodes as well
Reimplemented in FSCSEditorTreeNodeRootActor.
RemoveChild()
virtual void FSCSEditorTreeNode::RemoveChild (FSCSEditorTreeNodePtrType InChildNodePtr) virtual
Removes the given node from the list of child nodes.
Parameters
InChildNodePtr The child node to remove.
Reimplemented in FSCSEditorTreeNodeActorBase, and FSCSEditorTreeNodeRootActor.
RemoveMeAsChild()
virtual void FSCSEditorTreeNode::RemoveMeAsChild () inline protected virtual
Reimplemented in FSCSEditorTreeNodeComponent, and FSCSEditorTreeNodeInstanceAddedComponent.
Definition at line 338 of file SSCSEditor.h.
SetActorRootNode()
void FSCSEditorTreeNode::SetActorRootNode (FSCSEditorActorNodePtrType InActorNode)
Sets the actor root to the given node for this node along with any children.
SetCachedFilterState()
void FSCSEditorTreeNode::SetCachedFilterState (bool bMatchesFilter, bool bUpdateParent) protected
Sets this item's filtration state.
Use bUpdateParent to make sure the parent's EFilteredState::ChildMatches flag is properly updated based off the new state
SetObject()
void FSCSEditorTreeNode::SetObject (UObject * InObject) inline
Sets the internal object instance represented by this node.
Definition at line 228 of file SSCSEditor.h.
References WeakObjectPtr.
Referenced by FSCSEditorTreeNodeActorBase::FSCSEditorTreeNodeActorBase().
SetRenameRequestedDelegate()
void FSCSEditorTreeNode::SetRenameRequestedDelegate (FOnRenameRequested InRenameRequested) inline
Sets up the delegate for a rename operation.
Definition at line 448 of file SSCSEditor.h.
References RenameRequestedDelegate.
Field Documentation
ActorRootNodePtr
FSCSEditorActorNodePtrType FSCSEditorTreeNode::ActorRootNodePtr private
Definition at line 483 of file SSCSEditor.h.
Referenced by GetActorRootNode().
Children
TArray<FSCSEditorTreeNodePtrType> FSCSEditorTreeNode::Children private
Definition at line 484 of file SSCSEditor.h.
Referenced by GetChildren().
FilterFlags
uint8 FSCSEditorTreeNode::FilterFlags private
Definition at line 498 of file SSCSEditor.h.
Referenced by IsFlaggedForFiltration().
NodeType
ENodeType FSCSEditorTreeNode::NodeType private
Definition at line 476 of file SSCSEditor.h.
Referenced by IsActorNode(), and IsComponentNode().
OngoingCreateTransaction
TUniquePtr<FScopedTransaction> FSCSEditorTreeNode::OngoingCreateTransaction protected
Definition at line 472 of file SSCSEditor.h.
Referenced by OnRequestRename().
ParentNodePtr
FSCSEditorTreeNodePtrType FSCSEditorTreeNode::ParentNodePtr private
Definition at line 482 of file SSCSEditor.h.
Referenced by GetParent(), and IsDirectlyAttachedTo().
RenameRequestedDelegate
FOnRenameRequested FSCSEditorTreeNode::RenameRequestedDelegate private
Handles rename requests.
Definition at line 487 of file SSCSEditor.h.
Referenced by SetRenameRequestedDelegate().
WeakObjectPtr
TWeakObjectPtr<UObject> FSCSEditorTreeNode::WeakObjectPtr private
Definition at line 479 of file SSCSEditor.h.
Referenced by GetComponentTemplate(), GetMutableObject(), GetObject(), and SetObject().
The documentation for this class was generated from the following file:
SSCSEditor.h