Unreal Engine 5.6 C++ API: TArrayView< InElementType, InSizeType > Class Template Reference
TArrayView< InElementType, InSizeType > Class Template Reference
Templated fixed-size view of another array.
#include "ArrayView.h"
Public Types
using ElementType = InElementType
using IntrusiveUnsetOptionalStateType = TArrayView
using SizeType = InSizeType
Public Member Functions
TArrayView ()
Constructor.
TArrayView (const TArrayView &)=default
TArrayView (FIntrusiveUnsetOptionalState)
template<typename OtherElementType UE_REQUIRES>
FORCEINLINE TArrayView (OtherElementType *InData UE_LIFETIMEBOUND, SizeType InCount)
Construct a view of an arbitrary pointer.
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TAnd< TIsContiguousContainer<CVUnqualifiedOtherRangeType>, TOr< TIsCompatibleRangeType<OtherRangeType>, TIsReinterpretableRangeType<OtherRangeType> > >::Value && !TIsTArrayView_V<CVUnqualifiedOtherRangeType>)>
FORCEINLINE TArrayView (OtherRangeType &&Other UE_LIFETIMEBOUND)
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TAnd< TIsContiguousContainer<CVUnqualifiedOtherRangeType>, TOr< TIsCompatibleRangeType<OtherRangeType>, TIsReinterpretableRangeType<OtherRangeType> > >::Value && TIsTArrayView_V<CVUnqualifiedOtherRangeType> && !std::is_same_v<CVUnqualifiedOtherRangeType, TArrayView>)>
FORCEINLINE TArrayView (OtherRangeType &&Other)
Constructor from another range.
FORCEINLINE TArrayView (std::initializer_list< ElementType > List UE_LIFETIMEBOUND)
Construct a view of an initializer list.
~TArrayView ()=default
FORCEINLINE ElementType * begin () const
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE void CheckInvariants () const
Checks array invariants: if array size is greater than or equal to zero.
template<typename ComparisonType>
bool Contains (const ComparisonType &Item) const
Checks if this array contains the element.
template<typename Predicate>
FORCEINLINE bool ContainsByPredicate (Predicate Pred) const
Checks if this array contains an element for which the predicate is true.
FORCEINLINE ElementType * end () const
template<typename Predicate>
TArray< std::remove_const_t< ElementType > > FilterByPredicate (Predicate Pred) const
Filters the elements in the array based on a predicate functor.
SizeType Find (const ElementType &Item) const
Finds element within the array.
FORCEINLINE bool Find (const ElementType &Item, SizeType &Index) const
Finds element within the array.
template<typename KeyType>
ElementType * FindByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename Predicate>
ElementType * FindByPredicate (Predicate Pred) const
Finds an element which matches a predicate functor.
SizeType FindLast (const ElementType &Item) const
Finds element within the array starting from the end.
FORCEINLINE bool FindLast (const ElementType &Item, SizeType &Index) const
Finds element within the array starting from the end.
template<typename Predicate>
FORCEINLINE SizeType FindLastByPredicate (Predicate Pred) const
Finds element within the array starting from the end.
template<typename Predicate>
SizeType FindLastByPredicate (Predicate Pred, SizeType StartIndex) const
Finds element within the array starting from StartIndex and going backwards.
FORCEINLINE ElementType * GetData () const
Helper function for returning a typed pointer to the first array entry.
template<typename KeyType>
SizeType IndexOfByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename Predicate>
SizeType IndexOfByPredicate (Predicate Pred) const
Finds an item by predicate.
bool IsEmpty () const
Returns true if the array view is empty and contains no elements.
FORCEINLINE bool IsValidIndex (SizeType Index) const
Tests if index is valid, i.e.
FORCEINLINE ElementType & Last (SizeType IndexFromTheEnd=0) const
Returns n-th last element from the array.
TArrayView Left (SizeType Count) const
Returns the left-most part of the view by taking the given number of elements from the left.
TArrayView LeftChop (SizeType Count) const
Returns the left-most part of the view by chopping the given number of elements from the right.
void LeftChopInline (SizeType CharCount)
Modifies the view by chopping the given number of elements from the right.
void LeftInline (SizeType CharCount)
Modifies the view to be the given number of elements from the left.
TArrayView Mid (SizeType Index, SizeType Count=TNumericLimits< SizeType >::Max()) const
Returns the middle part of the view by taking up to the given number of elements from the given position.
void MidInline (SizeType Position, SizeType CharCount=TNumericLimits< SizeType >::Max())
Modifies the view to be the middle part by taking up to the given number of elements from the given position.
FORCEINLINE SizeType Num () const
Returns number of elements in array.
FORCEINLINE SIZE_T NumBytes () const
TArrayView & operator= (const TArrayView &)=default
bool operator== (FIntrusiveUnsetOptionalState) const
FORCEINLINE ElementType & operator[] (SizeType Index) const
Array bracket operator.
FORCEINLINE void RangeCheck (SizeType Index) const
Checks if index is in array range.
FORCEINLINE TReversePointerIterator< ElementType > rbegin () const
FORCEINLINE TReversePointerIterator< ElementType > rend () const
TArrayView Right (SizeType Count) const
Returns the right-most part of the view by taking the given number of elements from the right.
TArrayView RightChop (SizeType Count) const
Returns the right-most part of the view by chopping the given number of elements from the left.
void RightChopInline (SizeType CharCount)
Modifies the view by chopping the given number of elements from the left.
void RightInline (SizeType CharCount)
Modifies the view to be the given number of elements from the right.
FORCEINLINE TArrayView Slice (SizeType Index, SizeType InNum) const
Returns a sliced view This is similar to Mid(), but with a narrow contract, i.e.
FORCEINLINE void SliceRangeCheck (SizeType Index, SizeType InNum) const
Checks if a slice range [Index, Index+InNum) is in array range.
void Sort ()
Sorts the array assuming < operator is defined for the item type.
template<class PREDICATE_CLASS>
void Sort (const PREDICATE_CLASS &Predicate)
Sorts the array using user define predicate class.
void StableSort ()
Stable sorts the array assuming < operator is defined for the item type.
template<class PREDICATE_CLASS>
void StableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the array using user defined predicate class.
Static Public Member Functions
static FORCEINLINE constexpr size_t GetTypeAlignment ()
Helper function returning the alignment of the inner type.
static FORCEINLINE constexpr size_t GetTypeSize ()
Helper function returning the size of the inner type.
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
template<typename T>
using TIsCompatibleRangeType = UE::Core::ArrayView::Private::TIsCompatibleRangeType<T, ElementType>
template<typename T>
using TIsReinterpretableRangeType = UE::Core::ArrayView::Private::TIsReinterpretableRangeType<T, ElementType>
Private Attributes
SizeType ArrayNum
ElementType * DataPtr
Detailed Description
template<typename InElementType, typename InSizeType>
class TArrayView< InElementType, InSizeType >
Templated fixed-size view of another array.
A statically sized view of an array of typed elements. Designed to allow functions to take either a fixed C array or a TArray with an arbitrary allocator as an argument when the function neither adds nor removes elements
e.g.: int32 SumAll(TArrayView<const int32> array) { return Algo::Accumulate(array); }
could be called as: SumAll(MyTArray);\ SumAll(MyCArray); SumAll(MakeArrayView(Ptr, Num));
auto Values = { 1, 2, 3 }; SumAll(Values);
Note: View classes are not const-propagating! If you want a view where the elements are const, you need "TArrayView<const T>" not "const TArrayView<T>"!
Caution: Treat a view like a reference to the elements in the array. DO NOT free or reallocate the array while the view exists! For this reason, be mindful of lifetimes when constructing TArrayViews from rvalue initializer lists:
TArrayView<int> View = { 1, 2, 3 }; // construction of array view from rvalue initializer list int n = View[0]; // undefined behavior, as the initializer list was destroyed at the end of the previous line
Definition at line 137 of file ArrayView.h.
Member Typedef Documentation
ElementType
template<typename InElementType, typename InSizeType> using TArrayView< InElementType, InSizeType >::ElementType = InElementType
Definition at line 140 of file ArrayView.h.
IntrusiveUnsetOptionalStateType
template<typename InElementType, typename InSizeType> using TArrayView< InElementType, InSizeType >::IntrusiveUnsetOptionalStateType = TArrayView
Definition at line 272 of file ArrayView.h.
SizeType
template<typename InElementType, typename InSizeType> using TArrayView< InElementType, InSizeType >::SizeType = InSizeType
Definition at line 141 of file ArrayView.h.
TIsCompatibleRangeType
template<typename InElementType, typename InSizeType> template<typename T> using TArrayView< InElementType, InSizeType >::TIsCompatibleRangeType = UE::Core::ArrayView::Private::TIsCompatibleRangeType<T, ElementType> private
Definition at line 161 of file ArrayView.h.
TIsReinterpretableRangeType
template<typename InElementType, typename InSizeType> template<typename T> using TArrayView< InElementType, InSizeType >::TIsReinterpretableRangeType = UE::Core::ArrayView::Private::TIsReinterpretableRangeType<T, ElementType> private
Definition at line 164 of file ArrayView.h.
Constructor & Destructor Documentation
TArrayView() [1/7]
template<typename InElementType, typename InSizeType> TArrayView< InElementType, InSizeType >::TArrayView (const TArrayView< InElementType, InSizeType > &) nodiscard default
~TArrayView()
template<typename InElementType, typename InSizeType> TArrayView< InElementType, InSizeType >::~TArrayView () default
TArrayView() [2/7]
template<typename InElementType, typename InSizeType> TArrayView< InElementType, InSizeType >::TArrayView () inline nodiscard
Constructor.
Definition at line 153 of file ArrayView.h.
Referenced by TArrayView< FTransform >::Left(), TArrayView< FTransform >::LeftChop(), TArrayView< FTransform >::Mid(), TArrayView< FTransform >::Right(), TArrayView< FTransform >::RightChop(), and TArrayView< FTransform >::Slice().
TArrayView() [3/7]
template<typename InElementType, typename InSizeType> template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TAnd< TIsContiguousContainer<CVUnqualifiedOtherRangeType>, TOr< TIsCompatibleRangeType<OtherRangeType>, TIsReinterpretableRangeType<OtherRangeType> > >::Value && TIsTArrayView_V<CVUnqualifiedOtherRangeType> && !std::is_same_v<CVUnqualifiedOtherRangeType, TArrayView>)> FORCEINLINE TArrayView< InElementType, InSizeType >::TArrayView (OtherRangeType && Other) inline nodiscard
Constructor from another range.
Parameters
Other The source range to copy
Definition at line 187 of file ArrayView.h.
TArrayView() [4/7]
template<typename InElementType, typename InSizeType> template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TAnd< TIsContiguousContainer<CVUnqualifiedOtherRangeType>, TOr< TIsCompatibleRangeType<OtherRangeType>, TIsReinterpretableRangeType<OtherRangeType> > >::Value && !TIsTArrayView_V<CVUnqualifiedOtherRangeType>)> FORCEINLINE TArrayView< InElementType, InSizeType >::TArrayView (OtherRangeType &&Other UE_LIFETIMEBOUND) inline nodiscard
Definition at line 219 of file ArrayView.h.
TArrayView() [5/7]
template<typename InElementType, typename InSizeType> template<typename OtherElementType UE_REQUIRES> FORCEINLINE TArrayView< InElementType, InSizeType >::TArrayView (OtherElementType *InData UE_LIFETIMEBOUND, SizeType InCount) inline nodiscard
Construct a view of an arbitrary pointer.
Parameters
InData The data to view
InCount The number of elements
Definition at line 249 of file ArrayView.h.
TArrayView() [6/7]
template<typename InElementType, typename InSizeType> FORCEINLINE TArrayView< InElementType, InSizeType >::TArrayView (std::initializer_list< ElementType > List UE_LIFETIMEBOUND) inline nodiscard
Construct a view of an initializer list.
The caller is responsible for ensuring that the view does not outlive the initializer list.
Definition at line 261 of file ArrayView.h.
TArrayView() [7/7]
template<typename InElementType, typename InSizeType> TArrayView< InElementType, InSizeType >::TArrayView (FIntrusiveUnsetOptionalState) inline explicit nodiscard
Definition at line 274 of file ArrayView.h.
Member Function Documentation
begin()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType * TArrayView< InElementType, InSizeType >::begin () const inline nodiscard
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 758 of file ArrayView.h.
CheckInvariants()
template<typename InElementType, typename InSizeType> FORCEINLINE void TArrayView< InElementType, InSizeType >::CheckInvariants () const inline
Checks array invariants: if array size is greater than or equal to zero.
Definition at line 320 of file ArrayView.h.
Referenced by TArrayView< FTransform >::RangeCheck().
Contains()
template<typename InElementType, typename InSizeType> template<typename ComparisonType> bool TArrayView< InElementType, InSizeType >::Contains (const ComparisonType & Item) const inline nodiscard
Checks if this array contains the element.
Returns
True if found. False otherwise.
Definition at line 728 of file ArrayView.h.
Referenced by TMovieSceneEvaluationTree< DataType >::FAddUniqueOperator::operator()().
ContainsByPredicate()
template<typename InElementType, typename InSizeType> template<typename Predicate> FORCEINLINE bool TArrayView< InElementType, InSizeType >::ContainsByPredicate (Predicate Pred) const inline nodiscard
Checks if this array contains an element for which the predicate is true.
Parameters
Predicate to use
Returns
True if found. False otherwise.
Definition at line 748 of file ArrayView.h.
end()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType * TArrayView< InElementType, InSizeType >::end () const inline nodiscard
Definition at line 759 of file ArrayView.h.
FilterByPredicate()
template<typename InElementType, typename InSizeType> template<typename Predicate> TArray< std::remove_const_t< ElementType > > TArrayView< InElementType, InSizeType >::FilterByPredicate (Predicate Pred) const inline nodiscard
Filters the elements in the array based on a predicate functor.
Parameters
Pred The functor to apply to each element.
Returns
TArray with the same type as this object which contains the subset of elements for which the functor returns true.
Definition at line 709 of file ArrayView.h.
Find() [1/2]
template<typename InElementType, typename InSizeType> SizeType TArrayView< InElementType, InSizeType >::Find (const ElementType & Item) const inline nodiscard
Finds element within the array.
Parameters
Item Item to look for.
Returns
Index of the found element. INDEX_NONE otherwise.
Definition at line 529 of file ArrayView.h.
Find() [2/2]
template<typename InElementType, typename InSizeType> FORCEINLINE bool TArrayView< InElementType, InSizeType >::Find (const ElementType & Item, SizeType & Index) const inline nodiscard
Finds element within the array.
Parameters
Item Item to look for.
Index Output parameter. Found index.
Returns
True if found. False otherwise.
Definition at line 516 of file ArrayView.h.
Referenced by SComboBox< OptionType >::OnKeyDown(), SListView< TSharedPtr< FString > >::OnKeyDown_Internal(), SListView< TSharedPtr< FString > >::OnNavigation(), STileView< ItemType >::OnNavigation(), and SListView< TSharedPtr< FString > >::Private_SelectRangeFromCurrentTo().
FindByKey()
template<typename InElementType, typename InSizeType> template<typename KeyType> ElementType * TArrayView< InElementType, InSizeType >::FindByKey (const KeyType & Key) const inline nodiscard
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
Parameters
Key The key to search by.
Returns
Pointer to the first matching element, or nullptr if none is found.
Definition at line 665 of file ArrayView.h.
FindByPredicate()
template<typename InElementType, typename InSizeType> template<typename Predicate> ElementType * TArrayView< InElementType, InSizeType >::FindByPredicate (Predicate Pred) const inline nodiscard
Finds an element which matches a predicate functor.
Parameters
Pred The functor to apply to each element.
Returns
Pointer to the first element for which the predicate returns true, or nullptr if none is found.
Definition at line 687 of file ArrayView.h.
Referenced by TArrayView< FTransform >::ContainsByPredicate(), and USTRUCT().
FindLast() [1/2]
template<typename InElementType, typename InSizeType> SizeType TArrayView< InElementType, InSizeType >::FindLast (const ElementType & Item) const inline nodiscard
Finds element within the array starting from the end.
Parameters
Item Item to look for.
Returns
Index of the found element. INDEX_NONE otherwise.
Definition at line 562 of file ArrayView.h.
FindLast() [2/2]
template<typename InElementType, typename InSizeType> FORCEINLINE bool TArrayView< InElementType, InSizeType >::FindLast (const ElementType & Item, SizeType & Index) const inline nodiscard
Finds element within the array starting from the end.
Parameters
Item Item to look for.
Index Output parameter. Found index.
Returns
True if found. False otherwise.
Definition at line 550 of file ArrayView.h.
Referenced by TArrayView< FTransform >::FindLast().
FindLastByPredicate() [1/2]
template<typename InElementType, typename InSizeType> template<typename Predicate> FORCEINLINE SizeType TArrayView< InElementType, InSizeType >::FindLastByPredicate (Predicate Pred) const inline nodiscard
Finds element within the array starting from the end.
Uses predicate to match element.
Parameters
Pred Predicate taking array element and returns true if element matches search criteria, false otherwise.
Returns
Index of the found element. INDEX_NONE otherwise.
Definition at line 606 of file ArrayView.h.
FindLastByPredicate() [2/2]
template<typename InElementType, typename InSizeType> template<typename Predicate> SizeType TArrayView< InElementType, InSizeType >::FindLastByPredicate (Predicate Pred, SizeType StartIndex) const inline nodiscard
Finds element within the array starting from StartIndex and going backwards.
Uses predicate to match element.
Parameters
Pred Predicate taking array element and returns true if element matches search criteria, false otherwise.
StartIndex Index of element from which to start searching.
Returns
Index of the found element. INDEX_NONE otherwise.
Definition at line 584 of file ArrayView.h.
Referenced by TArrayView< FTransform >::FindLastByPredicate().
GetData()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType * TArrayView< InElementType, InSizeType >::GetData () const inline nodiscard
Helper function for returning a typed pointer to the first array entry.
Returns
Pointer to first array entry.
Definition at line 294 of file ArrayView.h.
Referenced by UE::Geometry::FMeshRegionOperator::FMeshRegionOperator(), UE::Geometry::FMeshRegionOperator::FMeshRegionOperator(), FRDGScatterUploadBase::Add(), TArrayView< FTransform >::begin(), TArrayView< FTransform >::Contains(), CreateByteAddressBuffer(), CreateStructuredBuffer(), CreateUploadBuffer(), TArrayView< FTransform >::end(), TArrayView< FTransform >::FilterByPredicate(), TArrayView< FTransform >::Find(), TArrayView< FTransform >::FindByKey(), TArrayView< FTransform >::FindByPredicate(), TArrayView< FTransform >::FindLast(), TArrayView< FTransform >::FindLastByPredicate(), FMeshDescription::GetVertexConnectedTriangles(), TArrayView< FTransform >::IndexOfByKey(), TArrayView< FTransform >::IndexOfByPredicate(), TAttributeArrayContainer< AttributeType >::InsertIntoElement(), TArrayView< FTransform >::Last(), TraceServices::FTraceAnalyzerUtils::LegacyAttachmentArray(), TArrayView< FTransform >::Mid(), operator==(), TArrayView< FTransform >::operator[](), TArrayView< FTransform >::rbegin(), RebaseTArrayView(), and TArrayView< FTransform >::rend().
GetTypeAlignment()
template<typename InElementType, typename InSizeType> FORCEINLINE constexpr size_t TArrayView< InElementType, InSizeType >::GetTypeAlignment () inline static nodiscard constexpr
Helper function returning the alignment of the inner type.
Definition at line 312 of file ArrayView.h.
GetTypeSize()
template<typename InElementType, typename InSizeType> FORCEINLINE constexpr size_t TArrayView< InElementType, InSizeType >::GetTypeSize () inline static nodiscard constexpr
Helper function returning the size of the inner type.
Returns
Size in bytes of array type.
Definition at line 304 of file ArrayView.h.
Referenced by FRDGScatterUploadBase::Add(), CreateByteAddressBuffer(), and CreateStructuredBuffer().
IndexOfByKey()
template<typename InElementType, typename InSizeType> template<typename KeyType> SizeType TArrayView< InElementType, InSizeType >::IndexOfByKey (const KeyType & Key) const inline nodiscard
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
Parameters
Key The key to search by.
Returns
Index to the first matching element, or INDEX_NONE if none is found.
Definition at line 621 of file ArrayView.h.
IndexOfByPredicate()
template<typename InElementType, typename InSizeType> template<typename Predicate> SizeType TArrayView< InElementType, InSizeType >::IndexOfByPredicate (Predicate Pred) const inline nodiscard
Finds an item by predicate.
Parameters
Pred The predicate to match.
Returns
Index to the first matching element, or INDEX_NONE if none is found.
Definition at line 643 of file ArrayView.h.
Referenced by USTRUCT().
IsEmpty()
template<typename InElementType, typename InSizeType> bool TArrayView< InElementType, InSizeType >::IsEmpty () const inline nodiscard
Returns true if the array view is empty and contains no elements.
Returns
True if the array view is empty.
See also
Num
Definition at line 369 of file ArrayView.h.
Referenced by UE::Geometry::FClusterKMeans::ComputeClusters(), ENUM_CLASS_FLAGS(), and UE::Geometry::FVoxelBaseOp::GetAverageTranslation().
IsValidIndex()
template<typename InElementType, typename InSizeType> FORCEINLINE bool TArrayView< InElementType, InSizeType >::IsValidIndex (SizeType Index) const inline nodiscard
Tests if index is valid, i.e.
greater than or equal to zero, and less than the number of elements in the array.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 358 of file ArrayView.h.
Referenced by UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODParentBoneIndex(), SListView< TSharedPtr< FString > >::OnNavigation(), and STileView< ItemType >::OnNavigation().
Last()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType & TArrayView< InElementType, InSizeType >::Last (SizeType IndexFromTheEnd = 0) const inline nodiscard
Returns n-th last element from the array.
Parameters
IndexFromTheEnd (Optional) Index from the end of array. Default is 0.
Returns
Reference to n-th last element from the array.
Definition at line 409 of file ArrayView.h.
Referenced by SListView< TSharedPtr< FString > >::OnKeyDown_Internal().
Left()
template<typename InElementType, typename InSizeType> TArrayView TArrayView< InElementType, InSizeType >::Left (SizeType Count) const inline nodiscard
Returns the left-most part of the view by taking the given number of elements from the left.
Definition at line 432 of file ArrayView.h.
LeftChop()
template<typename InElementType, typename InSizeType> TArrayView TArrayView< InElementType, InSizeType >::LeftChop (SizeType Count) const inline nodiscard
Returns the left-most part of the view by chopping the given number of elements from the right.
Definition at line 438 of file ArrayView.h.
LeftChopInline()
template<typename InElementType, typename InSizeType> void TArrayView< InElementType, InSizeType >::LeftChopInline (SizeType CharCount) inline
Modifies the view by chopping the given number of elements from the right.
Definition at line 485 of file ArrayView.h.
LeftInline()
template<typename InElementType, typename InSizeType> void TArrayView< InElementType, InSizeType >::LeftInline (SizeType CharCount) inline
Modifies the view to be the given number of elements from the left.
Definition at line 479 of file ArrayView.h.
Mid()
template<typename InElementType, typename InSizeType> TArrayView TArrayView< InElementType, InSizeType >::Mid (SizeType Index, SizeType Count = TNumericLimits<SizeType>::Max()) const inline nodiscard
Returns the middle part of the view by taking up to the given number of elements from the given position.
Definition at line 458 of file ArrayView.h.
Referenced by TArrayView< FTransform >::MidInline().
MidInline()
template<typename InElementType, typename InSizeType> void TArrayView< InElementType, InSizeType >::MidInline (SizeType Position, SizeType CharCount = TNumericLimits<SizeType>::Max()) inline
Modifies the view to be the middle part by taking up to the given number of elements from the given position.
Definition at line 503 of file ArrayView.h.
Num()
template<typename InElementType, typename InSizeType> FORCEINLINE SizeType TArrayView< InElementType, InSizeType >::Num () const inline nodiscard
Returns number of elements in array.
Returns
Number of elements in array.
Definition at line 379 of file ArrayView.h.
Referenced by UE::Geometry::FMeshRegionOperator::FMeshRegionOperator(), UE::Geometry::FMeshRegionOperator::FMeshRegionOperator(), UE::Geometry::TPolygon2< double >::TPolygon2(), FRDGScatterUploadBase::Add(), UE::Geometry::TDynamicVector< Type, BlockSize >::Add(), UE::MemStack::AllocateArrayView(), TSet< class UObject * >::Append(), UE::Anim::FCurveFilter::AppendNames(), FInstancedSkinnedMeshComponentHelper::CalcBounds(), UE::Geometry::FDynamicSubmesh3::Compute(), UE::Geometry::FDynamicSubmesh3::ComputeBoundaryInfo(), UE::Geometry::FClusterKMeans::ComputeClusters(), UE::Geometry::FVerticalCylinderGeneratorBase::ComputeSegLengths(), CreateByteAddressBuffer(), CreateStructuredBuffer(), CreateUploadBuffer(), TManagedStoragePlatformFile< BaseClass >::DeleteFiles(), FPixelShaderUtils::DrawFullscreenInstancedMultiViewportPixelShader(), TSequencerChannelInterfaceCommon< ChannelType >::DrawKeys_Raw(), TArrayView< FTransform >::end(), ENUM_CLASS_FLAGS(), TArrayView< FTransform >::FindLastByPredicate(), UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree >::FindRootsInRange(), UE::MovieScene::FPlaybackCapabilities::ForEachCapabilityInterface(), TDeltaSetup< ElementType, DeltaType >::FWriter::Gather(), UE::Geometry::FVerticalCylinderGeneratorBase::GenerateVerticalCircleSweep(), ActorElementDataUtil::GetActorsFromHandles(), ActorElementDataUtil::GetActorsFromHandlesChecked(), UE::Geometry::FVoxelBaseOp::GetAverageTranslation(), FInstancedSkinnedMeshComponentHelper::GetComponentDesc(), ComponentElementDataUtil::GetComponentsFromHandles(), ComponentElementDataUtil::GetComponentsFromHandlesChecked(), TraceServices::GetElementRangeOverlappingGivenRange(), FStaticMeshInstanceData::GetInstanceCustomDataInternal(), Audio::GetInterpolationParametersAtTimestamp(), FMeshDescription::GetNumPolygonVertices(), ObjectElementDataUtil::GetObjectsFromHandles(), ObjectElementDataUtil::GetObjectsFromHandlesChecked(), FRDGParameterStruct::GetParameterInternal(), FMeshDescription::GetPolygonPerimeterEdges(), FMeshDescription::GetPolygonVertexInstances(), FMeshDescription::GetPolygonVertices(), GetRenderTargetBindings(), GetRenderTargetBindings(), SMInstanceElementDataUtil::GetSMInstancesFromHandles(), SMInstanceElementDataUtil::GetSMInstancesFromHandlesChecked(), FShader::GetUniformBufferParameter(), FMeshDescription::GetVertexAdjacentVertices(), FMeshDescription::GetVertexConnectedTriangles(), FArrangedChildren::Hittest2_FromArray(), UE::CurveEditor::Private::InvertKeyAttributes(), UE::CurveEditor::Private::InvertKeyPositions(), FMeshDescription::IsEdgeInternal(), FMeshDescription::IsEdgeInternalToPolygon(), UE::Geometry::FDynamicSubmesh3::MapEdgesToSubmesh(), UE::Geometry::FDynamicSubmesh3::MapGroupsToSubmesh(), UE::Geometry::FDynamicSubmesh3::MapTrianglesToSubmesh(), MovieSceneToolHelpers::MergeChannels(), MovieSceneToolHelpers::MergeSections(), MovieSceneToolHelpers::MergeSections(), TArrayView< FTransform >::Mid(), SComboBox< OptionType >::OnKeyDown(), SListView< TSharedPtr< FString > >::OnKeyDown_Internal(), SListView< TSharedPtr< FString > >::OnNavigation(), operator==(), UE::MovieScene::Optimize(), STreeView< FRigVMSearchResult >::PopulateLinearizedItems(), SListView< TSharedPtr< FString > >::Private_SelectRangeFromCurrentTo(), TArrayView< FTransform >::rbegin(), RebaseTArrayView(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RebuildOperational(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendChannel(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendImpl(), SListView< TSharedPtr< FString > >::ReGenerateItems(), STileView< ItemType >::ReGenerateItems(), TArrayAttribute< T >::RemoveAll(), TAttributeArrayContainer< AttributeType >::RemoveFromElement(), UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType >::Run(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set(), UE::Anim::FAttributeBlendData::SingleAdditiveContainerUniformWeighted(), UE::Anim::FAttributeBlendData::SingleContainerUniformWeighted(), and SListView< TSharedPtr< FString > >::UpdateSelectionSet().
NumBytes()
template<typename InElementType, typename InSizeType> FORCEINLINE SIZE_T TArrayView< InElementType, InSizeType >::NumBytes () const inline nodiscard
Returns
Number of bytes used, excluding slack
Definition at line 385 of file ArrayView.h.
operator=()
template<typename InElementType, typename InSizeType> TArrayView & TArrayView< InElementType, InSizeType >::operator= (const TArrayView< InElementType, InSizeType > &) default
operator==()
template<typename InElementType, typename InSizeType> bool TArrayView< InElementType, InSizeType >::operator== (FIntrusiveUnsetOptionalState) const inline nodiscard
Definition at line 279 of file ArrayView.h.
operator[]()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType & TArrayView< InElementType, InSizeType >::operator[] (SizeType Index) const inline nodiscard
Array bracket operator.
Returns reference to element at given index.
Returns
Reference to indexed element.
Definition at line 395 of file ArrayView.h.
RangeCheck()
template<typename InElementType, typename InSizeType> FORCEINLINE void TArrayView< InElementType, InSizeType >::RangeCheck (SizeType Index) const inline
Checks if index is in array range.
Parameters
Index Index to check.
Definition at line 330 of file ArrayView.h.
Referenced by TArrayView< FTransform >::Last(), and TArrayView< FTransform >::operator[]().
rbegin()
template<typename InElementType, typename InSizeType> FORCEINLINE TReversePointerIterator< ElementType > TArrayView< InElementType, InSizeType >::rbegin () const inline nodiscard
Definition at line 760 of file ArrayView.h.
rend()
template<typename InElementType, typename InSizeType> FORCEINLINE TReversePointerIterator< ElementType > TArrayView< InElementType, InSizeType >::rend () const inline nodiscard
Definition at line 761 of file ArrayView.h.
Right()
template<typename InElementType, typename InSizeType> TArrayView TArrayView< InElementType, InSizeType >::Right (SizeType Count) const inline nodiscard
Returns the right-most part of the view by taking the given number of elements from the right.
Definition at line 444 of file ArrayView.h.
RightChop()
template<typename InElementType, typename InSizeType> TArrayView TArrayView< InElementType, InSizeType >::RightChop (SizeType Count) const inline nodiscard
Returns the right-most part of the view by chopping the given number of elements from the left.
Definition at line 451 of file ArrayView.h.
RightChopInline()
template<typename InElementType, typename InSizeType> void TArrayView< InElementType, InSizeType >::RightChopInline (SizeType CharCount) inline
Modifies the view by chopping the given number of elements from the left.
Definition at line 497 of file ArrayView.h.
RightInline()
template<typename InElementType, typename InSizeType> void TArrayView< InElementType, InSizeType >::RightInline (SizeType CharCount) inline
Modifies the view to be the given number of elements from the right.
Definition at line 491 of file ArrayView.h.
Slice()
template<typename InElementType, typename InSizeType> FORCEINLINE TArrayView TArrayView< InElementType, InSizeType >::Slice (SizeType Index, SizeType InNum) const inline nodiscard
Returns a sliced view This is similar to Mid(), but with a narrow contract, i.e.
slicing outside of the range of the view is illegal.
Parameters
Index starting index of the new view
InNum number of elements in the new view
Returns
Sliced view
See also
Mid
Definition at line 425 of file ArrayView.h.
SliceRangeCheck()
template<typename InElementType, typename InSizeType> FORCEINLINE void TArrayView< InElementType, InSizeType >::SliceRangeCheck (SizeType Index, SizeType InNum) const inline
Checks if a slice range [Index, Index+InNum) is in array range.
Length is 0 is allowed on empty arrays; Index must be 0 in that case.
Parameters
Index Starting index of the slice.
InNum Length of the slice.
Definition at line 344 of file ArrayView.h.
Referenced by TArrayView< FTransform >::Slice().
Sort() [1/2]
template<typename InElementType, typename InSizeType> void TArrayView< InElementType, InSizeType >::Sort () inline
Sorts the array assuming < operator is defined for the item type.
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your array will be sorted by the values being pointed to, rather than the pointers' values. If this is not desirable, please use Algo::Sort(MyArray) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 772 of file ArrayView.h.
Sort() [2/2]
template<typename InElementType, typename InSizeType> template<class PREDICATE_CLASS> void TArrayView< InElementType, InSizeType >::Sort (const PREDICATE_CLASS & Predicate) inline
Sorts the array using user define predicate class.
Parameters
Predicate Predicate class instance.
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your predicate will be passed references rather than pointers. If this is not desirable, please use Algo::Sort(MyArray, Predicate) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 787 of file ArrayView.h.
StableSort() [1/2]
template<typename InElementType, typename InSizeType> void TArrayView< InElementType, InSizeType >::StableSort () inline
Stable sorts the array assuming < operator is defined for the item type.
Stable sort is slower than non-stable algorithm.
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your array will be sorted by the values being pointed to, rather than the pointers' values. If this is not desirable, please use Algo::StableSort(MyArray) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 802 of file ArrayView.h.
StableSort() [2/2]
template<typename InElementType, typename InSizeType> template<class PREDICATE_CLASS> void TArrayView< InElementType, InSizeType >::StableSort (const PREDICATE_CLASS & Predicate) inline
Stable sorts the array using user defined predicate class.
Stable sort is slower than non-stable algorithm.
Parameters
Predicate Predicate class instance
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your predicate will be passed references rather than pointers. If this is not desirable, please use Algo::StableSort(MyArray, Predicate) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 819 of file ArrayView.h.
Field Documentation
ArrayNum
template<typename InElementType, typename InSizeType> SizeType TArrayView< InElementType, InSizeType >::ArrayNum private
Definition at line 827 of file ArrayView.h.
bHasIntrusiveUnsetOptionalState
template<typename InElementType, typename InSizeType> bool TArrayView< InElementType, InSizeType >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 271 of file ArrayView.h.
DataPtr
template<typename InElementType, typename InSizeType> ElementType* TArrayView< InElementType, InSizeType >::DataPtr private
Definition at line 826 of file ArrayView.h.
The documentation for this class was generated from the following files:
ViewModelExtensionCollection.h
ArrayView.h