Unreal Engine 5.6 C++ API: FObjectInitializer Class Reference
FObjectInitializer Class Reference
Internal class to finalize UObject creation (initialize properties) after the real C++ constructor is called.
#include "UObjectGlobals.h"
Data Structures
struct FOverrides
Little helper struct to manage overrides from derived classes.
struct FSubobjectsToInit
Little helper struct to manage overrides from derived classes.
Public Member Functions
FObjectInitializer ()
Default Constructor, used when you are using the C++ "new" syntax.
FObjectInitializer (UObject *InObj, UObject *InObjectArchetype, EObjectInitializerOptions InOptions, struct FObjectInstancingGraph *InInstanceGraph=nullptr)
Constructor.
~FObjectInitializer ()
FORCEINLINE void AddPropertyPostInitCallback (TFunction< void()> &&Callback)
UObject * CreateDefaultSubobject (UObject *Outer, FName SubobjectFName, const UClass *ReturnType, const UClass *ClassToCreateByDefault, bool bIsRequired=true, bool bIsTransient=false) const
Create a component or subobject that will be instanced inside all instances of this class.
template<class TReturnType>
TReturnType * CreateDefaultSubobject (UObject *Outer, FName SubobjectName, bool bTransient=false) const
Create a component or subobject that will be instanced inside all instances of this class.
template<class TReturnType, class TClassToConstructByDefault>
TReturnType * CreateDefaultSubobject (UObject *Outer, FName SubobjectName, bool bTransient=false) const
Create a component or subobject, allows creating a child class and returning the parent class.
template<class TReturnType>
TReturnType * CreateEditorOnlyDefaultSubobject (UObject *Outer, FName SubobjectName, bool bTransient=false) const
Create a component or subobject only to be used with the editor.
UObject * CreateEditorOnlyDefaultSubobject (UObject *Outer, FName SubobjectName, const UClass *ReturnType, bool bTransient=false) const
Create a component or subobject only to be used with the editor.
template<class TReturnType>
TReturnType * CreateOptionalDefaultSubobject (UObject *Outer, FName SubobjectName, bool bTransient=false) const
Create optional component or subobject.
const FObjectInitializer & DoNotCreateDefaultSubobject (FName SubobjectName) const
Indicates that a base class should not create a component.
const FObjectInitializer & DoNotCreateNestedDefaultSubobject (FStringView SubobjectName) const
Indicates that a subobject should not create a component if created using CreateOptionalDefaultSubobject.
const FObjectInitializer & DoNotCreateNestedDefaultSubobject (TArrayView< const FName > SubobjectNames) const
Indicates that a subobject should not create a component if created using CreateOptionalDefaultSubobject.
FORCEINLINE void FinalizeSubobjectClassInitialization ()
FORCEINLINE UObject * GetArchetype () const
Return the archetype that this object will copy properties from later.
UClass * GetClass () const
Return the class of the object that is being constructed.
FORCEINLINE struct FObjectInstancingGraph * GetInstancingGraph ()
FORCEINLINE UObject * GetObj () const
Return the object that is being constructed.
template<class T>
const FObjectInitializer & SetDefaultSubobjectClass (FName SubobjectName) const
Sets the class to use for a subobject defined in a base class, the class must be a subclass of the class used by the base class.
const FObjectInitializer & SetDefaultSubobjectClass (FName SubobjectName, const UClass *Class) const
Sets the class to use for a subobject defined in a base class, the class must be a subclass of the class used by the base class.
template<class T>
const FObjectInitializer & SetNestedDefaultSubobjectClass (FStringView SubobjectName) const
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
const FObjectInitializer & SetNestedDefaultSubobjectClass (FStringView SubobjectName, const UClass *Class) const
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
template<class T>
const FObjectInitializer & SetNestedDefaultSubobjectClass (TArrayView< const FName > SubobjectNames) const
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
const FObjectInitializer & SetNestedDefaultSubobjectClass (TArrayView< const FName > SubobjectNames, const UClass *Class) const
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
UE_DEPRECATED (5.0, "Use version that takes EObjectInitializerOptions") FObjectInitializer(UObject *InObj
Static Public Member Functions
static void AssertIfInConstructor (UObject *Outer, const TCHAR *ErrorMessage)
Asserts with the specified message if code is executed inside UObject constructor.
static FObjectInitializer & Get ()
Gets ObjectInitializer for the currently constructed object.
Data Fields
UObject bool bInCopyTransientsFromClassDefaults
UObject bool bool bInShouldInitializeProps
UObject bool bool struct FObjectInstancingGraph * InInstanceGraph
UObject * InObjectArchetype
Private Member Functions
void AssertIfSubobjectSetupIsNotAllowed (const FName SubobjectName) const
Asserts if SetDefaultSubobjectClass or DoNotCreateOptionalDefaultSuobject are called inside of the constructor body.
void AssertIfSubobjectSetupIsNotAllowed (FStringView SubobjectName) const
Asserts if SetDefaultSubobjectClass or DoNotCreateOptionalDefaultSuobject are called inside of the constructor body.
void AssertIfSubobjectSetupIsNotAllowed (TArrayView< const FName > SubobjectNames) const
Asserts if SetDefaultSubobjectClass or DoNotCreateOptionalDefaultSuobject are called inside of the constructor body.
void Construct_Internal ()
Helper for the common behaviors in the constructors.
bool InitSubobjectProperties (bool bAllowInstancing) const
Calls InitProperties for any default subobjects created through this ObjectInitializer.
void InstanceSubobjects (UClass *Class, bool bNeedInstancing, bool bNeedSubobjectInstancing) const
Create copies of the object's components from their templates.
bool IsInstancingAllowed () const
void PostConstructInit ()
Finalizes a constructed UObject by initializing properties, instancing/initializing sub-objects, etc.
Static Private Member Functions
static bool InitNonNativeProperty (FProperty *Property, UObject *Data)
Initializes a non-native property, according to the initialization rules.
static void InitProperties (UObject *Obj, UClass *DefaultsClass, UObject *DefaultData, bool bCopyTransientsFromClassDefaults)
Binary initialize object properties to zero or defaults.
Private Attributes
bool bCopyTransientsFromClassDefaults
if true, copy the transients from the DefaultsClass defaults, otherwise copy the transients from DefaultData
bool bShouldInitializePropsFromArchetype
If true, initialize the properties.
bool bShouldSkipPostConstructInit {false}
bool bSubobjectClassInitializationAllowed = true
Only true until ObjectInitializer has not reached the base UObject class.
FSubobjectsToInit ComponentInits
List of component classes to initialize after the C++ constructors.
TArray< FName, TInlineAllocator< 8 > > ConstructedSubobjects
List of all subobject names constructed for this object.
struct FObjectInstancingGraph * InstanceGraph
Instance graph.
UObject * LastConstructedObject = nullptr
Previously constructed object in the callstack.
UObject * Obj
object to initialize, from static allocate object, after construction
UObject * ObjectArchetype
object to copy properties from
TFunction< void()> PropertyInitCallback
Callbacks for custom property initialization before PostInitProperties gets called.
TArray< TFunction< void()> > PropertyPostInitCallbacks
FOverrides SubobjectOverrides
List of component classes to override from derived classes.
Friends
class FScriptIntegrationObjectHelper
struct FStaticConstructObjectParameters
template<class T>
void InternalConstructor (const class FObjectInitializer &X)
class UObject
Detailed Description
Internal class to finalize UObject creation (initialize properties) after the real C++ constructor is called.
Definition at line 1256 of file UObjectGlobals.h.
Constructor & Destructor Documentation
FObjectInitializer() [1/2]
FObjectInitializer::FObjectInitializer ()
Default Constructor, used when you are using the C++ "new" syntax.
UObject::UObject will set the object pointer
Referenced by DoNotCreateDefaultSubobject(), DoNotCreateNestedDefaultSubobject(), DoNotCreateNestedDefaultSubobject(), Get(), InternalConstructor, SetDefaultSubobjectClass(), SetDefaultSubobjectClass(), SetNestedDefaultSubobjectClass(), SetNestedDefaultSubobjectClass(), SetNestedDefaultSubobjectClass(), and SetNestedDefaultSubobjectClass().
FObjectInitializer() [2/2]
FObjectInitializer::FObjectInitializer (UObject * InObj, UObject * InObjectArchetype, EObjectInitializerOptions InOptions, struct FObjectInstancingGraph * InInstanceGraph = nullptr)
Constructor.
Parameters
InObj object to initialize, from static allocate object, after construction
InObjectArchetype object to initialize properties from
InOptions initialization options, see EObjectInitializerOptions
InInstanceGraph passed instance graph
References InInstanceGraph, InObjectArchetype, InOptions, and UObject.
~FObjectInitializer()
FObjectInitializer::~FObjectInitializer ()
Member Function Documentation
AddPropertyPostInitCallback()
FORCEINLINE void FObjectInitializer::AddPropertyPostInitCallback (TFunction< void()> && Callback) inline
Definition at line 1313 of file UObjectGlobals.h.
References FORCEINLINE, MoveTemp(), and PropertyPostInitCallbacks.
AssertIfInConstructor()
void FObjectInitializer::AssertIfInConstructor (UObject * Outer, const TCHAR * ErrorMessage) static
Asserts with the specified message if code is executed inside UObject constructor.
References Outer, and UObject.
Referenced by NewObject(), NewObject(), and NewObject().
AssertIfSubobjectSetupIsNotAllowed() [1/3]
void FObjectInitializer::AssertIfSubobjectSetupIsNotAllowed (const FName SubobjectName) const private
Asserts if SetDefaultSubobjectClass or DoNotCreateOptionalDefaultSuobject are called inside of the constructor body.
Referenced by DoNotCreateDefaultSubobject(), DoNotCreateNestedDefaultSubobject(), DoNotCreateNestedDefaultSubobject(), SetDefaultSubobjectClass(), SetNestedDefaultSubobjectClass(), and SetNestedDefaultSubobjectClass().
AssertIfSubobjectSetupIsNotAllowed() [2/3]
void FObjectInitializer::AssertIfSubobjectSetupIsNotAllowed (FStringView SubobjectName) const private
Asserts if SetDefaultSubobjectClass or DoNotCreateOptionalDefaultSuobject are called inside of the constructor body.
AssertIfSubobjectSetupIsNotAllowed() [3/3]
void FObjectInitializer::AssertIfSubobjectSetupIsNotAllowed (TArrayView< const FName > SubobjectNames) const private
Asserts if SetDefaultSubobjectClass or DoNotCreateOptionalDefaultSuobject are called inside of the constructor body.
Construct_Internal()
void FObjectInitializer::Construct_Internal () private
Helper for the common behaviors in the constructors.
CreateDefaultSubobject() [1/3]
UObject * FObjectInitializer::CreateDefaultSubobject (UObject * Outer, FName SubobjectFName, const UClass * ReturnType, const UClass * ClassToCreateByDefault, bool bIsRequired = true, bool bIsTransient = false) const
Create a component or subobject that will be instanced inside all instances of this class.
Parameters
Outer outer to construct the subobject in
SubobjectName name of the new component
ReturnType class of return type, all overrides must be of this type
ClassToConstructByDefault if the derived class has not overridden, create a component of this type
bIsRequired true if the component is required and will always be created even if DoNotCreateDefaultSubobject was specified.
bIsTransient true if the component is being assigned to a transient property
References Outer, and UObject.
CreateDefaultSubobject() [2/3]
template<class TReturnType> TReturnType * FObjectInitializer::CreateDefaultSubobject (UObject * Outer, FName SubobjectName, bool bTransient = false) const inline
Create a component or subobject that will be instanced inside all instances of this class.
Parameters
TReturnType class of return type, all overrides must be of this type
Outer outer to construct the subobject in
SubobjectName name of the new component, this will be the same for all instances of this class
bTransient true if the component is being assigned to a transient property
Definition at line 1331 of file UObjectGlobals.h.
References CreateDefaultSubobject(), Outer, and UObject.
Referenced by CreateDefaultSubobject(), and CreateOptionalDefaultSubobject().
CreateDefaultSubobject() [3/3]
template<class TReturnType, class TClassToConstructByDefault> TReturnType * FObjectInitializer::CreateDefaultSubobject (UObject * Outer, FName SubobjectName, bool bTransient = false) const inline
Create a component or subobject, allows creating a child class and returning the parent class.
Parameters
TReturnType class of return type, all overrides must be of this type
TClassToConstructByDefault class to construct by default
Outer outer to construct the subobject in
SubobjectName name of the new component, this will be the same for all instances of this class
bTransient true if the component is being assigned to a transient property
Definition at line 1361 of file UObjectGlobals.h.
References CreateDefaultSubobject(), Outer, and UObject.
CreateEditorOnlyDefaultSubobject() [1/2]
template<class TReturnType> TReturnType * FObjectInitializer::CreateEditorOnlyDefaultSubobject (UObject * Outer, FName SubobjectName, bool bTransient = false) const inline
Create a component or subobject only to be used with the editor.
Parameters
TReturnType class of return type, all overrides must be of this type
Outer outer to construct the subobject in
SubobjectName name of the new component, this will be the same for all instances of this class
bTransient true if the component is being assigned to a transient property
Definition at line 1374 of file UObjectGlobals.h.
References CreateEditorOnlyDefaultSubobject(), Outer, and UObject.
Referenced by CreateEditorOnlyDefaultSubobject().
CreateEditorOnlyDefaultSubobject() [2/2]
UObject * FObjectInitializer::CreateEditorOnlyDefaultSubobject (UObject * Outer, FName SubobjectName, const UClass * ReturnType, bool bTransient = false) const
Create a component or subobject only to be used with the editor.
Parameters
Outer outer to construct the subobject in
SubobjectName name of the new component, this will be the same for all instances of this class
ReturnType type of the new component
bTransient true if the component is being assigned to a transient property
References Outer, and UObject.
CreateOptionalDefaultSubobject()
template<class TReturnType> TReturnType * FObjectInitializer::CreateOptionalDefaultSubobject (UObject * Outer, FName SubobjectName, bool bTransient = false) const inline
Create optional component or subobject.
Optional subobjects will not get created. if a derived class specifies DoNotCreateDefaultSubobject with the subobject name.
Parameters
TReturnType class of return type, all overrides must be of this type
Outer outer to construct the subobject in
SubobjectName name of the new component, this will be the same for all instances of this class
bTransient true if the component is being assigned to a transient property
Definition at line 1346 of file UObjectGlobals.h.
References CreateDefaultSubobject(), Outer, and UObject.
DoNotCreateDefaultSubobject()
const FObjectInitializer & FObjectInitializer::DoNotCreateDefaultSubobject (FName SubobjectName) const inline
Indicates that a base class should not create a component.
Parameters
SubobjectName name of the new component or subobject to not create
Definition at line 1426 of file UObjectGlobals.h.
References FObjectInitializer(), AssertIfSubobjectSetupIsNotAllowed(), and SubobjectOverrides.
DoNotCreateNestedDefaultSubobject() [1/2]
const FObjectInitializer & FObjectInitializer::DoNotCreateNestedDefaultSubobject (FStringView SubobjectName) const inline
Indicates that a subobject should not create a component if created using CreateOptionalDefaultSubobject.
Parameters
SubobjectName name of the new component or subobject to not create
Definition at line 1481 of file UObjectGlobals.h.
References FObjectInitializer(), AssertIfSubobjectSetupIsNotAllowed(), and SubobjectOverrides.
DoNotCreateNestedDefaultSubobject() [2/2]
const FObjectInitializer & FObjectInitializer::DoNotCreateNestedDefaultSubobject (TArrayView< const FName > SubobjectNames) const inline
Indicates that a subobject should not create a component if created using CreateOptionalDefaultSubobject.
Parameters
SubobjectName name of the new component or subobject to not create
Definition at line 1492 of file UObjectGlobals.h.
References FObjectInitializer(), AssertIfSubobjectSetupIsNotAllowed(), and SubobjectOverrides.
FinalizeSubobjectClassInitialization()
FORCEINLINE void FObjectInitializer::FinalizeSubobjectClassInitialization () inline
Definition at line 1504 of file UObjectGlobals.h.
References bSubobjectClassInitializationAllowed, and FORCEINLINE.
Get()
FObjectInitializer & FObjectInitializer::Get () static
Gets ObjectInitializer for the currently constructed object.
Can only be used inside of a constructor of UObject-derived class.
References FObjectInitializer().
Referenced by UActorComponent::UActorComponent(), UBoolProperty::UBoolProperty(), UBTService_DefaultFocus::UBTService_DefaultFocus(), UClass::UClass(), UGCObjectReferencer::UGCObjectReferencer(), UModel::UModel(), UPackage::UPackage(), UProperty::UProperty(), USceneComponent::USceneComponent(), and UCLASS().
GetArchetype()
FORCEINLINE UObject * FObjectInitializer::GetArchetype () const inline
Return the archetype that this object will copy properties from later.
Definition at line 1295 of file UObjectGlobals.h.
References FORCEINLINE, ObjectArchetype, and UObject.
GetClass()
UClass * FObjectInitializer::GetClass () const
Return the class of the object that is being constructed.
GetInstancingGraph()
FORCEINLINE struct FObjectInstancingGraph * FObjectInitializer::GetInstancingGraph () inline
Definition at line 1308 of file UObjectGlobals.h.
References FORCEINLINE, and InstanceGraph.
GetObj()
FORCEINLINE UObject * FObjectInitializer::GetObj () const inline
Return the object that is being constructed.
Definition at line 1303 of file UObjectGlobals.h.
References FORCEINLINE, Obj, and UObject.
InitNonNativeProperty()
bool FObjectInitializer::InitNonNativeProperty (FProperty * Property, UObject * Data) static private
Initializes a non-native property, according to the initialization rules.
If the property is non-native and does not have a zero contructor, it is inialized with the default value.
Parameters
Property Property to be initialized
Data Default data
Returns
Returns true if that property was a non-native one, otherwise false
References Property, and UObject.
InitProperties()
void FObjectInitializer::InitProperties (UObject * Obj, UClass * DefaultsClass, UObject * DefaultData, bool bCopyTransientsFromClassDefaults) static private
Binary initialize object properties to zero or defaults.
Parameters
Obj object to initialize data for
DefaultsClass the class to use for initializing the data
DefaultData the buffer containing the source data for the initialization
bCopyTransientsFromClassDefaults if true, copy the transients from the DefaultsClass defaults, otherwise copy the transients from DefaultData
References bCopyTransientsFromClassDefaults, Obj, and UObject.
Referenced by FScriptIntegrationObjectHelper::InitProperties().
InitSubobjectProperties()
bool FObjectInitializer::InitSubobjectProperties (bool bAllowInstancing) const private
Calls InitProperties for any default subobjects created through this ObjectInitializer.
Parameters
bAllowInstancing Indicates whether the object's components may be copied from their templates.
Returns
true if there are any subobjects which require instancing.
Referenced by FScriptIntegrationObjectHelper::InitSubobjectProperties().
InstanceSubobjects()
void FObjectInitializer::InstanceSubobjects (UClass * Class, bool bNeedInstancing, bool bNeedSubobjectInstancing) const private
Create copies of the object's components from their templates.
Parameters
Class Class of the object we are initializing
bNeedInstancing Indicates whether the object's components need to be instanced
bNeedSubobjectInstancing Indicates whether subobjects of the object's components need to be instanced
References Class.
Referenced by FScriptIntegrationObjectHelper::InstanceSubobjects().
IsInstancingAllowed()
bool FObjectInitializer::IsInstancingAllowed () const private
Referenced by FScriptIntegrationObjectHelper::InitSubobjectProperties().
PostConstructInit()
void FObjectInitializer::PostConstructInit () private
Finalizes a constructed UObject by initializing properties, instancing/initializing sub-objects, etc.
Referenced by FScriptIntegrationObjectHelper::PostConstructInitObject().
SetDefaultSubobjectClass() [1/2]
template<class T> const FObjectInitializer & FObjectInitializer::SetDefaultSubobjectClass (FName SubobjectName) const inline
Sets the class to use for a subobject defined in a base class, the class must be a subclass of the class used by the base class.
Parameters
SubobjectName name of the new component or subobject
Definition at line 1417 of file UObjectGlobals.h.
References FObjectInitializer(), and SetDefaultSubobjectClass().
SetDefaultSubobjectClass() [2/2]
const FObjectInitializer & FObjectInitializer::SetDefaultSubobjectClass (FName SubobjectName, const UClass * Class) const inline
Sets the class to use for a subobject defined in a base class, the class must be a subclass of the class used by the base class.
Parameters
SubobjectName name of the new component or subobject
Class The class to use for the specified subobject or component.
Definition at line 1405 of file UObjectGlobals.h.
References FObjectInitializer(), AssertIfSubobjectSetupIsNotAllowed(), Class, and SubobjectOverrides.
Referenced by SetDefaultSubobjectClass().
SetNestedDefaultSubobjectClass() [1/4]
template<class T> const FObjectInitializer & FObjectInitializer::SetNestedDefaultSubobjectClass (FStringView SubobjectName) const inline
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
Parameters
SubobjectName path to the new component or subobject
Definition at line 1462 of file UObjectGlobals.h.
References FObjectInitializer(), and SetNestedDefaultSubobjectClass().
SetNestedDefaultSubobjectClass() [2/4]
const FObjectInitializer & FObjectInitializer::SetNestedDefaultSubobjectClass (FStringView SubobjectName, const UClass * Class) const inline
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
Parameters
SubobjectName path to the new component or subobject
Class The class to use for the specified subobject or component.
Definition at line 1438 of file UObjectGlobals.h.
References FObjectInitializer(), AssertIfSubobjectSetupIsNotAllowed(), Class, and SubobjectOverrides.
Referenced by SetNestedDefaultSubobjectClass(), and SetNestedDefaultSubobjectClass().
SetNestedDefaultSubobjectClass() [3/4]
template<class T> const FObjectInitializer & FObjectInitializer::SetNestedDefaultSubobjectClass (TArrayView< const FName > SubobjectNames) const inline
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
Parameters
SubobjectName path to the new component or subobject
Definition at line 1472 of file UObjectGlobals.h.
References FObjectInitializer(), and SetNestedDefaultSubobjectClass().
SetNestedDefaultSubobjectClass() [4/4]
const FObjectInitializer & FObjectInitializer::SetNestedDefaultSubobjectClass (TArrayView< const FName > SubobjectNames, const UClass * Class) const inline
Sets the class to use for a subobject defined in a nested subobject, the class must be a subclass of the class used when calling CreateDefaultSubobject.
Parameters
SubobjectName path to the new component or subobject
Class The class to use for the specified subobject or component.
Definition at line 1450 of file UObjectGlobals.h.
References FObjectInitializer(), AssertIfSubobjectSetupIsNotAllowed(), Class, and SubobjectOverrides.
UE_DEPRECATED()
FObjectInitializer::UE_DEPRECATED (5. 0, "Use version that takes EObjectInitializerOptions")
Friends And Related Symbol Documentation
FScriptIntegrationObjectHelper
friend class FScriptIntegrationObjectHelper friend
Definition at line 1515 of file UObjectGlobals.h.
References FScriptIntegrationObjectHelper.
Referenced by FScriptIntegrationObjectHelper.
FStaticConstructObjectParameters
friend struct FStaticConstructObjectParameters friend
Definition at line 1700 of file UObjectGlobals.h.
References FStaticConstructObjectParameters.
Referenced by FStaticConstructObjectParameters.
InternalConstructor
template<class T> void InternalConstructor (const class FObjectInitializer & X) friend
References FObjectInitializer(), and X.
UObject
friend class UObject friend
Definition at line 1514 of file UObjectGlobals.h.
References UObject.
Referenced by FObjectInitializer(), FObjectInitializer::FSubobjectsToInit::FSubobjectInit::FSubobjectInit(), FObjectInitializer::FSubobjectsToInit::Add(), AssertIfInConstructor(), CreateDefaultSubobject(), CreateDefaultSubobject(), CreateEditorOnlyDefaultSubobject(), CreateEditorOnlyDefaultSubobject(), CreateOptionalDefaultSubobject(), GetArchetype(), GetObj(), InitNonNativeProperty(), InitProperties(), and UObject.
Field Documentation
bCopyTransientsFromClassDefaults
bool FObjectInitializer::bCopyTransientsFromClassDefaults private
if true, copy the transients from the DefaultsClass defaults, otherwise copy the transients from DefaultData
Definition at line 1673 of file UObjectGlobals.h.
Referenced by InitProperties(), and FScriptIntegrationObjectHelper::InitProperties().
bInCopyTransientsFromClassDefaults
UObject bool FObjectInitializer::bInCopyTransientsFromClassDefaults
Definition at line 1274 of file UObjectGlobals.h.
bInShouldInitializeProps
UObject bool bool FObjectInitializer::bInShouldInitializeProps
Definition at line 1274 of file UObjectGlobals.h.
bShouldInitializePropsFromArchetype
bool FObjectInitializer::bShouldInitializePropsFromArchetype private
If true, initialize the properties.
Definition at line 1675 of file UObjectGlobals.h.
bShouldSkipPostConstructInit
bool FObjectInitializer::bShouldSkipPostConstructInit {false} private
Definition at line 1676 of file UObjectGlobals.h.
bSubobjectClassInitializationAllowed
bool FObjectInitializer::bSubobjectClassInitializationAllowed = true private
Only true until ObjectInitializer has not reached the base UObject class.
Definition at line 1678 of file UObjectGlobals.h.
Referenced by FinalizeSubobjectClassInitialization().
ComponentInits
FSubobjectsToInit FObjectInitializer::ComponentInits mutable private
List of component classes to initialize after the C++ constructors.
Definition at line 1688 of file UObjectGlobals.h.
ConstructedSubobjects
TArray<FName, TInlineAllocator<8> > FObjectInitializer::ConstructedSubobjects mutable private
List of all subobject names constructed for this object.
Definition at line 1691 of file UObjectGlobals.h.
InInstanceGraph
UObject bool bool struct FObjectInstancingGraph* FObjectInitializer::InInstanceGraph
Initial value:
= nullptr)
        : FObjectInitializer(InObj, InObjectArchetype,
            (bInCopyTransientsFromClassDefaults ? EObjectInitializerOptions::CopyTransientsFromClassDefaults : EObjectInitializerOptions::None) |
            (bInShouldInitializeProps ? EObjectInitializerOptions::InitializeProperties : EObjectInitializerOptions::None),
            InInstanceGraph)
    {
    }
    1 FObjectInitializer(UObject* InObj, const FStaticConstructObjectParameters& StaticConstructParams, UE::RemoteObject::Serialization::FRemoteObjectConstructionOverrides* RemoteObjectOverides = nullptr)
Definition at line 1274 of file UObjectGlobals.h.
Referenced by FObjectInitializer().
InObjectArchetype
UObject* FObjectInitializer::InObjectArchetype
Definition at line 1274 of file UObjectGlobals.h.
Referenced by FObjectInitializer().
InstanceGraph
struct FObjectInstancingGraph* FObjectInitializer::InstanceGraph private
Instance graph.
Definition at line 1684 of file UObjectGlobals.h.
Referenced by GetInstancingGraph().
LastConstructedObject
UObject* FObjectInitializer::LastConstructedObject = nullptr private
Previously constructed object in the callstack.
Definition at line 1694 of file UObjectGlobals.h.
Obj
UObject* FObjectInitializer::Obj private
object to initialize, from static allocate object, after construction
Definition at line 1669 of file UObjectGlobals.h.
Referenced by GetObj(), and InitProperties().
ObjectArchetype
UObject* FObjectInitializer::ObjectArchetype private
object to copy properties from
Definition at line 1671 of file UObjectGlobals.h.
Referenced by GetArchetype().
PropertyInitCallback
TFunction<void()> FObjectInitializer::PropertyInitCallback private
Callbacks for custom property initialization before PostInitProperties gets called.
Definition at line 1697 of file UObjectGlobals.h.
PropertyPostInitCallbacks
TArray<TFunction<void()> > FObjectInitializer::PropertyPostInitCallbacks private
Definition at line 1698 of file UObjectGlobals.h.
Referenced by AddPropertyPostInitCallback().
SubobjectOverrides
FOverrides FObjectInitializer::SubobjectOverrides mutable private
List of component classes to override from derived classes.
Definition at line 1686 of file UObjectGlobals.h.
Referenced by DoNotCreateDefaultSubobject(), DoNotCreateNestedDefaultSubobject(), DoNotCreateNestedDefaultSubobject(), SetDefaultSubobjectClass(), SetNestedDefaultSubobjectClass(), and SetNestedDefaultSubobjectClass().
The documentation for this class was generated from the following file:
UObjectGlobals.h