Unreal Engine 5.6 C++ API: FChaosCacheObjectSpawner Class Reference
FChaosCacheObjectSpawner Class Reference
Chaos cache Manager spawner to create a new cache manager from the spawnable template.
#include "ChaosCacheObjectSpawner.h"
Public Member Functions
virtual int32 GetSpawnerPriority () const override
virtual bool IsEditor () const override
UE_DEPRECATED (5.5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") CHAOSCACHING_API FChaosCacheObjectSpawner()
UE_DEPRECATED (5.5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") CHAOSCACHING_API virtual UClass *GetSupportedTemplateType() const override
UE_DEPRECATED (5.5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") CHAOSCACHING_API virtual UObject *SpawnObject(FMovieSceneSpawnable &Spawnable
UE_DEPRECATED (5.5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") CHAOSCACHING_API virtual void DestroySpawnedObject(UObject &Object) override
UE_DEPRECATED (5.5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") static CHAOSCACHING_API TSharedRef< IMovieSceneObjectSpawner > CreateObjectSpawner()
Static method to create the object spawner.
Public Member Functions inherited from FLevelSequenceActorSpawner
virtual LEVELSEQUENCE_API void DestroySpawnedObject (UObject &Object) override
Destroy a specific previously spawned object.
virtual LEVELSEQUENCE_API UClass * GetSupportedTemplateType () const override
Returns the type of object we can spawn.
virtual LEVELSEQUENCE_API UObject * SpawnObject (FMovieSceneSpawnable &Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) override
Spawn an object for the specified GUID, from the specified sequence instance.
Public Member Functions inherited from IMovieSceneObjectSpawner
virtual ~IMovieSceneObjectSpawner ()
Virtual destructor.
virtual bool CanConvertSpawnableToPossessable (FMovieSceneSpawnable &Spawnable) const
Check whether the specified Spawnable can become a Possessable.
virtual bool CanSetupDefaultsForSpawnable (UObject *SpawnedObject) const
virtual TValueOrError< FNewSpawnable, FText > CreateNewSpawnableType (UObject &SourceObject, UMovieScene &OwnerMovieScene, UActorFactory *ActorFactory=nullptr)
Create a new spawnable type from the given source object.
virtual void SetupDefaultsForSpawnable (UObject *SpawnedObject, const FGuid &Guid, const TOptional< FTransformData > &TransformData, TSharedRef< ISequencer > Sequencer, USequencerSettings *Settings)
Setup a new spawnable object with some default tracks and keys.
Data Fields
FMovieSceneSequenceIDRef TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState override
FMovieSceneSequenceIDRef TemplateID
Additional Inherited Members
Static Public Member Functions inherited from FLevelSequenceActorSpawner
static LEVELSEQUENCE_API TSharedRef< IMovieSceneObjectSpawner > CreateObjectSpawner ()
Detailed Description
Chaos cache Manager spawner to create a new cache manager from the spawnable template.
Definition at line 8 of file ChaosCacheObjectSpawner.h.
Member Function Documentation
GetSpawnerPriority()
virtual int32 FChaosCacheObjectSpawner::GetSpawnerPriority () const inline override virtual
Returns
Spawner priority in order to sort the list of the spawners. If several spawners match the template type, the one with the highest priority will be picked.
Reimplemented from IMovieSceneObjectSpawner.
Definition at line 28 of file ChaosCacheObjectSpawner.h.
IsEditor()
virtual bool FChaosCacheObjectSpawner::IsEditor () const inline override virtual
Returns
true if this spawner is used in the editor, or false if it is purely runtime. We use this to prioritize the use of editor spawners when in editor
Reimplemented from IMovieSceneObjectSpawner.
Definition at line 27 of file ChaosCacheObjectSpawner.h.
References IsEditor().
Referenced by IsEditor().
UE_DEPRECATED() [1/5]
FChaosCacheObjectSpawner::UE_DEPRECATED (5. 5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/5]
FChaosCacheObjectSpawner::UE_DEPRECATED (5. 5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") const override
References FLevelSequenceActorSpawner::GetSupportedTemplateType(), override, and UE_DEPRECATED().
UE_DEPRECATED() [3/5]
FChaosCacheObjectSpawner::UE_DEPRECATED (5. 5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") &
References UE_DEPRECATED().
UE_DEPRECATED() [4/5]
FChaosCacheObjectSpawner::UE_DEPRECATED (5. 5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic") & override
References FLevelSequenceActorSpawner::DestroySpawnedObject(), Object, override, and UE_DEPRECATED().
UE_DEPRECATED() [5/5]
FChaosCacheObjectSpawner::UE_DEPRECATED (5. 5, "This has been deprecated as it is no longer necessary. We use UMovieSceneSpawnableChaosCache custom binding instead to handle this logic")
Static method to create the object spawner.
References FLevelSequenceActorSpawner::CreateObjectSpawner(), and UE_DEPRECATED().
Field Documentation
override
FMovieSceneSequenceIDRef TSharedRef<const UE::MovieScene::FSharedPlaybackState> SharedPlaybackState FChaosCacheObjectSpawner::override
Definition at line 23 of file ChaosCacheObjectSpawner.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
TemplateID
FMovieSceneSequenceIDRef FChaosCacheObjectSpawner::TemplateID
Definition at line 23 of file ChaosCacheObjectSpawner.h.
The documentation for this class was generated from the following file:
ChaosCacheObjectSpawner.h