Unreal Engine 5.6 C++ API: LayoutUtils.h File Reference
LayoutUtils.h File Reference
#include "CoreMinimal.h"
#include "ArrangedChildren.h"
#include "FlowDirection.h"
#include "Layout/Children.h"
#include "Margin.h"
#include "SlateRect.h"
#include "Templates/UnrealTypeTraits.h"
#include "Types/SlateStructs.h"
#include "Visibility.h"
#include "Widgets/SBoxPanel.h"
Data Structures
struct AlignmentArrangeResult
struct ArrangeUtils::GetChildAlignment< Orientation >
Gets the alignment of an axis-agnostic int32 so that we can do alignment on an axis without caring about its orientation.
struct ArrangeUtils::GetChildAlignment< Orient_Horizontal >
struct ArrangeUtils::GetChildAlignment< Orient_Vertical >
struct FSlotProxy
Represents a single slot, used to perform arrangement operations.
class TSlotProxyIterator< UE_REQUIRES >
A custom iterator for FSlotProxy implementations, with behavior similar to TPanelChildrenConstIterator.
struct UE::Slate::TSlotAccessor< SlotType, typename >
A wrapper for accessing slot parameters for a given SlotType.
struct UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >
Specialization for FSlotProxy (and derived).
struct UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< TBasicLayoutWidgetSlot< SlotType >, std::decay_t< SlotType > > &&std::is_base_of_v< TResizingWidgetSlotMixin< SlotType >, std::decay_t< SlotType > > > >
struct UE::Slate::TSlotIterator< SlotType, typename >
struct UE::Slate::TSlotIterator< SlotType, std::enable_if_t< std::is_base_of_v< FSlotBase, std::decay_t< SlotType > > > >
struct UE::Slate::TSlotIterator< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >
Namespaces
namespace ArrangeUtils
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Slate
Functions
template<EOrientation Orientation>
static AlignmentArrangeResult ArrangeUtils::AlignCenter (float AllottedSize, float ChildDesiredSize, const FMargin &SlotPadding, const float ContentScale=1.0f, bool bClampToParent=true)
Same as AlignChild but force the alignment to be center.
template<EOrientation Orientation, typename SlotType>
static AlignmentArrangeResult AlignChild (EFlowDirection InLayoutFlow, float AllottedSize, const SlotType &ChildToArrange, const FMargin &SlotPadding, const float &ContentScale=1.0f, bool bClampToParent=true)
template<EOrientation Orientation, typename SlotType>
static AlignmentArrangeResult AlignChild (EFlowDirection InLayoutFlow, float AllottedSize, float ChildDesiredSize, const SlotType &ChildToArrange, const FMargin &SlotPadding, const float &ContentScale=1.0f, bool bClampToParent=true)
Helper method to BoxPanel::ArrangeChildren.
template<EOrientation Orientation, typename SlotType>
static AlignmentArrangeResult AlignChild (float AllottedSize, const SlotType &ChildToArrange, const FMargin &SlotPadding, const float &ContentScale=1.0f, bool bClampToParent=true)
template<EOrientation Orientation, typename SlotType>
static AlignmentArrangeResult AlignChild (float AllottedSize, float ChildDesiredSize, const SlotType &ChildToArrange, const FMargin &SlotPadding, const float &ContentScale=1.0f, bool bClampToParent=true)
template<EOrientation Orientation>
static AlignmentArrangeResult ArrangeUtils::AlignFill (float AllottedSize, const FMargin &SlotPadding, const float ContentScale=1.0f)
Same as AlignChild but force the alignment to be fill.
template<EOrientation Orientation, typename InputChildrenType, typename InputSlotType UE_REQUIRES>
static void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const InputChildrenType &InChildren, const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, float InOffset, bool bInAllowShrink, FVector2D &OutArrangedSize)
Note that this accepts Child Proxies rather than the children themselves, allowing layout operations independent of the child widget array itself.
template<EOrientation Orientation, typename SlotType UE_REQUIRES>
static void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const TArrayView< SlotType > &Children, const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, float InOffset, bool bInAllowShrink, FVector2D &OutArrangedSize)
template<EOrientation Orientation, typename SlotType UE_REQUIRES>
static void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const TConstArrayView< SlotType > &Children, const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, float InOffset, bool bInAllowShrink, FVector2D &OutArrangedSize)
template<EOrientation Orientation, typename SlotType UE_REQUIRES>
static void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const TPanelChildren< SlotType > &Children, const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, float InOffset, bool bInAllowShrink)
template<typename SlotType>
static void ArrangeSingleChild (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, const SlotType &ChildSlot, const FVector2D &ContentScale)
template<typename SlotType>
static void ArrangeSingleChild (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, const SlotType &ChildSlot, const TAttribute< FVector2D > &ContentScale)
Arrange a ChildSlot within the AllottedGeometry and populate ArrangedChildren with the arranged result.
template<typename SlotType>
static void ArrangeSingleChild (EFlowDirection InFlowDirection, const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, const SlotType &ChildSlot, const FVector2D &ContentScale)
template<typename SlotType>
static void ArrangeSingleChild (EFlowDirection InFlowDirection, const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, const SlotType &ChildSlot, const TAttribute< FVector2D > &ContentScale)
UE::Slate::FDeprecateVector2DResult ComputePopupFitInRect (const FSlateRect &InAnchor, const FSlateRect &PopupRect, const EOrientation &Orientation, const FSlateRect &RectToFit, bool bAllowFlip=true)
Given information about a popup and the space available for displaying that popup, compute best placement for it.
static FMargin LayoutPaddingWithFlow (EFlowDirection InLayoutFlow, const FMargin &InPadding)
Function Documentation
AlignChild() [1/4]
template<EOrientation Orientation, typename SlotType> AlignmentArrangeResult AlignChild (EFlowDirection InLayoutFlow, float AllottedSize, const SlotType & ChildToArrange, const FMargin & SlotPadding, const float & ContentScale = 1.0f, bool bClampToParent = true) static
Definition at line 680 of file LayoutUtils.h.
References ArrangeUtils::GetChildAlignment< Orientation >::AsInt(), FMath::Max, FMath::Min, and Y.
AlignChild() [2/4]
template<EOrientation Orientation, typename SlotType> AlignmentArrangeResult AlignChild (EFlowDirection InLayoutFlow, float AllottedSize, float ChildDesiredSize, const SlotType & ChildToArrange, const FMargin & SlotPadding, const float & ContentScale = 1.0f, bool bClampToParent = true) static
Helper method to BoxPanel::ArrangeChildren.
Parameters
AllottedSize The size available to arrange the widget along the given orientation
ChildToArrange The widget and associated layout information
SlotPadding The padding to when aligning the child
ContentScale The scale to apply to the child before aligning it.
bClampToParent If true the child's size is clamped to the allotted size before alignment occurs, if false, the child's desired size is used, even if larger than the allotted size.
Returns
Offset and Size of widget
Definition at line 642 of file LayoutUtils.h.
References ArrangeUtils::GetChildAlignment< Orientation >::AsInt(), FMath::Max, and FMath::Min.
Referenced by AlignChild(), AlignChild(), ArrangeChildrenInStack(), ArrangeSingleChild(), ArrangeSingleChild(), and SNodePanel::SNode::OnArrangeChildren().
AlignChild() [3/4]
template<EOrientation Orientation, typename SlotType> AlignmentArrangeResult AlignChild (float AllottedSize, const SlotType & ChildToArrange, const FMargin & SlotPadding, const float & ContentScale = 1.0f, bool bClampToParent = true) static
Definition at line 726 of file LayoutUtils.h.
References AlignChild(), and LeftToRight.
AlignChild() [4/4]
template<EOrientation Orientation, typename SlotType> AlignmentArrangeResult AlignChild (float AllottedSize, float ChildDesiredSize, const SlotType & ChildToArrange, const FMargin & SlotPadding, const float & ContentScale = 1.0f, bool bClampToParent = true) static
Definition at line 674 of file LayoutUtils.h.
References AlignChild(), and LeftToRight.
ArrangeChildrenInStack() [1/4]
template<EOrientation Orientation, typename InputChildrenType, typename InputSlotType UE_REQUIRES> void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const InputChildrenType & InChildren, const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, float InOffset, bool bInAllowShrink, FVector2D & OutArrangedSize) static
Note that this accepts Child Proxies rather than the children themselves, allowing layout operations independent of the child widget array itself.
InputChildrenType supports both TPanelChildren<FSlot>, TArrayView/TConstArrayView<FSlotProxy> If the provided type is TArrayView (non-const), the SlotProxy ArrangedSize is written to.
Definition at line 798 of file LayoutUtils.h.
References FArrangedChildren::AddWidget(), AlignChild(), FMath::Clamp(), EVisibility::Collapsed, UE::Slate::TSlotAccessor< SlotType, typename >::GetDesiredSize(), UE::Slate::TSlotAccessor< SlotType, typename >::GetMaxSize(), UE::Slate::TSlotAccessor< SlotType, typename >::GetMinSize(), UE::Slate::TSlotAccessor< SlotType, typename >::GetPadding(), UE::Slate::TSlotAccessor< SlotType, typename >::GetShrinkSizeValue(), UE::Slate::TSlotAccessor< SlotType, typename >::GetSizeRule(), UE::Slate::TSlotAccessor< SlotType, typename >::GetSizeValue(), UE::Slate::TSlotAccessor< SlotType, typename >::GetVisibility(), TArray< InElementType, InAllocatorType >::Init(), FMath::IsNearlyZero(), Item, LayoutPaddingWithFlow(), UE::Slate::TSlotAccessor< SlotType, typename >::MakeArrangedWidget(), FMath::Max, UE::Math::TVector2< double >::Max(), MaxSize, FMath::Min, UE::Math::TVector2< double >::Min(), MinSize, FArrangedChildren::Num(), AlignmentArrangeResult::Offset, Pass, FArrangedChildren::Reserve(), AlignmentArrangeResult::Size, FSizeParam::SizeRule_Auto, FSizeParam::SizeRule_Stretch, FSizeParam::SizeRule_StretchContent, TSequenceHistory< HistorySize >::Size, UE_KINDA_SMALL_NUMBER, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by ArrangeChildrenInStack(), ArrangeChildrenInStack(), and ArrangeChildrenInStack().
ArrangeChildrenInStack() [2/4]
template<EOrientation Orientation, typename SlotType UE_REQUIRES> void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const TArrayView< SlotType > & Children, const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, float InOffset, bool bInAllowShrink, FVector2D & OutArrangedSize) static
Definition at line 1164 of file LayoutUtils.h.
References ArrangeChildrenInStack().
ArrangeChildrenInStack() [3/4]
template<EOrientation Orientation, typename SlotType UE_REQUIRES> void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const TConstArrayView< SlotType > & Children, const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, float InOffset, bool bInAllowShrink, FVector2D & OutArrangedSize) static
Definition at line 1155 of file LayoutUtils.h.
References ArrangeChildrenInStack().
ArrangeChildrenInStack() [4/4]
template<EOrientation Orientation, typename SlotType UE_REQUIRES> void ArrangeChildrenInStack (EFlowDirection InLayoutFlow, const TPanelChildren< SlotType > & Children, const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, float InOffset, bool bInAllowShrink) static
Definition at line 1173 of file LayoutUtils.h.
References ArrangeChildrenInStack(), and Unused.
ArrangeSingleChild() [1/4]
template<typename SlotType> void ArrangeSingleChild (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, const SlotType & ChildSlot, const FVector2D & ContentScale) static
Definition at line 762 of file LayoutUtils.h.
References ArrangeSingleChild(), and LeftToRight.
ArrangeSingleChild() [2/4]
template<typename SlotType> void ArrangeSingleChild (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, const SlotType & ChildSlot, const TAttribute< FVector2D > & ContentScale) static
Arrange a ChildSlot within the AllottedGeometry and populate ArrangedChildren with the arranged result.
The code makes certain assumptions about the type of ChildSlot.
Definition at line 737 of file LayoutUtils.h.
References ArrangeSingleChild(), and LeftToRight.
Referenced by ArrangeSingleChild(), and ArrangeSingleChild().
ArrangeSingleChild() [3/4]
template<typename SlotType> void ArrangeSingleChild (EFlowDirection InFlowDirection, const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, const SlotType & ChildSlot, const FVector2D & ContentScale) static
Definition at line 768 of file LayoutUtils.h.
References FArrangedChildren::Accepts(), FArrangedChildren::AddWidget(), AlignChild(), LayoutPaddingWithFlow(), AlignmentArrangeResult::Offset, AlignmentArrangeResult::Size, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
ArrangeSingleChild() [4/4]
template<typename SlotType> void ArrangeSingleChild (EFlowDirection InFlowDirection, const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, const SlotType & ChildSlot, const TAttribute< FVector2D > & ContentScale) static
Definition at line 743 of file LayoutUtils.h.
References FArrangedChildren::Accepts(), FArrangedChildren::AddWidget(), AlignChild(), TAttribute< ObjectType >::Get(), LayoutPaddingWithFlow(), AlignmentArrangeResult::Offset, AlignmentArrangeResult::Size, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
ComputePopupFitInRect()
UE::Slate::FDeprecateVector2DResult ComputePopupFitInRect (const FSlateRect & InAnchor, const FSlateRect & PopupRect, const EOrientation & Orientation, const FSlateRect & RectToFit, bool bAllowFlip = true)
Given information about a popup and the space available for displaying that popup, compute best placement for it.
Parameters
InAnchor Area relative to which popup is being created (e.g. the button part of a combo box)
PopupRect Proposed placement of popup; position may require adjustment.
Orientation Are we trying to show the popup above/below or left/right relative to the anchor?
RectToFit The space available for showing this popup; we want to fit entirely within it without clipping.
bAllowFlip Determines whether the popup can be flipped to the other side of the anchor when there is no space on the screen for it to fit at its preferred position.
Returns
A best position within the RectToFit such that none of the popup clips outside of the RectToFit.
LayoutPaddingWithFlow()
FMargin LayoutPaddingWithFlow (EFlowDirection InLayoutFlow, const FMargin & InPadding) static
Definition at line 1179 of file LayoutUtils.h.
References RightToLeft.
Referenced by ArrangeChildrenInStack(), ArrangeSingleChild(), and ArrangeSingleChild().