Unreal Engine 5.6 C++ API: FRenderTarget Class Reference
FRenderTarget Class Reference abstract
A render target.
#include "UnrealClient.h"
Public Member Functions
FRenderTarget ()
Default constructor.
virtual ~FRenderTarget ()
Destructor.
virtual EDisplayColorGamut GetDisplayColorGamut () const
virtual float GetDisplayGamma () const
virtual EDisplayOutputFormat GetDisplayOutputFormat () const
virtual FRHIGPUMask GetGPUMask (FRHICommandListImmediate &RHICmdList) const
Returns the GPU nodes on which to render this render target.
virtual const FTextureRHIRef & GetRenderTargetTexture () const
Accessor for the surface RHI when setting this render target.
virtual FRDGTextureRef GetRenderTargetTexture (FRDGBuilder &GraphBuilder) const
Returns a valid RDG texture for this render target.
virtual FUnorderedAccessViewRHIRef GetRenderTargetUAV () const
virtual bool GetSceneHDREnabled () const
virtual const FTextureRHIRef & GetShaderResourceTexture () const
Accessor for the surface RHI to use when reading the reading target (may differ from GetRenderTargetTexture() for some implementations like cubemaps)
virtual FIntPoint GetSizeXY () const =0
virtual bool HasToggleFreezeCommand ()
Returns if there is a command to toggle freezerendering.
virtual void ProcessToggleFreezeCommand ()
Handles freezing/unfreezing of rendering.
virtual bool ReadFloat16Pixels (TArray< FFloat16Color > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadLinearColorPixels (TArray< FLinearColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
bool ReadLinearColorPixelsPtr (FLinearColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadPixels (TArray< FColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
bool ReadPixelsPtr (FColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
UE_DEPRECATED (5.4, "Use the other ReadFloat16Pixels variant (ECubeFace can be set in FReadSurfaceDataFlags)") 1 bool ReadFloat16Pixels(TArray< FFloat16Color > &OutImageData
Reads the render target's displayed pixels into the given color buffer.
Static Public Member Functions
static float GetEngineDisplayGamma ()
Data Fields
ECubeFace CubeFace
Protected Attributes
FTextureRHIRef RenderTargetTextureRHI
Detailed Description
A render target.
Definition at line 29 of file UnrealClient.h.
Constructor & Destructor Documentation
FRenderTarget()
FRenderTarget::FRenderTarget ()
Default constructor.
~FRenderTarget()
virtual FRenderTarget::~FRenderTarget () virtual
Destructor.
Member Function Documentation
GetDisplayColorGamut()
virtual EDisplayColorGamut FRenderTarget::GetDisplayColorGamut () const inline virtual
Reimplemented in FDummyViewport, and FSceneViewport.
Definition at line 72 of file UnrealClient.h.
References sRGB_D65.
GetDisplayGamma()
virtual float FRenderTarget::GetDisplayGamma () const virtual
Returns
display gamma expected for rendering to this render target
Reimplemented in FPlanarReflectionRenderTarget, FSceneViewport, FSlateTextureRenderTarget2DResource, FTextureRenderTarget2DArrayResource, FTextureRenderTarget2DResource, FTextureRenderTargetCubeResource, FTextureRenderTargetResource, and FTextureRenderTargetVolumeResource.
GetDisplayOutputFormat()
virtual EDisplayOutputFormat FRenderTarget::GetDisplayOutputFormat () const inline virtual
Reimplemented in FDummyViewport, and FSceneViewport.
Definition at line 73 of file UnrealClient.h.
References SDR_sRGB.
GetEngineDisplayGamma()
float FRenderTarget::GetEngineDisplayGamma () static
GetGPUMask()
virtual FRHIGPUMask FRenderTarget::GetGPUMask (FRHICommandListImmediate & RHICmdList) const inline virtual
Returns the GPU nodes on which to render this render target.
Reimplemented in FPlanarReflectionRenderTarget, FTextureRenderTargetResource, and FViewport.
Definition at line 168 of file UnrealClient.h.
References GetGPUMask().
Referenced by GetGPUMask().
GetRenderTargetTexture() [1/2]
virtual const FTextureRHIRef & FRenderTarget::GetRenderTargetTexture () const virtual
Accessor for the surface RHI when setting this render target.
Returns
render target surface RHI resource
Reimplemented in FSceneViewport.
GetRenderTargetTexture() [2/2]
virtual FRDGTextureRef FRenderTarget::GetRenderTargetTexture (FRDGBuilder & GraphBuilder) const virtual
Returns a valid RDG texture for this render target.
GetRenderTargetUAV()
virtual FUnorderedAccessViewRHIRef FRenderTarget::GetRenderTargetUAV () const virtual
GetSceneHDREnabled()
virtual bool FRenderTarget::GetSceneHDREnabled () const inline virtual
Reimplemented in FDummyViewport, and FSceneViewport.
Definition at line 74 of file UnrealClient.h.
GetShaderResourceTexture()
virtual const FTextureRHIRef & FRenderTarget::GetShaderResourceTexture () const virtual
Accessor for the surface RHI to use when reading the reading target (may differ from GetRenderTargetTexture() for some implementations like cubemaps)
Returns
surface RHI resource
Reimplemented in FTextureRenderTargetResource.
GetSizeXY()
virtual FIntPoint FRenderTarget::GetSizeXY () const pure virtual
Implemented in FPlanarReflectionRenderTarget, FSlateTextureRenderTarget2DResource, FTextureRenderTarget2DArrayResource, FTextureRenderTarget2DResource, FTextureRenderTargetCubeResource, FTextureRenderTargetVolumeResource, FViewport::FHitProxyMap, and FViewport.
HasToggleFreezeCommand()
virtual bool FRenderTarget::HasToggleFreezeCommand () inline virtual
Returns if there is a command to toggle freezerendering.
Reimplemented in FViewport.
Definition at line 84 of file UnrealClient.h.
ProcessToggleFreezeCommand()
virtual void FRenderTarget::ProcessToggleFreezeCommand () inline virtual
Handles freezing/unfreezing of rendering.
Reimplemented in FViewport.
Definition at line 79 of file UnrealClient.h.
ReadFloat16Pixels()
virtual bool FRenderTarget::ReadFloat16Pixels (TArray< FFloat16Color > & OutImageData, FReadSurfaceDataFlags InFlags = FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect = FIntRect(0, 0, 0, 0)) virtual
Reads the render target's displayed pixels into the given color buffer.
Parameters
OutImageData - RGBA16F values will be stored in this buffer
InFlags - Additional information about how to to read the surface data (cube face, slice index, etc.)
InSrcRect - InSrcRect not specified means the whole rect
Returns
True if the read succeeded.
The default value for InFlags specifies RCM_UNorm which will cause values to be scaled into [0,1] ; use RCM_MinMax to retrieve values without change.
Unlike other RenderTarget Read functions, this only works if surface is PF_FloatRGBA exactly ; it does not convert. Prefer using FImageUtils::GetRenderTargetImage rather than calling this directly.
Reimplemented in FTextureRenderTargetVolumeResource.
References ReadFloat16Pixels().
Referenced by ReadFloat16Pixels().
ReadLinearColorPixels()
virtual bool FRenderTarget::ReadLinearColorPixels (TArray< FLinearColor > & OutImageData, FReadSurfaceDataFlags InFlags = FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect = FIntRect(0, 0, 0, 0)) virtual
Reads the render target's displayed pixels into the given color buffer.
Parameters
OutImageData - Linear color array to store the value
InFlags - Additional information about how to to read the surface data (cube face, slice index, etc.)
InSrcRect - InSrcRect not specified means the whole rect
Returns
True if the read succeeded.
The default value for InFlags specifies RCM_UNorm which will cause values to be scaled into [0,1] ; use RCM_MinMax to retrieve values without change.
This will convert whatever the pixel format is to FLinearColor (if supported). Prefer using FImageUtils::GetRenderTargetImage rather than calling this directly.
Reimplemented in FTextureRenderTargetVolumeResource.
References ReadLinearColorPixels().
Referenced by ReadLinearColorPixels().
ReadLinearColorPixelsPtr()
bool FRenderTarget::ReadLinearColorPixelsPtr (FLinearColor * OutImageBytes, FReadSurfaceDataFlags InFlags = FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect = FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
Parameters
OutImageBytes - Linear color array will be stored in this buffer. Buffer must be preallocated with the correct size!
InFlags - Additional information about how to to read the surface data (cube face, slice index, etc.)
InSrcRect - InSrcRect not specified means the whole rect
Returns
True if the read succeeded.
Ptr variant of this API just does an extra memcpy; prefer the TArray variant. Prefer using FImageUtils::GetRenderTargetImage rather than calling this directly.
References ReadLinearColorPixelsPtr().
Referenced by ReadLinearColorPixelsPtr().
ReadPixels()
virtual bool FRenderTarget::ReadPixels (TArray< FColor > & OutImageData, FReadSurfaceDataFlags InFlags = FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect = FIntRect(0, 0, 0, 0)) virtual
Reads the render target's displayed pixels into a preallocated color buffer.
Parameters
OutImageData - RGBA8 values will be stored in this buffer
InFlags - Additional information about how to to read the surface data (cube face, slice index, etc.)
InSrcRect - InSrcRect not specified means the whole rect
Returns
True if the read succeeded.
This will convert whatever the pixel format is to FColor Prefer using FImageUtils::GetRenderTargetImage rather than calling this directly.
The default value for InFlags specifies RCM_UNorm which will cause values to be scaled into [0,1] ; use RCM_MinMax to retrieve values without change.
If the RenderTarget surface is float linear, it will converted to SRGB FColor, if InFlags.bLinearToGamma is set (which is on by default). If the RenderTarget surface is U8, then the SRGB/not state is unchanged, the U8 values are retrieved unchanged in either Linear or SRGB. Gamma is handled correctly automatically by FImageUtils::GetRenderTargetImage
Reimplemented in FTextureRenderTarget2DArrayResource, and FTextureRenderTargetVolumeResource.
Referenced by FTextureRenderTarget2DArrayResource::GetDisplayGamma(), and FTextureRenderTargetCubeResource::UE_DEPRECATED().
ReadPixelsPtr()
bool FRenderTarget::ReadPixelsPtr (FColor * OutImageBytes, FReadSurfaceDataFlags InFlags = FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect = FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
Parameters
OutImageBytes - RGBA8 values will be stored in this buffer. Buffer must be preallocated with the correct size!
InFlags - Additional information about how to to read the surface data (cube face, slice index, etc.)
InSrcRect - InSrcRect not specified means the whole rect
Returns
True if the read succeeded.
Ptr variant of this API just does an extra memcpy; prefer the TArray variant. Prefer using FImageUtils::GetRenderTargetImage rather than calling this directly.
UE_DEPRECATED()
FRenderTarget::UE_DEPRECATED (5. 4, "Use the other ReadFloat16Pixels variant (ECubeFace can be set in FReadSurfaceDataFlags)") &
Reads the render target's displayed pixels into the given color buffer.
Parameters
OutImageData - RGBA16F values will be stored in this buffer
CubeFace - optional cube face for when reading from a cube render target
Returns
True if the read succeeded.
Field Documentation
CubeFace
ECubeFace FRenderTarget::CubeFace
Definition at line 123 of file UnrealClient.h.
RenderTargetTextureRHI
FTextureRHIRef FRenderTarget::RenderTargetTextureRHI protected
Definition at line 172 of file UnrealClient.h.
Referenced by FViewport::FHitProxyMap::GetHitProxyTexture(), and FPlanarReflectionRenderTarget::InitRHI().
The documentation for this class was generated from the following file:
UnrealClient.h