Unreal Engine 5.6 C++ API: TNetworkSimAuxBuffer< ElementType > Struct Template Reference
TNetworkSimAuxBuffer< ElementType > Struct Template Reference
#include "NetworkPredictionBuffer.h"
Data Structures
struct TInternal
Public Member Functions
TNetworkSimAuxBuffer (int32 Capacity)
TNetSimLazyWriterFunc< ElementType > LazyWriter (int32 Frame)
ElementType * operator[] (int32 Frame)
const ElementType * operator[] (int32 Frame) const
void Resize (int32 NewSize)
ElementType * WriteAtFrame (int32 Frame)
Private Member Functions
const ElementType * GetImpl (int32 Frame) const
void Init (int32 NewSize)
Private Attributes
TArray< TInternal > Elements
int32 HeadPosition = 0
int32 IndexMask = 0
Detailed Description
template<typename ElementType>
struct TNetworkSimAuxBuffer< ElementType >
Definition at line 50 of file NetworkPredictionBuffer.h.
Constructor & Destructor Documentation
TNetworkSimAuxBuffer()
template<typename ElementType> TNetworkSimAuxBuffer< ElementType >::TNetworkSimAuxBuffer (int32 Capacity) inline
Definition at line 52 of file NetworkPredictionBuffer.h.
References Init.
Member Function Documentation
GetImpl()
template<typename ElementType> const ElementType * TNetworkSimAuxBuffer< ElementType >::GetImpl (int32 Frame) const inline private
Definition at line 129 of file NetworkPredictionBuffer.h.
References TNetworkSimAuxBuffer< ElementType >::TInternal::Element, Elements, TNetworkSimAuxBuffer< ElementType >::TInternal::Frame, HeadPosition, IndexMask, and FMath::Max.
Referenced by operator[](), and operator[]().
Init()
template<typename ElementType> void TNetworkSimAuxBuffer< ElementType >::Init (int32 NewSize) inline private
Definition at line 122 of file NetworkPredictionBuffer.h.
References Elements, and IndexMask.
LazyWriter()
template<typename ElementType> TNetSimLazyWriterFunc< ElementType > TNetworkSimAuxBuffer< ElementType >::LazyWriter (int32 Frame) inline
Definition at line 93 of file NetworkPredictionBuffer.h.
operator[]() [1/2]
template<typename ElementType> ElementType * TNetworkSimAuxBuffer< ElementType >::operator[] (int32 Frame) inline
Definition at line 57 of file NetworkPredictionBuffer.h.
References GetImpl().
operator[]() [2/2]
template<typename ElementType> const ElementType * TNetworkSimAuxBuffer< ElementType >::operator[] (int32 Frame) const inline
Definition at line 62 of file NetworkPredictionBuffer.h.
References GetImpl().
Resize()
template<typename ElementType> void TNetworkSimAuxBuffer< ElementType >::Resize (int32 NewSize) inline
Definition at line 99 of file NetworkPredictionBuffer.h.
References check, Elements, HeadPosition, IndexMask, Init, FMath::Min, MoveTemp(), and TArray< InElementType, InAllocatorType >::Num().
WriteAtFrame()
template<typename ElementType> ElementType * TNetworkSimAuxBuffer< ElementType >::WriteAtFrame (int32 Frame) inline
Definition at line 68 of file NetworkPredictionBuffer.h.
References TNetworkSimAuxBuffer< ElementType >::TInternal::Element, Elements, TNetworkSimAuxBuffer< ElementType >::TInternal::Frame, HeadPosition, IndexMask, and FMath::Max.
Field Documentation
Elements
template<typename ElementType> TArray<TInternal> TNetworkSimAuxBuffer< ElementType >::Elements private
Definition at line 152 of file NetworkPredictionBuffer.h.
Referenced by GetImpl(), Init(), Resize(), and WriteAtFrame().
HeadPosition
template<typename ElementType> int32 TNetworkSimAuxBuffer< ElementType >::HeadPosition = 0 private
Definition at line 146 of file NetworkPredictionBuffer.h.
Referenced by GetImpl(), Resize(), and WriteAtFrame().
IndexMask
template<typename ElementType> int32 TNetworkSimAuxBuffer< ElementType >::IndexMask = 0 private
Definition at line 149 of file NetworkPredictionBuffer.h.
Referenced by GetImpl(), Init(), Resize(), and WriteAtFrame().
The documentation for this struct was generated from the following file:
NetworkPredictionBuffer.h