Unreal Engine 5.6 C++ API: FSlateAttributeMetaData Class Reference
FSlateAttributeMetaData Class Reference
#include "SlateAttributeMetaData.h"
Data Structures
struct FGetterItem
Public Types
enum class EInvalidationPermission : uint8 {
AllowInvalidationIfConstructed , AllowInvalidation , DelayInvalidation , DenyInvalidation ,
DenyAndClearDelayedInvalidation
}
Public Member Functions
FSlateAttributeMetaData ()=default
FSlateAttributeMetaData (const FSlateAttributeMetaData &)=delete
int32 GetRegisteredAffectVisibilityAttributeCount () const
int32 GetRegisteredAttributeCount () const
bool IsBound (const FSlateAttributeBase &Attribute) const
FSlateAttributeMetaData & operator= (const FSlateAttributeMetaData &)=delete
SLATE_METADATA_TYPE (FSlateAttributeMetaData, ISlateMetaData)
Public Member Functions inherited from ISlateMetaData
virtual ~ISlateMetaData ()
Virtual destructor.
template<class TType>
bool IsOfType () const
Check if this metadata operation can cast safely to the specified template type.
Static Public Member Functions
static void ApplyDelayedInvalidation (SWidget &OwningWidget)
Apply any delayed invalidation previously delayed with EInvalidationPermission::DelayInvalidation.
static FSlateAttributeMetaData * FindMetaData (const SWidget &OwningWidget)
static TArray< FName > GetAttributeNames (const SWidget &OwningWidget)
Get the name of all the attributes, if available.
static void UpdateAllAttributes (SWidget &OwningWidget, EInvalidationPermission InvalidationStyle)
Update all the attributes.
static void UpdateChildrenOnlyVisibilityAttributes (SWidget &OwningWidget, EInvalidationPermission InvalidationStyle, bool bRecursive)
Execute UpdateOnlyVisibilityAttributes on every children of the widget.
static void UpdateExceptVisibilityAttributes (SWidget &OwningWidget, EInvalidationPermission InvalidationStyle)
Update attributes that are NOT responsible to change visibility of the widget.
static void UpdateOnlyVisibilityAttributes (SWidget &OwningWidget, EInvalidationPermission InvalidationStyle)
Update attributes that are responsible to change visibility of the widget.
Private Types
using ESlateAttributeType = SlateAttributePrivate::ESlateAttributeType
using ISlateAttributeContainer = SlateAttributePrivate::ISlateAttributeContainer
using ISlateAttributeGetter = SlateAttributePrivate::ISlateAttributeGetter
Private Member Functions
int32 IndexOfAttribute (const FSlateAttributeBase &Attribute) const
bool InvalidateWidgetAttribute (SWidget &OwningWidget, const FSlateAttributeBase &Attribute, EInvalidateWidgetReason Reason)
void RegisterContainAttributeImpl (ISlateAttributeContainer &OwningContainer, SWidget &OwningWidget, FSlateAttributeBase &Attribute, TUniquePtr< ISlateAttributeGetter > &&Getter)
void RegisterManagedAttributeImpl (SWidget &OwningWidget, FSlateAttributeBase &Attribute, TUniquePtr< ISlateAttributeGetter > &&Getter)
void RegisterMemberAttributeImpl (SWidget &OwningWidget, FSlateAttributeBase &Attribute, TUniquePtr< ISlateAttributeGetter > &&Getter)
void RemoveMetaDataIfNeeded (SWidget &OwningWidget, bool bRemoved) const
bool UnregisterAttributeImpl (const FSlateAttributeBase &Attribute)
void UpdateAttributesImpl (SWidget &OwningWidget, EInvalidationPermission InvaldiationStyle, int32 StartIndex, int32 IndexNum)
Static Private Member Functions
static SlateAttributePrivate::ISlateAttributeGetter * GetAttributeGetter (const SWidget &OwningWidget, const FSlateAttributeBase &Attribute)
static FDelegateHandle GetAttributeGetterHandle (const SWidget &OwningWidget, const FSlateAttributeBase &Attribute)
static void InvalidateWidget (ISlateAttributeContainer &OwningContainer, const FSlateAttributeBase &Attribute, ESlateAttributeType AttributeType, EInvalidateWidgetReason Reason)
static void InvalidateWidget (SWidget &OwningWidget, const FSlateAttributeBase &Attribute, ESlateAttributeType AttributeType, EInvalidateWidgetReason Reason)
static bool IsAttributeBound (const SWidget &OwningWidget, const FSlateAttributeBase &Attribute)
static void MoveAttribute (const SWidget &OwningWidget, FSlateAttributeBase &NewAttribute, ESlateAttributeType AttributeType, const FSlateAttributeBase *PreviousAttribute)
static void RegisterAttribute (ISlateAttributeContainer &OwningContainer, FSlateAttributeBase &Attribute, ESlateAttributeType AttributeType, TUniquePtr< ISlateAttributeGetter > &&Wrapper)
static void RegisterAttribute (SWidget &OwningWidget, FSlateAttributeBase &Attribute, ESlateAttributeType AttributeType, TUniquePtr< ISlateAttributeGetter > &&Wrapper)
static void RemoveContainerWidget (SWidget &Widget, ISlateAttributeContainer &Container)
static bool UnregisterAttribute (ISlateAttributeContainer &OwningContainer, const FSlateAttributeBase &Attribute)
static bool UnregisterAttribute (SWidget &OwningWidget, const FSlateAttributeBase &Attribute)
static void UpdateAttribute (SWidget &OwningWidget, FSlateAttributeBase &Attribute)
static void UpdateContainerSortOrder (SWidget &Widget, ISlateAttributeContainer &Container)
Private Attributes
uint8 AffectVisibilityCounter = 0
TArray< FGetterItem, TInlineAllocator< 4 > > Attributes
EInvalidateWidgetReason CachedInvalidationReason = EInvalidateWidgetReason::None
Friends
const TCHAR * DebugSlateAttribute (const SWidget *Widget, int32 Index)
Helper function that can be used inside the debuggers watch window.
Additional Inherited Members
Protected Member Functions inherited from ISlateMetaData
virtual bool IsOfTypeImpl (const FName &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
Detailed Description
Definition at line 17 of file SlateAttributeMetaData.h.
Member Typedef Documentation
ESlateAttributeType
using FSlateAttributeMetaData::ESlateAttributeType = SlateAttributePrivate::ESlateAttributeType private
Definition at line 100 of file SlateAttributeMetaData.h.
ISlateAttributeContainer
using FSlateAttributeMetaData::ISlateAttributeContainer = SlateAttributePrivate::ISlateAttributeContainer private
Definition at line 99 of file SlateAttributeMetaData.h.
ISlateAttributeGetter
using FSlateAttributeMetaData::ISlateAttributeGetter = SlateAttributePrivate::ISlateAttributeGetter private
Definition at line 101 of file SlateAttributeMetaData.h.
Member Enumeration Documentation
EInvalidationPermission
enum class FSlateAttributeMetaData::EInvalidationPermission : uint8 strong
Enumerator
AllowInvalidationIfConstructed
Invalidate the widget if it's needed and it's construction phase is completed.
AllowInvalidation
Invalidate the widget if it's needed.
DelayInvalidation
Cache the invalidation.
On any future update, if it's needed, invalidate the widget.
DenyInvalidation
Never invalidate the widget.
DenyAndClearDelayedInvalidation
Never invalidate the widget and clear any delayed invalidation.
Definition at line 33 of file SlateAttributeMetaData.h.
Constructor & Destructor Documentation
FSlateAttributeMetaData() [1/2]
FSlateAttributeMetaData::FSlateAttributeMetaData () default
Referenced by FSlateAttributeMetaData(), FindMetaData(), operator=(), and SLATE_METADATA_TYPE().
FSlateAttributeMetaData() [2/2]
FSlateAttributeMetaData::FSlateAttributeMetaData (const FSlateAttributeMetaData &) delete
References FSlateAttributeMetaData().
Member Function Documentation
ApplyDelayedInvalidation()
void FSlateAttributeMetaData::ApplyDelayedInvalidation (SWidget & OwningWidget) static
Apply any delayed invalidation previously delayed with EInvalidationPermission::DelayInvalidation.
FindMetaData()
FSlateAttributeMetaData * FSlateAttributeMetaData::FindMetaData (const SWidget & OwningWidget) static
Returns
the instance associated to the SWidget (if it exists).
References FSlateAttributeMetaData().
GetAttributeGetter()
SlateAttributePrivate::ISlateAttributeGetter * FSlateAttributeMetaData::GetAttributeGetter (const SWidget & OwningWidget, const FSlateAttributeBase & Attribute) static private
References Attribute.
GetAttributeGetterHandle()
FDelegateHandle FSlateAttributeMetaData::GetAttributeGetterHandle (const SWidget & OwningWidget, const FSlateAttributeBase & Attribute) static private
References Attribute.
GetAttributeNames()
TArray< FName > FSlateAttributeMetaData::GetAttributeNames (const SWidget & OwningWidget) static
Get the name of all the attributes, if available.
GetRegisteredAffectVisibilityAttributeCount()
int32 FSlateAttributeMetaData::GetRegisteredAffectVisibilityAttributeCount () const inline
Definition at line 83 of file SlateAttributeMetaData.h.
References AffectVisibilityCounter.
GetRegisteredAttributeCount()
int32 FSlateAttributeMetaData::GetRegisteredAttributeCount () const inline
Definition at line 78 of file SlateAttributeMetaData.h.
References Attributes.
IndexOfAttribute()
int32 FSlateAttributeMetaData::IndexOfAttribute (const FSlateAttributeBase & Attribute) const inline private
Definition at line 129 of file SlateAttributeMetaData.h.
References Attribute, Attributes, and Item.
Referenced by IsBound().
InvalidateWidget() [1/2]
void FSlateAttributeMetaData::InvalidateWidget (ISlateAttributeContainer & OwningContainer, const FSlateAttributeBase & Attribute, ESlateAttributeType AttributeType, EInvalidateWidgetReason Reason) static private
References Attribute.
InvalidateWidget() [2/2]
void FSlateAttributeMetaData::InvalidateWidget (SWidget & OwningWidget, const FSlateAttributeBase & Attribute, ESlateAttributeType AttributeType, EInvalidateWidgetReason Reason) static private
References Attribute.
InvalidateWidgetAttribute()
bool FSlateAttributeMetaData::InvalidateWidgetAttribute (SWidget & OwningWidget, const FSlateAttributeBase & Attribute, EInvalidateWidgetReason Reason) private
References Attribute.
IsAttributeBound()
bool FSlateAttributeMetaData::IsAttributeBound (const SWidget & OwningWidget, const FSlateAttributeBase & Attribute) static private
References Attribute.
IsBound()
bool FSlateAttributeMetaData::IsBound (const FSlateAttributeBase & Attribute) const inline
Definition at line 73 of file SlateAttributeMetaData.h.
References Attribute, INDEX_NONE, and IndexOfAttribute().
MoveAttribute()
void FSlateAttributeMetaData::MoveAttribute (const SWidget & OwningWidget, FSlateAttributeBase & NewAttribute, ESlateAttributeType AttributeType, const FSlateAttributeBase * PreviousAttribute) static private
operator=()
FSlateAttributeMetaData & FSlateAttributeMetaData::operator= (const FSlateAttributeMetaData &) delete
References FSlateAttributeMetaData().
RegisterAttribute() [1/2]
void FSlateAttributeMetaData::RegisterAttribute (ISlateAttributeContainer & OwningContainer, FSlateAttributeBase & Attribute, ESlateAttributeType AttributeType, TUniquePtr< ISlateAttributeGetter > && Wrapper) static private
References Attribute.
RegisterAttribute() [2/2]
void FSlateAttributeMetaData::RegisterAttribute (SWidget & OwningWidget, FSlateAttributeBase & Attribute, ESlateAttributeType AttributeType, TUniquePtr< ISlateAttributeGetter > && Wrapper) static private
References Attribute.
RegisterContainAttributeImpl()
void FSlateAttributeMetaData::RegisterContainAttributeImpl (ISlateAttributeContainer & OwningContainer, SWidget & OwningWidget, FSlateAttributeBase & Attribute, TUniquePtr< ISlateAttributeGetter > && Getter) private
References Attribute.
RegisterManagedAttributeImpl()
void FSlateAttributeMetaData::RegisterManagedAttributeImpl (SWidget & OwningWidget, FSlateAttributeBase & Attribute, TUniquePtr< ISlateAttributeGetter > && Getter) private
References Attribute.
RegisterMemberAttributeImpl()
void FSlateAttributeMetaData::RegisterMemberAttributeImpl (SWidget & OwningWidget, FSlateAttributeBase & Attribute, TUniquePtr< ISlateAttributeGetter > && Getter) private
References Attribute.
RemoveContainerWidget()
void FSlateAttributeMetaData::RemoveContainerWidget (SWidget & Widget, ISlateAttributeContainer & Container) static private
References Container.
RemoveMetaDataIfNeeded()
void FSlateAttributeMetaData::RemoveMetaDataIfNeeded (SWidget & OwningWidget, bool bRemoved) const private
SLATE_METADATA_TYPE()
FSlateAttributeMetaData::SLATE_METADATA_TYPE (FSlateAttributeMetaData , ISlateMetaData)
References FSlateAttributeMetaData().
UnregisterAttribute() [1/2]
bool FSlateAttributeMetaData::UnregisterAttribute (ISlateAttributeContainer & OwningContainer, const FSlateAttributeBase & Attribute) static private
References Attribute.
UnregisterAttribute() [2/2]
bool FSlateAttributeMetaData::UnregisterAttribute (SWidget & OwningWidget, const FSlateAttributeBase & Attribute) static private
References Attribute.
UnregisterAttributeImpl()
bool FSlateAttributeMetaData::UnregisterAttributeImpl (const FSlateAttributeBase & Attribute) private
References Attribute.
UpdateAllAttributes()
void FSlateAttributeMetaData::UpdateAllAttributes (SWidget & OwningWidget, EInvalidationPermission InvalidationStyle) static
Update all the attributes.
Parameters
InvalidationStyle if we should invalidate the widget.
UpdateAttribute()
void FSlateAttributeMetaData::UpdateAttribute (SWidget & OwningWidget, FSlateAttributeBase & Attribute) static private
References Attribute.
UpdateAttributesImpl()
void FSlateAttributeMetaData::UpdateAttributesImpl (SWidget & OwningWidget, EInvalidationPermission InvaldiationStyle, int32 StartIndex, int32 IndexNum) private
UpdateChildrenOnlyVisibilityAttributes()
void FSlateAttributeMetaData::UpdateChildrenOnlyVisibilityAttributes (SWidget & OwningWidget, EInvalidationPermission InvalidationStyle, bool bRecursive) static
Execute UpdateOnlyVisibilityAttributes on every children of the widget.
Parameters
InvalidationStyle if we should invalidate the widget.
UpdateContainerSortOrder()
void FSlateAttributeMetaData::UpdateContainerSortOrder (SWidget & Widget, ISlateAttributeContainer & Container) static private
References Container.
UpdateExceptVisibilityAttributes()
void FSlateAttributeMetaData::UpdateExceptVisibilityAttributes (SWidget & OwningWidget, EInvalidationPermission InvalidationStyle) static
Update attributes that are NOT responsible to change visibility of the widget.
Parameters
InvalidationStyle if we should invalidate the widget.
UpdateOnlyVisibilityAttributes()
void FSlateAttributeMetaData::UpdateOnlyVisibilityAttributes (SWidget & OwningWidget, EInvalidationPermission InvalidationStyle) static
Update attributes that are responsible to change visibility of the widget.
Parameters
InvalidationStyle if we should invalidate the widget.
Friends And Related Symbol Documentation
DebugSlateAttribute
const TCHAR * DebugSlateAttribute (const SWidget * Widget, int32 Index) friend
Helper function that can be used inside the debuggers watch window.
E.g. "DebugSlateAttribute(this, 0)" E.g. "DebugSlateAttribute((SWidget*)(0x123456789), 0)"
Field Documentation
AffectVisibilityCounter
uint8 FSlateAttributeMetaData::AffectVisibilityCounter = 0 private
Definition at line 194 of file SlateAttributeMetaData.h.
Referenced by GetRegisteredAffectVisibilityAttributeCount().
Attributes
TArray<FGetterItem, TInlineAllocator<4> > FSlateAttributeMetaData::Attributes private
Definition at line 188 of file SlateAttributeMetaData.h.
Referenced by GetRegisteredAttributeCount(), and IndexOfAttribute().
CachedInvalidationReason
EInvalidateWidgetReason FSlateAttributeMetaData::CachedInvalidationReason = EInvalidateWidgetReason::None private
Definition at line 193 of file SlateAttributeMetaData.h.
The documentation for this class was generated from the following file:
SlateAttributeMetaData.h