Unreal Engine 5.6 C++ API: FAsciiSet Class Reference
FAsciiSet Class Reference
ASCII character bitset useful for fast and readable parsing.
#include "AsciiSet.h"
Data Structures
struct InitData
Public Member Functions
template<typename CharType, int N>
constexpr FAsciiSet (const CharType(&Chars)[N])
template<typename CharType>
constexpr FORCEINLINE bool Contains (CharType Char) const
Returns true if a character is part of the set.
constexpr FORCEINLINE FAsciiSet operator& (FAsciiSet OtherSet) const
Create new set containing only the characters that exist in both this and another specified set.
constexpr FORCEINLINE FAsciiSet operator+ (char Char) const
Create new set with specified character in it.
constexpr FORCEINLINE FAsciiSet operator| (FAsciiSet OtherSet) const
Create new set containing the combination of this set and another.
constexpr FORCEINLINE FAsciiSet operator~ () const
Create new set containing inverse set of characters - likely including null-terminator.
template<typename CharType>
constexpr FORCEINLINE uint64 Test (CharType Char) const
Returns non-zero if a character is part of the set.
Static Public Member Functions
template<class CharType>
static constexpr const CharType * FindFirstOrEnd (const CharType *Str, FAsciiSet Set)
Find first character of string inside set or end pointer.
template<class CharType>
static constexpr const CharType * FindLastOrEnd (const CharType *Str, FAsciiSet Set)
Find last character of string inside set or end pointer.
template<class StringType>
static constexpr StringType FindPrefixWith (const StringType &Str, FAsciiSet Set)
Get initial substring with all characters in set.
template<class StringType>
static constexpr StringType FindPrefixWithout (const StringType &Str, FAsciiSet Set)
Get initial substring with no characters in set.
template<class StringType>
static constexpr StringType FindSuffixWith (const StringType &Str, FAsciiSet Set)
Get trailing substring with all characters in set.
template<class StringType>
static constexpr StringType FindSuffixWithout (const StringType &Str, FAsciiSet Set)
Get trailing substring with no characters in set.
template<typename CharType>
static constexpr bool HasAny (const CharType *Str, FAsciiSet Set)
Test if string contains any character in set.
template<class StringType>
static constexpr bool HasAny (const StringType &Str, FAsciiSet Set)
Test if string contains any character in set.
template<typename CharType>
static constexpr bool HasNone (const CharType *Str, FAsciiSet Set)
Test if string contains no character in set.
template<class StringType>
static constexpr bool HasNone (const StringType &Str, FAsciiSet Set)
Test if string contains no character in set.
template<typename CharType>
static constexpr bool HasOnly (const CharType *Str, FAsciiSet Set)
Test if string contains any character outside of set.
template<class StringType>
static constexpr bool HasOnly (const StringType &Str, FAsciiSet Set)
Test if string contains any character outside of set.
template<typename CharType>
static constexpr const CharType * Skip (const CharType *Str, FAsciiSet Set)
Find first character of string outside of set.
template<class StringType>
static constexpr StringType TrimPrefixWith (const StringType &Str, FAsciiSet Set)
Trim initial characters in set.
template<class StringType>
static constexpr StringType TrimPrefixWithout (const StringType &Str, FAsciiSet Set)
Trim initial characters not in set.
template<class StringType>
static constexpr StringType TrimSuffixWith (const StringType &Str, FAsciiSet Set)
Trim trailing characters in set.
template<class StringType>
static constexpr StringType TrimSuffixWithout (const StringType &Str, FAsciiSet Set)
Trim trailing characters not in set.
Private Types
enum class EDir { Forward , Reverse }
enum class EInclude { Members , NonMembers }
enum class EKeep { Head , Tail }
Private Member Functions
constexpr FAsciiSet (InitData Bitset)
constexpr FAsciiSet (uint64 Lo, uint64 Hi)
constexpr FORCEINLINE uint64 TestImpl (uint32 Char) const
Static Private Member Functions
template<EInclude Include, typename CharType>
static constexpr const CharType * FindFirst (FAsciiSet Set, const CharType *It, const CharType *End)
template<EInclude Include, typename CharType>
static constexpr const CharType * FindLast (FAsciiSet Set, const CharType *It, const CharType *End)
template<EDir Dir, EInclude Include, EKeep Keep, class StringType>
static constexpr StringType Scan (const StringType &Str, FAsciiSet Set)
static constexpr FORCEINLINE void SetImpl (InitData &Bitset, uint32 Char)
template<typename CharType, int N>
static constexpr InitData StringToBitset (const CharType(&Chars)[N])
Private Attributes
uint64 HiMask
uint64 LoMask
Static Private Attributes
static constexpr uint64 NilMask = uint64(1) << '\0'
Detailed Description
ASCII character bitset useful for fast and readable parsing.
Entirely constexpr. Works with both wide and narrow strings.
Example use cases:
constexpr FAsciiSet WhitespaceCharacters(" \v\f\t\r\n"); bool bIsWhitespace = WhitespaceCharacters.Test(MyChar); const char* HelloWorld = FAsciiSet::Skip(" \t\tHello world!", WhitespaceCharacters);
constexpr FAsciiSet XmlEscapeChars("&<>\"'"); check(FAsciiSet::HasNone(EscapedXmlString, XmlEscapeChars));
constexpr FAsciiSet Delimiters(".:;"); const TCHAR* DelimiterOrEnd = FAsciiSet::FindFirstOrEnd(PrefixedName, Delimiters); FString Prefix(PrefixedName, DelimiterOrEnd - PrefixedName);
constexpr FAsciiSet Slashes("/\\"); const TCHAR* SlashOrEnd = FAsciiSet::FindLastOrEnd(PathName, Slashes); const TCHAR* FileName = *SlashOrEnd ? SlashOrEnd + 1 : PathName;
Definition at line 29 of file AsciiSet.h.
Member Enumeration Documentation
EDir
enum class FAsciiSet::EDir strong private
Enumerator
Forward
Reverse
Definition at line 221 of file AsciiSet.h.
EInclude
enum class FAsciiSet::EInclude strong private
Enumerator
Members
NonMembers
Definition at line 222 of file AsciiSet.h.
EKeep
enum class FAsciiSet::EKeep strong private
Enumerator
Head
Tail
Definition at line 223 of file AsciiSet.h.
Constructor & Destructor Documentation
FAsciiSet() [1/3]
template<typename CharType, int N> FAsciiSet::FAsciiSet (const CharType(&) Chars[N]) inline constexpr
Definition at line 33 of file AsciiSet.h.
References FAsciiSet(), and StringToBitset().
Referenced by FAsciiSet(), FindFirst(), FindFirstOrEnd(), FindLast(), FindLastOrEnd(), FindPrefixWith(), FindPrefixWithout(), FindSuffixWith(), FindSuffixWithout(), HasAny(), HasAny(), HasNone(), HasNone(), HasOnly(), HasOnly(), operator&(), operator+(), operator|(), operator~(), Scan(), Skip(), TrimPrefixWith(), TrimPrefixWithout(), TrimSuffixWith(), and TrimSuffixWithout().
FAsciiSet() [2/3]
FAsciiSet::FAsciiSet (InitData Bitset) inline constexpr private
Definition at line 286 of file AsciiSet.h.
References HiMask, and LoMask.
FAsciiSet() [3/3]
FAsciiSet::FAsciiSet (uint64 Lo, uint64 Hi) inline constexpr private
Definition at line 290 of file AsciiSet.h.
References HiMask, and LoMask.
Member Function Documentation
Contains()
template<typename CharType> FORCEINLINE bool FAsciiSet::Contains (CharType Char) const inline constexpr
Returns true if a character is part of the set.
Definition at line 39 of file AsciiSet.h.
References FORCEINLINE, TestImpl(), and TChar< CharType >::ToUnsigned().
FindFirst()
template<EInclude Include, typename CharType> constexpr const CharType * FAsciiSet::FindFirst (FAsciiSet Set, const CharType * It, const CharType * End) inline static constexpr private
Definition at line 226 of file AsciiSet.h.
References FAsciiSet(), End, and Members.
Referenced by HasOnly(), and Scan().
FindFirstOrEnd()
template<class CharType> constexpr const CharType * FAsciiSet::FindFirstOrEnd (const CharType * Str, FAsciiSet Set) inline static constexpr
Find first character of string inside set or end pointer.
Never returns null.
Definition at line 81 of file AsciiSet.h.
References FAsciiSet(), and NilMask.
Referenced by FindLastOrEnd(), HasAny(), and HasNone().
FindLast()
template<EInclude Include, typename CharType> constexpr const CharType * FAsciiSet::FindLast (FAsciiSet Set, const CharType * It, const CharType * End) inline static constexpr private
Definition at line 233 of file AsciiSet.h.
References FAsciiSet(), End, and Members.
Referenced by Scan().
FindLastOrEnd()
template<class CharType> constexpr const CharType * FAsciiSet::FindLastOrEnd (const CharType * Str, FAsciiSet Set) inline static constexpr
Find last character of string inside set or end pointer.
Never returns null.
Definition at line 90 of file AsciiSet.h.
References FAsciiSet(), FindFirstOrEnd(), and Last.
FindPrefixWith()
template<class StringType> constexpr StringType FAsciiSet::FindPrefixWith (const StringType & Str, FAsciiSet Set) inline static constexpr
Get initial substring with all characters in set.
Definition at line 139 of file AsciiSet.h.
References FAsciiSet(), and Scan().
FindPrefixWithout()
template<class StringType> constexpr StringType FAsciiSet::FindPrefixWithout (const StringType & Str, FAsciiSet Set) inline static constexpr
Get initial substring with no characters in set.
Definition at line 146 of file AsciiSet.h.
References FAsciiSet(), and Scan().
FindSuffixWith()
template<class StringType> constexpr StringType FAsciiSet::FindSuffixWith (const StringType & Str, FAsciiSet Set) inline static constexpr
Get trailing substring with all characters in set.
Definition at line 167 of file AsciiSet.h.
References FAsciiSet(), and Scan().
FindSuffixWithout()
template<class StringType> constexpr StringType FAsciiSet::FindSuffixWithout (const StringType & Str, FAsciiSet Set) inline static constexpr
Get trailing substring with no characters in set.
Definition at line 174 of file AsciiSet.h.
References FAsciiSet(), and Scan().
HasAny() [1/2]
template<typename CharType> constexpr bool FAsciiSet::HasAny (const CharType * Str, FAsciiSet Set) inline static constexpr
Test if string contains any character in set.
Definition at line 116 of file AsciiSet.h.
References FAsciiSet(), and FindFirstOrEnd().
HasAny() [2/2]
template<class StringType> constexpr bool FAsciiSet::HasAny (const StringType & Str, FAsciiSet Set) inline static constexpr
Test if string contains any character in set.
Definition at line 195 of file AsciiSet.h.
References FAsciiSet(), and HasNone().
HasNone() [1/2]
template<typename CharType> constexpr bool FAsciiSet::HasNone (const CharType * Str, FAsciiSet Set) inline static constexpr
Test if string contains no character in set.
Definition at line 123 of file AsciiSet.h.
References FAsciiSet(), and FindFirstOrEnd().
Referenced by HasAny().
HasNone() [2/2]
template<class StringType> constexpr bool FAsciiSet::HasNone (const StringType & Str, FAsciiSet Set) inline static constexpr
Test if string contains no character in set.
Definition at line 202 of file AsciiSet.h.
References FAsciiSet(), and Match.
HasOnly() [1/2]
template<typename CharType> constexpr bool FAsciiSet::HasOnly (const CharType * Str, FAsciiSet Set) inline static constexpr
Test if string contains any character outside of set.
Definition at line 130 of file AsciiSet.h.
References FAsciiSet(), and Skip.
HasOnly() [2/2]
template<class StringType> constexpr bool FAsciiSet::HasOnly (const StringType & Str, FAsciiSet Set) inline static constexpr
Test if string contains any character outside of set.
Definition at line 214 of file AsciiSet.h.
References FAsciiSet(), End, FindFirst(), GetData(), and GetNum().
operator&()
FORCEINLINE FAsciiSet FAsciiSet::operator& (FAsciiSet OtherSet) const inline constexpr
Create new set containing only the characters that exist in both this and another specified set.
Definition at line 66 of file AsciiSet.h.
References FAsciiSet(), FORCEINLINE, HiMask, and LoMask.
operator+()
FORCEINLINE FAsciiSet FAsciiSet::operator+ (char Char) const inline constexpr
Create new set with specified character in it.
Definition at line 52 of file AsciiSet.h.
References FAsciiSet(), FORCEINLINE, HiMask, LoMask, SetImpl(), and TChar< CharType >::ToUnsigned().
operator|()
FORCEINLINE FAsciiSet FAsciiSet::operator| (FAsciiSet OtherSet) const inline constexpr
Create new set containing the combination of this set and another.
Definition at line 60 of file AsciiSet.h.
References FAsciiSet(), FORCEINLINE, HiMask, and LoMask.
operator~()
FORCEINLINE FAsciiSet FAsciiSet::operator~ () const inline constexpr
Create new set containing inverse set of characters - likely including null-terminator.
Definition at line 72 of file AsciiSet.h.
References FAsciiSet(), FORCEINLINE, HiMask, and LoMask.
Scan()
template<EDir Dir, EInclude Include, EKeep Keep, class StringType> constexpr StringType FAsciiSet::Scan (const StringType & Str, FAsciiSet Set) inline static constexpr private
Definition at line 240 of file AsciiSet.h.
References FAsciiSet(), End, FindFirst(), FindLast(), Forward, GetData(), GetNum(), Head, and Keep.
Referenced by FindPrefixWith(), FindPrefixWithout(), FindSuffixWith(), FindSuffixWithout(), TrimPrefixWith(), TrimPrefixWithout(), TrimSuffixWith(), and TrimSuffixWithout().
SetImpl()
constexpr FORCEINLINE void FAsciiSet::SetImpl (InitData & Bitset, uint32 Char) inline static constexpr private
Definition at line 255 of file AsciiSet.h.
References FORCEINLINE, FAsciiSet::InitData::Hi, and FAsciiSet::InitData::Lo.
Referenced by operator+(), and StringToBitset().
Skip()
template<typename CharType> constexpr const CharType * FAsciiSet::Skip (const CharType * Str, FAsciiSet Set) inline static constexpr
Find first character of string outside of set.
Never returns null.
Definition at line 104 of file AsciiSet.h.
References FAsciiSet().
StringToBitset()
template<typename CharType, int N> constexpr InitData FAsciiSet::StringToBitset (const CharType(&) Chars[N]) inline static constexpr private
Definition at line 275 of file AsciiSet.h.
References SetImpl(), and TChar< CharType >::ToUnsigned().
Referenced by FAsciiSet().
Test()
template<typename CharType> FORCEINLINE uint64 FAsciiSet::Test (CharType Char) const inline constexpr
Returns non-zero if a character is part of the set.
Prefer Contains() to avoid VS2019 conversion warnings.
Definition at line 46 of file AsciiSet.h.
References FORCEINLINE, TestImpl(), and TChar< CharType >::ToUnsigned().
TestImpl()
FORCEINLINE uint64 FAsciiSet::TestImpl (uint32 Char) const inline constexpr private
Definition at line 265 of file AsciiSet.h.
References FORCEINLINE, HiMask, and LoMask.
Referenced by Contains(), and Test().
TrimPrefixWith()
template<class StringType> constexpr StringType FAsciiSet::TrimPrefixWith (const StringType & Str, FAsciiSet Set) inline static constexpr
Trim initial characters in set.
Definition at line 153 of file AsciiSet.h.
References FAsciiSet(), and Scan().
TrimPrefixWithout()
template<class StringType> constexpr StringType FAsciiSet::TrimPrefixWithout (const StringType & Str, FAsciiSet Set) inline static constexpr
Trim initial characters not in set.
Definition at line 160 of file AsciiSet.h.
References FAsciiSet(), and Scan().
TrimSuffixWith()
template<class StringType> constexpr StringType FAsciiSet::TrimSuffixWith (const StringType & Str, FAsciiSet Set) inline static constexpr
Trim trailing characters in set.
Definition at line 181 of file AsciiSet.h.
References FAsciiSet(), and Scan().
TrimSuffixWithout()
template<class StringType> constexpr StringType FAsciiSet::TrimSuffixWithout (const StringType & Str, FAsciiSet Set) inline static constexpr
Trim trailing characters not in set.
Definition at line 188 of file AsciiSet.h.
References FAsciiSet(), and Scan().
Field Documentation
HiMask
uint64 FAsciiSet::HiMask private
Definition at line 294 of file AsciiSet.h.
Referenced by FAsciiSet(), FAsciiSet(), operator&(), operator+(), operator|(), operator~(), and TestImpl().
LoMask
uint64 FAsciiSet::LoMask private
Definition at line 294 of file AsciiSet.h.
Referenced by FAsciiSet(), FAsciiSet(), operator&(), operator+(), operator|(), operator~(), and TestImpl().
NilMask
uint64 FAsciiSet::NilMask = uint64(1) << '\0' static constexpr private
Definition at line 253 of file AsciiSet.h.
Referenced by FindFirstOrEnd().
The documentation for this class was generated from the following file:
AsciiSet.h