Unreal Engine 5.6 C++ API: UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator > Class Template Reference
UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator > Class Template Reference final
#include "SharedBuffer.h"
Public Member Functions
TBufferOwnerTArray (TArray< T, Allocator > &&InArray)
Private Member Functions
virtual void FreeBuffer () final
Free the buffer and any associated resources.
Private Attributes
TArray< T, Allocator > Array
Additional Inherited Members
Public Types inherited from FBufferOwner
enum class EBufferOwnerFlags : uint8 { None = 0 , Owned = 1 << 0 , Immutable = 1 << 1 , Materialized = 1 << 2 }
Protected Member Functions inherited from FBufferOwner
FBufferOwner ()=default
FBufferOwner (const FBufferOwner &)=delete
FBufferOwner (void *InData, uint64 InSize)
virtual ~FBufferOwner ()
void * GetData ()
uint64 GetSize ()
uint32 GetTotalRefCount () const
bool IsImmutable () const
bool IsMaterialized () const
bool IsOwned () const
void Materialize ()
virtual void MaterializeBuffer ()
Materialize the buffer by making it ready to be accessed.
FBufferOwner & operator= (const FBufferOwner &)=delete
void SetBuffer (void *InData, uint64 InSize)
void SetIsImmutable ()
void SetIsMaterialized ()
void SetIsOwned ()
Detailed Description
template<typename T, typename Allocator>
class UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >
Definition at line 884 of file SharedBuffer.h.
Constructor & Destructor Documentation
TBufferOwnerTArray()
template<typename T, typename Allocator> UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >::TBufferOwnerTArray (TArray< T, Allocator > && InArray) inline explicit
Definition at line 887 of file SharedBuffer.h.
References Array, MoveTemp(), FBufferOwner::SetBuffer(), FBufferOwner::SetIsMaterialized(), and FBufferOwner::SetIsOwned().
Member Function Documentation
FreeBuffer()
template<typename T, typename Allocator> virtual void UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >::FreeBuffer () inline final private virtual
Free the buffer and any associated resources.
This is called when the last shared reference is released. The destructor will be called when the last weak reference is released. A buffer owner will always call this function before the calling the destructor, unless an exception was thrown by the constructor.
Implements FBufferOwner.
Definition at line 896 of file SharedBuffer.h.
References Array.
Field Documentation
Array
template<typename T, typename Allocator> TArray<T, Allocator> UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >::Array private
Definition at line 901 of file SharedBuffer.h.
Referenced by TBufferOwnerTArray(), and FreeBuffer().
The documentation for this class was generated from the following file:
SharedBuffer.h