Unreal Engine 5.6 C++ API: TDoubleLinkedList< ElementType >::TDoubleLinkedListNode Class Reference
TDoubleLinkedList< ElementType >::TDoubleLinkedListNode Class Reference
#include "List.h"
Public Member Functions
TDoubleLinkedListNode (const ElementType &InValue)
Constructor.
TDoubleLinkedListNode * GetNextNode ()
const TDoubleLinkedListNode * GetNextNode () const
TDoubleLinkedListNode * GetPrevNode ()
const TDoubleLinkedListNode * GetPrevNode () const
ElementType & GetValue ()
const ElementType & GetValue () const
Protected Attributes
TDoubleLinkedListNode * NextNode
TDoubleLinkedListNode * PrevNode
ElementType Value
Friends
class TDoubleLinkedList
Detailed Description
template<class ElementType>
class TDoubleLinkedList< ElementType >::TDoubleLinkedListNode
Definition at line 440 of file List.h.
Constructor & Destructor Documentation
TDoubleLinkedListNode()
template<class ElementType> TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::TDoubleLinkedListNode (const ElementType & InValue) inline nodiscard
Constructor.
Definition at line 446 of file List.h.
References NextNode, PrevNode, and Value.
Referenced by GetNextNode(), GetNextNode(), GetPrevNode(), and GetPrevNode().
Member Function Documentation
GetNextNode() [1/2]
template<class ElementType> TDoubleLinkedListNode * TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::GetNextNode () inline nodiscard
Definition at line 461 of file List.h.
References TDoubleLinkedListNode(), and NextNode.
GetNextNode() [2/2]
template<class ElementType> const TDoubleLinkedListNode * TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::GetNextNode () const inline nodiscard
Definition at line 466 of file List.h.
References TDoubleLinkedListNode(), and NextNode.
GetPrevNode() [1/2]
template<class ElementType> TDoubleLinkedListNode * TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::GetPrevNode () inline nodiscard
Definition at line 471 of file List.h.
References TDoubleLinkedListNode(), and PrevNode.
GetPrevNode() [2/2]
template<class ElementType> const TDoubleLinkedListNode * TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::GetPrevNode () const inline nodiscard
Definition at line 476 of file List.h.
References TDoubleLinkedListNode(), and PrevNode.
GetValue() [1/2]
template<class ElementType> ElementType & TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::GetValue () inline nodiscard
Definition at line 456 of file List.h.
References Value.
GetValue() [2/2]
template<class ElementType> const ElementType & TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::GetValue () const inline nodiscard
Definition at line 451 of file List.h.
References Value.
Friends And Related Symbol Documentation
TDoubleLinkedList
template<class ElementType> friend class TDoubleLinkedList friend
Definition at line 443 of file List.h.
References TDoubleLinkedList.
Referenced by TDoubleLinkedList.
Field Documentation
NextNode
template<class ElementType> TDoubleLinkedListNode* TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::NextNode protected
Definition at line 483 of file List.h.
Referenced by TDoubleLinkedListNode(), GetNextNode(), GetNextNode(), TDoubleLinkedListNode< FSegmentAndSID >::InsertNode(), and TDoubleLinkedListNode< FSegmentAndSID >::RemoveNode().
PrevNode
template<class ElementType> TDoubleLinkedListNode* TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::PrevNode protected
Definition at line 484 of file List.h.
Referenced by TDoubleLinkedListNode(), GetPrevNode(), GetPrevNode(), TDoubleLinkedListNode< FSegmentAndSID >::InsertNode(), and TDoubleLinkedListNode< FSegmentAndSID >::RemoveNode().
Value
template<class ElementType> ElementType TDoubleLinkedList< ElementType >::TDoubleLinkedListNode::Value protected
Definition at line 482 of file List.h.
Referenced by TDoubleLinkedListNode(), GetValue(), and GetValue().
The documentation for this class was generated from the following file:
List.h