Unreal Engine 5.6 C++ API: FWorldPartitionStreamingContext Struct Reference
FWorldPartitionStreamingContext Struct Reference
#include "WorldPartitionRuntimeHash.h"
Public Member Functions
FWorldPartitionStreamingContext ()
bool IsValid () const
Static Public Member Functions
static FWorldPartitionStreamingContext Create (const UWorld *InWorld)
Private Member Functions
FWorldPartitionStreamingContext (const UWorld *InWorld)
FWorldPartitionStreamingContext (EWorldPartitionDataLayersLogicOperator InDataLayersLogicOperator, const FWorldDataLayersEffectiveStates &InDataLayerEffectiveStates, int32 InUpdateStreamingStateEpoch)
int32 GetResolvingDataLayersRuntimeStateEpoch () const
int32 GetUpdateStreamingStateEpoch () const
EDataLayerRuntimeState ResolveDataLayerRuntimeState (const FDataLayerInstanceNames &InDataLayerNames) const
Private Attributes
bool bIsValid
const FWorldDataLayersEffectiveStates * DataLayerEffectiveStates
EWorldPartitionDataLayersLogicOperator DataLayersLogicOperator
int32 UpdateStreamingStateEpoch
Friends
class UWorldPartitionRuntimeCell
class UWorldPartitionRuntimeCellData
class UWorldPartitionStreamingPolicy
Detailed Description
Definition at line 159 of file WorldPartitionRuntimeHash.h.
Constructor & Destructor Documentation
FWorldPartitionStreamingContext() [1/3]
FWorldPartitionStreamingContext::FWorldPartitionStreamingContext ()
Referenced by Create().
FWorldPartitionStreamingContext() [2/3]
FWorldPartitionStreamingContext::FWorldPartitionStreamingContext (const UWorld * InWorld) private
FWorldPartitionStreamingContext() [3/3]
FWorldPartitionStreamingContext::FWorldPartitionStreamingContext (EWorldPartitionDataLayersLogicOperator InDataLayersLogicOperator, const FWorldDataLayersEffectiveStates & InDataLayerEffectiveStates, int32 InUpdateStreamingStateEpoch) private
Member Function Documentation
Create()
FWorldPartitionStreamingContext FWorldPartitionStreamingContext::Create (const UWorld * InWorld) static
References FWorldPartitionStreamingContext().
GetResolvingDataLayersRuntimeStateEpoch()
int32 FWorldPartitionStreamingContext::GetResolvingDataLayersRuntimeStateEpoch () const inline private
Definition at line 170 of file WorldPartitionRuntimeHash.h.
References check, DataLayerEffectiveStates, and IsValid().
GetUpdateStreamingStateEpoch()
int32 FWorldPartitionStreamingContext::GetUpdateStreamingStateEpoch () const inline private
Definition at line 171 of file WorldPartitionRuntimeHash.h.
References check, IsValid(), and UpdateStreamingStateEpoch.
IsValid()
bool FWorldPartitionStreamingContext::IsValid () const inline
Definition at line 164 of file WorldPartitionRuntimeHash.h.
References bIsValid.
Referenced by GetResolvingDataLayersRuntimeStateEpoch(), and GetUpdateStreamingStateEpoch().
ResolveDataLayerRuntimeState()
EDataLayerRuntimeState FWorldPartitionStreamingContext::ResolveDataLayerRuntimeState (const FDataLayerInstanceNames & InDataLayerNames) const private
Friends And Related Symbol Documentation
UWorldPartitionRuntimeCell
friend class UWorldPartitionRuntimeCell friend
Definition at line 180 of file WorldPartitionRuntimeHash.h.
References UWorldPartitionRuntimeCell.
Referenced by UWorldPartitionRuntimeCell.
UWorldPartitionRuntimeCellData
friend class UWorldPartitionRuntimeCellData friend
Definition at line 181 of file WorldPartitionRuntimeHash.h.
References UWorldPartitionRuntimeCellData.
Referenced by UWorldPartitionRuntimeCellData.
UWorldPartitionStreamingPolicy
friend class UWorldPartitionStreamingPolicy friend
Definition at line 179 of file WorldPartitionRuntimeHash.h.
References UWorldPartitionStreamingPolicy.
Referenced by UWorldPartitionStreamingPolicy.
Field Documentation
bIsValid
bool FWorldPartitionStreamingContext::bIsValid private
Definition at line 174 of file WorldPartitionRuntimeHash.h.
Referenced by IsValid().
DataLayerEffectiveStates
const FWorldDataLayersEffectiveStates* FWorldPartitionStreamingContext::DataLayerEffectiveStates private
Definition at line 176 of file WorldPartitionRuntimeHash.h.
Referenced by GetResolvingDataLayersRuntimeStateEpoch().
DataLayersLogicOperator
EWorldPartitionDataLayersLogicOperator FWorldPartitionStreamingContext::DataLayersLogicOperator private
Definition at line 175 of file WorldPartitionRuntimeHash.h.
UpdateStreamingStateEpoch
int32 FWorldPartitionStreamingContext::UpdateStreamingStateEpoch private
Definition at line 177 of file WorldPartitionRuntimeHash.h.
Referenced by GetUpdateStreamingStateEpoch().
The documentation for this struct was generated from the following file:
WorldPartitionRuntimeHash.h