Unreal Engine 5.6 C++ API: FAttributesSetEntry Class Reference
FAttributesSetEntry Class Reference
This is a wrapper for an allocated attributes array.
#include "MeshAttributeArray.h"
Public Member Functions
FAttributesSetEntry ()=default
Default constructor.
FAttributesSetEntry (const FAttributesSetEntry &Other)
Polymorphic copy: a new copy of Other is created.
template<typename AttributeType>
FAttributesSetEntry (const int32 NumberOfChannels, const AttributeType &Default, const EMeshAttributeFlags Flags, const int32 NumElements, const int32 Extent)
Construct a valid FAttributesSetEntry of the concrete type specified.
FAttributesSetEntry (FAttributesSetEntry &&)=default
Default move constructor.
~FAttributesSetEntry ()=default
Default destructor.
void CreateArrayOfType (const uint32 Type, const uint32 Extent)
Given a type at runtime, allocate an attribute array of that type, owned by Ptr.
FORCEINLINE FMeshAttributeArraySetBase * Get ()
FORCEINLINE const FMeshAttributeArraySetBase * Get () const
Transparent access through the TUniquePtr.
FORCEINLINE operator bool () const
Object can be coerced to bool to indicate if it is valid.
FORCEINLINE bool operator! () const
FORCEINLINE FMeshAttributeArraySetBase & operator* ()
FORCEINLINE const FMeshAttributeArraySetBase & operator* () const
FORCEINLINE FMeshAttributeArraySetBase * operator-> ()
FORCEINLINE const FMeshAttributeArraySetBase * operator-> () const
FAttributesSetEntry & operator= (const FAttributesSetEntry &Other)
Polymorphic assignment.
FAttributesSetEntry & operator= (FAttributesSetEntry &&)=default
Default move assignment.
Private Attributes
TUniquePtr< FMeshAttributeArraySetBase > Ptr
Friends
FArchive & operator<< (FArchive &Ar, FAttributesSetEntry &Entry)
Serialization.
Detailed Description
This is a wrapper for an allocated attributes array.
It holds a TUniquePtr pointing to the actual attributes array, and performs polymorphic copy and assignment, as per the actual array type.
Definition at line 1481 of file MeshAttributeArray.h.
Constructor & Destructor Documentation
FAttributesSetEntry() [1/4]
FAttributesSetEntry::FAttributesSetEntry () default
Default constructor.
This breaks the invariant that Ptr be always valid, but is necessary so that it can be the value type of a TMap.
Referenced by FAttributesSetEntry(), FAttributesSetEntry(), operator<<, operator=(), and operator=().
FAttributesSetEntry() [2/4]
template<typename AttributeType> FAttributesSetEntry::FAttributesSetEntry (const int32 NumberOfChannels, const AttributeType & Default, const EMeshAttributeFlags Flags, const int32 NumElements, const int32 Extent) inline
Construct a valid FAttributesSetEntry of the concrete type specified.
Definition at line 1494 of file MeshAttributeArray.h.
References Default, Flags, MakeUnique(), and Ptr.
~FAttributesSetEntry()
FAttributesSetEntry::~FAttributesSetEntry () default
Default destructor.
FAttributesSetEntry() [3/4]
FAttributesSetEntry::FAttributesSetEntry (const FAttributesSetEntry & Other) inline
Polymorphic copy: a new copy of Other is created.
Definition at line 1510 of file MeshAttributeArray.h.
References FAttributesSetEntry(), Other, and Ptr.
FAttributesSetEntry() [4/4]
FAttributesSetEntry::FAttributesSetEntry (FAttributesSetEntry &&) default
Default move constructor.
References FAttributesSetEntry().
Member Function Documentation
CreateArrayOfType()
void FAttributesSetEntry::CreateArrayOfType (const uint32 Type, const uint32 Extent) inline
Given a type at runtime, allocate an attribute array of that type, owned by Ptr.
Definition at line 2402 of file MeshAttributeArray.h.
References CreateTypeImpl::MakeJumpTable(), and Ptr.
Get() [1/2]
FORCEINLINE FMeshAttributeArraySetBase * FAttributesSetEntry::Get () inline
Definition at line 1532 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
Get() [2/2]
FORCEINLINE const FMeshAttributeArraySetBase * FAttributesSetEntry::Get () const inline
Transparent access through the TUniquePtr.
Definition at line 1529 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
Referenced by FAttributesSetBase::RegisterAttributeInternal().
operator bool()
FORCEINLINE FAttributesSetEntry::operator bool () const inline explicit
Object can be coerced to bool to indicate if it is valid.
Definition at line 1537 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
operator!()
FORCEINLINE bool FAttributesSetEntry::operator! () const inline
Definition at line 1538 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
operator*() [1/2]
FORCEINLINE FMeshAttributeArraySetBase & FAttributesSetEntry::operator* () inline
Definition at line 1534 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
operator*() [2/2]
FORCEINLINE const FMeshAttributeArraySetBase & FAttributesSetEntry::operator* () const inline
Definition at line 1531 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
operator->() [1/2]
FORCEINLINE FMeshAttributeArraySetBase * FAttributesSetEntry::operator-> () inline
Definition at line 1533 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
operator->() [2/2]
FORCEINLINE const FMeshAttributeArraySetBase * FAttributesSetEntry::operator-> () const inline
Definition at line 1530 of file MeshAttributeArray.h.
References FORCEINLINE, and Ptr.
operator=() [1/2]
FAttributesSetEntry & FAttributesSetEntry::operator= (const FAttributesSetEntry & Other) inline
Polymorphic assignment.
Definition at line 1518 of file MeshAttributeArray.h.
References FAttributesSetEntry(), Other, and Swap.
operator=() [2/2]
FAttributesSetEntry & FAttributesSetEntry::operator= (FAttributesSetEntry &&) default
Default move assignment.
References FAttributesSetEntry().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FAttributesSetEntry & Entry) friend
Serialization.
References FAttributesSetEntry(), and Ar.
Field Documentation
Ptr
TUniquePtr<FMeshAttributeArraySetBase> FAttributesSetEntry::Ptr private
Definition at line 1547 of file MeshAttributeArray.h.
Referenced by FAttributesSetEntry(), FAttributesSetEntry(), CreateArrayOfType(), Get(), Get(), operator bool(), operator!(), operator*(), operator*(), operator->(), and operator->().
The documentation for this class was generated from the following file:
MeshAttributeArray.h