Unreal Engine 5.6 C++ API: UE::AnimNext::FEvaluationVM Struct Reference
UE::AnimNext::FEvaluationVM Struct Reference
#include "EvaluationVM.h"
Public Member Functions
FEvaluationVM ()=default
ANIMNEXTANIMGRAPH_API FEvaluationVM (EEvaluationFlags InEvaluationFlags, const UE::AnimNext::FReferencePose &InReferencePose, int32 InCurrentLOD)
FEvaluationVM (FEvaluationVM &&)=default
int32 GetCurrentLOD () const
EEvaluationFlags GetFlags () const
ANIMNEXTANIMGRAPH_API bool IsValid () const
ANIMNEXTANIMGRAPH_API FKeyframeState MakeReferenceKeyframe (bool bAdditiveKeyframe) const
ANIMNEXTANIMGRAPH_API FKeyframeState MakeUninitializedKeyframe (bool bAdditiveKeyframe) const
FEvaluationVM & operator= (FEvaluationVM &&)=default
template<typename ValueType>
const ValueType * PeekValue (const FEvaluationVMStackName &StackName, uint32 Offset) const
template<typename ValueType>
ValueType * PeekValueMutable (const FEvaluationVMStackName &StackName, uint32 Offset)
template<typename ValueType>
bool PopValue (const FEvaluationVMStackName &StackName, ValueType &OutValue)
template<typename ValueType>
void PushValue (const FEvaluationVMStackName &StackName, ValueType &&Value)
ANIMNEXTANIMGRAPH_API void Shrink ()
Private Member Functions
FEvaluationVM (const FEvaluationVM &)=delete
ANIMNEXTANIMGRAPH_API FEvaluationVMStack * FindStack (const FEvaluationVMStackName &StackName, uint32 TypeID)
ANIMNEXTANIMGRAPH_API const FEvaluationVMStack * FindStack (const FEvaluationVMStackName &StackName, uint32 TypeID) const
ANIMNEXTANIMGRAPH_API FEvaluationVMStack & GetOrCreateStack (const FEvaluationVMStackName &StackName, uint32 TypeID)
FEvaluationVM & operator= (const FEvaluationVM &)=delete
ANIMNEXTANIMGRAPH_API const void * PeekValueImpl (const FEvaluationVMStackName &StackName, uint32 TypeID, uint32 Offset) const
Private Attributes
int32 CurrentLOD = 0
UE::Anim::FCurveFilter CurveFilter
EEvaluationFlags EvaluationFlags = EEvaluationFlags::All
TMap< FName, FEvaluationVMStack > InternalStacks
const UE::AnimNext::FReferencePose * ReferencePose = nullptr
Detailed Description
Definition at line 147 of file EvaluationVM.h.
Constructor & Destructor Documentation
FEvaluationVM() [1/4]
UE::AnimNext::FEvaluationVM::FEvaluationVM () default
Referenced by FEvaluationVM(), FEvaluationVM(), operator=(), and operator=().
FEvaluationVM() [2/4]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FEvaluationVM::FEvaluationVM (EEvaluationFlags InEvaluationFlags, const UE::AnimNext::FReferencePose & InReferencePose, int32 InCurrentLOD)
References UE_API.
FEvaluationVM() [3/4]
UE::AnimNext::FEvaluationVM::FEvaluationVM (FEvaluationVM &&) default
References FEvaluationVM().
FEvaluationVM() [4/4]
UE::AnimNext::FEvaluationVM::FEvaluationVM (const FEvaluationVM &) private delete
References FEvaluationVM().
Member Function Documentation
FindStack() [1/2]
ANIMNEXTANIMGRAPH_API FEvaluationVMStack * UE::AnimNext::FEvaluationVM::FindStack (const FEvaluationVMStackName & StackName, uint32 TypeID) private
References UE_API.
Referenced by PopValue().
FindStack() [2/2]
ANIMNEXTANIMGRAPH_API const FEvaluationVMStack * UE::AnimNext::FEvaluationVM::FindStack (const FEvaluationVMStackName & StackName, uint32 TypeID) const private
References UE_API.
GetCurrentLOD()
int32 UE::AnimNext::FEvaluationVM::GetCurrentLOD () const inline
Definition at line 192 of file EvaluationVM.h.
References CurrentLOD.
GetFlags()
EEvaluationFlags UE::AnimNext::FEvaluationVM::GetFlags () const inline nodiscard
Definition at line 160 of file EvaluationVM.h.
References EvaluationFlags.
GetOrCreateStack()
ANIMNEXTANIMGRAPH_API FEvaluationVMStack & UE::AnimNext::FEvaluationVM::GetOrCreateStack (const FEvaluationVMStackName & StackName, uint32 TypeID) private
References UE_API.
Referenced by PushValue().
IsValid()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FEvaluationVM::IsValid () const nodiscard
References UE_API.
MakeReferenceKeyframe()
ANIMNEXTANIMGRAPH_API FKeyframeState UE::AnimNext::FEvaluationVM::MakeReferenceKeyframe (bool bAdditiveKeyframe) const nodiscard
References UE_API.
MakeUninitializedKeyframe()
ANIMNEXTANIMGRAPH_API FKeyframeState UE::AnimNext::FEvaluationVM::MakeUninitializedKeyframe (bool bAdditiveKeyframe) const nodiscard
References UE_API.
operator=() [1/2]
FEvaluationVM & UE::AnimNext::FEvaluationVM::operator= (const FEvaluationVM &) private delete
References FEvaluationVM().
operator=() [2/2]
FEvaluationVM & UE::AnimNext::FEvaluationVM::operator= (FEvaluationVM &&) default
References FEvaluationVM().
PeekValue()
template<typename ValueType> const ValueType * UE::AnimNext::FEvaluationVM::PeekValue (const FEvaluationVMStackName & StackName, uint32 Offset) const inline nodiscard
Definition at line 291 of file EvaluationVM.h.
References UE::AnimNext::GetTypeID(), and PeekValueImpl().
PeekValueImpl()
ANIMNEXTANIMGRAPH_API const void * UE::AnimNext::FEvaluationVM::PeekValueImpl (const FEvaluationVMStackName & StackName, uint32 TypeID, uint32 Offset) const private
References UE_API.
Referenced by PeekValue(), and PeekValueMutable().
PeekValueMutable()
template<typename ValueType> ValueType * UE::AnimNext::FEvaluationVM::PeekValueMutable (const FEvaluationVMStackName & StackName, uint32 Offset) inline nodiscard
Definition at line 297 of file EvaluationVM.h.
References UE::AnimNext::GetTypeID(), and PeekValueImpl().
PopValue()
template<typename ValueType> bool UE::AnimNext::FEvaluationVM::PopValue (const FEvaluationVMStackName & StackName, ValueType & OutValue) inline nodiscard
Definition at line 263 of file EvaluationVM.h.
References FindStack(), FMemory::Free(), UE::AnimNext::GetTypeID(), UE::AnimNext::FEvaluationVMStackEntry::GetValuePtr(), MoveTemp(), UE::AnimNext::FEvaluationVMStackEntry::Prev, and UE::AnimNext::FEvaluationVMStack::Top.
PushValue()
template<typename ValueType> void UE::AnimNext::FEvaluationVM::PushValue (const FEvaluationVMStackName & StackName, ValueType && Value) inline
Definition at line 233 of file EvaluationVM.h.
References ensureMsgf, UE::AnimNext::FEvaluationVMStackEntry::Flags, GetOrCreateStack(), UE::AnimNext::GetTypeDestructor(), UE::AnimNext::GetTypeID(), UE::AnimNext::FEvaluationVMStackEntry::GetValuePtr(), MoveTemp(), UE::AnimNext::FEvaluationVMStackEntry::Prev, UE::AnimNext::FEvaluationVMStackEntry::Size, TEXT, UE::AnimNext::FEvaluationVMStack::Top, UE::AnimNext::FEvaluationVMStack::TypeDestructor, UE::AnimNext::FEvaluationVMStack::TypeID, and Value.
Shrink()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FEvaluationVM::Shrink ()
References UE_API.
Field Documentation
CurrentLOD
int32 UE::AnimNext::FEvaluationVM::CurrentLOD = 0 private
Definition at line 217 of file EvaluationVM.h.
Referenced by GetCurrentLOD().
CurveFilter
UE::Anim::FCurveFilter UE::AnimNext::FEvaluationVM::CurveFilter private
Definition at line 223 of file EvaluationVM.h.
EvaluationFlags
EEvaluationFlags UE::AnimNext::FEvaluationVM::EvaluationFlags = EEvaluationFlags::All private
Definition at line 220 of file EvaluationVM.h.
Referenced by GetFlags().
InternalStacks
TMap<FName, FEvaluationVMStack> UE::AnimNext::FEvaluationVM::InternalStacks private
Definition at line 211 of file EvaluationVM.h.
ReferencePose
const UE::AnimNext::FReferencePose* UE::AnimNext::FEvaluationVM::ReferencePose = nullptr private
Definition at line 214 of file EvaluationVM.h.
The documentation for this struct was generated from the following file:
EvaluationVM.h