Unreal Engine 5.6 C++ Documentation: UCheatManager Class Reference
UCheatManager Class Reference
Cheat Manager is a central blueprint to implement test and debug code and actions that are not to ship with the game.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CheatManager.h>
Public Member Functions
void AddCheatManagerExtension (UCheatManagerExtension *CheatObject)
Registers a cheat manager extension with this cheat manager.
void RemoveCheatManagerExtension (UCheatManagerExtension *CheatObject)
Removes a cheat manager extension from this cheat manager.
UCheatManagerExtension * FindCheatManagerExtension (const UClass *InClass) const
Finds a previously registered cheat manager extension of the specified class.
template<typename T>
T * FindCheatManagerExtension () const
Finds a previously registered cheat manager extension of the specified class.
UCheatManagerExtension * FindCheatManagerExtensionInterface (const UClass *InClass) const
Finds a previously registered cheat manager extension that implements the specified interface.
template<class T = UInterface>
T * FindCheatManagerExtensionInterface () const
Finds a previously registered cheat manager extension that implements the specified interface.
virtual bool DoGameSpecificBugItLog (FOutputDevice &OutputFile)
Do game specific bugIt.
APlayerController * GetPlayerController () const
Static Public Member Functions
static FDelegateHandle RegisterForOnCheatManagerCreated (FOnCheatManagerCreated::FDelegate &&Delegate)
Register a delegate to call whenever a cheat manager is spawned; it will also be called immediately for cheat managers that already exist at this point.
static void UnregisterFromOnCheatManagerCreated (FDelegateHandle DelegateHandle)
Unregister a delegate previously registered with CallOrRegister_OnCheatManagerCreated.
Protected Member Functions
virtual void EnableDebugCamera ()
Switch controller to debug camera without locking gameplay and with locking local player controller input.
virtual void DisableDebugCamera ()
Switch controller from debug camera back to normal controller.
virtual AActor * GetTarget (APlayerController *PlayerController, struct FHitResult &OutHit)
Retrieve the given PlayerContoller's current "target" AActor.
Protected Attributes
TArray< TObjectPtr< UCheatManagerExtension > > CheatManagerExtensions
List of registered cheat manager extensions.
Static Protected Attributes
static FOnCheatManagerCreated OnCheatManagerCreatedDelegate
Delegate called when the asset manager singleton is created.
Detailed Description
Cheat Manager is a central blueprint to implement test and debug code and actions that are not to ship with the game.
As the Cheat Manager is not instanced in shipping builds, it is for debugging purposes only
Definition at line 97 of file CheatManager.h.
Member Function Documentation
AddCheatManagerExtension()
void UCheatManager::AddCheatManagerExtension (UCheatManagerExtension * CheatObject)
Registers a cheat manager extension with this cheat manager.
DisableDebugCamera()
virtual void UCheatManager::DisableDebugCamera () protected virtual
Switch controller from debug camera back to normal controller.
References DisableDebugCamera().
DoGameSpecificBugItLog()
virtual bool UCheatManager::DoGameSpecificBugItLog (FOutputDevice & OutputFile) virtual
Do game specific bugIt.
EnableDebugCamera()
virtual void UCheatManager::EnableDebugCamera () protected virtual
Switch controller to debug camera without locking gameplay and with locking local player controller input.
References EnableDebugCamera().
FindCheatManagerExtension() [1/2]
template<typename T> T * UCheatManager::FindCheatManagerExtension () const inline
Finds a previously registered cheat manager extension of the specified class.
Definition at line 445 of file CheatManager.h.
References FindCheatManagerExtension().
FindCheatManagerExtension() [2/2]
UCheatManagerExtension * UCheatManager::FindCheatManagerExtension (const UClass * InClass) const
Finds a previously registered cheat manager extension of the specified class.
FindCheatManagerExtensionInterface() [1/2]
template<class T = UInterface> T * UCheatManager::FindCheatManagerExtensionInterface () const inline
Finds a previously registered cheat manager extension that implements the specified interface.
Definition at line 455 of file CheatManager.h.
References FindCheatManagerExtensionInterface().
FindCheatManagerExtensionInterface() [2/2]
UCheatManagerExtension * UCheatManager::FindCheatManagerExtensionInterface (const UClass * InClass) const
Finds a previously registered cheat manager extension that implements the specified interface.
GetPlayerController()
APlayerController * UCheatManager::GetPlayerController () const
References GetPlayerController().
GetTarget()
virtual AActor * UCheatManager::GetTarget (APlayerController * PlayerController, struct FHitResult & OutHit) protected virtual
Retrieve the given PlayerContoller's current "target" AActor.
References GetTarget().
RegisterForOnCheatManagerCreated()
FDelegateHandle UCheatManager::RegisterForOnCheatManagerCreated (FOnCheatManagerCreated::FDelegate && Delegate) static
Register a delegate to call whenever a cheat manager is spawned; it will also be called immediately for cheat managers that already exist at this point.
RemoveCheatManagerExtension()
void UCheatManager::RemoveCheatManagerExtension (UCheatManagerExtension * CheatObject)
Removes a cheat manager extension from this cheat manager.
UnregisterFromOnCheatManagerCreated()
void UCheatManager::UnregisterFromOnCheatManagerCreated (FDelegateHandle DelegateHandle) static
Unregister a delegate previously registered with CallOrRegister_OnCheatManagerCreated.
Member Data Documentation
CheatManagerExtensions
TArray<TObjectPtr<UCheatManagerExtension> > UCheatManager::CheatManagerExtensions protected
List of registered cheat manager extensions.
Definition at line 472 of file CheatManager.h.
OnCheatManagerCreatedDelegate
FOnCheatManagerCreated UCheatManager::OnCheatManagerCreatedDelegate static protected
Delegate called when the asset manager singleton is created.
Definition at line 475 of file CheatManager.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CheatManager.h