Unreal Engine 5.6 C++ API: FParticlePerfStatsContext Struct Reference
FParticlePerfStatsContext Struct Reference
#include "ParticlePerfStats.h"
Public Member Functions
FParticlePerfStatsContext ()
FORCEINLINE FParticlePerfStatsContext (const UFXSystemComponent *InComponent)
FORCEINLINE FParticlePerfStatsContext (const UWorld *InWorld, const UFXSystemAsset *InSystem)
FORCEINLINE FParticlePerfStatsContext (const UWorld *InWorld, const UFXSystemAsset *InSystem, const UFXSystemComponent *InComponent)
FORCEINLINE FParticlePerfStatsContext (FParticlePerfStats *InComponentStats)
FORCEINLINE FParticlePerfStatsContext (FParticlePerfStats *InWorldStats, FParticlePerfStats *InSystemStats)
FORCEINLINE FParticlePerfStatsContext (FParticlePerfStats *InWorldStats, FParticlePerfStats *InSystemStats, FParticlePerfStats *InComponentStats)
FORCEINLINE FParticlePerfStats * GetComponentStats ()
FORCEINLINE FParticlePerfStats * GetSystemStats ()
FORCEINLINE FParticlePerfStats * GetWorldStats ()
FORCEINLINE bool IsValid ()
FORCEINLINE void SetComponentStats (FParticlePerfStats *Stats)
FORCEINLINE void SetSystemStats (FParticlePerfStats *Stats)
FORCEINLINE void SetWorldStats (FParticlePerfStats *Stats)
Data Fields
FParticlePerfStats * ComponentStats = nullptr
FParticlePerfStats * SystemStats = nullptr
FParticlePerfStats * WorldStats = nullptr
Detailed Description
Definition at line 301 of file ParticlePerfStats.h.
Constructor & Destructor Documentation
FParticlePerfStatsContext() [1/7]
FParticlePerfStatsContext::FParticlePerfStatsContext () inline
Definition at line 303 of file ParticlePerfStats.h.
References ComponentStats, SystemStats, WITH_PER_COMPONENT_PARTICLE_PERF_STATS, WITH_PER_SYSTEM_PARTICLE_PERF_STATS, and WorldStats.
FParticlePerfStatsContext() [2/7]
FORCEINLINE FParticlePerfStatsContext::FParticlePerfStatsContext (FParticlePerfStats * InWorldStats, FParticlePerfStats * InSystemStats, FParticlePerfStats * InComponentStats) inline
Definition at line 313 of file ParticlePerfStats.h.
References FORCEINLINE, SetComponentStats(), SetSystemStats(), and SetWorldStats().
FParticlePerfStatsContext() [3/7]
FORCEINLINE FParticlePerfStatsContext::FParticlePerfStatsContext (FParticlePerfStats * InWorldStats, FParticlePerfStats * InSystemStats) inline
Definition at line 320 of file ParticlePerfStats.h.
References FORCEINLINE, SetSystemStats(), and SetWorldStats().
FParticlePerfStatsContext() [4/7]
FORCEINLINE FParticlePerfStatsContext::FParticlePerfStatsContext (FParticlePerfStats * InComponentStats) inline
Definition at line 326 of file ParticlePerfStats.h.
References FORCEINLINE, and SetComponentStats().
FParticlePerfStatsContext() [5/7]
FORCEINLINE FParticlePerfStatsContext::FParticlePerfStatsContext (const UWorld * InWorld, const UFXSystemAsset * InSystem, const UFXSystemComponent * InComponent) inline
Definition at line 331 of file ParticlePerfStats.h.
References FORCEINLINE, FParticlePerfStats::GetStats(), SetComponentStats(), SetSystemStats(), and SetWorldStats().
FParticlePerfStatsContext() [6/7]
FORCEINLINE FParticlePerfStatsContext::FParticlePerfStatsContext (const UWorld * InWorld, const UFXSystemAsset * InSystem) inline
Definition at line 338 of file ParticlePerfStats.h.
References FORCEINLINE, FParticlePerfStats::GetStats(), SetSystemStats(), and SetWorldStats().
FParticlePerfStatsContext() [7/7]
FORCEINLINE FParticlePerfStatsContext::FParticlePerfStatsContext (const UFXSystemComponent * InComponent) inline
Definition at line 344 of file ParticlePerfStats.h.
References FORCEINLINE, FParticlePerfStats::GetStats(), and SetComponentStats().
Member Function Documentation
GetComponentStats()
FORCEINLINE FParticlePerfStats * FParticlePerfStatsContext::GetComponentStats () inline
Definition at line 369 of file ParticlePerfStats.h.
References ComponentStats, and FORCEINLINE.
Referenced by IsValid().
GetSystemStats()
FORCEINLINE FParticlePerfStats * FParticlePerfStatsContext::GetSystemStats () inline
Definition at line 360 of file ParticlePerfStats.h.
References FORCEINLINE, and SystemStats.
Referenced by IsValid().
GetWorldStats()
FORCEINLINE FParticlePerfStats * FParticlePerfStatsContext::GetWorldStats () inline
Definition at line 355 of file ParticlePerfStats.h.
References FORCEINLINE, and WorldStats.
Referenced by IsValid().
IsValid()
FORCEINLINE bool FParticlePerfStatsContext::IsValid () inline
Definition at line 349 of file ParticlePerfStats.h.
References FORCEINLINE, GetComponentStats(), GetSystemStats(), and GetWorldStats().
SetComponentStats()
FORCEINLINE void FParticlePerfStatsContext::SetComponentStats (FParticlePerfStats * Stats) inline
Definition at line 370 of file ParticlePerfStats.h.
References ComponentStats, and FORCEINLINE.
Referenced by FParticlePerfStatsContext(), FParticlePerfStatsContext(), FParticlePerfStatsContext(), and FParticlePerfStatsContext().
SetSystemStats()
FORCEINLINE void FParticlePerfStatsContext::SetSystemStats (FParticlePerfStats * Stats) inline
Definition at line 361 of file ParticlePerfStats.h.
References FORCEINLINE, and SystemStats.
Referenced by FParticlePerfStatsContext(), FParticlePerfStatsContext(), FParticlePerfStatsContext(), and FParticlePerfStatsContext().
SetWorldStats()
FORCEINLINE void FParticlePerfStatsContext::SetWorldStats (FParticlePerfStats * Stats) inline
Definition at line 356 of file ParticlePerfStats.h.
References FORCEINLINE, and WorldStats.
Referenced by FParticlePerfStatsContext(), FParticlePerfStatsContext(), FParticlePerfStatsContext(), and FParticlePerfStatsContext().
Field Documentation
ComponentStats
FParticlePerfStats* FParticlePerfStatsContext::ComponentStats = nullptr
Definition at line 368 of file ParticlePerfStats.h.
Referenced by FParticlePerfStatsContext(), GetComponentStats(), and SetComponentStats().
SystemStats
FParticlePerfStats* FParticlePerfStatsContext::SystemStats = nullptr
Definition at line 359 of file ParticlePerfStats.h.
Referenced by FParticlePerfStatsContext(), GetSystemStats(), and SetSystemStats().
WorldStats
FParticlePerfStats* FParticlePerfStatsContext::WorldStats = nullptr
Definition at line 354 of file ParticlePerfStats.h.
Referenced by FParticlePerfStatsContext(), GetWorldStats(), and SetWorldStats().
The documentation for this struct was generated from the following file:
ParticlePerfStats.h