Unreal Engine 5.6 C++ API: FLiveLinkProvider Struct Reference
FLiveLinkProvider Struct Reference
#include "LiveLinkProviderImpl.h"
Public Member Functions
FLiveLinkProvider (const FString &InProviderName)
FLiveLinkProvider (const FString &InProviderName, struct FMessageEndpointBuilder &&EndpointBuilder)
virtual ~FLiveLinkProvider () override
virtual void ClearSubject (const FName &SubjectName)
virtual bool HasConnection () const override
Is this provider currently connected to something.
virtual FDelegateHandle RegisterConnStatusChangedHandle (const FLiveLinkProviderConnectionStatusChanged::FDelegate &ConnStatusChanged) override
Function for managing connection status changed delegate.
virtual void RemoveSubject (const FName SubjectName) override
Inform UE that a subject won't be streamed anymore.
virtual void UnregisterConnStatusChangedHandle (FDelegateHandle Handle) override
Function for managing connection status changed delegate.
virtual void UpdateSubject (const FName &SubjectName, const TArray< FName > &BoneNames, const TArray< int32 > &BoneParents)
virtual void UpdateSubjectFrame (const FName &SubjectName, const TArray< FTransform > &BoneTransforms, const TArray< FLiveLinkCurveElement > &CurveData, const FLiveLinkMetaData &MetaData, double Time)
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS void UpdateSubjectFrame (const FName &SubjectName, const TArray< FTransform > &BoneTransforms, const TArray< FLiveLinkCurveElement > &CurveData, double Time)
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS bool UpdateSubjectFrameData (const FName SubjectName, FLiveLinkFrameDataStruct &&FrameData, const TMap< FName, FString > &ExtraAnnotations={}) override
Send the static data of a subject to UE.
virtual bool UpdateSubjectStaticData (const FName SubjectName, TSubclassOf< ULiveLinkRole > Role, FLiveLinkStaticDataStruct &&StaticData, const TMap< FName, FString > &ExtraAnnotations={}) override
Send, to UE, the static data of a subject.
Public Member Functions inherited from ILiveLinkProvider
virtual ~ILiveLinkProvider ()
Protected Member Functions
FLiveLinkProvider (const FString &InProviderName, bool bInCreateEndpoint)
void CloseConnection (FMessageAddress Address)
void CreateMessageEndpoint (struct FMessageEndpointBuilder &EndpointBuilder)
virtual TMap< FName, FString > GetAnnotations () const
void GetConnectedAddresses (TArray< FMessageAddress > &Addresses)
FMessageAddress GetEndpointAddress () const
TPair< UClass *, FLiveLinkStaticDataStruct * > GetLastSubjectStaticDataStruct (FName SubjectName)
const FString & GetMachineName () const
const FString & GetProviderName () const
void HandleConnectMessage (const FLiveLinkConnectMessage &Message, const TSharedRef< class IMessageContext, ESPMode::ThreadSafe > &Context)
virtual void OnConnectionsClosed (const TArray< FMessageAddress > &ClosedAddresses)
template<typename MessageType>
void Publish (MessageType *Message)
void SendClearSubjectToConnections (FName SubjectName)
template<typename MessageType>
void SendMessage (MessageType *Message, const FMessageAddress &Address, EMessageFlags Flags=EMessageFlags::None)
template<typename MessageType>
void SendMessage (MessageType *Message, const TArray< FMessageAddress > &Addresses, EMessageFlags Flags=EMessageFlags::None)
template<typename MessageType>
void SendMessage (MessageType *Message, EMessageFlags Flags=EMessageFlags::None)
virtual bool ShouldTransmitToSubject_AnyThread (FName SubjectName, FMessageAddress Address) const
template<typename MessageType>
void Subscribe ()
void ValidateConnections ()
Private Member Functions
void ClearTrackedSubject (const FName &SubjectName)
void GetFilteredAddresses (FName SubjectName, TArray< FMessageAddress > &Addresses)
FTrackedFrameData * GetLastSubjectFrameData (const FName &SubjectName)
FTrackedStaticData * GetLastSubjectStaticData (const FName &SubjectName)
FTrackedSubject & GetTrackedSubject (const FName &SubjectName)
void HandleHeartbeat (const FLiveLinkHeartbeatMessage &Message, const TSharedRef< class IMessageContext, ESPMode::ThreadSafe > &Context)
void HandlePingMessage (const FLiveLinkPingMessage &Message, const TSharedRef< class IMessageContext, ESPMode::ThreadSafe > &Context)
void SendSubject (FName SubjectName, const struct FTrackedSubject &Subject)
void SendSubjectFrame (FName SubjectName, const struct FTrackedSubject &Subject)
struct FLiveLinkSerializedFrameData SerializeAnimationData (struct FLiveLinkAnimationFrameData *AnimData)
void SetLastSubjectFrameData (FName SubjectName, FLiveLinkFrameDataStruct &&FrameData, TMap< FName, FString > &&SubjectAnnotations)
void SetLastSubjectStaticData (FName SubjectName, TSubclassOf< ULiveLinkRole > Role, FLiveLinkStaticDataStruct &&StaticData, TMap< FName, FString > &&Annotations)
Private Attributes
TArray< struct FTrackedAddress > ConnectedAddresses
FCriticalSection CriticalSection
TArray< struct FTrackedFrameData > FrameDatas
const FString MachineName
TSharedPtr< class FMessageEndpoint, ESPMode::ThreadSafe > MessageEndpoint
FLiveLinkProviderConnectionStatusChanged OnConnectionStatusChanged
const FString ProviderName
TArray< struct FTrackedStaticData > StaticDatas
TMap< FName, FTrackedSubject > Subjects
Additional Inherited Members
Static Public Member Functions inherited from ILiveLinkProvider
static LIVELINKMESSAGEBUSFRAMEWORK_API TSharedPtr< ILiveLinkProvider > CreateLiveLinkProvider (const FString &ProviderName)
template<typename T>
static TSharedPtr< ILiveLinkProvider > CreateLiveLinkProvider (const FString &ProviderName, struct FMessageEndpointBuilder &&EndpointBuilder)
Create a Live Link Provider based on a class derived from ILiveLinkProvider instead of using the default Live Link Provider.
Detailed Description
Definition at line 32 of file LiveLinkProviderImpl.h.
Constructor & Destructor Documentation
FLiveLinkProvider() [1/3]
FLiveLinkProvider::FLiveLinkProvider (const FString & InProviderName, bool bInCreateEndpoint) protected
FLiveLinkProvider() [2/3]
FLiveLinkProvider::FLiveLinkProvider (const FString & InProviderName)
FLiveLinkProvider() [3/3]
FLiveLinkProvider::FLiveLinkProvider (const FString & InProviderName, struct FMessageEndpointBuilder && EndpointBuilder)
~FLiveLinkProvider()
virtual FLiveLinkProvider::~FLiveLinkProvider () override virtual
Member Function Documentation
ClearSubject()
virtual void FLiveLinkProvider::ClearSubject (const FName & SubjectName) virtual
ClearTrackedSubject()
void FLiveLinkProvider::ClearTrackedSubject (const FName & SubjectName) private
CloseConnection()
void FLiveLinkProvider::CloseConnection (FMessageAddress Address) protected
CreateMessageEndpoint()
void FLiveLinkProvider::CreateMessageEndpoint (struct FMessageEndpointBuilder & EndpointBuilder) protected
GetAnnotations()
virtual TMap< FName, FString > FLiveLinkProvider::GetAnnotations () const inline protected virtual
Definition at line 177 of file LiveLinkProviderImpl.h.
References MoveTemp(), StaticEnum(), and FLiveLinkMessageAnnotation::TopologyModeAnnotation.
GetConnectedAddresses()
void FLiveLinkProvider::GetConnectedAddresses (TArray< FMessageAddress > & Addresses) protected
Referenced by SendMessage().
GetEndpointAddress()
FMessageAddress FLiveLinkProvider::GetEndpointAddress () const protected
GetFilteredAddresses()
void FLiveLinkProvider::GetFilteredAddresses (FName SubjectName, TArray< FMessageAddress > & Addresses) private
GetLastSubjectFrameData()
FTrackedFrameData * FLiveLinkProvider::GetLastSubjectFrameData (const FName & SubjectName) private
GetLastSubjectStaticData()
FTrackedStaticData * FLiveLinkProvider::GetLastSubjectStaticData (const FName & SubjectName) private
GetLastSubjectStaticDataStruct()
TPair< UClass *, FLiveLinkStaticDataStruct * > FLiveLinkProvider::GetLastSubjectStaticDataStruct (FName SubjectName) protected
GetMachineName()
const FString & FLiveLinkProvider::GetMachineName () const inline protected
Definition at line 168 of file LiveLinkProviderImpl.h.
References MachineName.
GetProviderName()
const FString & FLiveLinkProvider::GetProviderName () const inline protected
Definition at line 163 of file LiveLinkProviderImpl.h.
References ProviderName.
GetTrackedSubject()
FTrackedSubject & FLiveLinkProvider::GetTrackedSubject (const FName & SubjectName) private
HandleConnectMessage()
void FLiveLinkProvider::HandleConnectMessage (const FLiveLinkConnectMessage & Message, const TSharedRef< class IMessageContext, ESPMode::ThreadSafe > & Context) protected
HandleHeartbeat()
void FLiveLinkProvider::HandleHeartbeat (const FLiveLinkHeartbeatMessage & Message, const TSharedRef< class IMessageContext, ESPMode::ThreadSafe > & Context) private
HandlePingMessage()
void FLiveLinkProvider::HandlePingMessage (const FLiveLinkPingMessage & Message, const TSharedRef< class IMessageContext, ESPMode::ThreadSafe > & Context) private
HasConnection()
virtual bool FLiveLinkProvider::HasConnection () const override virtual
Is this provider currently connected to something.
Implements ILiveLinkProvider.
OnConnectionsClosed()
virtual void FLiveLinkProvider::OnConnectionsClosed (const TArray< FMessageAddress > & ClosedAddresses) inline protected virtual
Definition at line 174 of file LiveLinkProviderImpl.h.
Publish()
template<typename MessageType> void FLiveLinkProvider::Publish (MessageType * Message) inline protected
Definition at line 144 of file LiveLinkProviderImpl.h.
References MessageEndpoint.
RegisterConnStatusChangedHandle()
virtual FDelegateHandle FLiveLinkProvider::RegisterConnStatusChangedHandle (const FLiveLinkProviderConnectionStatusChanged::FDelegate & ConnStatusChanged) override virtual
Function for managing connection status changed delegate.
Implements ILiveLinkProvider.
RemoveSubject()
virtual void FLiveLinkProvider::RemoveSubject (const FName SubjectName) override virtual
Inform UE that a subject won't be streamed anymore.
Parameters
SubjectName The name of the subject.
Implements ILiveLinkProvider.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
SendClearSubjectToConnections()
void FLiveLinkProvider::SendClearSubjectToConnections (FName SubjectName) protected
SendMessage() [1/3]
template<typename MessageType> void FLiveLinkProvider::SendMessage (MessageType * Message, const FMessageAddress & Address, EMessageFlags Flags = EMessageFlags::None) inline protected
Definition at line 122 of file LiveLinkProviderImpl.h.
References Flags, FDateTime::MaxValue(), MessageEndpoint, and FTimespan::Zero().
SendMessage() [2/3]
template<typename MessageType> void FLiveLinkProvider::SendMessage (MessageType * Message, const TArray< FMessageAddress > & Addresses, EMessageFlags Flags = EMessageFlags::None) inline protected
Definition at line 133 of file LiveLinkProviderImpl.h.
References Flags, FDateTime::MaxValue(), MessageEndpoint, TArray< InElementType, InAllocatorType >::Num(), and FTimespan::Zero().
SendMessage() [3/3]
template<typename MessageType> void FLiveLinkProvider::SendMessage (MessageType * Message, EMessageFlags Flags = EMessageFlags::None) inline protected
Definition at line 106 of file LiveLinkProviderImpl.h.
References Flags, GetConnectedAddresses(), FDateTime::MaxValue(), MessageEndpoint, TArray< InElementType, InAllocatorType >::Num(), and FTimespan::Zero().
SendSubject()
void FLiveLinkProvider::SendSubject (FName SubjectName, const struct FTrackedSubject & Subject) private
SendSubjectFrame()
void FLiveLinkProvider::SendSubjectFrame (FName SubjectName, const struct FTrackedSubject & Subject) private
SerializeAnimationData()
struct FLiveLinkSerializedFrameData FLiveLinkProvider::SerializeAnimationData (struct FLiveLinkAnimationFrameData * AnimData) private
References SerializeAnimationData().
Referenced by SerializeAnimationData().
SetLastSubjectFrameData()
void FLiveLinkProvider::SetLastSubjectFrameData (FName SubjectName, FLiveLinkFrameDataStruct && FrameData, TMap< FName, FString > && SubjectAnnotations) private
SetLastSubjectStaticData()
void FLiveLinkProvider::SetLastSubjectStaticData (FName SubjectName, TSubclassOf< ULiveLinkRole > Role, FLiveLinkStaticDataStruct && StaticData, TMap< FName, FString > && Annotations) private
References Role.
ShouldTransmitToSubject_AnyThread()
virtual bool FLiveLinkProvider::ShouldTransmitToSubject_AnyThread (FName SubjectName, FMessageAddress Address) const inline protected virtual
Definition at line 188 of file LiveLinkProviderImpl.h.
Subscribe()
template<typename MessageType> void FLiveLinkProvider::Subscribe () inline protected
Definition at line 155 of file LiveLinkProviderImpl.h.
References MessageEndpoint.
UnregisterConnStatusChangedHandle()
virtual void FLiveLinkProvider::UnregisterConnStatusChangedHandle (FDelegateHandle Handle) override virtual
Function for managing connection status changed delegate.
Implements ILiveLinkProvider.
References Handle.
UpdateSubject()
virtual void FLiveLinkProvider::UpdateSubject (const FName & SubjectName, const TArray< FName > & BoneNames, const TArray< int32 > & BoneParents) virtual
UpdateSubjectFrame() [1/2]
virtual void FLiveLinkProvider::UpdateSubjectFrame (const FName & SubjectName, const TArray< FTransform > & BoneTransforms, const TArray< FLiveLinkCurveElement > & CurveData, const FLiveLinkMetaData & MetaData, double Time) virtual
References BoneTransforms, MetaData, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and Time.
UpdateSubjectFrame() [2/2]
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS void FLiveLinkProvider::UpdateSubjectFrame (const FName & SubjectName, const TArray< FTransform > & BoneTransforms, const TArray< FLiveLinkCurveElement > & CurveData, double Time) virtual
References BoneTransforms, and Time.
UpdateSubjectFrameData()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS bool FLiveLinkProvider::UpdateSubjectFrameData (const FName SubjectName, FLiveLinkFrameDataStruct && FrameData, const TMap< FName, FString > & ExtraAnnotations = {}) override virtual
Send the static data of a subject to UE.
Parameters
SubjectName The name of the subject
StaticData The frame data of the subject. The type should match the role's data send with UpdateSubjectStaticData. The FLiveLinkFrameDataStruct doesn't have a copy constructor. The argument is passed by r-value to help the user understand the compiler error message.
ExtraAnnotations Extra annotations to pass in with the frame data message.
Returns
True if the message was sent or is pending an active connection.
See also
UpdateSubjectStaticData, RemoveSubject
Implements ILiveLinkProvider.
UpdateSubjectStaticData()
virtual bool FLiveLinkProvider::UpdateSubjectStaticData (const FName SubjectName, TSubclassOf< ULiveLinkRole > Role, FLiveLinkStaticDataStruct && StaticData, const TMap< FName, FString > & ExtraAnnotations = {}) override virtual
Send, to UE, the static data of a subject.
Parameters
SubjectName The name of the subject
Role The Live Link role of the subject. The StaticData type should match the role's data.
StaticData The static data of the subject. The FLiveLinkStaticDataStruct doesn't have a copy constructor. The argument is passed by r-value to help the user understand the compiler error message.
ExtraAnnotations Extra annotations to pass in with the static data message.
Returns
True if the message was sent or is pending an active connection.
See also
UpdateSubjectFrameData, RemoveSubject
Implements ILiveLinkProvider.
References Role.
ValidateConnections()
void FLiveLinkProvider::ValidateConnections () protected
Field Documentation
ConnectedAddresses
TArray<struct FTrackedAddress> FLiveLinkProvider::ConnectedAddresses private
Definition at line 44 of file LiveLinkProviderImpl.h.
CriticalSection
FCriticalSection FLiveLinkProvider::CriticalSection mutable private
Definition at line 41 of file LiveLinkProviderImpl.h.
FrameDatas
TArray<struct FTrackedFrameData> FLiveLinkProvider::FrameDatas private
Definition at line 48 of file LiveLinkProviderImpl.h.
MachineName
const FString FLiveLinkProvider::MachineName private
Definition at line 36 of file LiveLinkProviderImpl.h.
Referenced by GetMachineName().
MessageEndpoint
TSharedPtr<class FMessageEndpoint, ESPMode::ThreadSafe> FLiveLinkProvider::MessageEndpoint private
Definition at line 38 of file LiveLinkProviderImpl.h.
Referenced by Publish(), SendMessage(), SendMessage(), SendMessage(), and Subscribe().
OnConnectionStatusChanged
FLiveLinkProviderConnectionStatusChanged FLiveLinkProvider::OnConnectionStatusChanged private
Definition at line 52 of file LiveLinkProviderImpl.h.
ProviderName
const FString FLiveLinkProvider::ProviderName private
Definition at line 35 of file LiveLinkProviderImpl.h.
Referenced by GetProviderName().
StaticDatas
TArray<struct FTrackedStaticData> FLiveLinkProvider::StaticDatas private
Definition at line 47 of file LiveLinkProviderImpl.h.
Subjects
TMap<FName, FTrackedSubject> FLiveLinkProvider::Subjects private
Definition at line 49 of file LiveLinkProviderImpl.h.
The documentation for this struct was generated from the following file:
LiveLinkProviderImpl.h