Unreal Engine 5.6 C++ API: FArchiveCookContext Struct Reference
FArchiveCookContext Struct Reference
Accessor for data about the package being cooked during UObject::Serialize calls.
#include "ArchiveCookContext.h"
Public Member Functions
FArchiveCookContext (UPackage *InPackage, UE::Cook::ECookType InCookType, UE::Cook::ECookingDLC InCookingDLC, const ITargetPlatform *InTargetPlatform, UE::Cook::ICookInfo *InCookInfo)
UE::Cook::ICookInfo * GetCookInfo ()
UE::Cook::ECookingDLC GetCookingDLC () const
FCookTagList * GetCookTagList ()
UE::Cook::ECookType GetCookType () const
const ITargetPlatform * GetTargetPlatform () const
bool IsCookByTheBook () const
bool IsCookOnTheFly () const
bool IsCookTypeUnknown () const
void Reset ()
UE_DEPRECATED (5.4, "Call version that takes TargetPlatform and CookInfo") FArchiveCookContext(UPackage *InPackage
UE_DEPRECATED (5.6, "Call version that takes CookInfo") FArchiveCookContext(UPackage *InPackage
Data Fields
UE::Cook::ECookType UE::Cook::ECookingDLC InCookingDLC
UE::Cook::ECookType InCookType
UE::Cook::ECookType UE::Cook::ECookingDLC const ITargetPlatform * InTargetPlatform
Private Attributes
bool bCookTagListEnabled = false
UE::Cook::ICookInfo * CookInfo = nullptr
UE::Cook::ECookingDLC CookingDLC = UE::Cook::ECookingDLC::Unknown
FCookTagList CookTagList
CookTagList is only valid for cook by the book; it is not publically accessible otherwise.
UE::Cook::ECookType CookType = UE::Cook::ECookType::Unknown
const ITargetPlatform * TargetPlatform = nullptr
Detailed Description
Accessor for data about the package being cooked during UObject::Serialize calls.
Definition at line 13 of file ArchiveCookContext.h.
Constructor & Destructor Documentation
FArchiveCookContext()
FArchiveCookContext::FArchiveCookContext (UPackage * InPackage, UE::Cook::ECookType InCookType, UE::Cook::ECookingDLC InCookingDLC, const ITargetPlatform * InTargetPlatform, UE::Cook::ICookInfo * InCookInfo) inline
Definition at line 73 of file ArchiveCookContext.h.
References FArchiveCookContext(), InCookingDLC, and InCookType.
Referenced by FArchiveCookContext(), and UE_DEPRECATED().
Member Function Documentation
GetCookInfo()
UE::Cook::ICookInfo * FArchiveCookContext::GetCookInfo () inline
Definition at line 136 of file ArchiveCookContext.h.
References CookInfo.
GetCookingDLC()
UE::Cook::ECookingDLC FArchiveCookContext::GetCookingDLC () const inline
Definition at line 131 of file ArchiveCookContext.h.
References CookingDLC.
GetCookTagList()
FCookTagList * FArchiveCookContext::GetCookTagList () inline
Definition at line 101 of file ArchiveCookContext.h.
References bCookTagListEnabled, and CookTagList.
GetCookType()
UE::Cook::ECookType FArchiveCookContext::GetCookType () const inline
Definition at line 126 of file ArchiveCookContext.h.
References CookType.
GetTargetPlatform()
const ITargetPlatform * FArchiveCookContext::GetTargetPlatform () const inline
Definition at line 106 of file ArchiveCookContext.h.
References TargetPlatform.
Referenced by FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer().
IsCookByTheBook()
bool FArchiveCookContext::IsCookByTheBook () const inline
Definition at line 111 of file ArchiveCookContext.h.
References UE::Cook::ByTheBook, and CookType.
IsCookOnTheFly()
bool FArchiveCookContext::IsCookOnTheFly () const inline
Definition at line 116 of file ArchiveCookContext.h.
References CookType, and UE::Cook::OnTheFly.
IsCookTypeUnknown()
bool FArchiveCookContext::IsCookTypeUnknown () const inline
Definition at line 121 of file ArchiveCookContext.h.
References CookType, and UE::Cook::Unknown.
Reset()
void FArchiveCookContext::Reset () inline
Definition at line 96 of file ArchiveCookContext.h.
References CookTagList.
UE_DEPRECATED() [1/2]
FArchiveCookContext::UE_DEPRECATED (5. 4, "Call version that takes TargetPlatform and CookInfo")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FArchiveCookContext::UE_DEPRECATED (5. 6, "Call version that takes CookInfo")
References FArchiveCookContext(), InCookingDLC, InCookType, and UE_DEPRECATED().
Field Documentation
bCookTagListEnabled
bool FArchiveCookContext::bCookTagListEnabled = false private
Definition at line 38 of file ArchiveCookContext.h.
Referenced by GetCookTagList().
CookInfo
UE::Cook::ICookInfo* FArchiveCookContext::CookInfo = nullptr private
Definition at line 41 of file ArchiveCookContext.h.
Referenced by GetCookInfo().
CookingDLC
UE::Cook::ECookingDLC FArchiveCookContext::CookingDLC = UE::Cook::ECookingDLC::Unknown private
Definition at line 40 of file ArchiveCookContext.h.
Referenced by GetCookingDLC().
CookTagList
FCookTagList FArchiveCookContext::CookTagList private
CookTagList is only valid for cook by the book; it is not publically accessible otherwise.
Definition at line 36 of file ArchiveCookContext.h.
Referenced by GetCookTagList(), and Reset().
CookType
UE::Cook::ECookType FArchiveCookContext::CookType = UE::Cook::ECookType::Unknown private
Definition at line 39 of file ArchiveCookContext.h.
Referenced by GetCookType(), IsCookByTheBook(), IsCookOnTheFly(), and IsCookTypeUnknown().
InCookingDLC
UE::Cook::ECookType UE::Cook::ECookingDLC FArchiveCookContext::InCookingDLC
Definition at line 46 of file ArchiveCookContext.h.
Referenced by FArchiveCookContext(), and UE_DEPRECATED().
InCookType
UE::Cook::ECookType FArchiveCookContext::InCookType
Definition at line 46 of file ArchiveCookContext.h.
Referenced by FArchiveCookContext(), and UE_DEPRECATED().
InTargetPlatform
UE::Cook::ECookType UE::Cook::ECookingDLC const ITargetPlatform* FArchiveCookContext::InTargetPlatform
Definition at line 49 of file ArchiveCookContext.h.
TargetPlatform
const ITargetPlatform* FArchiveCookContext::TargetPlatform = nullptr private
Definition at line 37 of file ArchiveCookContext.h.
Referenced by GetTargetPlatform().
The documentation for this struct was generated from the following file:
ArchiveCookContext.h