Unreal Engine 5.6 C++ API: FLocalLightSceneProxy Class Reference
FLocalLightSceneProxy Class Reference
The parts of the point light scene info that aren't dependent on the light policy type.
#include "LocalLightSceneProxy.h"
Public Member Functions
FLocalLightSceneProxy (const ULocalLightComponent *Component)
Initialization constructor.
virtual bool AffectsBounds (const FBoxSphereBounds &Bounds) const override
Tests whether the light affects the given bounding volume.
virtual FSphere GetBoundingSphere () const
virtual float GetEffectiveScreenRadius (const FViewMatrices &ShadowViewMatrices) const override
virtual float GetEffectiveScreenRadius (const FViewMatrices &ShadowViewMatrices, const FIntPoint &CameraViewRectSize) const override
virtual float GetFadeRange () const final override
virtual float GetMaxDrawDistance () const final override
virtual bool GetPerObjectProjectedShadowInitializer (const FBoxSphereBounds &SubjectBounds, class FPerObjectProjectedShadowInitializer &OutInitializer) const override
Sets up a projected shadow initializer for the given subject.
virtual FVector GetPerObjectProjectedShadowProjectionPoint (const FBoxSphereBounds &SubjectBounds) const
virtual float GetRadius () const override
virtual bool GetScissorRect (FIntRect &ScissorRect, const FSceneView &View, const FIntRect &ViewRect) const override
virtual bool IsLocalLight () const override
virtual bool SetScissorRect (FRHICommandList &RHICmdList, const FSceneView &View, const FIntRect &ViewRect, FIntRect *OutScissorRect=nullptr) const override
void UpdateRadius_GameThread (float Radius)
Called on the light scene info after it has been passed to the rendering thread to update the rendering thread's cached info when the light's radius changes.
Public Member Functions inherited from FLightSceneProxy
FLightSceneProxy (const ULightComponent *InLightComponent)
Initialization constructor.
virtual ~FLightSceneProxy ()
bool AffectGlobalIllumination () const
bool AffectReflection () const
bool AffectsTranslucentLighting () const
bool AllowMegaLights () const
virtual void ApplyWorldOffset (FVector InOffset)
Shifts light position and all relevant data by an arbitrary delta.
bool CastsDynamicShadow () const
bool CastsHairStrandsDeepShadow () const
bool CastsModulatedShadows () const
TEnumAsByte< ECastRayTracedShadow::Type > CastsRaytracedShadow () const
bool CastsShadowsFromCinematicObjectsOnly () const
bool CastsStaticShadow () const
bool CastsTranslucentShadows () const
bool CastsVolumetricShadow () const
FLinearColor GetAtmosphereSunDiskColorScale () const
uint8 GetAtmosphereSunLightIndex () const
virtual FLinearColor GetAtmosphereTransmittanceTowardSun () const
virtual bool GetCastCloudShadows () const
virtual bool GetCastShadowsOnAtmosphere () const
virtual bool GetCastShadowsOnClouds () const
virtual FLinearColor GetCloudScatteredLuminanceScale () const
virtual float GetCloudShadowDepthBias () const
virtual float GetCloudShadowExtent () const
virtual float GetCloudShadowMapResolutionScale () const
virtual float GetCloudShadowOnAtmosphereStrength () const
virtual float GetCloudShadowOnSurfaceStrength () const
virtual float GetCloudShadowRaySampleCountScale () const
virtual float GetCloudShadowStrength () const
const FLinearColor & GetColor () const
FName GetComponentFName () const
float GetContactShadowCastingIntensity () const
float GetContactShadowLength () const
float GetContactShadowNonCastingIntensity () const
float GetDeepShadowLayerDistribution () const
float GetDiffuseScale () const
FVector GetDirection () const
virtual FVector2D GetDirectionalLightDistanceFadeParameters (ERHIFeatureLevel::Type InFeatureLevel, bool bPrecomputedLightingIsValid, int32 MaxNearCascades) const
virtual int32 GetDirectionalLightForwardShadingPriority () const
bool GetForceCachedShadowsForMovablePrimitives () const
UTextureLightProfile * GetIESTexture () const
FTexture * GetIESTextureResource () const
float GetIndirectLightingScale () const
FName GetLevelName () const
const ULightComponent * GetLightComponent () const
Note: The Rendering thread must not dereference UObjects!
uint8 GetLightFunctionAtlasLightIndex () const
float GetLightFunctionDisabledBrightness () const
float GetLightFunctionFadeDistance () const
const FMaterialRenderProxy * GetLightFunctionMaterial () const
FVector GetLightFunctionScale () const
FGuid GetLightGuid () const
uint8 GetLightingChannelMask () const
virtual FVector GetLightPositionForLightShafts (FVector ViewOrigin) const
FLightSceneInfo * GetLightSceneInfo () const
virtual void GetLightShaderParameters (FLightRenderParameters &OutLightParameters, uint32 Flags=0) const
Accesses parameters needed for rendering the light.
virtual bool GetLightShaftOcclusionParameters (float &OutOcclusionMaskDarkness, float &OutOcclusionDepthRange) const
virtual float GetLightSourceAngle () const
const FMatrix & GetLightToWorld () const
uint8 GetLightType () const
TEnumAsByte< EMegaLightsShadowMethod::Type > GetMegaLightsShadowMethod () const
const FLinearColor & GetModulatedShadowColor () const
virtual uint32 GetNumViewDependentWholeSceneShadows (const FSceneView &View, bool bPrecomputedLightingIsValid) const
Returns the number of view dependent shadows this light will create, not counting distance field shadow cascades.
FVector GetOrigin () const
virtual float GetOuterConeAngle () const
virtual FLinearColor GetOuterSpaceIlluminance () const
virtual FLinearColor GetOuterSpaceLuminance () const
FString GetOwnerNameOrLabel () const
Use to get the owning actor label (or component name as fallback, if the owner is null or ENABLE_DEBUG_LABELS is off) for diagnostic messages, debug or profiling.
virtual bool GetPerPixelTransmittanceEnabled () const
FVector4 GetPosition () const
int32 GetPreviewShadowMapChannel () const
float GetRayStartOffsetDepthScale () const
uint32 GetSamplesPerPixel () const
FSceneInterface * GetSceneInterface () const
const float GetShadowAmount () const
int32 GetShadowMapChannel () const
float GetShadowResolutionScale () const
float GetShadowSharpen () const
virtual float GetShadowSourceAngleFactor () const
virtual FSphere GetShadowSplitBounds (const FSceneView &View, int32 InCascadeIndex, bool bPrecomputedLightingIsValid, FShadowCascadeSettings *OutCascadeSettings) const
virtual FSphere GetShadowSplitBoundsDepthRange (const FSceneView &View, FVector ViewOrigin, float SplitNear, float SplitFar, FShadowCascadeSettings *OutCascadeSettings) const
virtual float GetSourceRadius () const
float GetSpecularScale () const
const class FStaticShadowDepthMap * GetStaticShadowDepthMap () const
FORCEINLINE TStatId GetStatId () const
virtual FLinearColor GetSunIlluminanceAccountingForSkyAtmospherePerPixelTransmittance () const
virtual FLinearColor GetSunIlluminanceOnGroundPostTransmittance () const
virtual float GetSunLightHalfApexAngleRadian () const
virtual float GetTraceDistance () const
virtual bool GetUsePerPixelAtmosphereTransmittance () const
float GetUserShadowBias () const
float GetUserShadowSlopeBias () const
virtual bool GetViewDependentWholeSceneProjectedShadowInitializer (const FSceneView &View, int32 InCascadeIndex, bool bPrecomputedLightingIsValid, FWholeSceneProjectedShadowInitializer &OutInitializer) const
Sets up a projected shadow initializer that's dependent on the current view for shadows from the entire scene.
uint8 GetViewLightingChannelMask () const
float GetVolumetricScatteringIntensity () const
float GetVSMResolutionLodBias () const
float GetVSMTexelDitherScale () const
virtual bool GetWholeSceneProjectedShadowInitializer (const FSceneViewFamily &ViewFamily, TArray< FWholeSceneProjectedShadowInitializer, TInlineAllocator< 6 > > &OutInitializers) const
Sets up a projected shadow initializer for shadows from the entire scene.
const FMatrix & GetWorldToLight () const
virtual bool HasSourceTexture () const
bool HasStaticLighting () const
bool HasStaticShadowing () const
bool HasValidLightFunctionAtlasSlot () const
bool IsContactShadowLengthInWS () const
virtual bool IsInverseSquared () const
bool IsMovable () const
virtual bool IsRectLight () const
bool IsSelected () const
bool IsUsedAsAtmosphereSunLight () const
virtual void SetAtmosphereRelatedProperties (FLinearColor TransmittanceTowardSunIn, FLinearColor SunDiscOuterSpaceLuminanceIn)
void SetLightFunctionAtlasIndices (uint8 LightIndex)
void SetSelected (bool bNewSelected)
virtual bool ShouldCreatePerObjectShadowsForDynamicObjects () const
Whether this light should create per object shadows for dynamic objects.
virtual bool ShouldCreateRayTracedCascade (ERHIFeatureLevel::Type Type, bool bPrecomputedLightingIsValid, int32 MaxNearCascades) const
bool Transmission () const
UE_DEPRECATED (5.1, "The GetEffectiveScreenRadius() that uses the screen-percentage scaled view rect (above) is used now.") virtual float GetEffectiveScreenRadius(const FViewMatrices &ShadowViewMatrices) const
virtual bool UseCSMForDynamicObjects () const
Whether this light should create CSM for dynamic objects only (forward renderer)
bool UseRayTracedDistanceFieldShadows () const
bool UseVirtualShadowMaps () const
Public Member Functions inherited from FLightSceneProxyFixLayout
virtual ~FLightSceneProxyFixLayout ()=default
Data Fields
float InvRadius
One over the light's radius.
float Radius
The light radius.
Protected Member Functions
void UpdateRadius (float ComponentRadius)
Updates the light scene info's radius from the component.
Protected Member Functions inherited from FLightSceneProxy
void SetColor (const FLinearColor &InColor)
Updates the light's color.
void SetTransform (const FMatrix &InLightToWorld, const FVector4 &InPosition)
Updates the light proxy's cached transforms.
Protected Attributes
float FadeRange
float InverseExposureBlend
float MaxDrawDistance
Protected Attributes inherited from FLightSceneProxy
FLinearColor AtmosphereSunDiskColorScale
const uint8 AtmosphereSunLightIndex
The index of the atmospheric light.
const uint8 bAffectGlobalIllumination: 1
Whether the light affects global illumination, when ray-traced global illumination is enabled.
const uint8 bAffectReflection: 1
Whether the light affects objects in reflections, when ray-traced reflection is enabled.
const uint8 bAffectTranslucentLighting: 1
Whether the light affects translucency or not.
const uint8 bAllowMegaLights: 1
Whether the light should be rendered with MegaLights.
uint8 bCastDynamicShadow: 1
True if the light casts dynamic shadows.
const uint8 bCastHairStrandsDeepShadow: 1
uint8 bCastModulatedShadows: 1
Whether the light will cast modulated shadows when using the forward renderer (mobile).
const uint8 bCastShadowsFromCinematicObjectsOnly: 1
const uint8 bCastStaticShadow: 1
True if the light casts static shadows.
const uint8 bCastTranslucentShadows: 1
Whether the light is allowed to cast dynamic shadows from translucency.
const uint8 bCastVolumetricShadow: 1
uint8 bContactShadowLengthInWS: 1
True: length of screen space ray trace for sharp contact shadows is in world space.
const uint8 bForceCachedShadowsForMovablePrimitives: 1
const uint8 bMovable: 1
uint8 bSelected: 1
Is the light selected in the editor?
const uint8 bStaticLighting: 1
Return True if a light's parameters as well as its position is static during gameplay, and can thus use static lighting.
uint8 bStaticShadowing: 1
Whether the light has static direct shadowing.
uint8 bTransmission: 1
Whether light from this light transmits through surfaces with subsurface scattering profiles.
const uint8 bUsedAsAtmosphereSunLight: 1
Whether to consider light as a sunlight for atmospheric scattering and exponential height fog.
const uint8 bUseRayTracedDistanceFieldShadows: 1
Whether to use ray traced distance field area shadows.
uint8 bUseVirtualShadowMaps: 1
Whether to use virtual shadow maps.
uint8 bUseWholeSceneCSMForMovableObjects: 1
Whether to render csm shadows for movable objects only (mobile).
const TEnumAsByte< ECastRayTracedShadow::Type > CastRaytracedShadow
Whether the light shadows are computed with shadow-mapping or ray-tracing (when available).
FLinearColor Color
The light color.
FName ComponentName
The name of the light component.
float ContactShadowCastingIntensity
Intensity of the shadows cast by primitives with "cast contact shadow" enabled.
float ContactShadowLength
Length of screen space ray trace for sharp contact shadows.
float ContactShadowNonCastingIntensity
Intensity of the shadows cast by primitives with "cast contact shadow" disabled.
float DeepShadowLayerDistribution
Deep shadow layer distribution.
float DiffuseScale
Diffuse scale.
uint32 FarShadowCascadeCount
Only for whole scene directional lights, 0: no FarShadowCascades, otherwise the count of cascades between WholeSceneDynamicShadowRadius and FarShadowDistance that are covered by distant shadow cascades.
float FarShadowDistance
Only for whole scene directional lights, if FarShadowCascadeCount > 0 and FarShadowDistance >= WholeSceneDynamicShadowRadius, where far shadow cascade should end.
uint32 IESAtlasId
IES texture atlas id.
UTextureLightProfile * IESTexture
IES texture (light profiles from real world measured data) We are safe to store a U pointer as those objects get deleted deferred, storing an FTexture pointer would crash if we recreate the texture.
float IndirectLightingScale
Scale for indirect lighting from this light.
FName LevelName
The name of the level the light is in.
const ULightComponent * LightComponent
The light component.
uint8 LightFunctionAtlasLightIndex
The light index in order to be able to read matrix and parameters when reading the light function atlas for that light.
float LightFunctionDisabledBrightness
float LightFunctionFadeDistance
const FMaterialRenderProxy * LightFunctionMaterial
FVector LightFunctionScale
Light function parameters.
FGuid LightGuid
The light's persistent shadowing GUID.
uint8 LightingChannelMask
class FLightSceneInfo * LightSceneInfo
The light's scene info.
FMatrix LightToWorld
A transform from light space into world space.
const uint8 LightType
The light type (ELightComponentType)
const TEnumAsByte< EMegaLightsShadowMethod::Type > MegaLightsShadowMethod
Whether the light shadows are computed with shadow-mapping or ray-tracing (when available).
FLinearColor ModulatedShadowColor
Modulated shadow color.
FVector4 Position
The homogeneous position of the light.
int32 PreviewShadowMapChannel
Transient shadowmap channel used to preview the results of stationary light shadowmap packing.
float RayStartOffsetDepthScale
uint32 SamplesPerPixel
Samples per pixel for ray tracing.
FSceneInterface * SceneInterface
The scene the primitive is in.
float ShadowAmount
Control the amount of shadow occlusion.
float ShadowBias
User setting from light component, 0:no bias, 0.5:reasonable, larger object might appear to float.
int32 ShadowMapChannel
Shadow map channel which is used to match up with the appropriate static shadowing during a deferred shading pass.
float ShadowResolutionScale
float ShadowSharpen
Sharpen shadow filtering.
float ShadowSlopeBias
User setting from light component, 0:no bias, 0.5:reasonable, larger object might appear to float.
float SpecularScale
Specular scale.
const class FStaticShadowDepthMap * StaticShadowDepthMap
TStatId StatId
Used for dynamic stats.
uint8 ViewLightingChannelMask
float VolumetricScatteringIntensity
Scales this light's intensity for volumetric scattering.
float VSMResolutionLodBias
Used to control shadow resolution for each light.
float VSMTexelDitherScale
Used to control the amount of additional dither filtering applied to shadows for each light.
FMatrix WorldToLight
A transform from world space into light space.
Additional Inherited Members
Static Public Member Functions inherited from FLightSceneProxy
static float GetSunOnEarthHalfApexAngleRadian ()
Detailed Description
The parts of the point light scene info that aren't dependent on the light policy type.
Definition at line 14 of file LocalLightSceneProxy.h.
Constructor & Destructor Documentation
FLocalLightSceneProxy()
FLocalLightSceneProxy::FLocalLightSceneProxy (const ULocalLightComponent * Component)
Initialization constructor.
References Component.
Member Function Documentation
AffectsBounds()
virtual bool FLocalLightSceneProxy::AffectsBounds (const FBoxSphereBounds & Bounds) const override virtual
Tests whether the light affects the given bounding volume.
Parameters
Bounds - The bounding volume to test.
Returns
True if the light affects the bounding volume
Reimplemented from FLightSceneProxy.
References AffectsBounds().
Referenced by AffectsBounds().
GetBoundingSphere()
virtual FSphere FLocalLightSceneProxy::GetBoundingSphere () const virtual
Reimplemented from FLightSceneProxy.
References GetBoundingSphere().
Referenced by GetBoundingSphere().
GetEffectiveScreenRadius() [1/2]
virtual float FLocalLightSceneProxy::GetEffectiveScreenRadius (const FViewMatrices & ShadowViewMatrices) const override virtual
References GetEffectiveScreenRadius().
GetEffectiveScreenRadius() [2/2]
virtual float FLocalLightSceneProxy::GetEffectiveScreenRadius (const FViewMatrices & ShadowViewMatrices, const FIntPoint & CameraViewRectSize) const override virtual
Reimplemented from FLightSceneProxy.
References GetEffectiveScreenRadius().
Referenced by GetEffectiveScreenRadius(), and GetEffectiveScreenRadius().
GetFadeRange()
virtual float FLocalLightSceneProxy::GetFadeRange () const final override virtual
Reimplemented from FLightSceneProxy.
References GetFadeRange().
Referenced by GetFadeRange().
GetMaxDrawDistance()
virtual float FLocalLightSceneProxy::GetMaxDrawDistance () const final override virtual
Reimplemented from FLightSceneProxy.
GetPerObjectProjectedShadowInitializer()
virtual bool FLocalLightSceneProxy::GetPerObjectProjectedShadowInitializer (const FBoxSphereBounds & SubjectBounds, class FPerObjectProjectedShadowInitializer & OutInitializer) const override virtual
Sets up a projected shadow initializer for the given subject.
Parameters
SubjectBounds - The bounding volume of the subject.
OutInitializer - Upon successful return, contains the initialization parameters for the shadow.
Returns
True if a projected shadow should be cast by this subject-light pair.
Reimplemented from FLightSceneProxy.
References GetPerObjectProjectedShadowInitializer().
Referenced by GetPerObjectProjectedShadowInitializer().
GetPerObjectProjectedShadowProjectionPoint()
virtual FVector FLocalLightSceneProxy::GetPerObjectProjectedShadowProjectionPoint (const FBoxSphereBounds & SubjectBounds) const virtual
References FVector, and GetPerObjectProjectedShadowProjectionPoint().
Referenced by GetPerObjectProjectedShadowProjectionPoint().
GetRadius()
virtual float FLocalLightSceneProxy::GetRadius () const override virtual
Returns
radius of the light or 0 if no radius
Reimplemented from FLightSceneProxy.
References GetRadius().
Referenced by GetRadius().
GetScissorRect()
virtual bool FLocalLightSceneProxy::GetScissorRect (FIntRect & ScissorRect, const FSceneView & View, const FIntRect & ViewRect) const override virtual
Reimplemented from FLightSceneProxy.
References GetScissorRect().
Referenced by GetScissorRect().
IsLocalLight()
virtual bool FLocalLightSceneProxy::IsLocalLight () const override virtual
Reimplemented from FLightSceneProxy.
References IsLocalLight().
Referenced by IsLocalLight().
SetScissorRect()
virtual bool FLocalLightSceneProxy::SetScissorRect (FRHICommandList & RHICmdList, const FSceneView & View, const FIntRect & ViewRect, FIntRect * OutScissorRect = nullptr) const override virtual
Reimplemented from FLightSceneProxy.
References SetScissorRect().
Referenced by SetScissorRect().
UpdateRadius()
void FLocalLightSceneProxy::UpdateRadius (float ComponentRadius) protected
Updates the light scene info's radius from the component.
References UpdateRadius().
Referenced by UpdateRadius().
UpdateRadius_GameThread()
void FLocalLightSceneProxy::UpdateRadius_GameThread (float Radius)
Called on the light scene info after it has been passed to the rendering thread to update the rendering thread's cached info when the light's radius changes.
References Radius.
Field Documentation
FadeRange
float FLocalLightSceneProxy::FadeRange protected
Definition at line 64 of file LocalLightSceneProxy.h.
InverseExposureBlend
float FLocalLightSceneProxy::InverseExposureBlend protected
Definition at line 65 of file LocalLightSceneProxy.h.
InvRadius
float FLocalLightSceneProxy::InvRadius
One over the light's radius.
Definition at line 22 of file LocalLightSceneProxy.h.
MaxDrawDistance
float FLocalLightSceneProxy::MaxDrawDistance protected
Definition at line 63 of file LocalLightSceneProxy.h.
Radius
float FLocalLightSceneProxy::Radius
The light radius.
Definition at line 19 of file LocalLightSceneProxy.h.
Referenced by UpdateRadius_GameThread().
The documentation for this class was generated from the following file:
LocalLightSceneProxy.h