Unreal Engine 5.6 C++ API: UE::FPlatformIoDispatcher Class Reference
UE::FPlatformIoDispatcher Class Reference
#include "PlatformIoDispatcher.h"
Static Public Member Functions
static void Create (FPlatformIoDispatcherCreateParams &&Config)
static IPlatformIoDispatcher & Get ()
static void Initialize ()
static void Shutdown ()
static IPlatformIoDispatcher * TryGet ()
Detailed Description
Definition at line 268 of file PlatformIoDispatcher.h.
Member Function Documentation
Create()
void UE::FPlatformIoDispatcher::Create (FPlatformIoDispatcherCreateParams && Config) static
Definition at line 21 of file PlatformIoDispatcher.cpp.
References UE::FGenericPlatformIoDispatcherFactory::Create(), UE::GPlatformIoDispatcher, UE::MakeGenericPlatformIoDispatcher(), MoveTemp(), and Params.
Get()
IPlatformIoDispatcher & UE::FPlatformIoDispatcher::Get () static
Definition at line 46 of file PlatformIoDispatcher.cpp.
References UE::GPlatformIoDispatcher.
Initialize()
void UE::FPlatformIoDispatcher::Initialize () static
Definition at line 33 of file PlatformIoDispatcher.cpp.
References UE::GPlatformIoDispatcher.
Shutdown()
void UE::FPlatformIoDispatcher::Shutdown () static
Definition at line 41 of file PlatformIoDispatcher.cpp.
References UE::GPlatformIoDispatcher.
TryGet()
IPlatformIoDispatcher * UE::FPlatformIoDispatcher::TryGet () static
Definition at line 51 of file PlatformIoDispatcher.cpp.
References UE::GPlatformIoDispatcher.
The documentation for this class was generated from the following files:
PlatformIoDispatcher.h
PlatformIoDispatcher.cpp