Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > > Struct Template Reference
UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > > Struct Template Reference
#include "MovieSceneEntitySystemTask.h"
Static Public Member Functions
template<typename TaskImpl, typename... AccessorTypes>
static void ForEachAllocationImpl (TaskImpl &TaskImplInstance, FEntityAllocationIteratorItem Item, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > &Components)
template<typename TaskImpl, typename... AccessorTypes>
static void ForEachAllocationImpl (TaskImpl &TaskImplInstance, FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > &Components)
template<typename TaskImpl, typename... AccessorTypes>
static void ForEachEntityImpl (TaskImpl &TaskImplInstance, FEntityAllocationIteratorItem Item, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > &Components)
template<typename TaskImpl, typename... AccessorTypes>
static void ForEachEntityImpl (TaskImpl &TaskImplInstance, FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > &Components)
Detailed Description
template<int... Indices>
struct UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >
Definition at line 1872 of file MovieSceneEntitySystemTask.h.
Member Function Documentation
ForEachAllocationImpl() [1/2]
template<int... Indices> template<typename TaskImpl, typename... AccessorTypes> void UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachAllocationImpl (TaskImpl & TaskImplInstance, FEntityAllocationIteratorItem Item, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > & Components) inline static
Definition at line 1913 of file MovieSceneEntitySystemTask.h.
References Components, Item, and MakeTuple().
ForEachAllocationImpl() [2/2]
template<int... Indices> template<typename TaskImpl, typename... AccessorTypes> void UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachAllocationImpl (TaskImpl & TaskImplInstance, FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > & Components) inline static
Definition at line 1905 of file MovieSceneEntitySystemTask.h.
References Components, and Item.
ForEachEntityImpl() [1/2]
template<int... Indices> template<typename TaskImpl, typename... AccessorTypes> void UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl (TaskImpl & TaskImplInstance, FEntityAllocationIteratorItem Item, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > & Components) inline static
Definition at line 1890 of file MovieSceneEntitySystemTask.h.
References Components, UE::MovieScene::GetComponentAtIndex(), Item, MakeTuple(), and Num.
ForEachEntityImpl() [2/2]
template<int... Indices> template<typename TaskImpl, typename... AccessorTypes> void UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl (TaskImpl & TaskImplInstance, FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, FEntityAllocationWriteContext WriteContext, const TEntityTaskComponents< AccessorTypes... > & Components) inline static
Definition at line 1875 of file MovieSceneEntitySystemTask.h.
References Components, UE::MovieScene::GetComponentAtIndex(), Item, MakeTuple(), and Num.
The documentation for this struct was generated from the following file:
MovieSceneEntitySystemTask.h