Unreal Engine 5.6 C++ API: TSparseArray< InElementType, Allocator >::TIterator Class Reference
TSparseArray< InElementType, Allocator >::TIterator Class Reference
Iterates over all allocated elements in a sparse array.
#include "SparseArray.h"
Public Member Functions
TIterator (TSparseArray &InArray)
TIterator (TSparseArray &InArray, const typename TBaseIterator< false >::BitArrayItType &InBitArrayIt)
void RemoveCurrent ()
Safely removes the current element from the array.
Public Member Functions inherited from TSparseArray< InElementType, Allocator >::TBaseIterator< false >
TBaseIterator (ArrayType &InArray, const BitArrayItType &InBitArrayIt)
FORCEINLINE int32 GetIndex () const
FORCEINLINE const FRelativeBitReference & GetRelativeBitReference () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
FORCEINLINE ItElementType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
FORCEINLINE ItElementType * operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
Additional Inherited Members
Public Types inherited from TSparseArray< InElementType, Allocator >::TBaseIterator< false >
typedef TConstSetBitIterator< typename Allocator::BitArrayAllocator > BitArrayItType
Protected Attributes inherited from TSparseArray< InElementType, Allocator >::TBaseIterator< false >
ArrayType & Array
BitArrayItType BitArrayIt
Detailed Description
template<typename InElementType, typename Allocator>
class TSparseArray< InElementType, Allocator >::TIterator
Iterates over all allocated elements in a sparse array.
Definition at line 1012 of file SparseArray.h.
Constructor & Destructor Documentation
TIterator() [1/2]
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::TIterator::TIterator (TSparseArray & InArray) inline nodiscard
Definition at line 1015 of file SparseArray.h.
References TSparseArray< InElementType, Allocator >::TBaseIterator< false >::TBaseIterator(), TSparseArray< InElementType, Allocator >::TSparseArray(), TSparseArray< InElementType, Allocator >::AllocationFlags, and Allocator.
Referenced by TSparseArray< InElementType, Allocator >::TRangedForIterator::TRangedForIterator(), and TSparseArray< InElementType, Allocator >::TRangedForIterator::operator!=().
TIterator() [2/2]
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::TIterator::TIterator (TSparseArray & InArray, const typename TBaseIterator< false >::BitArrayItType & InBitArrayIt) inline nodiscard
Definition at line 1020 of file SparseArray.h.
References TSparseArray< InElementType, Allocator >::TBaseIterator< false >::TBaseIterator(), and TSparseArray< InElementType, Allocator >::TSparseArray().
Member Function Documentation
RemoveCurrent()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::TIterator::RemoveCurrent () inline
Safely removes the current element from the array.
Definition at line 1026 of file SparseArray.h.
References TSparseArray< InElementType, Allocator >::TBaseIterator< false >::Array, and TSparseArray< InElementType, Allocator >::TBaseIterator< false >::GetIndex().
The documentation for this class was generated from the following file:
SparseArray.h