Unreal Engine 5.6 C++ API: UE::Geometry::FWindingNumberBasedSolidify Class Reference
UE::Geometry::FWindingNumberBasedSolidify Class Reference
Use marching cubes to remesh an arbitrary function that provides a winding-number like scalar value to a solid surface.
#include "Solidify.h"
Public Member Functions
FWindingNumberBasedSolidify (TUniqueFunction< double(const FVector3d &)> WindingFunctionIn, const FAxisAlignedBox3d &BoundsIn, const TArray< FVector3d > &SeedPointsIn)
virtual ~FWindingNumberBasedSolidify ()
const FMeshShapeGenerator & Generate ()
void SetCellSizeAndExtendBounds (const FAxisAlignedBox3d &Bounds, double ExtendBoundsIn, int TargetOutputVoxelCount)
Set cell size to hit the target voxel count along the max dimension of the bounds.
bool Validate ()
Data Fields
bool bSolidAtBoundaries = true
What to do if the surface extends outside the marching cubes bounds – if true, puts a solid surface at the boundary.
TFunction< bool(void)> CancelF
if this function returns true, we should abort calculation
double ExtendBounds = 1
How much to extend bounds considered by marching cubes outside the original surface bounds.
FAxisAlignedBox3d FunctionBounds
Bounds within which we will mesh things.
double MeshCellSize = 1.0
size of the cells used when meshing the output (marching cubes' cube size)
TArray< FVector3d > SeedPoints
Seed points for meshing.
int SurfaceSearchSteps = 4
How many binary search steps to do when placing surface at boundary.
TUniqueFunction< double(const FVector3d &)> WindingFunction = [](const FVector3d& Pos) { return 0.0; }
Inputs.
double WindingThreshold = .5
Inside/outside winding number threshold.
Protected Attributes
FMarchingCubes MarchingCubes
Detailed Description
Use marching cubes to remesh an arbitrary function that provides a winding-number like scalar value to a solid surface.
Definition at line 167 of file Solidify.h.
Constructor & Destructor Documentation
FWindingNumberBasedSolidify()
UE::Geometry::FWindingNumberBasedSolidify::FWindingNumberBasedSolidify (TUniqueFunction< double(const FVector3d &)> WindingFunctionIn, const FAxisAlignedBox3d & BoundsIn, const TArray< FVector3d > & SeedPointsIn) inline
Definition at line 171 of file Solidify.h.
References FunctionBounds, MoveTemp(), SeedPoints, and WindingFunction.
~FWindingNumberBasedSolidify()
virtual UE::Geometry::FWindingNumberBasedSolidify::~FWindingNumberBasedSolidify () inline virtual
Definition at line 181 of file Solidify.h.
Member Function Documentation
Generate()
const FMeshShapeGenerator & UE::Geometry::FWindingNumberBasedSolidify::Generate () inline
Definition at line 246 of file Solidify.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::Bisection, bSolidAtBoundaries, CancelF, UE::Geometry::TAxisAlignedBox3< RealType >::Contains(), ensure, UE::Geometry::TAxisAlignedBox3< RealType >::Expand(), ExtendBounds, FunctionBounds, MarchingCubes, MeshCellSize, SeedPoints, SurfaceSearchSteps, Validate(), WindingFunction, and WindingThreshold.
SetCellSizeAndExtendBounds()
void UE::Geometry::FWindingNumberBasedSolidify::SetCellSizeAndExtendBounds (const FAxisAlignedBox3d & Bounds, double ExtendBoundsIn, int TargetOutputVoxelCount) inline
Set cell size to hit the target voxel count along the max dimension of the bounds.
Definition at line 216 of file Solidify.h.
References ExtendBounds, UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), and MeshCellSize.
Validate()
bool UE::Geometry::FWindingNumberBasedSolidify::Validate () inline
Returns
true if input parameters are valid
Definition at line 237 of file Solidify.h.
References MeshCellSize, and SurfaceSearchSteps.
Referenced by Generate().
Field Documentation
bSolidAtBoundaries
bool UE::Geometry::FWindingNumberBasedSolidify::bSolidAtBoundaries = true
What to do if the surface extends outside the marching cubes bounds – if true, puts a solid surface at the boundary.
Definition at line 205 of file Solidify.h.
Referenced by Generate().
CancelF
TFunction<bool(void)> UE::Geometry::FWindingNumberBasedSolidify::CancelF
Initial value:
= []()
    {
        return false;
    }
if this function returns true, we should abort calculation
Definition at line 223 of file Solidify.h.
Referenced by Generate().
ExtendBounds
double UE::Geometry::FWindingNumberBasedSolidify::ExtendBounds = 1
How much to extend bounds considered by marching cubes outside the original surface bounds.
Definition at line 202 of file Solidify.h.
Referenced by Generate(), and SetCellSizeAndExtendBounds().
FunctionBounds
FAxisAlignedBox3d UE::Geometry::FWindingNumberBasedSolidify::FunctionBounds
Bounds within which we will mesh things.
Definition at line 193 of file Solidify.h.
Referenced by FWindingNumberBasedSolidify(), and Generate().
MarchingCubes
FMarchingCubes UE::Geometry::FWindingNumberBasedSolidify::MarchingCubes protected
Definition at line 230 of file Solidify.h.
Referenced by Generate().
MeshCellSize
double UE::Geometry::FWindingNumberBasedSolidify::MeshCellSize = 1.0
size of the cells used when meshing the output (marching cubes' cube size)
Definition at line 211 of file Solidify.h.
Referenced by Generate(), SetCellSizeAndExtendBounds(), and Validate().
SeedPoints
TArray<FVector3d> UE::Geometry::FWindingNumberBasedSolidify::SeedPoints
Seed points for meshing.
Definition at line 196 of file Solidify.h.
Referenced by FWindingNumberBasedSolidify(), and Generate().
SurfaceSearchSteps
int UE::Geometry::FWindingNumberBasedSolidify::SurfaceSearchSteps = 4
How many binary search steps to do when placing surface at boundary.
Definition at line 208 of file Solidify.h.
Referenced by Generate(), and Validate().
WindingFunction
TUniqueFunction<double(const FVector3d&)> UE::Geometry::FWindingNumberBasedSolidify::WindingFunction = [](const FVector3d& Pos) { return 0.0; }
Inputs.
External Winding-Number Function
Definition at line 190 of file Solidify.h.
Referenced by FWindingNumberBasedSolidify(), and Generate().
WindingThreshold
double UE::Geometry::FWindingNumberBasedSolidify::WindingThreshold = .5
Inside/outside winding number threshold.
Definition at line 199 of file Solidify.h.
Referenced by Generate().
The documentation for this class was generated from the following file:
Solidify.h