Unreal Engine 5.6 C++ API: FPoseContext Struct Reference
FPoseContext Struct Reference
Evaluation context passed around during animation tree evaluation.
#include "AnimNodeBase.h"
Public Member Functions
FPoseContext (const FBoneContainer &InRequiredBones, bool bInExpectsAdditivePose=false)
FPoseContext (const FPoseContext &SourceContext, bool bInOverrideExpectsAdditivePose=false)
FPoseContext (FAnimInstanceProxy *InAnimInstanceProxy, bool bInExpectsAdditivePose=false)
bool ContainsNaN () const
bool ExpectsAdditivePose () const
bool IsNormalized () const
void LogMessage (const TSharedRef< FTokenizedMessage > &InMessage) const
void LogMessage (EMessageSeverity::Type InSeverity, FText InMessage) const
FPoseContext & operator= (const FPoseContext &Other)
void ResetToAdditiveIdentity ()
void ResetToRefPose ()
UE_DEPRECATED (5.2, "This function will be made private. It should never be called externally, use the constructor instead.") void Initialize(FAnimInstanceProxy *InAnimInstanceProxy)
Public Member Functions inherited from FAnimationBaseContext
FAnimationBaseContext ()
FAnimationBaseContext (const FAnimationBaseContext &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAnimationBaseContext (FAnimationBaseContext &&)=default
template<typename TGraphMessageType>
TGraphMessageType * FindMessage (TFunctionRef< bool(TGraphMessageType &)> InFunction) const
IAnimClassInterface * GetAnimClass () const
UObject * GetAnimInstanceObject () const
int32 GetCurrentNodeId () const
template<typename TGraphMessageType>
TGraphMessageType * GetMessage () const
template<typename TGraphMessageType>
TGraphMessageType & GetMessageChecked () const
int32 GetPreviousNodeId () const
bool IsActive () const
FAnimationBaseContext & operator= (const FAnimationBaseContext &)=default
FAnimationBaseContext & operator= (FAnimationBaseContext &&)=default
void SetNodeId (int32 InNodeId)
void SetNodeIds (const FAnimationBaseContext &InContext)
template<typename NodeType>
UE_DEPRECATED (5.0, "Please use the message & tagging system in UE::Anim::FMessageStack") FScopedAnimNodeTracker TrackAncestor(NodeType *Node) const
template<typename NodeType>
UE_DEPRECATED (5.0, "Please use the message & tagging system in UE::Anim::FMessageStack") NodeType *GetAncestor() const
Data Fields
FBlendedCurve Curve
UE::Anim::FStackAttributeContainer CustomAttributes
FCompactPose Pose
Data Fields inherited from FAnimationBaseContext
FAnimInstanceProxy * AnimInstanceProxy
FAnimationUpdateSharedContext * SharedContext
Private Member Functions
void InitializeImpl (FAnimInstanceProxy *InAnimInstanceProxy)
Private Attributes
bool bExpectsAdditivePose
Friends
class FScopedExpectsAdditiveOverride
Additional Inherited Members
Protected Member Functions inherited from FAnimationBaseContext
FAnimationBaseContext (FAnimInstanceProxy *InAnimInstanceProxy, FAnimationUpdateSharedContext *InSharedContext=nullptr)
FAnimationBaseContext (UAnimInstance *InAnimInstance)
void LogMessageInternal (FName InLogType, const TSharedRef< FTokenizedMessage > &InMessage) const
Interface for node contexts to register log messages with the proxy.
Protected Attributes inherited from FAnimationBaseContext
bool bIsActive = true
int32 CurrentNodeId
int32 PreviousNodeId
Detailed Description
Evaluation context passed around during animation tree evaluation.
Definition at line 478 of file AnimNodeBase.h.
Constructor & Destructor Documentation
FPoseContext() [1/3]
FPoseContext::FPoseContext (FAnimInstanceProxy * InAnimInstanceProxy, bool bInExpectsAdditivePose = false) inline
Definition at line 490 of file AnimNodeBase.h.
References FAnimationBaseContext::FAnimationBaseContext(), bExpectsAdditivePose, and InitializeImpl().
Referenced by FPoseContext(), and operator=().
FPoseContext() [2/3]
FPoseContext::FPoseContext (const FPoseContext & SourceContext, bool bInOverrideExpectsAdditivePose = false) inline
Definition at line 498 of file AnimNodeBase.h.
References FAnimationBaseContext::FAnimationBaseContext(), FPoseContext(), FAnimationBaseContext::AnimInstanceProxy, bExpectsAdditivePose, FAnimationBaseContext::CurrentNodeId, InitializeImpl(), and FAnimationBaseContext::PreviousNodeId.
FPoseContext() [3/3]
FPoseContext::FPoseContext (const FBoneContainer & InRequiredBones, bool bInExpectsAdditivePose = false) inline
Definition at line 509 of file AnimNodeBase.h.
References FAnimationBaseContext::FAnimationBaseContext(), bExpectsAdditivePose, checkSlow, Curve, FBoneContainer::IsValid(), and Pose.
Member Function Documentation
ContainsNaN()
bool FPoseContext::ContainsNaN () const inline
Definition at line 542 of file AnimNodeBase.h.
References Pose.
ExpectsAdditivePose()
bool FPoseContext::ExpectsAdditivePose () const inline
Definition at line 567 of file AnimNodeBase.h.
References bExpectsAdditivePose.
InitializeImpl()
void FPoseContext::InitializeImpl (FAnimInstanceProxy * InAnimInstanceProxy) private
Referenced by FPoseContext(), FPoseContext(), operator=(), and UE_DEPRECATED().
IsNormalized()
bool FPoseContext::IsNormalized () const inline
Definition at line 547 of file AnimNodeBase.h.
References Pose.
LogMessage() [1/2]
void FPoseContext::LogMessage (const TSharedRef< FTokenizedMessage > & InMessage) const inline
Definition at line 522 of file AnimNodeBase.h.
References FAnimationBaseContext::LogMessageInternal().
LogMessage() [2/2]
void FPoseContext::LogMessage (EMessageSeverity::Type InSeverity, FText InMessage) const inline
Definition at line 523 of file AnimNodeBase.h.
References FTokenizedMessage::Create(), and LogMessage().
Referenced by LogMessage().
operator=()
FPoseContext & FPoseContext::operator= (const FPoseContext & Other) inline
Definition at line 552 of file AnimNodeBase.h.
References FPoseContext(), FAnimationBaseContext::AnimInstanceProxy, bExpectsAdditivePose, Curve, CustomAttributes, InitializeImpl(), Other, and Pose.
ResetToAdditiveIdentity()
void FPoseContext::ResetToAdditiveIdentity () inline
Definition at line 537 of file AnimNodeBase.h.
References Pose.
ResetToRefPose()
void FPoseContext::ResetToRefPose () inline
Definition at line 525 of file AnimNodeBase.h.
References bExpectsAdditivePose, and Pose.
UE_DEPRECATED()
FPoseContext::UE_DEPRECATED (5. 2, "This function will be made private. It should never be called externally, use the constructor instead.") inline
Definition at line 518 of file AnimNodeBase.h.
References Initialize, and InitializeImpl().
Friends And Related Symbol Documentation
FScopedExpectsAdditiveOverride
friend class FScopedExpectsAdditiveOverride friend
Definition at line 487 of file AnimNodeBase.h.
References FScopedExpectsAdditiveOverride.
Referenced by FScopedExpectsAdditiveOverride.
Field Documentation
bExpectsAdditivePose
bool FPoseContext::bExpectsAdditivePose private
Definition at line 573 of file AnimNodeBase.h.
Referenced by FPoseContext(), FPoseContext(), FPoseContext(), ExpectsAdditivePose(), operator=(), and ResetToRefPose().
Curve
FBlendedCurve FPoseContext::Curve
Definition at line 483 of file AnimNodeBase.h.
Referenced by FPoseContext(), and operator=().
CustomAttributes
UE::Anim::FStackAttributeContainer FPoseContext::CustomAttributes
Definition at line 484 of file AnimNodeBase.h.
Referenced by operator=().
Pose
FCompactPose FPoseContext::Pose
Definition at line 482 of file AnimNodeBase.h.
Referenced by FPoseContext(), ContainsNaN(), IsNormalized(), operator=(), ResetToAdditiveIdentity(), and ResetToRefPose().
The documentation for this struct was generated from the following file:
AnimNodeBase.h