Unreal Engine 5.6 C++ API: FShaderLooseParameterBufferInfo Class Reference
FShaderLooseParameterBufferInfo Class Reference
#include "Shader.h"
Public Member Functions
FShaderLooseParameterBufferInfo ()
FShaderLooseParameterBufferInfo (uint16 InBufferIndex, uint16 InBufferSize)
LAYOUT_FIELD (TMemoryImageArray< FShaderLooseParameterInfo >, Parameters)
LAYOUT_FIELD (uint16, BaseIndex)
LAYOUT_FIELD (uint16, Size)
bool operator< (const FShaderLooseParameterBufferInfo &Rhs) const
bool operator== (const FShaderLooseParameterBufferInfo &Rhs) const
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderLooseParameterBufferInfo, RENDERCORE_API, NonVirtual)
Friends
FArchive & operator<< (FArchive &Ar, FShaderLooseParameterBufferInfo &Info)
Detailed Description
Definition at line 250 of file Shader.h.
Constructor & Destructor Documentation
FShaderLooseParameterBufferInfo() [1/2]
FShaderLooseParameterBufferInfo::FShaderLooseParameterBufferInfo () inline
Definition at line 259 of file Shader.h.
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT(), operator<(), operator<<, and operator==().
FShaderLooseParameterBufferInfo() [2/2]
FShaderLooseParameterBufferInfo::FShaderLooseParameterBufferInfo (uint16 InBufferIndex, uint16 InBufferSize) inline
Definition at line 261 of file Shader.h.
References checkf, TEXT, and TSequenceHistory< HistorySize >::Size.
Member Function Documentation
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderLooseParameterBufferInfo::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderLooseParameterBufferInfo , RENDERCORE_API , NonVirtual) private
References FShaderLooseParameterBufferInfo().
LAYOUT_FIELD() [1/3]
FShaderLooseParameterBufferInfo::LAYOUT_FIELD (TMemoryImageArray< FShaderLooseParameterInfo > , Parameters)
LAYOUT_FIELD() [2/3]
FShaderLooseParameterBufferInfo::LAYOUT_FIELD (uint16 , BaseIndex)
LAYOUT_FIELD() [3/3]
FShaderLooseParameterBufferInfo::LAYOUT_FIELD (uint16 , Size)
References TSequenceHistory< HistorySize >::Size.
operator<()
bool FShaderLooseParameterBufferInfo::operator< (const FShaderLooseParameterBufferInfo & Rhs) const inline
Definition at line 283 of file Shader.h.
References FShaderLooseParameterBufferInfo().
operator==()
bool FShaderLooseParameterBufferInfo::operator== (const FShaderLooseParameterBufferInfo & Rhs) const inline
Definition at line 276 of file Shader.h.
References FShaderLooseParameterBufferInfo(), and TSequenceHistory< HistorySize >::Size.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FShaderLooseParameterBufferInfo & Info) friend
Definition at line 268 of file Shader.h.
References FShaderLooseParameterBufferInfo(), Ar, and Info.
The documentation for this class was generated from the following file:
Shader.h