Unreal Engine 5.6 C++ API: FStructuredArchiveChildReader Class Reference
FStructuredArchiveChildReader Class Reference
FStructuredArchiveChildReader.
#include "StructuredArchiveChildReader.h"
Public Member Functions
FStructuredArchiveChildReader (const FStructuredArchiveChildReader &)=delete
FStructuredArchiveChildReader (FStructuredArchiveChildReader &&)=delete
FORCEINLINE FStructuredArchiveChildReader (FStructuredArchiveSlot InSlot)
FORCEINLINE ~FStructuredArchiveChildReader ()
FORCEINLINE FStructuredArchiveSlot GetRoot () const
FStructuredArchiveChildReader & operator= (const FStructuredArchiveChildReader &)=delete
FStructuredArchiveChildReader & operator= (FStructuredArchiveChildReader &&)=delete
Private Attributes
FStructuredArchiveFormatter * OwnedFormatter
TOptional< FStructuredArchiveSlot > Root
FStructuredArchive * StructuredArchive
Detailed Description
FStructuredArchiveChildReader.
Utility class for easily creating a structured archive that covers the data hierarchy underneath the given slot
Allows serialization code to get an archive instance for the current location, so that it can return to it later on after the master archive has potentially moved on into a different location in the file.
Definition at line 29 of file StructuredArchiveChildReader.h.
Constructor & Destructor Documentation
FStructuredArchiveChildReader() [1/3]
FORCEINLINE FStructuredArchiveChildReader::FStructuredArchiveChildReader (FStructuredArchiveSlot InSlot) explicit
Definition at line 54 of file StructuredArchiveChildReader.h.
References FORCEINLINE, FStructuredArchive::Formatter, OwnedFormatter, Root, StructuredArchive, and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by FStructuredArchiveChildReader(), FStructuredArchiveChildReader(), operator=(), and operator=().
~FStructuredArchiveChildReader()
FORCEINLINE FStructuredArchiveChildReader::~FStructuredArchiveChildReader ()
Definition at line 62 of file StructuredArchiveChildReader.h.
References FORCEINLINE, and StructuredArchive.
FStructuredArchiveChildReader() [2/3]
FStructuredArchiveChildReader::FStructuredArchiveChildReader (FStructuredArchiveChildReader &&) delete
References FStructuredArchiveChildReader().
FStructuredArchiveChildReader() [3/3]
FStructuredArchiveChildReader::FStructuredArchiveChildReader (const FStructuredArchiveChildReader &) delete
References FStructuredArchiveChildReader().
Member Function Documentation
GetRoot()
FORCEINLINE FStructuredArchiveSlot FStructuredArchiveChildReader::GetRoot () const inline
Definition at line 41 of file StructuredArchiveChildReader.h.
References FORCEINLINE, and Root.
operator=() [1/2]
FStructuredArchiveChildReader & FStructuredArchiveChildReader::operator= (const FStructuredArchiveChildReader &) delete
References FStructuredArchiveChildReader().
operator=() [2/2]
FStructuredArchiveChildReader & FStructuredArchiveChildReader::operator= (FStructuredArchiveChildReader &&) delete
References FStructuredArchiveChildReader().
Field Documentation
OwnedFormatter
FStructuredArchiveFormatter* FStructuredArchiveChildReader::OwnedFormatter private
Definition at line 47 of file StructuredArchiveChildReader.h.
Referenced by FStructuredArchiveChildReader().
Root
TOptional<FStructuredArchiveSlot> FStructuredArchiveChildReader::Root private
Definition at line 49 of file StructuredArchiveChildReader.h.
Referenced by FStructuredArchiveChildReader(), and GetRoot().
StructuredArchive
FStructuredArchive* FStructuredArchiveChildReader::StructuredArchive private
Definition at line 48 of file StructuredArchiveChildReader.h.
Referenced by FStructuredArchiveChildReader(), and ~FStructuredArchiveChildReader().
The documentation for this class was generated from the following file:
StructuredArchiveChildReader.h