Unreal Engine 5.6 C++ API: Metasound::Frontend::INodeClassRegistryEntry Class Reference
Metasound::Frontend::INodeClassRegistryEntry Class Reference abstract
INodeClassRegistryEntry declares the interface for a node registry entry.
#include "MetasoundFrontendNodeClassRegistry.h"
Public Member Functions
virtual ~INodeClassRegistryEntry ()=default
virtual METASOUNDFRONTEND_API TInstancedStruct< FMetaSoundFrontendNodeConfiguration > CreateFrontendNodeConfiguration () const
Optionally create the node extension associated with the node.
virtual METASOUNDFRONTEND_API TUniquePtr< INode > CreateNode (FNodeData) const
Create a node given FNodeData.
virtual const FNodeClassInfo & GetClassInfo () const =0
Return FNodeClassInfo for the node class.
virtual FVertexInterface GetDefaultVertexInterface () const =0
virtual const FMetasoundFrontendClass & GetFrontendClass () const =0
Return a FMetasoundFrontendClass which describes the node.
virtual const TSet< FMetasoundFrontendVersion > * GetImplementedInterfaces () const =0
Returns set of implemented interface versions.
UE_DEPRECATED (5.6, "Node Class Registration Entries do not need to be cloned.") virtual TUniquePtr< INodeClassRegistryEntry > Clone() const
Clone this registry entry.
UE_DEPRECATED (5.6, "Node class registry no longer tracks nature of implementation (i.e. if was registered " "from an asset or c++. Use the MetaSoundAssetManager to determine if the class has been defined within an asset(s).") virtual bool IsNative() const
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(const FNodeInitData &) const =0
Create a node given FNodeInitData.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultLiteralNodeConstructorParams &&) const
Create a node given FDefaultLiteralNodeConstructorParams.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultNamedVertexNodeConstructorParams &&) const
Create a node given FDefaultNamedVertexNodeConstructorParams.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultNamedVertexWithLiteralNodeConstructorParams &&) const
Create a node given FDefaultNamedVertexWithLiteralNodeConstructorParams.
Detailed Description
INodeClassRegistryEntry declares the interface for a node registry entry.
Each node class in the registry must satisfy this interface.
Definition at line 38 of file MetasoundFrontendNodeClassRegistry.h.
Constructor & Destructor Documentation
~INodeClassRegistryEntry()
virtual Metasound::Frontend::INodeClassRegistryEntry::~INodeClassRegistryEntry () virtual default
Member Function Documentation
CreateFrontendNodeConfiguration()
virtual METASOUNDFRONTEND_API TInstancedStruct< FMetaSoundFrontendNodeConfiguration > Metasound::Frontend::INodeClassRegistryEntry::CreateFrontendNodeConfiguration () const virtual
Optionally create the node extension associated with the node.
Reimplemented in Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase, Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntry< NodeType, ConfigurationType >, and Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntry< NodeType, void >.
References UE_API.
CreateNode()
virtual METASOUNDFRONTEND_API TUniquePtr< INode > Metasound::Frontend::INodeClassRegistryEntry::CreateNode (FNodeData) const virtual
Create a node given FNodeData.
If a node can be created with FNodeData, this function should return a valid node pointer.
Reimplemented in Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase, Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >, and Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< NodeType >.
References CreateNode(), and UE_API.
Referenced by CreateNode(), Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::GetFrontendClass(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
GetClassInfo()
virtual const FNodeClassInfo & Metasound::Frontend::INodeClassRegistryEntry::GetClassInfo () const pure virtual
Return FNodeClassInfo for the node class.
Implementations of method should avoid any expensive operations (e.g. loading from disk, allocating memory) as this method is called frequently when querying nodes.
Implemented in Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase.
GetDefaultVertexInterface()
virtual FVertexInterface Metasound::Frontend::INodeClassRegistryEntry::GetDefaultVertexInterface () const pure virtual
Implemented in Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase.
GetFrontendClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::INodeClassRegistryEntry::GetFrontendClass () const pure virtual
Return a FMetasoundFrontendClass which describes the node.
Implemented in Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase.
References GetFrontendClass().
Referenced by GetFrontendClass().
GetImplementedInterfaces()
virtual const TSet< FMetasoundFrontendVersion > * Metasound::Frontend::INodeClassRegistryEntry::GetImplementedInterfaces () const pure virtual
Returns set of implemented interface versions.
Returns nullptr if node class implementation does not support interface implementation.
Implemented in Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase.
UE_DEPRECATED() [1/6]
Metasound::Frontend::INodeClassRegistryEntry::UE_DEPRECATED (5. 6, "Node Class Registration Entries do not need to be cloned.") const inline
Clone this registry entry.
Definition at line 94 of file MetasoundFrontendNodeClassRegistry.h.
References UE_DEPRECATED().
UE_DEPRECATED() [2/6]
Metasound::Frontend::INodeClassRegistryEntry::UE_DEPRECATED (5. 6) const inline
Definition at line 105 of file MetasoundFrontendNodeClassRegistry.h.
UE_DEPRECATED() [3/6]
Metasound::Frontend::INodeClassRegistryEntry::UE_DEPRECATED (5. 6, "Node classes should be constructed with FNodeData") const & pure virtual
Create a node given FNodeInitData.
If a node can be created with FNodeInitData, this function should return a valid node pointer.
Implemented in Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase.
References CreateNode().
UE_DEPRECATED() [4/6]
Metasound::Frontend::INodeClassRegistryEntry::UE_DEPRECATED (5. 6, "Node classes should be constructed with FNodeData") const && inline
Create a node given FDefaultLiteralNodeConstructorParams.
If a node can be created with FDefaultLiteralNodeConstructorParams, this function should return a valid node pointer.
Definition at line 72 of file MetasoundFrontendNodeClassRegistry.h.
References CreateNode().
UE_DEPRECATED() [5/6]
Metasound::Frontend::INodeClassRegistryEntry::UE_DEPRECATED (5. 6, "Node classes should be constructed with FNodeData") const && inline
Create a node given FDefaultNamedVertexNodeConstructorParams.
If a node can be created with FDefaultNamedVertexNodeConstructorParams, this function should return a valid node pointer.
Definition at line 56 of file MetasoundFrontendNodeClassRegistry.h.
References CreateNode().
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [6/6]
Metasound::Frontend::INodeClassRegistryEntry::UE_DEPRECATED (5. 6, "Node classes should be constructed with FNodeData") const && inline
Create a node given FDefaultNamedVertexWithLiteralNodeConstructorParams.
If a node can be created with FDefaultNamedVertexWithLiteralNodeConstructorParams, this function should return a valid node pointer.
Definition at line 64 of file MetasoundFrontendNodeClassRegistry.h.
References CreateNode().
The documentation for this class was generated from the following file:
MetasoundFrontendNodeClassRegistry.h