Unreal Engine 5.6 C++ API: UE::Geometry::TMeshAABBTree3< TriangleMeshType > Class Template Reference
UE::Geometry::TMeshAABBTree3< TriangleMeshType > Class Template Reference
#include "MeshAABBTree3.h"
Data Structures
struct FBoxesSet
class FTreeTraversal
Public Types
using GetSplitAxisFunc = TUniqueFunction<int(int Depth, const FAxisAlignedBox3d& Box)>
using MeshType = TriangleMeshType
Public Member Functions
TMeshAABBTree3 ()
TMeshAABBTree3 (const TriangleMeshType *SourceMesh, bool bAutoBuild=true)
double box_box_distsqr (int iBox, const FAxisAlignedBox3d &testBox) const
bool box_box_intersect (int IBox, const FAxisAlignedBox3d &TestBox) const
bool box_contains (int IBox, const FVector3d &P) const
template<typename RayType>
double box_ray_intersect_t (int IBox, const RayType &Ray) const
double BoxDistanceSqr (int IBox, const FVector3d &V) const
void Build ()
void Build (const TArray< int32 > &TriangleList)
void BuildTopDown (bool bSorted)
template<typename TriIndexEnumerable>
void BuildTopDown (bool bSorted, TriIndexEnumerable TriangleList, int32 NumTriangles)
void BuildTopDown (TArray< int > &Triangles, TArray< FVector3d > &Centers, int32 NumTriangles)
virtual void DoTraversal (FTreeTraversal &Traversal, const FQueryOptions &Options=FQueryOptions()) const
Hierarchically descend through the tree Nodes, calling the FTreeTraversal functions at each level.
int find_any_intersection (int iBox, const FTriangle3d &Triangle, const FAxisAlignedBox3d &triBounds, TFunctionRef< bool(const FTriangle3d &A, const FTriangle3d &B)> TriangleIntersectionTest, const FQueryOptions &Options) const
bool find_any_intersection (int iBox, const TMeshAABBTree3 &OtherTree, const TFunction< FVector3d(const FVector3d &)> &TransformF, int oBox, int depth, TFunctionRef< bool(const FTriangle3d &A, const FTriangle3d &B)> TriangleIntersectionTest, const FQueryOptions &Options, const FQueryOptions &OtherTreeOptions) const
void find_intersections (int iBox, const TMeshAABBTree3 &OtherTree, const TFunction< FVector3d(const FVector3d &)> &TransformF, int oBox, int depth, MeshIntersection::FIntersectionsQueryResult &result, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions &Options, const FQueryOptions &OtherTreeOptions) const
void find_nearest_triangles (int iBox, TMeshAABBTree3 &OtherTree, const TFunction< FVector3d(const FVector3d &)> &TransformF, int oBox, int depth, double &nearest_sqr, FIndex2i &nearest_pair, const FQueryOptions &Options, const FQueryOptions &OtherTreeOptions) const
bool find_self_intersections (MeshIntersection::FIntersectionsQueryResult *Result, bool bIgnoreTopoConnected, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions &Options) const
bool find_self_intersections_acrossboxes (int Box1, int Box2, MeshIntersection::FIntersectionsQueryResult *Result, bool bIgnoreTopoConnected, int depth, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions &Options) const
bool find_tri_tri_intersections (int TID_A, int IdxRangeStart, int IdxRangeEnd, MeshIntersection::FIntersectionsQueryResult *Result, bool bIgnoreTopoConnected, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions &Options) const
virtual bool FindAllHitTriangles (const FRay3d &Ray, TArray< MeshIntersection::FHitIntersectionResult > &OutHits, const FQueryOptions &Options=FQueryOptions()) const override
Find all triangles intersected by the given ray sorted by distance.
bool FindAllHitTriangles (const FWatertightRay3d &Ray, TArray< MeshIntersection::FHitIntersectionResult > &OutHits, const FQueryOptions &Options=FQueryOptions()) const
virtual MeshIntersection::FIntersectionsQueryResult FindAllIntersections (const TMeshAABBTree3 &OtherTree, const TFunction< FVector3d(const FVector3d &)> &TransformF=nullptr, const FQueryOptions &Options=FQueryOptions(), const FQueryOptions &OtherTreeOptions=FQueryOptions(), TFunction< bool(FIntrTriangle3Triangle3d &)> IntersectionFn=nullptr) const
Compute all intersections between two meshes.
virtual MeshIntersection::FIntersectionsQueryResult FindAllSelfIntersections (bool bIgnoreTopoConnected=true, const FQueryOptions &Options=FQueryOptions(), TFunction< bool(FIntrTriangle3Triangle3d &)> IntersectionFn=nullptr) const
Compute self intersections on our mesh.
virtual int FindNearestHitTriangle (const FRay3d &Ray, const FQueryOptions &Options=FQueryOptions()) const override
virtual bool FindNearestHitTriangle (const FRay3d &Ray, double &NearestT, int &TID, const FQueryOptions &Options=FQueryOptions()) const override
Find nearest triangle from the given ray.
virtual bool FindNearestHitTriangle (const FRay3d &Ray, double &NearestT, int &TID, FVector3d &BaryCoords, const FQueryOptions &Options=FQueryOptions()) const override
Find nearest triangle from the given ray.
bool FindNearestHitTriangle (const FWatertightRay3d &Ray, double &NearestT, int &TID, FVector3d &BaryCoords, const FQueryOptions &Options=FQueryOptions()) const
virtual FVector3d FindNearestPoint (const FVector3d &Point, const FQueryOptions &Options=FQueryOptions()) const
Convenience function that calls FindNearestTriangle and then finds nearest point.
virtual int FindNearestTriangle (const FVector3d &P, double &NearestDistSqr, const FQueryOptions &Options=FQueryOptions()) const override
Find the triangle closest to P, and distance to it, within distance MaxDist, or return InvalidID Use MeshQueries.TriangleDistance() to get more information.
virtual FIndex2i FindNearestTriangles (TMeshAABBTree3 &OtherTree, const TFunction< FVector3d(const FVector3d &)> &TransformF, double &Distance, const FQueryOptions &Options=FQueryOptions(), const FQueryOptions &OtherTreeOptions=FQueryOptions())
Find nearest pair of triangles on this tree with OtherTree, within Options.MaxDistance.
virtual int FindNearestVertex (const FVector3d &P, double &NearestDistSqr, double MaxDist=TNumericLimits< double >::Max(), const FQueryOptions &Options=FQueryOptions())
Find the Vertex closest to P, and distance to it, within distance MaxDist, or return InvalidID.
FAxisAlignedBox3d GetBoundingBox () const
Get the overall bounding box of the whole tree.
const TriangleMeshType * GetMesh () const
virtual bool IsInside (const FVector3d &P) const override
bool IsValid (bool bAllowUnsafeModifiedMeshQueries) const
virtual bool IsWithinDistanceSquared (const FVector3d &Point, double ThresholdDistanceSqr, int &OutTriangleID, const FQueryOptions &Options=FQueryOptions()) const
Test whether there is any triangle closer than sqrt(ThresholdDistanceSqr) to Point Note that FQueryOptions::MaxDistance is ignored by this query, as ThresholdDistanceSqr controls the query distance instead.
void SetBuildOptions (int32 MaxBoxTriCount, GetSplitAxisFunc &&GetSplitAxisIn=MakeDefaultSplitAxisFunc())
void SetMesh (const TriangleMeshType *SourceMesh, bool bAutoBuild=true)
void SetTolerance (double Tolerance)
Sets the box intersection tolerance TODO: move into the IMeshSpatial::FQueryOptions and delete this function.
int SplitTriSetMidpoint (TArray< int > &Triangles, TArray< FVector3d > &Centers, int IStart, int ICount, int Depth, int MinTriCount, FBoxesSet &Tris, FBoxesSet &Nodes, FAxisAlignedBox3d &Box)
virtual bool SupportsNearestTriangle () const override
virtual bool SupportsPointContainment () const override
virtual bool SupportsTriangleRayIntersection () const override
virtual bool TestAnyHitTriangle (const FRay3d &Ray, const FQueryOptions &Options=FQueryOptions()) const
void TestCoverage ()
virtual bool TestIntersection (const FTriangle3d &Triangle, const FQueryOptions &Options=FQueryOptions()) const
Returns true if triangle intersects any triangle of our mesh.
virtual bool TestIntersection (const TMeshAABBTree3 &OtherTree, const TFunction< FVector3d(const FVector3d &)> &TransformF=nullptr, const FQueryOptions &Options=FQueryOptions(), const FQueryOptions &OtherTreeOptions=FQueryOptions()) const
Returns true if there is any intersection between our mesh and 'other' mesh.
virtual bool TestIntersection (const TriangleMeshType *TestMesh, FAxisAlignedBox3d TestMeshBounds=FAxisAlignedBox3d::Empty(), const TFunction< FVector3d(const FVector3d &)> &TransformF=nullptr, const FQueryOptions &Options=FQueryOptions()) const
return true if any triangle of TestMesh intersects with our tree.
virtual bool TestSelfIntersection (bool bIgnoreTopoConnected=true, const FQueryOptions &Options=FQueryOptions()) const
double TotalVolume ()
Total sum of volumes of all boxes in the tree.
Public Member Functions inherited from UE::Geometry::IMeshSpatial
virtual ~IMeshSpatial ()=default
Public Member Functions inherited from UE::Geometry::ISpatial
virtual ~ISpatial ()=default
Static Public Member Functions
static void AddTriTriIntersectionResult (const FIntrTriangle3Triangle3d &Intr, int TID_A, int TID_B, MeshIntersection::FIntersectionsQueryResult &Result)
Helper to add a triangle-triangle intersection result from to a intersection result struct.
static bool TriangleIntersection (FIntrTriangle3Triangle3d &Intr)
Standard tri tri intersection test (with computing intersection geometry)
static bool TriangleIntersectionFilter (const FTriangle3d &A, const FTriangle3d &B)
Standard tri tri intersection test (without computing intersection geometry)
Data Fields
TDynamicVector< FVector3d > BoxCenters
TDynamicVector< FVector3d > BoxExtents
TDynamicVector< int > BoxToIndex
TDynamicVector< int > IndexList
int RootIndex = -1
int TrianglesEnd = -1
Static Public Attributes
static constexpr double DOUBLE_MAX = TNumericLimits<double>::Max()
Protected Member Functions
template<bool bEarlyStop = false>
bool find_nearest_tri (int IBox, const FVector3d &P, double &NearestDistSqr, int &TID, const FQueryOptions &Options) const
void find_nearest_vertex (int IBox, const FVector3d &P, double &NearestDistSqr, int &NearestVertexID, const FQueryOptions &Options)
template<typename RayType = FRay3d>
void FindHitTriangle (int IBox, const RayType &Ray, double &NearestT, int &TID, FVector3d &BaryCoords, const FQueryOptions &Options=FQueryOptions()) const
template<typename RayType = FRay3d>
void FindHitTriangles (int IBox, const RayType &Ray, TArray< MeshIntersection::FHitIntersectionResult > &Intersections, const FQueryOptions &Options=FQueryOptions()) const
FAxisAlignedBox3d GetBox (int IBox) const
FAxisAlignedBox3d GetBox (int iBox, const TFunction< FVector3d(const FVector3d &)> &TransformF) const
FAxisAlignedBox3d GetBoxEps (int IBox, double Epsilon=FMathd::ZeroTolerance) const
bool TestAnyHitTriangle (int IBox, const FRay3d &Ray, int32 &HitTIDOut, double MaxDistance, const FQueryOptions &Options=FQueryOptions()) const
virtual void TreeTraversalImpl (int IBox, int Depth, FTreeTraversal &Traversal, const FQueryOptions &Options) const
Static Protected Member Functions
static GetSplitAxisFunc MakeDefaultSplitAxisFunc ()
Protected Attributes
double BoxEps = FMathd::ZeroTolerance
GetSplitAxisFunc GetSplitAxis = MakeDefaultSplitAxisFunc()
const TriangleMeshType * Mesh
uint64 MeshChangeStamp = 0
int TopDownLeafMaxTriCount = 3
Private Member Functions
void debug_check_child_tri_distances (int IBox, const FVector3d &P)
void debug_check_child_tris_in_box (int IBox)
template<typename RayType>
bool FindAllHitTrianglesImpl (const RayType &Ray, TArray< MeshIntersection::FHitIntersectionResult > &OutHits, const FQueryOptions &Options=FQueryOptions()) const
template<typename RayType>
bool FindNearestHitTriangleImpl (const RayType &Ray, double &NearestT, int &TID, FVector3d &BaryCoords, const FQueryOptions &Options=FQueryOptions()) const
void test_coverage (TArray< int > &tri_counts, TArray< int > &parent_indices, int IBox)
Friends
class TFastWindingTree< TriangleMeshType >
Detailed Description
template<class TriangleMeshType>
class UE::Geometry::TMeshAABBTree3< TriangleMeshType >
Definition at line 60 of file MeshAABBTree3.h.
Member Typedef Documentation
GetSplitAxisFunc
template<class TriangleMeshType> using UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetSplitAxisFunc = TUniqueFunction<int(int Depth, const FAxisAlignedBox3d& Box)>
Definition at line 66 of file MeshAABBTree3.h.
MeshType
template<class TriangleMeshType> using UE::Geometry::TMeshAABBTree3< TriangleMeshType >::MeshType = TriangleMeshType
Definition at line 65 of file MeshAABBTree3.h.
Constructor & Destructor Documentation
TMeshAABBTree3() [1/2]
template<class TriangleMeshType> UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TMeshAABBTree3 () inline
Definition at line 86 of file MeshAABBTree3.h.
TMeshAABBTree3() [2/2]
template<class TriangleMeshType> UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TMeshAABBTree3 (const TriangleMeshType * SourceMesh, bool bAutoBuild = true) inline
Definition at line 91 of file MeshAABBTree3.h.
Member Function Documentation
AddTriTriIntersectionResult()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::AddTriTriIntersectionResult (const FIntrTriangle3Triangle3d & Intr, int TID_A, int TID_B, MeshIntersection::FIntersectionsQueryResult & Result) inline static
Helper to add a triangle-triangle intersection result from to a intersection result struct.
Definition at line 2063 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_tri_tri_intersections().
box_box_distsqr()
template<class TriangleMeshType> double UE::Geometry::TMeshAABBTree3< TriangleMeshType >::box_box_distsqr (int iBox, const FAxisAlignedBox3d & testBox) const inline
Definition at line 1618 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
box_box_intersect()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::box_box_intersect (int IBox, const FAxisAlignedBox3d & TestBox) const inline
Definition at line 1191 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections_acrossboxes(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection().
box_contains()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::box_contains (int IBox, const FVector3d & P) const inline
Definition at line 1167 of file MeshAABBTree3.h.
box_ray_intersect_t()
template<class TriangleMeshType> template<typename RayType> double UE::Geometry::TMeshAABBTree3< TriangleMeshType >::box_ray_intersect_t (int IBox, const RayType & Ray) const inline
Definition at line 1174 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle().
BoxDistanceSqr()
template<class TriangleMeshType> double UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BoxDistanceSqr (int IBox, const FVector3d & V) const inline
Definition at line 1155 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::debug_check_child_tri_distances(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_tri(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_vertex().
Build() [1/2]
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::Build () inline
Definition at line 136 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeSecondPass(), UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SetMesh().
Build() [2/2]
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::Build (const TArray< int32 > & TriangleList) inline
Definition at line 142 of file MeshAABBTree3.h.
BuildTopDown() [1/3]
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BuildTopDown (bool bSorted) inline
Definition at line 1241 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::Build(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::Build(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown().
BuildTopDown() [2/3]
template<class TriangleMeshType> template<typename TriIndexEnumerable> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BuildTopDown (bool bSorted, TriIndexEnumerable TriangleList, int32 NumTriangles) inline
Definition at line 1271 of file MeshAABBTree3.h.
BuildTopDown() [3/3]
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BuildTopDown (TArray< int > & Triangles, TArray< FVector3d > & Centers, int32 NumTriangles) inline
Definition at line 1300 of file MeshAABBTree3.h.
debug_check_child_tri_distances()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::debug_check_child_tri_distances (int IBox, const FVector3d & P) inline private
Definition at line 2351 of file MeshAABBTree3.h.
debug_check_child_tris_in_box()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::debug_check_child_tris_in_box (int IBox) inline private
Definition at line 2369 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::test_coverage().
DoTraversal()
template<class TriangleMeshType> virtual void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::DoTraversal (FTreeTraversal & Traversal, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Hierarchically descend through the tree Nodes, calling the FTreeTraversal functions at each level.
Definition at line 845 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TotalVolume().
find_any_intersection() [1/2]
template<class TriangleMeshType> int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_any_intersection (int iBox, const FTriangle3d & Triangle, const FAxisAlignedBox3d & triBounds, TFunctionRef< bool(const FTriangle3d &A, const FTriangle3d &B)> TriangleIntersectionTest, const FQueryOptions & Options) const inline
Definition at line 1656 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection().
find_any_intersection() [2/2]
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_any_intersection (int iBox, const TMeshAABBTree3< TriangleMeshType > & OtherTree, const TFunction< FVector3d(const FVector3d &)> & TransformF, int oBox, int depth, TFunctionRef< bool(const FTriangle3d &A, const FTriangle3d &B)> TriangleIntersectionTest, const FQueryOptions & Options, const FQueryOptions & OtherTreeOptions) const inline
Definition at line 1715 of file MeshAABBTree3.h.
find_intersections()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_intersections (int iBox, const TMeshAABBTree3< TriangleMeshType > & OtherTree, const TFunction< FVector3d(const FVector3d &)> & TransformF, int oBox, int depth, MeshIntersection::FIntersectionsQueryResult & result, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions & Options, const FQueryOptions & OtherTreeOptions) const inline
Definition at line 2122 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllIntersections().
find_nearest_tri()
template<class TriangleMeshType> template<bool bEarlyStop = false> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_nearest_tri (int IBox, const FVector3d & P, double & NearestDistSqr, int & TID, const FQueryOptions & Options) const inline protected
Definition at line 230 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_tri(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangle(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::IsWithinDistanceSquared().
find_nearest_triangles()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_nearest_triangles (int iBox, TMeshAABBTree3< TriangleMeshType > & OtherTree, const TFunction< FVector3d(const FVector3d &)> & TransformF, int oBox, int depth, double & nearest_sqr, FIndex2i & nearest_pair, const FQueryOptions & Options, const FQueryOptions & OtherTreeOptions) const inline
Definition at line 1452 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangles().
find_nearest_vertex()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_nearest_vertex (int IBox, const FVector3d & P, double & NearestDistSqr, int & NearestVertexID, const FQueryOptions & Options) inline protected
Definition at line 344 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_vertex(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestVertex().
find_self_intersections()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_self_intersections (MeshIntersection::FIntersectionsQueryResult * Result, bool bIgnoreTopoConnected, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions & Options) const inline
Definition at line 2093 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllSelfIntersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestSelfIntersection().
find_self_intersections_acrossboxes()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_self_intersections_acrossboxes (int Box1, int Box2, MeshIntersection::FIntersectionsQueryResult * Result, bool bIgnoreTopoConnected, int depth, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions & Options) const inline
Definition at line 1855 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections_acrossboxes().
find_tri_tri_intersections()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::find_tri_tri_intersections (int TID_A, int IdxRangeStart, int IdxRangeEnd, MeshIntersection::FIntersectionsQueryResult * Result, bool bIgnoreTopoConnected, TFunctionRef< bool(FIntrTriangle3Triangle3d &)> IntersectFn, const FQueryOptions & Options) const inline
Definition at line 1991 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections_acrossboxes().
FindAllHitTriangles() [1/2]
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindAllHitTriangles (const FRay3d & Ray, TArray< MeshIntersection::FHitIntersectionResult > & OutHits, const FQueryOptions & Options = FQueryOptions()) const inline override virtual
Find all triangles intersected by the given ray sorted by distance.
Parameters
Ray query ray
OutHits returned-by-reference hit infos sorted by distance
Options Query options (ex. max distance)
Returns
true if hit, false if no hit found
Implements UE::Geometry::IMeshSpatial.
Definition at line 455 of file MeshAABBTree3.h.
FindAllHitTriangles() [2/2]
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindAllHitTriangles (const FWatertightRay3d & Ray, TArray< MeshIntersection::FHitIntersectionResult > & OutHits, const FQueryOptions & Options = FQueryOptions()) const inline
Definition at line 462 of file MeshAABBTree3.h.
FindAllHitTrianglesImpl()
template<class TriangleMeshType> template<typename RayType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindAllHitTrianglesImpl (const RayType & Ray, TArray< MeshIntersection::FHitIntersectionResult > & OutHits, const FQueryOptions & Options = FQueryOptions()) const inline private
Definition at line 493 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTriangles(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTriangles().
FindAllIntersections()
template<class TriangleMeshType> virtual MeshIntersection::FIntersectionsQueryResult UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindAllIntersections (const TMeshAABBTree3< TriangleMeshType > & OtherTree, const TFunction< FVector3d(const FVector3d &)> & TransformF = nullptr, const FQueryOptions & Options = FQueryOptions(), const FQueryOptions & OtherTreeOptions = FQueryOptions(), TFunction< bool(FIntrTriangle3Triangle3d &)> IntersectionFn = nullptr) const inline virtual
Compute all intersections between two meshes.
TransformF argument transforms vertices of OtherTree to our tree (can be null if in same coord space) Returns pairs of intersecting triangles, which could intersect in either point or segment Currently does not return coplanar intersections.
Definition at line 1025 of file MeshAABBTree3.h.
FindAllSelfIntersections()
template<class TriangleMeshType> virtual MeshIntersection::FIntersectionsQueryResult UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindAllSelfIntersections (bool bIgnoreTopoConnected = true, const FQueryOptions & Options = FQueryOptions(), TFunction< bool(FIntrTriangle3Triangle3d &)> IntersectionFn = nullptr) const inline virtual
Compute self intersections on our mesh.
Returns pairs of intersecting triangles, which could intersect in either point or segment Currently does not return coplanar intersections.
Parameters
bIgnoreTopoConnected Ignore intersections between triangles that share a vertex (if false a lot of triangles that simply share an edge will be counted as self intersecting)
Definition at line 1059 of file MeshAABBTree3.h.
FindHitTriangle()
template<class TriangleMeshType> template<typename RayType = FRay3d> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindHitTriangle (int IBox, const RayType & Ray, double & NearestT, int & TID, FVector3d & BaryCoords, const FQueryOptions & Options = FQueryOptions()) const inline protected
Definition at line 522 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangle(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangleImpl().
FindHitTriangles()
template<class TriangleMeshType> template<typename RayType = FRay3d> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindHitTriangles (int IBox, const RayType & Ray, TArray< MeshIntersection::FHitIntersectionResult > & Intersections, const FQueryOptions & Options = FQueryOptions()) const inline protected
Definition at line 600 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTrianglesImpl(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles().
FindNearestHitTriangle() [1/4]
template<class TriangleMeshType> virtual int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestHitTriangle (const FRay3d & Ray, const FQueryOptions & Options = FQueryOptions()) const inline override virtual
Parameters
Ray query ray
Options Query options (ex. max distance)
Returns
ID of triangle intersected by ray within MaxDistance, or InvalidID if not found
Reimplemented from UE::Geometry::IMeshSpatial.
Definition at line 425 of file MeshAABBTree3.h.
FindNearestHitTriangle() [2/4]
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestHitTriangle (const FRay3d & Ray, double & NearestT, int & TID, const FQueryOptions & Options = FQueryOptions()) const inline override virtual
Find nearest triangle from the given ray.
Parameters
Ray query ray
NearestT returned-by-reference parameter of the nearest hit
TID returned-by-reference ID of triangle intersected by ray within MaxDistance, or InvalidID if not found
Options Query options (ex. max distance)
Returns
true if hit, false if no hit found
Reimplemented from UE::Geometry::IMeshSpatial.
Definition at line 435 of file MeshAABBTree3.h.
FindNearestHitTriangle() [3/4]
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestHitTriangle (const FRay3d & Ray, double & NearestT, int & TID, FVector3d & BaryCoords, const FQueryOptions & Options = FQueryOptions()) const inline override virtual
Find nearest triangle from the given ray.
Parameters
Ray query ray
NearestT returned-by-reference parameter of the nearest hit
TID returned-by-reference ID of triangle intersected by ray within MaxDistance, or InvalidID if not found
BaryCoords returned-by-reference Barycentric coordinates of the triangle intersected by ray within MaxDistance, or FVector3d::Zero if not found.
Options Query options (ex. max distance)
Returns
true if hit, false if no hit found
Implements UE::Geometry::IMeshSpatial.
Definition at line 441 of file MeshAABBTree3.h.
FindNearestHitTriangle() [4/4]
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestHitTriangle (const FWatertightRay3d & Ray, double & NearestT, int & TID, FVector3d & BaryCoords, const FQueryOptions & Options = FQueryOptions()) const inline
Definition at line 448 of file MeshAABBTree3.h.
FindNearestHitTriangleImpl()
template<class TriangleMeshType> template<typename RayType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestHitTriangleImpl (const RayType & Ray, double & NearestT, int & TID, FVector3d & BaryCoords, const FQueryOptions & Options = FQueryOptions()) const inline private
Definition at line 471 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle().
FindNearestPoint()
template<class TriangleMeshType> virtual FVector3d UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestPoint (const FVector3d & Point, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Convenience function that calls FindNearestTriangle and then finds nearest point.
Returns
nearest point to Point, or Point itself if a nearest point was not found
Definition at line 192 of file MeshAABBTree3.h.
Referenced by UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed().
FindNearestTriangle()
template<class TriangleMeshType> virtual int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestTriangle (const FVector3d & P, double & NearestDistSqr, const FQueryOptions & Options = FQueryOptions()) const inline override virtual
Find the triangle closest to P, and distance to it, within distance MaxDist, or return InvalidID Use MeshQueries.TriangleDistance() to get more information.
Implements UE::Geometry::IMeshSpatial.
Definition at line 157 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestPoint().
FindNearestTriangles()
template<class TriangleMeshType> virtual FIndex2i UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestTriangles (TMeshAABBTree3< TriangleMeshType > & OtherTree, const TFunction< FVector3d(const FVector3d &)> & TransformF, double & Distance, const FQueryOptions & Options = FQueryOptions(), const FQueryOptions & OtherTreeOptions = FQueryOptions()) inline virtual
Find nearest pair of triangles on this tree with OtherTree, within Options.MaxDistance.
TransformF transforms vertices of OtherTree into our coordinates. can be null. returns triangle-id pair (my_tri,other_tri), or FIndex2i::Invalid if not found within max_dist Use MeshQueries.TrianglesDistance() to get more information Note: Only uses MaxDistance from Options; OtherTreeOptions.MaxDistance is not used
Definition at line 796 of file MeshAABBTree3.h.
FindNearestVertex()
template<class TriangleMeshType> virtual int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::FindNearestVertex (const FVector3d & P, double & NearestDistSqr, double MaxDist = TNumericLimits<double>::Max(), const FQueryOptions & Options = FQueryOptions()) inline virtual
Find the Vertex closest to P, and distance to it, within distance MaxDist, or return InvalidID.
Definition at line 328 of file MeshAABBTree3.h.
GetBoundingBox()
template<class TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetBoundingBox () const inline
Get the overall bounding box of the whole tree.
Definition at line 176 of file MeshAABBTree3.h.
Referenced by UE::Geometry::FOccupancyGrid3::FOccupancyGrid3(), and UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeSecondPass().
GetBox() [1/2]
template<class TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetBox (int IBox) const inline protected
Definition at line 1109 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections_acrossboxes(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::GetBoundingBox(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::GetBox().
GetBox() [2/2]
template<class TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetBox (int iBox, const TFunction< FVector3d(const FVector3d &)> & TransformF) const inline protected
Definition at line 1116 of file MeshAABBTree3.h.
GetBoxEps()
template<class TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetBoxEps (int IBox, double Epsilon = FMathd::ZeroTolerance) const inline protected
Definition at line 1130 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::box_box_distsqr(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::box_box_intersect(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::box_contains(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::debug_check_child_tris_in_box(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::test_coverage().
GetMesh()
template<class TriangleMeshType> const TriangleMeshType * UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetMesh () const inline
Definition at line 107 of file MeshAABBTree3.h.
IsInside()
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::IsInside (const FVector3d & Point) const inline override virtual
Returns
true if the query point is inside the object
Implements UE::Geometry::ISpatial.
Definition at line 825 of file MeshAABBTree3.h.
IsValid()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::IsValid (bool bAllowUnsafeModifiedMeshQueries) const inline
Parameters
bAllowUnsafeModifiedMeshQueries if true, then a built tree will still be considered valid even if the mesh change stamp has been modified
Returns
true if tree is built and mesh is unchanged (identified based on change stamp)
Definition at line 116 of file MeshAABBTree3.h.
IsWithinDistanceSquared()
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::IsWithinDistanceSquared (const FVector3d & Point, double ThresholdDistanceSqr, int & OutTriangleID, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Test whether there is any triangle closer than sqrt(ThresholdDistanceSqr) to Point Note that FQueryOptions::MaxDistance is ignored by this query, as ThresholdDistanceSqr controls the query distance instead.
Parameters
OutTriangleID The ID of a triangle (not necessarily the closest) within the distance threshold, or InvalidID if none found.
Definition at line 212 of file MeshAABBTree3.h.
MakeDefaultSplitAxisFunc()
template<class TriangleMeshType> GetSplitAxisFunc UE::Geometry::TMeshAABBTree3< TriangleMeshType >::MakeDefaultSplitAxisFunc () inline static protected
Definition at line 73 of file MeshAABBTree3.h.
SetBuildOptions()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::SetBuildOptions (int32 MaxBoxTriCount, GetSplitAxisFunc && GetSplitAxisIn = MakeDefaultSplitAxisFunc()) inline
Definition at line 130 of file MeshAABBTree3.h.
SetMesh()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::SetMesh (const TriangleMeshType * SourceMesh, bool bAutoBuild = true) inline
Definition at line 96 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TMeshAABBTree3(), and UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed().
SetTolerance()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::SetTolerance (double Tolerance) inline
Sets the box intersection tolerance TODO: move into the IMeshSpatial::FQueryOptions and delete this function.
Definition at line 1150 of file MeshAABBTree3.h.
SplitTriSetMidpoint()
template<class TriangleMeshType> int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::SplitTriSetMidpoint (TArray< int > & Triangles, TArray< FVector3d > & Centers, int IStart, int ICount, int Depth, int MinTriCount, FBoxesSet & Tris, FBoxesSet & Nodes, FAxisAlignedBox3d & Box) inline
Definition at line 1349 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint().
SupportsNearestTriangle()
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::SupportsNearestTriangle () const inline override virtual
Returns
true if this object supports nearest-triangle queries
Implements UE::Geometry::IMeshSpatial.
Definition at line 148 of file MeshAABBTree3.h.
SupportsPointContainment()
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::SupportsPointContainment () const inline override virtual
Returns
true if this object supports point-containment inside/outside queries
Implements UE::Geometry::ISpatial.
Definition at line 820 of file MeshAABBTree3.h.
SupportsTriangleRayIntersection()
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::SupportsTriangleRayIntersection () const inline override virtual
Returns
true if this object supports ray-triangle intersection queries
Implements UE::Geometry::IMeshSpatial.
Definition at line 420 of file MeshAABBTree3.h.
test_coverage()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::test_coverage (TArray< int > & tri_counts, TArray< int > & parent_indices, int IBox) inline private
Definition at line 2302 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::test_coverage(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestCoverage().
TestAnyHitTriangle() [1/2]
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TestAnyHitTriangle (const FRay3d & Ray, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Returns
true if ray hits the mesh at some point (doesn't necessarily find the nearest hit).
Definition at line 681 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle().
TestAnyHitTriangle() [2/2]
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TestAnyHitTriangle (int IBox, const FRay3d & Ray, int32 & HitTIDOut, double MaxDistance, const FQueryOptions & Options = FQueryOptions()) const inline protected
Definition at line 695 of file MeshAABBTree3.h.
TestCoverage()
template<class TriangleMeshType> void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TestCoverage () inline
Definition at line 2263 of file MeshAABBTree3.h.
TestIntersection() [1/3]
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TestIntersection (const FTriangle3d & Triangle, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Returns true if triangle intersects any triangle of our mesh.
Definition at line 998 of file MeshAABBTree3.h.
TestIntersection() [2/3]
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TestIntersection (const TMeshAABBTree3< TriangleMeshType > & OtherTree, const TFunction< FVector3d(const FVector3d &)> & TransformF = nullptr, const FQueryOptions & Options = FQueryOptions(), const FQueryOptions & OtherTreeOptions = FQueryOptions()) const inline virtual
Returns true if there is any intersection between our mesh and 'other' mesh.
TransformF takes vertices of OtherTree into our tree - can be null if in same coord space
Definition at line 972 of file MeshAABBTree3.h.
TestIntersection() [3/3]
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TestIntersection (const TriangleMeshType * TestMesh, FAxisAlignedBox3d TestMeshBounds = FAxisAlignedBox3d::Empty(), const TFunction< FVector3d(const FVector3d &)> & TransformF = nullptr, const FQueryOptions & Options = FQueryOptions()) const inline virtual
return true if any triangle of TestMesh intersects with our tree.
If TestMeshBounds is not empty, only test collision if the provided bounding box intersects the root AABB box Use TransformF to transform vertices of TestMesh into space of this tree.
Definition at line 921 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection().
TestSelfIntersection()
template<class TriangleMeshType> virtual bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TestSelfIntersection (bool bIgnoreTopoConnected = true, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Definition at line 1085 of file MeshAABBTree3.h.
TotalVolume()
template<class TriangleMeshType> double UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TotalVolume () inline
Total sum of volumes of all boxes in the tree.
Mainly useful to evaluate tree quality.
Definition at line 2286 of file MeshAABBTree3.h.
TreeTraversalImpl()
template<class TriangleMeshType> virtual void UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TreeTraversalImpl (int IBox, int Depth, FTreeTraversal & Traversal, const FQueryOptions & Options) const inline protected virtual
Definition at line 860 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::debug_check_child_tri_distances(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::debug_check_child_tris_in_box(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::DoTraversal(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TreeTraversalImpl().
TriangleIntersection()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TriangleIntersection (FIntrTriangle3Triangle3d & Intr) inline static
Standard tri tri intersection test (with computing intersection geometry)
Parameters
Intr Stores intersection problem; after call, should be set with intersection result
Returns
true if triangles were intersecting
Definition at line 1639 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllIntersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllSelfIntersections().
TriangleIntersectionFilter()
template<class TriangleMeshType> bool UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TriangleIntersectionFilter (const FTriangle3d & A, const FTriangle3d & B) inline static
Standard tri tri intersection test (without computing intersection geometry)
Definition at line 1630 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestSelfIntersection().
Friends And Related Symbol Documentation
TFastWindingTree< TriangleMeshType >
template<class TriangleMeshType> friend class TFastWindingTree< TriangleMeshType > friend
Definition at line 43 of file MeshAABBTree3.h.
Field Documentation
BoxCenters
template<class TriangleMeshType> TDynamicVector<FVector3d> UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BoxCenters
Definition at line 1204 of file MeshAABBTree3.h.
BoxEps
template<class TriangleMeshType> double UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BoxEps = FMathd::ZeroTolerance protected
Definition at line 1143 of file MeshAABBTree3.h.
BoxExtents
template<class TriangleMeshType> TDynamicVector<FVector3d> UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BoxExtents
Definition at line 1205 of file MeshAABBTree3.h.
BoxToIndex
template<class TriangleMeshType> TDynamicVector<int> UE::Geometry::TMeshAABBTree3< TriangleMeshType >::BoxToIndex
Definition at line 1203 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
DOUBLE_MAX
template<class TriangleMeshType> double UE::Geometry::TMeshAABBTree3< TriangleMeshType >::DOUBLE_MAX = TNumericLimits<double>::Max() static constexpr
Definition at line 84 of file MeshAABBTree3.h.
GetSplitAxis
template<class TriangleMeshType> GetSplitAxisFunc UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetSplitAxis = MakeDefaultSplitAxisFunc() protected
Definition at line 81 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint().
IndexList
template<class TriangleMeshType> TDynamicVector<int> UE::Geometry::TMeshAABBTree3< TriangleMeshType >::IndexList
Definition at line 1217 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
Mesh
template<class TriangleMeshType> const TriangleMeshType* UE::Geometry::TMeshAABBTree3< TriangleMeshType >::Mesh protected
Definition at line 69 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
MeshChangeStamp
template<class TriangleMeshType> uint64 UE::Geometry::TMeshAABBTree3< TriangleMeshType >::MeshChangeStamp = 0 protected
Definition at line 70 of file MeshAABBTree3.h.
RootIndex
template<class TriangleMeshType> int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::RootIndex = -1
Definition at line 1223 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllIntersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangles(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection().
TopDownLeafMaxTriCount
template<class TriangleMeshType> int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TopDownLeafMaxTriCount = 3 protected
Definition at line 71 of file MeshAABBTree3.h.
TrianglesEnd
template<class TriangleMeshType> int UE::Geometry::TMeshAABBTree3< TriangleMeshType >::TrianglesEnd = -1
Definition at line 1220 of file MeshAABBTree3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
The documentation for this class was generated from the following files:
TransferBoneWeights.h
MeshAABBTree3.h