Unreal Engine 5.6 C++ API: FSlateInvalidationWidgetIndex Struct Reference
FSlateInvalidationWidgetIndex Struct Reference
Index of the special container to order widget in InvalidateRoot.
#include "SlateInvalidationWidgetIndex.h"
Public Member Functions
bool operator!= (FSlateInvalidationWidgetIndex Other) const
bool operator== (FSlateInvalidationWidgetIndex Other) const
FString ToString () const
Static Public Attributes
static const FSlateInvalidationWidgetIndex Invalid
Private Types
using IndexType = uint16
Private Member Functions
FSlateInvalidationWidgetIndex (IndexType InArray, IndexType InElement)
Private Attributes
IndexType ArrayIndex
Index of the array node in FSlateInvalidationWidgetList.
IndexType ElementIndex
Index of the element node in FSlateInvalidationWidgetList.
Friends
class FSlateInvalidationWidgetList
struct FSlateInvalidationWidgetSortOrder
Detailed Description
Index of the special container to order widget in InvalidateRoot.
See SlateInvalidationWidgetlist.
Definition at line 12 of file SlateInvalidationWidgetIndex.h.
Member Typedef Documentation
IndexType
using FSlateInvalidationWidgetIndex::IndexType = uint16 private
Definition at line 24 of file SlateInvalidationWidgetIndex.h.
Constructor & Destructor Documentation
FSlateInvalidationWidgetIndex()
FSlateInvalidationWidgetIndex::FSlateInvalidationWidgetIndex (IndexType InArray, IndexType InElement) inline private
Definition at line 26 of file SlateInvalidationWidgetIndex.h.
References ArrayIndex, and ElementIndex.
Referenced by operator!=(), and operator==().
Member Function Documentation
operator!=()
bool FSlateInvalidationWidgetIndex::operator!= (FSlateInvalidationWidgetIndex Other) const inline
Definition at line 20 of file SlateInvalidationWidgetIndex.h.
References FSlateInvalidationWidgetIndex(), ArrayIndex, ElementIndex, and Other.
operator==()
bool FSlateInvalidationWidgetIndex::operator== (FSlateInvalidationWidgetIndex Other) const inline
Definition at line 19 of file SlateInvalidationWidgetIndex.h.
References FSlateInvalidationWidgetIndex(), ArrayIndex, ElementIndex, and Other.
ToString()
FString FSlateInvalidationWidgetIndex::ToString () const inline
Definition at line 21 of file SlateInvalidationWidgetIndex.h.
References ArrayIndex, ElementIndex, and TEXT.
Friends And Related Symbol Documentation
FSlateInvalidationWidgetList
friend class FSlateInvalidationWidgetList friend
Definition at line 14 of file SlateInvalidationWidgetIndex.h.
References FSlateInvalidationWidgetList.
Referenced by FSlateInvalidationWidgetList.
FSlateInvalidationWidgetSortOrder
friend struct FSlateInvalidationWidgetSortOrder friend
Definition at line 15 of file SlateInvalidationWidgetIndex.h.
References FSlateInvalidationWidgetSortOrder.
Referenced by FSlateInvalidationWidgetSortOrder.
Field Documentation
ArrayIndex
IndexType FSlateInvalidationWidgetIndex::ArrayIndex private
Index of the array node in FSlateInvalidationWidgetList.
Definition at line 29 of file SlateInvalidationWidgetIndex.h.
Referenced by FSlateInvalidationWidgetIndex(), operator!=(), operator==(), and ToString().
ElementIndex
IndexType FSlateInvalidationWidgetIndex::ElementIndex private
Index of the element node in FSlateInvalidationWidgetList.
Definition at line 31 of file SlateInvalidationWidgetIndex.h.
Referenced by FSlateInvalidationWidgetIndex(), operator!=(), operator==(), and ToString().
Invalid
const FSlateInvalidationWidgetIndex FSlateInvalidationWidgetIndex::Invalid static
Definition at line 18 of file SlateInvalidationWidgetIndex.h.
The documentation for this struct was generated from the following file:
SlateInvalidationWidgetIndex.h