Unreal Engine 5.6 C++ API: FBlueprintObjectsBeingDebuggedIterator Struct Reference
FBlueprintObjectsBeingDebuggedIterator Struct Reference
#include "KismetDebugUtilities.h"
Public Member Functions
UNREALED_API FBlueprintObjectsBeingDebuggedIterator (UBlueprint *InBlueprint)
Element access
UBlueprint * Blueprint
UNREALED_API UObject * operator* () const
UNREALED_API UObject * operator-> () const
UNREALED_API FBlueprintObjectsBeingDebuggedIterator & operator++ ()
Advances iterator to the next element in the container.
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator has not reached the last element.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
UNREALED_API bool IsValid () const
Detailed Description
Definition at line 164 of file KismetDebugUtilities.h.
Constructor & Destructor Documentation
FBlueprintObjectsBeingDebuggedIterator()
UNREALED_API FBlueprintObjectsBeingDebuggedIterator::FBlueprintObjectsBeingDebuggedIterator (UBlueprint * InBlueprint)
Referenced by operator++().
Member Function Documentation
IsValid()
UNREALED_API bool FBlueprintObjectsBeingDebuggedIterator::IsValid () const private
Referenced by operator bool().
operator bool()
FORCEINLINE FBlueprintObjectsBeingDebuggedIterator::operator bool () const inline explicit
conversion to "bool" returning true if the iterator has not reached the last element.
Definition at line 179 of file KismetDebugUtilities.h.
References FORCEINLINE, and IsValid().
operator!()
FORCEINLINE bool FBlueprintObjectsBeingDebuggedIterator::operator! () const inline
inverse of the "bool" operator
Definition at line 184 of file KismetDebugUtilities.h.
References bool, and FORCEINLINE.
operator*()
UNREALED_API UObject * FBlueprintObjectsBeingDebuggedIterator::operator* () const
operator++()
UNREALED_API FBlueprintObjectsBeingDebuggedIterator & FBlueprintObjectsBeingDebuggedIterator::operator++ ()
Advances iterator to the next element in the container.
References FBlueprintObjectsBeingDebuggedIterator().
operator->()
UNREALED_API UObject * FBlueprintObjectsBeingDebuggedIterator::operator-> () const
Field Documentation
Blueprint
UBlueprint* FBlueprintObjectsBeingDebuggedIterator::Blueprint private
Definition at line 190 of file KismetDebugUtilities.h.
The documentation for this struct was generated from the following file:
KismetDebugUtilities.h