Unreal Engine 5.6 C++ API: FSlateRenderer::FScopedAcquireDrawBuffer Struct Reference
FSlateRenderer::FScopedAcquireDrawBuffer Struct Reference
Acquire the draw buffer and release it at the end of the scope.
#include "SlateRenderer.h"
Public Member Functions
FScopedAcquireDrawBuffer (const FScopedAcquireDrawBuffer &)=delete
FScopedAcquireDrawBuffer (FSlateRenderer &InSlateRenderer)
~FScopedAcquireDrawBuffer ()
FSlateDrawBuffer & GetDrawBuffer ()
FScopedAcquireDrawBuffer & operator= (const FScopedAcquireDrawBuffer &)=delete
Private Attributes
FSlateDrawBuffer & DrawBuffer
FSlateRenderer & SlateRenderer
Detailed Description
Acquire the draw buffer and release it at the end of the scope.
Definition at line 184 of file SlateRenderer.h.
Constructor & Destructor Documentation
FScopedAcquireDrawBuffer() [1/2]
FSlateRenderer::FScopedAcquireDrawBuffer::FScopedAcquireDrawBuffer (FSlateRenderer & InSlateRenderer) inline
Definition at line 186 of file SlateRenderer.h.
References FSlateRenderer::FSlateRenderer(), FSlateRenderer::AcquireDrawBuffer(), DrawBuffer, and SlateRenderer.
Referenced by FScopedAcquireDrawBuffer(), and operator=().
~FScopedAcquireDrawBuffer()
FSlateRenderer::FScopedAcquireDrawBuffer::~FScopedAcquireDrawBuffer () inline
Definition at line 191 of file SlateRenderer.h.
References DrawBuffer, and SlateRenderer.
FScopedAcquireDrawBuffer() [2/2]
FSlateRenderer::FScopedAcquireDrawBuffer::FScopedAcquireDrawBuffer (const FScopedAcquireDrawBuffer &) delete
References FScopedAcquireDrawBuffer().
Member Function Documentation
GetDrawBuffer()
FSlateDrawBuffer & FSlateRenderer::FScopedAcquireDrawBuffer::GetDrawBuffer () inline
Definition at line 198 of file SlateRenderer.h.
References DrawBuffer.
operator=()
FScopedAcquireDrawBuffer & FSlateRenderer::FScopedAcquireDrawBuffer::operator= (const FScopedAcquireDrawBuffer &) delete
References FScopedAcquireDrawBuffer().
Field Documentation
DrawBuffer
FSlateDrawBuffer& FSlateRenderer::FScopedAcquireDrawBuffer::DrawBuffer private
Definition at line 205 of file SlateRenderer.h.
Referenced by FScopedAcquireDrawBuffer(), ~FScopedAcquireDrawBuffer(), and GetDrawBuffer().
SlateRenderer
FSlateRenderer& FSlateRenderer::FScopedAcquireDrawBuffer::SlateRenderer private
Definition at line 204 of file SlateRenderer.h.
Referenced by FScopedAcquireDrawBuffer(), and ~FScopedAcquireDrawBuffer().
The documentation for this struct was generated from the following file:
SlateRenderer.h