Unreal Engine 5.6 C++ API: UParticleModuleColor Class Reference
UParticleModuleColor Class Reference
#include "ParticleModuleColor.h"
Private Member Functions
virtual bool AddModuleCurvesToEditor (UInterpCurveEdSetup *EdSetup, TArray< const FCurveEdEntry * > &OutCurveEntries) override
virtual void CompileModule (struct FParticleEmitterBuildInfo &EmitterInfo) override
GENERATED_UCLASS_BODY () UPROPERTY()) FRawDistributionVector StartColor
Initial color for a particle as a function of Emitter time.
UPROPERTY() uint8 bClampAlpha void InitializeDefaults ()
If true, the alpha value will be clamped to the [0..1] range.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void SetToSensibleDefaults (UParticleEmitter *Owner) override
virtual void Spawn (const FSpawnContext &Context) override
void SpawnEx (const FSpawnContext &Context, struct FRandomStream *InRandomStream)
Extended version of spawn, allows for using a random stream for distribution value retrieval.
UPROPERTY () FRawDistributionFloat StartAlpha
Initial alpha for a particle as a function of Emitter time.
Detailed Description
Definition at line 21 of file ParticleModuleColor.h.
Member Function Documentation
AddModuleCurvesToEditor()
virtual bool UParticleModuleColor::AddModuleCurvesToEditor (UInterpCurveEdSetup * EdSetup, TArray< const FCurveEdEntry * > & OutCurveEntries) override private virtual
CompileModule()
virtual void UParticleModuleColor::CompileModule (struct FParticleEmitterBuildInfo & EmitterInfo) override private virtual
GENERATED_UCLASS_BODY()
UParticleModuleColor::GENERATED_UCLASS_BODY () private
Initial color for a particle as a function of Emitter time.
References Category, Color, meta, and UPROPERTY().
InitializeDefaults()
UPROPERTY() uint8 bClampAlpha void UParticleModuleColor::InitializeDefaults () private
If true, the alpha value will be clamped to the [0..1] range.
Initializes the default values for this property
References InitializeDefaults().
Referenced by InitializeDefaults().
PostEditChangeProperty()
virtual void UParticleModuleColor::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostInitProperties()
virtual void UParticleModuleColor::PostInitProperties () override private virtual
SetToSensibleDefaults()
virtual void UParticleModuleColor::SetToSensibleDefaults (UParticleEmitter * Owner) override private virtual
References Owner.
Spawn()
virtual void UParticleModuleColor::Spawn (const FSpawnContext & Context) override private virtual
SpawnEx()
void UParticleModuleColor::SpawnEx (const FSpawnContext & Context, struct FRandomStream * InRandomStream) private
Extended version of spawn, allows for using a random stream for distribution value retrieval.
Parameters
Owner The particle emitter instance that is spawning
Offset The offset to the modules payload data
SpawnTime The time of the spawn
InRandomStream The random stream to use for retrieving random values
UPROPERTY()
UParticleModuleColor::UPROPERTY () private
Initial alpha for a particle as a function of Emitter time.
References Category, Color, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), and UPROPERTY().
The documentation for this class was generated from the following file:
ParticleModuleColor.h