Unreal Engine 5.6 C++ API: FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType > Struct Template Reference
FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType > Struct Template Reference
#include "WorldPartitionActorDescArchive.h"
Public Types
using FDeprecateFunction = TFunction<void(DestPropertyType&, const SourcePropertyType&)>
Public Member Functions
TDeltaSerializer (DestPropertyType &InValue)
TDeltaSerializer (DestPropertyType &InValue, FDeprecateFunction InFunc)
Data Fields
FDeprecateFunction Func
DestPropertyType & Value
Friends
FArchive & operator<< (FArchive &Ar, const TDeltaSerializer< DestPropertyType, SourcePropertyType > &V)
Detailed Description
template<typename DestPropertyType, typename SourcePropertyType>
struct FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType >
Definition at line 35 of file WorldPartitionActorDescArchive.h.
Member Typedef Documentation
FDeprecateFunction
template<typename DestPropertyType, typename SourcePropertyType> using FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType >::FDeprecateFunction = TFunction<void(DestPropertyType&, const SourcePropertyType&)>
Definition at line 37 of file WorldPartitionActorDescArchive.h.
Constructor & Destructor Documentation
TDeltaSerializer() [1/2]
template<typename DestPropertyType, typename SourcePropertyType> FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType >::TDeltaSerializer (DestPropertyType & InValue) inline explicit
Definition at line 39 of file WorldPartitionActorDescArchive.h.
References Value.
Referenced by operator<<.
TDeltaSerializer() [2/2]
template<typename DestPropertyType, typename SourcePropertyType> FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType >::TDeltaSerializer (DestPropertyType & InValue, FDeprecateFunction InFunc) inline explicit
Definition at line 43 of file WorldPartitionActorDescArchive.h.
References Func, and Value.
Friends And Related Symbol Documentation
operator<<
template<typename DestPropertyType, typename SourcePropertyType> FArchive & operator<< (FArchive & Ar, const TDeltaSerializer< DestPropertyType, SourcePropertyType > & V) friend
Definition at line 48 of file WorldPartitionActorDescArchive.h.
References FActorDescArchive::FActorDescArchive(), FArchive::FArchive(), TDeltaSerializer(), FActorDescArchive::ActorDesc, Ar, FActorDescArchive::BaseDesc, FActorDescArchive::BaseDescSizeof, FActorDescArchive::bIsMissingBaseDesc, check, Func, FFortniteMainBranchObjectVersion::GUID, and Value.
Field Documentation
Func
template<typename DestPropertyType, typename SourcePropertyType> FDeprecateFunction FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType >::Func
Definition at line 118 of file WorldPartitionActorDescArchive.h.
Referenced by TDeltaSerializer(), and operator<<.
Value
template<typename DestPropertyType, typename SourcePropertyType> DestPropertyType& FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType >::Value
Definition at line 117 of file WorldPartitionActorDescArchive.h.
Referenced by TDeltaSerializer(), TDeltaSerializer(), and operator<<.
The documentation for this struct was generated from the following file:
WorldPartitionActorDescArchive.h