Unreal Engine 5.6 C++ API: MovementModifier.h File Reference
MovementModifier.h File Reference
#include "GameplayTagContainer.h"
#include "MoveLibrary/MovementUtilsTypes.h"
#include "MovementModifier.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovementModifierBase >
struct TStructOpsTypeTraits< FMovementModifierGroup >
Macros
#define MODIFIER_HANDLE_MAX UINT16_MAX
#define MODIFIER_HANDLE_TYPE uint16
#define MODIFIER_INVALID_HANDLE 0
#define UE_API MOVER_API
Functions
USTRUCT () struct FMovementModifierHandle
Handle to identify movement modifiers.
Macro Definition Documentation
MODIFIER_HANDLE_MAX
#define MODIFIER_HANDLE_MAX UINT16_MAX
Definition at line 18 of file MovementModifier.h.
MODIFIER_HANDLE_TYPE
#define MODIFIER_HANDLE_TYPE uint16
Definition at line 17 of file MovementModifier.h.
Referenced by USTRUCT().
MODIFIER_INVALID_HANDLE
#define MODIFIER_INVALID_HANDLE 0
Definition at line 19 of file MovementModifier.h.
Referenced by USTRUCT().
UE_API
#define UE_API MOVER_API
Definition at line 9 of file MovementModifier.h.
Function Documentation
USTRUCT()
USTRUCT ()
Handle to identify movement modifiers.
Movement Modifier: Used to apply changes that indirectly influence the movement simulation, without proposing or executing any movement, but still in sync with the sim.
Example usages: changing groups of settings, movement mode re-mappings, etc.
Note: Currently mover expects to only have one type of modifier active at a time. This can be fixed by extending the Matches function to check more than just type, but make sure anything used to compare is synced through the NetSerialize function.
Creates a new handle
Fired when this modifier is activated.
Fired when this modifier is deactivated.
Fired just before a movement Substep
Fired after a movement Substep
Kicks off this modifier, allowing any initialization to occur.
Ends this move, allowing any cleanup to occur.
Runtime query whether this modifier is finished and can be destroyed. The default implementation is based on DurationMs.
Used to compare modifiers and check if they are the same instance of modifiers. Doesn't need to be overridden but more specific data to match is best Note: Current default implementation only checks type and nothing else.
Used to write to a valid handle to a invalid handle Currently used to write a local handle to modifiers that were added from a rollback so they don't have a handle yet This is done to avoid queueing a modifier again as a local client applies potential input
Check modifier for a gameplay tag.
Parameters
TagToFind Tag to check on the Mover systems
bExactMatch If true, the tag has to be exactly present, if false then TagToFind will include it's parent tags while matching
Returns
True if the TagToFind was found
Modifier handle local to this client or server instance. Used to cancel or query for a active/queued modifier.
Serialize all modifiers and their states for this group
Copy operator - deep copy so it can be used for archiving/saving off moves
Comparison operator - needs matching modifier along with identical states in those structs
Comparison operator
Exposes references to GC system
Get a simplified string representation of this group. Typically for debugging.
Const access to active moves
Const access to queued moves
Movement modifiers that are currently active in this group
Movement modifiers that are queued to become active next sim frame
Helper function for serializing array of movement modifiers
Definition at line 24 of file MovementModifier.h.
References BlueprintType, GENERATED_BODY, Handle, IsValid(), MODIFIER_HANDLE_TYPE, MODIFIER_INVALID_HANDLE, operator!=(), operator==(), Other, TEXT, ToString(), and UE_API.