Unreal Engine 5.6 C++ API: IDetailTreeNode Class Reference
IDetailTreeNode Class Reference abstract
#include "IDetailTreeNode.h"
Public Member Functions
virtual ~IDetailTreeNode ()
virtual FNodeWidgets CreateNodeWidgets () const =0
Creates the slate widgets for this row.
virtual TSharedPtr< IPropertyHandle > CreatePropertyHandle () const =0
Creates a handle to the property on this row if the row represents a property.
virtual void GetChildren (TArray< TSharedRef< IDetailTreeNode > > &OutChildren, const bool &bInIgnoreVisibility=false)=0
Gets the children of this tree node
Note: Customizations can determine the visibility of children.
virtual void GetFilterStrings (TArray< FString > &OutFilterStrings) const =0
Gets the filter strings for this node in the tree.
virtual bool GetInitiallyCollapsed () const =0
Gets if this node should be initially collapsed by default.
virtual TSharedPtr< class IDetailsView > GetNodeDetailsViewSharedPtr () const =0
virtual FName GetNodeName () const =0
Gets an identifier name for this node.
virtual EDetailNodeType GetNodeType () const =0
virtual TSharedPtr< class IDetailPropertyRow > GetRow () const =0
Get the property row that this node is represented by.
UE_DEPRECATED (5.5, "Use GetNodeDetailsViewSharedPtr() instead.") class IDetailsView *GetNodeDetailsView() const
Detailed Description
Definition at line 118 of file IDetailTreeNode.h.
Constructor & Destructor Documentation
~IDetailTreeNode()
virtual IDetailTreeNode::~IDetailTreeNode () inline virtual
Definition at line 121 of file IDetailTreeNode.h.
Member Function Documentation
CreateNodeWidgets()
virtual FNodeWidgets IDetailTreeNode::CreateNodeWidgets () const pure virtual
Creates the slate widgets for this row.
Returns
the node widget structure with either name/value pair or a whole row widget
Implemented in FDetailTreeNode.
CreatePropertyHandle()
virtual TSharedPtr< IPropertyHandle > IDetailTreeNode::CreatePropertyHandle () const pure virtual
Creates a handle to the property on this row if the row represents a property.
Only compatible with item node types that are properties
Returns
The property handle for the row or null if the node doesn't have a property
GetChildren()
virtual void IDetailTreeNode::GetChildren (TArray< TSharedRef< IDetailTreeNode > > & OutChildren, const bool & bInIgnoreVisibility = false) pure virtual
Gets the children of this tree node
Note: Customizations can determine the visibility of children.
This will only return visible children if bInIgnoreVisibility if false
Parameters
OutChildren The generated children
bInIgnoreVisibility Whether to return children regardless of visibility
Implemented in FDetailTreeNode.
GetFilterStrings()
virtual void IDetailTreeNode::GetFilterStrings (TArray< FString > & OutFilterStrings) const pure virtual
Gets the filter strings for this node in the tree.
Implemented in FDetailTreeNode.
GetInitiallyCollapsed()
virtual bool IDetailTreeNode::GetInitiallyCollapsed () const pure virtual
Gets if this node should be initially collapsed by default.
Implemented in FDetailTreeNode.
GetNodeDetailsViewSharedPtr()
virtual TSharedPtr< class IDetailsView > IDetailTreeNode::GetNodeDetailsViewSharedPtr () const pure virtual
Returns
Get the details view that this node is contained in.
Referenced by UE_DEPRECATED().
GetNodeName()
virtual FName IDetailTreeNode::GetNodeName () const pure virtual
Gets an identifier name for this node.
This is not a name formatted for display purposes, but can be useful for storing UI state like if this row is expanded.
Implemented in FDetailTreeNode.
GetNodeType()
virtual EDetailNodeType IDetailTreeNode::GetNodeType () const pure virtual
Returns
The type of this node. Should be used to determine any external styling to apply to the generated r ow
GetRow()
virtual TSharedPtr< class IDetailPropertyRow > IDetailTreeNode::GetRow () const pure virtual
Get the property row that this node is represented by.
Implemented in FDetailTreeNode.
UE_DEPRECATED()
IDetailTreeNode::UE_DEPRECATED (5. 5, "Use GetNodeDetailsViewSharedPtr() instead.") const inline
Definition at line 128 of file IDetailTreeNode.h.
References TSharedPtr< ObjectType, InMode >::Get(), and GetNodeDetailsViewSharedPtr().
The documentation for this class was generated from the following file:
IDetailTreeNode.h