Unreal Engine 5.6 C++ API: verse::FExecutionContext Struct Reference
verse::FExecutionContext Struct Reference
#include "VVMExecutionContext.h"
Public Member Functions
FExecutionContext (const FExecutionContext &Other)
::Verse::FRunningContext GetContext ()
Static Public Member Functions
static FExecutionContext GetActiveContext ()
static bool IsExecutionBlocked ()
static bool SetBlockExecution (bool ShouldBlock)
Private Member Functions
FExecutionContext (::Verse::FRunningContext InImpl)
Private Attributes
::Verse::FRunningContext Impl
Static Private Attributes
static bool bBlockAllExecution = false
Detailed Description
Definition at line 33 of file VVMExecutionContext.h.
Constructor & Destructor Documentation
FExecutionContext() [1/2]
verse::FExecutionContext::FExecutionContext (const FExecutionContext & Other) inline
Definition at line 35 of file VVMExecutionContext.h.
References FExecutionContext(), bBlockAllExecution, ensure, and Other.
Referenced by FExecutionContext(), and GetActiveContext().
FExecutionContext() [2/2]
verse::FExecutionContext::FExecutionContext (::Verse::FRunningContext InImpl) inline explicit private
Definition at line 82 of file VVMExecutionContext.h.
Member Function Documentation
GetActiveContext()
FExecutionContext verse::FExecutionContext::GetActiveContext () inline static
Definition at line 49 of file VVMExecutionContext.h.
References FExecutionContext(), bBlockAllExecution, and ensure.
GetContext()
::Verse::FRunningContext verse::FExecutionContext::GetContext () inline
Definition at line 60 of file VVMExecutionContext.h.
IsExecutionBlocked()
bool verse::FExecutionContext::IsExecutionBlocked () inline static
Definition at line 72 of file VVMExecutionContext.h.
References bBlockAllExecution.
SetBlockExecution()
bool verse::FExecutionContext::SetBlockExecution (bool ShouldBlock) inline static
Definition at line 66 of file VVMExecutionContext.h.
References bBlockAllExecution.
Field Documentation
bBlockAllExecution
bool verse::FExecutionContext::bBlockAllExecution = false static private
Definition at line 88 of file VVMExecutionContext.h.
Referenced by FExecutionContext(), GetActiveContext(), IsExecutionBlocked(), and SetBlockExecution().
Impl
::Verse::FRunningContext verse::FExecutionContext::Impl private
Definition at line 93 of file VVMExecutionContext.h.
The documentation for this struct was generated from the following files:
VVMExecutionContext.h
VVMExecutionContext.cpp