Unreal Engine 5.6 C++ API: UE::Sequencer::FKeySelection Struct Reference
UE::Sequencer::FKeySelection Struct Reference
Main key selection class that stores selected key handles, and the channel they originated from.
#include "Selection.h"
Public Member Functions
void Deselect (FKeyHandle InKey)
Overridden Deselect function to remove duplicate keys on deselection.
void Empty ()
Overridden Empty function to remove duplicate keys on deselection.
void Select (TViewModelPtr< FChannelModel > InOwner, FKeyHandle InKey, bool *OutNewlySelected=nullptr)
Overridden Select function for passing by TViewModelPtr instead of TWeakViewModelPtr.
template<typename RangeType>
void SelectRange (TViewModelPtr< FChannelModel > InOwner, RangeType Range, bool *OutAnySelected=nullptr)
Overridden SelectRange function for passing by TViewModelPtr instead of TWeakViewModelPtr.
Public Member Functions inherited from UE::Sequencer::TUniqueFragmentSelectionSet< FKeyHandle, FChannelModel >
FORCEINLINE TUniqueFragmentSelectionSetIterator< FKeyHandle > begin () const
void Deselect (FKeyHandle InKey)
Deselect an item.
void Empty ()
Empty this selection.
FORCEINLINE TUniqueFragmentSelectionSetIterator< FKeyHandle > end () const
TViewModelPtr< FChannelModel > GetModelForKey (FKeyHandle InKey) const
Retrieve the view model associated with the specified fragment selection.
const TSet< FKeyHandle > & GetSelected () const
Returns the underlying selection set (including potentially invalid items)
bool IsSelected (FKeyHandle InKey) const
Check whether a given item is currently selected.
int32 Num () const
Returns the number of selected items (including potentially invalid items)
void RemoveByPredicate (Filter &&InFilter)
Remove all selected items that pass the specified filter.
void ReplaceWith (TUniqueFragmentSelectionSet< FKeyHandle, FChannelModel > &&OtherSelection)
Replace this selection set with the contents from another.
void Select (TViewModelPtr< FChannelModel > InOwner, FKeyHandle InKey, bool *OutNewlySelected=nullptr)
Select a key, optionally supplying a boolean to receieve a value indicating whether it was already selected or not.
void SelectRange (TViewModelPtr< FChannelModel > InOwner, RangeType Range, bool *OutAnySelected=nullptr)
Selects a range of keys, optionally supplying a boolean to receieve a value indicating whether any were newly selected or not.
Public Member Functions inherited from UE::Sequencer::FSelectionBase
SEQUENCERCORE_API void Empty ()
Empty this selection set.
bool HasPendingChanges () const
Check whether this selection set has reported changes that are currently pending.
Private Member Functions
void RemoveDuplicateKeys (TArrayView< FKeyHandle > KeyHandles)
Additional Inherited Members
Data Fields inherited from UE::Sequencer::FSelectionBase
FSimpleMulticastDelegate OnChanged
Broadcast if this selection set has changed when all event suppressors have been destroyed.
Protected Member Functions inherited from UE::Sequencer::FSelectionBase
FSelectionBase ()
Should only be used by derived types.
virtual ~FSelectionBase ()
FSequencerCoreSelection * GetOwner () const
Retrieve the owner of this instance, assuming it has been added to one.
SEQUENCERCORE_API void ReportChanges (bool bInSelectionChanged=true)
Called by derived classes when they have changed.
Detailed Description
Main key selection class that stores selected key handles, and the channel they originated from.
Definition at line 26 of file Editor/Sequencer/Public/MVVM/Selection/Selection.h.
Member Function Documentation
Deselect()
void UE::Sequencer::FKeySelection::Deselect (FKeyHandle InKey)
Overridden Deselect function to remove duplicate keys on deselection.
Empty()
void UE::Sequencer::FKeySelection::Empty ()
Overridden Empty function to remove duplicate keys on deselection.
RemoveDuplicateKeys()
void UE::Sequencer::FKeySelection::RemoveDuplicateKeys (TArrayView< FKeyHandle > KeyHandles) private
Select()
void UE::Sequencer::FKeySelection::Select (TViewModelPtr< FChannelModel > InOwner, FKeyHandle InKey, bool * OutNewlySelected = nullptr) inline
Overridden Select function for passing by TViewModelPtr instead of TWeakViewModelPtr.
Definition at line 31 of file Editor/Sequencer/Public/MVVM/Selection/Selection.h.
References UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Select().
SelectRange()
template<typename RangeType> void UE::Sequencer::FKeySelection::SelectRange (TViewModelPtr< FChannelModel > InOwner, RangeType Range, bool * OutAnySelected = nullptr) inline
Overridden SelectRange function for passing by TViewModelPtr instead of TWeakViewModelPtr.
Definition at line 40 of file Editor/Sequencer/Public/MVVM/Selection/Selection.h.
References Forward(), and UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::SelectRange().
The documentation for this struct was generated from the following file:
Editor/Sequencer/Public/MVVM/Selection/Selection.h