Unreal Engine 5.6 C++ API: FMaterialShaderMapId Class Reference
FMaterialShaderMapId Class Reference
Contains all the information needed to uniquely identify a FMaterialShaderMap.
#include "MaterialShared.h"
Public Member Functions
FMaterialShaderMapId ()
~FMaterialShaderMapId ()
void AppendKeyString (FString &KeyString, bool bIncludeSourceAndMaterialState=true, bool bIncludeKeyStringShaderDependencies=true) const
Appends string representations of this Id to a key string.
bool ContainsShaderPipelineType (const FShaderPipelineType *ShaderPipelineType) const
Returns true if the requested shader type is a dependency of this shader map Id.
bool ContainsShaderType (const FShaderType *ShaderType, int32 PermutationId) const
Returns true if the requested shader type is a dependency of this shader map Id.
bool ContainsVertexFactoryType (const FVertexFactoryType *VFType) const
Returns true if the requested vertex factory type is a dependency of this shader map Id.
bool Equals (const FMaterialShaderMapId &ReferenceSet, bool bWithStaticParameters) const
void GetMaterialHash (FSHAHash &OutHash) const
void GetMaterialHash (FSHAHash &OutHash, bool bWithStaticParameters) const
Hashes the material-specific part of this shader map Id.
const TOptional< FMaterialLayersFunctions::ID > & GetMaterialLayersId () const
EShaderPermutationFlags GetPermutationFlags () const
SIZE_T GetSizeBytes () const
const TArray< FStaticComponentMaskParameter > & GetStaticComponentMaskParameters () const
const TArray< FStaticSwitchParameter > & GetStaticSwitchParameters () const
const TArray< FStaticTerrainLayerWeightParameter > & GetTerrainLayerWeightParameters () const
bool IsContentValid () const
Ensure content is valid - for example overrides are set deterministically for serialization and sorting.
bool IsCookedId () const
bool IsValid () const
bool operator!= (const FMaterialShaderMapId &ReferenceSet) const
bool operator== (const FMaterialShaderMapId &ReferenceSet) const
Tests this set against another for equality.
void RecordAndEmit (FMaterialKeyGeneratorContext &Context)
void Serialize (FArchive &Ar, bool bLoadingCooked)
void SetShaderDependencies (const TArray< FShaderType * > &ShaderTypes, const TArray< const FShaderPipelineType * > &ShaderPipelineTypes, const TArray< FVertexFactoryType * > &VFTypes, EShaderPlatform ShaderPlatform)
UE_DEPRECATED (5.5, "Internal function only, called through AppendKeyString.") void AppendStaticParametersString(FString &ParamsString) const
void UpdateFromParameterSet (const FStaticParameterSet &StaticParameters)
Updates the Id's static parameter set data.
Data Fields
FGuid BaseMaterialId
The base material's StateId.
FSHAHash BasePropertyOverridesHash
A hash of the base property overrides for this material instance.
bool bUsingNewHLSLGenerator
Is the material using the new HLSL generator?
FSHAHash CookedShaderMapIdHash
FSHAHash ExpressionIncludesHash
A hash of the content of files (dynamically) included by material expressions.
FSHAHash ExternalCodeReferencesHash
A hash of all external code delcarations referenced in the shader map.
ERHIFeatureLevel::Type FeatureLevel
Feature level that the shader map is going to be compiled for.
FPlatformTypeLayoutParameters LayoutParams
EMaterialQualityLevel::Type QualityLevel
Quality level that this shader map is going to be compiled at.
TArray< FGuid > ReferencedFunctions
Guids of any functions the material was dependent on.
TArray< FGuid > ReferencedParameterCollections
Guids of any Parameter Collections the material was dependent on.
TArray< FShaderPipelineTypeDependency > ShaderPipelineTypeDependencies
Shader pipeline types of shader pipelines that are inlined in this shader map in the DDC.
TArray< FShaderTypeDependency > ShaderTypeDependencies
Shader types of shaders that are inlined in this shader map in the DDC.
FSubstrateCompilationConfig SubstrateCompilationConfig
The Substrate configuration used when compiling this material, can be tweaked in the material editor for live visualization of simplification.
FSHAHash TextureReferencesHash
Hash of the textures referenced by the uniform expressions in the shader map.
EMaterialShaderMapUsage::Type Usage
Indicates what use case this shader map will be for.
FString UsageCustomOutput
Name of which specific custom output this shader map will be a use case for.
TArray< FVertexFactoryTypeDependency > VertexFactoryTypeDependencies
Vertex factory types of shaders that are inlined in this shader map in the DDC.
Private Member Functions
void AppendStaticParameters (FShaderKeyGenerator &KeyGen) const
Private Attributes
bool bIsCookedId
Was the shadermap Id loaded in from a cooked resource.
TOptional< FMaterialLayersFunctions::ID > MaterialLayersId
TArray< FStaticComponentMaskParameter > StaticComponentMaskParameters
TArray< FStaticSwitchParameter > StaticSwitchParameters
Relevant portions of StaticParameterSet from material.
TArray< FStaticTerrainLayerWeightParameter > TerrainLayerWeightParameters
Friends
uint32 GetTypeHash (const FMaterialShaderMapId &Ref)
Detailed Description
Contains all the information needed to uniquely identify a FMaterialShaderMap.
Definition at line 1119 of file MaterialShared.h.
Constructor & Destructor Documentation
FMaterialShaderMapId()
FMaterialShaderMapId::FMaterialShaderMapId () inline
Definition at line 1209 of file MaterialShared.h.
References bIsCookedId, bUsingNewHLSLGenerator, Default, FeatureLevel, High, QualityLevel, SubstrateCompilationConfig, and Usage.
Referenced by Equals(), GetTypeHash, operator!=(), and operator==().
~FMaterialShaderMapId()
FMaterialShaderMapId::~FMaterialShaderMapId () inline
Definition at line 1220 of file MaterialShared.h.
Member Function Documentation
AppendKeyString()
void FMaterialShaderMapId::AppendKeyString (FString & KeyString, bool bIncludeSourceAndMaterialState = true, bool bIncludeKeyStringShaderDependencies = true) const
Appends string representations of this Id to a key string.
References bIncludeKeyStringShaderDependencies.
AppendStaticParameters()
void FMaterialShaderMapId::AppendStaticParameters (FShaderKeyGenerator & KeyGen) const private
ContainsShaderPipelineType()
bool FMaterialShaderMapId::ContainsShaderPipelineType (const FShaderPipelineType * ShaderPipelineType) const
Returns true if the requested shader type is a dependency of this shader map Id.
ContainsShaderType()
bool FMaterialShaderMapId::ContainsShaderType (const FShaderType * ShaderType, int32 PermutationId) const
Returns true if the requested shader type is a dependency of this shader map Id.
ContainsVertexFactoryType()
bool FMaterialShaderMapId::ContainsVertexFactoryType (const FVertexFactoryType * VFType) const
Returns true if the requested vertex factory type is a dependency of this shader map Id.
Equals()
bool FMaterialShaderMapId::Equals (const FMaterialShaderMapId & ReferenceSet, bool bWithStaticParameters) const
References FMaterialShaderMapId().
Referenced by operator!=(), and operator==().
GetMaterialHash() [1/2]
void FMaterialShaderMapId::GetMaterialHash (FSHAHash & OutHash) const inline
Definition at line 1274 of file MaterialShared.h.
References GetMaterialHash().
GetMaterialHash() [2/2]
void FMaterialShaderMapId::GetMaterialHash (FSHAHash & OutHash, bool bWithStaticParameters) const
Hashes the material-specific part of this shader map Id.
Referenced by GetMaterialHash().
GetMaterialLayersId()
const TOptional< FMaterialLayersFunctions::ID > & FMaterialShaderMapId::GetMaterialLayersId () const inline
Definition at line 1318 of file MaterialShared.h.
References MaterialLayersId.
GetPermutationFlags()
EShaderPermutationFlags FMaterialShaderMapId::GetPermutationFlags () const inline
Definition at line 1301 of file MaterialShared.h.
References GetShaderPermutationFlags(), and LayoutParams.
GetSizeBytes()
SIZE_T FMaterialShaderMapId::GetSizeBytes () const inline
Definition at line 1257 of file MaterialShared.h.
References ReferencedFunctions, ReferencedParameterCollections, ShaderPipelineTypeDependencies, ShaderTypeDependencies, and VertexFactoryTypeDependencies.
GetStaticComponentMaskParameters()
const TArray< FStaticComponentMaskParameter > & FMaterialShaderMapId::GetStaticComponentMaskParameters () const inline
Definition at line 1316 of file MaterialShared.h.
References StaticComponentMaskParameters.
GetStaticSwitchParameters()
const TArray< FStaticSwitchParameter > & FMaterialShaderMapId::GetStaticSwitchParameters () const inline
Definition at line 1315 of file MaterialShared.h.
References GetStaticSwitchParameters(), and StaticSwitchParameters.
Referenced by GetStaticSwitchParameters().
GetTerrainLayerWeightParameters()
const TArray< FStaticTerrainLayerWeightParameter > & FMaterialShaderMapId::GetTerrainLayerWeightParameters () const inline
Definition at line 1317 of file MaterialShared.h.
References TerrainLayerWeightParameters.
IsContentValid()
bool FMaterialShaderMapId::IsContentValid () const
Ensure content is valid - for example overrides are set deterministically for serialization and sorting.
IsCookedId()
bool FMaterialShaderMapId::IsCookedId () const inline
Definition at line 1229 of file MaterialShared.h.
References bIsCookedId.
Referenced by IsValid().
IsValid()
bool FMaterialShaderMapId::IsValid () const inline
Definition at line 1238 of file MaterialShared.h.
References BaseMaterialId, CookedShaderMapIdHash, and IsCookedId().
operator!=()
bool FMaterialShaderMapId::operator!= (const FMaterialShaderMapId & ReferenceSet) const inline
Definition at line 1293 of file MaterialShared.h.
References FMaterialShaderMapId(), and Equals().
operator==()
bool FMaterialShaderMapId::operator== (const FMaterialShaderMapId & ReferenceSet) const inline
Tests this set against another for equality.
Parameters
ReferenceSet The set to compare against
Returns
true if the sets are equal
Definition at line 1288 of file MaterialShared.h.
References FMaterialShaderMapId(), and Equals().
RecordAndEmit()
void FMaterialShaderMapId::RecordAndEmit (FMaterialKeyGeneratorContext & Context)
Serialize()
void FMaterialShaderMapId::Serialize (FArchive & Ar, bool bLoadingCooked)
References Ar.
SetShaderDependencies()
void FMaterialShaderMapId::SetShaderDependencies (const TArray< FShaderType * > & ShaderTypes, const TArray< const FShaderPipelineType * > & ShaderPipelineTypes, const TArray< FVertexFactoryType * > & VFTypes, EShaderPlatform ShaderPlatform)
References ShaderPlatform.
UE_DEPRECATED()
FMaterialShaderMapId::UE_DEPRECATED (5. 5, "Internal function only, called through AppendKeyString.") const &
UpdateFromParameterSet()
void FMaterialShaderMapId::UpdateFromParameterSet (const FStaticParameterSet & StaticParameters)
Updates the Id's static parameter set data.
Reset the override parameters for deterministic serialization and comparison
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FMaterialShaderMapId & Ref) friend
Definition at line 1247 of file MaterialShared.h.
References FMaterialShaderMapId().
Field Documentation
BaseMaterialId
FGuid FMaterialShaderMapId::BaseMaterialId
The base material's StateId.
This guid represents all the state of a UMaterial that is not covered by the other members of FMaterialShaderMapId. Any change to the UMaterial that modifies that state (for example, adding an expression) must modify this guid.
Definition at line 1130 of file MaterialShared.h.
Referenced by IsValid().
BasePropertyOverridesHash
FSHAHash FMaterialShaderMapId::BasePropertyOverridesHash
A hash of the base property overrides for this material instance.
Definition at line 1191 of file MaterialShared.h.
bIsCookedId
bool FMaterialShaderMapId::bIsCookedId private
Was the shadermap Id loaded in from a cooked resource.
Definition at line 1157 of file MaterialShared.h.
Referenced by FMaterialShaderMapId(), and IsCookedId().
bUsingNewHLSLGenerator
bool FMaterialShaderMapId::bUsingNewHLSLGenerator
Is the material using the new HLSL generator?
Definition at line 1197 of file MaterialShared.h.
Referenced by FMaterialShaderMapId().
CookedShaderMapIdHash
FSHAHash FMaterialShaderMapId::CookedShaderMapIdHash
Definition at line 1122 of file MaterialShared.h.
Referenced by IsValid().
ExpressionIncludesHash
FSHAHash FMaterialShaderMapId::ExpressionIncludesHash
A hash of the content of files (dynamically) included by material expressions.
Definition at line 1188 of file MaterialShared.h.
ExternalCodeReferencesHash
FSHAHash FMaterialShaderMapId::ExternalCodeReferencesHash
A hash of all external code delcarations referenced in the shader map.
Definition at line 1194 of file MaterialShared.h.
FeatureLevel
ERHIFeatureLevel::Type FMaterialShaderMapId::FeatureLevel
Feature level that the shader map is going to be compiled for.
Definition at line 1140 of file MaterialShared.h.
Referenced by FMaterialShaderMapId().
LayoutParams
FPlatformTypeLayoutParameters FMaterialShaderMapId::LayoutParams
Definition at line 1207 of file MaterialShared.h.
Referenced by GetPermutationFlags().
MaterialLayersId
TOptional<FMaterialLayersFunctions::ID> FMaterialShaderMapId::MaterialLayersId private
Definition at line 1163 of file MaterialShared.h.
Referenced by GetMaterialLayersId().
QualityLevel
EMaterialQualityLevel::Type FMaterialShaderMapId::QualityLevel
Quality level that this shader map is going to be compiled at.
Can be a value of EMaterialQualityLevel::Num if quality level doesn't matter to the compiled result.
Definition at line 1137 of file MaterialShared.h.
Referenced by FMaterialShaderMapId().
ReferencedFunctions
TArray<FGuid> FMaterialShaderMapId::ReferencedFunctions
Guids of any functions the material was dependent on.
Definition at line 1166 of file MaterialShared.h.
Referenced by GetSizeBytes().
ReferencedParameterCollections
TArray<FGuid> FMaterialShaderMapId::ReferencedParameterCollections
Guids of any Parameter Collections the material was dependent on.
Definition at line 1169 of file MaterialShared.h.
Referenced by GetSizeBytes().
ShaderPipelineTypeDependencies
TArray<FShaderPipelineTypeDependency> FMaterialShaderMapId::ShaderPipelineTypeDependencies
Shader pipeline types of shader pipelines that are inlined in this shader map in the DDC.
Definition at line 1175 of file MaterialShared.h.
Referenced by GetSizeBytes().
ShaderTypeDependencies
TArray<FShaderTypeDependency> FMaterialShaderMapId::ShaderTypeDependencies
Shader types of shaders that are inlined in this shader map in the DDC.
Definition at line 1172 of file MaterialShared.h.
Referenced by GetSizeBytes().
StaticComponentMaskParameters
TArray<FStaticComponentMaskParameter> FMaterialShaderMapId::StaticComponentMaskParameters private
Definition at line 1161 of file MaterialShared.h.
Referenced by GetStaticComponentMaskParameters().
StaticSwitchParameters
TArray<FStaticSwitchParameter> FMaterialShaderMapId::StaticSwitchParameters private
Relevant portions of StaticParameterSet from material.
Definition at line 1160 of file MaterialShared.h.
Referenced by GetStaticSwitchParameters().
SubstrateCompilationConfig
FSubstrateCompilationConfig FMaterialShaderMapId::SubstrateCompilationConfig
The Substrate configuration used when compiling this material, can be tweaked in the material editor for live visualization of simplification.
Definition at line 1200 of file MaterialShared.h.
Referenced by FMaterialShaderMapId().
TerrainLayerWeightParameters
TArray<FStaticTerrainLayerWeightParameter> FMaterialShaderMapId::TerrainLayerWeightParameters private
Definition at line 1162 of file MaterialShared.h.
Referenced by GetTerrainLayerWeightParameters().
TextureReferencesHash
FSHAHash FMaterialShaderMapId::TextureReferencesHash
Hash of the textures referenced by the uniform expressions in the shader map.
This is stored in the shader map Id to gracefully handle situations where code changes that generates the array of textures that the uniform expressions use to link up after being loaded from the DDC.
Definition at line 1185 of file MaterialShared.h.
Usage
EMaterialShaderMapUsage::Type FMaterialShaderMapId::Usage
Indicates what use case this shader map will be for.
This allows the same UMaterial / UMaterialInstance to be compiled with multiple FMaterial derived classes, While still creating an Id that is deterministic between runs (no appCreateGuid used).
Definition at line 1148 of file MaterialShared.h.
Referenced by FMaterialShaderMapId().
UsageCustomOutput
FString FMaterialShaderMapId::UsageCustomOutput
Name of which specific custom output this shader map will be a use case for.
Only used if Usage is MaterialExportCustomOutput.
Definition at line 1153 of file MaterialShared.h.
VertexFactoryTypeDependencies
TArray<FVertexFactoryTypeDependency> FMaterialShaderMapId::VertexFactoryTypeDependencies
Vertex factory types of shaders that are inlined in this shader map in the DDC.
Definition at line 1178 of file MaterialShared.h.
Referenced by GetSizeBytes().
The documentation for this class was generated from the following file:
MaterialShared.h