Unreal Engine 5.6 C++ API: FChildren::FConstWidgetRef Struct Reference
FChildren::FConstWidgetRef Struct Reference
#include "ChildrenBase.h"
Public Member Functions
FConstWidgetRef (const FConstWidgetRef &Other)
FConstWidgetRef (ECopyConstruct, TSharedRef< const SWidget > InWidgetCopy)
FConstWidgetRef (ERefConstruct, const SWidget &InWidgetRef)
FConstWidgetRef (FConstWidgetRef &&Other)
const SWidget & GetWidget () const
FConstWidgetRef & operator= (const FConstWidgetRef &)=delete
FConstWidgetRef & operator= (FConstWidgetRef &&)=delete
Private Attributes
TOptional< TSharedRef< const SWidget > > WidgetCopy
const SWidget & WidgetReference
Detailed Description
Definition at line 158 of file ChildrenBase.h.
Constructor & Destructor Documentation
FConstWidgetRef() [1/4]
FChildren::FConstWidgetRef::FConstWidgetRef (ECopyConstruct , TSharedRef< const SWidget > InWidgetCopy) inline
Definition at line 165 of file ChildrenBase.h.
References MoveTemp(), WidgetCopy, and WidgetReference.
Referenced by FConstWidgetRef(), FConstWidgetRef(), operator=(), and operator=().
FConstWidgetRef() [2/4]
FChildren::FConstWidgetRef::FConstWidgetRef (ERefConstruct , const SWidget & InWidgetRef) inline
Definition at line 169 of file ChildrenBase.h.
References WidgetCopy, and WidgetReference.
FConstWidgetRef() [3/4]
FChildren::FConstWidgetRef::FConstWidgetRef (const FConstWidgetRef & Other) inline
Definition at line 173 of file ChildrenBase.h.
References FConstWidgetRef(), Other, WidgetCopy, and WidgetReference.
FConstWidgetRef() [4/4]
FChildren::FConstWidgetRef::FConstWidgetRef (FConstWidgetRef && Other) inline
Definition at line 177 of file ChildrenBase.h.
References FConstWidgetRef(), MoveTemp(), Other, WidgetCopy, and WidgetReference.
Member Function Documentation
GetWidget()
const SWidget & FChildren::FConstWidgetRef::GetWidget () const inline
Definition at line 183 of file ChildrenBase.h.
References WidgetReference.
Referenced by FChildren::ForEachWidget().
operator=() [1/2]
FConstWidgetRef & FChildren::FConstWidgetRef::operator= (const FConstWidgetRef &) delete
References FConstWidgetRef().
operator=() [2/2]
FConstWidgetRef & FChildren::FConstWidgetRef::operator= (FConstWidgetRef &&) delete
References FConstWidgetRef().
Field Documentation
WidgetCopy
TOptional<TSharedRef<const SWidget> > FChildren::FConstWidgetRef::WidgetCopy private
Definition at line 161 of file ChildrenBase.h.
Referenced by FConstWidgetRef(), FConstWidgetRef(), FConstWidgetRef(), and FConstWidgetRef().
WidgetReference
const SWidget& FChildren::FConstWidgetRef::WidgetReference private
Definition at line 162 of file ChildrenBase.h.
Referenced by FConstWidgetRef(), FConstWidgetRef(), FConstWidgetRef(), FConstWidgetRef(), and GetWidget().
The documentation for this struct was generated from the following file:
ChildrenBase.h