Unreal Engine 5.6 C++ API: UE::MeshDeformation Namespace Reference
UE::MeshDeformation Namespace Reference
Data Structures
class CotanTriangleData
The per-triangle data used in constructing the cotangent weighted laplacian.
class MeanValueTriangleData
The per-triangle data used in constructing the mean-value weighted laplacian.
Enumerations
enum class ECotangentAreaMode { NoArea = 0 , VoronoiArea = 1 }
enum class ECotangentWeightMode { Default = 0 , ClampedMagnitude = 1 , TriangleArea = 2 }
Functions
template<typename MeshT>
int32 ComputeNumMatrixElements (const MeshT &DynamicMesh, const TArray< int32 > &ToVtxId)
void DYNAMICMESH_API ComputeSmoothing_BiHarmonic (const ELaplacianWeightScheme WeightingScheme, const FDynamicMesh3 &OriginalMesh, const double Speed, const double Weight, const int32 NumIterations, TArray< FVector3d > &PositionArray, FProgressCancel *Progress=nullptr)
Note: for discussion of implicit / explicit integration of diffusion and biharmonic equations see "Implicit Fairing of Irregular Meshes using Diffusion and Curvature Flow" - M Desbrun 99.
void DYNAMICMESH_API ComputeSmoothing_Diffusion (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 &OriginalMesh, bool bForwardEuler, const double Speed, double Weight, const int32 NumIterations, TArray< FVector3d > &PositionArray, FProgressCancel *Progress=nullptr)
This is equivalent to forward or backward Euler time steps of the diffusion equation.
void DYNAMICMESH_API ComputeSmoothing_Forward (bool bUniformWeightScheme, bool bSmoothBoundary, const FDynamicMesh3 &OriginalMesh, TFunctionRef< double(int VID, bool bBoundary)> GetSmoothingAlpha, const int32 NumIterations, TArray< FVector3d > &PositionArray, class FProgressCancel *Progress=nullptr)
Simple iterative smoothing with an optional weight map Each iteration Lerps towards the weighted neighbor centroid by the GetSmoothingAlpha amount.
void DYNAMICMESH_API ComputeSmoothing_ImplicitBiHarmonicPCG (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 &OriginalMesh, const double Speed, const double Weight, const int32 MaxIterations, TArray< FVector3d > &PositionArray)
TUniquePtr< UE::Solvers::IConstrainedMeshSolver > DYNAMICMESH_API ConstructConstrainedMeshDeformer (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 &DynamicMesh)
Solves the linear system for p_vec.
TUniquePtr< UE::Solvers::IConstrainedMeshSolver > DYNAMICMESH_API ConstructConstrainedMeshSmoother (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 &DynamicMesh)
Solves the linear system for p_vec.
template<typename RealType>
void ConstructCotangentLaplacian (const FDynamicMesh3 &DynamicMesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &AreaMatrix, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianBoundary)
Construct a sparse matrix representation using a cotangent-weighted Laplacian.
template<typename RealType>
void ConstructCotangentLaplacian (const FDynamicMesh3 &DynamicMesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianBoundary, const bool bClampWeights)
Construct a sparse matrix representation using a pre-multiplied cotangent-weighted Laplacian.
void DYNAMICMESH_API ConstructEdgeCotanWeightsDataArray (const FDynamicMesh3 &Mesh, TArray< double > &EdgeWeightsDataArray, double ClampMin=-1.e5, double ClampMax=1.e5)
template<typename RealType>
void ConstructFullCotangentLaplacian (const FDynamicMesh3 &DynamicMesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianMatrix, ECotangentWeightMode WeightMode=ECotangentWeightMode::ClampedMagnitude, ECotangentAreaMode AreaMode=ECotangentAreaMode::NoArea)
Construct sparse Cotangent Laplacian matrix.
template<typename RealType>
void ConstructFullIDTCotangentLaplacian (const FDynamicMesh3 &Mesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianMatrix, ECotangentWeightMode WeightMode=ECotangentWeightMode::ClampedMagnitude, ECotangentAreaMode AreaMode=ECotangentAreaMode::NoArea)
Use intrinsic Delaunay mesh to construct sparse Cotangent Laplacian matrix.
template<typename RealType>
void ConstructIDTCotangentLaplacian (const FDynamicMesh3 &DynamicMesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianBoundary, const bool bClampWeights)
Construct a sparse matrix representation using a pre-multiplied cotangent-weighted Laplacian, using an intrinsic Delaunay mesh internally NB: there is no reason to expect this to be a symmetric matrix.
template<typename RealType>
void ConstructMeanValueWeightLaplacian (const FDynamicMesh3 &DynamicMesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianBoundary)
Construct a sparse matrix representation using a meanvalue-weighted Laplacian.
TUniquePtr< UE::Solvers::IConstrainedMeshUVSolver > DYNAMICMESH_API ConstructNaturalConformalParamSolver (const FDynamicMesh3 &DynamicMesh)
Create solver for the Least Squares Conformal UV Parameterization for this mesh.
TUniquePtr< UE::Solvers::IConstrainedLaplacianMeshSolver > DYNAMICMESH_API ConstructSoftMeshDeformer (const FDynamicMesh3 &DynamicMesh)
Construct a Mesh Deformer object for the given mesh that uses Biharmonic Laplacian Mesh Deformation to solve for the deformed vertex positions.
TUniquePtr< UE::Solvers::IConstrainedMeshUVSolver > DYNAMICMESH_API ConstructSpectralConformalParamSolver (const FDynamicMesh3 &DynamicMesh, bool bPreserveIrregularity)
Create solver for the Spectral Conformal UV Parameterization for this mesh.
template<typename TriangleDataType>
void ConstructTriangleDataArray (const FDynamicMesh3 &DynamicMesh, const FTriangleLinearization &TriangleLinearization, TArray< TriangleDataType > &TriangleDataArray)
Return and array in triangle order that holds the per-triangle derived data needed.
template<typename RealType>
void ConstructUmbrellaLaplacian (const FDynamicMesh3 &DynamicMesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianBoundary)
Construct a sparse matrix representation of an umbrella weighted Laplacian.
TUniquePtr< UE::Solvers::IConstrainedMeshSolver > DYNAMICMESH_API ConstructUniformConstrainedMeshDeformer (const FDynamicGraph3d &Graph)
Interface for a mesh with only edges and vertices.
template<typename RealType, typename MeshType>
void ConstructUniformLaplacian (const MeshType &Mesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianBoundary)
Construct a sparse matrix representation of a uniform weighted Laplacian.
template<typename RealType>
void ConstructValenceWeightedLaplacian (const FDynamicMesh3 &DynamicMesh, const FVertexLinearization &VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > &LaplacianBoundary)
Construct a sparse matrix representation of a valence-weighted Laplacian.
Enumeration Type Documentation
ECotangentAreaMode
enum class UE::MeshDeformation::ECotangentAreaMode strong
Enumerator
NoArea
uniform-weighted cotangents
VoronoiArea
weight each vertex/row by 1/voronoi_area
Definition at line 207 of file LaplacianMatrixAssembly.h.
ECotangentWeightMode
enum class UE::MeshDeformation::ECotangentWeightMode strong
Enumerator
Default
Standard cotangent weights.
ClampedMagnitude
Magnitude of matrix entries clamped to [-1e5,1e5], scaled by area weight.
TriangleArea
Divide cotangent weights by the area of the triangle.
Definition at line 196 of file LaplacianMatrixAssembly.h.
Function Documentation
ComputeNumMatrixElements()
template<typename MeshT> int32 UE::MeshDeformation::ComputeNumMatrixElements (const MeshT & DynamicMesh, const TArray< int32 > & ToVtxId)
Definition at line 20 of file PrecomputedMeshWeightData.h.
References TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::SetNumUninitialized().
Referenced by ConstructCotangentLaplacian(), ConstructCotangentLaplacian(), ConstructFullCotangentLaplacian(), ConstructFullIDTCotangentLaplacian(), ConstructIDTCotangentLaplacian(), ConstructMeanValueWeightLaplacian(), ConstructUmbrellaLaplacian(), ConstructUniformLaplacian(), and ConstructValenceWeightedLaplacian().
ComputeSmoothing_BiHarmonic()
void DYNAMICMESH_API UE::MeshDeformation::ComputeSmoothing_BiHarmonic (const ELaplacianWeightScheme WeightingScheme, const FDynamicMesh3 & OriginalMesh, const double Speed, const double Weight, const int32 NumIterations, TArray< FVector3d > & PositionArray, FProgressCancel * Progress = nullptr)
Note: for discussion of implicit / explicit integration of diffusion and biharmonic equations see "Implicit Fairing of Irregular Meshes using Diffusion and Curvature Flow" - M Desbrun 99.
although the following suggests an additional source term could be included in the implicit solve for better accuracy. or "Generalized Surface Flows for Mesh Processing" Eckstein et al. 2007 This is equivalent to taking a single backward Euler time step of bi-harmonic diffusion where L is the Laplacian (Del^2) , and L^T L is an approximation of the Del^4.
dp/dt = - k*k L^T L[p]
p^{n+1} + dt * k * k L^TL [p^{n+1}] = p^{n}
re-write as L^TL[p^{n+1}] + weight * weight p^{n+1} = weight * weight p^{n} with weight = 1 / (k * Sqrt[dt])
The result is returned in the PositionArray Note: if canceled using the optional FProgressCancel, the results may be in an unusable state.
References Speed, and Weight.
ComputeSmoothing_Diffusion()
void DYNAMICMESH_API UE::MeshDeformation::ComputeSmoothing_Diffusion (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 & OriginalMesh, bool bForwardEuler, const double Speed, double Weight, const int32 NumIterations, TArray< FVector3d > & PositionArray, FProgressCancel * Progress = nullptr)
This is equivalent to forward or backward Euler time steps of the diffusion equation.
dp/dt = L[p]
p^{n+1} = p^{n} + dt L[p^{n}]
with dt = Speed / Max(|w_ii|)
here w_ii are the diagonal values of L Note: if canceled using the optional FProgressCancel, the results may be in an unusable state.
References Speed, and Weight.
ComputeSmoothing_Forward()
void DYNAMICMESH_API UE::MeshDeformation::ComputeSmoothing_Forward (bool bUniformWeightScheme, bool bSmoothBoundary, const FDynamicMesh3 & OriginalMesh, TFunctionRef< double(int VID, bool bBoundary)> GetSmoothingAlpha, const int32 NumIterations, TArray< FVector3d > & PositionArray, class FProgressCancel * Progress = nullptr)
Simple iterative smoothing with an optional weight map Each iteration Lerps towards the weighted neighbor centroid by the GetSmoothingAlpha amount.
Parameters
bUniformWeightScheme If true, uses uniform weights for centroid; else uses cotan weights
bSmoothBoundary If true, boundary vertices are smoothed (toward the centroid of neighboring boundary vertices); else boundary is fixed
OriginalMesh The source mesh, used for topology
GetSmoothingAlpha The amount to lerp each vertex towards the centroid, per iteration
NumIterations Number of iterations to smooth
PositionsArray Vertex positions (input and output)
Progress An optional interrupter that can terminate the iterations, leaving the results in an unusable state.
ComputeSmoothing_ImplicitBiHarmonicPCG()
void DYNAMICMESH_API UE::MeshDeformation::ComputeSmoothing_ImplicitBiHarmonicPCG (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 & OriginalMesh, const double Speed, const double Weight, const int32 MaxIterations, TArray< FVector3d > & PositionArray)
References Speed, and Weight.
ConstructConstrainedMeshDeformer()
TUniquePtr< UE::Solvers::IConstrainedMeshSolver > DYNAMICMESH_API UE::MeshDeformation::ConstructConstrainedMeshDeformer (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 & DynamicMesh)
Solves the linear system for p_vec.
   ( Transpose(L) * L   + (0  0      )  ) p_vec = source_vec + ( 0              )
 (                      (0 lambda^2)  )                      ( lambda^2 c_vec )
where: L := laplacian for the mesh, source_vec := Transpose(L)*L mesh_vertex_positions lambda := weights c_vec := constrained positions
Expected Use:
// Create Deformation Solver from Mesh TUniquePtr<IConstrainedMeshSolver> MeshDeformer = ConstructConstrainedMeshDeformer(ELaplacianWeightScheme::ClampedCotangent, DynamicMesh);
// Add constraints. for.. { int32 VtxId = ..; double Weight = ..; FVector3d TargetPos = ..; bool bPostFix = ...; MeshDeformer->AddConstraint(VtxId, Weight, TargetPos, bPostFix); }
// Solve for new mesh vertex locations TArray<FVector3d> PositionBuffer; MeshDeformer->Deform(PositionBuffer);
// Update Mesh? for (int32 VtxId : DynamicMesh.VertexIndices()) DynamicMesh.SetVertex(VtxId, PositionBuffer[VtxId]); ...
// Update constraint positions. for .. { int32 VtxId = ..; FVector3d TargetPos = ..; bool bPostFix = ...; MeshDeformer->UpdateConstraintPosition(VtxId, TargetPos, bPostFix); }
// Solve for new vertex locations. MeshDeformer->Deform(PositionBuffer); // Update Mesh?
Referenced by UE::Geometry::FLaplacianOffsetMeshOp::Offset().
ConstructConstrainedMeshSmoother()
TUniquePtr< UE::Solvers::IConstrainedMeshSolver > DYNAMICMESH_API UE::MeshDeformation::ConstructConstrainedMeshSmoother (const ELaplacianWeightScheme WeightScheme, const FDynamicMesh3 & DynamicMesh)
Solves the linear system for p_vec.
   ( Transpose(L) * L   + (0  0      )  ) p_vec = ( 0              )
 (                      (0 lambda^2)  )         ( lambda^2 c_vec )
where: L := laplacian for the mesh, lambda := weights c_vec := constrained positions
Expected Use: same as the ConstrainedMeshDeformer above.
ConstructCotangentLaplacian() [1/2]
template<typename RealType> void UE::MeshDeformation::ConstructCotangentLaplacian (const FDynamicMesh3 & DynamicMesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & AreaMatrix, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianBoundary)
Construct a sparse matrix representation using a cotangent-weighted Laplacian.
but returns the result in two symmetric parts.
The mesh itself is assumed to have N interior vertices, and M boundary vertices.
(AreaMatrix^{-1}) * L_hat = Cotangent weighted Laplacian.
Parameters
DynamicMesh The triangle mesh
VertexMap Additional arrays used to map between vertexID and offset in a linear array (i.e. the row). The vertices are ordered so that last M (= VertexMap.NumBoundaryVerts()) correspond to those on the boundary.
AreaMatrix On return, the mass matrix for the internal vertices. sparse N x N matrix
LaplacianInterior On return, the laplacian operator that acts on the interior vertices: sparse N x N matrix - symmetric
LaplacianBoundary On return, the portion of the operator that acts on the boundary vertices: sparse N x M matrix
AreaMatrix^{-1} * (LaplacianInterior * Vector_InteriorVerts + LaplacianBoundary * Vector_BoundaryVerts) = Full Laplacian applied to interior vertices.
Definition at line 515 of file LaplacianMatrixAssembly.h.
References UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, checkSlow, ComputeNumMatrixElements(), ConstructTriangleDataArray(), UE::Geometry::Edge, UE::Geometry::FDynamicMesh3::GetEdge(), UE::MeshDeformation::CotanTriangleData::GetOpposingCotangent(), UE::Geometry::FDynamicMesh3::GetTriangle(), UE::Geometry::FDynamicMesh3::InvalidID, UE::Geometry::FVertexLinearization::NumBoundaryVerts(), UE::Geometry::FTriangleLinearization::NumTris(), UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), UE::MeshDeformation::CotanTriangleData::VoronoiArea, UE::Geometry::FDynamicMesh3::VtxEdgesItr(), and UE::Geometry::FDynamicMesh3::VtxTrianglesItr().
ConstructCotangentLaplacian() [2/2]
template<typename RealType> void UE::MeshDeformation::ConstructCotangentLaplacian (const FDynamicMesh3 & DynamicMesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianBoundary, const bool bClampWeights)
Construct a sparse matrix representation using a pre-multiplied cotangent-weighted Laplacian.
NB: there is no reason to expect this to be a symmetric matrix.
This computes the laplacian scaled by the average area A_ave: ie. LScaled = A_ave/(2A_i) (Cot alpha_ij + Cot beta_ij)
The mesh itself is assumed to have N interior vertices, and M boundary vertices.
Parameters
DynamicMesh The triangle mesh
VertexMap Additional arrays used to map between vertexID and offset in a linear array (i.e. the row). The vertices are ordered so that last M (= VertexMap.NumBoundaryVerts()) correspond to those on the boundary.
LaplacianInterior On return, scaled laplacian operator that acts on the interior vertices: sparse N x N matrix
LaplacianBoundary On return, scaled portion of the operator that acts on the boundary vertices: sparse N x M matrix
bClampAreas Indicates if (A_ave / A_i) should be clamped to (0.5, 5) range. in practice this is desirable when creating the biharmonic operator, but not the mean curvature flow operator
LaplacianInterior * Vector_InteriorVerts + LaplacianBoundary * Vector_BoundaryVerts = Full Laplacian applied to interior vertices.
Definition at line 616 of file LaplacianMatrixAssembly.h.
References UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, checkSlow, TMathUtil< double >::Clamp(), ComputeNumMatrixElements(), ConstructTriangleDataArray(), UE::Geometry::Edge, UE::Geometry::FDynamicMesh3::GetEdge(), UE::MeshDeformation::CotanTriangleData::GetOpposingCotangent(), UE::Geometry::FDynamicMesh3::GetTriangle(), UE::Geometry::FDynamicMesh3::InvalidID, UE::Geometry::FVertexLinearization::NumBoundaryVerts(), UE::Geometry::FTriangleLinearization::NumTris(), UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), UE::MeshDeformation::CotanTriangleData::VoronoiArea, UE::Geometry::FDynamicMesh3::VtxEdgesItr(), and UE::Geometry::FDynamicMesh3::VtxTrianglesItr().
ConstructEdgeCotanWeightsDataArray()
void DYNAMICMESH_API UE::MeshDeformation::ConstructEdgeCotanWeightsDataArray (const FDynamicMesh3 & Mesh, TArray< double > & EdgeWeightsDataArray, double ClampMin = -1.e5, double ClampMax = 1.e5)
Returns
Edge cotanget weights.
Todo
Add an option to return the weights computed on an intrinsic mesh.
References UE::Geometry::Mesh.
ConstructFullCotangentLaplacian()
template<typename RealType> void UE::MeshDeformation::ConstructFullCotangentLaplacian (const FDynamicMesh3 & DynamicMesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianMatrix, ECotangentWeightMode WeightMode = ECotangentWeightMode::ClampedMagnitude, ECotangentAreaMode AreaMode = ECotangentAreaMode::NoArea)
Construct sparse Cotangent Laplacian matrix.
This variant combines the N interior and M boundary vertices into a single (N+M) matrix and does not do any special treatment of boundaries, they just get standard Cotan weights
If you don't want to move the boundary vertices to the end, then initialize the VertexMap with bRemapBoundary set to false.
Example usage:
If you want to get the standard cotangent weight matrix for a mesh with no boundary reordering:
FDynamicMesh3 DynamicMesh; const bool bRemapBoundary = false; FVertexLinearization VertexMap(DynamicMesh, bRemapBoundary); ConstructFullCotangentLaplacian(DynamicMesh, VertexMap, ECotangentWeightMode::Default, ECotangentAreaMode::NoArea);
Definition at line 855 of file LaplacianMatrixAssembly.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntriesFunc, UE::MeshDeformation::CotanTriangleData::Area, FMath::Clamp(), TMathUtil< double >::Clamp(), ClampedMagnitude, ComputeNumMatrixElements(), ConstructTriangleDataArray(), FMath::DivideAndRoundUp(), UE::Geometry::Edge, TArray< InElementType, InAllocatorType >::Emplace(), IndexUtil::FindTriIndex(), FTaskGraphInterface::Get(), TArray< InElementType, InAllocatorType >::GetData(), UE::MeshDeformation::CotanTriangleData::GetOpposingCotangent(), UE::Geometry::FDynamicMesh3::InvalidID, UE::Tasks::Launch(), FMath::Max, UE::Geometry::Mesh, FMath::Min, TArray< InElementType, InAllocatorType >::Num(), UE::Geometry::FTriangleLinearization::NumTris(), UE::Geometry::FVertexLinearization::NumVerts(), TArray< InElementType, InAllocatorType >::Reserve(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, TArray< InElementType, InAllocatorType >::SetNum(), UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), TriangleArea, UE_SOURCE_LOCATION, UE::MeshDeformation::CotanTriangleData::VoronoiArea, VoronoiArea, and UE::Tasks::Wait().
ConstructFullIDTCotangentLaplacian()
template<typename RealType> void UE::MeshDeformation::ConstructFullIDTCotangentLaplacian (const FDynamicMesh3 & Mesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianMatrix, ECotangentWeightMode WeightMode = ECotangentWeightMode::ClampedMagnitude, ECotangentAreaMode AreaMode = ECotangentAreaMode::NoArea)
Use intrinsic Delaunay mesh to construct sparse Cotangent Laplacian matrix.
This variant combines the N interior and M boundary vertices into a single (N+M) matrix and does not do any special treatment of boundaries, they just get standard Cotan weights.
Definition at line 983 of file LaplacianMatrixAssembly.h.
References UE::Geometry::FIndex2i::A, UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, TArray< InElementType, InAllocatorType >::AddUninitialized(), UE::Geometry::FIndex2i::B, TMathUtil< double >::Clamp(), ClampedMagnitude, ComputeNumMatrixElements(), TSet< InElementType, KeyFuncs, Allocator >::Contains(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeCotanWeight(), UE::Geometry::FlipToDelaunay(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeLength(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeV(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsEdge(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::MaxEdgeID(), UE::Geometry::Mesh, UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), VoronoiArea, UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VtxEdgesItr(), and Weight.
ConstructIDTCotangentLaplacian()
template<typename RealType> void UE::MeshDeformation::ConstructIDTCotangentLaplacian (const FDynamicMesh3 & DynamicMesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianBoundary, const bool bClampWeights)
Construct a sparse matrix representation using a pre-multiplied cotangent-weighted Laplacian, using an intrinsic Delaunay mesh internally NB: there is no reason to expect this to be a symmetric matrix.
This computes the laplacian scaled by the average area A_ave: ie. LScaled = A_ave/(2A_i) (Cot alpha_ij + Cot beta_ij)
The mesh itself is assumed to have N interior vertices, and M boundary vertices.
Parameters
DynamicMesh The triangle mesh
VertexMap Additional arrays used to map between vertexID and offset in a linear array (i.e. the row). The vertices are ordered so that last M (= VertexMap.NumBoundaryVerts()) correspond to those on the boundary.
LaplacianInterior On return, scaled laplacian operator that acts on the interior vertices: sparse N x N matrix
LaplacianBoundary On return, scaled portion of the operator that acts on the boundary vertices: sparse N x M matrix
bClampAreas Indicates if (A_ave / A_i) should be clamped to (0.5, 5) range. in practice this is desirable when creating the biharmonic operator, but not the mean curvature flow operator
LaplacianInterior * Vector_InteriorVerts + LaplacianBoundary * Vector_BoundaryVerts = Full Laplacian applied to interior vertices.
Definition at line 712 of file LaplacianMatrixAssembly.h.
References UE::Geometry::FIndex2i::A, UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, TArray< InElementType, InAllocatorType >::AddZeroed(), UE::Geometry::FIndex2i::B, TMathUtil< double >::Clamp(), ComputeNumMatrixElements(), TSet< InElementType, KeyFuncs, Allocator >::Contains(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeCotanWeight(), UE::Geometry::FlipToDelaunay(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeLength(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeV(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsEdge(), TMathUtil< double >::Max(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::MaxEdgeID(), UE::Geometry::FVertexLinearization::NumBoundaryVerts(), UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VtxEdgesItr(), and Weight.
ConstructMeanValueWeightLaplacian()
template<typename RealType> void UE::MeshDeformation::ConstructMeanValueWeightLaplacian (const FDynamicMesh3 & DynamicMesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianBoundary)
Construct a sparse matrix representation using a meanvalue-weighted Laplacian.
NB: there is no reason to expect this to be a symmetric matrix.
The mesh itself is assumed to have N interior vertices, and M boundary vertices.
Parameters
DynamicMesh The triangle mesh
VertexMap Additional arrays used to map between vertexID and offset in a linear array (i.e. the row). The vertices are ordered so that last M (= VertexMap.NumBoundaryVerts()) correspond to those on the boundary.
LaplacianInterior On return, the laplacian operator that acts on the interior vertices: sparse N x N matrix
LaplacianBoundary On return, the portion of the operator that acts on the boundary vertices: sparse N x M matrix
LaplacianInterior * Vector_InteriorVerts + LaplacianBoundary * Vector_BoundaryVerts = Full Laplacian applied to interior vertices.
Definition at line 443 of file LaplacianMatrixAssembly.h.
References UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, ComputeNumMatrixElements(), ConstructTriangleDataArray(), UE::Geometry::Edge, UE::Geometry::FDynamicMesh3::GetEdge(), UE::Geometry::FDynamicMesh3::InvalidID, TMathUtil< double >::Max(), UE::Geometry::FVertexLinearization::NumBoundaryVerts(), UE::Geometry::FTriangleLinearization::NumTris(), UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), and UE::Geometry::FDynamicMesh3::VtxEdgesItr().
ConstructNaturalConformalParamSolver()
TUniquePtr< UE::Solvers::IConstrainedMeshUVSolver > DYNAMICMESH_API UE::MeshDeformation::ConstructNaturalConformalParamSolver (const FDynamicMesh3 & DynamicMesh)
Create solver for the Least Squares Conformal UV Parameterization for this mesh.
Warning
Assumption is that mesh is a single connected component.
ConstructSoftMeshDeformer()
TUniquePtr< UE::Solvers::IConstrainedLaplacianMeshSolver > DYNAMICMESH_API UE::MeshDeformation::ConstructSoftMeshDeformer (const FDynamicMesh3 & DynamicMesh)
Construct a Mesh Deformer object for the given mesh that uses Biharmonic Laplacian Mesh Deformation to solve for the deformed vertex positions.
Similar to ConstructConstrainedMeshDeformer() however (1) a Voronoi-Area Weighted Clamped Cotangent Laplacian is always used and (2) the boundary positions are included in the system. This allows for the solution of deformation problems where the boundary also moves, however it also means that constraints should be added for all boundary vertices or the deformation may be unstable.
ConstructSpectralConformalParamSolver()
TUniquePtr< UE::Solvers::IConstrainedMeshUVSolver > DYNAMICMESH_API UE::MeshDeformation::ConstructSpectralConformalParamSolver (const FDynamicMesh3 & DynamicMesh, bool bPreserveIrregularity)
Create solver for the Spectral Conformal UV Parameterization for this mesh.
Warning
Assumption is that mesh is a single connected component.
ConstructTriangleDataArray()
template<typename TriangleDataType> void UE::MeshDeformation::ConstructTriangleDataArray (const FDynamicMesh3 & DynamicMesh, const FTriangleLinearization & TriangleLinearization, TArray< TriangleDataType > & TriangleDataArray)
Return and array in triangle order that holds the per-triangle derived data needed.
Definition at line 208 of file PrecomputedMeshWeightData.h.
References TArray< InElementType, InAllocatorType >::Add(), FMath::DivideAndRoundUp(), FTaskGraphInterface::Get(), UE::Tasks::Launch(), FMath::Max, FMath::Min, UE::Geometry::FTriangleLinearization::NumTris(), TArray< InElementType, InAllocatorType >::Reserve(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), UE::Geometry::FElementLinearization::ToId(), UE_SOURCE_LOCATION, and UE::Tasks::Wait().
Referenced by ConstructCotangentLaplacian(), ConstructCotangentLaplacian(), ConstructFullCotangentLaplacian(), and ConstructMeanValueWeightLaplacian().
ConstructUmbrellaLaplacian()
template<typename RealType> void UE::MeshDeformation::ConstructUmbrellaLaplacian (const FDynamicMesh3 & DynamicMesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianBoundary)
Construct a sparse matrix representation of an umbrella weighted Laplacian.
This Laplacian is defined solely in terms of the connectivity of the mesh. Note, there is no expectation that the resulting matrix will be symmetric.
The mesh itself is assumed to have N interior vertices, and M boundary vertices.
Row i represents the Laplacian at vert_i, the non-zero entries correspond to the incident one-ring vertices vert_j.
L_{ij} = 1 / valence(of i) if vert_j is in the one-ring of vert_i L_{ii} = -Sum{ L_{ij}, j != i} = -1
Parameters
DynamicMesh The triangle mesh
VertexMap Additional arrays used to map between vertexID and offset in a linear array (i.e. the row). The vertices are ordered so that last M (= VertexMap.NumBoundaryVerts()) correspond to those on the boundary.
LaplacianInterior On return, the laplacian operator that acts on the interior vertices: sparse N x N matrix
LaplacianBoundary On return, the portion of the operator that acts on the boundary vertices: sparse N x M matrix
LaplacianInterior * Vector_InteriorVerts + LaplacianBoundary * Vector_BoundaryVerts = Full Laplacian applied to interior vertices.
Definition at line 316 of file LaplacianMatrixAssembly.h.
References UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, checkSlow, ComputeNumMatrixElements(), UE::Geometry::FDynamicMesh3::GetVtxEdgeCount(), UE::Geometry::FDynamicMesh3::IsBoundaryVertex(), UE::Geometry::FVertexLinearization::NumBoundaryVerts(), UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, TArray< InElementType, InAllocatorType >::SetNumUninitialized(), UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), Valence, and UE::Geometry::FDynamicMesh3::VtxVerticesItr().
ConstructUniformConstrainedMeshDeformer()
TUniquePtr< UE::Solvers::IConstrainedMeshSolver > DYNAMICMESH_API UE::MeshDeformation::ConstructUniformConstrainedMeshDeformer (const FDynamicGraph3d & Graph)
Interface for a mesh with only edges and vertices.
Construct a Mesh Deformer object for the given generic mesh that uses Biharmonic Laplacian Mesh Deformation to solve for the deformed vertex positions.
Similar to ConstructConstrainedMeshDeformer() however a uniform-weighted Laplacian is always used. This allows for the solution of deformation problems on a more generic mesh type (triangles or faces are not required.)
ConstructUniformLaplacian()
template<typename RealType, typename MeshType> void UE::MeshDeformation::ConstructUniformLaplacian (const MeshType & Mesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianBoundary)
Construct a sparse matrix representation of a uniform weighted Laplacian.
The uniform weighted Laplacian is defined solely in terms of the connectivity of the mesh. Note, by construction this should be a symmetric matrix.
The mesh itself is assumed to have N interior vertices, and M boundary vertices.
Row i represents the Laplacian at vert_i, the non-zero entries correspond to the incident one-ring vertices vert_j.
L_{ij} = 1 if vert_j is in the one-ring of vert_i L_{ii} = -Sum{ L_{ij}, j != i}
Parameters
DynamicMesh The triangle mesh
VertexMap On return, Additional arrays used to map between vertexID and offset in a linear array (i.e. the row). The vertices are ordered so that last M (= VertexMap.NumBoundaryVerts()) correspond to those on the boundary.
LaplacianInterior On return, the laplacian operator that acts on the interior vertices: sparse N x N matrix
LaplacianBoundary On return, the portion of the operator that acts on the boundary vertices: sparse N x M matrix
LaplacianInterior * Vector_InteriorVerts + LaplacianBoundary * Vector_BoundaryVerts = Full Laplacian applied to interior vertices.
Definition at line 265 of file LaplacianMatrixAssembly.h.
References UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, checkSlow, ComputeNumMatrixElements(), UE::Geometry::Mesh, UE::Geometry::FVertexLinearization::NumBoundaryVerts(), UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, UE::Geometry::FElementLinearization::ToId(), and UE::Geometry::FElementLinearization::ToIndex().
ConstructValenceWeightedLaplacian()
template<typename RealType> void UE::MeshDeformation::ConstructValenceWeightedLaplacian (const FDynamicMesh3 & DynamicMesh, const FVertexLinearization & VertexMap, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianInterior, UE::Solvers::TSparseMatrixAssembler< RealType > & LaplacianBoundary)
Construct a sparse matrix representation of a valence-weighted Laplacian.
The valence weighted Laplacian is defined solely in terms of the connectivity of the mesh. Note, by construction this should be a symmetric matrix.
The mesh itself is assumed to have N interior vertices, and M boundary vertices.
Row i represents the Laplacian at vert_i, the non-zero entries correspond to the incident one-ring vertices vert_j.
L_{ij} = 1/\sqrt(valence(i) + valence(j)) if vert_j is in the one-ring of vert_i L_{ii} = -Sum{ L_{ij}, j != i}
Parameters
DynamicMesh The triangle mesh
VertexMap Additional arrays used to map between vertexID and offset in a linear array (i.e. the row). The vertices are ordered so that last M (= VertexMap.NumBoundaryVerts()) correspond to those on the boundary.
LaplacianInterior On return, the laplacian operator that acts on the interior vertices: sparse N x N matrix
LaplacianBoundary On return, the portion of the operator that acts on the boundary vertices: sparse N x M matrix
LaplacianInterior * Vector_InteriorVerts + LaplacianBoundary * Vector_BoundaryVerts = Full Laplacian applied to interior vertices.
Definition at line 381 of file LaplacianMatrixAssembly.h.
References UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc, ComputeNumMatrixElements(), UE::Geometry::FDynamicMesh3::GetVtxEdgeCount(), UE::Geometry::FVertexLinearization::NumBoundaryVerts(), UE::Geometry::FVertexLinearization::NumVerts(), UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc, TArray< InElementType, InAllocatorType >::SetNumUninitialized(), TMathUtil< RealType >::Sqrt(), UE::Geometry::FElementLinearization::ToId(), UE::Geometry::FElementLinearization::ToIndex(), and UE::Geometry::FDynamicMesh3::VtxVerticesItr().