Unreal Engine 5.6 C++ API: Audio::FConvolutionReverb Class Reference
Audio::FConvolutionReverb Class Reference
FConvolutionReverb applies an impulse response to audio.
#include "ConvolutionReverb.h"
Data Structures
class FChannelFormatConverterWrapper
Public Member Functions
~FConvolutionReverb ()
SYNTHESIS_API int32 GetNumInputChannels () const
SYNTHESIS_API int32 GetNumOutputChannels () const
SYNTHESIS_API const FConvolutionReverbSettings & GetSettings () const
SYNTHESIS_API void ProcessAudio (int32 InNumInputChannels, const FAlignedFloatBuffer &InputAudio, int32 InNumOutputChannels, FAlignedFloatBuffer &OutputAudio)
SYNTHESIS_API void ProcessAudio (int32 InNumInputChannels, const float *InputAudio, int32 InNumOutputChannels, float *OutputAudio, const int32 InNumFrames)
SYNTHESIS_API void SetSettings (const FConvolutionReverbSettings &InSettings)
Static Public Member Functions
static SYNTHESIS_API TUniquePtr< FConvolutionReverb > CreateConvolutionReverb (const FConvolutionReverbInitData &InInitData, const FConvolutionReverbSettings &InSettings=FConvolutionReverbSettings::DefaultSettings)
static SYNTHESIS_API void DeinterleaveBuffer (TArray< FAlignedFloatBuffer > &OutputBuffers, TArrayView< const float > InputBuffer, const int32 NumChannels)
static SYNTHESIS_API void InterleaveBuffer (FAlignedFloatBuffer &OutBuffer, const TArray< FAlignedFloatBuffer > &InputBuffers, const int32 NumChannels)
Private Types
using FInputFormat = IChannelFormatConverter::FInputFormat
using FOutputFormat = IChannelFormatConverter::FOutputFormat
Private Member Functions
FConvolutionReverb ()=delete
FConvolutionReverb (const FConvolutionReverb &&)=delete
FConvolutionReverb (const FConvolutionReverb &)=delete
FConvolutionReverb (TUniquePtr< IConvolutionAlgorithm > InAlgorithm, TUniquePtr< IChannelFormatConverter > InInputConverter, FChannelFormatConverterWrapper &&InOutputConverter, const FConvolutionReverbSettings &InSettings)
FConvolutionReverb & operator= (const FConvolutionReverb &)=delete
void ProcessAudioBlock (const float *InputAudio, int32 InNumInputChannels, FAlignedFloatBuffer &OutputAudio, int32 InNumOutputChannels)
void ResizeArrayOfBuffers (TArray< FAlignedFloatBuffer > &InArrayOfBuffers, int32 MinNumBuffers, int32 NumFrames) const
void ResizeBlockBuffers ()
void ResizeProcessingBuffers ()
void SetConvolutionAlgorithm (TUniquePtr< IConvolutionAlgorithm > InAlgorithm)
void Update (bool bFadeToParams)
Private Attributes
bool bIsConvertingInputChannelFormat
bool bIsConvertingOutputChannelFormat
TUniquePtr< IConvolutionAlgorithm > ConvolutionAlgorithm
int32 ExpectedNumFramesPerCallback
TUniquePtr< FAlignedBlockBuffer > InputBlockBuffer
TArray< float * > InputBufferPtrs
TArray< FAlignedFloatBuffer > InputChannelConverterBuffers
TUniquePtr< IChannelFormatConverter > InputChannelFormatConverter
TArray< FAlignedFloatBuffer > InputDeinterleaveBuffers
FAlignedFloatBuffer InterleavedOutputBlock
int32 NumInputSamplesPerBlock
int32 NumOutputSamplesPerBlock
TUniquePtr< FAlignedBlockBuffer > OutputBlockBuffer
TArray< float * > OutputBufferPtrs
TArray< FAlignedFloatBuffer > OutputChannelConverterBuffers
FChannelFormatConverterWrapper OutputChannelFormatConverter
TArray< FAlignedFloatBuffer > OutputDeinterleaveBuffers
float OutputGain
FConvolutionReverbSettings Settings
Detailed Description
FConvolutionReverb applies an impulse response to audio.
The audio pipeline within an FConvolutionReverb is described in ascii art here.
      +-----------+
      |Input Audio|
      +-----------+
            |
            v
      +------------+
      |Deinterleave|
      +------------+
            |
            v
+----------------------------+
|Mix Input Audio to IR Format|
+----------------------------+
            |
            v
    +-----------------+
    |Convolve with IRs|
    +-----------------+
            |
            v
+------------------------------—+ |Mix Reverb Audio to Output Format| +------------------------------—+ | v +-------—+ |Interleave| +-------—+ | v +---------—+ |Output Audio| +---------—+
Definition at line 142 of file ConvolutionReverb.h.
Member Typedef Documentation
FInputFormat
using Audio::FConvolutionReverb::FInputFormat = IChannelFormatConverter::FInputFormat private
Definition at line 180 of file ConvolutionReverb.h.
FOutputFormat
using Audio::FConvolutionReverb::FOutputFormat = IChannelFormatConverter::FOutputFormat private
Definition at line 181 of file ConvolutionReverb.h.
Constructor & Destructor Documentation
FConvolutionReverb() [1/4]
Audio::FConvolutionReverb::FConvolutionReverb () private delete
Referenced by FConvolutionReverb(), FConvolutionReverb(), and operator=().
FConvolutionReverb() [2/4]
Audio::FConvolutionReverb::FConvolutionReverb (const FConvolutionReverb &) private delete
References FConvolutionReverb().
FConvolutionReverb() [3/4]
Audio::FConvolutionReverb::FConvolutionReverb (const FConvolutionReverb &&) private delete
References FConvolutionReverb().
~FConvolutionReverb()
Audio::FConvolutionReverb::~FConvolutionReverb ()
FConvolutionReverb() [4/4]
Audio::FConvolutionReverb::FConvolutionReverb (TUniquePtr< IConvolutionAlgorithm > InAlgorithm, TUniquePtr< IChannelFormatConverter > InInputConverter, FChannelFormatConverterWrapper && InOutputConverter, const FConvolutionReverbSettings & InSettings) private
Member Function Documentation
CreateConvolutionReverb()
SYNTHESIS_API TUniquePtr< FConvolutionReverb > Audio::FConvolutionReverb::CreateConvolutionReverb (const FConvolutionReverbInitData & InInitData, const FConvolutionReverbSettings & InSettings = FConvolutionReverbSettings::DefaultSettings) static
References Audio::FConvolutionReverbSettings::DefaultSettings.
DeinterleaveBuffer()
SYNTHESIS_API void Audio::FConvolutionReverb::DeinterleaveBuffer (TArray< FAlignedFloatBuffer > & OutputBuffers, TArrayView< const float > InputBuffer, const int32 NumChannels) static
GetNumInputChannels()
SYNTHESIS_API int32 Audio::FConvolutionReverb::GetNumInputChannels () const
GetNumOutputChannels()
SYNTHESIS_API int32 Audio::FConvolutionReverb::GetNumOutputChannels () const
GetSettings()
SYNTHESIS_API const FConvolutionReverbSettings & Audio::FConvolutionReverb::GetSettings () const
InterleaveBuffer()
SYNTHESIS_API void Audio::FConvolutionReverb::InterleaveBuffer (FAlignedFloatBuffer & OutBuffer, const TArray< FAlignedFloatBuffer > & InputBuffers, const int32 NumChannels) static
operator=()
FConvolutionReverb & Audio::FConvolutionReverb::operator= (const FConvolutionReverb &) private delete
References FConvolutionReverb().
ProcessAudio() [1/2]
SYNTHESIS_API void Audio::FConvolutionReverb::ProcessAudio (int32 InNumInputChannels, const FAlignedFloatBuffer & InputAudio, int32 InNumOutputChannels, FAlignedFloatBuffer & OutputAudio)
ProcessAudio() [2/2]
SYNTHESIS_API void Audio::FConvolutionReverb::ProcessAudio (int32 InNumInputChannels, const float * InputAudio, int32 InNumOutputChannels, float * OutputAudio, const int32 InNumFrames)
ProcessAudioBlock()
void Audio::FConvolutionReverb::ProcessAudioBlock (const float * InputAudio, int32 InNumInputChannels, FAlignedFloatBuffer & OutputAudio, int32 InNumOutputChannels) private
ResizeArrayOfBuffers()
void Audio::FConvolutionReverb::ResizeArrayOfBuffers (TArray< FAlignedFloatBuffer > & InArrayOfBuffers, int32 MinNumBuffers, int32 NumFrames) const private
References NumFrames.
ResizeBlockBuffers()
void Audio::FConvolutionReverb::ResizeBlockBuffers () private
ResizeProcessingBuffers()
void Audio::FConvolutionReverb::ResizeProcessingBuffers () private
SetConvolutionAlgorithm()
void Audio::FConvolutionReverb::SetConvolutionAlgorithm (TUniquePtr< IConvolutionAlgorithm > InAlgorithm) private
SetSettings()
SYNTHESIS_API void Audio::FConvolutionReverb::SetSettings (const FConvolutionReverbSettings & InSettings)
Update()
void Audio::FConvolutionReverb::Update (bool bFadeToParams) private
Field Documentation
bIsConvertingInputChannelFormat
bool Audio::FConvolutionReverb::bIsConvertingInputChannelFormat private
Definition at line 263 of file ConvolutionReverb.h.
bIsConvertingOutputChannelFormat
bool Audio::FConvolutionReverb::bIsConvertingOutputChannelFormat private
Definition at line 264 of file ConvolutionReverb.h.
ConvolutionAlgorithm
TUniquePtr<IConvolutionAlgorithm> Audio::FConvolutionReverb::ConvolutionAlgorithm private
Definition at line 238 of file ConvolutionReverb.h.
ExpectedNumFramesPerCallback
int32 Audio::FConvolutionReverb::ExpectedNumFramesPerCallback private
Definition at line 258 of file ConvolutionReverb.h.
InputBlockBuffer
TUniquePtr<FAlignedBlockBuffer> Audio::FConvolutionReverb::InputBlockBuffer private
Definition at line 254 of file ConvolutionReverb.h.
InputBufferPtrs
TArray<float*> Audio::FConvolutionReverb::InputBufferPtrs private
Definition at line 251 of file ConvolutionReverb.h.
InputChannelConverterBuffers
TArray<FAlignedFloatBuffer> Audio::FConvolutionReverb::InputChannelConverterBuffers private
Definition at line 245 of file ConvolutionReverb.h.
InputChannelFormatConverter
TUniquePtr<IChannelFormatConverter> Audio::FConvolutionReverb::InputChannelFormatConverter private
Definition at line 239 of file ConvolutionReverb.h.
InputDeinterleaveBuffers
TArray<FAlignedFloatBuffer> Audio::FConvolutionReverb::InputDeinterleaveBuffers private
Definition at line 244 of file ConvolutionReverb.h.
InterleavedOutputBlock
FAlignedFloatBuffer Audio::FConvolutionReverb::InterleavedOutputBlock private
Definition at line 256 of file ConvolutionReverb.h.
NumInputSamplesPerBlock
int32 Audio::FConvolutionReverb::NumInputSamplesPerBlock private
Definition at line 259 of file ConvolutionReverb.h.
NumOutputSamplesPerBlock
int32 Audio::FConvolutionReverb::NumOutputSamplesPerBlock private
Definition at line 260 of file ConvolutionReverb.h.
OutputBlockBuffer
TUniquePtr<FAlignedBlockBuffer> Audio::FConvolutionReverb::OutputBlockBuffer private
Definition at line 255 of file ConvolutionReverb.h.
OutputBufferPtrs
TArray<float*> Audio::FConvolutionReverb::OutputBufferPtrs private
Definition at line 252 of file ConvolutionReverb.h.
OutputChannelConverterBuffers
TArray<FAlignedFloatBuffer> Audio::FConvolutionReverb::OutputChannelConverterBuffers private
Definition at line 249 of file ConvolutionReverb.h.
OutputChannelFormatConverter
FChannelFormatConverterWrapper Audio::FConvolutionReverb::OutputChannelFormatConverter private
Definition at line 241 of file ConvolutionReverb.h.
OutputDeinterleaveBuffers
TArray<FAlignedFloatBuffer> Audio::FConvolutionReverb::OutputDeinterleaveBuffers private
Definition at line 248 of file ConvolutionReverb.h.
OutputGain
float Audio::FConvolutionReverb::OutputGain private
Definition at line 262 of file ConvolutionReverb.h.
Settings
FConvolutionReverbSettings Audio::FConvolutionReverb::Settings private
Definition at line 236 of file ConvolutionReverb.h.
The documentation for this class was generated from the following file:
ConvolutionReverb.h