Unreal Engine 5.6 C++ API: TraceServices::TVariablePagedArray< InItemType > Class Template Reference
TraceServices::TVariablePagedArray< InItemType > Class Template Reference
#include "VariablePagedArray.h"
Public Types
typedef InItemType ItemType
typedef TVariablePagedArrayPageGroup< InItemType > PageGroupType
typedef TVariablePagedArrayPage< InItemType > PageType
typedef TVariablePagedArrayIterator< InItemType > TIterator
Public Member Functions
TVariablePagedArray (ILinearAllocator &InAllocator, uint64 InPageSize)
~TVariablePagedArray ()
ItemType & First ()
const ItemType & First () const
TIterator GetIterator () const
TIterator GetIteratorFromItem (uint64 ItemIndex) const
uint64 GetPageSize () const
ItemType & Insert (uint64 Index)
ItemType & Last ()
const ItemType & Last () const
uint64 Num () const
uint64 NumItemsWasted () const
uint64 NumPages () const
ItemType & operator[] (uint64 Index)
const ItemType & operator[] (uint64 Index) const
ItemType & PushBack ()
double WastedPercent () const
Private Member Functions
void CheckIntegrity () const
void CreateInitialPage ()
void FindItemChecked (const uint64 Index, const PageType *&OutPage, uint64 &OutItemIndexInPage) const
void OnInsertedItem (const uint64 PageGroupIndex)
void OnInsertedPage (const uint64 PageGroupIndex)
ItemType & PushBackItemInPageGroup (const uint64 PageGroupIndex)
Private Attributes
ILinearAllocator & Allocator
PageType * FirstPage
PageGroupType * FirstPageGroup
PageType * LastPage
PageGroupType * LastPageGroup
TArray< PageGroupType > PageGroups
TArray< PageType > Pages
uint64 PageSize
uint64 TotalItemCount
Friends
template<typename ItemType>
class TVariablePagedArrayIterator
Detailed Description
template<typename InItemType>
class TraceServices::TVariablePagedArray< InItemType >
Definition at line 339 of file VariablePagedArray.h.
Member Typedef Documentation
ItemType
template<typename InItemType> typedef InItemType TraceServices::TVariablePagedArray< InItemType >::ItemType
Definition at line 342 of file VariablePagedArray.h.
PageGroupType
template<typename InItemType> typedef TVariablePagedArrayPageGroup<InItemType> TraceServices::TVariablePagedArray< InItemType >::PageGroupType
Definition at line 344 of file VariablePagedArray.h.
PageType
template<typename InItemType> typedef TVariablePagedArrayPage<InItemType> TraceServices::TVariablePagedArray< InItemType >::PageType
Definition at line 343 of file VariablePagedArray.h.
TIterator
template<typename InItemType> typedef TVariablePagedArrayIterator<InItemType> TraceServices::TVariablePagedArray< InItemType >::TIterator
Definition at line 345 of file VariablePagedArray.h.
Constructor & Destructor Documentation
TVariablePagedArray()
template<typename InItemType> TraceServices::TVariablePagedArray< InItemType >::TVariablePagedArray (ILinearAllocator & InAllocator, uint64 InPageSize) inline
Definition at line 347 of file VariablePagedArray.h.
~TVariablePagedArray()
template<typename InItemType> TraceServices::TVariablePagedArray< InItemType >::~TVariablePagedArray () inline
Definition at line 360 of file VariablePagedArray.h.
Member Function Documentation
CheckIntegrity()
template<typename InItemType> void TraceServices::TVariablePagedArray< InItemType >::CheckIntegrity () const inline private
Definition at line 715 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArray< ItemType >::Insert().
CreateInitialPage()
template<typename InItemType> void TraceServices::TVariablePagedArray< InItemType >::CreateInitialPage () inline private
Definition at line 640 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArray< ItemType >::PushBack().
FindItemChecked()
template<typename InItemType> void TraceServices::TVariablePagedArray< InItemType >::FindItemChecked (const uint64 Index, const PageType *& OutPage, uint64 & OutItemIndexInPage) const inline private
Definition at line 609 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArray< ItemType >::operator[]().
First() [1/2]
template<typename InItemType> ItemType & TraceServices::TVariablePagedArray< InItemType >::First () inline
Definition at line 584 of file VariablePagedArray.h.
First() [2/2]
template<typename InItemType> const ItemType & TraceServices::TVariablePagedArray< InItemType >::First () const inline
Definition at line 590 of file VariablePagedArray.h.
GetIterator()
template<typename InItemType> TIterator TraceServices::TVariablePagedArray< InItemType >::GetIterator () const inline
Definition at line 560 of file VariablePagedArray.h.
GetIteratorFromItem()
template<typename InItemType> TIterator TraceServices::TVariablePagedArray< InItemType >::GetIteratorFromItem (uint64 ItemIndex) const inline
Definition at line 565 of file VariablePagedArray.h.
GetPageSize()
template<typename InItemType> uint64 TraceServices::TVariablePagedArray< InItemType >::GetPageSize () const inline
Definition at line 378 of file VariablePagedArray.h.
Insert()
template<typename InItemType> ItemType & TraceServices::TVariablePagedArray< InItemType >::Insert (uint64 Index) inline
Definition at line 427 of file VariablePagedArray.h.
Last() [1/2]
template<typename InItemType> ItemType & TraceServices::TVariablePagedArray< InItemType >::Last () inline
Definition at line 596 of file VariablePagedArray.h.
Last() [2/2]
template<typename InItemType> const ItemType & TraceServices::TVariablePagedArray< InItemType >::Last () const inline
Definition at line 602 of file VariablePagedArray.h.
Num()
template<typename InItemType> uint64 TraceServices::TVariablePagedArray< InItemType >::Num () const inline
Definition at line 373 of file VariablePagedArray.h.
NumItemsWasted()
template<typename InItemType> uint64 TraceServices::TVariablePagedArray< InItemType >::NumItemsWasted () const inline
Definition at line 388 of file VariablePagedArray.h.
NumPages()
template<typename InItemType> uint64 TraceServices::TVariablePagedArray< InItemType >::NumPages () const inline
Definition at line 383 of file VariablePagedArray.h.
OnInsertedItem()
template<typename InItemType> void TraceServices::TVariablePagedArray< InItemType >::OnInsertedItem (const uint64 PageGroupIndex) inline private
Definition at line 699 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArray< ItemType >::Insert(), and TraceServices::TVariablePagedArray< ItemType >::PushBackItemInPageGroup().
OnInsertedPage()
template<typename InItemType> void TraceServices::TVariablePagedArray< InItemType >::OnInsertedPage (const uint64 PageGroupIndex) inline private
Definition at line 681 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArray< ItemType >::Insert(), and TraceServices::TVariablePagedArray< ItemType >::PushBackItemInPageGroup().
operator[]() [1/2]
template<typename InItemType> ItemType & TraceServices::TVariablePagedArray< InItemType >::operator[] (uint64 Index) inline
Definition at line 570 of file VariablePagedArray.h.
operator[]() [2/2]
template<typename InItemType> const ItemType & TraceServices::TVariablePagedArray< InItemType >::operator[] (uint64 Index) const inline
Definition at line 579 of file VariablePagedArray.h.
PushBack()
template<typename InItemType> ItemType & TraceServices::TVariablePagedArray< InItemType >::PushBack () inline
Definition at line 400 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArray< ItemType >::Insert().
PushBackItemInPageGroup()
template<typename InItemType> ItemType & TraceServices::TVariablePagedArray< InItemType >::PushBackItemInPageGroup (const uint64 PageGroupIndex) inline private
Definition at line 657 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArray< ItemType >::Insert().
WastedPercent()
template<typename InItemType> double TraceServices::TVariablePagedArray< InItemType >::WastedPercent () const inline
Definition at line 394 of file VariablePagedArray.h.
Friends And Related Symbol Documentation
TVariablePagedArrayIterator
template<typename InItemType> template<typename ItemType> friend class TVariablePagedArrayIterator friend
Definition at line 777 of file VariablePagedArray.h.
Field Documentation
Allocator
template<typename InItemType> ILinearAllocator& TraceServices::TVariablePagedArray< InItemType >::Allocator private
Definition at line 779 of file VariablePagedArray.h.
FirstPage
template<typename InItemType> PageType* TraceServices::TVariablePagedArray< InItemType >::FirstPage private
Definition at line 782 of file VariablePagedArray.h.
FirstPageGroup
template<typename InItemType> PageGroupType* TraceServices::TVariablePagedArray< InItemType >::FirstPageGroup private
Definition at line 786 of file VariablePagedArray.h.
LastPage
template<typename InItemType> PageType* TraceServices::TVariablePagedArray< InItemType >::LastPage private
Definition at line 783 of file VariablePagedArray.h.
LastPageGroup
template<typename InItemType> PageGroupType* TraceServices::TVariablePagedArray< InItemType >::LastPageGroup private
Definition at line 787 of file VariablePagedArray.h.
PageGroups
template<typename InItemType> TArray<PageGroupType> TraceServices::TVariablePagedArray< InItemType >::PageGroups private
Definition at line 785 of file VariablePagedArray.h.
Pages
template<typename InItemType> TArray<PageType> TraceServices::TVariablePagedArray< InItemType >::Pages private
Definition at line 781 of file VariablePagedArray.h.
PageSize
template<typename InItemType> uint64 TraceServices::TVariablePagedArray< InItemType >::PageSize private
Definition at line 789 of file VariablePagedArray.h.
TotalItemCount
template<typename InItemType> uint64 TraceServices::TVariablePagedArray< InItemType >::TotalItemCount private
Definition at line 790 of file VariablePagedArray.h.
The documentation for this class was generated from the following file:
VariablePagedArray.h