Unreal Engine 5.6 C++ API: FLightWeightInstanceSubsystem Struct Reference
FLightWeightInstanceSubsystem Struct Reference
#include "LightWeightInstanceSubsystem.h"
Public Member Functions
FLightWeightInstanceSubsystem ()
~FLightWeightInstanceSubsystem ()
bool AddManager (ALightWeightInstanceManager *Manager)
FActorInstanceHandle CreateNewLightWeightInstance (UClass *ActorClass, FLWIData *InitData, UDataLayerInstance *Layer, UWorld *World)
void DeleteInstance (const FActorInstanceHandle &Handle)
ALightWeightInstanceManager * FindLightWeightInstanceManager (const FActorInstanceHandle &Handle) const
ALightWeightInstanceManager * FindLightWeightInstanceManager (UClass &ActorClass, UWorld &World, const FVector &InPos, const UDataLayerInstance *DataLayer=nullptr) const
ALightWeightInstanceManager * FindOrAddLightWeightInstanceManager (UClass &ActorClass, UWorld &World, const FVector &InPos, const UDataLayerInstance *DataLayer=nullptr)
AActor * GetActor_NoCreate (const FActorInstanceHandle &Handle) const
UClass * GetActorClass (const FActorInstanceHandle &Handle)
ULevel * GetLevel (const FActorInstanceHandle &Handle)
FVector GetLocation (const FActorInstanceHandle &Handle)
FString GetName (const FActorInstanceHandle &Handle)
bool IsInLevel (const FActorInstanceHandle &Handle, const ULevel *InLevel)
bool RemoveManager (ALightWeightInstanceManager *Manager)
UE_DEPRECATED (5.3, "Use LWI Managers version of ConvertPositionToCoord()") static 1 FInt32Vector3 ConvertPositionToCoord(const FVector &InPosition)
UE_DEPRECATED (5.3, "Use the version that takes in a position.") 1 ALightWeightInstanceManager *FindLightWeightInstanceManager(UClass *ActorClass
UE_DEPRECATED (5.3, "Use the version that takes in a position.") 1 ALightWeightInstanceManager *FindOrAddLightWeightInstanceManager(UClass *ActorClass
Static Public Member Functions
static FLightWeightInstanceSubsystem & Get ()
Data Fields
const UDataLayerInstance UWorld *World const
const UDataLayerInstance * DataLayer
const UDataLayerInstance * Layer
const UDataLayerInstance UWorld * World
Protected Member Functions
UClass * FindBestInstanceManagerClass (const UClass *ActorClass)
const ALightWeightInstanceManager * GetManagerAt (int32 Index) const
int32 GetManagerIndex (const ALightWeightInstanceManager *Manager) const
Private Attributes
FTransactionallySafeRWLock LWIManagersRWLock
TArray< ALightWeightInstanceManager * > LWInstanceManagers
FDelegateHandle OnLevelActorAddedHandle
FDelegateHandle OnLevelActorDeletedHandle
Detailed Description
Definition at line 15 of file LightWeightInstanceSubsystem.h.
Constructor & Destructor Documentation
FLightWeightInstanceSubsystem()
FLightWeightInstanceSubsystem::FLightWeightInstanceSubsystem ()
Referenced by Get().
~FLightWeightInstanceSubsystem()
FLightWeightInstanceSubsystem::~FLightWeightInstanceSubsystem ()
Member Function Documentation
AddManager()
bool FLightWeightInstanceSubsystem::AddManager (ALightWeightInstanceManager * Manager)
References AddManager().
Referenced by AddManager().
CreateNewLightWeightInstance()
FActorInstanceHandle FLightWeightInstanceSubsystem::CreateNewLightWeightInstance (UClass * ActorClass, FLWIData * InitData, UDataLayerInstance * Layer, UWorld * World)
References CreateNewLightWeightInstance(), Layer, and World.
Referenced by CreateNewLightWeightInstance().
DeleteInstance()
void FLightWeightInstanceSubsystem::DeleteInstance (const FActorInstanceHandle & Handle)
References const, DeleteInstance(), and Handle.
Referenced by DeleteInstance().
FindBestInstanceManagerClass()
UClass * FLightWeightInstanceSubsystem::FindBestInstanceManagerClass (const UClass * ActorClass) protected
References const, and FindBestInstanceManagerClass().
Referenced by FindBestInstanceManagerClass().
FindLightWeightInstanceManager() [1/2]
ALightWeightInstanceManager * FLightWeightInstanceSubsystem::FindLightWeightInstanceManager (const FActorInstanceHandle & Handle) const
References Handle.
Referenced by FindLightWeightInstanceManager().
FindLightWeightInstanceManager() [2/2]
ALightWeightInstanceManager * FLightWeightInstanceSubsystem::FindLightWeightInstanceManager (UClass & ActorClass, UWorld & World, const FVector & InPos, const UDataLayerInstance * DataLayer = nullptr) const
References const, DataLayer, FindLightWeightInstanceManager(), FVector, and World.
FindOrAddLightWeightInstanceManager()
ALightWeightInstanceManager * FLightWeightInstanceSubsystem::FindOrAddLightWeightInstanceManager (UClass & ActorClass, UWorld & World, const FVector & InPos, const UDataLayerInstance * DataLayer = nullptr)
References const, DataLayer, FindOrAddLightWeightInstanceManager(), FVector, and World.
Referenced by FindOrAddLightWeightInstanceManager().
Get()
FLightWeightInstanceSubsystem & FLightWeightInstanceSubsystem::Get () inline static
Definition at line 17 of file LightWeightInstanceSubsystem.h.
References FLightWeightInstanceSubsystem(), and MakeShareable().
GetActor_NoCreate()
AActor * FLightWeightInstanceSubsystem::GetActor_NoCreate (const FActorInstanceHandle & Handle) const
References const, GetActor_NoCreate(), and Handle.
Referenced by GetActor_NoCreate().
GetActorClass()
UClass * FLightWeightInstanceSubsystem::GetActorClass (const FActorInstanceHandle & Handle)
References const, GetActorClass(), and Handle.
Referenced by GetActorClass().
GetLevel()
ULevel * FLightWeightInstanceSubsystem::GetLevel (const FActorInstanceHandle & Handle)
References const, GetLevel(), and Handle.
Referenced by GetLevel().
GetLocation()
FVector FLightWeightInstanceSubsystem::GetLocation (const FActorInstanceHandle & Handle)
References const, FVector, GetLocation(), and Handle.
Referenced by GetLocation().
GetManagerAt()
const ALightWeightInstanceManager * FLightWeightInstanceSubsystem::GetManagerAt (int32 Index) const protected
References const, and GetManagerAt().
Referenced by GetManagerAt().
GetManagerIndex()
int32 FLightWeightInstanceSubsystem::GetManagerIndex (const ALightWeightInstanceManager * Manager) const protected
References const, and GetManagerIndex().
Referenced by GetManagerIndex().
GetName()
FString FLightWeightInstanceSubsystem::GetName (const FActorInstanceHandle & Handle)
References const, GetName(), and Handle.
Referenced by GetName().
IsInLevel()
bool FLightWeightInstanceSubsystem::IsInLevel (const FActorInstanceHandle & Handle, const ULevel * InLevel)
References const, Handle, and IsInLevel().
Referenced by IsInLevel().
RemoveManager()
bool FLightWeightInstanceSubsystem::RemoveManager (ALightWeightInstanceManager * Manager)
References RemoveManager().
Referenced by RemoveManager().
UE_DEPRECATED() [1/3]
FLightWeightInstanceSubsystem::UE_DEPRECATED (5. 3, "Use LWI Managers version of ConvertPositionToCoord()") const &
References const, FVector, and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FLightWeightInstanceSubsystem::UE_DEPRECATED (5. 3, "Use the version that takes in a position.")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FLightWeightInstanceSubsystem::UE_DEPRECATED (5. 3, "Use the version that takes in a position.")
References UE_DEPRECATED().
Field Documentation
const
const UDataLayerInstance UWorld* World FLightWeightInstanceSubsystem::const
Definition at line 34 of file LightWeightInstanceSubsystem.h.
Referenced by DeleteInstance(), FindBestInstanceManagerClass(), FindLightWeightInstanceManager(), FindOrAddLightWeightInstanceManager(), GetActor_NoCreate(), GetActorClass(), GetLevel(), GetLocation(), GetManagerAt(), GetManagerIndex(), GetName(), IsInLevel(), and UE_DEPRECATED().
DataLayer
const UDataLayerInstance* FLightWeightInstanceSubsystem::DataLayer
Definition at line 38 of file LightWeightInstanceSubsystem.h.
Referenced by FindLightWeightInstanceManager(), and FindOrAddLightWeightInstanceManager().
Layer
const UDataLayerInstance* FLightWeightInstanceSubsystem::Layer
Definition at line 34 of file LightWeightInstanceSubsystem.h.
Referenced by CreateNewLightWeightInstance().
LWIManagersRWLock
FTransactionallySafeRWLock FLightWeightInstanceSubsystem::LWIManagersRWLock mutable private
Definition at line 92 of file LightWeightInstanceSubsystem.h.
LWInstanceManagers
TArray<ALightWeightInstanceManager*> FLightWeightInstanceSubsystem::LWInstanceManagers private
Definition at line 89 of file LightWeightInstanceSubsystem.h.
OnLevelActorAddedHandle
FDelegateHandle FLightWeightInstanceSubsystem::OnLevelActorAddedHandle private
Definition at line 96 of file LightWeightInstanceSubsystem.h.
OnLevelActorDeletedHandle
FDelegateHandle FLightWeightInstanceSubsystem::OnLevelActorDeletedHandle private
Definition at line 97 of file LightWeightInstanceSubsystem.h.
World
const UDataLayerInstance UWorld* FLightWeightInstanceSubsystem::World
Definition at line 38 of file LightWeightInstanceSubsystem.h.
Referenced by CreateNewLightWeightInstance(), FindLightWeightInstanceManager(), and FindOrAddLightWeightInstanceManager().
The documentation for this struct was generated from the following file:
LightWeightInstanceSubsystem.h