Unreal Engine 5.6 C++ API: Verse::Names Namespace Reference
Verse::Names Namespace Reference
Namespaces
namespace Private
Functions
FString AddVerseDeadPrefix (FStringView Name)
template<typename CharType>
const CharType * GetAssetsSubPath ()
template<>
FORCEINLINE const TCHAR * GetAssetsSubPath< TCHAR > ()
template<>
FORCEINLINE const UTF8CHAR * GetAssetsSubPath< UTF8CHAR > ()
template<typename CharType>
const CharType * GetAssetsSubPathForPackageName ()
template<>
FORCEINLINE const TCHAR * GetAssetsSubPathForPackageName< TCHAR > ()
template<>
FORCEINLINE const UTF8CHAR * GetAssetsSubPathForPackageName< UTF8CHAR > ()
template TStringBuilder< DefaultNameLength > GetDecoratedName (FStringView Path, FStringView Module, FStringView Name)
template TStringBuilder< DefaultNameLength > GetDecoratedName (FStringView Path, FStringView Name)
template TUtf8StringBuilder< DefaultNameLength > GetDecoratedName (FUtf8StringView Path, FUtf8StringView Module, FUtf8StringView Name)
template TUtf8StringBuilder< DefaultNameLength > GetDecoratedName (FUtf8StringView Path, FUtf8StringView Name)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetDecoratedName (TStringView< CharType > Path, TStringView< CharType > Module, TStringView< CharType > Name)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetDecoratedName (TStringView< CharType > Path, TStringView< CharType > Name)
template<typename CharType>
const CharType * GetPublishedPackageNameSuffix ()
template<>
FORCEINLINE const TCHAR * GetPublishedPackageNameSuffix< TCHAR > ()
template<>
FORCEINLINE const UTF8CHAR * GetPublishedPackageNameSuffix< UTF8CHAR > ()
template TStringBuilder< DefaultNameLength > GetUPackagePath (FStringView VersePackageName, EVersePackageType *OutPackageType)
template TUtf8StringBuilder< DefaultNameLength > GetUPackagePath (FUtf8StringView VersePackageName, EVersePackageType *OutPackageType)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetUPackagePath (TStringView< CharType > VersePackageName, EVersePackageType *OutPackageType=nullptr)
template TStringBuilder< DefaultNameLength > GetUPackagePathForAssets (FStringView MountPointName)
template TUtf8StringBuilder< DefaultNameLength > GetUPackagePathForAssets (FUtf8StringView MountPointName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetUPackagePathForAssets (TStringView< CharType > MountPointName)
template TStringBuilder< DefaultNameLength > GetUPackagePathForContent (FStringView MountPointName)
template TUtf8StringBuilder< DefaultNameLength > GetUPackagePathForContent (FUtf8StringView MountPointName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetUPackagePathForContent (TStringView< CharType > MountPointName)
template TStringBuilder< DefaultNameLength > GetUPackagePathForVni (FStringView MountPointName, FStringView CppModuleName)
template TUtf8StringBuilder< DefaultNameLength > GetUPackagePathForVni (FUtf8StringView MountPointName, FUtf8StringView CppModuleName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetUPackagePathForVni (TStringView< CharType > MountPointName, TStringView< CharType > CppModuleName)
FStringView GetVerseDeadPrefix ()
template TStringBuilder< DefaultNameLength > GetVersePackageDirForAssets (FStringView MountPointName)
template TUtf8StringBuilder< DefaultNameLength > GetVersePackageDirForAssets (FUtf8StringView MountPointName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetVersePackageDirForAssets (TStringView< CharType > MountPointName)
template TStringBuilder< DefaultNameLength > GetVersePackageDirForContent (FStringView MountPointName)
template TUtf8StringBuilder< DefaultNameLength > GetVersePackageDirForContent (FUtf8StringView MountPointName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetVersePackageDirForContent (TStringView< CharType > MountPointName)
template TStringBuilder< DefaultNameLength > GetVersePackageNameForAssets (FStringView MountPointName)
template TUtf8StringBuilder< DefaultNameLength > GetVersePackageNameForAssets (FUtf8StringView MountPointName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetVersePackageNameForAssets (TStringView< CharType > MountPointName)
template TStringBuilder< DefaultNameLength > GetVersePackageNameForContent (FStringView MountPointName)
template TUtf8StringBuilder< DefaultNameLength > GetVersePackageNameForContent (FUtf8StringView MountPointName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetVersePackageNameForContent (TStringView< CharType > MountPointName)
template TStringBuilder< DefaultNameLength > GetVersePackageNameForPublishedContent (FStringView MountPointName)
template TUtf8StringBuilder< DefaultNameLength > GetVersePackageNameForPublishedContent (FUtf8StringView MountPointName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetVersePackageNameForPublishedContent (TStringView< CharType > MountPointName)
template TStringBuilder< DefaultNameLength > GetVersePackageNameForVni (FStringView MountPointName, FStringView CppModuleName)
template TUtf8StringBuilder< DefaultNameLength > GetVersePackageNameForVni (FUtf8StringView MountPointName, FUtf8StringView CppModuleName)
template<typename CharType>
TStringBuilderWithBuffer< CharType, DefaultNameLength > GetVersePackageNameForVni (TStringView< CharType > MountPointName, TStringView< CharType > CppModuleName)
template<typename CharType>
const CharType * GetVerseSubPath ()
template<>
FORCEINLINE const TCHAR * GetVerseSubPath< TCHAR > ()
template<>
FORCEINLINE const UTF8CHAR * GetVerseSubPath< UTF8CHAR > ()
template<typename CharType>
const CharType * GetVniSubPath ()
template<>
FORCEINLINE const TCHAR * GetVniSubPath< TCHAR > ()
template<>
FORCEINLINE const UTF8CHAR * GetVniSubPath< UTF8CHAR > ()
bool HasVerseDeadPrefix (FStringView Name)
bool IsFullPath (FStringView Name)
bool IsFullPath (FUtf8StringView Name)
void MakeTypeDead (UObject *Object, UObject *NewOuter)
FStringView RemoveQualifier (FStringView QualifiedName)
FUtf8StringView RemoveQualifier (FUtf8StringView QualifiedName)
FStringView RemoveVerseDeadPrefix (FStringView Name)
FString UEFuncToVerseName (FName UEName)
FString UEFuncToVerseName (FStringView UEName)
FName UEPropToVerseFName (FName UEName, bool *bIsVerseName=nullptr)
FName UEPropToVerseFName (FStringView UEName, bool *bIsVerseName=nullptr)
FString UEPropToVerseName (FName UEName, bool *bIsVerseName=nullptr)
FString UEPropToVerseName (FStringView UEName, bool *bIsVerseName=nullptr)
FName VerseFuncToUEFName (FStringView VerseName)
FString VerseFuncToUEName (FStringView VerseName)
FName VersePropToUEFName (FStringView VerseName, bool *bWasVerseName=nullptr)
FName VersePropToUEFName (FStringView VerseName, FStringView CrcVerseName, bool *bWasVerseName=nullptr)
FString VersePropToUEName (FStringView VerseName, bool *bWasVerseName=nullptr)
FString VersePropToUEName (FStringView VerseName, FStringView CrcVerseName, bool *bWasVerseName=nullptr)
Variables
static constexpr int32 DefaultNameLength = 64
Function Documentation
AddVerseDeadPrefix()
FString Verse::Names::AddVerseDeadPrefix (FStringView Name)
References Name.
GetAssetsSubPath()
template<typename CharType> const CharType * Verse::Names::GetAssetsSubPath ()
References UE_MAKE_CONSTANT_STRING_METHODS.
GetAssetsSubPath< TCHAR >()
template<> FORCEINLINE const TCHAR * Verse::Names::GetAssetsSubPath< TCHAR > ()
Definition at line 64 of file VVMNames.h.
GetAssetsSubPath< UTF8CHAR >()
template<> FORCEINLINE const UTF8CHAR * Verse::Names::GetAssetsSubPath< UTF8CHAR > ()
Definition at line 64 of file VVMNames.h.
GetAssetsSubPathForPackageName()
template<typename CharType> const CharType * Verse::Names::GetAssetsSubPathForPackageName ()
References UE_MAKE_CONSTANT_STRING_METHODS.
GetAssetsSubPathForPackageName< TCHAR >()
template<> FORCEINLINE const TCHAR * Verse::Names::GetAssetsSubPathForPackageName< TCHAR > ()
Definition at line 65 of file VVMNames.h.
GetAssetsSubPathForPackageName< UTF8CHAR >()
template<> FORCEINLINE const UTF8CHAR * Verse::Names::GetAssetsSubPathForPackageName< UTF8CHAR > ()
Definition at line 65 of file VVMNames.h.
GetDecoratedName() [1/6]
template TStringBuilder< DefaultNameLength > Verse::Names::GetDecoratedName (FStringView Path, FStringView Module, FStringView Name) extern
References Name, and Path.
GetDecoratedName() [2/6]
template TStringBuilder< DefaultNameLength > Verse::Names::GetDecoratedName (FStringView Path, FStringView Name) extern
References Name, and Path.
GetDecoratedName() [3/6]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetDecoratedName (FUtf8StringView Path, FUtf8StringView Module, FUtf8StringView Name) extern
References Name, and Path.
GetDecoratedName() [4/6]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetDecoratedName (FUtf8StringView Path, FUtf8StringView Name) extern
References Name, and Path.
GetDecoratedName() [5/6]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetDecoratedName (TStringView< CharType > Path, TStringView< CharType > Module, TStringView< CharType > Name)
References Name, and Path.
GetDecoratedName() [6/6]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetDecoratedName (TStringView< CharType > Path, TStringView< CharType > Name)
References Name, and Path.
GetPublishedPackageNameSuffix()
template<typename CharType> const CharType * Verse::Names::GetPublishedPackageNameSuffix ()
References UE_MAKE_CONSTANT_STRING_METHODS.
GetPublishedPackageNameSuffix< TCHAR >()
template<> FORCEINLINE const TCHAR * Verse::Names::GetPublishedPackageNameSuffix< TCHAR > ()
Definition at line 66 of file VVMNames.h.
GetPublishedPackageNameSuffix< UTF8CHAR >()
template<> FORCEINLINE const UTF8CHAR * Verse::Names::GetPublishedPackageNameSuffix< UTF8CHAR > ()
Definition at line 66 of file VVMNames.h.
GetUPackagePath() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetUPackagePath (FStringView VersePackageName, EVersePackageType * OutPackageType) extern
GetUPackagePath() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetUPackagePath (FUtf8StringView VersePackageName, EVersePackageType * OutPackageType) extern
GetUPackagePath() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetUPackagePath (TStringView< CharType > VersePackageName, EVersePackageType * OutPackageType = nullptr)
GetUPackagePathForAssets() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetUPackagePathForAssets (FStringView MountPointName) extern
GetUPackagePathForAssets() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetUPackagePathForAssets (FUtf8StringView MountPointName) extern
GetUPackagePathForAssets() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetUPackagePathForAssets (TStringView< CharType > MountPointName)
GetUPackagePathForContent() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetUPackagePathForContent (FStringView MountPointName) extern
GetUPackagePathForContent() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetUPackagePathForContent (FUtf8StringView MountPointName) extern
GetUPackagePathForContent() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetUPackagePathForContent (TStringView< CharType > MountPointName)
GetUPackagePathForVni() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetUPackagePathForVni (FStringView MountPointName, FStringView CppModuleName) extern
GetUPackagePathForVni() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetUPackagePathForVni (FUtf8StringView MountPointName, FUtf8StringView CppModuleName) extern
GetUPackagePathForVni() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetUPackagePathForVni (TStringView< CharType > MountPointName, TStringView< CharType > CppModuleName)
GetVerseDeadPrefix()
FStringView Verse::Names::GetVerseDeadPrefix ()
GetVersePackageDirForAssets() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetVersePackageDirForAssets (FStringView MountPointName) extern
GetVersePackageDirForAssets() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetVersePackageDirForAssets (FUtf8StringView MountPointName) extern
GetVersePackageDirForAssets() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetVersePackageDirForAssets (TStringView< CharType > MountPointName)
GetVersePackageDirForContent() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetVersePackageDirForContent (FStringView MountPointName) extern
GetVersePackageDirForContent() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetVersePackageDirForContent (FUtf8StringView MountPointName) extern
GetVersePackageDirForContent() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetVersePackageDirForContent (TStringView< CharType > MountPointName)
GetVersePackageNameForAssets() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForAssets (FStringView MountPointName) extern
GetVersePackageNameForAssets() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForAssets (FUtf8StringView MountPointName) extern
GetVersePackageNameForAssets() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetVersePackageNameForAssets (TStringView< CharType > MountPointName)
GetVersePackageNameForContent() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForContent (FStringView MountPointName) extern
GetVersePackageNameForContent() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForContent (FUtf8StringView MountPointName) extern
GetVersePackageNameForContent() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetVersePackageNameForContent (TStringView< CharType > MountPointName)
GetVersePackageNameForPublishedContent() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForPublishedContent (FStringView MountPointName) extern
GetVersePackageNameForPublishedContent() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForPublishedContent (FUtf8StringView MountPointName) extern
GetVersePackageNameForPublishedContent() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetVersePackageNameForPublishedContent (TStringView< CharType > MountPointName)
GetVersePackageNameForVni() [1/3]
template TStringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForVni (FStringView MountPointName, FStringView CppModuleName) extern
GetVersePackageNameForVni() [2/3]
template TUtf8StringBuilder< DefaultNameLength > Verse::Names::GetVersePackageNameForVni (FUtf8StringView MountPointName, FUtf8StringView CppModuleName) extern
GetVersePackageNameForVni() [3/3]
template<typename CharType> TStringBuilderWithBuffer< CharType, DefaultNameLength > Verse::Names::GetVersePackageNameForVni (TStringView< CharType > MountPointName, TStringView< CharType > CppModuleName)
GetVerseSubPath()
template<typename CharType> const CharType * Verse::Names::GetVerseSubPath ()
GetVerseSubPath< TCHAR >()
template<> FORCEINLINE const TCHAR * Verse::Names::GetVerseSubPath< TCHAR > ()
Definition at line 62 of file VVMNames.h.
GetVerseSubPath< UTF8CHAR >()
template<> FORCEINLINE const UTF8CHAR * Verse::Names::GetVerseSubPath< UTF8CHAR > ()
Definition at line 62 of file VVMNames.h.
GetVniSubPath()
template<typename CharType> const CharType * Verse::Names::GetVniSubPath ()
References UE_MAKE_CONSTANT_STRING_METHODS.
GetVniSubPath< TCHAR >()
template<> FORCEINLINE const TCHAR * Verse::Names::GetVniSubPath< TCHAR > ()
Definition at line 63 of file VVMNames.h.
GetVniSubPath< UTF8CHAR >()
template<> FORCEINLINE const UTF8CHAR * Verse::Names::GetVniSubPath< UTF8CHAR > ()
Definition at line 63 of file VVMNames.h.
HasVerseDeadPrefix()
bool Verse::Names::HasVerseDeadPrefix (FStringView Name)
References Name.
IsFullPath() [1/2]
bool Verse::Names::IsFullPath (FStringView Name) inline
Definition at line 145 of file VVMNames.h.
References Name.
IsFullPath() [2/2]
bool Verse::Names::IsFullPath (FUtf8StringView Name) inline
Definition at line 141 of file VVMNames.h.
References Name.
MakeTypeDead()
void Verse::Names::MakeTypeDead (UObject * Object, UObject * NewOuter)
References Object.
RemoveQualifier() [1/2]
FStringView Verse::Names::RemoveQualifier (FStringView QualifiedName) inline
Definition at line 158 of file VVMNames.h.
References TStringView< CharType >::FindChar(), and TStringView< CharType >::RemovePrefix().
RemoveQualifier() [2/2]
FUtf8StringView Verse::Names::RemoveQualifier (FUtf8StringView QualifiedName) inline
Definition at line 149 of file VVMNames.h.
References TStringView< CharType >::FindChar(), and TStringView< CharType >::RemovePrefix().
RemoveVerseDeadPrefix()
FStringView Verse::Names::RemoveVerseDeadPrefix (FStringView Name)
References Name.
UEFuncToVerseName() [1/2]
FString Verse::Names::UEFuncToVerseName (FName UEName)
UEFuncToVerseName() [2/2]
FString Verse::Names::UEFuncToVerseName (FStringView UEName)
UEPropToVerseFName() [1/2]
FName Verse::Names::UEPropToVerseFName (FName UEName, bool * bIsVerseName = nullptr)
UEPropToVerseFName() [2/2]
FName Verse::Names::UEPropToVerseFName (FStringView UEName, bool * bIsVerseName = nullptr)
UEPropToVerseName() [1/2]
FString Verse::Names::UEPropToVerseName (FName UEName, bool * bIsVerseName = nullptr)
UEPropToVerseName() [2/2]
FString Verse::Names::UEPropToVerseName (FStringView UEName, bool * bIsVerseName = nullptr)
VerseFuncToUEFName()
FName Verse::Names::VerseFuncToUEFName (FStringView VerseName)
VerseFuncToUEName()
FString Verse::Names::VerseFuncToUEName (FStringView VerseName)
VersePropToUEFName() [1/2]
FName Verse::Names::VersePropToUEFName (FStringView VerseName, bool * bWasVerseName = nullptr)
VersePropToUEFName() [2/2]
FName Verse::Names::VersePropToUEFName (FStringView VerseName, FStringView CrcVerseName, bool * bWasVerseName = nullptr)
VersePropToUEName() [1/2]
FString Verse::Names::VersePropToUEName (FStringView VerseName, bool * bWasVerseName = nullptr)
VersePropToUEName() [2/2]
FString Verse::Names::VersePropToUEName (FStringView VerseName, FStringView CrcVerseName, bool * bWasVerseName = nullptr)
Variable Documentation
DefaultNameLength
int32 Verse::Names::DefaultNameLength = 64 static constexpr
Definition at line 12 of file VVMNames.h.