Unreal Engine 5.6 C++ API: SNumericEntryBox< NumericType > Class Template Reference
SNumericEntryBox< NumericType > Class Template Reference
Implementation for a box that only accepts a numeric value or that can display an undetermined value via a string Supports an optional spin box for manipulating a value by dragging with the mouse Supports an optional label inset in the text box.
#include "SNumericEntryBox.h"
Public Types
enum class ELabelLocation { Outside , Inside }
Public Member Functions
void Construct (const FArguments &InArgs)
DECLARE_DELEGATE_FourParams (FOnDynamicSliderMinMaxValueChanged, NumericType, TWeakPtr< SWidget >, bool, bool)
Notification when the max/min spinner values are changed (only apply if SupportDynamicSliderMaxValue or SupportDynamicSliderMinValue are true)
DECLARE_DELEGATE_OneParam (FOnUndeterminedValueChanged, FText)
Notification for change of undetermined values.
DECLARE_DELEGATE_OneParam (FOnValueChanged, NumericType)
Notification for numeric value change.
DECLARE_DELEGATE_TwoParams (FOnUndeterminedValueCommitted, FText, ETextCommit::Type)
Notification for committing undetermined values.
DECLARE_DELEGATE_TwoParams (FOnValueCommitted, NumericType, ETextCommit::Type)
Notification for numeric value committed.
int32 GetMaxFractionalDigits () const
See the MaxFractionalDigits attribute.
int32 GetMinFractionalDigits () const
See the MinFractionalDigits attribute.
TSharedPtr< SWidget > GetSpinBox () const
Return the internally created SpinBox if bAllowSpin is true.
void SetMaxFractionalDigits (const TAttribute< TOptional< int32 > > &InMaxFractionalDigits)
void SetMinFractionalDigits (const TAttribute< TOptional< int32 > > &InMinFractionalDigits)
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font SLATE_ARGUMENT (bool, AllowSpin) SLATE_ATTRIBUTE_DEPRECATED(int32
Whether or not the user should be able to change the value by dragging with the mouse cursor.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue SLATE_ARGUMENT (bool, AllowWheel) SLATE_ARGUMENT(bool
Whether this spin box should have mouse wheel feature enabled, defaults to true.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling SLATE_ARGUMENT (bool, BroadcastValueChangesPerKey) SLATE_ATTRIBUTE(TOptional< NumericType >
True to broadcast every time we type.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement TypeInterface SLATE_ARGUMENT (bool, DisplayToggle) SLATE_ATTRIBUTE(ECheckBoxState
Whether or not to include a toggle checkbox to the left of the widget.
SpinBoxStyle LabelVAlign LabelLocation SLATE_ARGUMENT (FMargin, LabelPadding) SLATE_ARGUMENT(FSlateColor
Padding around the label content.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor SLATE_ARGUMENT (FSlateColor, BorderBackgroundColor) SLATE_ATTRIBUTE(TOptional< NumericType >
Border Background Color.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value SLATE_ARGUMENT (FText, UndeterminedString) SLATE_ATTRIBUTE(FSlateFontInfo
The string to display if the value cannot be determined.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue SLATE_ATTRIBUTE (bool, SupportDynamicSliderMinValue) SLATE_EVENT(FOnDynamicSliderMinMaxValueChanged
Tell us if we want to support dynamically changing of the min value using ctrl (only use if there is a spinbox allow)
SpinBoxStyle LabelVAlign SLATE_ATTRIBUTE (ETextJustify::Type, Justification) SLATE_ARGUMENT(ELabelLocation
How should the value be justified in the editable text field.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep SLATE_ATTRIBUTE (float, MinDesiredValueWidth) SLATE_ATTRIBUTE(FMargin
The minimum desired width for the value portion of the control.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier SLATE_ATTRIBUTE (float, ShiftMultiplier) SLATE_ATTRIBUTE(float
Multiplier to use when shift is held down.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SLATE_ATTRIBUTE (float, SliderExponent) SLATE_ATTRIBUTE(NumericType
Use exponential scale for the slider.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SLATE_ATTRIBUTE (int32, LinearDeltaSensitivity) SLATE_ATTRIBUTE(bool
If we're an unbounded spinbox, what value do we divide mouse movement by before multiplying by Delta.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement TypeInterface ToggleChecked TogglePadding SLATE_ATTRIBUTE (TOptional< FTextFormat >, ToolTipTextFormat) SLATE_END_ARGS() SNumericEntryBox()
An optional format pattern that is used to format the ToolTipText.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta SLATE_ATTRIBUTE (TOptional< int32 >, MinFractionalDigits) SLATE_ATTRIBUTE(TOptional< int32 >
The minimum fractional digits the spin box displays, defaults to 1.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue SLATE_ATTRIBUTE (TOptional< NumericType >, MinSliderValue) SLATE_ATTRIBUTE(TOptional< NumericType >
The minimum value that can be specified by using the slider.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits SLATE_ATTRIBUTE (TOptional< NumericType >, MinValue) SLATE_ATTRIBUTE(TOptional< NumericType >
The minimum value that can be entered into the text edit box.
SLATE_BEGIN_ARGS (SNumericEntryBox< NumericType >)
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement SLATE_EVENT (FMenuExtensionDelegate, ContextMenuExtender) SLATE_ARGUMENT(TSharedPtr< INumericTypeInterface< NumericType > >
Menu extender for right-click context menu.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement TypeInterface ToggleChecked SLATE_EVENT (FOnCheckStateChanged, OnToggleChanged) SLATE_ARGUMENT(FMargin
Called whenever the toggle changes state.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SLATE_EVENT (FOnDynamicSliderMinMaxValueChanged, OnDynamicSliderMinValueChanged) SLATE_ATTRIBUTE(NumericType
Called right after the spinner min value is changed (only relevant if SupportDynamicSliderMinValue is true)
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted SLATE_EVENT (FOnUndeterminedValueChanged, OnUndeterminedValueChanged) SLATE_EVENT(FOnUndeterminedValueCommitted
Called whenever the text is changed programmatically or interactively by the user.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin SLATE_EVENT (FOnValueChanged, OnValueChanged) SLATE_EVENT(FOnValueCommitted
Called whenever the text is changed programmatically or interactively by the user.
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted SLATE_EVENT (FSimpleDelegate, OnBeginSliderMovement) SLATE_EVENT(FOnValueChanged
Called right before the slider begins to move.
SpinBoxStyle SLATE_NAMED_SLOT (FArguments, Label) SLATE_ARGUMENT(EVerticalAlignment
Slot for this button's content (optional)
SLATE_STYLE_ARGUMENT (FEditableTextBoxStyle, EditableTextBoxStyle) SLATE_STYLE_ARGUMENT(FSpinBoxStyle
Style to use for the editable text box within this widget.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< SWidget > BuildLabel (TAttribute< FText > LabelText, const FSlateColor &ForegroundColor, const FSlateColor &BackgroundColor)
static TSharedRef< SWidget > BuildNarrowColorLabel (FLinearColor LabelColor)
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Data Fields
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is deprecated
SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font ShiftMouseMovePixelPerDelta
Static Public Attributes
static const FLinearColor BlueLabelBackgroundColor
static const FText DefaultUndeterminedString
static const FLinearColor GreenLabelBackgroundColor
static const FLinearColor LilacLabelBackgroundColor
static const FLinearColor RedLabelBackgroundColor
Private Member Functions
const FSlateBrush * GetBorderImage () const
Called to get the border image of the box.
FString GetCachedString (const NumericType CurrentValue) const
FString GetLabel () const
FText GetToolTipText () const
void HandleToggleCheckBoxChanged (ECheckBoxState InCheckState, FOnCheckStateChanged OnToggleChanged) const
bool IsToggleEnabled () const
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent) override
Called when focus is given to this widget.
NumericType OnGetValueForSpinBox () const
Called to get the value for the spin box.
FText OnGetValueForTextBox () const
Called to get the value for the text box as FText.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
void OnTextChanged (const FText &NewValue)
Called when the text changes in the text box.
void OnTextCommitted (const FText &NewValue, ETextCommit::Type CommitInfo)
Called when the text is committed from the text box.
void ResetCachedValueString ()
void SendChangesFromText (const FText &NewValue, bool bCommit, ETextCommit::Type CommitInfo)
Calls the value commit or changed delegate set for this box when the value is set from a string.
void SetCachedString (const NumericType CurrentValue)
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Caches the value and performs widget visibility maintenance.
Private Attributes
bool bCachedValueStringDirty
Whetever the interfaced setting changed and the CachedValueString needs to be recomputed.
const FSlateBrush * BorderImageFocused
Styling: border image to draw when focused.
const FSlateBrush * BorderImageHovered
Styling: border image to draw when hovered.
const FSlateBrush * BorderImageNormal
Styling: border image to draw when not hovered or focused.
TOptional< NumericType > CachedExternalValue
Cached value of entry box, updated on set & per tick.
FString CachedValueString
Used to prevent per-frame re-conversion of the cached numeric value to a string.
TSharedPtr< SEditableText > EditableText
Editable widget.
TSharedPtr< INumericTypeInterface< NumericType > > Interface
Type interface that defines how we should deal with the templated numeric type.
TAttribute< TOptional< FString > > LabelAttribute
Attribute for getting the label.
TAttribute< TOptional< int32 > > MaxFractionalDigits
TAttribute< float > MinDesiredValueWidth
Prevents the value portion of the control from being smaller than desired in certain cases.
TAttribute< TOptional< int32 > > MinFractionalDigits
FOnUndeterminedValueChanged OnUndeterminedValueChanged
Delegate to call when an undetermined value changes.
FOnUndeterminedValueCommitted OnUndeterminedValueCommitted
Delegate to call when an undetermined is committed.
FOnValueChanged OnValueChanged
Delegate to call when the value changes.
FOnValueCommitted OnValueCommitted
Delegate to call when the value is committed.
TSharedPtr< SSpinBox< NumericType > > SpinBox
Spinbox widget.
TSharedPtr< SCheckBox > ToggleCheckBox
Toggle checkbox.
TAttribute< TOptional< FTextFormat > > ToolTipTextFormat
FText UndeterminedString
The undetermined string to display when needed.
TAttribute< TOptional< NumericType > > ValueAttribute
Attribute for getting the value.
Static Private Attributes
static const int32 DefaultMaxFractionalDigits
The default maximum fractional digits.
static const int32 DefaultMinFractionalDigits
The default minimum fractional digits.
Additional Inherited Members
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
template<typename NumericType>
class SNumericEntryBox< NumericType >
Implementation for a box that only accepts a numeric value or that can display an undetermined value via a string Supports an optional spin box for manipulating a value by dragging with the mouse Supports an optional label inset in the text box.
Definition at line 36 of file SNumericEntryBox.h.
Member Enumeration Documentation
ELabelLocation
template<typename NumericType> enum class SNumericEntryBox::ELabelLocation strong
Enumerator
Outside
Inside
Definition at line 61 of file SNumericEntryBox.h.
Member Function Documentation
BuildLabel()
template<typename NumericType> TSharedRef< SWidget > SNumericEntryBox< NumericType >::BuildLabel (TAttribute< FText > LabelText, const FSlateColor & ForegroundColor, const FSlateColor & BackgroundColor) inline static
Definition at line 440 of file SNumericEntryBox.h.
References FCoreStyle::Get(), EVisibility::HitTestInvisible, and SNew.
BuildNarrowColorLabel()
template<typename NumericType> TSharedRef< SWidget > SNumericEntryBox< NumericType >::BuildNarrowColorLabel (FLinearColor LabelColor) inline static
Definition at line 458 of file SNumericEntryBox.h.
References FAppStyle::Get(), EVisibility::HitTestInvisible, and SNew.
Referenced by SNumericRotatorInputBox< float >::ConstructPitch(), SNumericRotatorInputBox< float >::ConstructRoll(), and SNumericRotatorInputBox< float >::ConstructYaw().
Construct()
template<typename NumericType> void SNumericEntryBox< NumericType >::Construct (const FArguments & InArgs) inline
Definition at line 210 of file SNumericEntryBox.h.
References bCachedValueStringDirty, BorderImageFocused, BorderImageHovered, BorderImageNormal, CachedExternalValue, CachedValueString, check, SCompoundWidget::ChildSlot, EVisibility::Collapsed, DefaultMaxFractionalDigits, DefaultMinFractionalDigits, EditableText, GetBorderImage(), GetToolTipText(), HandleToggleCheckBoxChanged(), Inside, Interface, MakeShareable(), MaxFractionalDigits, MinDesiredValueWidth, MinFractionalDigits, SNullWidget::NullWidget, OnGetValueForSpinBox(), OnGetValueForTextBox(), OnTextChanged(), OnTextCommitted(), OnUndeterminedValueChanged, OnUndeterminedValueCommitted, OnValueChanged, OnValueCommitted, SBorder::Padding(), ResetCachedValueString(), SAssignNew, SetMaxFractionalDigits(), SetMinFractionalDigits(), SHorizontalBox::Slot(), SNew, SpinBox, ToggleCheckBox, ToolTipTextFormat, TSharedPtr< ObjectType, InMode >::ToSharedRef(), UndeterminedString, ValueAttribute, and EVisibility::Visible.
DECLARE_DELEGATE_FourParams()
template<typename NumericType> SNumericEntryBox< NumericType >::DECLARE_DELEGATE_FourParams (FOnDynamicSliderMinMaxValueChanged , NumericType , TWeakPtr< SWidget > , bool , bool)
Notification when the max/min spinner values are changed (only apply if SupportDynamicSliderMaxValue or SupportDynamicSliderMinValue are true)
DECLARE_DELEGATE_OneParam() [1/2]
template<typename NumericType> SNumericEntryBox< NumericType >::DECLARE_DELEGATE_OneParam (FOnUndeterminedValueChanged , FText)
Notification for change of undetermined values.
DECLARE_DELEGATE_OneParam() [2/2]
template<typename NumericType> SNumericEntryBox< NumericType >::DECLARE_DELEGATE_OneParam (FOnValueChanged , NumericType)
Notification for numeric value change.
DECLARE_DELEGATE_TwoParams() [1/2]
template<typename NumericType> SNumericEntryBox< NumericType >::DECLARE_DELEGATE_TwoParams (FOnUndeterminedValueCommitted , FText , ETextCommit::Type)
Notification for committing undetermined values.
DECLARE_DELEGATE_TwoParams() [2/2]
template<typename NumericType> SNumericEntryBox< NumericType >::DECLARE_DELEGATE_TwoParams (FOnValueCommitted , NumericType , ETextCommit::Type)
Notification for numeric value committed.
GetBorderImage()
template<typename NumericType> const FSlateBrush * SNumericEntryBox< NumericType >::GetBorderImage () const inline private
Called to get the border image of the box.
Definition at line 677 of file SNumericEntryBox.h.
References BorderImageFocused, BorderImageHovered, BorderImageNormal, EditableText, SpinBox, and EVisibility::Visible.
Referenced by Construct().
GetCachedString()
template<typename NumericType> FString SNumericEntryBox< NumericType >::GetCachedString (const NumericType CurrentValue) const inline private
Definition at line 571 of file SNumericEntryBox.h.
References bCachedValueStringDirty, CachedExternalValue, CachedValueString, and Interface.
Referenced by GetToolTipText(), and OnGetValueForTextBox().
GetLabel()
template<typename NumericType> FString SNumericEntryBox< NumericType >::GetLabel () const inline private
Returns
the Label that should be displayed
Definition at line 539 of file SNumericEntryBox.h.
References LabelAttribute.
GetMaxFractionalDigits()
template<typename NumericType> int32 SNumericEntryBox< NumericType >::GetMaxFractionalDigits () const inline
See the MaxFractionalDigits attribute.
Definition at line 482 of file SNumericEntryBox.h.
References Interface.
GetMinFractionalDigits()
template<typename NumericType> int32 SNumericEntryBox< NumericType >::GetMinFractionalDigits () const inline
See the MinFractionalDigits attribute.
Definition at line 474 of file SNumericEntryBox.h.
References Interface.
GetSpinBox()
template<typename NumericType> TSharedPtr< SWidget > SNumericEntryBox< NumericType >::GetSpinBox () const inline
Return the internally created SpinBox if bAllowSpin is true.
Definition at line 471 of file SNumericEntryBox.h.
References SpinBox.
GetToolTipText()
template<typename NumericType> FText SNumericEntryBox< NumericType >::GetToolTipText () const inline private
Definition at line 577 of file SNumericEntryBox.h.
References CachedValueString, FText::Format(), FText::FromString(), GetCachedString(), FText::GetEmpty(), NSLOCTEXT, TEXT, ToolTipTextFormat, Value, and ValueAttribute.
Referenced by Construct().
HandleToggleCheckBoxChanged()
template<typename NumericType> void SNumericEntryBox< NumericType >::HandleToggleCheckBoxChanged (ECheckBoxState InCheckState, FOnCheckStateChanged OnToggleChanged) const inline private
Definition at line 793 of file SNumericEntryBox.h.
References EditableText, and SpinBox.
Referenced by Construct().
IsToggleEnabled()
template<typename NumericType> bool SNumericEntryBox< NumericType >::IsToggleEnabled () const inline private
Definition at line 784 of file SNumericEntryBox.h.
References SWidget::IsEnabled(), and ToggleCheckBox.
OnFocusReceived()
template<typename NumericType> virtual FReply SNumericEntryBox< NumericType >::OnFocusReceived (const FGeometry & MyGeometry, const FFocusEvent & InFocusEvent) inline override private virtual
Called when focus is given to this widget.
This event does not bubble.
Parameters
MyGeometry The Geometry of the widget receiving the event
InFocusEvent The FocusEvent
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
Definition at line 498 of file SNumericEntryBox.h.
References EditableText, FReply::Handled(), FReply::SetUserFocus(), SpinBox, TSharedPtr< ObjectType, InMode >::ToSharedRef(), and EVisibility::Visible.
OnGetValueForSpinBox()
template<typename NumericType> NumericType SNumericEntryBox< NumericType >::OnGetValueForSpinBox () const inline private
Called to get the value for the spin box.
Definition at line 548 of file SNumericEntryBox.h.
References Value, and ValueAttribute.
Referenced by Construct().
OnGetValueForTextBox()
template<typename NumericType> FText SNumericEntryBox< NumericType >::OnGetValueForTextBox () const inline private
Called to get the value for the text box as FText.
Definition at line 620 of file SNumericEntryBox.h.
References EditableText, FText::FromString(), GetCachedString(), FText::GetEmpty(), UndeterminedString, Value, ValueAttribute, and EVisibility::Visible.
Referenced by Construct().
OnKeyDown()
template<typename NumericType> virtual FReply SNumericEntryBox< NumericType >::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline override private virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
Definition at line 522 of file SNumericEntryBox.h.
References EditableText, EKeys::Escape, FReply::Handled(), Key, FReply::SetUserFocus(), TSharedFromThis< SWidget >::SharedThis(), and FReply::Unhandled().
OnTextChanged()
template<typename NumericType> void SNumericEntryBox< NumericType >::OnTextChanged (const FText & NewValue) inline private
Called when the text changes in the text box.
Definition at line 643 of file SNumericEntryBox.h.
References OnUndeterminedValueChanged, SendChangesFromText(), Value, and ValueAttribute.
Referenced by Construct().
OnTextCommitted()
template<typename NumericType> void SNumericEntryBox< NumericType >::OnTextCommitted (const FText & NewValue, ETextCommit::Type CommitInfo) inline private
Called when the text is committed from the text box.
Definition at line 660 of file SNumericEntryBox.h.
References OnUndeterminedValueCommitted, SendChangesFromText(), Value, and ValueAttribute.
Referenced by Construct().
ResetCachedValueString()
template<typename NumericType> void SNumericEntryBox< NumericType >::ResetCachedValueString () inline private
Definition at line 809 of file SNumericEntryBox.h.
References bCachedValueStringDirty, and ValueAttribute.
Referenced by Construct().
SendChangesFromText()
template<typename NumericType> void SNumericEntryBox< NumericType >::SendChangesFromText (const FText & NewValue, bool bCommit, ETextCommit::Type CommitInfo) inline private
Calls the value commit or changed delegate set for this box when the value is set from a string.
Parameters
NewValue The new value as a string
bCommit Whether or not to call the commit or changed delegate
Definition at line 709 of file SNumericEntryBox.h.
References TOptional< OptionalType >::Get(), TOptional< OptionalType >::GetValue(), Interface, FText::IsEmpty(), TOptional< OptionalType >::IsSet(), OnValueChanged, OnValueCommitted, SetCachedString(), and ValueAttribute.
Referenced by OnTextChanged(), and OnTextCommitted().
SetCachedString()
template<typename NumericType> void SNumericEntryBox< NumericType >::SetCachedString (const NumericType CurrentValue) inline private
Definition at line 561 of file SNumericEntryBox.h.
References bCachedValueStringDirty, CachedExternalValue, CachedValueString, and Interface.
Referenced by SendChangesFromText(), and Tick().
SetMaxFractionalDigits()
template<typename NumericType> void SNumericEntryBox< NumericType >::SetMaxFractionalDigits (const TAttribute< TOptional< int32 > > & InMaxFractionalDigits) inline
Definition at line 483 of file SNumericEntryBox.h.
References bCachedValueStringDirty, Interface, and MaxFractionalDigits.
Referenced by Construct().
SetMinFractionalDigits()
template<typename NumericType> void SNumericEntryBox< NumericType >::SetMinFractionalDigits (const TAttribute< TOptional< int32 > > & InMinFractionalDigits) inline
Definition at line 475 of file SNumericEntryBox.h.
References bCachedValueStringDirty, Interface, and MinFractionalDigits.
Referenced by Construct().
SLATE_ARGUMENT() [1/7]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font SNumericEntryBox< NumericType >::SLATE_ARGUMENT (bool , AllowSpin)
Whether or not the user should be able to change the value by dragging with the mouse cursor.
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [2/7]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue SNumericEntryBox< NumericType >::SLATE_ARGUMENT (bool , AllowWheel)
Whether this spin box should have mouse wheel feature enabled, defaults to true.
If refresh requests for the viewport should happen for all value changes
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [3/7]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling SNumericEntryBox< NumericType >::SLATE_ARGUMENT (bool , BroadcastValueChangesPerKey)
True to broadcast every time we type.
Step to increment or decrement the value by when scrolling the mouse wheel. If not specified will determine automatically
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ARGUMENT() [4/7]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement TypeInterface SNumericEntryBox< NumericType >::SLATE_ARGUMENT (bool , DisplayToggle)
Whether or not to include a toggle checkbox to the left of the widget.
The value of the toggle checkbox
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ARGUMENT() [5/7]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation SNumericEntryBox< NumericType >::SLATE_ARGUMENT (FMargin , LabelPadding)
Padding around the label content.
Border Foreground Color
References SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_NAMED_SLOT().
SLATE_ARGUMENT() [6/7]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor SNumericEntryBox< NumericType >::SLATE_ARGUMENT (FSlateColor , BorderBackgroundColor)
Border Background Color.
The value that should be displayed. This value is optional in the case where a value cannot be determined
References SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and Value.
SLATE_ARGUMENT() [7/7]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value SNumericEntryBox< NumericType >::SLATE_ARGUMENT (FText , UndeterminedString)
The string to display if the value cannot be determined.
Font color and opacity
References SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and UndeterminedString.
SLATE_ATTRIBUTE() [1/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (bool , SupportDynamicSliderMinValue)
Tell us if we want to support dynamically changing of the min value using ctrl (only use if there is a spinbox allow)
Called right after the spinner max value is changed (only relevant if SupportDynamicSliderMaxValue is true)
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [2/10]
template<typename NumericType> SpinBoxStyle LabelVAlign SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (ETextJustify::Type , Justification)
How should the value be justified in the editable text field.
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [3/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (float , MinDesiredValueWidth)
The minimum desired width for the value portion of the control.
The text margin to use if overridden.
References MinDesiredValueWidth, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [4/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (float , ShiftMultiplier)
Multiplier to use when shift is held down.
Multiplier to use when ctrl is held down
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [5/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (float , SliderExponent)
Use exponential scale for the slider.
When using exponential scale specify a neutral value where we want the maximum precision (by default it is the smallest slider value)
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [6/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (int32 , LinearDeltaSensitivity)
If we're an unbounded spinbox, what value do we divide mouse movement by before multiplying by Delta.
Requires Delta to be set. Tell us if we want to support dynamically changing of the max value using ctrl (only use if there is a spinbox allow)
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [7/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement TypeInterface ToggleChecked TogglePadding SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (TOptional< FTextFormat > , ToolTipTextFormat) inline
An optional format pattern that is used to format the ToolTipText.
If set, this is used with a single argument ({0} = the display value).
Definition at line 203 of file SNumericEntryBox.h.
References SLATE_ATTRIBUTE(), SLATE_END_ARGS, and ToolTipTextFormat.
SLATE_ATTRIBUTE() [8/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (TOptional< int32 > , MinFractionalDigits)
The minimum fractional digits the spin box displays, defaults to 1.
The maximum fractional digits the spin box displays, defaults to 6
References MaxFractionalDigits, MinFractionalDigits, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [9/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (TOptional< NumericType > , MinSliderValue)
The minimum value that can be specified by using the slider.
The maximum value that can be specified by using the slider
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [10/10]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits SNumericEntryBox< NumericType >::SLATE_ATTRIBUTE (TOptional< NumericType > , MinValue)
The minimum value that can be entered into the text edit box.
The maximum value that can be entered into the text edit box
References SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
template<typename NumericType> SNumericEntryBox< NumericType >::SLATE_BEGIN_ARGS (SNumericEntryBox< NumericType >) inline
Definition at line 71 of file SNumericEntryBox.h.
References DefaultMaxFractionalDigits, DefaultMinFractionalDigits, DefaultUndeterminedString, Left, Lowest, Max, and Outside.
SLATE_EVENT() [1/6]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement SNumericEntryBox< NumericType >::SLATE_EVENT (FMenuExtensionDelegate , ContextMenuExtender)
Menu extender for right-click context menu.
Provide custom type conversion functionality to this spin box
References SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_EVENT() [2/6]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted OnEndSliderMovement TypeInterface ToggleChecked SNumericEntryBox< NumericType >::SLATE_EVENT (FOnCheckStateChanged , OnToggleChanged)
Called whenever the toggle changes state.
Padding around the toggle checkbox
References SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_EVENT() [3/6]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged SNumericEntryBox< NumericType >::SLATE_EVENT (FOnDynamicSliderMinMaxValueChanged , OnDynamicSliderMinValueChanged)
Called right after the spinner min value is changed (only relevant if SupportDynamicSliderMinValue is true)
Delta to increment the value as the slider moves. If not specified will determine automatically
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
Referenced by SLATE_ATTRIBUTE(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [4/6]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted SNumericEntryBox< NumericType >::SLATE_EVENT (FOnUndeterminedValueChanged , OnUndeterminedValueChanged)
Called whenever the text is changed programmatically or interactively by the user.
Called whenever the text is committed. This happens when the user presses enter or the text box loses focus.
References OnUndeterminedValueChanged, OnUndeterminedValueCommitted, and SLATE_EVENT().
SLATE_EVENT() [5/6]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin SNumericEntryBox< NumericType >::SLATE_EVENT (FOnValueChanged , OnValueChanged)
Called whenever the text is changed programmatically or interactively by the user.
Called whenever the text is committed. This happens when the user presses enter or the text box loses focus.
References OnValueChanged, OnValueCommitted, and SLATE_EVENT().
SLATE_EVENT() [6/6]
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is please use ShiftMultiplier CtrlMultiplier SupportDynamicSliderMaxValue OnDynamicSliderMaxValueChanged Delta MaxFractionalDigits MaxValue MaxSliderValue SliderExponentNeutralValue PreventThrottling WheelStep OverrideTextMargin OnValueCommitted OnUndeterminedValueCommitted SNumericEntryBox< NumericType >::SLATE_EVENT (FSimpleDelegate , OnBeginSliderMovement)
Called right before the slider begins to move.
Called right after the slider handle is released by the user
References SLATE_EVENT().
SLATE_NAMED_SLOT()
template<typename NumericType> SpinBoxStyle SNumericEntryBox< NumericType >::SLATE_NAMED_SLOT (FArguments , Label)
Slot for this button's content (optional)
Vertical alignment of the label content
References SLATE_ARGUMENT(), and SLATE_NAMED_SLOT().
Referenced by SLATE_NAMED_SLOT().
SLATE_STYLE_ARGUMENT()
template<typename NumericType> SNumericEntryBox< NumericType >::SLATE_STYLE_ARGUMENT (FEditableTextBoxStyle , EditableTextBoxStyle)
Style to use for the editable text box within this widget.
Style to use for the spin box within this widget
SupportsKeyboardFocus()
template<typename NumericType> virtual bool SNumericEntryBox< NumericType >::SupportsKeyboardFocus () const inline override private virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
Definition at line 493 of file SNumericEntryBox.h.
References EditableText, and StaticCastSharedPtr().
Tick()
template<typename NumericType> virtual void SNumericEntryBox< NumericType >::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) inline override private virtual
Caches the value and performs widget visibility maintenance.
Reimplemented from SWidget.
Definition at line 737 of file SNumericEntryBox.h.
References bCachedValueStringDirty, EVisibility::Collapsed, EditableText, SWidget::GetPersistentState(), Interface, SetCachedString(), SpinBox, Value, ValueAttribute, and EVisibility::Visible.
Field Documentation
bCachedValueStringDirty
template<typename NumericType> bool SNumericEntryBox< NumericType >::bCachedValueStringDirty private
Whetever the interfaced setting changed and the CachedValueString needs to be recomputed.
Definition at line 860 of file SNumericEntryBox.h.
Referenced by Construct(), GetCachedString(), ResetCachedValueString(), SetCachedString(), SetMaxFractionalDigits(), SetMinFractionalDigits(), and Tick().
BlueLabelBackgroundColor
template<typename NumericType> const FLinearColor SNumericEntryBox< NumericType >::BlueLabelBackgroundColor static
Definition at line 42 of file SNumericEntryBox.h.
BorderImageFocused
template<typename NumericType> const FSlateBrush* SNumericEntryBox< NumericType >::BorderImageFocused private
Styling: border image to draw when focused.
Definition at line 850 of file SNumericEntryBox.h.
Referenced by Construct(), and GetBorderImage().
BorderImageHovered
template<typename NumericType> const FSlateBrush* SNumericEntryBox< NumericType >::BorderImageHovered private
Styling: border image to draw when hovered.
Definition at line 848 of file SNumericEntryBox.h.
Referenced by Construct(), and GetBorderImage().
BorderImageNormal
template<typename NumericType> const FSlateBrush* SNumericEntryBox< NumericType >::BorderImageNormal private
Styling: border image to draw when not hovered or focused.
Definition at line 846 of file SNumericEntryBox.h.
Referenced by Construct(), and GetBorderImage().
CachedExternalValue
template<typename NumericType> TOptional<NumericType> SNumericEntryBox< NumericType >::CachedExternalValue private
Cached value of entry box, updated on set & per tick.
Definition at line 856 of file SNumericEntryBox.h.
Referenced by Construct(), GetCachedString(), and SetCachedString().
CachedValueString
template<typename NumericType> FString SNumericEntryBox< NumericType >::CachedValueString private
Used to prevent per-frame re-conversion of the cached numeric value to a string.
Definition at line 858 of file SNumericEntryBox.h.
Referenced by Construct(), GetCachedString(), GetToolTipText(), and SetCachedString().
DefaultMaxFractionalDigits
template<typename NumericType> const int32 SNumericEntryBox< NumericType >::DefaultMaxFractionalDigits static private
The default maximum fractional digits.
Definition at line 823 of file SNumericEntryBox.h.
Referenced by Construct(), and SLATE_BEGIN_ARGS().
DefaultMinFractionalDigits
template<typename NumericType> const int32 SNumericEntryBox< NumericType >::DefaultMinFractionalDigits static private
The default minimum fractional digits.
Definition at line 820 of file SNumericEntryBox.h.
Referenced by Construct(), and SLATE_BEGIN_ARGS().
DefaultUndeterminedString
template<typename NumericType> const FText SNumericEntryBox< NumericType >::DefaultUndeterminedString static
Definition at line 44 of file SNumericEntryBox.h.
Referenced by SLATE_BEGIN_ARGS().
deprecated
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font Shift Mouse Move Pixel Per Delta is SNumericEntryBox< NumericType >::deprecated
Definition at line 133 of file SNumericEntryBox.h.
EditableText
template<typename NumericType> TSharedPtr<SEditableText> SNumericEntryBox< NumericType >::EditableText private
Editable widget.
Definition at line 834 of file SNumericEntryBox.h.
Referenced by Construct(), GetBorderImage(), HandleToggleCheckBoxChanged(), OnFocusReceived(), OnGetValueForTextBox(), OnKeyDown(), SupportsKeyboardFocus(), and Tick().
GreenLabelBackgroundColor
template<typename NumericType> const FLinearColor SNumericEntryBox< NumericType >::GreenLabelBackgroundColor static
Definition at line 41 of file SNumericEntryBox.h.
Interface
template<typename NumericType> TSharedPtr< INumericTypeInterface<NumericType> > SNumericEntryBox< NumericType >::Interface private
Type interface that defines how we should deal with the templated numeric type.
Always valid after construction.
Definition at line 854 of file SNumericEntryBox.h.
Referenced by Construct(), GetCachedString(), GetMaxFractionalDigits(), GetMinFractionalDigits(), SendChangesFromText(), SetCachedString(), SetMaxFractionalDigits(), SetMinFractionalDigits(), and Tick().
LabelAttribute
template<typename NumericType> TAttribute< TOptional<FString > > SNumericEntryBox< NumericType >::LabelAttribute private
Attribute for getting the label.
Definition at line 826 of file SNumericEntryBox.h.
Referenced by GetLabel().
LilacLabelBackgroundColor
template<typename NumericType> const FLinearColor SNumericEntryBox< NumericType >::LilacLabelBackgroundColor static
Definition at line 43 of file SNumericEntryBox.h.
Referenced by SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::FVectorWArguments().
MaxFractionalDigits
template<typename NumericType> TAttribute< TOptional<int32> > SNumericEntryBox< NumericType >::MaxFractionalDigits private
Definition at line 862 of file SNumericEntryBox.h.
Referenced by Construct(), SetMaxFractionalDigits(), and SLATE_ATTRIBUTE().
MinDesiredValueWidth
template<typename NumericType> TAttribute<float> SNumericEntryBox< NumericType >::MinDesiredValueWidth private
Prevents the value portion of the control from being smaller than desired in certain cases.
Definition at line 852 of file SNumericEntryBox.h.
Referenced by Construct(), and SLATE_ATTRIBUTE().
MinFractionalDigits
template<typename NumericType> TAttribute< TOptional<int32> > SNumericEntryBox< NumericType >::MinFractionalDigits private
Definition at line 861 of file SNumericEntryBox.h.
Referenced by Construct(), SetMinFractionalDigits(), and SLATE_ATTRIBUTE().
OnUndeterminedValueChanged
template<typename NumericType> FOnUndeterminedValueChanged SNumericEntryBox< NumericType >::OnUndeterminedValueChanged private
Delegate to call when an undetermined value changes.
Definition at line 840 of file SNumericEntryBox.h.
Referenced by Construct(), OnTextChanged(), and SLATE_EVENT().
OnUndeterminedValueCommitted
template<typename NumericType> FOnUndeterminedValueCommitted SNumericEntryBox< NumericType >::OnUndeterminedValueCommitted private
Delegate to call when an undetermined is committed.
Definition at line 842 of file SNumericEntryBox.h.
Referenced by Construct(), OnTextCommitted(), and SLATE_EVENT().
OnValueChanged
template<typename NumericType> FOnValueChanged SNumericEntryBox< NumericType >::OnValueChanged private
Delegate to call when the value changes.
Definition at line 836 of file SNumericEntryBox.h.
Referenced by Construct(), SendChangesFromText(), and SLATE_EVENT().
OnValueCommitted
template<typename NumericType> FOnValueCommitted SNumericEntryBox< NumericType >::OnValueCommitted private
Delegate to call when the value is committed.
Definition at line 838 of file SNumericEntryBox.h.
Referenced by Construct(), SendChangesFromText(), and SLATE_EVENT().
RedLabelBackgroundColor
template<typename NumericType> const FLinearColor SNumericEntryBox< NumericType >::RedLabelBackgroundColor static
Definition at line 40 of file SNumericEntryBox.h.
ShiftMouseMovePixelPerDelta
template<typename NumericType> SpinBoxStyle LabelVAlign LabelLocation BorderForegroundColor Value Font SNumericEntryBox< NumericType >::ShiftMouseMovePixelPerDelta
Definition at line 133 of file SNumericEntryBox.h.
SpinBox
template<typename NumericType> TSharedPtr<SSpinBox<NumericType> > SNumericEntryBox< NumericType >::SpinBox private
Spinbox widget.
Definition at line 832 of file SNumericEntryBox.h.
Referenced by Construct(), GetBorderImage(), GetSpinBox(), HandleToggleCheckBoxChanged(), OnFocusReceived(), and Tick().
ToggleCheckBox
template<typename NumericType> TSharedPtr<SCheckBox> SNumericEntryBox< NumericType >::ToggleCheckBox private
Toggle checkbox.
Definition at line 830 of file SNumericEntryBox.h.
Referenced by Construct(), and IsToggleEnabled().
ToolTipTextFormat
template<typename NumericType> TAttribute< TOptional<FTextFormat> > SNumericEntryBox< NumericType >::ToolTipTextFormat private
Definition at line 863 of file SNumericEntryBox.h.
Referenced by Construct(), GetToolTipText(), and SLATE_ATTRIBUTE().
UndeterminedString
template<typename NumericType> FText SNumericEntryBox< NumericType >::UndeterminedString private
The undetermined string to display when needed.
Definition at line 844 of file SNumericEntryBox.h.
Referenced by Construct(), OnGetValueForTextBox(), and SLATE_ARGUMENT().
ValueAttribute
template<typename NumericType> TAttribute< TOptional<NumericType> > SNumericEntryBox< NumericType >::ValueAttribute private
Attribute for getting the value.
If the value is not set we display the undetermined string
Definition at line 828 of file SNumericEntryBox.h.
Referenced by Construct(), GetToolTipText(), OnGetValueForSpinBox(), OnGetValueForTextBox(), OnTextChanged(), OnTextCommitted(), ResetCachedValueString(), SendChangesFromText(), and Tick().
The documentation for this class was generated from the following files:
SlateFwd.h
SNumericEntryBox.h