Unreal Engine 5.6 C++ API: FFileManagerGeneric Class Reference
FFileManagerGeneric Class Reference
Base class for file managers.
#include "FileManagerGeneric.h"
Public Member Functions
FFileManagerGeneric ()
Default constructor.
virtual ~FFileManagerGeneric ()
Virtual destructor.
FString ConvertToAbsolutePathForExternalAppForRead (const TCHAR *Filename) override
Converts passed in filename to use an absolute path (for reading)
FString ConvertToAbsolutePathForExternalAppForWrite (const TCHAR *Filename) override
Converts passed in filename to use an absolute path (for writing)
FString ConvertToRelativePath (const TCHAR *Filename) override
Converts passed in filename to use a relative path.
virtual uint32 Copy (const TCHAR *Dest, const TCHAR *Src, bool Replace=1, bool EvenIfReadOnly=0, bool Attributes=0, FCopyProgress *Progress=nullptr, EFileRead ReadFlags=FILEREAD_None, EFileWrite WriteFlags=FILEWRITE_None) override
Copies a file.
FArchive * CreateFileReader (const TCHAR *Filename, uint32 ReadFlags=0) override
Opens a file for reading and create an FArchive which can be used to read from it.
FArchive * CreateFileWriter (const TCHAR *Filename, uint32 WriteFlags=0) override
Opens a file for writing and create an FArchive which can be used to write to it.
bool Delete (const TCHAR *Filename, bool RequireExists=0, bool EvenReadOnly=0, bool Quiet=0) override
Deletes a file.
virtual bool DeleteDirectory (const TCHAR *Path, bool RequireExists=0, bool Tree=0) override
Deletes a directory.
bool DirectoryExists (const TCHAR *InDirectory) override
Checks if a directory exists.
bool FileExists (const TCHAR *Filename) override
Checks if a file exists.
int64 FileSize (const TCHAR *Filename) override
Returns the size of a file.
virtual void FindFiles (TArray< FString > &FoundFiles, const TCHAR *Directory, const TCHAR *FileExtension=nullptr) override
Finds all the files within the given directory, with optional file extension filter.
void FindFiles (TArray< FString > &Result, const TCHAR *Filename, bool Files, bool Directories) override
Finds file or directories.
void FindFilesRecursive (TArray< FString > &FileNames, const TCHAR *StartDirectory, const TCHAR *Filename, bool Files, bool Directories, bool bClearFileNames=true) override
Finds file or directories recursively.
FDateTime GetAccessTimeStamp (const TCHAR *Filename) override
double GetFileAgeSeconds (const TCHAR *Filename) override
Gets the age of a file measured in seconds.
virtual FString GetFilenameOnDisk (const TCHAR *Filename) override
For case insensitive filesystems, returns the full path of the file with the same case as in the filesystem.
virtual FFileStatData GetStatData (const TCHAR *FilenameOrDirectory) override
Return the stat data for the given file or directory.
FDateTime GetTimeStamp (const TCHAR *Filename) override
void GetTimeStampPair (const TCHAR *PathA, const TCHAR *PathB, FDateTime &OutTimeStampA, FDateTime &OutTimeStampB)
bool IsReadOnly (const TCHAR *Filename) override
Checks if a file is read-only.
virtual bool IsSandboxEnabled () const override
Returns whether the sandbox is enabled or not.
bool IterateDirectory (const TCHAR *Directory, IPlatformFile::FDirectoryVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a single directory.
bool IterateDirectory (const TCHAR *Directory, IPlatformFile::FDirectoryVisitorFunc Visitor) override
Call the visitor once for each file or directory in a single directory.
bool IterateDirectoryRecursively (const TCHAR *Directory, IPlatformFile::FDirectoryVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a directory tree.
bool IterateDirectoryRecursively (const TCHAR *Directory, IPlatformFile::FDirectoryVisitorFunc Visitor) override
Call the Visit function of the visitor once for each file or directory in a directory tree.
bool IterateDirectoryStat (const TCHAR *Directory, IPlatformFile::FDirectoryStatVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a single directory.
bool IterateDirectoryStat (const TCHAR *Directory, IPlatformFile::FDirectoryStatVisitorFunc Visitor) override
Call the visitor once for each file or directory in a single directory.
bool IterateDirectoryStatRecursively (const TCHAR *Directory, IPlatformFile::FDirectoryStatVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a directory tree.
bool IterateDirectoryStatRecursively (const TCHAR *Directory, IPlatformFile::FDirectoryStatVisitorFunc Visitor) override
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool MakeDirectory (const TCHAR *Path, bool Tree=0) override
Creates a directory.
bool Move (const TCHAR *Dest, const TCHAR *Src, bool Replace=1, bool EvenIfReadOnly=0, bool Attributes=0, bool bDoNotRetryOrError=0) override
Moves/renames a file.
virtual void ProcessCommandLineOptions () override
Allow the file manager to handle the commandline.
virtual bool SendMessageToServer (const TCHAR *Message, IPlatformFile::IFileServerMessageHandler *Handler) override
Sends a message to the file server, and will block until it's complete.
virtual void SetSandboxEnabled (bool bInEnabled) override
Enables/disables the sandbox, if it is being used.
bool SetTimeStamp (const TCHAR *Filename, FDateTime Timestamp) override
Sets the modification time of the given file.
Static Public Member Functions
static FString DefaultConvertToRelativePath (const TCHAR *Filename)
Converts passed in filename to use a relative path.
Static Public Member Functions inherited from IFileManager
static IFileManager & Get ()
Singleton access, platform specific, also calls PreInit()
Private Member Functions
uint32 CopyWithProgress (const TCHAR *InDestFile, const TCHAR *InSrcFile, bool ReplaceExisting, bool EvenIfReadOnly, bool Attributes, FCopyProgress *Progress, EFileRead ReadFlags, EFileWrite WriteFlags)
Helper called from Copy if Progress is available.
FArchive * CreateFileReaderInternal (const TCHAR *Filename, uint32 ReadFlags, uint32 BufferSize)
FArchive * CreateFileWriterInternal (const TCHAR *Filename, uint32 WriteFlags, uint32 BufferSize)
void FindFilesRecursiveInternal (TArray< FString > &FileNames, const TCHAR *StartDirectory, const TCHAR *Filename, bool Files, bool Directories)
FORCEINLINE IPlatformFile & GetLowLevel () const
Additional Inherited Members
Protected Member Functions inherited from IFileManager
IFileManager ()
Construtor.
Detailed Description
Base class for file managers.
This base class simplifies IFileManager implementations by providing simple, unoptimized implementations of functions whose implementations can be derived from other functions.
Definition at line 35 of file FileManagerGeneric.h.
Constructor & Destructor Documentation
FFileManagerGeneric()
FFileManagerGeneric::FFileManagerGeneric () inline
Default constructor.
Definition at line 49 of file FileManagerGeneric.h.
~FFileManagerGeneric()
virtual FFileManagerGeneric::~FFileManagerGeneric () inline virtual
Virtual destructor.
Definition at line 54 of file FileManagerGeneric.h.
Member Function Documentation
ConvertToAbsolutePathForExternalAppForRead()
FString FFileManagerGeneric::ConvertToAbsolutePathForExternalAppForRead (const TCHAR * Filename) override virtual
Converts passed in filename to use an absolute path (for reading)
Parameters
Filename filename to convert to use an absolute path, safe to pass in already using absolute path
Returns
filename using absolute path
Implements IFileManager.
References Filename.
ConvertToAbsolutePathForExternalAppForWrite()
FString FFileManagerGeneric::ConvertToAbsolutePathForExternalAppForWrite (const TCHAR * Filename) override virtual
Converts passed in filename to use an absolute path (for writing)
Parameters
Filename filename to convert to use an absolute path, safe to pass in already using absolute path
Returns
filename using absolute path
Implements IFileManager.
References Filename.
ConvertToRelativePath()
FString FFileManagerGeneric::ConvertToRelativePath (const TCHAR * Filename) override virtual
Converts passed in filename to use a relative path.
Parameters
Filename filename to convert to use a relative path
Returns
filename using relative path
Implements IFileManager.
References Filename.
Copy()
virtual uint32 FFileManagerGeneric::Copy (const TCHAR * Dest, const TCHAR * Src, bool Replace = 1, bool EvenIfReadOnly = 0, bool Attributes = 0, FCopyProgress * Progress = nullptr, EFileRead ReadFlags = FILEREAD_None, EFileWrite WriteFlags = FILEWRITE_None) override virtual
Copies a file.
Implements IFileManager.
References FILEREAD_None, FILEWRITE_None, and Replace.
CopyWithProgress()
uint32 FFileManagerGeneric::CopyWithProgress (const TCHAR * InDestFile, const TCHAR * InSrcFile, bool ReplaceExisting, bool EvenIfReadOnly, bool Attributes, FCopyProgress * Progress, EFileRead ReadFlags, EFileWrite WriteFlags) private
Helper called from Copy if Progress is available.
CreateFileReader()
FArchive * FFileManagerGeneric::CreateFileReader (const TCHAR * Filename, uint32 ReadFlags = 0) inline override virtual
Opens a file for reading and create an FArchive which can be used to read from it.
Parameters
Filename Path to the file to open
ReadFlags An optional bitfield of optional flags. For flag values see @See EFileRead
Returns
Returns a pointer to an FArchive when successful and a nullptr if the operation failed. Note that it is up to the caller to delete the FArchive when done.
Implements IFileManager.
Definition at line 72 of file FileManagerGeneric.h.
References CreateFileReaderInternal(), Filename, and PLATFORM_FILE_READER_BUFFER_SIZE.
CreateFileReaderInternal()
FArchive * FFileManagerGeneric::CreateFileReaderInternal (const TCHAR * Filename, uint32 ReadFlags, uint32 BufferSize) private
References Filename.
Referenced by CreateFileReader().
CreateFileWriter()
FArchive * FFileManagerGeneric::CreateFileWriter (const TCHAR * Filename, uint32 WriteFlags = 0) inline override virtual
Opens a file for writing and create an FArchive which can be used to write to it.
Parameters
Filename Path to the desired location of the file
WriteFlags An optional bitfield of optional flags. For flag values see @See EFileWrite
Returns
Returns a pointer to an FArchive when successful and a nullptr if the operation failed. Note that it is up to the caller to delete the FArchive when done.
Implements IFileManager.
Definition at line 77 of file FileManagerGeneric.h.
References CreateFileWriterInternal(), Filename, and PLATFORM_FILE_WRITER_BUFFER_SIZE.
CreateFileWriterInternal()
FArchive * FFileManagerGeneric::CreateFileWriterInternal (const TCHAR * Filename, uint32 WriteFlags, uint32 BufferSize) private
References Filename.
Referenced by CreateFileWriter().
DefaultConvertToRelativePath()
FString FFileManagerGeneric::DefaultConvertToRelativePath (const TCHAR * Filename) static
Converts passed in filename to use a relative path.
Parameters
Filename filename to convert to use a relative path
Returns
filename using relative path
References Filename.
Delete()
bool FFileManagerGeneric::Delete (const TCHAR * Filename, bool RequireExists = 0, bool EvenReadOnly = 0, bool Quiet = 0) override virtual
Deletes a file.
Implements IFileManager.
References Filename.
DeleteDirectory()
virtual bool FFileManagerGeneric::DeleteDirectory (const TCHAR * Path, bool RequireExists = 0, bool Tree = 0) override virtual
Deletes a directory.
Implements IFileManager.
References Path.
DirectoryExists()
bool FFileManagerGeneric::DirectoryExists (const TCHAR * InDirectory) override virtual
Checks if a directory exists.
Implements IFileManager.
FileExists()
bool FFileManagerGeneric::FileExists (const TCHAR * Filename) override virtual
Checks if a file exists.
Implements IFileManager.
References Filename.
FileSize()
int64 FFileManagerGeneric::FileSize (const TCHAR * Filename) override virtual
Returns the size of a file.
(Thread-safe)
Parameters
Filename Platform-independent Unreal filename.
Returns
File size in bytes or INDEX_NONE if the file didn't exist.
Implements IFileManager.
References Filename.
FindFiles() [1/2]
virtual void FFileManagerGeneric::FindFiles (TArray< FString > & FoundFiles, const TCHAR * Directory, const TCHAR * FileExtension = nullptr) override virtual
Finds all the files within the given directory, with optional file extension filter.
Parameters
Directory,the absolute path to the directory to search. Ex: "C:\UE4\Pictures"
FileExtension,If FileExtension is NULL, or an empty string "" then all files are found. Otherwise FileExtension can be of the form .EXT or just EXT and only files with that extension will be returned.
Returns
FoundFiles, All the files that matched the optional FileExtension filter, or all files if none was specified.
Implements IFileManager.
FindFiles() [2/2]
void FFileManagerGeneric::FindFiles (TArray< FString > & FileNames, const TCHAR * Filename, bool Files, bool Directories) override virtual
Finds file or directories.
Implements IFileManager.
References Filename.
FindFilesRecursive()
void FFileManagerGeneric::FindFilesRecursive (TArray< FString > & FileNames, const TCHAR * StartDirectory, const TCHAR * Filename, bool Files, bool Directories, bool bClearFileNames = true) override virtual
Finds file or directories recursively.
Implements IFileManager.
References Filename.
FindFilesRecursiveInternal()
void FFileManagerGeneric::FindFilesRecursiveInternal (TArray< FString > & FileNames, const TCHAR * StartDirectory, const TCHAR * Filename, bool Files, bool Directories) private
References Filename.
GetAccessTimeStamp()
FDateTime FFileManagerGeneric::GetAccessTimeStamp (const TCHAR * Filename) override virtual
Returns
the last access time of the given file (or FDateTime::MinValue() on failure)
Implements IFileManager.
References Filename.
GetFileAgeSeconds()
double FFileManagerGeneric::GetFileAgeSeconds (const TCHAR * Filename) override virtual
Gets the age of a file measured in seconds.
Implements IFileManager.
References Filename.
GetFilenameOnDisk()
virtual FString FFileManagerGeneric::GetFilenameOnDisk (const TCHAR * Filename) override virtual
For case insensitive filesystems, returns the full path of the file with the same case as in the filesystem.
Parameters
Filename Filename to query
Returns
Filename with the same case as in the filesystem.
Implements IFileManager.
References Filename.
GetLowLevel()
FORCEINLINE IPlatformFile & FFileManagerGeneric::GetLowLevel () const inline private
Definition at line 39 of file FileManagerGeneric.h.
References FORCEINLINE, FPlatformFileManager::Get(), and FPlatformFileManager::GetPlatformFile().
Referenced by IsSandboxEnabled(), SendMessageToServer(), and SetSandboxEnabled().
GetStatData()
virtual FFileStatData FFileManagerGeneric::GetStatData (const TCHAR * FilenameOrDirectory) override virtual
Return the stat data for the given file or directory.
Check the FFileStatData::bIsValid member before using the returned data
Implements IFileManager.
GetTimeStamp()
FDateTime FFileManagerGeneric::GetTimeStamp (const TCHAR * Path) override virtual
Returns
the modification time of the given file (or FDateTime::MinValue() on failure)
Implements IFileManager.
References Filename.
GetTimeStampPair()
void FFileManagerGeneric::GetTimeStampPair (const TCHAR * PathA, const TCHAR * PathB, FDateTime & OutTimeStampA, FDateTime & OutTimeStampB) virtual
Parameters
[in] PathA The first given file
[in] PathB The second given file
[out] OutTimeStampA the modification time of the first given file (or FDateTime::MinValue() on failure)
[out] OutTimeStampB the modification time of the second given file (or FDateTime::MinValue() on failure)
Implements IFileManager.
IsReadOnly()
bool FFileManagerGeneric::IsReadOnly (const TCHAR * Filename) override virtual
Checks if a file is read-only.
Implements IFileManager.
References Filename.
IsSandboxEnabled()
virtual bool FFileManagerGeneric::IsSandboxEnabled () const inline override virtual
Returns whether the sandbox is enabled or not.
Implements IFileManager.
Definition at line 67 of file FileManagerGeneric.h.
References GetLowLevel(), and IPlatformFile::IsSandboxEnabled().
IterateDirectory() [1/2]
bool FFileManagerGeneric::IterateDirectory (const TCHAR * Directory, IPlatformFile::FDirectoryVisitor & Visitor) override virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
IterateDirectory() [2/2]
bool FFileManagerGeneric::IterateDirectory (const TCHAR * Directory, IPlatformFile::FDirectoryVisitorFunc Visitor) override virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
IterateDirectoryRecursively() [1/2]
bool FFileManagerGeneric::IterateDirectoryRecursively (const TCHAR * Directory, IPlatformFile::FDirectoryVisitor & Visitor) override virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories.
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
IterateDirectoryRecursively() [2/2]
bool FFileManagerGeneric::IterateDirectoryRecursively (const TCHAR * Directory, IPlatformFile::FDirectoryVisitorFunc Visitor) override virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories (see FDirectoryVisitor::Visit for the signature).
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
IterateDirectoryStat() [1/2]
bool FFileManagerGeneric::IterateDirectoryStat (const TCHAR * Directory, IPlatformFile::FDirectoryStatVisitor & Visitor) override virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
IterateDirectoryStat() [2/2]
bool FFileManagerGeneric::IterateDirectoryStat (const TCHAR * Directory, IPlatformFile::FDirectoryStatVisitorFunc Visitor) override virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryStatVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
IterateDirectoryStatRecursively() [1/2]
bool FFileManagerGeneric::IterateDirectoryStatRecursively (const TCHAR * Directory, IPlatformFile::FDirectoryStatVisitor & Visitor) override virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories.
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
IterateDirectoryStatRecursively() [2/2]
bool FFileManagerGeneric::IterateDirectoryStatRecursively (const TCHAR * Directory, IPlatformFile::FDirectoryStatVisitorFunc Visitor) override virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories (see FDirectoryStatVisitor::Visit for the signature).
Returns
false if the directory did not exist or if the visitor returned false.
Implements IFileManager.
MakeDirectory()
virtual bool FFileManagerGeneric::MakeDirectory (const TCHAR * Path, bool Tree = 0) override virtual
Creates a directory.
Implements IFileManager.
References Path.
Move()
bool FFileManagerGeneric::Move (const TCHAR * Dest, const TCHAR * Src, bool Replace = 1, bool EvenIfReadOnly = 0, bool Attributes = 0, bool bDoNotRetryOrError = 0) override virtual
Moves/renames a file.
Implements IFileManager.
References Replace.
ProcessCommandLineOptions()
virtual void FFileManagerGeneric::ProcessCommandLineOptions () override virtual
Allow the file manager to handle the commandline.
Implements IFileManager.
SendMessageToServer()
virtual bool FFileManagerGeneric::SendMessageToServer (const TCHAR * Message, IPlatformFile::IFileServerMessageHandler * Handler) inline override virtual
Sends a message to the file server, and will block until it's complete.
Will return immediately if the file manager doesn't support talking to a server.
Parameters
Message The string message to send to the server
Returns
true if the message was sent to server and it returned success, or false if there is no server, or the command failed
Implements IFileManager.
Definition at line 204 of file FileManagerGeneric.h.
References GetLowLevel(), and IPlatformFile::SendMessageToServer().
SetSandboxEnabled()
virtual void FFileManagerGeneric::SetSandboxEnabled (bool bInEnabled) inline override virtual
Enables/disables the sandbox, if it is being used.
Implements IFileManager.
Definition at line 62 of file FileManagerGeneric.h.
References GetLowLevel(), and IPlatformFile::SetSandboxEnabled().
SetTimeStamp()
bool FFileManagerGeneric::SetTimeStamp (const TCHAR * Path, FDateTime TimeStamp) override virtual
Sets the modification time of the given file.
Implements IFileManager.
References Filename.
The documentation for this class was generated from the following file:
FileManagerGeneric.h