Unreal Engine 5.6 C++ API: Metasound::MetasoundExecutableOperatorPrivate::TResetFunctionAdapter< OperatorType > Struct Template Reference
Metasound::MetasoundExecutableOperatorPrivate::TResetFunctionAdapter< OperatorType > Struct Template Reference
#include "MetasoundExecutableOperator.h"
Static Public Member Functions
static IOperator::FResetFunction GetResetFunction ()
Static Private Member Functions
static void ResetFunction (IOperator *InOperator, const IOperator::FResetParams &InParams)
Detailed Description
template<typename OperatorType>
struct Metasound::MetasoundExecutableOperatorPrivate::TResetFunctionAdapter< OperatorType >
Definition at line 45 of file MetasoundExecutableOperator.h.
Member Function Documentation
GetResetFunction()
template<typename OperatorType> IOperator::FResetFunction Metasound::MetasoundExecutableOperatorPrivate::TResetFunctionAdapter< OperatorType >::GetResetFunction () inline static
Definition at line 49 of file MetasoundExecutableOperator.h.
References ResetFunction(), and Metasound::MetasoundExecutableOperatorPrivate::TIsResetMethodDeclared< U >::Value.
Referenced by Metasound::TExecutableOperator< DerivedOperatorType >::GetResetFunction().
ResetFunction()
template<typename OperatorType> void Metasound::MetasoundExecutableOperatorPrivate::TResetFunctionAdapter< OperatorType >::ResetFunction (IOperator * InOperator, const IOperator::FResetParams & InParams) inline static private
Definition at line 62 of file MetasoundExecutableOperator.h.
References check, checkNoEntry, and Metasound::MetasoundExecutableOperatorPrivate::TIsResetMethodDeclared< U >::Value.
Referenced by GetResetFunction().
The documentation for this struct was generated from the following file:
MetasoundExecutableOperator.h