Unreal Engine 5.6 C++ API: UE::Geometry::FSmallListSet::MappedValueEnumerable Class Reference
UE::Geometry::FSmallListSet::MappedValueEnumerable Class Reference
MappedValueEnumerable is an object that provides begin/end semantics for a small list, suitable for use with a range-based for loop.
#include "SmallListSet.h"
Public Member Functions
MappedValueEnumerable ()
MappedValueEnumerable (const FSmallListSet *ListSetIn, int32 ListIndex, TFunction< int32(int32)> MapFunc)
FSmallListSet::MappedValueIterator begin () const
FSmallListSet::MappedValueIterator end () const
Data Fields
int32 ListIndex
const FSmallListSet * ListSet
TFunction< int32(int32)> MapFunc
Detailed Description
MappedValueEnumerable is an object that provides begin/end semantics for a small list, suitable for use with a range-based for loop.
Definition at line 634 of file SmallListSet.h.
Constructor & Destructor Documentation
MappedValueEnumerable() [1/2]
UE::Geometry::FSmallListSet::MappedValueEnumerable::MappedValueEnumerable () inline
Definition at line 640 of file SmallListSet.h.
MappedValueEnumerable() [2/2]
UE::Geometry::FSmallListSet::MappedValueEnumerable::MappedValueEnumerable (const FSmallListSet * ListSetIn, int32 ListIndex, TFunction< int32(int32)> MapFunc) inline
Definition at line 641 of file SmallListSet.h.
References ListIndex, MapFunc, and MoveTemp().
Member Function Documentation
begin()
FSmallListSet::MappedValueIterator UE::Geometry::FSmallListSet::MappedValueEnumerable::begin () const inline
Definition at line 647 of file SmallListSet.h.
References ListIndex, ListSet, and MapFunc.
end()
FSmallListSet::MappedValueIterator UE::Geometry::FSmallListSet::MappedValueEnumerable::end () const inline
Definition at line 648 of file SmallListSet.h.
References ListIndex, ListSet, and MapFunc.
Field Documentation
ListIndex
int32 UE::Geometry::FSmallListSet::MappedValueEnumerable::ListIndex
Definition at line 638 of file SmallListSet.h.
Referenced by MappedValueEnumerable(), begin(), and end().
ListSet
const FSmallListSet* UE::Geometry::FSmallListSet::MappedValueEnumerable::ListSet
Definition at line 637 of file SmallListSet.h.
Referenced by begin(), and end().
MapFunc
TFunction<int32(int32)> UE::Geometry::FSmallListSet::MappedValueEnumerable::MapFunc
Definition at line 639 of file SmallListSet.h.
Referenced by MappedValueEnumerable(), begin(), and end().
The documentation for this class was generated from the following file:
SmallListSet.h