Unreal Engine 5.6 C++ API: WorldPartitionStreamingSource.h File Reference
WorldPartitionStreamingSource.h File Reference
#include "Math/Color.h"
#include "Math/RandomStream.h"
#include "HAL/IConsoleManager.h"
#include "WorldPartitionStreamingSource.generated.h"
Data Structures
struct FSetStreamingSourceExtraAngle
struct FSetStreamingSourceExtraRadius
class FSphericalSector
See https://en.wikipedia.org/wiki/Spherical_sector.
class FStreamingSourceShapeHelper
Helper class used to iterate over streaming source shapes.
struct FWorldPartitionStreamingSource
Streaming Source Priority.
struct IWorldPartitionStreamingSourceProvider
Interface for world partition streaming sources.
Functions
UENUM() enum class EStreamingSourceTargetState const TCHAR * GetStreamingSourceTargetStateName (EStreamingSourceTargetState StreamingSourceTargetState)
Streaming Source Target State.
USTRUCT () struct FWorldPartitionStreamingQuerySource
Structure containing all properties required to query a streaming state.
Function Documentation
GetStreamingSourceTargetStateName()
UENUM() enum class EStreamingSourceTargetState const TCHAR * GetStreamingSourceTargetStateName (EStreamingSourceTargetState StreamingSourceTargetState) inline
Streaming Source Target State.
Definition at line 223 of file WorldPartitionStreamingSource.h.
References check, and TEXT.
USTRUCT()
USTRUCT ()
Structure containing all properties required to query a streaming state.
Defines how TargetGrids will be applied to this streaming source.
Helper method that iterates over all shapes. If none is provided, it will still pass a sphere shape using Radius or grid's loading range (see bUseGridLoadingRange).
Helper method that iterates over all shapes. If none is provided, it will still pass a sphere shape using Radius or grid's loading range (see bUseGridLoadingRange).
Definition at line 93 of file WorldPartitionStreamingSource.h.
References BlueprintType, Category, ForceInitToZero, FVector, GENERATED_BODY, GetTypeHash(), Hash, HashCombineFast(), Location, meta, Rotation, Streaming, ToString(), and UPROPERTY.