Unreal Engine 5.6 C++ API: FExternalPackageHelper Class Reference
FExternalPackageHelper Class Reference
#include "ExternalPackageHelper.h"
Data Structures
class FRenameExternalObjectsHelperContext
Public Types
enum class EGetExternalSaveableObjectsFlags : uint32 { None = 0 , CheckDirty = (1 << 0) }
Public Member Functions
DECLARE_EVENT_TwoParams (FExternalPackageHelper, FOnObjectPackagingModeChanged, UObject *, bool)
FRIEND_ENUM_CLASS_FLAGS (EGetExternalSaveableObjectsFlags)
Static Public Member Functions
static void CopyObjectsExternalPackageFilePathToClipboard (const TArray< const UObject * > &InObjects)
static UPackage * CreateExternalPackage (const UObject *InObjectOuter, const FString &InObjectPath, EPackageFlags InFlags=FExternalPackageHelper::GetDefaultExternalPackageFlags(), const UExternalDataLayerAsset *InExternalDataLayerAsset=nullptr)
Create an external package.
static void DuplicateExternalPackages (const UObject *InObject, FObjectDuplicationParameters &InDuplicationParameters, EActorPackagingScheme ActorPackagingScheme=EActorPackagingScheme::Reduced)
Duplicates all ExternalPackage for any UObject outered to InObject (UObject themselves are handled by regular DuplicateObject behavior)
static EPackageFlags GetDefaultExternalPackageFlags ()
Returns default external package flags used to create external packages.
static FString GetExternalObjectsPath (const FString &InOuterPackageName, const FString &InPackageShortName=FString())
Get the path containing the external objects for this path.
static FString GetExternalObjectsPath (UPackage *InPackage, const FString &InPackageShortName=FString(), bool bTryUsingPackageLoadedPath=false)
Get the path containing the external objects for this Outer.
static FString GetExternalPackageName (const FString &InOuterPackageName, const FString &InObjectPath)
Get the external package name for this object.
static void GetExternalSaveableObjects (UObject *InOuter, TArray< UObject * > &OutObjects, EGetExternalSaveableObjectsFlags InFlags=EGetExternalSaveableObjectsFlags::CheckDirty)
Get the saveable external objects that should be saved alongside this outer's package.
static TArray< FString > GetObjectsExternalPackageFilePath (const TArray< const UObject * > &InObjects)
Returns an array of external package file paths for the provided objects.
static void GetSortedAssets (const FARFilter &Filter, TArray< FAssetData > &OutAssets)
Call AssetRegistry.GetAssets and sort the results for deterministic use in cooked data.
template<typename T>
static void LoadObjectsFromExternalPackages (UObject *InOuter, TFunctionRef< void(T *)> Operation)
Loads objects from an external package.
static void SetPackagingMode (UObject *InObject, const UObject *InObjectOuter, bool bInIsPackageExternal, bool bInShouldDirty=true, EPackageFlags InExternalPackageFlags=FExternalPackageHelper::GetDefaultExternalPackageFlags())
Set the object packaging mode.
Static Public Attributes
static FOnObjectPackagingModeChanged OnObjectPackagingModeChanged
Static Private Member Functions
static FString GetExternalObjectPackageInstanceName (const FString &OuterPackageName, const FString &ObjectPackageName)
Get the external object package instance name.
Detailed Description
Definition at line 24 of file ExternalPackageHelper.h.
Member Enumeration Documentation
EGetExternalSaveableObjectsFlags
enum class FExternalPackageHelper::EGetExternalSaveableObjectsFlags : uint32 strong
Enumerator
None
CheckDirty
Definition at line 96 of file ExternalPackageHelper.h.
Member Function Documentation
CopyObjectsExternalPackageFilePathToClipboard()
void FExternalPackageHelper::CopyObjectsExternalPackageFilePathToClipboard (const TArray< const UObject * > & InObjects) static
CreateExternalPackage()
UPackage * FExternalPackageHelper::CreateExternalPackage (const UObject * InObjectOuter, const FString & InObjectPath, EPackageFlags InFlags = FExternalPackageHelper::GetDefaultExternalPackageFlags(), const UExternalDataLayerAsset * InExternalDataLayerAsset = nullptr) static
Create an external package.
Parameters
InObjectOuter the object's outer
InObjectPath the fully qualified object path, in the format: 'Outermost.Outer.Name'
InFlags the package flags to apply
Returns
the created package
References GetDefaultExternalPackageFlags().
Referenced by AWorldDataLayers::CreateDataLayer().
DECLARE_EVENT_TwoParams()
FExternalPackageHelper::DECLARE_EVENT_TwoParams (FExternalPackageHelper , FOnObjectPackagingModeChanged , UObject * , bool)
DuplicateExternalPackages()
void FExternalPackageHelper::DuplicateExternalPackages (const UObject * InObject, FObjectDuplicationParameters & InDuplicationParameters, EActorPackagingScheme ActorPackagingScheme = EActorPackagingScheme::Reduced) static
Duplicates all ExternalPackage for any UObject outered to InObject (UObject themselves are handled by regular DuplicateObject behavior)
FRIEND_ENUM_CLASS_FLAGS()
FExternalPackageHelper::FRIEND_ENUM_CLASS_FLAGS (EGetExternalSaveableObjectsFlags)
GetDefaultExternalPackageFlags()
EPackageFlags FExternalPackageHelper::GetDefaultExternalPackageFlags () static
Returns default external package flags used to create external packages.
Referenced by AWorldDataLayers::CreateDataLayer(), CreateExternalPackage(), and SetPackagingMode().
GetExternalObjectPackageInstanceName()
FString FExternalPackageHelper::GetExternalObjectPackageInstanceName (const FString & OuterPackageName, const FString & ObjectPackageName) static private
Get the external object package instance name.
Referenced by LoadObjectsFromExternalPackages().
GetExternalObjectsPath() [1/2]
FString FExternalPackageHelper::GetExternalObjectsPath (const FString & InOuterPackageName, const FString & InPackageShortName = FString()) static
Get the path containing the external objects for this path.
Parameters
InOuterPackageName The package name to get the external objects path of
InPackageShortName Optional short name to use instead of the package short name
Returns
the path
Referenced by LoadObjectsFromExternalPackages().
GetExternalObjectsPath() [2/2]
FString FExternalPackageHelper::GetExternalObjectsPath (UPackage * InPackage, const FString & InPackageShortName = FString(), bool bTryUsingPackageLoadedPath = false) static
Get the path containing the external objects for this Outer.
Parameters
InPackage The package to get the external objects path of
InPackageShortName Optional short name to use instead of the package short name
Returns
the path
GetExternalPackageName()
FString FExternalPackageHelper::GetExternalPackageName (const FString & InOuterPackageName, const FString & InObjectPath) static
Get the external package name for this object.
Parameters
InOuterPackageName The name of the package of that contains the outer of the object.
InObjectPath the fully qualified object path, in the format: 'Outermost.Outer.Name'
Returns
the package name
References InOuter.
GetExternalSaveableObjects()
void FExternalPackageHelper::GetExternalSaveableObjects (UObject * InOuter, TArray< UObject * > & OutObjects, EGetExternalSaveableObjectsFlags InFlags = EGetExternalSaveableObjectsFlags::CheckDirty) static
Get the saveable external objects that should be saved alongside this outer's package.
Parameters
InOuter The external object's outer
OutObjects The objects that should be saved
InFlags Flags controlling behavior
See also
EGetExternalSaveableObjectsFlags
References CheckDirty, and InOuter.
GetObjectsExternalPackageFilePath()
TArray< FString > FExternalPackageHelper::GetObjectsExternalPackageFilePath (const TArray< const UObject * > & InObjects) static
Returns an array of external package file paths for the provided objects.
Parameters
InObjects The objects to process
GetSortedAssets()
void FExternalPackageHelper::GetSortedAssets (const FARFilter & Filter, TArray< FAssetData > & OutAssets) static
Call AssetRegistry.GetAssets and sort the results for deterministic use in cooked data.
References Filter.
Referenced by LoadObjectsFromExternalPackages().
LoadObjectsFromExternalPackages()
template<typename T> void FExternalPackageHelper::LoadObjectsFromExternalPackages (UObject * InOuter, TFunctionRef< void(T *)> Operation) static
Loads objects from an external package.
Definition at line 141 of file ExternalPackageHelper.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), FLinkerInstancingContext::AddPackageMapping(), Asset, Cast(), CastChecked(), check, Class, ClassPaths, CreatePackage(), ensure, Filter, FCoreRedirects::FindPreviousNames(), ForEachObjectWithPackage(), GetDerivedClasses(), FExternalDataLayerHelper::GetExternalDataLayerLevelRootPath(), GetExternalObjectPackageInstanceName(), GetExternalObjectsPath(), UObjectBase::GetFName(), UPackage::GetLoadedPath(), UObjectBaseUtility::GetName(), UObjectBase::GetOuter(), UObjectBaseUtility::GetPackage(), FPackagePath::GetPackageFName(), FPackagePath::GetPackageName(), IDataLayerInstanceProvider::GetRootExternalDataLayerAsset(), GetSortedAssets(), UObjectBaseUtility::HasAnyFlags(), InOuter, FPackagePath::IsEmpty(), FName::IsNone(), LOAD_None, LOAD_PackageForPIE, LoadFlags, FModuleManager::LoadModuleChecked(), LoadObjectsFromExternalPackages(), LoadPackage, MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), Object, Package, PKG_PlayInEditor, FLinkerInstancingContext::RemapPackage(), TArray< InElementType, InAllocatorType >::Reserve(), RF_NoFlags, RF_Transient, UObjectBaseUtility::SetFlags(), TEXT, FName::ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, Type_Class, and Unreachable.
Referenced by LoadObjectsFromExternalPackages().
SetPackagingMode()
void FExternalPackageHelper::SetPackagingMode (UObject * InObject, const UObject * InObjectOuter, bool bInIsPackageExternal, bool bInShouldDirty = true, EPackageFlags InExternalPackageFlags = FExternalPackageHelper::GetDefaultExternalPackageFlags()) static
Set the object packaging mode.
Parameters
InObject the object on which to change the packaging mode
InObjectOuter the object's outer
bInIsPackageExternal will set the object packaging mode to external if true, to internal otherwise
bInShouldDirty should dirty or not the object's outer package
InExternalPackageFlags the flags to apply to the external package if bInIsPackageExternal is true
References GetDefaultExternalPackageFlags().
Field Documentation
OnObjectPackagingModeChanged
FOnObjectPackagingModeChanged FExternalPackageHelper::OnObjectPackagingModeChanged static
Definition at line 41 of file ExternalPackageHelper.h.
The documentation for this class was generated from the following file:
ExternalPackageHelper.h