Unreal Engine 5.6 C++ API: TGCObjectsScopeGuard< ObjectType > Class Template Reference
TGCObjectsScopeGuard< ObjectType > Class Template Reference
Specific implementation of FGCObject that prevents an array of UObject-based pointers from being GC'd while this guard is in scope.
#include "GCObjectScopeGuard.h"
Public Member Functions
TGCObjectsScopeGuard (const TArray< ObjectType * > &InObjects)
TGCObjectsScopeGuard (const TGCObjectsScopeGuard &)=delete
Non-copyable.
virtual ~TGCObjectsScopeGuard ()
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
FORCEINLINE_DEBUGGABLE const TArray< ObjectType * > & Get () const
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
TGCObjectsScopeGuard & operator= (const TGCObjectsScopeGuard &)=delete
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Private Attributes
TArray< TObjectPtr< ObjectType > > Objects
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Detailed Description
template<typename ObjectType>
class TGCObjectsScopeGuard< ObjectType >
Specific implementation of FGCObject that prevents an array of UObject-based pointers from being GC'd while this guard is in scope.
Definition at line 56 of file GCObjectScopeGuard.h.
Constructor & Destructor Documentation
TGCObjectsScopeGuard() [1/2]
template<typename ObjectType> TGCObjectsScopeGuard< ObjectType >::TGCObjectsScopeGuard (const TArray< ObjectType * > & InObjects) inline explicit
Definition at line 61 of file GCObjectScopeGuard.h.
References Objects.
Referenced by TGCObjectsScopeGuard(), and operator=().
~TGCObjectsScopeGuard()
template<typename ObjectType> virtual TGCObjectsScopeGuard< ObjectType >::~TGCObjectsScopeGuard () inline virtual
Definition at line 66 of file GCObjectScopeGuard.h.
TGCObjectsScopeGuard() [2/2]
template<typename ObjectType> TGCObjectsScopeGuard< ObjectType >::TGCObjectsScopeGuard (const TGCObjectsScopeGuard< ObjectType > &) delete
Non-copyable.
References TGCObjectsScopeGuard().
Member Function Documentation
AddReferencedObjects()
template<typename ObjectType> virtual void TGCObjectsScopeGuard< ObjectType >::AddReferencedObjects (FReferenceCollector & Collector) inline override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Definition at line 75 of file GCObjectScopeGuard.h.
References Objects.
Get()
template<typename ObjectType> FORCEINLINE_DEBUGGABLE const TArray< ObjectType * > & TGCObjectsScopeGuard< ObjectType >::Get () const inline
Definition at line 85 of file GCObjectScopeGuard.h.
References FORCEINLINE_DEBUGGABLE, and Objects.
GetReferencerName()
template<typename ObjectType> virtual FString TGCObjectsScopeGuard< ObjectType >::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 80 of file GCObjectScopeGuard.h.
References TEXT.
operator=()
template<typename ObjectType> TGCObjectsScopeGuard & TGCObjectsScopeGuard< ObjectType >::operator= (const TGCObjectsScopeGuard< ObjectType > &) delete
References TGCObjectsScopeGuard().
Field Documentation
Objects
template<typename ObjectType> TArray<TObjectPtr<ObjectType> > TGCObjectsScopeGuard< ObjectType >::Objects private
Definition at line 91 of file GCObjectScopeGuard.h.
Referenced by TGCObjectsScopeGuard(), AddReferencedObjects(), and Get().
The documentation for this class was generated from the following file:
GCObjectScopeGuard.h