Unreal Engine 5.6 C++ API: UE::MovieScene::TMemberFunctionTaskWrapper< ClassType > Struct Template Reference
UE::MovieScene::TMemberFunctionTaskWrapper< ClassType > Struct Template Reference
#include "IMovieSceneTaskScheduler.h"
Public Types
using MemberFunctionPtr = void (ClassType::*)()
Public Member Functions
TMemberFunctionTaskWrapper (ClassType *InClassPtr, MemberFunctionPtr InFunctionPtr)
Public Member Functions inherited from UE::MovieScene::ITaskContext
virtual ~ITaskContext ()
Static Public Member Functions
static void Execute (const ITaskContext *Context, FEntityAllocationWriteContext WriteContext)
Data Fields
ClassType * ClassPtr
MemberFunctionPtr FunctionPtr
Detailed Description
template<typename ClassType>
struct UE::MovieScene::TMemberFunctionTaskWrapper< ClassType >
Definition at line 134 of file IMovieSceneTaskScheduler.h.
Member Typedef Documentation
MemberFunctionPtr
template<typename ClassType> using UE::MovieScene::TMemberFunctionTaskWrapper< ClassType >::MemberFunctionPtr = void (ClassType::*)()
Definition at line 136 of file IMovieSceneTaskScheduler.h.
Constructor & Destructor Documentation
TMemberFunctionTaskWrapper()
template<typename ClassType> UE::MovieScene::TMemberFunctionTaskWrapper< ClassType >::TMemberFunctionTaskWrapper (ClassType * InClassPtr, MemberFunctionPtr InFunctionPtr) inline explicit
Definition at line 141 of file IMovieSceneTaskScheduler.h.
References ClassPtr, and FunctionPtr.
Referenced by Execute().
Member Function Documentation
Execute()
template<typename ClassType> void UE::MovieScene::TMemberFunctionTaskWrapper< ClassType >::Execute (const ITaskContext * Context, FEntityAllocationWriteContext WriteContext) inline static
Definition at line 146 of file IMovieSceneTaskScheduler.h.
References TMemberFunctionTaskWrapper(), and UE::MovieScene::This.
Referenced by UE::MovieScene::IEntitySystemScheduler::AddMemberFunctionTask().
Field Documentation
ClassPtr
template<typename ClassType> ClassType* UE::MovieScene::TMemberFunctionTaskWrapper< ClassType >::ClassPtr
Definition at line 138 of file IMovieSceneTaskScheduler.h.
Referenced by TMemberFunctionTaskWrapper().
FunctionPtr
template<typename ClassType> MemberFunctionPtr UE::MovieScene::TMemberFunctionTaskWrapper< ClassType >::FunctionPtr
Definition at line 139 of file IMovieSceneTaskScheduler.h.
Referenced by TMemberFunctionTaskWrapper().
The documentation for this struct was generated from the following file:
IMovieSceneTaskScheduler.h