Unreal Engine 5.6 C++ API: LWCSerializerPrivate Namespace Reference
LWCSerializerPrivate Namespace Reference
Functions
bool IsPreLWC (const FArchive &Ar)
bool IsPreLWC (const FStructuredArchive::FSlot &Slot)
template<typename FAltType, typename FType, typename FArSlot>
std::enable_if_t< std::is_floating_point_v< typename FType::FReal >, bool > SerializeFromMismatchedTag (FType &Target, FName StructTag, FArSlot &ArSlot, FName BaseTag, FName ThisTag, FName AltTag)
template<typename FAltType, typename FType, typename FArSlot>
std::enable_if_t< std::is_integral_v< typename FType::IntType >, bool > SerializeFromMismatchedTag (FType &Target, FName StructTag, FArSlot &ArSlot, FName BaseTag, FName ThisTag, FName AltTag)
Function Documentation
IsPreLWC() [1/2]
bool LWCSerializerPrivate::IsPreLWC (const FArchive & Ar) inline
Definition at line 13 of file LargeWorldCoordinatesSerializer.h.
References Ar, and LARGE_WORLD_COORDINATES.
Referenced by IsPreLWC(), and SerializeFromMismatchedTag().
IsPreLWC() [2/2]
bool LWCSerializerPrivate::IsPreLWC (const FStructuredArchive::FSlot & Slot) inline
Definition at line 14 of file LargeWorldCoordinatesSerializer.h.
References UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), and IsPreLWC().
SerializeFromMismatchedTag() [1/2]
template<typename FAltType, typename FType, typename FArSlot> std::enable_if_t< std::is_floating_point_v< typename FType::FReal >, bool > LWCSerializerPrivate::SerializeFromMismatchedTag (FType & Target, FName StructTag, FArSlot & ArSlot, FName BaseTag, FName ThisTag, FName AltTag)
Definition at line 18 of file LargeWorldCoordinatesSerializer.h.
References IsPreLWC(), Target, and TIsUECoreVariant< T, typename, typename >::Value.
SerializeFromMismatchedTag() [2/2]
template<typename FAltType, typename FType, typename FArSlot> std::enable_if_t< std::is_integral_v< typename FType::IntType >, bool > LWCSerializerPrivate::SerializeFromMismatchedTag (FType & Target, FName StructTag, FArSlot & ArSlot, FName BaseTag, FName ThisTag, FName AltTag)
Definition at line 39 of file LargeWorldCoordinatesSerializer.h.
References Target, and TIsUECoreVariant< T, typename, typename >::Value.