Unreal Engine 5.6 C++ API: FSdfGlyphTaskKey Struct Reference
FSdfGlyphTaskKey Struct Reference
Used to lookup information about specific SDF generation tasks - unlike FSdfGlyphEntryKey is also identified by em spread.
#include "FontCache.h"
Public Member Functions
FORCEINLINE FSdfGlyphTaskKey (const FSdfGlyphEntryKey &InSdfGlyphEntryKey, float InEmOuterSpread, float InEmInnerSpread)
FORCEINLINE bool operator!= (const FSdfGlyphTaskKey &Other) const
FORCEINLINE bool operator== (const FSdfGlyphTaskKey &Other) const
Data Fields
float EmInnerSpread
Inner portion of distance field spread in em.
float EmOuterSpread
Outer portion of distance field spread in em.
const FSdfGlyphEntryKey SdfGlyphEntryKey
Glyph entry key.
Private Attributes
uint32 KeyHash
Cached hash value used for map lookups.
Friends
uint32 GetTypeHash (const FSdfGlyphTaskKey &Key)
Detailed Description
Used to lookup information about specific SDF generation tasks - unlike FSdfGlyphEntryKey is also identified by em spread.
Definition at line 298 of file FontCache.h.
Constructor & Destructor Documentation
FSdfGlyphTaskKey()
FORCEINLINE FSdfGlyphTaskKey::FSdfGlyphTaskKey (const FSdfGlyphEntryKey & InSdfGlyphEntryKey, float InEmOuterSpread, float InEmInnerSpread)
References FORCEINLINE.
Referenced by GetTypeHash, operator!=(), and operator==().
Member Function Documentation
operator!=()
FORCEINLINE bool FSdfGlyphTaskKey::operator!= (const FSdfGlyphTaskKey & Other) const inline
Definition at line 310 of file FontCache.h.
References FSdfGlyphTaskKey(), FORCEINLINE, and Other.
operator==()
FORCEINLINE bool FSdfGlyphTaskKey::operator== (const FSdfGlyphTaskKey & Other) const inline
Definition at line 303 of file FontCache.h.
References FSdfGlyphTaskKey(), EmInnerSpread, EmOuterSpread, FORCEINLINE, Other, and SdfGlyphEntryKey.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSdfGlyphTaskKey & Key) friend
Definition at line 315 of file FontCache.h.
References FSdfGlyphTaskKey(), and Key.
Field Documentation
EmInnerSpread
float FSdfGlyphTaskKey::EmInnerSpread
Inner portion of distance field spread in em.
Definition at line 325 of file FontCache.h.
Referenced by operator==().
EmOuterSpread
float FSdfGlyphTaskKey::EmOuterSpread
Outer portion of distance field spread in em.
Definition at line 323 of file FontCache.h.
Referenced by operator==().
KeyHash
uint32 FSdfGlyphTaskKey::KeyHash private
Cached hash value used for map lookups.
Definition at line 329 of file FontCache.h.
SdfGlyphEntryKey
const FSdfGlyphEntryKey FSdfGlyphTaskKey::SdfGlyphEntryKey
Glyph entry key.
Definition at line 321 of file FontCache.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
FontCache.h