Unreal Engine 5.6 C++ API: FGenericPlatformStricmp Struct Reference
FGenericPlatformStricmp Struct Reference
Optimized locale and CRT independent case-insensitive string comparisons.
#include "GenericPlatformStricmp.h"
Static Public Member Functions
static int32 Stricmp (const ANSICHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const WIDECHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const WIDECHAR *String2)
static int32 Strnicmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
Detailed Description
Optimized locale and CRT independent case-insensitive string comparisons.
Only considers ASCII character casing, i.e. C locale semantics
Returns
Zero if strings are equal, greater than zero if first string is greater than the second one and less than zero otherwise.
Definition at line 15 of file GenericPlatformStricmp.h.
Member Function Documentation
Stricmp() [1/13]
int32 FGenericPlatformStricmp::Stricmp (const ANSICHAR * String1, const ANSICHAR * String2) static
Referenced by TCString< T >::Stricmp().
Stricmp() [2/13]
int32 FGenericPlatformStricmp::Stricmp (const ANSICHAR * String1, const UTF16CHAR * String2) static
Stricmp() [3/13]
int32 FGenericPlatformStricmp::Stricmp (const ANSICHAR * String1, const UTF32CHAR * String2) static
Stricmp() [4/13]
int32 FGenericPlatformStricmp::Stricmp (const ANSICHAR * String1, const UTF8CHAR * String2) static
Stricmp() [5/13]
int32 FGenericPlatformStricmp::Stricmp (const ANSICHAR * String1, const WIDECHAR * String2) static
Stricmp() [6/13]
int32 FGenericPlatformStricmp::Stricmp (const UTF16CHAR * String1, const ANSICHAR * String2) static
Stricmp() [7/13]
int32 FGenericPlatformStricmp::Stricmp (const UTF16CHAR * String1, const UTF16CHAR * String2) static
Stricmp() [8/13]
int32 FGenericPlatformStricmp::Stricmp (const UTF32CHAR * String1, const ANSICHAR * String2) static
Stricmp() [9/13]
int32 FGenericPlatformStricmp::Stricmp (const UTF32CHAR * String1, const UTF32CHAR * String2) static
Stricmp() [10/13]
int32 FGenericPlatformStricmp::Stricmp (const UTF8CHAR * String1, const ANSICHAR * String2) static
Stricmp() [11/13]
int32 FGenericPlatformStricmp::Stricmp (const UTF8CHAR * String1, const UTF8CHAR * String2) static
Stricmp() [12/13]
int32 FGenericPlatformStricmp::Stricmp (const WIDECHAR * String1, const ANSICHAR * String2) static
Stricmp() [13/13]
int32 FGenericPlatformStricmp::Stricmp (const WIDECHAR * String1, const WIDECHAR * String2) static
Strnicmp() [1/13]
int32 FGenericPlatformStricmp::Strnicmp (const ANSICHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Referenced by TStringView< CharType >::Compare(), TStringView< CharType >::PrivateCompare(), TStringView< CharType >::PrivateEquals(), and TCString< T >::Strnicmp().
Strnicmp() [2/13]
int32 FGenericPlatformStricmp::Strnicmp (const ANSICHAR * String1, const UTF16CHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [3/13]
int32 FGenericPlatformStricmp::Strnicmp (const ANSICHAR * String1, const UTF32CHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [4/13]
int32 FGenericPlatformStricmp::Strnicmp (const ANSICHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [5/13]
int32 FGenericPlatformStricmp::Strnicmp (const ANSICHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [6/13]
int32 FGenericPlatformStricmp::Strnicmp (const UTF16CHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [7/13]
int32 FGenericPlatformStricmp::Strnicmp (const UTF16CHAR * String1, const UTF16CHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [8/13]
int32 FGenericPlatformStricmp::Strnicmp (const UTF32CHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [9/13]
int32 FGenericPlatformStricmp::Strnicmp (const UTF32CHAR * String1, const UTF32CHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [10/13]
int32 FGenericPlatformStricmp::Strnicmp (const UTF8CHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [11/13]
int32 FGenericPlatformStricmp::Strnicmp (const UTF8CHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [12/13]
int32 FGenericPlatformStricmp::Strnicmp (const WIDECHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
References Count.
Strnicmp() [13/13]
int32 FGenericPlatformStricmp::Strnicmp (const WIDECHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
References Count.
The documentation for this struct was generated from the following file:
GenericPlatformStricmp.h