Unreal Engine 5.6 C++ API: FOptionalPropertyLayout Struct Reference
FOptionalPropertyLayout Struct Reference
#include "PropertyOptional.h"
Public Member Functions
FOptionalPropertyLayout (FProperty *InValueProperty)
FORCEINLINE int32 CalcSize () const
FORCEINLINE const void * GetValuePointerForRead (const void *Data) const
FORCEINLINE const void * GetValuePointerForReadIfSet (const void *Data) const
FORCEINLINE const void * GetValuePointerForReadOrReplace (const void *Data) const
FORCEINLINE void * GetValuePointerForReadOrReplace (void *Data) const
FORCEINLINE const void * GetValuePointerForReadOrReplaceIfSet (const void *Data) const
FORCEINLINE void * GetValuePointerForReadOrReplaceIfSet (void *Data) const
FORCEINLINE void * GetValuePointerForReplace (void *Data) const
FORCEINLINE void * GetValuePointerForReplaceIfSet (void *Data) const
FProperty * GetValueProperty () const
FORCEINLINE bool IsSet (const void *Data) const
FORCEINLINE void * MarkSetAndGetInitializedValuePointerToReplace (void *Data) const
FORCEINLINE void MarkUnset (void *Data) const
Protected Member Functions
FOptionalPropertyLayout ()
FORCEINLINE int32 CalcIsSetOffset () const
FORCEINLINE const bool * GetIsSetPointer (const void *Data) const
FORCEINLINE bool * GetIsSetPointer (void *Data) const
Protected Attributes
FProperty * ValueProperty
Detailed Description
Definition at line 14 of file PropertyOptional.h.
Constructor & Destructor Documentation
FOptionalPropertyLayout() [1/2]
FOptionalPropertyLayout::FOptionalPropertyLayout (FProperty * InValueProperty) inline explicit
Definition at line 16 of file PropertyOptional.h.
References check, and ValueProperty.
FOptionalPropertyLayout() [2/2]
FOptionalPropertyLayout::FOptionalPropertyLayout () inline protected
Definition at line 153 of file PropertyOptional.h.
References ValueProperty.
Member Function Documentation
CalcIsSetOffset()
FORCEINLINE int32 FOptionalPropertyLayout::CalcIsSetOffset () const inline protected
Definition at line 158 of file PropertyOptional.h.
References Align(), check, checkfSlow, FORCEINLINE, TEXT, and ValueProperty.
Referenced by CalcSize(), GetIsSetPointer(), and GetIsSetPointer().
CalcSize()
FORCEINLINE int32 FOptionalPropertyLayout::CalcSize () const inline
Definition at line 139 of file PropertyOptional.h.
References Align, CalcIsSetOffset(), FORCEINLINE, and ValueProperty.
GetIsSetPointer() [1/2]
FORCEINLINE const bool * FOptionalPropertyLayout::GetIsSetPointer (const void * Data) const inline protected
Definition at line 174 of file PropertyOptional.h.
References CalcIsSetOffset(), and FORCEINLINE.
GetIsSetPointer() [2/2]
FORCEINLINE bool * FOptionalPropertyLayout::GetIsSetPointer (void * Data) const inline protected
Definition at line 170 of file PropertyOptional.h.
References CalcIsSetOffset(), and FORCEINLINE.
Referenced by IsSet(), MarkSetAndGetInitializedValuePointerToReplace(), and MarkUnset().
GetValuePointerForRead()
FORCEINLINE const void * FOptionalPropertyLayout::GetValuePointerForRead (const void * Data) const inline
Definition at line 78 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValuePointerForReadIfSet()
FORCEINLINE const void * FOptionalPropertyLayout::GetValuePointerForReadIfSet (const void * Data) const inline
Definition at line 95 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValuePointerForReadOrReplace() [1/2]
FORCEINLINE const void * FOptionalPropertyLayout::GetValuePointerForReadOrReplace (const void * Data) const inline
Definition at line 113 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValuePointerForReadOrReplace() [2/2]
FORCEINLINE void * FOptionalPropertyLayout::GetValuePointerForReadOrReplace (void * Data) const inline
Definition at line 118 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValuePointerForReadOrReplaceIfSet() [1/2]
FORCEINLINE const void * FOptionalPropertyLayout::GetValuePointerForReadOrReplaceIfSet (const void * Data) const inline
Definition at line 128 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValuePointerForReadOrReplaceIfSet() [2/2]
FORCEINLINE void * FOptionalPropertyLayout::GetValuePointerForReadOrReplaceIfSet (void * Data) const inline
Definition at line 133 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValuePointerForReplace()
FORCEINLINE void * FOptionalPropertyLayout::GetValuePointerForReplace (void * Data) const inline
Definition at line 86 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValuePointerForReplaceIfSet()
FORCEINLINE void * FOptionalPropertyLayout::GetValuePointerForReplaceIfSet (void * Data) const inline
Definition at line 104 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, and IsSet().
GetValueProperty()
FProperty * FOptionalPropertyLayout::GetValueProperty () const inline
Definition at line 22 of file PropertyOptional.h.
References checkf, TEXT, and ValueProperty.
IsSet()
FORCEINLINE bool FOptionalPropertyLayout::IsSet (const void * Data) const inline
Definition at line 28 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, GetIsSetPointer(), and ValueProperty.
Referenced by GetValuePointerForRead(), GetValuePointerForReadIfSet(), GetValuePointerForReadOrReplace(), GetValuePointerForReadOrReplace(), GetValuePointerForReadOrReplaceIfSet(), GetValuePointerForReadOrReplaceIfSet(), GetValuePointerForReplace(), GetValuePointerForReplaceIfSet(), and MarkSetAndGetInitializedValuePointerToReplace().
MarkSetAndGetInitializedValuePointerToReplace()
FORCEINLINE void * FOptionalPropertyLayout::MarkSetAndGetInitializedValuePointerToReplace (void * Data) const inline
Definition at line 35 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, GetIsSetPointer(), IsSet(), and ValueProperty.
MarkUnset()
FORCEINLINE void FOptionalPropertyLayout::MarkUnset (void * Data) const inline
Definition at line 58 of file PropertyOptional.h.
References checkSlow, FORCEINLINE, GetIsSetPointer(), and ValueProperty.
Field Documentation
ValueProperty
FProperty* FOptionalPropertyLayout::ValueProperty protected
Definition at line 156 of file PropertyOptional.h.
Referenced by FOptionalPropertyLayout(), FOptionalPropertyLayout(), CalcIsSetOffset(), CalcSize(), GetValueProperty(), IsSet(), MarkSetAndGetInitializedValuePointerToReplace(), and MarkUnset().
The documentation for this struct was generated from the following file:
PropertyOptional.h