Unreal Engine 5.6 C++ API: FSlateApplication Class Reference
FSlateApplication Class Reference
#include "SlateApplication.h"
Data Structures
struct FScopedPreventDebuggingMode
class InputPreProcessorsHelper
A helper class to wrap the list of input pre-processors.
Public Member Functions
virtual ~FSlateApplication ()
Virtual destructor.
void ActivateGameViewport ()
Activates the Game Viewport if it is properly childed under a window.
void AddModalWindow (TSharedRef< SWindow > InSlateWindow, const TSharedPtr< const SWidget > InParentWidget, bool bSlowTaskWindow=false)
Adds a modal window to the application.
virtual TSharedRef< SWindow > AddWindow (TSharedRef< SWindow > InSlateWindow, const bool bShowImmediately=true) override
Associates a top level Slate Window with a native window and ensures that it is tracked properly by the application.
TSharedRef< SWindow > AddWindowAsNativeChild (TSharedRef< SWindow > InSlateWindow, TSharedRef< SWindow > InParentWindow, const bool bShowImmediately=true)
Associates a top level Slate Window with a native window, and "natively" parents that window to the specified Slate window.
bool AllowMoveCursor ()
virtual bool AnyMenusVisible () const override
bool AreMenuAnimationsEnabled () const
virtual void ArrangeWindowToFrontVirtual (TArray< TSharedRef< SWindow > > &Windows, const TSharedRef< SWindow > &WindowToBringToFront) override
Reorders an array of windows so the specified window is "brought to the front".
virtual bool BeginReshapingWindow (const TSharedRef< FGenericWindow > &PlatformWindow) override
virtual UE::Slate::FDeprecateVector2DResult CalculatePopupWindowPosition (const FSlateRect &InAnchor, const UE::Slate::FDeprecateVector2DParameter &InSize, bool bAutoAdjustForDPIScale=true, const UE::Slate::FDeprecateVector2DParameter &InProposedPlacement=FVector2f::ZeroVector, const EOrientation Orientation=Orient_Vertical, const EPopupLayoutMode=EPopupLayoutMode::Menu) const
Calculates the popup window position from the passed in window position and size.
virtual UE::Slate::FDeprecateVector2DResult CalculateTooltipWindowPosition (const FSlateRect &InAnchorRect, const UE::Slate::FDeprecateVector2DParameter &InSize, bool bAutoAdjustForDPIScale, EPopupCursorOverlapMode CursorOverlapMode=EPopupCursorOverlapMode::PreventOverlap) const
Calculates the tooltip window position.
bool CanAddModalWindow () const
Returns true if this slate application is ready to open modal windows.
void CancelDragDrop ()
Cancels any in flight drag and drops.
bool CanDisplayWindows () const
Returns true if this slate application is ready to display windows.
void ClearAllUserFocus (EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Releases the focus for all users from whatever it currently is on.
void ClearKeyboardFocus (const EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Clears keyboard focus, if any widget is currently focused.
void ClearUserFocus (uint32 UserIndex, EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Releases the users focus from whatever it currently is on.
void CloseAllWindowsImmediately ()
Closes all active windows immediately.
void CloseToolTip ()
Closes the open tool-tip, if a tool-tip is open.
DECLARE_EVENT_OneParam (FSlateApplication, FApplicationActivationStateChangedEvent, const bool) virtual FApplicationActivationStateChangedEvent &OnApplicationActivationStateChanged()
DECLARE_EVENT_OneParam (FSlateApplication, FOnApplicationMousePreInputButtonDownListener, const FPointerEvent &)
Gets a delegate that is invoked before the mouse input button down get process by slate widgets bubble system.
DECLARE_EVENT_OneParam (FSlateApplication, FOnApplicationPreInputKeyDownListener, const FKeyEvent &)
Gets a delegate that is invoked before the input key get process by slate widgets bubble system.
DECLARE_EVENT_OneParam (FSlateApplication, FOnModalLoopTickEvent, float)
Event type for when Slate is ticking during a modal dialog loop.
DECLARE_EVENT_OneParam (FSlateApplication, FOnWindowBeingDestroyed, const SWindow &)
Delegate called when a window is about to be destroyed.
DECLARE_EVENT_OneParam (FSlateApplication, FOnWindowDPIScaleChanged, TSharedRef< SWindow >)
Gets a delegate that is invoked in the editor when a windows dpi scale changes or when a widget window may have changed and DPI scale info needs to be checked.
DECLARE_EVENT_OneParam (FSlateApplication, FSlateLastUserInteractionTimeUpdateEvent, double)
DECLARE_EVENT_OneParam (FSlateApplication, FSlateTickEvent, float)
Event before slate application ticks.
DECLARE_EVENT_OneParam (FSlateApplication, FUserRegisteredEvent, int32)
Delegate for when a new user has been registered.
DECLARE_MULTICAST_DELEGATE_FiveParams (FOnFocusChanging, const FFocusEvent &, const FWeakWidgetPath &, const TSharedPtr< SWidget > &, const FWidgetPath &, const TSharedPtr< SWidget > &)
Delegate called just before possible focus change.
void DestroyWindowImmediately (TSharedRef< SWindow > WindowToDestroy)
HACK: Don't use this unless shutting down a game viewport Game viewport windows need to be destroyed instantly or else the viewport could tick and access deleted data.
void DestroyWindowsImmediately ()
Destroy the native and slate windows in the array provided.
void DismissAllMenus ()
Dismisses all open menus.
void DismissMenu (const TSharedPtr< IMenu > &InFromMenu)
Dismisses a menu and all its children.
void DismissMenuByWidget (const TSharedRef< SWidget > &InWidgetInMenu)
Dismisses a menu and all its children.
void EnterDebuggingMode ()
Enters debugging mode which is a special state that causes the Slate application to tick in place which in the middle of a stack frame.
void ExternalModalStart ()
Disable Slate components when an external, non-slate, modal window is brought up.
void ExternalModalStop ()
Re-enable disabled Slate components when a non-slate modal window is dismissed.
void ExternalUIChange (bool bIsOpening)
Sets the display state of external UI such as Steam.
TSharedPtr< SWindow > FindBestParentWindowForDialogs (const TSharedPtr< SWidget > &InWidget, const ESlateParentWindowSearchMethod InParentWindowSearchMethod=ESlateParentWindowSearchMethod::ActiveWindow)
Given an optional widget, try and get the most suitable parent window to use with dialogs (such as file and directory pickers).
const void * FindBestParentWindowHandleForDialogs (const TSharedPtr< SWidget > &InWidget, const ESlateParentWindowSearchMethod InParentWindowSearchMethod=ESlateParentWindowSearchMethod::ActiveWindow)
Given an optional widget, try and get the most suitable parent window handle to use with dialogs (such as file and directory pickers).
int32 FindInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const EInputPreProcessorType &Type) const
Get the index of a registered pre-processor.
TSharedPtr< IMenu > FindMenuInWidgetPath (const FWidgetPath &InWidgetPath) const
Attempt to locate a menu that contains the specified widget.
TSharedRef< FSlateVirtualUserHandle > FindOrCreateVirtualUser (int32 VirtualUserIndex)
virtual bool FindPathToWidget (TSharedRef< const SWidget > InWidget, FWidgetPath &OutWidgetPath, EVisibility VisibilityFilter=EVisibility::Visible) override
Searches for the specified widget and generates a full path to it.
virtual TSharedPtr< SWindow > FindWidgetWindow (TSharedRef< const SWidget > InWidget) const override
Finds the window that the provided widget resides in.
void FinishedInputThisFrame ()
Occurs before Tick(), after all pointer and keyboard input has been processed.
virtual void FinishedReshapingWindow (const TSharedRef< FGenericWindow > &PlatformWindow) override
void FlushRenderState ()
Flushes the render state of slate, releasing accesses and flushing all render commands.
void ForceRedrawWindow (const TSharedRef< SWindow > &InWindowToDraw)
Forces the window to redraw immediately.
void ForEachUser (TFunctionRef< void(FSlateUser &)> InPredicate, bool bIncludeVirtualUsers=false)
Allows you do some operations for every registered user.
void GeneratePathToWidgetChecked (TSharedRef< const SWidget > InWidget, FWidgetPath &OutWidgetPath, EVisibility VisibilityFilter=EVisibility::Visible) const
bool GeneratePathToWidgetUnchecked (TSharedRef< const SWidget > InWidget, FWidgetPath &OutWidgetPath, EVisibility VisibilityFilter=EVisibility::Visible) const
TSharedPtr< SWindow > GetActiveModalWindow () const
virtual TSharedPtr< SWindow > GetActiveTopLevelRegularWindow () const override
Gets the active regular top-level window.
virtual TSharedPtr< SWindow > GetActiveTopLevelWindow () const override
Gets the active top-level window.
bool GetAllowTooltips () const
void GetAllVisibleWindowsOrdered (TArray< TSharedRef< SWindow > > &OutWindows)
Gets all visible slate windows ordered from back to front based on child hierarchies.
virtual const FSlateBrush * GetAppIcon () const override
Gets the global application icon.
virtual const FSlateBrush * GetAppIconSmall () const override
virtual float GetApplicationScale () const override
Gets the ratio SlateUnit / ScreenPixel.
const float GetAverageDeltaTime () const
Returns the running average delta time (smoothed over several frames)
float GetAverageDeltaTimeForResponsiveness () const
Returns the running average delta time (smoothed over several frames) Unlike GetAverageDeltaTime() it excludes exceptional situations, such as when throttling mode is active.
virtual TSharedPtr< SWidget > GetCurrentDebugContextWidget () const override
virtual const double GetCurrentTime () const override
Gets Slate's current cached real time.
virtual UE::Slate::FDeprecateVector2DResult GetCursorPos () const override
Gets the current position of the cursor.
float GetCursorRadius () const
Getter for the cursor radius.
virtual UE::Slate::FDeprecateVector2DResult GetCursorSize () const override
Gets the size of the cursor.
FORCEINLINE TSharedPtr< FSlateUser > GetCursorUser ()
FORCEINLINE TSharedPtr< const FSlateUser > GetCursorUser () const
Get the standard 'default' user (there's always guaranteed to be at least one).
const float GetDeltaTime () const
Returns the real time delta since Slate last ticked widgets.
TSharedPtr< class FDragDropOperation > GetDragDroppingContent () const
Get the current drag-dropping content.
float GetDragTriggerDistance () const
float GetDragTriggerDistanceSquared () const
TSharedPtr< SViewport > GetGameViewport () const
Returns the game viewport registered with the slate application.
bool GetHandleDeviceInputWhenApplicationNotActive () const
virtual void GetInitialDisplayMetrics (FDisplayMetrics &OutDisplayMetrics) const
FInputDeviceId GetInputDeviceIdForKeyboard () const
FInputDeviceId GetInputDeviceIdForMouse () const
IInputInterface * GetInputInterface () const
TArray< TSharedRef< SWindow > > GetInteractiveTopLevelWindows ()
virtual TSharedPtr< SWidget > GetKeyboardFocusedWidget () const override
Gets the widget that currently has keyboard focus, if any.
virtual UE::Slate::FDeprecateVector2DResult GetLastCursorPos () const override
Gets the last known position of the cursor.
double GetLastUserInteractionTime () const
FSlateLastUserInteractionTimeUpdateEvent & GetLastUserInteractionTimeUpdateEvent ()
TSharedPtr< SWidget > GetMenuHostWidget () const
FModifierKeysState GetModifierKeys () const
Returns the current modifier keys state.
virtual void * GetMouseCaptureWindow () const
returning platform-specific value designating window that captures mouse, or nullptr if mouse isn't captured
virtual EUINavigationAction GetNavigationActionFromKey (const FKeyEvent &InKeyEvent) const override
Returns the navigation action corresponding to a key event.
TSharedRef< FNavigationConfig > GetNavigationConfig () const
virtual EUINavigation GetNavigationDirectionFromAnalog (const FAnalogInputEvent &InAnalogEvent) override
Returns navigation direction matching an anlog event, this is determined in the FNavigationConfig.
virtual EUINavigation GetNavigationDirectionFromKey (const FKeyEvent &InKeyEvent) const override
Returns navigation direction matching a key event, this is determined in the FNavigationConfig.
const TAttribute< bool > & GetNormalExecutionAttribute () const
Returns the attribute that can be used by widgets to check if the application is in normal execution mode Don't hold a reference to this anywhere that can exist when this application closes.
FOnModalLoopTickEvent & GetOnModalLoopTickEvent ()
Get the FOnModalLoopTickEvent for the Slate Application.
FPopupSupport & GetPopupSupport ()
virtual FSlateRect GetPreferredWorkArea () const override
Gets the rectangle of the current preferred work area.
const TSet< FKey > & GetPressedMouseButtons () const
const class FStyleNode * GetRootStyle () const
virtual FWindowSizeLimits GetSizeLimitsForWindow (const TSharedRef< FGenericWindow > &Window) const override
virtual bool GetSoftwareCursorAvailable () const override
Whether the software cursor is enabled for this application.
virtual EVisibility GetSoftwareCursorVis () const override
Gets the desired visibility of the software cursor.
float GetSoundDuration (const FSlateSound &Sound) const
ITextInputMethodSystem * GetTextInputMethodSystem () const
virtual const TArray< TSharedRef< SWindow > > GetTopLevelWindows () const override
Get a list of all top-level windows in the application, excluding virtual windows.
bool GetTransformFullscreenMouseInput () const
True if transforming mouse input coordinates to account for fullscreen distortions.
FORCEINLINE TSharedPtr< FSlateUser > GetUser (const FInputEvent &InputEvent)
FORCEINLINE TSharedPtr< const FSlateUser > GetUser (const FInputEvent &InputEvent) const
TSharedPtr< FSlateUser > GetUser (FPlatformUserId PlatformUser)
FORCEINLINE TSharedPtr< FSlateUser > GetUser (int32 UserIndex)
FORCEINLINE TSharedPtr< const FSlateUser > GetUser (int32 UserIndex) const
Gets the user at the given index, null if the user does not exist.
virtual TSharedPtr< SWidget > GetUserFocusedWidget (uint32 UserIndex) const override
FORCEINLINE TSharedPtr< FSlateUser > GetUserFromControllerId (int32 ControllerId)
FORCEINLINE TSharedPtr< const FSlateUser > GetUserFromControllerId (int32 ControllerId) const
TSharedPtr< FSlateUser > GetUserFromPlatformUser (FPlatformUserId PlatformUser)
TSharedPtr< const FSlateUser > GetUserFromPlatformUser (FPlatformUserId PlatformUser) const
int32 GetUserIndexForController (int32 ControllerId) const
TOptional< int32 > GetUserIndexForController (int32 ControllerId, FKey InKey) const
TOptional< int32 > GetUserIndexForInputDevice (FInputDeviceId InputDeviceId) const
int32 GetUserIndexForKeyboard () const
int32 GetUserIndexForMouse () const
TOptional< int32 > GetUserIndexForPlatformUser (FPlatformUserId PlatformUser) const
TSharedPtr< SWindow > GetVisibleMenuWindow () const
virtual EWindowTransparency GetWindowTransparencySupport () const override
Get the highest level of window transparency support currently enabled by this application.
virtual EWindowZone::Type GetWindowZoneForPoint (const TSharedRef< FGenericWindow > &PlatformWindow, const int32 X, const int32 Y) override
FSlateRect GetWorkArea (const FSlateRect &InRect) const
Get the work area that has the largest intersection with the specified rectangle.
void GotoLineInSource (const FString &FileName, int32 LineNumber) const
Opens the current platform's code editing IDE (if necessary) and focuses the specified line in the specified file.
virtual void HandleDPIScaleChanged (const TSharedRef< FGenericWindow > &Window) override
virtual bool HasAnyMouseCaptor () const override
Gets whether or not a widget has captured the mouse.
virtual bool HasFocusedDescendants (const TSharedRef< const SWidget > &Widget) const override
Checks whether the specified widget has any descendants which are currently focused.
bool HasOpenSubMenus (TSharedPtr< IMenu > InMenu) const
bool HasTraveledFarEnoughToTriggerDrag (const FPointerEvent &PointerEvent, const UE::Slate::FDeprecateVector2DParameter ScreenSpaceOrigin) const
bool HasTraveledFarEnoughToTriggerDrag (const FPointerEvent &PointerEvent, const UE::Slate::FDeprecateVector2DParameter ScreenSpaceOrigin, EOrientation Orientation) const
virtual bool HasUserFocusedDescendants (const TSharedRef< const SWidget > &Widget, int32 UserIndex) const override
Checks whether the specified widget has any descendants which are currently focused for the specified user user.
virtual bool HasUserMouseCapture (int32 UserIndex) const override
Gets whether or not a widget has captured the mouse for a particular user.
virtual bool InitializeRenderer (TSharedRef< FSlateRenderer > InRenderer, bool bQuietMode=false)
Initializes the renderer responsible for drawing all elements in this application.
virtual void InitializeSound (const TSharedRef< ISlateSoundDevice > &InSlateSoundDevice)
Set the slate sound provider that the slate app should use.
bool InKismetDebuggingMode () const
void InvalidateAllViewports ()
Removes references to FViewportRHI's.
virtual bool IsActive () const override
Whether the application is active.
bool IsDragDropping () const
Are we drag-dropping right now?
bool IsDragDroppingAffected (const FPointerEvent &InPointerEvent) const
Are we drag-dropping and are we affected by this pointer event?
virtual bool IsExternalUIOpened () override
Checks whether an UI for external services such as Steam is open.
bool IsFakingTouchEvents () const
bool IsGamepadAttached () const
bool IsMouseAttached () const
bool IsNormalExecution () const
bool IsProcessingInput () const
Returns true if the we're currently processing mouse, keyboard, touch or gamepad input.
bool IsRenderingOffScreen () const
bool IsRunningAtTargetFrameRate () const
bool IsTicking () const
Returns true if we are currently ticking the SlateApplication.
bool IsUsingHighPrecisionMouseMovment () const
bool IsUsingTrackpad () const
virtual bool IsWindowHousingInteractiveTooltip (const TSharedRef< const SWindow > &WindowToTest) const override
bool IsWindowInDestroyQueue (TSharedRef< SWindow > Window) const
Is the window in the app's destroy queue?
void LeaveDebuggingMode (bool bLeavingDebugForSingleStep=false)
Leaves debugging mode.
virtual FWidgetPath LocateWindowUnderMouse (UE::Slate::FDeprecateVector2DParameter ScreenspaceMouseCoordinate, const TArray< TSharedRef< SWindow > > &Windows, bool bIgnoreEnabledStatus=false, int32 UserIndex=INDEX_NONE) override
Given the screen-space coordinate of the mouse cursor, searches for a string of widgets that are under the mouse.
virtual TSharedRef< SImage > MakeImage (const TAttribute< const FSlateBrush * > &Image, const TAttribute< FSlateColor > &Color, const TAttribute< EVisibility > &Visibility) const override
Creates an image widget.
virtual TSharedRef< IToolTip > MakeToolTip (const FText &ToolTipText) override
Creates a tool tip with the specified text.
virtual TSharedRef< IToolTip > MakeToolTip (const TAttribute< FText > &ToolTipText) override
Creates a tool tip with the specified text.
virtual TSharedRef< SWidget > MakeWindowTitleBar (const FWindowTitleBarArgs &InArgs, TSharedPtr< IWindowTitleBar > &OutTitleBar) const override
Creates a title bar for the specified window.
virtual void NativeApp_ShowKeyboard (bool bShow, FString InitialString="", int32 SelectionStart=-1, int32 SelectionEnd=-1)
Shows or hides an onscreen keyboard.
EUINavigation NavigateFromWidget (const uint32 InUserIndex, TSharedPtr< SWidget > InNavigationSource, const TArray< EUINavigation > &InNavigationTypes)
Attempts to navigate to a neighboring widget by searching the given directions.
void NavigateFromWidgetUnderCursor (const uint32 InUserIndex, EUINavigation InNavigationType, TSharedRef< SWindow > InWindow)
Attempts to navigate directly to the widget currently under the given user's cursor.
void NavigateToWidget (const uint32 UserIndex, const TSharedPtr< SWidget > &NavigationDestination, ENavigationSource NavigationSource=ENavigationSource::FocusedWidget)
Attempts to navigate directly to the given widget.
virtual bool OnApplicationActivationChanged (const bool IsActive) override
FOnApplicationMousePreInputButtonDownListener & OnApplicationMousePreInputButtonDownListener ()
FOnApplicationPreInputKeyDownListener & OnApplicationPreInputKeyDownListener ()
virtual bool OnControllerAnalog (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, float AnalogValue) override
virtual bool OnControllerButtonPressed (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat) override
virtual bool OnControllerButtonReleased (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat) override
virtual bool OnConvertibleLaptopModeChanged () override
virtual bool OnCursorSet () override
virtual EDropEffect::Type OnDragDrop (const TSharedPtr< FGenericWindow > &Window) override
EDropEffect::Type OnDragEnter (const TSharedRef< SWindow > &Window, const TSharedRef< FExternalDragOperation > &DragDropOperation)
virtual EDropEffect::Type OnDragEnterExternal (const TSharedRef< FGenericWindow > &Window, const FString &Text, const TArray< FString > &Files) override
virtual EDropEffect::Type OnDragEnterFiles (const TSharedRef< FGenericWindow > &Window, const TArray< FString > &Files) override
virtual EDropEffect::Type OnDragEnterText (const TSharedRef< FGenericWindow > &Window, const FString &Text) override
virtual void OnDragLeave (const TSharedPtr< FGenericWindow > &Window) override
virtual EDropEffect::Type OnDragOver (const TSharedPtr< FGenericWindow > &Window) override
FOnFocusChanging & OnFocusChanging ()
virtual void OnInputLanguageChanged () override
virtual bool OnKeyChar (const TCHAR Character, const bool IsRepeat) override
virtual bool OnKeyDown (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat) override
virtual bool OnKeyUp (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat) override
FOnMenuDestroyed & OnMenuBeingDestroyed ()
virtual bool OnMotionDetected (const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId) override
virtual bool OnMouseDoubleClick (const TSharedPtr< FGenericWindow > &PlatformWindow, const EMouseButtons::Type Button) override
virtual bool OnMouseDoubleClick (const TSharedPtr< FGenericWindow > &PlatformWindow, const EMouseButtons::Type Button, const FVector2D CursorPos) override
virtual bool OnMouseDown (const TSharedPtr< FGenericWindow > &PlatformWindow, const EMouseButtons::Type Button) override
virtual bool OnMouseDown (const TSharedPtr< FGenericWindow > &PlatformWindow, const EMouseButtons::Type Button, const FVector2D CursorPos) override
virtual bool OnMouseMove () override
virtual bool OnMouseUp (const EMouseButtons::Type Button) override
virtual bool OnMouseUp (const EMouseButtons::Type Button, const FVector2D CursorPos) override
virtual bool OnMouseWheel (const float Delta) override
virtual bool OnMouseWheel (const float Delta, const FVector2D CursorPos) override
virtual void OnMovedWindow (const TSharedRef< FGenericWindow > &PlatformWindow, const int32 X, const int32 Y) override
virtual void OnOSPaint (const TSharedRef< FGenericWindow > &PlatformWindow) override
FSlateTickEvent & OnPostTick ()
Event after slate application ticks.
FSimpleMulticastDelegate & OnPreShutdown ()
Event when the application is about to shutdown.
FSlateTickEvent & OnPreTick ()
virtual bool OnRawMouseMove (const int32 X, const int32 Y) override
virtual void OnResizingWindow (const TSharedRef< FGenericWindow > &PlatformWindow) override
virtual bool OnSizeChanged (const TSharedRef< FGenericWindow > &PlatformWindow, const int32 Width, const int32 Height, bool bWasMinimized=false) override
FOnWindowDPIScaleChanged & OnSystemSignalsDPIChanged ()
Event used to signal that a DPI change is about to happen.
virtual bool OnTouchEnded (const FVector2D &Location, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override
virtual bool OnTouchFirstMove (const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override
virtual bool OnTouchForceChanged (const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override
virtual bool OnTouchGesture (EGestureEvent GestureType, const FVector2D &Delta, float WheelDelta, bool bIsDirectionInvertedFromDevice) override
virtual bool OnTouchMoved (const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override
virtual bool OnTouchStarted (const TSharedPtr< FGenericWindow > &Window, const FVector2D &Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceId) override
FUserRegisteredEvent & OnUserRegistered ()
virtual bool OnWindowAction (const TSharedRef< FGenericWindow > &PlatformWindow, const EWindowAction::Type InActionType) override
virtual bool OnWindowActivationChanged (const TSharedRef< FGenericWindow > &PlatformWindow, const EWindowActivation ActivationType) override
FOnWindowBeingDestroyed & OnWindowBeingDestroyed ()
virtual void OnWindowClose (const TSharedRef< FGenericWindow > &PlatformWindow) override
FOnWindowDPIScaleChanged & OnWindowDPIScaleChanged ()
void OverridePlatformApplication (TSharedPtr< class GenericApplication > InPlatformApplication)
Replace the current platform application with a custom version.
void OverridePlatformTextField (TUniquePtr< IPlatformTextField > PlatformTextField)
Replace the IPlatformTextField implementation with a custom one.
void PlaySound (const FSlateSound &SoundToPlay, int32 UserIndex=0) const
Play SoundToPlay.
void PollGameDeviceState ()
Polls game devices for input.
bool ProcessAnalogInputEvent (const FAnalogInputEvent &InAnalogInputEvent)
Called when a analog input values change.
void ProcessApplicationActivationEvent (bool InAppActivated)
Called when the application is activated (i.e.
void ProcessCursorReply (const FCursorReply &CursorReply)
Apply any requests from the CursorReply.
bool ProcessDragEnterEvent (TSharedRef< SWindow > WindowEntered, const FDragDropEvent &DragDropEvent)
Called when a drag from an external (non-slate) source enters a window.
void ProcessExternalReply (const FWidgetPath &CurrentEventPath, const FReply TheReply, const int32 UserIndex=0, const int32 PointerIndex=10)
Apply any requests from the Reply to the application.
bool ProcessKeyCharEvent (const FCharacterEvent &InCharacterEvent)
Called when a character is entered.
bool ProcessKeyDownEvent (const FKeyEvent &InKeyEvent)
Called when a key is pressed.
bool ProcessKeyUpEvent (const FKeyEvent &InKeyEvent)
Called when a key is released.
void ProcessMotionDetectedEvent (const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) when polling game device state.
bool ProcessMouseButtonDoubleClickEvent (const TSharedPtr< FGenericWindow > &PlatformWindow, const FPointerEvent &InMouseEvent)
Called by the native application in response to a mouse release.
bool ProcessMouseButtonDownEvent (const TSharedPtr< FGenericWindow > &PlatformWindow, const FPointerEvent &InMouseEvent)
Called by the native application in response to a mouse button press.
bool ProcessMouseButtonUpEvent (const FPointerEvent &MouseEvent)
Called by the native application in response to a mouse button release.
bool ProcessMouseMoveEvent (const FPointerEvent &MouseEvent, bool bIsSynthetic=false)
Called by the native application in response to a mouse move.
bool ProcessMouseWheelOrGestureEvent (const FPointerEvent &InWheelEvent, const FPointerEvent *InGestureEvent)
Called by the native application in response to a mouse wheel spin or a touch gesture.
void ProcessReply (const FWidgetPath &CurrentEventPath, const FReply &TheReply, const FWidgetPath *WidgetsUnderMouse, const FPointerEvent *InMouseEvent, const uint32 UserIndex=0)
Apply any requests from the Reply to the application.
void ProcessTouchEndedEvent (const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted) when polling game device state.
void ProcessTouchMovedEvent (const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved) when polling game device state.
void ProcessTouchStartedEvent (const TSharedPtr< FGenericWindow > &PlatformWindow, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down) when polling game device state.
bool ProcessWindowActivatedEvent (const FWindowActivateEvent &ActivateEvent)
Called by the native application in response to an activation or deactivation.
void PumpMessages ()
Pumps OS messages when a modal window or intra-frame debugging session exists.
TSharedPtr< IMenu > PushHostedMenu (const TSharedPtr< IMenu > &InParentMenu, const TSharedRef< IMenuHost > &InMenuHost, const TSharedRef< SWidget > &InContent, TSharedPtr< SWidget > &OutWrappedContent, const FPopupTransitionEffect &TransitionEffect, EShouldThrottle ShouldThrottle, const bool bIsCollapsedByParent=true)
Creates a new hosted child Menu and adds it to the menu stack under the specified parent menu.
TSharedPtr< IMenu > PushHostedMenu (const TSharedRef< SWidget > &InParentWidget, const FWidgetPath &InOwnerPath, const TSharedRef< IMenuHost > &InMenuHost, const TSharedRef< SWidget > &InContent, TSharedPtr< SWidget > &OutWrappedContent, const FPopupTransitionEffect &TransitionEffect, EShouldThrottle ShouldThrottle, const bool bIsCollapsedByParent=true)
Creates a new hosted Menu and adds it to the menu stack.
TSharedPtr< IMenu > PushMenu (const TSharedPtr< IMenu > &InParentMenu, const TSharedRef< SWidget > &InContent, const UE::Slate::FDeprecateVector2DParameter &SummonLocation, const FPopupTransitionEffect &TransitionEffect, const bool bFocusImmediately=true, const UE::Slate::FDeprecateVector2DParameter &SummonLocationSize=FVector2f::ZeroVector, const bool bIsCollapsedByParent=true, const int32 FocusUserIndex=INDEX_NONE)
Creates a new Menu and adds it to the menu stack under the specified parent menu.
TSharedPtr< IMenu > PushMenu (const TSharedRef< SWidget > &InParentWidget, const FWidgetPath &InOwnerPath, const TSharedRef< SWidget > &InContent, const UE::Slate::FDeprecateVector2DParameter &SummonLocation, const FPopupTransitionEffect &TransitionEffect, const bool bFocusImmediately=true, const UE::Slate::FDeprecateVector2DParameter &SummonLocationSize=FVector2f::ZeroVector, TOptional< EPopupMethod > Method=TOptional< EPopupMethod >(), const bool bIsCollapsedByParent=true, const int32 FocusUserIndex=INDEX_NONE)
Creates a new Menu and adds it to the menu stack.
void QueryCursor ()
Bubble a request for which cursor to display for widgets under the mouse or the widget that captured the mouse.
void RegisterGameViewport (TSharedRef< SViewport > InViewport)
Registers a game viewport with the Slate application so that specific messages can be routed directly to a viewport.
bool RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor)
Adds input pre-processor if unique.
bool RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const EInputPreProcessorType Type)
Adds input pre-processor if unique.
bool RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const FInputPreprocessorRegistrationKey &Info)
Adds input pre-processor if unique.
bool RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const int32 Index)
Adds input pre-processor if unique.
FDelegateHandle RegisterOnWindowActionNotification (const FOnWindowAction &Notification)
Register for a notification when the window action occurs.
void RegisterViewport (TSharedRef< SViewport > InViewport)
Registers a viewport with the Slate application so that specific messages can be routed directly to a viewport This is for all viewports, there can be multiple of these as opposed to the singular "Game Viewport".
void RegisterVirtualWindow (TSharedRef< SWindow > InWindow)
Register another window that may be visible in a non-top level way that still needs to be able to maintain focus paths.
void ReleaseAllPointerCapture ()
Releases capture for every pointer on every user from whatever it currently is on.
void ReleaseAllPointerCapture (int32 UserIndex)
Releases capture for every pointer belonging to the given user index particular user.
virtual void RequestDestroyWindow (TSharedRef< SWindow > WindowToDestroy) override
Destroying windows has implications on some OSs (e.g.
void ResetToDefaultInputSettings ()
Restores all input settings to their original values.
void ResetToDefaultPointerInputSettings ()
Restores all pointer input settings to their original values.
FReply RouteMouseWheelOrGestureEvent (const FWidgetPath &WidgetsUnderPointer, const FPointerEvent &InWheelEvent, const FPointerEvent *InGestureEvent=nullptr)
Directly routes a pointer mouse wheel or gesture event to the widgets in the specified widget path.
FReply RoutePointerDoubleClickEvent (const FWidgetPath &WidgetsUnderPointer, const FPointerEvent &PointerEvent)
Directly routes a pointer double click event to the widgets in the specified widget path.
FReply RoutePointerDownEvent (const FWidgetPath &WidgetsUnderPointer, const FPointerEvent &PointerEvent)
Directly routes a pointer down event to the widgets in the specified widget path.
bool RoutePointerMoveEvent (const FWidgetPath &WidgetsUnderPointer, const FPointerEvent &PointerEvent, bool bIsSynthetic)
Directly routes a pointer move event to the widgets in the specified widget path.
FReply RoutePointerUpEvent (const FWidgetPath &WidgetsUnderPointer, const FPointerEvent &PointerEvent)
Directly routes a pointer up event to the widgets in the specified widget path.
void SetAllowTooltips (bool bCanShow)
virtual void SetAllUserFocus (const FWidgetPath &InFocusPath, const EFocusCause InCause) override
Sets the focus for all users to the specified widget.
void SetAllUserFocus (const TSharedPtr< SWidget > &WidgetToFocus, EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Sets focus for all users to the SWidget passed in.
virtual void SetAllUserFocusAllowingDescendantFocus (const FWidgetPath &InFocusPath, const EFocusCause InCause) override
Sets the focus for all users to the specified widget unless that user is focused on a descendant.
void SetAllUserFocusToGameViewport (EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Sets all users focus to the SWidget representing the currently active game viewport.
void SetApplicationScale (float InScale)
void SetCursorPos (const FVector2D &MouseCoordinate) override
Sets the position of the cursor.
void SetCursorRadius (float NewRadius)
Sets the hit detection radius of the cursor.
void SetDragTriggerDistance (float ScreenPixels)
Set the size of the deadzone for dragging in screen pixels.
void SetExitRequestedHandler (const FSimpleDelegate &OnExitRequestedHandler)
Assign a delegate to be called when this application is requesting an exit (e.g.
void SetGameAllowsFakingTouchEvents (const bool bAllowFaking)
Sets whether the application is allowed to fake touches or not.
void SetGameIsFakingTouchEvents (const bool bIsFaking, FVector2D *CursorLocation=nullptr)
Sets whether the application is treating mouse events as imitating touch events.
void SetHandleDeviceInputWhenApplicationNotActive (bool bAllow)
Mouse capture.
void SetInputManager (TSharedRef< ISlateInputManager > InputManager)
Establishes the input mapping object used to map input sources to SlateUser indices.
virtual bool SetKeyboardFocus (const FWidgetPath &InFocusPath, const EFocusCause InCause) override
Sets keyboard focus to the specified widget.
bool SetKeyboardFocus (const TSharedPtr< SWidget > &OptionalWidgetToFocus, EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Sets the Keyboard focus to the specified SWidget.
void SetModalWindowStackEndedDelegate (FModalWindowStackEnded StackEndedDelegate)
Sets the delegate for when a modal window stack ends.
void SetModalWindowStackStartedDelegate (FModalWindowStackStarted StackStartedDelegate)
Sets the delegate for when a modal window stack begins.
void SetNavigationConfig (TSharedRef< FNavigationConfig > InNavigationConfig)
Sets the navigation config.
void SetPlatformApplication (const TSharedRef< class GenericApplication > &InPlatformApplication)
void SetPlatformCursorVisibility (bool bNewVisibility)
Changes the cursor type to Default (Visible) or None (Not Visible)
void SetUnhandledKeyDownEventHandler (const FOnKeyEvent &NewHandler)
Sets the handler for otherwise unhandled key down events.
void SetUnhandledKeyUpEventHandler (const FOnKeyEvent &NewHandler)
Sets the handler for otherwise unhandled key down events.
virtual bool SetUserFocus (const uint32 InUserIndex, const FWidgetPath &InFocusPath, const EFocusCause InCause) override
Sets user focus to the specified widget.
bool SetUserFocus (uint32 UserIndex, const TSharedPtr< SWidget > &WidgetToFocus, EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Sets specified user focus to the SWidget passed in.
virtual bool SetUserFocusAllowingDescendantFocus (const uint32 InUserIndex, const FWidgetPath &InFocusPath, const EFocusCause InCause) override
Sets the focus for the specified user to the specified widget unless that user is focused on a descendant.
void SetUserFocusToGameViewport (uint32 UserIndex, EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly)
Sets specified user focus to the SWidget representing the currently active game viewport.
void SetWidgetReflector (const TSharedRef< IWidgetReflector > &WidgetReflector)
Sets the widget reflector.
void SetWidgetReflectorAssetAccessDelegate (FAccessAsset AccessDelegate)
void SetWidgetReflectorQuerySourceAccessDelegate (FQueryAccessSourceCode QueryAccessDelegate)
void SetWidgetReflectorSourceAccessDelegate (FAccessSourceCode AccessDelegate)
virtual bool ShouldProcessUserInputMessages (const TSharedPtr< FGenericWindow > &PlatformWindow) const override
virtual void ShouldSimulateGesture (EGestureEvent Gesture, bool bEnable) override
void ShowSystemHelp ()
void ShowVirtualKeyboard (bool bShow, int32 UserIndex, TSharedPtr< IVirtualKeyboardEntry > TextEntryWidget=nullptr)
Shows or hides an onscreen keyboard.
virtual void SignalSystemDPIChanged (const TSharedRef< FGenericWindow > &Window) override
void SpawnToolTip (const TSharedRef< IToolTip > &InToolTip, const UE::Slate::FDeprecateVector2DParameter &InSpawnLocation)
Spawns a tool tip window.
bool SupportsSourceAccess () const
bool SupportsSystemHelp () const
bool TakeHDRScreenshot (const TSharedRef< SWidget > &Widget, const FIntRect &InnerWidgetArea, TArray< FLinearColor > &OutColorData, FIntVector &OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided, this version allows you to provide an inner area to screenshot.
bool TakeHDRScreenshot (const TSharedRef< SWidget > &Widget, TArray< FLinearColor > &OutColorData, FIntVector &OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided.
bool TakeScreenshot (const TSharedRef< SWidget > &Widget, const FIntRect &InnerWidgetArea, TArray< FColor > &OutColorData, FIntVector &OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided, this version allows you to provide an inner area to screenshot.
bool TakeScreenshot (const TSharedRef< SWidget > &Widget, TArray< FColor > &OutColorData, FIntVector &OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided.
void Tick (ESlateTickType TickType=ESlateTickType::All)
Ticks this application.
UE_DEPRECATED (4.20, "Returning to a simpler method of registering navigation configs.\nSetNavigationConfig, is what you should use now. Note: You'll need to store per user state information yourself if you have any, like we do for repeats with the analog stick in FNavigationConfig::UserNavigationState,\nrather than Slate creating a new Navigation Config per user.") void SetNavigationConfigFactory(TFunction< TSharedRef< FNavigationConfig >()> InNavigationConfigFactory)
Sets the navigation config factory.
UE_DEPRECATED (4.23, "ForEachUser now provides an FSlateUser& parameter to the lambda instead of an FSlateUser*") 1 void ForEachUser(TFunctionRef< void(FSlateUser *)> InPredicate
UE_DEPRECATED (4.23, "ReleaseMouseCapture has been renamed to ReleaseAllPointerCapture()") 1 void ReleaseMouseCapture()
UE_DEPRECATED (4.23, "ReleaseMouseCaptureForUser has been renamed to ReleaseAllPointerCapture(int32 UserIndex)") 1 void ReleaseMouseCaptureForUser(int32 UserIndex)
UE_DEPRECATED (4.23, "The FindWidgetWindow method that takes an FWidgetPath has been deprecated. If you dont need the widget path, use FindWidgetWindow(MyWidget) instead. If you need the path use GeneratePathToWidget") 1 TSharedPtr< SWindow > FindWidgetWindow(TSharedRef< const SWidget > InWidget
Finds the window that the provided widget resides in.
UE_DEPRECATED (4.24, "GetNavigationActionForKey doesn't handle multiple users properly, use GetNavigationActionFromKey instead") 1 virtual EUINavigationAction GetNavigationActionForKey(const FKey &InKey) const override
UE_DEPRECATED (4.26, "SetAppIcon has been deprecated. Set \"AppIcon\" in your applications style to override the icon") 1 void SetAppIcon(const FSlateBrush *const InAppIcon)
Set the global application icon.
UE_DEPRECATED (5.0, "Enable Window Animations is no longer used and is a no-op so calling this function is no longer necessary.") 1 void EnableMenuAnimations(const bool bEnableAnimations)
Sets whether transition effects for new menus and windows should be played.
UE_DEPRECATED (5.5, "This method is deprecated and will use EInputPreProcessorType::Game as a default. For a more accurate search result, please use the new version taking a EInputPreProcessorType") 1 int32 FindInputPreProcessor(TSharedPtr< class IInputProcessor > InputProcessor) const
Get the index of a registered pre-processor.
void UnregisterGameViewport ()
Unregisters the current game viewport from Slate.
void UnregisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor)
Removes an input pre-processor.
void UnregisterOnWindowActionNotification (FDelegateHandle Handle)
Unregister the notification because it is no longer desired.
void UnregisterUser (int32 UserIndex)
void UnregisterVirtualWindow (TSharedRef< SWindow > InWindow)
Unregister a virtual window.
void UpdateToolTip (bool bAllowSpawningOfNewToolTips)
void UsePlatformCursorForCursorUser (bool bUsePlatformCursor)
Updates the cursor user's cursor to either the platform cursor or fake cursor.
Public Member Functions inherited from FSlateApplicationBase
FSlateApplicationBase ()
virtual ~FSlateApplicationBase ()
DECLARE_EVENT_OneParam (FSlateApplicationBase, FOnGlobalInvalidationToggled, bool)
DECLARE_EVENT_OneParam (FSlateApplicationBase, FOnInvalidateAllWidgets, bool)
Gets a delegate that is invoked when a global invalidate of all widgets should occur.
void GetCachedDisplayMetrics (FDisplayMetrics &OutDisplayMetrics) const
Gets the application's cached display metrics.
const FMargin & GetCustomSafeZone () const
void GetDisplayMetrics (FDisplayMetrics &OutDisplayMetrics)
Gets the application's display metrics.
const FHitTesting & GetHitTesting () const
virtual EUINavigationAction GetNavigationActionForKey (const FKey &InKey) const =0
TSharedPtr< class GenericApplication > GetPlatformApplication ()
virtual const TSharedPtr< GenericApplication > GetPlatformApplication () const
Gets the platform application.
TSharedPtr< ICursor > GetPlatformCursor ()
FORCEINLINE FSlateRenderer * GetRenderer () const
Gets the renderer being used to draw this application.
void GetSafeZoneSize (FMargin &SafeZone, const UE::Slate::FDeprecateVector2DParameter &OverrideSize)
void InvalidateAllWidgets (bool bClearResourcesImmediately) const
Notifies all invalidation panels that they should invalidate their contents Note: this is a very expensive call and should only be done in non-performance critical situations.
bool IsCustomSafeZoneSet () const
bool IsSlateAsleep ()
Is Slate currently sleeping or not.
FOnGlobalInvalidationToggled & OnGlobalInvalidationToggled ()
FOnInvalidateAllWidgets & OnInvalidateAllWidgets ()
void ResetCustomSafeZone ()
void SetCustomSafeZone (const FMargin &InSafeZone)
void ToggleGlobalInvalidation (bool bIsGlobalInvalidationEnabled)
Public Member Functions inherited from FGenericApplicationMessageHandler
virtual ~FGenericApplicationMessageHandler ()
virtual void OnBeginGesture ()
virtual void OnEndGesture ()
virtual bool OnMotionDetected (const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration, int32 ControllerId)
virtual bool OnTouchEnded (const FVector2D &Location, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchFirstMove (const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchForceChanged (const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchMoved (const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool OnTouchStarted (const TSharedPtr< FGenericWindow > &Window, const FVector2D &Location, float Force, int32 TouchIndex, int32 ControllerId)
virtual bool ShouldUsePlatformUserId () const
Return true if this message handler expects FPlatformUserIds.
Static Public Member Functions
static void Create ()
static TSharedRef< FSlateApplication > Create (const TSharedRef< class GenericApplication > &InPlatformApplication)
static FSlateApplication & Get ()
Returns the current instance of the application.
static FORCEINLINE double GetFixedDeltaTime ()
Gets time step in seconds if a fixed delta time is wanted.
static TSharedRef< class FGlobalTabmanager > GetGlobalTabManager ()
static void InitHighDPI (const bool bForceEnable)
Initializes high dpi support for the process.
static TSharedRef< FSlateApplication > InitializeAsStandaloneApplication (const TSharedRef< class FSlateRenderer > &PlatformRenderer)
static TSharedRef< FSlateApplication > InitializeAsStandaloneApplication (const TSharedRef< class FSlateRenderer > &PlatformRenderer, const TSharedRef< class GenericApplication > &InPlatformApplication)
static void InitializeCoreStyle ()
static bool IsInitialized ()
Returns true if a Slate application instance is currently initialized and ready.
static void SetFixedDeltaTime (double InSeconds)
Sets time step in seconds if a fixed delta time is wanted.
static void Shutdown (bool bShutdownPlatform=true)
Static Public Member Functions inherited from FSlateApplicationBase
static FSlateApplicationBase & Get ()
Returns the current instance of the application.
static bool IsInitialized ()
Returns true if a Slate application instance is currently initialized and ready.
Data Fields
bool bIncludeVirtualUsers = false)
FWidgetPath &OutWidgetPath const
Data Fields inherited from FSlateApplicationBase
FOnConstrainedAspectRatioChanged OnConstrainedAspectRatioChanged
Protected Member Functions
void DestroyRenderer ()
virtual bool DoesWidgetHaveMouseCapture (const TSharedPtr< const SWidget > Widget) const override
Gets whether or not a particular widget has mouse capture.
virtual bool DoesWidgetHaveMouseCaptureByUser (const TSharedPtr< const SWidget > Widget, int32 UserIndex, TOptional< int32 > PointerIndex) const override
Gets whether or not a particular widget has mouse capture by a user.
void DrawPrepass (TSharedPtr< SWindow > DrawOnlyThisWindow)
Pre-pass step before drawing windows to compute geometry size and reshape autosized windows.
void DrawWindowAndChildren (const TSharedRef< SWindow > &WindowToDraw, struct FDrawWindowArgs &DrawWindowArgs)
Draws a window and its children.
void DrawWindows ()
Draws Slate windows.
void GetAllVisibleChildWindows (TArray< TSharedRef< SWindow > > &OutWindows, TSharedRef< SWindow > CurrentWindow)
Gets all visible child windows of a window.
virtual TSharedPtr< SWidget > GetMouseCaptorImpl () const override
Implementation of GetMouseCaptor which can be overridden without warnings.
FORCEINLINE TSharedRef< FSlateUser > GetOrCreateUser (const FInputEvent &InputEvent)
TSharedRef< FSlateUser > GetOrCreateUser (FInputDeviceId DeviceId)
Locates the SlateUser object corresponding to the input device id, creating a new one if it doesn't exist.
TSharedRef< FSlateUser > GetOrCreateUser (FPlatformUserId PlatformUserId)
Locates the SlateUser object corresponding to the index, creating a new one if it doesn't exist.
TSharedRef< FSlateUser > GetOrCreateUser (int32 UserIndex)
Locates the SlateUser object corresponding to the index, creating a new one if it doesn't exist.
TSharedRef< FNavigationConfig > GetRelevantNavConfig (int32 UserIndex) const
virtual TOptional< EFocusCause > HasAnyUserFocus (const TSharedPtr< const SWidget > Widget) const override
Gets whether or not a particular widget has any users focus, and if so the type of focus (first one found).
virtual TOptional< EFocusCause > HasUserFocus (const TSharedPtr< const SWidget > Widget, int32 UserIndex) const override
Gets whether or not a particular widget has the specified users focus, and if so the type of focus.
virtual bool IsWidgetDirectlyHovered (const TSharedPtr< const SWidget > Widget) const override
Gets whether or not a particular widget is directly hovered.
virtual FWidgetPath LocateWidgetInWindow (UE::Slate::FDeprecateVector2DParameter ScreenspaceMouseCoordinate, const TSharedRef< SWindow > &Window, bool bIgnoreEnabledStatus, int32 UserIndex) const override
Given a window, locate a widget under the cursor in it; returns an invalid path if cursor is not over this window.
void OnShutdown ()
Called when the slate application is being shut down.
void PrivateDrawWindows (TSharedPtr< SWindow > DrawOnlyThisWindow=nullptr)
Draws slate windows, optionally only drawing the passed in window.
TSharedRef< FSlateUser > RegisterNewUser (FPlatformUserId PlatformUserId, bool bIsVirtual=false)
Register a new user with Slate.
TSharedRef< FSlateUser > RegisterNewUser (int32 UserIndex, bool bIsVirtual=false)
Register a new user with Slate.
void SetupPhysicalSensitivities ()
Sets up any values that need to be based on the physical dimensions of the device.
virtual bool ShowUserFocus (const TSharedPtr< const SWidget > Widget) const override
Gets whether or not a particular widget should show user focus.
void ThrottleApplicationBasedOnMouseMovement ()
Engages or disengages application throttling based on user behavior.
void TickAndDrawWidgets (float DeltaTime)
Ticks and paints the actual Slate portion of the application.
void TickPlatform (float DeltaTime)
Pumps and ticks the platform.
void TickTime ()
Advances time for the application.
FPointerEvent TransformPointerEvent (const FPointerEvent &PointerEvent, const TSharedPtr< SWindow > &Window) const
Transforms a pointer event to account for non-standard viewport resolutions.
Protected Member Functions inherited from FSlateApplicationBase
void GetSafeZoneRatio (FMargin &SafeZoneRatio)
void SwapSafeZoneTypes ()
void UpdateAnyActiveTimersArePending ()
Used to determine if any active timer handles are ready to fire.
void UpdateCustomSafeZone (const FMargin &NewSafeZoneRatio, bool bShouldRecacheMetrics)
Private Member Functions
FSlateApplication ()
bool AttemptNavigation (const FWidgetPath &NavigationSource, const FNavigationEvent &NavigationEvent, const FNavigationReply &NavigationReply, const FArrangedWidget &BoundaryWidget)
Attempts to navigate to the next widget in the direction specified.
bool ExecuteNavigation (const FWidgetPath &NavigationSource, TSharedPtr< SWidget > DestinationWidget, const uint32 UserIndex, bool bAlwaysHandleNavigationAttempt)
Executes a navigate to the specified widget if possible.
TSharedRef< FGenericWindow > MakeWindow (TSharedRef< SWindow > InSlateWindow, const bool bShowImmediately)
void OnMenuDestroyed (const TSharedRef< IMenu > &Menu)
void OnVirtualDesktopSizeChanged (const FDisplayMetrics &NewDisplayMetric)
Will be invoked when the size of the geometry of the virtual desktop changes (e.g.
void PrivateDestroyWindow (const TSharedRef< SWindow > &DestroyedWindow)
Destroys an SWindow, removing it and all its children from the Slate window list.
void SetLastUserInteractionTime (const double InCurrentTime)
bool SetUserFocus (FSlateUser &User, const FWidgetPath &InFocusPath, const EFocusCause InCause)
Private Attributes
TArray< TSharedPtr< SWindow > > ActiveModalWindows
List of active modal windows.
TWeakPtr< SWindow > ActiveTopLevelWindow
The currently active slate window that is a top-level window (full fledged window; not a menu or tooltip)
TSet< TWeakPtr< SViewport > > AllGameViewports
List of all registered game viewports since the last time UnregisterGameViewport was called.
const FSlateBrush * AppIcon
The icon to use on application windows.
FApplicationActivationStateChangedEvent ApplicationActivationStateChangedEvent
FAccessAsset AssetAccessDelegate
Delegate for accessing assets, to pass to any widget inspectors.
float AverageDeltaTime
Running average time in seconds between calls to Tick (used for monitoring responsiveness)
float AverageDeltaTimeForResponsiveness
Average delta time for application responsiveness tracking.
bool bAllowFakingTouch
Restricts or allows the faking of touches.
bool bAppIsActive
true when the slate app is active; i.e.
bool bHandleDeviceInputWhenApplicationNotActive
Force Mouse Pointer Capture to always occur even when the application is not active or widget is not a virtual window.
bool bIsExternalUIOpened
Keeps track of whether or not the UI for services such as Steam is open.
bool bIsFakingTouch
For desktop platforms that want to test touch style input, pass -faketouches or -simmobile on the commandline to set this.
bool bIsFakingTouched
For desktop platforms that the touch move event be called when this variable is true.
bool bIsGameFakingTouch
For games that want to allow mouse to imitate touch.
bool bIsTicking = false
Are we ticking the SlateApplication.
bool bLeaveDebugForSingleStep
Whether or not we need to leave debug mode for single stepping.
bool bMenuAnimationsEnabled
Slate look and feel.
bool bRenderOffScreen
true if rendering windows even when they are set to invisible
bool bRequestLeaveDebugMode
Whether or not we are requesting that we leave debugging mode after the tick is complete.
bool bSlateWindowActive
true if any slate window is currently active (not just top level windows)
bool bSoftwareCursorAvailable
.ini controlled option to allow or disallow software cursor rendering
bool bSynthesizedCursorMove = false
Did we synthesize cursor input this frame?
bool bTouchFallbackToMouse
controls whether unhandled touch events fall back to sending mouse events
TWeakPtr< SWidget > CurrentDebugContextWidget
The painting SWindow.
TWeakPtr< SWindow > CurrentDebuggingWindow
double CurrentTime
The current cached absolute real time, right before we tick widgets.
float CursorRadius
The hit-test radius of the cursor.
TWeakPtr< SNotificationItem > DebuggingModeNotificationMessage
The message when the EnterDebugginMode failed.
bool DragIsHandled
When an drag and drop is happening, we keep track of whether slate knew what to do with the payload on last mouse move.
float DragTriggerDistance
The dead zone distance in virtual desktop pixels (a.k.a screen pixels) that the user has to move their finder before it is considered a drag.
TSharedRef< FNavigationConfig > EditorNavigationConfig
When PIE runs, the game's navigation config will overwrite the editor's navigation config.
FOnFocusChanging FocusChangingDelegate
Delegate for when focus might be about to change.
TWeakPtr< SViewport > GameViewportWidget
Pointer to the currently registered game viewport widget if any.
TSharedRef< ISlateInputManager > InputManager
Allows applications finer control over how we map controllers to users.
InputPreProcessorsHelper InputPreProcessors
A list of input pre-processors, gets an opportunity to parse input before anything else.
EFocusCause LastAllUsersFocusCause
TWeakPtr< SWidget > LastAllUsersFocusWidget
Last widget that was set for 'all users' focus and the cause.
double LastMouseMoveTime
Used when considering whether to put Slate to sleep.
FVector2f LastPlatformCursorPosition = FVector2f::ZeroVector
The location of the cursor the last time OnMouseMove was called.
double LastTickTime
Last absolute real time that we ticked.
double LastUserInteractionTime
The last real time that the user pressed a key or mouse button.
double LastUserInteractionTimeForThrottling
Subset of LastUserInteractionTime that is used only when considering when to throttle.
FSlateLastUserInteractionTimeUpdateEvent LastUserInteractionTimeUpdateEvent
Delegate that gets called for LastUserInteractionTime Update.
FOnMenuDestroyed MenuBeingDestroyedEvent
Delegate for a when a menu has been dismissed.
FMenuStack MenuStack
The stack of menus that are open.
FOnModalLoopTickEvent ModalLoopTickEvent
Delegate for slate Tick during modal dialogs.
FModalWindowStackEnded ModalWindowStackEndedDelegate
FModalWindowStackStarted ModalWindowStackStartedDelegate
Modal Windows.
FThrottleRequest MouseButtonDownResponsivnessThrottle
Application throttling.
TSharedRef< FNavigationConfig > NavigationConfig
TAttribute< bool > NormalExecutionGetter
int32 NumExternalModalWindowsActive
Allows us to track the number of non-slate modal windows active.
FOnApplicationMousePreInputButtonDownListener OnApplicationMousePreInputButtonDownListenerEvent
Delegate that is invoked before the mouse input button get process by slate widgets bubble system.
FOnApplicationPreInputKeyDownListener OnApplicationPreInputKeyDownListenerEvent
Delegate that is invoked before the input key get process by slate widgets bubble system.
FSimpleDelegate OnExitRequested
Provides a platform-agnostic method for requesting that the application exit.
FOnWindowDPIScaleChanged OnSignalSystemDPIChangedEvent
Called before the dpi scale of a particular window is about to changed.
TArray< FOnWindowAction > OnWindowActionNotifications
List of delegates that need to be called when the window action occurs.
FOnWindowDPIScaleChanged OnWindowDPIScaleChangedEvent
Called when an editor window dpi scale is changed.
uint64 PlatformMouseMovementEvents = 0
Platform mouse movement event count.
FPopupSupport PopupSupport
Support for auto-dismissing pop-ups.
FSlateTickEvent PostTickEvent
Delegate for post slate Tick.
FSimpleMulticastDelegate PreShutdownEvent
Delegate for pre shutdown.
TSet< FKey > PressedMouseButtons
FSlateTickEvent PreTickEvent
Delegate for pre slate tick.
TArray< TPair< FText, int32 > > PreventDebuggingModeStack
List of reason why we can't enter in debugging mode.
int32 ProcessingInput
Are we currently processing input in slate?
FQueryAccessSourceCode QuerySourceCodeAccessDelegate
Delegate for querying if source code access is available.
const class FStyleNode * RootStyleNode
The top of the Style tree.
float Scale
Application-wide scale for supporting monitors of varying pixel density.
TBitArray< FDefaultBitArrayAllocator > SimulateGestures
The simulated gestures Slate Application will be in charge of.
TSharedPtr< ISlateSoundDevice > SlateSoundDevice
TUniquePtr< IPlatformTextField > SlateTextField
Virtual keyboard text field.
FCriticalSection SlateTickCriticalSection
Critical section to avoid multiple threads calling Slate Tick when we're synchronizing between the Slate Loading Thread and the Game Thread.
TArray< TSharedRef< SWindow > > SlateVirtualWindows
All the virtual windows, which can be anywhere - likely inside the virtual world.
TArray< TSharedRef< SWindow > > SlateWindows
All the top-level windows owned by this application; they are tracked here in a platform-agnostic way.
FAccessSourceCode SourceCodeAccessDelegate
Delegate for accessing source code, to pass to any widget inspectors.
FThrottleRequest ThrottleHandle
Handle to a throttle request made to ensure the window is responsive in low FPS situations.
FOnKeyEvent UnhandledKeyDownEventHandler
Delegate for when a key down event occurred but was not handled in any other way by ProcessKeyDownMessage.
FOnKeyEvent UnhandledKeyUpEventHandler
Delegate for when a key down event occurred but was not handled in any other way by ProcessKeyDownMessage.
FThrottleRequest UserInteractionResponsivnessThrottle
Separate throttle handle that engages automatically based on mouse movement and other user behavior.
FUserRegisteredEvent UserRegisteredEvent
Delegate for when a new user has been registered.
TArray< TSharedPtr< FSlateUser > > Users
All users currently registered with Slate.
FSlateRect VirtualDesktopRect
TArray< TWeakPtr< FSlateVirtualUserHandle > > VirtualUsers
Weak pointers to the allocated virtual users.
TWeakPtr< IWidgetReflector > WidgetReflectorPtr
A Widget that introspects the current UI hierarchy.
FOnWindowBeingDestroyed WindowBeingDestroyedEvent
Delegate for when a window is in the process of being destroyed.
TArray< TSharedRef< SWindow > > WindowDestroyQueue
These windows will be destroyed next tick.
Static Private Attributes
static TSharedPtr< FSlateApplication > CurrentApplication
Application singleton.
static double FixedDeltaTime
Constant delta time used on every Slate widget Tick if CVarSlateUseFixedDeltaTime is enabled.
Friends
class FEventRouter
Additional Inherited Members
Static Public Attributes inherited from FSlateApplicationBase
static const uint32 CursorPointerIndex
static const uint32 CursorUserIndex
static const FPlatformUserId SlateAppPrimaryPlatformUser
The primary platform user for this application.
Protected Types inherited from FSlateApplicationBase
enum class ECustomSafeZoneState : uint8 { Unset , Set , Debug }
Protected Attributes inherited from FSlateApplicationBase
FCriticalSection ActiveTimerCS
Critical section for active timer registration as it can be called from the movie thread and the game thread.
bool bAnyActiveTimersPending = false
Whether any active timers are pending for this Slate tick.
bool bIsSlateAsleep
float CachedDebugTitleSafeRatio
FDisplayMetrics CachedDisplayMetrics
FMargin CustomSafeZoneRatio
Safe Zone ratio to override platform settings.
ECustomSafeZoneState CustomSafeZoneState
If Safe Zone ratio has been manually set, unset, or set via debug.
FHitTesting HitTesting
FOnGlobalInvalidationToggled OnGlobalInvalidationToggledEvent
FOnInvalidateAllWidgets OnInvalidateAllWidgetsEvent
multicast delegate to broadcast when a global invalidate is requested
TSharedPtr< FSlateRenderer > Renderer
Static Protected Attributes inherited from FSlateApplicationBase
static TSharedPtr< FSlateApplicationBase > CurrentBaseApplication
static TSharedPtr< class GenericApplication > PlatformApplication
Detailed Description
Definition at line 249 of file SlateApplication.h.
Constructor & Destructor Documentation
~FSlateApplication()
virtual FSlateApplication::~FSlateApplication () virtual
Virtual destructor.
FSlateApplication()
FSlateApplication::FSlateApplication () private
Referenced by DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), Get(), FSlateApplication::InputPreProcessorsHelper::HandleAnalogInputEvent(), FSlateApplication::InputPreProcessorsHelper::HandleKeyDownEvent(), FSlateApplication::InputPreProcessorsHelper::HandleKeyUpEvent(), FSlateApplication::InputPreProcessorsHelper::HandleMotionDetectedEvent(), FSlateApplication::InputPreProcessorsHelper::HandleMouseButtonDoubleClickEvent(), FSlateApplication::InputPreProcessorsHelper::HandleMouseButtonDownEvent(), FSlateApplication::InputPreProcessorsHelper::HandleMouseButtonUpEvent(), FSlateApplication::InputPreProcessorsHelper::HandleMouseMoveEvent(), FSlateApplication::InputPreProcessorsHelper::HandleMouseWheelOrGestureEvent(), and FSlateApplication::InputPreProcessorsHelper::Tick().
Member Function Documentation
ActivateGameViewport()
void FSlateApplication::ActivateGameViewport ()
Activates the Game Viewport if it is properly childed under a window.
AddModalWindow()
void FSlateApplication::AddModalWindow (TSharedRef< SWindow > InSlateWindow, const TSharedPtr< const SWidget > InParentWidget, bool bSlowTaskWindow = false)
Adds a modal window to the application.
In most cases, this function does not return until the modal window is closed (the only exception is a modal window for slow tasks)
Parameters
InSlateWindow A SlateWindow to which to add a native window.
InParentWindow The parent of the modal window. All modal windows must have a parent.
bSlowTaskWindow true if the window is for a slow task and this function should return before the window is closed
References AddModalWindow(), const, and FSlateApplicationBase::SWidget.
Referenced by AddModalWindow().
AddWindow()
virtual TSharedRef< SWindow > FSlateApplication::AddWindow (TSharedRef< SWindow > InSlateWindow, const bool bShowImmediately = true) override virtual
Associates a top level Slate Window with a native window and ensures that it is tracked properly by the application.
Calling this method will cause the window to be displayed (unless specified otherwise), so be sure to associate content with the window object you're passing in first!
Parameters
InSlateWindow A SlateWindow to which to add a native window.
bShowImmediately true to show the window, false if you're going to call ShowWindow() yourself later.
Returns
a reference to the SWindow that was just added.
Implements FSlateApplicationBase.
Referenced by SRigVMBulkEditDialog< InWidgetType >::ShowNormal().
AddWindowAsNativeChild()
TSharedRef< SWindow > FSlateApplication::AddWindowAsNativeChild (TSharedRef< SWindow > InSlateWindow, TSharedRef< SWindow > InParentWindow, const bool bShowImmediately = true)
Associates a top level Slate Window with a native window, and "natively" parents that window to the specified Slate window.
Although the window still a top level window in Slate, it will be considered a child window to the operating system.
Parameters
InSlateWindow A Slate window to which to add a native window.
InParentWindow Slate window that the window being added should be a native child of
bShowImmediately True to show the window. Pass false if you're going to call ShowWindow() yourself later.
Returns
a reference to the SWindow that was just added.
References AddWindowAsNativeChild(), and const.
Referenced by AddWindowAsNativeChild(), and SRigVMBulkEditDialog< InWidgetType >::ShowNormal().
AllowMoveCursor()
bool FSlateApplication::AllowMoveCursor ()
Returns
true if the current platform allows cursor positioning in editable text boxes
AnyMenusVisible()
virtual bool FSlateApplication::AnyMenusVisible () const override virtual
Returns
Returns true if there are any pop-up menus summoned
Implements FSlateApplicationBase.
References AnyMenusVisible(), and const.
Referenced by AnyMenusVisible().
AreMenuAnimationsEnabled()
bool FSlateApplication::AreMenuAnimationsEnabled () const
Returns
Returns true if transition effects for new menus and windows should be played
ArrangeWindowToFrontVirtual()
virtual void FSlateApplication::ArrangeWindowToFrontVirtual (TArray< TSharedRef< SWindow > > & Windows, const TSharedRef< SWindow > & WindowToBringToFront) inline override virtual
Reorders an array of windows so the specified window is "brought to the front".
Implements FSlateApplicationBase.
Definition at line 1572 of file SlateApplication.h.
References FSlateWindowHelper::ArrangeWindowToFront().
AttemptNavigation()
bool FSlateApplication::AttemptNavigation (const FWidgetPath & NavigationSource, const FNavigationEvent & NavigationEvent, const FNavigationReply & NavigationReply, const FArrangedWidget & BoundaryWidget) private
Attempts to navigate to the next widget in the direction specified.
Returns
if a new widget was navigated too
BeginReshapingWindow()
virtual bool FSlateApplication::BeginReshapingWindow (const TSharedRef< FGenericWindow > & PlatformWindow) override virtual
Reimplemented from FGenericApplicationMessageHandler.
CalculatePopupWindowPosition()
virtual UE::Slate::FDeprecateVector2DResult FSlateApplication::CalculatePopupWindowPosition (const FSlateRect & InAnchor, const UE::Slate::FDeprecateVector2DParameter & InSize, bool bAutoAdjustForDPIScale = true, const UE::Slate::FDeprecateVector2DParameter & InProposedPlacement = FVector2f::ZeroVector, const EOrientation Orientation = Orient_Vertical, const EPopupLayoutMode = EPopupLayoutMode::Menu) const virtual
Calculates the popup window position from the passed in window position and size.
Adjusts position for popup windows which are outside of the work area of the monitor where they reside
Parameters
InAnchor The current(suggested) window position and size of an area which may not be covered by the popup.
InSize The size of the window
bAutoAdjustForDPIScale Whether the method should attempt to correct for the DPI scale of the monitor.
InProposedPlacement The location on screen where the popup should go if allowed. If zero this will be determined from Orientation and Anchor
Orientation The direction of the popup. If vertical it will attempt to open below the anchor but will open above if there is no room. If horizontal it will attempt to open below the anchor but will open above if there is no room.
LayoutMode Determines whether the popup is allowed to flip to the other side of the anchor when there is no room on the screen.
Returns
The adjusted position
References UE::Math::TVector2< float >::ZeroVector.
CalculateTooltipWindowPosition()
virtual UE::Slate::FDeprecateVector2DResult FSlateApplication::CalculateTooltipWindowPosition (const FSlateRect & InAnchorRect, const UE::Slate::FDeprecateVector2DParameter & InSize, bool bAutoAdjustForDPIScale, EPopupCursorOverlapMode CursorOverlapMode = EPopupCursorOverlapMode::PreventOverlap) const virtual
Calculates the tooltip window position.
Parameters
InAnchorRect The current(suggested) window position and size of an area which may not be covered by the popup.
InSize The size of the tooltip window.
bAutoAdjustForDPIScale Whether the method should attempt to correct for the DPI scale of the monitor.
CursorOverlapMode Whether the tooltip window should be permitted to open under the position of the cursor.
Returns
The suggested position.
Implements FSlateApplicationBase.
References PreventOverlap.
CanAddModalWindow()
bool FSlateApplication::CanAddModalWindow () const
Returns true if this slate application is ready to open modal windows.
CancelDragDrop()
void FSlateApplication::CancelDragDrop ()
Cancels any in flight drag and drops.
CanDisplayWindows()
bool FSlateApplication::CanDisplayWindows () const
Returns true if this slate application is ready to display windows.
ClearAllUserFocus()
void FSlateApplication::ClearAllUserFocus (EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Releases the focus for all users from whatever it currently is on.
ClearKeyboardFocus()
void FSlateApplication::ClearKeyboardFocus (const EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Clears keyboard focus, if any widget is currently focused.
Parameters
ReasonFocusIsChanging The reason that keyboard focus is changing
Referenced by SGridLineSpacingList::SetValue(), and SNumericDropDown< NumericType >::SetValue().
ClearUserFocus()
void FSlateApplication::ClearUserFocus (uint32 UserIndex, EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Releases the users focus from whatever it currently is on.
CloseAllWindowsImmediately()
void FSlateApplication::CloseAllWindowsImmediately ()
Closes all active windows immediately.
CloseToolTip()
void FSlateApplication::CloseToolTip ()
Closes the open tool-tip, if a tool-tip is open.
Create() [1/2]
void FSlateApplication::Create () static
Create() [2/2]
TSharedRef< FSlateApplication > FSlateApplication::Create (const TSharedRef< class GenericApplication > & InPlatformApplication) static
DECLARE_EVENT_OneParam() [1/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FApplicationActivationStateChangedEvent , const bool) & inline
Definition at line 1644 of file SlateApplication.h.
References FSlateApplication(), and ApplicationActivationStateChangedEvent.
DECLARE_EVENT_OneParam() [2/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FOnApplicationMousePreInputButtonDownListener , const FPointerEvent &)
Gets a delegate that is invoked before the mouse input button down get process by slate widgets bubble system.
Its read only and you cannot mark the input as handled.
References FSlateApplication().
DECLARE_EVENT_OneParam() [3/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FOnApplicationPreInputKeyDownListener , const FKeyEvent &)
Gets a delegate that is invoked before the input key get process by slate widgets bubble system.
Its read only and you cannot mark the input as handled.
References FSlateApplication().
DECLARE_EVENT_OneParam() [4/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FOnModalLoopTickEvent , float)
Event type for when Slate is ticking during a modal dialog loop.
References FSlateApplication().
DECLARE_EVENT_OneParam() [5/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FOnWindowBeingDestroyed , const SWindow &)
Delegate called when a window is about to be destroyed.
References FSlateApplication().
DECLARE_EVENT_OneParam() [6/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FOnWindowDPIScaleChanged , TSharedRef< SWindow >)
Gets a delegate that is invoked in the editor when a windows dpi scale changes or when a widget window may have changed and DPI scale info needs to be checked.
References FSlateApplication().
DECLARE_EVENT_OneParam() [7/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FSlateLastUserInteractionTimeUpdateEvent , double)
References FSlateApplication().
DECLARE_EVENT_OneParam() [8/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FSlateTickEvent , float)
Event before slate application ticks.
References FSlateApplication(), and DECLARE_EVENT_OneParam().
Referenced by DECLARE_EVENT_OneParam().
DECLARE_EVENT_OneParam() [9/9]
FSlateApplication::DECLARE_EVENT_OneParam (FSlateApplication , FUserRegisteredEvent , int32)
Delegate for when a new user has been registered.
References FSlateApplication().
DECLARE_MULTICAST_DELEGATE_FiveParams()
FSlateApplication::DECLARE_MULTICAST_DELEGATE_FiveParams (FOnFocusChanging , const FFocusEvent & , const FWeakWidgetPath & , const TSharedPtr< SWidget > & , const FWidgetPath & , const TSharedPtr< SWidget > &)
Delegate called just before possible focus change.
DestroyRenderer()
void FSlateApplication::DestroyRenderer () protected
DestroyWindowImmediately()
void FSlateApplication::DestroyWindowImmediately (TSharedRef< SWindow > WindowToDestroy)
HACK: Don't use this unless shutting down a game viewport Game viewport windows need to be destroyed instantly or else the viewport could tick and access deleted data.
Parameters
WindowToDestroy Window for destruction
References DestroyWindowImmediately().
Referenced by DestroyWindowImmediately().
DestroyWindowsImmediately()
void FSlateApplication::DestroyWindowsImmediately ()
Destroy the native and slate windows in the array provided.
Parameters
WindowsToDestroy Destroy these windows
DismissAllMenus()
void FSlateApplication::DismissAllMenus ()
Dismisses all open menus.
References DismissAllMenus().
Referenced by DismissAllMenus(), and SRigVMActionMenu::OnActionSelected().
DismissMenu()
void FSlateApplication::DismissMenu (const TSharedPtr< IMenu > & InFromMenu)
Dismisses a menu and all its children.
Parameters
InFromMenu The menu to dismiss, any children, grandchildren etc will also be dismissed
References const, and DismissMenu().
Referenced by DismissMenu().
DismissMenuByWidget()
void FSlateApplication::DismissMenuByWidget (const TSharedRef< SWidget > & InWidgetInMenu)
Dismisses a menu and all its children.
The menu is determined by looking for menus in the parent chain of the widget.
Parameters
InWidgetInMenu The widget whose path is search upwards for a menu. That menu will then be dismissed.
References const, DismissMenuByWidget(), and FSlateApplicationBase::SWidget.
Referenced by DismissMenuByWidget().
DoesWidgetHaveMouseCapture()
virtual bool FSlateApplication::DoesWidgetHaveMouseCapture (const TSharedPtr< const SWidget > Widget) const override protected virtual
Gets whether or not a particular widget has mouse capture.
Returns
True if the widget has mouse capture, otherwise false.
Implements FSlateApplicationBase.
DoesWidgetHaveMouseCaptureByUser()
virtual bool FSlateApplication::DoesWidgetHaveMouseCaptureByUser (const TSharedPtr< const SWidget > Widget, int32 UserIndex, TOptional< int32 > PointerIndex) const override protected virtual
Gets whether or not a particular widget has mouse capture by a user.
Returns
True if the widget has mouse capture, otherwise false.
Implements FSlateApplicationBase.
DrawPrepass()
void FSlateApplication::DrawPrepass (TSharedPtr< SWindow > DrawOnlyThisWindow) protected
Pre-pass step before drawing windows to compute geometry size and reshape autosized windows.
DrawWindowAndChildren()
void FSlateApplication::DrawWindowAndChildren (const TSharedRef< SWindow > & WindowToDraw, struct FDrawWindowArgs & DrawWindowArgs) protected
Draws a window and its children.
DrawWindows()
void FSlateApplication::DrawWindows () protected
Draws Slate windows.
Should only be called by the application's main loop or renderer.
EnterDebuggingMode()
void FSlateApplication::EnterDebuggingMode ()
Enters debugging mode which is a special state that causes the Slate application to tick in place which in the middle of a stack frame.
ExecuteNavigation()
bool FSlateApplication::ExecuteNavigation (const FWidgetPath & NavigationSource, TSharedPtr< SWidget > DestinationWidget, const uint32 UserIndex, bool bAlwaysHandleNavigationAttempt) private
Executes a navigate to the specified widget if possible.
Returns
if the widget was navigated too
ExternalModalStart()
void FSlateApplication::ExternalModalStart ()
Disable Slate components when an external, non-slate, modal window is brought up.
In the case of multiple external modal windows, we will only increment our tracking counter.
References ExternalModalStart().
Referenced by ExternalModalStart().
ExternalModalStop()
void FSlateApplication::ExternalModalStop ()
Re-enable disabled Slate components when a non-slate modal window is dismissed.
Slate components will only be re-enabled when all tracked external modal windows have been dismissed.
References ExternalModalStop().
Referenced by ExternalModalStop().
ExternalUIChange()
void FSlateApplication::ExternalUIChange (bool bIsOpening) inline
Sets the display state of external UI such as Steam.
Definition at line 989 of file SlateApplication.h.
References bIsExternalUIOpened, and ExternalUIChange().
Referenced by ExternalUIChange().
FindBestParentWindowForDialogs()
TSharedPtr< SWindow > FSlateApplication::FindBestParentWindowForDialogs (const TSharedPtr< SWidget > & InWidget, const ESlateParentWindowSearchMethod InParentWindowSearchMethod = ESlateParentWindowSearchMethod::ActiveWindow)
Given an optional widget, try and get the most suitable parent window to use with dialogs (such as file and directory pickers).
This will first try and get the window that owns the widget (if provided), before falling back to using the MainFrame window.
FindBestParentWindowHandleForDialogs()
const void * FSlateApplication::FindBestParentWindowHandleForDialogs (const TSharedPtr< SWidget > & InWidget, const ESlateParentWindowSearchMethod InParentWindowSearchMethod = ESlateParentWindowSearchMethod::ActiveWindow)
Given an optional widget, try and get the most suitable parent window handle to use with dialogs (such as file and directory pickers).
This will first try and get the window that owns the widget (if provided), before falling back to using the MainFrame window.
FindInputPreProcessor()
int32 FSlateApplication::FindInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const EInputPreProcessorType & Type) const
Get the index of a registered pre-processor.
Parameters
InputProcessor The input pre-processor to find.
Type The priority bracket in which the pre-processor should be registered
Returns
The index of the pre-processor, or INDEX_NONE if not registered.
References const, and FindInputPreProcessor().
Referenced by FindInputPreProcessor(), and UE_DEPRECATED().
FindMenuInWidgetPath()
TSharedPtr< IMenu > FSlateApplication::FindMenuInWidgetPath (const FWidgetPath & InWidgetPath) const
Attempt to locate a menu that contains the specified widget.
Parameters
InWidgetPath Path to the widget to use for the search
Returns
the menu in which the widget resides, or nullptr
References const, and FindMenuInWidgetPath().
Referenced by FindMenuInWidgetPath().
FindOrCreateVirtualUser()
TSharedRef< FSlateVirtualUserHandle > FSlateApplication::FindOrCreateVirtualUser (int32 VirtualUserIndex)
Returns
a handle for the existing or newly created virtual slate user. This is handy when you need to create virtual hardware users for slate components in the virtual world that may need to be interacted with with virtual hardware.
FindPathToWidget()
virtual bool FSlateApplication::FindPathToWidget (TSharedRef< const SWidget > InWidget, FWidgetPath & OutWidgetPath, EVisibility VisibilityFilter = EVisibility::Visible) inline override virtual
Searches for the specified widget and generates a full path to it.
Note: this is a relatively slow operation!
Parameters
InWidget Widget to generate a path to
OutWidgetPath The generated widget path
VisibilityFilter Widgets must have this type of visibility to be included the path
Returns
True if the widget path was found
Implements FSlateApplicationBase.
Definition at line 1577 of file SlateApplication.h.
References FSlateWindowHelper::FindPathToWidget(), GetInteractiveTopLevelWindows(), SlateVirtualWindows, and EVisibility::Visible.
FindWidgetWindow()
virtual TSharedPtr< SWindow > FSlateApplication::FindWidgetWindow (TSharedRef< const SWidget > InWidget) const override virtual
Finds the window that the provided widget resides in.
Parameters
InWidget The widget to find the window for
Returns
The window where the widget resides, or null if the widget wasn't found. Remember, a widget might not be found simply because its parent decided not to report the widget in ArrangeChildren.
Implements FSlateApplicationBase.
References const, FindWidgetWindow(), and FSlateApplicationBase::SWidget.
Referenced by FindWidgetWindow().
FinishedInputThisFrame()
void FSlateApplication::FinishedInputThisFrame ()
Occurs before Tick(), after all pointer and keyboard input has been processed.
FinishedReshapingWindow()
virtual void FSlateApplication::FinishedReshapingWindow (const TSharedRef< FGenericWindow > & PlatformWindow) override virtual
Reimplemented from FGenericApplicationMessageHandler.
FlushRenderState()
void FSlateApplication::FlushRenderState ()
Flushes the render state of slate, releasing accesses and flushing all render commands.
ForceRedrawWindow()
void FSlateApplication::ForceRedrawWindow (const TSharedRef< SWindow > & InWindowToDraw)
Forces the window to redraw immediately.
ForEachUser()
void FSlateApplication::ForEachUser (TFunctionRef< void(FSlateUser &)> InPredicate, bool bIncludeVirtualUsers = false)
Allows you do some operations for every registered user.
References bIncludeVirtualUsers.
Referenced by SComboBox< OptionType >::OnMenuOpenChanged().
GeneratePathToWidgetChecked()
void FSlateApplication::GeneratePathToWidgetChecked (TSharedRef< const SWidget > InWidget, FWidgetPath & OutWidgetPath, EVisibility VisibilityFilter = EVisibility::Visible) const
Todo
slate: Remove this method or make it private. Searches for the specified widget and generates a full path to it. Note that this is a relatively slow operation! Asserts if the widget isn't found.
Parameters
InWidget Widget to generate a path to
OutWidgetPath The generated widget path
VisibilityFilter Widgets must have this type of visibility to be included the path
References const, GeneratePathToWidgetChecked(), FSlateApplicationBase::SWidget, and Visible.
Referenced by GeneratePathToWidgetChecked().
GeneratePathToWidgetUnchecked()
bool FSlateApplication::GeneratePathToWidgetUnchecked (TSharedRef< const SWidget > InWidget, FWidgetPath & OutWidgetPath, EVisibility VisibilityFilter = EVisibility::Visible) const
Todo
slate: Remove this method or make it private. Searches for the specified widget and generates a full path to it. Note that this is a relatively slow operation! It can fail, in which case OutWidgetPath.IsValid() will be false.
Parameters
InWidget Widget to generate a path to
OutWidgetPath The generated widget path
VisibilityFilter Widgets must have this type of visibility to be included the path
References const, GeneratePathToWidgetUnchecked(), FSlateApplicationBase::SWidget, and Visible.
Referenced by GeneratePathToWidgetUnchecked().
Get()
FSlateApplication & FSlateApplication::Get () inline static
Returns the current instance of the application.
The application should have been initialized before this method is called
Returns
Reference to the application
Definition at line 319 of file SlateApplication.h.
References FSlateApplication(), check, CurrentApplication, IsInAsyncLoadingThread, IsInGameThread(), and IsInSlateThread().
Referenced by FDelayedDrag::FDelayedDrag(), SSegmentedControl< OptionType >::CommitValue(), UE::Insights::FDrawContext::DrawTextAligned(), SRigVMActionMenu::OnActionSelected(), SComboBox< OptionType >::OnKeyDown(), SComboBox< OptionType >::OnMenuOpenChanged(), SComboBox< OptionType >::PlayPressedSound(), SComboBox< OptionType >::PlaySelectionChangeSound(), FDelayedDrag::SetTriggerScaleFactor(), SGridLineSpacingList::SetValue(), SNumericDropDown< NumericType >::SetValue(), and SRigVMBulkEditDialog< InWidgetType >::ShowNormal().
GetActiveModalWindow()
TSharedPtr< SWindow > FSlateApplication::GetActiveModalWindow () const
Returns
The active modal window or nullptr if there is no modal window.
References const, and GetActiveModalWindow().
Referenced by GetActiveModalWindow().
GetActiveTopLevelRegularWindow()
virtual TSharedPtr< SWindow > FSlateApplication::GetActiveTopLevelRegularWindow () const override virtual
Gets the active regular top-level window.
A regular window is a non-menu, non-tooltip, non-cursor decorator window
Returns
The top level window, or nullptr if no Slate windows are currently active.
Implements FSlateApplicationBase.
Referenced by SRigVMBulkEditDialog< InWidgetType >::ShowNormal().
GetActiveTopLevelWindow()
virtual TSharedPtr< SWindow > FSlateApplication::GetActiveTopLevelWindow () const override virtual
Gets the active top-level window.
Returns
The top level window, or nullptr if no Slate windows are currently active.
Implements FSlateApplicationBase.
GetAllowTooltips()
bool FSlateApplication::GetAllowTooltips () const
References const, and GetAllowTooltips().
Referenced by GetAllowTooltips().
GetAllVisibleChildWindows()
void FSlateApplication::GetAllVisibleChildWindows (TArray< TSharedRef< SWindow > > & OutWindows, TSharedRef< SWindow > CurrentWindow) protected
Gets all visible child windows of a window.
GetAllVisibleWindowsOrdered()
void FSlateApplication::GetAllVisibleWindowsOrdered (TArray< TSharedRef< SWindow > > & OutWindows)
Gets all visible slate windows ordered from back to front based on child hierarchies.
GetAppIcon()
virtual const FSlateBrush * FSlateApplication::GetAppIcon () const override virtual
Gets the global application icon.
Returns
The icon.
Implements FSlateApplicationBase.
GetAppIconSmall()
virtual const FSlateBrush * FSlateApplication::GetAppIconSmall () const override virtual
Implements FSlateApplicationBase.
GetApplicationScale()
virtual float FSlateApplication::GetApplicationScale () const inline override virtual
Gets the ratio SlateUnit / ScreenPixel.
Returns
Application scale.
Implements FSlateApplicationBase.
Definition at line 1599 of file SlateApplication.h.
References Scale.
GetAverageDeltaTime()
const float FSlateApplication::GetAverageDeltaTime () const inline
Returns the running average delta time (smoothed over several frames)
Returns
The average time delta
Definition at line 265 of file SlateApplication.h.
References AverageDeltaTime.
GetAverageDeltaTimeForResponsiveness()
float FSlateApplication::GetAverageDeltaTimeForResponsiveness () const inline
Returns the running average delta time (smoothed over several frames) Unlike GetAverageDeltaTime() it excludes exceptional situations, such as when throttling mode is active.
Returns
The average time delta
Definition at line 287 of file SlateApplication.h.
References AverageDeltaTimeForResponsiveness.
GetCurrentDebugContextWidget()
virtual TSharedPtr< SWidget > FSlateApplication::GetCurrentDebugContextWidget () const override virtual
Returns
the Widget that started a tick, paint, prepass or an event.
Implements FSlateApplicationBase.
GetCurrentTime()
virtual const double FSlateApplication::GetCurrentTime () const inline override virtual
Gets Slate's current cached real time.
This time value is updated every frame right before we tick widgets and is the recommended time value to use for UI animations and transitions, as opposed to calling FPlatformTime::Seconds() (which is generally slower)
Returns
The current Slate real time in seconds
Implements FSlateApplicationBase.
Definition at line 1587 of file SlateApplication.h.
References CurrentTime.
GetCursorPos()
virtual UE::Slate::FDeprecateVector2DResult FSlateApplication::GetCursorPos () const override virtual
Gets the current position of the cursor.
Returns
Cursor position.
Implements FSlateApplicationBase.
GetCursorRadius()
float FSlateApplication::GetCursorRadius () const
Getter for the cursor radius.
References const, and GetCursorRadius().
Referenced by GetCursorRadius().
GetCursorSize()
virtual UE::Slate::FDeprecateVector2DResult FSlateApplication::GetCursorSize () const override virtual
Gets the size of the cursor.
Returns
Cursor size.
Implements FSlateApplicationBase.
GetCursorUser() [1/2]
FORCEINLINE TSharedPtr< FSlateUser > FSlateApplication::GetCursorUser () inline
Definition at line 1107 of file SlateApplication.h.
References check, FSlateApplicationBase::CursorUserIndex, FORCEINLINE, GetUser(), and TSharedPtr< ObjectType, InMode >::IsValid().
GetCursorUser() [2/2]
FORCEINLINE TSharedPtr< const FSlateUser > FSlateApplication::GetCursorUser () const inline
Get the standard 'default' user (there's always guaranteed to be at least one).
Definition at line 1101 of file SlateApplication.h.
References check, FSlateApplicationBase::CursorUserIndex, FORCEINLINE, GetUser(), and TSharedPtr< ObjectType, InMode >::IsValid().
GetDeltaTime()
const float FSlateApplication::GetDeltaTime () const inline
Returns the real time delta since Slate last ticked widgets.
Returns
The time delta since last tick
Definition at line 275 of file SlateApplication.h.
References CurrentTime, and LastTickTime.
GetDragDroppingContent()
TSharedPtr< class FDragDropOperation > FSlateApplication::GetDragDroppingContent () const
Get the current drag-dropping content.
GetDragTriggerDistance()
float FSlateApplication::GetDragTriggerDistance () const
Returns
the deadzone size for dragging in screen pixels (aka virtual desktop pixels)
Referenced by FDelayedDrag::FDelayedDrag().
GetDragTriggerDistanceSquared()
float FSlateApplication::GetDragTriggerDistanceSquared () const
Returns
the deadzone size squared for dragging in screen pixels (aka virtual desktop pixels)
GetFixedDeltaTime()
FORCEINLINE double FSlateApplication::GetFixedDeltaTime () inline static
Gets time step in seconds if a fixed delta time is wanted.
Returns
Time step in seconds for fixed delta time.
Definition at line 1133 of file SlateApplication.h.
References FixedDeltaTime, FORCEINLINE, and GetFixedDeltaTime().
Referenced by GetFixedDeltaTime().
GetGameViewport()
TSharedPtr< SViewport > FSlateApplication::GetGameViewport () const
Returns the game viewport registered with the slate application.
Returns
registered game viewport
GetGlobalTabManager()
TSharedRef< class FGlobalTabmanager > FSlateApplication::GetGlobalTabManager () static
Returns
the global tab manager
GetHandleDeviceInputWhenApplicationNotActive()
bool FSlateApplication::GetHandleDeviceInputWhenApplicationNotActive () const inline
Definition at line 760 of file SlateApplication.h.
References bHandleDeviceInputWhenApplicationNotActive.
GetInitialDisplayMetrics()
virtual void FSlateApplication::GetInitialDisplayMetrics (FDisplayMetrics & OutDisplayMetrics) const inline virtual
Definition at line 874 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
GetInputDeviceIdForKeyboard()
FInputDeviceId FSlateApplication::GetInputDeviceIdForKeyboard () const
Returns
InputDeviceId that the keyboard is mapped to
GetInputDeviceIdForMouse()
FInputDeviceId FSlateApplication::GetInputDeviceIdForMouse () const
Returns
InputDeviceId that the mouse is mapped to
GetInputInterface()
IInputInterface * FSlateApplication::GetInputInterface () const inline
Definition at line 354 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
GetInteractiveTopLevelWindows()
TArray< TSharedRef< SWindow > > FSlateApplication::GetInteractiveTopLevelWindows ()
Returns
an array of top-level windows that can be interacted with. e.g. when a modal window is up, only return the modal window
Referenced by FindPathToWidget().
GetKeyboardFocusedWidget()
virtual TSharedPtr< SWidget > FSlateApplication::GetKeyboardFocusedWidget () const override virtual
Gets the widget that currently has keyboard focus, if any.
Returns
The focused widget, or nullptr if no widget has focus.
Implements FSlateApplicationBase.
GetLastCursorPos()
virtual UE::Slate::FDeprecateVector2DResult FSlateApplication::GetLastCursorPos () const override virtual
Gets the last known position of the cursor.
Returns
Cursor position.
Implements FSlateApplicationBase.
GetLastUserInteractionTime()
double FSlateApplication::GetLastUserInteractionTime () const inline
Returns
the last time a user interacted with a keyboard, mouse, touch device, or controller
Definition at line 1477 of file SlateApplication.h.
References LastUserInteractionTime.
GetLastUserInteractionTimeUpdateEvent()
FSlateLastUserInteractionTimeUpdateEvent & FSlateApplication::GetLastUserInteractionTimeUpdateEvent () inline
Returns
Gets the event for LasterUserInteractionTime update
Definition at line 1481 of file SlateApplication.h.
References LastUserInteractionTimeUpdateEvent.
GetMenuHostWidget()
TSharedPtr< SWidget > FSlateApplication::GetMenuHostWidget () const
Returns
Returns a ptr to the widget that created the opened root menu or null if one is not opened
References const, GetMenuHostWidget(), and FSlateApplicationBase::SWidget.
Referenced by GetMenuHostWidget().
GetModifierKeys()
FModifierKeysState FSlateApplication::GetModifierKeys () const
Returns the current modifier keys state.
Returns
State of modifier keys
Referenced by SSegmentedControl< OptionType >::CommitValue().
GetMouseCaptorImpl()
virtual TSharedPtr< SWidget > FSlateApplication::GetMouseCaptorImpl () const override protected virtual
Implementation of GetMouseCaptor which can be overridden without warnings.
Returns
Widget with the mouse capture
Implements FSlateApplicationBase.
GetMouseCaptureWindow()
virtual void * FSlateApplication::GetMouseCaptureWindow () const virtual
returning platform-specific value designating window that captures mouse, or nullptr if mouse isn't captured
GetNavigationActionFromKey()
virtual EUINavigationAction FSlateApplication::GetNavigationActionFromKey (const FKeyEvent & InKeyEvent) const override virtual
Returns the navigation action corresponding to a key event.
This version will handle multiple users correctly
Implements FSlateApplicationBase.
Referenced by SComboBox< OptionType >::OnKeyDown().
GetNavigationConfig()
TSharedRef< FNavigationConfig > FSlateApplication::GetNavigationConfig () const inline
Definition at line 1384 of file SlateApplication.h.
References NavigationConfig.
GetNavigationDirectionFromAnalog()
virtual EUINavigation FSlateApplication::GetNavigationDirectionFromAnalog (const FAnalogInputEvent & InAnalogEvent) override virtual
Returns navigation direction matching an anlog event, this is determined in the FNavigationConfig.
Implements FSlateApplicationBase.
GetNavigationDirectionFromKey()
virtual EUINavigation FSlateApplication::GetNavigationDirectionFromKey (const FKeyEvent & InKeyEvent) const override virtual
Returns navigation direction matching a key event, this is determined in the FNavigationConfig.
Implements FSlateApplicationBase.
Referenced by SComboBox< OptionType >::OnKeyDown().
GetNormalExecutionAttribute()
const TAttribute< bool > & FSlateApplication::GetNormalExecutionAttribute () const inline
Returns the attribute that can be used by widgets to check if the application is in normal execution mode Don't hold a reference to this anywhere that can exist when this application closes.
Definition at line 892 of file SlateApplication.h.
References NormalExecutionGetter.
GetOnModalLoopTickEvent()
FOnModalLoopTickEvent & FSlateApplication::GetOnModalLoopTickEvent () inline
Get the FOnModalLoopTickEvent for the Slate Application.
Allows clients to register for callbacks during modal dialog loops.
Returns
The application's FOnModalLoopTickEvent.
Definition at line 1801 of file SlateApplication.h.
References ModalLoopTickEvent.
GetOrCreateUser() [1/4]
FORCEINLINE TSharedRef< FSlateUser > FSlateApplication::GetOrCreateUser (const FInputEvent & InputEvent) inline protected
Definition at line 1178 of file SlateApplication.h.
References FORCEINLINE, and GetOrCreateUser().
Referenced by GetOrCreateUser().
GetOrCreateUser() [2/4]
TSharedRef< FSlateUser > FSlateApplication::GetOrCreateUser (FInputDeviceId DeviceId) protected
Locates the SlateUser object corresponding to the input device id, creating a new one if it doesn't exist.
This will call GetOrCreateUser for the owning Platform User of the given input device. Asserts if given an invalid (ie, negative) index.
GetOrCreateUser() [3/4]
TSharedRef< FSlateUser > FSlateApplication::GetOrCreateUser (FPlatformUserId PlatformUserId) protected
Locates the SlateUser object corresponding to the index, creating a new one if it doesn't exist.
Asserts if given an invalid (ie, negative) index.
GetOrCreateUser() [4/4]
TSharedRef< FSlateUser > FSlateApplication::GetOrCreateUser (int32 UserIndex) protected
Locates the SlateUser object corresponding to the index, creating a new one if it doesn't exist.
Asserts if given an invalid (ie, negative) index.
GetPopupSupport()
FPopupSupport & FSlateApplication::GetPopupSupport () inline
Returns
Service that supports popups; helps with auto-hiding of popups
Definition at line 1025 of file SlateApplication.h.
References PopupSupport.
GetPreferredWorkArea()
virtual FSlateRect FSlateApplication::GetPreferredWorkArea () const override virtual
Gets the rectangle of the current preferred work area.
Returns
Area rectangle.
Implements FSlateApplicationBase.
GetPressedMouseButtons()
const TSet< FKey > & FSlateApplication::GetPressedMouseButtons () const
GetRelevantNavConfig()
TSharedRef< FNavigationConfig > FSlateApplication::GetRelevantNavConfig (int32 UserIndex) const protected
GetRootStyle()
const class FStyleNode * FSlateApplication::GetRootStyle () const
Returns
the root style node, which is the entry point to the style graph representing all the current style rules.
GetSizeLimitsForWindow()
virtual FWindowSizeLimits FSlateApplication::GetSizeLimitsForWindow (const TSharedRef< FGenericWindow > & Window) const override virtual
Reimplemented from FGenericApplicationMessageHandler.
GetSoftwareCursorAvailable()
virtual bool FSlateApplication::GetSoftwareCursorAvailable () const inline override virtual
Whether the software cursor is enabled for this application.
Returns
software cursor available or not.
Implements FSlateApplicationBase.
Definition at line 1600 of file SlateApplication.h.
References bSoftwareCursorAvailable.
GetSoftwareCursorVis()
virtual EVisibility FSlateApplication::GetSoftwareCursorVis () const override virtual
Gets the desired visibility of the software cursor.
Returns
Software Cursor visibility
Implements FSlateApplicationBase.
GetSoundDuration()
float FSlateApplication::GetSoundDuration (const FSlateSound & Sound) const
Returns
The duration of the given sound resource
References Sound.
GetTextInputMethodSystem()
ITextInputMethodSystem * FSlateApplication::GetTextInputMethodSystem () const inline
Returns
The text input method interface for this application
Definition at line 362 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
GetTopLevelWindows()
virtual const TArray< TSharedRef< SWindow > > FSlateApplication::GetTopLevelWindows () const inline override virtual
Get a list of all top-level windows in the application, excluding virtual windows.
Returns
An array of all current top-level SWindows.
Implements FSlateApplicationBase.
Definition at line 1642 of file SlateApplication.h.
References SlateWindows.
GetTransformFullscreenMouseInput()
bool FSlateApplication::GetTransformFullscreenMouseInput () const
True if transforming mouse input coordinates to account for fullscreen distortions.
GetUser() [1/5]
FORCEINLINE TSharedPtr< FSlateUser > FSlateApplication::GetUser (const FInputEvent & InputEvent) inline
Definition at line 1075 of file SlateApplication.h.
References FORCEINLINE, and GetUser().
Referenced by GetUser().
GetUser() [2/5]
FORCEINLINE TSharedPtr< const FSlateUser > FSlateApplication::GetUser (const FInputEvent & InputEvent) const inline
Definition at line 1074 of file SlateApplication.h.
References FORCEINLINE, and GetUser().
Referenced by GetUser().
GetUser() [3/5]
TSharedPtr< FSlateUser > FSlateApplication::GetUser (FPlatformUserId PlatformUser)
GetUser() [4/5]
FORCEINLINE TSharedPtr< FSlateUser > FSlateApplication::GetUser (int32 UserIndex) inline
Definition at line 1069 of file SlateApplication.h.
References FORCEINLINE, and Users.
GetUser() [5/5]
FORCEINLINE TSharedPtr< const FSlateUser > FSlateApplication::GetUser (int32 UserIndex) const inline
Gets the user at the given index, null if the user does not exist.
Definition at line 1065 of file SlateApplication.h.
References FORCEINLINE, and Users.
Referenced by GetCursorUser(), GetCursorUser(), GetUserFromControllerId(), and GetUserFromControllerId().
GetUserFocusedWidget()
virtual TSharedPtr< SWidget > FSlateApplication::GetUserFocusedWidget (uint32 UserIndex) const override virtual
Returns
a pointer to the Widget that currently has the users focus; Empty pointer when the user has no focus.
Implements FSlateApplicationBase.
GetUserFromControllerId() [1/2]
FORCEINLINE TSharedPtr< FSlateUser > FSlateApplication::GetUserFromControllerId (int32 ControllerId) inline
Definition at line 1077 of file SlateApplication.h.
References FORCEINLINE, GetUser(), GetUserIndexForController(), TOptional< OptionalType >::GetValue(), and TOptional< OptionalType >::IsSet().
GetUserFromControllerId() [2/2]
FORCEINLINE TSharedPtr< const FSlateUser > FSlateApplication::GetUserFromControllerId (int32 ControllerId) const inline
Definition at line 1086 of file SlateApplication.h.
References FORCEINLINE, GetUser(), GetUserIndexForController(), TOptional< OptionalType >::GetValue(), and TOptional< OptionalType >::IsSet().
GetUserFromPlatformUser() [1/2]
TSharedPtr< FSlateUser > FSlateApplication::GetUserFromPlatformUser (FPlatformUserId PlatformUser)
GetUserFromPlatformUser() [2/2]
TSharedPtr< const FSlateUser > FSlateApplication::GetUserFromPlatformUser (FPlatformUserId PlatformUser) const
GetUserIndexForController() [1/2]
int32 FSlateApplication::GetUserIndexForController (int32 ControllerId) const
Returns
int user index that this controller is mapped to.
Referenced by GetUserFromControllerId(), and GetUserFromControllerId().
GetUserIndexForController() [2/2]
TOptional< int32 > FSlateApplication::GetUserIndexForController (int32 ControllerId, FKey InKey) const
GetUserIndexForInputDevice()
TOptional< int32 > FSlateApplication::GetUserIndexForInputDevice (FInputDeviceId InputDeviceId) const
Returns
Gets the slate user index that this input device is mapped to
GetUserIndexForKeyboard()
int32 FSlateApplication::GetUserIndexForKeyboard () const
Returns
int user index that the keyboard is mapped to.
GetUserIndexForMouse()
int32 FSlateApplication::GetUserIndexForMouse () const
Returns
int user index that the mouse is mapped to.
GetUserIndexForPlatformUser()
TOptional< int32 > FSlateApplication::GetUserIndexForPlatformUser (FPlatformUserId PlatformUser) const
Returns
Gets the slate user index that this platform user id mapped to
GetVisibleMenuWindow()
TSharedPtr< SWindow > FSlateApplication::GetVisibleMenuWindow () const
Returns
Returns a ptr to the window that is currently the host of the menu stack or null if no menus are visible
References const, and GetVisibleMenuWindow().
Referenced by GetVisibleMenuWindow().
GetWindowTransparencySupport()
virtual EWindowTransparency FSlateApplication::GetWindowTransparencySupport () const inline override virtual
Get the highest level of window transparency support currently enabled by this application.
Returns
Enumeration value specifying the level of transparency currently supported
Implements FSlateApplicationBase.
Definition at line 1609 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
GetWindowZoneForPoint()
virtual EWindowZone::Type FSlateApplication::GetWindowZoneForPoint (const TSharedRef< FGenericWindow > & PlatformWindow, const int32 X, const int32 Y) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References X, and Y.
GetWorkArea()
FSlateRect FSlateApplication::GetWorkArea (const FSlateRect & InRect) const
Get the work area that has the largest intersection with the specified rectangle.
GotoLineInSource()
void FSlateApplication::GotoLineInSource (const FString & FileName, int32 LineNumber) const
Opens the current platform's code editing IDE (if necessary) and focuses the specified line in the specified file.
Will only work if SupportsSourceAccess() returns true
HandleDPIScaleChanged()
virtual void FSlateApplication::HandleDPIScaleChanged (const TSharedRef< FGenericWindow > & Window) override virtual
Reimplemented from FGenericApplicationMessageHandler.
HasAnyMouseCaptor()
virtual bool FSlateApplication::HasAnyMouseCaptor () const override virtual
Gets whether or not a widget has captured the mouse.
Returns
True if one or more widgets have capture, otherwise false.
Implements FSlateApplicationBase.
HasAnyUserFocus()
virtual TOptional< EFocusCause > FSlateApplication::HasAnyUserFocus (const TSharedPtr< const SWidget > Widget) const override protected virtual
Gets whether or not a particular widget has any users focus, and if so the type of focus (first one found).
Returns
The optional will be set with the focus cause, if unset this widget doesn't have focus.
Implements FSlateApplicationBase.
HasFocusedDescendants()
virtual bool FSlateApplication::HasFocusedDescendants (const TSharedRef< const SWidget > & Widget) const override virtual
Checks whether the specified widget has any descendants which are currently focused.
Parameters
Widget The widget to check.
Returns
true if any descendants are focused, false otherwise.
Implements FSlateApplicationBase.
HasOpenSubMenus()
bool FSlateApplication::HasOpenSubMenus (TSharedPtr< IMenu > InMenu) const
Returns
Returns whether the menu has child menus.
References const, and HasOpenSubMenus().
Referenced by HasOpenSubMenus().
HasTraveledFarEnoughToTriggerDrag() [1/2]
bool FSlateApplication::HasTraveledFarEnoughToTriggerDrag (const FPointerEvent & PointerEvent, const UE::Slate::FDeprecateVector2DParameter ScreenSpaceOrigin) const
Returns
true if the difference between the ScreenSpaceOrigin and the ScreenSpacePosition is larger than the trigger distance for dragging in Slate.
HasTraveledFarEnoughToTriggerDrag() [2/2]
bool FSlateApplication::HasTraveledFarEnoughToTriggerDrag (const FPointerEvent & PointerEvent, const UE::Slate::FDeprecateVector2DParameter ScreenSpaceOrigin, EOrientation Orientation) const
HasUserFocus()
virtual TOptional< EFocusCause > FSlateApplication::HasUserFocus (const TSharedPtr< const SWidget > Widget, int32 UserIndex) const override protected virtual
Gets whether or not a particular widget has the specified users focus, and if so the type of focus.
Returns
The optional will be set with the focus cause, if unset this widget doesn't have focus.
Implements FSlateApplicationBase.
HasUserFocusedDescendants()
virtual bool FSlateApplication::HasUserFocusedDescendants (const TSharedRef< const SWidget > & Widget, int32 UserIndex) const override virtual
Checks whether the specified widget has any descendants which are currently focused for the specified user user.
Parameters
Widget The widget to check.
InUserIndex Index of the user that we want to check for.
Returns
true if any descendants are focused, false otherwise.
Implements FSlateApplicationBase.
HasUserMouseCapture()
virtual bool FSlateApplication::HasUserMouseCapture (int32 UserIndex) const override virtual
Gets whether or not a widget has captured the mouse for a particular user.
Returns
True if one or more widgets have capture, otherwise false.
Implements FSlateApplicationBase.
InitHighDPI()
void FSlateApplication::InitHighDPI (const bool bForceEnable) static
Initializes high dpi support for the process.
InitializeAsStandaloneApplication() [1/2]
TSharedRef< FSlateApplication > FSlateApplication::InitializeAsStandaloneApplication (const TSharedRef< class FSlateRenderer > & PlatformRenderer) static
InitializeAsStandaloneApplication() [2/2]
TSharedRef< FSlateApplication > FSlateApplication::InitializeAsStandaloneApplication (const TSharedRef< class FSlateRenderer > & PlatformRenderer, const TSharedRef< class GenericApplication > & InPlatformApplication) static
InitializeCoreStyle()
void FSlateApplication::InitializeCoreStyle () static
InitializeRenderer()
virtual bool FSlateApplication::InitializeRenderer (TSharedRef< FSlateRenderer > InRenderer, bool bQuietMode = false) virtual
Initializes the renderer responsible for drawing all elements in this application.
Parameters
InRenderer The renderer to use.
bQuietMode Don't show any message boxes when initialization fails.
InitializeSound()
virtual void FSlateApplication::InitializeSound (const TSharedRef< ISlateSoundDevice > & InSlateSoundDevice) virtual
Set the slate sound provider that the slate app should use.
InKismetDebuggingMode()
bool FSlateApplication::InKismetDebuggingMode () const inline
Returns
true if in debugging mode
Definition at line 902 of file SlateApplication.h.
References GIntraFrameDebuggingGameThread.
InvalidateAllViewports()
void FSlateApplication::InvalidateAllViewports ()
Removes references to FViewportRHI's.
This has to be done explicitly instead of using the FRenderResource mechanism because FViewportRHI's are managed by the game thread. This is needed before destroying the RHI device.
IsActive()
virtual bool FSlateApplication::IsActive () const inline override virtual
Whether the application is active.
Returns
application active or not
Implements FSlateApplicationBase.
Definition at line 1565 of file SlateApplication.h.
References bAppIsActive.
Referenced by OnApplicationActivationChanged().
IsDragDropping()
bool FSlateApplication::IsDragDropping () const
Are we drag-dropping right now?
IsDragDroppingAffected()
bool FSlateApplication::IsDragDroppingAffected (const FPointerEvent & InPointerEvent) const
Are we drag-dropping and are we affected by this pointer event?
IsExternalUIOpened()
virtual bool FSlateApplication::IsExternalUIOpened () override virtual
Checks whether an UI for external services such as Steam is open.
Returns
true if an external UI is open, false otherwise.
Implements FSlateApplicationBase.
IsFakingTouchEvents()
bool FSlateApplication::IsFakingTouchEvents () const
Returns
true if mouse events are being turned into touch events, and touch UI should be forced on
IsGamepadAttached()
bool FSlateApplication::IsGamepadAttached () const inline
Returns
True if there is a gamepad attached
Definition at line 844 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
IsInitialized()
bool FSlateApplication::IsInitialized () inline static
Returns true if a Slate application instance is currently initialized and ready.
Returns
True if Slate application is initialized
Definition at line 308 of file SlateApplication.h.
References CurrentApplication.
IsMouseAttached()
bool FSlateApplication::IsMouseAttached () const inline
Returns
True if there is a mouse device attached
Definition at line 839 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
IsNormalExecution()
bool FSlateApplication::IsNormalExecution () const inline
Returns
true if not in debugging mode
Definition at line 897 of file SlateApplication.h.
References GIntraFrameDebuggingGameThread.
IsProcessingInput()
bool FSlateApplication::IsProcessingInput () const inline
Returns true if the we're currently processing mouse, keyboard, touch or gamepad input.
Definition at line 1380 of file SlateApplication.h.
References ProcessingInput.
IsRenderingOffScreen()
bool FSlateApplication::IsRenderingOffScreen () const inline
Definition at line 1559 of file SlateApplication.h.
References bRenderOffScreen, and IsRenderingOffScreen().
Referenced by IsRenderingOffScreen().
IsRunningAtTargetFrameRate()
bool FSlateApplication::IsRunningAtTargetFrameRate () const
Returns
Returns true if the application's average frame rate is at least as high as our target frame rate that satisfies our requirement for a smooth and responsive UI experience
IsTicking()
bool FSlateApplication::IsTicking () const
Returns true if we are currently ticking the SlateApplication.
IsUsingHighPrecisionMouseMovment()
bool FSlateApplication::IsUsingHighPrecisionMouseMovment () const inline
Returns
True if the application is currently routing high precision mouse movement events (OS specific) If this value is true, the mouse is captured and hidden by the widget that originally made the request.
Definition at line 829 of file SlateApplication.h.
References IsUsingHighPrecisionMouseMovment(), and FSlateApplicationBase::PlatformApplication.
Referenced by IsUsingHighPrecisionMouseMovment().
IsUsingTrackpad()
bool FSlateApplication::IsUsingTrackpad () const inline
Returns
True if the last mouse event was from a trackpad.
Definition at line 834 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
IsWidgetDirectlyHovered()
virtual bool FSlateApplication::IsWidgetDirectlyHovered (const TSharedPtr< const SWidget > Widget) const override protected virtual
Gets whether or not a particular widget is directly hovered.
Directly hovered means that the widget is directly under the pointer, is not true for ancestors tho they are Hovered.
Returns
True if the widget is directly hovered, otherwise false.
Implements FSlateApplicationBase.
IsWindowHousingInteractiveTooltip()
virtual bool FSlateApplication::IsWindowHousingInteractiveTooltip (const TSharedRef< const SWindow > & WindowToTest) const override virtual
Returns
true if 'WindowToTest' is being used to display the current tooltip and the tooltip is interactive.
Implements FSlateApplicationBase.
IsWindowInDestroyQueue()
bool FSlateApplication::IsWindowInDestroyQueue (TSharedRef< SWindow > Window) const
Is the window in the app's destroy queue?
If so it will be destroyed next tick.
Parameters
Window The window to find in the destroy list
Returns
true if Window is in the destroy queue
LeaveDebuggingMode()
void FSlateApplication::LeaveDebuggingMode (bool bLeavingDebugForSingleStep = false)
Leaves debugging mode.
Parameters
bLeavingDebugForSingleStep Whether or not we are leaving debug mode due to single stepping
LocateWidgetInWindow()
virtual FWidgetPath FSlateApplication::LocateWidgetInWindow (UE::Slate::FDeprecateVector2DParameter ScreenspaceMouseCoordinate, const TSharedRef< SWindow > & Window, bool bIgnoreEnabledStatus, int32 UserIndex) const override protected virtual
Given a window, locate a widget under the cursor in it; returns an invalid path if cursor is not over this window.
Implements FSlateApplicationBase.
LocateWindowUnderMouse()
virtual FWidgetPath FSlateApplication::LocateWindowUnderMouse (UE::Slate::FDeprecateVector2DParameter ScreenspaceMouseCoordinate, const TArray< TSharedRef< SWindow > > & Windows, bool bIgnoreEnabledStatus = false, int32 UserIndex = INDEX_NONE) override virtual
Given the screen-space coordinate of the mouse cursor, searches for a string of widgets that are under the mouse.
The widgets will be returned with the associated geometry. The first item will always be the top-level window while the last item will be the leaf-most widget.
Returns
The path to the widget.
Implements FSlateApplicationBase.
References INDEX_NONE.
MakeImage()
virtual TSharedRef< SImage > FSlateApplication::MakeImage (const TAttribute< const FSlateBrush * > & Image, const TAttribute< FSlateColor > & Color, const TAttribute< EVisibility > & Visibility) const override virtual
Creates an image widget.
Returns
The new image widget.
Implements FSlateApplicationBase.
References Color, and Visibility.
MakeToolTip() [1/2]
virtual TSharedRef< IToolTip > FSlateApplication::MakeToolTip (const FText & ToolTipText) override virtual
Creates a tool tip with the specified text.
Parameters
ToolTipText The text to assign to the tool tip.
Returns
The tool tip.
Implements FSlateApplicationBase.
MakeToolTip() [2/2]
virtual TSharedRef< IToolTip > FSlateApplication::MakeToolTip (const TAttribute< FText > & ToolTipText) override virtual
Creates a tool tip with the specified text.
Parameters
ToolTipText The text attribute to assign to the tool tip.
Returns
The tool tip.
Implements FSlateApplicationBase.
MakeWindow()
TSharedRef< FGenericWindow > FSlateApplication::MakeWindow (TSharedRef< SWindow > InSlateWindow, const bool bShowImmediately) private
MakeWindowTitleBar()
virtual TSharedRef< SWidget > FSlateApplication::MakeWindowTitleBar (const FWindowTitleBarArgs & InArgs, TSharedPtr< IWindowTitleBar > & OutTitleBar) const override virtual
Creates a title bar for the specified window.
Parameters
InArgs The creation arguments for the titlebar
OutTitleBar Will hold a pointer to the title bar's interface.
Returns
The new title bar widget.
Implements FSlateApplicationBase.
NativeApp_ShowKeyboard()
virtual void FSlateApplication::NativeApp_ShowKeyboard (bool bShow, FString InitialString = "", int32 SelectionStart = -1, int32 SelectionEnd = -1) inline virtual
Shows or hides an onscreen keyboard.
Parameters
bShow true to show the keyboard, false to hide it
Definition at line 1013 of file SlateApplication.h.
NavigateFromWidget()
EUINavigation FSlateApplication::NavigateFromWidget (const uint32 InUserIndex, TSharedPtr< SWidget > InNavigationSource, const TArray< EUINavigation > & InNavigationTypes)
Attempts to navigate to a neighboring widget by searching the given directions.
Parameters
InUserIndex The user that is doing the navigation
InNavigationSource The source widget to navigate from. If null, will use current user focus
InNavigationTypes The navigation requests to attempt, in order
Returns
If succesful, returns the direction navigated. Otherwise return EUINavigation::Invalid
NavigateFromWidgetUnderCursor()
void FSlateApplication::NavigateFromWidgetUnderCursor (const uint32 InUserIndex, EUINavigation InNavigationType, TSharedRef< SWindow > InWindow)
Attempts to navigate directly to the widget currently under the given user's cursor.
Parameters
InUserIndex The user that is doing the navigation
InNavigationType The navigation type / direction
InWindow The window to do the navigation within
NavigateToWidget()
void FSlateApplication::NavigateToWidget (const uint32 UserIndex, const TSharedPtr< SWidget > & NavigationDestination, ENavigationSource NavigationSource = ENavigationSource::FocusedWidget)
Attempts to navigate directly to the given widget.
Parameters
InUserIndex The user that is doing the navigation
NavigationDestination The navigation destination widget
NavigationSource The source type of the navigation
OnApplicationActivationChanged()
virtual bool FSlateApplication::OnApplicationActivationChanged (const bool IsActive) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References IsActive().
OnApplicationMousePreInputButtonDownListener()
FOnApplicationMousePreInputButtonDownListener & FSlateApplication::OnApplicationMousePreInputButtonDownListener () inline
Definition at line 720 of file SlateApplication.h.
References OnApplicationMousePreInputButtonDownListenerEvent.
OnApplicationPreInputKeyDownListener()
FOnApplicationPreInputKeyDownListener & FSlateApplication::OnApplicationPreInputKeyDownListener () inline
Definition at line 713 of file SlateApplication.h.
References OnApplicationPreInputKeyDownListenerEvent.
OnControllerAnalog()
virtual bool FSlateApplication::OnControllerAnalog (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, float AnalogValue) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnControllerButtonPressed()
virtual bool FSlateApplication::OnControllerButtonPressed (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnControllerButtonReleased()
virtual bool FSlateApplication::OnControllerButtonReleased (FGamepadKeyNames::Type KeyName, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId, bool IsRepeat) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnConvertibleLaptopModeChanged()
virtual bool FSlateApplication::OnConvertibleLaptopModeChanged () override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnCursorSet()
virtual bool FSlateApplication::OnCursorSet () override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnDragDrop()
virtual EDropEffect::Type FSlateApplication::OnDragDrop (const TSharedPtr< FGenericWindow > & Window) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnDragEnter()
EDropEffect::Type FSlateApplication::OnDragEnter (const TSharedRef< SWindow > & Window, const TSharedRef< FExternalDragOperation > & DragDropOperation)
OnDragEnterExternal()
virtual EDropEffect::Type FSlateApplication::OnDragEnterExternal (const TSharedRef< FGenericWindow > & Window, const FString & Text, const TArray< FString > & Files) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References Text.
OnDragEnterFiles()
virtual EDropEffect::Type FSlateApplication::OnDragEnterFiles (const TSharedRef< FGenericWindow > & Window, const TArray< FString > & Files) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnDragEnterText()
virtual EDropEffect::Type FSlateApplication::OnDragEnterText (const TSharedRef< FGenericWindow > & Window, const FString & Text) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References Text.
OnDragLeave()
virtual void FSlateApplication::OnDragLeave (const TSharedPtr< FGenericWindow > & Window) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnDragOver()
virtual EDropEffect::Type FSlateApplication::OnDragOver (const TSharedPtr< FGenericWindow > & Window) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnFocusChanging()
FOnFocusChanging & FSlateApplication::OnFocusChanging () inline
Definition at line 589 of file SlateApplication.h.
References FocusChangingDelegate.
OnInputLanguageChanged()
virtual void FSlateApplication::OnInputLanguageChanged () override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnKeyChar()
virtual bool FSlateApplication::OnKeyChar (const TCHAR Character, const bool IsRepeat) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References Character.
OnKeyDown()
virtual bool FSlateApplication::OnKeyDown (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnKeyUp()
virtual bool FSlateApplication::OnKeyUp (const int32 KeyCode, const uint32 CharacterCode, const bool IsRepeat) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMenuBeingDestroyed()
FOnMenuDestroyed & FSlateApplication::OnMenuBeingDestroyed () inline
Definition at line 585 of file SlateApplication.h.
References MenuBeingDestroyedEvent.
OnMenuDestroyed()
void FSlateApplication::OnMenuDestroyed (const TSharedRef< IMenu > & Menu) private
References Menu.
OnMotionDetected()
virtual bool FSlateApplication::OnMotionDetected (const FVector & Tilt, const FVector & RotationRate, const FVector & Gravity, const FVector & Acceleration, FPlatformUserId PlatformUserId, FInputDeviceId InputDeviceId) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References Acceleration, and FVector.
OnMouseDoubleClick() [1/2]
virtual bool FSlateApplication::OnMouseDoubleClick (const TSharedPtr< FGenericWindow > & PlatformWindow, const EMouseButtons::Type Button) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseDoubleClick() [2/2]
virtual bool FSlateApplication::OnMouseDoubleClick (const TSharedPtr< FGenericWindow > & PlatformWindow, const EMouseButtons::Type Button, const FVector2D CursorPos) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseDown() [1/2]
virtual bool FSlateApplication::OnMouseDown (const TSharedPtr< FGenericWindow > & PlatformWindow, const EMouseButtons::Type Button) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseDown() [2/2]
virtual bool FSlateApplication::OnMouseDown (const TSharedPtr< FGenericWindow > & PlatformWindow, const EMouseButtons::Type Button, const FVector2D CursorPos) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseMove()
virtual bool FSlateApplication::OnMouseMove () override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseUp() [1/2]
virtual bool FSlateApplication::OnMouseUp (const EMouseButtons::Type Button) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseUp() [2/2]
virtual bool FSlateApplication::OnMouseUp (const EMouseButtons::Type Button, const FVector2D CursorPos) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseWheel() [1/2]
virtual bool FSlateApplication::OnMouseWheel (const float Delta) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMouseWheel() [2/2]
virtual bool FSlateApplication::OnMouseWheel (const float Delta, const FVector2D CursorPos) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnMovedWindow()
virtual void FSlateApplication::OnMovedWindow (const TSharedRef< FGenericWindow > & PlatformWindow, const int32 X, const int32 Y) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References X, and Y.
OnOSPaint()
virtual void FSlateApplication::OnOSPaint (const TSharedRef< FGenericWindow > & PlatformWindow) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnPostTick()
FSlateTickEvent & FSlateApplication::OnPostTick () inline
Event after slate application ticks.
Definition at line 571 of file SlateApplication.h.
References PostTickEvent.
OnPreShutdown()
FSimpleMulticastDelegate & FSlateApplication::OnPreShutdown () inline
Event when the application is about to shutdown.
Definition at line 574 of file SlateApplication.h.
References PreShutdownEvent.
OnPreTick()
FSlateTickEvent & FSlateApplication::OnPreTick () inline
Definition at line 568 of file SlateApplication.h.
References OnPreTick(), and PreTickEvent.
Referenced by OnPreTick().
OnRawMouseMove()
virtual bool FSlateApplication::OnRawMouseMove (const int32 X, const int32 Y) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References X, and Y.
OnResizingWindow()
virtual void FSlateApplication::OnResizingWindow (const TSharedRef< FGenericWindow > & PlatformWindow) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnShutdown()
void FSlateApplication::OnShutdown () protected
Called when the slate application is being shut down.
OnSizeChanged()
virtual bool FSlateApplication::OnSizeChanged (const TSharedRef< FGenericWindow > & PlatformWindow, const int32 Width, const int32 Height, bool bWasMinimized = false) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References Width.
OnSystemSignalsDPIChanged()
FOnWindowDPIScaleChanged & FSlateApplication::OnSystemSignalsDPIChanged () inline
Event used to signal that a DPI change is about to happen.
Definition at line 727 of file SlateApplication.h.
References OnSignalSystemDPIChangedEvent.
OnTouchEnded()
virtual bool FSlateApplication::OnTouchEnded (const FVector2D & Location, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References DeviceID, and Location.
OnTouchFirstMove()
virtual bool FSlateApplication::OnTouchFirstMove (const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References DeviceID, Force, and Location.
OnTouchForceChanged()
virtual bool FSlateApplication::OnTouchForceChanged (const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References DeviceID, Force, and Location.
OnTouchGesture()
virtual bool FSlateApplication::OnTouchGesture (EGestureEvent GestureType, const FVector2D & Delta, float WheelDelta, bool bIsDirectionInvertedFromDevice) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnTouchMoved()
virtual bool FSlateApplication::OnTouchMoved (const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceID) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References DeviceID, Force, and Location.
OnTouchStarted()
virtual bool FSlateApplication::OnTouchStarted (const TSharedPtr< FGenericWindow > & Window, const FVector2D & Location, float Force, int32 TouchIndex, FPlatformUserId PlatformUserId, FInputDeviceId DeviceId) override virtual
Reimplemented from FGenericApplicationMessageHandler.
References Force, and Location.
OnUserRegistered()
FUserRegisteredEvent & FSlateApplication::OnUserRegistered () inline
Definition at line 578 of file SlateApplication.h.
References UserRegisteredEvent.
OnVirtualDesktopSizeChanged()
void FSlateApplication::OnVirtualDesktopSizeChanged (const FDisplayMetrics & NewDisplayMetric) private
Will be invoked when the size of the geometry of the virtual desktop changes (e.g.
resolution change or monitors re-arranged)
OnWindowAction()
virtual bool FSlateApplication::OnWindowAction (const TSharedRef< FGenericWindow > & PlatformWindow, const EWindowAction::Type InActionType) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnWindowActivationChanged()
virtual bool FSlateApplication::OnWindowActivationChanged (const TSharedRef< FGenericWindow > & PlatformWindow, const EWindowActivation ActivationType) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnWindowBeingDestroyed()
FOnWindowBeingDestroyed & FSlateApplication::OnWindowBeingDestroyed () inline
Definition at line 582 of file SlateApplication.h.
References WindowBeingDestroyedEvent.
OnWindowClose()
virtual void FSlateApplication::OnWindowClose (const TSharedRef< FGenericWindow > & PlatformWindow) override virtual
Reimplemented from FGenericApplicationMessageHandler.
OnWindowDPIScaleChanged()
FOnWindowDPIScaleChanged & FSlateApplication::OnWindowDPIScaleChanged () inline
Definition at line 724 of file SlateApplication.h.
References OnWindowDPIScaleChangedEvent.
OverridePlatformApplication()
void FSlateApplication::OverridePlatformApplication (TSharedPtr< class GenericApplication > InPlatformApplication)
Replace the current platform application with a custom version.
Parameters
InPlatformApplication - The replacement platform application.
References OverridePlatformApplication().
Referenced by OverridePlatformApplication().
OverridePlatformTextField()
void FSlateApplication::OverridePlatformTextField (TUniquePtr< IPlatformTextField > PlatformTextField)
Replace the IPlatformTextField implementation with a custom one.
The implementation used by default is platform specific. If you need to change the default behavior for virtual keyboard, this method is for you.
Parameters
PlatformTextField The platform specific implementation of the IPlatformTextField.
PlaySound()
void FSlateApplication::PlaySound (const FSlateSound & SoundToPlay, int32 UserIndex = 0) const
Play SoundToPlay.
Interrupt previous sound if one is playing.
Referenced by SComboBox< OptionType >::PlayPressedSound(), and SComboBox< OptionType >::PlaySelectionChangeSound().
PollGameDeviceState()
void FSlateApplication::PollGameDeviceState ()
Polls game devices for input.
PrivateDestroyWindow()
void FSlateApplication::PrivateDestroyWindow (const TSharedRef< SWindow > & DestroyedWindow) private
Destroys an SWindow, removing it and all its children from the Slate window list.
Notifies the native window to destroy itself and releases rendering resources
Parameters
DestroyedWindow The window to destroy
PrivateDrawWindows()
void FSlateApplication::PrivateDrawWindows (TSharedPtr< SWindow > DrawOnlyThisWindow = nullptr) protected
Draws slate windows, optionally only drawing the passed in window.
ProcessAnalogInputEvent()
bool FSlateApplication::ProcessAnalogInputEvent (const FAnalogInputEvent & InAnalogInputEvent)
Called when a analog input values change.
Parameters
InAnalogInputEvent Analog input event
Returns
Was this event handled by the Slate application?
ProcessApplicationActivationEvent()
void FSlateApplication::ProcessApplicationActivationEvent (bool InAppActivated)
Called when the application is activated (i.e.
one of its windows becomes active) or deactivated.
Parameters
InAppActivated Whether the application was activated.
ProcessCursorReply()
void FSlateApplication::ProcessCursorReply (const FCursorReply & CursorReply)
Apply any requests from the CursorReply.
Parameters
CursorReply The reply generated by an event that was being processed.
ProcessDragEnterEvent()
bool FSlateApplication::ProcessDragEnterEvent (TSharedRef< SWindow > WindowEntered, const FDragDropEvent & DragDropEvent)
Called when a drag from an external (non-slate) source enters a window.
Parameters
WindowEntered The window that was entered by the drag and drop
DragDropEvent Describes the mouse state (position, pressed buttons, etc) and associated payload
Returns
true if the drag enter was handled and can be processed by some widget in this window; false otherwise
ProcessExternalReply()
void FSlateApplication::ProcessExternalReply (const FWidgetPath & CurrentEventPath, const FReply TheReply, const int32 UserIndex = 0, const int32 PointerIndex = 10)
Apply any requests from the Reply to the application.
E.g. Capture mouse
Parameters
CurrentEventPath The WidgetPath along which the reply-generated event was routed
TheReply The reply generated by an event that was being processed.
UserIndex User index that generated the event we are replying to (defaults to 0, at least for now)
PointerIndex Pointer index that generated the event we are replying to
ProcessKeyCharEvent()
bool FSlateApplication::ProcessKeyCharEvent (const FCharacterEvent & InCharacterEvent)
Called when a character is entered.
Parameters
InCharacterEvent Character event
Returns
Was this event handled by the Slate application?
ProcessKeyDownEvent()
bool FSlateApplication::ProcessKeyDownEvent (const FKeyEvent & InKeyEvent)
Called when a key is pressed.
Parameters
InKeyEvent Keyb event
Returns
Was this event handled by the Slate application?
ProcessKeyUpEvent()
bool FSlateApplication::ProcessKeyUpEvent (const FKeyEvent & InKeyEvent)
Called when a key is released.
Parameters
InKeyEvent Key event
Returns
Was this event handled by the Slate application?
ProcessMotionDetectedEvent()
void FSlateApplication::ProcessMotionDetectedEvent (const FMotionEvent & InMotionEvent)
Called when motion is detected (controller or device) when polling game device state.
Parameters
MotionEvent The motion event generated
ProcessMouseButtonDoubleClickEvent()
bool FSlateApplication::ProcessMouseButtonDoubleClickEvent (const TSharedPtr< FGenericWindow > & PlatformWindow, const FPointerEvent & InMouseEvent)
Called by the native application in response to a mouse release.
Routs the event to Slate Widgets.
Parameters
InMouseEvent Mouse event
Returns
Was this event handled by the Slate application?
ProcessMouseButtonDownEvent()
bool FSlateApplication::ProcessMouseButtonDownEvent (const TSharedPtr< FGenericWindow > & PlatformWindow, const FPointerEvent & InMouseEvent)
Called by the native application in response to a mouse button press.
Routs the event to Slate Widgets.
Parameters
PlatformWindow The platform window the event originated from, used to set focus at the platform level. If Invalid the Mouse event will work but there will be no effect on the platform.
InMouseEvent Mouse event
Returns
Was this event handled by the Slate application?
ProcessMouseButtonUpEvent()
bool FSlateApplication::ProcessMouseButtonUpEvent (const FPointerEvent & MouseEvent)
Called by the native application in response to a mouse button release.
Routs the event to Slate Widgets.
Parameters
InMouseEvent Mouse event
Returns
Was this event handled by the Slate application?
References MouseEvent.
ProcessMouseMoveEvent()
bool FSlateApplication::ProcessMouseMoveEvent (const FPointerEvent & MouseEvent, bool bIsSynthetic = false)
Called by the native application in response to a mouse move.
Routs the event to Slate Widgets.
Parameters
InMouseEvent Mouse event
bIsSynthetic True when the even is synthesized by slate.
Returns
Was this event handled by the Slate application?
References MouseEvent.
ProcessMouseWheelOrGestureEvent()
bool FSlateApplication::ProcessMouseWheelOrGestureEvent (const FPointerEvent & InWheelEvent, const FPointerEvent * InGestureEvent)
Called by the native application in response to a mouse wheel spin or a touch gesture.
Routs the event to Slate Widgets.
Parameters
InWheelEvent Mouse wheel event details
InGestureEvent Optional gesture event details
Returns
Was this event handled by the Slate application?
ProcessReply()
void FSlateApplication::ProcessReply (const FWidgetPath & CurrentEventPath, const FReply & TheReply, const FWidgetPath * WidgetsUnderMouse, const FPointerEvent * InMouseEvent, const uint32 UserIndex = 0)
Apply any requests from the Reply to the application.
E.g. Capture mouse
Parameters
CurrentEventPath The WidgetPath along which the reply-generated event was routed
TheReply The reply generated by an event that was being processed.
WidgetsUnderMouse Optional widgets currently under the mouse; initiating drag and drop needs access to widgets under the mouse.
InMouseEvent Optional mouse event that caused this action.
UserIndex User index that generated the event we are replying to (defaults to 0, at least for now)
ProcessTouchEndedEvent()
void FSlateApplication::ProcessTouchEndedEvent (const FPointerEvent & InTouchEvent)
Called when a touchpad touch is ended (finger lifted) when polling game device state.
Parameters
ControllerEvent The touch event generated
ProcessTouchMovedEvent()
void FSlateApplication::ProcessTouchMovedEvent (const FPointerEvent & InTouchEvent)
Called when a touchpad touch is moved (finger moved) when polling game device state.
Parameters
ControllerEvent The touch event generated
ProcessTouchStartedEvent()
void FSlateApplication::ProcessTouchStartedEvent (const TSharedPtr< FGenericWindow > & PlatformWindow, const FPointerEvent & InTouchEvent)
Called when a touchpad touch is started (finger down) when polling game device state.
Parameters
ControllerEvent The touch event generated
ProcessWindowActivatedEvent()
bool FSlateApplication::ProcessWindowActivatedEvent (const FWindowActivateEvent & ActivateEvent)
Called by the native application in response to an activation or deactivation.
Parameters
ActivateEvent Information about the window activation/deactivation
Returns
Was this event handled by the Slate application?
PumpMessages()
void FSlateApplication::PumpMessages ()
Pumps OS messages when a modal window or intra-frame debugging session exists.
PushHostedMenu() [1/2]
TSharedPtr< IMenu > FSlateApplication::PushHostedMenu (const TSharedPtr< IMenu > & InParentMenu, const TSharedRef< IMenuHost > & InMenuHost, const TSharedRef< SWidget > & InContent, TSharedPtr< SWidget > & OutWrappedContent, const FPopupTransitionEffect & TransitionEffect, EShouldThrottle ShouldThrottle, const bool bIsCollapsedByParent = true)
Creates a new hosted child Menu and adds it to the menu stack under the specified parent menu.
Hosted menus are drawn by an external host widget.
Parameters
InParentMenu The parent menu for this menu
InMenuHost The host widget that draws the menu's content
InContent The menu's content
OutWrappedContent Returns the InContent wrapped with widgets needed by the menu stack system. This is what should be drawn by the host after this call.
TransitionEffect Animation to use when the popup appears
ShouldThrottle Should we throttle engine ticking to maximize the menu responsiveness
bIsCollapsedByParent Is this menu collapsed when a parent menu receives focus/activation? If false, only focus/activation outside the entire stack will auto collapse it.
References const, PushHostedMenu(), and FSlateApplicationBase::SWidget.
PushHostedMenu() [2/2]
TSharedPtr< IMenu > FSlateApplication::PushHostedMenu (const TSharedRef< SWidget > & InParentWidget, const FWidgetPath & InOwnerPath, const TSharedRef< IMenuHost > & InMenuHost, const TSharedRef< SWidget > & InContent, TSharedPtr< SWidget > & OutWrappedContent, const FPopupTransitionEffect & TransitionEffect, EShouldThrottle ShouldThrottle, const bool bIsCollapsedByParent = true)
Creates a new hosted Menu and adds it to the menu stack.
Hosted menus are drawn by an external host widget.
Parameters
InParentMenu The parent of the menu. Must be a valid menu in the stack.
InOwnerPath Optional full widget path of the parent if one is available. If an invalid path is given PushMenu will attempt to generate a path to the InParentWidget
InMenuHost The host widget that draws the menu's content
InContent The content to be placed inside the new menu
OutWrappedContent Returns the InContent wrapped with widgets needed by the menu stack system. This is what should be drawn by the host after this call.
TransitionEffect Animation to use when the popup appears
ShouldThrottle Should we throttle engine ticking to maximize the menu responsiveness
bIsCollapsedByParent Is this menu collapsed when a parent menu receives focus/activation? If false, only focus/activation outside the entire stack will auto collapse it.
References const, PushHostedMenu(), and FSlateApplicationBase::SWidget.
Referenced by PushHostedMenu(), and PushHostedMenu().
PushMenu() [1/2]
TSharedPtr< IMenu > FSlateApplication::PushMenu (const TSharedPtr< IMenu > & InParentMenu, const TSharedRef< SWidget > & InContent, const UE::Slate::FDeprecateVector2DParameter & SummonLocation, const FPopupTransitionEffect & TransitionEffect, const bool bFocusImmediately = true, const UE::Slate::FDeprecateVector2DParameter & SummonLocationSize = FVector2f::ZeroVector, const bool bIsCollapsedByParent = true, const int32 FocusUserIndex = INDEX_NONE)
Creates a new Menu and adds it to the menu stack under the specified parent menu.
Menus are always auto-sized. Use fixed-size content if a fixed size is required.
Parameters
InParentMenu The parent of the menu. Must be a valid menu in the stack.
InContent The content to be placed inside the new menu
SummonLocation The location where this menu should be summoned
TransitionEffect Animation to use when the popup appears
bFocusImmediately Should the popup steal focus when shown?
SummonLocationSize An optional rect which describes an area in which the menu may not appear
bIsCollapsedByParent Is this menu collapsed when a parent menu receives focus/activation? If false, only focus/activation outside the entire stack will auto collapse it.
FocusUserIndex The index of the user that should focus the menu. INDEX_NONE for all users.
References const, INDEX_NONE, PushMenu(), and FSlateApplicationBase::SWidget.
PushMenu() [2/2]
TSharedPtr< IMenu > FSlateApplication::PushMenu (const TSharedRef< SWidget > & InParentWidget, const FWidgetPath & InOwnerPath, const TSharedRef< SWidget > & InContent, const UE::Slate::FDeprecateVector2DParameter & SummonLocation, const FPopupTransitionEffect & TransitionEffect, const bool bFocusImmediately = true, const UE::Slate::FDeprecateVector2DParameter & SummonLocationSize = FVector2f::ZeroVector, TOptional< EPopupMethod > Method = TOptional< EPopupMethod >(), const bool bIsCollapsedByParent = true, const int32 FocusUserIndex = INDEX_NONE)
Creates a new Menu and adds it to the menu stack.
Menus are always auto-sized. Use fixed-size content if a fixed size is required.
Parameters
InParentWidget The parent of the menu. If the stack isn't empty, PushMenu will attempt to determine the stack level for the new menu by looking of an open menu in the parent's path.
InOwnerPath Optional full widget path of the parent if one is available. If an invalid path is given PushMenu will attempt to generate a path to the InParentWidget
InContent The content to be placed inside the new menu
SummonLocation The location where this menu should be summoned
TransitionEffect Animation to use when the popup appears
bFocusImmediately Should the popup steal focus when shown?
SummonLocationSize An optional rect which describes an area in which the menu may not appear
Method An optional popup method override. If not set, the widgets in the InOwnerPath will be queried for this.
bIsCollapsedByParent Is this menu collapsed when a parent menu receives focus/activation? If false, only focus/activation outside the entire stack will auto collapse it.
FocusUserIndex The index of the user that should focus the menu. INDEX_NONE for all users.
References const, INDEX_NONE, PushMenu(), and FSlateApplicationBase::SWidget.
Referenced by PushMenu(), and PushMenu().
QueryCursor()
void FSlateApplication::QueryCursor ()
Bubble a request for which cursor to display for widgets under the mouse or the widget that captured the mouse.
RegisterGameViewport()
void FSlateApplication::RegisterGameViewport (TSharedRef< SViewport > InViewport)
Registers a game viewport with the Slate application so that specific messages can be routed directly to a viewport.
Parameters
InViewport The viewport to register. Note there is currently only one registered viewport
RegisterInputPreProcessor() [1/4]
bool FSlateApplication::RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor)
Adds input pre-processor if unique.
Parameters
InputProcessor The input pre-processor to add. Defaults to using the EInputPreProcessorType::Game bucket type and adding at the end of the bucket.
Returns
True if added to list of input pre-processors, false if not
RegisterInputPreProcessor() [2/4]
bool FSlateApplication::RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const EInputPreProcessorType Type)
Adds input pre-processor if unique.
Parameters
InputProcessor The input pre-processor to add.
Type Which bucket to insert the processor in. Defaults to adding at the end of the bucket.
Returns
True if added to list of input pre-processors, false if not
RegisterInputPreProcessor() [3/4]
bool FSlateApplication::RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const FInputPreprocessorRegistrationKey & Info)
Adds input pre-processor if unique.
Parameters
InputProcessor The input pre-processor to add.
Info Information specifying which priority type and index should be used to register the pre-processor.
Returns
True if added to list of input pre-processors, false if not
References Info.
RegisterInputPreProcessor() [4/4]
bool FSlateApplication::RegisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor, const int32 Index)
Adds input pre-processor if unique.
Parameters
InputProcessor The input pre-processor to add.
Index Where to insert the InputProcessor within the type bucket. Defaults to using the EInputPreProcessorType::Game type.
Returns
True if added to list of input pre-processors, false if not
RegisterNewUser() [1/2]
TSharedRef< FSlateUser > FSlateApplication::RegisterNewUser (FPlatformUserId PlatformUserId, bool bIsVirtual = false) protected
Register a new user with Slate.
Normally this is unnecessary as Slate automatically adds a user entry if it gets input from a controller for that index. Might happen if the user allocates the virtual user.
RegisterNewUser() [2/2]
TSharedRef< FSlateUser > FSlateApplication::RegisterNewUser (int32 UserIndex, bool bIsVirtual = false) protected
Register a new user with Slate.
Normally this is unnecessary as Slate automatically adds a user entry if it gets input from a controller for that index. Might happen if the user allocates the virtual user.
RegisterOnWindowActionNotification()
FDelegateHandle FSlateApplication::RegisterOnWindowActionNotification (const FOnWindowAction & Notification)
Register for a notification when the window action occurs.
Parameters
Notification The notification to invoke.
Returns
Handle to the registered delegate.
References FOnWindowAction, and Notification.
RegisterViewport()
void FSlateApplication::RegisterViewport (TSharedRef< SViewport > InViewport)
Registers a viewport with the Slate application so that specific messages can be routed directly to a viewport This is for all viewports, there can be multiple of these as opposed to the singular "Game Viewport".
Parameters
InViewport The viewport to register. Note there is currently only one registered viewport
RegisterVirtualWindow()
void FSlateApplication::RegisterVirtualWindow (TSharedRef< SWindow > InWindow)
Register another window that may be visible in a non-top level way that still needs to be able to maintain focus paths.
Generally speaking - this is for Virtual Windows that are created to render in the 3D world slate content.
ReleaseAllPointerCapture() [1/2]
void FSlateApplication::ReleaseAllPointerCapture ()
Releases capture for every pointer on every user from whatever it currently is on.
Referenced by ReleaseAllPointerCapture().
ReleaseAllPointerCapture() [2/2]
void FSlateApplication::ReleaseAllPointerCapture (int32 UserIndex)
Releases capture for every pointer belonging to the given user index particular user.
References ReleaseAllPointerCapture().
RequestDestroyWindow()
virtual void FSlateApplication::RequestDestroyWindow (TSharedRef< SWindow > WindowToDestroy) override virtual
Destroying windows has implications on some OSs (e.g.
destroying Win32 HWNDs can cause events to be lost).
Slate strictly controls when windows are destroyed.
Parameters
WindowToDestroy The window to queue for destruction.
Implements FSlateApplicationBase.
ResetToDefaultInputSettings()
void FSlateApplication::ResetToDefaultInputSettings ()
Restores all input settings to their original values.
Clears all user focus Shows the mouse, clears any locks and captures, turns off high precision input
ResetToDefaultPointerInputSettings()
void FSlateApplication::ResetToDefaultPointerInputSettings ()
Restores all pointer input settings to their original values.
Shows the mouse, clears any locks and captures, turns off high precision input
RouteMouseWheelOrGestureEvent()
FReply FSlateApplication::RouteMouseWheelOrGestureEvent (const FWidgetPath & WidgetsUnderPointer, const FPointerEvent & InWheelEvent, const FPointerEvent * InGestureEvent = nullptr)
Directly routes a pointer mouse wheel or gesture event to the widgets in the specified widget path.
Parameters
WidgetsUnderPointer The path of widgets the event is routed to.
InWheelEvent The event data that is is routed to the widget path
InGestureEvent The event data that is is routed to the widget path
RoutePointerDoubleClickEvent()
FReply FSlateApplication::RoutePointerDoubleClickEvent (const FWidgetPath & WidgetsUnderPointer, const FPointerEvent & PointerEvent)
Directly routes a pointer double click event to the widgets in the specified widget path.
Parameters
WidgetsUnderPointer The path of widgets the event is routed to.
PointerEvent The event data that is is routed to the widget path
RoutePointerDownEvent()
FReply FSlateApplication::RoutePointerDownEvent (const FWidgetPath & WidgetsUnderPointer, const FPointerEvent & PointerEvent)
Directly routes a pointer down event to the widgets in the specified widget path.
Parameters
WidgetsUnderPointer The path of widgets the event is routed to.
PointerEvent The event data that is is routed to the widget path
Returns
The reply returned by the widget that handled the event
RoutePointerMoveEvent()
bool FSlateApplication::RoutePointerMoveEvent (const FWidgetPath & WidgetsUnderPointer, const FPointerEvent & PointerEvent, bool bIsSynthetic)
Directly routes a pointer move event to the widgets in the specified widget path.
Parameters
WidgetsUnderPointer The path of widgets the event is routed to.
PointerEvent The event data that is is routed to the widget path
bIsSynthetic Whether or not the move event is synthetic. Synthetic pointer moves used simulate an event without the pointer actually moving
RoutePointerUpEvent()
FReply FSlateApplication::RoutePointerUpEvent (const FWidgetPath & WidgetsUnderPointer, const FPointerEvent & PointerEvent)
Directly routes a pointer up event to the widgets in the specified widget path.
Parameters
WidgetsUnderPointer The path of widgets the event is routed to.
PointerEvent The event data that is is routed to the widget path
Returns
The reply from the event
SetAllowTooltips()
void FSlateApplication::SetAllowTooltips (bool bCanShow)
References SetAllowTooltips().
Referenced by SetAllowTooltips().
SetAllUserFocus() [1/2]
virtual void FSlateApplication::SetAllUserFocus (const FWidgetPath & InFocusPath, const EFocusCause InCause) override virtual
Sets the focus for all users to the specified widget.
The widget must be allowed to receive focus.
Parameters
InFocusPath WidgetPath to the Widget to being focused.
InCause The reason that focus is changing.
Implements FSlateApplicationBase.
SetAllUserFocus() [2/2]
void FSlateApplication::SetAllUserFocus (const TSharedPtr< SWidget > & WidgetToFocus, EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Sets focus for all users to the SWidget passed in.
Parameters
WidgetToFocus the widget to set focus to
ReasonFocusIsChanging the contextual reason for the focus change
SetAllUserFocusAllowingDescendantFocus()
virtual void FSlateApplication::SetAllUserFocusAllowingDescendantFocus (const FWidgetPath & InFocusPath, const EFocusCause InCause) override virtual
Sets the focus for all users to the specified widget unless that user is focused on a descendant.
The widget must be allowed to receive focus.
Parameters
InWidget WidgetPath to the Widget to being focused.
InCause The reason that focus is changing.
Implements FSlateApplicationBase.
SetAllUserFocusToGameViewport()
void FSlateApplication::SetAllUserFocusToGameViewport (EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Sets all users focus to the SWidget representing the currently active game viewport.
SetApplicationScale()
void FSlateApplication::SetApplicationScale (float InScale) inline
Parameters
Scale Sets the ratio SlateUnit / ScreenPixel
Definition at line 872 of file SlateApplication.h.
References Scale.
SetCursorPos()
void FSlateApplication::SetCursorPos (const FVector2D & MouseCoordinate) override virtual
Sets the position of the cursor.
Parameters
MouseCoordinate The new position.
Reimplemented from FGenericApplicationMessageHandler.
SetCursorRadius()
void FSlateApplication::SetCursorRadius (float NewRadius)
Sets the hit detection radius of the cursor.
References SetCursorRadius().
Referenced by SetCursorRadius().
SetDragTriggerDistance()
void FSlateApplication::SetDragTriggerDistance (float ScreenPixels)
Set the size of the deadzone for dragging in screen pixels.
SetExitRequestedHandler()
void FSlateApplication::SetExitRequestedHandler (const FSimpleDelegate & OnExitRequestedHandler)
Assign a delegate to be called when this application is requesting an exit (e.g.
when the last window is closed).
Parameters
OnExitRequestHandler Function to execute when the application wants to quit
References const, and SetExitRequestedHandler().
Referenced by SetExitRequestedHandler().
SetFixedDeltaTime()
void FSlateApplication::SetFixedDeltaTime (double InSeconds) static
Sets time step in seconds if a fixed delta time is wanted.
Parameters
seconds Time step in seconds for fixed delta time.
SetGameAllowsFakingTouchEvents()
void FSlateApplication::SetGameAllowsFakingTouchEvents (const bool bAllowFaking)
Sets whether the application is allowed to fake touches or not.
SetGameIsFakingTouchEvents()
void FSlateApplication::SetGameIsFakingTouchEvents (const bool bIsFaking, FVector2D * CursorLocation = nullptr)
Sets whether the application is treating mouse events as imitating touch events.
Optional CursorLocation can be supplied to override the platform's belief of where the cursor is
SetHandleDeviceInputWhenApplicationNotActive()
void FSlateApplication::SetHandleDeviceInputWhenApplicationNotActive (bool bAllow) inline
Mouse capture.
Parameters
bAllow If true, mouse pointer capture will be processed even when the application is not active or widget is not a virtual window
Definition at line 759 of file SlateApplication.h.
References bHandleDeviceInputWhenApplicationNotActive.
SetInputManager()
void FSlateApplication::SetInputManager (TSharedRef< ISlateInputManager > InputManager)
Establishes the input mapping object used to map input sources to SlateUser indices.
References InputManager.
SetKeyboardFocus() [1/2]
virtual bool FSlateApplication::SetKeyboardFocus (const FWidgetPath & InFocusPath, const EFocusCause InCause) override virtual
Sets keyboard focus to the specified widget.
The widget must be allowed to receive keyboard focus.
Parameters
InFocusPath WidgetPath to the Widget to being focused
InCause The reason that keyboard focus is changing
Returns
true if the widget is now focused, false otherwise.
Implements FSlateApplicationBase.
SetKeyboardFocus() [2/2]
bool FSlateApplication::SetKeyboardFocus (const TSharedPtr< SWidget > & OptionalWidgetToFocus, EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Sets the Keyboard focus to the specified SWidget.
SetLastUserInteractionTime()
void FSlateApplication::SetLastUserInteractionTime (const double InCurrentTime) private
SetModalWindowStackEndedDelegate()
void FSlateApplication::SetModalWindowStackEndedDelegate (FModalWindowStackEnded StackEndedDelegate)
Sets the delegate for when a modal window stack ends.
References SetModalWindowStackEndedDelegate().
Referenced by SetModalWindowStackEndedDelegate().
SetModalWindowStackStartedDelegate()
void FSlateApplication::SetModalWindowStackStartedDelegate (FModalWindowStackStarted StackStartedDelegate)
Sets the delegate for when a modal window stack begins.
References SetModalWindowStackStartedDelegate().
Referenced by SetModalWindowStackStartedDelegate().
SetNavigationConfig()
void FSlateApplication::SetNavigationConfig (TSharedRef< FNavigationConfig > InNavigationConfig)
Sets the navigation config.
If you need to control navigation config dynamically, you should subclass FNavigationConfig to be dynamically adjustable to your needs.
SetPlatformApplication()
void FSlateApplication::SetPlatformApplication (const TSharedRef< class GenericApplication > & InPlatformApplication)
References const, and SetPlatformApplication().
Referenced by SetPlatformApplication().
SetPlatformCursorVisibility()
void FSlateApplication::SetPlatformCursorVisibility (bool bNewVisibility)
Changes the cursor type to Default (Visible) or None (Not Visible)
SetUnhandledKeyDownEventHandler()
void FSlateApplication::SetUnhandledKeyDownEventHandler (const FOnKeyEvent & NewHandler)
Sets the handler for otherwise unhandled key down events.
This is used by the editor to provide a global action list, if the key was not consumed by any widget.
SetUnhandledKeyUpEventHandler()
void FSlateApplication::SetUnhandledKeyUpEventHandler (const FOnKeyEvent & NewHandler)
Sets the handler for otherwise unhandled key down events.
This is used by the editor to provide a global action list, if the key was not consumed by any widget.
SetupPhysicalSensitivities()
void FSlateApplication::SetupPhysicalSensitivities () protected
Sets up any values that need to be based on the physical dimensions of the device.
Such as dead zones associated with precise tapping...etc
SetUserFocus() [1/3]
virtual bool FSlateApplication::SetUserFocus (const uint32 InUserIndex, const FWidgetPath & InFocusPath, const EFocusCause InCause) override virtual
Sets user focus to the specified widget.
The widget must be allowed to receive focus.
Parameters
InUserIndex Index of the user that we want to change the focus of.
InFocusPath WidgetPath to the Widget to being focused.
InCause The reason that focus is changing.
Returns
true if the widget is now focused, false otherwise.
Implements FSlateApplicationBase.
SetUserFocus() [2/3]
bool FSlateApplication::SetUserFocus (FSlateUser & User, const FWidgetPath & InFocusPath, const EFocusCause InCause) private
SetUserFocus() [3/3]
bool FSlateApplication::SetUserFocus (uint32 UserIndex, const TSharedPtr< SWidget > & WidgetToFocus, EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Sets specified user focus to the SWidget passed in.
Parameters
UserIndex Index of the user to change focus for
WidgetToFocus the widget to set focus to
ReasonFocusIsChanging the contextual reason for the focus change
SetUserFocusAllowingDescendantFocus()
virtual bool FSlateApplication::SetUserFocusAllowingDescendantFocus (const uint32 InUserIndex, const FWidgetPath & InFocusPath, const EFocusCause InCause) override virtual
Sets the focus for the specified user to the specified widget unless that user is focused on a descendant.
The widget must be allowed to receive focus.
Parameters
InUserIndex Index of the user that we want to change the focus of.
InFocusPath WidgetPath to the Widget to being focused.
InCause The reason that focus is changing.
Returns
true if the widget or a descendant is now focused, false otherwise.
Implements FSlateApplicationBase.
SetUserFocusToGameViewport()
void FSlateApplication::SetUserFocusToGameViewport (uint32 UserIndex, EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly)
Sets specified user focus to the SWidget representing the currently active game viewport.
SetWidgetReflector()
void FSlateApplication::SetWidgetReflector (const TSharedRef< IWidgetReflector > & WidgetReflector)
Sets the widget reflector.
Parameters
WidgetReflector The widget reflector to set.
SetWidgetReflectorAssetAccessDelegate()
void FSlateApplication::SetWidgetReflectorAssetAccessDelegate (FAccessAsset AccessDelegate) inline
Parameters
AccessDelegate The delegate to pass along to the widget reflector
Definition at line 866 of file SlateApplication.h.
References AssetAccessDelegate.
SetWidgetReflectorQuerySourceAccessDelegate()
void FSlateApplication::SetWidgetReflectorQuerySourceAccessDelegate (FQueryAccessSourceCode QueryAccessDelegate) inline
Parameters
QueryAccessDelegate The delegate to pass along to the widget reflector
Definition at line 860 of file SlateApplication.h.
References QuerySourceCodeAccessDelegate.
SetWidgetReflectorSourceAccessDelegate()
void FSlateApplication::SetWidgetReflectorSourceAccessDelegate (FAccessSourceCode AccessDelegate) inline
Parameters
AccessDelegate The delegate to pass along to the widget reflector
Definition at line 854 of file SlateApplication.h.
References FAccessSourceCode, and SourceCodeAccessDelegate.
ShouldProcessUserInputMessages()
virtual bool FSlateApplication::ShouldProcessUserInputMessages (const TSharedPtr< FGenericWindow > & PlatformWindow) const override virtual
Reimplemented from FGenericApplicationMessageHandler.
ShouldSimulateGesture()
virtual void FSlateApplication::ShouldSimulateGesture (EGestureEvent Gesture, bool bEnable) override virtual
Reimplemented from FGenericApplicationMessageHandler.
ShowSystemHelp()
void FSlateApplication::ShowSystemHelp () inline
Definition at line 359 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
ShowUserFocus()
virtual bool FSlateApplication::ShowUserFocus (const TSharedPtr< const SWidget > Widget) const override protected virtual
Gets whether or not a particular widget should show user focus.
Returns
True if we should show user focus
Implements FSlateApplicationBase.
ShowVirtualKeyboard()
void FSlateApplication::ShowVirtualKeyboard (bool bShow, int32 UserIndex, TSharedPtr< IVirtualKeyboardEntry > TextEntryWidget = nullptr)
Shows or hides an onscreen keyboard.
Parameters
bShow true to show the keyboard, false to hide it
TextEntryWidget The widget that will receive the input from the virtual keyboard
Shutdown()
void FSlateApplication::Shutdown (bool bShutdownPlatform = true) static
SignalSystemDPIChanged()
virtual void FSlateApplication::SignalSystemDPIChanged (const TSharedRef< FGenericWindow > & Window) override virtual
Reimplemented from FGenericApplicationMessageHandler.
SpawnToolTip()
void FSlateApplication::SpawnToolTip (const TSharedRef< IToolTip > & InToolTip, const UE::Slate::FDeprecateVector2DParameter & InSpawnLocation)
Spawns a tool tip window.
If an existing tool tip window is open, it will be dismissed first.
Parameters
InToolTip Widget to display.
InSpawnLocation Screen space location to show the tool tip (window top left)
SupportsSourceAccess()
bool FSlateApplication::SupportsSourceAccess () const
Returns
true if the current platform allows source code access
SupportsSystemHelp()
bool FSlateApplication::SupportsSystemHelp () const inline
Returns
Whether or not the current platform supports system help
Definition at line 357 of file SlateApplication.h.
References FSlateApplicationBase::PlatformApplication.
TakeHDRScreenshot() [1/2]
bool FSlateApplication::TakeHDRScreenshot (const TSharedRef< SWidget > & Widget, const FIntRect & InnerWidgetArea, TArray< FLinearColor > & OutColorData, FIntVector & OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided, this version allows you to provide an inner area to screenshot.
Note that the format is BGRA. The size of the resulting image is also output.
Returns
true if taking the screenshot was successful.
TakeHDRScreenshot() [2/2]
bool FSlateApplication::TakeHDRScreenshot (const TSharedRef< SWidget > & Widget, TArray< FLinearColor > & OutColorData, FIntVector & OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided.
This is to be used with HDR buffers the size of the resulting image is also output.
Returns
true if taking the screenshot was successful.
TakeScreenshot() [1/2]
bool FSlateApplication::TakeScreenshot (const TSharedRef< SWidget > & Widget, const FIntRect & InnerWidgetArea, TArray< FColor > & OutColorData, FIntVector & OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided, this version allows you to provide an inner area to screenshot.
Note that the format is BGRA. The size of the resulting image is also output.
Returns
true if taking the screenshot was successful.
TakeScreenshot() [2/2]
bool FSlateApplication::TakeScreenshot (const TSharedRef< SWidget > & Widget, TArray< FColor > & OutColorData, FIntVector & OutSize)
Takes a screenshot of the widget writing the results into the color buffer provided.
Note that the format is BGRA. the size of the resulting image is also output.
Returns
true if taking the screenshot was successful.
ThrottleApplicationBasedOnMouseMovement()
void FSlateApplication::ThrottleApplicationBasedOnMouseMovement () protected
Engages or disengages application throttling based on user behavior.
Tick()
void FSlateApplication::Tick (ESlateTickType TickType = ESlateTickType::All)
Ticks this application.
References All.
TickAndDrawWidgets()
void FSlateApplication::TickAndDrawWidgets (float DeltaTime) protected
Ticks and paints the actual Slate portion of the application.
References DeltaTime.
TickPlatform()
void FSlateApplication::TickPlatform (float DeltaTime) protected
Pumps and ticks the platform.
References DeltaTime.
TickTime()
void FSlateApplication::TickTime () protected
Advances time for the application.
TransformPointerEvent()
FPointerEvent FSlateApplication::TransformPointerEvent (const FPointerEvent & PointerEvent, const TSharedPtr< SWindow > & Window) const protected
Transforms a pointer event to account for non-standard viewport resolutions.
UE_DEPRECATED() [1/9]
FSlateApplication::UE_DEPRECATED (4. 20, "Returning to a simpler method of registering navigation configs.\ nSetNavigationConfig, is what you should use now. Note:You 'll need to store per user state information yourself if you have any, like we do for repeats with the analog stick in FNavigationConfig::UserNavigationState , \nrather than Slate creating a new Navigation Config per user.") inline
Sets the navigation config factory.
If you need to control navigation config dynamically, you should subclass FNavigationConfig to be dynamically adjustable to your needs.
Definition at line 1396 of file SlateApplication.h.
UE_DEPRECATED() [2/9]
FSlateApplication::UE_DEPRECATED (4. 23, "ForEachUser now provides an FSlateUser& parameter to the lambda instead of an FSlateUser*")
UE_DEPRECATED() [3/9]
FSlateApplication::UE_DEPRECATED (4. 23, "ReleaseMouseCapture has been renamed to ReleaseAllPointerCapture()")
UE_DEPRECATED() [4/9]
FSlateApplication::UE_DEPRECATED (4. 23, "ReleaseMouseCaptureForUser has been renamed to ReleaseAllPointerCapture(int32 UserIndex)")
References UE_DEPRECATED().
UE_DEPRECATED() [5/9]
FSlateApplication::UE_DEPRECATED (4. 23, "The FindWidgetWindow method that takes an FWidgetPath has been deprecated. If you dont need the widget path, use FindWidgetWindow(MyWidget) instead. If you need the path use GeneratePathToWidget") const
Finds the window that the provided widget resides in.
Parameters
InWidget The widget to find the window for
OutWidgetPath Full widget path generated
Returns
The window where the widget resides, or null if the widget wasn't found. Remember, a widget might not be found simply because its parent decided not to report the widget in ArrangeChildren.
References UE_DEPRECATED().
UE_DEPRECATED() [6/9]
FSlateApplication::UE_DEPRECATED (4. 24, "GetNavigationActionForKey doesn't handle multiple users properly, use GetNavigationActionFromKey instead") const & override
References const, and FSlateApplicationBase::GetNavigationActionForKey().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [7/9]
FSlateApplication::UE_DEPRECATED (4. 26, "SetAppIcon has been deprecated. Set \"AppIcon\" in your applications style to override the icon") const
Set the global application icon.
References const, and UE_DEPRECATED().
UE_DEPRECATED() [8/9]
FSlateApplication::UE_DEPRECATED (5. 0, "Enable Window Animations is no longer used and is a no-op so calling this function is no longer necessary.") const
Sets whether transition effects for new menus and windows should be played.
This can be called at any time.
Parameters
bEnableAnimations True if animations should be used, otherwise false.
References const.
UE_DEPRECATED() [9/9]
FSlateApplication::UE_DEPRECATED (5. 5, "This method is deprecated and will use EInputPreProcessorType::Game as a default. For a more accurate search result, please use the new version taking a EInputPreProcessorType") const
Get the index of a registered pre-processor.
Parameters
InputProcessor The input pre-processor to find.
Returns
The index of the pre-processor, or INDEX_NONE if not registered.
References const, and FindInputPreProcessor().
UnregisterGameViewport()
void FSlateApplication::UnregisterGameViewport ()
Unregisters the current game viewport from Slate.
This method sends a final deactivation message to the viewport to allow it to do a final cleanup before being closed.
UnregisterInputPreProcessor()
void FSlateApplication::UnregisterInputPreProcessor (TSharedPtr< class IInputProcessor > InputProcessor)
Removes an input pre-processor.
Parameters
InputProcessor The input pre-processor to Remove.
UnregisterOnWindowActionNotification()
void FSlateApplication::UnregisterOnWindowActionNotification (FDelegateHandle Handle)
Unregister the notification because it is no longer desired.
Parameters
Handle Handle to the delegate to unregister.
References Handle.
UnregisterUser()
void FSlateApplication::UnregisterUser (int32 UserIndex)
UnregisterVirtualWindow()
void FSlateApplication::UnregisterVirtualWindow (TSharedRef< SWindow > InWindow)
Unregister a virtual window.
UpdateToolTip()
void FSlateApplication::UpdateToolTip (bool bAllowSpawningOfNewToolTips)
UsePlatformCursorForCursorUser()
void FSlateApplication::UsePlatformCursorForCursorUser (bool bUsePlatformCursor)
Updates the cursor user's cursor to either the platform cursor or fake cursor.
Friends And Related Symbol Documentation
FEventRouter
friend class FEventRouter friend
Definition at line 1180 of file SlateApplication.h.
References FEventRouter.
Referenced by FEventRouter.
Field Documentation
ActiveModalWindows
TArray< TSharedPtr<SWindow> > FSlateApplication::ActiveModalWindows private
List of active modal windows.
The last item in the list is the top-most modal window
Definition at line 1929 of file SlateApplication.h.
ActiveTopLevelWindow
TWeakPtr<SWindow> FSlateApplication::ActiveTopLevelWindow private
The currently active slate window that is a top-level window (full fledged window; not a menu or tooltip)
Definition at line 1926 of file SlateApplication.h.
AllGameViewports
TSet<TWeakPtr<SViewport> > FSlateApplication::AllGameViewports private
List of all registered game viewports since the last time UnregisterGameViewport was called.
Definition at line 1989 of file SlateApplication.h.
AppIcon
const FSlateBrush* FSlateApplication::AppIcon private
The icon to use on application windows.
Definition at line 2104 of file SlateApplication.h.
ApplicationActivationStateChangedEvent
FApplicationActivationStateChangedEvent FSlateApplication::ApplicationActivationStateChangedEvent private
Definition at line 2106 of file SlateApplication.h.
Referenced by DECLARE_EVENT_OneParam().
AssetAccessDelegate
FAccessAsset FSlateApplication::AssetAccessDelegate private
Delegate for accessing assets, to pass to any widget inspectors.
Definition at line 2030 of file SlateApplication.h.
Referenced by SetWidgetReflectorAssetAccessDelegate().
AverageDeltaTime
float FSlateApplication::AverageDeltaTime private
Running average time in seconds between calls to Tick (used for monitoring responsiveness)
Definition at line 2007 of file SlateApplication.h.
Referenced by GetAverageDeltaTime().
AverageDeltaTimeForResponsiveness
float FSlateApplication::AverageDeltaTimeForResponsiveness private
Average delta time for application responsiveness tracking.
This is like AverageDeltaTime, but it excludes frame deltas spent while the the application is in a throttled state
Definition at line 2011 of file SlateApplication.h.
Referenced by GetAverageDeltaTimeForResponsiveness().
bAllowFakingTouch
bool FSlateApplication::bAllowFakingTouch private
Restricts or allows the faking of touches.
Definition at line 2079 of file SlateApplication.h.
bAppIsActive
bool FSlateApplication::bAppIsActive private
true when the slate app is active; i.e.
the current foreground window is from our Slate app
Definition at line 1905 of file SlateApplication.h.
Referenced by IsActive().
bHandleDeviceInputWhenApplicationNotActive
bool FSlateApplication::bHandleDeviceInputWhenApplicationNotActive private
Force Mouse Pointer Capture to always occur even when the application is not active or widget is not a virtual window.
Definition at line 2082 of file SlateApplication.h.
Referenced by GetHandleDeviceInputWhenApplicationNotActive(), and SetHandleDeviceInputWhenApplicationNotActive().
bIncludeVirtualUsers
bool FSlateApplication::bIncludeVirtualUsers = false)
Definition at line 1127 of file SlateApplication.h.
Referenced by ForEachUser().
bIsExternalUIOpened
bool FSlateApplication::bIsExternalUIOpened private
Keeps track of whether or not the UI for services such as Steam is open.
Definition at line 2056 of file SlateApplication.h.
Referenced by ExternalUIChange().
bIsFakingTouch
bool FSlateApplication::bIsFakingTouch private
For desktop platforms that want to test touch style input, pass -faketouches or -simmobile on the commandline to set this.
Definition at line 2070 of file SlateApplication.h.
bIsFakingTouched
bool FSlateApplication::bIsFakingTouched private
For desktop platforms that the touch move event be called when this variable is true.
Definition at line 2076 of file SlateApplication.h.
bIsGameFakingTouch
bool FSlateApplication::bIsGameFakingTouch private
For games that want to allow mouse to imitate touch.
Definition at line 2073 of file SlateApplication.h.
bIsTicking
bool FSlateApplication::bIsTicking = false private
Are we ticking the SlateApplication.
Definition at line 2162 of file SlateApplication.h.
bLeaveDebugForSingleStep
bool FSlateApplication::bLeaveDebugForSingleStep private
Whether or not we need to leave debug mode for single stepping.
Definition at line 2044 of file SlateApplication.h.
bMenuAnimationsEnabled
bool FSlateApplication::bMenuAnimationsEnabled private
Slate look and feel.
Globally enables or disables transition effects for pop-up menus (menu stacks)
Definition at line 2101 of file SlateApplication.h.
bRenderOffScreen
bool FSlateApplication::bRenderOffScreen private
true if rendering windows even when they are set to invisible
Definition at line 1911 of file SlateApplication.h.
Referenced by IsRenderingOffScreen().
bRequestLeaveDebugMode
bool FSlateApplication::bRequestLeaveDebugMode private
Whether or not we are requesting that we leave debugging mode after the tick is complete.
Definition at line 2042 of file SlateApplication.h.
bSlateWindowActive
bool FSlateApplication::bSlateWindowActive private
true if any slate window is currently active (not just top level windows)
Definition at line 1908 of file SlateApplication.h.
bSoftwareCursorAvailable
bool FSlateApplication::bSoftwareCursorAvailable private
.ini controlled option to allow or disallow software cursor rendering
Definition at line 2094 of file SlateApplication.h.
Referenced by GetSoftwareCursorAvailable().
bSynthesizedCursorMove
bool FSlateApplication::bSynthesizedCursorMove = false private
Did we synthesize cursor input this frame?
Definition at line 2159 of file SlateApplication.h.
bTouchFallbackToMouse
bool FSlateApplication::bTouchFallbackToMouse private
controls whether unhandled touch events fall back to sending mouse events
Definition at line 2091 of file SlateApplication.h.
const
FWidgetPath& OutWidgetPath FSlateApplication::const
Definition at line 823 of file SlateApplication.h.
Referenced by AddModalWindow(), AddWindowAsNativeChild(), AnyMenusVisible(), DismissMenu(), DismissMenuByWidget(), FindInputPreProcessor(), FindMenuInWidgetPath(), FindWidgetWindow(), GeneratePathToWidgetChecked(), GeneratePathToWidgetUnchecked(), GetActiveModalWindow(), GetAllowTooltips(), GetCursorRadius(), GetMenuHostWidget(), GetVisibleMenuWindow(), HasOpenSubMenus(), PushHostedMenu(), PushHostedMenu(), PushMenu(), PushMenu(), SetExitRequestedHandler(), SetPlatformApplication(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
CurrentApplication
TSharedPtr< FSlateApplication > FSlateApplication::CurrentApplication static private
Application singleton.
Definition at line 1900 of file SlateApplication.h.
Referenced by Get(), and IsInitialized().
CurrentDebugContextWidget
TWeakPtr<SWidget> FSlateApplication::CurrentDebugContextWidget private
The painting SWindow.
Definition at line 1956 of file SlateApplication.h.
CurrentDebuggingWindow
TWeakPtr<SWindow> FSlateApplication::CurrentDebuggingWindow private
Definition at line 1957 of file SlateApplication.h.
CurrentTime
double FSlateApplication::CurrentTime private
The current cached absolute real time, right before we tick widgets.
Definition at line 2001 of file SlateApplication.h.
Referenced by GetCurrentTime(), and GetDeltaTime().
CursorRadius
float FSlateApplication::CursorRadius private
The hit-test radius of the cursor.
Default value is 0.
Definition at line 1938 of file SlateApplication.h.
DebuggingModeNotificationMessage
TWeakPtr<SNotificationItem> FSlateApplication::DebuggingModeNotificationMessage private
The message when the EnterDebugginMode failed.
Definition at line 1996 of file SlateApplication.h.
DragIsHandled
bool FSlateApplication::DragIsHandled private
When an drag and drop is happening, we keep track of whether slate knew what to do with the payload on last mouse move.
Definition at line 2062 of file SlateApplication.h.
DragTriggerDistance
float FSlateApplication::DragTriggerDistance private
The dead zone distance in virtual desktop pixels (a.k.a screen pixels) that the user has to move their finder before it is considered a drag.
Definition at line 1917 of file SlateApplication.h.
EditorNavigationConfig
TSharedRef<FNavigationConfig> FSlateApplication::EditorNavigationConfig private
When PIE runs, the game's navigation config will overwrite the editor's navigation config.
This separate config allows editor navigation to work even when PIE is running.
Definition at line 2122 of file SlateApplication.h.
FixedDeltaTime
double FSlateApplication::FixedDeltaTime static private
Constant delta time used on every Slate widget Tick if CVarSlateUseFixedDeltaTime is enabled.
Definition at line 2171 of file SlateApplication.h.
Referenced by GetFixedDeltaTime().
FocusChangingDelegate
FOnFocusChanging FSlateApplication::FocusChangingDelegate private
Delegate for when focus might be about to change.
Definition at line 2150 of file SlateApplication.h.
Referenced by OnFocusChanging().
GameViewportWidget
TWeakPtr<SViewport> FSlateApplication::GameViewportWidget private
Pointer to the currently registered game viewport widget if any.
Definition at line 1985 of file SlateApplication.h.
InputManager
TSharedRef<ISlateInputManager> FSlateApplication::InputManager private
Allows applications finer control over how we map controllers to users.
Definition at line 2243 of file SlateApplication.h.
Referenced by SetInputManager().
InputPreProcessors
InputPreProcessorsHelper FSlateApplication::InputPreProcessors private
A list of input pre-processors, gets an opportunity to parse input before anything else.
Definition at line 2240 of file SlateApplication.h.
LastAllUsersFocusCause
EFocusCause FSlateApplication::LastAllUsersFocusCause private
Definition at line 1953 of file SlateApplication.h.
LastAllUsersFocusWidget
TWeakPtr<SWidget> FSlateApplication::LastAllUsersFocusWidget private
Last widget that was set for 'all users' focus and the cause.
Definition at line 1952 of file SlateApplication.h.
LastMouseMoveTime
double FSlateApplication::LastMouseMoveTime private
Used when considering whether to put Slate to sleep.
Definition at line 1979 of file SlateApplication.h.
LastPlatformCursorPosition
FVector2f FSlateApplication::LastPlatformCursorPosition = FVector2f::ZeroVector private
The location of the cursor the last time OnMouseMove was called.
Definition at line 2168 of file SlateApplication.h.
LastTickTime
double FSlateApplication::LastTickTime private
Last absolute real time that we ticked.
Definition at line 2004 of file SlateApplication.h.
Referenced by GetDeltaTime().
LastUserInteractionTime
double FSlateApplication::LastUserInteractionTime private
The last real time that the user pressed a key or mouse button.
Definition at line 1970 of file SlateApplication.h.
Referenced by GetLastUserInteractionTime().
LastUserInteractionTimeForThrottling
double FSlateApplication::LastUserInteractionTimeForThrottling private
Subset of LastUserInteractionTime that is used only when considering when to throttle.
Definition at line 1973 of file SlateApplication.h.
LastUserInteractionTimeUpdateEvent
FSlateLastUserInteractionTimeUpdateEvent FSlateApplication::LastUserInteractionTimeUpdateEvent private
Delegate that gets called for LastUserInteractionTime Update.
Definition at line 1976 of file SlateApplication.h.
Referenced by GetLastUserInteractionTimeUpdateEvent().
MenuBeingDestroyedEvent
FOnMenuDestroyed FSlateApplication::MenuBeingDestroyedEvent private
Delegate for a when a menu has been dismissed.
Definition at line 2144 of file SlateApplication.h.
Referenced by OnMenuBeingDestroyed().
MenuStack
FMenuStack FSlateApplication::MenuStack private
The stack of menus that are open.
Definition at line 1935 of file SlateApplication.h.
ModalLoopTickEvent
FOnModalLoopTickEvent FSlateApplication::ModalLoopTickEvent private
Delegate for slate Tick during modal dialogs.
Definition at line 2147 of file SlateApplication.h.
Referenced by GetOnModalLoopTickEvent().
ModalWindowStackEndedDelegate
FModalWindowStackEnded FSlateApplication::ModalWindowStackEndedDelegate private
Definition at line 2053 of file SlateApplication.h.
ModalWindowStackStartedDelegate
FModalWindowStackStarted FSlateApplication::ModalWindowStackStartedDelegate private
Modal Windows.
Delegates for when modal windows open or close
Definition at line 2052 of file SlateApplication.h.
MouseButtonDownResponsivnessThrottle
FThrottleRequest FSlateApplication::MouseButtonDownResponsivnessThrottle private
Application throttling.
Holds a current request to ensure Slate is responsive in low FPS situations, based in mouse button pressed state
Definition at line 1964 of file SlateApplication.h.
NavigationConfig
TSharedRef<FNavigationConfig> FSlateApplication::NavigationConfig private
Definition at line 2117 of file SlateApplication.h.
Referenced by GetNavigationConfig().
NormalExecutionGetter
TAttribute<bool> FSlateApplication::NormalExecutionGetter private
Definition at line 2045 of file SlateApplication.h.
Referenced by GetNormalExecutionAttribute().
NumExternalModalWindowsActive
int32 FSlateApplication::NumExternalModalWindowsActive private
Allows us to track the number of non-slate modal windows active.
Definition at line 2033 of file SlateApplication.h.
OnApplicationMousePreInputButtonDownListenerEvent
FOnApplicationMousePreInputButtonDownListener FSlateApplication::OnApplicationMousePreInputButtonDownListenerEvent private
Delegate that is invoked before the mouse input button get process by slate widgets bubble system.
User Function cannot mark the input as handled.
Definition at line 2256 of file SlateApplication.h.
Referenced by OnApplicationMousePreInputButtonDownListener().
OnApplicationPreInputKeyDownListenerEvent
FOnApplicationPreInputKeyDownListener FSlateApplication::OnApplicationPreInputKeyDownListenerEvent private
Delegate that is invoked before the input key get process by slate widgets bubble system.
User Function cannot mark the input as handled.
Definition at line 2250 of file SlateApplication.h.
Referenced by OnApplicationPreInputKeyDownListener().
OnExitRequested
FSimpleDelegate FSlateApplication::OnExitRequested private
Provides a platform-agnostic method for requesting that the application exit.
Implementations should assign a handler that terminates the process when this delegate is invoked.
Definition at line 2018 of file SlateApplication.h.
OnSignalSystemDPIChangedEvent
FOnWindowDPIScaleChanged FSlateApplication::OnSignalSystemDPIChangedEvent private
Called before the dpi scale of a particular window is about to changed.
Definition at line 2261 of file SlateApplication.h.
Referenced by OnSystemSignalsDPIChanged().
OnWindowActionNotifications
TArray<FOnWindowAction> FSlateApplication::OnWindowActionNotifications private
List of delegates that need to be called when the window action occurs.
Definition at line 2036 of file SlateApplication.h.
OnWindowDPIScaleChangedEvent
FOnWindowDPIScaleChanged FSlateApplication::OnWindowDPIScaleChangedEvent private
Called when an editor window dpi scale is changed.
Definition at line 2266 of file SlateApplication.h.
Referenced by OnWindowDPIScaleChanged().
PlatformMouseMovementEvents
uint64 FSlateApplication::PlatformMouseMovementEvents = 0 private
Platform mouse movement event count.
Definition at line 2165 of file SlateApplication.h.
PopupSupport
FPopupSupport FSlateApplication::PopupSupport private
Support for auto-dismissing pop-ups.
Definition at line 1982 of file SlateApplication.h.
Referenced by GetPopupSupport().
PostTickEvent
FSlateTickEvent FSlateApplication::PostTickEvent private
Delegate for post slate Tick.
Definition at line 2132 of file SlateApplication.h.
Referenced by OnPostTick().
PreShutdownEvent
FSimpleMulticastDelegate FSlateApplication::PreShutdownEvent private
Delegate for pre shutdown.
Definition at line 2135 of file SlateApplication.h.
Referenced by OnPreShutdown().
PressedMouseButtons
TSet<FKey> FSlateApplication::PressedMouseButtons private
Definition at line 1902 of file SlateApplication.h.
PreTickEvent
FSlateTickEvent FSlateApplication::PreTickEvent private
Delegate for pre slate tick.
Definition at line 2129 of file SlateApplication.h.
Referenced by OnPreTick().
PreventDebuggingModeStack
TArray<TPair<FText, int32> > FSlateApplication::PreventDebuggingModeStack private
List of reason why we can't enter in debugging mode.
Definition at line 1992 of file SlateApplication.h.
ProcessingInput
int32 FSlateApplication::ProcessingInput private
Are we currently processing input in slate?
If so this value will be greater than 0.
Definition at line 2156 of file SlateApplication.h.
Referenced by IsProcessingInput().
QuerySourceCodeAccessDelegate
FQueryAccessSourceCode FSlateApplication::QuerySourceCodeAccessDelegate private
Delegate for querying if source code access is available.
Definition at line 2027 of file SlateApplication.h.
Referenced by SetWidgetReflectorQuerySourceAccessDelegate().
RootStyleNode
const class FStyleNode* FSlateApplication::RootStyleNode private
The top of the Style tree.
Definition at line 2039 of file SlateApplication.h.
Scale
float FSlateApplication::Scale private
Application-wide scale for supporting monitors of varying pixel density.
Definition at line 1914 of file SlateApplication.h.
Referenced by GetApplicationScale(), and SetApplicationScale().
SimulateGestures
TBitArray<FDefaultBitArrayAllocator> FSlateApplication::SimulateGestures private
The simulated gestures Slate Application will be in charge of.
Definition at line 2126 of file SlateApplication.h.
SlateSoundDevice
TSharedPtr<ISlateSoundDevice> FSlateApplication::SlateSoundDevice private
Definition at line 1998 of file SlateApplication.h.
SlateTextField
TUniquePtr<IPlatformTextField> FSlateApplication::SlateTextField private
Virtual keyboard text field.
Definition at line 2067 of file SlateApplication.h.
SlateTickCriticalSection
FCriticalSection FSlateApplication::SlateTickCriticalSection private
Critical section to avoid multiple threads calling Slate Tick when we're synchronizing between the Slate Loading Thread and the Game Thread.
Definition at line 2153 of file SlateApplication.h.
SlateVirtualWindows
TArray< TSharedRef<SWindow> > FSlateApplication::SlateVirtualWindows private
All the virtual windows, which can be anywhere - likely inside the virtual world.
Definition at line 1923 of file SlateApplication.h.
Referenced by FindPathToWidget().
SlateWindows
TArray< TSharedRef<SWindow> > FSlateApplication::SlateWindows private
All the top-level windows owned by this application; they are tracked here in a platform-agnostic way.
Definition at line 1920 of file SlateApplication.h.
Referenced by GetTopLevelWindows().
SourceCodeAccessDelegate
FAccessSourceCode FSlateApplication::SourceCodeAccessDelegate private
Delegate for accessing source code, to pass to any widget inspectors.
Definition at line 2024 of file SlateApplication.h.
Referenced by SetWidgetReflectorSourceAccessDelegate().
ThrottleHandle
FThrottleRequest FSlateApplication::ThrottleHandle private
Handle to a throttle request made to ensure the window is responsive in low FPS situations.
Definition at line 2059 of file SlateApplication.h.
UnhandledKeyDownEventHandler
FOnKeyEvent FSlateApplication::UnhandledKeyDownEventHandler private
Delegate for when a key down event occurred but was not handled in any other way by ProcessKeyDownMessage.
Definition at line 2085 of file SlateApplication.h.
UnhandledKeyUpEventHandler
FOnKeyEvent FSlateApplication::UnhandledKeyUpEventHandler private
Delegate for when a key down event occurred but was not handled in any other way by ProcessKeyDownMessage.
Definition at line 2088 of file SlateApplication.h.
UserInteractionResponsivnessThrottle
FThrottleRequest FSlateApplication::UserInteractionResponsivnessThrottle private
Separate throttle handle that engages automatically based on mouse movement and other user behavior.
Definition at line 1967 of file SlateApplication.h.
UserRegisteredEvent
FUserRegisteredEvent FSlateApplication::UserRegisteredEvent private
Delegate for when a new user has been registered.
Definition at line 2138 of file SlateApplication.h.
Referenced by OnUserRegistered().
Users
TArray<TSharedPtr<FSlateUser> > FSlateApplication::Users private
All users currently registered with Slate.
Normally there's just one, but any case where multiple users can provide input to the same application will register multiple users.
Note: The array may contain invalid entries. Users have associated indices that they expect to maintain, independent of the existence of other users.
Definition at line 1946 of file SlateApplication.h.
Referenced by GetUser(), and GetUser().
VirtualDesktopRect
FSlateRect FSlateApplication::VirtualDesktopRect private
Definition at line 2115 of file SlateApplication.h.
VirtualUsers
TArray<TWeakPtr<FSlateVirtualUserHandle> > FSlateApplication::VirtualUsers private
Weak pointers to the allocated virtual users.
Definition at line 1949 of file SlateApplication.h.
WidgetReflectorPtr
TWeakPtr<IWidgetReflector> FSlateApplication::WidgetReflectorPtr private
A Widget that introspects the current UI hierarchy.
Definition at line 2021 of file SlateApplication.h.
WindowBeingDestroyedEvent
FOnWindowBeingDestroyed FSlateApplication::WindowBeingDestroyedEvent private
Delegate for when a window is in the process of being destroyed.
Definition at line 2141 of file SlateApplication.h.
Referenced by OnWindowBeingDestroyed().
WindowDestroyQueue
TArray< TSharedRef<SWindow> > FSlateApplication::WindowDestroyQueue private
These windows will be destroyed next tick.
Definition at line 1932 of file SlateApplication.h.
The documentation for this class was generated from the following file:
SlateApplication.h