Unreal Engine 5.6 C++ API: TStringPassthru< ToType, FromType, DefaultConversionSize > Class Template Reference
TStringPassthru< ToType, FromType, DefaultConversionSize > Class Template Reference
This class is returned by StringPassthru and is not intended to be used directly.
#include "StringConv.h"
Public Member Functions
FORCEINLINE TStringPassthru (ToType *InDest, int32 InDestLen, int32 InSrcLen)
FORCEINLINE TStringPassthru (TStringPassthru &&Other)
FORCEINLINE void Apply () const
FORCEINLINE FromType * Get () UE_LIFETIMEBOUND
Private Types
typedef TInlineAllocator< DefaultConversionSize >::template ForElementType< FromType > AllocatorType
Private Member Functions
TStringPassthru (const TStringPassthru &)
TStringPassthru & operator= (const TStringPassthru &)
Private Attributes
ToType * Dest
int32 DestLen
int32 SrcLen
Detailed Description
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u>
class TStringPassthru< ToType, FromType, DefaultConversionSize >
This class is returned by StringPassthru and is not intended to be used directly.
Definition at line 1238 of file StringConv.h.
Member Typedef Documentation
AllocatorType
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> typedef TInlineAllocator<DefaultConversionSize>::template ForElementType<FromType> TStringPassthru< ToType, FromType, DefaultConversionSize >::AllocatorType private
Definition at line 1240 of file StringConv.h.
Constructor & Destructor Documentation
TStringPassthru() [1/3]
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> FORCEINLINE TStringPassthru< ToType, FromType, DefaultConversionSize >::TStringPassthru (ToType * InDest, int32 InDestLen, int32 InSrcLen) inline nodiscard
Definition at line 1243 of file StringConv.h.
References Dest, DestLen, FORCEINLINE, and SrcLen.
Referenced by TStringPassthru(), TStringPassthru(), and operator=().
TStringPassthru() [2/3]
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> FORCEINLINE TStringPassthru< ToType, FromType, DefaultConversionSize >::TStringPassthru (TStringPassthru< ToType, FromType, DefaultConversionSize > && Other) inline nodiscard
Definition at line 1251 of file StringConv.h.
References TStringPassthru(), FORCEINLINE, and Other.
TStringPassthru() [3/3]
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> TStringPassthru< ToType, FromType, DefaultConversionSize >::TStringPassthru (const TStringPassthru< ToType, FromType, DefaultConversionSize > &) private
References TStringPassthru().
Member Function Documentation
Apply()
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> FORCEINLINE void TStringPassthru< ToType, FromType, DefaultConversionSize >::Apply () const inline
Definition at line 1256 of file StringConv.h.
References check, FGenericPlatformString::Convert(), FGenericPlatformString::ConvertedLength(), Dest, DestLen, FORCEINLINE, Source, and SrcLen.
Get()
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> FORCEINLINE FromType * TStringPassthru< ToType, FromType, DefaultConversionSize >::Get () inline nodiscard
Definition at line 1263 of file StringConv.h.
References FORCEINLINE, and UE_LIFETIMEBOUND.
operator=()
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> TStringPassthru & TStringPassthru< ToType, FromType, DefaultConversionSize >::operator= (const TStringPassthru< ToType, FromType, DefaultConversionSize > &) private
References TStringPassthru().
Field Documentation
Dest
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> ToType* TStringPassthru< ToType, FromType, DefaultConversionSize >::Dest private
Definition at line 1273 of file StringConv.h.
Referenced by TStringPassthru(), and Apply().
DestLen
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> int32 TStringPassthru< ToType, FromType, DefaultConversionSize >::DestLen private
Definition at line 1274 of file StringConv.h.
Referenced by TStringPassthru(), and Apply().
SrcLen
template<typename ToType, typename FromType, int32 DefaultConversionSize = 128u> int32 TStringPassthru< ToType, FromType, DefaultConversionSize >::SrcLen private
Definition at line 1275 of file StringConv.h.
Referenced by TStringPassthru(), and Apply().
The documentation for this class was generated from the following file:
StringConv.h