Unreal Engine 5.6 C++ API: UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... > Struct Template Reference
UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... > Struct Template Reference
#include "MovieSceneMaterialSystem.h"
Public Member Functions
TAddBoundMaterialMutationImpl (TComponentTypeID< RequiredComponents >... InRequiredComponents)
virtual void CreateMutation (FEntityManager *EntityManager, FComponentMask *InOutEntityComponentTypes) const override
virtual void InitializeAllocation (FEntityAllocation *Allocation, const FComponentMask &AllocationType) const
void InitializeAllocation (FEntityAllocation *Allocation, FObjectComponent *OutBoundMaterials, const RequiredComponents *... InRequiredComponents) const
Public Member Functions inherited from UE::MovieScene::IMovieSceneEntityMutation
virtual ~IMovieSceneEntityMutation ()
virtual void InitializeUnmodifiedAllocation (FEntityAllocation *Allocation, const FComponentMask &AllocationType) const
Private Attributes
FBuiltInComponentTypes * BuiltInComponents
TTuple< TComponentTypeID< RequiredComponents >... > ComponentTypes
FMovieSceneTracksComponentTypes * TracksComponents
Detailed Description
template<typename AccessorType, typename... RequiredComponents, int... Indices>
struct UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >
Definition at line 315 of file MovieSceneMaterialSystem.h.
Constructor & Destructor Documentation
TAddBoundMaterialMutationImpl()
template<typename AccessorType, typename... RequiredComponents, int... Indices> UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::TAddBoundMaterialMutationImpl (TComponentTypeID< RequiredComponents >... InRequiredComponents) inline
Definition at line 317 of file MovieSceneMaterialSystem.h.
References BuiltInComponents, ComponentTypes, UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), and TracksComponents.
Member Function Documentation
CreateMutation()
template<typename AccessorType, typename... RequiredComponents, int... Indices> virtual void UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::CreateMutation (FEntityManager * EntityManager, FComponentMask * InOutEntityComponentTypes) const inline override virtual
Implements UE::MovieScene::IMovieSceneEntityMutation.
Definition at line 323 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::FComponentMask::Set(), and TracksComponents.
InitializeAllocation() [1/2]
template<typename AccessorType, typename... RequiredComponents, int... Indices> virtual void UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::InitializeAllocation (FEntityAllocation * Allocation, const FComponentMask & AllocationType) const inline virtual
Reimplemented from UE::MovieScene::IMovieSceneEntityMutation.
Definition at line 327 of file MovieSceneMaterialSystem.h.
References ComponentTypes, InitializeAllocation(), and TracksComponents.
Referenced by InitializeAllocation().
InitializeAllocation() [2/2]
template<typename AccessorType, typename... RequiredComponents, int... Indices> void UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::InitializeAllocation (FEntityAllocation * Allocation, FObjectComponent * OutBoundMaterials, const RequiredComponents *... InRequiredComponents) const inline
Definition at line 333 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::FObjectComponent::Null(), and Num.
Field Documentation
BuiltInComponents
template<typename AccessorType, typename... RequiredComponents, int... Indices> FBuiltInComponentTypes* UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::BuiltInComponents private
Definition at line 343 of file MovieSceneMaterialSystem.h.
Referenced by TAddBoundMaterialMutationImpl().
ComponentTypes
template<typename AccessorType, typename... RequiredComponents, int... Indices> TTuple<TComponentTypeID<RequiredComponents>...> UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::ComponentTypes private
Definition at line 346 of file MovieSceneMaterialSystem.h.
Referenced by TAddBoundMaterialMutationImpl(), and InitializeAllocation().
TracksComponents
template<typename AccessorType, typename... RequiredComponents, int... Indices> FMovieSceneTracksComponentTypes* UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::TracksComponents private
Definition at line 344 of file MovieSceneMaterialSystem.h.
Referenced by TAddBoundMaterialMutationImpl(), CreateMutation(), and InitializeAllocation().
The documentation for this struct was generated from the following file:
MovieSceneMaterialSystem.h