Unreal Engine 5.6 C++ API: Actor.h File Reference
Actor.h File Reference
#include "Stats/Stats.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectBaseUtility.h"
#include "UObject/Object.h"
#include "InputCoreTypes.h"
#include "Templates/Requires.h"
#include "Templates/SubclassOf.h"
#include "Engine/EngineTypes.h"
#include "Engine/EngineBaseTypes.h"
#include "PropertyPairsMap.h"
#include "Components/ChildActorComponent.h"
#include "RenderCommandFence.h"
#include "Net/Core/Misc/NetSubObjectRegistry.h"
#include "Engine/ReplicatedState.h"
#include <atomic>
#include "Folder.h"
#include "WorldPartition/WorldPartitionActorDescType.h"
#include "Actor.generated.h"
Data Structures
class TInlineComponentArray< T, NumElements >
TInlineComponentArray is simply a TArray that reserves a fixed amount of space on the stack to try to avoid heap allocation when there are fewer than a specified number of elements expected in the result.
struct TIsContiguousContainer< TInlineComponentArray< T, NumElements > >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Net
Responsible for creating headers allowing remote factories to spawn replicated actors.
Macros
#define ACTOR_HAS_LABELS (UE_BUILD_DEBUG || UE_BUILD_DEVELOPMENT || WITH_PROFILEGPU)
#define HIDE_ACTOR_TRANSFORM_FUNCTIONS()
Functions
DECLARE_DELEGATE_RetVal_ThreeParams (bool, FOnProcessEvent, AActor *, UFunction *, void *)
DECLARE_DELEGATE_SixParams (FMakeNoiseDelegate, AActor *, float, class APawn *, const FVector &, float, FName)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_FiveParams (FTakeAnyDamageSignature, AActor, OnTakeAnyDamage, AActor *, DamagedActor, float, Damage, const class UDamageType *, DamageType, class AController *, InstigatedBy, AActor *, DamageCauser)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_FourParams (FActorHitSignature, AActor, OnActorHit, AActor *, SelfActor, AActor *, OtherActor, FVector, NormalImpulse, const FHitResult &, Hit)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_NineParams (FTakePointDamageSignature, AActor, OnTakePointDamage, AActor *, DamagedActor, float, Damage, class AController *, InstigatedBy, FVector, HitLocation, class UPrimitiveComponent *, FHitComponent, FName, BoneName, FVector, ShotFromDirection, const class UDamageType *, DamageType, AActor *, DamageCauser)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorBeginCursorOverSignature, AActor, OnBeginCursorOver, AActor *, TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorDestroyedSignature, AActor, OnDestroyed, AActor *, DestroyedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorEndCursorOverSignature, AActor, OnEndCursorOver, AActor *, TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_SevenParams (FTakeRadialDamageSignature, AActor, OnTakeRadialDamage, AActor *, DamagedActor, float, Damage, const class UDamageType *, DamageType, FVector, Origin, const FHitResult &, HitInfo, class AController *, InstigatedBy, AActor *, DamageCauser)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorBeginOverlapSignature, AActor, OnActorBeginOverlap, AActor *, OverlappedActor, AActor *, OtherActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorBeginTouchOverSignature, AActor, OnInputTouchEnter, ETouchIndex::Type, FingerIndex, AActor *, TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorEndOverlapSignature, AActor, OnActorEndOverlap, AActor *, OverlappedActor, AActor *, OtherActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorEndPlaySignature, AActor, OnEndPlay, AActor *, Actor, EEndPlayReason::Type, EndPlayReason)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorEndTouchOverSignature, AActor, OnInputTouchLeave, ETouchIndex::Type, FingerIndex, AActor *, TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnClickedSignature, AActor, OnClicked, AActor *, TouchedActor, FKey, ButtonPressed)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnInputTouchBeginSignature, AActor, OnInputTouchBegin, ETouchIndex::Type, FingerIndex, AActor *, TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnInputTouchEndSignature, AActor, OnInputTouchEnd, ETouchIndex::Type, FingerIndex, AActor *, TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnReleasedSignature, AActor, OnReleased, AActor *, TouchedActor, FKey, ButtonReleased)
DECLARE_EVENT_TwoParams (AActor, FActorOnPackagingModeChanged, AActor *, bool)
DECLARE_LOG_CATEGORY_EXTERN (LogActor, Log, All)
UENUM() enum class EActorUpdateOverlapsMethod UENUM() enum class ESpawnActorScaleMethod UENUM() enum class ELevelInstanceType UENUM() enum class ELevelInstanceFlags ENUM_CLASS_FLAGS (ELevelInstanceFlags) struct FActorLastRenderTime
Chooses a method for actors to update overlap state (objects it is touching) on initialization, currently only used during level streaming.
UCLASS ()
Actor is the base class for an Object that can be placed or spawned in a level.
Macro Definition Documentation
ACTOR_HAS_LABELS
#define ACTOR_HAS_LABELS (UE_BUILD_DEBUG || UE_BUILD_DEVELOPMENT || WITH_PROFILEGPU)
Definition at line 65 of file Actor.h.
Referenced by FHeterogeneousVolumeData::FHeterogeneousVolumeData().
HIDE_ACTOR_TRANSFORM_FUNCTIONS
#define HIDE_ACTOR_TRANSFORM_FUNCTIONS ()
Function Documentation
DECLARE_DELEGATE_RetVal_ThreeParams()
DECLARE_DELEGATE_RetVal_ThreeParams (bool , FOnProcessEvent , AActor * , UFunction * , void *)
DECLARE_DELEGATE_SixParams()
DECLARE_DELEGATE_SixParams (FMakeNoiseDelegate , AActor * , float , class APawn * , const FVector & , float , FName)
References FVector.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_FiveParams()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_FiveParams (FTakeAnyDamageSignature , AActor , OnTakeAnyDamage , AActor * , DamagedActor , float , Damage , const class UDamageType * , DamageType , class AController * , InstigatedBy , AActor * , DamageCauser)
References Damage, DamageCauser, DamagedActor, and DamageType.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_FourParams()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_FourParams (FActorHitSignature , AActor , OnActorHit , AActor * , SelfActor , AActor * , OtherActor , FVector , NormalImpulse , const FHitResult & , Hit)
References FVector.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_NineParams()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_NineParams (FTakePointDamageSignature , AActor , OnTakePointDamage , AActor * , DamagedActor , float , Damage , class AController * , InstigatedBy , FVector , HitLocation , class UPrimitiveComponent * , FHitComponent , FName , BoneName , FVector , ShotFromDirection , const class UDamageType * , DamageType , AActor * , DamageCauser)
References Damage, DamageCauser, DamagedActor, DamageType, and FVector.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam() [1/3]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorBeginCursorOverSignature , AActor , OnBeginCursorOver , AActor * , TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam() [2/3]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorDestroyedSignature , AActor , OnDestroyed , AActor * , DestroyedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam() [3/3]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorEndCursorOverSignature , AActor , OnEndCursorOver , AActor * , TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_SevenParams()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_SevenParams (FTakeRadialDamageSignature , AActor , OnTakeRadialDamage , AActor * , DamagedActor , float , Damage , const class UDamageType * , DamageType , FVector , Origin , const FHitResult & , HitInfo , class AController * , InstigatedBy , AActor * , DamageCauser)
References Damage, DamageCauser, DamagedActor, DamageType, FVector, and Origin.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [1/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorBeginOverlapSignature , AActor , OnActorBeginOverlap , AActor * , OverlappedActor , AActor * , OtherActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [2/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorBeginTouchOverSignature , AActor , OnInputTouchEnter , ETouchIndex::Type , FingerIndex , AActor * , TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [3/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorEndOverlapSignature , AActor , OnActorEndOverlap , AActor * , OverlappedActor , AActor * , OtherActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [4/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorEndPlaySignature , AActor , OnEndPlay , AActor * , Actor , EEndPlayReason::Type , EndPlayReason)
References Actor.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [5/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorEndTouchOverSignature , AActor , OnInputTouchLeave , ETouchIndex::Type , FingerIndex , AActor * , TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [6/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnClickedSignature , AActor , OnClicked , AActor * , TouchedActor , FKey , ButtonPressed)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [7/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnInputTouchBeginSignature , AActor , OnInputTouchBegin , ETouchIndex::Type , FingerIndex , AActor * , TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [8/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnInputTouchEndSignature , AActor , OnInputTouchEnd , ETouchIndex::Type , FingerIndex , AActor * , TouchedActor)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams() [9/9]
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorOnReleasedSignature , AActor , OnReleased , AActor * , TouchedActor , FKey , ButtonReleased)
DECLARE_EVENT_TwoParams()
DECLARE_EVENT_TwoParams (AActor , FActorOnPackagingModeChanged , AActor * , bool)
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogActor , Log , All)
References All, and Log.
ENUM_CLASS_FLAGS()
UENUM() enum class EActorUpdateOverlapsMethod UENUM() enum class ESpawnActorScaleMethod UENUM() enum class ELevelInstanceType UENUM() enum class ELevelInstanceFlags ENUM_CLASS_FLAGS (ELevelInstanceFlags)
Chooses a method for actors to update overlap state (objects it is touching) on initialization, currently only used during level streaming.
Determines how the transform being passed into actor spawning methods interact with the actor's default root component Determines in what type of LevelInstance the actor is in, if any. Helper struct that allows UPrimitiveComponent and FPrimitiveSceneInfo write to the Actor's LastRenderTime member
Definition at line 115 of file Actor.h.
References Hidden, Location, None, UE_DEPRECATED, and UMETA.
UCLASS()
UCLASS ()
Actor is the base class for an Object that can be placed or spawned in a level.
Actors may contain a collection of ActorComponents, which can be used to control how actors move, how they are rendered, etc. The other main function of an Actor is the replication of properties and function calls across the network during play.
Actor initialization has multiple steps, here's the order of important virtual functions that get called:
UObject::PostLoad: For actors statically placed in a level, the normal UObject PostLoad gets called both in the editor and during gameplay. This is not called for newly spawned actors.
UActorComponent::OnComponentCreated: When an actor is spawned in the editor or during gameplay, this gets called for any native components. For blueprint-created components, this gets called during construction for that component. This is not called for components loaded from a level.
AActor::PreRegisterAllComponents: For statically placed actors and spawned actors that have native root components, this gets called now. For blueprint actors without a native root component, these registration functions get called later during construction.
UActorComponent::RegisterComponent: All components are registered in editor and at runtime, this creates their physical/visual representation. These calls may be distributed over multiple frames, but are always after PreRegisterAllComponents. This may also get called later on after an UnregisterComponent call removes it from the world.
AActor::PostRegisterAllComponents: Called for all actors both in the editor and in gameplay, this is the last function that is called in all cases.
AActor::PostActorCreated: When an actor is created in the editor or during gameplay, this gets called right before construction. This is not called for components loaded from a level.
AActor::UserConstructionScript: Called for blueprints that implement a construction script.
AActor::OnConstruction: Called at the end of ExecuteConstruction, which calls the blueprint construction script. This is called after all blueprint-created components are fully created and registered. This is only called during gameplay for spawned actors, and may get rerun in the editor when changing blueprints.
AActor::PreInitializeComponents: Called before InitializeComponent is called on the actor's components. This is only called during gameplay and in certain editor preview windows.
UActorComponent::Activate: This will be called only if the component has bAutoActivate set. It will also got called later on if a component is manually activated.
UActorComponent::InitializeComponent: This will be called only if the component has bWantsInitializeComponentSet. This only happens once per gameplay session.
AActor::PostInitializeComponents: Called after the actor's components have been initialized, only during gameplay and some editor previews.
AActor::BeginPlay: Called when the level starts ticking, only during actual gameplay. This normally happens right after PostInitializeComponents but can be delayed for networked or child actors.
See also
https://docs.unrealengine.com/Programming/UnrealArchitecture/Actors
https://docs.unrealengine.com/Programming/UnrealArchitecture/Actors/ActorLifecycle
UActorComponent
References Actor, TArray< InElementType, InAllocatorType >::Add(), Ar, BaseColor, Blueprintable, BlueprintType, Cast(), CastChecked(), Category, check, Class, Component, config, Damage, DamageCauser, DamageType, DeltaTime, Destroyed, End, Engine, EnumHasAnyFlags(), Event, Flags, FlushNetDormancy, ForceInit, FORCEINLINE, UE::Math::TVector< double >::ForwardVector, Frequency, Function, FVector, GENERATED_BODY, GET_MEMBER_NAME_CHECKED, GIsDemoMode, GIsEditor, UE::Math::TTransform< double >::Identity, Info, InName, Input, Interface, UStruct::IsChildOf(), FGuid::IsValid(), IsValidChecked(), Key, Keywords, EKeys::LeftMouseButton, meta, MinimalAPI, ObjectPtrDecay(), Origin, Other, Owner, PackageName, Params, Parent, Pawn, Physics, PivotOffset, Point, PostLoad, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, PreSave, RemoteRole, REN_None, Rename, ReplicatedActor, Reset, TArray< InElementType, InAllocatorType >::Reset(), UE::Math::TVector< double >::RightVector, Role, Seconds, ShortTooltip, Source, Tags, TearOff, TemplateName, TEXT, Time, ToRawPtr(), TransactionAnnotation, Transform, Transient, UE_DEPRECATED, UFUNCTION, UPARAM, UPROPERTY, UE::Math::TVector< double >::UpVector, UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value, FColor::White, UE::Math::TRotator< double >::ZeroRotator, and UE::Math::TVector< double >::ZeroVector.