Unreal Engine 5.6 C++ API: RigVMTypeUtils Namespace Reference
RigVMTypeUtils Namespace Reference
Data Structures
class TypeIndex
Enumerations
enum class EClassArgType { AsClass , AsObject }
Functions
RIGVMDEVELOPER_API bool AreCompatible (const FEdGraphPinType &InTypeA, const FEdGraphPinType &InTypeB, const FString &InSegmentPathA=FString(), const FString &InSegmentPathB=FString())
RIGVMDEVELOPER_API bool AreCompatible (const FName &InCPPTypeA, UObject *InCPPTypeObjectA, const FName &InCPPTypeB, UObject *InCPPTypeObjectB)
static bool AreCompatible (const FProperty *InSourceProperty, const FProperty *InTargetProperty)
RIGVMDEVELOPER_API bool AreCompatible (const FRigVMExternalVariable &InTypeA, const FRigVMExternalVariable &InTypeB, const FString &InSegmentPathA=FString(), const FString &InSegmentPathB=FString())
FString ArrayTypeFromBaseType (const FString &InCPPType)
FString BaseTypeFromArrayType (const FString &InCPPType)
const FLazyName BoolArrayTypeName (BoolArrayType)
const FLazyName BoolTypeName (BoolType)
RIGVMDEVELOPER_API bool CanCastTypes (const TRigVMTypeIndex &InSourceTypeIndex, const TRigVMTypeIndex &InTargetTypeIndex)
FString CPPTypeFromEnum (const UEnum *InEnum)
RIGVMDEVELOPER_API bool CPPTypeFromExternalVariable (const FRigVMExternalVariable &InExternalVariable, FString &OutCPPType, UObject **OutCPPTypeObject)
static FString CPPTypeFromObject (const UObject *InCPPTypeObject, EClassArgType InClassArgType=EClassArgType::AsObject)
RIGVMDEVELOPER_API bool CPPTypeFromPin (URigVMPin *InPin, FString &OutCPPType, FName &OutCPPTypeObjectPath, bool bGetBaseCPPType=false)
RIGVMDEVELOPER_API bool CPPTypeFromPin (URigVMPin *InPin, FString &OutCPPType, FString &OutCPPTypeObjectPath, bool bGetBaseCPPType=false)
RIGVMDEVELOPER_API bool CPPTypeFromPin (URigVMPin *InPin, FString &OutCPPType, UObject **OutCPPTypeObject, bool bGetBaseCPPType=false)
RIGVMDEVELOPER_API bool CPPTypeFromPinType (const FEdGraphPinType &InPinType, FString &OutCPPType, FName &OutCPPTypeObjectPath)
RIGVMDEVELOPER_API bool CPPTypeFromPinType (const FEdGraphPinType &InPinType, FString &OutCPPType, FString &OutCPPTypeObjectPath)
RIGVMDEVELOPER_API bool CPPTypeFromPinType (const FEdGraphPinType &InPinType, FString &OutCPPType, UObject **OutCPPTypeObject)
const FLazyName DoubleArrayTypeName (DoubleArrayType)
const FLazyName DoubleTypeName (DoubleType)
RIGVM_API FRigVMExternalVariable ExternalVariableFromBPVariableDescription (const FBPVariableDescription &InVariableDescription)
RIGVM_API FRigVMExternalVariable ExternalVariableFromBPVariableDescription (const FBPVariableDescription &InVariableDescription, void *Container)
RIGVM_API FRigVMExternalVariable ExternalVariableFromCPPType (const FName &InName, const FString &InCPPType, UObject *InCPPTypeObject, bool bInPublic=false, bool bInReadonly=false)
RIGVM_API FRigVMExternalVariable ExternalVariableFromCPPTypePath (const FName &InName, const FString &InCPPTypePath, bool bInPublic=false, bool bInReadonly=false)
RIGVM_API FRigVMExternalVariable ExternalVariableFromPinType (const FName &InName, const FEdGraphPinType &InPinType, bool bInPublic=false, bool bInReadonly=false)
RIGVMDEVELOPER_API FRigVMExternalVariable ExternalVariableFromRigVMVariableDescription (const FRigVMGraphVariableDescription &InVariableDescription)
static UObject * FindObjectFromCPPTypeObjectPath (const FString &InObjectPath)
template<class T>
static T * FindObjectFromCPPTypeObjectPath (const FString &InObjectPath)
static UObject * FindObjectGlobally (const TCHAR *InObjectName, bool bUseRedirector)
static bool FixCPPTypeAndObject (FString &InOutCPPType, TObjectPtr< UObject > &InOutCPPTypeObject, const FRigVMUserDefinedTypeResolver *InResolvalInfo=nullptr)
const FLazyName FloatArrayTypeName (FloatArrayType)
const FLazyName FloatTypeName (FloatType)
const FLazyName FNameArrayTypeName (FNameArrayType)
const FLazyName FNameTypeName (FNameType)
const FLazyName FStringArrayTypeName (FStringArrayType)
const FLazyName FStringTypeName (FStringType)
const FLazyName FTextTypeName (FTextType)
RIGVMDEVELOPER_API const TArray< TRigVMTypeIndex > & GetAvailableCasts (const TRigVMTypeIndex &InTypeIndex, bool bAsInput)
RIGVMDEVELOPER_API const FRigVMFunction * GetCastForTypeIndices (const TRigVMTypeIndex &InSourceTypeIndex, const TRigVMTypeIndex &InTargetTypeIndex)
RIGVMDEVELOPER_API const FLazyName & GetCastTemplateNotation ()
RIGVMDEVELOPER_API const FLazyName & GetCastTemplateResultName ()
RIGVMDEVELOPER_API const FLazyName & GetCastTemplateValueName ()
RIGVMDEVELOPER_API FText GetDisplayTextForArgumentType (const FRigVMTemplateArgumentType &InType)
RIGVM_API TArray< FRigVMExternalVariableDef > GetExternalVariableDefs (const TArray< FRigVMExternalVariable > &ExternalVariables)
FString GetUniqueStructTypeName (const FGuid &InStructGuid)
FString GetUniqueStructTypeName (const UScriptStruct *InScriptStruct)
static const FString & GetWildCardArrayCPPType ()
static const FLazyName & GetWildCardArrayCPPTypeName ()
static const FString & GetWildCardCPPType ()
static const FLazyName & GetWildCardCPPTypeName ()
static UScriptStruct * GetWildCardCPPTypeObject ()
const FLazyName Int32ArrayTypeName (Int32ArrayType)
const FLazyName Int32TypeName (Int32Type)
const FLazyName Int64TypeName (Int64Type)
const FLazyName IntTypeName (IntType)
bool IsArrayType (const FString &InCPPType)
bool IsInterfaceType (const FString &InCPPType)
bool IsUClassType (const FString &InCPPType)
bool IsUObjectType (const FString &InCPPType)
static UObject * ObjectFromCPPType (FString &InOutCPPType, bool bUseRedirector=true, const FRigVMUserDefinedTypeResolver *InTypeResolver=nullptr)
RIGVMDEVELOPER_API FEdGraphPinType PinTypeFromCPPType (const FName &InCPPType, UObject *InCPPTypeObject)
RIGVMDEVELOPER_API FEdGraphPinType PinTypeFromExternalVariable (const FRigVMExternalVariable &InExternalVariable)
RIGVMDEVELOPER_API FEdGraphPinType PinTypeFromRigVMVariableDescription (const FRigVMGraphVariableDescription &InVariableDescription)
RIGVMDEVELOPER_API FEdGraphPinType PinTypeFromTypeIndex (const TRigVMTypeIndex &InTypeIndex)
static FString PostProcessCPPType (const FString &InCPPType, UObject *InCPPTypeObject=nullptr, const FRigVMUserDefinedTypeResolver *InResolvalInfo=nullptr)
static bool RequiresCPPTypeObject (const FString &InCPPType)
RIGVMDEVELOPER_API FEdGraphPinType SubPinType (const FEdGraphPinType &InPinType, const FString &SegmentPath)
RIGVMDEVELOPER_API TRigVMTypeIndex TypeIndexFromPinType (const FEdGraphPinType &InPinType)
const FLazyName UInt32ArrayTypeName (UInt32ArrayType)
const FLazyName UInt32TypeName (UInt32Type)
const FLazyName UInt64TypeName (UInt64Type)
const FLazyName UInt8ArrayTypeName (UInt8ArrayType)
const FLazyName UInt8TypeName (UInt8Type)
RIGVM_API UObject * UserDefinedTypeFromCPPType (FString &InOutCPPType, const FRigVMUserDefinedTypeResolver *InTypeResolver=nullptr)
Variables
const TCHAR * BoolArrayType = TEXT("TArray<bool>")
const TCHAR * BoolType = TEXT("bool")
const TCHAR * DoubleArrayType = TEXT("TArray<double>")
const TCHAR * DoubleType = TEXT("double")
const TCHAR * FloatArrayType = TEXT("TArray<float>")
const TCHAR * FloatType = TEXT("float")
const TCHAR * FNameArrayType = TEXT("TArray<FName>")
const TCHAR * FNameType = TEXT("FName")
const TCHAR * FStringArrayType = TEXT("TArray<FString>")
const TCHAR * FStringType = TEXT("FString")
const TCHAR * FTextArrayType = TEXT("TArray<FText>")
const TCHAR * FTextType = TEXT("FText")
const TCHAR * Int32ArrayType = TEXT("TArray<int32>")
const TCHAR * Int32Type = TEXT("int32")
const TCHAR * Int64Type = TEXT("int64")
const TCHAR * IntType = TEXT("int")
constexpr TCHAR TArrayPrefix [] = TEXT("TArray<")
constexpr TCHAR TArrayTemplate [] = TEXT("TArray<%s>")
constexpr TCHAR TObjectPtrPrefix [] = TEXT("TObjectPtr<")
constexpr TCHAR TObjectPtrTemplate [] = TEXT("TObjectPtr<%s%s>")
constexpr TCHAR TScriptInterfacePrefix [] = TEXT("TScriptInterface<")
constexpr TCHAR TScriptInterfaceTemplate [] = TEXT("TScriptInterface<%s%s>")
constexpr TCHAR TSubclassOfPrefix [] = TEXT("TSubclassOf<")
constexpr TCHAR TSubclassOfTemplate [] = TEXT("TSubclassOf<%s%s>")
const TCHAR * UInt32ArrayType = TEXT("TArray<uint32>")
const TCHAR * UInt32Type = TEXT("uint32")
const TCHAR * UInt64Type = TEXT("uint64")
const TCHAR * UInt8ArrayType = TEXT("TArray<uint8>")
const TCHAR * UInt8Type = TEXT("uint8")
Enumeration Type Documentation
EClassArgType
enum class RigVMTypeUtils::EClassArgType strong
Enumerator
AsClass
AsObject
Definition at line 337 of file RigVMTypeUtils.h.
Function Documentation
AreCompatible() [1/4]
RIGVMDEVELOPER_API bool RigVMTypeUtils::AreCompatible (const FEdGraphPinType & InTypeA, const FEdGraphPinType & InTypeB, const FString & InSegmentPathA = FString(), const FString & InSegmentPathB = FString())
AreCompatible() [2/4]
RIGVMDEVELOPER_API bool RigVMTypeUtils::AreCompatible (const FName & InCPPTypeA, UObject * InCPPTypeObjectA, const FName & InCPPTypeB, UObject * InCPPTypeObjectB)
AreCompatible() [3/4]
bool RigVMTypeUtils::AreCompatible (const FProperty * InSourceProperty, const FProperty * InTargetProperty) static
Definition at line 547 of file RigVMTypeUtils.h.
References CastField(), FField::IsA(), and FProperty::SameType().
AreCompatible() [4/4]
RIGVMDEVELOPER_API bool RigVMTypeUtils::AreCompatible (const FRigVMExternalVariable & InTypeA, const FRigVMExternalVariable & InTypeB, const FString & InSegmentPathA = FString(), const FString & InSegmentPathB = FString())
References FRigVMExternalVariable.
ArrayTypeFromBaseType()
FString RigVMTypeUtils::ArrayTypeFromBaseType (const FString & InCPPType) inline
Definition at line 135 of file RigVMTypeUtils.h.
References RigVMStringUtils::JoinStrings(), TArrayPrefix, and TEXT.
Referenced by GetWildCardArrayCPPType(), PostProcessCPPType(), USTRUCT(), and USTRUCT().
BaseTypeFromArrayType()
FString RigVMTypeUtils::BaseTypeFromArrayType (const FString & InCPPType) inline
Definition at line 140 of file RigVMTypeUtils.h.
Referenced by ObjectFromCPPType(), PostProcessCPPType(), and USTRUCT().
BoolArrayTypeName()
const FLazyName RigVMTypeUtils::BoolArrayTypeName (BoolArrayType)
References BoolArrayType.
BoolTypeName()
const FLazyName RigVMTypeUtils::BoolTypeName (BoolType)
References BoolType.
CanCastTypes()
RIGVMDEVELOPER_API bool RigVMTypeUtils::CanCastTypes (const TRigVMTypeIndex & InSourceTypeIndex, const TRigVMTypeIndex & InTargetTypeIndex)
CPPTypeFromEnum()
FString RigVMTypeUtils::CPPTypeFromEnum (const UEnum * InEnum) inline
Definition at line 161 of file RigVMTypeUtils.h.
References GetTypeHash(), and TEXT.
Referenced by CPPTypeFromObject(), and USTRUCT().
CPPTypeFromExternalVariable()
RIGVMDEVELOPER_API bool RigVMTypeUtils::CPPTypeFromExternalVariable (const FRigVMExternalVariable & InExternalVariable, FString & OutCPPType, UObject ** OutCPPTypeObject)
References FRigVMExternalVariable.
CPPTypeFromObject()
FString RigVMTypeUtils::CPPTypeFromObject (const UObject * InCPPTypeObject, EClassArgType InClassArgType = EClassArgType::AsObject) static
Definition at line 346 of file RigVMTypeUtils.h.
References AsClass, AsObject, Cast(), Class, CPPTypeFromEnum(), Enum, GetUniqueStructTypeName(), ScriptStruct, TEXT, TObjectPtrTemplate, TScriptInterfaceTemplate, and TSubclassOfTemplate.
Referenced by ObjectFromCPPType(), PostProcessCPPType(), and USTRUCT().
CPPTypeFromPin() [1/3]
RIGVMDEVELOPER_API bool RigVMTypeUtils::CPPTypeFromPin (URigVMPin * InPin, FString & OutCPPType, FName & OutCPPTypeObjectPath, bool bGetBaseCPPType = false)
CPPTypeFromPin() [2/3]
RIGVMDEVELOPER_API bool RigVMTypeUtils::CPPTypeFromPin (URigVMPin * InPin, FString & OutCPPType, FString & OutCPPTypeObjectPath, bool bGetBaseCPPType = false)
CPPTypeFromPin() [3/3]
RIGVMDEVELOPER_API bool RigVMTypeUtils::CPPTypeFromPin (URigVMPin * InPin, FString & OutCPPType, UObject ** OutCPPTypeObject, bool bGetBaseCPPType = false)
CPPTypeFromPinType() [1/3]
RIGVMDEVELOPER_API bool RigVMTypeUtils::CPPTypeFromPinType (const FEdGraphPinType & InPinType, FString & OutCPPType, FName & OutCPPTypeObjectPath)
CPPTypeFromPinType() [2/3]
RIGVMDEVELOPER_API bool RigVMTypeUtils::CPPTypeFromPinType (const FEdGraphPinType & InPinType, FString & OutCPPType, FString & OutCPPTypeObjectPath)
CPPTypeFromPinType() [3/3]
RIGVMDEVELOPER_API bool RigVMTypeUtils::CPPTypeFromPinType (const FEdGraphPinType & InPinType, FString & OutCPPType, UObject ** OutCPPTypeObject)
Referenced by USTRUCT().
DoubleArrayTypeName()
const FLazyName RigVMTypeUtils::DoubleArrayTypeName (DoubleArrayType)
References DoubleArrayType.
DoubleTypeName()
const FLazyName RigVMTypeUtils::DoubleTypeName (DoubleType)
References DoubleType.
ExternalVariableFromBPVariableDescription() [1/2]
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromBPVariableDescription (const FBPVariableDescription & InVariableDescription)
References FRigVMExternalVariable.
ExternalVariableFromBPVariableDescription() [2/2]
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromBPVariableDescription (const FBPVariableDescription & InVariableDescription, void * Container)
References Container, and FRigVMExternalVariable.
ExternalVariableFromCPPType()
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromCPPType (const FName & InName, const FString & InCPPType, UObject * InCPPTypeObject, bool bInPublic = false, bool bInReadonly = false)
References FRigVMExternalVariable, and InName.
ExternalVariableFromCPPTypePath()
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromCPPTypePath (const FName & InName, const FString & InCPPTypePath, bool bInPublic = false, bool bInReadonly = false)
References FRigVMExternalVariable, and InName.
ExternalVariableFromPinType()
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromPinType (const FName & InName, const FEdGraphPinType & InPinType, bool bInPublic = false, bool bInReadonly = false)
References FRigVMExternalVariable, and InName.
ExternalVariableFromRigVMVariableDescription()
RIGVMDEVELOPER_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromRigVMVariableDescription (const FRigVMGraphVariableDescription & InVariableDescription)
References FRigVMExternalVariable.
Referenced by USTRUCT().
FindObjectFromCPPTypeObjectPath() [1/2]
UObject * RigVMTypeUtils::FindObjectFromCPPTypeObjectPath (const FString & InObjectPath) static
Definition at line 497 of file RigVMTypeUtils.h.
References EnsureIfAmbiguous, FindObjectFromCPPTypeObjectPath(), FindPackage(), FName, FCoreRedirects::GetRedirectedName(), NativeFirst, Package, PackageName, TEXT, FCoreRedirectObjectName::ToString(), ToString(), and Type_Struct.
Referenced by FindObjectFromCPPTypeObjectPath().
FindObjectFromCPPTypeObjectPath() [2/2]
template<class T> T * RigVMTypeUtils::FindObjectFromCPPTypeObjectPath (const FString & InObjectPath) static
Definition at line 542 of file RigVMTypeUtils.h.
References Cast(), and FindObjectFromCPPTypeObjectPath().
FindObjectGlobally()
UObject * RigVMTypeUtils::FindObjectGlobally (const TCHAR * InObjectName, bool bUseRedirector) static
Definition at line 272 of file RigVMTypeUtils.h.
References AllowPartialMatch, FindPackage(), FName::IsNone(), Left, NativeFirst, Object, FCoreRedirectObjectName::ObjectName, Package, FCoreRedirectObjectName::PackageName, FCoreRedirects::RedirectNameAndValues(), Right, TEXT, FName::ToString(), Type_Class, Type_Enum, and Type_Struct.
Referenced by ObjectFromCPPType().
FixCPPTypeAndObject()
bool RigVMTypeUtils::FixCPPTypeAndObject (FString & InOutCPPType, TObjectPtr< UObject > & InOutCPPTypeObject, const FRigVMUserDefinedTypeResolver * InResolvalInfo = nullptr) static
Definition at line 470 of file RigVMTypeUtils.h.
References Cast(), Enum, ObjectFromCPPType(), and PostProcessCPPType().
FloatArrayTypeName()
const FLazyName RigVMTypeUtils::FloatArrayTypeName (FloatArrayType)
References FloatArrayType.
FloatTypeName()
const FLazyName RigVMTypeUtils::FloatTypeName (FloatType)
References FloatType.
FNameArrayTypeName()
const FLazyName RigVMTypeUtils::FNameArrayTypeName (FNameArrayType)
References FNameArrayType.
FNameTypeName()
const FLazyName RigVMTypeUtils::FNameTypeName (FNameType)
References FNameType.
FStringArrayTypeName()
const FLazyName RigVMTypeUtils::FStringArrayTypeName (FStringArrayType)
References FStringArrayType.
FStringTypeName()
const FLazyName RigVMTypeUtils::FStringTypeName (FStringType)
References FStringType.
FTextTypeName()
const FLazyName RigVMTypeUtils::FTextTypeName (FTextType)
References FTextType.
GetAvailableCasts()
RIGVMDEVELOPER_API const TArray< TRigVMTypeIndex > & RigVMTypeUtils::GetAvailableCasts (const TRigVMTypeIndex & InTypeIndex, bool bAsInput)
GetCastForTypeIndices()
RIGVMDEVELOPER_API const FRigVMFunction * RigVMTypeUtils::GetCastForTypeIndices (const TRigVMTypeIndex & InSourceTypeIndex, const TRigVMTypeIndex & InTargetTypeIndex)
GetCastTemplateNotation()
RIGVMDEVELOPER_API const FLazyName & RigVMTypeUtils::GetCastTemplateNotation ()
GetCastTemplateResultName()
RIGVMDEVELOPER_API const FLazyName & RigVMTypeUtils::GetCastTemplateResultName ()
GetCastTemplateValueName()
RIGVMDEVELOPER_API const FLazyName & RigVMTypeUtils::GetCastTemplateValueName ()
GetDisplayTextForArgumentType()
RIGVMDEVELOPER_API FText RigVMTypeUtils::GetDisplayTextForArgumentType (const FRigVMTemplateArgumentType & InType)
GetExternalVariableDefs()
RIGVM_API TArray< FRigVMExternalVariableDef > RigVMTypeUtils::GetExternalVariableDefs (const TArray< FRigVMExternalVariable > & ExternalVariables)
GetUniqueStructTypeName() [1/2]
FString RigVMTypeUtils::GetUniqueStructTypeName (const FGuid & InStructGuid) inline
Definition at line 145 of file RigVMTypeUtils.h.
References TEXT, and FGuid::ToString().
Referenced by CPPTypeFromObject(), GetUniqueStructTypeName(), GetWildCardCPPType(), and USTRUCT().
GetUniqueStructTypeName() [2/2]
FString RigVMTypeUtils::GetUniqueStructTypeName (const UScriptStruct * InScriptStruct) inline
Definition at line 151 of file RigVMTypeUtils.h.
References Cast(), UScriptStruct::GetStructCPPName(), and GetUniqueStructTypeName().
GetWildCardArrayCPPType()
const FString & RigVMTypeUtils::GetWildCardArrayCPPType () static
Definition at line 204 of file RigVMTypeUtils.h.
References ArrayTypeFromBaseType(), and GetWildCardCPPType().
Referenced by GetWildCardArrayCPPTypeName().
GetWildCardArrayCPPTypeName()
const FLazyName & RigVMTypeUtils::GetWildCardArrayCPPTypeName () static
Definition at line 210 of file RigVMTypeUtils.h.
References GetWildCardArrayCPPType().
Referenced by USTRUCT().
GetWildCardCPPType()
const FString & RigVMTypeUtils::GetWildCardCPPType () static
Definition at line 192 of file RigVMTypeUtils.h.
References GetUniqueStructTypeName().
Referenced by GetWildCardArrayCPPType(), and GetWildCardCPPTypeName().
GetWildCardCPPTypeName()
const FLazyName & RigVMTypeUtils::GetWildCardCPPTypeName () static
Definition at line 198 of file RigVMTypeUtils.h.
References GetWildCardCPPType().
Referenced by USTRUCT().
GetWildCardCPPTypeObject()
UScriptStruct * RigVMTypeUtils::GetWildCardCPPTypeObject () static
Definition at line 186 of file RigVMTypeUtils.h.
Referenced by USTRUCT().
Int32ArrayTypeName()
const FLazyName RigVMTypeUtils::Int32ArrayTypeName (Int32ArrayType)
References Int32ArrayType.
Int32TypeName()
const FLazyName RigVMTypeUtils::Int32TypeName (Int32Type)
References Int32Type.
Int64TypeName()
const FLazyName RigVMTypeUtils::Int64TypeName (Int64Type)
References Int64Type.
IntTypeName()
const FLazyName RigVMTypeUtils::IntTypeName (IntType)
References IntType.
IsArrayType()
bool RigVMTypeUtils::IsArrayType (const FString & InCPPType) inline
Definition at line 130 of file RigVMTypeUtils.h.
References TArrayPrefix.
Referenced by ObjectFromCPPType(), PostProcessCPPType(), USTRUCT(), and USTRUCT().
IsInterfaceType()
bool RigVMTypeUtils::IsInterfaceType (const FString & InCPPType) inline
Definition at line 181 of file RigVMTypeUtils.h.
References TScriptInterfacePrefix.
IsUClassType()
bool RigVMTypeUtils::IsUClassType (const FString & InCPPType) inline
Definition at line 171 of file RigVMTypeUtils.h.
References TSubclassOfPrefix.
IsUObjectType()
bool RigVMTypeUtils::IsUObjectType (const FString & InCPPType) inline
Definition at line 176 of file RigVMTypeUtils.h.
References TObjectPtrPrefix.
ObjectFromCPPType()
UObject * RigVMTypeUtils::ObjectFromCPPType (FString & InOutCPPType, bool bUseRedirector = true, const FRigVMUserDefinedTypeResolver * InTypeResolver = nullptr) static
Definition at line 379 of file RigVMTypeUtils.h.
References AsClass, AsObject, BaseTypeFromArrayType(), CPPTypeFromObject(), FindObjectGlobally(), IsArrayType(), RequiresCPPTypeObject(), TEXT, TObjectPtrPrefix, TScriptInterfacePrefix, TSubclassOfPrefix, and UserDefinedTypeFromCPPType().
Referenced by FixCPPTypeAndObject(), and PostProcessCPPType().
PinTypeFromCPPType()
RIGVMDEVELOPER_API FEdGraphPinType RigVMTypeUtils::PinTypeFromCPPType (const FName & InCPPType, UObject * InCPPTypeObject)
PinTypeFromExternalVariable()
RIGVMDEVELOPER_API FEdGraphPinType RigVMTypeUtils::PinTypeFromExternalVariable (const FRigVMExternalVariable & InExternalVariable)
References FRigVMExternalVariable.
PinTypeFromRigVMVariableDescription()
RIGVMDEVELOPER_API FEdGraphPinType RigVMTypeUtils::PinTypeFromRigVMVariableDescription (const FRigVMGraphVariableDescription & InVariableDescription)
Referenced by USTRUCT().
PinTypeFromTypeIndex()
RIGVMDEVELOPER_API FEdGraphPinType RigVMTypeUtils::PinTypeFromTypeIndex (const TRigVMTypeIndex & InTypeIndex)
PostProcessCPPType()
FString RigVMTypeUtils::PostProcessCPPType (const FString & InCPPType, UObject * InCPPTypeObject = nullptr, const FRigVMUserDefinedTypeResolver * InResolvalInfo = nullptr) static
Definition at line 444 of file RigVMTypeUtils.h.
References ArrayTypeFromBaseType(), AsClass, AsObject, BaseTypeFromArrayType(), CPPTypeFromObject(), IsArrayType(), ObjectFromCPPType(), RequiresCPPTypeObject(), and TSubclassOfPrefix.
Referenced by FixCPPTypeAndObject().
RequiresCPPTypeObject()
bool RigVMTypeUtils::RequiresCPPTypeObject (const FString & InCPPType) static
Definition at line 216 of file RigVMTypeUtils.h.
References ESearchCase::CaseSensitive, TArray< InElementType, InAllocatorType >::Contains(), and TEXT.
Referenced by ObjectFromCPPType(), and PostProcessCPPType().
SubPinType()
RIGVMDEVELOPER_API FEdGraphPinType RigVMTypeUtils::SubPinType (const FEdGraphPinType & InPinType, const FString & SegmentPath)
TypeIndexFromPinType()
RIGVMDEVELOPER_API TRigVMTypeIndex RigVMTypeUtils::TypeIndexFromPinType (const FEdGraphPinType & InPinType)
UInt32ArrayTypeName()
const FLazyName RigVMTypeUtils::UInt32ArrayTypeName (UInt32ArrayType)
References UInt32ArrayType.
UInt32TypeName()
const FLazyName RigVMTypeUtils::UInt32TypeName (UInt32Type)
References UInt32Type.
UInt64TypeName()
const FLazyName RigVMTypeUtils::UInt64TypeName (UInt64Type)
References UInt64Type.
UInt8ArrayTypeName()
const FLazyName RigVMTypeUtils::UInt8ArrayTypeName (UInt8ArrayType)
References UInt8ArrayType.
UInt8TypeName()
const FLazyName RigVMTypeUtils::UInt8TypeName (UInt8Type)
References UInt8Type.
UserDefinedTypeFromCPPType()
RIGVM_API UObject * RigVMTypeUtils::UserDefinedTypeFromCPPType (FString & InOutCPPType, const FRigVMUserDefinedTypeResolver * InTypeResolver = nullptr)
Referenced by ObjectFromCPPType().
Variable Documentation
BoolArrayType
const TCHAR* RigVMTypeUtils::BoolArrayType = TEXT("TArray<bool>") inline
Definition at line 73 of file RigVMTypeUtils.h.
Referenced by BoolArrayTypeName().
BoolType
const TCHAR* RigVMTypeUtils::BoolType = TEXT("bool") inline
Definition at line 61 of file RigVMTypeUtils.h.
Referenced by BoolTypeName().
DoubleArrayType
const TCHAR* RigVMTypeUtils::DoubleArrayType = TEXT("TArray<double>") inline
Definition at line 75 of file RigVMTypeUtils.h.
Referenced by DoubleArrayTypeName().
DoubleType
const TCHAR* RigVMTypeUtils::DoubleType = TEXT("double") inline
Definition at line 63 of file RigVMTypeUtils.h.
Referenced by DoubleTypeName().
FloatArrayType
const TCHAR* RigVMTypeUtils::FloatArrayType = TEXT("TArray<float>") inline
Definition at line 74 of file RigVMTypeUtils.h.
Referenced by FloatArrayTypeName().
FloatType
const TCHAR* RigVMTypeUtils::FloatType = TEXT("float") inline
Definition at line 62 of file RigVMTypeUtils.h.
Referenced by FloatTypeName().
FNameArrayType
const TCHAR* RigVMTypeUtils::FNameArrayType = TEXT("TArray<FName>") inline
Definition at line 79 of file RigVMTypeUtils.h.
Referenced by FNameArrayTypeName().
FNameType
const TCHAR* RigVMTypeUtils::FNameType = TEXT("FName") inline
Definition at line 70 of file RigVMTypeUtils.h.
Referenced by FNameTypeName().
FStringArrayType
const TCHAR* RigVMTypeUtils::FStringArrayType = TEXT("TArray<FString>") inline
Definition at line 80 of file RigVMTypeUtils.h.
Referenced by FStringArrayTypeName().
FStringType
const TCHAR* RigVMTypeUtils::FStringType = TEXT("FString") inline
Definition at line 71 of file RigVMTypeUtils.h.
Referenced by FStringTypeName().
FTextArrayType
const TCHAR* RigVMTypeUtils::FTextArrayType = TEXT("TArray<FText>") inline
Definition at line 81 of file RigVMTypeUtils.h.
FTextType
const TCHAR* RigVMTypeUtils::FTextType = TEXT("FText") inline
Definition at line 72 of file RigVMTypeUtils.h.
Referenced by FTextTypeName().
Int32ArrayType
const TCHAR* RigVMTypeUtils::Int32ArrayType = TEXT("TArray<int32>") inline
Definition at line 76 of file RigVMTypeUtils.h.
Referenced by Int32ArrayTypeName().
Int32Type
const TCHAR* RigVMTypeUtils::Int32Type = TEXT("int32") inline
Definition at line 65 of file RigVMTypeUtils.h.
Referenced by Int32TypeName().
Int64Type
const TCHAR* RigVMTypeUtils::Int64Type = TEXT("int64") inline
Definition at line 66 of file RigVMTypeUtils.h.
Referenced by Int64TypeName().
IntType
const TCHAR* RigVMTypeUtils::IntType = TEXT("int") inline
Definition at line 64 of file RigVMTypeUtils.h.
Referenced by IntTypeName().
TArrayPrefix
TCHAR RigVMTypeUtils::TArrayPrefix[] = TEXT("TArray<") constexpr
Definition at line 52 of file RigVMTypeUtils.h.
Referenced by ArrayTypeFromBaseType(), and IsArrayType().
TArrayTemplate
TCHAR RigVMTypeUtils::TArrayTemplate[] = TEXT("TArray<%s>") constexpr
Definition at line 56 of file RigVMTypeUtils.h.
TObjectPtrPrefix
TCHAR RigVMTypeUtils::TObjectPtrPrefix[] = TEXT("TObjectPtr<") constexpr
Definition at line 53 of file RigVMTypeUtils.h.
Referenced by IsUObjectType(), and ObjectFromCPPType().
TObjectPtrTemplate
TCHAR RigVMTypeUtils::TObjectPtrTemplate[] = TEXT("TObjectPtr<%s%s>") constexpr
Definition at line 57 of file RigVMTypeUtils.h.
Referenced by CPPTypeFromObject().
TScriptInterfacePrefix
TCHAR RigVMTypeUtils::TScriptInterfacePrefix[] = TEXT("TScriptInterface<") constexpr
Definition at line 55 of file RigVMTypeUtils.h.
Referenced by IsInterfaceType(), and ObjectFromCPPType().
TScriptInterfaceTemplate
TCHAR RigVMTypeUtils::TScriptInterfaceTemplate[] = TEXT("TScriptInterface<%s%s>") constexpr
Definition at line 59 of file RigVMTypeUtils.h.
Referenced by CPPTypeFromObject().
TSubclassOfPrefix
TCHAR RigVMTypeUtils::TSubclassOfPrefix[] = TEXT("TSubclassOf<") constexpr
Definition at line 54 of file RigVMTypeUtils.h.
Referenced by IsUClassType(), ObjectFromCPPType(), and PostProcessCPPType().
TSubclassOfTemplate
TCHAR RigVMTypeUtils::TSubclassOfTemplate[] = TEXT("TSubclassOf<%s%s>") constexpr
Definition at line 58 of file RigVMTypeUtils.h.
Referenced by CPPTypeFromObject().
UInt32ArrayType
const TCHAR* RigVMTypeUtils::UInt32ArrayType = TEXT("TArray<uint32>") inline
Definition at line 77 of file RigVMTypeUtils.h.
Referenced by UInt32ArrayTypeName().
UInt32Type
const TCHAR* RigVMTypeUtils::UInt32Type = TEXT("uint32") inline
Definition at line 68 of file RigVMTypeUtils.h.
Referenced by UInt32TypeName().
UInt64Type
const TCHAR* RigVMTypeUtils::UInt64Type = TEXT("uint64") inline
Definition at line 69 of file RigVMTypeUtils.h.
Referenced by UInt64TypeName().
UInt8ArrayType
const TCHAR* RigVMTypeUtils::UInt8ArrayType = TEXT("TArray<uint8>") inline
Definition at line 78 of file RigVMTypeUtils.h.
Referenced by UInt8ArrayTypeName().
UInt8Type
const TCHAR* RigVMTypeUtils::UInt8Type = TEXT("uint8") inline
Definition at line 67 of file RigVMTypeUtils.h.
Referenced by UInt8TypeName().