Unreal Engine 5.6 C++ API: TRingBuffer< T, AllocatorT > Class Template Reference
TRingBuffer< T, AllocatorT > Class Template Reference
RingBuffer - an array with a Front and Back pointer and with implicit wraparound to the beginning of the array when reaching the end of the array when iterating from Front to Back Useful for providing O(1) push/pop at the end of the array (for Queue or Stack) while still having high cache coherency during iteration.
#include "RingBuffer.h"
Public Types
typedef AllocatorT Allocator
using ElementAllocatorType
typedef T ElementType
Type of the Elements in the container.
typedef std::make_signed_t< typename Allocator::SizeType > IndexType
Type used to request values at a given index in the container.
typedef std::make_unsigned_t< typename Allocator::SizeType > SizeType
Type used to communicate size and capacity and counts.
typedef TRingBufferIterator< const TRingBuffer, const ElementType, typename Allocator::SizeType > TConstIterator
typedef TRingBufferIterator< TRingBuffer, ElementType, typename Allocator::SizeType > TIterator
Iterator type used for ranged-for traversal.
Public Member Functions
TRingBuffer ()
Construct Empty Queue with capacity 0.
TRingBuffer (const TRingBuffer &Other)
TRingBuffer (SizeType InitialCapacity)
Construct Empty Queue with the given initial requested capacity.
TRingBuffer (std::initializer_list< ElementType > InitList)
Construct a Queue with initial state (from front to back) equal to the given list.
TRingBuffer (TRingBuffer &&Other)
~TRingBuffer ()
IndexType Add (const ElementType &Element)
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
IndexType Add (ElementType &&Element)
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
ElementType & Add_GetRef (const ElementType &Element)
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
ElementType & Add_GetRef (ElementType &&Element)
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
IndexType AddFront (const ElementType &Element)
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
IndexType AddFront (ElementType &&Element)
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
ElementType & AddFront_GetRef (const ElementType &Element)
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
ElementType & AddFront_GetRef (ElementType &&Element)
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
IndexType AddFrontUninitialized ()
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
ElementType & AddFrontUninitialized_GetRef ()
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
IndexType AddUninitialized ()
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
ElementType & AddUninitialized_GetRef ()
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
TIterator begin ()
begin iterator for ranged-for
TConstIterator begin () const
begin iterator for const ranged-for
TArrayView< T > Compact ()
Shift all elements so that the front pointer's location in memory is less than the back pointer's.
IndexType ConvertPointerToIndex (const ElementType *Ptr) const
Given a pointer to an Element anywhere in memory, return the index of the element in the RingBuffer, or INDEX_NONE if it is not present.
template<typename... ArgsType>
IndexType Emplace (ArgsType &&... Args)
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
template<typename... ArgsType>
ElementType & Emplace_GetRef (ArgsType &&... Args)
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
template<typename... ArgsType>
IndexType EmplaceFront (ArgsType &&... Args)
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
template<typename... ArgsType>
ElementType & EmplaceFront_GetRef (ArgsType &&... Args)
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
void Empty (SizeType Capacity=0)
Empty the RingBuffer, destructing any elements and releasing the RingBuffer's storage.
TIterator end ()
end iterator for ranged-for
TConstIterator end () const
end iterator for const ranged-for
ElementType & First ()
Return a reference to the element at the front pointer of the RingBuffer.
const ElementType & First () const
Return a const reference to the element at the front pointer of the RingBuffer.
SIZE_T GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container.
ElementType & GetAtIndexNoCheck (IndexType Index)
Unsafely return a writable reference to the value at the given Index.
const ElementType & GetAtIndexNoCheck (IndexType Index) const
Unsafely return a const reference to the value at the given Index.
bool IsEmpty () const
Returns true if the RingBuffer is empty.
bool IsValidIndex (IndexType Index) const
Tests if index is valid, i.e.
ElementType & Last ()
Return a reference to the element at the back pointer of the RingBuffer.
const ElementType & Last () const
Return a const reference to the element at the back pointer of the RingBuffer.
IndexType Max () const
Current allocated Capacity, note this will always be a power of two, or the special case 0.
void MoveAppendRange (ElementType *OtherData, SizeType OtherNum)
Append elements from a range onto the back pointer of the RingBuffer, resizing if necessary.
IndexType Num () const
Gets the number of elements in the RingBuffer.
template<typename OtherAllocator>
bool operator!= (const TRingBuffer< ElementType, OtherAllocator > &Other) const
TRingBuffer & operator= (const TRingBuffer &Other)
TRingBuffer & operator= (TRingBuffer &&Other)
template<typename OtherAllocator>
bool operator== (const TRingBuffer< ElementType, OtherAllocator > &Other) const
ElementType & operator[] (IndexType Index)
Return a writable reference to the value at the given Index.
const ElementType & operator[] (IndexType Index) const
Return a const reference to the value at the given Index.
void Pop (SizeType PopCount=1)
Pop the given number of arguments (default: 1) from the back pointer of the RingBuffer.
void PopFront (SizeType PopCount=1)
Pop the given number of elements (default: 1) from the front pointer of the RingBuffer.
void PopFrontNoCheck (SizeType PopCount=1)
Unsafely pop the given number of arguments (default: 1) from the front pointer of the RingBuffer.
ElementType PopFrontValue ()
void PopNoCheck (SizeType PopCount=1)
Pop the given number of elements (default: 1) from the back pointer of the RingBuffer.
ElementType PopValue ()
SizeType Remove (const ElementType &Item)
Removes as many instances of Item as there are in the array, maintaining order but not indices.
template<typename PredicateType>
SizeType RemoveAll (PredicateType Predicate)
Removes all items for which a given predicate applies, maintaining order but not indices.
void RemoveAt (IndexType Index)
Remove the value at the given index from the RingBuffer, and shift values ahead or behind it into its location to fill the hole.
void Reserve (SizeType RequiredCapacity)
Set the capacity to the maximum of the current capacity and the (next power of two greater than or equal to) the given capacity.
void Reset ()
Empty the RingBuffer, destructing any elements in the RingBuffer but not releasing the RingBuffer's storage.
void ShiftIndexToBack (IndexType Index)
Move the value at the given index into the back pointer of the RingBuffer, and shift all elements behind of it up by one to make room for it.
void ShiftIndexToFront (IndexType Index)
Move the value at the given index into the front pointer of the RingBuffer, and shift all elements ahead of it down by one to make room for it.
void Trim ()
Set the capacity to the minimum power of two (or 0) greater than or equal to the current number of elements in the RingBuffer.
Private Types
typedef std::make_unsigned_t< typename Allocator::SizeType > StorageModuloType
Type used for variables that are indexes into the underlying storage.
Private Member Functions
void AllocatorResizeAllocation (ElementAllocatorType &InAllocatorInstance, SizeType CurrentNum, SizeType NewArrayMax)
void ConditionalIncrementCapacity ()
Increase capacity if necessary to make room for the addition of a new element.
void DestructRange (StorageModuloType RangeStart, StorageModuloType RangeEnd)
Destruct all elements in the RingBuffer from Index RangeStart to Index RangeEnd.
ElementType * GetStorage ()
Return a const pointer to the underlying storage of the RingBuffer.
FORCEINLINE const ElementType * GetStorage () const
Return a pointer to the underlying storage of the RingBuffer.
SizeType NormalizeCapacity (SizeType InCapacity)
Convert the requested capacity into the implementation-specific actual capacity that should be used.
void PopRangeCheck (SizeType PopCount) const
void RangeCheck (IndexType Index) const
void Reallocate (SizeType NewCapacity)
Set the capacity to the given value and move or copy all elements from the old storage into a new storage with the given capacity.
void ShiftLastToFirst (StorageModuloType RangeFirst, StorageModuloType RangeLast, int RangeDirection)
Move the value at index RangeLast into index RangeFirst, and shift all values between RangeFirst+1 and RangeLast towards RangeLast to make room for it.
void SlackTrackerNumChanged ()
Static Private Member Functions
static constexpr bool NeedsDestructElements ()
Private Attributes
StorageModuloType AfterBack
Pointer to the first location after the back pointer of the RingBuffer; when the RingBuffer is non-empty, one element before this index is the back of the RingBuffer AfterBack is in StorageModulo space.
ElementAllocatorType AllocatorInstance
The underlying storage of the RingBuffer is in the c-style array provided by this AllocatorInstance.GetAllocation().
StorageModuloType Front
Front pointer of the RingBuffer; it points to the first element in the iteration of the RingBuffer, unless the RingBuffer is empty, in which case it can point to any value in the underlying storage.
StorageModuloType IndexMask
A bitmask used to convert from StorageModulo space into an index into Storage.
Friends
class FRingBufferTest
Detailed Description
template<typename T, typename AllocatorT = FDefaultAllocator>
class TRingBuffer< T, AllocatorT >
RingBuffer - an array with a Front and Back pointer and with implicit wraparound to the beginning of the array when reaching the end of the array when iterating from Front to Back Useful for providing O(1) push/pop at the end of the array (for Queue or Stack) while still having high cache coherency during iteration.
Not thread-safe; caller must ensure there is no simultaneous access from multiple threads.
Implementation Details: Relies on unsigned arithmetics and ever-increasing Front and Back indices to avoid having to store an extra element or maintain explicit empty state. Capacity will always be rounded up to the next power of two, to provide rapid masking of the index.
Definition at line 134 of file RingBuffer.h.
Member Typedef Documentation
Allocator
template<typename T, typename AllocatorT = FDefaultAllocator> typedef AllocatorT TRingBuffer< T, AllocatorT >::Allocator
Definition at line 140 of file RingBuffer.h.
ElementAllocatorType
template<typename T, typename AllocatorT = FDefaultAllocator> using TRingBuffer< T, AllocatorT >::ElementAllocatorType
Initial value:
 std::conditional_t<
        Allocator::NeedsElementType,
        typename Allocator::template ForElementType<ElementType>,
        typename Allocator::ForAnyElementType
    >
Definition at line 141 of file RingBuffer.h.
ElementType
template<typename T, typename AllocatorT = FDefaultAllocator> typedef T TRingBuffer< T, AllocatorT >::ElementType
Type of the Elements in the container.
Definition at line 138 of file RingBuffer.h.
IndexType
template<typename T, typename AllocatorT = FDefaultAllocator> typedef std::make_signed_t<typename Allocator::SizeType> TRingBuffer< T, AllocatorT >::IndexType
Type used to request values at a given index in the container.
Definition at line 147 of file RingBuffer.h.
SizeType
template<typename T, typename AllocatorT = FDefaultAllocator> typedef std::make_unsigned_t<typename Allocator::SizeType> TRingBuffer< T, AllocatorT >::SizeType
Type used to communicate size and capacity and counts.
Definition at line 149 of file RingBuffer.h.
StorageModuloType
template<typename T, typename AllocatorT = FDefaultAllocator> typedef std::make_unsigned_t<typename Allocator::SizeType> TRingBuffer< T, AllocatorT >::StorageModuloType private
Type used for variables that are indexes into the underlying storage.
StorageModuloType types are offsets from the beginning of storage, and any bits outside IndexMask are discarded. They may have added on multiples of the capacity due to wrapping around, but will be interpreted as pointing to the value at (value & IndexMask). StorageModuloTypes are also allowed to underflow/overflow their integer storage type; the only constraint is that X - Front <= Capacity for all valid indexes and for AfterBack.
Definition at line 160 of file RingBuffer.h.
TConstIterator
template<typename T, typename AllocatorT = FDefaultAllocator> typedef TRingBufferIterator<const TRingBuffer, const ElementType, typename Allocator::SizeType> TRingBuffer< T, AllocatorT >::TConstIterator
Definition at line 152 of file RingBuffer.h.
TIterator
template<typename T, typename AllocatorT = FDefaultAllocator> typedef TRingBufferIterator<TRingBuffer, ElementType, typename Allocator::SizeType> TRingBuffer< T, AllocatorT >::TIterator
Iterator type used for ranged-for traversal.
Definition at line 151 of file RingBuffer.h.
Constructor & Destructor Documentation
TRingBuffer() [1/5]
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer< T, AllocatorT >::TRingBuffer () inline nodiscard
Construct Empty Queue with capacity 0.
Definition at line 164 of file RingBuffer.h.
References AfterBack, Front, and IndexMask.
Referenced by TRingBuffer(), TRingBuffer(), TRingBuffer(), TRingBuffer(), GetStorage(), operator!=(), operator=(), operator=(), and operator==().
TRingBuffer() [2/5]
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer< T, AllocatorT >::TRingBuffer (SizeType InitialCapacity) inline explicit nodiscard
Construct Empty Queue with the given initial requested capacity.
Definition at line 172 of file RingBuffer.h.
References TRingBuffer(), and Reserve().
TRingBuffer() [3/5]
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer< T, AllocatorT >::TRingBuffer (std::initializer_list< ElementType > InitList) inline nodiscard
Construct a Queue with initial state (from front to back) equal to the given list.
Definition at line 179 of file RingBuffer.h.
References TRingBuffer(), and Add.
TRingBuffer() [4/5]
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer< T, AllocatorT >::TRingBuffer (TRingBuffer< T, AllocatorT > && Other) inline nodiscard
Definition at line 188 of file RingBuffer.h.
References TRingBuffer(), MoveTemp(), and Other.
TRingBuffer() [5/5]
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer< T, AllocatorT >::TRingBuffer (const TRingBuffer< T, AllocatorT > & Other) inline nodiscard
Definition at line 208 of file RingBuffer.h.
References TRingBuffer(), and Other.
~TRingBuffer()
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer< T, AllocatorT >::~TRingBuffer () inline
Definition at line 224 of file RingBuffer.h.
References Empty.
Member Function Documentation
Add() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::Add (const ElementType & Element) inline
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The new element is copy constructed from the argument. Returns the index to the added element.
Definition at line 299 of file RingBuffer.h.
References AddUninitialized(), and GetAtIndexNoCheck().
Add() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::Add (ElementType && Element) inline
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The new element is move constructed from the argument. Returns the index of the added element.
Definition at line 282 of file RingBuffer.h.
References AddUninitialized(), GetAtIndexNoCheck(), and MoveTempIfPossible().
Add_GetRef() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::Add_GetRef (const ElementType & Element) inline nodiscard
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The new element is copy constructed from the argument. Returns a reference to the added element.
Definition at line 308 of file RingBuffer.h.
References AddUninitialized(), and GetAtIndexNoCheck().
Add_GetRef() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::Add_GetRef (ElementType && Element) inline nodiscard
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The new element is move constructed from the argument. Returns a reference to the added element.
Definition at line 291 of file RingBuffer.h.
References AddUninitialized_GetRef(), and MoveTempIfPossible().
AddFront() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::AddFront (const ElementType & Element) inline
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The new element is copy constructed from the argument. Returns the index to the added element.
Definition at line 411 of file RingBuffer.h.
References AddFrontUninitialized(), and GetAtIndexNoCheck().
AddFront() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::AddFront (ElementType && Element) inline
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The new element is move constructed from the argument. Returns the index of the added element.
Definition at line 394 of file RingBuffer.h.
References AddFrontUninitialized(), GetAtIndexNoCheck(), and MoveTempIfPossible().
AddFront_GetRef() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::AddFront_GetRef (const ElementType & Element) inline nodiscard
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The new element is copy constructed from the argument. Returns a reference to the added element.
Definition at line 420 of file RingBuffer.h.
References AddFrontUninitialized(), and GetAtIndexNoCheck().
AddFront_GetRef() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::AddFront_GetRef (ElementType && Element) inline nodiscard
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The new element is move constructed from the argument. Returns a reference to the added element.
Definition at line 403 of file RingBuffer.h.
References AddFrontUninitialized_GetRef(), and MoveTempIfPossible().
AddFrontUninitialized()
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::AddFrontUninitialized () inline
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The constructor is not called on the new element and its values in memory are arbitrary. Returns the index to the added element.
Definition at line 448 of file RingBuffer.h.
References ConditionalIncrementCapacity(), Front, and SlackTrackerNumChanged().
Referenced by AddFront(), AddFront(), AddFront_GetRef(), AddFrontUninitialized_GetRef(), and EmplaceFront().
AddFrontUninitialized_GetRef()
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::AddFrontUninitialized_GetRef () inline nodiscard
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The constructor is not called on the new element and its values in memory are arbitrary. Returns a reference to the added element.
Definition at line 460 of file RingBuffer.h.
References AddFrontUninitialized(), and GetAtIndexNoCheck().
Referenced by AddFront_GetRef(), and EmplaceFront_GetRef().
AddUninitialized()
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::AddUninitialized () inline
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The constructor is not called on the new element and its values in memory are arbitrary. Returns the index to the added element.
Definition at line 336 of file RingBuffer.h.
References AfterBack, ConditionalIncrementCapacity(), Front, and SlackTrackerNumChanged().
Referenced by Add(), Add(), Add_GetRef(), AddUninitialized_GetRef(), and Emplace().
AddUninitialized_GetRef()
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::AddUninitialized_GetRef () inline nodiscard
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The constructor is not called on the new element and its values in memory are arbitrary. Returns a reference to the added element.
Definition at line 348 of file RingBuffer.h.
References AddUninitialized(), and GetAtIndexNoCheck().
Referenced by Add_GetRef(), and Emplace_GetRef().
AllocatorResizeAllocation()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::AllocatorResizeAllocation (ElementAllocatorType & InAllocatorInstance, SizeType CurrentNum, SizeType NewArrayMax) inline private
Definition at line 862 of file RingBuffer.h.
References TAllocatorTraitsBase< AllocatorType >::SupportsElementAlignment.
Referenced by Reallocate().
begin() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> TIterator TRingBuffer< T, AllocatorT >::begin () inline nodiscard
begin iterator for ranged-for
Definition at line 565 of file RingBuffer.h.
begin() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> TConstIterator TRingBuffer< T, AllocatorT >::begin () const inline nodiscard
begin iterator for const ranged-for
Definition at line 571 of file RingBuffer.h.
Compact()
template<typename T, typename AllocatorT = FDefaultAllocator> TArrayView< T > TRingBuffer< T, AllocatorT >::Compact () inline
Shift all elements so that the front pointer's location in memory is less than the back pointer's.
Returns a temporary ArrayView for the RingBuffer's elements; the returned ArrayView will be invalid after the next write operation on the RingBuffer.
Definition at line 769 of file RingBuffer.h.
References AfterBack, Front, GetStorage(), IndexMask, Max(), Num(), and Reallocate().
ConditionalIncrementCapacity()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::ConditionalIncrementCapacity () inline private
Increase capacity if necessary to make room for the addition of a new element.
Definition at line 932 of file RingBuffer.h.
References Num(), and Reserve().
Referenced by AddFrontUninitialized(), and AddUninitialized().
ConvertPointerToIndex()
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::ConvertPointerToIndex (const ElementType * Ptr) const inline nodiscard
Given a pointer to an Element anywhere in memory, return the index of the element in the RingBuffer, or INDEX_NONE if it is not present.
Definition at line 621 of file RingBuffer.h.
References Front, GetStorage(), INDEX_NONE, IndexMask, Max(), and Num().
DestructRange()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::DestructRange (StorageModuloType RangeStart, StorageModuloType RangeEnd) inline private
Destruct all elements in the RingBuffer from Index RangeStart to Index RangeEnd.
RangeStart and RangeEnd are given in StorageModulo space. RangeEnd - RangeStart must be less than or equal to capacity. Note that due to potential valid overflow of StorageModuleType, RangeEnd might be less than RangeStart if RangeStart is e.g. 0xffffffff and RangeEnd is 0, and RangeEnd - RangeStart is 1.
Definition at line 890 of file RingBuffer.h.
References check, DestructItems(), GetStorage(), IndexMask, Max(), and NeedsDestructElements().
Referenced by PopFrontNoCheck(), PopNoCheck(), and Reallocate().
Emplace()
template<typename T, typename AllocatorT = FDefaultAllocator> template<typename... ArgsType> IndexType TRingBuffer< T, AllocatorT >::Emplace (ArgsType &&... Args) inline
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The new element is constructed from the given arguments. Returns the index to the added element.
Definition at line 318 of file RingBuffer.h.
References AddUninitialized(), Forward(), and GetAtIndexNoCheck().
Emplace_GetRef()
template<typename T, typename AllocatorT = FDefaultAllocator> template<typename... ArgsType> ElementType & TRingBuffer< T, AllocatorT >::Emplace_GetRef (ArgsType &&... Args) inline nodiscard
Add a new element after the back pointer of the RingBuffer, resizing if necessary.
The new element is constructed from the given arguments. Returns a reference to the added element.
Definition at line 328 of file RingBuffer.h.
References AddUninitialized_GetRef(), and Forward().
EmplaceFront()
template<typename T, typename AllocatorT = FDefaultAllocator> template<typename... ArgsType> IndexType TRingBuffer< T, AllocatorT >::EmplaceFront (ArgsType &&... Args) inline
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The new element is constructed from the given arguments. Returns the index to the added element.
Definition at line 430 of file RingBuffer.h.
References AddFrontUninitialized(), Forward(), and GetAtIndexNoCheck().
EmplaceFront_GetRef()
template<typename T, typename AllocatorT = FDefaultAllocator> template<typename... ArgsType> ElementType & TRingBuffer< T, AllocatorT >::EmplaceFront_GetRef (ArgsType &&... Args) inline nodiscard
Add a new element before the front pointer of the RingBuffer, resizing if necessary.
The new element is constructed from the given arguments. Returns a reference to the added element.
Definition at line 440 of file RingBuffer.h.
References AddFrontUninitialized_GetRef(), and Forward().
Empty()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::Empty (SizeType Capacity = 0) inline
Empty the RingBuffer, destructing any elements and releasing the RingBuffer's storage.
Sets the new capacity after release to the given capacity.
Definition at line 274 of file RingBuffer.h.
References NormalizeCapacity(), Reallocate(), and Reset().
end() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> TIterator TRingBuffer< T, AllocatorT >::end () inline nodiscard
end iterator for ranged-for
Definition at line 577 of file RingBuffer.h.
References Num().
end() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> TConstIterator TRingBuffer< T, AllocatorT >::end () const inline nodiscard
end iterator for const ranged-for
Definition at line 583 of file RingBuffer.h.
References Num().
First() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::First () inline nodiscard
Return a reference to the element at the front pointer of the RingBuffer.
Invalid to call on an empty RingBuffer.
Definition at line 466 of file RingBuffer.h.
Referenced by PopFrontValue().
First() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> const ElementType & TRingBuffer< T, AllocatorT >::First () const inline nodiscard
Return a const reference to the element at the front pointer of the RingBuffer.
Invalid to call on an empty RingBuffer.
Definition at line 472 of file RingBuffer.h.
GetAllocatedSize()
template<typename T, typename AllocatorT = FDefaultAllocator> SIZE_T TRingBuffer< T, AllocatorT >::GetAllocatedSize (void) const inline nodiscard
Helper function to return the amount of memory allocated by this container.
Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
Number of bytes allocated by this container.
Definition at line 789 of file RingBuffer.h.
References Max().
GetAtIndexNoCheck() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::GetAtIndexNoCheck (IndexType Index) inline nodiscard
Unsafely return a writable reference to the value at the given Index.
Invalid to call (and does not warn) with an index less than 0 or greater than or equal to the number of elements in the RingBuffer.
Definition at line 609 of file RingBuffer.h.
References Front, GetStorage(), and IndexMask.
Referenced by Add(), Add(), Add_GetRef(), AddFront(), AddFront(), AddFront_GetRef(), AddFrontUninitialized_GetRef(), AddUninitialized_GetRef(), Emplace(), EmplaceFront(), operator==(), operator[](), and operator[]().
GetAtIndexNoCheck() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> const ElementType & TRingBuffer< T, AllocatorT >::GetAtIndexNoCheck (IndexType Index) const inline nodiscard
Unsafely return a const reference to the value at the given Index.
Invalid to call (and does not warn) with an index less than 0 or greater than or equal to the number of elements in the RingBuffer.
Definition at line 615 of file RingBuffer.h.
References Front, GetStorage(), and IndexMask.
GetStorage() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType * TRingBuffer< T, AllocatorT >::GetStorage () inline nodiscard private
Return a const pointer to the underlying storage of the RingBuffer.
Definition at line 985 of file RingBuffer.h.
References AllocatorInstance.
GetStorage() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> FORCEINLINE const ElementType * TRingBuffer< T, AllocatorT >::GetStorage () const inline nodiscard private
Return a pointer to the underlying storage of the RingBuffer.
Definition at line 979 of file RingBuffer.h.
References TRingBuffer(), FORCEINLINE, and GetStorage().
Referenced by Compact(), ConvertPointerToIndex(), DestructRange(), GetAtIndexNoCheck(), GetAtIndexNoCheck(), GetStorage(), MoveAppendRange(), Reallocate(), RemoveAll(), and ShiftLastToFirst().
IsEmpty()
template<typename T, typename AllocatorT = FDefaultAllocator> bool TRingBuffer< T, AllocatorT >::IsEmpty () const inline nodiscard
Returns true if the RingBuffer is empty.
Definition at line 230 of file RingBuffer.h.
References AfterBack, and Front.
IsValidIndex()
template<typename T, typename AllocatorT = FDefaultAllocator> bool TRingBuffer< T, AllocatorT >::IsValidIndex (IndexType Index) const inline nodiscard
Tests if index is valid, i.e.
greater than or equal to zero, and less than the number of elements in the array.
Definition at line 589 of file RingBuffer.h.
References Num().
Last() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::Last () inline nodiscard
Return a reference to the element at the back pointer of the RingBuffer.
Invalid to call on an empty RingBuffer.
Definition at line 478 of file RingBuffer.h.
References Num().
Referenced by PopValue().
Last() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> const ElementType & TRingBuffer< T, AllocatorT >::Last () const inline nodiscard
Return a const reference to the element at the back pointer of the RingBuffer.
Invalid to call on an empty RingBuffer.
Definition at line 484 of file RingBuffer.h.
References Num().
Max()
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::Max () const inline nodiscard
Current allocated Capacity, note this will always be a power of two, or the special case 0.
Definition at line 242 of file RingBuffer.h.
References IndexMask.
Referenced by Compact(), ConvertPointerToIndex(), DestructRange(), GetAllocatedSize(), Reallocate(), RemoveAt(), Reserve(), and ShiftLastToFirst().
MoveAppendRange()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::MoveAppendRange (ElementType * OtherData, SizeType OtherNum) inline
Append elements from a range onto the back pointer of the RingBuffer, resizing if necessary.
Each element is move-constructed into the RingBuffer; source elements may therefore be modified.
Definition at line 357 of file RingBuffer.h.
References AfterBack, check, checkf, Front, GetStorage(), IndexMask, MoveConstructItems(), Num(), Reserve(), SlackTrackerNumChanged(), and TEXT.
NeedsDestructElements()
template<typename T, typename AllocatorT = FDefaultAllocator> constexpr bool TRingBuffer< T, AllocatorT >::NeedsDestructElements () inline static nodiscard constexpr private
Definition at line 795 of file RingBuffer.h.
Referenced by DestructRange(), RemoveAll(), and ShiftLastToFirst().
NormalizeCapacity()
template<typename T, typename AllocatorT = FDefaultAllocator> SizeType TRingBuffer< T, AllocatorT >::NormalizeCapacity (SizeType InCapacity) inline private
Convert the requested capacity into the implementation-specific actual capacity that should be used.
Definition at line 918 of file RingBuffer.h.
References checkf, and TEXT.
Referenced by Empty(), Reallocate(), Reserve(), and Trim().
Num()
template<typename T, typename AllocatorT = FDefaultAllocator> IndexType TRingBuffer< T, AllocatorT >::Num () const inline nodiscard
Gets the number of elements in the RingBuffer.
Definition at line 236 of file RingBuffer.h.
References AfterBack, and Front.
Referenced by Compact(), ConditionalIncrementCapacity(), ConvertPointerToIndex(), end(), end(), IsValidIndex(), Last(), Last(), MoveAppendRange(), operator==(), PopRangeCheck(), RangeCheck(), Reallocate(), Reset(), ShiftIndexToBack(), SlackTrackerNumChanged(), and Trim().
operator!=()
template<typename T, typename AllocatorT = FDefaultAllocator> template<typename OtherAllocator> bool TRingBuffer< T, AllocatorT >::operator!= (const TRingBuffer< ElementType, OtherAllocator > & Other) const inline nodiscard
Definition at line 760 of file RingBuffer.h.
References TRingBuffer(), and Other.
operator=() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer & TRingBuffer< T, AllocatorT >::operator= (const TRingBuffer< T, AllocatorT > & Other) inline
Definition at line 214 of file RingBuffer.h.
References TRingBuffer(), Add, Empty, and Other.
operator=() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> TRingBuffer & TRingBuffer< T, AllocatorT >::operator= (TRingBuffer< T, AllocatorT > && Other) inline
Definition at line 194 of file RingBuffer.h.
References TRingBuffer(), AfterBack, AllocatorInstance, Empty, Front, IndexMask, Other, and Swap.
operator==()
template<typename T, typename AllocatorT = FDefaultAllocator> template<typename OtherAllocator> bool TRingBuffer< T, AllocatorT >::operator== (const TRingBuffer< ElementType, OtherAllocator > & Other) const inline nodiscard
Definition at line 742 of file RingBuffer.h.
References TRingBuffer(), GetAtIndexNoCheck(), Num(), and Other.
operator[]() [1/2]
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType & TRingBuffer< T, AllocatorT >::operator[] (IndexType Index) inline nodiscard
Return a writable reference to the value at the given Index.
Invalid to call with an index less than 0 or greater than or equal to the number of elements in the RingBuffer.
Definition at line 595 of file RingBuffer.h.
References GetAtIndexNoCheck(), and RangeCheck().
operator[]() [2/2]
template<typename T, typename AllocatorT = FDefaultAllocator> const ElementType & TRingBuffer< T, AllocatorT >::operator[] (IndexType Index) const inline nodiscard
Return a const reference to the value at the given Index.
Invalid to call with an index less than 0 or greater than or equal to the number of elements in the RingBuffer.
Definition at line 602 of file RingBuffer.h.
References GetAtIndexNoCheck(), and RangeCheck().
Pop()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::Pop (SizeType PopCount = 1) inline
Pop the given number of arguments (default: 1) from the back pointer of the RingBuffer.
Invalid to call with a number of elements greater than the current number of elements in the RingBuffer.
Definition at line 515 of file RingBuffer.h.
References PopNoCheck(), and PopRangeCheck().
Referenced by RemoveAt().
PopFront()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::PopFront (SizeType PopCount = 1) inline
Pop the given number of elements (default: 1) from the front pointer of the RingBuffer.
Invalid to call with a number of elements greater than the current number of elements in the RingBuffer.
Definition at line 490 of file RingBuffer.h.
References PopFrontNoCheck(), and PopRangeCheck().
Referenced by RemoveAt().
PopFrontNoCheck()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::PopFrontNoCheck (SizeType PopCount = 1) inline
Unsafely pop the given number of arguments (default: 1) from the front pointer of the RingBuffer.
Invalid to call (and does not warn) with a number of elements greater than the current number of elements in the RingBuffer.
Definition at line 497 of file RingBuffer.h.
References DestructRange(), Front, and SlackTrackerNumChanged().
Referenced by PopFront(), PopFrontValue(), and Reset().
PopFrontValue()
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType TRingBuffer< T, AllocatorT >::PopFrontValue () inline
Definition at line 506 of file RingBuffer.h.
References First(), MoveTemp(), PopFrontNoCheck(), and PopRangeCheck().
PopNoCheck()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::PopNoCheck (SizeType PopCount = 1) inline
Pop the given number of elements (default: 1) from the back pointer of the RingBuffer.
Invalid to call (and does not warn) with a number of elements greater than the current number of elements in the RingBuffer.
Definition at line 522 of file RingBuffer.h.
References AfterBack, DestructRange(), and SlackTrackerNumChanged().
Referenced by Pop(), and PopValue().
PopRangeCheck()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::PopRangeCheck (SizeType PopCount) const inline private
Definition at line 1000 of file RingBuffer.h.
References checkf, Num(), and TEXT.
Referenced by Pop(), PopFront(), PopFrontValue(), and PopValue().
PopValue()
template<typename T, typename AllocatorT = FDefaultAllocator> ElementType TRingBuffer< T, AllocatorT >::PopValue () inline
Definition at line 531 of file RingBuffer.h.
References Last(), MoveTemp(), PopNoCheck(), and PopRangeCheck().
RangeCheck()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::RangeCheck (IndexType Index) const inline private
Definition at line 991 of file RingBuffer.h.
References checkf, Num(), and TEXT.
Referenced by operator[](), operator[](), RemoveAt(), ShiftIndexToBack(), and ShiftIndexToFront().
Reallocate()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::Reallocate (SizeType NewCapacity) inline private
Set the capacity to the given value and move or copy all elements from the old storage into a new storage with the given capacity.
Assumes the capacity has already been normalized and is greater than or equal to the number of elements in the RingBuffer.
Definition at line 801 of file RingBuffer.h.
References AfterBack, AllocatorInstance, AllocatorResizeAllocation(), check, DestructRange(), Front, GetStorage(), IndexMask, Max(), MoveTemp(), NormalizeCapacity(), and Num().
Referenced by Compact(), Empty(), Reserve(), and Trim().
Remove()
template<typename T, typename AllocatorT = FDefaultAllocator> SizeType TRingBuffer< T, AllocatorT >::Remove (const ElementType & Item) inline
Removes as many instances of Item as there are in the array, maintaining order but not indices.
Parameters
Item Item to remove from array.
Returns
Number of removed elements.
Definition at line 678 of file RingBuffer.h.
References Item, and RemoveAll().
RemoveAll()
template<typename T, typename AllocatorT = FDefaultAllocator> template<typename PredicateType> SizeType TRingBuffer< T, AllocatorT >::RemoveAll (PredicateType Predicate) inline
Removes all items for which a given predicate applies, maintaining order but not indices.
Parameters
Predicate Any item for which the predicate returns true is removed.
Returns
Number of removed elements.
Definition at line 690 of file RingBuffer.h.
References AfterBack, DestructItem(), Front, GetStorage(), IndexMask, MoveTemp(), NeedsDestructElements(), Predicate, and SlackTrackerNumChanged().
Referenced by Remove().
RemoveAt()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::RemoveAt (IndexType Index) inline
Remove the value at the given index from the RingBuffer, and shift values ahead or behind it into its location to fill the hole.
It is valid to call with Index outside the range of the array; does nothing in that case.
Definition at line 651 of file RingBuffer.h.
References AfterBack, Front, IndexMask, Max(), Pop(), PopFront(), RangeCheck(), ShiftIndexToBack(), and ShiftIndexToFront().
Reserve()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::Reserve (SizeType RequiredCapacity) inline
Set the capacity to the maximum of the current capacity and the (next power of two greater than or equal to) the given capacity.
Definition at line 248 of file RingBuffer.h.
References Max(), NormalizeCapacity(), and Reallocate().
Referenced by TRingBuffer(), ConditionalIncrementCapacity(), and MoveAppendRange().
Reset()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::Reset () inline
Empty the RingBuffer, destructing any elements in the RingBuffer but not releasing the RingBuffer's storage.
Definition at line 266 of file RingBuffer.h.
References AfterBack, Front, Num(), and PopFrontNoCheck().
Referenced by Empty().
ShiftIndexToBack()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::ShiftIndexToBack (IndexType Index) inline
Move the value at the given index into the back pointer of the RingBuffer, and shift all elements behind of it up by one to make room for it.
Invalid to call with an index less than 0 or greater than or equal to the number of elements in the RingBuffer.
Definition at line 552 of file RingBuffer.h.
References AfterBack, Front, Num(), RangeCheck(), and ShiftLastToFirst().
Referenced by RemoveAt().
ShiftIndexToFront()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::ShiftIndexToFront (IndexType Index) inline
Move the value at the given index into the front pointer of the RingBuffer, and shift all elements ahead of it down by one to make room for it.
Invalid to call with a negative index or index greater than the number of elements in the RingBuffer.
Definition at line 540 of file RingBuffer.h.
References Front, RangeCheck(), and ShiftLastToFirst().
Referenced by RemoveAt().
ShiftLastToFirst()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::ShiftLastToFirst (StorageModuloType RangeFirst, StorageModuloType RangeLast, int RangeDirection) inline private
Move the value at index RangeLast into index RangeFirst, and shift all values between RangeFirst+1 and RangeLast towards RangeLast to make room for it.
RangeLast may be greater than or less than RangeFirst; the shift of the other elements will occur in the appropriate direction from RangeFirst down to RangeLast. RangeFirst and RangeLast are given in StorageModulo space. RangeDirection is -1 or 1 and indicates which direction we should move in StorageModulo space to iterate from RangeLast to RangeFirst. Required constraint: (RangeLast - RangeFirst) <= capacity for RangeDirection == -1, and (RangeFirst - RangeLast) <= capacity for RangeDirection == 1
Definition at line 944 of file RingBuffer.h.
References check, Copy, DestructItems(), GetStorage(), IndexMask, Max(), MoveTemp(), and NeedsDestructElements().
Referenced by ShiftIndexToBack(), and ShiftIndexToFront().
SlackTrackerNumChanged()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::SlackTrackerNumChanged () inline private
Definition at line 874 of file RingBuffer.h.
References AllocatorInstance, Num(), and TAllocatorTraitsBase< AllocatorType >::SupportsSlackTracking.
Referenced by AddFrontUninitialized(), AddUninitialized(), MoveAppendRange(), PopFrontNoCheck(), PopNoCheck(), and RemoveAll().
Trim()
template<typename T, typename AllocatorT = FDefaultAllocator> void TRingBuffer< T, AllocatorT >::Trim () inline
Set the capacity to the minimum power of two (or 0) greater than or equal to the current number of elements in the RingBuffer.
Definition at line 259 of file RingBuffer.h.
References NormalizeCapacity(), Num(), and Reallocate().
Friends And Related Symbol Documentation
FRingBufferTest
template<typename T, typename AllocatorT = FDefaultAllocator> friend class FRingBufferTest friend
Definition at line 1008 of file RingBuffer.h.
References FRingBufferTest.
Referenced by FRingBufferTest.
Field Documentation
AfterBack
template<typename T, typename AllocatorT = FDefaultAllocator> StorageModuloType TRingBuffer< T, AllocatorT >::AfterBack private
Pointer to the first location after the back pointer of the RingBuffer; when the RingBuffer is non-empty, one element before this index is the back of the RingBuffer AfterBack is in StorageModulo space.
Like all values in StorageModulo space, AfterBack is allowed to underflow or overflow its StorageModuloType; it might be 0 and then subtract 1 to wrap around to 0xffffffff, but it is always true that (AfterBack - Front) <= capacity. Note that when AfterBack is converted from StorageModulo space into an index into underlying storage (AfterBack&IndexMask), it will be equal to (Front&IndexMask) for both an empty RingBuffer and for a RingBuffer that is at capacity.
Definition at line 1036 of file RingBuffer.h.
Referenced by TRingBuffer(), AddUninitialized(), Compact(), IsEmpty(), MoveAppendRange(), Num(), operator=(), PopNoCheck(), Reallocate(), RemoveAll(), RemoveAt(), Reset(), and ShiftIndexToBack().
AllocatorInstance
template<typename T, typename AllocatorT = FDefaultAllocator> ElementAllocatorType TRingBuffer< T, AllocatorT >::AllocatorInstance private
The underlying storage of the RingBuffer is in the c-style array provided by this AllocatorInstance.GetAllocation().
Elements in this array are uninitialized until the front pointer moves before them or the back pointer moves after them. The front pointer and the back pointer can be at arbitrary offsets in this array.
Definition at line 1015 of file RingBuffer.h.
Referenced by GetStorage(), operator=(), Reallocate(), and SlackTrackerNumChanged().
Front
template<typename T, typename AllocatorT = FDefaultAllocator> StorageModuloType TRingBuffer< T, AllocatorT >::Front private
Front pointer of the RingBuffer; it points to the first element in the iteration of the RingBuffer, unless the RingBuffer is empty, in which case it can point to any value in the underlying storage.
Front is in StorageModulo space. Like all values in StorageModulo space, Front is allowed to underflow or overflow its StorageModuloType; it might be 0 and then subtract 1 to wrap around to 0xffffffff.
Definition at line 1027 of file RingBuffer.h.
Referenced by TRingBuffer(), AddFrontUninitialized(), AddUninitialized(), Compact(), ConvertPointerToIndex(), GetAtIndexNoCheck(), GetAtIndexNoCheck(), IsEmpty(), MoveAppendRange(), Num(), operator=(), PopFrontNoCheck(), Reallocate(), RemoveAll(), RemoveAt(), Reset(), ShiftIndexToBack(), and ShiftIndexToFront().
IndexMask
template<typename T, typename AllocatorT = FDefaultAllocator> StorageModuloType TRingBuffer< T, AllocatorT >::IndexMask private
A bitmask used to convert from StorageModulo space into an index into Storage.
(X & IndexMask) is a valid index into GetStorage() for any value of X, as long as the RingBuffer is non-empty. Tightly tied to capacity; IndexMask == capacity - 1
Definition at line 1021 of file RingBuffer.h.
Referenced by TRingBuffer(), Compact(), ConvertPointerToIndex(), DestructRange(), GetAtIndexNoCheck(), GetAtIndexNoCheck(), Max(), MoveAppendRange(), operator=(), Reallocate(), RemoveAll(), RemoveAt(), and ShiftLastToFirst().
The documentation for this class was generated from the following file:
RingBuffer.h