Unreal Engine 5.6 C++ API: ScalableFloat.h File Reference
ScalableFloat.h File Reference
#include "CoreMinimal.h"
#include "Engine/CurveTable.h"
#include "DataRegistryId.h"
#include "ScalableFloat.generated.h"
Data Structures
struct TStructOpsTypeTraits< FScalableFloat >
Macros
#define SCALABLEFLOAT_REPORTERROR(Scalable)
Macro to call IsValidWithWarnings with a correct error info.
#define SCALABLEFLOAT_REPORTERROR_WITHPATHNAME(Scalable, PathNameString)
Macro to call IsValidWithWarnings with a correct error info.
#define UE_API GAMEPLAYABILITIES_API
Functions
USTRUCT () struct FScalableFloat
Generic numerical value in the form Value * Curve[Level].
Macro Definition Documentation
SCALABLEFLOAT_REPORTERROR
#define SCALABLEFLOAT_REPORTERROR (Scalable)
Value:
    Scalable.IsValidWithWarnings(FString::Printf(TEXT("%s.%s"), *GetPathName(), TEXT(#Scalable)))\
Macro to call IsValidWithWarnings with a correct error info.
Assumed to be called within a UObject
Definition at line 130 of file ScalableFloat.h.
SCALABLEFLOAT_REPORTERROR_WITHPATHNAME
#define SCALABLEFLOAT_REPORTERROR_WITHPATHNAME (Scalable, PathNameString)
Value:
    Scalable.IsValidWithWarnings(FString::Printf(TEXT("%s.%s"), *PathNameString, TEXT(#Scalable)))
Macro to call IsValidWithWarnings with a correct error info.
Definition at line 134 of file ScalableFloat.h.
UE_API
#define UE_API GAMEPLAYABILITIES_API
Definition at line 10 of file ScalableFloat.h.
Function Documentation
USTRUCT()
USTRUCT ()
Generic numerical value in the form Value * Curve[Level].
Raw value, is multiplied by curve
Curve that is evaluated at a specific level. If found, it is multipled by Value
Name of Data Registry containing curve to use. If set the RowName inside Curve is used as the item name
Returns the scaled value at a given level
Returns the scaled value at level 0
Used when using a scalable float as a bool
Returns the value as an int32
Gets the value and possible curve at a given level, returning false if it failed to find a good value
True if there is no curve lookup
Sets raw value
Overrides raw value and curve reference
Returns static value, only safe if this has no curve reference
Outputs human readable string
Error checking: Returns false if this has an invalid curve reference but will not print warnings
Error checking: Checks if float is valid and prints detailed warnings if not valid
Error checking must be performed by the owning class, then call this to get specific errors
Equality/Inequality operators
copy operator to prevent duplicate handles
Used to upgrade a float or int8/int16/int32 property into an FScalableFloat
Definition at line 13 of file ScalableFloat.h.
References BlueprintType, Category, check, GENERATED_USTRUCT_BODY, INDEX_NONE, IsValid(), operator!=(), operator=(), operator==(), Other, UE_API, UE_DEPRECATED, UPROPERTY, and Value.