Unreal Engine 5.6 C++ API: Verse Namespace Reference
Verse Namespace Reference
Namespaces
namespace CodeGen
namespace Names
namespace ObjectPrinting
Data Structures
class CAttributeArrayValue
class CAttributeClassValue
class CAttributeFloatValue
class CAttributeIntValue
class CAttributeLogicValue
class CAttributeStringValue
class CAttributeTypeValue
class CAttributeValue
struct FInstantiationContext
struct FInstantiationScope
class FNativeCastableType
struct FNativeConverter
class FNativeString
class FNativeType
class FNativeTypeBase
class FPackageName
class ICustomAttributeHandler
class IEngineEnvironment
struct SRuntimeDiagnosticInfo
struct TagOf
struct TagOf< T, T, Ts... >
struct TagOf< T, U, Ts... >
struct TFromVValue
struct TFromVValue< NativeType >
struct TFromVValue< NativeType, typename TEnableIf< TIsNativeStruct< NativeType >::Value >::Type >
struct TFromVValue< TNonNullPtr< NativeType > >
struct TGetTupleElem
struct TGetTupleElem< 0, TNativeTuple< Type, RestTypes... > >
struct TGetTupleElem< Idx, TNativeTuple< Type, RestTypes... > >
struct TIsNativeStruct
class TNativeSubtype
struct TNativeTuple
struct TNativeTuple< Type >
struct TNativeTuple< Type, RestTypes... >
struct TNativeTuple<>
struct TPtrVariant
struct TToVValue
struct TToVValue< NativeType >
struct TToVValue< TNonNullPtr< ObjectType > >
class VerseVM
Typedefs
using CAttributeValueMap = TMap<FName, TSharedPtr<CAttributeValue>>
template<class T>
using TNativeCastableSubtype = TNativeSubtype<T, FNativeCastableType>
Enumerations
enum class EAttributeValueType {
Logic , Int , Float , Type ,
Class , Array , String
}
enum class EDefaultConstructNativeType { UnsafeDoNotUse }
enum class EFloatStringFormat { Legacy , ShortestOfFixedOrScientific }
enum class ERuntimeDiagnostic : uint16_t {
ErrRuntime_Internal , ErrRuntime_TransactionAbortedByLanguage , ErrRuntime_NativeInternal , ErrRuntime_GeneratedNativeInternal ,
ErrRuntime_InfiniteLoop , ErrRuntime_ComputationLimitExceeded , ErrRuntime_Overflow , ErrRuntime_Underflow ,
ErrRuntime_FloatingPointOverflow , ErrRuntime_IntegerOverflow , ErrRuntime_ErrorRequested , ErrRuntime_IntegerBoundsExceeded ,
ErrRuntime_MemoryLimitExceeded , ErrRuntime_DivisionByZero , ErrRuntime_WeakMapInvalidKey , ErrRuntime_InvalidVarRead ,
ErrRuntime_InvalidVarWrite , ErrRuntime_InvalidFunctionCall , ErrRuntime_MathIntrinsicCallFailure , ErrRuntime_InvalidArrayLength ,
ErrRuntime_InvalidStringLength
}
enum class ERuntimeDiagnosticSeverity : uint8_t { UnrecoverableError }
enum class EValueStringFormat {
Verse , Diagnostic , Cells , CellsWithAddresses ,
JSON
}
Functions
void AppendDecimalToString (FUtf8StringBuilderBase &Builder, VFloat Float, EFloatStringFormat Format=EFloatStringFormat::ShortestOfFixedOrScientific)
void AppendToString (FUtf8StringBuilderBase &Builder, UObject *Object, EValueStringFormat Format, uint32 RecursionDepth)
void AppendToString (VCell *Cell, FUtf8StringBuilderBase &Builder, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth=0)
void AppendToString (VValue Value, FUtf8StringBuilderBase &Builder, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth=0)
void AppendVerseToString (FUtf8StringBuilderBase &Builder, FUtf8StringView String)
void AppendVerseToString (FUtf8StringBuilderBase &Builder, UTF32CHAR Char)
void AppendVerseToString (FUtf8StringBuilderBase &Builder, UTF8CHAR Char)
FString AsFormattedString (const ERuntimeDiagnostic &Diagnostic, const FText &MessageText)
constexpr size_t BitCeil (size_t X)
const SRuntimeDiagnosticInfo & GetRuntimeDiagnosticInfo (const ERuntimeDiagnostic Diagnostic)
template<typename... Ts>
uint32 GetTypeHash (TPtrVariant< Ts... > Ptr)
constexpr bool IsCellFormat (EValueStringFormat Format)
FUtf8String ToString (VCell *Cell, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth=0)
FUtf8String ToString (VValue Value, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth=0)
FUtf8String VerseToString (FUtf8StringView String)
FUtf8String VerseToString (UTF32CHAR Char)
FUtf8String VerseToString (UTF8CHAR Char)
Variables
TAutoConsoleVariable< bool > CVarEnableAssetClassRedirectors
TAutoConsoleVariable< bool > CVarForceCompileFramework
TAutoConsoleVariable< bool > CVarUseDynamicSubobjectInstancing
Typedef Documentation
CAttributeValueMap
using Verse::CAttributeValueMap = TMap<FName, TSharedPtr<CAttributeValue>>
Definition at line 81 of file VVMCustomAttributeHandler.h.
TNativeCastableSubtype
template<class T> using Verse::TNativeCastableSubtype = TNativeSubtype<T, FNativeCastableType>
Definition at line 123 of file VVMNativeType.h.
Enumeration Type Documentation
EAttributeValueType
enum class Verse::EAttributeValueType strong
Enumerator
Logic
Int
Float
Type
Class
Array
String
Definition at line 10 of file VVMCustomAttributeHandler.h.
EDefaultConstructNativeType
enum class Verse::EDefaultConstructNativeType strong
Enumerator
UnsafeDoNotUse
Definition at line 26 of file VVMNativeType.h.
EFloatStringFormat
enum class Verse::EFloatStringFormat strong
Enumerator
Legacy
ShortestOfFixedOrScientific
Definition at line 11 of file VVMFloatPrinting.h.
ERuntimeDiagnostic
enum class Verse::ERuntimeDiagnostic : uint16_t strong
Enumerator
ErrRuntime_Internal
ErrRuntime_TransactionAbortedByLanguage
ErrRuntime_NativeInternal
ErrRuntime_GeneratedNativeInternal
ErrRuntime_InfiniteLoop
ErrRuntime_ComputationLimitExceeded
ErrRuntime_Overflow
ErrRuntime_Underflow
ErrRuntime_FloatingPointOverflow
ErrRuntime_IntegerOverflow
ErrRuntime_ErrorRequested
ErrRuntime_IntegerBoundsExceeded
ErrRuntime_MemoryLimitExceeded
ErrRuntime_DivisionByZero
ErrRuntime_WeakMapInvalidKey
ErrRuntime_InvalidVarRead
ErrRuntime_InvalidVarWrite
ErrRuntime_InvalidFunctionCall
ErrRuntime_MathIntrinsicCallFailure
ErrRuntime_InvalidArrayLength
ErrRuntime_InvalidStringLength
Definition at line 36 of file VVMVerseException.h.
ERuntimeDiagnosticSeverity
enum class Verse::ERuntimeDiagnosticSeverity : uint8_t strong
Enumerator
UnrecoverableError
Definition at line 43 of file VVMVerseException.h.
EValueStringFormat
enum class Verse::EValueStringFormat strong
Enumerator
Verse
Diagnostic
Cells
CellsWithAddresses
JSON
Definition at line 16 of file VVMValuePrinting.h.
Function Documentation
AppendDecimalToString()
void Verse::AppendDecimalToString (FUtf8StringBuilderBase & Builder, VFloat Float, EFloatStringFormat Format = EFloatStringFormat::ShortestOfFixedOrScientific)
References Float, Format, and ShortestOfFixedOrScientific.
AppendToString() [1/3]
void Verse::AppendToString (FUtf8StringBuilderBase & Builder, UObject * Object, EValueStringFormat Format, uint32 RecursionDepth)
References Format, and Object.
AppendToString() [2/3]
void Verse::AppendToString (VCell * Cell, FUtf8StringBuilderBase & Builder, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth = 0)
References Cell, and Format.
AppendToString() [3/3]
void Verse::AppendToString (VValue Value, FUtf8StringBuilderBase & Builder, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth = 0)
References Format, and Value.
AppendVerseToString() [1/3]
void Verse::AppendVerseToString (FUtf8StringBuilderBase & Builder, FUtf8StringView String)
References String.
AppendVerseToString() [2/3]
void Verse::AppendVerseToString (FUtf8StringBuilderBase & Builder, UTF32CHAR Char)
AppendVerseToString() [3/3]
void Verse::AppendVerseToString (FUtf8StringBuilderBase & Builder, UTF8CHAR Char)
AsFormattedString()
FString Verse::AsFormattedString (const ERuntimeDiagnostic & Diagnostic, const FText & MessageText)
References Diagnostic.
BitCeil()
size_t Verse::BitCeil (size_t X) inline constexpr
Definition at line 27 of file VVMPtrVariant.h.
References X.
GetRuntimeDiagnosticInfo()
const SRuntimeDiagnosticInfo & Verse::GetRuntimeDiagnosticInfo (const ERuntimeDiagnostic Diagnostic)
References Diagnostic.
GetTypeHash()
template<typename... Ts> uint32 Verse::GetTypeHash (TPtrVariant< Ts... > Ptr) inline
Definition at line 83 of file VVMPtrVariant.h.
References BitCast(), PointerHash(), and Verse::TPtrVariant< Ts >::RawPtr().
IsCellFormat()
bool Verse::IsCellFormat (EValueStringFormat Format) constexpr
Definition at line 25 of file VVMValuePrinting.h.
References Cells, CellsWithAddresses, and Format.
ToString() [1/2]
FUtf8String Verse::ToString (VCell * Cell, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth = 0)
References Cell, and Format.
ToString() [2/2]
FUtf8String Verse::ToString (VValue Value, FAllocationContext Context, EValueStringFormat Format, uint32 RecursionDepth = 0)
References Format, and Value.
VerseToString() [1/3]
FUtf8String Verse::VerseToString (FUtf8StringView String)
References String.
VerseToString() [2/3]
FUtf8String Verse::VerseToString (UTF32CHAR Char)
VerseToString() [3/3]
FUtf8String Verse::VerseToString (UTF8CHAR Char)
Variable Documentation
CVarEnableAssetClassRedirectors
TAutoConsoleVariable<bool> Verse::CVarEnableAssetClassRedirectors extern
CVarForceCompileFramework
TAutoConsoleVariable<bool> Verse::CVarForceCompileFramework extern
CVarUseDynamicSubobjectInstancing
TAutoConsoleVariable<bool> Verse::CVarUseDynamicSubobjectInstancing extern