Unreal Engine 5.6 C++ API: FSoundWaveProxy Class Reference
FSoundWaveProxy Class Reference
#include "SoundWave.h"
Public Member Functions
FSoundWaveProxy (const FSoundWaveProxy &Other)
FSoundWaveProxy (USoundWave *InWave)
~FSoundWaveProxy ()
FStreamedAudioChunk & GetChunk (uint32 ChunkIndex)
bool GetChunkData (int32 ChunkIndex, uint8 **OutChunkData, bool bMakeSureChunkIsLoaded=false)
int32 GetChunkFromDDC (int32 ChunkIndex, uint8 **OutChunkData, bool bMakeSureChunkIsLoaded)
FByteBulkData * GetCompressedData (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides=USoundWave::GetPlatformCompressionOverridesForCurrentPlatform())
const TArray< FSoundWaveCuePoint > & GetCuePoints () const
const TArray< FSoundWaveCuePoint > GetCuePointsAndLoopRegions () const
int32 GetCurrentChunkRevision () const
float GetDuration () const
const FName & GetFName () const
const FObjectKey & GetFObjectKey () const
ESoundWaveLoadingBehavior GetLoadingBehavior () const
const TArray< FSoundWaveCuePoint > & GetLoopRegions () const
uint32 GetNumChannels () const
uint32 GetNumChunks () const
int32 GetNumFrames () const
const FName & GetPackageName () const
const uint8 * GetResourceData () const
int32 GetResourceSize () const
const FName & GetRuntimeFormat () const
float GetSampleRate () const
uint32 GetSizeOfChunk (uint32 ChunkIndex) const
const FSoundWavePtr GetSoundWaveData ()
const TArrayView< uint8 > GetZerothChunkDataView () const
bool HasCompressedData (FName Format, ITargetPlatform *TargetPlatform=USoundWave::GetRunningPlatform()) const
IMPL_AUDIOPROXY_CLASS (FSoundWaveProxy)
bool IsLooping () const
bool IsRetainingAudio () const
bool IsSeekable () const
bool IsStreaming () const
bool IsTemplate () const
bool IsZerothChunkDataLoaded () const
bool LoadZerothChunk ()
void ReleaseCompressedAudio ()
bool ShouldUseStreamCaching () const
bool WasLoadingBehaviorOverridden () const
Static Public Member Functions
static TArrayView< const uint8 > GetZerothChunk (const FSoundWaveProxyPtr &SoundWaveProxy, bool bForImmediatePlayback=false)
Private Attributes
TSharedPtr< FSoundWaveData, ESPMode::ThreadSafe > SoundWaveDataPtr
uint32 TypeHash = uint32(INDEX_NONE)
Friends
FORCEINLINE uint32 GetTypeHash (const FSoundWaveProxy &InProxy)
Detailed Description
Definition at line 1720 of file SoundWave.h.
Constructor & Destructor Documentation
FSoundWaveProxy() [1/2]
FSoundWaveProxy::FSoundWaveProxy (USoundWave * InWave) explicit
Referenced by FSoundWaveProxy(), GetTypeHash, and IMPL_AUDIOPROXY_CLASS().
FSoundWaveProxy() [2/2]
FSoundWaveProxy::FSoundWaveProxy (const FSoundWaveProxy & Other)
References FSoundWaveProxy(), and Other.
~FSoundWaveProxy()
FSoundWaveProxy::~FSoundWaveProxy ()
Member Function Documentation
GetChunk()
FStreamedAudioChunk & FSoundWaveProxy::GetChunk (uint32 ChunkIndex)
GetChunkData()
bool FSoundWaveProxy::GetChunkData (int32 ChunkIndex, uint8 ** OutChunkData, bool bMakeSureChunkIsLoaded = false)
GetChunkFromDDC()
int32 FSoundWaveProxy::GetChunkFromDDC (int32 ChunkIndex, uint8 ** OutChunkData, bool bMakeSureChunkIsLoaded)
GetCompressedData()
FByteBulkData * FSoundWaveProxy::GetCompressedData (FName Format, const FPlatformAudioCookOverrides * CompressionOverrides = USoundWave::GetPlatformCompressionOverridesForCurrentPlatform())
References Format, and USoundWave::GetPlatformCompressionOverridesForCurrentPlatform().
GetCuePoints()
const TArray< FSoundWaveCuePoint > & FSoundWaveProxy::GetCuePoints () const
GetCuePointsAndLoopRegions()
const TArray< FSoundWaveCuePoint > FSoundWaveProxy::GetCuePointsAndLoopRegions () const
GetCurrentChunkRevision()
int32 FSoundWaveProxy::GetCurrentChunkRevision () const
GetDuration()
float FSoundWaveProxy::GetDuration () const
GetFName()
const FName & FSoundWaveProxy::GetFName () const
GetFObjectKey()
const FObjectKey & FSoundWaveProxy::GetFObjectKey () const
GetLoadingBehavior()
ESoundWaveLoadingBehavior FSoundWaveProxy::GetLoadingBehavior () const
GetLoopRegions()
const TArray< FSoundWaveCuePoint > & FSoundWaveProxy::GetLoopRegions () const
GetNumChannels()
uint32 FSoundWaveProxy::GetNumChannels () const
GetNumChunks()
uint32 FSoundWaveProxy::GetNumChunks () const
GetNumFrames()
int32 FSoundWaveProxy::GetNumFrames () const
GetPackageName()
const FName & FSoundWaveProxy::GetPackageName () const
GetResourceData()
const uint8 * FSoundWaveProxy::GetResourceData () const
GetResourceSize()
int32 FSoundWaveProxy::GetResourceSize () const
GetRuntimeFormat()
const FName & FSoundWaveProxy::GetRuntimeFormat () const
GetSampleRate()
float FSoundWaveProxy::GetSampleRate () const
GetSizeOfChunk()
uint32 FSoundWaveProxy::GetSizeOfChunk (uint32 ChunkIndex) const
GetSoundWaveData()
const FSoundWavePtr FSoundWaveProxy::GetSoundWaveData ()
GetZerothChunk()
TArrayView< const uint8 > FSoundWaveProxy::GetZerothChunk (const FSoundWaveProxyPtr & SoundWaveProxy, bool bForImmediatePlayback = false) static
GetZerothChunkDataView()
const TArrayView< uint8 > FSoundWaveProxy::GetZerothChunkDataView () const
HasCompressedData()
bool FSoundWaveProxy::HasCompressedData (FName Format, ITargetPlatform * TargetPlatform = USoundWave::GetRunningPlatform()) const
References Format, and USoundWave::GetRunningPlatform().
IMPL_AUDIOPROXY_CLASS()
FSoundWaveProxy::IMPL_AUDIOPROXY_CLASS (FSoundWaveProxy)
References FSoundWaveProxy().
IsLooping()
bool FSoundWaveProxy::IsLooping () const
IsRetainingAudio()
bool FSoundWaveProxy::IsRetainingAudio () const
IsSeekable()
bool FSoundWaveProxy::IsSeekable () const
IsStreaming()
bool FSoundWaveProxy::IsStreaming () const
IsTemplate()
bool FSoundWaveProxy::IsTemplate () const
IsZerothChunkDataLoaded()
bool FSoundWaveProxy::IsZerothChunkDataLoaded () const
LoadZerothChunk()
bool FSoundWaveProxy::LoadZerothChunk ()
ReleaseCompressedAudio()
void FSoundWaveProxy::ReleaseCompressedAudio ()
ShouldUseStreamCaching()
bool FSoundWaveProxy::ShouldUseStreamCaching () const
WasLoadingBehaviorOverridden()
bool FSoundWaveProxy::WasLoadingBehaviorOverridden () const
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FSoundWaveProxy & InProxy) friend
Definition at line 1792 of file SoundWave.h.
References FSoundWaveProxy(), FORCEINLINE, and TypeHash.
Field Documentation
SoundWaveDataPtr
TSharedPtr<FSoundWaveData, ESPMode::ThreadSafe> FSoundWaveProxy::SoundWaveDataPtr private
Definition at line 1798 of file SoundWave.h.
TypeHash
uint32 FSoundWaveProxy::TypeHash = uint32(INDEX_NONE) private
Definition at line 1799 of file SoundWave.h.
Referenced by GetTypeHash.
The documentation for this class was generated from the following file:
SoundWave.h