Unreal Engine 5.6 C++ API: UE::Dataflow Namespace Reference
UE::Dataflow Namespace Reference
Extract a named integer from the results of an ImportGEO node.
Namespaces
namespace CollectionSpreadSheetHelpers
namespace Private
Selects all the bones for the Collection.
namespace Utils
Data Structures
class FDataflowConstruction2DViewMode
class FDataflowConstruction2DViewModeBase
class FDataflowConstruction3DViewMode
class FDataflowConstruction3DViewModeBase
class FDataflowConstructionUVViewMode
class FDataflowConstructionVisualizationRegistry
class FDataflowNodeDetailExtensionHandler
This is the IDetailPropertyExtensionHandler that the DataflowToolkit actually uses.It simply calls the equivalent methods on the FDataflowNodeDetailExtensionRegistry singleton.
class FDataflowNodeDetailExtensionRegistry
Registry for IDataflowNodeDetailExtension.
class FDataflowSimulationGenerator
Dataflow simulation generator.
struct FDataflowSimulationResource
Async simulation resource that will be used while simulating.
class FDataflowSimulationTask
Simulation Task to be run on the async thread.
class FDataflowSimulationVisualizationRegistry
struct FDataflowTaskManager
Simulation Task manager.
class FDataflowToolRegistry
struct FGraphRenderingState
class FPropertyGroupCustomization
Property group customization to allow selecting of a group from a list of the groups currently held by the node's collection.
class FRenderingFactory
class FRenderingViewModeFactory
class IDataflowConstructionViewMode
class IDataflowConstructionVisualization
class IDataflowNodeDetailExtension
IDetailPropertyExtensionHandler that can be registered with FDataflowNodeDetailExtensionRegistry to be aggregated and applied to the Dataflow Node Details panel.
class IDataflowSimulationVisualization
Typedefs
typedef TPair< FString, FName > FRenderKey
Enumerations
enum class EDataflowGeneratorActions { NoAction , StartGenerate , TickGenerate }
Enum for all the generator actions.
enum class ESchemaActionSectionID : int32 { NONE = 0 , SUBGRAPHS , VARIABLES }
Functions
void ComputeSkeletonAnimation (const TObjectPtr< AActor > &PreviewActor, const float SimulationTime)
Compute the skelmesh animation at some point in time (PT)
void GeometryCollectionArrayNodes ()
void GeometryCollectionClusteringNodes ()
void GeometryCollectionConversionNodes ()
void GeometryCollectionDebugNodes ()
void GeometryCollectionEditNodes ()
void GeometryCollectionEmbedNodes ()
void GeometryCollectionEngineAssetNodes ()
void GeometryCollectionEngineNodes ()
void GeometryCollectionFieldNodes ()
void GeometryCollectionFracturingNodes ()
void GeometryCollectionMakeNodes ()
void GeometryCollectionMaterialNodes ()
void GeometryCollectionMathNodes ()
void GeometryCollectionMeshNodes ()
void GeometryCollectionOverrideNodes ()
void GeometryCollectionProcessingNodes ()
void GeometryCollectionSamplingNodes ()
void GeometryCollectionSelectionNodes ()
void GeometryCollectionUtilityNodes ()
void GeometryCollectionVerticesNodes ()
TArray< int32 > CHAOSFLESHNODES_API GetMatchingMeshIndices (const TArray< FString > &MeshNames, const FManagedArrayCollection *InCollection)
GetMatchingMeshIndices Find matching geometry names in the collection.
TArray< FIntVector3 > CHAOSFLESHNODES_API GetSurfaceTriangles (const TArray< FIntVector4 > &Tets, const bool bKeepInterior)
void PauseSkeletonAnimation (const TObjectPtr< AActor > &PreviewActor)
Pause the skelmesh animation.
void RegisterChaosFleshEngineAssetNodes ()
void RegisterChaosFleshImportGEONodes ()
void RegisterChaosFleshKinematicInitializationNodes ()
void RegisterGeometryCollectionMaterialInterfaceNodes ()
void RegisterGeometryCollectionNodesColors ()
void RegisterGeometryCollectionTextureNodes ()
void RegisterGeometryCollectionUVNodes ()
void RegisterGeometryStaticMeshToCollectionNodes ()
void RenderingCallbacks ()
Rendering callbacks for the Dataflow Rendering Factory.
void SetupSkeletonAnimation (const TObjectPtr< AActor > &PreviewActor, const bool bSkeletalMeshVisibility=true)
Setup the skelmesh animations to be used in the scene/generator.
bool ShouldResetWorld (const TObjectPtr< UDataflow > &SimulationGraph, const TObjectPtr< UWorld > &SimulationWorld, UE::Dataflow::FTimestamp &LastTimeStamp)
Check if the simulation cache nodes have changed to trigger a reset.
TObjectPtr< AActor > SpawnSimulatedActor (const TSubclassOf< AActor > &ActorClass, const TObjectPtr< AChaosCacheManager > &CacheManager, const TObjectPtr< UChaosCacheCollection > &CacheCollection, const bool bIsRecording, const TObjectPtr< UDataflowBaseContent > &DataflowContent, const FTransform &ActorTransform)
Spawn an actor given a class type and attach it to the cache manager.
void StartSkeletonAnimation (const TObjectPtr< AActor > &PreviewActor)
Start the skelmesh animation.
void StepSkeletonAnimation (const TObjectPtr< AActor > &PreviewActor)
Step the skelmesh animation.
void UpdateSkeletonAnimation (const TObjectPtr< AActor > &PreviewActor, const float SimulationTime)
Update the skelmesh animation at some point in time (GT)
Detailed Description
Extract a named integer from the results of an ImportGEO node.
Auto unwrap UVs for a specific UV channel.
Generates convex hull representation for the bones for simulation.
Create a geometry collection from a UStaticMesh.
Selects specified Vertices/Faces/Transforms in the GeometryCollection by using an attribute value Currently supported attribute types: float, int32, String, bool.
Filter a point set to only the points inside or outside of a given mesh.
Converts points into a DynamicMesh.
Converts a float to a nearest less or equal integer.
Adds Outside/Inside Materials to Outside/Inside faces Deprecated (5.6) - Use AssignMaterialToCollection node instead.
Make a array from a user defined list of material objects.
Make a literal string Deprecated (5.6)
Visualizing fracture/cluster info in fractured collection.
RadialFalloff Field Dataflow node.
Deletes selected bones from Collection.
Description for this node.
Automatically group pieces of a fractured Collection into a specified number of clusters.
Create a RootProxyMesh object (used by geometry collection assets)
Returns the specified element from an array DEPRECATED 5.6 - use the generic GetArrayElement node instead.
Extract a named integer array from the results of an ImportGEO node. Extract a named float array from the results of an ImportGEO node. Import data from GEO file.
Converts a Float array to Int array using the specified method. Returns the specified element from an array DEPRECATED 5.6 - use the generic GetArrayElement node instead Returns the number of elements in an array DEPRECATED 5.6 - use the generic GetArraySize node instead Converts a TArray<bool> to a FDataflowFaceSelection Converts a TArray<float> to a FDataflowVertexSelection Normalize the selected float data in a FloatArray Normalize all the selected vectors in a VectorArray Removes the specified element from an array Computes statistics of a float array Randomize elements in a float array (Random value will be in (RandomRangeMin, RandomRangeMax) Get size of an array Get an element from an array Append an element to an array of ManagedArrayCollections.
Create a RootProxyMesh Array (used by geometry collection assets) Get Current geometry collection asset Note : Use with caution as this may get replaced in a near future for a more generic getAsset node Get the list of the original mesh information used to create a specific geometryc collection asset each entry contains a mesh, a transform and a list of override materials create a geometry collection from a set of geometry sources
DEPRECATED 5.6 : use the new node version with a single material array output create a geometry collection from a set of geometry sources Converts a UGeometryCollection asset to an FManagedArrayCollection DEPRECATED 5.6 : use the new version that only has one material array output Converts a UGeometryCollection asset to an FManagedArrayCollection Create a geometry collection from an asset DEPRECATED 5.6 : use the new version that only has one material array output Create a geometry collection from an asset
Flattens selected bones. If no selection is provided, flattens all bones to level 1 Uncluster selected nodes Cluster selected nodes under a new parent Merge selected bones to their neighbors Merge selected bones under a new parent cluster Add a single cluster to the Geometry Collection if it only has a single transform with no clusters Cluster by grouping the selected bones with their adjacent, neighboring bones.
Description for this node Converts an Int to a String Converts a Bool to a String in a form of ("true", "false") Converts an Int to a Float Converts an Int to a Double Converts an Float to a Double Converts a Float to Int using the specified method Converts an Int to a Bool Converts a Bool to an Int
Empty clusters will be eliminated Sets all selected bone's visibilty to Visible/Hidden Merges selected bones into a single bone
BoxFalloff Field Dataflow node PlaneFalloff Field Dataflow node RadialIntMask Field Dataflow node UniformScalar Field Dataflow node UniformVector Field Dataflow node RadialVector Field Dataflow node RandomVector Field Dataflow node Noise Field Dataflow node UniformInteger Field Dataflow node WaveScalar Field Dataflow node v2 Converts a sparse FloatArray (a selected subset of the whole incoming array) into a dense FloatArray (same number of elements as the incoming array using NumSamplePositions) using the Remap input NumSamplePositions controls the size of the output array, only indices smaller than l to than NumSamplePositions will be processed
Set a float values in an array
Make a literal string Make a points array from specified points Make a box Description for this node Make a float value Deprecated (5.6) Make a float value Make a double value Make an integer value Deprecated (5.6) Make an integer value Make a bool value Deprecated(5.6) Make a bool value Make a vector Deprecated(5.6) Use MakeVector3 instead Make an FTransform Note: Originaly this version was depricated and replaced with FMakeTransformDataflowNode_v2 but when AnyRotationType was introduced with the ConvertAnyRotation node FMakeTransformDataflowNode_v2 became obsolete and this version became the current version again Make a FTransform Deprecated (5.6) Use FMakeTransformDataflowNode instead M Make an empty ManagedArrayCollection Make a Rotator Break a Transform into Translation, Rotation (Euler, Rotator, Quaternion), Scale Make a sphere mesh Make a capsule mesh Make a cylinder mesh Make a box mesh Make a plane Make a disc mesh Make a stair mesh Make a rectangle mesh Make a torus mesh
Get number of element in an material array DEPRECATED 5.6 - use the generic GetArraySize node instead Get a material interface from an existing asset Get an element from a material array (if the index does not match the range of the array, null is returned) DEPRECATED 5.6 - use the generic GetArrayElement node instead Set an element into a material array at a specific index (if the index does not match the range of the array, the array will remain unchanged) Add material(s) to an array Assign material to a set of face in a geometry collection Duplicate the given material and replace the target texture with the override texture on the newly-created material
Reassign existing material(s) to Outside/Inside faces Deprecated (5.6) - Use AssignMaterialToCollection node instead Generates a formatted string of materials from the Materials array Deprecated (5.6) Get a Material from a Materials array Deprecated (5.6) - Use GetFromMaterialArray instead Set a Material in a Materials array Deprecated (5.6) - Use SetIntoMaterialArray instead Makes a material Deprecated (5.6) Makes an empty Materials array Deprecated (5.6)
Converts a float to the nearest greater or equal integer Converts a float to the nearest integer. Rounds up when the fraction is .5 Converts a float to the nearest integer. Rounds up when the fraction is .5 Returns the fractional part of a float Returns 1, 0, or -1 depending on relation of Float to 0 Clamps X to be between Min and Max, inclusive DEPRECATED 5.6: Use the Clamp node that support all numerics types Fits a value from one range to another Returns a number between newmin and newmax that is relative to num in the range between oldmin and oldmax. If the value is outside the old range, it will be clamped to the new range. Fits a value from one range to another
Takes the value num from the range (oldmin, oldmax) and shifts it to the corresponding value in the new range (newmin, newmax). Unlike fit, this function does not clamp values in the given range. Returns log of A base Base (if Base ^ R == A, where R is ReturnValue) Returns log of A base Base (if Base ^ R == A, where R is ReturnValue) Linearly interpolates between A and B based on Alpha. (100% of A when Alpha = 0.0 and 100% of B when Alpha = 1.0) Returns the sine of A. (Expects Radians) Returns the arcsine of A. (ReturnValue is in Radians) Returns the cosine of A. (Expects Radians) Returns the arccosine of A. (ReturnValue is in Radians) Returns the cosine of A. (Expects Radians) Returns the arccosine of A. (ReturnValue is in Radians) Returns the arccosine of A. (ReturnValue is in Radians) Returns Float normalized to the given range Generates a random float Generates a random float between Min and Max Returns a random vector with length of 1 Returns a random vector with length of 1, within the specified cone, with uniform random distribution Converts radians to degrees Converts degrees to radians Offers a selection of Math constants Returns 1.0 - A Expression node for floats Expression node for floats
Base class for nodes that applying Geometry Script Mesh Processors Apply a Geometry Script Mesh Processors to an input UDynamicMesh Apply a Geometry Script Mesh Processors to the geometry of selected transforms in a geometry collection Converts a Collection to a set of Dynamic Meshes per selected Transform Append Array of Meshes to Collection Converts a BoundingBox into a DynamicMesh Collects information from the DynamicMesh and outputs it into a formatted string Converts a DynamicMesh to a Collection Converts a Collection to a DynamicMesh Converts a StaticMesh into a DynamicMesh Appends two meshes Combine two Dataflow meshes Create a UDataflow mesh from an input UDynamicMesh and material array Create a new UV layer/channel in a UDataflowMesh Split a mesh into a connected islands Split a UDataflow mesh into a UDynamicMesh and a material array Copies the same mesh with scale onto points Outputs Mesh data
Description for this node Description for this node DEPRECATED - use Print node (core nodes) Description for this node DEPRECATED - use Print node (core nodes) Description for this node Description for this node Create an array of lengths of bounding boxes (measured along an axis, diagonal, or the max/min axes) from an array of bounding boxes Description for this node Expands data of FSphere Expands a Vector into X, Y, Z components Concatenates two strings together to make a new string DEPRECATED - use new version of the same node Concatenates strings together to make a new string Generates a hash value from a string Generates a hash value from a vector Gets BoundingBoxes of pieces from a Collection Get the root node index Gets centroids of pieces from a Collection Transforms a Collection Bake transforms in Collection Transforms a mesh Comparison between integers Comparison between floats Boolean operations Branch between two mesh inputs based on boolean condition Branch between two Managed Array Collections based on Boolean condition Collects group and attribute information from the Collection and outputs it into a formatted string Sets the anchored state on the selected bones in a Collection Sets the dynamic state on the selected bones in a Collection Update the proximity (contact) graph for the bones in a Collection Sets pivot for Collection Adds custom attribute to Collection Returns number of elements in a group in a Collection Get attribute data from a Collection Get attribute data from a Collection Set attribute data in a Collection Description for this node Invert a transform. Branch between two float inputs based on boolean condition Branch between two int inputs based on boolean condition Visualize tetrahedrons in a collection Add point cloud to a collection as vertices Get vertices from a collection as a point cloud Outputs Spheres as Points and radius values
Uniform Sampling on a DynamicMesh NonUniform Sampling on a DynamicMesh VertexWeighted Sampling on a DynamicMesh
Converts GeometrySelection to VertexSelection Runs boolean operation on selection (support all selection types) Inverts selection (support all selection types) Select internal faces
Create a geometry collection from a UStaticMesh Deprecated (5.6) - use the second version of StaticMeshToCollection node with only one materials ouput
Generates cluster convex hulls for leafs hulls Generates cluster convex hulls for children hulls Clear convex hulls from a collection Copy convex hulls from given transforms on a source collection to transforms on the target collection Merge convex hulls on transforms with multiple hulls Update the Volume and Size attributes on the target Collection (and add them if they were not present) Get the sum of volumes of the convex hulls on the selected nodes Editor Fracture Mode / Utilities / TinyGeo tool Merge pieces of geometry onto their neighbors – use it to, for example, clean up too small pieces of geometry. Editor Fracture Mode / Utilities / Normals tool Recompute normals and tangents. Editor Fracture Mode / Utilities / Resample tool Resample to add collision particles in large flat regions that otherwise might have poor collision response. Only useful to help improve Particle - Implicit collisions. Editor Fracture Mode / Utilities / Validate tool Ensures that geometrycollection is valid and clean.
Merge adjacent UV Islands with similar normals for a specific UV channel Generates UVs using a box projection
Typedef Documentation
FRenderKey
typedef TPair<FString, FName> UE::Dataflow::FRenderKey
Definition at line 20 of file DataflowRenderingFactory.h.
Enumeration Type Documentation
EDataflowGeneratorActions
enum class UE::Dataflow::EDataflowGeneratorActions strong
Enum for all the generator actions.
Enumerator
NoAction
StartGenerate
TickGenerate
Definition at line 147 of file DataflowSimulationGenerator.h.
ESchemaActionSectionID
enum class UE::Dataflow::ESchemaActionSectionID : int32 strong
Enumerator
NONE
SUBGRAPHS
VARIABLES
Definition at line 20 of file DataflowGraphSchemaAction.h.
Function Documentation
ComputeSkeletonAnimation()
void UE::Dataflow::ComputeSkeletonAnimation (const TObjectPtr< AActor > & PreviewActor, const float SimulationTime)
Compute the skelmesh animation at some point in time (PT)
GeometryCollectionArrayNodes()
void UE::Dataflow::GeometryCollectionArrayNodes ()
References GeometryCollectionArrayNodes().
Referenced by GeometryCollectionArrayNodes().
GeometryCollectionClusteringNodes()
void UE::Dataflow::GeometryCollectionClusteringNodes ()
GeometryCollectionConversionNodes()
void UE::Dataflow::GeometryCollectionConversionNodes ()
GeometryCollectionDebugNodes()
void UE::Dataflow::GeometryCollectionDebugNodes ()
References GeometryCollectionDebugNodes().
Referenced by GeometryCollectionDebugNodes().
GeometryCollectionEditNodes()
void UE::Dataflow::GeometryCollectionEditNodes ()
GeometryCollectionEmbedNodes()
void UE::Dataflow::GeometryCollectionEmbedNodes ()
GeometryCollectionEngineAssetNodes()
void UE::Dataflow::GeometryCollectionEngineAssetNodes ()
References GeometryCollectionEngineAssetNodes().
Referenced by GeometryCollectionEngineAssetNodes().
GeometryCollectionEngineNodes()
void UE::Dataflow::GeometryCollectionEngineNodes ()
References GeometryCollectionEngineNodes().
Referenced by GeometryCollectionEngineNodes().
GeometryCollectionFieldNodes()
void UE::Dataflow::GeometryCollectionFieldNodes ()
GeometryCollectionFracturingNodes()
void UE::Dataflow::GeometryCollectionFracturingNodes ()
References GeometryCollectionFracturingNodes().
Referenced by GeometryCollectionFracturingNodes().
GeometryCollectionMakeNodes()
void UE::Dataflow::GeometryCollectionMakeNodes ()
References GeometryCollectionMakeNodes().
Referenced by GeometryCollectionMakeNodes().
GeometryCollectionMaterialNodes()
void UE::Dataflow::GeometryCollectionMaterialNodes ()
GeometryCollectionMathNodes()
void UE::Dataflow::GeometryCollectionMathNodes ()
References GeometryCollectionMathNodes().
Referenced by GeometryCollectionMathNodes().
GeometryCollectionMeshNodes()
void UE::Dataflow::GeometryCollectionMeshNodes ()
References GeometryCollectionMeshNodes().
Referenced by GeometryCollectionMeshNodes().
GeometryCollectionOverrideNodes()
void UE::Dataflow::GeometryCollectionOverrideNodes ()
GeometryCollectionProcessingNodes()
void UE::Dataflow::GeometryCollectionProcessingNodes ()
GeometryCollectionSamplingNodes()
void UE::Dataflow::GeometryCollectionSamplingNodes ()
References GeometryCollectionSamplingNodes().
Referenced by GeometryCollectionSamplingNodes().
GeometryCollectionSelectionNodes()
void UE::Dataflow::GeometryCollectionSelectionNodes ()
References GeometryCollectionSelectionNodes().
Referenced by GeometryCollectionSelectionNodes().
GeometryCollectionUtilityNodes()
void UE::Dataflow::GeometryCollectionUtilityNodes ()
References GeometryCollectionUtilityNodes().
Referenced by GeometryCollectionUtilityNodes().
GeometryCollectionVerticesNodes()
void UE::Dataflow::GeometryCollectionVerticesNodes ()
GetMatchingMeshIndices()
TArray< int32 > CHAOSFLESHNODES_API UE::Dataflow::GetMatchingMeshIndices (const TArray< FString > & MeshNames, const FManagedArrayCollection * InCollection)
GetMatchingMeshIndices Find matching geometry names in the collection.
If MeshNames is empty return all the geometry indices.
Parameters
MeshNames : List of name to match, or empty for all indices
Collection : Collection to search
GetSurfaceTriangles()
TArray< FIntVector3 > CHAOSFLESHNODES_API UE::Dataflow::GetSurfaceTriangles (const TArray< FIntVector4 > & Tets, const bool bKeepInterior)
PauseSkeletonAnimation()
void UE::Dataflow::PauseSkeletonAnimation (const TObjectPtr< AActor > & PreviewActor)
Pause the skelmesh animation.
RegisterChaosFleshEngineAssetNodes()
void UE::Dataflow::RegisterChaosFleshEngineAssetNodes ()
RegisterChaosFleshImportGEONodes()
void UE::Dataflow::RegisterChaosFleshImportGEONodes ()
RegisterChaosFleshKinematicInitializationNodes()
void UE::Dataflow::RegisterChaosFleshKinematicInitializationNodes ()
RegisterGeometryCollectionMaterialInterfaceNodes()
void UE::Dataflow::RegisterGeometryCollectionMaterialInterfaceNodes ()
References RegisterGeometryCollectionMaterialInterfaceNodes().
Referenced by RegisterGeometryCollectionMaterialInterfaceNodes().
RegisterGeometryCollectionNodesColors()
void UE::Dataflow::RegisterGeometryCollectionNodesColors ()
RegisterGeometryCollectionTextureNodes()
void UE::Dataflow::RegisterGeometryCollectionTextureNodes ()
References RegisterGeometryCollectionTextureNodes().
Referenced by RegisterGeometryCollectionTextureNodes().
RegisterGeometryCollectionUVNodes()
void UE::Dataflow::RegisterGeometryCollectionUVNodes ()
RegisterGeometryStaticMeshToCollectionNodes()
void UE::Dataflow::RegisterGeometryStaticMeshToCollectionNodes ()
References RegisterGeometryStaticMeshToCollectionNodes().
Referenced by RegisterGeometryStaticMeshToCollectionNodes().
RenderingCallbacks()
void UE::Dataflow::RenderingCallbacks ()
Rendering callbacks for the Dataflow Rendering Factory.
SetupSkeletonAnimation()
void UE::Dataflow::SetupSkeletonAnimation (const TObjectPtr< AActor > & PreviewActor, const bool bSkeletalMeshVisibility = true)
Setup the skelmesh animations to be used in the scene/generator.
ShouldResetWorld()
bool UE::Dataflow::ShouldResetWorld (const TObjectPtr< UDataflow > & SimulationGraph, const TObjectPtr< UWorld > & SimulationWorld, UE::Dataflow::FTimestamp & LastTimeStamp)
Check if the simulation cache nodes have changed to trigger a reset.
SpawnSimulatedActor()
TObjectPtr< AActor > UE::Dataflow::SpawnSimulatedActor (const TSubclassOf< AActor > & ActorClass, const TObjectPtr< AChaosCacheManager > & CacheManager, const TObjectPtr< UChaosCacheCollection > & CacheCollection, const bool bIsRecording, const TObjectPtr< UDataflowBaseContent > & DataflowContent, const FTransform & ActorTransform)
Spawn an actor given a class type and attach it to the cache manager.
StartSkeletonAnimation()
void UE::Dataflow::StartSkeletonAnimation (const TObjectPtr< AActor > & PreviewActor)
Start the skelmesh animation.
StepSkeletonAnimation()
void UE::Dataflow::StepSkeletonAnimation (const TObjectPtr< AActor > & PreviewActor)
Step the skelmesh animation.
UpdateSkeletonAnimation()
void UE::Dataflow::UpdateSkeletonAnimation (const TObjectPtr< AActor > & PreviewActor, const float SimulationTime)
Update the skelmesh animation at some point in time (GT)