Unreal Engine 5.6 C++ API: UE::Anim::AttributeTypes Struct Reference
UE::Anim::AttributeTypes Struct Reference
#include "AttributeTypes.h"
Public Member Functions
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAttributeTypesChanged, const UScriptStruct *, bool)
UE_DEPRECATED (5.4, "This function is no longer used, the system will initialize built-in and user-defined types at the appropriate times") static void LazyInitialize()
Static Public Member Functions
static bool CanInterpolateType (TWeakObjectPtr< const UScriptStruct > WeakStruct)
Returns whether or not the provided type can be interpolated, defaults to false when the type is not registered.
static FOnAttributeTypesChanged & GetOnAttributeTypesChanged ()
static TArray< TWeakObjectPtr< const UScriptStruct > > & GetRegisteredTypes ()
Returns all registered types.
static const IAttributeBlendOperator * GetTypeOperator (TWeakObjectPtr< const UScriptStruct > WeakStruct)
Returns the blend operator for the provided type, asserts when the type is not registered.
static bool IsTypeRegistered (const UScriptStruct *ScriptStruct)
Returns whether or not the type is registered.
template<typename AttributeType>
static void RegisterType ()
Used for registering an attribute type for which TAttributeTypeTraits::WithCustomBlendOperator is set to false, use RegisterTypeWithOperator() otherwise.
template<typename AttributeType, typename OperatorType, typename... OperatorArgs>
static void RegisterTypeWithOperator (OperatorArgs &&... args)
Used for registering an attribute type for which TAttributeTypeTraits::WithCustomBlendOperator is set to true, use RegisterType() otherwise.
template<typename AttributeType>
static void UnregisterType ()
Unregisters a specific attribute type and deletes its associated blend operator.
Static Protected Member Functions
static bool RegisterNonBlendableType (const UScriptStruct *InScriptStruct)
Register user defined structs as non-blendable animation attribute.
static void UnregisterType (const UScriptStruct *InScriptStruct)
Unregisters a specific attribute type and deletes its associated blend operator.
Static Protected Attributes
static TArray< TWeakObjectPtr< const UScriptStruct > > InterpolatableTypes
static FOnAttributeTypesChanged OnAttributeTypesChangedDelegate
static TArray< TUniquePtr< IAttributeBlendOperator > > Operators
static TArray< TWeakObjectPtr< const UScriptStruct > > RegisteredTypes
Friends
class ::UAnimationSettings
struct FAttributeTypeRegistrar
Detailed Description
Definition at line 45 of file AttributeTypes.h.
Member Function Documentation
CanInterpolateType()
bool UE::Anim::AttributeTypes::CanInterpolateType (TWeakObjectPtr< const UScriptStruct > WeakStruct) inline static
Returns whether or not the provided type can be interpolated, defaults to false when the type is not registered.
Definition at line 136 of file AttributeTypes.h.
DECLARE_MULTICAST_DELEGATE_TwoParams()
UE::Anim::AttributeTypes::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAttributeTypesChanged , const UScriptStruct * , bool)
GetOnAttributeTypesChanged()
FOnAttributeTypesChanged & UE::Anim::AttributeTypes::GetOnAttributeTypesChanged () inline static
Definition at line 65 of file AttributeTypes.h.
References OnAttributeTypesChangedDelegate.
GetRegisteredTypes()
TArray< TWeakObjectPtr< const UScriptStruct > > & UE::Anim::AttributeTypes::GetRegisteredTypes () inline static
Returns all registered types.
Definition at line 148 of file AttributeTypes.h.
GetTypeOperator()
const IAttributeBlendOperator * UE::Anim::AttributeTypes::GetTypeOperator (TWeakObjectPtr< const UScriptStruct > WeakStruct) inline static
Returns the blend operator for the provided type, asserts when the type is not registered.
Definition at line 127 of file AttributeTypes.h.
References checkf, ensure, INDEX_NONE, TWeakObjectPtr< T, TWeakObjectPtrBase >::IsValid(), and TEXT.
IsTypeRegistered()
bool UE::Anim::AttributeTypes::IsTypeRegistered (const UScriptStruct * ScriptStruct) inline static
Returns whether or not the type is registered.
Definition at line 142 of file AttributeTypes.h.
References ScriptStruct.
RegisterNonBlendableType()
bool UE::Anim::AttributeTypes::RegisterNonBlendableType (const UScriptStruct * InScriptStruct) static protected
Register user defined structs as non-blendable animation attribute.
RegisterType()
template<typename AttributeType> void UE::Anim::AttributeTypes::RegisterType () inline static
Used for registering an attribute type for which TAttributeTypeTraits::WithCustomBlendOperator is set to false, use RegisterTypeWithOperator() otherwise.
Definition at line 85 of file AttributeTypes.h.
References UE::Anim::TAttributeTypeTraitsBase< AttributeType >::IsBlendable, MakeUnique(), UE::Anim::TAttributeTypeTraitsBase< AttributeType >::RequiresNormalization, ScriptStruct, UE::Anim::TAttributeTypeTraitsBase< AttributeType >::StepInterpolate, TModels_V, and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::WithCustomBlendOperator.
RegisterTypeWithOperator()
template<typename AttributeType, typename OperatorType, typename... OperatorArgs> void UE::Anim::AttributeTypes::RegisterTypeWithOperator (OperatorArgs &&... args) inline static
Used for registering an attribute type for which TAttributeTypeTraits::WithCustomBlendOperator is set to true, use RegisterType() otherwise.
Definition at line 69 of file AttributeTypes.h.
References Forward(), MakeUnique(), ScriptStruct, UE::Anim::TAttributeTypeTraitsBase< AttributeType >::StepInterpolate, and UE::Anim::TAttributeTypeTraitsBase< AttributeType >::WithCustomBlendOperator.
UE_DEPRECATED()
UE::Anim::AttributeTypes::UE_DEPRECATED (5. 4, "This function is no longer used, the system will initialize built-in and user-defined types at the appropriate times") inline
Definition at line 62 of file AttributeTypes.h.
UnregisterType() [1/2]
template<typename AttributeType> void UE::Anim::AttributeTypes::UnregisterType () inline static
Unregisters a specific attribute type and deletes its associated blend operator.
Definition at line 112 of file AttributeTypes.h.
References INDEX_NONE, ScriptStruct, and UObjectInitialized().
UnregisterType() [2/2]
void UE::Anim::AttributeTypes::UnregisterType (const UScriptStruct * InScriptStruct) static protected
Unregisters a specific attribute type and deletes its associated blend operator.
Friends And Related Symbol Documentation
::UAnimationSettings
friend class ::UAnimationSettings friend
Definition at line 153 of file AttributeTypes.h.
FAttributeTypeRegistrar
friend struct FAttributeTypeRegistrar friend
Definition at line 154 of file AttributeTypes.h.
References FAttributeTypeRegistrar.
Referenced by FAttributeTypeRegistrar.
Field Documentation
InterpolatableTypes
TArray<TWeakObjectPtr<const UScriptStruct> > UE::Anim::AttributeTypes::InterpolatableTypes static protected
Definition at line 52 of file AttributeTypes.h.
OnAttributeTypesChangedDelegate
FOnAttributeTypesChanged UE::Anim::AttributeTypes::OnAttributeTypesChangedDelegate static protected
Definition at line 53 of file AttributeTypes.h.
Referenced by GetOnAttributeTypesChanged().
Operators
TArray<TUniquePtr<IAttributeBlendOperator> > UE::Anim::AttributeTypes::Operators static protected
Definition at line 51 of file AttributeTypes.h.
RegisteredTypes
TArray<TWeakObjectPtr<const UScriptStruct> > UE::Anim::AttributeTypes::RegisteredTypes static protected
Definition at line 50 of file AttributeTypes.h.
The documentation for this struct was generated from the following file:
AttributeTypes.h