Unreal Engine 5.6 C++ API: MidiStepSequence.h File Reference
MidiStepSequence.h File Reference
#include "IAudioProxyInitializer.h"
#include "Harmonix/AudioRenderableProxy.h"
#include "AudioRenderableAsset.h"
#include "MetasoundDataReference.h"
#include "MetasoundDataTypeRegistrationMacro.h"
#include "HarmonixMidi/MidiConstants.h"
#include "MidiStepSequence.generated.h"
Data Structures
struct Metasound::TDataReferenceTypeInfo< HarmonixMetasound::FMidiStepSequenceAsset >
struct Metasound::TDataReferenceTypeInfo< TArray< HarmonixMetasound::FMidiStepSequenceAsset > >
struct Metasound::TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FMidiStepSequenceAsset > >
struct Metasound::TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FMidiStepSequenceAsset > > >
struct TStructOpsTypeTraits< FStepSequenceNote >
Macros
#define UE_API HARMONIXMETASOUND_API
Functions
USING_AUDIORENDERABLE_PROXY (FStepSequenceTable, FStepSequenceTableProxy) namespace HarmonixMetasound
USTRUCT () struct FStepSequenceCell
Macro Definition Documentation
UE_API
#define UE_API HARMONIXMETASOUND_API
Definition at line 14 of file MidiStepSequence.h.
Function Documentation
USING_AUDIORENDERABLE_PROXY()
USING_AUDIORENDERABLE_PROXY (FStepSequenceTable , FStepSequenceTableProxy)
Definition at line 190 of file MidiStepSequence.h.
References USING_AUDIORENDERABLE_PROXY().
Referenced by USING_AUDIORENDERABLE_PROXY().
USTRUCT()
USTRUCT ()
Definition at line 19 of file MidiStepSequence.h.
References BlueprintType, Category, GENERATED_BODY, Meta, operator=(), and UPROPERTY.