Unreal Engine 5.6 C++ API: TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments > Class Template Reference
TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments > Class Template Reference
A templated pool for resources that can only be freed at a 'safe' point in the frame.
#include "ResourcePool.h"
Data Structures
class FLockScope
A scope that takes a single lock so that individual allocations / deallocations can skip it.
struct FPooledResource
Public Member Functions
TResourcePool ()=default
TResourcePool (ResourcePoolPolicy InPolicy)
Constructor with policy argument.
virtual ~TResourcePool ()
Destructor.
ResourceType CreatePooledResource (FRHICommandListBase &RHICmdList, ResourceCreationArguments Args)
Creates a pooled resource.
void DrainPool (bool bForceDrainAll)
Drain the pool of freed resources that need to be culled or prepared for reuse.
uint32 PooledSizeForCreationArguments (ResourceCreationArguments Args)
Gets the size a pooled object will use when constructed from the pool.
void ReleasePooledResource (ResourceType &&Resource)
Release a resource back into the pool.
Private Attributes
bool bLocked = false
UE::FMutex CS
uint32 LastSafeFrameNumber = INDEX_NONE
ResourcePoolPolicy Policy
Pooling policy for this resource.
TArray< FPooledResource > ResourceBuckets [ResourcePoolPolicy::NumPoolBuckets]
TArray< FPooledResource > SafeResourceBuckets [ResourcePoolPolicy::NumSafeFrames]
Detailed Description
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments>
class TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >
A templated pool for resources that can only be freed at a 'safe' point in the frame.
Definition at line 17 of file ResourcePool.h.
Constructor & Destructor Documentation
TResourcePool() [1/2]
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::TResourcePool () default
Referenced by TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::FLockScope::FLockScope(), and TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::TRenderResourcePool().
TResourcePool() [2/2]
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::TResourcePool (ResourcePoolPolicy InPolicy) inline
Constructor with policy argument.
Parameters
InPolicy An initialised policy object
Definition at line 25 of file ResourcePool.h.
References Policy.
~TResourcePool()
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> virtual TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::~TResourcePool () inline virtual
Destructor.
Definition at line 30 of file ResourcePool.h.
References DrainPool().
Member Function Documentation
CreatePooledResource()
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> ResourceType TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::CreatePooledResource (FRHICommandListBase & RHICmdList, ResourceCreationArguments Args) inline
Creates a pooled resource.
Parameters
Args the argument object for construction.
Returns
An initialised resource.
Definition at line 49 of file ResourcePool.h.
References bLocked, CS, No, TArray< InElementType, InAllocatorType >::Num(), Policy, TArray< InElementType, InAllocatorType >::Pop(), and ResourceBuckets.
Referenced by TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::CreatePooledResource(), and TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::UE_DEPRECATED().
DrainPool()
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> void TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::DrainPool (bool bForceDrainAll) inline
Drain the pool of freed resources that need to be culled or prepared for reuse.
Parameters
bForceDrainAll Clear the pool of all free resources, rather than obeying the policy
Definition at line 90 of file ResourcePool.h.
References bLocked, check, FMath::Clamp(), CS, TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::FPooledResource::FrameFreed, GFrameNumberRenderThread, INDEX_NONE, LastSafeFrameNumber, MoveTemp(), No, Num, Policy, ResourceBuckets, and SafeResourceBuckets.
Referenced by ~TResourcePool(), TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleaseRHI(), and TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::Tick().
PooledSizeForCreationArguments()
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> uint32 TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::PooledSizeForCreationArguments (ResourceCreationArguments Args) inline
Gets the size a pooled object will use when constructed from the pool.
Parameters
Args the argument object for construction.
Returns
The size for a pooled object created with Args
Definition at line 39 of file ResourcePool.h.
References Policy.
ReleasePooledResource()
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> void TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleasePooledResource (ResourceType && Resource) inline
Release a resource back into the pool.
Parameters
Resource The resource to return to the pool
Definition at line 72 of file ResourcePool.h.
References bLocked, TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::FPooledResource::BucketIndex, TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::FPooledResource::CreationArguments, CS, Forward(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::FPooledResource::FrameFreed, GFrameNumberRenderThread, MoveTemp(), Policy, TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::FPooledResource::Resource, and SafeResourceBuckets.
Referenced by TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleasePooledResource().
Field Documentation
bLocked
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> bool TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::bLocked = false private
Definition at line 208 of file ResourcePool.h.
Referenced by CreatePooledResource(), DrainPool(), and ReleasePooledResource().
CS
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> UE::FMutex TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::CS private
Definition at line 207 of file ResourcePool.h.
Referenced by TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::FLockScope::FLockScope(), CreatePooledResource(), DrainPool(), and ReleasePooledResource().
LastSafeFrameNumber
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> uint32 TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::LastSafeFrameNumber = INDEX_NONE private
Definition at line 206 of file ResourcePool.h.
Referenced by DrainPool().
Policy
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> ResourcePoolPolicy TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::Policy private
Pooling policy for this resource.
Definition at line 192 of file ResourcePool.h.
Referenced by TResourcePool(), CreatePooledResource(), DrainPool(), PooledSizeForCreationArguments(), and ReleasePooledResource().
ResourceBuckets
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> TArray<FPooledResource> TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ResourceBuckets[ResourcePoolPolicy::NumPoolBuckets] private
Definition at line 211 of file ResourcePool.h.
Referenced by CreatePooledResource(), and DrainPool().
SafeResourceBuckets
template<typename ResourceType, class ResourcePoolPolicy, class ResourceCreationArguments> TArray<FPooledResource> TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::SafeResourceBuckets[ResourcePoolPolicy::NumSafeFrames] private
Definition at line 214 of file ResourcePool.h.
Referenced by DrainPool(), and ReleasePooledResource().
The documentation for this class was generated from the following file:
ResourcePool.h