Unreal Engine 5.6 C++ API: FastTriWinding Namespace Reference
FastTriWinding Namespace Reference
Formulas for triangle winding number approximation.
Typedefs
using FMatrix3d = UE::Geometry::FMatrix3d
using FTriangle3d = UE::Geometry::FTriangle3d
Functions
template<class TriangleMeshType>
void ComputeCoeffs (const TriangleMeshType &Mesh, const TSet< int > &TriangleSet, const FMeshTriInfoCache &TriCache, FVector3d &P, double &R, FVector3d &Order1, FMatrix3d &Order2, int NumTasks=16)
precompute constant coefficients of triangle winding number approximation (evaluated in parallel for large sets of triangles) P: 'Center' of expansion for Triangles (area-weighted centroid avg) R: max distance from P to Triangles Order1: first-order vector coeff Order2: second-order matrix coeff TriCache: precomputed triangle centroid/normal/area
template<class TriangleMeshType, class IterableTriangleIndices>
void ComputeCoeffsSerial (const TriangleMeshType &Mesh, const IterableTriangleIndices &Triangles, const FMeshTriInfoCache &TriCache, FVector3d &P, double &R, FVector3d &Order1, FMatrix3d &Order2)
precompute constant coefficients of triangle winding number approximation (serial implementation) P: 'Center' of expansion for Triangles (area-weighted centroid avg) R: max distance from P to Triangles Order1: first-order vector coeff Order2: second-order matrix coeff TriCache: precomputed triangle centroid/normal/area
double EvaluateOrder1Approx (const FVector3d &Center, const FVector3d &Order1Coeff, const FVector3d &Q)
Evaluate first-order FWN approximation at point Q, relative to Center c.
double EvaluateOrder2Approx (const FVector3d &Center, const FVector3d &Order1Coeff, const FMatrix3d &Order2Coeff, const FVector3d &Q)
Evaluate second-order FWN approximation at point Q, relative to Center c.
double Order1Approx (const FTriangle3d &T, const FVector3d &P, const FVector3d &XN, double XA, const FVector3d &Q)
double Order2Approx (const FTriangle3d &T, const FVector3d &P, const FVector3d &XN, double XA, const FVector3d &Q)
Detailed Description
Formulas for triangle winding number approximation.
Typedef Documentation
FMatrix3d
using FastTriWinding::FMatrix3d = UE::Geometry::FMatrix3d
Definition at line 19 of file FastWinding.h.
FTriangle3d
using FastTriWinding::FTriangle3d = UE::Geometry::FTriangle3d
Definition at line 18 of file FastWinding.h.
Function Documentation
ComputeCoeffs()
template<class TriangleMeshType> void FastTriWinding::ComputeCoeffs (const TriangleMeshType & Mesh, const TSet< int > & TriangleSet, const FMeshTriInfoCache & TriCache, FVector3d & P, double & R, FVector3d & Order1, FMatrix3d & Order2, int NumTasks = 16)
precompute constant coefficients of triangle winding number approximation (evaluated in parallel for large sets of triangles) P: 'Center' of expansion for Triangles (area-weighted centroid avg) R: max distance from P to Triangles Order1: first-order vector coeff Order2: second-order matrix coeff TriCache: precomputed triangle centroid/normal/area
Definition at line 84 of file FastWinding.h.
References A, UE::Geometry::Area, UE::Geometry::FMeshTriInfoCache::Areas, TSet< InElementType, KeyFuncs, Allocator >::Array(), B, UE::Geometry::FMeshTriInfoCache::Centroids, check, ComputeCoeffsSerial(), UE::Geometry::DistanceSquared(), UE::Geometry::FMeshTriInfoCache::GetTriInfo(), FMath::Max, FMath::Max3(), UE::Geometry::Mesh, TArray< InElementType, InAllocatorType >::Num(), TSet< InElementType, KeyFuncs, Allocator >::Num(), UE::Geometry::ParallelTransformReduce(), and R.
Referenced by UE::Geometry::TFastWindingTree< TriangleMeshType >::make_box_fast_winding_cache().
ComputeCoeffsSerial()
template<class TriangleMeshType, class IterableTriangleIndices> void FastTriWinding::ComputeCoeffsSerial (const TriangleMeshType & Mesh, const IterableTriangleIndices & Triangles, const FMeshTriInfoCache & TriCache, FVector3d & P, double & R, FVector3d & Order1, FMatrix3d & Order2)
precompute constant coefficients of triangle winding number approximation (serial implementation) P: 'Center' of expansion for Triangles (area-weighted centroid avg) R: max distance from P to Triangles Order1: first-order vector coeff Order2: second-order matrix coeff TriCache: precomputed triangle centroid/normal/area
Definition at line 30 of file FastWinding.h.
References UE::Geometry::Area, UE::Geometry::FMeshTriInfoCache::Areas, UE::Geometry::FMeshTriInfoCache::Centroids, UE::Geometry::DistanceSquared(), UE::Geometry::FMeshTriInfoCache::GetTriInfo(), FMath::Max, FMath::Max3(), UE::Geometry::Mesh, R, UE::Geometry::TMatrix3< double >::Zero(), and UE::Math::TVector< double >::Zero().
Referenced by ComputeCoeffs().
EvaluateOrder1Approx()
double FastTriWinding::EvaluateOrder1Approx (const FVector3d & Center, const FVector3d & Order1Coeff, const FVector3d & Q) inline
Evaluate first-order FWN approximation at point Q, relative to Center c.
Definition at line 196 of file FastWinding.h.
References UE::Math::TVector< T >::Dot(), TMathUtilConstants< double >::FourPi, and UE::Math::TVector< T >::Length().
Referenced by UE::Geometry::TFastWindingTree< TriangleMeshType >::evaluate_box_fast_winding_cache().
EvaluateOrder2Approx()
double FastTriWinding::EvaluateOrder2Approx (const FVector3d & Center, const FVector3d & Order1Coeff, const FMatrix3d & Order2Coeff, const FVector3d & Q) inline
Evaluate second-order FWN approximation at point Q, relative to Center c.
Definition at line 207 of file FastWinding.h.
References UE::Math::TVector< T >::Dot(), TMathUtilConstants< double >::FourPi, UE::Geometry::TMatrix3< RealType >::InnerProduct(), UE::Math::TVector< T >::Length(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TFastWindingTree< TriangleMeshType >::evaluate_box_fast_winding_cache().
Order1Approx()
double FastTriWinding::Order1Approx (const FTriangle3d & T, const FVector3d & P, const FVector3d & XN, double XA, const FVector3d & Q) inline
Definition at line 235 of file FastWinding.h.
References UE::Math::TVector< T >::Dot(), TMathUtilConstants< double >::FourPi, and UE::Math::TVector< T >::Length().
Order2Approx()
double FastTriWinding::Order2Approx (const FTriangle3d & T, const FVector3d & P, const FVector3d & XN, double XA, const FVector3d & Q) inline
Definition at line 249 of file FastWinding.h.
References UE::Math::TVector< T >::Dot(), TMathUtilConstants< double >::FourPi, UE::Geometry::TMatrix3< RealType >::InnerProduct(), and UE::Math::TVector< T >::Length().