Unreal Engine 5.6 C++ API: FSignatureBase< InDataType > Struct Template Reference
FSignatureBase< InDataType > Struct Template Reference
#include "BigInt.h"
Public Types
typedef InDataType DataType
Public Member Functions
FSignatureBase ()
bool IsValid () const
bool operator!= (const FSignatureBase &InOther)
bool operator== (const FSignatureBase &InOther)
void Serialize (FArchive &Ar)
Static Public Member Functions
static int64 Size ()
Data Fields
DataType Data
Friends
FArchive & operator<< (FArchive &Ar, FSignatureBase &Value)
Serialization.
Detailed Description
template<class InDataType>
struct FSignatureBase< InDataType >
Definition at line 1239 of file BigInt.h.
Member Typedef Documentation
DataType
template<class InDataType> typedef InDataType FSignatureBase< InDataType >::DataType
Definition at line 1241 of file BigInt.h.
Constructor & Destructor Documentation
FSignatureBase()
template<class InDataType> FSignatureBase< InDataType >::FSignatureBase () inline
Definition at line 1245 of file BigInt.h.
References Data.
Referenced by operator!=(), operator<<, and operator==().
Member Function Documentation
IsValid()
template<class InDataType> bool FSignatureBase< InDataType >::IsValid () const inline
Definition at line 1260 of file BigInt.h.
References Data.
operator!=()
template<class InDataType> bool FSignatureBase< InDataType >::operator!= (const FSignatureBase< InDataType > & InOther) inline
Definition at line 1265 of file BigInt.h.
References FSignatureBase(), and Data.
operator==()
template<class InDataType> bool FSignatureBase< InDataType >::operator== (const FSignatureBase< InDataType > & InOther) inline
Definition at line 1270 of file BigInt.h.
References FSignatureBase(), and Data.
Serialize()
template<class InDataType> void FSignatureBase< InDataType >::Serialize (FArchive & Ar) inline
Definition at line 1250 of file BigInt.h.
References Ar, and Data.
Size()
template<class InDataType> int64 FSignatureBase< InDataType >::Size () inline static
Definition at line 1255 of file BigInt.h.
Friends And Related Symbol Documentation
operator<<
template<class InDataType> FArchive & operator<< (FArchive & Ar, FSignatureBase< InDataType > & Value) friend
Serialization.
Definition at line 1278 of file BigInt.h.
References FSignatureBase(), Ar, and Value.
Field Documentation
Data
template<class InDataType> DataType FSignatureBase< InDataType >::Data
Definition at line 1243 of file BigInt.h.
Referenced by FSignatureBase(), FEncryption::DecryptSignature(), FEncryption::EncryptSignature(), IsValid(), operator!=(), operator==(), and Serialize().
The documentation for this struct was generated from the following file:
BigInt.h