Unreal Engine 5.6 C++ API: FBlueprintActionFilter Class Reference
FBlueprintActionFilter Class Reference
#include "BlueprintActionFilter.h"
Data Structures
struct FTargetClassFilterData
A list of classes that you want members for.
Public Types
enum EFlags {
BPFILTER_NoFlags = (0) , BPFILTER_PermitDeprecated = (1<<0) , BPFILTER_RejectGlobalFields = (1<<1) , BPFILTER_RejectPermittedSubClasses = (1<<2) ,
BPFILTER_PermitRejectionSubClasses = (1<<3) , BPFILTER_RejectNonImportedFields = (1<<4) , BPFILTER_RejectIncompatibleThreadSafety = (1<<5)
}
typedef FBlueprintGraphModule::FActionMenuRejectionTest FRejectionTestDelegate
The filter uses a series of rejection tests matching.
Public Member Functions
FBlueprintActionFilter (const EFlags InFlags=BPFILTER_NoFlags)
void AddRejectionTest (FRejectionTestDelegate RejectionTestDelegate)
Users can extend the filter and add their own rejection tests with this method.
void AddRejectionTest (TSharedRef< FActionFilterTest > RejectionTest)
bool HasAllFlags (EFlags InFlags) const
bool HasAnyFlags (EFlags InFlags) const
bool IsFiltered (FBlueprintActionInfo &BlueprintAction)
Query to check and see if the specified action gets filtered out by this (and any and'd/or'd filters).
FBlueprintActionFilter const & operator&= (FBlueprintActionFilter const &Rhs)
Appends another filter to be utilized in IsFiltered() queries, extending
the query to be: IsFilteredByThis() && Rhs.IsFiltered()
FBlueprintActionFilter const & operator|= (FBlueprintActionFilter const &Rhs)
Appends another filter to be utilized in IsFiltered() queries, extending
the query to be: IsFilteredByThis() || Rhs.IsFiltered()
UE_DEPRECATED (5.1, "Please use the version that takes the EFlags type as input") FBlueprintActionFilter(uint32 const Flags)
Static Public Member Functions
static void Add (TArray< FTargetClassFilterData > &ToArray, UClass *TargetClass)
Helper to add a class to the TargetClasses, fills out FTargetClassFilterData.
static void AddUnique (TArray< FTargetClassFilterData > &ToArray, UClass *TargetClass)
Helper to add a class to the TargetClasses, TargetClass may already be in the array.
Data Fields
TSharedPtr< IAssetReferenceFilter > AssetReferenceFilter
Filter for asset references.
class FBlueprintGraphModule * BluprintGraphModule
Cached reference to the BluprintGraphModule, which has extra rejection tests:
FBlueprintActionContext Context
Contains the full blueprint/graph/pin context that this is filtering actions for.
TArray< TSubclassOf< UEdGraphNode > > PermittedNodeTypes
A list of allowed node types.
TArray< TSubclassOf< UEdGraphNode > > RejectedNodeTypes
A list of node types that should be filtered out.
TArray< FTargetClassFilterData > TargetClasses
Private Member Functions
bool IsFilteredByThis (FBlueprintActionInfo &BlueprintAction) const
Query to check and see if the specified action gets filtered out by this (does not take into consideration any and'd/or'd filters).
Private Attributes
TArray< FBlueprintActionFilter > AndFilters
Filters to be logically and'd in with the IsFilteredByThis() result.
EFlags FilterFlags = BPFILTER_NoFlags
Configuration flags for this filter.
TArray< FRejectionTestDelegate > FilterTests
Set of rejection tests for this specific filter.
TArray< FBlueprintActionFilter > OrFilters
Alternative filters to be logically or'd in with the IsFilteredByThis() result.
Detailed Description
Definition at line 242 of file BlueprintActionFilter.h.
Member Typedef Documentation
FRejectionTestDelegate
typedef FBlueprintGraphModule::FActionMenuRejectionTest FBlueprintActionFilter::FRejectionTestDelegate
The filter uses a series of rejection tests matching.
Definition at line 246 of file BlueprintActionFilter.h.
Member Enumeration Documentation
EFlags
enum FBlueprintActionFilter::EFlags
Enumerator
BPFILTER_NoFlags
BPFILTER_PermitDeprecated
Deprecated class actions will not be filtered out.
BPFILTER_RejectGlobalFields
Rejects actions associated with global/static ("persistent") fields.
However, static members of TargetClasses are kept, and not outright rejected by this (if TargetClasses is left empty, then all "persistent" fields are rejected).
BPFILTER_RejectPermittedSubClasses
Makes PermittedNodeType tests more aggressive by rejecting node sub-classes, (actions would have to explicitly match a class listed in PermittedNodeTypes).
BPFILTER_PermitRejectionSubClasses
Makes RejectedNodeType tests less aggressive by permitting node sub-classes, (actions would have to explicitly match a class listed in RejectedNodeTypes).
BPFILTER_RejectNonImportedFields
Actions that reference member variables or functions that belong to a struct that exists outside the scope of the current set of imported namespaces will be filtered out.
BPFILTER_RejectIncompatibleThreadSafety
Rejects actions that would spawn nodes with thread safety characteristics that are incompatible with the specification of the containing graph.
Definition at line 248 of file BlueprintActionFilter.h.
Constructor & Destructor Documentation
FBlueprintActionFilter()
FBlueprintActionFilter::FBlueprintActionFilter (const EFlags InFlags = BPFILTER_NoFlags)
Parameters
InFlags - Filter configuration flags.
References BPFILTER_NoFlags.
Referenced by operator&=(), operator|=(), and UE_DEPRECATED().
Member Function Documentation
Add()
void FBlueprintActionFilter::Add (TArray< FTargetClassFilterData > & ToArray, UClass * TargetClass) static
Helper to add a class to the TargetClasses, fills out FTargetClassFilterData.
AddRejectionTest() [1/2]
void FBlueprintActionFilter::AddRejectionTest (FRejectionTestDelegate RejectionTestDelegate)
Users can extend the filter and add their own rejection tests with this method.
We use rejection "IsFiltered" tests rather than inclusive tests because it is more optimal to whittle down the list of actions early.
Parameters
RejectionTestDelegate The rejection test you wish to add to this filter.
AddRejectionTest() [2/2]
void FBlueprintActionFilter::AddRejectionTest (TSharedRef< FActionFilterTest > RejectionTest)
Parameters
RejectionTest a test this filter will run to cull blueprint actions
Flags List of flags that will be added in the provided rejection test
AddUnique()
void FBlueprintActionFilter::AddUnique (TArray< FTargetClassFilterData > & ToArray, UClass * TargetClass) static
Helper to add a class to the TargetClasses, TargetClass may already be in the array.
HasAllFlags()
bool FBlueprintActionFilter::HasAllFlags (EFlags InFlags) const inline
Returns
TRUE if all of the given configuration flags are set on this filter.
Definition at line 407 of file BlueprintActionFilter.h.
References FilterFlags.
HasAnyFlags()
bool FBlueprintActionFilter::HasAnyFlags (EFlags InFlags) const inline
Returns
TRUE if any of the given configuration flags are set on this filter.
Definition at line 399 of file BlueprintActionFilter.h.
References FilterFlags.
IsFiltered()
bool FBlueprintActionFilter::IsFiltered (FBlueprintActionInfo & BlueprintAction)
Query to check and see if the specified action gets filtered out by this (and any and'd/or'd filters).
NOT marked const to keep FIsFilteredDelegates from recursively calling.
Parameters
BlueprintAction The node-spawner you wish to test.
Returns
False if the action passes the filter, otherwise false (the action got filtered out).
IsFilteredByThis()
bool FBlueprintActionFilter::IsFilteredByThis (FBlueprintActionInfo & BlueprintAction) const private
Query to check and see if the specified action gets filtered out by this (does not take into consideration any and'd/or'd filters).
Parameters
BlueprintAction The node-spawner you wish to test.
Returns
False if the action passes the filter, otherwise true (the action got filtered out).
operator&=()
FBlueprintActionFilter const & FBlueprintActionFilter::operator&= (FBlueprintActionFilter const & Rhs)
Appends another filter to be utilized in IsFiltered() queries, extending
the query to be: IsFilteredByThis() && Rhs.IsFiltered()
NOTE: Appending additional filters can hinder performance (as the additional filter has to loop over its tests foreach database entry)
Parameters
Rhs The filter to append to this one.
Returns
This.
References FBlueprintActionFilter().
operator|=()
FBlueprintActionFilter const & FBlueprintActionFilter::operator|= (FBlueprintActionFilter const & Rhs)
Appends another filter to be utilized in IsFiltered() queries, extending
the query to be: IsFilteredByThis() || Rhs.IsFiltered()
NOTE: Appending additional filters can hinder performance (as the additional filter has to loop over its tests foreach database entry)
Parameters
Rhs The filter to append to this one.
Returns
This.
References FBlueprintActionFilter().
UE_DEPRECATED()
FBlueprintActionFilter::UE_DEPRECATED (5. 1, "Please use the version that takes the EFlags type as input") const
References FBlueprintActionFilter(), and Flags.
Field Documentation
AndFilters
TArray<FBlueprintActionFilter> FBlueprintActionFilter::AndFilters private
Filters to be logically and'd in with the IsFilteredByThis() result.
Definition at line 435 of file BlueprintActionFilter.h.
AssetReferenceFilter
TSharedPtr<IAssetReferenceFilter> FBlueprintActionFilter::AssetReferenceFilter
Filter for asset references.
Definition at line 345 of file BlueprintActionFilter.h.
BluprintGraphModule
class FBlueprintGraphModule* FBlueprintActionFilter::BluprintGraphModule
Cached reference to the BluprintGraphModule, which has extra rejection tests:
Definition at line 342 of file BlueprintActionFilter.h.
Context
FBlueprintActionContext FBlueprintActionFilter::Context
Contains the full blueprint/graph/pin context that this is filtering actions for.
Definition at line 301 of file BlueprintActionFilter.h.
FilterFlags
EFlags FBlueprintActionFilter::FilterFlags = BPFILTER_NoFlags private
Configuration flags for this filter.
Definition at line 429 of file BlueprintActionFilter.h.
Referenced by HasAllFlags(), and HasAnyFlags().
FilterTests
TArray<FRejectionTestDelegate> FBlueprintActionFilter::FilterTests private
Set of rejection tests for this specific filter.
Definition at line 432 of file BlueprintActionFilter.h.
OrFilters
TArray<FBlueprintActionFilter> FBlueprintActionFilter::OrFilters private
Alternative filters to be logically or'd in with the IsFilteredByThis() result.
Definition at line 438 of file BlueprintActionFilter.h.
PermittedNodeTypes
TArray< TSubclassOf<UEdGraphNode> > FBlueprintActionFilter::PermittedNodeTypes
A list of allowed node types.
If a spawner's NodeClass isn't one of these types, then it is filtered out. Use the "RejectPermittedNodeSubClasses" flag to aggressively filter out child classes as well (enforcing an explicit match).
Definition at line 309 of file BlueprintActionFilter.h.
RejectedNodeTypes
TArray< TSubclassOf<UEdGraphNode> > FBlueprintActionFilter::RejectedNodeTypes
A list of node types that should be filtered out.
If a node class is listed both here and in PermittedNodeTypes, then the exclusion wins (it will be filtered out).
Definition at line 316 of file BlueprintActionFilter.h.
TargetClasses
TArray<FTargetClassFilterData> FBlueprintActionFilter::TargetClasses
Definition at line 333 of file BlueprintActionFilter.h.
The documentation for this class was generated from the following file:
BlueprintActionFilter.h