Unreal Engine 5.6 C++ API: TCommonReplicator_SP< InModelDef > Class Template Reference
TCommonReplicator_SP< InModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Public Types
using ModelDef = InModelDef
Static Public Member Functions
template<typename ClientRecvDataType>
static void NetRecv (const FNetSerializeParams &P, ClientRecvDataType &ClientRecvState, TModelDataStore< ModelDef > *DataStore)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, TInstanceData< ModelDef > *InstanceData, int32 PendingFrame)
Detailed Description
template<typename InModelDef>
class TCommonReplicator_SP< InModelDef >
Definition at line 533 of file NetworkPredictionSerialization.h.
Member Typedef Documentation
ModelDef
template<typename InModelDef> using TCommonReplicator_SP< InModelDef >::ModelDef = InModelDef
Definition at line 537 of file NetworkPredictionSerialization.h.
Member Function Documentation
NetRecv()
template<typename InModelDef> template<typename ClientRecvDataType> void TCommonReplicator_SP< InModelDef >::NetRecv (const FNetSerializeParams & P, ClientRecvDataType & ClientRecvState, TModelDataStore< ModelDef > * DataStore) inline static
Definition at line 540 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, FNetworkPredictionDriverBase< ModelDef >::PhysicsNetRecv(), UE_NP_TRACE_PHYSICS_STATE_RECV, UE_NP_TRACE_USER_STATE_AUX, UE_NP_TRACE_USER_STATE_INPUT, and UE_NP_TRACE_USER_STATE_SYNC.
Referenced by TFixedTickReplicator_SP< InModelDef >::NetRecv(), and TIndependentTickReplicator_SP< InModelDef >::NetRecv().
NetSend()
template<typename InModelDef> void TCommonReplicator_SP< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, TInstanceData< ModelDef > * InstanceData, int32 PendingFrame) inline static
Definition at line 557 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, TInstanceFrameState< ModelDef >::FFrame::AuxState, TInstanceFrameState< ModelDef >::Buffer, TModelDataStore< ModelDef >::Frames, ID, TInstanceData< ModelDef >::Info, TInstanceFrameState< ModelDef >::FFrame::InputCmd, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, npCheckSlow, FNetworkPredictionDriverBase< ModelDef >::PhysicsNetSend(), and TInstanceFrameState< ModelDef >::FFrame::SyncState.
Referenced by TFixedTickReplicator_SP< InModelDef >::NetSend(), and TIndependentTickReplicator_SP< InModelDef >::NetSend().
The documentation for this class was generated from the following file:
NetworkPredictionSerialization.h