Unreal Engine 5.6 C++ API: UE::Sequencer::FEditorViewModel Class Reference
UE::Sequencer::FEditorViewModel Class Reference
This represents to root view-model for a sequencer-like editor.
#include "EditorViewModel.h"
Public Member Functions
FEditorViewModel ()
Builds a new editor view model.
~FEditorViewModel ()
Destroys this editor view model.
FViewModelChildren GetEditorPanels ()
Gets the editor panels' view models.
TSharedPtr< FOutlinerViewModel > GetOutliner () const
Gets the outliner view-model.
FViewModelPtr GetRootModel () const
Gets the root view-model of the sequence being edited.
USequencerScriptingLayer * GetScriptingLayer () const
Gets the scripting layer.
TSharedPtr< FSequencerCoreSelection > GetSelection () const
Gets the selection class.
TSharedPtr< FTrackAreaViewModel > GetTrackArea () const
Gets the track area view-model.
FViewDensityInfo GetViewDensity () const
Returns the current view density for this editor.
void InitializeEditor ()
Initializes the outliner and track-area for this editor.
bool IsEditable () const
Returns the inverse of read-only - useful for direct bindings to IsEnabled for widgets.
virtual bool IsReadOnly () const
Returns whether this editor is currently read-only.
void SetViewDensity (const FViewDensityInfo &InViewDensity)
Returns the current view density for this editor.
UE_SEQUENCER_DECLARE_CASTABLE (FEditorViewModel, FViewModel)
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Static Public Member Functions
static EViewModelListType GetEditorPanelType ()
Children type for editor panels.
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Protected Member Functions
virtual TSharedPtr< FOutlinerViewModel > CreateOutlinerImpl ()
Creates the outliner for this editor.
virtual TSharedPtr< FViewModel > CreateRootModelImpl ()
Creates the root data model for this editor.
virtual USequencerScriptingLayer * CreateScriptingLayerImpl ()
Creates the scripting layer class for this editor.
virtual TSharedPtr< FSequencerCoreSelection > CreateSelectionImpl ()
Creates the selection class for this editor.
virtual TSharedPtr< FTrackAreaViewModel > CreateTrackAreaImpl ()
Creates the track-area for this editor.
virtual void InitializeEditorImpl ()
Creates any other panels for this editor.
virtual void PreInitializeEditorImpl ()
Initializes this view model before panels and root models are created.
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Private Attributes
TSharedPtr< FOutlinerViewModel > Outliner
Cached pointer to the outliner panel view-model.
FViewModelListHead PanelList
List of panel view-models for this editor.
TSharedPtr< FViewModel > RootDataModel
The root view-model for the data being edited.
TStrongObjectPtr< USequencerScriptingLayer > ScriptingLayer
Cached pointer to the scripting layer class.
TSharedPtr< FSequencerCoreSelection > Selection
Cached pointer to the selection class.
TSharedPtr< FTrackAreaViewModel > TrackArea
Cached pointer to the track area panel view-model.
FViewDensityInfo ViewDensity
This editor's current view density defining how condensed the elements appear.
Friends
class FOutlinerViewModel
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Detailed Description
This represents to root view-model for a sequencer-like editor.
This view-model assumes that the editor includes at least an outliner area and a track area. Other panels in the editor can be added to the list of panels.
The data being edited is represented by a root view-model which doesn't change: if the editor needs to edit a different piece of data, this should change inside the root view-model, and call the necessary code to refresh the entire view-model hierarchy. Note that this root view-model is not parented under the editor view-model.
Definition at line 39 of file EditorViewModel.h.
Constructor & Destructor Documentation
FEditorViewModel()
UE::Sequencer::FEditorViewModel::FEditorViewModel ()
Builds a new editor view model.
Referenced by UE_SEQUENCER_DECLARE_CASTABLE(), and UE::Sequencer::FSequencerEditorViewModel::UE_SEQUENCER_DECLARE_CASTABLE().
~FEditorViewModel()
UE::Sequencer::FEditorViewModel::~FEditorViewModel ()
Destroys this editor view model.
Member Function Documentation
CreateOutlinerImpl()
virtual TSharedPtr< FOutlinerViewModel > UE::Sequencer::FEditorViewModel::CreateOutlinerImpl () protected virtual
Creates the outliner for this editor.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
CreateRootModelImpl()
virtual TSharedPtr< FViewModel > UE::Sequencer::FEditorViewModel::CreateRootModelImpl () protected virtual
Creates the root data model for this editor.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
CreateScriptingLayerImpl()
virtual USequencerScriptingLayer * UE::Sequencer::FEditorViewModel::CreateScriptingLayerImpl () protected virtual
Creates the scripting layer class for this editor.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
CreateSelectionImpl()
virtual TSharedPtr< FSequencerCoreSelection > UE::Sequencer::FEditorViewModel::CreateSelectionImpl () protected virtual
Creates the selection class for this editor.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
CreateTrackAreaImpl()
virtual TSharedPtr< FTrackAreaViewModel > UE::Sequencer::FEditorViewModel::CreateTrackAreaImpl () protected virtual
Creates the track-area for this editor.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
GetEditorPanels()
FViewModelChildren UE::Sequencer::FEditorViewModel::GetEditorPanels ()
Gets the editor panels' view models.
References UE::Sequencer::FViewModel::FViewModelChildren.
GetEditorPanelType()
EViewModelListType UE::Sequencer::FEditorViewModel::GetEditorPanelType () static
Children type for editor panels.
GetOutliner()
TSharedPtr< FOutlinerViewModel > UE::Sequencer::FEditorViewModel::GetOutliner () const
Gets the outliner view-model.
GetRootModel()
FViewModelPtr UE::Sequencer::FEditorViewModel::GetRootModel () const
Gets the root view-model of the sequence being edited.
GetScriptingLayer()
USequencerScriptingLayer * UE::Sequencer::FEditorViewModel::GetScriptingLayer () const
Gets the scripting layer.
GetSelection()
TSharedPtr< FSequencerCoreSelection > UE::Sequencer::FEditorViewModel::GetSelection () const
Gets the selection class.
GetTrackArea()
TSharedPtr< FTrackAreaViewModel > UE::Sequencer::FEditorViewModel::GetTrackArea () const
Gets the track area view-model.
GetViewDensity()
FViewDensityInfo UE::Sequencer::FEditorViewModel::GetViewDensity () const
Returns the current view density for this editor.
InitializeEditor()
void UE::Sequencer::FEditorViewModel::InitializeEditor ()
Initializes the outliner and track-area for this editor.
InitializeEditorImpl()
virtual void UE::Sequencer::FEditorViewModel::InitializeEditorImpl () inline protected virtual
Creates any other panels for this editor.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
Definition at line 105 of file EditorViewModel.h.
IsEditable()
bool UE::Sequencer::FEditorViewModel::IsEditable () const inline
Returns the inverse of read-only - useful for direct bindings to IsEnabled for widgets.
Definition at line 85 of file EditorViewModel.h.
References IsReadOnly().
IsReadOnly()
virtual bool UE::Sequencer::FEditorViewModel::IsReadOnly () const virtual
Returns whether this editor is currently read-only.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
Referenced by IsEditable().
PreInitializeEditorImpl()
virtual void UE::Sequencer::FEditorViewModel::PreInitializeEditorImpl () inline protected virtual
Initializes this view model before panels and root models are created.
Reimplemented in UE::Sequencer::FSequencerEditorViewModel.
Definition at line 93 of file EditorViewModel.h.
SetViewDensity()
void UE::Sequencer::FEditorViewModel::SetViewDensity (const FViewDensityInfo & InViewDensity)
Returns the current view density for this editor.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FEditorViewModel::UE_SEQUENCER_DECLARE_CASTABLE (FEditorViewModel , FViewModel)
References FEditorViewModel(), and UE::Sequencer::FViewModel::FViewModel().
Friends And Related Symbol Documentation
FOutlinerViewModel
friend class FOutlinerViewModel friend
Definition at line 109 of file EditorViewModel.h.
References FOutlinerViewModel.
Referenced by FOutlinerViewModel.
Field Documentation
Outliner
TSharedPtr<FOutlinerViewModel> UE::Sequencer::FEditorViewModel::Outliner private
Cached pointer to the outliner panel view-model.
Definition at line 115 of file EditorViewModel.h.
PanelList
FViewModelListHead UE::Sequencer::FEditorViewModel::PanelList private
List of panel view-models for this editor.
Definition at line 112 of file EditorViewModel.h.
RootDataModel
TSharedPtr<FViewModel> UE::Sequencer::FEditorViewModel::RootDataModel private
The root view-model for the data being edited.
Definition at line 124 of file EditorViewModel.h.
ScriptingLayer
TStrongObjectPtr<USequencerScriptingLayer> UE::Sequencer::FEditorViewModel::ScriptingLayer private
Cached pointer to the scripting layer class.
Definition at line 121 of file EditorViewModel.h.
Selection
TSharedPtr<FSequencerCoreSelection> UE::Sequencer::FEditorViewModel::Selection private
Cached pointer to the selection class.
Definition at line 119 of file EditorViewModel.h.
TrackArea
TSharedPtr<FTrackAreaViewModel> UE::Sequencer::FEditorViewModel::TrackArea private
Cached pointer to the track area panel view-model.
Definition at line 117 of file EditorViewModel.h.
ViewDensity
FViewDensityInfo UE::Sequencer::FEditorViewModel::ViewDensity private
This editor's current view density defining how condensed the elements appear.
Definition at line 127 of file EditorViewModel.h.
The documentation for this class was generated from the following file:
EditorViewModel.h