Unreal Engine 5.6 C++ API: FConstPawnIterator Class Reference
FConstPawnIterator Class Reference
Imitation iterator class that attempts to provide the basic interface that FConstPawnIterator previously did when a typedef of TArray<TWeakObjectPtr<APawn>>::Iterator.
#include "PawnIterator.h"
Public Member Functions
FConstPawnIterator (FConstPawnIterator &&)
~FConstPawnIterator ()
operator bool () const
FPawnIteratorObject operator* () const
FConstPawnIterator & operator++ ()
FConstPawnIterator & operator++ (int)
TUniquePtr< FPawnIteratorObject > operator-> () const
FConstPawnIterator & operator= (FConstPawnIterator &&)
UE_DEPRECATED (4.23, "Decrement operator no longer means anything on a pawn iterator") FConstPawnIterator &operator--()
UE_DEPRECATED (4.23, "Decrement operator no longer means anything on a pawn iterator") FConstPawnIterator &operator--(int)
Private Member Functions
FConstPawnIterator (UWorld *World)
Private Attributes
TUniquePtr< TActorIterator< APawn > > Iterator
friend UWorld
Detailed Description
Imitation iterator class that attempts to provide the basic interface that FConstPawnIterator previously did when a typedef of TArray<TWeakObjectPtr<APawn>>::Iterator.
In general you should prefer not to use this iterator and instead use TActorIterator<APawn> or TActorRange<APawn> (or the desired more derived type). This iterator will likely be deprecated in a future release.
Definition at line 41 of file PawnIterator.h.
Constructor & Destructor Documentation
FConstPawnIterator() [1/2]
FConstPawnIterator::FConstPawnIterator (UWorld * World) private
References UWorld.
Referenced by FConstPawnIterator(), operator++(), operator++(), operator=(), UE_DEPRECATED(), and UE_DEPRECATED().
~FConstPawnIterator()
FConstPawnIterator::~FConstPawnIterator ()
FConstPawnIterator() [2/2]
FConstPawnIterator::FConstPawnIterator (FConstPawnIterator &&)
References FConstPawnIterator().
Member Function Documentation
operator bool()
FConstPawnIterator::operator bool () const explicit
operator*()
FPawnIteratorObject FConstPawnIterator::operator* () const
operator++() [1/2]
FConstPawnIterator & FConstPawnIterator::operator++ ()
References FConstPawnIterator().
operator++() [2/2]
FConstPawnIterator & FConstPawnIterator::operator++ (int)
References FConstPawnIterator().
operator->()
TUniquePtr< FPawnIteratorObject > FConstPawnIterator::operator-> () const
operator=()
FConstPawnIterator & FConstPawnIterator::operator= (FConstPawnIterator &&)
References FConstPawnIterator().
UE_DEPRECATED() [1/2]
FConstPawnIterator::UE_DEPRECATED (4. 23, "Decrement operator no longer means anything on a pawn iterator") & inline
Definition at line 58 of file PawnIterator.h.
References FConstPawnIterator().
UE_DEPRECATED() [2/2]
FConstPawnIterator::UE_DEPRECATED (4. 23, "Decrement operator no longer means anything on a pawn iterator") & inline
Definition at line 60 of file PawnIterator.h.
References FConstPawnIterator().
Field Documentation
Iterator
TUniquePtr<TActorIterator<APawn> > FConstPawnIterator::Iterator private
Definition at line 64 of file PawnIterator.h.
UWorld
friend FConstPawnIterator::UWorld private
Definition at line 66 of file PawnIterator.h.
Referenced by FConstPawnIterator().
The documentation for this class was generated from the following file:
PawnIterator.h