Unreal Engine 5.6 C++ Documentation: URotatingMovementComponent Class Reference
URotatingMovementComponent Class Reference
Performs continuous rotation of a component at a specific rotation rate.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RotatingMovementComponent.h>
Public Member Functions
virtual void RegisterComponentTickFunctions (bool bRegister) override
virtual void PostLoad () override
virtual void Deactivate () override
virtual void Serialize (FArchive &Ar) override
virtual void InitializeComponent () override
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
virtual void OnRegister () override
Overridden to update component properties that should be updated while being edited.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual float GetGravityZ () const
Returns gravity that affects this component.
virtual float GetMaxSpeed () const
Returns maximum speed of component in current movement mode.
virtual bool IsExceedingMaxSpeed (float MaxSpeed) const
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
virtual void StopMovementImmediately ()
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
virtual bool ShouldSkipUpdate (float DeltaTime) const
Possibly skip update if moved component is not rendered or can't move.
virtual APhysicsVolume * GetPhysicsVolume () const
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
virtual void PhysicsVolumeChanged (class APhysicsVolume *NewVolume)
Delegate when PhysicsVolume of UpdatedComponent has been changed.
virtual void SetUpdatedComponent (USceneComponent *NewUpdatedComponent)
Assign the component we move and update.
virtual bool IsInWater () const
Returns true if it's in PhysicsVolume with water flag.
virtual void UpdateTickRegistration ()
Update tick registration state, determined by bAutoUpdateTickRegistration.
virtual void HandleImpact (const FHitResult &Hit, float TimeSlice=0.f, const FVector &MoveDelta=FVector::ZeroVector)
Called for Blocking impact.
virtual void UpdateComponentVelocity ()
Update ComponentVelocity of UpdatedComponent.
virtual void InitCollisionParams (FCollisionQueryParams &OutParams, FCollisionResponseParams &OutResponseParam) const
Initialize collision params appropriately based on our collision settings.
virtual bool OverlapTest (const FVector &Location, const FQuat &RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape &CollisionShape, const AActor *IgnoreActor) const
Return true if the given collision shape overlaps other geometry at the given location and rotation.
bool MoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool MoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
bool K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult &OutHit, bool bSweep=true, bool bTeleport=false)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool SafeMoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
bool SafeMoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
virtual FVector GetPenetrationAdjustment (const FHitResult &Hit) const
Calculate a movement adjustment to try to move out of a penetration from a failed move.
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation)
Try to move out of penetration in an object after a failed move.
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FRotator &NewRotation)
virtual FVector ComputeSlideVector (const FVector &Delta, const float Time, const FVector &Normal, const FHitResult &Hit) const
Compute a vector to slide along a surface, given an attempted move, time, and normal.
virtual float SlideAlongSurface (const FVector &Delta, float Time, const FVector &Normal, FHitResult &Hit, bool bHandleImpact=false)
Slide smoothly along a surface, and slide away from multiple impacts using TwoWallAdjust if necessary.
virtual void TwoWallAdjust (FVector &Delta, const FHitResult &Hit, const FVector &OldHitNormal) const
Compute a movement direction when contacting two surfaces.
virtual void AddRadialForce (const FVector &Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff)
Adds force from radial force components.
virtual void AddRadialImpulse (const FVector &Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange)
Adds impulse from radial force components.
virtual void SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting)
Set the plane constraint axis setting.
EPlaneConstraintAxisSetting GetPlaneConstraintAxisSetting () const
Get the plane constraint axis setting.
virtual void SetPlaneConstraintNormal (FVector PlaneNormal)
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintFromVectors (FVector Forward, FVector Up)
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintOrigin (FVector PlaneOrigin)
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintEnabled (bool bEnabled)
Sets whether or not the plane constraint is enabled.
const FVector & GetPlaneConstraintNormal () const
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
const FVector & GetPlaneConstraintOrigin () const
Get the plane constraint origin.
virtual FVector ConstrainDirectionToPlane (FVector Direction) const
Constrain a direction vector to the plane constraint, if enabled.
virtual FVector ConstrainLocationToPlane (FVector Location) const
Constrain a position vector to the plane constraint, if enabled.
virtual FVector ConstrainNormalToPlane (FVector Normal) const
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
virtual void SnapUpdatedComponentToPlane ()
Snap the updated component to the plane constraint, if enabled.
virtual void OnTeleported ()
Called by owning Actor upon successful teleport from AActor::TeleportTo().
Static Public Member Functions
static void PhysicsLockedAxisSettingChanged ()
Public Attributes
uint8 bUpdateOnlyIfRendered:1
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
uint8 bAutoUpdateTickRegistration:1
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
uint8 bTickBeforeOwner:1
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
uint8 bAutoRegisterUpdatedComponent:1
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
uint8 bConstrainToPlane:1
If true, movement will be constrained to a plane.
uint8 bSnapToPlaneAtStart:1
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
uint8 bAutoRegisterPhysicsVolumeUpdates:1
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
uint8 bComponentShouldUpdatePhysicsVolume:1
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Protected Member Functions
FVector GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const
Helper to compute the plane constraint axis from the current setting.
virtual bool MoveUpdatedComponentImpl (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
virtual bool ResolvePenetrationImpl (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation)
Protected Attributes
FVector PlaneConstraintNormal
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
FVector PlaneConstraintOrigin
The origin of the plane that constrains movement, if plane constraint is enabled.
Detailed Description
Performs continuous rotation of a component at a specific rotation rate.
Rotation can optionally be offset around a pivot point. Collision testing is not performed during movement.
Definition at line 15 of file RotatingMovementComponent.h.
Member Function Documentation
AddRadialForce()
virtual void UMovementComponent::AddRadialForce (const FVector & Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff) virtual inherited
Adds force from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
Reimplemented in UCharacterMovementComponent.
References AddRadialForce().
AddRadialImpulse()
virtual void UMovementComponent::AddRadialImpulse (const FVector & Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange) virtual inherited
Adds impulse from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
bVelChange If true, the Strength is taken as a change in velocity instead of an impulse (ie. mass will have no effect).
Reimplemented in UCharacterMovementComponent.
References AddRadialImpulse().
ComputeSlideVector()
virtual FVector UMovementComponent::ComputeSlideVector (const FVector & Delta, const float Time, const FVector & Normal, const FHitResult & Hit) const virtual inherited
Compute a vector to slide along a surface, given an attempted move, time, and normal.
Parameters
Delta Attempted move.
Time Amount of move to apply (between 0 and 1).
Normal Normal opposed to movement. Not necessarily equal to Hit.Normal.
Hit HitResult of the move that resulted in the slide.
Reimplemented in UCharacterMovementComponent.
References ComputeSlideVector().
ConstrainDirectionToPlane()
virtual FVector UMovementComponent::ConstrainDirectionToPlane (FVector Direction) const virtual inherited
Constrain a direction vector to the plane constraint, if enabled.
See also
SetPlaneConstraint
References ConstrainDirectionToPlane().
ConstrainLocationToPlane()
virtual FVector UMovementComponent::ConstrainLocationToPlane (FVector Location) const virtual inherited
Constrain a position vector to the plane constraint, if enabled.
References ConstrainLocationToPlane(), and Location.
ConstrainNormalToPlane()
virtual FVector UMovementComponent::ConstrainNormalToPlane (FVector Normal) const virtual inherited
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
References ConstrainNormalToPlane().
Deactivate()
virtual void UMovementComponent::Deactivate () override virtual inherited
Reimplemented in UCharacterMovementComponent.
GetGravityZ()
virtual float UMovementComponent::GetGravityZ () const virtual inherited
Returns gravity that affects this component.
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
References GetGravityZ(), and GetMaxSpeed().
GetMaxSpeed()
float UMovementComponent::GetMaxSpeed () const inline virtual inherited
Returns maximum speed of component in current movement mode.
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
Definition at line 466 of file MovementComponent.h.
GetPenetrationAdjustment()
virtual FVector UMovementComponent::GetPenetrationAdjustment (const FHitResult & Hit) const virtual inherited
Calculate a movement adjustment to try to move out of a penetration from a failed move.
Parameters
Hit the result of the failed move
Returns
The adjustment to use after a failed move, or a zero vector if no attempt should be made.
Reimplemented in UCharacterMovementComponent.
References GetPenetrationAdjustment(), and ResolvePenetration().
GetPhysicsVolume()
virtual APhysicsVolume * UMovementComponent::GetPhysicsVolume () const virtual inherited
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
References GetPhysicsVolume().
GetPlaneConstraintAxisSetting()
EPlaneConstraintAxisSetting UMovementComponent::GetPlaneConstraintAxisSetting () const inline inherited
Get the plane constraint axis setting.
Definition at line 477 of file MovementComponent.h.
References EPlaneConstraintAxisSetting.
GetPlaneConstraintNormal()
const FVector & UMovementComponent::GetPlaneConstraintNormal () const inherited
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
References GetPlaneConstraintNormal().
GetPlaneConstraintNormalFromAxisSetting()
FVector UMovementComponent::GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const protected inherited
Helper to compute the plane constraint axis from the current setting.
Parameters
AxisSetting Setting to use when computing the axis.
Returns
Plane constraint axis/normal.
References EPlaneConstraintAxisSetting, and GetPlaneConstraintNormalFromAxisSetting().
GetPlaneConstraintOrigin()
const FVector & UMovementComponent::GetPlaneConstraintOrigin () const inherited
Get the plane constraint origin.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
Returns
The origin of the plane that constrains movement, if the plane constraint is enabled.
References GetPlaneConstraintOrigin().
HandleImpact()
virtual void UMovementComponent::HandleImpact (const FHitResult & Hit, float TimeSlice = 0.f, const FVector & MoveDelta = FVector::ZeroVector) virtual inherited
Called for Blocking impact.
Parameters
Hit Describes the collision.
TimeSlice Time period for the simulation that produced this hit. Useful for putting Hit.Time in context. Can be zero in certain situations where it's not appropriate, be sure to handle that.
MoveDelta Attempted move that resulted in the hit.
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
References HandleImpact().
InitCollisionParams()
virtual void UMovementComponent::InitCollisionParams (FCollisionQueryParams & OutParams, FCollisionResponseParams & OutResponseParam) const virtual inherited
Initialize collision params appropriately based on our collision settings.
Use this before any Line, Overlap, or Sweep tests.
References InitCollisionParams().
InitializeComponent()
virtual void UMovementComponent::InitializeComponent () override virtual inherited
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
Reimplemented in UProjectileMovementComponent.
IsExceedingMaxSpeed()
virtual bool UMovementComponent::IsExceedingMaxSpeed (float MaxSpeed) const virtual inherited
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
Note that under normal circumstances updates cause by acceleration will not cause this to be true, however external forces or changes in the max speed limit can cause the max speed to be violated.
References IsExceedingMaxSpeed(), and StopMovementImmediately().
IsInWater()
virtual bool UMovementComponent::IsInWater () const virtual inherited
Returns true if it's in PhysicsVolume with water flag.
References IsInWater().
K2_MoveUpdatedComponent()
bool UMovementComponent::K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult & OutHit, bool bSweep = true, bool bTeleport = false) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
References K2_MoveUpdatedComponent().
MoveUpdatedComponent() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled. \note This simply calls the virtual MoveUpdatedComponentImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
Definition at line 487 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 492 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponentImpl()
virtual bool UMovementComponent::MoveUpdatedComponentImpl (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) protected virtual inherited
References MoveUpdatedComponentImpl().
OnRegister()
virtual void UMovementComponent::OnRegister () override virtual inherited
Overridden to update component properties that should be updated while being edited.
Reimplemented in UCharacterMovementComponent.
OnTeleported()
virtual void UMovementComponent::OnTeleported () inline virtual inherited
Called by owning Actor upon successful teleport from AActor::TeleportTo().
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
Definition at line 459 of file MovementComponent.h.
References OnTeleported().
OverlapTest()
virtual bool UMovementComponent::OverlapTest (const FVector & Location, const FQuat & RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape & CollisionShape, const AActor * IgnoreActor) const virtual inherited
Return true if the given collision shape overlaps other geometry at the given location and rotation.
The collision params are set by InitCollisionParams().
References Location, MoveUpdatedComponent(), and OverlapTest().
PhysicsLockedAxisSettingChanged()
void UMovementComponent::PhysicsLockedAxisSettingChanged () static inherited
PhysicsVolumeChanged()
virtual void UMovementComponent::PhysicsVolumeChanged (class APhysicsVolume * NewVolume) virtual inherited
Delegate when PhysicsVolume of UpdatedComponent has been changed.
Reimplemented in UCharacterMovementComponent.
References PhysicsVolumeChanged().
PostEditChangeProperty()
virtual void UMovementComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual inherited
Reimplemented in UCharacterMovementComponent, and UNavMovementComponent.
PostLoad()
virtual void UMovementComponent::PostLoad () override virtual inherited
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
RegisterComponentTickFunctions()
virtual void UMovementComponent::RegisterComponentTickFunctions (bool bRegister) override virtual inherited
Reimplemented in UCharacterMovementComponent.
ResolvePenetration() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) inherited
Try to move out of penetration in an object after a failed move.
This function should respect the plane constraint if applicable. \note This simply calls the virtual ResolvePenetrationImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat)..
Parameters
Adjustment The requested adjustment, usually from GetPenetrationAdjustment()
Hit The result of the failed move
Returns
True if the adjustment was successful and the original move should be retried, or false if no repeated attempt should be made.
Definition at line 497 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetration() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FRotator & NewRotation) inherited
Definition at line 502 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetrationImpl()
virtual bool UMovementComponent::ResolvePenetrationImpl (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) protected virtual inherited
Reimplemented in UCharacterMovementComponent, and UFloatingPawnMovement.
References ResolvePenetrationImpl().
SafeMoveUpdatedComponent() [1/2]
bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
If this adjustment succeeds, the original movement will be attempted again. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
result of the final MoveUpdatedComponent() call.
References SafeMoveUpdatedComponent().
SafeMoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 482 of file MovementComponent.h.
References SafeMoveUpdatedComponent().
Serialize()
virtual void UMovementComponent::Serialize (FArchive & Ar) override virtual inherited
Reimplemented in UCharacterMovementComponent, UNavMovementComponent, and UPawnMovementComponent.
SetPlaneConstraintAxisSetting()
virtual void UMovementComponent::SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting) virtual inherited
Set the plane constraint axis setting.
Changing this setting will modify the current value of PlaneConstraintNormal.
Parameters
NewAxisSetting New plane constraint axis setting.
References EPlaneConstraintAxisSetting, GetPlaneConstraintAxisSetting(), and SetPlaneConstraintAxisSetting().
SetPlaneConstraintEnabled()
virtual void UMovementComponent::SetPlaneConstraintEnabled (bool bEnabled) virtual inherited
Sets whether or not the plane constraint is enabled.
References SetPlaneConstraintEnabled().
SetPlaneConstraintFromVectors()
virtual void UMovementComponent::SetPlaneConstraintFromVectors (FVector Forward, FVector Up) virtual inherited
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintFromVectors().
SetPlaneConstraintNormal()
virtual void UMovementComponent::SetPlaneConstraintNormal (FVector PlaneNormal) virtual inherited
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
Changing the normal automatically sets PlaneConstraintAxisSetting to "Custom".
Parameters
PlaneNormal The normal of the plane. If non-zero in length, it will be normalized.
References SetPlaneConstraintNormal().
SetPlaneConstraintOrigin()
virtual void UMovementComponent::SetPlaneConstraintOrigin (FVector PlaneOrigin) virtual inherited
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintOrigin().
SetUpdatedComponent()
virtual void UMovementComponent::SetUpdatedComponent (USceneComponent * NewUpdatedComponent) virtual inherited
Assign the component we move and update.
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
References SetUpdatedComponent().
ShouldSkipUpdate()
virtual bool UMovementComponent::ShouldSkipUpdate (float DeltaTime) const virtual inherited
Possibly skip update if moved component is not rendered or can't move.
Parameters
DeltaTime
Todo
this parameter is not used in the function.
Returns
true if component movement update should be skipped
References ShouldSkipUpdate().
SlideAlongSurface()
virtual float UMovementComponent::SlideAlongSurface (const FVector & Delta, float Time, const FVector & Normal, FHitResult & Hit, bool bHandleImpact = false) virtual inherited
Slide smoothly along a surface, and slide away from multiple impacts using TwoWallAdjust if necessary.
Calls HandleImpact for each surface hit, if requested. Uses SafeMoveUpdatedComponent() for movement, and ComputeSlideVector() to determine the slide direction.
Parameters
Delta Attempted movement vector.
Time Percent of Delta to apply (between 0 and 1). Usually equal to the remaining time after a collision: (1.0 - Hit.Time).
Normal Normal opposing movement, along which we will slide.
Hit [In] HitResult of the attempted move that resulted in the impact triggering the slide. [Out] HitResult of last attempted move.
bHandleImpact Whether to call HandleImpact on each hit.
Returns
The percentage of requested distance (Delta * Percent) actually applied (between 0 and 1). 0 if no movement occurred, non-zero if movement occurred.
Reimplemented in UCharacterMovementComponent.
References SlideAlongSurface().
SnapUpdatedComponentToPlane()
virtual void UMovementComponent::SnapUpdatedComponentToPlane () virtual inherited
Snap the updated component to the plane constraint, if enabled.
References SnapUpdatedComponentToPlane().
StopMovementImmediately()
void UMovementComponent::StopMovementImmediately () inline virtual inherited
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
Reimplemented in UNavMovementComponent.
Definition at line 471 of file MovementComponent.h.
References UpdateComponentVelocity().
TwoWallAdjust()
virtual void UMovementComponent::TwoWallAdjust (FVector & Delta, const FHitResult & Hit, const FVector & OldHitNormal) const virtual inherited
Compute a movement direction when contacting two surfaces.
Parameters
Delta [In] Amount of move attempted before impact. [Out] Computed adjustment based on impacts.
Hit Impact from last attempted move
OldHitNormal Normal of impact before last attempted move
Returns
Result in Delta that is the direction to move when contacting two surfaces.
Reimplemented in UCharacterMovementComponent.
References TwoWallAdjust().
UpdateComponentVelocity()
virtual void UMovementComponent::UpdateComponentVelocity () virtual inherited
Update ComponentVelocity of UpdatedComponent.
This needs to be called by derived classes at the end of an update whenever Velocity has changed.
References UpdateComponentVelocity().
UpdateTickRegistration()
virtual void UMovementComponent::UpdateTickRegistration () virtual inherited
Update tick registration state, determined by bAutoUpdateTickRegistration.
Called by SetUpdatedComponent.
Reimplemented in UProjectileMovementComponent.
References UpdateTickRegistration().
Member Data Documentation
bAutoRegisterPhysicsVolumeUpdates
uint8 UMovementComponent::bAutoRegisterPhysicsVolumeUpdates inherited
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
If false, will not change bShouldUpdatePhysicsVolume on the UpdatedComponent at all.
See also
bComponentShouldUpdatePhysicsVolume
Definition at line 166 of file MovementComponent.h.
bAutoRegisterUpdatedComponent
uint8 UMovementComponent::bAutoRegisterUpdatedComponent inherited
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
Definition at line 148 of file MovementComponent.h.
bAutoUpdateTickRegistration
uint8 UMovementComponent::bAutoUpdateTickRegistration inherited
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
This will NOT enable tick at startup if bAutoActivate is false, because presumably you have a good reason for not wanting it to start ticking initially.
Definition at line 136 of file MovementComponent.h.
bComponentShouldUpdatePhysicsVolume
uint8 UMovementComponent::bComponentShouldUpdatePhysicsVolume inherited
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Only enabled if bAutoRegisterPhysicsVolumeUpdates is true. WARNING: UpdatePhysicsVolume is potentially expensive if overlap events are also disabled because it requires a separate query against all physics volumes in the world.
Definition at line 174 of file MovementComponent.h.
bConstrainToPlane
uint8 UMovementComponent::bConstrainToPlane inherited
If true, movement will be constrained to a plane.
See also
PlaneConstraintNormal, PlaneConstraintOrigin, PlaneConstraintAxisSetting
Definition at line 155 of file MovementComponent.h.
bSnapToPlaneAtStart
uint8 UMovementComponent::bSnapToPlaneAtStart inherited
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
Definition at line 159 of file MovementComponent.h.
bTickBeforeOwner
uint8 UMovementComponent::bTickBeforeOwner inherited
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
This is important when our tick causes an update in the owner's position, so that when the owner ticks it uses the most recent position without lag. Disabling this can improve performance if both objects tick but the order of ticks doesn't matter.
Definition at line 144 of file MovementComponent.h.
bUpdateOnlyIfRendered
uint8 UMovementComponent::bUpdateOnlyIfRendered inherited
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
Definition at line 129 of file MovementComponent.h.
PlaneConstraintNormal
FVector UMovementComponent::PlaneConstraintNormal protected inherited
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
If for example you wanted to constrain movement to the X-Z plane (so that Y cannot change), the normal would be set to X=0 Y=1 Z=0. This is recalculated whenever PlaneConstraintAxisSetting changes. It is normalized once the component is registered with the game world.
See also
bConstrainToPlane, SetPlaneConstraintNormal(), SetPlaneConstraintFromVectors()
Definition at line 107 of file MovementComponent.h.
PlaneConstraintOrigin
FVector UMovementComponent::PlaneConstraintOrigin protected inherited
The origin of the plane that constrains movement, if plane constraint is enabled.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
See also
bConstrainToPlane, SetPlaneConstraintOrigin().
Definition at line 115 of file MovementComponent.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RotatingMovementComponent.h