Unreal Engine 5.6 C++ API: RenderTransform.h File Reference
RenderTransform.h File Reference
#include "CoreMinimal.h"
#include "Math/Box.h"
#include "Math/BoxSphereBounds.h"
#include "Math/Float32.h"
#include "Math/Matrix.h"
#include "Math/NumericLimits.h"
#include "Math/UnrealMathSSE.h"
#include "Math/Vector.h"
#include "Math/Vector2D.h"
#include "Math/VectorRegister.h"
#include "Serialization/Archive.h"
#include "Serialization/MemoryLayout.h"
#include "Serialization/StructuredArchiveAdapters.h"
Data Structures
struct FCompressedTransform
struct FRenderBounds
struct FRenderTransform
Functions
FORCEINLINE void GetHemiOrthoBasis (FVector3f &BasisX, FVector3f &BasisY, const FVector3f &BasisZ)
FORCEINLINE FVector3f HemiOctahedronToUnitVector (const FVector2f &Oct)
FORCEINLINE FVector2f UnitVectorToHemiOctahedron (const FVector3f &N)
Function Documentation
GetHemiOrthoBasis()
FORCEINLINE void GetHemiOrthoBasis (FVector3f & BasisX, FVector3f & BasisY, const FVector3f & BasisZ)
Definition at line 416 of file RenderTransform.h.
References A, B, FORCEINLINE, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by FCompressedTransform::FCompressedTransform(), and FCompressedTransform::ToRenderTransform().
HemiOctahedronToUnitVector()
FORCEINLINE FVector3f HemiOctahedronToUnitVector (const FVector2f & Oct)
Definition at line 430 of file RenderTransform.h.
References FORCEINLINE, UE::Math::TVector< T >::GetUnsafeNormal(), UE::Math::TVector2< T >::X, UE::Math::TVector< T >::X, UE::Math::TVector2< T >::Y, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by FCompressedTransform::ToRenderTransform().
UnitVectorToHemiOctahedron()
FORCEINLINE FVector2f UnitVectorToHemiOctahedron (const FVector3f & N)
Definition at line 424 of file RenderTransform.h.
References FORCEINLINE, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by FCompressedTransform::FCompressedTransform().