Unreal Engine 5.6 C++ API: FSlateWindowElementList Class Reference
FSlateWindowElementList Class Reference
Represents a top level window and its draw elements.
#include "DrawElements.h"
Data Structures
struct FDeferredPaint
Some widgets may want to paint their children after after another, loosely-related widget finished painting.
struct FWidgetDrawElementState
State of the current widget that is adding draw elements.
Public Member Functions
FSlateWindowElementList (const TSharedPtr< SWindow > &InPaintWindow)
Construct a new list of elements with which to paint a window.
~FSlateWindowElementList ()
void AddReferencedObjects (FReferenceCollector &Collector)
template<EElementType ElementType = EElementType::ET_NonMapped>
TSlateDrawElement< ElementType > & AddUninitialized ()
Creates an uninitialized draw element if using caching will create a new cached draw list if needed (Whenever a top level draw widget's cache handle doesn't match the current cached handle).
FSlateDrawElement & AddUninitializedLookup (EElementType InElementType=EElementType::ET_NonMapped)
Calls AddUninitialized, resolving template version based on enum.
void BeginDeferredGroup ()
void EndDeferredGroup ()
FSlateBatchData & GetBatchData ()
FSlateBatchData & GetBatchDataHDR ()
int32 GetClippingIndex () const
FSlateClippingManager & GetClippingManager ()
const FSlateClippingManager & GetClippingManager () const
int32 GetClippingStackDepth () const
TOptional< FSlateClippingState > GetClippingState () const
TArrayView< FSlateCachedElementList *const > GetCurrentCachedElementWithNewData () const
TArray< TSharedPtr< FDeferredPaint > > GetDeferredPaintList () const
bool GetIsInGameLayer ()
SWindow * GetPaintWindow () const
EWidgetPixelSnapping GetPixelSnappingMethod () const
SWindow * GetRenderWindow () const
const FSlateDrawElementMap & GetUncachedDrawElements () const
UE::Slate::FDeprecateVector2DResult GetWindowSize () const
int32 PaintDeferred (int32 LayerId, const FSlateRect &MyCullingRect)
void PopCachedElementData ()
void PopClip ()
void PopClipToStackIndex (int32 Index)
FSlateCachedElementsHandle PopPaintingWidget (const SWidget &CurrentWidget)
Pops the current painted widget off the stack.
void PopPixelSnappingMethod ()
void PushCachedElementData (FSlateCachedElementData &CachedElementData)
Pushes cached element data onto the stack.
int32 PushClip (const FSlateClippingZone &InClipZone)
void PushPaintingWidget (const SWidget &CurrentWidget, int32 StartingLayerId, FSlateCachedElementsHandle &CurrentCacheHandle)
Pushes the current widget that is painting onto the widget stack so we know what elements belong to each widget This information is used for caching later.
int32 PushPixelSnappingMethod (EWidgetPixelSnapping InPixelSnappingMethod)
void QueueDeferredPainting (const FDeferredPaint &InDeferredPaint)
void ResetElementList ()
Remove all the elements from this draw list.
void SetIsInGameLayer (bool bInGameLayer)
void SetRenderTargetWindow (SWindow *InRenderTargetWindow)
bool ShouldResolveDeferred () const
Private Member Functions
template<EElementType ElementType>
TSlateDrawElement< ElementType > & AddCachedElement ()
Adds a cached element, generating a new cached list for the widget at the top of the cache if needed.
void FinishMergeRenderBatches ()
TArrayView< FSlateCachedElementData *const > GetCachedElementDataList () const
FSlateCachedElementData * GetCurrentCachedElementData () const
void StartMergeRenderBatches ()
STAT (int32 MemManagerAllocatedMemory;) SWindow *RenderTargetWindow
The window to render to.
Private Attributes
FSlateBatchData BatchData
Batched data used for rendering.
FSlateBatchData BatchDataHDR
Batched data used for rendering.
bool bIsInGameLayer
Store if currently drawing within Game Layer.
bool bNeedsDeferredResolve
TArray< FSlateCachedElementData *, TInlineAllocator< 4 > > CachedElementDataList
TArray< int32, TInlineAllocator< 4 > > CachedElementDataListStack
FSlateClippingManager ClippingManager
TArray< TSharedPtr< FDeferredPaint > > DeferredPaintList
Some widgets want their logical children to appear at a different "layer" in the physical hierarchy.
FMemStackBase MemManager
UE::Tasks::FTask MergeBatchDataTask
TArray< EWidgetPixelSnapping, TInlineAllocator< 4 > > PixelSnappingMethodStack
Manages what pixel snapping method should be applied.
SWindow * RawPaintWindow
TArray< int32 > ResolveToDeferredIndex
FSlateDrawElementMap UncachedDrawElements
The uncached draw elements to be processed.
TWeakPtr< SWindow > WeakPaintWindow
Window which owns the widgets that are being painted but not necessarily rendered to Widgets are always rendered to the RenderTargetWindow.
TArray< FWidgetDrawElementState, TInlineAllocator< 50 > > WidgetDrawStack
FVector2f WindowSize
Store the size of the window being used to paint.
Friends
class FSlateElementBatcher
Additional Inherited Members
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Detailed Description
Represents a top level window and its draw elements.
Definition at line 219 of file DrawElements.h.
Constructor & Destructor Documentation
FSlateWindowElementList()
FSlateWindowElementList::FSlateWindowElementList (const TSharedPtr< SWindow > & InPaintWindow) explicit
Construct a new list of elements with which to paint a window.
Parameters
InPaintWindow The window that owns the widgets being painted. This is almost most always the same window that is being rendered to
InRenderWindow The window that we will be rendering to.
Referenced by FSlateWindowElementList::FDeferredPaint::ExecutePaint().
~FSlateWindowElementList()
FSlateWindowElementList::~FSlateWindowElementList ()
Member Function Documentation
AddCachedElement()
template<EElementType ElementType> TSlateDrawElement< ElementType > & FSlateWindowElementList::AddCachedElement () inline private
Adds a cached element, generating a new cached list for the widget at the top of the cache if needed.
Definition at line 425 of file DrawElements.h.
References FSlateCachedElementData::AddCache(), FSlateCachedElementData::AddCachedElement(), FSlateWindowElementList::FWidgetDrawElementState::bIsVolatile, FSlateWindowElementList::FWidgetDrawElementState::CacheHandle, check, GetClippingManager(), GetCurrentCachedElementData(), FSlateCachedElementsHandle::IsValid(), FSlateWindowElementList::FWidgetDrawElementState::Widget, and WidgetDrawStack.
Referenced by AddUninitialized().
AddReferencedObjects()
void FSlateWindowElementList::AddReferencedObjects (FReferenceCollector & Collector)
AddUninitialized()
template<EElementType ElementType = EElementType::ET_NonMapped> TSlateDrawElement< ElementType > & FSlateWindowElementList::AddUninitialized () inline
Creates an uninitialized draw element if using caching will create a new cached draw list if needed (Whenever a top level draw widget's cache handle doesn't match the current cached handle).
Definition at line 265 of file DrawElements.h.
References AddCachedElement(), CachedElementDataListStack, Container, FSlateDebugging::ElementTypeAdded, UncachedDrawElements, and WidgetDrawStack.
AddUninitializedLookup()
FSlateDrawElement & FSlateWindowElementList::AddUninitializedLookup (EElementType InElementType = EElementType::ET_NonMapped)
Calls AddUninitialized, resolving template version based on enum.
References ET_NonMapped.
BeginDeferredGroup()
void FSlateWindowElementList::BeginDeferredGroup ()
EndDeferredGroup()
void FSlateWindowElementList::EndDeferredGroup ()
FinishMergeRenderBatches()
void FSlateWindowElementList::FinishMergeRenderBatches () private
Referenced by GetBatchData(), and GetBatchDataHDR().
GetBatchData()
FSlateBatchData & FSlateWindowElementList::GetBatchData () inline
Definition at line 392 of file DrawElements.h.
References BatchData, and FinishMergeRenderBatches().
GetBatchDataHDR()
FSlateBatchData & FSlateWindowElementList::GetBatchDataHDR () inline
Definition at line 398 of file DrawElements.h.
References BatchDataHDR, and FinishMergeRenderBatches().
GetCachedElementDataList()
TArrayView< FSlateCachedElementData *const > FSlateWindowElementList::GetCachedElementDataList () const inline private
Definition at line 441 of file DrawElements.h.
References CachedElementDataList, and MakeArrayView().
GetClippingIndex()
int32 FSlateWindowElementList::GetClippingIndex () const
GetClippingManager() [1/2]
FSlateClippingManager & FSlateWindowElementList::GetClippingManager () inline
Definition at line 310 of file DrawElements.h.
References ClippingManager.
Referenced by AddCachedElement().
GetClippingManager() [2/2]
const FSlateClippingManager & FSlateWindowElementList::GetClippingManager () const inline
Definition at line 311 of file DrawElements.h.
References ClippingManager.
GetClippingStackDepth()
int32 FSlateWindowElementList::GetClippingStackDepth () const inline
Definition at line 304 of file DrawElements.h.
References ClippingManager.
GetClippingState()
TOptional< FSlateClippingState > FSlateWindowElementList::GetClippingState () const
GetCurrentCachedElementData()
FSlateCachedElementData * FSlateWindowElementList::GetCurrentCachedElementData () const inline private
Definition at line 443 of file DrawElements.h.
References CachedElementDataList, and CachedElementDataListStack.
Referenced by AddCachedElement(), and GetCurrentCachedElementWithNewData().
GetCurrentCachedElementWithNewData()
TArrayView< FSlateCachedElementList *const > FSlateWindowElementList::GetCurrentCachedElementWithNewData () const inline
Definition at line 411 of file DrawElements.h.
References CachedElementDataList, CachedElementDataListStack, and GetCurrentCachedElementData().
GetDeferredPaintList()
TArray< TSharedPtr< FDeferredPaint > > FSlateWindowElementList::GetDeferredPaintList () const inline
Definition at line 358 of file DrawElements.h.
References DeferredPaintList.
GetIsInGameLayer()
bool FSlateWindowElementList::GetIsInGameLayer ()
GetPaintWindow()
SWindow * FSlateWindowElementList::GetPaintWindow () const inline
Returns
Get the window that we will be painting
Definition at line 234 of file DrawElements.h.
References check, IsInGameThread(), IsInSlateThread(), RawPaintWindow, and WeakPaintWindow.
Referenced by GetRenderWindow().
GetPixelSnappingMethod()
EWidgetPixelSnapping FSlateWindowElementList::GetPixelSnappingMethod () const
GetRenderWindow()
SWindow * FSlateWindowElementList::GetRenderWindow () const inline
Returns
Get the window that we will be rendering to. Unless you are a slate renderer you probably want to use GetPaintWindow()
Definition at line 241 of file DrawElements.h.
References check, GetPaintWindow(), IsInGameThread(), and IsInSlateThread().
GetUncachedDrawElements()
const FSlateDrawElementMap & FSlateWindowElementList::GetUncachedDrawElements () const inline
Returns
Get the draw elements that we want to render into this window
Definition at line 249 of file DrawElements.h.
References UncachedDrawElements.
GetWindowSize()
UE::Slate::FDeprecateVector2DResult FSlateWindowElementList::GetWindowSize () const inline
Returns
Get the window size that we will be painting
Definition at line 255 of file DrawElements.h.
References WindowSize.
PaintDeferred()
int32 FSlateWindowElementList::PaintDeferred (int32 LayerId, const FSlateRect & MyCullingRect)
PopCachedElementData()
void FSlateWindowElementList::PopCachedElementData ()
PopClip()
void FSlateWindowElementList::PopClip ()
PopClipToStackIndex()
void FSlateWindowElementList::PopClipToStackIndex (int32 Index)
PopPaintingWidget()
FSlateCachedElementsHandle FSlateWindowElementList::PopPaintingWidget (const SWidget & CurrentWidget)
Pops the current painted widget off the stack.
Returns
true if an element was added while the widget was pushed
PopPixelSnappingMethod()
void FSlateWindowElementList::PopPixelSnappingMethod ()
PushCachedElementData()
void FSlateWindowElementList::PushCachedElementData (FSlateCachedElementData & CachedElementData)
Pushes cached element data onto the stack.
Any draw elements cached after will use this cached element data until popped
PushClip()
int32 FSlateWindowElementList::PushClip (const FSlateClippingZone & InClipZone)
PushPaintingWidget()
void FSlateWindowElementList::PushPaintingWidget (const SWidget & CurrentWidget, int32 StartingLayerId, FSlateCachedElementsHandle & CurrentCacheHandle)
Pushes the current widget that is painting onto the widget stack so we know what elements belong to each widget This information is used for caching later.
PushPixelSnappingMethod()
int32 FSlateWindowElementList::PushPixelSnappingMethod (EWidgetPixelSnapping InPixelSnappingMethod)
QueueDeferredPainting()
void FSlateWindowElementList::QueueDeferredPainting (const FDeferredPaint & InDeferredPaint)
ResetElementList()
void FSlateWindowElementList::ResetElementList ()
Remove all the elements from this draw list.
SetIsInGameLayer()
void FSlateWindowElementList::SetIsInGameLayer (bool bInGameLayer)
SetRenderTargetWindow()
void FSlateWindowElementList::SetRenderTargetWindow (SWindow * InRenderTargetWindow)
ShouldResolveDeferred()
bool FSlateWindowElementList::ShouldResolveDeferred () const inline
Definition at line 353 of file DrawElements.h.
References bNeedsDeferredResolve.
StartMergeRenderBatches()
void FSlateWindowElementList::StartMergeRenderBatches () private
STAT()
FSlateWindowElementList::STAT (int32 MemManagerAllocatedMemory;) private
The window to render to.
This may be different from the paint window if we are displaying the contents of a window (or virtual window) onto another window The primary use case of this is thread safe rendering of widgets during times when the main thread is blocked (e.g loading movies) If this is null, the paint window is used
Friends And Related Symbol Documentation
FSlateElementBatcher
friend class FSlateElementBatcher friend
Definition at line 221 of file DrawElements.h.
References FSlateElementBatcher.
Referenced by FSlateElementBatcher.
Field Documentation
BatchData
FSlateBatchData FSlateWindowElementList::BatchData private
Batched data used for rendering.
Definition at line 466 of file DrawElements.h.
Referenced by GetBatchData().
BatchDataHDR
FSlateBatchData FSlateWindowElementList::BatchDataHDR private
Batched data used for rendering.
Definition at line 469 of file DrawElements.h.
Referenced by GetBatchDataHDR().
bIsInGameLayer
bool FSlateWindowElementList::bIsInGameLayer private
Store if currently drawing within Game Layer.
Definition at line 517 of file DrawElements.h.
bNeedsDeferredResolve
bool FSlateWindowElementList::bNeedsDeferredResolve private
Definition at line 485 of file DrawElements.h.
Referenced by ShouldResolveDeferred().
CachedElementDataList
TArray<FSlateCachedElementData*, TInlineAllocator<4> > FSlateWindowElementList::CachedElementDataList private
Definition at line 509 of file DrawElements.h.
Referenced by GetCachedElementDataList(), GetCurrentCachedElementData(), and GetCurrentCachedElementWithNewData().
CachedElementDataListStack
TArray<int32, TInlineAllocator<4> > FSlateWindowElementList::CachedElementDataListStack private
Definition at line 510 of file DrawElements.h.
Referenced by AddUninitialized(), GetCurrentCachedElementData(), and GetCurrentCachedElementWithNewData().
ClippingManager
FSlateClippingManager FSlateWindowElementList::ClippingManager private
Definition at line 474 of file DrawElements.h.
Referenced by GetClippingManager(), GetClippingManager(), and GetClippingStackDepth().
DeferredPaintList
TArray< TSharedPtr<FDeferredPaint> > FSlateWindowElementList::DeferredPaintList private
Some widgets want their logical children to appear at a different "layer" in the physical hierarchy.
We accomplish this by deferring their painting.
Definition at line 483 of file DrawElements.h.
Referenced by GetDeferredPaintList().
MemManager
FMemStackBase FSlateWindowElementList::MemManager private
Definition at line 456 of file DrawElements.h.
MergeBatchDataTask
UE::Tasks::FTask FSlateWindowElementList::MergeBatchDataTask private
Definition at line 471 of file DrawElements.h.
PixelSnappingMethodStack
TArray<EWidgetPixelSnapping, TInlineAllocator<4> > FSlateWindowElementList::PixelSnappingMethodStack private
Manages what pixel snapping method should be applied.
Definition at line 477 of file DrawElements.h.
RawPaintWindow
SWindow* FSlateWindowElementList::RawPaintWindow private
Definition at line 454 of file DrawElements.h.
Referenced by GetPaintWindow().
ResolveToDeferredIndex
TArray<int32> FSlateWindowElementList::ResolveToDeferredIndex private
Definition at line 486 of file DrawElements.h.
UncachedDrawElements
FSlateDrawElementMap FSlateWindowElementList::UncachedDrawElements private
The uncached draw elements to be processed.
Definition at line 506 of file DrawElements.h.
Referenced by AddUninitialized(), and GetUncachedDrawElements().
WeakPaintWindow
TWeakPtr<SWindow> FSlateWindowElementList::WeakPaintWindow private
Window which owns the widgets that are being painted but not necessarily rendered to Widgets are always rendered to the RenderTargetWindow.
Definition at line 453 of file DrawElements.h.
Referenced by GetPaintWindow().
WidgetDrawStack
TArray<FWidgetDrawElementState, TInlineAllocator<50> > FSlateWindowElementList::WidgetDrawStack private
Definition at line 508 of file DrawElements.h.
Referenced by AddCachedElement(), and AddUninitialized().
WindowSize
FVector2f FSlateWindowElementList::WindowSize private
Store the size of the window being used to paint.
Definition at line 514 of file DrawElements.h.
Referenced by GetWindowSize().
The documentation for this class was generated from the following file:
DrawElements.h