Unreal Engine 5.6 C++ API: ClusterUnionComponent.h File Reference
ClusterUnionComponent.h File Reference
#include "Chaos/PhysicsObject.h"
#include "Components/PrimitiveComponent.h"
#include "Containers/Array.h"
#include "Containers/Map.h"
#include "Containers/Set.h"
#include "Engine/EngineTypes.h"
#include "Logging/LogMacros.h"
#include "PhysicsEngine/ExternalSpatialAccelerationPayload.h"
#include "PhysicsEngine/SafePhysicsObjectHandle.h"
#include "PhysicsInterfaceTypesCore.h"
#include "PhysicsProxy/ClusterUnionPhysicsProxy.h"
#include "UObject/ObjectKey.h"
#include "ClusterUnionComponent.generated.h"
Namespaces
namespace Chaos
Functions
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnClusterUnionRemovedComponent, UPrimitiveComponent *, Component)
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams (FOnClusterUnionAddedComponent, UPrimitiveComponent *, Component, const TSet< int32 > &, BoneIds, bool, bIsNew)
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnClusterUnionBoundsChanged, UClusterUnionComponent *, Component, const FBoxSphereBounds &, Bounds)
DECLARE_LOG_CATEGORY_EXTERN (LogClusterUnion, Log, All)
DECLARE_MULTICAST_DELEGATE_FourParams (FOnClusterUnionAddedComponentNative, UPrimitiveComponent *, const TArray< FClusterUnionBoneData > &, const TArray< FClusterUnionBoneData > &, bool)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnClusterUnionPostSyncBodies, const FClusterUnionInitializationData &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnClusterUnionRemovedComponentNative, UPrimitiveComponent *, const TArray< FClusterUnionBoneData > &)
USTRUCT () struct FClusterUnionBoneData
Function Documentation
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnClusterUnionRemovedComponent , UPrimitiveComponent * , Component)
References Component, and DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams (FOnClusterUnionAddedComponent , UPrimitiveComponent * , Component , const TSet< int32 > & , BoneIds , bool , bIsNew)
References Component, and DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnClusterUnionBoundsChanged , UClusterUnionComponent * , Component , const FBoxSphereBounds & , Bounds)
References Component, and DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams.
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogClusterUnion , Log , All)
References All, and Log.
DECLARE_MULTICAST_DELEGATE_FourParams()
DECLARE_MULTICAST_DELEGATE_FourParams (FOnClusterUnionAddedComponentNative , UPrimitiveComponent * , const TArray< FClusterUnionBoneData > & , const TArray< FClusterUnionBoneData > & , bool)
References DECLARE_MULTICAST_DELEGATE_FourParams.
DECLARE_MULTICAST_DELEGATE_OneParam()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnClusterUnionPostSyncBodies , const FClusterUnionInitializationData &)
References Category, Component, DECLARE_MULTICAST_DELEGATE_OneParam, End, FVector, GENERATED_BODY, Geometry, GetTypeHash(), meta, MinimalAPI, Name, operator<(), operator==(), Other, Params, R, TUniquePtr< T, Deleter >::Reset(), Algo::Transform(), UCLASS, UE_DEPRECATED, UFUNCTION, UPROPERTY, and X.
DECLARE_MULTICAST_DELEGATE_TwoParams()
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnClusterUnionRemovedComponentNative , UPrimitiveComponent * , const TArray< FClusterUnionBoneData > &)
References DECLARE_MULTICAST_DELEGATE_TwoParams.
USTRUCT()
USTRUCT ()
Definition at line 35 of file ClusterUnionComponent.h.
References GENERATED_BODY, GetTypeHash(), ID, INDEX_NONE, operator!=(), operator==(), and Other.