Unreal Engine 5.6 C++ API: MemStack.h File Reference
MemStack.h File Reference
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/LockFreeFixedSizeAllocator.h"
#include "CoreGlobals.h"
#include "CoreTypes.h"
#include "HAL/MemoryBase.h"
#include "HAL/PlatformCrt.h"
#include "HAL/ThreadSafeCounter.h"
#include "HAL/ThreadSingleton.h"
#include "HAL/UnrealMemory.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/AssertionMacros.h"
#include "Misc/Build.h"
#include "Misc/NoopCounter.h"
#include "Templates/AlignmentTemplates.h"
#include "Templates/UnrealTemplate.h"
Data Structures
class FMemMark
FMemMark marks a top-of-stack position in the memory stack.
class FMemStackBase
Simple linear-allocation memory stack.
struct FMemStackBase::FTaggedMemory
class FPageAllocator
struct TAllocatorTraits< TMemStackAllocator< Alignment > >
class TMemStackAllocator< Alignment >
A container allocator that allocates from a mem-stack.
class TMemStackAllocator< Alignment >::ForElementType< ElementType >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Enumerations
enum EMemOned { MEM_Oned = 1 }
enum EMemZeroed { MEM_Zeroed = 1 }
Functions
template<class T>
UE_DECLARE_THREAD_SINGLETON_TLS(class FMemStack, 1) class FMemStack T * New (FMemStackBase &Mem, int32 Count=1, int32 Align=DEFAULT_ALIGNMENT)
template<class T>
T * NewOned (FMemStackBase &Mem, int32 Count=1, int32 Align=DEFAULT_ALIGNMENT)
template<class T>
T * NewZeroed (FMemStackBase &Mem, int32 Count=1, int32 Align=DEFAULT_ALIGNMENT)
void UE::Core::Private::OnInvalidMemStackAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
void * operator new (size_t Size, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new (size_t Size, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new (size_t Size, FMemStackBase &Mem, int32 Count=1)
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase &Mem, int32 Count=1)
void * operator new[] (size_t Size, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new[] (size_t Size, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new[] (size_t Size, FMemStackBase &Mem, int32 Count=1)
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase &Mem, int32 Count=1)
Enumeration Type Documentation
EMemOned
enum EMemOned
Enumerator
MEM_Oned
Definition at line 29 of file MemStack.h.
EMemZeroed
enum EMemZeroed
Enumerator
MEM_Zeroed
Definition at line 23 of file MemStack.h.
Function Documentation
New()
template<class T> UE_DECLARE_THREAD_SINGLETON_TLS(class FMemStack, 1) class FMemStack T * New (FMemStackBase & Mem, int32 Count = 1, int32 Align = DEFAULT_ALIGNMENT) inline
Definition at line 259 of file MemStack.h.
References Align(), Count, DEFAULT_ALIGNMENT, and FMemStackBase::PushBytes().
Referenced by FRigVMStructUpgradeInfo::FRigVMStructUpgradeInfo(), UE::MemStack::AllocateString(), IConsoleObject::ClearFlags(), DiffUtils::CompareUnrelatedSCS(), TMovieSceneInterrogationIterator< DataType >::end, TClosableMpscQueue< T >::Enqueue(), TMpscQueue< T, AllocatorType >::Enqueue(), FReload::NotifyChange(), FReload::NotifyChange(), FReload::NotifyChange(), FReload::NotifyChange(), IReload::NotifyChange(), IReload::NotifyChange(), IReload::NotifyChange(), IReload::NotifyChange(), UE::TConsumeAllMpmcQueue< T, AllocatorType >::ProduceItem(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Realloc(), FCurveEditorScreenSpace::ToCurveSpace(), UE::UE_DEPRECATED(), FReload::UpdateStats(), and USTRUCT().
NewOned()
template<class T> T * NewOned (FMemStackBase & Mem, int32 Count = 1, int32 Align = DEFAULT_ALIGNMENT) inline
Definition at line 269 of file MemStack.h.
References Align(), Count, DEFAULT_ALIGNMENT, FMemory::Memset(), and FMemStackBase::PushBytes().
NewZeroed()
template<class T> T * NewZeroed (FMemStackBase & Mem, int32 Count = 1, int32 Align = DEFAULT_ALIGNMENT) inline
Definition at line 263 of file MemStack.h.
References Align(), Count, DEFAULT_ALIGNMENT, FMemory::Memzero(), and FMemStackBase::PushBytes().
operator new() [1/6]
void * operator new (size_t Size, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) inline
Definition at line 314 of file MemStack.h.
operator new() [2/6]
void * operator new (size_t Size, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) inline
Definition at line 296 of file MemStack.h.
operator new() [3/6]
void * operator new (size_t Size, FMemStackBase & Mem, int32 Count = 1) inline
Definition at line 282 of file MemStack.h.
operator new() [4/6]
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) inline
Definition at line 323 of file MemStack.h.
operator new() [5/6]
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) inline
Definition at line 305 of file MemStack.h.
operator new() [6/6]
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase & Mem, int32 Count = 1) inline
Definition at line 289 of file MemStack.h.
operator new[]() [1/6]
void * operator new[] (size_t Size, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) inline
Definition at line 364 of file MemStack.h.
operator new[]() [2/6]
void * operator new[] (size_t Size, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) inline
Definition at line 346 of file MemStack.h.
operator new[]() [3/6]
void * operator new[] (size_t Size, FMemStackBase & Mem, int32 Count = 1) inline
Definition at line 332 of file MemStack.h.
operator new[]() [4/6]
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) inline
Definition at line 373 of file MemStack.h.
operator new[]() [5/6]
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) inline
Definition at line 355 of file MemStack.h.
operator new[]() [6/6]
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase & Mem, int32 Count = 1) inline
Definition at line 339 of file MemStack.h.