Unreal Engine 5.6 C++ API: USoundWave Class Reference
USoundWave Class Reference
#include "SoundWave.h"
Public Types
typedef FAsyncTask< class FAsyncAudioDecompressWorker > FAsyncAudioDecompress
Async worker that decompresses the audio data on a different thread.
using FSoundWaveClientPtr = ISoundWaveClient*
Public Member Functions
void AddPlayingSource ()
void AddPlayingSource (const FSoundWaveClientPtr &Source)
virtual void BeginDestroy () override
virtual void BeginGetCompressedData (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides, const ITargetPlatform *InTargetPlatform)
virtual bool CanEditChange (const FProperty *InProperty) const override
void CleanupCachedRunningPlatformData ()
bool CleanupDecompressor (bool bForceCleanup=false)
Will clean up the decompressor task if the task has finished or force it finish.
TArray< uint8 > CreateNewCueData (const char ChunkName[4])
virtual TSharedPtr< Audio::IProxyData > CreateProxyData (const Audio::FProxyDataInitParams &InitParams) override
FSoundWaveProxyPtr CreateSoundWaveProxy ()
virtual void FinishDestroy () override
void FreeResources (bool bStopSoundsUsingThisResource=true)
Frees up all the resources allocated in this class.
virtual int32 GeneratePCMData (uint8 *PCMData, const int32 SamplesNeeded)
This is only used for DTYPE_Procedural audio.
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override
bool GetChunkData (int32 ChunkIndex, uint8 **OutChunkData, bool bMakeSureChunkIsLoaded=false)
Get Chunk data for a specified chunk index.
void GetChunkSizeStats (uint32 &OutTotalBytesOfAudioData, uint32 &OutMaxChunkBytesOfAudioData) const
virtual FByteBulkData * GetCompressedData (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides=GetPlatformCompressionOverridesForCurrentPlatform(), const ITargetPlatform *InTargetPlatform=GetRunningPlatform())
Gets the compressed data from derived data cache for the specified platform Warning, the returned pointer isn't valid after we add new formats.
SIZE_T GetCompressedDataSize (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides=GetPlatformCompressionOverridesForCurrentPlatform())
Gets the compressed data size from derived data cache for the specified format.
int32 GetCompressionQuality () const
virtual class UCurveTable * GetCurveData () const override
Returns curves associated with this sound wave.
virtual FString GetDesc () override
virtual float GetDuration () const override
virtual FName GetExporterName () override
virtual Audio::EAudioMixerStreamDataFormat::Type GetGeneratedPCMDataFormat () const
Return the format of the generated PCM data type.
void GetHandleForChunkOfAudio (TFunction< void(FAudioChunkHandle &&)> OnLoadCompleted, bool bForceSync=false, int32 ChunkIndex=1, ENamedThreads::Type CallbackThread=ENamedThreads::GameThread)
If stream caching is enabled, allows the user to retain a strong handle to the first chunk of audio in the cache.
uint32 GetImportedSampleRate () const
bool GetImportedSoundWaveData (TArray< uint8 > &OutRawPCMData, uint32 &OutSampleRate, TArray< EAudioSpeakers > &OutChannelOrder) const
Utility which returns imported PCM data and the parsed header for the file.
bool GetImportedSoundWaveData (TArray< uint8 > &OutRawPCMData, uint32 &OutSampleRate, uint16 &OutNumChannels) const
Utility which returns imported PCM data and the parsed header for the file.
class UCurveTable * GetInternalCurveData () const
These functions are required for support for some custom details/editor functionality.
bool GetInterpolatedCookedEnvelopeDataForTime (float InTime, uint32 &InOutLastIndex, float &OutAmplitude, bool bLoop)
bool GetInterpolatedCookedFFTDataForTime (float InTime, uint32 &InOutLastIndex, TArray< FSoundWaveSpectralData > &OutData, bool bLoop)
Helper function to get interpolated cooked FFT data for a given time value.
ESoundWaveLoadingBehavior GetLoadingBehavior (bool bCheckSoundClasses=true) const
Returns the loading behavior we should use for this sound wave.
uint32 GetNumChunks () const
uint32 GetNumFrames () const
Return the number of frames.
ESoundWavePrecacheState GetPrecacheState () const
const uint8 * GetResourceData () const
Memory containing the data copied from the compressed bulk data.
int32 GetResourceSize () const
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
virtual int32 GetResourceSizeForFormat (FName Format)
FName GetRuntimeFormat () const
Returns the Runtime format of the wave.
float GetSampleRateForCompressionOverrides (const FPlatformAudioCookOverrides *CompressionOverrides) const
float GetSampleRateForCurrentPlatform () const
uint32 GetSizeOfChunk (uint32 ChunkIndex) const
ESoundAssetCompressionType GetSoundAssetCompressionTypeEnum () const
will return the raw value, (i.e.
TArray< FSoundWaveCuePoint > GetSoundWaveCuePoints () const
virtual bool GetSoundWavesWithCookedAnalysisData (TArray< USoundWave * > &OutSoundWaves) override
virtual float GetSubtitlePriority () const override
const FWaveTransformUObjectConfiguration & GetTransformationChainConfig () const
FWaveformTransformationInfo GetWaveformTransformationInfo () const
TArrayView< const uint8 > GetZerothChunk (bool bForImmediatePlayback=false)
This returns the initial chunk of compressed data for streaming data sources.
FWaveInstance & HandleStart (FActiveSound &ActiveSound, const UPTRINT WaveInstanceHash) const
Handle any special requirements when the sound starts (e.g.
virtual bool HasCompressedData (FName Format, ITargetPlatform *TargetPlatform=GetRunningPlatform()) const
virtual bool HasCookedAmplitudeEnvelopeData () const override
virtual bool HasCookedFFTData () const override
bool HasError () const
bool HasInternalCurves () const
Returns whether this sound wave has internal curves.
bool HasStreamingChunks ()
virtual void InitAudioResource (FByteBulkData &CompressedData)
Copy the compressed audio data from the bulk data.
virtual bool InitAudioResource (FName Format)
Copy the compressed audio data from derived data cache.
void InvalidateCompressedData (bool bFreeResources=false, bool bRebuildStreamingChunks=true)
Change the guid and flush all compressed data.
void InvalidateSoundWaveIfNeccessary ()
This function can be called before playing or using a SoundWave to check if any cook settings have been modified since this SoundWave was last cooked.
bool IsAsyncWorkComplete () const
IInterface_AsyncCompilation end.
virtual bool IsCompiling () const override
IInterface_AsyncCompilation begin.
bool IsCompressedDataReady (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides) const
Returns if an async task for a certain platform has finished.
bool IsGeneratingAudio () const
bool IsLoadedFromCookedData () const
virtual bool IsPlayable () const override
virtual bool IsProcedurallyGenerated () const override
virtual bool IsReadyForFinishDestroy () override
bool IsRetainingAudio ()
virtual bool IsSeekable () const
Queries if Seeking is supported by the Decoder for this Wave.
bool IsStreaming (const FPlatformAudioCookOverrides &Overrides) const
bool IsStreaming (const TCHAR *PlatformName=nullptr) const
Checks whether sound has been categorized as streaming.
bool LoadZerothChunk ()
void LogBakedData ()
virtual void OnBeginGenerate ()
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &CookContext) override
virtual void OnEndGenerate ()
virtual void OnEndGenerate (ISoundGeneratorPtr Generator)
void OverrideLoadingBehavior (ESoundWaveLoadingBehavior InLoadingBehavior)
If Stream Caching is enabled, this can be used to override the default loading behavior of this USoundWave.
void OverwriteSoundWaveDataWithTransformationData ()
virtual void Parse (class FAudioDevice *AudioDevice, const UPTRINT NodeWaveInstanceHash, FActiveSound &ActiveSound, const FSoundParseParameters &ParseParams, TArray< FWaveInstance * > &WaveInstances) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
void PostImport ()
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PreSave (FObjectPreSaveContext SaveContext) override
void ReleaseCompressedAudio ()
If stream caching is enabled and au.streamcache.KeepFirstChunkInMemory is 1, this will release this USoundWave's first chunk, allowing it to be deleted.
void RemoveAudioResource ()
Remove the compressed audio data associated with the passed in wave.
void RemovePlayingSource ()
void RemovePlayingSource (const FSoundWaveClientPtr &Source)
void ResetError ()
void RetainCompressedAudio (bool bForceSync=false)
If stream caching is enabled, set this sound wave to retain a strong handle to its first chunk.
virtual void Serialize (FArchive &Ar) override
virtual void SerializeCookedPlatformData (class FArchive &Ar)
Serializes cooked platform data.
void SetAllCuePoints (TArray< FSoundWaveCuePoint > InCuePoints) const
void SetCurveData (UCurveTable *InCurves)
Sets the curve data for this sound wave.
void SetError (const TCHAR *InErrorMsg=nullptr)
void SetImportedSampleRate (uint32 InImportedSampleRate)
void SetInternalCurveData (UCurveTable *InCurves)
Sets the internal curve data for this sound wave.
void SetNumFrames (uint32 InNumFrames)
Overwrite number of frames.
void SetPrecacheState (ESoundWavePrecacheState InState)
void SetSampleRate (uint32 InSampleRate, const bool bFromDecoders=false)
Overwrite sample rate.
void SetSoundWaveCuePoints (const TArray< FSoundWaveCuePoint > &InCuePoints)
bool ShouldUseStreamCaching () const
Checks whether we should use the load on demand cache.
virtual bool SupportsSubtitles () const override
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const override
UFUNCTION () 1 ESoundAssetCompressionType GetSoundAssetCompressionType() const
Returns the sound's asset compression type.
UFUNCTION () 1 TArray< FSoundWaveCuePoint > GetCuePoints() const
Filters for the cue points that are not loop regions and returns those as a new array.
UFUNCTION () 1 TArray< FSoundWaveCuePoint > GetLoopRegions() const
Filters for the cue points that are loop regions and returns those as a new array.
UFUNCTION () 1 void SetSoundAssetCompressionType(ESoundAssetCompressionType InSoundAssetCompressionType
Procedurally set the compression type.
void UpdatePlatformData ()
Attempts to update the cached platform data after any changes that might affect it.
const FWaveTransformUObjectConfiguration & UpdateTransformations ()
UPROPERTY ()
Playback volume of sound 0 to 1 - Default is 1.0.
UPROPERTY ()
Playback pitch for sound.
UPROPERTY () ESoundwaveSampleRateSettings SampleRateQuality
Determines the max sample rate to use if the platform enables "Resampling For Device" in project settings.
UPROPERTY () float SubtitlePriority
The priority of the subtitle.
UPROPERTY () FSoundModulationDefaultRoutingSettings ModulationSettings
Modulation Settings.
UPROPERTY () int32 NumChannels
Number of channels of multichannel data; 1 or 2 for regular mono and stereo files.
UPROPERTY () TArray< FSoundWaveEnvelopeTimeData > CookedEnvelopeTimeData
The cooked cooked envelope data.
UPROPERTY () TArray< FSoundWaveSpectralTimeData > CookedSpectralTimeData
The cooked spectral time data.
UPROPERTY () TArray< struct FSubtitleCue > Subtitles
Subtitle cues.
UPROPERTY ()) FString SpokenText_DEPRECATED
A localized version of the text that is actually spoken phonetically in the audio.
UPROPERTY ()) int32 StreamingPriority
Platform agnostic compression quality.
UPROPERTY ()) mutable ESoundWaveLoadingBehavior LoadingBehavior
Specifies how and when compressed audio data is loaded for asset if stream caching is enabled.
UPROPERTY ()) TArray< float > FrequenciesToAnalyze
The frequencies (in hz) to analyze when doing baked FFT analysis.
UPROPERTY ()) TEnumAsByte< ESoundGroup > SoundGroup
Static Public Member Functions
static FName GetCurvePropertyName ()
Gets the member name for the Curves property of the USoundWave object.
static ESoundWaveLoadingBehavior GetDefaultLoadingBehavior ()
static const TCHAR * GetDefaultLoadingBehaviorCVarName ()
Used to ensure that we recook USoundWaves if the default loading behavior has changed.
static const FPlatformAudioCookOverrides * GetPlatformCompressionOverridesForCurrentPlatform ()
Return the platform compression overrides set for the current platform.
static FName GetPlatformSpecificFormat (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides)
static ITargetPlatform * GetRunningPlatform ()
helper function for getting the cached name of the current platform.
Data Fields
FAsyncAudioDecompress * AudioDecompressor
uint8 bCanProcessAsync: 1
Set to true for procedural waves that can be processed asynchronously.
UPROPERTY() uint8 bMature UPROPERTY() uint8 bManualWordWrap UPROPERTY() uint8 bSingleLine UPROPERTY() uint8 bIsAmbisonics uint8 bDecompressedFromOgg: 1
If set to true if this sound is considered to contain mature/adult content.
uint8 bDynamicResource: 1
Whether to free the resource data after it has been uploaded to the hardware.
uint8 bIsSourceBus: 1
Set to true of this is a bus sound source.
bool bMarkDirty = true)
uint8 bProcedural: 1
Set to true for programmatically generated audio.
uint8 bRequiresStopFade:1
Set to true if fade is required when sound is abruptly stopped.
uint8 * CachedRealtimeFirstBuffer
Pointer to 16 bit PCM data - used to avoid synchronous operation to obtain first block of the realtime decompressed buffer.
FGuid CompressedDataGuid
GUID used to uniquely identify this node so it can be found in the DDC.
TSortedMap< FString, FStreamedAudioPlatformData * > CookedPlatformData
cooked streaming platform data for this sound
std::atomic< int32 > CurrentChunkRevision = 0
The current revision of our compressed audio data.
TEnumAsByte< EDecompressionType > DecompressionType
Type of buffer this wave uses.
int32 NumPrecacheFrames
The number of frames which have been precached for this sound wave.
FThreadSafeCounter NumSourcesPlaying
the number of sounds currently playing this sound wave.
EditAnywhere float Pitch
uint8 * RawPCMData
Pointer to 16 bit PCM data - used to decompress data to and preview sounds.
int32 RawPCMDataSize
Size of RawPCMData, or what RawPCMData would be if the sound was fully decompressed.
int32 ResourceID
Resource index to cross reference with buffers.
int32 TrackedMemoryUsage
Cache the total used memory recorded for this SoundWave to keep INC/DEC consistent.
EditAnywhere float Volume
Protected Member Functions
virtual void SerializeCuePoints (FArchive &Ar, const bool bIsLoadingFromCookedArchive)
UPROPERTY () int32 SampleRate
Cooked sample rate of the asset.
UPROPERTY () TObjectPtr< class UCurveTable > Curves
Curves associated with this sound wave.
UPROPERTY () TObjectPtr< class UCurveTable > InternalCurves
Hold a reference to our internal curve so we can switch back to it if we want to.
Private Types
enum class ESoundWaveResourceState : uint8 { NeedsFree , Freeing , Freed }
Private Member Functions
void BakeEnvelopeAnalysis ()
void BakeFFTAnalysis ()
void CacheInheritedLoadingBehavior () const
void CreateNewSoundWaveData ()
Creates and initializes a new FSoundWaveData and FSoundWaveProxy.
void FlushAsyncLoadingDataFormats ()
void FlushAudioRenderingCommands () const
uint32 GetInterpolatedCookedEnvelopeDataForTimeInternal (float InTime, uint32 StartingIndex, float &OutAmplitude, bool bLoop)
uint32 GetInterpolatedCookedFFTDataForTimeInternal (float InTime, uint32 StartingIndex, TArray< FSoundWaveSpectralData > &OutData, bool bLoop)
Helper functions to search analysis data.
bool RescheduleAsyncTask (FQueuedThreadPool *InThreadPool, EQueuedWorkPriority InPriority)
Utility function used internally to change task priority while maintaining thread-safety.
void UpdateAsset (bool bMarkDirty=true)
UPROPERTY()) uint8 bSeekableStreaming UPROPERTY()) uint8 bUseBinkAudio UPROPERTY () ESoundAssetCompressionType SoundAssetCompressionType
If set, when played directly (not through a sound cue) the wave will be played looping.
bool WaitAsyncTaskWithTimeout (float InTimeoutInSeconds)
Utility function used internally to wait or poll a task while maintaining thread-safety.
Private Attributes
uint8 bCachedSampleRateFromPlatformSettings: 1
uint8 bLoadedFromCookedData: 1
uint8 bNeedsThumbnailGeneration: 1
uint8 bSampleRateManuallyReset: 1
float CachedSampleRateOverride
FThreadSafeCounter PrecacheState
What state the precache decompressor is in.
FSoundWaveProxyPtr Proxy { nullptr }
ESoundWaveResourceState ResourceState: 2
TSharedPtr< FSoundWaveData, ESPMode::ThreadSafe > SoundWaveDataPtr { MakeShared<FSoundWaveData>() }
TArray< FSoundWaveClientPtr > SourcesPlaying
UE::FMutex SourcesPlayingCs
the number of sounds currently playing this sound wave.
FWaveTransformUObjectConfiguration TransformationChainConfig
Friends
class FSoundWaveCompilingManager
class FSoundWaveProxy
class USoundFactory
Detailed Description
Definition at line 416 of file SoundWave.h.
Member Typedef Documentation
FAsyncAudioDecompress
typedef FAsyncTask< class FAsyncAudioDecompressWorker > USoundWave::FAsyncAudioDecompress
Async worker that decompresses the audio data on a different thread.
Definition at line 884 of file SoundWave.h.
FSoundWaveClientPtr
using USoundWave::FSoundWaveClientPtr = ISoundWaveClient*
Definition at line 511 of file SoundWave.h.
Member Enumeration Documentation
ESoundWaveResourceState
enum class USoundWave::ESoundWaveResourceState : uint8 strong private
Enumerator
NeedsFree
Freeing
Freed
Definition at line 717 of file SoundWave.h.
Member Function Documentation
AddPlayingSource() [1/2]
void USoundWave::AddPlayingSource () inline
Definition at line 466 of file SoundWave.h.
References AddPlayingSource(), and NumSourcesPlaying.
Referenced by AddPlayingSource().
AddPlayingSource() [2/2]
void USoundWave::AddPlayingSource (const FSoundWaveClientPtr & Source)
References Source.
BakeEnvelopeAnalysis()
void USoundWave::BakeEnvelopeAnalysis () private
BakeFFTAnalysis()
void USoundWave::BakeFFTAnalysis () private
BeginDestroy()
virtual void USoundWave::BeginDestroy () override virtual
BeginGetCompressedData()
virtual void USoundWave::BeginGetCompressedData (FName Format, const FPlatformAudioCookOverrides * CompressionOverrides, const ITargetPlatform * InTargetPlatform) virtual
References Format.
CacheInheritedLoadingBehavior()
void USoundWave::CacheInheritedLoadingBehavior () const private
CanEditChange()
virtual bool USoundWave::CanEditChange (const FProperty * InProperty) const override virtual
CleanupCachedRunningPlatformData()
void USoundWave::CleanupCachedRunningPlatformData ()
CleanupDecompressor()
bool USoundWave::CleanupDecompressor (bool bForceCleanup = false)
Will clean up the decompressor task if the task has finished or force it finish.
Returns true if the decompressor is cleaned up.
CreateNewCueData()
TArray< uint8 > USoundWave::CreateNewCueData (const char ChunkName[4])
CreateNewSoundWaveData()
void USoundWave::CreateNewSoundWaveData () private
Creates and initializes a new FSoundWaveData and FSoundWaveProxy.
CreateProxyData()
virtual TSharedPtr< Audio::IProxyData > USoundWave::CreateProxyData (const Audio::FProxyDataInitParams & InitParams) override virtual
CreateSoundWaveProxy()
FSoundWaveProxyPtr USoundWave::CreateSoundWaveProxy ()
FinishDestroy()
virtual void USoundWave::FinishDestroy () override virtual
FlushAsyncLoadingDataFormats()
void USoundWave::FlushAsyncLoadingDataFormats () private
FlushAudioRenderingCommands()
void USoundWave::FlushAudioRenderingCommands () const private
FreeResources()
void USoundWave::FreeResources (bool bStopSoundsUsingThisResource = true)
Frees up all the resources allocated in this class.
Parameters
bStopSoundsUsingThisResource if false, will leave any playing audio alive. This occurs when we force a re-cook of audio while starting to play a sound.
GeneratePCMData()
virtual int32 USoundWave::GeneratePCMData (uint8 * PCMData, const int32 SamplesNeeded) inline virtual
This is only used for DTYPE_Procedural audio.
It's recommended to use USynthComponent base class for procedurally generated sound vs overriding this function. If a new component is not feasible, consider using USoundWaveProcedural base class vs USoundWave base class since as it implements GeneratePCMData for you and you only need to return PCM data.
Definition at line 1275 of file SoundWave.h.
References ensure.
GetAssetRegistryTags()
virtual void USoundWave::GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override virtual
Referenced by UE_DEPRECATED().
GetChunkData()
bool USoundWave::GetChunkData (int32 ChunkIndex, uint8 ** OutChunkData, bool bMakeSureChunkIsLoaded = false)
Get Chunk data for a specified chunk index.
Parameters
ChunkIndex The Chunk index to cache.
OutChunkData Address of pointer that will store data.
GetChunkSizeStats()
void USoundWave::GetChunkSizeStats (uint32 & OutTotalBytesOfAudioData, uint32 & OutMaxChunkBytesOfAudioData) const
GetCompressedData()
virtual FByteBulkData * USoundWave::GetCompressedData (FName Format, const FPlatformAudioCookOverrides * CompressionOverrides = GetPlatformCompressionOverridesForCurrentPlatform(), const ITargetPlatform * InTargetPlatform = GetRunningPlatform()) virtual
Gets the compressed data from derived data cache for the specified platform Warning, the returned pointer isn't valid after we add new formats.
Parameters
Format format of compressed data
CompressionOverrides optional platform compression overrides
Returns
compressed data, if it could be obtained
References Format, GetPlatformCompressionOverridesForCurrentPlatform(), and GetRunningPlatform().
Referenced by GetCompressedDataSize().
GetCompressedDataSize()
SIZE_T USoundWave::GetCompressedDataSize (FName Format, const FPlatformAudioCookOverrides * CompressionOverrides = GetPlatformCompressionOverridesForCurrentPlatform()) inline
Gets the compressed data size from derived data cache for the specified format.
Parameters
Format format of compressed data
CompressionOverrides Optional argument for compression overrides.
Returns
compressed data size, or zero if it could not be obtained
Definition at line 1292 of file SoundWave.h.
References Format, FBulkData::GetBulkDataSize(), GetCompressedData(), and GetPlatformCompressionOverridesForCurrentPlatform().
GetCompressionQuality()
int32 USoundWave::GetCompressionQuality () const
GetCurveData()
virtual class UCurveTable * USoundWave::GetCurveData () const inline override virtual
Returns curves associated with this sound wave.
Definition at line 1362 of file SoundWave.h.
References Curves.
GetCurvePropertyName()
FName USoundWave::GetCurvePropertyName () inline static
Gets the member name for the Curves property of the USoundWave object.
Definition at line 1383 of file SoundWave.h.
References Curves, and GET_MEMBER_NAME_CHECKED.
GetDefaultLoadingBehavior()
ESoundWaveLoadingBehavior USoundWave::GetDefaultLoadingBehavior () static
Referenced by FSoundWaveLoadingBehaviorUtil::WalkClassHierarchy().
GetDefaultLoadingBehaviorCVarName()
const TCHAR * USoundWave::GetDefaultLoadingBehaviorCVarName () static
Used to ensure that we recook USoundWaves if the default loading behavior has changed.
Referenced by UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
GetDesc()
virtual FString USoundWave::GetDesc () override virtual
GetDuration()
virtual float USoundWave::GetDuration () const override virtual
Reimplemented in USoundSourceBus.
References GetDuration().
Referenced by GetDuration().
GetExporterName()
virtual FName USoundWave::GetExporterName () override virtual
GetGeneratedPCMDataFormat()
virtual Audio::EAudioMixerStreamDataFormat::Type USoundWave::GetGeneratedPCMDataFormat () const inline virtual
Return the format of the generated PCM data type.
Used in audio mixer to allow generating float buffers and avoid unnecessary format conversions. This feature is only supported in audio mixer. If your procedural sound wave needs to be used in both audio mixer and old audio engine, it's best to generate int16 data as old audio engine only supports int16 formats. Or check at runtime if the audio mixer is enabled. Audio mixer will convert from int16 to float internally.
Definition at line 1283 of file SoundWave.h.
GetHandleForChunkOfAudio()
void USoundWave::GetHandleForChunkOfAudio (TFunction< void(FAudioChunkHandle &&)> OnLoadCompleted, bool bForceSync = false, int32 ChunkIndex = 1, ENamedThreads::Type CallbackThread = ENamedThreads::GameThread)
If stream caching is enabled, allows the user to retain a strong handle to the first chunk of audio in the cache.
Please note that this USoundWave is NOT guaranteed to be still alive when OnLoadCompleted is called.
References GameThread, and GetHandleForChunkOfAudio().
Referenced by GetHandleForChunkOfAudio().
GetImportedSampleRate()
uint32 USoundWave::GetImportedSampleRate () const inline
Definition at line 1200 of file SoundWave.h.
GetImportedSoundWaveData() [1/2]
bool USoundWave::GetImportedSoundWaveData (TArray< uint8 > & OutRawPCMData, uint32 & OutSampleRate, TArray< EAudioSpeakers > & OutChannelOrder) const
Utility which returns imported PCM data and the parsed header for the file.
Returns true if there was data, false if there wasn't.
GetImportedSoundWaveData() [2/2]
bool USoundWave::GetImportedSoundWaveData (TArray< uint8 > & OutRawPCMData, uint32 & OutSampleRate, uint16 & OutNumChannels) const
Utility which returns imported PCM data and the parsed header for the file.
Returns true if there was data, false if there wasn't.
GetInternalCurveData()
class UCurveTable * USoundWave::GetInternalCurveData () const inline
These functions are required for support for some custom details/editor functionality.
Returns internal curves associated with this sound wave
Definition at line 1371 of file SoundWave.h.
GetInterpolatedCookedEnvelopeDataForTime()
bool USoundWave::GetInterpolatedCookedEnvelopeDataForTime (float InTime, uint32 & InOutLastIndex, float & OutAmplitude, bool bLoop)
References GetInterpolatedCookedEnvelopeDataForTime(), and InTime.
Referenced by GetInterpolatedCookedEnvelopeDataForTime().
GetInterpolatedCookedEnvelopeDataForTimeInternal()
uint32 USoundWave::GetInterpolatedCookedEnvelopeDataForTimeInternal (float InTime, uint32 StartingIndex, float & OutAmplitude, bool bLoop) private
References InTime.
GetInterpolatedCookedFFTDataForTime()
bool USoundWave::GetInterpolatedCookedFFTDataForTime (float InTime, uint32 & InOutLastIndex, TArray< FSoundWaveSpectralData > & OutData, bool bLoop)
Helper function to get interpolated cooked FFT data for a given time value.
References GetInterpolatedCookedFFTDataForTime(), and InTime.
Referenced by GetInterpolatedCookedFFTDataForTime().
GetInterpolatedCookedFFTDataForTimeInternal()
uint32 USoundWave::GetInterpolatedCookedFFTDataForTimeInternal (float InTime, uint32 StartingIndex, TArray< FSoundWaveSpectralData > & OutData, bool bLoop) private
Helper functions to search analysis data.
Takes starting index to start query. Returns which data index the result was found at. Returns INDEX_NONE if not found.
References InTime.
GetLoadingBehavior()
ESoundWaveLoadingBehavior USoundWave::GetLoadingBehavior (bool bCheckSoundClasses = true) const
Returns the loading behavior we should use for this sound wave.
If this is called within Serialize(), this should be called with bCheckSoundClasses = false, Since there is no guarantee that the deserialized USoundClasses have been resolved yet.
References GetLoadingBehavior(), and meta.
Referenced by GetLoadingBehavior().
GetNumChunks()
uint32 USoundWave::GetNumChunks () const
GetNumFrames()
uint32 USoundWave::GetNumFrames () const
Return the number of frames.
(can change after decoders read the headers).
GetPlatformCompressionOverridesForCurrentPlatform()
const FPlatformAudioCookOverrides * USoundWave::GetPlatformCompressionOverridesForCurrentPlatform () static
Return the platform compression overrides set for the current platform.
Referenced by FSoundWaveData::GetCompressedData(), FSoundWaveProxy::GetCompressedData(), GetCompressedData(), and GetCompressedDataSize().
GetPlatformSpecificFormat()
FName USoundWave::GetPlatformSpecificFormat (FName Format, const FPlatformAudioCookOverrides * CompressionOverrides) static
References Format.
GetPrecacheState()
ESoundWavePrecacheState USoundWave::GetPrecacheState () const inline
Definition at line 1535 of file SoundWave.h.
References PrecacheState.
GetResourceData()
const uint8 * USoundWave::GetResourceData () const
Memory containing the data copied from the compressed bulk data.
References None, and RawData.
GetResourceSize()
int32 USoundWave::GetResourceSize () const
GetResourceSizeEx()
virtual void USoundWave::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override virtual
GetResourceSizeForFormat()
virtual int32 USoundWave::GetResourceSizeForFormat (FName Format) virtual
Parameters
Format Format to check
Returns
Sum of the size of waves referenced by this cue for the given platform.
References Format.
GetRunningPlatform()
ITargetPlatform * USoundWave::GetRunningPlatform () static
helper function for getting the cached name of the current platform.
Referenced by GetCompressedData(), FSoundWaveData::HasCompressedData(), FSoundWaveProxy::HasCompressedData(), and HasCompressedData().
GetRuntimeFormat()
FName USoundWave::GetRuntimeFormat () const
Returns the Runtime format of the wave.
References GetRuntimeFormat().
Referenced by GetRuntimeFormat().
GetSampleRateForCompressionOverrides()
float USoundWave::GetSampleRateForCompressionOverrides (const FPlatformAudioCookOverrides * CompressionOverrides) const
GetSampleRateForCurrentPlatform()
float USoundWave::GetSampleRateForCurrentPlatform () const
GetSizeOfChunk()
uint32 USoundWave::GetSizeOfChunk (uint32 ChunkIndex) const
GetSoundAssetCompressionTypeEnum()
ESoundAssetCompressionType USoundWave::GetSoundAssetCompressionTypeEnum () const
will return the raw value, (i.e.
does not resolve options such as "Project Defined" to the correct codec)
References GetSoundAssetCompressionTypeEnum().
Referenced by GetSoundAssetCompressionTypeEnum().
GetSoundWaveCuePoints()
TArray< FSoundWaveCuePoint > USoundWave::GetSoundWaveCuePoints () const
GetSoundWavesWithCookedAnalysisData()
virtual bool USoundWave::GetSoundWavesWithCookedAnalysisData (TArray< USoundWave * > & OutSoundWaves) override virtual
References GetSoundWavesWithCookedAnalysisData().
Referenced by GetSoundWavesWithCookedAnalysisData().
GetSubtitlePriority()
virtual float USoundWave::GetSubtitlePriority () const override virtual
References GetSubtitlePriority().
Referenced by GetSubtitlePriority().
GetTransformationChainConfig()
const FWaveTransformUObjectConfiguration & USoundWave::GetTransformationChainConfig () const
GetWaveformTransformationInfo()
FWaveformTransformationInfo USoundWave::GetWaveformTransformationInfo () const
GetZerothChunk()
TArrayView< const uint8 > USoundWave::GetZerothChunk (bool bForImmediatePlayback = false)
This returns the initial chunk of compressed data for streaming data sources.
HandleStart()
FWaveInstance & USoundWave::HandleStart (FActiveSound & ActiveSound, const UPTRINT WaveInstanceHash) const
Handle any special requirements when the sound starts (e.g.
subtitles)
HasCompressedData()
virtual bool USoundWave::HasCompressedData (FName Format, ITargetPlatform * TargetPlatform = GetRunningPlatform()) const virtual
References Format, and GetRunningPlatform().
HasCookedAmplitudeEnvelopeData()
virtual bool USoundWave::HasCookedAmplitudeEnvelopeData () const override virtual
References HasCookedAmplitudeEnvelopeData().
Referenced by HasCookedAmplitudeEnvelopeData().
HasCookedFFTData()
virtual bool USoundWave::HasCookedFFTData () const override virtual
References HasCookedFFTData().
Referenced by HasCookedFFTData().
HasError()
bool USoundWave::HasError () const
HasInternalCurves()
bool USoundWave::HasInternalCurves () const inline
Returns whether this sound wave has internal curves.
Definition at line 1374 of file SoundWave.h.
HasStreamingChunks()
bool USoundWave::HasStreamingChunks ()
InitAudioResource() [1/2]
virtual void USoundWave::InitAudioResource (FByteBulkData & CompressedData) virtual
Copy the compressed audio data from the bulk data.
References CompressedData.
InitAudioResource() [2/2]
virtual bool USoundWave::InitAudioResource (FName Format) virtual
Copy the compressed audio data from derived data cache.
Parameters
Format to get the compressed audio in
Returns
true if the resource has been successfully initialized or it was already initialized.
References Format.
InvalidateCompressedData()
void USoundWave::InvalidateCompressedData (bool bFreeResources = false, bool bRebuildStreamingChunks = true)
Change the guid and flush all compressed data.
Parameters
bFreeResources if true, will delete any precached compressed data as well.
InvalidateSoundWaveIfNeccessary()
void USoundWave::InvalidateSoundWaveIfNeccessary ()
This function can be called before playing or using a SoundWave to check if any cook settings have been modified since this SoundWave was last cooked.
IsAsyncWorkComplete()
bool USoundWave::IsAsyncWorkComplete () const
IInterface_AsyncCompilation end.
IsCompiling()
virtual bool USoundWave::IsCompiling () const override virtual
IInterface_AsyncCompilation begin.
IsCompressedDataReady()
bool USoundWave::IsCompressedDataReady (FName Format, const FPlatformAudioCookOverrides * CompressionOverrides) const
Returns if an async task for a certain platform has finished.
References Format.
IsGeneratingAudio()
bool USoundWave::IsGeneratingAudio () const inline
Definition at line 1184 of file SoundWave.h.
References SourcesPlaying, and SourcesPlayingCs.
IsLoadedFromCookedData()
bool USoundWave::IsLoadedFromCookedData () const
IsPlayable()
virtual bool USoundWave::IsPlayable () const override virtual
Reimplemented in USoundSourceBus.
References IsPlayable().
Referenced by IsPlayable().
IsProcedurallyGenerated()
virtual bool USoundWave::IsProcedurallyGenerated () const inline override virtual
Definition at line 1165 of file SoundWave.h.
References bProcedural, and IsProcedurallyGenerated().
Referenced by IsProcedurallyGenerated().
IsReadyForFinishDestroy()
virtual bool USoundWave::IsReadyForFinishDestroy () override virtual
IsRetainingAudio()
bool USoundWave::IsRetainingAudio ()
References IsRetainingAudio().
Referenced by IsRetainingAudio().
IsSeekable()
virtual bool USoundWave::IsSeekable () const virtual
Queries if Seeking is supported by the Decoder for this Wave.
Returns
true if Seeking is supported, false otherwise.
Reimplemented in USoundSourceBus.
IsStreaming() [1/2]
bool USoundWave::IsStreaming (const FPlatformAudioCookOverrides & Overrides) const
IsStreaming() [2/2]
bool USoundWave::IsStreaming (const TCHAR * PlatformName = nullptr) const
Checks whether sound has been categorized as streaming.
LoadZerothChunk()
bool USoundWave::LoadZerothChunk ()
LogBakedData()
void USoundWave::LogBakedData ()
OnBeginGenerate()
virtual void USoundWave::OnBeginGenerate () inline virtual
Definition at line 1175 of file SoundWave.h.
OnCookEvent()
virtual void USoundWave::OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext & CookContext) override virtual
OnEndGenerate() [1/2]
virtual void USoundWave::OnEndGenerate () inline virtual
Definition at line 1178 of file SoundWave.h.
OnEndGenerate() [2/2]
virtual void USoundWave::OnEndGenerate (ISoundGeneratorPtr Generator) inline virtual
Definition at line 1179 of file SoundWave.h.
OverrideLoadingBehavior()
void USoundWave::OverrideLoadingBehavior (ESoundWaveLoadingBehavior InLoadingBehavior)
If Stream Caching is enabled, this can be used to override the default loading behavior of this USoundWave.
This can even be called on USoundWaves that still have the RF_NeedLoad flag, and won't be stomped by serialization. NOTE: The new behavior will be ignored if it is less memory-aggressive than existing (even inherited) behavior
References OverrideLoadingBehavior().
Referenced by OverrideLoadingBehavior().
OverwriteSoundWaveDataWithTransformationData()
void USoundWave::OverwriteSoundWaveDataWithTransformationData ()
Parse()
virtual void USoundWave::Parse (class FAudioDevice * AudioDevice, const UPTRINT NodeWaveInstanceHash, FActiveSound & ActiveSound, const FSoundParseParameters & ParseParams, TArray< FWaveInstance * > & WaveInstances) override virtual
References Parse().
Referenced by Parse().
PostEditChangeProperty()
virtual void USoundWave::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented in USoundSourceBus.
PostImport()
void USoundWave::PostImport ()
PostInitProperties()
virtual void USoundWave::PostInitProperties () override virtual
PostLoad()
virtual void USoundWave::PostLoad () override virtual
Reimplemented in USoundSourceBus.
PreSave()
virtual void USoundWave::PreSave (FObjectPreSaveContext SaveContext) override virtual
ReleaseCompressedAudio()
void USoundWave::ReleaseCompressedAudio ()
If stream caching is enabled and au.streamcache.KeepFirstChunkInMemory is 1, this will release this USoundWave's first chunk, allowing it to be deleted.
References ReleaseCompressedAudio().
Referenced by ReleaseCompressedAudio().
RemoveAudioResource()
void USoundWave::RemoveAudioResource ()
Remove the compressed audio data associated with the passed in wave.
RemovePlayingSource() [1/2]
void USoundWave::RemovePlayingSource () inline
Definition at line 471 of file SoundWave.h.
References check, and NumSourcesPlaying.
RemovePlayingSource() [2/2]
void USoundWave::RemovePlayingSource (const FSoundWaveClientPtr & Source)
References Source.
RescheduleAsyncTask()
bool USoundWave::RescheduleAsyncTask (FQueuedThreadPool * InThreadPool, EQueuedWorkPriority InPriority) private
Utility function used internally to change task priority while maintaining thread-safety.
Referenced by USTRUCT().
ResetError()
void USoundWave::ResetError ()
RetainCompressedAudio()
void USoundWave::RetainCompressedAudio (bool bForceSync = false)
If stream caching is enabled, set this sound wave to retain a strong handle to its first chunk.
If not called on the game thread, bForceSync must be true.
References RetainCompressedAudio().
Referenced by RetainCompressedAudio().
Serialize()
virtual void USoundWave::Serialize (FArchive & Ar) override virtual
Reimplemented in USoundSourceBus.
References Ar.
SerializeCookedPlatformData()
virtual void USoundWave::SerializeCookedPlatformData (class FArchive & Ar) virtual
Serializes cooked platform data.
Reimplemented in USoundSourceBus.
References Ar.
SerializeCuePoints()
virtual void USoundWave::SerializeCuePoints (FArchive & Ar, const bool bIsLoadingFromCookedArchive) protected virtual
Reimplemented in USoundSourceBus.
References Ar.
SetAllCuePoints()
void USoundWave::SetAllCuePoints (TArray< FSoundWaveCuePoint > InCuePoints) const
References SetAllCuePoints().
Referenced by SetAllCuePoints().
SetCurveData()
void USoundWave::SetCurveData (UCurveTable * InCurves) inline
Sets the curve data for this sound wave.
Definition at line 1377 of file SoundWave.h.
References Curves.
SetError()
void USoundWave::SetError (const TCHAR * InErrorMsg = nullptr)
SetImportedSampleRate()
void USoundWave::SetImportedSampleRate (uint32 InImportedSampleRate) inline
Definition at line 1193 of file SoundWave.h.
SetInternalCurveData()
void USoundWave::SetInternalCurveData (UCurveTable * InCurves) inline
Sets the internal curve data for this sound wave.
Definition at line 1380 of file SoundWave.h.
SetNumFrames()
void USoundWave::SetNumFrames (uint32 InNumFrames)
Overwrite number of frames.
Used for procedural soundwaves, as well as sound waves that are resampled on compress/decompress.
SetPrecacheState()
void USoundWave::SetPrecacheState (ESoundWavePrecacheState InState) inline
Definition at line 1530 of file SoundWave.h.
References PrecacheState.
SetSampleRate()
void USoundWave::SetSampleRate (uint32 InSampleRate, const bool bFromDecoders = false)
Overwrite sample rate.
Used for procedural soundwaves, as well as sound waves that are resampled on compress/decompress.
SetSoundWaveCuePoints()
void USoundWave::SetSoundWaveCuePoints (const TArray< FSoundWaveCuePoint > & InCuePoints)
ShouldUseStreamCaching()
bool USoundWave::ShouldUseStreamCaching () const
Checks whether we should use the load on demand cache.
SupportsSubtitles()
virtual bool USoundWave::SupportsSubtitles () const override virtual
References SupportsSubtitles().
Referenced by SupportsSubtitles().
UE_DEPRECATED()
USoundWave::UE_DEPRECATED (5. 4, "Implement the version that takes FAssetRegistryTagsContext instead.") const & override
References GetAssetRegistryTags().
UFUNCTION() [1/4]
USoundWave::UFUNCTION () const
Returns the sound's asset compression type.
References Category.
Referenced by UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/4]
USoundWave::UFUNCTION () const
Filters for the cue points that are not loop regions and returns those as a new array.
References Category, and UFUNCTION().
UFUNCTION() [3/4]
USoundWave::UFUNCTION () const
Filters for the cue points that are loop regions and returns those as a new array.
References Category.
UFUNCTION() [4/4]
USoundWave::UFUNCTION ()
Procedurally set the compression type.
References Category, and UFUNCTION().
UpdateAsset()
void USoundWave::UpdateAsset (bool bMarkDirty = true) private
References bMarkDirty.
UpdatePlatformData()
void USoundWave::UpdatePlatformData ()
Attempts to update the cached platform data after any changes that might affect it.
UpdateTransformations()
const FWaveTransformUObjectConfiguration & USoundWave::UpdateTransformations ()
UPROPERTY() [1/18]
USoundWave::UPROPERTY ()
Playback volume of sound 0 to 1 - Default is 1.0.
References Category, meta, Sound, and UPROPERTY().
UPROPERTY() [2/18]
USoundWave::UPROPERTY ()
Playback pitch for sound.
References Category, meta, Sound, and UPROPERTY().
UPROPERTY() [3/18]
UPROPERTY()) uint8 bSeekableStreaming UPROPERTY()) uint8 bUseBinkAudio USoundWave::UPROPERTY () private
If set, when played directly (not through a sound cue) the wave will be played looping.
Here for legacy code. The compression type to use for the sound wave asset.
References Category, and UPROPERTY().
UPROPERTY() [4/18]
USoundWave::UPROPERTY ()
Determines the max sample rate to use if the platform enables "Resampling For Device" in project settings.
For example, if the platform enables Resampling For Device and specifies 32000 for High, then setting High here will force the sound wave to be at most 32000. Does nothing if Resampling For Device is disabled.
References Category, and UPROPERTY().
UPROPERTY() [5/18]
USoundWave::UPROPERTY ()
The priority of the subtitle.
References Category, Subtitles, and UPROPERTY().
UPROPERTY() [6/18]
USoundWave::UPROPERTY ()
Modulation Settings.
References Category.
UPROPERTY() [7/18]
USoundWave::UPROPERTY ()
Number of channels of multichannel data; 1 or 2 for regular mono and stereo files.
References Category, Info, and UPROPERTY().
UPROPERTY() [8/18]
USoundWave::UPROPERTY () protected
Cooked sample rate of the asset.
Can be modified by sample rate override.
References Category, and Info.
UPROPERTY() [9/18]
USoundWave::UPROPERTY ()
The cooked cooked envelope data.
References UPROPERTY().
UPROPERTY() [10/18]
USoundWave::UPROPERTY ()
The cooked spectral time data.
References UPROPERTY().
UPROPERTY() [11/18]
USoundWave::UPROPERTY ()
Subtitle cues.
References Category, Info, Subtitles, and UPROPERTY().
UPROPERTY() [12/18]
USoundWave::UPROPERTY () protected
Curves associated with this sound wave.
References Category, and Curves.
UPROPERTY() [13/18]
USoundWave::UPROPERTY () protected
Hold a reference to our internal curve so we can switch back to it if we want to.
References Category, config, GET_MEMBER_NAME_CHECKED, Meta, and ToolTip.
UPROPERTY() [14/18]
USoundWave::UPROPERTY ()
A localized version of the text that is actually spoken phonetically in the audio.
References meta.
UPROPERTY() [15/18]
USoundWave::UPROPERTY ()
Platform agnostic compression quality.
1..100 with 1 being best compression and 100 being best quality. ADPCM and PCM sound asset compression types ignore this parameter.
References meta, and StreamingPriority.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [16/18]
USoundWave::UPROPERTY ()
Specifies how and when compressed audio data is loaded for asset if stream caching is enabled.
References Category, and meta.
UPROPERTY() [17/18]
USoundWave::UPROPERTY ()
The frequencies (in hz) to analyze when doing baked FFT analysis.
References Category, meta, and UPROPERTY().
UPROPERTY() [18/18]
USoundWave::UPROPERTY ()
References Category, meta, Sound, and UPROPERTY().
WaitAsyncTaskWithTimeout()
bool USoundWave::WaitAsyncTaskWithTimeout (float InTimeoutInSeconds) private
Utility function used internally to wait or poll a task while maintaining thread-safety.
Referenced by USTRUCT().
Friends And Related Symbol Documentation
FSoundWaveCompilingManager
friend class FSoundWaveCompilingManager friend
Definition at line 1132 of file SoundWave.h.
References FSoundWaveCompilingManager.
Referenced by FSoundWaveCompilingManager.
FSoundWaveProxy
friend class FSoundWaveProxy friend
Definition at line 1544 of file SoundWave.h.
References FSoundWaveProxy.
Referenced by FSoundWaveProxy.
USoundFactory
friend class USoundFactory friend
Definition at line 1545 of file SoundWave.h.
References USoundFactory.
Referenced by USoundFactory.
Field Documentation
AudioDecompressor
FAsyncAudioDecompress* USoundWave::AudioDecompressor
Definition at line 885 of file SoundWave.h.
bCachedSampleRateFromPlatformSettings
uint8 USoundWave::bCachedSampleRateFromPlatformSettings mutable private
Definition at line 704 of file SoundWave.h.
bCanProcessAsync
uint8 USoundWave::bCanProcessAsync
Set to true for procedural waves that can be processed asynchronously.
Definition at line 665 of file SoundWave.h.
bDecompressedFromOgg
UPROPERTY () uint8 bMature UPROPERTY () uint8 bManualWordWrap UPROPERTY () uint8 bSingleLine UPROPERTY () uint8 bIsAmbisonics uint8 USoundWave::bDecompressedFromOgg
If set to true if this sound is considered to contain mature/adult content.
If set to true will disable automatic generation of line breaks - use if the subtitles have been split manually. If set to true the subtitles display as a sequence of single lines as opposed to multiline. Whether or not this source is ambisonics file format. If set, sound always uses the 'Master Ambisonics Submix' as set in the 'Audio' category of Project Settings' and ignores submix if provided locally or in the referenced SoundClass. Whether this SoundWave was decompressed from OGG.
Definition at line 694 of file SoundWave.h.
bDynamicResource
uint8 USoundWave::bDynamicResource
Whether to free the resource data after it has been uploaded to the hardware.
Definition at line 668 of file SoundWave.h.
bIsSourceBus
uint8 USoundWave::bIsSourceBus
Set to true of this is a bus sound source.
This will result in the sound wave not generating audio for itself, but generate audio through instances. Used only in audio mixer.
Definition at line 662 of file SoundWave.h.
bLoadedFromCookedData
uint8 USoundWave::bLoadedFromCookedData private
Definition at line 714 of file SoundWave.h.
bMarkDirty
bool USoundWave::bMarkDirty = true)
Definition at line 486 of file SoundWave.h.
Referenced by UpdateAsset().
bNeedsThumbnailGeneration
uint8 USoundWave::bNeedsThumbnailGeneration private
Definition at line 711 of file SoundWave.h.
bProcedural
uint8 USoundWave::bProcedural
Set to true for programmatically generated audio.
Definition at line 656 of file SoundWave.h.
Referenced by IsProcedurallyGenerated().
bRequiresStopFade
uint8 USoundWave::bRequiresStopFade
Set to true if fade is required when sound is abruptly stopped.
Definition at line 659 of file SoundWave.h.
bSampleRateManuallyReset
uint8 USoundWave::bSampleRateManuallyReset private
Definition at line 707 of file SoundWave.h.
CachedRealtimeFirstBuffer
uint8* USoundWave::CachedRealtimeFirstBuffer
Pointer to 16 bit PCM data - used to avoid synchronous operation to obtain first block of the realtime decompressed buffer.
Definition at line 888 of file SoundWave.h.
CachedSampleRateOverride
float USoundWave::CachedSampleRateOverride mutable private
Definition at line 642 of file SoundWave.h.
CompressedDataGuid
FGuid USoundWave::CompressedDataGuid
GUID used to uniquely identify this node so it can be found in the DDC.
Definition at line 1080 of file SoundWave.h.
CookedPlatformData
TSortedMap<FString, FStreamedAudioPlatformData*> USoundWave::CookedPlatformData
cooked streaming platform data for this sound
Definition at line 1090 of file SoundWave.h.
CurrentChunkRevision
std::atomic<int32> USoundWave::CurrentChunkRevision = 0
The current revision of our compressed audio data.
Used to tell when a chunk in the cache is stale.
Definition at line 698 of file SoundWave.h.
DecompressionType
TEnumAsByte<EDecompressionType> USoundWave::DecompressionType
Type of buffer this wave uses.
Set once on load
Definition at line 439 of file SoundWave.h.
NumPrecacheFrames
int32 USoundWave::NumPrecacheFrames
The number of frames which have been precached for this sound wave.
Definition at line 891 of file SoundWave.h.
NumSourcesPlaying
FThreadSafeCounter USoundWave::NumSourcesPlaying
the number of sounds currently playing this sound wave.
Definition at line 635 of file SoundWave.h.
Referenced by AddPlayingSource(), and RemovePlayingSource().
Pitch
EditAnywhere float USoundWave::Pitch
Definition at line 757 of file SoundWave.h.
PrecacheState
FThreadSafeCounter USoundWave::PrecacheState private
What state the precache decompressor is in.
Definition at line 631 of file SoundWave.h.
Referenced by GetPrecacheState(), and SetPrecacheState().
Proxy
FSoundWaveProxyPtr USoundWave::Proxy { nullptr } private
Definition at line 507 of file SoundWave.h.
RawPCMData
uint8* USoundWave::RawPCMData
Pointer to 16 bit PCM data - used to decompress data to and preview sounds.
Definition at line 897 of file SoundWave.h.
RawPCMDataSize
int32 USoundWave::RawPCMDataSize
Size of RawPCMData, or what RawPCMData would be if the sound was fully decompressed.
Definition at line 894 of file SoundWave.h.
ResourceID
int32 USoundWave::ResourceID
Resource index to cross reference with buffers.
Definition at line 804 of file SoundWave.h.
ResourceState
ESoundWaveResourceState USoundWave::ResourceState private
Definition at line 724 of file SoundWave.h.
SoundWaveDataPtr
TSharedPtr<FSoundWaveData, ESPMode::ThreadSafe> USoundWave::SoundWaveDataPtr { MakeShared<FSoundWaveData>() } private
Definition at line 1542 of file SoundWave.h.
SourcesPlaying
TArray<FSoundWaveClientPtr> USoundWave::SourcesPlaying private
Definition at line 639 of file SoundWave.h.
Referenced by IsGeneratingAudio().
SourcesPlayingCs
UE::FMutex USoundWave::SourcesPlayingCs mutable private
the number of sounds currently playing this sound wave.
Definition at line 734 of file SoundWave.h.
Referenced by IsGeneratingAudio().
TrackedMemoryUsage
int32 USoundWave::TrackedMemoryUsage
Cache the total used memory recorded for this SoundWave to keep INC/DEC consistent.
Definition at line 809 of file SoundWave.h.
TransformationChainConfig
FWaveTransformUObjectConfiguration USoundWave::TransformationChainConfig private
Definition at line 1328 of file SoundWave.h.
Volume
EditAnywhere float USoundWave::Volume
Definition at line 753 of file SoundWave.h.
The documentation for this class was generated from the following file:
SoundWave.h