Unreal Engine 5.6 C++ API: FNetGUIDCache Class Reference
FNetGUIDCache Class Reference
#include "PackageMapClient.h"
Data Structures
struct FPendingAsyncLoadRequest
Public Types
enum class EAsyncLoadMode : uint8 { UseCVar = 0 , ForceDisable = 1 , ForceEnable = 2 }
enum class ENetworkChecksumMode : uint8 { None = 0 , SaveAndUse = 1 , SaveButIgnore = 2 }
Public Member Functions
FNetGUIDCache (const FNetGUIDCache &)=delete
PRAGMA_DISABLE_DEPRECATION_WARNINGS FNetGUIDCache (FNetGUIDCache &&)=default
FNetGUIDCache (UNetDriver *InDriver)
FNetworkGUID AssignNewNetGUID_Server (UObject *Object)
FNetworkGUID AssignNewNetGUIDFromPath_Server (const FString &PathName, UObject *ObjOuter, UClass *ObjClass)
void AsyncPackageCallback (const FName &PackageName, UPackage *Package, EAsyncLoadingResult::Type Result)
bool CanClientLoadObject (const UObject *Object, const FNetworkGUID &NetGUID) const
void CleanReferences ()
void ClearSyncLoadedGUID (FNetworkGUID NetGUID)
void CollectReferences (class FReferenceCollector &ReferenceCollector)
void ConsumeAsyncLoadDelinquencyAnalytics (FNetAsyncLoadDelinquencyAnalytics &Out)
void CountBytes (FArchive &Ar) const
FString Describe (const FNetworkGUID &NetGUID) const
const TArray< FNetworkGUID > * FindUnmappedStablyNamedGuidsWithOuter (FNetworkGUID OuterGUID) const
FString FullNetGUIDPath (const FNetworkGUID &NetGUID) const
void GenerateFullNetGUIDPath_r (const FNetworkGUID &NetGUID, FString &FullPath) const
const FNetAsyncLoadDelinquencyAnalytics & GetAsyncLoadDelinquencyAnalytics () const
FNetGuidCacheObject const *const GetCacheObject (const FNetworkGUID &NetGUID) const
uint32 GetClassNetworkChecksum (UClass *Class)
FNetworkGUID GetNetGUID (const UObject *Object) const
uint32 GetNetworkChecksum (UObject *Obj)
UObject * GetObjectFromNetGUID (const FNetworkGUID &NetGUID, const bool bIgnoreMustBeMapped)
FNetworkGUID GetOrAssignNetGUID (UObject *Object, const TWeakObjectPtr< UObject > *WeakObjectPtr=nullptr)
FNetworkGUID GetOuterNetGUID (const FNetworkGUID &NetGUID) const
bool IsDynamicObject (const UObject *Object)
bool IsGUIDBroken (const FNetworkGUID &NetGUID, const bool bMustBeRegistered) const
bool IsGUIDLoaded (const FNetworkGUID &NetGUID) const
bool IsGUIDNoLoad (const FNetworkGUID &NetGUID) const
bool IsGUIDPending (const FNetworkGUID &NetGUID) const
bool IsGUIDRegistered (const FNetworkGUID &NetGUID) const
bool IsNetGUIDAuthority () const
FNetGUIDCache & operator= (const FNetGUIDCache &)=delete
FNetGUIDCache & operator= (FNetGUIDCache &&)=default
void RegisterNetGUID_Client (const FNetworkGUID &NetGUID, const UObject *Object)
void RegisterNetGUID_Internal (const FNetworkGUID &NetGUID, const FNetGuidCacheObject &CacheObject)
void RegisterNetGUID_Server (const FNetworkGUID &NetGUID, UObject *Object)
void RegisterNetGUIDFromPath_Client (const FNetworkGUID &NetGUID, const FString &PathName, const FNetworkGUID &OuterGUID, const uint32 NetworkChecksum, const bool bNoLoad, const bool bIgnoreWhenMissing)
void RegisterNetGUIDFromPath_Server (const FNetworkGUID &NetGUID, const FString &PathName, const FNetworkGUID &OuterGUID, const uint32 NetworkChecksum, const bool bNoLoad, const bool bIgnoreWhenMissing)
const void RemoveUnmappedStablyNamedGuidsWithOuter (FNetworkGUID OuterGUID)
void ReportSyncLoadedGUIDs ()
If LogNetSyncLoads is enabled, log all objects that caused a sync load that haven't been otherwise reported by the package map yet, and clear that list.
void ResetAsyncLoadDelinquencyAnalytics ()
void ResetCacheForDemo ()
void ResetReplayDirtyTracking ()
void SetAsyncLoadMode (const EAsyncLoadMode NewMode)
void SetNetworkChecksumMode (const ENetworkChecksumMode NewMode)
bool ShouldAsyncLoad () const
bool ShouldIgnoreWhenMissing (const FNetworkGUID &NetGUID) const
bool SupportsObject (const UObject *Object, const TWeakObjectPtr< UObject > *WeakObjectPtr=nullptr) const
TSharedRef< FQueuedBunchObjectReference > TrackQueuedBunchObjectReference (const FNetworkGUID InNetGUID, UObject *InObject)
UE_DEPRECATED (5.3, "No longer used") int32 UniqueNetIDs[2]
bool WasGUIDSyncLoaded (FNetworkGUID NetGUID) const
Static Public Member Functions
static const bool IsHistoryEnabled ()
Data Fields
EAsyncLoadMode AsyncLoadMode
UNetDriver * Driver
TMap< FNetworkGUID, FString > History
TSet< FNetworkGUID > ImportedNetGuids
bool IsExportingNetGUIDBunch
TMap< TWeakObjectPtr< UObject >, FNetworkGUID > NetGUIDLookup
ENetworkChecksumMode NetworkChecksumMode
TMap< FNetworkGUID, FNetGuidCacheObject > ObjectLookup
TMap< FNetworkGUID, TSet< FNetworkGUID > > PendingOuterNetGuids
Private Member Functions
void StartAsyncLoadingPackage (FNetGuidCacheObject &Object, const FNetworkGUID ObjectGUID, const bool bWasAlreadyAsyncLoading)
void UpdateQueuedBunchObjectReference (const FNetworkGUID NetGUID, UObject *NewObject)
void ValidateAsyncLoadingPackage (FNetGuidCacheObject &Object, const FNetworkGUID ObjectGUID)
Private Attributes
FNetAsyncLoadDelinquencyAnalytics DelinquentAsyncLoads
TMap< uint32, FNetFieldExportGroup * > NetFieldExportGroupIndexToGroup
Maps assigned net field export group index to pointer to group, lifetime of the referenced FNetFieldExportGroups are managed by NetFieldExportGroupMap.
TMap< FString, TSharedPtr< FNetFieldExportGroup > > NetFieldExportGroupMap
Maps net field export group name to the respective FNetFieldExportGroup.
TMap< FString, uint32 > NetFieldExportGroupPathToIndex
Maps field export group path to assigned index.
uint64 NetworkGuidIndex [2]
TMap< FName, FPendingAsyncLoadRequest > PendingAsyncLoadRequests
Set of packages that are currently pending Async loads, referenced by package name.
TMap< FName, FNetworkGUID > PendingAsyncPackages
TMap< FNetworkGUID, TWeakPtr< FQueuedBunchObjectReference > > QueuedBunchObjectReferences
Set of all current Objects that we've been requested to be referenced while channels resolve their queued bunches.
TArray< FNetworkGUID > SyncLoadedGUIDs
Store all GUIDs that caused the sync loading of a package, for debugging & logging with LogNetSyncLoads.
int32 UniqueNetFieldExportGroupPathIndex
Current index used when filling in NetFieldExportGroupPathToIndex/NetFieldExportGroupIndexToPath.
TMap< FNetworkGUID, UE::Net::Private::FRefCountedNetGUIDArray > UnmappedStablyNamedGuids_OuterToInner
Map of outer GUIDs to their unmapped, stably named subobjects.
Friends
class UPackageMapClient
Detailed Description
Definition at line 194 of file PackageMapClient.h.
Member Enumeration Documentation
EAsyncLoadMode
enum class FNetGUIDCache::EAsyncLoadMode : uint8 strong
Enumerator
UseCVar
ForceDisable
ForceEnable
Definition at line 213 of file PackageMapClient.h.
ENetworkChecksumMode
enum class FNetGUIDCache::ENetworkChecksumMode : uint8 strong
Enumerator
None
SaveAndUse
SaveButIgnore
Definition at line 206 of file PackageMapClient.h.
Constructor & Destructor Documentation
FNetGUIDCache() [1/3]
FNetGUIDCache::FNetGUIDCache (UNetDriver * InDriver)
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by FNetGUIDCache(), FNetGUIDCache(), operator=(), and operator=().
FNetGUIDCache() [2/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FNetGUIDCache::FNetGUIDCache (FNetGUIDCache &&) default
References FNetGUIDCache().
FNetGUIDCache() [3/3]
FNetGUIDCache::FNetGUIDCache (const FNetGUIDCache &) delete
References FNetGUIDCache().
Member Function Documentation
AssignNewNetGUID_Server()
FNetworkGUID FNetGUIDCache::AssignNewNetGUID_Server (UObject * Object)
References Object.
AssignNewNetGUIDFromPath_Server()
FNetworkGUID FNetGUIDCache::AssignNewNetGUIDFromPath_Server (const FString & PathName, UObject * ObjOuter, UClass * ObjClass)
AsyncPackageCallback()
void FNetGUIDCache::AsyncPackageCallback (const FName & PackageName, UPackage * Package, EAsyncLoadingResult::Type Result)
References Package, and PackageName.
CanClientLoadObject()
bool FNetGUIDCache::CanClientLoadObject (const UObject * Object, const FNetworkGUID & NetGUID) const
References Object.
CleanReferences()
void FNetGUIDCache::CleanReferences ()
ClearSyncLoadedGUID()
void FNetGUIDCache::ClearSyncLoadedGUID (FNetworkGUID NetGUID) inline
Definition at line 266 of file PackageMapClient.h.
References SyncLoadedGUIDs.
CollectReferences()
void FNetGUIDCache::CollectReferences (class FReferenceCollector & ReferenceCollector)
ConsumeAsyncLoadDelinquencyAnalytics()
void FNetGUIDCache::ConsumeAsyncLoadDelinquencyAnalytics (FNetAsyncLoadDelinquencyAnalytics & Out)
CountBytes()
void FNetGUIDCache::CountBytes (FArchive & Ar) const
References Ar.
Describe()
FString FNetGUIDCache::Describe (const FNetworkGUID & NetGUID) const
FindUnmappedStablyNamedGuidsWithOuter()
const TArray< FNetworkGUID > * FNetGUIDCache::FindUnmappedStablyNamedGuidsWithOuter (FNetworkGUID OuterGUID) const
FullNetGUIDPath()
FString FNetGUIDCache::FullNetGUIDPath (const FNetworkGUID & NetGUID) const
GenerateFullNetGUIDPath_r()
void FNetGUIDCache::GenerateFullNetGUIDPath_r (const FNetworkGUID & NetGUID, FString & FullPath) const
GetAsyncLoadDelinquencyAnalytics()
const FNetAsyncLoadDelinquencyAnalytics & FNetGUIDCache::GetAsyncLoadDelinquencyAnalytics () const
GetCacheObject()
FNetGuidCacheObject const *const FNetGUIDCache::GetCacheObject (const FNetworkGUID & NetGUID) const
GetClassNetworkChecksum()
uint32 FNetGUIDCache::GetClassNetworkChecksum (UClass * Class)
References Class.
GetNetGUID()
FNetworkGUID FNetGUIDCache::GetNetGUID (const UObject * Object) const
References Object.
GetNetworkChecksum()
uint32 FNetGUIDCache::GetNetworkChecksum (UObject * Obj)
GetObjectFromNetGUID()
UObject * FNetGUIDCache::GetObjectFromNetGUID (const FNetworkGUID & NetGUID, const bool bIgnoreMustBeMapped)
GetOrAssignNetGUID()
FNetworkGUID FNetGUIDCache::GetOrAssignNetGUID (UObject * Object, const TWeakObjectPtr< UObject > * WeakObjectPtr = nullptr)
Parameters
WeakObjectPtr Optional: pass in existing weakptr to prevent this function from constructing one internally
References Object, and WeakObjectPtr.
GetOuterNetGUID()
FNetworkGUID FNetGUIDCache::GetOuterNetGUID (const FNetworkGUID & NetGUID) const
IsDynamicObject()
bool FNetGUIDCache::IsDynamicObject (const UObject * Object)
References Object.
IsGUIDBroken()
bool FNetGUIDCache::IsGUIDBroken (const FNetworkGUID & NetGUID, const bool bMustBeRegistered) const
IsGUIDLoaded()
bool FNetGUIDCache::IsGUIDLoaded (const FNetworkGUID & NetGUID) const
IsGUIDNoLoad()
bool FNetGUIDCache::IsGUIDNoLoad (const FNetworkGUID & NetGUID) const
IsGUIDPending()
bool FNetGUIDCache::IsGUIDPending (const FNetworkGUID & NetGUID) const
IsGUIDRegistered()
bool FNetGUIDCache::IsGUIDRegistered (const FNetworkGUID & NetGUID) const
IsHistoryEnabled()
const bool FNetGUIDCache::IsHistoryEnabled () static
IsNetGUIDAuthority()
bool FNetGUIDCache::IsNetGUIDAuthority () const
operator=() [1/2]
FNetGUIDCache & FNetGUIDCache::operator= (const FNetGUIDCache &) delete
References FNetGUIDCache(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FNetGUIDCache & FNetGUIDCache::operator= (FNetGUIDCache &&) default
References FNetGUIDCache().
RegisterNetGUID_Client()
void FNetGUIDCache::RegisterNetGUID_Client (const FNetworkGUID & NetGUID, const UObject * Object)
References Object.
RegisterNetGUID_Internal()
void FNetGUIDCache::RegisterNetGUID_Internal (const FNetworkGUID & NetGUID, const FNetGuidCacheObject & CacheObject)
RegisterNetGUID_Server()
void FNetGUIDCache::RegisterNetGUID_Server (const FNetworkGUID & NetGUID, UObject * Object)
References Object.
RegisterNetGUIDFromPath_Client()
void FNetGUIDCache::RegisterNetGUIDFromPath_Client (const FNetworkGUID & NetGUID, const FString & PathName, const FNetworkGUID & OuterGUID, const uint32 NetworkChecksum, const bool bNoLoad, const bool bIgnoreWhenMissing)
RegisterNetGUIDFromPath_Server()
void FNetGUIDCache::RegisterNetGUIDFromPath_Server (const FNetworkGUID & NetGUID, const FString & PathName, const FNetworkGUID & OuterGUID, const uint32 NetworkChecksum, const bool bNoLoad, const bool bIgnoreWhenMissing)
RemoveUnmappedStablyNamedGuidsWithOuter()
const void FNetGUIDCache::RemoveUnmappedStablyNamedGuidsWithOuter (FNetworkGUID OuterGUID) inline
Definition at line 277 of file PackageMapClient.h.
References UnmappedStablyNamedGuids_OuterToInner.
ReportSyncLoadedGUIDs()
void FNetGUIDCache::ReportSyncLoadedGUIDs ()
If LogNetSyncLoads is enabled, log all objects that caused a sync load that haven't been otherwise reported by the package map yet, and clear that list.
ResetAsyncLoadDelinquencyAnalytics()
void FNetGUIDCache::ResetAsyncLoadDelinquencyAnalytics ()
ResetCacheForDemo()
void FNetGUIDCache::ResetCacheForDemo ()
ResetReplayDirtyTracking()
void FNetGUIDCache::ResetReplayDirtyTracking ()
SetAsyncLoadMode()
void FNetGUIDCache::SetAsyncLoadMode (const EAsyncLoadMode NewMode)
SetNetworkChecksumMode()
void FNetGUIDCache::SetNetworkChecksumMode (const ENetworkChecksumMode NewMode)
ShouldAsyncLoad()
bool FNetGUIDCache::ShouldAsyncLoad () const
ShouldIgnoreWhenMissing()
bool FNetGUIDCache::ShouldIgnoreWhenMissing (const FNetworkGUID & NetGUID) const
StartAsyncLoadingPackage()
void FNetGUIDCache::StartAsyncLoadingPackage (FNetGuidCacheObject & Object, const FNetworkGUID ObjectGUID, const bool bWasAlreadyAsyncLoading) private
References Object.
SupportsObject()
bool FNetGUIDCache::SupportsObject (const UObject * Object, const TWeakObjectPtr< UObject > * WeakObjectPtr = nullptr) const
Parameters
WeakObjectPtr Optional: pass in existing weakptr to prevent this function from constructing one internally
References Object, and WeakObjectPtr.
TrackQueuedBunchObjectReference()
TSharedRef< FQueuedBunchObjectReference > FNetGUIDCache::TrackQueuedBunchObjectReference (const FNetworkGUID InNetGUID, UObject * InObject)
UE_DEPRECATED()
FNetGUIDCache::UE_DEPRECATED (5. 3, "No longer used")
UpdateQueuedBunchObjectReference()
void FNetGUIDCache::UpdateQueuedBunchObjectReference (const FNetworkGUID NetGUID, UObject * NewObject) private
References NewObject().
ValidateAsyncLoadingPackage()
void FNetGUIDCache::ValidateAsyncLoadingPackage (FNetGuidCacheObject & Object, const FNetworkGUID ObjectGUID) private
References Object.
WasGUIDSyncLoaded()
bool FNetGUIDCache::WasGUIDSyncLoaded (FNetworkGUID NetGUID) const inline
Definition at line 265 of file PackageMapClient.h.
References SyncLoadedGUIDs.
Friends And Related Symbol Documentation
UPackageMapClient
friend class UPackageMapClient friend
Definition at line 297 of file PackageMapClient.h.
References UPackageMapClient.
Referenced by UPackageMapClient.
Field Documentation
AsyncLoadMode
EAsyncLoadMode FNetGUIDCache::AsyncLoadMode
Definition at line 291 of file PackageMapClient.h.
DelinquentAsyncLoads
FNetAsyncLoadDelinquencyAnalytics FNetGUIDCache::DelinquentAsyncLoads private
Definition at line 366 of file PackageMapClient.h.
Driver
UNetDriver* FNetGUIDCache::Driver
Definition at line 288 of file PackageMapClient.h.
History
TMap<FNetworkGUID, FString> FNetGUIDCache::History
Definition at line 324 of file PackageMapClient.h.
ImportedNetGuids
TSet< FNetworkGUID > FNetGUIDCache::ImportedNetGuids
Definition at line 285 of file PackageMapClient.h.
IsExportingNetGUIDBunch
bool FNetGUIDCache::IsExportingNetGUIDBunch
Definition at line 293 of file PackageMapClient.h.
NetFieldExportGroupIndexToGroup
TMap< uint32, FNetFieldExportGroup* > FNetGUIDCache::NetFieldExportGroupIndexToGroup private
Maps assigned net field export group index to pointer to group, lifetime of the referenced FNetFieldExportGroups are managed by NetFieldExportGroupMap.
Definition at line 310 of file PackageMapClient.h.
NetFieldExportGroupMap
TMap< FString, TSharedPtr< FNetFieldExportGroup > > FNetGUIDCache::NetFieldExportGroupMap private
Maps net field export group name to the respective FNetFieldExportGroup.
Definition at line 304 of file PackageMapClient.h.
NetFieldExportGroupPathToIndex
TMap< FString, uint32 > FNetGUIDCache::NetFieldExportGroupPathToIndex private
Maps field export group path to assigned index.
Definition at line 307 of file PackageMapClient.h.
NetGUIDLookup
TMap< TWeakObjectPtr< UObject >, FNetworkGUID > FNetGUIDCache::NetGUIDLookup
Definition at line 280 of file PackageMapClient.h.
NetworkChecksumMode
ENetworkChecksumMode FNetGUIDCache::NetworkChecksumMode
Definition at line 290 of file PackageMapClient.h.
NetworkGuidIndex
uint64 FNetGUIDCache::NetworkGuidIndex[2] private
Definition at line 299 of file PackageMapClient.h.
ObjectLookup
TMap< FNetworkGUID, FNetGuidCacheObject > FNetGUIDCache::ObjectLookup
Definition at line 279 of file PackageMapClient.h.
PendingAsyncLoadRequests
TMap<FName, FPendingAsyncLoadRequest> FNetGUIDCache::PendingAsyncLoadRequests private
Set of packages that are currently pending Async loads, referenced by package name.
Definition at line 364 of file PackageMapClient.h.
PendingAsyncPackages
TMap<FName, FNetworkGUID> FNetGUIDCache::PendingAsyncPackages private
Definition at line 301 of file PackageMapClient.h.
PendingOuterNetGuids
TMap< FNetworkGUID, TSet< FNetworkGUID > > FNetGUIDCache::PendingOuterNetGuids
Definition at line 286 of file PackageMapClient.h.
QueuedBunchObjectReferences
TMap<FNetworkGUID, TWeakPtr<FQueuedBunchObjectReference> > FNetGUIDCache::QueuedBunchObjectReferences private
Set of all current Objects that we've been requested to be referenced while channels resolve their queued bunches.
This is used to prevent objects (especially async load objects, which may have no other references) from being GC'd while a channel is waiting for more pending guids.
Definition at line 379 of file PackageMapClient.h.
SyncLoadedGUIDs
TArray<FNetworkGUID> FNetGUIDCache::SyncLoadedGUIDs private
Store all GUIDs that caused the sync loading of a package, for debugging & logging with LogNetSyncLoads.
Definition at line 316 of file PackageMapClient.h.
Referenced by ClearSyncLoadedGUID(), and WasGUIDSyncLoaded().
UniqueNetFieldExportGroupPathIndex
int32 FNetGUIDCache::UniqueNetFieldExportGroupPathIndex private
Current index used when filling in NetFieldExportGroupPathToIndex/NetFieldExportGroupIndexToPath.
Definition at line 313 of file PackageMapClient.h.
UnmappedStablyNamedGuids_OuterToInner
TMap<FNetworkGUID, UE::Net::Private::FRefCountedNetGUIDArray> FNetGUIDCache::UnmappedStablyNamedGuids_OuterToInner private
Map of outer GUIDs to their unmapped, stably named subobjects.
So that the inner objects can be remapped when their outer GUID is imported again.
Definition at line 385 of file PackageMapClient.h.
Referenced by RemoveUnmappedStablyNamedGuidsWithOuter().
The documentation for this class was generated from the following file:
PackageMapClient.h