Unreal Engine 5.6 C++ API: UE::Logging::Private::FMemoryLogTemplateStorage Class Reference
UE::Logging::Private::FMemoryLogTemplateStorage Class Reference
Store a log template in a detachable allocation from FMemory.
#include "StructuredLogFormat.h"
Public Member Functions
FMemoryLogTemplateStorage ()=default
FMemoryLogTemplateStorage (const FMemoryLogTemplateStorage &)=delete
~FMemoryLogTemplateStorage ()
void * Allocate (int32 Size)
void * Detach ()
const void * Get () const
FMemoryLogTemplateStorage & operator= (const FMemoryLogTemplateStorage &)=delete
Static Public Member Functions
static void Free (void *D)
Private Attributes
void * Data = nullptr
Detailed Description
Store a log template in a detachable allocation from FMemory.
Definition at line 68 of file StructuredLogFormat.h.
Constructor & Destructor Documentation
FMemoryLogTemplateStorage() [1/2]
UE::Logging::Private::FMemoryLogTemplateStorage::FMemoryLogTemplateStorage () default
Referenced by FMemoryLogTemplateStorage(), and operator=().
FMemoryLogTemplateStorage() [2/2]
UE::Logging::Private::FMemoryLogTemplateStorage::FMemoryLogTemplateStorage (const FMemoryLogTemplateStorage &) delete
References FMemoryLogTemplateStorage().
~FMemoryLogTemplateStorage()
UE::Logging::Private::FMemoryLogTemplateStorage::~FMemoryLogTemplateStorage () inline
Definition at line 75 of file StructuredLogFormat.h.
References Data, and Free().
Member Function Documentation
Allocate()
void * UE::Logging::Private::FMemoryLogTemplateStorage::Allocate (int32 Size) inline
Definition at line 80 of file StructuredLogFormat.h.
References Data, Free(), and TSequenceHistory< HistorySize >::Size.
Detach()
void * UE::Logging::Private::FMemoryLogTemplateStorage::Detach () inline
Definition at line 92 of file StructuredLogFormat.h.
References Data, and ON_SCOPE_EXIT.
Free()
void UE::Logging::Private::FMemoryLogTemplateStorage::Free (void * D) inline static
Definition at line 98 of file StructuredLogFormat.h.
References FMemory::Free().
Referenced by ~FMemoryLogTemplateStorage(), and Allocate().
Get()
const void * UE::Logging::Private::FMemoryLogTemplateStorage::Get () const inline
Definition at line 87 of file StructuredLogFormat.h.
References Data.
operator=()
FMemoryLogTemplateStorage & UE::Logging::Private::FMemoryLogTemplateStorage::operator= (const FMemoryLogTemplateStorage &) delete
References FMemoryLogTemplateStorage().
Field Documentation
Data
void* UE::Logging::Private::FMemoryLogTemplateStorage::Data = nullptr private
Definition at line 107 of file StructuredLogFormat.h.
Referenced by ~FMemoryLogTemplateStorage(), Allocate(), Detach(), and Get().
The documentation for this class was generated from the following file:
StructuredLogFormat.h