Unreal Engine 5.6 C++ API: UE::MovieScene::FDirectedGraph Struct Reference
UE::MovieScene::FDirectedGraph Struct Reference
Directed graph represented as a bitarray for allocated nodes, and edges defined by pairs of integers (from->to).
#include "MovieSceneEntitySystemDirectedGraph.h"
Data Structures
struct FBreadthFirstSearch
struct FDepthFirstSearch
struct FDirectionalEdge
struct FDiscoverCyclicEdges
Public Member Functions
FDirectedGraph ()
MOVIESCENE_API void AllocateNode (uint16 NodeID)
MOVIESCENE_API void CleanUpDanglingEdges ()
MOVIESCENE_API void DestroyAllEdges ()
MOVIESCENE_API void DestroyEdge (uint16 FromNode, uint16 ToNode)
MOVIESCENE_API TBitArray FindEdgeUpstreamNodes () const
MOVIESCENE_API TArrayView< const FDirectionalEdge > GetEdges () const
MOVIESCENE_API TArrayView< const FDirectionalEdge > GetEdgesFrom (uint16 InNode) const
const TBitArray & GetNodeMask () const
MOVIESCENE_API bool HasEdgeFrom (uint16 InNode) const
MOVIESCENE_API bool HasEdgeTo (uint16 InNode) const
MOVIESCENE_API bool IsCyclic () const
MOVIESCENE_API bool IsNodeAllocated (uint16 NodeID) const
MOVIESCENE_API void MakeEdge (uint16 FromNode, uint16 ToNode)
MOVIESCENE_API void RemoveNode (uint16 NodeID)
MOVIESCENE_API FString ToString (const UE::MovieScene::FDirectedGraphStringParameters &Parameters) const
MOVIESCENE_API FString ToString (const UE::MovieScene::FDirectedGraphStringParameters &Parameters, TFunctionRef< void(uint16, FStringBuilderBase &)> EmitLabel) const
Private Member Functions
MOVIESCENE_API bool EdgeExists (const FDirectionalEdge &Edge) const
MOVIESCENE_API int32 FindEdgeIndex (const FDirectionalEdge &Edge) const
MOVIESCENE_API int32 FindEdgeStart (uint16 FromNode) const
MOVIESCENE_API bool IsCyclicImpl (uint16 NodeID, TBitArray<> &Visiting) const
Private Attributes
bool bHasDanglingEdges
friend FBreadthFirstSearch
friend FDepthFirstSearch
friend FDiscoverCyclicEdges
TBitArray Nodes
TArray< FDirectionalEdge > SortedEdges
Detailed Description
Directed graph represented as a bitarray for allocated nodes, and edges defined by pairs of integers (from->to).
Definition at line 24 of file MovieSceneEntitySystemDirectedGraph.h.
Constructor & Destructor Documentation
FDirectedGraph()
UE::MovieScene::FDirectedGraph::FDirectedGraph () inline
Definition at line 132 of file MovieSceneEntitySystemDirectedGraph.h.
References bHasDanglingEdges.
Referenced by UE::MovieScene::FDirectedGraph::FBreadthFirstSearch::FBreadthFirstSearch(), UE::MovieScene::FDirectedGraph::FDepthFirstSearch::FDepthFirstSearch(), and UE::MovieScene::FDirectedGraph::FDiscoverCyclicEdges::FDiscoverCyclicEdges().
Member Function Documentation
AllocateNode()
MOVIESCENE_API void UE::MovieScene::FDirectedGraph::AllocateNode (uint16 NodeID)
CleanUpDanglingEdges()
MOVIESCENE_API void UE::MovieScene::FDirectedGraph::CleanUpDanglingEdges ()
DestroyAllEdges()
MOVIESCENE_API void UE::MovieScene::FDirectedGraph::DestroyAllEdges ()
DestroyEdge()
MOVIESCENE_API void UE::MovieScene::FDirectedGraph::DestroyEdge (uint16 FromNode, uint16 ToNode)
EdgeExists()
MOVIESCENE_API bool UE::MovieScene::FDirectedGraph::EdgeExists (const FDirectionalEdge & Edge) const private
References Edge.
FindEdgeIndex()
MOVIESCENE_API int32 UE::MovieScene::FDirectedGraph::FindEdgeIndex (const FDirectionalEdge & Edge) const private
References Edge.
FindEdgeStart()
MOVIESCENE_API int32 UE::MovieScene::FDirectedGraph::FindEdgeStart (uint16 FromNode) const private
FindEdgeUpstreamNodes()
MOVIESCENE_API TBitArray UE::MovieScene::FDirectedGraph::FindEdgeUpstreamNodes () const
GetEdges()
MOVIESCENE_API TArrayView< const FDirectionalEdge > UE::MovieScene::FDirectedGraph::GetEdges () const
GetEdgesFrom()
MOVIESCENE_API TArrayView< const FDirectionalEdge > UE::MovieScene::FDirectedGraph::GetEdgesFrom (uint16 InNode) const
GetNodeMask()
const TBitArray & UE::MovieScene::FDirectedGraph::GetNodeMask () const inline
Definition at line 144 of file MovieSceneEntitySystemDirectedGraph.h.
References Nodes.
HasEdgeFrom()
MOVIESCENE_API bool UE::MovieScene::FDirectedGraph::HasEdgeFrom (uint16 InNode) const
HasEdgeTo()
MOVIESCENE_API bool UE::MovieScene::FDirectedGraph::HasEdgeTo (uint16 InNode) const
IsCyclic()
MOVIESCENE_API bool UE::MovieScene::FDirectedGraph::IsCyclic () const
IsCyclicImpl()
MOVIESCENE_API bool UE::MovieScene::FDirectedGraph::IsCyclicImpl (uint16 NodeID, TBitArray<> & Visiting) const private
IsNodeAllocated()
MOVIESCENE_API bool UE::MovieScene::FDirectedGraph::IsNodeAllocated (uint16 NodeID) const
MakeEdge()
MOVIESCENE_API void UE::MovieScene::FDirectedGraph::MakeEdge (uint16 FromNode, uint16 ToNode)
RemoveNode()
MOVIESCENE_API void UE::MovieScene::FDirectedGraph::RemoveNode (uint16 NodeID)
ToString() [1/2]
MOVIESCENE_API FString UE::MovieScene::FDirectedGraph::ToString (const UE::MovieScene::FDirectedGraphStringParameters & Parameters) const
ToString() [2/2]
MOVIESCENE_API FString UE::MovieScene::FDirectedGraph::ToString (const UE::MovieScene::FDirectedGraphStringParameters & Parameters, TFunctionRef< void(uint16, FStringBuilderBase &)> EmitLabel) const
Field Documentation
bHasDanglingEdges
bool UE::MovieScene::FDirectedGraph::bHasDanglingEdges private
Definition at line 189 of file MovieSceneEntitySystemDirectedGraph.h.
Referenced by FDirectedGraph().
FBreadthFirstSearch
friend UE::MovieScene::FDirectedGraph::FBreadthFirstSearch private
Definition at line 184 of file MovieSceneEntitySystemDirectedGraph.h.
FDepthFirstSearch
friend UE::MovieScene::FDirectedGraph::FDepthFirstSearch private
Definition at line 183 of file MovieSceneEntitySystemDirectedGraph.h.
FDiscoverCyclicEdges
friend UE::MovieScene::FDirectedGraph::FDiscoverCyclicEdges private
Definition at line 185 of file MovieSceneEntitySystemDirectedGraph.h.
Nodes
TBitArray UE::MovieScene::FDirectedGraph::Nodes private
Definition at line 187 of file MovieSceneEntitySystemDirectedGraph.h.
Referenced by GetNodeMask().
SortedEdges
TArray<FDirectionalEdge> UE::MovieScene::FDirectedGraph::SortedEdges private
Definition at line 188 of file MovieSceneEntitySystemDirectedGraph.h.
The documentation for this struct was generated from the following file:
MovieSceneEntitySystemDirectedGraph.h