Unreal Engine 5.6 C++ API: FHittestGrid Class Reference
FHittestGrid Class Reference
#include "HittestGrid.h"
Data Structures
struct FAppendedGridData
struct FCell
All the available space is partitioned into Cells.
struct FDebuggingFindNextFocusableWidgetArgs
struct FIndexAndDistance
struct FWidgetData
Widget Data we maintain internally store along with the widget reference.
struct FWidgetIndex
Public Member Functions
FHittestGrid ()
void AddGrid (const TSharedRef< const FHittestGrid > &OtherGrid)
Add an already existing grid that occupy the same space.
void AddWidget (const SWidget *InWidget, int32 InBatchPriorityGroup, int32 InLayerId, FSlateInvalidationWidgetSortOrder InSecondarySort)
Add SWidget from the HitTest Grid.
void Clear ()
Clear the grid.
bool ContainsWidget (const SWidget *InWidget) const
Check if SWidget is contained within the HitTest Grid.
TSharedPtr< SWidget > FindNextFocusableWidget (const FArrangedWidget &StartingWidget, const EUINavigation Direction, const FNavigationReply &NavigationReply, const FArrangedWidget &RuleWidget, int32 UserIndex)
Finds the next focusable widget by searching through the hit test grid.
TArray< FWidgetAndPointer > GetBubblePath (UE::Slate::FDeprecateVector2DParameter DesktopSpaceCoordinate, float CursorRadius, bool bIgnoreEnabledStatus, int32 UserIndex=INDEX_NONE)
Given a Slate Units coordinate in virtual desktop space, perform a hittest and return the path along which the corresponding event would be bubbled.
UE::Slate::FDeprecateVector2DResult GetGridOrigin () const
UE::Slate::FDeprecateVector2DResult GetGridSize () const
UE::Slate::FDeprecateVector2DResult GetGridWindowOrigin () const
int32 GetUserIndex () const
Gets current slate user index that should be associated with any added widgets.
void InsertCustomHitTestPath (const SWidget *InWidget, const TSharedRef< ICustomHitTestPath > &CustomHitTestPath)
Insert custom hit test data for a widget already in the grid.
void RemoveGrid (const SWidget *OtherGridOwner)
Remove a grid that was appended.
void RemoveGrid (const TSharedRef< const FHittestGrid > &OtherGrid)
Remove a grid that was appended.
void RemoveWidget (const SWidget *InWidget)
Remove SWidget from the HitTest Grid.
void SetCullingRect (const FSlateRect &InCullingRect)
Set the culling rect to be used by the parent grid (in case we are appended to another grid).
bool SetHittestArea (const UE::Slate::FDeprecateVector2DParameter &HittestPositionInDesktop, const UE::Slate::FDeprecateVector2DParameter &HittestDimensions, const UE::Slate::FDeprecateVector2DParameter &HitestOffsetInWindow=FVector2f::ZeroVector)
Set the position and size of the hittest area in desktop coordinates.
void SetOwner (const SWidget *InOwner)
Set the owner SWidget to be used by the parent grid (in case we are appended to another grid).
void SetUserIndex (int32 UserIndex)
Sets the current slate user index that should be associated with any added widgets.
void UpdateWidget (const SWidget *InWidget, FSlateInvalidationWidgetSortOrder InSecondarySort)
Update the widget SecondarySort without removing it and readding it again.
Private Types
using FCollapsedHittestGridArray = TArray<const FHittestGrid*, TInlineAllocator<16>>
using FCollapsedWidgetsArray = TArray<FWidgetIndex, TInlineAllocator<100>>
Private Member Functions
bool CanBeAppended (const FHittestGrid *OtherGrid) const
Is the other grid compatible with this grid.
FORCEINLINE_DEBUGGABLE FCell & CellAt (const int32 X, const int32 Y)
Access a cell at coordinates X, Y.
FORCEINLINE_DEBUGGABLE const FCell & CellAt (const int32 X, const int32 Y) const
Access a cell at coordinates X, Y.
void ClearInternal (int32 TotalCells)
template<typename TCompareFunc, typename TSourceSideFunc, typename TDestSideFunc>
TSharedPtr< SWidget > FindFocusableWidget (const FSlateRect WidgetRect, const FSlateRect SweptRect, int32 AxisIndex, int32 Increment, const EUINavigation Direction, const FNavigationReply &NavigationReply, TCompareFunc CompareFunc, TSourceSideFunc SourceSideFunc, TDestSideFunc DestSideFunc, int32 UserIndex, TArray< FDebuggingFindNextFocusableWidgetArgs::FWidgetResult > *IntermediatedResultPtr, TSet< TSharedPtr< SWidget > > *DisabledDestinations) const
Utility function for searching for the next focusable widget.
FIntPoint GetCellCoordinate (UE::Slate::FDeprecateVector2DParameter Position) const
Constrains a float position into the grid coordinate.
void GetCollapsedHittestGrid (FCollapsedHittestGridArray &OutResult) const
Get all the hittest grid appended to this grid.
void GetCollapsedWidgets (FCollapsedWidgetsArray &Out, const int32 X, const int32 Y) const
Return the list of all the widget in that cell.
FIndexAndDistance GetHitIndexFromCellIndex (const FGridTestingParams &Params) const
Return the Index and distance to a hit given the testing params.
bool IsDescendantOf (const SWidget *Parent, const FWidgetData &ChildData) const
bool IsValidCellCoord (const FIntPoint &CellCoord) const
bool IsValidCellCoord (const int32 XCoord, const int32 YCoord) const
void RemoveStaleAppendedHittestGrid ()
Remove appended hittest grid that are not valid anymore.
bool SameSize (const FHittestGrid *OtherGrid) const
Are both grid of the same size.
Private Attributes
TArray< FAppendedGridData > AppendedGridArray
The collapsed grid cached untiled it's dirtied.
TArray< FCell > Cells
The cells that make up the space partition.
FSlateRect CullingRect
Culling Rect used when the widget was painted.
int32 CurrentUserIndex
The current slate user index that should be associated with any added widgets.
FVector2f GridOrigin
Where the 0,0 of the upper-left-most cell corresponds to in desktop space.
FVector2f GridSize
The Size of the current grid.
FVector2f GridWindowOrigin
Where the 0,0 of the upper-left-most cell corresponds to in window space.
FIntPoint NumCells
The size of the grid in cells.
const SWidget * Owner
A grid needs a owner to be appended.
TSparseArray< FWidgetData > WidgetArray
Stable indexed sparse array of all the widget data we track.
TMap< const SWidget *, int32 > WidgetMap
Map of all the widgets currently in the hit test grid to their stable index.
Additional Inherited Members
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Detailed Description
Definition at line 27 of file HittestGrid.h.
Member Typedef Documentation
FCollapsedHittestGridArray
using FHittestGrid::FCollapsedHittestGridArray = TArray<const FHittestGrid*, TInlineAllocator<16>> private
Definition at line 277 of file HittestGrid.h.
FCollapsedWidgetsArray
using FHittestGrid::FCollapsedWidgetsArray = TArray<FWidgetIndex, TInlineAllocator<100>> private
Definition at line 281 of file HittestGrid.h.
Constructor & Destructor Documentation
FHittestGrid()
FHittestGrid::FHittestGrid ()
Referenced by FHittestGrid::FWidgetIndex::FWidgetIndex(), CanBeAppended(), FHittestGrid::FWidgetIndex::GetGrid(), and SameSize().
Member Function Documentation
AddGrid()
void FHittestGrid::AddGrid (const TSharedRef< const FHittestGrid > & OtherGrid)
Add an already existing grid that occupy the same space.
The grid needs to have an owner, not be this grid and occupy the same space as this grid.
AddWidget()
void FHittestGrid::AddWidget (const SWidget * InWidget, int32 InBatchPriorityGroup, int32 InLayerId, FSlateInvalidationWidgetSortOrder InSecondarySort)
Add SWidget from the HitTest Grid.
CanBeAppended()
bool FHittestGrid::CanBeAppended (const FHittestGrid * OtherGrid) const private
Is the other grid compatible with this grid.
References FHittestGrid().
CellAt() [1/2]
FORCEINLINE_DEBUGGABLE FCell & FHittestGrid::CellAt (const int32 X, const int32 Y) inline private
Access a cell at coordinates X, Y.
Coordinates are row and column indexes.
Definition at line 258 of file HittestGrid.h.
References Cells, checkfSlow, FORCEINLINE_DEBUGGABLE, NumCells, TEXT, X, and Y.
CellAt() [2/2]
FORCEINLINE_DEBUGGABLE const FCell & FHittestGrid::CellAt (const int32 X, const int32 Y) const inline private
Access a cell at coordinates X, Y.
Coordinates are row and column indexes.
Definition at line 265 of file HittestGrid.h.
References Cells, checkfSlow, FORCEINLINE_DEBUGGABLE, NumCells, TEXT, X, and Y.
Clear()
void FHittestGrid::Clear ()
Clear the grid.
ClearInternal()
void FHittestGrid::ClearInternal (int32 TotalCells) private
ContainsWidget()
bool FHittestGrid::ContainsWidget (const SWidget * InWidget) const
Check if SWidget is contained within the HitTest Grid.
FindFocusableWidget()
template<typename TCompareFunc, typename TSourceSideFunc, typename TDestSideFunc> TSharedPtr< SWidget > FHittestGrid::FindFocusableWidget (const FSlateRect WidgetRect, const FSlateRect SweptRect, int32 AxisIndex, int32 Increment, const EUINavigation Direction, const FNavigationReply & NavigationReply, TCompareFunc CompareFunc, TSourceSideFunc SourceSideFunc, TDestSideFunc DestSideFunc, int32 UserIndex, TArray< FDebuggingFindNextFocusableWidgetArgs::FWidgetResult > * IntermediatedResultPtr, TSet< TSharedPtr< SWidget > > * DisabledDestinations) const private
Utility function for searching for the next focusable widget.
FindNextFocusableWidget()
TSharedPtr< SWidget > FHittestGrid::FindNextFocusableWidget (const FArrangedWidget & StartingWidget, const EUINavigation Direction, const FNavigationReply & NavigationReply, const FArrangedWidget & RuleWidget, int32 UserIndex)
Finds the next focusable widget by searching through the hit test grid.
Parameters
StartingWidget This is the widget we are starting at, and navigating from.
Direction The direction we should search in.
NavigationReply The Navigation Reply to specify a boundary rule for the search.
RuleWidget The Widget that is applying the boundary rule, used to get the bounds of the Rule.
GetBubblePath()
TArray< FWidgetAndPointer > FHittestGrid::GetBubblePath (UE::Slate::FDeprecateVector2DParameter DesktopSpaceCoordinate, float CursorRadius, bool bIgnoreEnabledStatus, int32 UserIndex = INDEX_NONE)
Given a Slate Units coordinate in virtual desktop space, perform a hittest and return the path along which the corresponding event would be bubbled.
References INDEX_NONE.
GetCellCoordinate()
FIntPoint FHittestGrid::GetCellCoordinate (UE::Slate::FDeprecateVector2DParameter Position) const private
Constrains a float position into the grid coordinate.
References Position.
GetCollapsedHittestGrid()
void FHittestGrid::GetCollapsedHittestGrid (FCollapsedHittestGridArray & OutResult) const private
Get all the hittest grid appended to this grid.
GetCollapsedWidgets()
void FHittestGrid::GetCollapsedWidgets (FCollapsedWidgetsArray & Out, const int32 X, const int32 Y) const private
Return the list of all the widget in that cell.
References X, and Y.
GetGridOrigin()
UE::Slate::FDeprecateVector2DResult FHittestGrid::GetGridOrigin () const inline
Definition at line 75 of file HittestGrid.h.
References GridOrigin.
GetGridSize()
UE::Slate::FDeprecateVector2DResult FHittestGrid::GetGridSize () const inline
Definition at line 74 of file HittestGrid.h.
References GridSize.
GetGridWindowOrigin()
UE::Slate::FDeprecateVector2DResult FHittestGrid::GetGridWindowOrigin () const inline
Definition at line 76 of file HittestGrid.h.
References GridWindowOrigin.
GetHitIndexFromCellIndex()
FIndexAndDistance FHittestGrid::GetHitIndexFromCellIndex (const FGridTestingParams & Params) const private
Return the Index and distance to a hit given the testing params.
References Params.
GetUserIndex()
int32 FHittestGrid::GetUserIndex () const inline
Gets current slate user index that should be associated with any added widgets.
Definition at line 62 of file HittestGrid.h.
References CurrentUserIndex.
InsertCustomHitTestPath()
void FHittestGrid::InsertCustomHitTestPath (const SWidget * InWidget, const TSharedRef< ICustomHitTestPath > & CustomHitTestPath)
Insert custom hit test data for a widget already in the grid.
IsDescendantOf()
bool FHittestGrid::IsDescendantOf (const SWidget * Parent, const FWidgetData & ChildData) const private
Returns
true if the child is a paint descendant of the provided Parent.
References Parent.
IsValidCellCoord() [1/2]
bool FHittestGrid::IsValidCellCoord (const FIntPoint & CellCoord) const private
IsValidCellCoord() [2/2]
bool FHittestGrid::IsValidCellCoord (const int32 XCoord, const int32 YCoord) const private
RemoveGrid() [1/2]
void FHittestGrid::RemoveGrid (const SWidget * OtherGridOwner)
Remove a grid that was appended.
RemoveGrid() [2/2]
void FHittestGrid::RemoveGrid (const TSharedRef< const FHittestGrid > & OtherGrid)
Remove a grid that was appended.
RemoveStaleAppendedHittestGrid()
void FHittestGrid::RemoveStaleAppendedHittestGrid () private
Remove appended hittest grid that are not valid anymore.
RemoveWidget()
void FHittestGrid::RemoveWidget (const SWidget * InWidget)
Remove SWidget from the HitTest Grid.
SameSize()
bool FHittestGrid::SameSize (const FHittestGrid * OtherGrid) const private
Are both grid of the same size.
References FHittestGrid().
SetCullingRect()
void FHittestGrid::SetCullingRect (const FSlateRect & InCullingRect) inline
Set the culling rect to be used by the parent grid (in case we are appended to another grid).
Definition at line 56 of file HittestGrid.h.
References CullingRect.
SetHittestArea()
bool FHittestGrid::SetHittestArea (const UE::Slate::FDeprecateVector2DParameter & HittestPositionInDesktop, const UE::Slate::FDeprecateVector2DParameter & HittestDimensions, const UE::Slate::FDeprecateVector2DParameter & HitestOffsetInWindow = FVector2f::ZeroVector)
Set the position and size of the hittest area in desktop coordinates.
Parameters
HittestPositionInDesktop The position of this hit testing area in desktop coordinates.
HittestDimensions The dimensions of this hit testing area.
Returns
Returns true if a clear of the hittest grid was required.
References UE::Math::TVector2< float >::ZeroVector.
SetOwner()
void FHittestGrid::SetOwner (const SWidget * InOwner) inline
Set the owner SWidget to be used by the parent grid (in case we are appended to another grid).
Definition at line 59 of file HittestGrid.h.
References check, and Owner.
SetUserIndex()
void FHittestGrid::SetUserIndex (int32 UserIndex) inline
Sets the current slate user index that should be associated with any added widgets.
Definition at line 53 of file HittestGrid.h.
References CurrentUserIndex.
UpdateWidget()
void FHittestGrid::UpdateWidget (const SWidget * InWidget, FSlateInvalidationWidgetSortOrder InSecondarySort)
Update the widget SecondarySort without removing it and readding it again.
Field Documentation
AppendedGridArray
TArray<FAppendedGridData> FHittestGrid::AppendedGridArray private
The collapsed grid cached untiled it's dirtied.
Definition at line 299 of file HittestGrid.h.
Cells
TArray<FCell> FHittestGrid::Cells private
The cells that make up the space partition.
Definition at line 296 of file HittestGrid.h.
Referenced by CellAt(), and CellAt().
CullingRect
FSlateRect FHittestGrid::CullingRect private
Culling Rect used when the widget was painted.
Definition at line 305 of file HittestGrid.h.
Referenced by SetCullingRect().
CurrentUserIndex
int32 FHittestGrid::CurrentUserIndex private
The current slate user index that should be associated with any added widgets.
Definition at line 320 of file HittestGrid.h.
Referenced by GetUserIndex(), and SetUserIndex().
GridOrigin
FVector2f FHittestGrid::GridOrigin private
Where the 0,0 of the upper-left-most cell corresponds to in desktop space.
Definition at line 311 of file HittestGrid.h.
Referenced by GetGridOrigin().
GridSize
FVector2f FHittestGrid::GridSize private
The Size of the current grid.
Definition at line 317 of file HittestGrid.h.
Referenced by GetGridSize().
GridWindowOrigin
FVector2f FHittestGrid::GridWindowOrigin private
Where the 0,0 of the upper-left-most cell corresponds to in window space.
Definition at line 314 of file HittestGrid.h.
Referenced by GetGridWindowOrigin().
NumCells
FIntPoint FHittestGrid::NumCells private
The size of the grid in cells.
Definition at line 308 of file HittestGrid.h.
Referenced by CellAt(), and CellAt().
Owner
const SWidget* FHittestGrid::Owner private
A grid needs a owner to be appended.
Definition at line 302 of file HittestGrid.h.
Referenced by SetOwner().
WidgetArray
TSparseArray<FWidgetData> FHittestGrid::WidgetArray private
Stable indexed sparse array of all the widget data we track.
Definition at line 293 of file HittestGrid.h.
WidgetMap
TMap<const SWidget*, int32> FHittestGrid::WidgetMap private
Map of all the widgets currently in the hit test grid to their stable index.
Definition at line 290 of file HittestGrid.h.
The documentation for this class was generated from the following file:
HittestGrid.h