Unreal Engine 5.6 C++ API: FRK4SpringInterpolatorUtils Namespace Reference
FRK4SpringInterpolatorUtils Namespace Reference
Functions
static FORCEINLINE bool AreEqual (float A, float B, float ErrorTolerance=UE_KINDA_SMALL_NUMBER)
static FORCEINLINE bool AreEqual (FVector A, FVector B, float ErrorTolerance=UE_KINDA_SMALL_NUMBER)
static FORCEINLINE bool IsValidValue (float Value, float MaxAbsoluteValue=(1e+16f))
static FORCEINLINE bool IsValidValue (FVector Value, float MaxAbsoluteValue=(1e+16f))
Function Documentation
AreEqual() [1/2]
FORCEINLINE bool FRK4SpringInterpolatorUtils::AreEqual (float A, float B, float ErrorTolerance = UE_KINDA_SMALL_NUMBER) static
Definition at line 121 of file SpringInterpolator.h.
References A, B, FORCEINLINE, FMath::IsNearlyEqual(), and UE_KINDA_SMALL_NUMBER.
Referenced by FRK4SpringInterpolator< float >::IsPositionEqualTo(), and FRK4SpringInterpolator< float >::IsVelocityZero().
AreEqual() [2/2]
FORCEINLINE bool FRK4SpringInterpolatorUtils::AreEqual (FVector A, FVector B, float ErrorTolerance = UE_KINDA_SMALL_NUMBER) static
Definition at line 126 of file SpringInterpolator.h.
References A, B, FORCEINLINE, FVector, and UE_KINDA_SMALL_NUMBER.
IsValidValue() [1/2]
FORCEINLINE bool FRK4SpringInterpolatorUtils::IsValidValue (float Value, float MaxAbsoluteValue = (1e+16f)) static
Definition at line 111 of file SpringInterpolator.h.
References FORCEINLINE, RK4_SPRING_INTERPOLATOR_MAX_VALUE, and Value.
Referenced by FRK4SpringInterpolator< float >::Update().
IsValidValue() [2/2]
FORCEINLINE bool FRK4SpringInterpolatorUtils::IsValidValue (FVector Value, float MaxAbsoluteValue = (1e+16f)) static
Definition at line 116 of file SpringInterpolator.h.
References FORCEINLINE, FVector, RK4_SPRING_INTERPOLATOR_MAX_VALUE, and Value.