Unreal Engine 5.6 C++ API: FUObjectAnnotationDenseBool Class Reference
FUObjectAnnotationDenseBool Class Reference
FUObjectAnnotationDenseBool is custom annotation that tracks a bool per UObject.
#include "UObjectAnnotation.h"
Public Member Functions
virtual ~FUObjectAnnotationDenseBool ()
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
FORCEINLINE void Clear (const UObjectBase *Object)
Removes an annotation from the annotation list.
FORCEINLINE void ClearAll ()
Removes all bool annotations.
FORCEINLINE bool Get (const UObjectBase *Object)
Return the bool annotation associated with a uobject.
virtual SIZE_T GetAllocatedSize () const override
Returns the size of heap memory allocated internally by this listener.
virtual void NotifyUObjectDeleted (const UObjectBase *Object, int32 Index)
Interface for FUObjectAllocator::FUObjectDeleteListener.
virtual void OnUObjectArrayShutdown () override
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
FORCEINLINE void Set (const UObjectBase *Object)
Sets this bool annotation to true for this object.
Public Member Functions inherited from FUObjectArray::FUObjectDeleteListener
virtual ~FUObjectDeleteListener ()
virtual void NotifyUObjectDeleted (const class UObjectBase *Object, int32 Index)=0
Provides notification that a UObjectBase has been removed from the uobject array.
Private Types
enum { BitsPerElement = sizeof(TBitType) * 8 }
typedef uint32 TBitType
Private Member Functions
void RemoveAllAnnotations ()
Removes all annotation from the annotation list.
void RemoveAnnotation (int32 Index)
Removes an annotation from the annotation list.
Private Attributes
TArray< TBitType > AnnotationArray
Map from live objects to an annotation.
Detailed Description
FUObjectAnnotationDenseBool is custom annotation that tracks a bool per UObject.
Definition at line 1342 of file UObjectAnnotation.h.
Member Typedef Documentation
TBitType
typedef uint32 FUObjectAnnotationDenseBool::TBitType private
Definition at line 1344 of file UObjectAnnotation.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
BitsPerElement
Definition at line 1345 of file UObjectAnnotation.h.
Constructor & Destructor Documentation
~FUObjectAnnotationDenseBool()
virtual FUObjectAnnotationDenseBool::~FUObjectAnnotationDenseBool () inline virtual
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
Definition at line 1368 of file UObjectAnnotation.h.
References RemoveAllAnnotations().
Member Function Documentation
Clear()
FORCEINLINE void FUObjectAnnotationDenseBool::Clear (const UObjectBase * Object) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 1402 of file UObjectAnnotation.h.
References checkSlow, FORCEINLINE, GUObjectArray, Object, and RemoveAnnotation().
ClearAll()
FORCEINLINE void FUObjectAnnotationDenseBool::ClearAll () inline
Removes all bool annotations.
Definition at line 1413 of file UObjectAnnotation.h.
References FORCEINLINE, and RemoveAllAnnotations().
Get()
FORCEINLINE bool FUObjectAnnotationDenseBool::Get (const UObjectBase * Object) inline
Return the bool annotation associated with a uobject.
Parameters
Object Object to return the bool annotation for
Definition at line 1423 of file UObjectAnnotation.h.
References AnnotationArray, BitsPerElement, checkSlow, FORCEINLINE, GUObjectArray, and Object.
GetAllocatedSize()
virtual SIZE_T FUObjectAnnotationDenseBool::GetAllocatedSize () const inline override virtual
Returns the size of heap memory allocated internally by this listener.
Reimplemented from FUObjectArray::FUObjectDeleteListener.
Definition at line 1435 of file UObjectAnnotation.h.
References AnnotationArray.
NotifyUObjectDeleted()
virtual void FUObjectAnnotationDenseBool::NotifyUObjectDeleted (const UObjectBase * Object, int32 Index) inline virtual
Interface for FUObjectAllocator::FUObjectDeleteListener.
Parameters
Object object that has been destroyed
Index index of object that is being deleted
Definition at line 1354 of file UObjectAnnotation.h.
References Object, and RemoveAnnotation().
OnUObjectArrayShutdown()
virtual void FUObjectAnnotationDenseBool::OnUObjectArrayShutdown () inline override virtual
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
Implements FUObjectArray::FUObjectDeleteListener.
Definition at line 1359 of file UObjectAnnotation.h.
References GUObjectArray, and RemoveAllAnnotations().
RemoveAllAnnotations()
void FUObjectAnnotationDenseBool::RemoveAllAnnotations () inline private
Removes all annotation from the annotation list.
Definition at line 1458 of file UObjectAnnotation.h.
References AnnotationArray, and GUObjectArray.
Referenced by ~FUObjectAnnotationDenseBool(), ClearAll(), and OnUObjectArrayShutdown().
RemoveAnnotation()
void FUObjectAnnotationDenseBool::RemoveAnnotation (int32 Index) inline private
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 1446 of file UObjectAnnotation.h.
References AnnotationArray, BitsPerElement, and checkSlow.
Referenced by Clear(), and NotifyUObjectDeleted().
Set()
FORCEINLINE void FUObjectAnnotationDenseBool::Set (const UObjectBase * Object) inline
Sets this bool annotation to true for this object.
Parameters
Object Object to annotate.
Definition at line 1378 of file UObjectAnnotation.h.
References AnnotationArray, BitsPerElement, checkSlow, FORCEINLINE, GUObjectArray, and Object.
Field Documentation
AnnotationArray
TArray<TBitType> FUObjectAnnotationDenseBool::AnnotationArray private
Map from live objects to an annotation.
Definition at line 1471 of file UObjectAnnotation.h.
Referenced by Get(), GetAllocatedSize(), RemoveAllAnnotations(), RemoveAnnotation(), and Set().
The documentation for this class was generated from the following file:
UObjectAnnotation.h