Unreal Engine 5.6 C++ API: Nanite Namespace Reference
Nanite Namespace Reference
Namespaces
namespace Private
Data Structures
class FClusterFixup
class FCoarseMeshStreamingManager
class FFixupChunk
class FFixupChunkBuffer
class FHierarchyFixup
struct FInstanceDraw
struct FMaterialAudit
struct FMaterialAuditEntry
struct FMeshDataSection
class FMeshDataSectionArray
class FNaniteResourcesHelper
Helper class used to share implementation for different Component types.
struct FPackedCluster
struct FPackedHierarchyNode
struct FPageKey
struct FPageStreamingState
struct FResourceMeshInfo
struct FResources
class FSceneProxy
class FSceneProxyBase
class FSkinnedSceneProxy
class FStreamingManager
struct FStreamingRequest
class FVertexFactoryResource
Typedefs
using CoarseMeshStreamingHandle = int16
Enumerations
enum class EFilterFlags : uint8 {
None = 0u , StaticMesh = (1u << 0u) , InstancedStaticMesh = (1u << 1u) , Foliage = (1u << 2u) ,
Grass = (1u << 3u) , Landscape = (1u << 4u) , StaticMobility = (1u << 5u) , NonStaticMobility = (1u << 6u) ,
SkeletalMesh = (1u << 7u) , All = 0xFF
}
enum class EMeshDataSectionFlags : uint32 {
None = 0x0 , EnableCollision = 1 << 1 , CastShadow = 1 << 2 , VisibleInRayTracing = 1 << 3 ,
AffectDistanceFieldLighting = 1 << 4 , ForceOpaque = 1 << 5 , Selected = 1 << 6 , RecomputeTangents = 1 << 7 ,
Use16BitBoneIndices = 1 << 8 , Disabled = 1 << 9
}
enum EProxyRenderMode { Allow , AllowForDebugging , Disallow }
enum class ERayTracingMode : uint8 { Fallback = 0u , StreamOut = 1u }
Functions
void AuditMaterials (const FSkinnedMeshSceneProxyDesc *ProxyDesc, FMaterialAudit &Audit, bool bSetMaterialUsage=true)
void AuditMaterials (const FStaticMeshSceneProxyDesc *ProxyDesc, FMaterialAudit &Audit, bool bSetMaterialUsage=true)
void AuditMaterials (const USkinnedMeshComponent *Component, FMaterialAudit &Audit, bool bSetMaterialUsage=true)
void AuditMaterials (const UStaticMeshComponent *Component, FMaterialAudit &Audit, bool bSetMaterialUsage=true)
FMeshDataSectionArray BuildMeshSections (const FStaticMeshSectionArray &InSections)
FMeshDataSectionArray BuildMeshSections (const TConstArrayView< const FSkelMeshSection > InSections)
FSkelMeshSectionArray BuildSkeletalMeshSections (const FMeshDataSectionArray &InSections)
FStaticMeshSectionArray BuildStaticMeshSections (const FMeshDataSectionArray &InSections)
ENUM_CLASS_FLAGS (EMeshDataSectionFlags) struct FMeshSkinningData
FORCEINLINE uint32 GetBits (uint32 Value, uint32 NumBits, uint32 Offset)
EProxyRenderMode GetProxyRenderMode ()
ERayTracingMode GetRayTracingMode ()
bool GetSupportsCustomDepthRendering ()
bool IsMaskingAllowed (UWorld *World, bool bForceNaniteForMasked)
bool IsSupportedBlendMode (const FMaterial &In)
bool IsSupportedBlendMode (const FMaterialShaderParameters &In)
bool IsSupportedBlendMode (const UMaterialInterface &In)
bool IsSupportedBlendMode (EBlendMode Mode)
bool IsSupportedMaterialDomain (EMaterialDomain Domain)
bool IsSupportedShadingModel (FMaterialShadingModelField ShadingModelField)
constexpr bool operator! (EFilterFlags E)
constexpr EFilterFlags operator& (EFilterFlags Lhs, EFilterFlags Rhs)
EFilterFlags & operator&= (EFilterFlags &Lhs, EFilterFlags Rhs)
constexpr EFilterFlags operator^ (EFilterFlags Lhs, EFilterFlags Rhs)
EFilterFlags & operator^= (EFilterFlags &Lhs, EFilterFlags Rhs)
constexpr EFilterFlags operator| (EFilterFlags Lhs, EFilterFlags Rhs)
EFilterFlags & operator|= (EFilterFlags &Lhs, EFilterFlags Rhs)
constexpr EFilterFlags operator~ (EFilterFlags E)
FORCEINLINE void SetBits (uint32 &Value, uint32 Bits, uint32 NumBits, uint32 Offset)
Variables
int32 GEnableNaniteMaterialOverrides
TGlobalResource< FStreamingManager > GStreamingManager
TGlobalResource< FVertexFactoryResource > GVertexFactoryResource
Typedef Documentation
CoarseMeshStreamingHandle
using Nanite::CoarseMeshStreamingHandle = int16
Definition at line 54 of file PrimitiveSceneProxy.h.
Enumeration Type Documentation
EFilterFlags
enum class Nanite::EFilterFlags : uint8 strong
Enumerator
None
StaticMesh
InstancedStaticMesh
Foliage
Grass
Landscape
StaticMobility
NonStaticMobility
SkeletalMesh
All
Definition at line 178 of file NaniteSceneProxy.h.
EMeshDataSectionFlags
enum class Nanite::EMeshDataSectionFlags : uint32 strong
Enumerator
None
EnableCollision
CastShadow
VisibleInRayTracing
AffectDistanceFieldLighting
ForceOpaque
Selected
RecomputeTangents
Use16BitBoneIndices
Disabled
Definition at line 341 of file NaniteResources.h.
EProxyRenderMode
enum Nanite::EProxyRenderMode
Enumerator
Allow
Fall back to rendering Nanite proxy meshes if Nanite is unsupported. (default)
AllowForDebugging
Disable rendering if Nanite is enabled on a mesh but is unsupported, except for debug purpose.
Disallow
Disable rendering if Nanite is enabled on a mesh but is unsupported.
Definition at line 152 of file NaniteSceneProxy.h.
ERayTracingMode
enum class Nanite::ERayTracingMode : uint8 strong
Enumerator
Fallback
StreamOut
Definition at line 17 of file NaniteInterface.h.
Function Documentation
AuditMaterials() [1/4]
void Nanite::AuditMaterials (const FSkinnedMeshSceneProxyDesc * ProxyDesc, FMaterialAudit & Audit, bool bSetMaterialUsage = true)
AuditMaterials() [2/4]
void Nanite::AuditMaterials (const FStaticMeshSceneProxyDesc * ProxyDesc, FMaterialAudit & Audit, bool bSetMaterialUsage = true)
AuditMaterials() [3/4]
void Nanite::AuditMaterials (const USkinnedMeshComponent * Component, FMaterialAudit & Audit, bool bSetMaterialUsage = true)
References Component.
AuditMaterials() [4/4]
void Nanite::AuditMaterials (const UStaticMeshComponent * Component, FMaterialAudit & Audit, bool bSetMaterialUsage = true)
References Component.
BuildMeshSections() [1/2]
FMeshDataSectionArray Nanite::BuildMeshSections (const FStaticMeshSectionArray & InSections)
BuildMeshSections() [2/2]
FMeshDataSectionArray Nanite::BuildMeshSections (const TConstArrayView< const FSkelMeshSection > InSections)
BuildSkeletalMeshSections()
FSkelMeshSectionArray Nanite::BuildSkeletalMeshSections (const FMeshDataSectionArray & InSections)
BuildStaticMeshSections()
FStaticMeshSectionArray Nanite::BuildStaticMeshSections (const FMeshDataSectionArray & InSections)
ENUM_CLASS_FLAGS()
Nanite::ENUM_CLASS_FLAGS (EMeshDataSectionFlags)
Vertex color channel to mask recompute tangents. R=0,G=1,B=2,A=None=3
Map between a vertex index and all vertices that share the same position
The cloth deformer mapping data to each required cloth LOD. Raytracing may require a different deformer LOD to the one being simulated/rendered. The outer array indexes the LOD bias to this LOD. The inner array indexes the vertex mapping data. For example, if this LODModel is LOD3, then ClothMappingDataLODs[1] will point to defomer data that are using cloth LOD2. Then ClothMappingDataLODs[2] will point to defomer data that are using cloth LOD1, ...etc. ClothMappingDataLODs[0] will always point to defomer data that are using the same cloth LOD as this section LOD, this is convenient for cases where the cloth LOD bias is not known/required.
Clothing data for this section, clothing is only present if ClothingData.IsValid() returns true
Definition at line 372 of file NaniteResources.h.
GetBits()
FORCEINLINE uint32 Nanite::GetBits (uint32 Value, uint32 NumBits, uint32 Offset)
Definition at line 78 of file NaniteResources.h.
References FORCEINLINE, Mask, and Value.
Referenced by Nanite::FPackedCluster::GetAttributeOffset(), Nanite::FPackedCluster::GetBitsPerAttribute(), Nanite::FPackedCluster::GetBitsPerIndex(), Nanite::FPackedCluster::GetFlags(), Nanite::FPackedCluster::GetIndexOffset(), Nanite::FPackedCluster::GetNormalPrecision(), Nanite::FPackedCluster::GetNumClusterBoneInfluences(), Nanite::FPackedCluster::GetNumTris(), Nanite::FPackedCluster::GetNumVerts(), Nanite::FPackedCluster::GetPosBitsX(), Nanite::FPackedCluster::GetPosBitsY(), Nanite::FPackedCluster::GetPosBitsZ(), Nanite::FPackedCluster::GetPositionOffset(), Nanite::FPackedCluster::GetPosPrecision(), and Nanite::FPackedCluster::GetTangentPrecision().
GetProxyRenderMode()
EProxyRenderMode Nanite::GetProxyRenderMode ()
Referenced by FStaticMeshComponentHelper::CreateSceneProxy().
GetRayTracingMode()
ERayTracingMode Nanite::GetRayTracingMode ()
GetSupportsCustomDepthRendering()
bool Nanite::GetSupportsCustomDepthRendering ()
IsMaskingAllowed()
bool Nanite::IsMaskingAllowed (UWorld * World, bool bForceNaniteForMasked)
Referenced by FStaticMeshComponentHelper::CreateSceneProxy(), and Nanite::FNaniteResourcesHelper::ShouldCreateNaniteProxy().
IsSupportedBlendMode() [1/4]
bool Nanite::IsSupportedBlendMode (const FMaterial & In)
IsSupportedBlendMode() [2/4]
bool Nanite::IsSupportedBlendMode (const FMaterialShaderParameters & In)
IsSupportedBlendMode() [3/4]
bool Nanite::IsSupportedBlendMode (const UMaterialInterface & In)
IsSupportedBlendMode() [4/4]
bool Nanite::IsSupportedBlendMode (EBlendMode Mode)
Referenced by Nanite::FNaniteResourcesHelper::AuditMaterials().
IsSupportedMaterialDomain()
bool Nanite::IsSupportedMaterialDomain (EMaterialDomain Domain)
IsSupportedShadingModel()
bool Nanite::IsSupportedShadingModel (FMaterialShadingModelField ShadingModelField)
Referenced by Nanite::FNaniteResourcesHelper::AuditMaterials().
operator!()
bool Nanite::operator! (EFilterFlags E) inline constexpr
Definition at line 192 of file NaniteSceneProxy.h.
operator&()
EFilterFlags Nanite::operator& (EFilterFlags Lhs, EFilterFlags Rhs) inline constexpr
Definition at line 192 of file NaniteSceneProxy.h.
operator&=()
EFilterFlags & Nanite::operator&= (EFilterFlags & Lhs, EFilterFlags Rhs) inline
Definition at line 192 of file NaniteSceneProxy.h.
operator^()
EFilterFlags Nanite::operator^ (EFilterFlags Lhs, EFilterFlags Rhs) inline constexpr
Definition at line 192 of file NaniteSceneProxy.h.
operator^=()
EFilterFlags & Nanite::operator^= (EFilterFlags & Lhs, EFilterFlags Rhs) inline
Definition at line 192 of file NaniteSceneProxy.h.
operator|()
EFilterFlags Nanite::operator| (EFilterFlags Lhs, EFilterFlags Rhs) inline constexpr
Definition at line 192 of file NaniteSceneProxy.h.
operator|=()
EFilterFlags & Nanite::operator|= (EFilterFlags & Lhs, EFilterFlags Rhs) inline
Definition at line 192 of file NaniteSceneProxy.h.
operator~()
EFilterFlags Nanite::operator~ (EFilterFlags E) inline constexpr
Definition at line 192 of file NaniteSceneProxy.h.
SetBits()
FORCEINLINE void Nanite::SetBits (uint32 & Value, uint32 Bits, uint32 NumBits, uint32 Offset)
Definition at line 84 of file NaniteResources.h.
References check, FORCEINLINE, Mask, and Value.
Referenced by Nanite::FPackedCluster::SetAttributeOffset(), Nanite::FPackedCluster::SetBitsPerAttribute(), Nanite::FPackedCluster::SetBitsPerIndex(), Nanite::FPackedCluster::SetBrickDataNum(), Nanite::FPackedCluster::SetBrickDataOffset(), Nanite::FPackedCluster::SetColorBitsA(), Nanite::FPackedCluster::SetColorBitsB(), Nanite::FPackedCluster::SetColorBitsG(), Nanite::FPackedCluster::SetColorBitsR(), Nanite::FPackedCluster::SetColorMode(), Nanite::FPackedCluster::SetDecodeInfoOffset(), Nanite::FPackedCluster::SetExtendedDataNum(), Nanite::FPackedCluster::SetExtendedDataOffset(), Nanite::FPackedCluster::SetFlags(), Nanite::FPackedCluster::SetGroupIndex(), Nanite::FPackedCluster::SetHasSkinning(), Nanite::FPackedCluster::SetHasTangents(), Nanite::FPackedCluster::SetIndexOffset(), Nanite::FPackedCluster::SetNormalPrecision(), Nanite::FPackedCluster::SetNumClusterBoneInfluences(), Nanite::FPackedCluster::SetNumTris(), Nanite::FPackedCluster::SetNumUVs(), Nanite::FPackedCluster::SetNumVerts(), Nanite::FPackedCluster::SetPosBitsX(), Nanite::FPackedCluster::SetPosBitsY(), Nanite::FPackedCluster::SetPosBitsZ(), Nanite::FPackedCluster::SetPositionOffset(), Nanite::FPackedCluster::SetPosPrecision(), and Nanite::FPackedCluster::SetTangentPrecision().
Variable Documentation
GEnableNaniteMaterialOverrides
int32 Nanite::GEnableNaniteMaterialOverrides extern
Referenced by Nanite::FNaniteResourcesHelper::UseNaniteOverrideMaterials().
GStreamingManager
TGlobalResource< FStreamingManager > Nanite::GStreamingManager extern
GVertexFactoryResource
TGlobalResource<FVertexFactoryResource> Nanite::GVertexFactoryResource extern