Unreal Engine 5.6 C++ API: TUniqueFunction< Ret(ParamTypes...)> Class Template Reference
TUniqueFunction< Ret(ParamTypes...)> Class Template Reference final
TUniqueFunction<FuncType>
#include "Function.h"
Public Member Functions
TUniqueFunction (const TFunction< Ret(ParamTypes...)> &Other)
Constructor which takes ownership of a TFunction's functor.
TUniqueFunction (const TUniqueFunction &Other)=delete
template<typename FunctorType UE_REQUIRES>
TUniqueFunction (FunctorType &&InFunc)
Constructor which binds a TFunction to any function object.
TUniqueFunction (TFunction< Ret(ParamTypes...)> &&Other)
Constructor which takes ownership of a TFunction's functor.
TUniqueFunction (TUniqueFunction &&)=default
TUniqueFunction (TYPE_OF_NULLPTR=nullptr)
Default constructor.
~TUniqueFunction ()=default
FORCEINLINE bool IsSet () const
Tests if the TUniqueFunction is callable.
FORCEINLINE operator bool () const
Tests if the TUniqueFunction is callable.
TUniqueFunction & operator= (const TUniqueFunction &Other)=delete
TUniqueFunction & operator= (TUniqueFunction &&Other)
Copy/move assignment operator.
void Reset ()
Removes any bound callable from the TFunction, restoring it to the default 'empty' state.
Private Types
using Super = UE::Core::Private::Function::TFunctionRefBase<UE::Core::Private::Function::TFunctionStorage<true>, Ret(ParamTypes...)>
Detailed Description
template<typename Ret, typename... ParamTypes>
class TUniqueFunction< Ret(ParamTypes...)>
TUniqueFunction<FuncType>
Used like TFunction above, but is move-only. This allows non-copyable functors to be bound to it.
Example:
TUniquePtr<FThing> Thing = MakeUnique<FThing>();
TFunction <void()> CopyableFunc = [Thing = MoveTemp(Thing)](){ Thing->DoSomething(); }; // error - lambda is not copyable TUniqueFunction<void()> MovableFunc = [Thing = MoveTemp(Thing)](){ Thing->DoSomething(); }; // ok
void Foo(TUniqueFunction<void()> Func); Foo(MovableFunc); // error - TUniqueFunction is not copyable Foo(MoveTemp(MovableFunc)); // ok
Definition at line 827 of file Function.h.
Member Typedef Documentation
Super
template<typename Ret, typename... ParamTypes> using TUniqueFunction< Ret(ParamTypes...)>::Super = UE::Core::Private::Function::TFunctionRefBase<UE::Core::Private::Function::TFunctionStorage<true>, Ret(ParamTypes...)> private
Definition at line 829 of file Function.h.
Constructor & Destructor Documentation
TUniqueFunction() [1/6]
template<typename Ret, typename... ParamTypes> TUniqueFunction< Ret(ParamTypes...)>::TUniqueFunction (TYPE_OF_NULLPTR = nullptr) inline
Default constructor.
Definition at line 835 of file Function.h.
Referenced by TUniqueFunction(), TUniqueFunction(), operator=(), and operator=().
TUniqueFunction() [2/6]
template<typename Ret, typename... ParamTypes> template<typename FunctorType UE_REQUIRES> TUniqueFunction< Ret(ParamTypes...)>::TUniqueFunction (FunctorType && InFunc) inline
Constructor which binds a TFunction to any function object.
Definition at line 850 of file Function.h.
References Core, Function, Private, and Value.
TUniqueFunction() [3/6]
template<typename Ret, typename... ParamTypes> TUniqueFunction< Ret(ParamTypes...)>::TUniqueFunction (TFunction< Ret(ParamTypes...)> && Other) inline
Constructor which takes ownership of a TFunction's functor.
Definition at line 869 of file Function.h.
References Core, Function, MoveTemp(), Other, and Private.
TUniqueFunction() [4/6]
template<typename Ret, typename... ParamTypes> TUniqueFunction< Ret(ParamTypes...)>::TUniqueFunction (const TFunction< Ret(ParamTypes...)> & Other) inline
Constructor which takes ownership of a TFunction's functor.
Definition at line 877 of file Function.h.
References Core, Function, Other, and Private.
TUniqueFunction() [5/6]
template<typename Ret, typename... ParamTypes> TUniqueFunction< Ret(ParamTypes...)>::TUniqueFunction (TUniqueFunction< Ret(ParamTypes...)> &&) default
References TUniqueFunction().
TUniqueFunction() [6/6]
template<typename Ret, typename... ParamTypes> TUniqueFunction< Ret(ParamTypes...)>::TUniqueFunction (const TUniqueFunction< Ret(ParamTypes...)> & Other) delete
References TUniqueFunction(), and Other.
~TUniqueFunction()
template<typename Ret, typename... ParamTypes> TUniqueFunction< Ret(ParamTypes...)>::~TUniqueFunction () default
Member Function Documentation
IsSet()
template<typename Ret, typename... ParamTypes> FORCEINLINE bool TUniqueFunction< Ret(ParamTypes...)>::IsSet () const inline
Tests if the TUniqueFunction is callable.
Definition at line 915 of file Function.h.
References FORCEINLINE.
operator bool()
template<typename Ret, typename... ParamTypes> FORCEINLINE TUniqueFunction< Ret(ParamTypes...)>::operator bool () const inline explicit
Tests if the TUniqueFunction is callable.
Definition at line 907 of file Function.h.
References FORCEINLINE.
operator=() [1/2]
template<typename Ret, typename... ParamTypes> TUniqueFunction & TUniqueFunction< Ret(ParamTypes...)>::operator= (const TUniqueFunction< Ret(ParamTypes...)> & Other) delete
References TUniqueFunction(), and Other.
operator=() [2/2]
template<typename Ret, typename... ParamTypes> TUniqueFunction & TUniqueFunction< Ret(ParamTypes...)>::operator= (TUniqueFunction< Ret(ParamTypes...)> && Other) inline
Copy/move assignment operator.
Definition at line 885 of file Function.h.
References TUniqueFunction(), Other, and Swap.
Reset()
template<typename Ret, typename... ParamTypes> void TUniqueFunction< Ret(ParamTypes...)>::Reset () inline
Removes any bound callable from the TFunction, restoring it to the default 'empty' state.
Definition at line 899 of file Function.h.
The documentation for this class was generated from the following file:
Function.h