Unreal Engine 5.6 C++ Documentation: FRootMotionSource Struct Reference
FRootMotionSource Struct Reference
Generalized source of Root Motion to a CharacterMovementComponent.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h>
Public Member Functions
FRootMotionSource ()
virtual ~FRootMotionSource ()
float GetTime () const
float GetStartTime () const
bool IsStartTimeValid () const
float GetDuration () const
virtual bool IsTimeOutEnabled () const
virtual FRootMotionSource * Clone () const
virtual bool Matches (const FRootMotionSource *Other) const
virtual bool MatchesAndHasSameState (const FRootMotionSource *Other) const
Checks that it Matches() and has the same state (time, track position, etc.)
virtual bool UpdateStateFrom (const FRootMotionSource *SourceToTakeStateFrom, bool bMarkForSimulatedCatchup=false)
Mainly for server correction purposes - update this Source's state from another's, usually the authoritative state from the server's version of the Source.
virtual bool IsActive () const
True when this RootMotionSource should be affecting root motion.
virtual void SetTime (float NewTime)
Set the CurrentTime of this source.
virtual void CheckTimeOut ()
Checks if this source has timed out and marks for removal if necessary.
virtual void PrepareRootMotion (float SimulationTime, float MovementTickTime, const ACharacter &Character, const UCharacterMovementComponent &MoveComponent)
Generates the RootMotion for this Source, can be used for both "live" generation or for playback (client prediction correction, simulated proxies, etc.)
virtual bool NetSerialize (FArchive &Ar, UPackageMap *Map, bool &bOutSuccess)
virtual UScriptStruct * GetScriptStruct () const
virtual FString ToSimpleString () const
virtual void AddReferencedObjects (class FReferenceCollector &Collector)
Public Attributes
uint16 Priority
Priority of this source relative to other sources - higher number being the highest priority/first applied.
uint16 LocalID
ID local to this client or server instance.
FName InstanceName
This name allows us to find the source later so that we can end it.
float StartTime
Time this source should start (in character movement client time) This is used to handle cases of inconsistent tick times (ServerMoves ticking for 1 second when root motion should have only applied for the last 0.1 seconds, or root motion source ending halfway through a 0.5 second tick)
float CurrentTime
Time elapsed so far for this source.
float PreviousTime
The last Time entry we had before the last SetTime() - used for simulated catchup.
float Duration
The length of this root motion - < 0 for infinite (to be removed manually)
FRootMotionSourceStatus Status
Status of this source.
FRootMotionSourceSettings Settings
Settings of this source.
ERootMotionAccumulateMode AccumulateMode
Accumulation mode for this source (whether or not to additively apply this root motion or override completely)
bool bInLocalSpace
True when this RootMotionSource is contributing local space accumulation (false for world space)
bool bNeedsSimulatedCatchup
True when this RootMotionSource has been marked for simulated catchup - this Simulated version of the Source needs to catch up to where it was before being corrected by authoritative version.
bool bSimulatedNeedsSmoothing
True when this RootMotionSource is running on a SimulatedProxy and has marked itself as needing location/rotation smoothing.
FRootMotionMovementParams RootMotionParams
Root Motion generated by this Source.
FRootMotionFinishVelocitySettings FinishVelocityParams
Finish Velocity Parameters.
Detailed Description
Generalized source of Root Motion to a CharacterMovementComponent.
Has priorities and different accumulation modes (override, additive, set, ignore).
RootMotionSources are accumulated from highest priority to lowest, once all values are "finalized" (meaning no more accumulation to those values), root motion accumulation is finished. Having all of translation and rotation in a transform being overridden during root motion accumulation means that CharacterMovementComponent Phys*() functions no longer need to CalcVelocity() since it'll just get overridden anyway.
Some example source possibilities: Full Animation Root Motion (matching only form of root motion we've supported historically):
Overrides all translation axes or rotation or both
Very High priority so it gets applied first and since it is override no other RootMotionSources have an influence that are lower priority
Scale on translation and/or rotation is set to 1 to match animation 1 for 1
Provides local space transform (character-orientation relative)
End result: Same as before - overrides velocity/rotation to values in AnimMontage
But can now scale individual translation axes if desired, or instead of override can use "set" to allow other additive sources of root motion to be applied on top of the animation root motion (modify velocity to home root motion melee attacks, etc.)
Jump pad volumes that work during animation root montage attacks
Constant velocity modification Z up, additive and high priority
Attack/melee animation root motion uses "set" instead of "override" to allow other sources
Animation root motion is applied, then the Z up additive of this source is so you are affected by the jump pad
Attack/melee homing
Additive, lower priority so it gets applied after any animation/significant root motion
World space, sourced by logic modifying velocity to go towards nearby enemies
Could point to a UAbilityTask node from the GameplayAbilities system
Character movement controlled by splines/curves in-editor instead of requiring animation tweaks
Same as animation root motion but source from spline/curve data
Definition at line 222 of file RootMotionSource.h.
Constructor & Destructor Documentation
FRootMotionSource()
FRootMotionSource::FRootMotionSource ()
References FRootMotionSource().
~FRootMotionSource()
virtual FRootMotionSource::~FRootMotionSource () inline virtual
Definition at line 308 of file RootMotionSource.h.
References FRootMotionSource().
Member Function Documentation
AddReferencedObjects()
virtual void FRootMotionSource::AddReferencedObjects (class FReferenceCollector & Collector) inline virtual
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
Definition at line 404 of file RootMotionSource.h.
CheckTimeOut()
virtual void FRootMotionSource::CheckTimeOut () virtual
Checks if this source has timed out and marks for removal if necessary.
Clone()
virtual FRootMotionSource * FRootMotionSource::Clone () const virtual
Returns
newly allocated copy of this FRootMotionSource. Must be overridden by child classes.
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
References FRootMotionSource().
GetDuration()
float FRootMotionSource::GetDuration () const
Returns
the Duration - the length of this root motion - < 0 for infinite (to be removed manually)
GetScriptStruct()
virtual UScriptStruct * FRootMotionSource::GetScriptStruct () const virtual
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
GetStartTime()
float FRootMotionSource::GetStartTime () const
Returns
the StartTime - time this source should start (in character movement client time)
GetTime()
float FRootMotionSource::GetTime () const
Returns
the CurrentTime - amount of time elapsed so far for this source
IsActive()
virtual bool FRootMotionSource::IsActive () const virtual
True when this RootMotionSource should be affecting root motion.
IsStartTimeValid()
bool FRootMotionSource::IsStartTimeValid () const
Returns
whether the start time has been set
IsTimeOutEnabled()
virtual bool FRootMotionSource::IsTimeOutEnabled () const virtual
Returns
whether this source will be removed when CurrentTime reaches Duration
Reimplemented in FRootMotionSource_JumpForce.
Matches()
virtual bool FRootMotionSource::Matches (const FRootMotionSource * Other) const virtual
Returns
Whether this is the same RootMotionSource as Other. This is used for networking when clients receive RootMotionSource data from the server and need to decide which local RootMotionSource to compare and apply the corrections to. This is required due to RootMotionSources in general being added independently on server and clients, not needing to know about each other by default.
For well-networked RootMotionSources, any given FRootMotionSource child class could implement their own unique ID and simply use that in the Matches check. This "heuristic-style" default was chosen to simplify addition of new RootMotionSources, and assumes that in a networked setting a given RootMotionSource won't be applied many times in a given frame by the same instigator to the same target with the exact same parameters.
Guaranteed uniqueness would also require a strict application order ("RootMotionSources can only be added on Authority") or a prediction-based setup ("Apply on Autonomous and Simulated predictively, then apply on Authority and confirm, and if Authority doesn't confirm remove them"). We avoid that synchronization complexity for now.
See UCharacterMovementComponent::ConvertRootMotionServerIDsToLocalIDs
Should be overridden by child classes, as default implementation only contains basic equivalency checks
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
References FRootMotionSource().
MatchesAndHasSameState()
virtual bool FRootMotionSource::MatchesAndHasSameState (const FRootMotionSource * Other) const virtual
Checks that it Matches() and has the same state (time, track position, etc.)
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
References FRootMotionSource().
NetSerialize()
virtual bool FRootMotionSource::NetSerialize (FArchive & Ar, UPackageMap * Map, bool & bOutSuccess) virtual
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
PrepareRootMotion()
virtual void FRootMotionSource::PrepareRootMotion (float SimulationTime, float MovementTickTime, const ACharacter & Character, const UCharacterMovementComponent & MoveComponent) virtual
Generates the RootMotion for this Source, can be used for both "live" generation or for playback (client prediction correction, simulated proxies, etc.)
Examples:
Animation RootMotionSources use Time as track time into AnimMontage and extract the root motion from AnimMontage chunk of time (Position,Position+DeltaTime)
ConstantForce source uses Time as the time into the application so if its duration ends halfway through the frame it knows how much root motion it should have applied
Spline/curve-based sources use Time for knowing where on spline/curve to extract from
Parameters
SimulationTime How far forward in time to simulate root motion
MovementTickTime How much time the movement is going to take that this is being prepared for
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
SetTime()
virtual void FRootMotionSource::SetTime (float NewTime) virtual
Set the CurrentTime of this source.
Use this setter so that sources based on duration can get correctly marked for end
Reimplemented in FRootMotionSource_MoveToDynamicForce, and FRootMotionSource_MoveToForce.
ToSimpleString()
virtual FString FRootMotionSource::ToSimpleString () const virtual
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
UpdateStateFrom()
virtual bool FRootMotionSource::UpdateStateFrom (const FRootMotionSource * SourceToTakeStateFrom, bool bMarkForSimulatedCatchup = false) virtual
Mainly for server correction purposes - update this Source's state from another's, usually the authoritative state from the server's version of the Source.
Parameters
bMarkForSimulatedCatchup sets the source for needing to "catch up" to current state next Prepare
Returns
Whether the update was sucessful or not. Note that failure to update denotes a complete failure, and the Source will then be marked for removal. We need to remove since we don't have a way of reverting partial updates depending on where the update failed.
Reimplemented in FRootMotionSource_ConstantForce, FRootMotionSource_JumpForce, FRootMotionSource_MoveToDynamicForce, FRootMotionSource_MoveToForce, and FRootMotionSource_RadialForce.
References FRootMotionSource().
Member Data Documentation
AccumulateMode
ERootMotionAccumulateMode FRootMotionSource::AccumulateMode
Accumulation mode for this source (whether or not to additively apply this root motion or override completely)
Definition at line 277 of file RootMotionSource.h.
bInLocalSpace
bool FRootMotionSource::bInLocalSpace
True when this RootMotionSource is contributing local space accumulation (false for world space)
Definition at line 281 of file RootMotionSource.h.
bNeedsSimulatedCatchup
bool FRootMotionSource::bNeedsSimulatedCatchup
True when this RootMotionSource has been marked for simulated catchup - this Simulated version of the Source needs to catch up to where it was before being corrected by authoritative version.
Definition at line 287 of file RootMotionSource.h.
bSimulatedNeedsSmoothing
bool FRootMotionSource::bSimulatedNeedsSmoothing
True when this RootMotionSource is running on a SimulatedProxy and has marked itself as needing location/rotation smoothing.
This smoothing logic is what runs whenever the SimulatedProxy receives a replication update from the server (SimulatedTick in CharacterMovementComponent, see bCorrectedToServer and SmoothCorrection), this flag allows the RootMotionSource to signal to the CMC that a change was done significant enough that needs smoothing.
Definition at line 296 of file RootMotionSource.h.
CurrentTime
float FRootMotionSource::CurrentTime
Time elapsed so far for this source.
Definition at line 255 of file RootMotionSource.h.
Duration
float FRootMotionSource::Duration
The length of this root motion - < 0 for infinite (to be removed manually)
Definition at line 263 of file RootMotionSource.h.
FinishVelocityParams
FRootMotionFinishVelocitySettings FRootMotionSource::FinishVelocityParams
Finish Velocity Parameters.
Definition at line 304 of file RootMotionSource.h.
InstanceName
FName FRootMotionSource::InstanceName
This name allows us to find the source later so that we can end it.
Definition at line 243 of file RootMotionSource.h.
LocalID
uint16 FRootMotionSource::LocalID
ID local to this client or server instance.
Used for matching up FRootMotionSources between SavedMoves and allow a mapping between server LocalIDs and client LocalIDs for correction/comparison
Definition at line 237 of file RootMotionSource.h.
PreviousTime
float FRootMotionSource::PreviousTime
The last Time entry we had before the last SetTime() - used for simulated catchup.
Definition at line 259 of file RootMotionSource.h.
Priority
uint16 FRootMotionSource::Priority
Priority of this source relative to other sources - higher number being the highest priority/first applied.
Definition at line 232 of file RootMotionSource.h.
RootMotionParams
FRootMotionMovementParams FRootMotionSource::RootMotionParams
Root Motion generated by this Source.
Definition at line 300 of file RootMotionSource.h.
Settings
FRootMotionSourceSettings FRootMotionSource::Settings
Settings of this source.
Definition at line 271 of file RootMotionSource.h.
StartTime
float FRootMotionSource::StartTime
Time this source should start (in character movement client time) This is used to handle cases of inconsistent tick times (ServerMoves ticking for 1 second when root motion should have only applied for the last 0.1 seconds, or root motion source ending halfway through a 0.5 second tick)
Definition at line 251 of file RootMotionSource.h.
Status
FRootMotionSourceStatus FRootMotionSource::Status
Status of this source.
Definition at line 267 of file RootMotionSource.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h