Unreal Engine 5.6 C++ API: FPackedNormal Struct Reference
FPackedNormal Struct Reference
A normal vector, quantized and packed into 32-bits.
#include "PackedNormal.h"
Public Member Functions
FPackedNormal ()
FPackedNormal (const FVector3d &InVector)
FPackedNormal (const FVector3f &InVector)
FPackedNormal (const FVector4d &InVector)
FPackedNormal (const FVector4f &InVector)
VectorRegister4Float GetVectorRegister () const
bool operator!= (const FPackedNormal &B) const
void operator= (const FVector3d &InVector)
void operator= (const FVector3f &InVector)
void operator= (const FVector4d &InVector)
void operator= (const FVector4f &InVector)
bool operator== (const FPackedNormal &B) const
void Set (const FVector &InVector)
FVector ToFVector () const
FVector3f ToFVector3f () const
FVector4 ToFVector4 () const
FVector4f ToFVector4f () const
FString ToString () const
Data Fields
union {
struct {
int8 W
int8 X
int8 Y
int8 Z
}
uint32 Packed
} Vector
Friends
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FPackedNormal &N)
Detailed Description
A normal vector, quantized and packed into 32-bits.
Definition at line 12 of file PackedNormal.h.
Constructor & Destructor Documentation
FPackedNormal() [1/5]
FPackedNormal::FPackedNormal () inline
Definition at line 26 of file PackedNormal.h.
References Vector.
Referenced by operator!=(), operator<<, and operator==().
FPackedNormal() [2/5]
FPackedNormal::FPackedNormal (const FVector3f & InVector) inline
Definition at line 27 of file PackedNormal.h.
FPackedNormal() [3/5]
FPackedNormal::FPackedNormal (const FVector3d & InVector) inline
Definition at line 28 of file PackedNormal.h.
FPackedNormal() [4/5]
FPackedNormal::FPackedNormal (const FVector4f & InVector) inline
Definition at line 29 of file PackedNormal.h.
FPackedNormal() [5/5]
FPackedNormal::FPackedNormal (const FVector4d & InVector) inline
Definition at line 30 of file PackedNormal.h.
Member Function Documentation
GetVectorRegister()
FORCEINLINE VectorRegister4Float FPackedNormal::GetVectorRegister () const
Definition at line 192 of file PackedNormal.h.
References FORCEINLINE, VectorLoadSignedByte4, VectorMultiply(), and VectorSetFloat1().
Referenced by ToFVector3f(), and ToFVector4f().
operator!=()
FORCEINLINE bool FPackedNormal::operator!= (const FPackedNormal & B) const
Definition at line 157 of file PackedNormal.h.
References FPackedNormal(), B, and FORCEINLINE.
operator=() [1/4]
FORCEINLINE void FPackedNormal::operator= (const FVector3d & InVector)
Definition at line 125 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int8, MIN_int8, Scale, Vector, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
operator=() [2/4]
FORCEINLINE void FPackedNormal::operator= (const FVector3f & InVector)
Definition at line 116 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int8, MIN_int8, Scale, Vector, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
operator=() [3/4]
FORCEINLINE void FPackedNormal::operator= (const FVector4d & InVector)
Definition at line 143 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int8, MIN_int8, Scale, Vector, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
operator=() [4/4]
FORCEINLINE void FPackedNormal::operator= (const FVector4f & InVector)
Definition at line 134 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int8, MIN_int8, Scale, Vector, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
operator==()
FORCEINLINE bool FPackedNormal::operator== (const FPackedNormal & B) const
Definition at line 152 of file PackedNormal.h.
References FPackedNormal(), B, FORCEINLINE, and Vector.
Set()
void FPackedNormal::Set (const FVector & InVector) inline
Definition at line 46 of file PackedNormal.h.
References FVector.
ToFVector()
FORCEINLINE FVector FPackedNormal::ToFVector () const
Definition at line 162 of file PackedNormal.h.
References FORCEINLINE, FVector, and ToFVector3f().
Referenced by GetBasisDeterminantSignByte().
ToFVector3f()
FORCEINLINE FVector3f FPackedNormal::ToFVector3f () const
Definition at line 168 of file PackedNormal.h.
References FORCEINLINE, GetVectorRegister(), and VectorStoreFloat3().
Referenced by ToFVector().
ToFVector4()
FORCEINLINE FVector4 FPackedNormal::ToFVector4 () const
Definition at line 177 of file PackedNormal.h.
References FORCEINLINE, and ToFVector4f().
ToFVector4f()
FORCEINLINE FVector4f FPackedNormal::ToFVector4f () const
Definition at line 183 of file PackedNormal.h.
References FORCEINLINE, GetVectorRegister(), and VectorStore().
Referenced by ToFVector4().
ToString()
FString FPackedNormal::ToString () const inline
Definition at line 55 of file PackedNormal.h.
References TEXT, and Vector.
Friends And Related Symbol Documentation
operator<<
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FPackedNormal & N) friend
References FPackedNormal(), and Ar.
Field Documentation
Packed
uint32 FPackedNormal::Packed
Definition at line 21 of file PackedNormal.h.
[union]
union { ... } FPackedNormal::Vector
Referenced by FPackedNormal(), operator=(), operator=(), operator=(), operator=(), operator==(), and ToString().
W
int8 FPackedNormal::W
Definition at line 18 of file PackedNormal.h.
X
int8 FPackedNormal::X
Definition at line 18 of file PackedNormal.h.
Y
int8 FPackedNormal::Y
Definition at line 18 of file PackedNormal.h.
Z
int8 FPackedNormal::Z
Definition at line 18 of file PackedNormal.h.
The documentation for this struct was generated from the following file:
PackedNormal.h