Unreal Engine 5.6 C++ API: Metasound::Frontend::FDocumentModifyDelegates Struct Reference
Metasound::Frontend::FDocumentModifyDelegates Struct Reference
#include "MetasoundFrontendDocumentModifyDelegates.h"
Public Member Functions
METASOUNDFRONTEND_API FDocumentModifyDelegates ()
METASOUNDFRONTEND_API FDocumentModifyDelegates (const FDocumentModifyDelegates &InModifyDelegates)
METASOUNDFRONTEND_API FDocumentModifyDelegates (const FMetasoundFrontendDocument &Document)
METASOUNDFRONTEND_API FDocumentModifyDelegates (FDocumentModifyDelegates &&)
METASOUNDFRONTEND_API void AddPageDelegates (const FGuid &InPageID)
METASOUNDFRONTEND_API FEdgeModifyDelegates & FindEdgeDelegatesChecked (const FGuid &InPageID)
METASOUNDFRONTEND_API FNodeModifyDelegates & FindNodeDelegatesChecked (const FGuid &InPageID)
void IterateGraphEdgeDelegates (TFunctionRef< void(FEdgeModifyDelegates &)> Func)
void IterateGraphNodeDelegates (TFunctionRef< void(FNodeModifyDelegates &)> Func)
METASOUNDFRONTEND_API FDocumentModifyDelegates & operator= (const FDocumentModifyDelegates &)
METASOUNDFRONTEND_API FDocumentModifyDelegates & operator= (FDocumentModifyDelegates &&)
METASOUNDFRONTEND_API void RemovePageDelegates (const FGuid &InPageID, bool bBroadcastNotify=true)
UE_DEPRECATED (5.5, "Public exposition of EdgeDelegates will be removed in a future build. Use accessor 'FindEdgeDelegates' instead") FEdgeModifyDelegates EdgeDelegates
UE_DEPRECATED (5.5, "Public exposition of NodeDelegates will be removed in a future build. Use accessor 'FindNodeDelegates' instead") FNodeModifyDelegates NodeDelegates
Public Member Functions inherited from TSharedFromThis< FDocumentModifyDelegates >
TSharedRef< FDocumentModifyDelegates, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDocumentModifyDelegates, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FInterfaceModifyDelegates InterfaceDelegates
FOnMetaSoundFrontendDocumentMutateArray OnDependencyAdded
FOnMetaSoundFrontendDocumentRemoveSwappingArray OnRemoveSwappingDependency
FOnMetaSoundFrontendDocumentRenameClass OnRenamingDependencyClass
FPageModifyDelegates PageDelegates
Private Attributes
TSortedMap< FGuid, FEdgeModifyDelegates > PageEdgeDelegates
TSortedMap< FGuid, FNodeModifyDelegates > PageNodeDelegates
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FDocumentModifyDelegates >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDocumentModifyDelegates >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 78 of file MetasoundFrontendDocumentModifyDelegates.h.
Constructor & Destructor Documentation
FDocumentModifyDelegates() [1/4]
METASOUNDFRONTEND_API Metasound::Frontend::FDocumentModifyDelegates::FDocumentModifyDelegates ()
References UE_API.
Referenced by FDocumentModifyDelegates(), FDocumentModifyDelegates(), operator=(), and operator=().
FDocumentModifyDelegates() [2/4]
METASOUNDFRONTEND_API Metasound::Frontend::FDocumentModifyDelegates::FDocumentModifyDelegates (const FDocumentModifyDelegates & InModifyDelegates)
References FDocumentModifyDelegates(), and UE_API.
FDocumentModifyDelegates() [3/4]
METASOUNDFRONTEND_API Metasound::Frontend::FDocumentModifyDelegates::FDocumentModifyDelegates (FDocumentModifyDelegates &&)
References FDocumentModifyDelegates(), and UE_API.
FDocumentModifyDelegates() [4/4]
METASOUNDFRONTEND_API Metasound::Frontend::FDocumentModifyDelegates::FDocumentModifyDelegates (const FMetasoundFrontendDocument & Document)
References UE_API.
Member Function Documentation
AddPageDelegates()
METASOUNDFRONTEND_API void Metasound::Frontend::FDocumentModifyDelegates::AddPageDelegates (const FGuid & InPageID)
References AddPageDelegates(), and UE_API.
Referenced by AddPageDelegates().
FindEdgeDelegatesChecked()
METASOUNDFRONTEND_API FEdgeModifyDelegates & Metasound::Frontend::FDocumentModifyDelegates::FindEdgeDelegatesChecked (const FGuid & InPageID)
References FindEdgeDelegatesChecked(), and UE_API.
Referenced by FindEdgeDelegatesChecked().
FindNodeDelegatesChecked()
METASOUNDFRONTEND_API FNodeModifyDelegates & Metasound::Frontend::FDocumentModifyDelegates::FindNodeDelegatesChecked (const FGuid & InPageID)
References FindNodeDelegatesChecked(), and UE_API.
Referenced by FindNodeDelegatesChecked().
IterateGraphEdgeDelegates()
void Metasound::Frontend::FDocumentModifyDelegates::IterateGraphEdgeDelegates (TFunctionRef< void(FEdgeModifyDelegates &)> Func) inline
Definition at line 112 of file MetasoundFrontendDocumentModifyDelegates.h.
References Metasound::Frontend::Func, IterateGraphEdgeDelegates(), PageEdgeDelegates, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by IterateGraphEdgeDelegates().
IterateGraphNodeDelegates()
void Metasound::Frontend::FDocumentModifyDelegates::IterateGraphNodeDelegates (TFunctionRef< void(FNodeModifyDelegates &)> Func) inline
Definition at line 124 of file MetasoundFrontendDocumentModifyDelegates.h.
References Metasound::Frontend::Func, PageNodeDelegates, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [1/2]
METASOUNDFRONTEND_API FDocumentModifyDelegates & Metasound::Frontend::FDocumentModifyDelegates::operator= (const FDocumentModifyDelegates &)
References FDocumentModifyDelegates(), and UE_API.
operator=() [2/2]
METASOUNDFRONTEND_API FDocumentModifyDelegates & Metasound::Frontend::FDocumentModifyDelegates::operator= (FDocumentModifyDelegates &&)
References FDocumentModifyDelegates(), and UE_API.
RemovePageDelegates()
METASOUNDFRONTEND_API void Metasound::Frontend::FDocumentModifyDelegates::RemovePageDelegates (const FGuid & InPageID, bool bBroadcastNotify = true)
References RemovePageDelegates(), and UE_API.
Referenced by RemovePageDelegates().
UE_DEPRECATED() [1/2]
Metasound::Frontend::FDocumentModifyDelegates::UE_DEPRECATED (5. 5, "Public exposition of EdgeDelegates will be removed in a future build. Use accessor 'FindEdgeDelegates' instead")
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
Metasound::Frontend::FDocumentModifyDelegates::UE_DEPRECATED (5. 5, "Public exposition of NodeDelegates will be removed in a future build. Use accessor 'FindNodeDelegates' instead")
Referenced by UE_DEPRECATED().
Field Documentation
InterfaceDelegates
FInterfaceModifyDelegates Metasound::Frontend::FDocumentModifyDelegates::InterfaceDelegates
Definition at line 93 of file MetasoundFrontendDocumentModifyDelegates.h.
OnDependencyAdded
FOnMetaSoundFrontendDocumentMutateArray Metasound::Frontend::FDocumentModifyDelegates::OnDependencyAdded
Definition at line 88 of file MetasoundFrontendDocumentModifyDelegates.h.
OnRemoveSwappingDependency
FOnMetaSoundFrontendDocumentRemoveSwappingArray Metasound::Frontend::FDocumentModifyDelegates::OnRemoveSwappingDependency
Definition at line 89 of file MetasoundFrontendDocumentModifyDelegates.h.
OnRenamingDependencyClass
FOnMetaSoundFrontendDocumentRenameClass Metasound::Frontend::FDocumentModifyDelegates::OnRenamingDependencyClass
Definition at line 90 of file MetasoundFrontendDocumentModifyDelegates.h.
PageDelegates
FPageModifyDelegates Metasound::Frontend::FDocumentModifyDelegates::PageDelegates
Definition at line 92 of file MetasoundFrontendDocumentModifyDelegates.h.
PageEdgeDelegates
TSortedMap<FGuid, FEdgeModifyDelegates> Metasound::Frontend::FDocumentModifyDelegates::PageEdgeDelegates private
Definition at line 106 of file MetasoundFrontendDocumentModifyDelegates.h.
Referenced by IterateGraphEdgeDelegates().
PageNodeDelegates
TSortedMap<FGuid, FNodeModifyDelegates> Metasound::Frontend::FDocumentModifyDelegates::PageNodeDelegates private
Definition at line 105 of file MetasoundFrontendDocumentModifyDelegates.h.
Referenced by IterateGraphNodeDelegates().
The documentation for this struct was generated from the following file:
MetasoundFrontendDocumentModifyDelegates.h