Unreal Engine 5.6 C++ API: FMeshParticleVertexFactory Class Reference
FMeshParticleVertexFactory Class Reference
Vertex factory for rendering instanced mesh particles with out dynamic parameter support.
#include "MeshParticleVertexFactory.h"
Data Structures
class FBatchParametersCPU
struct FDataType
Public Member Functions
FMeshParticleVertexFactory ()
FMeshParticleVertexFactory (EParticleVertexFactoryType InType, ERHIFeatureLevel::Type InFeatureLevel, int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride)
Default constructor.
FMeshParticleVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
void Copy (const FMeshParticleVertexFactory &Other)
Copy the data from another vertex factory.
FMeshParticleInstanceVertices *& GetInstanceVerticesCPU ()
uint8 GetLODIdx () const
FRHIShaderResourceView * GetPreviousTransformBufferSRV () const
FORCEINLINE FRHIUniformBuffer * GetUniformBuffer ()
Retrieve the uniform buffer for this vertex factory.
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
uint8 * LockPreviousTransformBuffer (FRHICommandListBase &RHICmdList, uint32 ParticleCount)
void SetData (FRHICommandListBase &RHICmdList, const FDataType &InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
void SetDynamicParameterBuffer (const FVertexBuffer *InDynamicParameterBuffer, uint32 StreamOffset, uint32 Stride)
Set the source vertex buffer that contains particle dynamic parameter data.
void SetInstanceBuffer (const FVertexBuffer *InstanceBuffer, uint32 StreamOffset, uint32 Stride)
Set the source vertex buffer that contains particle instance data.
void SetLODIdx (uint8 InLODIdx)
void SetStrides (int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride)
Update the data strides (MUST HAPPEN BEFORE InitRHI is called)
FORCEINLINE void SetUniformBuffer (const FMeshParticleUniformBufferRef &InMeshParticleUniformBuffer)
Set the uniform buffer for this vertex factory.
UE_DEPRECATED (5.4, "SetData requires a command list.") 1 void SetData(const FDataType &InData)
void UnlockPreviousTransformBuffer (FRHICommandListBase &RHICmdList)
Public Member Functions inherited from FParticleVertexFactoryBase
FParticleVertexFactoryBase (EParticleVertexFactoryType Type, ERHIFeatureLevel::Type InFeatureLevel)
Default constructor.
FParticleVertexFactoryBase (ERHIFeatureLevel::Type InFeatureLevel)
ERHIFeatureLevel::Type GetFeatureLevel () const
FORCEINLINE EParticleVertexFactoryType GetParticleFactoryType () const
Return the vertex factory type.
void SetParticleFactoryType (EParticleVertexFactoryType InType)
Public Member Functions inherited from FVertexFactory
FVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
virtual RENDERCORE_API ~FVertexFactory ()
FVertexDeclarationRHIRef & GetDeclaration ()
const FVertexDeclarationRHIRef & GetDeclaration (EVertexInputStreamType InputStreamType) const
int32 GetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) const
RENDERCORE_API void GetStreams (ERHIFeatureLevel::Type InFeatureLevel, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &OutVertexStreams) const
virtual FShaderResourceViewRHIRef GetTriangleSortingPositionSRV () const
virtual FVertexFactoryType * GetType () const
bool NeedsDeclaration () const
RENDERCORE_API void OffsetInstanceStreams (uint32 InstanceOffset, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &VertexStreams) const
virtual RENDERCORE_API void ReleaseRHI ()
Releases the RHI resources used by this resource.
virtual bool RendersPrimitivesAsCameraFacingSprites () const
void SetDeclaration (FVertexDeclarationRHIRef &NewDeclaration)
bool SupportsGPUScene (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsManualVertexFetch (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsNullPixelShader () const
Indicates whether the vertex factory supports a null pixel shader.
virtual bool SupportsPositionAndNormalOnlyStream () const
Indicates whether the vertex factory supports a position-and-normal-only stream.
virtual bool SupportsPositionOnlyStream () const
Indicates whether the vertex factory supports a position-only stream.
bool SupportsTriangleSorting () const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Get vertex elements used when during PSO precaching materials using this vertex factory type.
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride, FDataType &Data, FVertexDeclarationElementList &Elements)
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Modify compile environment to enable instancing.
static bool ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters &Parameters)
Should we cache the material's shadertype on this platform with this vertex factory?
Static Public Member Functions inherited from FParticleVertexFactoryBase
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Static Public Member Functions inherited from FVertexFactory
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Can be overridden by FVertexFactory subclasses which have EVertexFactoryFlags::SupportsPSOPrecaching set - this function will only be called when that flag is set.
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Can be overridden by FVertexFactory subclasses to modify their compile environment just before compilation occurs.
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Can be overridden by FVertexFactory subclasses to fail a compile based on compilation output.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Static Protected Member Functions
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride, FDataType &Data, FVertexDeclarationElementList &Elements, FVertexStreamList &InOutStreams)
Static Protected Member Functions inherited from FVertexFactory
template<typename VertexStreamListType>
static FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, VertexStreamListType &InOutStreams)
Creates a vertex element for a vertex stream components.
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes
FDataType Data
int32 DynamicParameterVertexStride
int32 DynamicVertexStride
Stride information for instanced mesh particles.
FMeshParticleInstanceVertices * InstanceVerticesCPU
Used to remember this in the case that we reuse the same vertex factory for multiple renders .
uint8 LODIdx
FRHIUniformBuffer * MeshParticleUniformBuffer
Uniform buffer with mesh particle parameters.
FDynamicReadBuffer PrevTransformBuffer
Protected Attributes inherited from FVertexFactory
bool bNeedsDeclaration = true
FVertexStreamList Streams
The vertex streams used to render the factory.
Private Member Functions
DECLARE_VERTEX_FACTORY_TYPE (FMeshParticleVertexFactory)
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Types inherited from FVertexFactory
typedef TArray< FVertexStream, TInlineAllocator< 8 > > FVertexStreamList
Protected Member Functions inherited from FVertexFactory
FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex)
Creates a vertex element for a vertex stream components.
RENDERCORE_API FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, EVertexInputStreamType InputStreamType)
Creates a vertex element for a vertex stream component.
RENDERCORE_API bool AddPrimitiveIdStreamElement (EVertexInputStreamType InputStreamType, FVertexDeclarationElementList &Elements, uint8 AttributeIndex, uint8 AttributeIndex_Mobile)
RENDERCORE_API void InitDeclaration (const FVertexDeclarationElementList &Elements, EVertexInputStreamType StreamType=EVertexInputStreamType::Default)
Initializes the vertex declaration.
void SetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType, int32 StreamIndex)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Detailed Description
Vertex factory for rendering instanced mesh particles with out dynamic parameter support.
Definition at line 45 of file MeshParticleVertexFactory.h.
Constructor & Destructor Documentation
FMeshParticleVertexFactory() [1/3]
FMeshParticleVertexFactory::FMeshParticleVertexFactory (ERHIFeatureLevel::Type InFeatureLevel) inline
Definition at line 49 of file MeshParticleVertexFactory.h.
References FParticleVertexFactoryBase::FParticleVertexFactoryBase().
Referenced by Copy(), and DECLARE_VERTEX_FACTORY_TYPE().
FMeshParticleVertexFactory() [2/3]
FMeshParticleVertexFactory::FMeshParticleVertexFactory (EParticleVertexFactoryType InType, ERHIFeatureLevel::Type InFeatureLevel, int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride) inline
Default constructor.
Definition at line 89 of file MeshParticleVertexFactory.h.
References FParticleVertexFactoryBase::FParticleVertexFactoryBase(), DynamicParameterVertexStride, DynamicVertexStride, InstanceVerticesCPU, and LODIdx.
FMeshParticleVertexFactory() [3/3]
FMeshParticleVertexFactory::FMeshParticleVertexFactory () inline
Definition at line 97 of file MeshParticleVertexFactory.h.
References FParticleVertexFactoryBase::FParticleVertexFactoryBase(), DynamicParameterVertexStride, DynamicVertexStride, InstanceVerticesCPU, LODIdx, Num, and PVFT_MAX.
Member Function Documentation
Copy()
void FMeshParticleVertexFactory::Copy (const FMeshParticleVertexFactory & Other)
Copy the data from another vertex factory.
Parameters
Other - factory to copy from
References FMeshParticleVertexFactory(), and Other.
DECLARE_VERTEX_FACTORY_TYPE()
FMeshParticleVertexFactory::DECLARE_VERTEX_FACTORY_TYPE (FMeshParticleVertexFactory) private
References FMeshParticleVertexFactory().
GetInstanceVerticesCPU()
FMeshParticleInstanceVertices *& FMeshParticleVertexFactory::GetInstanceVerticesCPU () inline
Definition at line 180 of file MeshParticleVertexFactory.h.
References InstanceVerticesCPU.
GetLODIdx()
uint8 FMeshParticleVertexFactory::GetLODIdx () const inline
Definition at line 190 of file MeshParticleVertexFactory.h.
References LODIdx.
GetPreviousTransformBufferSRV()
FRHIShaderResourceView * FMeshParticleVertexFactory::GetPreviousTransformBufferSRV () const
GetPSOPrecacheVertexFetchElements()
void FMeshParticleVertexFactory::GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList & Elements) static
Get vertex elements used when during PSO precaching materials using this vertex factory type.
GetUniformBuffer()
FORCEINLINE FRHIUniformBuffer * FMeshParticleVertexFactory::GetUniformBuffer () inline
Retrieve the uniform buffer for this vertex factory.
Definition at line 142 of file MeshParticleVertexFactory.h.
References FORCEINLINE, and MeshParticleUniformBuffer.
GetVertexElements() [1/2]
void FMeshParticleVertexFactory::GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride, FDataType & Data, FVertexDeclarationElementList & Elements) static
References Data, and FRenderResource::FeatureLevel.
GetVertexElements() [2/2]
void FMeshParticleVertexFactory::GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride, FDataType & Data, FVertexDeclarationElementList & Elements, FVertexStreamList & InOutStreams) static protected
References Data, and FRenderResource::FeatureLevel.
InitRHI()
virtual void FMeshParticleVertexFactory::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
LockPreviousTransformBuffer()
uint8 * FMeshParticleVertexFactory::LockPreviousTransformBuffer (FRHICommandListBase & RHICmdList, uint32 ParticleCount)
ModifyCompilationEnvironment()
void FMeshParticleVertexFactory::ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) static
Modify compile environment to enable instancing.
Parameters
OutEnvironment - shader compile environment to modify
SetData()
void FMeshParticleVertexFactory::SetData (FRHICommandListBase & RHICmdList, const FDataType & InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
Referenced by UE_DEPRECATED().
SetDynamicParameterBuffer()
void FMeshParticleVertexFactory::SetDynamicParameterBuffer (const FVertexBuffer * InDynamicParameterBuffer, uint32 StreamOffset, uint32 Stride)
Set the source vertex buffer that contains particle dynamic parameter data.
SetInstanceBuffer()
void FMeshParticleVertexFactory::SetInstanceBuffer (const FVertexBuffer * InstanceBuffer, uint32 StreamOffset, uint32 Stride)
Set the source vertex buffer that contains particle instance data.
SetLODIdx()
void FMeshParticleVertexFactory::SetLODIdx (uint8 InLODIdx) inline
Definition at line 185 of file MeshParticleVertexFactory.h.
References LODIdx.
SetStrides()
void FMeshParticleVertexFactory::SetStrides (int32 InDynamicVertexStride, int32 InDynamicParameterVertexStride) inline
Update the data strides (MUST HAPPEN BEFORE InitRHI is called)
Definition at line 150 of file MeshParticleVertexFactory.h.
References DynamicParameterVertexStride, DynamicVertexStride, ensure, and IsInitialized.
SetUniformBuffer()
FORCEINLINE void FMeshParticleVertexFactory::SetUniformBuffer (const FMeshParticleUniformBufferRef & InMeshParticleUniformBuffer) inline
Set the uniform buffer for this vertex factory.
Definition at line 134 of file MeshParticleVertexFactory.h.
References FORCEINLINE, MeshParticleUniformBuffer, and SetUniformBuffer().
Referenced by SetUniformBuffer().
ShouldCompilePermutation()
bool FMeshParticleVertexFactory::ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters & Parameters) static
Should we cache the material's shadertype on this platform with this vertex factory?
UE_DEPRECATED()
FMeshParticleVertexFactory::UE_DEPRECATED (5. 4, "SetData requires a command list.") const &
References SetData().
UnlockPreviousTransformBuffer()
void FMeshParticleVertexFactory::UnlockPreviousTransformBuffer (FRHICommandListBase & RHICmdList)
Field Documentation
Data
FDataType FMeshParticleVertexFactory::Data protected
Definition at line 198 of file MeshParticleVertexFactory.h.
Referenced by GetVertexElements(), and GetVertexElements().
DynamicParameterVertexStride
int32 FMeshParticleVertexFactory::DynamicParameterVertexStride protected
Definition at line 204 of file MeshParticleVertexFactory.h.
Referenced by FMeshParticleVertexFactory(), FMeshParticleVertexFactory(), and SetStrides().
DynamicVertexStride
int32 FMeshParticleVertexFactory::DynamicVertexStride protected
Stride information for instanced mesh particles.
Definition at line 203 of file MeshParticleVertexFactory.h.
Referenced by FMeshParticleVertexFactory(), FMeshParticleVertexFactory(), and SetStrides().
InstanceVerticesCPU
FMeshParticleInstanceVertices* FMeshParticleVertexFactory::InstanceVerticesCPU protected
Used to remember this in the case that we reuse the same vertex factory for multiple renders .
Definition at line 212 of file MeshParticleVertexFactory.h.
Referenced by FMeshParticleVertexFactory(), FMeshParticleVertexFactory(), and GetInstanceVerticesCPU().
LODIdx
uint8 FMeshParticleVertexFactory::LODIdx protected
Definition at line 200 of file MeshParticleVertexFactory.h.
Referenced by FMeshParticleVertexFactory(), FMeshParticleVertexFactory(), GetLODIdx(), and SetLODIdx().
MeshParticleUniformBuffer
FRHIUniformBuffer* FMeshParticleVertexFactory::MeshParticleUniformBuffer protected
Uniform buffer with mesh particle parameters.
Definition at line 207 of file MeshParticleVertexFactory.h.
Referenced by GetUniformBuffer(), and SetUniformBuffer().
PrevTransformBuffer
FDynamicReadBuffer FMeshParticleVertexFactory::PrevTransformBuffer protected
Definition at line 209 of file MeshParticleVertexFactory.h.
The documentation for this class was generated from the following file:
MeshParticleVertexFactory.h