Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FEditLayerTargetTypeState Class Reference
UE::Landscape::EditLayers::FEditLayerTargetTypeState Class Reference
FEditLayerTargetTypeState fully describes the state of an edit layer renderer wrt its target types.
#include "LandscapeEditLayerTargetTypeState.h"
Public Member Functions
FEditLayerTargetTypeState Intersect (const FEditLayerTargetTypeState &InOther) const
Returns the "intersection" (AND operation) between the target type state and the one in parameter.
bool operator== (const FEditLayerTargetTypeState &InOther) const
FString ToString () const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") ELandscapeToolTargetTypeFlags GetTargetTypeMask() const
Returns the target type mask (i.e.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API bool IsActive(ELandscapeToolTargetType InTargetType
Indicates whether a given target type is currently active in this state.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API bool IsActive(ELandscapeToolTargetType InTargetType
Indicates whether a given target type is currently active in this state.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API bool IsActiveChecked(ELandscapeToolTargetType InTargetType
Indicates whether a given target type is currently active in this state.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FEditLayerTargetTypeState(const FMergeContext *InMergeContext
Initializes a FEditLayerTargetTypeState with the target types passed in parameter.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FEditLayerTargetTypeState(const FMergeContext *InMergeContext
Initializes a FEditLayerTargetTypeState with the target types and the weightmaps passed in parameter (by name)
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FEditLayerTargetTypeState(const FMergeContext *InMergeContext
Initializes a FEditLayerTargetTypeState with the target types and (optionally) the weightmaps passed in parameter (by bit index)
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FEditLayerTargetTypeState(const FMergeContext *InMergeContext)
Constructs an empty FEditLayerTargetTypeState (all target types turned off, no active weightmaps)
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TArray< FName > GetActiveWeightmaps() const
Returns the currently active weightmaps :
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> GetActiveWeightmapBitIndices() const
Returns the currently active weightmaps :
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void AddTargetType(ELandscapeToolTargetType InTargetType)
Adds the target type in parameter to the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void AddTargetTypeMask(ELandscapeToolTargetTypeFlags InTargetTypeMask)
Appends the target type mask in parameter to the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void AddWeightmap(const FName &InWeightmapLayerName)
Adds a weightmap to the list of active weightmaps (make sure ELandscapeToolTargetType::Weightmap is amongst the supported target types)
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void AddWeightmap(int32 InWeightmapLayerIndex)
Adds a weightmap to the list of active weightmaps (make sure ELandscapeToolTargetType::Weightmap is amongst the supported target types).
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void AddWeightmapChecked(const FName &InWeightmapLayerName)
Adds a weightmap to the list of active weightmaps (make sure ELandscapeToolTargetType::Weightmap is amongst the supported target types).
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void RemoveTargetType(ELandscapeToolTargetType InTargetType)
Removes a single target type from the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void RemoveTargetTypeMask(ELandscapeToolTargetTypeFlags InTargetTypeMask)
Removes the target type mask in parameter from the mask of active target types.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void RemoveWeightmap(const FName &InWeightmapLayerName)
Removes a weightmap from the list of active weightmaps.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void RemoveWeightmap(int32 InWeightmapLayerIndex)
Removes a weightmap from the list of active weightmaps.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void RemoveWeightmapChecked(const FName &InWeightmapLayerName)
Removes a weightmap from the list of active weightmaps.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void SetTargetTypeMask(ELandscapeToolTargetTypeFlags InTargetTypeMask)
Sets the target type mask (i.e.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") static const FEditLayerTargetTypeState &GetDummyTargetTypeState()
Data Fields
ELandscapeToolTargetTypeFlags const TArrayView< const FName > bool bInChecked
ELandscapeToolTargetTypeFlags const TBitArray & InSupportedWeightmapLayerIndices
ELandscapeToolTargetTypeFlags const TArrayView< const FName > & InSupportedWeightmaps
ELandscapeToolTargetTypeFlags InTargetTypeMask
int32 InWeightmapLayerIndex = INDEX_NONE) const
const FName & InWeightmapLayerName = NAME_None) const
Private Member Functions
FEditLayerTargetTypeState ()=default
Private Attributes
friend FEditLayerRendererState
friend ILandscapeEditLayerRenderer
const FMergeContext * MergeContext = nullptr
Global context being used for this merge : contains generic information about the landscape, its available layer names, etc.
ELandscapeToolTargetTypeFlags TargetTypeMask = ELandscapeToolTargetTypeFlags::None
Bitmask of the target types that are supported.
TBitArray WeightmapTargetLayerBitIndices
List of weightmaps that are supported for the ELandscapeToolTargetType::Weightmap/ELandscapeToolTargetTypeVisibility type.
Detailed Description
FEditLayerTargetTypeState fully describes the state of an edit layer renderer wrt its target types.
It's named after the enum "ELandscapeToolTargetType" in order to tell whether the renderer's heightmaps and/or visibility and/or weightmaps are enabled (and if so, which weightmap is enabled exactly)
It is meant to be provided by the edit layer renderer's GetRendererStateInfo implementation.
Definition at line 34 of file LandscapeEditLayerTargetTypeState.h.
Constructor & Destructor Documentation
FEditLayerTargetTypeState()
UE::Landscape::EditLayers::FEditLayerTargetTypeState::FEditLayerTargetTypeState () private default
Referenced by Intersect(), operator==(), and UE_EXPERIMENTAL().
Member Function Documentation
Intersect()
FEditLayerTargetTypeState UE::Landscape::EditLayers::FEditLayerTargetTypeState::Intersect (const FEditLayerTargetTypeState & InOther) const
Returns the "intersection" (AND operation) between the target type state and the one in parameter.
e.g. if state S0 is:
(------—|Visibility|Weightmap) with active weightmaps (A|B|C|-), and state S1 is:
(Heightmap|-------—|Weightmap) with active weightmaps (-|-|C|D), then state S0.Intersect(S1) is:
(------—|-------—|Weightmap) with active weightmaps (-|-|C|-)
References FEditLayerTargetTypeState().
operator==()
bool UE::Landscape::EditLayers::FEditLayerTargetTypeState::operator== (const FEditLayerTargetTypeState & InOther) const
References FEditLayerTargetTypeState().
ToString()
FString UE::Landscape::EditLayers::FEditLayerTargetTypeState::ToString () const
UE_EXPERIMENTAL() [1/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Returns the target type mask (i.e.
same as ELandscapeToolTargetType, but as bit flags)
Definition at line 127 of file LandscapeEditLayerTargetTypeState.h.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and TargetTypeMask.
UE_EXPERIMENTAL() [2/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Indicates whether a given target type is currently active in this state.
Parameters
InTargetType the requested target type (heightmap/weightmap/visibility)
InWeightmapLayerName (optional) is the requested weightmap, only relevant for the ELandscapeToolTargetType::Weightmap case
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [3/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Indicates whether a given target type is currently active in this state.
Parameters
InTargetType is the requested target type (heightmap/weightmap/visibility)
int32 (optional) is the requested weightmap index (in FMergeContex), only relevant for the ELandscapeToolTargetType::Weightmap case. Asserts if the layer index isn't valid for the merge context (except for INDEX_NONE)
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [4/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Indicates whether a given target type is currently active in this state.
Parameters
InTargetType the requested target type (heightmap/weightmap/visibility)
InWeightmapLayerName (optional) is the requested weightmap, only relevant for the ELandscapeToolTargetType::Weightmap case. Asserts if the layer name isn't valid for the merge context (except for NAME_None)
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [5/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Initializes a FEditLayerTargetTypeState with the target types passed in parameter.
Parameters
InMergeContext context containing all sorts of information related to this merge operation
InTargetTypeMask target type mask supported by this target type state (no active weightmaps)
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [6/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Initializes a FEditLayerTargetTypeState with the target types and the weightmaps passed in parameter (by name)
Parameters
InMergeContext context containing all sorts of information related to this merge operation
InTargetTypeMask target type mask supported by this target type state
InSupportedWeightmaps names of weightmaps supported by this target type state
bInChecked,if true, will validate that every weightmap requested is part of the merge context (if false, only the known weightmaps will be marked as supported)
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [7/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Initializes a FEditLayerTargetTypeState with the target types and (optionally) the weightmaps passed in parameter (by bit index)
Parameters
InMergeContext context containing all sorts of information related to this merge operation
InTargetTypeMask target type mask supported by this target type state
InSupportedWeightmaps bit indices of the weightmaps supported by this target type state (corresponds to the FMergeContext's AllTargetLayerNames) Asserts if one of the layer indices isn't valid for the merge context (except when InSupportedWeightmapLayerIndices is == TBitArray<>)
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [8/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Constructs an empty FEditLayerTargetTypeState (all target types turned off, no active weightmaps)
Parameters
InMergeContext context containing all sorts of information related to this merge operation
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [9/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns the currently active weightmaps :
If Weightmap is amongst the target types it will return all the weightmaps
Additionally, if Visibility is amongst the target types, it will also return the visibility weightmap
If neither Weightmap nor Visibility is amongst the target types, it will return an empty array
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [10/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns the currently active weightmaps :
If Weightmap is amongst the target types it will return all the weightmaps
Additionally, if Visibility is amongst the target types, it will also return the visibility weightmap
If neither Weightmap nor Visibility is amongst the target types, it will return an empty array
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [11/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Adds the target type in parameter to the mask of active target types.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [12/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Appends the target type mask in parameter to the mask of active target types.
References InTargetTypeMask, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [13/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Adds a weightmap to the list of active weightmaps (make sure ELandscapeToolTargetType::Weightmap is amongst the supported target types)
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [14/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Adds a weightmap to the list of active weightmaps (make sure ELandscapeToolTargetType::Weightmap is amongst the supported target types).
Asserts if the layer index isn't valid for the merge context
References InWeightmapLayerIndex, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [15/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Adds a weightmap to the list of active weightmaps (make sure ELandscapeToolTargetType::Weightmap is amongst the supported target types).
Asserts if the layer name isn't known to the merge context.
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [16/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Removes a single target type from the mask of active target types.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [17/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Removes the target type mask in parameter from the mask of active target types.
References InTargetTypeMask, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [18/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Removes a weightmap from the list of active weightmaps.
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [19/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Removes a weightmap from the list of active weightmaps.
Asserts if the layer index isn't valid for the merge context.
References InWeightmapLayerIndex, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [20/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Removes a weightmap from the list of active weightmaps.
Asserts if the layer name isn't known to the merge context.
References InWeightmapLayerName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [21/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Sets the target type mask (i.e.
same as ELandscapeToolTargetType, but as bit flags)
References InTargetTypeMask, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [22/22]
UE::Landscape::EditLayers::FEditLayerTargetTypeState::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
References FEditLayerTargetTypeState(), and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
Field Documentation
bInChecked
ELandscapeToolTargetTypeFlags const TArrayView<const FName> bool UE::Landscape::EditLayers::FEditLayerTargetTypeState::bInChecked
Definition at line 73 of file LandscapeEditLayerTargetTypeState.h.
FEditLayerRendererState
friend UE::Landscape::EditLayers::FEditLayerTargetTypeState::FEditLayerRendererState private
Definition at line 37 of file LandscapeEditLayerTargetTypeState.h.
ILandscapeEditLayerRenderer
friend UE::Landscape::EditLayers::FEditLayerTargetTypeState::ILandscapeEditLayerRenderer private
Definition at line 36 of file LandscapeEditLayerTargetTypeState.h.
InSupportedWeightmapLayerIndices
ELandscapeToolTargetTypeFlags const TBitArray& UE::Landscape::EditLayers::FEditLayerTargetTypeState::InSupportedWeightmapLayerIndices
Definition at line 84 of file LandscapeEditLayerTargetTypeState.h.
InSupportedWeightmaps
ELandscapeToolTargetTypeFlags const TArrayView<const FName>& UE::Landscape::EditLayers::FEditLayerTargetTypeState::InSupportedWeightmaps
Definition at line 73 of file LandscapeEditLayerTargetTypeState.h.
InTargetTypeMask
ELandscapeToolTargetTypeFlags UE::Landscape::EditLayers::FEditLayerTargetTypeState::InTargetTypeMask
Definition at line 62 of file LandscapeEditLayerTargetTypeState.h.
Referenced by UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
InWeightmapLayerIndex
int32 UE::Landscape::EditLayers::FEditLayerTargetTypeState::InWeightmapLayerIndex = INDEX_NONE) const
Definition at line 108 of file LandscapeEditLayerTargetTypeState.h.
Referenced by UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
InWeightmapLayerName
const FName & UE::Landscape::EditLayers::FEditLayerTargetTypeState::InWeightmapLayerName = NAME_None) const
Definition at line 92 of file LandscapeEditLayerTargetTypeState.h.
Referenced by UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
MergeContext
const FMergeContext* UE::Landscape::EditLayers::FEditLayerTargetTypeState::MergeContext = nullptr private
Global context being used for this merge : contains generic information about the landscape, its available layer names, etc.
Definition at line 188 of file LandscapeEditLayerTargetTypeState.h.
TargetTypeMask
ELandscapeToolTargetTypeFlags UE::Landscape::EditLayers::FEditLayerTargetTypeState::TargetTypeMask = ELandscapeToolTargetTypeFlags::None private
Bitmask of the target types that are supported.
Definition at line 191 of file LandscapeEditLayerTargetTypeState.h.
Referenced by UE_EXPERIMENTAL().
WeightmapTargetLayerBitIndices
TBitArray UE::Landscape::EditLayers::FEditLayerTargetTypeState::WeightmapTargetLayerBitIndices private
List of weightmaps that are supported for the ELandscapeToolTargetType::Weightmap/ELandscapeToolTargetTypeVisibility type.
Each bit in that bit array corresponds to an entry in FMergeContext's AllTargetLayerNames
Definition at line 197 of file LandscapeEditLayerTargetTypeState.h.
The documentation for this class was generated from the following file:
LandscapeEditLayerTargetTypeState.h