Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicGraph3< T > Class Template Reference
UE::Geometry::FDynamicGraph3< T > Class Template Reference
#include "DynamicGraph3.h"
Public Member Functions
int AppendVertex (TVector< T > V)
FAxisAlignedBox2d GetBounds () const
TVector< T > GetEdgeCenter (int EID) const
TSegment3< T > GetEdgeSegment (int EID) const
FIndex2i GetEdgeV (int EID) const
bool GetEdgeV (int EID, TVector< T > &A, TVector< T > &B) const
TVector< T > GetVertex (int VID) const
bool InsertVertex (int32 Vid, TVector< T > V)
void SetVertex (int VID, TVector< T > VNewPos)
FRefCountVector::IndexEnumerable VertexIndicesItr () const
value_iteration< TVector< T > > VerticesItr () const
Enumerate positions of all Vertices in graph.
Public Member Functions inherited from UE::Geometry::FDynamicGraph
FDynamicGraph ()
virtual ~FDynamicGraph ()
int AllocateEdgeGroup ()
int AppendEdge (const FEdge &E)
int AppendEdge (const FIndex2i &ev, int GID=-1)
int AppendEdge (int v0, int v1, int GID=-1)
virtual bool CheckValidity (EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check) const
This function checks that the graph is well-formed, ie all internal data structures are consistent.
EMeshResult CollapseEdge (int VKeep, int VRemove, FEdgeCollapseInfo &Collapse)
int EdgeCount () const
edge_iterator EdgeIndices () const
value_iteration< FEdge > Edges () const
Enumerate edges.
int FindEdge (int VA, int VB) const
FEdge GetEdge (int EID) const
int GetEdgeGroup (int EID) const
FIndex2i GetEdgeV (int EID) const
int GetMaxVtxEdgeCount () const
int GetVtxEdgeCount (int VID) const
bool IsBoundaryVertex (int VID) const
bool IsCompact () const
bool IsCompactV () const
bool IsEdge (int EID) const
bool IsJunctionVertex (int VID) const
bool IsRegularVertex (int VID) const
bool IsVertex (int VID) const
int MaxEdgeID () const
int MaxGroupID () const
int MaxVertexID () const
EMeshResult RemoveEdge (int EID, bool bRemoveIsolatedVertices)
EMeshResult RemoveVertex (int VID, bool bRemoveIsolatedVertices)
void SetEdgeGroup (int EID, int GroupID)
int ShapeTimestamp () const
EMeshResult SplitEdge (int EAB, FEdgeSplitInfo &Split)
EMeshResult SplitEdge (int VA, int VB, FEdgeSplitInfo &Split)
EMeshResult SplitEdgeWithExistingVertex (int EAB, int ExistingMidVert, FEdgeSplitInfo &Split)
int Timestamp () const
int VertexCount () const
vertex_iterator VertexIndices () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int VID) const
Enumerate edge ids connected to vertex (i.e.
FSmallListSet::MappedValueEnumerable VtxVerticesItr (int VID) const
Enumerate "other" vertices of edges connected to vertex (i.e.
Static Public Member Functions
static TVector< T > InvalidVertex ()
Static Public Member Functions inherited from UE::Geometry::FDynamicGraph
static FEdge InvalidEdge3 ()
static FIndex2i InvalidEdgeV ()
Protected Member Functions
virtual int append_new_split_vertex (int A, int B) override
virtual void subclass_validity_checks (TFunction< void(bool)> CheckOrFailF) const override
Protected Member Functions inherited from UE::Geometry::FDynamicGraph
int add_edge (int A, int B, int GID)
int append_vertex_internal ()
void debug_check_is_edge (int E) const
void debug_check_is_vertex (int V) const
bool edge_has_v (int EID, int VID) const
int edge_other_v (int EID, int VID) const
bool insert_vertex_internal (int32 Vid)
int replace_edge_vertex (int EID, int VOld, int VNew)
void updateTimeStamp (bool bShapeChange)
Private Attributes
TDynamicVectorN< T, 3 > Vertices
Additional Inherited Members
Public Types inherited from UE::Geometry::FDynamicGraph
typedef FRefCountVector::IndexEnumerable edge_iterator
template<typename T>
using value_iteration = FRefCountVector::MappedEnumerable<T>
typedef FRefCountVector::IndexEnumerable vertex_iterator
Static Public Attributes inherited from UE::Geometry::FDynamicGraph
static constexpr int DuplicateEdgeID = -2
static constexpr int InvalidID = IndexConstants::InvalidID
Protected Attributes inherited from UE::Geometry::FDynamicGraph
TDynamicVector< FEdge > edges
FRefCountVector edges_refcount
int max_group_id = 0
int shape_timestamp = 0
int timestamp = 0
FSmallListSet vertex_edges
FRefCountVector vertices_refcount
Detailed Description
template<typename T>
class UE::Geometry::FDynamicGraph3< T >
Definition at line 26 of file DynamicGraph3.h.
Member Function Documentation
append_new_split_vertex()
template<typename T> virtual int UE::Geometry::FDynamicGraph3< T >::append_new_split_vertex (int A, int B) inline override protected virtual
Reimplemented from UE::Geometry::FDynamicGraph.
Definition at line 134 of file DynamicGraph3.h.
AppendVertex()
template<typename T> int UE::Geometry::FDynamicGraph3< T >::AppendVertex (TVector< T > V) inline
Definition at line 79 of file DynamicGraph3.h.
Referenced by UE::Geometry::FDynamicGraph3< double >::append_new_split_vertex().
GetBounds()
template<typename T> FAxisAlignedBox2d UE::Geometry::FDynamicGraph3< T >::GetBounds () const inline
Definition at line 121 of file DynamicGraph3.h.
GetEdgeCenter()
template<typename T> TVector< T > UE::Geometry::FDynamicGraph3< T >::GetEdgeCenter (int EID) const inline
Definition at line 72 of file DynamicGraph3.h.
GetEdgeSegment()
template<typename T> TSegment3< T > UE::Geometry::FDynamicGraph3< T >::GetEdgeSegment (int EID) const inline
Definition at line 63 of file DynamicGraph3.h.
GetEdgeV() [1/2]
template<typename T> FIndex2i UE::Geometry::FDynamicGraph::GetEdgeV (int EID) const inline
Definition at line 152 of file DynamicGraph.h.
GetEdgeV() [2/2]
template<typename T> bool UE::Geometry::FDynamicGraph3< T >::GetEdgeV (int EID, TVector< T > & A, TVector< T > & B) const inline
Definition at line 52 of file DynamicGraph3.h.
GetVertex()
template<typename T> TVector< T > UE::Geometry::FDynamicGraph3< T >::GetVertex (int VID) const inline
Definition at line 36 of file DynamicGraph3.h.
Referenced by UE::Geometry::FDynamicGraph3< double >::append_new_split_vertex(), and UE::Geometry::FDynamicGraph3< double >::subclass_validity_checks().
InsertVertex()
template<typename T> bool UE::Geometry::FDynamicGraph3< T >::InsertVertex (int32 Vid, TVector< T > V) inline
Returns
false If insertion failed (because a vertex with that ID already exists).
Definition at line 89 of file DynamicGraph3.h.
InvalidVertex()
template<typename T> TVector< T > UE::Geometry::FDynamicGraph3< T >::InvalidVertex () inline static
Definition at line 31 of file DynamicGraph3.h.
Referenced by UE::Geometry::FDynamicGraph3< double >::GetVertex().
SetVertex()
template<typename T> void UE::Geometry::FDynamicGraph3< T >::SetVertex (int VID, TVector< T > VNewPos) inline
Definition at line 41 of file DynamicGraph3.h.
subclass_validity_checks()
template<typename T> virtual void UE::Geometry::FDynamicGraph3< T >::subclass_validity_checks (TFunction< void(bool)> CheckOrFailF) const inline override protected virtual
Reimplemented from UE::Geometry::FDynamicGraph.
Definition at line 141 of file DynamicGraph3.h.
VertexIndicesItr()
template<typename T> FRefCountVector::IndexEnumerable UE::Geometry::FDynamicGraph3< T >::VertexIndicesItr () const inline
Definition at line 105 of file DynamicGraph3.h.
VerticesItr()
template<typename T> value_iteration< TVector< T > > UE::Geometry::FDynamicGraph3< T >::VerticesItr () const inline
Enumerate positions of all Vertices in graph.
Definition at line 111 of file DynamicGraph3.h.
Field Documentation
Vertices
template<typename T> TDynamicVectorN<T, 3> UE::Geometry::FDynamicGraph3< T >::Vertices private
Definition at line 28 of file DynamicGraph3.h.
Referenced by UE::Geometry::FDynamicGraph3< double >::GetBounds().
The documentation for this class was generated from the following file:
DynamicGraph3.h