Unreal Engine 5.6 C++ API: FUniformBufferBinding Class Reference
FUniformBufferBinding Class Reference
#include "ShaderParameterMacros.h"
Public Member Functions
FUniformBufferBinding ()=default
FORCEINLINE EUniformBufferBindingFlags GetBindingFlags () const
FORCEINLINE FRHIUniformBuffer * GetUniformBuffer () const
FORCEINLINE bool IsShader () const
FORCEINLINE bool IsStatic () const
FORCEINLINE operator bool () const
Protected Member Functions
FORCEINLINE FUniformBufferBinding (const FUniformBufferRHIRef &InUniformBuffer, EUniformBufferBindingFlags InBindingFlags)
Private Attributes
EUniformBufferBindingFlags BindingFlags = EUniformBufferBindingFlags::Shader
FRHIUniformBuffer * UniformBuffer = nullptr
Detailed Description
Definition at line 184 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
FUniformBufferBinding() [1/2]
FUniformBufferBinding::FUniformBufferBinding () default
Referenced by TUniformBufferBinding< UniformBufferStructType >::TUniformBufferBinding(), and TUniformBufferBinding< UniformBufferStructType >::TUniformBufferBinding().
FUniformBufferBinding() [2/2]
FORCEINLINE FUniformBufferBinding::FUniformBufferBinding (const FUniformBufferRHIRef & InUniformBuffer, EUniformBufferBindingFlags InBindingFlags) inline protected
Definition at line 215 of file ShaderParameterMacros.h.
References BindingFlags, FORCEINLINE, and UniformBuffer.
Member Function Documentation
GetBindingFlags()
FORCEINLINE EUniformBufferBindingFlags FUniformBufferBinding::GetBindingFlags () const inline
Definition at line 194 of file ShaderParameterMacros.h.
References BindingFlags, and FORCEINLINE.
Referenced by TUniformBufferBinding< UniformBufferStructType >::TUniformBufferBinding().
GetUniformBuffer()
FORCEINLINE FRHIUniformBuffer * FUniformBufferBinding::GetUniformBuffer () const inline
Definition at line 189 of file ShaderParameterMacros.h.
References FORCEINLINE, and UniformBuffer.
Referenced by TUniformBufferBinding< UniformBufferStructType >::GetUniformBufferRef(), and TUniformBufferBinding< UniformBufferStructType >::operator->().
IsShader()
FORCEINLINE bool FUniformBufferBinding::IsShader () const inline
Definition at line 204 of file ShaderParameterMacros.h.
References BindingFlags, EnumHasAnyFlags(), and FORCEINLINE.
IsStatic()
FORCEINLINE bool FUniformBufferBinding::IsStatic () const inline
Definition at line 199 of file ShaderParameterMacros.h.
References BindingFlags, EnumHasAnyFlags(), and FORCEINLINE.
operator bool()
FORCEINLINE FUniformBufferBinding::operator bool () const inline
Definition at line 209 of file ShaderParameterMacros.h.
References FORCEINLINE, and UniformBuffer.
Field Documentation
BindingFlags
EUniformBufferBindingFlags FUniformBufferBinding::BindingFlags = EUniformBufferBindingFlags::Shader private
Definition at line 222 of file ShaderParameterMacros.h.
Referenced by FUniformBufferBinding(), GetBindingFlags(), IsShader(), and IsStatic().
UniformBuffer
FRHIUniformBuffer* FUniformBufferBinding::UniformBuffer = nullptr private
Definition at line 221 of file ShaderParameterMacros.h.
Referenced by FUniformBufferBinding(), GetUniformBuffer(), and operator bool().
The documentation for this class was generated from the following file:
ShaderParameterMacros.h