Unreal Engine 5.6 C++ API: FCbObjectId Class Reference
FCbObjectId Class Reference
An opaque 12-byte object identifier.
#include "CompactBinary.h"
Public Types
using ByteArray = uint8[12]
Public Member Functions
FCbObjectId ()=default
Construct an ObjectId with every byte initialized to zero.
FCbObjectId (const ByteArray &ObjectId)
Construct an ObjectId from an array of 12 bytes.
FCbObjectId (FMemoryView ObjectId)
Construct an ObjectId from a view of 12 bytes.
const ByteArray & GetBytes () const
Returns a reference to the raw byte array for the ObjectId.
constexpr FMemoryView GetView () const
Returns a view of the raw byte array for the ObjectId.
operator const ByteArray & () const
bool operator!= (const FCbObjectId &B) const
bool operator< (const FCbObjectId &B) const
bool operator== (const FCbObjectId &B) const
Static Public Member Functions
static FCbObjectId NewObjectId ()
Private Attributes
ByteArray Bytes {}
Friends
uint32 GetTypeHash (const FCbObjectId &Id)
template<typename CharType>
TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > &Builder, const FCbObjectId &Id)
Convert the ObjectId to a 24-character hex string.
Detailed Description
An opaque 12-byte object identifier.
It has no intrinsic meaning, and can only be properly interpreted in the context of its usage.
Definition at line 478 of file CompactBinary.h.
Member Typedef Documentation
ByteArray
using FCbObjectId::ByteArray = uint8[12]
Definition at line 481 of file CompactBinary.h.
Constructor & Destructor Documentation
FCbObjectId() [1/3]
FCbObjectId::FCbObjectId () default
Construct an ObjectId with every byte initialized to zero.
References ObjectId.
Referenced by GetTypeHash, NewObjectId(), operator!=(), operator<(), operator<<, and operator==().
FCbObjectId() [2/3]
FCbObjectId::FCbObjectId (const ByteArray & ObjectId) inline explicit
Construct an ObjectId from an array of 12 bytes.
Definition at line 533 of file CompactBinary.h.
References Bytes, FMemory::Memcpy(), and ObjectId.
FCbObjectId() [3/3]
FCbObjectId::FCbObjectId (FMemoryView ObjectId) explicit
Construct an ObjectId from a view of 12 bytes.
References ObjectId.
Member Function Documentation
GetBytes()
const ByteArray & FCbObjectId::GetBytes () const inline
Returns a reference to the raw byte array for the ObjectId.
Definition at line 493 of file CompactBinary.h.
References Bytes.
Referenced by operator<<.
GetView()
FMemoryView FCbObjectId::GetView () const inline constexpr
Returns a view of the raw byte array for the ObjectId.
Definition at line 497 of file CompactBinary.h.
References Bytes, and MakeMemoryView().
NewObjectId()
FCbObjectId FCbObjectId::NewObjectId () static nodiscard
References FCbObjectId().
operator const ByteArray &()
FCbObjectId::operator const ByteArray & () const inline
Definition at line 494 of file CompactBinary.h.
References Bytes.
operator!=()
bool FCbObjectId::operator!= (const FCbObjectId & B) const inline
Definition at line 506 of file CompactBinary.h.
References FCbObjectId(), B, and FMemory::Memcmp().
operator<()
bool FCbObjectId::operator< (const FCbObjectId & B) const inline
Definition at line 511 of file CompactBinary.h.
References FCbObjectId(), B, and FMemory::Memcmp().
operator==()
bool FCbObjectId::operator== (const FCbObjectId & B) const inline
Definition at line 501 of file CompactBinary.h.
References FCbObjectId(), B, and FMemory::Memcmp().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FCbObjectId & Id) friend
Definition at line 516 of file CompactBinary.h.
References FCbObjectId().
operator<<
template<typename CharType> TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > & Builder, const FCbObjectId & Id) friend
Convert the ObjectId to a 24-character hex string.
Definition at line 523 of file CompactBinary.h.
References FCbObjectId(), UE::String::BytesToHexLower(), and GetBytes().
Field Documentation
Bytes
ByteArray FCbObjectId::Bytes {} private
Definition at line 530 of file CompactBinary.h.
Referenced by FCbObjectId(), GetBytes(), GetView(), and operator const ByteArray &().
The documentation for this class was generated from the following file:
CompactBinary.h