Unreal Engine 5.6 C++ API: FMessageLog Class Reference
FMessageLog Class Reference
#include "MessageLog.h"
Public Member Functions
FMessageLog (const FName &InLogName)
Constructor.
~FMessageLog ()
Destructor When this object goes out of scope, its buffered messages will be flushed.
const TSharedRef< FTokenizedMessage > & AddMessage (const TSharedRef< FTokenizedMessage > &InMessage)
Add a message to the log.
void AddMessages (const TArray< TSharedRef< FTokenizedMessage > > &InMessages)
Add an array of messages to the message log.
DECLARE_DELEGATE_OneParam (FMessageSelectionChanged, TArray< TSharedRef< FTokenizedMessage > > &)
Delegate used when message selection changes.
DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< class IMessageLog >, FGetLog, const FName &)
Delegate to retrieve a log interface.
TSharedRef< FTokenizedMessage > Error (const FText &InMessage=FText())
void Flush ()
Send the currently buffered messages to the log & clear the buffer.
TSharedRef< FTokenizedMessage > Info (const FText &InMessage=FText())
TSharedRef< FTokenizedMessage > Message (EMessageSeverity::Type InSeverity, const FText &InMessage=FText())
Helper functions to allow easy adding of messages to the log.
void NewPage (const FText &InLabel)
Add a new page to the log.
void Notify (const FText &InMessage=FText(), EMessageSeverity::Type InSeverityFilter=EMessageSeverity::Info, bool bForce=false)
Notify the user with a message if there are messages present.
int32 NumMessages (EMessageSeverity::Type InSeverityFilter=EMessageSeverity::Info)
Check whether there are any messages present for this log.
void Open (EMessageSeverity::Type InSeverityFilter=EMessageSeverity::Info, bool bOpenEvenIfEmpty=false)
Opens the log for display to the user given certain conditions.
TSharedRef< FTokenizedMessage > PerformanceWarning (const FText &InMessage=FText())
void SetCurrentPage (const FText &InLabel)
Sets the current page to the one specified by the label.
FMessageLog & SuppressLoggingToOutputLog (bool bShouldSuppress=true)
Should we mirror message log messages from this instance to the output log during flush?
UE_DEPRECATED (5.1, "CriticalError was removed because it can't trigger an assert at the callsite. Use 'checkf' instead.") 1 TSharedRef< FTokenizedMessage > CriticalError(const FText &InMessage
TSharedRef< FTokenizedMessage > Warning (const FText &InMessage=FText())
Static Public Member Functions
static const TCHAR *const GetLogColor (EMessageSeverity::Type InSeverity)
Helper function to retrieve a log color for a specified message severity.
static ELogVerbosity::Type GetLogVerbosity (EMessageSeverity::Type InSeverity)
Helper function to convert message log severity to log verbosity.
static FGetLog & OnGetLog ()
static FMessageSelectionChanged & OnMessageSelectionChanged ()
Private Attributes
bool bSuppressLoggingToOutputLog
Do we want to suppress logging to the output log in addition to the message log?
FName LogName
Name of this message log.
TSharedPtr< class IMessageLog > MessageLog
The message log we use for output.
TArray< TSharedRef< FTokenizedMessage > > Messages
Buffer for messages.
Static Private Attributes
static FGetLog GetLog
Delegate for retrieving the message log.
static FMessageSelectionChanged MessageSelectionChanged
Delegate for message selection.
Detailed Description
Definition at line 20 of file MessageLog.h.
Constructor & Destructor Documentation
FMessageLog()
FMessageLog::FMessageLog (const FName & InLogName)
Constructor.
Parameters
InLogName the name of the log to use
Referenced by SuppressLoggingToOutputLog().
~FMessageLog()
FMessageLog::~FMessageLog ()
Destructor When this object goes out of scope, its buffered messages will be flushed.
Member Function Documentation
AddMessage()
const TSharedRef< FTokenizedMessage > & FMessageLog::AddMessage (const TSharedRef< FTokenizedMessage > & InMessage)
Add a message to the log.
Parameters
InMessage The message to add
Returns
The message for chaining calls
AddMessages()
void FMessageLog::AddMessages (const TArray< TSharedRef< FTokenizedMessage > > & InMessages)
Add an array of messages to the message log.
Parameters
InMessages The messages to add
DECLARE_DELEGATE_OneParam()
FMessageLog::DECLARE_DELEGATE_OneParam (FMessageSelectionChanged , TArray< TSharedRef< FTokenizedMessage > > &)
Delegate used when message selection changes.
This is used to select object in the scene according to objects referenced in message tokens.
DECLARE_DELEGATE_RetVal_OneParam()
FMessageLog::DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< class IMessageLog > , FGetLog , const FName &)
Delegate to retrieve a log interface.
This allows systems that implement IMessageLog to receive messages.
References DECLARE_DELEGATE_RetVal_OneParam().
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
Error()
TSharedRef< FTokenizedMessage > FMessageLog::Error (const FText & InMessage = FText())
References Error().
Referenced by Error().
Flush()
void FMessageLog::Flush ()
Send the currently buffered messages to the log & clear the buffer.
GetLogColor()
const TCHAR *const FMessageLog::GetLogColor (EMessageSeverity::Type InSeverity) static
Helper function to retrieve a log color for a specified message severity.
GetLogVerbosity()
ELogVerbosity::Type FMessageLog::GetLogVerbosity (EMessageSeverity::Type InSeverity) static
Helper function to convert message log severity to log verbosity.
Info()
TSharedRef< FTokenizedMessage > FMessageLog::Info (const FText & InMessage = FText())
References Info().
Referenced by Info(), Notify(), NumMessages(), and Open().
Message()
TSharedRef< FTokenizedMessage > FMessageLog::Message (EMessageSeverity::Type InSeverity, const FText & InMessage = FText())
Helper functions to allow easy adding of messages to the log.
Each one will add a token for the severity (if valid) and the textual message (if any). Messages are buffered.
Parameters
InSeverity The severity of the message
InMessage The message to use
Returns
the message for chaining calls.
NewPage()
void FMessageLog::NewPage (const FText & InLabel)
Add a new page to the log.
Pages will not be created until messages are added to them, so we dont generate lots of empty pages. This call will cause a flush so that the logs state is properly reflected.
Parameters
InLabel The label for the page.
References NewPage().
Referenced by NewPage().
Notify()
void FMessageLog::Notify (const FText & InMessage = FText(), EMessageSeverity::Type InSeverityFilter = EMessageSeverity::Info, bool bForce = false)
Notify the user with a message if there are messages present.
This call will cause a flush so that the logs state is properly reflected.
Parameters
InMessage The notification message.
InSeverityFilter Only messages of higher severity than this filter will be considered when checking.
bForce Notify anyway, even if the filters gives us no messages.
References Info(), and Notify().
Referenced by Notify().
NumMessages()
int32 FMessageLog::NumMessages (EMessageSeverity::Type InSeverityFilter = EMessageSeverity::Info)
Check whether there are any messages present for this log.
If the log is paged, this will check if there are any messages on the current page. This call will cause a flush so that the logs state is properly reflected.
Parameters
InSeverityFilter Only messages of higher severity than this filter will be considered when checking.
Returns
The number of messages that pass our filter
References Info(), and NumMessages().
Referenced by NumMessages().
OnGetLog()
FGetLog & FMessageLog::OnGetLog () inline static
Definition at line 115 of file MessageLog.h.
References GetLog, and OnGetLog().
Referenced by OnGetLog().
OnMessageSelectionChanged()
FMessageSelectionChanged & FMessageLog::OnMessageSelectionChanged () inline static
Definition at line 122 of file MessageLog.h.
References MessageSelectionChanged.
Open()
void FMessageLog::Open (EMessageSeverity::Type InSeverityFilter = EMessageSeverity::Info, bool bOpenEvenIfEmpty = false)
Opens the log for display to the user given certain conditions.
This call will cause a flush so that the logs state is properly reflected.
Parameters
InSeverityFilter Only messages of higher severity than this filter will be considered when checking.
bOpenEvenIfEmpty Override the filter & log status & force the log to open.
References Info(), and Open().
Referenced by Open().
PerformanceWarning()
TSharedRef< FTokenizedMessage > FMessageLog::PerformanceWarning (const FText & InMessage = FText())
References PerformanceWarning().
Referenced by PerformanceWarning().
SetCurrentPage()
void FMessageLog::SetCurrentPage (const FText & InLabel)
Sets the current page to the one specified by the label.
This call will cause a flush so that the logs state is properly reflected.
Parameters
InLabel The label for the page.
References SetCurrentPage().
Referenced by SetCurrentPage().
SuppressLoggingToOutputLog()
FMessageLog & FMessageLog::SuppressLoggingToOutputLog (bool bShouldSuppress = true)
Should we mirror message log messages from this instance to the output log during flush?
References FMessageLog(), and SuppressLoggingToOutputLog().
Referenced by SuppressLoggingToOutputLog().
UE_DEPRECATED()
FMessageLog::UE_DEPRECATED (5. 1, "CriticalError was removed because it can't trigger an assert at the callsite. Use 'checkf' instead.") const &
Warning()
TSharedRef< FTokenizedMessage > FMessageLog::Warning (const FText & InMessage = FText())
References Warning().
Referenced by Warning().
Field Documentation
bSuppressLoggingToOutputLog
bool FMessageLog::bSuppressLoggingToOutputLog private
Do we want to suppress logging to the output log in addition to the message log?
Definition at line 141 of file MessageLog.h.
GetLog
FGetLog FMessageLog::GetLog static private
Delegate for retrieving the message log.
Definition at line 144 of file MessageLog.h.
Referenced by OnGetLog().
LogName
FName FMessageLog::LogName private
Name of this message log.
Definition at line 138 of file MessageLog.h.
MessageLog
TSharedPtr<class IMessageLog> FMessageLog::MessageLog private
The message log we use for output.
Definition at line 135 of file MessageLog.h.
Messages
TArray< TSharedRef<FTokenizedMessage> > FMessageLog::Messages private
Buffer for messages.
Definition at line 132 of file MessageLog.h.
MessageSelectionChanged
FMessageSelectionChanged FMessageLog::MessageSelectionChanged static private
Delegate for message selection.
Definition at line 147 of file MessageLog.h.
Referenced by OnMessageSelectionChanged().
The documentation for this class was generated from the following file:
MessageLog.h