Unreal Engine 5.6 C++ API: TAudioBuffer< DataType > Class Template Reference
TAudioBuffer< DataType > Class Template Reference
#include "AudioBuffer.h"
Public Member Functions
TAudioBuffer ()
TAudioBuffer (EAudioBufferChannelLayout InChannelLayout, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode)
TAudioBuffer (FAudioBufferConfig InConfig, EAudioBufferCleanupMode InCleanupMode)
TAudioBuffer (int32 InNumChannels, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode)
~TAudioBuffer ()
void Accumulate (const TAudioBuffer< DataType > &Other)
void Accumulate (DataType **Input, int32 InNumChannels, int32 InNumFrames)
void AdvanceAliasedDataPointers (int32 InNumFrames)
void Alias (const DataType *RawData, int32 InNumFrames, int32 InNumChannels, float SampleRate=0.0f, bool IsInterleaved=false)
void Alias (const TAudioBuffer< DataType > &Other, int32 InFrameOffset=0)
void AliasChannelDataPointers (const FAudioBufferConfig &NewValidConfig, DataType **DataPtrs)
void AliasChannelDataPointers (const TAudioBuffer< DataType > &Other, int32 InFirstChannel=0, int32 InNumChannels=MAX_int32)
void AssertEqualWithTolerance (const TAudioBuffer< DataType > &Other, DataType InTolerance) const
bool CheckIntegrity ()
void ComputeOverview (uint32 InFramesPerOverviewSample, TAudioBuffer< DataType > &OutOverviewMax, TAudioBuffer< DataType > &OutOverviewMin) const
void Configure (EAudioBufferChannelLayout InChannelLayout, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode, float InSampleRate=0.0f, bool InInterleaved=false)
void Configure (FAudioBufferConfig InConfig, EAudioBufferCleanupMode InCleanupMode)
void Configure (int32 InNumChannels, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode, float InSampleRate=0.0f, bool InInterleaved=false)
FORCEINLINE bool ContainsFrame (int32 InFrameNumber)
void Copy (const TAudioBuffer< DataType > &Other)
void Copy (const TAudioBuffer< DataType > &Other, float InGain, DataType InMin, DataType InMax)
void Copy (const TAudioBuffer< DataType > &Other, int32 InNumFrames, int32 InOffset)
void DebugLog (uint32 InChannel) const
void Deinterleave (const TAudioBuffer< DataType > &Other)
void Deinterleave (const TAudioBuffer< DataType > &Other, float InGain, DataType InMin, DataType InMax)
bool EqualWithTolerance (const TAudioBuffer< DataType > &Other, DataType InTolerance) const
bool EqualWithTolerance (int32 ThisChannelIdx, const TAudioBuffer< DataType > &Other, int32 OtherChannelIdx, DataType Tolerance) const
void Fill (DataType InValue)
void FillData (char InChr)
void FillValidFrames (char InChr)
void FillWithWhiteNoise (float InGain=1.0f)
fill the buffer with white noise this function only works for buffers of floats.
bool FindFirstDiff (const TAudioBuffer< DataType > &Other, int32 &OutChannelIndex, int32 &OutFrameIndex, DataType InTolerance) const
EAudioBufferChannelLayout GetChannelLayout () const
uint16 GetChannelMask () const
EAudioBufferCleanupMode GetCleanupMode () const
DataType ** GetData ()
int32 GetFirstFrame () const
int32 GetFreeableSize () const
bool GetIsInterleaved () const
bool GetIsSilent () const
size_t GetLastFrame () const
int32 GetLengthInFrames () const
const FAudioBufferConfig & GetMaxConfig () const
int32 GetMaxNumChannels () const
int32 GetMaxNumFrames () const
uint32 GetNumTotalValidSamples () const
int32 GetNumValidBytes () const
int32 GetNumValidChannels () const
int32 GetNumValidFrames () const
DataType GetPeak () const
DataType GetPeak (int32 ChannelIndex) const
DataType * GetRawChannelData (int32 ChanneIdx)
const DataType * GetRawChannelData (int32 ChanneIdx) const
TDynamicStridePtr< DataType > GetStridingChannelDataPointer (int32 InChannelIdx) const
const DataType * GetValidChannelData (int32 ChanneIdx) const
DataType * GetValidChannelData (int32 InChannelIndex)
FAudioBufferConfig GetValidConfig () const
void IncrementChannelDataPointers (int32 InIncrementSize)
void Initialize ()
void Interleave (const TAudioBuffer< DataType > &Other)
void Interleave (const TAudioBuffer< DataType > &Other, float InGain, DataType InMin, DataType InMax)
void MultiplyAccumulate (const TAudioBuffer< DataType > &Other, DataType InGain, DataType InGainDelta)
bool operator!= (const TAudioBuffer< DataType > &Other) const
TAudioBuffer< DataType > & operator*= (const TAudioBuffer< DataType > &Other)
bool operator== (const TAudioBuffer< DataType > &Other) const
DataType * operator[] (int32 Index)
void Reset ()
Clears the buffer and deletes the data if CleanupMode == EAudioBufferCleanupMode::Delete.
bool Saturate (DataType MinValue, DataType MaxValue)
bool SaturateWithNANCheck (DataType MinValue, DataType MaxValue)
void Scale (float InFactor)
void SetAliasedChannelData (DataType **InData, int32 InNumChannels)
void SetChannelData (int32 InChannelIndex, const DataType *InData)
void SetChannelLayout (EAudioBufferChannelLayout InChannelLayout)
void SetChannelMask (uint16 InMask)
void SetFirstFrame (int32 InFirstFrame)
void SetIsSilent (bool InIsSilent)
void SetLengthInFrames (int32 InLength)
void SetNumValidChannels (int32 InNumChannels)
void SetNumValidFrames (int32 InNumFrames)
void SetSampleRate (float InSampleRateHz)
void SwapEndianness ()
void ZeroData ()
void ZeroValidFrames ()
Static Public Member Functions
static int32 GetBytesPerSample ()
Private Member Functions
TAudioBuffer (const TAudioBuffer &Other)
void _AccumulateSIMD (DataType **InData, int32 InNumChannels, int32 InNumFrames)
FORCEINLINE void _AccumulateSIMD (float **InputData, int32 InNumChannels, int32 InNumFrames)
void _CopySIMD (const TAudioBuffer< DataType > &Other, float InGain, DataType InMin, DataType InMax)
FORCEINLINE void _CopySIMD (const TAudioBuffer< float > &Other, float InGain, float InMin, float InMax)
void _MultiplyAccumulateSIMD (const TAudioBuffer< DataType > &Other, DataType InGain, DataType InGainDelta)
FORCEINLINE void _MultiplyAccumulateSIMD (const TAudioBuffer< float > &Other, float InGain, float InGainDelta)
bool _SaturateSIMD (DataType InMinValue, DataType InMaxValue)
FORCEINLINE bool _SaturateSIMD (float InMinValue, float InMaxValue)
void _ScaleSIMD (float InFactor)
FORCEINLINE void _ScaleSIMD (float InFactor)
constexpr bool _UseSIMD ()
void operator= (const TAudioBuffer &Other)
Static Private Member Functions
static constexpr bool _UseSIMD ()
Private Attributes
EAudioBufferChannelLayout ChannelLayout
uint16 ChannelMask = 0xFFFF
EAudioBufferCleanupMode CleanupMode
int32 FirstFrame
bool IsSilent
int32 LastFrame
FAudioBufferConfig MaxConfig
DataType * MyData [FAudioBufferConfig::kMaxAudioBufferChannels]
int32 NumFrames
int32 NumValidChannels
int32 NumValidFrames
Static Private Attributes
static constexpr int32 kAudioBufferStompDetector = 0xFEEDF00D
Detailed Description
template<typename DataType>
class TAudioBuffer< DataType >
Definition at line 41 of file AudioBuffer.h.
Constructor & Destructor Documentation
TAudioBuffer() [1/5]
template<typename DataType> TAudioBuffer< DataType >::TAudioBuffer () inline
Definition at line 45 of file AudioBuffer.h.
References Initialize().
Referenced by TAudioBuffer(), _CopySIMD(), _MultiplyAccumulateSIMD(), Accumulate(), Alias(), AliasChannelDataPointers(), AssertEqualWithTolerance(), ComputeOverview(), Copy(), Copy(), Copy(), Deinterleave(), Deinterleave(), EqualWithTolerance(), EqualWithTolerance(), FindFirstDiff(), Interleave(), Interleave(), MultiplyAccumulate(), operator!=(), operator*=(), operator=(), and operator==().
TAudioBuffer() [2/5]
template<typename DataType> TAudioBuffer< DataType >::TAudioBuffer (FAudioBufferConfig InConfig, EAudioBufferCleanupMode InCleanupMode) inline
Definition at line 189 of file AudioBuffer.h.
References Configure(), and Initialize().
TAudioBuffer() [3/5]
template<typename DataType> TAudioBuffer< DataType >::TAudioBuffer (int32 InNumChannels, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode) inline
Definition at line 195 of file AudioBuffer.h.
References Configure(), and Initialize().
TAudioBuffer() [4/5]
template<typename DataType> TAudioBuffer< DataType >::TAudioBuffer (EAudioBufferChannelLayout InChannelLayout, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode) inline
Definition at line 201 of file AudioBuffer.h.
References Configure(), and Initialize().
~TAudioBuffer()
template<typename DataType> TAudioBuffer< DataType >::~TAudioBuffer () inline
Definition at line 207 of file AudioBuffer.h.
References Reset().
TAudioBuffer() [5/5]
template<typename DataType> TAudioBuffer< DataType >::TAudioBuffer (const TAudioBuffer< DataType > & Other) private
References TAudioBuffer(), and Other.
Member Function Documentation
_AccumulateSIMD() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::_AccumulateSIMD (DataType ** InData, int32 InNumChannels, int32 InNumFrames) inline private
Definition at line 1450 of file AudioBuffer.h.
Referenced by Accumulate().
_AccumulateSIMD() [2/2]
FORCEINLINE void TAudioBuffer< float >::_AccumulateSIMD (float ** InputData, int32 InNumChannels, int32 InNumFrames) private
Definition at line 1646 of file AudioBuffer.h.
_CopySIMD() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::_CopySIMD (const TAudioBuffer< DataType > & Other, float InGain, DataType InMin, DataType InMax) inline private
Definition at line 1447 of file AudioBuffer.h.
References TAudioBuffer(), and Other.
Referenced by Copy().
_CopySIMD() [2/2]
FORCEINLINE void TAudioBuffer< float >::_CopySIMD (const TAudioBuffer< float > & Other, float InGain, float InMin, float InMax) private
Definition at line 1600 of file AudioBuffer.h.
_MultiplyAccumulateSIMD() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::_MultiplyAccumulateSIMD (const TAudioBuffer< DataType > & Other, DataType InGain, DataType InGainDelta) inline private
Definition at line 1453 of file AudioBuffer.h.
References TAudioBuffer(), and Other.
Referenced by MultiplyAccumulate().
_MultiplyAccumulateSIMD() [2/2]
FORCEINLINE void TAudioBuffer< float >::_MultiplyAccumulateSIMD (const TAudioBuffer< float > & Other, float InGain, float InGainDelta) private
Definition at line 1669 of file AudioBuffer.h.
_SaturateSIMD() [1/2]
template<typename DataType> bool TAudioBuffer< DataType >::_SaturateSIMD (DataType InMinValue, DataType InMaxValue) inline private
Definition at line 1441 of file AudioBuffer.h.
Referenced by Saturate(), and SaturateWithNANCheck().
_SaturateSIMD() [2/2]
FORCEINLINE bool TAudioBuffer< float >::_SaturateSIMD (float InMinValue, float InMaxValue) private
Definition at line 1513 of file AudioBuffer.h.
_ScaleSIMD() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::_ScaleSIMD (float InFactor) inline private
Definition at line 1444 of file AudioBuffer.h.
Referenced by Scale().
_ScaleSIMD() [2/2]
FORCEINLINE void TAudioBuffer< float >::_ScaleSIMD (float InFactor) private
Definition at line 1582 of file AudioBuffer.h.
_UseSIMD() [1/2]
template<typename DataType> constexpr bool TAudioBuffer< DataType >::_UseSIMD () inline static constexpr private
Definition at line 1439 of file AudioBuffer.h.
Referenced by Accumulate(), Copy(), MultiplyAccumulate(), Saturate(), SaturateWithNANCheck(), and Scale().
_UseSIMD() [2/2]
bool TAudioBuffer< float >::_UseSIMD () constexpr private
Definition at line 1507 of file AudioBuffer.h.
Accumulate() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::Accumulate (const TAudioBuffer< DataType > & Other) inline
Definition at line 1232 of file AudioBuffer.h.
References TAudioBuffer(), checkSlow, Delete, GetCleanupMode(), GetIsInterleaved(), GetNumValidChannels(), GetNumValidFrames(), GetValidChannelData(), Other, and SetIsSilent().
Accumulate() [2/2]
template<typename DataType> void TAudioBuffer< DataType >::Accumulate (DataType ** Input, int32 InNumChannels, int32 InNumFrames) inline
Definition at line 1304 of file AudioBuffer.h.
References _AccumulateSIMD(), _UseSIMD(), checkSlow, GetIsInterleaved(), GetNumValidChannels(), GetNumValidFrames(), GetValidChannelData(), Input, and SetIsSilent().
AdvanceAliasedDataPointers()
template<typename DataType> void TAudioBuffer< DataType >::AdvanceAliasedDataPointers (int32 InNumFrames) inline
Definition at line 617 of file AudioBuffer.h.
References check, GetNumValidChannels(), GetNumValidFrames(), MaxConfig, MyData, NumValidChannels, NumValidFrames, and SetNumValidFrames().
Referenced by Alias().
Alias() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::Alias (const DataType * RawData, int32 InNumFrames, int32 InNumChannels, float SampleRate = 0.0f, bool IsInterleaved = false) inline
Definition at line 687 of file AudioBuffer.h.
References Configure(), DontDelete, GetNumValidChannels(), GetNumValidFrames(), MyData, and RawData.
Alias() [2/2]
template<typename DataType> void TAudioBuffer< DataType >::Alias (const TAudioBuffer< DataType > & Other, int32 InFrameOffset = 0) inline
Definition at line 677 of file AudioBuffer.h.
References TAudioBuffer(), AdvanceAliasedDataPointers(), AliasChannelDataPointers(), Configure(), DontDelete, and Other.
AliasChannelDataPointers() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::AliasChannelDataPointers (const FAudioBufferConfig & NewValidConfig, DataType ** DataPtrs) inline
Definition at line 721 of file AudioBuffer.h.
References check, CleanupMode, Configure(), DontDelete, GetMaxNumChannels(), GetMaxNumFrames(), FAudioBufferConfig::GetNumChannels(), FAudioBufferConfig::GetNumFrames(), NumValidChannels, SetChannelData(), SetNumValidChannels(), and SetNumValidFrames().
AliasChannelDataPointers() [2/2]
template<typename DataType> void TAudioBuffer< DataType >::AliasChannelDataPointers (const TAudioBuffer< DataType > & Other, int32 InFirstChannel = 0, int32 InNumChannels = MAX_int32) inline
Definition at line 700 of file AudioBuffer.h.
References TAudioBuffer(), check, MAX_int32, MaxConfig, Other, SetChannelData(), and SetNumValidChannels().
Referenced by Alias().
AssertEqualWithTolerance()
template<typename DataType> void TAudioBuffer< DataType >::AssertEqualWithTolerance (const TAudioBuffer< DataType > & Other, DataType InTolerance) const inline
Definition at line 974 of file AudioBuffer.h.
References TAudioBuffer(), check, HarmonixDsp::FAudioBuffer::DebugLog(), Error, FindFirstDiff(), GetNumValidFrames(), GetValidChannelData(), FMath::Min, Other, TEXT, and UE_LOG.
CheckIntegrity()
template<typename DataType> bool TAudioBuffer< DataType >::CheckIntegrity () inline
Definition at line 176 of file AudioBuffer.h.
References check, CleanupMode, Delete, kAudioBufferStompDetector, MaxConfig, MyData, and Num.
ComputeOverview()
template<typename DataType> void TAudioBuffer< DataType >::ComputeOverview (uint32 InFramesPerOverviewSample, TAudioBuffer< DataType > & OutOverviewMax, TAudioBuffer< DataType > & OutOverviewMin) const inline
Definition at line 402 of file AudioBuffer.h.
References TAudioBuffer(), check, GetNumValidChannels(), GetNumValidFrames(), GetValidChannelData(), MaxConfig, FMath::Min, and ZeroData().
Configure() [1/3]
template<typename DataType> void TAudioBuffer< DataType >::Configure (EAudioBufferChannelLayout InChannelLayout, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode, float InSampleRate = 0.0f, bool InInterleaved = false) inline
Definition at line 96 of file AudioBuffer.h.
References Configure().
Configure() [2/3]
template<typename DataType> void TAudioBuffer< DataType >::Configure (FAudioBufferConfig InConfig, EAudioBufferCleanupMode InCleanupMode) inline
Definition at line 101 of file AudioBuffer.h.
References ChannelLayout, check, CleanupMode, Delete, FAudioBufferConfig::GetChannelLayout(), FAudioBufferConfig::GetNumChannels(), FAudioBufferConfig::GetNumFrames(), kAudioBufferStompDetector, FAudioBufferConfig::kMaxAudioBufferChannels, LLM_SCOPE_BYTAG, MAX_int32, MaxConfig, MyData, NumValidChannels, NumValidFrames, Reset(), SetFirstFrame(), SetIsSilent(), and SetLengthInFrames().
Configure() [3/3]
template<typename DataType> void TAudioBuffer< DataType >::Configure (int32 InNumChannels, int32 InNumFrames, EAudioBufferCleanupMode InCleanupMode, float InSampleRate = 0.0f, bool InInterleaved = false) inline
Definition at line 91 of file AudioBuffer.h.
References Configure().
Referenced by TAudioBuffer(), TAudioBuffer(), TAudioBuffer(), Alias(), Alias(), AliasChannelDataPointers(), Configure(), and Configure().
ContainsFrame()
template<typename DataType> FORCEINLINE bool TAudioBuffer< DataType >::ContainsFrame (int32 InFrameNumber) inline
Definition at line 258 of file AudioBuffer.h.
References FORCEINLINE, GetFirstFrame(), and GetLastFrame().
Copy() [1/3]
template<typename DataType> void TAudioBuffer< DataType >::Copy (const TAudioBuffer< DataType > & Other) inline
Definition at line 1042 of file AudioBuffer.h.
References TAudioBuffer(), Deinterleave(), Delete, GetCleanupMode(), GetIsInterleaved(), GetMaxNumFrames(), GetNumValidChannels(), GetValidChannelData(), Interleave(), FMemory::Memcpy(), FMemory::Memset(), FMath::Min, MyData, Other, SetIsSilent(), and SetNumValidFrames().
Copy() [2/3]
template<typename DataType> void TAudioBuffer< DataType >::Copy (const TAudioBuffer< DataType > & Other, float InGain, DataType InMin, DataType InMax) inline
Definition at line 1169 of file AudioBuffer.h.
References TAudioBuffer(), _CopySIMD(), _UseSIMD(), check, Deinterleave(), Delete, GetCleanupMode(), GetIsInterleaved(), GetNumValidChannels(), GetNumValidFrames(), Interleave(), MyData, and Other.
Copy() [3/3]
template<typename DataType> void TAudioBuffer< DataType >::Copy (const TAudioBuffer< DataType > & Other, int32 InNumFrames, int32 InOffset) inline
Definition at line 1115 of file AudioBuffer.h.
References TAudioBuffer(), check, GetIsInterleaved(), GetMaxNumFrames(), GetNumValidChannels(), GetValidChannelData(), FMemory::Memcpy(), FMemory::Memset(), MyData, Other, SetIsSilent(), and SetNumValidFrames().
DebugLog()
template<typename DataType> void TAudioBuffer< DataType >::DebugLog (uint32 InChannel) const inline
Definition at line 1431 of file AudioBuffer.h.
References HarmonixDsp::FAudioBuffer::DebugLog(), GetNumValidFrames(), and GetValidChannelData().
Deinterleave() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::Deinterleave (const TAudioBuffer< DataType > & Other) inline
Definition at line 800 of file AudioBuffer.h.
References TAudioBuffer(), check, GetMaxNumFrames(), GetNumValidChannels(), GetNumValidFrames(), FMemory::Memset(), FMath::Min, MyData, Other, SetIsSilent(), and SetNumValidFrames().
Referenced by Copy(), and Copy().
Deinterleave() [2/2]
template<typename DataType> void TAudioBuffer< DataType >::Deinterleave (const TAudioBuffer< DataType > & Other, float InGain, DataType InMin, DataType InMax) inline
Definition at line 827 of file AudioBuffer.h.
References TAudioBuffer(), check, GetMaxNumFrames(), GetNumValidChannels(), MyData, Other, SetIsSilent(), and SetNumValidFrames().
EqualWithTolerance() [1/2]
template<typename DataType> bool TAudioBuffer< DataType >::EqualWithTolerance (const TAudioBuffer< DataType > & Other, DataType InTolerance) const inline
Definition at line 959 of file AudioBuffer.h.
References TAudioBuffer(), FindFirstDiff(), GetNumValidChannels(), GetNumValidFrames(), and Other.
EqualWithTolerance() [2/2]
template<typename DataType> bool TAudioBuffer< DataType >::EqualWithTolerance (int32 ThisChannelIdx, const TAudioBuffer< DataType > & Other, int32 OtherChannelIdx, DataType Tolerance) const inline
Definition at line 900 of file AudioBuffer.h.
References TAudioBuffer(), GetNumValidChannels(), GetNumValidFrames(), GetStridingChannelDataPointer(), and Other.
Referenced by operator==().
Fill()
template<typename DataType> void TAudioBuffer< DataType >::Fill (DataType InValue) inline
Definition at line 300 of file AudioBuffer.h.
References GetIsInterleaved(), GetNumValidChannels(), GetNumValidFrames(), and GetValidChannelData().
FillData()
template<typename DataType> void TAudioBuffer< DataType >::FillData (char InChr) inline
Definition at line 323 of file AudioBuffer.h.
References CleanupMode, Delete, GetNumValidChannels(), MaxConfig, FMemory::Memset(), and MyData.
Referenced by ZeroData(), and ZeroValidFrames().
FillValidFrames()
template<typename DataType> void TAudioBuffer< DataType >::FillValidFrames (char InChr) inline
Definition at line 285 of file AudioBuffer.h.
References GetIsInterleaved(), GetNumValidChannels(), FMemory::Memset(), MyData, and NumValidFrames.
Referenced by ZeroValidFrames().
FillWithWhiteNoise()
template<typename DataType> void TAudioBuffer< DataType >::FillWithWhiteNoise (float InGain = 1.0f) inline
fill the buffer with white noise this function only works for buffers of floats.
Parameters
InGain (optional) the InGain to apply to the white noise. defaults to 1 (0 dBFS).
Returns
description of the return type
Definition at line 344 of file AudioBuffer.h.
References HarmonixDsp::GenerateWhiteNoiseEq(), GetNumValidChannels(), GetNumValidFrames(), and MyData.
FindFirstDiff()
template<typename DataType> bool TAudioBuffer< DataType >::FindFirstDiff (const TAudioBuffer< DataType > & Other, int32 & OutChannelIndex, int32 & OutFrameIndex, DataType InTolerance) const inline
Definition at line 929 of file AudioBuffer.h.
References TAudioBuffer(), check, GetNumValidChannels(), GetNumValidFrames(), GetValidChannelData(), and Other.
Referenced by AssertEqualWithTolerance(), and EqualWithTolerance().
GetBytesPerSample()
template<typename DataType> int32 TAudioBuffer< DataType >::GetBytesPerSample () inline static
Definition at line 232 of file AudioBuffer.h.
GetChannelLayout()
template<typename DataType> EAudioBufferChannelLayout TAudioBuffer< DataType >::GetChannelLayout () const inline
Definition at line 774 of file AudioBuffer.h.
References ChannelLayout.
Referenced by FGainMatrix::Configure(), FGainMatrix::ConfigureForOutputBuffer(), and GetValidConfig().
GetChannelMask()
template<typename DataType> uint16 TAudioBuffer< DataType >::GetChannelMask () const inline
Definition at line 780 of file AudioBuffer.h.
References ChannelMask.
Referenced by FGainMatrix::Configure(), and FGainMatrix::ConfigureForOutputBuffer().
GetCleanupMode()
template<typename DataType> EAudioBufferCleanupMode TAudioBuffer< DataType >::GetCleanupMode () const inline
Definition at line 256 of file AudioBuffer.h.
References CleanupMode.
Referenced by Accumulate(), Copy(), and Copy().
GetData()
template<typename DataType> DataType ** TAudioBuffer< DataType >::GetData () inline
Definition at line 756 of file AudioBuffer.h.
References MyData.
GetFirstFrame()
template<typename DataType> int32 TAudioBuffer< DataType >::GetFirstFrame () const inline
Definition at line 238 of file AudioBuffer.h.
References FirstFrame.
Referenced by ContainsFrame().
GetFreeableSize()
template<typename DataType> int32 TAudioBuffer< DataType >::GetFreeableSize () const inline
Definition at line 217 of file AudioBuffer.h.
References CleanupMode, DontDelete, and MaxConfig.
GetIsInterleaved()
template<typename DataType> bool TAudioBuffer< DataType >::GetIsInterleaved () const inline
Definition at line 215 of file AudioBuffer.h.
References MaxConfig.
Referenced by Accumulate(), Accumulate(), Copy(), Copy(), Copy(), Fill(), FillValidFrames(), Interleave(), Interleave(), MultiplyAccumulate(), operator*=(), Saturate(), SaturateWithNANCheck(), and Scale().
GetIsSilent()
template<typename DataType> bool TAudioBuffer< DataType >::GetIsSilent () const inline
Definition at line 212 of file AudioBuffer.h.
References IsSilent.
GetLastFrame()
template<typename DataType> size_t TAudioBuffer< DataType >::GetLastFrame () const inline
Definition at line 254 of file AudioBuffer.h.
References LastFrame.
Referenced by ContainsFrame().
GetLengthInFrames()
template<typename DataType> int32 TAudioBuffer< DataType >::GetLengthInFrames () const inline
Definition at line 247 of file AudioBuffer.h.
References NumFrames.
GetMaxConfig()
template<typename DataType> const FAudioBufferConfig & TAudioBuffer< DataType >::GetMaxConfig () const inline
Definition at line 757 of file AudioBuffer.h.
References MaxConfig.
GetMaxNumChannels()
template<typename DataType> int32 TAudioBuffer< DataType >::GetMaxNumChannels () const inline
Definition at line 764 of file AudioBuffer.h.
References MaxConfig.
Referenced by AliasChannelDataPointers(), GetRawChannelData(), GetRawChannelData(), and SetChannelData().
GetMaxNumFrames()
template<typename DataType> int32 TAudioBuffer< DataType >::GetMaxNumFrames () const inline
Definition at line 765 of file AudioBuffer.h.
References MaxConfig.
Referenced by AliasChannelDataPointers(), Copy(), Copy(), Deinterleave(), Deinterleave(), Interleave(), and Interleave().
GetNumTotalValidSamples()
template<typename DataType> uint32 TAudioBuffer< DataType >::GetNumTotalValidSamples () const inline
Definition at line 793 of file AudioBuffer.h.
References GetNumValidChannels(), and GetNumValidFrames().
GetNumValidBytes()
template<typename DataType> int32 TAudioBuffer< DataType >::GetNumValidBytes () const inline
Definition at line 227 of file AudioBuffer.h.
References GetNumValidChannels(), and GetNumValidFrames().
GetNumValidChannels()
template<typename DataType> int32 TAudioBuffer< DataType >::GetNumValidChannels () const inline
Definition at line 767 of file AudioBuffer.h.
References NumValidChannels.
Referenced by Accumulate(), Accumulate(), AdvanceAliasedDataPointers(), Alias(), ComputeOverview(), FGainMatrix::Configure(), FGainMatrix::ConfigureForOutputBuffer(), Copy(), Copy(), Copy(), Deinterleave(), Deinterleave(), EqualWithTolerance(), EqualWithTolerance(), Fill(), FillData(), FillValidFrames(), FillWithWhiteNoise(), FindFirstDiff(), GetNumTotalValidSamples(), GetNumValidBytes(), GetPeak(), GetValidChannelData(), GetValidChannelData(), GetValidConfig(), IncrementChannelDataPointers(), Interleave(), Interleave(), MultiplyAccumulate(), operator*=(), and operator[]().
GetNumValidFrames()
template<typename DataType> int32 TAudioBuffer< DataType >::GetNumValidFrames () const inline
Definition at line 786 of file AudioBuffer.h.
References NumValidFrames.
Referenced by Accumulate(), Accumulate(), AdvanceAliasedDataPointers(), Alias(), AssertEqualWithTolerance(), ComputeOverview(), Copy(), DebugLog(), Deinterleave(), EqualWithTolerance(), EqualWithTolerance(), Fill(), FillWithWhiteNoise(), FindFirstDiff(), GetNumTotalValidSamples(), GetNumValidBytes(), GetValidConfig(), MultiplyAccumulate(), and operator*=().
GetPeak() [1/2]
template<typename DataType> DataType TAudioBuffer< DataType >::GetPeak () const inline
Definition at line 388 of file AudioBuffer.h.
References GetPeak(), and NumValidChannels.
Referenced by GetPeak().
GetPeak() [2/2]
template<typename DataType> DataType TAudioBuffer< DataType >::GetPeak (int32 ChannelIndex) const inline
Definition at line 353 of file AudioBuffer.h.
References check, GetNumValidChannels(), MaxConfig, MyData, NumValidChannels, and NumValidFrames.
GetRawChannelData() [1/2]
template<typename DataType> DataType * TAudioBuffer< DataType >::GetRawChannelData (int32 ChanneIdx) inline
Definition at line 649 of file AudioBuffer.h.
References check, GetMaxNumChannels(), MaxConfig, and MyData.
Referenced by operator*=().
GetRawChannelData() [2/2]
template<typename DataType> const DataType * TAudioBuffer< DataType >::GetRawChannelData (int32 ChanneIdx) const inline
Definition at line 657 of file AudioBuffer.h.
References check, GetMaxNumChannels(), MaxConfig, and MyData.
GetStridingChannelDataPointer()
template<typename DataType> TDynamicStridePtr< DataType > TAudioBuffer< DataType >::GetStridingChannelDataPointer (int32 InChannelIdx) const inline
Definition at line 664 of file AudioBuffer.h.
References MaxConfig, and MyData.
Referenced by EqualWithTolerance().
GetValidChannelData() [1/2]
template<typename DataType> const DataType * TAudioBuffer< DataType >::GetValidChannelData (int32 ChanneIdx) const inline
Definition at line 642 of file AudioBuffer.h.
References check, GetNumValidChannels(), MaxConfig, and MyData.
GetValidChannelData() [2/2]
template<typename DataType> DataType * TAudioBuffer< DataType >::GetValidChannelData (int32 InChannelIndex) inline
Definition at line 634 of file AudioBuffer.h.
References check, GetNumValidChannels(), MaxConfig, and MyData.
Referenced by Accumulate(), Accumulate(), AssertEqualWithTolerance(), ComputeOverview(), Copy(), Copy(), DebugLog(), Fill(), FindFirstDiff(), and MultiplyAccumulate().
GetValidConfig()
template<typename DataType> FAudioBufferConfig TAudioBuffer< DataType >::GetValidConfig () const inline
Definition at line 759 of file AudioBuffer.h.
References GetChannelLayout(), GetNumValidChannels(), GetNumValidFrames(), and MaxConfig.
IncrementChannelDataPointers()
template<typename DataType> void TAudioBuffer< DataType >::IncrementChannelDataPointers (int32 InIncrementSize) inline
Definition at line 741 of file AudioBuffer.h.
References check, CleanupMode, DontDelete, GetNumValidChannels(), MaxConfig, and MyData.
Initialize()
template<typename DataType> void TAudioBuffer< DataType >::Initialize () inline
Definition at line 50 of file AudioBuffer.h.
References ChannelLayout, CleanupMode, DontDelete, FirstFrame, IsSilent, FAudioBufferConfig::kMaxAudioBufferChannels, LastFrame, MaxConfig, MyData, NumFrames, NumValidChannels, NumValidFrames, and UnsupportedFormat.
Referenced by TAudioBuffer(), TAudioBuffer(), TAudioBuffer(), TAudioBuffer(), and Reset().
Interleave() [1/2]
template<typename DataType> void TAudioBuffer< DataType >::Interleave (const TAudioBuffer< DataType > & Other) inline
Definition at line 851 of file AudioBuffer.h.
References TAudioBuffer(), check, GetIsInterleaved(), GetMaxNumFrames(), GetNumValidChannels(), FMath::Min, MyData, Other, SetIsSilent(), and SetNumValidFrames().
Referenced by Copy(), and Copy().
Interleave() [2/2]
template<typename DataType> void TAudioBuffer< DataType >::Interleave (const TAudioBuffer< DataType > & Other, float InGain, DataType InMin, DataType InMax) inline
Definition at line 877 of file AudioBuffer.h.
References TAudioBuffer(), checkSlow, GetIsInterleaved(), GetMaxNumFrames(), GetNumValidChannels(), MyData, Other, SetIsSilent(), and SetNumValidFrames().
MultiplyAccumulate()
template<typename DataType> void TAudioBuffer< DataType >::MultiplyAccumulate (const TAudioBuffer< DataType > & Other, DataType InGain, DataType InGainDelta) inline
Definition at line 1351 of file AudioBuffer.h.
References TAudioBuffer(), _MultiplyAccumulateSIMD(), _UseSIMD(), checkSlow, GetIsInterleaved(), GetNumValidChannels(), GetNumValidFrames(), GetValidChannelData(), Other, and SetIsSilent().
operator!=()
template<typename DataType> bool TAudioBuffer< DataType >::operator!= (const TAudioBuffer< DataType > & Other) const inline
Definition at line 1005 of file AudioBuffer.h.
References TAudioBuffer(), and Other.
operator*=()
template<typename DataType> TAudioBuffer< DataType > & TAudioBuffer< DataType >::operator*= (const TAudioBuffer< DataType > & Other) inline
Definition at line 1010 of file AudioBuffer.h.
References TAudioBuffer(), check, GetIsInterleaved(), GetNumValidChannels(), GetNumValidFrames(), GetRawChannelData(), Other, and RawData.
operator=()
template<typename DataType> void TAudioBuffer< DataType >::operator= (const TAudioBuffer< DataType > & Other) private
References TAudioBuffer(), and Other.
operator==()
template<typename DataType> bool TAudioBuffer< DataType >::operator== (const TAudioBuffer< DataType > & Other) const inline
Definition at line 1000 of file AudioBuffer.h.
References TAudioBuffer(), EqualWithTolerance(), and Other.
operator[]()
template<typename DataType> DataType * TAudioBuffer< DataType >::operator[] (int32 Index) inline
Definition at line 1226 of file AudioBuffer.h.
References GetNumValidChannels(), and MyData.
Reset()
template<typename DataType> void TAudioBuffer< DataType >::Reset () inline
Clears the buffer and deletes the data if CleanupMode == EAudioBufferCleanupMode::Delete.
Definition at line 71 of file AudioBuffer.h.
References check, CleanupMode, Delete, FMemory::Free(), Initialize(), and MyData.
Referenced by ~TAudioBuffer(), and Configure().
Saturate()
template<typename DataType> bool TAudioBuffer< DataType >::Saturate (DataType MinValue, DataType MaxValue) inline
Definition at line 467 of file AudioBuffer.h.
References _SaturateSIMD(), _UseSIMD(), GetIsInterleaved(), MyData, NumValidChannels, and NumValidFrames.
SaturateWithNANCheck()
template<typename DataType> bool TAudioBuffer< DataType >::SaturateWithNANCheck (DataType MinValue, DataType MaxValue) inline
Definition at line 517 of file AudioBuffer.h.
References _SaturateSIMD(), _UseSIMD(), GetIsInterleaved(), FGenericPlatformMath::IsNaN(), MyData, NumValidChannels, and NumValidFrames.
Scale()
template<typename DataType> void TAudioBuffer< DataType >::Scale (float InFactor) inline
Definition at line 577 of file AudioBuffer.h.
References _ScaleSIMD(), _UseSIMD(), check, GetIsInterleaved(), MyData, NumValidChannels, and NumValidFrames.
SetAliasedChannelData()
template<typename DataType> void TAudioBuffer< DataType >::SetAliasedChannelData (DataType ** InData, int32 InNumChannels) inline
Definition at line 610 of file AudioBuffer.h.
References MyData, and SetNumValidChannels().
SetChannelData()
template<typename DataType> void TAudioBuffer< DataType >::SetChannelData (int32 InChannelIndex, const DataType * InData) inline
Definition at line 598 of file AudioBuffer.h.
References check, CleanupMode, DontDelete, GetMaxNumChannels(), MaxConfig, and MyData.
Referenced by AliasChannelDataPointers(), and AliasChannelDataPointers().
SetChannelLayout()
template<typename DataType> void TAudioBuffer< DataType >::SetChannelLayout (EAudioBufferChannelLayout InChannelLayout) inline
Definition at line 775 of file AudioBuffer.h.
References ChannelLayout.
SetChannelMask()
template<typename DataType> void TAudioBuffer< DataType >::SetChannelMask (uint16 InMask) inline
Definition at line 781 of file AudioBuffer.h.
References ChannelMask.
SetFirstFrame()
template<typename DataType> void TAudioBuffer< DataType >::SetFirstFrame (int32 InFirstFrame) inline
Definition at line 239 of file AudioBuffer.h.
References FirstFrame, LastFrame, and NumFrames.
Referenced by Configure().
SetIsSilent()
template<typename DataType> void TAudioBuffer< DataType >::SetIsSilent (bool InIsSilent) inline
Definition at line 213 of file AudioBuffer.h.
References IsSilent.
Referenced by Accumulate(), Accumulate(), Configure(), Copy(), Copy(), Deinterleave(), Deinterleave(), Interleave(), Interleave(), MultiplyAccumulate(), ZeroData(), and ZeroValidFrames().
SetLengthInFrames()
template<typename DataType> void TAudioBuffer< DataType >::SetLengthInFrames (int32 InLength) inline
Definition at line 248 of file AudioBuffer.h.
References FirstFrame, LastFrame, and NumFrames.
Referenced by Configure().
SetNumValidChannels()
template<typename DataType> void TAudioBuffer< DataType >::SetNumValidChannels (int32 InNumChannels) inline
Definition at line 768 of file AudioBuffer.h.
References check, FAudioBufferConfig::kMaxAudioBufferChannels, and NumValidChannels.
Referenced by AliasChannelDataPointers(), AliasChannelDataPointers(), and SetAliasedChannelData().
SetNumValidFrames()
template<typename DataType> void TAudioBuffer< DataType >::SetNumValidFrames (int32 InNumFrames) inline
Definition at line 787 of file AudioBuffer.h.
References check, MaxConfig, and NumValidFrames.
Referenced by AdvanceAliasedDataPointers(), AliasChannelDataPointers(), Copy(), Copy(), Deinterleave(), Deinterleave(), Interleave(), and Interleave().
SetSampleRate()
template<typename DataType> void TAudioBuffer< DataType >::SetSampleRate (float InSampleRateHz) inline
Definition at line 171 of file AudioBuffer.h.
References MaxConfig.
SwapEndianness()
template<typename DataType> void TAudioBuffer< DataType >::SwapEndianness () inline
Definition at line 443 of file AudioBuffer.h.
References CleanupMode, Delete, MaxConfig, MyData, NumValidChannels, and NumValidFrames.
ZeroData()
template<typename DataType> void TAudioBuffer< DataType >::ZeroData () inline
Definition at line 279 of file AudioBuffer.h.
References FillData(), and SetIsSilent().
Referenced by ComputeOverview().
ZeroValidFrames()
template<typename DataType> void TAudioBuffer< DataType >::ZeroValidFrames () inline
Definition at line 263 of file AudioBuffer.h.
References FillData(), FillValidFrames(), MaxConfig, NumValidFrames, and SetIsSilent().
Field Documentation
ChannelLayout
template<typename DataType> EAudioBufferChannelLayout TAudioBuffer< DataType >::ChannelLayout private
Definition at line 1462 of file AudioBuffer.h.
Referenced by Configure(), GetChannelLayout(), Initialize(), and SetChannelLayout().
ChannelMask
template<typename DataType> uint16 TAudioBuffer< DataType >::ChannelMask = 0xFFFF private
Definition at line 1464 of file AudioBuffer.h.
Referenced by GetChannelMask(), and SetChannelMask().
CleanupMode
template<typename DataType> EAudioBufferCleanupMode TAudioBuffer< DataType >::CleanupMode private
Definition at line 1455 of file AudioBuffer.h.
Referenced by AliasChannelDataPointers(), CheckIntegrity(), Configure(), FillData(), GetCleanupMode(), GetFreeableSize(), IncrementChannelDataPointers(), Initialize(), Reset(), SetChannelData(), and SwapEndianness().
FirstFrame
template<typename DataType> int32 TAudioBuffer< DataType >::FirstFrame private
Definition at line 1467 of file AudioBuffer.h.
Referenced by GetFirstFrame(), Initialize(), SetFirstFrame(), and SetLengthInFrames().
IsSilent
template<typename DataType> bool TAudioBuffer< DataType >::IsSilent private
Definition at line 1471 of file AudioBuffer.h.
Referenced by GetIsSilent(), Initialize(), and SetIsSilent().
kAudioBufferStompDetector
template<typename DataType> int32 TAudioBuffer< DataType >::kAudioBufferStompDetector = 0xFEEDF00D static constexpr private
Definition at line 1473 of file AudioBuffer.h.
Referenced by CheckIntegrity(), and Configure().
LastFrame
template<typename DataType> int32 TAudioBuffer< DataType >::LastFrame private
Definition at line 1469 of file AudioBuffer.h.
Referenced by GetLastFrame(), Initialize(), SetFirstFrame(), and SetLengthInFrames().
MaxConfig
template<typename DataType> FAudioBufferConfig TAudioBuffer< DataType >::MaxConfig private
Definition at line 1458 of file AudioBuffer.h.
Referenced by AdvanceAliasedDataPointers(), AliasChannelDataPointers(), CheckIntegrity(), ComputeOverview(), Configure(), FillData(), GetFreeableSize(), GetIsInterleaved(), GetMaxConfig(), GetMaxNumChannels(), GetMaxNumFrames(), GetPeak(), GetRawChannelData(), GetRawChannelData(), GetStridingChannelDataPointer(), GetValidChannelData(), GetValidChannelData(), GetValidConfig(), IncrementChannelDataPointers(), Initialize(), SetChannelData(), SetNumValidFrames(), SetSampleRate(), SwapEndianness(), and ZeroValidFrames().
MyData
template<typename DataType> DataType* TAudioBuffer< DataType >::MyData[FAudioBufferConfig::kMaxAudioBufferChannels] private
Definition at line 1456 of file AudioBuffer.h.
Referenced by AdvanceAliasedDataPointers(), Alias(), CheckIntegrity(), Configure(), Copy(), Copy(), Copy(), Deinterleave(), Deinterleave(), FillData(), FillValidFrames(), FillWithWhiteNoise(), GetData(), GetPeak(), GetRawChannelData(), GetRawChannelData(), GetStridingChannelDataPointer(), GetValidChannelData(), GetValidChannelData(), IncrementChannelDataPointers(), Initialize(), Interleave(), Interleave(), operator[](), Reset(), Saturate(), SaturateWithNANCheck(), Scale(), SetAliasedChannelData(), SetChannelData(), and SwapEndianness().
NumFrames
template<typename DataType> int32 TAudioBuffer< DataType >::NumFrames private
Definition at line 1468 of file AudioBuffer.h.
Referenced by GetLengthInFrames(), Initialize(), SetFirstFrame(), and SetLengthInFrames().
NumValidChannels
template<typename DataType> int32 TAudioBuffer< DataType >::NumValidChannels private
Definition at line 1461 of file AudioBuffer.h.
Referenced by AdvanceAliasedDataPointers(), AliasChannelDataPointers(), Configure(), GetNumValidChannels(), GetPeak(), GetPeak(), Initialize(), Saturate(), SaturateWithNANCheck(), Scale(), SetNumValidChannels(), and SwapEndianness().
NumValidFrames
template<typename DataType> int32 TAudioBuffer< DataType >::NumValidFrames private
Definition at line 1463 of file AudioBuffer.h.
Referenced by AdvanceAliasedDataPointers(), Configure(), FillValidFrames(), GetNumValidFrames(), GetPeak(), Initialize(), Saturate(), SaturateWithNANCheck(), Scale(), SetNumValidFrames(), SwapEndianness(), and ZeroValidFrames().
The documentation for this class was generated from the following file:
AudioBuffer.h