Unreal Engine 5.6 C++ API: FRK4SpringInterpolator< T > Struct Template Reference
FRK4SpringInterpolator< T > Struct Template Reference
#include "SpringInterpolator.h"
Public Member Functions
FRK4SpringInterpolator (float InSpringStiffness=1.f, float InDampeningRatio=1.f)
float GetDefaultStiffnessConstant () const
T GetLastDeltaPosition () const
T GetPosition () const
T GetVelocity () const
bool IsInMotion () const
bool IsPositionEqualTo (const T &OtherPosition) const
bool IsVelocityZero () const
void OffsetPosition (const T &Offset)
void OffsetVelocity (const T &Offset)
void Reset (const T &DefaultPosition=T(0.f))
void SetDefaultSpringConstants (const float &InSpringStiffness, const float &InDampeningRatio=1.f)
void SetPosition (const T &NewPosition)
void SetSpringConstants (const float &InSpringStiffness, const float &InDampeningRatio=1.f)
void SetVelocity (const T &NewVelocity)
T Update (const T &InNewPosition, const T &InTargetPosition, const float &InDeltaTime)
T Update (const T &InTargetPosition, const float &InDeltaTime)
Protected Attributes
bool bIsInitialized
bool bIsInMotion
float DampeningRatio
T LastPosition
FRK4SpringConstants SpringConstants
RK4Integrator::FRK4State< T > State
float StiffnessConstant
float TimeRemaining
Detailed Description
template<typename T>
struct FRK4SpringInterpolator< T >
Definition at line 133 of file SpringInterpolator.h.
Constructor & Destructor Documentation
FRK4SpringInterpolator()
template<typename T> FRK4SpringInterpolator< T >::FRK4SpringInterpolator (float InSpringStiffness = 1.f, float InDampeningRatio = 1.f) inline
Definition at line 148 of file SpringInterpolator.h.
Member Function Documentation
GetDefaultStiffnessConstant()
template<typename T> float FRK4SpringInterpolator< T >::GetDefaultStiffnessConstant () const inline
Definition at line 172 of file SpringInterpolator.h.
GetLastDeltaPosition()
template<typename T> T FRK4SpringInterpolator< T >::GetLastDeltaPosition () const inline
Definition at line 197 of file SpringInterpolator.h.
GetPosition()
template<typename T> T FRK4SpringInterpolator< T >::GetPosition () const inline
Definition at line 182 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::IsPositionEqualTo().
GetVelocity()
template<typename T> T FRK4SpringInterpolator< T >::GetVelocity () const inline
Definition at line 202 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::IsVelocityZero().
IsInMotion()
template<typename T> bool FRK4SpringInterpolator< T >::IsInMotion () const inline
Definition at line 177 of file SpringInterpolator.h.
IsPositionEqualTo()
template<typename T> bool FRK4SpringInterpolator< T >::IsPositionEqualTo (const T & OtherPosition) const inline
Definition at line 218 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::Update().
IsVelocityZero()
template<typename T> bool FRK4SpringInterpolator< T >::IsVelocityZero () const inline
Definition at line 223 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::SetVelocity(), and FRK4SpringInterpolator< float >::Update().
OffsetPosition()
template<typename T> void FRK4SpringInterpolator< T >::OffsetPosition (const T & Offset) inline
Definition at line 192 of file SpringInterpolator.h.
OffsetVelocity()
template<typename T> void FRK4SpringInterpolator< T >::OffsetVelocity (const T & Offset) inline
Definition at line 213 of file SpringInterpolator.h.
Reset()
template<typename T> void FRK4SpringInterpolator< T >::Reset (const T & DefaultPosition = T(0.f)) inline
Definition at line 228 of file SpringInterpolator.h.
SetDefaultSpringConstants()
template<typename T> void FRK4SpringInterpolator< T >::SetDefaultSpringConstants (const float & InSpringStiffness, const float & InDampeningRatio = 1.f) inline
Parameters
InDampeningRatio 0 = Undamped, <1 = Underdamped, 1 = Critically damped, >1 = Overdamped
Definition at line 158 of file SpringInterpolator.h.
SetPosition()
template<typename T> void FRK4SpringInterpolator< T >::SetPosition (const T & NewPosition) inline
Definition at line 187 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::Update().
SetSpringConstants()
template<typename T> void FRK4SpringInterpolator< T >::SetSpringConstants (const float & InSpringStiffness, const float & InDampeningRatio = 1.f) inline
Parameters
InDampeningRatio 0 = Undamped, <1 = Underdamped, 1 = Critically damped, >1 = Overdamped
Definition at line 165 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::Update().
SetVelocity()
template<typename T> void FRK4SpringInterpolator< T >::SetVelocity (const T & NewVelocity) inline
Definition at line 207 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::OffsetVelocity().
Update() [1/2]
template<typename T> T FRK4SpringInterpolator< T >::Update (const T & InNewPosition, const T & InTargetPosition, const float & InDeltaTime) inline
Definition at line 283 of file SpringInterpolator.h.
Update() [2/2]
template<typename T> T FRK4SpringInterpolator< T >::Update (const T & InTargetPosition, const float & InDeltaTime) inline
Definition at line 236 of file SpringInterpolator.h.
Referenced by FRK4SpringInterpolator< float >::Update().
Field Documentation
bIsInitialized
template<typename T> bool FRK4SpringInterpolator< T >::bIsInitialized protected
Definition at line 139 of file SpringInterpolator.h.
bIsInMotion
template<typename T> bool FRK4SpringInterpolator< T >::bIsInMotion protected
Definition at line 140 of file SpringInterpolator.h.
DampeningRatio
template<typename T> float FRK4SpringInterpolator< T >::DampeningRatio protected
Definition at line 137 of file SpringInterpolator.h.
LastPosition
template<typename T> T FRK4SpringInterpolator< T >::LastPosition protected
Definition at line 144 of file SpringInterpolator.h.
SpringConstants
template<typename T> FRK4SpringConstants FRK4SpringInterpolator< T >::SpringConstants protected
Definition at line 142 of file SpringInterpolator.h.
State
template<typename T> RK4Integrator::FRK4State<T> FRK4SpringInterpolator< T >::State protected
Definition at line 145 of file SpringInterpolator.h.
StiffnessConstant
template<typename T> float FRK4SpringInterpolator< T >::StiffnessConstant protected
Definition at line 136 of file SpringInterpolator.h.
TimeRemaining
template<typename T> float FRK4SpringInterpolator< T >::TimeRemaining protected
Definition at line 141 of file SpringInterpolator.h.
The documentation for this struct was generated from the following file:
SpringInterpolator.h