Unreal Engine 5.6 C++ API: FRenderBounds Struct Reference
FRenderBounds Struct Reference
#include "RenderTransform.h"
Public Member Functions
FORCEINLINE FRenderBounds ()
FORCEINLINE FRenderBounds (const FBox &Box)
FORCEINLINE FRenderBounds (const FBoxSphereBounds &Bounds)
FORCEINLINE FRenderBounds (const FVector3f &InMin, const FVector3f &InMax)
FORCEINLINE float ComputeSquaredDistanceToPoint (const FVector3f &Point) const
Computes a squared distance to point.
FORCEINLINE bool Equals (const FRenderBounds &Other, float Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE FVector3f GetCenter () const
FORCEINLINE FVector3f GetExtent () const
FORCEINLINE const FVector3f & GetMax () const
FORCEINLINE const FVector3f & GetMin () const
FORCEINLINE float GetSurfaceArea () const
FORCEINLINE FRenderBounds operator+ (const FRenderBounds &Other) const
FORCEINLINE FRenderBounds & operator+= (const FRenderBounds &Other)
FORCEINLINE FRenderBounds & operator+= (const FVector3f &Other)
FORCEINLINE FRenderBounds & operator= (const FVector3f &Other)
FORCEINLINE FBox ToBox () const
FORCEINLINE FBoxSphereBounds ToBoxSphereBounds () const
RENDERCORE_API FRenderBounds TransformBy (const FMatrix44d &M) const
RENDERCORE_API FRenderBounds TransformBy (const FMatrix44f &M) const
Gets a bounding volume transformed by a matrix.
RENDERCORE_API FRenderBounds TransformBy (const FRenderTransform &T) const
Gets a bounding volume transformed by a render transform.
Data Fields
FVector3f Max
FVector3f Min
Friends
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, FRenderBounds &B)
Serializes the render bounds.
Detailed Description
Definition at line 271 of file RenderTransform.h.
Constructor & Destructor Documentation
FRenderBounds() [1/4]
FORCEINLINE FRenderBounds::FRenderBounds () inline
Definition at line 277 of file RenderTransform.h.
References FORCEINLINE, Max, MAX_flt, and Min.
Referenced by Equals(), operator+(), operator+=(), operator+=(), operator<<, operator=(), TransformBy(), TransformBy(), and TransformBy().
FRenderBounds() [2/4]
FORCEINLINE FRenderBounds::FRenderBounds (const FVector3f & InMin, const FVector3f & InMax) inline
Definition at line 283 of file RenderTransform.h.
References FORCEINLINE, Max, and Min.
FRenderBounds() [3/4]
FORCEINLINE FRenderBounds::FRenderBounds (const FBox & Box) inline
Definition at line 289 of file RenderTransform.h.
References Box, FORCEINLINE, Max, and Min.
FRenderBounds() [4/4]
FORCEINLINE FRenderBounds::FRenderBounds (const FBoxSphereBounds & Bounds) inline
Definition at line 295 of file RenderTransform.h.
References UE::Math::TBoxSphereBounds< T, TExtent >::BoxExtent, FORCEINLINE, Max, Min, and UE::Math::TBoxSphereBounds< T, TExtent >::Origin.
Member Function Documentation
ComputeSquaredDistanceToPoint()
FORCEINLINE float FRenderBounds::ComputeSquaredDistanceToPoint (const FVector3f & Point) const inline
Computes a squared distance to point.
Parameters
Point Point
Returns
Squared distance to specified point
Definition at line 392 of file RenderTransform.h.
References FORCEINLINE, GetCenter(), GetExtent(), UE::Math::TVector< float >::Max(), and Point.
Equals()
FORCEINLINE bool FRenderBounds::Equals (const FRenderBounds & Other, float Tolerance = UE_KINDA_SMALL_NUMBER) const inline
Definition at line 338 of file RenderTransform.h.
References FRenderBounds(), FORCEINLINE, Max, Min, Other, and UE_KINDA_SMALL_NUMBER.
GetCenter()
FORCEINLINE FVector3f FRenderBounds::GetCenter () const inline
Definition at line 353 of file RenderTransform.h.
References FORCEINLINE, Max, and Min.
Referenced by ComputeSquaredDistanceToPoint(), and FPrimitiveUniformShaderParametersBuilder::InstanceLocalBounds().
GetExtent()
FORCEINLINE FVector3f FRenderBounds::GetExtent () const inline
Definition at line 358 of file RenderTransform.h.
References FORCEINLINE, Max, and Min.
Referenced by ComputeSquaredDistanceToPoint(), and FPrimitiveUniformShaderParametersBuilder::InstanceLocalBounds().
GetMax()
FORCEINLINE const FVector3f & FRenderBounds::GetMax () const inline
Definition at line 348 of file RenderTransform.h.
References FORCEINLINE, and Max.
GetMin()
FORCEINLINE const FVector3f & FRenderBounds::GetMin () const inline
Definition at line 343 of file RenderTransform.h.
References FORCEINLINE, and Min.
GetSurfaceArea()
FORCEINLINE float FRenderBounds::GetSurfaceArea () const inline
Definition at line 363 of file RenderTransform.h.
References FORCEINLINE, Max, Min, and TSequenceHistory< HistorySize >::Size.
operator+()
FORCEINLINE FRenderBounds FRenderBounds::operator+ (const FRenderBounds & Other) const inline
Definition at line 333 of file RenderTransform.h.
References FRenderBounds(), FORCEINLINE, and Other.
operator+=() [1/2]
FORCEINLINE FRenderBounds & FRenderBounds::operator+= (const FRenderBounds & Other) inline
Definition at line 326 of file RenderTransform.h.
References FRenderBounds(), FORCEINLINE, Max, Min, Other, VectorLoadFloat3(), VectorMax(), VectorMin(), and VectorStoreFloat3().
operator+=() [2/2]
FORCEINLINE FRenderBounds & FRenderBounds::operator+= (const FVector3f & Other) inline
Definition at line 318 of file RenderTransform.h.
References FRenderBounds(), FORCEINLINE, Max, Min, Other, VectorLoadFloat3(), VectorMax(), VectorMin(), and VectorStoreFloat3().
operator=()
FORCEINLINE FRenderBounds & FRenderBounds::operator= (const FVector3f & Other) inline
Definition at line 311 of file RenderTransform.h.
References FRenderBounds(), FORCEINLINE, Max, Min, and Other.
ToBox()
FORCEINLINE FBox FRenderBounds::ToBox () const inline
Definition at line 301 of file RenderTransform.h.
References FORCEINLINE, FVector, Max, and Min.
Referenced by ToBoxSphereBounds().
ToBoxSphereBounds()
FORCEINLINE FBoxSphereBounds FRenderBounds::ToBoxSphereBounds () const inline
Definition at line 306 of file RenderTransform.h.
References FORCEINLINE, and ToBox().
TransformBy() [1/3]
RENDERCORE_API FRenderBounds FRenderBounds::TransformBy (const FMatrix44d & M) const
References FRenderBounds().
TransformBy() [2/3]
RENDERCORE_API FRenderBounds FRenderBounds::TransformBy (const FMatrix44f & M) const
Gets a bounding volume transformed by a matrix.
Parameters
M The matrix.
Returns
The transformed volume.
References FRenderBounds().
TransformBy() [3/3]
RENDERCORE_API FRenderBounds FRenderBounds::TransformBy (const FRenderTransform & T) const
Gets a bounding volume transformed by a render transform.
Parameters
T The render transform.
Returns
The transformed volume.
References FRenderBounds().
Friends And Related Symbol Documentation
operator<<
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, FRenderBounds & B) friend
Serializes the render bounds.
Parameters
Ar Reference to the serialization archive.
B Reference to the render bounds being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 406 of file RenderTransform.h.
References FRenderBounds(), Ar, B, and FORCEINLINE.
Field Documentation
Max
FVector3f FRenderBounds::Max
Definition at line 274 of file RenderTransform.h.
Referenced by FRenderBounds(), FRenderBounds(), FRenderBounds(), FRenderBounds(), Equals(), GetCenter(), GetExtent(), GetMax(), GetSurfaceArea(), operator+=(), operator+=(), operator=(), and ToBox().
Min
FVector3f FRenderBounds::Min
Definition at line 273 of file RenderTransform.h.
Referenced by FRenderBounds(), FRenderBounds(), FRenderBounds(), FRenderBounds(), Equals(), GetCenter(), GetExtent(), GetMin(), GetSurfaceArea(), operator+=(), operator+=(), operator=(), and ToBox().
The documentation for this struct was generated from the following file:
RenderTransform.h