Unreal Engine 5.6 C++ API: FHairDescription Class Reference
FHairDescription Class Reference
#include "HairDescription.h"
Public Member Functions
HAIRSTRANDSCORE_API FHairDescription ()
FHairDescription (const FHairDescription &)=default
FHairDescription (FHairDescription &&)=default
~FHairDescription ()=default
HAIRSTRANDSCORE_API FStrandID AddStrand ()
HAIRSTRANDSCORE_API FVertexID AddVertex ()
int32 GetNumStrands () const
int32 GetNumVertices () const
TAttributesSet< FGroomID > & GroomAttributes ()
const TAttributesSet< FGroomID > & GroomAttributes () const
HAIRSTRANDSCORE_API bool HasAttribute (EHairAttribute InAttribute) const
HAIRSTRANDSCORE_API void InitializeStrands (int32 InNumStrands)
HAIRSTRANDSCORE_API void InitializeVertices (int32 InNumVertices)
HAIRSTRANDSCORE_API bool IsValid () const
FHairDescription & operator= (const FHairDescription &)=default
FHairDescription & operator= (FHairDescription &&)=default
HAIRSTRANDSCORE_API void Reset ()
HAIRSTRANDSCORE_API void Serialize (FArchive &Ar)
TAttributesSet< FStrandID > & StrandAttributes ()
const TAttributesSet< FStrandID > & StrandAttributes () const
UE_DEPRECATED (5.3, "HasAOAttributes accessor is deprecated. Use HasAttribute instead") HAIRSTRANDSCORE_API bool HasAOAttributes() const
UE_DEPRECATED (5.3, "HasClumpID accessor is deprecated. Use HasAttribute instead") HAIRSTRANDSCORE_API bool HasClumpID() const
UE_DEPRECATED (5.3, "HasColorAttributes accessor is deprecated. Use HasAttribute instead") HAIRSTRANDSCORE_API bool HasColorAttributes() const
UE_DEPRECATED (5.3, "HasGuideWeights accessor is deprecated. Use HasAttribute instead") HAIRSTRANDSCORE_API bool HasGuideWeights() const
UE_DEPRECATED (5.3, "HasRootUV accessor is deprecated. Use HasAttribute instead") HAIRSTRANDSCORE_API bool HasRootUV() const
UE_DEPRECATED (5.3, "HasRoughnessAttributes accessor is deprecated. Use HasAttribute instead") HAIRSTRANDSCORE_API bool HasRoughnessAttributes() const
TAttributesSet< FVertexID > & VertexAttributes ()
const TAttributesSet< FVertexID > & VertexAttributes () const
Private Attributes
TAttributesSet< FGroomID > GroomAttributesSet
int32 NumStrands
int32 NumVertices
TAttributesSet< FStrandID > StrandAttributesSet
TAttributesSet< FVertexID > VertexAttributesSet
Detailed Description
Definition at line 65 of file HairDescription.h.
Constructor & Destructor Documentation
FHairDescription() [1/3]
HAIRSTRANDSCORE_API FHairDescription::FHairDescription ()
Referenced by FHairDescription(), FHairDescription(), operator=(), and operator=().
~FHairDescription()
FHairDescription::~FHairDescription () default
FHairDescription() [2/3]
FHairDescription::FHairDescription (const FHairDescription &) default
References FHairDescription().
FHairDescription() [3/3]
FHairDescription::FHairDescription (FHairDescription &&) default
References FHairDescription().
Member Function Documentation
AddStrand()
HAIRSTRANDSCORE_API FStrandID FHairDescription::AddStrand ()
AddVertex()
HAIRSTRANDSCORE_API FVertexID FHairDescription::AddVertex ()
GetNumStrands()
int32 FHairDescription::GetNumStrands () const inline
Definition at line 95 of file HairDescription.h.
References NumStrands.
GetNumVertices()
int32 FHairDescription::GetNumVertices () const inline
Definition at line 94 of file HairDescription.h.
References NumVertices.
GroomAttributes() [1/2]
TAttributesSet< FGroomID > & FHairDescription::GroomAttributes () inline
Definition at line 91 of file HairDescription.h.
References GroomAttributesSet.
Referenced by SetGroomAttribute().
GroomAttributes() [2/2]
const TAttributesSet< FGroomID > & FHairDescription::GroomAttributes () const inline
Definition at line 92 of file HairDescription.h.
References GroomAttributesSet.
HasAttribute()
HAIRSTRANDSCORE_API bool FHairDescription::HasAttribute (EHairAttribute InAttribute) const
InitializeStrands()
HAIRSTRANDSCORE_API void FHairDescription::InitializeStrands (int32 InNumStrands)
InitializeVertices()
HAIRSTRANDSCORE_API void FHairDescription::InitializeVertices (int32 InNumVertices)
IsValid()
HAIRSTRANDSCORE_API bool FHairDescription::IsValid () const
operator=() [1/2]
FHairDescription & FHairDescription::operator= (const FHairDescription &) default
References FHairDescription().
operator=() [2/2]
FHairDescription & FHairDescription::operator= (FHairDescription &&) default
References FHairDescription().
Reset()
HAIRSTRANDSCORE_API void FHairDescription::Reset ()
Serialize()
HAIRSTRANDSCORE_API void FHairDescription::Serialize (FArchive & Ar)
References Ar.
StrandAttributes() [1/2]
TAttributesSet< FStrandID > & FHairDescription::StrandAttributes () inline
Definition at line 88 of file HairDescription.h.
References StrandAttributesSet.
Referenced by SetHairStrandAttribute().
StrandAttributes() [2/2]
const TAttributesSet< FStrandID > & FHairDescription::StrandAttributes () const inline
Definition at line 89 of file HairDescription.h.
References StrandAttributesSet.
UE_DEPRECATED() [1/6]
FHairDescription::UE_DEPRECATED (5. 3, "HasAOAttributes accessor is deprecated. Use HasAttribute instead") const
References UE_DEPRECATED().
UE_DEPRECATED() [2/6]
FHairDescription::UE_DEPRECATED (5. 3, "HasClumpID accessor is deprecated. Use HasAttribute instead") const
References UE_DEPRECATED().
UE_DEPRECATED() [3/6]
FHairDescription::UE_DEPRECATED (5. 3, "HasColorAttributes accessor is deprecated. Use HasAttribute instead") const
References UE_DEPRECATED().
UE_DEPRECATED() [4/6]
FHairDescription::UE_DEPRECATED (5. 3, "HasGuideWeights accessor is deprecated. Use HasAttribute instead") const
References UE_DEPRECATED().
UE_DEPRECATED() [5/6]
FHairDescription::UE_DEPRECATED (5. 3, "HasRootUV accessor is deprecated. Use HasAttribute instead") const
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [6/6]
FHairDescription::UE_DEPRECATED (5. 3, "HasRoughnessAttributes accessor is deprecated. Use HasAttribute instead") const
References UE_DEPRECATED().
VertexAttributes() [1/2]
TAttributesSet< FVertexID > & FHairDescription::VertexAttributes () inline
Definition at line 85 of file HairDescription.h.
References VertexAttributesSet.
Referenced by SetHairVertexAttribute().
VertexAttributes() [2/2]
const TAttributesSet< FVertexID > & FHairDescription::VertexAttributes () const inline
Definition at line 86 of file HairDescription.h.
References VertexAttributesSet.
Field Documentation
GroomAttributesSet
TAttributesSet<FGroomID> FHairDescription::GroomAttributesSet private
Definition at line 118 of file HairDescription.h.
Referenced by GroomAttributes(), and GroomAttributes().
NumStrands
int32 FHairDescription::NumStrands private
Definition at line 121 of file HairDescription.h.
Referenced by GetNumStrands().
NumVertices
int32 FHairDescription::NumVertices private
Definition at line 120 of file HairDescription.h.
Referenced by GetNumVertices().
StrandAttributesSet
TAttributesSet<FStrandID> FHairDescription::StrandAttributesSet private
Definition at line 117 of file HairDescription.h.
Referenced by StrandAttributes(), and StrandAttributes().
VertexAttributesSet
TAttributesSet<FVertexID> FHairDescription::VertexAttributesSet private
Definition at line 116 of file HairDescription.h.
Referenced by VertexAttributes(), and VertexAttributes().
The documentation for this class was generated from the following file:
HairDescription.h