Unreal Engine 5.6 C++ API: TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType > Class Template Reference
TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType > Class Template Reference
#include "AsyncEnumerateTask.h"
Data Structures
struct FEnumerationStackEntry
Public Types
typedef TFunctionRef< void(int32)> InitialStackCallback
Static Public Member Functions
static void EnumerateEventsDownSampled (FAsyncEnumerateTaskData< InEventType, SettingsType > &Data, InitialStackCallback InitCallback, typename ITimeline< InEventType >::EventCallback Callback)
Static Private Member Functions
static bool ShouldStopSearchingForEndEvents (FAsyncEnumerateTaskData< InEventType, SettingsType > &Data, FEnumerationStackEntry *EventStack, const FEventScopeEntryPage *InitialPage, int32 CurrentStackDepth, const FDetailLevel< InEventType, SettingsType > &DetailLevel)
Detailed Description
template<typename InEventType, typename SettingsType>
class TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >
Definition at line 30 of file AsyncEnumerateTask.h.
Member Typedef Documentation
InitialStackCallback
template<typename InEventType, typename SettingsType> typedef TFunctionRef<void(int32)> TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::InitialStackCallback
Definition at line 39 of file AsyncEnumerateTask.h.
Member Function Documentation
EnumerateEventsDownSampled()
template<typename InEventType, typename SettingsType> void TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::EnumerateEventsDownSampled (FAsyncEnumerateTaskData< InEventType, SettingsType > & Data, InitialStackCallback InitCallback, typename ITimeline< InEventType >::EventCallback Callback) inline static
Definition at line 41 of file AsyncEnumerateTask.h.
References TraceServices::FEventScopeEntryPage::BeginEventIndex, TraceServices::ByEndTime, TraceServices::ByStartTime, check, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::DetailLevel, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::EndPageIndex, TraceServices::FEventStackEntry::EndTime, TraceServices::FEventStackEntry::EnterScopeIndex, Event, TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::FEnumerationStackEntry::Event, TraceServices::FEventStackEntry::EventIndex, TraceServices::FDetailLevel< EventType, SettingsType >::Events, TraceServices::FDetailLevel< EventType, SettingsType >::GetEvent(), TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromItem(), TraceServices::FDetailLevel< EventType, SettingsType >::GetScopeEntryTime(), TraceServices::FEventScopeEntryPage::InitialStack, TraceServices::FEventScopeEntryPage::InitialStackCount, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::NumTasks, TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, ShouldStopSearchingForEndEvents(), TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::SortOrder, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::StartPageIndex, TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::FEnumerationStackEntry::StartTime, TraceServices::Stop, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::TaskIndex, and TraceServices::FEventScopeEntry::Time.
Referenced by TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::DoWork(), TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EnumerateOrderedByEndTime(), and TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EnumerateOrderedByStartTime().
ShouldStopSearchingForEndEvents()
template<typename InEventType, typename SettingsType> bool TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::ShouldStopSearchingForEndEvents (FAsyncEnumerateTaskData< InEventType, SettingsType > & Data, FEnumerationStackEntry * EventStack, const FEventScopeEntryPage * InitialPage, int32 CurrentStackDepth, const FDetailLevel< InEventType, SettingsType > & DetailLevel) inline static private
Definition at line 172 of file AsyncEnumerateTask.h.
References TraceServices::ByStartTime, TraceServices::FEventStackEntry::EnterScopeIndex, TraceServices::FDetailLevel< EventType, SettingsType >::GetScopeEntryTime(), TraceServices::FEventScopeEntryPage::InitialStack, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::SortOrder, and TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::TaskIndex.
Referenced by EnumerateEventsDownSampled().
The documentation for this class was generated from the following file:
AsyncEnumerateTask.h