Unreal Engine 5.6 C++ API: FBaseDynamicMeshSelector Class Reference
FBaseDynamicMeshSelector Class Reference
FBaseDynamicMeshSelector is an implementation of IGeometrySelector for a UDynamicMesh.
#include "DynamicMeshSelector.h"
Public Member Functions
virtual MODELINGCOMPONENTS_API ~FBaseDynamicMeshSelector ()
virtual MODELINGCOMPONENTS_API void AccumulateElementsFromPredicate (FGeometrySelectionElements &Elements, bool bTransformToWorld, bool bIsForPreview, bool bUseGroupTopology, TFunctionRef< bool(UE::Geometry::EGeometryElementType, UE::Geometry::FGeoSelectionID)> Predicate) override
Accumulate all geometric elements (currently 3D triangles, line segments, and points) in the provided ElementsInOut by initializing vertex, edge, and face selections using the provided predicate and then accumulating elements for those selections.
virtual MODELINGCOMPONENTS_API void AccumulateSelectionBounds (const FGeometrySelection &Selection, FGeometrySelectionBounds &BoundsInOut, bool bTransformToWorld) override
Accumulate the bounds of the provided Selection in the provided BoundsInOut.
virtual MODELINGCOMPONENTS_API void AccumulateSelectionElements (const FGeometrySelection &Selection, FGeometrySelectionElements &Elements, bool bTransformToWorld, UE::Geometry::EEnumerateSelectionMapping Flags=UE::Geometry::EEnumerateSelectionMapping::Default) override
Prefer AccumulateSelectionElements with Flags parameter.
UDynamicMesh * GetDynamicMesh () const
MODELINGCOMPONENTS_API const UE::Geometry::FGroupTopology * GetGroupTopology ()
virtual FGeometryIdentifier GetIdentifier () const override
virtual FTransform GetLocalToWorldTransform () const
virtual MODELINGCOMPONENTS_API void GetSelectionFrame (const FGeometrySelection &Selection, UE::Geometry::FFrame3d &SelectionFrame, bool bTransformToWorld) override
Compute a 3D frame for the provided Selection.
virtual MODELINGCOMPONENTS_API void GetSelectionPreviewForRaycast (const FWorldRayQueryInfo &RayInfo, FGeometrySelectionEditor &PreviewEditor) override
Query the Selector for a potential selection based on world-space Ray.
virtual FGeometryIdentifier GetSourceGeometryIdentifier () const
virtual MODELINGCOMPONENTS_API void GetTargetFrame (const FGeometrySelection &Selection, UE::Geometry::FFrame3d &SelectionFrame) override
Compute a 3D frame for the Selector's target object.
virtual MODELINGCOMPONENTS_API void Initialize (FGeometryIdentifier SourceGeometryIdentifier, UDynamicMesh *TargetMesh, TUniqueFunction< UE::Geometry::FTransformSRT3d()> GetWorldTransformFunc)
Initialize the FBaseDynamicMeshSelector for a given source/target UDynamicMesh.
virtual MODELINGCOMPONENTS_API void InitializeSelectionFromPredicate (FGeometrySelection &SelectionInOut, TFunctionRef< bool(UE::Geometry::FGeoSelectionID)> SelectionIDPredicate, EInitializeSelectionMode InitializeMode=EInitializeSelectionMode::All, const FGeometrySelection *ReferenceSelection=nullptr) override
Populate a Selection using the provided ReferenceMode, with a Predicate and optional ReferenceSelection.
virtual MODELINGCOMPONENTS_API bool RayHitTest (const FWorldRayQueryInfo &RayInfo, UE::Geometry::FGeometrySelectionHitQueryConfig QueryConfig, FInputRayHit &HitResultOut) override
Check for intersection between a world-space Ray with the Selector's target object and return a FInputRayHit result.
virtual MODELINGCOMPONENTS_API bool Restore ()
Restore a Selector that has had Sleep() called on it.
virtual MODELINGCOMPONENTS_API void Shutdown () override
Disconnect the Selector from its target object and prepare for deletion.
virtual MODELINGCOMPONENTS_API bool Sleep ()
Temporarily disable the Selector, with the intention of re-enabling it (via Restore()) in the future.
virtual MODELINGCOMPONENTS_API bool SupportsSleep () const
The SelectionManager will call SupportsSleep() to determine if an IGeometrySelector needs to be destroyed when the target object is deselected, or if it can be re-used (generally more efficient)
UE_DEPRECATED (5.5, "AccumulateSelectionElements which takes a bIsForPreview boolean is deprecated." "Please use the function of the same name which takes EEnumerateSelectionMapping flags instead") MODELINGCOMPONENTS_API virtual void AccumulateSelectionElements(const FGeometrySelection &Selection
virtual MODELINGCOMPONENTS_API void UpdateAfterGeometryEdit (IToolsContextTransactionsAPI *TransactionsAPI, bool bInTransaction, TUniquePtr< UE::Geometry::FDynamicMeshChange > DynamicMeshChange, FText GeometryEditTransactionString)
UpdateAfterGeometryEdit should be called after editing the UDynamicMesh owned by the Selector (TargetMesh).
virtual MODELINGCOMPONENTS_API void UpdateSelectionFromSelection (const FGeometrySelection &FromSelection, bool bAllowConversion, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, UE::Geometry::FGeometrySelectionDelta *SelectionDelta=nullptr) override
Combine FromSelection with the current Selection owned/referenced by the Selector, using the provided SelectionEditor and UpdateConfig.
virtual MODELINGCOMPONENTS_API void UpdateSelectionViaRaycast (const FWorldRayQueryInfo &RayInfo, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut) override
Update the active selection based on a world-space Ray.
virtual MODELINGCOMPONENTS_API void UpdateSelectionViaShape (const FWorldShapeQueryInfo &ShapeInfo, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut) override
Update the active selection based on a world-space Shape.
Public Member Functions inherited from IGeometrySelector
virtual ~IGeometrySelector ()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnGeometryModified, IGeometrySelector *Selector)
FOnGeometryModified & GetOnGeometryModifed ()
The OnGeometryModified delegate will fire if the geometry of the Selector's Target Object is modified.
virtual IGeometrySelectionTransformer * InitializeTransformation (const FGeometrySelection &Selection)=0
Create and initialize a IGeometrySelectionTransformer for the provided Selection.
virtual bool IsLockable () const
virtual bool IsLocked () const
virtual void SetLockedState (bool bLocked)
virtual void ShutdownTransformation (IGeometrySelectionTransformer *Transformer)=0
Shutdown an active IGeometrySelectionTransformer.
UE_DEPRECATED (5.5, "AccumulateSelectionElements which takes a bIsForPreview boolean is deprecated." "Please use the function of the same name which takes EEnumerateSelectionMapping flags instead") virtual void AccumulateSelectionElements(const FGeometrySelection &Selection
Prefer AccumulateSelectionElements with Flags parameter.
Data Fields
FGeometrySelectionElements bool bTransformToWorld
FGeometrySelectionElements & Elements
FGeometrySelectionElements bool bool bIsForPreview override
Data Fields inherited from IGeometrySelector
FGeometrySelectionElements bool bool bIsForPreview = 0
FGeometrySelectionElements bool bTransformToWorld
FGeometrySelectionElements & ElementsInOut
Protected Member Functions
MODELINGCOMPONENTS_API const UE::Geometry::FColliderMesh * GetColliderMesh ()
MODELINGCOMPONENTS_API const UE::Geometry::FSegmentTree3 * GetGroupEdgeSpatial ()
MODELINGCOMPONENTS_API void InvalidateOnMeshChange (FDynamicMeshChangeInfo ChangeInfo)
MODELINGCOMPONENTS_API void RegisterMeshChangedHandler ()
MODELINGCOMPONENTS_API void UpdateColliderMesh ()
MODELINGCOMPONENTS_API void UpdateGroupEdgeSegmentTree ()
MODELINGCOMPONENTS_API void UpdateGroupTopology ()
virtual MODELINGCOMPONENTS_API void UpdateSelectionViaRaycast_GroupEdges (const FWorldRayQueryInfo &RayInfo, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut)
virtual MODELINGCOMPONENTS_API void UpdateSelectionViaRaycast_MeshTopology (const FWorldRayQueryInfo &RayInfo, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut)
Protected Member Functions inherited from IGeometrySelector
void NotifyGeometryModified ()
Protected Attributes
TPimplPtr< UE::Geometry::FColliderMesh > ColliderMesh
TUniqueFunction< UE::Geometry::FTransformSRT3d()> GetWorldTransformFunc
TPimplPtr< UE::Geometry::FSegmentTree3 > GroupEdgeSegmentTree
TPimplPtr< UE::Geometry::FGroupTopology > GroupTopology
TWeakObjectPtr< UDynamicMesh > SleepingTargetMesh = nullptr
FGeometryIdentifier SourceGeometryIdentifier
TWeakObjectPtr< UDynamicMesh > TargetMesh
FDelegateHandle TargetMesh_OnMeshChangedHandle
Protected Attributes inherited from IGeometrySelector
FOnGeometryModified OnGeometryModifed
Additional Inherited Members
Public Types inherited from IGeometrySelector
enum class EInitializeSelectionMode { All , Connected , AdjacentToBorder }
using FGeometrySelection = UE::Geometry::FGeometrySelection
using FGeometrySelectionBounds = UE::Geometry::FGeometrySelectionBounds
using FGeometrySelectionEditor = UE::Geometry::FGeometrySelectionEditor
using FGeometrySelectionElements = UE::Geometry::FGeometrySelectionElements
using FGeometrySelectionUpdateConfig = UE::Geometry::FGeometrySelectionUpdateConfig
using FGeometrySelectionUpdateResult = UE::Geometry::FGeometrySelectionUpdateResult
Detailed Description
FBaseDynamicMeshSelector is an implementation of IGeometrySelector for a UDynamicMesh.
Note that the Selector itself does not require that the target object be a UDynamicMeshComponent, and subclasses of FBaseDynamicMeshSelector are used for both Volumes and StaticMeshComponents. Access to the World transform is provided by a TUniqueFunction set up in the Factory.
Definition at line 30 of file DynamicMeshSelector.h.
Constructor & Destructor Documentation
~FBaseDynamicMeshSelector()
virtual MODELINGCOMPONENTS_API FBaseDynamicMeshSelector::~FBaseDynamicMeshSelector () virtual
References UE_API.
Member Function Documentation
AccumulateElementsFromPredicate()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::AccumulateElementsFromPredicate (FGeometrySelectionElements & ElementsInOut, bool bTransformToWorld, bool bIsForPreview, bool bUseGroupTopology, TFunctionRef< bool(UE::Geometry::EGeometryElementType, UE::Geometry::FGeoSelectionID)> Predicate) override virtual
Accumulate all geometric elements (currently 3D triangles, line segments, and points) in the provided ElementsInOut by initializing vertex, edge, and face selections using the provided predicate and then accumulating elements for those selections.
ElementsInOut is not cleared.
Parameters
bTransformToWorld if true each geometric element will be transformed to World space, based on GetLocalToWorldTransform()
bIsForPreview if true, geometry is being collected for a preview of selection. Selector may return simplified geometry in this case
bUseGroupTopology if true, attempt to use group topology when populating ElementsInOut
Predicate if true for a given element type and element ID, this element will be collected, otherwise this element will be skipped.
Implements IGeometrySelector.
References AccumulateElementsFromPredicate(), IGeometrySelector::bIsForPreview, bTransformToWorld, Elements, Geometry, override, Predicate, and UE_API.
Referenced by AccumulateElementsFromPredicate().
AccumulateSelectionBounds()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::AccumulateSelectionBounds (const FGeometrySelection & Selection, FGeometrySelectionBounds & BoundsInOut, bool bTransformToWorld) override virtual
Accumulate the bounds of the provided Selection in the provided BoundsInOut.
BoundsInOut is not cleared.
Parameters
bTransformToWorld if true each bounded point/element will be transformed to World space before being "contained" in BoundsInOut
Implements IGeometrySelector.
References bTransformToWorld, and UE_API.
AccumulateSelectionElements()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::AccumulateSelectionElements (const FGeometrySelection & Selection, FGeometrySelectionElements & Elements, bool bTransformToWorld, UE::Geometry::EEnumerateSelectionMapping Flags = UE::Geometry::EEnumerateSelectionMapping::Default) override virtual
Prefer AccumulateSelectionElements with Flags parameter.
Implements IGeometrySelector.
References AccumulateSelectionElements(), bTransformToWorld, Default, Elements, Flags, Geometry, override, and UE_API.
Referenced by AccumulateSelectionElements().
GetColliderMesh()
MODELINGCOMPONENTS_API const UE::Geometry::FColliderMesh * FBaseDynamicMeshSelector::GetColliderMesh () protected
References UE_API.
GetDynamicMesh()
UDynamicMesh * FBaseDynamicMeshSelector::GetDynamicMesh () const inline
Definition at line 162 of file DynamicMeshSelector.h.
References GetDynamicMesh(), and TargetMesh.
Referenced by GetDynamicMesh().
GetGroupEdgeSpatial()
MODELINGCOMPONENTS_API const UE::Geometry::FSegmentTree3 * FBaseDynamicMeshSelector::GetGroupEdgeSpatial () protected
References UE_API.
GetGroupTopology()
MODELINGCOMPONENTS_API const UE::Geometry::FGroupTopology * FBaseDynamicMeshSelector::GetGroupTopology ()
References UE_API.
GetIdentifier()
virtual FGeometryIdentifier FBaseDynamicMeshSelector::GetIdentifier () const inline override virtual
Returns
a FGeometryIdentifier for this Selector.
Implements IGeometrySelector.
Definition at line 64 of file DynamicMeshSelector.h.
References FGeometryIdentifier::DynamicMesh, FGeometryIdentifier::MeshContainer, FGeometryIdentifier::ObjectType, TargetMesh, FGeometryIdentifier::TargetObject, and FGeometryIdentifier::TargetType.
GetLocalToWorldTransform()
virtual FTransform FBaseDynamicMeshSelector::GetLocalToWorldTransform () const inline virtual
Returns
the World transform for the Selector's target object
Implements IGeometrySelector.
Definition at line 115 of file DynamicMeshSelector.h.
References GetWorldTransformFunc.
GetSelectionFrame()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::GetSelectionFrame (const FGeometrySelection & Selection, UE::Geometry::FFrame3d & SelectionFrameOut, bool bTransformToWorld) override virtual
Compute a 3D frame for the provided Selection.
For example this could simply be a frame aligned to the XYZ axes at the center of the selection bounding-box, or something more sophisticated, like aligned to the tangent-space of the selected element(s), etc.
Parameters
bTransformToWorld if true the resulting SelectionFrameOut will be in world-space, based on GetLocalToWorldTransform()
Implements IGeometrySelector.
References bTransformToWorld, and UE_API.
GetSelectionPreviewForRaycast()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::GetSelectionPreviewForRaycast (const FWorldRayQueryInfo & RayInfo, FGeometrySelectionEditor & PreviewEditor) override virtual
Query the Selector for a potential selection based on world-space Ray.
The intention of this query is that it be used for "selection preview", eg like hover-highlighting. The PreviewEditor will always be updated in 'Add' mode, and currently no result information will be returned.
Implements IGeometrySelector.
References UE_API.
GetSourceGeometryIdentifier()
virtual FGeometryIdentifier FBaseDynamicMeshSelector::GetSourceGeometryIdentifier () const inline virtual
Returns
FGeometryIdentifier for the parent of this Selector (eg a UDynamicMeshComponent in the common case)
Definition at line 49 of file DynamicMeshSelector.h.
References SourceGeometryIdentifier.
GetTargetFrame()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::GetTargetFrame (const FGeometrySelection & Selection, UE::Geometry::FFrame3d & SelectionFrameOut) override virtual
Compute a 3D frame for the Selector's target object.
Implements IGeometrySelector.
References UE_API.
Initialize()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::Initialize (FGeometryIdentifier SourceGeometryIdentifier, UDynamicMesh * TargetMesh, TUniqueFunction< UE::Geometry::FTransformSRT3d()> GetWorldTransformFunc) virtual
Initialize the FBaseDynamicMeshSelector for a given source/target UDynamicMesh.
Parameters
SourceGeometryIdentifier identifier for the object that the TargetMesh came from (eg DynamicMeshComponent or other UDynamicMesh source)
TargetMesh the target UDynamicMesh
GetWorldTransformFunc function that provides the Local to World Transform
References GetWorldTransformFunc, SourceGeometryIdentifier, TargetMesh, and UE_API.
InitializeSelectionFromPredicate()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::InitializeSelectionFromPredicate (FGeometrySelection & SelectionInOut, TFunctionRef< bool(UE::Geometry::FGeoSelectionID)> SelectionIDPredicate, EInitializeSelectionMode InitializeMode = EInitializeSelectionMode::All, const FGeometrySelection * ReferenceSelection = nullptr) override virtual
Populate a Selection using the provided ReferenceMode, with a Predicate and optional ReferenceSelection.
Note that this method does not modify/access any selection that might be "owned" by the Selector. It is part of the IGeometrySelector API because often a Selector has access to internal data structures (like a Mesh, GroupTopology, etc) that are required to initialize a Selection.
Parameters
SelectionInOut the Selection to initialize, the input Geometry/Topology types define what type of element will be selected
SelectionIDPredicate only Elements that pass this predicate will be included in SelectionInOut
InitializeMode method to use to initialize SelectionInOut
ReferenceSelection optional Selection to select "relative to", based on the InitializeMode
Implements IGeometrySelector.
References IGeometrySelector::All, and UE_API.
InvalidateOnMeshChange()
MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::InvalidateOnMeshChange (FDynamicMeshChangeInfo ChangeInfo) protected
References UE_API.
RayHitTest()
virtual MODELINGCOMPONENTS_API bool FBaseDynamicMeshSelector::RayHitTest (const FWorldRayQueryInfo & RayInfo, UE::Geometry::FGeometrySelectionHitQueryConfig QueryConfig, FInputRayHit & HitResultOut) override virtual
Check for intersection between a world-space Ray with the Selector's target object and return a FInputRayHit result.
RayHitTest() must return true for other raycast-based functions like UpdateSelectionViaRaycast() to be called.
Returns
true on hit, false on miss
Implements IGeometrySelector.
References UE_API.
RegisterMeshChangedHandler()
MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::RegisterMeshChangedHandler () protected
References UE_API.
Restore()
virtual MODELINGCOMPONENTS_API bool FBaseDynamicMeshSelector::Restore () virtual
Restore a Selector that has had Sleep() called on it.
Returns
true on success
Reimplemented from IGeometrySelector.
References UE_API.
Shutdown()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::Shutdown () override virtual
Disconnect the Selector from its target object and prepare for deletion.
Implements IGeometrySelector.
References UE_API.
Sleep()
virtual MODELINGCOMPONENTS_API bool FBaseDynamicMeshSelector::Sleep () virtual
Temporarily disable the Selector, with the intention of re-enabling it (via Restore()) in the future.
Sleep should (currently) free any large memory data structures.
Returns
true if Sleep was successful, if not the Selector will likely be Shutdown
Reimplemented from IGeometrySelector.
References UE_API.
SupportsSleep()
virtual MODELINGCOMPONENTS_API bool FBaseDynamicMeshSelector::SupportsSleep () const virtual
The SelectionManager will call SupportsSleep() to determine if an IGeometrySelector needs to be destroyed when the target object is deselected, or if it can be re-used (generally more efficient)
Reimplemented from IGeometrySelector.
References UE_API.
UE_DEPRECATED()
FBaseDynamicMeshSelector::UE_DEPRECATED (5. 5, "AccumulateSelectionElements which takes a bIsForPreview boolean is deprecated." "Please use the function of the same name which takes EEnumerateSelectionMapping flags instead") const &
UpdateAfterGeometryEdit()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateAfterGeometryEdit (IToolsContextTransactionsAPI * TransactionsAPI, bool bInTransaction, TUniquePtr< UE::Geometry::FDynamicMeshChange > DynamicMeshChange, FText GeometryEditTransactionString) virtual
UpdateAfterGeometryEdit should be called after editing the UDynamicMesh owned by the Selector (TargetMesh).
This may be an external DynamicMesh in the case of a DynamicMeshComponent, or a temporary UDynamicMesh in the case of (eg) the StaticMeshSelector and VolumeSelector subclasses. In DynamicMeshSelector the MeshChange can just be emitted as a transaction, this is the default behavior. However in StaticMeshSelector, the StaticMesh needs to be synchronized with the UDynamicMesh modification in the same transaction. And potentially the MeshChange does not need to be emitted at all in that case.
This is a bit ugly and might be possible to do more cleanly by having the StaticMeshSelector listen to the UDynamicMesh for changes. However currently we do not have the granularity to have it /only/ listen for external mesh edit changes, and not all changes (and since the UDynamicMesh changes in response to
StaticMesh changes, eg on undo or external edits, it creates a cycle).
References Geometry, UE_API, and UpdateAfterGeometryEdit().
Referenced by UpdateAfterGeometryEdit().
UpdateColliderMesh()
MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateColliderMesh () protected
References UE_API.
UpdateGroupEdgeSegmentTree()
MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateGroupEdgeSegmentTree () protected
References UE_API.
UpdateGroupTopology()
MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateGroupTopology () protected
References UE_API.
UpdateSelectionFromSelection()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateSelectionFromSelection (const FGeometrySelection & FromSelection, bool bAllowConversion, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, UE::Geometry::FGeometrySelectionDelta * SelectionDelta = nullptr) override virtual
Combine FromSelection with the current Selection owned/referenced by the Selector, using the provided SelectionEditor and UpdateConfig.
This can be used to explicitly initialize the Selection, restore it to a previous state for undo/redo, etc.
Parameters
bAllowConversion if true, FromSelection's Geometry/Topology type will be converted to the internal types of the Selector/SelectionEditor
SelectionDelta if passed as non-null, this Delta will be initialized based on the change in the internal Selection
Implements IGeometrySelector.
References UE_API.
UpdateSelectionViaRaycast()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateSelectionViaRaycast (const FWorldRayQueryInfo & RayInfo, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut) override virtual
Update the active selection based on a world-space Ray.
Should only be called if RayHitTest() returns true. Uses the provided SelectionEditor and UpdateConfig to do the update Information about any changes actually made to the selection via the SelectionEditor are returned in ResultOut
Implements IGeometrySelector.
References UE_API.
UpdateSelectionViaRaycast_GroupEdges()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateSelectionViaRaycast_GroupEdges (const FWorldRayQueryInfo & RayInfo, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut) protected virtual
References UE_API.
UpdateSelectionViaRaycast_MeshTopology()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateSelectionViaRaycast_MeshTopology (const FWorldRayQueryInfo & RayInfo, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut) protected virtual
References UE_API.
UpdateSelectionViaShape()
virtual MODELINGCOMPONENTS_API void FBaseDynamicMeshSelector::UpdateSelectionViaShape (const FWorldShapeQueryInfo & ShapeInfo, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut) override virtual
Update the active selection based on a world-space Shape.
Uses the provided SelectionEditor and UpdateConfig to do the update Information about any changes actually made to the selection via the SelectionEditor are returned in ResultOut
Implements IGeometrySelector.
References UE_API.
Field Documentation
bTransformToWorld
FGeometrySelectionElements bool FBaseDynamicMeshSelector::bTransformToWorld
Definition at line 126 of file DynamicMeshSelector.h.
Referenced by AccumulateElementsFromPredicate(), AccumulateSelectionBounds(), AccumulateSelectionElements(), and GetSelectionFrame().
ColliderMesh
TPimplPtr<UE::Geometry::FColliderMesh> FBaseDynamicMeshSelector::ColliderMesh protected
Definition at line 179 of file DynamicMeshSelector.h.
Elements
FGeometrySelectionElements& FBaseDynamicMeshSelector::Elements
Definition at line 126 of file DynamicMeshSelector.h.
Referenced by AccumulateElementsFromPredicate(), and AccumulateSelectionElements().
GetWorldTransformFunc
TUniqueFunction<UE::Geometry::FTransformSRT3d()> FBaseDynamicMeshSelector::GetWorldTransformFunc protected
Definition at line 167 of file DynamicMeshSelector.h.
Referenced by GetLocalToWorldTransform(), and Initialize().
GroupEdgeSegmentTree
TPimplPtr<UE::Geometry::FSegmentTree3> FBaseDynamicMeshSelector::GroupEdgeSegmentTree protected
Definition at line 193 of file DynamicMeshSelector.h.
GroupTopology
TPimplPtr<UE::Geometry::FGroupTopology> FBaseDynamicMeshSelector::GroupTopology protected
Definition at line 186 of file DynamicMeshSelector.h.
override
FGeometrySelectionElements bool bool bIsForPreview FBaseDynamicMeshSelector::override
Definition at line 126 of file DynamicMeshSelector.h.
Referenced by AccumulateElementsFromPredicate(), and AccumulateSelectionElements().
SleepingTargetMesh
TWeakObjectPtr<UDynamicMesh> FBaseDynamicMeshSelector::SleepingTargetMesh = nullptr protected
Definition at line 198 of file DynamicMeshSelector.h.
SourceGeometryIdentifier
FGeometryIdentifier FBaseDynamicMeshSelector::SourceGeometryIdentifier protected
Definition at line 166 of file DynamicMeshSelector.h.
Referenced by GetSourceGeometryIdentifier(), and Initialize().
TargetMesh
TWeakObjectPtr<UDynamicMesh> FBaseDynamicMeshSelector::TargetMesh protected
Definition at line 169 of file DynamicMeshSelector.h.
Referenced by GetDynamicMesh(), GetIdentifier(), and Initialize().
TargetMesh_OnMeshChangedHandle
FDelegateHandle FBaseDynamicMeshSelector::TargetMesh_OnMeshChangedHandle protected
Definition at line 172 of file DynamicMeshSelector.h.
The documentation for this class was generated from the following file:
DynamicMeshSelector.h