Unreal Engine 5.6 C++ API: IImportantToggleSettingInterface Class Reference
IImportantToggleSettingInterface Class Reference
#include "ImportantToggleSettingInterface.h"
Private Member Functions
GENERATED_IINTERFACE_BODY () virtual void GetToggleCategoryAndPropertyNames(FName &OutCategory
virtual FString GetAdditionalInfoUrl () const
virtual FText GetAdditionalInfoUrlLabel () const
virtual FText GetFalseStateDescription () const
virtual FText GetFalseStateLabel () const
virtual FText GetFalseStateTooltip () const
virtual FText GetTrueStateDescription () const
virtual FText GetTrueStateLabel () const
virtual FText GetTrueStateTooltip () const
Private Attributes
FName &OutProperty const { OutCategory = NAME_None
OutProperty = NAME_None
Detailed Description
Definition at line 24 of file ImportantToggleSettingInterface.h.
Member Function Documentation
GENERATED_IINTERFACE_BODY()
IImportantToggleSettingInterface::GENERATED_IINTERFACE_BODY () & private
GetAdditionalInfoUrl()
virtual FString IImportantToggleSettingInterface::GetAdditionalInfoUrl () const inline private virtual
Definition at line 36 of file ImportantToggleSettingInterface.h.
GetAdditionalInfoUrlLabel()
virtual FText IImportantToggleSettingInterface::GetAdditionalInfoUrlLabel () const inline private virtual
Definition at line 37 of file ImportantToggleSettingInterface.h.
References FText::GetEmpty().
GetFalseStateDescription()
virtual FText IImportantToggleSettingInterface::GetFalseStateDescription () const inline private virtual
Definition at line 32 of file ImportantToggleSettingInterface.h.
References FText::GetEmpty().
GetFalseStateLabel()
virtual FText IImportantToggleSettingInterface::GetFalseStateLabel () const inline private virtual
Definition at line 30 of file ImportantToggleSettingInterface.h.
References FText::GetEmpty().
GetFalseStateTooltip()
virtual FText IImportantToggleSettingInterface::GetFalseStateTooltip () const inline private virtual
Definition at line 31 of file ImportantToggleSettingInterface.h.
References FText::GetEmpty().
GetTrueStateDescription()
virtual FText IImportantToggleSettingInterface::GetTrueStateDescription () const inline private virtual
Definition at line 35 of file ImportantToggleSettingInterface.h.
References FText::GetEmpty().
GetTrueStateLabel()
virtual FText IImportantToggleSettingInterface::GetTrueStateLabel () const inline private virtual
Definition at line 33 of file ImportantToggleSettingInterface.h.
References FText::GetEmpty().
GetTrueStateTooltip()
virtual FText IImportantToggleSettingInterface::GetTrueStateTooltip () const inline private virtual
Definition at line 34 of file ImportantToggleSettingInterface.h.
References FText::GetEmpty().
Field Documentation
const
FName& OutProperty IImportantToggleSettingInterface::const { OutCategory = NAME_None private
Definition at line 28 of file ImportantToggleSettingInterface.h.
OutProperty
IImportantToggleSettingInterface::OutProperty = NAME_None private
Definition at line 28 of file ImportantToggleSettingInterface.h.
The documentation for this class was generated from the following file:
ImportantToggleSettingInterface.h