Unreal Engine 5.6 C++ API: WorldPartitionActorDesc.h File Reference
WorldPartitionActorDesc.h File Reference
#include "CoreMinimal.h"
#include "PropertyPairsMap.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/SoftObjectPath.h"
#include "UObject/TopLevelAssetPath.h"
#include "UObject/WeakObjectPtrTemplates.h"
#include "UObject/WeakObjectPtr.h"
#include "Templates/SubclassOf.h"
#include "Misc/Guid.h"
#include "Misc/TVariant.h"
#include "WorldPartition/WorldPartitionActorDescType.h"
#include "WorldPartition/WorldPartitionActorContainerID.h"
#include "WorldPartition/Filter/WorldPartitionActorFilter.h"
Data Structures
class FWorldPartitionActorDesc
Represents a Actor Metadata (editor-only)
struct FWorldPartitionActorDesc::FContainerInstance
struct FWorldPartitionActorDescInitData
struct FWorldPartitionAssetDataPatcher
struct FWorldPartitionRelativeBounds
Enumerations
enum class EContainerClusterMode : uint8 { Partitioned }
Functions
template<>
bool CompareUnsortedArrays (const TArray< FName > &Array1, const TArray< FName > &Array2)
template<typename T>
bool CompareUnsortedArrays (const TArray< T > &Array1, const TArray< T > &Array2)
template<typename T, class F>
bool CompareUnsortedArrays (const TArray< T > &Array1, const TArray< T > &Array2, F Func)
Enumeration Type Documentation
EContainerClusterMode
enum class EContainerClusterMode : uint8 strong
Enumerator
Partitioned
Definition at line 200 of file WorldPartitionActorDesc.h.
Function Documentation
CompareUnsortedArrays() [1/3]
template<> bool CompareUnsortedArrays (const TArray< FName > & Array1, const TArray< FName > & Array2) inline
Definition at line 226 of file WorldPartitionActorDesc.h.
References A, B, and CompareUnsortedArrays().
CompareUnsortedArrays() [2/3]
template<typename T> bool CompareUnsortedArrays (const TArray< T > & Array1, const TArray< T > & Array2) inline
Definition at line 220 of file WorldPartitionActorDesc.h.
References A, B, and CompareUnsortedArrays().
CompareUnsortedArrays() [3/3]
template<typename T, class F> bool CompareUnsortedArrays (const TArray< T > & Array1, const TArray< T > & Array2, F Func) inline
Definition at line 206 of file WorldPartitionActorDesc.h.
References TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::Sort().
Referenced by CompareUnsortedArrays(), and CompareUnsortedArrays().