Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolItemProxyRegistry Class Reference
UE::SequenceNavigator::FNavigationToolItemProxyRegistry Class Reference
Handles registering a Navigation Tool item type with a Navigation Tool item proxy factory that creates the respective INavigationToolItemProxy.
#include "NavigationToolItemProxyRegistry.h"
Public Member Functions
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type>
INavigationToolItemProxyFactory * GetItemProxyFactory () const
Gets the Item Proxy Factory if it was registered with the Item Proxy Type Name.
INavigationToolItemProxyFactory * GetItemProxyFactory (FName InItemProxyTypeName) const
Gets the Item Proxy Factory for the given Item Proxy Type Name.
void GetRegisteredItemProxyTypeNames (TSet< FName > &OutItemProxyTypeNames) const
Gets all the Item Proxy Type Names that exist in this registry.
template<typename InItemProxyFactoryType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyFactoryType, INavigationToolItemProxyFactory>::IsDerived>::Type, typename... InArgTypes>
void RegisterItemProxyFactory (InArgTypes &&... InArgs)
template<typename InItemProxyType, uint32 InItemProxyPriority = 0, typename InType = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type, typename... InArgTypes>
void RegisterItemProxyWithDefaultFactory ()
Registers an Item Proxy Type with the Default Factory.
void UnregisterAllItemProxyFactories ()
Unregisters all the Item Proxy Factories for this Instance.
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type>
void UnregisterItemProxyFactory ()
Unregisters the given Item Type from having an Item Proxy Factory.
void UnregisterItemProxyFactory (FName InItemProxyTypeName)
Private Attributes
TMap< FName, TSharedRef< INavigationToolItemProxyFactory > > ItemProxyFactories
Map of the item proxy type name and its item proxy factory.
Detailed Description
Handles registering a Navigation Tool item type with a Navigation Tool item proxy factory that creates the respective INavigationToolItemProxy.
See also
INavigationToolItemProxy
Definition at line 20 of file NavigationToolItemProxyRegistry.h.
Member Function Documentation
GetItemProxyFactory() [1/2]
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type> INavigationToolItemProxyFactory * UE::SequenceNavigator::FNavigationToolItemProxyRegistry::GetItemProxyFactory () const inline
Gets the Item Proxy Factory if it was registered with the Item Proxy Type Name.
Returns nullptr if not found
Definition at line 73 of file NavigationToolItemProxyRegistry.h.
References GetItemProxyFactory(), and UE::SequenceNavigator::TNavigationToolItemType< T, bool >::GetTypeId().
Referenced by GetItemProxyFactory().
GetItemProxyFactory() [2/2]
INavigationToolItemProxyFactory * UE::SequenceNavigator::FNavigationToolItemProxyRegistry::GetItemProxyFactory (FName InItemProxyTypeName) const inline
Gets the Item Proxy Factory for the given Item Proxy Type Name.
Returns nullptr if not found
Definition at line 62 of file NavigationToolItemProxyRegistry.h.
References ItemProxyFactories.
Referenced by UE::SequenceNavigator::INavigationTool::GetItemProxyFactory().
GetRegisteredItemProxyTypeNames()
void UE::SequenceNavigator::FNavigationToolItemProxyRegistry::GetRegisteredItemProxyTypeNames (TSet< FName > & OutItemProxyTypeNames) const inline
Gets all the Item Proxy Type Names that exist in this registry.
Definition at line 79 of file NavigationToolItemProxyRegistry.h.
References ItemProxyFactories.
RegisterItemProxyFactory()
template<typename InItemProxyFactoryType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyFactoryType, INavigationToolItemProxyFactory>::IsDerived>::Type, typename... InArgTypes> void UE::SequenceNavigator::FNavigationToolItemProxyRegistry::RegisterItemProxyFactory (InArgTypes &&... InArgs) inline
Definition at line 26 of file NavigationToolItemProxyRegistry.h.
References Forward(), ItemProxyFactories, and MakeShared().
Referenced by RegisterItemProxyWithDefaultFactory().
RegisterItemProxyWithDefaultFactory()
template<typename InItemProxyType, uint32 InItemProxyPriority = 0, typename InType = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type, typename... InArgTypes> void UE::SequenceNavigator::FNavigationToolItemProxyRegistry::RegisterItemProxyWithDefaultFactory () inline
Registers an Item Proxy Type with the Default Factory.
Definition at line 38 of file NavigationToolItemProxyRegistry.h.
References RegisterItemProxyFactory().
UnregisterAllItemProxyFactories()
void UE::SequenceNavigator::FNavigationToolItemProxyRegistry::UnregisterAllItemProxyFactories () inline
Unregisters all the Item Proxy Factories for this Instance.
Definition at line 56 of file NavigationToolItemProxyRegistry.h.
References ItemProxyFactories.
UnregisterItemProxyFactory() [1/2]
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type> void UE::SequenceNavigator::FNavigationToolItemProxyRegistry::UnregisterItemProxyFactory () inline
Unregisters the given Item Type from having an Item Proxy Factory.
Definition at line 45 of file NavigationToolItemProxyRegistry.h.
References UE::SequenceNavigator::TNavigationToolItemType< T, bool >::GetTypeId(), and ItemProxyFactories.
UnregisterItemProxyFactory() [2/2]
void UE::SequenceNavigator::FNavigationToolItemProxyRegistry::UnregisterItemProxyFactory (FName InItemProxyTypeName) inline
Definition at line 50 of file NavigationToolItemProxyRegistry.h.
References ItemProxyFactories.
Field Documentation
ItemProxyFactories
TMap<FName, TSharedRef<INavigationToolItemProxyFactory> > UE::SequenceNavigator::FNavigationToolItemProxyRegistry::ItemProxyFactories private
Map of the item proxy type name and its item proxy factory.
Definition at line 86 of file NavigationToolItemProxyRegistry.h.
Referenced by GetItemProxyFactory(), GetRegisteredItemProxyTypeNames(), RegisterItemProxyFactory(), UnregisterAllItemProxyFactories(), UnregisterItemProxyFactory(), and UnregisterItemProxyFactory().
The documentation for this class was generated from the following file:
NavigationToolItemProxyRegistry.h