Unreal Engine 5.6 C++ API: UE::MovieScene::FErasedReadAccess Struct Reference
UE::MovieScene::FErasedReadAccess Struct Reference
#include "MovieSceneComponentAccessors.h"
Public Member Functions
FErasedReadAccess (FComponentTypeID InComponentTypeID)
FORCEINLINE FComponentReader LockComponentData (const FEntityAllocation *Allocation, FEntityAllocationWriteContext WriteContext) const
FORCEINLINE void PreLockComponentData (const FEntityAllocation *Allocation, FPreLockedDataPtr *PrelockedComponentData) const
FORCEINLINE FReadErased ResolvePreLockedComponentData (const FEntityAllocation *Allocation, const FPreLockedDataPtr *Ptr, FEntityAllocationWriteContext WriteContext) const
Public Member Functions inherited from UE::MovieScene::FReadAccess
FReadAccess (FComponentTypeID InComponentType)
Public Member Functions inherited from UE::MovieScene::FComponentAccess
FORCEINLINE void PreLockComponentData (const FEntityAllocation *Allocation, FPreLockedDataPtr *PrelockedComponentData) const
Static Public Attributes
static constexpr int32 PreLockedDataNum = 1
Additional Inherited Members
Data Fields inherited from UE::MovieScene::FComponentAccess
FComponentTypeID ComponentType
Detailed Description
Definition at line 162 of file MovieSceneComponentAccessors.h.
Constructor & Destructor Documentation
FErasedReadAccess()
UE::MovieScene::FErasedReadAccess::FErasedReadAccess (FComponentTypeID InComponentTypeID) inline
Definition at line 166 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FReadAccess::FReadAccess().
Member Function Documentation
LockComponentData()
FORCEINLINE FComponentReader UE::MovieScene::FErasedReadAccess::LockComponentData (const FEntityAllocation * Allocation, FEntityAllocationWriteContext WriteContext) const inline
Definition at line 181 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FComponentAccess::ComponentType, and FORCEINLINE.
PreLockComponentData()
FORCEINLINE void UE::MovieScene::FErasedReadAccess::PreLockComponentData (const FEntityAllocation * Allocation, FPreLockedDataPtr * PrelockedComponentData) const inline
Definition at line 170 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FComponentAccess::ComponentType, FORCEINLINE, Header, and TRelativePtr< T, OffsetType >::Reset().
ResolvePreLockedComponentData()
FORCEINLINE FReadErased UE::MovieScene::FErasedReadAccess::ResolvePreLockedComponentData (const FEntityAllocation * Allocation, const FPreLockedDataPtr * Ptr, FEntityAllocationWriteContext WriteContext) const inline
Definition at line 176 of file MovieSceneComponentAccessors.h.
References FORCEINLINE, and TRelativePtr< T, OffsetType >::Resolve().
Field Documentation
PreLockedDataNum
int32 UE::MovieScene::FErasedReadAccess::PreLockedDataNum = 1 static constexpr
Definition at line 164 of file MovieSceneComponentAccessors.h.
The documentation for this struct was generated from the following file:
MovieSceneComponentAccessors.h