Unreal Engine 5.6 C++ API: FStreamableDownloadCachePin Struct Reference
FStreamableDownloadCachePin Struct Reference
Handle that pins downloaded packages in the local cache, may be shared between requests.
#include "StreamableManager.h"
Public Member Functions
FStreamableDownloadCachePin ()
~FStreamableDownloadCachePin ()
FString GetDebugName () const
bool IsValid () const
operator bool () const
bool operator== (FStreamableDownloadCachePin &Other) const
void Release ()
Static Public Member Functions
template<typename DebugNameType = UE::FSourceLocation>
static FStreamableDownloadCachePin Create (DebugNameType &&DebugNameOrLocation)
Private Attributes
UE::IoStore::FOnDemandContentHandle ContentHandle
Friends
struct UE::StreamableManager::Private::FDownloadContext
Detailed Description
Handle that pins downloaded packages in the local cache, may be shared between requests.
Definition at line 88 of file StreamableManager.h.
Constructor & Destructor Documentation
FStreamableDownloadCachePin()
FStreamableDownloadCachePin::FStreamableDownloadCachePin ()
Referenced by Create(), and operator==().
~FStreamableDownloadCachePin()
FStreamableDownloadCachePin::~FStreamableDownloadCachePin ()
Member Function Documentation
Create()
template<typename DebugNameType = UE::FSourceLocation> FStreamableDownloadCachePin FStreamableDownloadCachePin::Create (DebugNameType && DebugNameOrLocation) inline static
Definition at line 94 of file StreamableManager.h.
References FStreamableDownloadCachePin(), UE::SourceLocation::FileAndLine(), Forward(), and ToString().
GetDebugName()
FString FStreamableDownloadCachePin::GetDebugName () const
IsValid()
bool FStreamableDownloadCachePin::IsValid () const
Referenced by operator bool().
operator bool()
FStreamableDownloadCachePin::operator bool () const inline
Definition at line 115 of file StreamableManager.h.
References IsValid().
operator==()
bool FStreamableDownloadCachePin::operator== (FStreamableDownloadCachePin & Other) const
References FStreamableDownloadCachePin(), and Other.
Release()
void FStreamableDownloadCachePin::Release ()
Friends And Related Symbol Documentation
UE::StreamableManager::Private::FDownloadContext
friend struct UE::StreamableManager::Private::FDownloadContext friend
Definition at line 119 of file StreamableManager.h.
References UE::StreamableManager::Private::FDownloadContext.
Referenced by UE::StreamableManager::Private::FDownloadContext.
Field Documentation
ContentHandle
UE::IoStore::FOnDemandContentHandle FStreamableDownloadCachePin::ContentHandle private
Definition at line 118 of file StreamableManager.h.
The documentation for this struct was generated from the following file:
StreamableManager.h