Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... > Struct Template Reference
UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... > Struct Template Reference
#include "MovieSceneEntityBuilder.h"
Public Member Functions
template<typename U, typename PayloadType>
TEntityBuilder< T..., TAdd< U > > Add (TComponentTypeID< U > ComponentType, PayloadType &&InPayload)
Add a component to the entity with a specific value.
template<typename U, typename PayloadType>
TEntityBuilder< T..., TAddConditional< U > > AddConditional (TComponentTypeID< U > ComponentType, PayloadType &&InPayload, bool bCondition)
Conditionally add a component to the entity with a specific value.
TEntityBuilder< T..., FAdd > AddDefaulted (FComponentTypeID ComponentType)
Add the specified default-constructed component type to the entity.
TEntityBuilder< T..., FAddConditional > AddDefaultedConditional (FComponentTypeID ComponentType, bool bCondition)
Add the specified default-constructed component to the entity if a condition is met.
TEntityBuilder< T..., FAddMany > AddMany (const FComponentMask &InComponentsToAdd)
Add all the specified default-constructed component type to the entity.
TEntityBuilder< T... > AddMutualComponents ()
Add any mutual components defined by the entity factory.
TEntityBuilder< T..., FAdd > AddTag (FComponentTypeID TagType)
Add the specified tag to the entity.
TEntityBuilder< T..., FAddConditional > AddTagConditional (FComponentTypeID TagType, bool bCondition)
Add the specified tag to the entity.
template<typename U>
TEntityBuilder< T..., U > Append (U &&InOther)
Append another component type to this builder.
virtual FMovieSceneEntityID Create (FEntityManager *EntityManager) override final
FMovieSceneEntityID CreateEntity (FEntityManager *EntityManager, FComponentMask NewType=FComponentMask())
Create a new entity using this builder's definition by moving the payload components into the new entity.
void CreateOrUpdate (FEntityManager *EntityManager, FMovieSceneEntityID &InOutEntityID, const FTypelessMutation &Base=FTypelessMutation().RemoveAll())
Mutate an existing entity using this instance's payload and an additional mask of components.
virtual void GenerateType (FEntityManager *EntityManager, FComponentMask &OutMask, bool &OutAddMutualComponents) override final
virtual void Initialize (FEntityManager *EntityManager, const FEntityInfo &Entity) override final
void MutateExisting (FEntityManager *EntityManager, FMovieSceneEntityID EntityID, const FTypelessMutation &Base=FTypelessMutation())
Mutate an existing entity using this instance's payload and an additional mask of components.
void ReplaceEntity (FEntityManager *EntityManager, FMovieSceneEntityID &InOutEntityID, FComponentMask NewType=FComponentMask())
Replace the components of an entity with this builder's definition.
Public Member Functions inherited from UE::MovieScene::IEntityBuilder
virtual ~IEntityBuilder ()
Protected Member Functions
TEntityBuilderImpl (T &&... InArgs, bool bInAddMutualComponents)
Protected Attributes
bool bAddMutualComponents
TTuple< T... > Payload
Payload data.
Detailed Description
template<typename... T, int... Indices>
struct UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >
Definition at line 205 of file MovieSceneEntityBuilder.h.
Constructor & Destructor Documentation
TEntityBuilderImpl()
template<typename... T, int... Indices> UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::TEntityBuilderImpl (T &&... InArgs, bool bInAddMutualComponents) inline protected
Definition at line 413 of file MovieSceneEntityBuilder.h.
References bAddMutualComponents, MoveTemp(), and Payload.
Referenced by Add(), AddConditional(), AddDefaulted(), AddDefaultedConditional(), AddMany(), AddMutualComponents(), AddTag(), AddTagConditional(), and Append().
Member Function Documentation
Add()
template<typename... T, int... Indices> template<typename U, typename PayloadType> TEntityBuilder< T..., TAdd< U > > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Add (TComponentTypeID< U > ComponentType, PayloadType && InPayload)
Add a component to the entity with a specific value.
Parameters
ComponentType The component type ID to add to the entity. Must be valid.
InPayload User-specified data to forward into the component
Returns
A new builder that includes the new component and payload
Definition at line 630 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), bAddMutualComponents, Forward(), MoveTemp(), and Payload.
AddConditional()
template<typename... T, int... Indices> template<typename U, typename PayloadType> TEntityBuilder< T..., TAddConditional< U > > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddConditional (TComponentTypeID< U > ComponentType, PayloadType && InPayload, bool bCondition)
Conditionally add a component to the entity with a specific value.
Parameters
ComponentType The component type ID to add to the entity. Must be valid if bCondition is true.
InPayload User-specified data to forward into the component
bCondition Condition specifying whether this component should be added or not
Returns
A new builder that includes the new component and payload
Definition at line 637 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), AddConditional(), bAddMutualComponents, Forward(), MoveTemp(), and Payload.
Referenced by AddConditional().
AddDefaulted()
template<typename... T, int... Indices> TEntityBuilder< T..., FAdd > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddDefaulted (FComponentTypeID ComponentType)
Add the specified default-constructed component type to the entity.
Parameters
ComponentType A valid component type or tag ID to add. Must be valid.
Returns
A new builder that includes the new component
Definition at line 611 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), AddDefaulted(), bAddMutualComponents, MoveTemp(), and Payload.
Referenced by AddDefaulted().
AddDefaultedConditional()
template<typename... T, int... Indices> TEntityBuilder< T..., FAddConditional > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddDefaultedConditional (FComponentTypeID ComponentType, bool bCondition)
Add the specified default-constructed component to the entity if a condition is met.
Parameters
ComponentType A valid component type ID to add. Must be valid.
bCondition Condition specifying whether this tag should be added or not
Returns
A new builder that includes the new component
Definition at line 643 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), AddDefaultedConditional(), bAddMutualComponents, MoveTemp(), and Payload.
Referenced by AddDefaultedConditional().
AddMany()
template<typename... T, int... Indices> TEntityBuilder< T..., FAddMany > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddMany (const FComponentMask & InComponentsToAdd)
Add all the specified default-constructed component type to the entity.
Parameters
InComponentsToAdd A (possibly empty) component mask that defines all the components to add
Returns
A new builder that includes the new component
Definition at line 617 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), AddMany(), and bAddMutualComponents.
Referenced by AddMany().
AddMutualComponents()
template<typename... T, int... Indices> TEntityBuilder< T... > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddMutualComponents ()
Add any mutual components defined by the entity factory.
Definition at line 662 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), AddMutualComponents(), MoveTemp(), and Payload.
Referenced by AddMutualComponents().
AddTag()
template<typename... T, int... Indices> TEntityBuilder< T..., FAdd > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddTag (FComponentTypeID TagType)
Add the specified tag to the entity.
Equivalent to AddDefaulted.
Parameters
Tag A valid component tag ID to add. Must be valid.
Returns
A new builder that includes the new component
Definition at line 623 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), AddTag(), bAddMutualComponents, MoveTemp(), and Payload.
Referenced by AddTag().
AddTagConditional()
template<typename... T, int... Indices> TEntityBuilder< T..., FAddConditional > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::AddTagConditional (FComponentTypeID TagType, bool bCondition)
Add the specified tag to the entity.
Equivalent to AddDefaulted.
Parameters
Tag A valid component tag ID to add. Must be valid.
bCondition Condition specifying whether this tag should be added or not
Returns
A new builder that includes the new component
Definition at line 649 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), AddTagConditional(), bAddMutualComponents, MoveTemp(), and Payload.
Referenced by AddTagConditional().
Append()
template<typename... T, int... Indices> template<typename U> TEntityBuilder< T..., U > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Append (U && InOther)
Append another component type to this builder.
Returns
A new builder that includes the new component
Definition at line 656 of file MovieSceneEntityBuilder.h.
References TEntityBuilderImpl(), bAddMutualComponents, MoveTemp(), and Payload.
Create()
template<typename... T, int... Indices> virtual FMovieSceneEntityID UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Create (FEntityManager * EntityManager) inline final override virtual
Implements UE::MovieScene::IEntityBuilder.
Definition at line 207 of file MovieSceneEntityBuilder.h.
References CreateEntity().
CreateEntity()
template<typename... T, int... Indices> FMovieSceneEntityID UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::CreateEntity (FEntityManager * EntityManager, FComponentMask NewType = FComponentMask()) inline
Create a new entity using this builder's definition by moving the payload components into the new entity.
Note
Will invalidate this instance of TEntityBuilder so its payload cannot be used again.
Parameters
EntityManager The entity manager to create the entity within. All component types must relate to this class.
NewType (Optional) An additional base type to use for the new entity. Any component types not stored by this builder will be default-constructed.
Returns
The created entity's ID
Definition at line 238 of file MovieSceneEntityBuilder.h.
References UE::MovieScene::FMutualComponentInitializers::Execute(), GenerateType(), and Initialize.
Referenced by Create(), CreateOrUpdate(), and ReplaceEntity().
CreateOrUpdate()
template<typename... T, int... Indices> void UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::CreateOrUpdate (FEntityManager * EntityManager, FMovieSceneEntityID & InOutEntityID, const FTypelessMutation & Base = FTypelessMutation().RemoveAll()) inline
Mutate an existing entity using this instance's payload and an additional mask of components.
Note
Will invalidate this instance of TEntityBuilder so its payload cannot be used again.
Parameters
EntityManager The entity manager that houses EntityID. All component types must relate to this class.
EntityID The entity to mutate
Base (Optional) An additional base mutation to apply while modifying this entity
Definition at line 321 of file MovieSceneEntityBuilder.h.
References CreateEntity(), and MutateExisting().
GenerateType()
template<typename... T, int... Indices> virtual void UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::GenerateType (FEntityManager * EntityManager, FComponentMask & OutMask, bool & OutAddMutualComponents) inline final override virtual
Implements UE::MovieScene::IEntityBuilder.
Definition at line 212 of file MovieSceneEntityBuilder.h.
References bAddMutualComponents, Payload, and VisitTupleElements().
Referenced by CreateEntity().
Initialize()
template<typename... T, int... Indices> virtual void UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Initialize (FEntityManager * EntityManager, const FEntityInfo & Entity) inline final override virtual
Implements UE::MovieScene::IEntityBuilder.
Definition at line 222 of file MovieSceneEntityBuilder.h.
References Payload, and VisitTupleElements().
MutateExisting()
template<typename... T, int... Indices> void UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::MutateExisting (FEntityManager * EntityManager, FMovieSceneEntityID EntityID, const FTypelessMutation & Base = FTypelessMutation()) inline
Mutate an existing entity using this instance's payload and an additional mask of components.
Note
Will invalidate this instance of TEntityBuilder so its payload cannot be used again.
Parameters
EntityManager The entity manager that houses EntityID. All component types must relate to this class.
EntityID The entity to mutate
Base (Optional) An additional base mutation to apply while modifying this entity
Definition at line 283 of file MovieSceneEntityBuilder.h.
References bAddMutualComponents, UE::MovieScene::FComponentMask::CompareSetBits(), Payload, and VisitTupleElements().
Referenced by CreateOrUpdate().
ReplaceEntity()
template<typename... T, int... Indices> void UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::ReplaceEntity (FEntityManager * EntityManager, FMovieSceneEntityID & InOutEntityID, FComponentMask NewType = FComponentMask()) inline
Replace the components of an entity with this builder's definition.
Note
Will invalidate this instance of TEntityBuilder so its payload cannot be used again.
Parameters
EntityManager The entity manager that houses EntityID. All component types must relate to this class.
EntityID The entity ID to replace
NewType (Optional) An additional base type to use for the new entity. Any component types not stored by this builder will be default-constructed.
Definition at line 268 of file MovieSceneEntityBuilder.h.
References CreateEntity().
Field Documentation
bAddMutualComponents
template<typename... T, int... Indices> bool UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::bAddMutualComponents protected
Definition at line 421 of file MovieSceneEntityBuilder.h.
Referenced by TEntityBuilderImpl(), Add(), AddConditional(), AddDefaulted(), AddDefaultedConditional(), AddMany(), AddTag(), AddTagConditional(), Append(), GenerateType(), and MutateExisting().
Payload
template<typename... T, int... Indices> TTuple< T... > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Payload protected
Payload data.
Definition at line 419 of file MovieSceneEntityBuilder.h.
Referenced by TEntityBuilderImpl(), Add(), AddConditional(), AddDefaulted(), AddDefaultedConditional(), AddMutualComponents(), AddTag(), AddTagConditional(), Append(), GenerateType(), Initialize(), and MutateExisting().
The documentation for this struct was generated from the following file:
MovieSceneEntityBuilder.h