Unreal Engine 5.6 C++ API: UEnvQueryGenerator_Donut Class Reference
UEnvQueryGenerator_Donut Class Reference
#include "EnvQueryGenerator_Donut.h"
Protected Member Functions
AIMODULE_API bool GenerateDonutNavPoints (const TArray< FVector > &CenterPoints, TArray< FNavLocation > &Points, FEnvQueryInstance &QueryInstance) const
AIMODULE_API FVector::FReal GetArcBisectorAngle (FEnvQueryInstance &QueryInstance) const
AIMODULE_API bool IsAngleAllowed (FVector::FReal TestAngleRad, FVector::FReal BisectAngleDeg, FVector::FReal AngleRangeDeg, bool bConstrainAngle) const
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() FAIDataProviderFloatValue InnerRadius
min distance between point and context
UPROPERTY()) uint32 bDefineArc virtual AIMODULE_API void GenerateItems (FEnvQueryInstance &QueryInstance) const override
virtual AIMODULE_API FText GetDescriptionDetails () const override
virtual AIMODULE_API FText GetDescriptionTitle () const override
virtual AIMODULE_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
UPROPERTY () bool bUseSpiralPattern
If true, the rings of the wheel will be rotated in a spiral pattern.
UPROPERTY () FAIDataProviderFloatValue ArcAngle
If you generate items on a piece of circle you define angle of Arc cut here.
UPROPERTY () FAIDataProviderFloatValue OuterRadius
max distance between point and context
UPROPERTY () FAIDataProviderIntValue NumberOfRings
number of rings to generate
UPROPERTY () FAIDataProviderIntValue PointsPerRing
number of items to generate for each ring
UPROPERTY () TSubclassOf< class UEnvQueryContext > Center
context
UPROPERTY ()) FEnvDirection ArcDirection
If you generate items on a piece of circle you define direction of Arc cut here.
Detailed Description
Definition at line 14 of file EnvQueryGenerator_Donut.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UEnvQueryGenerator_Donut::GENERATED_UCLASS_BODY () private
min distance between point and context
References Category, and UPROPERTY().
GenerateDonutNavPoints()
AIMODULE_API bool UEnvQueryGenerator_Donut::GenerateDonutNavPoints (const TArray< FVector > & CenterPoints, TArray< FNavLocation > & Points, FEnvQueryInstance & QueryInstance) const protected
References Points.
GenerateItems()
UPROPERTY()) uint32 bDefineArc virtual AIMODULE_API void UEnvQueryGenerator_Donut::GenerateItems (FEnvQueryInstance & QueryInstance) const override private virtual
References GenerateItems().
Referenced by GenerateItems().
GetArcBisectorAngle()
AIMODULE_API FVector::FReal UEnvQueryGenerator_Donut::GetArcBisectorAngle (FEnvQueryInstance & QueryInstance) const protected
GetDescriptionDetails()
virtual AIMODULE_API FText UEnvQueryGenerator_Donut::GetDescriptionDetails () const override private virtual
References GetDescriptionDetails().
Referenced by GetDescriptionDetails().
GetDescriptionTitle()
virtual AIMODULE_API FText UEnvQueryGenerator_Donut::GetDescriptionTitle () const override private virtual
References GetDescriptionTitle().
Referenced by GetDescriptionTitle().
IsAngleAllowed()
AIMODULE_API bool UEnvQueryGenerator_Donut::IsAngleAllowed (FVector::FReal TestAngleRad, FVector::FReal BisectAngleDeg, FVector::FReal AngleRangeDeg, bool bConstrainAngle) const protected
PostEditChangeProperty()
virtual AIMODULE_API void UEnvQueryGenerator_Donut::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override private virtual
UPROPERTY() [1/7]
UEnvQueryGenerator_Donut::UPROPERTY () private
If true, the rings of the wheel will be rotated in a spiral pattern.
If false, they will all be at a zero rotation, looking more like the spokes on a wheel.
References Category, and UPROPERTY().
UPROPERTY() [2/7]
UEnvQueryGenerator_Donut::UPROPERTY () private
If you generate items on a piece of circle you define angle of Arc cut here.
References Category, and UPROPERTY().
UPROPERTY() [3/7]
UEnvQueryGenerator_Donut::UPROPERTY () private
max distance between point and context
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [4/7]
UEnvQueryGenerator_Donut::UPROPERTY () private
number of rings to generate
References Category, and UPROPERTY().
UPROPERTY() [5/7]
UEnvQueryGenerator_Donut::UPROPERTY () private
number of items to generate for each ring
References Category, and UPROPERTY().
UPROPERTY() [6/7]
UEnvQueryGenerator_Donut::UPROPERTY () private
context
References Category, meta, and UPROPERTY().
UPROPERTY() [7/7]
UEnvQueryGenerator_Donut::UPROPERTY () private
If you generate items on a piece of circle you define direction of Arc cut here.
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
EnvQueryGenerator_Donut.h