Unreal Engine 5.6 C++ API: UE::Sequencer::FSectionModel Class Reference
UE::Sequencer::FSectionModel Class Reference
Model for a sequencer section.
#include "SectionModel.h"
Public Member Functions
FSectionModel ()
~FSectionModel ()
void AddToSnapField (const ISnapCandidate &Candidate, ISnapField &SnapField) const override
FTrackLaneVirtualAlignment ArrangeVirtualTrackLaneView () const override
bool CanDrag () const override
Returns whether the model can be dragged.
TSharedPtr< ITrackLaneWidget > CreateTrackLaneView (const FCreateTrackLaneViewParams &InParams) override
DECLARE_MULTICAST_DELEGATE_OneParam (FOnModelUpdated, FSectionModel *) UE_DEPRECATED(5.5
const UMovieSceneCondition * GetCondition () const override
EConditionableConditionState GetConditionState () const override
Returns condition state for this item.
TArray< FOverlappingSections > GetEasingSegments ()
Gets an array of sections whose easing bounds underlap the specified section.
TRange< FFrameNumber > GetLayerBarRange () const override
virtual UObject * GetObject () const override
TViewModelPtr< ITrackExtension > GetParentTrackExtension () const
Gets the parent track or track row model as an ITrackExtension.
TViewModelPtr< ITrackExtension > GetParentTrackModel () const
Gets the parent track or track row model.
int32 GetPostRollFrames () const
int32 GetPreRollFrames () const
TRange< FFrameNumber > GetRange () const
Gets the time range of the section.
UMovieSceneSection * GetSection () const
Gets the section object.
TSharedPtr< ISequencerSection > GetSectionInterface () const
Gets the section interface.
TArray< FOverlappingSections > GetUnderlappingSections ()
Gets an array of sections that underlap the specified section.
virtual void InitializeObject (TWeakObjectPtr<> InWeakObject) override
void InitializeSection (TSharedPtr< ISequencerSection > InSectionInterface)
ESelectionIntent IsSelectable () const override
bool NeedsLayout () const
Returns whether this section model needs to be rebuilt, ie.
void OffsetLayerBar (FFrameNumber Amount) override
void OnBeginDrag (IDragOperation &DragOperation) override
Called at the beginning of the drag operation.
EStretchResult OnBeginStretch (const IStretchOperation &StretchOperation, const FStretchScreenParameters &ScreenParameters, FStretchParameters *InOutParameters) override
void OnEndDrag (IDragOperation &DragOperation) override
Called at the end of a drag operation.
void OnEndStretch (const IStretchOperation &StretchOperation, const FStretchScreenParameters &ScreenParameters, FStretchParameters *InOutParameters) override
void OnInitiateStretch (IStretchOperation &StretchOperation, EStretchConstraint Constraint, FStretchParameters *InOutGlobalParameters) override
void OnModifiedDirectly (UMovieSceneSignedObject *) override
void OnRowChanged (UMovieSceneSection *) override
void OnStretch (const IStretchOperation &StretchOperation, const FStretchScreenParameters &ScreenParameters, FStretchParameters *InOutParameters) override
void SetConditionEditorForceTrue (bool bEditorForceTrue) override
Set this item's condition to evaluate true for editor preview purposes.
void SetLayoutChannelProxy (TWeakPtr< FMovieSceneChannelProxy > InPreviousLayoutChannelProxy)
Set the channel proxy that was most recently used to layout this section model.
void SetLayoutRowIndex (int32 InRowIndex)
Set the row index that was most recently used to layout this section model.
UE_SEQUENCER_DECLARE_CASTABLE (FSectionModel, FViewModel, FLinkedOutlinerExtension, IObjectModelExtension, ILayerBarExtension, ITrackLaneExtension, ISelectableExtension, ISnappableExtension, IDraggableTrackAreaExtension, IStretchableExtension, IConditionableExtension)
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Public Member Functions inherited from UE::Sequencer::FLinkedOutlinerExtension
FLinkedOutlinerExtension ()
TViewModelPtr< IOutlinerExtension > GetLinkedOutlinerItem () const
void SetLinkedOutlinerItem (const TViewModelPtr< IOutlinerExtension > &InOutlinerItem)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (FLinkedOutlinerExtension)
Public Member Functions inherited from UE::Sequencer::IObjectModelExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IObjectModelExtension) virtual ~IObjectModelExtension()
Public Member Functions inherited from UE::Sequencer::ILayerBarExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ILayerBarExtension) virtual ~ILayerBarExtension()
Public Member Functions inherited from UE::Sequencer::ITrackLaneExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ITrackLaneExtension) virtual ~ITrackLaneExtension()
Public Member Functions inherited from UE::Sequencer::ISelectableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISelectableExtension) virtual ~ISelectableExtension()
Public Member Functions inherited from UE::Sequencer::ISnappableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISnappableExtension) virtual ~ISnappableExtension()
Public Member Functions inherited from UE::Sequencer::IDraggableTrackAreaExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDraggableTrackAreaExtension) virtual ~IDraggableTrackAreaExtension()
Public Member Functions inherited from UE::Sequencer::IStretchableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IStretchableExtension) virtual ~IStretchableExtension()
Public Member Functions inherited from UE::Sequencer::IConditionableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IConditionableExtension) virtual ~IConditionableExtension()
Public Member Functions inherited from TIntrusiveLinkedList< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > >
TIntrusiveLinkedList ()
Default constructor (empty list).
Public Member Functions inherited from TLinkedListBase< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveLinkedListIterator >
TLinkedListBase ()
Default constructor (empty list)
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > * GetNextLink () const
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > ** GetPrevLink () const
FORCEINLINE bool IsLinked ()
Returns whether element is currently linked.
FORCEINLINE void LinkAfter (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *After)
Adds this element to the linked list, after the specified element.
FORCEINLINE void LinkBefore (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *Before)
Adds this element to a list, before the given element.
FORCEINLINE void LinkHead (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *&Head)
Adds this element as the head of the linked list, linking the input Head pointer to this element, so that when the element is linked/unlinked, the Head linked list pointer will be correctly updated.
FORCEINLINE void LinkReplace (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *Replace)
Adds this element to the linked list, replacing the specified element.
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > * Next ()
FORCEINLINE void Unlink ()
Removes this element from the list in constant time.
Public Member Functions inherited from UE::MovieScene::ISignedObjectEventHandler
virtual void OnModifiedIndirectly (UMovieSceneSignedObject *)
virtual void OnPostUndo ()
Public Member Functions inherited from TIntrusiveLinkedList< TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > >
TIntrusiveLinkedList ()
Default constructor (empty list).
Public Member Functions inherited from TLinkedListBase< TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler >, TIntrusiveLinkedListIterator >
TLinkedListBase ()
Default constructor (empty list)
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > * GetNextLink () const
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > ** GetPrevLink () const
FORCEINLINE bool IsLinked ()
Returns whether element is currently linked.
FORCEINLINE void LinkAfter (TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > *After)
Adds this element to the linked list, after the specified element.
FORCEINLINE void LinkBefore (TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > *Before)
Adds this element to a list, before the given element.
FORCEINLINE void LinkHead (TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > *&Head)
Adds this element as the head of the linked list, linking the input Head pointer to this element, so that when the element is linked/unlinked, the Head linked list pointer will be correctly updated.
FORCEINLINE void LinkReplace (TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > *Replace)
Adds this element to the linked list, replacing the specified element.
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > * Next ()
FORCEINLINE void Unlink ()
Removes this element from the list in constant time.
Public Member Functions inherited from UE::MovieScene::ISectionEventHandler
virtual void OnDecorationAdded (UObject *AddedDecoration)
virtual void OnDecorationRemoved (UObject *RemovedDecoration)
Data Fields
This member is no longer please subscribe to UMovieSceneSignedObject::OnModifiedDirectly FOnModelUpdated OnUpdated
This member is no longer supported
Private Member Functions
void UpdateCachedData ()
Private Attributes
FViewModelListHead ChannelList
TRange< FFrameNumber > LayerBarRange
TWeakPtr< FMovieSceneChannelProxy > PreviousLayoutChannelProxy
int32 PreviousLayoutRowIndex = -1
TSharedPtr< ISequencerSection > SectionInterface
TRange< FFrameNumber > SectionRange
TWeakObjectPtr< UMovieSceneSection > WeakSection
Additional Inherited Members
Public Types inherited from TLinkedListBase< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveLinkedListIterator >
typedef TIntrusiveLinkedListIterator< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, const TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > > TConstIterator
typedef TIntrusiveLinkedListIterator< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > > TIterator
Used to iterate over the elements of a linked list.
Public Types inherited from TLinkedListBase< TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler >, TIntrusiveLinkedListIterator >
typedef TIntrusiveLinkedListIterator< TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler >, const TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > > TConstIterator
typedef TIntrusiveLinkedListIterator< TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler > > TIterator
Used to iterate over the elements of a linked list.
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Protected Member Functions inherited from UE::MovieScene::TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >
virtual ~TIntrusiveEventHandler ()
Protected Member Functions inherited from UE::MovieScene::TIntrusiveEventHandler< UE::MovieScene::ISectionEventHandler >
virtual ~TIntrusiveEventHandler ()
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Detailed Description
Model for a sequencer section.
Definition at line 39 of file SectionModel.h.
Constructor & Destructor Documentation
FSectionModel()
UE::Sequencer::FSectionModel::FSectionModel ()
References FSectionModel().
Referenced by FSectionModel(), ~FSectionModel(), DECLARE_MULTICAST_DELEGATE_OneParam(), and UE_SEQUENCER_DECLARE_CASTABLE().
~FSectionModel()
UE::Sequencer::FSectionModel::~FSectionModel ()
References FSectionModel().
Member Function Documentation
AddToSnapField()
void UE::Sequencer::FSectionModel::AddToSnapField (const ISnapCandidate & Candidate, ISnapField & SnapField) const override virtual
Implements UE::Sequencer::ISnappableExtension.
ArrangeVirtualTrackLaneView()
FTrackLaneVirtualAlignment UE::Sequencer::FSectionModel::ArrangeVirtualTrackLaneView () const override virtual
Implements UE::Sequencer::ITrackLaneExtension.
CanDrag()
bool UE::Sequencer::FSectionModel::CanDrag () const override virtual
Returns whether the model can be dragged.
Implements UE::Sequencer::IDraggableTrackAreaExtension.
CreateTrackLaneView()
TSharedPtr< ITrackLaneWidget > UE::Sequencer::FSectionModel::CreateTrackLaneView (const FCreateTrackLaneViewParams & InParams) override virtual
Implements UE::Sequencer::ITrackLaneExtension.
DECLARE_MULTICAST_DELEGATE_OneParam()
UE::Sequencer::FSectionModel::DECLARE_MULTICAST_DELEGATE_OneParam (FOnModelUpdated , FSectionModel *)
References FSectionModel().
GetCondition()
const UMovieSceneCondition * UE::Sequencer::FSectionModel::GetCondition () const override virtual
Implements UE::Sequencer::IConditionableExtension.
GetConditionState()
EConditionableConditionState UE::Sequencer::FSectionModel::GetConditionState () const override virtual
Returns condition state for this item.
Implements UE::Sequencer::IConditionableExtension.
GetEasingSegments()
TArray< FOverlappingSections > UE::Sequencer::FSectionModel::GetEasingSegments ()
Gets an array of sections whose easing bounds underlap the specified section.
References GetEasingSegments().
Referenced by GetEasingSegments().
GetLayerBarRange()
TRange< FFrameNumber > UE::Sequencer::FSectionModel::GetLayerBarRange () const override virtual
Implements UE::Sequencer::ILayerBarExtension.
GetObject()
virtual UObject * UE::Sequencer::FSectionModel::GetObject () const override virtual
Implements UE::Sequencer::IObjectModelExtension.
GetParentTrackExtension()
TViewModelPtr< ITrackExtension > UE::Sequencer::FSectionModel::GetParentTrackExtension () const
Gets the parent track or track row model as an ITrackExtension.
References GetParentTrackExtension().
Referenced by GetParentTrackExtension().
GetParentTrackModel()
TViewModelPtr< ITrackExtension > UE::Sequencer::FSectionModel::GetParentTrackModel () const
Gets the parent track or track row model.
References GetParentTrackModel().
Referenced by GetParentTrackModel().
GetPostRollFrames()
int32 UE::Sequencer::FSectionModel::GetPostRollFrames () const
References GetPostRollFrames().
Referenced by GetPostRollFrames().
GetPreRollFrames()
int32 UE::Sequencer::FSectionModel::GetPreRollFrames () const
References GetPreRollFrames().
Referenced by GetPreRollFrames().
GetRange()
TRange< FFrameNumber > UE::Sequencer::FSectionModel::GetRange () const
Gets the time range of the section.
References GetRange().
Referenced by GetRange().
GetSection()
UMovieSceneSection * UE::Sequencer::FSectionModel::GetSection () const
Gets the section object.
References GetSection().
Referenced by GetSection(), and NeedsLayout().
GetSectionInterface()
TSharedPtr< ISequencerSection > UE::Sequencer::FSectionModel::GetSectionInterface () const
Gets the section interface.
References GetSectionInterface().
Referenced by GetSectionInterface().
GetUnderlappingSections()
TArray< FOverlappingSections > UE::Sequencer::FSectionModel::GetUnderlappingSections ()
Gets an array of sections that underlap the specified section.
References GetUnderlappingSections().
Referenced by GetUnderlappingSections().
InitializeObject()
virtual void UE::Sequencer::FSectionModel::InitializeObject (TWeakObjectPtr<> InWeakObject) override virtual
Implements UE::Sequencer::IObjectModelExtension.
InitializeSection()
void UE::Sequencer::FSectionModel::InitializeSection (TSharedPtr< ISequencerSection > InSectionInterface)
References InitializeSection().
Referenced by InitializeSection().
IsSelectable()
ESelectionIntent UE::Sequencer::FSectionModel::IsSelectable () const override virtual
Reimplemented from UE::Sequencer::ISelectableExtension.
NeedsLayout()
bool UE::Sequencer::FSectionModel::NeedsLayout () const inline
Returns whether this section model needs to be rebuilt, ie.
the channel proxy is no longer valid
Definition at line 101 of file SectionModel.h.
References GetSection(), IsValid(), NeedsLayout(), PreviousLayoutChannelProxy, and PreviousLayoutRowIndex.
Referenced by NeedsLayout().
OffsetLayerBar()
void UE::Sequencer::FSectionModel::OffsetLayerBar (FFrameNumber Amount) override virtual
Implements UE::Sequencer::ILayerBarExtension.
OnBeginDrag()
void UE::Sequencer::FSectionModel::OnBeginDrag (IDragOperation & DragOperation) override virtual
Called at the beginning of the drag operation.
Implements UE::Sequencer::IDraggableTrackAreaExtension.
OnBeginStretch()
EStretchResult UE::Sequencer::FSectionModel::OnBeginStretch (const IStretchOperation & StretchOperation, const FStretchScreenParameters & ScreenParameters, FStretchParameters * InOutParameters) override virtual
Reimplemented from UE::Sequencer::IStretchableExtension.
OnEndDrag()
void UE::Sequencer::FSectionModel::OnEndDrag (IDragOperation & DragOperation) override virtual
Called at the end of a drag operation.
Implements UE::Sequencer::IDraggableTrackAreaExtension.
OnEndStretch()
void UE::Sequencer::FSectionModel::OnEndStretch (const IStretchOperation & StretchOperation, const FStretchScreenParameters & ScreenParameters, FStretchParameters * InOutParameters) override virtual
Reimplemented from UE::Sequencer::IStretchableExtension.
OnInitiateStretch()
void UE::Sequencer::FSectionModel::OnInitiateStretch (IStretchOperation & StretchOperation, EStretchConstraint Constraint, FStretchParameters * InOutGlobalParameters) override virtual
Reimplemented from UE::Sequencer::IStretchableExtension.
OnModifiedDirectly()
void UE::Sequencer::FSectionModel::OnModifiedDirectly (UMovieSceneSignedObject *) override virtual
Reimplemented from UE::MovieScene::ISignedObjectEventHandler.
OnRowChanged()
void UE::Sequencer::FSectionModel::OnRowChanged (UMovieSceneSection *) override virtual
Reimplemented from UE::MovieScene::ISectionEventHandler.
OnStretch()
void UE::Sequencer::FSectionModel::OnStretch (const IStretchOperation & StretchOperation, const FStretchScreenParameters & ScreenParameters, FStretchParameters * InOutParameters) override virtual
Reimplemented from UE::Sequencer::IStretchableExtension.
SetConditionEditorForceTrue()
void UE::Sequencer::FSectionModel::SetConditionEditorForceTrue (bool bEditorForceTrue) override virtual
Set this item's condition to evaluate true for editor preview purposes.
Implements UE::Sequencer::IConditionableExtension.
SetLayoutChannelProxy()
void UE::Sequencer::FSectionModel::SetLayoutChannelProxy (TWeakPtr< FMovieSceneChannelProxy > InPreviousLayoutChannelProxy) inline
Set the channel proxy that was most recently used to layout this section model.
Definition at line 107 of file SectionModel.h.
References PreviousLayoutChannelProxy.
SetLayoutRowIndex()
void UE::Sequencer::FSectionModel::SetLayoutRowIndex (int32 InRowIndex) inline
Set the row index that was most recently used to layout this section model.
Definition at line 113 of file SectionModel.h.
References PreviousLayoutRowIndex.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FSectionModel::UE_SEQUENCER_DECLARE_CASTABLE (FSectionModel , FViewModel , FLinkedOutlinerExtension , IObjectModelExtension , ILayerBarExtension , ITrackLaneExtension , ISelectableExtension , ISnappableExtension , IDraggableTrackAreaExtension , IStretchableExtension , IConditionableExtension)
References UE::Sequencer::FLinkedOutlinerExtension::FLinkedOutlinerExtension(), FSectionModel(), and UE::Sequencer::FViewModel::FViewModel().
UpdateCachedData()
void UE::Sequencer::FSectionModel::UpdateCachedData () private
Field Documentation
ChannelList
FViewModelListHead UE::Sequencer::FSectionModel::ChannelList private
Definition at line 166 of file SectionModel.h.
LayerBarRange
TRange<FFrameNumber> UE::Sequencer::FSectionModel::LayerBarRange private
Definition at line 170 of file SectionModel.h.
OnUpdated
This member is no longer please subscribe to UMovieSceneSignedObject::OnModifiedDirectly FOnModelUpdated UE::Sequencer::FSectionModel::OnUpdated
Definition at line 70 of file SectionModel.h.
PreviousLayoutChannelProxy
TWeakPtr<FMovieSceneChannelProxy> UE::Sequencer::FSectionModel::PreviousLayoutChannelProxy private
Definition at line 172 of file SectionModel.h.
Referenced by NeedsLayout(), and SetLayoutChannelProxy().
PreviousLayoutRowIndex
int32 UE::Sequencer::FSectionModel::PreviousLayoutRowIndex = -1 private
Definition at line 173 of file SectionModel.h.
Referenced by NeedsLayout(), and SetLayoutRowIndex().
SectionInterface
TSharedPtr<ISequencerSection> UE::Sequencer::FSectionModel::SectionInterface private
Definition at line 167 of file SectionModel.h.
SectionRange
TRange<FFrameNumber> UE::Sequencer::FSectionModel::SectionRange private
Definition at line 169 of file SectionModel.h.
supported
This member is no longer UE::Sequencer::FSectionModel::supported
Definition at line 69 of file SectionModel.h.
WeakSection
TWeakObjectPtr<UMovieSceneSection> UE::Sequencer::FSectionModel::WeakSection private
Definition at line 168 of file SectionModel.h.
The documentation for this class was generated from the following file:
SectionModel.h