Unreal Engine 5.6 C++ API: UKismetArrayLibrary Class Reference
UKismetArrayLibrary Class Reference
#include "KismetArrayLibrary.h"
Public Member Functions
DECLARE_FUNCTION (execArray_Add)
DECLARE_FUNCTION (execArray_AddUnique)
DECLARE_FUNCTION (execArray_Append)
DECLARE_FUNCTION (execArray_Clear)
DECLARE_FUNCTION (execArray_Contains)
DECLARE_FUNCTION (execArray_Find)
DECLARE_FUNCTION (execArray_Get)
DECLARE_FUNCTION (execArray_Identical)
DECLARE_FUNCTION (execArray_Insert)
DECLARE_FUNCTION (execArray_IsEmpty)
DECLARE_FUNCTION (execArray_IsNotEmpty)
DECLARE_FUNCTION (execArray_IsValidIndex)
DECLARE_FUNCTION (execArray_LastIndex)
DECLARE_FUNCTION (execArray_Length)
DECLARE_FUNCTION (execArray_Random)
DECLARE_FUNCTION (execArray_RandomFromStream)
DECLARE_FUNCTION (execArray_Remove)
DECLARE_FUNCTION (execArray_RemoveItem)
DECLARE_FUNCTION (execArray_Resize)
DECLARE_FUNCTION (execArray_Reverse)
DECLARE_FUNCTION (execArray_Set)
DECLARE_FUNCTION (execArray_Shuffle)
DECLARE_FUNCTION (execArray_ShuffleFromStream)
DECLARE_FUNCTION (execArray_Swap)
DECLARE_FUNCTION (execSetArrayPropertyByName)
Static Public Member Functions
static int32 GetLastIndex (const FScriptArrayHelper &ArrayHelper)
Static Public Attributes
static const FName ReachedMaximumContainerSizeWarning
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION()
Add item to array.
UFUNCTION ()
Add item to array (unique)
UFUNCTION ()
Shuffle (randomize) the elements of an array.
UFUNCTION ()
Shuffle (randomize) the elements of an array from a specific stream of random data, useful for achieving determinism.
UFUNCTION ()
Checks if two arrays are memberwise identical.
UFUNCTION ()
Append an array to another array.
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
Reverse the elements of an array.
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
UFUNCTION ()
Gets a random item from specified array.
UFUNCTION ()
Gets a random item from specified array (using random stream)
UFUNCTION ()) static 1 void SetArrayPropertyByName(UObject *Object
Not exposed to users.
UFUNCTION ()) static 1 void SortByteArray(UPARAM(Ref) TArray< uint8 > &TargetArray
Sorts an array of bytes.
UFUNCTION ()) static 1 void SortFloatArray(UPARAM(Ref) TArray< double > &TargetArray
Sorts an array of doubles.
UFUNCTION ()) static 1 void SortInt64Array(UPARAM(Ref) TArray< int64 > &TargetArray
Sorts an array of 64-bit integers.
UFUNCTION ()) static 1 void SortIntArray(UPARAM(Ref) TArray< int32 > &TargetArray
Sorts an array of integers.
UFUNCTION ()) static 1 void SortNameArray(UPARAM(Ref) TArray< FName > &TargetArray
Sorts an array of FNames.
UFUNCTION ()) static 1 void SortStringArray(UPARAM(Ref) TArray< FString > &TargetArray
Sorts an array of strings alphabetically.
Static Private Member Functions
static int32 GenericArray_Add (void *TargetArray, const FArrayProperty *ArrayProp, const void *NewItem)
static int32 GenericArray_AddUnique (void *TargetArray, const FArrayProperty *ArrayProp, const void *NewItem)
static void GenericArray_Append (void *TargetArray, const FArrayProperty *TargetArrayProp, void *SourceArray, const FArrayProperty *SourceArrayProperty)
static void GenericArray_Clear (void *TargetArray, const FArrayProperty *ArrayProp)
static int32 GenericArray_Find (const void *TargetArray, const FArrayProperty *ArrayProperty, const void *ItemToFind)
static void GenericArray_Get (void *TargetArray, const FArrayProperty *ArrayProp, int32 Index, void *Item)
static void GenericArray_HandleBool (const FProperty *Property, void *ItemPtr)
static bool GenericArray_Identical (void *ArrayA, const FArrayProperty *ArrayAProp, void *ArrayB, const FArrayProperty *ArrayBProperty)
static void GenericArray_Insert (void *TargetArray, const FArrayProperty *ArrayProp, const void *NewItem, int32 Index)
static bool GenericArray_IsEmpty (const void *TargetArray, const FArrayProperty *ArrayProp)
static bool GenericArray_IsNotEmpty (const void *TargetArray, const FArrayProperty *ArrayProp)
static bool GenericArray_IsValidIndex (const void *TargetArray, const FArrayProperty *ArrayProp, int32 IndexToTest)
static int32 GenericArray_LastIndex (const void *TargetArray, const FArrayProperty *ArrayProp)
static int32 GenericArray_Length (const void *TargetArray, const FArrayProperty *ArrayProp)
static void GenericArray_Random (void *TargetArray, const FArrayProperty *ArrayProp, void *OutItem, int32 *OutIndex)
static void GenericArray_RandomFromStream (void *TargetArray, const FArrayProperty *ArrayProp, FRandomStream *RandomStream, void *OutItem, int32 *OutIndex)
static void GenericArray_Remove (void *TargetArray, const FArrayProperty *ArrayProp, int32 IndexToRemove)
static bool GenericArray_RemoveItem (void *TargetArray, const FArrayProperty *ArrayProp, const void *Item)
static void GenericArray_Resize (void *TargetArray, const FArrayProperty *ArrayProp, int32 Size)
static void GenericArray_Reverse (void *TargetArray, const FArrayProperty *ArrayProp)
static void GenericArray_Set (void *TargetArray, const FArrayProperty *ArrayProp, int32 Index, const void *NewItem, bool bSizeToFit)
static void GenericArray_SetArrayPropertyByName (UObject *OwnerObject, FName ArrayPropertyName, const void *SrcArrayAddr)
static void GenericArray_Shuffle (void *TargetArray, const FArrayProperty *ArrayProp)
static void GenericArray_ShuffleFromStream (void *TargetArray, const FArrayProperty *ArrayProp, FRandomStream *RandomStream)
static void GenericArray_Swap (const void *TargetArray, const FArrayProperty *ArrayProp, int32 First, int32 Second)
Private Attributes
bool bool bLexicalSort = true
bool bStableSort = false
Category
FName PropertyName
bool EArraySortOrder SortOrder = EArraySortOrder::Ascending)
bool bool EArraySortOrder SortOrder = EArraySortOrder::Ascending)
FName const TArray< int32 > & Value
Static Private Attributes
static constexpr int32 MaxSupportedArraySize = TNumericLimits<int32>::Max()
Detailed Description
Definition at line 26 of file KismetArrayLibrary.h.
Member Function Documentation
DECLARE_FUNCTION() [1/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Add) inline
Definition at line 379 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_Add(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [2/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_AddUnique) inline
Definition at line 409 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_AddUnique(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [3/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Append) inline
Definition at line 510 of file KismetArrayLibrary.h.
References CastField(), GenericArray_Append(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [4/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Clear) inline
Definition at line 625 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_Clear(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [5/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Contains) inline
Definition at line 882 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_Find(), GenericArray_HandleBool(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [6/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Find) inline
Definition at line 847 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_Find(), GenericArray_HandleBool(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [7/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Get) inline
Definition at line 747 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_Get(), FField::GetClass(), FProperty::GetElementSize(), FProperty::InitializeValue(), FFieldClass::IsChildOf(), P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [8/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Identical) inline
Definition at line 481 of file KismetArrayLibrary.h.
References CastField(), GenericArray_Identical(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [9/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Insert) inline
Definition at line 540 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_Insert(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [10/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_IsEmpty) inline
Definition at line 696 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_IsEmpty(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [11/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_IsNotEmpty) inline
Definition at line 713 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_IsNotEmpty(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [12/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_IsValidIndex) inline
Definition at line 939 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_IsValidIndex(), P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [13/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_LastIndex) inline
Definition at line 730 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_LastIndex(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [14/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Length) inline
Definition at line 679 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_Length(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [15/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Random) inline
Definition at line 960 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_Random(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [16/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_RandomFromStream) inline
Definition at line 986 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_RandomFromStream(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RandomStream.
DECLARE_FUNCTION() [17/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Remove) inline
Definition at line 571 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_Remove(), P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [18/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_RemoveItem) inline
Definition at line 591 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_HandleBool(), GenericArray_RemoveItem(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [19/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Resize) inline
Definition at line 643 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_Resize(), P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, P_NATIVE_END, and TSequenceHistory< HistorySize >::Size.
DECLARE_FUNCTION() [20/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Reverse) inline
Definition at line 662 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_Reverse(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [21/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Set) inline
Definition at line 790 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericArray_Set(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_GET_PROPERTY, P_GET_UBOOL, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [22/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Shuffle) inline
Definition at line 439 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_Shuffle(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [23/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_ShuffleFromStream) inline
Definition at line 458 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_ShuffleFromStream(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RandomStream.
DECLARE_FUNCTION() [24/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execArray_Swap) inline
Definition at line 825 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), First, GenericArray_Swap(), P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, P_NATIVE_END, and Second.
DECLARE_FUNCTION() [25/25]
UKismetArrayLibrary::DECLARE_FUNCTION (execSetArrayPropertyByName) inline
Definition at line 917 of file KismetArrayLibrary.h.
References ArrayProperty, CastField(), GenericArray_SetArrayPropertyByName(), P_FINISH, P_GET_OBJECT, P_GET_PROPERTY, P_NATIVE_BEGIN, and P_NATIVE_END.
GENERATED_UCLASS_BODY()
UKismetArrayLibrary::GENERATED_UCLASS_BODY () private
Add item to array.
Parameters
TargetArray The array to add item to
NewItem The item to add to the array
Returns
The index of the newly added item
GenericArray_Add()
int32 UKismetArrayLibrary::GenericArray_Add (void * TargetArray, const FArrayProperty * ArrayProp, const void * NewItem) static private
References GenericArray_Add().
Referenced by DECLARE_FUNCTION(), and GenericArray_Add().
GenericArray_AddUnique()
int32 UKismetArrayLibrary::GenericArray_AddUnique (void * TargetArray, const FArrayProperty * ArrayProp, const void * NewItem) static private
References GenericArray_AddUnique().
Referenced by DECLARE_FUNCTION(), and GenericArray_AddUnique().
GenericArray_Append()
void UKismetArrayLibrary::GenericArray_Append (void * TargetArray, const FArrayProperty * TargetArrayProp, void * SourceArray, const FArrayProperty * SourceArrayProperty) static private
References GenericArray_Append().
Referenced by DECLARE_FUNCTION(), and GenericArray_Append().
GenericArray_Clear()
void UKismetArrayLibrary::GenericArray_Clear (void * TargetArray, const FArrayProperty * ArrayProp) static private
References GenericArray_Clear().
Referenced by DECLARE_FUNCTION(), and GenericArray_Clear().
GenericArray_Find()
int32 UKismetArrayLibrary::GenericArray_Find (const void * TargetArray, const FArrayProperty * ArrayProperty, const void * ItemToFind) static private
References ArrayProperty, and GenericArray_Find().
Referenced by DECLARE_FUNCTION(), DECLARE_FUNCTION(), and GenericArray_Find().
GenericArray_Get()
void UKismetArrayLibrary::GenericArray_Get (void * TargetArray, const FArrayProperty * ArrayProp, int32 Index, void * Item) static private
References GenericArray_Get(), and Item.
Referenced by DECLARE_FUNCTION(), and GenericArray_Get().
GenericArray_HandleBool()
void UKismetArrayLibrary::GenericArray_HandleBool (const FProperty * Property, void * ItemPtr) static private
References GenericArray_HandleBool(), and Property.
Referenced by DECLARE_FUNCTION(), DECLARE_FUNCTION(), DECLARE_FUNCTION(), and GenericArray_HandleBool().
GenericArray_Identical()
bool UKismetArrayLibrary::GenericArray_Identical (void * ArrayA, const FArrayProperty * ArrayAProp, void * ArrayB, const FArrayProperty * ArrayBProperty) static private
References GenericArray_Identical().
Referenced by DECLARE_FUNCTION(), and GenericArray_Identical().
GenericArray_Insert()
void UKismetArrayLibrary::GenericArray_Insert (void * TargetArray, const FArrayProperty * ArrayProp, const void * NewItem, int32 Index) static private
References GenericArray_Insert().
Referenced by DECLARE_FUNCTION(), and GenericArray_Insert().
GenericArray_IsEmpty()
bool UKismetArrayLibrary::GenericArray_IsEmpty (const void * TargetArray, const FArrayProperty * ArrayProp) static private
References GenericArray_IsEmpty().
Referenced by DECLARE_FUNCTION(), and GenericArray_IsEmpty().
GenericArray_IsNotEmpty()
bool UKismetArrayLibrary::GenericArray_IsNotEmpty (const void * TargetArray, const FArrayProperty * ArrayProp) static private
References GenericArray_IsNotEmpty().
Referenced by DECLARE_FUNCTION(), and GenericArray_IsNotEmpty().
GenericArray_IsValidIndex()
bool UKismetArrayLibrary::GenericArray_IsValidIndex (const void * TargetArray, const FArrayProperty * ArrayProp, int32 IndexToTest) static private
References GenericArray_IsValidIndex().
Referenced by DECLARE_FUNCTION(), and GenericArray_IsValidIndex().
GenericArray_LastIndex()
int32 UKismetArrayLibrary::GenericArray_LastIndex (const void * TargetArray, const FArrayProperty * ArrayProp) static private
References GenericArray_LastIndex().
Referenced by DECLARE_FUNCTION(), and GenericArray_LastIndex().
GenericArray_Length()
int32 UKismetArrayLibrary::GenericArray_Length (const void * TargetArray, const FArrayProperty * ArrayProp) static private
References GenericArray_Length().
Referenced by DECLARE_FUNCTION(), and GenericArray_Length().
GenericArray_Random()
void UKismetArrayLibrary::GenericArray_Random (void * TargetArray, const FArrayProperty * ArrayProp, void * OutItem, int32 * OutIndex) static private
References GenericArray_Random().
Referenced by DECLARE_FUNCTION(), and GenericArray_Random().
GenericArray_RandomFromStream()
void UKismetArrayLibrary::GenericArray_RandomFromStream (void * TargetArray, const FArrayProperty * ArrayProp, FRandomStream * RandomStream, void * OutItem, int32 * OutIndex) static private
References GenericArray_RandomFromStream(), and RandomStream.
Referenced by DECLARE_FUNCTION(), and GenericArray_RandomFromStream().
GenericArray_Remove()
void UKismetArrayLibrary::GenericArray_Remove (void * TargetArray, const FArrayProperty * ArrayProp, int32 IndexToRemove) static private
References GenericArray_Remove().
Referenced by DECLARE_FUNCTION(), and GenericArray_Remove().
GenericArray_RemoveItem()
bool UKismetArrayLibrary::GenericArray_RemoveItem (void * TargetArray, const FArrayProperty * ArrayProp, const void * Item) static private
References GenericArray_RemoveItem(), and Item.
Referenced by DECLARE_FUNCTION(), and GenericArray_RemoveItem().
GenericArray_Resize()
void UKismetArrayLibrary::GenericArray_Resize (void * TargetArray, const FArrayProperty * ArrayProp, int32 Size) static private
References GenericArray_Resize(), and TSequenceHistory< HistorySize >::Size.
Referenced by DECLARE_FUNCTION(), and GenericArray_Resize().
GenericArray_Reverse()
void UKismetArrayLibrary::GenericArray_Reverse (void * TargetArray, const FArrayProperty * ArrayProp) static private
References GenericArray_Reverse().
Referenced by DECLARE_FUNCTION(), and GenericArray_Reverse().
GenericArray_Set()
void UKismetArrayLibrary::GenericArray_Set (void * TargetArray, const FArrayProperty * ArrayProp, int32 Index, const void * NewItem, bool bSizeToFit) static private
References GenericArray_Set().
Referenced by DECLARE_FUNCTION(), and GenericArray_Set().
GenericArray_SetArrayPropertyByName()
void UKismetArrayLibrary::GenericArray_SetArrayPropertyByName (UObject * OwnerObject, FName ArrayPropertyName, const void * SrcArrayAddr) static private
References GenericArray_SetArrayPropertyByName().
Referenced by DECLARE_FUNCTION(), and GenericArray_SetArrayPropertyByName().
GenericArray_Shuffle()
void UKismetArrayLibrary::GenericArray_Shuffle (void * TargetArray, const FArrayProperty * ArrayProp) static private
References GenericArray_Shuffle().
Referenced by DECLARE_FUNCTION(), and GenericArray_Shuffle().
GenericArray_ShuffleFromStream()
void UKismetArrayLibrary::GenericArray_ShuffleFromStream (void * TargetArray, const FArrayProperty * ArrayProp, FRandomStream * RandomStream) static private
References GenericArray_ShuffleFromStream(), and RandomStream.
Referenced by DECLARE_FUNCTION(), and GenericArray_ShuffleFromStream().
GenericArray_Swap()
void UKismetArrayLibrary::GenericArray_Swap (const void * TargetArray, const FArrayProperty * ArrayProp, int32 First, int32 Second) static private
References First, GenericArray_Swap(), and Second.
Referenced by DECLARE_FUNCTION(), and GenericArray_Swap().
GetLastIndex()
int32 UKismetArrayLibrary::GetLastIndex (const FScriptArrayHelper & ArrayHelper) inline static
Definition at line 373 of file KismetArrayLibrary.h.
References GetLastIndex().
Referenced by GetLastIndex().
UFUNCTION() [1/31]
UKismetArrayLibrary::UFUNCTION () private
Add item to array (unique)
Parameters
TargetArray The array to add item to
NewItem The item to add to the array
Returns
The index of the newly added item, or INDEX_NONE if the item is already present in the array
References Category, meta, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/31]
UKismetArrayLibrary::UFUNCTION () private
Shuffle (randomize) the elements of an array.
Parameters
TargetArray The array to shuffle
References Category, meta, and UFUNCTION().
UFUNCTION() [3/31]
UKismetArrayLibrary::UFUNCTION () private
Shuffle (randomize) the elements of an array from a specific stream of random data, useful for achieving determinism.
Parameters
TargetArray The array to shuffle
RandomStream The random stream
References Category, meta, RandomStream, UFUNCTION(), and UPARAM.
UFUNCTION() [4/31]
UKismetArrayLibrary::UFUNCTION () private
Checks if two arrays are memberwise identical.
Parameters
ArrayA One of the arrays to compare
ArrayB The other array to compare
Returns
Whether the two arrays are identical
References Category, meta, and UFUNCTION().
UFUNCTION() [5/31]
UKismetArrayLibrary::UFUNCTION () private
Append an array to another array.
Parameters
TargetArray The array to add the source array to
SourceArray The array to add to the target array
References Category, meta, and UFUNCTION().
UFUNCTION() [6/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [7/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [8/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, Item, meta, and UFUNCTION().
UFUNCTION() [9/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [10/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, TSequenceHistory< HistorySize >::Size, and UFUNCTION().
UFUNCTION() [11/31]
UKismetArrayLibrary::UFUNCTION () private
Reverse the elements of an array.
Parameters
TargetArray The array to reverse
References Category, meta, and UFUNCTION().
UFUNCTION() [12/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [13/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [14/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [15/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [16/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, Item, meta, and UFUNCTION().
UFUNCTION() [17/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, Item, meta, and UFUNCTION().
UFUNCTION() [18/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [19/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [20/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [21/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [22/31]
UKismetArrayLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [23/31]
UKismetArrayLibrary::UFUNCTION () private
Gets a random item from specified array.
Parameters
TargetArray The array
OutItem The random item from this array
OutIndex The index of random item (will be -1 if array is empty)
References Category, meta, and UFUNCTION().
UFUNCTION() [24/31]
UKismetArrayLibrary::UFUNCTION () private
Gets a random item from specified array (using random stream)
Parameters
TargetArray The array
RandomStream The random stream
OutItem The random item from this array
OutIndex The index of random item (will be -1 if array is empty)
References Category, meta, RandomStream, UFUNCTION(), and UPARAM.
UFUNCTION() [25/31]
UKismetArrayLibrary::UFUNCTION () private
Not exposed to users.
Supports setting an array property on an object by name.
References meta, and UFUNCTION().
UFUNCTION() [26/31]
UKismetArrayLibrary::UFUNCTION () & private
Sorts an array of bytes.
Parameters
TargetArray The array to sort.
bStableSort If a stable sort should be used. This preserves the order of identical elements, but is slower.
SortOrder If the array should be sorted in ascending or descending order.
References Ascending, bStableSort, Category, meta, SortOrder, UFUNCTION(), and UPARAM.
UFUNCTION() [27/31]
UKismetArrayLibrary::UFUNCTION () & private
Sorts an array of doubles.
Parameters
TargetArray The array to sort.
bStableSort If a stable sort should be used. This preserves the order of identical elements, but is slower.
SortOrder If the array should be sorted in ascending or descending order.
References Ascending, bStableSort, Category, meta, SortOrder, UFUNCTION(), and UPARAM.
UFUNCTION() [28/31]
UKismetArrayLibrary::UFUNCTION () & private
Sorts an array of 64-bit integers.
Parameters
TargetArray The array to sort.
bStableSort If a stable sort should be used. This preserves the order of identical elements, but is slower.
SortOrder If the array should be sorted in ascending or descending order.
References Ascending, bStableSort, Category, meta, SortOrder, UFUNCTION(), and UPARAM.
UFUNCTION() [29/31]
UKismetArrayLibrary::UFUNCTION () & private
Sorts an array of integers.
Parameters
TargetArray The array to sort.
bStableSort If a stable sort should be used. This preserves the order of identical elements, but is slower.
SortOrder If the array should be sorted in ascending or descending order.
References Ascending, bStableSort, Category, meta, SortOrder, UFUNCTION(), and UPARAM.
UFUNCTION() [30/31]
UKismetArrayLibrary::UFUNCTION () & private
Sorts an array of FNames.
Parameters
TargetArray The array to sort.
bStableSort If a stable sort should be used. This preserves the order of identical elements, but is slower.
bLexicalSort If the names should be sorted based on the string value of the name rather than the comparison index. This is slower when enabled.
SortOrder If the array should be sorted in ascending or descending order.
References Category, meta, and UFUNCTION().
UFUNCTION() [31/31]
UKismetArrayLibrary::UFUNCTION () & private
Sorts an array of strings alphabetically.
Parameters
TargetArray The array to sort.
bStableSort If a stable sort should be used. This preserves the order of identical elements, but is slower.
SortOrder If the array should be sorted in ascending or descending order.
References Category, meta, and UFUNCTION().
Field Documentation
bLexicalSort
bool bool UKismetArrayLibrary::bLexicalSort = true private
Definition at line 295 of file KismetArrayLibrary.h.
bStableSort
bool UKismetArrayLibrary::bStableSort = false private
Definition at line 284 of file KismetArrayLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Category
UKismetArrayLibrary::Category private
Initial value:
="Utilities|Array")
    static 1 int32 Array_Add(const TArray<int32>& TargetArray, const int32& NewItem)
Definition at line 36 of file KismetArrayLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
MaxSupportedArraySize
int32 UKismetArrayLibrary::MaxSupportedArraySize = TNumericLimits<int32>::Max() static constexpr private
Definition at line 364 of file KismetArrayLibrary.h.
PropertyName
FName UKismetArrayLibrary::PropertyName private
Definition at line 243 of file KismetArrayLibrary.h.
ReachedMaximumContainerSizeWarning
const FName UKismetArrayLibrary::ReachedMaximumContainerSizeWarning static
Definition at line 370 of file KismetArrayLibrary.h.
SortOrder [1/2]
bool EArraySortOrder UKismetArrayLibrary::SortOrder = EArraySortOrder::Ascending) private
Definition at line 284 of file KismetArrayLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
SortOrder [2/2]
bool bool EArraySortOrder UKismetArrayLibrary::SortOrder = EArraySortOrder::Ascending) private
Definition at line 295 of file KismetArrayLibrary.h.
Value
FName const TArray<int32>& UKismetArrayLibrary::Value private
Definition at line 243 of file KismetArrayLibrary.h.
The documentation for this class was generated from the following file:
KismetArrayLibrary.h