Unreal Engine 5.6 C++ API: IChaosCachingEditorPlugin Class Reference
IChaosCachingEditorPlugin Class Reference
The public interface to this module.
#include "ChaosCachingEditorPlugin.h"
Public Member Functions
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IChaosCachingEditorPlugin & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Private Member Functions
TSharedRef< FExtender > ExtendLevelViewportContextMenu (const TSharedRef< FUICommandList > InCommandList, const TArray< AActor * > SelectedActors)
void OnCreateCacheManager ()
void RegisterCachingSubMenu (FMenuBuilder &InMenuBuilder)
Private Attributes
FAssetTypeActions_ChaosCacheCollection * AssetTypeActions_ChaosCacheCollection
TArray< IConsoleObject * > EditorCommands
FMovieSceneChaosCacheTrackRecorderFactory MovieSceneChaosCacheTrackRecorder
FDelegateHandle SourcesMenuExtension
FDelegateHandle StartupHandle
FDelegateHandle TrackEditorBindingHandle
Detailed Description
The public interface to this module.
Definition at line 22 of file ChaosCachingEditorPlugin.h.
Member Function Documentation
ExtendLevelViewportContextMenu()
TSharedRef< FExtender > IChaosCachingEditorPlugin::ExtendLevelViewportContextMenu (const TSharedRef< FUICommandList > InCommandList, const TArray< AActor * > SelectedActors) private
Get()
IChaosCachingEditorPlugin & IChaosCachingEditorPlugin::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 36 of file ChaosCachingEditorPlugin.h.
References FModuleManager::LoadModuleChecked().
IsAvailable()
bool IChaosCachingEditorPlugin::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 46 of file ChaosCachingEditorPlugin.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
OnCreateCacheManager()
void IChaosCachingEditorPlugin::OnCreateCacheManager () private
RegisterCachingSubMenu()
void IChaosCachingEditorPlugin::RegisterCachingSubMenu (FMenuBuilder & InMenuBuilder) private
ShutdownModule()
virtual void IChaosCachingEditorPlugin::ShutdownModule () virtual
Called before the module is unloaded, right before the module object is destroyed.
During normal shutdown, this is called in reverse order that modules finish StartupModule(). This means that, as long as a module references dependent modules in it's StartupModule(), it can safely reference those dependencies in ShutdownModule() as well.
Reimplemented from IModuleInterface.
StartupModule()
virtual void IChaosCachingEditorPlugin::StartupModule () virtual
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
ie:
FModuleManager::Get().LoadModuleChecked(TEXT("HTTP"));
Reimplemented from IModuleInterface.
Field Documentation
AssetTypeActions_ChaosCacheCollection
FAssetTypeActions_ChaosCacheCollection* IChaosCachingEditorPlugin::AssetTypeActions_ChaosCacheCollection private
Definition at line 55 of file ChaosCachingEditorPlugin.h.
EditorCommands
TArray<IConsoleObject*> IChaosCachingEditorPlugin::EditorCommands private
Definition at line 24 of file ChaosCachingEditorPlugin.h.
MovieSceneChaosCacheTrackRecorder
FMovieSceneChaosCacheTrackRecorderFactory IChaosCachingEditorPlugin::MovieSceneChaosCacheTrackRecorder private
Definition at line 60 of file ChaosCachingEditorPlugin.h.
SourcesMenuExtension
FDelegateHandle IChaosCachingEditorPlugin::SourcesMenuExtension private
Definition at line 58 of file ChaosCachingEditorPlugin.h.
StartupHandle
FDelegateHandle IChaosCachingEditorPlugin::StartupHandle private
Definition at line 56 of file ChaosCachingEditorPlugin.h.
TrackEditorBindingHandle
FDelegateHandle IChaosCachingEditorPlugin::TrackEditorBindingHandle private
Definition at line 57 of file ChaosCachingEditorPlugin.h.
The documentation for this class was generated from the following file:
ChaosCachingEditorPlugin.h