Unreal Engine 5.6 C++ API: FShaderType Class Reference
FShaderType Class Reference
An object which is used to serialize/deserialize, compile, and cache a particular shader class.
#include "Shader.h"
Data Structures
class FParameters
Derived FShaderTypes should derive from this class to pass params to FShader constructor.
Public Types
typedef FShader *(* ConstructCompiledType) (const FShader::CompiledShaderInitializerType &Initializer)
typedef class FShader *(* ConstructSerializedType) ()
enum class EShaderTypeForDynamicCast : uint32 {
Global , Material , MeshMaterial , Niagara ,
OCIO , ComputeKernel , NNERuntimeIREE , NumShaderTypes
}
typedef EShaderCompileJobPriority(* GetOverrideJobPriorityType) ()
typedef void(* GetPermutationIdStringType) (int32 PermutationId, FString &, bool)
typedef ERayTracingPayloadType(* GetRayTracingPayloadTypeType) (const int32 PermutationId)
typedef const FShaderBindingLayout *(* GetShaderBindingLayoutType) (const FShaderPermutationParameters &)
typedef void(* ModifyCompilationEnvironmentType) (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
typedef bool(* ShouldCompilePermutationType) (const FShaderPermutationParameters &)
typedef EShaderPermutationPrecacheRequest(* ShouldPrecachePermutationType) (const FShaderPermutationParameters &)
typedef bool(* ValidateCompiledResultType) (EShaderPlatform, const FShaderParameterMap &, TArray< FString > &)
Public Member Functions
RENDERCORE_API FShaderType (EShaderTypeForDynamicCast InShaderTypeForDynamicCast, FTypeLayoutDesc &InTypeLayout, const TCHAR *InName, const TCHAR *InSourceFilename, const TCHAR *InFunctionName, uint32 InFrequency, int32 TotalPermutationCount, ConstructSerializedType InConstructSerializedRef, ConstructCompiledType InConstructCompiledRef, ShouldCompilePermutationType InShouldCompilePermutationRef, ShouldPrecachePermutationType InShouldPrecachePermutationRef, GetRayTracingPayloadTypeType InGetRayTracingPayloadTypeRef, GetShaderBindingLayoutType InGetShaderBindingLayoutTypeRef, ModifyCompilationEnvironmentType InModifyCompilationEnvironmentRef, ValidateCompiledResultType InValidateCompiledResultRef, GetOverrideJobPriorityType InGetOverrideJobPriorityRef, uint32 InTypeSize, const FShaderParametersMetadata *InRootParametersMetadata, GetPermutationIdStringType InGetPermutationIdStringRef=nullptr)
Minimal initialization constructor.
virtual RENDERCORE_API ~FShaderType ()
RENDERCORE_API void AddUniformBufferIncludesToEnvironment (FShaderCompilerEnvironment &OutEnvironment, EShaderPlatform Platform) const
Adds include statements for uniform buffers that this shader type references.
const FGlobalShaderType * AsGlobalShaderType () const
const FMaterialShaderType * AsMaterialShaderType () const
const FMeshMaterialShaderType * AsMeshMaterialShaderType () const
const FNiagaraShaderType * AsNiagaraShaderType () const
const FOpenColorIOShaderType * AsOpenColorIOShaderType () const
RENDERCORE_API FShader * ConstructCompiled (const FShader::CompiledShaderInitializerType &Initializer) const
RENDERCORE_API FShader * ConstructForDeserialization () const
Constructs a new instance of the shader type for deserialization.
RENDERCORE_API void DumpDebugInfo ()
FComputeKernelShaderType * GetComputeKernelShaderType ()
const FComputeKernelShaderType * GetComputeKernelShaderType () const
const FName & GetFName () const
EShaderFrequency GetFrequency () const
const TCHAR * GetFunctionName () const
FGlobalShaderType * GetGlobalShaderType ()
const FGlobalShaderType * GetGlobalShaderType () const
const FHashedName & GetHashedName () const
const FHashedName & GetHashedShaderFilename () const
const FTypeLayoutDesc & GetLayout () const
FMaterialShaderType * GetMaterialShaderType ()
const FMaterialShaderType * GetMaterialShaderType () const
FMeshMaterialShaderType * GetMeshMaterialShaderType ()
const FMeshMaterialShaderType * GetMeshMaterialShaderType () const
const TCHAR * GetName () const
FNiagaraShaderType * GetNiagaraShaderType ()
const FNiagaraShaderType * GetNiagaraShaderType () const
FNNERuntimeIREEShaderType * GetNNERuntimeIREEShaderType ()
const FNNERuntimeIREEShaderType * GetNNERuntimeIREEShaderType () const
int32 GetNumShaders () const
FOpenColorIOShaderType * GetOpenColorIOShaderType ()
const FOpenColorIOShaderType * GetOpenColorIOShaderType () const
RENDERCORE_API EShaderCompileJobPriority GetOverrideJobPriority () const
Returns a custom compile job priority or EShaderCompileJobPriority::None to ignore the customization.
int32 GetPermutationCount () const
RENDERCORE_API FString GetPermutationIdString (int32 PermutationId, bool bFullNames) const
Returns a string representation for the specified permutation Id.
RENDERCORE_API ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId) const
const TSet< const TCHAR *, TStringPointerSetKeyFuncs_DEPRECATED< const TCHAR * > > & GetReferencedUniformBufferNames () const
const TSet< const FShaderParametersMetadata * > & GetReferencedUniformBuffers () const
const FShaderParametersMetadata * GetRootParametersMetadata () const
Returns the meta data for the root shader parameter struct.
RENDERCORE_API const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &Parameters) const
const TCHAR * GetShaderFilename () const
RENDERCORE_API void GetShaderStableKeyParts (struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API const FSHAHash & GetSourceHash (EShaderPlatform ShaderPlatform) const
Calculates a Hash based on this shader type's source code and includes.
EShaderTypeForDynamicCast GetTypeForDynamicCast () const
uint32 GetTypeSize () const
RENDERCORE_API void ModifyCompilationEnvironment (const FShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment) const
RENDERCORE_API bool ShouldCompilePermutation (const FShaderPermutationParameters &Parameters) const
RENDERCORE_API EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters) const
RENDERCORE_API void UpdateReferencedUniformBufferNames (const TMap< FString, TArray< const TCHAR * > > &ShaderFileToUniformBufferVariables)
RENDERCORE_API bool ValidateCompiledResult (EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutError) const
Checks if the shader type should pass compilation for a particular set of parameters.
Static Public Member Functions
static RENDERCORE_API TMap< FHashedName, FShaderType * > & GetNameToTypeMap ()
static RENDERCORE_API FShaderType * GetShaderTypeByName (const TCHAR *Name)
static RENDERCORE_API TArray< const FShaderType * > GetShaderTypesByFilename (const TCHAR *Filename, bool bSearchAsRegexFilter=false)
static RENDERCORE_API TArray< const FShaderType * > GetShaderTypesByFilenameFilter (const TFunction< bool(const TCHAR *)> &InFilenameFilter)
static RENDERCORE_API const TArray< FShaderType * > & GetSortedTypes (EShaderTypeForDynamicCast Type)
static RENDERCORE_API TLinkedList< FShaderType * > *& GetTypeList ()
static RENDERCORE_API void Initialize (const TMap< FString, TArray< const TCHAR * > > &ShaderFileToUniformBufferVariables)
Initialize FShaderType static members, this must be called before any shader types are created.
static RENDERCORE_API void Uninitialize ()
Uninitializes FShaderType cached data.
Protected Attributes
TSet< const FShaderParametersMetadata * > ReferencedUniformBuffers
Cache of referenced uniform buffer structs.
Private Attributes
ConstructCompiledType ConstructCompiledRef
ConstructSerializedType ConstructSerializedRef
uint32 Frequency
const TCHAR * FunctionName
GetOverrideJobPriorityType GetOverrideJobPriorityRef
GetPermutationIdStringType GetPermutationIdStringRef
GetRayTracingPayloadTypeType GetRayTracingPayloadTypeRef
GetShaderBindingLayoutType GetShaderBindingLayoutTypeRef
TLinkedList< FShaderType * > GlobalListLink
FHashedName HashedName
FHashedName HashedSourceFilename
ModifyCompilationEnvironmentType ModifyCompilationEnvironmentRef
const TCHAR * Name
const FShaderParametersMetadata *const RootParametersMetadata
EShaderTypeForDynamicCast ShaderTypeForDynamicCast
ShouldCompilePermutationType ShouldCompilePermutationRef
ShouldPrecachePermutationType ShouldPrecachePermutationRef
const TCHAR * SourceFilename
int32 TotalPermutationCount
const FTypeLayoutDesc * TypeLayout
FName TypeName
uint32 TypeSize
ValidateCompiledResultType ValidateCompiledResultRef
Static Private Attributes
static bool bInitializedSerializationHistory
Tracks whether serialization history for all shader types has been initialized.
Friends
void RENDERCORE_API DumpShaderStats (EShaderPlatform Platform, EShaderFrequency Frequency)
Dumps shader stats to the log.
uint32 GetTypeHash (FShaderType *Ref)
Hashes a pointer to a shader type.
RENDERCORE_API friend FArchive & operator<< (FArchive &Ar, FShaderType *&Ref)
Serializes a shader type reference by name.
Detailed Description
An object which is used to serialize/deserialize, compile, and cache a particular shader class.
A shader type can manage multiple instance of FShader across mutiple dimensions such as EShaderPlatform, or permutation id. The number of permutation of a shader type is simply given by GetPermutationCount().
Definition at line 1260 of file Shader.h.
Member Typedef Documentation
ConstructCompiledType
typedef FShader *(* FShaderType::ConstructCompiledType) (const FShader::CompiledShaderInitializerType &Initializer)
Definition at line 1281 of file Shader.h.
ConstructSerializedType
typedef class FShader *(* FShaderType::ConstructSerializedType) ()
Definition at line 1235 of file Shader.h.
GetOverrideJobPriorityType
typedef EShaderCompileJobPriority(* FShaderType::GetOverrideJobPriorityType) ()
Definition at line 1289 of file Shader.h.
GetPermutationIdStringType
typedef void(* FShaderType::GetPermutationIdStringType) (int32 PermutationId, FString &, bool)
Definition at line 1290 of file Shader.h.
GetRayTracingPayloadTypeType
typedef ERayTracingPayloadType(* FShaderType::GetRayTracingPayloadTypeType) (const int32 PermutationId)
Definition at line 1284 of file Shader.h.
GetShaderBindingLayoutType
typedef const FShaderBindingLayout *(* FShaderType::GetShaderBindingLayoutType) (const FShaderPermutationParameters &)
Definition at line 1285 of file Shader.h.
ModifyCompilationEnvironmentType
typedef void(* FShaderType::ModifyCompilationEnvironmentType) (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
Definition at line 1287 of file Shader.h.
ShouldCompilePermutationType
typedef bool(* FShaderType::ShouldCompilePermutationType) (const FShaderPermutationParameters &)
Definition at line 1282 of file Shader.h.
ShouldPrecachePermutationType
typedef EShaderPermutationPrecacheRequest(* FShaderType::ShouldPrecachePermutationType) (const FShaderPermutationParameters &)
Definition at line 1283 of file Shader.h.
ValidateCompiledResultType
typedef bool(* FShaderType::ValidateCompiledResultType) (EShaderPlatform, const FShaderParameterMap &, TArray< FString > &)
Definition at line 1288 of file Shader.h.
Member Enumeration Documentation
EShaderTypeForDynamicCast
enum class FShaderType::EShaderTypeForDynamicCast : uint32 strong
Enumerator
Global
Material
MeshMaterial
Niagara
OCIO
ComputeKernel
NNERuntimeIREE
NumShaderTypes
Definition at line 1264 of file Shader.h.
Constructor & Destructor Documentation
FShaderType()
RENDERCORE_API FShaderType::FShaderType (EShaderTypeForDynamicCast InShaderTypeForDynamicCast, FTypeLayoutDesc & InTypeLayout, const TCHAR * InName, const TCHAR * InSourceFilename, const TCHAR * InFunctionName, uint32 InFrequency, int32 TotalPermutationCount, ConstructSerializedType InConstructSerializedRef, ConstructCompiledType InConstructCompiledRef, ShouldCompilePermutationType InShouldCompilePermutationRef, ShouldPrecachePermutationType InShouldPrecachePermutationRef, GetRayTracingPayloadTypeType InGetRayTracingPayloadTypeRef, GetShaderBindingLayoutType InGetShaderBindingLayoutTypeRef, ModifyCompilationEnvironmentType InModifyCompilationEnvironmentRef, ValidateCompiledResultType InValidateCompiledResultRef, GetOverrideJobPriorityType InGetOverrideJobPriorityRef, uint32 InTypeSize, const FShaderParametersMetadata * InRootParametersMetadata, GetPermutationIdStringType InGetPermutationIdStringRef = nullptr)
Minimal initialization constructor.
References InName, and TotalPermutationCount.
Referenced by FMaterialShaderType::CompiledShaderInitializerType::CompiledShaderInitializerType(), FMeshMaterialShaderType::CompiledShaderInitializerType::CompiledShaderInitializerType(), GetShaderTypeByName(), GetTypeHash, operator<<, and FMeshMaterialShaderType::ShouldCompileVertexFactoryPermutation().
~FShaderType()
virtual RENDERCORE_API FShaderType::~FShaderType () virtual
Member Function Documentation
AddUniformBufferIncludesToEnvironment()
RENDERCORE_API void FShaderType::AddUniformBufferIncludesToEnvironment (FShaderCompilerEnvironment & OutEnvironment, EShaderPlatform Platform) const
Adds include statements for uniform buffers that this shader type references.
References Platform.
AsGlobalShaderType()
const FGlobalShaderType * FShaderType::AsGlobalShaderType () const inline
Definition at line 1443 of file Shader.h.
References checkf, FORCEINLINE, GetName(), Global, ShaderTypeForDynamicCast, and TEXT.
AsMaterialShaderType()
const FMaterialShaderType * FShaderType::AsMaterialShaderType () const inline
Definition at line 1449 of file Shader.h.
References checkf, FORCEINLINE, GetName(), Material, ShaderTypeForDynamicCast, and TEXT.
AsMeshMaterialShaderType()
const FMeshMaterialShaderType * FShaderType::AsMeshMaterialShaderType () const inline
Definition at line 1455 of file Shader.h.
References checkf, FORCEINLINE, GetName(), MeshMaterial, ShaderTypeForDynamicCast, and TEXT.
AsNiagaraShaderType()
const FNiagaraShaderType * FShaderType::AsNiagaraShaderType () const inline
Definition at line 1461 of file Shader.h.
References checkf, FORCEINLINE, GetName(), Niagara, ShaderTypeForDynamicCast, and TEXT.
AsOpenColorIOShaderType()
const FOpenColorIOShaderType * FShaderType::AsOpenColorIOShaderType () const inline
Definition at line 1467 of file Shader.h.
References checkf, FORCEINLINE, GetName(), OCIO, ShaderTypeForDynamicCast, and TEXT.
ConstructCompiled()
RENDERCORE_API FShader * FShaderType::ConstructCompiled (const FShader::CompiledShaderInitializerType & Initializer) const
ConstructForDeserialization()
RENDERCORE_API FShader * FShaderType::ConstructForDeserialization () const
Constructs a new instance of the shader type for deserialization.
DumpDebugInfo()
RENDERCORE_API void FShaderType::DumpDebugInfo ()
GetComputeKernelShaderType() [1/2]
FComputeKernelShaderType * FShaderType::GetComputeKernelShaderType () inline
Definition at line 1430 of file Shader.h.
References ComputeKernel, FORCEINLINE, and ShaderTypeForDynamicCast.
GetComputeKernelShaderType() [2/2]
const FComputeKernelShaderType * FShaderType::GetComputeKernelShaderType () const inline
Definition at line 1426 of file Shader.h.
References ComputeKernel, FORCEINLINE, and ShaderTypeForDynamicCast.
GetFName()
const FName & FShaderType::GetFName () const inline
Definition at line 1491 of file Shader.h.
References TypeName.
Referenced by FGlobalShaderType::ShouldCompilePermutation(), and FGlobalShaderType::ShouldPrecachePermutation().
GetFrequency()
EShaderFrequency FShaderType::GetFrequency () const inline
Definition at line 1483 of file Shader.h.
References Frequency.
Referenced by FMaterialShaderTypes::AddShaderType().
GetFunctionName()
const TCHAR * FShaderType::GetFunctionName () const inline
Definition at line 1507 of file Shader.h.
References FunctionName.
GetGlobalShaderType() [1/2]
FGlobalShaderType * FShaderType::GetGlobalShaderType () inline
Definition at line 1386 of file Shader.h.
References FORCEINLINE, Global, and ShaderTypeForDynamicCast.
GetGlobalShaderType() [2/2]
const FGlobalShaderType * FShaderType::GetGlobalShaderType () const inline
Definition at line 1390 of file Shader.h.
References FORCEINLINE, Global, and ShaderTypeForDynamicCast.
GetHashedName()
const FHashedName & FShaderType::GetHashedName () const inline
Definition at line 1495 of file Shader.h.
References HashedName.
Referenced by FShaderMapContent::GetShader().
GetHashedShaderFilename()
const FHashedName & FShaderType::GetHashedShaderFilename () const inline
Definition at line 1503 of file Shader.h.
References HashedSourceFilename.
GetLayout()
const FTypeLayoutDesc & FShaderType::GetLayout () const inline
Definition at line 1479 of file Shader.h.
References TypeLayout.
GetMaterialShaderType() [1/2]
FMaterialShaderType * FShaderType::GetMaterialShaderType () inline
Definition at line 1394 of file Shader.h.
References FORCEINLINE, Material, and ShaderTypeForDynamicCast.
GetMaterialShaderType() [2/2]
const FMaterialShaderType * FShaderType::GetMaterialShaderType () const inline
Definition at line 1398 of file Shader.h.
References FORCEINLINE, Material, and ShaderTypeForDynamicCast.
GetMeshMaterialShaderType() [1/2]
FMeshMaterialShaderType * FShaderType::GetMeshMaterialShaderType () inline
Definition at line 1402 of file Shader.h.
References FORCEINLINE, MeshMaterial, and ShaderTypeForDynamicCast.
GetMeshMaterialShaderType() [2/2]
const FMeshMaterialShaderType * FShaderType::GetMeshMaterialShaderType () const inline
Definition at line 1406 of file Shader.h.
References FORCEINLINE, MeshMaterial, and ShaderTypeForDynamicCast.
GetName()
const TCHAR * FShaderType::GetName () const inline
Definition at line 1487 of file Shader.h.
References Name.
Referenced by AsGlobalShaderType(), AsMaterialShaderType(), AsMeshMaterialShaderType(), AsNiagaraShaderType(), and AsOpenColorIOShaderType().
GetNameToTypeMap()
RENDERCORE_API TMap< FHashedName, FShaderType * > & FShaderType::GetNameToTypeMap () static
Returns
The global shader name to type map
GetNiagaraShaderType() [1/2]
FNiagaraShaderType * FShaderType::GetNiagaraShaderType () inline
Definition at line 1414 of file Shader.h.
References FORCEINLINE, Niagara, and ShaderTypeForDynamicCast.
GetNiagaraShaderType() [2/2]
const FNiagaraShaderType * FShaderType::GetNiagaraShaderType () const inline
Definition at line 1410 of file Shader.h.
References FORCEINLINE, Niagara, and ShaderTypeForDynamicCast.
GetNNERuntimeIREEShaderType() [1/2]
FNNERuntimeIREEShaderType * FShaderType::GetNNERuntimeIREEShaderType () inline
Definition at line 1438 of file Shader.h.
References FORCEINLINE, NNERuntimeIREE, and ShaderTypeForDynamicCast.
GetNNERuntimeIREEShaderType() [2/2]
const FNNERuntimeIREEShaderType * FShaderType::GetNNERuntimeIREEShaderType () const inline
Definition at line 1434 of file Shader.h.
References FORCEINLINE, NNERuntimeIREE, and ShaderTypeForDynamicCast.
GetNumShaders()
int32 FShaderType::GetNumShaders () const inline
Definition at line 1516 of file Shader.h.
GetOpenColorIOShaderType() [1/2]
FOpenColorIOShaderType * FShaderType::GetOpenColorIOShaderType () inline
Definition at line 1422 of file Shader.h.
References FORCEINLINE, OCIO, and ShaderTypeForDynamicCast.
GetOpenColorIOShaderType() [2/2]
const FOpenColorIOShaderType * FShaderType::GetOpenColorIOShaderType () const inline
Definition at line 1418 of file Shader.h.
References FORCEINLINE, OCIO, and ShaderTypeForDynamicCast.
GetOverrideJobPriority()
RENDERCORE_API EShaderCompileJobPriority FShaderType::GetOverrideJobPriority () const
Returns a custom compile job priority or EShaderCompileJobPriority::None to ignore the customization.
GetPermutationCount()
int32 FShaderType::GetPermutationCount () const inline
Definition at line 1522 of file Shader.h.
References TotalPermutationCount.
GetPermutationIdString()
RENDERCORE_API FString FShaderType::GetPermutationIdString (int32 PermutationId, bool bFullNames) const
Returns a string representation for the specified permutation Id.
Parameters
PermutationId Zero based index in the half-open range [0, GetPermutationCount()).
bFullNames Specifies whether the full shader defines are meant to be included. If false, a short form is returned as comma-separated integers.
GetRayTracingPayloadType()
RENDERCORE_API ERayTracingPayloadType FShaderType::GetRayTracingPayloadType (const int32 PermutationId) const
GetReferencedUniformBufferNames()
const TSet< const TCHAR *, TStringPointerSetKeyFuncs_DEPRECATED< const TCHAR * > > & FShaderType::GetReferencedUniformBufferNames () const inline
Definition at line 1535 of file Shader.h.
References GetReferencedUniformBufferNames().
Referenced by GetReferencedUniformBufferNames().
GetReferencedUniformBuffers()
const TSet< const FShaderParametersMetadata * > & FShaderType::GetReferencedUniformBuffers () const inline
Definition at line 1541 of file Shader.h.
References ReferencedUniformBuffers.
GetRootParametersMetadata()
const FShaderParametersMetadata * FShaderType::GetRootParametersMetadata () const inline
Returns the meta data for the root shader parameter struct.
Definition at line 1528 of file Shader.h.
References RootParametersMetadata.
GetShaderBindingLayout()
RENDERCORE_API const FShaderBindingLayout * FShaderType::GetShaderBindingLayout (const FShaderPermutationParameters & Parameters) const
GetShaderFilename()
const TCHAR * FShaderType::GetShaderFilename () const inline
Definition at line 1499 of file Shader.h.
References SourceFilename.
GetShaderStableKeyParts()
RENDERCORE_API void FShaderType::GetShaderStableKeyParts (struct FStableShaderKeyAndValue & SaveKeyVal)
GetShaderTypeByName()
RENDERCORE_API FShaderType * FShaderType::GetShaderTypeByName (const TCHAR * Name) static
References FShaderType(), and Name.
GetShaderTypesByFilename()
RENDERCORE_API TArray< const FShaderType * > FShaderType::GetShaderTypesByFilename (const TCHAR * Filename, bool bSearchAsRegexFilter = false) static
References Filename.
GetShaderTypesByFilenameFilter()
RENDERCORE_API TArray< const FShaderType * > FShaderType::GetShaderTypesByFilenameFilter (const TFunction< bool(const TCHAR *)> & InFilenameFilter) static
GetSortedTypes()
RENDERCORE_API const TArray< FShaderType * > & FShaderType::GetSortedTypes (EShaderTypeForDynamicCast Type) static
GetSourceHash()
RENDERCORE_API const FSHAHash & FShaderType::GetSourceHash (EShaderPlatform ShaderPlatform) const
Calculates a Hash based on this shader type's source code and includes.
References ShaderPlatform.
Referenced by FShaderTypeDependency::FShaderTypeDependency().
GetTypeForDynamicCast()
EShaderTypeForDynamicCast FShaderType::GetTypeForDynamicCast () const inline
Definition at line 1473 of file Shader.h.
References ShaderTypeForDynamicCast.
GetTypeList()
RENDERCORE_API TLinkedList< FShaderType * > *& FShaderType::GetTypeList () static
Returns
The global shader factory list.
GetTypeSize()
uint32 FShaderType::GetTypeSize () const inline
Definition at line 1511 of file Shader.h.
References TypeSize.
Initialize()
RENDERCORE_API void FShaderType::Initialize (const TMap< FString, TArray< const TCHAR * > > & ShaderFileToUniformBufferVariables) static
Initialize FShaderType static members, this must be called before any shader types are created.
ModifyCompilationEnvironment()
RENDERCORE_API void FShaderType::ModifyCompilationEnvironment (const FShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) const
ShouldCompilePermutation()
RENDERCORE_API bool FShaderType::ShouldCompilePermutation (const FShaderPermutationParameters & Parameters) const
Referenced by FGlobalShaderType::ShouldCompilePermutation().
ShouldPrecachePermutation()
RENDERCORE_API EShaderPermutationPrecacheRequest FShaderType::ShouldPrecachePermutation (const FShaderPermutationParameters & Parameters) const
Referenced by FGlobalShaderType::ShouldPrecachePermutation().
Uninitialize()
RENDERCORE_API void FShaderType::Uninitialize () static
Uninitializes FShaderType cached data.
UpdateReferencedUniformBufferNames()
RENDERCORE_API void FShaderType::UpdateReferencedUniformBufferNames (const TMap< FString, TArray< const TCHAR * > > & ShaderFileToUniformBufferVariables)
ValidateCompiledResult()
RENDERCORE_API bool FShaderType::ValidateCompiledResult (EShaderPlatform Platform, const FShaderParameterMap & ParameterMap, TArray< FString > & OutError) const
Checks if the shader type should pass compilation for a particular set of parameters.
Parameters
Platform - Platform to validate.
ParameterMap - Shader parameters to validate.
OutError - List for appending validation errors.
References Platform.
Friends And Related Symbol Documentation
DumpShaderStats
void RENDERCORE_API DumpShaderStats (EShaderPlatform Platform, EShaderFrequency Frequency) friend
Dumps shader stats to the log.
Will also print some shader pipeline information.
Parameters
Platform - Platform to dump shader info for, use SP_NumPlatforms for all
Frequency - Whether to dump PS or VS info, use SF_NumFrequencies to dump both
References Frequency, and Platform.
GetTypeHash
uint32 GetTypeHash (FShaderType * Ref) friend
Hashes a pointer to a shader type.
Definition at line 1380 of file Shader.h.
References FShaderType(), and GetTypeHash.
Referenced by GetTypeHash.
operator<<
RENDERCORE_API friend FArchive & operator<< (FArchive & Ar, FShaderType *& Ref) friend
Serializes a shader type reference by name.
References FShaderType(), and Ar.
Field Documentation
bInitializedSerializationHistory
bool FShaderType::bInitializedSerializationHistory static private
Tracks whether serialization history for all shader types has been initialized.
Definition at line 1588 of file Shader.h.
ConstructCompiledRef
ConstructCompiledType FShaderType::ConstructCompiledRef private
Definition at line 1570 of file Shader.h.
ConstructSerializedRef
ConstructSerializedType FShaderType::ConstructSerializedRef private
Definition at line 1569 of file Shader.h.
Frequency
uint32 FShaderType::Frequency private
Definition at line 1565 of file Shader.h.
Referenced by DumpShaderStats, and GetFrequency().
FunctionName
const TCHAR* FShaderType::FunctionName private
Definition at line 1564 of file Shader.h.
Referenced by GetFunctionName().
GetOverrideJobPriorityRef
GetOverrideJobPriorityType FShaderType::GetOverrideJobPriorityRef private
Definition at line 1578 of file Shader.h.
GetPermutationIdStringRef
GetPermutationIdStringType FShaderType::GetPermutationIdStringRef private
Definition at line 1579 of file Shader.h.
GetRayTracingPayloadTypeRef
GetRayTracingPayloadTypeType FShaderType::GetRayTracingPayloadTypeRef private
Definition at line 1573 of file Shader.h.
GetShaderBindingLayoutTypeRef
GetShaderBindingLayoutType FShaderType::GetShaderBindingLayoutTypeRef private
Definition at line 1574 of file Shader.h.
GlobalListLink
TLinkedList<FShaderType*> FShaderType::GlobalListLink private
Definition at line 1583 of file Shader.h.
HashedName
FHashedName FShaderType::HashedName private
Definition at line 1561 of file Shader.h.
Referenced by GetHashedName().
HashedSourceFilename
FHashedName FShaderType::HashedSourceFilename private
Definition at line 1562 of file Shader.h.
Referenced by GetHashedShaderFilename().
ModifyCompilationEnvironmentRef
ModifyCompilationEnvironmentType FShaderType::ModifyCompilationEnvironmentRef private
Definition at line 1576 of file Shader.h.
Name
const TCHAR* FShaderType::Name private
Definition at line 1559 of file Shader.h.
Referenced by GetName(), and GetShaderTypeByName().
ReferencedUniformBuffers
TSet<const FShaderParametersMetadata*> FShaderType::ReferencedUniformBuffers protected
Cache of referenced uniform buffer structs.
These are derived from source files so they need to be flushed when editing and recompiling shaders on the fly. FShaderType::Initialize will add the referenced uniform buffers, but this set may be updated by FlushShaderFileCache.
Definition at line 1597 of file Shader.h.
Referenced by GetReferencedUniformBuffers().
RootParametersMetadata
const FShaderParametersMetadata* const FShaderType::RootParametersMetadata private
Definition at line 1581 of file Shader.h.
Referenced by GetRootParametersMetadata().
ShaderTypeForDynamicCast
EShaderTypeForDynamicCast FShaderType::ShaderTypeForDynamicCast private
Definition at line 1557 of file Shader.h.
Referenced by AsGlobalShaderType(), AsMaterialShaderType(), AsMeshMaterialShaderType(), AsNiagaraShaderType(), AsOpenColorIOShaderType(), GetComputeKernelShaderType(), GetComputeKernelShaderType(), GetGlobalShaderType(), GetGlobalShaderType(), GetMaterialShaderType(), GetMaterialShaderType(), GetMeshMaterialShaderType(), GetMeshMaterialShaderType(), GetNiagaraShaderType(), GetNiagaraShaderType(), GetNNERuntimeIREEShaderType(), GetNNERuntimeIREEShaderType(), GetOpenColorIOShaderType(), GetOpenColorIOShaderType(), and GetTypeForDynamicCast().
ShouldCompilePermutationRef
ShouldCompilePermutationType FShaderType::ShouldCompilePermutationRef private
Definition at line 1571 of file Shader.h.
ShouldPrecachePermutationRef
ShouldPrecachePermutationType FShaderType::ShouldPrecachePermutationRef private
Definition at line 1572 of file Shader.h.
SourceFilename
const TCHAR* FShaderType::SourceFilename private
Definition at line 1563 of file Shader.h.
Referenced by GetShaderFilename().
TotalPermutationCount
int32 FShaderType::TotalPermutationCount private
Definition at line 1567 of file Shader.h.
Referenced by FShaderType(), and GetPermutationCount().
TypeLayout
const FTypeLayoutDesc* FShaderType::TypeLayout private
Definition at line 1558 of file Shader.h.
Referenced by GetLayout().
TypeName
FName FShaderType::TypeName private
Definition at line 1560 of file Shader.h.
Referenced by GetFName().
TypeSize
uint32 FShaderType::TypeSize private
Definition at line 1566 of file Shader.h.
Referenced by GetTypeSize().
ValidateCompiledResultRef
ValidateCompiledResultType FShaderType::ValidateCompiledResultRef private
Definition at line 1577 of file Shader.h.
The documentation for this class was generated from the following file:
Shader.h