Unreal Engine 5.6 C++ API: FSkinWeightsVertexAttributesConstRef Class Reference
FSkinWeightsVertexAttributesConstRef Class Reference
#include "SkinWeightsAttributesRef.h"
Public Member Functions
FSkinWeightsVertexAttributesConstRef ()=default
FSkinWeightsVertexAttributesConstRef (const FSkinWeightsVertexAttributesConstRef &)=default
FSkinWeightsVertexAttributesConstRef (const FSkinWeightsVertexAttributesRef &InAttribs)
FSkinWeightsVertexAttributesConstRef (FSkinWeightsVertexAttributesConstRef &&) noexcept=default
FVertexBoneWeightsConst Get (FVertexID InVertexIndex) const
bool IsValid () const
FSkinWeightsVertexAttributesConstRef & operator= (const FSkinWeightsVertexAttributesConstRef &InAttributesRef)
FSkinWeightsVertexAttributesConstRef & operator= (const FSkinWeightsVertexAttributesRef &InAttribs)
FSkinWeightsVertexAttributesConstRef & operator= (FSkinWeightsVertexAttributesConstRef &&InAttributesRef) noexcept
Protected Member Functions
FSkinWeightsVertexAttributesConstRef (TVertexAttributesRef< TArrayAttribute< const int32 > > InAttributesConstRef)
FSkinWeightsVertexAttributesConstRef (TVertexAttributesRef< TArrayAttribute< int32 > > InAttributesConstRef)
Private Attributes
TVertexAttributesConstRef< TArrayAttribute< int32 > > AttributesConstRef
Friends
class FSkeletalMeshAttributes
class FSkeletalMeshAttributesShared
Detailed Description
Definition at line 224 of file SkinWeightsAttributesRef.h.
Constructor & Destructor Documentation
FSkinWeightsVertexAttributesConstRef() [1/6]
FSkinWeightsVertexAttributesConstRef::FSkinWeightsVertexAttributesConstRef () default
Referenced by FSkinWeightsVertexAttributesConstRef(), FSkinWeightsVertexAttributesConstRef(), operator=(), operator=(), and operator=().
FSkinWeightsVertexAttributesConstRef() [2/6]
FSkinWeightsVertexAttributesConstRef::FSkinWeightsVertexAttributesConstRef (const FSkinWeightsVertexAttributesConstRef &) default
References FSkinWeightsVertexAttributesConstRef().
FSkinWeightsVertexAttributesConstRef() [3/6]
FSkinWeightsVertexAttributesConstRef::FSkinWeightsVertexAttributesConstRef (FSkinWeightsVertexAttributesConstRef &&) default noexcept
References FSkinWeightsVertexAttributesConstRef().
FSkinWeightsVertexAttributesConstRef() [4/6]
FSkinWeightsVertexAttributesConstRef::FSkinWeightsVertexAttributesConstRef (const FSkinWeightsVertexAttributesRef & InAttribs) inline explicit
Definition at line 244 of file SkinWeightsAttributesRef.h.
References AttributesConstRef.
FSkinWeightsVertexAttributesConstRef() [5/6]
FSkinWeightsVertexAttributesConstRef::FSkinWeightsVertexAttributesConstRef (TVertexAttributesRef< TArrayAttribute< int32 > > InAttributesConstRef) inline protected
Definition at line 268 of file SkinWeightsAttributesRef.h.
References AttributesConstRef.
FSkinWeightsVertexAttributesConstRef() [6/6]
FSkinWeightsVertexAttributesConstRef::FSkinWeightsVertexAttributesConstRef (TVertexAttributesRef< TArrayAttribute< const int32 > > InAttributesConstRef) inline protected
Definition at line 272 of file SkinWeightsAttributesRef.h.
References AttributesConstRef.
Member Function Documentation
Get()
FVertexBoneWeightsConst FSkinWeightsVertexAttributesConstRef::Get (FVertexID InVertexIndex) const inline
Definition at line 259 of file SkinWeightsAttributesRef.h.
References AttributesConstRef.
IsValid()
bool FSkinWeightsVertexAttributesConstRef::IsValid () const inline
Definition at line 254 of file SkinWeightsAttributesRef.h.
References AttributesConstRef.
operator=() [1/3]
FSkinWeightsVertexAttributesConstRef & FSkinWeightsVertexAttributesConstRef::operator= (const FSkinWeightsVertexAttributesConstRef & InAttributesRef) inline
Definition at line 230 of file SkinWeightsAttributesRef.h.
References FSkinWeightsVertexAttributesConstRef(), and AttributesConstRef.
operator=() [2/3]
FSkinWeightsVertexAttributesConstRef & FSkinWeightsVertexAttributesConstRef::operator= (const FSkinWeightsVertexAttributesRef & InAttribs) inline
Definition at line 248 of file SkinWeightsAttributesRef.h.
References FSkinWeightsVertexAttributesConstRef(), AttributesConstRef, and FSkinWeightsVertexAttributesRef::AttributesRef.
operator=() [3/3]
FSkinWeightsVertexAttributesConstRef & FSkinWeightsVertexAttributesConstRef::operator= (FSkinWeightsVertexAttributesConstRef && InAttributesRef) inline noexcept
Definition at line 236 of file SkinWeightsAttributesRef.h.
References FSkinWeightsVertexAttributesConstRef(), AttributesConstRef, and MoveTemp().
Friends And Related Symbol Documentation
FSkeletalMeshAttributes
friend class FSkeletalMeshAttributes friend
Definition at line 265 of file SkinWeightsAttributesRef.h.
References FSkeletalMeshAttributes.
Referenced by FSkeletalMeshAttributes.
FSkeletalMeshAttributesShared
friend class FSkeletalMeshAttributesShared friend
Definition at line 266 of file SkinWeightsAttributesRef.h.
References FSkeletalMeshAttributesShared.
Referenced by FSkeletalMeshAttributesShared.
Field Documentation
AttributesConstRef
TVertexAttributesConstRef<TArrayAttribute<int32> > FSkinWeightsVertexAttributesConstRef::AttributesConstRef private
Definition at line 277 of file SkinWeightsAttributesRef.h.
Referenced by FSkinWeightsVertexAttributesConstRef(), FSkinWeightsVertexAttributesConstRef(), FSkinWeightsVertexAttributesConstRef(), Get(), IsValid(), operator=(), operator=(), and operator=().
The documentation for this class was generated from the following file:
SkinWeightsAttributesRef.h