Unreal Engine 5.6 C++ API: TRefCountPtr< ReferencedType > Class Template Reference
TRefCountPtr< ReferencedType > Class Template Reference
A smart pointer to an object which implements AddRef/Release.
#include "RefCounting.h"
Public Member Functions
FORCEINLINE TRefCountPtr ()=default
TRefCountPtr (const TRefCountPtr &Copy)
template<typename CopyReferencedType>
TRefCountPtr (const TRefCountPtr< CopyReferencedType > &Copy)
TRefCountPtr (ReferencedType *InReference, bool bAddRef=true)
FORCEINLINE TRefCountPtr (TRefCountPtr &&Move)
template<typename MoveReferencedType>
TRefCountPtr (TRefCountPtr< MoveReferencedType > &&Move)
~TRefCountPtr ()
FORCEINLINE ReferencedType ** GetInitReference ()
uint32 GetRefCount ()
FORCEINLINE ReferencedType * GetReference () const
FORCEINLINE bool IsValid () const
FORCEINLINE operator ReferenceType () const
FORCEINLINE ReferencedType * operator-> () const
FORCEINLINE TRefCountPtr & operator= (const TRefCountPtr &InPtr)
template<typename CopyReferencedType>
FORCEINLINE TRefCountPtr & operator= (const TRefCountPtr< CopyReferencedType > &InPtr)
TRefCountPtr & operator= (ReferencedType *InReference)
TRefCountPtr & operator= (TRefCountPtr &&InPtr)
template<typename MoveReferencedType>
TRefCountPtr & operator= (TRefCountPtr< MoveReferencedType > &&InPtr)
FORCEINLINE bool operator== (const TRefCountPtr &B) const
FORCEINLINE bool operator== (ReferencedType *B) const
FORCEINLINE void SafeRelease ()
void Serialize (FArchive &Ar)
FORCEINLINE void Swap (TRefCountPtr &InPtr)
Private Types
using ReferenceType = ReferencedType*
Private Attributes
ReferencedType * Reference = nullptr
Friends
template<typename OtherType>
class TRefCountPtr
FORCEINLINE friend bool IsValidRef (const TRefCountPtr &InReference)
Detailed Description
template<typename ReferencedType>
class TRefCountPtr< ReferencedType >
A smart pointer to an object which implements AddRef/Release.
Definition at line 453 of file RefCounting.h.
Member Typedef Documentation
ReferenceType
template<typename ReferencedType> using TRefCountPtr< ReferencedType >::ReferenceType = ReferencedType* private
Definition at line 455 of file RefCounting.h.
Constructor & Destructor Documentation
TRefCountPtr() [1/6]
template<typename ReferencedType> FORCEINLINE TRefCountPtr< ReferencedType >::TRefCountPtr () default
TRefCountPtr() [2/6]
template<typename ReferencedType> TRefCountPtr< ReferencedType >::TRefCountPtr (ReferencedType * InReference, bool bAddRef = true) inline
Definition at line 460 of file RefCounting.h.
TRefCountPtr() [3/6]
template<typename ReferencedType> TRefCountPtr< ReferencedType >::TRefCountPtr (const TRefCountPtr< ReferencedType > & Copy) inline
Definition at line 469 of file RefCounting.h.
TRefCountPtr() [4/6]
template<typename ReferencedType> template<typename CopyReferencedType> TRefCountPtr< ReferencedType >::TRefCountPtr (const TRefCountPtr< CopyReferencedType > & Copy) inline explicit
Definition at line 479 of file RefCounting.h.
TRefCountPtr() [5/6]
template<typename ReferencedType> FORCEINLINE TRefCountPtr< ReferencedType >::TRefCountPtr (TRefCountPtr< ReferencedType > && Move) inline
Definition at line 488 of file RefCounting.h.
TRefCountPtr() [6/6]
template<typename ReferencedType> template<typename MoveReferencedType> TRefCountPtr< ReferencedType >::TRefCountPtr (TRefCountPtr< MoveReferencedType > && Move) inline explicit
Definition at line 495 of file RefCounting.h.
~TRefCountPtr()
template<typename ReferencedType> TRefCountPtr< ReferencedType >::~TRefCountPtr () inline
Definition at line 501 of file RefCounting.h.
Member Function Documentation
GetInitReference()
template<typename ReferencedType> FORCEINLINE ReferencedType ** TRefCountPtr< ReferencedType >::GetInitReference () inline
Definition at line 578 of file RefCounting.h.
GetRefCount()
template<typename ReferencedType> uint32 TRefCountPtr< ReferencedType >::GetRefCount () inline
Definition at line 604 of file RefCounting.h.
GetReference()
template<typename ReferencedType> FORCEINLINE ReferencedType * TRefCountPtr< ReferencedType >::GetReference () const inline
Definition at line 584 of file RefCounting.h.
Referenced by FDelegateGraphTask::CreateAndDispatchWhenReady(), FFunctionGraphTask::CreateAndDispatchWhenReady(), FFunctionGraphTask::CreateAndDispatchWhenReady(), FSimpleDelegateGraphTask::CreateAndDispatchWhenReady(), UE::UnifiedError::FError::GetErrorContext(), UE::UnifiedError::FError::GetErrorDetails(), GetTypeHash(), TRefCountPtr< FBaseGraphTask >::operator=(), TRefCountPtr< FBaseGraphTask >::operator==(), and TRefCountPtr< FBaseGraphTask >::operator==().
IsValid()
template<typename ReferencedType> FORCEINLINE bool TRefCountPtr< ReferencedType >::IsValid () const inline
Definition at line 594 of file RefCounting.h.
Referenced by FQueuedLowLevelThreadPool::RetractQueuedWork().
operator ReferenceType()
template<typename ReferencedType> FORCEINLINE TRefCountPtr< ReferencedType >::operator ReferenceType () const inline
Definition at line 573 of file RefCounting.h.
operator->()
template<typename ReferencedType> FORCEINLINE ReferencedType * TRefCountPtr< ReferencedType >::operator-> () const inline
Definition at line 568 of file RefCounting.h.
operator=() [1/5]
template<typename ReferencedType> FORCEINLINE TRefCountPtr & TRefCountPtr< ReferencedType >::operator= (const TRefCountPtr< ReferencedType > & InPtr) inline
Definition at line 528 of file RefCounting.h.
operator=() [2/5]
template<typename ReferencedType> template<typename CopyReferencedType> FORCEINLINE TRefCountPtr & TRefCountPtr< ReferencedType >::operator= (const TRefCountPtr< CopyReferencedType > & InPtr) inline
Definition at line 534 of file RefCounting.h.
operator=() [3/5]
template<typename ReferencedType> TRefCountPtr & TRefCountPtr< ReferencedType >::operator= (ReferencedType * InReference) inline
Definition at line 509 of file RefCounting.h.
operator=() [4/5]
template<typename ReferencedType> TRefCountPtr & TRefCountPtr< ReferencedType >::operator= (TRefCountPtr< ReferencedType > && InPtr) inline
Definition at line 539 of file RefCounting.h.
operator=() [5/5]
template<typename ReferencedType> template<typename MoveReferencedType> TRefCountPtr & TRefCountPtr< ReferencedType >::operator= (TRefCountPtr< MoveReferencedType > && InPtr) inline
Definition at line 555 of file RefCounting.h.
operator==() [1/2]
template<typename ReferencedType> FORCEINLINE bool TRefCountPtr< ReferencedType >::operator== (const TRefCountPtr< ReferencedType > & B) const inline
Definition at line 639 of file RefCounting.h.
operator==() [2/2]
template<typename ReferencedType> FORCEINLINE bool TRefCountPtr< ReferencedType >::operator== (ReferencedType * B) const inline
Definition at line 644 of file RefCounting.h.
SafeRelease()
template<typename ReferencedType> FORCEINLINE void TRefCountPtr< ReferencedType >::SafeRelease () inline
Definition at line 599 of file RefCounting.h.
Referenced by TIndexedPtrBase< T, T * >::SafeReleaseImpl().
Serialize()
template<typename ReferencedType> void TRefCountPtr< ReferencedType >::Serialize (FArchive & Ar) inline
Definition at line 622 of file RefCounting.h.
Referenced by operator<<().
Swap()
template<typename ReferencedType> FORCEINLINE void TRefCountPtr< ReferencedType >::Swap (TRefCountPtr< ReferencedType > & InPtr) inline
Definition at line 615 of file RefCounting.h.
Friends And Related Symbol Documentation
TRefCountPtr
template<typename ReferencedType> template<typename OtherType> friend class TRefCountPtr friend
Definition at line 636 of file RefCounting.h.
IsValidRef
template<typename ReferencedType> FORCEINLINE friend bool IsValidRef (const TRefCountPtr< ReferencedType > & InReference) friend
Definition at line 589 of file RefCounting.h.
Field Documentation
Reference
template<typename ReferencedType> ReferencedType* TRefCountPtr< ReferencedType >::Reference = nullptr private
Definition at line 633 of file RefCounting.h.
Referenced by TRefCountPtr< FBaseGraphTask >::IsValidRef, TRefCountPtr< FBaseGraphTask >::operator=(), and TRefCountPtr< FBaseGraphTask >::Swap().
The documentation for this class was generated from the following file:
RefCounting.h