Unreal Engine 5.6 C++ API: UE::SoundWaveLoadingUtil::Private Namespace Reference
UE::SoundWaveLoadingUtil::Private Namespace Reference
Functions
void HashSoundWaveLoadingBehaviorDependenciesForCook (FCbFieldViewIterator Args, UE::Cook::FCookDependencyContext &Context)
void RecordSoundWaveLoadingBehaviorDependenciesForCook (UE::Cook::FCookEventContext &CookContext, const USoundWave *SoundWave)
UE_COOK_DEPENDENCY_FUNCTION (HashSoundWaveLoadingBehaviorDependenciesForCook, HashSoundWaveLoadingBehaviorDependenciesForCook)
Variables
constexpr int32 HashSoundWaveLoadingBehaviorDependenciesForCookArgsVersion = 1
Function Documentation
HashSoundWaveLoadingBehaviorDependenciesForCook()
void UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook (FCbFieldViewIterator Args, UE::Cook::FCookDependencyContext & Context)
Definition at line 300 of file SoundWaveLoadingBehavior.cpp.
References TArray< InElementType, InAllocatorType >::Add(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), ISoundWaveLoadingBehaviorUtil::Get(), TStringBuilderBase< CharType >::GetData(), HashSoundWaveLoadingBehaviorDependenciesForCookArgsVersion, InPlace, TStringBuilderBase< CharType >::Len(), Algo::Sort(), and TEXT.
Referenced by RecordSoundWaveLoadingBehaviorDependenciesForCook(), and UE_COOK_DEPENDENCY_FUNCTION().
RecordSoundWaveLoadingBehaviorDependenciesForCook()
void UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook (UE::Cook::FCookEventContext & CookContext, const USoundWave * SoundWave)
Definition at line 337 of file SoundWaveLoadingBehavior.cpp.
References UE::Cook::FCookEventContext::AddLoadBuildDependency(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), UE::Cook::FCookDependency::ConsoleVariable(), UE::Cook::FCookDependency::Function(), ISoundWaveLoadingBehaviorUtil::Get(), FSoundWaveLoadingBehaviorUtil::GetChainOfClassesForLoadingBehaviorInheritance(), USoundWave::GetDefaultLoadingBehaviorCVarName(), HashSoundWaveLoadingBehaviorDependenciesForCook(), HashSoundWaveLoadingBehaviorDependenciesForCookArgsVersion, UE::Cook::FCookDependency::Package(), FCbWriter::Save(), SoundCue, and UE_COOK_DEPENDENCY_FUNCTION_CALL.
UE_COOK_DEPENDENCY_FUNCTION()
UE::SoundWaveLoadingUtil::Private::UE_COOK_DEPENDENCY_FUNCTION (HashSoundWaveLoadingBehaviorDependenciesForCook , HashSoundWaveLoadingBehaviorDependenciesForCook)
References HashSoundWaveLoadingBehaviorDependenciesForCook().
Variable Documentation
HashSoundWaveLoadingBehaviorDependenciesForCookArgsVersion
int32 UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCookArgsVersion = 1 constexpr
Definition at line 299 of file SoundWaveLoadingBehavior.cpp.
Referenced by HashSoundWaveLoadingBehaviorDependenciesForCook(), and RecordSoundWaveLoadingBehaviorDependenciesForCook().