Unreal Engine 5.6 C++ API: TraceServices::TCachedPagedArray< InItemType, PageSize > Class Template Reference
TraceServices::TCachedPagedArray< InItemType, PageSize > Class Template Reference
A typed paged array allowing persistent storage of the data.
#include "CachedPagedArray.h"
Public Types
typedef InItemType ItemType
Public Member Functions
TCachedPagedArray (const TCHAR *InCacheId, IAnalysisCache &InCache, uint32 InResidentPages=~0)
template<typename... ArgsType>
ItemType & EmplaceBack (ArgsType &&... Args)
uint64 Num () const
uint32 NumPages () const
ItemType & operator[] (uint64 Index)
Private Member Functions
void EvictPages ()
void GetItemsFromPage (uint64 PageIndex, ItemType **OutFirstItem, ItemType **OutLastItem) const
ItemType * GetPage (uint32 InPageIndex)
ItemType * GetPageForNextItem ()
Private Attributes
IAnalysisCache & Cache
uint32 CacheId
uint64 * ElementCount
TArray< ItemType * > Pages
uint32 ResidentPageCount
TArray< FSharedBuffer > ResidentPages
Static Private Attributes
static constexpr uint32 BlocksPerPage = (PageSizeBytes + IAnalysisCache::BlockSizeBytes - 1) / IAnalysisCache::BlockSizeBytes
static constexpr uint32 PageSizeBytes = sizeof(ItemType) * PageSize
static constexpr uint32 WastePerPage = (BlocksPerPage * IAnalysisCache::BlockSizeBytes) - PageSizeBytes
Detailed Description
template<typename InItemType, unsigned int PageSize>
class TraceServices::TCachedPagedArray< InItemType, PageSize >
A typed paged array allowing persistent storage of the data.
User defines page size (in number of elements) which defines the size of the page. The page is then mapped to a number of cache blocks. The blocks are always loaded into a coherent buffer. +----------------------------------------------------------------—+ | Page | +----------------------------------------------------------------—+ | | | | | | | | v v v v +---------------------------------------------------------------------------—+ | Block n | Block n+1 | Block n+2 | Block n+3 | +---------------------------------------------------------------------------—+
Depending on the page size there could be some blocks that are only partially used.
The container supports unloading pages for extremely large datasets by defining the number of resident pages. Once the limit is reached pages are unloaded. Pages are lazily loaded on access.
Definition at line 32 of file CachedPagedArray.h.
Member Typedef Documentation
ItemType
template<typename InItemType, unsigned int PageSize> typedef InItemType TraceServices::TCachedPagedArray< InItemType, PageSize >::ItemType
Definition at line 35 of file CachedPagedArray.h.
Constructor & Destructor Documentation
TCachedPagedArray()
template<typename InItemType, unsigned int PageSize> TraceServices::TCachedPagedArray< InItemType, PageSize >::TCachedPagedArray (const TCHAR * InCacheId, IAnalysisCache & InCache, uint32 InResidentPages = ~0) inline
Definition at line 37 of file CachedPagedArray.h.
References Cache, CacheId, check, ElementCount, TMemoryView< DataType >::GetData(), GetPage(), TMemoryView< DataType >::GetSize(), NumPages(), Pages, and ResidentPageCount.
Member Function Documentation
EmplaceBack()
template<typename InItemType, unsigned int PageSize> template<typename... ArgsType> ItemType & TraceServices::TCachedPagedArray< InItemType, PageSize >::EmplaceBack (ArgsType &&... Args) inline
Definition at line 61 of file CachedPagedArray.h.
References ElementCount, Forward(), and GetPageForNextItem().
EvictPages()
template<typename InItemType, unsigned int PageSize> void TraceServices::TCachedPagedArray< InItemType, PageSize >::EvictPages () inline private
Definition at line 132 of file CachedPagedArray.h.
References check, TraceServices::GetData(), INDEX_NONE, Pages, ResidentPageCount, and ResidentPages.
Referenced by GetPage(), and GetPageForNextItem().
GetItemsFromPage()
template<typename InItemType, unsigned int PageSize> void TraceServices::TCachedPagedArray< InItemType, PageSize >::GetItemsFromPage (uint64 PageIndex, ItemType ** OutFirstItem, ItemType ** OutLastItem) const inline private
Definition at line 111 of file CachedPagedArray.h.
References TraceServices::Count, ElementCount, GetPage(), and Pages.
GetPage()
template<typename InItemType, unsigned int PageSize> ItemType * TraceServices::TCachedPagedArray< InItemType, PageSize >::GetPage (uint32 InPageIndex) inline private
Definition at line 119 of file CachedPagedArray.h.
References BlocksPerPage, Cache, CacheId, EvictPages(), Pages, and ResidentPages.
Referenced by TCachedPagedArray(), GetItemsFromPage(), and operator[]().
GetPageForNextItem()
template<typename InItemType, unsigned int PageSize> ItemType * TraceServices::TCachedPagedArray< InItemType, PageSize >::GetPageForNextItem () inline private
Definition at line 100 of file CachedPagedArray.h.
References BlocksPerPage, Cache, CacheId, ElementCount, EvictPages(), FSharedBuffer::GetData(), Pages, and ResidentPages.
Referenced by EmplaceBack().
Num()
template<typename InItemType, unsigned int PageSize> uint64 TraceServices::TCachedPagedArray< InItemType, PageSize >::Num () const inline
Definition at line 90 of file CachedPagedArray.h.
References ElementCount.
NumPages()
template<typename InItemType, unsigned int PageSize> uint32 TraceServices::TCachedPagedArray< InItemType, PageSize >::NumPages () const inline
Definition at line 85 of file CachedPagedArray.h.
References ElementCount.
Referenced by TCachedPagedArray().
operator[]()
template<typename InItemType, unsigned int PageSize> ItemType & TraceServices::TCachedPagedArray< InItemType, PageSize >::operator[] (uint64 Index) inline
Definition at line 72 of file CachedPagedArray.h.
References check, ElementCount, GetPage(), and Pages.
Field Documentation
BlocksPerPage
template<typename InItemType, unsigned int PageSize> uint32 TraceServices::TCachedPagedArray< InItemType, PageSize >::BlocksPerPage = (PageSizeBytes + IAnalysisCache::BlockSizeBytes - 1) / IAnalysisCache::BlockSizeBytes static constexpr private
Definition at line 97 of file CachedPagedArray.h.
Referenced by GetPage(), and GetPageForNextItem().
Cache
template<typename InItemType, unsigned int PageSize> IAnalysisCache& TraceServices::TCachedPagedArray< InItemType, PageSize >::Cache private
Definition at line 145 of file CachedPagedArray.h.
Referenced by TCachedPagedArray(), GetPage(), and GetPageForNextItem().
CacheId
template<typename InItemType, unsigned int PageSize> uint32 TraceServices::TCachedPagedArray< InItemType, PageSize >::CacheId private
Definition at line 148 of file CachedPagedArray.h.
Referenced by TCachedPagedArray(), GetPage(), and GetPageForNextItem().
ElementCount
template<typename InItemType, unsigned int PageSize> uint64* TraceServices::TCachedPagedArray< InItemType, PageSize >::ElementCount private
Definition at line 150 of file CachedPagedArray.h.
Referenced by TCachedPagedArray(), EmplaceBack(), GetItemsFromPage(), GetPageForNextItem(), Num(), NumPages(), and operator[]().
Pages
template<typename InItemType, unsigned int PageSize> TArray<ItemType*> TraceServices::TCachedPagedArray< InItemType, PageSize >::Pages private
Definition at line 146 of file CachedPagedArray.h.
Referenced by TCachedPagedArray(), EvictPages(), GetItemsFromPage(), GetPage(), GetPageForNextItem(), and operator[]().
PageSizeBytes
template<typename InItemType, unsigned int PageSize> uint32 TraceServices::TCachedPagedArray< InItemType, PageSize >::PageSizeBytes = sizeof(ItemType) * PageSize static constexpr private
Definition at line 96 of file CachedPagedArray.h.
ResidentPageCount
template<typename InItemType, unsigned int PageSize> uint32 TraceServices::TCachedPagedArray< InItemType, PageSize >::ResidentPageCount private
Definition at line 149 of file CachedPagedArray.h.
Referenced by TCachedPagedArray(), and EvictPages().
ResidentPages
template<typename InItemType, unsigned int PageSize> TArray<FSharedBuffer> TraceServices::TCachedPagedArray< InItemType, PageSize >::ResidentPages private
Definition at line 147 of file CachedPagedArray.h.
Referenced by EvictPages(), GetPage(), and GetPageForNextItem().
WastePerPage
template<typename InItemType, unsigned int PageSize> uint32 TraceServices::TCachedPagedArray< InItemType, PageSize >::WastePerPage = (BlocksPerPage * IAnalysisCache::BlockSizeBytes) - PageSizeBytes static constexpr private
Definition at line 98 of file CachedPagedArray.h.
The documentation for this class was generated from the following file:
CachedPagedArray.h