Unreal Engine 5.6 C++ API: UE::Geometry::FRefCountVector Class Reference
UE::Geometry::FRefCountVector Class Reference
FRefCountVector is used to keep track of which indices in a linear Index list are in use/referenced.
#include "RefCountVector.h"
Data Structures
class BaseIterator
base iterator for indices with valid refcount (skips zero-refcount indices)
class FilteredEnumerable
class IndexEnumerable
enumerable object that provides begin()/end() semantics, so you can iterate over valid indices using range-based for loop
class IndexIterator
class MappedEnumerable
Public Member Functions
FRefCountVector ()=default
FRefCountVector (const FRefCountVector &)=default
FRefCountVector (FRefCountVector &&)=default
int Allocate ()
bool AllocateAt (int Index)
allocate at specific Index, which must either be larger than current max Index, or on the free list.
bool AllocateAtUnsafe (int Index)
allocate at specific Index, which must be free or larger than current max Index.
void Append (const FRefCountVector &Other)
IndexIterator BeginIndices () const
void Clear ()
void Decrement (int Index, unsigned short DecrementCount=1)
IndexIterator EndIndices () const
FilteredEnumerable FilteredIndices (TFunction< bool(int)> FilterFunc) const
SIZE_T GetByteCount () const
size_t GetCount () const
size_t GetMaxIndex () const
int GetRawRefCount (int Index) const
const TDynamicVector< unsigned short > & GetRawRefCounts () const
TDynamicVector< unsigned short > & GetRawRefCountsUnsafe ()
int GetRefCount (int Index) const
int Increment (int Index, unsigned short IncrementCount=1)
IndexEnumerable Indices () const
returns iteration object over valid indices usage: for (int idx : indices()) { ... }
bool IsDense () const
bool IsEmpty () const
bool IsValid (int Index) const
bool IsValidUnsafe (int Index) const
template<typename ToType>
MappedEnumerable< ToType > MappedIndices (TFunction< ToType(int)> MapFunc) const
returns iteration object over mapping applied to valid indices eg usage: for (FVector3d v : mapped_indices(fn_that_looks_up_mesh_vtx_from_id)) { ... }
FRefCountVector & operator= (const FRefCountVector &)=default
FRefCountVector & operator= (FRefCountVector &&)=default
template<typename IterateFunc, typename AllocateRefCountFunc, typename IncrementRefCountFunc>
void Rebuild (unsigned int Num, IterateFunc &&Iterate, AllocateRefCountFunc &&AllocateRefCount, IncrementRefCountFunc &&IncrementRefCount)
Rebuilds all reference counts from external source data via callables.
void RebuildFreeList ()
void Serialize (FArchive &Ar, bool bCompactData, bool bUseCompression)
Serialize FRefCountVector to an archive.
void SetRefCountUnsafe (int Index, unsigned short ToCount)
void Trim (int maxIndex)
FString UsageStats () const
Static Public Attributes
static constexpr unsigned short INVALID_REF_COUNT = MAX_uint16
Private Attributes
TDynamicVector< int > FreeIndices {}
TDynamicVector< unsigned short > RefCounts {}
int UsedCount {0}
Friends
bool operator!= (const FRefCountVector &Lhs, const FRefCountVector &Rhs)
FArchive & operator<< (FArchive &Ar, FRefCountVector &Vec)
Serialization operator for FRefCountVector.
bool operator== (const FRefCountVector &Lhs, const FRefCountVector &Rhs)
Detailed Description
FRefCountVector is used to keep track of which indices in a linear Index list are in use/referenced.
A free list is tracked so that unreferenced indices can be re-used.
The enumerator iterates over valid indices (ie where refcount > 0)
Warning
refcounts are 16-bit ints (shorts) so the maximum count is 65536. behavior is undefined if this overflows.
No overflow checking is done in release builds.
Definition at line 24 of file RefCountVector.h.
Constructor & Destructor Documentation
FRefCountVector() [1/3]
UE::Geometry::FRefCountVector::FRefCountVector () default
Referenced by FRefCountVector(), FRefCountVector(), UE::Geometry::FRefCountVector::IndexEnumerable::IndexEnumerable(), Append(), operator!=, operator<<, operator=(), operator=(), and operator==.
FRefCountVector() [2/3]
UE::Geometry::FRefCountVector::FRefCountVector (const FRefCountVector &) default
References FRefCountVector().
FRefCountVector() [3/3]
UE::Geometry::FRefCountVector::FRefCountVector (FRefCountVector &&) default
References FRefCountVector().
Member Function Documentation
Allocate()
int UE::Geometry::FRefCountVector::Allocate () inline
Definition at line 91 of file RefCountVector.h.
References FreeIndices, INDEX_NONE, RefCounts, and UsedCount.
AllocateAt()
bool UE::Geometry::FRefCountVector::AllocateAt (int Index) inline
allocate at specific Index, which must either be larger than current max Index, or on the free list.
If larger, all elements up to this one will be pushed onto free list. otherwise we have to do a linear search through free list. If you are doing many of these, it is likely faster to use AllocateAtUnsafe(), and then RebuildFreeList() after you are done.
Definition at line 147 of file RefCountVector.h.
References FreeIndices, INVALID_REF_COUNT, IsValidUnsafe(), RefCounts, and UsedCount.
AllocateAtUnsafe()
bool UE::Geometry::FRefCountVector::AllocateAtUnsafe (int Index) inline
allocate at specific Index, which must be free or larger than current max Index.
However, we do not update free list. So, you probably need to do RebuildFreeList() after calling this.
Definition at line 189 of file RefCountVector.h.
References INVALID_REF_COUNT, IsValidUnsafe(), RefCounts, and UsedCount.
Append()
void UE::Geometry::FRefCountVector::Append (const FRefCountVector & Other) inline
Definition at line 78 of file RefCountVector.h.
References FRefCountVector(), FreeIndices, Other, RefCounts, and UsedCount.
BeginIndices()
IndexIterator UE::Geometry::FRefCountVector::BeginIndices () const inline
Definition at line 411 of file RefCountVector.h.
References RefCounts.
Clear()
void UE::Geometry::FRefCountVector::Clear () inline
Definition at line 321 of file RefCountVector.h.
References FreeIndices, RefCounts, and UsedCount.
Decrement()
void UE::Geometry::FRefCountVector::Decrement (int Index, unsigned short DecrementCount = 1) inline
Definition at line 128 of file RefCountVector.h.
References checkSlow, FreeIndices, INVALID_REF_COUNT, RefCounts, and UsedCount.
EndIndices()
IndexIterator UE::Geometry::FRefCountVector::EndIndices () const inline
Definition at line 416 of file RefCountVector.h.
References RefCounts.
FilteredIndices()
FilteredEnumerable UE::Geometry::FRefCountVector::FilteredIndices (TFunction< bool(int)> FilterFunc) const inline
Definition at line 508 of file RefCountVector.h.
References Indices().
GetByteCount()
SIZE_T UE::Geometry::FRefCountVector::GetByteCount () const inline
Definition at line 519 of file RefCountVector.h.
References FreeIndices, and RefCounts.
GetCount()
size_t UE::Geometry::FRefCountVector::GetCount () const inline
Definition at line 40 of file RefCountVector.h.
References UsedCount.
Referenced by operator==.
GetMaxIndex()
size_t UE::Geometry::FRefCountVector::GetMaxIndex () const inline
Definition at line 45 of file RefCountVector.h.
References RefCounts.
Referenced by operator==.
GetRawRefCount()
int UE::Geometry::FRefCountVector::GetRawRefCount (int Index) const inline
Definition at line 71 of file RefCountVector.h.
References RefCounts.
GetRawRefCounts()
const TDynamicVector< unsigned short > & UE::Geometry::FRefCountVector::GetRawRefCounts () const inline
Definition at line 217 of file RefCountVector.h.
References RefCounts.
GetRawRefCountsUnsafe()
TDynamicVector< unsigned short > & UE::Geometry::FRefCountVector::GetRawRefCountsUnsafe () inline
Warning
you should not use this!
Definition at line 225 of file RefCountVector.h.
References RefCounts.
GetRefCount()
int UE::Geometry::FRefCountVector::GetRefCount (int Index) const inline
Definition at line 65 of file RefCountVector.h.
References INVALID_REF_COUNT, and RefCounts.
Referenced by operator==.
Increment()
int UE::Geometry::FRefCountVector::Increment (int Index, unsigned short IncrementCount = 1) inline
Definition at line 121 of file RefCountVector.h.
References checkSlow, INVALID_REF_COUNT, and RefCounts.
Indices()
IndexEnumerable UE::Geometry::FRefCountVector::Indices () const inline
returns iteration object over valid indices usage: for (int idx : indices()) { ... }
Definition at line 439 of file RefCountVector.h.
Referenced by FilteredIndices(), and MappedIndices().
IsDense()
bool UE::Geometry::FRefCountVector::IsDense () const inline
Definition at line 50 of file RefCountVector.h.
References FreeIndices.
IsEmpty()
bool UE::Geometry::FRefCountVector::IsEmpty () const inline
Definition at line 35 of file RefCountVector.h.
References UsedCount.
IsValid()
bool UE::Geometry::FRefCountVector::IsValid (int Index) const inline
Definition at line 55 of file RefCountVector.h.
References IsValidUnsafe(), and RefCounts.
Referenced by operator==.
IsValidUnsafe()
bool UE::Geometry::FRefCountVector::IsValidUnsafe (int Index) const inline
Definition at line 60 of file RefCountVector.h.
References INVALID_REF_COUNT, and RefCounts.
Referenced by AllocateAt(), AllocateAtUnsafe(), UE::Geometry::FRefCountVector::BaseIterator::goto_next(), IsValid(), and RebuildFreeList().
MappedIndices()
template<typename ToType> MappedEnumerable< ToType > UE::Geometry::FRefCountVector::MappedIndices (TFunction< ToType(int)> MapFunc) const inline
returns iteration object over mapping applied to valid indices eg usage: for (FVector3d v : mapped_indices(fn_that_looks_up_mesh_vtx_from_id)) { ... }
Definition at line 478 of file RefCountVector.h.
References Indices().
operator=() [1/2]
FRefCountVector & UE::Geometry::FRefCountVector::operator= (const FRefCountVector &) default
References FRefCountVector().
operator=() [2/2]
FRefCountVector & UE::Geometry::FRefCountVector::operator= (FRefCountVector &&) default
References FRefCountVector().
Rebuild()
template<typename IterateFunc, typename AllocateRefCountFunc, typename IncrementRefCountFunc> void UE::Geometry::FRefCountVector::Rebuild (unsigned int Num, IterateFunc && Iterate, AllocateRefCountFunc && AllocateRefCount, IncrementRefCountFunc && IncrementRefCount) inline
Rebuilds all reference counts from external source data via callables.
For example, we could rebuild ref counts for vertices by iterating over all triangles via the Iterate callable, and in the process any vertex we encounter for the first time gets a ref count of 1 via the AllocateRefCount callable, and any vertex we encounter repeatedly has its ref count incremented by one via the IncrementRefCount callable.
Parameters
Num Number of items that get referenced.
Iterate Callable that iterates over all referenced items in the external source data.
AllocateRefCount Callable for allocating an item, i.e. an item that is referenced for the first time.
IncrementRefCount Callable for incrementing an item, i.e. an item that has been referenced before.
Definition at line 255 of file RefCountVector.h.
References Forward(), FreeIndices, INVALID_REF_COUNT, Num, RefCounts, and UsedCount.
RebuildFreeList()
void UE::Geometry::FRefCountVector::RebuildFreeList () inline
Definition at line 295 of file RefCountVector.h.
References FreeIndices, IsValidUnsafe(), RefCounts, and UsedCount.
Serialize()
void UE::Geometry::FRefCountVector::Serialize (FArchive & Ar, bool bCompactData, bool bUseCompression) inline
Serialize FRefCountVector to an archive.
Parameters
Ar Archive to serialize with
bCompactData Only serialize unique data and/or recompute redundant data when loading.
bUseCompression Use compression to serialize data; the resulting size will likely be smaller but serialization will take significantly longer.
Definition at line 543 of file RefCountVector.h.
References Ar, ensure, FreeIndices, FUE5MainStreamObjectVersion::GUID, INVALID_REF_COUNT, Num, RefCounts, and UsedCount.
Referenced by operator<<.
SetRefCountUnsafe()
void UE::Geometry::FRefCountVector::SetRefCountUnsafe (int Index, unsigned short ToCount) inline
Warning
you should not use this!
Definition at line 233 of file RefCountVector.h.
References RefCounts.
Trim()
void UE::Geometry::FRefCountVector::Trim (int maxIndex) inline
Definition at line 314 of file RefCountVector.h.
References FreeIndices, RefCounts, and UsedCount.
UsageStats()
FString UE::Geometry::FRefCountVector::UsageStats () const inline
Definition at line 513 of file RefCountVector.h.
References FreeIndices, RefCounts, and TEXT.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FRefCountVector & Lhs, const FRefCountVector & Rhs) friend
Definition at line 635 of file RefCountVector.h.
References FRefCountVector().
operator<<
FArchive & operator<< (FArchive & Ar, FRefCountVector & Vec) friend
Serialization operator for FRefCountVector.
Parameters
Ar Archive to serialize with.
Vec Vector to serialize.
Returns
Passing down serializing archive.
Definition at line 531 of file RefCountVector.h.
References FRefCountVector(), Ar, and Serialize().
operator==
bool operator== (const FRefCountVector & Lhs, const FRefCountVector & Rhs) friend
Definition at line 611 of file RefCountVector.h.
References FRefCountVector(), GetCount(), GetMaxIndex(), GetRefCount(), IsValid(), FMath::Max, and Num.
Field Documentation
FreeIndices
TDynamicVector<int> UE::Geometry::FRefCountVector::FreeIndices {} private
Definition at line 642 of file RefCountVector.h.
Referenced by Allocate(), AllocateAt(), Append(), Clear(), Decrement(), GetByteCount(), IsDense(), Rebuild(), RebuildFreeList(), Serialize(), Trim(), and UsageStats().
INVALID_REF_COUNT
unsigned short UE::Geometry::FRefCountVector::INVALID_REF_COUNT = MAX_uint16 static constexpr
Definition at line 27 of file RefCountVector.h.
Referenced by AllocateAt(), AllocateAtUnsafe(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactInPlace(), Decrement(), GetRefCount(), Increment(), IsValidUnsafe(), Rebuild(), and Serialize().
RefCounts
TDynamicVector<unsigned short> UE::Geometry::FRefCountVector::RefCounts {} private
Definition at line 641 of file RefCountVector.h.
Referenced by Allocate(), AllocateAt(), AllocateAtUnsafe(), Append(), BeginIndices(), Clear(), Decrement(), EndIndices(), GetByteCount(), GetMaxIndex(), GetRawRefCount(), GetRawRefCounts(), GetRawRefCountsUnsafe(), GetRefCount(), Increment(), IsValid(), IsValidUnsafe(), Rebuild(), RebuildFreeList(), Serialize(), SetRefCountUnsafe(), Trim(), and UsageStats().
UsedCount
int UE::Geometry::FRefCountVector::UsedCount {0} private
Definition at line 643 of file RefCountVector.h.
Referenced by Allocate(), AllocateAt(), AllocateAtUnsafe(), Append(), Clear(), Decrement(), GetCount(), IsEmpty(), Rebuild(), RebuildFreeList(), Serialize(), and Trim().
The documentation for this class was generated from the following file:
RefCountVector.h