Unreal Engine 5.6 C++ API: TComponentReregisterContext< ComponentType > Class Template Reference
TComponentReregisterContext< ComponentType > Class Template Reference
Removes all components of the templated type from their scenes for the lifetime of the class.
#include "ComponentReregisterContext.h"
Public Member Functions
TComponentReregisterContext ()
Initialization constructor.
~TComponentReregisterContext ()
Private Member Functions
void UpdateAllPrimitiveSceneInfos ()
Private Attributes
TIndirectArray< FComponentReregisterContext > ComponentContexts
The recreate contexts for the individual components.
TSet< FSceneInterface * > ScenesToUpdateAllPrimitiveSceneInfos
Detailed Description
template<class ComponentType>
class TComponentReregisterContext< ComponentType >
Removes all components of the templated type from their scenes for the lifetime of the class.
Definition at line 161 of file ComponentReregisterContext.h.
Constructor & Destructor Documentation
TComponentReregisterContext()
template<class ComponentType> TComponentReregisterContext< ComponentType >::TComponentReregisterContext () inline
Initialization constructor.
Definition at line 165 of file ComponentReregisterContext.h.
References ComponentContexts, FlushRenderingCommands(), ScenesToUpdateAllPrimitiveSceneInfos, and UpdateAllPrimitiveSceneInfos().
~TComponentReregisterContext()
template<class ComponentType> TComponentReregisterContext< ComponentType >::~TComponentReregisterContext () inline
Definition at line 179 of file ComponentReregisterContext.h.
References UpdateAllPrimitiveSceneInfos().
Member Function Documentation
UpdateAllPrimitiveSceneInfos()
template<class ComponentType> void TComponentReregisterContext< ComponentType >::UpdateAllPrimitiveSceneInfos () inline private
Definition at line 190 of file ComponentReregisterContext.h.
References check, MoveTemp(), ScenesToUpdateAllPrimitiveSceneInfos, and UpdateAllPrimitiveSceneInfosForScenes().
Referenced by TComponentReregisterContext(), and ~TComponentReregisterContext().
Field Documentation
ComponentContexts
template<class ComponentType> TIndirectArray<FComponentReregisterContext> TComponentReregisterContext< ComponentType >::ComponentContexts private
The recreate contexts for the individual components.
Definition at line 186 of file ComponentReregisterContext.h.
Referenced by TComponentReregisterContext().
ScenesToUpdateAllPrimitiveSceneInfos
template<class ComponentType> TSet<FSceneInterface*> TComponentReregisterContext< ComponentType >::ScenesToUpdateAllPrimitiveSceneInfos private
Definition at line 188 of file ComponentReregisterContext.h.
Referenced by TComponentReregisterContext(), and UpdateAllPrimitiveSceneInfos().
The documentation for this class was generated from the following file:
ComponentReregisterContext.h