Unreal Engine 5.6 C++ API: StaticMeshComponent.h File Reference
StaticMeshComponent.h File Reference
#include "CoreMinimal.h"
#include "RHIResources.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Misc/Guid.h"
#include "UObject/Class.h"
#include "Engine/EngineTypes.h"
#include "Engine/TextureStreamingTypes.h"
#include "Components/MeshComponent.h"
#include "Components/ActorStaticMeshComponentInterface.h"
#include "PackedNormal.h"
#include "Templates/UniquePtr.h"
#include "Runtime/Launch/Resources/Version.h"
#include "UObject/RenderingObjectVersion.h"
#include "SceneTypes.h"
#include "DrawDebugHelpers.h"
#include "StateStream/StaticMeshStateStreamHandle.h"
#include "StaticMeshComponent.generated.h"
Data Structures
class UStaticMeshComponent
Namespaces
namespace Nanite
Macros
#define STATICMESH_ENABLE_DEBUG_RENDERING ENABLE_DRAW_DEBUG
Whether FStaticMeshSceneProxy should to store data and enable codepaths needed for debug rendering.
Functions
UCLASS ()
StaticMeshComponent is used to create an instance of a UStaticMesh.
USTRUCT () struct FPaintedVertex
Cached vertex information at the time the mesh was painted.
Variables
editinlinenew
hidecategories =(Object,Activation,"Components|Activation")
meta =(BlueprintSpawnableComponent)
ShowCategories =(Mobility)
Macro Definition Documentation
STATICMESH_ENABLE_DEBUG_RENDERING
#define STATICMESH_ENABLE_DEBUG_RENDERING ENABLE_DRAW_DEBUG
Whether FStaticMeshSceneProxy should to store data and enable codepaths needed for debug rendering.
Definition at line 44 of file StaticMeshComponent.h.
Function Documentation
UCLASS()
UCLASS ()
StaticMeshComponent is used to create an instance of a UStaticMesh.
A static mesh is a piece of geometry that consists of a static set of polygons.
See also
https://docs.unrealengine.com/latest/INT/Engine/Content/Types/StaticMeshes/
UStaticMesh
USTRUCT()
USTRUCT ()
Cached vertex information at the time the mesh was painted.
Vertex data stored per-LOD.
copy of painted vertex data
Copy of vertex buffer colors
Index of the LOD that this data came from
Check whether this contains valid data
Definition at line 53 of file StaticMeshComponent.h.
References Ar, Color, ForceInit, FORCEINLINE, FVector, GENERATED_USTRUCT_BODY, FRenderingObjectVersion::GUID, FRenderingObjectVersion::IncreaseNormalPrecision, Normal, operator<<(), Position, and UPROPERTY.
Variable Documentation
editinlinenew
editinlinenew
Definition at line 101 of file StaticMeshComponent.h.
hidecategories
hidecategories =(Object,Activation,"Components|Activation")
Definition at line 101 of file StaticMeshComponent.h.
meta
meta =(BlueprintSpawnableComponent)
Definition at line 101 of file StaticMeshComponent.h.
Referenced by UStaticMeshComponent::UPROPERTY(), UStaticMeshComponent::UPROPERTY(), UStaticMeshComponent::UPROPERTY(), UStaticMeshComponent::UPROPERTY(), UStaticMeshComponent::UPROPERTY(), UStaticMeshComponent::UPROPERTY(), UStaticMeshComponent::UPROPERTY(), and UStaticMeshComponent::UPROPERTY().
ShowCategories
ShowCategories =(Mobility)
Definition at line 101 of file StaticMeshComponent.h.