Unreal Engine 5.6 C++ API: TTypeCompatibleBytes< void > Struct Reference
TTypeCompatibleBytes< void > Struct Reference
#include "TypeCompatibleBytes.h"
Public Types
using ConstGetType = void
using ElementTypeAlias_NatVisHelper = void
using MutableGetType = void
using RvalueGetType = void
Public Member Functions
TTypeCompatibleBytes ()=default
TTypeCompatibleBytes (const TTypeCompatibleBytes &)=delete
TTypeCompatibleBytes (TTypeCompatibleBytes &&)=delete
~TTypeCompatibleBytes ()=default
void DestroyUnchecked ()
void EmplaceUnchecked ()
void * GetTypedPtr ()
void GetUnchecked () const
TTypeCompatibleBytes & operator= (const TTypeCompatibleBytes &)=delete
TTypeCompatibleBytes & operator= (TTypeCompatibleBytes &&)=delete
Data Fields
uint8 Pad [sizeof(void)]
Detailed Description
Definition at line 126 of file TypeCompatibleBytes.h.
Member Typedef Documentation
ConstGetType
using TTypeCompatibleBytes< void >::ConstGetType = void
Definition at line 141 of file TypeCompatibleBytes.h.
ElementTypeAlias_NatVisHelper
using TTypeCompatibleBytes< void >::ElementTypeAlias_NatVisHelper = void
Definition at line 128 of file TypeCompatibleBytes.h.
MutableGetType
using TTypeCompatibleBytes< void >::MutableGetType = void
Definition at line 140 of file TypeCompatibleBytes.h.
RvalueGetType
using TTypeCompatibleBytes< void >::RvalueGetType = void
Definition at line 142 of file TypeCompatibleBytes.h.
Constructor & Destructor Documentation
TTypeCompatibleBytes() [1/3]
TTypeCompatibleBytes< void >::TTypeCompatibleBytes () default
Referenced by TTypeCompatibleBytes(), TTypeCompatibleBytes(), operator=(), and operator=().
~TTypeCompatibleBytes()
TTypeCompatibleBytes< void >::~TTypeCompatibleBytes () default
TTypeCompatibleBytes() [2/3]
TTypeCompatibleBytes< void >::TTypeCompatibleBytes (TTypeCompatibleBytes< void > &&) delete
References TTypeCompatibleBytes().
TTypeCompatibleBytes() [3/3]
TTypeCompatibleBytes< void >::TTypeCompatibleBytes (const TTypeCompatibleBytes< void > &) delete
References TTypeCompatibleBytes().
Member Function Documentation
DestroyUnchecked()
void TTypeCompatibleBytes< void >::DestroyUnchecked () inline
Definition at line 157 of file TypeCompatibleBytes.h.
EmplaceUnchecked()
void TTypeCompatibleBytes< void >::EmplaceUnchecked () inline
Definition at line 151 of file TypeCompatibleBytes.h.
GetTypedPtr()
void * TTypeCompatibleBytes< void >::GetTypedPtr () inline
Definition at line 38 of file TypeCompatibleBytes.h.
GetUnchecked()
void TTypeCompatibleBytes< void >::GetUnchecked () const inline
Definition at line 145 of file TypeCompatibleBytes.h.
operator=() [1/2]
TTypeCompatibleBytes & TTypeCompatibleBytes< void >::operator= (const TTypeCompatibleBytes< void > &) delete
References TTypeCompatibleBytes().
operator=() [2/2]
TTypeCompatibleBytes & TTypeCompatibleBytes< void >::operator= (TTypeCompatibleBytes< void > &&) delete
References TTypeCompatibleBytes().
Field Documentation
Pad
uint8 TTypeCompatibleBytes< void >::Pad[sizeof(void)]
Definition at line 81 of file TypeCompatibleBytes.h.
The documentation for this struct was generated from the following file:
TypeCompatibleBytes.h