Unreal Engine 5.6 C++ API: Async.h File Reference
Async.h File Reference
#include "Async/Future.h"
#include "Async/TaskGraphInterfaces.h"
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "HAL/PlatformAffinity.h"
#include "HAL/PlatformProcess.h"
#include "HAL/Runnable.h"
#include "HAL/RunnableThread.h"
#include "HAL/ThreadSafeCounter.h"
#include "Misc/AssertionMacros.h"
#include "Misc/CoreStats.h"
#include "Misc/Fork.h"
#include "Misc/IQueuedWork.h"
#include "Misc/QueuedThreadPool.h"
#include "Containers/Ticker.h"
#include "Stats/Stats.h"
#include "Templates/Function.h"
#include "Templates/UnrealTemplate.h"
Data Structures
class FAsyncGraphTaskBase
Base class for asynchronous functions that are executed in the Task Graph system.
struct FAsyncThreadIndex
Helper struct used to generate unique ids for the stats.
class TAsyncGraphTask< ResultType >
Template for asynchronous functions that are executed in the Task Graph system.
class TAsyncQueuedWork< ResultType >
Template for asynchronous functions that are executed in the queued thread pool.
class TAsyncRunnable< ResultType >
Template for asynchronous functions that are executed in a separate thread.
Enumerations
enum class EAsyncExecution {
TaskGraph , TaskGraphMainThread , TaskGraphMainTick , Thread ,
ThreadIfForkSafe , ThreadPool , LargeThreadPool
}
Enumerates available asynchronous execution methods.
Functions
template<typename CallableType>
auto Async (EAsyncExecution Execution, CallableType &&Callable, TUniqueFunction< void()> CompletionCallback=nullptr) -> TFuture< decltype(Forward< CallableType >(Callable)())>
Execute a given function asynchronously.
template<typename CallableType>
auto AsyncPool (FQueuedThreadPool &ThreadPool, CallableType &&Callable, TUniqueFunction< void()> CompletionCallback=nullptr, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal) -> TFuture< decltype(Forward< CallableType >(Callable)())>
Execute a given function asynchronously on the specified thread pool.
void AsyncTask (ENamedThreads::Type Thread, TUniqueFunction< void()> Function)
Convenience function for executing code asynchronously on the Task Graph.
template<typename CallableType>
auto AsyncThread (CallableType &&Callable, uint32 StackSize=0, EThreadPriority ThreadPri=TPri_Normal, TUniqueFunction< void()> CompletionCallback=nullptr) -> TFuture< decltype(Forward< CallableType >(Callable)())>
Execute a given function asynchronously using a separate thread.
template<typename ResultType, typename CallableType>
void SetPromise (TPromise< ResultType > &Promise, CallableType &&Callable)
Template for setting a promise value from a callable.
template<typename CallableType>
void SetPromise (TPromise< void > &Promise, CallableType &&Callable)
Enumeration Type Documentation
EAsyncExecution
enum class EAsyncExecution strong
Enumerates available asynchronous execution methods.
Enumerator
TaskGraph
Execute in Task Graph (for short running tasks).
TaskGraphMainThread
Execute in Task Graph on the main thread (for short running tasks that are safe to run anywhere including inside other waits).
Note: this could end up running inside the GC or inside PostLoads, code with delegates that can't be known to be safe in advance should opt for TaskGraphMainTick instead.
TaskGraphMainTick
Execute inside a Tick on the main thread (for short running tasks that needs to run at a safe place).
Thread
Execute in separate thread if supported (for long running tasks).
ThreadIfForkSafe
Execute in separate thread if supported or supported post fork (see FForkProcessHelper::CreateThreadIfForkSafe) (for long running tasks).
ThreadPool
Execute in global queued thread pool.
LargeThreadPool
Execute in large global queued thread pool.
Definition at line 27 of file Async.h.
Function Documentation
Async()
template<typename CallableType> auto Async (EAsyncExecution Execution, CallableType && Callable, TUniqueFunction< void()> CompletionCallback = nullptr) -> TFuture<decltype(Forward<CallableType>(Callable)())>
Execute a given function asynchronously.
Usage examples:
// using global function int TestFunc() { return 123; }
TUniqueFunction<int()> Task = TestFunc(); auto Result = Async(EAsyncExecution::Thread, Task);
// using lambda TUniqueFunction<int()> Task = []() { return 123; }
auto Result = Async(EAsyncExecution::Thread, Task);
// using inline lambda auto Result = Async(EAsyncExecution::Thread, []() { return 123; }
Parameters
CallableType The type of callable object.
Execution The execution method to use, i.e. on Task Graph or in a separate thread.
Function The function to execute.
CompletionCallback An optional callback function that is executed when the function completed execution.
Returns
A TFuture object that will receive the return value from the function.
Definition at line 299 of file Async.h.
References FTSTicker::AddTicker(), ENamedThreads::AnyThread, check, FRunnableThread::Create(), FForkProcessHelper::CreateForkableThread(), Forward(), Function, ENamedThreads::GameThread, FTSTicker::GetCoreTicker(), TPromise< ResultType >::GetFuture(), FAsyncThreadIndex::GetNext(), FRunnableThread::GetThreadType(), GLargeThreadPool, GThreadPool, FForkProcessHelper::IsForkedMultithreadInstance(), LargeThreadPool, MoveTemp(), FRunnableThread::Real, SetPromise(), TPromise< ResultType >::SetValue(), FGenericPlatformProcess::SupportsMultithreading(), TaskGraph, TaskGraphMainThread, TaskGraphMainTick, TEXT, Thread, ThreadIfForkSafe, and ThreadPool.
Referenced by UHierarchicalInstancedStaticMeshComponent::BuildTreeIfOutdated().
AsyncPool()
template<typename CallableType> auto AsyncPool (FQueuedThreadPool & ThreadPool, CallableType && Callable, TUniqueFunction< void()> CompletionCallback = nullptr, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal) -> TFuture<decltype(Forward<CallableType>(Callable)())>
Execute a given function asynchronously on the specified thread pool.
Parameters
CallableType The type of callable object.
ThreadPool The thread pool to execute on.
Function The function to execute.
CompletionCallback An optional callback function that is executed when the function completed execution.
Returns
A TFuture object that will receive the return value from the function.
Definition at line 407 of file Async.h.
References Forward(), Function, TPromise< ResultType >::GetFuture(), MoveTemp(), Normal, and ThreadPool.
AsyncTask()
void AsyncTask (ENamedThreads::Type Thread, TUniqueFunction< void()> Function)
Convenience function for executing code asynchronously on the Task Graph.
Parameters
Thread The name of the thread to run on.
Function The function to execute.
References Function, and Thread.
Referenced by UE::PixelStreaming2::DoOnGameThread(), UE::PixelStreaming2::DoOnGameThreadAndWait(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampledAsync(), FPersistentStorageManager::Initialize(), AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType >::Reschedule(), USTRUCT(), and AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType >::WaitCompletionWithTimeout().
AsyncThread()
template<typename CallableType> auto AsyncThread (CallableType && Callable, uint32 StackSize = 0, EThreadPriority ThreadPri = TPri_Normal, TUniqueFunction< void()> CompletionCallback = nullptr) -> TFuture<decltype(Forward<CallableType>(Callable)())>
Execute a given function asynchronously using a separate thread.
Parameters
CallableType The type of callable object.
Function The function to execute.
StackSize stack space to allocate for the new thread
ThreadPri thread priority
CompletionCallback An optional callback function that is executed when the function completed execution.
Returns
A TFuture object that will receive the return value from the function.
Definition at line 430 of file Async.h.
References check, FRunnableThread::Create(), Forward(), Function, TPromise< ResultType >::GetFuture(), FAsyncThreadIndex::GetNext(), MoveTemp(), SetPromise(), TPromise< ResultType >::SetValue(), FGenericPlatformProcess::SupportsMultithreading(), TEXT, and TPri_Normal.
SetPromise() [1/2]
template<typename ResultType, typename CallableType> void SetPromise (TPromise< ResultType > & Promise, CallableType && Callable) inline
Template for setting a promise value from a callable.
Definition at line 61 of file Async.h.
References Forward(), and TPromise< ResultType >::SetValue().
Referenced by Async(), AsyncThread(), TAsyncGraphTask< ResultType >::DoTask(), TAsyncQueuedWork< ResultType >::DoThreadedWork(), and TAsyncRunnable< ResultType >::Run().
SetPromise() [2/2]
template<typename CallableType> void SetPromise (TPromise< void > & Promise, CallableType && Callable) inline
Definition at line 67 of file Async.h.
References Forward(), and TPromise< ResultType >::SetValue().