Unreal Engine 5.6 C++ API: FPrimitiveComponentHelper Class Reference
FPrimitiveComponentHelper Class Reference
Helper class used to share implementation for different PrimitiveComponent types.
#include "PrimitiveComponentHelper.h"
Static Public Member Functions
template<class T>
static void AddNavigationModifier (const T &Component, FNavigationRelevantData &OutData)
template<class T>
static void GetNavigationData (const T &Component, FNavigationRelevantData &OutData)
template<class T>
static FPrimitiveMaterialPropertyDescriptor GetUsedMaterialPropertyDesc (const T &Component, ERHIFeatureLevel::Type FeatureLevel)
Detailed Description
Helper class used to share implementation for different PrimitiveComponent types.
Definition at line 19 of file PrimitiveComponentHelper.h.
Member Function Documentation
AddNavigationModifier()
template<class T> void FPrimitiveComponentHelper::AddNavigationModifier (const T & Component, FNavigationRelevantData & OutData) static
Definition at line 84 of file PrimitiveComponentHelper.h.
References FCompositeNavModifier::Add(), Component, FNavigationRelevantData::Modifiers, FCompositeNavModifier::SetFillCollisionUnderneathForNavmesh(), and FCompositeNavModifier::SetRasterizeAsFilledConvexVolume().
Referenced by FInstancedStaticMeshComponentHelper::GetNavigationData(), and GetNavigationData().
GetNavigationData()
template<class T> void FPrimitiveComponentHelper::GetNavigationData (const T & Component, FNavigationRelevantData & OutData) static
Definition at line 78 of file PrimitiveComponentHelper.h.
References AddNavigationModifier(), and Component.
GetUsedMaterialPropertyDesc()
template<class T> FPrimitiveMaterialPropertyDescriptor FPrimitiveComponentHelper::GetUsedMaterialPropertyDesc (const T & Component, ERHIFeatureLevel::Type FeatureLevel) static
Definition at line 33 of file PrimitiveComponentHelper.h.
References FMaterialRelevance::bUsesDisplacement, FMaterialRelevance::bUsesWorldPositionOffset, Component, IsOpaqueOrMaskedBlendMode(), FMath::Max, FMath::Min, and UseNaniteTessellation().
Referenced by FInstancedSkinnedMeshComponentHelper::GetComponentDesc().
The documentation for this class was generated from the following file:
PrimitiveComponentHelper.h