Unreal Engine 5.6 C++ API: FWatchablePropertySet Class Reference
FWatchablePropertySet Class Reference
#include "InteractiveTool.h"
Data Structures
class FPropertyWatcher
class TPropertyWatcher
Public Member Functions
FWatchablePropertySet ()=default
FWatchablePropertySet (const FWatchablePropertySet &)=delete
void CheckAndUpdateWatched ()
FWatchablePropertySet & operator= (const FWatchablePropertySet &)=delete
void SilentUpdateWatched ()
void SilentUpdateWatcherAtIndex (int32 i)
Silently updates just a single watcher, using an index gotten from WatchProperty.
template<typename PropType>
int32 WatchProperty (const PropType &ValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn)
template<typename PropType>
int32 WatchProperty (const PropType &ValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn, typename TPropertyWatcher< PropType >::FNotEqualTestFunction NotEqualsIn)
template<typename PropType>
int32 WatchProperty (typename TPropertyWatcher< PropType >::FValueGetter GetValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn)
template<typename PropType>
int32 WatchProperty (typename TPropertyWatcher< PropType >::FValueGetter GetValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn, typename TPropertyWatcher< PropType >::FNotEqualTestFunction NotEqualsIn)
Private Attributes
TArray< TUniquePtr< FPropertyWatcher > > PropertyWatchers
Detailed Description
Definition at line 63 of file InteractiveTool.h.
Constructor & Destructor Documentation
FWatchablePropertySet() [1/2]
FWatchablePropertySet::FWatchablePropertySet () default
Referenced by FWatchablePropertySet(), and operator=().
FWatchablePropertySet() [2/2]
FWatchablePropertySet::FWatchablePropertySet (const FWatchablePropertySet &) delete
References FWatchablePropertySet().
Member Function Documentation
CheckAndUpdateWatched()
void FWatchablePropertySet::CheckAndUpdateWatched () inline
Definition at line 166 of file InteractiveTool.h.
References PropertyWatchers.
operator=()
FWatchablePropertySet & FWatchablePropertySet::operator= (const FWatchablePropertySet &) delete
References FWatchablePropertySet().
SilentUpdateWatched()
void FWatchablePropertySet::SilentUpdateWatched () inline
Definition at line 173 of file InteractiveTool.h.
References PropertyWatchers.
SilentUpdateWatcherAtIndex()
void FWatchablePropertySet::SilentUpdateWatcherAtIndex (int32 i) inline
Silently updates just a single watcher, using an index gotten from WatchProperty.
Useful when you want watching to still work for other properties changed in the same tick.
Definition at line 185 of file InteractiveTool.h.
References check, and PropertyWatchers.
WatchProperty() [1/4]
template<typename PropType> int32 FWatchablePropertySet::WatchProperty (const PropType & ValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn) inline
Returns
Index of the watcher, which can be used in SilentUpdateWatcherAtIndex
Definition at line 193 of file InteractiveTool.h.
References MakeUnique(), and PropertyWatchers.
WatchProperty() [2/4]
template<typename PropType> int32 FWatchablePropertySet::WatchProperty (const PropType & ValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn, typename TPropertyWatcher< PropType >::FNotEqualTestFunction NotEqualsIn) inline
Returns
Index of the watcher, which can be used in SilentUpdateWatcherAtIndex
Definition at line 208 of file InteractiveTool.h.
References MakeUnique(), and PropertyWatchers.
WatchProperty() [3/4]
template<typename PropType> int32 FWatchablePropertySet::WatchProperty (typename TPropertyWatcher< PropType >::FValueGetter GetValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn) inline
Returns
Index of the watcher, which can be used in SilentUpdateWatcherAtIndex
Definition at line 200 of file InteractiveTool.h.
References MakeUnique(), and PropertyWatchers.
WatchProperty() [4/4]
template<typename PropType> int32 FWatchablePropertySet::WatchProperty (typename TPropertyWatcher< PropType >::FValueGetter GetValueIn, typename TPropertyWatcher< PropType >::FChangedCallback OnChangedIn, typename TPropertyWatcher< PropType >::FNotEqualTestFunction NotEqualsIn) inline
Returns
Index of the watcher, which can be used in SilentUpdateWatcherAtIndex
Definition at line 216 of file InteractiveTool.h.
References MakeUnique(), and PropertyWatchers.
Field Documentation
PropertyWatchers
TArray<TUniquePtr<FPropertyWatcher> > FWatchablePropertySet::PropertyWatchers private
Definition at line 224 of file InteractiveTool.h.
Referenced by CheckAndUpdateWatched(), SilentUpdateWatched(), SilentUpdateWatcherAtIndex(), WatchProperty(), WatchProperty(), WatchProperty(), and WatchProperty().
The documentation for this class was generated from the following file:
InteractiveTool.h