Unreal Engine 5.6 C++ API: UDynamicMeshComponent Class Reference
UDynamicMeshComponent Class Reference
#include "DynamicMeshComponent.h"
Public Member Functions
virtual GEOMETRYFRAMEWORK_API void ApplyChange (const FMeshChange *Change, bool bRevert) override
Apply a general mesh change to the mesh.
virtual GEOMETRYFRAMEWORK_API void ApplyChange (const FMeshReplacementChange *Change, bool bRevert) override
Apply a mesh replacement change to mesh.
virtual GEOMETRYFRAMEWORK_API void ApplyChange (const FMeshVertexChange *Change, bool bRevert) override
Apply a vertex deformation change to the mesh.
virtual GEOMETRYFRAMEWORK_API void ClearSimpleCollisionShapes (bool bUpdateCollision)
Clear the simple collision shapes associated with this mesh component.
virtual GEOMETRYFRAMEWORK_API void ClearTriangleColorFunction (EDynamicMeshComponentRenderUpdateMode UpdateMode=EDynamicMeshComponentRenderUpdateMode::FastUpdate)
Clear an active triangle color function if one exists, and update the mesh.
virtual GEOMETRYFRAMEWORK_API void ClearVertexColorRemappingFunction (EDynamicMeshComponentRenderUpdateMode UpdateMode=EDynamicMeshComponentRenderUpdateMode::FastUpdate)
Clear an active VertexColor Remapping function if one exists, and update the mesh.
virtual GEOMETRYFRAMEWORK_API bool ContainsPhysicsTriMeshData (bool InUseAllTriData) const override
Interface for checking if the implementing objects contains triangle mesh collision data.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FMeshRegionModified, UDynamicMeshComponent *, const FMeshRegionChangeBase *, bool)
This delegate fires when the mesh has been changed via an FMeshRegionChange-derived change – FMeshChange, FMeshVertexChange, or FMeshReplacementChange Note that in the case of an FMeshVertexChange, the OnMeshVerticesChanged delegate will also fire.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FMeshVerticesModified, UDynamicMeshComponent *, const FMeshVertexChange *, bool)
This delegate fires when the mesh vertices have been changed via an FMeshVertexChange.
DECLARE_MULTICAST_DELEGATE_TwoParams (FComponentChildrenChangedDelegate, USceneComponent *, bool)
virtual GEOMETRYFRAMEWORK_API void DisableSecondaryTriangleBuffers ()
Disable secondary triangle buffers.
virtual GEOMETRYFRAMEWORK_API void EnableSecondaryTriangleBuffers (TUniqueFunction< bool(const FDynamicMesh3 *, int32)> SecondaryTriFilterFunc)
If Secondary triangle buffers are enabled, then we will filter triangles that pass the given predicate function into a second index buffer.
GEOMETRYFRAMEWORK_API void FastNotifyColorsUpdated ()
Call this instead of NotifyMeshUpdated() if you have only updated the vertex colors (or triangle color function).
GEOMETRYFRAMEWORK_API void FastNotifyPositionsUpdated (bool bNormals=false, bool bColors=false, bool bUVs=false)
Call this instead of NotifyMeshUpdated() if you have only updated the vertex positions (and possibly some attributes).
GEOMETRYFRAMEWORK_API void FastNotifySecondaryTrianglesChanged ()
Call this instead of NotifyMeshUpdated() if you have only updated secondary triangle sorting.
GEOMETRYFRAMEWORK_API void FastNotifyTriangleVerticesUpdated (const TArray< int32 > &Triangles, EMeshRenderAttributeFlags UpdatedAttributes)
This function updates vertex positions/attributes of existing SceneProxy render buffers if possible, for the given triangles.
GEOMETRYFRAMEWORK_API void FastNotifyTriangleVerticesUpdated (const TSet< int32 > &Triangles, EMeshRenderAttributeFlags UpdatedAttributes)
This function updates vertex positions/attributes of existing SceneProxy render buffers if possible, for the given triangles.
GEOMETRYFRAMEWORK_API void FastNotifyTriangleVerticesUpdated_ApplyPrecompute (const TArray< int32 > &Triangles, EMeshRenderAttributeFlags UpdatedAttributes, TFuture< bool > &Precompute, const TArray< int32 > &UpdateSets, const UE::Geometry::FAxisAlignedBox3d &UpdateSetBounds)
This function updates vertex positions/attributes of existing SceneProxy render buffers if possible, for the given triangles.
GEOMETRYFRAMEWORK_API TFuture< bool > FastNotifyTriangleVerticesUpdated_TryPrecompute (const TArray< int32 > &Triangles, TArray< int32 > &UpdateSetsOut, UE::Geometry::FAxisAlignedBox3d &BoundsOut)
If a Decomposition is set on this Component, and everything is currently valid (proxy/etc), precompute the set of buffers that will be modified, as well as the bounds of the modified region.
GEOMETRYFRAMEWORK_API void FastNotifyUVsUpdated ()
Call this instead of NotifyMeshUpdated() if you have only updated the vertex uvs.
GEOMETRYFRAMEWORK_API void FastNotifyVertexAttributesUpdated (bool bNormals, bool bColors, bool bUVs)
Call this instead of NotifyMeshUpdated() if you have only updated the vertex attributes (but not positions).
GEOMETRYFRAMEWORK_API void FastNotifyVertexAttributesUpdated (EMeshRenderAttributeFlags UpdatedAttributes)
Call this instead of NotifyMeshUpdated() if you have only updated the vertex positions/attributes This function will update the existing RenderProxy buffers if possible, rather than create new ones.
GEOMETRYFRAMEWORK_API const UE::Geometry::FMeshTangentsf * GetAutoCalculatedTangents ()
virtual const UBodySetup * GetBodySetup () const
virtual GEOMETRYFRAMEWORK_API UBodySetup * GetBodySetup () override
bool GetInvalidateProxyOnChangeEnabled () const
virtual GEOMETRYFRAMEWORK_API bool GetPhysicsTriMeshData (struct FTriMeshCollisionData *CollisionData, bool InUseAllTriData) override
virtual GEOMETRYFRAMEWORK_API FDynamicMesh3 * GetRenderMesh ()
The SceneProxy should call these functions to get the post-processed RenderMesh.
virtual GEOMETRYFRAMEWORK_API const FDynamicMesh3 * GetRenderMesh () const
The SceneProxy should call these functions to get the post-processed RenderMesh.
const FKAggregateGeom & GetSimpleCollisionShapes () const
virtual GEOMETRYFRAMEWORK_API bool GetTriMeshSizeEstimates (struct FTriMeshCollisionDataEstimates &OutTriMeshEstimates, bool bInUseAllTriData) const override
Returns an estimate of how much data would be retrieved by GetPhysicsTriMeshData.
virtual GEOMETRYFRAMEWORK_API bool HasTriangleColorFunction ()
virtual GEOMETRYFRAMEWORK_API bool HasVertexColorRemappingFunction ()
virtual GEOMETRYFRAMEWORK_API void InvalidateAutoCalculatedTangents ()
This function marks the auto tangents as dirty, they will be recomputed before they are used again.
virtual GEOMETRYFRAMEWORK_API void NotifyMeshUpdated () override
Call this if you update the mesh via GetMesh().
virtual GEOMETRYFRAMEWORK_API void SetExternalDecomposition (TUniquePtr< FMeshRenderDecomposition > Decomposition)
Configure a decomposition of the mesh, which will result in separate render buffers for each decomposition triangle group.
GEOMETRYFRAMEWORK_API void SetInvalidateProxyOnChangeEnabled (bool bEnabled)
When a FMeshChange or FMeshVertexChange is applied, by default we currently fully invalidate the render proxy.
virtual GEOMETRYFRAMEWORK_API void SetRenderMeshPostProcessor (TUniquePtr< IRenderMeshPostProcessor > Processor)
Add a render mesh processor, to be called before the mesh is sent for rendering.
GEOMETRYFRAMEWORK_API void SetSceneProxyVerifyUsedMaterials (bool bState)
Set whether or not to validate mesh batch materials against the component materials.
virtual GEOMETRYFRAMEWORK_API void SetSimpleCollisionShapes (const struct FKAggregateGeom &AggGeom, bool bUpdateCollision)
Update the simple collision shapes associated with this mesh component.
GEOMETRYFRAMEWORK_API void SetTransientDeferCollisionUpdates (bool bEnabled)
The bDeferCollisionUpdates property is a serialized Component setting that controls when collision is regenerated.
virtual GEOMETRYFRAMEWORK_API void SetTriangleColorFunction (TUniqueFunction< FColor(const FDynamicMesh3 *, int)> TriangleColorFuncIn, EDynamicMeshComponentRenderUpdateMode UpdateMode=EDynamicMeshComponentRenderUpdateMode::FastUpdate)
Set an active triangle color function if one exists, and update the mesh.
virtual GEOMETRYFRAMEWORK_API void SetVertexColorRemappingFunction (TUniqueFunction< void(FVector4f &)> ColorMapFuncIn, EDynamicMeshComponentRenderUpdateMode UpdateMode=EDynamicMeshComponentRenderUpdateMode::FastUpdate)
Set an active VertexColor Remapping function if one exists, and update the mesh.
UFUNCTION () EDynamicMeshComponentTangentsMode GetTangentsType() const
UFUNCTION () GEOMETRYFRAMEWORK_API bool ValidateMaterialSlots(bool bCreateIfMissing
Compute the maximum MaterialID on the DynamicMesh, and ensure that Material Slots match.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void NotifyMeshModified()
Notify the Component that it's DynamicMesh has been modified externally.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void NotifyMeshVertexAttributesModified(bool bPositions
Notify the Component that vertex attribute values of it's DynamicMesh have been modified externally.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void UpdateCollision(bool bOnlyIfPending
Force an update of the Collision/Physics data for this Component.
UFUNCTION () GEOMETRYFRAMEWORK_API void ConfigureMaterialSet(const TArray< UMaterialInterface * > &NewMaterialSet
Set new list of Materials for the Mesh.
UFUNCTION () GEOMETRYFRAMEWORK_API void EnableComplexAsSimpleCollision()
calls SetComplexAsSimpleCollisionEnabled(true, true)
UFUNCTION () GEOMETRYFRAMEWORK_API void SetComplexAsSimpleCollisionEnabled(bool bEnabled
If bEnabled=true, sets bEnableComplexCollision=true and CollisionType=CTF_UseComplexAsSimple If bEnabled=true, sets bEnableComplexCollision=false and CollisionType=CTF_UseDefault.
UFUNCTION () GEOMETRYFRAMEWORK_API void SetDeferredCollisionUpdatesEnabled(bool bEnabled
Set value of bDeferCollisionUpdates, when enabled, collision is not automatically recomputed each time the mesh changes.
UFUNCTION () GEOMETRYFRAMEWORK_API void SetTangentsType(EDynamicMeshComponentTangentsMode NewTangentsType)
UPROPERTY ()
If true, current mesh will be used as Complex Collision source mesh.
UPROPERTY ()
If true, updates to the mesh will not result in immediate collision regeneration.
UPROPERTY ()
If true, UV hit results will not be enabled for this mesh's complex collision even if they are enabled for the project settings generally.
UPROPERTY () bool bUseAsyncCooking
Controls whether the physics cooking should be done off the game thread.
UPROPERTY () TEnumAsByte< enum ECollisionTraceFlag > CollisionType
Type of Collision Geometry to use for this Mesh.
virtual GEOMETRYFRAMEWORK_API bool WantsNegXTriMesh () override
Do we want to create a negative version of this mesh.
Public Member Functions inherited from UBaseDynamicMeshComponent
virtual GEOMETRYFRAMEWORK_API UMaterialInterface * GetMaterial (int32 ElementIndex) const override
virtual GEOMETRYFRAMEWORK_API UMaterialInterface * GetMaterialByName (FName MaterialSlotName) const override
virtual GEOMETRYFRAMEWORK_API FMaterialRelevance GetMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const override
Accesses the scene relevance information for the materials applied to the mesh.
virtual GEOMETRYFRAMEWORK_API TArray< FName > GetMaterialSlotNames () const override
virtual GEOMETRYFRAMEWORK_API int32 GetNumMaterials () const override
virtual GEOMETRYFRAMEWORK_API void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
virtual bool HasOverrideSecondaryWireframeRenderMaterial () const
virtual bool HasOverrideWireframeRenderMaterial () const
virtual bool HasSecondaryRenderMaterial () const
virtual GEOMETRYFRAMEWORK_API bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
GEOMETRYFRAMEWORK_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual GEOMETRYFRAMEWORK_API void SetMaterial (int32 ElementIndex, UMaterialInterface *Material) override
virtual GEOMETRYFRAMEWORK_API void SetNumMaterials (int32 NumMaterials)
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") UFUNCTION()) virtual EDynamicMeshComponentDistanceFieldMode GetDistanceFieldMode() const
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") UFUNCTION()) virtual void SetDistanceFieldMode(EDynamicMeshComponentDistanceFieldMode NewDistFieldMode)
Configure Distance Field computation mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual bool GetEnableRaytracing() const
UFUNCTION () GEOMETRYFRAMEWORK_API virtual bool GetSecondaryBuffersVisibility() const
UFUNCTION () GEOMETRYFRAMEWORK_API virtual EDynamicMeshDrawPath GetMeshDrawPath() const
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearOverrideRenderMaterial()
Clear any active override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearOverrideSecondaryWireframeRenderMaterial()
Clear any active secondary wireframe override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearOverrideWireframeRenderMaterial()
Clear any active wireframe override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearSecondaryRenderMaterial()
Clear any active secondary render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetColorOverrideMode(EDynamicMeshComponentColorOverrideMode NewMode)
Configure the active Color Override.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetConstantOverrideColor(FColor NewColor)
Configure the Color used with Constant Color Override Mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetEnableFlatShading(bool bEnable)
Configure the Color used with Constant Color Override Mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetEnableRaytracing(bool bSetEnabled)
Enable/Disable raytracing support.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetMeshDrawPath(EDynamicMeshDrawPath NewDrawPath)
Set the mesh rendering to use the static or dynamic draw path.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetOverrideRenderMaterial(UMaterialInterface *Material)
Set an active override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetOverrideSecondaryWireframeRenderMaterial(UMaterialInterface *Material)
Set an active secondary wireframe override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetOverrideWireframeRenderMaterial(UMaterialInterface *Material)
Set an active wireframe override render Material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetSecondaryBuffersVisibility(bool bSetVisible)
Show/Hide the secondary triangle buffers.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetSecondaryRenderMaterial(UMaterialInterface *Material)
Set an active secondary render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetShadowsEnabled(bool bEnabled)
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetVertexColorSpaceTransformMode(EDynamicMeshVertexColorTransformMode NewMode)
Configure the active Color Space Transform Mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetViewModeOverridesEnabled(bool bEnabled)
UFUNCTION () virtual bool GetEnableWireframeRenderPass() const
UFUNCTION () virtual bool GetFlatShadingEnabled() const
UFUNCTION () virtual bool GetShadowsEnabled() const
UFUNCTION () virtual bool GetViewModeOverridesEnabled() const
UFUNCTION () virtual bool HasOverrideRenderMaterial(int k) const
UFUNCTION () virtual EDynamicMeshComponentColorOverrideMode GetColorOverrideMode() const
UFUNCTION () virtual EDynamicMeshVertexColorTransformMode GetVertexColorSpaceTransformMode() const
UFUNCTION () virtual FColor GetConstantOverrideColor() const
UFUNCTION () virtual UMaterialInterface *GetOverrideRenderMaterial(int MaterialIndex) const
UFUNCTION () virtual UMaterialInterface *GetOverrideSecondaryWireframeRenderMaterial() const
UFUNCTION () virtual UMaterialInterface *GetOverrideWireframeRenderMaterial() const
UFUNCTION () virtual UMaterialInterface *GetSecondaryRenderMaterial() const
UFUNCTION () virtual void SetEnableWireframeRenderPass(bool bEnable)
Configure whether wireframe rendering is enabled or not.
UPROPERTY () bool bEnableRaytracing
Enable/disable Raytracing support on this Mesh, if Raytracing is currently enabled in the Project Settings.
UPROPERTY () TArray< TObjectPtr< UMaterialInterface > > BaseMaterials
UPROPERTY ()) bool bEnableFlatShading
Enable use of per-triangle facet normals in place of mesh normals.
UPROPERTY ()) bool bEnableViewModeOverrides
This flag controls whether Editor View Mode Overrides are enabled for this mesh.
UPROPERTY ()) bool bExplicitShowWireframe
If true, render the Wireframe on top of the Shaded Mesh.
UPROPERTY ()) EDynamicMeshComponentColorOverrideMode ColorMode
UPROPERTY ()) EDynamicMeshVertexColorTransformMode ColorSpaceMode
Color Space Transform that will be applied to the colors stored in the DynamicMesh Attribute Color Overlay when constructing render buffers.
UPROPERTY ()) FColor ConstantColor
Constant Color used when Override Color Mode is set to Constant.
UPROPERTY ()) FLinearColor WireframeColor
Constant Color used when Override Color Mode is set to Constant.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Data Fields
bool bool bool bColors = true)
bool bDeferCollisionUpdates = false
bool bDeleteExtraSlots = true)
bool bDisableMeshUVHitResults = false
bool bEnableComplexCollision = false
bool bImmediateUpdate = true)
bool bNormals = true
bool bool bUVs = true
FComponentChildrenChangedDelegate OnChildAttachmentModified
The OnChildAttached() and OnChildDetached() implementations (from USceneComponent API) broadcast this delegate.
FSimpleMulticastDelegate OnMeshChanged
This delegate fires when the mesh has been changed.
FMeshRegionModified OnMeshRegionChanged
FMeshVerticesModified OnMeshVerticesChanged
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Member Functions
virtual GEOMETRYFRAMEWORK_API void BeginDestroy () override
virtual GEOMETRYFRAMEWORK_API FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual GEOMETRYFRAMEWORK_API UBodySetup * CreateBodySetupHelper ()
virtual GEOMETRYFRAMEWORK_API FPrimitiveSceneProxy * CreateSceneProxy () override
virtual GEOMETRYFRAMEWORK_API void FinishPhysicsAsyncCook (bool bSuccess, UBodySetup *FinishedBodySetup)
Once async physics cook is done, create needed state.
virtual FBaseDynamicMeshSceneProxy * GetBaseSceneProxy () override
Subclass must implement this to return scene proxy if available, or nullptr.
GEOMETRYFRAMEWORK_API FDynamicMeshSceneProxy * GetCurrentSceneProxy ()
GEOMETRYFRAMEWORK_API FColor GetGroupColor (const FDynamicMesh3 *Mesh, int TriangleID) const
This function is passed via lambda to the RenderProxy when BaseDynamicMeshComponent::ColorMode == Polygroups.
GEOMETRYFRAMEWORK_API FColor GetTriangleColor (const FDynamicMesh3 *Mesh, int TriangleID)
This function is passed via lambda to the RenderProxy to be able to access TriangleColorFunc.
virtual GEOMETRYFRAMEWORK_API void InvalidatePhysicsData ()
virtual GEOMETRYFRAMEWORK_API void NotifyMaterialSetUpdated ()
This is called to tell our RenderProxy about modifications to the material set.
virtual GEOMETRYFRAMEWORK_API void OnChildAttached (USceneComponent *ChildComponent) override
virtual GEOMETRYFRAMEWORK_API void OnChildDetached (USceneComponent *ChildComponent) override
GEOMETRYFRAMEWORK_API void OnMeshObjectChanged (UDynamicMesh *ChangedMeshObject, FDynamicMeshChangeInfo ChangeInfo)
Called whenever internal MeshObject is modified, fires OnMeshChanged and OnMeshVerticesChanged above.
GEOMETRYFRAMEWORK_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual GEOMETRYFRAMEWORK_API void PostEditImport () override
virtual GEOMETRYFRAMEWORK_API void PostLoad () override
virtual GEOMETRYFRAMEWORK_API void RebuildPhysicsData ()
GEOMETRYFRAMEWORK_API void RemapVertexColor (FVector4f &VertexColorInOut)
This function is passed via lambda to the RenderProxy to be able to access VertexColorMappingFunc.
GEOMETRYFRAMEWORK_API void ResetProxy ()
Fully invalidate all rendering data for this Component.
virtual GEOMETRYFRAMEWORK_API void Serialize (FArchive &Ar) override
virtual GEOMETRYFRAMEWORK_API void SetBodySetup (UBodySetup *NewSetup)
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") FCriticalSection DistanceFieldLock
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") TAsyncComponentDataComputeQueue< FDistanceFieldVolumeData > DistanceFieldComputeQueue
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") TSharedPtr< FDistanceFieldVolumeData > CurrentDistanceField
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") virtual void OnNewDistanceFieldData_Async(TUniquePtr< FDistanceFieldVolumeData > NewData)
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") virtual void UpdateDistanceField()
GEOMETRYFRAMEWORK_API void UpdateAutoCalculatedTangents ()
GEOMETRYFRAMEWORK_API void UpdateLocalBounds ()
Recompute LocalBounds from the current Mesh.
UPROPERTY () EDynamicMeshComponentTangentsMode TangentsType
Tangent source defines whether we use the provided tangents on the Dynamic Mesh, autogenerate tangents, or do not use tangents.
UPROPERTY () TArray< TObjectPtr< UBodySetup > > AsyncBodySetupQueue
Queue for async body setups that are being cooked.
UPROPERTY () TObjectPtr< UBodySetup > MeshBodySetup
UPROPERTY () TObjectPtr< UDynamicMesh > MeshObject
Internal FDynamicMesh is stored inside a UDynamicMesh container, which allows it to be used from BP, shared with other UObjects, and so on.
UPROPERTY ()) struct FKAggregateGeom AggGeom
Simplified collision representation for the mesh component.
Protected Member Functions inherited from UBaseDynamicMeshComponent
virtual bool AllowFastUpdate ()
virtual GEOMETRYFRAMEWORK_API void OnRenderingStateChanged (bool bForceImmedateRebuild)
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") GEOMETRYFRAMEWORK_API virtual void OnNewDistanceFieldMode()
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") UPROPERTY()) EDynamicMeshComponentDistanceFieldMode DistanceFieldMode_DEPRECATED
Controls how distance field is computed.
UPROPERTY ()
UPROPERTY ()
UPROPERTY () EDynamicMeshDrawPath DrawPath
Controls whether to use the dynamic or static draw path.
UPROPERTY () TObjectPtr< UMaterialInterface > OverrideRenderMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > SecondaryRenderMaterial
Protected Member Functions inherited from UMeshComponent
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes
UE::Geometry::FMeshTangentsf AutoCalculatedTangents
Set of per-triangle-vertex tangents computed for the current mesh.
bool bAutoCalculatedTangentsValid = false
true if AutoCalculatedTangents has been computed for current mesh
bool bCollisionUpdatePending = false
bool bInvalidateProxyOnChange = true
If false, we don't completely invalidate the RenderProxy when ApplyChange() is called (assumption is it will be handled elsewhere)
bool bIsEditable = true
If set to false, this blocks external code from being able to modify the internal mesh.
bool bProxyValid = false
If the render proxy is invalidated (eg by MarkRenderStateDirty()), it will be destroyed at the end of the frame, but the base SceneProxy pointer is not nulled out immediately.
bool bProxyVerifyUsedMaterials = true
If true, the render proxy will verify that the mesh batch materials match the contents from the component GetUsedMaterials().
bool bTransientDeferCollisionUpdates = false
TUniquePtr< FMeshRenderDecomposition > Decomposition
UE::Geometry::FAxisAlignedBox3d LocalBounds
Current local-space bounding box of Mesh.
FDelegateHandle MeshObjectChangedHandle
Handle for OnMeshObjectChanged which is registered with MeshObject::OnMeshChanged delegate.
TUniquePtr< FDynamicMesh3 > RenderMesh
TUniquePtr< IRenderMeshPostProcessor > RenderMeshPostProcessor
TUniqueFunction< bool(const FDynamicMesh3 *, int32)> SecondaryTriFilterFunc = nullptr
TUniqueFunction< FColor(const FDynamicMesh3 *, int)> TriangleColorFunc = nullptr
If this function is set, we will use these colors instead of vertex colors.
TUniqueFunction< void(FVector4f &)> VertexColorMappingFunc = nullptr
If this function is set, DynamicMesh Attribute Color Overlay colors will be passed through this function before sending to render buffers.
Protected Attributes inherited from UBaseDynamicMeshComponent
bool bDrawSecondaryBuffers = true
TObjectPtr< UMaterialInterface > SecondaryWireframeMaterialOverride = nullptr
TObjectPtr< UMaterialInterface > WireframeMaterialOverride = nullptr
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Member Functions
virtual GEOMETRYFRAMEWORK_API void ApplyTransform (const FTransform3d &Transform, bool bInvert) override
Apply transform to internal mesh.
void BroadcastMeshPropertyChangeEvent ()
virtual GEOMETRYFRAMEWORK_API void EditMesh (TFunctionRef< void(UE::Geometry::FDynamicMesh3 &)> EditFunc, EDynamicMeshComponentRenderUpdateMode UpdateMode=EDynamicMeshComponentRenderUpdateMode::FullUpdate)
Allow external code to to edit the internal mesh.
void InternalOnMeshUpdated ()
bool IsEditable () const
If set to false, this blocks external code from being able to modify the internal mesh.
virtual GEOMETRYFRAMEWORK_API void ProcessMesh (TFunctionRef< void(const UE::Geometry::FDynamicMesh3 &)> ProcessFunc) const
Allow external code to read the internal mesh.
void SetIsEditable (bool bInIsEditable)
GENERATED_UCLASS_BODY() public virtual GEOMETRYFRAMEWORK_API void SetMesh (UE::Geometry::FDynamicMesh3 &&MoveMesh) override
Replace the current UDynamicMesh with a new one, and transfer ownership of NewMesh to this Component.
UFUNCTION () bool AllowsGeometrySelection() const
UFUNCTION () EDynamicMeshComponentTangentsMode GetTangentsTypePure() const
UFUNCTION () void SetAllowsGeometrySelection(bool bInAllowsGeometrySelection)
Enable/Disable interactive geometry element selection for the mesh.
UPROPERTY () bool bAllowsGeometrySelection
If set to false, the geometry element selection UI will not be used for this mesh component.
Static Private Attributes
static constexpr EDynamicMeshComponentTangentsMode UseDefaultTangentsType = EDynamicMeshComponentTangentsMode::ExternallyProvided
Additional Inherited Members
Static Public Member Functions inherited from UBaseDynamicMeshComponent
static GEOMETRYFRAMEWORK_API void SetDefaultVertexColorMaterial (UMaterialInterface *Material)
Set the vertex color material used for all BaseDynamicMeshComponent-derived Components.
static GEOMETRYFRAMEWORK_API void SetDefaultWireframeMaterial (UMaterialInterface *Material)
Set the wireframe material used for all BaseDynamicMeshComponent-derived Components.
Static Protected Member Functions inherited from UBaseDynamicMeshComponent
static GEOMETRYFRAMEWORK_API UMaterialInterface * GetDefaultVertexColorMaterial_RenderThread ()
static GEOMETRYFRAMEWORK_API UMaterialInterface * GetDefaultWireframeMaterial_RenderThread ()
static GEOMETRYFRAMEWORK_API void InitializeDefaultMaterials ()
Detailed Description
Definition at line 171 of file DynamicMeshComponent.h.
Member Function Documentation
ApplyChange() [1/3]
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ApplyChange (const FMeshChange * Change, bool bRevert) override virtual
Apply a general mesh change to the mesh.
Reimplemented from UBaseDynamicMeshComponent.
References ApplyChange().
ApplyChange() [2/3]
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ApplyChange (const FMeshReplacementChange * Change, bool bRevert) override virtual
Apply a mesh replacement change to mesh.
Reimplemented from UBaseDynamicMeshComponent.
References ApplyChange().
ApplyChange() [3/3]
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ApplyChange (const FMeshVertexChange * Change, bool bRevert) override virtual
Apply a vertex deformation change to the mesh.
Reimplemented from UBaseDynamicMeshComponent.
References ApplyChange().
Referenced by ApplyChange(), ApplyChange(), and ApplyChange().
ApplyTransform()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ApplyTransform (const FTransform3d & Transform, bool bInvert) override private virtual
Apply transform to internal mesh.
In some cases this can be more efficient than a general edit.
Parameters
bInvert if true, inverse tranform is applied instead of forward transform
Reimplemented from UBaseDynamicMeshComponent.
References Transform.
BeginDestroy()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::BeginDestroy () override protected virtual
Reimplemented from UMeshComponent.
BroadcastMeshPropertyChangeEvent()
void UDynamicMeshComponent::BroadcastMeshPropertyChangeEvent () private
CalcBounds()
virtual GEOMETRYFRAMEWORK_API FBoxSphereBounds UDynamicMeshComponent::CalcBounds (const FTransform & LocalToWorld) const override protected virtual
ClearSimpleCollisionShapes()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ClearSimpleCollisionShapes (bool bUpdateCollision) virtual
Clear the simple collision shapes associated with this mesh component.
Parameters
bUpdateCollision Whether to automatically call UpdateCollision() – if false, manually call it to register the change with the physics system
ClearTriangleColorFunction()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ClearTriangleColorFunction (EDynamicMeshComponentRenderUpdateMode UpdateMode = EDynamicMeshComponentRenderUpdateMode::FastUpdate) virtual
Clear an active triangle color function if one exists, and update the mesh.
References ClearTriangleColorFunction().
Referenced by ClearTriangleColorFunction().
ClearVertexColorRemappingFunction()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ClearVertexColorRemappingFunction (EDynamicMeshComponentRenderUpdateMode UpdateMode = EDynamicMeshComponentRenderUpdateMode::FastUpdate) virtual
Clear an active VertexColor Remapping function if one exists, and update the mesh.
References ClearVertexColorRemappingFunction().
Referenced by ClearVertexColorRemappingFunction().
ContainsPhysicsTriMeshData()
virtual GEOMETRYFRAMEWORK_API bool UDynamicMeshComponent::ContainsPhysicsTriMeshData (bool InUseAllTriData) const override virtual
Interface for checking if the implementing objects contains triangle mesh collision data.
Returns
true if the implementing object contains triangle mesh data, false otherwise
Reimplemented from IInterface_CollisionDataProvider.
References ContainsPhysicsTriMeshData(), and IInterface_CollisionDataProvider::InUseAllTriData.
Referenced by ContainsPhysicsTriMeshData().
CreateBodySetupHelper()
virtual GEOMETRYFRAMEWORK_API UBodySetup * UDynamicMeshComponent::CreateBodySetupHelper () protected virtual
References CreateBodySetupHelper().
Referenced by CreateBodySetupHelper().
CreateSceneProxy()
virtual GEOMETRYFRAMEWORK_API FPrimitiveSceneProxy * UDynamicMeshComponent::CreateSceneProxy () override protected virtual
DECLARE_MULTICAST_DELEGATE_ThreeParams() [1/2]
UDynamicMeshComponent::DECLARE_MULTICAST_DELEGATE_ThreeParams (FMeshRegionModified , UDynamicMeshComponent * , const FMeshRegionChangeBase * , bool)
This delegate fires when the mesh has been changed via an FMeshRegionChange-derived change – FMeshChange, FMeshVertexChange, or FMeshReplacementChange Note that in the case of an FMeshVertexChange, the OnMeshVerticesChanged delegate will also fire.
References DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_ThreeParams() [2/2]
UDynamicMeshComponent::DECLARE_MULTICAST_DELEGATE_ThreeParams (FMeshVerticesModified , UDynamicMeshComponent * , const FMeshVertexChange * , bool)
This delegate fires when the mesh vertices have been changed via an FMeshVertexChange.
References DECLARE_MULTICAST_DELEGATE_ThreeParams().
Referenced by DECLARE_MULTICAST_DELEGATE_ThreeParams(), and DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_TwoParams()
UDynamicMeshComponent::DECLARE_MULTICAST_DELEGATE_TwoParams (FComponentChildrenChangedDelegate , USceneComponent * , bool)
References DECLARE_MULTICAST_DELEGATE_TwoParams().
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams().
DisableSecondaryTriangleBuffers()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::DisableSecondaryTriangleBuffers () virtual
Disable secondary triangle buffers.
This invalidates the SceneProxy.
References DisableSecondaryTriangleBuffers().
Referenced by DisableSecondaryTriangleBuffers().
EditMesh()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::EditMesh (TFunctionRef< void(UE::Geometry::FDynamicMesh3 &)> EditFunc, EDynamicMeshComponentRenderUpdateMode UpdateMode = EDynamicMeshComponentRenderUpdateMode::FullUpdate) private virtual
Allow external code to to edit the internal mesh.
EnableSecondaryTriangleBuffers()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::EnableSecondaryTriangleBuffers (TUniqueFunction< bool(const FDynamicMesh3 *, int32)> SecondaryTriFilterFunc) virtual
If Secondary triangle buffers are enabled, then we will filter triangles that pass the given predicate function into a second index buffer.
These triangles will be drawn with the Secondary render material that is set in the BaseDynamicMeshComponent. Calling this function invalidates the SceneProxy.
References EnableSecondaryTriangleBuffers(), and SecondaryTriFilterFunc.
Referenced by EnableSecondaryTriangleBuffers().
FastNotifyColorsUpdated()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyColorsUpdated ()
Call this instead of NotifyMeshUpdated() if you have only updated the vertex colors (or triangle color function).
This function will update the existing RenderProxy buffers if possible
FastNotifyPositionsUpdated()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyPositionsUpdated (bool bNormals = false, bool bColors = false, bool bUVs = false)
Call this instead of NotifyMeshUpdated() if you have only updated the vertex positions (and possibly some attributes).
This function will update the existing RenderProxy buffers if possible
References bColors, bNormals, and bUVs.
FastNotifySecondaryTrianglesChanged()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifySecondaryTrianglesChanged ()
Call this instead of NotifyMeshUpdated() if you have only updated secondary triangle sorting.
This function will update the existing buffers if possible, without rebuilding entire RenderProxy.
FastNotifyTriangleVerticesUpdated() [1/2]
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyTriangleVerticesUpdated (const TArray< int32 > & Triangles, EMeshRenderAttributeFlags UpdatedAttributes)
This function updates vertex positions/attributes of existing SceneProxy render buffers if possible, for the given triangles.
If a FMeshRenderDecomposition has not been explicitly set, call is forwarded to FastNotifyVertexAttributesUpdated()
FastNotifyTriangleVerticesUpdated() [2/2]
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyTriangleVerticesUpdated (const TSet< int32 > & Triangles, EMeshRenderAttributeFlags UpdatedAttributes)
This function updates vertex positions/attributes of existing SceneProxy render buffers if possible, for the given triangles.
If a FMeshRenderDecomposition has not been explicitly set, call is forwarded to FastNotifyVertexAttributesUpdated()
FastNotifyTriangleVerticesUpdated_ApplyPrecompute()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyTriangleVerticesUpdated_ApplyPrecompute (const TArray< int32 > & Triangles, EMeshRenderAttributeFlags UpdatedAttributes, TFuture< bool > & Precompute, const TArray< int32 > & UpdateSets, const UE::Geometry::FAxisAlignedBox3d & UpdateSetBounds)
This function updates vertex positions/attributes of existing SceneProxy render buffers if possible, for the given triangles.
The assumption is that FastNotifyTriangleVerticesUpdated_TryPrecompute() was used to get the Precompute future, this function will Wait() until it is done and then use the UpdateSets and UpdateSetBounds that were computed (must be the same variables passed to FastNotifyTriangleVerticesUpdated_TryPrecompute). If the Precompute future returns false, then we forward the call to FastNotifyTriangleVerticesUpdated(), which will do more work.
FastNotifyTriangleVerticesUpdated_TryPrecompute()
GEOMETRYFRAMEWORK_API TFuture< bool > UDynamicMeshComponent::FastNotifyTriangleVerticesUpdated_TryPrecompute (const TArray< int32 > & Triangles, TArray< int32 > & UpdateSetsOut, UE::Geometry::FAxisAlignedBox3d & BoundsOut)
If a Decomposition is set on this Component, and everything is currently valid (proxy/etc), precompute the set of buffers that will be modified, as well as the bounds of the modified region.
These are both computed in parallel. Use FastNotifyTriangleVerticesUpdated_ApplyPrecompute() with the returned future to apply this precomputation.
Returns
a future that will (eventually) return true if the precompute is OK, and (immediately) false if it is not
FastNotifyUVsUpdated()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyUVsUpdated ()
Call this instead of NotifyMeshUpdated() if you have only updated the vertex uvs.
This function will update the existing RenderProxy buffers if possible
FastNotifyVertexAttributesUpdated() [1/2]
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyVertexAttributesUpdated (bool bNormals, bool bColors, bool bUVs)
Call this instead of NotifyMeshUpdated() if you have only updated the vertex attributes (but not positions).
This function will update the existing RenderProxy buffers if possible, rather than create new ones.
References bColors, bNormals, and bUVs.
FastNotifyVertexAttributesUpdated() [2/2]
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FastNotifyVertexAttributesUpdated (EMeshRenderAttributeFlags UpdatedAttributes)
Call this instead of NotifyMeshUpdated() if you have only updated the vertex positions/attributes This function will update the existing RenderProxy buffers if possible, rather than create new ones.
FinishPhysicsAsyncCook()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::FinishPhysicsAsyncCook (bool bSuccess, UBodySetup * FinishedBodySetup) protected virtual
Once async physics cook is done, create needed state.
References FinishPhysicsAsyncCook().
Referenced by FinishPhysicsAsyncCook().
GetAutoCalculatedTangents()
GEOMETRYFRAMEWORK_API const UE::Geometry::FMeshTangentsf * UDynamicMeshComponent::GetAutoCalculatedTangents ()
Returns
AutoCalculated Tangent Set, which may require that they be recomputed, or nullptr if not enabled/available
GetBaseSceneProxy()
virtual FBaseDynamicMeshSceneProxy * UDynamicMeshComponent::GetBaseSceneProxy () inline override protected virtual
Subclass must implement this to return scene proxy if available, or nullptr.
Reimplemented from UBaseDynamicMeshComponent.
Definition at line 854 of file DynamicMeshComponent.h.
References UBaseDynamicMeshComponent::FBaseDynamicMeshSceneProxy, GetBaseSceneProxy(), and GetCurrentSceneProxy().
Referenced by GetBaseSceneProxy().
GetBodySetup() [1/2]
virtual const UBodySetup * UDynamicMeshComponent::GetBodySetup () const inline virtual
Returns
current BodySetup for this Component, or nullptr if it does not exist
Definition at line 725 of file DynamicMeshComponent.h.
References GetBodySetup().
Referenced by GetBodySetup().
GetBodySetup() [2/2]
virtual GEOMETRYFRAMEWORK_API UBodySetup * UDynamicMeshComponent::GetBodySetup () override virtual
Returns
BodySetup for this Component. A new BodySetup will be created if one does not exist.
GetCurrentSceneProxy()
GEOMETRYFRAMEWORK_API FDynamicMeshSceneProxy * UDynamicMeshComponent::GetCurrentSceneProxy () protected
Returns
current render proxy, if valid, otherwise nullptr
Referenced by GetBaseSceneProxy().
GetGroupColor()
GEOMETRYFRAMEWORK_API FColor UDynamicMeshComponent::GetGroupColor (const FDynamicMesh3 * Mesh, int TriangleID) const protected
This function is passed via lambda to the RenderProxy when BaseDynamicMeshComponent::ColorMode == Polygroups.
References GetGroupColor(), and Mesh.
Referenced by GetGroupColor().
GetInvalidateProxyOnChangeEnabled()
bool UDynamicMeshComponent::GetInvalidateProxyOnChangeEnabled () const inline
Returns
true if InvalidateProxyOnChange is enabled (default)
Definition at line 422 of file DynamicMeshComponent.h.
References bInvalidateProxyOnChange, and GetInvalidateProxyOnChangeEnabled().
Referenced by GetInvalidateProxyOnChangeEnabled().
GetPhysicsTriMeshData()
virtual GEOMETRYFRAMEWORK_API bool UDynamicMeshComponent::GetPhysicsTriMeshData (struct FTriMeshCollisionData * CollisionData, bool InUseAllTriData) override virtual
References GetPhysicsTriMeshData(), and IInterface_CollisionDataProvider::InUseAllTriData.
Referenced by GetPhysicsTriMeshData().
GetRenderMesh() [1/2]
virtual GEOMETRYFRAMEWORK_API FDynamicMesh3 * UDynamicMeshComponent::GetRenderMesh () virtual
The SceneProxy should call these functions to get the post-processed RenderMesh.
(See IRenderMeshPostProcessor.)
References GetRenderMesh().
Referenced by GetRenderMesh(), and GetRenderMesh().
GetRenderMesh() [2/2]
virtual GEOMETRYFRAMEWORK_API const FDynamicMesh3 * UDynamicMeshComponent::GetRenderMesh () const virtual
The SceneProxy should call these functions to get the post-processed RenderMesh.
(See IRenderMeshPostProcessor.)
References GetRenderMesh().
GetSimpleCollisionShapes()
const FKAggregateGeom & UDynamicMeshComponent::GetSimpleCollisionShapes () const inline
Definition at line 748 of file DynamicMeshComponent.h.
References GetSimpleCollisionShapes().
Referenced by GetSimpleCollisionShapes().
GetTriangleColor()
GEOMETRYFRAMEWORK_API FColor UDynamicMeshComponent::GetTriangleColor (const FDynamicMesh3 * Mesh, int TriangleID) protected
This function is passed via lambda to the RenderProxy to be able to access TriangleColorFunc.
References GetTriangleColor(), and Mesh.
Referenced by GetTriangleColor().
GetTriMeshSizeEstimates()
virtual GEOMETRYFRAMEWORK_API bool UDynamicMeshComponent::GetTriMeshSizeEstimates (struct FTriMeshCollisionDataEstimates & OutTriMeshEstimates, bool bInUseAllTriData) const override virtual
Returns an estimate of how much data would be retrieved by GetPhysicsTriMeshData.
Parameters
OutTriMeshEstimates - structure given by the caller to be filled with tri mesh estimate data
Returns
true if successful, false if unable to successfully fill in data structure
Reimplemented from IInterface_CollisionDataProvider.
References GetTriMeshSizeEstimates().
Referenced by GetTriMeshSizeEstimates().
HasTriangleColorFunction()
virtual GEOMETRYFRAMEWORK_API bool UDynamicMeshComponent::HasTriangleColorFunction () virtual
Returns
true if a triangle color function is configured
References HasTriangleColorFunction().
Referenced by HasTriangleColorFunction().
HasVertexColorRemappingFunction()
virtual GEOMETRYFRAMEWORK_API bool UDynamicMeshComponent::HasVertexColorRemappingFunction () virtual
Returns
true if a VertexColor Remapping function is configured
References HasVertexColorRemappingFunction().
Referenced by HasVertexColorRemappingFunction().
InternalOnMeshUpdated()
void UDynamicMeshComponent::InternalOnMeshUpdated () private
InvalidateAutoCalculatedTangents()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::InvalidateAutoCalculatedTangents () virtual
This function marks the auto tangents as dirty, they will be recomputed before they are used again.
InvalidatePhysicsData()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::InvalidatePhysicsData () protected virtual
References InvalidatePhysicsData().
Referenced by InvalidatePhysicsData().
IsEditable()
bool UDynamicMeshComponent::IsEditable () const inline private
If set to false, this blocks external code from being able to modify the internal mesh.
It prevents modifications through methods on this UDynamicMeshComponent such as EditMesh/SetMesh, However, this cannot prevent code from modifying the underlying UDynamicMesh through direct references (ex. via GetDynamicMesh()->SetMesh).
Definition at line 234 of file DynamicMeshComponent.h.
References bIsEditable.
NotifyMaterialSetUpdated()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::NotifyMaterialSetUpdated () protected virtual
This is called to tell our RenderProxy about modifications to the material set.
We need to pass this on for things like material validation in the Editor.
Reimplemented from UBaseDynamicMeshComponent.
References NotifyMaterialSetUpdated().
Referenced by NotifyMaterialSetUpdated().
NotifyMeshUpdated()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::NotifyMeshUpdated () override virtual
Call this if you update the mesh via GetMesh().
This will destroy the existing RenderProxy and create a new one.
Todo
should provide a function that calls a lambda to modify the mesh, and only return const mesh pointer
Reimplemented from UBaseDynamicMeshComponent.
OnChildAttached()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::OnChildAttached (USceneComponent * ChildComponent) override protected virtual
OnChildDetached()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::OnChildDetached (USceneComponent * ChildComponent) override protected virtual
OnMeshObjectChanged()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::OnMeshObjectChanged (UDynamicMesh * ChangedMeshObject, FDynamicMeshChangeInfo ChangeInfo) protected
Called whenever internal MeshObject is modified, fires OnMeshChanged and OnMeshVerticesChanged above.
PostEditChangeProperty()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override protected
PostEditImport()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::PostEditImport () override protected virtual
PostLoad()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::PostLoad () override protected virtual
ProcessMesh()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ProcessMesh (TFunctionRef< void(const UE::Geometry::FDynamicMesh3 &)> ProcessFunc) const private virtual
Allow external code to read the internal mesh.
Reimplemented from UBaseDynamicMeshComponent.
RebuildPhysicsData()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::RebuildPhysicsData () protected virtual
References RebuildPhysicsData().
Referenced by RebuildPhysicsData().
RemapVertexColor()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::RemapVertexColor (FVector4f & VertexColorInOut) protected
This function is passed via lambda to the RenderProxy to be able to access VertexColorMappingFunc.
References RemapVertexColor().
Referenced by RemapVertexColor().
ResetProxy()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::ResetProxy () protected
Fully invalidate all rendering data for this Component.
Current Proxy will be discarded, Bounds and possibly Tangents recomputed, etc
Serialize()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::Serialize (FArchive & Ar) override protected virtual
References Ar.
SetBodySetup()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetBodySetup (UBodySetup * NewSetup) protected virtual
Returns
Set new BodySetup for this Component.
References SetBodySetup().
Referenced by SetBodySetup().
SetExternalDecomposition()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetExternalDecomposition (TUniquePtr< FMeshRenderDecomposition > Decomposition) virtual
Configure a decomposition of the mesh, which will result in separate render buffers for each decomposition triangle group.
Invalidates existing SceneProxy.
References Decomposition, and SetExternalDecomposition().
Referenced by SetExternalDecomposition().
SetInvalidateProxyOnChangeEnabled()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetInvalidateProxyOnChangeEnabled (bool bEnabled)
When a FMeshChange or FMeshVertexChange is applied, by default we currently fully invalidate the render proxy.
However in certain realtime situations (eg like Sculpting tools) it can be critical to undo/redo performance to do more optimized render data updates (eg using one of the FastXYZ functions above). To allow for that, the full proxy invalidation on change can be (temporarily!) disabled using this function.
References SetInvalidateProxyOnChangeEnabled().
Referenced by SetInvalidateProxyOnChangeEnabled().
SetIsEditable()
void UDynamicMeshComponent::SetIsEditable (bool bInIsEditable) inline private
Definition at line 235 of file DynamicMeshComponent.h.
References bIsEditable.
SetMesh()
GENERATED_UCLASS_BODY() public virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetMesh (UE::Geometry::FDynamicMesh3 && MoveMesh) override private virtual
Replace the current UDynamicMesh with a new one, and transfer ownership of NewMesh to this Component.
Returns
pointer to internal mesh
Warning
avoid usage of this function, access via GetDynamicMesh() instead
Returns
pointer to internal mesh
Warning
avoid usage of this function, access via GetDynamicMesh() instead
Returns
the child UDynamicMesh This can be used to (eg) assign a UDynamicMesh created with NewObject in the Transient Package to this Component.
Warning
If NewMesh is owned/Outer'd to another DynamicMeshComponent, a GLEO error may occur if that Component is serialized. initialize the internal mesh from a DynamicMesh
SetRenderMeshPostProcessor()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetRenderMeshPostProcessor (TUniquePtr< IRenderMeshPostProcessor > Processor) virtual
Add a render mesh processor, to be called before the mesh is sent for rendering.
References SetRenderMeshPostProcessor().
Referenced by SetRenderMeshPostProcessor().
SetSceneProxyVerifyUsedMaterials()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetSceneProxyVerifyUsedMaterials (bool bState)
Set whether or not to validate mesh batch materials against the component materials.
SetSimpleCollisionShapes()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetSimpleCollisionShapes (const struct FKAggregateGeom & AggGeom, bool bUpdateCollision) virtual
Update the simple collision shapes associated with this mesh component.
Parameters
AggGeom New simple collision shapes to be used
bUpdateCollision Whether to automatically call UpdateCollision() – if false, manually call it to register the change with the physics system
References SetSimpleCollisionShapes().
Referenced by SetSimpleCollisionShapes().
SetTransientDeferCollisionUpdates()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetTransientDeferCollisionUpdates (bool bEnabled)
The bDeferCollisionUpdates property is a serialized Component setting that controls when collision is regenerated.
However, in some cases where a UDynamicMesh is being programmatically edited (eg like a live deformation/etc), we want to defer collision updates during the user interaction, but not change the serialized property. In this case a non-serialized version of the flag can be temporarily set via this function in C++.
References SetTransientDeferCollisionUpdates().
Referenced by SetTransientDeferCollisionUpdates().
SetTriangleColorFunction()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetTriangleColorFunction (TUniqueFunction< FColor(const FDynamicMesh3 *, int)> TriangleColorFuncIn, EDynamicMeshComponentRenderUpdateMode UpdateMode = EDynamicMeshComponentRenderUpdateMode::FastUpdate) virtual
Set an active triangle color function if one exists, and update the mesh.
References SetTriangleColorFunction().
Referenced by SetTriangleColorFunction().
SetVertexColorRemappingFunction()
virtual GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::SetVertexColorRemappingFunction (TUniqueFunction< void(FVector4f &)> ColorMapFuncIn, EDynamicMeshComponentRenderUpdateMode UpdateMode = EDynamicMeshComponentRenderUpdateMode::FastUpdate) virtual
Set an active VertexColor Remapping function if one exists, and update the mesh.
References SetVertexColorRemappingFunction().
Referenced by SetVertexColorRemappingFunction().
UE_DEPRECATED() [1/5]
UDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") protected
References UE_DEPRECATED().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/5]
UDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") protected
UE_DEPRECATED() [3/5]
UDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") protected
References UE_DEPRECATED().
UE_DEPRECATED() [4/5]
UDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") inline protected
Definition at line 687 of file DynamicMeshComponent.h.
References UE_DEPRECATED().
UE_DEPRECATED() [5/5]
UDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") inline protected
Definition at line 683 of file DynamicMeshComponent.h.
References UE_DEPRECATED().
UFUNCTION() [1/13]
UDynamicMeshComponent::UFUNCTION () const inline private
Returns
Whether geometry elements (triangles, edges, etc) of the dynamic mesh can be interactively selected.
Definition at line 241 of file DynamicMeshComponent.h.
References bool, and Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/13]
UDynamicMeshComponent::UFUNCTION () const inline
Definition at line 638 of file DynamicMeshComponent.h.
References Category, UFUNCTION(), and UseDefaultTangentsType.
UFUNCTION() [3/13]
UDynamicMeshComponent::UFUNCTION () const inline private
Definition at line 646 of file DynamicMeshComponent.h.
References Category.
UFUNCTION() [4/13]
UDynamicMeshComponent::UFUNCTION ()
Compute the maximum MaterialID on the DynamicMesh, and ensure that Material Slots match.
Pass both arguments as false to just do a check.
Parameters
bCreateIfMissing if true, add extra (empty) Material Slots to match max MaterialID
bDeleteExtraSlots if true, extra Material Slots beyond max MaterialID are removed
Returns
true if at the end of this function, Material Slot Count == Max MaterialID
References bDeleteExtraSlots, Category, and UFUNCTION().
UFUNCTION() [5/13]
UDynamicMeshComponent::UFUNCTION ()
Notify the Component that it's DynamicMesh has been modified externally.
This will result in all Rendering Data for the Component being rebuilt on the next frame (internally the Scene Proxy is fully destroyed and rebuilt).
You must use this function if the mesh triangulation has been modified, or if polygroups or material assignments have been changed, or if Normal/UV/Color topology has changed (ie new split-vertices have been introduced). If only vertex attribute values (position, normals, UVs, colors) have been modified, then Notify Vertex Attributes Updated can be used to do a faster update.
References Category.
UFUNCTION() [6/13]
UDynamicMeshComponent::UFUNCTION ()
Notify the Component that vertex attribute values of it's DynamicMesh have been modified externally.
This will result in Rendering vertex buffers being updated. This update path is more efficient than doing a full Notify Mesh Updated.
Warning
it is invalid to call this function if (1) the mesh triangulation has also been changed, (2) triangle MaterialIDs have been changed, or (3) any attribute overlay (normal, color, UV) topology has been modified, ie split-vertices have been added/removed. Behavior of this function is undefined in these cases and may crash. If you are unsure, use Notify Mesh Updated.
References Category, and UFUNCTION().
UFUNCTION() [7/13]
UDynamicMeshComponent::UFUNCTION ()
Force an update of the Collision/Physics data for this Component.
Parameters
bOnlyIfPending only update if a collision update is pending, ie the underlying DynamicMesh changed and bDeferCollisionUpdates is enabled
References Category.
UFUNCTION() [8/13]
UDynamicMeshComponent::UFUNCTION () const &
Set new list of Materials for the Mesh.
Dynamic Mesh Component does not have Slot Names, so the size of the Material Set should be the same as the number of different Material IDs on the mesh MaterialID attribute
Parameters
bDeleteExtraSlots if true, extra Material Slots beyond max NewMaterialSet.Num() are removed
References Category, and UFUNCTION().
UFUNCTION() [9/13]
UDynamicMeshComponent::UFUNCTION ()
calls SetComplexAsSimpleCollisionEnabled(true, true)
References Category.
UFUNCTION() [10/13]
UDynamicMeshComponent::UFUNCTION ()
If bEnabled=true, sets bEnableComplexCollision=true and CollisionType=CTF_UseComplexAsSimple If bEnabled=true, sets bEnableComplexCollision=false and CollisionType=CTF_UseDefault.
Parameters
bImmediateUpdate if true, UpdateCollision(true) is called
References Category, and UFUNCTION().
UFUNCTION() [11/13]
UDynamicMeshComponent::UFUNCTION ()
Set value of bDeferCollisionUpdates, when enabled, collision is not automatically recomputed each time the mesh changes.
Parameters
bImmediateUpdate if true, UpdateCollision(true) is called if bEnabled=false, ie to force a collision rebuild
References bImmediateUpdate, Category, and UFUNCTION().
UFUNCTION() [12/13]
UDynamicMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [13/13]
UDynamicMeshComponent::UFUNCTION () inline private
Enable/Disable interactive geometry element selection for the mesh.
Useful to disable geometry selection on procedural meshes where the selection will be frequently invalidated.
Parameters
bInAllowsGeometrySelection Whether geometry elements (triangles, edges, etc) of the dynamic mesh will be interactively selectable.
Definition at line 248 of file DynamicMeshComponent.h.
References Category.
UpdateAutoCalculatedTangents()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::UpdateAutoCalculatedTangents () protected
References UpdateAutoCalculatedTangents().
Referenced by UpdateAutoCalculatedTangents().
UpdateLocalBounds()
GEOMETRYFRAMEWORK_API void UDynamicMeshComponent::UpdateLocalBounds () protected
Recompute LocalBounds from the current Mesh.
References UpdateLocalBounds().
Referenced by UpdateLocalBounds().
UPROPERTY() [1/11]
UDynamicMeshComponent::UPROPERTY ()
If true, current mesh will be used as Complex Collision source mesh.
This is independent of the CollisionType setting, ie, even if Complex collision is enabled, if this is false, then the Complex Collision mesh will be empty
References Category, and UPROPERTY().
UPROPERTY() [2/11]
UDynamicMeshComponent::UPROPERTY ()
If true, updates to the mesh will not result in immediate collision regeneration.
Useful when the mesh will be modified multiple times before collision is needed.
References Category, and UPROPERTY().
UPROPERTY() [3/11]
UDynamicMeshComponent::UPROPERTY ()
If true, UV hit results will not be enabled for this mesh's complex collision even if they are enabled for the project settings generally.
This can make the complex build faster and take less memory.
References Category, and UPROPERTY().
UPROPERTY() [4/11]
UDynamicMeshComponent::UPROPERTY () private
If set to false, the geometry element selection UI will not be used for this mesh component.
This is useful for procedural meshes where selection would be frequently invalidated.
References bool.
UPROPERTY() [5/11]
UDynamicMeshComponent::UPROPERTY ()
Controls whether the physics cooking should be done off the game thread.
This should be used when collision geometry doesn't have to be immediately up to date (For example streaming in far away objects)
References bool, and Category.
UPROPERTY() [6/11]
UDynamicMeshComponent::UPROPERTY () protected
Tangent source defines whether we use the provided tangents on the Dynamic Mesh, autogenerate tangents, or do not use tangents.
References Category, and Default.
UPROPERTY() [7/11]
UDynamicMeshComponent::UPROPERTY () protected
Queue for async body setups that are being cooked.
References transient, and UPROPERTY().
UPROPERTY() [8/11]
UDynamicMeshComponent::UPROPERTY ()
Type of Collision Geometry to use for this Mesh.
References Category, and UPROPERTY().
UPROPERTY() [9/11]
UDynamicMeshComponent::UPROPERTY () protected
References UPROPERTY().
UPROPERTY() [10/11]
UDynamicMeshComponent::UPROPERTY () protected
Internal FDynamicMesh is stored inside a UDynamicMesh container, which allows it to be used from BP, shared with other UObjects, and so on.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [11/11]
UDynamicMeshComponent::UPROPERTY () protected
Simplified collision representation for the mesh component.
References BodySetup, Category, meta, and UPROPERTY().
WantsNegXTriMesh()
virtual GEOMETRYFRAMEWORK_API bool UDynamicMeshComponent::WantsNegXTriMesh () override virtual
Do we want to create a negative version of this mesh.
Reimplemented from IInterface_CollisionDataProvider.
References WantsNegXTriMesh().
Referenced by WantsNegXTriMesh().
Field Documentation
AutoCalculatedTangents
UE::Geometry::FMeshTangentsf UDynamicMeshComponent::AutoCalculatedTangents protected
Set of per-triangle-vertex tangents computed for the current mesh.
Only valid if bAutoCalculatedTangentsValid == true
Definition at line 669 of file DynamicMeshComponent.h.
bAutoCalculatedTangentsValid
bool UDynamicMeshComponent::bAutoCalculatedTangentsValid = false protected
true if AutoCalculatedTangents has been computed for current mesh
Definition at line 666 of file DynamicMeshComponent.h.
bCollisionUpdatePending
bool UDynamicMeshComponent::bCollisionUpdatePending = false protected
Definition at line 797 of file DynamicMeshComponent.h.
bColors
bool bool bool UDynamicMeshComponent::bColors = true)
Definition at line 371 of file DynamicMeshComponent.h.
Referenced by FastNotifyPositionsUpdated(), and FastNotifyVertexAttributesUpdated().
bDeferCollisionUpdates
bool UDynamicMeshComponent::bDeferCollisionUpdates = false
Definition at line 775 of file DynamicMeshComponent.h.
bDeleteExtraSlots
bool UDynamicMeshComponent::bDeleteExtraSlots = true)
Definition at line 606 of file DynamicMeshComponent.h.
Referenced by UFUNCTION().
bDisableMeshUVHitResults
bool UDynamicMeshComponent::bDisableMeshUVHitResults = false
Definition at line 779 of file DynamicMeshComponent.h.
bEnableComplexCollision
bool UDynamicMeshComponent::bEnableComplexCollision = false
Definition at line 771 of file DynamicMeshComponent.h.
bImmediateUpdate
bool UDynamicMeshComponent::bImmediateUpdate = true)
Definition at line 709 of file DynamicMeshComponent.h.
Referenced by UFUNCTION().
bInvalidateProxyOnChange
bool UDynamicMeshComponent::bInvalidateProxyOnChange = true protected
If false, we don't completely invalidate the RenderProxy when ApplyChange() is called (assumption is it will be handled elsewhere)
Definition at line 426 of file DynamicMeshComponent.h.
Referenced by GetInvalidateProxyOnChangeEnabled().
bIsEditable
bool UDynamicMeshComponent::bIsEditable = true protected
If set to false, this blocks external code from being able to modify the internal mesh.
It prevents modifications through methods on this UDynamicMeshComponent such as EditMesh/SetMesh, However, this cannot prevent code from modifying the underlying UDynamicMesh through direct references (ex. via GetDynamicMesh()->SetMesh).
Definition at line 438 of file DynamicMeshComponent.h.
Referenced by IsEditable(), and SetIsEditable().
bNormals
bool UDynamicMeshComponent::bNormals = true
Definition at line 369 of file DynamicMeshComponent.h.
Referenced by FastNotifyPositionsUpdated(), and FastNotifyVertexAttributesUpdated().
bProxyValid
bool UDynamicMeshComponent::bProxyValid = false protected
If the render proxy is invalidated (eg by MarkRenderStateDirty()), it will be destroyed at the end of the frame, but the base SceneProxy pointer is not nulled out immediately.
As a result if we call various partial-update functions after invalidating the proxy, they may be operating on an invalid proxy. So we have to keep track of proxy-valid state ourselves.
Definition at line 843 of file DynamicMeshComponent.h.
bProxyVerifyUsedMaterials
bool UDynamicMeshComponent::bProxyVerifyUsedMaterials = true protected
If true, the render proxy will verify that the mesh batch materials match the contents from the component GetUsedMaterials().
Used material verification is prone to races when changing materials on this component in quick succession (for example, SetOverrideRenderMaterial). This parameter is provided to allow clients to opt out of used material verification for these use cases.
Definition at line 852 of file DynamicMeshComponent.h.
bTransientDeferCollisionUpdates
bool UDynamicMeshComponent::bTransientDeferCollisionUpdates = false protected
Definition at line 796 of file DynamicMeshComponent.h.
bUVs
bool bool UDynamicMeshComponent::bUVs = true
Definition at line 370 of file DynamicMeshComponent.h.
Referenced by FastNotifyPositionsUpdated(), and FastNotifyVertexAttributesUpdated().
Decomposition
TUniquePtr<FMeshRenderDecomposition> UDynamicMeshComponent::Decomposition protected
Definition at line 545 of file DynamicMeshComponent.h.
Referenced by SetExternalDecomposition().
LocalBounds
UE::Geometry::FAxisAlignedBox3d UDynamicMeshComponent::LocalBounds protected
Current local-space bounding box of Mesh.
Definition at line 806 of file DynamicMeshComponent.h.
MeshObjectChangedHandle
FDelegateHandle UDynamicMeshComponent::MeshObjectChangedHandle protected
Handle for OnMeshObjectChanged which is registered with MeshObject::OnMeshChanged delegate.
Definition at line 429 of file DynamicMeshComponent.h.
OnChildAttachmentModified
FComponentChildrenChangedDelegate UDynamicMeshComponent::OnChildAttachmentModified
The OnChildAttached() and OnChildDetached() implementations (from USceneComponent API) broadcast this delegate.
This allows Actors that have UDynamicMeshComponent's to respond to changes in their Component hierarchy.
Definition at line 591 of file DynamicMeshComponent.h.
OnMeshChanged
FSimpleMulticastDelegate UDynamicMeshComponent::OnMeshChanged
This delegate fires when the mesh has been changed.
Definition at line 398 of file DynamicMeshComponent.h.
OnMeshRegionChanged
FMeshRegionModified UDynamicMeshComponent::OnMeshRegionChanged
Definition at line 411 of file DynamicMeshComponent.h.
OnMeshVerticesChanged
FMeshVerticesModified UDynamicMeshComponent::OnMeshVerticesChanged
Definition at line 404 of file DynamicMeshComponent.h.
RenderMesh
TUniquePtr<FDynamicMesh3> UDynamicMeshComponent::RenderMesh protected
Definition at line 574 of file DynamicMeshComponent.h.
RenderMeshPostProcessor
TUniquePtr<IRenderMeshPostProcessor> UDynamicMeshComponent::RenderMeshPostProcessor protected
Definition at line 573 of file DynamicMeshComponent.h.
SecondaryTriFilterFunc
TUniqueFunction<bool(const FDynamicMesh3*, int32)> UDynamicMeshComponent::SecondaryTriFilterFunc = nullptr protected
Definition at line 525 of file DynamicMeshComponent.h.
Referenced by EnableSecondaryTriangleBuffers().
TriangleColorFunc
TUniqueFunction<FColor(const FDynamicMesh3*, int)> UDynamicMeshComponent::TriangleColorFunc = nullptr protected
If this function is set, we will use these colors instead of vertex colors.
Definition at line 469 of file DynamicMeshComponent.h.
UseDefaultTangentsType
EDynamicMeshComponentTangentsMode UDynamicMeshComponent::UseDefaultTangentsType = EDynamicMeshComponentTangentsMode::ExternallyProvided static constexpr private
Definition at line 632 of file DynamicMeshComponent.h.
Referenced by UFUNCTION().
VertexColorMappingFunc
TUniqueFunction<void(FVector4f&)> UDynamicMeshComponent::VertexColorMappingFunc = nullptr protected
If this function is set, DynamicMesh Attribute Color Overlay colors will be passed through this function before sending to render buffers.
Definition at line 497 of file DynamicMeshComponent.h.
The documentation for this class was generated from the following file:
DynamicMeshComponent.h