Unreal Engine 5.6 C++ API: TSharedRef< ObjectType, InMode > Class Template Reference
TSharedRef< ObjectType, InMode > Class Template Reference
TSharedRef is a non-nullable, non-intrusive reference-counted authoritative object reference.
#include "SharedPointer.h"
Public Types
using ElementType = ObjectType
using IntrusiveUnsetOptionalStateType = TSharedRef
Public Member Functions
TSharedRef ()
Constructs default shared reference that owns the default object for specified type.
TSharedRef (FIntrusiveUnsetOptionalState)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedRef (OtherType *InObject)
Constructs a shared reference that owns the specified object.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedRef (OtherType *InObject, DeleterType &&InDeleter)
Constructs a shared reference that owns the specified object.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedRef (SharedPointerInternals::TRawPtrProxy< OtherType > const &InRawPtrProxy)
Constructs a shared reference using a proxy reference to a raw pointer.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedRef (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > &&InRawPtrProxy)
Constructs a shared reference using a proxy reference to a raw pointer.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedRef (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const &InRawPtrProxy)
Constructs a shared reference using a proxy reference to a raw pointer.
FORCEINLINE TSharedRef (TSharedRef &&InSharedRef)
FORCEINLINE TSharedRef (TSharedRef const &InSharedRef)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedRef (TSharedRef< OtherType, Mode > const &InSharedRef)
Constructs a shared reference as a reference to an existing shared reference's object.
template<typename OtherType>
FORCEINLINE TSharedRef (TSharedRef< OtherType, Mode > const &InSharedRef, SharedPointerInternals::FConstCastTag)
Special constructor used internally to cast a 'const' shared reference a 'mutable' reference.
template<typename OtherType>
FORCEINLINE TSharedRef (TSharedRef< OtherType, Mode > const &InSharedRef, SharedPointerInternals::FStaticCastTag)
Special constructor used internally to statically cast one shared reference type to another.
template<typename OtherType>
FORCEINLINE TSharedRef (TSharedRef< OtherType, Mode > const &OtherSharedRef, ObjectType *InObject)
Aliasing constructor used to create a shared reference which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
FORCEINLINE ObjectType & Get () const
Returns a C++ reference to the object this shared reference is referencing.
FORCEINLINE int32 GetSharedReferenceCount () const
Returns the number of shared references to this object (including this reference.) IMPORTANT: Not necessarily fast!
FORCEINLINE bool IsUnique () const
Returns true if this is the only shared reference to this object.
FORCEINLINE ObjectType & operator* () const
Dereference operator returns a reference to the object this shared pointer points to.
FORCEINLINE ObjectType * operator-> () const
Arrow operator returns a pointer to this shared reference's object.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedRef & operator= (SharedPointerInternals::TRawPtrProxy< OtherType > const &InRawPtrProxy)
Assignment operator replaces this shared reference with the specified shared reference.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedRef & operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > &&InRawPtrProxy)
Assignment operator replaces this shared reference with the specified shared reference.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedRef & operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const &InRawPtrProxy)
Assignment operator replaces this shared reference with the specified shared reference.
FORCEINLINE TSharedRef & operator= (TSharedRef &&InSharedRef)
FORCEINLINE TSharedRef & operator= (TSharedRef const &InSharedRef)
Assignment operator replaces this shared reference with the specified shared reference.
bool operator== (FIntrusiveUnsetOptionalState) const
FORCEINLINE TSharedPtr< ObjectType, Mode > ToSharedPtr () const
Converts a shared reference to a shared pointer.
FORCEINLINE TWeakPtr< ObjectType, Mode > ToWeakPtr () const
Converts a shared reference to a weak ptr.
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
static constexpr ESPMode Mode = InMode
Private Member Functions
FORCEINLINE TSharedRef (ObjectType *InObject, SharedPointerInternals::TReferenceControllerBase< Mode > *InSharedReferenceCount)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedRef (TSharedPtr< OtherType, Mode > &&InSharedPtr)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedRef (TSharedPtr< OtherType, Mode > const &InSharedPtr)
Converts a shared pointer to a shared reference.
template<class OtherType>
void Init (OtherType *InObject)
FORCEINLINE bool IsValid () const
Checks to see if this shared reference is actually pointing to an object.
Private Attributes
ObjectType * Object
The object we're holding a reference to.
SharedPointerInternals::FSharedReferencer< Mode > SharedReferenceCount
Interface to the reference counter for this object.
Friends
template<class OtherType, ESPMode OtherMode>
class TSharedRef
template<class OtherType, ESPMode OtherMode>
class TSharedPtr
template<class OtherType, ESPMode OtherMode>
class TWeakPtr
TSharedRef UE::Core::Private::MakeSharedRef (ObjectType *InObject, SharedPointerInternals::TReferenceControllerBase< Mode > *InSharedReferenceCount)
Detailed Description
template<class ObjectType, ESPMode InMode>
class TSharedRef< ObjectType, InMode >
TSharedRef is a non-nullable, non-intrusive reference-counted authoritative object reference.
This shared reference will be conditionally thread-safe when the optional Mode template argument is set to ThreadSafe.
Definition at line 151 of file SharedPointer.h.
Member Typedef Documentation
ElementType
template<class ObjectType, ESPMode InMode> using TSharedRef< ObjectType, InMode >::ElementType = ObjectType
Definition at line 156 of file SharedPointer.h.
IntrusiveUnsetOptionalStateType
template<class ObjectType, ESPMode InMode> using TSharedRef< ObjectType, InMode >::IntrusiveUnsetOptionalStateType = TSharedRef
Definition at line 535 of file SharedPointer.h.
Constructor & Destructor Documentation
TSharedRef() [1/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (OtherType * InObject) inline explicit
Constructs a shared reference that owns the specified object.
Must not be nullptr.
Parameters
InObject Object this shared reference to retain a reference to
Definition at line 171 of file SharedPointer.h.
TSharedRef() [2/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (OtherType * InObject, DeleterType && InDeleter) inline
Constructs a shared reference that owns the specified object.
Must not be nullptr.
Parameters
InObject Object this shared pointer to retain a reference to
InDeleter Deleter object used to destroy the object when it is no longer referenced.
Definition at line 189 of file SharedPointer.h.
TSharedRef() [3/16]
template<class ObjectType, ESPMode InMode> TSharedRef< ObjectType, InMode >::TSharedRef () inline
Constructs default shared reference that owns the default object for specified type.
Used internally only. Please do not use!
Definition at line 201 of file SharedPointer.h.
TSharedRef() [4/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (SharedPointerInternals::TRawPtrProxy< OtherType > const & InRawPtrProxy) inline
Constructs a shared reference using a proxy reference to a raw pointer.
(See MakeShareable()) Must not be nullptr.
Parameters
InRawPtrProxy Proxy raw pointer that contains the object that the new shared reference will reference
Definition at line 220 of file SharedPointer.h.
TSharedRef() [5/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const & InRawPtrProxy) inline
Constructs a shared reference using a proxy reference to a raw pointer.
(See MakeShareable()) Must not be nullptr.
Parameters
InRawPtrProxy Proxy raw pointer that contains the object that the new shared reference will reference
Definition at line 245 of file SharedPointer.h.
TSharedRef() [6/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > && InRawPtrProxy) inline
Constructs a shared reference using a proxy reference to a raw pointer.
(See MakeShareable()) Must not be nullptr.
Parameters
InRawPtrProxy Proxy raw pointer that contains the object that the new shared reference will reference
Definition at line 270 of file SharedPointer.h.
TSharedRef() [7/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedRef< OtherType, Mode > const & InSharedRef) inline
Constructs a shared reference as a reference to an existing shared reference's object.
This constructor is needed so that we can implicitly upcast to base classes.
Parameters
InSharedRef The shared reference whose object we should create an additional reference to
Definition at line 293 of file SharedPointer.h.
TSharedRef() [8/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedRef< OtherType, Mode > const & InSharedRef, SharedPointerInternals::FStaticCastTag) inline
Special constructor used internally to statically cast one shared reference type to another.
You should never call this constructor directly. Instead, use the StaticCastSharedRef() function. This constructor creates a shared reference as a shared reference to an existing shared reference after statically casting that reference's object. This constructor is needed for static casts.
Parameters
InSharedRef The shared reference whose object we should create an additional reference to
Definition at line 308 of file SharedPointer.h.
TSharedRef() [9/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedRef< OtherType, Mode > const & InSharedRef, SharedPointerInternals::FConstCastTag) inline
Special constructor used internally to cast a 'const' shared reference a 'mutable' reference.
You should never call this constructor directly. Instead, use the ConstCastSharedRef() function. This constructor creates a shared reference as a shared reference to an existing shared reference after const casting that reference's object. This constructor is needed for const casts.
Parameters
InSharedRef The shared reference whose object we should create an additional reference to
Definition at line 323 of file SharedPointer.h.
TSharedRef() [10/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedRef< OtherType, Mode > const & OtherSharedRef, ObjectType * InObject) inline
Aliasing constructor used to create a shared reference which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
Parameters
OtherSharedRef The shared reference whose reference count should be shared.
InObject The object pointer to use (instead of the incoming shared pointer's object)
Definition at line 337 of file SharedPointer.h.
TSharedRef() [11/16]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedRef< ObjectType, InMode > const & InSharedRef) inline
Definition at line 346 of file SharedPointer.h.
TSharedRef() [12/16]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedRef< ObjectType, InMode > && InSharedRef) inline
Definition at line 351 of file SharedPointer.h.
TSharedRef() [13/16]
template<class ObjectType, ESPMode InMode> TSharedRef< ObjectType, InMode >::TSharedRef (FIntrusiveUnsetOptionalState) inline explicit
Definition at line 537 of file SharedPointer.h.
TSharedRef() [14/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedPtr< OtherType, Mode > const & InSharedPtr) inline explicit private
Converts a shared pointer to a shared reference.
The pointer must be valid or an assertion will trigger. NOTE: This explicit conversion constructor is intentionally private. Use 'ToSharedRef()' instead.
Returns
Reference to the object
Definition at line 572 of file SharedPointer.h.
TSharedRef() [15/16]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (TSharedPtr< OtherType, Mode > && InSharedPtr) inline explicit private
Definition at line 585 of file SharedPointer.h.
TSharedRef() [16/16]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedRef< ObjectType, InMode >::TSharedRef (ObjectType * InObject, SharedPointerInternals::TReferenceControllerBase< Mode > * InSharedReferenceCount) inline explicit private
Definition at line 635 of file SharedPointer.h.
Member Function Documentation
Get()
template<class ObjectType, ESPMode InMode> FORCEINLINE ObjectType & TSharedRef< ObjectType, InMode >::Get () const inline nodiscard
Returns a C++ reference to the object this shared reference is referencing.
Returns
The object owned by this shared reference
Definition at line 473 of file SharedPointer.h.
Referenced by UE::Sequencer::TViewModelPtr< FViewModel >::TViewModelPtr(), SWidget::AccessWidgetVisibilityAttribute(), FSlateCachedElementData::AddCachedElement(), UE::Sequencer::FDynamicExtensionContainer::AddDynamicExtension(), TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::DebugDump(), TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::DebugDump(), FMovieSceneBlendingAccumulator::FindActuator(), GetTypeHash(), SRigVMActionMenu::OnCreateWidgetForAction(), SListView< ItemType >::FWidgetGenerator::OnItemSeen(), operator!=(), operator!=(), operator!=(), operator!=(), FTransaction::operator<<, UE::Sequencer::TViewModelPtr< FViewModel >::operator=(), operator==(), operator==(), operator==(), operator==(), SListView< ItemType >::FWidgetGenerator::ProcessItemCleanUp(), and SListView< ItemType >::FWidgetGenerator::ValidateWidgetGeneration().
GetSharedReferenceCount()
template<class ObjectType, ESPMode InMode> FORCEINLINE int32 TSharedRef< ObjectType, InMode >::GetSharedReferenceCount () const inline nodiscard
Returns the number of shared references to this object (including this reference.) IMPORTANT: Not necessarily fast!
Should only be used for debugging purposes!
Returns
Number of shared references to the object (including this reference.)
Definition at line 510 of file SharedPointer.h.
Init()
template<class ObjectType, ESPMode InMode> template<class OtherType> void TSharedRef< ObjectType, InMode >::Init (OtherType * InObject) inline private
Definition at line 551 of file SharedPointer.h.
Referenced by FActorDragDropGraphEdOp::New(), FLevelDragDropOp::New(), and FLevelDragDropOp::New().
IsUnique()
template<class ObjectType, ESPMode InMode> FORCEINLINE bool TSharedRef< ObjectType, InMode >::IsUnique () const inline nodiscard
Returns true if this is the only shared reference to this object.
Note that there may be outstanding weak references left.
IMPORTANT: This has different behavior to GetSharedReferenceCount() == 1 in a multithreaded context. The expectation is that this will be used when a user wants exclusive write-access to an otherwise-immutable object. Care still needs to be taken when pinning TWeakPtrs to make new shared references.
Returns
True if there is only one shared reference to the object, and this is it!
Definition at line 526 of file SharedPointer.h.
IsValid()
template<class ObjectType, ESPMode InMode> FORCEINLINE bool TSharedRef< ObjectType, InMode >::IsValid () const inline nodiscard private
Checks to see if this shared reference is actually pointing to an object.
NOTE: This validity test is intentionally private because shared references must always be valid.
Returns
True if the shared reference is valid and can be dereferenced
Definition at line 602 of file SharedPointer.h.
Referenced by TSharedRef< INavigationToolItem >::TSharedRef(), TSharedRef< INavigationToolItem >::TSharedRef(), TSharedRef< INavigationToolItem >::Get(), FDocumentTabFactoryForObjects< BaseClass >::IsPayloadSupported(), FDocumentTabFactoryForObjects< BaseClass >::IsPayloadValid(), TSharedRef< INavigationToolItem >::operator*(), TSharedRef< INavigationToolItem >::operator->(), and TSharedRef< INavigationToolItem >::operator==().
operator*()
template<class ObjectType, ESPMode InMode> FORCEINLINE ObjectType & TSharedRef< ObjectType, InMode >::operator* () const inline nodiscard
Dereference operator returns a reference to the object this shared pointer points to.
Returns
Reference to the object
Definition at line 485 of file SharedPointer.h.
operator->()
template<class ObjectType, ESPMode InMode> FORCEINLINE ObjectType * TSharedRef< ObjectType, InMode >::operator-> () const inline nodiscard
Arrow operator returns a pointer to this shared reference's object.
Returns
Returns a pointer to the object referenced by this shared reference
Definition at line 497 of file SharedPointer.h.
operator=() [1/5]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedRef & TSharedRef< ObjectType, InMode >::operator= (SharedPointerInternals::TRawPtrProxy< OtherType > const & InRawPtrProxy) inline
Assignment operator replaces this shared reference with the specified shared reference.
The object currently referenced by this shared reference will no longer be referenced and will be deleted if there are no other referencers. Must not be nullptr.
Parameters
InRawPtrProxy Proxy object used to assign the object (see MakeShareable helper function)
Definition at line 392 of file SharedPointer.h.
operator=() [2/5]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedRef & TSharedRef< ObjectType, InMode >::operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > && InRawPtrProxy) inline
Assignment operator replaces this shared reference with the specified shared reference.
The object currently referenced by this shared reference will no longer be referenced and will be deleted if there are no other referencers. Must not be nullptr.
Parameters
InRawPtrProxy Proxy object used to assign the object (see MakeShareable helper function)
Definition at line 438 of file SharedPointer.h.
operator=() [3/5]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedRef & TSharedRef< ObjectType, InMode >::operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const & InRawPtrProxy) inline
Assignment operator replaces this shared reference with the specified shared reference.
The object currently referenced by this shared reference will no longer be referenced and will be deleted if there are no other referencers. Must not be nullptr.
Parameters
InRawPtrProxy Proxy object used to assign the object (see MakeShareable helper function)
Definition at line 415 of file SharedPointer.h.
operator=() [4/5]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedRef & TSharedRef< ObjectType, InMode >::operator= (TSharedRef< ObjectType, InMode > && InSharedRef) inline
Definition at line 374 of file SharedPointer.h.
operator=() [5/5]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedRef & TSharedRef< ObjectType, InMode >::operator= (TSharedRef< ObjectType, InMode > const & InSharedRef) inline
Assignment operator replaces this shared reference with the specified shared reference.
The object currently referenced by this shared reference will no longer be referenced and will be deleted if there are no other referencers.
Parameters
InSharedRef Shared reference to replace with
Definition at line 367 of file SharedPointer.h.
operator==()
template<class ObjectType, ESPMode InMode> bool TSharedRef< ObjectType, InMode >::operator== (FIntrusiveUnsetOptionalState) const inline
Definition at line 541 of file SharedPointer.h.
ToSharedPtr()
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr< ObjectType, Mode > TSharedRef< ObjectType, InMode >::ToSharedPtr () const inline nodiscard
Converts a shared reference to a shared pointer.
Returns
Shared pointer to the object
Definition at line 453 of file SharedPointer.h.
ToWeakPtr()
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr< ObjectType, Mode > TSharedRef< ObjectType, InMode >::ToWeakPtr () const inline nodiscard
Converts a shared reference to a weak ptr.
Returns
Weak pointer to the object
Definition at line 463 of file SharedPointer.h.
Friends And Related Symbol Documentation
TSharedRef
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TSharedRef friend
Definition at line 608 of file SharedPointer.h.
Referenced by TSharedRef< INavigationToolItem >::operator=(), TSharedRef< INavigationToolItem >::operator=(), and TSharedRef< INavigationToolItem >::operator=().
TSharedPtr
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TSharedPtr friend
Definition at line 611 of file SharedPointer.h.
Referenced by TSharedRef< INavigationToolItem >::ToSharedPtr().
TWeakPtr
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TWeakPtr friend
Definition at line 612 of file SharedPointer.h.
UE::Core::Private::MakeSharedRef
template<class ObjectType, ESPMode InMode> TSharedRef UE::Core::Private::MakeSharedRef (ObjectType * InObject, SharedPointerInternals::TReferenceControllerBase< Mode > * InSharedReferenceCount) friend
Field Documentation
bHasIntrusiveUnsetOptionalState
template<class ObjectType, ESPMode InMode> bool TSharedRef< ObjectType, InMode >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 534 of file SharedPointer.h.
Mode
template<class ObjectType, ESPMode InMode> ESPMode TSharedRef< ObjectType, InMode >::Mode = InMode static constexpr
Definition at line 157 of file SharedPointer.h.
Object
template<class ObjectType, ESPMode InMode> ObjectType* TSharedRef< ObjectType, InMode >::Object private
The object we're holding a reference to.
Can be nullptr.
Definition at line 617 of file SharedPointer.h.
Referenced by TWeakPtr< INavigationToolItem >::operator=().
SharedReferenceCount
template<class ObjectType, ESPMode InMode> SharedPointerInternals::FSharedReferencer< Mode > TSharedRef< ObjectType, InMode >::SharedReferenceCount private
Interface to the reference counter for this object.
Note that the actual reference controller object is shared by all shared and weak pointers that refer to the object
Definition at line 621 of file SharedPointer.h.
Referenced by TWeakPtr< INavigationToolItem >::operator=().
The documentation for this class was generated from the following file:
SharedPointer.h