Unreal Engine 5.6 C++ API: TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > Class Template Reference
TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > Class Template Reference
A TMapBase specialization that allows multiple values to be associated with each key.
#include "Map.h"
Public Types
using IntrusiveUnsetOptionalStateType = TMultiMap
typedef Super::KeyConstPointerType KeyConstPointerType
typedef Super::KeyInitType KeyInitType
typedef TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Super
typedef Super::ValueInitType ValueInitType
Public Types inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
typedef TPair< KeyType, ValueType > ElementType
typedef TTypeTraits< KeyType >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< KeyType >::ConstInitType KeyInitType
using TRangedForConstIterator = TBaseIterator<true, true>
using TRangedForIterator = TBaseIterator<false, true>
typedef TTypeTraits< ValueType >::ConstInitType ValueInitType
Public Member Functions
TMultiMap ()=default
TMultiMap (const TMultiMap &)=default
template<typename OtherSetAllocator>
TMultiMap (const TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TMultiMap (FIntrusiveUnsetOptionalState Tag)
TMultiMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Constructor which gets its elements from a native initializer list.
TMultiMap (TMultiMap &&)=default
template<typename OtherSetAllocator>
TMultiMap (TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
FORCEINLINE ValueType & AddUnique (const KeyType &InKey, const ValueType &InValue)
Add a key-value association to the map.
FORCEINLINE ValueType & AddUnique (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & AddUnique (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & AddUnique (KeyType &&InKey, ValueType &&InValue)
template<typename OtherSetAllocator>
void Append (const TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &OtherMultiMap)
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
template<typename OtherSetAllocator>
void Append (TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&OtherMultiMap)
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
template<typename InitKeyType, typename InitValueType>
ValueType & EmplaceUnique (InitKeyType &&InKey, InitValueType &&InValue)
Add a key-value association to the map.
ValueType * FindPair (KeyInitType Key, ValueInitType Value)
Find an association between a specified key and value.
FORCEINLINE const ValueType * FindPair (KeyInitType Key, ValueInitType Value) const
Find an association between a specified key and value.
template<typename Allocator>
void MultiFind (KeyInitType Key, TArray< ValueType, Allocator > &OutValues, bool bMaintainOrder=false) const
Finds all values associated with the specified key.
template<typename Allocator>
void MultiFindPointer (KeyInitType Key, TArray< const ValueType *, Allocator > &OutValues, bool bMaintainOrder=false) const
Finds all values associated with the specified key.
template<typename Allocator>
void MultiFindPointer (KeyInitType Key, TArray< ValueType *, Allocator > &OutValues, bool bMaintainOrder=false)
FORCEINLINE int32 Num () const
int32 Num (KeyInitType Key) const
Returns the number of values within this map associated with the specified key.
TMultiMap & operator= (const TMultiMap &)=default
template<typename OtherSetAllocator>
TMultiMap & operator= (const TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TMultiMap & operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Assignment operator which gets its elements from a native initializer list.
TMultiMap & operator= (TMultiMap &&)=default
template<typename OtherSetAllocator>
TMultiMap & operator= (TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
int32 Remove (KeyInitType InKey, ValueInitType InValue)
Remove associations between the specified key and value from the map.
int32 RemoveSingle (KeyInitType InKey, ValueInitType InValue)
Remove the first association between the specified key and value from the map.
Public Member Functions inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
template<typename PREDICATE_CLASS>
FORCEINLINE void KeySort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void KeyStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
void SortFreeList ()
Sort the free element list so that subsequent additions will occur in the lowest available TSet index resulting in tighter packing without moving any existing items.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueSort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
Public Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
FORCEINLINE ValueType & Add (const KeyType &InKey)
Set a default value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (const TTuple< KeyType, ValueType > &InKeyValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (KeyType &&InKey)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (TTuple< KeyType, ValueType > &&InKeyValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, const ValueType &InValue)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, ValueType &&InValue)
TArray< ElementType > Array () const
Copy the key/value pairs in this map into an array.
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TRangedForConstIterator begin () const
FORCEINLINE void Compact ()
Compacts the pair set to remove holes.
FORCEINLINE void CompactStable ()
Compacts the pair set to remove holes.
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Check if map contains the specified key.
template<typename ComparableKey>
FORCEINLINE bool ContainsByHash (uint32 KeyHash, const ComparableKey &Key) const
See Contains() and class documentation section on ByHash() functions.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
FORCEINLINE void CountBytes (FArchive &Ar) const
Track the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (typename TConstKeyIterator::KeyArgumentType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (typename TKeyIterator::KeyArgumentType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
template<typename InitKeyType = KeyType>
ValueType & Emplace (InitKeyType &&InKey)
Set a default value associated with a key.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
template<typename InitKeyType = KeyType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey)
See Emplace() and class documentation section on ByHash() functions.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey, InitValueType &&InValue)
See Emplace() and class documentation section on ByHash() functions.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map.
FORCEINLINE TRangedForIterator end ()
FORCEINLINE TRangedForConstIterator end () const
template<typename Predicate>
TMap< KeyType, ValueType, SetAllocator, KeyFuncs > FilterByPredicate (Predicate Pred) const
Filters the elements in the map based on a predicate functor.
FORCEINLINE ValueType * Find (KeyConstPointerType Key)
Find the value associated with a specified key.
FORCEINLINE const ValueType * Find (KeyConstPointerType Key) const
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
const ElementType * FindArbitraryElement () const
template<typename ComparableKey>
FORCEINLINE ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key)
See Find() and class documentation section on ByHash() functions.
template<typename ComparableKey>
FORCEINLINE const ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key) const
template<typename ComparableKey>
FORCEINLINE ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key)
template<typename ComparableKey>
FORCEINLINE const ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key) const
FORCEINLINE ValueType & FindChecked (KeyConstPointerType Key)
Find a reference to the value associated with a specified key.
FORCEINLINE const ValueType & FindChecked (KeyConstPointerType Key) const
Find a reference to the value associated with a specified key.
FORCEINLINE FSetElementId FindId (KeyInitType Key) const
Finds the index of the first element that is assigned to the specified key.
template<typename ComparableKey>
FORCEINLINE FSetElementId FindIdByHash (uint32 KeyHash, const ComparableKey &Key) const
See FindId() and class documentation section on ByHash() functions.
const KeyType * FindKey (ValueInitType Value) const
Find the key associated with the specified value.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, const ValueType &Value)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, const ValueType &Value)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType FindRef (KeyConstPointerType Key) const
Find the value associated with a specified key.
FORCEINLINE ValueType FindRef (KeyConstPointerType Key, ValueType DefaultValue) const
Find the value associated with a specified key.
template<typename Allocator>
void GenerateKeyArray (TArray< KeyType, Allocator > &OutArray) const
Generate an array from the keys in this map.
template<typename Allocator>
void GenerateValueArray (TArray< ValueType, Allocator > &OutArray) const
Generate an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container .
template<typename Allocator>
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Get the unique keys contained within this map.
template<typename InSetKeyFuncs, typename InSetAllocator>
int32 GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > &OutKeys) const
Get the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
bool OrderIndependentCompareEqual (const TMapBase &Other) const
Compare this map with another for equality.
FORCEINLINE void Remove (FSetElementId Id)
Removes the element at the specified index.
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
template<typename ComparableKey>
FORCEINLINE int32 RemoveByHash (uint32 KeyHash, const ComparableKey &Key)
See Remove() and class documentation section on ByHash() functions.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Additional Inherited Members
Static Public Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Protected Types inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
using IntrusiveUnsetOptionalStateType = TSortableMapBase
typedef TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Super
Protected Types inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
typedef TSet< ElementType, KeyFuncs, SetAllocator > ElementSetType
using IntrusiveUnsetOptionalStateType = TMapBase
Protected Member Functions inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
TSortableMapBase ()=default
TSortableMapBase (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TSortableMapBase (FIntrusiveUnsetOptionalState Tag)
TSortableMapBase (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Protected Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
TMapBase ()=default
TMapBase (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TMapBase (FIntrusiveUnsetOptionalState Tag)
TMapBase (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TMapBase & operator= (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase & operator= (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TMapBase & operator= (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase & operator= (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Protected Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
ElementSetType Pairs
A set of the key-value pairs in the map.
Static Protected Attributes inherited from TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Static Protected Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Detailed Description
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
class TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >
A TMapBase specialization that allows multiple values to be associated with each key.
Definition at line 1506 of file Map.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> using TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::IntrusiveUnsetOptionalStateType = TMultiMap
Definition at line 1550 of file Map.h.
KeyConstPointerType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef Super::KeyConstPointerType TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::KeyConstPointerType
Definition at line 1512 of file Map.h.
KeyInitType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef Super::KeyInitType TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::KeyInitType
Definition at line 1513 of file Map.h.
Super
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef TSortableMapBase<KeyType, ValueType, SetAllocator, KeyFuncs> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::Super
Definition at line 1511 of file Map.h.
ValueInitType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef Super::ValueInitType TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::ValueInitType
Definition at line 1514 of file Map.h.
Constructor & Destructor Documentation
TMultiMap() [1/7]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::TMultiMap () nodiscard default
TMultiMap() [2/7]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::TMultiMap (TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &&) nodiscard default
TMultiMap() [3/7]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::TMultiMap (const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &) nodiscard default
TMultiMap() [4/7]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::TMultiMap (TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline nodiscard
Constructor for moving elements from a TMap with a different SetAllocator.
Definition at line 1524 of file Map.h.
TMultiMap() [5/7]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::TMultiMap (const TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline nodiscard
Constructor for copying elements from a TMap with a different SetAllocator.
Definition at line 1531 of file Map.h.
TMultiMap() [6/7]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::TMultiMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList) inline nodiscard
Constructor which gets its elements from a native initializer list.
Definition at line 1537 of file Map.h.
TMultiMap() [7/7]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::TMultiMap (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 1552 of file Map.h.
Member Function Documentation
AddUnique() [1/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::AddUnique (const KeyType & InKey, const ValueType & InValue) inline
Add a key-value association to the map.
The association doesn't replace any of the key's existing associations. However, if both the key and value match an existing association in the map, no new association is made and the existing association's value is returned.
Parameters
InKey The key to associate.
InValue The value to associate.
Returns
A reference to the value as stored in the map; the reference is only valid until the next change to any key in the map.
Definition at line 1653 of file Map.h.
AddUnique() [2/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::AddUnique (const KeyType & InKey, ValueType && InValue) inline
Definition at line 1654 of file Map.h.
AddUnique() [3/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::AddUnique (KeyType && InKey, const ValueType & InValue) inline
Definition at line 1655 of file Map.h.
AddUnique() [4/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::AddUnique (KeyType && InKey, ValueType && InValue) inline
Definition at line 1656 of file Map.h.
Append() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> void TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::Append (const TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & OtherMultiMap) inline
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
Parameters
OtherMultiMap The other map of items to add.
Definition at line 1820 of file Map.h.
Append() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> void TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::Append (TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && OtherMultiMap) inline
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
Parameters
OtherMultiMap The other map of items to move the elements from.
Definition at line 1802 of file Map.h.
EmplaceUnique()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InitKeyType, typename InitValueType> ValueType & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::EmplaceUnique (InitKeyType && InKey, InitValueType && InValue) inline
Add a key-value association to the map.
The association doesn't replace any of the key's existing associations. However, if both key and value match an existing association in the map, no new association is made and the existing association's value is returned.
Parameters
InKey The key to associate.
InValue The value to associate.
Returns
A reference to the value as stored in the map; the reference is only valid until the next change to any key in the map.
Definition at line 1670 of file Map.h.
Referenced by TConstKeyIterator< FFixedObjectBindingID, FName >::AddUnique(), TConstKeyIterator< FFixedObjectBindingID, FName >::AddUnique(), TConstKeyIterator< FFixedObjectBindingID, FName >::AddUnique(), and TConstKeyIterator< FFixedObjectBindingID, FName >::AddUnique().
FindPair() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> ValueType * TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::FindPair (KeyInitType Key, ValueInitType Value) inline nodiscard
Find an association between a specified key and value.
Parameters
Key The key to find.
Value The value to find.
Returns
If the map contains a matching association, a pointer to the value in the map is returned. Otherwise nullptr is returned. The pointer is only valid as long as the map isn't changed.
Definition at line 1762 of file Map.h.
FindPair() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE const ValueType * TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::FindPair (KeyInitType Key, ValueInitType Value) const inline nodiscard
Find an association between a specified key and value.
(const)
Parameters
Key The key to find.
Value The value to find.
Returns
If the map contains a matching association, a pointer to the value in the map is returned. Otherwise nullptr is returned. The pointer is only valid as long as the map isn't changed.
Definition at line 1749 of file Map.h.
Referenced by TConstKeyIterator< FFixedObjectBindingID, FName >::EmplaceUnique(), and TConstKeyIterator< FFixedObjectBindingID, FName >::FindPair().
MultiFind()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename Allocator> void TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::MultiFind (KeyInitType Key, TArray< ValueType, Allocator > & OutValues, bool bMaintainOrder = false) const inline
Finds all values associated with the specified key.
Parameters
Key The key to find associated values for.
OutValues Upon return, contains the values associated with the key.
bMaintainOrder true if the Values array should be in the same order as the map's pairs.
Definition at line 1598 of file Map.h.
MultiFindPointer() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename Allocator> void TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::MultiFindPointer (KeyInitType Key, TArray< const ValueType *, Allocator > & OutValues, bool bMaintainOrder = false) const inline
Finds all values associated with the specified key.
Parameters
Key The key to find associated values for.
OutValues Upon return, contains pointers to the values associated with the key. Pointers are only valid until the next change to any key in the map.
bMaintainOrder true if the Values array should be in the same order as the map's pairs.
Definition at line 1619 of file Map.h.
MultiFindPointer() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename Allocator> void TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::MultiFindPointer (KeyInitType Key, TArray< ValueType *, Allocator > & OutValues, bool bMaintainOrder = false) inline
Definition at line 1631 of file Map.h.
Num() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE int32 TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::Num () const inline nodiscard
Definition at line 1790 of file Map.h.
Referenced by TConstKeyIterator< FFixedObjectBindingID, FName >::Append(), and TConstKeyIterator< FFixedObjectBindingID, FName >::Append().
Num() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> int32 TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::Num (KeyInitType Key) const inline nodiscard
Returns the number of values within this map associated with the specified key.
Definition at line 1778 of file Map.h.
Referenced by TConstKeyIterator< FFixedObjectBindingID, FName >::Append().
operator=() [1/5]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &) default
operator=() [2/5]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMultiMap & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (const TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline
Assignment operator for copying elements from a TMap with a different SetAllocator.
Definition at line 1574 of file Map.h.
operator=() [3/5]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList) inline
Assignment operator which gets its elements from a native initializer list.
Definition at line 1581 of file Map.h.
operator=() [4/5]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMultiMap & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &&) default
operator=() [5/5]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMultiMap & TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (TMultiMap< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline
Assignment operator for moving elements from a TMap with a different SetAllocator.
Definition at line 1566 of file Map.h.
operator==()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 1556 of file Map.h.
Remove() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE int32 TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::Remove (KeyConstPointerType InKey) inline
Remove all value associations for a key.
Parameters
InKey The key to remove associated values for.
Returns
The number of values that were associated with the key.
Definition at line 1687 of file Map.h.
Remove() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> int32 TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::Remove (KeyInitType InKey, ValueInitType InValue) inline
Remove associations between the specified key and value from the map.
Parameters
InKey The key part of the pair to remove.
InValue The value part of the pair to remove.
Returns
The number of associations removed.
Definition at line 1699 of file Map.h.
RemoveSingle()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> int32 TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::RemoveSingle (KeyInitType InKey, ValueInitType InValue) inline
Remove the first association between the specified key and value from the map.
Parameters
InKey The key part of the pair to remove.
InValue The value part of the pair to remove.
Returns
The number of associations removed.
Definition at line 1722 of file Map.h.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 1549 of file Map.h.
The documentation for this class was generated from the following file:
Map.h