Unreal Engine 5.6 C++ API: FMovieSceneAccumulatedBlendState Struct Reference
FMovieSceneAccumulatedBlendState Struct Reference
Blendable token state that's accumulated per-operand.
#include "MovieSceneAccumulatedBlendState.h"
Data Structures
struct FTokenEntry
Base entry that is used to temporarily store token data for later consolidation.
struct TTokenEntry
Templated entry that is used to temporarily store token data for later consolidation.
Public Member Functions
FMovieSceneAccumulatedBlendState ()=default
FMovieSceneAccumulatedBlendState (const FMovieSceneAccumulatedBlendState &)=delete
FMovieSceneAccumulatedBlendState (FMovieSceneAccumulatedBlendState &&)=default
template<typename DataType>
void Add (FMovieSceneBlendingActuatorID InActuatorType, TBlendableToken< DataType > &&InToken)
Add a new token to this accumulator to be applied using the specified actuator type.
MOVIESCENE_API void Consolidate (TMap< FMovieSceneBlendingKey, FActuatorTokenStackPtr > &InOutBlendState)
Consolidate all tokens currently accumulated into the specified container.
MOVIESCENE_API void Consolidate (TMap< FMovieSceneBlendingKey, FActuatorTokenStackPtr > &InOutBlendState, FMovieSceneEvaluationOperand InOperand, IMovieScenePlayer &Player)
Consolidate all tokens currently accumulated into the specified container by resolving the specified operand.
FMovieSceneAccumulatedBlendState & operator= (const FMovieSceneAccumulatedBlendState &)=delete
FMovieSceneAccumulatedBlendState & operator= (FMovieSceneAccumulatedBlendState &&)=default
void Reset ()
Reset this container.
Private Attributes
TArray< TInlineValue< FTokenEntry, 128 > > TokensToBlend
Array of all tokens that have been added this frame.
Detailed Description
Blendable token state that's accumulated per-operand.
Definition at line 51 of file MovieSceneAccumulatedBlendState.h.
Constructor & Destructor Documentation
FMovieSceneAccumulatedBlendState() [1/3]
FMovieSceneAccumulatedBlendState::FMovieSceneAccumulatedBlendState () default
Referenced by FMovieSceneAccumulatedBlendState(), FMovieSceneAccumulatedBlendState(), operator=(), and operator=().
FMovieSceneAccumulatedBlendState() [2/3]
FMovieSceneAccumulatedBlendState::FMovieSceneAccumulatedBlendState (const FMovieSceneAccumulatedBlendState &) delete
References FMovieSceneAccumulatedBlendState().
FMovieSceneAccumulatedBlendState() [3/3]
FMovieSceneAccumulatedBlendState::FMovieSceneAccumulatedBlendState (FMovieSceneAccumulatedBlendState &&) default
References FMovieSceneAccumulatedBlendState().
Member Function Documentation
Add()
template<typename DataType> void FMovieSceneAccumulatedBlendState::Add (FMovieSceneBlendingActuatorID InActuatorType, TBlendableToken< DataType > && InToken) inline
Add a new token to this accumulator to be applied using the specified actuator type.
Parameters
InScope The currently evaluating scope. Used to track which entities require pre-animated state restoration when the final blended token is applied
InActuatorType Unique identifier for the actuator that should be used to apply this token once blended with all other tokens of the same type and actuator
InToken The token to blend
Definition at line 70 of file MovieSceneAccumulatedBlendState.h.
References MoveTemp(), and TokensToBlend.
Consolidate() [1/2]
MOVIESCENE_API void FMovieSceneAccumulatedBlendState::Consolidate (TMap< FMovieSceneBlendingKey, FActuatorTokenStackPtr > & InOutBlendState)
Consolidate all tokens currently accumulated into the specified container.
Used for offline interrogation.
Parameters
InOutBlendState Map of token stacks to populate. One FActuatorTokenStackPtr per actuator type ID.
Consolidate() [2/2]
MOVIESCENE_API void FMovieSceneAccumulatedBlendState::Consolidate (TMap< FMovieSceneBlendingKey, FActuatorTokenStackPtr > & InOutBlendState, FMovieSceneEvaluationOperand InOperand, IMovieScenePlayer & Player)
Consolidate all tokens currently accumulated into the specified container by resolving the specified operand.
Used for runtime evaluation.
Parameters
InOutBlendState Map from object to a map of token stacks to populate. One FActuatorTokenStackPtr per actuator type ID.
InOperand The operand that is being animated
Player The movie scene player that is currently being animated
operator=() [1/2]
FMovieSceneAccumulatedBlendState & FMovieSceneAccumulatedBlendState::operator= (const FMovieSceneAccumulatedBlendState &) delete
References FMovieSceneAccumulatedBlendState().
operator=() [2/2]
FMovieSceneAccumulatedBlendState & FMovieSceneAccumulatedBlendState::operator= (FMovieSceneAccumulatedBlendState &&) default
References FMovieSceneAccumulatedBlendState().
Reset()
void FMovieSceneAccumulatedBlendState::Reset () inline
Reset this container.
Definition at line 94 of file MovieSceneAccumulatedBlendState.h.
References TokensToBlend.
Field Documentation
TokensToBlend
TArray<TInlineValue<FTokenEntry, 128> > FMovieSceneAccumulatedBlendState::TokensToBlend private
Array of all tokens that have been added this frame.
Definition at line 191 of file MovieSceneAccumulatedBlendState.h.
Referenced by Add(), and Reset().
The documentation for this struct was generated from the following file:
MovieSceneAccumulatedBlendState.h