Unreal Engine 5.6 C++ API: ObjectPtr_Private::Friend Struct Reference
ObjectPtr_Private::Friend Struct Reference
#include "ObjectPtr.h"
Static Public Member Functions
template<typename T>
static FORCEINLINE uint32 GetPtrTypeHash (const TObjectPtr< T > &InObjectPtr)
template<typename T>
static FORCEINLINE T * NoAccessTrackingGet (const TObjectPtr< T > &Ptr)
template<typename T>
static FORCEINLINE T * NoAccessTrackingGetNoResolve (const TObjectPtr< T > &Ptr)
template<typename T>
static FORCEINLINE FArchive & Serialize (FArchive &Ar, TObjectPtr< T > &InObjectPtr)
template<typename T>
static FORCEINLINE void SerializePtrStructured (FStructuredArchiveSlot Slot, TObjectPtr< T > &InObjectPtr)
Detailed Description
Definition at line 852 of file ObjectPtr.h.
Member Function Documentation
GetPtrTypeHash()
template<typename T> FORCEINLINE uint32 ObjectPtr_Private::Friend::GetPtrTypeHash (const TObjectPtr< T > & InObjectPtr) inline static
Definition at line 855 of file ObjectPtr.h.
References FORCEINLINE, GetTypeHash(), and TObjectPtr< T >::ObjectPtr.
Referenced by GetTypeHash().
NoAccessTrackingGet()
template<typename T> FORCEINLINE T * ObjectPtr_Private::Friend::NoAccessTrackingGet (const TObjectPtr< T > & Ptr) inline static
Definition at line 874 of file ObjectPtr.h.
References FORCEINLINE, FObjectPtr::GetHandleRef(), TObjectPtr< T >::ObjectPtr, and UE::CoreUObject::Private::ResolveObjectHandleNoRead().
Referenced by UClass::CheckDefaultObjectIsValidLowLevelFast(), and ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::Get().
NoAccessTrackingGetNoResolve()
template<typename T> FORCEINLINE T * ObjectPtr_Private::Friend::NoAccessTrackingGetNoResolve (const TObjectPtr< T > & Ptr) inline static
Definition at line 880 of file ObjectPtr.h.
References FORCEINLINE, FObjectPtr::GetHandleRef(), UE::CoreUObject::Private::NoResolveObjectHandleNoRead(), and TObjectPtr< T >::ObjectPtr.
Referenced by ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::GetNoResolve(), and UObjectBase::GetOuter().
Serialize()
template<typename T> FORCEINLINE FArchive & ObjectPtr_Private::Friend::Serialize (FArchive & Ar, TObjectPtr< T > & InObjectPtr) inline static
Definition at line 861 of file ObjectPtr.h.
References Ar, FORCEINLINE, and TObjectPtr< T >::ObjectPtr.
Referenced by operator<<().
SerializePtrStructured()
template<typename T> FORCEINLINE void ObjectPtr_Private::Friend::SerializePtrStructured (FStructuredArchiveSlot Slot, TObjectPtr< T > & InObjectPtr) inline static
Definition at line 868 of file ObjectPtr.h.
References FORCEINLINE, and TObjectPtr< T >::ObjectPtr.
Referenced by operator<<().
The documentation for this struct was generated from the following file:
ObjectPtr.h