Unreal Engine 5.6 C++ API: Nanite::FNaniteResourcesHelper Class Reference
Nanite::FNaniteResourcesHelper Class Reference
Helper class used to share implementation for different Component types.
#include "NaniteResourcesHelper.h"
Static Public Member Functions
template<class T>
static FMaterialAudit & AuditMaterials (const T *Component, FMaterialAudit &Audit, bool bSetMaterialUsage)
template<class T>
static bool HasValidNaniteData (const T &Component)
template<class T>
static bool ShouldCreateNaniteProxy (const T &Component, FMaterialAudit *OutNaniteMaterials)
template<class T>
static bool UseNaniteOverrideMaterials (const T &Component, bool bDoingMaterialAudit)
Detailed Description
Helper class used to share implementation for different Component types.
Definition at line 27 of file NaniteResourcesHelper.h.
Member Function Documentation
AuditMaterials()
template<class T> FMaterialAudit & Nanite::FNaniteResourcesHelper::AuditMaterials (const T * Component, FMaterialAudit & Audit, bool bSetMaterialUsage) static
Definition at line 171 of file NaniteResourcesHelper.h.
References Nanite::FMaterialAudit::AssetName, Nanite::FMaterialAudit::bCompatibleWithLumenCardSharing, Nanite::FMaterialAudit::bHasAnyError, Nanite::FMaterialAuditEntry::bHasAnyError, Nanite::FMaterialAuditEntry::bHasInvalidUsage, Nanite::FMaterialAudit::bHasMasked, Nanite::FMaterialAuditEntry::bHasNullMaterial, Nanite::FMaterialAuditEntry::bHasPerInstanceCustomData, Nanite::FMaterialAuditEntry::bHasPerInstanceRandomID, Nanite::FMaterialAuditEntry::bHasPixelDepthOffset, Nanite::FMaterialAudit::bHasSky, Nanite::FMaterialAuditEntry::bHasTessellationEnabled, Nanite::FMaterialAuditEntry::bHasUnsupportedBlendMode, Nanite::FMaterialAuditEntry::bHasUnsupportedShadingModel, Nanite::FMaterialAuditEntry::bHasVertexInterpolator, Nanite::FMaterialAuditEntry::bHasVertexUVs, Nanite::FMaterialAuditEntry::bHasWorldPositionOffset, check, Component, Nanite::FMaterialAudit::Entries, Nanite::FMaterialAudit::FallbackMaterial, IConsoleManager::FindTConsoleVariableDataInt(), IConsoleManager::Get(), GetBlendModeString(), Nanite::Private::GetMaterialMeshName(), Nanite::Private::GetMaterialSlotInfos(), GetShadingModelFieldString(), TConsoleVariableData< T >::GetValueOnAnyThread(), Nanite::Private::IsMaterialSkeletalMesh(), Nanite::IsSupportedBlendMode(), Nanite::IsSupportedShadingModel(), Nanite::FMaterialAuditEntry::LocalUVDensities, Nanite::FMaterialAuditEntry::Material, Material, Nanite::FMaterialAuditEntry::MaterialIndex, Nanite::FMaterialAuditEntry::MaterialSlotName, TArray< InElementType, InAllocatorType >::Num(), TEXT, UE_LOG, and Warning.
Referenced by ShouldCreateNaniteProxy().
HasValidNaniteData()
template<class T> bool Nanite::FNaniteResourcesHelper::HasValidNaniteData (const T & Component) static
Definition at line 157 of file NaniteResourcesHelper.h.
References Component, and Nanite::FResources::PageStreamingStates.
ShouldCreateNaniteProxy()
template<class T> bool Nanite::FNaniteResourcesHelper::ShouldCreateNaniteProxy (const T & Component, FMaterialAudit * OutNaniteMaterials) static
Definition at line 113 of file NaniteResourcesHelper.h.
References AuditMaterials(), Component, Nanite::IsMaskingAllowed(), Nanite::FMaterialAudit::IsValid(), MoveTemp(), ShaderPlatform, and UseNanite().
Referenced by FInstancedStaticMeshComponentHelper::CollectPSOPrecacheData(), FStaticMeshComponentHelper::CollectPSOPrecacheData(), and UseNaniteOverrideMaterials().
UseNaniteOverrideMaterials()
template<class T> bool Nanite::FNaniteResourcesHelper::UseNaniteOverrideMaterials (const T & Component, bool bDoingMaterialAudit) static
Definition at line 164 of file NaniteResourcesHelper.h.
References Component, Nanite::GEnableNaniteMaterialOverrides, and ShouldCreateNaniteProxy().
The documentation for this class was generated from the following file:
NaniteResourcesHelper.h