Unreal Engine 5.6 C++ API: ASceneCapture Class Reference
ASceneCapture Class Reference
#include "SceneCapture.h"
Public Member Functions
virtual void PostLoad () override
virtual void Serialize (FArchive &Ar) override
UE_DEPRECATED (4.22, "SceneCapture's mesh and frustum components should now be accessed through the SceneCaptureComponent instead of the Actor") class UStaticMeshComponent *GetMeshComp() const
Returns MeshComp subobject.
Private Member Functions
GENERATED_UCLASS_BODY() private UPROPERTY ()) TObjectPtr< class USceneComponent > SceneComponent
To display the 3d camera in the editor.
Detailed Description
Definition at line 16 of file SceneCapture.h.
Member Function Documentation
PostLoad()
virtual void ASceneCapture::PostLoad () override virtual
Reimplemented in APlanarReflection.
References PostLoad().
Referenced by PostLoad().
Serialize()
virtual void ASceneCapture::Serialize (FArchive & Ar) override virtual
References Ar, and Serialize().
Referenced by Serialize().
UE_DEPRECATED()
ASceneCapture::UE_DEPRECATED (4. 22, "SceneCapture's mesh and frustum components should now be accessed through the SceneCaptureComponent instead of the Actor") const inline
Returns MeshComp subobject.
Definition at line 34 of file SceneCapture.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_DEPRECATED().
Referenced by UE_DEPRECATED().
UPROPERTY()
GENERATED_UCLASS_BODY() private ASceneCapture::UPROPERTY () private
To display the 3d camera in the editor.
References Category, Components, and meta.
Referenced by APlanarReflection::UE_DEPRECATED().
The documentation for this class was generated from the following file:
SceneCapture.h