Unreal Engine 5.6 C++ API: Verse::FNativeTypeBase Class Reference
Verse::FNativeTypeBase Class Reference
#include "VVMNativeType.h"
Public Member Functions
FNativeTypeBase ()=delete
FNativeTypeBase (EDefaultConstructNativeType)
FNativeTypeBase (UClass *InType)
UClass * AsUEClassNullableUnsafeDoNotUse () const
bool IsEqualUnsafeDoNotUse (const FNativeTypeBase &Other) const
bool IsNullUnsafeDoNotUse () const
Protected Member Functions
UClass * AsUEClassChecked () const
bool IsTypeOf (UObject *Obj) const
Protected Attributes
TObjectPtr< UClass > Type
Friends
struct Verse::FNativeConverter
template<typename NativeType, typename>
struct Verse::TToVValue
Detailed Description
Definition at line 31 of file VVMNativeType.h.
Constructor & Destructor Documentation
FNativeTypeBase() [1/3]
Verse::FNativeTypeBase::FNativeTypeBase () delete
Referenced by IsEqualUnsafeDoNotUse().
FNativeTypeBase() [2/3]
Verse::FNativeTypeBase::FNativeTypeBase (EDefaultConstructNativeType) inline
Definition at line 35 of file VVMNativeType.h.
FNativeTypeBase() [3/3]
Verse::FNativeTypeBase::FNativeTypeBase (UClass * InType) inline
Definition at line 37 of file VVMNativeType.h.
References Type.
Member Function Documentation
AsUEClassChecked()
UClass * Verse::FNativeTypeBase::AsUEClassChecked () const inline protected
Definition at line 51 of file VVMNativeType.h.
References check, and Type.
Referenced by Verse::FNativeType::AsUEClassCheckedUnsafeDoNotUse(), and Verse::TNativeSubtype< T, FNativeCastableType >::CheckValid().
AsUEClassNullableUnsafeDoNotUse()
UClass * Verse::FNativeTypeBase::AsUEClassNullableUnsafeDoNotUse () const inline
Definition at line 44 of file VVMNativeType.h.
References Type.
IsEqualUnsafeDoNotUse()
bool Verse::FNativeTypeBase::IsEqualUnsafeDoNotUse (const FNativeTypeBase & Other) const inline
Definition at line 43 of file VVMNativeType.h.
References FNativeTypeBase(), Other, and Type.
IsNullUnsafeDoNotUse()
bool Verse::FNativeTypeBase::IsNullUnsafeDoNotUse () const inline
Definition at line 42 of file VVMNativeType.h.
References Type.
IsTypeOf()
bool Verse::FNativeTypeBase::IsTypeOf (UObject * Obj) const inline protected
Definition at line 57 of file VVMNativeType.h.
References UObjectBaseUtility::IsA(), and Type.
Referenced by Verse::FNativeType::IsTypeOfUnsafeDoNotUse().
Friends And Related Symbol Documentation
Verse::FNativeConverter
friend struct Verse::FNativeConverter friend
Definition at line 47 of file VVMNativeType.h.
Verse::TToVValue
template<typename NativeType, typename> friend struct Verse::TToVValue friend
Definition at line 49 of file VVMNativeType.h.
Field Documentation
Type
TObjectPtr<UClass> Verse::FNativeTypeBase::Type protected
Definition at line 63 of file VVMNativeType.h.
Referenced by FNativeTypeBase(), AsUEClassChecked(), AsUEClassNullableUnsafeDoNotUse(), IsEqualUnsafeDoNotUse(), IsNullUnsafeDoNotUse(), and IsTypeOf().
The documentation for this class was generated from the following file:
VVMNativeType.h