Unreal Engine 5.6 C++ API: FNoReply Class Reference
FNoReply Class Reference
A reply type for events that return a void reply.
#include "ReplyBase.h"
Public Member Functions
FNoReply ()
Public Member Functions inherited from TReplyBase< FNoReply >
TReplyBase (bool bIsHandled)
Public Member Functions inherited from FReplyBase
const TSharedPtr< SWidget > GetHandler () const
The widget that ultimately handled the event.
bool IsEventHandled () const
Static Public Member Functions
static FNoReply Unhandled ()
Additional Inherited Members
Protected Member Functions inherited from TReplyBase< FNoReply >
FNoReply & Me ()
FNoReply & SetHandler (const TSharedRef< SWidget > &InHandler)
Set the widget that handled the event; undefined if never handled.
Protected Member Functions inherited from FReplyBase
FReplyBase (bool InIsHandled)
A reply can be handled or unhandled.
Protected Attributes inherited from FReplyBase
bool bIsHandled
Has a widget handled an event.
TSharedPtr< SWidget > EventHandler
Widget that handled the event that generated this reply.
Detailed Description
A reply type for events that return a void reply.
e.g. OnMouseLeave()
Definition at line 66 of file ReplyBase.h.
Constructor & Destructor Documentation
FNoReply()
FNoReply::FNoReply () inline
Definition at line 70 of file ReplyBase.h.
References FNoReply(), and TReplyBase< FNoReply >::TReplyBase().
Referenced by FNoReply(), and Unhandled().
Member Function Documentation
Unhandled()
FNoReply FNoReply::Unhandled () inline static
Definition at line 69 of file ReplyBase.h.
References FNoReply().
The documentation for this class was generated from the following file:
ReplyBase.h