Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType > Class Template Reference
UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType > Class Template Reference
Forward declarations.
#include "DynamicVertexSkinWeightsAttribute.h"
Public Types
using FBoneWeight = UE::AnimationCore::FBoneWeight
using FBoneWeights = UE::AnimationCore::FBoneWeights
Public Member Functions
TDynamicVertexSkinWeightsAttribute ()=default
Create an empty overlay.
TDynamicVertexSkinWeightsAttribute (ParentType *ParentIn, bool bAutoInit=true)
Create an attribute for the given parent.
virtual ~TDynamicVertexSkinWeightsAttribute ()=default
virtual bool Append (const TDynamicAttributeBase< ParentType > &Source, const UE::Geometry::FDynamicMesh3::FAppendInfo &Info) override
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
virtual void AppendDefaulted (const UE::Geometry::FDynamicMesh3::FAppendInfo &Info) override
Add default-valued elements, using the AppendInfo to determine the range to add.
bool CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const override
Check validity of attribute.
void CompactCopy (const FCompactMaps &CompactMaps, const TDynamicVertexSkinWeightsAttribute< ParentType > &ToCopy)
void CompactInPlace (const FCompactMaps &CompactMaps) override
Compact the attribute in place.
void Copy (const TDynamicVertexSkinWeightsAttribute< ParentType > &Copy)
Set this overlay to contain the same arrays as the copy overlay.
bool CopyIn (int RawID, void *Buffer, int BufferSize) override
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
bool CopyOut (int RawID, void *Buffer, int BufferSize) const override
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
bool CopyThroughMapping (const TDynamicAttributeBase< ParentType > *Source, const FMeshIndexMappings &Mapping) override
Copy data from a different attribute to this one, using the mesh index mapping to determine the correspondence.
void CopyValue (int FromVertexID, int ToVertexID)
Copy the attribute value at FromVertexID to ToVertexID.
TSet< int32 > GetBoundBoneIndices () const
Returns a list of all unique bone indices that are used by this skin weight attribute.
virtual SIZE_T GetByteCount () const override
ParentType * GetParent ()
const ParentType * GetParent () const
template<typename AsType>
void GetValue (int VertexID, AsType &Data) const
Get the element at a given index.
void GetValue (int VertexID, FBoneWeights &Data) const
Get the element at a given index.
template<typename BoneIndexType, typename BoneFloatWeightType>
void GetValue (int VertexID, TArray< BoneIndexType > &OutBones, TArray< BoneFloatWeightType > &OutWeights) const
Get the element at a given index via a pair of bone index and weight arrays.
void Initialize (const FBoneWeights InitialValue={})
Initialize the attribute values to the given max vertex ID.
TDynamicAttributeBase< ParentType > * MakeCompactCopy (const FCompactMaps &CompactMaps, ParentType *ParentTypeIn) const override
Allocate a new compact copy of the attribute layer, optionally with a different parent.
TDynamicAttributeBase< ParentType > * MakeCopy (ParentType *ParentIn) const override
Allocate a new copy of the attribute layer, optionally with a different parent.
TDynamicAttributeBase< ParentType > * MakeNew (ParentType *ParentIn) const override
Allocate a new empty instance of the same type of attribute layer.
TUniquePtr< TDynamicAttributeChangeBase< ParentType > > NewBlankChange () const override
void OnCollapseEdge (const FDynamicMesh3::FEdgeCollapseInfo &CollapseInfo) override
Update the overlay to reflect an edge collapse in the parent.
void OnFlipEdge (const FDynamicMesh3::FEdgeFlipInfo &FlipInfo) override
Update the overlay to reflect an edge flip in the parent.
void OnMergeEdges (const FDynamicMesh3::FMergeEdgesInfo &MergeInfo) override
Update the overlay to reflect an edge merge in the parent.
void OnMergeVertices (const FDynamicMesh3::FMergeVerticesInfo &MergeInfo) override
Update the overlay to reflect a vertex merge in the parent.
void OnNewVertex (int VertexID, bool bInserted) override
void OnPokeTriangle (const FDynamicMesh3::FPokeTriangleInfo &PokeInfo) override
Update the overlay to reflect a face poke in the parent.
void OnSplitEdge (const FDynamicMesh3::FEdgeSplitInfo &SplitInfo) override
Update the overlay to reflect an edge split in the parent.
void OnSplitVertex (const FDynamicMesh3::FVertexSplitInfo &SplitInfo, const TArrayView< const int > &TrianglesToUpdate) override
Update the overlay to reflect a vertex split in the parent.
bool ReindexBoneIndicesToSkeleton (const TArray< FName > &FromRefSkeleton, const TArray< FName > &ToRefSkeleton)
Re-index bone indices of the skin weights from one reference skeleton (represented by an array of bone names) to another.
void ResizeAttribStoreIfNeeded (int VertexID)
void Serialize (FArchive &Ar, const FCompactMaps *CompactMaps, bool bUseCompression)
void SetNewValue (int32 InNewVertexID, const FBoneWeights InBoneWeights)
void SetValue (int VertexID, const FBoneWeights &Data)
Set the element at a given index.
template<typename BoneIndexType, typename BoneFloatWeightType>
void SetValue (int VertexID, const TArray< BoneIndexType > &InBones, const TArray< BoneFloatWeightType > &InWeights, int32 InNumEntries)
Set the element at a given index.
template<typename ContainerAdapter>
void SetValue (int VertexID, const UE::AnimationCore::TBoneWeights< ContainerAdapter > &Data)
Set the element at a given index.
Public Member Functions inherited from UE::Geometry::TDynamicAttributeBase< ParentType >
virtual ~TDynamicAttributeBase ()
FName GetName () const
Get optional identifier for this attribute set.
virtual void OnNewTriangle (int TriangleID, bool bInserted)
virtual void OnRemoveTriangle (int TriangleID)
virtual void OnRemoveVertex (int VertexID)
virtual void OnReverseTriOrientation (int TriangleID)
void Serialize (FArchive &Ar)
Serialize to and from an archive.
void SetName (FName NameIn)
Set optional identifier for this attribute set.
Protected Member Functions
void SetBoneWeightsFromBary (int SetAttribute, int AttributeA, int AttributeB, int AttributeC, const FVector3d &BaryCoords)
Set the value at an Attribute to be a barycentric interpolation of three other Attributes.
void SetBoneWeightsFromLerp (int SetAttribute, int AttributeA, int AttributeB, double Alpha)
Set the value at an Attribute to be a linear interpolation of two other Attributes.
Protected Member Functions inherited from UE::Geometry::TDynamicAttributeBase< ParentType >
virtual void CopyParentClassData (const TDynamicAttributeBase< ParentType > &Other)
Implementation of parent-class copy.
Protected Attributes
ParentType * Parent = nullptr
The parent object (e.g.
TDynamicVector< FBoneWeights > VertexBoneWeights
List of per-vertex bone weights values.
Protected Attributes inherited from UE::Geometry::TDynamicAttributeBase< ParentType >
FName Name = FName()
Optional FName identifier for this attribute set.
Private Member Functions
void Reparent (ParentType *NewParent) override
Update any held pointer to the parent.
Friends
class FDynamicMeshAttributeSet
Detailed Description
template<typename ParentType>
class UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >
Forward declarations.
TDynamicVertexAttribute provides per-vertex storage of bone weights (skin weights)
Definition at line 46 of file DynamicVertexSkinWeightsAttribute.h.
Member Typedef Documentation
FBoneWeight
template<typename ParentType> using UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::FBoneWeight = UE::AnimationCore::FBoneWeight
Definition at line 51 of file DynamicVertexSkinWeightsAttribute.h.
FBoneWeights
template<typename ParentType> using UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::FBoneWeights = UE::AnimationCore::FBoneWeights
Definition at line 50 of file DynamicVertexSkinWeightsAttribute.h.
Constructor & Destructor Documentation
TDynamicVertexSkinWeightsAttribute() [1/2]
template<typename ParentType> UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::TDynamicVertexSkinWeightsAttribute () default
Create an empty overlay.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::MakeCompactCopy(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::MakeCopy(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::MakeNew().
TDynamicVertexSkinWeightsAttribute() [2/2]
template<typename ParentType> UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::TDynamicVertexSkinWeightsAttribute (ParentType * ParentIn, bool bAutoInit = true) inline
Create an attribute for the given parent.
Definition at line 69 of file DynamicVertexSkinWeightsAttribute.h.
~TDynamicVertexSkinWeightsAttribute()
template<typename ParentType> virtual UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::~TDynamicVertexSkinWeightsAttribute () virtual default
Member Function Documentation
Append()
template<typename ParentType> virtual bool UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::Append (const TDynamicAttributeBase< ParentType > & Source, const UE::Geometry::FDynamicMesh3::FAppendInfo & AppendInfo) inline override virtual
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
Returns
true if the append succeeded, false otherwise (e.g. false if the data from the source attribute was not compatible and the CopyOut failed to copy across)
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 297 of file DynamicVertexSkinWeightsAttribute.h.
AppendDefaulted()
template<typename ParentType> virtual void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::AppendDefaulted (const UE::Geometry::FDynamicMesh3::FAppendInfo & AppendInfo) inline override virtual
Add default-valued elements, using the AppendInfo to determine the range to add.
Called when appending from a mesh that does not have this attribute.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 320 of file DynamicVertexSkinWeightsAttribute.h.
CheckValidity()
template<typename ParentType> bool UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const inline override virtual
Check validity of attribute.
Parameters
bAllowNonmanifold Accept non-manifold topology as valid. Note that this should almost always be true for attributes; non-manifold overlays are generally valid.
FailMode Desired behavior if mesh is found invalid
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 511 of file DynamicVertexSkinWeightsAttribute.h.
CompactCopy()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::CompactCopy (const FCompactMaps & CompactMaps, const TDynamicVertexSkinWeightsAttribute< ParentType > & ToCopy) inline
Definition at line 132 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::MakeCompactCopy().
CompactInPlace()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::CompactInPlace (const FCompactMaps & CompactMaps) inline override virtual
Compact the attribute in place.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 115 of file DynamicVertexSkinWeightsAttribute.h.
Copy()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::Copy (const TDynamicVertexSkinWeightsAttribute< ParentType > & Copy) inline
Set this overlay to contain the same arrays as the copy overlay.
Definition at line 101 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::MakeCopy().
CopyIn()
template<typename ParentType> bool UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::CopyIn (int RawID, void * Buffer, int BufferSize) inline override virtual
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 337 of file DynamicVertexSkinWeightsAttribute.h.
CopyOut()
template<typename ParentType> bool UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::CopyOut (int RawID, void * Buffer, int BufferSize) const inline override virtual
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 326 of file DynamicVertexSkinWeightsAttribute.h.
CopyThroughMapping()
template<typename ParentType> bool UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::CopyThroughMapping (const TDynamicAttributeBase< ParentType > * Source, const FMeshIndexMappings & Mapping) inline override virtual
Copy data from a different attribute to this one, using the mesh index mapping to determine the correspondence.
Parameters
Source copy attribute data from this source
Mapping the correspondence from Source's parent to this attribute's parent
Returns
true if the copy succeeded, false otherwise (e.g. false if the data from the source attribute was not compatible and the CopyOut failed to copy across)
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 280 of file DynamicVertexSkinWeightsAttribute.h.
CopyValue()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::CopyValue (int FromVertexID, int ToVertexID) inline
Copy the attribute value at FromVertexID to ToVertexID.
Definition at line 421 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactInPlace(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnSplitVertex().
GetBoundBoneIndices()
template<typename ParentType> TSet< int32 > UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetBoundBoneIndices () const inline
Returns a list of all unique bone indices that are used by this skin weight attribute.
Returns
A unique list of bone indices used by all bone weights across all vertices.
Definition at line 262 of file DynamicVertexSkinWeightsAttribute.h.
GetByteCount()
template<typename ParentType> virtual SIZE_T UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetByteCount () const inline override virtual
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 669 of file DynamicVertexSkinWeightsAttribute.h.
GetParent() [1/2]
template<typename ParentType> ParentType * UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetParent () inline
Returns
the parent for this attribute
Definition at line 83 of file DynamicVertexSkinWeightsAttribute.h.
GetParent() [2/2]
template<typename ParentType> const ParentType * UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetParent () const inline
Returns
the parent for this attribute
Definition at line 81 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::Apply().
GetValue() [1/3]
template<typename ParentType> template<typename AsType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetValue (int VertexID, AsType & Data) const inline
Get the element at a given index.
Definition at line 357 of file DynamicVertexSkinWeightsAttribute.h.
GetValue() [2/3]
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetValue (int VertexID, FBoneWeights & Data) const inline
Get the element at a given index.
Definition at line 350 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::GetValue(), UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::SaveInitialVertex(), and UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::StoreAllFinalVertices().
GetValue() [3/3]
template<typename ParentType> template<typename BoneIndexType, typename BoneFloatWeightType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetValue (int VertexID, TArray< BoneIndexType > & OutBones, TArray< BoneFloatWeightType > & OutWeights) const inline
Get the element at a given index via a pair of bone index and weight arrays.
The number of influences is equal to the array size.
Definition at line 367 of file DynamicVertexSkinWeightsAttribute.h.
Initialize()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::Initialize (const FBoneWeights InitialValue = {}) inline
Initialize the attribute values to the given max vertex ID.
Definition at line 150 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::MakeCompactCopy(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::MakeNew().
MakeCompactCopy()
template<typename ParentType> TDynamicAttributeBase< ParentType > * UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::MakeCompactCopy (const FCompactMaps & CompactMaps, ParentType * ParentIn) const inline override virtual
Allocate a new compact copy of the attribute layer, optionally with a different parent.
Default implementation does a full copy and then compacts it, usually derived class will want to override this with a more efficient direct compact copy implementation
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 107 of file DynamicVertexSkinWeightsAttribute.h.
MakeCopy()
template<typename ParentType> TDynamicAttributeBase< ParentType > * UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::MakeCopy (ParentType * ParentIn) const inline override virtual
Allocate a new copy of the attribute layer, optionally with a different parent.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 93 of file DynamicVertexSkinWeightsAttribute.h.
MakeNew()
template<typename ParentType> TDynamicAttributeBase< ParentType > * UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::MakeNew (ParentType * ParentIn) const inline override virtual
Allocate a new empty instance of the same type of attribute layer.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 87 of file DynamicVertexSkinWeightsAttribute.h.
NewBlankChange()
template<typename ParentType> TUniquePtr< TDynamicAttributeChangeBase< ParentType > > UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::NewBlankChange () const inline override virtual
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 500 of file DynamicVertexSkinWeightsAttribute.h.
OnCollapseEdge()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnCollapseEdge (const FDynamicMesh3::FEdgeCollapseInfo & CollapseInfo) inline override virtual
Update the overlay to reflect an edge collapse in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 443 of file DynamicVertexSkinWeightsAttribute.h.
OnFlipEdge()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnFlipEdge (const FDynamicMesh3::FEdgeFlipInfo & FlipInfo) inline override virtual
Update the overlay to reflect an edge flip in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 437 of file DynamicVertexSkinWeightsAttribute.h.
OnMergeEdges()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnMergeEdges (const FDynamicMesh3::FMergeEdgesInfo & MergeInfo) inline override virtual
Update the overlay to reflect an edge merge in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 475 of file DynamicVertexSkinWeightsAttribute.h.
OnMergeVertices()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnMergeVertices (const FDynamicMesh3::FMergeVerticesInfo & MergeInfo) inline override virtual
Update the overlay to reflect a vertex merge in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 489 of file DynamicVertexSkinWeightsAttribute.h.
OnNewVertex()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnNewVertex (int VertexID, bool bInserted) inline override virtual
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 461 of file DynamicVertexSkinWeightsAttribute.h.
OnPokeTriangle()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnPokeTriangle (const FDynamicMesh3::FPokeTriangleInfo & PokeInfo) inline override virtual
Update the overlay to reflect a face poke in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 467 of file DynamicVertexSkinWeightsAttribute.h.
OnSplitEdge()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnSplitEdge (const FDynamicMesh3::FEdgeSplitInfo & SplitInfo) inline override virtual
Update the overlay to reflect an edge split in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 430 of file DynamicVertexSkinWeightsAttribute.h.
OnSplitVertex()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::OnSplitVertex (const FDynamicMesh3::FVertexSplitInfo & SplitInfo, const TArrayView< const int > & TrianglesToUpdate) inline override virtual
Update the overlay to reflect a vertex split in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 495 of file DynamicVertexSkinWeightsAttribute.h.
ReindexBoneIndicesToSkeleton()
template<typename ParentType> bool UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::ReindexBoneIndicesToSkeleton (const TArray< FName > & FromRefSkeleton, const TArray< FName > & ToRefSkeleton) inline
Re-index bone indices of the skin weights from one reference skeleton (represented by an array of bone names) to another.
Parameters
FromRefSkeleton The reference skeleton that the current skin weights are indexed against.
ToRefSkeleton The new reference skeleton that should be used to reindex the weights.
Returns
true on success, false otherwise
Note
Reasons for failure are:
bone index of one of the bone weights is larger than the number of bones in FromRefSkeleton, meaning the weights most likely were not computed with respect to the FromRefSkeleton.
one of the bone weights references a bone in FromRefSkeleton that doesn't exist in ToRefSkeleton.
ToRefSkeleton contains duplicates.
FromRefSkeleton can contain bones that are not present in ToRefSkeleton as long as those bones are not referenced by any of the weights.
Definition at line 181 of file DynamicVertexSkinWeightsAttribute.h.
Reparent()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::Reparent (ParentType * NewParent) inline override private virtual
Update any held pointer to the parent.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 85 of file DynamicVertexSkinWeightsAttribute.h.
ResizeAttribStoreIfNeeded()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::ResizeAttribStoreIfNeeded (int VertexID) inline
Definition at line 448 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnNewVertex(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnPokeTriangle(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnSplitEdge().
Serialize()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::Serialize (FArchive & Ar, const FCompactMaps * CompactMaps, bool bUseCompression) inline
Definition at line 530 of file DynamicVertexSkinWeightsAttribute.h.
SetBoneWeightsFromBary()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::SetBoneWeightsFromBary (int SetAttribute, int AttributeA, int AttributeB, int AttributeC, const FVector3d & BaryCoords) inline protected
Set the value at an Attribute to be a barycentric interpolation of three other Attributes.
If one of the barycentric coordinates is nearly one (within UE_SMALL_NUMBER tolerance) then simply copy over the value of the corresponding Attribute.
Definition at line 689 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnPokeTriangle().
SetBoneWeightsFromLerp()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::SetBoneWeightsFromLerp (int SetAttribute, int AttributeA, int AttributeB, double Alpha) inline protected
Set the value at an Attribute to be a linear interpolation of two other Attributes.
Definition at line 679 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnCollapseEdge(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnMergeEdges(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnMergeVertices(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::OnSplitEdge().
SetNewValue()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::SetNewValue (int32 InNewVertexID, const FBoneWeights InBoneWeights) inline
Definition at line 157 of file DynamicVertexSkinWeightsAttribute.h.
SetValue() [1/3]
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::SetValue (int VertexID, const FBoneWeights & Data) inline
Set the element at a given index.
Definition at line 385 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Append(), UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::Apply(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactCopy(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CopyThroughMapping().
SetValue() [2/3]
template<typename ParentType> template<typename BoneIndexType, typename BoneFloatWeightType> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::SetValue (int VertexID, const TArray< BoneIndexType > & InBones, const TArray< BoneFloatWeightType > & InWeights, int32 InNumEntries) inline
Set the element at a given index.
Definition at line 399 of file DynamicVertexSkinWeightsAttribute.h.
SetValue() [3/3]
template<typename ParentType> template<typename ContainerAdapter> void UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::SetValue (int VertexID, const UE::AnimationCore::TBoneWeights< ContainerAdapter > & Data) inline
Set the element at a given index.
Definition at line 392 of file DynamicVertexSkinWeightsAttribute.h.
Friends And Related Symbol Documentation
FDynamicMeshAttributeSet
template<typename ParentType> friend class FDynamicMeshAttributeSet friend
Definition at line 54 of file DynamicVertexSkinWeightsAttribute.h.
Field Documentation
Parent
template<typename ParentType> ParentType* UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::Parent = nullptr protected
The parent object (e.g.
mesh, point set) this attribute belongs to
Definition at line 57 of file DynamicVertexSkinWeightsAttribute.h.
VertexBoneWeights
template<typename ParentType> TDynamicVector<FBoneWeights> UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::VertexBoneWeights protected
List of per-vertex bone weights values.
Definition at line 61 of file DynamicVertexSkinWeightsAttribute.h.
The documentation for this class was generated from the following files:
SmoothBoneWeights.h
DynamicVertexSkinWeightsAttribute.h