Unreal Engine 5.6 C++ API: StringConv Namespace Reference
StringConv Namespace Reference
Functions
FORCEINLINE void DecodeSurrogate (const uint32 Codepoint, uint16 &OutHighSurrogate, uint16 &OutLowSurrogate)
FORCEINLINE uint32 EncodeSurrogate (const uint16 HighSurrogate, const uint16 LowSurrogate)
template<typename ConverterType>
FUnused GetLegacyFromType (...)
template<typename ConverterType>
ConverterType::LegacyFromType GetLegacyFromType (typename ConverterType::LegacyFromType *)
void InlineCombineSurrogates (FString &Str)
Inline combine any UTF-16 surrogate pairs in the given string.
template<typename AllocatorType>
FORCEINLINE void InlineCombineSurrogates_Array (TArray< TCHAR, AllocatorType > &StrBuffer)
Inline combine any UTF-16 surrogate pairs in the given null-terminated TCHAR array.
template<typename CharType>
FORCEINLINE int32 InlineCombineSurrogates_Buffer (CharType *StrBuffer, int32 StrLen)
Inline combine any UTF-16 surrogate pairs in the given null-terminated character buffer, returning the updated length.
FORCEINLINE bool IsEncodedSurrogate (const uint32 Codepoint)
Is the provided Codepoint outside of the range of the basic multilingual plane, but within the valid range of UTF8/16?
FORCEINLINE bool IsHighSurrogate (const uint32 Codepoint)
Is the provided Codepoint within the range of the high-surrogates?
FORCEINLINE bool IsLowSurrogate (const uint32 Codepoint)
Is the provided Codepoint within the range of the low-surrogates?
FORCEINLINE bool IsValidCodepoint (const uint32 Codepoint)
Is the provided Codepoint within the range of valid codepoints?
Function Documentation
DecodeSurrogate()
FORCEINLINE void StringConv::DecodeSurrogate (const uint32 Codepoint, uint16 & OutHighSurrogate, uint16 & OutLowSurrogate)
Definition at line 80 of file StringConv.h.
References FORCEINLINE, HIGH_SURROGATE_START_CODEPOINT, and LOW_SURROGATE_START_CODEPOINT.
Referenced by TUTF32ToUTF16_Convert< InFromType, InToType >::Utf16FromCodepoint().
EncodeSurrogate()
FORCEINLINE uint32 StringConv::EncodeSurrogate (const uint16 HighSurrogate, const uint16 LowSurrogate) nodiscard
Definition at line 75 of file StringConv.h.
References FORCEINLINE, HIGH_SURROGATE_START_CODEPOINT, and LOW_SURROGATE_START_CODEPOINT.
Referenced by TUTF16ToUTF32_Convert< InFromType, InToType >::CodepointFromUtf16(), and InlineCombineSurrogates_Buffer().
GetLegacyFromType() [1/2]
template<typename ConverterType> FUnused StringConv::GetLegacyFromType (...)
GetLegacyFromType() [2/2]
template<typename ConverterType> ConverterType::LegacyFromType StringConv::GetLegacyFromType (typename ConverterType::LegacyFromType *)
InlineCombineSurrogates()
void StringConv::InlineCombineSurrogates (FString & Str)
Inline combine any UTF-16 surrogate pairs in the given string.
InlineCombineSurrogates_Array()
template<typename AllocatorType> FORCEINLINE void StringConv::InlineCombineSurrogates_Array (TArray< TCHAR, AllocatorType > & StrBuffer)
Inline combine any UTF-16 surrogate pairs in the given null-terminated TCHAR array.
Definition at line 154 of file StringConv.h.
References FORCEINLINE, TArray< InElementType, InAllocatorType >::GetData(), InlineCombineSurrogates_Buffer(), No, TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::SetNum().
InlineCombineSurrogates_Buffer()
template<typename CharType> FORCEINLINE int32 StringConv::InlineCombineSurrogates_Buffer (CharType * StrBuffer, int32 StrLen)
Inline combine any UTF-16 surrogate pairs in the given null-terminated character buffer, returning the updated length.
Definition at line 95 of file StringConv.h.
References EncodeSurrogate(), FORCEINLINE, IsHighSurrogate(), IsLowSurrogate(), FMemory::Memmove(), and UNICODE_BOGUS_CHAR_CODEPOINT.
Referenced by InlineCombineSurrogates_Array().
IsEncodedSurrogate()
FORCEINLINE bool StringConv::IsEncodedSurrogate (const uint32 Codepoint) nodiscard
Is the provided Codepoint outside of the range of the basic multilingual plane, but within the valid range of UTF8/16?
Definition at line 88 of file StringConv.h.
References ENCODED_SURROGATE_END_CODEPOINT, ENCODED_SURROGATE_START_CODEPOINT, and FORCEINLINE.
Referenced by TUTF32ToUTF16_Convert< InFromType, InToType >::Utf16FromCodepoint().
IsHighSurrogate()
FORCEINLINE bool StringConv::IsHighSurrogate (const uint32 Codepoint) nodiscard
Is the provided Codepoint within the range of the high-surrogates?
Definition at line 64 of file StringConv.h.
References FORCEINLINE, HIGH_SURROGATE_END_CODEPOINT, and HIGH_SURROGATE_START_CODEPOINT.
Referenced by TUTF16ToUTF32_Convert< InFromType, InToType >::CodepointFromUtf16(), InlineCombineSurrogates_Buffer(), TUTF32ToUTF16_Convert< InFromType, InToType >::Utf16FromCodepoint(), and UE::Core::Private::FTCHARToUTF8_Convert::Utf8FromCodepoint().
IsLowSurrogate()
FORCEINLINE bool StringConv::IsLowSurrogate (const uint32 Codepoint) nodiscard
Is the provided Codepoint within the range of the low-surrogates?
Definition at line 70 of file StringConv.h.
References FORCEINLINE, LOW_SURROGATE_END_CODEPOINT, and LOW_SURROGATE_START_CODEPOINT.
Referenced by TUTF16ToUTF32_Convert< InFromType, InToType >::CodepointFromUtf16(), InlineCombineSurrogates_Buffer(), TUTF32ToUTF16_Convert< InFromType, InToType >::Utf16FromCodepoint(), and UE::Core::Private::FTCHARToUTF8_Convert::Utf8FromCodepoint().
IsValidCodepoint()
FORCEINLINE bool StringConv::IsValidCodepoint (const uint32 Codepoint) nodiscard
Is the provided Codepoint within the range of valid codepoints?
Definition at line 53 of file StringConv.h.
References FORCEINLINE.
Referenced by TUTF32ToUTF16_Convert< InFromType, InToType >::Utf16FromCodepoint(), and UE::Core::Private::FTCHARToUTF8_Convert::Utf8FromCodepoint().