Unreal Engine 5.6 C++ API: UE::Core::Private::FCountingOutputIterator Struct Reference
UE::Core::Private::FCountingOutputIterator Struct Reference
This is a basic object which counts how many times it has been incremented.
#include "StringConv.h"
Public Member Functions
FCountingOutputIterator ()
int32 GetCount () const
const FCountingOutputIterator & operator* () const
const FCountingOutputIterator & operator++ ()
const FCountingOutputIterator & operator++ (int)
const FCountingOutputIterator & operator+= (const int32 Amount)
template<typename T>
T operator= (T Val) const
Private Attributes
int32 Counter
Friends
int32 operator- (FCountingOutputIterator Lhs, FCountingOutputIterator Rhs)
Detailed Description
This is a basic object which counts how many times it has been incremented.
Definition at line 177 of file StringConv.h.
Constructor & Destructor Documentation
FCountingOutputIterator()
UE::Core::Private::FCountingOutputIterator::FCountingOutputIterator () inline nodiscard
Definition at line 179 of file StringConv.h.
References Counter.
Referenced by operator*(), operator++(), operator++(), operator+=(), and operator-.
Member Function Documentation
GetCount()
int32 UE::Core::Private::FCountingOutputIterator::GetCount () const inline nodiscard
Definition at line 216 of file StringConv.h.
References Counter.
Referenced by TUTF16ToUTF32_Convert< InFromType, InToType >::ConvertedLength(), and TUTF32ToUTF16_Convert< InFromType, InToType >::ConvertedLength().
operator*()
const FCountingOutputIterator & UE::Core::Private::FCountingOutputIterator::operator* () const inline nodiscard
Definition at line 184 of file StringConv.h.
References FCountingOutputIterator().
operator++() [1/2]
const FCountingOutputIterator & UE::Core::Private::FCountingOutputIterator::operator++ () inline
Definition at line 189 of file StringConv.h.
References FCountingOutputIterator(), and Counter.
operator++() [2/2]
const FCountingOutputIterator & UE::Core::Private::FCountingOutputIterator::operator++ (int) inline
Definition at line 194 of file StringConv.h.
References FCountingOutputIterator(), and Counter.
operator+=()
const FCountingOutputIterator & UE::Core::Private::FCountingOutputIterator::operator+= (const int32 Amount) inline
Definition at line 199 of file StringConv.h.
References FCountingOutputIterator(), and Counter.
operator=()
template<typename T> T UE::Core::Private::FCountingOutputIterator::operator= (T Val) const inline
Definition at line 206 of file StringConv.h.
Friends And Related Symbol Documentation
operator-
int32 operator- (FCountingOutputIterator Lhs, FCountingOutputIterator Rhs) friend
Definition at line 211 of file StringConv.h.
References FCountingOutputIterator(), and Counter.
Field Documentation
Counter
int32 UE::Core::Private::FCountingOutputIterator::Counter private
Definition at line 222 of file StringConv.h.
Referenced by FCountingOutputIterator(), GetCount(), operator++(), operator++(), operator+=(), and operator-.
The documentation for this struct was generated from the following file:
StringConv.h