Unreal Engine 5.6 C++ API: RenderUtils.h File Reference
RenderUtils.h File Reference
#include "CoreMinimal.h"
#include "RHIFwd.h"
#include "RHIShaderPlatform.h"
#include "RHIFeatureLevel.h"
#include "ReadOnlyCVARCache.h"
Data Structures
struct FPackedPosition
A 3x1 of xyz(11:11:10) format.
Namespaces
namespace Substrate
Macros
#define NUM_CUBE_VERTICES 36
#define NUM_DEBUG_UTIL_COLORS (32)
Enumerations
enum EConstructTextureFlags : uint32 {
CTF_Compress = 0x01 , CTF_DeferCompression = 0x02 , CTF_SRGB = 0x04 , CTF_AllowMips = 0x08 ,
CTF_ForceOneBitAlpha = 0x10 , CTF_RemapAlphaAsMasked = 0x20 , CTF_ForceOpaque = 0x40 , CTF_SkipPostEdit = 0x80 ,
CTF_Default = CTF_Compress | CTF_SRGB
}
Flags that control ConstructTexture(2D/2DArray/Volume/etc.)
Functions
RENDERCORE_API bool AllowPerPixelShadingModels (const FStaticShaderPlatform Platform)
RENDERCORE_API bool AllowPixelDepthOffset (const FStaticShaderPlatform Platform)
RENDERCORE_API bool AllowTranslucencyPerObjectShadows (const FStaticShaderPlatform Platform)
Read-only switch to check if translucency per object shadows are enabled.
RENDERCORE_API bool AreMobileScreenSpaceReflectionsEnabled (const FStaticShaderPlatform Platform)
RENDERCORE_API bool AreNaniteFallbackMeshesEnabledForPlatform (const FStaticShaderPlatform Platform)
Returns true if Nanite Fallback Meshes are enabled for the given shader platform.
RENDERCORE_API bool AreSkinCacheShadersEnabled (EShaderPlatform Platform)
Checks if skin cache shaders are enabled for the platform (via r.SkinCache.CompileShaders)
RENDERCORE_API FIntPoint CalcMipMapExtent (uint32 TextureSizeX, uint32 TextureSizeY, EPixelFormat Format, uint32 MipIndex)
Calculates the extent of a mip.
RENDERCORE_API void CalcMipMapExtent3D (uint32 TextureSizeX, uint32 TextureSizeY, uint32 TextureSizeZ, EPixelFormat Format, uint32 MipIndex, uint32 &OutXExtent, uint32 &OutYExtent, uint32 &OutZExtent)
Calculates the extent of a mip.
RENDERCORE_API SIZE_T CalcTextureMipMapSize (uint32 TextureSizeX, uint32 TextureSizeY, EPixelFormat Format, uint32 MipIndex)
Calculates the amount of memory used for a single mip-map of a texture.
RENDERCORE_API SIZE_T CalcTextureMipMapSize3D (uint32 TextureSizeX, uint32 TextureSizeY, uint32 TextureSizeZ, EPixelFormat Format, uint32 MipIndex)
Calculates the amount of memory used for a single mip-map of a texture 3D.
RENDERCORE_API SIZE_T CalcTextureSize (uint32 SizeX, uint32 SizeY, EPixelFormat Format, uint32 MipCount)
Calculates the amount of memory used for a texture.
RENDERCORE_API SIZE_T CalcTextureSize3D (uint32 SizeX, uint32 SizeY, uint32 SizeZ, EPixelFormat Format, uint32 MipCount)
Calculates the amount of memory used for a texture.
FVector CalculateGridZParams (float NearPlane, float FarPlane, float DepthDistributionScale, int32 GridSizeZ)
RENDERCORE_API void CopyTextureData2D (const void *Source, void *Dest, uint32 SizeY, EPixelFormat Format, uint32 SourceStride, uint32 DestStride)
Copies the data for a 2D texture between two buffers with potentially different strides.
RENDERCORE_API bool DoesPlatformSupportHeterogeneousVolumes (EShaderPlatform Platform)
Returns true if Heterogeneous Volumes should be used for the given shader platform.
RENDERCORE_API bool DoesPlatformSupportLumenGI (EShaderPlatform Platform, bool bSkipProjectCheck=false)
RENDERCORE_API bool DoesPlatformSupportNanite (EShaderPlatform Platform, bool bCheckForProjectSetting=true)
RENDERCORE_API bool DoesPlatformSupportNonNaniteVirtualShadowMaps (EShaderPlatform ShaderPlatform)
Returns true if non-Nanite virtual shadow maps are enabled by CVar r.Shadow.Virtual.NonNaniteVSM and the runtime supports Nanite/virtual shadow maps.
RENDERCORE_API bool DoesPlatformSupportSparseVolumeTextures (EShaderPlatform Platform)
Returns true if SparseVolumeTextures are supported on the given shader platform.
RENDERCORE_API bool DoesPlatformSupportVirtualShadowMaps (EShaderPlatform Platform)
Returns true if Virtual Shadow Mapsare supported for the given shader platform.
RENDERCORE_API bool DoesProjectSupportExpFogMatchesVolumetricFog ()
RENDERCORE_API bool DoesProjectSupportLumenGI (EShaderPlatform Platform)
RENDERCORE_API bool DoesProjectSupportLumenRayTracedTranslucentRefraction ()
RENDERCORE_API bool DoesRuntimeSupportHeterogeneousVolumes (EShaderPlatform Platform)
RENDERCORE_API bool DoesRuntimeSupportNanite (EShaderPlatform ShaderPlatform, bool bCheckForAtomicSupport, bool bCheckForProjectSetting)
RENDERCORE_API bool DoesRuntimeSupportOnePassPointLightShadows (EShaderPlatform Platform)
RENDERCORE_API bool DoesTargetPlatformSupportNanite (const ITargetPlatform *TargetPlatform)
FORCEINLINE float EV100ToLog2 (float LuminanceMax, float EV100)
FORCEINLINE float EV100ToLuminance (float EV100)
FORCEINLINE float EV100ToLuminance (float LuminanceMax, float EV100)
RENDERCORE_API bool ExcludeNonPipelinedShaderTypes (EShaderPlatform ShaderPlatform)
Checks if the non-pipeline shaders will not be compild and ones from FShaderPipeline used instead.
RENDERCORE_API bool ForceSimpleSkyDiffuse (const FStaticShaderPlatform Platform)
RENDERCORE_API bool ForwardShadingForcesSkyLightCubemapBlending (const FStaticShaderPlatform Platform)
Return true if all forward shaded material should blend the interpolated sky boxes for higher quality.
RENDERCORE_API uint32 Substrate::GetBytePerPixel ()
RENDERCORE_API uint32 Substrate::GetBytePerPixel (EShaderPlatform InPlatform)
RENDERCORE_API uint32 Substrate::GetClosurePerPixel (EShaderPlatform InPlatform)
RENDERCORE_API ECubeFace GetCubeFaceFromName (const FString &Name)
Convert from text string to ECubeFace.
RENDERCORE_API const TCHAR * GetCubeFaceName (ECubeFace Face)
Convert from ECubeFace to text string.
uint16 GetCubeVertexIndex (uint32 X, uint32 Y, uint32 Z)
Maps from an X,Y,Z cube vertex coordinate to the corresponding vertex index.
RENDERCORE_API uint32 GetHairStrandsLODMode ()
RENDERCORE_API bool GetHairStrandsUsesTriangleStrips ()
RENDERCORE_API int32 GetLightFunctionAtlasFormat ()
RENDERCORE_API uint32 Substrate::GetNormalQuality ()
RENDERCORE_API EPixelFormatChannelFlags GetPixelFormatValidChannels (EPixelFormat InPixelFormat)
Returns the valid channels for this pixel format.
RENDERCORE_API uint32 GetPlatformShadingModelsMask (const FStaticShaderPlatform Platform)
RENDERCORE_API uint32 Substrate::GetRayTracingMaterialPayloadSizeInBytes (bool bFullySimplifiedMaterial)
RENDERCORE_API ERayTracingMode GetRayTracingMode ()
RENDERCORE_API uint32 Substrate::GetShadingQuality ()
RENDERCORE_API uint32 Substrate::GetShadingQuality (EShaderPlatform InPlatform)
RENDERCORE_API uint32 Substrate::GetSheenQuality ()
RENDERCORE_API uint32 Substrate::GetSheenQuality (EShaderPlatform InPlatform)
RENDERCORE_API bool GetSingleLayerWaterUsesLightFunctionAtlas ()
RENDERCORE_API bool GetTranslucentUsesLightFunctionAtlas ()
RENDERCORE_API bool GetTranslucentUsesLightIESProfiles ()
RENDERCORE_API bool GetTranslucentUsesLightRectLights ()
RENDERCORE_API bool GetTranslucentUsesShadowedLocalLights ()
RENDERCORE_API FBufferRHIRef & GetUnitCubeAABBVertexBuffer ()
Unit cube AABB vertex buffer (useful to create procedural raytracing geometry)
RENDERCORE_API FBufferRHIRef & GetUnitCubeIndexBuffer ()
Unit cube index buffer.
RENDERCORE_API FBufferRHIRef & GetUnitCubeVertexBuffer ()
Unit cube vertex buffer (VertexDeclarationFVector4)
RENDERCORE_API FVertexDeclarationRHIRef & GetVertexDeclarationFVector2 ()
RENDERCORE_API FVertexDeclarationRHIRef & GetVertexDeclarationFVector3 ()
RENDERCORE_API FVertexDeclarationRHIRef & GetVertexDeclarationFVector4 ()
RENDERCORE_API float Substrate::GlintLevelBias ()
RENDERCORE_API float Substrate::GlintLevelMin ()
RENDERCORE_API uint32 Substrate::GlintLUTIndex ()
RENDERCORE_API bool HardwareVariableRateShadingSupportedByPlatform (EShaderPlatform ShaderPlatform)
RENDERCORE_API bool HasFirstPersonGBufferBit (EShaderPlatform ShaderPlatform)
RENDERCORE_API bool Substrate::IsAdvancedVisualizationEnabled ()
RENDERCORE_API bool Substrate::IsBackCompatibilityEnabled ()
RENDERCORE_API bool Substrate::IsDBufferPassEnabled (EShaderPlatform InPlatform)
RENDERCORE_API bool IsForwardShadingEnabled (const FStaticShaderPlatform Platform)
Returns if ForwardShading is enabled.
RENDERCORE_API bool Substrate::IsGlintEnabled ()
RENDERCORE_API bool Substrate::IsGlintEnabled (EShaderPlatform InPlatform)
RENDERCORE_API bool IsGPUSkinCacheAllowed (EShaderPlatform Platform)
Checks if skin cache shaders are allowed for the platform (via r.SkinCache.Allow)
RENDERCORE_API bool IsGPUSkinCacheAvailable (EShaderPlatform Platform)
Can the skin cache be used (ie shaders added, etc)
RENDERCORE_API bool IsGPUSkinPassThroughSupported (EShaderPlatform Platform)
Does the platform support GPUSkinPassthrough permutations.
RENDERCORE_API bool Substrate::IsHiddenMaterialAssetConversionEnabled ()
RENDERCORE_API bool Substrate::IsMaterialLayeringSupportEnabled ()
RENDERCORE_API bool IsMobileAmbientOcclusionEnabled (const FStaticShaderPlatform Platform)
RENDERCORE_API bool IsMobileCapsuleDirectShadowsEnabled (const FStaticShaderPlatform Platform)
RENDERCORE_API bool IsMobileCapsuleShadowsEnabled (const FStaticShaderPlatform Platform)
bool IsMobileDeferredShadingEnabled (const FStaticShaderPlatform Platform)
RENDERCORE_API bool IsMobileDistanceFieldAOEnabled (const FStaticShaderPlatform Platform)
Returns if Mobile Distance Field AO Enabled.
RENDERCORE_API bool IsMobileDistanceFieldEnabled (const FStaticShaderPlatform Platform)
bool IsMobileHDR ()
True if HDR is enabled for the mobile renderer.
RENDERCORE_API bool IsMobileMovableSpotlightShadowsEnabled (const FStaticShaderPlatform Platform)
RENDERCORE_API bool Substrate::IsOpaqueRoughRefractionEnabled (EShaderPlatform InPlatform)
RENDERCORE_API bool IsRayTracingAllowed ()
RENDERCORE_API bool IsRayTracingEnabled ()
RENDERCORE_API bool IsRayTracingEnabled (EShaderPlatform ShaderPlatform)
RENDERCORE_API bool IsRayTracingEnabledForProject (EShaderPlatform ShaderPlatform)
RENDERCORE_API bool IsRayTracingEnableOnDemandSupported ()
RENDERCORE_API bool IsRayTracingUsingReferenceBasedResidency ()
RENDERCORE_API bool Substrate::IsRoughDiffuseEnabled ()
RENDERCORE_API bool IsSingleLayerWaterDepthPrepassEnabled (const FStaticShaderPlatform Platform, FStaticFeatureLevel FeatureLevel)
(Non-runtime) Checks if the depth prepass for single layer water is enabled.
RENDERCORE_API bool Substrate::IsSpecularProfileEnabled ()
RENDERCORE_API bool Substrate::IsSpecularProfileEnabled (EShaderPlatform InPlatform)
bool IsStaticLightingAllowed ()
RENDERCORE_API bool Substrate::IsStochasticLightingEnabled (EShaderPlatform InPlatform)
RENDERCORE_API bool Substrate::IsSubstrateBlendableGBufferEnabled (EShaderPlatform InPlatform)
RENDERCORE_API bool Substrate::IsSubstrateEnabled ()
RENDERCORE_API bool IsUsingBasePassVelocity (const FStaticShaderPlatform Platform)
Returns whether the base pass should output to the velocity buffer is enabled for a given shader platform.
RENDERCORE_API bool IsUsingDBuffers (const FStaticShaderPlatform Platform)
RENDERCORE_API bool IsUsingDistanceFields (const FStaticShaderPlatform Platform)
Returns whether distance fields are enabled for a given shader platform.
RENDERCORE_API bool IsUsingGBuffers (const FStaticShaderPlatform Platform)
Returns if the GBuffer is used.
RENDERCORE_API bool IsUsingSelectiveBasePassOutputs (const FStaticShaderPlatform Platform)
Returns whether the base pass should use selective outputs for a given shader platform.
RENDERCORE_API bool IsWaterDistanceFieldShadowEnabled (const FStaticShaderPlatform Platform)
Returns if water should render distance field shadow a second time for the water surface.
RENDERCORE_API bool IsWaterSeparateMainDirLightEnabled (const FStaticShaderPlatform Platform)
Returns if water needs a separate main directional light texture.
RENDERCORE_API bool IsWaterVirtualShadowMapFilteringEnabled (const FStaticShaderPlatform Platform)
Returns if water should evaluate virtual shadow maps a second time for the water surface.
FORCEINLINE float Log2ToEV100 (float LuminanceMax, float Log2)
FORCEINLINE float LuminanceToEV100 (float Luminance)
FORCEINLINE float LuminanceToEV100 (float LuminanceMax, float Luminance)
RENDERCORE_API bool MaskedInEarlyPass (const FStaticShaderPlatform Platform)
RENDERCORE_API bool MobileAllowFramebufferFetch (const FStaticShaderPlatform Platform)
RENDERCORE_API bool MobileBasePassAlwaysUsesCSM (const FStaticShaderPlatform Platform)
RENDERCORE_API bool MobileForwardEnableClusteredReflections (const FStaticShaderPlatform Platform)
bool MobileForwardEnableLocalLights (const FStaticShaderPlatform Platform)
bool MobileForwardEnableParticleLights (const FStaticShaderPlatform Platform)
RENDERCORE_API bool MobileRequiresSceneDepthAux (const FStaticShaderPlatform Platform)
bool MobileSupportsGPUScene ()
RENDERCORE_API bool MobileUsesExtenedGBuffer (const FStaticShaderPlatform Platform)
RENDERCORE_API bool MobileUsesFullDepthPrepass (const FStaticShaderPlatform Platform)
RENDERCORE_API bool MobileUsesGBufferCustomData (const FStaticShaderPlatform Platform)
RENDERCORE_API bool MobileUsesShadowMaskTexture (const FStaticShaderPlatform Platform)
RENDERCORE_API bool NaniteAtomicsSupported ()
RENDERCORE_API bool NaniteSkinnedMeshesSupported ()
RENDERCORE_API bool NaniteSplineMeshesSupported ()
RENDERCORE_API bool NaniteWorkGraphMaterialsSupported ()
RENDERCORE_API bool PlatformGPUSceneUsesUniformBufferView (const FStaticShaderPlatform Platform)
RENDERCORE_API bool PlatformRequires128bitRT (EPixelFormat PixelFormat)
Note, this should only be used when a platform requires special shader compilation for 32 bit pixel format render targets.
RENDERCORE_API bool PlatformSupportsVelocityRendering (const FStaticShaderPlatform Platform)
RENDERCORE_API void QuantizeSceneBufferSize (const FIntPoint &InBufferSize, FIntPoint &OutBufferSize, const uint32 SuggestedDivisor=0)
Takes the requested buffer size and quantizes it to an appropriate size for the rest of the rendering pipeline.
RENDERCORE_API bool RenderRectLightsAsSpotLights (const FStaticFeatureLevel FeatureLevel)
RENDERCORE_API void RenderUtilsInit ()
RENDERCORE_API bool ShouldCompileRayTracingCallableShadersForProject (EShaderPlatform ShaderPlatform)
RENDERCORE_API bool ShouldCompileRayTracingShadersForProject (EShaderPlatform ShaderPlatform)
RENDERCORE_API bool ShouldForceFullDepthPass (const FStaticShaderPlatform Platform)
RENDERCORE_API bool ShouldGenerateRayTracingProxiesByDefault ()
RENDERCORE_API bool SupportsGen4TAA (const FStaticShaderPlatform Platform)
RENDERCORE_API bool SupportsTextureCubeArray (ERHIFeatureLevel::Type FeatureLevel)
RENDERCORE_API bool SupportsTSR (const FStaticShaderPlatform Platform)
RENDERCORE_API bool UseGPUScene (const FStaticShaderPlatform Platform)
RENDERCORE_API bool UseGPUScene (const FStaticShaderPlatform Platform, const FStaticFeatureLevel FeatureLevel)
RENDERCORE_API bool UseNanite (EShaderPlatform ShaderPlatform, bool bCheckForAtomicSupport=true, bool bCheckForProjectSetting=true)
Returns true if Nanite rendering should be used for the given shader platform.
RENDERCORE_API bool UseNaniteFastTileClear ()
RENDERCORE_API bool UseNaniteLandscapeMesh (EShaderPlatform ShaderPlatform)
Checks if platform uses a Nanite landscape mesh.
RENDERCORE_API bool UseNaniteTessellation ()
RENDERCORE_API bool UseNonNaniteVirtualShadowMaps (EShaderPlatform ShaderPlatform, FStaticFeatureLevel FeatureLevel)
Similar to DoesPlatformSupportNonNaniteVirtualShadowMaps, but checks if nanite and virtual shadow maps are enabled (at runtime).
RENDERCORE_API bool UseRemoveUnsedInterpolators (EShaderPlatform ShaderPlatform)
Checks if we can strip unused interpolators for a specific platform.
RENDERCORE_API bool UseShaderPipelines (EShaderPlatform ShaderPlatform)
Checks if shader pipelines is enable for a specific platform.
RENDERCORE_API bool UseSparseVolumeTextures (EShaderPlatform Platform)
Returns true if SparseVolumeTextures are supported on the given shader platform and are enabled.
RENDERCORE_API bool UseSplineMeshSceneResources (const FStaticShaderPlatform Platform)
Whether or not the platform supports the scene spline texture for spline meshes.
RENDERCORE_API bool UseVirtualShadowMaps (EShaderPlatform ShaderPlatform)
Returns true if Virtual Shadow Maps should be used for the given shader platform.
RENDERCORE_API bool UseVirtualShadowMaps (EShaderPlatform ShaderPlatform, const FStaticFeatureLevel FeatureLevel)
Returns true if Virtual Shadow Maps should be used for the given shader platform.
RENDERCORE_API bool UseVirtualTextureLightmap (const FStaticShaderPlatform Platform, const ITargetPlatformSettings *TargetPlatform=nullptr)
Checks if virtual texturing lightmap enabled and supported.
RENDERCORE_API bool UseVirtualTexturing (const FStaticShaderPlatform InShaderPlatform)
Checks if virtual texturing enabled and supported.
RENDERCORE_API bool UseVirtualTexturing (const FStaticShaderPlatform InShaderPlatform, const ITargetPlatformSettings *InTargetPlatform)
RENDERCORE_API bool UseVirtualTexturing (const ITargetPlatformSettings *InTargetPlatform)
RENDERCORE_API bool VelocityEncodeDepth (const FStaticShaderPlatform Platform)
RENDERCORE_API bool VelocityEncodeHasPixelAnimation (const FStaticShaderPlatform Platform)
Variables
constexpr FColor DebugUtilColor [(32)]
RENDERCORE_API const uint16 GCubeIndices [36]
The indices for drawing a cube.
Macro Definition Documentation
NUM_CUBE_VERTICES
#define NUM_CUBE_VERTICES 36
Definition at line 55 of file RenderUtils.h.
NUM_DEBUG_UTIL_COLORS
#define NUM_DEBUG_UTIL_COLORS (32)
Definition at line 18 of file RenderUtils.h.
Enumeration Type Documentation
EConstructTextureFlags
enum EConstructTextureFlags : uint32
Flags that control ConstructTexture(2D/2DArray/Volume/etc.)
Enumerator
CTF_Compress
Compress RGBA8 to DXT.
CTF_DeferCompression
Don't actually compress until the package is saved.
CTF_SRGB
Enable SRGB on the texture.
CTF_AllowMips
Generate mipmaps for the texture.
CTF_ForceOneBitAlpha
Use DXT1a to get 1 bit alpha but only 4 bits per pixel (note: color of alpha'd out part will be black)
CTF_RemapAlphaAsMasked
When rendering a masked material, the depth is in the alpha, and anywhere not rendered will be full depth, which should actually be alpha of 0, and anything else is alpha of 255.
CTF_ForceOpaque
Ensure the alpha channel of the texture is opaque white (255).
CTF_SkipPostEdit
Don't call a post edit change on the texture.
CTF_Default
Default flags (maps to previous defaults to ConstructTexture2D)
Definition at line 124 of file RenderUtils.h.
Function Documentation
AllowPerPixelShadingModels()
RENDERCORE_API bool AllowPerPixelShadingModels (const FStaticShaderPlatform Platform)
References Platform.
AllowPixelDepthOffset()
RENDERCORE_API bool AllowPixelDepthOffset (const FStaticShaderPlatform Platform)
References Platform.
AllowTranslucencyPerObjectShadows()
RENDERCORE_API bool AllowTranslucencyPerObjectShadows (const FStaticShaderPlatform Platform)
Read-only switch to check if translucency per object shadows are enabled.
References Platform.
AreMobileScreenSpaceReflectionsEnabled()
RENDERCORE_API bool AreMobileScreenSpaceReflectionsEnabled (const FStaticShaderPlatform Platform)
References Platform.
AreNaniteFallbackMeshesEnabledForPlatform()
RENDERCORE_API bool AreNaniteFallbackMeshesEnabledForPlatform (const FStaticShaderPlatform Platform)
Returns true if Nanite Fallback Meshes are enabled for the given shader platform.
References Platform.
AreSkinCacheShadersEnabled()
RENDERCORE_API bool AreSkinCacheShadersEnabled (EShaderPlatform Platform)
Checks if skin cache shaders are enabled for the platform (via r.SkinCache.CompileShaders)
References Platform.
CalcMipMapExtent()
RENDERCORE_API FIntPoint CalcMipMapExtent (uint32 TextureSizeX, uint32 TextureSizeY, EPixelFormat Format, uint32 MipIndex)
Calculates the extent of a mip.
Incorrectly forces min mip size to be block dimensions: UE-159189
Parameters
TextureSizeX Number of horizontal texels (for the base mip-level)
TextureSizeY Number of vertical texels (for the base mip-level)
Format Texture format
MipIndex The index of the mip-map to compute the size of.
References Format.
CalcMipMapExtent3D()
RENDERCORE_API void CalcMipMapExtent3D (uint32 TextureSizeX, uint32 TextureSizeY, uint32 TextureSizeZ, EPixelFormat Format, uint32 MipIndex, uint32 & OutXExtent, uint32 & OutYExtent, uint32 & OutZExtent)
Calculates the extent of a mip.
Incorrectly forces min mip size to be block dimensions: UE-159189
Parameters
TextureSizeX Number of horizontal texels (for the base mip-level)
TextureSizeY Number of vertical texels (for the base mip-level)
TextureSizeZ Number of depth texels (for the base mip-level)
Format Texture format
MipIndex The index of the mip-map to compute the size of.
OutXExtent The extent X of the mip
OutYExtent The extent Y of the mip
OutZExtent The extent Z of the mip
References Format.
CalcTextureMipMapSize()
RENDERCORE_API SIZE_T CalcTextureMipMapSize (uint32 TextureSizeX, uint32 TextureSizeY, EPixelFormat Format, uint32 MipIndex)
Calculates the amount of memory used for a single mip-map of a texture.
Use GPixelFormats[Format].Get2DTextureMipSizeInBytes() instead.
Parameters
TextureSizeX Number of horizontal texels (for the base mip-level)
TextureSizeY Number of vertical texels (for the base mip-level)
Format Texture format
MipIndex The index of the mip-map to compute the size of.
References Format.
CalcTextureMipMapSize3D()
RENDERCORE_API SIZE_T CalcTextureMipMapSize3D (uint32 TextureSizeX, uint32 TextureSizeY, uint32 TextureSizeZ, EPixelFormat Format, uint32 MipIndex)
Calculates the amount of memory used for a single mip-map of a texture 3D.
Use GPixelFormats[Format].Get3DTextureMipSizeInBytes() instead.
Parameters
TextureSizeX Number of horizontal texels (for the base mip-level)
TextureSizeY Number of vertical texels (for the base mip-level)
TextureSizeZ Number of slices (for the base mip-level)
Format Texture format
MipIndex The index of the mip-map to compute the size of.
References Format.
CalcTextureSize()
RENDERCORE_API SIZE_T CalcTextureSize (uint32 SizeX, uint32 SizeY, EPixelFormat Format, uint32 MipCount)
Calculates the amount of memory used for a texture.
Use GPixelFormats[Format].Get2DTextureSizeInBytes() instead.
Parameters
SizeX Number of horizontal texels (for the base mip-level)
SizeY Number of vertical texels (for the base mip-level)
Format Texture format
MipCount Number of mip-levels (including the base mip-level)
References Format.
CalcTextureSize3D()
RENDERCORE_API SIZE_T CalcTextureSize3D (uint32 SizeX, uint32 SizeY, uint32 SizeZ, EPixelFormat Format, uint32 MipCount)
Calculates the amount of memory used for a texture.
Use GPixelFormats[Format].Get3DTextureSizeInBytes() instead.
Parameters
SizeX Number of horizontal texels (for the base mip-level)
SizeY Number of vertical texels (for the base mip-level)
SizeY Number of depth texels (for the base mip-level)
Format Texture format
MipCount Number of mip-levels (including the base mip-level)
References Format.
CalculateGridZParams()
FVector CalculateGridZParams (float NearPlane, float FarPlane, float DepthDistributionScale, int32 GridSizeZ) inline
Definition at line 641 of file RenderUtils.h.
References B, FVector, and NearPlane.
CopyTextureData2D()
RENDERCORE_API void CopyTextureData2D (const void * Source, void * Dest, uint32 SizeY, EPixelFormat Format, uint32 SourceStride, uint32 DestStride)
Copies the data for a 2D texture between two buffers with potentially different strides.
Parameters
Source - The source buffer
Dest - The destination buffer.
SizeY - The height of the texture data to copy in pixels.
Format - The format of the texture being copied.
SourceStride - The stride of the source buffer.
DestStride - The stride of the destination buffer.
References Format, and Source.
DoesPlatformSupportHeterogeneousVolumes()
RENDERCORE_API bool DoesPlatformSupportHeterogeneousVolumes (EShaderPlatform Platform)
Returns true if Heterogeneous Volumes should be used for the given shader platform.
References Platform.
DoesPlatformSupportLumenGI()
RENDERCORE_API bool DoesPlatformSupportLumenGI (EShaderPlatform Platform, bool bSkipProjectCheck = false) extern
References Platform.
DoesPlatformSupportNanite()
RENDERCORE_API bool DoesPlatformSupportNanite (EShaderPlatform Platform, bool bCheckForProjectSetting = true)
References Platform.
DoesPlatformSupportNonNaniteVirtualShadowMaps()
RENDERCORE_API bool DoesPlatformSupportNonNaniteVirtualShadowMaps (EShaderPlatform ShaderPlatform)
Returns true if non-Nanite virtual shadow maps are enabled by CVar r.Shadow.Virtual.NonNaniteVSM and the runtime supports Nanite/virtual shadow maps.
References ShaderPlatform.
DoesPlatformSupportSparseVolumeTextures()
RENDERCORE_API bool DoesPlatformSupportSparseVolumeTextures (EShaderPlatform Platform)
Returns true if SparseVolumeTextures are supported on the given shader platform.
References Platform.
DoesPlatformSupportVirtualShadowMaps()
RENDERCORE_API bool DoesPlatformSupportVirtualShadowMaps (EShaderPlatform Platform)
Returns true if Virtual Shadow Mapsare supported for the given shader platform.
Note: Virtual Shadow Maps require Nanite platform support.
References Platform.
DoesProjectSupportExpFogMatchesVolumetricFog()
RENDERCORE_API bool DoesProjectSupportExpFogMatchesVolumetricFog ()
DoesProjectSupportLumenGI()
RENDERCORE_API bool DoesProjectSupportLumenGI (EShaderPlatform Platform)
References Platform.
DoesProjectSupportLumenRayTracedTranslucentRefraction()
RENDERCORE_API bool DoesProjectSupportLumenRayTracedTranslucentRefraction () extern
DoesRuntimeSupportHeterogeneousVolumes()
RENDERCORE_API bool DoesRuntimeSupportHeterogeneousVolumes (EShaderPlatform Platform)
References Platform.
DoesRuntimeSupportNanite()
RENDERCORE_API bool DoesRuntimeSupportNanite (EShaderPlatform ShaderPlatform, bool bCheckForAtomicSupport, bool bCheckForProjectSetting)
References ShaderPlatform.
DoesRuntimeSupportOnePassPointLightShadows()
RENDERCORE_API bool DoesRuntimeSupportOnePassPointLightShadows (EShaderPlatform Platform)
References Platform.
DoesTargetPlatformSupportNanite()
RENDERCORE_API bool DoesTargetPlatformSupportNanite (const ITargetPlatform * TargetPlatform)
EV100ToLog2()
FORCEINLINE float EV100ToLog2 (float LuminanceMax, float EV100)
Definition at line 675 of file RenderUtils.h.
References FORCEINLINE, and FMath::Log2().
EV100ToLuminance() [1/2]
FORCEINLINE float EV100ToLuminance (float EV100)
Definition at line 669 of file RenderUtils.h.
References EV100ToLuminance(), and FORCEINLINE.
EV100ToLuminance() [2/2]
FORCEINLINE float EV100ToLuminance (float LuminanceMax, float EV100)
Definition at line 664 of file RenderUtils.h.
References FORCEINLINE.
Referenced by EV100ToLuminance().
ExcludeNonPipelinedShaderTypes()
RENDERCORE_API bool ExcludeNonPipelinedShaderTypes (EShaderPlatform ShaderPlatform)
Checks if the non-pipeline shaders will not be compild and ones from FShaderPipeline used instead.
References ShaderPlatform.
ForceSimpleSkyDiffuse()
RENDERCORE_API bool ForceSimpleSkyDiffuse (const FStaticShaderPlatform Platform)
References Platform.
ForwardShadingForcesSkyLightCubemapBlending()
RENDERCORE_API bool ForwardShadingForcesSkyLightCubemapBlending (const FStaticShaderPlatform Platform)
Return true if all forward shaded material should blend the interpolated sky boxes for higher quality.
References Platform.
GetCubeFaceFromName()
RENDERCORE_API ECubeFace GetCubeFaceFromName (const FString & Name)
Convert from text string to ECubeFace.
Parameters
Name e.g. RandomNamePosX
Returns
CubeFace_MAX if not recognized
References Name.
GetCubeFaceName()
RENDERCORE_API const TCHAR * GetCubeFaceName (ECubeFace Face)
Convert from ECubeFace to text string.
Parameters
Face - ECubeFace type to convert
Returns
text string for cube face enum value
References Face.
GetCubeVertexIndex()
uint16 GetCubeVertexIndex (uint32 X, uint32 Y, uint32 Z) inline
Maps from an X,Y,Z cube vertex coordinate to the corresponding vertex index.
Definition at line 63 of file RenderUtils.h.
References X, Y, and Z.
GetHairStrandsLODMode()
RENDERCORE_API uint32 GetHairStrandsLODMode ()
GetHairStrandsUsesTriangleStrips()
RENDERCORE_API bool GetHairStrandsUsesTriangleStrips ()
GetLightFunctionAtlasFormat()
RENDERCORE_API int32 GetLightFunctionAtlasFormat ()
GetPixelFormatValidChannels()
RENDERCORE_API EPixelFormatChannelFlags GetPixelFormatValidChannels (EPixelFormat InPixelFormat)
Returns the valid channels for this pixel format.
Returns
e.g. EPixelFormatChannelFlags::G for PF_G8
GetPlatformShadingModelsMask()
RENDERCORE_API uint32 GetPlatformShadingModelsMask (const FStaticShaderPlatform Platform)
References Platform.
GetRayTracingMode()
RENDERCORE_API ERayTracingMode GetRayTracingMode () extern
GetSingleLayerWaterUsesLightFunctionAtlas()
RENDERCORE_API bool GetSingleLayerWaterUsesLightFunctionAtlas ()
GetTranslucentUsesLightFunctionAtlas()
RENDERCORE_API bool GetTranslucentUsesLightFunctionAtlas ()
GetTranslucentUsesLightIESProfiles()
RENDERCORE_API bool GetTranslucentUsesLightIESProfiles ()
GetTranslucentUsesLightRectLights()
RENDERCORE_API bool GetTranslucentUsesLightRectLights ()
GetTranslucentUsesShadowedLocalLights()
RENDERCORE_API bool GetTranslucentUsesShadowedLocalLights ()
GetUnitCubeAABBVertexBuffer()
RENDERCORE_API FBufferRHIRef & GetUnitCubeAABBVertexBuffer ()
Unit cube AABB vertex buffer (useful to create procedural raytracing geometry)
GetUnitCubeIndexBuffer()
RENDERCORE_API FBufferRHIRef & GetUnitCubeIndexBuffer ()
Unit cube index buffer.
GetUnitCubeVertexBuffer()
RENDERCORE_API FBufferRHIRef & GetUnitCubeVertexBuffer ()
Unit cube vertex buffer (VertexDeclarationFVector4)
GetVertexDeclarationFVector2()
RENDERCORE_API FVertexDeclarationRHIRef & GetVertexDeclarationFVector2 ()
GetVertexDeclarationFVector3()
RENDERCORE_API FVertexDeclarationRHIRef & GetVertexDeclarationFVector3 ()
GetVertexDeclarationFVector4()
RENDERCORE_API FVertexDeclarationRHIRef & GetVertexDeclarationFVector4 ()
HardwareVariableRateShadingSupportedByPlatform()
RENDERCORE_API bool HardwareVariableRateShadingSupportedByPlatform (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
HasFirstPersonGBufferBit()
RENDERCORE_API bool HasFirstPersonGBufferBit (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
IsForwardShadingEnabled()
RENDERCORE_API bool IsForwardShadingEnabled (const FStaticShaderPlatform Platform)
Returns if ForwardShading is enabled.
Only valid for the current platform (otherwise call ITargetPlatform::UsesForwardShading()).
References Platform.
IsGPUSkinCacheAllowed()
RENDERCORE_API bool IsGPUSkinCacheAllowed (EShaderPlatform Platform)
Checks if skin cache shaders are allowed for the platform (via r.SkinCache.Allow)
References Platform.
IsGPUSkinCacheAvailable()
RENDERCORE_API bool IsGPUSkinCacheAvailable (EShaderPlatform Platform)
Can the skin cache be used (ie shaders added, etc)
References Platform.
IsGPUSkinPassThroughSupported()
RENDERCORE_API bool IsGPUSkinPassThroughSupported (EShaderPlatform Platform)
Does the platform support GPUSkinPassthrough permutations.
This knowledge can be used to indicate if we need to create SRV for index/vertex buffers.
References Platform.
IsMobileAmbientOcclusionEnabled()
RENDERCORE_API bool IsMobileAmbientOcclusionEnabled (const FStaticShaderPlatform Platform)
References Platform.
IsMobileCapsuleDirectShadowsEnabled()
RENDERCORE_API bool IsMobileCapsuleDirectShadowsEnabled (const FStaticShaderPlatform Platform)
References Platform.
IsMobileCapsuleShadowsEnabled()
RENDERCORE_API bool IsMobileCapsuleShadowsEnabled (const FStaticShaderPlatform Platform)
References Platform.
IsMobileDeferredShadingEnabled()
bool IsMobileDeferredShadingEnabled (const FStaticShaderPlatform Platform) inline
Definition at line 275 of file RenderUtils.h.
References IsMobileHDR(), FReadOnlyCVARCache::MobileDeferredShading(), and Platform.
IsMobileDistanceFieldAOEnabled()
RENDERCORE_API bool IsMobileDistanceFieldAOEnabled (const FStaticShaderPlatform Platform)
Returns if Mobile Distance Field AO Enabled.
References Platform.
IsMobileDistanceFieldEnabled()
RENDERCORE_API bool IsMobileDistanceFieldEnabled (const FStaticShaderPlatform Platform)
References Platform.
IsMobileHDR()
bool IsMobileHDR () inline
True if HDR is enabled for the mobile renderer.
Definition at line 265 of file RenderUtils.h.
References FReadOnlyCVARCache::MobileHDR().
Referenced by IsMobileDeferredShadingEnabled().
IsMobileMovableSpotlightShadowsEnabled()
RENDERCORE_API bool IsMobileMovableSpotlightShadowsEnabled (const FStaticShaderPlatform Platform)
References Platform.
IsRayTracingAllowed()
RENDERCORE_API bool IsRayTracingAllowed () extern
Referenced by FSkeletalMeshStreamIn::DoFinishUpdate(), FStaticMeshComponentHelper::GetUsedMaterials(), and FSkeletalMeshStreamOut::ReleaseBuffers().
IsRayTracingEnabled() [1/2]
RENDERCORE_API bool IsRayTracingEnabled () extern
Referenced by FSkeletalMeshStreamIn::CreateBuffers(), FSkeletalMeshStreamIn::DoFinishUpdate(), and FMeshRenderBufferSet::ValidateRayTracingData().
IsRayTracingEnabled() [2/2]
RENDERCORE_API bool IsRayTracingEnabled (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
IsRayTracingEnabledForProject()
RENDERCORE_API bool IsRayTracingEnabledForProject (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
IsRayTracingEnableOnDemandSupported()
RENDERCORE_API bool IsRayTracingEnableOnDemandSupported ()
IsRayTracingUsingReferenceBasedResidency()
RENDERCORE_API bool IsRayTracingUsingReferenceBasedResidency ()
IsSingleLayerWaterDepthPrepassEnabled()
RENDERCORE_API bool IsSingleLayerWaterDepthPrepassEnabled (const FStaticShaderPlatform Platform, FStaticFeatureLevel FeatureLevel)
(Non-runtime) Checks if the depth prepass for single layer water is enabled.
This also depends on virtual shadow maps to be supported on the platform.
References Platform.
IsStaticLightingAllowed()
bool IsStaticLightingAllowed () inline
Definition at line 571 of file RenderUtils.h.
References FReadOnlyCVARCache::AllowStaticLighting().
IsUsingBasePassVelocity()
RENDERCORE_API bool IsUsingBasePassVelocity (const FStaticShaderPlatform Platform)
Returns whether the base pass should output to the velocity buffer is enabled for a given shader platform.
References Platform.
IsUsingDBuffers()
RENDERCORE_API bool IsUsingDBuffers (const FStaticShaderPlatform Platform)
References Platform.
IsUsingDistanceFields()
RENDERCORE_API bool IsUsingDistanceFields (const FStaticShaderPlatform Platform)
Returns whether distance fields are enabled for a given shader platform.
References Platform.
IsUsingGBuffers()
RENDERCORE_API bool IsUsingGBuffers (const FStaticShaderPlatform Platform)
Returns if the GBuffer is used.
Only valid for the current platform.
References Platform.
IsUsingSelectiveBasePassOutputs()
RENDERCORE_API bool IsUsingSelectiveBasePassOutputs (const FStaticShaderPlatform Platform)
Returns whether the base pass should use selective outputs for a given shader platform.
References Platform.
IsWaterDistanceFieldShadowEnabled()
RENDERCORE_API bool IsWaterDistanceFieldShadowEnabled (const FStaticShaderPlatform Platform)
Returns if water should render distance field shadow a second time for the water surface.
This is for a platofrm so can be used at cook time.
References Platform.
IsWaterSeparateMainDirLightEnabled()
RENDERCORE_API bool IsWaterSeparateMainDirLightEnabled (const FStaticShaderPlatform Platform)
Returns if water needs a separate main directional light texture.
This is for a platofrm so can be used at cook time or at runtime.
References Platform.
IsWaterVirtualShadowMapFilteringEnabled()
RENDERCORE_API bool IsWaterVirtualShadowMapFilteringEnabled (const FStaticShaderPlatform Platform)
Returns if water should evaluate virtual shadow maps a second time for the water surface.
This is for a platform so can be used at cook time.
References Platform.
Log2ToEV100()
FORCEINLINE float Log2ToEV100 (float LuminanceMax, float Log2)
Definition at line 691 of file RenderUtils.h.
References FORCEINLINE, and FMath::Log2().
LuminanceToEV100() [1/2]
FORCEINLINE float LuminanceToEV100 (float Luminance)
Definition at line 685 of file RenderUtils.h.
References FORCEINLINE, FMath::Log2(), and Luminance.
LuminanceToEV100() [2/2]
FORCEINLINE float LuminanceToEV100 (float LuminanceMax, float Luminance)
Definition at line 680 of file RenderUtils.h.
References FORCEINLINE, FMath::Log2(), and Luminance.
MaskedInEarlyPass()
RENDERCORE_API bool MaskedInEarlyPass (const FStaticShaderPlatform Platform)
References Platform.
MobileAllowFramebufferFetch()
RENDERCORE_API bool MobileAllowFramebufferFetch (const FStaticShaderPlatform Platform)
References Platform.
MobileBasePassAlwaysUsesCSM()
RENDERCORE_API bool MobileBasePassAlwaysUsesCSM (const FStaticShaderPlatform Platform)
References Platform.
MobileForwardEnableClusteredReflections()
RENDERCORE_API bool MobileForwardEnableClusteredReflections (const FStaticShaderPlatform Platform)
References Platform.
MobileForwardEnableLocalLights()
bool MobileForwardEnableLocalLights (const FStaticShaderPlatform Platform) inline
Definition at line 280 of file RenderUtils.h.
References FReadOnlyCVARCache::MobileForwardLocalLights(), and Platform.
Referenced by MobileForwardEnableParticleLights().
MobileForwardEnableParticleLights()
bool MobileForwardEnableParticleLights (const FStaticShaderPlatform Platform) inline
Definition at line 285 of file RenderUtils.h.
References MobileForwardEnableLocalLights(), FReadOnlyCVARCache::MobileForwardParticleLights(), and Platform.
MobileRequiresSceneDepthAux()
RENDERCORE_API bool MobileRequiresSceneDepthAux (const FStaticShaderPlatform Platform)
References Platform.
MobileSupportsGPUScene()
bool MobileSupportsGPUScene () inline
Definition at line 270 of file RenderUtils.h.
References FReadOnlyCVARCache::MobileSupportsGPUScene().
MobileUsesExtenedGBuffer()
RENDERCORE_API bool MobileUsesExtenedGBuffer (const FStaticShaderPlatform Platform)
References Platform.
MobileUsesFullDepthPrepass()
RENDERCORE_API bool MobileUsesFullDepthPrepass (const FStaticShaderPlatform Platform)
References Platform.
MobileUsesGBufferCustomData()
RENDERCORE_API bool MobileUsesGBufferCustomData (const FStaticShaderPlatform Platform)
References Platform.
MobileUsesShadowMaskTexture()
RENDERCORE_API bool MobileUsesShadowMaskTexture (const FStaticShaderPlatform Platform)
References Platform.
NaniteAtomicsSupported()
RENDERCORE_API bool NaniteAtomicsSupported ()
NaniteSkinnedMeshesSupported()
RENDERCORE_API bool NaniteSkinnedMeshesSupported ()
NaniteSplineMeshesSupported()
RENDERCORE_API bool NaniteSplineMeshesSupported ()
NaniteWorkGraphMaterialsSupported()
RENDERCORE_API bool NaniteWorkGraphMaterialsSupported ()
PlatformGPUSceneUsesUniformBufferView()
RENDERCORE_API bool PlatformGPUSceneUsesUniformBufferView (const FStaticShaderPlatform Platform)
References Platform.
PlatformRequires128bitRT()
RENDERCORE_API bool PlatformRequires128bitRT (EPixelFormat PixelFormat)
Note, this should only be used when a platform requires special shader compilation for 32 bit pixel format render targets.
Does not replace pixel format associations across the board
PlatformSupportsVelocityRendering()
RENDERCORE_API bool PlatformSupportsVelocityRendering (const FStaticShaderPlatform Platform)
References Platform.
QuantizeSceneBufferSize()
RENDERCORE_API void QuantizeSceneBufferSize (const FIntPoint & InBufferSize, FIntPoint & OutBufferSize, const uint32 SuggestedDivisor = 0)
Takes the requested buffer size and quantizes it to an appropriate size for the rest of the rendering pipeline.
Currently ensures that sizes are multiples of 4 so that they can safely be halved in size several times.
RenderRectLightsAsSpotLights()
RENDERCORE_API bool RenderRectLightsAsSpotLights (const FStaticFeatureLevel FeatureLevel)
RenderUtilsInit()
RENDERCORE_API void RenderUtilsInit () extern
ShouldCompileRayTracingCallableShadersForProject()
RENDERCORE_API bool ShouldCompileRayTracingCallableShadersForProject (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
ShouldCompileRayTracingShadersForProject()
RENDERCORE_API bool ShouldCompileRayTracingShadersForProject (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
ShouldForceFullDepthPass()
RENDERCORE_API bool ShouldForceFullDepthPass (const FStaticShaderPlatform Platform)
References Platform.
ShouldGenerateRayTracingProxiesByDefault()
RENDERCORE_API bool ShouldGenerateRayTracingProxiesByDefault ()
SupportsGen4TAA()
RENDERCORE_API bool SupportsGen4TAA (const FStaticShaderPlatform Platform)
References Platform.
SupportsTextureCubeArray()
RENDERCORE_API bool SupportsTextureCubeArray (ERHIFeatureLevel::Type FeatureLevel)
SupportsTSR()
RENDERCORE_API bool SupportsTSR (const FStaticShaderPlatform Platform)
References Platform.
UseGPUScene() [1/2]
RENDERCORE_API bool UseGPUScene (const FStaticShaderPlatform Platform)
References Platform.
UseGPUScene() [2/2]
RENDERCORE_API bool UseGPUScene (const FStaticShaderPlatform Platform, const FStaticFeatureLevel FeatureLevel)
References Platform.
Referenced by FInstancedStaticMeshComponentHelper::CollectPSOPrecacheData().
UseNanite()
RENDERCORE_API bool UseNanite (EShaderPlatform ShaderPlatform, bool bCheckForAtomicSupport = true, bool bCheckForProjectSetting = true)
Returns true if Nanite rendering should be used for the given shader platform.
References ShaderPlatform.
Referenced by Nanite::FNaniteResourcesHelper::ShouldCreateNaniteProxy(), and FSkinnedMeshComponentHelper::ShouldNaniteSkin().
UseNaniteFastTileClear()
RENDERCORE_API bool UseNaniteFastTileClear ()
UseNaniteLandscapeMesh()
RENDERCORE_API bool UseNaniteLandscapeMesh (EShaderPlatform ShaderPlatform)
Checks if platform uses a Nanite landscape mesh.
References ShaderPlatform.
UseNaniteTessellation()
RENDERCORE_API bool UseNaniteTessellation ()
Referenced by FPrimitiveComponentHelper::GetUsedMaterialPropertyDesc().
UseNonNaniteVirtualShadowMaps()
RENDERCORE_API bool UseNonNaniteVirtualShadowMaps (EShaderPlatform ShaderPlatform, FStaticFeatureLevel FeatureLevel)
Similar to DoesPlatformSupportNonNaniteVirtualShadowMaps, but checks if nanite and virtual shadow maps are enabled (at runtime).
References ShaderPlatform.
UseRemoveUnsedInterpolators()
RENDERCORE_API bool UseRemoveUnsedInterpolators (EShaderPlatform ShaderPlatform)
Checks if we can strip unused interpolators for a specific platform.
References ShaderPlatform.
UseShaderPipelines()
RENDERCORE_API bool UseShaderPipelines (EShaderPlatform ShaderPlatform)
Checks if shader pipelines is enable for a specific platform.
References ShaderPlatform.
UseSparseVolumeTextures()
RENDERCORE_API bool UseSparseVolumeTextures (EShaderPlatform Platform)
Returns true if SparseVolumeTextures are supported on the given shader platform and are enabled.
References Platform.
UseSplineMeshSceneResources()
RENDERCORE_API bool UseSplineMeshSceneResources (const FStaticShaderPlatform Platform)
Whether or not the platform supports the scene spline texture for spline meshes.
References Platform.
UseVirtualShadowMaps() [1/2]
RENDERCORE_API bool UseVirtualShadowMaps (EShaderPlatform ShaderPlatform)
Returns true if Virtual Shadow Maps should be used for the given shader platform.
Note: Virtual Shadow Maps require Nanite support.
References ShaderPlatform.
UseVirtualShadowMaps() [2/2]
RENDERCORE_API bool UseVirtualShadowMaps (EShaderPlatform ShaderPlatform, const FStaticFeatureLevel FeatureLevel)
Returns true if Virtual Shadow Maps should be used for the given shader platform.
Note: Virtual Shadow Maps require Nanite support.
References ShaderPlatform.
UseVirtualTextureLightmap()
RENDERCORE_API bool UseVirtualTextureLightmap (const FStaticShaderPlatform Platform, const ITargetPlatformSettings * TargetPlatform = nullptr)
Checks if virtual texturing lightmap enabled and supported.
References Platform.
UseVirtualTexturing() [1/3]
RENDERCORE_API bool UseVirtualTexturing (const FStaticShaderPlatform InShaderPlatform)
Checks if virtual texturing enabled and supported.
UseVirtualTexturing() [2/3]
RENDERCORE_API bool UseVirtualTexturing (const FStaticShaderPlatform InShaderPlatform, const ITargetPlatformSettings * InTargetPlatform)
UseVirtualTexturing() [3/3]
RENDERCORE_API bool UseVirtualTexturing (const ITargetPlatformSettings * InTargetPlatform)
VelocityEncodeDepth()
RENDERCORE_API bool VelocityEncodeDepth (const FStaticShaderPlatform Platform)
References Platform.
VelocityEncodeHasPixelAnimation()
RENDERCORE_API bool VelocityEncodeHasPixelAnimation (const FStaticShaderPlatform Platform)
References Platform.
Variable Documentation
DebugUtilColor
FColor DebugUtilColor[(32)] inline constexpr
Definition at line 19 of file RenderUtils.h.
GCubeIndices
RENDERCORE_API const uint16 GCubeIndices[36] extern
The indices for drawing a cube.