Unreal Engine 5.6 C++ API: TGuardValueAccessors< AssignedType > Struct Template Reference
TGuardValueAccessors< AssignedType > Struct Template Reference
Guard around saving/restoring a value.
#include "GuardValueAccessors.h"
Public Member Functions
~TGuardValueAccessors ()
FORCEINLINE const AssignedType & GetOriginalValue () const
Provides read-only access to the original value of the data being tracked by this struct.
TFunction< void(const AssignedType &)> const AssignedType OriginalValue (Getter())
UE_NONCOPYABLE (TGuardValueAccessors) explicit TGuardValueAccessors(TFunctionRef< AssignedType()> Getter
Data Fields
TFunction< void(const AssignedType &)> && InSetter
TFunction< void(const AssignedType &)> const AssignedType & NewValue: Setter(MoveTemp(InSetter))
Private Attributes
AssignedType OriginalValue
TFunction< void(const AssignedType &)> Setter
Detailed Description
template<typename AssignedType>
struct TGuardValueAccessors< AssignedType >
Guard around saving/restoring a value.
Commonly used to make sure a value is restored even if the code early outs in the future. Usage: TGuardValueAccessors GuardSomeBool(UE::SomeGetterFunction, UE::SomeSetterFunction, false); // Saves the state, sets the value, and restores it in dtor.
Definition at line 16 of file GuardValueAccessors.h.
Constructor & Destructor Documentation
~TGuardValueAccessors()
template<typename AssignedType> TGuardValueAccessors< AssignedType >::~TGuardValueAccessors () inline
Definition at line 27 of file GuardValueAccessors.h.
References OriginalValue, and Setter.
Member Function Documentation
GetOriginalValue()
template<typename AssignedType> FORCEINLINE const AssignedType & TGuardValueAccessors< AssignedType >::GetOriginalValue () const inline
Provides read-only access to the original value of the data being tracked by this struct.
Returns
a const reference to the original data value
Definition at line 37 of file GuardValueAccessors.h.
References FORCEINLINE, and OriginalValue.
OriginalValue()
template<typename AssignedType> TFunction< void(const AssignedType &)> const AssignedType TGuardValueAccessors< AssignedType >::OriginalValue (Getter()) inline
Definition at line 22 of file GuardValueAccessors.h.
References NewValue, OriginalValue, and Setter.
UE_NONCOPYABLE()
template<typename AssignedType> TGuardValueAccessors< AssignedType >::UE_NONCOPYABLE (TGuardValueAccessors< AssignedType >) nodiscard
Field Documentation
InSetter
template<typename AssignedType> TFunction<void(const AssignedType&)>&& TGuardValueAccessors< AssignedType >::InSetter
Definition at line 20 of file GuardValueAccessors.h.
NewValue
template<typename AssignedType> TFunction<void(const AssignedType&)> const AssignedType& TGuardValueAccessors< AssignedType >::NewValue
Definition at line 20 of file GuardValueAccessors.h.
Referenced by OriginalValue().
OriginalValue
template<typename AssignedType> AssignedType TGuardValueAccessors< AssignedType >::OriginalValue private
Definition at line 43 of file GuardValueAccessors.h.
Referenced by ~TGuardValueAccessors(), GetOriginalValue(), and OriginalValue().
Setter
template<typename AssignedType> TFunction<void(const AssignedType&)> TGuardValueAccessors< AssignedType >::Setter private
Definition at line 42 of file GuardValueAccessors.h.
Referenced by ~TGuardValueAccessors(), and OriginalValue().
The documentation for this struct was generated from the following file:
GuardValueAccessors.h