Unreal Engine 5.6 C++ API: FReimportHandler Class Reference
FReimportHandler Class Reference abstract
Reimport handler for package resources with associated source files on disk.
#include "EditorReimportHandler.h"
Public Member Functions
FReimportHandler ()
Constructor.
virtual ~FReimportHandler ()
Destructor.
virtual bool CanReimport (UObject *Obj, TArray< FString > &OutFilenames)=0
Check to see if the handler is capable of reimporting the object.
virtual TObjectPtr< UObject > * GetFactoryObject () const
Returns the UFactory object associated with this reimport handler.
virtual UNREALED_API int32 GetPriority () const
Get the import priority for this handler.
virtual bool IsAutomatedReimport () const
When True dialog prompts should not appear.
virtual bool IsForceShowDialog () const
When True dialog prompts will prompts even if the show dialog setting is false.
virtual bool IsInterchangeFactory () const
virtual void PostImportCleanUp ()
Call after multiple import happen.
virtual EReimportResult::Type Reimport (UObject *Obj)=0
Attempt to reimport the specified object from its source.
virtual EReimportResult::Type Reimport (UObject *Obj, int32 SourceFileIndex)
Attempt to reimport the specified object from its source.
virtual void SetAutomatedReimport (const bool InAutomatedReimport)
Sets automated, when True dialog prompts should not appear.
virtual void SetForceShowDialog (const bool InbForceShowDialog)
Sets force show dialog, when True dialog will prompts even if the show dialog setting is false.
void SetPreferredReimportPath (const FString &Path)
Sets the preferred reimport path, for aiding in resolving reimporting objects where the object path differs from the new path (ex.
virtual void SetReimportPaths (UObject *Obj, const FString &NewReimportPath, const int32 SourceIndex)
Sets the reimport path(s) for the specified object at the specified index.
virtual void SetReimportPaths (UObject *Obj, const TArray< FString > &NewReimportPaths)=0
Sets the reimport path(s) for the specified object.
virtual void SetReimportSourceIndex (UObject *Obj, const int32 SourceIndex)
If we want to import a specific source index and there is some settings to update in the asset import data before starting the re-import.
Protected Attributes
bool bAutomatedReimport
bool bForceShowDialog = false
FString PreferredReimportPath
Detailed Description
Reimport handler for package resources with associated source files on disk.
Definition at line 206 of file EditorReimportHandler.h.
Constructor & Destructor Documentation
FReimportHandler()
FReimportHandler::FReimportHandler () inline
Constructor.
Add self to manager
Definition at line 210 of file EditorReimportHandler.h.
References bAutomatedReimport, FReimportManager::Instance(), and FReimportManager::RegisterHandler().
~FReimportHandler()
virtual FReimportHandler::~FReimportHandler () inline virtual
Destructor.
Remove self from manager
Definition at line 212 of file EditorReimportHandler.h.
References FReimportManager::Instance(), and FReimportManager::UnregisterHandler().
Member Function Documentation
CanReimport()
virtual bool FReimportHandler::CanReimport (UObject * Obj, TArray< FString > & OutFilenames) pure virtual
Check to see if the handler is capable of reimporting the object.
Parameters
Obj Object to attempt to reimport
OutFilenames The filename(s) of the source art for the specified object
Returns
true if this handler is capable of reimporting the provided object
Implemented in UReimportTextureFactory.
GetFactoryObject()
virtual TObjectPtr< UObject > * FReimportHandler::GetFactoryObject () const inline virtual
Returns the UFactory object associated with this reimport handler.
Definition at line 289 of file EditorReimportHandler.h.
GetPriority()
virtual UNREALED_API int32 FReimportHandler::GetPriority () const virtual
Get the import priority for this handler.
Import handlers with higher priority values will take precedent over lower priorities.
Reimplemented in UReimportTextureFactory.
IsAutomatedReimport()
virtual bool FReimportHandler::IsAutomatedReimport () const inline virtual
When True dialog prompts should not appear.
Definition at line 309 of file EditorReimportHandler.h.
References bAutomatedReimport.
IsForceShowDialog()
virtual bool FReimportHandler::IsForceShowDialog () const inline virtual
When True dialog prompts will prompts even if the show dialog setting is false.
Definition at line 326 of file EditorReimportHandler.h.
References bForceShowDialog.
IsInterchangeFactory()
virtual bool FReimportHandler::IsInterchangeFactory () const inline virtual
Definition at line 314 of file EditorReimportHandler.h.
PostImportCleanUp()
virtual void FReimportHandler::PostImportCleanUp () inline virtual
Call after multiple import happen.
Definition at line 295 of file EditorReimportHandler.h.
Reimport() [1/2]
virtual EReimportResult::Type FReimportHandler::Reimport (UObject * Obj) pure virtual
Attempt to reimport the specified object from its source.
Parameters
Obj Object to attempt to reimport
Returns
EReimportResult::Succeeded if this handler was able to handle reimporting the provided object, EReimportResult::Failed if this handler was unable to handle reimporting the provided object or EReimportResult::Cancelled if the handler was cancelled part-way through re-importing the provided object.
Implemented in UReimportTextureFactory.
Referenced by Reimport().
Reimport() [2/2]
virtual EReimportResult::Type FReimportHandler::Reimport (UObject * Obj, int32 SourceFileIndex) inline virtual
Attempt to reimport the specified object from its source.
Parameters
Obj Object to attempt to reimport
SourceFileIndex the index of the SourceFile to use to reimport the Obj
Returns
EReimportResult::Succeeded if this handler was able to handle reimporting the provided object, EReimportResult::Failed if this handler was unable to handle reimporting the provided object or EReimportResult::Cancelled if the handler was cancelled part-way through re-importing the provided object.
Definition at line 277 of file EditorReimportHandler.h.
References Reimport().
SetAutomatedReimport()
virtual void FReimportHandler::SetAutomatedReimport (const bool InAutomatedReimport) inline virtual
Sets automated, when True dialog prompts should not appear.
Definition at line 303 of file EditorReimportHandler.h.
References bAutomatedReimport.
SetForceShowDialog()
virtual void FReimportHandler::SetForceShowDialog (const bool InbForceShowDialog) inline virtual
Sets force show dialog, when True dialog will prompts even if the show dialog setting is false.
Definition at line 320 of file EditorReimportHandler.h.
References bForceShowDialog.
SetPreferredReimportPath()
void FReimportHandler::SetPreferredReimportPath (const FString & Path) inline
Sets the preferred reimport path, for aiding in resolving reimporting objects where the object path differs from the new path (ex.
differing extensions).
Definition at line 300 of file EditorReimportHandler.h.
References Path, and PreferredReimportPath.
SetReimportPaths() [1/2]
virtual void FReimportHandler::SetReimportPaths (UObject * Obj, const FString & NewReimportPath, const int32 SourceIndex) inline virtual
Sets the reimport path(s) for the specified object at the specified index.
Parameters
Obj Object for which to change the reimport path(s)
NewReimportPaths The new path(s) to set on the object
SourceIndex the index of the SourceFile to set the reimport path
Definition at line 239 of file EditorReimportHandler.h.
References TArray< InElementType, InAllocatorType >::Add(), and SetReimportPaths().
SetReimportPaths() [2/2]
virtual void FReimportHandler::SetReimportPaths (UObject * Obj, const TArray< FString > & NewReimportPaths) pure virtual
Sets the reimport path(s) for the specified object.
Parameters
Obj Object for which to change the reimport path(s)
NewReimportPaths The new path(s) to set on the object
Implemented in UReimportTextureFactory.
Referenced by SetReimportPaths().
SetReimportSourceIndex()
virtual void FReimportHandler::SetReimportSourceIndex (UObject * Obj, const int32 SourceIndex) inline virtual
If we want to import a specific source index and there is some settings to update in the asset import data before starting the re-import.
Parameters
Obj - Object for which to change re-import settings.
SourceIndex - the index of the SourceFile that will be re-imported
Definition at line 252 of file EditorReimportHandler.h.
Field Documentation
bAutomatedReimport
bool FReimportHandler::bAutomatedReimport protected
Definition at line 333 of file EditorReimportHandler.h.
Referenced by FReimportHandler(), IsAutomatedReimport(), and SetAutomatedReimport().
bForceShowDialog
bool FReimportHandler::bForceShowDialog = false protected
Definition at line 334 of file EditorReimportHandler.h.
Referenced by IsForceShowDialog(), and SetForceShowDialog().
PreferredReimportPath
FString FReimportHandler::PreferredReimportPath protected
Definition at line 332 of file EditorReimportHandler.h.
Referenced by SetPreferredReimportPath().
The documentation for this class was generated from the following file:
EditorReimportHandler.h