Unreal Engine 5.6 C++ API: TIndependentTickReplicator_AP< InModelDef > Class Template Reference
TIndependentTickReplicator_AP< InModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Public Types
using ModelDef = InModelDef
Static Public Member Functions
static void NetRecv (const FNetSerializeParams &P, TClientRecvData< ModelDef > &ClientRecvState, TModelDataStore< ModelDef > *DataStore, FVariableTickState *TickState)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, TServerRecvData_Independent< ModelDef > &ServerRecvData, const FVariableTickState *VariableTickState)
Detailed Description
template<typename InModelDef>
class TIndependentTickReplicator_AP< InModelDef >
Definition at line 479 of file NetworkPredictionSerialization.h.
Member Typedef Documentation
ModelDef
template<typename InModelDef> using TIndependentTickReplicator_AP< InModelDef >::ModelDef = InModelDef
Definition at line 483 of file NetworkPredictionSerialization.h.
Member Function Documentation
NetRecv()
template<typename InModelDef> void TIndependentTickReplicator_AP< InModelDef >::NetRecv (const FNetSerializeParams & P, TClientRecvData< ModelDef > & ClientRecvState, TModelDataStore< ModelDef > * DataStore, FVariableTickState * TickState) inline static
Definition at line 488 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, FVariableTickState::ConfirmedFrame, TClientRecvData< ModelDef >::InstanceIdx, TModelDataStore< ModelDef >::Instances, TCommonReplicator_AP< ModelDef >::NetRecv(), npEnsure, FVariableTickState::PendingFrame, FNetworkPredictionSerialization::ReadCompressedFrame(), FNetworkPredictionSerialization::SerializeTimeMS(), TClientRecvData< ModelDef >::ServerFrame, TClientRecvData< ModelDef >::SimTimeMS, and UE_NP_TRACE_NET_RECV.
NetSend()
template<typename InModelDef> void TIndependentTickReplicator_AP< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, TServerRecvData_Independent< ModelDef > & ServerRecvData, const FVariableTickState * VariableTickState) inline static
Definition at line 508 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, TInstanceFrameState< ModelDef >::Buffer, TModelDataStore< ModelDef >::Frames, TServerRecvData_Independent< ModelDef >::FramesIdx, ID, TServerRecvData_Independent< ModelDef >::InstanceIdx, TModelDataStore< ModelDef >::Instances, TServerRecvData_Independent< ModelDef >::LastConsumedFrame, TCommonReplicator_AP< ModelDef >::NetSend(), TServerRecvData_Independent< ModelDef >::PendingFrame, FNetworkPredictionSerialization::SerializeTimeMS(), TServerRecvData_Independent< ModelDef >::TotalSimTimeMS, and FNetworkPredictionSerialization::WriteCompressedFrame().
The documentation for this class was generated from the following file:
NetworkPredictionSerialization.h