Unreal Engine 5.6 C++ API: UE::FPropertyTypeName Class Reference
UE::FPropertyTypeName Class Reference
Represents the type name of a property, including any containers and underlying types.
#include "PropertyTypeName.h"
Public Member Functions
FPropertyTypeName ()=default
FPropertyTypeName (const FProperty *Property)
FName GetName () const
Returns the type at the root of this property type name.
FPropertyTypeName GetParameter (int32 ParamIndex) const
Returns the indexed parameter under the root of this property type name.
int32 GetParameterCount () const
Returns the number of type parameters under the root of this property type name.
FName GetParameterName (int32 ParamIndex) const
Returns the indexed parameter type name under the root of this property type name.
bool IsEmpty () const
bool IsEnum (FName EnumName) const
Returns true if this is EnumProperty or ByteProperty with a first parameter of EnumName.
bool IsStruct (FName StructName) const
Returns true if this is StructProperty with a first parameter of StructName.
void Reset ()
Resets this to an empty type name.
Private Attributes
friend FPropertyTypeNameBuilder
int32 Index = 0
Friends
void AppendHash (FBlake3 &Builder, const FPropertyTypeName &TypeName)
uint32 GetTypeHash (const FPropertyTypeName &TypeName)
bool operator< (const FPropertyTypeName &Lhs, const FPropertyTypeName &Rhs)
FArchive & operator<< (FArchive &Ar, FPropertyTypeName &TypeName)
FStringBuilderBase & operator<< (FStringBuilderBase &Builder, const FPropertyTypeName &TypeName)
void operator<< (FStructuredArchiveSlot Slot, FPropertyTypeName &TypeName)
bool operator== (const FPropertyTypeName &Lhs, const FPropertyTypeName &Rhs)
Detailed Description
Represents the type name of a property, including any containers and underlying types.
The path name for a type is represented as the object name with the outer chain as type parameters.
/Script/CoreUObject.Outer0:Outer1.Outer2.StructName -> StructName(/Script/CoreUObject,Outer0,Outer1,Outer2)
Examples:
int32 -> IntProperty
TArray<int32> -> ArrayProperty(IntProperty)
TArray<FStructType> -> ArrayProperty(StructProperty(StructType(/Script/Module),e21f566f-7153-433a-959d-bfb3abed17e2))
TMap<FKeyStruct, EByteEnum> -> MapProperty(StructProperty(KeyStruct(/Script/Module)),EnumProperty(ByteEnum(/Script/Module),ByteProperty))
Incomplete property types created from sources with incomplete type information. Consumers must support this.
ArrayProperty(StructProperty)
MapProperty(EnumProperty,StructProperty)
Definition at line 45 of file PropertyTypeName.h.
Constructor & Destructor Documentation
FPropertyTypeName() [1/2]
UE::FPropertyTypeName::FPropertyTypeName () default
Referenced by AppendHash, GetParameter(), GetTypeHash, operator<, operator<<, operator<<, operator<<, and operator==.
FPropertyTypeName() [2/2]
UE::FPropertyTypeName::FPropertyTypeName (const FProperty * Property) explicit nodiscard
References Property, and UE_API.
Member Function Documentation
GetName()
FName UE::FPropertyTypeName::GetName () const nodiscard
Returns the type at the root of this property type name.
Example: MapProperty(StructProperty(KeyStruct),EnumProperty(ByteEnum,ByteProperty))
GetName() -> MapProperty
References UE_API.
Referenced by GetParameterName(), UScriptStruct::TCppStructOps< CPPSTRUCT >::SerializeFromMismatchedTag(), and UScriptStruct::TCppStructOps< CPPSTRUCT >::StructuredSerializeFromMismatchedTag().
GetParameter()
FPropertyTypeName UE::FPropertyTypeName::GetParameter (int32 ParamIndex) const nodiscard
Returns the indexed parameter under the root of this property type name.
An out-of-bounds index will return an empty type name.
Example: MapProperty(StructProperty(KeyStruct),EnumProperty(ByteEnum,ByteProperty))
GetParameter(0) -> StructProperty(KeyStruct)
GetParameter(1) -> EnumProperty(ByteEnum,ByteProperty)
References FPropertyTypeName(), and UE_API.
Referenced by GetParameterName().
GetParameterCount()
int32 UE::FPropertyTypeName::GetParameterCount () const nodiscard
Returns the number of type parameters under the root of this property type name.
Example: MapProperty(StructProperty(KeyStruct),EnumProperty(ByteEnum,ByteProperty))
GetParameterCount() -> 2
References UE_API.
Referenced by TProperty_Numeric< InTCppType >::ConvertFromType(), UScriptStruct::TCppStructOps< CPPSTRUCT >::SerializeFromMismatchedTag(), and UScriptStruct::TCppStructOps< CPPSTRUCT >::StructuredSerializeFromMismatchedTag().
GetParameterName()
FName UE::FPropertyTypeName::GetParameterName (int32 ParamIndex) const inline nodiscard
Returns the indexed parameter type name under the root of this property type name.
An out-of-bounds index will return a name of None.
Example: MapProperty(StructProperty(KeyStruct),EnumProperty(ByteEnum,ByteProperty))
GetParameterName(0) -> StructProperty
GetParameterName(1) -> EnumProperty
Definition at line 93 of file PropertyTypeName.h.
References GetName(), and GetParameter().
Referenced by UScriptStruct::TCppStructOps< CPPSTRUCT >::SerializeFromMismatchedTag(), and UScriptStruct::TCppStructOps< CPPSTRUCT >::StructuredSerializeFromMismatchedTag().
IsEmpty()
bool UE::FPropertyTypeName::IsEmpty () const inline nodiscard
Definition at line 52 of file PropertyTypeName.h.
References Index.
IsEnum()
bool UE::FPropertyTypeName::IsEnum (FName EnumName) const nodiscard
Returns true if this is EnumProperty or ByteProperty with a first parameter of EnumName.
References UE_API.
IsStruct()
bool UE::FPropertyTypeName::IsStruct (FName StructName) const nodiscard
Returns true if this is StructProperty with a first parameter of StructName.
References UE_API.
Reset()
void UE::FPropertyTypeName::Reset () inline
Resets this to an empty type name.
Definition at line 101 of file PropertyTypeName.h.
References Index.
Friends And Related Symbol Documentation
AppendHash
void AppendHash (FBlake3 & Builder, const FPropertyTypeName & TypeName) friend
References FPropertyTypeName(), and UE_API.
GetTypeHash
uint32 GetTypeHash (const FPropertyTypeName & TypeName) friend
References FPropertyTypeName(), and UE_API.
operator<
bool operator< (const FPropertyTypeName & Lhs, const FPropertyTypeName & Rhs) friend
References FPropertyTypeName(), and UE_API.
operator<< [1/3]
FArchive & operator<< (FArchive & Ar, FPropertyTypeName & TypeName) friend
References FPropertyTypeName(), Ar, and UE_API.
operator<< [2/3]
FStringBuilderBase & operator<< (FStringBuilderBase & Builder, const FPropertyTypeName & TypeName) friend
References FPropertyTypeName(), and UE_API.
operator<< [3/3]
void operator<< (FStructuredArchiveSlot Slot, FPropertyTypeName & TypeName) friend
References FPropertyTypeName(), and UE_API.
operator==
bool operator== (const FPropertyTypeName & Lhs, const FPropertyTypeName & Rhs) friend
References FPropertyTypeName(), and UE_API.
Field Documentation
FPropertyTypeNameBuilder
friend UE::FPropertyTypeName::FPropertyTypeNameBuilder private
Definition at line 125 of file PropertyTypeName.h.
Index
int32 UE::FPropertyTypeName::Index = 0 private
Definition at line 123 of file PropertyTypeName.h.
Referenced by IsEmpty(), and Reset().
The documentation for this class was generated from the following file:
PropertyTypeName.h