Unreal Engine 5.6 C++ API: FBulkDataBatchRequest::FBuilder Class Reference
FBulkDataBatchRequest::FBuilder Class Reference
Public Member Functions
FBuilder (const FBuilder &)=delete
~FBuilder ()
FBuilder & operator= (const FBuilder &)=delete
Protected Member Functions
FBuilder (int32 MaxCount)
FBulkDataBatchRequest::FBatchHandle & GetBatch ()
void IssueBatch (FBulkDataBatchRequest *OutRequest, FCompletionCallback &&Callback)
Protected Attributes
int32 BatchCount = 0
int32 NumLoaded = 0
Private Attributes
TRefCountPtr< FBulkDataBatchRequest::FBatchHandle > Batch
int32 BatchMax = -1
Detailed Description
Definition at line 1299 of file BulkData.h.
Constructor & Destructor Documentation
~FBuilder()
FBulkDataBatchRequest::FBuilder::~FBuilder ()
FBuilder() [1/2]
FBulkDataBatchRequest::FBuilder::FBuilder (const FBuilder &) delete
References FBuilder().
Referenced by FBuilder(), and operator=().
FBuilder() [2/2]
FBulkDataBatchRequest::FBuilder::FBuilder (int32 MaxCount) explicit protected
Member Function Documentation
GetBatch()
FBulkDataBatchRequest::FBatchHandle & FBulkDataBatchRequest::FBuilder::GetBatch () protected
IssueBatch()
void FBulkDataBatchRequest::FBuilder::IssueBatch (FBulkDataBatchRequest * OutRequest, FCompletionCallback && Callback) protected
References FBulkDataRequest::FBulkDataBatchRequest.
operator=()
FBuilder & FBulkDataBatchRequest::FBuilder::operator= (const FBuilder &) delete
References FBuilder().
Field Documentation
Batch
TRefCountPtr<FBulkDataBatchRequest::FBatchHandle> FBulkDataBatchRequest::FBuilder::Batch private
Definition at line 1316 of file BulkData.h.
BatchCount
int32 FBulkDataBatchRequest::FBuilder::BatchCount = 0 protected
Definition at line 1311 of file BulkData.h.
BatchMax
int32 FBulkDataBatchRequest::FBuilder::BatchMax = -1 private
Definition at line 1315 of file BulkData.h.
NumLoaded
int32 FBulkDataBatchRequest::FBuilder::NumLoaded = 0 protected
Definition at line 1312 of file BulkData.h.
The documentation for this class was generated from the following file:
BulkData.h