Unreal Engine 5.6 C++ API: SEditorViewport Class Reference
SEditorViewport Class Reference abstract
#include "SEditorViewport.h"
Public Member Functions
virtual UNREALED_API ~SEditorViewport ()
UNREALED_API TSharedRef< SWidget > BuildFixedEV100Menu () const
Build the exposure menu using EV100 settings.
UNREALED_API TSharedRef< SWidget > BuildWireframeMenu () const
Build the slider to adjust wireframe opacity.
virtual bool CanToggleInViewportContextMenu ()
UNREALED_API void Construct (const FArguments &InArgs)
UNREALED_API void EnableStereoRendering (const bool bInEnableStereoRendering)
Sets whether stereo rendering is allowed for this viewport.
const TSharedPtr< FUICommandList > GetCommandList () const
UNREALED_API TSharedPtr< IPreviewProfileController > GetPreviewProfileController ()
TSharedPtr< FSceneViewport > GetSceneViewport ()
virtual UNREALED_API EVisibility GetTransformToolbarVisibility () const
Controls the visibility of the widget transform toolbar, if there is an associated toolbar.
TSharedPtr< FEditorViewportClient > GetViewportClient () const
virtual void HideInViewportContextMenu ()
UNREALED_API void Invalidate ()
Invalidates the viewport to ensure it is redrawn during the next tick.
virtual UNREALED_API bool IsCoordSystemActive (ECoordSystem CoordSystem) const
UNREALED_API bool IsPreviewingScreenPercentage () const
UNREALED_API bool IsRealtime () const
virtual UNREALED_API bool IsVisible () const
void MarkLegacyToolbarChildAsAutomaticallyUpgradable (const TSharedRef< SWidget > &ExpectedChild)
A legacy patch built to allow SCommonEditorViewportToolbarBase to automatically switch to the new viewport style.
virtual UNREALED_API void OnCycleCoordinateSystem ()
Cycles between world and local coordinate systems.
virtual UNREALED_API FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent) override
Called when focus is given to this widget.
virtual UNREALED_API FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
UNREALED_API void OnOpenViewportPerformanceEditorPreferences ()
UNREALED_API void OnOpenViewportPerformanceProjectSettings ()
UNREALED_API void OnToggleRealtime ()
Toggles realtime on/off for the viewport.
UNREALED_API void SetRenderDirectlyToWindow (const bool bInRenderDirectlyToWindow)
Sets whether this viewport can render directly to the back buffer.
SLATE_ATTRIBUTE (FVector2D, ViewportSize)
SLATE_BEGIN_ARGS (SEditorViewport)
SLATE_END_ARGS () UNREALED_API SEditorViewport()
virtual UNREALED_API bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
virtual UNREALED_API void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
virtual void ToggleInViewportContextMenu ()
Called when the user wants to show the in-viewport context menu.
UNREALED_API void TogglePreviewingScreenPercentage ()
virtual UNREALED_API void UpdateInViewportMenuLocation (const FVector2D InLocation)
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual UNREALED_API void BindCommands ()
virtual UNREALED_API void BindShowCommands (FUICommandList &OutCommandList)
UNREALED_API TSharedRef< SWidget > BuildFeatureLevelWidget () const
call this function to build a 'text' widget that can display the present feature level
virtual TSharedPtr< SWidget > BuildViewportToolbar ()
UNREALED_API bool CanToggleRealtime () const
UNREALED_API void ChangeExposureSetting ()
Changes the auto exposure setting for this viewport.
virtual UNREALED_API TSharedPtr< IPreviewProfileController > CreatePreviewProfileController ()
virtual bool DoesAllowScreenCapture ()
UNREALED_API EVisibility GetCurrentFeatureLevelPreviewTextVisibility () const
virtual UNREALED_API UWorld * GetWorld () const
Gets the world this viewport is for.
virtual UNREALED_API bool Is2DModeVisible () const
UNREALED_API bool IsExposureSettingSelected () const
Checks if auto exposure setting is selected.
UNREALED_API bool IsFixedEV100Enabled () const
Called to know whether the fixed EV100 slider is enabled.
UNREALED_API bool IsShowFlagEnabled (uint32 EngineShowFlagIndex) const
Checks if a show flag is enabled in this viewport.
virtual UNREALED_API bool IsStatCommandVisible (FString CommandName) const
Checks if Stat command is visible in this viewport.
virtual UNREALED_API bool IsTranslateRotateModeVisible () const
virtual UNREALED_API bool IsWidgetModeActive (UE::Widget::EWidgetMode Mode) const
virtual TSharedRef< FEditorViewportClient > MakeEditorViewportClient ()=0
virtual TSharedPtr< SWidget > MakeViewportToolbar ()
virtual UNREALED_API void OnCycleWidgetMode ()
Moves between widget modes.
virtual void OnDecrementPositionGridSize ()
virtual void OnDecrementRotationGridSize ()
UNREALED_API void OnFixedEV100ValueChanged (float NewValue)
Called when fixed EV100 slider is adjusted.
virtual void OnFocusViewportToSelection ()
Called when the user wants to focus the viewport to the current selection.
UNREALED_API float OnGetFixedEV100Value () const
Called by the fixed EV100 slider to get the fixed EV100 value.
virtual EVisibility OnGetFocusedViewportIndicatorVisibility () const
virtual const FSlateBrush * OnGetViewportBorderBrush () const
virtual FSlateColor OnGetViewportBorderColorAndOpacity () const
virtual UNREALED_API EVisibility OnGetViewportContentVisibility () const
UNREALED_API float OnGetWireframeOpacity () const
virtual void OnIncrementPositionGridSize ()
Changes the snapping grid size.
virtual void OnIncrementRotationGridSize ()
virtual UNREALED_API void OnScreenCapture ()
virtual UNREALED_API void OnScreenCaptureForProjectThumbnail ()
UNREALED_API void OnToggleStats ()
UI Command delegate bindings.
UNREALED_API void OnWireframeOpacityChanged (float Opacity)
Adjustable wireframe opacity.
virtual void PopulateViewportOverlays (TSharedRef< SOverlay > Overlay)
UNREALED_API void ToggleShowFlag (uint32 EngineShowFlagIndex)
Toggles a show flag in this viewport.
virtual UNREALED_API void ToggleStatCommand (FString CommandName)
Toggles Stat command visibility in this viewport.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static UNREALED_API TSharedPtr< SWidget > CreateViewportIndicatorWidget (const TAttribute< EVisibility > &InVisibility)
Creates a widget showing whether the viewport is active or not.
static UNREALED_API bool IsDistanceBasedCameraSpeedEnabled ()
Called to test whether distance-based perspective camera speed scaling is enabled.
static UNREALED_API bool IsRotateToSurfaceNormalEnabled ()
Called to test whether rotation matching surface normal is enabled or not.
static UNREALED_API bool OnIsSurfaceSnapEnabled ()
Called to test whether surface snapping is enabled or not.
static UNREALED_API void OnToggleDistanceBasedCameraSpeed ()
Called to enable/disable distance-based perspective camera speed scaling.
static UNREALED_API void OnToggleRotateToSurfaceNormal ()
Called when rotation matching surface normal has been enabled/disabled.
static UNREALED_API void OnToggleSurfaceSnap ()
Called when surface snapping has been enabled/disabled.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
TSharedPtr< FEditorViewportClient > Client
The client responsible for setting up the scene.
TSharedPtr< FUICommandList > CommandList
Commandlist used in the viewport (Maps commands to viewport specific actions)
FVector2D InViewportContextMenuLocation
double LastTickTime
The last time the viewport was ticked (for visibility determination)
TSharedPtr< IPreviewProfileController > PreviewProfileController
Handles Preview Profiles.
TSharedPtr< FSceneViewport > SceneViewport
Viewport that renders the scene provided by the viewport client.
TSharedPtr< SOverlay > ViewportOverlay
TSharedPtr< SViewport > ViewportWidget
Widget where the scene viewport is drawn in.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
UNREALED_API EActiveTimerReturnType EnsureTick (double InCurrentTime, float InDeltaTime)
Ensures a Slate tick/paint pass when the viewport is realtime or was invalidated this frame.
UNREALED_API EVisibility GetActiveBorderVisibility () const
Gets the visibility of the active viewport border.
UNREALED_API FText GetCurrentFeatureLevelPreviewText (bool bDrawOnlyLabel) const
Called to get the feature level preview text.
UNREALED_API EShaderPlatform GetShaderPlatformHelper (const ERHIFeatureLevel::Type InFeatureLevel) const
Helper function that, for some FeatureLevel argument, will retrieve the required shader platform.
Private Attributes
TWeakPtr< FActiveTimerHandle > ActiveTimerHandle
The handle to the active timer.
TWeakPtr< SWidget > AutoUpgradeWidgetChild = nullptr
For automatic legacy toolbar upgrades.
bool bInvalidated
Whether the viewport needs to update, even without input or realtime (e.g.
bool bLegacyToolbarIsAutomaticallyUpgradable = false
A flag indicating that the automatic toolbar upgrade has been approved.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Detailed Description
Definition at line 22 of file SEditorViewport.h.
Constructor & Destructor Documentation
~SEditorViewport()
virtual UNREALED_API SEditorViewport::~SEditorViewport () virtual
Member Function Documentation
BindCommands()
virtual UNREALED_API void SEditorViewport::BindCommands () protected virtual
Reimplemented in SAssetEditorViewport.
BindShowCommands()
virtual UNREALED_API void SEditorViewport::BindShowCommands (FUICommandList & OutCommandList) protected virtual
BuildFeatureLevelWidget()
UNREALED_API TSharedRef< SWidget > SEditorViewport::BuildFeatureLevelWidget () const protected
call this function to build a 'text' widget that can display the present feature level
BuildFixedEV100Menu()
UNREALED_API TSharedRef< SWidget > SEditorViewport::BuildFixedEV100Menu () const
Build the exposure menu using EV100 settings.
BuildViewportToolbar()
virtual TSharedPtr< SWidget > SEditorViewport::BuildViewportToolbar () inline protected virtual
Definition at line 164 of file SEditorViewport.h.
BuildWireframeMenu()
UNREALED_API TSharedRef< SWidget > SEditorViewport::BuildWireframeMenu () const
Build the slider to adjust wireframe opacity.
CanToggleInViewportContextMenu()
virtual bool SEditorViewport::CanToggleInViewportContextMenu () inline virtual
Definition at line 110 of file SEditorViewport.h.
CanToggleRealtime()
UNREALED_API bool SEditorViewport::CanToggleRealtime () const protected
Returns
true if realtime can be toggled (it cannot be toggled directly if there is an override in place)
ChangeExposureSetting()
UNREALED_API void SEditorViewport::ChangeExposureSetting () protected
Changes the auto exposure setting for this viewport.
Construct()
UNREALED_API void SEditorViewport::Construct (const FArguments & InArgs)
References Construct().
Referenced by Construct().
CreatePreviewProfileController()
virtual UNREALED_API TSharedPtr< IPreviewProfileController > SEditorViewport::CreatePreviewProfileController () inline protected virtual
Definition at line 172 of file SEditorViewport.h.
CreateViewportIndicatorWidget()
UNREALED_API TSharedPtr< SWidget > SEditorViewport::CreateViewportIndicatorWidget (const TAttribute< EVisibility > & InVisibility) static protected
Creates a widget showing whether the viewport is active or not.
Parameters
InVisibility visibility attribute, can be used to dynamically hide the widget
DoesAllowScreenCapture()
virtual bool SEditorViewport::DoesAllowScreenCapture () inline protected virtual
Definition at line 229 of file SEditorViewport.h.
EnableStereoRendering()
UNREALED_API void SEditorViewport::EnableStereoRendering (const bool bInEnableStereoRendering)
Sets whether stereo rendering is allowed for this viewport.
Advanced use only
Parameters
bInEnableStereoRendering Whether stereo rendering should be allowed for this viewport
References EnableStereoRendering().
Referenced by EnableStereoRendering().
EnsureTick()
UNREALED_API EActiveTimerReturnType SEditorViewport::EnsureTick (double InCurrentTime, float InDeltaTime) private
Ensures a Slate tick/paint pass when the viewport is realtime or was invalidated this frame.
GetActiveBorderVisibility()
UNREALED_API EVisibility SEditorViewport::GetActiveBorderVisibility () const private
Gets the visibility of the active viewport border.
GetCommandList()
const TSharedPtr< FUICommandList > SEditorViewport::GetCommandList () const inline
Returns
The viewport command list
Definition at line 84 of file SEditorViewport.h.
References CommandList, and GetCommandList().
Referenced by GetCommandList().
GetCurrentFeatureLevelPreviewText()
UNREALED_API FText SEditorViewport::GetCurrentFeatureLevelPreviewText (bool bDrawOnlyLabel) const private
Called to get the feature level preview text.
GetCurrentFeatureLevelPreviewTextVisibility()
UNREALED_API EVisibility SEditorViewport::GetCurrentFeatureLevelPreviewTextVisibility () const protected
Returns
The visibility of the current feature level preview text display
GetPreviewProfileController()
UNREALED_API TSharedPtr< IPreviewProfileController > SEditorViewport::GetPreviewProfileController ()
GetSceneViewport()
TSharedPtr< FSceneViewport > SEditorViewport::GetSceneViewport () inline
Returns
The current FSceneViewport shared pointer
Definition at line 91 of file SEditorViewport.h.
References SceneViewport.
GetShaderPlatformHelper()
UNREALED_API EShaderPlatform SEditorViewport::GetShaderPlatformHelper (const ERHIFeatureLevel::Type InFeatureLevel) const private
Helper function that, for some FeatureLevel argument, will retrieve the required shader platform.
GetTransformToolbarVisibility()
virtual UNREALED_API EVisibility SEditorViewport::GetTransformToolbarVisibility () const virtual
Controls the visibility of the widget transform toolbar, if there is an associated toolbar.
GetViewportClient()
TSharedPtr< FEditorViewportClient > SEditorViewport::GetViewportClient () const inline
Definition at line 86 of file SEditorViewport.h.
References Client.
GetWorld()
virtual UNREALED_API UWorld * SEditorViewport::GetWorld () const protected virtual
Gets the world this viewport is for.
HideInViewportContextMenu()
virtual void SEditorViewport::HideInViewportContextMenu () inline virtual
Definition at line 108 of file SEditorViewport.h.
Invalidate()
UNREALED_API void SEditorViewport::Invalidate ()
Invalidates the viewport to ensure it is redrawn during the next tick.
This is implied every frame while the viewport IsRealtime().
References Invalidate().
Referenced by Invalidate().
Is2DModeVisible()
virtual UNREALED_API bool SEditorViewport::Is2DModeVisible () const protected virtual
Returns
true if the 2d mode widget is visible
IsCoordSystemActive()
virtual UNREALED_API bool SEditorViewport::IsCoordSystemActive (ECoordSystem CoordSystem) const virtual
Returns
true if the specified coordinate system the active one active
References IsCoordSystemActive().
Referenced by IsCoordSystemActive().
IsDistanceBasedCameraSpeedEnabled()
UNREALED_API bool SEditorViewport::IsDistanceBasedCameraSpeedEnabled () static protected
Called to test whether distance-based perspective camera speed scaling is enabled.
IsExposureSettingSelected()
UNREALED_API bool SEditorViewport::IsExposureSettingSelected () const protected
Checks if auto exposure setting is selected.
IsFixedEV100Enabled()
UNREALED_API bool SEditorViewport::IsFixedEV100Enabled () const protected
Called to know whether the fixed EV100 slider is enabled.
IsPreviewingScreenPercentage()
UNREALED_API bool SEditorViewport::IsPreviewingScreenPercentage () const
IsRealtime()
UNREALED_API bool SEditorViewport::IsRealtime () const
Returns
True if the viewport is being updated in realtime
References IsRealtime().
Referenced by IsRealtime().
IsRotateToSurfaceNormalEnabled()
UNREALED_API bool SEditorViewport::IsRotateToSurfaceNormalEnabled () static protected
Called to test whether rotation matching surface normal is enabled or not.
IsShowFlagEnabled()
UNREALED_API bool SEditorViewport::IsShowFlagEnabled (uint32 EngineShowFlagIndex) const protected
Checks if a show flag is enabled in this viewport.
Parameters
EngineShowFlagIndex the ID to check
Returns
true if the show flag is enabled, false otherwise
IsStatCommandVisible()
virtual UNREALED_API bool SEditorViewport::IsStatCommandVisible (FString CommandName) const protected virtual
Checks if Stat command is visible in this viewport.
Parameters
CommandName Name of the command
IsTranslateRotateModeVisible()
virtual UNREALED_API bool SEditorViewport::IsTranslateRotateModeVisible () const protected virtual
Returns
true if the translate/rotate mode widget is visible
IsVisible()
virtual UNREALED_API bool SEditorViewport::IsVisible () const virtual
Returns
True if the viewport is currently visible
Reimplemented in SBasePoseViewport.
References IsVisible().
Referenced by IsVisible().
IsWidgetModeActive()
virtual UNREALED_API bool SEditorViewport::IsWidgetModeActive (UE::Widget::EWidgetMode Mode) const protected virtual
Returns
true if the specified widget mode is active
MakeEditorViewportClient()
virtual TSharedRef< FEditorViewportClient > SEditorViewport::MakeEditorViewportClient () protected pure virtual
Implemented in SAssetEditorViewport, and SBasePoseViewport.
MakeViewportToolbar()
virtual TSharedPtr< SWidget > SEditorViewport::MakeViewportToolbar () inline protected virtual
Reimplemented in SBasePoseViewport.
Definition at line 167 of file SEditorViewport.h.
MarkLegacyToolbarChildAsAutomaticallyUpgradable()
void SEditorViewport::MarkLegacyToolbarChildAsAutomaticallyUpgradable (const TSharedRef< SWidget > & ExpectedChild)
A legacy patch built to allow SCommonEditorViewportToolbarBase to automatically switch to the new viewport style.
This function will go away in the future.
OnCycleCoordinateSystem()
virtual UNREALED_API void SEditorViewport::OnCycleCoordinateSystem () virtual
Cycles between world and local coordinate systems.
References OnCycleCoordinateSystem().
Referenced by OnCycleCoordinateSystem().
OnCycleWidgetMode()
virtual UNREALED_API void SEditorViewport::OnCycleWidgetMode () protected virtual
Moves between widget modes.
OnDecrementPositionGridSize()
virtual void SEditorViewport::OnDecrementPositionGridSize () inline protected virtual
Definition at line 235 of file SEditorViewport.h.
OnDecrementRotationGridSize()
virtual void SEditorViewport::OnDecrementRotationGridSize () inline protected virtual
Definition at line 237 of file SEditorViewport.h.
OnFixedEV100ValueChanged()
UNREALED_API void SEditorViewport::OnFixedEV100ValueChanged (float NewValue) protected
Called when fixed EV100 slider is adjusted.
OnFocusReceived()
virtual UNREALED_API FReply SEditorViewport::OnFocusReceived (const FGeometry & MyGeometry, const FFocusEvent & InFocusEvent) override virtual
Called when focus is given to this widget.
This event does not bubble.
Parameters
MyGeometry The Geometry of the widget receiving the event
InFocusEvent The FocusEvent
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnFocusReceived().
Referenced by OnFocusReceived().
OnFocusViewportToSelection()
virtual void SEditorViewport::OnFocusViewportToSelection () inline protected virtual
Called when the user wants to focus the viewport to the current selection.
Definition at line 262 of file SEditorViewport.h.
OnGetFixedEV100Value()
UNREALED_API float SEditorViewport::OnGetFixedEV100Value () const protected
Called by the fixed EV100 slider to get the fixed EV100 value.
OnGetFocusedViewportIndicatorVisibility()
virtual EVisibility SEditorViewport::OnGetFocusedViewportIndicatorVisibility () const inline protected virtual
Returns
The visibility of the viewport focus indicator.
Definition at line 187 of file SEditorViewport.h.
References EVisibility::Collapsed.
OnGetViewportBorderBrush()
virtual const FSlateBrush * SEditorViewport::OnGetViewportBorderBrush () const inline protected virtual
Definition at line 176 of file SEditorViewport.h.
OnGetViewportBorderColorAndOpacity()
virtual FSlateColor SEditorViewport::OnGetViewportBorderColorAndOpacity () const inline protected virtual
Definition at line 177 of file SEditorViewport.h.
References FLinearColor::Black.
OnGetViewportContentVisibility()
virtual UNREALED_API EVisibility SEditorViewport::OnGetViewportContentVisibility () const protected virtual
Returns
The visibility of widgets in the viewport (e.g, menus). Note this is not the visibility of the scene rendered in the viewport
OnGetWireframeOpacity()
UNREALED_API float SEditorViewport::OnGetWireframeOpacity () const protected
OnIncrementPositionGridSize()
virtual void SEditorViewport::OnIncrementPositionGridSize () inline protected virtual
Changes the snapping grid size.
Definition at line 234 of file SEditorViewport.h.
OnIncrementRotationGridSize()
virtual void SEditorViewport::OnIncrementRotationGridSize () inline protected virtual
Definition at line 236 of file SEditorViewport.h.
OnIsSurfaceSnapEnabled()
UNREALED_API bool SEditorViewport::OnIsSurfaceSnapEnabled () static protected
Called to test whether surface snapping is enabled or not.
OnKeyDown()
virtual UNREALED_API FReply SEditorViewport::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
OnOpenViewportPerformanceEditorPreferences()
UNREALED_API void SEditorViewport::OnOpenViewportPerformanceEditorPreferences ()
OnOpenViewportPerformanceProjectSettings()
UNREALED_API void SEditorViewport::OnOpenViewportPerformanceProjectSettings ()
OnScreenCapture()
virtual UNREALED_API void SEditorViewport::OnScreenCapture () protected virtual
OnScreenCaptureForProjectThumbnail()
virtual UNREALED_API void SEditorViewport::OnScreenCaptureForProjectThumbnail () protected virtual
OnToggleDistanceBasedCameraSpeed()
UNREALED_API void SEditorViewport::OnToggleDistanceBasedCameraSpeed () static protected
Called to enable/disable distance-based perspective camera speed scaling.
OnToggleRealtime()
UNREALED_API void SEditorViewport::OnToggleRealtime ()
Toggles realtime on/off for the viewport.
Slate tick/paint is ensured when realtime is on.
References OnToggleRealtime().
Referenced by OnToggleRealtime().
OnToggleRotateToSurfaceNormal()
UNREALED_API void SEditorViewport::OnToggleRotateToSurfaceNormal () static protected
Called when rotation matching surface normal has been enabled/disabled.
OnToggleStats()
UNREALED_API void SEditorViewport::OnToggleStats () protected
UI Command delegate bindings.
OnToggleSurfaceSnap()
UNREALED_API void SEditorViewport::OnToggleSurfaceSnap () static protected
Called when surface snapping has been enabled/disabled.
OnWireframeOpacityChanged()
UNREALED_API void SEditorViewport::OnWireframeOpacityChanged (float Opacity) protected
Adjustable wireframe opacity.
PopulateViewportOverlays()
virtual void SEditorViewport::PopulateViewportOverlays (TSharedRef< SOverlay > Overlay) inline protected virtual
Definition at line 170 of file SEditorViewport.h.
SetRenderDirectlyToWindow()
UNREALED_API void SEditorViewport::SetRenderDirectlyToWindow (const bool bInRenderDirectlyToWindow)
Sets whether this viewport can render directly to the back buffer.
Advanced use only
Parameters
bInRenderDirectlyToWindow Whether we should be able to render to the back buffer
References SetRenderDirectlyToWindow().
Referenced by SetRenderDirectlyToWindow().
SLATE_ATTRIBUTE()
SEditorViewport::SLATE_ATTRIBUTE (FVector2D , ViewportSize)
SLATE_BEGIN_ARGS()
SEditorViewport::SLATE_BEGIN_ARGS (SEditorViewport) inline
Definition at line 26 of file SEditorViewport.h.
SLATE_END_ARGS()
SEditorViewport::SLATE_END_ARGS ()
SupportsKeyboardFocus()
virtual UNREALED_API bool SEditorViewport::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
References SupportsKeyboardFocus().
Referenced by SupportsKeyboardFocus().
Tick()
virtual UNREALED_API void SEditorViewport::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
References Tick().
Referenced by Tick().
ToggleInViewportContextMenu()
virtual void SEditorViewport::ToggleInViewportContextMenu () inline virtual
Called when the user wants to show the in-viewport context menu.
Definition at line 107 of file SEditorViewport.h.
TogglePreviewingScreenPercentage()
UNREALED_API void SEditorViewport::TogglePreviewingScreenPercentage ()
ToggleShowFlag()
UNREALED_API void SEditorViewport::ToggleShowFlag (uint32 EngineShowFlagIndex) protected
Toggles a show flag in this viewport.
Parameters
EngineShowFlagIndex the ID to toggle
ToggleStatCommand()
virtual UNREALED_API void SEditorViewport::ToggleStatCommand (FString CommandName) protected virtual
Toggles Stat command visibility in this viewport.
Parameters
CommandName Name of the command
UpdateInViewportMenuLocation()
virtual UNREALED_API void SEditorViewport::UpdateInViewportMenuLocation (const FVector2D InLocation) virtual
Field Documentation
ActiveTimerHandle
TWeakPtr<FActiveTimerHandle> SEditorViewport::ActiveTimerHandle private
The handle to the active timer.
Definition at line 334 of file SEditorViewport.h.
AutoUpgradeWidgetChild
TWeakPtr<SWidget> SEditorViewport::AutoUpgradeWidgetChild = nullptr private
For automatic legacy toolbar upgrades.
Registers the child widget to expect in order to allow an automatic upgrade.
Definition at line 340 of file SEditorViewport.h.
bInvalidated
bool SEditorViewport::bInvalidated private
Whether the viewport needs to update, even without input or realtime (e.g.
inertial camera movement)
Definition at line 337 of file SEditorViewport.h.
bLegacyToolbarIsAutomaticallyUpgradable
bool SEditorViewport::bLegacyToolbarIsAutomaticallyUpgradable = false private
A flag indicating that the automatic toolbar upgrade has been approved.
Definition at line 342 of file SEditorViewport.h.
Client
TSharedPtr<FEditorViewportClient> SEditorViewport::Client protected
The client responsible for setting up the scene.
Definition at line 313 of file SEditorViewport.h.
Referenced by GetViewportClient().
CommandList
TSharedPtr<FUICommandList> SEditorViewport::CommandList protected
Commandlist used in the viewport (Maps commands to viewport specific actions)
Definition at line 316 of file SEditorViewport.h.
Referenced by GetCommandList().
InViewportContextMenuLocation
FVector2D SEditorViewport::InViewportContextMenuLocation protected
Definition at line 324 of file SEditorViewport.h.
LastTickTime
double SEditorViewport::LastTickTime protected
The last time the viewport was ticked (for visibility determination)
Definition at line 322 of file SEditorViewport.h.
PreviewProfileController
TSharedPtr<IPreviewProfileController> SEditorViewport::PreviewProfileController protected
Handles Preview Profiles.
Definition at line 319 of file SEditorViewport.h.
SceneViewport
TSharedPtr<FSceneViewport> SEditorViewport::SceneViewport protected
Viewport that renders the scene provided by the viewport client.
Definition at line 307 of file SEditorViewport.h.
Referenced by GetSceneViewport().
ViewportOverlay
TSharedPtr<SOverlay> SEditorViewport::ViewportOverlay protected
Definition at line 304 of file SEditorViewport.h.
ViewportWidget
TSharedPtr<SViewport> SEditorViewport::ViewportWidget protected
Widget where the scene viewport is drawn in.
Definition at line 310 of file SEditorViewport.h.
The documentation for this class was generated from the following file:
SEditorViewport.h