Unreal Engine 5.6 C++ API: UE::FPackageTrailer Class Reference
UE::FPackageTrailer Class Reference
The package trailer should only ever stored the payloads in the workspace domain.
#include "PackageTrailer.h"
Data Structures
struct FFooter
struct FHeader
Public Member Functions
FPackageTrailer ()=default
FPackageTrailer (const FPackageTrailer &Other)=default
FPackageTrailer (FPackageTrailer &&Other)=default
~FPackageTrailer ()=default
int64 FindPayloadOffsetInFile (const FIoHash &Id) const
Returns the absolute offset of the payload in the package file, invalid and virtualized payloads will return INDEX_NONE.
int64 FindPayloadSizeOnDisk (const FIoHash &Id) const
Returns the size of the payload on as stored on disk, invalid and virtualized payloads will return INDEX_NONE.
EPayloadStatus FindPayloadStatus (const FIoHash &Id) const
Attempt to find the status of the given payload.
void ForEachPayload (TFunctionRef< void(const FIoHash &, uint64, uint64, EPayloadAccessMode, UE::Virtualization::EPayloadFilterReason)> Callback) const
Iterates over all payloads in the trailer and invokes the provoided callback on them.
int32 GetNumPayloads (EPayloadFilter Filter) const
Returns the number of payloads that the trailer owns that match the given filter type.
int32 GetNumPayloads (EPayloadStorageType Type) const
Returns the number of payloads that the trailer owns with the given storage type.
FPayloadInfo GetPayloadInfo (const FIoHash &Id) const
TArray< FIoHash > GetPayloads (EPayloadFilter Filter) const
Returns an array of the payloads that match the given filter type.
TArray< FIoHash > GetPayloads (EPayloadStorageType StorageType) const
Returns an array of the payloads with the given storage type.
int64 GetTrailerLength () const
Returns the total size of the of the trailer on disk in bytes.
bool IsValid () const
Returns true if the trailer contains actual data from a package file and false if it just contains the defaults of an unloaded trailer.
FCompressedBuffer LoadLocalPayload (const FIoHash &Id, FArchive &Ar) const
Loads a payload that is stored locally within the package trailer.
FPackageTrailer & operator= (const FPackageTrailer &Other)=default
FPackageTrailer & operator= (FPackageTrailer &&Other)=default
bool TryLoad (FArchive &Ar)
Serializes the trailer from the given archive assuming that the seek position of the archive is already at the correct position for the trailer.
bool TryLoadBackwards (FArchive &Ar)
Serializes the trailer from the given archive BUT assumes that the seek position of the archive is at the end of the trailer and so will attempt to read the footer first and use that to find the start of the trailer in order to read the header.
UE_DEPRECATED (5.3, "FPackageTrailer::IsEnabled will always return true as the system is no longer optional") static bool IsEnabled()
Returns if the feature is enabled or disabled.
bool UpdatePayloadAsVirtualized (const FIoHash &Identifier)
Calling this indicates that the payload has been virtualized and will no longer be stored on disk.
Static Public Member Functions
static bool TryLoadFromArchive (FArchive &Ar, FPackageTrailer &OutTrailer)
Try to load a trailer from a given archive.
static bool TryLoadFromFile (const FString &Path, FPackageTrailer &OutTrailer)
Try to load a trailer from a given file path.
static bool TryLoadFromPackage (const FPackagePath &PackagePath, FPackageTrailer &OutTrailer)
Try to load a trailer from a given package path.
Private Member Functions
FFooter CreateFooter () const
Create a valid footer for the current trailer.
Private Attributes
FHeader Header
The header of the trailer.
int64 TrailerPositionInFile = INDEX_NONE
Where in the workspace domain package file the trailer is located.
Friends
class FPackageTrailerBuilder
Detailed Description
The package trailer should only ever stored the payloads in the workspace domain.
If the package trailer is in the editor domain then it's values should be valid, but when loading non-virtualized payloads they need to come from the workspace domain package.
Definition at line 406 of file PackageTrailer.h.
Constructor & Destructor Documentation
FPackageTrailer() [1/3]
UE::FPackageTrailer::FPackageTrailer () default
Referenced by FPackageTrailer(), FPackageTrailer(), operator=(), operator=(), TryLoadFromArchive(), TryLoadFromFile(), and TryLoadFromPackage().
~FPackageTrailer()
UE::FPackageTrailer::~FPackageTrailer () default
FPackageTrailer() [2/3]
UE::FPackageTrailer::FPackageTrailer (const FPackageTrailer & Other) default
References FPackageTrailer(), and Other.
FPackageTrailer() [3/3]
UE::FPackageTrailer::FPackageTrailer (FPackageTrailer && Other) default
References FPackageTrailer(), and Other.
Member Function Documentation
CreateFooter()
FFooter UE::FPackageTrailer::CreateFooter () const private
Create a valid footer for the current trailer.
FindPayloadOffsetInFile()
int64 UE::FPackageTrailer::FindPayloadOffsetInFile (const FIoHash & Id) const nodiscard
Returns the absolute offset of the payload in the package file, invalid and virtualized payloads will return INDEX_NONE.
FindPayloadSizeOnDisk()
int64 UE::FPackageTrailer::FindPayloadSizeOnDisk (const FIoHash & Id) const nodiscard
Returns the size of the payload on as stored on disk, invalid and virtualized payloads will return INDEX_NONE.
FindPayloadStatus()
EPayloadStatus UE::FPackageTrailer::FindPayloadStatus (const FIoHash & Id) const nodiscard
Attempt to find the status of the given payload.
@See EPayloadStatus
ForEachPayload()
void UE::FPackageTrailer::ForEachPayload (TFunctionRef< void(const FIoHash &, uint64, uint64, EPayloadAccessMode, UE::Virtualization::EPayloadFilterReason)> Callback) const
Iterates over all payloads in the trailer and invokes the provoided callback on them.
GetNumPayloads() [1/2]
int32 UE::FPackageTrailer::GetNumPayloads (EPayloadFilter Filter) const nodiscard
Returns the number of payloads that the trailer owns that match the given filter type.
@See EPayloadFilter
References Filter.
GetNumPayloads() [2/2]
int32 UE::FPackageTrailer::GetNumPayloads (EPayloadStorageType Type) const nodiscard
Returns the number of payloads that the trailer owns with the given storage type.
@See EPayloadStoragetype
GetPayloadInfo()
FPayloadInfo UE::FPackageTrailer::GetPayloadInfo (const FIoHash & Id) const nodiscard
GetPayloads() [1/2]
TArray< FIoHash > UE::FPackageTrailer::GetPayloads (EPayloadFilter Filter) const nodiscard
Returns an array of the payloads that match the given filter type.
@See EPayloadFilter
References Filter.
GetPayloads() [2/2]
TArray< FIoHash > UE::FPackageTrailer::GetPayloads (EPayloadStorageType StorageType) const nodiscard
Returns an array of the payloads with the given storage type.
@See EPayloadStoragetype
GetTrailerLength()
int64 UE::FPackageTrailer::GetTrailerLength () const nodiscard
Returns the total size of the of the trailer on disk in bytes.
IsValid()
bool UE::FPackageTrailer::IsValid () const inline nodiscard
Returns true if the trailer contains actual data from a package file and false if it just contains the defaults of an unloaded trailer.
Definition at line 442 of file PackageTrailer.h.
References Header, and UE::FPackageTrailer::FHeader::HeaderTag.
LoadLocalPayload()
FCompressedBuffer UE::FPackageTrailer::LoadLocalPayload (const FIoHash & Id, FArchive & Ar) const nodiscard
Loads a payload that is stored locally within the package trailer.
Payloads stored externally (either referenced or virtualized) will not load.
Parameters
Id The payload to load
Ar The archive from which the payload trailer was also loaded from
Returns
The payload in the form of a FCompressedBuffer. If the payload does not exist in the trailer or is not stored locally in the trailer then the FCompressedBuffer will be null.
References Ar.
operator=() [1/2]
FPackageTrailer & UE::FPackageTrailer::operator= (const FPackageTrailer & Other) default
References FPackageTrailer(), and Other.
operator=() [2/2]
FPackageTrailer & UE::FPackageTrailer::operator= (FPackageTrailer && Other) default
References FPackageTrailer(), and Other.
TryLoad()
bool UE::FPackageTrailer::TryLoad (FArchive & Ar) nodiscard
Serializes the trailer from the given archive assuming that the seek position of the archive is already at the correct position for the trailer.
Parameters
Ar The archive to load the trailer from
Returns
True if a valid trailer was found and was able to be loaded, otherwise false. If the trailer was found but failed to load then the archive will be set to the error state.
References Ar.
TryLoadBackwards()
bool UE::FPackageTrailer::TryLoadBackwards (FArchive & Ar) nodiscard
Serializes the trailer from the given archive BUT assumes that the seek position of the archive is at the end of the trailer and so will attempt to read the footer first and use that to find the start of the trailer in order to read the header.
Parameters
Ar The archive to load the trailer from
Returns
True if a valid trailer was found and was able to be loaded, otherwise false. If the trailer was found but failed to load then the archive will be set to the error state.
References Ar.
TryLoadFromArchive()
bool UE::FPackageTrailer::TryLoadFromArchive (FArchive & Ar, FPackageTrailer & OutTrailer) static nodiscard
Try to load a trailer from a given archive.
Assumes that the trailer is at the end of the archive
References FPackageTrailer(), and Ar.
TryLoadFromFile()
bool UE::FPackageTrailer::TryLoadFromFile (const FString & Path, FPackageTrailer & OutTrailer) static nodiscard
Try to load a trailer from a given file path.
References FPackageTrailer(), and Path.
TryLoadFromPackage()
bool UE::FPackageTrailer::TryLoadFromPackage (const FPackagePath & PackagePath, FPackageTrailer & OutTrailer) static nodiscard
Try to load a trailer from a given package path.
Note that it will always try to load the trailer from the workspace domain
References FPackageTrailer(), and PackagePath.
UE_DEPRECATED()
UE::FPackageTrailer::UE_DEPRECATED (5. 3, "FPackageTrailer::IsEnabled will always return true as the system is no longer optional") inline nodiscard
Returns if the feature is enabled or disabled.
Note that this is for development purposes only and should ship as always enabled!
Definition at line 414 of file PackageTrailer.h.
UpdatePayloadAsVirtualized()
bool UE::FPackageTrailer::UpdatePayloadAsVirtualized (const FIoHash & Identifier) nodiscard
Calling this indicates that the payload has been virtualized and will no longer be stored on disk.
Parameters
Identifier The payload that has been virtualized
Returns
True if the payload was in the trailer, otherwise false
Friends And Related Symbol Documentation
FPackageTrailerBuilder
friend class FPackageTrailerBuilder friend
Definition at line 570 of file PackageTrailer.h.
References FPackageTrailerBuilder.
Referenced by FPackageTrailerBuilder.
Field Documentation
Header
FHeader UE::FPackageTrailer::Header private
The header of the trailer.
Since this contains the lookup table for payloads we keep this in memory once the trailer has been loaded. There is no need to keep the footer in memory
Definition at line 581 of file PackageTrailer.h.
Referenced by IsValid(), and UE::FPackageTrailer::FHeader::operator<<.
TrailerPositionInFile
int64 UE::FPackageTrailer::TrailerPositionInFile = INDEX_NONE private
Where in the workspace domain package file the trailer is located.
Definition at line 576 of file PackageTrailer.h.
The documentation for this class was generated from the following file:
PackageTrailer.h