Unreal Engine 5.6 C++ API: FNetworkPredictionSerialization Struct Reference
FNetworkPredictionSerialization Struct Reference
#include "NetworkPredictionSerialization.h"
Public Types
enum { MAX_FRAME_WRITE = 1 << NUM_BITS_FRAME }
enum { NUM_BITS_FRAME = 8 }
enum { FRAME_ERROR_THRESHOLD = MAX_FRAME_WRITE / 2 }
Static Public Member Functions
static int32 ReadCompressedFrame (FArchive &Ar, int32 RelativeFrame)
static void SerializeDeltaMS (FArchive &Ar, int32 &DeltaTimeMS)
static int32 SerializeFrame (FArchive &Ar, int32 Frame, int32 RelativeFrame)
static void SerializeTimeMS (FArchive &Ar, int32 &TimestampMS)
static void WriteCompressedFrame (FArchive &Ar, int32 Frame)
Detailed Description
Definition at line 29 of file NetworkPredictionSerialization.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MAX_FRAME_WRITE
Definition at line 38 of file NetworkPredictionSerialization.h.
anonymous enum
anonymous enum
Enumerator
NUM_BITS_FRAME
Definition at line 35 of file NetworkPredictionSerialization.h.
anonymous enum
anonymous enum
Enumerator
FRAME_ERROR_THRESHOLD
Definition at line 43 of file NetworkPredictionSerialization.h.
Member Function Documentation
ReadCompressedFrame()
int32 FNetworkPredictionSerialization::ReadCompressedFrame (FArchive & Ar, int32 RelativeFrame) inline static
Definition at line 67 of file NetworkPredictionSerialization.h.
References Ar.
Referenced by TFixedTickReplicator_AP< InModelDef >::NetRecv(), TFixedTickReplicator_Server< InModelDef >::NetRecv(), TFixedTickReplicator_SP< InModelDef >::NetRecv(), TIndependentTickReplicator_AP< InModelDef >::NetRecv(), and TIndependentTickReplicator_Server< InModelDef >::NetRecv().
SerializeDeltaMS()
void FNetworkPredictionSerialization::SerializeDeltaMS (FArchive & Ar, int32 & DeltaTimeMS) inline static
Definition at line 85 of file NetworkPredictionSerialization.h.
References Ar.
Referenced by TIndependentTickReplicator_Server< InModelDef >::EatCmd(), TIndependentTickReplicator_Server< InModelDef >::NetRecv(), and TIndependentTickReplicator_Server< InModelDef >::NetSend().
SerializeFrame()
int32 FNetworkPredictionSerialization::SerializeFrame (FArchive & Ar, int32 Frame, int32 RelativeFrame) inline static
Definition at line 46 of file NetworkPredictionSerialization.h.
References Ar, MakeRelative(), and MAX_FRAME_WRITE.
SerializeTimeMS()
void FNetworkPredictionSerialization::SerializeTimeMS (FArchive & Ar, int32 & TimestampMS) inline static
Definition at line 78 of file NetworkPredictionSerialization.h.
References Ar.
Referenced by TIndependentTickReplicator_AP< InModelDef >::NetRecv(), TIndependentTickReplicator_SP< InModelDef >::NetRecv(), TIndependentTickReplicator_AP< InModelDef >::NetSend(), and TIndependentTickReplicator_SP< InModelDef >::NetSend().
WriteCompressedFrame()
void FNetworkPredictionSerialization::WriteCompressedFrame (FArchive & Ar, int32 Frame) inline static
Definition at line 58 of file NetworkPredictionSerialization.h.
References Ar.
Referenced by TFixedTickReplicator_AP< InModelDef >::NetSend(), TFixedTickReplicator_Server< InModelDef >::NetSend(), TFixedTickReplicator_SP< InModelDef >::NetSend(), TIndependentTickReplicator_AP< InModelDef >::NetSend(), and TIndependentTickReplicator_Server< InModelDef >::NetSend().
The documentation for this struct was generated from the following file:
NetworkPredictionSerialization.h