Unreal Engine 5.6 C++ API: SharedBuffer.h File Reference
SharedBuffer.h File Reference
#include "Containers/ContainersFwd.h"
#include "CoreTypes.h"
#include "Memory/MemoryFwd.h"
#include "Memory/MemoryView.h"
#include "Misc/AssertionMacros.h"
#include "Misc/EnumClassFlags.h"
#include "Templates/Invoke.h"
#include "Templates/TypeHash.h"
#include "Templates/UnrealTemplate.h"
#include <atomic>
#include <type_traits>
Data Structures
class FBufferOwner
A reference-counted owner for a buffer, which is a raw pointer and size.
class FSharedBuffer
A reference to a shared-ownership immutable buffer.
class FUniqueBuffer
A reference to a single-ownership mutable buffer.
class FWeakSharedBuffer
A weak reference to a shared-ownership immutable buffer.
struct TIsWeakPointerType< FWeakSharedBuffer >
struct TIsZeroConstructType< FSharedBuffer >
struct TIsZeroConstructType< FUniqueBuffer >
struct TIsZeroConstructType< FWeakSharedBuffer >
struct UE::SharedBuffer::Private::FSharedOps
struct UE::SharedBuffer::Private::FWeakOps
class UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >
class UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >
class UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::SharedBuffer
namespace UE::SharedBuffer::Private
Functions
ENUM_CLASS_FLAGS (FBufferOwner::EBufferOwnerFlags)
template<typename T, typename Allocator>
FSharedBuffer MakeSharedBufferFromArray (TArray< T, Allocator > &&Array)
Construct a shared buffer by taking ownership of an array.
template<typename T, typename Allocator>
FUniqueBuffer MakeUniqueBufferFromArray (TArray< T, Allocator > &&Array)
Construct a unique buffer by taking ownership of an array.
Function Documentation
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (FBufferOwner::EBufferOwnerFlags)
MakeSharedBufferFromArray()
template<typename T, typename Allocator> FSharedBuffer MakeSharedBufferFromArray (TArray< T, Allocator > && Array) inline nodiscard
Construct a shared buffer by taking ownership of an array.
Definition at line 915 of file SharedBuffer.h.
References Array, and MoveTemp().
Referenced by FShaderCode::FinalizeShaderCode().
MakeUniqueBufferFromArray()
template<typename T, typename Allocator> FUniqueBuffer MakeUniqueBufferFromArray (TArray< T, Allocator > && Array) inline nodiscard
Construct a unique buffer by taking ownership of an array.
Definition at line 908 of file SharedBuffer.h.
References Array, and MoveTemp().