Unreal Engine 5.6 C++ API: FCoreRedirectObjectName Struct Reference
FCoreRedirectObjectName Struct Reference
An object path extracted into component names for matching.
#include "CoreRedirects.h"
Public Types
enum class EMatchFlags {
None = 0 , DisallowPartialLHSMatch = (1 << 0) , AllowPartialRHSMatch = (1 << 1) , CheckSubString = (1 << 2) ,
CheckPrefix = (1 << 3) , CheckSuffix = (1 << 4)
}
Flags for the Matches function.
Public Member Functions
FCoreRedirectObjectName ()=default
Default to invalid names.
FCoreRedirectObjectName (const class UObject *Object)
Construct from object in memory.
FCoreRedirectObjectName (const FSoftObjectPath &SoftObjectPath)
FCoreRedirectObjectName (const FString &InString)
FCoreRedirectObjectName (const FTopLevelAssetPath &TopLevelAssetPath)
FCoreRedirectObjectName (FName InObjectName, FName InOuterName, FName InPackageName)
Construct from FNames that are already expanded.
void AppendHash (FBlake3 &Hasher) const
Update Hasher with all fields from this.
int Compare (const FCoreRedirectObjectName &Other) const
Compares the two names lexically, returning -,0,+.
FName GetSearchKey (ECoreRedirectFlags Type) const
Returns the name used as the key into the acceleration map.
bool HasValidCharacters (ECoreRedirectFlags Type) const
Returns true if all names have valid characters.
bool IsValid () const
Returns true if this refers to an actual object.
bool Matches (const FCoreRedirectObjectName &Other, EMatchFlags MatchFlags=EMatchFlags::None) const
Returns true if the passed in name matches requirements.
int32 MatchScore (const FCoreRedirectObjectName &Other, ECoreRedirectFlags RedirectFlags, ECoreRedirectMatchFlags MatchFlags) const
Returns integer of degree of match.
bool operator!= (const FCoreRedirectObjectName &Other) const
bool operator== (const FCoreRedirectObjectName &Other) const
Checks for exact equality.
void Reset ()
Sets back to invalid state.
FString ToString () const
Creates FString version.
void UnionFieldsInline (const FCoreRedirectObjectName &Other)
Fills in any empty fields on this with the corresponding fields from Other.
Static Public Member Functions
static FCoreRedirectObjectName AppendObjectName (const FCoreRedirectObjectName &Parent, FName ObjectName)
Given parent FCoreRedirectObjectName and FName of a child under it, return child's FCoreRedirectObjectName.
static FString CombineNames (FName NewName, FName NewOuter, FName NewPackage)
Turn it back into an FString.
static bool ExpandNames (const FStringView FullString, FName &OutName, FName &OutOuter, FName &OutPackage)
Expand OldName/NewName as needed.
static FCoreRedirectObjectName GetParent (const FCoreRedirectObjectName &Child)
Given a child FCoreRedirectObjectName, return its parent's FCoreRedirectObjectName.
Data Fields
FName ObjectName
Raw name of object.
FName OuterName
String of outer chain, may be empty.
FName PackageName
Package this was in before, may be extracted out of OldName.
Friends
uint32 GetTypeHash (const FCoreRedirectObjectName &RedirectName)
Detailed Description
An object path extracted into component names for matching.
TODO merge with FSoftObjectPath?
Definition at line 87 of file CoreRedirects.h.
Member Enumeration Documentation
EMatchFlags
enum class FCoreRedirectObjectName::EMatchFlags strong
Flags for the Matches function.
These flags overlap but are lower-level than ECoreRedirectMatchFlags.
Enumerator
None
DisallowPartialLHSMatch
Do not match if LHS (aka *this) has null fields that RHS (aka Other) does not.
Default is to match.
AllowPartialRHSMatch
Match even if RHS (aka Other) has null fields that LHS (aka *this) does not.
Default is to NOT match.
CheckSubString
LHS fields (aka *this) are searchstrings; RHS (aka Other) fields are searched for that substring.
Without this flag a Match returns true if and only if the complete string matches: LHS == RHS. With this flag a Match returns true if and only if RHS.Contains(LHS). This flag makes the match more expensive and should be avoided when possible. This flag forces partial LHS matches, and will ignore the DisallowPartialLHSMatch flag when matching.
CheckPrefix
LHS fields (aka *this) are searchstrings; RHS (aka Other) fields are searched for that prefix.
Without this flag a Match returns true if and only if the complete string matches: LHS == RHS. With this flag a Match returns true if and only if RHS.StartsWith(LHS). This flag makes the match more expensive and should be avoided when possible. This flag forces partial LHS matches, and will ignore the DisallowPartialLHSMatch flag when matching.
CheckSuffix
LHS fields (aka *this) are searchstrings; RHS (aka Other) fields are searched for that suffix.
Without this flag a Match returns true if and only if the complete string matches: LHS == RHS. With this flag a Match returns true if and only if RHS.EndsWith(LHS). This flag makes the match more expensive and should be avoided when possible. This flag forces partial LHS matches, and will ignore the DisallowPartialLHSMatch flag when matching.
Definition at line 138 of file CoreRedirects.h.
Constructor & Destructor Documentation
FCoreRedirectObjectName() [1/6]
FCoreRedirectObjectName::FCoreRedirectObjectName () default
Default to invalid names.
Referenced by AppendObjectName(), CombineNames(), Compare(), GetParent(), GetTypeHash, Matches(), MatchScore(), operator!=(), operator==(), and UnionFieldsInline().
FCoreRedirectObjectName() [2/6]
FCoreRedirectObjectName::FCoreRedirectObjectName (FName InObjectName, FName InOuterName, FName InPackageName) inline
Construct from FNames that are already expanded.
Definition at line 102 of file CoreRedirects.h.
References ObjectName, OuterName, and PackageName.
FCoreRedirectObjectName() [3/6]
FCoreRedirectObjectName::FCoreRedirectObjectName (const FTopLevelAssetPath & TopLevelAssetPath)
FCoreRedirectObjectName() [4/6]
FCoreRedirectObjectName::FCoreRedirectObjectName (const FSoftObjectPath & SoftObjectPath)
References SoftObjectPath.
FCoreRedirectObjectName() [5/6]
FCoreRedirectObjectName::FCoreRedirectObjectName (const FString & InString)
FCoreRedirectObjectName() [6/6]
FCoreRedirectObjectName::FCoreRedirectObjectName (const class UObject * Object)
Construct from object in memory.
References Object.
Member Function Documentation
AppendHash()
void FCoreRedirectObjectName::AppendHash (FBlake3 & Hasher) const
Update Hasher with all fields from this.
AppendObjectName()
FCoreRedirectObjectName FCoreRedirectObjectName::AppendObjectName (const FCoreRedirectObjectName & Parent, FName ObjectName) static
Given parent FCoreRedirectObjectName and FName of a child under it, return child's FCoreRedirectObjectName.
References FCoreRedirectObjectName(), ObjectName, and Parent.
CombineNames()
FString FCoreRedirectObjectName::CombineNames (FName NewName, FName NewOuter, FName NewPackage) static
Turn it back into an FString.
References FCoreRedirectObjectName().
Compare()
int FCoreRedirectObjectName::Compare (const FCoreRedirectObjectName & Other) const
Compares the two names lexically, returning -,0,+.
References FCoreRedirectObjectName(), and Other.
ExpandNames()
bool FCoreRedirectObjectName::ExpandNames (const FStringView FullString, FName & OutName, FName & OutOuter, FName & OutPackage) static
Expand OldName/NewName as needed.
GetParent()
FCoreRedirectObjectName FCoreRedirectObjectName::GetParent (const FCoreRedirectObjectName & Child) static
Given a child FCoreRedirectObjectName, return its parent's FCoreRedirectObjectName.
If the input has no parent (empty or is package with no outer), returns an empty FCoreRedirectObjectName.
References FCoreRedirectObjectName(), and Child.
GetSearchKey()
FName FCoreRedirectObjectName::GetSearchKey (ECoreRedirectFlags Type) const
Returns the name used as the key into the acceleration map.
HasValidCharacters()
bool FCoreRedirectObjectName::HasValidCharacters (ECoreRedirectFlags Type) const
Returns true if all names have valid characters.
IsValid()
bool FCoreRedirectObjectName::IsValid () const inline
Returns true if this refers to an actual object.
Definition at line 183 of file CoreRedirects.h.
References ObjectName, and PackageName.
Matches()
bool FCoreRedirectObjectName::Matches (const FCoreRedirectObjectName & Other, EMatchFlags MatchFlags = EMatchFlags::None) const
Returns true if the passed in name matches requirements.
References FCoreRedirectObjectName(), None, and Other.
MatchScore()
int32 FCoreRedirectObjectName::MatchScore (const FCoreRedirectObjectName & Other, ECoreRedirectFlags RedirectFlags, ECoreRedirectMatchFlags MatchFlags) const
Returns integer of degree of match.
0 if doesn't match at all, higher integer for better matches
References FCoreRedirectObjectName(), and Other.
operator!=()
bool FCoreRedirectObjectName::operator!= (const FCoreRedirectObjectName & Other) const inline
Definition at line 129 of file CoreRedirects.h.
References FCoreRedirectObjectName(), and Other.
operator==()
bool FCoreRedirectObjectName::operator== (const FCoreRedirectObjectName & Other) const inline
Checks for exact equality.
Definition at line 124 of file CoreRedirects.h.
References FCoreRedirectObjectName(), ObjectName, Other, OuterName, and PackageName.
Reset()
void FCoreRedirectObjectName::Reset ()
Sets back to invalid state.
ToString()
FString FCoreRedirectObjectName::ToString () const
Creates FString version.
Referenced by RigVMTypeUtils::FindObjectFromCPPTypeObjectPath().
UnionFieldsInline()
void FCoreRedirectObjectName::UnionFieldsInline (const FCoreRedirectObjectName & Other)
Fills in any empty fields on this with the corresponding fields from Other.
References FCoreRedirectObjectName(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FCoreRedirectObjectName & RedirectName) friend
Definition at line 188 of file CoreRedirects.h.
References FCoreRedirectObjectName(), GetTypeHash, HashCombine(), ObjectName, OuterName, and PackageName.
Referenced by GetTypeHash.
Field Documentation
ObjectName
FName FCoreRedirectObjectName::ObjectName
Raw name of object.
Definition at line 90 of file CoreRedirects.h.
Referenced by FCoreRedirectObjectName(), AppendObjectName(), RigVMTypeUtils::FindObjectGlobally(), GetTypeHash, IsValid(), and operator==().
OuterName
FName FCoreRedirectObjectName::OuterName
String of outer chain, may be empty.
Definition at line 93 of file CoreRedirects.h.
Referenced by FCoreRedirectObjectName(), GetTypeHash, and operator==().
PackageName
FName FCoreRedirectObjectName::PackageName
Package this was in before, may be extracted out of OldName.
Definition at line 96 of file CoreRedirects.h.
Referenced by FCoreRedirectObjectName(), RigVMTypeUtils::FindObjectGlobally(), GetTypeHash, IsValid(), and operator==().
The documentation for this struct was generated from the following file:
CoreRedirects.h