Unreal Engine 5.6 C++ API: FCachedOSPageAllocator Struct Reference
FCachedOSPageAllocator Struct Reference
#include "CachedOSPageAllocator.h"
Data Structures
struct FFreePageBlock
Protected Member Functions
void * AllocateImpl (SIZE_T Size, uint32 CachedByteLimit, FFreePageBlock *First, FFreePageBlock *Last, uint32 &FreedPageBlocksNum, SIZE_T &CachedTotal, UE::FPlatformRecursiveMutex *Mutex)
void FreeAllImpl (FFreePageBlock *First, uint32 &FreedPageBlocksNum, SIZE_T &CachedTotal, UE::FPlatformRecursiveMutex *Mutex)
void FreeImpl (void *Ptr, SIZE_T Size, uint32 NumCacheBlocks, uint32 CachedByteLimit, FFreePageBlock *First, uint32 &FreedPageBlocksNum, SIZE_T &CachedTotal, UE::FPlatformRecursiveMutex *Mutex, bool ThreadIsTimeCritical)
Static Protected Member Functions
static bool IsOSAllocation (SIZE_T Size, uint32 CachedByteLimit)
Detailed Description
Definition at line 10 of file CachedOSPageAllocator.h.
Member Function Documentation
AllocateImpl()
void * FCachedOSPageAllocator::AllocateImpl (SIZE_T Size, uint32 CachedByteLimit, FFreePageBlock * First, FFreePageBlock * Last, uint32 & FreedPageBlocksNum, SIZE_T & CachedTotal, UE::FPlatformRecursiveMutex * Mutex) protected
References First, Last, and TSequenceHistory< HistorySize >::Size.
Referenced by TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::Allocate().
FreeAllImpl()
void FCachedOSPageAllocator::FreeAllImpl (FFreePageBlock * First, uint32 & FreedPageBlocksNum, SIZE_T & CachedTotal, UE::FPlatformRecursiveMutex * Mutex) protected
References First.
Referenced by TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::FreeAll().
FreeImpl()
void FCachedOSPageAllocator::FreeImpl (void * Ptr, SIZE_T Size, uint32 NumCacheBlocks, uint32 CachedByteLimit, FFreePageBlock * First, uint32 & FreedPageBlocksNum, SIZE_T & CachedTotal, UE::FPlatformRecursiveMutex * Mutex, bool ThreadIsTimeCritical) protected
References First, and TSequenceHistory< HistorySize >::Size.
Referenced by TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::Free().
IsOSAllocation()
bool FCachedOSPageAllocator::IsOSAllocation (SIZE_T Size, uint32 CachedByteLimit) inline static protected
Definition at line 29 of file CachedOSPageAllocator.h.
References FGenericPlatformMemory::BinnedPlatformHasMemoryPoolForThisSize(), and TSequenceHistory< HistorySize >::Size.
Referenced by TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::IsOSAllocation().
The documentation for this struct was generated from the following file:
CachedOSPageAllocator.h