Unreal Engine 5.6 C++ API: FSlateIconFinder Class Reference
FSlateIconFinder Class Reference
Class used for finding icons within a registered set of styles.
#include "SlateIconFinder.h"
Static Public Member Functions
static const FSlateBrush * FindCustomIconBrushForClass (const UStruct *InStruct, const TCHAR *InStyleBasePath, const FName &InDefaultName=FName())
Find a custom icon to use for the supplied struct, according to the specified base style.
static FSlateIcon FindCustomIconForClass (const UStruct *InStruct, const TCHAR *InStyleBasePath, const FName &InDefaultName=FName())
Find a custom icon to use for the supplied struct, according to the specified base style.
static FSlateIcon FindIcon (const FName &InIconName)
Find the first occurrence of a brush represented by the specified IconName in any of the registered style sets.
static const FSlateBrush * FindIconBrushForClass (const UStruct *InStruct, const FName &InDefaultName=FName())
Find a slate brush to use for the supplied struct's icon.
static FSlateIcon FindIconForClass (const UStruct *InStruct, const FName &InDefaultName=FName())
Find the icon to use for the supplied struct.
Detailed Description
Class used for finding icons within a registered set of styles.
Definition at line 11 of file SlateIconFinder.h.
Member Function Documentation
FindCustomIconBrushForClass()
const FSlateBrush * FSlateIconFinder::FindCustomIconBrushForClass (const UStruct * InStruct, const TCHAR * InStyleBasePath, const FName & InDefaultName = FName()) inline static
Find a custom icon to use for the supplied struct, according to the specified base style.
Parameters
InStruct The struct to locate an icon for
InStyleBasePath Style base path to use for the search (e.g. ClassIcon, or ClassThumbnail)
InDefaultName The default icon name to use, if no specialized icon could be found
Returns
A slate brush, or nullptr if no icon was found
Definition at line 54 of file SlateIconFinder.h.
References FindCustomIconForClass(), and FSlateIcon::GetIcon().
Referenced by FClassIconFinder::FindThumbnailForClass().
FindCustomIconForClass()
FSlateIcon FSlateIconFinder::FindCustomIconForClass (const UStruct * InStruct, const TCHAR * InStyleBasePath, const FName & InDefaultName = FName()) static
Find a custom icon to use for the supplied struct, according to the specified base style.
Parameters
InStruct The struct to locate an icon for
InStyleBasePath Style base path to use for the search (e.g. ClassIcon, or ClassThumbnail)
InDefaultName The default icon name to use, if no specialized icon could be found
Returns
An FSlateIcon structure defining the struct's icon
Referenced by FindCustomIconBrushForClass().
FindIcon()
FSlateIcon FSlateIconFinder::FindIcon (const FName & InIconName) static
Find the first occurrence of a brush represented by the specified IconName in any of the registered style sets.
Parameters
InIconName The fully qualified style name of the icon to find
Returns
An FSlateIcon structure
FindIconBrushForClass()
const FSlateBrush * FSlateIconFinder::FindIconBrushForClass (const UStruct * InStruct, const FName & InDefaultName = FName()) inline static
Find a slate brush to use for the supplied struct's icon.
Parameters
InStruct The struct to locate an icon for
InDefaultName The default icon name to use, if no specialized icon could be found
Returns
A slate brush, or nullptr if no icon was found
Definition at line 41 of file SlateIconFinder.h.
References FindIconForClass(), and FSlateIcon::GetIcon().
Referenced by FClassDragDropOp::GetDefaultDecorator().
FindIconForClass()
FSlateIcon FSlateIconFinder::FindIconForClass (const UStruct * InStruct, const FName & InDefaultName = FName()) static
Find the icon to use for the supplied struct.
Parameters
InStruct The struct to locate an icon for
InDefaultName The default icon name to use, if no specialized icon could be found
Returns
An FSlateIcon structure defining the struct's icon
Referenced by FindIconBrushForClass().
The documentation for this class was generated from the following file:
SlateIconFinder.h