Unreal Engine 5.6 C++ API: FShaderParametersMetadataRegistration Class Reference
FShaderParametersMetadataRegistration Class Reference
#include "ShaderParameterMacros.h"
Public Member Functions
FShaderParametersMetadataRegistration (TFunctionRef< const FShaderParametersMetadata *()> LazyShaderParametersMetadataAccessor)
Static Public Member Functions
static RENDERCORE_API void CommitAll ()
static RENDERCORE_API TArray< const FShaderParametersMetadataRegistration * > & GetInstances ()
static RENDERCORE_API bool IsReadyForRegistration ()
Private Attributes
TFunctionRef< const FShaderParametersMetadata *()> LazyShaderParametersMetadataAccessor
Detailed Description
Definition at line 1523 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
FShaderParametersMetadataRegistration()
FShaderParametersMetadataRegistration::FShaderParametersMetadataRegistration (TFunctionRef< const FShaderParametersMetadata *()> LazyShaderParametersMetadataAccessor) inline
Definition at line 1526 of file ShaderParameterMacros.h.
References GetInstances(), and LazyShaderParametersMetadataAccessor.
Member Function Documentation
CommitAll()
RENDERCORE_API void FShaderParametersMetadataRegistration::CommitAll () static
GetInstances()
RENDERCORE_API TArray< const FShaderParametersMetadataRegistration * > & FShaderParametersMetadataRegistration::GetInstances () static
Referenced by FShaderParametersMetadataRegistration().
IsReadyForRegistration()
RENDERCORE_API bool FShaderParametersMetadataRegistration::IsReadyForRegistration () static
Field Documentation
LazyShaderParametersMetadataAccessor
TFunctionRef<const FShaderParametersMetadata* ()> FShaderParametersMetadataRegistration::LazyShaderParametersMetadataAccessor private
Definition at line 1539 of file ShaderParameterMacros.h.
Referenced by FShaderParametersMetadataRegistration().
The documentation for this class was generated from the following file:
ShaderParameterMacros.h