Unreal Engine 5.6 C++ API: FBlueprintActionMenuBuilder Struct Reference
FBlueprintActionMenuBuilder Struct Reference
Responsible for constructing a list of viable blueprint actions.
#include "BlueprintActionMenuBuilder.h"
Public Types
enum EConfigFlags { UseTimeSlicing = (1<<0) , DefaultConfig = 0 }
Flags used to configure the builder.
enum ESectionFlag { ConsolidatePropertyActions = (1<<0) , ConsolidateBoundActions = (1<<1) , FlattenCategoryHierarcy = (1<<2) }
Flags used to customize specific sections of the menu.
Public Member Functions
FBlueprintActionMenuBuilder (EConfigFlags Flags=EConfigFlags::DefaultConfig)
Default constructor.
void AddMenuSection (FBlueprintActionFilter const &Filter, FText const &Heading=FText::GetEmpty(), int32 MenuOrder=0, uint32 const Flags=0)
Some action menus require multiple sections.
virtual void Empty () override
Clears the action entries.
int32 GetNumPendingActions () const
Returns the current number of actions that are still pending.
float GetPendingActionsProgress () const
Returns the normalized completion state when processing pending actions (e.g.
bool ProcessPendingActions ()
Processes any actions that may be added asynchronously or across multiple frames.
void RebuildActionList ()
Regenerates the entire menu list from the cached menu sections.
UE_DEPRECATED (5.2, "The action filter now stores a reference to the authoritative editor context. Please use the default constructor instead.") FBlueprintActionMenuBuilder(TWeakPtr< FBlueprintEditor > BlueprintEditorPtr)
Public Member Functions inherited from FGraphActionListBuilderBase
FGraphActionListBuilderBase ()
virtual ~FGraphActionListBuilderBase ()
Virtual destructor.
virtual void AddAction (const TSharedPtr< FEdGraphSchemaAction > &NewAction)
Adds an action entry containing a single action.
void Append (FGraphActionListBuilderBase &Other)
Appends all the action entries from a different graph action builder.
template<typename NodeType>
NodeType * CreateTemplateNode (UClass *Class=NodeType::StaticClass())
int32 GetNumActions () const
Returns the current number of entries.
TSharedPtr< FEdGraphSchemaAction > & GetSchemaAction (int32 Index)
Returns the specified entry.
class UE_DEPRECATED (5.5, "ActionGroup has been deprecated - operate only on TSharedPtr<FEdGraphSchemaAction> or const FEdGraphSchemaAction& as appropriate") ActionGroup
A single entry in the list - can contain multiple actions.
UE_DEPRECATED (5.5, "Collections of Action lists were ambiguous and unused - make a compound FEdGraphSchemaAction and Add it") 1 virtual void AddActionList(const TArray< TSharedPtr< FEdGraphSchemaAction > > &NewActions
Adds an action entry containing multiple actions.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.5, "FGraphActionListBuilderBase::ActionGroup has been deprecated, access TSharedPtr<FEdGraphSchemaAction> directly using GetSchemaAction") 1 ActionGroup GetAction(int32 Index)
UE_DEPRECATED (5.5, "Overriding the schema action category is no longer supported, set the category via CosmeticUpdateRootCategory or CosmeticUpdateCategory") 1 virtual void AddAction(const TSharedPtr< FEdGraphSchemaAction > &NewAction
Protected Member Functions
void BuildCompleted ()
void MakeMenuItems (FBlueprintActionInfo &InAction)
Private Attributes
bool bUsePendingActionList
If enabled, actions will be added to the pending list rather than processed immediately.
TSharedPtr< FBlueprintActionMenuBuilderImpl::FMenuItemListAddHelper > MenuItemListAddHelper
Defines a utility that assists with building the list of action menu items for each menu section based on a set of Blueprint action descriptor records.
TArray< TSharedRef< FBlueprintActionMenuBuilderImpl::FMenuSectionDefinition > > MenuSections
Defines all the separate sections of the menu (filter, sort order, etc.).
Additional Inherited Members
Data Fields inherited from FGraphActionListBuilderBase
FString const & Category = FString())
UEdGraph * OwnerOfTemporaries
Detailed Description
Responsible for constructing a list of viable blueprint actions.
Runs the blueprint actions database through a filter and spawns a series of FBlueprintActionMenuItems for actions that pass. Takes care of generating the each menu item's category/name/etc.
Definition at line 32 of file BlueprintActionMenuBuilder.h.
Member Enumeration Documentation
EConfigFlags
enum FBlueprintActionMenuBuilder::EConfigFlags
Flags used to configure the builder.
Enumerator
UseTimeSlicing
DefaultConfig
Definition at line 36 of file BlueprintActionMenuBuilder.h.
ESectionFlag
enum FBlueprintActionMenuBuilder::ESectionFlag
Flags used to customize specific sections of the menu.
Enumerator
ConsolidatePropertyActions
ConsolidateBoundActions
FlattenCategoryHierarcy
Definition at line 48 of file BlueprintActionMenuBuilder.h.
Constructor & Destructor Documentation
FBlueprintActionMenuBuilder()
FBlueprintActionMenuBuilder::FBlueprintActionMenuBuilder (EConfigFlags Flags = EConfigFlags::DefaultConfig)
Default constructor.
Parameters
Flags - Optional configuration flags.
References DefaultConfig, and Flags.
Referenced by UE_DEPRECATED().
Member Function Documentation
AddMenuSection()
void FBlueprintActionMenuBuilder::AddMenuSection (FBlueprintActionFilter const & Filter, FText const & Heading = FText::GetEmpty(), int32 MenuOrder = 0, uint32 const Flags = 0)
Some action menus require multiple sections.
One option is to create multiple FBlueprintActionMenuBuilders and append them together, but that can be unperformant (each builder will run through the entire database separately)... This method provides an alternative, where you can specify a separate filter/heading/ordering for a sub-section of the menu.
Parameters
Filter The filter you want applied to this section of the menu.
Heading The root category for this section of the menu (can be left blank).
MenuOrder The sort order to assign this section of the menu (higher numbers come first).
Flags Set of ESectionFlags to customize this menu section.
References AddMenuSection(), Filter, and Flags.
Referenced by AddMenuSection().
BuildCompleted()
void FBlueprintActionMenuBuilder::BuildCompleted () protected
References BuildCompleted().
Referenced by BuildCompleted().
Empty()
virtual void FBlueprintActionMenuBuilder::Empty () override virtual
Clears the action entries.
Reimplemented from FGraphActionListBuilderBase.
References Empty().
Referenced by Empty().
GetNumPendingActions()
int32 FBlueprintActionMenuBuilder::GetNumPendingActions () const
Returns the current number of actions that are still pending.
References GetNumPendingActions().
Referenced by GetNumPendingActions().
GetPendingActionsProgress()
float FBlueprintActionMenuBuilder::GetPendingActionsProgress () const
Returns the normalized completion state when processing pending actions (e.g.
for a status indicator)
References GetPendingActionsProgress().
Referenced by GetPendingActionsProgress().
MakeMenuItems()
void FBlueprintActionMenuBuilder::MakeMenuItems (FBlueprintActionInfo & InAction) protected
References MakeMenuItems().
Referenced by MakeMenuItems().
ProcessPendingActions()
bool FBlueprintActionMenuBuilder::ProcessPendingActions ()
Processes any actions that may be added asynchronously or across multiple frames.
Returns true if one or more actions were added into the list.
References ProcessPendingActions().
Referenced by ProcessPendingActions().
RebuildActionList()
void FBlueprintActionMenuBuilder::RebuildActionList ()
Regenerates the entire menu list from the cached menu sections.
Filters and adds action items from the blueprint action database (as defined by the MenuSections list).
References RebuildActionList().
Referenced by RebuildActionList().
UE_DEPRECATED()
FBlueprintActionMenuBuilder::UE_DEPRECATED (5. 2, "The action filter now stores a reference to the authoritative editor context. Please use the default constructor instead.")
References FBlueprintActionMenuBuilder().
Field Documentation
bUsePendingActionList
bool FBlueprintActionMenuBuilder::bUsePendingActionList private
If enabled, actions will be added to the pending list rather than processed immediately.
Definition at line 129 of file BlueprintActionMenuBuilder.h.
MenuItemListAddHelper
TSharedPtr<FBlueprintActionMenuBuilderImpl::FMenuItemListAddHelper> FBlueprintActionMenuBuilder::MenuItemListAddHelper private
Defines a utility that assists with building the list of action menu items for each menu section based on a set of Blueprint action descriptor records.
Definition at line 126 of file BlueprintActionMenuBuilder.h.
MenuSections
TArray< TSharedRef<FBlueprintActionMenuBuilderImpl::FMenuSectionDefinition> > FBlueprintActionMenuBuilder::MenuSections private
Defines all the separate sections of the menu (filter, sort order, etc.).
Defined as a TSharedRef<> so as to hide the implementation details (keep this API clean).
Definition at line 120 of file BlueprintActionMenuBuilder.h.
The documentation for this struct was generated from the following file:
BlueprintActionMenuBuilder.h