Unreal Engine 5.6 C++ API: FComposableFloatDistribution Class Reference
FComposableFloatDistribution Class Reference
A composable floating point distribution.
#include "Distributions.h"
Public Member Functions
FComposableFloatDistribution ()
Default constructor.
FComposableFloatDistribution (const FComposableFloatDistribution &Other)
Copy constructor.
void AddDistribution (const class UDistributionFloat *FloatDistribution)
Adds each sample in the distribution to the corresponding sample in another distribution.
void Initialize (const class UDistributionFloat *FloatDistribution)
Initializes this distribution from that specified.
void InitializeWithConstant (float Value)
Initializes this distribution with a constant value.
void Normalize (float *OutScale, float *OutBias)
Normalizes each value to [0,1] and return a scale and bias to reconstruct the original values.
const FComposableFloatDistribution & operator= (const FComposableFloatDistribution &Other)
Assignment operator.
void Resample (float MinIn, float MaxIn)
Resamples the distribution to include only information from [MinIn,MaxIn].
void ScaleByConstant (float Scale)
Scales each sample in the distribution by a constant.
void ScaleByDistribution (const class UDistributionFloat *FloatDistribution)
Scale each sample in the distribution by the corresponding sample in another distribution.
Additional Inherited Members
Static Public Member Functions inherited from FComposableDistribution
static void BuildFloat (class FFloatDistribution &OutDistribution, const class FComposableFloatDistribution &X)
Constructs a type-safe floating point distribution.
static void BuildVector (class FVectorDistribution &OutDistribution, const class FComposableVectorDistribution &XYZ)
Constructs a type-safe vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableFloatDistribution &X, const class FComposableFloatDistribution &Y, const class FComposableFloatDistribution &Z, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableVectorDistribution &XY, const class FComposableFloatDistribution &Z, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableVectorDistribution &XYZ, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void QuantizeVector4 (TArray< FColor > &OutQuantizedSamples, FVector4 &OutScale, FVector4 &OutBias, const class FVector4Distribution &Distribution)
Quantizes a 4-component vector distribution.
Protected Member Functions inherited from FComposableDistribution
FComposableDistribution ()
Constructor.
FComposableDistribution (const FComposableDistribution &Other)
Copy constructor.
~FComposableDistribution ()
Destructor.
const FComposableDistribution & operator= (const FComposableDistribution &Other)
Assignment operator.
Protected Attributes inherited from FComposableDistribution
FDistributionLookupTable LookupTable
The lookup table.
Detailed Description
A composable floating point distribution.
Definition at line 610 of file Distributions.h.
Constructor & Destructor Documentation
FComposableFloatDistribution() [1/2]
FComposableFloatDistribution::FComposableFloatDistribution ()
Default constructor.
Referenced by FComposableFloatDistribution(), and operator=().
FComposableFloatDistribution() [2/2]
FComposableFloatDistribution::FComposableFloatDistribution (const FComposableFloatDistribution & Other) inline
Copy constructor.
Definition at line 617 of file Distributions.h.
References FComposableDistribution::FComposableDistribution(), FComposableFloatDistribution(), and Other.
Member Function Documentation
AddDistribution()
void FComposableFloatDistribution::AddDistribution (const class UDistributionFloat * FloatDistribution)
Adds each sample in the distribution to the corresponding sample in another distribution.
Initialize()
void FComposableFloatDistribution::Initialize (const class UDistributionFloat * FloatDistribution)
Initializes this distribution from that specified.
InitializeWithConstant()
void FComposableFloatDistribution::InitializeWithConstant (float Value)
Initializes this distribution with a constant value.
References Value.
Normalize()
void FComposableFloatDistribution::Normalize (float * OutScale, float * OutBias)
Normalizes each value to [0,1] and return a scale and bias to reconstruct the original values.
operator=()
const FComposableFloatDistribution & FComposableFloatDistribution::operator= (const FComposableFloatDistribution & Other) inline
Assignment operator.
Definition at line 623 of file Distributions.h.
References FComposableFloatDistribution(), FComposableDistribution::operator=(), and Other.
Resample()
void FComposableFloatDistribution::Resample (float MinIn, float MaxIn)
Resamples the distribution to include only information from [MinIn,MaxIn].
ScaleByConstant()
void FComposableFloatDistribution::ScaleByConstant (float Scale)
Scales each sample in the distribution by a constant.
References Scale.
ScaleByDistribution()
void FComposableFloatDistribution::ScaleByDistribution (const class UDistributionFloat * FloatDistribution)
Scale each sample in the distribution by the corresponding sample in another distribution.
The documentation for this class was generated from the following file:
Distributions.h