Unreal Engine 5.6 C++ API: FActionFilterTest Struct Reference
FActionFilterTest Struct Reference
#include "BlueprintActionFilter.h"
Public Types
typedef FBlueprintGraphModule::FActionMenuRejectionTest FRejectionDelegate
The filter uses a series of rejection tests matching.
Public Member Functions
FActionFilterTest (const FRejectionDelegate Delegate, FString Name, EActionFilterTestFlags Flags=EActionFilterTestFlags::Default)
bool Call (FBlueprintActionFilter const &Filter, FBlueprintActionInfo &ActionInfo)
bool operator== (const FActionFilterTest &other) const
TSharedRef< FActionFilterTest > WithFlags (EActionFilterTestFlags InFlags)
Public Member Functions inherited from TSharedFromThis< FActionFilterTest >
TSharedRef< FActionFilterTest, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FActionFilterTest, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
EActionFilterTestFlags Flags = EActionFilterTestFlags::Default
FString Name
FRejectionDelegate RejectionDelegate
Static Public Attributes
static TAutoConsoleVariable< bool > CVarEnableCaching
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FActionFilterTest >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FActionFilterTest >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 210 of file BlueprintActionFilter.h.
Member Typedef Documentation
FRejectionDelegate
typedef FBlueprintGraphModule::FActionMenuRejectionTest FActionFilterTest::FRejectionDelegate
The filter uses a series of rejection tests matching.
Definition at line 215 of file BlueprintActionFilter.h.
Constructor & Destructor Documentation
FActionFilterTest()
FActionFilterTest::FActionFilterTest (const FRejectionDelegate Delegate, FString Name, EActionFilterTestFlags Flags = EActionFilterTestFlags::Default)
References Default, Flags, and Name.
Referenced by operator==().
Member Function Documentation
Call()
bool FActionFilterTest::Call (FBlueprintActionFilter const & Filter, FBlueprintActionInfo & ActionInfo)
References Filter.
operator==()
bool FActionFilterTest::operator== (const FActionFilterTest & other) const
References FActionFilterTest().
WithFlags()
TSharedRef< FActionFilterTest > FActionFilterTest::WithFlags (EActionFilterTestFlags InFlags) inline
Definition at line 219 of file BlueprintActionFilter.h.
References TSharedFromThis< FActionFilterTest >::AsShared(), EnumAddFlags(), and Flags.
Field Documentation
CVarEnableCaching
TAutoConsoleVariable<bool> FActionFilterTest::CVarEnableCaching static
Definition at line 212 of file BlueprintActionFilter.h.
Flags
EActionFilterTestFlags FActionFilterTest::Flags = EActionFilterTestFlags::Default
Definition at line 230 of file BlueprintActionFilter.h.
Referenced by FActionFilterTest(), and WithFlags().
Name
FString FActionFilterTest::Name
Definition at line 229 of file BlueprintActionFilter.h.
Referenced by FActionFilterTest().
RejectionDelegate
FRejectionDelegate FActionFilterTest::RejectionDelegate
Definition at line 228 of file BlueprintActionFilter.h.
The documentation for this struct was generated from the following file:
BlueprintActionFilter.h