Unreal Engine 5.6 C++ API: UBTFunctionLibrary Class Reference
UBTFunctionLibrary Class Reference
#include "BTFunctionLibrary.h"
Private Member Functions
UFUNCTION ()) static AIMODULE_API AActor *GetBlackboardValueAsActor(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API bool GetBlackboardValueAsBool(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API float GetBlackboardValueAsFloat(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API FName GetBlackboardValueAsName(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API FRotator GetBlackboardValueAsRotator(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API FString GetBlackboardValueAsString(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API FVector GetBlackboardValueAsVector(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API int32 GetBlackboardValueAsInt(UBTNode *NodeOwner
GENERATED_BODY() public UFUNCTION ()) static AIMODULE_API UBehaviorTreeComponent *GetOwnerComponent(UBTNode *NodeOwner)
UFUNCTION ()) static AIMODULE_API UClass *GetBlackboardValueAsClass(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API uint8 GetBlackboardValueAsEnum(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API UObject *GetBlackboardValueAsObject(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void ClearBlackboardValue(UBTNode *NodeOwner
Resets indicated value to "not set" value, based on values type.
UFUNCTION ()) static AIMODULE_API void ClearBlackboardValueAsVector(UBTNode *NodeOwner
(DEPRECATED) Use ClearBlackboardValue instead
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsBool(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsClass(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsEnum(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsFloat(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsInt(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsName(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsObject(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsRotator(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsString(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void SetBlackboardValueAsVector(UBTNode *NodeOwner
UFUNCTION ()) static AIMODULE_API void StartUsingExternalEvent(UBTNode *NodeOwner
Initialize variables marked as "instance memory" and set owning actor for blackboard operations.
UFUNCTION ()) static AIMODULE_API void StopUsingExternalEvent(UBTNode *NodeOwner)
Save variables marked as "instance memory" and clear owning actor.
Private Attributes
const FBlackboardKeySelector & Key
AActor * OwningActor
const FBlackboardKeySelector UObject * Value
const FBlackboardKeySelector UClass * Value
const FBlackboardKeySelector uint8 Value
const FBlackboardKeySelector int32 Value
const FBlackboardKeySelector float Value
const FBlackboardKeySelector bool Value
const FBlackboardKeySelector FString Value
const FBlackboardKeySelector FName Value
const FBlackboardKeySelector FVector Value
const FBlackboardKeySelector FRotator Value
Detailed Description
Definition at line 29 of file BTFunctionLibrary.h.
Member Function Documentation
UFUNCTION() [1/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [2/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [3/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [4/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [5/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [6/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [7/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, FVector, Key, Meta, and UFUNCTION().
UFUNCTION() [8/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [9/26]
GENERATED_BODY() public UBTFunctionLibrary::UFUNCTION () private
References Category, and Meta.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [10/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [11/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [12/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [13/26]
UBTFunctionLibrary::UFUNCTION () private
Resets indicated value to "not set" value, based on values type.
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [14/26]
UBTFunctionLibrary::UFUNCTION () private
(DEPRECATED) Use ClearBlackboardValue instead
References Category, Key, Meta, and UFUNCTION().
UFUNCTION() [15/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [16/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [17/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [18/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [19/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [20/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [21/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [22/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [23/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [24/26]
UBTFunctionLibrary::UFUNCTION () private
References Category, Meta, and UFUNCTION().
UFUNCTION() [25/26]
UBTFunctionLibrary::UFUNCTION () private
Initialize variables marked as "instance memory" and set owning actor for blackboard operations.
References Category, Meta, and UFUNCTION().
UFUNCTION() [26/26]
UBTFunctionLibrary::UFUNCTION () private
Save variables marked as "instance memory" and clear owning actor.
References Category, Meta, and UFUNCTION().
Field Documentation
Key
const FBlackboardKeySelector & UBTFunctionLibrary::Key private
Definition at line 41 of file BTFunctionLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
OwningActor
AActor* UBTFunctionLibrary::OwningActor private
Definition at line 113 of file BTFunctionLibrary.h.
Value [1/10]
const FBlackboardKeySelector UObject* UBTFunctionLibrary::Value private
Definition at line 74 of file BTFunctionLibrary.h.
Value [2/10]
const FBlackboardKeySelector UClass* UBTFunctionLibrary::Value private
Definition at line 77 of file BTFunctionLibrary.h.
Value [3/10]
const FBlackboardKeySelector uint8 UBTFunctionLibrary::Value private
Definition at line 80 of file BTFunctionLibrary.h.
Value [4/10]
const FBlackboardKeySelector int32 UBTFunctionLibrary::Value private
Definition at line 83 of file BTFunctionLibrary.h.
Value [5/10]
const FBlackboardKeySelector float UBTFunctionLibrary::Value private
Definition at line 86 of file BTFunctionLibrary.h.
Value [6/10]
const FBlackboardKeySelector bool UBTFunctionLibrary::Value private
Definition at line 89 of file BTFunctionLibrary.h.
Value [7/10]
const FBlackboardKeySelector FString UBTFunctionLibrary::Value private
Definition at line 92 of file BTFunctionLibrary.h.
Value [8/10]
const FBlackboardKeySelector FName UBTFunctionLibrary::Value private
Definition at line 95 of file BTFunctionLibrary.h.
Value [9/10]
const FBlackboardKeySelector FVector UBTFunctionLibrary::Value private
Definition at line 98 of file BTFunctionLibrary.h.
Value [10/10]
const FBlackboardKeySelector FRotator UBTFunctionLibrary::Value private
Definition at line 105 of file BTFunctionLibrary.h.
The documentation for this class was generated from the following file:
BTFunctionLibrary.h