Unreal Engine 5.6 C++ API: SGraphNodeResizable Class Reference
SGraphNodeResizable Class Reference
#include "SGraphNodeResizable.h"
Public Types
enum EResizableWindowZone {
CRWZ_NotInWindow = 0 , CRWZ_InWindow = 1 , CRWZ_RightBorder = 2 , CRWZ_BottomBorder = 3 ,
CRWZ_BottomRightBorder = 4 , CRWZ_LeftBorder = 5 , CRWZ_TopBorder = 6 , CRWZ_TopLeftBorder = 7 ,
CRWZ_TopRightBorder = 8 , CRWZ_BottomLeftBorder = 9 , CRWZ_TitleBar = 10
}
The resizable window zone the user is interacting with.
Public Types inherited from SNodePanel::SNode
typedef TSet< TWeakPtr< SNodePanel::SNode > > FNodeSet
using FScopedWidgetSlotArguments = TPanelChildren<FNodeSlot>::FScopedWidgetSlotArguments
Public Member Functions
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
Public Member Functions inherited from SGraphNode
void ApplyRename ()
Sets node into rename state if supported.
virtual void CreatePinWidgets ()
Create the widgets for pins on the node.
virtual void CreateStandardPinWidget (UEdGraphPin *Pin)
Create a single pin widget.
TSharedPtr< SGraphPin > FindWidgetForPin (UEdGraphPin *ThePin) const
FLinearColor GetColorAndOpacity () const
UE::Slate::FDeprecateVector2DResult GetContentScale () const
EGraphRenderingLOD::Type GetCurrentLOD () const
Returns the current Node LOD or Highest LOD if unable to query.
FString GetEditableNodeTitle () const
FText GetEditableNodeTitleAsText () const
virtual TOptional< FSlateColor > GetHighlightColor (const SGraphPin *InGraphPin) const
Allows the node to override the pin highlight color.
virtual TSharedPtr< SGraphPin > GetHoveredPin (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) const
Find the pin that is hovered.
virtual const FSlateBrush * GetNodeBodyBrush () const
FSlateColor GetNodeBodyColor () const
virtual FString GetNodeComment () const override
FSlateColor GetNodeCommentColor () const
UEdGraphNode * GetNodeObj () const
FSlateColor GetNodeTitleColor () const
FSlateColor GetNodeTitleIconColor () const
FLinearColor GetNodeTitleTextColor () const
FText GetNodeTooltip () const
virtual TSharedRef< SGraphNode > GetNodeUnderMouse (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
virtual UObject * GetObjectBeingDisplayed () const override
TSharedPtr< SGraphPanel > GetOwnerPanel () const
virtual TOptional< const FSlateBrush * > GetPinBorder (const SGraphPin *InGraphPin) const
Allows the node to override the pin border image.
FLinearColor GetPinLabelColorAndOpacity () const
void GetPins (TArray< TSharedRef< SWidget > > &AllPins) const
void GetPins (TSet< TSharedRef< SWidget > > &AllPins) const
Get all the pins found on this node.
virtual TOptional< FSlateColor > GetPinTextColor (const SGraphPin *InGraphPin) const
Allows the node to override the pin text color.
virtual FVector2f GetPosition2f () const override
virtual FSlateRect GetTitleRect () const
return rect of the title area
virtual TSharedPtr< IToolTip > GetToolTip () override
UE::Slate::FDeprecateVector2DResult GetUnscaledPosition () const
Gets the unscaled position of the node from the last tick.
void InvalidateGraphData ()
Called when ed graph data is cleared, indicating this widget can no longer safely access GraphNode - forwards call to owned pins:
virtual bool IsHidingPinWidgets () const
Returns true if the node is hiding its pins.
virtual bool IsNodeEditable () const
Returns if widget is editable, additionally considers if the owning graph is read only.
bool IsRenamePending () const
returns true if a rename is pending on this node
virtual void MoveTo (const FVector2f &NewPosition, FNodeSet &NodeFilter, bool bMarkDirty=true) override
UE::Slate::FDeprecateVector2DResult NodeCoordToGraphCoord (const UE::Slate::FDeprecateVector2DParameter &PanelSpaceCoordinate) const
Given a coordinate in SGraphNode space, return the same coordinate in graph space while taking zoom and panning of the parent graph into account.
void NotifyDisallowedPinConnection (const class UEdGraphPin *PinA, const class UEdGraphPin *PinB) const
Called from drag drop code when a disallowed connection is hovered.
virtual void OnCommentBubbleToggled (bool bInCommentBubbleVisible)
called when the node's comment bubble is toggled
virtual void OnCommentTextCommitted (const FText &NewComment, ETextCommit::Type CommitInfo)
called to replace this nodes comment text
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
Called when a mouse button is double clicked.
virtual void OnToolTipClosing () override
Called when a tooltip displayed from this widget is being closed.
void PlaySpawnEffect ()
virtual void RefreshErrorInfo ()
Called when GraphNode changes its error information, may be called when no change has actually occurred:
void RequestRename ()
flags node as rename pending if supported
virtual void RequestRenameOnSpawn ()
Requests a rename when the node was initially spawned.
void SetDisallowedPinConnectionEvent (SGraphEditor::FOnDisallowedPinConnection InOnDisallowedPinConnection)
Set event when the user generates a warning tooltip because a connection was invalid.
void SetDoubleClickEvent (FSingleNodeEvent InDoubleClickEvent)
Set event when node is double clicked.
void SetIsEditable (TAttribute< bool > InIsEditable)
Set attribute for determining if widget is editable.
virtual void SetOwner (const TSharedRef< SGraphPanel > &OwnerPanel)
void SetTextCommittedEvent (FOnNodeTextCommitted InDelegate)
Set event when text is committed on the node.
void SetVerifyTextCommitEvent (FOnNodeVerifyTextCommit InOnVerifyTextCommit)
Set event when text is committed on the node.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
virtual void UpdateGraphNode ()
Update this GraphNode to match the data that it is observing.
virtual bool UseLowDetailPinNames () const
Public Member Functions inherited from SNodePanel::SNode
virtual bool CanBeSelected (const FVector2f &MousePositionInNode) const
virtual FVector2D ComputeDesiredSize (float) const override
A Panel's desired size in the space required to arrange of its children on the screen while respecting all of the children's desired sizes and any layout-related options specified by the user.
virtual void EndUserInteraction () const
Called when user interaction has completed.
virtual FChildren * GetChildren () override
All widgets must provide a way to access their children in a layout-agnostic way.
virtual FVector2f GetDesiredSizeForMarquee2f () const
virtual void GetDiffHighlightBrushes (const FSlateBrush *&BackgroundOut, const FSlateBrush *&ForegroundOut) const
used by GetDiffHighlights to generate outlines for diffed nodes
TArray< SNodePanel::SNode::DiffHighlightInfo > GetDiffHighlights (const FDiffSingleResult &DiffResult) const
virtual void GetNodeInfoPopups (FNodeInfoContext *Context, TArray< FGraphInformationPopupInfo > &Popups) const
Populate the popups array with any popups to render.
FScopedWidgetSlotArguments GetOrAddSlot (const ENodeZone::Type SlotId)
virtual void GetOverlayBrushes (bool bSelected, const FVector2f &WidgetSize, TArray< FOverlayBrushInfo > &Brushes) const
virtual TArray< FOverlayWidgetInfo > GetOverlayWidgets (bool bSelected, const FVector2f &WidgetSize) const
virtual float GetRelativeLayoutScale (int32 ChildIndex, float LayoutScaleMultiplier) const override
What is the Child's scale relative to this widget.
FNodeSlot * GetSlot (const ENodeZone::Type SlotId)
virtual int32 GetSortDepth () const
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Panels arrange their children in a space described by the AllottedGeometry parameter.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
bool operator< (const SNodePanel::SNode &NodeIn) const
virtual void PerformSecondPassLayout (const TMap< UObject *, TSharedRef< SNode > > &InNodeToWidgetLookup) const
Performs second pass layout; only called if RequiresSecondPassLayout returned true.
void RemoveSlot (const ENodeZone::Type SlotId)
virtual bool RequiresSecondPassLayout () const
Returns true if this node is dependent on the location of other nodes (it can only depend on the location of first-pass only nodes)
void SetParentPanel (const TSharedPtr< SNodePanel > &InParent)
virtual bool ShouldAllowCulling () const
Return false if this node should not be culled.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual bool CanBeSelected(const FVector2D &MousePositionInNode) const UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
return if the node can be selected, by pointing given location
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FVector2D GetDesiredSizeForMarquee() const UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
override, when area used to select node, should be different, than it's size e.g.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual TArray< FOverlayWidgetInfo > GetOverlayWidgets(bool bSelected
Populate the widgets array with any overlay widgets to render.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual void GetOverlayBrushes(bool bSelected
Populate the brushes array with any overlay brushes to render.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual void MoveTo(const FVector2D &NewPosition
Public Member Functions inherited from SPanel
void Construct ()
Most panels do not create widgets as part of their implementation, so they do not need to implement a Construct()
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual UE_DEPRECATED(5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual SGraphNodeResizable SGraphNodeResizable::EResizableWindowZone FindMouseZone (const FVector2f &LocalMouseCoordinates) const
Find the current window zone the mouse is in.
UE::Slate::FDeprecateVector2DResult GetCorrectedNodePosition () const
Function to fetch the corrected node position based on anchor point.
virtual FSlateRect GetHitTestingBorder () const
virtual FVector2f GetNodeMaximumSize2f () const
virtual FVector2f GetNodeMinimumSize2f () const
virtual float GetTitleBarHeight () const
Get the current titlebar size.
void InitNodeAnchorPoint ()
Function to store anchor point before resizing the node.
bool InSelectionArea () const
bool InSelectionArea (EResizableWindowZone InZone) const
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FVector2D GetNodeMaximumSize() const
Return largest desired node size.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FVector2D GetNodeMinimumSize() const
Return smallest desired node size.
Protected Member Functions inherited from SGraphNode
SGraphNode ()
virtual void AddPin (const TSharedRef< SGraphPin > &PinToAdd)
Add a new pin to this graph node.
TSharedRef< SWidget > AddPinButtonContent (FText PinText, FText PinTooltipText, bool bRightSide=true, FString DocumentationExcerpt=FString(), TSharedPtr< SToolTip > CustomTooltip=NULL)
Creates widget for an Add pin button, which can then be added to the node.
virtual EVisibility AdvancedViewArrowVisibility () const
Returns visibility of AdvancedViewButton.
virtual void CreateAdvancedViewArrow (TSharedPtr< SVerticalBox > MainBox)
Create button to show/hide advanced pins.
virtual void CreateBelowPinControls (TSharedPtr< SVerticalBox > MainBox)
virtual void CreateBelowWidgetControls (TSharedPtr< SVerticalBox > MainBox)
virtual void CreateInputSideAddButton (TSharedPtr< SVerticalBox > InputBox)
Override this to create a button to add pins on the input side of the node.
virtual TSharedRef< SWidget > CreateNodeContentArea ()
Create the inner node content area, including the left/right pin boxes.
virtual void CreateOutputSideAddButton (TSharedPtr< SVerticalBox > OutputBox)
Override this to create a button to add pins on the output side of the node.
virtual TSharedPtr< SGraphPin > CreatePinWidget (UEdGraphPin *Pin) const
Hook that allows derived classes to supply their own SGraphPin derivatives for any pin.
virtual TSharedRef< SWidget > CreateTitleRightWidget ()
Optionally create a widget to dock to the right in the title bar of the node.
virtual TSharedRef< SWidget > CreateTitleWidget (TSharedPtr< SNodeTitle > NodeTitle)
virtual const FSlateBrush * GetAdvancedViewArrow () const
Up when shown, down when hidden.
virtual FSlateColor GetCommentColor () const
Return the desired comment bubble color.
virtual TSharedPtr< SToolTip > GetComplexTooltip ()
Override this to provide support for an 'expensive' tooltip widget that is only built on demand.
TSharedPtr< SWidget > GetEnabledStateWidget ()
Returns the widget to use for the enabled state of the node.
FSlateColor GetErrorColor () const
FString GetErrorMessage () const
Helper function to get any error text for the node.
FText GetErrorMsgToolTip () const
Function to get error description string.
virtual TOptional< ETextOverflowPolicy > GetNameOverflowPolicy () const
Determines how the node title overflow is handled.
FSlateColor GetVisualWarningColor () const
FText GetVisualWarningMsgToolTip () const
Function to get a visual warning description string(visual warnings does not break the build)
virtual EVisibility IsAddPinButtonVisible () const
Checks whether Add pin button should currently be visible.
virtual ECheckBoxState IsAdvancedViewChecked () const
hidden == unchecked, shown == checked
virtual bool IsNameReadOnly () const
bool IsSelectedExclusively () const
Checks if the node is the only node selected.
virtual FReply OnAddPin ()
Callback function executed when Add pin button is clicked.
virtual void OnAdvancedViewChanged (const ECheckBoxState NewCheckedState)
Show/hide advanced view.
void OnNameTextCommited (const FText &InText, ETextCommit::Type CommitInfo)
bool OnVerifyNameTextChanged (const FText &InText, FText &OutErrorMessage)
Called when text is being committed to check for validity.
virtual void PopulateMetaTag (class FGraphNodeMetaData *TagMeta) const
void PositionThisNodeBetweenOtherNodes (const FVector2f &PrevPos, const FVector2f &NextPos, float HeightAboveWire) const
void PositionThisNodeBetweenOtherNodes (const TMap< UObject *, TSharedRef< SNode > > &NodeToWidgetLookup, TSet< UEdGraphNode * > &PreviousNodes, TSet< UEdGraphNode * > &NextNodes, float HeightAboveWire) const
void PositionThisNodeBetweenOtherNodes (const TMap< UObject *, TSharedRef< SNode > > &NodeToWidgetLookup, UEdGraphNode *PreviousNode, UEdGraphNode *NextNode, float HeightAboveWire) const
virtual void SetDefaultTitleAreaWidget (TSharedRef< SOverlay > DefaultTitleAreaWidget)
void SetupErrorReporting ()
Set-up the error reporting widget for the node.
bool ShouldPinBeHidden (const UEdGraphPin *InPin) const
Returns TRUE if the input pin should be hidden from view.
virtual void UpdateErrorInfo ()
Called to set error text on the node.
virtual bool UseLowDetailNodeTitles () const
EVisibility VisualWarningVisibility () const
Controls wether to show or not the visual warning message.
Protected Member Functions inherited from SNodePanel::SNode
SNode ()
Protected Member Functions inherited from SPanel
SPanel ()
Hidden default constructor.
virtual ~SPanel ()
int32 PaintArrangedChildren (const FPaintArgs &Args, const FArrangedChildren &ArrangedChildren, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Just like OnPaint, but takes already arranged children.
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bUserIsDragging
If true the user is actively dragging the node.
FDeprecateSlateVector2D DragSize
The non snapped size of the node for fluid resizing.
EResizableWindowZone MouseZone
The current window zone the mouse is in.
FDeprecateSlateVector2D NodeAnchorPoint
Anchor point used to correct node position on resizing the node.
TSharedPtr< FScopedTransaction > ResizeTransactionPtr
The resize transaction.
FDeprecateSlateVector2D StoredUserSize
The original size of the node while resizing.
FDeprecateSlateVector2D UserSize
The desired size of the node set during a drag.
Protected Attributes inherited from SGraphNode
bool bProvidedComplexTooltip
bool bRenameIsPending
FVector2f CachedUnscaledPosition
Caches true position of node.
FSlateColor ErrorColor
Used to set the error color.
FString ErrorMsg
Used to report errors on the node.
TSharedPtr< class IErrorReportingWidget > ErrorReporting
Error handling widget.
FCurveHandle FadeCurve
UEdGraphNode * GraphNode
The GraphNode being observed by this widget.
FLinearColor IconColor
Cached icon color for the node.
TSharedPtr< SInlineEditableTextBlock > InlineEditableText
Used to display the name of the node and allow renaming of the node.
TArray< TSharedRef< SGraphPin > > InputPins
Input pin widgets on this node.
TAttribute< bool > IsEditable
Is this node editable.
TSharedPtr< SVerticalBox > LeftNodeBox
The area where input pins reside.
SGraphEditor::FOnDisallowedPinConnection OnDisallowedPinConnection
Called when the user generates a warning tooltip because a connection was invalid.
FSingleNodeEvent OnDoubleClick
FOnNodeTextCommitted OnTextCommitted
Called whenever the text on the node is committed interactively by the user.
FOnNodeVerifyTextCommit OnVerifyTextCommit
Called whenever the text on the node is being committed interactively by the user, validates the string for commit.
TArray< TSharedRef< SGraphPin > > OutputPins
Output pin widgets on this node.
TWeakPtr< SGraphPanel > OwnerGraphPanelPtr
The GraphPanel within in which this node resides.
TSharedPtr< SVerticalBox > RightNodeBox
The area where output pins reside.
const class UGraphEditorSettings * Settings
Cached pointer to graph editor settings.
FCurveSequence SpawnAnim
FMargin TitleBorderMargin = FMargin(10.f, 5.f, 30.f, 3.f)
FSlateColor VisualWarningColor
Used to set the soft error color.
FString VisualWarningMsg
Used to report visual warnings on the node (does not break build)
TSharedPtr< class IErrorReportingWidget > VisualWarningReporting
Visual Warning handling widget.
FCurveHandle ZoomCurve
Protected Attributes inherited from SNodePanel::SNode
TAttribute< FSlateColor > BorderBackgroundColor
TAttribute< const FSlateBrush * > BorderImage
TAttribute< FLinearColor > ColorAndOpacity
The color and opacity to apply to this widget and all its descendants.
TAttribute< FDeprecateSlateVector2D > ContentScale
The layout scale to apply to this widget's contents; useful for animation.
TAttribute< FDeprecateSlateVector2D > DesiredSizeScale
TAttribute< FSlateColor > ForegroundColor
Optional foreground color that will be inherited by all of this widget's contents.
FPointerEventHandler MouseButtonDownHandler
Mouse event handlers.
FPointerEventHandler MouseButtonUpHandler
FPointerEventHandler MouseDoubleClickHandler
FPointerEventHandler MouseMoveHandler
TAttribute< bool > ShowDisabledEffect
Whether or not to show the disabled effect when this border is disabled.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Data Fields inherited from SNodePanel::SNode
FNodeSet bool bMarkDirty
FNodeSet & NodeFilter
const FVector2D TArray< FOverlayBrushInfo > &Brushes const UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
const FVector2D &WidgetSize const UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
const FVector2D WidgetSize
Static Protected Member Functions inherited from SGraphNode
static bool CanAllowInteractionUsingDragDropOp (const UEdGraphNode *GraphNodePtr, const TSharedPtr< FActorDragDropOp > &DragDropOp)
Check whether drag and drop functionality is permitted on the given node.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 17 of file SGraphNodeResizable.h.
Member Enumeration Documentation
EResizableWindowZone
enum SGraphNodeResizable::EResizableWindowZone
The resizable window zone the user is interacting with.
Enumerator
CRWZ_NotInWindow
CRWZ_InWindow
CRWZ_RightBorder
CRWZ_BottomBorder
CRWZ_BottomRightBorder
CRWZ_LeftBorder
CRWZ_TopBorder
CRWZ_TopLeftBorder
CRWZ_TopRightBorder
CRWZ_BottomLeftBorder
CRWZ_TitleBar
Definition at line 24 of file SGraphNodeResizable.h.
Member Function Documentation
FindMouseZone()
virtual UE_DEPRECATED(5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual SGraphNodeResizable SGraphNodeResizable::EResizableWindowZone SGraphNodeResizable::FindMouseZone (const FVector2f & LocalMouseCoordinates) const protected virtual
Find the current window zone the mouse is in.
References FindMouseZone().
Referenced by FindMouseZone(), and OnCursorQuery().
GetCorrectedNodePosition()
UE::Slate::FDeprecateVector2DResult SGraphNodeResizable::GetCorrectedNodePosition () const protected
Function to fetch the corrected node position based on anchor point.
GetHitTestingBorder()
virtual FSlateRect SGraphNodeResizable::GetHitTestingBorder () const protected virtual
Reimplemented in SGraphNodeComment, and SGraphNodeDocumentation.
References GetHitTestingBorder().
Referenced by GetHitTestingBorder().
GetNodeMaximumSize2f()
virtual FVector2f SGraphNodeResizable::GetNodeMaximumSize2f () const protected virtual
Reimplemented in SGraphNodeComment, and SGraphNodeDocumentation.
References GetNodeMaximumSize2f().
Referenced by GetNodeMaximumSize2f().
GetNodeMinimumSize2f()
virtual FVector2f SGraphNodeResizable::GetNodeMinimumSize2f () const protected virtual
Reimplemented in SGraphNodeDocumentation.
References GetNodeMinimumSize2f().
Referenced by GetNodeMinimumSize2f().
GetTitleBarHeight()
virtual float SGraphNodeResizable::GetTitleBarHeight () const protected virtual
Get the current titlebar size.
Reimplemented in SGraphNodeComment, and SGraphNodeDocumentation.
InitNodeAnchorPoint()
void SGraphNodeResizable::InitNodeAnchorPoint () protected
Function to store anchor point before resizing the node.
The node will be anchored to this point when resizing happens
InSelectionArea() [1/2]
bool SGraphNodeResizable::InSelectionArea () const inline protected
Returns
true if the current window zone is considered a selection area
Definition at line 56 of file SGraphNodeResizable.h.
References InSelectionArea(), and MouseZone.
Referenced by InSelectionArea().
InSelectionArea() [2/2]
bool SGraphNodeResizable::InSelectionArea (EResizableWindowZone InZone) const protected
Returns
true if the passed zone is a selection area
OnCursorQuery()
virtual FCursorReply SGraphNodeResizable::OnCursorQuery (const FGeometry & MyGeometry, const FPointerEvent & CursorEvent) const override virtual
The system asks each widget under the mouse to provide a cursor.
This event is bubbled.
Returns
FCursorReply::Unhandled() if the event is not handled; return FCursorReply::Cursor() otherwise.
Reimplemented from SWidget.
References FindMouseZone(), and SNodePanel::SNode::UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION.
OnMouseButtonDown()
virtual FReply SGraphNodeResizable::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SGraphNode.
References MouseEvent.
OnMouseButtonUp()
virtual FReply SGraphNodeResizable::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SGraphNode.
Reimplemented in SGraphNodeComment, and SRigVMGraphNodeComment.
References MouseEvent.
OnMouseEnter()
virtual void SGraphNodeResizable::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has entered it.
This event is uses a custom bubble strategy.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Reimplemented from SNodePanel::SNode.
References MouseEvent.
OnMouseLeave()
virtual void SGraphNodeResizable::OnMouseLeave (const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented from SNodePanel::SNode.
References MouseEvent.
OnMouseMove()
virtual FReply SGraphNodeResizable::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent.
UE_DEPRECATED() [1/2]
SGraphNodeResizable::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") const protected
Return largest desired node size.
References UE_DEPRECATED(), and SNodePanel::SNode::UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION.
UE_DEPRECATED() [2/2]
SGraphNodeResizable::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") const protected
Return smallest desired node size.
References SNodePanel::SNode::UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION.
Referenced by UE_DEPRECATED().
Field Documentation
bUserIsDragging
bool SGraphNodeResizable::bUserIsDragging protected
If true the user is actively dragging the node.
Definition at line 104 of file SGraphNodeResizable.h.
DragSize
FDeprecateSlateVector2D SGraphNodeResizable::DragSize protected
The non snapped size of the node for fluid resizing.
Definition at line 86 of file SGraphNodeResizable.h.
MouseZone
EResizableWindowZone SGraphNodeResizable::MouseZone protected
The current window zone the mouse is in.
Definition at line 101 of file SGraphNodeResizable.h.
Referenced by InSelectionArea().
NodeAnchorPoint
FDeprecateSlateVector2D SGraphNodeResizable::NodeAnchorPoint protected
Anchor point used to correct node position on resizing the node.
Definition at line 98 of file SGraphNodeResizable.h.
ResizeTransactionPtr
TSharedPtr<FScopedTransaction> SGraphNodeResizable::ResizeTransactionPtr protected
The resize transaction.
Definition at line 95 of file SGraphNodeResizable.h.
StoredUserSize
FDeprecateSlateVector2D SGraphNodeResizable::StoredUserSize protected
The original size of the node while resizing.
Definition at line 92 of file SGraphNodeResizable.h.
UserSize
FDeprecateSlateVector2D SGraphNodeResizable::UserSize protected
The desired size of the node set during a drag.
Definition at line 89 of file SGraphNodeResizable.h.
The documentation for this class was generated from the following file:
SGraphNodeResizable.h