Unreal Engine 5.6 C++ API: FBaseKelvinletBrushOp Class Reference
FBaseKelvinletBrushOp Class Reference
#include "KelvinletBrushOp.h"
Public Member Functions
template<typename KelvinletType>
void ApplyKelvinlet (const KelvinletType &Kelvinlet, const FFrame3d &LocalFrame, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) const
virtual void ApplyStamp (const FDynamicMesh3 *SrcMesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) override
void SetBaseProperties (const FDynamicMesh3 *SrcMesh, const FSculptBrushStamp &Stamp)
Public Member Functions inherited from FMeshSculptBrushOp
virtual ~FMeshSculptBrushOp ()
virtual void ApplyStamp (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewValuesOut)=0
virtual void BeginStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &InitialVertices)
virtual void CancelStroke ()
virtual void ConfigureOptions (const FSculptBrushOptions &Options)
virtual void EndStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &FinalVertices)
virtual bool GetAlignStampToView () const
virtual EBrushRegionType GetBrushRegionType () const
virtual ESculptBrushOpTargetType GetBrushTargetType () const
const FMeshSculptFallofFunc & GetFalloff () const
template<typename PropType>
PropType * GetPropertySetAs ()
template<typename PropType>
const PropType * GetPropertySetAs () const
virtual EReferencePlaneType GetReferencePlaneType () const
virtual EStampAlignmentType GetStampAlignmentType () const
virtual bool IgnoreZeroMovements () const
virtual bool SupportsVariableSpacing () const
virtual bool UseLastStampFrameOnZeroMovement () const
virtual bool UsesAlpha () const
virtual bool WantsStampRegionPlane () const
Protected Member Functions
void ApplyFalloff (const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) const
template<typename KelvinletType>
void DisplaceKelvinlet (const KelvinletType &Kelvinlet, const FFrame3d &LocalFrame, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) const
template<typename KelvinletType>
void IntegrateKelvinlet (const KelvinletType &Kelvinlet, const FFrame3d &LocalFrame, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut, const double Dt, const int32 Steps) const
Protected Attributes
double IntegrationTime = 1.
const FDynamicMesh3 * Mesh
float Mu
float Nu
int32 NumSteps
float Size
Additional Inherited Members
Public Types inherited from FMeshSculptBrushOp
enum class EBrushRegionType { LocalSphere , InfiniteCylinder , CylinderOnSphere }
enum class EReferencePlaneType { None , InitialROI , InitialROI_ViewAligned , WorkPlane }
enum class EStampAlignmentType { HitNormal , Camera , ReferencePlane , ReferenceSphere }
Data Fields inherited from FMeshSculptBrushOp
FSculptBrushOptions CurrentOptions
TSharedPtr< FMeshSculptFallofFunc > Falloff
TWeakObjectPtr< UMeshSculptBrushOpProps > PropertySet
Detailed Description
Definition at line 57 of file KelvinletBrushOp.h.
Member Function Documentation
ApplyFalloff()
void FBaseKelvinletBrushOp::ApplyFalloff (const FSculptBrushStamp & Stamp, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) const inline protected
Definition at line 100 of file KelvinletBrushOp.h.
References Alpha, FMath::Clamp(), FMeshSculptFallofFunc::Evaluate(), FMeshSculptBrushOp::Falloff, FMeshSculptBrushOp::GetFalloff(), Mesh, and ParallelFor().
Referenced by FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FPinchKelvinletBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FScaleKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), and FTwistKelvinletBrushOp::ApplyStamp().
ApplyKelvinlet()
template<typename KelvinletType> void FBaseKelvinletBrushOp::ApplyKelvinlet (const KelvinletType & Kelvinlet, const FFrame3d & LocalFrame, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) const inline
Definition at line 81 of file KelvinletBrushOp.h.
References DisplaceKelvinlet(), IntegrateKelvinlet(), IntegrationTime, and NumSteps.
Referenced by FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FPinchKelvinletBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FScaleKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), and FTwistKelvinletBrushOp::ApplyStamp().
ApplyStamp()
virtual void FBaseKelvinletBrushOp::ApplyStamp (const FDynamicMesh3 * SrcMesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) inline override virtual
Reimplemented in FBiLaplacianPullKelvinletBrushOp, FLaplacianPullKelvinletBrushOp, FPinchKelvinletBrushOp, FPullKelvinletBrushOp, FScaleKelvinletBrushOp, FSharpPullKelvinletBrushOp, and FTwistKelvinletBrushOp.
Definition at line 96 of file KelvinletBrushOp.h.
DisplaceKelvinlet()
template<typename KelvinletType> void FBaseKelvinletBrushOp::DisplaceKelvinlet (const KelvinletType & Kelvinlet, const FFrame3d & LocalFrame, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) const inline protected
Definition at line 121 of file KelvinletBrushOp.h.
References UE::Geometry::TFrame3< RealType >::FromFramePoint(), Mesh, No, ParallelFor(), TArray< InElementType, InAllocatorType >::SetNum(), and UE::Geometry::TFrame3< RealType >::ToFramePoint().
Referenced by ApplyKelvinlet().
IntegrateKelvinlet()
template<typename KelvinletType> void FBaseKelvinletBrushOp::IntegrateKelvinlet (const KelvinletType & Kelvinlet, const FFrame3d & LocalFrame, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut, const double Dt, const int32 Steps) const inline protected
Definition at line 144 of file KelvinletBrushOp.h.
References UE::Geometry::TFrame3< RealType >::FromFramePoint(), Mesh, No, ParallelFor(), TArray< InElementType, InAllocatorType >::SetNum(), and UE::Geometry::TFrame3< RealType >::ToFramePoint().
Referenced by ApplyKelvinlet().
SetBaseProperties()
void FBaseKelvinletBrushOp::SetBaseProperties (const FDynamicMesh3 * SrcMesh, const FSculptBrushStamp & Stamp) inline
Definition at line 61 of file KelvinletBrushOp.h.
References FMath::Clamp(), FMeshSculptBrushOp::GetPropertySetAs(), FMath::Max, Mesh, Mu, Nu, NumSteps, FSculptBrushStamp::Radius, and Size.
Referenced by FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FScaleKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), and FTwistKelvinletBrushOp::ApplyStamp().
Field Documentation
IntegrationTime
double FBaseKelvinletBrushOp::IntegrationTime = 1. protected
Definition at line 181 of file KelvinletBrushOp.h.
Referenced by ApplyKelvinlet().
Mesh
const FDynamicMesh3* FBaseKelvinletBrushOp::Mesh protected
Definition at line 183 of file KelvinletBrushOp.h.
Referenced by ApplyFalloff(), DisplaceKelvinlet(), IntegrateKelvinlet(), and SetBaseProperties().
Mu
float FBaseKelvinletBrushOp::Mu protected
Definition at line 174 of file KelvinletBrushOp.h.
Referenced by FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FPinchKelvinletBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FScaleKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), FTwistKelvinletBrushOp::ApplyStamp(), and SetBaseProperties().
Nu
float FBaseKelvinletBrushOp::Nu protected
Definition at line 175 of file KelvinletBrushOp.h.
Referenced by FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FPinchKelvinletBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FScaleKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), FTwistKelvinletBrushOp::ApplyStamp(), and SetBaseProperties().
NumSteps
int32 FBaseKelvinletBrushOp::NumSteps protected
Definition at line 180 of file KelvinletBrushOp.h.
Referenced by ApplyKelvinlet(), and SetBaseProperties().
Size
float FBaseKelvinletBrushOp::Size protected
Definition at line 177 of file KelvinletBrushOp.h.
Referenced by FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FPinchKelvinletBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FScaleKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), FTwistKelvinletBrushOp::ApplyStamp(), and SetBaseProperties().
The documentation for this class was generated from the following file:
KelvinletBrushOp.h