Unreal Engine 5.6 C++ API: SUniformGridPanel::FSlot Struct Reference
SUniformGridPanel::FSlot Struct Reference
Stores the per-child info for this panel type.
#include "SUniformGridPanel.h"
Public Member Functions
int32 Column (InColumn)
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
int32 GetColumn () const
int32 GetRow () const
int32 Row (InRow)
void SetColumn (int32 InColumn)
void SetRow (int32 InRow)
SLATE_SLOT_BEGIN_ARGS_OneMixin (FSlot, TSlotBase< FSlot >, TAlignmentWidgetSlotMixin< FSlot >) SLATE_SLOT_END_ARGS() FSlot(int32 InColumn
int32 TAlignmentWidgetSlotMixin (HAlign_Fill, VAlign_Fill)
Public Member Functions inherited from TSlotBase< FSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlot & Expose (FSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Public Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
TAlignmentWidgetSlotMixin ()
EHorizontalAlignment GetHorizontalAlignment () const
EVerticalAlignment GetVerticalAlignment () const
void SetHorizontalAlignment (EHorizontalAlignment Alignment)
void SetVerticalAlignment (EVerticalAlignment Alignment)
Data Fields
int32 InRow: TSlotBase<FSlot>()
Private Attributes
int32 Column
int32 Row
Additional Inherited Members
Public Types inherited from TSlotBase< FSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Protected Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Detailed Description
Stores the per-child info for this panel type.
Definition at line 22 of file SUniformGridPanel.h.
Member Function Documentation
Column()
int32 SUniformGridPanel::FSlot::Column (InColumn)
References Column.
Construct()
void SUniformGridPanel::FSlot::Construct (const FChildren & SlotOwner, FSlotArguments && InArgs) inline
Definition at line 35 of file SUniformGridPanel.h.
References TSlotBase< SlotType >::Construct(), TAlignmentWidgetSlotMixin< MixedIntoType >::ConstructMixin(), and MoveTemp().
GetColumn()
int32 SUniformGridPanel::FSlot::GetColumn () const inline
Definition at line 50 of file SUniformGridPanel.h.
References Column.
GetRow()
int32 SUniformGridPanel::FSlot::GetRow () const inline
Definition at line 55 of file SUniformGridPanel.h.
References Row.
Row()
int32 SUniformGridPanel::FSlot::Row (InRow) inline
Definition at line 31 of file SUniformGridPanel.h.
References InRow, and Row.
SetColumn()
void SUniformGridPanel::FSlot::SetColumn (int32 InColumn) inline
Definition at line 41 of file SUniformGridPanel.h.
References Column, FSlotBase::Invalidate(), and Layout.
SetRow()
void SUniformGridPanel::FSlot::SetRow (int32 InRow) inline
Definition at line 60 of file SUniformGridPanel.h.
References InRow, FSlotBase::Invalidate(), Layout, and Row.
SLATE_SLOT_BEGIN_ARGS_OneMixin()
SUniformGridPanel::FSlot::SLATE_SLOT_BEGIN_ARGS_OneMixin (FSlot , TSlotBase< FSlot > , TAlignmentWidgetSlotMixin< FSlot >)
References TAlignmentWidgetSlotMixin().
TAlignmentWidgetSlotMixin()
int32 SUniformGridPanel::FSlot::TAlignmentWidgetSlotMixin (HAlign_Fill , VAlign_Fill)
Referenced by SLATE_SLOT_BEGIN_ARGS_OneMixin().
Field Documentation
Column
int32 SUniformGridPanel::FSlot::Column private
Definition at line 70 of file SUniformGridPanel.h.
Referenced by Column(), GetColumn(), and SetColumn().
InRow
int32 SUniformGridPanel::FSlot::InRow
Definition at line 27 of file SUniformGridPanel.h.
Referenced by Row(), and SetRow().
Row
int32 SUniformGridPanel::FSlot::Row private
Definition at line 71 of file SUniformGridPanel.h.
Referenced by GetRow(), Row(), and SetRow().
The documentation for this struct was generated from the following file:
SUniformGridPanel.h