Unreal Engine 5.6 C++ API: UE::Math::TQuat< T > Struct Template Reference
UE::Math::TQuat< T > Struct Template Reference
Floating point quaternion that can represent a rotation about an axis in 3-D space.
#include "Quat.h"
Public Types
using FReal = T
Type of the template param (float or double)
using QuatVectorRegister = TVectorRegisterType<T>
Public Member Functions
TQuat ()=default
Default constructor (no initialization).
TQuat (const TMatrix< T > &M)
Creates and initializes a new quaternion from the given matrix.
template<typename FArg UE_REQUIRES>
TQuat (const TQuat< FArg > &From)
TQuat (const TRotator< T > &R)
Creates and initializes a new quaternion from the given rotator.
FORCEINLINE TQuat (EForceInit)
Creates and initializes a new quaternion, with the W component either 0 or 1.
FORCEINLINE TQuat (T InX, T InY, T InZ, T InW)
Constructor.
template<typename DummyT = T UE_REQUIRES(std::is_arithmetic_v<T>)>
FORCEINLINE TQuat (T V)
Initializes all elements to V.
TQuat (TVector< T > Axis, T AngleRad)
Creates and initializes a new quaternion from the a rotation around the given axis.
FORCEINLINE T AngularDistance (const TQuat< T > &Q) const
Find the angular distance between two rotation quaternions (in radians)
bool ContainsNaN () const
Utility to check if there are any non-finite values (NaN or Inf) in this Quat.
FORCEINLINE void DiagnosticCheckNaN () const
FORCEINLINE void DiagnosticCheckNaN (const TCHAR *Message) const
void EnforceShortestArcWith (const TQuat< T > &OtherQuat)
Enforce that the delta between this Quaternion and another one represents the shortest possible rotation angle.
FORCEINLINE bool Equals (const TQuat< T > &Q, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether another Quaternion is equal to this, within specified tolerance.
TVector< T > Euler () const
Convert a Quaternion into floating-point Euler angles (in degrees).
TQuat< T > Exp () const
FORCEINLINE T GetAngle () const
Get the angle in radians of this quaternion.
FORCEINLINE TVector< T > GetAxisX () const
Get the forward direction (X axis) after it has been rotated by this Quaternion.
FORCEINLINE TVector< T > GetAxisY () const
Get the right direction (Y axis) after it has been rotated by this Quaternion.
FORCEINLINE TVector< T > GetAxisZ () const
Get the up direction (Z axis) after it has been rotated by this Quaternion.
FORCEINLINE TVector< T > GetForwardVector () const
Get the forward direction (X axis) after it has been rotated by this Quaternion.
FORCEINLINE TQuat< T > GetNormalized (T Tolerance=UE_SMALL_NUMBER) const
Get a normalized copy of this quaternion.
FORCEINLINE TVector< T > GetRightVector () const
Get the right direction (Y axis) after it has been rotated by this Quaternion.
FORCEINLINE TVector< T > GetRotationAxis () const
Get the axis of rotation of the Quaternion.
TQuat< T > GetShortestArcWith (const TQuat< T > &OtherQuat) const
Returns the version of this quaternion that represents the shortest rotation angle to the other quaternion.
T GetTwistAngle (const TVector< T > &TwistAxis) const
Get the twist angle (in radians) for a specified axis.
FORCEINLINE TVector< T > GetUpVector () const
Get the up direction (Z axis) after it has been rotated by this Quaternion.
bool Identical (const TQuat *Q, const uint32 PortFlags) const
Identical implementation for TQuat properties.
bool InitFromString (const FString &InSourceString)
Initialize this TQuat from a FString.
FORCEINLINE TQuat< T > Inverse () const
FORCEINLINE bool IsIdentity (T Tolerance=UE_SMALL_NUMBER) const
Checks whether this Quaternion is an Identity Quaternion.
bool IsNormalized () const
TQuat< T > Log () const
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess)
Serializes the vector compressed for e.g.
FORCEINLINE void Normalize (T Tolerance=UE_SMALL_NUMBER)
Normalize this quaternion if it is large enough.
bool operator!= (const TQuat< T > &Q) const
Checks whether two quaternions are not identical.
template<typename FArg UE_REQUIRES>
FORCEINLINE TQuat< T > operator* (const FArg Scale) const
Get the result of scaling this quaternion.
TMatrix< T > operator* (const TMatrix< T > &M) const
Multiply this by a matrix.
FORCEINLINE TQuat< T > operator* (const TQuat< T > &Q) const
Gets the result of multiplying this by another quaternion (this * Q).
TVector< T > operator* (const TVector< T > &V) const
Rotate a vector by this quaternion.
template<typename FArg UE_REQUIRES>
FORCEINLINE TQuat< T > operator*= (const FArg Scale)
Multiply this quaternion by a scaling factor.
FORCEINLINE TQuat< T > operator*= (const TQuat< T > &Q)
Multiply this by a quaternion (this = this * Q).
FORCEINLINE TQuat< T > operator+ (const TQuat< T > &Q) const
Gets the result of adding a Quaternion to this.
FORCEINLINE TQuat< T > operator+= (const TQuat< T > &Q)
Adds to this quaternion.
FORCEINLINE TQuat< T > operator- () const
Negates the quaternion.
FORCEINLINE TQuat< T > operator- (const TQuat< T > &Q) const
Gets the result of subtracting a Quaternion to this.
FORCEINLINE TQuat< T > operator-= (const TQuat< T > &Q)
Subtracts another quaternion from this.
template<typename FArg UE_REQUIRES>
FORCEINLINE TQuat< T > operator/ (const FArg Scale) const
Divide this quaternion by scale.
template<typename FArg UE_REQUIRES>
FORCEINLINE TQuat< T > operator/= (const FArg Scale)
Divide this quaternion by scale.
bool operator== (const TQuat< T > &Q) const
Checks whether two quaternions are identical.
T operator| (const TQuat< T > &Q) const
Calculates dot product of two quaternions.
TVector< T > RotateVector (TVector< T > V) const
Rotate a vector by this quaternion.
TRotator< T > Rotator () const
Get the TRotator<T> representation of this Quaternion.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
FORCEINLINE T Size () const
Get the length of this quaternion.
FORCEINLINE T SizeSquared () const
Get the length squared of this quaternion.
void ToAxisAndAngle (TVector< T > &Axis, double &Angle) const
void ToAxisAndAngle (TVector< T > &Axis, float &Angle) const
get the axis and angle of rotation of this quaternion
TTuple< T, T, T > ToLUFEuler () const
FORCEINLINE TMatrix< T > ToMatrix () const
Get the TMatrix<T> representation of this Quaternion.
void ToMatrix (TMatrix< T > &Mat) const
Get the TMatrix<T> representation of this Quaternion and store it in Mat.
TVector< T > ToRotationVector () const
Get the rotation vector corresponding to this quaternion.
FString ToString () const
Get a textual representation of the vector.
void ToSwingTwist (const TVector< T > &InTwistAxis, TQuat< T > &OutSwing, TQuat< T > &OutTwist) const
Get the swing and twist decomposition for a specified axis.
TVector< T > UnrotateVector (TVector< T > V) const
Rotate a vector by the inverse of this quaternion.
FORCEINLINE TVector< T > Vector () const
Convert a rotation into a unit vector facing in its direction.
Static Public Member Functions
static void CalcTangents (const TQuat< T > &PrevP, const TQuat< T > &P, const TQuat< T > &NextP, T Tension, TQuat< T > &OutTan)
Calculate tangents between given points.
static FORCEINLINE T Error (const TQuat< T > &Q1, const TQuat< T > &Q2)
Error measure (angle) between two quaternions, ranged [0..1].
static FORCEINLINE T ErrorAutoNormalize (const TQuat< T > &A, const TQuat< T > &B)
TQuat<T>::Error with auto-normalization.
static FORCEINLINE TQuat< T > FastBilerp (const TQuat< T > &P00, const TQuat< T > &P10, const TQuat< T > &P01, const TQuat< T > &P11, T FracX, T FracY)
Bi-Linear Quaternion interpolation.
static FORCEINLINE TQuat< T > FastLerp (const TQuat< T > &A, const TQuat< T > &B, const T Alpha)
Fast Linear Quaternion Interpolation.
static FORCEINLINE TQuat< T > FindBetween (const TVector< T > &Vector1, const TVector< T > &Vector2)
Generates the 'smallest' (geodesic) rotation between two vectors of arbitrary length.
static TQuat< T > FindBetweenNormals (const TVector< T > &Normal1, const TVector< T > &Normal2)
Generates the 'smallest' (geodesic) rotation between two normals (assumed to be unit length).
static TQuat< T > FindBetweenVectors (const TVector< T > &Vector1, const TVector< T > &Vector2)
Generates the 'smallest' (geodesic) rotation between two vectors of arbitrary length.
static TQuat< T > MakeFromEuler (const TVector< T > &Euler)
Convert a vector of floating-point Euler angles (in degrees) into a Quaternion.
static TQuat MakeFromLUFEuler (const TTuple< T, T, T > &InLUFEuler)
static TQuat< T > MakeFromRotationVector (const TVector< T > &RotationVector)
Constructs a quaternion corresponding to the rotation vector.
static FORCEINLINE TQuat< T > MakeFromRotator (const TRotator< T > &R)
static FORCEINLINE TQuat< T > MakeFromVectorRegister (QuatVectorRegister V)
static FORCEINLINE TQuat< T > Slerp (const TQuat< T > &Quat1, const TQuat< T > &Quat2, T Slerp)
Spherical interpolation.
static TQuat< T > Slerp_NotNormalized (const TQuat< T > &Quat1, const TQuat< T > &Quat2, T Slerp)
Spherical interpolation.
static FORCEINLINE TQuat< T > SlerpFullPath (const TQuat< T > &quat1, const TQuat< T > &quat2, T Alpha)
Simpler Slerp that doesn't do any checks for 'shortest distance' etc.
static TQuat< T > SlerpFullPath_NotNormalized (const TQuat< T > &quat1, const TQuat< T > &quat2, T Alpha)
Simpler Slerp that doesn't do any checks for 'shortest distance' etc.
static TQuat< T > Squad (const TQuat< T > &quat1, const TQuat< T > &tang1, const TQuat< T > &quat2, const TQuat< T > &tang2, T Alpha)
Given start and end quaternions of quat1 and quat2, and tangents at those points tang1 and tang2, calculate the point at Alpha (between 0 and 1) between them.
static TQuat< T > SquadFullPath (const TQuat< T > &quat1, const TQuat< T > &tang1, const TQuat< T > &quat2, const TQuat< T > &tang2, T Alpha)
Simpler Squad that doesn't do any checks for 'shortest distance' etc.
Data Fields
T W
The quaternion's W-component.
T X
The quaternion's X-component.
T Y
The quaternion's Y-component.
T Z
The quaternion's Z-component.
Static Public Attributes
static const TQuat< T > Identity
Identity quaternion.
Protected Member Functions
TQuat (QuatVectorRegister V)
Creates and initializes a new quaternion from the XYZW values in the given VectorRegister4Float.
Detailed Description
template<typename T>
struct UE::Math::TQuat< T >
Floating point quaternion that can represent a rotation about an axis in 3-D space.
The X, Y, Z, W components also double as the Axis/Angle format.
Order matters when composing quaternions: C = A * B will yield a quaternion C that logically first applies B then A to any subsequent transformation (right first, then left). Note that this is the opposite order of FTransform multiplication.
Example: LocalToWorld = (LocalToWorld * DeltaRotation) will change rotation in local space by DeltaRotation. Example: LocalToWorld = (DeltaRotation * LocalToWorld) will change rotation in world space by DeltaRotation.
Definition at line 38 of file Quat.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TQuat< T >::FReal = T
Type of the template param (float or double)
Definition at line 45 of file Quat.h.
QuatVectorRegister
template<typename T> using UE::Math::TQuat< T >::QuatVectorRegister = TVectorRegisterType<T>
Definition at line 46 of file Quat.h.
Constructor & Destructor Documentation
TQuat() [1/9]
template<typename T> UE::Math::TQuat< T >::TQuat () nodiscard default
Default constructor (no initialization).
Referenced by AngularDistance(), EnforceShortestArcWith(), Equals(), Error(), ErrorAutoNormalize(), FastBilerp(), FastLerp(), GetNormalized(), GetShortestArcWith(), Identical(), Inverse(), MakeFromLUFEuler(), MakeFromRotationVector(), UE::Math::TQuat< double >::MakeFromRotator(), UE::Math::TQuat< double >::MakeFromVectorRegister(), operator!=(), operator*(), UE::Math::TQuat< double >::operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), UE::Math::TQuat< double >::operator/(), operator==(), operator|(), and ToRotationVector().
TQuat() [2/9]
template<typename T> FORCEINLINE UE::Math::TQuat< T >::TQuat (EForceInit ZeroOrNot) explicit nodiscard
Creates and initializes a new quaternion, with the W component either 0 or 1.
Parameters
EForceInit Force init enum: if equal to ForceInitToZero then W is 0, otherwise W = 1 (creating an identity transform)
Definition at line 869 of file Quat.h.
References ForceInitToZero, FORCEINLINE, W, X, Y, and Z.
TQuat() [3/9]
template<typename T> FORCEINLINE UE::Math::TQuat< T >::TQuat (T InX, T InY, T InZ, T InW) nodiscard
Constructor.
Parameters
InX X component of the quaternion
InY Y component of the quaternion
InZ Z component of the quaternion
InW W component of the quaternion
Definition at line 874 of file Quat.h.
References DiagnosticCheckNaN(), FORCEINLINE, TIsFloatingPoint< T >::Value, W, X, Y, and Z.
TQuat() [4/9]
template<typename T> template<typename DummyT = T UE_REQUIRES(std::is_arithmetic_v<T>)> FORCEINLINE UE::Math::TQuat< T >::TQuat (T V) inline explicit nodiscard
Initializes all elements to V.
Definition at line 91 of file Quat.h.
TQuat() [5/9]
template<typename T> FORCEINLINE UE::Math::TQuat< T >::TQuat (QuatVectorRegister V) explicit nodiscard protected
Creates and initializes a new quaternion from the XYZW values in the given VectorRegister4Float.
Parameters
V XYZW components of the quaternion packed into a single VectorRegister4Float
Definition at line 885 of file Quat.h.
References DiagnosticCheckNaN(), FORCEINLINE, and VectorStoreAligned().
TQuat() [6/9]
template<typename T> FORCEINLINE UE::Math::TQuat< T >::TQuat (const TRotator< T > & R) explicit
Creates and initializes a new quaternion from the given rotator.
Parameters
R The rotator to initialize from.
Definition at line 853 of file Quat.h.
References DiagnosticCheckNaN(), FORCEINLINE, and R.
TQuat() [7/9]
template<typename T> UE::Math::TQuat< T >::TQuat (const TMatrix< T > & M) inline explicit
Creates and initializes a new quaternion from the given matrix.
Parameters
M The rotation matrix to initialize from.
Definition at line 777 of file Quat.h.
References DiagnosticCheckNaN(), ensure, UE::Math::TMatrix< T >::GetScaledAxis(), Identity, UE::Math::TMatrix< T >::M, UE_KINDA_SMALL_NUMBER, EAxis::X, EAxis::Y, and EAxis::Z.
TQuat() [8/9]
template<typename T> FORCEINLINE UE::Math::TQuat< T >::TQuat (TVector< T > Axis, T AngleRad)
Creates and initializes a new quaternion from the a rotation around the given axis.
Parameters
Axis assumed to be a normalized vector
Angle angle to rotate above the given axis (in radians)
Definition at line 914 of file Quat.h.
References Axis, DiagnosticCheckNaN(), FORCEINLINE, FMath::SinCos(), W, X, Y, and Z.
TQuat() [9/9]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TQuat< T >::TQuat (const TQuat< FArg > & From) inline explicit
Definition at line 732 of file Quat.h.
Member Function Documentation
AngularDistance()
template<typename T> T UE::Math::TQuat< T >::AngularDistance (const TQuat< T > & Q) const nodiscard
Find the angular distance between two rotation quaternions (in radians)
Definition at line 1230 of file Quat.h.
References TQuat(), W, X, Y, and Z.
CalcTangents()
template<typename T> void UE::Math::TQuat< T >::CalcTangents (const TQuat< T > & PrevP, const TQuat< T > & P, const TQuat< T > & NextP, T Tension, TQuat< T > & OutTan) static
Calculate tangents between given points.
Parameters
PrevP quaternion at P-1
P quaternion to return the tangent
NextP quaternion P+1
Tension
Todo
document
Parameters
OutTan Out control point
ContainsNaN()
template<typename T> FORCEINLINE bool UE::Math::TQuat< T >::ContainsNaN () const nodiscard
Utility to check if there are any non-finite values (NaN or Inf) in this Quat.
Returns
true if there are any non-finite values in this Quaternion, otherwise false.
Definition at line 1394 of file Quat.h.
References FORCEINLINE, W, X, Y, and Z.
DiagnosticCheckNaN() [1/2]
template<typename T> FORCEINLINE void UE::Math::TQuat< T >::DiagnosticCheckNaN () const inline
Definition at line 607 of file Quat.h.
Referenced by TQuat(), TQuat(), TQuat(), TQuat(), TQuat(), UE::Math::TQuat< double >::TQuat(), InitFromString(), operator*=(), UE::Math::TQuat< double >::operator*=(), operator+=(), operator-=(), and UE::Math::TQuat< double >::operator/=().
DiagnosticCheckNaN() [2/2]
template<typename T> FORCEINLINE void UE::Math::TQuat< T >::DiagnosticCheckNaN (const TCHAR * Message) const inline
Definition at line 608 of file Quat.h.
EnforceShortestArcWith()
template<typename T> FORCEINLINE void UE::Math::TQuat< T >::EnforceShortestArcWith (const TQuat< T > & OtherQuat)
Enforce that the delta between this Quaternion and another one represents the shortest possible rotation angle.
Definition at line 1276 of file Quat.h.
References TQuat(), FORCEINLINE, W, X, Y, and Z.
Referenced by AnimationMath::SimpleSpringDamperQuat().
Equals()
template<typename T> FORCEINLINE bool UE::Math::TQuat< T >::Equals (const TQuat< T > & Q, T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Checks whether another Quaternion is equal to this, within specified tolerance.
Parameters
Q The other Quaternion.
Tolerance Error tolerance for comparison with other Quaternion.
Returns
true if two Quaternions are equal, within specified tolerance, otherwise false.
Definition at line 985 of file Quat.h.
References TQuat(), A, B, FORCEINLINE, VectorAbs(), VectorAdd(), VectorAnyGreaterThan(), VectorLoadAligned(), VectorLoadFloat1(), VectorSubtract(), W, X, Y, and Z.
Referenced by IsIdentity().
Error()
template<typename T> FORCEINLINE T UE::Math::TQuat< T >::Error (const TQuat< T > & Q1, const TQuat< T > & Q2) static nodiscard
Error measure (angle) between two quaternions, ranged [0..1].
Returns the hypersphere-angle between two quaternions; alignment shouldn't matter, though
Note
normalized input is expected.
Definition at line 1349 of file Quat.h.
References TQuat(), FORCEINLINE, UE_PI, W, X, Y, and Z.
Referenced by ErrorAutoNormalize().
ErrorAutoNormalize()
template<typename T> FORCEINLINE T UE::Math::TQuat< T >::ErrorAutoNormalize (const TQuat< T > & A, const TQuat< T > & B) static nodiscard
TQuat<T>::Error with auto-normalization.
Definition at line 1357 of file Quat.h.
References TQuat(), A, B, Error(), FORCEINLINE, and Normalize().
Euler()
template<typename T> TVector< T > UE::Math::TQuat< T >::Euler () const nodiscard
Convert a Quaternion into floating-point Euler angles (in degrees).
Referenced by ToLUFEuler().
Exp()
template<typename T> TQuat< T > UE::Math::TQuat< T >::Exp () const nodiscard
Note
Exp should really only be used after Log. Assumes a quaternion with W=0 and V=theta*v (where |v| = 1). Exp(q) = (sin(theta)*v, cos(theta))
Referenced by MakeFromRotationVector(), and AnimationMath::QuatFromScaledAngleAxis().
FastBilerp()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::FastBilerp (const TQuat< T > & P00, const TQuat< T > & P10, const TQuat< T > & P01, const TQuat< T > & P11, T FracX, T FracY) static nodiscard
Bi-Linear Quaternion interpolation.
Result is NOT normalized.
Definition at line 1383 of file Quat.h.
References TQuat(), FastLerp(), and FORCEINLINE.
FastLerp()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::FastLerp (const TQuat< T > & A, const TQuat< T > & B, const T Alpha) static nodiscard
Fast Linear Quaternion Interpolation.
Result is NOT normalized.
Definition at line 1373 of file Quat.h.
References TQuat(), A, Alpha, B, and FORCEINLINE.
Referenced by UE::Math::TTransform< double >::Blend(), UE::Math::TTransform< double >::BlendWith(), and FastBilerp().
FindBetween()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::FindBetween (const TVector< T > & Vector1, const TVector< T > & Vector2) inline static nodiscard
Generates the 'smallest' (geodesic) rotation between two vectors of arbitrary length.
Definition at line 616 of file Quat.h.
FindBetweenNormals()
template<typename T> TQuat< T > UE::Math::TQuat< T >::FindBetweenNormals (const TVector< T > & Normal1, const TVector< T > & Normal2) static nodiscard
Generates the 'smallest' (geodesic) rotation between two normals (assumed to be unit length).
FindBetweenVectors()
template<typename T> TQuat< T > UE::Math::TQuat< T >::FindBetweenVectors (const TVector< T > & Vector1, const TVector< T > & Vector2) static nodiscard
Generates the 'smallest' (geodesic) rotation between two vectors of arbitrary length.
Referenced by UE::Math::TQuat< double >::FindBetween().
GetAngle()
template<typename T> FORCEINLINE T UE::Math::TQuat< T >::GetAngle () const nodiscard
Get the angle in radians of this quaternion.
Warning
: The rotation returned may not be the shortest version. You may wish to call GetShortestArcWith(FQuat::Identity) first.
Definition at line 1174 of file Quat.h.
References FORCEINLINE, and W.
Referenced by FBuoyancyComponentSim::ApplyTorqueForDownstreamAngularRotation(), ToAxisAndAngle(), and ToAxisAndAngle().
GetAxisX()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::GetAxisX () const nodiscard
Get the forward direction (X axis) after it has been rotated by this Quaternion.
Definition at line 1296 of file Quat.h.
References FORCEINLINE, and RotateVector().
Referenced by FUpdatedComponentAsyncInput::GetForwardVector(), GetForwardVector(), and Vector().
GetAxisY()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::GetAxisY () const nodiscard
Get the right direction (Y axis) after it has been rotated by this Quaternion.
Definition at line 1303 of file Quat.h.
References FORCEINLINE, and RotateVector().
Referenced by FUpdatedComponentAsyncInput::GetRightVector(), and GetRightVector().
GetAxisZ()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::GetAxisZ () const nodiscard
Get the up direction (Z axis) after it has been rotated by this Quaternion.
Definition at line 1310 of file Quat.h.
References FORCEINLINE, and RotateVector().
Referenced by FUpdatedComponentAsyncInput::GetUpVector(), and GetUpVector().
GetForwardVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::GetForwardVector () const nodiscard
Get the forward direction (X axis) after it has been rotated by this Quaternion.
Definition at line 1317 of file Quat.h.
References FORCEINLINE, and GetAxisX().
GetNormalized()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::GetNormalized (T Tolerance = UE_SMALL_NUMBER) const nodiscard
Get a normalized copy of this quaternion.
If it is too small, returns an identity quaternion.
Parameters
Tolerance Minimum squared length of quaternion for normalization.
Definition at line 1140 of file Quat.h.
References TQuat(), and FORCEINLINE.
Referenced by UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend(), FRotationConversionCache::QuatToRotator(), FRotationConversionCache::QuatToRotator_ReadOnly(), UE::Math::TQuat< double >::Slerp(), and UE::Math::TQuat< double >::SlerpFullPath().
GetRightVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::GetRightVector () const nodiscard
Get the right direction (Y axis) after it has been rotated by this Quaternion.
Definition at line 1323 of file Quat.h.
References FORCEINLINE, and GetAxisY().
GetRotationAxis()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::GetRotationAxis () const nodiscard
Get the axis of rotation of the Quaternion.
This is the axis around which rotation occurs to transform the canonical coordinate system to the target orientation. For the identity Quaternion which has no such rotation, TVector<T>(1,0,0) is returned.
Definition at line 1210 of file Quat.h.
References A, FORCEINLINE, R, Scale, UE_SMALL_NUMBER, VectorLoadAligned(), VectorSet_W0(), VectorStoreFloat3(), X, UE::Math::TVector< T >::XAxisVector, Y, and Z.
Referenced by FBuoyancyComponentSim::ApplyTorqueForDownstreamAngularRotation(), ToAxisAndAngle(), and ToAxisAndAngle().
GetShortestArcWith()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::GetShortestArcWith (const TQuat< T > & OtherQuat) const nodiscard
Returns the version of this quaternion that represents the shortest rotation angle to the other quaternion.
Definition at line 1288 of file Quat.h.
References TQuat(), and FORCEINLINE.
GetTwistAngle()
template<typename T> T UE::Math::TQuat< T >::GetTwistAngle (const TVector< T > & TwistAxis) const nodiscard
Get the twist angle (in radians) for a specified axis.
Parameters
TwistAxis Axis to use for decomposition
Returns
Twist angle (in radians)
Warning
assumes normalized quaternion and twist axis
GetUpVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::GetUpVector () const nodiscard
Get the up direction (Z axis) after it has been rotated by this Quaternion.
Definition at line 1329 of file Quat.h.
References FORCEINLINE, and GetAxisZ().
Identical()
template<typename T> FORCEINLINE bool UE::Math::TQuat< T >::Identical (const TQuat< T > * Q, const uint32 PortFlags) const nodiscard
Identical implementation for TQuat properties.
Avoids intrinsics to remain consistent with previous per-property comparison.
Definition at line 1068 of file Quat.h.
References TQuat(), FORCEINLINE, W, X, Y, and Z.
InitFromString()
template<typename T> bool UE::Math::TQuat< T >::InitFromString (const FString & InSourceString) inline
Initialize this TQuat from a FString.
The string is expected to contain X=, Y=, Z=, W=, otherwise this TQuat will have indeterminate (invalid) values.
Parameters
InSourceString FString containing the quaternion values.
Returns
true if the TQuat was initialized; false otherwise.
Definition at line 899 of file Quat.h.
References DiagnosticCheckNaN(), TEXT, FParse::Value(), W, X, Y, and Z.
Inverse()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::Inverse () const nodiscard
Returns
inverse of this quaternion
Warning
: Requires this quaternion to be normalized.
Definition at line 1264 of file Quat.h.
References TQuat(), checkSlow, FORCEINLINE, IsNormalized(), VectorLoadAligned(), W, X, Y, and Z.
Referenced by AnimationMath::SimpleSpringDamperQuat().
IsIdentity()
template<typename T> FORCEINLINE bool UE::Math::TQuat< T >::IsIdentity (T Tolerance = UE_SMALL_NUMBER) const nodiscard
Checks whether this Quaternion is an Identity Quaternion.
Assumes Quaternion tested is normalized.
Parameters
Tolerance Error tolerance for comparison with Identity Quaternion.
Returns
true if Quaternion is a normalized Identity Quaternion.
Definition at line 1002 of file Quat.h.
References Equals(), FORCEINLINE, and Identity.
IsNormalized()
template<typename T> FORCEINLINE bool UE::Math::TQuat< T >::IsNormalized () const nodiscard
Definition at line 1149 of file Quat.h.
References A, FORCEINLINE, SizeSquared(), UE_THRESH_QUAT_NORMALIZED, VectorAbs(), VectorAnyGreaterThan(), VectorDot4(), VectorLoadAligned(), and VectorSubtract().
Referenced by UE::Math::TQuatRotationTranslationMatrix< T >::TQuatRotationTranslationMatrix(), Inverse(), and ToRotationVector().
Log()
template<typename T> TQuat< T > UE::Math::TQuat< T >::Log () const nodiscard
Returns
quaternion with W=0 and V=theta*v.
Warning
: The rotation returned may not be the shortest version. You may wish to call GetShortestArcWith(FQuat::Identity) first.
Referenced by AnimationMath::QuatToScaledAngleAxis().
MakeFromEuler()
template<typename T> TQuat< T > UE::Math::TQuat< T >::MakeFromEuler (const TVector< T > & Euler) static
Convert a vector of floating-point Euler angles (in degrees) into a Quaternion.
Parameters
Euler the Euler angles
Returns
constructed TQuat
MakeFromLUFEuler()
template<typename T> TQuat< T > UE::Math::TQuat< T >::MakeFromLUFEuler (const TTuple< T, T, T > & InLUFEuler) static nodiscard
Definition at line 1439 of file Quat.h.
References TQuat(), UE::Math::TVector< T >::ForwardVector, UE::Math::TVector< T >::LeftVector, and UE::Math::TVector< T >::UpVector.
MakeFromRotationVector()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::MakeFromRotationVector (const TVector< T > & RotationVector) static nodiscard
Constructs a quaternion corresponding to the rotation vector.
The direction of the vector represents the rotation axis, and the magnitude the angle in radians.
Definition at line 1203 of file Quat.h.
References TQuat(), Exp(), FORCEINLINE, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
MakeFromRotator()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::MakeFromRotator (const TRotator< T > & R) inline static nodiscard
Definition at line 122 of file Quat.h.
MakeFromVectorRegister()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::MakeFromVectorRegister (QuatVectorRegister V) inline static nodiscard
Definition at line 110 of file Quat.h.
NetSerialize()
template<typename T> bool UE::Math::TQuat< T >::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess)
Serializes the vector compressed for e.g.
network transmission.
Parameters
Ar Archive to serialize to/ from.
Returns
false to allow the ordinary struct code to run (this never happens).
Normalize()
template<typename T> FORCEINLINE void UE::Math::TQuat< T >::Normalize (T Tolerance = UE_SMALL_NUMBER)
Normalize this quaternion if it is large enough.
If it is too small, returns an identity quaternion.
Parameters
Tolerance Minimum squared length of quaternion for normalization.
Definition at line 1107 of file Quat.h.
References FORCEINLINE, Identity, Scale, Vector(), VectorCompareGE(), VectorDot4(), VectorLoadAligned(), VectorLoadFloat1(), VectorMultiply(), VectorSelect(), VectorStoreAligned(), W, X, Y, and Z.
Referenced by ErrorAutoNormalize(), FQuatFixed32NoW::FromQuat(), FQuatFixed48NoW::FromQuat(), FQuatFloat32NoW::FromQuat(), FQuatFloat96NoW::FromQuat(), FQuatIntervalFixed32NoW::FromQuat(), AEFConstantKeyLerp< FORMAT >::GetBoneAtomRotation(), AEFVariableKeyLerp< FORMAT >::GetBoneAtomRotation(), AnimationCompressionUtils::Interpolate< FQuat4d >(), and AnimationCompressionUtils::Interpolate< FQuat4f >().
operator!=()
template<typename T> FORCEINLINE bool UE::Math::TQuat< T >::operator!= (const TQuat< T > & Q) const nodiscard
Checks whether two quaternions are not identical.
Parameters
Q The other quaternion.
Returns
true if two quaternion are not identical, otherwise false.
Definition at line 1087 of file Quat.h.
References TQuat(), A, B, FORCEINLINE, VectorCompareNE(), VectorLoadAligned(), VectorMaskBits(), W, X, Y, and Z.
operator*() [1/4]
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator* (const FArg Scale) const inline nodiscard
Get the result of scaling this quaternion.
Parameters
Scale The scaling factor.
Returns
The result of scaling.
Definition at line 278 of file Quat.h.
operator*() [2/4]
template<typename T> TMatrix< T > UE::Math::TQuat< T >::operator* (const TMatrix< T > & M) const nodiscard
Multiply this by a matrix.
This matrix conversion came from http://www.m-hikari.com/ija/ija-password-2008/ija-password17-20-2008/aristidouIJA17-20-2008.pdf used for non-uniform scaling transform.
Parameters
M Matrix to multiply by.
Returns
Matrix result after multiplication.
operator*() [3/4]
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator* (const TQuat< T > & Q) const nodiscard
Gets the result of multiplying this by another quaternion (this * Q).
Order matters when composing quaternions: C = A * B will yield a quaternion C that logically first applies B then A to any subsequent transformation (right first, then left).
Parameters
Q The Quaternion to multiply this by.
Returns
The result of multiplication (this * Q).
Definition at line 1028 of file Quat.h.
References TQuat(), FORCEINLINE, and VectorQuaternionMultiply().
operator*() [4/4]
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::operator* (const TVector< T > & V) const nodiscard
Rotate a vector by this quaternion.
Parameters
V the vector to be rotated
Returns
vector after rotation
See also
RotateVector
Definition at line 860 of file Quat.h.
References FORCEINLINE, and RotateVector().
operator*=() [1/2]
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator*= (const FArg Scale) inline
Multiply this quaternion by a scaling factor.
Parameters
Scale The scaling factor.
Returns
a reference to this after scaling.
Definition at line 254 of file Quat.h.
operator*=() [2/2]
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator*= (const TQuat< T > & Q)
Multiply this by a quaternion (this = this * Q).
Order matters when composing quaternions: C = A * B will yield a quaternion C that logically first applies B then A to any subsequent transformation (right first, then left).
Parameters
Q the quaternion to multiply this by.
Returns
The result of multiplication (this * Q).
Definition at line 1040 of file Quat.h.
References TQuat(), A, B, DiagnosticCheckNaN(), FORCEINLINE, VectorLoadAligned(), VectorQuaternionMultiply2(), and VectorStoreAligned().
operator+()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator+ (const TQuat< T > & Q) const nodiscard
Gets the result of adding a Quaternion to this.
This is a component-wise addition; composing quaternions should be done via multiplication.
Parameters
Q The Quaternion to add.
Returns
The result of addition.
Definition at line 930 of file Quat.h.
References TQuat(), A, B, FORCEINLINE, VectorAdd(), VectorLoadAligned(), W, X, Y, and Z.
operator+=()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator+= (const TQuat< T > & Q)
Adds to this quaternion.
This is a component-wise addition; composing quaternions should be done via multiplication.
Parameters
Other The quaternion to add to this.
Returns
Result after addition.
Definition at line 943 of file Quat.h.
References TQuat(), A, B, DiagnosticCheckNaN(), FORCEINLINE, VectorAdd(), VectorLoadAligned(), VectorStoreAligned(), W, X, Y, and Z.
operator-() [1/2]
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator- () const nodiscard
Negates the quaternion.
Note that this represents the same rotation.
Returns
The result of negation.
Definition at line 975 of file Quat.h.
References TQuat(), FORCEINLINE, VectorLoadAligned(), VectorNegate(), W, X, Y, and Z.
operator-() [2/2]
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator- (const TQuat< T > & Q) const nodiscard
Gets the result of subtracting a Quaternion to this.
This is a component-wise subtraction; composing quaternions should be done via multiplication.
Parameters
Q The Quaternion to subtract.
Returns
The result of subtraction.
Definition at line 963 of file Quat.h.
References TQuat(), A, B, FORCEINLINE, VectorLoadAligned(), VectorSubtract(), W, X, Y, and Z.
operator-=()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator-= (const TQuat< T > & Q)
Subtracts another quaternion from this.
This is a component-wise subtraction; composing quaternions should be done via multiplication.
Parameters
Q The other quaternion.
Returns
reference to this after subtraction.
Definition at line 1008 of file Quat.h.
References TQuat(), A, B, DiagnosticCheckNaN(), FORCEINLINE, VectorLoadAligned(), VectorStoreAligned(), VectorSubtract(), W, X, Y, and Z.
operator/()
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator/ (const FArg Scale) const inline nodiscard
Divide this quaternion by scale.
Parameters
Scale What to divide by.
Returns
new Quaternion of this after division by scale.
Definition at line 321 of file Quat.h.
operator/=()
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::operator/= (const FArg Scale) inline
Divide this quaternion by scale.
Parameters
Scale What to divide by.
Returns
a reference to this after scaling.
Definition at line 296 of file Quat.h.
operator==()
template<typename T> FORCEINLINE bool UE::Math::TQuat< T >::operator== (const TQuat< T > & Q) const nodiscard
Checks whether two quaternions are identical.
This is an exact comparison per-component;see Equals() for a comparison that allows for a small error tolerance and flipped axes of rotation.
Parameters
Q The other quaternion.
Returns
true if two quaternion are identical, otherwise false.
See also
Equals
Definition at line 1074 of file Quat.h.
References TQuat(), A, B, FORCEINLINE, VectorCompareEQ(), VectorLoadAligned(), VectorMaskBits(), W, X, Y, and Z.
operator|()
template<typename T> FORCEINLINE T UE::Math::TQuat< T >::operator| (const TQuat< T > & Q) const nodiscard
Calculates dot product of two quaternions.
Parameters
Q The other quaternions.
Returns
The dot product.
Definition at line 1100 of file Quat.h.
References TQuat(), FORCEINLINE, W, X, Y, and Z.
RotateVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::RotateVector (TVector< T > V) const nodiscard
Rotate a vector by this quaternion.
Parameters
V the vector to be rotated
Returns
vector after rotation
Definition at line 1238 of file Quat.h.
References UE::Math::TVector< T >::CrossProduct(), FORCEINLINE, W, X, Y, and Z.
Referenced by GetAxisX(), GetAxisY(), GetAxisZ(), operator*(), and FBeamParticleModifierPayloadData::UpdateTangent().
Rotator()
template<typename T> TRotator< T > UE::Math::TQuat< T >::Rotator () const nodiscard
Get the TRotator<T> representation of this Quaternion.
Referenced by UE::Math::TRotationAboutPointMatrix< T >::Make(), UE::MovieScene::MultiChannelFromData(), FRotationConversionCache::NormalizedQuatToRotator(), FRotationConversionCache::NormalizedQuatToRotator_ReadOnly(), FRotationConversionCache::QuatToRotator(), FRotationConversionCache::QuatToRotator_ReadOnly(), FDisplayClusterShaderParameters_ICVFX::FCameraSettings::SetViewProjection(), and DisplayClusterTypesConverter::ToHexString().
Serialize()
template<typename T> bool UE::Math::TQuat< T >::Serialize (FArchive & Ar) inline
Definition at line 712 of file Quat.h.
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TQuat< T >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 718 of file Quat.h.
Size()
template<typename T> FORCEINLINE T UE::Math::TQuat< T >::Size () const nodiscard
Get the length of this quaternion.
Returns
The length of this quaternion.
Definition at line 1162 of file Quat.h.
References FORCEINLINE, W, X, Y, and Z.
SizeSquared()
template<typename T> FORCEINLINE T UE::Math::TQuat< T >::SizeSquared () const nodiscard
Get the length squared of this quaternion.
Returns
The length of this quaternion.
Definition at line 1168 of file Quat.h.
References FORCEINLINE, W, X, Y, and Z.
Referenced by IsNormalized().
Slerp()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::Slerp (const TQuat< T > & Quat1, const TQuat< T > & Quat2, T Slerp) inline static nodiscard
Spherical interpolation.
Will correct alignment. Result is normalized.
Definition at line 660 of file Quat.h.
Referenced by TCustomLerp< UE::Math::TQuat< T > >::Lerp().
Slerp_NotNormalized()
template<typename T> TQuat< T > UE::Math::TQuat< T >::Slerp_NotNormalized (const TQuat< T > & Quat1, const TQuat< T > & Quat2, T Slerp) static nodiscard
Spherical interpolation.
Will correct alignment. Result is NOT normalized.
Referenced by TCustomLerp< UE::Math::TQuat< T > >::BiLerp(), and UE::Math::TQuat< double >::Slerp().
SlerpFullPath()
template<typename T> FORCEINLINE TQuat< T > UE::Math::TQuat< T >::SlerpFullPath (const TQuat< T > & quat1, const TQuat< T > & quat2, T Alpha) inline static nodiscard
Simpler Slerp that doesn't do any checks for 'shortest distance' etc.
We need this for the cubic interpolation stuff so that the multiple Slerps dont go in different directions. Result is normalized.
Definition at line 677 of file Quat.h.
SlerpFullPath_NotNormalized()
template<typename T> TQuat< T > UE::Math::TQuat< T >::SlerpFullPath_NotNormalized (const TQuat< T > & quat1, const TQuat< T > & quat2, T Alpha) static nodiscard
Simpler Slerp that doesn't do any checks for 'shortest distance' etc.
We need this for the cubic interpolation stuff so that the multiple Slerps dont go in different directions. Result is NOT normalized.
Referenced by UE::Math::TQuat< double >::SlerpFullPath().
Squad()
template<typename T> TQuat< T > UE::Math::TQuat< T >::Squad (const TQuat< T > & quat1, const TQuat< T > & tang1, const TQuat< T > & quat2, const TQuat< T > & tang2, T Alpha) static nodiscard
Given start and end quaternions of quat1 and quat2, and tangents at those points tang1 and tang2, calculate the point at Alpha (between 0 and 1) between them.
Result is normalized. This will correct alignment by ensuring that the shortest path is taken.
Referenced by TCustomLerp< UE::Math::TQuat< T > >::CubicInterp().
SquadFullPath()
template<typename T> TQuat< T > UE::Math::TQuat< T >::SquadFullPath (const TQuat< T > & quat1, const TQuat< T > & tang1, const TQuat< T > & quat2, const TQuat< T > & tang2, T Alpha) static nodiscard
Simpler Squad that doesn't do any checks for 'shortest distance' etc.
Given start and end quaternions of quat1 and quat2, and tangents at those points tang1 and tang2, calculate the point at Alpha (between 0 and 1) between them. Result is normalized.
ToAxisAndAngle() [1/2]
template<typename T> FORCEINLINE void UE::Math::TQuat< T >::ToAxisAndAngle (TVector< T > & Axis, double & Angle) const
Definition at line 1188 of file Quat.h.
References Angle, Axis, FORCEINLINE, GetAngle(), and GetRotationAxis().
ToAxisAndAngle() [2/2]
template<typename T> FORCEINLINE void UE::Math::TQuat< T >::ToAxisAndAngle (TVector< T > & Axis, float & Angle) const
get the axis and angle of rotation of this quaternion
Parameters
Axis{out] Normalized rotation axis of the quaternion
Angle{out] Angle of the quaternion in radians
Warning
: Requires this quaternion to be normalized.
: The rotation returned may not be the shortest version. You may wish to call GetShortestArcWith(FQuat::Identity) first.
Definition at line 1181 of file Quat.h.
References Angle, Axis, float, FORCEINLINE, GetAngle(), and GetRotationAxis().
ToLUFEuler()
template<typename T> TTuple< T, T, T > UE::Math::TQuat< T >::ToLUFEuler () const nodiscard
Definition at line 1418 of file Quat.h.
References Euler(), W, X, Y, and Z.
ToMatrix() [1/2]
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TQuat< T >::ToMatrix () const nodiscard
Get the TMatrix<T> representation of this Quaternion.
Definition at line 1341 of file Quat.h.
References FORCEINLINE, R, and ToMatrix().
ToMatrix() [2/2]
template<typename T> void UE::Math::TQuat< T >::ToMatrix (TMatrix< T > & Mat) const
Get the TMatrix<T> representation of this Quaternion and store it in Mat.
ToRotationVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::ToRotationVector () const nodiscard
Get the rotation vector corresponding to this quaternion.
The direction of the vector represents the rotation axis, and the magnitude the angle in radians.
Warning
: Requires this quaternion to be normalized.
: The rotation returned may not be the shortest version. You may wish to call GetShortestArcWith(FQuat::Identity) first.
Definition at line 1195 of file Quat.h.
References TQuat(), checkSlow, FORCEINLINE, IsNormalized(), Log, X, Y, and Z.
ToString()
template<typename T> FORCEINLINE FString UE::Math::TQuat< T >::ToString () const nodiscard
Get a textual representation of the vector.
Returns
Text describing the vector.
Definition at line 893 of file Quat.h.
References FORCEINLINE, TEXT, W, X, Y, and Z.
Referenced by DisplayClusterTypesConverter::ToString().
ToSwingTwist()
template<typename T> void UE::Math::TQuat< T >::ToSwingTwist (const TVector< T > & InTwistAxis, TQuat< T > & OutSwing, TQuat< T > & OutTwist) const
Get the swing and twist decomposition for a specified axis.
Parameters
InTwistAxis Axis to use for decomposition
OutSwing swing component quaternion
OutTwist Twist component quaternion
Warning
assumes normalized quaternion and twist axis
UnrotateVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::UnrotateVector (TVector< T > V) const nodiscard
Rotate a vector by the inverse of this quaternion.
Parameters
V the vector to be rotated
Returns
vector after rotation by the inverse of this quaternion.
Definition at line 1254 of file Quat.h.
References UE::Math::TVector< T >::CrossProduct(), FORCEINLINE, W, X, Y, and Z.
Vector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TQuat< T >::Vector () const nodiscard
Convert a rotation into a unit vector facing in its direction.
Equivalent to GetForwardVector().
Definition at line 1335 of file Quat.h.
References FORCEINLINE, and GetAxisX().
Referenced by Normalize().
Field Documentation
Identity
template<typename T> const TQuat<T> UE::Math::TQuat< T >::Identity static
Identity quaternion.
Definition at line 63 of file Quat.h.
Referenced by TQuat(), UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate(), IsIdentity(), Normalize(), UE::Math::TTransform< double >::SetIdentity(), and UE::Math::TTransform< double >::SetIdentityZeroScale().
W
template<typename T> T UE::Math::TQuat< T >::W
The quaternion's W-component.
Definition at line 58 of file Quat.h.
Referenced by TQuat(), TQuat(), TQuat(), UE::Math::TQuatRotationTranslationMatrix< T >::TQuatRotationTranslationMatrix(), AngularDistance(), ContainsNaN(), EnforceShortestArcWith(), Equals(), Error(), FQuatFixed32NoW::FromQuat(), FQuatFixed48NoW::FromQuat(), FQuatFloat32NoW::FromQuat(), FQuatFloat96NoW::FromQuat(), FQuatIntervalFixed32NoW::FromQuat(), GetAngle(), Identical(), InitFromString(), Inverse(), Normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), UE::Math::operator<<(), UE::Math::operator<<(), operator==(), operator|(), RotateVector(), Size(), SizeSquared(), DisplayClusterTypesConverter::ToHexString(), ToLUFEuler(), FQuatFixed48NoW::ToQuat(), ToString(), and UnrotateVector().
X
template<typename T> T UE::Math::TQuat< T >::X
The quaternion's X-component.
Definition at line 49 of file Quat.h.
Referenced by TQuat(), TQuat(), TQuat(), UE::Math::TQuatRotationTranslationMatrix< T >::TQuatRotationTranslationMatrix(), AngularDistance(), UE::Math::TDualQuat< T >::AsFTransform(), ContainsNaN(), EnforceShortestArcWith(), Equals(), Error(), FQuatFixed32NoW::FromQuat(), FQuatFixed48NoW::FromQuat(), FQuatFloat32NoW::FromQuat(), FQuatFloat96NoW::FromQuat(), FQuatIntervalFixed32NoW::FromQuat(), GetRotationAxis(), Identical(), InitFromString(), Inverse(), Normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), UE::Math::operator<<(), UE::Math::operator<<(), operator==(), operator|(), AnimationMath::QuatToScaledAngleAxis(), RotateVector(), Size(), SizeSquared(), DisplayClusterTypesConverter::ToHexString(), ToLUFEuler(), FQuatFixed48NoW::ToQuat(), ToRotationVector(), ToString(), and UnrotateVector().
Y
template<typename T> T UE::Math::TQuat< T >::Y
The quaternion's Y-component.
Definition at line 52 of file Quat.h.
Referenced by TQuat(), TQuat(), TQuat(), UE::Math::TQuatRotationTranslationMatrix< T >::TQuatRotationTranslationMatrix(), AngularDistance(), UE::Math::TDualQuat< T >::AsFTransform(), ContainsNaN(), EnforceShortestArcWith(), Equals(), Error(), FQuatFixed32NoW::FromQuat(), FQuatFixed48NoW::FromQuat(), FQuatFloat32NoW::FromQuat(), FQuatFloat96NoW::FromQuat(), FQuatIntervalFixed32NoW::FromQuat(), GetRotationAxis(), Identical(), InitFromString(), Inverse(), Normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), UE::Math::operator<<(), UE::Math::operator<<(), operator==(), operator|(), AnimationMath::QuatToScaledAngleAxis(), RotateVector(), Size(), SizeSquared(), DisplayClusterTypesConverter::ToHexString(), ToLUFEuler(), FQuatFixed48NoW::ToQuat(), ToRotationVector(), ToString(), and UnrotateVector().
Z
template<typename T> T UE::Math::TQuat< T >::Z
The quaternion's Z-component.
Definition at line 55 of file Quat.h.
Referenced by TQuat(), TQuat(), TQuat(), UE::Math::TQuatRotationTranslationMatrix< T >::TQuatRotationTranslationMatrix(), AngularDistance(), UE::Math::TDualQuat< T >::AsFTransform(), ContainsNaN(), EnforceShortestArcWith(), Equals(), Error(), FQuatFixed32NoW::FromQuat(), FQuatFixed48NoW::FromQuat(), FQuatFloat32NoW::FromQuat(), FQuatFloat96NoW::FromQuat(), FQuatIntervalFixed32NoW::FromQuat(), GetRotationAxis(), Identical(), InitFromString(), Inverse(), Normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), UE::Math::operator<<(), UE::Math::operator<<(), operator==(), operator|(), AnimationMath::QuatToScaledAngleAxis(), RotateVector(), Size(), SizeSquared(), DisplayClusterTypesConverter::ToHexString(), ToLUFEuler(), FQuatFixed48NoW::ToQuat(), ToRotationVector(), ToString(), and UnrotateVector().
The documentation for this struct was generated from the following files:
MathFwd.h
Quat.h