Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicAttributeBase< ParentType > Class Template Reference
UE::Geometry::TDynamicAttributeBase< ParentType > Class Template Reference abstract
Base class for attributes that live on a dynamic mesh (or similar dynamic object)
#include "DynamicAttribute.h"
Public Member Functions
virtual ~TDynamicAttributeBase ()
virtual bool Append (const TDynamicAttributeBase &Source, const FDynamicMesh3::FAppendInfo &AppendInfo)=0
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
virtual void AppendDefaulted (const FDynamicMesh3::FAppendInfo &AppendInfo)=0
Add default-valued elements, using the AppendInfo to determine the range to add.
virtual bool CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const
Check validity of attribute.
virtual void CompactInPlace (const FCompactMaps &CompactMaps)=0
Compact the attribute in place.
virtual bool CopyIn (int RawID, void *Buffer, int BufferSize)=0
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
virtual bool CopyOut (int RawID, void *Buffer, int BufferSize) const =0
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
virtual bool CopyThroughMapping (const TDynamicAttributeBase *Source, const FMeshIndexMappings &Mapping)=0
Copy data from a different attribute to this one, using the mesh index mapping to determine the correspondence.
virtual SIZE_T GetByteCount () const
FName GetName () const
Get optional identifier for this attribute set.
virtual TDynamicAttributeBase * MakeCompactCopy (const FCompactMaps &CompactMaps, ParentType *ParentIn) const
Allocate a new compact copy of the attribute layer, optionally with a different parent.
virtual TDynamicAttributeBase * MakeCopy (ParentType *ParentIn) const =0
Allocate a new copy of the attribute layer, optionally with a different parent.
virtual TDynamicAttributeBase * MakeNew (ParentType *ParentIn) const =0
Allocate a new empty instance of the same type of attribute layer.
virtual TUniquePtr< TDynamicAttributeChangeBase< ParentType > > NewBlankChange () const =0
virtual void OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo &CollapseInfo)
Update to reflect an edge collapse in the parent mesh.
virtual void OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo &FlipInfo)
Update to reflect an edge flip in the parent mesh.
virtual void OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo &MergeInfo)
Update to reflect an edge merge in the parent mesh.
virtual void OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo &MergeInfo)
Update to reflect a vertex merge that does not resolve as a collapse or edge merge (i.e.
virtual void OnNewTriangle (int TriangleID, bool bInserted)
virtual void OnNewVertex (int VertexID, bool bInserted)
virtual void OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo &PokeInfo)
Update to reflect a face poke in the parent mesh.
virtual void OnRemoveTriangle (int TriangleID)
virtual void OnRemoveVertex (int VertexID)
virtual void OnReverseTriOrientation (int TriangleID)
virtual void OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo &SplitInfo)
Update to reflect an edge split in the parent mesh.
virtual void OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo &SplitInfo, const TArrayView< const int > &TrianglesToUpdate)
Update to reflect an edge merge in the parent mesh.
virtual void Reparent (ParentType *NewParent)=0
Update any held pointer to the parent.
void Serialize (FArchive &Ar)
Serialize to and from an archive.
void SetName (FName NameIn)
Set optional identifier for this attribute set.
Protected Member Functions
virtual void CopyParentClassData (const TDynamicAttributeBase< ParentType > &Other)
Implementation of parent-class copy.
Protected Attributes
FName Name = FName()
Optional FName identifier for this attribute set.
Friends
FArchive & operator<< (FArchive &Ar, TDynamicAttributeBase< ParentType > &Attr)
Serialization operator for TDynamicAttributeBase.
Detailed Description
template<typename ParentType>
class UE::Geometry::TDynamicAttributeBase< ParentType >
Base class for attributes that live on a dynamic mesh (or similar dynamic object)
Subclasses can override the On* functions to ensure the attribute remains up to date through changes to the dynamic object
Definition at line 66 of file DynamicAttribute.h.
Constructor & Destructor Documentation
~TDynamicAttributeBase()
template<typename ParentType> virtual UE::Geometry::TDynamicAttributeBase< ParentType >::~TDynamicAttributeBase () inline virtual
Definition at line 70 of file DynamicAttribute.h.
Member Function Documentation
Append()
template<typename ParentType> virtual bool UE::Geometry::TDynamicAttributeBase< ParentType >::Append (const TDynamicAttributeBase< ParentType > & Source, const FDynamicMesh3::FAppendInfo & AppendInfo) pure virtual
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
Returns
true if the append succeeded, false otherwise (e.g. false if the data from the source attribute was not compatible and the CopyOut failed to copy across)
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >.
AppendDefaulted()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::AppendDefaulted (const FDynamicMesh3::FAppendInfo & AppendInfo) pure virtual
Add default-valued elements, using the AppendInfo to determine the range to add.
Called when appending from a mesh that does not have this attribute.
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
CheckValidity()
template<typename ParentType> virtual bool UE::Geometry::TDynamicAttributeBase< ParentType >::CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const inline virtual
Check validity of attribute.
Parameters
bAllowNonmanifold Accept non-manifold topology as valid. Note that this should almost always be true for attributes; non-manifold overlays are generally valid.
FailMode Desired behavior if mesh is found invalid
Reimplemented in UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 164 of file DynamicAttribute.h.
CompactInPlace()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::CompactInPlace (const FCompactMaps & CompactMaps) pure virtual
Compact the attribute in place.
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
CopyIn()
template<typename ParentType> virtual bool UE::Geometry::TDynamicAttributeBase< ParentType >::CopyIn (int RawID, void * Buffer, int BufferSize) pure virtual
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
CopyOut()
template<typename ParentType> virtual bool UE::Geometry::TDynamicAttributeBase< ParentType >::CopyOut (int RawID, void * Buffer, int BufferSize) const pure virtual
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
CopyParentClassData()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::CopyParentClassData (const TDynamicAttributeBase< ParentType > & Other) inline protected virtual
Implementation of parent-class copy.
MakeCopy() and MakeCompactCopy() implementations should call this to transfer any custom data added by parent attribute set class.
Definition at line 249 of file DynamicAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Copy(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Copy().
CopyThroughMapping()
template<typename ParentType> virtual bool UE::Geometry::TDynamicAttributeBase< ParentType >::CopyThroughMapping (const TDynamicAttributeBase< ParentType > * Source, const FMeshIndexMappings & Mapping) pure virtual
Copy data from a different attribute to this one, using the mesh index mapping to determine the correspondence.
Parameters
Source copy attribute data from this source
Mapping the correspondence from Source's parent to this attribute's parent
Returns
true if the copy succeeded, false otherwise (e.g. false if the data from the source attribute was not compatible and the CopyOut failed to copy across)
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >.
GetByteCount()
template<typename ParentType> virtual SIZE_T UE::Geometry::TDynamicAttributeBase< ParentType >::GetByteCount () const inline virtual
Reimplemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 241 of file DynamicAttribute.h.
GetName()
template<typename ParentType> FName UE::Geometry::TDynamicAttributeBase< ParentType >::GetName () const inline
Get optional identifier for this attribute set.
Definition at line 77 of file DynamicAttribute.h.
MakeCompactCopy()
template<typename ParentType> virtual TDynamicAttributeBase * UE::Geometry::TDynamicAttributeBase< ParentType >::MakeCompactCopy (const FCompactMaps & CompactMaps, ParentType * ParentIn) const inline virtual
Allocate a new compact copy of the attribute layer, optionally with a different parent.
Default implementation does a full copy and then compacts it, usually derived class will want to override this with a more efficient direct compact copy implementation
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 100 of file DynamicAttribute.h.
MakeCopy()
template<typename ParentType> virtual TDynamicAttributeBase * UE::Geometry::TDynamicAttributeBase< ParentType >::MakeCopy (ParentType * ParentIn) const pure virtual
Allocate a new copy of the attribute layer, optionally with a different parent.
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Referenced by UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >::MakeCompactCopy().
MakeNew()
template<typename ParentType> virtual TDynamicAttributeBase * UE::Geometry::TDynamicAttributeBase< ParentType >::MakeNew (ParentType * ParentIn) const pure virtual
Allocate a new empty instance of the same type of attribute layer.
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
NewBlankChange()
template<typename ParentType> virtual TUniquePtr< TDynamicAttributeChangeBase< ParentType > > UE::Geometry::TDynamicAttributeBase< ParentType >::NewBlankChange () const pure virtual
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
OnCollapseEdge()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo & CollapseInfo) inline virtual
Update to reflect an edge collapse in the parent mesh.
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 186 of file DynamicAttribute.h.
OnFlipEdge()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo & FlipInfo) inline virtual
Update to reflect an edge flip in the parent mesh.
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 181 of file DynamicAttribute.h.
OnMergeEdges()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo & MergeInfo) inline virtual
Update to reflect an edge merge in the parent mesh.
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 196 of file DynamicAttribute.h.
OnMergeVertices()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo & MergeInfo) inline virtual
Update to reflect a vertex merge that does not resolve as a collapse or edge merge (i.e.
a vertex merge that resolves as bowtie creation).
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 204 of file DynamicAttribute.h.
OnNewTriangle()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnNewTriangle (int TriangleID, bool bInserted) inline virtual
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >.
Definition at line 146 of file DynamicAttribute.h.
OnNewVertex()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnNewVertex (int VertexID, bool bInserted) inline virtual
Reimplemented in UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 138 of file DynamicAttribute.h.
OnPokeTriangle()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo & PokeInfo) inline virtual
Update to reflect a face poke in the parent mesh.
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 191 of file DynamicAttribute.h.
OnRemoveTriangle()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnRemoveTriangle (int TriangleID) inline virtual
Definition at line 150 of file DynamicAttribute.h.
OnRemoveVertex()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnRemoveVertex (int VertexID) inline virtual
Definition at line 142 of file DynamicAttribute.h.
OnReverseTriOrientation()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnReverseTriOrientation (int TriangleID) inline virtual
Definition at line 154 of file DynamicAttribute.h.
OnSplitEdge()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo & SplitInfo) inline virtual
Update to reflect an edge split in the parent mesh.
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 176 of file DynamicAttribute.h.
OnSplitVertex()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo & SplitInfo, const TArrayView< const int > & TrianglesToUpdate) inline virtual
Update to reflect an edge merge in the parent mesh.
Reimplemented in UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Definition at line 209 of file DynamicAttribute.h.
Reparent()
template<typename ParentType> virtual void UE::Geometry::TDynamicAttributeBase< ParentType >::Reparent (ParentType * NewParent) pure virtual
Update any held pointer to the parent.
Implemented in UE::Geometry::TDynamicBoneAttributeBase< ParentType, AttribValueType >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FName >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FTransform >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f >, UE::Geometry::TDynamicBoneAttributeBase< FDynamicMesh3, int32 >, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >, UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >, UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >.
Serialize()
template<typename ParentType> void UE::Geometry::TDynamicAttributeBase< ParentType >::Serialize (FArchive & Ar) inline
Serialize to and from an archive.
Parameters
Ar Archive to serialize with.
Definition at line 231 of file DynamicAttribute.h.
Referenced by UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >::operator<<, and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Serialize().
SetName()
template<typename ParentType> void UE::Geometry::TDynamicAttributeBase< ParentType >::SetName (FName NameIn) inline
Set optional identifier for this attribute set.
Definition at line 80 of file DynamicAttribute.h.
Friends And Related Symbol Documentation
operator<<
template<typename ParentType> FArchive & operator<< (FArchive & Ar, TDynamicAttributeBase< ParentType > & Attr) friend
Serialization operator for TDynamicAttributeBase.
Parameters
Ar Archive to serialize with.
Attr Mesh attribute to serialize.
Returns
Passing down serializing archive.
Definition at line 220 of file DynamicAttribute.h.
Field Documentation
Name
template<typename ParentType> FName UE::Geometry::TDynamicAttributeBase< ParentType >::Name = FName() protected
Optional FName identifier for this attribute set.
Not guaranteed to be unique.
Definition at line 84 of file DynamicAttribute.h.
The documentation for this class was generated from the following file:
DynamicAttribute.h