Unreal Engine 5.6 C++ API: UE::Geometry::FImageOccupancyMap Class Reference
UE::Geometry::FImageOccupancyMap Class Reference
ImageOccupancyMap calculates and stores coverage information for a 2D image/texture, for example coverage derived from UV islands of a mesh, 2D polygons, etc.
#include "ImageOccupancyMap.h"
Public Types
using FGridSampler = TGridSampler<double>
Public Member Functions
template<typename MeshType, typename GetTriangleIDFuncType>
bool ClassifySamplesFromUVSpaceMesh (const MeshType &UVSpaceMesh, const TMeshAABBTree3< MeshType > &UVSpaceMeshSpatial, GetTriangleIDFuncType GetTriangleIDFunc=[](int32 TriangleID) { return TriangleID;}, const TArray< int32 > *UVSpaceMeshTriCharts=nullptr)
template<typename MeshType, typename GetTriangleIDFuncType>
bool ClassifySamplesFromUVSpaceMesh (const MeshType &UVSpaceMesh, GetTriangleIDFuncType GetTriangleIDFunc=[](int32 TriangleID) { return TriangleID;}, const TArray< int32 > *UVSpaceMeshTriCharts=nullptr)
Set texel type at the given X/Y.
template<typename MeshType, typename GetTriangleIDFuncType>
bool ComputeFromUVSpaceMesh (const MeshType &UVSpaceMesh, GetTriangleIDFuncType GetTriangleIDFunc=[](int32 TriangleID) { return TriangleID;}, const TArray< int32 > *UVSpaceMeshTriCharts=nullptr)
Computes the image occupancy map from a UV space mesh.
bool ComputeGutterTexelsFromGutterSamples ()
void Initialize (FImageDimensions DimensionsIn, const FImageTile &TileIn, int32 SamplesPerPixel=1)
void Initialize (FImageDimensions DimensionsIn, int32 SamplesPerPixel=1)
bool IsInterior (int64 LinearIndex) const
template<typename TexelValueType>
void ParallelProcessingPass (TFunctionRef< TexelValueType(int64 LinearIdx)> BeginTexel, TFunctionRef< void(int64 LinearIdx, float Weight, TexelValueType &)> AccumulateTexel, TFunctionRef< void(int64 LinearIdx, float Weight, TexelValueType &)> CompleteTexel, TFunctionRef< void(int64 LinearIdx, TexelValueType &)> WriteTexel, TFunctionRef< float(const FVector2i &TexelOffset)> WeightFunction, int32 FilterWidth, TArray< TexelValueType > &PassBuffer) const
int32 TexelNumSamples (int64 LinearIndex) const
Data Fields
TArray64< TTuple< int64, int64 > > BorderTexels
Set of Border Texels, Pair is <LinearIndexOfBorderTexel, LinearIndexOfNearestInteriorTexel>, so Border can be filled by directly copying from source to target.
bool bParallel = true
FImageDimensions Dimensions
Image Dimensions.
int32 GutterSize = 4
Width of the gutter.
TArray64< TTuple< int64, int64 > > GutterTexels
Set of Gutter Texels.
FGridSampler PixelSampler = FGridSampler(1)
TArray64< int32 > TexelInteriorSamples
Count of interior samples for each texel in Tile.
TArray64< int32 > TexelQueryTriangle
Integer/Triangle ID for each sample in Tile.
TArray64< FVector2f > TexelQueryUV
UV for each sample in Tile.
TArray64< int32 > TexelQueryUVChart
UV Chart ID for each texel in Tile.
TArray64< int8 > TexelType
Classification of each sample in Tile.
FImageTile Tile
Static Public Attributes
static constexpr int8 BorderTexel = 2
static constexpr int8 EmptyTexel = 0
static constexpr int8 GutterTexel = 3
static constexpr int8 InteriorTexel = 1
Protected Member Functions
void InitializePixelSampler (const int32 SamplesPerPixelIn)
Initialize the pixel sampler.
Detailed Description
ImageOccupancyMap calculates and stores coverage information for a 2D image/texture, for example coverage derived from UV islands of a mesh, 2D polygons, etc.
An optional set of gutter texels can be calculated, and correspondence between gutter texels and the nearest interior texel is stored.
In addition, a 2D coordinate (eg UV) and integer ID (eg Triangle ID) of each texel can be calculated/stored. This is not just a cache. For 'border' texels where the texel center is technically outside the mesh/polygon, but the texel rectangle may still overlap the shape, the nearest UV/Triangle is stored. This simplifies computing samples around the borders such that the shape is covered under linear interpolatione/etc.
TODO Some of the names in this class are misleading because the name mentions "Texel" but should actually say "Sample" this is because the class initially supported only one sample per texel but later multi-sampling was added
Definition at line 33 of file ImageOccupancyMap.h.
Member Typedef Documentation
FGridSampler
using UE::Geometry::FImageOccupancyMap::FGridSampler = TGridSampler<double>
Definition at line 92 of file ImageOccupancyMap.h.
Member Function Documentation
ClassifySamplesFromUVSpaceMesh() [1/2]
template<typename MeshType, typename GetTriangleIDFuncType> bool UE::Geometry::FImageOccupancyMap::ClassifySamplesFromUVSpaceMesh (const MeshType & UVSpaceMesh, const TMeshAABBTree3< MeshType > & UVSpaceMeshSpatial, GetTriangleIDFuncType GetTriangleIDFunc = [](int32 TriangleID) { return TriangleID; }, const TArray< int32 > * UVSpaceMeshTriCharts = nullptr) inline
Definition at line 148 of file ImageOccupancyMap.h.
ClassifySamplesFromUVSpaceMesh() [2/2]
template<typename MeshType, typename GetTriangleIDFuncType> bool UE::Geometry::FImageOccupancyMap::ClassifySamplesFromUVSpaceMesh (const MeshType & UVSpaceMesh, GetTriangleIDFuncType GetTriangleIDFunc = [](int32 TriangleID) { return TriangleID; }, const TArray< int32 > * UVSpaceMeshTriCharts = nullptr) inline
Set texel type at the given X/Y.
Definition at line 135 of file ImageOccupancyMap.h.
ComputeFromUVSpaceMesh()
template<typename MeshType, typename GetTriangleIDFuncType> bool UE::Geometry::FImageOccupancyMap::ComputeFromUVSpaceMesh (const MeshType & UVSpaceMesh, GetTriangleIDFuncType GetTriangleIDFunc = [](int32 TriangleID) { return TriangleID; }, const TArray< int32 > * UVSpaceMeshTriCharts = nullptr) inline
Computes the image occupancy map from a UV space mesh.
This function classifies all the samples in the image, and computes the GutterTexels mapping, if you dont want the mapping you can call ClassifySamplesFromUVSpaceMesh and compute it yourself (eg for texture baking we use filter kernel coverage to compute the GutterTexels mapping)
Parameters
UVSpaceMesh UV space mesh to compute the occupancy map from.
GetTriangleIDFunc Lambda to remap a texel's nearest triangle ID
UVSpaceMeshTriCharts Optional UVSpaceMesh triangle ID to UV chart map
Definition at line 323 of file ImageOccupancyMap.h.
ComputeGutterTexelsFromGutterSamples()
bool UE::Geometry::FImageOccupancyMap::ComputeGutterTexelsFromGutterSamples () inline
Definition at line 245 of file ImageOccupancyMap.h.
References TArray< InElementType, InAllocatorType >::Num(), ParallelFor(), TArray< InElementType, InAllocatorType >::SetNum(), and Tile.
Initialize() [1/2]
void UE::Geometry::FImageOccupancyMap::Initialize (FImageDimensions DimensionsIn, const FImageTile & TileIn, int32 SamplesPerPixel = 1) inline
Definition at line 106 of file ImageOccupancyMap.h.
References check, Dimensions, InitializePixelSampler(), UE::Geometry::FImageDimensions::IsSquare(), UE::Geometry::SamplesPerPixel, and Tile.
Initialize() [2/2]
void UE::Geometry::FImageOccupancyMap::Initialize (FImageDimensions DimensionsIn, int32 SamplesPerPixel = 1) inline
Definition at line 98 of file ImageOccupancyMap.h.
References check, Dimensions, InitializePixelSampler(), UE::Geometry::FImageDimensions::IsSquare(), UE::Geometry::SamplesPerPixel, and Tile.
InitializePixelSampler()
void UE::Geometry::FImageOccupancyMap::InitializePixelSampler (const int32 SamplesPerPixelIn) inline protected
Initialize the pixel sampler.
Parameters
SamplesPerPixelIn The desired number of samples per pixel
Definition at line 412 of file ImageOccupancyMap.h.
References TMathUtil< float >::Clamp(), PixelSampler, and TMathUtil< float >::Sqrt().
Referenced by Initialize(), and Initialize().
IsInterior()
bool UE::Geometry::FImageOccupancyMap::IsInterior (int64 LinearIndex) const inline
Returns
true if texel sample at this sample linear index is an Interior texel
Definition at line 117 of file ImageOccupancyMap.h.
References InteriorTexel, and TexelType.
ParallelProcessingPass()
template<typename TexelValueType> void UE::Geometry::FImageOccupancyMap::ParallelProcessingPass (TFunctionRef< TexelValueType(int64 LinearIdx)> BeginTexel, TFunctionRef< void(int64 LinearIdx, float Weight, TexelValueType &)> AccumulateTexel, TFunctionRef< void(int64 LinearIdx, float Weight, TexelValueType &)> CompleteTexel, TFunctionRef< void(int64 LinearIdx, TexelValueType &)> WriteTexel, TFunctionRef< float(const FVector2i &TexelOffset)> WeightFunction, int32 FilterWidth, TArray< TexelValueType > & PassBuffer) const inline
Definition at line 339 of file ImageOccupancyMap.h.
References checkSlow, Dimensions, ParallelFor(), TArray< InElementType, InAllocatorType >::SetNum(), and Weight.
TexelNumSamples()
int32 UE::Geometry::FImageOccupancyMap::TexelNumSamples (int64 LinearIndex) const inline
Returns
number of interior samples for the texel at this image linear index.
Definition at line 123 of file ImageOccupancyMap.h.
References TexelInteriorSamples.
Field Documentation
BorderTexel
int8 UE::Geometry::FImageOccupancyMap::BorderTexel = 2 static constexpr
Definition at line 47 of file ImageOccupancyMap.h.
BorderTexels
TArray64<TTuple<int64, int64> > UE::Geometry::FImageOccupancyMap::BorderTexels
Set of Border Texels, Pair is <LinearIndexOfBorderTexel, LinearIndexOfNearestInteriorTexel>, so Border can be filled by directly copying from source to target.
Definition at line 84 of file ImageOccupancyMap.h.
bParallel
bool UE::Geometry::FImageOccupancyMap::bParallel = true
Definition at line 95 of file ImageOccupancyMap.h.
Dimensions
FImageDimensions UE::Geometry::FImageOccupancyMap::Dimensions
Image Dimensions.
Definition at line 37 of file ImageOccupancyMap.h.
Referenced by Initialize(), Initialize(), and ParallelProcessingPass().
EmptyTexel
int8 UE::Geometry::FImageOccupancyMap::EmptyTexel = 0 static constexpr
Definition at line 45 of file ImageOccupancyMap.h.
GutterSize
int32 UE::Geometry::FImageOccupancyMap::GutterSize = 4
Width of the gutter.
This is actually multiplied by the diagonal length of a texel, so the gutter is generally larger than this number of pixels
Definition at line 42 of file ImageOccupancyMap.h.
GutterTexel
int8 UE::Geometry::FImageOccupancyMap::GutterTexel = 3 static constexpr
Definition at line 48 of file ImageOccupancyMap.h.
GutterTexels
TArray64<TTuple<int64, int64> > UE::Geometry::FImageOccupancyMap::GutterTexels
Set of Gutter Texels.
Pair is <LinearIndexOfGutterTexel, LinearIndexOfNearestInteriorTexel>, so Gutter can be filled by directly copying from source to target.
Definition at line 90 of file ImageOccupancyMap.h.
InteriorTexel
int8 UE::Geometry::FImageOccupancyMap::InteriorTexel = 1 static constexpr
Definition at line 46 of file ImageOccupancyMap.h.
Referenced by IsInterior().
PixelSampler
FGridSampler UE::Geometry::FImageOccupancyMap::PixelSampler = FGridSampler(1)
Definition at line 93 of file ImageOccupancyMap.h.
Referenced by InitializePixelSampler().
TexelInteriorSamples
TArray64<int32> UE::Geometry::FImageOccupancyMap::TexelInteriorSamples
Count of interior samples for each texel in Tile.
Size = Tile.GetWidth() x Tile.GetHeight().
Definition at line 60 of file ImageOccupancyMap.h.
Referenced by TexelNumSamples().
TexelQueryTriangle
TArray64<int32> UE::Geometry::FImageOccupancyMap::TexelQueryTriangle
Integer/Triangle ID for each sample in Tile.
Size = Tile.GetWidth() x Tile.GetHeight() x SamplesPerPixel.
Definition at line 72 of file ImageOccupancyMap.h.
TexelQueryUV
TArray64<FVector2f> UE::Geometry::FImageOccupancyMap::TexelQueryUV
UV for each sample in Tile.
Size = Tile.GetWidth() x Tile.GetHeight() x SamplesPerPixel.
Definition at line 66 of file ImageOccupancyMap.h.
TexelQueryUVChart
TArray64<int32> UE::Geometry::FImageOccupancyMap::TexelQueryUVChart
UV Chart ID for each texel in Tile.
Only set if UVSpaceMeshTriCharts is provided Size = Tile.GetWidth() x Tile.GetHeight().
Definition at line 78 of file ImageOccupancyMap.h.
TexelType
TArray64<int8> UE::Geometry::FImageOccupancyMap::TexelType
Classification of each sample in Tile.
Size = Tile.GetWidth() x Tile.GetHeight() x SamplesPerPixel.
Definition at line 54 of file ImageOccupancyMap.h.
Referenced by IsInterior().
Tile
FImageTile UE::Geometry::FImageOccupancyMap::Tile
Definition at line 38 of file ImageOccupancyMap.h.
Referenced by ComputeGutterTexelsFromGutterSamples(), Initialize(), and Initialize().
The documentation for this class was generated from the following file:
ImageOccupancyMap.h