Unreal Engine 5.6 C++ API: FSlateRenderingPolicy Class Reference
FSlateRenderingPolicy Class Reference abstract
Abstract base class for Slate rendering policies.
#include "RenderingPolicy.h"
Public Member Functions
FSlateRenderingPolicy (const TSharedRef< class FSlateFontServices > &InFontServices, float InPixelCenterOffset)
Creates and initializes a new instance.
virtual ~FSlateRenderingPolicy ()
Virtual destructor.
virtual void AddSceneAt (FSceneInterface *Scene, int32 Index)
virtual void ClearScenes ()
TSharedRef< class FSlateFontCache > GetFontCache () const
TSharedRef< class FSlateFontServices > GetFontServices () const
float GetPixelCenterOffset () const
virtual TSharedRef< class FSlateShaderResourceManager > GetResourceManager () const =0
virtual bool IsVertexColorInLinearSpace () const =0
Private Member Functions
FSlateRenderingPolicy (const FSlateRenderingPolicy &)
FSlateRenderingPolicy & operator= (const FSlateRenderingPolicy &)
Private Attributes
TSharedRef< FSlateFontServices > FontServices
float PixelCenterOffset
Detailed Description
Abstract base class for Slate rendering policies.
Definition at line 18 of file RenderingPolicy.h.
Constructor & Destructor Documentation
FSlateRenderingPolicy() [1/2]
FSlateRenderingPolicy::FSlateRenderingPolicy (const TSharedRef< class FSlateFontServices > & InFontServices, float InPixelCenterOffset) inline
Creates and initializes a new instance.
Parameters
InPixelCenterOffset
Definition at line 27 of file RenderingPolicy.h.
References FontServices, and PixelCenterOffset.
Referenced by FSlateRenderingPolicy(), and operator=().
~FSlateRenderingPolicy()
virtual FSlateRenderingPolicy::~FSlateRenderingPolicy () inline virtual
Virtual destructor.
Definition at line 33 of file RenderingPolicy.h.
FSlateRenderingPolicy() [2/2]
FSlateRenderingPolicy::FSlateRenderingPolicy (const FSlateRenderingPolicy &) private
References FSlateRenderingPolicy().
Member Function Documentation
AddSceneAt()
virtual void FSlateRenderingPolicy::AddSceneAt (FSceneInterface * Scene, int32 Index) inline virtual
Definition at line 48 of file RenderingPolicy.h.
References Scene.
ClearScenes()
virtual void FSlateRenderingPolicy::ClearScenes () inline virtual
Definition at line 49 of file RenderingPolicy.h.
GetFontCache()
TSharedRef< class FSlateFontCache > FSlateRenderingPolicy::GetFontCache () const
GetFontServices()
TSharedRef< class FSlateFontServices > FSlateRenderingPolicy::GetFontServices () const
GetPixelCenterOffset()
float FSlateRenderingPolicy::GetPixelCenterOffset () const inline
Definition at line 42 of file RenderingPolicy.h.
References PixelCenterOffset.
GetResourceManager()
virtual TSharedRef< class FSlateShaderResourceManager > FSlateRenderingPolicy::GetResourceManager () const pure virtual
IsVertexColorInLinearSpace()
virtual bool FSlateRenderingPolicy::IsVertexColorInLinearSpace () const pure virtual
operator=()
FSlateRenderingPolicy & FSlateRenderingPolicy::operator= (const FSlateRenderingPolicy &) private
References FSlateRenderingPolicy().
Field Documentation
FontServices
TSharedRef<FSlateFontServices> FSlateRenderingPolicy::FontServices private
Definition at line 58 of file RenderingPolicy.h.
Referenced by FSlateRenderingPolicy().
PixelCenterOffset
float FSlateRenderingPolicy::PixelCenterOffset private
Definition at line 59 of file RenderingPolicy.h.
Referenced by FSlateRenderingPolicy(), and GetPixelCenterOffset().
The documentation for this class was generated from the following file:
RenderingPolicy.h