Unreal Engine 5.6 C++ API: Metasound::FOperatorSettings Class Reference
Metasound::FOperatorSettings Class Reference
FOperatorSettings.
#include "MetasoundOperatorSettings.h"
Public Member Functions
METASOUNDGRAPHCORE_API FOperatorSettings (FSampleRate InSampleRate, float InTargetBlockRate)
FOperatorSettings constructor.
METASOUNDGRAPHCORE_API float GetActualBlockRate () const
Get the actual block rate in Hz after adhering to sample rate and SIMD alignment.
FORCEINLINE int32 GetNumFramesPerBlock () const
Get the number of audio frames in a block.
FORCEINLINE float GetSampleRate () const
Get the audio sample rate in Hz.
METASOUNDGRAPHCORE_API float GetTargetBlockRate () const
Get the target block rate in Hz.
METASOUNDGRAPHCORE_API void SetSampleRate (FSampleRate InSampleRate)
Set the audio sample rate in Hz.
METASOUNDGRAPHCORE_API void SetTargetBlockRate (float InTargetBlockRate)
Set the target block rate in Hz.
METASOUNDGRAPHCORE_API FString ToString () const
Convert to human readable string.
Private Member Functions
METASOUNDGRAPHCORE_API int32 RoundToAligned (int32 Alignment, int32 InNum) const
METASOUNDGRAPHCORE_API void Update ()
Private Attributes
float ActualBlockRate = 1.f
int32 NumFramesPerBlock = 0
FSampleRate SampleRate = 1
float TargetBlockRate = 1.f
Friends
FORCEINLINE uint32 GetTypeHash (const FOperatorSettings &InSettings)
METASOUNDGRAPHCORE_API friend bool operator< (const FOperatorSettings &InLHS, const FOperatorSettings &InRHS)
METASOUNDGRAPHCORE_API friend bool operator== (const FOperatorSettings &InLHS, const FOperatorSettings &InRHS)
Detailed Description
FOperatorSettings.
Audio settings for Metasound IOperators including audio sample rate, block rate and frames per block.
The audio SampleRate defines the number of audio samples per a second of a mono waveform.
The BlockRate defines the number of times an IOperator's execution function will be triggered per a second of audio content.
The NumFramesPerBlock defines the number of audio frames written-to and/or read-from during a single call to an IOperator's execution function.
GetNumFramesPerBlock() is required to return a value that abides by the alignment requirements of FAudioBuffer, FAlignedFloatBuffer and the math routines declared in BufferVectorOperations.h. This enables the vast majority of Metasound IOperators to take advantage of SIMD hardware accelerations.
In order to achieve SIMD alignment, desired block rates must be slightly adjusted to match the boundaries of the given sample rate and SIMD alignment. GetActualBlockRate() returns the true block rate after adhering to sample rate and SIMD boundaries.
Definition at line 40 of file MetasoundOperatorSettings.h.
Constructor & Destructor Documentation
FOperatorSettings()
METASOUNDGRAPHCORE_API Metasound::FOperatorSettings::FOperatorSettings (FSampleRate InSampleRate, float InTargetBlockRate)
FOperatorSettings constructor.
Parameters
InSampleRate - Audio sample rate in Hz.
InTargetBlockRate - The desired block rate in Hz.
References UE_API.
Referenced by GetTypeHash, operator<, and operator==.
Member Function Documentation
GetActualBlockRate()
METASOUNDGRAPHCORE_API float Metasound::FOperatorSettings::GetActualBlockRate () const
Get the actual block rate in Hz after adhering to sample rate and SIMD alignment.
References UE_API.
GetNumFramesPerBlock()
FORCEINLINE int32 Metasound::FOperatorSettings::GetNumFramesPerBlock () const inline
Get the number of audio frames in a block.
This function is required to return a value that abides by the alignment requirements of FAudioBuffer, FAlignedFloatBuffer and the math routines declared in BufferVectorOperations.h. This enables the vast majority of Metasound IOperators to take advantage of SIMD hardware accelerations.
Definition at line 84 of file MetasoundOperatorSettings.h.
References FORCEINLINE, and NumFramesPerBlock.
Referenced by Metasound::FAudioBuffer::FAudioBuffer().
GetSampleRate()
FORCEINLINE float Metasound::FOperatorSettings::GetSampleRate () const inline
Get the audio sample rate in Hz.
Definition at line 54 of file MetasoundOperatorSettings.h.
References FORCEINLINE, and SampleRate.
GetTargetBlockRate()
METASOUNDGRAPHCORE_API float Metasound::FOperatorSettings::GetTargetBlockRate () const
Get the target block rate in Hz.
References UE_API.
RoundToAligned()
METASOUNDGRAPHCORE_API int32 Metasound::FOperatorSettings::RoundToAligned (int32 Alignment, int32 InNum) const private
References UE_API.
SetSampleRate()
METASOUNDGRAPHCORE_API void Metasound::FOperatorSettings::SetSampleRate (FSampleRate InSampleRate)
Set the audio sample rate in Hz.
References UE_API.
SetTargetBlockRate()
METASOUNDGRAPHCORE_API void Metasound::FOperatorSettings::SetTargetBlockRate (float InTargetBlockRate)
Set the target block rate in Hz.
In order to achieve SIMD alignment, target block rates must be adjusted to match the boundaries of the given sample rate and SIMD alignment. GetActualBlockRate() returns the true block rate after adhering to sample rate and SIMD boundaries.
References UE_API.
ToString()
METASOUNDGRAPHCORE_API FString Metasound::FOperatorSettings::ToString () const
Convert to human readable string.
References UE_API.
Update()
METASOUNDGRAPHCORE_API void Metasound::FOperatorSettings::Update () private
References UE_API.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FOperatorSettings & InSettings) friend
Definition at line 95 of file MetasoundOperatorSettings.h.
References FOperatorSettings(), FORCEINLINE, GetTypeHash, HashCombineFast(), NumFramesPerBlock, and SampleRate.
Referenced by GetTypeHash.
operator<
METASOUNDGRAPHCORE_API friend bool operator< (const FOperatorSettings & InLHS, const FOperatorSettings & InRHS) friend
References FOperatorSettings().
operator==
METASOUNDGRAPHCORE_API friend bool operator== (const FOperatorSettings & InLHS, const FOperatorSettings & InRHS) friend
References FOperatorSettings().
Field Documentation
ActualBlockRate
float Metasound::FOperatorSettings::ActualBlockRate = 1.f private
Definition at line 112 of file MetasoundOperatorSettings.h.
NumFramesPerBlock
int32 Metasound::FOperatorSettings::NumFramesPerBlock = 0 private
Definition at line 114 of file MetasoundOperatorSettings.h.
Referenced by GetNumFramesPerBlock(), and GetTypeHash.
SampleRate
FSampleRate Metasound::FOperatorSettings::SampleRate = 1 private
Definition at line 108 of file MetasoundOperatorSettings.h.
Referenced by GetSampleRate(), and GetTypeHash.
TargetBlockRate
float Metasound::FOperatorSettings::TargetBlockRate = 1.f private
Definition at line 110 of file MetasoundOperatorSettings.h.
The documentation for this class was generated from the following file:
MetasoundOperatorSettings.h