Unreal Engine 5.6 C++ API: UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT > Class Template Reference
UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT > Class Template Reference
Wrapper around existing iterator that returns multiple values, of potentially different type, for each value that input iterator returns.
#include "IteratorUtil.h"
Public Member Functions
ExpandIterator ()
ExpandIterator (const InputIteratorT &CurItr, const InputIteratorT &EndItr, const ExpandFunctionT &ExpandFuncIn)
void goto_next ()
bool operator!= (const ExpandIterator &Other) const
OutputType operator* () const
const ExpandIterator & operator++ ()
bool operator== (const ExpandIterator &Other) const
Data Fields
InputIteratorT Cur
int CurExpandI
OutputType CurValue
InputIteratorT End
ExpandFunctionT ExpandFunc
Private Types
using ExpandFunctionT = TFunction<OutputType(InputType, int&)>
Detailed Description
template<typename OutputType, typename InputType, typename InputIteratorT>
class UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >
Wrapper around existing iterator that returns multiple values, of potentially different type, for each value that input iterator returns.
This is done via an "expansion" function that takes an int reference which indicates "where" we are in the expansion (eg like a state machine). How you use this value is up to you.
When the input is -1, you should interpret this as the "beginning" of handling the input value (ie we have not returned any values yet for this input value)
When you are "done" with an input value, set the outgoing int reference to -1 and the base iterator will be incremented.
If you have more values to return for this input value, set it to some positive number of your choosing.
See FDynamicMesh3::VtxTrianglesItr for an example
Definition at line 151 of file IteratorUtil.h.
Member Typedef Documentation
ExpandFunctionT
template<typename OutputType, typename InputType, typename InputIteratorT> using UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::ExpandFunctionT = TFunction<OutputType(InputType, int&)> private
Definition at line 153 of file IteratorUtil.h.
Constructor & Destructor Documentation
ExpandIterator() [1/2]
template<typename OutputType, typename InputType, typename InputIteratorT> UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::ExpandIterator () inline
Definition at line 156 of file IteratorUtil.h.
Referenced by operator!=(), operator++(), and operator==().
ExpandIterator() [2/2]
template<typename OutputType, typename InputType, typename InputIteratorT> UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::ExpandIterator (const InputIteratorT & CurItr, const InputIteratorT & EndItr, const ExpandFunctionT & ExpandFuncIn) inline
Definition at line 194 of file IteratorUtil.h.
References Cur, CurExpandI, End, ExpandFunc, and goto_next().
Member Function Documentation
goto_next()
template<typename OutputType, typename InputType, typename InputIteratorT> void UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::goto_next () inline
Definition at line 178 of file IteratorUtil.h.
References Cur, CurExpandI, CurValue, End, and ExpandFunc.
Referenced by ExpandIterator(), and operator++().
operator!=()
template<typename OutputType, typename InputType, typename InputIteratorT> bool UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::operator!= (const ExpandIterator< OutputType, InputType, InputIteratorT > & Other) const inline
Definition at line 162 of file IteratorUtil.h.
References ExpandIterator(), Cur, and Other.
operator*()
template<typename OutputType, typename InputType, typename InputIteratorT> OutputType UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::operator* () const inline
Definition at line 167 of file IteratorUtil.h.
References CurValue.
operator++()
template<typename OutputType, typename InputType, typename InputIteratorT> const ExpandIterator & UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::operator++ () inline
Definition at line 172 of file IteratorUtil.h.
References ExpandIterator(), and goto_next().
operator==()
template<typename OutputType, typename InputType, typename InputIteratorT> bool UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::operator== (const ExpandIterator< OutputType, InputType, InputIteratorT > & Other) const inline
Definition at line 158 of file IteratorUtil.h.
References ExpandIterator(), Cur, and Other.
Field Documentation
Cur
template<typename OutputType, typename InputType, typename InputIteratorT> InputIteratorT UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::Cur
Definition at line 203 of file IteratorUtil.h.
Referenced by ExpandIterator(), goto_next(), operator!=(), and operator==().
CurExpandI
template<typename OutputType, typename InputType, typename InputIteratorT> int UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::CurExpandI
Definition at line 206 of file IteratorUtil.h.
Referenced by ExpandIterator(), and goto_next().
CurValue
template<typename OutputType, typename InputType, typename InputIteratorT> OutputType UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::CurValue
Definition at line 205 of file IteratorUtil.h.
Referenced by goto_next(), and operator*().
End
template<typename OutputType, typename InputType, typename InputIteratorT> InputIteratorT UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::End
Definition at line 204 of file IteratorUtil.h.
Referenced by ExpandIterator(), and goto_next().
ExpandFunc
template<typename OutputType, typename InputType, typename InputIteratorT> ExpandFunctionT UE::Geometry::ExpandIterator< OutputType, InputType, InputIteratorT >::ExpandFunc
Definition at line 207 of file IteratorUtil.h.
Referenced by ExpandIterator(), and goto_next().
The documentation for this class was generated from the following file:
IteratorUtil.h