Unreal Engine 5.6 C++ API: Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData Struct Reference
Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData Struct Reference
#include "RobinHoodHashTable.h"
Data Structures
struct FIteratorState
Public Member Functions
FData ()=default
FData (const FData &)=default
~FData ()
template<typename DeducedKeyType, typename DeducedValueType>
IndexType Allocate (DeducedKeyType &&Key, DeducedValueType &&Val, FHashType Hash)
bool Contains (IndexType Index) const
void Deallocate (IndexType Index)
void Empty ()
FIteratorState End () const
KeyValueType & Get (IndexType Index)
const KeyValueType & Get (IndexType Index) const
SizeType GetAllocatedSize () const
IndexType GetMaxIndex () const
FIteratorState Next (FIteratorState State) const
SizeType Num () const
FData & operator= (const FData &)=default
void Reserve (SizeType ReserveNum)
FIteratorState Start () const
Data Fields
TFreeList< InlineOneAllocatorType > FreeList
TArray< FHashType, HashMapAllocator > Hashes
TArray< KeyValueType, HashMapAllocator > KeyVals
Detailed Description
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator>
struct Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData
Definition at line 330 of file RobinHoodHashTable.h.
Constructor & Destructor Documentation
FData() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::FData () default
Referenced by FData(), and operator=().
FData() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::FData (const FData &) default
References FData().
~FData()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::~FData () inline
Definition at line 335 of file RobinHoodHashTable.h.
References Empty().
Member Function Documentation
Allocate()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename DeducedKeyType, typename DeducedValueType> IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Allocate (DeducedKeyType && Key, DeducedValueType && Val, FHashType Hash) inline
Definition at line 346 of file RobinHoodHashTable.h.
References CHECK_CONCURRENT_ACCESS, checkSlow, Forward(), FreeList, Hash, Hashes, Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::InvalidIndex, Key, and KeyVals.
Contains()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Contains (IndexType Index) const inline
Definition at line 389 of file RobinHoodHashTable.h.
References FreeList, and KeyVals.
Referenced by Get(), and Get().
Deallocate()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> void Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Deallocate (IndexType Index) inline
Definition at line 370 of file RobinHoodHashTable.h.
References CHECK_CONCURRENT_ACCESS, FreeList, Hashes, and KeyVals.
Empty()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> void Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Empty () inline
Definition at line 461 of file RobinHoodHashTable.h.
References End(), FreeList, Hashes, Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::FIteratorState::Index, KeyVals, Next(), and Start().
Referenced by ~FData().
End()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FIteratorState Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::End () const inline
Definition at line 456 of file RobinHoodHashTable.h.
References KeyVals.
Referenced by Empty().
Get() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> KeyValueType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Get (IndexType Index) inline
Definition at line 404 of file RobinHoodHashTable.h.
References CHECK_CONCURRENT_ACCESS, Contains(), and KeyVals.
Get() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const KeyValueType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Get (IndexType Index) const inline
Definition at line 394 of file RobinHoodHashTable.h.
References CHECK_CONCURRENT_ACCESS, Contains(), and KeyVals.
GetAllocatedSize()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> SizeType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::GetAllocatedSize () const inline
Definition at line 340 of file RobinHoodHashTable.h.
References FreeList, and KeyVals.
GetMaxIndex()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::GetMaxIndex () const inline
Definition at line 419 of file RobinHoodHashTable.h.
References KeyVals.
Next()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FIteratorState Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Next (FIteratorState State) const inline
Definition at line 439 of file RobinHoodHashTable.h.
References Hashes, Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::InvalidIndex, KeyVals, and State.
Referenced by Empty(), and Start().
Num()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> SizeType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Num () const inline
Definition at line 414 of file RobinHoodHashTable.h.
References FreeList, and KeyVals.
operator=()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FData & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::operator= (const FData &) default
References FData().
Reserve()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> void Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Reserve (SizeType ReserveNum) inline
Definition at line 476 of file RobinHoodHashTable.h.
References KeyVals.
Start()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FIteratorState Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Start () const inline
Definition at line 451 of file RobinHoodHashTable.h.
References Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::InvalidIndex, and Next().
Referenced by Empty().
Field Documentation
FreeList
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> TFreeList<InlineOneAllocatorType> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::FreeList
Definition at line 487 of file RobinHoodHashTable.h.
Referenced by Allocate(), Contains(), Deallocate(), Empty(), GetAllocatedSize(), and Num().
Hashes
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> TArray<FHashType, HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Hashes
Definition at line 486 of file RobinHoodHashTable.h.
Referenced by Allocate(), Deallocate(), Empty(), and Next().
KeyVals
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> TArray<KeyValueType, HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::KeyVals
Definition at line 485 of file RobinHoodHashTable.h.
Referenced by Allocate(), Contains(), Deallocate(), Empty(), End(), Get(), Get(), GetAllocatedSize(), GetMaxIndex(), Next(), Num(), and Reserve().
The documentation for this struct was generated from the following file:
RobinHoodHashTable.h