Unreal Engine 5.6 C++ API: FAndroidAffinity Class Reference
FAndroidAffinity Class Reference
#include "AndroidPlatformAffinity.h"
Static Public Member Functions
static const uint64 GetAsyncLoadingThreadMask ()
static const uint64 GetAudioRenderThreadMask ()
static const uint64 GetMainGameMask ()
static const uint64 GetPoolThreadMask ()
static const uint64 GetRenderingThreadMask ()
static EThreadPriority GetRenderingThreadPriority ()
static const uint64 GetRHIThreadMask ()
static EThreadPriority GetRHIThreadPriority ()
static const uint64 GetRTHeartBeatMask ()
static const uint64 GetTaskGraphBackgroundTaskMask ()
static const uint64 GetTaskGraphHighPriorityTaskMask ()
static const uint64 GetTaskGraphThreadMask ()
Static Public Member Functions inherited from FGenericPlatformAffinity
static const uint64 GetAsyncLoadingThreadMask ()
static const uint64 GetAudioRenderThreadMask ()
static EThreadPriority GetGameThreadPriority ()
static const uint64 GetIoDispatcherThreadMask ()
static const uint64 GetMainGameMask ()
static const uint64 GetNoAffinityMask ()
static const uint64 GetPoolThreadMask ()
static EThreadCreateFlags GetRenderingThreadFlags ()
static const uint64 GetRenderingThreadMask ()
static EThreadPriority GetRenderingThreadPriority ()
static const uint64 GetRHIFrameOffsetThreadMask ()
static EThreadCreateFlags GetRHIThreadFlags ()
static const uint64 GetRHIThreadMask ()
static EThreadPriority GetRHIThreadPriority ()
static const uint64 GetRTHeartBeatMask ()
static EThreadPriority GetTaskBPThreadPriority ()
static const uint64 GetTaskGraphBackgroundTaskMask ()
static const uint64 GetTaskGraphHighPriorityTaskMask ()
static const uint64 GetTaskGraphThreadMask ()
static EThreadPriority GetTaskThreadPriority ()
static const uint64 GetTraceThreadMask ()
Static Public Attributes
static uint64 GameThreadMask
static uint64 RenderingThreadMask
Static Private Member Functions
static uint64 GetLittleCoreMask ()
Static Private Attributes
static const uint64 AllCores = 0xFFFFFFFFFFFFFFFF
Detailed Description
Definition at line 12 of file AndroidPlatformAffinity.h.
Member Function Documentation
GetAsyncLoadingThreadMask()
const uint64 FAndroidAffinity::GetAsyncLoadingThreadMask () inline static
Definition at line 67 of file AndroidPlatformAffinity.h.
References AllCores.
GetAudioRenderThreadMask()
const uint64 FAndroidAffinity::GetAudioRenderThreadMask () inline static
Definition at line 52 of file AndroidPlatformAffinity.h.
References GetLittleCoreMask().
GetLittleCoreMask()
uint64 FAndroidAffinity::GetLittleCoreMask () static private
Referenced by GetAudioRenderThreadMask(), GetPoolThreadMask(), GetRTHeartBeatMask(), and GetTaskGraphBackgroundTaskMask().
GetMainGameMask()
const uint64 FAndroidAffinity::GetMainGameMask () inline static
Definition at line 18 of file AndroidPlatformAffinity.h.
References GameThreadMask.
GetPoolThreadMask()
const uint64 FAndroidAffinity::GetPoolThreadMask () inline static
Definition at line 38 of file AndroidPlatformAffinity.h.
References AllCores, and GetLittleCoreMask().
GetRenderingThreadMask()
const uint64 FAndroidAffinity::GetRenderingThreadMask () inline static
Definition at line 23 of file AndroidPlatformAffinity.h.
References RenderingThreadMask.
GetRenderingThreadPriority()
EThreadPriority FAndroidAffinity::GetRenderingThreadPriority () inline static
Definition at line 72 of file AndroidPlatformAffinity.h.
References TPri_SlightlyBelowNormal.
GetRHIThreadMask()
const uint64 FAndroidAffinity::GetRHIThreadMask () inline static
Definition at line 28 of file AndroidPlatformAffinity.h.
References AllCores.
GetRHIThreadPriority()
EThreadPriority FAndroidAffinity::GetRHIThreadPriority () inline static
Definition at line 77 of file AndroidPlatformAffinity.h.
References TPri_Normal.
GetRTHeartBeatMask()
const uint64 FAndroidAffinity::GetRTHeartBeatMask () inline static
Definition at line 33 of file AndroidPlatformAffinity.h.
References GetLittleCoreMask().
GetTaskGraphBackgroundTaskMask()
const uint64 FAndroidAffinity::GetTaskGraphBackgroundTaskMask () inline static
Definition at line 57 of file AndroidPlatformAffinity.h.
References GetLittleCoreMask().
GetTaskGraphHighPriorityTaskMask()
const uint64 FAndroidAffinity::GetTaskGraphHighPriorityTaskMask () inline static
Definition at line 62 of file AndroidPlatformAffinity.h.
References AllCores.
GetTaskGraphThreadMask()
const uint64 FAndroidAffinity::GetTaskGraphThreadMask () inline static
Definition at line 47 of file AndroidPlatformAffinity.h.
References AllCores.
Field Documentation
AllCores
const uint64 FAndroidAffinity::AllCores = 0xFFFFFFFFFFFFFFFF static private
Definition at line 16 of file AndroidPlatformAffinity.h.
Referenced by GetAsyncLoadingThreadMask(), GetPoolThreadMask(), GetRHIThreadMask(), GetTaskGraphHighPriorityTaskMask(), and GetTaskGraphThreadMask().
GameThreadMask
uint64 FAndroidAffinity::GameThreadMask static
Definition at line 83 of file AndroidPlatformAffinity.h.
Referenced by GetMainGameMask().
RenderingThreadMask
uint64 FAndroidAffinity::RenderingThreadMask static
Definition at line 84 of file AndroidPlatformAffinity.h.
Referenced by GetRenderingThreadMask().
The documentation for this class was generated from the following file:
AndroidPlatformAffinity.h