Unreal Engine 5.6 C++ API: HDRHelper.h File Reference
HDRHelper.h File Reference
#include "CoreMinimal.h"
Data Structures
struct FACESTonemapParams
struct FDisplayInformation
Typedefs
using FDisplayInformationArray = TArray<FDisplayInformation>
Functions
RENDERCORE_API void ConvertPixelDataToSCRGB (TArray< FLinearColor > &InOutRawPixels, EDisplayOutputFormat Pixelformat)
RENDERCORE_API FMatrix44f GamutToXYZMatrix (EDisplayColorGamut ColorGamut)
template<class FACESTonemapParametersType>
void GetACESTonemapParameters (FACESTonemapParametersType &ACESTonemapParameters)
RENDERCORE_API void HDRAddCustomMetaData (void *OSWindow, EDisplayOutputFormat DisplayOutputFormat, EDisplayColorGamut DisplayColorGamut, bool bHDREnabled)
RENDERCORE_API void HDRConfigureCVars (bool bIsHDREnabled, uint32 DisplayNits, bool bFromGameSettings)
RENDERCORE_API EDisplayColorGamut HDRGetDefaultDisplayColorGamut ()
RENDERCORE_API EDisplayOutputFormat HDRGetDefaultDisplayOutputFormat ()
RENDERCORE_API float HDRGetDisplayMaximumLuminance ()
RENDERCORE_API void HDRGetMetaData (EDisplayOutputFormat &OutDisplayOutputFormat, EDisplayColorGamut &OutDisplayColorGamut, bool &OutbHDRSupported, const FVector2D &WindowTopLeft, const FVector2D &WindowBottomRight, void *OSWindow)
RENDERCORE_API void HDRRemoveCustomMetaData (void *OSWindow)
RENDERCORE_API bool IsDefaultBackBufferLinearSDR ()
RENDERCORE_API bool IsHDRAllowed ()
RENDERCORE_API bool IsHDREnabled ()
UE_DEPRECATED (all, "For internal use only.") RENDERCORE_API FACESTonemapParams HDRGetACESTonemapParams()
RENDERCORE_API FMatrix44f XYZToGamutMatrix (EDisplayColorGamut ColorGamut)
Typedef Documentation
FDisplayInformationArray
using FDisplayInformationArray = TArray<FDisplayInformation>
Definition at line 36 of file HDRHelper.h.
Function Documentation
ConvertPixelDataToSCRGB()
RENDERCORE_API void ConvertPixelDataToSCRGB (TArray< FLinearColor > & InOutRawPixels, EDisplayOutputFormat Pixelformat)
GamutToXYZMatrix()
RENDERCORE_API FMatrix44f GamutToXYZMatrix (EDisplayColorGamut ColorGamut)
GetACESTonemapParameters()
template<class FACESTonemapParametersType> void GetACESTonemapParameters (FACESTonemapParametersType & ACESTonemapParameters) inline
Definition at line 67 of file HDRHelper.h.
References FMath::Clamp(), GetACESTonemapParameters(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by GetACESTonemapParameters().
HDRAddCustomMetaData()
RENDERCORE_API void HDRAddCustomMetaData (void * OSWindow, EDisplayOutputFormat DisplayOutputFormat, EDisplayColorGamut DisplayColorGamut, bool bHDREnabled)
HDRConfigureCVars()
RENDERCORE_API void HDRConfigureCVars (bool bIsHDREnabled, uint32 DisplayNits, bool bFromGameSettings)
HDRGetDefaultDisplayColorGamut()
RENDERCORE_API EDisplayColorGamut HDRGetDefaultDisplayColorGamut ()
HDRGetDefaultDisplayOutputFormat()
RENDERCORE_API EDisplayOutputFormat HDRGetDefaultDisplayOutputFormat ()
HDRGetDisplayMaximumLuminance()
RENDERCORE_API float HDRGetDisplayMaximumLuminance ()
HDRGetMetaData()
RENDERCORE_API void HDRGetMetaData (EDisplayOutputFormat & OutDisplayOutputFormat, EDisplayColorGamut & OutDisplayColorGamut, bool & OutbHDRSupported, const FVector2D & WindowTopLeft, const FVector2D & WindowBottomRight, void * OSWindow)
HDRRemoveCustomMetaData()
RENDERCORE_API void HDRRemoveCustomMetaData (void * OSWindow)
IsDefaultBackBufferLinearSDR()
RENDERCORE_API bool IsDefaultBackBufferLinearSDR ()
IsHDRAllowed()
RENDERCORE_API bool IsHDRAllowed ()
IsHDREnabled()
RENDERCORE_API bool IsHDREnabled ()
UE_DEPRECATED()
UE_DEPRECATED (all , "For internal use only.")
XYZToGamutMatrix()
RENDERCORE_API FMatrix44f XYZToGamutMatrix (EDisplayColorGamut ColorGamut)