Unreal Engine 5.6 C++ API: FLandscapeComponentDataInterface Struct Reference
FLandscapeComponentDataInterface Struct Reference
#include "LandscapeDataAccess.h"
Public Member Functions
LANDSCAPE_API FLandscapeComponentDataInterface (ULandscapeComponent *InComponent, int32 InMipLevel=0, bool InWorkOnEditingLayer=true)
LANDSCAPE_API ~FLandscapeComponentDataInterface ()
uint16 GetHeight (int32 LocalX, int32 LocalY) const
uint16 GetHeight (int32 VertexIndex) const
FColor * GetHeightData (int32 LocalX, int32 LocalY) const
LANDSCAPE_API int32 GetHeightmapSizeX (int32 MipIndex) const
LANDSCAPE_API int32 GetHeightmapSizeY (int32 MipIndex) const
LANDSCAPE_API void GetHeightmapTextureData (TArray< FColor > &OutData, bool bOkToFail=false)
float GetLocalHeight (int32 LocalX, int32 LocalY) const
float GetLocalHeight (int32 VertexIndex) const
void GetLocalTangentVectors (int32 LocalX, int32 LocalY, FVector &LocalTangentX, FVector &LocalTangentY, FVector &LocalTangentZ) const
void GetLocalTangentVectors (int32 VertexIndex, FVector &LocalTangentX, FVector &LocalTangentY, FVector &LocalTangentZ) const
LANDSCAPE_API FVector GetLocalVertex (int32 LocalX, int32 LocalY) const
FVector GetLocalVertex (int32 VertexIndex) const
FColor * GetRawHeightData () const
FColor * GetRawXYOffsetData () const
LANDSCAPE_API bool GetWeightmapTextureData (ULandscapeLayerInfoObject *InLayerInfo, TArray< uint8 > &OutData, bool bInUseEditingWeightmap=false, bool bInRemoveSubsectionDuplicates=false)
LANDSCAPE_API void GetWorldPositionTangents (int32 LocalX, int32 LocalY, FVector &WorldPos, FVector &WorldTangentX, FVector &WorldTangentY, FVector &WorldTangentZ) const
void GetWorldPositionTangents (int32 VertexIndex, FVector &WorldPos, FVector &WorldTangentX, FVector &WorldTangentY, FVector &WorldTangentZ) const
LANDSCAPE_API void GetWorldTangentVectors (int32 LocalX, int32 LocalY, FVector &WorldTangentX, FVector &WorldTangentY, FVector &WorldTangentZ) const
void GetWorldTangentVectors (int32 VertexIndex, FVector &WorldTangentX, FVector &WorldTangentY, FVector &WorldTangentZ) const
LANDSCAPE_API FVector GetWorldVertex (int32 LocalX, int32 LocalY) const
FVector GetWorldVertex (int32 VertexIndex) const
void GetXYOffset (int32 VertexIndex, float &XOffset, float &YOffset) const
void GetXYOffset (int32 X, int32 Y, float &XOffset, float &YOffset) const
LANDSCAPE_API FColor * GetXYOffsetData (int32 LocalX, int32 LocalY) const
void SetRawHeightData (FColor *NewHeightData)
void SetRawXYOffsetData (FColor *NewXYOffsetData)
Public Member Functions inherited from FLandscapeComponentDataInterfaceBase
FLandscapeComponentDataInterfaceBase ()
LANDSCAPE_API FLandscapeComponentDataInterfaceBase (ULandscapeComponent *InComponent, int32 InMipLevel, bool InWorkOnEditingLayer=true)
void ComponentXYToSubsectionXY (int32 CompX, int32 CompY, int32 &SubNumX, int32 &SubNumY, int32 &SubX, int32 &SubY) const
int32 GetComponentSizeVerts () const
uint16 GetHeight (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
const FColor * GetHeightData (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
float GetLocalHeight (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
void GetLocalTangentVectors (int32 LocalX, int32 LocalY, FVector &LocalTangentX, FVector &LocalTangentY, FVector &LocalTangentZ, const TArray< FColor > &HeightAndNormals) const
FVector GetLocalVertex (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
float GetScaleFactor () const
void QuadIndexToXY (int32 QuadIndex, int32 &OutX, int32 &OutY) const
int32 TexelXYToIndex (int32 TexelX, int32 TexelY) const
int32 VertexIndexToTexel (int32 VertexIndex) const
void VertexIndexToXY (int32 VertexIndex, int32 &OutX, int32 &OutY) const
int32 VertexXYToIndex (int32 VertX, int32 VertY) const
void VertexXYToTexelXY (int32 VertX, int32 VertY, int32 &OutX, int32 &OutY) const
Private Attributes
bool bWorkOnEditingLayer
ULandscapeComponent * Component
FLandscapeDataInterface DataInterface
FColor * HeightMipData
FColor * XYOffsetMipData
Friends
struct FLandscapeDataInterface
Additional Inherited Members
Data Fields inherited from FLandscapeComponentDataInterfaceBase
int32 HeightmapComponentOffsetX = 0
int32 HeightmapComponentOffsetY = 0
int32 HeightmapStride = 0
int32 HeightmapSubsectionOffset = 0
const int32 MipLevel = 0
Protected Attributes inherited from FLandscapeComponentDataInterfaceBase
int32 ComponentNumSubsections = 0
int32 ComponentSizeQuads = 0
int32 ComponentSizeVerts = 0
int32 SubsectionSizeVerts = 0
Detailed Description
Definition at line 275 of file LandscapeDataAccess.h.
Constructor & Destructor Documentation
FLandscapeComponentDataInterface()
LANDSCAPE_API FLandscapeComponentDataInterface::FLandscapeComponentDataInterface (ULandscapeComponent * InComponent, int32 InMipLevel = 0, bool InWorkOnEditingLayer = true)
~FLandscapeComponentDataInterface()
LANDSCAPE_API FLandscapeComponentDataInterface::~FLandscapeComponentDataInterface ()
Member Function Documentation
GetHeight() [1/2]
uint16 FLandscapeComponentDataInterface::GetHeight (int32 LocalX, int32 LocalY) const inline
Definition at line 327 of file LandscapeDataAccess.h.
References FColor::G, GetHeightData(), and FColor::R.
Referenced by GetHeight(), GetLocalHeight(), and GetLocalHeight().
GetHeight() [2/2]
uint16 FLandscapeComponentDataInterface::GetHeight (int32 VertexIndex) const inline
Definition at line 333 of file LandscapeDataAccess.h.
References GetHeight(), FLandscapeComponentDataInterfaceBase::VertexIndexToXY(), X, and Y.
GetHeightData()
FColor * FLandscapeComponentDataInterface::GetHeightData (int32 LocalX, int32 LocalY) const inline
Definition at line 311 of file LandscapeDataAccess.h.
References check, Component, FLandscapeComponentDataInterfaceBase::ComponentSizeVerts, FLandscapeComponentDataInterfaceBase::HeightmapComponentOffsetX, FLandscapeComponentDataInterfaceBase::HeightmapComponentOffsetY, FLandscapeComponentDataInterfaceBase::HeightmapStride, HeightMipData, and FLandscapeComponentDataInterfaceBase::VertexXYToTexelXY().
Referenced by GetHeight(), and GetLocalTangentVectors().
GetHeightmapSizeX()
LANDSCAPE_API int32 FLandscapeComponentDataInterface::GetHeightmapSizeX (int32 MipIndex) const
GetHeightmapSizeY()
LANDSCAPE_API int32 FLandscapeComponentDataInterface::GetHeightmapSizeY (int32 MipIndex) const
GetHeightmapTextureData()
LANDSCAPE_API void FLandscapeComponentDataInterface::GetHeightmapTextureData (TArray< FColor > & OutData, bool bOkToFail = false)
GetLocalHeight() [1/2]
float FLandscapeComponentDataInterface::GetLocalHeight (int32 LocalX, int32 LocalY) const inline
Definition at line 340 of file LandscapeDataAccess.h.
References GetHeight(), and LandscapeDataAccess::GetLocalHeight().
GetLocalHeight() [2/2]
float FLandscapeComponentDataInterface::GetLocalHeight (int32 VertexIndex) const inline
Definition at line 345 of file LandscapeDataAccess.h.
References GetHeight(), and LandscapeDataAccess::GetLocalHeight().
GetLocalTangentVectors() [1/2]
void FLandscapeComponentDataInterface::GetLocalTangentVectors (int32 LocalX, int32 LocalY, FVector & LocalTangentX, FVector & LocalTangentY, FVector & LocalTangentZ) const inline
Definition at line 373 of file LandscapeDataAccess.h.
References FVector, GetHeightData(), LandscapeDataAccess::UnpackNormal(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by GetLocalTangentVectors().
GetLocalTangentVectors() [2/2]
void FLandscapeComponentDataInterface::GetLocalTangentVectors (int32 VertexIndex, FVector & LocalTangentX, FVector & LocalTangentY, FVector & LocalTangentZ) const inline
Definition at line 390 of file LandscapeDataAccess.h.
References FVector, GetLocalTangentVectors(), FLandscapeComponentDataInterfaceBase::VertexIndexToXY(), X, and Y.
GetLocalVertex() [1/2]
LANDSCAPE_API FVector FLandscapeComponentDataInterface::GetLocalVertex (int32 LocalX, int32 LocalY) const
References FVector.
Referenced by GetLocalVertex().
GetLocalVertex() [2/2]
FVector FLandscapeComponentDataInterface::GetLocalVertex (int32 VertexIndex) const inline
Definition at line 383 of file LandscapeDataAccess.h.
References FVector, GetLocalVertex(), FLandscapeComponentDataInterfaceBase::VertexIndexToXY(), X, and Y.
GetRawHeightData()
FColor * FLandscapeComponentDataInterface::GetRawHeightData () const inline
Definition at line 283 of file LandscapeDataAccess.h.
References HeightMipData.
GetRawXYOffsetData()
FColor * FLandscapeComponentDataInterface::GetRawXYOffsetData () const inline
Definition at line 288 of file LandscapeDataAccess.h.
References XYOffsetMipData.
GetWeightmapTextureData()
LANDSCAPE_API bool FLandscapeComponentDataInterface::GetWeightmapTextureData (ULandscapeLayerInfoObject * InLayerInfo, TArray< uint8 > & OutData, bool bInUseEditingWeightmap = false, bool bInRemoveSubsectionDuplicates = false)
GetWorldPositionTangents() [1/2]
LANDSCAPE_API void FLandscapeComponentDataInterface::GetWorldPositionTangents (int32 LocalX, int32 LocalY, FVector & WorldPos, FVector & WorldTangentX, FVector & WorldTangentY, FVector & WorldTangentZ) const
References FVector.
Referenced by GetWorldPositionTangents().
GetWorldPositionTangents() [2/2]
void FLandscapeComponentDataInterface::GetWorldPositionTangents (int32 VertexIndex, FVector & WorldPos, FVector & WorldTangentX, FVector & WorldTangentY, FVector & WorldTangentZ) const inline
Definition at line 417 of file LandscapeDataAccess.h.
References FVector, GetWorldPositionTangents(), FLandscapeComponentDataInterfaceBase::VertexIndexToXY(), X, and Y.
GetWorldTangentVectors() [1/2]
LANDSCAPE_API void FLandscapeComponentDataInterface::GetWorldTangentVectors (int32 LocalX, int32 LocalY, FVector & WorldTangentX, FVector & WorldTangentY, FVector & WorldTangentZ) const
References FVector.
Referenced by GetWorldTangentVectors().
GetWorldTangentVectors() [2/2]
void FLandscapeComponentDataInterface::GetWorldTangentVectors (int32 VertexIndex, FVector & WorldTangentX, FVector & WorldTangentY, FVector & WorldTangentZ) const inline
Definition at line 410 of file LandscapeDataAccess.h.
References FVector, GetWorldTangentVectors(), FLandscapeComponentDataInterfaceBase::VertexIndexToXY(), X, and Y.
GetWorldVertex() [1/2]
LANDSCAPE_API FVector FLandscapeComponentDataInterface::GetWorldVertex (int32 LocalX, int32 LocalY) const
References FVector.
Referenced by GetWorldVertex().
GetWorldVertex() [2/2]
FVector FLandscapeComponentDataInterface::GetWorldVertex (int32 VertexIndex) const inline
Definition at line 403 of file LandscapeDataAccess.h.
References FVector, GetWorldVertex(), FLandscapeComponentDataInterfaceBase::VertexIndexToXY(), X, and Y.
GetXYOffset() [1/2]
void FLandscapeComponentDataInterface::GetXYOffset (int32 VertexIndex, float & XOffset, float & YOffset) const inline
Definition at line 364 of file LandscapeDataAccess.h.
References GetXYOffset(), FLandscapeComponentDataInterfaceBase::VertexIndexToXY(), X, and Y.
GetXYOffset() [2/2]
void FLandscapeComponentDataInterface::GetXYOffset (int32 X, int32 Y, float & XOffset, float & YOffset) const inline
Definition at line 350 of file LandscapeDataAccess.h.
References FColor::A, FColor::B, float, FColor::G, GetXYOffsetData(), LANDSCAPE_XYOFFSET_SCALE, FColor::R, X, XYOffsetMipData, and Y.
Referenced by GetXYOffset().
GetXYOffsetData()
LANDSCAPE_API FColor * FLandscapeComponentDataInterface::GetXYOffsetData (int32 LocalX, int32 LocalY) const
Referenced by GetXYOffset().
SetRawHeightData()
void FLandscapeComponentDataInterface::SetRawHeightData (FColor * NewHeightData) inline
Definition at line 293 of file LandscapeDataAccess.h.
References HeightMipData.
SetRawXYOffsetData()
void FLandscapeComponentDataInterface::SetRawXYOffsetData (FColor * NewXYOffsetData) inline
Definition at line 298 of file LandscapeDataAccess.h.
References XYOffsetMipData.
Friends And Related Symbol Documentation
FLandscapeDataInterface
friend struct FLandscapeDataInterface friend
Definition at line 277 of file LandscapeDataAccess.h.
References FLandscapeDataInterface.
Referenced by FLandscapeDataInterface.
Field Documentation
bWorkOnEditingLayer
bool FLandscapeComponentDataInterface::bWorkOnEditingLayer private
Definition at line 427 of file LandscapeDataAccess.h.
Component
ULandscapeComponent* FLandscapeComponentDataInterface::Component private
Definition at line 426 of file LandscapeDataAccess.h.
Referenced by GetHeightData().
DataInterface
FLandscapeDataInterface FLandscapeComponentDataInterface::DataInterface private
Definition at line 425 of file LandscapeDataAccess.h.
HeightMipData
FColor* FLandscapeComponentDataInterface::HeightMipData private
Definition at line 430 of file LandscapeDataAccess.h.
Referenced by GetHeightData(), GetRawHeightData(), and SetRawHeightData().
XYOffsetMipData
FColor* FLandscapeComponentDataInterface::XYOffsetMipData private
Definition at line 431 of file LandscapeDataAccess.h.
Referenced by GetRawXYOffsetData(), GetXYOffset(), and SetRawXYOffsetData().
The documentation for this struct was generated from the following file:
LandscapeDataAccess.h