Unreal Engine 5.6 C++ API: Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase Class Reference
Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase Class Reference
#include "MetasoundNodeRegistrationMacro.h"
Public Member Functions
METASOUNDFRONTEND_API FNodeRegistryEntryBase (const Metasound::FNodeClassMetadata &InMetadata)
virtual ~FNodeRegistryEntryBase ()=default
virtual METASOUNDFRONTEND_API TInstancedStruct< FMetaSoundFrontendNodeConfiguration > CreateFrontendNodeConfiguration () const override
Optionally create the node extension associated with the node.
virtual METASOUNDFRONTEND_API TUniquePtr< INode > CreateNode (FNodeData) const
Create a node given FNodeData.
virtual METASOUNDFRONTEND_API const FNodeClassInfo & GetClassInfo () const override
Return FNodeClassInfo for the node class.
virtual METASOUNDFRONTEND_API FVertexInterface GetDefaultVertexInterface () const override
virtual METASOUNDFRONTEND_API const FMetasoundFrontendClass & GetFrontendClass () const override
Return a FMetasoundFrontendClass which describes the node.
virtual METASOUNDFRONTEND_API const TSet< FMetasoundFrontendVersion > * GetImplementedInterfaces () const override
Returns set of implemented interface versions.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") METASOUNDFRONTEND_API virtual TUniquePtr< INode > CreateNode(const FNodeInitData &InInitData) const override
Create a node given FNodeInitData.
Public Member Functions inherited from Metasound::Frontend::INodeClassRegistryEntry
virtual ~INodeClassRegistryEntry ()=default
UE_DEPRECATED (5.6, "Node Class Registration Entries do not need to be cloned.") virtual TUniquePtr< INodeClassRegistryEntry > Clone() const
Clone this registry entry.
UE_DEPRECATED (5.6, "Node class registry no longer tracks nature of implementation (i.e. if was registered " "from an asset or c++. Use the MetaSoundAssetManager to determine if the class has been defined within an asset(s).") virtual bool IsNative() const
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultLiteralNodeConstructorParams &&) const
Create a node given FDefaultLiteralNodeConstructorParams.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultNamedVertexNodeConstructorParams &&) const
Create a node given FDefaultNamedVertexNodeConstructorParams.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultNamedVertexWithLiteralNodeConstructorParams &&) const
Create a node given FDefaultNamedVertexWithLiteralNodeConstructorParams.
Protected Member Functions
METASOUNDFRONTEND_API TSharedRef< const FNodeClassMetadata > GetNodeClassMetadata () const
Private Attributes
FNodeClassInfo ClassInfo
TSharedRef< FNodeClassMetadata > ClassMetadata
FMetasoundFrontendClass FrontendClass
Detailed Description
Definition at line 30 of file MetasoundNodeRegistrationMacro.h.
Constructor & Destructor Documentation
FNodeRegistryEntryBase()
METASOUNDFRONTEND_API Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::FNodeRegistryEntryBase (const Metasound::FNodeClassMetadata & InMetadata)
References UE_API.
~FNodeRegistryEntryBase()
virtual Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::~FNodeRegistryEntryBase () virtual default
Member Function Documentation
CreateFrontendNodeConfiguration()
virtual METASOUNDFRONTEND_API TInstancedStruct< FMetaSoundFrontendNodeConfiguration > Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::CreateFrontendNodeConfiguration () const override virtual
Optionally create the node extension associated with the node.
Reimplemented from Metasound::Frontend::INodeClassRegistryEntry.
Reimplemented in Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntry< NodeType, ConfigurationType >, and Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntry< NodeType, void >.
References CreateFrontendNodeConfiguration(), and UE_API.
Referenced by CreateFrontendNodeConfiguration().
CreateNode()
virtual METASOUNDFRONTEND_API TUniquePtr< INode > Metasound::Frontend::INodeClassRegistryEntry::CreateNode (FNodeData) const virtual
Create a node given FNodeData.
If a node can be created with FNodeData, this function should return a valid node pointer.
Reimplemented from Metasound::Frontend::INodeClassRegistryEntry.
Reimplemented in Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >, and Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< NodeType >.
Referenced by UE_DEPRECATED().
GetClassInfo()
virtual METASOUNDFRONTEND_API const FNodeClassInfo & Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::GetClassInfo () const override virtual
Return FNodeClassInfo for the node class.
Implementations of method should avoid any expensive operations (e.g. loading from disk, allocating memory) as this method is called frequently when querying nodes.
Implements Metasound::Frontend::INodeClassRegistryEntry.
References UE_API.
GetDefaultVertexInterface()
virtual METASOUNDFRONTEND_API FVertexInterface Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::GetDefaultVertexInterface () const override virtual
Implements Metasound::Frontend::INodeClassRegistryEntry.
References GetDefaultVertexInterface(), and UE_API.
Referenced by GetDefaultVertexInterface().
GetFrontendClass()
virtual METASOUNDFRONTEND_API const FMetasoundFrontendClass & Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::GetFrontendClass () const override virtual
Return a FMetasoundFrontendClass which describes the node.
Implements Metasound::Frontend::INodeClassRegistryEntry.
References Metasound::Frontend::INodeClassRegistryEntry::CreateNode(), and UE_API.
GetImplementedInterfaces()
virtual METASOUNDFRONTEND_API const TSet< FMetasoundFrontendVersion > * Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::GetImplementedInterfaces () const override virtual
Returns set of implemented interface versions.
Returns nullptr if node class implementation does not support interface implementation.
Implements Metasound::Frontend::INodeClassRegistryEntry.
References GetImplementedInterfaces(), and UE_API.
Referenced by GetImplementedInterfaces().
GetNodeClassMetadata()
METASOUNDFRONTEND_API TSharedRef< const FNodeClassMetadata > Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::GetNodeClassMetadata () const protected
References GetNodeClassMetadata(), and UE_API.
Referenced by Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >::CreateNode(), and GetNodeClassMetadata().
UE_DEPRECATED()
Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::UE_DEPRECATED (5. 6, "Node classes should be constructed with FNodeData") const & override virtual
Create a node given FNodeInitData.
If a node can be created with FNodeInitData, this function should return a valid node pointer.
Implements Metasound::Frontend::INodeClassRegistryEntry.
References CreateNode(), and UE_API.
Field Documentation
ClassInfo
FNodeClassInfo Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::ClassInfo private
Definition at line 59 of file MetasoundNodeRegistrationMacro.h.
ClassMetadata
TSharedRef<FNodeClassMetadata> Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::ClassMetadata private
Definition at line 58 of file MetasoundNodeRegistrationMacro.h.
FrontendClass
FMetasoundFrontendClass Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::FrontendClass private
Definition at line 60 of file MetasoundNodeRegistrationMacro.h.
The documentation for this class was generated from the following file:
MetasoundNodeRegistrationMacro.h