Unreal Engine 5.6 C++ API: RK4Integrator Namespace Reference
RK4Integrator Namespace Reference
Data Structures
struct FRK4State
struct FRK4StateDerivative
Functions
template<typename T>
static T Accelerate (const FRK4State< T > &InCurrentState, const T &InTargetPosition, const FRK4SpringConstants &InSpringConstants)
template<typename T>
static FRK4StateDerivative< T > Evaluate (const FRK4State< T > &InCurrentState, const FRK4StateDerivative< T > &InDerivativeState, const T &InTargetPosition, const FRK4SpringConstants &InSpringConstants, const float &InDeltaTime)
template<typename T>
static void Integrate (FRK4State< T > &InCurrentState, const T &InTargetPosition, const FRK4SpringConstants &InSpringConstants, const float &InDeltaTime)
Function Documentation
Accelerate()
template<typename T> T RK4Integrator::Accelerate (const FRK4State< T > & InCurrentState, const T & InTargetPosition, const FRK4SpringConstants & InSpringConstants) static
Definition at line 63 of file SpringInterpolator.h.
References FRK4SpringConstants::DampingConstant, RK4Integrator::FRK4State< T >::Position, FRK4SpringConstants::SpringStiffness, and RK4Integrator::FRK4State< T >::Velocity.
Referenced by Evaluate().
Evaluate()
template<typename T> FRK4StateDerivative< T > RK4Integrator::Evaluate (const FRK4State< T > & InCurrentState, const FRK4StateDerivative< T > & InDerivativeState, const T & InTargetPosition, const FRK4SpringConstants & InSpringConstants, const float & InDeltaTime) static
Definition at line 69 of file SpringInterpolator.h.
References Accelerate(), RK4Integrator::FRK4StateDerivative< T >::Acceleration, RK4Integrator::FRK4State< T >::Position, RK4Integrator::FRK4State< T >::Velocity, and RK4Integrator::FRK4StateDerivative< T >::Velocity.
Integrate()
template<typename T> void RK4Integrator::Integrate (FRK4State< T > & InCurrentState, const T & InTargetPosition, const FRK4SpringConstants & InSpringConstants, const float & InDeltaTime) static
Definition at line 83 of file SpringInterpolator.h.
References Acceleration, RK4Integrator::FRK4StateDerivative< T >::Acceleration, Evaluate, RK4Integrator::FRK4State< T >::Position, RK4Integrator::FRK4State< T >::Velocity, and RK4Integrator::FRK4StateDerivative< T >::Velocity.
Referenced by FRK4SpringInterpolator< float >::Update().