Unreal Engine 5.6 C++ API: SCommonEditorViewportToolbarBase Class Reference
SCommonEditorViewportToolbarBase Class Reference
A viewport toolbar widget for an asset or level editor that is placed in a viewport.
#include "SCommonEditorViewportToolbarBase.h"
Public Member Functions
UNREALED_API void Construct (const FArguments &InArgs, TSharedPtr< class ICommonEditorViewportToolbarInfoProvider > InInfoProvider)
UNREALED_API const TSharedPtr< IPreviewProfileController > & GetPreviewProfileController () const
Gets the preview profile controller explicitly set to this toolbar.
SLATE_ARGUMENT (bool, AddRealtimeButton) SLATE_ARGUMENT(TSharedPtr< IPreviewProfileController >
SLATE_BEGIN_ARGS (SCommonEditorViewportToolbarBase)
PreviewProfileController SLATE_END_ARGS () UNREALED_API virtual ~SCommonEditorViewportToolbarBase()
UE_DEPRECATED (5.6, "Use the version taking UToolMenu as argument: UE::UnrealEd::ConstructScreenPercentageMenu(InMenu)") static UNREALED_API void ConstructScreenPercentageMenu(FMenuBuilder &MenuBuilder
Public Member Functions inherited from SViewportToolBar
UNREALED_API TWeakPtr< SMenuAnchor > GetOpenMenu () const
virtual UNREALED_API bool IsViewModeSupported (EViewModeIndex ViewModeIndex) const
UNREALED_API void SetOpenMenu (TSharedPtr< SMenuAnchor > &NewMenu)
Sets the open menu to a new menu and closes any currently opened one.
SLATE_BEGIN_ARGS (SViewportToolBar)
SLATE_END_ARGS () UNREALED_API void Construct(const FArguments &InArgs)
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
class FEditorViewportClient * ViewportClient
Protected Member Functions
UNREALED_API void CreateViewMenuExtensions (FMenuBuilder &MenuBuilder)
virtual UNREALED_API void ExtendLeftAlignedToolbarSlots (TSharedPtr< SHorizontalBox > MainBoxPtr, TSharedPtr< SViewportToolBar > ParentToolBarPtr) const
Extension allowing derived classes to add to left-aligned portion of the toolbar slots.
virtual UNREALED_API void ExtendOptionsMenu (FMenuBuilder &OptionsMenuBuilder) const
Extension allowing derived classes to add to the options menu.
virtual UNREALED_API void FillShowFlagsMenu (class UToolMenu *InMenu) const
UNREALED_API TSharedRef< SWidget > GenerateFarViewPlaneMenu () const
UNREALED_API TSharedRef< SWidget > GenerateFOVMenu () const
UNREALED_API TSharedPtr< FExtender > GetCombinedExtenderList (TSharedRef< FExtender > MenuExtender) const
UNREALED_API ICommonEditorViewportToolbarInfoProvider & GetInfoProvider () const
UNREALED_API FText GetScalabilityWarningLabel () const
UNREALED_API TSharedRef< SWidget > GetScalabilityWarningMenuContent () const
UNREALED_API EVisibility GetScalabilityWarningVisibility () const
virtual bool GetShowScalabilityMenu () const
virtual UNREALED_API TSharedPtr< FExtender > GetViewMenuExtender () const
Gets the extender for the view menu.
UNREALED_API class FEditorViewportClient & GetViewportClient () const
virtual UNREALED_API TSharedRef< class SEditorViewportViewMenu > MakeViewMenu ()
virtual UNREALED_API void OnFOVValueChanged (float NewValue) const
Called when the FOV slider is adjusted in the perspective viewport.
UNREALED_API void OnScreenPercentageValueChanged (int32 NewValue)
Called when the ScreenPercentage slider is adjusted in the viewport.
Protected Member Functions inherited from SViewportToolBar
virtual UNREALED_API const FSlateBrush * GetCameraMenuLabelIconFromViewportType (const ELevelViewportType ViewportType) const
Returns the label icon for the "Camera" tool bar menu, which changes depending on the viewport type.
UE_DEPRECATED (5.6, "Please use UE::UnrealEd::GetCameraSubmenuLabelFromViewportType instead.") UNREALED_API virtual FText GetCameraMenuLabelFromViewportType(const ELevelViewportType ViewportType) const
Returns the label for the "Camera" tool bar menu based on based viewport type.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
UNREALED_API TSharedRef< SWidget > GenerateCameraMenu () const
Generates the toolbar camera menu content.
UNREALED_API TSharedRef< SWidget > GenerateOptionsMenu () const
Generates the toolbar options menu content.
virtual UNREALED_API TSharedRef< SWidget > GenerateShowMenu () const
Generates the toolbar show menu content.
UNREALED_API TSharedRef< SWidget > GenerateViewMenu () const
Generates the toolbar view menu content.
UNREALED_API TSharedRef< SWidget > GenerateViewModeOptionsMenu () const
Generates the toolbar view param menu content.
UNREALED_API FSlateIcon GetCameraMenuIcon () const
UNREALED_API FText GetCameraMenuLabel () const
Returns the label for the "Camera" tool bar menu, which changes depending on the viewport type.
UNREALED_API EVisibility GetRealtimeWarningVisibility () const
Called to determine if we should show the realtime warning.
UNREALED_API EVisibility GetViewModeOptionsVisibility () const
Returns the initial visibility of the view mode options widget.
TSharedPtr< SWidget > MakeLegacyShowMenu () const
UNREALED_API void OnFarViewPlaneValueChanged (float NewValue)
Called when the far view plane slider is adjusted in the perspective viewport.
UNREALED_API float OnGetFarViewPlaneValue () const
Called by the far view plane slider in the perspective viewport to get the far view plane value.
UNREALED_API float OnGetFOVValue () const
Called by the FOV slider in the perspective viewport to get the FOV value.
UNREALED_API FReply OnRealtimeWarningClicked ()
Called when we click the realtime warning.
bool ShouldCreateOptionsMenu () const
Private Attributes
bool bHasExtendedLeftSide = true
bool bHasExtendedSettingsMenu = true
bool bIsBuildingToolMenu = false
bool bIsGeneratingToolMenuWidget = false
Automatic Legacy Upgrade Support.
TSharedPtr< class SEditorViewportViewMenu > BlankViewMenu
bool bUsesDefaultViewMenu = false
TWeakPtr< class ICommonEditorViewportToolbarInfoProvider > InfoProviderPtr
The viewport that we are in.
TSharedPtr< IPreviewProfileController > PreviewProfileController
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
A viewport toolbar widget for an asset or level editor that is placed in a viewport.
Definition at line 132 of file SCommonEditorViewportToolbarBase.h.
Member Function Documentation
Construct()
UNREALED_API void SCommonEditorViewportToolbarBase::Construct (const FArguments & InArgs, TSharedPtr< class ICommonEditorViewportToolbarInfoProvider > InInfoProvider)
CreateViewMenuExtensions()
UNREALED_API void SCommonEditorViewportToolbarBase::CreateViewMenuExtensions (FMenuBuilder & MenuBuilder) protected
ExtendLeftAlignedToolbarSlots()
virtual UNREALED_API void SCommonEditorViewportToolbarBase::ExtendLeftAlignedToolbarSlots (TSharedPtr< SHorizontalBox > MainBoxPtr, TSharedPtr< SViewportToolBar > ParentToolBarPtr) const protected virtual
Extension allowing derived classes to add to left-aligned portion of the toolbar slots.
ExtendOptionsMenu()
virtual UNREALED_API void SCommonEditorViewportToolbarBase::ExtendOptionsMenu (FMenuBuilder & OptionsMenuBuilder) const protected virtual
Extension allowing derived classes to add to the options menu.
FillShowFlagsMenu()
virtual UNREALED_API void SCommonEditorViewportToolbarBase::FillShowFlagsMenu (class UToolMenu * InMenu) const protected virtual
GenerateCameraMenu()
UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GenerateCameraMenu () const private
Generates the toolbar camera menu content.
Returns
The widget containing the view menu content
GenerateFarViewPlaneMenu()
UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GenerateFarViewPlaneMenu () const protected
Returns
The widget containing the far view plane slider.
GenerateFOVMenu()
UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GenerateFOVMenu () const protected
Returns
The widget containing the perspective only FOV window.
GenerateOptionsMenu()
UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GenerateOptionsMenu () const private
Generates the toolbar options menu content.
Returns
The widget containing the options menu content
GenerateShowMenu()
virtual UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GenerateShowMenu () const private virtual
Generates the toolbar show menu content.
Returns
The widget containing the show menu content
GenerateViewMenu()
UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GenerateViewMenu () const private
Generates the toolbar view menu content.
Returns
The widget containing the view menu content
GenerateViewModeOptionsMenu()
UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GenerateViewModeOptionsMenu () const private
Generates the toolbar view param menu content.
Returns
The widget containing the show menu content
GetCameraMenuIcon()
UNREALED_API FSlateIcon SCommonEditorViewportToolbarBase::GetCameraMenuIcon () const private
GetCameraMenuLabel()
UNREALED_API FText SCommonEditorViewportToolbarBase::GetCameraMenuLabel () const private
Returns the label for the "Camera" tool bar menu, which changes depending on the viewport type.
Returns
Label to use for this menu label
GetCombinedExtenderList()
UNREALED_API TSharedPtr< FExtender > SCommonEditorViewportToolbarBase::GetCombinedExtenderList (TSharedRef< FExtender > MenuExtender) const protected
GetInfoProvider()
UNREALED_API ICommonEditorViewportToolbarInfoProvider & SCommonEditorViewportToolbarBase::GetInfoProvider () const protected
GetPreviewProfileController()
UNREALED_API const TSharedPtr< IPreviewProfileController > & SCommonEditorViewportToolbarBase::GetPreviewProfileController () const inline
Gets the preview profile controller explicitly set to this toolbar.
Definition at line 152 of file SCommonEditorViewportToolbarBase.h.
References GetPreviewProfileController(), and PreviewProfileController.
Referenced by GetPreviewProfileController().
GetRealtimeWarningVisibility()
UNREALED_API EVisibility SCommonEditorViewportToolbarBase::GetRealtimeWarningVisibility () const private
Called to determine if we should show the realtime warning.
GetScalabilityWarningLabel()
UNREALED_API FText SCommonEditorViewportToolbarBase::GetScalabilityWarningLabel () const protected
GetScalabilityWarningMenuContent()
UNREALED_API TSharedRef< SWidget > SCommonEditorViewportToolbarBase::GetScalabilityWarningMenuContent () const protected
GetScalabilityWarningVisibility()
UNREALED_API EVisibility SCommonEditorViewportToolbarBase::GetScalabilityWarningVisibility () const protected
GetShowScalabilityMenu()
virtual bool SCommonEditorViewportToolbarBase::GetShowScalabilityMenu () const inline protected virtual
Definition at line 258 of file SCommonEditorViewportToolbarBase.h.
GetViewMenuExtender()
virtual UNREALED_API TSharedPtr< FExtender > SCommonEditorViewportToolbarBase::GetViewMenuExtender () const protected virtual
Gets the extender for the view menu.
GetViewModeOptionsVisibility()
UNREALED_API EVisibility SCommonEditorViewportToolbarBase::GetViewModeOptionsVisibility () const private
Returns the initial visibility of the view mode options widget.
Returns
The visibility value
GetViewportClient()
UNREALED_API class FEditorViewportClient & SCommonEditorViewportToolbarBase::GetViewportClient () const protected
MakeLegacyShowMenu()
TSharedPtr< SWidget > SCommonEditorViewportToolbarBase::MakeLegacyShowMenu () const private
MakeViewMenu()
virtual UNREALED_API TSharedRef< class SEditorViewportViewMenu > SCommonEditorViewportToolbarBase::MakeViewMenu () protected virtual
OnFarViewPlaneValueChanged()
UNREALED_API void SCommonEditorViewportToolbarBase::OnFarViewPlaneValueChanged (float NewValue) private
Called when the far view plane slider is adjusted in the perspective viewport.
OnFOVValueChanged()
virtual UNREALED_API void SCommonEditorViewportToolbarBase::OnFOVValueChanged (float NewValue) const protected virtual
Called when the FOV slider is adjusted in the perspective viewport.
OnGetFarViewPlaneValue()
UNREALED_API float SCommonEditorViewportToolbarBase::OnGetFarViewPlaneValue () const private
Called by the far view plane slider in the perspective viewport to get the far view plane value.
OnGetFOVValue()
UNREALED_API float SCommonEditorViewportToolbarBase::OnGetFOVValue () const private
Called by the FOV slider in the perspective viewport to get the FOV value.
OnRealtimeWarningClicked()
UNREALED_API FReply SCommonEditorViewportToolbarBase::OnRealtimeWarningClicked () private
Called when we click the realtime warning.
OnScreenPercentageValueChanged()
UNREALED_API void SCommonEditorViewportToolbarBase::OnScreenPercentageValueChanged (int32 NewValue) protected
Called when the ScreenPercentage slider is adjusted in the viewport.
ShouldCreateOptionsMenu()
bool SCommonEditorViewportToolbarBase::ShouldCreateOptionsMenu () const private
SLATE_ARGUMENT()
SCommonEditorViewportToolbarBase::SLATE_ARGUMENT (bool , AddRealtimeButton)
References PreviewProfileController.
SLATE_BEGIN_ARGS()
SCommonEditorViewportToolbarBase::SLATE_BEGIN_ARGS (SCommonEditorViewportToolbarBase) inline
Definition at line 135 of file SCommonEditorViewportToolbarBase.h.
SLATE_END_ARGS()
PreviewProfileController SCommonEditorViewportToolbarBase::SLATE_END_ARGS () inline
Definition at line 142 of file SCommonEditorViewportToolbarBase.h.
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
UE_DEPRECATED()
SCommonEditorViewportToolbarBase::UE_DEPRECATED (5. 6, "Use the version taking UToolMenu as argument: UE::UnrealEd::ConstructScreenPercentageMenu(InMenu)") &
Field Documentation
bHasExtendedLeftSide
bool SCommonEditorViewportToolbarBase::bHasExtendedLeftSide = true mutable private
Definition at line 282 of file SCommonEditorViewportToolbarBase.h.
bHasExtendedSettingsMenu
bool SCommonEditorViewportToolbarBase::bHasExtendedSettingsMenu = true mutable private
Definition at line 281 of file SCommonEditorViewportToolbarBase.h.
bIsBuildingToolMenu
bool SCommonEditorViewportToolbarBase::bIsBuildingToolMenu = false mutable private
Definition at line 280 of file SCommonEditorViewportToolbarBase.h.
bIsGeneratingToolMenuWidget
bool SCommonEditorViewportToolbarBase::bIsGeneratingToolMenuWidget = false private
Automatic Legacy Upgrade Support.
Definition at line 278 of file SCommonEditorViewportToolbarBase.h.
BlankViewMenu
TSharedPtr<class SEditorViewportViewMenu> SCommonEditorViewportToolbarBase::BlankViewMenu private
Definition at line 273 of file SCommonEditorViewportToolbarBase.h.
bUsesDefaultViewMenu
bool SCommonEditorViewportToolbarBase::bUsesDefaultViewMenu = false mutable private
Definition at line 283 of file SCommonEditorViewportToolbarBase.h.
InfoProviderPtr
TWeakPtr<class ICommonEditorViewportToolbarInfoProvider> SCommonEditorViewportToolbarBase::InfoProviderPtr private
The viewport that we are in.
Definition at line 270 of file SCommonEditorViewportToolbarBase.h.
PreviewProfileController
TSharedPtr<IPreviewProfileController> SCommonEditorViewportToolbarBase::PreviewProfileController private
Definition at line 271 of file SCommonEditorViewportToolbarBase.h.
Referenced by GetPreviewProfileController(), and SLATE_ARGUMENT().
ViewportClient
class FEditorViewportClient* SCommonEditorViewportToolbarBase::ViewportClient
Definition at line 149 of file SCommonEditorViewportToolbarBase.h.
The documentation for this class was generated from the following file:
SCommonEditorViewportToolbarBase.h