Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitRegistryHandle Struct Reference
UE::AnimNext::FTraitRegistryHandle Struct Reference final
FTraitRegistryHandle.
#include "TraitRegistryHandle.h"
Public Member Functions
FTraitRegistryHandle () noexcept=default
int32 GetDynamicIndex () const noexcept
int32 GetStaticOffset () const noexcept
bool IsDynamic () const noexcept
bool IsStatic () const noexcept
bool IsValid () const noexcept
bool operator!= (FTraitRegistryHandle RHS) const noexcept
bool operator== (FTraitRegistryHandle RHS) const noexcept
Private Member Functions
FTraitRegistryHandle (int16 HandleValue_) noexcept
Static Private Member Functions
static FTraitRegistryHandle MakeDynamic (int32 TraitIndex)
static FTraitRegistryHandle MakeStatic (int32 TraitOffset)
Private Attributes
int16 HandleValue = 0
Friends
struct FTraitRegistry
Detailed Description
FTraitRegistryHandle.
Encapsulates a value used as a handle in the trait registry. When valid, it can be used to retrieve a pointer to the corresponding trait.
Definition at line 15 of file TraitRegistryHandle.h.
Constructor & Destructor Documentation
FTraitRegistryHandle() [1/2]
UE::AnimNext::FTraitRegistryHandle::FTraitRegistryHandle () default noexcept
Referenced by MakeDynamic(), MakeStatic(), operator!=(), and operator==().
FTraitRegistryHandle() [2/2]
UE::AnimNext::FTraitRegistryHandle::FTraitRegistryHandle (int16 HandleValue_) inline explicit private noexcept
Definition at line 40 of file TraitRegistryHandle.h.
Member Function Documentation
GetDynamicIndex()
int32 UE::AnimNext::FTraitRegistryHandle::GetDynamicIndex () const inline noexcept
Definition at line 33 of file TraitRegistryHandle.h.
References HandleValue, INDEX_NONE, and IsDynamic().
GetStaticOffset()
int32 UE::AnimNext::FTraitRegistryHandle::GetStaticOffset () const inline noexcept
Definition at line 30 of file TraitRegistryHandle.h.
References HandleValue, INDEX_NONE, and IsStatic().
IsDynamic()
bool UE::AnimNext::FTraitRegistryHandle::IsDynamic () const inline noexcept
Definition at line 27 of file TraitRegistryHandle.h.
References HandleValue, and IsValid().
Referenced by GetDynamicIndex().
IsStatic()
bool UE::AnimNext::FTraitRegistryHandle::IsStatic () const inline noexcept
Definition at line 24 of file TraitRegistryHandle.h.
References HandleValue, and IsValid().
Referenced by GetStaticOffset().
IsValid()
bool UE::AnimNext::FTraitRegistryHandle::IsValid () const inline noexcept
Definition at line 21 of file TraitRegistryHandle.h.
References HandleValue, and IsValid().
Referenced by IsDynamic(), IsStatic(), and IsValid().
MakeDynamic()
FTraitRegistryHandle UE::AnimNext::FTraitRegistryHandle::MakeDynamic (int32 TraitIndex) inline static private
Definition at line 52 of file TraitRegistryHandle.h.
References FTraitRegistryHandle(), and check.
MakeStatic()
FTraitRegistryHandle UE::AnimNext::FTraitRegistryHandle::MakeStatic (int32 TraitOffset) inline static private
Definition at line 45 of file TraitRegistryHandle.h.
References FTraitRegistryHandle(), and check.
operator!=()
bool UE::AnimNext::FTraitRegistryHandle::operator!= (FTraitRegistryHandle RHS) const inline noexcept
Definition at line 37 of file TraitRegistryHandle.h.
References FTraitRegistryHandle(), and HandleValue.
operator==()
bool UE::AnimNext::FTraitRegistryHandle::operator== (FTraitRegistryHandle RHS) const inline noexcept
Definition at line 36 of file TraitRegistryHandle.h.
References FTraitRegistryHandle(), and HandleValue.
Friends And Related Symbol Documentation
FTraitRegistry
friend struct FTraitRegistry friend
Definition at line 64 of file TraitRegistryHandle.h.
References FTraitRegistry.
Referenced by FTraitRegistry.
Field Documentation
HandleValue
int16 UE::AnimNext::FTraitRegistryHandle::HandleValue = 0 private
Definition at line 62 of file TraitRegistryHandle.h.
Referenced by GetDynamicIndex(), GetStaticOffset(), IsDynamic(), IsStatic(), IsValid(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
TraitRegistryHandle.h