Unreal Engine 5.6 C++ API: UE::MovieScene::FEntityLedger Struct Reference
UE::MovieScene::FEntityLedger Struct Reference
An entity ledger is responsible for tracking the entites that have been imported for the currently relevant frame of a sequence instance.
#include "MovieSceneEntityLedger.h"
Data Structures
struct FImportedEntityData
Public Member Functions
MOVIESCENE_API bool CanImportEntity (UMovieSceneEntitySystemLinker *Linker, const FEntityImportSequenceParams &ImportParams, const FMovieSceneEntityComponentField *EntityField, const FMovieSceneEvaluationFieldEntityQuery &Query, FMovieSceneEvaluationFieldEntitySet &OutPerTickConditionalEntities, TMap< uint32, bool > &ConditionResultCache, bool bUpdatingPerTickEntities=false)
MOVIESCENE_API void CleanupLinkerEntities (const TSet< FMovieSceneEntityID > &LinkerEntities)
Remove linker entity IDs that exist in the specified set since they are no longer valid.
MOVIESCENE_API bool Contains (UMovieSceneEntitySystemLinker *Linker, const FEntityComponentFilter &Filter) const
Check whether any of the entities in this ledger or their children match the specified filter.
MOVIESCENE_API void FindImportedEntities (TWeakObjectPtr< UObject > EntityOwner, TArray< FMovieSceneEntityID > &OutEntityIDs) const
Find imported entities.
MOVIESCENE_API FMovieSceneEntityID FindImportedEntity (const FMovieSceneEvaluationFieldEntityKey &EntityKey) const
Find an imported entity.
MOVIESCENE_API bool HasImportedEntity (const FMovieSceneEvaluationFieldEntityKey &EntityKey) const
Check whether the specified entity is being tracked by this ledger at all.
MOVIESCENE_API void ImportEntity (UMovieSceneEntitySystemLinker *Linker, const FEntityImportSequenceParams &ImportParams, const FMovieSceneEntityComponentField *EntityField, const FMovieSceneEvaluationFieldEntityQuery &Query, FMovieSceneEvaluationFieldEntitySet &OutPerTickConditionalEntities, TMap< uint32, bool > &ConditionResultCache)
Indicate that the specified field entity is currently being evaluated.
MOVIESCENE_API void Invalidate ()
Invalidate any and all entities that are currently being tracked, causing new linker entities to be created on the next evaluation, and ones to become unlinked (preserving any components with the preserve flag)
MOVIESCENE_API bool IsEmpty () const
Check whether this ledger contains any information at all (ie is tracking any global entities, even if it has not created any linker entities for them)
bool IsInvalidated () const
MOVIESCENE_API void MutateAll (UMovieSceneEntitySystemLinker *Linker, const FEntityComponentFilter &Filter, const IMovieScenePerEntityMutation &Mutation) const
Mutate all the entities within this ledger by using the specified filter.
MOVIESCENE_API void TagGarbage (UMovieSceneEntitySystemLinker *Linker)
Called in order to tag garbage as NeedsUnlink.
UE_DEPRECATED (5.5, "Please call the version that takes ConditionResultCache") MOVIESCENE_API void UpdateOneShotEntities(UMovieSceneEntitySystemLinker *Linker
UE_DEPRECATED (5.5, "Please call the version that takes OutPerTickConditionalEntities and ConditionResultCache") MOVIESCENE_API void ImportEntity(UMovieSceneEntitySystemLinker *Linker
UE_DEPRECATED (5.5, "Please call the version that takes OutPerTickConditionalEntities and ConditionResultCache") MOVIESCENE_API void UpdateEntities(UMovieSceneEntitySystemLinker *Linker
MOVIESCENE_API void UnlinkEverything (UMovieSceneEntitySystemLinker *Linker, EUnlinkEverythingMode Garbage=EUnlinkEverythingMode::Normal)
Unlink all imported linker entities and their children, whilst maintaining the map of imported entities.
MOVIESCENE_API void UnlinkOneShots (UMovieSceneEntitySystemLinker *Linker)
Unlink all imported one-shot linker entities and their children and clear the list of one shots.
MOVIESCENE_API void UpdateConditionalEntities (UMovieSceneEntitySystemLinker *Linker, const FEntityImportSequenceParams &ImportParams, const FMovieSceneEntityComponentField *EntityField, const FMovieSceneEvaluationFieldEntitySet &ConditionalEntities)
Update any conditional entities for the current frame.
MOVIESCENE_API void UpdateEntities (UMovieSceneEntitySystemLinker *Linker, const FEntityImportSequenceParams &ImportParams, const FMovieSceneEntityComponentField *EntityField, const FMovieSceneEvaluationFieldEntitySet &NewEntities, FMovieSceneEvaluationFieldEntitySet &OutPerTickConditionalEntities, TMap< uint32, bool > &ConditionResultCache)
To be called any time this ledger's instance is to be evaluated with a different set of entities - updates the set of entities that are required for the current evaluation environment.
MOVIESCENE_API void UpdateOneShotEntities (UMovieSceneEntitySystemLinker *Linker, const FEntityImportSequenceParams &ImportParams, const FMovieSceneEntityComponentField *EntityField, const FMovieSceneEvaluationFieldEntitySet &NewEntities, TMap< uint32, bool > &ConditionResultCache)
Update any one-shot entities for the current frame.
Data Fields
const FEntityImportSequenceParams const FMovieSceneEntityComponentField * EntityField
const FEntityImportSequenceParams & ImportParams
const FEntityImportSequenceParams const FMovieSceneEntityComponentField const FMovieSceneEvaluationFieldEntitySet & NewEntities
const FEntityImportSequenceParams const FMovieSceneEntityComponentField const FMovieSceneEvaluationFieldEntityQuery & Query
Private Attributes
bool bInvalidated
Whether we have been invalidated, and need to re-instantiate everything.
TMap< FMovieSceneEvaluationFieldEntityKey, FImportedEntityData > ImportedEntities
Map of source field entity key -> imported linker entities.
TArray< FMovieSceneEntityID > OneShotEntities
Map of source entities that were swept this frame.
Detailed Description
An entity ledger is responsible for tracking the entites that have been imported for the currently relevant frame of a sequence instance.
It is responsible for linking and unlinking new and expired entities in the linker's entity manager based on the current set of entities required for evaluation.
Definition at line 37 of file MovieSceneEntityLedger.h.
Member Function Documentation
CanImportEntity()
MOVIESCENE_API bool UE::MovieScene::FEntityLedger::CanImportEntity (UMovieSceneEntitySystemLinker * Linker, const FEntityImportSequenceParams & ImportParams, const FMovieSceneEntityComponentField * EntityField, const FMovieSceneEvaluationFieldEntityQuery & Query, FMovieSceneEvaluationFieldEntitySet & OutPerTickConditionalEntities, TMap< uint32, bool > & ConditionResultCache, bool bUpdatingPerTickEntities = false)
References EntityField, ImportParams, and Query.
CleanupLinkerEntities()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::CleanupLinkerEntities (const TSet< FMovieSceneEntityID > & LinkerEntities)
Remove linker entity IDs that exist in the specified set since they are no longer valid.
Parameters
LinkerEntities Set of entity IDs that have been destroyed
References CleanupLinkerEntities().
Referenced by CleanupLinkerEntities().
Contains()
MOVIESCENE_API bool UE::MovieScene::FEntityLedger::Contains (UMovieSceneEntitySystemLinker * Linker, const FEntityComponentFilter & Filter) const
Check whether any of the entities in this ledger or their children match the specified filter.
References Contains(), and Filter.
Referenced by Contains().
FindImportedEntities()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::FindImportedEntities (TWeakObjectPtr< UObject > EntityOwner, TArray< FMovieSceneEntityID > & OutEntityIDs) const
Find imported entities.
FindImportedEntity()
MOVIESCENE_API FMovieSceneEntityID UE::MovieScene::FEntityLedger::FindImportedEntity (const FMovieSceneEvaluationFieldEntityKey & EntityKey) const
Find an imported entity.
HasImportedEntity()
MOVIESCENE_API bool UE::MovieScene::FEntityLedger::HasImportedEntity (const FMovieSceneEvaluationFieldEntityKey & EntityKey) const
Check whether the specified entity is being tracked by this ledger at all.
ImportEntity()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::ImportEntity (UMovieSceneEntitySystemLinker * Linker, const FEntityImportSequenceParams & ImportParams, const FMovieSceneEntityComponentField * EntityField, const FMovieSceneEvaluationFieldEntityQuery & Query, FMovieSceneEvaluationFieldEntitySet & OutPerTickConditionalEntities, TMap< uint32, bool > & ConditionResultCache)
Indicate that the specified field entity is currently being evaluated.
Parameters
Linker The linker To import into
InstanceHandle A handle to the sequence instance that the entity relates to (relating to Linker->GetInstanceRegistry())
Entity The field entity that is being imported
OutConditionalEntities Output set returning conditional entities that require re-evaluating in between full updates.
ConditionResultCache Cache of previous condition results, to be used and potentially modified during any condition checking in updating entities.
References EntityField, ImportEntity(), ImportParams, and Query.
Referenced by ImportEntity().
Invalidate()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::Invalidate ()
Invalidate any and all entities that are currently being tracked, causing new linker entities to be created on the next evaluation, and ones to become unlinked (preserving any components with the preserve flag)
References Invalidate().
Referenced by Invalidate().
IsEmpty()
MOVIESCENE_API bool UE::MovieScene::FEntityLedger::IsEmpty () const
Check whether this ledger contains any information at all (ie is tracking any global entities, even if it has not created any linker entities for them)
IsInvalidated()
bool UE::MovieScene::FEntityLedger::IsInvalidated () const inline
Definition at line 87 of file MovieSceneEntityLedger.h.
References bInvalidated, and IsInvalidated().
Referenced by IsInvalidated().
MutateAll()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::MutateAll (UMovieSceneEntitySystemLinker * Linker, const FEntityComponentFilter & Filter, const IMovieScenePerEntityMutation & Mutation) const
Mutate all the entities within this ledger by using the specified filter.
References Filter, and MutateAll().
Referenced by MutateAll().
TagGarbage()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::TagGarbage (UMovieSceneEntitySystemLinker * Linker)
Called in order to tag garbage as NeedsUnlink.
Parameters
Linker The linker that owns this ledger
References TagGarbage().
Referenced by TagGarbage().
UE_DEPRECATED() [1/3]
UE::MovieScene::FEntityLedger::UE_DEPRECATED (5. 5, "Please call the version that takes ConditionResultCache")
References EntityField, ImportParams, NewEntities, UE_DEPRECATED(), and UpdateOneShotEntities().
UE_DEPRECATED() [2/3]
UE::MovieScene::FEntityLedger::UE_DEPRECATED (5. 5, "Please call the version that takes OutPerTickConditionalEntities and ConditionResultCache")
UE_DEPRECATED() [3/3]
UE::MovieScene::FEntityLedger::UE_DEPRECATED (5. 5, "Please call the version that takes OutPerTickConditionalEntities and ConditionResultCache")
Referenced by UE_DEPRECATED().
UnlinkEverything()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::UnlinkEverything (UMovieSceneEntitySystemLinker * Linker, EUnlinkEverythingMode Garbage = EUnlinkEverythingMode::Normal)
Unlink all imported linker entities and their children, whilst maintaining the map of imported entities.
Parameters
Linker The linker that owns this ledger
References Garbage, UE::MovieScene::Normal, and UnlinkEverything().
Referenced by UnlinkEverything().
UnlinkOneShots()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::UnlinkOneShots (UMovieSceneEntitySystemLinker * Linker)
Unlink all imported one-shot linker entities and their children and clear the list of one shots.
Parameters
Linker The linker that owns this ledger
Returns
A mask representing the changes made to the environment
References UnlinkOneShots().
Referenced by UnlinkOneShots().
UpdateConditionalEntities()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::UpdateConditionalEntities (UMovieSceneEntitySystemLinker * Linker, const FEntityImportSequenceParams & ImportParams, const FMovieSceneEntityComponentField * EntityField, const FMovieSceneEvaluationFieldEntitySet & ConditionalEntities)
Update any conditional entities for the current frame.
Parameters
Linker The linker that owns this ledger
ImportParams Basis for import parameters
EntityField Possibly null if NewEntities is empty- an entity field containing structural information about the sequence
ConditionalEntities A set specifying any conditional entities that need to be checked again and possibly imported or removed.
References EntityField, ImportParams, and UpdateConditionalEntities().
Referenced by UpdateConditionalEntities().
UpdateEntities()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::UpdateEntities (UMovieSceneEntitySystemLinker * Linker, const FEntityImportSequenceParams & ImportParams, const FMovieSceneEntityComponentField * EntityField, const FMovieSceneEvaluationFieldEntitySet & NewEntities, FMovieSceneEvaluationFieldEntitySet & OutPerTickConditionalEntities, TMap< uint32, bool > & ConditionResultCache)
To be called any time this ledger's instance is to be evaluated with a different set of entities - updates the set of entities that are required for the current evaluation environment.
Parameters
Linker The linker that owns this ledger
ImportParams Basis for import parameters
EntityField Possibly null if NewEntities is empty- an entity field containing structural information about the sequence
NewEntities A set specifying all the entities required for the next evaluation. Specifying an empty set will unlink all existing entities.
OutConditionalEntities Output set returning conditional entities that require re-evaluating in between full updates.
ConditionResultCache Cache of previous condition results, to be used and potentially modified during any condition checking in updating entities.
References EntityField, ImportParams, NewEntities, and UpdateEntities().
Referenced by UpdateEntities().
UpdateOneShotEntities()
MOVIESCENE_API void UE::MovieScene::FEntityLedger::UpdateOneShotEntities (UMovieSceneEntitySystemLinker * Linker, const FEntityImportSequenceParams & ImportParams, const FMovieSceneEntityComponentField * EntityField, const FMovieSceneEvaluationFieldEntitySet & NewEntities, TMap< uint32, bool > & ConditionResultCache)
Update any one-shot entities for the current frame.
Parameters
Linker The linker that owns this ledger
ImportParams Basis for import parameters
EntityField Possibly null if NewEntities is empty- an entity field containing structural information about the sequence
NewEntities A set specifying all the entities required for the next evaluation. Specifying an empty set will unlink all existing entities.
ConditionResultCache Cache of previous condition results, to be used and potentially modified during any condition checking in updating entities.
References EntityField, ImportParams, NewEntities, and UpdateOneShotEntities().
Referenced by UE_DEPRECATED(), and UpdateOneShotEntities().
Field Documentation
bInvalidated
bool UE::MovieScene::FEntityLedger::bInvalidated private
Whether we have been invalidated, and need to re-instantiate everything.
Definition at line 188 of file MovieSceneEntityLedger.h.
Referenced by IsInvalidated().
EntityField
const FEntityImportSequenceParams const FMovieSceneEntityComponentField * UE::MovieScene::FEntityLedger::EntityField
Definition at line 40 of file MovieSceneEntityLedger.h.
Referenced by CanImportEntity(), ImportEntity(), UE_DEPRECATED(), UpdateConditionalEntities(), UpdateEntities(), and UpdateOneShotEntities().
ImportedEntities
TMap<FMovieSceneEvaluationFieldEntityKey, FImportedEntityData> UE::MovieScene::FEntityLedger::ImportedEntities private
Map of source field entity key -> imported linker entities.
Definition at line 185 of file MovieSceneEntityLedger.h.
ImportParams
const FEntityImportSequenceParams & UE::MovieScene::FEntityLedger::ImportParams
Definition at line 40 of file MovieSceneEntityLedger.h.
Referenced by CanImportEntity(), ImportEntity(), UE_DEPRECATED(), UpdateConditionalEntities(), UpdateEntities(), and UpdateOneShotEntities().
NewEntities
const FEntityImportSequenceParams const FMovieSceneEntityComponentField const FMovieSceneEvaluationFieldEntitySet & UE::MovieScene::FEntityLedger::NewEntities
Definition at line 40 of file MovieSceneEntityLedger.h.
Referenced by UE_DEPRECATED(), UpdateEntities(), and UpdateOneShotEntities().
OneShotEntities
TArray<FMovieSceneEntityID> UE::MovieScene::FEntityLedger::OneShotEntities private
Map of source entities that were swept this frame.
Definition at line 182 of file MovieSceneEntityLedger.h.
Query
const FEntityImportSequenceParams const FMovieSceneEntityComponentField const FMovieSceneEvaluationFieldEntityQuery& UE::MovieScene::FEntityLedger::Query
Definition at line 118 of file MovieSceneEntityLedger.h.
Referenced by CanImportEntity(), and ImportEntity().
The documentation for this struct was generated from the following file:
MovieSceneEntityLedger.h