Unreal Engine 5.6 C++ API: FRDGTextureSRVDesc Class Reference
FRDGTextureSRVDesc Class Reference final
Descriptor for render graph tracked SRV.
#include "RenderGraphResources.h"
Public Member Functions
FRDGTextureSRVDesc ()=default
FRDGTextureSRVDesc (FRDGTexture *InTexture)
bool IsValid () const
Returns whether this descriptor conforms to requirements.
bool operator!= (const FRDGTextureSRVDesc &Other) const
bool operator== (const FRDGTextureSRVDesc &Other) const
Static Public Member Functions
static FRDGTextureSRVDesc Create (FRDGTextureRef Texture)
Create SRV that access all sub resources of texture.
static FRDGTextureSRVDesc CreateForMetaData (FRDGTextureRef Texture, ERDGTextureMetaDataAccess MetaData)
Create SRV with access to a specific meta data plane.
static FRDGTextureSRVDesc CreateForMipLevel (FRDGTextureRef Texture, int32 MipLevel)
Create SRV that access one specific mip level.
static FRDGTextureSRVDesc CreateForSlice (FRDGTextureRef Texture, int32 SliceIndex)
Create SRV that access one specific slice.
static FRDGTextureSRVDesc CreateWithPixelFormat (FRDGTextureRef Texture, EPixelFormat PixelFormat)
Create SRV that access all sub resources of texture with a specific pixel format.
Data Fields
FRDGTextureRef Texture = nullptr
Friends
uint32 GetTypeHash (const FRDGTextureSRVDesc &Desc)
Detailed Description
Descriptor for render graph tracked SRV.
Definition at line 745 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGTextureSRVDesc() [1/2]
FRDGTextureSRVDesc::FRDGTextureSRVDesc () default
Referenced by Create(), CreateForMetaData(), CreateForMipLevel(), CreateForSlice(), CreateWithPixelFormat(), GetTypeHash, operator!=(), and operator==().
FRDGTextureSRVDesc() [2/2]
FRDGTextureSRVDesc::FRDGTextureSRVDesc (FRDGTexture * InTexture) inline
Definition at line 751 of file RenderGraphResources.h.
References FRDGTexture::Desc, and Texture.
Member Function Documentation
Create()
FRDGTextureSRVDesc FRDGTextureSRVDesc::Create (FRDGTextureRef Texture) inline static
Create SRV that access all sub resources of texture.
Definition at line 762 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), and Texture.
Referenced by CreateForMetaData(), CreateForMipLevel(), CreateForSlice(), and CreateWithPixelFormat().
CreateForMetaData()
FRDGTextureSRVDesc FRDGTextureSRVDesc::CreateForMetaData (FRDGTextureRef Texture, ERDGTextureMetaDataAccess MetaData) inline static
Create SRV with access to a specific meta data plane.
Definition at line 801 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), Create(), MetaData, and Texture.
CreateForMipLevel()
FRDGTextureSRVDesc FRDGTextureSRVDesc::CreateForMipLevel (FRDGTextureRef Texture, int32 MipLevel) inline static
Create SRV that access one specific mip level.
Definition at line 768 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), check, Create(), and Texture.
CreateForSlice()
FRDGTextureSRVDesc FRDGTextureSRVDesc::CreateForSlice (FRDGTextureRef Texture, int32 SliceIndex) inline static
Create SRV that access one specific slice.
Definition at line 778 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), check, Create(), and Texture.
CreateWithPixelFormat()
FRDGTextureSRVDesc FRDGTextureSRVDesc::CreateWithPixelFormat (FRDGTextureRef Texture, EPixelFormat PixelFormat) inline static
Create SRV that access all sub resources of texture with a specific pixel format.
Definition at line 793 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), Create(), and Texture.
IsValid()
bool FRDGTextureSRVDesc::IsValid () const inline
Returns whether this descriptor conforms to requirements.
Definition at line 824 of file RenderGraphResources.h.
References Texture.
operator!=()
bool FRDGTextureSRVDesc::operator!= (const FRDGTextureSRVDesc & Other) const inline
Definition at line 813 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), and Other.
operator==()
bool FRDGTextureSRVDesc::operator== (const FRDGTextureSRVDesc & Other) const inline
Definition at line 808 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), Other, and Texture.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRDGTextureSRVDesc & Desc) friend
Definition at line 818 of file RenderGraphResources.h.
References FRDGTextureSRVDesc(), GetTypeHash, HashCombine(), and Texture.
Referenced by GetTypeHash.
Field Documentation
Texture
FRDGTextureRef FRDGTextureSRVDesc::Texture = nullptr
Definition at line 833 of file RenderGraphResources.h.
Referenced by FRDGTextureSRVDesc(), Create(), CreateForMetaData(), CreateForMipLevel(), CreateForSlice(), CreateWithPixelFormat(), GetTypeHash, IsValid(), and operator==().
The documentation for this class was generated from the following file:
RenderGraphResources.h