Unreal Engine 5.6 C++ API: MovieSceneEntitySystemTypes.h File Reference
MovieSceneEntitySystemTypes.h File Reference
#include "Algo/Find.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/BitArray.h"
#include "MovieSceneFwd.h"
#include "EntitySystem/MovieSceneEntityIDs.h"
#include "HAL/CriticalSection.h"
#include "Math/NumericLimits.h"
#include "Math/UnrealMathSSE.h"
#include "Misc/AssertionMacros.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/TransactionallySafeRWLock.h"
#include "Stats/Stats.h"
#include "Templates/UnrealTemplate.h"
#include <atomic>
#include <initializer_list>
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Functions
DECLARE_STATS_GROUP (TEXT("Movie Scene Evaluation Systems"), STATGROUP_MovieSceneECS, STATCAT_Advanced) namespace UE
Function Documentation
DECLARE_STATS_GROUP()
DECLARE_STATS_GROUP (TEXT("Movie Scene Evaluation Systems") , STATGROUP_MovieSceneECS , STATCAT_Advanced)
Null phase which indicates that the system never runs, but still exists in the reference graph
Expensive: Phase that is run before instantiation any time any boundary is crossed in the sequence. Used to spawn new objects and trigger pre/post-spawn events.
Expensive: Houses any system that needs to instantiate global entities into the linker, or make meaningful changes to entity structures..
Fast, distributed: Houses the majority of evaluation systems that compute animation data. Entity manager is locked down for the duration of this phase.
Finalization phase for enything that wants to run after everything else.
This component type should be preserved when an entity is replaced with another during linking
Automatically copy this component to child components when being constructed through the component factory
Indicates that this component type represents a cached value that should be copied to blend outputs
Indicates that this component type represents a cached value that should be migrated to blend outputs (and removed from blend inputs)
Enumeration specifying the locking mechanism to use when accessing component data
A numeric identifier used to represent a specific 'channel' within an interrogation linker. Interrogation channels are used to identify groupings of tracks or entities that relate to the same output (eg: a property on an object; a root track etc). See FInterrogationKey for a combination of a channel with a specific interrogation index (or time)
Default construction to an invalid channel
Get the next channel after this one
Check whether this channel is valid
Check whether this channel is valid
Get the underlying numeric representation of this channel
A default interrogation channel that can be used when interrogation is only operating on a single set of tracks
Retrieve the first allocatable channel when dealing with multiple groupings of tracks
Make a channel from an index known to already relate to a valid channel
Retrieve the last allocatable channel when dealing with multiple groupings of tracks
An invalid channel. Should only be used for comparison.
A key that uniquely identifies a specific interrogation time with a group of entities allocated within a channel
The channel that the entities are allocated within
The index of the interrogation (see FSystemInterrogator::InterrogateTime, and FSystemInterrogator::InterrogationData)
Sequence instance information for interrogations
Pointer to the first component of this header's type, with array size == FEntityAllocation::Capacity, and stride == FComponentHeader::Sizeof
Legacy mutex used for locked threaded evaluation
Serial number that is increased after every time this header is opened for write access. Not currently meaningfully used but may be used for caching in future.
Atomic access count used for verifying write exclusivity at runtime.
sizeof(T) for the component type this header represents (ie: the stride of our component data). 0 if this header represents a tag.
Component type identifier
Whether this component header describes a tag component (i.e. a component with no data).
Whether this component header is associated with a data buffer.
Tag components don't have data. Non-tag components could have no data if their data buffer has been relocated, such as an entity allocation that has moved elsewhere because of a migration or mutation.
Get the raw pointer to the associated component data buffer.
Moveable scoped read-lock type for component headers
Moveable scoped write-lock type for component headers
FEntityAllocation is the authoritative storage of entity-component data within an FEntityManager. It stores component data in separate contiguous arrays, aligned to a cache line. Storing component data in this way allows for cache-efficient and concurrent access to each component array in isolation. It also allows for write access to component arrays at the same time as concurrent read-access to other component arrays within the same entity allocation.
FEntityAllocations are custom allocated according to the size of its component capacity, which is loosely computed as sizeof(FEntityAllocation) + sizeof(ComponentData), not simply sizeof(FEntityAllocation).
A typical allocation will look like this in memory:
uint32 {UniqueID}, uint16 {NumComponents}, uint16 {Size}, uint16 {Capacity}, uint16 {MaxCapacity}, uint32 {SerialNumber}, FMovieSceneEntityID* {EntityIDs}, <– points to FMovieSceneEntityID array at end of structure FComponentHeader[NumComponents], <– each component header contains a component array ptr that points to its corresponding type array below (padding) FMovieSceneEntityID[Capacity], (padding) ComponentType1[Capacity], (padding) ComponentType2[Capacity], (padding) ComponentType3[Capacity],
Constructor that initializes the defaults for this structure. CAUTION: Does not initialize ComponentHeaders - these constructors must be called manually
Manually invoked destructor that calls the destructor of each component header according to the number of components
Entity allocations are non-copyable
Retrieve all of this allocation's component and tag headers.
Retrieve all of this allocation's component and tag headers.
Check whether this allocation has the specified component type
Parameters
ComponentTypeID The type ID for the component to check
Returns
true if these entities have the specified component, false otherwise
Find a component header by its type
Parameters
ComponentTypeID The type ID for the component header to locate
Returns
A pointer to the component header, or nullptr if one was not found
Find a component header by its type
Parameters
ComponentTypeID The type ID for the component header to locate
Returns
A pointer to the component header, or nullptr if one was not found
Get a reference to a component header by its type. Will fail an assertion if it does not exist.
Parameters
ComponentTypeID The type ID for the component header to locate
Returns
A reference to the component header
Get a reference to a component header by its type. Will fail an assertion if it does not exist.
Parameters
ComponentTypeID The type ID for the component header to locate
Returns
A reference to the component header
Retrieve all of this allocation's entity IDs
Retrieve all of this allocation's entity IDs as a raw ptr
Retrieve the address of this allocation's component data. Only to be used for construction of TRelativePtrs.
Get the unique identifier for this allocation. This identifier is unique to the specific allocation and entity manager, but is not globally unique. Typically used for caching component data on a per-allocation basis
Retrieve this allocation's serial number. The serial number is incremented whenever a component is modified on this allocation, or when an entity is added or removed. Typically used for caching component data on a per-allocation basis
Called when this allocation has been modified. Will invalidate any cached data based of this allocation's serial number
Get the number of component types and tags that exist within this allocation
Retrieve the number of entities in this allocation
Retrieve the maximum number of entities that this allocation is allowed to grow to until a new one must be made
Retrieve the number of entities this allocation can currently house without reallocation
Retrieve the amount of empty space within this allocation
Get this allocation's current lock mode
Read type-erased component data for the specified component type
Write type-erased component data for the specified component type
Attempt to read type-erased component data for the specified component type
Attempt to write type-erased component data for the specified component type
Read typed component data for the specified component type
Write typed component data for the specified component type
Write typed component data for the specified component type
Attempt to write typed component data for the specified component type
Assigned to FEntityManager::GetSystemSerial whenever this allocation is written to
Unique Identifier within this allocation's FEntityManager. This ID is never reused.
The number of component and tag types in this allocation (also defines the number of ComponentHeaders).
The number of entities currently allocated within this block. Defines the stride of each component array.
The maximum number of entities currently allocated within this block including slack. Defines the maximum stride of each component array.
The maximum number of entities that this entity is allowed to reallocate to accomodate for.
Lock mode for access - under threading models this will be set to EComponentHeaderLockMode::Mutex, EComponentHeaderLockMode::LockFree otherwise
Pointer to the entity ID array (stored in the end padding of this structure).
Pointer to separately allocated data buffer for components.
Pointer to array of the component headers of size NumComponents (stored in the end padding of this structure).
Scoped guard that temporarily overrides the locking mechanism for a specific allocation. In order to guarantee thread-safety, this structure only actually does anything if InLockMode is specified as LockFree
A wrapper around an FEntityAllocation that provides access to other pieces of information such as its component mask.
Gets the entity allocation
Gets the entity allocation
Gets the entity allocation component mask
Return this allocation's index within the entity manager
Implicit cast to an entity allocation
Implicit cast to an entity allocation
Implicit cast to a component mask
Hashing function for storing handles in maps
Entity manager being iterated
Current allocation index or Manager->EntityAllocationMasks.GetMaxIndex() when finished
Defines a contiguous range of entities within an allocation
Definition at line 27 of file MovieSceneEntitySystemTypes.h.
References A, Add, All, UE::MovieScene::AllOf, Any, B, bool, check, checkf, Complex, Components, Default, ENUM_CLASS_FLAGS, UE::MovieScene::Evaluation, UE::MovieScene::Finalization, Algo::FindBy(), First, GetTypeHash(), Header, Import, INDEX_NONE, Input, UE::MovieScene::Instantiation, Invalid, IsValid(), Last, MakeArrayView(), Mandatory, Mask, Match, FMath::Max, MAX_int32, MaxSize, None, Num, operator!=(), operator++(), operator<(), operator=(), operator==(), Optional, Reset, Spawn, TEXT, TSequenceHistory< HistorySize >::Size, and Value.