Unreal Engine 5.6 C++ API: UCachedAnimDataLibrary Class Reference
UCachedAnimDataLibrary Class Reference
#include "CachedAnimDataLibrary.h"
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION() static 1 bool StateMachine_IsStateRelevant(UAnimInstance *InAnimInstance
UFUNCTION () static 1 bool StateMachine_IsFullWeight(UAnimInstance *InAnimInstance
UFUNCTION () static 1 bool StateMachine_IsRelevant(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetAssetPlayerTime(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetAssetPlayerTimeRatio(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetCrossfadeDuration(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetGlobalWeight(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetLocalWeight(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetRelevantAnimTime(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetRelevantAnimTimeRemaining(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetRelevantAnimTimeRemainingFraction(UAnimInstance *InAnimInstance
UFUNCTION () static 1 float StateMachine_GetTotalWeight(UAnimInstance *InAnimInstance
UPARAM (ref) const FCachedAnimAssetPlayerData &CachedAnimAssetPlayerData)
UPARAM (ref) const FCachedAnimAssetPlayerData &CachedAnimAssetPlayerData)
UPARAM (ref) const FCachedAnimRelevancyData &CachedAnimRelevancyData)
UPARAM (ref) const FCachedAnimRelevancyData &CachedAnimRelevancyData)
UPARAM (ref) const FCachedAnimRelevancyData &CachedAnimRelevancyData)
UPARAM (ref) const FCachedAnimStateArray &CachedAnimStateArray)
UPARAM (ref) const FCachedAnimStateArray &CachedAnimStateArray)
UPARAM (ref) const FCachedAnimStateArray &CachedAnimStateArray)
UPARAM (ref) const FCachedAnimStateData &CachedAnimStateData)
UPARAM (ref) const FCachedAnimStateData &CachedAnimStateData)
UPARAM (ref) const FCachedAnimStateData &CachedAnimStateData)
UPARAM (ref) const FCachedAnimTransitionData &CachedAnimTransitionData)
Detailed Description
Definition at line 16 of file CachedAnimDataLibrary.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UCachedAnimDataLibrary::GENERATED_UCLASS_BODY () private
References Category, and UFUNCTION().
UFUNCTION() [1/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [2/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [3/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [4/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [5/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [6/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [7/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [8/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [9/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [10/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [11/11]
UCachedAnimDataLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UPARAM() [1/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [2/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [3/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [4/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [5/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [6/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [7/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [8/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [9/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
Referenced by UPARAM(), UPARAM(), UPARAM(), UPARAM(), and UPARAM().
UPARAM() [10/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [11/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
UPARAM() [12/12]
UCachedAnimDataLibrary::UPARAM (ref) const & private
References UPARAM().
The documentation for this class was generated from the following file:
CachedAnimDataLibrary.h