Unreal Engine 5.6 C++ API: UE::Cook::FCookDependencyContext Struct Reference
UE::Cook::FCookDependencyContext Struct Reference
Context passed into UE_COOK_DEPENDENCY_FUNCTION functions to provide calling flags and receive hash output.
#include "CookDependency.h"
Data Structures
struct FErrorHandlerScope
Private implementation struct used for AddErrorHandlerScope.
Public Member Functions
FCookDependencyContext (void *InHasher, TUniqueFunction< void(ELogVerbosity::Type, FString &&)> &&InOnLog, TUniqueFunction< void(ELogVerbosity::Type)> &&InOnInvalidated, FName InPackageName)
InHasher is void* to mask the implementation details of the hashbuilder.
FErrorHandlerScope ErrorHandlerScope (TUniqueFunction< FString(FString &&)> &&ErrorHandler)
Add a function that will be removed when the return value goes out of scope, to modify error strings reported inside the scope before passing them on to higher scopes or the error consumer.
FName GetPackageName () const
Get the name of the package being considered.
void Log (ELogVerbosity::Type, FString Message)
Send a message to the cook dependency context with the given severity.
void LogError (FString Message)
Calls Log(Error, Message) and ReportError.
void LogInvalidated (FString Message)
Calls Log(Display, Message) and ReportInvalidated.
void ReportError ()
Reports failure to compute the hash (e.g.
void ReportInvalidated ()
Reports that current evaluation of the function is different from all previous evaluations for a reason that cannot be reported as data passed into Update.
void * SetHasher (void *NewHasher)
Set a new hasher and return the old one.
void Update (const void *Data, uint64 Size)
Update the hashbuilder for the key being constructed (e.g.
Private Attributes
TArray< TUniqueFunction< FString(FString &&)>, TInlineAllocator< 1 > > ErrorHandlers
void * Hasher
TUniqueFunction< void(ELogVerbosity::Type)> OnInvalidated
TUniqueFunction< void(ELogVerbosity::Type, FString &&)> OnLog
FName PackageName
Detailed Description
Context passed into UE_COOK_DEPENDENCY_FUNCTION functions to provide calling flags and receive hash output.
Definition at line 29 of file CookDependency.h.
Constructor & Destructor Documentation
FCookDependencyContext()
UE::Cook::FCookDependencyContext::FCookDependencyContext (void * InHasher, TUniqueFunction< void(ELogVerbosity::Type, FString &&)> && InOnLog, TUniqueFunction< void(ELogVerbosity::Type)> && InOnInvalidated, FName InPackageName) inline explicit
InHasher is void* to mask the implementation details of the hashbuilder.
See Update function.
Definition at line 693 of file CookDependency.h.
References Hasher, MoveTemp(), OnInvalidated, OnLog, and PackageName.
Member Function Documentation
ErrorHandlerScope()
FErrorHandlerScope UE::Cook::FCookDependencyContext::ErrorHandlerScope (TUniqueFunction< FString(FString &&)> && ErrorHandler) nodiscard
Add a function that will be removed when the return value goes out of scope, to modify error strings reported inside the scope before passing them on to higher scopes or the error consumer.
e.g. FCookDependencyContext::FErrorHandlerScope Scope = Context.ErrorHandlerScope([](FString&& Inner) { return FString::Printf(TEXT("OuterClass for %s: %s"), *Name, *Inner);});
GetPackageName()
FName UE::Cook::FCookDependencyContext::GetPackageName () const inline
Get the name of the package being considered.
Definition at line 97 of file CookDependency.h.
References PackageName.
Log()
void UE::Cook::FCookDependencyContext::Log (ELogVerbosity::Type , FString Message)
Send a message to the cook dependency context with the given severity.
The message may be suppressed or reduced in verbosity based on the calling context.
LogError()
void UE::Cook::FCookDependencyContext::LogError (FString Message) inline
Calls Log(Error, Message) and ReportError.
Definition at line 463 of file CookDependency.h.
References ELogVerbosity::Error, Log, MoveTemp(), and ReportError().
LogInvalidated()
void UE::Cook::FCookDependencyContext::LogInvalidated (FString Message) inline
Calls Log(Display, Message) and ReportInvalidated.
Definition at line 469 of file CookDependency.h.
References ELogVerbosity::Display, Log, MoveTemp(), and ReportInvalidated().
ReportError()
void UE::Cook::FCookDependencyContext::ReportError ()
Reports failure to compute the hash (e.g.
because a file cannot be read). When called while calculating the initial hash the storage of the key fails and the package will be recooked on the next cook. When called while testing incrementally skippable the package is marked modified and recooked.
Referenced by LogError().
ReportInvalidated()
void UE::Cook::FCookDependencyContext::ReportInvalidated ()
Reports that current evaluation of the function is different from all previous evaluations for a reason that cannot be reported as data passed into Update.
When called while calculating the initial hash this call is ignored. When called while testing incrementally skippable the package is marked modified and recooked.
Referenced by LogInvalidated().
SetHasher()
void * UE::Cook::FCookDependencyContext::SetHasher (void * NewHasher)
Set a new hasher and return the old one.
Update()
void UE::Cook::FCookDependencyContext::Update (const void * Data, uint64 Size)
Update the hashbuilder for the key being constructed (e.g.
TargetDomainKey for cooked packages) with the given Data of Size bytes.
References TSequenceHistory< HistorySize >::Size.
Field Documentation
ErrorHandlers
TArray<TUniqueFunction<FString(FString&&)>, TInlineAllocator<1> > UE::Cook::FCookDependencyContext::ErrorHandlers private
Definition at line 105 of file CookDependency.h.
Hasher
void* UE::Cook::FCookDependencyContext::Hasher private
Definition at line 107 of file CookDependency.h.
Referenced by FCookDependencyContext().
OnInvalidated
TUniqueFunction<void(ELogVerbosity::Type)> UE::Cook::FCookDependencyContext::OnInvalidated private
Definition at line 104 of file CookDependency.h.
Referenced by FCookDependencyContext().
OnLog
TUniqueFunction<void(ELogVerbosity::Type, FString&&)> UE::Cook::FCookDependencyContext::OnLog private
Definition at line 103 of file CookDependency.h.
Referenced by FCookDependencyContext().
PackageName
FName UE::Cook::FCookDependencyContext::PackageName private
Definition at line 106 of file CookDependency.h.
Referenced by FCookDependencyContext(), and GetPackageName().
The documentation for this struct was generated from the following file:
CookDependency.h