Unreal Engine 5.6 C++ API: Tuple.h File Reference
Tuple.h File Reference
#include "CoreTypes.h"
#include "Templates/UnrealTemplate.h"
#include "Delegates/IntegerSequence.h"
#include "Templates/Invoke.h"
#include "Serialization/StructuredArchive.h"
#include "Serialization/MemoryLayout.h"
#include "Templates/Requires.h"
#include "Templates/TypeHash.h"
#include <tuple>
#include <type_traits>
Data Structures
struct std::tuple_element< N, TTuple< ArgTypes... > >
struct std::tuple_size< TTuple< ArgTypes... > >
struct TIsTuple< T >
struct TTuple< Types >
struct TTupleArity< TupleType >
Traits class which calculates the number of elements in a tuple.
struct UE::Core::Private::Tuple::FEqualityHelper< ArgCount, ArgToCompare >
struct UE::Core::Private::Tuple::FEqualityHelper< ArgCount, ArgCount >
struct UE::Core::Private::Tuple::TCVTupleArity< const volatile TTuple< Types... > >
struct UE::Core::Private::Tuple::TCVTupleElement< Index, TupleType >
struct UE::Core::Private::Tuple::TCVTupleElement< Index, const volatile TTuple< TupleTypes... > >
struct UE::Core::Private::Tuple::TCVTupleIndex< Type, TupleType >
struct UE::Core::Private::Tuple::TCVTupleIndex< Type, const volatile TTuple< TupleTypes... > >
struct UE::Core::Private::Tuple::TGetTupleHashHelper< ArgToCombine, ArgCount >
struct UE::Core::Private::Tuple::TGetTupleHashHelper< ArgIndex, ArgIndex >
struct UE::Core::Private::Tuple::TLessThanHelper< NumArgs, ArgToCompare, Last >
struct UE::Core::Private::Tuple::TLessThanHelper< NumArgs, ArgToCompare, true >
struct UE::Core::Private::Tuple::TLessThanHelper< NumArgs, NumArgs, false >
struct UE::Core::Private::Tuple::TTransformTuple_Impl< TIntegerSequence< uint32, Indices... > >
struct UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >
struct UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >
struct UE::Core::Private::Tuple::TTupleBaseElement< T, 0, 2 >
struct UE::Core::Private::Tuple::TTupleElementGetterByIndex< Index, TupleSize >
struct UE::Core::Private::Tuple::TTupleElementGetterByIndex< 0, 2 >
struct UE::Core::Private::Tuple::TTupleElementGetterByType< Type, TupleSize >
struct UE::Core::Private::Tuple::TVisitTupleElements_Impl< TIntegerSequence< uint32, Indices... > >
Namespaces
namespace Freeze
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
namespace UE::Core::Private::Tuple
Macros
#define UE_TUPLE_STATIC_ANALYSIS_WORKAROUND 0
Typedefs
template<typename KeyType, typename ValueType>
using TPair = TTuple<KeyType, ValueType>
template<uint32 Index, typename TupleType>
using TTupleElement = UE::Core::Private::Tuple::TCVTupleElement<Index, const volatile TupleType>
Traits class which gets the element type of a TTuple with the given index.
template<typename Type, typename TupleType>
using TTupleIndex = UE::Core::Private::Tuple::TCVTupleIndex<Type, const volatile TupleType>
Traits class which gets the tuple index of a given type from a given TTuple.
Enumerations
enum UE::Core::Private::Tuple::EForwardingConstructor { UE::Core::Private::Tuple::ForwardingConstructor }
enum UE::Core::Private::Tuple::EOtherTupleConstructor { UE::Core::Private::Tuple::OtherTupleConstructor }
Functions
template<typename LhsType, typename RhsType, uint32... Indices, decltype(ConceptCheckingHelper((DeclVal< LhsType & >().template Get< Indices >()=DeclVal< RhsType && >().template Get< Indices >(), 0)...)) * = nullptr>
static void UE::Core::Private::Tuple::Assign (LhsType &Lhs, RhsType &&Rhs, TIntegerSequence< uint32, Indices... >)
template<typename... Given, typename... Deduced>
decltype(ConceptCheckingHelper((DeclVal< Given >()=DeclVal< Deduced && >(), 0)...)) UE::Core::Private::Tuple::AssignableConceptCheck (Deduced &&...)
template<typename... ArgTypes>
void UE::Core::Private::Tuple::ConceptCheckingHelper (ArgTypes &&...)
template<typename... Given, typename... Deduced>
std::enable_if_t< std::conjunction_v< std::is_constructible< Given, Deduced && >... > > UE::Core::Private::Tuple::ConstructibleConceptCheck (Deduced &&...)
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename KeyType, typename ValueType >),(TTuple< KeyType, ValueType >))
template<typename... Types>
FORCEINLINE TTuple< Types &&... > ForwardAsTuple (Types &&... Args)
Makes a TTuple from some arguments.
template<int N, typename TupleType UE_REQUIRES>
decltype(auto) get (TupleType &&val)
template<typename... Types>
FORCEINLINE uint32 GetTypeHash (const TTuple< Types... > &Tuple)
FORCEINLINE uint32 GetTypeHash (const TTuple<> &Tuple)
template<typename KeyType, typename ValueType>
uint32 Freeze::IntrinsicAppendHash (const TTuple< KeyType, ValueType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename KeyType, typename ValueType>
uint32 Freeze::IntrinsicGetTargetAlignment (const TTuple< KeyType, ValueType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename KeyType, typename ValueType>
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TTuple< KeyType, ValueType > &Object, void *OutDst)
template<typename KeyType, typename ValueType>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TTuple< KeyType, ValueType > &Object, const FTypeLayoutDesc &)
template<typename... Types>
TTuple< std::decay_t< Types >... > MakeTuple (Types &&... Args)
Makes a TTuple from some arguments.
template<typename... Types>
FORCEINLINE TTuple< std::decay_t< Types >... > MakeTuple (Types &&... Args)
Makes a TTuple from some arguments.
template<typename... ElementTypes, typename... Types>
FORCEINLINE TTuple< ElementTypes... > UE::Core::Private::Tuple::MakeTupleImpl (Types &&... Args)
template<typename... Types>
FORCEINLINE FArchive & operator<< (FArchive &Ar, TTuple< Types... > &Tuple)
template<typename... Types>
FORCEINLINE void operator<< (FStructuredArchive::FSlot Slot, TTuple< Types... > &Tuple)
template<typename... Types>
FORCEINLINE TTuple< Types &... > Tie (Types &... Args)
Tie function for structured unpacking of tuples into individual variables.
template<typename FuncType, typename... Types>
FORCEINLINE decltype(auto) TransformTuple (const TTuple< Types... > &Tuple, FuncType Func)
template<typename FuncType, typename... Types>
FORCEINLINE decltype(auto) TransformTuple (TTuple< Types... > &&Tuple, FuncType Func)
Creates a new TTuple by applying a functor to each of the elements.
template<typename FuncType, typename FirstTupleType, typename... TupleTypes>
FORCEINLINE void VisitTupleElements (FuncType &&Func, FirstTupleType &&FirstTuple, TupleTypes &&... Tuples)
Visits each element in the specified tuples in parallel and applies them as arguments to the functor.
Variables
template<typename T>
constexpr bool TIsTuple_V = false
template<typename... Types>
constexpr bool TIsTuple_V< const TTuple< Types... > > = true
template<typename... Types>
constexpr bool TIsTuple_V< const volatile TTuple< Types... > > = true
template<typename... Types>
constexpr bool TIsTuple_V< TTuple< Types... > > = true
template<typename... Types>
constexpr bool TIsTuple_V< volatile TTuple< Types... > > = true
template<typename T, typename... Types>
constexpr uint32 UE::Core::Private::Tuple::TTypeCountInParameterPack_V = 0
template<typename T, typename U, typename... Types>
constexpr uint32 UE::Core::Private::Tuple::TTypeCountInParameterPack_V< T, U, Types... > = TTypeCountInParameterPack_V<T, Types...> + (std::is_same_v<T, U> ? 1 : 0)
Macro Definition Documentation
UE_TUPLE_STATIC_ANALYSIS_WORKAROUND
#define UE_TUPLE_STATIC_ANALYSIS_WORKAROUND 0
Definition at line 37 of file Tuple.h.
Typedef Documentation
TPair
template<typename KeyType, typename ValueType> using TPair = TTuple<KeyType, ValueType>
Definition at line 46 of file Tuple.h.
TTupleElement
template<uint32 Index, typename TupleType> using TTupleElement = UE::Core::Private::Tuple::TCVTupleElement<Index, const volatile TupleType>
Traits class which gets the element type of a TTuple with the given index.
If the index is out of range, a compile error is generated.
Given Index = 1, and Tuple = TTuple<int, float, char>, TTupleElement<Index, Tuple>::Type will be float.
Definition at line 820 of file Tuple.h.
TTupleIndex
template<typename Type, typename TupleType> using TTupleIndex = UE::Core::Private::Tuple::TCVTupleIndex<Type, const volatile TupleType>
Traits class which gets the tuple index of a given type from a given TTuple.
If the type doesn't appear, or appears more than once, a compile error is generated.
Given Type = char, and Tuple = TTuple<int, float, char>, TTupleIndex<Type, Tuple>::Value will be 2.
Definition at line 809 of file Tuple.h.
Function Documentation
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT()
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename KeyType, typename ValueType >) , (TTuple< KeyType, ValueType >))
ForwardAsTuple()
template<typename... Types> FORCEINLINE TTuple< Types &&... > ForwardAsTuple (Types &&... Args)
Makes a TTuple from some arguments.
Unlike MakeTuple, the TTuple element types are references and retain the same value category of the arguments, like the Forward function.
Parameters
Args The arguments used to construct the tuple.
Returns
A tuple containing forwarded references to the arguments.
Example:
template <typename... Ts> void Foo(const TTuple<Ts...>&);
void Func(const int32 A, FString&& B) { // Calls Foo<const int32&, const TCHAR(&)[6], FString&&>(...); Foo(ForwardAsTuple(A, TEXT("Hello"), MoveTemp(B))); }
Definition at line 864 of file Tuple.h.
References FORCEINLINE, Forward(), and UE::Core::Private::Tuple::MakeTupleImpl().
get()
template<int N, typename TupleType UE_REQUIRES> decltype(auto) get (TupleType && val)
Definition at line 988 of file Tuple.h.
GetTypeHash() [1/2]
template<typename... Types> FORCEINLINE uint32 GetTypeHash (const TTuple< Types... > & Tuple)
Definition at line 747 of file Tuple.h.
References FORCEINLINE, and GetTypeHash().
Referenced by GetTypeHash().
GetTypeHash() [2/2]
FORCEINLINE uint32 GetTypeHash (const TTuple<> & Tuple)
Definition at line 752 of file Tuple.h.
References FORCEINLINE.
MakeTuple() [1/2]
template<typename... Types> TTuple< std::decay_t< Types >... > MakeTuple (Types &&... Args)
Makes a TTuple from some arguments.
The type of the TTuple elements are the decayed versions of the arguments.
Parameters
Args The arguments used to construct the tuple.
Returns
A tuple containing a copy of the arguments.
Example:
void Func(const int32 A, FString&& B) { // Equivalent to: // TTuple<int32, const TCHAR*, FString> MyTuple(A, TEXT("Hello"), MoveTemp(B)); auto MyTuple = MakeTuple(A, TEXT("Hello"), MoveTemp(B)); }
Definition at line 839 of file Tuple.h.
References FORCEINLINE, Forward(), and UE::Core::Private::Tuple::MakeTupleImpl().
Referenced by UE::Core::Private::Tuple::TTransformTuple_Impl< TIntegerSequence< uint32, Indices... > >::Do(), FMovieSceneChannelValueHelper::FindFirstKey(), UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachAllocationImpl(), UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl(), UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl(), UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >::GetGroupKey(), UE::MovieScene::TPropertyMetaDataComponentsImpl< TIntegerSequence< int, Indices... >, TPropertyMetaData< MetaDataTypes... > >::GetType(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), UE::MovieScene::FInstanceRegistry::InvalidateObjectBinding(), UE::MovieScene::FInstanceRegistry::IsBindingInvalidated(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerAllocationImpl(), FAssetDataTagMapSharedView::MakePair(), FAssetDataTagMapSharedView::MakePair(), UE::Slate::MakeTupleIndiciesInner(), TraceServices::TCachedStringStore< WIDECHAR >::StoreInternal(), and FBuoyancyComponentSim::UpdateBuoyancy().
MakeTuple() [2/2]
template<typename... Types> FORCEINLINE TTuple< std::decay_t< Types >... > MakeTuple (Types &&... Args)
Makes a TTuple from some arguments.
The type of the TTuple elements are the decayed versions of the arguments.
Parameters
Args The arguments used to construct the tuple.
Returns
A tuple containing a copy of the arguments.
Example:
void Func(const int32 A, FString&& B) { // Equivalent to: // TTuple<int32, const TCHAR*, FString> MyTuple(A, TEXT("Hello"), MoveTemp(B)); auto MyTuple = MakeTuple(A, TEXT("Hello"), MoveTemp(B)); }
Definition at line 839 of file Tuple.h.
References FORCEINLINE, Forward(), and UE::Core::Private::Tuple::MakeTupleImpl().
Referenced by UE::Core::Private::Tuple::TTransformTuple_Impl< TIntegerSequence< uint32, Indices... > >::Do(), FMovieSceneChannelValueHelper::FindFirstKey(), UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachAllocationImpl(), UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl(), UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl(), UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >::GetGroupKey(), UE::MovieScene::TPropertyMetaDataComponentsImpl< TIntegerSequence< int, Indices... >, TPropertyMetaData< MetaDataTypes... > >::GetType(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), UE::MovieScene::FInstanceRegistry::InvalidateObjectBinding(), UE::MovieScene::FInstanceRegistry::IsBindingInvalidated(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerAllocationImpl(), FAssetDataTagMapSharedView::MakePair(), FAssetDataTagMapSharedView::MakePair(), UE::Slate::MakeTupleIndiciesInner(), TraceServices::TCachedStringStore< WIDECHAR >::StoreInternal(), and FBuoyancyComponentSim::UpdateBuoyancy().
operator<<() [1/2]
template<typename... Types> FORCEINLINE FArchive & operator<< (FArchive & Ar, TTuple< Types... > & Tuple)
Definition at line 997 of file Tuple.h.
References Ar, and FORCEINLINE.
operator<<() [2/2]
template<typename... Types> FORCEINLINE void operator<< (FStructuredArchive::FSlot Slot, TTuple< Types... > & Tuple)
Definition at line 1004 of file Tuple.h.
References FORCEINLINE.
Tie()
template<typename... Types> FORCEINLINE TTuple< Types &... > Tie (Types &... Args)
Tie function for structured unpacking of tuples into individual variables.
Example:
TTuple<FString, float, TArray<int32>> SomeFunction();
FString Ret1; float Ret2; TArray<int32> Ret3;
Tie(Ret1, Ret2, Ret3) = SomeFunction();
// Now Ret1, Ret2 and Ret3 contain the unpacked return values.
Definition at line 944 of file Tuple.h.
References FORCEINLINE.
TransformTuple() [1/2]
template<typename FuncType, typename... Types> FORCEINLINE decltype(auto) TransformTuple (const TTuple< Types... > & Tuple, FuncType Func)
Definition at line 898 of file Tuple.h.
References FORCEINLINE, and MoveTemp().
TransformTuple() [2/2]
template<typename FuncType, typename... Types> FORCEINLINE decltype(auto) TransformTuple (TTuple< Types... > && Tuple, FuncType Func)
Creates a new TTuple by applying a functor to each of the elements.
Parameters
Tuple The tuple to apply the functor to.
Func The functor to apply.
Returns
A new tuple of the transformed elements.
Example:
float Overloaded(int32 Arg); char Overloaded(const TCHAR* Arg); const TCHAR* Overloaded(const FString& Arg);
void Func(const TTuple<int32, const TCHAR*, FString>& MyTuple) { // Equivalent to: // TTuple<float, char, const TCHAR*> TransformedTuple(Overloaded(MyTuple.Get<0>()), Overloaded(MyTuple.Get<1>()), Overloaded(MyTuple.Get<2>()))); auto TransformedTuple = TransformTuple(MyTuple, [](const auto& Arg) { return Overloaded(Arg); }); }
Definition at line 892 of file Tuple.h.
References FORCEINLINE, and MoveTemp().
VisitTupleElements()
template<typename FuncType, typename FirstTupleType, typename... TupleTypes> FORCEINLINE void VisitTupleElements (FuncType && Func, FirstTupleType && FirstTuple, TupleTypes &&... Tuples)
Visits each element in the specified tuples in parallel and applies them as arguments to the functor.
All specified tuples must have the same number of elements.
Parameters
Func The functor to apply.
Tuples The tuples whose elements are to be applied to the functor.
Example:
void Func(const TTuple<int32, const TCHAR*, FString>& Tuple1, const TTuple<bool, float, FName>& Tuple2) { // Equivalent to: // Functor(Tuple1.Get<0>(), Tuple2.Get<0>()); // Functor(Tuple1.Get<1>(), Tuple2.Get<1>()); // Functor(Tuple1.Get<2>(), Tuple2.Get<2>()); VisitTupleElements(Functor, Tuple1, Tuple2); }
Definition at line 923 of file Tuple.h.
References FORCEINLINE, Forward(), and Value.
Referenced by UE::MovieScene::TMultiComponentData< TReadOptional< T >... >< FCustomPropertyIndex, uint16, TSharedPtr< FTrackInstancePropertyBindings > >::TMultiComponentData(), Algo::Private::TTiedTupleAdder< OutputTypes >::Add(), UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Discard(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::GenerateType(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::Initialize(), UE::String::JoinTupleByTo(), UE::String::JoinTupleQuotedByTo(), LoadFromCompactBinary(), UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::MutateExisting(), UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >::OnObjectsReplaced(), and operator<<().
Variable Documentation
TIsTuple_V
template<typename T> bool TIsTuple_V = false constexpr
Definition at line 949 of file Tuple.h.
TIsTuple_V< const TTuple< Types... > >
template<typename... Types> bool TIsTuple_V< const TTuple< Types... > > = true constexpr
Definition at line 952 of file Tuple.h.
TIsTuple_V< const volatile TTuple< Types... > >
template<typename... Types> bool TIsTuple_V< const volatile TTuple< Types... > > = true constexpr
Definition at line 954 of file Tuple.h.
TIsTuple_V< TTuple< Types... > >
template<typename... Types> bool TIsTuple_V< TTuple< Types... > > = true constexpr
Definition at line 951 of file Tuple.h.
TIsTuple_V< volatile TTuple< Types... > >
template<typename... Types> bool TIsTuple_V< volatile TTuple< Types... > > = true constexpr
Definition at line 953 of file Tuple.h.