Unreal Engine 5.6 C++ API: FWildcardString Class Reference
FWildcardString Class Reference
Implements a string with wild card pattern matching abilities.
#include "WildcardString.h"
Public Member Functions
FWildcardString ()
Default constructor.
FWildcardString (const FString &Pattern)
Creates and initializes a new instance with the specified pattern.
FWildcardString (const TCHAR *Pattern)
Creates and initializes a new instance with the specified pattern.
bool ContainsWildcards () const
Checks whether this string contains wild card characters.
bool IsMatch (const FString &Input) const
Matches the given input string to this wild card pattern.
bool IsMatch (const TCHAR *Input) const
Matches the given input string to this wild card pattern.
Static Public Member Functions
static bool ContainsWildcards (const TCHAR *Pattern)
Checks whether the specified pattern contains wild card characters.
static bool IsMatch (const TCHAR *Pattern, const TCHAR *Input)
Non-recursive wild card string matching algorithm.
static bool IsMatchSubstring (const TCHAR *Pattern, const TCHAR *Input, const TCHAR *InputEnd, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive)
As IsMatch, except can accept the end of the input string in order to facilitate FStringView usage.
Static Protected Attributes
static const TCHAR EndOfString = TCHAR('\0')
Holds the string terminator character.
static const TCHAR ExactWildcard = TCHAR('?')
Holds the wild card that matches exactly one character (default is '?
static const TCHAR SequenceWildcard = TCHAR('*')
Holds the wild card that matches a sequence of characters (default is '*').
Detailed Description
Implements a string with wild card pattern matching abilities.
The FWildcardString is meant to hold the pattern you are matching against. For basic use, just call the static functions IsMatch() or IsMatchSubstring if you have FStringView
Definition at line 16 of file WildcardString.h.
Constructor & Destructor Documentation
FWildcardString() [1/3]
FWildcardString::FWildcardString () inline
Default constructor.
Definition at line 22 of file WildcardString.h.
FWildcardString() [2/3]
FWildcardString::FWildcardString (const FString & Pattern) inline
Creates and initializes a new instance with the specified pattern.
Parameters
Pattern The pattern string.
Definition at line 31 of file WildcardString.h.
FWildcardString() [3/3]
FWildcardString::FWildcardString (const TCHAR * Pattern) inline
Creates and initializes a new instance with the specified pattern.
Parameters
Pattern The pattern string.
Definition at line 40 of file WildcardString.h.
Member Function Documentation
ContainsWildcards() [1/2]
bool FWildcardString::ContainsWildcards () const inline
Checks whether this string contains wild card characters.
Returns
true if this string contains wild cards, false otherwise.
Definition at line 51 of file WildcardString.h.
References ContainsWildcards().
Referenced by ContainsWildcards().
ContainsWildcards() [2/2]
bool FWildcardString::ContainsWildcards (const TCHAR * Pattern) static
Checks whether the specified pattern contains wild card characters.
Parameters
Pattern The string to check.
Returns
true if the string contains wild cards, false otherwise.
IsMatch() [1/3]
bool FWildcardString::IsMatch (const FString & Input) const inline
Matches the given input string to this wild card pattern.
Parameters
Input The string to match.
Returns
true if the input string matches this pattern, false otherwise.
Definition at line 73 of file WildcardString.h.
References Input, and IsMatch().
IsMatch() [2/3]
bool FWildcardString::IsMatch (const TCHAR * Input) const inline
Matches the given input string to this wild card pattern.
Parameters
Input The string to match.
Returns
true if the input string matches this pattern, false otherwise.
Definition at line 62 of file WildcardString.h.
References Input, and IsMatch().
Referenced by IsMatch(), and IsMatch().
IsMatch() [3/3]
bool FWildcardString::IsMatch (const TCHAR * Pattern, const TCHAR * Input) static
Non-recursive wild card string matching algorithm.
Parameters
Pattern The pattern to match.
Input The input string to check.
References Input.
IsMatchSubstring()
bool FWildcardString::IsMatchSubstring (const TCHAR * Pattern, const TCHAR * Input, const TCHAR * InputEnd, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) static
As IsMatch, except can accept the end of the input string in order to facilitate FStringView usage.
if ESearchCase::IgnoreCase is used, the pattern and input are ToLower()d before comparison (note - does not apply locale and just uses c runtime style tolower)
References ESearchCase::CaseSensitive, and Input.
Field Documentation
EndOfString
const TCHAR FWildcardString::EndOfString = TCHAR('\0') static protected
Holds the string terminator character.
Definition at line 109 of file WildcardString.h.
ExactWildcard
const TCHAR FWildcardString::ExactWildcard = TCHAR('?') static protected
Holds the wild card that matches exactly one character (default is '?
').
Definition at line 112 of file WildcardString.h.
SequenceWildcard
const TCHAR FWildcardString::SequenceWildcard = TCHAR('*') static protected
Holds the wild card that matches a sequence of characters (default is '*').
Definition at line 115 of file WildcardString.h.
The documentation for this class was generated from the following file:
WildcardString.h