Unreal Engine 5.6 C++ API: FPathFollowingResultFlags Namespace Reference
FPathFollowingResultFlags Namespace Reference
Typedefs
typedef uint16 Type
Functions
FString ToString (uint16 Value)
Variables
const Type AlreadyAtGoal = (1 << 9)
Finish details: never started, agent was already at goal.
const Type Blocked = (1 << 1)
Movement was blocked (EPathFollowingResult::Blocked)
const Type FirstGameplayFlagShift = 10
Can be used to create project specific reasons.
const Type ForcedScript = (1 << 8)
Abort details: blueprint MoveTo function was called.
const Type InvalidPath = (1 << 5)
Abort details: path is no longer valid.
const Type MovementStop = (1 << 6)
Abort details: unable to move.
const Type NewRequest = (1 << 7)
Abort details: new movement request was received.
const Type None = 0
const Type OffPath = (1 << 2)
Agent is not on path (EPathFollowingResult::OffPath)
const Type OwnerFinished = (1 << 4)
Abort details: owner no longer wants to move.
const Type Success = (1 << 0)
Reached destination (EPathFollowingResult::Success)
const Type UserAbort = (1 << 3)
Aborted (EPathFollowingResult::Aborted)
const Type UserAbortFlagMask = ~(Success | Blocked | OffPath)
Typedef Documentation
Type
typedef uint16 FPathFollowingResultFlags::Type
Definition at line 79 of file PathFollowingComponent.h.
Function Documentation
ToString()
FString FPathFollowingResultFlags::ToString (uint16 Value)
References Value.
Variable Documentation
AlreadyAtGoal
const Type FPathFollowingResultFlags::AlreadyAtGoal = (1 << 9) inline
Finish details: never started, agent was already at goal.
Definition at line 111 of file PathFollowingComponent.h.
Blocked
const Type FPathFollowingResultFlags::Blocked = (1 << 1) inline
Movement was blocked (EPathFollowingResult::Blocked)
Definition at line 87 of file PathFollowingComponent.h.
FirstGameplayFlagShift
const Type FPathFollowingResultFlags::FirstGameplayFlagShift = 10 inline
Can be used to create project specific reasons.
Definition at line 114 of file PathFollowingComponent.h.
ForcedScript
const Type FPathFollowingResultFlags::ForcedScript = (1 << 8) inline
Abort details: blueprint MoveTo function was called.
Definition at line 108 of file PathFollowingComponent.h.
InvalidPath
const Type FPathFollowingResultFlags::InvalidPath = (1 << 5) inline
Abort details: path is no longer valid.
Definition at line 99 of file PathFollowingComponent.h.
MovementStop
const Type FPathFollowingResultFlags::MovementStop = (1 << 6) inline
Abort details: unable to move.
Definition at line 102 of file PathFollowingComponent.h.
NewRequest
const Type FPathFollowingResultFlags::NewRequest = (1 << 7) inline
Abort details: new movement request was received.
Definition at line 105 of file PathFollowingComponent.h.
Referenced by FPathFollowingResult::IsInterrupted().
None
const Type FPathFollowingResultFlags::None = 0 inline
Definition at line 81 of file PathFollowingComponent.h.
OffPath
const Type FPathFollowingResultFlags::OffPath = (1 << 2) inline
Agent is not on path (EPathFollowingResult::OffPath)
Definition at line 90 of file PathFollowingComponent.h.
OwnerFinished
const Type FPathFollowingResultFlags::OwnerFinished = (1 << 4) inline
Abort details: owner no longer wants to move.
Definition at line 96 of file PathFollowingComponent.h.
Success
const Type FPathFollowingResultFlags::Success = (1 << 0) inline
Reached destination (EPathFollowingResult::Success)
Definition at line 84 of file PathFollowingComponent.h.
Referenced by FPathFollowingResult::IsFailure(), and FPathFollowingResult::IsSuccess().
UserAbort
const Type FPathFollowingResultFlags::UserAbort = (1 << 3) inline
Aborted (EPathFollowingResult::Aborted)
Definition at line 93 of file PathFollowingComponent.h.
Referenced by FPathFollowingResult::IsInterrupted().
UserAbortFlagMask
const Type FPathFollowingResultFlags::UserAbortFlagMask = ~(Success | Blocked | OffPath) inline
Definition at line 116 of file PathFollowingComponent.h.