Unreal Engine 5.6 C++ API: ArrayView.h File Reference
ArrayView.h File Reference
#include "CoreTypes.h"
#include "Containers/ContainersFwd.h"
#include "Misc/AssertionMacros.h"
#include "Misc/ReverseIterate.h"
#include "Misc/IntrusiveUnsetOptionalState.h"
#include "Templates/Invoke.h"
#include "Templates/UnrealTypeTraits.h"
#include "Traits/ElementType.h"
#include "Containers/Array.h"
#include "Math/UnrealMathUtility.h"
#include <type_traits>
Data Structures
class TArrayView< InElementType, InSizeType >
Templated fixed-size view of another array.
struct TIsContiguousContainer< TArrayView< T, SizeType > >
struct TIsTArrayView< T >
struct TIsZeroConstructType< TArrayView< InElementType > >
struct UE::Core::ArrayView::Private::TIsCompatibleRangeType< RangeType, ElementType >
Trait testing whether a type is compatible with the view type.
struct UE::Core::ArrayView::Private::TIsReinterpretableRangeType< RangeType, ElementType >
Trait testing whether a type is reinterpretable in a way that permits use with the view type.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::ArrayView
namespace UE::Core::ArrayView::Private
Functions
template<typename T>
FORCEINLINE decltype(auto) UE::Core::ArrayView::Private::GetDataHelper (T &&Arg)
template<typename T>
FORCEINLINE decltype(auto) UE::Core::ArrayView::Private::GetReinterpretedDataHelper (T &&Arg)
template<typename ElementType>
TArrayView< ElementType > MakeArrayView (ElementType *Pointer UE_LIFETIMEBOUND, int32 Size)
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && !TIsTArrayView_V<CVUnqualifiedOtherRangeType>)>
auto MakeArrayView (OtherRangeType &&Other UE_LIFETIMEBOUND)
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && TIsTArrayView_V<CVUnqualifiedOtherRangeType>)>
auto MakeArrayView (OtherRangeType &&Other)
template<typename ElementType>
TArrayView< const ElementType > MakeArrayView (std::initializer_list< ElementType > List UE_LIFETIMEBOUND)
template<typename ElementType>
TArrayView< const ElementType > MakeConstArrayView (const ElementType *Pointer UE_LIFETIMEBOUND, int32 Size)
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && !TIsTArrayView_V<CVUnqualifiedOtherRangeType>)>
auto MakeConstArrayView (OtherRangeType &&Other UE_LIFETIMEBOUND)
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && TIsTArrayView_V<CVUnqualifiedOtherRangeType>)>
auto MakeConstArrayView (OtherRangeType &&Other)
template<typename ElementType>
TArrayView< const ElementType > MakeConstArrayView (std::initializer_list< ElementType > List UE_LIFETIMEBOUND)
template<typename RangeType, typename ElementType UE_REQUIRES>
bool operator!= (RangeType &&Lhs, TArrayView< ElementType > Rhs)
Inequality operator.
template<typename RangeType, typename ElementType UE_REQUIRES>
bool operator!= (TArrayView< ElementType > Lhs, RangeType &&Rhs)
template<typename ElementType, typename SizeType, typename OtherElementType, typename OtherSizeType>
bool operator!= (TArrayView< ElementType, SizeType >, TArrayView< OtherElementType, OtherSizeType >)=delete
template<typename RangeType, typename ElementType UE_REQUIRES>
bool operator== (RangeType &&Lhs, TArrayView< ElementType > Rhs)
Equality operator.
template<typename RangeType, typename ElementType UE_REQUIRES>
bool operator== (TArrayView< ElementType > Lhs, RangeType &&Rhs)
template<typename ElementType, typename SizeType, typename OtherElementType, typename OtherSizeType>
bool operator== (TArrayView< ElementType, SizeType >, TArrayView< OtherElementType, OtherSizeType >)=delete
Variables
template<typename T, typename ElementType>
constexpr bool UE::Core::ArrayView::Private::TIsCompatibleElementType_V =std::is_convertible_v<T**, ElementType* const*>
Trait testing whether a type is compatible with the view type.
template<typename T>
constexpr bool TIsTArrayView_V = false
template<typename InElementType, typename InSizeType>
constexpr bool TIsTArrayView_V< const TArrayView< InElementType, InSizeType > > = true
template<typename InElementType, typename InSizeType>
constexpr bool TIsTArrayView_V< const volatile TArrayView< InElementType, InSizeType > > = true
template<typename InElementType, typename InSizeType>
constexpr bool TIsTArrayView_V< TArrayView< InElementType, InSizeType > > = true
template<typename InElementType, typename InSizeType>
constexpr bool TIsTArrayView_V< volatile TArrayView< InElementType, InSizeType > > = true
Function Documentation
MakeArrayView() [1/4]
template<typename ElementType> TArrayView< ElementType > MakeArrayView (ElementType *Pointer UE_LIFETIMEBOUND, int32 Size) nodiscard
Definition at line 864 of file ArrayView.h.
References Pointer, TSequenceHistory< HistorySize >::Size, and UE_LIFETIMEBOUND.
MakeArrayView() [2/4]
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && !TIsTArrayView_V<CVUnqualifiedOtherRangeType>)> auto MakeArrayView (OtherRangeType &&Other UE_LIFETIMEBOUND) nodiscard
Definition at line 858 of file ArrayView.h.
References Forward(), Other, and UE_LIFETIMEBOUND.
MakeArrayView() [3/4]
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && TIsTArrayView_V<CVUnqualifiedOtherRangeType>)> auto MakeArrayView (OtherRangeType && Other) nodiscard
Definition at line 849 of file ArrayView.h.
References Forward(), and Other.
Referenced by FResourceArrayUploadArrayView::FResourceArrayUploadArrayView(), FResourceBulkDataArrayView::FResourceBulkDataArrayView(), FDisplayClusterConfiguratorTreeBuilderOutput::Add(), UE::Anim::AddTypedCustomAttribute(), UE::MemStack::AllocateArrayView(), UE::MovieScene::TComponentPtr< T >::AsArray(), TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), ITypedElementWorldInterface::CopyElement(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_STATS_GROUP(), ITypedElementWorldInterface::DeleteElement(), FISMPartitionInstanceManager::DeleteISMPartitionInstance(), FSMInstanceManager::DeleteSMInstance(), ITypedElementWorldInterface::DuplicateElement(), FISMPartitionInstanceManager::DuplicateISMPartitionInstance(), FSMInstanceManager::DuplicateSMInstance(), FDisplayClusterConfiguratorTreeBuilderOutput::Find(), UE::MovieScene::TEntityRange< T >::GetAll(), UE::MovieScene::TMultiComponentData< TReadOptional< T >... >< FCustomPropertyIndex, uint16, TSharedPtr< FTrackInstancePropertyBindings > >::GetAsArray(), FSlateWindowElementList::GetCachedElementDataList(), FPersistentStorageManager::FCategoryInfo::GetCategories(), FPersistentStorageManager::FCategoryInfo::GetCategories(), FInstancedSkinnedMeshComponentHelper::GetComponentDesc(), UE::MovieScene::FPropertyRegistry::GetComposites(), TraceServices::GetElementRangeOverlappingGivenRange(), FShaderPreprocessOutput::GetErrors(), UE::Sequencer::FViewModelExtensionCollection::GetExtensions(), UE::MovieScene::FPlaybackCapabilitiesImpl::GetHeaders(), FSlateCachedElementData::GetListsWithNewData(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToMeshBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToParentLODBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToSkeletonBoneIndexMap(), UE::GC::FWorkBlock::GetObjects(), UE::GC::FWorkBlock::GetPadding(), FPersistentStorageManager::FRootDirInfo::GetRootDirectories(), UE::MovieScene::TPropertyMetaDataComponentsImpl< TIntegerSequence< int, Indices... >, TPropertyMetaData< MetaDataTypes... > >::GetTypes(), FHistogram::InitFromArray(), FGenericPlatformChunkInstall::InstallNamedChunk(), FPropertySoftPath::IsSubPropertyMatch(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), MakeConstStridedView(), MakeStridedView(), FXxHash128::operator<<, FXxHash64::operator<<, UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray(), UE::Virtualization::IVirtualizationSystem::PullData(), UE::Virtualization::IVirtualizationSystem::PullData(), UE::Virtualization::IVirtualizationSystem::PushData(), UE::Virtualization::IVirtualizationSystem::PushData(), UE::MovieScene::FPropertyComponentArrayView::ReinterpretCast(), UInstancedStaticMeshComponent::RemoveInstanceById(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Select(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Select(), UInstancedStaticMeshComponent::SetCustomDataById(), IAnimationDataController::SetTypedAttributeKeys(), UE::MovieScene::TComponentPtr< T >::Slice(), TBVTree< InElementType, InAllocator >::Subdivide(), FGenericPlatformChunkInstall::UninstallNamedChunk(), TraceServices::PagedArrayAlgoImpl::UpperBoundInternal(), USTRUCT(), USTRUCT(), and UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::ZeroAccumulationBuffers().
MakeArrayView() [4/4]
template<typename ElementType> TArrayView< const ElementType > MakeArrayView (std::initializer_list< ElementType > List UE_LIFETIMEBOUND) nodiscard
Definition at line 870 of file ArrayView.h.
References UE_LIFETIMEBOUND.
MakeConstArrayView() [1/4]
template<typename ElementType> TArrayView< const ElementType > MakeConstArrayView (const ElementType *Pointer UE_LIFETIMEBOUND, int32 Size) nodiscard
Definition at line 895 of file ArrayView.h.
References Pointer, TSequenceHistory< HistorySize >::Size, and UE_LIFETIMEBOUND.
MakeConstArrayView() [2/4]
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && !TIsTArrayView_V<CVUnqualifiedOtherRangeType>)> auto MakeConstArrayView (OtherRangeType &&Other UE_LIFETIMEBOUND) nodiscard
Definition at line 889 of file ArrayView.h.
References Forward(), Other, and UE_LIFETIMEBOUND.
MakeConstArrayView() [3/4]
template<typename OtherRangeType, typename CVUnqualifiedOtherRangeType = std::remove_cv_t<std::remove_reference_t<OtherRangeType>> UE_REQUIRES(TIsContiguousContainer<CVUnqualifiedOtherRangeType>::Value && TIsTArrayView_V<CVUnqualifiedOtherRangeType>)> auto MakeConstArrayView (OtherRangeType && Other) nodiscard
Definition at line 880 of file ArrayView.h.
References Forward(), and Other.
Referenced by FWaterMeshIndexBuffer::CreateIndexBuffer(), FShaderCodeResource::GetCodeView(), and FShaderCodeReader::GetOffsetShaderCode().
MakeConstArrayView() [4/4]
template<typename ElementType> TArrayView< const ElementType > MakeConstArrayView (std::initializer_list< ElementType > List UE_LIFETIMEBOUND) nodiscard
Definition at line 901 of file ArrayView.h.
References UE_LIFETIMEBOUND.
operator!=() [1/3]
template<typename RangeType, typename ElementType UE_REQUIRES> bool operator!= (RangeType && Lhs, TArrayView< ElementType > Rhs) nodiscard
Inequality operator.
Parameters
Lhs Another ranged type to compare.
Returns
False if this array view's contents and the other ranged type match. True otherwise.
Definition at line 955 of file ArrayView.h.
operator!=() [2/3]
template<typename RangeType, typename ElementType UE_REQUIRES> bool operator!= (TArrayView< ElementType > Lhs, RangeType && Rhs) nodiscard
Definition at line 965 of file ArrayView.h.
operator!=() [3/3]
template<typename ElementType, typename SizeType, typename OtherElementType, typename OtherSizeType> bool operator!= (TArrayView< ElementType, SizeType > , TArrayView< OtherElementType, OtherSizeType >) delete
operator==() [1/3]
template<typename RangeType, typename ElementType UE_REQUIRES> bool operator== (RangeType && Lhs, TArrayView< ElementType > Rhs) nodiscard
Equality operator.
Parameters
Lhs Another ranged type to compare.
Returns
True if this array view's contents and the other ranged type match. False otherwise.
Definition at line 927 of file ArrayView.h.
References CompareItems(), Count, GetData(), TArrayView< InElementType, InSizeType >::GetData(), GetNum(), and TArrayView< InElementType, InSizeType >::Num().
operator==() [2/3]
template<typename RangeType, typename ElementType UE_REQUIRES> bool operator== (TArrayView< ElementType > Lhs, RangeType && Rhs) nodiscard
Definition at line 938 of file ArrayView.h.
operator==() [3/3]
template<typename ElementType, typename SizeType, typename OtherElementType, typename OtherSizeType> bool operator== (TArrayView< ElementType, SizeType > , TArrayView< OtherElementType, OtherSizeType >) delete
Variable Documentation
TIsTArrayView_V
template<typename T> bool TIsTArrayView_V = false constexpr
Definition at line 93 of file ArrayView.h.
TIsTArrayView_V< const TArrayView< InElementType, InSizeType > >
template<typename InElementType, typename InSizeType> bool TIsTArrayView_V< const TArrayView< InElementType, InSizeType > > = true constexpr
Definition at line 96 of file ArrayView.h.
TIsTArrayView_V< const volatile TArrayView< InElementType, InSizeType > >
template<typename InElementType, typename InSizeType> bool TIsTArrayView_V< const volatile TArrayView< InElementType, InSizeType > > = true constexpr
Definition at line 97 of file ArrayView.h.
TIsTArrayView_V< TArrayView< InElementType, InSizeType > >
template<typename InElementType, typename InSizeType> bool TIsTArrayView_V< TArrayView< InElementType, InSizeType > > = true constexpr
Definition at line 94 of file ArrayView.h.
TIsTArrayView_V< volatile TArrayView< InElementType, InSizeType > >
template<typename InElementType, typename InSizeType> bool TIsTArrayView_V< volatile TArrayView< InElementType, InSizeType > > = true constexpr
Definition at line 95 of file ArrayView.h.