Unreal Engine 5.6 C++ API: UBasicPointSetComponentBase Class Reference
UBasicPointSetComponentBase Class Reference
UBasic2DPointSetComponent and UBasic3DPointSetComponent are components that draw a set of points as small squares.
#include "BasicPointSetComponent.h"
Public Member Functions
UBasicPointSetComponentBase ()
void ClearComponent ()
Clears the component state and marks component as dirty.
void SetColor (const FColor InColor)
Set per point material Color parameter that is uniform for all points.
void SetPointMaterial (UMaterialInterface *InPointMaterial)
Specify material that handles points.
void SetPointSetParameters (FColor InColor, float InSize, float InDepthBias)
Set per point material parameters that are uniform for all points.
void SetPointSize (const float InSize)
Set per point material Size parameter tat is uniform for all points.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Protected Member Functions
virtual int32 GetNumMaterials () const override
template<typename CalcPointBoxFn>
FBoxSphereBounds UpdateComponentBounds (const FTransform &LocalToWorld, bool bPointsDirty, CalcPointBoxFn &&CalcPointBox) const
Update component bounds using a provided function that determines the box around all point positions.
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes
bool bBoundsDirty = true
FBoxSphereBounds Bounds
FColor Color
float DepthBias = 0.0f
TObjectPtr< const UMaterialInterface > PointMaterial
float Size = 1.0f
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Additional Inherited Members
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Detailed Description
UBasic2DPointSetComponent and UBasic3DPointSetComponent are components that draw a set of points as small squares.
The 2D version stores XY coordinates with Z set to 0 whereas the 3D version stores XYZ coordinates. All points have the same color, size, and depth bias based on what is set via SetPointSetParameters(). The points are drawn as two triangles, i.e. a square, orthogonal to the view direction. The actual point size is calculated in the shader using a custom material.
Before inserting any points via AddElement(), the maximum number of points that will be added needs to be declared via ReserveElements(). The actual number of points that were added is available via NumElements().
To support both 2D and 3D with minimal code duplication, the point set components are composed from the UBasicPointSetComponentBase class for the component specific functionality, and an instantiation of the TBasicElementSet template class for either FVector2f or FVector3f that encapsulates all point specific functionality. The final derived classes UBasic2DPointSetComponent and UBasic3DPointSetComponent contain identical boilerplate code to facilitate calls that need to go both to the component base class and the point base class, e.g. Clear() will both mark the component as dirty and delete all points. Base class for component specific functionality independent of the type of point stored in the component.
Definition at line 30 of file BasicPointSetComponent.h.
Constructor & Destructor Documentation
UBasicPointSetComponentBase()
UBasicPointSetComponentBase::UBasicPointSetComponentBase ()
References UBasicPointSetComponentBase().
Referenced by UBasicPointSetComponentBase().
Member Function Documentation
ClearComponent()
void UBasicPointSetComponentBase::ClearComponent ()
Clears the component state and marks component as dirty.
References ClearComponent().
Referenced by UBasic2DPointSetComponent::Clear(), UBasic3DPointSetComponent::Clear(), and ClearComponent().
GetNumMaterials()
virtual int32 UBasicPointSetComponentBase::GetNumMaterials () const inline override protected virtual
Reimplemented from UMeshComponent.
Definition at line 56 of file BasicPointSetComponent.h.
References GetNumMaterials().
Referenced by GetNumMaterials().
SetColor()
void UBasicPointSetComponentBase::SetColor (const FColor InColor)
Set per point material Color parameter that is uniform for all points.
References SetColor().
Referenced by SetColor().
SetPointMaterial()
void UBasicPointSetComponentBase::SetPointMaterial (UMaterialInterface * InPointMaterial)
Specify material that handles points.
References SetPointMaterial().
Referenced by SetPointMaterial().
SetPointSetParameters()
void UBasicPointSetComponentBase::SetPointSetParameters (FColor InColor, float InSize, float InDepthBias)
Set per point material parameters that are uniform for all points.
References SetPointSetParameters().
Referenced by SetPointSetParameters().
SetPointSize()
void UBasicPointSetComponentBase::SetPointSize (const float InSize)
Set per point material Size parameter tat is uniform for all points.
References SetPointSize().
Referenced by SetPointSize().
UpdateComponentBounds()
template<typename CalcPointBoxFn> FBoxSphereBounds UBasicPointSetComponentBase::UpdateComponentBounds (const FTransform & LocalToWorld, bool bPointsDirty, CalcPointBoxFn && CalcPointBox) const inline protected
Update component bounds using a provided function that determines the box around all point positions.
This unifies how the bounds are calculated while keeping the calculation of the box around all point positions generic.
Definition at line 61 of file BasicPointSetComponent.h.
References bBoundsDirty, Bounds, Box, and Size.
Referenced by UBasic2DPointSetComponent::CalcBounds(), and UBasic3DPointSetComponent::CalcBounds().
Field Documentation
bBoundsDirty
bool UBasicPointSetComponentBase::bBoundsDirty = true mutable protected
Definition at line 95 of file BasicPointSetComponent.h.
Referenced by UpdateComponentBounds().
Bounds
FBoxSphereBounds UBasicPointSetComponentBase::Bounds mutable protected
Definition at line 92 of file BasicPointSetComponent.h.
Referenced by UpdateComponentBounds().
Color
FColor UBasicPointSetComponentBase::Color protected
Definition at line 98 of file BasicPointSetComponent.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UBasicPointSetComponentBase::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 32 of file BasicPointSetComponent.h.
DepthBias
float UBasicPointSetComponentBase::DepthBias = 0.0f protected
Definition at line 104 of file BasicPointSetComponent.h.
PointMaterial
TObjectPtr<const UMaterialInterface> UBasicPointSetComponentBase::PointMaterial protected
Definition at line 89 of file BasicPointSetComponent.h.
Size
float UBasicPointSetComponentBase::Size = 1.0f protected
Definition at line 101 of file BasicPointSetComponent.h.
Referenced by UpdateComponentBounds().
The documentation for this class was generated from the following file:
BasicPointSetComponent.h