Unreal Engine 5.6 C++ API: FBlueprintActionUiSpec Struct Reference
FBlueprintActionUiSpec Struct Reference
#include "BlueprintNodeSpawner.h"
Public Member Functions
FBlueprintActionUiSpec ()
FBlueprintActionUiSpec (const FBlueprintActionUiSpec &Other)
FBlueprintActionUiSpec (FBlueprintActionUiSpec &&Other)
~FBlueprintActionUiSpec ()
FBlueprintActionUiSpec & operator= (const FBlueprintActionUiSpec &Other)
FBlueprintActionUiSpec & operator= (FBlueprintActionUiSpec &&Other)
Data Fields
FText Category
FString DocExcerptTag
FString DocLink
FSlateIcon Icon
FLinearColor IconTint
FText Keywords
FText MenuName
FText Tooltip
Private Member Functions
void Copy (const FBlueprintActionUiSpec &Other)
void Move (FBlueprintActionUiSpec &Other)
Detailed Description
Definition at line 32 of file BlueprintNodeSpawner.h.
Constructor & Destructor Documentation
FBlueprintActionUiSpec() [1/3]
FBlueprintActionUiSpec::FBlueprintActionUiSpec () inline
Definition at line 34 of file BlueprintNodeSpawner.h.
References IconTint.
Referenced by FBlueprintActionUiSpec(), FBlueprintActionUiSpec(), Copy(), Move(), operator=(), and operator=().
FBlueprintActionUiSpec() [2/3]
FBlueprintActionUiSpec::FBlueprintActionUiSpec (FBlueprintActionUiSpec && Other) inline
Definition at line 38 of file BlueprintNodeSpawner.h.
References FBlueprintActionUiSpec(), Move, and Other.
FBlueprintActionUiSpec() [3/3]
FBlueprintActionUiSpec::FBlueprintActionUiSpec (const FBlueprintActionUiSpec & Other) inline
Definition at line 52 of file BlueprintNodeSpawner.h.
References FBlueprintActionUiSpec(), Copy, and Other.
~FBlueprintActionUiSpec()
FBlueprintActionUiSpec::~FBlueprintActionUiSpec () inline
Definition at line 66 of file BlueprintNodeSpawner.h.
Member Function Documentation
Copy()
void FBlueprintActionUiSpec::Copy (const FBlueprintActionUiSpec & Other) inline private
Definition at line 90 of file BlueprintNodeSpawner.h.
References FBlueprintActionUiSpec(), Category, DocExcerptTag, DocLink, Icon, IconTint, Keywords, MenuName, Other, and Tooltip.
Move()
void FBlueprintActionUiSpec::Move (FBlueprintActionUiSpec & Other) inline private
Definition at line 78 of file BlueprintNodeSpawner.h.
References FBlueprintActionUiSpec(), Category, DocExcerptTag, DocLink, Icon, IconTint, Keywords, MenuName, MoveTemp(), Other, and Tooltip.
operator=() [1/2]
FBlueprintActionUiSpec & FBlueprintActionUiSpec::operator= (const FBlueprintActionUiSpec & Other) inline
Definition at line 57 of file BlueprintNodeSpawner.h.
References FBlueprintActionUiSpec(), Copy, and Other.
operator=() [2/2]
FBlueprintActionUiSpec & FBlueprintActionUiSpec::operator= (FBlueprintActionUiSpec && Other) inline
Definition at line 43 of file BlueprintNodeSpawner.h.
References FBlueprintActionUiSpec(), Move, and Other.
Field Documentation
Category
FText FBlueprintActionUiSpec::Category
Definition at line 69 of file BlueprintNodeSpawner.h.
Referenced by Copy(), and Move().
DocExcerptTag
FString FBlueprintActionUiSpec::DocExcerptTag
Definition at line 75 of file BlueprintNodeSpawner.h.
Referenced by Copy(), and Move().
DocLink
FString FBlueprintActionUiSpec::DocLink
Definition at line 74 of file BlueprintNodeSpawner.h.
Referenced by Copy(), and Move().
Icon
FSlateIcon FBlueprintActionUiSpec::Icon
Definition at line 72 of file BlueprintNodeSpawner.h.
Referenced by Copy(), and Move().
IconTint
FLinearColor FBlueprintActionUiSpec::IconTint
Definition at line 73 of file BlueprintNodeSpawner.h.
Referenced by FBlueprintActionUiSpec(), Copy(), and Move().
Keywords
FText FBlueprintActionUiSpec::Keywords
Definition at line 71 of file BlueprintNodeSpawner.h.
Referenced by Copy(), and Move().
MenuName
FText FBlueprintActionUiSpec::MenuName
Definition at line 68 of file BlueprintNodeSpawner.h.
Referenced by Copy(), and Move().
Tooltip
FText FBlueprintActionUiSpec::Tooltip
Definition at line 70 of file BlueprintNodeSpawner.h.
Referenced by Copy(), and Move().
The documentation for this struct was generated from the following file:
BlueprintNodeSpawner.h