Unreal Engine 5.6 C++ API: TPatchedPtrBase< T, PtrType > Class Template Reference
TPatchedPtrBase< T, PtrType > Class Template Reference
#include "MemoryImage.h"
Public Types
using FPtrTable = TPtrTableBase<T, PtrType>
Public Member Functions
TPatchedPtrBase (T *InPtr=nullptr)
T * Get () const
T * GetChecked () const
operator T* () const
T & operator* () const
T * operator-> () const
Private Attributes
PtrType Ptr
Detailed Description
template<typename T, typename PtrType>
class TPatchedPtrBase< T, PtrType >
Definition at line 1219 of file MemoryImage.h.
Member Typedef Documentation
FPtrTable
template<typename T, typename PtrType> using TPatchedPtrBase< T, PtrType >::FPtrTable = TPtrTableBase<T, PtrType>
Definition at line 1222 of file MemoryImage.h.
Constructor & Destructor Documentation
TPatchedPtrBase()
template<typename T, typename PtrType> TPatchedPtrBase< T, PtrType >::TPatchedPtrBase (T * InPtr = nullptr) inline
Definition at line 1224 of file MemoryImage.h.
Member Function Documentation
Get()
template<typename T, typename PtrType> T * TPatchedPtrBase< T, PtrType >::Get () const inline
Definition at line 1226 of file MemoryImage.h.
Referenced by TPatchedPtrBase< T, T * >::GetChecked(), and TPatchedPtrBase< T, T * >::operator T*().
GetChecked()
template<typename T, typename PtrType> T * TPatchedPtrBase< T, PtrType >::GetChecked () const inline
Definition at line 1231 of file MemoryImage.h.
Referenced by TPatchedPtrBase< T, T * >::operator*(), and TPatchedPtrBase< T, T * >::operator->().
operator T*()
template<typename T, typename PtrType> TPatchedPtrBase< T, PtrType >::operator T* () const inline
Definition at line 1234 of file MemoryImage.h.
operator*()
template<typename T, typename PtrType> T & TPatchedPtrBase< T, PtrType >::operator* () const inline
Definition at line 1233 of file MemoryImage.h.
operator->()
template<typename T, typename PtrType> T * TPatchedPtrBase< T, PtrType >::operator-> () const inline
Definition at line 1232 of file MemoryImage.h.
Field Documentation
Ptr
template<typename T, typename PtrType> PtrType TPatchedPtrBase< T, PtrType >::Ptr private
Definition at line 1238 of file MemoryImage.h.
The documentation for this class was generated from the following file:
MemoryImage.h