Unreal Engine 5.6 C++ API: UE::SVT::FTextureRenderResources Class Reference
UE::SVT::FTextureRenderResources Class Reference
#include "SparseVolumeTexture.h"
Public Member Functions
int32 GetFrameIndex () const
const FHeader & GetHeader () const
int32 GetNumLogicalMipLevels () const
void GetPackedUniforms (FUintVector4 &OutPacked0, FUintVector4 &OutPacked1) const
FRHITextureReference * GetPageTableTexture () const
FRHITextureReference * GetPhysicalTileDataATexture () const
FRHITextureReference * GetPhysicalTileDataBTexture () const
FIntVector3 GetTileDataTextureResolution () const
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void SetGlobalVolumeResolution_GameThread (const FIntVector3 &GlobalVolumeResolution)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Attributes
int32 FrameIndex = INDEX_NONE
FIntVector3 GlobalVolumeResolution = FIntVector3::ZeroValue
FHeader Header
int32 NumLogicalMipLevels = 0
FTextureReferenceRHIRef PageTableTextureReferenceRHI
FTextureReferenceRHIRef PhysicalTileDataATextureReferenceRHI
FTextureReferenceRHIRef PhysicalTileDataBTextureReferenceRHI
FIntVector3 TileDataTextureResolution = FIntVector3::ZeroValue
Friends
class FStreamingManager
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 260 of file SparseVolumeTexture.h.
Member Function Documentation
GetFrameIndex()
int32 UE::SVT::FTextureRenderResources::GetFrameIndex () const inline
Definition at line 266 of file SparseVolumeTexture.h.
References check, FrameIndex, and IsInParallelRenderingThread().
GetHeader()
const FHeader & UE::SVT::FTextureRenderResources::GetHeader () const inline
Definition at line 264 of file SparseVolumeTexture.h.
References check, Header, and IsInParallelRenderingThread().
GetNumLogicalMipLevels()
int32 UE::SVT::FTextureRenderResources::GetNumLogicalMipLevels () const inline
Definition at line 267 of file SparseVolumeTexture.h.
References check, IsInParallelRenderingThread(), and NumLogicalMipLevels.
GetPackedUniforms()
void UE::SVT::FTextureRenderResources::GetPackedUniforms (FUintVector4 & OutPacked0, FUintVector4 & OutPacked1) const
GetPageTableTexture()
FRHITextureReference * UE::SVT::FTextureRenderResources::GetPageTableTexture () const inline
Definition at line 268 of file SparseVolumeTexture.h.
References check, IsInParallelRenderingThread(), and PageTableTextureReferenceRHI.
GetPhysicalTileDataATexture()
FRHITextureReference * UE::SVT::FTextureRenderResources::GetPhysicalTileDataATexture () const inline
Definition at line 269 of file SparseVolumeTexture.h.
References check, IsInParallelRenderingThread(), and PhysicalTileDataATextureReferenceRHI.
GetPhysicalTileDataBTexture()
FRHITextureReference * UE::SVT::FTextureRenderResources::GetPhysicalTileDataBTexture () const inline
Definition at line 270 of file SparseVolumeTexture.h.
References check, IsInParallelRenderingThread(), and PhysicalTileDataBTextureReferenceRHI.
GetTileDataTextureResolution()
FIntVector3 UE::SVT::FTextureRenderResources::GetTileDataTextureResolution () const inline
Definition at line 265 of file SparseVolumeTexture.h.
References check, IsInParallelRenderingThread(), and TileDataTextureResolution.
InitRHI()
virtual void UE::SVT::FTextureRenderResources::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseRHI()
virtual void UE::SVT::FTextureRenderResources::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
SetGlobalVolumeResolution_GameThread()
void UE::SVT::FTextureRenderResources::SetGlobalVolumeResolution_GameThread (const FIntVector3 & GlobalVolumeResolution)
References GlobalVolumeResolution.
Friends And Related Symbol Documentation
FStreamingManager
friend class FStreamingManager friend
Definition at line 262 of file SparseVolumeTexture.h.
References FStreamingManager.
Referenced by FStreamingManager.
Field Documentation
FrameIndex
int32 UE::SVT::FTextureRenderResources::FrameIndex = INDEX_NONE private
Definition at line 284 of file SparseVolumeTexture.h.
Referenced by GetFrameIndex().
GlobalVolumeResolution
FIntVector3 UE::SVT::FTextureRenderResources::GlobalVolumeResolution = FIntVector3::ZeroValue private
Definition at line 282 of file SparseVolumeTexture.h.
Referenced by SetGlobalVolumeResolution_GameThread().
Header
FHeader UE::SVT::FTextureRenderResources::Header private
Definition at line 281 of file SparseVolumeTexture.h.
Referenced by GetHeader().
NumLogicalMipLevels
int32 UE::SVT::FTextureRenderResources::NumLogicalMipLevels = 0 private
Definition at line 285 of file SparseVolumeTexture.h.
Referenced by GetNumLogicalMipLevels().
PageTableTextureReferenceRHI
FTextureReferenceRHIRef UE::SVT::FTextureRenderResources::PageTableTextureReferenceRHI private
Definition at line 286 of file SparseVolumeTexture.h.
Referenced by GetPageTableTexture().
PhysicalTileDataATextureReferenceRHI
FTextureReferenceRHIRef UE::SVT::FTextureRenderResources::PhysicalTileDataATextureReferenceRHI private
Definition at line 287 of file SparseVolumeTexture.h.
Referenced by GetPhysicalTileDataATexture().
PhysicalTileDataBTextureReferenceRHI
FTextureReferenceRHIRef UE::SVT::FTextureRenderResources::PhysicalTileDataBTextureReferenceRHI private
Definition at line 288 of file SparseVolumeTexture.h.
Referenced by GetPhysicalTileDataBTexture().
TileDataTextureResolution
FIntVector3 UE::SVT::FTextureRenderResources::TileDataTextureResolution = FIntVector3::ZeroValue private
Definition at line 283 of file SparseVolumeTexture.h.
Referenced by GetTileDataTextureResolution().
The documentation for this class was generated from the following file:
SparseVolumeTexture.h