Unreal Engine 5.6 C++ API: FGameDragDropOperation Class Reference
FGameDragDropOperation Class Reference
#include "DragAndDrop.h"
Public Member Functions
FGameDragDropOperation ()
Default constructor.
virtual FVector2D GetDecoratorPosition () const override
Gets the desired position of the decorator in absolute space.
virtual bool IsOfTypeImpl (const FString &Type) const override
Checks whether this drag and drop operation can cast safely to the specified type.
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const
Gets the widget that will serve as the decorator unless overridden.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static const FString & GetTypeId ()
Protected Attributes
FVector2D DecoratorPosition
The absolute position of the decorator.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Additional Inherited Members
Protected Member Functions inherited from FDragDropOperation
virtual void Construct ()
Constructs the window and widget if applicable.
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 257 of file DragAndDrop.h.
Constructor & Destructor Documentation
FGameDragDropOperation()
FGameDragDropOperation::FGameDragDropOperation ()
Default constructor.
References FGameDragDropOperation().
Referenced by FGameDragDropOperation(), and GetTypeId().
Member Function Documentation
GetDecoratorPosition()
virtual FVector2D FGameDragDropOperation::GetDecoratorPosition () const override virtual
Gets the desired position of the decorator in absolute space.
Reimplemented from FDragDropOperation.
References GetDecoratorPosition().
Referenced by GetDecoratorPosition().
GetTypeId()
const FString & FGameDragDropOperation::GetTypeId () inline static
Definition at line 260 of file DragAndDrop.h.
References FDragDropOperation::FDragDropOperation(), and FGameDragDropOperation().
IsOfTypeImpl()
virtual bool FGameDragDropOperation::IsOfTypeImpl (const FString & Type) const inline override virtual
Checks whether this drag and drop operation can cast safely to the specified type.
Reimplemented from FDragDropOperation.
Definition at line 260 of file DragAndDrop.h.
Field Documentation
DecoratorPosition
FVector2D FGameDragDropOperation::DecoratorPosition protected
The absolute position of the decorator.
Definition at line 271 of file DragAndDrop.h.
The documentation for this class was generated from the following file:
DragAndDrop.h