Unreal Engine 5.6 C++ API: FBulkData::FAllocatedPtr Struct Reference
FBulkData::FAllocatedPtr Struct Reference
Data Structures
union FAllocation
Public Member Functions
FAllocatedPtr ()=default
~FAllocatedPtr ()=default
void Free (FBulkData *Owner)
void * GetAllocationForWrite (const FBulkData *Owner) const
const void * GetAllocationReadOnly (const FBulkData *Owner) const
bool IsLoaded () const
void * ReallocateData (FBulkData *Owner, int64 SizeInBytes)
void SetData (FBulkData *Owner, void *Buffer)
void SetMemoryMappedData (FBulkData *Owner, IMappedFileHandle *MappedHandle, IMappedFileRegion *MappedRegion)
FOwnedBulkDataPtr * StealFileMapping (FBulkData *Owner)
void Swap (FBulkData *Owner, void **DstBuffer)
Private Attributes
FAllocation Allocation { nullptr }
Detailed Description
Definition at line 471 of file BulkData.h.
Constructor & Destructor Documentation
FAllocatedPtr()
FBulkData::FAllocatedPtr::FAllocatedPtr () default
~FAllocatedPtr()
FBulkData::FAllocatedPtr::~FAllocatedPtr () default
Member Function Documentation
Free()
void FBulkData::FAllocatedPtr::Free (FBulkData * Owner)
References FBulkData::FBulkData(), and Owner.
GetAllocationForWrite()
void * FBulkData::FAllocatedPtr::GetAllocationForWrite (const FBulkData * Owner) const
References FBulkData::FBulkData(), and Owner.
GetAllocationReadOnly()
const void * FBulkData::FAllocatedPtr::GetAllocationReadOnly (const FBulkData * Owner) const
References FBulkData::FBulkData(), and Owner.
IsLoaded()
bool FBulkData::FAllocatedPtr::IsLoaded () const inline
Definition at line 476 of file BulkData.h.
References Allocation.
ReallocateData()
void * FBulkData::FAllocatedPtr::ReallocateData (FBulkData * Owner, int64 SizeInBytes)
References FBulkData::FBulkData(), and Owner.
SetData()
void FBulkData::FAllocatedPtr::SetData (FBulkData * Owner, void * Buffer)
References FBulkData::FBulkData(), Buffer, and Owner.
SetMemoryMappedData()
void FBulkData::FAllocatedPtr::SetMemoryMappedData (FBulkData * Owner, IMappedFileHandle * MappedHandle, IMappedFileRegion * MappedRegion)
References FBulkData::FBulkData(), and Owner.
StealFileMapping()
FOwnedBulkDataPtr * FBulkData::FAllocatedPtr::StealFileMapping (FBulkData * Owner)
References FBulkData::FBulkData(), and Owner.
Swap()
void FBulkData::FAllocatedPtr::Swap (FBulkData * Owner, void ** DstBuffer)
References FBulkData::FBulkData(), and Owner.
Field Documentation
Allocation
FAllocation FBulkData::FAllocatedPtr::Allocation { nullptr } private
Definition at line 504 of file BulkData.h.
Referenced by IsLoaded().
The documentation for this struct was generated from the following file:
BulkData.h