Unreal Engine 5.6 C++ API: FMallocDebug Class Reference
FMallocDebug Class Reference
#include "MallocDebug.h"
Data Structures
struct FMemDebug
Public Member Functions
FMallocDebug ()
virtual void DumpAllocatorStats (FOutputDevice &Ar) override
Dumps details about all allocations to an output device.
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar) override
Exec handler.
virtual void Free (void *InPtr) override
Free.
virtual bool GetAllocationSize (void *Original, SIZE_T &SizeOut) override
If possible determine the size of the memory allocated at the given address.
virtual const TCHAR * GetDescriptiveName () override
Gets descriptive name for logging purposes.
virtual void * Malloc (SIZE_T Size, uint32 Alignment) override
Malloc.
virtual void * Realloc (void *InPtr, SIZE_T NewSize, uint32 Alignment) override
Realloc.
virtual bool ValidateHeap () override
Validates the allocator's heap.
Public Member Functions inherited from FMalloc
virtual void ClearAndDisableTLSCachesOnCurrentThread ()
Clears the TLS caches on the current thread and disables any future caching.
virtual void GetAllocatorStats (FGenericMemoryStats &out_Stats)
Writes allocator stats from the last update into the specified destination.
virtual uint64 GetImmediatelyFreeableCachedMemorySize () const
Returns the amount of free memory cached by the allocator that can be returned to the system in case of a memory shortage.
virtual uint64 GetTotalFreeCachedMemorySize () const
Returns the amount of total free memory cached by the allocator.
virtual void InitializeStatsMetadata ()
Initializes stats metadata.
virtual bool IsInternallyThreadSafe () const
Returns if the allocator is guaranteed to be thread-safe and therefore doesn't need a unnecessary thread-safety wrapper around it.
virtual void * MallocZeroed (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
Malloc zeroed memory.
virtual void MarkTLSCachesAsUnusedOnCurrentThread ()
Mark TLS caches for current thread as unused.
virtual void MarkTLSCachesAsUsedOnCurrentThread ()
Mark TLS caches for the current thread as used.
virtual void OnMallocInitialized ()
Notifies the malloc implementation that initialization of all allocators in GMalloc is complete, so it's safe to initialize any extra features that require "regular" allocations.
virtual void OnPostFork ()
Notifies the malloc implementation that the process has forked so we can try and avoid dirtying pre-fork pages.
virtual void OnPreFork ()
Notifies the malloc implementation that the process is about to fork.
virtual SIZE_T QuantizeSize (SIZE_T Count, uint32 Alignment)
For some allocators this will return the actual size that should be requested to eliminate internal fragmentation.
virtual void SetupTLSCachesOnCurrentThread ()
Set up TLS caches on the current thread.
virtual void Trim (bool bTrimThreadCaches)
Releases as much memory as possible.
virtual void * TryMalloc (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryMalloc - like Malloc(), but may return a nullptr result if the allocation request cannot be satisfied.
virtual void * TryMallocZeroed (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryMalloc - like MallocZeroed(), but may return a nullptr result if the allocation request cannot be satisfied.
virtual void * TryRealloc (void *Original, SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryRealloc - like Realloc(), but may return a nullptr if the allocation request cannot be satisfied.
virtual void UpdateStats ()
Called once per frame, gathers and sets all memory allocator statistics into the corresponding stats.
Public Member Functions inherited from FUseSystemMallocForNew
void operator delete (void *Ptr)
Overloaded delete operator using the system allocator.
void operator delete[] (void *Ptr)
Overloaded array delete operator using the system allocator.
void * operator new (size_t Size)
Overloaded new operator using the system allocator.
void * operator new[] (size_t Size)
Overloaded array new operator using the system allocator.
Public Member Functions inherited from FExec
virtual ~FExec ()
Private Types
enum { MEM_Recent = 5000 }
enum { ALLOCATION_ALIGNMENT = 16 }
enum { MEM_WipeTag = 0xcd }
enum { MEM_AgeSlice = 100 }
enum { MEM_SizeMax = 128 }
enum { MEM_Tag = 0xfe }
enum { MEM_PreTag = 0xf0ed1cee }
enum { MEM_PostTag = 0xdeadf00f }
enum { MEM_AgeMax = 80 }
Private Attributes
FMemDebug * GFirstDebug
SIZE_T TotalAllocationSize
Total size of allocations.
SIZE_T TotalWasteSize
Total size of allocation overhead.
Static Private Attributes
static constexpr uint32 AllocatorOverhead = sizeof(FMemDebug) + sizeof(FMemDebug*) + sizeof(int32) + ALLOCATION_ALIGNMENT + sizeof(int32)
Additional Inherited Members
Static Public Attributes inherited from FMalloc
static TAtomic< uint64 > MaxSingleAlloc
Limits the maximum single allocation, to this many bytes, for debugging.
Protected Member Functions inherited from FExec
virtual bool Exec_Dev (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in non-shipping targets.
virtual bool Exec_Editor (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in editor.
virtual bool Exec_Runtime (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is called on all targets where UE_ALLOW_EXEC_COMMANDS is true.
Detailed Description
Definition at line 12 of file MallocDebug.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
MEM_Recent
Definition at line 25 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
ALLOCATION_ALIGNMENT
Definition at line 21 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
MEM_WipeTag
Definition at line 18 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
MEM_AgeSlice
Definition at line 27 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
MEM_SizeMax
Definition at line 24 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
MEM_Tag
Definition at line 17 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
MEM_PreTag
Definition at line 15 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
MEM_PostTag
Definition at line 16 of file MallocDebug.h.
anonymous enum
anonymous enum private
Enumerator
MEM_AgeMax
Definition at line 26 of file MallocDebug.h.
Constructor & Destructor Documentation
FMallocDebug()
FMallocDebug::FMallocDebug () inline
Definition at line 51 of file MallocDebug.h.
References GFirstDebug, TotalAllocationSize, and TotalWasteSize.
Member Function Documentation
DumpAllocatorStats()
virtual void FMallocDebug::DumpAllocatorStats (FOutputDevice & Ar) inline override virtual
Dumps details about all allocations to an output device.
Parameters
Ar [in] Output device
Reimplemented from FMalloc.
Definition at line 174 of file MallocDebug.h.
References Ar, Count, GFirstDebug, TEXT, TotalAllocationSize, and TotalWasteSize.
Exec()
virtual bool FMallocDebug::Exec (UWorld * InWorld, const TCHAR * Cmd, FOutputDevice & Ar) inline override virtual
Exec handler.
Parameters
InWorld World context
Cmd Command to parse
Ar Output device to log to
Returns
true if command was handled, false otherwise
Reimplemented from FExec.
Definition at line 214 of file MallocDebug.h.
References Ar, and Cmd.
Free()
virtual void FMallocDebug::Free (void * InPtr) inline override virtual
Free.
Implements FMalloc.
Definition at line 116 of file MallocDebug.h.
References AllocatorOverhead, check, GIsCriticalError, MEM_PostTag, MEM_PreTag, MEM_WipeTag, FMemory::Memset(), FMallocDebug::FMemDebug::Next, FMallocDebug::FMemDebug::PreTag, FMallocDebug::FMemDebug::PrevLink, FMallocDebug::FMemDebug::RefCount, FMallocDebug::FMemDebug::Size, TotalAllocationSize, and TotalWasteSize.
Referenced by Realloc().
GetAllocationSize()
virtual bool FMallocDebug::GetAllocationSize (void * Original, SIZE_T & SizeOut) inline override virtual
If possible determine the size of the memory allocated at the given address.
Parameters
Original - Pointer to memory we are checking the size of
SizeOut - If possible, this value is set to the size of the passed in pointer
Returns
true if succeeded
Reimplemented from FMalloc.
Definition at line 154 of file MallocDebug.h.
References FMallocDebug::FMemDebug::Size.
GetDescriptiveName()
virtual const TCHAR * FMallocDebug::GetDescriptiveName () inline override virtual
Gets descriptive name for logging purposes.
Returns
pointer to human-readable malloc name
Reimplemented from FMalloc.
Definition at line 219 of file MallocDebug.h.
References TEXT.
Malloc()
virtual void * FMallocDebug::Malloc (SIZE_T Size, uint32 Alignment) inline override virtual
Malloc.
Implements FMalloc.
Definition at line 60 of file MallocDebug.h.
References Align, ALLOCATION_ALIGNMENT, AllocatorOverhead, check, GFirstDebug, GIsCriticalError, MEM_PostTag, MEM_PreTag, MEM_Tag, FMemory::Memset(), FMallocDebug::FMemDebug::Next, FMallocDebug::FMemDebug::PreTag, FMallocDebug::FMemDebug::PrevLink, FMallocDebug::FMemDebug::RefCount, FMallocDebug::FMemDebug::Size, TotalAllocationSize, TotalWasteSize, and TSequenceHistory< HistorySize >::Size.
Referenced by Realloc().
Realloc()
virtual void * FMallocDebug::Realloc (void * InPtr, SIZE_T NewSize, uint32 Alignment) inline override virtual
Realloc.
Implements FMalloc.
Definition at line 91 of file MallocDebug.h.
References check, Free(), GIsCriticalError, Malloc(), FMemory::Memcpy(), FMath::Min, FMallocDebug::FMemDebug::RefCount, and FMallocDebug::FMemDebug::Size.
ValidateHeap()
virtual bool FMallocDebug::ValidateHeap () inline override virtual
Validates the allocator's heap.
Reimplemented from FMalloc.
Definition at line 197 of file MallocDebug.h.
References check, GFirstDebug, and GIsCriticalError.
Field Documentation
AllocatorOverhead
uint32 FMallocDebug::AllocatorOverhead = sizeof(FMemDebug) + sizeof(FMemDebug*) + sizeof(int32) + ALLOCATION_ALIGNMENT + sizeof(int32) static constexpr private
Definition at line 47 of file MallocDebug.h.
Referenced by Free(), and Malloc().
GFirstDebug
FMemDebug* FMallocDebug::GFirstDebug private
Definition at line 40 of file MallocDebug.h.
Referenced by FMallocDebug(), DumpAllocatorStats(), Malloc(), and ValidateHeap().
TotalAllocationSize
SIZE_T FMallocDebug::TotalAllocationSize private
Total size of allocations.
Definition at line 43 of file MallocDebug.h.
Referenced by FMallocDebug(), DumpAllocatorStats(), Free(), and Malloc().
TotalWasteSize
SIZE_T FMallocDebug::TotalWasteSize private
Total size of allocation overhead.
Definition at line 45 of file MallocDebug.h.
Referenced by FMallocDebug(), DumpAllocatorStats(), Free(), and Malloc().
The documentation for this class was generated from the following file:
MallocDebug.h