Unreal Engine 5.6 C++ API: FParticlePerfStats_GPU Struct Reference
FParticlePerfStats_GPU Struct Reference
Stats gathered from the GPU.
#include "ParticlePerfStats.h"
Public Member Functions
FParticlePerfStats_GPU ()
FORCEINLINE uint64 GetPerInstanceAvgMicroseconds () const
FORCEINLINE uint64 GetTotalMicroseconds () const
FParticlePerfStats_GPU & operator+= (FParticlePerfStats_GPU &Other)
FORCEINLINE void Reset ()
Data Fields
uint64 NumInstances = 0
uint64 TotalMicroseconds = 0
Detailed Description
Stats gathered from the GPU.
Definition at line 147 of file ParticlePerfStats.h.
Constructor & Destructor Documentation
FParticlePerfStats_GPU()
FParticlePerfStats_GPU::FParticlePerfStats_GPU () inline
Definition at line 155 of file ParticlePerfStats.h.
References Reset().
Referenced by operator+=().
Member Function Documentation
GetPerInstanceAvgMicroseconds()
FORCEINLINE uint64 FParticlePerfStats_GPU::GetPerInstanceAvgMicroseconds () const inline
Definition at line 153 of file ParticlePerfStats.h.
References FORCEINLINE, GetTotalMicroseconds(), and NumInstances.
GetTotalMicroseconds()
FORCEINLINE uint64 FParticlePerfStats_GPU::GetTotalMicroseconds () const inline
Definition at line 152 of file ParticlePerfStats.h.
References FORCEINLINE, and TotalMicroseconds.
Referenced by GetPerInstanceAvgMicroseconds().
operator+=()
FParticlePerfStats_GPU & FParticlePerfStats_GPU::operator+= (FParticlePerfStats_GPU & Other) inline
Definition at line 162 of file ParticlePerfStats.h.
References FParticlePerfStats_GPU(), NumInstances, Other, and TotalMicroseconds.
Reset()
FORCEINLINE void FParticlePerfStats_GPU::Reset () inline
Definition at line 156 of file ParticlePerfStats.h.
References FORCEINLINE, NumInstances, and TotalMicroseconds.
Referenced by FParticlePerfStats_GPU().
Field Documentation
NumInstances
uint64 FParticlePerfStats_GPU::NumInstances = 0
Definition at line 149 of file ParticlePerfStats.h.
Referenced by GetPerInstanceAvgMicroseconds(), operator+=(), and Reset().
TotalMicroseconds
uint64 FParticlePerfStats_GPU::TotalMicroseconds = 0
Definition at line 150 of file ParticlePerfStats.h.
Referenced by GetTotalMicroseconds(), operator+=(), and Reset().
The documentation for this struct was generated from the following file:
ParticlePerfStats.h