Unreal Engine 5.6 C++ API: UAbilitySystemComponent Class Reference
UAbilitySystemComponent Class Reference abstract
#include "AbilitySystemComponent.h"
Data Structures
struct FAbilityListLockActiveChange
struct FAbilitySystemComponentDebugInfo
struct FPendingAbilityInfo
A pending activation that cannot be activated yet, will be rechecked at a later point.
Public Member Functions
GAMEPLAYABILITIES_API FSimpleMulticastDelegate & AbilityReplicatedEventDelegate (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Returns Generic Replicated Event for a given Ability/PredictionKey pair.
virtual GAMEPLAYABILITIES_API void AbilitySpecInputPressed (FGameplayAbilitySpec &Spec)
Called on local player always.
virtual GAMEPLAYABILITIES_API void AbilitySpecInputReleased (FGameplayAbilitySpec &Spec)
Called on local player always.
GAMEPLAYABILITIES_API FSimpleMulticastDelegate & AbilityTargetDataCancelledDelegate (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Returns TargetData Cancelled delegate for a given Ability/PredictionKey pair.
GAMEPLAYABILITIES_API FAbilityTargetDataSetDelegate & AbilityTargetDataSetDelegate (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Returns TargetDataSet delegate for a given Ability/PredictionKey pair.
virtual GAMEPLAYABILITIES_API void BeginPlay () override
Begins Play for the component.
GAMEPLAYABILITIES_API void CacheIsNetSimulated ()
Caches the flags that indicate whether this component has network authority.
GAMEPLAYABILITIES_API void CallAllReplicatedDelegatesIfSet (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Calls any Replicated delegates that have been sent (TargetData or Generic Replicated Events).
GAMEPLAYABILITIES_API bool CallOrAddReplicatedDelegate (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, FSimpleMulticastDelegate::FDelegate Delegate)
Calls passed in delegate if the Client Event has already been sent.
GAMEPLAYABILITIES_API bool CallReplicatedEventDelegateIfSet (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Calls a given Generic Replicated Event delegate if the event has already been sent.
GAMEPLAYABILITIES_API bool CallReplicatedTargetDataDelegatesIfSet (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Calls the TargetData Confirm/Cancel events if they have been sent.
virtual GAMEPLAYABILITIES_API void CancelAbilityTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Cancels the ability target data and calls callbacks.
virtual GAMEPLAYABILITIES_API void ClearActorInfo ()
This is called when the actor that is initialized to this system dies, this will clear that actor from this system and FGameplayAbilityActorInfo.
virtual GAMEPLAYABILITIES_API void ConfirmAbilityTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, const FGameplayAbilityTargetDataHandle &TargetData, const FGameplayTag &ApplicationTag)
Sets the current target data and calls applicable callbacks.
GAMEPLAYABILITIES_API void ConsumeAllReplicatedData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Deletes all cached ability client data (Was: ConsumeAbilityTargetData)
GAMEPLAYABILITIES_API void ConsumeClientReplicatedTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Consumes cached TargetData from client (only TargetData)
GAMEPLAYABILITIES_API void ConsumeGenericReplicatedEvent (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Consumes the given Generic Replicated Event (unsets it).
virtual GAMEPLAYABILITIES_API void ForceReplication () override
Force owning actor to update it's replication, to make sure that gameplay cues get sent down quickly.
GAMEPLAYABILITIES_API AActor * GetAvatarActor () const
Returns the avatar actor for this component.
AActor * GetAvatarActor_Direct () const
virtual GAMEPLAYABILITIES_API AActor * GetGameplayTaskAvatar (const UGameplayTask *Task) const override
Returns avatar actor to be used for a specific task, normally GetAvatarActor.
AActor * GetOwnerActor () const
GAMEPLAYABILITIES_API FAbilityReplicatedData GetReplicatedDataOfGenericReplicatedEvent (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Gets replicated data of the given Generic Replicated Event.
virtual GAMEPLAYABILITIES_API bool GetShouldTick () const override
retrieves information whether this component should be ticking taken current activity into consideration
virtual GAMEPLAYABILITIES_API void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &Objs) override
Returns a list of sub-objects that have stable names for networking.
virtual GAMEPLAYABILITIES_API void InitAbilityActorInfo (AActor *InOwnerActor, AActor *InAvatarActor)
Initialized the Abilities' ActorInfo - the structure that holds information about who we are acting on and who controls us.
virtual GAMEPLAYABILITIES_API void InitializeComponent () override
Initializes the component.
UFUNCTION() GAMEPLAYABILITIES_API void ServerSetReplicatedEvent(EAbilityGenericReplicatedEvent UFUNCTION() GAMEPLAYABILITIES_API void ServerSetReplicatedEventWithPayload(EAbilityGenericReplicatedEvent UFUNCTION() GAMEPLAYABILITIES_API void ClientSetReplicatedEvent(EAbilityGenericReplicatedEvent GAMEPLAYABILITIES_API bool InvokeReplicatedEvent (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, FPredictionKey CurrentPredictionKey=FPredictionKey())
Replicates the Generic Replicated Event to the server.
GAMEPLAYABILITIES_API bool InvokeReplicatedEventWithPayload (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, FPredictionKey CurrentPredictionKey, FVector_NetQuantize100 VectorPayload)
Calls local callbacks that are registered with the given Generic Replicated Event.
virtual GAMEPLAYABILITIES_API void OnComponentDestroyed (bool bDestroyingHierarchy) override
Called when a component is destroyed.
virtual void OnPlayerControllerSet ()
called when the ASC's AbilityActorInfo has a PlayerController set.
virtual GAMEPLAYABILITIES_API void OnRegister () override
Called when a component is registered, after Scene is set, but before CreateRenderState_Concurrent or OnCreatePhysicsState are called.
virtual GAMEPLAYABILITIES_API void OnUnregister () override
Called when a component is unregistered.
virtual GAMEPLAYABILITIES_API void PostNetReceive () override
Called right after receiving a bunch.
virtual GAMEPLAYABILITIES_API void PreNetReceive () override
Called right before receiving a bunch.
virtual GAMEPLAYABILITIES_API void ReadyForReplication () override
ReadyForReplication gets called on replicated components when their owning actor is officially ready for replication.
GAMEPLAYABILITIES_API void RefreshAbilityActorInfo ()
This will refresh the Ability's ActorInfo structure based on the current ActorInfo.
virtual GAMEPLAYABILITIES_API bool ReplicateSubobjects (class UActorChannel *Channel, class FOutBunch *Bunch, FReplicationFlags *RepFlags) override
Allows a component to replicate other subobject on the actor.
GAMEPLAYABILITIES_API void SetAvatarActor (AActor *InAvatarActor)
Changes the avatar actor, leaves the owner actor the same.
GAMEPLAYABILITIES_API void SetAvatarActor_Direct (AActor *NewAvatarActor)
GAMEPLAYABILITIES_API void SetOwnerActor (AActor *NewOwnerActor)
virtual GAMEPLAYABILITIES_API void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
Function called every frame on this ActorComponent.
UFUNCTION () GAMEPLAYABILITIES_API void OnAvatarActorDestroyed(AActor *InActor)
UFUNCTION () GAMEPLAYABILITIES_API void OnOwnerActorDestroyed(AActor *InActor)
UFUNCTION () GAMEPLAYABILITIES_API void OnRep_OwningActor()
UFUNCTION () GAMEPLAYABILITIES_API void OnSpawnedAttributesEndPlayed(AActor *InActor
UFUNCTION () GAMEPLAYABILITIES_API void ServerSetInputPressed(FGameplayAbilitySpecHandle AbilityHandle)
Direct Input state replication.
UFUNCTION () GAMEPLAYABILITIES_API void ServerSetInputReleased(FGameplayAbilitySpecHandle AbilityHandle)
UFUNCTION () GAMEPLAYABILITIES_API void ServerSetReplicatedTargetData(FGameplayAbilitySpecHandle AbilityHandle
Replicates targeting data to the server.
UFUNCTION () GAMEPLAYABILITIES_API void ServerSetReplicatedTargetDataCancelled(FGameplayAbilitySpecHandle AbilityHandle
Replicates to the server that targeting has been cancelled.
virtual GAMEPLAYABILITIES_API void UninitializeComponent () override
Handle this component being Uninitialized.
UPROPERTY () FReplicatedPredictionKeyMap ReplicatedPredictionKeyMap
PredictionKeys, see more info in GameplayPrediction.h.
Public Member Functions inherited from UGameplayTasksComponent
GAMEPLAYTASKS_API UGameplayTasksComponent (const FObjectInitializer &ObjectInitializer)
GAMEPLAYTASKS_API void AddTaskReadyForActivation (UGameplayTask &NewTask)
processes the task and figures out if it should get triggered instantly or wait based on task's RequiredResources, Priority and ResourceOverlapPolicy
GAMEPLAYTASKS_API void EndAllResourceConsumingTasksOwnedBy (const IGameplayTaskOwnerInterface &TaskOwner)
GAMEPLAYTASKS_API bool FindAllResourceConsumingTasksOwnedBy (const IGameplayTaskOwnerInterface &TaskOwner, TArray< UGameplayTask * > &FoundTasks) const
GAMEPLAYTASKS_API UGameplayTask * FindResourceConsumingTaskByName (const FName TaskInstanceName) const
finds first resource-consuming task of given name
FORCEINLINE FGameplayResourceSet GetCurrentlyUsedResources () const
virtual AActor * GetGameplayTaskOwner (const UGameplayTask *Task) const override
virtual UGameplayTasksComponent * GetGameplayTasksComponent (const UGameplayTask &Task) const
GAMEPLAYTASKS_API GameplayTaskContainerType::TConstIterator GetKnownTaskIterator () const
GAMEPLAYTASKS_API FString GetKnownTasksDescription () const
GAMEPLAYTASKS_API GameplayTaskContainerType::TConstIterator GetPriorityQueueIterator () const
GAMEPLAYTASKS_API GameplayTaskContainerType::TConstIterator GetSimulatedTaskIterator () const
GAMEPLAYTASKS_API FString GetTasksPriorityQueueDescription () const
GAMEPLAYTASKS_API GameplayTaskContainerType::TConstIterator GetTickingTaskIterator () const
GAMEPLAYTASKS_API FString GetTickingTasksDescription () const
GAMEPLAYTASKS_API bool HasActiveTasks (UClass *TaskClass) const
virtual GAMEPLAYTASKS_API void OnGameplayTaskActivated (UGameplayTask &Task) override
Notify called after GameplayTask changes state to Active (initial activation or resuming)
virtual GAMEPLAYTASKS_API void OnGameplayTaskDeactivated (UGameplayTask &Task) override
Notify called after GameplayTask changes state from Active (finishing or pausing)
GAMEPLAYTASKS_API void RemoveResourceConsumingTask (UGameplayTask &Task)
UFUNCTION ()
UFUNCTION () GAMEPLAYTASKS_API void OnRep_SimulatedTasks(const TArray< UGameplayTask * > &PreviousSimulatedTasks)
GAMEPLAYTASKS_API void UpdateShouldTick ()
UPROPERTY () FOnClaimedResourcesChangeSignature OnClaimedResourcesChange
Public Member Functions inherited from UActorComponent
virtual void AddAssetUserData (UAssetUserData *InUserData) override
virtual UObject const * AdditionalStatObject () const
Give a readable name for this component, including asset name if applicable.
void AddReplicatedSubObject (UObject *SubObject, ELifetimeCondition NetCondition=COND_None)
Register a SubObject that will get replicated along with the actor component.
FORCEINLINE bool AllowReregistration () const
Check whether the component class allows reregistration during ReregisterAllComponents.
virtual bool AllowsAsyncPhysicsStateCreation () const
Returns whether this component allows having its physics state being created asynchronously (outside of the GameThread).
virtual bool AllowsAsyncPhysicsStateDestruction () const
Returns whether this component allows having its physics state being destroyed asynchronously (outside of the GameThread).
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift)
Called by owner actor on position shifting Component should update all relevant data structures to reflect new actor location.
virtual void AsyncPhysicsTickComponent (float DeltaTime, float SimTime)
Override this function to implement custom logic to be executed every physics step.
virtual void BeginDestroy () override
Called before destroying the object.
virtual bool CallRemoteFunction (UFunction *Function, void *Parameters, FOutParmRec *OutParms, FFrame *Stack) override
Call the actor's function remotely.
virtual bool CanEditChange (const FProperty *InProperty) const override
Called by the editor to query whether a property of this object is allowed to be modified.
bool CanEverAffectNavigation () const
Can this component potentially influence navigation.
virtual void CheckForErrors ()
Function that gets called from within Map_Check to allow this actor component to check itself for any potential errors and register them with map check dialog.
void ClearNeedEndOfFrameUpdate ()
If we belong to a world, clear the request to do a deferred update.
void ClearUCSModifiedProperties ()
Clears the component's UCS modified properties.
bool ComponentIsInLevel (const class ULevel *TestLevel) const
Returns true if this actor is contained by TestLevel.
bool ComponentIsInPersistentLevel (bool bIncludeLevelStreamingPersistent) const
See if this component is in the persistent level.
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const
Override to allow a component subclass to compute an hash for the purpose of HLOD generation.
void CreatePhysicsState (bool bAllowDeferral=false)
Create any physics engine information for this component.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMarkRenderStateDirty, UActorComponent &)
virtual void DestroyComponent (bool bPromoteChildren=false)
Unregister the component, remove it from its outer Actor's Components array and mark for pending kill.
void DestroyPhysicsState ()
Shut down any physics engine structure for this component.
void DestroyReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels to delete the replica of this subobject next time the Actor gets replicated Note it is up to the caller to delete the local object on the authority.
void DetermineUCSModifiedProperties ()
Initializes the list of properties that are modified by the UserConstructionScript.
void DoDeferredRenderUpdates_Concurrent ()
Uses the bRenderStateDirty/bRenderTransformDirty/bRenderInstancesDirty to perform any necessary work on this component.
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason)
Ends gameplay for this component.
virtual bool ForceActorNoDataLayers () const
virtual bool ForceActorNonSpatiallyLoaded () const
virtual void GetActorDescProperties (FPropertyPairsMap &PropertyPairsMap) const
Add properties to the component owner's actor desc.
virtual const TArray< UAssetUserData * > * GetAssetUserDataArray () const override
virtual UAssetUserData * GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual UObject * GetAsyncPhysicsStateObject () const override final
Returns the associated UObject for this processor.
virtual void GetComponentChildElements (TArray< FTypedElementHandle > &OutElementHandles, const bool bAllowCreate=true)
Get the logical child elements of this component, if any.
virtual bool GetComponentClassCanReplicate () const
Returns true if this type of component can ever replicate, override to disable the default behavior.
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const
Called before we throw away components during RerunConstructionScripts, to cache any data we wish to persist across that operation.
ULevel * GetComponentLevel () const
Return the ULevel that this Component is part of.
virtual TSharedPtr< SWidget > GetCustomEditorPreviewWidget ()
If this component is set up to provide a preview window in editor (see GetEditorPreviewInfo), you can use this to customize the preview (to be something other than a world viewport).
virtual TSubclassOf< class UHLODBuilder > GetCustomHLODBuilderClass () const
Return the custom HLODBuilder class that should be used to generate HLODs for components of this type.
virtual bool GetEditorPreviewInfo (float DeltaTime, FMinimalViewInfo &ViewOut)
Supplies the editor with a view specific to this component (think a view from a camera components POV, a render, etc.).
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack) override
Return the space this function should be called.
virtual TArray< UActorComponent * > GetHLODProxyComponents () const
Override to provide a custom set of components to be used in place of the current component for the HLOD generation.
FORCEINLINE bool GetIsReplicated () const
Returns whether replication is enabled or not.
uint32 GetMarkedForEndOfFrameUpdateState () const
Tracks whether the component has been added to one of the world's end of frame update lists.
uint32 GetMarkedForPreEndOfFrameSync () const
Tracks whether the component has been added to one of the world's end of frame update lists.
ENetMode GetNetMode () const
Get the network mode (dedicated server, client, standalone, etc) for this component.
template<class T>
T * GetOwner () const
Templated version of GetOwner(), will return nullptr if cast fails.
ENetRole GetOwnerRole () const
Get the network role of the Owner, or ROLE_None if there is no owner.
virtual FString GetReadableName () const
Returns a readable name for this component, including the asset name if applicable By default this appends a space plus AdditionalStatObject()
virtual ELifetimeCondition GetReplicationCondition () const
Returns the replication condition for the component.
class FSceneInterface * GetScene () const
Returns the rendering scene associated with this component.
virtual FBox GetStreamingBounds () const
virtual FBox GetStreamingBoundsEditor () const
void GetUCSModifiedProperties (TSet< const FProperty * > &ModifiedProperties) const
Returns the list of properties that are modified by the UserConstructionScript.
int32 GetUCSSerializationIndex () const
Returns the UCS serialization index.
virtual UWorld * GetWorld () const override final
Getter for the cached world pointer, will return null if the component is not actually spawned in a level.
bool HasBeenCreated () const
Indicates that OnCreatedComponent has been called, but OnDestroyedComponent has not yet.
bool HasBeenInitialized () const
Indicates that InitializeComponent has been called, but UninitializeComponent has not yet.
bool HasBegunPlay () const
Indicates that BeginPlay has been called, but EndPlay has not yet.
void InvalidateLightingCache ()
Invalidate lighting cache with default options.
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly)
Called when this actor component has moved, allowing it to discard statically cached lighting information.
bool IsAsyncCreatePhysicsStateRunning () const
Whether asynchronous physics state creation is running or not.
bool IsAsyncDestroyPhysicsStateRunning () const
Whether asynchronous physics state destruction is running or not.
virtual bool IsAsyncPhysicsStateCreated () const override final
Returns whether the physics state is created.
bool IsCreatedByConstructionScript () const
Returns true if instances of this component are created by either the user or simple construction script.
bool IsEditableWhenInherited () const
True if this component can be modified when it was inherited from a parent actor class.
virtual bool IsHLODRelevant () const
Override to specify that a component is relevant to the HLOD generation.
virtual bool IsNameStableForNetworking () const override
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsNavigationRelevant () const
Override to specify that a component is relevant to the navigation system.
bool IsNetMode (ENetMode Mode) const
Test whether net mode is the given mode.
bool IsNetSimulating () const
Returns true if we are replicating and this client is not authoritative.
bool IsNetStartupComponent () const
Returns true if this component was owned by a net startup actor during level load.
bool IsOwnerRunningUserConstructionScript () const
See if the owning Actor is currently running the UCS.
bool IsOwnerSelected () const
Returns whether the component's owner is selected in the editor.
bool IsPhysicsStateCreated () const
Returns true if the physics 'state' (e.g.
FORCEINLINE bool IsPreRegistered () const
See if this component is currently pre-registered.
FORCEINLINE bool IsPreRegistering () const
See if this component is currently pre-registering.
FORCEINLINE bool IsPreUnregistered () const
See if this component is currently pre-unregistered.
FORCEINLINE bool IsPreUnregistering () const
See if this component is currently pre-unregistering.
virtual bool IsReadyForOwnerToAutoDestroy () const
Overridable check for a component to indicate to its Owner that it should prevent the Actor from auto destroying when finished.
bool IsReadyForReplication () const
Indicates that ReadyForReplication has been called.
FORCEINLINE bool IsRegistered () const
See if this component is currently registered.
bool IsRenderInstancesDirty () const
Is this component's instance data in need of sending to the renderer?
bool IsRenderStateCreated () const
Returns true if the render 'state' (e.g.
bool IsRenderStateDirty () const
Is this component in need of its whole state being sent to the renderer?
bool IsRenderStateRecreating () const
Returns true if the render 'state' is being recreated for this component (see additional comments on variable above)
bool IsRenderTransformDirty () const
Is this component's transform in need of sending to the renderer?
bool IsReplicatedSubObjectRegistered (const UObject *SubObject) const
Tells if the object is registered to be replicated by this actor component.
virtual bool IsSelectedInEditor () const override
Test the selection state of a UObject.
virtual bool IsSupportedForNetworking () const override
IsSupportedForNetworking means an object can be referenced over the network.
bool IsUsingRegisteredSubObjectList () const
Returns if this component is replicating subobjects via the registration list or via the virtual ReplicateSubObjects method.
void MarkForNeededEndOfFrameRecreate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkForNeededEndOfFrameUpdate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkRenderDynamicDataDirty ()
Indicate that dynamic data for this component needs to be sent at the end of the frame.
void MarkRenderInstancesDirty ()
Marks the instances as dirty - changes to instance transforms/custom data will be sent to the render thread at the end of the frame.
void MarkRenderStateDirty ()
Mark the render state as dirty - will be sent to the render thread at the end of the frame.
void MarkRenderTransformDirty ()
Marks the transform as dirty - will be sent to the render thread at the end of the frame.
virtual bool Modify (bool bAlwaysMarkDirty=true) override
Note that the object will be modified.
virtual bool NeedsLoadForClient () const override
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForEditorGame () const override
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
virtual bool NeedsLoadForServer () const override
Called during saving to determine the load flags to save with the object.
virtual void OnActorEnableCollisionChanged ()
Called on each component when the Actor's bEnableCollisionChanged flag changes.
virtual void OnActorVisibilityChanged ()
Called on each component when the Actor's visibility state changes.
virtual bool OnAsyncCreatePhysicsState (const UE::FTimeout &Timeout) override
Used to create any physics engine information for this component outside of the GameThread.
virtual void OnAsyncCreatePhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is created.
virtual bool OnAsyncDestroyPhysicsState (const UE::FTimeout &Timeout) override
Used to destroy any physics engine information for this component outside of the GameThread.
virtual void OnAsyncDestroyPhysicsStateBegin_GameThread () override
Called on the GameThread before the component's physic engine information is destroyed.
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is destroyed.
virtual void OnComponentCreated ()
Called when a component is created (not loaded).
void OnCreatedFromReplication ()
void OnDestroyedFromReplication ()
virtual void OnEndOfFrameUpdateDuringTick ()
Allows components to handle an EOF update happening mid tick.
virtual void OnPreEndOfFrameSync ()
Allows components to wait on outstanding tasks prior to sending EOF update data.
virtual void PostApplyToComponent ()
Called after ApplyToComponent has run.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
This alternate version of PostEditChange is called when properties inside structs are modified.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
Called when a property on this object has been modified externally.
virtual void PostEditUndo () override
Called after applying a transaction to the object.
virtual void PostInitProperties () override
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
virtual void PostLoad () override
Do any object-specific cleanup required immediately after loading an object.
virtual void PostRename (UObject *OldOuter, const FName OldName) override
Called at the end of Rename(), but only if the rename was actually carried out.
virtual void PreEditChange (FProperty *PropertyThatWillChange) override
This is called when a property is about to be modified externally.
virtual void PreEditUndo () override
Called before applying a transaction to the object.
void PreRegisterComponentWithWorld (UWorld *InWorld)
Pre-registers a component with a specific world.
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker)
Called on the component right before replication occurs.
void PreUnregisterComponentFromWorld ()
Pre-unregisters a component from a specific world.
void RecreatePhysicsState ()
Recreate the physics state right way.
void RecreateRenderState_Concurrent ()
Recreate the render state right away.
UFUNCTION()) 1 void ReceiveEndPlay(EEndPlayReason void RegisterAllComponentTickFunctions (bool bRegister)
Blueprint implementable event for when the component ends play, generally via destruction or its Actor's EndPlay.
void RegisterComponent ()
Register this component, creating any rendering/physics state.
void RegisterComponentWithWorld (UWorld *InWorld, FRegisterComponentContext *Context=nullptr)
Registers a component with a specific world, which creates any visual/physical state.
void RemoveReplicatedSubObject (UObject *SubObject)
Unregister a SubObject to stop replicating it's properties to clients.
void RemoveUCSModifiedProperties (const TArray< FProperty * > &Properties)
Removes specified properties from the list of UCS-modified properties.
virtual void RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual bool Rename (const TCHAR *NewName=NULL, UObject *NewOuter=NULL, ERenameFlags Flags=REN_None) override
Rename this object to a unique name, or change its outer.
virtual bool RequiresGameThreadEndOfFrameRecreate () const
return true if this component requires end of frame recreates to happen from the game thread.
virtual bool RequiresGameThreadEndOfFrameUpdates () const
return true if this component requires end of frame updates to happen from the game thread.
virtual bool RequiresPreEndOfFrameSync () const
return true if this component needs to sync to tasks before end of frame updates are executed
void ReregisterComponent ()
Unregisters and immediately re-registers component.
virtual void Serialize (FArchive &Ar) override
Handles reading, writing, and reference collecting using FArchive.
void SetActiveFlag (const bool bNewIsActive)
Sets the value of bIsActive without causing other side effects to this instance.
void SetCanEverAffectNavigation (bool bRelevant)
Sets value of bCanEverAffectNavigation flag and update navigation octree if needed.
virtual void SetComponentTickEnabledAsync (bool bEnabled)
Spawns a task on GameThread that will call SetComponentTickEnabled.
void SetIsNetStartupComponent (const bool bInIsNetStartupComponent)
This should only be called by the engine in ULevel::InitializeNetworkActors to initialize bIsNetStartupComponent.
void SetNetAddressable ()
This signifies the component can be ID'd by name over the network.
virtual void SetPackageExternal (bool bExternal, bool bShouldDirty)
bool SetupActorComponentTickFunction (struct FTickFunction *TickFunction)
Set up a tick function for a component in the standard way.
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const
Returns whether PreRegisterComponentWithWorld should be called for this component when its Level is being added to the world.
virtual bool ShouldIncrementalPreUnregister () const
Returns whether PreUnregisterComponentFromWorld should be called for this component when its Level is being removed from the world.
void TearOffReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels who spawned a replica of this subobject to release ownership over it.
UFUNCTION () 1 bool ComponentHasTag(FName Tag) const
See if this component contains the supplied tag.
UFUNCTION () 1 float GetComponentTickInterval() const
Returns the tick interval for this component's primary tick function, which is the frequency in seconds at which it will be executed.
UFUNCTION () 1 virtual bool IsComponentTickEnabled() const
Returns whether this component has tick enabled or not.
UFUNCTION () 1 virtual void OnRep_IsActive()
Handles replication of active state, handles ticking by default but should be overridden as needed.
UFUNCTION () 1 virtual void SetAutoActivate(bool bNewAutoActivate)
Sets whether the component should be auto activate or not.
UFUNCTION () 1 virtual void SetComponentTickEnabled(bool bEnabled)
Set this component's tick functions to be enabled or disabled.
UFUNCTION () 1 void SetComponentTickInterval(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetComponentTickIntervalAndCooldown(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetIsReplicated(bool ShouldReplicate)
Enable or disable replication.
UFUNCTION () 1 void SetTickableWhenPaused(bool bTickableWhenPaused)
Sets whether this component can tick when paused.
UFUNCTION ()) 1 virtual void Activate(bool bReset
Activates the SceneComponent, should be overridden by native child classes.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteActor(AActor *PrerequisiteActor)
Make this component tick after PrerequisiteActor.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Make this component tick after PrerequisiteComponent.
UFUNCTION ()) 1 virtual void Deactivate()
Deactivates the SceneComponent.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteActor(AActor *PrerequisiteActor)
Remove tick dependency on PrerequisiteActor.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Remove tick dependency on PrerequisiteComponent.
UFUNCTION ()) 1 virtual void SetActive(bool bNewActive
Sets whether the component is active or not.
UFUNCTION ()) 1 virtual void ToggleActive()
Toggles the active state of the component.
UFUNCTION ()) 1 void K2_DestroyComponent(UObject *Object)
Unregister and mark for pending kill a component.
UFUNCTION ()) 1 void ReceiveAsyncPhysicsTick(float DeltaSeconds
Event called every async physics tick if bAsyncPhysicsTickEnabled is true.
UFUNCTION ()) 1 void ReceiveBeginPlay()
Blueprint implementable event for when the component is beginning play, called before its owning actor's BeginPlay or when the component is dynamically created if the Actor has already BegunPlay.
UFUNCTION ()) 1 void ReceiveTick(float DeltaSeconds)
Event called every frame if tick is enabled.
UFUNCTION ()) 1 void SetTickGroup(ETickingGroup NewTickGroup)
Changes the ticking group for this component.
UFUNCTION ()) AActor *GetOwner() const
Follow the Outer chain to get the AActor that 'Owns' this component.
UFUNCTION ()) bool IsActive() const
Returns whether the component is active or not.
UFUNCTION ()) bool IsBeingDestroyed() const
Returns whether the component is in the process of being destroyed.
void UnregisterComponent ()
Unregister this component, destroying any rendering/physics state.
virtual void UpdateComponentToWorld (EUpdateTransformFlags UpdateTransformFlags=EUpdateTransformFlags::None, ETeleportType Teleport=ETeleportType::None)
Recalculate the value of our component to world transform.
UPROPERTY () EComponentCreationMethod CreationMethod
Describes how a component instance will be created.
UPROPERTY () FActorComponentActivatedSignature OnComponentActivated
Called when the component has been activated, with parameter indicating if it was from a reset.
UPROPERTY () FActorComponentDeactivateSignature OnComponentDeactivated
Called when the component has been deactivated.
Public Member Functions inherited from UObject
void AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const
Returns whether native properties are identical to the one of the passed in component.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform)
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
virtual void BuildSubobjectMapping (UObject *OtherObject, TMap< UObject *, UObject * > &ObjectMapping) const
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
void CallAddReferencedObjects (FReferenceCollector &Collector)
Helper function to call AddReferencedObjects for this object's class.
void CallFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
Internal VM method for executing a function.
bool CallFunctionByNameWithArguments (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor, bool bForceCallWithNonExec=false)
Handle calling a function by name when executed from the console or a command line.
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain) const
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
bool CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
bool CheckDefaultSubobjects (bool bForceCheck=false) const
Checks default sub-object assumptions.
virtual void ClearAllCachedCookedPlatformData ()
Clear all cached cooked platform data.
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform)
Clears cached cooked platform data for specific platform.
virtual void CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext)
Collect any save override state.
bool ConditionalBeginDestroy ()
Called before destroying the object.
bool ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
void ConditionalPostLoad ()
PostLoad if needed.
void ConditionalPostLoadSubobjects (struct FObjectInstancingGraph *OuterInstanceGraph=NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
virtual bool ConformSparseClassDataStruct (UScriptStruct *SourceSparseClassDataStruct, void *SourceSparseClassData) const
void CookAdditionalFiles (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
TSharedPtr< ITransactionObjectAnnotation > CreateAndRestoreTransactionAnnotation (FArchive &Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetPreviewPlatform, FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
void DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
void ExecuteUbergraph (int32 EntryPoint)
Execute the ubergraph from a specific entry point.
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent)
Exports the property values for the specified object as text to the output device.
UFunction * FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
UFunction * FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
TSharedPtr< ITransactionObjectAnnotation > FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
virtual void FinishDestroy ()
Called to finish destroying the object.
virtual void GetAdditionalAssetDataObjectsForCook (FArchiveCookContext &CookContext, TArray< UObject * > &OutObjects) const
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
UObject * GetArchetype () const
Return the template this object is based on.
void GetArchetypeInstances (TArray< UObject * > &Instances)
Builds a list of objects which have this object in their archetype chain.
virtual void GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > &OutMetadata) const
Gathers a collection of asset registry tag metadata.
void GetAssetRegistryTags (FAssetData &Out) const
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
void GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData &Out) const
Gathers a list of asset registry tags for an FAssetData.
virtual const TCHAR * GetConfigOverridePlatform () const
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
FString GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
virtual FString GetDesc ()
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
FString GetDetailedInfo () const
This will return detail info about this specific object.
virtual FName GetExporterName (void)
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
virtual void GetExtendedAssetRegistryTagsForSave (const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &OutTags) const
Temporary interim solution to gather asset registry data at save time only.
FString GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
virtual bool GetNativePropertyValues (TMap< FString, FString > &out_PropertyValues, uint32 ExportFlags=0) const
Callback for retrieving a textual representation of natively serialized properties.
virtual uint64 GetNetPushIdDynamic () const
Should only ever be used by internal systems.
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
Called during cooking.
virtual void GetPrestreamPackages (TArray< UObject * > &OutPrestream)
Called during cooking.
virtual FPrimaryAssetId GetPrimaryAssetId () const
Returns an Type:Name pair representing the PrimaryAssetId for this object.
FString GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
SIZE_T GetResourceSizeBytes (EResourceSizeMode::Type Mode)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
virtual FRestoreForUObjectOverwrite * GetRestoreForUObjectOverwrite ()
Save information for StaticAllocateObject in the case of overwriting an existing object.
UScriptStruct * GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
virtual bool HasNonEditorOnlyReferences () const
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
template<class T>
FORCEINLINE bool Implements () const
Returns true if this object implements the interface T, false otherwise.
template<class T>
bool Implements () const
Returns true if this object implements the interface T, false otherwise.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn)
Exports the property values for the specified object as text to the output device.
void InstanceSubobjectTemplates (struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
virtual bool IsAsset () const
Returns true if this object is considered an asset.
bool IsBasedOnArchetype (const UObject *const SomeObject) const
Determine if this object has SomeObject in its archetype chain.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform)
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
virtual bool IsCapturingAsRootObjectForTransaction () const
Method to disable the sub object special handling in the transaction buffer for this object.
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const
Generic function to validate objects during changelist validations, etc.
virtual bool IsEditorOnly () const
Called during saving to determine if the object is forced to be editor only or not.
virtual bool IsFullNameStableForNetworking () const
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
bool IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
virtual bool IsLocalizedResource () const
Returns true if this object is considered a localized resource.
virtual bool IsPostLoadThreadSafe () const
Called during async load to determine if PostLoad can be called on the loading thread.
virtual bool IsReadyForAsyncPostLoad () const
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
virtual bool IsReadyForFinishDestroy ()
Called to check if the object is ready for FinishDestroy.
virtual bool IsSafeForRootSet () const
Returns true if this object is safe to add to the root set.
bool IsSelected () const
Test the selection state of a UObject.
void LoadConfig (UClass *ConfigClass=nullptr, const TCHAR *Filename=nullptr, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > *OutAccessedKeys=nullptr)
Imports property values from an .ini file.
virtual void LoadedFromAnotherClass (const FName &OldClassName)
Called when the object was loaded from another class via active class redirects.
virtual void MarkAsEditorOnlySubobject ()
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
virtual void MoveDataToSparseClassDataStruct () const
virtual bool NeedsLoadForTargetPlatform (const class ITargetPlatform *TargetPlatform) const
Called during saving to determine the load flags to save with the object.
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &Context)
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
void OutputReferencers (FOutputDevice &Ar, FReferencerInformationList *Referencers=NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
virtual void OverrideConfigSection (FString &SectionName)
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
virtual void OverridePerObjectConfigSection (FString &SectionName)
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
void ParseParms (const TCHAR *Parms)
Import an object from a file.
virtual void PostCDOCompiled (const FPostCDOCompiledContext &Context)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
virtual void PostCDOContruct ()
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
virtual void PostDuplicate (bool bDuplicateForPIE)
Called after duplication & serialization and before PostLoad.
virtual void PostDuplicate (EDuplicateMode::Type DuplicateMode)
void PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
virtual void PostEditImport ()
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation)
Called after applying a transaction to the object in cases where transaction annotation was provided.
virtual void PostLinkerChange ()
Called in response to the linker changing, this can only happen in the editor.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph)
Instances components for objects being loaded from disk, if necessary.
virtual void PostReinitProperties ()
Called after properties are overwritten, including after subobjects initialization from a CDO.
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded)
Called from ReloadConfig after the object has reloaded its configuration data.
virtual void PostRepNotifies ()
Called right after calling all OnRep notifies (called even when there are no notifies)
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent)
Called after the object has been transacted in some way.
virtual void PreDestroyFromReplication ()
Called right before being marked for destruction due to network replication.
virtual void PreDuplicate (FObjectDuplicationParameters &DupParams)
Called before duplication.
virtual void PreEditChange (class FEditPropertyChain &PropertyAboutToChange)
This alternate version of PreEditChange is called when properties inside structs are modified.
virtual void PreSave (FObjectPreSaveContext SaveContext)
Presave function.
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual bool ProcessConsoleExec (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor)
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
virtual void ProcessEvent (UFunction *Function, void *Parms)
Called by VM to execute a UFunction with a filled in UStruct of parameters.
void PropagatePostEditChange (TArray< UObject * > &AffectedObjects, FPropertyChangedChainEvent &PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
void PropagatePreEditChange (TArray< UObject * > &AffectedObjects, FEditPropertyChain &PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
virtual UClass * RegenerateClass (UClass *ClassToRegenerate, UObject *PreviousCDO)
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
void ReinitializeProperties (UObject *SourceObject=NULL, struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
void ReloadConfig (UClass *ConfigClass=NULL, const TCHAR *Filename=NULL, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
virtual bool ResolveSubobject (const TCHAR *SubObjectPath, UObject *&OutObject, bool bLoadIfExists)
Called to defer loading a subobject to its top-level container object.
void RetrieveReferencers (TArray< FReferencerInformation > *OutInternalReferencers, TArray< FReferencerInformation > *OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
void SaveConfig (uint64 RequiredPropertyFlags=CPF_Config, const TCHAR *Filename=nullptr, FConfigCacheIni *Config=GConfig, bool bAllowCopyToDefaultObject=true)
Save configuration out to ini files.
virtual void Serialize (FStructuredArchive::FRecord Record)
void SerializeScriptProperties (FArchive &Ar) const
Serializes the script property data located at Data.
void SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
void SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
void SetLinker (FLinkerLoad *LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting=true)
Changes the linker and linker index to the passed in one.
virtual void ShutdownAfterError ()
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
void SkipFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
virtual void TagSubobjects (EObjectFlags NewFlags)
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
void ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext &Context) const
Internal use function for the AssetRegistry.
bool TryUpdateDefaultConfigFile (const FString &SpecificFileLocation="", bool bWarnIfFail=true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") 1 void UpdateDefaultConfigFile(const FString &SpecificFileLocation
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.1, "Use version that takes FPostCDOCompiledContext instead.") virtual void PostCDOCompiled()
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
UE_DEPRECATED (5.3, "Matinee has been removed in 5.0, nothing is calling PostInterpChange anymore") virtual void PostInterpChange(FProperty *PropertyThatChanged)
UE_DEPRECATED (5.3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") 1 virtual EDataValidationResult IsDataValid(TArray< FText > &ValidationErrors)
Generic function to validate objects during changelist validations, etc.
UE_DEPRECATED (5.3, "Please use the the const version of IsDataValid(FDataValidationContext&)") 1 virtual EDataValidationResult IsDataValid(class FDataValidationContext &Context)
UE_DEPRECATED (5.4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") 1 void CollectDefaultSubobjects(TArray< UObject * > &OutDefaultSubobjects
Gets all subobjects inside this object that return true for IsDefaultSubobject.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const
UE_DEPRECATED (5.5, "Multithreaded destruction of UObjects is no longer supported.") 1 virtual bool IsDestructionThreadSafe() const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
UE_DEPRECATED (5.5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \ Note that this function MUST be safe to call on a background thread. If you have functionality that doesn't meet that requirement, \ consider using the AssetRegistry's AssetAddedEvent which fires on the game thread.") virtual void PostLoadAssetRegistryTags(const FAssetData &InAssetData
void UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
void UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
void UpdateSinglePropertyInConfigFile (const FProperty *InProperty, const FString &InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
virtual void ValidateGeneratedRepEnums (const TArray< struct FRepRecord > &ClassReps) const
virtual void WillNeverCacheCookedPlatformDataAgain ()
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Public Member Functions inherited from UObjectBaseUtility
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Public Member Functions inherited from IAsyncPhysicsStateProcessor
virtual void CollectBodySetupsWithPhysicsMeshesToCreate (TSet< UBodySetup * > &OutBodySetups) const
Returns body setups that needs to create their physics meshes before physics state asynchronous creation.
Data Fields
TSharedPtr< FGameplayAbilityActorInfo > AbilityActorInfo
Cached off data about the owning actor that abilities will need to frequently access (movement component, mesh component, anim instance, etc)
FPredictionKey AbilityOriginalPredictionKey
FPredictionKey const FGameplayAbilityTargetDataHandle FGameplayTag ApplicationTag
FPredictionKey const FGameplayAbilityTargetDataHandle FGameplayTag FPredictionKey CurrentPredictionKey
FPredictionKey FPredictionKey CurrentPredictionKey
EEndPlayReason::Type EndPlayReason
FPredictionKey const FGameplayAbilityTargetDataHandle & ReplicatedTargetDataHandle
Data Fields inherited from UGameplayTasksComponent
Category = "Gameplay Tasks"
meta
Data Fields inherited from UActorComponent
uint8 bAllowAnyoneToDestroyMe:1
Can this component be destroyed (via K2_DestroyComponent) by any parent.
uint8 bAllowConcurrentTick:1
Can we tick this concurrently on other threads?
uint8 bAutoRegister:1
Does this component automatically register with its owner.
UPROPERTY() uint8 bEditableWhenInherited uint8 bNavigationRelevant: 1
Whether the component is activated at creation or must be explicitly activated.
uint8 bNeverNeedsRenderUpdate:1
If true, this component never needs a render update.
bool bReset =false)
uint8 bTickInEditor:1
Should this component be ticked in the editor.
uint8 bWantsInitializeComponent:1
Whether this component can potentially influence navigation.
float SimSeconds
Data Fields inherited from UObject
bool bIncludeNestedSubobjects =false) const
TArray< FAssetRegistryTag > &OutTagsAndValuesToUpdate const final
Protected Member Functions
virtual GAMEPLAYABILITIES_API void AddGameplayCue_Internal (const FGameplayTag GameplayCueTag, const FGameplayCueParameters &GameplayCueParameters, FActiveGameplayCueContainer &GameplayCueContainer)
virtual GAMEPLAYABILITIES_API void AddGameplayCue_Internal (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle &EffectContext, FActiveGameplayCueContainer &GameplayCueContainer)
GAMEPLAYABILITIES_API PRAGMA_ENABLE_DEPRECATION_WARNINGS void AddReplicatedInstancedAbility (UGameplayAbility *GameplayAbility)
Add a gameplay ability associated to this component.
GAMEPLAYABILITIES_API void AnimMontage_UpdateForcedPlayFlags (FGameplayAbilityRepAnimMontage &OutRepAnimMontageInfo)
Copy over playing flags for duplicate animation data.
GAMEPLAYABILITIES_API void AnimMontage_UpdateReplicatedData ()
Copy LocalAnimMontageInfo into RepAnimMontageInfo.
GAMEPLAYABILITIES_API void AnimMontage_UpdateReplicatedData (FGameplayAbilityRepAnimMontage &OutRepAnimMontageInfo)
virtual GAMEPLAYABILITIES_API void CancelAbilitySpec (FGameplayAbilitySpec &Spec, UGameplayAbility *Ignore)
Cancel a specific ability spec.
GAMEPLAYABILITIES_API void CheckDurationExpired (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API void CheckForClearedAbilities ()
Called from ClearAbility, ClearAllAbilities or OnRep.
virtual GAMEPLAYABILITIES_API UGameplayAbility * CreateNewInstanceOfAbility (FGameplayAbilitySpec &Spec, const UGameplayAbility *Ability)
Creates a new instance of an ability, storing it in the spec.
GAMEPLAYABILITIES_API void DebugCyclicAggregatorBroadcasts (struct FAggregator *Aggregator)
GAMEPLAYABILITIES_API void ExecuteGameplayEffect (FGameplayEffectSpec &Spec, FPredictionKey PredictionKey)
GAMEPLAYABILITIES_API void ExecutePeriodicEffect (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API TArray< TObjectPtr< UGameplayTask > > & GetAbilityActiveTasks (UGameplayAbility *Ability)
GAMEPLAYABILITIES_API const UAttributeSet * GetAttributeSubobject (const TSubclassOf< UAttributeSet > AttributeClass) const
GAMEPLAYABILITIES_API const UAttributeSet * GetAttributeSubobjectChecked (const TSubclassOf< UAttributeSet > AttributeClass) const
GAMEPLAYABILITIES_API const TArray< uint8 > & GetBlockedAbilityBindings () const
GAMEPLAYABILITIES_API TArray< uint8 > & GetBlockedAbilityBindings_Mutable ()
virtual GAMEPLAYABILITIES_API void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
Returns properties that are replicated for the lifetime of the actor channel.
GAMEPLAYABILITIES_API const FMinimalReplicationTagCountMap & GetMinimalReplicationTags () const
GAMEPLAYABILITIES_API FMinimalReplicationTagCountMap & GetMinimalReplicationTags_Mutable ()
GAMEPLAYABILITIES_API const UAttributeSet * GetOrCreateAttributeSubobject (TSubclassOf< UAttributeSet > AttributeClass)
GAMEPLAYABILITIES_API const FGameplayAbilityRepAnimMontage & GetRepAnimMontageInfo () const
GAMEPLAYABILITIES_API FGameplayAbilityRepAnimMontage & GetRepAnimMontageInfo_Mutable ()
virtual GAMEPLAYABILITIES_API void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const override
Called when this object begins replicating to initialize the state of custom property conditions.
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray< UGameplayAbility * > & GetReplicatedInstancedAbilities () const
Full list of all instance-per-execution gameplay abilities associated with this component.
GAMEPLAYABILITIES_API const FMinimalReplicationTagCountMap & GetReplicatedLooseTags () const
GAMEPLAYABILITIES_API FMinimalReplicationTagCountMap & GetReplicatedLooseTags_Mutable ()
GAMEPLAYABILITIES_API bool HasNetworkAuthorityToActivateTriggeredAbility (const FGameplayAbilitySpec &Spec) const
Returns true if the specified ability should be activated from an event in this network mode.
GAMEPLAYABILITIES_API bool HasNetworkAuthorityToApplyGameplayEffect (FPredictionKey PredictionKey) const
virtual GAMEPLAYABILITIES_API void InternalServerTryActivateAbility (FGameplayAbilitySpecHandle AbilityToActivate, bool InputPressed, const FPredictionKey &PredictionKey, const FGameplayEventData *TriggerEventData)
Implementation of ServerTryActivateAbility.
virtual GAMEPLAYABILITIES_API bool IsReadyForReplicatedMontage ()
Returns true if we are ready to handle replicated montage information.
virtual GAMEPLAYABILITIES_API void MonitoredTagChanged (const FGameplayTag Tag, int32 NewCount)
Callback that is called when an owned tag bound to an ability changes.
GAMEPLAYABILITIES_API void NotifyTagMap_StackCountChange (const FGameplayTagContainer &Container)
GAMEPLAYABILITIES_API void OnClientActivateAbilityCaughtUp (FGameplayAbilitySpecHandle AbilityToActivate, FPredictionKey::KeyType PredictionKey)
virtual GAMEPLAYABILITIES_API void OnGiveAbility (FGameplayAbilitySpec &AbilitySpec)
Will be called from GiveAbility or from OnRep.
GAMEPLAYABILITIES_API void OnPredictiveMontageRejected (UAnimMontage *PredictiveMontage)
Called when a prediction key that played a montage is rejected.
virtual GAMEPLAYABILITIES_API void OnRemoveAbility (FGameplayAbilitySpec &AbilitySpec)
Will be called from RemoveAbility or from OnRep.
virtual void OnTagUpdated (const FGameplayTag &Tag, bool TagExists)
GAMEPLAYABILITIES_API void RemoteEndOrCancelAbility (FGameplayAbilitySpecHandle AbilityToEnd, FGameplayAbilityActivationInfo ActivationInfo, bool bWasCanceled)
Called by ServerEndAbility and ClientEndAbility; avoids code duplication.
GAMEPLAYABILITIES_API void RemoveActiveGameplayEffect_AllowClientRemoval (FActiveGameplayEffectHandle Handle, int32 StacksToRemove=-1)
A version of RemoveActiveGameplayEffect that allows us to remove it even when we don't have authority.
GAMEPLAYABILITIES_API void RemoveAllReplicatedInstancedAbilities ()
Unregister all the gameplay abilities of this component.
virtual GAMEPLAYABILITIES_API void RemoveGameplayCue_Internal (const FGameplayTag GameplayCueTag, FActiveGameplayCueContainer &GameplayCueContainer)
GAMEPLAYABILITIES_API void RemoveReplicatedInstancedAbility (UGameplayAbility *GameplayAbility)
Remove a gameplay ability associated to this component.
GAMEPLAYABILITIES_API void ResetTagMap ()
GAMEPLAYABILITIES_API void SetBlockedAbilityBindings (const TArray< uint8 > &NewBlockedAbilityBindings)
GAMEPLAYABILITIES_API void SetMinimalReplicationTags (const FMinimalReplicationTagCountMap &NewMinimalReplicationTags)
GAMEPLAYABILITIES_API void SetNumericAttribute_Internal (const FGameplayAttribute &Attribute, float &NewFloatValue)
Actually pushes the final attribute value to the attribute set's property.
GAMEPLAYABILITIES_API void SetRepAnimMontageInfo (const FGameplayAbilityRepAnimMontage &NewRepAnimMontageInfo)
UE_DEPRECATED (4.26, "This will be made private in future engine versions. Use SetBlockedAbilityBindings, GetBlockedAbilityBindings, or GetBlockedAbilityBindings_Mutable instead.") UPROPERTY() TArray< uint8 > BlockedAbilityBindings
Tracks abilities that are blocked based on input binding.
UE_DEPRECATED (4.26, "This will be made private in future engine versions. Use SetMinimalReplicationTags, GetMinimalReplicationTags, or GetMinimalReplicationTags_Mutable instead.") UPROPERTY() FMinimalReplicationTagCountMap MinimalReplicationTags
UE_DEPRECATED (4.26, "This will be made private in future engine versions. Use SetRepAnimMontageInfo, GetRepAnimMontageInfo, or GetRepAnimMontageInfo_Mutable instead.") UPROPERTY() FGameplayAbilityRepAnimMontage RepAnimMontageInfo
Data structure for replicating montage info to simulated clients.
UE_DEPRECATED (5.1, "This array will be made private. Use GetReplicatedInstancedAbilities, AddReplicatedInstancedAbility or RemoveReplicatedInstancedAbility instead.") UPROPERTY() TArray< TObjectPtr< UGameplayAbility > > AllReplicatedInstancedAbilities
Full list of all instance-per-execution gameplay abilities associated with this component.
UE_DEPRECATED (5.3, "Use OnImmunityBlockGameplayEffectDelegate directly. It is trigger from a UImmunityGameplayEffectComponent. You can create your own GameplayEffectComponent if you need different functionality.") GAMEPLAYABILITIES_API virtual void OnImmunityBlockGameplayEffect(const FGameplayEffectSpec &Spec
UFUNCTION () GAMEPLAYABILITIES_API virtual void OnRep_ActivateAbilities()
UFUNCTION () GAMEPLAYABILITIES_API virtual void OnRep_ReplicatedAnimMontage()
UFUNCTION () GAMEPLAYABILITIES_API void ClientActivateAbilityFailed(FGameplayAbilitySpecHandle AbilityToActivate
UFUNCTION () GAMEPLAYABILITIES_API void ClientActivateAbilitySucceed(FGameplayAbilitySpecHandle AbilityToActivate
UFUNCTION () GAMEPLAYABILITIES_API void ClientActivateAbilitySucceedWithEventData(FGameplayAbilitySpecHandle AbilityToActivate
UFUNCTION () GAMEPLAYABILITIES_API void ClientCancelAbility(FGameplayAbilitySpecHandle AbilityToCancel
UFUNCTION () GAMEPLAYABILITIES_API void ClientEndAbility(FGameplayAbilitySpecHandle AbilityToEnd
UFUNCTION () GAMEPLAYABILITIES_API void ClientTryActivateAbility(FGameplayAbilitySpecHandle AbilityToActivate)
UFUNCTION () GAMEPLAYABILITIES_API void ServerCancelAbility(FGameplayAbilitySpecHandle AbilityToCancel
UFUNCTION () GAMEPLAYABILITIES_API void ServerCurrentMontageJumpToSectionName(UAnimSequenceBase *ClientAnimation
RPC function called from CurrentMontageJumpToSection, replicates to other clients.
UFUNCTION () GAMEPLAYABILITIES_API void ServerCurrentMontageSetNextSectionName(UAnimSequenceBase *ClientAnimation
RPC function called from CurrentMontageSetNextSectionName, replicates to other clients.
UFUNCTION () GAMEPLAYABILITIES_API void ServerCurrentMontageSetPlayRate(UAnimSequenceBase *ClientAnimation
RPC function called from CurrentMontageSetPlayRate, replicates to other clients.
UFUNCTION () GAMEPLAYABILITIES_API void ServerEndAbility(FGameplayAbilitySpecHandle AbilityToEnd
UFUNCTION () GAMEPLAYABILITIES_API void ServerTryActivateAbility(FGameplayAbilitySpecHandle AbilityToActivate
UFUNCTION () GAMEPLAYABILITIES_API void ServerTryActivateAbilityWithEventData(FGameplayAbilitySpecHandle AbilityToActivate
GAMEPLAYABILITIES_API void UpdateActiveGameplayEffectsReplicationCondition ()
GAMEPLAYABILITIES_API void UpdateMinimalReplicationGameplayCuesCondition ()
GAMEPLAYABILITIES_API void UpdateTagMap_Internal (const FGameplayTagContainer &Container, int32 CountDelta)
UPROPERTY () bool bCachedIsNetSimulated
Cached value of rather this is a simulated actor.
UPROPERTY () bool bPendingMontageRep
Set if montage rep happens while we don't have the animinstance associated with us yet.
UPROPERTY () FActiveGameplayCueContainer ActiveGameplayCues
List of all active gameplay cues (executed outside of Gameplay Effects)
UPROPERTY () FActiveGameplayCueContainer MinimalReplicationGameplayCues
Replicated gameplaycues when in minimal replication mode.
UPROPERTY () FActiveGameplayEffectsContainer ActiveGameplayEffects
Contains all of the gameplay effects that are currently active on this component.
UPROPERTY () FGameplayAbilityLocalAnimMontage LocalAnimMontageInfo
Data structure for montages that were instigated locally (everything if server, predictive if client.
UPROPERTY () FGameplayAbilitySpecContainer ActivatableAbilities
The abilities we can activate.
Protected Member Functions inherited from UGameplayTasksComponent
GAMEPLAYTASKS_API bool AddSimulatedTask (UGameplayTask *NewTask)
Add a new simulated task.
const TArray< UGameplayTask * > & GetSimulatedTasks ()
Tasks that run on simulated proxies.
GAMEPLAYTASKS_API void ProcessTaskEvents ()
GAMEPLAYTASKS_API void RemoveSimulatedTask (UGameplayTask *NewTask)
Remove an existing simulated task.
GAMEPLAYTASKS_API void RequestTicking ()
GAMEPLAYTASKS_API void SetCurrentlyClaimedResources (FGameplayResourceSet NewClaimedSet)
GAMEPLAYTASKS_API void SetSimulatedTasks (const TArray< UGameplayTask * > &NewSimulatedTasks)
Remove all current tasks and register the one in the passed array.
UE_DEPRECATED (5.1, "This will be removed in future versions. Use AddSimulatedTask or RemoveSimulatedTask to modify the array") GAMEPLAYTASKS_API TArray< TObjectPtr< UGameplayTask > > &GetSimulatedTasks_Mutable()
GAMEPLAYTASKS_API void UpdateTaskActivations ()
UPROPERTY () TArray< TObjectPtr< UGameplayTask > > KnownTasks
All known tasks (processed by this component) referenced for GC.
UPROPERTY () TArray< TObjectPtr< UGameplayTask > > TaskPriorityQueue
UPROPERTY () TArray< TObjectPtr< UGameplayTask > > TickingTasks
Array of currently active UGameplayTask that require ticking.
Protected Member Functions inherited from UActorComponent
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context)
Used to create any rendering thread information for this component.
void DeferRemoveAsyncPhysicsTick ()
Defers the call to SetAsyncPhysicsTickEnabled(false) to the next async tick.
virtual void DestroyRenderState_Concurrent ()
Used to shut down any rendering thread structure for this component.
void HandleCanEverAffectNavigationChange (bool bForceUpdate=false)
Makes sure navigation system has up to date information regarding component's navigation relevancy and if it can affect navigation at all.
virtual bool HasValidPhysicsState () const
Used to check that DestroyPhysicsState() is working correctly.
bool NeedsInitialization () const
Convenience method for testing whether or not we are still be constructed / initialized.
virtual void OnCreatePhysicsState ()
Used to create any physics engine information for this component.
virtual void OnDestroyPhysicsState ()
Used to shut down and physics engine structure for this component.
virtual void OnPreRegister ()
Called by PreRegisterComponentWithWorld when the component is being pre-registered.
virtual void OnPreRegistered ()
Called once the component is pre-registered.
virtual void OnPreUnregister ()
Called by PreUnregisterComponentFromWorld when the component is being pre-unregistered.
virtual void OnPreUnregistered ()
Called once the component is pre-unregistered.
bool OwnerNeedsInitialization () const
Convenience method for testing whether or not our owner is still being constructed / initialized.
virtual void PrecachePSOs ()
Precache all PSOs which can be used by the actor component.
virtual void RegisterComponentTickFunctions (bool bRegister)
Virtual call chain to register all tick functions.
virtual void SendRenderDynamicData_Concurrent ()
Called to send dynamic data for this component to the rendering thread.
virtual void SendRenderInstanceData_Concurrent ()
Called to send instance data for this component to the rendering thread.
virtual void SendRenderTransform_Concurrent ()
Called to send a transform update for this component to the rendering thread.
void SetAsyncPhysicsTickEnabled (bool bEnabled)
Sets bAsyncPhysicsTickEnabled which determines whether to use use the async physics tick with this component.
void SetIsReplicatedByDefault (const bool bNewReplicates)
Sets the value of bReplicates without causing other side effects to this instance.
virtual bool ShouldActivate () const
Return true if this component is in a state where it can be activated normally.
virtual bool ShouldAsyncCreatePhysicsState (UWorld *WorldContext) const
Returns whether this component should create its physics state asynchronously.
virtual bool ShouldAsyncDestroyPhysicsState () const
Returns whether this component should destroy its physics state asynchronously.
virtual bool ShouldCreatePhysicsState () const
Return true if CreatePhysicsState() should be called.
virtual bool ShouldCreateRenderState () const
Return true if CreateRenderState() should be called.
UPROPERTY () TArray< TObjectPtr< UAssetUserData > > AssetUserData
Array of user data stored with the component.
Protected Member Functions inherited from UObject
bool CanCheckDefaultSubObjects (bool bForceCheck, bool &bResult) const
Checks it's ok to perform subobjects check at this time.
virtual bool CheckDefaultSubobjectsInternal () const
Checks default sub-object assumptions.
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const
virtual FString GetDetailedInfoInternal () const
This function actually does the work for the GetDetailedInfo() and is virtual.
virtual void ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext &Context) const
Performs fixup on loaded asset registry data.
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Protected Member Functions inherited from IGameplayTagAssetInterface
UFUNCTION ()) GAMEPLAYTAGS_API virtual UPARAM(DisplayName
Gets the owned gameplay tags for the asset.
Protected Attributes
float AbilityLastActivatedTime
Local World time of the last ability activation.
TArray< FAbilityListLockActiveChange * > AbilityListLockActiveChanges
TArray< FGameplayAbilitySpec, TInlineAllocator< 2 > > AbilityPendingAdds
Abilities that will be added when exiting the current ability scope lock.
TArray< FGameplayAbilitySpecHandle, TInlineAllocator< 2 > > AbilityPendingRemoves
Abilities that will be removed when exiting the current ability scope lock.
int32 AbilityScopeLockCount
Indicates how many levels of ABILITY_SCOPE_LOCK() we are in.
FGameplayAbilityReplicatedDataContainer AbilityTargetDataMap
Maps from an ability spec to the target data.
FGameplayAbilityActivationInfo ActivationInfo
bool bAbilityPendingClearAll
Whether all abilities should be removed when exiting the current ability scope lock.
FGameplayTagCountContainer BlockedAbilityTags
Abilities with these tags are not able to be activated.
int32 ClientActivateAbilityFailedCountRecent
float ClientActivateAbilityFailedStartTime
float ClientPosition
TArray< TPair< FGameplayTagContainer, FGameplayEventTagMulticastDelegate > > GameplayEventTagContainerDelegates
List of gameplay tag container filters, and the delegates they call.
TMap< FGameplayTag, TArray< FGameplayAbilitySpecHandle > > GameplayEventTriggeredAbilities
Abilities that are triggered from a gameplay event.
FGameplayTagCountContainer GameplayTagCountContainer
Acceleration map for all gameplay tags (OwnedGameplayTags from GEs and explicit GameplayCueTags)
const FActiveGameplayEffect * ImmunityGE
float InPlayRate
bool InputPressed
float FName FName NextSectionName
TMap< FGameplayTag, TArray< FGameplayAbilitySpecHandle > > OwnedTagTriggeredAbilities
Abilities that are triggered from a tag being added to the owner.
bool FPredictionKey PredictionKey
FGameplayAbilityActivationInfo FPredictionKey PredictionKey
int16 PredictionKey
float FName SectionName
FName SectionName
bool FPredictionKey FGameplayEventData TriggerEventData
FPredictionKey FGameplayEventData TriggerEventData
Protected Attributes inherited from UGameplayTasksComponent
FGameplayResourceSet CurrentlyClaimedResources
Resources used by currently active tasks.
TArray< FGameplayTaskEventData > TaskEvents
Transient array of events whose main role is to avoid long chain of recurrent calls if an activated/paused/removed task wants to push/pause/kill other tasks.
uint8 TopActivePriority
Indicates what's the highest priority among currently running tasks.
Protected Attributes inherited from UActorComponent
uint8 bAllowReregistration:1
Check whether the component class allows reregistration during ReregisterAllComponents.
uint8 bCallAsyncPhysicsStateCreatedDelegate:1
If the physics state was created while component was pre-registering, notification to GameThread is deferred next time CreatePhysicsState is called.
uint8 bPhysicsStateCreated:1
If the physics state is currently created for this component.
uint8 bRegistered:1
Indicates if this ActorComponent is currently registered with a scene.
uint8 bRenderStateCreated:1
If the render state is currently created for this component.
uint8 bRenderStateRecreating:1
Render state is being recreated for this component.
EComponentRegistrationState RegistrationState
Indicates if this ActorComponent is currently pre-registering or pre-registered with a scene.
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Private Member Functions
virtual GAMEPLAYABILITIES_API void AbilityLocalInputPressed (int32 InputID)
Called to handle ability bind input.
virtual GAMEPLAYABILITIES_API void AbilityLocalInputReleased (int32 InputID)
GAMEPLAYABILITIES_API void AccumulateScreenPos (FAbilitySystemComponentDebugInfo &Info)
template<class T>
const T * AddAttributeSetSubobject (T *Subobject)
Manually add a new attribute set that is a subobject of this ability system component.
GAMEPLAYABILITIES_API void AddGameplayCue (const FGameplayTag GameplayCueTag, const FGameplayCueParameters &GameplayCueParameters)
GAMEPLAYABILITIES_API void AddGameplayCue (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle EffectContext=FGameplayEffectContextHandle())
Add a persistent gameplay cue.
GAMEPLAYABILITIES_API void AddGameplayCue_MinimalReplication (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle EffectContext=FGameplayEffectContextHandle())
Add gameplaycue for minimal replication mode.
GAMEPLAYABILITIES_API FDelegateHandle AddGameplayEventTagContainerDelegate (const FGameplayTagContainer &TagFilter, const FGameplayEventTagMulticastDelegate::FDelegate &Delegate)
Adds a new delegate to call when gameplay events happen.
FORCEINLINE void AddLooseGameplayTag (const FGameplayTag &GameplayTag, int32 Count=1)
Allows GameCode to add loose gameplaytags which are not backed by a GameplayEffect.
FORCEINLINE void AddLooseGameplayTags (const FGameplayTagContainer &GameplayTags, int32 Count=1)
FORCEINLINE void AddMinimalReplicationGameplayTag (const FGameplayTag &GameplayTag)
Minimally replicated tags are replicated tags that come from GEs when in bMinimalReplication mode.
FORCEINLINE void AddMinimalReplicationGameplayTags (const FGameplayTagContainer &GameplayTags)
FORCEINLINE void AddReplicatedLooseGameplayTag (const FGameplayTag &GameplayTag)
Allows GameCode to add loose gameplaytags which are not backed by a GameplayEffect.
FORCEINLINE void AddReplicatedLooseGameplayTags (const FGameplayTagContainer &GameplayTags)
template<class T>
const T * AddSet ()
Adds a new AttributeSet (initialized to default values)
GAMEPLAYABILITIES_API void AddSpawnedAttribute (UAttributeSet *Attribute)
Add a new attribute set.
virtual GAMEPLAYABILITIES_API void ApplyAbilityBlockAndCancelTags (const FGameplayTagContainer &AbilityTags, UGameplayAbility *RequestingAbility, bool bEnableBlockTags, const FGameplayTagContainer &BlockTags, bool bExecuteCancelTags, const FGameplayTagContainer &CancelTags)
Called from ability activation or native code, will apply the correct ability blocking tags and cancel existing abilities.
virtual GAMEPLAYABILITIES_API FActiveGameplayEffectHandle ApplyGameplayEffectSpecToSelf (const FGameplayEffectSpec &GameplayEffect, FPredictionKey PredictionKey=FPredictionKey())
virtual GAMEPLAYABILITIES_API FActiveGameplayEffectHandle ApplyGameplayEffectSpecToTarget (const FGameplayEffectSpec &GameplayEffect, UAbilitySystemComponent *Target, FPredictionKey PredictionKey=FPredictionKey())
GAMEPLAYABILITIES_API FActiveGameplayEffectHandle ApplyGameplayEffectToSelf (const UGameplayEffect *GameplayEffect, float Level, const FGameplayEffectContextHandle &EffectContext, FPredictionKey PredictionKey=FPredictionKey())
GAMEPLAYABILITIES_API FActiveGameplayEffectHandle ApplyGameplayEffectToTarget (UGameplayEffect *GameplayEffect, UAbilitySystemComponent *Target, float Level=UGameplayEffect::INVALID_LEVEL, FGameplayEffectContextHandle Context=FGameplayEffectContextHandle(), FPredictionKey PredictionKey=FPredictionKey())
GAMEPLAYABILITIES_API void ApplyModToAttribute (const FGameplayAttribute &Attribute, TEnumAsByte< EGameplayModOp::Type > ModifierOp, float ModifierMagnitude)
Applies an in-place mod to the given attribute.
GAMEPLAYABILITIES_API void ApplyModToAttributeUnsafe (const FGameplayAttribute &Attribute, TEnumAsByte< EGameplayModOp::Type > ModifierOp, float ModifierMagnitude)
Applies an inplace mod to the given attribute.
virtual GAMEPLAYABILITIES_API bool AreAbilityTagsBlocked (const FGameplayTagContainer &Tags) const
Returns true if any passed in tags are blocked.
virtual GAMEPLAYABILITIES_API void BeginServerAbilityRPCBatch (FGameplayAbilitySpecHandle AbilityHandle)
virtual GAMEPLAYABILITIES_API void BindAbilityActivationToInputComponent (UInputComponent *InputComponent, FGameplayAbilityInputBinds BindInfo)
Bind to an input component with customized bindings.
virtual GAMEPLAYABILITIES_API void BindToInputComponent (UInputComponent *InputComponent)
Bind to an input component with some default action names.
GAMEPLAYABILITIES_API void BlockAbilitiesWithTags (const FGameplayTagContainer &Tags)
Block or cancel blocking for specific ability tags.
GAMEPLAYABILITIES_API void BlockAbilityByInputID (int32 InputID)
Block or cancel blocking for specific input IDs.
virtual GAMEPLAYABILITIES_API FGameplayAbilitySpec BuildAbilitySpecFromClass (TSubclassOf< UGameplayAbility > AbilityClass, int32 Level=0, int32 InputID=-1)
Build a simple FGameplayAbilitySpec from class, level and optional Input ID.
GAMEPLAYABILITIES_API void CallServerEndAbility (FGameplayAbilitySpecHandle AbilityToEnd, FGameplayAbilityActivationInfo ActivationInfo, FPredictionKey PredictionKey)
GAMEPLAYABILITIES_API void CallServerSetReplicatedTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, const FGameplayAbilityTargetDataHandle &ReplicatedTargetDataHandle, FGameplayTag ApplicationTag, FPredictionKey CurrentPredictionKey)
GAMEPLAYABILITIES_API void CallServerTryActivateAbility (FGameplayAbilitySpecHandle AbilityToActivate, bool InputPressed, FPredictionKey PredictionKey)
bool CanApplyAttributeModifiers (const UGameplayEffect *GameplayEffect, float Level, const FGameplayEffectContextHandle &EffectContext)
Tests if all modifiers in this GameplayEffect will leave the attribute > 0.f.
GAMEPLAYABILITIES_API void CancelAbilities (const FGameplayTagContainer *WithTags=nullptr, const FGameplayTagContainer *WithoutTags=nullptr, UGameplayAbility *Ignore=nullptr)
Cancel all abilities with the specified tags.
GAMEPLAYABILITIES_API void CancelAbility (UGameplayAbility *Ability)
Cancels the specified ability CDO.
GAMEPLAYABILITIES_API void CancelAbilityHandle (const FGameplayAbilitySpecHandle &AbilityHandle)
Cancels the ability indicated by passed in spec handle.
GAMEPLAYABILITIES_API void CancelAllAbilities (UGameplayAbility *Ignore=nullptr)
Cancels all abilities regardless of tags.
bool CanPredict () const
Do we have a valid prediction key to do more predictive actions with.
GAMEPLAYABILITIES_API void CaptureAttributeForGameplayEffect (OUT FGameplayEffectAttributeCaptureSpec &OutCaptureSpec)
Populate the specified capture spec with the data necessary to capture an attribute from the component.
GAMEPLAYABILITIES_API FString CleanupName (FString Str)
GAMEPLAYABILITIES_API void ClearAbilityReplicatedDataCache (FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActivationInfo &ActivationInfo)
virtual GAMEPLAYABILITIES_API void ClearAnimatingAbility (UGameplayAbility *Ability)
Clear the animating ability that is passed in, if it's still currently animating.
virtual GAMEPLAYABILITIES_API void CurrentMontageJumpToSection (FName SectionName)
Jumps current montage to given section.
virtual GAMEPLAYABILITIES_API void CurrentMontageSetNextSectionName (FName FromSectionName, FName ToSectionName)
Sets current montages next section name.
virtual GAMEPLAYABILITIES_API void CurrentMontageSetPlayRate (float InPlayRate)
Sets current montage's play rate.
virtual GAMEPLAYABILITIES_API void CurrentMontageStop (float OverrideBlendOutTime=-1.0f)
Stops whatever montage is currently playing.
virtual GAMEPLAYABILITIES_API void Debug_Internal (struct FAbilitySystemComponentDebugInfo &Info)
GAMEPLAYABILITIES_API void DebugLine (struct FAbilitySystemComponentDebugInfo &Info, FString Str, float XOffset, float YOffset, int32 MinTextRowsToAdvance=0)
DECLARE_DYNAMIC_MULTICAST_DELEGATE (FAbilityConfirmOrCancel)
Used to register callbacks to confirm/cancel input.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnGameplayEffectAppliedDelegate, UAbilitySystemComponent *, const FGameplayEffectSpec &, FActiveGameplayEffectHandle)
Delegate for when an effect is applied.
GAMEPLAYABILITIES_API void DecrementAbilityListLock ()
virtual GAMEPLAYABILITIES_API void DestroyActiveState ()
Cancels all abilities and kills any remaining instanced abilities.
virtual GAMEPLAYABILITIES_API void DisplayDebug (class UCanvas *Canvas, const class FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos)
virtual GAMEPLAYABILITIES_API void EndServerAbilityRPCBatch (FGameplayAbilitySpecHandle AbilityHandle)
GAMEPLAYABILITIES_API void ExecuteGameplayCue (const FGameplayTag GameplayCueTag, const FGameplayCueParameters &GameplayCueParameters)
GAMEPLAYABILITIES_API void ExecuteGameplayCue (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle EffectContext=FGameplayEffectContextHandle())
GameplayCues can also come on their own.
GAMEPLAYABILITIES_API FGameplayAbilitySpec * FindAbilitySpecFromClass (TSubclassOf< UGameplayAbility > InAbilityClass) const
Returns an ability spec corresponding to given ability class.
GAMEPLAYABILITIES_API FGameplayAbilitySpec * FindAbilitySpecFromHandle (FGameplayAbilitySpecHandle Handle, EConsiderPending ConsiderPending=EConsiderPending::PendingRemove) const
Returns an ability spec from a handle.
GAMEPLAYABILITIES_API FGameplayAbilitySpec * FindAbilitySpecFromInputID (int32 InputID) const
Returns an ability spec from a handle.
GAMEPLAYABILITIES_API TArray< const FGameplayAbilitySpec * > FindAbilitySpecsFromGEHandle (const FScopedAbilityListLock &ScopeLock, FActiveGameplayEffectHandle Handle, EConsiderPending ConsiderPending=EConsiderPending::PendingRemove) const
Returns all ability spec handles granted from a GE handle.
GAMEPLAYABILITIES_API FActiveGameplayEffectHandle FindActiveGameplayEffectHandle (FGameplayAbilitySpecHandle Handle) const
Gets the GE Handle of the GE that granted the passed in Ability.
virtual GAMEPLAYABILITIES_API void FindAllAbilitySpecsFromInputID (int32 InputID, TArray< const FGameplayAbilitySpec * > &OutAbilitySpecs) const
Returns all abilities with the given InputID.
virtual GAMEPLAYABILITIES_API void ForceAvatarReplication ()
Forces avatar actor to update it's replication.
virtual GAMEPLAYABILITIES_API void ForceCancelAbilityDueToReplication (UGameplayAbility *Instance)
Force cancels the ability and does not replicate this to the other side.
GENERATED_UCLASS_BODY () DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FAbilityAbilityKey
Used to register callbacks to ability-key input.
float GetAbilityLastActivatedTime () const
Returns local world time that an ability was activated.
TArray< FGameplayAbilitySpec > & GetActivatableAbilities ()
Returns the list of all activatable abilities.
const TArray< FGameplayAbilitySpec > & GetActivatableAbilities () const
Returns the list of all activatable abilities.
GAMEPLAYABILITIES_API void GetActivatableGameplayAbilitySpecsByAllMatchingTags (const FGameplayTagContainer &GameplayTagContainer, TArray< struct FGameplayAbilitySpec * > &MatchingGameplayAbilities, bool bOnlyAbilitiesThatSatisfyTagRequirements=true) const
Gets all Activatable Gameplay Abilities that match all tags in GameplayTagContainer AND for which DoesAbilitySatisfyTagRequirements() is true.
GAMEPLAYABILITIES_API FActiveGameplayEffectEvents * GetActiveEffectEventSet (FActiveGameplayEffectHandle Handle)
Returns delegate structure that allows binding to several gameplay effect changes.
GAMEPLAYABILITIES_API TArray< float > GetActiveEffectsDuration (const FGameplayEffectQuery &Query) const
Gets total duration for all effects that match query.
GAMEPLAYABILITIES_API float GetActiveEffectsEndTime (const FGameplayEffectQuery &Query) const
This will give the world time that all effects matching this query will be finished.
GAMEPLAYABILITIES_API bool GetActiveEffectsEndTimeAndDuration (const FGameplayEffectQuery &Query, float &EndTime, float &Duration) const
Returns end time and total duration.
GAMEPLAYABILITIES_API float GetActiveEffectsEndTimeWithInstigators (const FGameplayEffectQuery &Query, TArray< AActor * > &Instigators) const
GAMEPLAYABILITIES_API TArray< float > GetActiveEffectsTimeRemaining (const FGameplayEffectQuery &Query) const
Gets time remaining for all effects that match query.
GAMEPLAYABILITIES_API TArray< TPair< float, float > > GetActiveEffectsTimeRemainingAndDuration (const FGameplayEffectQuery &Query) const
Gets both time remaining and total duration for all effects that match query.
GAMEPLAYABILITIES_API const FActiveGameplayEffect * GetActiveGameplayEffect (const FActiveGameplayEffectHandle Handle) const
Returns const pointer to the actual active gameplay effect structure.
GAMEPLAYABILITIES_API const FActiveGameplayEffectsContainer & GetActiveGameplayEffects () const
Returns all active gameplay effects on this ASC.
GAMEPLAYABILITIES_API FString GetActiveGEDebugString (FActiveGameplayEffectHandle Handle) const
Returns debug string describing active gameplay effect.
GAMEPLAYABILITIES_API int32 GetAggregatedStackCount (const FGameplayEffectQuery &Query) const
Returns the sum of StackCount of all gameplay effects that pass query.
void GetAllActiveGameplayEffectSpecs (TArray< FGameplayEffectSpec > &OutSpecCopies) const
Makes a copy of all the active effects on this ability component.
GAMEPLAYABILITIES_API UGameplayAbility * GetAnimatingAbility () const
Returns the current animating ability.
FORCEINLINE const FGameplayTagContainer & GetBlockedAbilityTags () const
FORCEINLINE void GetBlockedAbilityTags (FGameplayTagContainer &TagContainer) const
Fills TagContainer with BlockedAbilityTags.
GAMEPLAYABILITIES_API const TArray< FString > & GetClientDebugStrings () const
GAMEPLAYABILITIES_API TArray< FString > & GetClientDebugStrings_Mutable ()
GAMEPLAYABILITIES_API UAnimMontage * GetCurrentMontage () const
Returns montage that is currently playing.
GAMEPLAYABILITIES_API int32 GetCurrentMontageSectionID () const
Get SectionID of currently playing AnimMontage.
GAMEPLAYABILITIES_API float GetCurrentMontageSectionLength () const
Get length in time of current section.
GAMEPLAYABILITIES_API FName GetCurrentMontageSectionName () const
Get SectionName of currently playing AnimMontage.
GAMEPLAYABILITIES_API float GetCurrentMontageSectionTimeLeft () const
Returns amount of time left in current section.
GAMEPLAYABILITIES_API int32 GetCurrentStackCount (FActiveGameplayEffectHandle Handle) const
Returns current stack count of an already applied GE.
GAMEPLAYABILITIES_API int32 GetCurrentStackCount (FGameplayAbilitySpecHandle Handle) const
Returns current stack count of an already applied GE, but given the ability spec handle that was granted by the GE.
GAMEPLAYABILITIES_API FGameplayEffectContextHandle GetEffectContextFromActiveGEHandle (FActiveGameplayEffectHandle Handle)
Retrieves the EffectContext of the GameplayEffect of the active GameplayEffect.
GAMEPLAYABILITIES_API float GetFilteredAttributeValue (const FGameplayAttribute &Attribute, const FGameplayTagRequirements &SourceTags, const FGameplayTagContainer &TargetTags, const TArray< FActiveGameplayEffectHandle > &HandlesToIgnore=TArray< FActiveGameplayEffectHandle >())
Returns an attribute value, after applying tag filters.
GAMEPLAYABILITIES_API FOnGameplayAttributeValueChange & GetGameplayAttributeValueChangeDelegate (FGameplayAttribute Attribute)
Register for when an attribute value changes.
GAMEPLAYABILITIES_API const UGameplayEffect * GetGameplayEffectCDO (const FActiveGameplayEffectHandle Handle) const
Returns a const pointer to the gameplay effect CDO associated with an active handle.
GAMEPLAYABILITIES_API const UGameplayEffect * GetGameplayEffectDefForHandle (FActiveGameplayEffectHandle Handle)
Gets the FActiveGameplayEffect based on the passed in Handle.
GAMEPLAYABILITIES_API float GetGameplayEffectDuration (FActiveGameplayEffectHandle Handle) const
Returns the total duration of a gameplay effect.
GAMEPLAYABILITIES_API const FGameplayTagContainer * GetGameplayEffectSourceTagsFromHandle (FActiveGameplayEffectHandle Handle) const
Get the source tags from the gameplay spec represented by the specified handle, if possible.
GAMEPLAYABILITIES_API void GetGameplayEffectStartTimeAndDuration (FActiveGameplayEffectHandle Handle, float &StartEffectTime, float &Duration) const
Return start time and total duration of a gameplay effect.
GAMEPLAYABILITIES_API const FGameplayTagContainer * GetGameplayEffectTargetTagsFromHandle (FActiveGameplayEffectHandle Handle) const
Get the target tags from the gameplay spec represented by the specified handle, if possible.
int32 GetNumActiveGameplayEffects () const
Returns the number of gameplay effects that are currently active on this ability system component.
GAMEPLAYABILITIES_API float GetNumericAttribute (const FGameplayAttribute &Attribute) const
Returns current (final) value of an attribute.
GAMEPLAYABILITIES_API float GetNumericAttributeBase (const FGameplayAttribute &Attribute) const
Gets the base value of an attribute.
GAMEPLAYABILITIES_API float GetNumericAttributeChecked (const FGameplayAttribute &Attribute) const
FORCEINLINE const FGameplayTagContainer & GetOwnedGameplayTags () const
FORCEINLINE void GetOwnedGameplayTags (FGameplayTagContainer &TagContainer) const override
FPredictionKey GetPredictionKeyForNewAction () const
Returns the prediction key that should be used for any actions.
PRAGMA_DISABLE_DEPRECATION_WARNINGS TArray< TObjectPtr< UGameplayAbility > > & GetReplicatedInstancedAbilities_Mutable ()
virtual GAMEPLAYABILITIES_API IAbilitySystemReplicationProxyInterface * GetReplicationInterface ()
Who to route replication through if ReplicationProxyEnabled (if this returns null, when ReplicationProxyEnabled, we wont replicate)
GAMEPLAYABILITIES_API const TArray< FString > & GetServerDebugStrings () const
GAMEPLAYABILITIES_API TArray< FString > & GetServerDebugStrings_Mutable ()
template<class T>
const T * GetSet () const
Finds existing AttributeSet.
template<class T>
const T * GetSetChecked () const
Finds existing AttributeSet.
GAMEPLAYABILITIES_API const TArray< UAttributeSet * > & GetSpawnedAttributes () const
Access the spawned attributes list when you don't intend to modify the list.
FORCEINLINE int32 GetTagCount (FGameplayTag TagToCheck) const
Returns the number of instances of a given tag.
GAMEPLAYABILITIES_API FGameplayAbilitySpecHandle GiveAbility (const FGameplayAbilitySpec &AbilitySpec)
GameplayAbilities.
GAMEPLAYABILITIES_API FGameplayAbilitySpecHandle GiveAbilityAndActivateOnce (FGameplayAbilitySpec &AbilitySpec, const FGameplayEventData *GameplayEventData=nullptr)
virtual void HandleChangeAbilityCanBeCanceled (const FGameplayTagContainer &AbilityTags, UGameplayAbility *RequestingAbility, bool bCanBeCanceled)
Called when an ability is cancellable or not.
virtual GAMEPLAYABILITIES_API void HandleDeferredGameplayCues (const FActiveGameplayEffectsContainer *GameplayEffectsContainer)
Handle GameplayCues that may have been deferred while doing the NetDeltaSerialize and waiting for the avatar actor to get loaded.
virtual GAMEPLAYABILITIES_API int32 HandleGameplayEvent (FGameplayTag EventTag, const FGameplayEventData *Payload)
Executes a gameplay event.
GAMEPLAYABILITIES_API bool HasActivatableTriggeredAbility (FGameplayTag Tag)
FORCEINLINE bool HasAllMatchingGameplayTags (const FGameplayTagContainer &TagContainer) const override
FORCEINLINE bool HasAnyMatchingGameplayTags (const FGameplayTagContainer &TagContainer) const override
GAMEPLAYABILITIES_API bool HasAttributeSetForAttribute (FGameplayAttribute Attribute) const
Does this ability system component have this attribute?
GAMEPLAYABILITIES_API bool HasAuthorityOrPredictionKey (const FGameplayAbilityActivationInfo *ActivationInfo) const
Returns true if this is running on the server or has a valid prediction key.
FORCEINLINE bool HasMatchingGameplayTag (FGameplayTag TagToCheck) const override
GAMEPLAYABILITIES_API void IncrementAbilityListLock ()
Called from FScopedAbilityListLock.
virtual GAMEPLAYABILITIES_API void InitDefaultGameplayCueParameters (FGameplayCueParameters &Parameters)
Will initialize gameplay cue parameters with this ASC's Owner (Instigator) and AvatarActor (EffectCauser)
GAMEPLAYABILITIES_API const UAttributeSet * InitStats (TSubclassOf< class UAttributeSet > Attributes, const UDataTable *DataTable)
Initializes starting attributes from a data table.
GAMEPLAYABILITIES_API bool InternalTryActivateAbility (FGameplayAbilitySpecHandle AbilityToActivate, FPredictionKey InPredictionKey=FPredictionKey(), UGameplayAbility **OutInstancedAbility=nullptr, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate=nullptr, const FGameplayEventData *TriggerEventData=nullptr)
Attempts to activate the given ability, will only work if called from the correct client/server context.
GAMEPLAYABILITIES_API void InvokeGameplayCueEvent (const FGameplayEffectSpecForRPC &Spec, EGameplayCueEvent::Type EventType)
Handles gameplay cue events from external sources.
GAMEPLAYABILITIES_API void InvokeGameplayCueEvent (const FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters &GameplayCueParameters)
GAMEPLAYABILITIES_API void InvokeGameplayCueEvent (const FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, FGameplayEffectContextHandle EffectContext=FGameplayEffectContextHandle())
GAMEPLAYABILITIES_API bool IsAbilityInputBlocked (int32 InputID) const
Checks if the ability system is currently blocking InputID.
GAMEPLAYABILITIES_API bool IsAnimatingAbility (UGameplayAbility *Ability) const
Returns true if the passed in ability is the current animating ability.
bool IsGenericCancelInputBound (int32 InputID) const
bool IsGenericConfirmInputBound (int32 InputID) const
virtual GAMEPLAYABILITIES_API bool IsOwnerActorAuthoritative () const
Returns true if this component's actor has authority.
virtual GAMEPLAYABILITIES_API bool IsReadyForGameplayCues ()
Are we ready to invoke gameplaycues yet?
virtual GAMEPLAYABILITIES_API void LocalInputCancel ()
virtual GAMEPLAYABILITIES_API void LocalInputConfirm ()
Handle confirm/cancel for target actors.
GAMEPLAYABILITIES_API void MarkAbilitySpecDirty (FGameplayAbilitySpec &Spec, bool WasAddOrRemove=false)
Call to mark that an ability spec has been modified.
FORCEINLINE bool MatchesGameplayTagQuery (const FGameplayTagQuery &TagQuery) const
Checks whether the query matches the owned GameplayTags.
virtual GAMEPLAYABILITIES_API void ModifyActiveEffectStartTime (FActiveGameplayEffectHandle Handle, float StartTimeDiff)
Modify the start time of a gameplay effect, to deal with timers being out of sync originally.
virtual GAMEPLAYABILITIES_API void NotifyAbilityActivated (const FGameplayAbilitySpecHandle Handle, UGameplayAbility *Ability)
virtual GAMEPLAYABILITIES_API void NotifyAbilityCommit (UGameplayAbility *Ability)
Call notify callbacks above.
virtual GAMEPLAYABILITIES_API void NotifyAbilityEnded (FGameplayAbilitySpecHandle Handle, UGameplayAbility *Ability, bool bWasCancelled)
Called from the ability to let the component know it is ended.
virtual GAMEPLAYABILITIES_API void NotifyAbilityFailed (const FGameplayAbilitySpecHandle Handle, UGameplayAbility *Ability, const FGameplayTagContainer &FailureReason)
GAMEPLAYABILITIES_API FOnGivenActiveGameplayEffectRemoved & OnAnyGameplayEffectRemovedDelegate ()
Called when any gameplay effects are removed.
GAMEPLAYABILITIES_API void OnAttributeAggregatorDirty (FAggregator *Aggregator, FGameplayAttribute Attribute, bool FromRecursiveCall=false)
Called when a specific attribute aggregator value changes, gameplay effects refresh their values when this happens.
virtual GAMEPLAYABILITIES_API void OnClientPrintDebug_Response (const TArray< FString > &Strings, int32 GameFlags)
GAMEPLAYABILITIES_API void OnGameplayEffectAppliedToSelf (UAbilitySystemComponent *Source, const FGameplayEffectSpec &SpecApplied, FActiveGameplayEffectHandle ActiveHandle)
GAMEPLAYABILITIES_API void OnGameplayEffectAppliedToTarget (UAbilitySystemComponent *Target, const FGameplayEffectSpec &SpecApplied, FActiveGameplayEffectHandle ActiveHandle)
This ASC has successfully applied a GE to something (potentially itself)
virtual GAMEPLAYABILITIES_API void OnGameplayEffectDurationChange (struct FActiveGameplayEffect &ActiveEffect)
Called when the duration of a gameplay effect has changed.
GAMEPLAYABILITIES_API FOnActiveGameplayEffectInhibitionChanged * OnGameplayEffectInhibitionChangedDelegate (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API FOnActiveGameplayEffectRemoved_Info * OnGameplayEffectRemoved_InfoDelegate (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API FOnActiveGameplayEffectStackChange * OnGameplayEffectStackChangeDelegate (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API FOnActiveGameplayEffectTimeChange * OnGameplayEffectTimeChangeDelegate (FActiveGameplayEffectHandle Handle)
GAMEPLAYABILITIES_API void OnMagnitudeDependencyChange (FActiveGameplayEffectHandle Handle, const FAggregator *ChangedAggregator)
Called when attribute magnitudes change, to forward information to dependent gameplay effects.
GAMEPLAYABILITIES_API void OnPeriodicGameplayEffectExecuteOnSelf (UAbilitySystemComponent *Source, const FGameplayEffectSpec &SpecExecuted, FActiveGameplayEffectHandle ActiveHandle)
GAMEPLAYABILITIES_API void OnPeriodicGameplayEffectExecuteOnTarget (UAbilitySystemComponent *Target, const FGameplayEffectSpec &SpecExecuted, FActiveGameplayEffectHandle ActiveHandle)
virtual GAMEPLAYABILITIES_API void OnPredictiveGameplayCueCatchup (FGameplayTag Tag)
Called for predictively added gameplay cue.
virtual GAMEPLAYABILITIES_API void OnServerPrintDebug_Request ()
Virtual function games can override to do their own stuff when either ServerPrintDebug function runs on the server.
virtual GAMEPLAYABILITIES_API float PlayMontage (UGameplayAbility *AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimMontage *Montage, float InPlayRate, FName StartSectionName=NAME_None, float StartTimeSeconds=0.0f)
Plays a montage and handles replication and prediction based on passed in ability/activation info.
GAMEPLAYABILITIES_API float PlayMontageInternal (UGameplayAbility *AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimMontage *Montage, float InPlayRate, FName StartSectionName, float StartTimeSeconds, TFunctionRef< void(FGameplayAbilityRepAnimMontage &)> MutateRepAnimMontageFunction)
virtual GAMEPLAYABILITIES_API float PlayMontageSimulated (UAnimMontage *Montage, float InPlayRate, FName StartSectionName=NAME_None)
Plays a montage without updating replication/prediction structures.
virtual GAMEPLAYABILITIES_API UAnimMontage * PlaySlotAnimationAsDynamicMontage (UGameplayAbility *AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimSequenceBase *AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate=1.f, float StartTimeSeconds=0.0f)
virtual GAMEPLAYABILITIES_API UAnimMontage * PlaySlotAnimationAsDynamicMontage_WithFractionalLoops (UGameplayAbility *AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimSequenceBase *AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate=1.f, float StartTimeSeconds=0.0f, float PlayCount=1.0f)
virtual GAMEPLAYABILITIES_API UAnimMontage * PlaySlotAnimationAsDynamicMontage_WithFractionalLoopsSimulated (UAnimSequenceBase *AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate=1.f, float PlayCount=1.0f)
virtual GAMEPLAYABILITIES_API UAnimMontage * PlaySlotAnimationAsDynamicMontageSimulated (UAnimSequenceBase *AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate=1.f)
GAMEPLAYABILITIES_API void PrintAllGameplayEffects () const
Print a debug list of all gameplay effects.
virtual GAMEPLAYABILITIES_API void PrintDebug ()
virtual GAMEPLAYABILITIES_API void RecomputeGameplayEffectStartTimes (const float WorldTime, const float ServerWorldTime)
Called whenever the server time replicates via the game state to keep our cooldown timers in sync with the server.
GAMEPLAYABILITIES_API FDelegateHandle RegisterAndCallGameplayTagEvent (FGameplayTag Tag, FOnGameplayEffectTagCountChanged::FDelegate Delegate, EGameplayTagEventType::Type EventType=EGameplayTagEventType::NewOrRemoved)
Register a tag event and immediately call it.
GAMEPLAYABILITIES_API FOnGameplayAttributeChange & RegisterGameplayAttributeEvent (FGameplayAttribute Attribute)
Register for when an attribute value changes, should be replaced by GetGameplayAttributeValueChangeDelegate.
GAMEPLAYABILITIES_API FOnGameplayEffectTagCountChanged & RegisterGameplayTagEvent (FGameplayTag Tag, EGameplayTagEventType::Type EventType=EGameplayTagEventType::NewOrRemoved)
Allow events to be registered for specific gameplay tags being added or removed.
GAMEPLAYABILITIES_API FOnGameplayEffectTagCountChanged & RegisterGenericGameplayTagEvent ()
Returns multicast delegate that is invoked whenever a tag is added or removed (but not if just count is increased.
virtual GAMEPLAYABILITIES_API int32 RemoveActiveEffects (const FGameplayEffectQuery &Query, int32 StacksToRemove=-1)
Removes all active effects that match given query.
GAMEPLAYABILITIES_API void RemoveAllGameplayCues ()
Removes any GameplayCue added on its own, i.e.
GAMEPLAYABILITIES_API void RemoveAllSpawnedAttributes ()
Remove all attribute sets.
GAMEPLAYABILITIES_API void RemoveGameplayCue (const FGameplayTag GameplayCueTag)
Remove a persistent gameplay cue.
GAMEPLAYABILITIES_API void RemoveGameplayCue_MinimalReplication (const FGameplayTag GameplayCueTag)
Remove gameplaycue for minimal replication mode.
GAMEPLAYABILITIES_API void RemoveGameplayEventTagContainerDelegate (const FGameplayTagContainer &TagFilter, FDelegateHandle DelegateHandle)
Remotes previously registered delegate.
FORCEINLINE void RemoveLooseGameplayTag (const FGameplayTag &GameplayTag, int32 Count=1)
FORCEINLINE void RemoveLooseGameplayTags (const FGameplayTagContainer &GameplayTags, int32 Count=1)
FORCEINLINE void RemoveMinimalReplicationGameplayTag (const FGameplayTag &GameplayTag)
FORCEINLINE void RemoveMinimalReplicationGameplayTags (const FGameplayTagContainer &GameplayTags)
FORCEINLINE void RemoveReplicatedLooseGameplayTag (const FGameplayTag &GameplayTag)
FORCEINLINE void RemoveReplicatedLooseGameplayTags (const FGameplayTagContainer &GameplayTags)
GAMEPLAYABILITIES_API void RemoveSpawnedAttribute (UAttributeSet *Attribute)
Remove an existing attribute set.
virtual GAMEPLAYABILITIES_API void ReplicateEndOrCancelAbility (FGameplayAbilitySpecHandle Handle, FGameplayAbilityActivationInfo ActivationInfo, UGameplayAbility *Ability, bool bWasCanceled)
Replicate that an ability has ended/canceled, to the client or server as appropriate.
virtual GAMEPLAYABILITIES_API void ServerAbilityRPCBatch_Internal (FServerAbilityRPCBatch &BatchInfo)
virtual GAMEPLAYABILITIES_API FActiveGameplayEffectHandle SetActiveGameplayEffectInhibit (FActiveGameplayEffectHandle &&ActiveGEHandle, bool bInhibit, bool bInvokeGameplayCueEvents)
(Un-)Inhibit an Active Gameplay Effect so it may be disabled (and perform some disabling actions, such as removing tags).
void SetBaseAttributeValueFromReplication (const FGameplayAttribute &Attribute, const FGameplayAttributeData &NewValue, const FGameplayAttributeData &OldValue)
Call from OnRep functions to set the attribute base value on the client.
void SetBaseAttributeValueFromReplication (const FGameplayAttribute &Attribute, float NewValue, float OldValue)
Call from OnRep functions to set the attribute base value on the client.
virtual GAMEPLAYABILITIES_API void SetBlockAbilityBindingsArray (FGameplayAbilityInputBinds BindInfo)
Initializes BlockedAbilityBindings variable.
GAMEPLAYABILITIES_API void SetClientDebugStrings (TArray< FString > &&NewClientDebugStrings)
FORCEINLINE void SetLooseGameplayTagCount (const FGameplayTag &GameplayTag, int32 NewCount)
GAMEPLAYABILITIES_API void SetMontageRepAnimPositionMethod (ERepAnimPositionMethod InMethod)
Method to set the replication method for the position in the montage.
GAMEPLAYABILITIES_API void SetNumericAttributeBase (const FGameplayAttribute &Attribute, float NewBaseValue)
Sets the base value of an attribute.
GAMEPLAYABILITIES_API void SetRemoveAbilityOnEnd (FGameplayAbilitySpecHandle AbilitySpecHandle)
Sets an ability spec to remove when its finished.
FORCEINLINE void SetReplicatedLooseGameplayTagCount (const FGameplayTag &GameplayTag, int32 NewCount)
virtual GAMEPLAYABILITIES_API void SetReplicationMode (EGameplayEffectReplicationMode NewReplicationMode)
When true, we will not replicate active gameplay effects for this ability system component, so attributes and tags.
GAMEPLAYABILITIES_API void SetServerDebugStrings (TArray< FString > &&NewServerDebugStrings)
GAMEPLAYABILITIES_API void SetSpawnedAttributes (const TArray< UAttributeSet * > &NewAttributeSet)
Remove all current AttributeSets and register the ones in the passed array.
GAMEPLAYABILITIES_API void SetSpawnedAttributesListDirty ()
FORCEINLINE void SetTagMapCount (const FGameplayTag &Tag, int32 NewCount)
Forcibly sets the number of instances of a given tag.
virtual bool ShouldDoServerAbilityRPCBatch () const
virtual GAMEPLAYABILITIES_API bool ShouldRecordMontageReplication () const
Returns true if this component should record montage replication info.
virtual GAMEPLAYABILITIES_API bool ShouldSendClientDebugStringsToServer () const
Determines whether to call ServerPrintDebug_Request or ServerPrintDebug_RequestWithStrings.
virtual GAMEPLAYABILITIES_API void StopMontageIfCurrent (const UAnimMontage &Montage, float OverrideBlendOutTime=-1.0f)
Stops current montage if it's the one given as the Montage param.
GAMEPLAYABILITIES_API bool TriggerAbilityFromGameplayEvent (FGameplayAbilitySpecHandle AbilityToTrigger, FGameplayAbilityActorInfo *ActorInfo, FGameplayTag Tag, const FGameplayEventData *Payload, UAbilitySystemComponent &Component)
Triggers an ability from a gameplay event, will only trigger on local/server depending on execution flags.
UE_DEPRECATED (4.26, "This will be made private in future engine versions. Use SetClientDebugStrings, GetClientDebugStrings, or GetClientDebugStrings_Mutable instead.") UPROPERTY() TArray< FString > ClientDebugStrings
UE_DEPRECATED (4.26, "This will be made private in future engine versions. Use SetServerDebugStrings, GetServerDebugStrings, or GetServerDebugStrings_Mutable instead.") UPROPERTY() TArray< FString > ServerDebugStrings
UE_DEPRECATED (5.1, "This function will be made private. Use Add/Remove SpawnedAttributes instead") GAMEPLAYABILITIES_API TArray< TObjectPtr< UAttributeSet > > &GetSpawnedAttributes_Mutable()
UE_DEPRECATED (5.3, "FindAbilitySpecFromGEHandle was never accurate because a GameplayEffect can grant multiple GameplayAbilities. It now returns nullptr.") GAMEPLAYABILITIES_API FGameplayAbilitySpec *FindAbilitySpecFromGEHandle(FActiveGameplayEffectHandle Handle) const
Returns an ability spec from a GE handle.
UE_DEPRECATED (5.4, "ReinvokeActiveGameplayCues was unused and had logic inconsistent with predicting Gameplay Effects. You can implement it in your own project if desired.") GAMEPLAYABILITIES_API virtual void ReinvokeActiveGameplayCues()
Invokes the WhileActive event for all GCs on active, non inhibited, GEs.
UE_DEPRECATED (5.4, "Use SetActiveGameplayEffectInhibit with a MoveTemp(ActiveGEHandle) so it's clear the Handle is no longer valid. Check (then use) the returned FActiveGameplayEffectHandle to continue your operation.") GAMEPLAYABILITIES_API virtual void InhibitActiveGameplayEffect(FActiveGameplayEffectHandle ActiveGEHandle
Inhibit an active gameplay effect so that it is disabled, but not removed.
UE_DEPRECATED_FORGAME (5.5, "This shouldn't be public. Use RemoveActiveGameplayEffect (which won't allow non-authority to remove) or expose RemoveActiveGameplayEffect_AllowClientRemoval if your intent is to break that contract.") GAMEPLAYABILITIES_API void RemoveActiveGameplayEffect_NoReturn(FActiveGameplayEffectHandle Handle
This only exists so it can be hooked up to a multicast delegate.
UFUNCTION () GAMEPLAYABILITIES_API bool GetUserAbilityActivationInhibited() const
This is meant to be used to inhibit activating an ability from an input perspective.
UFUNCTION () GAMEPLAYABILITIES_API bool TryActivateAbilitiesByTag(const FGameplayTagContainer &GameplayTagContainer
Attempts to activate every gameplay ability that matches the given tag and DoesAbilitySatisfyTagRequirements().
UFUNCTION () GAMEPLAYABILITIES_API bool TryActivateAbility(FGameplayAbilitySpecHandle AbilityToActivate
Attempts to activate the given ability, will check costs and requirements before doing so.
UFUNCTION () GAMEPLAYABILITIES_API bool TryActivateAbilityByClass(TSubclassOf< UGameplayAbility > InAbilityToActivate
Attempts to activate the ability that is passed in.
UFUNCTION () GAMEPLAYABILITIES_API float GetGameplayAttributeValue(FGameplayAttribute Attribute
Returns the current value of the given gameplay attribute, or zero if the attribute is not found.
UFUNCTION () GAMEPLAYABILITIES_API float GetGameplayEffectMagnitude(FActiveGameplayEffectHandle Handle
Raw accessor to ask the magnitude of a gameplay effect, not necessarily always correct.
UFUNCTION () GAMEPLAYABILITIES_API int32 GetGameplayEffectCount(TSubclassOf< UGameplayEffect > SourceGameplayEffect
Get the count of the specified source effect on the ability system component.
UFUNCTION () GAMEPLAYABILITIES_API int32 GetGameplayEffectCount_IfLoaded(TSoftClassPtr< UGameplayEffect > SoftSourceGameplayEffect
Get the count of the specified source effect on the ability system component.
UFUNCTION () GAMEPLAYABILITIES_API int32 GetGameplayTagCount(FGameplayTag GameplayTag) const
Returns the current count of the given gameplay tag.
UFUNCTION () GAMEPLAYABILITIES_API int32 RemoveActiveEffectsWithAppliedTags(FGameplayTagContainer Tags)
Removes all active effects that apply any of the tags in Tags.
UFUNCTION () GAMEPLAYABILITIES_API int32 RemoveActiveEffectsWithGrantedTags(FGameplayTagContainer Tags)
Removes all active effects that grant any of the tags in Tags.
UFUNCTION () GAMEPLAYABILITIES_API int32 RemoveActiveEffectsWithSourceTags(FGameplayTagContainer Tags)
Removes all active effects with captured source tags that contain any of the tags in Tags.
UFUNCTION () GAMEPLAYABILITIES_API int32 RemoveActiveEffectsWithTags(FGameplayTagContainer Tags)
Removes all active effects that contain any of the tags in Tags.
UFUNCTION () GAMEPLAYABILITIES_API TArray< FActiveGameplayEffectHandle > GetActiveEffectsWithAllTags(FGameplayTagContainer Tags) const
Returns list of active effects that have all of the passed in tags.
UFUNCTION () GAMEPLAYABILITIES_API virtual bool RemoveActiveGameplayEffect(FActiveGameplayEffectHandle Handle
Removes the specified GameplayEffect by Handle.
UFUNCTION () GAMEPLAYABILITIES_API virtual FGameplayEffectContextHandle MakeEffectContext() const
Create an EffectContext for the owner of this AbilitySystemComponent.
UFUNCTION () GAMEPLAYABILITIES_API virtual FGameplayEffectSpecHandle MakeOutgoingSpec(TSubclassOf< UGameplayEffect > GameplayEffectClass
Get an outgoing GameplayEffectSpec that is ready to be applied to other things.
UFUNCTION () GAMEPLAYABILITIES_API virtual void OnRep_ClientDebugString()
UFUNCTION () GAMEPLAYABILITIES_API virtual void OnRep_ServerDebugString()
UFUNCTION () GAMEPLAYABILITIES_API virtual void RemoveActiveGameplayEffectBySourceEffect(TSubclassOf< UGameplayEffect > GameplayEffect
Remove active gameplay effects whose backing definition are the specified gameplay effect class.
UFUNCTION () GAMEPLAYABILITIES_API virtual void SetActiveGameplayEffectLevel(FActiveGameplayEffectHandle ActiveHandle
Updates the level of an already applied gameplay effect.
UFUNCTION () GAMEPLAYABILITIES_API virtual void SetActiveGameplayEffectLevelUsingQuery(FGameplayEffectQuery Query
Updates the level of an already applied gameplay effect.
UFUNCTION () GAMEPLAYABILITIES_API virtual void SetUserAbilityActivationInhibited(bool NewInhibit)
Disable or Enable a local user from being able to activate abilities.
UFUNCTION () GAMEPLAYABILITIES_API virtual void TargetCancel()
Any active targeting actors will be stopped and canceled, not returning any targeting data.
UFUNCTION () GAMEPLAYABILITIES_API virtual void TargetConfirm()
Any active targeting actors will be told to stop and return current targeting data.
UFUNCTION () GAMEPLAYABILITIES_API virtual void UpdateActiveGameplayEffectSetByCallerMagnitude(FActiveGameplayEffectHandle ActiveHandle
Dynamically update the set-by-caller magnitude for an active gameplay effect.
UFUNCTION () GAMEPLAYABILITIES_API virtual void UpdateActiveGameplayEffectSetByCallerMagnitudes(FActiveGameplayEffectHandle ActiveHandle
Dynamically update multiple set-by-caller magnitudes for an active gameplay effect.
UFUNCTION () GAMEPLAYABILITIES_API void ClearAbility(const FGameplayAbilitySpecHandle &Handle)
Removes the specified ability.
UFUNCTION () GAMEPLAYABILITIES_API void ClearAllAbilities()
Wipes all 'given' abilities.
UFUNCTION () GAMEPLAYABILITIES_API void ClearAllAbilitiesWithInputID(int32 InputID=0)
Clears all abilities bound to a given Input ID This will be ignored if the actor is not authoritative.
UFUNCTION () GAMEPLAYABILITIES_API void ClientPrintDebug_Response(const TArray< FString > &Strings
UFUNCTION () GAMEPLAYABILITIES_API void FindAllAbilitiesMatchingQuery(TArray< FGameplayAbilitySpecHandle > &OutAbilityHandles
Returns an array with all abilities that match the provided Gameplay Tag Query.
UFUNCTION () GAMEPLAYABILITIES_API void FindAllAbilitiesWithInputID(TArray< FGameplayAbilitySpecHandle > &OutAbilityHandles
Returns an array with all abilities bound to an Input ID value.
UFUNCTION () GAMEPLAYABILITIES_API void FindAllAbilitiesWithTags(TArray< FGameplayAbilitySpecHandle > &OutAbilityHandles
Returns an array with all abilities that match the provided tags.
UFUNCTION () GAMEPLAYABILITIES_API void GetAllAbilities(TArray< FGameplayAbilitySpecHandle > &OutAbilityHandles) const
Returns an array with all granted ability handles NOTE: currently this doesn't include abilities that are mid-activation.
UFUNCTION () GAMEPLAYABILITIES_API void GetAllAttributes(TArray< FGameplayAttribute > &OutAttributes)
Returns a list of all attributes for this abilty system component.
UFUNCTION () GAMEPLAYABILITIES_API void InputCancel()
Sends a local player Input Cancel event, notifying abilities.
UFUNCTION () GAMEPLAYABILITIES_API void InputConfirm()
Sends a local player Input Confirm event, notifying abilities.
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCueAdded(const FGameplayTag GameplayCueTag
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCueAdded_WithParams(const FGameplayTag GameplayCueTag
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCueAddedAndWhileActive_FromSpec(const FGameplayEffectSpecForRPC &Spec
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCueAddedAndWhileActive_WithParams(const FGameplayTag GameplayCueTag
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCueExecuted(const FGameplayTag GameplayCueTag
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCueExecuted_FromSpec(const FGameplayEffectSpecForRPC Spec
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCueExecuted_WithParams(const FGameplayTag GameplayCueTag
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCuesAddedAndWhileActive_WithParams(const FGameplayTagContainer GameplayCueTags
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCuesExecuted(const FGameplayTagContainer GameplayCueTags
UFUNCTION () GAMEPLAYABILITIES_API void NetMulticast_InvokeGameplayCuesExecuted_WithParams(const FGameplayTagContainer GameplayCueTags
UFUNCTION () GAMEPLAYABILITIES_API void OnRep_SpawnedAttributes(const TArray< UAttributeSet * > &PreviousSpawnedAttributes)
UFUNCTION () GAMEPLAYABILITIES_API void PressInputID(int32 InputID)
UFUNCTION () GAMEPLAYABILITIES_API void ReleaseInputID(int32 InputID)
Sends a local player Input Released event with the provided Input ID, notifying any bound abilities.
UFUNCTION () GAMEPLAYABILITIES_API void ServerAbilityRPCBatch(FServerAbilityRPCBatch BatchInfo)
UFUNCTION () GAMEPLAYABILITIES_API void ServerPrintDebug_Request()
Ask the server to send ability system debug information back to the client, via ClientPrintDebug_Response.
UFUNCTION () GAMEPLAYABILITIES_API void ServerPrintDebug_RequestWithStrings(const TArray< FString > &Strings)
Same as ServerPrintDebug_Request but this includes the client debug strings so that the server can embed them in replays.
UFUNCTION ()) bool IsGameplayCueActive(const FGameplayTag GameplayCueTag) const
Allows polling to see if a GameplayCue is active.
UFUNCTION ()) GAMEPLAYABILITIES_API const UAttributeSet *GetAttributeSet(TSubclassOf< UAttributeSet > AttributeSetClass) const
Returns a reference to the Attribute Set instance, if one exists in this component.
UFUNCTION ()) GAMEPLAYABILITIES_API FActiveGameplayEffectHandle BP_ApplyGameplayEffectSpecToSelf(const FGameplayEffectSpecHandle &SpecHandle)
Applies a previously created gameplay effect spec to this component.
UFUNCTION ()) GAMEPLAYABILITIES_API FActiveGameplayEffectHandle BP_ApplyGameplayEffectSpecToTarget(const FGameplayEffectSpecHandle &SpecHandle
Applies a previously created gameplay effect spec to a target.
UFUNCTION ()) GAMEPLAYABILITIES_API FActiveGameplayEffectHandle BP_ApplyGameplayEffectToSelf(TSubclassOf< UGameplayEffect > GameplayEffectClass
Apply a gameplay effect to self.
UFUNCTION ()) GAMEPLAYABILITIES_API FActiveGameplayEffectHandle BP_ApplyGameplayEffectToTarget(TSubclassOf< UGameplayEffect > GameplayEffectClass
Apply a gameplay effect to passed in target.
UFUNCTION ()) GAMEPLAYABILITIES_API FGameplayAbilitySpecHandle K2_GiveAbility(TSubclassOf< UGameplayAbility > AbilityClass
Grants a Gameplay Ability and returns its handle.
UFUNCTION ()) GAMEPLAYABILITIES_API FGameplayAbilitySpecHandle K2_GiveAbilityAndActivateOnce(TSubclassOf< UGameplayAbility > AbilityClass
Grants a Gameplay Ability, activates it once, and removes it.
UFUNCTION ()) GAMEPLAYABILITIES_API TArray< FActiveGameplayEffectHandle > GetActiveEffects(const FGameplayEffectQuery &Query) const
Returns list of active effects, for a query.
UFUNCTION ()) GAMEPLAYABILITIES_API void K2_InitStats(TSubclassOf< class UAttributeSet > Attributes
GAMEPLAYABILITIES_API void UnBlockAbilitiesWithTags (const FGameplayTagContainer &Tags)
GAMEPLAYABILITIES_API void UnBlockAbilityByInputID (int32 InputID)
GAMEPLAYABILITIES_API bool UnregisterGameplayTagEvent (FDelegateHandle DelegateHandle, FGameplayTag Tag, EGameplayTagEventType::Type EventType=EGameplayTagEventType::NewOrRemoved)
Unregister previously added events.
UPARAM (meta=(Categories="SetByCaller")) FGameplayTag SetByCallerTag
FORCEINLINE void UpdateTagMap (const FGameplayTag &BaseTag, int32 CountDelta)
Update the number of instances of a given tag and calls callback.
FORCEINLINE void UpdateTagMap (const FGameplayTagContainer &Container, int32 CountDelta)
Update the number of instances of a given tag and calls callback.
UPROPERTY () bool bSuppressGameplayCues
Suppress all GameplayCues on this component.
UPROPERTY () bool bSuppressGrantAbility
Suppress all ability granting through GEs on this component.
UPROPERTY () bool ReplicationProxyEnabled
When enabled GameplayCue RPCs will be routed through the AvatarActor's IAbilitySystemReplicationProxyInterface rather than this component.
UPROPERTY () bool UserAbilityActivationInhibited
Rather activation is currently inhibited.
UPROPERTY () FMinimalReplicationTagCountMap ReplicatedLooseTags
Container used for replicating loose gameplay tags.
UPROPERTY () FName AffectedAnimInstanceTag
The linked Anim Instance that this component will play montages in.
UPROPERTY () TArray< FAttributeDefaults > DefaultStartingData
UPROPERTY () TArray< TObjectPtr< AGameplayAbilityTargetActor > > SpawnedTargetActors
List of currently active targeting actors.
UPROPERTY () TArray< TObjectPtr< UAttributeSet > > SpawnedAttributes
List of attribute sets.
UPROPERTY () TObjectPtr< AActor > AvatarActor
The actor that is the physical representation used for abilities.
UPROPERTY () TObjectPtr< AActor > OwnerActor
The actor that owns this component logically.
UPROPERTY ()) float IncomingDuration
Internal Attribute that modifies the duration of gameplay effects applied to this component.
UPROPERTY ()) float OutgoingDuration
Internal Attribute that modifies the duration of gameplay effects created by this component.
Static Private Member Functions
static GAMEPLAYABILITIES_API const FGameplayEffectAttributeCaptureDefinition & GetIncomingDurationCapture ()
static GAMEPLAYABILITIES_API FProperty * GetIncomingDurationProperty ()
static GAMEPLAYABILITIES_API const FGameplayEffectAttributeCaptureDefinition & GetOutgoingDurationCapture ()
static GAMEPLAYABILITIES_API FProperty * GetOutgoingDurationProperty ()
static GAMEPLAYABILITIES_API void OnShowDebugInfo (AHUD *HUD, UCanvas *Canvas, const FDebugDisplayInfo &DisplayInfo, float &YL, float &YPos)
Private Attributes
FGenericAbilityDelegate AbilityActivatedCallbacks
A generic callback anytime an ability is activated (started)
FGenericAbilityDelegate AbilityCommittedCallbacks
A generic callback anytime an ability is committed (cost/cooldown applied)
FAbilityEnded AbilityEndedCallbacks
Callback anytime an ability is ended.
FAbilityFailedDelegate AbilityFailedCallbacks
Called with a failure reason when an ability fails to activate.
FAbilitySpecDirtied AbilitySpecDirtiedCallbacks
Called when an ability spec's internals have changed.
bool bAllowRemoteActivation = true)
uint8 bDestroyActiveStateInitiated: 1
UAbilitySystemComponent bool bEnforceOnGoingCheck = true) const
FGameplayTagContainer bool bExactMatch = true) const
bool bInhibit
bool bool bInvokeGameplayCueEvents
bool &bFound const
float FGameplayEffectContextHandle Context const
FGameplayAttribute Attribute const
FGameplayTagQuery Query const
UAbilitySystemComponent float FGameplayEffectContextHandle Context
const UDataTable * DataTable
float FGameplayEffectContextHandle EffectContext
int32 GameFlags
TArray< FGameplayEffectApplicationQuery > GameplayEffectApplicationQueries
We allow users to setup a series of functions that must be true in order to allow a GameplayEffect to be applied.
int32 GenericCancelInputID
int32 GenericConfirmInputID
InputID for binding GenericConfirm/Cancel events.
TMap< FGameplayTag, FGameplayEventMulticastDelegate > GenericGameplayEventCallbacks
Callbacks bound to Gameplay tags, these only activate if the exact tag is used.
FAbilityConfirmOrCancel GenericLocalCancelCallbacks
Generic local callback for generic CancelEvent that any ability can listen to.
FAbilityConfirmOrCancel GenericLocalConfirmCallbacks
Generic local callback for generic ConfirmEvent that any ability can listen to.
InputID = -1)
int32 int32 InputID = -1)
int32 InputID = 0) const
UAbilitySystemComponent * InstigatorAbilitySystemComponent
int32
FGameplayTagContainer InternalTryActivateAbilityFailureTags
Failure tags used by InternalTryActivateAbility (E.g., this stores the FailureTags of the last call to InternalTryActivateAbility.
float Level = 0
UAbilitySystemComponent float Level
int32 Level = 0
TArray< FServerAbilityRPCBatch, TInlineAllocator< 1 > > LocalServerAbilityRPCBatchData
Accumulated client side data that is batched out to server on EndServerAbilityRPCBatch.
FDelegateHandle MonitoredTagChangedDelegateHandle
int32 NewLevel
const TMap< FGameplayTag, float > & NewSetByCallerValues
float NewValue
FGameplayAbilityEndedDelegate OnAbilityEnded
Callback anytime an ability is ended, with extra information.
FOnGameplayEffectAppliedDelegate OnActiveGameplayEffectAddedDelegateToSelf
Called on both client and server whenever a duration based GE is added (E.g., instant GEs do not trigger this).
FOnGameplayEffectAppliedDelegate OnGameplayEffectAppliedDelegateToSelf
Called on server whenever a GE is applied to self.
FOnGameplayEffectAppliedDelegate OnGameplayEffectAppliedDelegateToTarget
Called on server whenever a GE is applied to someone else.
FImmunityBlockGE OnImmunityBlockGameplayEffectDelegate
Immunity notification support.
FOnGameplayEffectAppliedDelegate OnPeriodicGameplayEffectExecuteDelegateOnSelf
Called on server whenever a periodic GE executes on self.
FOnGameplayEffectAppliedDelegate OnPeriodicGameplayEffectExecuteDelegateOnTarget
Called on server whenever a periodic GE executes on target.
FTimerHandle OnRep_ActivateAbilitiesTimerHandle
UAbilitySystemComponent * OptionalInstigatorFilterComponent
FPredictionKey PredictionKey override
FPredictionKey FGameplayEffectContextHandle EffectContext override
FPredictionKey FGameplayCueParameters GameplayCueParameters override
FPredictionKey FGameplayCueParameters Parameters override
TArray< FPendingAbilityInfo > PendingServerActivatedAbilities
This is a list of GameplayAbilities that were activated on the server and can't yet execute on the client.
FPredictionKey PredictionKey
EGameplayEffectReplicationMode ReplicationMode
How gameplay effects are replicated.
FPredictionKey ScopedPredictionKey
Current prediction key, set with FScopedPredictionWindow.
int32 StacksToRemove =-1)
UAbilitySystemComponent int32 StacksToRemove = -1)
FGameplayTagContainer Tags
UAbilitySystemComponent * Target
Friends
class AAbilitySystemDebugHUD
struct FActiveGameplayCue
struct FActiveGameplayCueContainer
struct FActiveGameplayEffect
struct FActiveGameplayEffectAction
struct FActiveGameplayEffectAction_Add
struct FActiveGameplayEffectsContainer
struct FAggregator
struct FGameplayAbilitySpec
struct FGameplayAbilitySpecContainer
struct FGameplayEffectSpec
class UAbilitySystemGlobals
Additional Inherited Members
Public Types inherited from UGameplayTasksComponent
using GameplayTaskContainerType = decltype(TickingTasks)
Public Types inherited from UObject
enum class ENetFields_Private { NETFIELD_REP_START = 0 , NETFIELD_REP_END = -1 }
using FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Static Public Member Functions inherited from UGameplayTasksComponent
static GAMEPLAYTASKS_API FString GetTaskStateName (EGameplayTaskState Value)
static GAMEPLAYTASKS_API EGameplayTaskRunResult RunGameplayTask (IGameplayTaskOwnerInterface &TaskOwner, UGameplayTask &Task, uint8 Priority, FGameplayResourceSet AdditionalRequiredResources, FGameplayResourceSet AdditionalClaimedResources)
Static Public Member Functions inherited from UActorComponent
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Static Public Member Functions inherited from UObject
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Callback used to allow object register its direct object references that are not already covered by the token stream.
static bool CanCreateInCurrentContext (UObject *Template)
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
static UObject * GetArchetypeFromRequiredInfo (const UClass *Class, const UObject *Outer, FName Name, EObjectFlags ObjectFlags)
Return the template that an object with this class, outer and name would be.
static TSet< FName > & GetMetaDataTagsForAssetRegistry ()
The metadata tags to be transferred from the FMetaData to the Asset Registry.
static const FName & SourceFileTagName ()
Get the common tag name used for all asset source file import paths.
static void UpdateClassesExcludedFromDedicatedClient (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated client builds.
static void UpdateClassesExcludedFromDedicatedServer (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated server builds.
Static Public Member Functions inherited from UObjectBaseUtility
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Static Public Attributes inherited from UActorComponent
static TMap< UActorComponent *, TArray< FSimpleMemberReference > > AllUCSModifiedProperties
static FTransactionallySafeRWLock AllUCSModifiedPropertiesLock
static const FString ComponentTemplateNameSuffix
Suffix used to identify template component instances.
static FOnMarkRenderStateDirty MarkRenderStateDirtyEvent
Called When render state is marked dirty.
Static Public Attributes inherited from UObject
static FOnGetPreviewPlatform OnGetPreviewPlatform
Protected Types inherited from UActorComponent
enum class EComponentRegistrationState {
None , PreRegistering , PreRegistered , PreUnregistering ,
PreUnregistered
}
Protected Types inherited from UObject
enum class ETransactionAnnotationCreationMode : uint8 { DefaultInstance , FindOrCreate }
Factory a new annotation object and optionally populate it with data.
Static Protected Member Functions inherited from UActorComponent
static bool CanBeHLODRelevant (const UActorComponent *ActorComponent)
Utility method used by subclasses to test basic conditions a component must fulfill to be considered HLOD relevant.
static const FName GetReplicatesPropertyName ()
Gets the property name for bReplicates.
Detailed Description
Definition at line 109 of file AbilitySystemComponent.h.
Member Function Documentation
AbilityLocalInputPressed()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::AbilityLocalInputPressed (int32 InputID) private virtual
Called to handle ability bind input.
References AbilityLocalInputPressed(), InputID, int32, and UE_API.
Referenced by AbilityLocalInputPressed().
AbilityLocalInputReleased()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::AbilityLocalInputReleased (int32 InputID) private virtual
References AbilityLocalInputReleased(), InputID, int32, and UE_API.
Referenced by AbilityLocalInputReleased().
AbilityReplicatedEventDelegate()
GAMEPLAYABILITIES_API FSimpleMulticastDelegate & UAbilitySystemComponent::AbilityReplicatedEventDelegate (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Returns Generic Replicated Event for a given Ability/PredictionKey pair.
References AbilityOriginalPredictionKey, AbilityReplicatedEventDelegate(), and UE_API.
Referenced by AbilityReplicatedEventDelegate().
AbilitySpecInputPressed()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::AbilitySpecInputPressed (FGameplayAbilitySpec & Spec) virtual
Called on local player always.
Called on server only if bReplicateInputDirectly is set on the GameplayAbility.
References AbilitySpecInputPressed(), FGameplayAbilitySpec, and UE_API.
Referenced by AbilitySpecInputPressed().
AbilitySpecInputReleased()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::AbilitySpecInputReleased (FGameplayAbilitySpec & Spec) virtual
Called on local player always.
Called on server only if bReplicateInputDirectly is set on the GameplayAbility.
References AbilitySpecInputReleased(), FGameplayAbilitySpec, and UE_API.
Referenced by AbilitySpecInputReleased().
AbilityTargetDataCancelledDelegate()
GAMEPLAYABILITIES_API FSimpleMulticastDelegate & UAbilitySystemComponent::AbilityTargetDataCancelledDelegate (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Returns TargetData Cancelled delegate for a given Ability/PredictionKey pair.
References AbilityOriginalPredictionKey, AbilityTargetDataCancelledDelegate(), and UE_API.
Referenced by AbilityTargetDataCancelledDelegate().
AbilityTargetDataSetDelegate()
GAMEPLAYABILITIES_API FAbilityTargetDataSetDelegate & UAbilitySystemComponent::AbilityTargetDataSetDelegate (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Returns TargetDataSet delegate for a given Ability/PredictionKey pair.
References AbilityOriginalPredictionKey, AbilityTargetDataSetDelegate(), and UE_API.
Referenced by AbilityTargetDataSetDelegate().
AccumulateScreenPos()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AccumulateScreenPos (FAbilitySystemComponentDebugInfo & Info) private
References Info, and UE_API.
AddAttributeSetSubobject()
template<class T> const T * UAbilitySystemComponent::AddAttributeSetSubobject (T * Subobject) inline private
Manually add a new attribute set that is a subobject of this ability system component.
All subobjects of this component are automatically added during initialization.
Definition at line 152 of file AbilitySystemComponent.h.
References AddSpawnedAttribute().
AddGameplayCue() [1/2]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AddGameplayCue (const FGameplayTag GameplayCueTag, const FGameplayCueParameters & GameplayCueParameters) private
References AddGameplayCue(), const, and UE_API.
AddGameplayCue() [2/2]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AddGameplayCue (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle EffectContext = FGameplayEffectContextHandle()) private
Add a persistent gameplay cue.
References AddGameplayCue(), const, EffectContext, and UE_API.
Referenced by AddGameplayCue(), and AddGameplayCue().
AddGameplayCue_Internal() [1/2]
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::AddGameplayCue_Internal (const FGameplayTag GameplayCueTag, const FGameplayCueParameters & GameplayCueParameters, FActiveGameplayCueContainer & GameplayCueContainer) protected virtual
References AddGameplayCue_Internal(), const, FActiveGameplayCueContainer, and UE_API.
AddGameplayCue_Internal() [2/2]
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::AddGameplayCue_Internal (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle & EffectContext, FActiveGameplayCueContainer & GameplayCueContainer) protected virtual
References AddGameplayCue_Internal(), const, EffectContext, FActiveGameplayCueContainer, and UE_API.
Referenced by AddGameplayCue_Internal(), and AddGameplayCue_Internal().
AddGameplayCue_MinimalReplication()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AddGameplayCue_MinimalReplication (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle EffectContext = FGameplayEffectContextHandle()) private
Add gameplaycue for minimal replication mode.
Should only be called in paths that would replicate gameplaycues in other ways (through GE for example) if not in minimal replication mode
References AddGameplayCue_MinimalReplication(), const, EffectContext, and UE_API.
Referenced by AddGameplayCue_MinimalReplication().
AddGameplayEventTagContainerDelegate()
GAMEPLAYABILITIES_API FDelegateHandle UAbilitySystemComponent::AddGameplayEventTagContainerDelegate (const FGameplayTagContainer & TagFilter, const FGameplayEventTagMulticastDelegate::FDelegate & Delegate) private
Adds a new delegate to call when gameplay events happen.
It will only be called if it matches any tags in passed filter container
References UE_API.
AddLooseGameplayTag()
FORCEINLINE void UAbilitySystemComponent::AddLooseGameplayTag (const FGameplayTag & GameplayTag, int32 Count = 1) inline private
Allows GameCode to add loose gameplaytags which are not backed by a GameplayEffect.
Tags added this way are not replicated! Use the 'Replicated' versions of these functions if replication is needed. It is up to the calling GameCode to make sure these tags are added on clients/server where necessary
Definition at line 654 of file AbilitySystemComponent.h.
References Count, FORCEINLINE, int32, and UpdateTagMap().
AddLooseGameplayTags()
FORCEINLINE void UAbilitySystemComponent::AddLooseGameplayTags (const FGameplayTagContainer & GameplayTags, int32 Count = 1) inline private
Definition at line 659 of file AbilitySystemComponent.h.
References Count, FORCEINLINE, GameplayTags, int32, and UpdateTagMap().
AddMinimalReplicationGameplayTag()
FORCEINLINE void UAbilitySystemComponent::AddMinimalReplicationGameplayTag (const FGameplayTag & GameplayTag) inline private
Minimally replicated tags are replicated tags that come from GEs when in bMinimalReplication mode.
(The GEs do not replicate, but the tags they grant do replicate via these functions)
Definition at line 723 of file AbilitySystemComponent.h.
References FORCEINLINE, and GetMinimalReplicationTags_Mutable().
AddMinimalReplicationGameplayTags()
FORCEINLINE void UAbilitySystemComponent::AddMinimalReplicationGameplayTags (const FGameplayTagContainer & GameplayTags) inline private
Definition at line 728 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTags, and GetMinimalReplicationTags_Mutable().
AddReplicatedInstancedAbility()
GAMEPLAYABILITIES_API PRAGMA_ENABLE_DEPRECATION_WARNINGS void UAbilitySystemComponent::AddReplicatedInstancedAbility (UGameplayAbility * GameplayAbility) protected
Add a gameplay ability associated to this component.
AddReplicatedLooseGameplayTag()
FORCEINLINE void UAbilitySystemComponent::AddReplicatedLooseGameplayTag (const FGameplayTag & GameplayTag) inline private
Allows GameCode to add loose gameplaytags which are not backed by a GameplayEffect.
Tags added using these functions will be replicated. Note that replicated loose tags will override any locally-set tag counts on simulated proxies.
Definition at line 694 of file AbilitySystemComponent.h.
References AddReplicatedLooseGameplayTag(), const, FORCEINLINE, and GetReplicatedLooseTags_Mutable().
Referenced by AddReplicatedLooseGameplayTag().
AddReplicatedLooseGameplayTags()
FORCEINLINE void UAbilitySystemComponent::AddReplicatedLooseGameplayTags (const FGameplayTagContainer & GameplayTags) inline private
Definition at line 699 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTags, and GetReplicatedLooseTags_Mutable().
AddSet()
template<class T> const T * UAbilitySystemComponent::AddSet () inline private
Adds a new AttributeSet (initialized to default values)
Definition at line 142 of file AbilitySystemComponent.h.
References GetOrCreateAttributeSubobject().
AddSpawnedAttribute()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AddSpawnedAttribute (UAttributeSet * Attribute) private
Add a new attribute set.
References AddSpawnedAttribute(), Attribute, and UE_API.
Referenced by AddAttributeSetSubobject(), and AddSpawnedAttribute().
AnimMontage_UpdateForcedPlayFlags()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AnimMontage_UpdateForcedPlayFlags (FGameplayAbilityRepAnimMontage & OutRepAnimMontageInfo) protected
Copy over playing flags for duplicate animation data.
References AnimMontage_UpdateForcedPlayFlags(), and UE_API.
Referenced by AnimMontage_UpdateForcedPlayFlags().
AnimMontage_UpdateReplicatedData() [1/2]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AnimMontage_UpdateReplicatedData () protected
Copy LocalAnimMontageInfo into RepAnimMontageInfo.
References AnimMontage_UpdateReplicatedData(), and UE_API.
Referenced by AnimMontage_UpdateReplicatedData(), and AnimMontage_UpdateReplicatedData().
AnimMontage_UpdateReplicatedData() [2/2]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::AnimMontage_UpdateReplicatedData (FGameplayAbilityRepAnimMontage & OutRepAnimMontageInfo) protected
References AnimMontage_UpdateReplicatedData(), and UE_API.
ApplyAbilityBlockAndCancelTags()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ApplyAbilityBlockAndCancelTags (const FGameplayTagContainer & AbilityTags, UGameplayAbility * RequestingAbility, bool bEnableBlockTags, const FGameplayTagContainer & BlockTags, bool bExecuteCancelTags, const FGameplayTagContainer & CancelTags) private virtual
Called from ability activation or native code, will apply the correct ability blocking tags and cancel existing abilities.
Subclasses can override the behavior
Parameters
AbilityTags The tags of the ability that has block and cancel flags
RequestingAbility The gameplay ability requesting the change, can be NULL for native events
bEnableBlockTags If true will enable the block tags, if false will disable the block tags
BlockTags What tags to block
bExecuteCancelTags If true will cancel abilities matching tags
CancelTags what tags to cancel
References ApplyAbilityBlockAndCancelTags(), const, and UE_API.
Referenced by ApplyAbilityBlockAndCancelTags().
ApplyGameplayEffectSpecToSelf()
virtual GAMEPLAYABILITIES_API FActiveGameplayEffectHandle UAbilitySystemComponent::ApplyGameplayEffectSpecToSelf (const FGameplayEffectSpec & GameplayEffect, FPredictionKey PredictionKey = FPredictionKey()) private virtual
References ApplyGameplayEffectSpecToSelf(), const, FGameplayEffectSpec, PredictionKey, and UE_API.
Referenced by ApplyGameplayEffectSpecToSelf().
ApplyGameplayEffectSpecToTarget()
virtual GAMEPLAYABILITIES_API FActiveGameplayEffectHandle UAbilitySystemComponent::ApplyGameplayEffectSpecToTarget (const FGameplayEffectSpec & GameplayEffect, UAbilitySystemComponent * Target, FPredictionKey PredictionKey = FPredictionKey()) private virtual
References ApplyGameplayEffectSpecToTarget(), const, FGameplayEffectSpec, PredictionKey, Target, and UE_API.
Referenced by ApplyGameplayEffectSpecToTarget().
ApplyGameplayEffectToSelf()
GAMEPLAYABILITIES_API FActiveGameplayEffectHandle UAbilitySystemComponent::ApplyGameplayEffectToSelf (const UGameplayEffect * GameplayEffect, float Level, const FGameplayEffectContextHandle & EffectContext, FPredictionKey PredictionKey = FPredictionKey()) private
References ApplyGameplayEffectToSelf(), const, EffectContext, Level, PredictionKey, and UE_API.
Referenced by ApplyGameplayEffectToSelf().
ApplyGameplayEffectToTarget()
GAMEPLAYABILITIES_API FActiveGameplayEffectHandle UAbilitySystemComponent::ApplyGameplayEffectToTarget (UGameplayEffect * GameplayEffect, UAbilitySystemComponent * Target, float Level = UGameplayEffect::INVALID_LEVEL, FGameplayEffectContextHandle Context = FGameplayEffectContextHandle(), FPredictionKey PredictionKey = FPredictionKey()) private
References ApplyGameplayEffectToTarget(), Context, Level, PredictionKey, Target, and UE_API.
Referenced by ApplyGameplayEffectToTarget().
ApplyModToAttribute()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ApplyModToAttribute (const FGameplayAttribute & Attribute, TEnumAsByte< EGameplayModOp::Type > ModifierOp, float ModifierMagnitude) private
Applies an in-place mod to the given attribute.
This correctly update the attribute's aggregator, updates the attribute set property, and invokes the OnDirty callbacks. This does not invoke Pre/PostGameplayEffectExecute calls on the attribute set. This does no tag checking, application requirements, immunity, etc. No GameplayEffectSpec is created or is applied! This should only be used in cases where applying a real GameplayEffectSpec is too slow or not possible.
References ApplyModToAttribute(), Attribute, const, and UE_API.
Referenced by ApplyModToAttribute().
ApplyModToAttributeUnsafe()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ApplyModToAttributeUnsafe (const FGameplayAttribute & Attribute, TEnumAsByte< EGameplayModOp::Type > ModifierOp, float ModifierMagnitude) private
Applies an inplace mod to the given attribute.
Unlike ApplyModToAttribute this function will run on the client or server. This may result in problems related to prediction and will not roll back properly.
References ApplyModToAttributeUnsafe(), Attribute, const, and UE_API.
Referenced by ApplyModToAttributeUnsafe().
AreAbilityTagsBlocked()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::AreAbilityTagsBlocked (const FGameplayTagContainer & Tags) const private virtual
Returns true if any passed in tags are blocked.
References Tags, and UE_API.
BeginPlay()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::BeginPlay () override virtual
Begins Play for the component.
Called when the owning Actor begins play or when the component is created if the Actor has already begun play. Actor BeginPlay normally happens right after PostInitializeComponents but can be delayed for networked or child actors. Requires component to be registered and initialized.
Reimplemented from UActorComponent.
References BeginPlay(), override, and UE_API.
Referenced by BeginPlay().
BeginServerAbilityRPCBatch()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::BeginServerAbilityRPCBatch (FGameplayAbilitySpecHandle AbilityHandle) private virtual
References UE_API.
BindAbilityActivationToInputComponent()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::BindAbilityActivationToInputComponent (UInputComponent * InputComponent, FGameplayAbilityInputBinds BindInfo) private virtual
Bind to an input component with customized bindings.
References BindAbilityActivationToInputComponent(), and UE_API.
Referenced by BindAbilityActivationToInputComponent().
BindToInputComponent()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::BindToInputComponent (UInputComponent * InputComponent) private virtual
Bind to an input component with some default action names.
References BindToInputComponent(), and UE_API.
Referenced by BindToInputComponent().
BlockAbilitiesWithTags()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::BlockAbilitiesWithTags (const FGameplayTagContainer & Tags) private
Block or cancel blocking for specific ability tags.
References Tags, and UE_API.
BlockAbilityByInputID()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::BlockAbilityByInputID (int32 InputID) private
Block or cancel blocking for specific input IDs.
References InputID, int32, and UE_API.
BuildAbilitySpecFromClass()
virtual GAMEPLAYABILITIES_API FGameplayAbilitySpec UAbilitySystemComponent::BuildAbilitySpecFromClass (TSubclassOf< UGameplayAbility > AbilityClass, int32 Level = 0, int32 InputID = -1) private virtual
Build a simple FGameplayAbilitySpec from class, level and optional Input ID.
References BuildAbilitySpecFromClass(), FGameplayAbilitySpec, InputID, int32, Level, and UE_API.
Referenced by BuildAbilitySpecFromClass().
CacheIsNetSimulated()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CacheIsNetSimulated ()
Caches the flags that indicate whether this component has network authority.
References CacheIsNetSimulated(), and UE_API.
Referenced by CacheIsNetSimulated().
CallAllReplicatedDelegatesIfSet()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CallAllReplicatedDelegatesIfSet (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Calls any Replicated delegates that have been sent (TargetData or Generic Replicated Events).
Note this can be dangerous if multiple places in an ability register events and then call this function.
References AbilityOriginalPredictionKey, CallAllReplicatedDelegatesIfSet(), and UE_API.
Referenced by CallAllReplicatedDelegatesIfSet().
CallOrAddReplicatedDelegate()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::CallOrAddReplicatedDelegate (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, FSimpleMulticastDelegate::FDelegate Delegate)
Calls passed in delegate if the Client Event has already been sent.
If not, it adds the delegate to our multicast callback that will fire when it does.
References AbilityOriginalPredictionKey, CallOrAddReplicatedDelegate(), and UE_API.
Referenced by CallOrAddReplicatedDelegate().
CallReplicatedEventDelegateIfSet()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::CallReplicatedEventDelegateIfSet (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Calls a given Generic Replicated Event delegate if the event has already been sent.
References AbilityOriginalPredictionKey, CallReplicatedEventDelegateIfSet(), and UE_API.
Referenced by CallReplicatedEventDelegateIfSet().
CallReplicatedTargetDataDelegatesIfSet()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::CallReplicatedTargetDataDelegatesIfSet (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Calls the TargetData Confirm/Cancel events if they have been sent.
References AbilityOriginalPredictionKey, CallReplicatedTargetDataDelegatesIfSet(), and UE_API.
Referenced by CallReplicatedTargetDataDelegatesIfSet().
CallServerEndAbility()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CallServerEndAbility (FGameplayAbilitySpecHandle AbilityToEnd, FGameplayAbilityActivationInfo ActivationInfo, FPredictionKey PredictionKey) private
References ActivationInfo, CallServerEndAbility(), PredictionKey, and UE_API.
Referenced by CallServerEndAbility().
CallServerSetReplicatedTargetData()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CallServerSetReplicatedTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, const FGameplayAbilityTargetDataHandle & ReplicatedTargetDataHandle, FGameplayTag ApplicationTag, FPredictionKey CurrentPredictionKey) private
References AbilityOriginalPredictionKey, ApplicationTag, CallServerSetReplicatedTargetData(), const, CurrentPredictionKey, ReplicatedTargetDataHandle, and UE_API.
Referenced by CallServerSetReplicatedTargetData().
CallServerTryActivateAbility()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CallServerTryActivateAbility (FGameplayAbilitySpecHandle AbilityToActivate, bool InputPressed, FPredictionKey PredictionKey) private
References CallServerTryActivateAbility(), InputPressed, PredictionKey, and UE_API.
Referenced by CallServerTryActivateAbility().
CanApplyAttributeModifiers()
bool UAbilitySystemComponent::CanApplyAttributeModifiers (const UGameplayEffect * GameplayEffect, float Level, const FGameplayEffectContextHandle & EffectContext) inline private
Tests if all modifiers in this GameplayEffect will leave the attribute > 0.f.
Definition at line 824 of file AbilitySystemComponent.h.
References EffectContext, and Level.
CancelAbilities()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CancelAbilities (const FGameplayTagContainer * WithTags = nullptr, const FGameplayTagContainer * WithoutTags = nullptr, UGameplayAbility * Ignore = nullptr) private
Cancel all abilities with the specified tags.
Will not cancel the Ignore instance
References CancelAbilities(), const, Ignore, and UE_API.
Referenced by CancelAbilities().
CancelAbility()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CancelAbility (UGameplayAbility * Ability) private
Cancels the specified ability CDO.
References CancelAbility(), and UE_API.
Referenced by CancelAbility().
CancelAbilityHandle()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CancelAbilityHandle (const FGameplayAbilitySpecHandle & AbilityHandle) private
Cancels the ability indicated by passed in spec handle.
If handle is not found among reactivated abilities nothing happens.
References CancelAbilityHandle(), const, and UE_API.
Referenced by CancelAbilityHandle().
CancelAbilitySpec()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::CancelAbilitySpec (FGameplayAbilitySpec & Spec, UGameplayAbility * Ignore) protected virtual
Cancel a specific ability spec.
References FGameplayAbilitySpec, Ignore, and UE_API.
CancelAbilityTargetData()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::CancelAbilityTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey) virtual
Cancels the ability target data and calls callbacks.
References AbilityOriginalPredictionKey, CancelAbilityTargetData(), and UE_API.
Referenced by CancelAbilityTargetData().
CancelAllAbilities()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CancelAllAbilities (UGameplayAbility * Ignore = nullptr) private
Cancels all abilities regardless of tags.
Will not cancel the ignore instance
References CancelAllAbilities(), Ignore, and UE_API.
Referenced by CancelAllAbilities().
CanPredict()
bool UAbilitySystemComponent::CanPredict () const inline private
Do we have a valid prediction key to do more predictive actions with.
Definition at line 277 of file AbilitySystemComponent.h.
References ScopedPredictionKey.
CaptureAttributeForGameplayEffect()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CaptureAttributeForGameplayEffect (OUT FGameplayEffectAttributeCaptureSpec & OutCaptureSpec) private
Populate the specified capture spec with the data necessary to capture an attribute from the component.
Parameters
OutCaptureSpec [OUT] Capture spec to populate with captured data
References CaptureAttributeForGameplayEffect(), OUT, and UE_API.
Referenced by CaptureAttributeForGameplayEffect().
CheckDurationExpired()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CheckDurationExpired (FActiveGameplayEffectHandle Handle) protected
References CheckDurationExpired(), Handle, and UE_API.
Referenced by CheckDurationExpired().
CheckForClearedAbilities()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::CheckForClearedAbilities () protected
Called from ClearAbility, ClearAllAbilities or OnRep.
Clears any triggers that should no longer exist.
References UE_API.
CleanupName()
GAMEPLAYABILITIES_API FString UAbilitySystemComponent::CleanupName (FString Str) private
References UE_API.
ClearAbilityReplicatedDataCache()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ClearAbilityReplicatedDataCache (FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActivationInfo & ActivationInfo) private
References ActivationInfo, ClearAbilityReplicatedDataCache(), const, Handle, and UE_API.
Referenced by ClearAbilityReplicatedDataCache().
ClearActorInfo()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ClearActorInfo () virtual
This is called when the actor that is initialized to this system dies, this will clear that actor from this system and FGameplayAbilityActorInfo.
References UE_API.
ClearAnimatingAbility()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ClearAnimatingAbility (UGameplayAbility * Ability) private virtual
Clear the animating ability that is passed in, if it's still currently animating.
References ClearAnimatingAbility(), and UE_API.
Referenced by ClearAnimatingAbility().
ConfirmAbilityTargetData()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ConfirmAbilityTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, const FGameplayAbilityTargetDataHandle & TargetData, const FGameplayTag & ApplicationTag) virtual
Sets the current target data and calls applicable callbacks.
References AbilityOriginalPredictionKey, ApplicationTag, ConfirmAbilityTargetData(), const, and UE_API.
Referenced by ConfirmAbilityTargetData().
ConsumeAllReplicatedData()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ConsumeAllReplicatedData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Deletes all cached ability client data (Was: ConsumeAbilityTargetData)
References AbilityOriginalPredictionKey, ConsumeAllReplicatedData(), and UE_API.
Referenced by ConsumeAllReplicatedData().
ConsumeClientReplicatedTargetData()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ConsumeClientReplicatedTargetData (FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Consumes cached TargetData from client (only TargetData)
References AbilityOriginalPredictionKey, ConsumeClientReplicatedTargetData(), and UE_API.
Referenced by ConsumeClientReplicatedTargetData().
ConsumeGenericReplicatedEvent()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ConsumeGenericReplicatedEvent (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Consumes the given Generic Replicated Event (unsets it).
References AbilityOriginalPredictionKey, ConsumeGenericReplicatedEvent(), and UE_API.
Referenced by ConsumeGenericReplicatedEvent().
CreateNewInstanceOfAbility()
virtual GAMEPLAYABILITIES_API UGameplayAbility * UAbilitySystemComponent::CreateNewInstanceOfAbility (FGameplayAbilitySpec & Spec, const UGameplayAbility * Ability) protected virtual
Creates a new instance of an ability, storing it in the spec.
References FGameplayAbilitySpec, and UE_API.
CurrentMontageJumpToSection()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::CurrentMontageJumpToSection (FName SectionName) private virtual
Jumps current montage to given section.
Expectation is caller should only be stopping it if they are the current animating ability (or have good reason not to check)
References CurrentMontageJumpToSection(), SectionName, and UE_API.
Referenced by CurrentMontageJumpToSection().
CurrentMontageSetNextSectionName()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::CurrentMontageSetNextSectionName (FName FromSectionName, FName ToSectionName) private virtual
Sets current montages next section name.
Expectation is caller should only be stopping it if they are the current animating ability (or have good reason not to check)
References CurrentMontageSetNextSectionName(), and UE_API.
Referenced by CurrentMontageSetNextSectionName().
CurrentMontageSetPlayRate()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::CurrentMontageSetPlayRate (float InPlayRate) private virtual
Sets current montage's play rate.
References CurrentMontageSetPlayRate(), InPlayRate, and UE_API.
Referenced by CurrentMontageSetPlayRate().
CurrentMontageStop()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::CurrentMontageStop (float OverrideBlendOutTime = -1.0f) private virtual
Stops whatever montage is currently playing.
Expectation is caller should only be stopping it if they are the current animating ability (or have good reason not to check)
References CurrentMontageStop(), and UE_API.
Referenced by CurrentMontageStop().
Debug_Internal()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::Debug_Internal (struct FAbilitySystemComponentDebugInfo & Info) private virtual
References Info, and UE_API.
DebugCyclicAggregatorBroadcasts()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::DebugCyclicAggregatorBroadcasts (struct FAggregator * Aggregator) protected
References DebugCyclicAggregatorBroadcasts(), FAggregator, and UE_API.
Referenced by DebugCyclicAggregatorBroadcasts().
DebugLine()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::DebugLine (struct FAbilitySystemComponentDebugInfo & Info, FString Str, float XOffset, float YOffset, int32 MinTextRowsToAdvance = 0) private
References Info, int32, and UE_API.
DECLARE_DYNAMIC_MULTICAST_DELEGATE()
UAbilitySystemComponent::DECLARE_DYNAMIC_MULTICAST_DELEGATE (FAbilityConfirmOrCancel) private
Used to register callbacks to confirm/cancel input.
References DECLARE_DYNAMIC_MULTICAST_DELEGATE().
Referenced by DECLARE_DYNAMIC_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE_ThreeParams()
UAbilitySystemComponent::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnGameplayEffectAppliedDelegate , UAbilitySystemComponent * , const FGameplayEffectSpec & , FActiveGameplayEffectHandle) private
Delegate for when an effect is applied.
References const, DECLARE_MULTICAST_DELEGATE_ThreeParams(), and FGameplayEffectSpec.
Referenced by DECLARE_MULTICAST_DELEGATE_ThreeParams().
DecrementAbilityListLock()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::DecrementAbilityListLock () private
References DecrementAbilityListLock(), and UE_API.
Referenced by DecrementAbilityListLock().
DestroyActiveState()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::DestroyActiveState () private virtual
Cancels all abilities and kills any remaining instanced abilities.
References DestroyActiveState(), and UE_API.
Referenced by DestroyActiveState().
DisplayDebug()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::DisplayDebug (class UCanvas * Canvas, const class FDebugDisplayInfo & DebugDisplay, float & YL, float & YPos) private virtual
References UE_API.
EndServerAbilityRPCBatch()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::EndServerAbilityRPCBatch (FGameplayAbilitySpecHandle AbilityHandle) private virtual
References UE_API.
ExecuteGameplayCue() [1/2]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ExecuteGameplayCue (const FGameplayTag GameplayCueTag, const FGameplayCueParameters & GameplayCueParameters) private
References const, ExecuteGameplayCue(), and UE_API.
ExecuteGameplayCue() [2/2]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ExecuteGameplayCue (const FGameplayTag GameplayCueTag, FGameplayEffectContextHandle EffectContext = FGameplayEffectContextHandle()) private
GameplayCues can also come on their own.
These take an optional effect context to pass through hit result, etc
References const, EffectContext, ExecuteGameplayCue(), and UE_API.
Referenced by ExecuteGameplayCue(), and ExecuteGameplayCue().
ExecuteGameplayEffect()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ExecuteGameplayEffect (FGameplayEffectSpec & Spec, FPredictionKey PredictionKey) protected
References ExecuteGameplayEffect(), FGameplayEffectSpec, PredictionKey, and UE_API.
Referenced by ExecuteGameplayEffect().
ExecutePeriodicEffect()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ExecutePeriodicEffect (FActiveGameplayEffectHandle Handle) protected
References ExecutePeriodicEffect(), Handle, and UE_API.
Referenced by ExecutePeriodicEffect().
FindAbilitySpecFromClass()
GAMEPLAYABILITIES_API FGameplayAbilitySpec * UAbilitySystemComponent::FindAbilitySpecFromClass (TSubclassOf< UGameplayAbility > InAbilityClass) const private
Returns an ability spec corresponding to given ability class.
If modifying call MarkAbilitySpecDirty
References const, FGameplayAbilitySpec, FindAbilitySpecFromClass(), and UE_API.
Referenced by FindAbilitySpecFromClass().
FindAbilitySpecFromHandle()
GAMEPLAYABILITIES_API FGameplayAbilitySpec * UAbilitySystemComponent::FindAbilitySpecFromHandle (FGameplayAbilitySpecHandle Handle, EConsiderPending ConsiderPending = EConsiderPending::PendingRemove) const private
Returns an ability spec from a handle.
If modifying call MarkAbilitySpecDirty. Treat the return value as ephemeral as the pointer will potentially be invalidated on any subsequent call into AbilitySystemComponent.
References FGameplayAbilitySpec, Handle, PendingRemove, and UE_API.
FindAbilitySpecFromInputID()
GAMEPLAYABILITIES_API FGameplayAbilitySpec * UAbilitySystemComponent::FindAbilitySpecFromInputID (int32 InputID) const private
Returns an ability spec from a handle.
If modifying call MarkAbilitySpecDirty
References const, FGameplayAbilitySpec, FindAbilitySpecFromInputID(), InputID, int32, and UE_API.
Referenced by FindAbilitySpecFromInputID().
FindAbilitySpecsFromGEHandle()
GAMEPLAYABILITIES_API TArray< const FGameplayAbilitySpec * > UAbilitySystemComponent::FindAbilitySpecsFromGEHandle (const FScopedAbilityListLock & ScopeLock, FActiveGameplayEffectHandle Handle, EConsiderPending ConsiderPending = EConsiderPending::PendingRemove) const private
Returns all ability spec handles granted from a GE handle.
Only the server may call this function.
Parameters
ScopeLock - The lock to communicate to the caller that the return value is only valid for as long as this lock is in scope
Handle - The handle of the Active Gameplay Effect which granted the abilities we are looking for
ConsiderPending - Are we returning AbilitySpecs that are pending for addition/removal?
References const, FGameplayAbilitySpec, FindAbilitySpecsFromGEHandle(), Handle, PendingRemove, and UE_API.
Referenced by FindAbilitySpecsFromGEHandle().
FindActiveGameplayEffectHandle()
GAMEPLAYABILITIES_API FActiveGameplayEffectHandle UAbilitySystemComponent::FindActiveGameplayEffectHandle (FGameplayAbilitySpecHandle Handle) const private
Gets the GE Handle of the GE that granted the passed in Ability.
References const, FindActiveGameplayEffectHandle(), Handle, and UE_API.
Referenced by FindActiveGameplayEffectHandle().
FindAllAbilitySpecsFromInputID()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::FindAllAbilitySpecsFromInputID (int32 InputID, TArray< const FGameplayAbilitySpec * > & OutAbilitySpecs) const private virtual
Returns all abilities with the given InputID.
Parameters
InputID The Input ID to match
OutAbilitySpecs Array of pointers to matching specs
References const, FGameplayAbilitySpec, FindAllAbilitySpecsFromInputID(), InputID, int32, and UE_API.
Referenced by FindAllAbilitySpecsFromInputID().
ForceAvatarReplication()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ForceAvatarReplication () private virtual
Forces avatar actor to update it's replication.
Useful for things like needing to replication for movement / locations reasons.
References ForceAvatarReplication(), and UE_API.
Referenced by ForceAvatarReplication().
ForceCancelAbilityDueToReplication()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ForceCancelAbilityDueToReplication (UGameplayAbility * Instance) private virtual
Force cancels the ability and does not replicate this to the other side.
This should be called when the ability is cancelled by the other side
References Instance, and UE_API.
ForceReplication()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ForceReplication () override virtual
Force owning actor to update it's replication, to make sure that gameplay cues get sent down quickly.
Override to change how aggressive this is
References ForceReplication(), override, and UE_API.
Referenced by ForceReplication().
GENERATED_UCLASS_BODY()
UAbilitySystemComponent::GENERATED_UCLASS_BODY () private
Used to register callbacks to ability-key input.
GetAbilityActiveTasks()
GAMEPLAYABILITIES_API TArray< TObjectPtr< UGameplayTask > > & UAbilitySystemComponent::GetAbilityActiveTasks (UGameplayAbility * Ability) protected
References GetAbilityActiveTasks(), and UE_API.
Referenced by GetAbilityActiveTasks().
GetAbilityLastActivatedTime()
float UAbilitySystemComponent::GetAbilityLastActivatedTime () const inline private
Returns local world time that an ability was activated.
Valid on authority (server) and autonomous proxy (controlling client).
Definition at line 1140 of file AbilitySystemComponent.h.
References AbilityLastActivatedTime.
GetActivatableAbilities() [1/2]
TArray< FGameplayAbilitySpec > & UAbilitySystemComponent::GetActivatableAbilities () inline private
Returns the list of all activatable abilities.
Definition at line 1134 of file AbilitySystemComponent.h.
GetActivatableAbilities() [2/2]
const TArray< FGameplayAbilitySpec > & UAbilitySystemComponent::GetActivatableAbilities () const inline private
Returns the list of all activatable abilities.
Read-only.
Definition at line 1128 of file AbilitySystemComponent.h.
GetActivatableGameplayAbilitySpecsByAllMatchingTags()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::GetActivatableGameplayAbilitySpecsByAllMatchingTags (const FGameplayTagContainer & GameplayTagContainer, TArray< struct FGameplayAbilitySpec * > & MatchingGameplayAbilities, bool bOnlyAbilitiesThatSatisfyTagRequirements = true) const private
Gets all Activatable Gameplay Abilities that match all tags in GameplayTagContainer AND for which DoesAbilitySatisfyTagRequirements() is true.
The latter requirement allows this function to find the correct ability without requiring advanced knowledge. For example, if there are two "Melee" abilities, one of which requires a weapon and one of which requires being unarmed, then those abilities can use Blocking and Required tags to determine when they can fire. Using the Satisfying Tags requirements simplifies a lot of usage cases. For example, Behavior Trees can use various decorators to test an ability fetched using this mechanism as well as the Task to execute the ability without needing to know that there even is more than one such ability.
References const, FGameplayAbilitySpec, GetActivatableGameplayAbilitySpecsByAllMatchingTags(), and UE_API.
Referenced by GetActivatableGameplayAbilitySpecsByAllMatchingTags().
GetActiveEffectEventSet()
GAMEPLAYABILITIES_API FActiveGameplayEffectEvents * UAbilitySystemComponent::GetActiveEffectEventSet (FActiveGameplayEffectHandle Handle) private
Returns delegate structure that allows binding to several gameplay effect changes.
References GetActiveEffectEventSet(), Handle, and UE_API.
Referenced by GetActiveEffectEventSet().
GetActiveEffectsDuration()
GAMEPLAYABILITIES_API TArray< float > UAbilitySystemComponent::GetActiveEffectsDuration (const FGameplayEffectQuery & Query) const private
Gets total duration for all effects that match query.
References UE_API.
GetActiveEffectsEndTime()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetActiveEffectsEndTime (const FGameplayEffectQuery & Query) const private
This will give the world time that all effects matching this query will be finished.
If multiple effects match, it returns the one that returns last
References const, GetActiveEffectsEndTime(), and UE_API.
Referenced by GetActiveEffectsEndTime().
GetActiveEffectsEndTimeAndDuration()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::GetActiveEffectsEndTimeAndDuration (const FGameplayEffectQuery & Query, float & EndTime, float & Duration) const private
Returns end time and total duration.
References const, Duration, GetActiveEffectsEndTimeAndDuration(), and UE_API.
Referenced by GetActiveEffectsEndTimeAndDuration().
GetActiveEffectsEndTimeWithInstigators()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetActiveEffectsEndTimeWithInstigators (const FGameplayEffectQuery & Query, TArray< AActor * > & Instigators) const private
References const, GetActiveEffectsEndTimeWithInstigators(), and UE_API.
Referenced by GetActiveEffectsEndTimeWithInstigators().
GetActiveEffectsTimeRemaining()
GAMEPLAYABILITIES_API TArray< float > UAbilitySystemComponent::GetActiveEffectsTimeRemaining (const FGameplayEffectQuery & Query) const private
Gets time remaining for all effects that match query.
References UE_API.
GetActiveEffectsTimeRemainingAndDuration()
GAMEPLAYABILITIES_API TArray< TPair< float, float > > UAbilitySystemComponent::GetActiveEffectsTimeRemainingAndDuration (const FGameplayEffectQuery & Query) const private
Gets both time remaining and total duration for all effects that match query.
References UE_API.
GetActiveGameplayEffect()
GAMEPLAYABILITIES_API const FActiveGameplayEffect * UAbilitySystemComponent::GetActiveGameplayEffect (const FActiveGameplayEffectHandle Handle) const private
Returns const pointer to the actual active gameplay effect structure.
References const, FActiveGameplayEffect, GetActiveGameplayEffect(), Handle, and UE_API.
Referenced by GetActiveGameplayEffect().
GetActiveGameplayEffects()
GAMEPLAYABILITIES_API const FActiveGameplayEffectsContainer & UAbilitySystemComponent::GetActiveGameplayEffects () const private
Returns all active gameplay effects on this ASC.
References const, FActiveGameplayEffectsContainer, GetActiveGameplayEffects(), and UE_API.
Referenced by GetActiveGameplayEffects().
GetActiveGEDebugString()
GAMEPLAYABILITIES_API FString UAbilitySystemComponent::GetActiveGEDebugString (FActiveGameplayEffectHandle Handle) const private
Returns debug string describing active gameplay effect.
References const, GetActiveGEDebugString(), Handle, and UE_API.
Referenced by GetActiveGEDebugString().
GetAggregatedStackCount()
GAMEPLAYABILITIES_API int32 UAbilitySystemComponent::GetAggregatedStackCount (const FGameplayEffectQuery & Query) const private
Returns the sum of StackCount of all gameplay effects that pass query.
References const, GetAggregatedStackCount(), int32, and UE_API.
Referenced by GetAggregatedStackCount().
GetAllActiveGameplayEffectSpecs()
void UAbilitySystemComponent::GetAllActiveGameplayEffectSpecs (TArray< FGameplayEffectSpec > & OutSpecCopies) const inline private
Makes a copy of all the active effects on this ability component.
Definition at line 806 of file AbilitySystemComponent.h.
GetAnimatingAbility()
GAMEPLAYABILITIES_API UGameplayAbility * UAbilitySystemComponent::GetAnimatingAbility () const private
Returns the current animating ability.
References const, GetAnimatingAbility(), and UE_API.
Referenced by GetAnimatingAbility().
GetAttributeSubobject()
GAMEPLAYABILITIES_API const UAttributeSet * UAbilitySystemComponent::GetAttributeSubobject (const TSubclassOf< UAttributeSet > AttributeClass) const protected
References UE_API.
Referenced by GetSet().
GetAttributeSubobjectChecked()
GAMEPLAYABILITIES_API const UAttributeSet * UAbilitySystemComponent::GetAttributeSubobjectChecked (const TSubclassOf< UAttributeSet > AttributeClass) const protected
References UE_API.
Referenced by GetSetChecked().
GetAvatarActor()
GAMEPLAYABILITIES_API AActor * UAbilitySystemComponent::GetAvatarActor () const
Returns the avatar actor for this component.
References const, GetAvatarActor(), and UE_API.
Referenced by GetAvatarActor().
GetAvatarActor_Direct()
AActor * UAbilitySystemComponent::GetAvatarActor_Direct () const inline
Definition at line 1529 of file AbilitySystemComponent.h.
GetBlockedAbilityBindings()
GAMEPLAYABILITIES_API const TArray< uint8 > & UAbilitySystemComponent::GetBlockedAbilityBindings () const protected
References const, GetBlockedAbilityBindings(), and UE_API.
Referenced by GetBlockedAbilityBindings().
GetBlockedAbilityBindings_Mutable()
GAMEPLAYABILITIES_API TArray< uint8 > & UAbilitySystemComponent::GetBlockedAbilityBindings_Mutable () protected
References GetBlockedAbilityBindings_Mutable(), and UE_API.
Referenced by GetBlockedAbilityBindings_Mutable().
GetBlockedAbilityTags() [1/2]
FORCEINLINE const FGameplayTagContainer & UAbilitySystemComponent::GetBlockedAbilityTags () const inline nodiscard private
Definition at line 644 of file AbilitySystemComponent.h.
References BlockedAbilityTags, and FORCEINLINE.
GetBlockedAbilityTags() [2/2]
FORCEINLINE void UAbilitySystemComponent::GetBlockedAbilityTags (FGameplayTagContainer & TagContainer) const inline private
Fills TagContainer with BlockedAbilityTags.
Definition at line 639 of file AbilitySystemComponent.h.
References FORCEINLINE, and GetBlockedAbilityTags().
Referenced by GetBlockedAbilityTags().
GetClientDebugStrings()
GAMEPLAYABILITIES_API const TArray< FString > & UAbilitySystemComponent::GetClientDebugStrings () const private
References const, GetClientDebugStrings(), and UE_API.
Referenced by GetClientDebugStrings().
GetClientDebugStrings_Mutable()
GAMEPLAYABILITIES_API TArray< FString > & UAbilitySystemComponent::GetClientDebugStrings_Mutable () private
References GetClientDebugStrings_Mutable(), and UE_API.
Referenced by GetClientDebugStrings_Mutable().
GetCurrentMontage()
GAMEPLAYABILITIES_API UAnimMontage * UAbilitySystemComponent::GetCurrentMontage () const private
Returns montage that is currently playing.
References const, GetCurrentMontage(), and UE_API.
Referenced by GetCurrentMontage().
GetCurrentMontageSectionID()
GAMEPLAYABILITIES_API int32 UAbilitySystemComponent::GetCurrentMontageSectionID () const private
Get SectionID of currently playing AnimMontage.
References const, GetCurrentMontageSectionID(), int32, and UE_API.
Referenced by GetCurrentMontageSectionID().
GetCurrentMontageSectionLength()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetCurrentMontageSectionLength () const private
Get length in time of current section.
References const, GetCurrentMontageSectionLength(), and UE_API.
Referenced by GetCurrentMontageSectionLength().
GetCurrentMontageSectionName()
GAMEPLAYABILITIES_API FName UAbilitySystemComponent::GetCurrentMontageSectionName () const private
Get SectionName of currently playing AnimMontage.
References const, GetCurrentMontageSectionName(), and UE_API.
Referenced by GetCurrentMontageSectionName().
GetCurrentMontageSectionTimeLeft()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetCurrentMontageSectionTimeLeft () const private
Returns amount of time left in current section.
References const, GetCurrentMontageSectionTimeLeft(), and UE_API.
Referenced by GetCurrentMontageSectionTimeLeft().
GetCurrentStackCount() [1/2]
GAMEPLAYABILITIES_API int32 UAbilitySystemComponent::GetCurrentStackCount (FActiveGameplayEffectHandle Handle) const private
Returns current stack count of an already applied GE.
References const, GetCurrentStackCount(), Handle, int32, and UE_API.
Referenced by GetCurrentStackCount(), and GetCurrentStackCount().
GetCurrentStackCount() [2/2]
GAMEPLAYABILITIES_API int32 UAbilitySystemComponent::GetCurrentStackCount (FGameplayAbilitySpecHandle Handle) const private
Returns current stack count of an already applied GE, but given the ability spec handle that was granted by the GE.
References const, GetCurrentStackCount(), Handle, int32, and UE_API.
GetEffectContextFromActiveGEHandle()
GAMEPLAYABILITIES_API FGameplayEffectContextHandle UAbilitySystemComponent::GetEffectContextFromActiveGEHandle (FActiveGameplayEffectHandle Handle) private
Retrieves the EffectContext of the GameplayEffect of the active GameplayEffect.
References GetEffectContextFromActiveGEHandle(), Handle, and UE_API.
Referenced by GetEffectContextFromActiveGEHandle().
GetFilteredAttributeValue()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetFilteredAttributeValue (const FGameplayAttribute & Attribute, const FGameplayTagRequirements & SourceTags, const FGameplayTagContainer & TargetTags, const TArray< FActiveGameplayEffectHandle > & HandlesToIgnore = TArray< FActiveGameplayEffectHandle >()) private
Returns an attribute value, after applying tag filters.
References Attribute, const, GetFilteredAttributeValue(), and UE_API.
Referenced by GetFilteredAttributeValue().
GetGameplayAttributeValueChangeDelegate()
GAMEPLAYABILITIES_API FOnGameplayAttributeValueChange & UAbilitySystemComponent::GetGameplayAttributeValueChangeDelegate (FGameplayAttribute Attribute) private
Register for when an attribute value changes.
References Attribute, GetGameplayAttributeValueChangeDelegate(), and UE_API.
Referenced by GetGameplayAttributeValueChangeDelegate().
GetGameplayEffectCDO()
GAMEPLAYABILITIES_API const UGameplayEffect * UAbilitySystemComponent::GetGameplayEffectCDO (const FActiveGameplayEffectHandle Handle) const private
Returns a const pointer to the gameplay effect CDO associated with an active handle.
References const, GetGameplayEffectCDO(), Handle, and UE_API.
Referenced by GetGameplayEffectCDO().
GetGameplayEffectDefForHandle()
GAMEPLAYABILITIES_API const UGameplayEffect * UAbilitySystemComponent::GetGameplayEffectDefForHandle (FActiveGameplayEffectHandle Handle) private
Gets the FActiveGameplayEffect based on the passed in Handle.
References const, GetGameplayEffectDefForHandle(), Handle, and UE_API.
Referenced by GetGameplayEffectDefForHandle().
GetGameplayEffectDuration()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetGameplayEffectDuration (FActiveGameplayEffectHandle Handle) const private
Returns the total duration of a gameplay effect.
References const, GetGameplayEffectDuration(), Handle, and UE_API.
Referenced by GetGameplayEffectDuration().
GetGameplayEffectSourceTagsFromHandle()
GAMEPLAYABILITIES_API const FGameplayTagContainer * UAbilitySystemComponent::GetGameplayEffectSourceTagsFromHandle (FActiveGameplayEffectHandle Handle) const private
Get the source tags from the gameplay spec represented by the specified handle, if possible.
Parameters
Handle Handle of the gameplay effect to retrieve source tags from
Returns
Source tags from the gameplay spec represented by the handle, if possible
References const, GetGameplayEffectSourceTagsFromHandle(), Handle, and UE_API.
Referenced by GetGameplayEffectSourceTagsFromHandle().
GetGameplayEffectStartTimeAndDuration()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::GetGameplayEffectStartTimeAndDuration (FActiveGameplayEffectHandle Handle, float & StartEffectTime, float & Duration) const private
Return start time and total duration of a gameplay effect.
References const, Duration, GetGameplayEffectStartTimeAndDuration(), Handle, and UE_API.
Referenced by GetGameplayEffectStartTimeAndDuration().
GetGameplayEffectTargetTagsFromHandle()
GAMEPLAYABILITIES_API const FGameplayTagContainer * UAbilitySystemComponent::GetGameplayEffectTargetTagsFromHandle (FActiveGameplayEffectHandle Handle) const private
Get the target tags from the gameplay spec represented by the specified handle, if possible.
Parameters
Handle Handle of the gameplay effect to retrieve target tags from
Returns
Target tags from the gameplay spec represented by the handle, if possible
References const, GetGameplayEffectTargetTagsFromHandle(), Handle, and UE_API.
Referenced by GetGameplayEffectTargetTagsFromHandle().
GetGameplayTaskAvatar()
virtual GAMEPLAYABILITIES_API AActor * UAbilitySystemComponent::GetGameplayTaskAvatar (const UGameplayTask * Task) const override virtual
Returns avatar actor to be used for a specific task, normally GetAvatarActor.
Reimplemented from UGameplayTasksComponent.
References const, GetGameplayTaskAvatar(), override, and UE_API.
Referenced by GetGameplayTaskAvatar().
GetIncomingDurationCapture()
GAMEPLAYABILITIES_API const FGameplayEffectAttributeCaptureDefinition & UAbilitySystemComponent::GetIncomingDurationCapture () static private
References const, GetIncomingDurationCapture(), and UE_API.
Referenced by GetIncomingDurationCapture().
GetIncomingDurationProperty()
GAMEPLAYABILITIES_API FProperty * UAbilitySystemComponent::GetIncomingDurationProperty () static private
References GetIncomingDurationProperty(), and UE_API.
Referenced by GetIncomingDurationProperty().
GetLifetimeReplicatedProps()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override protected virtual
Returns properties that are replicated for the lifetime of the actor channel.
Reimplemented from UGameplayTasksComponent.
References const, GetLifetimeReplicatedProps(), override, and UE_API.
Referenced by GetLifetimeReplicatedProps().
GetMinimalReplicationTags()
GAMEPLAYABILITIES_API const FMinimalReplicationTagCountMap & UAbilitySystemComponent::GetMinimalReplicationTags () const protected
References const, GetMinimalReplicationTags(), and UE_API.
Referenced by GetMinimalReplicationTags().
GetMinimalReplicationTags_Mutable()
GAMEPLAYABILITIES_API FMinimalReplicationTagCountMap & UAbilitySystemComponent::GetMinimalReplicationTags_Mutable () protected
References GetMinimalReplicationTags_Mutable(), and UE_API.
Referenced by AddMinimalReplicationGameplayTag(), AddMinimalReplicationGameplayTags(), GetMinimalReplicationTags_Mutable(), RemoveMinimalReplicationGameplayTag(), and RemoveMinimalReplicationGameplayTags().
GetNumActiveGameplayEffects()
int32 UAbilitySystemComponent::GetNumActiveGameplayEffects () const inline private
Returns the number of gameplay effects that are currently active on this ability system component.
Definition at line 800 of file AbilitySystemComponent.h.
References GetNumActiveGameplayEffects(), and int32.
Referenced by GetNumActiveGameplayEffects().
GetNumericAttribute()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetNumericAttribute (const FGameplayAttribute & Attribute) const private
Returns current (final) value of an attribute.
References Attribute, const, GetNumericAttribute(), and UE_API.
Referenced by GetNumericAttribute().
GetNumericAttributeBase()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetNumericAttributeBase (const FGameplayAttribute & Attribute) const private
Gets the base value of an attribute.
That is, the value of the attribute with no stateful modifiers
References Attribute, const, GetNumericAttributeBase(), and UE_API.
Referenced by GetNumericAttributeBase().
GetNumericAttributeChecked()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::GetNumericAttributeChecked (const FGameplayAttribute & Attribute) const private
References Attribute, const, GetNumericAttributeChecked(), and UE_API.
Referenced by GetNumericAttributeChecked().
GetOrCreateAttributeSubobject()
GAMEPLAYABILITIES_API const UAttributeSet * UAbilitySystemComponent::GetOrCreateAttributeSubobject (TSubclassOf< UAttributeSet > AttributeClass) protected
References UE_API.
Referenced by AddSet().
GetOutgoingDurationCapture()
GAMEPLAYABILITIES_API const FGameplayEffectAttributeCaptureDefinition & UAbilitySystemComponent::GetOutgoingDurationCapture () static private
References const, GetOutgoingDurationCapture(), and UE_API.
Referenced by GetOutgoingDurationCapture().
GetOutgoingDurationProperty()
GAMEPLAYABILITIES_API FProperty * UAbilitySystemComponent::GetOutgoingDurationProperty () static private
References GetOutgoingDurationProperty(), and UE_API.
Referenced by GetOutgoingDurationProperty().
GetOwnedGameplayTags() [1/2]
FORCEINLINE const FGameplayTagContainer & UAbilitySystemComponent::GetOwnedGameplayTags () const inline nodiscard private
Definition at line 597 of file AbilitySystemComponent.h.
References FORCEINLINE, and GameplayTagCountContainer.
GetOwnedGameplayTags() [2/2]
FORCEINLINE void UAbilitySystemComponent::GetOwnedGameplayTags (FGameplayTagContainer & TagContainer) const inline override private
Definition at line 591 of file AbilitySystemComponent.h.
References FORCEINLINE, and GetOwnedGameplayTags().
Referenced by GetOwnedGameplayTags().
GetOwnerActor()
AActor * UAbilitySystemComponent::GetOwnerActor () const inline
Definition at line 1526 of file AbilitySystemComponent.h.
References GetOwnerActor().
Referenced by GetOwnerActor().
GetPredictionKeyForNewAction()
FPredictionKey UAbilitySystemComponent::GetPredictionKeyForNewAction () const inline private
Returns the prediction key that should be used for any actions.
Definition at line 271 of file AbilitySystemComponent.h.
References GetPredictionKeyForNewAction(), and ScopedPredictionKey.
Referenced by GetPredictionKeyForNewAction().
GetRepAnimMontageInfo()
GAMEPLAYABILITIES_API const FGameplayAbilityRepAnimMontage & UAbilitySystemComponent::GetRepAnimMontageInfo () const protected
References const, GetRepAnimMontageInfo(), and UE_API.
Referenced by GetRepAnimMontageInfo().
GetRepAnimMontageInfo_Mutable()
GAMEPLAYABILITIES_API FGameplayAbilityRepAnimMontage & UAbilitySystemComponent::GetRepAnimMontageInfo_Mutable () protected
References GetRepAnimMontageInfo_Mutable(), and UE_API.
Referenced by GetRepAnimMontageInfo_Mutable().
GetReplicatedCustomConditionState()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::GetReplicatedCustomConditionState (FCustomPropertyConditionState & OutActiveState) const override protected virtual
Called when this object begins replicating to initialize the state of custom property conditions.
Reimplemented from UObject.
References const, GetReplicatedCustomConditionState(), override, and UE_API.
Referenced by GetReplicatedCustomConditionState().
GetReplicatedDataOfGenericReplicatedEvent()
GAMEPLAYABILITIES_API FAbilityReplicatedData UAbilitySystemComponent::GetReplicatedDataOfGenericReplicatedEvent (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey)
Gets replicated data of the given Generic Replicated Event.
References AbilityOriginalPredictionKey, GetReplicatedDataOfGenericReplicatedEvent(), and UE_API.
Referenced by GetReplicatedDataOfGenericReplicatedEvent().
GetReplicatedInstancedAbilities()
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray< UGameplayAbility * > & UAbilitySystemComponent::GetReplicatedInstancedAbilities () const inline protected
Full list of all instance-per-execution gameplay abilities associated with this component.
Definition at line 1711 of file AbilitySystemComponent.h.
References const, and GetReplicatedInstancedAbilities().
Referenced by GetReplicatedInstancedAbilities().
GetReplicatedInstancedAbilities_Mutable()
PRAGMA_DISABLE_DEPRECATION_WARNINGS TArray< TObjectPtr< UGameplayAbility > > & UAbilitySystemComponent::GetReplicatedInstancedAbilities_Mutable () inline private
Definition at line 1951 of file AbilitySystemComponent.h.
GetReplicatedLooseTags()
GAMEPLAYABILITIES_API const FMinimalReplicationTagCountMap & UAbilitySystemComponent::GetReplicatedLooseTags () const protected
References const, GetReplicatedLooseTags(), and UE_API.
Referenced by GetReplicatedLooseTags().
GetReplicatedLooseTags_Mutable()
GAMEPLAYABILITIES_API FMinimalReplicationTagCountMap & UAbilitySystemComponent::GetReplicatedLooseTags_Mutable () protected
References GetReplicatedLooseTags_Mutable(), and UE_API.
Referenced by AddReplicatedLooseGameplayTag(), AddReplicatedLooseGameplayTags(), GetReplicatedLooseTags_Mutable(), RemoveReplicatedLooseGameplayTag(), RemoveReplicatedLooseGameplayTags(), and SetReplicatedLooseGameplayTagCount().
GetReplicationInterface()
virtual GAMEPLAYABILITIES_API IAbilitySystemReplicationProxyInterface * UAbilitySystemComponent::GetReplicationInterface () private virtual
Who to route replication through if ReplicationProxyEnabled (if this returns null, when ReplicationProxyEnabled, we wont replicate)
References GetReplicationInterface(), and UE_API.
Referenced by GetReplicationInterface().
GetServerDebugStrings()
GAMEPLAYABILITIES_API const TArray< FString > & UAbilitySystemComponent::GetServerDebugStrings () const private
References const, GetServerDebugStrings(), and UE_API.
Referenced by GetServerDebugStrings().
GetServerDebugStrings_Mutable()
GAMEPLAYABILITIES_API TArray< FString > & UAbilitySystemComponent::GetServerDebugStrings_Mutable () private
References GetServerDebugStrings_Mutable(), and UE_API.
Referenced by GetServerDebugStrings_Mutable().
GetSet()
template<class T> const T * UAbilitySystemComponent::GetSet () const inline private
Finds existing AttributeSet.
Definition at line 128 of file AbilitySystemComponent.h.
References const, GetAttributeSubobject(), and GetSet().
Referenced by GetSet().
GetSetChecked()
template<class T> const T * UAbilitySystemComponent::GetSetChecked () const inline private
Finds existing AttributeSet.
Asserts if it isn't there.
Definition at line 135 of file AbilitySystemComponent.h.
References GetAttributeSubobjectChecked().
GetShouldTick()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::GetShouldTick () const override virtual
retrieves information whether this component should be ticking taken current activity into consideration
Reimplemented from UGameplayTasksComponent.
References const, GetShouldTick(), override, and UE_API.
Referenced by GetShouldTick().
GetSpawnedAttributes()
GAMEPLAYABILITIES_API const TArray< UAttributeSet * > & UAbilitySystemComponent::GetSpawnedAttributes () const private
Access the spawned attributes list when you don't intend to modify the list.
References const, GetSpawnedAttributes(), and UE_API.
Referenced by GetSpawnedAttributes().
GetSubobjectsWithStableNamesForNetworking()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > & ObjList) override virtual
Returns a list of sub-objects that have stable names for networking.
Reimplemented from UObject.
References UObject::UObject(), GetSubobjectsWithStableNamesForNetworking(), override, and UE_API.
Referenced by GetSubobjectsWithStableNamesForNetworking().
GetTagCount()
FORCEINLINE int32 UAbilitySystemComponent::GetTagCount (FGameplayTag TagToCheck) const inline private
Returns the number of instances of a given tag.
Definition at line 609 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTagCountContainer, and int32.
GiveAbility()
GAMEPLAYABILITIES_API FGameplayAbilitySpecHandle UAbilitySystemComponent::GiveAbility (const FGameplayAbilitySpec & AbilitySpec) private
GameplayAbilities.
The role of the AbilitySystemComponent with respect to Abilities is to provide: -Management of ability instances (whether per actor or per execution instance). -Someone has to keep track of these instances. -Non instanced abilities could be executed without any ability stuff in AbilitySystemComponent. They should be able to operate on an GameplayAbilityActorInfo + GameplayAbility.
As convenience it may provide some other features: -Some basic input binding (whether instanced or non instanced abilities). -Concepts like "this component has these abilities
References const, FGameplayAbilitySpec, GiveAbility(), and UE_API.
Referenced by GiveAbility().
GiveAbilityAndActivateOnce()
GAMEPLAYABILITIES_API FGameplayAbilitySpecHandle UAbilitySystemComponent::GiveAbilityAndActivateOnce (FGameplayAbilitySpec & AbilitySpec, const FGameplayEventData * GameplayEventData = nullptr) private
References const, FGameplayAbilitySpec, GiveAbilityAndActivateOnce(), and UE_API.
Referenced by GiveAbilityAndActivateOnce().
HandleChangeAbilityCanBeCanceled()
virtual void UAbilitySystemComponent::HandleChangeAbilityCanBeCanceled (const FGameplayTagContainer & AbilityTags, UGameplayAbility * RequestingAbility, bool bCanBeCanceled) inline private virtual
Called when an ability is cancellable or not.
Doesn't do anything by default, can be overridden to tie into gameplay events
Definition at line 1107 of file AbilitySystemComponent.h.
References const, and HandleChangeAbilityCanBeCanceled().
Referenced by HandleChangeAbilityCanBeCanceled().
HandleDeferredGameplayCues()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::HandleDeferredGameplayCues (const FActiveGameplayEffectsContainer * GameplayEffectsContainer) private virtual
Handle GameplayCues that may have been deferred while doing the NetDeltaSerialize and waiting for the avatar actor to get loaded.
References FActiveGameplayEffectsContainer, and UE_API.
HandleGameplayEvent()
virtual GAMEPLAYABILITIES_API int32 UAbilitySystemComponent::HandleGameplayEvent (FGameplayTag EventTag, const FGameplayEventData * Payload) private virtual
Executes a gameplay event.
Returns the number of successful ability activations triggered by the event
References int32, and UE_API.
HasActivatableTriggeredAbility()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::HasActivatableTriggeredAbility (FGameplayTag Tag) private
References HasActivatableTriggeredAbility(), and UE_API.
Referenced by HasActivatableTriggeredAbility().
HasAllMatchingGameplayTags()
FORCEINLINE bool UAbilitySystemComponent::HasAllMatchingGameplayTags (const FGameplayTagContainer & TagContainer) const inline override private
Definition at line 581 of file AbilitySystemComponent.h.
References FORCEINLINE, and GameplayTagCountContainer.
HasAnyMatchingGameplayTags()
FORCEINLINE bool UAbilitySystemComponent::HasAnyMatchingGameplayTags (const FGameplayTagContainer & TagContainer) const inline override private
Definition at line 586 of file AbilitySystemComponent.h.
References FORCEINLINE, and GameplayTagCountContainer.
HasAttributeSetForAttribute()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::HasAttributeSetForAttribute (FGameplayAttribute Attribute) const private
Does this ability system component have this attribute?
Parameters
Attribute Handle of the gameplay effect to retrieve target tags from
Returns
true if Attribute is valid and this ability system component contains an attribute set that contains Attribute. Returns false otherwise.
References Attribute, and UE_API.
HasAuthorityOrPredictionKey()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::HasAuthorityOrPredictionKey (const FGameplayAbilityActivationInfo * ActivationInfo) const private
Returns true if this is running on the server or has a valid prediction key.
References ActivationInfo, and UE_API.
HasMatchingGameplayTag()
FORCEINLINE bool UAbilitySystemComponent::HasMatchingGameplayTag (FGameplayTag TagToCheck) const inline override private
Definition at line 576 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTagCountContainer, and HasMatchingGameplayTag().
Referenced by HasMatchingGameplayTag(), and UFUNCTION().
HasNetworkAuthorityToActivateTriggeredAbility()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::HasNetworkAuthorityToActivateTriggeredAbility (const FGameplayAbilitySpec & Spec) const protected
Returns true if the specified ability should be activated from an event in this network mode.
References const, FGameplayAbilitySpec, HasNetworkAuthorityToActivateTriggeredAbility(), and UE_API.
Referenced by HasNetworkAuthorityToActivateTriggeredAbility().
HasNetworkAuthorityToApplyGameplayEffect()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::HasNetworkAuthorityToApplyGameplayEffect (FPredictionKey PredictionKey) const protected
References const, HasNetworkAuthorityToApplyGameplayEffect(), PredictionKey, and UE_API.
Referenced by HasNetworkAuthorityToApplyGameplayEffect().
IncrementAbilityListLock()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::IncrementAbilityListLock () private
Called from FScopedAbilityListLock.
References IncrementAbilityListLock(), and UE_API.
Referenced by IncrementAbilityListLock().
InitAbilityActorInfo()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::InitAbilityActorInfo (AActor * InOwnerActor, AActor * InAvatarActor) virtual
Initialized the Abilities' ActorInfo - the structure that holds information about who we are acting on and who controls us.
OwnerActor is the actor that logically owns this component. AvatarActor is what physical actor in the world we are acting on. Usually a Pawn but it could be a Tower, Building, Turret, etc, may be the same as Owner
References InitAbilityActorInfo(), and UE_API.
Referenced by InitAbilityActorInfo().
InitDefaultGameplayCueParameters()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::InitDefaultGameplayCueParameters (FGameplayCueParameters & Parameters) private virtual
Will initialize gameplay cue parameters with this ASC's Owner (Instigator) and AvatarActor (EffectCauser)
References UE_API.
InitializeComponent()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::InitializeComponent () override virtual
Initializes the component.
Occurs at level startup or actor spawn. This is before BeginPlay (Actor or Component).
All Components in the level will be Initialized on load before any Actor/Component gets BeginPlay Requires component to be registered, and bWantsInitializeComponent to be true.
Reimplemented from UActorComponent.
References InitializeComponent(), override, and UE_API.
Referenced by InitializeComponent().
InitStats()
GAMEPLAYABILITIES_API const UAttributeSet * UAbilitySystemComponent::InitStats (TSubclassOf< class UAttributeSet > Attributes, const UDataTable * DataTable) private
Initializes starting attributes from a data table.
Not well supported, a gameplay effect with curve table references may be a better solution
References DataTable, and UE_API.
InternalServerTryActivateAbility()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::InternalServerTryActivateAbility (FGameplayAbilitySpecHandle AbilityToActivate, bool InputPressed, const FPredictionKey & PredictionKey, const FGameplayEventData * TriggerEventData) protected virtual
Implementation of ServerTryActivateAbility.
References const, InputPressed, InternalServerTryActivateAbility(), PredictionKey, TriggerEventData, and UE_API.
Referenced by InternalServerTryActivateAbility().
InternalTryActivateAbility()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::InternalTryActivateAbility (FGameplayAbilitySpecHandle AbilityToActivate, FPredictionKey InPredictionKey = FPredictionKey(), UGameplayAbility ** OutInstancedAbility = nullptr, FOnGameplayAbilityEnded::FDelegate * OnGameplayAbilityEndedDelegate = nullptr, const FGameplayEventData * TriggerEventData = nullptr) private
Attempts to activate the given ability, will only work if called from the correct client/server context.
References const, InternalTryActivateAbility(), TriggerEventData, and UE_API.
Referenced by InternalTryActivateAbility().
InvokeGameplayCueEvent() [1/3]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::InvokeGameplayCueEvent (const FGameplayEffectSpecForRPC & Spec, EGameplayCueEvent::Type EventType) private
Handles gameplay cue events from external sources.
References const, InvokeGameplayCueEvent(), and UE_API.
Referenced by InvokeGameplayCueEvent(), InvokeGameplayCueEvent(), and InvokeGameplayCueEvent().
InvokeGameplayCueEvent() [2/3]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::InvokeGameplayCueEvent (const FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters & GameplayCueParameters) private
References const, InvokeGameplayCueEvent(), and UE_API.
InvokeGameplayCueEvent() [3/3]
GAMEPLAYABILITIES_API void UAbilitySystemComponent::InvokeGameplayCueEvent (const FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, FGameplayEffectContextHandle EffectContext = FGameplayEffectContextHandle()) private
References const, EffectContext, InvokeGameplayCueEvent(), and UE_API.
InvokeReplicatedEvent()
UFUNCTION() GAMEPLAYABILITIES_API void ServerSetReplicatedEvent(EAbilityGenericReplicatedEvent UFUNCTION() GAMEPLAYABILITIES_API void ServerSetReplicatedEventWithPayload(EAbilityGenericReplicatedEvent UFUNCTION() GAMEPLAYABILITIES_API void ClientSetReplicatedEvent(EAbilityGenericReplicatedEvent GAMEPLAYABILITIES_API bool UAbilitySystemComponent::InvokeReplicatedEvent (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, FPredictionKey CurrentPredictionKey = FPredictionKey())
Replicates the Generic Replicated Event to the server.
Replicates the Generic Replicated Event to the server with payload. Replicates the Generic Replicated Event to the client. Calls local callbacks that are registered with the given Generic Replicated Event
References AbilityOriginalPredictionKey, CurrentPredictionKey, and UE_API.
InvokeReplicatedEventWithPayload()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::InvokeReplicatedEventWithPayload (EAbilityGenericReplicatedEvent::Type EventType, FGameplayAbilitySpecHandle AbilityHandle, FPredictionKey AbilityOriginalPredictionKey, FPredictionKey CurrentPredictionKey, FVector_NetQuantize100 VectorPayload)
Calls local callbacks that are registered with the given Generic Replicated Event.
References AbilityOriginalPredictionKey, CurrentPredictionKey, and UE_API.
IsAbilityInputBlocked()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::IsAbilityInputBlocked (int32 InputID) const private
Checks if the ability system is currently blocking InputID.
Returns true if InputID is blocked, false otherwise.
References InputID, int32, and UE_API.
IsAnimatingAbility()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::IsAnimatingAbility (UGameplayAbility * Ability) const private
Returns true if the passed in ability is the current animating ability.
References const, IsAnimatingAbility(), and UE_API.
Referenced by IsAnimatingAbility().
IsGenericCancelInputBound()
bool UAbilitySystemComponent::IsGenericCancelInputBound (int32 InputID) const inline private
Definition at line 1433 of file AbilitySystemComponent.h.
References GenericCancelInputID, GenericLocalCancelCallbacks, InputID, and int32.
IsGenericConfirmInputBound()
bool UAbilitySystemComponent::IsGenericConfirmInputBound (int32 InputID) const inline private
Definition at line 1432 of file AbilitySystemComponent.h.
References GenericConfirmInputID, GenericLocalConfirmCallbacks, InputID, int32, and IsGenericConfirmInputBound().
Referenced by IsGenericConfirmInputBound().
IsOwnerActorAuthoritative()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::IsOwnerActorAuthoritative () const private virtual
Returns true if this component's actor has authority.
References UE_API.
IsReadyForGameplayCues()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::IsReadyForGameplayCues () private virtual
Are we ready to invoke gameplaycues yet?
References UE_API.
IsReadyForReplicatedMontage()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::IsReadyForReplicatedMontage () protected virtual
Returns true if we are ready to handle replicated montage information.
References IsReadyForReplicatedMontage(), and UE_API.
Referenced by IsReadyForReplicatedMontage().
LocalInputCancel()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::LocalInputCancel () private virtual
References LocalInputCancel(), and UE_API.
Referenced by LocalInputCancel().
LocalInputConfirm()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::LocalInputConfirm () private virtual
Handle confirm/cancel for target actors.
References LocalInputConfirm(), and UE_API.
Referenced by LocalInputConfirm().
MarkAbilitySpecDirty()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::MarkAbilitySpecDirty (FGameplayAbilitySpec & Spec, bool WasAddOrRemove = false) private
Call to mark that an ability spec has been modified.
References FGameplayAbilitySpec, MarkAbilitySpecDirty(), and UE_API.
Referenced by MarkAbilitySpecDirty().
MatchesGameplayTagQuery()
FORCEINLINE bool UAbilitySystemComponent::MatchesGameplayTagQuery (const FGameplayTagQuery & TagQuery) const inline private
Checks whether the query matches the owned GameplayTags.
Definition at line 603 of file AbilitySystemComponent.h.
References FORCEINLINE, and GameplayTagCountContainer.
ModifyActiveEffectStartTime()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ModifyActiveEffectStartTime (FActiveGameplayEffectHandle Handle, float StartTimeDiff) private virtual
Modify the start time of a gameplay effect, to deal with timers being out of sync originally.
References Handle, ModifyActiveEffectStartTime(), and UE_API.
Referenced by ModifyActiveEffectStartTime().
MonitoredTagChanged()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::MonitoredTagChanged (const FGameplayTag Tag, int32 NewCount) protected virtual
Callback that is called when an owned tag bound to an ability changes.
References const, int32, MonitoredTagChanged(), and UE_API.
Referenced by MonitoredTagChanged().
NotifyAbilityActivated()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::NotifyAbilityActivated (const FGameplayAbilitySpecHandle Handle, UGameplayAbility * Ability) private virtual
References const, Handle, NotifyAbilityActivated(), and UE_API.
Referenced by NotifyAbilityActivated().
NotifyAbilityCommit()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::NotifyAbilityCommit (UGameplayAbility * Ability) private virtual
Call notify callbacks above.
References NotifyAbilityCommit(), and UE_API.
Referenced by NotifyAbilityCommit().
NotifyAbilityEnded()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::NotifyAbilityEnded (FGameplayAbilitySpecHandle Handle, UGameplayAbility * Ability, bool bWasCancelled) private virtual
Called from the ability to let the component know it is ended.
References Handle, NotifyAbilityEnded(), and UE_API.
Referenced by NotifyAbilityEnded().
NotifyAbilityFailed()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::NotifyAbilityFailed (const FGameplayAbilitySpecHandle Handle, UGameplayAbility * Ability, const FGameplayTagContainer & FailureReason) private virtual
References const, Handle, NotifyAbilityFailed(), and UE_API.
Referenced by NotifyAbilityFailed().
NotifyTagMap_StackCountChange()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::NotifyTagMap_StackCountChange (const FGameplayTagContainer & Container) protected
References const, Container, NotifyTagMap_StackCountChange(), and UE_API.
Referenced by NotifyTagMap_StackCountChange().
OnAnyGameplayEffectRemovedDelegate()
GAMEPLAYABILITIES_API FOnGivenActiveGameplayEffectRemoved & UAbilitySystemComponent::OnAnyGameplayEffectRemovedDelegate () private
Called when any gameplay effects are removed.
References OnAnyGameplayEffectRemovedDelegate(), and UE_API.
Referenced by OnAnyGameplayEffectRemovedDelegate().
OnAttributeAggregatorDirty()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnAttributeAggregatorDirty (FAggregator * Aggregator, FGameplayAttribute Attribute, bool FromRecursiveCall = false) private
Called when a specific attribute aggregator value changes, gameplay effects refresh their values when this happens.
References Attribute, FAggregator, OnAttributeAggregatorDirty(), and UE_API.
Referenced by OnAttributeAggregatorDirty().
OnClientActivateAbilityCaughtUp()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnClientActivateAbilityCaughtUp (FGameplayAbilitySpecHandle AbilityToActivate, FPredictionKey::KeyType PredictionKey) protected
References OnClientActivateAbilityCaughtUp(), PredictionKey, and UE_API.
Referenced by OnClientActivateAbilityCaughtUp().
OnClientPrintDebug_Response()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnClientPrintDebug_Response (const TArray< FString > & Strings, int32 GameFlags) private virtual
References const, GameFlags, int32, OnClientPrintDebug_Response(), Snapshot, and UE_API.
Referenced by OnClientPrintDebug_Response().
OnComponentDestroyed()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnComponentDestroyed (bool bDestroyingHierarchy) override virtual
Called when a component is destroyed.
Parameters
bDestroyingHierarchy - True if the entire component hierarchy is being torn down, allows avoiding expensive operations
Reimplemented from UActorComponent.
References OnComponentDestroyed(), override, and UE_API.
Referenced by OnComponentDestroyed().
OnGameplayEffectAppliedToSelf()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnGameplayEffectAppliedToSelf (UAbilitySystemComponent * Source, const FGameplayEffectSpec & SpecApplied, FActiveGameplayEffectHandle ActiveHandle) private
References const, FGameplayEffectSpec, OnGameplayEffectAppliedToSelf(), Source, and UE_API.
Referenced by OnGameplayEffectAppliedToSelf().
OnGameplayEffectAppliedToTarget()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnGameplayEffectAppliedToTarget (UAbilitySystemComponent * Target, const FGameplayEffectSpec & SpecApplied, FActiveGameplayEffectHandle ActiveHandle) private
This ASC has successfully applied a GE to something (potentially itself)
References const, FGameplayEffectSpec, OnGameplayEffectAppliedToTarget(), Target, and UE_API.
Referenced by OnGameplayEffectAppliedToTarget().
OnGameplayEffectDurationChange()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnGameplayEffectDurationChange (struct FActiveGameplayEffect & ActiveEffect) private virtual
Called when the duration of a gameplay effect has changed.
References FActiveGameplayEffect, OnGameplayEffectDurationChange(), and UE_API.
Referenced by OnGameplayEffectDurationChange().
OnGameplayEffectInhibitionChangedDelegate()
GAMEPLAYABILITIES_API FOnActiveGameplayEffectInhibitionChanged * UAbilitySystemComponent::OnGameplayEffectInhibitionChangedDelegate (FActiveGameplayEffectHandle Handle) private
References Handle, OnGameplayEffectInhibitionChangedDelegate(), and UE_API.
Referenced by OnGameplayEffectInhibitionChangedDelegate().
OnGameplayEffectRemoved_InfoDelegate()
GAMEPLAYABILITIES_API FOnActiveGameplayEffectRemoved_Info * UAbilitySystemComponent::OnGameplayEffectRemoved_InfoDelegate (FActiveGameplayEffectHandle Handle) private
References Handle, OnGameplayEffectRemoved_InfoDelegate(), and UE_API.
Referenced by OnGameplayEffectRemoved_InfoDelegate().
OnGameplayEffectStackChangeDelegate()
GAMEPLAYABILITIES_API FOnActiveGameplayEffectStackChange * UAbilitySystemComponent::OnGameplayEffectStackChangeDelegate (FActiveGameplayEffectHandle Handle) private
References Handle, OnGameplayEffectStackChangeDelegate(), and UE_API.
Referenced by OnGameplayEffectStackChangeDelegate().
OnGameplayEffectTimeChangeDelegate()
GAMEPLAYABILITIES_API FOnActiveGameplayEffectTimeChange * UAbilitySystemComponent::OnGameplayEffectTimeChangeDelegate (FActiveGameplayEffectHandle Handle) private
References Handle, OnGameplayEffectTimeChangeDelegate(), and UE_API.
Referenced by OnGameplayEffectTimeChangeDelegate().
OnGiveAbility()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnGiveAbility (FGameplayAbilitySpec & AbilitySpec) protected virtual
Will be called from GiveAbility or from OnRep.
Initializes events (triggers and inputs) with the given ability
References FGameplayAbilitySpec, and UE_API.
OnMagnitudeDependencyChange()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnMagnitudeDependencyChange (FActiveGameplayEffectHandle Handle, const FAggregator * ChangedAggregator) private
Called when attribute magnitudes change, to forward information to dependent gameplay effects.
References const, FAggregator, Handle, OnMagnitudeDependencyChange(), and UE_API.
Referenced by OnMagnitudeDependencyChange().
OnPeriodicGameplayEffectExecuteOnSelf()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnPeriodicGameplayEffectExecuteOnSelf (UAbilitySystemComponent * Source, const FGameplayEffectSpec & SpecExecuted, FActiveGameplayEffectHandle ActiveHandle) private
References const, FGameplayEffectSpec, OnPeriodicGameplayEffectExecuteOnSelf(), Source, and UE_API.
Referenced by OnPeriodicGameplayEffectExecuteOnSelf().
OnPeriodicGameplayEffectExecuteOnTarget()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnPeriodicGameplayEffectExecuteOnTarget (UAbilitySystemComponent * Target, const FGameplayEffectSpec & SpecExecuted, FActiveGameplayEffectHandle ActiveHandle) private
References const, FGameplayEffectSpec, OnPeriodicGameplayEffectExecuteOnTarget(), Target, and UE_API.
Referenced by OnPeriodicGameplayEffectExecuteOnTarget().
OnPlayerControllerSet()
virtual void UAbilitySystemComponent::OnPlayerControllerSet () inline virtual
called when the ASC's AbilityActorInfo has a PlayerController set.
Definition at line 1563 of file AbilitySystemComponent.h.
References OnPlayerControllerSet().
Referenced by OnPlayerControllerSet().
OnPredictiveGameplayCueCatchup()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnPredictiveGameplayCueCatchup (FGameplayTag Tag) private virtual
Called for predictively added gameplay cue.
Needs to remove tag count and possible invoke OnRemove event if misprediction
References OnPredictiveGameplayCueCatchup(), and UE_API.
Referenced by OnPredictiveGameplayCueCatchup().
OnPredictiveMontageRejected()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnPredictiveMontageRejected (UAnimMontage * PredictiveMontage) protected
Called when a prediction key that played a montage is rejected.
References OnPredictiveMontageRejected(), and UE_API.
Referenced by OnPredictiveMontageRejected().
OnRegister()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnRegister () override virtual
Called when a component is registered, after Scene is set, but before CreateRenderState_Concurrent or OnCreatePhysicsState are called.
Reimplemented from UActorComponent.
References OnRegister(), override, and UE_API.
Referenced by OnRegister().
OnRemoveAbility()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnRemoveAbility (FGameplayAbilitySpec & AbilitySpec) protected virtual
Will be called from RemoveAbility or from OnRep.
Unbinds inputs with the given ability
References FGameplayAbilitySpec, and UE_API.
OnServerPrintDebug_Request()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnServerPrintDebug_Request () private virtual
Virtual function games can override to do their own stuff when either ServerPrintDebug function runs on the server.
References UE_API.
OnShowDebugInfo()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnShowDebugInfo (AHUD * HUD, UCanvas * Canvas, const FDebugDisplayInfo & DisplayInfo, float & YL, float & YPos) static private
References UE_API.
OnTagUpdated()
virtual void UAbilitySystemComponent::OnTagUpdated (const FGameplayTag & Tag, bool TagExists) inline protected virtual
Definition at line 1923 of file AbilitySystemComponent.h.
References const, and OnTagUpdated().
Referenced by OnTagUpdated(), and UpdateTagMap().
OnUnregister()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::OnUnregister () override virtual
Called when a component is unregistered.
Called after DestroyRenderState_Concurrent and OnDestroyPhysicsState are called.
Reimplemented from UActorComponent.
References OnUnregister(), override, and UE_API.
Referenced by OnUnregister().
PlayMontage()
virtual GAMEPLAYABILITIES_API float UAbilitySystemComponent::PlayMontage (UGameplayAbility * AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimMontage * Montage, float InPlayRate, FName StartSectionName = NAME_None, float StartTimeSeconds = 0.0f) private virtual
Plays a montage and handles replication and prediction based on passed in ability/activation info.
References ActivationInfo, InPlayRate, Montage, PlayMontage(), and UE_API.
Referenced by PlayMontage().
PlayMontageInternal()
GAMEPLAYABILITIES_API float UAbilitySystemComponent::PlayMontageInternal (UGameplayAbility * AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimMontage * Montage, float InPlayRate, FName StartSectionName, float StartTimeSeconds, TFunctionRef< void(FGameplayAbilityRepAnimMontage &)> MutateRepAnimMontageFunction) private
References ActivationInfo, InPlayRate, Montage, and UE_API.
PlayMontageSimulated()
virtual GAMEPLAYABILITIES_API float UAbilitySystemComponent::PlayMontageSimulated (UAnimMontage * Montage, float InPlayRate, FName StartSectionName = NAME_None) private virtual
Plays a montage without updating replication/prediction structures.
Used by simulated proxies when replication tells them to play a montage.
References InPlayRate, Montage, PlayMontageSimulated(), and UE_API.
Referenced by PlayMontageSimulated().
PlaySlotAnimationAsDynamicMontage()
virtual GAMEPLAYABILITIES_API UAnimMontage * UAbilitySystemComponent::PlaySlotAnimationAsDynamicMontage (UGameplayAbility * AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimSequenceBase * AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate = 1.f, float StartTimeSeconds = 0.0f) private virtual
References ActivationInfo, InPlayRate, PlaySlotAnimationAsDynamicMontage(), and UE_API.
Referenced by PlaySlotAnimationAsDynamicMontage().
PlaySlotAnimationAsDynamicMontage_WithFractionalLoops()
virtual GAMEPLAYABILITIES_API UAnimMontage * UAbilitySystemComponent::PlaySlotAnimationAsDynamicMontage_WithFractionalLoops (UGameplayAbility * AnimatingAbility, FGameplayAbilityActivationInfo ActivationInfo, UAnimSequenceBase * AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate = 1.f, float StartTimeSeconds = 0.0f, float PlayCount = 1.0f) private virtual
References ActivationInfo, InPlayRate, PlaySlotAnimationAsDynamicMontage_WithFractionalLoops(), and UE_API.
Referenced by PlaySlotAnimationAsDynamicMontage_WithFractionalLoops().
PlaySlotAnimationAsDynamicMontage_WithFractionalLoopsSimulated()
virtual GAMEPLAYABILITIES_API UAnimMontage * UAbilitySystemComponent::PlaySlotAnimationAsDynamicMontage_WithFractionalLoopsSimulated (UAnimSequenceBase * AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate = 1.f, float PlayCount = 1.0f) private virtual
References InPlayRate, PlaySlotAnimationAsDynamicMontage_WithFractionalLoopsSimulated(), and UE_API.
Referenced by PlaySlotAnimationAsDynamicMontage_WithFractionalLoopsSimulated().
PlaySlotAnimationAsDynamicMontageSimulated()
virtual GAMEPLAYABILITIES_API UAnimMontage * UAbilitySystemComponent::PlaySlotAnimationAsDynamicMontageSimulated (UAnimSequenceBase * AnimAsset, FName SlotName, float BlendInTime, float BlendOutTime, float InPlayRate = 1.f) private virtual
References InPlayRate, PlaySlotAnimationAsDynamicMontageSimulated(), and UE_API.
Referenced by PlaySlotAnimationAsDynamicMontageSimulated().
PostNetReceive()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::PostNetReceive () override virtual
Called right after receiving a bunch.
Reimplemented from UObject.
References override, PostNetReceive(), and UE_API.
Referenced by PostNetReceive().
PreNetReceive()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::PreNetReceive () override virtual
Called right before receiving a bunch.
Reimplemented from UObject.
References override, PreNetReceive(), and UE_API.
Referenced by PreNetReceive().
PrintAllGameplayEffects()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::PrintAllGameplayEffects () const private
Print a debug list of all gameplay effects.
References UE_API.
PrintDebug()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::PrintDebug () private virtual
References UE_API.
ReadyForReplication()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ReadyForReplication () override virtual
ReadyForReplication gets called on replicated components when their owning actor is officially ready for replication.
Called after InitializeComponent but before BeginPlay. From there it will only be set false when the component is destroyed. This is where you want to register your replicated subobjects if you already possess some. A component can get replicated before HasBegunPlay() is true if inside a tick or in BeginPlay() an RPC is called on it. Requires component to be registered, initialized and set to replicate.
Reimplemented from UGameplayTasksComponent.
References override, ReadyForReplication(), and UE_API.
Referenced by ReadyForReplication().
RecomputeGameplayEffectStartTimes()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::RecomputeGameplayEffectStartTimes (const float WorldTime, const float ServerWorldTime) private virtual
Called whenever the server time replicates via the game state to keep our cooldown timers in sync with the server.
References const, RecomputeGameplayEffectStartTimes(), and UE_API.
Referenced by RecomputeGameplayEffectStartTimes().
RefreshAbilityActorInfo()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RefreshAbilityActorInfo ()
This will refresh the Ability's ActorInfo structure based on the current ActorInfo.
That is, AvatarActor will be the same but we will look for new AnimInstance, MovementComponent, PlayerController, etc.
References AbilityOriginalPredictionKey, Client, CurrentPredictionKey, Server, and UE_API.
RegisterAndCallGameplayTagEvent()
GAMEPLAYABILITIES_API FDelegateHandle UAbilitySystemComponent::RegisterAndCallGameplayTagEvent (FGameplayTag Tag, FOnGameplayEffectTagCountChanged::FDelegate Delegate, EGameplayTagEventType::Type EventType = EGameplayTagEventType::NewOrRemoved) private
Register a tag event and immediately call it.
References UE_API.
RegisterGameplayAttributeEvent()
GAMEPLAYABILITIES_API FOnGameplayAttributeChange & UAbilitySystemComponent::RegisterGameplayAttributeEvent (FGameplayAttribute Attribute) private
Register for when an attribute value changes, should be replaced by GetGameplayAttributeValueChangeDelegate.
References Attribute, RegisterGameplayAttributeEvent(), and UE_API.
Referenced by RegisterGameplayAttributeEvent().
RegisterGameplayTagEvent()
GAMEPLAYABILITIES_API FOnGameplayEffectTagCountChanged & UAbilitySystemComponent::RegisterGameplayTagEvent (FGameplayTag Tag, EGameplayTagEventType::Type EventType = EGameplayTagEventType::NewOrRemoved) private
Allow events to be registered for specific gameplay tags being added or removed.
References UE_API.
RegisterGenericGameplayTagEvent()
GAMEPLAYABILITIES_API FOnGameplayEffectTagCountChanged & UAbilitySystemComponent::RegisterGenericGameplayTagEvent () private
Returns multicast delegate that is invoked whenever a tag is added or removed (but not if just count is increased.
Only for 'new' and 'removed' events)
References UE_API.
RemoteEndOrCancelAbility()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoteEndOrCancelAbility (FGameplayAbilitySpecHandle AbilityToEnd, FGameplayAbilityActivationInfo ActivationInfo, bool bWasCanceled) protected
Called by ServerEndAbility and ClientEndAbility; avoids code duplication.
References ActivationInfo, RemoteEndOrCancelAbility(), and UE_API.
Referenced by RemoteEndOrCancelAbility().
RemoveActiveEffects()
virtual GAMEPLAYABILITIES_API int32 UAbilitySystemComponent::RemoveActiveEffects (const FGameplayEffectQuery & Query, int32 StacksToRemove = -1) private virtual
Removes all active effects that match given query.
StacksToRemove=-1 will remove all stacks.
References const, int32, RemoveActiveEffects(), StacksToRemove, and UE_API.
Referenced by RemoveActiveEffects().
RemoveActiveGameplayEffect_AllowClientRemoval()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveActiveGameplayEffect_AllowClientRemoval (FActiveGameplayEffectHandle Handle, int32 StacksToRemove = -1) protected
A version of RemoveActiveGameplayEffect that allows us to remove it even when we don't have authority.
References Handle, int32, RemoveActiveGameplayEffect_AllowClientRemoval(), StacksToRemove, and UE_API.
Referenced by RemoveActiveGameplayEffect_AllowClientRemoval().
RemoveAllGameplayCues()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveAllGameplayCues () private
Removes any GameplayCue added on its own, i.e.
not as part of a GameplayEffect.
References RemoveAllGameplayCues(), and UE_API.
Referenced by RemoveAllGameplayCues().
RemoveAllReplicatedInstancedAbilities()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveAllReplicatedInstancedAbilities () protected
Unregister all the gameplay abilities of this component.
References UE_API.
RemoveAllSpawnedAttributes()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveAllSpawnedAttributes () private
Remove all attribute sets.
References RemoveAllSpawnedAttributes(), and UE_API.
Referenced by RemoveAllSpawnedAttributes().
RemoveGameplayCue()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveGameplayCue (const FGameplayTag GameplayCueTag) private
Remove a persistent gameplay cue.
References const, RemoveGameplayCue(), and UE_API.
Referenced by RemoveGameplayCue().
RemoveGameplayCue_Internal()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveGameplayCue_Internal (const FGameplayTag GameplayCueTag, FActiveGameplayCueContainer & GameplayCueContainer) protected virtual
References const, FActiveGameplayCueContainer, RemoveGameplayCue_Internal(), and UE_API.
Referenced by RemoveGameplayCue_Internal().
RemoveGameplayCue_MinimalReplication()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveGameplayCue_MinimalReplication (const FGameplayTag GameplayCueTag) private
Remove gameplaycue for minimal replication mode.
Should only be called in paths that would replicate gameplaycues in other ways (through GE for example) if not in minimal replication mode
References const, RemoveGameplayCue_MinimalReplication(), and UE_API.
Referenced by RemoveGameplayCue_MinimalReplication().
RemoveGameplayEventTagContainerDelegate()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveGameplayEventTagContainerDelegate (const FGameplayTagContainer & TagFilter, FDelegateHandle DelegateHandle) private
Remotes previously registered delegate.
References UE_API.
RemoveLooseGameplayTag()
FORCEINLINE void UAbilitySystemComponent::RemoveLooseGameplayTag (const FGameplayTag & GameplayTag, int32 Count = 1) inline private
Definition at line 664 of file AbilitySystemComponent.h.
References Count, FORCEINLINE, int32, and UpdateTagMap().
RemoveLooseGameplayTags()
FORCEINLINE void UAbilitySystemComponent::RemoveLooseGameplayTags (const FGameplayTagContainer & GameplayTags, int32 Count = 1) inline private
Definition at line 669 of file AbilitySystemComponent.h.
References Count, FORCEINLINE, GameplayTags, int32, and UpdateTagMap().
RemoveMinimalReplicationGameplayTag()
FORCEINLINE void UAbilitySystemComponent::RemoveMinimalReplicationGameplayTag (const FGameplayTag & GameplayTag) inline private
Definition at line 733 of file AbilitySystemComponent.h.
References FORCEINLINE, and GetMinimalReplicationTags_Mutable().
RemoveMinimalReplicationGameplayTags()
FORCEINLINE void UAbilitySystemComponent::RemoveMinimalReplicationGameplayTags (const FGameplayTagContainer & GameplayTags) inline private
Definition at line 738 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTags, and GetMinimalReplicationTags_Mutable().
RemoveReplicatedInstancedAbility()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveReplicatedInstancedAbility (UGameplayAbility * GameplayAbility) protected
Remove a gameplay ability associated to this component.
References UE_API.
RemoveReplicatedLooseGameplayTag()
FORCEINLINE void UAbilitySystemComponent::RemoveReplicatedLooseGameplayTag (const FGameplayTag & GameplayTag) inline private
Definition at line 704 of file AbilitySystemComponent.h.
References FORCEINLINE, and GetReplicatedLooseTags_Mutable().
RemoveReplicatedLooseGameplayTags()
FORCEINLINE void UAbilitySystemComponent::RemoveReplicatedLooseGameplayTags (const FGameplayTagContainer & GameplayTags) inline private
Definition at line 709 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTags, and GetReplicatedLooseTags_Mutable().
RemoveSpawnedAttribute()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::RemoveSpawnedAttribute (UAttributeSet * Attribute) private
Remove an existing attribute set.
References Attribute, RemoveSpawnedAttribute(), and UE_API.
Referenced by RemoveSpawnedAttribute().
ReplicateEndOrCancelAbility()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ReplicateEndOrCancelAbility (FGameplayAbilitySpecHandle Handle, FGameplayAbilityActivationInfo ActivationInfo, UGameplayAbility * Ability, bool bWasCanceled) private virtual
Replicate that an ability has ended/canceled, to the client or server as appropriate.
References ActivationInfo, Handle, and UE_API.
ReplicateSubobjects()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::ReplicateSubobjects (class UActorChannel * Channel, class FOutBunch * Bunch, FReplicationFlags * RepFlags) override virtual
Allows a component to replicate other subobject on the actor.
Must return true if any data gets serialized into the bunch. This method is used only when bReplicateUsingRegisteredSubObjectList is false. Otherwise this function is not called and only the ReplicatedSubObjects list is used.
Reimplemented from UGameplayTasksComponent.
References override, ReplicateSubobjects(), and UE_API.
Referenced by ReplicateSubobjects().
ResetTagMap()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::ResetTagMap () protected
References ResetTagMap(), and UE_API.
Referenced by ResetTagMap().
ServerAbilityRPCBatch_Internal()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::ServerAbilityRPCBatch_Internal (FServerAbilityRPCBatch & BatchInfo) private virtual
References UE_API.
SetActiveGameplayEffectInhibit()
virtual GAMEPLAYABILITIES_API FActiveGameplayEffectHandle UAbilitySystemComponent::SetActiveGameplayEffectInhibit (FActiveGameplayEffectHandle && ActiveGEHandle, bool bInhibit, bool bInvokeGameplayCueEvents) private virtual
(Un-)Inhibit an Active Gameplay Effect so it may be disabled (and perform some disabling actions, such as removing tags).
An inhibited Active Gameplay Effect will lay dormant for re-enabling on some condition (usually tags). When it's uninhibited, it will reapply some of its functionality. NOTE: The passed-in ActiveGEHandle is no longer valid. Use the returned FActiveGameplayEffectHandle to determine if the Active GE Handle is still active.
References bInhibit, bInvokeGameplayCueEvents, SetActiveGameplayEffectInhibit(), and UE_API.
Referenced by SetActiveGameplayEffectInhibit().
SetAvatarActor()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetAvatarActor (AActor * InAvatarActor)
Changes the avatar actor, leaves the owner actor the same.
References SetAvatarActor(), and UE_API.
Referenced by SetAvatarActor().
SetAvatarActor_Direct()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetAvatarActor_Direct (AActor * NewAvatarActor)
References UE_API.
SetBaseAttributeValueFromReplication() [1/2]
void UAbilitySystemComponent::SetBaseAttributeValueFromReplication (const FGameplayAttribute & Attribute, const FGameplayAttributeData & NewValue, const FGameplayAttributeData & OldValue) inline private
Call from OnRep functions to set the attribute base value on the client.
Definition at line 818 of file AbilitySystemComponent.h.
References Attribute, and NewValue.
SetBaseAttributeValueFromReplication() [2/2]
void UAbilitySystemComponent::SetBaseAttributeValueFromReplication (const FGameplayAttribute & Attribute, float NewValue, float OldValue) inline private
Call from OnRep functions to set the attribute base value on the client.
Definition at line 812 of file AbilitySystemComponent.h.
References Attribute, and NewValue.
SetBlockAbilityBindingsArray()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetBlockAbilityBindingsArray (FGameplayAbilityInputBinds BindInfo) private virtual
Initializes BlockedAbilityBindings variable.
References SetBlockAbilityBindingsArray(), and UE_API.
Referenced by SetBlockAbilityBindingsArray().
SetBlockedAbilityBindings()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetBlockedAbilityBindings (const TArray< uint8 > & NewBlockedAbilityBindings) protected
References const, SetBlockedAbilityBindings(), and UE_API.
Referenced by SetBlockedAbilityBindings().
SetClientDebugStrings()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetClientDebugStrings (TArray< FString > && NewClientDebugStrings) private
References SetClientDebugStrings(), and UE_API.
Referenced by SetClientDebugStrings().
SetLooseGameplayTagCount()
FORCEINLINE void UAbilitySystemComponent::SetLooseGameplayTagCount (const FGameplayTag & GameplayTag, int32 NewCount) inline private
Definition at line 674 of file AbilitySystemComponent.h.
References FORCEINLINE, int32, and SetTagMapCount().
SetMinimalReplicationTags()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetMinimalReplicationTags (const FMinimalReplicationTagCountMap & NewMinimalReplicationTags) protected
References const, SetMinimalReplicationTags(), and UE_API.
Referenced by SetMinimalReplicationTags().
SetMontageRepAnimPositionMethod()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetMontageRepAnimPositionMethod (ERepAnimPositionMethod InMethod) private
Method to set the replication method for the position in the montage.
References SetMontageRepAnimPositionMethod(), and UE_API.
Referenced by SetMontageRepAnimPositionMethod().
SetNumericAttribute_Internal()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetNumericAttribute_Internal (const FGameplayAttribute & Attribute, float & NewFloatValue) protected
Actually pushes the final attribute value to the attribute set's property.
Should not be called by outside code since this does not go through the attribute aggregator system.
References Attribute, const, SetNumericAttribute_Internal(), and UE_API.
Referenced by SetNumericAttribute_Internal().
SetNumericAttributeBase()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetNumericAttributeBase (const FGameplayAttribute & Attribute, float NewBaseValue) private
Sets the base value of an attribute.
Existing active modifiers are NOT cleared and will act upon the new base value.
References Attribute, const, SetNumericAttributeBase(), and UE_API.
Referenced by SetNumericAttributeBase().
SetOwnerActor()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetOwnerActor (AActor * NewOwnerActor)
References SetOwnerActor(), and UE_API.
Referenced by SetOwnerActor().
SetRemoveAbilityOnEnd()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetRemoveAbilityOnEnd (FGameplayAbilitySpecHandle AbilitySpecHandle) private
Sets an ability spec to remove when its finished.
If the spec is not currently active, it terminates it immediately. Also clears InputID of the Spec.
References SetRemoveAbilityOnEnd(), and UE_API.
Referenced by SetRemoveAbilityOnEnd().
SetRepAnimMontageInfo()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetRepAnimMontageInfo (const FGameplayAbilityRepAnimMontage & NewRepAnimMontageInfo) protected
References const, SetRepAnimMontageInfo(), and UE_API.
Referenced by SetRepAnimMontageInfo().
SetReplicatedLooseGameplayTagCount()
FORCEINLINE void UAbilitySystemComponent::SetReplicatedLooseGameplayTagCount (const FGameplayTag & GameplayTag, int32 NewCount) inline private
Definition at line 714 of file AbilitySystemComponent.h.
References FORCEINLINE, GetReplicatedLooseTags_Mutable(), and int32.
SetReplicationMode()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetReplicationMode (EGameplayEffectReplicationMode NewReplicationMode) private virtual
When true, we will not replicate active gameplay effects for this ability system component, so attributes and tags.
References SetReplicationMode(), and UE_API.
Referenced by SetReplicationMode().
SetServerDebugStrings()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetServerDebugStrings (TArray< FString > && NewServerDebugStrings) private
References SetServerDebugStrings(), and UE_API.
Referenced by SetServerDebugStrings().
SetSpawnedAttributes()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetSpawnedAttributes (const TArray< UAttributeSet * > & NewAttributeSet) private
Remove all current AttributeSets and register the ones in the passed array.
Note that it's better to call Add/Remove directly when possible.
References const, SetSpawnedAttributes(), and UE_API.
Referenced by SetSpawnedAttributes().
SetSpawnedAttributesListDirty()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::SetSpawnedAttributesListDirty () private
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and UE_API.
SetTagMapCount()
FORCEINLINE void UAbilitySystemComponent::SetTagMapCount (const FGameplayTag & Tag, int32 NewCount) inline private
Forcibly sets the number of instances of a given tag.
Definition at line 615 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTagCountContainer, and int32.
Referenced by SetLooseGameplayTagCount().
ShouldDoServerAbilityRPCBatch()
virtual bool UAbilitySystemComponent::ShouldDoServerAbilityRPCBatch () const inline private virtual
Definition at line 1335 of file AbilitySystemComponent.h.
References ShouldDoServerAbilityRPCBatch().
Referenced by ShouldDoServerAbilityRPCBatch().
ShouldRecordMontageReplication()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::ShouldRecordMontageReplication () const private virtual
Returns true if this component should record montage replication info.
References UE_API.
ShouldSendClientDebugStringsToServer()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemComponent::ShouldSendClientDebugStringsToServer () const private virtual
Determines whether to call ServerPrintDebug_Request or ServerPrintDebug_RequestWithStrings.
References UE_API.
StopMontageIfCurrent()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::StopMontageIfCurrent (const UAnimMontage & Montage, float OverrideBlendOutTime = -1.0f) private virtual
Stops current montage if it's the one given as the Montage param.
References const, Montage, StopMontageIfCurrent(), and UE_API.
Referenced by StopMontageIfCurrent().
TickComponent()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
Function called every frame on this ActorComponent.
Override this function to implement custom logic to be executed every frame. Only executes if the component is registered, and also PrimaryComponentTick.bCanEverTick must be set to true.
Parameters
DeltaTime - The time since the last tick.
TickType - The kind of tick this is, for example, are we paused, or 'simulating' in the editor
ThisTickFunction - Internal tick function struct that caused this to run
Reimplemented from UGameplayTasksComponent.
References DeltaTime, UActorComponent::FActorComponentTickFunction, override, TickComponent(), and UE_API.
Referenced by TickComponent().
TriggerAbilityFromGameplayEvent()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::TriggerAbilityFromGameplayEvent (FGameplayAbilitySpecHandle AbilityToTrigger, FGameplayAbilityActorInfo * ActorInfo, FGameplayTag Tag, const FGameplayEventData * Payload, UAbilitySystemComponent & Component) private
Triggers an ability from a gameplay event, will only trigger on local/server depending on execution flags.
References Component, const, TriggerAbilityFromGameplayEvent(), and UE_API.
Referenced by TriggerAbilityFromGameplayEvent().
UE_DEPRECATED() [1/11]
UAbilitySystemComponent::UE_DEPRECATED (4. 26, "This will be made private in future engine versions. Use SetBlockedAbilityBindings, GetBlockedAbilityBindings , or GetBlockedAbilityBindings_Mutable instead.") protected
Tracks abilities that are blocked based on input binding.
An ability is blocked if BlockedAbilityBindings[InputID] > 0
References Transient, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [2/11]
UAbilitySystemComponent::UE_DEPRECATED (4. 26, "This will be made private in future engine versions. Use SetClientDebugStrings, GetClientDebugStrings , or GetClientDebugStrings_Mutable instead.") private
References UPROPERTY().
UE_DEPRECATED() [3/11]
UAbilitySystemComponent::UE_DEPRECATED (4. 26, "This will be made private in future engine versions. Use SetMinimalReplicationTags, GetMinimalReplicationTags , or GetMinimalReplicationTags_Mutable instead.") protected
References UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [4/11]
UAbilitySystemComponent::UE_DEPRECATED (4. 26, "This will be made private in future engine versions. Use SetRepAnimMontageInfo, GetRepAnimMontageInfo , or GetRepAnimMontageInfo_Mutable instead.") protected
Data structure for replicating montage info to simulated clients.
References UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [5/11]
UAbilitySystemComponent::UE_DEPRECATED (4. 26, "This will be made private in future engine versions. Use SetServerDebugStrings, GetServerDebugStrings , or GetServerDebugStrings_Mutable instead.") private
References UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [6/11]
UAbilitySystemComponent::UE_DEPRECATED (5. 1, "This array will be made private. Use GetReplicatedInstancedAbilities, AddReplicatedInstancedAbility or RemoveReplicatedInstancedAbility instead.") protected
Full list of all instance-per-execution gameplay abilities associated with this component.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [7/11]
UAbilitySystemComponent::UE_DEPRECATED (5. 1, "This function will be made private. Use Add/Remove SpawnedAttributes instead") & private
References UE_API, and UE_DEPRECATED().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [8/11]
UAbilitySystemComponent::UE_DEPRECATED (5. 3, "FindAbilitySpecFromGEHandle was never accurate because a GameplayEffect can grant multiple GameplayAbilities. It now returns nullptr.") const private
Returns an ability spec from a GE handle.
If modifying call MarkAbilitySpecDirty
References const, FGameplayAbilitySpec, Handle, and UE_API.
UE_DEPRECATED() [9/11]
UAbilitySystemComponent::UE_DEPRECATED (5. 3, "Use OnImmunityBlockGameplayEffectDelegate directly. It is trigger from a UImmunityGameplayEffectComponent. You can create your own GameplayEffectComponent if you need different functionality.") const & protected
References UE_DEPRECATED().
UE_DEPRECATED() [10/11]
UAbilitySystemComponent::UE_DEPRECATED (5. 4, "ReinvokeActiveGameplayCues was unused and had logic inconsistent with predicting Gameplay Effects. You can implement it in your own project if desired.") private
Invokes the WhileActive event for all GCs on active, non inhibited, GEs.
This would typically be used on "respawn" or something where the mesh/avatar has changed
References UE_API.
UE_DEPRECATED() [11/11]
UAbilitySystemComponent::UE_DEPRECATED (5. 4, "Use SetActiveGameplayEffectInhibit with a MoveTemp(ActiveGEHandle) so it's clear the Handle is no longer valid. Check (then use) the returned FActiveGameplayEffectHandle to continue your operation.") private
Inhibit an active gameplay effect so that it is disabled, but not removed.
References UE_DEPRECATED().
UE_DEPRECATED_FORGAME()
UAbilitySystemComponent::UE_DEPRECATED_FORGAME (5. 5, "This shouldn't be public. Use RemoveActiveGameplayEffect (which won't allow non-authority to remove) or expose RemoveActiveGameplayEffect_AllowClientRemoval if your intent is to break that contract.") private
This only exists so it can be hooked up to a multicast delegate.
References Handle, int32, StacksToRemove, UE_API, and UE_DEPRECATED_FORGAME().
Referenced by UE_DEPRECATED_FORGAME().
UFUNCTION() [1/87]
UAbilitySystemComponent::UFUNCTION () const private
This is meant to be used to inhibit activating an ability from an input perspective.
(E.g., the menu is pulled up, another game mechanism is consuming all input, etc) This should only be called on locally owned players. This should not be used to game mechanics like silences or disables. Those should be done through gameplay effects.
References UGameplayTasksComponent::Category, const, and UE_API.
UFUNCTION() [2/87]
UAbilitySystemComponent::UFUNCTION () const & private
Attempts to activate every gameplay ability that matches the given tag and DoesAbilitySatisfyTagRequirements().
Returns true if anything attempts to activate. Can activate more than one ability and the ability may fail later. If bAllowRemoteActivation is true, it will remotely activate local/server abilities, if false it will only try to locally activate abilities.
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [3/87]
UAbilitySystemComponent::UFUNCTION () private
Attempts to activate the given ability, will check costs and requirements before doing so.
Returns true if it thinks it activated, but it may return false positives due to failure later in activation. If bAllowRemoteActivation is true, it will remotely activate local/server abilities, if false it will only try to locally activate the ability
References bAllowRemoteActivation, UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [4/87]
UAbilitySystemComponent::UFUNCTION () private
Attempts to activate the ability that is passed in.
This will check costs and requirements before doing so. Returns true if it thinks it activated, but it may return false positives due to failure later in activation. If bAllowRemoteActivation is true, it will remotely activate local/server abilities, if false it will only try to locally activate the ability
References bAllowRemoteActivation, UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [5/87]
UAbilitySystemComponent::UFUNCTION () private
Returns the current value of the given gameplay attribute, or zero if the attribute is not found.
NOTE: This doesn't take predicted gameplay effect modifiers into consideration, so the value may not be accurate on clients at all times.
Parameters
Attribute The gameplay attribute to query
bFound Set to true if the attribute exists in this component
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [6/87]
UAbilitySystemComponent::UFUNCTION () private
Raw accessor to ask the magnitude of a gameplay effect, not necessarily always correct.
How should outside code (UI, etc) ask things like 'how much is this gameplay effect modifying my damage by' (most likely we want to catch this on the backend - when damage is applied we can get a full dump/history of how the number got to where it is. But still we may need polling methods like below (how much would my damage be)
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [7/87]
UAbilitySystemComponent::UFUNCTION () private
Get the count of the specified source effect on the ability system component.
For non-stacking effects, this is the sum of all active instances. For stacking effects, this is the sum of all valid stack counts. If an instigator is specified, only effects from that instigator are counted.
Parameters
SourceGameplayEffect Effect to get the count of
OptionalInstigatorFilterComponent If specified, only count effects applied by this ability system component
Returns
Count of the specified source effect
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [8/87]
UAbilitySystemComponent::UFUNCTION () private
Get the count of the specified source effect on the ability system component.
For non-stacking effects, this is the sum of all active instances. For stacking effects, this is the sum of all valid stack counts. If an instigator is specified, only effects from that instigator are counted.
Parameters
SoftSourceGameplayEffect Effect to get the count of. If this is not currently loaded, the count is 0
OptionalInstigatorFilterComponent If specified, only count effects applied by this ability system component
Returns
Count of the specified source effect
References bEnforceOnGoingCheck, UGameplayTasksComponent::Category, const, int32, OptionalInstigatorFilterComponent, UE_API, and UFUNCTION().
UFUNCTION() [9/87]
UAbilitySystemComponent::UFUNCTION () const private
Returns the current count of the given gameplay tag.
This includes both loose tags, and tags granted by gameplay effects and abilities. This function can be called on the client, but it may not display the most current count on the server.
Parameters
GameplayTag The gameplay tag to query
References UGameplayTasksComponent::Category, const, int32, and UE_API.
UFUNCTION() [10/87]
UAbilitySystemComponent::UFUNCTION () private
Removes all active effects that apply any of the tags in Tags.
References UGameplayTasksComponent::Category, int32, Tags, UE_API, and UFUNCTION().
UFUNCTION() [11/87]
UAbilitySystemComponent::UFUNCTION () private
Removes all active effects that grant any of the tags in Tags.
References UGameplayTasksComponent::Category, int32, Tags, UE_API, and UFUNCTION().
UFUNCTION() [12/87]
UAbilitySystemComponent::UFUNCTION () private
Removes all active effects with captured source tags that contain any of the tags in Tags.
References UGameplayTasksComponent::Category, int32, Tags, UE_API, and UFUNCTION().
UFUNCTION() [13/87]
UAbilitySystemComponent::UFUNCTION () private
Removes all active effects that contain any of the tags in Tags.
References UGameplayTasksComponent::Category, int32, Tags, UE_API, and UFUNCTION().
UFUNCTION() [14/87]
UAbilitySystemComponent::UFUNCTION () const private
Returns list of active effects that have all of the passed in tags.
References UGameplayTasksComponent::Category, const, Tags, UE_API, and UFUNCTION().
UFUNCTION() [15/87]
UAbilitySystemComponent::UFUNCTION () private
Removes the specified GameplayEffect by Handle.
Parameters
Handle The handle of the gameplay effect to remove
StacksToRemove Number of stacks to remove, -1 means remove all
Returns
Whether the effect was successfully removed.
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [16/87]
UAbilitySystemComponent::UFUNCTION () const private
Create an EffectContext for the owner of this AbilitySystemComponent.
References UGameplayTasksComponent::Category, const, UE_API, and UFUNCTION().
UFUNCTION() [17/87]
UAbilitySystemComponent::UFUNCTION () private
Get an outgoing GameplayEffectSpec that is ready to be applied to other things.
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [18/87]
UAbilitySystemComponent::UFUNCTION () protected
References UE_API.
UFUNCTION() [19/87]
UAbilitySystemComponent::UFUNCTION () private
References UE_API, and UFUNCTION().
UFUNCTION() [20/87]
UAbilitySystemComponent::UFUNCTION () protected
References UE_API, and UFUNCTION().
UFUNCTION() [21/87]
UAbilitySystemComponent::UFUNCTION () private
References UE_API, and UFUNCTION().
UFUNCTION() [22/87]
UAbilitySystemComponent::UFUNCTION () private
Remove active gameplay effects whose backing definition are the specified gameplay effect class.
Parameters
GameplayEffect Class of gameplay effect to remove; Does nothing if left null
InstigatorAbilitySystemComponent If specified, will only remove gameplay effects applied from this instigator ability system component
StacksToRemove Number of stacks to remove, -1 means remove all
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [23/87]
UAbilitySystemComponent::UFUNCTION () private
Updates the level of an already applied gameplay effect.
The intention is that this is 'seemless' and doesnt behave like removing/reapplying
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [24/87]
UAbilitySystemComponent::UFUNCTION () private
Updates the level of an already applied gameplay effect.
The intention is that this is 'seemless' and doesnt behave like removing/reapplying
References UGameplayTasksComponent::Category, int32, NewLevel, UE_API, and UFUNCTION().
UFUNCTION() [25/87]
UAbilitySystemComponent::UFUNCTION () private
Disable or Enable a local user from being able to activate abilities.
This should only be used for input/UI etc related inhibition. Do not use for game mechanics.
References UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [26/87]
UAbilitySystemComponent::UFUNCTION () private
Any active targeting actors will be stopped and canceled, not returning any targeting data.
References UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [27/87]
UAbilitySystemComponent::UFUNCTION () private
Any active targeting actors will be told to stop and return current targeting data.
References UGameplayTasksComponent::Category, and UE_API.
UFUNCTION() [28/87]
UAbilitySystemComponent::UFUNCTION () private
Dynamically update the set-by-caller magnitude for an active gameplay effect.
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [29/87]
UAbilitySystemComponent::UFUNCTION () private
Dynamically update multiple set-by-caller magnitudes for an active gameplay effect.
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [30/87]
UAbilitySystemComponent::UFUNCTION () const & private
Removes the specified ability.
This will be ignored if the actor is not authoritative.
Parameters
Handle Ability Spec Handle of the ability we want to remove
References UGameplayTasksComponent::Category, const, Handle, UE_API, and UFUNCTION().
UFUNCTION() [31/87]
UAbilitySystemComponent::UFUNCTION () private
Wipes all 'given' abilities.
This will be ignored if the actor is not authoritative.
References UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [32/87]
UAbilitySystemComponent::UFUNCTION () private pure virtual
Clears all abilities bound to a given Input ID This will be ignored if the actor is not authoritative.
Parameters
InputID The numeric Input ID of the abilities to remove
References UGameplayTasksComponent::Category, InputID, int32, UE_API, and UFUNCTION().
UFUNCTION() [33/87]
UAbilitySystemComponent::UFUNCTION () protected
References Client, and UFUNCTION().
UFUNCTION() [34/87]
UAbilitySystemComponent::UFUNCTION () protected
References Client, PredictionKey, UE_API, and UFUNCTION().
UFUNCTION() [35/87]
UAbilitySystemComponent::UFUNCTION () protected
References Client, and UFUNCTION().
UFUNCTION() [36/87]
UAbilitySystemComponent::UFUNCTION () protected
References ActivationInfo, Client, UE_API, and UFUNCTION().
UFUNCTION() [37/87]
UAbilitySystemComponent::UFUNCTION () protected
References ActivationInfo, Client, UE_API, and UFUNCTION().
UFUNCTION() [38/87]
UAbilitySystemComponent::UFUNCTION () const & private
References Client.
UFUNCTION() [39/87]
UAbilitySystemComponent::UFUNCTION () protected
References Client, UE_API, and UFUNCTION().
UFUNCTION() [40/87]
UAbilitySystemComponent::UFUNCTION () & private
Returns an array with all abilities that match the provided Gameplay Tag Query.
Parameters
OutAbilityHandles This array will be filled with matching Ability Spec Handles
Query Gameplay Tag Query to match
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [41/87]
UAbilitySystemComponent::UFUNCTION () & private
Returns an array with all abilities bound to an Input ID value.
Parameters
OutAbilityHandles This array will be filled with matching Ability Spec Handles
InputID The Input ID to match
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [42/87]
UAbilitySystemComponent::UFUNCTION () & private
Returns an array with all abilities that match the provided tags.
Parameters
OutAbilityHandles This array will be filled with matching Ability Spec Handles
Tags Gameplay Tags to match
bExactMatch If true, tags must be matched exactly. Otherwise, abilities matching any of the tags will be returned
References UGameplayTasksComponent::Category, and UFUNCTION().
UFUNCTION() [43/87]
UAbilitySystemComponent::UFUNCTION () const & private
Returns an array with all granted ability handles NOTE: currently this doesn't include abilities that are mid-activation.
Parameters
OutAbilityHandles This array will be filled with the granted Ability Spec Handles
References UGameplayTasksComponent::Category, const, UE_API, and UFUNCTION().
UFUNCTION() [44/87]
UAbilitySystemComponent::UFUNCTION () & private
Returns a list of all attributes for this abilty system component.
References UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [45/87]
UAbilitySystemComponent::UFUNCTION () private
Sends a local player Input Cancel event, notifying abilities.
References UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [46/87]
UAbilitySystemComponent::UFUNCTION () private
Sends a local player Input Confirm event, notifying abilities.
References UGameplayTasksComponent::Category, UE_API, and UFUNCTION().
UFUNCTION() [47/87]
UAbilitySystemComponent::UFUNCTION () const private
References const, EffectContext, IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueAdded(), override, PredictionKey, UE_API, and UFUNCTION().
UFUNCTION() [48/87]
UAbilitySystemComponent::UFUNCTION () const private
References UFUNCTION().
UFUNCTION() [49/87]
UAbilitySystemComponent::UFUNCTION () const & private
References const, IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueAddedAndWhileActive_FromSpec(), override, PredictionKey, UE_API, and UFUNCTION().
UFUNCTION() [50/87]
UAbilitySystemComponent::UFUNCTION () const private
References const, IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueAddedAndWhileActive_WithParams(), override, PredictionKey, UE_API, and UFUNCTION().
UFUNCTION() [51/87]
UAbilitySystemComponent::UFUNCTION () const private
References UFUNCTION().
UFUNCTION() [52/87]
UAbilitySystemComponent::UFUNCTION () const private
References UFUNCTION().
UFUNCTION() [53/87]
UAbilitySystemComponent::UFUNCTION () const private
References UFUNCTION().
UFUNCTION() [54/87]
UAbilitySystemComponent::UFUNCTION () const private
References const, IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCuesAddedAndWhileActive_WithParams(), override, PredictionKey, UE_API, and UFUNCTION().
UFUNCTION() [55/87]
UAbilitySystemComponent::UFUNCTION () const private
References const, EffectContext, IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCuesExecuted(), override, PredictionKey, UE_API, and UFUNCTION().
UFUNCTION() [56/87]
UAbilitySystemComponent::UFUNCTION () const private
References const, IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCuesExecuted_WithParams(), override, PredictionKey, UE_API, and UFUNCTION().
UFUNCTION() [57/87]
UAbilitySystemComponent::UFUNCTION ()
References UE_API, and UFUNCTION().
UFUNCTION() [58/87]
UAbilitySystemComponent::UFUNCTION ()
References UE_API, and UFUNCTION().
UFUNCTION() [59/87]
UAbilitySystemComponent::UFUNCTION ()
References UE_API.
UFUNCTION() [60/87]
UAbilitySystemComponent::UFUNCTION () const & private
References const, and UE_API.
UFUNCTION() [61/87]
UAbilitySystemComponent::UFUNCTION ()
References UFUNCTION().
UFUNCTION() [62/87]
UAbilitySystemComponent::UFUNCTION () private
References UGameplayTasksComponent::Category, InputID, int32, UE_API, and UFUNCTION().
UFUNCTION() [63/87]
UAbilitySystemComponent::UFUNCTION () private
Sends a local player Input Released event with the provided Input ID, notifying any bound abilities.
Parameters
InputID The Input ID to match
References UGameplayTasksComponent::Category, InputID, int32, UE_API, and UFUNCTION().
UFUNCTION() [64/87]
UAbilitySystemComponent::UFUNCTION () private
References Server, and UE_API.
UFUNCTION() [65/87]
UAbilitySystemComponent::UFUNCTION () protected
References ActivationInfo, Server, UE_API, and UFUNCTION().
UFUNCTION() [66/87]
UAbilitySystemComponent::UFUNCTION () protected
RPC function called from CurrentMontageJumpToSection, replicates to other clients.
References UFUNCTION().
UFUNCTION() [67/87]
UAbilitySystemComponent::UFUNCTION () protected
RPC function called from CurrentMontageSetNextSectionName, replicates to other clients.
References UFUNCTION().
UFUNCTION() [68/87]
UAbilitySystemComponent::UFUNCTION () protected
RPC function called from CurrentMontageSetPlayRate, replicates to other clients.
References UFUNCTION().
UFUNCTION() [69/87]
UAbilitySystemComponent::UFUNCTION () protected
References Server, and UFUNCTION().
UFUNCTION() [70/87]
UAbilitySystemComponent::UFUNCTION () private
Ask the server to send ability system debug information back to the client, via ClientPrintDebug_Response.
References Server, and UE_API.
UFUNCTION() [71/87]
UAbilitySystemComponent::UFUNCTION () const & private
Same as ServerPrintDebug_Request but this includes the client debug strings so that the server can embed them in replays.
References Server, and UE_API.
UFUNCTION() [72/87]
UAbilitySystemComponent::UFUNCTION ()
Direct Input state replication.
These will be called if bReplicateInputDirectly is true on the ability and is generally not a good thing to use. (Instead, prefer to use Generic Replicated Events).
References Server, UE_API, and UFUNCTION().
UFUNCTION() [73/87]
UAbilitySystemComponent::UFUNCTION ()
References Server, UE_API, and UFUNCTION().
UFUNCTION() [74/87]
UAbilitySystemComponent::UFUNCTION ()
Replicates targeting data to the server.
References Server.
UFUNCTION() [75/87]
UAbilitySystemComponent::UFUNCTION ()
Replicates to the server that targeting has been cancelled.
References Server, and UFUNCTION().
UFUNCTION() [76/87]
UAbilitySystemComponent::UFUNCTION () protected
References Server, and UFUNCTION().
UFUNCTION() [77/87]
UAbilitySystemComponent::UFUNCTION () protected
References Server, and UFUNCTION().
UFUNCTION() [78/87]
UAbilitySystemComponent::UFUNCTION () const inline private
Allows polling to see if a GameplayCue is active.
We expect most GameplayCue handling to be event based, but some cases we may need to check if a GameplayCue is active (Animation Blueprint for example)
Definition at line 936 of file AbilitySystemComponent.h.
References UGameplayTasksComponent::Category, const, HasMatchingGameplayTag(), UGameplayTasksComponent::meta, and UFUNCTION().
UFUNCTION() [79/87]
UAbilitySystemComponent::UFUNCTION () const private
Returns a reference to the Attribute Set instance, if one exists in this component.
Parameters
AttributeSetClass The type of attribute set to look for
bFound Set to true if an instance of the Attribute Set exists
References UGameplayTasksComponent::Category, const, UGameplayTasksComponent::meta, UE_API, and UFUNCTION().
UFUNCTION() [80/87]
UAbilitySystemComponent::UFUNCTION () const & private
Applies a previously created gameplay effect spec to this component.
References UGameplayTasksComponent::Category, const, UGameplayTasksComponent::meta, UE_API, and UFUNCTION().
UFUNCTION() [81/87]
UAbilitySystemComponent::UFUNCTION () const & private
Applies a previously created gameplay effect spec to a target.
References UGameplayTasksComponent::Category, and UGameplayTasksComponent::meta.
UFUNCTION() [82/87]
UAbilitySystemComponent::UFUNCTION () private
Apply a gameplay effect to self.
References UGameplayTasksComponent::Category, UGameplayTasksComponent::meta, and UFUNCTION().
UFUNCTION() [83/87]
UAbilitySystemComponent::UFUNCTION () private
Apply a gameplay effect to passed in target.
References UGameplayTasksComponent::Category, UGameplayTasksComponent::meta, and UFUNCTION().
UFUNCTION() [84/87]
UAbilitySystemComponent::UFUNCTION () private
Grants a Gameplay Ability and returns its handle.
This will be ignored if the actor is not authoritative.
Parameters
AbilityClass Type of ability to grant
Level Level to grant the ability at
InputID Input ID value to bind ability activation to.
References UGameplayTasksComponent::Category, UGameplayTasksComponent::meta, and UFUNCTION().
UFUNCTION() [85/87]
UAbilitySystemComponent::UFUNCTION () private
Grants a Gameplay Ability, activates it once, and removes it.
This will be ignored if the actor is not authoritative.
Parameters
AbilityClass Type of ability to grant
Level Level to grant the ability at
InputID Input ID value to bind ability activation to.
References UGameplayTasksComponent::Category, InputID, int32, Level, UGameplayTasksComponent::meta, UE_API, and UFUNCTION().
UFUNCTION() [86/87]
UAbilitySystemComponent::UFUNCTION () const & private
Returns list of active effects, for a query.
References UGameplayTasksComponent::Category, const, UGameplayTasksComponent::meta, and UE_API.
UFUNCTION() [87/87]
UAbilitySystemComponent::UFUNCTION () private
References UGameplayTasksComponent::Category, and UGameplayTasksComponent::meta.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UnBlockAbilitiesWithTags()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::UnBlockAbilitiesWithTags (const FGameplayTagContainer & Tags) private
References Tags, and UE_API.
UnBlockAbilityByInputID()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::UnBlockAbilityByInputID (int32 InputID) private
References InputID, int32, and UE_API.
UninitializeComponent()
virtual GAMEPLAYABILITIES_API void UAbilitySystemComponent::UninitializeComponent () override virtual
Handle this component being Uninitialized.
Called from AActor::EndPlay only if bHasBeenInitialized is true
Reimplemented from UActorComponent.
References override, UE_API, and UninitializeComponent().
Referenced by UninitializeComponent().
UnregisterGameplayTagEvent()
GAMEPLAYABILITIES_API bool UAbilitySystemComponent::UnregisterGameplayTagEvent (FDelegateHandle DelegateHandle, FGameplayTag Tag, EGameplayTagEventType::Type EventType = EGameplayTagEventType::NewOrRemoved) private
Unregister previously added events.
References UE_API.
UPARAM()
UAbilitySystemComponent::UPARAM (meta = (Categories = "SetByCaller")) private
UpdateActiveGameplayEffectsReplicationCondition()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::UpdateActiveGameplayEffectsReplicationCondition () protected
References UE_API, and UpdateActiveGameplayEffectsReplicationCondition().
Referenced by UpdateActiveGameplayEffectsReplicationCondition().
UpdateMinimalReplicationGameplayCuesCondition()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::UpdateMinimalReplicationGameplayCuesCondition () protected
References UE_API, and UpdateMinimalReplicationGameplayCuesCondition().
Referenced by UpdateMinimalReplicationGameplayCuesCondition().
UpdateTagMap() [1/2]
FORCEINLINE void UAbilitySystemComponent::UpdateTagMap (const FGameplayTag & BaseTag, int32 CountDelta) inline private
Update the number of instances of a given tag and calls callback.
Definition at line 621 of file AbilitySystemComponent.h.
References FORCEINLINE, GameplayTagCountContainer, int32, and OnTagUpdated().
Referenced by AddLooseGameplayTag(), AddLooseGameplayTags(), RemoveLooseGameplayTag(), and RemoveLooseGameplayTags().
UpdateTagMap() [2/2]
FORCEINLINE void UAbilitySystemComponent::UpdateTagMap (const FGameplayTagContainer & Container, int32 CountDelta) inline private
Update the number of instances of a given tag and calls callback.
Definition at line 630 of file AbilitySystemComponent.h.
References Container, FORCEINLINE, int32, and UpdateTagMap_Internal().
UpdateTagMap_Internal()
GAMEPLAYABILITIES_API void UAbilitySystemComponent::UpdateTagMap_Internal (const FGameplayTagContainer & Container, int32 CountDelta) protected
References Container, int32, and UE_API.
Referenced by UpdateTagMap().
UPROPERTY() [1/21]
UAbilitySystemComponent::UPROPERTY () protected
Cached value of rather this is a simulated actor.
References UPROPERTY().
UPROPERTY() [2/21]
UAbilitySystemComponent::UPROPERTY () protected
Set if montage rep happens while we don't have the animinstance associated with us yet.
References UPROPERTY().
UPROPERTY() [3/21]
UAbilitySystemComponent::UPROPERTY () private
Suppress all GameplayCues on this component.
References UPROPERTY().
UPROPERTY() [4/21]
UAbilitySystemComponent::UPROPERTY () private
Suppress all ability granting through GEs on this component.
References UPROPERTY().
UPROPERTY() [5/21]
UAbilitySystemComponent::UPROPERTY () private
When enabled GameplayCue RPCs will be routed through the AvatarActor's IAbilitySystemReplicationProxyInterface rather than this component.
References UPROPERTY().
UPROPERTY() [6/21]
UAbilitySystemComponent::UPROPERTY () private
Rather activation is currently inhibited.
References UPROPERTY().
UPROPERTY() [7/21]
UAbilitySystemComponent::UPROPERTY () protected
List of all active gameplay cues (executed outside of Gameplay Effects)
References FActiveGameplayCueContainer, and UPROPERTY().
UPROPERTY() [8/21]
UAbilitySystemComponent::UPROPERTY () protected
Replicated gameplaycues when in minimal replication mode.
These are cues that would come normally come from ActiveGameplayEffects (but since we do not replicate AGE in minimal mode, they must be replicated through here)
References FActiveGameplayCueContainer, and UPROPERTY().
UPROPERTY() [9/21]
UAbilitySystemComponent::UPROPERTY () protected
Contains all of the gameplay effects that are currently active on this component.
References FActiveGameplayEffectsContainer, and UPROPERTY().
UPROPERTY() [10/21]
UAbilitySystemComponent::UPROPERTY () protected
Data structure for montages that were instigated locally (everything if server, predictive if client.
replicated if simulated proxy)
References UPROPERTY().
UPROPERTY() [11/21]
UAbilitySystemComponent::UPROPERTY () protected
The abilities we can activate.
-This will include CDOs for non instanced abilities and per-execution instanced abilities. -Actor-instanced abilities will be the actual instance (not CDO)
This array is not vital for things to work. It is a convenience thing for 'giving abilities to the actor'. But abilities could also work on things without an AbilitySystemComponent. For example an ability could be written to execute on a StaticMeshActor. As long as the ability doesn't require instancing or anything else that the AbilitySystemComponent would provide, then it doesn't need the component to function.
References UGameplayTasksComponent::Category, FGameplayAbilitySpecContainer, Transient, and UPROPERTY().
UPROPERTY() [12/21]
UAbilitySystemComponent::UPROPERTY () private
Container used for replicating loose gameplay tags.
References UPROPERTY().
UPROPERTY() [13/21]
UAbilitySystemComponent::UPROPERTY () private
The linked Anim Instance that this component will play montages in.
Use NAME_None for the main anim instance.
References UGameplayTasksComponent::Category, and UPROPERTY().
UPROPERTY() [14/21]
UAbilitySystemComponent::UPROPERTY ()
PredictionKeys, see more info in GameplayPrediction.h.
This has to come last in all replicated properties on the AbilitySystemComponent to ensure OnRep/callback order.
References Transient, and UPROPERTY().
UPROPERTY() [15/21]
UAbilitySystemComponent::UPROPERTY () private
References UGameplayTasksComponent::Category, and UPROPERTY().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [16/21]
UAbilitySystemComponent::UPROPERTY () private
List of currently active targeting actors.
References UPROPERTY().
UPROPERTY() [17/21]
UAbilitySystemComponent::UPROPERTY () private
List of attribute sets.
References Transient.
UPROPERTY() [18/21]
UAbilitySystemComponent::UPROPERTY () private
The actor that is the physical representation used for abilities.
Can be NULL
References UPROPERTY().
UPROPERTY() [19/21]
UAbilitySystemComponent::UPROPERTY () private
The actor that owns this component logically.
References UPROPERTY().
UPROPERTY() [20/21]
UAbilitySystemComponent::UPROPERTY () private
Internal Attribute that modifies the duration of gameplay effects applied to this component.
References UGameplayTasksComponent::meta, and UPROPERTY().
UPROPERTY() [21/21]
UAbilitySystemComponent::UPROPERTY () private
Internal Attribute that modifies the duration of gameplay effects created by this component.
References float, and UGameplayTasksComponent::meta.
Friends And Related Symbol Documentation
AAbilitySystemDebugHUD
friend class AAbilitySystemDebugHUD friend
Definition at line 1941 of file AbilitySystemComponent.h.
References AAbilitySystemDebugHUD.
Referenced by AAbilitySystemDebugHUD.
FActiveGameplayCue
friend struct FActiveGameplayCue friend
Definition at line 1934 of file AbilitySystemComponent.h.
References FActiveGameplayCue.
Referenced by FActiveGameplayCue.
FActiveGameplayCueContainer
friend struct FActiveGameplayCueContainer friend
Definition at line 1935 of file AbilitySystemComponent.h.
References FActiveGameplayCueContainer.
Referenced by AddGameplayCue_Internal(), AddGameplayCue_Internal(), FActiveGameplayCueContainer, RemoveGameplayCue_Internal(), UPROPERTY(), and UPROPERTY().
FActiveGameplayEffect
friend struct FActiveGameplayEffect friend
Definition at line 1931 of file AbilitySystemComponent.h.
References FActiveGameplayEffect.
Referenced by FActiveGameplayEffect, GetActiveGameplayEffect(), and OnGameplayEffectDurationChange().
FActiveGameplayEffectAction
friend struct FActiveGameplayEffectAction friend
Definition at line 1932 of file AbilitySystemComponent.h.
References FActiveGameplayEffectAction.
Referenced by FActiveGameplayEffectAction.
FActiveGameplayEffectAction_Add
friend struct FActiveGameplayEffectAction_Add friend
Definition at line 1939 of file AbilitySystemComponent.h.
References FActiveGameplayEffectAction_Add.
Referenced by FActiveGameplayEffectAction_Add.
FActiveGameplayEffectsContainer
friend struct FActiveGameplayEffectsContainer friend
Definition at line 1933 of file AbilitySystemComponent.h.
References FActiveGameplayEffectsContainer.
Referenced by FActiveGameplayEffectsContainer, GetActiveGameplayEffects(), HandleDeferredGameplayCues(), and UPROPERTY().
FAggregator
friend struct FAggregator friend
Definition at line 1938 of file AbilitySystemComponent.h.
References FAggregator.
Referenced by DebugCyclicAggregatorBroadcasts(), FAggregator, OnAttributeAggregatorDirty(), and OnMagnitudeDependencyChange().
FGameplayAbilitySpec
friend struct FGameplayAbilitySpec friend
Definition at line 1936 of file AbilitySystemComponent.h.
References FGameplayAbilitySpec.
Referenced by UAbilitySystemComponent::FAbilityListLockActiveChange::FAbilityListLockActiveChange(), AbilitySpecInputPressed(), AbilitySpecInputReleased(), BuildAbilitySpecFromClass(), CancelAbilitySpec(), CreateNewInstanceOfAbility(), FGameplayAbilitySpec, FindAbilitySpecFromClass(), FindAbilitySpecFromHandle(), FindAbilitySpecFromInputID(), FindAbilitySpecsFromGEHandle(), FindAllAbilitySpecsFromInputID(), GetActivatableGameplayAbilitySpecsByAllMatchingTags(), GiveAbility(), GiveAbilityAndActivateOnce(), HasNetworkAuthorityToActivateTriggeredAbility(), MarkAbilitySpecDirty(), OnGiveAbility(), OnRemoveAbility(), and UE_DEPRECATED().
FGameplayAbilitySpecContainer
friend struct FGameplayAbilitySpecContainer friend
Definition at line 1937 of file AbilitySystemComponent.h.
References FGameplayAbilitySpecContainer.
Referenced by FGameplayAbilitySpecContainer, and UPROPERTY().
FGameplayEffectSpec
friend struct FGameplayEffectSpec friend
Definition at line 1940 of file AbilitySystemComponent.h.
References FGameplayEffectSpec.
Referenced by ApplyGameplayEffectSpecToSelf(), ApplyGameplayEffectSpecToTarget(), DECLARE_MULTICAST_DELEGATE_ThreeParams(), ExecuteGameplayEffect(), FGameplayEffectSpec, OnGameplayEffectAppliedToSelf(), OnGameplayEffectAppliedToTarget(), OnPeriodicGameplayEffectExecuteOnSelf(), and OnPeriodicGameplayEffectExecuteOnTarget().
UAbilitySystemGlobals
friend class UAbilitySystemGlobals friend
Definition at line 1942 of file AbilitySystemComponent.h.
References UAbilitySystemGlobals.
Referenced by UAbilitySystemGlobals.
Field Documentation
AbilityActivatedCallbacks
FGenericAbilityDelegate UAbilitySystemComponent::AbilityActivatedCallbacks private
A generic callback anytime an ability is activated (started)
Definition at line 537 of file AbilitySystemComponent.h.
AbilityActorInfo
TSharedPtr<FGameplayAbilityActorInfo> UAbilitySystemComponent::AbilityActorInfo
Cached off data about the owning actor that abilities will need to frequently access (movement component, mesh component, anim instance, etc)
Definition at line 1544 of file AbilitySystemComponent.h.
AbilityCommittedCallbacks
FGenericAbilityDelegate UAbilitySystemComponent::AbilityCommittedCallbacks private
A generic callback anytime an ability is committed (cost/cooldown applied)
Definition at line 546 of file AbilitySystemComponent.h.
AbilityEndedCallbacks
FAbilityEnded UAbilitySystemComponent::AbilityEndedCallbacks private
Callback anytime an ability is ended.
Definition at line 540 of file AbilitySystemComponent.h.
AbilityFailedCallbacks
FAbilityFailedDelegate UAbilitySystemComponent::AbilityFailedCallbacks private
Called with a failure reason when an ability fails to activate.
Definition at line 549 of file AbilitySystemComponent.h.
AbilityLastActivatedTime
float UAbilitySystemComponent::AbilityLastActivatedTime protected
Local World time of the last ability activation.
This is used for AFK/idle detection
Definition at line 1748 of file AbilitySystemComponent.h.
Referenced by GetAbilityLastActivatedTime().
AbilityListLockActiveChanges
TArray<FAbilityListLockActiveChange*> UAbilitySystemComponent::AbilityListLockActiveChanges protected
Definition at line 2004 of file AbilitySystemComponent.h.
AbilityOriginalPredictionKey
FPredictionKey UAbilitySystemComponent::AbilityOriginalPredictionKey
Definition at line 1601 of file AbilitySystemComponent.h.
Referenced by AbilityReplicatedEventDelegate(), AbilityTargetDataCancelledDelegate(), AbilityTargetDataSetDelegate(), CallAllReplicatedDelegatesIfSet(), CallOrAddReplicatedDelegate(), CallReplicatedEventDelegateIfSet(), CallReplicatedTargetDataDelegatesIfSet(), CallServerSetReplicatedTargetData(), CancelAbilityTargetData(), ConfirmAbilityTargetData(), ConsumeAllReplicatedData(), ConsumeClientReplicatedTargetData(), ConsumeGenericReplicatedEvent(), GetReplicatedDataOfGenericReplicatedEvent(), InvokeReplicatedEvent(), InvokeReplicatedEventWithPayload(), and RefreshAbilityActorInfo().
AbilityPendingAdds
TArray<FGameplayAbilitySpec, TInlineAllocator<2> > UAbilitySystemComponent::AbilityPendingAdds protected
Abilities that will be added when exiting the current ability scope lock.
Definition at line 1743 of file AbilitySystemComponent.h.
AbilityPendingRemoves
TArray<FGameplayAbilitySpecHandle, TInlineAllocator<2> > UAbilitySystemComponent::AbilityPendingRemoves protected
Abilities that will be removed when exiting the current ability scope lock.
Definition at line 1741 of file AbilitySystemComponent.h.
AbilityScopeLockCount
int32 UAbilitySystemComponent::AbilityScopeLockCount protected
Indicates how many levels of ABILITY_SCOPE_LOCK() we are in.
The ability list may not be modified while AbilityScopeLockCount > 0.
Definition at line 1739 of file AbilitySystemComponent.h.
AbilitySpecDirtiedCallbacks
FAbilitySpecDirtied UAbilitySystemComponent::AbilitySpecDirtiedCallbacks private
Called when an ability spec's internals have changed.
Definition at line 552 of file AbilitySystemComponent.h.
AbilityTargetDataMap
FGameplayAbilityReplicatedDataContainer UAbilitySystemComponent::AbilityTargetDataMap protected
Maps from an ability spec to the target data.
Used to track replicated data and callbacks
Definition at line 1699 of file AbilitySystemComponent.h.
ActivationInfo
FGameplayAbilityActivationInfo UAbilitySystemComponent::ActivationInfo protected
Definition at line 1766 of file AbilitySystemComponent.h.
Referenced by CallServerEndAbility(), ClearAbilityReplicatedDataCache(), HasAuthorityOrPredictionKey(), PlayMontage(), PlayMontageInternal(), PlaySlotAnimationAsDynamicMontage(), PlaySlotAnimationAsDynamicMontage_WithFractionalLoops(), RemoteEndOrCancelAbility(), ReplicateEndOrCancelAbility(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
ApplicationTag
FPredictionKey const FGameplayAbilityTargetDataHandle FGameplayTag UAbilitySystemComponent::ApplicationTag
Definition at line 1601 of file AbilitySystemComponent.h.
Referenced by CallServerSetReplicatedTargetData(), and ConfirmAbilityTargetData().
bAbilityPendingClearAll
bool UAbilitySystemComponent::bAbilityPendingClearAll protected
Whether all abilities should be removed when exiting the current ability scope lock.
Will be prioritized over pending adds.
Definition at line 1745 of file AbilitySystemComponent.h.
bAllowRemoteActivation
bool UAbilitySystemComponent::bAllowRemoteActivation = true) private
Definition at line 1052 of file AbilitySystemComponent.h.
Referenced by UFUNCTION(), and UFUNCTION().
bDestroyActiveStateInitiated
uint8 UAbilitySystemComponent::bDestroyActiveStateInitiated private
Definition at line 1970 of file AbilitySystemComponent.h.
bEnforceOnGoingCheck
UAbilitySystemComponent bool UAbilitySystemComponent::bEnforceOnGoingCheck = true) const private
Definition at line 379 of file AbilitySystemComponent.h.
Referenced by UFUNCTION().
bExactMatch
FGameplayTagContainer bool UAbilitySystemComponent::bExactMatch = true) const private
Definition at line 1193 of file AbilitySystemComponent.h.
bInhibit
bool UAbilitySystemComponent::bInhibit private
Definition at line 430 of file AbilitySystemComponent.h.
Referenced by SetActiveGameplayEffectInhibit().
bInvokeGameplayCueEvents
bool bool UAbilitySystemComponent::bInvokeGameplayCueEvents private
Definition at line 430 of file AbilitySystemComponent.h.
Referenced by SetActiveGameplayEffectInhibit().
BlockedAbilityTags
FGameplayTagCountContainer UAbilitySystemComponent::BlockedAbilityTags protected
Abilities with these tags are not able to be activated.
Definition at line 1892 of file AbilitySystemComponent.h.
Referenced by GetBlockedAbilityTags().
ClientActivateAbilityFailedCountRecent
int32 UAbilitySystemComponent::ClientActivateAbilityFailedCountRecent protected
Definition at line 1779 of file AbilitySystemComponent.h.
ClientActivateAbilityFailedStartTime
float UAbilitySystemComponent::ClientActivateAbilityFailedStartTime protected
Definition at line 1780 of file AbilitySystemComponent.h.
ClientPosition
float UAbilitySystemComponent::ClientPosition protected
Definition at line 1833 of file AbilitySystemComponent.h.
const [1/4]
bool& bFound UAbilitySystemComponent::const private
Definition at line 194 of file AbilitySystemComponent.h.
Referenced by AddGameplayCue(), AddGameplayCue(), AddGameplayCue_Internal(), AddGameplayCue_Internal(), AddGameplayCue_MinimalReplication(), AddReplicatedLooseGameplayTag(), ApplyAbilityBlockAndCancelTags(), ApplyGameplayEffectSpecToSelf(), ApplyGameplayEffectSpecToTarget(), ApplyGameplayEffectToSelf(), ApplyModToAttribute(), ApplyModToAttributeUnsafe(), CallServerSetReplicatedTargetData(), CancelAbilities(), CancelAbilityHandle(), ClearAbilityReplicatedDataCache(), ConfirmAbilityTargetData(), DECLARE_MULTICAST_DELEGATE_ThreeParams(), ExecuteGameplayCue(), ExecuteGameplayCue(), FindAbilitySpecFromClass(), FindAbilitySpecFromInputID(), FindAbilitySpecsFromGEHandle(), FindActiveGameplayEffectHandle(), FindAllAbilitySpecsFromInputID(), GetActivatableGameplayAbilitySpecsByAllMatchingTags(), GetActiveEffectsEndTime(), GetActiveEffectsEndTimeAndDuration(), GetActiveEffectsEndTimeWithInstigators(), GetActiveGameplayEffect(), GetActiveGameplayEffects(), GetActiveGEDebugString(), GetAggregatedStackCount(), GetAnimatingAbility(), GetAvatarActor(), GetBlockedAbilityBindings(), GetClientDebugStrings(), GetCurrentMontage(), GetCurrentMontageSectionID(), GetCurrentMontageSectionLength(), GetCurrentMontageSectionName(), GetCurrentMontageSectionTimeLeft(), GetCurrentStackCount(), GetCurrentStackCount(), GetFilteredAttributeValue(), GetGameplayEffectCDO(), GetGameplayEffectDefForHandle(), GetGameplayEffectDuration(), GetGameplayEffectSourceTagsFromHandle(), GetGameplayEffectStartTimeAndDuration(), GetGameplayEffectTargetTagsFromHandle(), GetGameplayTaskAvatar(), GetIncomingDurationCapture(), GetLifetimeReplicatedProps(), GetMinimalReplicationTags(), GetNumericAttribute(), GetNumericAttributeBase(), GetNumericAttributeChecked(), GetOutgoingDurationCapture(), GetRepAnimMontageInfo(), GetReplicatedCustomConditionState(), GetReplicatedInstancedAbilities(), GetReplicatedLooseTags(), GetServerDebugStrings(), GetSet(), GetShouldTick(), GetSpawnedAttributes(), GiveAbility(), GiveAbilityAndActivateOnce(), HandleChangeAbilityCanBeCanceled(), HasNetworkAuthorityToActivateTriggeredAbility(), HasNetworkAuthorityToApplyGameplayEffect(), InternalServerTryActivateAbility(), InternalTryActivateAbility(), InvokeGameplayCueEvent(), InvokeGameplayCueEvent(), InvokeGameplayCueEvent(), IsAnimatingAbility(), MonitoredTagChanged(), NotifyAbilityActivated(), NotifyAbilityFailed(), NotifyTagMap_StackCountChange(), OnClientPrintDebug_Response(), OnGameplayEffectAppliedToSelf(), OnGameplayEffectAppliedToTarget(), OnMagnitudeDependencyChange(), OnPeriodicGameplayEffectExecuteOnSelf(), OnPeriodicGameplayEffectExecuteOnTarget(), OnTagUpdated(), RecomputeGameplayEffectStartTimes(), RemoveActiveEffects(), RemoveGameplayCue(), RemoveGameplayCue_Internal(), RemoveGameplayCue_MinimalReplication(), SetBlockedAbilityBindings(), SetMinimalReplicationTags(), SetNumericAttribute_Internal(), SetNumericAttributeBase(), SetRepAnimMontageInfo(), SetSpawnedAttributes(), StopMontageIfCurrent(), TriggerAbilityFromGameplayEvent(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
const [2/4]
float FGameplayEffectContextHandle Context UAbilitySystemComponent::const private
Definition at line 363 of file AbilitySystemComponent.h.
const [3/4]
FGameplayAttribute Attribute UAbilitySystemComponent::const private
Definition at line 444 of file AbilitySystemComponent.h.
const [4/4]
FGameplayTagQuery Query UAbilitySystemComponent::const private
Definition at line 1202 of file AbilitySystemComponent.h.
Context
UAbilitySystemComponent float FGameplayEffectContextHandle UAbilitySystemComponent::Context private
Definition at line 791 of file AbilitySystemComponent.h.
Referenced by ApplyGameplayEffectToTarget().
CurrentPredictionKey [1/2]
FPredictionKey const FGameplayAbilityTargetDataHandle FGameplayTag FPredictionKey UAbilitySystemComponent::CurrentPredictionKey
Definition at line 1601 of file AbilitySystemComponent.h.
Referenced by CallServerSetReplicatedTargetData(), InvokeReplicatedEvent(), InvokeReplicatedEventWithPayload(), and RefreshAbilityActorInfo().
CurrentPredictionKey [2/2]
FPredictionKey FPredictionKey UAbilitySystemComponent::CurrentPredictionKey
Definition at line 1605 of file AbilitySystemComponent.h.
DataTable
const UDataTable* UAbilitySystemComponent::DataTable private
Definition at line 171 of file AbilitySystemComponent.h.
Referenced by InitStats().
EffectContext
float FGameplayEffectContextHandle UAbilitySystemComponent::EffectContext private
Definition at line 796 of file AbilitySystemComponent.h.
Referenced by AddGameplayCue(), AddGameplayCue_Internal(), AddGameplayCue_MinimalReplication(), ApplyGameplayEffectToSelf(), CanApplyAttributeModifiers(), ExecuteGameplayCue(), InvokeGameplayCueEvent(), UFUNCTION(), and UFUNCTION().
EndPlayReason
EEndPlayReason::Type UAbilitySystemComponent::EndPlayReason
Definition at line 1541 of file AbilitySystemComponent.h.
GameFlags
int32 UAbilitySystemComponent::GameFlags private
Definition at line 1295 of file AbilitySystemComponent.h.
Referenced by OnClientPrintDebug_Response().
GameplayEffectApplicationQueries
TArray<FGameplayEffectApplicationQuery> UAbilitySystemComponent::GameplayEffectApplicationQueries private
We allow users to setup a series of functions that must be true in order to allow a GameplayEffect to be applied.
Definition at line 555 of file AbilitySystemComponent.h.
GameplayEventTagContainerDelegates
TArray<TPair<FGameplayTagContainer, FGameplayEventTagMulticastDelegate> > UAbilitySystemComponent::GameplayEventTagContainerDelegates protected
List of gameplay tag container filters, and the delegates they call.
Definition at line 1702 of file AbilitySystemComponent.h.
GameplayEventTriggeredAbilities
TMap<FGameplayTag, TArray<FGameplayAbilitySpecHandle > > UAbilitySystemComponent::GameplayEventTriggeredAbilities protected
Abilities that are triggered from a gameplay event.
Definition at line 1844 of file AbilitySystemComponent.h.
GameplayTagCountContainer
FGameplayTagCountContainer UAbilitySystemComponent::GameplayTagCountContainer protected
Acceleration map for all gameplay tags (OwnedGameplayTags from GEs and explicit GameplayCueTags)
Definition at line 1906 of file AbilitySystemComponent.h.
Referenced by GetOwnedGameplayTags(), GetTagCount(), HasAllMatchingGameplayTags(), HasAnyMatchingGameplayTags(), HasMatchingGameplayTag(), MatchesGameplayTagQuery(), SetTagMapCount(), and UpdateTagMap().
GenericCancelInputID
int32 UAbilitySystemComponent::GenericCancelInputID private
Definition at line 1430 of file AbilitySystemComponent.h.
Referenced by IsGenericCancelInputBound().
GenericConfirmInputID
int32 UAbilitySystemComponent::GenericConfirmInputID private
InputID for binding GenericConfirm/Cancel events.
Definition at line 1429 of file AbilitySystemComponent.h.
Referenced by IsGenericConfirmInputBound().
GenericGameplayEventCallbacks
TMap<FGameplayTag, FGameplayEventMulticastDelegate> UAbilitySystemComponent::GenericGameplayEventCallbacks private
Callbacks bound to Gameplay tags, these only activate if the exact tag is used.
To handle tag hierarchies use AddGameplayEventContainerDelegate
Definition at line 765 of file AbilitySystemComponent.h.
GenericLocalCancelCallbacks
FAbilityConfirmOrCancel UAbilitySystemComponent::GenericLocalCancelCallbacks private
Generic local callback for generic CancelEvent that any ability can listen to.
Definition at line 1439 of file AbilitySystemComponent.h.
Referenced by IsGenericCancelInputBound().
GenericLocalConfirmCallbacks
FAbilityConfirmOrCancel UAbilitySystemComponent::GenericLocalConfirmCallbacks private
Generic local callback for generic ConfirmEvent that any ability can listen to.
Definition at line 1436 of file AbilitySystemComponent.h.
Referenced by IsGenericConfirmInputBound().
ImmunityGE
const FActiveGameplayEffect* UAbilitySystemComponent::ImmunityGE protected
Definition at line 1856 of file AbilitySystemComponent.h.
InPlayRate
float UAbilitySystemComponent::InPlayRate protected
Definition at line 1841 of file AbilitySystemComponent.h.
Referenced by CurrentMontageSetPlayRate(), PlayMontage(), PlayMontageInternal(), PlayMontageSimulated(), PlaySlotAnimationAsDynamicMontage(), PlaySlotAnimationAsDynamicMontage_WithFractionalLoops(), PlaySlotAnimationAsDynamicMontage_WithFractionalLoopsSimulated(), and PlaySlotAnimationAsDynamicMontageSimulated().
InputID [1/3]
int32 int32 UAbilitySystemComponent::InputID = -1) private
Definition at line 114 of file AbilitySystemComponent.h.
Referenced by AbilityLocalInputPressed(), AbilityLocalInputReleased(), BlockAbilityByInputID(), BuildAbilitySpecFromClass(), FindAbilitySpecFromInputID(), FindAllAbilitySpecsFromInputID(), IsAbilityInputBlocked(), IsGenericCancelInputBound(), IsGenericConfirmInputBound(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UnBlockAbilityByInputID().
InputID [2/3]
int32 int32 UAbilitySystemComponent::InputID = -1) private
Definition at line 997 of file AbilitySystemComponent.h.
InputID [3/3]
int32 UAbilitySystemComponent::InputID = 0) const private
Definition at line 1211 of file AbilitySystemComponent.h.
InputPressed
bool UAbilitySystemComponent::InputPressed protected
Definition at line 1754 of file AbilitySystemComponent.h.
Referenced by CallServerTryActivateAbility(), and InternalServerTryActivateAbility().
InstigatorAbilitySystemComponent
UAbilitySystemComponent* UAbilitySystemComponent::InstigatorAbilitySystemComponent private
Definition at line 359 of file AbilitySystemComponent.h.
int32
UAbilitySystemComponent::int32 private
Definition at line 114 of file AbilitySystemComponent.h.
Referenced by AbilityLocalInputPressed(), AbilityLocalInputReleased(), AddLooseGameplayTag(), AddLooseGameplayTags(), BlockAbilityByInputID(), BuildAbilitySpecFromClass(), DebugLine(), FindAbilitySpecFromInputID(), FindAllAbilitySpecsFromInputID(), GetAggregatedStackCount(), GetCurrentMontageSectionID(), GetCurrentStackCount(), GetCurrentStackCount(), GetNumActiveGameplayEffects(), GetTagCount(), HandleGameplayEvent(), IsAbilityInputBlocked(), IsGenericCancelInputBound(), IsGenericConfirmInputBound(), MonitoredTagChanged(), OnClientPrintDebug_Response(), RemoveActiveEffects(), RemoveActiveGameplayEffect_AllowClientRemoval(), RemoveLooseGameplayTag(), RemoveLooseGameplayTags(), SetLooseGameplayTagCount(), SetReplicatedLooseGameplayTagCount(), SetTagMapCount(), UE_DEPRECATED_FORGAME(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UnBlockAbilityByInputID(), UpdateTagMap(), UpdateTagMap(), and UpdateTagMap_Internal().
InternalTryActivateAbilityFailureTags
FGameplayTagContainer UAbilitySystemComponent::InternalTryActivateAbilityFailureTags private
Failure tags used by InternalTryActivateAbility (E.g., this stores the FailureTags of the last call to InternalTryActivateAbility.
Definition at line 1223 of file AbilitySystemComponent.h.
Level [1/3]
int32 UAbilitySystemComponent::Level = 0 private
Definition at line 363 of file AbilitySystemComponent.h.
Referenced by ApplyGameplayEffectToSelf(), ApplyGameplayEffectToTarget(), BuildAbilitySpecFromClass(), CanApplyAttributeModifiers(), and UFUNCTION().
Level [2/3]
UAbilitySystemComponent float UAbilitySystemComponent::Level private
Definition at line 791 of file AbilitySystemComponent.h.
Level [3/3]
int32 UAbilitySystemComponent::Level = 0 private
Definition at line 997 of file AbilitySystemComponent.h.
LocalServerAbilityRPCBatchData
TArray<FServerAbilityRPCBatch, TInlineAllocator<1> > UAbilitySystemComponent::LocalServerAbilityRPCBatchData private
Accumulated client side data that is batched out to server on EndServerAbilityRPCBatch.
Definition at line 1340 of file AbilitySystemComponent.h.
MonitoredTagChangedDelegateHandle
FDelegateHandle UAbilitySystemComponent::MonitoredTagChangedDelegateHandle private
Definition at line 1963 of file AbilitySystemComponent.h.
NewLevel
int32 UAbilitySystemComponent::NewLevel private
Definition at line 422 of file AbilitySystemComponent.h.
Referenced by UFUNCTION().
NewSetByCallerValues
const TMap<FGameplayTag, float>& UAbilitySystemComponent::NewSetByCallerValues private
Definition at line 418 of file AbilitySystemComponent.h.
NewValue
float UAbilitySystemComponent::NewValue private
Definition at line 414 of file AbilitySystemComponent.h.
Referenced by SetBaseAttributeValueFromReplication(), and SetBaseAttributeValueFromReplication().
NextSectionName
float FName FName UAbilitySystemComponent::NextSectionName protected
Definition at line 1833 of file AbilitySystemComponent.h.
OnAbilityEnded
FGameplayAbilityEndedDelegate UAbilitySystemComponent::OnAbilityEnded private
Callback anytime an ability is ended, with extra information.
Definition at line 543 of file AbilitySystemComponent.h.
OnActiveGameplayEffectAddedDelegateToSelf
FOnGameplayEffectAppliedDelegate UAbilitySystemComponent::OnActiveGameplayEffectAddedDelegateToSelf private
Called on both client and server whenever a duration based GE is added (E.g., instant GEs do not trigger this).
Definition at line 519 of file AbilitySystemComponent.h.
OnGameplayEffectAppliedDelegateToSelf
FOnGameplayEffectAppliedDelegate UAbilitySystemComponent::OnGameplayEffectAppliedDelegateToSelf private
Called on server whenever a GE is applied to self.
This includes instant and duration based GEs.
Definition at line 513 of file AbilitySystemComponent.h.
OnGameplayEffectAppliedDelegateToTarget
FOnGameplayEffectAppliedDelegate UAbilitySystemComponent::OnGameplayEffectAppliedDelegateToTarget private
Called on server whenever a GE is applied to someone else.
This includes instant and duration based GEs.
Definition at line 516 of file AbilitySystemComponent.h.
OnImmunityBlockGameplayEffectDelegate
FImmunityBlockGE UAbilitySystemComponent::OnImmunityBlockGameplayEffectDelegate private
Immunity notification support.
Definition at line 528 of file AbilitySystemComponent.h.
OnPeriodicGameplayEffectExecuteDelegateOnSelf
FOnGameplayEffectAppliedDelegate UAbilitySystemComponent::OnPeriodicGameplayEffectExecuteDelegateOnSelf private
Called on server whenever a periodic GE executes on self.
Definition at line 522 of file AbilitySystemComponent.h.
OnPeriodicGameplayEffectExecuteDelegateOnTarget
FOnGameplayEffectAppliedDelegate UAbilitySystemComponent::OnPeriodicGameplayEffectExecuteDelegateOnTarget private
Called on server whenever a periodic GE executes on target.
Definition at line 525 of file AbilitySystemComponent.h.
OnRep_ActivateAbilitiesTimerHandle
FTimerHandle UAbilitySystemComponent::OnRep_ActivateAbilitiesTimerHandle private
Definition at line 1964 of file AbilitySystemComponent.h.
OptionalInstigatorFilterComponent
UAbilitySystemComponent * UAbilitySystemComponent::OptionalInstigatorFilterComponent private
Definition at line 379 of file AbilitySystemComponent.h.
Referenced by UFUNCTION().
override [1/4]
FPredictionKey FGameplayCueParameters GameplayCueParameters UAbilitySystemComponent::override private
Definition at line 881 of file AbilitySystemComponent.h.
Referenced by BeginPlay(), ForceReplication(), GetGameplayTaskAvatar(), GetLifetimeReplicatedProps(), GetReplicatedCustomConditionState(), GetShouldTick(), GetSubobjectsWithStableNamesForNetworking(), InitializeComponent(), OnComponentDestroyed(), OnRegister(), OnUnregister(), PostNetReceive(), PreNetReceive(), ReadyForReplication(), ReplicateSubobjects(), TickComponent(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UninitializeComponent().
override [2/4]
FPredictionKey FGameplayEffectContextHandle EffectContext UAbilitySystemComponent::override private
Definition at line 884 of file AbilitySystemComponent.h.
override [3/4]
FPredictionKey FGameplayCueParameters GameplayCueParameters UAbilitySystemComponent::override private
Definition at line 890 of file AbilitySystemComponent.h.
override [4/4]
FPredictionKey FGameplayCueParameters Parameters UAbilitySystemComponent::override private
Definition at line 899 of file AbilitySystemComponent.h.
OwnedTagTriggeredAbilities
TMap<FGameplayTag, TArray<FGameplayAbilitySpecHandle > > UAbilitySystemComponent::OwnedTagTriggeredAbilities protected
Abilities that are triggered from a tag being added to the owner.
Definition at line 1847 of file AbilitySystemComponent.h.
PendingServerActivatedAbilities
TArray<FPendingAbilityInfo> UAbilitySystemComponent::PendingServerActivatedAbilities private
This is a list of GameplayAbilities that were activated on the server and can't yet execute on the client.
It will try to execute these at a later point
Definition at line 320 of file AbilitySystemComponent.h.
PredictionKey [1/4]
FPredictionKey UAbilitySystemComponent::PredictionKey private
Definition at line 884 of file AbilitySystemComponent.h.
Referenced by ApplyGameplayEffectSpecToSelf(), ApplyGameplayEffectSpecToTarget(), ApplyGameplayEffectToSelf(), ApplyGameplayEffectToTarget(), CallServerEndAbility(), CallServerTryActivateAbility(), ExecuteGameplayEffect(), HasNetworkAuthorityToApplyGameplayEffect(), InternalServerTryActivateAbility(), OnClientActivateAbilityCaughtUp(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
PredictionKey [2/4]
bool FPredictionKey UAbilitySystemComponent::PredictionKey protected
Definition at line 1754 of file AbilitySystemComponent.h.
PredictionKey [3/4]
FGameplayAbilityActivationInfo FPredictionKey UAbilitySystemComponent::PredictionKey protected
Definition at line 1766 of file AbilitySystemComponent.h.
PredictionKey [4/4]
int16 UAbilitySystemComponent::PredictionKey protected
Definition at line 1778 of file AbilitySystemComponent.h.
ReplicatedTargetDataHandle
FPredictionKey const FGameplayAbilityTargetDataHandle& UAbilitySystemComponent::ReplicatedTargetDataHandle
Definition at line 1601 of file AbilitySystemComponent.h.
Referenced by CallServerSetReplicatedTargetData().
ReplicationMode
EGameplayEffectReplicationMode UAbilitySystemComponent::ReplicationMode private
How gameplay effects are replicated.
Definition at line 262 of file AbilitySystemComponent.h.
ScopedPredictionKey
FPredictionKey UAbilitySystemComponent::ScopedPredictionKey private
Current prediction key, set with FScopedPredictionWindow.
Definition at line 268 of file AbilitySystemComponent.h.
Referenced by CanPredict(), and GetPredictionKeyForNewAction().
SectionName [1/2]
float FName UAbilitySystemComponent::SectionName protected
Definition at line 1833 of file AbilitySystemComponent.h.
Referenced by CurrentMontageJumpToSection().
SectionName [2/2]
FName UAbilitySystemComponent::SectionName protected
Definition at line 1837 of file AbilitySystemComponent.h.
StacksToRemove [1/2]
int32 UAbilitySystemComponent::StacksToRemove =-1) private
Definition at line 349 of file AbilitySystemComponent.h.
Referenced by RemoveActiveEffects(), RemoveActiveGameplayEffect_AllowClientRemoval(), and UE_DEPRECATED_FORGAME().
StacksToRemove [2/2]
UAbilitySystemComponent int32 UAbilitySystemComponent::StacksToRemove = -1) private
Definition at line 359 of file AbilitySystemComponent.h.
Tags
FGameplayTagContainer UAbilitySystemComponent::Tags private
Definition at line 1193 of file AbilitySystemComponent.h.
Referenced by AreAbilityTagsBlocked(), BlockAbilitiesWithTags(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UnBlockAbilitiesWithTags().
Target
UAbilitySystemComponent * UAbilitySystemComponent::Target private
Definition at line 328 of file AbilitySystemComponent.h.
Referenced by ApplyGameplayEffectSpecToTarget(), ApplyGameplayEffectToTarget(), OnGameplayEffectAppliedToTarget(), and OnPeriodicGameplayEffectExecuteOnTarget().
TriggerEventData [1/2]
bool FPredictionKey FGameplayEventData UAbilitySystemComponent::TriggerEventData protected
Definition at line 1757 of file AbilitySystemComponent.h.
Referenced by InternalServerTryActivateAbility(), and InternalTryActivateAbility().
TriggerEventData [2/2]
FPredictionKey FGameplayEventData UAbilitySystemComponent::TriggerEventData protected
Definition at line 1789 of file AbilitySystemComponent.h.
The documentation for this class was generated from the following file:
AbilitySystemComponent.h