Unreal Engine 5.6 C++ API: FXxHash128Builder Class Reference
FXxHash128Builder Class Reference
Calculates a 128-bit hash with XXH128.
#include "xxhash.h"
Public Member Functions
FXxHash128Builder ()
FXxHash128Builder (const FXxHash128Builder &)=delete
FXxHash128 Finalize () const
FXxHash128Builder & operator= (const FXxHash128Builder &)=delete
void Reset ()
void Update (const FCompositeBuffer &Buffer)
void Update (const void *Data, uint64 Size)
void Update (FMemoryView View)
Private Attributes
char StateBytes [576]
Detailed Description
Calculates a 128-bit hash with XXH128.
Definition at line 201 of file xxhash.h.
Constructor & Destructor Documentation
FXxHash128Builder() [1/2]
FXxHash128Builder::FXxHash128Builder () inline
Definition at line 204 of file xxhash.h.
References Reset().
Referenced by FXxHash128Builder(), and operator=().
FXxHash128Builder() [2/2]
FXxHash128Builder::FXxHash128Builder (const FXxHash128Builder &) delete
References FXxHash128Builder().
Member Function Documentation
Finalize()
FXxHash128 FXxHash128Builder::Finalize () const nodiscard
operator=()
FXxHash128Builder & FXxHash128Builder::operator= (const FXxHash128Builder &) delete
References FXxHash128Builder().
Reset()
void FXxHash128Builder::Reset ()
Referenced by FXxHash128Builder().
Update() [1/3]
void FXxHash128Builder::Update (const FCompositeBuffer & Buffer)
References Buffer.
Update() [2/3]
void FXxHash128Builder::Update (const void * Data, uint64 Size)
References TSequenceHistory< HistorySize >::Size.
Update() [3/3]
void FXxHash128Builder::Update (FMemoryView View)
Field Documentation
StateBytes
char FXxHash128Builder::StateBytes[576] private
Definition at line 218 of file xxhash.h.
The documentation for this class was generated from the following file:
xxhash.h