Unreal Engine 5.6 C++ API: Chaos::TUserDataManagerPT< TUserData > Class Template Reference
Chaos::TUserDataManagerPT< TUserData > Class Template Reference
#include "ChaosUserDataPT.h"
Public Member Functions
virtual ~TUserDataManagerPT ()
bool ClearData_GT (const bool bResize=true)
template<typename TParticleHandle>
const TUserData * GetData_PT (const TParticleHandle &Handle) const
virtual FName GetFNameForStatId () const override
template<>
bool RemoveData_GT (const Chaos::FPhysicsObjectHandle &Object)
template<typename TParticleHandle>
bool RemoveData_GT (const TParticleHandle &Handle)
template<>
bool SetData_GT (const Chaos::FPhysicsObjectHandle &Object, const TUserData &UserData)
template<typename TParticleHandle>
bool SetData_GT (const TParticleHandle &Handle, const TUserData &UserData)
void VisitAllData_PT (const TFunction< void(Chaos::FUniqueIdx, const TUserData &)> &Lambda)
Protected Member Functions
virtual void OnParticleUnregistered_Internal (TArray< TTuple< FUniqueIdx, FSingleParticlePhysicsProxy * > > &UnregisteredProxies) override
virtual void OnPreSimulate_Internal () override
Protected Attributes
int32 InputIdentifier_GT = 0
int32 InputIdentifier_PT = -1
TSparseArray< TUniquePtr< TUserData > > UserDataMap_PT
Private Types
using TInput = TUserDataManagerPTInput<TUserData>
Detailed Description
template<typename TUserData>
class Chaos::TUserDataManagerPT< TUserData >
Definition at line 85 of file ChaosUserDataPT.h.
Member Typedef Documentation
TInput
template<typename TUserData> using Chaos::TUserDataManagerPT< TUserData >::TInput = TUserDataManagerPTInput<TUserData> private
Definition at line 90 of file ChaosUserDataPT.h.
Constructor & Destructor Documentation
~TUserDataManagerPT()
template<typename TUserData> virtual Chaos::TUserDataManagerPT< TUserData >::~TUserDataManagerPT () inline virtual
Definition at line 94 of file ChaosUserDataPT.h.
Member Function Documentation
ClearData_GT()
template<typename TUserData> bool Chaos::TUserDataManagerPT< TUserData >::ClearData_GT (const bool bResize = true) inline
Definition at line 210 of file ChaosUserDataPT.h.
References Input.
GetData_PT()
template<typename TUserData> template<typename TParticleHandle> const TUserData * Chaos::TUserDataManagerPT< TUserData >::GetData_PT (const TParticleHandle & Handle) const inline
Definition at line 188 of file ChaosUserDataPT.h.
References Handle, SCOPE_CYCLE_COUNTER, and UserDataMap_PT.
GetFNameForStatId()
template<typename TUserData> virtual FName Chaos::TUserDataManagerPT< TUserData >::GetFNameForStatId () const inline override virtual
Definition at line 230 of file ChaosUserDataPT.h.
OnParticleUnregistered_Internal()
template<typename TUserData> virtual void Chaos::TUserDataManagerPT< TUserData >::OnParticleUnregistered_Internal (TArray< TTuple< FUniqueIdx, FSingleParticlePhysicsProxy * > > & UnregisteredProxies) inline override protected virtual
Definition at line 301 of file ChaosUserDataPT.h.
References UserDataMap_PT.
OnPreSimulate_Internal()
template<typename TUserData> virtual void Chaos::TUserDataManagerPT< TUserData >::OnPreSimulate_Internal () inline override protected virtual
Definition at line 238 of file ChaosUserDataPT.h.
References Input, InputIdentifier_PT, MoveTemp(), SCOPE_CYCLE_COUNTER, and UserDataMap_PT.
RemoveData_GT() [1/2]
template<typename TUserData> template<> bool Chaos::TUserDataManagerPT< TUserData >::RemoveData_GT (const Chaos::FPhysicsObjectHandle & Object) inline
Definition at line 172 of file ChaosUserDataPT.h.
References Interface, FPhysicsObjectExternalInterface::LockRead(), Object, and RemoveData_GT().
RemoveData_GT() [2/2]
template<typename TUserData> template<typename TParticleHandle> bool Chaos::TUserDataManagerPT< TUserData >::RemoveData_GT (const TParticleHandle & Handle) inline
Definition at line 130 of file ChaosUserDataPT.h.
References Handle, Input, and SCOPE_CYCLE_COUNTER.
Referenced by RemoveData_GT().
SetData_GT() [1/2]
template<typename TUserData> template<> bool Chaos::TUserDataManagerPT< TUserData >::SetData_GT (const Chaos::FPhysicsObjectHandle & Object, const TUserData & UserData) inline
Definition at line 159 of file ChaosUserDataPT.h.
References Interface, FPhysicsObjectExternalInterface::LockRead(), Object, and SetData_GT().
SetData_GT() [2/2]
template<typename TUserData> template<typename TParticleHandle> bool Chaos::TUserDataManagerPT< TUserData >::SetData_GT (const TParticleHandle & Handle, const TUserData & UserData) inline
Definition at line 98 of file ChaosUserDataPT.h.
References Handle, Input, InputIdentifier_GT, MakeUnique(), and SCOPE_CYCLE_COUNTER.
Referenced by SetData_GT().
VisitAllData_PT()
template<typename TUserData> void Chaos::TUserDataManagerPT< TUserData >::VisitAllData_PT (const TFunction< void(Chaos::FUniqueIdx, const TUserData &)> & Lambda) inline
Definition at line 197 of file ChaosUserDataPT.h.
References UserDataMap_PT.
Field Documentation
InputIdentifier_GT
template<typename TUserData> int32 Chaos::TUserDataManagerPT< TUserData >::InputIdentifier_GT = 0 protected
Definition at line 322 of file ChaosUserDataPT.h.
Referenced by SetData_GT().
InputIdentifier_PT
template<typename TUserData> int32 Chaos::TUserDataManagerPT< TUserData >::InputIdentifier_PT = -1 protected
Definition at line 325 of file ChaosUserDataPT.h.
Referenced by OnPreSimulate_Internal().
UserDataMap_PT
template<typename TUserData> TSparseArray<TUniquePtr<TUserData> > Chaos::TUserDataManagerPT< TUserData >::UserDataMap_PT protected
Definition at line 328 of file ChaosUserDataPT.h.
Referenced by GetData_PT(), OnParticleUnregistered_Internal(), OnPreSimulate_Internal(), and VisitAllData_PT().
The documentation for this class was generated from the following file:
ChaosUserDataPT.h