Unreal Engine 5.6 C++ API: UE::AnimNext::TTraitBinding< IGraphFactory > Struct Reference
UE::AnimNext::TTraitBinding< IGraphFactory > Struct Reference
Specialization for trait binding.
#include "IGraphFactory.h"
Public Member Functions
void CreatePayloadForObject (FExecutionContext &Context, const UObject *InObject, FAnimNextDataInterfacePayload &InOutPayload) const
const UAnimNextAnimationGraph * GetGraphFromObject (FExecutionContext &Context, const UObject *InObject, FAnimNextDataInterfacePayload &InOutPayload) const
Public Member Functions inherited from UE::AnimNext::FTraitBinding
FTraitBinding ()=default
template<class TraitInterface>
bool AsInterface (TTraitBinding< TraitInterface > &OutBinding) const
template<class InstanceDataType>
InstanceDataType * GetInstanceData () const
ANIMNEXTANIMGRAPH_API FTraitInterfaceUID GetInterfaceUID () const
template<typename PropertyType>
const PropertyType * GetLatentProperty (FLatentPropertyHandle Handle) const
const FLatentPropertyHandle * GetLatentPropertyHandles () const
template<class SharedDataType>
const SharedDataType * GetSharedData () const
const FTraitStackBinding * GetStack () const
bool GetStackBaseTrait (FTraitBinding &OutBinding) const
template<class TraitInterface>
bool GetStackInterface (TTraitBinding< TraitInterface > &OutBinding) const
template<class TraitInterface>
bool GetStackInterfaceSuper (TTraitBinding< TraitInterface > &OutSuperBinding) const
const FTrait * GetTrait () const
uint32 GetTraitIndex () const
FWeakTraitPtr GetTraitPtr () const
template<class TraitInterface>
bool HasInterface () const
template<class TraitInterface>
bool HasStackInterface () const
template<class TraitInterface>
bool HasStackInterfaceSuper () const
bool IsValid () const
bool operator!= (const FTraitBinding &RHS) const
bool operator== (const FTraitBinding &RHS) const
void Reset ()
Protected Member Functions
const IGraphFactory * GetInterface () const
Protected Member Functions inherited from UE::AnimNext::FTraitBinding
FTraitBinding (const FTraitStackBinding *InStack, const FTrait *InTraitImpl, uint32 InTraitIndex, int32 InInterfaceThisOffset=-1)
bool AsInterfaceImpl (FTraitInterfaceUID InterfaceUID, FTraitBinding &OutBinding) const
template<class TraitInterfaceType>
const TraitInterfaceType * GetInterfaceTyped () const
bool HasInterfaceImpl (FTraitInterfaceUID InterfaceUID) const
Additional Inherited Members
Protected Attributes inherited from UE::AnimNext::FTraitBinding
friend FExecutionContext
friend FTraitStackBinding
int32 InterfaceThisOffset = -1
const FTraitStackBinding * Stack = nullptr
const FTrait * TraitImpl = nullptr
uint32 TraitIndex = 0
Detailed Description
Specialization for trait binding.
Definition at line 54 of file IGraphFactory.h.
Member Function Documentation
CreatePayloadForObject()
void UE::AnimNext::TTraitBinding< IGraphFactory >::CreatePayloadForObject (FExecutionContext & Context, const UObject * InObject, FAnimNextDataInterfacePayload & InOutPayload) const inline
Definition at line 63 of file IGraphFactory.h.
References UE::AnimNext::FTraitBinding::FExecutionContext, and GetInterface().
GetGraphFromObject()
const UAnimNextAnimationGraph * UE::AnimNext::TTraitBinding< IGraphFactory >::GetGraphFromObject (FExecutionContext & Context, const UObject * InObject, FAnimNextDataInterfacePayload & InOutPayload) const inline
Definition at line 57 of file IGraphFactory.h.
References UE::AnimNext::FTraitBinding::FExecutionContext, and GetInterface().
GetInterface()
const IGraphFactory * UE::AnimNext::TTraitBinding< IGraphFactory >::GetInterface () const inline protected
Definition at line 69 of file IGraphFactory.h.
References UE::AnimNext::FTraitBinding::GetInterfaceTyped().
Referenced by CreatePayloadForObject(), and GetGraphFromObject().
The documentation for this struct was generated from the following file:
IGraphFactory.h