Unreal Engine 5.6 C++ API: UE::MovieScene::Private Namespace Reference
UE::MovieScene::Private Namespace Reference
Namespaces
namespace Tests
Data Structures
struct TCustomPropertyAccessorStorageType
struct TCustomPropertyAccessorStorageTypeImpl
Utility class for selecting a property traits' CustomAccessorStorageType, or StorageType if not defined.
struct TCustomPropertyAccessorStorageTypeImpl< PropertyTraits, false >
struct TCustomPropertyAccessorStorageTypeImpl< PropertyTraits, true >
Functions
template<typename T, typename U>
static T BitOffsetToHighBitMask (U BitOffset)
Return a bitmask of all the bits greater-than-or-equal to BitOffset.
template<typename T, typename U>
static T BitOffsetToLowBitMask (U BitOffset)
Return a bitmask of all the bits less-than BitOffset.
static uint32 CountTrailingZeros (uint16 In)
static uint32 CountTrailingZeros (uint32 In)
static uint32 CountTrailingZeros (uint64 In)
static uint32 CountTrailingZeros (uint8 In)
template<typename T>
bool ReplaceGroupKeyObjectElement (T &&InElem, const TMap< UObject *, UObject * > &ReplacementMap)
template<typename T>
TEnableIf< TPointerIsConvertibleFromTo< T, UObject >::Value, bool >::Type ReplaceGroupKeyObjectElement (T &InOutElem, const TMap< UObject *, UObject * > &ReplacementMap)
Variables
template<typename, typename = void>
constexpr bool PropertyTraitsHaveCustomAccessorStorageType = false
Utility global flag to determine whether a given type has a nested type called CustomAccessorStorageType.
template<typename T>
constexpr bool PropertyTraitsHaveCustomAccessorStorageType< T, std::void_t< decltype(sizeof(typename T::CustomAccessorStorageType))> > = true
Function Documentation
BitOffsetToHighBitMask()
template<typename T, typename U> T UE::MovieScene::Private::BitOffsetToHighBitMask (U BitOffset) static
Return a bitmask of all the bits greater-than-or-equal to BitOffset.
Definition at line 62 of file SparseBitSet.h.
References BitOffsetToLowBitMask().
BitOffsetToLowBitMask()
template<typename T, typename U> T UE::MovieScene::Private::BitOffsetToLowBitMask (U BitOffset) static
Return a bitmask of all the bits less-than BitOffset.
Definition at line 53 of file SparseBitSet.h.
References One.
Referenced by BitOffsetToHighBitMask().
CountTrailingZeros() [1/4]
uint32 UE::MovieScene::Private::CountTrailingZeros (uint16 In) static
Definition at line 37 of file SparseBitSet.h.
References X.
CountTrailingZeros() [2/4]
uint32 UE::MovieScene::Private::CountTrailingZeros (uint32 In) static
Definition at line 42 of file SparseBitSet.h.
CountTrailingZeros() [3/4]
uint32 UE::MovieScene::Private::CountTrailingZeros (uint64 In) static
Definition at line 46 of file SparseBitSet.h.
CountTrailingZeros() [4/4]
uint32 UE::MovieScene::Private::CountTrailingZeros (uint8 In) static
Definition at line 32 of file SparseBitSet.h.
References X.
Referenced by UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::Begin(), and UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::operator|=().
ReplaceGroupKeyObjectElement() [1/2]
template<typename T> bool UE::MovieScene::Private::ReplaceGroupKeyObjectElement (T && InElem, const TMap< UObject *, UObject * > & ReplacementMap)
Definition at line 270 of file MovieSceneEntityGroupingSystem.h.
Referenced by UE::MovieScene::TTupleGroupingPolicy< ComponentTypes >::OnObjectsReplaced().
ReplaceGroupKeyObjectElement() [2/2]
template<typename T> TEnableIf< TPointerIsConvertibleFromTo< T, UObject >::Value, bool >::Type UE::MovieScene::Private::ReplaceGroupKeyObjectElement (T & InOutElem, const TMap< UObject *, UObject * > & ReplacementMap)
Definition at line 276 of file MovieSceneEntityGroupingSystem.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), and NewObject().
Variable Documentation
PropertyTraitsHaveCustomAccessorStorageType
template<typename, typename = void> bool UE::MovieScene::Private::PropertyTraitsHaveCustomAccessorStorageType = false constexpr
Utility global flag to determine whether a given type has a nested type called CustomAccessorStorageType.
Definition at line 65 of file MovieScenePropertySystemTypes.h.
PropertyTraitsHaveCustomAccessorStorageType< T, std::void_t< decltype(sizeof(typename T::CustomAccessorStorageType))> >
template<typename T> bool UE::MovieScene::Private::PropertyTraitsHaveCustomAccessorStorageType< T, std::void_t< decltype(sizeof(typename T::CustomAccessorStorageType))> > = true constexpr
Definition at line 68 of file MovieScenePropertySystemTypes.h.