Unreal Engine 5.6 C++ API: TransformCalculus3D.h File Reference
TransformCalculus3D.h File Reference
#include "CoreTypes.h"
#include "Math/Vector.h"
#include "Math/Rotator.h"
#include "Math/Matrix.h"
#include "Math/RotationMatrix.h"
#include "Math/TranslationMatrix.h"
#include "Math/Quat.h"
#include "Math/ScaleMatrix.h"
#include "Math/TransformCalculus.h"
Data Structures
struct ConcatenateRules< double, TScale< T > >
struct ConcatenateRules< double, UE::Math::TMatrix< T > >
struct ConcatenateRules< double, UE::Math::TQuat< T > >
struct ConcatenateRules< double, UE::Math::TRotator< T > >
struct ConcatenateRules< double, UE::Math::TVector< T > >
struct ConcatenateRules< float, TScale< T > >
concatenation rules for basic UE4 types.
struct ConcatenateRules< float, UE::Math::TMatrix< T > >
struct ConcatenateRules< float, UE::Math::TQuat< T > >
struct ConcatenateRules< float, UE::Math::TRotator< T > >
struct ConcatenateRules< float, UE::Math::TVector< T > >
struct ConcatenateRules< TScale< T >, double >
struct ConcatenateRules< TScale< T >, float >
struct ConcatenateRules< TScale< T >, UE::Math::TMatrix< T > >
struct ConcatenateRules< TScale< T >, UE::Math::TQuat< T > >
struct ConcatenateRules< TScale< T >, UE::Math::TRotator< T > >
struct ConcatenateRules< TScale< T >, UE::Math::TVector< T > >
struct ConcatenateRules< UE::Math::TMatrix< T >, double >
struct ConcatenateRules< UE::Math::TMatrix< T >, float >
struct ConcatenateRules< UE::Math::TMatrix< T >, TScale< T > >
struct ConcatenateRules< UE::Math::TMatrix< T >, UE::Math::TQuat< T > >
struct ConcatenateRules< UE::Math::TMatrix< T >, UE::Math::TRotator< T > >
struct ConcatenateRules< UE::Math::TMatrix< T >, UE::Math::TVector< T > >
struct ConcatenateRules< UE::Math::TQuat< T >, double >
struct ConcatenateRules< UE::Math::TQuat< T >, float >
struct ConcatenateRules< UE::Math::TQuat< T >, TScale< T > >
struct ConcatenateRules< UE::Math::TQuat< T >, UE::Math::TMatrix< T > >
struct ConcatenateRules< UE::Math::TQuat< T >, UE::Math::TRotator< T > >
struct ConcatenateRules< UE::Math::TQuat< T >, UE::Math::TVector< T > >
struct ConcatenateRules< UE::Math::TRotator< T >, double >
struct ConcatenateRules< UE::Math::TRotator< T >, float >
struct ConcatenateRules< UE::Math::TRotator< T >, TScale< T > >
struct ConcatenateRules< UE::Math::TRotator< T >, UE::Math::TMatrix< T > >
struct ConcatenateRules< UE::Math::TRotator< T >, UE::Math::TQuat< T > >
struct ConcatenateRules< UE::Math::TRotator< T >, UE::Math::TVector< T > >
struct ConcatenateRules< UE::Math::TVector< T >, double >
struct ConcatenateRules< UE::Math::TVector< T >, float >
struct ConcatenateRules< UE::Math::TVector< T >, TScale< T > >
struct ConcatenateRules< UE::Math::TVector< T >, UE::Math::TMatrix< T > >
struct ConcatenateRules< UE::Math::TVector< T >, UE::Math::TQuat< T > >
struct ConcatenateRules< UE::Math::TVector< T >, UE::Math::TRotator< T > >
struct TransformConverter< FMatrix44d >
struct TransformConverter< FMatrix44f >
Specialization of TransformConverter for UE::Math::TMatrix<T>.
class TScale< T >
Represents a 3D non-uniform scale (to disambiguate from an UE::Math::TVector<T>, which is used for translation).
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Math
Implements an axis-aligned box.
Typedefs
typedef FScale3f FScale3D
typedef TScale< double > FScale3d
typedef TScale< float > FScale3f
Core typedefs.
Functions
template<typename T>
UE::Math::TRotator< T > Concatenate (const UE::Math::TRotator< T > &LHS, const UE::Math::TRotator< T > &RHS)
Specialization for concatenating two rotations.
template<typename T>
UE::Math::TMatrix< T > UE::Math::Concatenate (const UE::Math::TMatrix< T > &LHS, const UE::Math::TMatrix< T > &RHS)
Specialization for concatenating two Matrices.
template<typename T>
UE::Math::TQuat< T > UE::Math::Concatenate (const UE::Math::TQuat< T > &LHS, const UE::Math::TQuat< T > &RHS)
Specialization for concatenating two rotations.
template<typename T>
UE::Math::TVector< T > UE::Math::Concatenate (const UE::Math::TVector< T > &LHS, const UE::Math::TVector< T > &RHS)
Specialization for concatenating two translations.
template<typename T>
UE::Math::TMatrix< T > Inverse (const UE::Math::TMatrix< T > &Transform)
Inverts a transform from space A to space B so it transforms from space B to space A.
template<typename T>
UE::Math::TQuat< T > Inverse (const UE::Math::TQuat< T > &Transform)
Inverts a transform from space A to space B so it transforms from space B to space A.
template<typename T>
UE::Math::TRotator< T > Inverse (const UE::Math::TRotator< T > &Transform)
Inverts a transform from space A to space B so it transforms from space B to space A.
template<typename T>
UE::Math::TVector< T > Inverse (const UE::Math::TVector< T > &Transform)
Inverts a transform from space A to space B so it transforms from space B to space A.
template<typename TransformType>
auto ToMatrix (const TransformType &Transform) -> decltype(Transform.ToMatrix())
Converts a generic transform to a matrix using a ToMatrix() member function.
UE::Math::TMatrix< double > ToMatrix (const TScale< double > &Scale)
UE::Math::TMatrix< float > ToMatrix (const TScale< float > &Scale)
Specialization for non-uniform Scale.
const UE::Math::TMatrix< double > & ToMatrix (const UE::Math::TMatrix< double > &Transform)
const UE::Math::TMatrix< float > & ToMatrix (const UE::Math::TMatrix< float > &Transform)
Specialization for the NULL Matrix conversion.
UE::Math::TMatrix< double > ToMatrix (const UE::Math::TQuat< double > &Rotation)
UE::Math::TMatrix< float > ToMatrix (const UE::Math::TQuat< float > &Rotation)
Specialization for rotation.
UE::Math::TMatrix< double > ToMatrix (const UE::Math::TRotator< double > &Rotation)
UE::Math::TMatrix< float > ToMatrix (const UE::Math::TRotator< float > &Rotation)
Specialization for rotation.
UE::Math::TMatrix< double > ToMatrix (const UE::Math::TVector< double > &Translation)
UE::Math::TMatrix< float > ToMatrix (const UE::Math::TVector< float > &Translation)
Specialization for translation.
UE::Math::TMatrix< double > ToMatrix (double Scale)
UE::Math::TMatrix< float > ToMatrix (float Scale)
Specialization for floats as a uniform scale.
template<typename T>
UE::Math::TVector< T > TransformPoint (const TScale< T > &Transform, const UE::Math::TVector< T > &Point)
Specialization for Scale.
template<typename T>
UE::Math::TVector< T > TransformPoint (const UE::Math::TMatrix< T > &Transform, const UE::Math::TVector< T > &Point)
Specialization for UE::Math::TMatrix<T> as it's member function is called something slightly different.
template<typename T>
UE::Math::TVector< T > TransformPoint (const UE::Math::TQuat< T > &Transform, const UE::Math::TVector< T > &Point)
Specialization for UE::Math::TQuat<T> as it's member function is called something slightly different.
template<typename T>
UE::Math::TVector< T > TransformPoint (const UE::Math::TRotator< T > &Transform, const UE::Math::TVector< T > &Point)
Specialization for UE::Math::TRotator<T> as it's member function is called something slightly different.
template<typename T>
UE::Math::TVector< T > TransformPoint (const UE::Math::TVector< T > &Transform, const UE::Math::TVector< T > &Point)
Specialization for UE::Math::TVector<T> Translation.
template<typename T>
UE::Math::TVector< T > TransformVector (const TScale< T > &Transform, const UE::Math::TVector< T > &Vector)
Specialization for Scale.
template<typename T>
UE::Math::TVector< T > TransformVector (const UE::Math::TQuat< T > &Transform, const UE::Math::TVector< T > &Vector)
Specialization for UE::Math::TQuat<T> as it's member function is called something slightly different.
template<typename T>
UE::Math::TVector< T > TransformVector (const UE::Math::TRotator< T > &Transform, const UE::Math::TVector< T > &Vector)
Specialization for UE::Math::TRotator<T> as it's member function is called something slightly different.
template<typename T>
const UE::Math::TVector< T > & TransformVector (const UE::Math::TVector< T > &Transform, const UE::Math::TVector< T > &Vector)
Specialization for UE::Math::TVector<T> Translation (does nothing).
Typedef Documentation
FScale3D
typedef FScale3f FScale3D
Definition at line 75 of file TransformCalculus3D.h.
FScale3d
typedef TScale<double> FScale3d
Definition at line 74 of file TransformCalculus3D.h.
FScale3f
typedef TScale<float> FScale3f
Core typedefs.
Definition at line 73 of file TransformCalculus3D.h.
Function Documentation
Concatenate()
template<typename T> UE::Math::TRotator< T > Concatenate (const UE::Math::TRotator< T > & LHS, const UE::Math::TRotator< T > & RHS) inline
Specialization for concatenating two rotations.
Parameters
LHS rotation that goes from space A to space B
RHS rotation that goes from space B to space C.
Returns
a new rotation representing the transformation from the input space of LHS to the output space of RHS.
Definition at line 332 of file TransformCalculus3D.h.
References Concatenate(), and TransformCast().
Referenced by Concatenate().
Inverse() [1/4]
template<typename T> UE::Math::TMatrix< T > Inverse (const UE::Math::TMatrix< T > & Transform) inline
Inverts a transform from space A to space B so it transforms from space B to space A.
Specialization for UE::Math::TMatrix<T>.
Parameters
Transform Input transform from space A to space B.
Returns
Inverted transform from space B to space A.
Definition at line 354 of file TransformCalculus3D.h.
References Transform.
Inverse() [2/4]
template<typename T> UE::Math::TQuat< T > Inverse (const UE::Math::TQuat< T > & Transform) inline
Inverts a transform from space A to space B so it transforms from space B to space A.
Specialization for UE::Math::TQuat<T>.
Parameters
Transform Input transform from space A to space B.
Returns
Inverted transform from space B to space A.
Definition at line 381 of file TransformCalculus3D.h.
References Transform.
Inverse() [3/4]
template<typename T> UE::Math::TRotator< T > Inverse (const UE::Math::TRotator< T > & Transform) inline
Inverts a transform from space A to space B so it transforms from space B to space A.
Specialization for UE::Math::TRotator<T>.
Parameters
Transform Input transform from space A to space B.
Returns
Inverted transform from space B to space A.
Definition at line 367 of file TransformCalculus3D.h.
References UE::Math::TRotator< T >::MakeFromEuler(), Transform, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Inverse() [4/4]
template<typename T> UE::Math::TVector< T > Inverse (const UE::Math::TVector< T > & Transform) inline
Inverts a transform from space A to space B so it transforms from space B to space A.
Specialization for translation.
Parameters
Transform Input transform from space A to space B.
Returns
Inverted transform from space B to space A.
Definition at line 394 of file TransformCalculus3D.h.
References Transform.
ToMatrix() [1/13]
template<typename TransformType> auto ToMatrix (const TransformType & Transform) -> decltype(Transform.ToMatrix()) inline
Converts a generic transform to a matrix using a ToMatrix() member function.
Uses decltype to allow some classes to return const-ref types for efficiency.
Parameters
Transform
Returns
the UE::Math::TMatrix<T> stored by the Transform.
Definition at line 99 of file TransformCalculus3D.h.
References Transform.
Referenced by TransformConverter< FMatrix44d >::Convert(), TransformConverter< FMatrix44f >::Convert(), and UE::Math::TQuat< T >::ToMatrix().
ToMatrix() [2/13]
UE::Math::TMatrix< double > ToMatrix (const TScale< double > & Scale) inline
Definition at line 146 of file TransformCalculus3D.h.
References Scale.
ToMatrix() [3/13]
UE::Math::TMatrix< float > ToMatrix (const TScale< float > & Scale) inline
Specialization for non-uniform Scale.
Parameters
Scale Non-uniform Scale
Returns
Matrix that represents the non-uniform Scale space.
Definition at line 142 of file TransformCalculus3D.h.
References Scale.
ToMatrix() [4/13]
const UE::Math::TMatrix< double > & ToMatrix (const UE::Math::TMatrix< double > & Transform) inline
Definition at line 115 of file TransformCalculus3D.h.
References Transform.
ToMatrix() [5/13]
const UE::Math::TMatrix< float > & ToMatrix (const UE::Math::TMatrix< float > & Transform) inline
Specialization for the NULL Matrix conversion.
Parameters
Scale Uniform Scale
Returns
Matrix that represents the uniform Scale space.
Definition at line 110 of file TransformCalculus3D.h.
References Transform.
ToMatrix() [6/13]
UE::Math::TMatrix< double > ToMatrix (const UE::Math::TQuat< double > & Rotation) inline
Definition at line 191 of file TransformCalculus3D.h.
References UE::Math::TRotationMatrix< T >::Make(), and Rotation.
ToMatrix() [7/13]
UE::Math::TMatrix< float > ToMatrix (const UE::Math::TQuat< float > & Rotation) inline
Specialization for rotation.
Parameters
Rotation Rotation
Returns
Matrix that represents the rotated space.
Definition at line 187 of file TransformCalculus3D.h.
References UE::Math::TRotationMatrix< T >::Make(), and Rotation.
ToMatrix() [8/13]
UE::Math::TMatrix< double > ToMatrix (const UE::Math::TRotator< double > & Rotation) inline
Definition at line 176 of file TransformCalculus3D.h.
References Rotation.
ToMatrix() [9/13]
UE::Math::TMatrix< float > ToMatrix (const UE::Math::TRotator< float > & Rotation) inline
Specialization for rotation.
Parameters
Rotation Rotation
Returns
Matrix that represents the rotated space.
Definition at line 172 of file TransformCalculus3D.h.
References Rotation.
ToMatrix() [10/13]
UE::Math::TMatrix< double > ToMatrix (const UE::Math::TVector< double > & Translation) inline
Definition at line 161 of file TransformCalculus3D.h.
References Translation.
ToMatrix() [11/13]
UE::Math::TMatrix< float > ToMatrix (const UE::Math::TVector< float > & Translation) inline
Specialization for translation.
Parameters
Translation Translation
Returns
Matrix that represents the translated space.
Definition at line 157 of file TransformCalculus3D.h.
References Translation.
ToMatrix() [12/13]
UE::Math::TMatrix< double > ToMatrix (double Scale) inline
Definition at line 131 of file TransformCalculus3D.h.
References Scale.
ToMatrix() [13/13]
UE::Math::TMatrix< float > ToMatrix (float Scale) inline
Specialization for floats as a uniform scale.
Parameters
Scale Uniform Scale
Returns
Matrix that represents the uniform Scale space.
Definition at line 126 of file TransformCalculus3D.h.
References Scale.
TransformPoint() [1/5]
template<typename T> UE::Math::TVector< T > TransformPoint (const TScale< T > & Transform, const UE::Math::TVector< T > & Point) inline
Specialization for Scale.
Definition at line 473 of file TransformCalculus3D.h.
References Point, and Transform.
TransformPoint() [2/5]
template<typename T> UE::Math::TVector< T > TransformPoint (const UE::Math::TMatrix< T > & Transform, const UE::Math::TVector< T > & Point) inline
Specialization for UE::Math::TMatrix<T> as it's member function is called something slightly different.
Definition at line 410 of file TransformCalculus3D.h.
References Point, and Transform.
TransformPoint() [3/5]
template<typename T> UE::Math::TVector< T > TransformPoint (const UE::Math::TQuat< T > & Transform, const UE::Math::TVector< T > & Point) inline
Specialization for UE::Math::TQuat<T> as it's member function is called something slightly different.
Definition at line 419 of file TransformCalculus3D.h.
References Point, and Transform.
TransformPoint() [4/5]
template<typename T> UE::Math::TVector< T > TransformPoint (const UE::Math::TRotator< T > & Transform, const UE::Math::TVector< T > & Point) inline
Specialization for UE::Math::TRotator<T> as it's member function is called something slightly different.
Definition at line 437 of file TransformCalculus3D.h.
References Point, and Transform.
TransformPoint() [5/5]
template<typename T> UE::Math::TVector< T > TransformPoint (const UE::Math::TVector< T > & Transform, const UE::Math::TVector< T > & Point) inline
Specialization for UE::Math::TVector<T> Translation.
Definition at line 455 of file TransformCalculus3D.h.
References Point, and Transform.
TransformVector() [1/4]
template<typename T> UE::Math::TVector< T > TransformVector (const TScale< T > & Transform, const UE::Math::TVector< T > & Vector) inline
Specialization for Scale.
Definition at line 482 of file TransformCalculus3D.h.
References Transform, and Vector.
TransformVector() [2/4]
template<typename T> UE::Math::TVector< T > TransformVector (const UE::Math::TQuat< T > & Transform, const UE::Math::TVector< T > & Vector) inline
Specialization for UE::Math::TQuat<T> as it's member function is called something slightly different.
Definition at line 428 of file TransformCalculus3D.h.
References Transform, and Vector.
TransformVector() [3/4]
template<typename T> UE::Math::TVector< T > TransformVector (const UE::Math::TRotator< T > & Transform, const UE::Math::TVector< T > & Vector) inline
Specialization for UE::Math::TRotator<T> as it's member function is called something slightly different.
Definition at line 446 of file TransformCalculus3D.h.
References Transform, and Vector.
TransformVector() [4/4]
template<typename T> const UE::Math::TVector< T > & TransformVector (const UE::Math::TVector< T > & Transform, const UE::Math::TVector< T > & Vector) inline
Specialization for UE::Math::TVector<T> Translation (does nothing).
Definition at line 464 of file TransformCalculus3D.h.
References Transform, and Vector.