Unreal Engine 5.6 C++ API: MaterialInterface.h File Reference
MaterialInterface.h File Reference
#include "Async/TaskGraphInterfaces.h"
#include "CoreMinimal.h"
#include "Delegates/Delegate.h"
#include "MaterialTypes.h"
#include "Containers/ArrayView.h"
#include "Containers/StaticArray.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Misc/Guid.h"
#include "Misc/Optional.h"
#include "Templates/UniquePtr.h"
#include "Templates/SharedPointer.h"
#include "Engine/EngineTypes.h"
#include "UObject/SoftObjectPath.h"
#include "UObject/ScriptMacros.h"
#include "RenderCommandFence.h"
#include "SceneTypes.h"
#include "Engine/BlendableInterface.h"
#include "Materials/MaterialLayersFunctions.h"
#include "Interfaces/Interface_AssetUserData.h"
#include "MaterialSceneTextureId.h"
#include "Materials/MaterialRelevance.h"
#include "MaterialRecursionGuard.h"
#include "MaterialShaderPrecompileMode.h"
#include "MeshUVChannelInfo.h"
#include "RHIFeatureLevel.h"
#include "PSOPrecache.h"
#include "StaticParameterSet.h"
#include "Interfaces/Interface_AsyncCompilation.h"
#include "MaterialInterface.generated.h"
Data Structures
struct FMaterialAnalysisResult
Holds data about what is used in the shader graph of a specific material property or custom output.
struct FMaterialInheritanceChain
Holds information about a hierarchy of materials.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MaterialInterface
namespace UE::MaterialInterface::Private
Typedefs
typedef TArray< FMaterialResource * > FMaterialResourceDeferredDeletionArray
using TMicRecursionGuard = TMaterialRecursionGuard<class UMaterialInterface>
Functions
UCLASS() class UMaterialInterfaceEditorOnlyData DECLARE_MULTICAST_DELEGATE_OneParam (FOnBaseMaterialIsSet, UMaterialInterface *)
FMaterialResource * FindMaterialResource (const TArray< FMaterialResource * > &MaterialResources, ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type QualityLevel, bool bAllowDefaultQuality)
FMaterialResource * FindMaterialResource (TArray< FMaterialResource * > &MaterialResources, ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type QualityLevel, bool bAllowDefaultQuality)
FMaterialResource * FindOrCreateMaterialResource (TArray< FMaterialResource * > &MaterialResources, UMaterial *OwnerMaterial, UMaterialInstance *OwnerMaterialInstance, ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type QualityLevel)
void ProcessSerializedInlineShaderMaps (UMaterialInterface *Owner, TArray< FMaterialResource > &LoadedResources, TArray< FMaterialResource * > &OutMaterialResourcesLoaded)
Helper function to process (register) serialized inline shader maps for the given material resources.
void UE::MaterialInterface::Private::SerializeInlineShaderMaps (FArchive &Ar, TArray< FMaterialResource > &OutLoadedResources, const FName &SerializingAsset=NAME_None, const TMap< const ITargetPlatform *, TArray< FMaterialResourceForCooking > > *PlatformMaterialResourcesToSave=nullptr)
Helper function to serialize inline shader maps for the given material resources.
UENUM() enum EMaterialUsage USTRUCT () struct FLightmassMaterialInterfaceSettings
UMaterial interface settings for Lightmass.
Typedef Documentation
FMaterialResourceDeferredDeletionArray
typedef TArray<FMaterialResource*> FMaterialResourceDeferredDeletionArray
Definition at line 69 of file MaterialInterface.h.
TMicRecursionGuard
using TMicRecursionGuard = TMaterialRecursionGuard<class UMaterialInterface>
Definition at line 203 of file MaterialInterface.h.
Function Documentation
DECLARE_MULTICAST_DELEGATE_OneParam()
UCLASS() class UMaterialInterfaceEditorOnlyData DECLARE_MULTICAST_DELEGATE_OneParam (FOnBaseMaterialIsSet , UMaterialInterface *)
References A, abstract, Ar, B, BlueprintType, Category, check, FMath::Clamp(), DECLARE_MULTICAST_DELEGATE_OneParam, Default, ExactClass, FRenderResource::FeatureLevel, Flags, FORCEINLINE, G, GENERATED_UCLASS_BODY, FBitSet::GetAndClearNextBit(), FMaterialRenderProxy::GetBlendableLocation(), FMaterialRenderProxy::GetBlendablePriority(), FMaterialRenderProxy::GetParameterValue(), FMaterialRenderProxy::GetUserSceneTextureOutput(), FMaterialRenderProxy::GetUserSceneTextureOverride(), HideCategories, LightingGuid, Lightmass, MakeArrayView(), Material, meta, MinimalAPI, FGuid::NewGuid(), EMaterialQualityLevel::Num, TArray< InElementType, InAllocatorType >::Num(), Owner, Platform, PostLoad, Predicate, PreSave, PreviewMesh, Property, PURE_VIRTUAL, R, REN_None, Rename, TArray< InElementType, InAllocatorType >::SetNum(), ShaderPlatform, Texture, Transient, transient, UCLASS, UFUNCTION, UPROPERTY, Value, and Weight.
FindMaterialResource() [1/2]
FMaterialResource * FindMaterialResource (const TArray< FMaterialResource * > & MaterialResources, ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type QualityLevel, bool bAllowDefaultQuality) extern
FindMaterialResource() [2/2]
FMaterialResource * FindMaterialResource (TArray< FMaterialResource * > & MaterialResources, ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type QualityLevel, bool bAllowDefaultQuality) extern
FindOrCreateMaterialResource()
FMaterialResource * FindOrCreateMaterialResource (TArray< FMaterialResource * > & MaterialResources, UMaterial * OwnerMaterial, UMaterialInstance * OwnerMaterialInstance, ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type QualityLevel)
ProcessSerializedInlineShaderMaps()
void ProcessSerializedInlineShaderMaps (UMaterialInterface * Owner, TArray< FMaterialResource > & LoadedResources, TArray< FMaterialResource * > & OutMaterialResourcesLoaded) extern
Helper function to process (register) serialized inline shader maps for the given material resources.
References Owner.
USTRUCT()
UENUM() enum EMaterialUsage USTRUCT ()
UMaterial interface settings for Lightmass.
This struct holds data about how a texture is sampled within a material.
Scales the emissive contribution of this material to static lighting.
Scales the diffuse contribution of this material to static lighting.
Scales the resolution that this material's attributes were exported at. This is useful for increasing material resolution when details are needed.
If true, forces translucency to cast static shadows as if the material were masked.
Boolean override flags - only used in MaterialInstance* cases.
If true, override the bCastShadowAsMasked setting of the parent material.
If true, override the emissive boost setting of the parent material.
If true, override the diffuse boost setting of the parent material.
If true, override the export resolution scale setting of the parent material.
The scale used when sampling the texture
The coordinate index used when sampling the texture
The texture name. Used for debugging and also to for quick matching of the entries.
Return whether the data is valid to be used
Definition at line 104 of file MaterialInterface.h.
References Category, GENERATED_USTRUCT_BODY, Material, and UPROPERTY.