Unreal Engine 5.6 C++ API: Metasound::FFrontendQuery Class Reference
Metasound::FFrontendQuery Class Reference
FFrontendQuery contains a set of query steps which produce a FFrontendQuerySelectionView.
#include "MetasoundFrontendQuery.h"
Data Structures
struct FStepInfo
Public Types
using FFilterFunction = FFrontendQueryStep::FFilterFunction
using FLimitFunction = FFrontendQueryStep::FLimitFunction
using FMapFunction = FFrontendQueryStep::FMapFunction
using FReduceFunction = FFrontendQueryStep::FReduceFunction
using FScoreFunction = FFrontendQueryStep::FScoreFunction
using FSortFunction = FFrontendQueryStep::FSortFunction
using FStreamFunction = FFrontendQueryStep::FStreamFunction
using FTransformFunction = FFrontendQueryStep::FTransformFunction
Public Member Functions
METASOUNDFRONTEND_API FFrontendQuery ()
FFrontendQuery (const FFrontendQuery &)=delete
FFrontendQuery (FFrontendQuery &&)=default
METASOUNDFRONTEND_API FFrontendQuery & AddFilterLambdaStep (FFilterFunction &&InFunc)
template<typename FuncType>
FFrontendQuery & AddFunctionStep (FuncType &&InFunc)
METASOUNDFRONTEND_API FFrontendQuery & AddLimitLambdaStep (FLimitFunction &&InFunc)
METASOUNDFRONTEND_API FFrontendQuery & AddMapLambdaStep (FMapFunction &&InFunc)
METASOUNDFRONTEND_API FFrontendQuery & AddReduceLambdaStep (FReduceFunction &&InFunc)
METASOUNDFRONTEND_API FFrontendQuery & AddScoreLambdaStep (FScoreFunction &&InFunc)
METASOUNDFRONTEND_API FFrontendQuery & AddSortLambdaStep (FSortFunction &&InFunc)
template<typename StepType, typename... ArgTypes>
FFrontendQuery & AddStep (ArgTypes &&... Args)
Add a step to the query.
METASOUNDFRONTEND_API FFrontendQuery & AddStep (TUniquePtr< FFrontendQueryStep > &&InStep)
Add a step to the query.
METASOUNDFRONTEND_API FFrontendQuery & AddStreamLambdaStep (FStreamFunction &&InFunc)
METASOUNDFRONTEND_API FFrontendQuery & AddTransformLambdaStep (FTransformFunction &&InFunc)
METASOUNDFRONTEND_API const FFrontendQuerySelection & GetSelection () const
Returns the current result.
FFrontendQuery & operator= (const FFrontendQuery &)=delete
FFrontendQuery & operator= (FFrontendQuery &&)=default
METASOUNDFRONTEND_API const FFrontendQuerySelection & Update ()
METASOUNDFRONTEND_API const FFrontendQuerySelection & Update (TSet< FFrontendQueryKey > &OutUpdatedKeys)
Calls all steps in the query and returns the selection.
Private Types
using FIncremental = FFrontendQueryStep::FIncremental
Private Member Functions
METASOUNDFRONTEND_API void AppendPartitions (const TSet< FFrontendQueryKey > &InKeysToAppend, const FFrontendQuerySelection &InSelection, TSet< FFrontendQueryKey > &OutKeysModified, FFrontendQuerySelection &OutSelection) const
METASOUNDFRONTEND_API void MergeInternal (FFrontendQueryStep &Step, FIncremental &InOutIncremental, FFrontendQuerySelection &InOutMergedSelection)
METASOUNDFRONTEND_API void UpdateInternal (TSet< FFrontendQueryKey > &OutUpdatedKeys)
Private Attributes
int32 FinalEntryProducingStepIndex = INDEX_NONE
TSharedRef< FFrontendQuerySelection, ESPMode::ThreadSafe > Result
TArray< FStepInfo > Steps
Detailed Description
FFrontendQuery contains a set of query steps which produce a FFrontendQuerySelectionView.
Definition at line 445 of file MetasoundFrontendQuery.h.
Member Typedef Documentation
FFilterFunction
using Metasound::FFrontendQuery::FFilterFunction = FFrontendQueryStep::FFilterFunction
Definition at line 453 of file MetasoundFrontendQuery.h.
FIncremental
using Metasound::FFrontendQuery::FIncremental = FFrontendQueryStep::FIncremental private
Definition at line 499 of file MetasoundFrontendQuery.h.
FLimitFunction
using Metasound::FFrontendQuery::FLimitFunction = FFrontendQueryStep::FLimitFunction
Definition at line 456 of file MetasoundFrontendQuery.h.
FMapFunction
using Metasound::FFrontendQuery::FMapFunction = FFrontendQueryStep::FMapFunction
Definition at line 451 of file MetasoundFrontendQuery.h.
FReduceFunction
using Metasound::FFrontendQuery::FReduceFunction = FFrontendQueryStep::FReduceFunction
Definition at line 452 of file MetasoundFrontendQuery.h.
FScoreFunction
using Metasound::FFrontendQuery::FScoreFunction = FFrontendQueryStep::FScoreFunction
Definition at line 454 of file MetasoundFrontendQuery.h.
FSortFunction
using Metasound::FFrontendQuery::FSortFunction = FFrontendQueryStep::FSortFunction
Definition at line 455 of file MetasoundFrontendQuery.h.
FStreamFunction
using Metasound::FFrontendQuery::FStreamFunction = FFrontendQueryStep::FStreamFunction
Definition at line 449 of file MetasoundFrontendQuery.h.
FTransformFunction
using Metasound::FFrontendQuery::FTransformFunction = FFrontendQueryStep::FTransformFunction
Definition at line 450 of file MetasoundFrontendQuery.h.
Constructor & Destructor Documentation
FFrontendQuery() [1/3]
METASOUNDFRONTEND_API Metasound::FFrontendQuery::FFrontendQuery ()
References UE_API.
Referenced by FFrontendQuery(), FFrontendQuery(), AddFilterLambdaStep(), AddFunctionStep(), AddLimitLambdaStep(), AddMapLambdaStep(), AddReduceLambdaStep(), AddScoreLambdaStep(), AddSortLambdaStep(), AddStep(), AddStep(), AddStreamLambdaStep(), AddTransformLambdaStep(), operator=(), and operator=().
FFrontendQuery() [2/3]
Metasound::FFrontendQuery::FFrontendQuery (FFrontendQuery &&) default
References FFrontendQuery().
FFrontendQuery() [3/3]
Metasound::FFrontendQuery::FFrontendQuery (const FFrontendQuery &) delete
References FFrontendQuery().
Member Function Documentation
AddFilterLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddFilterLambdaStep (FFilterFunction && InFunc)
References FFrontendQuery(), and UE_API.
AddFunctionStep()
template<typename FuncType> FFrontendQuery & Metasound::FFrontendQuery::AddFunctionStep (FuncType && InFunc) inline
Definition at line 474 of file MetasoundFrontendQuery.h.
References FFrontendQuery(), AddStep(), MakeUnique(), and MoveTemp().
AddLimitLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddLimitLambdaStep (FLimitFunction && InFunc)
References FFrontendQuery(), and UE_API.
AddMapLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddMapLambdaStep (FMapFunction && InFunc)
References FFrontendQuery(), and UE_API.
AddReduceLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddReduceLambdaStep (FReduceFunction && InFunc)
References FFrontendQuery(), and UE_API.
AddScoreLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddScoreLambdaStep (FScoreFunction && InFunc)
References FFrontendQuery(), and UE_API.
AddSortLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddSortLambdaStep (FSortFunction && InFunc)
References FFrontendQuery(), and UE_API.
AddStep() [1/2]
template<typename StepType, typename... ArgTypes> FFrontendQuery & Metasound::FFrontendQuery::AddStep (ArgTypes &&... Args) inline
Add a step to the query.
Definition at line 468 of file MetasoundFrontendQuery.h.
References FFrontendQuery(), AddStep(), Forward(), and MakeUnique().
Referenced by AddFunctionStep(), and AddStep().
AddStep() [2/2]
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddStep (TUniquePtr< FFrontendQueryStep > && InStep)
Add a step to the query.
References FFrontendQuery(), and UE_API.
AddStreamLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddStreamLambdaStep (FStreamFunction && InFunc)
References FFrontendQuery(), and UE_API.
AddTransformLambdaStep()
METASOUNDFRONTEND_API FFrontendQuery & Metasound::FFrontendQuery::AddTransformLambdaStep (FTransformFunction && InFunc)
References FFrontendQuery(), and UE_API.
AppendPartitions()
METASOUNDFRONTEND_API void Metasound::FFrontendQuery::AppendPartitions (const TSet< FFrontendQueryKey > & InKeysToAppend, const FFrontendQuerySelection & InSelection, TSet< FFrontendQueryKey > & OutKeysModified, FFrontendQuerySelection & OutSelection) const private
References UE_API.
GetSelection()
METASOUNDFRONTEND_API const FFrontendQuerySelection & Metasound::FFrontendQuery::GetSelection () const
Returns the current result.
References UE_API.
MergeInternal()
METASOUNDFRONTEND_API void Metasound::FFrontendQuery::MergeInternal (FFrontendQueryStep & Step, FIncremental & InOutIncremental, FFrontendQuerySelection & InOutMergedSelection) private
References UE_API.
operator=() [1/2]
FFrontendQuery & Metasound::FFrontendQuery::operator= (const FFrontendQuery &) delete
References FFrontendQuery().
operator=() [2/2]
FFrontendQuery & Metasound::FFrontendQuery::operator= (FFrontendQuery &&) default
References FFrontendQuery().
Update() [1/2]
METASOUNDFRONTEND_API const FFrontendQuerySelection & Metasound::FFrontendQuery::Update ()
References UE_API.
Update() [2/2]
METASOUNDFRONTEND_API const FFrontendQuerySelection & Metasound::FFrontendQuery::Update (TSet< FFrontendQueryKey > & OutUpdatedKeys)
Calls all steps in the query and returns the selection.
References UE_API.
UpdateInternal()
METASOUNDFRONTEND_API void Metasound::FFrontendQuery::UpdateInternal (TSet< FFrontendQueryKey > & OutUpdatedKeys) private
References UE_API.
Field Documentation
FinalEntryProducingStepIndex
int32 Metasound::FFrontendQuery::FinalEntryProducingStepIndex = INDEX_NONE private
Definition at line 517 of file MetasoundFrontendQuery.h.
Result
TSharedRef<FFrontendQuerySelection, ESPMode::ThreadSafe> Metasound::FFrontendQuery::Result private
Definition at line 504 of file MetasoundFrontendQuery.h.
Steps
TArray<FStepInfo> Metasound::FFrontendQuery::Steps private
Definition at line 516 of file MetasoundFrontendQuery.h.
The documentation for this class was generated from the following file:
MetasoundFrontendQuery.h