Unreal Engine 5.6 C++ API: UE::Math Namespace Reference
UE::Math Namespace Reference
Implements an axis-aligned box.
Namespaces
namespace anonymous_namespace{ScaleRotationTranslationMatrix.h}
Data Structures
class FLinearFeedbackShiftRegister
struct TBasisVectorMatrix
struct TBox
struct TBox2
struct TBoxConstInit
struct TBoxSphereBounds
struct TCapsuleShape
struct TClipProjectionMatrix
Realigns the near plane for an existing projection matrix with an arbitrary clip plane from: http://sourceforge.net/mailarchive/message.php?msg_id=000901c26324%242181ea90%24a1e93942%40firefly Updated for the fact that our FPlane uses Ax+By+Cz=D.
struct TDualQuat
struct TIntPoint
Structure for integer points in 2-d space.
struct TIntRect
Structure for integer rectangles in 2-d space.
struct TIntVector2
struct TIntVector3
Structure for integer vectors in 3-d space.
struct TIntVector4
struct TInverseRotationMatrix
Inverse Rotation matrix.
struct TLookAtMatrix
struct TLookFromMatrix
struct TMatrix
struct TMirrorMatrix
Mirrors a point about an arbitrary plane.
struct TOrthoMatrix
struct TPerspectiveMatrix
struct TPlane
struct TPolynomialRootSolver
Find roots of a polynomial of a specified degree.
struct TQuat
Floating point quaternion that can represent a rotation about an axis in 3-D space.
struct TQuatRotationMatrix
Rotation matrix using quaternion rotation.
struct TQuatRotationTranslationMatrix
Rotation and translation matrix using quaternion rotation.
struct TRay
struct TReversedZOrthoMatrix
struct TReversedZPerspectiveMatrix
struct TRotationAboutPointMatrix
Rotates about an Origin point.
struct TRotationMatrix
Rotation matrix no translation.
struct TRotationTranslationMatrix
Combined rotation and translation matrix.
struct TRotator
Implements a container for rotation information.
struct TScaleMatrix
Scale matrix.
struct TScaleRotationTranslationMatrix
Combined Scale rotation and translation matrix.
struct TSphere
struct TTransform
struct TTranslationMatrix
struct TVector
A vector in 3-D space composed of components (X, Y, Z) with floating point precision.
struct TVector2
struct TVector4
A 4D homogeneous vector, 4x1 FLOATs, 16-byte aligned.
struct TVectorConstInit
Functions
template<typename T>
UE::Math::TMatrix< T > Concatenate (const UE::Math::TMatrix< T > &LHS, const UE::Math::TMatrix< T > &RHS)
Specialization for concatenating two Matrices.
template<typename T>
UE::Math::TQuat< T > Concatenate (const UE::Math::TQuat< T > &LHS, const UE::Math::TQuat< T > &RHS)
Specialization for concatenating two rotations.
template<typename T>
UE::Math::TVector2< T > Concatenate (const UE::Math::TVector2< T > &LHS, const UE::Math::TVector2< T > &RHS)
Specialization for concatenating two 2D Translations.
template<typename T>
UE::Math::TVector< T > Concatenate (const UE::Math::TVector< T > &LHS, const UE::Math::TVector< T > &RHS)
Specialization for concatenating two translations.
template<typename T>
uint32 GetTypeHash (const TBox< T > &Box)
template<typename IntType>
uint32 GetTypeHash (const TIntPoint< IntType > &InPoint)
template<typename IntType>
uint32 GetTypeHash (const TIntRect< IntType > &InRect)
template<typename T>
uint32 GetTypeHash (const TIntVector2< T > &Vector)
Creates a hash value from an IntVector2.
template<typename T>
uint32 GetTypeHash (const TIntVector3< T > &Vector)
Creates a hash value from an IntVector3.
template<typename T>
uint32 GetTypeHash (const TIntVector4< T > &Vector)
Creates a hash value from an IntVector4.
template<typename T>
FORCEINLINE uint32 GetTypeHash (const TQuat< T > &Quat)
Creates a hash value from an FQuat.
template<typename T>
uint32 GetTypeHash (const TTransform< T > &Transform)
Creates a hash value from an FTransform.
template<typename T>
FORCEINLINE uint32 GetTypeHash (const TVector2< T > &Vector)
Creates a hash value from a TVector2<T>.
template<typename T>
FORCEINLINE uint32 GetTypeHash (const TVector< T > &Vector)
Creates a hash value from an FVector.
template<typename T>
FORCEINLINE TQuat< T > operator* (const double Scale, const TQuat< T > &Q)
template<typename T>
FORCEINLINE TQuat< T > operator* (const float Scale, const TQuat< T > &Q)
template<typename T, typename FArg UE_REQUIRES>
FORCEINLINE TRotator< T > operator* (FArg Scale, const TRotator< T > &R)
Scale a rotator and return.
template<typename T, typename T2 UE_REQUIRES>
FORCEINLINE TVector2< T > operator* (T2 Scale, const TVector2< T > &V)
Multiplies a Vector2 by a scaling factor.
template<typename T, typename T2 UE_REQUIRES>
FORCEINLINE TVector4< T > operator* (T2 Scale, const TVector4< T > &V)
Scales a vector.
template<typename T, typename T2 UE_REQUIRES>
FORCEINLINE TVector< T > operator* (T2 Scale, const TVector< T > &V)
Multiplies a vector by a scaling factor.
FArchive & operator<< (FArchive &Ar, TBoxSphereBounds< double, double > &Bounds)
Serializes the given bounding volume from or into the specified archive.
FArchive & operator<< (FArchive &Ar, TBoxSphereBounds< float, float > &Bounds)
Serializes the given bounding volume from or into the specified archive.
FArchive & operator<< (FArchive &Ar, TMatrix< double > &M)
Serializes the Matrix.
FArchive & operator<< (FArchive &Ar, TMatrix< float > &M)
Serializes the Matrix.
FArchive & operator<< (FArchive &Ar, TPlane< double > &P)
Serializer.
FArchive & operator<< (FArchive &Ar, TPlane< float > &P)
Serializer.
FArchive & operator<< (FArchive &Ar, TQuat< double > &F)
FArchive & operator<< (FArchive &Ar, TQuat< float > &F)
Serializes the quaternion.
FArchive & operator<< (FArchive &Ar, TRotator< double > &R)
FArchive & operator<< (FArchive &Ar, TRotator< float > &R)
Serializer.
FArchive & operator<< (FArchive &Ar, TSphere< double > &Sphere)
Serializes the given sphere from or into the specified archive.
FArchive & operator<< (FArchive &Ar, TSphere< float > &Sphere)
Serializes the given sphere from or into the specified archive.
FArchive & operator<< (FArchive &Ar, TVector2< double > &V)
FArchive & operator<< (FArchive &Ar, TVector2< float > &V)
Serialize a vector.
FArchive & operator<< (FArchive &Ar, TVector4< double > &V)
FArchive & operator<< (FArchive &Ar, TVector4< float > &V)
Serializer.
FArchive & operator<< (FArchive &Ar, TVector< double > &V)
Serializer for FVector3d.
FArchive & operator<< (FArchive &Ar, TVector< float > &V)
Serializer for FVector3f.
void operator<< (FStructuredArchive::FSlot Slot, TVector2< double > &V)
void operator<< (FStructuredArchive::FSlot Slot, TVector2< float > &V)
void operator<< (FStructuredArchive::FSlot Slot, TVector< double > &V)
Structured archive slot serializer for FVector3d.
void operator<< (FStructuredArchive::FSlot Slot, TVector< float > &V)
Structured archive slot serializer for FVector3f.
template<typename RealType>
std::ostream & operator<< (std::ostream &os, const TVector2< RealType > &Vec)
template<typename RealType>
std::ostream & operator<< (std::ostream &os, const TVector4< RealType > &Vec)
Detailed Description
Implements an axis-aligned box.
Boxes describe an axis-aligned extent in three dimensions. They are used for many different things in the Engine and in games, such as bounding volumes, collision detection and visibility calculation.
Function Documentation
Concatenate() [1/4]
template<typename T> UE::Math::TMatrix< T > UE::Math::Concatenate (const UE::Math::TMatrix< T > & LHS, const UE::Math::TMatrix< T > & RHS) inline
Specialization for concatenating two Matrices.
Parameters
LHS rotation that goes from space A to space B
RHS rotation that goes from space B to space C.
Returns
a new rotation representing the transformation from the input space of LHS to the output space of RHS.
Definition at line 285 of file TransformCalculus3D.h.
Concatenate() [2/4]
template<typename T> UE::Math::TQuat< T > UE::Math::Concatenate (const UE::Math::TQuat< T > & LHS, const UE::Math::TQuat< T > & RHS) inline
Specialization for concatenating two rotations.
NOTE: UE::Math::TQuat<T> concatenates right to left, opposite of how UE::Math::TMatrix<T> implements it. Confusing, no? That's why we have these high level functions!
Parameters
LHS rotation that goes from space A to space B
RHS rotation that goes from space B to space C.
Returns
a new rotation representing the transformation from the input space of LHS to the output space of RHS.
Definition at line 316 of file TransformCalculus3D.h.
Concatenate() [3/4]
template<typename T> UE::Math::TVector2< T > UE::Math::Concatenate (const UE::Math::TVector2< T > & LHS, const UE::Math::TVector2< T > & RHS) inline nodiscard
Specialization for concatenating two 2D Translations.
Definition at line 45 of file TransformCalculus2D.h.
Concatenate() [4/4]
template<typename T> UE::Math::TVector< T > UE::Math::Concatenate (const UE::Math::TVector< T > & LHS, const UE::Math::TVector< T > & RHS) inline
Specialization for concatenating two translations.
Parameters
LHS Translation that goes from space A to space B
RHS Translation that goes from space B to space C.
Returns
a new Translation representing the transformation from the input space of LHS to the output space of RHS.
Definition at line 299 of file TransformCalculus3D.h.
GetTypeHash() [1/10]
template<typename T> uint32 UE::Math::GetTypeHash (const TBox< T > & Box)
Definition at line 993 of file Box.h.
References Box, GetTypeHash(), and HashCombineFast().
Referenced by GetTypeHash(), GetTypeHash(), GetTypeHash(), and GetTypeHash().
GetTypeHash() [2/10]
template<typename IntType> uint32 UE::Math::GetTypeHash (const TIntPoint< IntType > & InPoint)
Definition at line 536 of file IntPoint.h.
References GetTypeHash(), HashCombine(), UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
GetTypeHash() [3/10]
template<typename IntType> uint32 UE::Math::GetTypeHash (const TIntRect< IntType > & InRect)
Definition at line 514 of file IntRect.h.
References GetTypeHash(), HashCombine(), UE::Math::TIntRect< InIntType >::Max, and UE::Math::TIntRect< InIntType >::Min.
GetTypeHash() [4/10]
template<typename T> uint32 UE::Math::GetTypeHash (const TIntVector2< T > & Vector)
Creates a hash value from an IntVector2.
Parameters
Vector the vector to create a hash value for
Returns
The hash value from the components
Definition at line 1851 of file IntVector.h.
References FCrc::MemCrc32(), and Vector.
GetTypeHash() [5/10]
template<typename T> uint32 UE::Math::GetTypeHash (const TIntVector3< T > & Vector)
Creates a hash value from an IntVector3.
Parameters
Vector the vector to create a hash value for
Returns
The hash value from the components
Definition at line 1864 of file IntVector.h.
References FCrc::MemCrc_DEPRECATED(), and Vector.
GetTypeHash() [6/10]
template<typename T> uint32 UE::Math::GetTypeHash (const TIntVector4< T > & Vector)
Creates a hash value from an IntVector4.
Parameters
Vector the vector to create a hash value for
Returns
The hash value from the components
Definition at line 1877 of file IntVector.h.
References FCrc::MemCrc32(), and Vector.
GetTypeHash() [7/10]
template<typename T> FORCEINLINE uint32 UE::Math::GetTypeHash (const TQuat< T > & Quat)
Creates a hash value from an FQuat.
Parameters
Quat the quat to create a hash value for
Returns
The hash value from the components
Definition at line 1410 of file Quat.h.
References FORCEINLINE, FCrc::MemCrc_DEPRECATED(), and Quat.
GetTypeHash() [8/10]
template<typename T> uint32 UE::Math::GetTypeHash (const TTransform< T > & Transform) inline
Creates a hash value from an FTransform.
Parameters
Transform the transform to create a hash value for
Returns
The hash value from the components
Definition at line 51 of file Math/Transform.h.
References GetTypeHash(), Hash, HashCombineFast(), and Transform.
GetTypeHash() [9/10]
template<typename T> FORCEINLINE uint32 UE::Math::GetTypeHash (const TVector2< T > & Vector)
Creates a hash value from a TVector2<T>.
Parameters
Vector the vector to create a hash value for
Returns
The hash value from the components
Definition at line 789 of file Vector2D.h.
References FORCEINLINE, FCrc::MemCrc_DEPRECATED(), and Vector.
GetTypeHash() [10/10]
template<typename T> FORCEINLINE uint32 UE::Math::GetTypeHash (const TVector< T > & Vector)
Creates a hash value from an FVector.
Parameters
Vector the vector to create a hash value for
Returns
The hash value from the components
Definition at line 2580 of file Vector.h.
References FORCEINLINE, FCrc::MemCrc_DEPRECATED(), and Vector.
operator*() [1/6]
template<typename T> FORCEINLINE TQuat< T > UE::Math::operator* (const double Scale, const TQuat< T > & Q)
Definition at line 1062 of file Quat.h.
References FORCEINLINE, and Scale.
operator*() [2/6]
template<typename T> FORCEINLINE TQuat< T > UE::Math::operator* (const float Scale, const TQuat< T > & Q)
Definition at line 1055 of file Quat.h.
References FORCEINLINE, and Scale.
operator*() [3/6]
template<typename T, typename FArg UE_REQUIRES> FORCEINLINE TRotator< T > UE::Math::operator* (FArg Scale, const TRotator< T > & R)
Scale a rotator and return.
Parameters
Scale scale to apply to R.
R rotator to be scaled.
Returns
Scaled rotator.
Definition at line 555 of file Rotator.h.
References FORCEINLINE, R, and Scale.
operator*() [4/6]
template<typename T, typename T2 UE_REQUIRES> FORCEINLINE TVector2< T > UE::Math::operator* (T2 Scale, const TVector2< T > & V)
Multiplies a Vector2 by a scaling factor.
Parameters
Scale Scaling factor.
V Vector2 to scale.
Returns
Result of multiplication.
Definition at line 878 of file Vector2D.h.
References FORCEINLINE, and Scale.
operator*() [5/6]
template<typename T, typename T2 UE_REQUIRES> FORCEINLINE TVector4< T > UE::Math::operator* (T2 Scale, const TVector4< T > & V)
Scales a vector.
Parameters
Scale The scaling factor.
V The vector to scale.
Returns
The result of scaling.
Definition at line 1069 of file Vector4.h.
References FORCEINLINE, and Scale.
operator*() [6/6]
template<typename T, typename T2 UE_REQUIRES> FORCEINLINE TVector< T > UE::Math::operator* (T2 Scale, const TVector< T > & V)
Multiplies a vector by a scaling factor.
Parameters
Scale Scaling factor.
V Vector to scale.
Returns
Result of multiplication.
Definition at line 2568 of file Vector.h.
References FORCEINLINE, and Scale.
operator<<() [1/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TBoxSphereBounds< double, double > & Bounds) inline
Serializes the given bounding volume from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Bounds The bounding volume to serialize.
Returns
The archive..
Definition at line 409 of file BoxSphereBounds.h.
References Ar, UE::Math::TBoxSphereBounds< T, TExtent >::BoxExtent, checkf, LARGE_WORLD_COORDINATES, UE::Math::TBoxSphereBounds< T, TExtent >::Origin, UE::Math::TBoxSphereBounds< T, TExtent >::SphereRadius, and TEXT.
operator<<() [2/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TBoxSphereBounds< float, float > & Bounds) inline
Serializes the given bounding volume from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Bounds The bounding volume to serialize.
Returns
The archive..
Definition at line 396 of file BoxSphereBounds.h.
References Ar, UE::Math::TBoxSphereBounds< T, TExtent >::BoxExtent, UE::Math::TBoxSphereBounds< T, TExtent >::Origin, and UE::Math::TBoxSphereBounds< T, TExtent >::SphereRadius.
operator<<() [3/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TMatrix< double > & M) inline
Serializes the Matrix.
Parameters
Ar Reference to the serialization archive.
M Reference to the matrix being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 503 of file Matrix.h.
References Ar, checkf, UE::Math::TMatrix< T >::DiagnosticCheckNaN(), LARGE_WORLD_COORDINATES, UE::Math::TMatrix< T >::M, and TEXT.
operator<<() [4/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TMatrix< float > & M) inline
Serializes the Matrix.
Parameters
Ar Reference to the serialization archive.
M Reference to the matrix being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 486 of file Matrix.h.
References Ar, UE::Math::TMatrix< T >::DiagnosticCheckNaN(), and UE::Math::TMatrix< T >::M.
operator<<() [5/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TPlane< double > & P) inline
Serializer.
Parameters
Ar Serialization Archive.
P Plane to serialize.
Returns
Reference to Archive after serialization.
Definition at line 384 of file Plane.h.
References Ar, checkf, UE::Math::TPlane< T >::DiagnosticCheckNaN(), LARGE_WORLD_COORDINATES, TEXT, and UE::Math::TPlane< T >::W.
operator<<() [6/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TPlane< float > & P) inline
Serializer.
Parameters
Ar Serialization Archive.
P Plane to serialize.
Returns
Reference to Archive after serialization.
Definition at line 370 of file Plane.h.
References Ar, UE::Math::TPlane< T >::DiagnosticCheckNaN(), and UE::Math::TPlane< T >::W.
operator<<() [7/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TQuat< double > & F) inline
Definition at line 750 of file Quat.h.
References Ar, checkf, LARGE_WORLD_COORDINATES, TEXT, UE::Math::TQuat< T >::W, UE::Math::TQuat< T >::X, X, Y, UE::Math::TQuat< T >::Y, Z, and UE::Math::TQuat< T >::Z.
operator<<() [8/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TQuat< float > & F) inline
Serializes the quaternion.
Parameters
Ar Reference to the serialization archive.
F Reference to the quaternion being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 745 of file Quat.h.
References Ar, UE::Math::TQuat< T >::W, UE::Math::TQuat< T >::X, UE::Math::TQuat< T >::Y, and UE::Math::TQuat< T >::Z.
operator<<() [9/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TRotator< double > & R) inline
Definition at line 527 of file Rotator.h.
References Ar, checkf, LARGE_WORLD_COORDINATES, R, and TEXT.
operator<<() [10/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TRotator< float > & R) inline
Serializer.
Parameters
Ar Serialization Archive.
R Rotator being serialized.
Returns
Reference to Archive after serialization.
Definition at line 521 of file Rotator.h.
References Ar, and R.
operator<<() [11/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TSphere< double > & Sphere) inline
Serializes the given sphere from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Sphere The sphere to serialize.
Returns
The archive.
Definition at line 275 of file Sphere.h.
References Ar, checkf, LARGE_WORLD_COORDINATES, Sphere, and TEXT.
operator<<() [12/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TSphere< float > & Sphere) inline
Serializes the given sphere from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Sphere The sphere to serialize.
Returns
The archive.
Definition at line 261 of file Sphere.h.
References Ar, and Sphere.
operator<<() [13/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TVector2< double > & V) inline
Definition at line 821 of file Vector2D.h.
References Ar, checkf, LARGE_WORLD_COORDINATES, TEXT, UE::Math::TVector2< T >::X, X, Y, and UE::Math::TVector2< T >::Y.
operator<<() [14/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TVector2< float > & V) inline
Serialize a vector.
Parameters
Ar Serialization archive.
V Vector being serialized.
Returns
Reference to Archive after serialization.
Definition at line 805 of file Vector2D.h.
References Ar, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
operator<<() [15/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TVector4< double > & V) inline
Definition at line 618 of file Vector4.h.
References Ar, checkf, LARGE_WORLD_COORDINATES, TEXT, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, X, Y, UE::Math::TVector4< T >::Y, Z, and UE::Math::TVector4< T >::Z.
operator<<() [16/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TVector4< float > & V) inline
Serializer.
Parameters
Ar The Serialization Archive.
V The vector being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 613 of file Vector4.h.
References Ar, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
operator<<() [17/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TVector< double > & V) inline
Serializer for FVector3d.
Parameters
Ar Serialization Archive.
V Vector to serialize.
Definition at line 1244 of file Vector.h.
References Ar, checkf, UE::Math::TVector< T >::DiagnosticCheckNaN(), LARGE_WORLD_COORDINATES, TEXT, UE::Math::TVector< T >::X, X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
operator<<() [18/24]
FArchive & UE::Math::operator<< (FArchive & Ar, TVector< float > & V) inline
Serializer for FVector3f.
Parameters
Ar Serialization Archive.
V Vector to serialize.
Definition at line 1227 of file Vector.h.
References Ar, UE::Math::TVector< T >::DiagnosticCheckNaN(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
operator<<() [19/24]
void UE::Math::operator<< (FStructuredArchive::FSlot Slot, TVector2< double > & V) inline
Definition at line 840 of file Vector2D.h.
References checkf, FStructuredArchiveSlot::EnterStream(), UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), FArchive::IsLoading(), LARGE_WORLD_COORDINATES, Stream, TEXT, FArchive::UEVer(), UE::Math::TVector2< T >::X, X, Y, and UE::Math::TVector2< T >::Y.
operator<<() [20/24]
void UE::Math::operator<< (FStructuredArchive::FSlot Slot, TVector2< float > & V) inline
Definition at line 812 of file Vector2D.h.
References FStructuredArchiveSlot::EnterStream(), Stream, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
operator<<() [21/24]
void UE::Math::operator<< (FStructuredArchive::FSlot Slot, TVector< double > & V) inline
Structured archive slot serializer for FVector3d.
Parameters
Slot Structured archive slot.
V Vector to serialize.
Definition at line 1297 of file Vector.h.
References checkf, UE::Math::TVector< T >::DiagnosticCheckNaN(), FStructuredArchiveSlot::EnterRecord(), UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), FArchive::IsLoading(), LARGE_WORLD_COORDINATES, Record, SA_VALUE, TEXT, FArchive::UEVer(), UE::Math::TVector< T >::X, X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
operator<<() [22/24]
void UE::Math::operator<< (FStructuredArchive::FSlot Slot, TVector< float > & V) inline
Structured archive slot serializer for FVector3f.
Parameters
Slot Structured archive slot.
V Vector to serialize.
Definition at line 1279 of file Vector.h.
References UE::Math::TVector< T >::DiagnosticCheckNaN(), FStructuredArchiveSlot::EnterRecord(), Record, SA_VALUE, TEXT, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
operator<<() [23/24]
template<typename RealType> std::ostream & UE::Math::operator<< (std::ostream & os, const TVector2< RealType > & Vec)
Definition at line 425 of file VectorTypes.h.
References UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
operator<<() [24/24]
template<typename RealType> std::ostream & UE::Math::operator<< (std::ostream & os, const TVector4< RealType > & Vec)
Definition at line 432 of file VectorTypes.h.
References UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.