Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitBinding Struct Reference
UE::AnimNext::FTraitBinding Struct Reference
FTraitBinding.
#include "TraitBinding.h"
Public Member Functions
FTraitBinding ()=default
template<class TraitInterface>
bool AsInterface (TTraitBinding< TraitInterface > &OutBinding) const
template<class InstanceDataType>
InstanceDataType * GetInstanceData () const
ANIMNEXTANIMGRAPH_API FTraitInterfaceUID GetInterfaceUID () const
template<typename PropertyType>
const PropertyType * GetLatentProperty (FLatentPropertyHandle Handle) const
const FLatentPropertyHandle * GetLatentPropertyHandles () const
template<class SharedDataType>
const SharedDataType * GetSharedData () const
const FTraitStackBinding * GetStack () const
bool GetStackBaseTrait (FTraitBinding &OutBinding) const
template<class TraitInterface>
bool GetStackInterface (TTraitBinding< TraitInterface > &OutBinding) const
template<class TraitInterface>
bool GetStackInterfaceSuper (TTraitBinding< TraitInterface > &OutSuperBinding) const
const FTrait * GetTrait () const
uint32 GetTraitIndex () const
FWeakTraitPtr GetTraitPtr () const
template<class TraitInterface>
bool HasInterface () const
template<class TraitInterface>
bool HasStackInterface () const
template<class TraitInterface>
bool HasStackInterfaceSuper () const
bool IsValid () const
bool operator!= (const FTraitBinding &RHS) const
bool operator== (const FTraitBinding &RHS) const
void Reset ()
Protected Member Functions
FTraitBinding (const FTraitStackBinding *InStack, const FTrait *InTraitImpl, uint32 InTraitIndex, int32 InInterfaceThisOffset=-1)
bool AsInterfaceImpl (FTraitInterfaceUID InterfaceUID, FTraitBinding &OutBinding) const
template<class TraitInterfaceType>
const TraitInterfaceType * GetInterfaceTyped () const
bool HasInterfaceImpl (FTraitInterfaceUID InterfaceUID) const
Protected Attributes
friend FExecutionContext
friend FTraitStackBinding
int32 InterfaceThisOffset = -1
const FTraitStackBinding * Stack = nullptr
const FTrait * TraitImpl = nullptr
uint32 TraitIndex = 0
Detailed Description
FTraitBinding.
Base class for all trait bindings. A trait binding contains untyped data about a specific trait instance.
Definition at line 37 of file TraitBinding.h.
Constructor & Destructor Documentation
FTraitBinding() [1/2]
UE::AnimNext::FTraitBinding::FTraitBinding () default
Referenced by AsInterfaceImpl(), GetStackBaseTrait(), operator!=(), operator==(), and Reset().
FTraitBinding() [2/2]
UE::AnimNext::FTraitBinding::FTraitBinding (const FTraitStackBinding * InStack, const FTrait * InTraitImpl, uint32 InTraitIndex, int32 InInterfaceThisOffset = -1) inline protected
Definition at line 206 of file TraitBinding.h.
References FTraitStackBinding, InterfaceThisOffset, Stack, TraitImpl, and TraitIndex.
Member Function Documentation
AsInterface()
template<class TraitInterface> bool UE::AnimNext::FTraitBinding::AsInterface (TTraitBinding< TraitInterface > & OutBinding) const inline
Definition at line 144 of file TraitBinding.h.
References AsInterfaceImpl().
AsInterfaceImpl()
bool UE::AnimNext::FTraitBinding::AsInterfaceImpl (FTraitInterfaceUID InterfaceUID, FTraitBinding & OutBinding) const inline protected
Definition at line 223 of file TraitBinding.h.
References FTraitBinding(), IsValid(), Stack, TraitImpl, and TraitIndex.
Referenced by AsInterface().
GetInstanceData()
template<class InstanceDataType> InstanceDataType * UE::AnimNext::FTraitBinding::GetInstanceData () const inline
Definition at line 72 of file TraitBinding.h.
References UE::AnimNext::FTraitTemplate::GetTraitInstance(), IsValid(), Stack, and TraitIndex.
GetInterfaceTyped()
template<class TraitInterfaceType> const TraitInterfaceType * UE::AnimNext::FTraitBinding::GetInterfaceTyped () const inline protected
Definition at line 216 of file TraitBinding.h.
References check, InterfaceThisOffset, and TraitImpl.
Referenced by UE::AnimNext::TTraitBinding< IAlphaInputArgs >::GetInterface(), UE::AnimNext::TTraitBinding< IAttributeProvider >::GetInterface(), UE::AnimNext::TTraitBinding< IBlendStack >::GetInterface(), UE::AnimNext::TTraitBinding< IContinuousBlend >::GetInterface(), UE::AnimNext::TTraitBinding< IDiscreteBlend >::GetInterface(), UE::AnimNext::TTraitBinding< IEvaluate >::GetInterface(), UE::AnimNext::TTraitBinding< IGarbageCollection >::GetInterface(), UE::AnimNext::TTraitBinding< IGraphFactory >::GetInterface(), UE::AnimNext::TTraitBinding< IGroupSynchronization >::GetInterface(), UE::AnimNext::TTraitBinding< IHierarchy >::GetInterface(), UE::AnimNext::TTraitBinding< IInertializerBlend >::GetInterface(), UE::AnimNext::TTraitBinding< INotifySource >::GetInterface(), UE::AnimNext::TTraitBinding< ISmoothBlend >::GetInterface(), UE::AnimNext::TTraitBinding< ISmoothBlendPerBone >::GetInterface(), UE::AnimNext::TTraitBinding< ITimeline >::GetInterface(), UE::AnimNext::TTraitBinding< ITimelinePlayer >::GetInterface(), UE::AnimNext::TTraitBinding< IUpdate >::GetInterface(), and UE::AnimNext::TTraitBinding< IUpdateTraversal >::GetInterface().
GetInterfaceUID()
ANIMNEXTANIMGRAPH_API FTraitInterfaceUID UE::AnimNext::FTraitBinding::GetInterfaceUID () const
References UE_API.
GetLatentProperty()
template<typename PropertyType> const PropertyType * UE::AnimNext::FTraitBinding::GetLatentProperty (FLatentPropertyHandle Handle) const inline
Definition at line 109 of file TraitBinding.h.
References Handle, IsValid(), and Stack.
GetLatentPropertyHandles()
const FLatentPropertyHandle * UE::AnimNext::FTraitBinding::GetLatentPropertyHandles () const inline
Definition at line 89 of file TraitBinding.h.
References UE::AnimNext::FTraitTemplate::GetTraitLatentPropertyHandles(), UE::AnimNext::FTraitTemplate::HasLatentProperties(), IsValid(), Stack, and TraitIndex.
GetSharedData()
template<class SharedDataType> const SharedDataType * UE::AnimNext::FTraitBinding::GetSharedData () const inline
Definition at line 54 of file TraitBinding.h.
References UE::AnimNext::FTraitTemplate::GetTraitDescription(), IsValid(), Stack, and TraitIndex.
GetStack()
const FTraitStackBinding * UE::AnimNext::FTraitBinding::GetStack () const inline
Definition at line 180 of file TraitBinding.h.
References FTraitStackBinding, and Stack.
Referenced by UE::AnimNext::IHierarchy::GetForwardedStackInterface(), UE::AnimNext::IHierarchy::GetNumStackChildren(), UE::AnimNext::IHierarchy::GetStackChildren(), and UE::AnimNext::FExecutionContext::PopStackScopedInterfaces().
GetStackBaseTrait()
bool UE::AnimNext::FTraitBinding::GetStackBaseTrait (FTraitBinding & OutBinding) const inline
Definition at line 184 of file TraitBinding.h.
References FTraitBinding(), IsValid(), and Stack.
GetStackInterface()
template<class TraitInterface> bool UE::AnimNext::FTraitBinding::GetStackInterface (TTraitBinding< TraitInterface > & OutBinding) const inline
Definition at line 128 of file TraitBinding.h.
References IsValid(), and Stack.
GetStackInterfaceSuper()
template<class TraitInterface> bool UE::AnimNext::FTraitBinding::GetStackInterfaceSuper (TTraitBinding< TraitInterface > & OutSuperBinding) const inline
Definition at line 136 of file TraitBinding.h.
References IsValid(), and Stack.
GetTrait()
const FTrait * UE::AnimNext::FTraitBinding::GetTrait () const inline
Definition at line 196 of file TraitBinding.h.
References TraitImpl.
GetTraitIndex()
uint32 UE::AnimNext::FTraitBinding::GetTraitIndex () const inline
Definition at line 193 of file TraitBinding.h.
References Stack, and TraitIndex.
GetTraitPtr()
FWeakTraitPtr UE::AnimNext::FTraitBinding::GetTraitPtr () const inline
Definition at line 190 of file TraitBinding.h.
References Stack, and TraitIndex.
Referenced by UE::AnimNext::FExecutionContext::AllocateNodeInstance().
HasInterface()
template<class TraitInterface> bool UE::AnimNext::FTraitBinding::HasInterface () const inline
Definition at line 155 of file TraitBinding.h.
References HasInterfaceImpl().
HasInterfaceImpl()
bool UE::AnimNext::FTraitBinding::HasInterfaceImpl (FTraitInterfaceUID InterfaceUID) const inline protected
Definition at line 241 of file TraitBinding.h.
References IsValid(), and TraitImpl.
Referenced by HasInterface().
HasStackInterface()
template<class TraitInterface> bool UE::AnimNext::FTraitBinding::HasStackInterface () const inline
Definition at line 166 of file TraitBinding.h.
References IsValid(), and Stack.
HasStackInterfaceSuper()
template<class TraitInterface> bool UE::AnimNext::FTraitBinding::HasStackInterfaceSuper () const inline
Definition at line 174 of file TraitBinding.h.
References IsValid(), and Stack.
IsValid()
bool UE::AnimNext::FTraitBinding::IsValid () const inline
Definition at line 43 of file TraitBinding.h.
References TraitImpl.
Referenced by AsInterfaceImpl(), UE::AnimNext::IHierarchy::GetForwardedStackInterface(), GetInstanceData(), GetLatentProperty(), GetLatentPropertyHandles(), UE::AnimNext::IHierarchy::GetNumStackChildren(), GetSharedData(), GetStackBaseTrait(), UE::AnimNext::IHierarchy::GetStackChildren(), GetStackInterface(), GetStackInterfaceSuper(), HasInterfaceImpl(), HasStackInterface(), HasStackInterfaceSuper(), and UE::AnimNext::FExecutionContext::PopStackScopedInterfaces().
operator!=()
bool UE::AnimNext::FTraitBinding::operator!= (const FTraitBinding & RHS) const inline
Definition at line 203 of file TraitBinding.h.
References FTraitBinding(), and operator==().
operator==()
bool UE::AnimNext::FTraitBinding::operator== (const FTraitBinding & RHS) const inline
Definition at line 202 of file TraitBinding.h.
References FTraitBinding(), InterfaceThisOffset, Stack, and TraitIndex.
Referenced by operator!=().
Reset()
void UE::AnimNext::FTraitBinding::Reset () inline
Definition at line 46 of file TraitBinding.h.
References FTraitBinding().
Field Documentation
FExecutionContext
friend UE::AnimNext::FTraitBinding::FExecutionContext protected
Definition at line 265 of file TraitBinding.h.
Referenced by UE::AnimNext::TTraitBinding< IGarbageCollection >::AddReferencedObjects(), UE::AnimNext::TTraitBinding< IGroupSynchronization >::AdvanceBy(), UE::AnimNext::TTraitBinding< ITimelinePlayer >::AdvanceBy(), UE::AnimNext::TTraitBinding< IGraphFactory >::CreatePayloadForObject(), UE::AnimNext::TTraitBinding< IAlphaInputArgs >::Get(), UE::AnimNext::TTraitBinding< IBlendStack >::GetActiveGraph(), UE::AnimNext::TTraitBinding< IAlphaInputArgs >::GetAlphaCurveName(), UE::AnimNext::TTraitBinding< IAlphaInputArgs >::GetAlphaInputType(), UE::AnimNext::TTraitBinding< IDiscreteBlend >::GetBlendDestinationChildIndex(), UE::AnimNext::TTraitBinding< ISmoothBlendPerBone >::GetBlendProfile(), UE::AnimNext::TTraitBinding< IDiscreteBlend >::GetBlendState(), UE::AnimNext::TTraitBinding< IInertializerBlend >::GetBlendTime(), UE::AnimNext::TTraitBinding< ISmoothBlend >::GetBlendTime(), UE::AnimNext::TTraitBinding< ISmoothBlend >::GetBlendType(), UE::AnimNext::TTraitBinding< IContinuousBlend >::GetBlendWeight(), UE::AnimNext::TTraitBinding< IDiscreteBlend >::GetBlendWeight(), UE::AnimNext::TTraitBinding< IHierarchy >::GetChildren(), UE::AnimNext::TTraitBinding< IAlphaInputArgs >::GetCurrentAlphaValue(), UE::AnimNext::TTraitBinding< ISmoothBlend >::GetCustomBlendCurve(), UE::AnimNext::TTraitBinding< ITimeline >::GetDelta(), UE::AnimNext::TTraitBinding< IBlendStack >::GetGraph(), UE::AnimNext::TTraitBinding< IGraphFactory >::GetGraphFromObject(), UE::AnimNext::TTraitBinding< IGroupSynchronization >::GetGroupParameters(), UE::AnimNext::TTraitBinding< IAlphaInputArgs >::GetInputScaleBiasClampCallback(), UE::AnimNext::TTraitBinding< INotifySource >::GetNotifies(), UE::AnimNext::TTraitBinding< IHierarchy >::GetNumChildren(), UE::AnimNext::TTraitBinding< IAttributeProvider >::GetOnExtractRootMotionAttribute(), UE::AnimNext::TTraitBinding< ITimeline >::GetState(), UE::AnimNext::TTraitBinding< ITimeline >::GetSyncMarkers(), UE::AnimNext::TTraitBinding< IDiscreteBlend >::OnBlendInitiated(), UE::AnimNext::TTraitBinding< IDiscreteBlend >::OnBlendTerminated(), UE::AnimNext::TTraitBinding< IDiscreteBlend >::OnBlendTransition(), and UE::AnimNext::TTraitBinding< IBlendStack >::PushGraph().
FTraitStackBinding
friend UE::AnimNext::FTraitBinding::FTraitStackBinding protected
Definition at line 266 of file TraitBinding.h.
Referenced by FTraitBinding(), and GetStack().
InterfaceThisOffset
int32 UE::AnimNext::FTraitBinding::InterfaceThisOffset = -1 protected
Definition at line 263 of file TraitBinding.h.
Referenced by FTraitBinding(), GetInterfaceTyped(), and operator==().
Stack
const FTraitStackBinding* UE::AnimNext::FTraitBinding::Stack = nullptr protected
Definition at line 252 of file TraitBinding.h.
Referenced by FTraitBinding(), AsInterfaceImpl(), GetInstanceData(), GetLatentProperty(), GetLatentPropertyHandles(), GetSharedData(), GetStack(), GetStackBaseTrait(), GetStackInterface(), GetStackInterfaceSuper(), GetTraitIndex(), GetTraitPtr(), HasStackInterface(), HasStackInterfaceSuper(), and operator==().
TraitImpl
const FTrait* UE::AnimNext::FTraitBinding::TraitImpl = nullptr protected
Definition at line 256 of file TraitBinding.h.
Referenced by FTraitBinding(), AsInterfaceImpl(), GetInterfaceTyped(), GetTrait(), HasInterfaceImpl(), and IsValid().
TraitIndex
uint32 UE::AnimNext::FTraitBinding::TraitIndex = 0 protected
Definition at line 259 of file TraitBinding.h.
Referenced by FTraitBinding(), AsInterfaceImpl(), GetInstanceData(), GetLatentPropertyHandles(), GetSharedData(), GetTraitIndex(), GetTraitPtr(), and operator==().
The documentation for this struct was generated from the following file:
TraitBinding.h