Unreal Engine 5.6 C++ API: TVariant.h File Reference
TVariant.h File Reference
#include "Templates/Requires.h"
#include "TVariantMeta.h"
#include <type_traits>
Data Structures
struct FEmptyVariantState
A special tag that can be used as the first type in a TVariant parameter pack if none of the other types can be default-constructed.
struct TInPlaceType< T >
A special tag used to indicate that in-place construction of a variant should take place.
class TVariant< T, Ts >
A type-safe union based loosely on std::variant.
Functions
template<typename... Ts>
FArchive & operator<< (typename UE::Core::Private::TAlwaysFArchive< TVariant< Ts... > >::Type &Ar, TVariant< Ts... > &Variant)
Serialization function for TVariants.
template<typename Func, typename... Variants UE_REQUIRES>
decltype(auto) Visit (Func &&Callable, Variants &&... Args)
Apply a visitor function to the list of variants.
Function Documentation
operator<<()
template<typename... Ts> FArchive & operator<< (typename UE::Core::Private::TAlwaysFArchive< TVariant< Ts... > >::Type & Ar, TVariant< Ts... > & Variant) inline
Serialization function for TVariants.
In order for a TVariant to be serializable, each type in its template parameter pack must:
Have a default constructor. This is required because when reading the type from an archive, it must be default constructed before being loaded.
Implement the FArchive& operator<<(FArchive&, T&) function. This is required to serialize the actual type that's stored in TVariant.
Definition at line 262 of file TVariant.h.
References Ar, check, TVariant< T, Ts >::GetIndex(), UE::Core::Private::TVariantLoadFromArchiveLookup< Ts >::Load(), and Visit().
Visit()
template<typename Func, typename... Variants UE_REQUIRES> decltype(auto) Visit (Func && Callable, Variants &&... Args)
Apply a visitor function to the list of variants.
Definition at line 241 of file TVariant.h.
References UE::Core::Private::EncodeIndices(), Forward(), TVariantSize_V, and UE::Core::Private::VisitImpl().
Referenced by FIoStoreTocResourceStorage::ChopBytes(), Metasound::Frontend::FGraphLinter::DepthFirstTraversal(), FPersistentStorageManager::Initialize(), FIoDirectoryIndexReader::IterateDirectoryIndex(), operator<<(), UE::Core::Private::TPtrVariantBase< BaseType, true >::Reset(), and USTRUCT().