Unreal Engine 5.6 C++ API: UMeshSimplificationSettings Class Reference
UMeshSimplificationSettings Class Reference
#include "MeshSimplificationSettings.h"
Public Member Functions
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
UPROPERTY ()) bool bMeshReductionBackwardCompatible
UPROPERTY ()) FName MeshReductionModuleName
Mesh reduction plugin to use when simplifying mesh geometry.
Private Member Functions
virtual GENERATED_UCLASS_BODY() public FName GetCategoryName () const override
void SetMeshReductionModuleName (FName InMeshReductionModuleName)
Detailed Description
Definition at line 11 of file MeshSimplificationSettings.h.
Member Function Documentation
GetCategoryName()
virtual GENERATED_UCLASS_BODY() public FName UMeshSimplificationSettings::GetCategoryName () const override private virtual
PostEditChangeProperty()
virtual void UMeshSimplificationSettings::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void UMeshSimplificationSettings::PostInitProperties () override virtual
References PostInitProperties().
Referenced by PostInitProperties().
SetMeshReductionModuleName()
void UMeshSimplificationSettings::SetMeshReductionModuleName (FName InMeshReductionModuleName) private
UPROPERTY() [1/2]
UMeshSimplificationSettings::UPROPERTY ()
References Category, config, meta, and UPROPERTY().
UPROPERTY() [2/2]
UMeshSimplificationSettings::UPROPERTY ()
Mesh reduction plugin to use when simplifying mesh geometry.
References Category, config, and meta.
Referenced by UPROPERTY().
The documentation for this class was generated from the following file:
MeshSimplificationSettings.h