Unreal Engine 5.6 C++ API: InputSettings.h File Reference
InputSettings.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "InputCoreTypes.h"
#include "UObject/SoftObjectPath.h"
#include "GameFramework/PlayerInput.h"
#include "GenericPlatform/InputDeviceMappingPolicy.h"
#include "Components/InputComponent.h"
#include "Engine/PlatformSettings.h"
#include "InputSettings.generated.h"
Functions
ENUM_CLASS_FLAGS (EHardwareDeviceSupportedFeatures::Type)
UCLASS() class UInputSettings UENUM ()) namespace EHardwareDeviceSupportedFeatures
Project wide settings for input handling.
UENUM() enum class EHardwareDevicePrimaryType USTRUCT () struct FHardwareDeviceIdentifier
What is the primary use of an input device type?
Function Documentation
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EHardwareDeviceSupportedFeatures::Type)
References BlueprintType, Camera, Touch, and Unspecified.
UENUM()
UCLASS() class UInputSettings UENUM ()
Project wide settings for input handling.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Input/index.html A bitmask of supported features that a hardware device has.
A device that has not specified the type
This device can support basic key presses
This device can handle basic pointer behavior, such as a mouse
This device has basic gamepad support
This device supports touch in some capactiy (tablet, controller with a touch pad, etc)
Does this device have a camera on it that we can access?
Can this device track motion in a 3D space? (VR controllers, headset, etc)
This hardware supports setting a light color (such as an LED light bar)
Does this device have trigger haptics available?
Flagged true if this device supports force feedback
Does this device support vibrations sourced from an audio file?
This device can track acceleration in the users physical space
This is a virtual device simulating input, not a physical device
This device has a microphone on it that you can get audio from
This device can track the orientation in world space, such as a gyroscope
This device has the capabilities of a guitar (whammy bar, tilt, etc)
This device has the capabilities of drums (symbols, foot pedal, etc)
Some custom flags that can be used in your game if you have custom hardware!
A flag for ALL supported device flags
Definition at line 315 of file InputSettings.h.
References Acceleration, All, BlueprintType, Camera, Hidden, Meta, Pointer, Touch, UMETA, Unspecified, and Virtual.
USTRUCT()
UENUM() enum class EHardwareDevicePrimaryType USTRUCT ()
What is the primary use of an input device type?
Each hardware device can only be one primary type. An identifier that can be used to determine what input devices are available based on the FInputDeviceScope. These mappings should match a FInputDeviceScope that is used by an IInputDevice
The name of the Input Class that uses this hardware device. This should correspond with a FInputDeviceScope that is used by an IInputDevice
The name of this hardware device. This should correspond with a FInputDeviceScope that is used by an IInputDevice
The generic type that this hardware identifies as. This can be used to easily determine behaviors
Flags that represent this hardware device's traits
Returns true if this hardware device has ANY of the given supported feature flags
Returns true if this hardware device has ALL of the given supported feature flags
Returns true if this hardware device Identifier has valid names
Returns a string containing the Input Class Name and HardwareDeviceIdentifier properties concatenated together.
An Invalid Hardware Device Identifier.
Hardware device ID that represents a keyboard and mouse. This is what will be set when an Input Event's FKey is not a gamepad key.
Hardware device ID that represents a default, generic, gamepad.
Hardware device id that represents a default, generic, mobile touch input (tablet, phone, etc)
Definition at line 412 of file InputSettings.h.
References Ar, BlueprintType, Category, Flags, GENERATED_BODY, GetTypeHash(), Invalid, IsValid(), meta, operator!=(), operator<<(), operator==(), Other, ToString(), and UPROPERTY.