Unreal Engine 5.6 C++ API: UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates Struct Reference
UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates Struct Reference
Normal Coordinates as defined by "Discrete Conformal Equivalence of Polyhedral Surfaces" - Gillespi, Springborn, Crane, TOG V40 No4, 2021 This structure assumes that the surface mesh is fixed, and the intrinsic mesh shares the same vertex set as the surface mesh and is initialized with the same connectivity as the surface mesh.
#include "IntrinsicCorrespondenceUtils.h"
Data Structures
struct FEdgeAndCrossingIdx
Public Types
typedef FMeshConnection MyBase
Public Member Functions
FNormalCoordinates ()
DYNAMICMESH_API FNormalCoordinates (const FDynamicMesh3 &SurfMesh)
DYNAMICMESH_API int32 GetEdgeOrder (const int32 VID, const int32 SurfaceEID) const
DYNAMICMESH_API int32 GetNthEdgeID (const int32 VID, const int32 N) const
bool IsSurfaceEdgeSegment (const int32 IntrinsicEID) const
int32 NumCornerCrossingRefEdges (const FIndex3i &IntrinsicTriEIDs, const int32 TriCornerIndex) const
int32 NumCornerEmanatingRefEdges (const FIndex3i &IntrinsicTriEIDs, const int32 TriCornerIndex) const
int32 NumEdgeCrossing (const int32 IntrinsicEID) const
DYNAMICMESH_API bool OnFlipEdge (const int32 T0ID, const FIndex3i &BeforeT0EIDs, const int32 T0OppVID, const int32 T1ID, const FIndex3i &BeforeT1EIDs, const int32 T1OppVID, const int32 FlippedEID)
Update the NormalCoords and RoundaboutOrder after an intrinsic mesh edge flip.
DYNAMICMESH_API void Reset (const FDynamicMesh3 &SurfMesh)
Reset the connection to the given (not owned) surface mesh.
DYNAMICMESH_API void Reset (TUniquePtr< FDynamicMesh3 > &SurfMesh)
Reset the connection to used an internally owned surface mesh.
Public Member Functions inherited from UE::Geometry::IntrinsicCorrespondenceUtils::FMeshConnection
FMeshConnection ()
DYNAMICMESH_API FMeshConnection (const FDynamicMesh3 &SurfMesh)
DYNAMICMESH_API void Reset (const FDynamicMesh3 &SurfMesh)
Reset the connection to the given (not owned) surface mesh.
DYNAMICMESH_API void Reset (TUniquePtr< FDynamicMesh3 > &SurfMesh)
Reset the connection to used a internally owned surface mesh.
Data Fields
TArray< FIndex3i > EdgeOrder
TDynamicVector< int32 > NormalCoord
TArray< int32 > RefVertDegree
TDynamicVector< FIndex3i > RoundaboutOrder
Data Fields inherited from UE::Geometry::IntrinsicCorrespondenceUtils::FMeshConnection
TUniquePtr< FDynamicMesh3 > OwnedSurfaceMesh
const FDynamicMesh3 * SurfaceMesh
TArray< int32 > TIDToReferenceEID
TArray< int32 > VIDToReferenceEID
Protected Member Functions
DYNAMICMESH_API void RebuildNormalCoordinates (const FDynamicMesh3 &SurfMesh)
rebuild the normal coordinate data in this connection.
Detailed Description
Normal Coordinates as defined by "Discrete Conformal Equivalence of Polyhedral Surfaces" - Gillespi, Springborn, Crane, TOG V40 No4, 2021 This structure assumes that the surface mesh is fixed, and the intrinsic mesh shares the same vertex set as the surface mesh and is initialized with the same connectivity as the surface mesh.
Note, it is assumed that the surface mesh has no bow-ties.
Definition at line 125 of file IntrinsicCorrespondenceUtils.h.
Member Typedef Documentation
MyBase
typedef FMeshConnection UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::MyBase
Definition at line 127 of file IntrinsicCorrespondenceUtils.h.
Constructor & Destructor Documentation
FNormalCoordinates() [1/2]
UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::FNormalCoordinates () inline
Definition at line 129 of file IntrinsicCorrespondenceUtils.h.
FNormalCoordinates() [2/2]
DYNAMICMESH_API UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::FNormalCoordinates (const FDynamicMesh3 & SurfMesh)
References UE_API.
Member Function Documentation
GetEdgeOrder()
DYNAMICMESH_API int32 UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::GetEdgeOrder (const int32 VID, const int32 SurfaceEID) const
Returns
the Order of the edge EID about VID (counting CCW from the surface reference edge for this vertex). Note: this assumes that edge EID is adjacent to vertex VID - otherwise -1 is returned.
References UE_API.
GetNthEdgeID()
DYNAMICMESH_API int32 UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::GetNthEdgeID (const int32 VID, const int32 N) const
Returns
the edgeID of the N-th out-going edge in the SurfaceMesh (counting CCW from the reference edge for this vertex).
References UE_API.
IsSurfaceEdgeSegment()
bool UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::IsSurfaceEdgeSegment (const int32 IntrinsicEID) const inline
Returns
true if the specified intrinsic edge (indicated by IntrinsicEID) is a segment of a surface edge.
Note: By construction the initial intrinsic edges will have the same ID as the corresponding surface mesh edges, but edge splits will disrupt this. Also note: it is the responsibility of the caller to ensure IntrinsicEID is a valid edge on the intrinsic mesh.
Definition at line 250 of file IntrinsicCorrespondenceUtils.h.
References NormalCoord.
NumCornerCrossingRefEdges()
int32 UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::NumCornerCrossingRefEdges (const FIndex3i & IntrinsicTriEIDs, const int32 TriCornerIndex) const inline
Returns
number of surface edges that cross corner the specified corner of the intrinsic triangle defined by the given edges. note, it is assumed that IntrinsicTriEIDs are edge ID of an intrinsic triangle, but no checking is done.
Definition at line 277 of file IntrinsicCorrespondenceUtils.h.
References TMathUtil< RealType >::Max(), NumCornerEmanatingRefEdges(), and NumEdgeCrossing().
NumCornerEmanatingRefEdges()
int32 UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::NumCornerEmanatingRefEdges (const FIndex3i & IntrinsicTriEIDs, const int32 TriCornerIndex) const inline
Returns
number of surface edges within the specified intrinsic triangle that are adjacent to the specified triangle corner. This excludes any surface edges that are along the intrinsic triangle boundary edges. note it is assumed that IntrinsicTriEIDs are edge ID of an intrinsic triangle, but no checking is done.
Definition at line 257 of file IntrinsicCorrespondenceUtils.h.
References TMathUtil< RealType >::Max(), and NumEdgeCrossing().
Referenced by NumCornerCrossingRefEdges().
NumEdgeCrossing()
int32 UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::NumEdgeCrossing (const int32 IntrinsicEID) const inline
Returns
the number of surface edges that cross this intrinsic edge.
Note: it is the responsibility of the caller to ensure IntrinsicEID is a valid edge on the intrinsic mesh.
Definition at line 245 of file IntrinsicCorrespondenceUtils.h.
References TMathUtil< RealType >::Max(), and NormalCoord.
Referenced by NumCornerCrossingRefEdges(), and NumCornerEmanatingRefEdges().
OnFlipEdge()
DYNAMICMESH_API bool UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::OnFlipEdge (const int32 T0ID, const FIndex3i & BeforeT0EIDs, const int32 T0OppVID, const int32 T1ID, const FIndex3i & BeforeT1EIDs, const int32 T1OppVID, const int32 FlippedEID)
Update the NormalCoords and RoundaboutOrder after an intrinsic mesh edge flip.
TriAEID, and TriBEID are the triangle edges of the two affected triangles prior (!) to flipping the specified edge.
Returns
false if something failed
References UE_API.
RebuildNormalCoordinates()
DYNAMICMESH_API void UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::RebuildNormalCoordinates (const FDynamicMesh3 & SurfMesh) protected
rebuild the normal coordinate data in this connection.
Assumes the base connection data is consistent with this surface mesh
References UE_API.
Reset() [1/2]
DYNAMICMESH_API void UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::Reset (const FDynamicMesh3 & SurfMesh)
Reset the connection to the given (not owned) surface mesh.
References UE_API.
Reset() [2/2]
DYNAMICMESH_API void UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::Reset (TUniquePtr< FDynamicMesh3 > & SurfMesh)
Reset the connection to used an internally owned surface mesh.
References UE_API.
Field Documentation
EdgeOrder
TArray<FIndex3i> UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::EdgeOrder
Definition at line 199 of file IntrinsicCorrespondenceUtils.h.
NormalCoord
TDynamicVector<int32> UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::NormalCoord
Definition at line 195 of file IntrinsicCorrespondenceUtils.h.
Referenced by IsSurfaceEdgeSegment(), and NumEdgeCrossing().
RefVertDegree
TArray<int32> UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::RefVertDegree
Definition at line 198 of file IntrinsicCorrespondenceUtils.h.
RoundaboutOrder
TDynamicVector<FIndex3i> UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::RoundaboutOrder
Definition at line 196 of file IntrinsicCorrespondenceUtils.h.
The documentation for this struct was generated from the following file:
IntrinsicCorrespondenceUtils.h