Unreal Engine 5.6 C++ API: TPropertyValueIterator< T > Class Template Reference
TPropertyValueIterator< T > Class Template Reference
Templated version, will verify the property type is correct and will skip any properties that are not.
#include "UnrealType.h"
Public Types
using PairType = TPair<const T*, const void*>
Public Types inherited from FPropertyValueIterator
using BasePairType = TPair<const FProperty*, const void*>
Public Member Functions
TPropertyValueIterator ()=default
Invalid iterator, start with empty stack.
TPropertyValueIterator (const UStruct *InStruct, const void *InStructValue, EPropertyValueIteratorFlags InRecursionFlags=EPropertyValueIteratorFlags::FullRecursion, EFieldIteratorFlags::DeprecatedPropertyFlags InDeprecatedPropertyFlags=EFieldIteratorFlags::IncludeDeprecated)
Construct an iterator using a struct and struct value.
FORCEINLINE const T * Key () const
Returns Property currently being iterated.
FORCEINLINE const PairType & operator* () const
Returns a TPair containing Property/Value currently being iterated.
FORCEINLINE const PairType * operator-> () const
Public Member Functions inherited from FPropertyValueIterator
FPropertyValueIterator ()
Invalid iterator, start with empty stack.
FPropertyValueIterator (FFieldClass *InPropertyClass, const UStruct *InStruct, const void *InStructValue, EPropertyValueIteratorFlags InRecursionFlags=EPropertyValueIteratorFlags::FullRecursion, EFieldIteratorFlags::DeprecatedPropertyFlags InDeprecatedPropertyFlags=EFieldIteratorFlags::IncludeDeprecated)
Construct an iterator using a struct and struct value.
void GetPropertyChain (TArray< const FProperty * > &PropertyChain) const
Returns the full stack of properties for the property currently being iterated.
FString GetPropertyPathDebugString () const
Returns a string of the property chain in a form that makes reading it easy.
FORCEINLINE const FProperty * Key () const
Returns Property currently being iterated.
FORCEINLINE operator bool () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const FPropertyValueIterator &Rhs) const
FORCEINLINE const BasePairType & operator* () const
Returns a TPair containing Property/Value currently being iterated.
FORCEINLINE void operator++ ()
Increments iterator.
FORCEINLINE const BasePairType * operator-> () const
FORCEINLINE bool operator== (const FPropertyValueIterator &Rhs) const
FORCEINLINE void SkipRecursiveProperty ()
Call when iterating a recursive property such as Array or Struct to stop it from iterating into that property.
FORCEINLINE const void * Value () const
Returns memory address currently being iterated.
Detailed Description
template<class T>
class TPropertyValueIterator< T >
Templated version, will verify the property type is correct and will skip any properties that are not.
Definition at line 7197 of file UnrealType.h.
Member Typedef Documentation
PairType
template<class T> using TPropertyValueIterator< T >::PairType = TPair<const T*, const void*>
Definition at line 7200 of file UnrealType.h.
Constructor & Destructor Documentation
TPropertyValueIterator() [1/2]
template<class T> TPropertyValueIterator< T >::TPropertyValueIterator (const UStruct * InStruct, const void * InStructValue, EPropertyValueIteratorFlags InRecursionFlags = EPropertyValueIteratorFlags::FullRecursion, EFieldIteratorFlags::DeprecatedPropertyFlags InDeprecatedPropertyFlags = EFieldIteratorFlags::IncludeDeprecated) inline explicit
Construct an iterator using a struct and struct value.
Parameters
InStruct The UClass or UScriptStruct containing properties to search for
InStructValue Address in memory of struct to search for property values
InRecursionFlags Rather to recurse into container and struct properties
InDeprecatedPropertyFlags Rather to iterate over deprecated properties
Definition at line 7210 of file UnrealType.h.
References FPropertyValueIterator::FPropertyValueIterator(), FullRecursion, EFieldIteratorFlags::IncludeDeprecated, and StaticClass().
TPropertyValueIterator() [2/2]
template<class T> TPropertyValueIterator< T >::TPropertyValueIterator () default
Invalid iterator, start with empty stack.
Member Function Documentation
Key()
template<class T> FORCEINLINE const T * TPropertyValueIterator< T >::Key () const inline
Returns Property currently being iterated.
Definition at line 7232 of file UnrealType.h.
References FORCEINLINE.
operator*()
template<class T> FORCEINLINE const PairType & TPropertyValueIterator< T >::operator* () const inline
Returns a TPair containing Property/Value currently being iterated.
Definition at line 7221 of file UnrealType.h.
References FORCEINLINE, and FPropertyValueIterator::operator*().
operator->()
template<class T> FORCEINLINE const PairType * TPropertyValueIterator< T >::operator-> () const inline
Definition at line 7226 of file UnrealType.h.
References FORCEINLINE, and FPropertyValueIterator::operator->().
The documentation for this class was generated from the following file:
UnrealType.h