Unreal Engine 5.6 C++ API: TUniquePtr< T, Deleter > Class Template Reference
TUniquePtr< T, Deleter > Class Template Reference
#include "UniquePtr.h"
Inherits TDefaultDelete< T >.
Public Types
using ElementType = T
Public Member Functions
FORCEINLINE TUniquePtr ()
Default constructor - initializes the TUniquePtr to null.
TUniquePtr (const TUniquePtr &)=delete
FORCEINLINE TUniquePtr (TUniquePtr &&Other)
Move constructor.
template<typename OtherT, typename OtherDeleter UE_REQUIRES>
FORCEINLINE TUniquePtr (TUniquePtr< OtherT, OtherDeleter > &&Other)
Constructor from rvalues of other (usually derived) types.
FORCEINLINE TUniquePtr (TYPE_OF_NULLPTR)
nullptr constructor - initializes the TUniquePtr to null.
template<typename U UE_REQUIRES>
FORCEINLINE TUniquePtr (U *InPtr)
Pointer constructor - takes ownership of the pointed-to object.
template<typename U UE_REQUIRES>
FORCEINLINE TUniquePtr (U *InPtr, const Deleter &InDeleter)
Pointer constructor - takes ownership of the pointed-to object.
template<typename U UE_REQUIRES>
FORCEINLINE TUniquePtr (U *InPtr, Deleter &&InDeleter)
Pointer constructor - takes ownership of the pointed-to object.
FORCEINLINE ~TUniquePtr ()
Destructor.
FORCEINLINE T * Get () const
Returns a pointer to the owned object without relinquishing ownership.
FORCEINLINE Deleter & GetDeleter ()
Returns a reference to the deleter subobject.
FORCEINLINE const Deleter & GetDeleter () const
Returns a reference to the deleter subobject.
bool IsValid () const
Tests if the TUniquePtr currently owns an object.
FORCEINLINE operator bool () const
operator bool
template<typename RhsT>
FORCEINLINE bool operator!= (const TUniquePtr< RhsT > &Rhs) const
Inequality comparison operator.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
Inequality comparison operator against nullptr.
template<typename DummyT = T UE_REQUIRES(UE_REQUIRES_EXPR(*(DummyT*)nullptr))>
FORCEINLINE DummyT & operator* () const
Dereference operator.
FORCEINLINE T * operator-> () const
Indirection operator.
TUniquePtr & operator= (const TUniquePtr &)=delete
FORCEINLINE TUniquePtr & operator= (TUniquePtr &&Other)
Move assignment operator.
template<typename OtherT, typename OtherDeleter UE_REQUIRES>
FORCEINLINE TUniquePtr & operator= (TUniquePtr< OtherT, OtherDeleter > &&Other)
Assignment operator for rvalues of other (usually derived) types.
FORCEINLINE TUniquePtr & operator= (TYPE_OF_NULLPTR)
Nullptr assignment operator.
template<typename RhsT>
FORCEINLINE bool operator== (const TUniquePtr< RhsT > &Rhs) const
Equality comparison operator.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
Equality comparison operator against nullptr.
FORCEINLINE T * Release ()
Relinquishes control of the owned object to the caller and nulls the TUniquePtr.
FORCEINLINE void Reset (T *InPtr=nullptr)
Gives the TUniquePtr a new object to own, destroying any previously-owned object.
Private Types
using PtrType = T*
Private Member Functions
DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES (TUniquePtr, NonVirtual, Deleter)
LAYOUT_FIELD (PtrType, Ptr)
Private Member Functions inherited from TDefaultDelete< T >
TDefaultDelete ()=default
TDefaultDelete (const TDefaultDelete &)=default
template<typename U UE_REQUIRES>
TDefaultDelete (const TDefaultDelete< U > &)
~TDefaultDelete ()=default
DECLARE_INLINE_TYPE_LAYOUT (TDefaultDelete, NonVirtual)
void operator() (T *Ptr) const
TDefaultDelete & operator= (const TDefaultDelete &)=default
template<typename U UE_REQUIRES>
TDefaultDelete & operator= (const TDefaultDelete< U > &)
Friends
template<typename OtherT, typename OtherDeleter>
class TUniquePtr
Detailed Description
template<typename T, typename Deleter = TDefaultDelete<T>>
class TUniquePtr< T, Deleter >
Definition at line 106 of file UniquePtr.h.
Member Typedef Documentation
ElementType
template<typename T, typename Deleter = TDefaultDelete<T>> using TUniquePtr< T, Deleter >::ElementType = T
Definition at line 114 of file UniquePtr.h.
PtrType
template<typename T, typename Deleter = TDefaultDelete<T>> using TUniquePtr< T, Deleter >::PtrType = T* private
Definition at line 378 of file UniquePtr.h.
Constructor & Destructor Documentation
TUniquePtr() [1/8]
template<typename T, typename Deleter = TDefaultDelete<T>> TUniquePtr< T, Deleter >::TUniquePtr (const TUniquePtr< T, Deleter > &) delete
TUniquePtr() [2/8]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE TUniquePtr< T, Deleter >::TUniquePtr () inline
Default constructor - initializes the TUniquePtr to null.
Definition at line 123 of file UniquePtr.h.
TUniquePtr() [3/8]
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename U UE_REQUIRES> FORCEINLINE TUniquePtr< T, Deleter >::TUniquePtr (U * InPtr) inline explicit
Pointer constructor - takes ownership of the pointed-to object.
Parameters
InPtr The pointed-to object to take ownership of.
Definition at line 138 of file UniquePtr.h.
TUniquePtr() [4/8]
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename U UE_REQUIRES> FORCEINLINE TUniquePtr< T, Deleter >::TUniquePtr (U * InPtr, Deleter && InDeleter) inline explicit
Pointer constructor - takes ownership of the pointed-to object.
Parameters
InPtr The pointed-to object to take ownership of.
Definition at line 153 of file UniquePtr.h.
TUniquePtr() [5/8]
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename U UE_REQUIRES> FORCEINLINE TUniquePtr< T, Deleter >::TUniquePtr (U * InPtr, const Deleter & InDeleter) inline explicit
Pointer constructor - takes ownership of the pointed-to object.
Parameters
InPtr The pointed-to object to take ownership of.
Definition at line 168 of file UniquePtr.h.
TUniquePtr() [6/8]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE TUniquePtr< T, Deleter >::TUniquePtr (TYPE_OF_NULLPTR) inline
nullptr constructor - initializes the TUniquePtr to null.
Definition at line 177 of file UniquePtr.h.
TUniquePtr() [7/8]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE TUniquePtr< T, Deleter >::TUniquePtr (TUniquePtr< T, Deleter > && Other) inline
Move constructor.
Definition at line 186 of file UniquePtr.h.
TUniquePtr() [8/8]
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename OtherT, typename OtherDeleter UE_REQUIRES> FORCEINLINE TUniquePtr< T, Deleter >::TUniquePtr (TUniquePtr< OtherT, OtherDeleter > && Other) inline
Constructor from rvalues of other (usually derived) types.
Definition at line 204 of file UniquePtr.h.
~TUniquePtr()
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE TUniquePtr< T, Deleter >::~TUniquePtr () inline
Destructor.
Definition at line 270 of file UniquePtr.h.
Member Function Documentation
DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES()
template<typename T, typename Deleter = TDefaultDelete<T>> TUniquePtr< T, Deleter >::DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES (TUniquePtr< T, Deleter > , NonVirtual , Deleter) private
Get()
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE T * TUniquePtr< T, Deleter >::Get () const inline nodiscard
Returns a pointer to the owned object without relinquishing ownership.
Returns
A copy of the pointer to the object owned by the TUniquePtr, or nullptr if no object is being owned.
Definition at line 324 of file UniquePtr.h.
Referenced by FScopedWidgetSlotArguments< FNodeSlot >::AddSlot(), TCueDispatchTable< TCueHandler >::Dispatch(), FManagedStorageFileLockRegistry::GetLock(), TAnimatedAttribute< NumericType >::IdenticalTo(), FScopedWidgetSlotArguments< FNodeSlot >::InsertSlot(), TAsyncComponentDataComputeQueue< DataType >::LaunchJob(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator!=(), TUniquePtr< T[], Deleter >::operator!=(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator==(), TUniquePtr< T[], Deleter >::operator==(), and TGenericDataBackgroundCompute< ResultDataType >::UpdateResults().
GetDeleter() [1/2]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE Deleter & TUniquePtr< T, Deleter >::GetDeleter () inline nodiscard
Returns a reference to the deleter subobject.
Returns
A reference to the deleter.
Definition at line 362 of file UniquePtr.h.
Referenced by TUniquePtr< T, struct FPixelStreamingTaskDeleter >::~TUniquePtr(), TUniquePtr< T[], Deleter >::~TUniquePtr(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator=(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator=(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator=(), TUniquePtr< T[], Deleter >::operator=(), TUniquePtr< T[], Deleter >::operator=(), TUniquePtr< T[], Deleter >::operator=(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::Reset(), TUniquePtr< T[], Deleter >::Reset(), and TUniquePtr< T[], Deleter >::Reset().
GetDeleter() [2/2]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE const Deleter & TUniquePtr< T, Deleter >::GetDeleter () const inline nodiscard
Returns a reference to the deleter subobject.
Returns
A reference to the deleter.
Definition at line 372 of file UniquePtr.h.
IsValid()
template<typename T, typename Deleter = TDefaultDelete<T>> bool TUniquePtr< T, Deleter >::IsValid () const inline nodiscard
Tests if the TUniquePtr currently owns an object.
Returns
true if the TUniquePtr currently owns an object, false otherwise.
Definition at line 280 of file UniquePtr.h.
Referenced by Metasound::Frontend::GenerateClass(), UE::FGenericPlatformIoDispatcher::OpenFile(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator bool(), TUniquePtr< T[], Deleter >::operator bool(), operator!=(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator!=(), TUniquePtr< T[], Deleter >::operator!=(), operator==(), TUniquePtr< T, struct FPixelStreamingTaskDeleter >::operator==(), TUniquePtr< T[], Deleter >::operator==(), Metasound::FAddressRouter::RegisterNewReceiver(), Metasound::FDataTransmissionCenter::RegisterNewReceiver(), Metasound::FAddressRouter::RegisterNewSender(), Metasound::FDataTransmissionCenter::RegisterNewSender(), and UPackage::SetWorldTileInfo().
LAYOUT_FIELD()
template<typename T, typename Deleter = TDefaultDelete<T>> TUniquePtr< T, Deleter >::LAYOUT_FIELD (PtrType , Ptr) private
operator bool()
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE TUniquePtr< T, Deleter >::operator bool () const inline explicit nodiscard
operator bool
Returns
true if the TUniquePtr currently owns an object, false otherwise.
Definition at line 290 of file UniquePtr.h.
operator!=() [1/2]
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename RhsT> FORCEINLINE bool TUniquePtr< T, Deleter >::operator!= (const TUniquePtr< RhsT > & Rhs) const inline nodiscard
Inequality comparison operator.
Parameters
Lhs The first TUniquePtr to compare.
Rhs The second TUniquePtr to compare.
Returns
false if the two TUniquePtrs are logically substitutable for each other, true otherwise.
Definition at line 418 of file UniquePtr.h.
operator!=() [2/2]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE bool TUniquePtr< T, Deleter >::operator!= (TYPE_OF_NULLPTR) const inline nodiscard
Inequality comparison operator against nullptr.
Parameters
Rhs The TUniquePtr to compare.
Returns
true if the TUniquePtr is not null, false otherwise.
Definition at line 430 of file UniquePtr.h.
operator*()
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename DummyT = T UE_REQUIRES(UE_REQUIRES_EXPR(*(DummyT*)nullptr))> FORCEINLINE DummyT & TUniquePtr< T, Deleter >::operator* () const inline nodiscard
Dereference operator.
Returns
A reference to the object owned by the TUniquePtr.
Definition at line 314 of file UniquePtr.h.
operator->()
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE T * TUniquePtr< T, Deleter >::operator-> () const inline nodiscard
Indirection operator.
Returns
A pointer to the object owned by the TUniquePtr.
Definition at line 300 of file UniquePtr.h.
operator=() [1/4]
template<typename T, typename Deleter = TDefaultDelete<T>> TUniquePtr & TUniquePtr< T, Deleter >::operator= (const TUniquePtr< T, Deleter > &) delete
operator=() [2/4]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE TUniquePtr & TUniquePtr< T, Deleter >::operator= (TUniquePtr< T, Deleter > && Other) inline
Move assignment operator.
Definition at line 214 of file UniquePtr.h.
operator=() [3/4]
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename OtherT, typename OtherDeleter UE_REQUIRES> FORCEINLINE TUniquePtr & TUniquePtr< T, Deleter >::operator= (TUniquePtr< OtherT, OtherDeleter > && Other) inline
Assignment operator for rvalues of other (usually derived) types.
Definition at line 241 of file UniquePtr.h.
operator=() [4/4]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE TUniquePtr & TUniquePtr< T, Deleter >::operator= (TYPE_OF_NULLPTR) inline
Nullptr assignment operator.
Definition at line 257 of file UniquePtr.h.
operator==() [1/2]
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename RhsT> FORCEINLINE bool TUniquePtr< T, Deleter >::operator== (const TUniquePtr< RhsT > & Rhs) const inline nodiscard
Equality comparison operator.
Parameters
Lhs The first TUniquePtr to compare.
Rhs The second TUniquePtr to compare.
Returns
true if the two TUniquePtrs are logically substitutable for each other, false otherwise.
Definition at line 391 of file UniquePtr.h.
operator==() [2/2]
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE bool TUniquePtr< T, Deleter >::operator== (TYPE_OF_NULLPTR) const inline nodiscard
Equality comparison operator against nullptr.
Parameters
Lhs The TUniquePtr to compare.
Returns
true if the TUniquePtr is null, false otherwise.
Definition at line 403 of file UniquePtr.h.
Release()
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE T * TUniquePtr< T, Deleter >::Release () inline nodiscard
Relinquishes control of the owned object to the caller and nulls the TUniquePtr.
Returns
The pointer to the object that was owned by the TUniquePtr, or nullptr if no object was being owned.
Definition at line 334 of file UniquePtr.h.
Referenced by Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs(), and UE::FGenericPlatformIoDispatcher::OpenFile().
Reset()
template<typename T, typename Deleter = TDefaultDelete<T>> FORCEINLINE void TUniquePtr< T, Deleter >::Reset (T * InPtr = nullptr) inline
Gives the TUniquePtr a new object to own, destroying any previously-owned object.
Parameters
InPtr A pointer to the object to take ownership of.
Definition at line 346 of file UniquePtr.h.
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), and FScopedWidgetSlotArguments< FNodeSlot >::RemoveAt().
Friends And Related Symbol Documentation
TUniquePtr
template<typename T, typename Deleter = TDefaultDelete<T>> template<typename OtherT, typename OtherDeleter> friend class TUniquePtr friend
Definition at line 111 of file UniquePtr.h.
The documentation for this class was generated from the following file:
UniquePtr.h