Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitInterfaceUID Struct Reference
UE::AnimNext::FTraitInterfaceUID Struct Reference final
FTraitInterfaceUID.
#include "TraitInterfaceUID.h"
Public Member Functions
constexpr FTraitInterfaceUID ()
constexpr FTraitInterfaceUID (FTraitInterfaceUIDRaw InUID)
constexpr const TCHAR * GetInterfaceName () const
constexpr FTraitInterfaceUIDRaw GetUID () const
constexpr bool IsValid () const
Static Public Member Functions
template<typename CharType, int32 Len>
static UE_CONSTEVAL FTraitInterfaceUID MakeUID (const CharType(&InInterfaceName)[Len]) noexcept
Private Member Functions
constexpr FTraitInterfaceUID (FTraitInterfaceUIDRaw InUID, const TCHAR *InInterfaceName) noexcept
Private Attributes
const TCHAR * InterfaceName = nullptr
FTraitInterfaceUIDRaw UID
Static Private Attributes
static constexpr FTraitInterfaceUIDRaw INVALID_UID = 0
Detailed Description
FTraitInterfaceUID.
Encapsulates an interface global UID.
The whole struct is meant to be 'constexpr' to allow inlining within the assembly as constants.
Definition at line 20 of file TraitInterfaceUID.h.
Constructor & Destructor Documentation
FTraitInterfaceUID() [1/3]
UE::AnimNext::FTraitInterfaceUID::FTraitInterfaceUID () inline constexpr
Definition at line 23 of file TraitInterfaceUID.h.
References InterfaceName, INVALID_UID, TEXT, and UID.
Referenced by MakeUID().
FTraitInterfaceUID() [2/3]
UE::AnimNext::FTraitInterfaceUID::FTraitInterfaceUID (FTraitInterfaceUIDRaw InUID) inline explicit constexpr
Definition at line 31 of file TraitInterfaceUID.h.
References InterfaceName, TEXT, and UID.
FTraitInterfaceUID() [3/3]
UE::AnimNext::FTraitInterfaceUID::FTraitInterfaceUID (FTraitInterfaceUIDRaw InUID, const TCHAR * InInterfaceName) inline explicit constexpr private noexcept
Definition at line 61 of file TraitInterfaceUID.h.
Member Function Documentation
GetInterfaceName()
const TCHAR * UE::AnimNext::FTraitInterfaceUID::GetInterfaceName () const inline constexpr
Definition at line 48 of file TraitInterfaceUID.h.
References InterfaceName.
GetUID()
FTraitInterfaceUIDRaw UE::AnimNext::FTraitInterfaceUID::GetUID () const inline constexpr
Definition at line 52 of file TraitInterfaceUID.h.
References UID.
Referenced by UE::AnimNext::operator!=(), UE::AnimNext::operator<(), and UE::AnimNext::operator==().
IsValid()
bool UE::AnimNext::FTraitInterfaceUID::IsValid () const inline constexpr
Definition at line 55 of file TraitInterfaceUID.h.
References INVALID_UID, and UID.
MakeUID()
template<typename CharType, int32 Len> UE_CONSTEVAL FTraitInterfaceUID UE::AnimNext::FTraitInterfaceUID::MakeUID (const CharType(&) InInterfaceName[Len]) inline static noexcept
Definition at line 41 of file TraitInterfaceUID.h.
References FTraitInterfaceUID(), UE::HashStringFNV1a(), MakeStringView(), and UE_CONSTEVAL.
Field Documentation
InterfaceName
const TCHAR* UE::AnimNext::FTraitInterfaceUID::InterfaceName = nullptr private
Definition at line 72 of file TraitInterfaceUID.h.
Referenced by FTraitInterfaceUID(), FTraitInterfaceUID(), and GetInterfaceName().
INVALID_UID
FTraitInterfaceUIDRaw UE::AnimNext::FTraitInterfaceUID::INVALID_UID = 0 static constexpr private
Definition at line 58 of file TraitInterfaceUID.h.
Referenced by FTraitInterfaceUID(), and IsValid().
UID
FTraitInterfaceUIDRaw UE::AnimNext::FTraitInterfaceUID::UID private
Definition at line 69 of file TraitInterfaceUID.h.
Referenced by FTraitInterfaceUID(), FTraitInterfaceUID(), GetUID(), and IsValid().
The documentation for this struct was generated from the following file:
TraitInterfaceUID.h