Unreal Engine 5.6 C++ API: FNavigationDirtyElement Struct Reference
FNavigationDirtyElement Struct Reference
#include "NavigationDirtyElement.h"
Public Member Functions
FNavigationDirtyElement (const FNavigationDirtyElement &Other)
FNavigationDirtyElement (const TSharedRef< const FNavigationElement > &InNavigationElement, const bool bUseWorldPartitionedDynamicMode=false)
FNavigationDirtyElement (const TSharedRef< const FNavigationElement > &InNavigationElement, ENavigationDirtyFlag InFlagsOverride, const bool bUseWorldPartitionedDynamicMode=false)
FNavigationDirtyElement & operator= (const FNavigationDirtyElement &Other)
UE_DEPRECATED (5.5, "The default constructor will be remove. Use the version with FNavigationElement instead.") 1 FNavigationDirtyElement()
UE_DEPRECATED (5.5, "This operator will no longer be used.") 1 bool operator
UE_DEPRECATED (5.5, "Use the version with FNavigationElement instead.") 1 explicit FNavigationDirtyElement(UObject *InOwner)
UE_DEPRECATED (5.5, "Use the version with FNavigationElement instead.") 1 FNavigationDirtyElement(UObject *InOwner
Data Fields
uint8 bHasPrevData: 1 = false
prev flags & bounds data are set
uint8 bInvalidRequest: 1 = false
request was invalidated while queued, use prev values to dirty area
uint8 bIsFromVisibilityChange: 1 = false
requested during visibility change of the owning level (loading/unloading)
uint8 bIsInBaseNavmesh: 1 = false
part of the base navmesh
INavRelevantInterface int32 const bool bUseWorldPartitionedDynamicMode = false)
TArray< FBox > ExplicitAreasToDirty
If not empty and the associated navigation element controls the dirty areas explicitly (i.e.
ENavigationDirtyFlag FlagsOverride
override for update flags
INavRelevantInterface int32 InFlagsOverride = 0
INavRelevantInterface * InNavInterface
TSharedRef< const FNavigationElement > NavigationElement
Navigation element associated with this dirty element.
FBox PrevBounds = FBox(ForceInit)
bounds of already existing entry for this actor
ENavigationDirtyFlag PrevFlags
flags of already existing entry for this actor
Friends
uint32 GetTypeHash (const FNavigationDirtyElement &Info)
Detailed Description
Definition at line 12 of file NavigationDirtyElement.h.
Constructor & Destructor Documentation
FNavigationDirtyElement() [1/3]
FNavigationDirtyElement::FNavigationDirtyElement (const TSharedRef< const FNavigationElement > & InNavigationElement, ENavigationDirtyFlag InFlagsOverride, const bool bUseWorldPartitionedDynamicMode = false)
References FNavigationDirtyElement(), bUseWorldPartitionedDynamicMode, and InFlagsOverride.
Referenced by FNavigationDirtyElement(), FNavigationDirtyElement(), FNavigationDirtyElement(), GetTypeHash, operator=(), UE_DEPRECATED(), and UE_DEPRECATED().
FNavigationDirtyElement() [2/3]
FNavigationDirtyElement::FNavigationDirtyElement (const TSharedRef< const FNavigationElement > & InNavigationElement, const bool bUseWorldPartitionedDynamicMode = false) explicit
References FNavigationDirtyElement(), and bUseWorldPartitionedDynamicMode.
FNavigationDirtyElement() [3/3]
FNavigationDirtyElement::FNavigationDirtyElement (const FNavigationDirtyElement & Other)
References FNavigationDirtyElement(), and Other.
Member Function Documentation
operator=()
FNavigationDirtyElement & FNavigationDirtyElement::operator= (const FNavigationDirtyElement & Other)
References FNavigationDirtyElement(), and Other.
UE_DEPRECATED() [1/4]
FNavigationDirtyElement::UE_DEPRECATED (5. 5, "The default constructor will be remove. Use the version with FNavigationElement instead.")
References FNavigationDirtyElement().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FNavigationDirtyElement::UE_DEPRECATED (5. 5, "This operator will no longer be used.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FNavigationDirtyElement::UE_DEPRECATED (5. 5, "Use the version with FNavigationElement instead.")
References FNavigationDirtyElement(), and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
FNavigationDirtyElement::UE_DEPRECATED (5. 5, "Use the version with FNavigationElement instead.")
References UE_DEPRECATED().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FNavigationDirtyElement & Info) friend
References FNavigationDirtyElement(), GetTypeHash, and Info.
Referenced by GetTypeHash.
Field Documentation
bHasPrevData
uint8 FNavigationDirtyElement::bHasPrevData
prev flags & bounds data are set
Definition at line 42 of file NavigationDirtyElement.h.
bInvalidRequest
uint8 FNavigationDirtyElement::bInvalidRequest
request was invalidated while queued, use prev values to dirty area
Definition at line 45 of file NavigationDirtyElement.h.
bIsFromVisibilityChange
uint8 FNavigationDirtyElement::bIsFromVisibilityChange
requested during visibility change of the owning level (loading/unloading)
Definition at line 48 of file NavigationDirtyElement.h.
bIsInBaseNavmesh
uint8 FNavigationDirtyElement::bIsInBaseNavmesh
part of the base navmesh
Definition at line 51 of file NavigationDirtyElement.h.
bUseWorldPartitionedDynamicMode
INavRelevantInterface int32 const bool FNavigationDirtyElement::bUseWorldPartitionedDynamicMode = false)
Definition at line 58 of file NavigationDirtyElement.h.
Referenced by FNavigationDirtyElement(), and FNavigationDirtyElement().
ExplicitAreasToDirty
TArray<FBox> FNavigationDirtyElement::ExplicitAreasToDirty
If not empty and the associated navigation element controls the dirty areas explicitly (i.e.
DirtyAreasOnRegistration is 'false'), the list will be used to indicate the areas that need rebuilding. Otherwise, the default behavior, element's bounds will be used.
Definition at line 19 of file NavigationDirtyElement.h.
FlagsOverride
ENavigationDirtyFlag FNavigationDirtyElement::FlagsOverride
override for update flags
Definition at line 36 of file NavigationDirtyElement.h.
InFlagsOverride
INavRelevantInterface int32 FNavigationDirtyElement::InFlagsOverride = 0
Definition at line 58 of file NavigationDirtyElement.h.
Referenced by FNavigationDirtyElement().
InNavInterface
INavRelevantInterface* FNavigationDirtyElement::InNavInterface
Definition at line 58 of file NavigationDirtyElement.h.
NavigationElement
TSharedRef<const FNavigationElement> FNavigationDirtyElement::NavigationElement
Navigation element associated with this dirty element.
Definition at line 22 of file NavigationDirtyElement.h.
PrevBounds
FBox FNavigationDirtyElement::PrevBounds = FBox(ForceInit)
bounds of already existing entry for this actor
Definition at line 33 of file NavigationDirtyElement.h.
PrevFlags
ENavigationDirtyFlag FNavigationDirtyElement::PrevFlags
flags of already existing entry for this actor
Definition at line 39 of file NavigationDirtyElement.h.
The documentation for this struct was generated from the following file:
NavigationDirtyElement.h