Unreal Engine 5.6 C++ API: TContainerElementTypeCompatibility< const TObjectPtr< T > > Struct Template Reference
TContainerElementTypeCompatibility< const TObjectPtr< T > > Struct Template Reference
#include "ObjectPtr.h"
Public Types
typedef T *const CopyFromOtherType
typedef T *const ReinterpretType
Static Public Member Functions
static constexpr void CopyingFromOtherType ()
template<typename IterBeginType, typename IterEndType, typename OperatorType = const std::remove_cv_t<std::remove_reference_t<decltype(*std::declval<IterBeginType>())>, &>
static void ReinterpretRange (IterBeginType Iter, IterEndType IterEnd, OperatorType Operator=TContainerElementTypeCompatibility_DefaultOperatorFunc)
template<typename IterBeginType, typename IterEndType, typename SizeType, typename OperatorType = std::remove_reference_t<decltype(*std::declval<IterBeginType>())>& (*)(IterBeginType&)>
static void ReinterpretRangeContiguous (IterBeginType Iter, IterEndType IterEnd, SizeType Size, OperatorType Operator=TContainerElementTypeCompatibility_DefaultOperatorFunc)
Detailed Description
template<typename T>
struct TContainerElementTypeCompatibility< const TObjectPtr< T > >
Definition at line 1148 of file ObjectPtr.h.
Member Typedef Documentation
CopyFromOtherType
template<typename T> typedef T* const TContainerElementTypeCompatibility< const TObjectPtr< T > >::CopyFromOtherType
Definition at line 1151 of file ObjectPtr.h.
ReinterpretType
template<typename T> typedef T* const TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretType
Definition at line 1150 of file ObjectPtr.h.
Member Function Documentation
CopyingFromOtherType()
template<typename T> constexpr void TContainerElementTypeCompatibility< const TObjectPtr< T > >::CopyingFromOtherType () inline static constexpr
Definition at line 1187 of file ObjectPtr.h.
References CopyingFromOtherType().
Referenced by CopyingFromOtherType().
ReinterpretRange()
template<typename T> template<typename IterBeginType, typename IterEndType, typename OperatorType = const std::remove_cv_t<std::remove_reference_t<decltype(*std::declval<IterBeginType>())>, &> void TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRange (IterBeginType Iter, IterEndType IterEnd, OperatorType Operator = TContainerElementTypeCompatibility_DefaultOperatorFunc) inline static
Definition at line 1155 of file ObjectPtr.h.
References check, and TContainerElementTypeCompatibility_DefaultOperatorFunc.
ReinterpretRangeContiguous()
template<typename T> template<typename IterBeginType, typename IterEndType, typename SizeType, typename OperatorType = std::remove_reference_t<decltype(*std::declval<IterBeginType>())>& (*)(IterBeginType&)> void TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRangeContiguous (IterBeginType Iter, IterEndType IterEnd, SizeType Size, OperatorType Operator = TContainerElementTypeCompatibility_DefaultOperatorFunc) inline static
Definition at line 1169 of file ObjectPtr.h.
References check, FObjectPtr::GetHandleRef(), FObjectPtr::IsResolved(), UE::CoreUObject::Private::OnHandleRead(), UE::CoreUObject::Private::ResolveObjectHandleNoRead(), TContainerElementTypeCompatibility_DefaultOperatorFunc, and TSequenceHistory< HistorySize >::Size.
The documentation for this struct was generated from the following file:
ObjectPtr.h