Unreal Engine 5.6 C++ API: FIoDispatcher Class Reference
FIoDispatcher Class Reference final
I/O dispatcher.
#include "IoDispatcher.h"
Public Member Functions
FIoDispatcher ()
FIoDispatcher (const FIoDispatcher &)=default
~FIoDispatcher ()
DECLARE_EVENT_OneParam (FIoDispatcher, FIoContainerMountedEvent, const FIoDispatcherMountedContainer &)
DECLARE_EVENT_OneParam (FIoDispatcher, FIoContainerUnmountedEvent, const FIoDispatcherMountedContainer &)
bool DoesChunkExist (const FIoChunkId &ChunkId) const
TIoStatusOr< uint64 > GetSizeForChunk (const FIoChunkId &ChunkId) const
int64 GetTotalLoaded () const
void Mount (TSharedRef< IIoDispatcherBackend > Backend, int32 Priority=0)
FIoBatch NewBatch ()
FIoSignatureErrorDelegate & OnSignatureError ()
TIoStatusOr< FIoMappedRegion > OpenMapped (const FIoChunkId &ChunkId, const FIoReadOptions &Options)
FIoDispatcher & operator= (const FIoDispatcher &)=delete
Static Public Member Functions
static FIoDispatcher & Get ()
static FIoStatus Initialize ()
static void InitializePostSettings ()
static bool IsInitialized ()
static void Shutdown ()
Private Member Functions
bool DoesChunkExist (const FIoChunkId &ChunkId, const FIoOffsetAndLength &ChunkRange) const
TIoStatusOr< uint64 > GetSizeForChunk (const FIoChunkId &ChunkId, const FIoOffsetAndLength &ChunkRange, uint64 &OutAvailable) const
Private Attributes
FIoDispatcherImpl * Impl = nullptr
Friends
class FBulkData
class FIoBatch
class FIoQueue
class FIoRequest
Detailed Description
I/O dispatcher.
Definition at line 349 of file IoDispatcher.h.
Constructor & Destructor Documentation
FIoDispatcher() [1/2]
FIoDispatcher::FIoDispatcher ()
Referenced by FIoDispatcher(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), Get(), and operator=().
~FIoDispatcher()
FIoDispatcher::~FIoDispatcher ()
FIoDispatcher() [2/2]
FIoDispatcher::FIoDispatcher (const FIoDispatcher &) default
References FIoDispatcher().
Member Function Documentation
DECLARE_EVENT_OneParam() [1/2]
FIoDispatcher::DECLARE_EVENT_OneParam (FIoDispatcher , FIoContainerMountedEvent , const FIoDispatcherMountedContainer &)
References FIoDispatcher().
DECLARE_EVENT_OneParam() [2/2]
FIoDispatcher::DECLARE_EVENT_OneParam (FIoDispatcher , FIoContainerUnmountedEvent , const FIoDispatcherMountedContainer &)
References FIoDispatcher().
DoesChunkExist() [1/2]
bool FIoDispatcher::DoesChunkExist (const FIoChunkId & ChunkId) const
Referenced by FIoDispatcherInternal::HasPackageData().
DoesChunkExist() [2/2]
bool FIoDispatcher::DoesChunkExist (const FIoChunkId & ChunkId, const FIoOffsetAndLength & ChunkRange) const private
Get()
FIoDispatcher & FIoDispatcher::Get () static
References FIoDispatcher().
Referenced by FIoDispatcherInternal::HasPackageData().
GetSizeForChunk() [1/2]
TIoStatusOr< uint64 > FIoDispatcher::GetSizeForChunk (const FIoChunkId & ChunkId) const
GetSizeForChunk() [2/2]
TIoStatusOr< uint64 > FIoDispatcher::GetSizeForChunk (const FIoChunkId & ChunkId, const FIoOffsetAndLength & ChunkRange, uint64 & OutAvailable) const private
GetTotalLoaded()
int64 FIoDispatcher::GetTotalLoaded () const
Initialize()
FIoStatus FIoDispatcher::Initialize () static
InitializePostSettings()
void FIoDispatcher::InitializePostSettings () static
IsInitialized()
bool FIoDispatcher::IsInitialized () static
Mount()
void FIoDispatcher::Mount (TSharedRef< IIoDispatcherBackend > Backend, int32 Priority = 0)
NewBatch()
FIoBatch FIoDispatcher::NewBatch ()
References FIoBatch.
OnSignatureError()
FIoSignatureErrorDelegate & FIoDispatcher::OnSignatureError ()
OpenMapped()
TIoStatusOr< FIoMappedRegion > FIoDispatcher::OpenMapped (const FIoChunkId & ChunkId, const FIoReadOptions & Options)
operator=()
FIoDispatcher & FIoDispatcher::operator= (const FIoDispatcher &) delete
References FIoDispatcher().
Shutdown()
void FIoDispatcher::Shutdown () static
Friends And Related Symbol Documentation
FBulkData
friend class FBulkData friend
Definition at line 391 of file IoDispatcher.h.
References FBulkData.
Referenced by FBulkData.
FIoBatch
friend class FIoBatch friend
Definition at line 389 of file IoDispatcher.h.
References FIoBatch.
Referenced by FIoBatch, and NewBatch().
FIoQueue
friend class FIoQueue friend
Definition at line 390 of file IoDispatcher.h.
References FIoQueue.
Referenced by FIoQueue.
FIoRequest
friend class FIoRequest friend
Definition at line 388 of file IoDispatcher.h.
References FIoRequest.
Referenced by FIoRequest.
Field Documentation
Impl
FIoDispatcherImpl* FIoDispatcher::Impl = nullptr private
Definition at line 386 of file IoDispatcher.h.
The documentation for this class was generated from the following file:
IoDispatcher.h