Unreal Engine 5.6 C++ API: ILevelInstanceInterface Class Reference
ILevelInstanceInterface Class Reference abstract
Interface to be implemented by Actor classes to implement support for LevelInstances.
#include "LevelInstanceInterface.h"
Private Member Functions
virtual void AdjustPivotOnCreation ()
virtual bool CanEnterEdit (FText *OutReason=nullptr) const
bool CanEnterEditPropertyOverrides (FText *OutReason=nullptr) const
virtual bool CanExitEdit (bool bDiscardEdits=false, FText *OutReason=nullptr) const
bool CanExitEditPropertyOverrides (bool bDiscardEdits=false, FText *OutReason=nullptr) const
virtual bool EnterEdit (AActor *ContextActor=nullptr)
bool EnterEditPropertyOverrides (AActor *ContextActor=nullptr)
virtual bool ExitEdit (bool bDiscardEdits=false)
bool ExitEditPropertyOverrides (bool bDiscardEdits=false)
GENERATED_IINTERFACE_BODY () virtual const FLevelInstanceID &GetLevelInstanceID() const =0
virtual ELevelInstanceRuntimeBehavior GetDefaultRuntimeBehavior () const =0
virtual ELevelInstanceRuntimeBehavior GetDesiredRuntimeBehavior () const =0
virtual EWorldPartitionActorFilterType GetDetailsFilterTypes () const
virtual TSubclassOf< AActor > GetEditorPivotClass () const
virtual const FWorldPartitionActorFilter & GetFilter () const
virtual const TMap< FActorContainerID, TSet< FGuid > > & GetFilteredActorsPerContainer () const
virtual ULevelInstanceComponent * GetLevelInstanceComponent () const =0
virtual const FGuid & GetLevelInstanceGuid () const =0
virtual ULevelInstanceSubsystem * GetLevelInstanceSubsystem () const
virtual ULevelStreamingLevelInstance * GetLevelStreaming () const
virtual TSubclassOf< ULevelStreamingLevelInstance > GetLevelStreamingClass () const
virtual EWorldPartitionActorFilterType GetLoadingFilterTypes () const
virtual ULevelInstancePropertyOverrideAsset * GetPropertyOverrideAsset () const
FString GetWorldAssetPackage () const
virtual bool HasChildEdit () const
virtual bool HasDirtyChildren () const
virtual bool HasParentEdit () const
virtual bool HasValidLevelInstanceID () const =0
virtual bool IsDirty () const
virtual bool IsEditing () const
bool IsEditingPropertyOverrides () const
bool IsInAnyEditMode () const
virtual bool IsInitiallyVisible () const
virtual bool IsLevelInstanceHLODRelevant () const
virtual bool IsLoadingEnabled () const =0
bool IsWorldAssetValid () const
virtual bool MoveActorsTo (const TArray< AActor * > &ActorsToMove)
virtual void OnCommit (bool bChanged)
virtual void OnCommitChild (bool bChanged)
virtual void OnCommitPropertyOverrides (bool bChanged)
virtual void OnEdit ()
virtual void OnEditChild ()
virtual void OnEditPropertyOverrides ()
virtual void OnFilterChanged ()
virtual void OnLevelInstanceLoaded ()
virtual bool SetCurrent ()
virtual void SetFilter (const FWorldPartitionActorFilter &InFilter, bool bNotify=true)
virtual void SetPropertyOverrideAsset (ULevelInstancePropertyOverrideAsset *InPropertyOverride)
virtual bool SupportsPartialEditorLoading () const
virtual bool SupportsPropertyOverrides () const
UFUNCTION () 1 virtual bool IsLoaded() const
UFUNCTION () 1 virtual ULevel *GetLoadedLevel() const
UFUNCTION () 1 virtual void LoadLevelInstance()
UFUNCTION () 1 virtual void UnloadLevelInstance()
UFUNCTION () virtual bool SetWorldAsset(TSoftObjectPtr< UWorld > WorldAsset)
Sets the UWorld asset reference when loading a LevelInstance.
UFUNCTION () virtual const TSoftObjectPtr< UWorld > &GetWorldAsset() const =0
virtual void UpdateLevelInstanceFromWorldAsset ()
Friends
class ULevelInstanceSubsystem
Detailed Description
Interface to be implemented by Actor classes to implement support for LevelInstances.
Interface exists to allow integration of the LevelInstance workflow on existing Actor class hierarchies.
See also
FLevelInstanceActorImpl to use as a member or base class member of the implementing class. It provides most of the boiler plate code so that the implementing class behaves properly in editor (Undo/Redo/Delete/Selection/Imporrt/etc)
Definition at line 32 of file LevelInstanceInterface.h.
Member Function Documentation
AdjustPivotOnCreation()
virtual void ILevelInstanceInterface::AdjustPivotOnCreation () inline private virtual
Definition at line 62 of file LevelInstanceInterface.h.
CanEnterEdit()
virtual bool ILevelInstanceInterface::CanEnterEdit (FText * OutReason = nullptr) const private virtual
CanEnterEditPropertyOverrides()
bool ILevelInstanceInterface::CanEnterEditPropertyOverrides (FText * OutReason = nullptr) const private
CanExitEdit()
virtual bool ILevelInstanceInterface::CanExitEdit (bool bDiscardEdits = false, FText * OutReason = nullptr) const private virtual
CanExitEditPropertyOverrides()
bool ILevelInstanceInterface::CanExitEditPropertyOverrides (bool bDiscardEdits = false, FText * OutReason = nullptr) const private
EnterEdit()
virtual bool ILevelInstanceInterface::EnterEdit (AActor * ContextActor = nullptr) private virtual
EnterEditPropertyOverrides()
bool ILevelInstanceInterface::EnterEditPropertyOverrides (AActor * ContextActor = nullptr) private
ExitEdit()
virtual bool ILevelInstanceInterface::ExitEdit (bool bDiscardEdits = false) private virtual
ExitEditPropertyOverrides()
bool ILevelInstanceInterface::ExitEditPropertyOverrides (bool bDiscardEdits = false) private
GENERATED_IINTERFACE_BODY()
ILevelInstanceInterface::GENERATED_IINTERFACE_BODY () const & private pure virtual
GetDefaultRuntimeBehavior()
virtual ELevelInstanceRuntimeBehavior ILevelInstanceInterface::GetDefaultRuntimeBehavior () const private pure virtual
GetDesiredRuntimeBehavior()
virtual ELevelInstanceRuntimeBehavior ILevelInstanceInterface::GetDesiredRuntimeBehavior () const private pure virtual
GetDetailsFilterTypes()
virtual EWorldPartitionActorFilterType ILevelInstanceInterface::GetDetailsFilterTypes () const private virtual
GetEditorPivotClass()
virtual TSubclassOf< AActor > ILevelInstanceInterface::GetEditorPivotClass () const inline private virtual
Definition at line 60 of file LevelInstanceInterface.h.
GetFilter()
virtual const FWorldPartitionActorFilter & ILevelInstanceInterface::GetFilter () const private virtual
GetFilteredActorsPerContainer()
virtual const TMap< FActorContainerID, TSet< FGuid > > & ILevelInstanceInterface::GetFilteredActorsPerContainer () const private virtual
GetLevelInstanceComponent()
virtual ULevelInstanceComponent * ILevelInstanceInterface::GetLevelInstanceComponent () const private pure virtual
GetLevelInstanceGuid()
virtual const FGuid & ILevelInstanceInterface::GetLevelInstanceGuid () const private pure virtual
References GetLevelInstanceGuid().
Referenced by GetLevelInstanceGuid().
GetLevelInstanceSubsystem()
virtual ULevelInstanceSubsystem * ILevelInstanceInterface::GetLevelInstanceSubsystem () const private virtual
References ULevelInstanceSubsystem.
GetLevelStreaming()
virtual ULevelStreamingLevelInstance * ILevelInstanceInterface::GetLevelStreaming () const private virtual
GetLevelStreamingClass()
virtual TSubclassOf< ULevelStreamingLevelInstance > ILevelInstanceInterface::GetLevelStreamingClass () const private virtual
GetLoadingFilterTypes()
virtual EWorldPartitionActorFilterType ILevelInstanceInterface::GetLoadingFilterTypes () const private virtual
GetPropertyOverrideAsset()
virtual ULevelInstancePropertyOverrideAsset * ILevelInstanceInterface::GetPropertyOverrideAsset () const inline private virtual
Definition at line 52 of file LevelInstanceInterface.h.
GetWorldAssetPackage()
FString ILevelInstanceInterface::GetWorldAssetPackage () const inline private
Definition at line 70 of file LevelInstanceInterface.h.
HasChildEdit()
virtual bool ILevelInstanceInterface::HasChildEdit () const private virtual
HasDirtyChildren()
virtual bool ILevelInstanceInterface::HasDirtyChildren () const private virtual
HasParentEdit()
virtual bool ILevelInstanceInterface::HasParentEdit () const private virtual
HasValidLevelInstanceID()
virtual bool ILevelInstanceInterface::HasValidLevelInstanceID () const private pure virtual
References HasValidLevelInstanceID().
Referenced by HasValidLevelInstanceID().
IsDirty()
virtual bool ILevelInstanceInterface::IsDirty () const private virtual
IsEditing()
virtual bool ILevelInstanceInterface::IsEditing () const private virtual
Referenced by IsInAnyEditMode().
IsEditingPropertyOverrides()
bool ILevelInstanceInterface::IsEditingPropertyOverrides () const private
Referenced by IsInAnyEditMode().
IsInAnyEditMode()
bool ILevelInstanceInterface::IsInAnyEditMode () const inline private
Definition at line 105 of file LevelInstanceInterface.h.
References IsEditing(), and IsEditingPropertyOverrides().
IsInitiallyVisible()
virtual bool ILevelInstanceInterface::IsInitiallyVisible () const inline private virtual
Definition at line 85 of file LevelInstanceInterface.h.
IsLevelInstanceHLODRelevant()
virtual bool ILevelInstanceInterface::IsLevelInstanceHLODRelevant () const private virtual
IsLoadingEnabled()
virtual bool ILevelInstanceInterface::IsLoadingEnabled () const private pure virtual
References IsLoadingEnabled().
Referenced by IsLoadingEnabled().
IsWorldAssetValid()
bool ILevelInstanceInterface::IsWorldAssetValid () const inline private
Definition at line 72 of file LevelInstanceInterface.h.
MoveActorsTo()
virtual bool ILevelInstanceInterface::MoveActorsTo (const TArray< AActor * > & ActorsToMove) private virtual
OnCommit()
virtual void ILevelInstanceInterface::OnCommit (bool bChanged) private virtual
OnCommitChild()
virtual void ILevelInstanceInterface::OnCommitChild (bool bChanged) inline private virtual
Definition at line 103 of file LevelInstanceInterface.h.
OnCommitPropertyOverrides()
virtual void ILevelInstanceInterface::OnCommitPropertyOverrides (bool bChanged) private virtual
OnEdit()
virtual void ILevelInstanceInterface::OnEdit () private virtual
OnEditChild()
virtual void ILevelInstanceInterface::OnEditChild () inline private virtual
Definition at line 98 of file LevelInstanceInterface.h.
OnEditPropertyOverrides()
virtual void ILevelInstanceInterface::OnEditPropertyOverrides () private virtual
OnFilterChanged()
virtual void ILevelInstanceInterface::OnFilterChanged () inline private virtual
Definition at line 145 of file LevelInstanceInterface.h.
OnLevelInstanceLoaded()
virtual void ILevelInstanceInterface::OnLevelInstanceLoaded () inline private virtual
Definition at line 68 of file LevelInstanceInterface.h.
SetCurrent()
virtual bool ILevelInstanceInterface::SetCurrent () private virtual
SetFilter()
virtual void ILevelInstanceInterface::SetFilter (const FWorldPartitionActorFilter & InFilter, bool bNotify = true) private virtual
SetPropertyOverrideAsset()
virtual void ILevelInstanceInterface::SetPropertyOverrideAsset (ULevelInstancePropertyOverrideAsset * InPropertyOverride) inline private virtual
Definition at line 169 of file LevelInstanceInterface.h.
SupportsPartialEditorLoading()
virtual bool ILevelInstanceInterface::SupportsPartialEditorLoading () const private virtual
SupportsPropertyOverrides()
virtual bool ILevelInstanceInterface::SupportsPropertyOverrides () const inline private virtual
Definition at line 50 of file LevelInstanceInterface.h.
UFUNCTION() [1/6]
ILevelInstanceInterface::UFUNCTION () const private
References Category, and Default.
UFUNCTION() [2/6]
ILevelInstanceInterface::UFUNCTION () const private
References Category, and Default.
UFUNCTION() [3/6]
ILevelInstanceInterface::UFUNCTION () private
References Category, and Default.
UFUNCTION() [4/6]
ILevelInstanceInterface::UFUNCTION () private
References Category, and Default.
UFUNCTION() [5/6]
ILevelInstanceInterface::UFUNCTION () inline private
Sets the UWorld asset reference when loading a LevelInstance.
Definition at line 158 of file LevelInstanceInterface.h.
References Category, and Default.
UFUNCTION() [6/6]
ILevelInstanceInterface::UFUNCTION () const & private pure virtual
References Category, Default, and UFUNCTION().
Referenced by UFUNCTION().
UpdateLevelInstanceFromWorldAsset()
virtual void ILevelInstanceInterface::UpdateLevelInstanceFromWorldAsset () private virtual
Friends And Related Symbol Documentation
ULevelInstanceSubsystem
friend class ULevelInstanceSubsystem friend
Definition at line 168 of file LevelInstanceInterface.h.
References ULevelInstanceSubsystem.
Referenced by GetLevelInstanceSubsystem(), and ULevelInstanceSubsystem.
The documentation for this class was generated from the following file:
LevelInstanceInterface.h