Unreal Engine 5.6 C++ API: FWorldDataLayersReference Class Reference
FWorldDataLayersReference Class Reference
#include "WorldDataLayerReference.h"
Public Member Functions
FWorldDataLayersReference ()
FWorldDataLayersReference (const FActorSpawnParameters &SpawnParameters)
FWorldDataLayersReference (FWorldDataLayersReference &&Other)
~FWorldDataLayersReference ()
AWorldDataLayers * Get ()
const AWorldDataLayers * Get () const
bool IsValid () const
AWorldDataLayers * operator-> ()
const AWorldDataLayers * operator-> () const
FWorldDataLayersReference & operator= (FWorldDataLayersReference &&Other)
void Reset ()
UE_DEPRECATED (5.4, "Use UActorDescContainerInstance version instead") FWorldDataLayersReference(UActorDescContainer *Container
Data Fields
FName WorldDataLayerName
Private Member Functions
bool TrySetReference (UActorDescContainerInstance *ContainerInstance, FName WorldDataLayerName)
Private Attributes
TVariant< AWorldDataLayers *, FWorldPartitionReference > WorldDataLayersVariant
Detailed Description
Definition at line 12 of file WorldDataLayerReference.h.
Constructor & Destructor Documentation
FWorldDataLayersReference() [1/3]
FWorldDataLayersReference::FWorldDataLayersReference ()
Referenced by FWorldDataLayersReference(), Get(), operator->(), and operator=().
FWorldDataLayersReference() [2/3]
FWorldDataLayersReference::FWorldDataLayersReference (const FActorSpawnParameters & SpawnParameters)
FWorldDataLayersReference() [3/3]
FWorldDataLayersReference::FWorldDataLayersReference (FWorldDataLayersReference && Other)
References FWorldDataLayersReference(), and Other.
~FWorldDataLayersReference()
FWorldDataLayersReference::~FWorldDataLayersReference ()
Member Function Documentation
Get() [1/2]
AWorldDataLayers * FWorldDataLayersReference::Get () inline
Definition at line 31 of file WorldDataLayerReference.h.
References FWorldDataLayersReference().
Get() [2/2]
const AWorldDataLayers * FWorldDataLayersReference::Get () const
Referenced by IsValid(), and operator->().
IsValid()
bool FWorldDataLayersReference::IsValid () const inline
Definition at line 25 of file WorldDataLayerReference.h.
References Get().
operator->() [1/2]
AWorldDataLayers * FWorldDataLayersReference::operator-> () inline
Definition at line 27 of file WorldDataLayerReference.h.
References FWorldDataLayersReference().
operator->() [2/2]
const AWorldDataLayers * FWorldDataLayersReference::operator-> () const inline
Definition at line 28 of file WorldDataLayerReference.h.
References Get().
operator=()
FWorldDataLayersReference & FWorldDataLayersReference::operator= (FWorldDataLayersReference && Other)
References FWorldDataLayersReference(), and Other.
Reset()
void FWorldDataLayersReference::Reset ()
TrySetReference()
bool FWorldDataLayersReference::TrySetReference (UActorDescContainerInstance * ContainerInstance, FName WorldDataLayerName) private
References WorldDataLayerName.
UE_DEPRECATED()
FWorldDataLayersReference::UE_DEPRECATED (5. 4, "Use UActorDescContainerInstance version instead")
Field Documentation
WorldDataLayerName
FName FWorldDataLayersReference::WorldDataLayerName
Initial value:
{}
    1 FWorldDataLayersReference(UActorDescContainerInstance* ContainerInstance, FName WorldDataLayerName)
Definition at line 18 of file WorldDataLayerReference.h.
Referenced by TrySetReference().
WorldDataLayersVariant
TVariant<AWorldDataLayers*, FWorldPartitionReference> FWorldDataLayersReference::WorldDataLayersVariant private
Definition at line 40 of file WorldDataLayerReference.h.
The documentation for this class was generated from the following file:
WorldDataLayerReference.h