Unreal Engine 5.6 C++ API: SComboBox< OptionType > Class Template Reference
SComboBox< OptionType > Class Template Reference
A combo box that shows arbitrary content.
#include "SComboBox.h"
Public Types
typedef TSlateDelegates< OptionType >::FOnGenerateWidget FOnGenerateWidget
Delegate type used to generate widgets that represent Options.
typedef TSlateDelegates< NullableOptionType >::FOnSelectionChanged FOnSelectionChanged
typedef TListTypeTraits< OptionType > ListTypeTraits
typedef TListTypeTraits< OptionType >::NullableType NullableOptionType
typedef SListView< OptionType > SComboListType
Type of list used for showing menu options.
Public Member Functions
SComboBox ()
void ClearItemsSource ()
Clears current item source.
void ClearSelection ()
NullableOptionType GetSelectedItem ()
void InvalidateItemStyle ()
void InvalidateStyle ()
void RefreshOptions ()
Requests a list refresh after updating options Call SetSelectedItem to update the selected item if required.
void SetEnableGamepadNavigationMode (bool InEnableGamepadNavigationMode)
void SetItemsSource (const TArray< OptionType > *InListItemsSource)
Sets new item source.
void SetItemsSource (TSharedRef<::UE::Slate::Containers::TObservableArray< OptionType > > InListItemsSource)
Sets new item source.
void SetItemStyle (const FTableRowStyle *InItemStyle)
void SetMaxHeight (float InMaxHeight)
void SetSelectedItem (NullableOptionType InSelectedItem)
void SetStyle (const FComboBoxStyle *InStyle)
ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method PressedSoundOverride HasDownArrow IsFocusable SLATE_ARGUMENT (bool, CollapseMenuOnParentFocus) SLATE_END_ARGS() void Construct(const FArguments &InArgs)
True if this combo's menu should be collapsed when our parent receives focus, false (default) otherwise.
ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method PressedSoundOverride HasDownArrow SLATE_ARGUMENT (bool, EnableGamepadNavigationMode) SLATE_ARGUMENT(bool
When false, directional keys will change the selection.
ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method SLATE_ARGUMENT (float, MaxListHeight) SLATE_ARGUMENT(TOptional< FSlateSound >
The max height of the combo box menu.
ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar SLATE_ARGUMENT (NullableOptionType, InitiallySelectedItem) SLATE_ARGUMENT(TOptional< EPopupMethod >
The option that should be selected when the combo box is first created.
ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method PressedSoundOverride SLATE_ARGUMENT (TOptional< FSlateSound >, SelectionChangeSoundOverride) SLATE_ARGUMENT(bool
The sound to play when the selection changes (overrides ComboBoxStyle)
ComboBoxStyle ItemStyle ContentPadding SLATE_ATTRIBUTE (FSlateColor, ForegroundColor) SLATE_ITEMS_SOURCE_ARGUMENT(OptionType
SLATE_BEGIN_ARGS (SComboBox)
SLATE_DEFAULT_SLOT (FArguments, Content) SLATE_STYLE_ARGUMENT(FComboBoxStyle
Slot for this button's content (optional)
ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget SLATE_EVENT (FOnComboBoxOpening, OnComboBoxOpening) SLATE_ARGUMENT(TSharedPtr< SScrollBar >
Called when combo box is opened, before list is actually created.
ComboBoxStyle ItemStyle ContentPadding OptionsSource SLATE_EVENT (FOnSelectionChanged, OnSelectionChanged) SLATE_EVENT(FOnGenerateWidget
ComboBoxStyle SLATE_STYLE_ARGUMENT (FButtonStyle, ButtonStyle) SLATE_STYLE_ARGUMENT(FTableRowStyle
The visual style of the button part of the combo box (overrides ComboBoxStyle)
ComboBoxStyle ItemStyle SLATE_STYLE_ARGUMENT (FScrollBarStyle, ScrollBarStyle) SLATE_ATTRIBUTE(FMargin
Public Member Functions inherited from SComboButton
void Construct (const FArguments &InArgs)
Construct the widget from a declaration.
void SetButtonContentPadding (FMargin InPadding)
See the padding for button content.
void SetHasDownArrow (bool InHasArrowDown)
add/remove the expanding arrow.
void SetMenuContentWidgetToFocus (TWeakPtr< SWidget > InWidgetToFocusPtr)
void SetOnGetMenuContent (FOnGetContent InOnGetMenuContent)
See the OnGetMenuContent event.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign Method SLATE_ARGUMENT (bool, CollapseMenuOnParentFocus) SLATE_END_ARGS() 1 virtual void SetMenuContent(TSharedRef< SWidget > InContent) override
True if this combo's menu should be collapsed when our parent receives focus, false (default) otherwise.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable SLATE_ARGUMENT (bool, HasDownArrow) SLATE_ATTRIBUTE(FSlateColor
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign SLATE_ARGUMENT (EVerticalAlignment, VAlign) SLATE_ARGUMENT(TOptional< EPopupMethod >
Spawn a new window or reuse current window for this combo.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding SLATE_ATTRIBUTE (EMenuPlacement, MenuPlacement) SLATE_ARGUMENT(EHorizontalAlignment
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor SLATE_ATTRIBUTE (FSlateColor, ButtonColorAndOpacity) SLATE_ATTRIBUTE(FMargin
SLATE_BEGIN_ARGS (SComboButton)
ButtonStyle MenuContent OnMenuOpenChanged SLATE_EVENT (FOnComboBoxOpened, OnComboBoxOpened) SLATE_ARGUMENT(bool
ButtonStyle MenuContent SLATE_EVENT (FOnGetContent, OnGetMenuContent) SLATE_EVENT(FOnIsOpenChanged
Sets an event handler to generate a widget dynamically when the menu is needed.
ButtonStyle SLATE_NAMED_SLOT (FArguments, ButtonContent) SLATE_NAMED_SLOT(FArguments
Optional static menu content.
SLATE_STYLE_ARGUMENT (FComboButtonStyle, ComboButtonStyle) SLATE_STYLE_ARGUMENT(FButtonStyle
The visual style of the button (overrides ComboButtonStyle)
Protected Member Functions
virtual bool IsInteractable () const
FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Handle key presses that SListView ignores.
virtual bool SupportsKeyboardFocus () const override
Protected Member Functions inherited from SComboButton
FText GetFilteredToolTipText (TAttribute< FText > ToolTipText) const
Called to query the tool tip text for this widget, but will return an empty text when the menu is already open.
Private Member Functions
TSharedRef< ITableRow > GenerateMenuItemRow (OptionType InItem, const TSharedRef< STableViewBase > &OwnerTable)
Generate a row for the InItem in the combo box's list (passed in as OwnerTable).
virtual FReply OnButtonClicked () override
Handle clicking on the content menu.
FReply OnKeyDownHandler (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
void OnMenuOpenChanged (bool bOpen)
void OnSelectionChanged_Internal (NullableOptionType ProposedSelection, ESelectInfo::Type SelectInfo)
Invoked when the selection in the list changes.
void PlayPressedSound () const
Play the pressed sound.
void PlaySelectionChangeSound () const
Play the selection changed sound.
Private Attributes
bool bControllerInputCaptured
TSharedPtr< SBox > ComboBoxMenuContent
const FComboBoxStyle * ComboBoxStyle
The combo box style to use.
TSharedPtr< SComboListType > ComboListView
The ListView that we pop up; visualized the available options.
TSharedPtr< SScrollBar > CustomScrollbar
The Scrollbar used in the ListView.
bool EnableGamepadNavigationMode
const FTableRowStyle * ItemStyle
The item style to use.
FMargin MenuRowPadding
The padding around each menu row.
FOnComboBoxOpening OnComboBoxOpening
Delegate to invoke before the combo box is opening.
FOnGenerateWidget OnGenerateWidget
Delegate to invoke when we need to visualize an option as a widget.
FOnSelectionChanged OnSelectionChanged
Delegate that is invoked when the selected item in the combo box changes.
FSlateSound PressedSound
The Sound to play when the button is pressed.
NullableOptionType SelectedItem
The item currently selected in the combo box.
FSlateSound SelectionChangeSound
The Sound to play when the selection is changed.
Additional Inherited Members
Protected Attributes inherited from SComboButton
bool bIsFocusable
Can this button be focused?
SHorizontalBox::FSlot * ButtonContentSlot
Area where the button's content resides.
TWeakPtr< SWidget > ContentWidgetPtr
The content widget, if any, set by the user on creation.
const FSlateBrush * MenuBorderBrush
Brush to use to add a "menu border" around the drop-down content.
FMargin MenuBorderPadding
Padding to use to add a "menu border" around the drop-down content.
FOnComboBoxOpened OnComboBoxOpened
Delegate to execute when the combo list is opened.
TWeakPtr< SWidget > WidgetToFocusPtr
Detailed Description
template<typename OptionType>
class SComboBox< OptionType >
A combo box that shows arbitrary content.
Definition at line 96 of file SComboBox.h.
Member Typedef Documentation
FOnGenerateWidget
template<typename OptionType> typedef TSlateDelegates<OptionType>::FOnGenerateWidget SComboBox< OptionType >::FOnGenerateWidget
Delegate type used to generate widgets that represent Options.
Definition at line 106 of file SComboBox.h.
FOnSelectionChanged
template<typename OptionType> typedef TSlateDelegates<NullableOptionType>::FOnSelectionChanged SComboBox< OptionType >::FOnSelectionChanged
Definition at line 107 of file SComboBox.h.
ListTypeTraits
template<typename OptionType> typedef TListTypeTraits< OptionType > SComboBox< OptionType >::ListTypeTraits
Definition at line 100 of file SComboBox.h.
NullableOptionType
template<typename OptionType> typedef TListTypeTraits<OptionType>::NullableType SComboBox< OptionType >::NullableOptionType
Definition at line 101 of file SComboBox.h.
SComboListType
template<typename OptionType> typedef SListView< OptionType > SComboBox< OptionType >::SComboListType
Type of list used for showing menu options.
Definition at line 104 of file SComboBox.h.
Constructor & Destructor Documentation
SComboBox()
template<typename OptionType> SComboBox< OptionType >::SComboBox () inline
Definition at line 273 of file SComboBox.h.
References Auto.
Referenced by SLATE_BEGIN_ARGS().
Member Function Documentation
ClearItemsSource()
template<typename OptionType> void SComboBox< OptionType >::ClearItemsSource () inline
Clears current item source.
Definition at line 424 of file SComboBox.h.
References ComboListView.
ClearSelection()
template<typename OptionType> void SComboBox< OptionType >::ClearSelection () inline
Definition at line 349 of file SComboBox.h.
References ComboListView.
GenerateMenuItemRow()
template<typename OptionType> TSharedRef< ITableRow > SComboBox< OptionType >::GenerateMenuItemRow (OptionType InItem, const TSharedRef< STableViewBase > & OwnerTable) inline private
Generate a row for the InItem in the combo box's list (passed in as OwnerTable).
Do this by calling the user-specified OnGenerateWidget
Definition at line 553 of file SComboBox.h.
References ItemStyle, MenuRowPadding, NSLOCTEXT, OnGenerateWidget, and SNew.
Referenced by SLATE_ARGUMENT().
GetSelectedItem()
template<typename OptionType> NullableOptionType SComboBox< OptionType >::GetSelectedItem () inline
Returns
the item currently selected by the combo box.
Definition at line 406 of file SComboBox.h.
References SelectedItem.
Referenced by OnKeyDown().
InvalidateItemStyle()
template<typename OptionType> void SComboBox< OptionType >::InvalidateItemStyle () inline
Definition at line 400 of file SComboBox.h.
References Layout.
Referenced by SetItemStyle().
InvalidateStyle()
template<typename OptionType> void SComboBox< OptionType >::InvalidateStyle () inline
Definition at line 386 of file SComboBox.h.
References Layout.
Referenced by SetStyle().
IsInteractable()
template<typename OptionType> virtual bool SComboBox< OptionType >::IsInteractable () const inline protected virtual
Definition at line 545 of file SComboBox.h.
Referenced by OnKeyDown().
OnButtonClicked()
template<typename OptionType> virtual FReply SComboBox< OptionType >::OnButtonClicked () inline override private virtual
Handle clicking on the content menu.
Reimplemented from SComboButton.
Definition at line 622 of file SComboBox.h.
References ComboListView, TArray< InElementType, InAllocatorType >::Num(), SComboButton::OnButtonClicked(), OnComboBoxOpening, OnSelectionChanged_Internal(), and PlayPressedSound().
OnKeyDown()
template<typename OptionType> FReply SComboBox< OptionType >::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline override protected virtual
Handle key presses that SListView ignores.
Reimplemented from SComboButton.
Definition at line 441 of file SComboBox.h.
References EKeys::BackSpace, bControllerInputCaptured, ComboListView, EnableGamepadNavigationMode, TArrayView< InElementType, InSizeType >::Find(), FSlateApplication::Get(), FSlateApplication::GetNavigationActionFromKey(), FSlateApplication::GetNavigationDirectionFromKey(), GetSelectedItem(), FReply::Handled(), IsInteractable(), TArray< InElementType, InAllocatorType >::Num(), TArrayView< InElementType, InSizeType >::Num(), SComboButton::OnButtonClicked(), OnComboBoxOpening, SComboButton::OnKeyDown(), SWidget::OnKeyDown(), OnMenuOpenChanged(), OnSelectionChanged_Internal(), PlayPressedSound(), SetSelectedItem(), and FReply::SetUserFocus().
OnKeyDownHandler()
template<typename OptionType> FReply SComboBox< OptionType >::OnKeyDownHandler (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline private
Definition at line 643 of file SComboBox.h.
References ComboListView, EKeys::Enter, FReply::Handled(), TArray< InElementType, InAllocatorType >::Num(), OnSelectionChanged_Internal(), and FReply::Unhandled().
Referenced by SLATE_ARGUMENT().
OnMenuOpenChanged()
template<typename OptionType> void SComboBox< OptionType >::OnMenuOpenChanged (bool bOpen) inline private
Definition at line 575 of file SComboBox.h.
References bControllerInputCaptured, ComboListView, FSlateApplication::ForEachUser(), FSlateApplication::Get(), FSlateUser::IsWidgetInFocusPath(), SelectedItem, and FSlateUser::SetFocus().
Referenced by OnKeyDown(), and SLATE_ARGUMENT().
OnSelectionChanged_Internal()
template<typename OptionType> void SComboBox< OptionType >::OnSelectionChanged_Internal (NullableOptionType ProposedSelection, ESelectInfo::Type SelectInfo) inline private
Invoked when the selection in the list changes.
Definition at line 604 of file SComboBox.h.
References OnSelectionChanged, PlaySelectionChangeSound(), and SelectedItem.
Referenced by OnButtonClicked(), OnKeyDown(), OnKeyDownHandler(), and SLATE_ARGUMENT().
PlayPressedSound()
template<typename OptionType> void SComboBox< OptionType >::PlayPressedSound () const inline private
Play the pressed sound.
Definition at line 661 of file SComboBox.h.
References FSlateApplication::Get(), FSlateApplication::PlaySound(), and PressedSound.
Referenced by OnButtonClicked(), and OnKeyDown().
PlaySelectionChangeSound()
template<typename OptionType> void SComboBox< OptionType >::PlaySelectionChangeSound () const inline private
Play the selection changed sound.
Definition at line 667 of file SComboBox.h.
References FSlateApplication::Get(), FSlateApplication::PlaySound(), and SelectionChangeSound.
Referenced by OnSelectionChanged_Internal().
RefreshOptions()
template<typename OptionType> void SComboBox< OptionType >::RefreshOptions () inline
Requests a list refresh after updating options Call SetSelectedItem to update the selected item if required.
See also
SetSelectedItem
Definition at line 434 of file SComboBox.h.
References ComboListView.
SetEnableGamepadNavigationMode()
template<typename OptionType> void SComboBox< OptionType >::SetEnableGamepadNavigationMode (bool InEnableGamepadNavigationMode) inline
Definition at line 367 of file SComboBox.h.
References EnableGamepadNavigationMode.
SetItemsSource() [1/2]
template<typename OptionType> void SComboBox< OptionType >::SetItemsSource (const TArray< OptionType > * InListItemsSource) inline
Sets new item source.
Definition at line 412 of file SComboBox.h.
References ComboListView.
SetItemsSource() [2/2]
template<typename OptionType> void SComboBox< OptionType >::SetItemsSource (TSharedRef<::UE::Slate::Containers::TObservableArray< OptionType > > InListItemsSource) inline
Sets new item source.
Definition at line 418 of file SComboBox.h.
References ComboListView.
SetItemStyle()
template<typename OptionType> void SComboBox< OptionType >::SetItemStyle (const FTableRowStyle * InItemStyle) inline
Definition at line 391 of file SComboBox.h.
References InvalidateItemStyle(), and ItemStyle.
SetMaxHeight()
template<typename OptionType> void SComboBox< OptionType >::SetMaxHeight (float InMaxHeight) inline
Definition at line 372 of file SComboBox.h.
References ComboBoxMenuContent.
SetSelectedItem()
template<typename OptionType> void SComboBox< OptionType >::SetSelectedItem (NullableOptionType InSelectedItem) inline
Definition at line 354 of file SComboBox.h.
References ComboListView.
Referenced by OnKeyDown().
SetStyle()
template<typename OptionType> void SComboBox< OptionType >::SetStyle (const FComboBoxStyle * InStyle) inline
Definition at line 377 of file SComboBox.h.
References ComboBoxStyle, and InvalidateStyle().
SLATE_ARGUMENT() [1/5]
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method PressedSoundOverride HasDownArrow IsFocusable SComboBox< OptionType >::SLATE_ARGUMENT (bool , CollapseMenuOnParentFocus) const & inline
True if this combo's menu should be collapsed when our parent receives focus, false (default) otherwise.
Construct the widget from a declaration
Parameters
InArgs Declaration from which to construct the combo box
Definition at line 182 of file SComboBox.h.
References bControllerInputCaptured, check, ComboBoxMenuContent, ComboBoxStyle, ComboListView, SComboButton::Construct(), CustomScrollbar, EnableGamepadNavigationMode, GenerateMenuItemRow(), FStyleDefaults::GetNoBrush(), ItemStyle, MenuRowPadding, NSLOCTEXT, SNullWidget::NullWidget, OnComboBoxOpening, OnGenerateWidget, OnKeyDownHandler(), OnMenuOpenChanged(), OnSelectionChanged, OnSelectionChanged_Internal(), PressedSound, FLinearColor::Red, SAssignNew, SelectedItem, SelectionChangeSound, SComboButton::SetMenuContentWidgetToFocus(), SLATE_ARGUMENT(), SLATE_END_ARGS, SNew, and TSharedPtr< ObjectType, InMode >::ToSharedRef().
SLATE_ARGUMENT() [2/5]
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method PressedSoundOverride HasDownArrow SComboBox< OptionType >::SLATE_ARGUMENT (bool , EnableGamepadNavigationMode)
When false, directional keys will change the selection.
When true, ComboBox must be activated and will only capture arrow input while activated. When true, allows the combo box to receive keyboard focus
References EnableGamepadNavigationMode, and SLATE_ARGUMENT().
SLATE_ARGUMENT() [3/5]
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method SComboBox< OptionType >::SLATE_ARGUMENT (float , MaxListHeight)
The max height of the combo box menu.
The sound to play when the button is pressed (overrides ComboBoxStyle)
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [4/5]
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar SComboBox< OptionType >::SLATE_ARGUMENT (NullableOptionType , InitiallySelectedItem)
The option that should be selected when the combo box is first created.
References SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_ARGUMENT() [5/5]
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget CustomScrollbar Method PressedSoundOverride SComboBox< OptionType >::SLATE_ARGUMENT (TOptional< FSlateSound > , SelectionChangeSoundOverride)
The sound to play when the selection changes (overrides ComboBoxStyle)
When false, the down arrow is not generated and it is up to the API consumer to make their own visual hint that this is a drop down.
References SLATE_ARGUMENT().
SLATE_ATTRIBUTE()
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding SComboBox< OptionType >::SLATE_ATTRIBUTE (FSlateColor , ForegroundColor)
References SLATE_ATTRIBUTE(), and SLATE_ITEMS_SOURCE_ARGUMENT.
Referenced by SLATE_ATTRIBUTE(), and SLATE_STYLE_ARGUMENT().
SLATE_BEGIN_ARGS()
template<typename OptionType> SComboBox< OptionType >::SLATE_BEGIN_ARGS (SComboBox< OptionType >) inline
Definition at line 109 of file SComboBox.h.
References SComboBox().
SLATE_DEFAULT_SLOT()
template<typename OptionType> SComboBox< OptionType >::SLATE_DEFAULT_SLOT (FArguments , Content)
Slot for this button's content (optional)
References ComboBoxStyle.
SLATE_EVENT() [1/2]
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding OptionsSource OnGenerateWidget SComboBox< OptionType >::SLATE_EVENT (FOnComboBoxOpening , OnComboBoxOpening)
Called when combo box is opened, before list is actually created.
The custom scrollbar to use in the ListView
References CustomScrollbar, OnComboBoxOpening, SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_EVENT() [2/2]
template<typename OptionType> ComboBoxStyle ItemStyle ContentPadding OptionsSource SComboBox< OptionType >::SLATE_EVENT (FOnSelectionChanged , OnSelectionChanged)
References OnGenerateWidget, OnSelectionChanged, and SLATE_EVENT().
Referenced by SLATE_EVENT(), and SLATE_EVENT().
SLATE_STYLE_ARGUMENT() [1/2]
template<typename OptionType> ComboBoxStyle SComboBox< OptionType >::SLATE_STYLE_ARGUMENT (FButtonStyle , ButtonStyle)
The visual style of the button part of the combo box (overrides ComboBoxStyle)
References ItemStyle, and SLATE_STYLE_ARGUMENT().
Referenced by SLATE_STYLE_ARGUMENT(), and SLATE_STYLE_ARGUMENT().
SLATE_STYLE_ARGUMENT() [2/2]
template<typename OptionType> ComboBoxStyle ItemStyle SComboBox< OptionType >::SLATE_STYLE_ARGUMENT (FScrollBarStyle , ScrollBarStyle)
References SLATE_ATTRIBUTE(), and SLATE_STYLE_ARGUMENT().
SupportsKeyboardFocus()
template<typename OptionType> virtual bool SComboBox< OptionType >::SupportsKeyboardFocus () const inline override protected virtual
Definition at line 540 of file SComboBox.h.
References SComboButton::bIsFocusable.
Field Documentation
bControllerInputCaptured
template<typename OptionType> bool SComboBox< OptionType >::bControllerInputCaptured private
Definition at line 704 of file SComboBox.h.
Referenced by OnKeyDown(), OnMenuOpenChanged(), and SLATE_ARGUMENT().
ComboBoxMenuContent
template<typename OptionType> TSharedPtr<SBox> SComboBox< OptionType >::ComboBoxMenuContent private
Definition at line 706 of file SComboBox.h.
Referenced by SetMaxHeight(), and SLATE_ARGUMENT().
ComboBoxStyle
template<typename OptionType> const FComboBoxStyle* SComboBox< OptionType >::ComboBoxStyle private
The combo box style to use.
Definition at line 682 of file SComboBox.h.
Referenced by SetStyle(), SLATE_ARGUMENT(), and SLATE_DEFAULT_SLOT().
ComboListView
template<typename OptionType> TSharedPtr< SComboListType > SComboBox< OptionType >::ComboListView private
The ListView that we pop up; visualized the available options.
Definition at line 693 of file SComboBox.h.
Referenced by ClearItemsSource(), ClearSelection(), OnButtonClicked(), OnKeyDown(), OnKeyDownHandler(), OnMenuOpenChanged(), RefreshOptions(), SetItemsSource(), SetItemsSource(), SetSelectedItem(), and SLATE_ARGUMENT().
CustomScrollbar
template<typename OptionType> TSharedPtr< SScrollBar > SComboBox< OptionType >::CustomScrollbar private
The Scrollbar used in the ListView.
Definition at line 695 of file SComboBox.h.
Referenced by SLATE_ARGUMENT(), and SLATE_EVENT().
EnableGamepadNavigationMode
template<typename OptionType> bool SComboBox< OptionType >::EnableGamepadNavigationMode private
Definition at line 701 of file SComboBox.h.
Referenced by OnKeyDown(), SetEnableGamepadNavigationMode(), SLATE_ARGUMENT(), and SLATE_ARGUMENT().
ItemStyle
template<typename OptionType> const FTableRowStyle* SComboBox< OptionType >::ItemStyle private
The item style to use.
Definition at line 679 of file SComboBox.h.
Referenced by GenerateMenuItemRow(), SetItemStyle(), SLATE_ARGUMENT(), and SLATE_STYLE_ARGUMENT().
MenuRowPadding
template<typename OptionType> FMargin SComboBox< OptionType >::MenuRowPadding private
The padding around each menu row.
Definition at line 685 of file SComboBox.h.
Referenced by GenerateMenuItemRow(), and SLATE_ARGUMENT().
OnComboBoxOpening
template<typename OptionType> FOnComboBoxOpening SComboBox< OptionType >::OnComboBoxOpening private
Delegate to invoke before the combo box is opening.
Definition at line 697 of file SComboBox.h.
Referenced by OnButtonClicked(), OnKeyDown(), SLATE_ARGUMENT(), and SLATE_EVENT().
OnGenerateWidget
template<typename OptionType> FOnGenerateWidget SComboBox< OptionType >::OnGenerateWidget private
Delegate to invoke when we need to visualize an option as a widget.
Definition at line 699 of file SComboBox.h.
Referenced by GenerateMenuItemRow(), SLATE_ARGUMENT(), and SLATE_EVENT().
OnSelectionChanged
template<typename OptionType> FOnSelectionChanged SComboBox< OptionType >::OnSelectionChanged private
Delegate that is invoked when the selected item in the combo box changes.
Definition at line 689 of file SComboBox.h.
Referenced by OnSelectionChanged_Internal(), SLATE_ARGUMENT(), and SLATE_EVENT().
PressedSound
template<typename OptionType> FSlateSound SComboBox< OptionType >::PressedSound private
The Sound to play when the button is pressed.
Definition at line 673 of file SComboBox.h.
Referenced by PlayPressedSound(), and SLATE_ARGUMENT().
SelectedItem
template<typename OptionType> NullableOptionType SComboBox< OptionType >::SelectedItem private
The item currently selected in the combo box.
Definition at line 691 of file SComboBox.h.
Referenced by GetSelectedItem(), OnMenuOpenChanged(), OnSelectionChanged_Internal(), and SLATE_ARGUMENT().
SelectionChangeSound
template<typename OptionType> FSlateSound SComboBox< OptionType >::SelectionChangeSound private
The Sound to play when the selection is changed.
Definition at line 676 of file SComboBox.h.
Referenced by PlaySelectionChangeSound(), and SLATE_ARGUMENT().
The documentation for this class was generated from the following file:
SComboBox.h