Unreal Engine 5.6 C++ API: TThreadSingleton< T > Class Template Reference
TThreadSingleton< T > Class Template Reference
This a special version of singleton.
#include "ThreadSingleton.h"
Static Public Member Functions
static FORCEINLINE T & Get ()
static FORCEINLINE T & Get (TFunctionRef< FTlsAutoCleanup *()> CreateInstance)
static FORCEINLINE T * Inject (T *Instance)
static FORCEINLINE T * TryGet ()
Protected Member Functions
TThreadSingleton ()
Default constructor.
virtual ~TThreadSingleton ()
Static Protected Member Functions
static FTlsAutoCleanup * CreateInstance ()
Protected Attributes
const uint32 ThreadId
Thread ID of this thread singleton.
Static Private Member Functions
static uint32 & GetTlsSlot ()
Additional Inherited Members
Public Member Functions inherited from FTlsAutoCleanup
virtual ~FTlsAutoCleanup ()
Virtual destructor.
void Register ()
Register this instance to be auto-cleanup.
Detailed Description
template<class T>
class TThreadSingleton< T >
This a special version of singleton.
It means that there is created only one instance for each thread. Calling Get() method is thread-safe.
Definition at line 43 of file ThreadSingleton.h.
Constructor & Destructor Documentation
TThreadSingleton()
template<class T> TThreadSingleton< T >::TThreadSingleton () inline protected
Default constructor.
Definition at line 71 of file ThreadSingleton.h.
References ThreadId.
~TThreadSingleton()
template<class T> virtual TThreadSingleton< T >::~TThreadSingleton () inline protected virtual
Definition at line 75 of file ThreadSingleton.h.
References check, GetTlsSlot(), FAndroidTLS::GetTlsValue(), FGenericPlatformTLS::InvalidTlsSlot, and FAndroidTLS::SetTlsValue().
Member Function Documentation
CreateInstance()
template<class T> FTlsAutoCleanup * TThreadSingleton< T >::CreateInstance () inline static protected
Returns
a new instance of the thread singleton.
Definition at line 88 of file ThreadSingleton.h.
Referenced by Get().
Get() [1/2]
template<class T> FORCEINLINE T & TThreadSingleton< T >::Get () inline static
Returns
an instance of a singleton for the current thread.
Definition at line 101 of file ThreadSingleton.h.
References FORCEINLINE, and FThreadSingletonInitializer::Get().
Get() [2/2]
template<class T> FORCEINLINE T & TThreadSingleton< T >::Get (TFunctionRef< FTlsAutoCleanup *()> CreateInstance) inline static
Parameters
CreateInstance Function to call when a new instance must be created.
Returns
an instance of a singleton for the current thread.
Definition at line 110 of file ThreadSingleton.h.
References CreateInstance(), FORCEINLINE, and FThreadSingletonInitializer::Get().
GetTlsSlot()
template<class T> uint32 & TThreadSingleton< T >::GetTlsSlot () inline static private
Returns
TLS slot that holds a TThreadSingleton.
Definition at line 61 of file ThreadSingleton.h.
References FGenericPlatformTLS::InvalidTlsSlot.
Referenced by ~TThreadSingleton().
Inject()
template<class T> FORCEINLINE T * TThreadSingleton< T >::Inject (T * Instance) inline static
Returns
sets the TLS store to the instance and returns the previous instance.
Definition at line 126 of file ThreadSingleton.h.
References FORCEINLINE, FThreadSingletonInitializer::Inject(), and Instance.
TryGet()
template<class T> FORCEINLINE T * TThreadSingleton< T >::TryGet () inline static
Returns
pointer to an instance of a singleton for the current thread. May be nullptr, prefer to use access by reference
Definition at line 118 of file ThreadSingleton.h.
References FORCEINLINE, and FThreadSingletonInitializer::TryGet().
Field Documentation
ThreadId
template<class T> const uint32 TThreadSingleton< T >::ThreadId protected
Thread ID of this thread singleton.
Definition at line 94 of file ThreadSingleton.h.
Referenced by TThreadSingleton().
The documentation for this class was generated from the following file:
ThreadSingleton.h