Unreal Engine 5.6 C++ API: FRigVMTreeTask Class Reference
FRigVMTreeTask Class Reference
A Task is a small piece of work that needs to be performed.
#include "RigVMTreeToolkitTask.h"
Public Types
typedef FRigVMTreeElement Super
Public Member Functions
virtual bool Execute (const TSharedRef< FRigVMTreePhase > &InPhase)
virtual TArray< FString > GetAffectedNodes () const
virtual URigVMBlueprint * GetBlueprint (const TSharedRef< FRigVMTreePhase > &InPhase) const
virtual FName GetType () const override
virtual bool IsOfType (const FName &InType) const override
bool IsUndoEnabled () const
virtual bool RequiresRefresh () const
virtual bool RequiresUndo () const
void SetEnableUndo (bool bEnabled)
TSharedPtr< FRigVMTreeTask > ToSharedPtr () const
TSharedRef< FRigVMTreeTask > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename... Types>
static TSharedRef< FRigVMTreeTask > Create (Types... Args)
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeTask"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Private Attributes
bool bEnableUndo = false
Friends
template<typename T>
TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeTask > &InElement)
template<typename T>
const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeTask > &InElement)
Additional Inherited Members
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A Task is a small piece of work that needs to be performed.
Definition at line 16 of file RigVMTreeToolkitTask.h.
Member Typedef Documentation
Super
typedef FRigVMTreeElement FRigVMTreeTask::Super
Definition at line 19 of file RigVMTreeToolkitTask.h.
Member Function Documentation
Create()
template<typename... Types> TSharedRef< FRigVMTreeTask > FRigVMTreeTask::Create (Types... Args) inline static
Definition at line 19 of file RigVMTreeToolkitTask.h.
Execute()
virtual bool FRigVMTreeTask::Execute (const TSharedRef< FRigVMTreePhase > & InPhase) inline virtual
Reimplemented in FRigVMCompileBlueprintTask, FRigVMSwapAssetReferenceTask, FRigVMSwapFunctionTask, and FRigVMTreeLoadPackageForNodeTask.
Definition at line 21 of file RigVMTreeToolkitTask.h.
References Execute().
Referenced by Execute().
GetAffectedNodes()
virtual TArray< FString > FRigVMTreeTask::GetAffectedNodes () const inline virtual
Reimplemented in FRigVMSwapFunctionTask.
Definition at line 41 of file RigVMTreeToolkitTask.h.
GetBlueprint()
virtual URigVMBlueprint * FRigVMTreeTask::GetBlueprint (const TSharedRef< FRigVMTreePhase > & InPhase) const inline virtual
Reimplemented in FRigVMSwapFunctionTask.
Definition at line 26 of file RigVMTreeToolkitTask.h.
GetType()
virtual FName FRigVMTreeTask::GetType () const inline override virtual
Reimplemented from FRigVMTreeElement.
Reimplemented in FRigVMCompileBlueprintTask, and FRigVMTreeLoadPackageForNodeTask.
Definition at line 19 of file RigVMTreeToolkitTask.h.
IsOfType()
virtual bool FRigVMTreeTask::IsOfType (const FName & InType) const inline override virtual
Reimplemented from FRigVMTreeElement.
Reimplemented in FRigVMCompileBlueprintTask, and FRigVMTreeLoadPackageForNodeTask.
Definition at line 19 of file RigVMTreeToolkitTask.h.
IsUndoEnabled()
bool FRigVMTreeTask::IsUndoEnabled () const inline
Definition at line 51 of file RigVMTreeToolkitTask.h.
References bEnableUndo.
RequiresRefresh()
virtual bool FRigVMTreeTask::RequiresRefresh () const inline virtual
Reimplemented in FRigVMCompileBlueprintTask, FRigVMSwapAssetReferenceTask, FRigVMSwapFunctionTask, and FRigVMTreeLoadPackageForNodeTask.
Definition at line 31 of file RigVMTreeToolkitTask.h.
RequiresUndo()
virtual bool FRigVMTreeTask::RequiresUndo () const inline virtual
Reimplemented in FRigVMSwapAssetReferenceTask, and FRigVMSwapFunctionTask.
Definition at line 36 of file RigVMTreeToolkitTask.h.
SetEnableUndo()
void FRigVMTreeTask::SetEnableUndo (bool bEnabled) inline
Definition at line 46 of file RigVMTreeToolkitTask.h.
References bEnableUndo.
ToSharedPtr()
TSharedPtr< FRigVMTreeTask > FRigVMTreeTask::ToSharedPtr () const inline
Definition at line 19 of file RigVMTreeToolkitTask.h.
ToSharedRef()
TSharedRef< FRigVMTreeTask > FRigVMTreeTask::ToSharedRef () const inline
Definition at line 19 of file RigVMTreeToolkitTask.h.
Friends And Related Symbol Documentation
Cast
template<typename T> TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeTask > & InElement) friend
Definition at line 19 of file RigVMTreeToolkitTask.h.
References FRigVMTreeElement::FRigVMTreeElement().
CastChecked
template<typename T> const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeTask > & InElement) friend
Definition at line 19 of file RigVMTreeToolkitTask.h.
Field Documentation
bEnableUndo
bool FRigVMTreeTask::bEnableUndo = false private
Definition at line 57 of file RigVMTreeToolkitTask.h.
Referenced by IsUndoEnabled(), and SetEnableUndo().
Type
const FLazyName FRigVMTreeTask::Type = FLazyName(TEXT("FRigVMTreeTask")) inline static
Definition at line 19 of file RigVMTreeToolkitTask.h.
The documentation for this class was generated from the following file:
RigVMTreeToolkitTask.h