Unreal Engine 5.6 C++ API: FWorldPartitionReplayStreamingSource Struct Reference
FWorldPartitionReplayStreamingSource Struct Reference
#include "WorldPartitionReplay.h"
Public Member Functions
FWorldPartitionReplayStreamingSource ()
FWorldPartitionReplayStreamingSource (const FWorldPartitionStreamingSource &InStreamingSource)
FWorldPartitionReplayStreamingSource (FName InName, const FVector &InLocation, const FRotator &InRotation, EStreamingSourceTargetState InTargetState, bool bInBlockOnSlowLoading, EStreamingSourcePriority InPriority, FVector InVelocity)
Public Member Functions inherited from FWorldPartitionStreamingSource
FWorldPartitionStreamingSource ()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FWorldPartitionStreamingSource (const FWorldPartitionStreamingSource &Other)=default
FWorldPartitionStreamingSource (FName InName, const FVector &InLocation, const FRotator &InRotation, EStreamingSourceTargetState InTargetState, bool bInBlockOnSlowLoading, EStreamingSourcePriority InPriority, bool bRemote, FVector InVelocity=FVector::Zero())
FWorldPartitionStreamingSource (FWorldPartitionStreamingSource &&Other)=default
FBox CalcBounds (float InGridLoadingRange, FName InGridName, bool bCalcIn2D=false) const
Returns a box encapsulating all shapes.
void ForEachShape (float InGridLoadingRange, bool bInProjectIn2D, TFunctionRef< void(const FSphericalSector &)> InOperation) const
Helper method that iterates over all shapes.
void ForEachShape (float InGridLoadingRange, FName InGridName, bool bInProjectIn2D, TFunctionRef< void(const FSphericalSector &)> InOperation) const
Helper method that iterates over all shapes affecting a specific grid.
PRAGMA_ENABLE_DEPRECATION_WARNINGS FColor GetDebugColor () const
uint32 GetHash (bool bInclude3DInformation=true) const
FWorldPartitionStreamingSource & operator= (const FWorldPartitionStreamingSource &Other)=default
FWorldPartitionStreamingSource & operator= (FWorldPartitionStreamingSource &&Other)=default
FString ToString () const
UE_DEPRECATED (5.4, "TargetHLODLayers is depredcated, use TargetGrids instead.") TSet< FSoftObjectPath > TargetHLODLayers
When set, this will change how this streaming source is applied to the provided HLODLayers based on the TargetBehavior.
void UpdateHash ()
Friends
FArchive & operator<< (FArchive &Ar, FWorldPartitionReplayStreamingSource &StreamingSource)
Additional Inherited Members
Static Public Member Functions inherited from FWorldPartitionStreamingSource
static int32 GetLocationQuantization ()
static int32 GetRotationQuantization ()
Data Fields inherited from FWorldPartitionStreamingSource
bool bBlockOnSlowLoading
Whether this source will be considered when world partition detects slow loading and waits for cell streaming to complete.
bool bForce2D
If true, this streaming source will force intersecting cells in 2D.
bool bRemote
If true, this streaming source is from a remote session.
bool bReplay
If true, this streaming source is from a replay recording.
bool bUseVelocityContributionToCellsSorting
Use velocity contribution to streaming cells priority streaming.
FColor DebugColor
Color used for debugging.
FVector Location
Source location.
FName Name
Source unique name.
EStreamingSourcePriority Priority
Streaming source priority.
FRotator Rotation
Source orientation (can impact streaming cell prioritization).
TArray< FStreamingSourceShape > Shapes
Source internal shapes.
EStreamingSourceTargetBehavior TargetBehavior
Defines how TargetGrids/TargetHLODLayers will be applied to this streaming source.
TSet< FName > TargetGrids
When set, this will change how this streaming source is applied to the provided runtime streaming grids based on the TargetBehavior.
EStreamingSourceTargetState TargetState
Target streaming state.
FVector Velocity
Source velocity (computed automatically).
Detailed Description
Definition at line 11 of file WorldPartitionReplay.h.
Constructor & Destructor Documentation
FWorldPartitionReplayStreamingSource() [1/3]
FWorldPartitionReplayStreamingSource::FWorldPartitionReplayStreamingSource () inline
Definition at line 13 of file WorldPartitionReplay.h.
Referenced by FWorldPartitionReplayStreamingSource(), and operator<<.
FWorldPartitionReplayStreamingSource() [2/3]
FWorldPartitionReplayStreamingSource::FWorldPartitionReplayStreamingSource (const FWorldPartitionStreamingSource & InStreamingSource) inline
Definition at line 18 of file WorldPartitionReplay.h.
References FWorldPartitionReplayStreamingSource(), FWorldPartitionStreamingSource::FWorldPartitionStreamingSource(), FWorldPartitionStreamingSource::bBlockOnSlowLoading, FWorldPartitionStreamingSource::Location, FWorldPartitionStreamingSource::Name, FWorldPartitionStreamingSource::Priority, FWorldPartitionStreamingSource::Rotation, FWorldPartitionStreamingSource::TargetState, and FWorldPartitionStreamingSource::Velocity.
FWorldPartitionReplayStreamingSource() [3/3]
FWorldPartitionReplayStreamingSource::FWorldPartitionReplayStreamingSource (FName InName, const FVector & InLocation, const FRotator & InRotation, EStreamingSourceTargetState InTargetState, bool bInBlockOnSlowLoading, EStreamingSourcePriority InPriority, FVector InVelocity) inline
Definition at line 23 of file WorldPartitionReplay.h.
References FWorldPartitionStreamingSource::FWorldPartitionStreamingSource(), FWorldPartitionStreamingSource::bReplay, FVector, and InName.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FWorldPartitionReplayStreamingSource & StreamingSource) friend
References FWorldPartitionReplayStreamingSource(), and Ar.
The documentation for this struct was generated from the following file:
WorldPartitionReplay.h