Unreal Engine 5.6 C++ API: FRemoteTransactionId Struct Reference
FRemoteTransactionId Struct Reference
#include "RemoteExecutor.h"
Public Member Functions
FRemoteTransactionId ()=default
constexpr FRemoteTransactionId (uint32 InId)
uint32 GetIdNumber () const
bool IsValid () const
bool operator!= (const FRemoteTransactionId &Rhs) const
void operator= (FRemoteTransactionId Other)
bool operator== (const FRemoteTransactionId &Rhs) const
FString ToString () const
Static Public Member Functions
static FRemoteTransactionId Invalid ()
Private Attributes
uint32 Id = 0
Friends
FArchive & operator<< (FArchive &Ar, FRemoteTransactionId &Id)
Detailed Description
Definition at line 13 of file RemoteExecutor.h.
Constructor & Destructor Documentation
FRemoteTransactionId() [1/2]
FRemoteTransactionId::FRemoteTransactionId () default
Referenced by Invalid(), operator!=(), operator<<, operator=(), and operator==().
FRemoteTransactionId() [2/2]
FRemoteTransactionId::FRemoteTransactionId (uint32 InId) inline explicit constexpr
Definition at line 16 of file RemoteExecutor.h.
References Id.
Member Function Documentation
GetIdNumber()
uint32 FRemoteTransactionId::GetIdNumber () const inline
Definition at line 29 of file RemoteExecutor.h.
References Id.
Invalid()
FRemoteTransactionId FRemoteTransactionId::Invalid () inline static
Definition at line 21 of file RemoteExecutor.h.
References FRemoteTransactionId().
IsValid()
bool FRemoteTransactionId::IsValid () const inline
Definition at line 33 of file RemoteExecutor.h.
References Id.
operator!=()
bool FRemoteTransactionId::operator!= (const FRemoteTransactionId & Rhs) const inline
Definition at line 27 of file RemoteExecutor.h.
References FRemoteTransactionId(), and Id.
operator=()
void FRemoteTransactionId::operator= (FRemoteTransactionId Other) inline
Definition at line 41 of file RemoteExecutor.h.
References FRemoteTransactionId(), Id, and Other.
operator==()
bool FRemoteTransactionId::operator== (const FRemoteTransactionId & Rhs) const inline
Definition at line 26 of file RemoteExecutor.h.
References FRemoteTransactionId(), and Id.
ToString()
FString FRemoteTransactionId::ToString () const inline
Definition at line 37 of file RemoteExecutor.h.
References Id.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FRemoteTransactionId & Id) friend
References FRemoteTransactionId(), Ar, and Id.
Field Documentation
Id
uint32 FRemoteTransactionId::Id = 0 private
Definition at line 49 of file RemoteExecutor.h.
Referenced by FRemoteTransactionId(), GetIdNumber(), IsValid(), operator!=(), operator<<, operator=(), operator==(), and ToString().
The documentation for this struct was generated from the following file:
RemoteExecutor.h